### ISSUE TITLE
Windows installation experience is subpar

### ISSUE THREAD

**Issue by mmrath** [bazelbuild/bazel#10003]
### Description of the problem / feature request:

The current windows installation experience is subpar. I was trying to get some internal projects to Bazel to show the wider team. I generally use MacOS but in my company Windows is default. When I tried to install on windows in company environment I was stumbled upon too many issue. Reporting some important once here. 

1. Dependency on MSYS, some of the dev don't even know what it is. And in my company environment you cannot install anything apart from `C:\Installs` and regular `Program Files` directory. Need to go through infra and security for any exceptions.
2.  If some how I install MSYS the next problem is to control Bazel extract directory from where bazel server runs. Any executable will need to be on `C:\Installs` for it to execute, but bazel's work directory is not there
 

### Feature requests: what underlying problem are you trying to solve with this feature?

One click installer which installs everything to get started with Bazel

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Install Bazel on windows as per documentation

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

Not able to install bazel

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

NA

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

NA

###  Have you found anything relevant by searching the web?

Yes but solution is not good enough for large scale deployment

### Any other information, logs, or outputs that you want to share?

NA

**Comment by pauldraper** [comment]
FYI circa 0.24.0, Bazel itself no longer requires MSYS.

Many rules however do rely on POSIX utilities.

**Comment by mmrath** [comment]
@pauldraper  but Bazel documentation mentions MSYS2 as prerequisite.

**Comment by laszlocsomor** [comment]
@mmrath : You're right, the docs are stale, let me update them. Bazel 1.0 doesn't need MSYS anymore unless you build or run targets that need Bash (e.g. `genrule` and `sh_test`). The only hard requirement is the Visual C++ Redistributble DLLs.

Re: configuring output directories: I agree a one-click installer would be easier, but in the meantime you can use certain flags to control this:
- [--output_user_root](https://docs.bazel.build/versions/master/command-line-reference.html#flag--output_user_root) flag defines the root directory where Bazel will extract its embedded files and where it will write the output by default.
- [--output_base](https://docs.bazel.build/versions/master/command-line-reference.html#flag--output_base) flag sets the output directory. 

Demo:
```
C:\>mkdir foo

C:\>cd foo

C:\foo>type nul > WORKSPACE

C:\foo>bazel --ignore_all_rc_files --output_user_root=c:\tmp\foo-out\out-user-root --output_base=c:\tmp\foo-out\out-base info
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to 'C:/tmp/foo-out/out-base/command.profile.gz'
bazel-bin: C:/tmp/foo-out/out-base/execroot/__main__/bazel-out/x64_windows-fastbuild/bin
bazel-genfiles: C:/tmp/foo-out/out-base/execroot/__main__/bazel-out/x64_windows-fastbuild/bin
bazel-testlogs: C:/tmp/foo-out/out-base/execroot/__main__/bazel-out/x64_windows-fastbuild/testlogs
character-encoding: file.encoding = ISO-8859-1, defaultCharset = ISO-8859-1
command_log: C:/tmp/foo-out/out-base/command.log
committed-heap-size: 1069MB
execution_root: C:/tmp/foo-out/out-base/execroot/__main__
gc-count: 2
gc-time: 14ms
install_base: C:/tmp/foo-out/out-user-root/install/e8edfeb4e263890fa5ef1045034f3bd4
java-home: C:/tmp/foo-out/out-user-root/install/e8edfeb4e263890fa5ef1045034f3bd4/_embedded_binaries/embedded_tools/jdk
java-runtime: OpenJDK Runtime Environment (build 11.0.2+7-LTS) by Azul Systems, Inc.
java-vm: OpenJDK 64-Bit Server VM (build 11.0.2+7-LTS, mixed mode) by Azul Systems, Inc.
max-heap-size: 17091MB
output_base: C:/tmp/foo-out/out-base
output_path: C:/tmp/foo-out/out-base/execroot/__main__/bazel-out
package_path: %workspace%
release: release 1.0.0
repository_cache: C:/tmp/foo-out/out-user-root/cache/repos/v1
server_log: C:/tmp/foo-out/out-base/java.log.laszlocsomor2-w.laszlocsomor.log.java.20191015-134442.11376
server_pid: 11376
used-heap-size: 136MB
workspace: C:/foo
```

If you set `--output_user_root` without setting `--output_base`, then the output base will be under the output_user_root. If you set `--output_base` without setting `--output_user_root`, then the output user root (and hence the extraction directory) will be under its default location.

To deploy this at scale, you can add the flags to one of the [bazelrc files](https://docs.bazel.build/versions/master/guide.html#bazelrc).

**Comment by laszlocsomor** [comment]
(I used `--ignore_all_rc_files` in my demo to avoid picking up my own user rc file.)

**Comment by mmrath** [comment]
@laszlocsomor Thank you. Flags you mentioned are working well.

**Comment by laszlocsomor** [comment]
Great! I documented them here: https://docs.bazel.build/versions/master/install-windows.html#4-optional-configure-output-directories and here: https://docs.bazel.build/versions/master/install-windows.html#5-optional-install-compilers-and-language-runtimes
