### ISSUE TITLE
Remove native cc_proto_library

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/bazel#10006]
This breaking change will implement `cc_proto_library` in Starlark and remove the native version.

Design doc:
https://docs.google.com/document/d/1u95vlQ1lWeQNR4bUw5T4cMeHTGJla2_e1dHHx7v4Dvg/edit#

Note that we do not have a timelime when the flag will be flipped.

**Comment by hlopko** [comment]
(I presume this is the tracking issue for the whole effort, and the issue for the actual incompatible flag will be created separately, right?)

**Comment by Yannic** [comment]
Exactly.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
