### ISSUE TITLE
Remove native Protobuf rules

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/bazel#10005]
This is the ☔️-bug for removing the native versions of everything related to Protocol Buffers from Bazel.

Blocked on:
  - [x] bazelbuild/rules_proto#6
  - [x] bazelbuild/bazel#10006
  - [x] bazelbuild/bazel#10484
  - [x] bazelbuild/bazel#7514
  - [x] bazelbuild/rules_proto#58
  - [x] bazelbuild/bazel#12037 
  - [x] bazelbuild/bazel#12431
  - [ ] bazelbuild/bazel#12484 
  - [x] bazelbuild/bazel#12486

**Comment by jin** [comment]
cc @lberki

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
