### ISSUE TITLE
`JavaRuntimeInfo.java_executable_runfiles_path` does not respect `--java_launcher`

### ISSUE THREAD

**Issue by kevingessner** [bazelbuild/bazel#10019]
### Description of the problem / feature request:

The `JavaRuntimeInfo` provider has fields for accessing the java binary that should be used to execute built java artifacts, `java_executable_runfiles_path` and `java_home_runfiles_path`.  In my reading, those should be changed when `--java_launcher` specifies "".  However, those fields are unchanged by `--java_launcher`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. apply this diff: https://gist.github.com/kevingessner/e99fbc80a6fdded8b8902ca64c09b205
2. run `bazel test src/test/java/com/google/devtools/build/lib:java-rules-tests --test_output=errors`

The new test fails:

```
There was 1 failure:
1) testJavaRuntimeProviderJavaLauncher(com.google.devtools.build.lib.rules.java.JavaSkylarkApiTest)
expected to start with: /a/launcher
but was               : /foo/bar/bin/java
        at com.google.devtools.build.lib.rules.java.JavaSkylarkApiTest.testJavaRuntimeProviderJavaLauncher(JavaSkylarkApiTest.java:196)
```

It fails on 0.29.1, 1.0.0, and master@0c05851b40caa1d826c1ec8eb24b57dd727ea90f.

Note the TODO: I'm not clear if both fields should be affected by `--java_launcher` or just one.

### What operating system are you running Bazel on?

centos 7

### What's the output of `bazel info release`?

This fails on 0.29.1, 1.0.0, and master@0c05851b40caa1d826c1ec8eb24b57dd727ea90f

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/bazelbuild/bazel
0c05851b40caa1d826c1ec8eb24b57dd727ea90f
0c05851b40caa1d826c1ec8eb24b57dd727ea90f

###  Have you found anything relevant by searching the web?

Nope

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
