### ISSUE TITLE
Print Bazel Estimate for RAM and CPUs

### ISSUE THREAD

**Issue by cancan101** [bazelbuild/bazel#1001]
The docs specify:

> By default Bazel will estimate amount of RAM and number of CPU cores directly from system configuration

I suggest adding an option to log out what bazel estimates for these two values

**Comment by jmmv** [comment]
I don't think we should pollute the console output with this information, but adding some entries to the `java.log` would certainly be beneficial.

@susinmotion has been doing work on this area and I think we already have some statements in this area. Could you confirm please and maybe add some extra log messages?

**Comment by susinmotion** [comment]
Marking as fixed with the above change.
