### ISSUE TITLE
Bazel CI: Redundant log output of Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#10017]
Since the nigtly build on last Wednesday https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1226#eabedf8c-dfe3-4112-8a05-37394c388cd6, there are some redundant output in the test log of Bazel:
```

(02:08:44) INFO: 132 processes: 132 remote cache hit.
--
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | //skydoc:common_test                                            (cached) PASSED in 0.2s
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | //skydoc:load_extractor_test                                    (cached) PASSED in 0.2s
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | (02:08:44) INFO: Build completed successfully, 67 total actions
  | //skydoc:macro_extractor_test                                   (cached) PASSED in 0.2s

```

This didn't happen in the previous nightly build: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1225#6fb19699-95f5-4ea6-a2e1-1471dbf05c55
And this doesn't happen with Bazel 1.0, either: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1225#6fb19699-95f5-4ea6-a2e1-1471dbf05c55

**Comment by meteorcloudy** [comment]
@aehlig Do you think it's related to https://github.com/bazelbuild/bazel/commit/c87cc91007aa89e33e95a153c448f8b9fc91fa2f ?

**Comment by aehlig** [comment]
> @aehlig Do you think it's related to https://github.com/bazelbuild/bazel/commit/c87cc91007aa89e33e95a153c448f8b9fc91fa2f ?

Fix submitted as https://github.com/bazelbuild/bazel/commit/d3283b15ef938d3d156e300f76588d8875e26272


-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by meteorcloudy** [comment]
Nice, thank you!
