### ISSUE TITLE
Bazel website, navigation: "Rules" section disappeared

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#10012]
### Description of the problem / feature request:

The Bazel website's left navigation pane used to have a "Rules" section. It was still there with version 0.29.1, but is missing with master and 1.0.0

**Comment by laszlocsomor** [comment]
With 1.0 (and master) this section moved into "Installing and Using Bazel" > "Rules".

**Comment by laszlocsomor** [comment]
I think the Rules documentation is less discoverable with the 1.0 layout than it used to be.

Origin: 40a8f0d2c802946ebc3e757c6b07cb6c9f14353e

I realize the motivation was to consolidate language-specific docs to a single page, rather than having submenu items for them. Removing all submenu items would've left the "Rules" section with just "Build Encyclopedia", or just an "Overview" page. I guess that's why @laurentlb decided to remove the section and make "Rules" itself a submenu item. Is that correct, Laurent?

**Comment by laurentlb** [comment]
Yes. There's no need for a section if there's only one link under it.

I'm happy to discuss changes to make it more visible, if you think it's a problem. I've added links to that page from a few other places.
