### ISSUE TITLE
Provide more helpful information if a cache key is missing with builds-without-the-bits

### ISSUE THREAD

**Issue by phb** [bazelbuild/bazel#10025]
### Description of the problem / feature request:

When running with build --remote_download_toplevel or build --remote_download_minimal, if a cache key is missing (It happens to us regularly even though we don't evict files, I have not been able to figure out a reproducer)
We get the message:
"failed due to unexpected I/O exception: Failed to fetch file with hash 'eb0c1584917af56e754ba6268479fb6312dfbca19fde95042c199748d0b86ed5' because it does not exist remotely. --experimental_remote_outputs=minimal does not work if your remote cache evicts files during builds."

It would be really helpful to get more information about what that key represents (filename, target, etc?) as our workaround generally involves making a dummy change that will re-populate the cache.

### Feature requests: what underlying problem are you trying to solve with this feature?

Trying to work around the fact that bazel is unable to re-populate missing cache keys.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Don't have one. But the issue is about improving the error message.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

1.0.0rc2

**Comment by buchgr** [comment]
Is your request to display the output file name that could not be fetched? That sounds reasonable to me. An output file will allow you uniquely identify an action. 

> It happens to us regularly even though we don't evict files, I have not been able to figure out a reproducer

Bazel only displays this message when a download attempt returns a 404. Are you 100% certain that output's are never evicted?

**Comment by phb** [comment]
Yes the filename would be ideal.

No eviction, but it's backed by S3, but it's eventually consistent in some scenarios so I suspect that might be what is happening.

**Comment by buchgr** [comment]
@phb are you pointing bazel directly at s3 or do you have a cache in front of it?

**Comment by phb** [comment]
Hi @buchgr,

Just directly to S3 via https://github.com/Asana/bazels3cache. I've configured the prior to not have any filesize restrictions, no in memory cache and a few other settings that I can't access from my current computer.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by coeuvre** [comment]
Hi Gowroji, sorry for the confusion but I would like to keep it opened and address it during my effort of improving BwoB.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 6.4.0 RC1](https://releases.bazel.build/6.4.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!
