### ISSUE TITLE
Bazel CI: rules_haskell is failing in downstream due to cache poisoning

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#10038]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1238#4455603b-b8b0-46a2-98a0-6fae47c3c82a

This happened before, which was fixed by [updating the cache poison key](https://github.com/bazelbuild/continuous-integration/commit/2e04e41a934a64e69473d2e80899d8c11958083f), but I think it's better to figure out the underlying problem.

**Comment by meisterT** [comment]
Note that the cache key update did only help once.

**Comment by buchgr** [comment]
What makes you think it's cache poisoning?

**Comment by meteorcloudy** [comment]
Because I tried to reproduce on a VM and I can only reproduce with remote caching. The same failure happened before, it was green for a while after I updated the cache key https://github.com/bazelbuild/continuous-integration/commit/2e04e41a934a64e69473d2e80899d8c11958083f, now it appears again.

**Comment by buchgr** [comment]
@meteorcloudy you are able to reproduce it? If so, how?
 I looked into the problem and my best guess is that it is indeed cache poisoning. I suspect that the library run path on the test binary is wrong. I don't know for sure though would need to have access to the file.

**Comment by meteorcloudy** [comment]
I'll send you the steps to reproduce this.

**Comment by buchgr** [comment]
@meteorcloudy and I found the issue.

rules_haskell stores absolute runpaths in the ELF binary. It so happens that it's also a path to the output base which depends on the machine and the bazel version.

 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../../_solib_k8/_U_S_Stests_Sbinary-linkstatic-flag_CHsLib___Utests_Sbinary-linkstatic-flag:$ORIGIN/../../_solib_k8:$ORIGIN/../../_solib_k8/_U@rules_Uhaskell_S_Shaskell_Ctoolchain-libraries___Uexternal_Srules_Uhaskell_Ughc_Ulinux_Uamd64_Slib_Sbase-4.12.0.0:$ORIGIN/../../_solib_k8/_U@rules_Uhaskell_S_Shaskell_Ctoolchain-libraries___Uexternal_Srules_Uhaskell_Ughc_Ulinux_Uamd64_Slib_Sinteger-gmp-1.0.2.0:$ORIGIN/../../_solib_k8/_U@rules_Uhaskell_S_Shaskell_Ctoolchain-libraries___Uexternal_Srules_Uhaskell_Ughc_Ulinux_Uamd64_Slib_Sghc-prim-0.5.3:$ORIGIN/../../_solib_k8/_U@rules_Uhaskell_S_Shaskell_Ctoolchain-libraries___Uexternal_Srules_Uhaskell_Ughc_Ulinux_Uamd64_Slib_Srts:**/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/bb079dd87775c7086715c97a1047d8b2/execroot/rules_haskell/external/rules_haskell_ghc_linux_amd64/bin/../lib/rts**]

I'll file an issue with rules_haskell. Let's disable remote caching for rules_haskell until this is fixed.

**Comment by buchgr** [comment]
I believe this can be closed.
