### ISSUE TITLE
Unable to build bazel from source on ppc64le

### ISSUE THREAD

**Issue by clnperez** [bazelbuild/bazel#10049]
### Description of the problem / feature request:
When building bazel from master, I'm getting the following error:
```
+ bazel --server_javabase=/usr/ build --sandbox_debug -s --verbose_failures --host_javabase=@local_jdk//:jdk //src:bazel
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
ERROR: /root/workspace/bazel/src/main/res/winsdk_configure.bzl:39:1: file '@bazel_tools//tools/cpp:cc_configure.bzl' does not contain symbol 'MSVC_ENVVARS'
ERROR: /root/workspace/bazel/src/main/res/winsdk_configure.bzl:172:20: Traceback (most recent call last):
	File "/root/workspace/bazel/src/main/res/winsdk_configure.bzl", line 169
		repository_rule(implementation = _impl, local = Tr..., ...))
	File "/root/workspace/bazel/src/main/res/winsdk_configure.bzl", line 172, in repository_rule
		list(MSVC_ENVVARS)
	File "/root/workspace/bazel/src/main/res/winsdk_configure.bzl", line 172, in list
		MSVC_ENVVARS
global variable 'MSVC_ENVVARS' is referenced before assignment.
ERROR: error loading package '': Extension file 'src/main/res/winsdk_configure.bzl' has errors
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
```
# request a free power system from https://osuosl.org/services/powerdev/request_hosting/ if you don't have power access
$ git clone git@github.com:clnperez/dockerfiles.git && cd dockerfiles 
$ docker build -f bazel/Dockerfile.bionic.master -t bazel:master_test bazel/

```

### What operating system are you running Bazel on?

ubuntu 18.04 (bionic) 

### What's the output of `bazel info release`?

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

master

###  Have you found anything relevant by searching the web?
https://github.com/bazelbuild/bazel/issues/9373
looks similar, and maybe i'm misunderstanding the workaround, but I couldn't get a build using the hints there

**Comment by irengrig** [comment]
Hi @clnperez , thank you for reporting the issue.
Yes I think #9373 is related, specifically: "So, in order to build 0.29.1, you need to use a binary that includes the correct bazel_tools internally".
Sorry I can not understand it about the docker image - which binary of Bazel does it use?
We just released 1.1.0: https://github.com/bazelbuild/bazel/releases/tag/1.1.0, please try to modify the image to use this release.

**Comment by clnperez** [comment]
@irengrig thanks for the response! I see that I forgot to paste my dockerfile repo there. I'll edit it, but, the docker file is here: https://github.com/clnperez/dockerfiles/blob/master/bazel/Dockerfile.bionic.master

**Comment by irengrig** [comment]
The Docker file uses: /bazel_bin_ppc64le_0.27.2
So, you could modify it to 1.1.0, I see this binary is listed in [https://oplab9.parqtec.unicamp.br/pub/ppc64el/bazel/ubuntu_18.04]

**Comment by clnperez** [comment]
The dockerfile has a three-step build:
1) download 0.27.2
2) build 0.29.0
3) build master using 0.29.0

I was originally building 0.29.1 in step 3 and couldn't, and 1.x wasn't available yet. 
From what I understood -- 0.29.0 would have the right bazel_tools for 0.29.1, so when I saw the same issue with master I assumed it was all the same problem but   ¯\\_(ツ)_/¯ .

The good news is, though, that your suggestion (using 1.1.0) does seem to get past that error, so, that's great. Thanks @irengrig. :D
