### ISSUE TITLE
incompatible_validate_top_level_header_inclusions: also validate headers in the top level directory

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#10047]
**Flag:** `incompatible_validate_top_level_header_inclusions`
**Available since:** 1.2.0
**Will be flipped:** 2.0
**Tracking issue:** https://github.com/bazelbuild/bazel/issues/9965

### Description

5 years ago we refactored some random code and a code that skipped validation of top level header inclusions appeared. Nobody remembers why, so we're deleting that. Since some Bazel users can depend on not validating top level headers, we created this incompatible flag.

### Migration

Declare top-level headers as srcs/hdrs/deps of the cc_libraries using them, just like it's done for any other header in any other package.

**Comment by katre** [comment]
Closing due to flag flip in 858a4b1a44f1058f5bbec9ea778421038ef34f10
