### ISSUE TITLE
skyframe tests should not depend on java rules

### ISSUE THREAD

**Issue by janakdr** [bazelbuild/bazel#1005]
$ bazel query 'somepath(//src/test/java/com/google/devtools/build/skyframe:skyframe_base_test,//src/main/java/com/google/devtools/build/lib:java-rules)'
//src/test/java/com/google/devtools/build/skyframe:skyframe_base_test
//src/test/java/com/google/devtools/build/lib:testutil
//src/main/java/com/google/devtools/build/lib:bazel-rules
//src/main/java/com/google/devtools/build/lib:java-rules

Why does //src/test/java/com/google/devtools/build/lib:testutil pull in so much?

**Comment by ulfjack** [comment]
I don't know. Probably because we don't have a tool to automatically remove
unused deps? From a quick glance, that dependency looks unnecessary to me.

On Thu, Mar 3, 2016 at 7:12 PM, Janak Ramakrishnan <notifications@github.com

**Comment by aiuto** [comment]
Closing as obsolete. I can not reproduce (after finding the moved targets).
