### ISSUE TITLE
tool_deps option is not supported for c++ projects

### ISSUE THREAD

**Issue by AlexanderPaniutin** [bazelbuild/bazel#10056]
### Description of the problem / feature request:

blaze query does not have --[no]tool_deps for C++ projects on v1.0.0

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- install Bazel with Homebrew.
- follow c++ tutorial for stage 1
- run suggested command
bazel query --notool_deps --noimplicit_deps 'deps(//main:hello-world)' \
  --output graph

Received unexpected error:
ERROR: Unrecognized option: --notool_deps

### What operating system are you running Bazel on?

iOS

### What's the output of `bazel info release`?

release 1.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/AlexanderPaniutin/BazelTutorial.git
abc7fc4bbf11ee7a8b5bfe571ea91353e4ec99df
abc7fc4bbf11ee7a8b5bfe571ea91353e4ec99df

###  Have you found anything relevant by searching the web?

Cannot find already reported issue on forum or issue trackers
### Any other information, logs, or outputs that you want to share?

Cannot find this flag in "bazel --help query"
Found trace of it in src/main/java/com/google/devtools/build/lib/query2

**Comment by adyavanapalli** [comment]
From looking at the codebase, it looks like [`host_deps` was deprecated in favor of `tool_deps`](https://github.com/bazelbuild/bazel/commit/5a0cf9b57d590e24c94c6c42b221d703e88535f9), but for some reason, the new alias i.e. `tool_deps` is not working.

**Comment by gregestren** [comment]
This works for me with 1.1.0. Can you `brew upgrade bazelbuild/tap/bazel` and re-try?

**Comment by limdor** [comment]
@gregestren I think this ticket can be closed, tool_deps is working in C++ or at least not failing with Unrecognized option.

I came to this ticket when searching to try to understand how tool_deps and implicit_deps behave. I cannot say if notool_deps is excluding what it should but the option is recognized.

In case someone is interested, there the different outputs with the different combinations in Bazel 5.2 with a simple example and autodetected toolchains.

```
bazel cquery --tool_deps --implicit_deps "deps(//:hello_world)"

//:hello_world (d762925)
@bazel_tools//tools/cpp:grep-includes (HOST)
@local_config_cc//:cc-compiler-k8 (d762925)
@bazel_tools//tools/cpp:toolchain_type (d762925)
@local_config_platform//:host (d762925)
@bazel_tools//tools/def_parser:def_parser (HOST)
//:hello_world.cpp (null)
@bazel_tools//tools/cpp:malloc (d762925)
@bazel_tools//tools/cpp:toolchain (d762925)
//:my_lib (d762925)
@bazel_tools//tools/cpp:interface_library_builder (8fde4ce)
@bazel_tools//tools/def_parser:no_op.bat (null)
@bazel_tools//tools/build_defs/cc/whitelists/starlark_hdrs_check:loose_header_check_allowed_in_toolchain (null)
@platforms//cpu:x86_64 (d762925)
@bazel_tools//tools/build_defs/cc/whitelists/parse_headers_and_layering_check:disabling_parse_headers_and_layering_check_allowed (null)
//:my_lib.cpp (null)
//:my_lib.h (null)
@local_config_cc//:toolchain (d762925)
@local_config_cc//:local (d762925)
@local_config_cc//:empty (8fde4ce)
@platforms//os:linux (d762925)
@bazel_tools//src/conditions:host_windows (HOST)
@local_config_cc//:compiler_deps (8fde4ce)
@bazel_tools//tools/cpp:grep-includes.sh (null)
@bazel_tools//tools/cpp:link_dynamic_library (8fde4ce)
@local_config_platform//:host (HOST)
@platforms//os:os (d762925)
@platforms//cpu:cpu (d762925)
@bazel_tools//src/conditions:host_windows_x64_constraint (HOST)
@local_config_cc//:cc-compiler-armeabi-v7a (d762925)
@local_config_platform//:host (8fde4ce)
@local_config_cc//:builtin_include_directory_paths (null)
@bazel_tools//tools/cpp:link_dynamic_library.sh (null)
@platforms//os:linux (HOST)
@local_config_cc//:cc-compiler-k8 (d762925)
@bazel_tools//tools/cpp:build_interface_so (null)
@bazel_tools//src/conditions:host_windows_arm64_constraint (HOST)
@platforms//cpu:x86_64 (HOST)
@platforms//os:os (HOST)
@platforms//cpu:cpu (HOST)
@platforms//os:linux (8fde4ce)
@platforms//cpu:x86_64 (8fde4ce)
@local_config_cc//:stub_armeabi-v7a (d762925)
@platforms//os:os (8fde4ce)
@platforms//cpu:cpu (8fde4ce)
```

```
bazel cquery --notool_deps --implicit_deps "deps(//:hello_world)"

//:hello_world (d762925)
@local_config_cc//:cc-compiler-k8 (d762925)
@bazel_tools//tools/cpp:toolchain_type (d762925)
@local_config_platform//:host (d762925)
//:hello_world.cpp (null)
@bazel_tools//tools/cpp:malloc (d762925)
@bazel_tools//tools/cpp:toolchain (d762925)
//:my_lib (d762925)
@bazel_tools//tools/build_defs/cc/whitelists/starlark_hdrs_check:loose_header_check_allowed_in_toolchain (null)
@platforms//cpu:x86_64 (d762925)
@bazel_tools//tools/build_defs/cc/whitelists/parse_headers_and_layering_check:disabling_parse_headers_and_layering_check_allowed (null)
//:my_lib.cpp (null)
//:my_lib.h (null)
@local_config_cc//:toolchain (d762925)
@local_config_cc//:local (d762925)
@platforms//os:linux (d762925)
@platforms//os:os (d762925)
@platforms//cpu:cpu (d762925)
@local_config_cc//:cc-compiler-k8 (d762925)
@local_config_cc//:cc-compiler-armeabi-v7a (d762925)
@local_config_cc//:stub_armeabi-v7a (d762925)
```

```
bazel cquery --tool_deps --noimplicit_deps "deps(//:hello_world)"

//:hello_world (d762925)
//:hello_world.cpp (null)
//:my_lib (d762925)
//:my_lib.cpp (null)
//:my_lib.h (null)
```

```
bazel cquery --notool_deps --noimplicit_deps "deps(//:hello_world)"

//:hello_world (d762925)
//:hello_world.cpp (null)
//:my_lib (d762925)
//:my_lib.cpp (null)
//:my_lib.h (null)
```
