### ISSUE TITLE
java_binary explicitly outputs two files, a wrapper (good) and a .jar (bad), when it should only be one

### ISSUE THREAD

**Issue by justhecuke-zz** [bazelbuild/bazel#10067]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

`$(location //some/java:binary)` does not work which means that you can't run a java_binary from a `genrule`. I recall reading somewhere that, in general, `$(location :some_binary)` should execute that binary and this issue breaks that guidance.

`java_binary` is supposed to generate a wrapper script with the same name, but it also generates a `.jar` file which means that you have to use `locations` rather than `location`. This is despite the [docs](https://docs.bazel.build/versions/1.0.0/be/java.html#java_binary_implicit_outputs) stating that the `.jar` output is an implicit one which means that it shouldn't be treated as a default output that `location` consumes.

We need to remove the `.jar` output as an explicit output and put it back as an implicit one.

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`bazel build :bad_genrule`

```build
load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "java_binary",
    srcs = ["src/bug_repro/empty.java"],
    main_class = "bug_repro.empty",
)

genrule(
    name = "bad_genrule",
    srcs = [":java_binary"],
    cmd_bash = "echo $(location :java_binary) > $@",
    outs = ["bad_genrule_location"],
)
```

### What operating system are you running Bazel on?

macOS Mojave 10.14.6 (18G103)

### What's the output of `bazel info release`?

release 1.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git@github.com:lyft/instant-android.git
2e3910226d678ea5c0bd1a8a0a3a3e49afc6663e
77450e850a7234ebc6396ab1b9271e1ce5578dd9

###  Have you found anything relevant by searching the web?

Yes. https://stackoverflow.com/questions/52900812/how-to-pass-executable-wrapper-generated-by-java-binary-to-ctx-actions-run

Seems unresolved but the exact same problem as me, although mine isn't related to constructing a rule.

Other than that, I couldn't find anything about this particular issue, although I mainly searched for java_binary, genrule, and implicit/explicit outputs and I got a bunch of not-related results.

### Any other information, logs, or outputs that you want to share?

`$ bazel build :bad_genrule`

```
ERROR: /some/path/bug_repro/java_binary_outputs/BUILD.bazel:12:16: in cmd_bash attribute of genrule rule //some/path/bug_repro/java_binary_outputs:java_binary_outputs: label '//some/path/bug_repro/java_binary_outputs:java_binary' in $(location) expression expands to more than one file, please use $(locations //some/path/bug_repro/java_binary_outputs:java_binary) instead.  Files (at most 5 shown) are: [bazel-out/darwin-fastbuild/bin/some/path/bug_repro/java_binary_outputs/java_binary, bazel-out/darwin-fastbuild/bin/some/path/bug_repro/java_binary_outputs/java_binary.jar]
```

**Comment by davido** [comment]
Have you checked [Gerrit Code Review](https://gerrit.googlesource.com/gerrit) project? It has answers to (almost?) all bazel related question for Java projects, as it is a huge code base with 100+ available external plugins.

In particular there is [one missing feature](https://github.com/bazelbuild/bazel/issues/2009) in Bazel, that java JAR manifest cannot be passed into the `java_binary` rule.

As workaround, we have to extract the output of `java_binary`, merged wanted lines into the manifest file and re-package the result to new JAR file. To achieve that, we use `java_binary_rule_name_deploy.jar` as source to genrule and it works as expected: [1].

[1] https://github.com/GerritCodeReview/gerrit/blob/master/tools/bzl/plugin.bzl#L50-L65

**Comment by justhecuke** [comment]
The workaround occurred to me, but the bug is still a bug. `java_binary` should not be explicitly outputting both the wrapper and the jar. Especially since the documentation lists the jar as an implicit output.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
