### ISSUE TITLE
Docs edit on command line reference returns 404

### ISSUE THREAD

**Issue by Qinusty** [bazelbuild/bazel#10069]
### Description of the problem / feature request:

Clicking edit at https://docs.bazel.build/versions/master/command-line-reference.html leads to a 404 page. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Visit https://docs.bazel.build/versions/master/command-line-reference.html
Click edit

**Comment by philwo** [comment]
Link no longer leads to a 404 page.
