### ISSUE TITLE
Allow multiple outputs with cc_binary or cc_toolchain (to support emscripten)

### ISSUE THREAD

**Issue by issacgerges** [bazelbuild/bazel#10078]
### Description of the problem / feature request:

Allow multiple outputs with `cc_binary`, or add cpp toolchain support for multiple outputs

### Feature requests: what underlying problem are you trying to solve with this feature?

`emscripten` may produce `.html`, `.js`, `.wasm`, and/or `.mem` files. At the moment, the output of a `cc_binary` rule is limited a file matching the `name` (and is limited to a single output per rule). The best we've found to pull multiple outputs is to run the same `cc_binary` rule twice with unique names matching each output. This results in unnecessary build wor in the execution phase.

### What's the output of `bazel info release`?

release 1.0.0

###  Have you found anything relevant by searching the web?

Older discussion suggesting a feature request was created
https://groups.google.com/forum/#!topic/bazel-discuss/veQFJzbql2M

bazel slack conversation regarding ways to achieve this
https://bazelbuild.slack.com/archives/CGA9QFQ8H/p1571436869010800?thread_ts=1571435152.010400&cid=CGA9QFQ8H

### Any other information, logs, or outputs that you want to share?

Very new to Bazel, but I assume you'd need to `ArtifactCategory.java` to include emscripten outputs. I feel like allowing `cc_binary` (or creating an alternative that is able) to select multiple outputs from the artifact categories would solve this issue for me.

**Comment by randykwarner** [comment]
Just ran into this problem myself.  Building the .wasm separately is giving me problems so I'd love to see something implemented here.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
