### ISSUE TITLE
Avdmanager and emulator paths in export_files of androidsdk

### ISSUE THREAD

**Issue by geaden** [bazelbuild/bazel#10077]
### Description of the problem / feature request:

Add `'tools/bin/avdmanager'` and `'tools/emulator'` to `export_files` in `external/androidsdk/BUILD.bazel`

### Feature requests: what underlying problem are you trying to solve with this feature?

When building custom rules for android (i.e. like [this one](https://github.com/jin/rules_experimental_android/blob/master/composer/defs.bzl)) you may need to specify paths to `tools/bin/avdmanager` and `tools/emulator`. The only way to do it currently is to update `external/androidsdk/BUILD.bazel`. If you try to use `composer_instrumentation_test` from the link above target analysis will fail without

```python
export_files([
  ...
  'tools/bin/avdmanager',
  'tools/emulator',
])
```

in `external/androidsdk/BUILD.bazel`.

### What operating system are you running Bazel on?

macOS 10.15

### What's the output of `bazel info release`?

`release 1.0.0-homebrew`

###  Have you found anything relevant by searching the web?

Original GitHub issue: https://github.com/jin/rules_experimental_android/issues/5

**Comment by jinchizhou** [comment]
@geaden @jin is there an update on this?

**Comment by ahumesky** [comment]
please feel free to send us a pull request for this, should be straight forward for us to merge it in

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
