### ISSUE TITLE
bazel.exe has stopped working

### ISSUE THREAD

**Issue by mpmischitelli** [bazelbuild/bazel#10089]
### Description of the problem / feature request:

Running `bazel version` in a cmd prompt in Windows 10 Enterprise 2016 LTSB works. Running the same command from inside any other folder which contains a WORKSPACE file, produces this line in the console

"Starting local Bazel server and connecting to it..."

At the same time a popup appears saying "bazel.exe has stopped working". Doing the same in a Msys2 console I obtain a "Segmentation fault" error.

This is just the simplest repro, but of course trying other, more fancyful things like test, build etc.. doesn't work as well.

The bazel binaries I've tried this with are 1.10, 0.29.1, 0.25.2, 0.23.2. All of them have this problem.

### Feature requests: what underlying problem are you trying to solve with this feature?

I wanted to build tensorflow, but the same problem appears even trying to compile examples in this repo

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Just run any bazel command from any folder containing a WORKSPACE file. I just can't use bazel in any way!

### What operating system are you running Bazel on?

Windows 10 Enterprise 2016 LTSB

### What's the output of `bazel info release`?

"Starting local Bazel server and connecting to it..."  and then "bazel.exe has stopped working"

**Comment by laszlocsomor** [comment]
With Bazel 1.1.0 in `cmd.exe`, what's the output of `bazel --ignore_all_rc_files --client_debug info` ?

**Comment by mpmischitelli** [comment]
```
[bazel INFO src/main/cpp/blaze_util_windows.cc:1408] python.exe found on PATH: C:\Users\mpmischitelli\AppData\Local\Programs\Python\Python37-32\python.exe
[bazel INFO src/main/cpp/blaze.cc:1610] Debug logging requested, sending all client log statements to stderr
[bazel INFO src/main/cpp/blaze.cc:1509] Acquired the client lock, waited 1 milliseconds
[bazel INFO src/main/cpp/blaze.cc:1687] Trying to connect to server (timeout: 30 secs)...
```

and then 'bazel.exe has stopped working'

**Comment by laszlocsomor** [comment]
[Bazel has a client-server model](https://docs.bazel.build/versions/master/guide.html#client/server). The client works on your machine but either the JVM fails to start or it crashes.

Bazel comes with its own embedded JVM, so you don't need to install one. Did you download a released Bazel binary, or did you build it yourself? If the latter, then you might be picking up a JVM that Bazel is not prepared for.

**Comment by laszlocsomor** [comment]
> Bazel comes with its own embedded JVM, so you don't need to install one

...to run Bazel itself, I mean.

If you want to build Java code, you will need to install the JDK of course. (Currently JDK 12 is the highest version supported.)

**Comment by mpmischitelli** [comment]
I downloaded the binaries directly from the website and I'm just trying to compile tensorflow (and the standalone tool tfcompile).

**Comment by laszlocsomor** [comment]
Thanks, it still looks like Bazel cannot start its server.

So you tried it also in a directory with nothing but an empty WORKSPACE file?

Let's see if Bazel created any server log. This file is in Bazel's server directory, but we cannot predict the server directory's path without running `bazel info`, which now crashes. So let's do this trick:

1. run `bazel --ignore_all_rc_files --client_debug --output_user_root=c:\foo\bar info`
2. after it crashed, search for `java.log` under `c:\foo\bar`
3. if the file exists, what are the contents?

**Comment by mpmischitelli** [comment]
No `java.log` file exists under that folder. Instead, there is a `java.log.<machinename>.log.java.<date>.[...]` which is empty.

**Comment by laszlocsomor** [comment]
That file is created from Java. So the JVM starts.

The client and server communicate over gRPC, do you think anything might be blocking that?

Are you using a 64-bit or 32-bit machine?

**Comment by mpmischitelli** [comment]
64bit, forgot to mention.

I don't really know.. On another computer with a newer OS but same AV and same policies, it works.

Could it be that Win10 1607 is causing these problems? I saw mentioned that on 1703 and newer Bazel needs to run with Developer Mode enabled, while on older versions Developer Mode should be disabled instead..

**Comment by laszlocsomor** [comment]
No, any Win10 version is fine (even Win 7 is OK), we just recommend 1703 + Dev mode so that you can use `--enable_runfiles`.

**Comment by laszlocsomor** [comment]
I'm out of ideas to debug this without building a custom Bazel binary with debug info (or with printfs). Would you be interested in that?

If so, then follow the [bootstrapping guide](https://docs.bazel.build/versions/master/install-compile-source.html#bootstrap-bazel) except in 2.2, step 4, use `EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk --javacopt=-g"` instead of what's on the homepage.

This will build `bazel.exe` with debug info. You can use the resulting `bazel.exe` as the release one, and you can attach a debugger with [--host_jvm_debug](https://docs.bazel.build/versions/master/command-line-reference.html#flag--host_jvm_debug):

```
bazel --ignore_all_rc_files --client_debug --host_jvm_debug info
```

Bazel will wait for a debugger on port 5005. The process seems to crash somewhere after this line: https://github.com/bazelbuild/bazel/blob/5ada1402f7945a7c0336e3ffc8b3e3dda93fc856/src/main/java/com/google/devtools/build/lib/util/SimpleLogHandler.java#L351

**Comment by laszlocsomor** [comment]
Correction, this `bazel.exe` won't have an embedded JDK, so you have to export `JAVA_HOME=` to the JDK's path to _run_ this Bazel.

**Comment by mpmischitelli** [comment]
I arrived at the same conclusion, I need to rebuild bazel. In the mean time I've asked internally to be given a new virtual environment where I can carry out my tests. Thus, for the time being, I'll carry on with other tasks and wait for the new environment to be ready. At that point I should be able to resume experimenting with this.

Thanks for now, I'll keep you updated.

**Comment by laszlocsomor** [comment]
Thank you very much. I think this will be very educational, and hopefully we can make Bazel able to run on more machines as a result.

I'll wait for your updates then.

**Comment by mpmischitelli** [comment]
Couldn't do many tests due to company policies. Upgrading to Windows 10 Enterprise LTSC 1809 the problem was solved.
