### ISSUE TITLE
Add ability to generate Visual Studio projects.

### ISSUE THREAD

**Issue by mdzoba** [bazelbuild/bazel#10099]
### Description of the problem / feature request:

> Feature Request: Please add the ability to generate Visual Studio projects to enable development in a native Windows IDE.

### Feature requests: what underlying problem are you trying to solve with this feature?

> A lot (most) people do Windows development in Visual Studio. The ability to hit a key and have the project built and run in the debugger is a huge convenience for productivity. Visual Studio offers great advanced features like code navigation, auto-completion, refactoring, profiling, etc.
With blaze, just to achieve what F5 does in Visual Studio, we have to cross-compile on a Linux machine, copy the file over to a Windows machine, open it in the debugger. Even then, the debugger is much harder to use vs. when it's opened in a VS project.

This functionality is critical for people who work on cross-platform applications, but spend a lot of time focusing on Windows features.

Other build systems like gyp and gn have this functionality.

Note that it's not critical that Visual Studio uses lexan, or even that the generated projects build with MSBuild. The developers who use this feature can make sure their builds work with both compilers.

### What operating system are you running Bazel on?

> Linux

### What's the output of `bazel info release`?

> release blaze-2019.10.17-1

###  Have you found anything relevant by searching the web?

> No

**Comment by jin** [comment]
Have you seen https://github.com/tmandry/lavender?

**Comment by chengwei920412** [comment]
lavender is ugly design
