### ISSUE TITLE
Test the content of a rules executable.

### ISSUE THREAD

**Issue by bajacondor** [bazelbuild/bazel#10093]
### Description of the problem / feature request:

I need to use the `file_test()` rule to test the content of a rule's executable .sh file.  This file is in the `bazel-out/...` dir named as the name of the rule target.  But since the rule does not list it as an output, I can't seem to test its content.

### Feature requests: what underlying problem are you trying to solve with this feature?

When the rule expands a template as its executable, I should be able to test that the resultant script has the content I expect.

### What operating system are you running Bazel on?

OSX, Bazel 1.0

### What's the output of `bazel info release`?

release 1.0.0

**Comment by irengrig** [comment]
Hi @bajacondor , any Bazel rule works only with declared inputs.
(If you did not use the file_test, but the other custom rule, it would still be necessary to have the inputs declared explicitly.)
Would it be possible to declare the .sh file as an output of the producing rule?
Is that the producing rule have many outputs, from which the .sh needs to be selected?

Also, using the $(location ...) variable may help: https://docs.bazel.build/versions/master/be/make-variables.html#predefined_label_variables

/cc @laszlocsomor

**Comment by laszlocsomor** [comment]
Could you show us the rule that generates the `.sh` file and the `file_test` rule that consumes it?

**Comment by bajacondor** [comment]
> Would it be possible to declare the .sh file as an output of the producing rule?
Is that the producing rule have many outputs, from which the .sh needs to be selected?

Yes, I am going down the path of making the executable be a declared output but it's complicated because the rule was already written using `ctx.outputs.executable`  which seems to be a depreciated built-in output.

> Could you show us the rule that generates the .sh file and the file_test rule that consumes it?
 
The rule is [container_image()](https://github.com/bazelbuild/rules_docker/blob/master/container/image.bzl#L572) It does not generate a `.sh` file. it's executable is generated as the same name as the name of the target, or `ctx.outputs.executable`  the `file_test() rule I'm trying to write would interrogate that executable, but it's unavailable, since it's not a declared output.

> Also, using the $(location ...) variable may help:

Thank you, this is worth looking at.

**Comment by jin** [comment]
Closing this issue for now. @bajacondor, if you have any more queries, please don't hesitate to ping this issue and we'll reopen it.
