### ISSUE TITLE
External label_flag command line parsing behaves strangely.

### ISSUE THREAD

**Issue by deeglaze** [bazelbuild/bazel#10097]
### Description of the problem / feature request:

If I define a label_flag in an external workspace, then it appears that I can't set the flag from the command line.
Suppose I have @test_label//:label as a label_flag, and I want to set it to //:foo.

ERROR: Unrecognized option: --@test_label//:label=//:foo

Maybe workspace syntax isn't right and I should use //external/test_label:label...?

ERROR: Skipping '//external/test_label:label': no such package 'external/test_label': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /tmp/tmp.iBwpZJnWki/external/test_label
WARNING: Target pattern parsing failed.
ERROR: Error loading option //external/test_label:label: no such package 'external/test_label': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /tmp/tmp.iBwpZJnWki/external/test_label

It appears that I can indeed set the flag through a transition, but I couldn't in my larger development. *Time passes* Thanks for fixing that in 1.1.0.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run this gist https://gist.github.com/deeglaze/3bc92c79a6465f2ed4f372c7c2838b85

### What operating system are you running Bazel on?

Rodete (Debian-like)

### What's the output of `bazel info release`?

release 1.1.0

###  Have you found anything relevant by searching the web?

No

**Comment by gregestren** [comment]
Does https://github.com/bazelbuild/bazel/issues/10039 address this?

**Comment by deeglaze** [comment]
Yes, it appears to. Thanks.
