### ISSUE TITLE
Android NDK package: add filegroup for Vulkan validation layers

### ISSUE THREAD

**Issue by hevrard** [bazelbuild/bazel#10094]
### Description of the feature request:

Provide a mean to access Vulkan validation layers which are precompiled dynamic libraries shipped in Android NDK.

Android NDK BUILD file is generated by Bazel itself (`@androidndk`), and offers predefined rules/target related to the NDK. Currently, I cannot find an easy way to refer to the Vulkan validation layers. These layers are shipped in:

`$ANDROID_NDK_HOME/sources/third_party/vulkan/src/build-android/jniLibs/<ABI>/libVkLayer_*.so`

Where ABI is arm64-v8a, x86, etc.

### Feature requests: what underlying problem are you trying to solve with this feature?

Easily add Vulkan validation layers to Android app.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try to refer to the Vulkan validation layers using Bazel. I think that currently you need a repository rule that can access ANDROID_NDK_HOME environment variable, and search for those layers yourself.

###  Have you found anything relevant by searching the web?

Nothing relevant shows up.

**Comment by jin** [comment]
`//src/test/java/com/google/devtools/build/lib/bazel:bazel-rules-tests` is failing. Please take a look at that. It's probably because the mocked NDK doesn't have these files..?
