### ISSUE TITLE
Cannot load .bzl via alias label

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#10092]
I noticed that copybara uses the starlark interpreter and allows load statements without a .bzl extension.
That sounds like nice syntax sugar so I tried it.

https://docs.bazel.build/versions/master/build-ref.html#load says that The first argument of load is a label identifying a .bzl file. 
However if that label is an alias it doesn't seem to work.

`/BUILD`
```
# This looks like nice syntax sugar!
load("//rules", "thing")

thing()
```

`/rules/BUILD`
```
alias(name = "rules", actual = "defs.bzl")
```

`/rules/defs.bzl`
```
def thing():
    pass
```

```
$ bazel build ...
INFO: Writing tracer profile to '/home/alexeagle/.cache/bazel/_bazel_alexeagle/e48f293efabb403475acb0d1d27af3d9/command.profile.gz'
ERROR: /home/alexeagle/Projects/repro_label_load/BUILD:1:6: in load statement: The label must reference a file with extension '.bzl'
ERROR: error loading package '': malformed load statements
INFO: Elapsed time: 0.240s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
alexeagle@alexeagle-glaptop:~/Projects/repro_label_load$ bazel version
Build label: 1.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 21 08:44:00 2019 (1571647440)
Build timestamp: 1571647440
Build timestamp as int: 1571647440
```

**Comment by laurentlb** [comment]
Load labels must be resolved before we even parse a BUILD file, so using `alias` (or anything else in a BUILD file) is not going to work.

**Comment by laurentlb** [comment]
I'm going to close this issue, because it's unlikely that we'll change this.
