### ISSUE TITLE
Please add a cc_inputs attribute to *c_library rules

### ISSUE THREAD

**Issue by ob** [bazelbuild/bazel#10107]
[rules_swift](https://github.com/bazelbuild/rules_swift)'s [swift_library](https://github.com/bazelbuild/rules_swift/blob/master/doc/rules.md#swift_library) rule, includes a [swiftc_inputs](https://github.com/bazelbuild/rules_swift/blob/master/doc/rules.md#swift_library.swiftc_inputs) attribute that allows it to pass additional inputs to the invocation of the `swiftc` compiler. It would be really handy if `objc_library()`, `cc_library()`, etc also had this attribute. 

The specific use case that I'm thinking of is passing around the module map in cases where it's needed to support `@import` statements in Objective-C. Currently I'm passing it as a header but this feels hacky.

**Comment by ob** [comment]
@irengrig I don't think this is `team-Apple`, probably more `team-Rules-CPP`

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
