### ISSUE TITLE
Configuration transitions in external dependencies don't work?

### ISSUE THREAD

**Issue by deeglaze** [bazelbuild/bazel#10118]
My project defines a few transition rules to switch from building a host application to building a binary that works on Intel SGX. It doesn't appear that any clients of my project can use these rules though due to how whitelist label resolution works.

I wrote up a repro here https://github.com/deeglaze/repro/raw/master/external_transition.tar.gz

```shell
bazel run :qux_setting --experimental_starlark_config_transitions
```

**Comment by gregestren** [comment]
P1 issue review: marking this as a P3 not because it's not important, but because it's an example of https://github.com/bazelbuild/bazel/issues/11128. That's the main tracking bug, which is prioritized for this quarter.

Keeping this bug open to verify fixes against this specific example.

**Comment by gregestren** [comment]
On second though, let's consolidate these bugs into #11128.

When that one is fixed, it if doesn't address this we can re-open this.
