### ISSUE TITLE
Bazel 1.0.1 is still marked as "latest release" when 1.1.0 is also available

### ISSUE THREAD

**Issue by ob** [bazelbuild/bazel#10129]
Title says it all. Is there a reason for this or is this an oversight?

I.e. https://github.com/bazelbuild/bazel/releases/latest shows 1.0.1

**Comment by meisterT** [comment]
We released 1.0.1 after 1.1.0, so timeline wise it is the latest release.
We would prefer that GitHub woiuld still show 1.1.0 as latest but that is non-trivial unfortunately :-/
