### ISSUE TITLE
Eliminate warning "please do not import [some header or cc file]"

### ISSUE THREAD

**Issue by stellaraccident** [bazelbuild/bazel#10121]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

I don't see the value in the warnings of the form "please do not import [some header or cc file]" from another package (I'm not saying there isn't value -- but this seems to be a level of build-policing that maybe shouldn't apply to the OSS version). Assuming that there is not a functional reason why this has to be prohibited, can the warning be removed from the OSS Bazel release?

Example of warning:
WARNING: C:/users/laurenzo/_bazel_laurenzo/aamy3fit/external/org_tensorflow/tensorflow/core/BUILD:2667:1: in srcs attribute of cc_library rule @org_tensorflow//tensorflow/core:framework_internal: please do not import '@org_tensorflow//tensorflow/core/util/sparse:group_iterator.h' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'tf_cuda_library', the error might have been caused by the macro implementation in C:/users/laurenzo/_bazel_laurenzo/aamy3fit/external/org_tensorflow/tensorflow/core/BUILD:2667:1

### Feature requests: what underlying problem are you trying to solve with this feature?

I don't understand why Bazel is imposing such a workspace design on me. In this case, it is hundreds of TensorFlow warnings, and I don't see why the situation is problematic.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Follow TensorFlow build instructions.

### What operating system are you running Bazel on?
Windows

### What's the output of `bazel info release`?

release 1.0.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/google/iree.git
47de2b7b049b4e794e8ebf574fa7098d5fc108b0
47de2b7b049b4e794e8ebf574fa7098d5fc108b0

###  Have you found anything relevant by searching the web?

People have reported this in various projects, but not (that I can see) as a Bazel defect. I think the burden should be on the Bazel side to indicate why this opinion as to how workspaces are laid out and cc artifacts are built is necessary. Especially since other build systems do not have such a constraint, it can impose non-trivial organizational disconnects (i.e. wrt cmake).

**Comment by stellaraccident** [comment]
More context: This is being enforced in CcLibrary.java: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/cpp/CcLibrary.java#L220

It appears to have been added in 2015 with no justification. Given that there seems to be no active plan to graduate this warning to an error, and it offers no explanation as to why Bazel is policing things in this way, I advocate for simply removing it. Alternatively, if there is an active reason why this rule may eventually be important to enforce, we should change the warning to reference rationale (even if just in the source code). Obviously, Bazel is functioning just fine with workspace layouts of this form and I don't immediately see the reason for it to be enforcing a more limited rule on eveyone.

Please correct if I'm missing somthing.

**Comment by stellaraccident** [comment]
(for context, I get hundreds of these warnings when building common projects, and aside from being sloppy, it severely slows down the terminal)

**Comment by navid-h-azimi** [comment]
+1 for this suggestion, In my case, I am using select function to link two different source file based on the platform. I don't really see any value for this warning.
