### ISSUE TITLE
ERROR: An error occurred during the fetch of repository 'local_config_cuda'

### ISSUE THREAD

**Issue by shauryad15** [bazelbuild/bazel#10139]
bazel version -- [bazel release 0.26.1]
cuda 10.0
cudnn 7
ubuntu 18.04
tensorflow r1.14

while building tensorflow, getting this error:
INFO: Call stack for the definition of repository 'local_config_cuda' which is a cuda_configure (rule definition at /home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl:1268:18):
 - /home/shaurya/Downloads/tensorflow/tensorflow/workspace.bzl:63:5
 - /home/shaurya/Downloads/tensorflow/WORKSPACE:94:1
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
	File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
		_create_local_cuda_repository(repository_ctx)
	File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 1199, in _create_local_cuda_repository
		_tpl(repository_ctx, "crosstool:BUILD", c...)
	File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 745, in _tpl
		repository_ctx.template(out, Label(("//third_party/gpus/%s...)), ...)
class com.google.devtools.build.lib.syntax.SkylarkList$MutableList cannot be cast to class java.lang.String (com.google.devtools.build.lib.syntax.SkylarkList$MutableList is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
		_create_local_cuda_repository(repository_ctx)
	File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 1199, in _create_local_cuda_repository
		_tpl(repository_ctx, "crosstool:BUILD", c...)
	File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 745, in _tpl
		repository_ctx.template(out, Label(("//third_party/gpus/%s...)), ...)
class com.google.devtools.build.lib.syntax.SkylarkList$MutableList cannot be cast to class java.lang.String (com.google.devtools.build.lib.syntax.SkylarkList$MutableList is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
		_create_local_cuda_repository(repository_ctx)
	File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 1199, in _create_local_cuda_repository
		_tpl(repository_ctx, "crosstool:BUILD", c...)
	File "/home/shaurya/Downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 745, in _tpl
		repository_ctx.template(out, Label(("//third_party/gpus/%s...)), ...)
class com.google.devtools.build.lib.syntax.SkylarkList$MutableList cannot be cast to class java.lang.String (com.google.devtools.build.lib.syntax.SkylarkList$MutableList is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
INFO: Elapsed time: 0.485s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package

**Comment by aiuto** [comment]
This looks like a mis-matched set of versions of all the components.

Can you provide more information
- what version sets did you previously have working together
- which components are pinned low rather than newer, and how out of date are those.

**Comment by sherry3255** [comment]
I have the same problem before.
the [issue](https://github.com/tensorflow/tensorflow/issues/11859) is similar with yours.
Try to install bazel0.5.2, maybe it can solve your problem.

**Comment by redradist** [comment]
@shauryad15 I have faced with the same error during the building tensorflow v2.3.0 ...
```console
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
        _create_local_cuda_repository(<1 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 955, in _create_local_cuda_repository
        _get_cuda_config(repository_ctx, <1 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 657, in _get_cuda_config
        find_cuda_config(repository_ctx, <2 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 635, in find_cuda_config
        _exec_find_cuda_config(<3 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 629, in _exec_find_cuda_config
        execute(repository_ctx, <1 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
        fail(<1 more arguments>)
Repository command failed
script.py:124: DeprecationWarning: invalid escape sequence \d
  match = re.match("#define %s +(\d+)" % name, line)
script.py:260: DeprecationWarning: invalid escape sequence \d
  pattern = "Cuda compilation tools, release \d+\.\d+, V(\d+\.\d+\.\d+)"
script.py:553: DeprecationWarning: invalid escape sequence \w
  match = re.match("^(/[^/ ]*)+/lib/\w+-linux-gnu/?$", os.environ[env_name])
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-10.2/include/cuda.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda/include/cublas_api.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/include/cudnn.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/include/cudnn_version.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
        _create_local_cuda_repository(<1 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 955, in _create_local_cuda_repository
        _get_cuda_config(repository_ctx, <1 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 657, in _get_cuda_config
        find_cuda_config(repository_ctx, <2 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 635, in find_cuda_config
        _exec_find_cuda_config(<3 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 629, in _exec_find_cuda_config
        execute(repository_ctx, <1 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
        fail(<1 more arguments>)
Repository command failed
script.py:124: DeprecationWarning: invalid escape sequence \d
  match = re.match("#define %s +(\d+)" % name, line)
script.py:260: DeprecationWarning: invalid escape sequence \d
  pattern = "Cuda compilation tools, release \d+\.\d+, V(\d+\.\d+\.\d+)"
script.py:553: DeprecationWarning: invalid escape sequence \w
  match = re.match("^(/[^/ ]*)+/lib/\w+-linux-gnu/?$", os.environ[env_name])
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-10.2/include/cuda.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda/include/cublas_api.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/include/cudnn.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/include/cudnn_version.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
INFO: Elapsed time: 8.508s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
```
