### ISSUE TITLE
Dynamic/static library extension on Windows is all wrong

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#1013]
We use .so , and Windows uses .dll . T

This is somewhat similar to the situation on OS X.

**Comment by dslomov** [comment]
Do we still have any user-visible issues here (unrelated to removing python wrapper)?

**Comment by meteorcloudy** [comment]
`.dll` can be explicitly specified in the `cc_binary` target name. However, users will always see Bazel linking `.a` file instead of `.lib` file, and the object file is ending with `.o` instead of `.obj`.  Although they all works fine, but it doesn't feel like a native tool, and I am not sure whether it would cause any problems for generating Visual Studio project file later.

**Comment by meteorcloudy** [comment]
https://docs.google.com/document/d/1ZK4f84wype5NsZ7ltOUqvyFr7eKOIf4Wd-DrU6HCBkA/edit talked about how to solve this.

**Comment by laszlocsomor** [comment]
Does anyone have updates on this bug? P1 seems unjustified, this looks merely like an inconvenience, so dropping to P3.

**Comment by meteorcloudy** [comment]
I am planing to work on this. It's true this isn't blocking anyone, but having wrong extensions for C++ artifacts gives people the impression that Bazel is not a native tool for Windows. 
And perhaps it would cause some problem when integrating with IDE? For example, the IDE expect .lib/.dll files for dynamic library, but Bazel can only provide .ifso/.so.
I'll say it's a P2 at least.

**Comment by laszlocsomor** [comment]
Sounds good, thank you! If you want to schedule this for Q1, please add the "windows-q1-2018-maybe" tag.

**Comment by laszlocsomor** [comment]
And let's stay realistic with how much we can take on for Q1. I'd rather underpromise and overdeliver than the other way around.

**Comment by meteorcloudy** [comment]
I think this is important for making users have a better experience on Windows. I want to work on it in Q1.

**Comment by meteorcloudy** [comment]
5c4f3b59fb4aa06da2c368c764cf0d9056ab287a should have fixed this

**Comment by mhlopko** [comment]
\o/
