### ISSUE TITLE
Severe sandbox performance regression with macOS Catalina

### ISSUE THREAD

**Issue by ob** [bazelbuild/bazel#10130]
I'm still investigating but I'm seeing a severe performance regression using sandboxing with macOS Catalina.

The build is for a large iOS application, running it with the flags:

```
$ bazel build --genrule_strategy=local --spawn_strategy=local //App
```

takes about 13 minutes. Running it with the flags:

```
$ bazel build --genrule_strategy=sandboxed --spawn_strategy=sandboxed //App
```

takes *22 hours*. I tried the same build on a different machine: identical hardware, but running macOS Mojave, using the sandboxed strategy takes about 2 hours.

**Comment by tetromino** [comment]
@jmmv, can you please see if this is reproducible? We may need to just disable sandboxing on Catalina if the performance is this bad.

**Comment by jmmv** [comment]
Are there any more details you can share about your build, like the primary rules you use? Do you have any antivirus software or monitoring software (like Santa) installed?

I just did a quick test building Bazel 1.1.0 itself on a 6-core Mac Pro 2013 running Catalina. The unsandboxed and sandboxed builds both took about 10 minutes. I seem to recall that building Bazel took 5 minutes on this same machine not too long ago though...  but if true, that's not a Catalina issue: the same build on a similar Mac Pro running Mojave gave me only slightly better timings.

Will try some other kind of build tomorrow.

cc @dmaclach

**Comment by ob** [comment]
I couldn't reproduce by building bazel itself on the same machine. Sandboxing or no sandboxing perf is almost the same (as you found out). I'll also keep poking at it and report back if I find anything.

**Comment by jmmv** [comment]
I've been testing this today with the build of a pretty large iOS app. I have a Mac Pro 2013 running Mojave and a MacBook Pro 2015 running Catalina. On both machines I observe a 3x slowdown when sandboxing is enabled, which is ugly... but is also normal. Haven't observed the severe regression reported here yet.

As requested earlier: can you share anything else about your build? Do you have any special software installed on the machine? Antivirus? Santa? Falcon? What machine are you running this on?

**Comment by ob** [comment]
It's not `sandbox-exec`. I wrote a fake `sandbox-exec` that just execs the given command without doing anything special and the build on that machine still takes 22 hours. 

The machine is an iMac 2017, (4.2 GHz Quad-Core Intel Core i7) with 64 GB of RAM and 500 GB of SSD HDD. It's running macOS Catalina version 10.15.1 (19B88). As far as I can tell it's not running any special software, I checked `kextstat -l | grep -v apple` and nothing pops up. There is no antivirus, no Santa, and no Falcon installed.

My MacBook Pro (15-inch, 2019) 2.4 GHz 8-Core Intel Core i9 takes 2 hours to build the same iOS app sandboxed. Building the non-sandboxed version takes 11 min, so it's 10x the non-sandboxed build time. 

The iOS app has a mix of Objective-C and Swift and uses modules, perhaps the app you built is just Objective-C and doesn't use modules?

**Comment by jmmv** [comment]
Thanks, and sorry about that. In the last reply, I hadn't noticed that you had already provided more details about your build.

The iMac is the one that took 22h, and the MBP takes 2h?

When you run the build on the machine that took 22h, what's happening? Is the CPU load high? Is Bazel using a lot of CPU? (If yes to the latter, getting some `jstack` traces a few seconds apart might be useful.) Is disk I/O high?

The iOS app I built does use ObjC modules, but no Swift. I could try something with Swift, which will be more I/O intensive I think.

I mean, this is not an answer, but you could try sandboxfs to see if it makes things better (just install the .pkg from the github releases page and then pass `--experimental_use_sandboxfs`). There is a known performance bug on machines with a high-core count, but you may see an improvement regardless.

**Comment by ob** [comment]
> The iMac is the one that took 22h, and the MBP takes 2h?

Yeah, the MBP is faster but not _that_ fast... I suspect something else is going on.

> When you run the build on the machine that took 22h, what's happening?

CPUs are loaded, it looks like this
<img width="1369" alt="Screen Shot 2019-10-31 at 10 04 41 AM" src="https://user-images.githubusercontent.com/4950/68039704-ed17f480-fc89-11e9-82b0-bc72ca7b7916.png">

I'm a bit concerned about that system time though... feels like too much for a compilation command. This is why I thought it was the sandbox, but as I said, I replaced `sandbox-exec` with a no-op version and the time is the same.

I poked at the sandbox while it was building and each sandbox is about 80Mb (mostly due to the pre-compiled modules). 

I tried to get a `trace-profile.json` but got hit with #10149. I manually fixed the JSON and noticed that most compilation actions at the end of the build are taking a long, long time to complete. Over 30 seconds.

Is there a way to get a breakdown between the sandbox set-up/tear-down and the time the actual action took? 

What I'm trying to figure out is if it's setting up the sandbox and tearing it down that is taking that time, or if it's the actual `clang` command. The `trace-profile.json` for one of those action says:

```
Category | action processing
-- | --
User Friendly Category | other
Start | 14,431,737.212 ms
Wall Duration | 29,721.772 ms
Self Time | 8.430 ms
```

What is the difference between "Wall Duration" and "Self Time"? This is for compiling a single `.m` file.

**Comment by jmmv** [comment]
What you describe (actions towards the end of the build taking a long time) is what I've observed too, and is "normal" because actions tend to get bigger and bigger (in number of inputs) as the build progresses.

I don't know if this shows up in the profile; never checked. But if you take a jstack of the Bazel process, you'll likely catch several threads busy in `deleteTrees` cleaning up each sandbox. (Somewhat related: https://jmmv.dev/2019/03/optimizing-tree-deletions.html) If that's true, I don't know why this may have gotten slower for you on Catalina.

I'm guessing this is all on the local SSD using APFS?

**Comment by ob** [comment]
Should using `--experimental_sandbox_async_tree_delete_idle_threads=auto` make a difference then? I tried it and it didn't seem to.

I took some samples of how many `deleteTrees` were running during the middle of the build, when `clang` seems to be taking 15s or so:

```
% n=1; while true ; do  echo $n - $(jstack 69343 | grep deleteTrees | wc -l) ; sleep 1 ; done                                                                            ✘ 130
1 - 2
1 - 0
1 - 2
1 - 2
1 - 4
1 - 6
1 - 2
1 - 0
1 - 2
1 - 0
1 - 2
1 - 2
1 - 0
1 - 0
1 - 2
1 - 4
1 - 2
1 - 4
1 - 4
1 - 2
1 - 0
1 - 0
1 - 2
1 - 4
1 - 2
1 - 0
1 - 0
1 - 0
1 - 0
1 - 4
1 - 0
```

Doesn't seem like it should be much of a problem. 

Yeah, this is on local SSD using APFS.

**Comment by jmmv** [comment]
Downgrading to P2 because we haven't gotten more reports about this and haven't been able to reproduce. (Will continue looking though.)

**Comment by ob** [comment]
Agreed. I am also unable to reproduce the severity of the slowdown in a different box. I will keep poking to see if I can figure out the root cause.

**Comment by jmmv** [comment]
Have you been able to find anything? Tempted to say this is an environmental issue with that machine's configuration and not a Bazel issue... without a reproduction case it'll be very hard to track down what's going on.

**Comment by ob** [comment]
I haven't found any more info.

My next step was going to be changing the way Bazel builds the sandbox from using `symlink` to using the `clonefile`, maybe traversing symlinks is slower in Catalina and the higher parallelism of the MacBook masks it? Do you think that's a possibility?

**Comment by jmmv** [comment]
I don't think so. The usual problems we have with sandboxing performance are with the creation and deletion of the thousands of symlinks; traversing them should be very cheap because that happens purely within the kernel and their targets should have already been cached at creation time.

So switching `symlink` with `clonefile` does not improve this because the number of syscalls remains the same, and linear with the number of inputs.

Note that the tests I ran were with less-powerful machines than your iMac (one 4-core and one 6-core though), so I'm not sure this is related either. But it's something worth investigating further. I'd actually be concerned about the opposite: a higher level of parallelism choking for some reason. I think I'll be upgrading my iMac Pro 18-core soon to Catalina so I'll give it another go once that happens.

**Comment by ob** [comment]
I ran "Instruments" while the build is going and I'm seeing the `clang` processes themselves taking up to 30s to compile, so it doesn't seem to be entirely due to setup/teardown of sandboxes... that's why I was thinking about symlinks being the problem. However, sampling some of those processes, I see them compiling modules (`compileModuleImpl`) in the deepest stack trace. A friend pointed me out to  https://github.com/liscio/SubFrameworks as a possible cause.

You might not be seeing it since I don't suppose you use modules, right?

**Comment by ob** [comment]
And after upgrading to Catalina 10.15.2 Beta (19C39d) the build time is down to 5 hours (it was 22 hours)... I think something was busted with the previous install.

**Comment by ob** [comment]
And trying with Xcode 11.2.1 brings it down to 2 hours 40 min. I think this has nothing to do with Bazel and it's probably an Xcode/Catalina bug. Sorry for the noise :-)

**Comment by jmmv** [comment]
Great; thanks for the additional research!
