### ISSUE TITLE
Release 2.1 - January 2020 (stable)

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#10132]
Cut date: 2020-01-07

**Comment by c16a** [comment]
Hope 934c4fd4a4a96093a2cd0b08cf619bef04d0b582 is included in this change?

**Comment by laurentlb** [comment]
# Status of Bazel 2.1

- Target baseline: 2020-01-08
- Expected release date: January 15th-20th
- [List of release blockers](https://github.com/bazelbuild/bazel/labels/Release%20blocker)

To report a release-blocking bug, please file a bug using the `Release blocker` label, and cc me.

Task list:

- [ ] Update GitHub issues for incompatible changes
- [ ] Pick release baseline:
- [ ] Create release candidate:
- [ ] Check downstream projects:
- [ ] [Create draft release announcement](https://docs.google.com/document/d/1wDvulLlj4NAlPZamdlEVFORks3YXJonCjyuQMUQEmB0/edit)
- [ ] Send for review the release announcement PR:
- [ ] Push the release, notify package maintainers:
- [ ] Update the documentation
- [ ] Push the blog post
- [ ] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by laurentlb** [comment]
All changes submitted before today should be included.
I'll update the previous status message later today.

**Comment by Yannic** [comment]
Could we cherry-pick https://github.com/bazelbuild/bazel/commit/4162cc54ba0b128b616c0bd05b65bf9ad5e66f2e into Bazel 2.1? (Context: https://github.com/bazelbuild/bazel/issues/10484)

**Comment by werkt** [comment]
Requesting cherry-pick of 9a823d9dab82631ff4600eff38d597807e8d1221 into Bazel 2.1 (Context: #10566), addresses a NPE resulting in build failures.

**Comment by meteorcloudy** [comment]
Please cherry-pick 7e4c9d5 to fix https://github.com/bazelbuild/bazel/issues/10572

**Comment by Helcaraxan** [comment]
For those not following the GitHub issue in question but #10356, which was [re-opened yesterday](https://github.com/bazelbuild/bazel/issues/10356#issuecomment-576386798), might be considered a release-blocker for 2.1.0.

**Comment by keith** [comment]
Any plans for when there will be another RC or the official 2.1.0 release?

**Comment by laurentlb** [comment]
I'll make another RC tomorrow.

**Comment by laurentlb** [comment]
I'm waiting for a resolution on https://github.com/bazelbuild/bazel/issues/10356.

Apart from that, I'll cherry-pick: 
- 733ac0ff7ad1e13ab68ceb2fde694d7ab71b2366 (for #10544)
- c94b1474b368dedf9f68f34fad90cc8664f2b0e0 (for #10550)

Please tell me if I forgot another one. In some cases, I commented on the issue why I don't think a fix qualifies for a cherry-pick. Let me know if you feel strongly otherwise.

**Comment by philwo** [comment]
Just mentioning this here, so it doesn't get lost: This commit https://github.com/bazelbuild/bazel/commit/2a8cc7075f741721563efd9dc050ca3458cde30b is the cherry-pick for #10356.

**Comment by laurentlb** [comment]
Sorry for the delay, I have been busy with some emergencies.

I've just tried to create rc2 with:
`scripts/release/release.sh create --force_rc=2 2.1.0` 41ec5a28fb30a8d6c5c60194c4bb29528352cf78 733ac0ff7ad1e13ab68ceb2fde694d7ab71b2366 c94b1474b368dedf9f68f34fad90cc8664f2b0e0 2a8cc7075f741721563efd9dc050ca3458cde30b

But this is currently failing: https://github.com/bazelbuild/continuous-integration/issues/929

**Comment by philwo** [comment]
I fixed the release pipeline so the error bazelbuild/continuous-integration#929 should no longer happen. We build Bazel with Xcode 10.3 now. I verified that the resulting binary still works fine on macOS High Sierra, so we don't regress in that regard.

Please cherry-pick this commit to fix a potential security issue that I accidentally introduced (it would have been in rc2, so let's skip that one) and then we can do rc3: https://github.com/bazelbuild/bazel/commit/d381c25bb7dd205c283f7ad91cac13190d2dfede

**Comment by laurentlb** [comment]
Creating candidate with:

`scripts/release/release.sh create --force_rc=3 2.1.0` 41ec5a28fb30a8d6c5c60194c4bb29528352cf78 733ac0ff7ad1e13ab68ceb2fde694d7ab71b2366 c94b1474b368dedf9f68f34fad90cc8664f2b0e0 2a8cc7075f741721563efd9dc050ca3458cde30b bdf34d7fd9539411e93348ba25307f34362d9a42 d381c25bb7dd205c283f7ad91cac13190d2dfede

(bdf34d7fd9539411e93348ba25307f34362d9a42 was added to avoid a merge conflict)

**Comment by laurentlb** [comment]
Although there are still some issues in our testing infrastructure, the binaries can be tried here:
https://releases.bazel.build/2.1.0/rc4/index.html

**Comment by laurentlb** [comment]
The release announcement is ready: https://github.com/bazelbuild/bazel-blog/pull/216

I'll do the release tomorrow.

**Comment by laurentlb** [comment]
https://github.com/bazelbuild/bazel/releases/tag/2.1.0
https://blog.bazel.build/2020/02/06/bazel-2.1.html

cc @vbatts @petemounce @excitoon

**Comment by philwo** [comment]
I'm preparing Bazel 2.1.1 with one cherry-pick:

9a823d9: Prevent NPE on backwards seek on Chunker.

RELEASE_NUMBER=2.0.1
BASELINE_COMMIT=50514fc6c125750d7063d7feea2c302a44d2db6e
git clone https://github.com/bazelbuild/bazel.git ~/bazel-release-$RELEASE_NUMBER
cd ~/bazel-release-$RELEASE_NUMBER
scripts/release/release.sh create $RELEASE_NUMBER $BASELINE_COMMIT \
    9a823d9dab82631ff4600eff38d597807e8d1221

**Comment by philwo** [comment]
Bazel 2.1.1rc1 is now available for those that want to try it out.
 
You can download it from:
  https://releases.bazel.build/2.1

**Comment by werkt** [comment]
I've tested the rc, and it works precisely how we hoped with my change. Can this be promoted to a full release?

**Comment by philwo** [comment]
@werkt I'll push it out tomorrow morning.

**Comment by werkt** [comment]
Any news on that release?

**Comment by philwo** [comment]
@werkt Pushing it now.

**Comment by or-shachar** [comment]
What about a docker image `l.gcr.io/google/bazel:2.1.1` ? :-) who's in charge of those releases?

**Comment by jin** [comment]
Can this be closed?
