### ISSUE TITLE
analyze-profile is broken with current default profile generated file

### ISSUE THREAD

**Issue by amarshat** [bazelbuild/bazel#10140]
### Description of the problem / feature request:

`analyze-profile` fails with `java.util.zip.ZipException` while trying to analyze the profile (generated as `gunzip`)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Follow the instructions here: https://docs.bazel.build/versions/master/skylark/performance.html#performance-profiling

```bash
bazel build --nobuild --profile=/tmp/prof //path/to/package:build_target
bazel analyze-profile /tmp/prof
WARNING: This information is intended for consumption by Bazel developers only, and may change at any time.  Script against it at your own risk
INFO: Loading /tmp/prof
java.util.zip.ZipException: incorrect header check
ERROR: Failed to analyze profile file(s): incorrect header check
```

### What operating system are you running Bazel on?
Darwin (macOS)

### What's the output of `bazel info release`?

`release 1.1.0`

###  Have you found anything relevant by searching the web?
https://github.com/bazelbuild/bazel/issues/8840

**Comment by drigz** [comment]
I also tried using --profile=profile.out.gz which results in a compressed file, but analyze-profile still fails.

**Comment by gydeveloper** [comment]
Wanted to check-in and see if there is any update on this? Thanks!

**Comment by meisterT** [comment]
See the most recent commit that is associated with it. Bazel (at HEAD) can now print a basic human readable summary from the JSON output.

**Comment by meisterT** [comment]
@thekyz can you try with https://releases.bazel.build/2.2.0/rc1/index.html ?

That works for me. If it doesn't work for you, then please tell me how to repro it.

**Comment by thekyz** [comment]
It does work with that version thx!

**Comment by jin** [comment]
Fix verified, closing.
