### ISSUE TITLE
When upgrading bazel remote repositories can cause difficult to diagnose failures

### ISSUE THREAD

**Issue by allada** [bazelbuild/bazel#10144]
### Description of the problem / feature request:

We recently upgraded to 1.1.0 from 0.26.1, all our bots passed, everything seemed to be ready so we pulled the trigger. Almost immediately almost all our bots started failing and some of our developers started saying they could not build. We quickly realized that if we `bazel clean --expunge` it would fix the problem for our developers, but cleaning our bots was going to be extremely difficult.

Eventually we discovered that an external rule: `com_github_nanopb_nanopb` was causing our problems. What happened is that we upgraded `grpc` in this commit and our rule was structured as such:
```py
    http_archive(
        name = "com_github_nanopb_nanopb",
        build_file = "@com_github_grpc_grpc//third_party:nanopb.BUILD",
        strip_prefix = "nanopb-nanopb-0.4.0-dev",
        url = "INTERNAL_URL",
        sha256 = "1681c50649cdcba4990de817e4b68ef3e1a763097900e140bb2226e56caf5bb6",
)
```

What I believe was happening here is that when we did `bazel fetch //...` (or build) it would not check the build rules on the new bazel when the build was clean. However, if the new bazel version used the old bazel versions external cache it would see that there's a cache entry for the BUILD rule and parse it and fail the build (because the new version of bazel does not work with this version of nanopb).

This was really difficult to figure out because when we upgraded bazel the bots happened to be fresh/clean bots and had no externals cache and passed fine since it never downloaded and/or parsed the unused nanopb BUILD file, however once we rolled it out the bots would try and parse this BUILD rule and/or download it and fail because it was present in the cache.

Although there are workarounds, I wanted to share this with others in case they run into similar issues and notify the bazel devs of a difficulty. :-)

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
