### ISSUE TITLE
Hashing external repository contents is slow and often unnecessary

### ISSUE THREAD

**Issue by scele** [bazelbuild/bazel#10147]
### Description of the problem / feature request:

The [resolved workspace files](https://blog.bazel.build/2018/09/28/first-class-resolved-file.html) feature seems to have added code that hashes the contents of each external repository after they have been materialized: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/repository/RepositoryResolvedEvent.java#L100

```java
    String digest = "[unavailable]";
    try {
      digest = outputDirectory.getDirectoryDigest();
      repositoryBuilder.put(OUTPUT_TREE_HASH, digest);
    } catch (IOException e) {
      // Digest not available, but we still have to report that a repository rule
      // was invoked. So we can do nothing, but ignore the event.
    }
    this.directoryDigest = digest;
```

If the external repository is big (e.g. large test data files, binaries, ...), this hashing can take a significant amount of time. In our build, it takes in the order of minutes and is significant enough that we ended up patching bazel to disable the line above. We don't currently use the [resolved workspace files](https://blog.bazel.build/2018/09/28/first-class-resolved-file.html) feature, so I believe the computed hash will not be used for anything. Could it somehow be calculated lazily only when needed, for example?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Here is a repro case that has a simple repository rule that generates a 10GB file using `fallocate` (which is very fast).

```sh
git clone git@github.com:scele/bazel-bugs.git
cd bazel-bugs/slow-hashing-of-external-repos
bazel clean --expunge --async
time bazel build @bigfile//...
```

On my machine, this takes about 30sec. On a patched bazel where I have removed these lines:
```diff
-      digest = outputDirectory.getDirectoryDigest();
-      repositoryBuilder.put(OUTPUT_TREE_HASH, digest);
```
it takes < 2 seconds. This toy example also shows how the hashing is not really needed for anything, as far as I can tell.

### What operating system are you running Bazel on?

```
Ubuntu 16.04.6 LTS
Linux lpeltonen-dtx 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

### What's the output of `bazel info release`?

```
release 1.1.0
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

For the repro case:
```
git@github.com:scele/bazel-bugs.git
c9c3c93373ae5f4e871bca9d6c54d1fe76e60d8c
c9c3c93373ae5f4e871bca9d6c54d1fe76e60d8c
```

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

Repro logs when running on bazel 1.1.0:

```
$ time bazel build @bigfile//...
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/mnt/data/cache/bazel/_bazel_lpeltonen/2be27ad7c8edb5db97259e3eb2f157be/command.profile.gz'
DEBUG: /home/lpeltonen/src/github.com/scele/bazel-bugs/slow-hashing-of-external-repos/bigfile.bzl:3:5: 
0.00user 0.00system 0:00.02elapsed 19%CPU (0avgtext+0avgdata 2220maxresident)k
936inputs+0outputs (0major+78minor)pagefaults 0swaps
INFO: Analyzed 0 targets (1 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 29.265s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

real    0m29,307s
user    0m0,007s
sys     0m0,006s
```

Repro logs when running on a patched bazel 1.1.0 that has the repository hashing commented out:
```
$ time /path/to/patched/bazel build @bigfile//...
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/mnt/data/cache/bazel/_bazel_lpeltonen/2be27ad7c8edb5db97259e3eb2f157be/command.profile.gz'
DEBUG: /home/lpeltonen/src/github.com/scele/bazel-bugs/slow-hashing-of-external-repos/bigfile.bzl:3:5: 
0.00user 0.00system 0:00.03elapsed 13%CPU (0avgtext+0avgdata 2120maxresident)k
1280inputs+0outputs (0major+77minor)pagefaults 0swaps
INFO: Analyzed 0 targets (1 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 1.542s, Critical Path: 0.02s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

real    0m1,597s
user    0m0,026s
sys     0m0,021s
```

**Comment by laurentlb** [comment]
@aehlig, can you take a look at the suggested fix?

**Comment by aehlig** [comment]
> @aehlig, can you take a look at the suggested fix?

The suggested fix removes the feature of recording the hash in the resolved file unconditionally. This is a policy decision, not a technical decision, if we want to keep the feature. If we're concerned about speed we could restrict the computation of the hash to the cases where a resolved file is actually in use.
