### ISSUE TITLE
BAZEL_SH and --workspace_status_cmd

### ISSUE THREAD

**Issue by solstice333** [bazelbuild/bazel#10151]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Bazel doc says set `BAZEL_SH` to `C:\msys64\usr\bin\bash.exe` if bash cannot be found. Bazel doc says `--workspace_status_cmd <program>` should be a native binary (.exe, .bat, or .cmd). If the workspace status program is a `.sh` should it execute via `BAZEL_SH`? I have a reproducible case where I have git-bash for Windows installed, and I'm building at least one Gerrit plugin. The .sh is associated to git-bash and so results in git-bash executing the workspace status program instead of BAZEL_SH. Is this a Bazel or Gerrit problem?

### Feature requests: what underlying problem are you trying to solve with this feature?

To make it a little more straightforward to do tree-driven Gerrit plugin builds. Ultimately, I had to associate .sh files directly to `C:\msys64\usr\bin\bash.exe` which isn't hard to do, but certainly is something that lessens the "it just works" experience

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Install git-bash for Windows. Install Bazel 1.1.0. Install MSYS2_64. Set `BAZEL_SH` to `C:\msys64\usr\bin\bash.exe`. Clone https://github.com/GerritCodeReview/gerrit.git and checkout tag v2.15.17. Fetch the plugins/hook submodule. Run `bazel build --verbose_failures plugins/hooks` from the top-level of the superproject repo. Build will fail at `.../gerrit/plugins/hooks/BUILD:3:1: Executing genrule //plugins/hooks:hooks failed (Exit 1)`

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

INFO: Invocation ID: 678aa674-91ee-45f8-8672-480b7aa36a71
release 1.1.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

Yes, https://github.com/bazelbuild/bazel/issues/5958. Which makes this sort of a duplicate. Perhaps it's more of a Gerrit issue where the Gerrit devs need to create a wrapper script to deal with conditionally choosing a script based on OS.

### Any other information, logs, or outputs that you want to share?

No

**Comment by davido** [comment]
> Perhaps it's more of a Gerrit issue where the Gerrit devs need to create a wrapper script to deal with conditionally choosing a script based on OS.

There are efforts underway: [1] to migrate `tools/workspace-status.sh` in Gerrit to Python script: 
`tools/workspace-status.py`. Unfortunately, the review process was staled. Your help would be greatly appreciated. Can you port that change to Gerrit core (it was proposed to `plugins/events-log` project) and try to verify it?

Also note that all Gerrit developers I am aware of using Linux and mac OS X.

[1] https://gerrit-review.googlesource.com/c/plugins/events-log/+/236933

**Comment by solstice333** [comment]
Ok, I can take a look at this now. I'll try to cherry-pick it to stable-2.15 and see if things work for me. Thanks.

**Comment by davido** [comment]
> I'll try to cherry-pick it to stable-2.15 and see if things work for me. 

A merge change was already uploaded: [1], just use it.

[1] https://gerrit-review.googlesource.com/c/gerrit/+/243659

**Comment by solstice333** [comment]
Ah, nice, sounds good. Can't wait to try it out.

**Comment by solstice333** [comment]
Tried https://gerrit-review.googlesource.com/c/gerrit/+/243659 (bcf8f57f8) and, in short, it was successful. For anyone running into the same thing, the relevant things (I think) in my environment are 

- OS: Windows 10
- PATH: 
   - C:\msys64\usr\bin (MSYS2 x64), 
   - C:\Program Files\Python37\Scripts\;C:\Program Files\Python37\  (Python 3.7.4), 
   - C:\Program Files (x86)\Common Files\Oracle\Java\javapath (Java 1.8.0_231), 
- BAZEL_SH: C:\msys64\usr\bin\bash.exe
- BAZEL_VC: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC
- JAVA_HOME: C:\Program Files\Java\jdk1.8.0_231

Not sure if all of that is needed, but either way, I tried building plugins/hooks and plugins/download-commands from the gerrit top-level (with my .sh files associated back to git-bash for Windows). The plugins were on the v2.15.17 tag to match the v2.15.17 version of Gerrit I was running:

```
$ bazel build --verbose_failures plugins/hooks
$ bazel build --verbose_failures plugins/download-commands
```

and it works for me. Thanks for all the help. Closing the issue.
