### ISSUE TITLE
Extra "bazel clean --expunge" needed on Windows after submodule update

### ISSUE THREAD

**Issue by stellaraccident** [bazelbuild/bazel#10153]
### Description of the problem / feature request:
Twice over the last month, I have done a submodule update on my project to pick up new commits and one of the repositories that the submodule creates (via a bazel macro) fails to update to the newest version. In both cases, this was seen as what appeared to be an incorrectly cached BUILD/bzl file in the child's child, manifesting as an error because of an incompatible change. I am not sure whether it is specific to BUILD files or all sources -- but I have only seen it on BUILD file diffs.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The first time, I considered this a glitch. The second time was ~a week later. I don't have a solid repro but you can look at my project:

https://github.com/google/iree

The issue has consistently happened specifically with @local_config_mlir repository seeming to cache in out of date BUILD or bzl file which the parent then has an incompatible reference to. Looking at the file on the file system shows the correct version.

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/google/iree.git
1bdc15d87b343951df060fb09446b51028ac2218
1bdc15d87b343951df060fb09446b51028ac2218

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

No. I'll update if I see the issue again. For now I've just clean --expunged once more.

**Comment by stellaraccident** [comment]
I should also note that in the first case, bazel was "hot" in that I did the submodule update during a regular dev workflow and the bazel server was running. The second time, it was a first invocation after coming in in the morning and the bazel server was not running when the submodule update was done. I don't know what level of caching bazel does internally, but I think this eliminates an in memory cache problem.

**Comment by stellaraccident** [comment]
Update: this just happened again on the same sub-repository post checkout of a different branch in the intermediate parent submodule. The sub-repository is @local_config_mlir, and I did this to clear it up:
  bazel shutdown
  rm -Rf /c/users/...{MYUSERINFO}.../aamy3fit/external/local_config_mlir/

I have a lot of sub repositories and it just seems to be consistently affecting this one, so it seems that there is something specific going on here.

The affected submodule is in third_party/tensorflow and defined here: https://github.com/tensorflow/tensorflow/blob/master/third_party/mlir/mlir_configure.bzl

**Comment by philwo** [comment]
Is this still an issue? To be honest, the chance of us being able to reproduce, debug and fix this is probably very slim, unless we can find some way how to consistently reproduce it. :/
