### ISSUE TITLE
No JavaInfo constructor in master documentation

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#10168]
### Description of the problem / feature request:

`JavaInfo` constructor is not documented in the master version.
https://docs.bazel.build/versions/master/skylark/lib/JavaInfo.htm

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Go to https://docs.bazel.build/versions/1.1.0/skylark/lib/JavaInfo.html and see `JavaInfo` constructor is documented. Go to https://docs.bazel.build/versions/master/skylark/lib/JavaInfo.htm and see it's not documented.

There's a chance the constructor has been dropped but then the issue is probably a lot bigger than docs.
cc @iirina

**Comment by ittaiz** [comment]
ping

**Comment by ittaiz** [comment]
dropped here https://docs.bazel.build/versions/1.2.0/skylark/lib/JavaInfo.html
appears last here https://docs.bazel.build/versions/1.1.0/skylark/lib/JavaInfo.html

**Comment by comius** [comment]
The documentation is here
https://docs.bazel.build/versions/master/skylark/lib/JavaInfo.html#JavaInfo

it looks like the link in the description is missing .html ending or this was perhaps already fixed?
