### ISSUE TITLE
How to add android_sdk_repository rule into workspace.bzl?

### ISSUE THREAD

**Issue by shauryad15** [bazelbuild/bazel#10160]
I build tensorflow without android. Now i want to add android_sdk_repository and android_ndk rule into workspace.bzl so that i can build the apk.

I've tried adding :
 android_sdk_repository(
        name = "androidsdk",
        # Set the path to the directory the Android SDK was unzipped into.
        path = "/home/shaurya/Android/Sdk",
        # Set the API level of the installed SDK Platform.
        api_level = 28,
        # Set the version of the build tools (a directory inside build-tools)
        build_tools_version="28.0.2"
    )
into workspace.bzl inside tensorflow but i'm getting this error :**name 'android_sdk_repository' is not defined** need help.

**Comment by jin** [comment]
Use `native.android_sdk_repository` in `.bzl` files.

**Comment by shauryad15** [comment]
You are asking me to replace **android_sdk_repository** to **native.android_sdk_repository**?

**Comment by shauryad15** [comment]
I replaced android_sdk_repository to native.android_sdk_repository but my build is getting failed without any error.

**Comment by jin** [comment]
Oh, I just realized you're working with tensorflow. Have you ran `./configure` and set up Android SDK integration through the script instead? Also, please file an issue with the TensorFlow repository instead.

**Comment by shauryad15** [comment]
hey jin,

I missed integrating at the time of configuration. Hence, i want to add it extensilvely. Can i do that? Also, it's just the edit in workspace.bzl but i don't the correct format that's why.
