### ISSUE TITLE
ijar fails on empty jars

### ISSUE THREAD

**Issue by agrieve** [bazelbuild/bazel#10162]
Here's a repro:

Tested with ijar from bazel 1.1.0.

```sh
$ python -c "import zipfile; zipfile.ZipFile('test.jar', 'w')"
$ ijar test.jar out.jar
size 108 > estimated size 22
Aborted
```

**Comment by lberki** [comment]
Somewhat embarrassing.

**Comment by cushon** [comment]
Out of curiosity, was what real world situation did you encounter this in? Typically `jar` files always have at least `META-INF/MANIFEST.MF` file, especially the ones created by Bazel.

**Comment by agrieve** [comment]
We encountered this in Chrome's build system, which doesn't bother with META-INF files for library targets (just zips up .class files).
