### ISSUE TITLE
Incompatible change in the behavior of '--experimental_generate_json_trace_profile' starting from Bazel 1.x.x

### ISSUE THREAD

**Issue by sha1n** [bazelbuild/bazel#10171]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

I'm trying to generate build profiles using `--profile` in conjunction with `--experimental_generate_json_trace_profile` and the profile file is created in binary format. 
I tested by running the exact same command on the exact same workspace using different bazel versions. It works on bazel 0.29.1 and starting from version 1.0.0, through 1.0.1 and 1.1.0 it stopped working.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run the following build command on the bazel repository and observe the profile file that's created.
`bazel build --profile=profile.json --experimental_generate_json_trace_profile //examples/py/...`

### What operating system are you running Bazel on?

MacOS 10.14.6 (Mojave)

### What's the output of `bazel info release`?

release 1.1.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git@github.com:bazelbuild/bazel.git
c7d2b8d2c8c5f71b6a8d7af0190a0500266bf12b
c7d2b8d2c8c5f71b6a8d7af0190a0500266bf12b

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Will be happy to share any

**Comment by meisterT** [comment]
The JSON profile is turned on by default right starting with Bazel version 1.0.

With that we also turned on gzip compression by default. Can you check if the resulting file is a gzip compressed file?

We probably should turn compression off when the user passes an explicit filename without the `.gz` extension.

**Comment by sha1n** [comment]
Thanks @meisterT, indeed it is gzip compressed.

If you choose to base that behavior on file extension, please consider updating [these](https://docs.bazel.build/versions/master/skylark/performance.html#performance-profiling) instructions. 
I would prefer it to be more explicit BTW. You could either use a dedicated flag, or use one flag with optional value, that can carry output specs.

I updated the title of this issue to better reflect the issue.

**Comment by meisterT** [comment]
There already is such a flag `--experimental_json_trace_compression` which (implicitly) defaults to true starting with Bazel 1.0.

But I guess it's better to avoid confusion and do what the user expects, e.g. if the file is explicitly specified *and* doesn't end with `.gz` then disable compression. I will make the above mentioned flag a tri state with default of auto (which does what I just described). Note that the chrome trace viewer does also treat the file as compressed depending on the extension.

**Comment by meisterT** [comment]
Pending change lives here: https://bazel-review.googlesource.com/c/bazel/+/119893

**Comment by sha1n** [comment]
Thanks @meisterT!

**Comment by sha1n** [comment]
Thanks @meisterT! 
Indeed I see (in the code) that what you say corresponds to the documentation of `--experimental_json_trace_compression`, which defaults to `auto` and should be based on the file extension. However, I can't find that flag in the public CLI reference docs (https://docs.bazel.build/versions/master/command-line-reference.html) - not sure that is intentional.

In any case, what you suggest and the documented behavior of those flags make sense.

**Comment by meisterT** [comment]
Note that I did promote this flag from experimental to stable in the same CL. Its new name is `json_trace_compression`. The old name still works, but the documentation is found under the new name.
