### ISSUE TITLE
java_test "broken" with no guidance how to fix

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/bazel#1017]
https://github.com/bazelbuild/bazel/commit/191d9804047fe2d19c6ca561b6f8de6ccbdc93fb

Apparently can use --legacy_bazel_java_test but there was no clear guidance how to fix rules of the form:
java_test(srcs = glob(["*Test.java"]), ...) with multiple Tests in one rule.

**Comment by damienmg** [comment]
What's your test suite class? You add a main_class before didn't you, just change this main_class for a test_class should works.

**Comment by damienmg** [comment]
Note to myself: fix the relnotes when doing the next bazel release

**Comment by damienmg** [comment]
Also the link to the ml announcement: https://groups.google.com/forum/#!topic/bazel-discuss/r5Qbn1c7eg4

**Comment by pmbethe09** [comment]
I never used a TestSuite or main_class before.   The previous behavior "just worked".

See attached mini example.
bazel test javatests/... --legacy_bazel_java_test
works just fine.  But without the legacy flag:

"Class not found: [tests]"

[Example.zip](https://github.com/bazelbuild/bazel/files/161532/Example.zip)

**Comment by damienmg** [comment]
The glob in the example resolve to only 1 file which is why the legacy behavior where finding the rule. The new behavior use the name of the rule to find the main class (compared to using the srcs if only one file is present like for java_binary). This is the behavior we use since the beginning at Google.

**Comment by pmbethe09** [comment]
Add another class or 2 to blah and the result is still the same.

**Comment by damienmg** [comment]
humm maybe we just take the first one, would be weird. We definitely don't create a test suite out of it.

**Comment by damienmg** [comment]
(PS: the glob has to resolve to multiple files)

**Comment by pmbethe09** [comment]
I don't know *why* it worked, but I can tell you that it did and picked up all of the tests in the glob.
See attached updated example -- run it then cat bazel-out/local_darwin-fastbuild/testlogs/javatests/tests/test.log
(or change target to linux)

I see
"
JUnit version 4.12
.Bar
.Foo

Time: 0.004

OK (2 tests)
"

It appears that org.junit.runner.JUnitCore was added as the main_class when none was specified, and that picked up all of the tests in the first jar 'javatests' jar file on the classpath.
This was easily be confirmed via experimentation/printlns

However, adding this class as the test_class and running without the '--legacy_bazel_java_test', gets me to a new failure "
1) initializationError(org.junit.runner.JUnitCore)
java.lang.Exception: No runnable methods
"

**Comment by pmbethe09** [comment]
and attachment
[Example.zip](https://github.com/bazelbuild/bazel/files/162480/Example.zip)

**Comment by damienmg** [comment]
The test_class should be a test class. not the JUnitCore runner.

Oh yes the legacy behavior allow multiple test file in the srcs. Humm... not sure we should do anything there.

**Comment by pmbethe09** [comment]
Easy enough to write a genrule to take my SRCS and generate
an org.junit.runners.Suite, but as I wrote, sad that this just worked
before, and now I have to add a layer of my own.

**Comment by pmbethe09** [comment]
If anyone else runs into this -- I created a junit_tests skylark rule which assumes the srcs are all Junit tests, and creates a native.java_test using a generated test_class.
(attached)
[junit.txt](https://github.com/bazelbuild/bazel/files/182485/junit.txt)

**Comment by ittaiz** [comment]
@damienmg does this mean you can't have a simple test target which runs all tests in the package?

**Comment by alltom** [comment]
It seems like the documentation still needs to be updated. http://www.bazel.io/docs/be/java.html#java_test_examples has an example that just globs `*.java`, and from what I understand in this thread (and trying it on my own), that no longer works.

**Comment by darkcrawler01** [comment]
Please update the documentation
