### ISSUE TITLE
Polymorphic libraries and rpaths

### ISSUE THREAD

**Issue by wesleyw72** [bazelbuild/bazel#10179]
### Description of the problem / feature request:

We're making a library which has two different implementations, acting as a polymorphic library. If I denote the two versions of the library as `libpoly.so(a)` and `libpoly.so(b)`. When testing the different library versions, we've hit a couple of pain points where a binary built with a dep via `cc_import` on `libpoly.so(a)`. It's very difficult to test the same binary against `libpoly.so(b)` as Bazel has hardcoded the path to the binary into the `rpath` of the binary and therefore the dynamic loader can inadvertently pull in the wrong library. 

I'm wondering if there's a way to instead of forcing the rpath of a binary, to instead be able to pass the `LD_LIBRARY_PATH` as an env variable to the actions so that this can be changed to be dependent on what version of the library we want to run against.

**Comment by scentini** [comment]
cc @oquenchil

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
