### ISSUE TITLE
Reproducibility: pkg_deb_impl with postinst and postrm attribute results in unpredictable control.tar.gz file

### ISSUE THREAD

**Issue by andreas-0815-qwertz** [bazelbuild/bazel#10178]
### Description of the problem / feature request:

Using

```
http_archive(
    name = "rules_pkg",
    url = "https://github.com/bazelbuild/rules_pkg/releases/download/0.2.4/rules_pkg-0.2.4.tar.gz",
    sha256 = "4ba8f4ab0ff85f2484287ab06c0d871dcb31cc54d439457d28fd4ae14b18450a",
)

```

in my WORKSPACE together with a homegrown wrapper macro for `pkg_deb_impl`

```
def atos_pkg_deb(name, basename, **kwargs):
    out_deb = basename + ".deb"
    out_changes = basename + ".changes"
    pkg_deb_impl(
        name = name,
        out = name + ".deb",
        deb = out_deb,
        changes = out_changes,
        **kwargs
    )

```

results in a non-predictable file order of the postinst and postrm scripts in the generated `control.tar.gz`, when used in a target definition like

```
atos_pkg_deb(
    name = "ATOS-trc-target-deb-cpu_a",
    basename = "atos-A-TraceCfg-" + atos_version + "-powerpc",
    architecture = "powerpc",
    data = ":ATOS-trc-target-tarball",
    depends = ["cohpa (>= 2)"],
    description = """
 ATO Service
 Copyright: Bombardier Transportation
 Automatic Train Operation Service software
    """,
    maintainer = "http://www.bombardier.com",
    package = "atos-A-TrcConfig",
    version = atos_version,
    postinst = ":postinstall-trace-cohpa",
    postrm = ":postremove-trace-cohpa",
)

```

When I am building the target twice in a row with an intermediate `bazel clean`, I get the output attached with diffoscope 78.
[atos-A-TraceCfg-0.3.0.0-powerpc.html.gz](https://github.com/bazelbuild/bazel/files/3815488/atos-A-TraceCfg-0.3.0.0-powerpc.html.gz)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Please see description above.

### What operating system are you running Bazel on?

Debian GNU/Linux 9.11

### What's the output of `bazel info release`?

`release 1.1.0`

(using bazelisk 1.1.0)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n.a.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n.a.

###  Have you found anything relevant by searching the web?

No, sorry.

### Any other information, logs, or outputs that you want to share?

see attachment.

**Comment by aiuto** [comment]
Please files against bazelbuild/rules_pkg

**Comment by andreas-0815-qwertz** [comment]
Copied to https://github.com/bazelbuild/rules_pkg/issues/114; sorry for the hassle ...
