### ISSUE TITLE
android_local_test's doc for resource_strip_prefix references non-existent resources attr

### ISSUE THREAD

**Issue by justhecuke-zz** [bazelbuild/bazel#10188]
### Description of the problem / feature request:

https://docs.bazel.build/versions/1.0.0/be/android.html#android_local_test.resource_strip_prefix

The doc implies that `resources` is an attr for `android_local_test` even though `resources` itself is not part of the doc and doesn't appear to be supported by Bazel if you try to pass it.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

android_local_test(
  name = "blah",
  resources = "something",
)

$ bazel query //my:blah
> ... no such attribute 'resources' in 'android_local_test' rule

### What operating system are you running Bazel on?

> Replace this line with your answer.

### What's the output of `bazel info release`?

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

release 1.0.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git@github.com:lyft/instant-android.git
a9bf64094d82278e76e901c1513627e09b57eaa3
a9bf64094d82278e76e901c1513627e09b57eaa3

###  Have you found anything relevant by searching the web?

No. Seems that people haven't noticed this discrepancy quite yet.

### Any other information, logs, or outputs that you want to share?

No.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
