### ISSUE TITLE
Absolute paths in `local_config_cc/builtin_include_directory_paths` break caching

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#10187]
### Description of the problem / feature request:

On macOS when the `builtin_include_directory_paths` file is generated it includes an absolute path:

```
This file is generated by cc_configure and contains builtin include directories
that /private/var/tmp/_bazel_ksmiley/36ab5c790411e201d438edcb7aed1d38/external/local_config_cc/wrapped_clang reported. This file is a dependency of every compilation action and
changes to it will be reflected in the action cache key. When some of these
paths change, Bazel will make sure to rerun the action, even though none of
declared action inputs or the action commandline changes.

/Applications/Xcode-11.2.0-beta2.app/Contents/Developer
/Applications/Xcode-11.2.1-GM1.app/Contents/Developer
/Applications/Xcode-10.3.0.app/Contents/Developer
/Applications/Xcode-10.2.1.app/Contents/Developer
/Applications/Xcode-11.2.0.app/Contents/Developer
/Applications/Xcode-11.2.0-beta1.app/Contents/Developer
/Applications/Xcode-11.1.0-GM1.app/Contents/Developer
/Applications/Xcode-11.0.0-GM2.app/Contents/Developer
/Applications/
```

This is caused by writing `cc` to the file:

https://github.com/bazelbuild/bazel/blob/bd0a40254697ec7e0cd9a522cf5ba282ea76389c/tools/cpp/lib_cc_configure.bzl#L242

Since macOS CC is defined by this absolute path:

https://github.com/bazelbuild/bazel/blob/bd0a40254697ec7e0cd9a522cf5ba282ea76389c/tools/cpp/osx_cc_configure.bzl#L84

In the meantime developers can disable this behavior entirely by setting `BAZEL_IGNORE_SYSTEM_HEADERS_VERSIONS=1` in their environment.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 1.1.0

###  Have you found anything relevant by searching the web?

This is very related to https://github.com/bazelbuild/bazel/issues/10184 which can hopefully be fixed by https://github.com/bazelbuild/bazel/pull/10185 but I wanted to track it separately because that PR will not fix this issue.

**Comment by slam** [comment]
This bug is as severe as #10184. They both break remote cache on MacOS. Is it possible to also fix this bug in the upcoming 1.2.0 release?

**Comment by keith** [comment]
I haven't submitted any fixes for this, but in the meantime you should set `BAZEL_IGNORE_SYSTEM_HEADERS_VERSIONS=1` when execing bazel (we do this from a wrapper script to have a single place for all these workarounds)

**Comment by keith** [comment]
To elaborate part of the problem here is that some of this is intended (at least for other platforms) where if users have different system headers for their tooling they may need to not share the cache. The reason I think this is a problem for macOS / iOS is just because there's no requirement for how developers name their Xcode versions, or how many they have, which means your cache hit rate could be very low very often. Since this is abstracted in bazel in general with `--xcode_version` it would be nice to be abstracted here as well.

**Comment by slam** [comment]
Thank you for the explanation.

The enumeration of the Xcode versions in this file is less of a problem for us. We’ve  always instructed our devs to set up their local Xcode env identical to how we set it up on the build machines. It is actually good to make it a cache miss if their local setup deviates.

Long term we don’t plan to use `BAZEL_IGNORE_SYSTEM_HEADERS_VERSIONS`. If we’ve already missed the fix window for 1.2 to fix this bug with the absolute cc path, I’ll use the env var as a workaround when 1.2 comes out.

**Comment by keith** [comment]
If all developers and build machines have Xcode setup the same way what contents of this file is breaking you?

**Comment by slam** [comment]
This path from your example in the description: `/private/var/tmp/_bazel_ksmiley/36ab5c790411e201d438edcb7aed1d38/external/local_config_cc/wrapped_clang`

The user name and repo root directory name are embedded in that path. I don’t believe #10185 fixes that.

**Comment by keith** [comment]
Ah yes you're right. My change did not fix that. There was a comment here about not letting this return an absolute path, but there was not a resolution https://github.com/bazelbuild/bazel/pull/10185#issuecomment-551606348

**Comment by slam** [comment]
And come to think of it, I don't quite understand why `builtin_include_directory_paths` is even necessary of macOS/iOS builds. It seems that Xcode version is already encoded in the action cache, as evident in this `src/tools/execlog:parser` output that I captured while debugging this remote cache breakage:

```
environment_variables {
  name: "XCODE_VERSION_OVERRIDE"
  value: "10.2.0.10E125"
}
```

It seems like with `XCODE_VERSION_OVERRIDE` if Xcode gets changed the action cache will already be invalidated...

**Comment by keith** [comment]
I think it might be possible depending on your PATH and maybe some other environment variables to have non-Xcode specific paths in this file. But I agree that is unlikely. I will submit a PR deleting this for macOS for discussion

**Comment by slam** [comment]
You are right. These are the env vars in one of the action files, for example:

```
environment_variables {
  name: "APPLE_SDK_PLATFORM"
  value: "MacOSX"
}
environment_variables {
  name: "APPLE_SDK_VERSION_OVERRIDE"
  value: "10.14"
}
environment_variables {
  name: "PATH"
  value: "/bin:/usr/bin:/usr/local/bin"
}
  environment_variables {
  name: "XCODE_VERSION_OVERRIDE"
  value: "10.2.0.10E125"
}
```

We set `--incompatible_strict_action_env` in our `.bazelrc` to make sure we all have the same `PATH` as documented here: https://github.com/bazelbuild/bazel/issues/6648

**Comment by keith** [comment]
I submitted https://github.com/bazelbuild/bazel/pull/10281

AFAICT I can't get other paths to end up here so this should be safe
