### ISSUE TITLE
Missing symbols during header compilation

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/bazel#10186]
### Description of the problem / feature request:

Very similarly to #6456 we are seeing missing symbols (Symbol not found) errors during compilation of a class that is available in the transitive closure, but not declared as a strict-dep, rather than a strict-deps error.  When we pass `--nojava_header_compilation` we get the strict deps error.  If we do `--nojava_header_compilation --experimental_strict_java_deps=warn` we see the strict deps error (as a warning) and the build succeeds. 

### Feature requests: what underlying problem are you trying to solve with this feature?

We don't want to see symbol not found errors, when it's actually a strict deps error which should be showing a more useful error. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Don't have a public repro-case for this. I'll try to work one up.  Internally, we have a simple `//f->//e->//d->//c->//b->//a` relationship where the source file whose symbol is not found can be seen in a `bazel query somepath(//f, //a:src/main/java/some/pkg/MissingFile.java)`.  The file is definitely in the transitive closure. But it symbol-not-found errors during header compilation.

### What operating system are you running Bazel on?

MacOS

### What's the output of `bazel info release`?

1.1.0

**Comment by cgruber** [comment]
cc: @inez who ran into this.

**Comment by comius** [comment]
This seems to be affecting quite an old version. If it still exists, please reopen.
