### ISSUE TITLE
globs miss hidden files

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#10197]
### Description of the problem / feature request:
Globs of filegroups miss hidden (`.foo.bar`) files.
I see this since I have an attribute in a rule that accepts certain file types (using `allow_files`), and when that attribute depends on the filegroup I get `in deps attribute of printer rule //attributes:some_target: '//attributes:sources' does not produce any printer deps files (expected .scala)`.  (In the above example the glob is for `*.scala` and there is a `.foo.scala` file).
Important to add that when the glob is on the attribute then it evaluates correctly (sees `.foo.scala`). When the glob is on the filegroup but the file is not hidden (`foo.scala`) it also works and finally when the filegroup has an explicit file (`srcs = [".foo.scala"]`) and the rule depends on the filegroup it also works. 

The only case that doesn't work is attribute that depends on a filegroup that uses a glob that should evaluate to a single hidden file but does not.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
git clone git@github.com:ittaiz/examples
cd examples
git checkout patch-1
cd rules/attributes
bazel build :some_target #see failure
ll -a #see .foo.scala
```

### What operating system are you running Bazel on?

macOS 10.13.6

### What's the output of `bazel info release`?

1.1.0
###  Have you found anything relevant by searching the web?

I'm basically trying to work around #7516 by always making sure I have a file that matches the glob while not getting in the way of my users (hence why I want to hide the file)

**Comment by ittaiz** [comment]
we have a workaround for #7516 so we won't need this. Still probably worth fixing as is unclear and surprising.

**Comment by laurentlb** [comment]
This looks like a bug in the glob function, and it's not related to filegroup.
Examples, after `touch .foo.scala`:

```
print(glob(["*.scala"]))
# no match

print(glob([".*.scala"]))
# matches .foo.scala

print(glob(["*"]))
# matches .foo.scala
```

The [documentation](https://docs.bazel.build/versions/master/be/functions.html#glob) says that hidden files are matched by the `*` wildcard.

(fyi, @haxorz)

**Comment by haxorz** [comment]
Based on the comments & code in UnixGlob#matches, this is WAI. 

https://github.com/bazelbuild/bazel/blob/a4d3da6f2dfc18e1b3fe60ea62bc75e35e0d2002/src/main/java/com/google/devtools/build/lib/vfs/UnixGlob.java#L187 - https://github.com/bazelbuild/bazel/blob/a4d3da6f2dfc18e1b3fe60ea62bc75e35e0d2002/src/main/java/com/google/devtools/build/lib/vfs/UnixGlob.java#L190.

Sounds like the documentation could be more explicit.
