### ISSUE TITLE
custom crosstool doesn't work with sandboxing

### ISSUE THREAD

**Issue by shahms** [bazelbuild/bazel#1019]
Specifically, the sandbox fails to mount the requisite crosstool directories if it resides outside of one of the default mounts.  This will bite us when OS X gets sandboxing as the default there is to use a custom wrapper which resides outside the default mounts.

**Comment by damienmg** [comment]
/cc @philwo that's the bug I talked to you about yesterday. 
/cc @hermione521 fyi

In http://goo.gl/fD4ZsY, I evoked the problem and having the crosstool configuration pass the cxx_include_directories and other pass in a list of system directories of the spawn action would make this works. Not sure how hard it is for the crosstool part but the part on the SpawnAction should be pretty straightforward, especially after the `--sandbox_add_path` change.

For the moment, the only workaround is to deactivate sandboxing: `--spawn_strategy=standalone`

**Comment by shahms** [comment]
the cxx_include_directories are required as is the compiler itself (I encountered this problem trying to do a build on a Linux machine with a crosstool configured similarly to OS X, which uses a local wrapper).

Thinking about this a bit more, it may be complicated by the need to mount the wrapper's dependencies as well.

**Comment by bsilver8192** [comment]
I think you can solve this problem without any Bazel changes by adding files to the appropriate places in `//tools/cpp:BUILD`. My wiki page about [Building with a custom toolchain](https://github.com/bazelbuild/bazel/wiki/Building-with-a-custom-toolchain) has come examples that should work. I've gotten Linux toolchains which are completely independent from the system ones working.

**Comment by damienmg** [comment]
Oh right we could definitely update the cc_configure rules to do it that way. Thanks Brian!

**Comment by ulfjack** [comment]
We're changing the sandbox to avoid this issue. I.e., the default sandbox configuration will allow access to all absolute paths but not to undeclared input files from the workspace. We're also planning to support a stricter sandbox configuration that allows no absolute paths, but mounts a given fs image into the root of the sandbox.

**Comment by ulfjack** [comment]
I'm not sure if the changes will land this week, otherwise they'll be in the release after the next (I expect).

**Comment by philwo** [comment]
Closing as obsolete - this should be long fixed by now.
