### ISSUE TITLE
Do not validate extensions in cc_common

### ISSUE THREAD

**Issue by maximyurchuk** [bazelbuild/bazel#10201]
### Description of the feature request:
Remove validation of extensions in C++ rules. If someone try to use custom header extension following error will be generated 
`'build/bazel/tests/test_header_without_ext/qqq.foo' has wrong extension. The list of possible extensions for 'private_hdrs' are: .h,.hh,.hpp,.ipp,.hxx,.h++,.inc,.inl,.tlh,.tli,.H`

Headers without extension also will lead to an error. 

There are several issues about this problem, for example 
#302
#5182
#6805
#7242
#8111

I suppose bazel can't know about all extensions which people can use, so I propose remove validation of extension. 

### Feature requests: what underlying problem are you trying to solve with this feature?
In our code we want to use own STL implementation and there are no extensions in header files, e.g. `#include <iostream>`. Bazel doesn't support this. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Sample code can be found [here](https://github.com/maximyurchuk/bazel-issues/tree/master/custom_headers_extension)

### What operating system are you running Bazel on?
Windows 10, 1903

### What's the output of `bazel info release`?
`release 1.0.0`

**Comment by scentini** [comment]
As per the reply on the PR, C++ team would prefer to keep validating extensions.

> Hey thank you for the change but we want to continue validating extensions. If you need more flexibility to customize which extensions are allowed through the toolchain, you can send a PR that allows this customization through the toolchain.

https://github.com/bazelbuild/bazel/pull/10202#issuecomment-559461855
