### ISSUE TITLE
The `no-cache` tag / execution requirement is broken for aspects

### ISSUE THREAD

**Issue by thundergolfer** [bazelbuild/bazel#10205]
### Description of the problem / feature request:

In an `aspect` implementation, I am adding the following `execution_requirements` to my `run_shell` action: 

```
        execution_requirements = {
            "no-sandbox": "1",
            "no-cache": "1",
            "no-remote": "1",
        }
```

This _should_ result I think in the aspect's action not being cached, but it is being cached. After a `bazel clean` my aspect's action is run again. 

Using `--execution_log_json_file` to look at things more closely, I can see that with the above `execution_requirements` the `cacheable: true` and `remoteable: true`  lines disappear from the action descriptions. Unfortunately as said above the actions are still cached.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Take the "Simple Example" from https://docs.bazel.build/versions/master/skylark/aspects.html 

and modify it to add: 

```
inputs = []
for src in ctx.rule.attr.srcs:
            for f in src.files:
                inputs.append(f)

ctx.actions.run_shell(
        outputs = [],
        inputs = inputs,
        command = "echo 'hello world' > ~/mytest.txt",
        use_default_shell_env = True,
        execution_requirements = {
            "no-sandbox": "1",
            "no-cache": "1",
            "no-remote": "1",
        }
    )
```

Run the aspect, then delete the `~/mytest.txt` file and run the aspect again. The action will not re-run and `~/mytest.txt` won't be recreated.

### What operating system are you running Bazel on?

`darwin`

### What's the output of `bazel info release`?

`release 1.0.0`

###  Have you found anything relevant by searching the web?

- https://github.com/bazelbuild/bazel/issues/4680
- https://github.com/bazelbuild/bazel/issues/6038

**Comment by chenk008** [comment]
I encountered the same issue in Starlark function.

**Comment by tjgq** [comment]
You're using Bazel incorrectly. An action must declare all of the outputs it produces. If you pass `outputs = []` to an action, Bazel considers it not to create any outputs, so by definition it is always up to date. On the other hand, it wouldn't be possible to declare `~/file.txt` as an output (i.e., in your home directory), because Bazel requires outputs to be in `bazel-out` (if you try it I suspect Bazel will interpret the `~` as a literal filename).
