### ISSUE TITLE
Setting --output_user_root in .bazelrc breaks the build

### ISSUE THREAD

**Issue by WesleyYue** [bazelbuild/bazel#10209]
### Description of the problem:
We use docker containers as a developer environment, and our containers are not expected to be persistent. As such, we set --output_user_root to a mounted volume shared with the host which allows our bazel artifacts to survive past our containers. While this runs fine on our computers, it fails on our CI build with the following error:

```
#!/bin/bash -eo pipefail
bazel build --remote_upload_local_results=true --verbose_failures --config=c++17 -- //... -//[redacted]/...INFO: Invocation ID: 4a7ea28e-b5d9-438f-9bd8-8ce1663a0ff9
ERROR: error loading package '.bazel-cache/user-root/37aacc1b8fc345fede199e633a8f3145/external/io_bazel_rules_closure/closure': Unable to load package for '//closure/private:lines_sorted_test.bzl': BUILD file not found on package path
INFO: Elapsed time: 0.444s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (5 packages loaded)
    currently loading: .bazel-cache/user-root/37aacc1b8fc345fede199e633a8f3145/external/rules_foreign_cc/test ... (2 packages)
```
but when I go to `.bazel-cache/user-root/37aacc1b8fc345fede199e633a8f3145/external/io_bazel_rules_closure/closure/private` and do `ls -alh`, I do see the BUILD file.

```
total 60K
drwxr-xr-x  2 root root 4.0K Nov 11 01:03 .
drwxr-xr-x 10 root root 4.0K Nov 11 01:03 ..
-rw-rw-r--  1 root root  768 Jun 13 12:29 BUILD
-rw-rw-r--  1 root root 1.3K Jun 13 12:29 deb_extract.bzl
-rw-rw-r--  1 root root  11K Jun 13 12:29 defs.bzl
-rw-rw-r--  1 root root 2.3K Jun 13 12:29 file_test.bzl
-rw-rw-r--  1 root root 2.5K Jun 13 12:29 files_equal_test.bzl
-rwxrwxr-x  1 root root 3.1K Jun 13 12:29 gensrcjar.sh
-rw-rw-r--  1 root root 4.5K Jun 13 12:29 java_import_external.bzl
-rw-rw-r--  1 root root 1.5K Jun 13 12:29 lines_sorted_test.bzl
-rw-rw-r--  1 root root 1.7K Jun 13 12:29 platform_http_file.bzl
-rw-rw-r--  1 root root 3.4K Jun 13 12:29 rule_test.bzl
```

I had a similar error previously on my local computer, but it went away after I restarted/nuked the output_user_root folder. 

Any idea what the issue might be?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In .bazelrc:
```startup --output_user_root=/project/.bazel-cache/user-root```

```bazel build //...```

### What operating system are you running Bazel on?

Ubuntu 18.04 Bionic

### What's the output of `bazel info release`?

0.24.1

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

Here is our full .bazelrc config:
```
# Keep bazel cache inside mounted folder for persistance across containers.
startup --output_user_root=/[redacted]/.bazel-cache/user-root

build:c++14 --cxxopt=-std=c++14
build:c++17 --cxxopt=-std=c++17

build:release --copt=-mavx
build:release --copt=-msse4.2

build:using_cuda --define=using_cuda=true
build:using_cuda --action_env TF_NEED_CUDA=1
build:using_cuda --crosstool_top=@local_config_cuda//crosstool:toolchain
build:cuda --config=c++14
build:cuda --config=using_cuda
build:cuda --define=using_cuda_nvcc=true
build:cuda --action_env TF_CUDA_CLANG=0

build:nativeopt --copt=-march=native
build:nativeopt --host_copt=-march=native
build:nativeopt --copt=-O3

build --action_env PYTHON_BIN_PATH="/usr/bin/python"
build --define PYTHON_BIN_PATH=/usr/bin/python

build --define=grpc_no_ares=true

build -c opt

build --remote_upload_local_results=false
build --remote_http_cache=https://storage.googleapis.com/[redacted]
build --google_credentials=[redacted]

```

**Comment by WesleyYue** [comment]
It actually turns out that the issue is with using `//...`. Related issue here: https://github.com/bazelbuild/bazel/issues/4284

**Comment by WesleyYue** [comment]
We solved this problem by mounting the ~/.cache/bazel/ directory inside the container directly through docker instead of using --output_user_root.

**Comment by TheButlah** [comment]
This is causing problems for me. In my case, its not sufficient to continue to use ~/.cache/bazel but with mounted volumes. We actually need to have the outputUserRoot in the current working directory, without any symlinks. We need to avoid `//...` from picking up that folder, for example `.bazel`, as a package.

It would be good if bazel automatically ignores any directories or subdirectories residing in outputUserRoot from wildcards like `//...`. Ignoring the file in `.bazelignore` does not solve the problem, as `.bazelignore` doesn't seem to handle subdirectories.
