### ISSUE TITLE
no such attribute 'imports' in 'py_library' rule

### ISSUE THREAD

**Issue by chenkan1994** [bazelbuild/bazel#1020]
I was trying to compile a python library, but failed, and bazel said:
    no such attribute 'imports' in 'py_library' rule.
which is different from what has been described in http://bazel.io/docs/be/python.html#py_library.imports

Is there anyone who knows why?
Thanks!

**Comment by davidzchen** [comment]
@chenkan1994 Which version of Bazel are you using? The `imports` attribute was added in Bazel 0.2.

**Comment by chenkan1994** [comment]
@davidzchen oops. I was using Bazel 0.1.5. Thank you!

**Comment by chenkan1994** [comment]
@davidzchen I'll download Bazel 0.2 and have a try.

**Comment by chenkan1994** [comment]
@davidzchen OK, it works well in Bazel 0.2, Thanks!
