### ISSUE TITLE
Installing from scratch does not seem to work

### ISSUE THREAD

**Issue by cjds** [bazelbuild/bazel#10208]
### Description of the problem / feature request:

Building from `./compile.sh` on an ARM compiler gives the following error

### Bug

```
env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh
```
```
ERROR: Must specify PROTOC if not bootstrapping from the distribution artifact
```

### What operating system are you running Bazel on?

Running on Raspbian on a Raspvery PI

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
https://github.com/bazelbuild/bazel.git
f8050544937a14d023209d061bc9360bfb9a3e5b
f8050544937a14d023209d061bc9360bfb9a3e5b

This might've worked for older versions of Bazel but doesn't work now
https://gist.github.com/EKami/9869ae6347f68c592c5b5cd181a3b205

**Comment by aehlig** [comment]
The error message accurately describes what is happening. Bootstrapping just from a git checkout requires `bazel` to be told where to find the correct version of various additional tools, including the `protoc` compiler. As described in our [instructions on bootstrapping](https://docs.bazel.build/versions/1.1.0/install-compile-source.html#bootstrap-bazel), the standard way to do so is to use the distribution artifact which already contains the (machine-independent) output of `protoc` (as well as a couple of other generated files); once you have a working version of `bazel`, this artifact can be built from the source tree, so the loop closes. For more background, please read the [design document on the distribution artifact](https://bazel.build/designs/2016/10/11/distribution-artifact.html).
