### ISSUE TITLE
Bazel fails to build with JDK 13

### ISSUE THREAD

**Issue by jonhoo** [bazelbuild/bazel#10214]
### Description of the problem:

JDK 13 was recently released, and it added the new method ([`JDK-8218875`](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8218875)):

```java
FileSystems.newFileSystem(Path, Map<String, ?>)
```

This addition causes [this line of `VanillaJavaBuilder.java`](https://github.com/bazelbuild/bazel/blob/229080d81ffbcb06bbe37cf5c4a540e7f26f1496/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/VanillaJavaBuilder.java#L82) to no longer compile with the error

```
ERROR: src/java_tools/buildjar/java/com/google/devtools/build/buildjar/BUILD:188:1: error executing shell command: '/bin/bash -c set -e;rm -rf bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libbootstrap_VanillaJavaBuilder.jar.build_output bazel-out/host/bin/src/java_tools/buil...' failed (Exit 1)
src/java_tools/buildjar/java/com/google/devtools/build/buildjar/VanillaJavaBuilder.java:82: error: reference to newFileSystem is ambiguous
      filesystems.put(sourceJar, fs = FileSystems.newFileSystem(sourceJar, null));
                                                 ^
  both method newFileSystem(Path,ClassLoader) in FileSystems and method newFileSystem(Path,Map<String,?>) in FileSystems match
Note: src/java_tools/buildjar/java/com/google/devtools/build/buildjar/VanillaJavaBuilder.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

As noted in the [release notes](https://www.oracle.com/technetwork/java/javase/13-relnote-issues-5460548.html#JDK-8218875):

> The addition of `newFileSystem(Path, Map<String, ?>)` creates a source (but not binary) compatibility issue for code that has been using the existing 2-arg `newFileSystem(Path, ClassLoader)` and specifying the class loader as `null`. For example, the following cannot be compiled because the reference to `newFileSystem` is ambiguous:
>
> ```java
> FileSystem fs = FileSystems.newFileSystem(path, null);
> ```
> 
> To avoid the ambiguous reference, this code needs to be modified to cast the second parameter to `java.lang.ClassLoader`.

### What's the simplest, easiest way to reproduce this bug?

Compile Bazel 1.1.0 with JDK 13 set as the system Java version.

### What operating system are you running Bazel on?

Arch Linux

**Comment by Gargo** [comment]
Can anybody at least write how to replace this string? I faced the same problem in another project

**Comment by moderation** [comment]
As per the chat at https://bazelbuild.slack.com/archives/CA31HN1T3/p1611261607021600 I can confirm that the patch from @ll-h works for resolving this error when trying to build `4.0.0` from source on aarch64 with Amazon Corretto 15.

**Comment by meteorcloudy** [comment]
Fixed by https://github.com/bazelbuild/bazel/commit/0216ee54417fa1f2fef14f6eb14cbc1e8f595821
