### ISSUE TITLE
Pass environment variables to query

### ISSUE THREAD

**Issue by samolisov** [bazelbuild/bazel#10226]
### Description of the problem / feature request:
I use a bazel repository rule that require an environment variable (in my case, a path to an LLVM installation). I've tried using `--action_env` as well as `--repo_env` to pass the variable (by some reasons, it can be unsuitable to save the variable in .bashrc as well as in the global list of Windows environment variables) with `bazel info` and `bazel query` (actually I use the bazel plugin for intellij products and it executes these command due to project synchronization). Unfortunately, both commands reply they aren't familiar with that options:

```bash
$ bazel query --tool_tag=ijwb:CLion --output=label_kind --keep_going --curses=no --color=yes --progress_in_terminal_title=no --action_env=LLVM_INSTALL_PREFIX=C:\Work\Dev\llvm\llvm-rel-msvc attr(\"tags\", \"^((?!manual).)*$\", //...:all -//bazel-bin/...:all -//bazel-genfiles/...:all -//bazel-out/...:all -//bazel-testlogs/...:all -//bazel-examples/...:all --exclude //.clwb/...:all) --

ERROR: Unrecognized option: --action_env=LLVM_INSTALL_PREFIX=C:\Work\Dev\llvm\llvm-rel-msvc

$ bazel query --tool_tag=ijwb:CLion --output=label_kind --keep_going --curses=no --color=yes --progress_in_terminal_title=no --repo_env=LLVM_INSTALL_PREFIX=C:\Work\Dev\llvm\llvm-rel-msvc attr(\"tags\", \"^((?!manual).)*$\", //...:all -//bazel-bin/...:all -//bazel-genfiles/...:all -//bazel-out/...:all -//bazel-testlogs/...:all -//bazel-examples/...:all --exclude //.clwb/...:all) --

ERROR: Unrecognized option: --repo_env=LLVM_INSTALL_PREFIX=C:\Work\Dev\llvm\llvm-rel-msvc
```

The problems occur with `bazel query` since it executes repository rules but my rule fails due to an unspecified environment variable.

### Feature requests: what underlying problem are you trying to solve with this feature?
I've found the information that `bazel info` and `bazel query` are actually not actions and therefore the `action_env` flag is not applicable. But I think it can be a good idea to pass environment variables to these commands as well. From my experience, it is a commons sense to use environment variables to pass installation specific parameters into the bazel build infrastructure. For example, Tensorflow uses libraries that change their behavior when an environment variable is specified, Intel MKL for example uses its local copy when the `TF_MKL_ROOT` environment variable is specified.

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 1.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

I've found this issue: https://github.com/bazelbuild/bazel/issues/3465 and the issue has the following answer: 

> It looks like action_env is also used for workspace rules, which seems off (since they are not actions).
> 
> _Originally posted by @ulfjack in https://github.com/bazelbuild/bazel/issues/3465#issuecomment-353029738_
> 

But I believe there should be a way to pass an environment variable into non-action bazel commands at least when they execute repository rules.

**Comment by bhack** [comment]
Any news on this?

**Comment by mvgijssel** [comment]
Running into this problem as well. I've overridden my PATH using action_env, but query fails because it does not pick up the newly defined PATH.
