### ISSUE TITLE
Add support for Mac Catalyst

### ISSUE THREAD

**Issue by TomasLinhart** [bazelbuild/bazel#10223]
Currently, Bazel does not support Mac Catalyst platform, so it is not possible to introduce rules that would allow to build iOS apps for Mac Catalyst. It would be nice to add such support so `bazelbuild/rules_apple` can be modified.

**Comment by jmmv** [comment]
Unfortunately, I do not think we have the plans or resources to do this. We can take contributions in this area, but until they come, I'll have to close this bug as not actionable... sorry!

**Comment by mself** [comment]
It looks like Catalyst support was added in Bazel 3.6.0 in Aug 2020.

**Comment by keith** [comment]
Lets track here: https://github.com/bazelbuild/rules_apple/issues/658
