### ISSUE TITLE
allow_files of attr.label_list does not properly check extensions when used with a filegroup

### ISSUE THREAD

**Issue by t-soliduslink** [bazelbuild/bazel#10228]
### Description of the problem / feature request:

`attr.label_list(allow_files = [ ".cc"])` lets file of any extension slip through when passed in the target of a `filegroup`.

Is this intentional? (I can see that it may be difficult (or inefficient) to check files provided by arbitrary targets. If that is the case, could this be documented, please? I was under the initial impression that `allow_files` means I would not need to perform any file extension checking in my rules' implementations.)

### Bugs: what's the simplest, easiest way to reproduce this bug?

```python
# WORKSPACE
```

```python
# BUILD
load(":foo.bzl", "foo")
filegroup(name = "files", srcs = [ "bar.cc", "foo.bzl" ])
foo(name = "foo1", srcs = [":files"])
foo(name = "foo2", srcs = ["bar.cc", "foo.bzl"])
```

```python
# foo.bzl
def _foo_impl(ctx):
    print([target.files.to_list() for target in ctx.attr.srcs])
    pass

foo = rule(implementation = _foo_impl,
           attrs = { "srcs" : attr.label_list(allow_files = [".cc"]) })
```

```c++
// bar.cc
// intentionally left blank
```

```bash
$ bazel build //:foo1
... succeeds
$ bazel build //:foo2
... fails
```

Expectation was that the build of `//:foo1` would fail, too.

### What operating system are you running Bazel on?

Ubuntu 19.10

### What's the output of `bazel info release`?

`release 1.0.1`

###  Have you found anything relevant by searching the web?

Negative. Searched the existing issues on github for "allow_files".

**Comment by laurentlb** [comment]
From the documentation (https://docs.bazel.build/versions/master/skylark/lib/attr.html#label_list): `allow_files` controls `whether File targets are allowed.`
It doesn't doesn't affect other targets.

If needed, PRs to improve the documentation are welcome.

**Comment by alexeagle** [comment]
@laurentlb I think that's not completely correct. If the filegroup produces no files that match the restriction, bazel does report an error.
Take `ts_library` for example, which is declared with
```
"srcs": attr.label_list(
    allow_files = [".ts", ".tsx"],
),
```

If I write a BUILD file
```
filegroup(name = "foo", srcs = ["b.html"])
ts_library(name = "bar", srcs = [
    "foo"
])
```

then I get an error
`test/BUILD:21:1: in srcs attribute of ts_library rule //test:bar: '//test:foo' does not produce any ts_library srcs files (expected .ts or .tsx)`

which suggests that even though "foo" is not a File target, the allow_files is doing some validation.

**Comment by comius** [comment]
I looks this was fixed - that is documentation says files are checked and they indeed are checked.
