### ISSUE TITLE
Avoid remote java tools in some situations

### ISSUE THREAD

**Issue by krafczyk** [bazelbuild/bazel#10230]
### Description of the problem / feature request:

While trying to build tensorboard on RHEL 6.10, I run into the following problem:

```
ERROR: /scratch/users/mkrafcz2/bazel_output_cpu_noxla_nomkl_ivybridge/external/javax_inject/BUILD:7:1: Extracting interface @javax_inject//:javax_inject failed (Exit 1) process-wrapper failed:
external/remote_java_tools_linux/java_tools/ijar/ijar: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by external/remote_java_tools_linux/java_tools/ijar/ijar)
```

This isn't surprising since RHEL 6.10 has glibc 2.12 and the downloaded toolkit was compiled with glibc 2.14.

### Feature requests: what underlying problem are you trying to solve with this feature?

Is there any simple way to use a bundled system-compiled version of ijar and so forth like what is done with process-wrapper, instead of downloading the remote toolkit in situations like this?

### What operating system are you running Bazel on?

RHEL 6.10

### What's the output of `bazel info release`?

release 0.26.1- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

I built it using a couple patches.

1. Allow me to set the output directory as my system's temp directory is not persistent
2. Allow me to pass additional options through the compile.sh shell script
3. Backport BAZEL_LINKLIBS functionality to get bazel to build and compile code properly on RHEL 6.10.

I then used the script:

```
export BAZEL_LINKOPTS="-static-libstdc++:-static-libgcc"
export BAZEL_LINKLIBS="-l%:libstdc++.a"
OUTPUT_DIR=${BAZEL_OUTPUT} ./compile.sh
```

To build bazel. This bazel has worked for me to build Tensorflow, tensorflow-estimator and tensotflow-hub.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

I downloaded a dist zip file.

###  Have you found anything relevant by searching the web?

No, I think I have a unique problem here.

### Any other information, logs, or outputs that you want to share?

Not right now

**Comment by comius** [comment]
Bazel Java now has supporting for systems with different glibc (will be released after 4.0.0).
Put into one of the build files:
```
load("@bazel_tools//tools/jdk:default_java_toolchain.bzl", 
    "default_java_toolchain", "NONPREBUILT_TOOLCHAIN_CONFIGURATION")

default_java_toolchain(
   name = "custom_toolchain",
   configuration = NONPREBUILT_TOOLCHAIN_CONFIGURATION,
   java_runtime = "@local_jdk//:jdk",
)
```

And run bazel with `--extra_toolchains=//:custom_toolchain_definition`

For more information see https://docs.bazel.build/versions/master/bazel-and-java.html
