### ISSUE TITLE
$(location ..) expansion does not work in cc_library include or linkopts attrs

### ISSUE THREAD

**Issue by shahms** [bazelbuild/bazel#1023]
Trying to reference the location of another rule from within a cc_library attributes fails to work.  I encountered this problem specifically attempting to reference an include directory in attempting to automatically configure local dependencies, but I was able to get it to recur for both files and directories, e.g.

```
bzltest/
  BUILD
  WORKSPACE
  subdir/
    child/
    file
```

=== BUILD ===

```
cc_library(
    name = "bzltest",
    # Adding dirs to srcs/hdrs does not help. 
    includes = [
        "$(location :subdir)",
        "$(location :subdir/child)",
        "$(location :subdir/file)",
    ],
    linkopts = [
        "$(location :subdir)",
        "$(location :subdir/file)",
        "$(location :subdir/child)",
    ],
)

# Also fails identically with filegroup() or simply not declaring them.
exports_files([
    "subdir",
    "subdir/file",
    "subdir/child",
])

# This works, but warns about the directories.
genrule(
    name = "locations",
    srcs = [
        ":subdir",
        ":subdir/file",
        ":subdir/child",
    ],
    outs = ["location.txt"],
    cmd = "echo $(location :subdir) $(location :subdir/file) $(location :subdir/child) > $@",
)
```

Runing the command:

```
$ bazel build :bztltest
ERROR: /tmp/bzltest/BUILD:3:16: in includes attribute of cc_library rule //:bzltest: $(location :subdir) not defined.
ERROR: /tmp/bzltest/BUILD:3:16: in includes attribute of cc_library rule //:bzltest: $(location :subdir/child) not defined.
ERROR: /tmp/bzltest/BUILD:3:16: in includes attribute of cc_library rule //:bzltest: $(location :subdir/file) not defined.
ERROR: /tmp/bzltest/BUILD:8:16: in linkopts attribute of cc_library rule //:bzltest: $(location :subdir) not defined.
ERROR: /tmp/bzltest/BUILD:8:16: in linkopts attribute of cc_library rule //:bzltest: $(location :subdir/file) not defined.
ERROR: /tmp/bzltest/BUILD:8:16: in linkopts attribute of cc_library rule //:bzltest: $(location :subdir/child) not defined.
ERROR: /tmp/bzltest/BUILD:8:16: in linkopts attribute of cc_library rule //:bzltest: $(location :subdir) not defined.
ERROR: /tmp/bzltest/BUILD:8:16: in linkopts attribute of cc_library rule //:bzltest: $(location :subdir/file) not defined.
ERROR: /tmp/bzltest/BUILD:8:16: in linkopts attribute of cc_library rule //:bzltest: $(location :subdir/child) not defined.
```

Versus:

```
$ bazel build :locations
INFO: Found 1 target...
WARNING: /tmp/bzltest/BUILD:27:1: input 'subdir' to //:locations is a directory; dependency checking of directories is unsound.
WARNING: /tmp/bzltest/BUILD:27:1: input 'subdir/child' to //:locations is a directory; dependency checking of directories is unsound.
Target //:locations up-to-date:
  bazel-genfiles/location.txt
INFO: Elapsed time: 0.120s, Critical Path: 0.00s
$ cat bazel-genfiles/location.txt
subdir subdir/file subdir/child
```

It would be really nice to be able to consistently refer to local paths rather than having to guess where the possible enclosing workspace will bind/name them (e.g. external/<repository name>/path).

**Comment by dslomov** [comment]
@laurentlb could you take a look?

**Comment by dslomov** [comment]
Rather, @damienmg

**Comment by damienmg** [comment]
Last change to add more locations was bb46c870ee238c15662d99ab8d6fa0c24197d32b

In short: adding that needs a modification of the Cc* rules implementation. Maybe somewhere in CcCommon

**Comment by ulfjack** [comment]
includes is relative to the current directory, so you should just use:
    includes = [
        "subdir",
        "subdir/child",
    ],

(Adding files in includes does nothing.)

For linkopt, I thought we had added support for that, but maybe I'm misremembering.

**Comment by ulfjack** [comment]
Linkopts doesn't support $(location), but it does automatically expand things that look like labels. The documentation isn't good, and the semantics are a bit unusual, but I think everything should work.

**Comment by ulfjack** [comment]
What's left here to do? We can update the documentation, and we could also support $(location) in linkopts (and maybe remove the 'heuristic' expansion of everything that looks like a label?). I don't think we should change how includes works.

**Comment by shahms** [comment]
I think `includes` is fine how it is (everything in there is a label anyway).  The issue with the heuristic expansion in linkopts (potentially surprising behavior aside) is that things like `-L<relative path>` don't look like labels (the heuristic skips components which start with '-', IIRC).  I think consistently supporting $(location) and removing the heuristic would be the least surprising behavior.

**Comment by ulfjack** [comment]
That sounds about right.

**Comment by shahms** [comment]
Apparently this also doesn't work in `copts` for which it would be desirable for the same reasons as `linkopts`

**Comment by ndrzej** [comment]
Hi! We need this to work:
 "-Wl,@$(location %s)" % linkcmds

The '@<file>' option does not have a two part format like other options and hence the "expand anything that looks walks like a label" does not work in this case.

FYI: There is no way to specify a dynamically derived section-start address otherwise - at least not without much hacking when using GNU.gold. Thus, we need to pass it through a command-options file.

**Comment by Helcaraxan** [comment]
Pinging here as there has not been any activity here for many months.

What is the status on this ticket? It appears work has been done but I am not sure whether the issue was actually solved.

**Comment by kchodorow** [comment]
As @ulfjack summarized in #issuecomment-226107952, there's more we could do.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
