### ISSUE TITLE
Make d8 the default dexer

### ISSUE THREAD

**Issue by gyias** [bazelbuild/bazel#10240]
### Description of the problem / feature request:

Make d8 the default dexer.

### Feature requests: what underlying problem are you trying to solve with this feature?

Now that d8 support has been added, make it the default dexer for bazel after baking it for a while.

**Comment by ahumesky** [comment]
android sdk build tools version 31.0.0 has removed dx, so we'll prioritize getting this fixed probably in the next couple of weeks
