### ISSUE TITLE
error when building from source

### ISSUE THREAD

**Issue by fayeshine** [bazelbuild/bazel#1024]
ERROR: /home/wenjian/pkgs/bazel/src/tools/android/java/com/google/devtools/build/android/BUILD:43:1: Java compilation in rule '//src/tools/android/java/com/google/devtools/build/android:android_builder_lib' failed: Worker process sent response with exit code: 1.
src/tools/android/java/com/google/devtools/build/android/XmlDataResource.java:18: error: package com.google.devtools.build.android.xml does not exist
import com.google.devtools.build.android.xml.ArrayXmlResourceValue;
                                            ^
src/tools/android/java/com/google/devtools/build/android/XmlResourceValues.java:16: error: package com.google.devtools.build.android.xml does not exist
import com.google.devtools.build.android.xml.AttrXmlResourceValue;
                                            ^
src/tools/android/java/com/google/devtools/build/android/XmlResourceValues.java:17: error: package com.google.devtools.build.android.xml does not exist
import com.google.devtools.build.android.xml.IdXmlResourceValue;
                                            ^
src/tools/android/java/com/google/devtools/build/android/XmlResourceValues.java:18: error: package com.google.devtools.build.android.xml does not exist
import com.google.devtools.build.android.xml.PluralXmlResourceValue;
                                            ^
src/tools/android/java/com/google/devtools/build/android/XmlResourceValues.java:19: error: package com.google.devtools.build.android.xml does not exist
import com.google.devtools.build.android.xml.SimpleXmlResourceValue;
                                            ^
src/tools/android/java/com/google/devtools/build/android/XmlResourceValues.java:20: error: package com.google.devtools.build.android.xml does not exist
import com.google.devtools.build.android.xml.StyleXmlResourceValue;
                                            ^
src/tools/android/java/com/google/devtools/build/android/XmlResourceValues.java:21: error: package com.google.devtools.build.android.xml does not exist
import com.google.devtools.build.android.xml.StyleableXmlResourceValue;
                                            ^
src/tools/android/java/com/google/devtools/build/android/XmlDataResource.java:113: error: cannot find symbol
                ArrayXmlResourceValue.parseArray(eventReader, start)));
                ^
  symbol:   variable ArrayXmlResourceValue
  location: class XmlDataResource
src/tools/android/java/com/google/devtools/build/android/XmlResourceValues.java:70: error: cannot find symbol
    return PluralXmlResourceValue.of(values);
           ^
  symbol:   variable PluralXmlResourceValue
  location: class XmlResourceValues
src/tools/android/java/com/google/devtools/build/android/XmlResourceValues.java:83: error: cannot find symbol
    return StyleXmlResourceValue.of(parseReferenceFromElementAttribute(start, ATTR_PARENT), values);
           ^
  symbol:   variable StyleXmlResourceValue
  location: class XmlResourceValues
src/tools/android/java/com/google/devtools/build/android/XmlResourceValues.java:114: error: cannot find symbol
            StyleableXmlResourceValue.of(members)));
            ^
  symbol:   variable StyleableXmlResourceValue
  location: class XmlResourceValues
src/tools/android/java/com/google/devtools/build/android/XmlResourceValues.java:119: error: cannot find symbol
    return AttrXmlResourceValue.from(
           ^
  symbol:   variable AttrXmlResourceValue
  location: class XmlResourceValues
src/tools/android/java/com/google/devtools/build/android/XmlResourceValues.java:124: error: cannot find symbol
    return IdXmlResourceValue.of();
           ^
  symbol:   variable IdXmlResourceValue
  location: class XmlResourceValues
src/tools/android/java/com/google/devtools/build/android/XmlResourceValues.java:130: error: package SimpleXmlResourceValue does not exist
        SimpleXmlResourceValue.Type.from(resourceType), eventReader.getElementText());
                              ^
src/tools/android/java/com/google/devtools/build/android/XmlResourceValues.java:129: error: cannot find symbol
    return SimpleXmlResourceValue.of(
           ^
  symbol:   variable SimpleXmlResourceValue
  location: class XmlResourceValues
Note: src/tools/android/java/com/google/devtools/build/android/ResourceShrinker.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
15 errors
BazelJavaBuilder threw exception: java compilation returned status ERROR
Target //src:bazel failed to build
INFO: Elapsed time: 16.247s, Critical Path: 13.30s

**Comment by Vesnica** [comment]
I have the same error

**Comment by fayeshine** [comment]
besides, I'm using openjdk8 u66

**Comment by Vesnica** [comment]
Oracle jdk 1.8.0_72 here

**Comment by damienmg** [comment]
This is the same issue as in our CI. HEAD is broken

@davidzchen : I assigned you the bug to track. Maybe we should just rollback the causing change

**Comment by damienmg** [comment]
https://github.com/bazelbuild/bazel/commit/3e011b1698bab6aff18497b12396d64bd77ab87b should have fixed it.

**Comment by Vesnica** [comment]
It's working now.
