### ISSUE TITLE
Allow `action_listener`s to be registered in the `WORKSPACE`

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#10244]
### Description of the problem / feature request:

`action_listener`s provide a mechanism for hooking in additional actions when particular events happen. They can be configured via the command line, but it would be advantageous to be able to register them during workspace set up (eg. from the configuration function provided by imported rules)

### Feature requests: what underlying problem are you trying to solve with this feature?

In bazel 1.1.0, they can only be added via command-line flags. This reduces their utility, and means that users need to be made aware of additional flags to pass when building, which isn't always practical (eg. the IJ plugin). We _could_ modify the `.bazelrc`, but that requires people to be aware that they make changes.

A common pattern advocated by the bazel project has been for imported rules to provide a "setup" function of some sort, which is called immediately after loading those rules. It would be very helpful if these setup functions could register new `action_listener`s in much the same way that they can register new toolchains.

###  Have you found anything relevant by searching the web?

No.

**Comment by laurentlb** [comment]
I think we don't recommend the use of action_listener.
Have you considered using aspects instead?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
