### ISSUE TITLE
genrule outputs in bazel-bin instead of bazel-genfiles

### ISSUE THREAD

**Issue by regisd** [bazelbuild/bazel#10256]
### Description of the problem / feature request:

I think this is a regression in Bazel 1.1 compared to 0.27

The `genrule` (and custom rules which have `output_to_genfiles = True`) outputs to `bazel-bin` instead of `bazel-genfiles`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
genrule(
    name = "hello",
    outs = ["hello.txt"],
    srcs = ["BUILD"],
    cmd = "echo $(RULEDIR) > $@",
    output_to_bindir=0,
)
```

```sh
bazel build //:hello
```

> Starting local Bazel server and connecting to it...
> INFO: Writing tracer profile to '/private/var/tmp/_bazel_regis/15bee190ff4e5724bdd67af04a5d1215/command.profile.gz'
> INFO: Analyzed target //:hello (5 packages loaded, 8 targets configured).
> INFO: Found 1 target...
> Target //:hello up-to-date:
>   bazel-bin/hello.txt
> INFO: Elapsed time: 5.655s, Critical Path: 0.11s
> INFO: 1 process: 1 darwin-sandbox.
> INFO: Build completed successfully, 2 total actions

### What operating system are you running Bazel on?

Mac OS Mojave

### What's the output of `bazel info release`?

release 1.1.0

### Any other information, logs, or outputs that you want to share?

The `bazel-genfiles` symlink is not created at all.

**Comment by crorvick** [comment]
I think this was intentional, see #6761.

**Comment by regisd** [comment]
Right, it is indeed.
