### ISSUE TITLE
http_archive re-downloaded for every change in its build_file

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#10269]
### Description of the problem / feature request:

WORKSPACE has the following rule:
```
http_archive(
    name = "boost",
    build_file = "@//thirdparty:boost/boost.BUILD",
    sha256 = ...,
    strip_prefix = ...,
    urls = ...,
)
```

Every time I make any change to boost.BUILD file (which is in my workspace) 'bazel build' re-downloads the archive from the original URL. This is totally unnecessary as the archive stays the same and it is already in the local cache. This re-download may take significant time - 40 seconds in case of Boost library and contradicts to Bazel philosophy of not doing unnecessary work.

### What operating system are you running Bazel on?

Windows 10 1809

### What's the output of `bazel info release`?

release 1.1.0

**Comment by aehlig** [comment]
> Every time I make any change to boost.BUILD file (which is in my workspace) 'bazel build' re-downloads the archive from the original URL.

I cannot reproduce the claimed network traffic. Please reopen with more detailed instructions should bazel indeed call out to the network. Please also keep the following in mind.
- Invalidation on the change of the BUILD file is as desiged, see https://bazel.build/designs/2016/10/18/repository-invalidation.html Several times, it was proposed to have actions also at the level of external repository fetching, but this never became a priority of the project.
- Taking an archive from cache, still its sha256 sum has to be verified which, for a large archive, takes a significant amount of CPU time. Also, the archive has to be unpacked freshly which, for a large archive, can take considerable amount of disk IO.

**Comment by konste** [comment]
@aehlig I have prepared the repro for this issue here: https://github.com/konste/bazel_repro_10269
Clone locally and run `bazel build //main:hello-world` - external repos are downloaded as expected.

Make ANY change to `thirdparty/icu65/icu65.build` file and rerun the build - you will see `Fetching @icu65; fetching`
Make ANY change to `thirdparty/boost/boost.build` file and rerun the build - you will see `Fetching @boost; fetching` which would take much longer (5 min for me) and you definitely can see the network traffic as the archive is redownloaded.

**Comment by jwnimmer-tri** [comment]
For what it's worth, I cannot reproduce this on Ubuntu 18.04 with bazel 1.2.0:

```console
jwnimmer@cons:~/tmp$ git clone https://github.com/konste/bazel_repro_10269.git
Cloning into 'bazel_repro_10269'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 13 (delta 0), reused 13 (delta 0), pack-reused 0
Unpacking objects: 100% (13/13), done.
jwnimmer@cons:~/tmp$ cd bazel_repro_10269
jwnimmer@cons:~/tmp/bazel_repro_10269$ sed -i -e's|BUILD|build|' WORKSPACE 
jwnimmer@cons:~/tmp/bazel_repro_10269$ bazel version
Starting local Bazel server and connecting to it...
Build label: 1.2.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 20 15:04:55 2019 (1574262295)
Build timestamp: 1574262295
Build timestamp as int: 1574262295
jwnimmer@cons:~/tmp/bazel_repro_10269$ bazel build //main:hello-world
INFO: Analyzed target //main:hello-world (15 packages loaded, 239 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /home/jwnimmer/.cache/bazel/_bazel_jwnimmer/a08175c907c36339053f3db03aec64db/sandbox
Target //main:hello-world up-to-date:
  bazel-bin/main/hello-world
INFO: Elapsed time: 28.358s, Critical Path: 0.32s
INFO: 1 process: 1 linux-sandbox.
INFO: Build completed successfully, 2 total actions
jwnimmer@cons:~/tmp/bazel_repro_10269$ echo "# Hello" >> thirdparty/boost/boost.build 
jwnimmer@cons:~/tmp/bazel_repro_10269$ bazel build //main:hello-world
INFO: Analyzed target //main:hello-world (1 packages loaded, 5 targets configured).
INFO: Found 1 target...
Target //main:hello-world up-to-date:
  bazel-bin/main/hello-world
INFO: Elapsed time: 9.413s, Critical Path: 0.00s
INFO: 0 processes.
```

The first build hits the network (and takes a while -- 28 seconds).  The second build does not hit the network (but still takes 9 seconds to compute checksums).

**Comment by konste** [comment]
@jwnimmer-tri Are you sure to make a change to third party build file before the second build? Without the change it does not redownload for me either. But if I make any insignificant change to say boost.build it definitely redownloads boost from internet. It reproduces for me on Windows.

**Comment by jwnimmer-tri** [comment]
Yes -- I did `echo "# Hello" >> thirdparty/boost/boost.build` in the above.  Without adding that line, the build only takes a few tens of milliseconds.  After adding the Hello, it takes around 9 seconds.

**Comment by konste** [comment]
@jwnimmer-tri I made exactly the same change to the build file as you - added `# Hello` comment at the end and got a repro. Now important notice - that message `Fetching @icu65; fetching` does not show up in the final console output! It shows up temporary for the time of the download after `Analysing target...` then it disappears and get replaced with `INFO: Found 1 target...`

**Comment by konste** [comment]
It would be rather weird, but it could be Windows specific issue.

**Comment by jwnimmer-tri** [comment]
For me (in curses mode, the default for interactive terminals) the "Fetching..." outputs are always ephemeral, even when it is doing real downloading.  To notice whether this bug exists, I am not looking at the console output, I'm just watching my network I/O graph as bazel runs.

**Comment by jwnimmer-tri** [comment]
... and just to be super clear, the message `    Fetching @boost; fetching` does not necessarily mean that a download is happening.  It can also mean the validation operations described above https://github.com/bazelbuild/bazel/issues/10269#issuecomment-558687448 are happening.

**Comment by konste** [comment]
Is there a way to get some kind of low level trace of what Bazel is doing? In the meanwhile I am trying to run it under Process Monitor trying to catch what exactly it is doing when it says "Fetching..."

**Comment by jwnimmer-tri** [comment]
I don't know of any tracing, but I'm not a bazel developer.

From personal experience, times on the order of 30 seconds for a boost source archive are par for the course when the repository is invalidated -- without any new downloads.  It just takes a while to re-verify the archive, unpack it, inventory the files, or whatever else bazel is doing.  The size and number of files is just that big.

If you are seeing 160MB of network traffic, then that would be a bug; but if it's just taking 30 +/- seconds to , that's consistent with my expectations and not a bug (or at least, not a "re-downloaded" bug).

**Comment by konste** [comment]
First of all, @jwnimmer-tri you are right that it is not a "re-downloaded" bug. Indeed Bazel does not re-download boost when boost.build is changed, but here is what it actually does (per Process Monitor trace):
1. "Analysing targets..." message shows up.
2.  3 min 14 sec it does full rescan of <workspace>/external/boost folder. 
3. "Fetching @boost; fetching" message shows up and stays to almost the end of the build 
4. 0.4 sec - reading the archive file in the content addressable cache (hashing?)
5. 1.5 sec - copying of the archive file from content addressable cache to <workspace>/external/boost folder
6. 1 sec - reading the same archive file again in <workspace>/external/boost folder
7. 6 min 34 sec - unpacking the archive file to <workspace>/external/boost folder
8. Copying boost.bazel file over to <workspace>/external/boost folder
9. 3 min 24 sec - second full rescan of <workspace>/external/boost folder

This behavior does not seem optimal.
1. There is no need to scan <workspace>/external/boost folder because we know that archive hash did not change.
2. There is no need to rehash the file in content addressable cache.
3. There is no need to copy the archive to unpack it.
4. There is no need to unpack the archive and rehash the folder again because we know that the archive is bit to bit the same as it was. 

This boils down to the build taking 13 min instead of 0.5 sec because of doing all those unnecessary steps. Looks like a performance bug to me.

**Comment by konste** [comment]
@aehlig Could you please reopen this issue to investigate performance problems discovered?

**Comment by hofst** [comment]
@aehlig Why his this issue been closed? It is obviously a performance bug that impacts many projects, even if there is no network traffic and only the archive get moved around and redundantly decompressed.
