### ISSUE TITLE
Cannot find variable named 'xcode_version_override_value' while using a custom rule

### ISSUE THREAD

**Issue by oakad** [bazelbuild/bazel#10268]
I have a following construct in a custom rule I'm using:
```
  cc_toolchain = find_cpp_toolchain(ctx)
  fcfg = cc_common.configure_features(ctx = ctx, cc_toolchain = cc_toolchain)
  env = cc_common.get_environment_variables(
    feature_configuration = fcfg,
    action_name = ACTION_NAMES.cpp_compile,
    variables = cc_common.empty_variables(),
  )
```

The purpose of this construct is to properly initialize the environment for code generator tools.

This works fine on Linux and Windows, and, until recently, on MacOS.

However, I'm unable to use my rules with bazel 1.1.0-homebrew on MacOS. `get_environment_variables` function always fails with "Cannot find variable named 'xcode_version_override_value'" message.

I have tried all the usual xcode tricks, bazel clean/shutdown, etc.

**Comment by scentini** [comment]
cc @oquenchil

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
