### ISSUE TITLE
Dependencies coming from the sealed external repo are still checked for changes

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#10273]
### Description of the problem / feature request:

WORKSPACE has the following rule:
```
http_archive(
    name = "boost",
    build_file = "@//thirdparty:boost/boost.BUILD",
    sha256 = ...,
    strip_prefix = ...,
    urls = ...,
)
```

I build the target which directly depends on the files from that archive. Bazel does not re-download the archive and it is correct, but it still hashes all the files the target depends on looking for the possible changes. This is pointless as the archive has not change as Bazel already knows. In case of Boost library it means re-hashing of 11000 files and adds 10 seconds to every build even when nothing has changed. 

### What operating system are you running Bazel on?

Windows 10 1809

### What's the output of `bazel info release`?

release 1.1.0

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
