### ISSUE TITLE
bazel --help does not provide help for installing a build [duplicate of #5849]

### ISSUE THREAD

**Issue by noloader** [bazelbuild/bazel#10283]
I'm trying to build TensorFlow from sources. TensorFlow requires Bazel. I believe TensorFlow is built. I can't figure out how to get Bazel to install TensorFlow. Naively I tried `bazel install` but that did not work. The command results in *`Command 'install' not found. Try 'bazel help'`*. I also tried `bazel build --install`, and it failed too. I'm out of guesses.

When I run `bazel --help` for the instructions, no information is provided for the install:

```
$ bazel --help 
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
                                                          [bazel release 0.26.0]
Usage: bazel <command> <options> ...

Available commands:
  analyze-profile     Analyzes build profile data.
  aquery              Analyzes the given targets and queries the action graph.
  build               Builds the specified targets.
  canonicalize-flags  Canonicalizes a list of bazel options.
  clean               Removes output files and optionally stops the server.
  coverage            Generates code coverage report for specified test targets.
  cquery              Loads, analyzes, and queries the specified targets w/ configurations.
  dump                Dumps the internal state of the bazel server process.
  fetch               Fetches external repositories that are prerequisites to the targets.
  help                Prints help for commands, or the index.
  info                Displays runtime info about the bazel server.
  license             Prints the license of this software.
  mobile-install      Installs targets to mobile devices.
  print_action        Prints the command line args for compiling a file.
  query               Executes a dependency graph query.
  run                 Runs the specified target.
  shutdown            Stops the bazel server.
  sync                Syncs all repositories specified in the workspace file
  test                Builds and runs the specified test targets.
  version             Prints version information for bazel.

Getting more help:
  bazel help <command>
                   Prints help and options for <command>.
  bazel help startup_options
                   Options for the JVM hosting bazel.
  bazel help target-syntax
                   Explains the syntax for specifying targets.
  bazel help info-keys
                   Displays a list of keys used by the info command.
```

`configure`, `make`, `make install` is a standard cycle when building software from sources. It would be incredibly helpful if `bazel --help` provided the information necessary to install the software.

-----

Tail of TensorFlow build:

```
  'build' options: --host_force_python=PY2 --action_env PYTHON_BIN_PATH=/usr/bin/python --action_env PYTHON_LIB_PATH=/usr/local/lib/python2.7/dist-packages --python_path=/usr/bin/python --config=xla --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:xla in file /home/jwalton/speech/tensorflow-1.15.0/.tf_configure.bazelrc: --define with_xla_support=true
WARNING: Usage: bazel build <options> <targets>.
Invoke `bazel help build` for full description of usage and options.
Your request is correct, but requested an empty set of targets. Nothing will be built.
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
INFO: Analyzed 0 targets (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 5.358s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
Command 'install' not found. Try 'bazel help'.
```

**Comment by benjaminp** [comment]
It's not in `help` because no such support exists. #5849

**Comment by laszlocsomor** [comment]
Indeed, bazel doesn't support `install`. Sorry, but I don't think we'll implement it any time soon.

**Comment by noloader** [comment]
> Sorry, but I don't think we'll implement it any time soon.

That is unfortunate.

I'm not a Bazel or Python person. I have no idea how to install the software. I depend on the build system to do it.

How is one supposed to install the software?

**Comment by laszlocsomor** [comment]
https://www.tensorflow.org/install/source seems to help -- I think you need to follow from https://www.tensorflow.org/install/source#build_the_package

**Comment by noloader** [comment]
Thanks @laszlocsomor.

If Bazel is not going to provide the functionality, then the project should probably document the lack of support in `bazel --help`. There's no reasons for users like me to keep wasting our time looking for a solution. I assumed I was doing something wrong.

Something like:

```
$ bazel --help 
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
                                                          [bazel release 0.26.0]
Usage: bazel <command> <options> ...

  ...
  test                Builds and runs the specified test targets.
  version             Prints version information for bazel.
  install             Not implemented
```

**Comment by laszlocsomor** [comment]
Sorry, that seems odd to me. Do other tools document features they don't have?

**Comment by noloader** [comment]
> Sorry, that seems odd to me. Do other tools document features they don't have?

Yes, it does think out of the box.

I don't really know what other Bazel-like tools do since I am not a Bazel/Python guy. In my languages (C, C++ and ObjectiveC), it is very unusual to lack the ability to install using the toolchain.

For me, I look at it in an economic model. It would take 5 minutes to document it as an option. Or, hundreds of users can waste hundreds of man hours searching for it. It is more economical for the project to document it in on place.

I help maintain a couple of open source C++ libraries. If I have a partial implementation, I throw a `NotImplemented` exception. I do it for the benefit of the users. It is least expensive for me to signal it in one place than waste a lot of people's time.

**Comment by jin** [comment]
This is something that can go into the Bazel FAQ. 

https://bazel.build/faq.html

**Comment by laszlocsomor** [comment]
Sorry, I still see no reason to add it to `bazel help`. Not because it's hard, but because it makes no sense to me. I appreciate you want to help other Bazel beginners, that's great, but in this case I don't see why this really helps.

Because, I guess if you're new to Bazel and assume it supports `install`, you might try running `bazel install`. Bazel says `Command 'install' not found. Try 'bazel help'.`, so you run `bazel help`. Alas `install` is not listed. Why would you then assume that you're doing something wrong? I don't understand.

**Comment by noloader** [comment]
> Not because it's hard, but because it makes no sense to me. I appreciate you want to help other Bazel beginners, that's great, but in this case I don't see why this really helps.

I'm guessing it makes no sense to you because you are a maintainer, and you know the tool is missing the basic functionality.

I wasted about an hour trying to figure out how to perform the install. There's a mobile install. so there (should|must) be a native install. There's nothing special about me. If I have wasted the time, others have too.

It would have _really_ helped me if Bazel told me it lacked the basic functionality.

[Here](https://pastebin.com/LfLPzSjB) is the script I was working on. It _really_ was trying to call `bazel install`, bazel build --install` and other things I could conceive.

**Comment by laszlocsomor** [comment]
In the script, line 100, it calls `bazel build` with no arguments. This has no effect: you must specify a build target to build, e.g. `bazel build //tensorflow/tools/pip_package:build_pip_package`. I assume you wrote that because some build tool(s) you're familiar with support this syntax to build a default target. But Bazel doesn't, it's a different tool. It just does nothing if you don't specify build targets.

Perhaps the website should have "Differences with $TOOL" pages or FAQ entries where we point these things out. The Starlark language page also has a "[Differences with Python](https://docs.bazel.build/versions/master/skylark/language.html#differences-with-python)" section -- very reasonably so.

**Comment by laszlocsomor** [comment]
Also wanted to say that I'm sorry you wasted an hour on this, I know that feels frustrating.
