### ISSUE TITLE
default xml test output missing any timing information

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#1028]
just has tests, failures and errors. Would be nice to include the timing, which is reported by bazel so obviously measured.

**Comment by damienmg** [comment]
The default xml output is very basic and the correct way to do it is to have a custom test runner per language just as we do for Java.

**Comment by benjaminp** [comment]
The fallback xml now includes a `duration` field, so I think this is fixed?

**Comment by aiuto** [comment]
Closing for staleness since we have duration now and as @damienmg pointed out, the good solutions is to add per-language information.
