### ISSUE TITLE
Bazel v1.2.0 accidentally no longer runs on macOS High Sierra

### ISSUE THREAD

**Issue by chenrui333** [bazelbuild/bazel#10297]
### Description of the problem:

I am trying to upgrade Bazel to v1.2.0 in this PR, https://github.com/Homebrew/homebrew-core/pull/46983#issuecomment-556462751

The error only happens on highsierra build. And I can totally reproduce in my repo as well.

```
Uncompressing......Mismatched bazel version. Found '' expected '1.2.0'.
Installing bazel 1.2.0
Downloading bazel installer for bazel 1.2.0
/tmp/bazel-1.2.0-installer.sh: line 1: syntax error near unexpected token `newline'
/tmp/bazel-1.2.0-installer.sh: line 1: `<!DOCTYPE html>'
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/xx/.bazel/bin/bazel-real (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
```

### What operating system are you running Bazel on?

Mac OS highsierra

**Comment by philwo** [comment]
Thank you for reporting this @chenrui333! I will prepare a patch release on Monday that will restore High Sierra compatibility.

I've also replied on the Homebrew bug that you linked.

**Comment by chenrui333** [comment]
@philwo really appreciate your quick turnaround on this!!

**Comment by philwo** [comment]
@chenrui333 If you have access to a Mac with High Sierra, could you please try out this binary? If not, don't worry, I can try later at home on a VM.

https://releases.bazel.build/1.2.1/rc1/bazel-1.2.1rc1-darwin-x86_64

If it works, I will release it as Bazel 1.2.1 tomorrow. Thanks again for the quick report.

**Comment by soonho-tri** [comment]
@philwo , I tried it on a machine running MacOS-10.13.6 and it worked!

**Comment by chenrui333** [comment]
@philwo I don't have High Sierra machine, but I guess @soonho-tri already verified on my behalf. 

If you can release a tag, I can test and verify thru homebrew-core CI pipeline.

**Comment by chenrui333** [comment]
I guess I managed to push a change to regression testing on the Mac machines now, https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/52457/

**Comment by ittaiz** [comment]
@philwo is HighSierra going to be dropped in 2.0?

**Comment by philwo** [comment]
> @philwo is HighSierra going to be dropped in 2.0?

No.

**Comment by ittaiz** [comment]
👍 fair enough. Thanks!

**Comment by chenrui333** [comment]
👍 Thanks for the quick turnaround on this issue.

**Comment by philwo** [comment]
Bazel 1.2.1 has been released to restore compatibility with macOS High Sierra.

@chenrui333 You're welcome. 😊Please let me know if you run into any other issues.
