### ISSUE TITLE
Support generating CLion project files (IDE integration)

### ISSUE THREAD

**Issue by kayasoze** [bazelbuild/bazel#1029]
This support may be significantly easier than other IDEs, as the target is a CMakefile.  I have a sample script which works well, though it uses `bazel query` and not the new aspect API.

**Comment by ulfjack** [comment]
We are working on this, though we don't have any announcements right now. Sorry. :-( Don't let that stop you.

**Comment by XperielIndigo** [comment]
This would be amazing to have! In the mean time, @kayasoze would you mind sharing your script? That would be really helpful so we can stop maintaining a CMakeLists.txt to support CLion.

**Comment by kayasoze** [comment]
I hate to say this, @XperielIndigo, but my employer does not allow internal source code to be open sourced.  I can say, however, that bazel query's XML output is your friend.  There are a few bugs in CLion which prevent building from the generated targets, but you can at least index them.

I've also found it useful to write a small script, callable from CLion, which uses bazel query to run all tests which could be affected by the current file under the cursor, and parse the output.

**Comment by dslomov** [comment]
This should be filed the tracker for IntelliJ plugin: https://github.com/bazelbuild/intellij/issues.
I actually think they support CLion by now.
