### ISSUE TITLE
Feature: Expose `hdrs` of cc_library in its providers

### ISSUE THREAD

**Issue by immars** [bazelbuild/bazel#10300]
### Description of the problem / feature request:

Expose `hdrs` of cc_library in its providers

### Feature requests: what underlying problem are you trying to solve with this feature?

The problem discussed in https://groups.google.com/forum/#!topic/bazel-discuss/778s8s2Ty-c

In my scenario, we need to export/deploy libraries produced by `cc_library` together with its public header files declared in `hdrs` and shared them with other team. 

To achieve that, I'm trying to implement a custom rule with dependency to a `cc_library` and package library and header files into a single .tar.

However, I cannot find a field within `CcInfo` or any other Providers of `cc_library` to determine the content of `hdrs`. the closest is `CcInfo.compilation_context.headers`, but it includes all header files in `hdrs` and `srcs`.

It will be good to have an additional field in `CcInfo`, or an individual Provider to indicate the content of `hdrs`. 

### What operating system are you running Bazel on?

macosx 10.15, ubuntu 16.04

### What's the output of `bazel info release`?

release 1.2.0

###  Have you found anything relevant by searching the web?

https://groups.google.com/forum/#!topic/bazel-discuss/778s8s2Ty-c

### Any other information, logs, or outputs that you want to share?

the rule is declared as :

```bazel
cc_package = rule(
    implementation = _package_impl,
    attrs = {
        "library" : attr.label(),
        "strip_include": attr.string(default = ""),
        "prepend_include": attr.string(default = "")
    }
)
```

expected usage:
```
cc_library(
    name = "hello-time",
    srcs = ["hello-time.cc", "hello-internal.h"],
    hdrs = ["hello-time.h"],
    visibility = ["//visibility:public"],
)

cc_package(
    name = "package_hello",
    library = ":hello-time"
)
```

**Comment by cocasema** [comment]
I'd love to get this rule as well!

Right now we have to use something hacky like this (it works only if cc_package is in the same BUILD file as the cc_library it refers to):
 
```
def _cc_package_impl(ctx):
    headers = []
    for src in ctx.attr.srcs:
        headers += [h for h in src[CcInfo].compilation_context.headers.to_list()
                    if src.label.package in h.path
                    and h.extension in ["h", "hpp"]]
    return [DefaultInfo(files=depset(headers))]

cc_package = rule(
    attrs={
        "srcs": attr.label_list(providers=[CcInfo]),
    },
    implementation=_cc_package_impl,
)```

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
