### ISSUE TITLE
Add force_pic to cc_common.link API

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#10303]
Currently there is no way to make the cc_common API force_pic.

More discussion https://github.com/bazelbuild/bazel/pull/10143

**Comment by oquenchil** [comment]
I rather not add force_pic to cc_common.link if there is a different way so that we can keep the API as small as possible.

Can you try by iterating over every library_to_link and for each one build a new library_to_link with just the pic_static_library instead of having the static_library in there too. I believe then that the logic defaults to just taking the pic libraries without any complaints.

Please let me know if that works.

**Comment by keith** [comment]
Sorry, this issue was probably a bit too prescriptive based on the recommendation from the linked PR

I tried your recommendation here, it's pretty nasty since we don't actually create the libraries ourselves, we just forward the CcInfo so instead of doing this https://github.com/bazelbuild/rules_swift/blob/2a20daa7ce087195b3fe0dbde78f7c5209526946/swift/internal/linking.bzl#L235

We have to do something like:


```bzl
for dep in deps:
    if CcInfo in dep:
        cc_info = dep[CcInfo]

        new_inputs = []
        for linker_input in cc_info.linking_context.linker_inputs.to_list():
            libraries = []
            for lib in linker_input.libraries:
                libraries.append(
                    cc_common.create_library_to_link(
                        actions = actions,
                        cc_toolchain = swift_toolchain.cc_toolchain_info,
                        feature_configuration = cc_feature_configuration,
                        pic_static_library = lib.pic_static_library,
                        alwayslink = True,
                    ),
                )

            new_inputs.append(
                cc_common.create_linker_input(
                    owner = owner,
                    user_link_flags = depset(linker_input.user_link_flags),
                    additional_inputs = depset(linker_input.additional_inputs),
                    libraries = depset(libraries),
                ),
            )

        linking_contexts.append(
            cc_common.create_linking_context(
                linker_inputs = depset(new_inputs),
            ),
        )
```

Which if nothing else seems like it might cause some memory usage issues given the deconstruction of depsets. I'm not sure why `alwayslink = True,` was required in my testing, but without that I ended up getting missing symbols in this case.
