### ISSUE TITLE
is "exec_compatible_with" ignored in cc_library?

### ISSUE THREAD

**Issue by luxe** [bazelbuild/bazel#10319]
### Description of the problem / feature request:

Wish to clarify support on `cc_library`'s `exec_compatible_with` attribute

### Feature requests: what underlying problem are you trying to solve with this feature?

I am looking for a way to use `exec_compatible_with` in a `cc_library` rule to affect the toolchain evaluation.  We want some rules to use clang, and other rules to use nvcc simultaneously from the same build invocation. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Assume a platform with a constraint:
```
platform(
    name = "platform",
    constraint_values = [
        "@bazel_tools//platforms:x86_64",
    ],
)
```

Two toolchains exist, but only 1 of them are compatible:
```
toolchain(
    name = "example_1",
    exec_compatible_with = [
        "@bazel_tools//platforms:x86_64",
    ],
    target_compatible_with = [
        "@bazel_tools//platforms:x86_64",
    ],
    toolchain = ":cc-compiler-local",
    toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
)

toolchain(
    name = "example_2",
    exec_compatible_with = [
    ],
    target_compatible_with = [
    ],
    toolchain = ":cc-compiler-local2",
    toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
)
```

The cc_library should choose example_1 toolchain:  
```
cc_library(
    exec_compatible_with = ["@bazel_tools//platforms:x86_64" ],
     **kwargs
)
```
But it does not, it still chooses example_2.

Both toolchains are provided in the bazelrc file with `--extra_toolchains`

### What operating system are you running Bazel on?
lsb_release -a
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

### What's the output of `bazel info release`?

release 1.1.0

###  Have you found anything relevant by searching the web?

I don't think what I want to do is supported.  

https://docs.bazel.build/versions/master/toolchains.html#toolchain-resolution
Toolchain Resolution
**Note: Some Bazel rules do not yet support toolchain resolution.**

https://docs.bazel.build/versions/master/be/common-definitions.html#common.exec_compatible_with
exec_compatible_with
This attribute is available only on genrule, shell rules, and all test rules (*_test).

Will this work in the future? am I doing something conceptually wrong?

**Comment by irengrig** [comment]
Toolchains are matched in the order they are registered; please check that you are not passing more generic toolchain first.

**Comment by luxe** [comment]
cc library rules do not yet participate in toolchain resolution (#7260). That was my issue.
