### ISSUE TITLE
Support for unused deps with aliases

### ISSUE THREAD

**Issue by Jamie5** [bazelbuild/bazel#10318]
Currently the unused_deps tool at https://github.com/bazelbuild/buildtools seems to not work with aliases, such as in this situation:

```
java_library(
    name = "c",
    srcs = ["C.java"],
    deps = [":d2"],
)

alias(
    name = "d2",
    actual = ":d"
)

java_library(
    name = "d",
    srcs = ["D.java"]
)
```

where C and D are independent of each other.

The unused_deps tool does not report any issues. Changing the dep from ":d2" to ":d" (i.e. no longer using the alias) causes the error to be reported as expected.

What would be the way to support unused_deps correctly reporting unused dependencies reported via aliases? (This issue might also apply to exports, but did not test that).

Does the functionality that java rules provide already give the needed information to make unused_deps work in this situation, or is additional functionality needed?

cc @ittaiz

(Note: this is the same as https://github.com/bazelbuild/rules_java/issues/24 but feels like this repository might be the right place for this)

**Comment by ittaiz** [comment]
@cushon maybe you are the right person to ask? I know we had many discussions about this in the past

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
