### ISSUE TITLE
incompatible_always_check_depset_elements: depset: depset(direct=...) constructor does not check element validity

### ISSUE THREAD

**Issue by alandonovan** [bazelbuild/bazel#10313]
The depset(direct=...) constructor that we have been recently migrating users towards does not apply the same element validity checks as the legacy depset([...]) constructor. Consequently one can insert mutable items such as structs and tuples containing lists:

```
x = [1, 2, 3]
s = depset(direct = [(x,)])
print(s)  # 'depset([([1, 2, 3],)])'

x.append(4) 
print(s) # 'depset([([1, 2, 3, 4],)])'
```

The fix is to apply the same checks as done by the legacy constructor, but this is a breaking change. The new check will thus be behind a flag called `--incompatible_always_check_depset_elements`.

**Comment by laurentlb** [comment]
Can you check if `s = depset([(x,)])` behaves correctly? This is the notation most people have been using. Also, please check what happens with the `--incompatible_disable_depset_items` flag.

I suspect this migration should be a blocker for https://github.com/bazelbuild/bazel/issues/9017.

**Comment by alandonovan** [comment]
Without the flag, depset([(x,)]) reports an error if and only if x is (or contains) a mutable value. With the flag, the expression succeeds even if x is (or contains) a mutable value. I could not see any difference between Blaze at tip and the previous release of Blaze, which is encouraging.
