### ISSUE TITLE
Add default_tags to the package

### ISSUE THREAD

**Issue by cocasema** [bazelbuild/bazel#10320]
### Description of the feature request:

Add `default_tags` to the [package](https://docs.bazel.build/versions/master/be/functions.html#package) function (similar to existing `default_visibility`).

### What underlying problem are you trying to solve with this feature?

The primary use-case for this feature request is to make project packaging rules easier to maintain and update.

In our codebase we have a separate directory ("distrib") for rpm/deb/etc. packaging rules alongside the "source" directory in each project. Packaging (building actual .deb/.rpm files) is also less frequent action than building/testing apps/services, and, therefore, all these rules in "distrib/BUILD" are explicitly marked as `manual` to save developers time when they run "bazel build ...". Also many of these rules depend on some volatile values / generated files  - like build number, etc., so they are also manually tagged with `no-cache` to avoid uploading never-to-be-reused artifacts to the remote cache.

This manual process of adding the very same set of tags to all rules in a package is both inconvenient and error-prone. I believe it can be simplified with

`package(default_tags=["manual", "no-cache"])`

I'd expect it to behave similarly to `default_visibility` attribute.

###  Have you found anything relevant by searching the web?

Nope.

**Comment by aiuto** [comment]
We don't want to add any `default_*` things to `package` until we fix the semantics on that. The fact that `package` only applies to targets after the `package` statement is a foot-gun.  There is no chance we are going to want to build this, nor accept a PR for this until we get a better handle on this concept.

**Comment by fmeum** [comment]
@tetromino @aiuto Is the problem of package placement mattering still present?
