### ISSUE TITLE
Bazel CI: deleting maven_jar broke downstream projects with bazel@head

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#10322]
Deleting the deprecated maven_jar rule broke several Bazel CI downstream projects we build with Bazel@HEAD. (These projects were apparently not migrated.)

Context: https://github.com/bazelbuild/bazel/pull/10237

Examples:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1294#cbe4d084-810d-4349-aedd-a938fbcbf8b2
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1294#1210713f-262e-4363-a30c-f4dcd14d7d00

```
/tmp/tmpai0tx989/bazel-bin/src/bazel --nomaster_bazelrc --bazelrc=/dev/null info
--
  | ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/a54b96b5dc1b1db87092e917fef4e796/external/build_bazel_integration_testing/tools/bazel_java_integration_test.bzl:161:3: Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/builds/bk-docker-dvg0/bazel-downstream-projects/intellij/WORKSPACE", line 281
  | bazel_java_integration_test_deps(<1 more arguments>)
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/a54b96b5dc1b1db87092e917fef4e796/external/build_bazel_integration_testing/tools/bazel_java_integration_test.bzl", line 161, in bazel_java_integration_test_deps
  | native.maven_jar(<2 more arguments>)
  | type 'struct' has no method maven_jar()
  | ERROR: error loading package '': Encountered error while reading extension file 'protobuf_deps.bzl': no such package '@com_google_protobuf//': error loading package 'external': Could not load //external package
  | Traceback (most recent call last):
  | File "bazelci.py", line 2887, in <module>
  | sys.exit(main())
  | File "bazelci.py", line 2867, in main
  | bazel_version=task_config.get("bazel") or configs.get("bazel"),
  | File "bazelci.py", line 831, in execute_commands
  | bazel_version = print_bazel_version_info(bazel_binary, platform)
  | File "bazelci.py", line 1048, in print_bazel_version_info
  | + ["--nomaster_bazelrc", "--bazelrc=/dev/null", "info"]
  | File "bazelci.py", line 1689, in execute_command
  | args, shell=shell, check=fail_if_nonzero, env=os.environ, cwd=cwd
  | File "/usr/local/lib/python3.6/subprocess.py", line 438, in run
  | output=stdout, stderr=stderr)
  | subprocess.CalledProcessError: Command '['/tmp/tmpai0tx989/bazel-bin/src/bazel', '--nomaster_bazelrc', '--bazelrc=/dev/null', 'info']' returned non-zero exit status 2.
```

Unfortunately it's not easy to roll back the culprit commit (88126f8ef345aeb20f2271b23a6a7100202b63fa), because two others (6884507aca322fa18afa39512a2a6177f2423ef5, 87da3f63b25a65505468bd55bc6158f511a05cac) are built on it, and apparently the rollback isn't clean.

**Comment by laszlocsomor** [comment]
@jin @dslomov @meisterT

**Comment by jin** [comment]
It looks like deleting maven_jar != flipping the incompatible change flag, and has a much wider impact that then downstream tests I did in https://github.com/bazelbuild/bazel/pull/10090 and https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1251#4a75bdb5-0eba-494a-afaa-39b6f3112c7b 

I'll see what I can do, especially on the migration tooling front.

**Comment by c-parsons** [comment]
Any updates?

**Comment by jin** [comment]
Yes: see https://github.com/bazelbuild/bazel/issues/10131#issuecomment-560459918

The only failing pipeline is protobuf, which will be fixed by https://github.com/protocolbuffers/protobuf/pull/6970

**Comment by jin** [comment]
All of the known failures have been migrated. Will wait for tonight's downstream to confirm.

**Comment by laszlocsomor** [comment]
Awesome @jin , thank you!

**Comment by jin** [comment]
The remaining failures are not maven_jar related.

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1306

**Comment by senpo** [comment]
I found the removal of maven_jar also breaks https://github.com/bazelbuild/tools_android, which we use to build firebase android apps. Is the tools_android repo still maintained?

``
ERROR: /private/var/tmp/_bazel_senpo/8e8ab08dfe8b1ede4ab2e2dba795577f/external/tools_android/tools/googleservices/defs.bzl:36:3: Traceback (most recent call last):
	File "/Users/senpo/Sources/github/senpo/senpo-mono/workspace/WORKSPACE", line 81
		google_services_workspace_dependencies()
	File "/private/var/tmp/_bazel_senpo/8e8ab08dfe8b1ede4ab2e2dba795577f/external/tools_android/tools/googleservices/defs.bzl", line 36, in google_services_workspace_dependencies
		native.maven_jar(<2 more arguments>)
type 'struct' has no method maven_jar()
``

**Comment by senpo** [comment]
Never mind. I found these changes that fix the issue. Cool.
https://github.com/bazelbuild/examples/commits/master/android/firebase-cloud-messaging/WORKSPACE
