### ISSUE TITLE
Can't build tensorflow_serving

### ISSUE THREAD

**Issue by 72L** [bazelbuild/bazel#1032]
I'm following directions here: 
https://tensorflow.github.io/serving/setup#prerequisites

Everything works great except for:
bazel build tensorflow_serving/...

I get the error:
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/external/tf/google/protobuf/BUILD:520:1: no such package 'util/python': BUILD file not found on package path and referenced by '@tf//google/protobuf:internal/_api_implementation.so'.

**Comment by damienmg** [comment]
Why was this reported in the Bazel issue tracker (I think it should have gone in the tensorflow/serving one)?

As for that, it seems like you have missed the configuration step.
