### ISSUE TITLE
incompatible_load_proto_toolchain_for_javalite_from_com_google_protobuf: Use javalite toolchain from Protobuf master

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/bazel#10335]
Flag: `--incompatible_load_proto_toolchain_for_javalite_from_com_google_protobuf`
Available since: 2.2
Will be flipped in: 3.0
Tracking issue: #9992

Historically, the runtime for `java_lite_proto_library` was developed in a dedicated branch of the [Protobuf repository](https://github.com/protocolbuffers/protobuf/tree/javalite). Recently, this was changed, and the latest javalite runtime/toolchain is now available on master (and will be in future releases). This incompatible flag changes the default value of `--proto_toolchain_for_javalite` to point to the new toolchain on master.

To become compatible with this incompatible change, users will have to update their version of Protobuf. We will not flip this flag before a compatible Protobuf release has been available for at least 6 weeks.

Note for triage: This is probably `P2` and `team-Rules-Server`. Please also add `incompatible-change` and `breaking-change-3.0` (and maybe assign it to me).

# Migration

If you are using `java_proto_library`, you need to update your `WORKSPACE` to load Protobuf (`@com_google_protobuf`) to version 3.11.3 or later. Starting with Bazel 3.0, you can start removing uses of `@com_google_protobuf_javalite` from your `BUILD`-files and delete it from `WORKSPACE`.

//cc @steeve @lberki @hlopko

**Comment by Yannic** [comment]
@irengrig This flag was added in https://github.com/bazelbuild/bazel/commit/613de1fbbff10de5d6f99f15882fb145a5007f7e. Can you add the labels to get this tested on the incompatible pipeline?

**Comment by siddharthab** [comment]
If this flag is not available in 2.0 and 2.1, can we remove the labels so bazelisk works well?

**Comment by laurentlb** [comment]
We're supposed to cut Bazel 3.0 now. Was this flag flipped?

**Comment by lberki** [comment]
Argh, no. Let me send a change.

**Comment by Yannic** [comment]
I prepared a PR for flipping this some time ago, but it was blocked on the release of Bazel 2.2.
Feel free to use https://github.com/bazelbuild/bazel/pull/10745 as inspiration :).

**Comment by lberki** [comment]
Indeed! Let me just import it then.
