### ISSUE TITLE
When creating a SkylarkKey from a label, the @repo_name prefix doesn't work inside repo_name

### ISSUE THREAD

**Issue by oquenchil** [bazelbuild/bazel#10338]
Example:
```
  private static final Provider.Key CC_SHARED_INFO_PROVIDER_RULES_CC =
      new SkylarkKey(
          Label.parseAbsoluteUnchecked("@rules_cc//examples:experimental_cc_shared_library.bzl"),
          "CcSharedLibraryInfo");
```
When we are in the rules_cc repository and we have a target that accesses this provider. The provider won't be found because the actual label for the provider will not have the @rules_cc repo prefix in the label.

This forces to check for the above and the following for the case where the target is in @rules_cc:

```
  private static final Provider.Key CC_SHARED_INFO_PROVIDER =
      new SkylarkKey(
          Label.parseAbsoluteUnchecked("//examples:experimental_cc_shared_library.bzl"),
          "CcSharedLibraryInfo");
```

**Comment by aehlig** [comment]
This is correct behavior.

> ```
>   private static final Provider.Key CC_SHARED_INFO_PROVIDER_RULES_CC =
>       new SkylarkKey(
>           Label.parseAbsoluteUnchecked("@rules_cc//examples:experimental_cc_shared_library.bzl"),
>           "CcSharedLibraryInfo");
> ```

`Label.parseAbsoluteUnchecked` expects as argument a String representing the canonical form of a label, i.e., with all applicable repository mapping already applied. If this cannot be achieved, `Label.parseAbsolute` with the repository mapping as argument should be used. Note that also for the main repository, the mapping is not necessarily empty, as it contains the map from its name to the empty string.
