### ISSUE TITLE
Fetch info in --build_event_text_file

### ISSUE THREAD

**Issue by emranbm** [bazelbuild/bazel#10343]
### Description of the problem / feature request:

In a typical Bazel project, running `bazel build :main --build_event_text_file log.txt`, for example, produces a file containing what happened during the build.  
But it doesn't contain any info about what dependencies where fetched. This is needed for determining what to cache (in the --distdir).  
Currently, the logs in the CI server seem like below and I have no idea what's being fetched in background.
```
Analyzing: target //:main (0 packages loaded, 0 targets configured)
Analyzing: target //:main (0 packages loaded, 0 targets configured)
Analyzing: target //:main (0 packages loaded, 0 targets configured)
Analyzing: target //:main (0 packages loaded, 0 targets configured)
Analyzing: target //:main (0 packages loaded, 0 targets configured)
Analyzing: target //:main (0 packages loaded, 0 targets configured)
Analyzing: target //:main (0 packages loaded, 0 targets configured)
```

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm trying to figure out what is the dependencies and provide them to the CI server (by --distdir option), so it doesn't re-download dependencies each time.

### What operating system are you running Bazel on?

Ubuntu 16.04 LTS

### What's the output of `bazel info release`?

release 0.29.1

###  Have you found anything relevant by searching the web?

I didn't find anything there but asked [a question on StackOverflow](https://stackoverflow.com/questions/59028430/bazel-build-command-ambiguous-stdout-stderr-while-piped) by myself.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
