### ISSUE TITLE
incompatible_proto_output_v2: new protobuf structure for aquery output

### ISSUE THREAD

**Issue by joeleba** [bazelbuild/bazel#10358]
**Flag:** `--incompatible_proto_output_v2`
**Available since:** 3.0
**Will be flipped in:** 4.0

## Motivation
aquery causes OOM while handling large queries due to:
1. It's large output size.
2. It's monolithic way of writing the output.

This new redesign of the output format aims to tackle these 2 problems.

## Changes

The new proto format: [`analysis_v2.proto`](https://source.bazel.build/bazel/+/master:src/main/protobuf/analysis_v2.proto;l=25;drc=587c73610064b3b163b680ae49675b8e6177c518)

**1. Change ids field in aquery's proto output from `string` to `uint32`.**
While this is the recommended best practice for proto, it makes the output unnecessarily big. Changing the type to `uint32` should cover our use cases, while decreasing the output size.

**2. Introducing `PathFragment`.**
Instead of writing exec paths as purely strings, we can intern them by using `PathFragment`s.

**3. Streaming aquery proto output.**
Currently aquery's proto output is generated in a monolithic manner, i.e. the whole [ActionGraphContainer](https://source.bazel.build/bazel/+/master:src/main/protobuf/analysis.proto;l=25;drc=ed99017be6c26047d843a7fef12094ae7f520836) is constructed in memory and then at the end printed to an output file. This requires the whole proto object to live in memory, which might cause OOMs. By restructuring the proto format and stream the result instead, we can avoid this situation.

## Migration

Consumers of aquery `proto`, `textproto` and `json` outputs should make the following changes (`text` output remains unaffected):
- Change `id` fields from `string` to the [corresponding language-specific](https://developers.google.com/protocol-buffers/docs/proto#scalar) equivalence of `uint32`.
- Change [`Artifact#exec_path`](https://source.bazel.build/bazel/+/master:src/main/protobuf/analysis_v2.proto;l=25;drc=587c73610064b3b163b680ae49675b8e6177c518) to [`Artifact#path_fragment_id`](https://source.bazel.build/bazel/+/master:src/main/protobuf/analysis_v2.proto;l=45;drc=587c73610064b3b163b680ae49675b8e6177c518)

**Example migration for [aquery_differ](https://source.bazel.build/bazel/+/master:tools/aquery_differ/aquery_differ.py;l=28?q=aquery_differ):** https://github.com/bazelbuild/bazel/commit/7f93647261efdb02b8f135874afebc245d57ed17

**Comment by laurentlb** [comment]
Can you add labels for this? (https://www.bazel.build/breaking-changes-guide.html)

**Comment by joeleba** [comment]
This is not yet ready for migration.

**Comment by joeleba** [comment]
This flag is now ready for migration. Updated the appropriate labels.
