### ISSUE TITLE
`depset` should treat targets with same basepath and name as duplicates

### ISSUE THREAD

**Issue by nkoroste** [bazelbuild/bazel#10378]
### Description of the problem / feature request:

given a targets:
`depset(["//foo/bar", "//foo/bar:bar"])`
since `//foo/bar` and `//foo/bar:bar` are the same target `depset` should treat them as duplicates and remove them from the list

### Feature requests: what underlying problem are you trying to solve with this feature?

This would help with creating genrules

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`t = depset(["//foo/bar", "//foo/bar:bar"])`
`print(t)` should print only `//foo/bar:bar`

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

1.2.1

**Comment by laurentlb** [comment]
These are strings and `"//foo/bar" != "//foo/bar:bar"`. I don't think we can (or want to) implement this FR.

In macros, the `depset` type is not very useful (the main use-case is for collecting transitive dependencies in a rule). You can use a dictionary to remove duplicates, or the [`sets`](https://github.com/bazelbuild/bazel-skylib/blob/master/docs/new_sets_doc.md) type for Skylib. With a bit of string processing, you can convert the labels into absolute labels. We should add a function for that in Skylib (you may file a feature request there).

**Comment by nkoroste** [comment]
From the documentation of `to_list` (https://docs.bazel.build/versions/master/skylark/lib/depset.html#to_list):
> Returns a list of the elements, without duplicates, in the depset's traversal order. 

Similar documentation implied for `get_transitive_srcs()`  in https://docs.bazel.build/versions/master/skylark/depsets.html

I guess based on that I'm expecting the resulting list not to include duplicate **build targets**. In the example I provided the strings are obviously different but they point to the same build target.

**Comment by jasonprado** [comment]
5 years on, if anyone else finds this thread I believe there is an idiomatic way to deduplicate `deps` in a macro. The key is `native.package_relative_label` which seems to do the right thing in turning both `"//foo/bar"` and `"//foo/bar:bar"` into the same `Label`. Then you can use bazel skylib's `sets` to do the deduplication.

Unless I'm missing something, this gave me a solution that does not rely on string manipulation.
