### ISSUE TITLE
pkg_deb(built_using)'s documentation is wrong

### ISSUE THREAD

**Issue by pkern** [bazelbuild/bazel#1037]
The documentation says this about pkg_deb's built_using:

> String or File, default to 'Bazel'
> The tool that were used to build this package provided either inline (with <code>built_using</code>) or from a file (with <code>built_using_file</code>).

This is not what Built-Using is for in Debian. Please read §7.8 on [https://www.debian.org/doc/debian-policy/ch-relationships.html]:

> Some binary packages incorporate parts of other packages when built but do not have to depend on those packages. […] A Built-Using field must list the corresponding source package for any such binary package incorporated during the build […]

Something like "Bazel" should certainly not be stored there, as it's not a package name. (Although I did not actually find the default in the code, maybe I'm blind.) "bazel (0.1.1)" as suggested in the overview would be technically ok (and should not cause the package to be rejected if bazel exists) but is not really the thing we'd need to list there. `make` would not need to be listed there either.

It's nice to have the field available, but it should never be set automatically. Thanks.

**Comment by dslomov** [comment]
@damienmg, please take a look

**Comment by aiuto** [comment]
Agreed. The field should be empty by default. I'll send a PR

**Comment by aiuto** [comment]
Fixed in #7921
