### ISSUE TITLE
Enable generating redistributable Java script

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#10373]
### Description of the problem / feature request:

While `java_binary` already creates a executable, it is not runnable outside of `/*.runfiles`.
The problem is that `needs_runfiles` overwrites the `--singlejar` option.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

```
release 1.2.1
```

### Any other information, logs, or outputs that you want to share?

Currently we workaround this via a `genrule`:
```
sed 's/"1" == 1/"0" == 1/g' "$1"
```

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
