### ISSUE TITLE
C++ actions don't report their env variables to Starlark properly

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#10376]
Envrionment variables specified through feature configuration are not visible from Starlark, making it not possible to recreate C++ actions in Starlark on Darwin.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
