### ISSUE TITLE
Can't replace C++ std with OSX default toolchain

### ISSUE THREAD

**Issue by oliverdain** [bazelbuild/bazel#10385]
### Description of the problem / feature request:

If you create a simple Bazel build on OSX the compile lines include `-std=c++11`. But I'm using C++14. I can put `build --cxxopt=-std=c++14` in a `.bazelrc` and that kind of works but it doesn't *replace* the `-std=c++11` - the compile line contains both the `-std=c++11` and the `-std=c++14`. The latter seems to override the former so it works but it seems brittle (i.e. is this ordering guaranteed?).

I can also put `copts = ["-std=c++14"]` in the `BUILD` file for every target. However, that gets completely ignored and does not appear in the compile line (verified via `bazel build -s ...`).

### Feature requests: what underlying problem are you trying to solve with this feature?

I don't think the default toolchain should specify a C++ language version. That means if you using a different version you have to write your own toolchain which is a huge task. If nothing else, there should be an easy way to change the language version.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
Olivers-MBP:bazel oliverdain$ ls -a
.		..		.bazelrc	BUILD		WORKSPACE	example.cpp
Olivers-MBP:bazel oliverdain$ cat .bazelrc
build --cxxopt=-std=c++14
Olivers-MBP:bazel oliverdain$ cat WORKSPACE
Olivers-MBP:bazel oliverdain$ cat BUILD
cc_binary(
   name = "example",
   srcs = [ "example.cpp" ]
)
Olivers-MBP:bazel oliverdain$ cat example.cpp
//
// example.cpp
// Revl
//
// Created by Oliver Dain on 12/07/2019
// Copyright © 2019 Revl. All rights reserved.
//

#include <iostream>

using namespace std;

int main(int argc, char** argv) {
  cout << "I ran" << endl;
}
Olivers-MBP:bazel oliverdain$ bazel build -s :example
INFO: Analyzed target //:example (14 packages loaded, 107 targets configured).
INFO: Found 1 target...
SUBCOMMAND: # //:example [action 'Compiling example.cpp', configuration: 1c5cb9b987c51d10e1122821fa456a963a3ff5afd325b68244662d42b3048be5]
(cd /private/var/tmp/_bazel_oliverdain/c86ea362b0f6ec05e4e55b0eda264fd0/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.15 \
    PATH='/Users/oliverdain/.poetry/bin:/Users/oliverdain/bin:/Users/oliverdain/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/oliverdain/.fzf/bin' \
    XCODE_VERSION_OVERRIDE=11.2.1.11B500 \
  external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' -iquote . -iquote bazel-out/darwin-fastbuild/bin -iquote external/bazel_tools -iquote bazel-out/darwin-fastbuild/bin/external/bazel_tools -MD -MF bazel-out/darwin-fastbuild/bin/_objs/example/example.d '-frandom-seed=bazel-out/darwin-fastbuild/bin/_objs/example/example.o' -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks '-mmacosx-version-min=10.15' '-std=c++14' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c example.cpp -o bazel-out/darwin-fastbuild/bin/_objs/example/example.o)
```

Note that both `std=c++11` and `std=c++14` are given as compiler flags. And note that using `copts` in the `BUILD` instead doesn't improve things.

### What operating system are you running Bazel on?

OSX Mojave - 10.14.6

### What's the output of `bazel info release`?

`release 1.2.1-homebrew`

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` 

N/A

###  Have you found anything relevant by searching the web?

I have done lots of searching. Have found some bugs suggesting it should be easier to change the c++ version and some posts that suggested the `.bazelrc` solution but nothing that points out that it's impossible to *change* the C++ version.

**Comment by oliverdain** [comment]
Ran into a similar issue compiling the same code on Linux. Our code isn't relocatable but `-fPIC` is passed by default and you can't make it go away. I think in general the C++ toolchains are just doing too much automatically. At the very least every single flag that's auto added should correspond to a feature so it can be disabled (note that `features = ["-pic"]` does not disable the `-fPIC` flag).

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
