### ISSUE TITLE
Check for message truncation is always false

### ISSUE THREAD

**Issue by Flamefire** [bazelbuild/bazel#10382]
As GCC correctly warns the check at https://github.com/bazelbuild/bazel/blob/dbc504c8a033f06041ba42c219b983f475972583/third_party/grpc/src/core/lib/iomgr/tcp_posix.cc#L725 is always false:

(E.g.) for `MSG_CTRUNC = $0008` the bitwise and is either zero or 8 so comparing it against 1 yields false.

See 

> third_party/grpc/src/core/lib/iomgr/tcp_posix.cc:725:40: warning: bitwise comparison always evaluates to false [-Wtautological-compare]

**Comment by benjaminp** [comment]
This is not a Bazel bug, but one in the vendored copy of gRPC. (which is fixed upstream at grpc/grpc@619e6c8ef61d5740f81160c782d202f064971d25)

**Comment by Flamefire** [comment]
Sure, but it has been in Bazel for ages (0.29+). I'm unsure about the usage of that particular code but it could be critical...
