### ISSUE TITLE
http_archive with tar.gz files containing symlinks between files does not work on windows

### ISSUE THREAD

**Issue by speedskater** [bazelbuild/bazel#10399]
### Description of the problem / feature request:

When using the `http_archive` repository rule on windows pointing to a tar.gz file containing symbolic links between individual files, the build fails when referencing a file corresponding to such a symbolic link.

This results the build to fail with the following error:

> ...external/test/bar (No such file or directory)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Create a repro.tar.gz archive containing a file `prefix/foo` and a symlink `prefix/bar` pointing to foo
2. Host this file on a local http server using something like `python3 -m http.server 80`
3. Create a new bazel project
4. Place the following code into your `WORKSPACE` file:

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "repro",
    build_file_content = """filegroup(name = "bar-file", srcs = ["bar"], visibility = ["//visibility:public"]);filegroup(name = "foo-file", srcs = ["foo"], visibility = ["//visibility:public"])""",
    sha256 = "7c3f4d1f373d8d155d3accc6a127f42c77b4923a2c3c53e4b0125d4ad4dd67e1"
    strip_prefix = "repro",
    urls = ["http://localhost/repro.tar.gz"],
)
```

5. Execute a simple build:

> bazel build @repro//:all

6. You should get a similar output:

```
[repro.zip](https://github.com/bazelbuild/bazel/files/3946333/repro.zip)

ERROR: missing input file '@repro//:bar':<project-directory>/k52n5tiz/external/repro/bar (No such file or directory)
ERROR: <project-directory>/k52n5tiz/external/test/BUILD.bazel:1:1: @repro//:bar-file: missing input file 'LabelCause{label=@repro//:bar, msg=missing input file '@test//:bar':<project-directory>/k52n5tiz/external/repro/bar (No such file or directory)}'
ERROR: <project-directory>/k52n5tiz/external/repro/BUILD.bazel:1:1 1 input file(s) do not exist
```

### What operating system are you running Bazel on?

Windows 10.0.17763

### What's the output of `bazel info release`?

release 1.2.1

### Any other information, logs, or outputs that you want to share?

[repro.zip](https://github.com/bazelbuild/bazel/files/3946329/repro.zip)

**Comment by laszlocsomor** [comment]
Thanks for reporting this bug!
What is the expected behavior?
