### ISSUE TITLE
glob() documentation incorrectly says it returns the outputs of targets

### ISSUE THREAD

**Issue by jmillikin** [bazelbuild/bazel#10395]
### Description of the problem / feature request:

https://docs.bazel.build/versions/master/be/functions.html#glob says:

> If a rule and a source file with the same name both exist in the package, the glob will return the outputs of the rule instead of the source file.

This isn't correct in the current version of Bazel (nor any I can remember using). Given the following workspace:

```
$ touch WORKSPACE
$ touch hello.c
$ cat >BUILD <<'EOF'
genrule(
    name = "hello.c",
    outs = ["hello-gen.c"],
    cmd = "touch $@",
)

print("glob: ", glob(["*"]))
EOF
```

Running `bazel build` will print out `hello.c`, not `hello-gen.c`.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 1.2.1

**Comment by laurentlb** [comment]
This line is very suspicious indeed.

@laszlocsomor Can you take a look at this? You reviewed the changes a long time ago, in 2015 (Google changes cl/88322388 and cl/88325408). :)

**Comment by aehlig** [comment]
> https://docs.bazel.build/versions/master/be/functions.html#glob says:
> 
> > If a rule and a source file with the same name both exist in the package, the glob will return the outputs of the rule instead of the source file.

This is indeed slightly misleading, but saying the `glob` would return the source file would be misleading as well. The truth is, that
- the `glob` returns a label for the source file, and
- if a label is used that could refer to both, a source file and a rule, the rule will be used.

Let's extend your example a bit and use the following `BUILD` file (note the `echo` in the second `genrule`).
```
genrule(
    name = "hello.c",
    outs = ["hello-gen.c"],
    cmd = "touch $@",
)

genrule(
    name = "globuse",
    outs = ["globuse.txt"],
    srcs = glob(["*.c"]),
    cmd = "echo $(SRCS) > $@",
)
```
If we then build `//:globuse`, the generated file `globuse.txt` will (on my OS) contain
```
bazel-out/freebsd-fastbuild/bin/hello-gen.c
```
So, indeed the output was used.

**Comment by jmillikin** [comment]
That's not got anything to do with `glob()` though, it's just a target shadowing a source file. You can completely drop the `glob()` and still see the same behavior:

```python
genrule(
    name = "hello.c",
    outs = ["hello-gen.c"],
    cmd = "touch $@",
)
genrule(
    name = "globuse",
    outs = ["globuse.txt"],
    srcs = ["hello.c"],
    cmd = "echo $(SRCS) > $@",
)
```

**Comment by laszlocsomor** [comment]
@jmillikin : I think you and Klaus are talking about the same.
Put simply, the `glob` runs a `readdir(3)`, finds the file, and returns a path relative to the package. This path is used as a package-relative label. Then the rule with the same name shadows the file.

Does that sound good as the new documentation?

**Comment by jmillikin** [comment]
Yes, I think clarifying the docs to state that:
* `glob()` returns labels for each source file,
* The label for a source file might be shadowed by another target.
* In this case attributes that consume labels will see them resolve to the target.
