### ISSUE TITLE
Compiler options break use of cache

### ISSUE THREAD

**Issue by blackliner** [bazelbuild/bazel#10406]
### Description of the problem / feature request:

When no compile options (like `--cxxopt=-std=c++14` or `--copt='-Wall'`) are used (be it manually or in the .bazelrc file), a `bazel test ...` will only need the time to do the tests, if a `bazel build ...` was run previously. This is because the build cache (?) is used.
But as soon as those flags are used, everything has to be rebuilt whenever one switches from `test` to `build` and vice versa. Whats the reason for that? I understand the necessity of a "clean" rebuilt if you use different compile options for `build` and `test`, but it should use the cache if those options are exactly the same, right?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

see above

### What operating system are you running Bazel on?

Win10 WSL Ubuntu 18.04

### What's the output of `bazel info release`?

1.2.1

**Comment by blackliner** [comment]
@benjaminp already tried to jump in here at https://github.com/bazelbuild/bazel/issues/8371

**Comment by benjaminp** [comment]
Don't list compiler options for both "build" and "test" in your configuration files. The test command inherits all configured options from the build command.

**Comment by blackliner** [comment]
:man_facepalming: thank you, never thought of anything being implicit wit bazel. Thank you!
