### ISSUE TITLE
Sandboxing time breakdown in tracing profile needed

### ISSUE THREAD

**Issue by ob** [bazelbuild/bazel#10404]
As discussed at BazelCon, debugging the sandbox performance problem on macOS would be easier if there was an option to add to the trace profile a break down, per action, of the time it takes to set up the sandbox, the time it takes to execute the action’s command, and the time it takes to tear down the sandbox.

**Comment by ob** [comment]
@meisterT, I just got around to trying this... but I'm not sure what I should be seeing. I ran bazel as 

```
bazel build --genrule_strategy=sandboxed --spawn_strategy=sandboxed --config Debug --experimental_generate_json_trace_profile --experimental_profile_cpu_usage --profile trace-profile.json //:App
```

And got this: 
<img width="333" alt="Screen Shot 2019-12-17 at 9 57 21 AM" src="https://user-images.githubusercontent.com/4950/71021666-b53b0400-20b3-11ea-8c94-8bf475497642.png">

I was expecting something more like this:
<img width="333" alt="Screen Shot 2019-12-17 at 9 57 21 AM" src="https://user-images.githubusercontent.com/4950/71021871-1367e700-20b4-11ea-93c6-4c5a2b66161f.png">

**Comment by meisterT** [comment]
It's there, it's just super small :-)

See my screenshots:
![xea2ruxP3vA](https://user-images.githubusercontent.com/418721/71022755-1532aa00-20b6-11ea-8a57-4589674503d4.png)

Same action, zoomed in:
![ajBOOnULB0v](https://user-images.githubusercontent.com/418721/71022766-195ec780-20b6-11ea-9db1-9b787f78c2be.png)

So the super thin blue bars are the sandboxing setup.

**Comment by meisterT** [comment]
I just realized that this just the Java object creation. I'll create a follow-up commit...
