### ISSUE TITLE
test-wrapper.sh should not add "." to PATH

### ISSUE THREAD

**Issue by jmillikin** [bazelbuild/bazel#10415]
### Description of the problem / feature request:

`test-wrapper.sh` modifies the action environment's `$PATH` variable to include `.:` as a prefix, which causes path-based command resolution to search the current working directory. This is undesirable -- processes that `chdir()` as part of their normal workflow can exhibit extremely surprising behavior when their `execvp()` calls now silently depend on the process's working dir.

In addition, since `PATH=".:${PATH}"` is widely considered an insecure configuration (cf. https://unix.stackexchange.com/questions/65700/is-it-safe-to-add-to-my-path-how-come), some tools detect it and refuse to run. Here's an example error message from `find -execdir`, which is (1) useful for debugging a failing test, and (2) won't run under the current configuration:

```
find: The current directory is included in the PATH environment variable, which is insecure in combination with the -execdir action of find.  Please remove the current directory from your $PATH (that is, remove ".", doubled colons, or leading or trailing colons)
```

Finally, Bazel's own documentation on the test environment (https://docs.bazel.build/versions/master/test-encyclopedia.html) documents `.` as being added to the _end_ of `$PATH`, but `test-wrapper.sh` inserts it at the beginning. This causes problems when the execroot contains top-level files sharing the same name as common utilities, since it allows the execroot to shadow everything in `/bin`, `/usr/bin`, and so on.

### What operating system are you running Bazel on?

macOS and Linux

### What's the output of `bazel info release`?

`release 1.2.1`

### Any other information, logs, or outputs that you want to share?

It looks like this behavior was added 5 years ago in https://github.com/bazelbuild/bazel/commit/fc64f5ee22e41e1f851b35f0a6bb2fd5a2e6af86, to enable `bazel test --run_under`.

Given the very long time this has been true and the unpredictable downstream effects of removing `.` from `$PATH`, I believe it would be considered a backward-incompatible change. It would be nice if the 1.x series could get a flag to turn it off, but that may be a bit challenging given its location in the wrapper script.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
