### ISSUE TITLE
ERROR: missing input file '@local_jdk//:bin/staprun':/tmp/bazel_lBI2reYV/out/external/local_jdk/bin/staprun (Permission denied)

### ISSUE THREAD

**Issue by adamjstewart** [bazelbuild/bazel#10418]
### Description of the problem / feature request:

I'm trying to build Bazel 0.26.1 on Amazon Linux 2 with GCC 7.3.1 and OpenJDK 1.8.0_222-b10, but it crashes during compilation with the following error message:
```
ERROR: missing input file '@local_jdk//:bin/staprun':/tmp/bazel_lBI2reYV/out/external/local_jdk/bin/staprun (Permission denied)
[920 / 1,221] checking cached actions

ERROR: /tmp/ec2-user/spack-stage/spack-stage-bazel-0.26.1-xqzcdeh3xlxrhvxgbjzmzsuspamoixys/spack-src/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/BUILD:186:1: //src/java_tools/buildjar/java/com/google/devtools/build/buildjar:bootstrap_VanillaJavaBuilder: missing input file '@local_jdk//:bin/staprun'
[920 / 1,221] checking cached actions

Target //src:bazel_nojdk failed to build
[920 / 1,221] checking cached actions

ERROR: /tmp/ec2-user/spack-stage/spack-stage-bazel-0.26.1-xqzcdeh3xlxrhvxgbjzmzsuspamoixys/spack-src/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/BUILD:186:1 1 input file(s) do not exist
[920 / 1,221] checking cached actions

INFO: Elapsed time: 235.616s, Critical Path: 22.12s
[920 / 1,221] checking cached actions

INFO: 904 processes: 904 local.
[920 / 1,221] checking cached actions

FAILED: Build did NOT complete successfully

FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel
````

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I use the following commands to build Bazel:
```console
$ export EXTRA_BAZEL_ARGS='--color=no --host_javabase=@local_jdk//:jdk'
$ bash ./compile.sh
```

### What operating system are you running Bazel on?

Amazon Linux 2 (AWS EC2)

### Any other information, logs, or outputs that you want to share?

I'm using the [Spack](https://spack.io) package manager to install Bazel.

- [.bazelrc](https://github.com/bazelbuild/bazel/files/3965594/bazelrc.txt)
- [Build log](https://github.com/bazelbuild/bazel/files/3965595/spack-build-out.txt)
- [Build environment](https://github.com/bazelbuild/bazel/files/3965596/spack-build-env.txt)

**Comment by comius** [comment]
Closing because I don't see any references to staprun in current version of bazel.
