### ISSUE TITLE
Add attr.struct_list()

### ISSUE THREAD

**Issue by cvrebert** [bazelbuild/bazel#10414]
### Description of the problem / feature request:

The [`attr`](https://docs.bazel.build/versions/master/skylark/lib/attr.html) module should have a `struct_list()` function to allow the definition of attributes whose values are lists of [`struct()`s](https://docs.bazel.build/versions/master/skylark/lib/struct.html).

### Feature requests: what underlying problem are you trying to solve with this feature?

I have Starlark macros/rules which take structured information as inputs. Due to lack of this feature, if I want to keep the information bundled together in my rule implementation, I'm forced to apply ugly hacks like encoding the `struct()` as a string. Even worse, I can't easily use JSON for this encoding due to https://github.com/bazelbuild/bazel/issues/3732 , so I'm forced to either reimplement JSON parsing myself, or implement a custom encoding scheme myself.

###  Have you found anything relevant by searching the web?

Nope.

- StackOverflow: No results.
- GitHub issues: No relevant results.
- bazel-discuss: No relevant results.

### Any other information, logs, or outputs that you want to share?

Happy to point you to concrete, Google-internal use-cases for this.

**Comment by laurentlb** [comment]
Allowing arbitrary values (inside the struct fields) might be problematic for Bazel, especially if they may contain labels.

It's hard to suggest alternatives without at the details, but you can sometimes use a list of labels. Each target in the list uses a rule that can wrap the information you need.

**Comment by Bocete** [comment]
If all contents of the struct attribute are ignored apart from piping the struct through (i.e. this is not a dependency attribute no matter what's inside it), is it still problematic?

**Comment by brandjon** [comment]
Please see [this explanation](https://github.com/bazelbuild/bazel/blob/3d78dc7e3a927612c23a6d1542bc38aad5a9703e/src/main/java/com/google/devtools/build/lib/packages/Type.java#L58-L80) of why we are loathe to extend the set of allowed attribute types.
