### ISSUE TITLE
Re-enable mandatory keyword-only parameters in Java Starlark

### ISSUE THREAD

**Issue by jmillikin** [bazelbuild/bazel#10416]
### Description of the problem / feature request:

Bazel's implementation of Starlark historically supported both mandatory and optional keyword-only parameters. This feature was disabled to maintain syntax compatibility with Python 2. Since then, the requirement to be compatible with Python 2 was dropped (see https://github.com/bazelbuild/starlark/issues/27 and https://github.com/bazelbuild/starlark/issues/23). It looks like at some point support for _optional_ parameters was re-enabled, but _mandatory_ parameters are still forbidden.

Based on @laurentlb's comment https://github.com/bazelbuild/starlark/issues/23#issuecomment-464007211 it sounds like there's no blockers to re-enabling this functionality.

### Feature requests: what underlying problem are you trying to solve with this feature?

It should be possible to declare the following function from Starlark:

```python
def hello(*, name):
  print("Hello,", name)
```

### What's the output of `bazel info release`?

release 1.2.1

**Comment by laurentlb** [comment]
Thanks for filing the issue.

I've re-enabled the feature. It should be part of Bazel 2.1.
