### ISSUE TITLE
bazelrc `try-import` shouldn't mask later `import` failures

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel#10419]
### Description of the problem / feature request:

The bazelrc statement `try-import` is documented as silently skipping imported files that don't exist or can't be read. Its actual behavior seems to be much broader -- it silently swallows errors if any transitively imported bazelrc fragment under its toplevel doesn't exist.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Construct a workspace with this bazelrc layout:
```
$ echo 'try-import %workspace%/bazelrc-ok' > .bazelrc
$ echo 'import noexist' > bazelrc-ok
```

I would expect this to fail -- the `try-import` should successfully locate and load `bazelrc-ok`, then the `import` should fail to locate `noexist` and thus fail. The failure should propagate up despite `try-import`.

What actually happens is the build proceeds like normal, with no indication that a config fragment requested by `import` was not found.

Additionally, the failure happens after previous content of `bazelrc-ok` is applied but stops further processing. This is extremely confusing, for example the following will cause the build to run with _only_ the first two lines of configuration applied:

```
$ cat bazelrc-ok
build --announce_rc
build --bes_keywords=reported-keyword
import noexist
build --bes_keywords=not-reported
```

### What operating system are you running Bazel on?

macOS and Linux

### What's the output of `bazel info release`?

release 1.2.1

**Comment by philwo** [comment]
I can still reproduce this.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
