### ISSUE TITLE
there probably needs to be separate c and c++ linkstamp action names

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#10411]
The cc rules use one linkstamp crosstool action name for all linkstamp compilation. This means it's not possible for the crosstool to apply different flags depending on whether the linkstamp is C or C++. For example, with the autoconfigured toolchain, `-std=c++something'`is likely to be passed to the compiler, which leads to warnings for '.c' files.

On the other hand, command line `--cxxopt` and `--conlyopt` are correctly applied based on the linkstamp source file type.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
