### ISSUE TITLE
Running android test rule fails with an error in protobuf

### ISSUE THREAD

**Issue by xykivo** [bazelbuild/bazel#10417]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Running
$bazel test //path/to/my/android/test:test_rule

Fails with the following error:
Error:(130, 19) Traceback (most recent call last):
	File "/home/ds/.cache/bazel/_bazel_ds/cb9917283032be91e0a297f397dce028/external/com_google_protobuf/protobuf.bzl", line 125
		rule(<3 more arguments>)
	File "/home/ds/.cache/bazel/_bazel_ds/cb9917283032be91e0a297f397dce028/external/com_google_protobuf/protobuf.bzl", line 130, in rule
		attr.label(cfg = "host", <3 more arguments>)
'single_file' is no longer supported. use allow_single_file instead. You can use --incompatible_disable_deprecated_attr_params=false to temporarily disable this check.

Note I followed the sample code in
https://docs.bazel.build/versions/master/android-instrumentation-test.html

### Feature requests: what underlying problem are you trying to solve with this feature?

Run android instrumentation tests using bazel from command line and from Android Studio.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try to run an Android instrumented test using bazel from command line, and from AndroidStudio

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

release 1.2.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.
NA

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
NA

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Full error message is:

/home/ds/.cache/bazel/_bazel_ds/cb9917283032be91e0a297f397dce028/external/com_google_protobuf/protobuf.bzl
Error:(130, 19) Traceback (most recent call last):
	File "/home/ds/.cache/bazel/_bazel_ds/cb9917283032be91e0a297f397dce028/external/com_google_protobuf/protobuf.bzl", line 125
		rule(<3 more arguments>)
	File "/home/ds/.cache/bazel/_bazel_ds/cb9917283032be91e0a297f397dce028/external/com_google_protobuf/protobuf.bzl", line 130, in rule
		attr.label(cfg = "host", <3 more arguments>)
'single_file' is no longer supported. use allow_single_file instead. You can use --incompatible_disable_deprecated_attr_params=false to temporarily disable this check.
ERROR
Error:/home/ds/.cache/bazel/_bazel_ds/cb9917283032be91e0a297f397dce028/external/android_test_support/tools/android/emulator/BUILD.bazel:30:1: error loading package '@com_google_protobuf//': Extension file 'protobuf.bzl' has errors and referenced by '@android_test_support//tools/android/emulator:emulator_meta_data_pb_py_pb2'
Error:/home/ds/.cache/bazel/_bazel_ds/cb9917283032be91e0a297f397dce028/external/android_test_support/tools/android/emulator/BUILD.bazel:121:1: error loading package '@com_google_protobuf//': Extension file 'protobuf.bzl' has errors and referenced by '@android_test_support//tools/android/emulator:unified_launcher_head'
Error:command succeeded, but there were loading phase errors

**Comment by DannyLuoDan** [comment]
hi, @iirina  have you fixed this problem? if yes, could you please kindly tell me how to fix it? thank you.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
