### ISSUE TITLE
Provide way to only pass some crosstool flags based on tools versions

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#10413]
From a discussion at BazelCon 2019. In the macOS world tools' supported flags are tied to Xcode versions, sometimes a tool adds a useful flag like this `libtool` flag that was added in Xcode 11:

```
-D     When  building  a  static  library, set archive contents' user ids, group ids, dates, and file modes to reasonable defaults. This
       allows libraries created with identical input to be identical to each other, regardless of time of day, user, group,  umask,  and
       other aspects of the environment.
```

But we can't add this to the crosstool since we support older Xcode versions. It would be nice if we could differentiate tools versions to be able to add this.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
