### ISSUE TITLE
Invoking Testng

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#10420]
# Description of the problem / feature request:

It is currently unclear how to tell TestNG how to test a (java) library.

Most straight forward approach would be:

```
java_test(
    name = "my-test",
    args = [
        "-testjar",
        "$(location :test_lib)", # Same problem with $(execpath :test_lib)
    ],
    main_class = "org.testng.TestNG",
    use_testrunner = False,
    runtime_deps = [
        ":test_lib",
```

This does not work an gives the error:
`label '//foo:test_lib' in $(location) expression is not a declared prerequisite of this rule`.

How should one reference the runtime dependency instead?

### What operating system are you running Bazel on?

Ubuntu 18.04.

### What's the output of `bazel info release`?

```
release 1.2.1
```

**Comment by navkast** [comment]
You can add `data = [":test_lib"]`:

```
java_test(
    name = "my-test",
    data = [":test_lib"]
    args = [
        "-testjar",
        "$(location :test_lib)", # Same problem with $(execpath :test_lib)
    ],
    main_class = "org.testng.TestNG",
    use_testrunner = False,
    runtime_deps = [
        ":test_lib",
```

See https://bazel.build/reference/be/common-definitions#typical.data

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by sgowroji** [comment]
Hi @ken4ward, Can you raise a new issue with complete details in it or if you are looking for support, You can also post the query in our slack channel. Thanks!

**Comment by ken4ward** [comment]
@sgowroji ,  please kindly share the slack channel. I'll also post it as a new issue.

**Comment by sgowroji** [comment]
[ slack ](https://bazelbuild.slack.com/join/shared_invite/zt-21u39l881-FClDvGq6FQSFldL~YW4IWw#/shared-invite/email)
