### ISSUE TITLE
JavaInfo.transitive_exports should return jars, not labels

### ISSUE THREAD

**Issue by steeve** [bazelbuild/bazel#10422]
### Description of the problem / feature request:

`JavaInfo.transitive_exports` returns a list of labels, not jars, as opposed to other attributes which return jars.

### Feature requests: what underlying problem are you trying to solve with this feature?

Trying to consume the transitive exports jars of a `JavaInfo` target to create one big jar with `singlejar`.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

`release 1.2.1`

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
