### ISSUE TITLE
Does bazel support kerberos authentication over a proxy

### ISSUE THREAD

**Issue by deryck1031** [bazelbuild/bazel#10424]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> bazel failed to download external deps behind a proxy that supports kerberos authentication. 

### Feature requests: what underlying problem are you trying to solve with this feature?

> How to configure bazel to use kerberos.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> N/A

### What operating system are you running Bazel on?

> RH6

### What's the output of `bazel info release`?

> 0.29.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

>N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

>N/A

###  Have you found anything relevant by searching the web?

>N/As

### Any other information, logs, or outputs that you want to share?

>

**Comment by philwo** [comment]
No, I'm sorry - we don't support Kerberos authentication.
