### ISSUE TITLE
Add JSON output format to aquery

### ISSUE THREAD

**Issue by devnev** [bazelbuild/bazel#10421]
### Description of the problem / feature request:

Add --output=json to `bazel aquery`

### Feature requests: what underlying problem are you trying to solve with this feature?

I recently encountered the need to use aquery to find all the outputs being generated by a particular set of rules. The results needed post-processing to extract the exec_path. We ended up using a bunch of grep/sed. Having a more common text format like JSON would have allowed us to avoid regex-based processing of structured data.

### What operating system are you running Bazel on?

MacOS Mojave 10.14

### What's the output of `bazel info release`?

release 0.26.1

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

No

**Comment by meisterT** [comment]
Why aren't you parsing the proto message (instead of using grep/sed)?

If that isn't an option for you, perhaps you can just use proto2json step in between, e.g. using https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/util/JsonFormat.html?

**Comment by devnev** [comment]
@meisterT 

> Why aren't you parsing the proto message (instead of using grep/sed)?

Avoiding grep/sed is exactly what I'd like to do, hence why I'm asking for JSON output. jq or similar would support doing what I want in a much cleaner fashion if I had JSON.

> If that isn't an option for you, perhaps you can just use proto2json step in between, e.g. using https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/util/JsonFormat.html?

As JSON is a first-class format for proto3, I was hoping that the format could also become a first-class format for aquery instead of needing an extra step to be supported. This would also make it easy to integrate aquery with the large ecosystem of JSON-based tooling that already exists without having to add extra proto-to-json conversion steps into existing tools.

**Comment by meisterT** [comment]
Do you perhaps want to send us a PR?

also cc @joeleba

**Comment by devnev** [comment]
If the FR sounds reasonable, I can give it a try. Do you have any pointers on where to start? I'm not familiar with the codebase.

**Comment by meisterT** [comment]
Check how we do text proto format in https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/query2/aquery/ActionGraphProtoOutputFormatterCallback.java

**Comment by devnev** [comment]
@meisterT PTAL @ #10426
