### ISSUE TITLE
Make BazelTestRunner thread dump timeout configurable

### ISSUE THREAD

**Issue by dremeika** [bazelbuild/bazel#10431]
### Description of the problem / feature request:

BazelTestRunner currently dumps threads if JVM didn't exit in 5 seconds (hardcoded): https://github.com/bazelbuild/bazel/blob/master/src/java_tools/junitrunner/java/com/google/testing/junit/runner/BazelTestRunner.java#L178

Could this 5 sec timeout be configurable to allow for longer shutdown time if that is expected for the tests?

### Feature requests: what underlying problem are you trying to solve with this feature?

Some of our tests execute cleanup/shutdown on JVM shutdown hook and usually takes longer than 5 seconds. Changing timeout to different value (10 seconds in our case) would not pollute output with thread dumps.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
