### ISSUE TITLE
Un-expandable config should produce a warning instead of an error when not reading all RC files

### ISSUE THREAD

**Issue by DavidANeil** [bazelbuild/bazel#10435]
### Description of the feature request:

Bazel (rightfully, in my opinion) produces an `OptionsParsingException` when a config is encountered that has no found expansions in any RC files, and is therefore unable to expand the config.
When running with options such as `--nohome_rc`, `--ignore_all_rc_files`, or `--bazelrc`  this error becomes very likely to occur, and also becomes increasingly difficult to workaround.

Proposal: If any of the flags that affect RC file reading are used to disable an RC file then this error should be downgraded to a warning, or silenced entirely.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
