### ISSUE TITLE
instantiation of non-exported repository_rules is not an error

### ISSUE THREAD

**Issue by alandonovan** [bazelbuild/bazel#10441]
repository_rules, like package rules, should not be instantiated until they have been "exported". 

"Exported" means assigned a globally unique name consisting of the pair (label, name) where _label_ is the build label `@repo//dir:file.bzl` of the defining file, and _name_ is the name of the global variable in that file that refers to the repository_rule. (The moment of export is supposed to be at the end of execution of the .bzl file, but in fact is immediately after a top-level assignment statement such as `r = rule(...)`; but that's a story for another GitHub issue.)

Unfortunately, the check that exists for package rules was not implemented for repository_rules, and a small number of Bazel projects have come to create a new class of repository_rule and then immediately  instantiate it, without an intervening "export", as in this example:

```
def _foo_impl(ctx): ... 

def f():
    r = repository_rule(implementation = _foo_impl)
    r(name="myrepo", ...)
```

The correct Bazel behavior for this program should be an error: line 5: cannot instantiate non-exported repository_rule declared on line 4. Instead, today, it instantiates a rule, and gives it the name "myrepo" and the rule class name "r". Bazel infers the rule class name using a hack: it looks at the syntax tree of the r(...) call expression and extracts the name "r".  (This heuristic would fail on a more complex call expression such as `[r][0](name="myrepo", ...)`.)

The resulting name is observable both in the user interface, and to Starlark programs, for example through the result of `native.existing_rules()` when called in a WORKSPACE thread.

This hack is an obstacle to a Starlark compiler, as we cannot have built-in functions looking through the syntax tree during execution. We need to change the heuristic to something else (e.g. to use a name such as "unexported-_foo_impl" instead of "r". This would be a potentially breaking change.

The correct user program is:

```
def _foo_impl(ctx): ... 
r = repository_rule(implementation = _foo_impl) # rule exported as class "r"

def f():
    r(name="myrepo", ...)
```

See also:
- Google internal issue b/111199163
- an attempted and reverted fix: https://bazel-review.googlesource.com/c/bazel/+/64591/

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
