### ISSUE TITLE
Feature request: for Bazel to integrate gcs:// and s3:// transports

### ISSUE THREAD

**Issue by nkoroste** [bazelbuild/bazel#10442]
Related issues:
https://github.com/bazelbuild/rules_jvm_external/issues/256
https://github.com/coursier/coursier/issues/1399

It would be nice to have the ability to use a maven repo from an internal GCS bucket. 

Currently https://github.com/bazelbuild/bazel/blob/d2a5b330fe3fe1a7f913a3ce2cf2969a872f7d75/src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/HttpDownloader.java
Doesn't support gcs://

**Comment by gmendonca** [comment]
Maybe we could make this broader and also support `s3://`

Related:
https://github.com/coursier/coursier/issues/1488
https://github.com/bazelbuild/rules_scala/issues/911

**Comment by jin** [comment]
Modified the FR to include `s3://`.

**Comment by uri-canva** [comment]
Would the new remote downloader feature help here in the meantime? For example if urls in `repo_ctx.download` were passed to the remote downloader without being checked for support, it would be possible for the remote downloader to support the transports, even if the downloader built into bazel didn't (it's possible that's already the case, I haven't checked).
