### ISSUE TITLE
Bazel expunge will remove all downloaded artifacts.

### ISSUE THREAD

**Issue by systemlogic** [bazelbuild/bazel#10456]
### Description of the problem / feature request:

Bazel expunge should not clean externally downloaded artifacts. For example jar, pypi package and other language specific libraries, perhaps a switch need to be provided to claim it from local bazel artifactory. To work with bazel one has to be on internet all the time.

### Feature requests: what underlying problem are you trying to solve with this feature?

Expunge should cleans compiled targets, not external libraries, including github repository specified in WORKSPACE file. This can be done via some proxy server on users development machine.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

bazel clean --expunge --compiled-target

### What operating system are you running Bazel on?

Any OS

### What's the output of `bazel info release`?

0.29.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

release 0.29.1

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

IBM private repository URL and two commits

###  Have you found anything relevant by searching the web?
 No,

**Comment by meisterT** [comment]
Bazel caches externally downloaded artifacts via the repository cache, e.g. `.cache/bazel/_bazel_user/cache/repos/v1/content_addressable/sha256/` outside of the current `WORKSPACE`.

**Comment by jin** [comment]
`bazel clean` does not clean external repositories and does not shut down the Bazel server.

`bazel clean --expunge` cleans *everything*, and shuts the server down. If your external repositories in the WORKSPACE have their sha256 specified, these are also cached in the location @meisterT mentioned.
