### ISSUE TITLE
Instructions unclear, docker got cloudbees exception

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1045]
I'm trying to follow the instructions at https://bazel.git.corp.google.com/continuous-integration/+/master/README.md for setting up local testing.

I've eventually arrived at the command line:

```
$ docker run --name=jenkins-master -p 8080:8080 -p 50000:50000 -d gcr.io/bazel-public/jenkins-master
```

which produced the attached log.  

[docker.txt](https://github.com/bazelbuild/bazel/files/174551/docker.txt)

**Comment by kchodorow** [comment]
Oh, just as a note: I've change JENKINS_HOST in jenkins/jenkins.bzl to localhost and have https://bazel-review.googlesource.com/#/c/3072/ applied locally.

**Comment by damienmg** [comment]
Well we should add an easy way to test everything, being able to launch a build and so on...

**Comment by kchodorow** [comment]
That would be great!

**Comment by damienmg** [comment]
Closing this one, use bazelbuild/continuous-integration#1 to follow-up
