### ISSUE TITLE
Bazel Pantry: Catalog for Skylark rule sets

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel#1046]
Now that we have moved all the Skylark rule sets out of the main repository into separate repositories, it would be great to have a searchable catalog/index of Skylark rule sets, similar in flavor to [NPM](https://www.npmjs.com/), [Bower](http://bower.io/search/), [Atom](https://atom.io/packages), [Crates.io](https://crates.io/), [Maven Central](http://search.maven.org/), etc.

Each page would have the name and description of the rule set, links to the rule set's documentation/website and repo, and a snippet containing the rules that one would need to add to the `WORKSPACE` file to use the rule set.

On a related note, it is great to see how many rule sets and languages we have so far. :) I'm sure there are many other repos elsewhere on GitHub, and having such a catalog of Skylark rules would be extremely helpful for discoverability.
- [bazelbuild/rules_appengine](https://github.com/bazelbuild/rules_appengine)
- [bazelbuild/rules_closure](https://github.com/bazelbuild/rules_closure)
- [bazelbuild/rules_d](https://github.com/bazelbuild/rules_d)
- [bazelbuild/rules_dotnet](https://github.com/bazelbuild/rules_dotnet)
- [bazelbuild/rules_go](https://github.com/bazelbuild/rules_go)
- [bazelbuild/rules_groovy](https://github.com/bazelbuild/rules_groovy)
- [bazelbuild/rules_jsonnet](https://github.com/bazelbuild/rules_jsonnet)
- [bazelbuild/rules_rust](https://github.com/bazelbuild/rules_rust)
- [bazelbuild/rules_sass](https://github.com/bazelbuild/rules_sass)
- [bazelbuild/rules_scala](https://github.com/bazelbuild/rules_scala)

**Comment by steren** [comment]
I can see 2 distinct components:

1. Something that helps sharing and re-using Bazel config for OSS libraries.
2. Something that is an index of first and 3rd party skylark rules.

It is not clear at all to me that these two components should be solved by the same solution.

For 1., we started to [discuss this on the mailing list](https://groups.google.com/forum/#!searchin/bazel-discuss/repository$20OSS%7Csort:relevance/bazel-discuss/yisAi4YUQjc/z4GvaJZnAAAJ)

For 2., we have to clarify how this relates to the Build Encyclopedia. As in my opinion, listing Bazel rules is exactly what the Encyclopedia should do. We have https://github.com/bazelbuild/bazel/issues/3255 to track this.

**Comment by laurentlb** [comment]
We list some rules here: https://docs.bazel.build/versions/master/be/overview.html

I also shared a doc about it: http://doc/1oYQ-cqmqrpVE02rphobn4F_Q-lqvch4IiUlqEy9q2Fs
