### ISSUE TITLE
Bazel build of an Android library that depends on a CC library fails

### ISSUE THREAD

**Issue by xykivo** [bazelbuild/bazel#10461]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

When adding a cc_library as a dependency of an android kotlin/java library the build fails with the message that the native library is missing a mandatory provider JavaInfo.

/path/to/build/BUILD:24:1: in deps attribute of kt_jvm_library rule //path/to/kotlin/android/library: '//path/to/cc/library' does not have mandatory providers: 'JavaInfo'. 

### Feature requests: what underlying problem are you trying to solve with this feature?

A dependency on a native library should not require java info 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create an android project that uses a kt_android_library that depends on a cc_library

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

release 1.2.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

NA

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

NA

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

NA

**Comment by ahumesky** [comment]
Depending on a cc_library from an android_library should work, so maybe one workaround is to put an android_library between the cc_library and the kt_android_library. Other than that, this is more likely an issue for https://github.com/bazelbuild/rules_kotlin
