### ISSUE TITLE
Java targets depend on local jdk incorrectly

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#10468]
On a system with no local JDK installed, Bazel should use the remote JDK downloaded as `@remotejdk11_linux//` (or windows, mac, etc) instead of trying to use `@local_jdk`. However, several local_jdk targets are still dependencies as shown by cquery:

```
@local_jdk//:jdk (419a3f9c03a725a237290b10359c9923007948fc3772740ed08cd228e37927c7)
@local_jdk//:jdk-bin (419a3f9c03a725a237290b10359c9923007948fc3772740ed08cd228e37927c7)
@local_jdk//:jdk-include (419a3f9c03a725a237290b10359c9923007948fc3772740ed08cd228e37927c7)
@local_jdk//:jdk-lib (419a3f9c03a725a237290b10359c9923007948fc3772740ed08cd228e37927c7)
@local_jdk//:jre-bin (419a3f9c03a725a237290b10359c9923007948fc3772740ed08cd228e37927c7)
@local_jdk//:jre-default (419a3f9c03a725a237290b10359c9923007948fc3772740ed08cd228e37927c7)
@local_jdk//:jre-lib (419a3f9c03a725a237290b10359c9923007948fc3772740ed08cd228e37927c7)
@local_jdk//:windows (419a3f9c03a725a237290b10359c9923007948fc3772740ed08cd228e37927c7)
```

Is there a flag with the wrong default value?

(Forked from #6341, which is now about creating a gencquery rule, but the core problem would still exist even when using cquery).

**Comment by jin** [comment]
+1, this will be really nice to have.

**Comment by AustinSchuh** [comment]
The problem is that the alias in @bazel_tools//tools/jdk:java, etc directly point to local_jdk.  There is now way to fix that.

I've been patching bazel and overriding those with remote JDKs.

**Comment by lberki** [comment]
@comius , mind taking a look? (this was incorrectly classified as "team-Rules-Server")

**Comment by comius** [comment]
> On a system with no local JDK installed, Bazel should use the remote JDK downloaded as @remotejdk11_linux// (or windows, mac, etc) instead of trying to use @local_jdk. 

If no local JDK is found, Bazel will still point to @local_jdk and won't automatically switch to any of remote JDKs. The main reason for this is to keep the build systems stable upon Bazel releases. If we automatically select any of remote JDKs, we will eventually come to a Bazel release that will select a different remote JDK. The selection needs to be done by the user.
This is discussed in issue #6105.

If no local JDK is found Bazel will in create a fake rule `@local_jdk//:jdk` that fails when built. The rule displays a message with instructions how to setup a remote_jdk on the command line. Message is 
```Auto-Configuration Error: Cannot find Java binary bin/java in %s; either correct your JAVA_HOME, PATH or specify embedded Java (e.g. --javabase=@bazel_tools//tools/jdk:remote_jdk11)```
That was done in #6993. This way also the builds that don't depend on Java continue working. 

When there is no local JDK and user sets remote JDK, there is no dependency on @local_jdk. Example:
```shell
$ bazel cquery --javabase=@remotejdk11_linux//:jdk 'somepath(//src:bazel,@local_jdk//:jdk)'
INFO: Analyzed 2 targets (0 packages loaded, 9008 targets configured).
INFO: Found 2 targets...
INFO: Empty query results
INFO: Elapsed time: 1.520s
```

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by AustinSchuh** [comment]
I did some initial poking and this might actually just be fixed based on the java toolchain work.  The world has changed enough it is a bit hard to confirm (and I don't have access to the target which initially triggered the report).
