### ISSUE TITLE
how to compile tensorflow with a shared library?

### ISSUE THREAD

**Issue by wangshuaizs** [bazelbuild/bazel#10474]
I am trying to compile tensorflow with a shared library. That is, tensorflow depends on the shared library. But I cannot compile tensorflow successfully with the following command
```
bazel build --linkopt="-rdynamic" --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --config=opt --config=verbs --config=gdr --config=nonccl --config=noaws --config=nohdfs --config=noignite  --config=nokafka //tensorflow/tools/pip_package:build_pip_package
```

The error is as following:
```
tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZTIN8bayesopt15ContinuousModelE
```
I think the shared library's path should be passed into the command, but it shows that 
```
gcc: error: unrecognized command line option '-rdynamic /usr/local/lib/libbayesopt.so /usr/local/lib/libnlopt.so'
```
Anybody knows how to compile?

Thanks.

**Comment by jin** [comment]
For TensorFlow issues, please open a new issue on the [TensorFlow repository](https://github.com/tensorflow/tensorflow).
