### ISSUE TITLE
bazel usage error

### ISSUE THREAD

**Issue by wolfgangmeyers** [bazelbuild/bazel#1047]
If you try to run bazel with --javacopt "-target 1.7" and don't also specify --javacopt "-source 1.7" you get this error:

blaze javac: source release 8 requires target release 1.8
Usage: blaze javac <options> <source files>

Seems like the error should explain what to fix at a higher level, and have bazel instead of blaze.

**Comment by davidstanke** [comment]
Update: the error no longer says "blaze."

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
