### ISSUE TITLE
Android JNI example is  out of date and not working on Android 10

### ISSUE THREAD

**Issue by xykivo** [bazelbuild/bazel#10478]
### Description of the problem / feature request:

The Android example at https://github.com/bazelbuild/bazel/tree/master/examples/android is out of date and not working on Android 10 (emulator).
I also tried to create my own code based on the example, and when debugging through visual studio I always get an UnsatisfiedLinkError - the JNI functions are missing from  libhello_world.so
 E.g. this is the nm output of for libhello_world.so

00000470 t atexit
00000450 t __atexit_handler_wrapper
00002004 A __bss_start
                 U __cxa_atexit
                 U __cxa_finalize
00002000 d __dso_handle
00001eec d _DYNAMIC
00002004 A _edata
00000430 t __emutls_unregister_key
00002004 A _end
0000052c r __FRAME_END__
00001fe4 d _GLOBAL_OFFSET_TABLE_
0000018c r ndk_build_number
0000014c r ndk_version
00000134 r note_android_ident
00000148 r note_data
000001cc r note_end
00000140 r note_name
00000400 t __on_dlclose
00000440 t __on_dlclose_late
000004a0 t pthread_atfork
                  U __register_atfork
                  U __stack_chk_fail
000004d0 t __stack_chk_fail_local

For some reason the dependency of the android binary/library on the cc library does not link the cc_library exported functions into the generated ndk shared library for hello_world

### Feature requests: what underlying problem are you trying to solve with this feature?

1. Update the sample for Android 10
2. Fix the issue that is causing the UnsatisfiedLinkError. As far as I can tell right now, the issue is that the generated libhello_world.so that is installed on Android is not linked with the cc_library.
3. (Nice to have). Update the sample to use Kotlin

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run the Android sample https://github.com/bazelbuild/bazel/tree/master/examples/android on an Andoird 10 emulator.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

release 1.2.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

NA

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

NA

###  Have you found anything relevant by searching the web?

All relevant web searches are from 3+ years ago.

### Any other information, logs, or outputs that you want to share?

NA

**Comment by tdounnyy** [comment]
Reporting same issue here

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
