### ISSUE TITLE
java_library will not output src.jar file

### ISSUE THREAD

**Issue by amit-traiana** [bazelbuild/bazel#10489]
### Description of the problem / feature request:
According to the official `java_library` [documentation](https://docs.bazel.build/versions/1.2.0/be/java.html#java_library), `java_library` should output both `libname.jar` and `libname-src.jar`, but for some reason `libname-src.jar` is not being created. I remember it used to create a src.jar, so I'm assuming something happened along the way somewhere between 0.9 and 1.0. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Here's a very basic Build file:

```
java_library(
        name="test",
        srcs=["HelloWorld.java"]
)
```

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 1.2.1

**Comment by comius** [comment]
It is built when requested explicitly: `bazel build //:libtest-src.jar`
