### ISSUE TITLE
proto_lang_toolchain and blacklisted_protos with ProtoInfo not propagated correctly

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#10484]
### Description of the problem / feature request:

With protobuf's `proto_lang_toolchain`, after this change https://github.com/protocolbuffers/protobuf/commit/7b28278c7d4f4175e70aef2f89d304696eb85ae3 it seems the `blacklisted_protos` are no longer working correctly and removing that field has no effect on the build.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See https://github.com/protocolbuffers/protobuf/issues/7046 for a repro case

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 1.2.0 (I also tried with 2.0.0 with no change)

### Have you found anything relevant by searching the web?

The protobuf commit linked above referenced this bazel change https://github.com/bazelbuild/bazel/commit/a5ee2c4d979441e663cf53b2ace4daa05e5033d8

I'm also wondering if the issue is with protobuf's use of `strip_import_prefix` on the `proto_library` targets they define: https://github.com/protocolbuffers/protobuf/commit/a03d332aca5d33c5d4b2cd25037c9e37d57eff02

**Comment by jin** [comment]
cc @cushon

**Comment by Yannic** [comment]
Suspecting a combination of https://github.com/bazelbuild/bazel/commit/a5ee2c4d979441e663cf53b2ace4daa05e5033d8 and https://github.com/bazelbuild/bazel/commit/46c95dcbe2889e515a2b44b9dec00d6c13f7e9fa (/cc @lberki).

Submitted #10493 to fix this for now.
Longer-term, we should make `ProtoInfo` mandatory for `blacklisted_protos`.
