### ISSUE TITLE
py_binary failed when --crosstool_top is present

### ISSUE THREAD

**Issue by immars** [bazelbuild/bazel#10488]
### Description of the problem / feature request:

`py_binary` failed when `--crosstool_top` is present

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Hi,
I’m using `rules_pkg` in my c++ project to package compiled libraries in to .zip files.At the beginning everything worked as expected.

However when I added toolchain definition of our cross-compilers to cross-compile the library, and invoke bazel with `--crosstool_top="@hr_bazel_tools//rules_toolchain/toolchain:toolchain"`,  `pkg_zip` complained about:

```shell
ERROR: ...: in cc_toolchain_suite rule @hr_bazel_tools//rules_toolchain/toolchain:toolchain: cc_toolchain_suite '@hr_bazel_tools//rules_toolchain/toolchain:toolchain' does not contain a toolchain for cpu 'k8'
```

It seems that `pkg_zip` uses a `py_binary` as executable to package zip files. and `py_binary` seems affected by command line argument --crosstool_top. 

Then I can replicate this error with a simple `py_binary` project:

```
py_binary(
        name = "hello",
        srcs = ["hello.py"]
)
```

if I  `bazel run //:hello` with `--crosstool_top` present, the bazel also failed.

Is this a bug, or is this expected behavior? Is there any way to overwrite this behavior? I think there is no need to bother `py_binary` with any `cc_toolchain_suite` defined.

Thanks,

### What operating system are you running Bazel on?

ubuntu 16.04

### What's the output of `bazel info release`?

tried 1.0.0, 1.2.0, 2.0.0

###  Have you found anything relevant by searching the web?

nothing I'm aware of

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
