### ISSUE TITLE
Use bazel to build tensorflow cause some problem

### ISSUE THREAD

**Issue by fayeshine** [bazelbuild/bazel#1048]
https://github.com/tensorflow/tensorflow/issues/1413

**Comment by damienmg** [comment]
/cc @kchodorow @davidzchen 
This is a proxy issue on git which we don't support yet.

I believe @posco wanted to use skylark remote repository to do a git_repository using the git command.

**Comment by damienmg** [comment]
Related bug: #810

**Comment by kchodorow** [comment]
Yeah, unfortunately the git download logic is different than that of the other rules.

**Comment by kchodorow** [comment]
This probably isn't going to be fixed with the native rules, but should work when #1408 is implemented.
