### ISSUE TITLE
Building java-example always tries to download a JDK although there is one installed

### ISSUE THREAD

**Issue by heini** [bazelbuild/bazel#10483]
### Description of the problem / feature request:
While trying to get familiar with Bazel, I wanted to execute the `java-tutorial` example, which then tries to download a JDK, although there is one installed locally. The `cpp-tutorial` OTOH doesn't download a C++ toolchain in order to build the project. I don't want to have stuff from an un(known|trusted) source being installed on my system.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Clone the examples repository and execute
```
bazel build //:ProjectRunner
```
in the java-tutorial directory.

### What operating system are you running Bazel on?
Debian 10 (buster)

### What's the output of `bazel info release`?
release 2.0.0

###  Have you found anything relevant by searching the web?
No.

**Comment by jin** [comment]
This is WAI. It's expected that you don't need a JDK installed in order to build Java projects, because Bazel would and should download toolchains for you in a reproducible manner, regardless of system state.

**Comment by heini** [comment]
So it's a bug then that it doesn't do it for the C++ tutorial?

**Comment by jin** [comment]
Not a bug -- auto-downloaded toolchain is just not implemented for C++ rules yet.
