### ISSUE TITLE
Bazel sends build console output to stderr, rather than stdout.

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#10496]
### Description of the problem / feature request:

For some commands (clean, build) Bazel sends all console output to **stderr** instead of **stdout**.

### Bugs: what's the simplest, easiest way to reproduce this bug? 

`bazel clean > stdout.txt 2> stderr.txt` 
or
`bazel build my_target > stdout.txt 2> stderr.txt` 
In both cases all the output goes into **stderr**!
When I tried `bazel info` or `bazel --version` the output goes to **stdout** as expected.

### What operating system are you running Bazel on?

I observe this behavior on both Linux and Windows.

### What's the output of `bazel info release`?

release 2.0.0

**Comment by ndizazzo** [comment]
+1 on this still release 3.0.0

**Comment by andyscott** [comment]
My understanding has been that machine readable output goes to stdout and human readable output goes to stderr. This makes it pretty easy to build tooling on top of `bazel query`, for example.

**Comment by laurentlb** [comment]
I think changing the output channel can be disruptive for the users (and the existing tools that interop with Bazel) and the value seems quite small. I'm not convinced this is worth changing.

The point of `bazel query`, `bazel info` or `bazel version` is to print information to the user; this goes to stdout.
The point of `bazel clean` or `bazel build` is to perform an action. The output is merely informative logs. I think it's reasonable to use stderr here.

**Comment by philwo** [comment]
Laurent is right, the current behavior is working as intended.

**Comment by ZacharyACoon** [comment]
![Screenshot from 2021-03-02 11-37-05](https://user-images.githubusercontent.com/69929375/109704656-b71fa480-7b4b-11eb-86f6-8c8c10a95f21.png)

stdout is for information,  stderr is for **errors**

Why would this be intended?  It prevents you from easily seeing problem areas/logs as easily.

**Comment by jesseschalken** [comment]
> stdout is for information, stderr is for errors

I don't think this is accurate. When stdout is intended to be captured and machine parsed, printing informational logs to stdout would corrupt the output, so stderr is used instead, eg `tar -cv`.

This may or may not be relevant to a specific Bazel command but a sweeping expectation that stderr only contains errors is not reasonable.

**Comment by philwo** [comment]
I find this StackOverflow answer useful: https://stackoverflow.com/a/41766832

Of course in the case of Bazel it's tricky where to draw the line between normal output and diagnostic messages. If someone has a good proposal how to structure the output, feel free to write it down here and we can consider it. But in general the current behavior is not a bug.

**Comment by stabai** [comment]
This doesn't appear to be open for discussion any more, but I think that having a flag control this would make the most sense. Many CLIs (e.g. git) have a flag to instruct the tool that output needs to be stable and machine readable (or the opposite, a flag that instructs the tool that output should be optimized for a human reader). This is already the case with things like [--color](https://bazel.build/reference/command-line-reference#flag--color) and [--curses](https://bazel.build/reference/command-line-reference#flag--curses), so having one controlling which stream the information is sent to seems reasonable.

Proposal: add a `--format` flag that has several possible options:
* `auto` (default): output is written using the classic existing behavior
* `human`: output is optimized for human readers
* `json`: output is written as a series of structured data objects that is easily machine readable

This json format could also be incredibly useful for tooling that wants to wrap bazel functionality. For example, data could be tagged based on its source. If I wanted to stream the bazel output, but only for errors and tests, that filtering could be done easily.

A format like this:
```json
{
  "action": "build",
  "level": "info",
  "target": "//foo:bar_lib",
  "data": "Found 1 target...\n[0 / 4] [Prepa] BazelWorkspaceStatusAction stable-status.txt"
}
{
  "action": "build",
  "level": "error",
  "target": "//foo:baz_lib",
  "file": "/home/stabai/code/foo/baz.go",
  "line": 3,
  "column": 11,
  "data": "GoCompilePkg foo/baz.a failed: (Exit 1): builder failed: error executing command"
}
{
  "action": "test",
  "level": "error",
  "target": "//foo:bar_test",
  "data": "panic: runtime error: invalid memory address or nil pointer dereference"
}
```
