### ISSUE TITLE
"Configuring C++ toolchains" doesn't work for detecting system includes

### ISSUE THREAD

**Issue by TPolzer** [bazelbuild/bazel#10492]
### Description of the problem / feature request:

I followed the "Configuring C++ toolchains" instructions at https://docs.bazel.build/versions/master/tutorial/cc-toolchain-config.html#configuring-c-toolchains

It compiles, but then complains about undeclared inclusions:

```
BUILD:1:1: undeclared inclusion(s) in rule '//:cli':
this rule is missing dependency declarations for the following files included by 'cli.c':
'/home/tobias/.cache/bazel/_bazel_tobias/72e4a49cd339e8cfa2485584b70f9660/external/toolchain_gcc_arm_none/lib/gcc/arm-none-eabi/9.2.1/include/stdint.h'  
'/home/tobias/.cache/bazel/_bazel_tobias/72e4a49cd339e8cfa2485584b70f9660/external/toolchain_gcc_arm_none/arm-none-eabi/include/stdint.h'
'/home/tobias/.cache/bazel/_bazel_tobias/72e4a49cd339e8cfa2485584b70f9660/external/toolchain_gcc_arm_none/arm-none-eabi/include/machine/_default_types.h'
[...]
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try to `bazel build :cli` at head from https://github.com/TPolzer/thread

### What operating system are you running Bazel on?

Debian

### What's the output of `bazel info release`?

release 2.0.0.

###  Have you found anything relevant by searching the web?

It seems to work for people for emscripten, e.g. here: https://github.com/bdecoste/aws-wasm-filter/blob/0a0491c2eaf65edf1dc19cccf85fed95d1457222/toolchain/cc_toolchain_config.bzl
In case I'm holding it wrong in some way, the guide could use some information on how to debug.

**Comment by TPolzer** [comment]
Debugged this a bit and I think this is related to #4605, passing no-canonical-prefixes seems to help (it fails in linking now).
The documentation could use an update here.

**Comment by oquenchil** [comment]
The :cli target is not in the tutorial and the https://github.com/TPolzer/thread link is dead, so unfortunately I'm not able to reproduce.

Please re-open the issue if you can provide instructions on which part of the tutorial you got the error and if you did any modifications what they were.

**Comment by TPolzer** [comment]
After debugging this, I'm just asking for https://github.com/bazelbuild/bazel/issues/4605#issuecomment-364174051 to be included in the instructions. I did follow the instructions and ended up with a gcc which "helpfully" normalized paths, breaking the build.

**Comment by oquenchil** [comment]
The problem is that I can't reproduce the error you see, so I don't know where to add the flag in the instructions.
