### ISSUE TITLE
Extend sandboxing so that JUnit tests can access GPU when run from Bazel

### ISSUE THREAD

**Issue by kd8azz** [bazelbuild/bazel#1049]
Hello Bazel Team,

I have a JUnit test that seems to be unable to connect to the GPU from within a 'bazel test' command, but can in several other ways.  I'm really at quite a loss, so I've put together a minimal example to demonstrate it.

Some potentially relevant details:
OS: Ubuntu GNOME 15.10 64bit
Java: openjdk version "1.8.0_66-internal"
Bazel: head (@af69e7a) -- built on 2016-01-17
GPU: GeForce GTX 980 Ti/PCIe/SSE2
GPU Driver: NVIDIA-SMI 352.63

The [context](http://stackoverflow.com/questions/35974242/cl-platform-not-found-khr-when-calling-jocl-org-from-junit-test) that led to this bug report.
A [minimal example](https://github.com/bazelbuild/bazel/files/175179/zip.zip) to demonstrate the problem.

For your convenience, the java file in question:
```
package com.example;

import java.util.Arrays;
import org.jocl.CL;
import org.jocl.Pointer;
import org.jocl.cl_platform_id;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

public class MinimalExample {
	public static void main(String[] args) {
		MinimalExample minimalExample = new MinimalExample();
		minimalExample.test();
	}
	@Test
	public void test() {
		CL.setExceptionsEnabled(true);
		final cl_platform_id[] platforms = new cl_platform_id[1];
		CL.clGetPlatformIDs(platforms.length, platforms, null);
		long[] size = new long[1];
		CL.clGetPlatformInfo(platforms[0], CL.CL_PLATFORM_NAME, 0, null, size);
		byte[] result = new byte[(int) size[0]];
		CL.clGetPlatformInfo(platforms[0], CL.CL_PLATFORM_NAME, size[0], Pointer.to(result), null);
		throw new RuntimeException(new String(result));
	}
}
```

Running it from main works.
    
    $ bazel run //src/main/java/com/example:minimal_binary
    Exception in thread "main" java.lang.RuntimeException: NVIDIA CUDA
    at com.example.MinimalExample.test(MinimalExample.java:26)
    at com.example.MinimalExample.main(MinimalExample.java:15)
    

Running the test from bazel does NOT work.
    
    $ bazel test //src/main/java/com/example:minimal_test && head -n20 <error file>
    exec ${PAGER:-/usr/bin/less} "$0" || exit 1
    -----------------------------------------------------------------------------
    JUnit version 4.12
    .E
    Time: 0.017
    There was 1 failure:
    1) test(com.example.MinimalExample)
    org.jocl.CLException: CL_PLATFORM_NOT_FOUND_KHR
    at org.jocl.CL.checkResult(CL.java:787)
    at org.jocl.CL.clGetPlatformIDs(CL.java:2152)
    at com.example.MinimalExample.test(MinimalExample.java:21)
    

Yet, when I run the command with a -s, and then copy+paste the command bazel ran, it works.
    
    $ (cd /home/kd8azz/.cache/bazel/_bazel_kd8azz/bec250408f32ccc252d6a6988f4ddcdc/minimal_example && \
    > exec env - \
    > JAVA_RUNFILES=/home/kd8azz/.cache/bazel/_bazel_kd8azz/bec250408f32ccc252d6a6988f4ddcdc/minimal_example/bazel-out/local_linux-fastbuild/bin/src/main/java/com/example/minimal_test.runfiles \
    > PATH=/home/kd8azz/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/kd8azz/bin \
    > PYTHON_RUNFILES=/home/kd8azz/.cache/bazel/_bazel_kd8azz/bec250408f32ccc252d6a6988f4ddcdc/minimal_example/bazel-out/local_linux-fastbuild/bin/src/main/java/com/example/minimal_test.runfiles \
    > TEST_SIZE=medium \
    > TEST_SRCDIR=/home/kd8azz/.cache/bazel/_bazel_kd8azz/bec250408f32ccc252d6a6988f4ddcdc/minimal_example/bazel-out/local_linux-fastbuild/bin/src/main/java/com/example/minimal_test.runfiles \
    > TEST_TIMEOUT=300 \
    > TEST_TMPDIR=/home/kd8azz/.cache/bazel/_bazel_kd8azz/bec250408f32ccc252d6a6988f4ddcdc/minimal_example/_tmp/minimal_test_1 \
    > TEST_WORKSPACE='' \
    > TZ=UTC \
    > XML_OUTPUT_FILE=/home/kd8azz/.cache/bazel/_bazel_kd8azz/bec250408f32ccc252d6a6988f4ddcdc/minimal_example/bazel-out/local_linux-fastbuild/testlogs/src/main/java/com/example/minimal_test/test.xml \
    > external/bazel_tools/tools/test/test-setup.sh src/main/java/com/example/minimal_test com.example.MinimalExample)
    exec ${PAGER:-/usr/bin/less} "$0" || exit 1
    -----------------------------------------------------------------------------
    JUnit version 4.12
    .E
    Time: 0.018
    There was 1 failure:
    1) test(com.example.MinimalExample)
    java.lang.RuntimeException: NVIDIA CUDA
    at com.example.MinimalExample.test(MinimalExample.java:26)
    

Now to be fair, I should mention that this cannot run from eclipse either.  But, it can run from junit directly
    
    $ cd bazel-bin/src/main/java/com/example/ &&  java -cp minimal_test.runfiles/external/hamcrest-all/jar/hamcrest-all-1.3.jar:minimal_test.runfiles/external/jocl/jar/jocl-0.2.0-RC00.jar:minimal_test.runfiles/external/junit/jar/junit-4.12.jar:minimal_test.runfiles/external/truth/jar/truth-0.27.jar:minimal_test.jar org.junit.runner.JUnitCore com.example.MinimalExample
    JUnit version 4.12
    .E
    Time: 0.014
    There was 1 failure:
    1) test(com.example.MinimalExample)
    java.lang.RuntimeException: NVIDIA CUDA
    at com.example.MinimalExample.test(MinimalExample.java:26)

**Comment by bsilver8192** [comment]
What happens when you disable the sandbox with `--spawn_strategy=standalone`?

[Bazel's sandboxing](http://bazel.io/blog/2015/09/11/sandboxing.html)  intentionally disables access to most of the system to make tests more hermetic, which sounds like it might interfere with getting to the GPU.

**Comment by kd8azz** [comment]
Excellent.  The JUnit test can contact the GPU when run with --spawn_strategy=standalone.

Is there an argument for the java_test( ) BUILD target, that will make it run this way?  I would like the ability to ```bazel test src/test/...```, and only a small handful of my tests will rely on the GPU.  Most should remain sandboxed.

**Comment by bsilver8192** [comment]
`tags = ['local']` should disable sandboxing for a specific test.

Also, do you know what exactly needs to be included in the sandbox to allow accessing the GPU? If it's something simple, I think it would be reasonable to have Bazel do it so you can leave the sandbox enabled.

**Comment by kd8azz** [comment]
To preface: I don't know; I'm just starting out with GPU programming.

What I do know is that the exception I'm getting indicates an [icd](https://www.khronos.org/registry/cl/extensions/khr/cl_khr_icd.txt) load failure.  So presumably there is a GPU driver of some sort, presumably related to the apt-get target ```nvidia-opencl-icd-352```.  But I have zero experience troubleshooting drivers, and lack a proper understanding of the linux driver architecture.

**Comment by kd8azz** [comment]
Is there a way I can dump the sandboxing parameters, or otherwise do a diff between the sandbox environment and the non-sandboxed environment?

**Comment by bsilver8192** [comment]
If you run Bazel with `--sandbox_debug`, it will print out all of the filesystem paths getting mounted for failing commands (like your test). If you have an idea about what package has the problematic files, try comparing the output of `dpkg -L nvidia-opencl-icd-352` to the paths Bazel is mounting (Bazel not getting `/usr/local` is a common issue; definitely look for that).

**Comment by kd8azz** [comment]
$ dpkg -L nvidia-opencl-icd-352
/etc
/etc/OpenCL
/etc/OpenCL/vendors

```$ cat <logfile> | grep OpenCL``` outputs nothing.

So it looks like ```/etc/OpenCL(/vendors)```.  Did I do that right?

**Comment by kd8azz** [comment]
To be clear,
```
$ cat <logfile> | grep etc
src/main/tools/namespace-sandbox.c:512: mount: /etc
src/main/tools/namespace-sandbox.c:512: mount: /etc/java-8-openjdk/accessibility.properties
src/main/tools/namespace-sandbox.c:512: mount: /etc/java-8-openjdk/calendars.properties
src/main/tools/namespace-sandbox.c:512: mount: /etc/java-8-openjdk/content-types.properties
<truncated>
```

So, the logfile does have debugging info in it.

**Comment by kd8azz** [comment]
And finally,
```
$ tree /etc/OpenCL/
/etc/OpenCL/
└── vendors
    └── nvidia.icd

1 directory, 1 file
```

**Comment by dslomov** [comment]
@philwo FYI

**Comment by philwo** [comment]
/etc should be mounted by default - it's OK that you don't see /etc/OpenCL specifically mentioned in the log file, because it mounts the whole directory, so it should be included.

If you build Bazel from HEAD and run your test using "bazel test --sandbox_debug --verbose_failures", Bazel should print a command-line that includes the "namespace-sandbox" binary and some instructions.

If you then run the whole command-line (including the namespace-sandbox part) in your shell, the sandbox should drop you into a shell running *inside* the sandbox :) From there, you could look around and see if /etc/OpenCL is really there and contains all the files it should, maybe try to run some GPU debugging tools to see if they can talk to the GPU, ...

This is a very new feature written by @hermione521 recently and we'd be happy to get feedback if it helps you.

It is possible that there is some required device file in /dev missing. If that's the case and you find out which, please reply back with that information too, because maybe we can find out how to get that mounted.

Of course, to get you going, you can add "tags = ["local"]" to your test in the BUILD file, as Brian suggested. It's definitely recommend to use the sandbox, but it's fine to disable it for certain things if you know what you're doing and if there's no better fix.

**Comment by kd8azz** [comment]
Sorry for taking so long to reply.  My free time is a transient resource, and upgrading bazel was non-trivial, as several features had breaking changes.

To confirm, the test does work with "tags = ["local"]".

Unfortunately, I cannot get the namespace-sandbox command to come up.

```
$ bazel test src/test/java/cl:Test --sandbox_debug --verbose_failures
INFO: Found 1 test target...
FAIL: //src/test/java/cl:Test (see /home/user/.cache/bazel/_bazel_user/00bb1210de2173919b75bf7db0a13118/bazel-out/local_linux-fastbuild/testlogs/src/test/java/cl/Test/test.log).
Target //src/test/java/cl:Test up-to-date:
  bazel-bin/src/test/java/cl/Test.jar
  bazel-bin/src/test/java/cl/Test
INFO: Elapsed time: 0.401s, Critical Path: 0.35s
//src/test/java/cl:Test                               FAILED in 0.3s
  /home/user/.cache/bazel/_bazel_user/00bb1210de2173919b75bf7db0a13118/bazel-out/local_linux-fastbuild/testlogs/src/test/java/cl/Test/test.log

Executed 1 out of 1 tests: 1 fails locally.
```

```
$ cat /home/user/.cache/bazel/_bazel_user/00bb1210de2173919b75bf7db0a13118/bazel-out/local_linux-fastbuild/testlogs/src/test/java/cl/Test/test.log | grep namespace-sandbox
```
Yields a large number of log lines of the form
```
src/main/tools/namespace-sandbox.c:563: mount: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
```

```
$ cat /home/user/.cache/bazel/_bazel_user/00bb1210de2173919b75bf7db0a13118/bazel-out/local_linux-fastbuild/testlogs/src/test/java/cl/Test/test.log | grep namespace-sandbox | grep -v namespace-sandbox.c
```
Yields nothing.

Am I doing something wrong?

**Comment by philwo** [comment]
@hermione521 Could you please check if we print the new error message including namespace-sandbox and the instructions on how to get a shell even when we use "bazel test --verbose_failures --sandbox_debug"?

**Comment by kd8azz** [comment]
Ping?

**Comment by hermione521** [comment]
Sorry for the late reply. I guess I've found the problem, will fix it soon.

**Comment by hermione521** [comment]
Hi @kd8azz, the commit above should give you instructions on sandbox failures. Please try with "bazel test --sandbox_debug --verbose_failures". There might be a lot of outputs.

**Comment by kd8azz** [comment]
Thanks!

Looking around, it took me a little while to get my bearings.  I was expecting to find /etc/OpenCL/vendors/nvidia.icd missing, but in fact, it was there.

@philwo mentioned that I should check /dev.  In fact, there is a large difference.  The sandbox has `fd  null  random  urandom  zero`, whereas my machine has many more.  Notable: `nvidia0` and `nvidiactl`.  Others may be relevant as well; I'm not familiar with /dev/.

Additionally, I have run my unit test manually, from within the sandbox, and it produces the same exception `org.jocl.CLException: CL_PLATFORM_NOT_FOUND_KHR`.  I wasn't expecting it to work, but I figured a sanity check wouldn't hurt.  As far as 
> maybe try to run some GPU debugging tools 
I am not experienced enough to have a toolset built up yet.  If needed, I'll come back to this later, when I do.

Is there a way I could try adding /dev/nvidia0 to the sandbox myself, to enable faster iteration on this bug, without me modifying bazel?

**Comment by bsilver8192** [comment]
With 0.2.1, you can use --sandbox_add_path. That should work on files in /dev just fine.

**Comment by hermione521** [comment]
I'm glad it works. The difference of /dev/ might be because of symlinks. You can try `--sandbox_add_path=/dev/nvidia0 --sandbox_add_path=nvidiactl`, but if there is symlink or device file, there might be some problems. If that happens, please try `ll` and copy it here. Thanks.

**Comment by kd8azz** [comment]
`bazel test src/test/... --sandbox_debug --verbose_failures --sandbox_add_path=/dev/nvidia0 --sandbox_add_path=/dev/nvidiactl` does successfully add nvidia0 and nvidiactl to /dev/ in the sandbox, but the unit test still fails.  When I get some time, I'll dig around and try adding other things as well, to see if I can figure out what's missing.  Suggestions appreciated.

**Comment by kd8azz** [comment]
nvidia0 and nvidiactl are not symlinks on my system.

**Comment by hermione521** [comment]
We have a new version of sandboxing that almost everything is readable, so this problem should go away. Can you check? Thanks.

**Comment by kd8azz** [comment]
Yes, my test now works without `tags = ['local']`.  Thanks!
