### ISSUE TITLE
Can't build bazelbuild/examples/cpp-tutorial/stage1 with clang-9

### ISSUE THREAD

**Issue by soonho-tri** [bazelbuild/bazel#10497]
### Description of the problem / feature request:

Fail to build bazelbuild/examples/cpp-tutorial/stage1 with clang-9.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

 - Ubuntu-18.04 (Bionic)
 - Install clang-9 by following the instructions at https://apt.llvm.org/. `clang-9 --version` gives `clang version 9.0.1-+20191211102125+c1a0a213378-1~exp1~20191211212701.104`.
 - Check out https://github.com/bazelbuild/examples
 - Use `bazel-2.0.0`
 - Run `CC=clang-9 CXX=clang++-9 bazel build //...` at `cpp-tutorial/stage1`

It gives the following:

```
Use --sandbox_debug to see verbose messages from the sandbox
In file included from main/hello-world.cc:1:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/ctime:42:
/usr/include/time.h:29:10: fatal error: 'stddef.h' file not found
#include <stddef.h>
         ^~~~~~~~~~
1 error generated.
Target //main:hello-world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.661s, Critical Path: 0.26s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

Note that the system default gcc/g++ (7.4) is installed.

### What operating system are you running Bazel on?

Ubuntu-18.04 (Bionic)

### What's the output of `bazel info release`?

`bazel version` returns:

```
Build label: 2.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 19 12:30:18 2019 (1576758618)
Build timestamp: 1576758618
Build timestamp as int: 1576758618
```

**Comment by soonho-tri** [comment]
Note that:

1) `clang++-9 main/hello-world.cc` runs without a problem. So I suspect that this is a bazel issue.
2) `clang-8` (`8.0.1-svn369350-1~exp1~20190820121219.79`) does not have this issue.

**Comment by oquenchil** [comment]
I can't reproduce with
`Build label: 3.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Apr 22 10:32:27 2020 (1587551547)
Build timestamp: 1587551547
Build timestamp as int: 1587551547
`
and
```
clang version 9.0.1-6+build1 
```

Please re-open with updated instructions if you still see this error.
