### ISSUE TITLE
Patches fail to apply cleanly with Bazel 2.0.0

### ISSUE THREAD

**Issue by dapirian** [bazelbuild/bazel#10506]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Every patch I have of `http_archive`s is failing to patch after attempting to upgrade to Bazel 2.0.0, despite not having changed the `http_archive` at all (either the url/sha256 or patch). Did the way bazel is applying patches change?

These patches were generated via `git diff master --no-prefix`

**Comment by irengrig** [comment]
Hi @dapirian, thank you for reporting the issue!
Could you please share the error message you get, and maybe the example of the patch?

/cc @meteorcloudy

**Comment by meteorcloudy** [comment]
@dapirian Which version of Bazel were you using previously?

**Comment by dapirian** [comment]
This was just a different with the native patch vs bazel patch where native defaulted to no prefix (-p0) and bazel didn't
