### ISSUE TITLE
bazel.sh prefers .bazelversion over tools/bazel script in 2.0.0

### ISSUE THREAD

**Issue by kellycampbell** [bazelbuild/bazel#10505]
### Description of the problem / feature request:

Bazel 2.0.0's debian package caused our projects builds to break when the system apt upgrade installed the new version.

```
ERROR: The project you're trying to build requires Bazel 1.0.1 (specified in /home/user/project/.bazelversion), but it wasn't found in /usr/bin.

You can install the required Bazel version via apt:
  sudo apt update && sudo apt install bazel-1.0.1
```

We use the tools/bazel special location to launch a bazelisk which is checked into the project and then it uses the .bazelversion file to determine which version to install and run.

I find this to be much easier to manage across a team than if we had to manually select and install specific versions of bazel apt packages. For example, some of our projects haven't been able to fully update to bazel 1.0.0 yet due to some tool incompatibilities, so depending on which project is being built, we might need bazel 0.29 or 1.x.

My initial thought on how to fix is to move the part of bazel.sh that execs the tools/bazel wrapper from the end of the script to just after `get_workspace_root` is called so it is run before doing the other checks. However, I understand this might not work in all cases, e.g. where you want to apply the .bazelversion before the wrapper is called. I don't have a good idea how to make it handle this situation though other than add some other file that tells it to use the bazel wrapper only and not try to determine version.

### Any other information, logs, or outputs that you want to share?

Here's our tools/bazel script:
```
#!/bin/bash

set -eu

export BAZELISK_SKIP_WRAPPER=1

BAZELISK_VERSION=1.0.0
BAZELISK_DIR="$(dirname "${BASH_SOURCE[0]}")/bazelisk"

if [ "$(uname -s)" == "Darwin" ]; then
    BAZELISK="${BAZELISK_DIR}/bazelisk-${BAZELISK_VERSION}-darwin-amd64"
elif [ "$(uname -s)" == "Linux" ]; then
    BAZELISK="${BAZELISK_DIR}/bazelisk-${BAZELISK_VERSION}-linux-amd64"
fi

set +u

if [ -z "${NO_BAZELISK}" ]; then
   exec -a "$0" "${BAZELISK}" "$@"
else
   exec -a "$0" bazel "$@"
fi
```

**Comment by kellycampbell** [comment]
cc: @philwo

**Comment by jin** [comment]
cc @meteorcloudy

**Comment by philwo** [comment]
@kellycampbell Mhm... I see. I'll have to think about this a bit.

Would it be an OK solution to ask users to `apt-get install bazelisk` (which would provide `/usr/bin/bazel`, but it's actually Bazelisk) on your workstations instead of `apt-get install bazel`? Then you also wouldn't have to check-in Bazelisk as `tools/bazel`. Note that this doesn't yet work, we don't have a Debian package for Bazelisk yet, but we could create one.

**Comment by Jdban** [comment]
We ran into this too. We have a similar setup with `tools/bazel` calling `bazelisk`
It's kind of annoying right now that `bazel` is looking at the `.bazelversion` file at all.

It might be nice at some point if `bazel` had its own fully-supported method for specifying the version of bazel to use, maybe in the WORKSPACE file?

**Comment by kellycampbell** [comment]
Closing since #10356 covers this.
