### ISSUE TITLE
Unable to use jar command on ubuntu

### ISSUE THREAD

**Issue by wolfgangmeyers** [bazelbuild/bazel#1051]
I'm building a project on ubutnu 14.04 64 bit. I created a genrule target that uses the jar command:

tools = ["@local_jdk//:bin/jar"]

And I store the location in an environment variable in the cmd:

"JAR=$$(pwd)/$(location @local_jdk//:bin/jar)"

Then I try to use $$JAR later in the command, it fails with this error:

external/local_jdk/bin/jar: error while loading shared libraries: libjli.so: cannot open shared object file: No such file or directory

Typically I'd use java_library for dealing with jar files, but there is some very specific packaging I need to do. I think maybe the LD_LIBRARY_PATH needs to be set in order for the jdk tools to work correctly from genrule targets.

**Comment by wolfgangmeyers** [comment]
I found a solution. Need to add the following in the tools:

    tools = [
        "@local_jdk//:bin/jar",
        "@local_jdk//:jdk-lib",
        "@local_jdk//:jre-default",
    ],

**Comment by wolfgangmeyers** [comment]
Looks like jar is a filegroup:
https://github.com/bazelbuild/bazel/blob/master/src/main/tools/jdk.BUILD#L31

Would it be possible to make this a binary rule instead so that jdk-lib and jre-default are included as dependencies?

**Comment by dslomov** [comment]
@damienmg : wdyt on @wolfgangmeyers suggestion?

**Comment by damienmg** [comment]
I don't know how we can do that. Maybe using a sh_binary but we have another bug (sh_binary cannot take other than .sh and .bash).

Other than the technical problem this seems like a good idea.

**Comment by ulfjack** [comment]
We have an (internal, sorry) proposal to add a java_runtime rule, which would expose a $(jar) make variable for use by genrules. We need to move more of our design discussions external, but....
