### ISSUE TITLE
java_binary rule is not generating java9 module compatible executable

### ISSUE THREAD

**Issue by suman-ganta** [bazelbuild/bazel#10514]
### Description of the problem / feature request:

When java_binary rule is used, the generated script is not compatible with java9 modules.

### Feature requests: what underlying problem are you trying to solve with this feature?

This is a bug, not a feature request. Feel free to change it to feature if my interpretation is incorrect.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Generate java executable with `java_binary` rule and notice the generated script has no option to set `--module-path` or `--module` to provide java9 modules.
The shell script generated has no traces of Java9 module options in it. I did not find a way to set `--module-path` or `--module` options which are essential to enable module subsystem in java.

Checked [associated template](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt), which seem to be the source of the generated script, but could not find any references to it.
Also, the `runtime_deps` parameter of `java_binary` seem to be translated into traditional classpath. So, essentially modules are suppressed completely.

### What operating system are you running Bazel on?

MacOS

### What's the output of `bazel info release`?

release 0.28.1

###  Have you found anything relevant by searching the web?

No, nothing found

### Any other information, logs, or outputs that you want to share?

Since this is reproducible with any java_binary rule, I'm not associating any logs here.

**Comment by comius** [comment]
We're not working on java9+ module support in the foreseeable future.
