### ISSUE TITLE
ctx.delete missing in utils.bzl?

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#10518]
@aehlig I just read the code of our http_archive repository rule and came across this part:
https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/utils.bzl#L50-L57

I don't know the exact semantics of `ctx.file`, `ctx.delete` and `ctx.symlink` regarding how they treat the case of a file already existing, but it seems like we either need to add `ctx.delete("WORKSPACE")` to the `else` clause, too, or we don't have to `ctx.delete` in the other two cases - right?

**Comment by aehlig** [comment]
Looking at the documentation (and verifying these assertions in tests)
- `ctx.file` removes a pre-existing file,
- while `ctx.symlink` may (and actually does) assume that the target location is empty.

So, we can remove two occurrences of `ctx.delete`. I will prepare a corresponding change.
