### ISSUE TITLE
Make Bazelisk the always-installed front end wrapper by which bazel is executed

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/bazel#10520]
Bazelisk provides a stellar mechanism for managing bazel versions for a given repository setup. I recommend that:

   1. bazelisk be explicitly listed in the bazel installation instructions as a way of installing and managing bazel execution
   2. have a brew/apt/whatever packaging option for bazelisk to symlink `bazel` to point to baselisk (should be a bug on the bazelisk project)
   3. Rework the bash completion to support bazelisk when it's not run as `bazel`

> Note: `#3` above is not really necessary if `#2` is implemented, since bash completion
> works just fine with bazelisk invoked AS bazel.

**Comment by sudoforge** [comment]
Just a note here: If you or your loved ones use Arch Linux, I maintain [`bazelisk-bin`][0], which installs Bazelisk as `bazel`, which effectively accomplishes the goal of this feature request. 

[0]: https://aur.archlinux.org/packages/bazelisk-bin/

**Comment by meisterT** [comment]
I think we should really promote bazelisk more. Look at the install section in our docs:
![image](https://user-images.githubusercontent.com/418721/153218531-9f9b6df2-2c2b-4f2f-b6aa-a05f0a632e06.png)


cc @meteorcloudy @fweikert @philomathing

**Comment by meteorcloudy** [comment]
This is fixed in our updated documentation!
