### ISSUE TITLE
StackOverflowError while building module with bazel

### ISSUE THREAD

**Issue by ash-srini** [bazelbuild/bazel#10526]
### Description of the problem / feature request:

One of the modules we are trying to build using bazel is erratically failing with StackOverflowError. 

**Bazel version** : Build label: 1.0.1
**Java version:**
`java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)`

Following is configured in bazelrc for using local jdk.
`build --host_javabase=@local_jdk//:jdk --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8 --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8`

Same error is seen while using embeded JDK (OpenJDK11) as well without the additional commands in bazelrc.

**Stacktrace:** Error stacktrace is attacked below

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Unable to provide exact way to reproduce since this is seen erratically and since stacktrace has some kind of compiler message bug.

### What operating system are you running Bazel on?

- Ubuntu 16.04.4 LTS
- Ubuntu 18
- MacOS 10.14.6 

### What's the output of `bazel info release`?
`$ bazel info release
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/home/ashsrinivasan/.cache/bazel/_bazel_ashsrinivasan/cea116372ae587df9a33edce9ae33bd5/command.profile.gz'
release 1.0.1`

###  Have you found anything relevant by searching the web?
 - Bazel internally uses openjdk11, using this embeded JDK we see same error with error message as seen below with same stacktrace:
`compiler message file broken: key=compiler.misc.msg.bug arguments=11.0.1, {1}, {2}, {3}, {4}, {5}, {6}, {7}
java.lang.StackOverflowError
	at jdk.compiler/com.sun.tools.javac.comp.Check.checkType(Check.java:554)
	at jdk.compiler/com.sun.tools.javac.comp.Attr$ResultInfo.check(Attr.java:518)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.check(Attr.java:250)`
Reference for openjdk11 bug: https://bugs.openjdk.java.net/browse/JDK-8222754 

- When trying to use local JDK (version mentioned above), we see the same issue with the stacktrace posted below.

### Any other information, logs, or outputs that you want to share?

Logs: 
Logs from using local JDK (version mentioned above along with bazel command options from bazelrc)
[Stackoverflow_local_jdk.log](https://github.com/bazelbuild/bazel/files/4026920/Stackoverflow_local_jdk.log)

Using default embeded jdk from bazel.
[Stackoverflow_embeded_jdk.log](https://github.com/bazelbuild/bazel/files/4026918/Stackoverflow_embeded_jdk.log)

Alternated approaches tried to mitigate the issue:
- Used higher memory system (8 vCPUs, 30 GB memory)
- Increasing JVM stack size to 4096 using bazel '--jvmopt' 
- Error is seen with and without remote cache.
- --verbose_failures and --subcommands=pretty_print does not help in pinpointing the point of failure.

**Comment by james-deee** [comment]
Any luck here? We're hitting this same error.
