### ISSUE TITLE
mingw and msys2 C++ toolchains not automatically registered on Windows

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel#10529]
### Description of the problem / feature request:

On a system with only `msys2` and `mingw` installed (not MSVC), when `--incompatible_enable_cc_toolchain_resolution` is enabled, toolchains should be automatically declared and registered for `msys2` and `mingw` and not for MSVC.

Currently, on such a system, several toolchains are declared, but only the toolchain for MSVC is registered automatically, even though that's the one that doesn't work.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Declare a trivial `cc_binary`:

```
cc_binary(
    name = "hello",
    srcs = ["hello.c"],
)
```

Build with `bazel build //:hello`:

```
The target you are compiling requires Visual C++ build tools.
Bazel couldn't find a valid Visual C++ build tools installation on your machine.
```

In order to use `mingw`, a `platform` like the one below needs to be defined:

```
platform(
    name = "windows_mingw",
    constraint_values = [
        "@bazel_tools//tools/cpp:mingw",
        "@platforms//os:windows",
        "@platforms//cpu:x86_64",
    ],
)
```

Then some additional flags are needed:

```
--host_platform=//:windows_mingw
--platforms=//:windows_mingw
--extra_toolchains=@local_config_cc//:cc-toolchain-x64_windows_mingw
```

This registers the `mingw` toolchain (which is automatically declared but not registered), then forces it to be selected by targeting a platform with the `@bazel_tools//tools/cpp:mingw` constraint.

### What operating system are you running Bazel on?

Windows 10 x86_64

### What's the output of `bazel info release`?

```
release 2.0.0
```

### Any other information, logs, or outputs that you want to share?

My understanding of how this works (may be wrong):

* The [`cc_configure`](https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/bazel/rules/cpp/cc_configure.WORKSPACE) macro is called automatically at the end of WORKSPACE.
* This declares the `local_config_cc` repository using [`cc_autoconf`](https://source.bazel.build/bazel/+/master:tools/cpp/cc_configure.bzl;l=143). This seems to work correctly. I can look at the BUILD file in that repository, and I see `cc-toolchain-x64_windows_msys` declared, pointing to `cc-compiler-x64_windows_msys`, which has the correct paths.
* `cc_configure` also declares the `local_config_cc_toolchains` repository using [`cc_autoconf_toolchains`](https://source.bazel.build/bazel/+/master:tools/cpp/cc_configure.bzl;l=79). This declares a separate toolchain target, but it points back to `@local_config_cc//:cc-compiler-x64_windows`. It does not declare other toolchains.
* The toolchains matched by `@local_config_cc_toolchains//:all` are registered. That just matches the one toolchain for MSVC.

**Comment by jayconrod** [comment]
cc @katre @hlopko 

Related to #7260

**Comment by jheaff1** [comment]
Hi,

Is there any update on this? Is there a standard way of configuring Bazel so that the VC compiler need not be installed and mingw is used instead?
