### ISSUE TITLE
Feature request: download external dependency from other protocols

### ISSUE THREAD

**Issue by gmendonca** [bazelbuild/bazel#10524]
### Description of the problem / feature request:

I know `bazel` can use `gcs://` or `s3://` for caching, but it's common for some build tools to actually publish artifacts to GCS or S3, for example. S3 offers an http api for public buckets, however if using private buckets, or you have to relay on downloading artifacts from `s3://` directly for authentication or use signed URLs (see https://github.com/bazelbuild/bazel/issues/5131). My feature request would be to allow different types of protocols to `repository_ctx.download()` and to declare maven repositories other than `http`. This way, I'm not sure if this is better done natively or through plugins.

**Comment by jin** [comment]
Dupe: https://github.com/bazelbuild/bazel/issues/10442
