### ISSUE TITLE
alwayslink doesn't work for static archives (`.a`)

### ISSUE THREAD

**Issue by wesleyw72** [bazelbuild/bazel#10522]
### Description of the problem / feature request:

If I have a `cc_library` with a `.a` files in the `srcs` and `alwayslink` set to `True`, that static archive isn't linked into final binaries that depend on the `cc_library`.

There is a work around, by changing the extension of the `.a` file to `.lo` ("Always Link library"). But this seems counter intuitive.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a `cc_binary` that depends on a `cc_library` with a `.a` file in the `srcs` and `alwayslink` set to `True`. The symbols from the static archive don't appear in the final binary.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

release 1.2.1

**Comment by vxfury** [comment]
also doesn't work for shared libraries.
