### ISSUE TITLE
Async download of build artifacts

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#10525]
### Description of the problem / feature request:

When performing a remote build, the `--remote_download_minimal` flag is very useful for making things seem fast, but not so helpful if the local bazel daemon is restarted for some reason. It would be ideal if bazel build (and test) could download build outputs asynchronously. This would allow cases where local execution is desirable (eg. debugging, or when refreshing the build graph) to also execute quickly

### Feature requests: what underlying problem are you trying to solve with this feature?

To make local builds and tests benefit from an RBE without needing to constantly download everything before indicating that a build is complete.

###  Have you found anything relevant by searching the web?

No.

**Comment by coeuvre** [comment]
Hi Simon, I am working on improving this. Please check #12665 and feel free to share your ideas.

**Comment by brentleyjones** [comment]
@coeuvre Was your commit supposed to close this? I don't think we have async downloads of outputs yet, do we?

**Comment by brentleyjones** [comment]
The feature request says this though:

> To make local builds and tests benefit from an RBE without needing to constantly download everything **before indicating that a build is complete.**

So I believe what is desired is similar to fully async bes uploading, for the downloading to continue in the background, after the command completes and returns the prompt to the user.

**Comment by coeuvre** [comment]
> before indicating that a build is complete.

Can you help me understand user cases for this?

IMO, if users request toplevel outputs, they expect outputs are there after the build complete. Otherwise, they can just use `minimal` mode. If the consumer is IDE or other tools, it would confuse them if the build complete but outputs are not there.

**Comment by brentleyjones** [comment]
Maybe @shs96c can elaborate more.

I know personally for some of my projects that there is a set of outputs that if they appear asynchronously it would be fine. I'm also fine with this "go as fast as possible during the build, but block at the end for any remaining downloads" behavior.
