### ISSUE TITLE
Show debug information about multiplex worker vs regular persistent worker

### ISSUE THREAD

**Issue by fenghaolw** [bazelbuild/bazel#10535]
### Description of the problem / feature request:

Currently when we replace our persistent worker with [multiplex worker](https://docs.bazel.build/versions/master/multiplex-worker.html), it is unclear which one is being used. `--worker_verbose` shows "Create new ... worker (id #)", but does not display the debug information for multiplex worker.

### Feature requests: what underlying problem are you trying to solve with this feature?

Add additional debug information for better developer experience.

### Any other information, logs, or outputs that you want to share?

It sounds to me we could add additional information in [WorkerKey](https://github.com/bazelbuild/bazel/blob/8c96c0614684243b0a51d0ad8ddc27b0258b4af1/src/main/java/com/google/devtools/build/lib/worker/WorkerKey.java) and then print this debug information in [WorkerFactory](https://github.com/bazelbuild/bazel/blob/8c96c0614684243b0a51d0ad8ddc27b0258b4af1/src/main/java/com/google/devtools/build/lib/worker/WorkerFactory.java)?

**Comment by susinmotion** [comment]
@borkaehw @SrodriguezO

**Comment by borkaehw** [comment]
Sounds like a good suggestion. I will check if I have bandwidth in the following few weeks. Anyone is welcome to implement this as well. Thanks.
