### ISSUE TITLE
Provide repo with CROSSTOOL for cross-compiling for other platforms 

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1053]
Must-have platform:
- Raspberry PI

Should-have:
- Old Linux platforms that do not support have Java 8
- NVIDIA Tegra

@dslomov: can you follow-up on that one? just make sure we do it by next quarter (TBD who is going to do it exactly).

**Comment by AustinSchuh** [comment]
@bsilver8192 
We've got compilers and crosstool files for the NI roboRIO used for FRC and the Jetson (running armhf debian jessie) which we can give you.

**Comment by bsilver8192** [comment]
Indeed. I would be happy to get those included.

I'm using the Linaro arm-linux-gnueabihf toolchain set up to work on any Debian armhf system (which should handle Tegra boards, the BeagleBone Black, and newer Raspberry Pis).

They are also setup to nicely download the relevant compilers (for amd64 Debian Jessie at least). I think it makes a lot of sense to distribute compilers which do that, so any thoughts on where to host the files? It's currently a 171M clang tarball (used as the actual compiler for armhf), a 300M linaro GCC tarball (used for headers, libraries, and binutils for armhf), and a 71M roboRIO GCC tarball.

**Comment by damienmg** [comment]
For storage, as long as the licensing is ok, we can store the binary files on the bazel GCS bucket. We still needs to figure out how we going to ship the repositories themselves but I guess a repository like tools_cc_roborio or something like that would be acceptable.

**Comment by damienmg** [comment]
@bsilver8192 Can we start sharing those?

**Comment by pedrokiefer** [comment]
I've put together a crosstool for stm32 (https://github.com/pedrokiefer/rules_stm32), still needs some tweaks for building the HAL library provided by ST automatically, it works fine if you have them at your repository. Also need to add support for windows and mac, as ARM provide gcc packages for those OS. From bazel roadmap, I think I'll wait release 0.5 for adding windows support.

As for the HAL library, I think #2163 needs to be fixed, so the rule can consume a filegroup of HAL sources and add the user defined headers (basically hal configuration).

**Comment by jkuszmaul** [comment]
If it's helpful, I've got a working crosstool for the BBB and one that worked with an RPi reasonably recently. (https://github.com/wpisailbot/boat/tree/testing/tools/arm_compiler). Kind of messy (and probably has some incorrect terminology,  as I was really just trying to get it working back when I did it and haven't tried to see if it works on anyone else's machines. Not sure if it'll be helpful, but I hadn't seen anything elsewhere.

**Comment by ulfjack** [comment]
Damien tells me I should close this as obsolete. He says there's a bazel-toolchains repo.

**Comment by damienmg** [comment]
https://github.com/bazelbuild/bazel-toolchains is the repo. I think this
should go there.

**Comment by lshamis** [comment]
bazel-toolchains disabled its issue tracker. @damienmg, is this still a planned feature?
