### ISSUE TITLE
bazel-bin in execution root

### ISSUE THREAD

**Issue by elbaro** [bazelbuild/bazel#10549]
### Description of the problem / feature request:

Add a symlink `bazel-bin` in the execution root.

### Feature requests: what underlying problem are you trying to solve with this 

My .bazelrc contains a path depending on k8-xx to provide a shorter includes to generated files.
```
build --cxxopts="-iquotebazel-bin/cc"
```
However bazel-bin does not exist. I have to manually provide
```
build --cxxopts="-iquotebazel-out/k8-opt/bin/cc"
build --cxxopts="-iquotebazel-out/k8-fastbuild/bin/cc"
build --cxxopts="-iquotebazel-out/k8-dbg/bin/cc"
```
but this can pick up the wrong files. (can use files under k8-opt with -c dbg)

### What's the output of `bazel info release`?

release 2.0.0

**Comment by janakdr** [comment]
If I understand correctly, adding such includes means that your build is extremely non-hermetic, since it can pick up files from anywhere in your output tree. It also won't work with sandboxed/remote execution. We don't plan to support such builds.
