### ISSUE TITLE
Doc sanity check: does cquery output analysis.proto or analysis_v2.proto?

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel#10540]
### Description of the problem / feature request:

https://docs.bazel.build/versions/master/cquery.html#proto says:

    The definition of the protocol buffer can be found at
    src/main/protobuf/analysis.proto.

But I see there's also [analysis_v2.proto](https://github.com/bazelbuild/bazel/blob/master/src/main/protobuf/analysis_v2.proto)

Which one should the documentation reference?

**Comment by joeleba** [comment]
Thanks for raising this. analysis_v2.proto isn't finalized yet. I'll update the documentation when we deprecate analysis.proto.

**Comment by dws** [comment]
In Bazel 6 we see:
```
$ bazel query //src/main/protobuf:all | grep analysis | sort
[...]
@io_bazel//src/main/protobuf:analysis_v2_java_proto
@io_bazel//src/main/protobuf:analysis_v2_java_proto_srcs
@io_bazel//src/main/protobuf:analysis_v2_proto
@io_bazel//src/main/protobuf:analysis_v2_py_proto
@io_bazel//src/main/protobuf:analysis_v2_py_proto_genproto
```
so `analysis.proto` appears to have been completely dropped.
But the docs still refer to analysis.proto (though the link target now points to analysis_v2.proto):
```
$ git grep analysis.proto
site/en/query/cquery.md:[src/main/protobuf/analysis.proto](https://github.com/bazelbuild/bazel/blob/master/src/main/protobuf/analysis_v2.proto){: .external}.
```

**Comment by gregestren** [comment]
Yep: https://github.com/bazelbuild/bazel/commit/d67dc88c5dd25edfad72173d2c85170370611725.

Prepped a fix for the cquery doc.
