### ISSUE TITLE
Put /usr/local/bin before /usr/bin in PATH for Python support

### ISSUE THREAD

**Issue by nikhilm** [bazelbuild/bazel#10557]
### Description of the problem / feature request:

macOS Catalina's system python3 trips the toolchain version check for unknown reasons. It would be nice if the brew/python.org python3 is preferred by changing `/usr/local/bin` to be first in the default PATH for actions.

This is partly a feature request, but I mainly want to document the issue and the workaround for others.

I believe it wouldn't  be the best idea to change the PATH order globally. Is it possible to have a python toolchain specific PATH?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

It is not possible to reliably reproduce this (we've had very few occurrences in our CI), but the gist is:
1. Create a py_binary
2. Have bazel use Python3
3. Try to run the binary on macOS Catalina

Occasionally it will fail with

```
Jan  9 06:42:24.592: Error occurred while attempting to use the default Python toolchain (@rules_python//python:autodetecting_toolchain).
Jan  9 06:42:24.592: Could not get interpreter version via '/usr/bin/python3 -V'
```
There are no other stderr/stdout logs relevant to this. 
Since Catalina, macOS ships with a python3 in /usr/bin.
The Python.org installer or homebrew python is installed  in /usr/local/bin.
In our project, setting `--action_env=PATH=/usr/local/bin:/bin:/usr/bin` to prefer this Python has generally had good results. I don't know what is wrong with the system Python to cause these failures.

### What operating system are you running Bazel on?

macOS 10.15

### What's the output of `bazel info release`?

release 1.0.1 (we cannot update to 1.2 just yet, but the code seems unchanged)

###  Have you found anything relevant by searching the web?

No

**Comment by keith** [comment]
FWIW preferring homebrew's python is considerably more risky IMO because users could have significantly different versions depending on when they installed it and when they updated homebrew's forumlae. I've said on other issues that I don't think `/usr/local/bin` should be included at all because of this risk (and we exec bazel with `PATH=/usr/bin:/bin` to ensure this.

**Comment by aiuto** [comment]
I agree with keith that using /usr/local/bin in any default is prone to problems.

It feels like the path to the python runtime that py_binary uses should be a property of the platform definition. Perhaps we need to define a distinct platform for Catalina OR for people who want to prefer homebrew.

**Comment by aiuto** [comment]
@brandjon might have a thought.

**Comment by brandjon** [comment]
> It feels like the path to the python runtime that py_binary uses should be a property of the platform definition.

Well, it's part of the Python toolchain definition, and the platform can be used to select appropriate toolchains based on constraints. The autodetecting toolchain is the toolchain of last resort. The preferred alternative is to define and register a toolchain pointing to the desired Python runtime.
