### ISSUE TITLE
Bazel CI: rules_jvm_external - Android instrumentation test example failing with Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#10550]
The failing test is [android_instrumentation_test](https://github.com/bazelbuild/rules_jvm_external/tree/master/examples/android_instrumentation_test)
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1344#880a086d-4c4b-4d4c-8910-b34301ae1054
```
(11:44:22) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/00ecb74aaf575e3792d5fc4fcd7fb5a6/external/android_test_support/tools/android/emulated_devices/generic_phone/BUILD.bazel:43:1: no such target '@androidsdk//:emulator_images_android_23_x86_qemu2_extra': target 'emulator_images_android_23_x86_qemu2_extra' not declared in package '' defined by /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/00ecb74aaf575e3792d5fc4fcd7fb5a6/external/androidsdk/BUILD.bazel and referenced by '@android_test_support//tools/android/emulated_devices/generic_phone:android_23_x86_qemu2_images'
```

A bisect shows 9694d5d628bf3afbe2a9b79c883ee9caf1715730 as the culprit
/cc @jin

**Comment by meteorcloudy** [comment]
Android Testing is failing with the same error in downstream
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1344#3a970b50-95fc-4917-be5a-3cce5340e9d9

**Comment by jin** [comment]
Confirmed fixed in tonight's downstream run https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1345

**Comment by meteorcloudy** [comment]
Thanks for the fix!

**Comment by meteorcloudy** [comment]
/cc @laurentlb 
We need to cherry-pick https://github.com/bazelbuild/bazel/commit/c94b1474b368dedf9f68f34fad90cc8664f2b0e0 for 2.1.0 to fix downstream.
