### ISSUE TITLE
bazel throws unrecoverable errors in flaky network environments

### ISSUE THREAD

**Issue by flokli** [bazelbuild/bazel#10568]
### Description of the problem / feature request:

We're using bazel with a remote test. On flaky network conditions, Bazel spits stacktraces and crashes, where it probably should just log a warning, and if it keeps failing, just try without the cache.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Unfortunately, I can't share the code, but we were running `bazel test //...`. It really seems to be related to flaky network, as this happens mostly on developer machines with bad connectivity, and we were able to eventually get things to build on these machines in the end, by just trying over and over again.

### What operating system are you running Bazel on?

NixOS 19.09

### What's the output of `bazel info release`?
release 0.29.0- (@non-git)

Built using nixpkgs from https://github.com/NixOS/nixpkgs/pull/69252, plus the following patches:
 - https://github.com/bazelbuild/bazel/commit/43855316fa35ffbef78fab7047cbea97a4151464.diff
 - https://github.com/bazelbuild/bazel/pull/8888.diff

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
See above

###  Have you found anything relevant by searching the web?
https://github.com/bazelbuild/bazel/issues/6170 has similar error messages, but this seems to be reproducible, and related to passing directories as inputs to `label_list` attributes

### Any other information, logs, or outputs that you want to share?
[log.txt](https://github.com/bazelbuild/bazel/files/4053866/log.txt)

**Comment by flokli** [comment]
@aiuto I don't understand the assignment. What's to be done for me here?

**Comment by philwo** [comment]
Error reporting was much improved in later versions of Bazel, so I'm closing this.
