### ISSUE TITLE
Bazel cc autoconfig does not support the default sanitizer blacklists in clang

### ISSUE THREAD

**Issue by nlopezgi** [bazelbuild/bazel#10561]
### Description of the problem / feature request:

With clang r407ac2eb5f136af5ddd213b8bcca176481ec5198 or above (see [here](https://github.com/GoogleCloudPlatform/layer-definitions/pull/674/files)) the compiler reports the blackilst file as an included file. However, Bazel cc autoconfig does not include this file in the builtin_include_directory_paths file. As a result of this, the following error is produced (with, e.g., msan enabled, building absail):
```
 ERROR: /workspace/external-src/absl/debugging/BUILD.bazel:105:1: undeclared inclusion(s) in rule '//absl/debugging:examine_stack':
this rule is missing dependency declarations for the following files included by 'absl/debugging/internal/examine_stack.cc':
'/usr/local/lib/clang/10.0.0/share/msan_blacklist.txt'
```

The current workaround is to use -fno-sanitize-blacklist (see [here](https://github.com/bazelbuild/bazel-toolchains/pull/795)). Ideally cc autoconfig would be able to add this directory (/usr/local/lib/clang/10.0.0/share) to the builtin_include_directory_paths file.

### Feature requests: what underlying problem are you trying to solve with this feature?

Sanitizer builds do not support use of blacklist file

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build Abseil on RBE with sanitizers, as exemplified on [this GCB build spec](https://github.com/bazelbuild/bazel-toolchains/blob/master/tests/rbe_external_project/abseil_msan.yaml).

### What operating system are you running Bazel on?

Any linux, building on RBE using the default clang toolchain using sanitizers.

### What's the output of `bazel info release`?

2.0.0

###  Have you found anything relevant by searching the web?

consulted with google C team experts (@ilya-biryukov) about the issue. His response was:
"I believe this is caused by a fix in the compiler. It did not report that it accessed those files before, so blaze/bazel did not detect a conflict there.
In fact, most of the time this does not affect compilation results, so it was not a big deal and probably never caused any problems.

In any case, we should add those files to the list of files that can be accessed by the compiler (to the list of system headers in the crosstool)."

**Comment by benjaminp** [comment]
This seems like it's the same as #10510.

**Comment by oquenchil** [comment]
Yes, it is the same as #10510. Thanks Benjamin. 

I'm still working on fixing this.
