### ISSUE TITLE
Bazel doesn't handle files that start with `bazel-`

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#10560]
Files starting with `bazel-` seem to cause problems when they are in the top level package.

Example:
```bash
$ ls
BUILD  WORKSPACE

$ cat BUILD
cc_library(
    name = "x",
    srcs = glob(["*.cc"]),
)

$ bazel build :x
# success

$ touch hello.cc
$ bazel build :x
# success

$ touch bazel-hello.cc
$ bazel build :x
gcc: error: bazel-hello.cc: No such file or directory
```

Workaround: moving the files in a subdirectory.

**Comment by phst** [comment]
The culprit is probably https://github.com/bazelbuild/bazel/blob/20b056ae8506e489933cf236b9401cddad90afac/src/main/java/com/google/devtools/build/lib/buildtool/SymlinkForest.java#L257-L258
