### ISSUE TITLE
March release

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1056]
Should be 0.2.1 (0.3 is almost there but we still needs some documentation for it).

We should cut the rc tomorrow, we have too many incompatibilities now.

/cc @kchodorow fyi

**Comment by tfarina** [comment]
Looks like Bazel 0.2.1-rc1 was made 4 days ago:
https://groups.google.com/d/msgid/bazel-discuss/265676298.299.1458593246235.JavaMail.jenkins%40jenkins-jenkins

**Comment by damienmg** [comment]
Canary is good but jenkins is red at HEAD due to infrastructure problem, delaying the release.

**Comment by damienmg** [comment]
Canary is good, Jenkins failures are because of incompatibilities from the rules or for tensorflow with developement binaries of Bazel, let push \o/

**Comment by damienmg** [comment]
Oops forgot to close this one :)
