### ISSUE TITLE
Bazel does not report details of the failed commands on windows.

### ISSUE THREAD

**Issue by Artem-B** [bazelbuild/bazel#10572]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:
Bazel does not report details of the failed commands on windows.. When compilation fails, bazel does not print any info about the failed command. --verbose_failures does not help.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
BUILD:
cc_library(
  name = "lib",
  srcs = ["lib.cc"],
)

lib.cc:
#error This file fails to compile

```

Output on Windows (no info about the failed command and its options, with or without --verbose_faqilures):
```
$ bazel200.exe build lib --verbose_failures
INFO: Invocation ID: 13dab351-628a-4c68-9628-e912a25f15ec
Loading: 
Loading: 0 packages loaded
Analyzing: target //:lib (0 packages loaded, 0 targets configured)
INFO: Analyzed target //:lib (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 3] [Scann] Compiling lib.cc
ERROR: C:/ktmpfs/repro/BUILD:1:1: C++ compilation of rule '//:lib' failed (Exit 2)
lib.cc(1): fatal error C1189: #error:  this file does not compile
Target //:lib failed to build
INFO: Elapsed time: 0.211s, Critical Path: 0.08s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

Compare with the output on Linux, which does print the failed command:
```
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:lib (13 packages loaded, 46 targets configured).
INFO: Found 1 target...
ERROR: /mnt/sda_crypt/tra/tf-win-break/BUILD:1:1: C++ compilation of rule '//:lib' failed (Exit 1) gcc failed: error executing command 
  (cd /usr/local/google/home/tra/work/.cache/bazel/_bazel_tra/5e7d1dac0bc55dad9def8e6cf6dbaef0/sandbox/linux-sandbox/1/execroot/__main__ && \
  exec env - \
    PATH=[....] \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/_objs/lib/lib.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/_objs/lib/lib.pic.o' -fPIC -iquote . -iquote bazel-out/k8-fastbuild/bin -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c lib.cc -o bazel-out/k8-fastbuild/bin/_objs/lib/lib.pic.o)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
lib.cc:1:2: error: #error this file fails to compile
 #error this file fails to compile
  ^~~~~
Target //:lib failed to build
INFO: Elapsed time: 4.561s, Critical Path: 0.10s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

```

NOTE: bazel on windows also prints the `FAILED:` line twice, for some reason.

### What operating system are you running Bazel on?

Windows Server 1809

### What's the output of `bazel info release`?

b2e80172 /tmpfs/repro > /tmpfs/bazel200.exe info release
INFO: Invocation ID: 6dd107dd-272e-4040-8c2e-e1a7061b1533
release 2.0.0

###  Have you found anything relevant by searching the web?

Nope. Discussed w/ @meteorcloudy

**Comment by meteorcloudy** [comment]
I did a bisect on this, the culprit turned out to be 08d691f40bbe8c6ed28a5ba22798f0cbee595fa7
@buchgr 
/cc @laszlocsomor

**Comment by meteorcloudy** [comment]
@laurentlb I think this is a serious bug that we need to cherry-pick a fix for the next release.

**Comment by meteorcloudy** [comment]
It turned out this is not a Windows only issue, it happens on all platform with `--spawn_strategy=local`, (which is default on Windows).
I can reproduce the same bug on Linux.

**Comment by laurentlb** [comment]
It looks like the bug is present since July. We normally cherry-pick only recent regressions.

**Comment by meteorcloudy** [comment]
This bug makes our users much harder to debug on CI, but the fact that no one reported it until now may suggest it didn't affect too many users. Anyway, it's the release manager's decision. ;)

**Comment by loeffel-io** [comment]
+1 (darwin)
