### ISSUE TITLE
a external workspace should occupy only one UI status line

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#10578]
Today (post e8102278c3700e0842e46b46cb9d1f91aecb62fb), when fetching an external workspace, the UI may have lines like this:
```
Fetching @some_external_workspace
/some/long/path: Extracting /some/long/path/some_external_workspace.tar.gz
```
These lines both pertain to the same external workspace, and in my opinion, they could be merged into something like this:
```
Fetching @some_external_workspace: extracting /some/long/path/some_external_workspace.tar.gz
```

To implement this, the `UiStateTracker` may have to have a stack of states for each executing repository rule.

**Comment by aehlig** [comment]
Semantically, these are two different status lines. The first is the [user-settable](https://github.com/bazelbuild/proposals/blob/master/designs/2018-10-29-external-repositories-reporting.md) status (via `ctx.report_progress`); some users found it useful to see the status set by them for the whole time till they set a new status. The second is the bazel's report on "network activity"; originally there, we only reported from which URLs we fetched and the number of bytes fetched so far (and these parallel reporting had been like that for quite a while). In e8102278c3700e0842e46b46cb9d1f91aecb62fb, we added archive extraction to the reported "network activity" as we had too many bug reports that incorrectly attributed the time the fetching of an external repository took to bazel calling out to the network when in reality bazel only unpacked a cached archive.

Now, making this network/unpacking activity hide the user-set fetch message would be a regression on the specified behavior there; so, before doing anything here I would like to know how many users would prefer which behavior.

**Comment by benjaminp** [comment]
> Semantically, these are two different status lines. The first is the [user-settable](https://github.com/bazelbuild/proposals/blob/master/designs/2018-10-29-external-repositories-reporting.md) status (via `ctx.report_progress`); some users found it useful to see the status set by them for the whole time till they set a new status. The second is the bazel's report on "network activity"; originally there, we only reported from which URLs we fetched and the number of bytes fetched so far (and these parallel reporting had been like that for quite a while). In [e810227](https://github.com/bazelbuild/bazel/commit/e8102278c3700e0842e46b46cb9d1f91aecb62fb), we added archive extraction to the reported "network activity" as we had too many bug reports that incorrectly attributed the time the fetching of an external repository took to bazel calling out to the network when in reality bazel only unpacked a cached archive.

I don't completely understand the semantic distinction. A single repository rule executes sequentially and thus can only be doing one thing at a time. The builtin HTTP repository rules don't set any interesting user status so display the uninformative "Fetch @some_rule` message for their entire execution. The downloading and extracting status also only says the name of the archive not the owning repository rule. Both of these problems would be fixed by collapsing the statuses onto one line.

> 
> Now, making this network/unpacking activity hide the user-set fetch message would be a regression on the specified behavior there; so, before doing anything here I would like to know how many users would prefer which behavior.

I suppose it's obvious which one I vote for. :)
