### ISSUE TITLE
add `label_kind` to `--output` for cquery

### ISSUE THREAD

**Issue by ahumesky** [bazelbuild/bazel#10574]
`bazel cquery` with `--output label_kind` gives

    ERROR: Invalid output format 'label_kind'. Valid values are: label, transitions, proto, textproto, build

**Comment by gregestren** [comment]
Contributions welcome. I expect this'd be easy by simply adding a new entry here:

https://github.com/bazelbuild/bazel/blob/605eaccabe2fed0a1d188d77baa2206f6346becd/src/main/java/com/google/devtools/build/lib/query2/cquery/ConfiguredTargetQueryEnvironment.java#L207-L209

i.e. clone and modify this:

https://github.com/bazelbuild/bazel/blob/966dc2328a8565103e514f898673fd8eb037b9c0/src/main/java/com/google/devtools/build/lib/query2/cquery/LabelAndConfigurationOutputFormatterCallback.java

**Comment by amanbora** [comment]
Hi, I would like to work on this issue, since I'm new to bazel i might need some guidance in the future.

**Comment by gregestren** [comment]
Hi Aman,

Happy to hear!. Feel free to reach out to me at any point and I'll offer help as I can (here or gregce@bazel.build).

**Comment by amanbora** [comment]
I have updated 'label' to 'label_kind' in [https://github.com/bazelbuild/bazel/blob/966dc2328a8565103e514f898673fd8eb037b9c0/src/main/java/com/google/devtools/build/lib/query2/cquery/LabelAndConfigurationOutputFormatterCallback.java](url),

and added a new entry in [https://github.com/bazelbuild/bazel/src/main/java/com/google/devtools/build/lib/query2/cquery/ConfiguredTargetQueryEnvironment.java](url)

**Comment by gregestren** [comment]
Great! I'll respond more on https://github.com/bazelbuild/bazel/pull/10632.
