### ISSUE TITLE
Incrementality on android targets with native tests

### ISSUE THREAD

**Issue by mrdomino** [bazelbuild/bazel#1057]
I have a few android targets that have native unit tests. All of their dependencies seem to be getting rebuilt every time I change them, and my guess is that this is because bazel currently considers a cc_library built for android as the same target as a cc_library built natively. Some way around this would be useful.

**Comment by ahumesky** [comment]
Do you have some way for us to reproduce the problem you're seeing? Or some example?

**Comment by dslomov** [comment]
Not really actionable pending clarifications from @mrdomino

**Comment by mrdomino** [comment]
Urf. I tried to get an example together and discovered that this wasn't the actual issue. Trying to figure out what's causing lots of third-party libraries to be rebuilt on ci.sh still.
