### ISSUE TITLE
Restrict propagation of an aspect to a dependency if it has a particular provider

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#10587]
Copying the comments from a discussion:

> Aspect propagation may unintentionally cross language boundaries. For example, say you have a genrule that produces output JavaScript files, which is then put in the srcs of a js_library. A JavaScript aspect will happily traverse the genrule.srcs attribute, even though it may contain targets that aren’t JavaScript at all. This is at best an annoyance (you must write the aspect in such a way that it refuses to operate on “invalid” targets) and at worst a potential bug (the aspect generates bogus output for these targets).

> This is AspectDefinition#getRequiredProviders(), which is not exposed to Starlark.

We may want to expose it.

**Comment by mai93** [comment]
`required_providers` is now exposed to Starlark in 1bca1bde7db06340559878a7d54b1f5698e7ddd6
