### ISSUE TITLE
Building for arm64_32 fails

### ISSUE THREAD

**Issue by AlessandroPatti** [bazelbuild/bazel#10582]
### Description of the problem / feature request:
Building a watch application for arm64_32 results in clang failing with 
`clang: error: invalid arch name '-arch <architecture>'`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Build any `watchos_application` target for arm64_32

### What operating system are you running Bazel on?
Macos 10.14.6

### What's the output of `bazel info release`?
release 2.0.0
###  Have you found anything relevant by searching the web?
Might be related to #7329

**Comment by tetromino** [comment]
Setting -arch to "<architecture>" for watchos_arm64_32 certainly seems to be the wrong thing to do. Thank you for the PR, I'll ping some potential reviewers.
