### ISSUE TITLE
bazel rc not take effect? 

### ISSUE THREAD

**Issue by zengyuxing007** [bazelbuild/bazel#10586]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

using bazel version : 0.24.1 

bazelrc defined:

`build --cxxopt -Wno-error=old-style-cast build --cxxopt -Wno-error=unused-private-field`

and using clang to compile ,but still reported a compile error,why ??

compile verbose failed information like this:

`foreign_cc/gperftools_build/include -isystem bazel-out/k8-dbg/genfiles/external/envoy/bazel/foreign_cc/nghttp2/include '-Wno-error=old-style-cast' '-Wno-error=unused-private-field' -Wall -Wextra -Werror -Wnon-virtual-dtor -Woverloaded-virtual -Wold-style-cast -Wvla '-std=c++14' -ggdb3 -DTCMALLOC -DENVOY_HANDLE_SIGNALS -DENVOY_OBJECT_TRACE_ON_DUMP -DENVOY_HOT_RESTART -DENVOY_GOOGLE_GRPC -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c source/extensions/filters/http/static_downgrade/static_downgrade_filter.cc -o bazel-out/k8-dbg/bin/source/extensions/filters/http/static_downgrade/_objs/static_downgrade_filter_lib/static_downgrade_filter.pic.o)
Execution platform: @bazel_tools//platforms:host_platform

Use --sandbox_debug to see verbose messages from the sandbox
In file included from source/extensions/filters/http/static_downgrade/static_downgrade_filter.cc:1:
bazel-out/k8-dbg/bin/source/extensions/filters/http/static_downgrade/_virtual_includes/static_downgrade_filter_lib/extensions/filters/http/static_downgrade/static_downgrade_filter.h:69:38: error: private field 'config_' is not used [-Werror,-Wunused-private-field]
  const StaticDowngradeCommonConfig *config_{nullptr};`

**Comment by zengyuxing007** [comment]
if i define copts under BUILD file like these:
`copts = [
        "-Wno-error=unused-private-field"
    ],`
that will be compiled successful....

**Comment by oquenchil** [comment]
I believe you need to specify each configuration option on its own line and also properly wrap the value of the option.

build --cxxopt="-Wno-error=old-style-cast"
build --cxxopt="-Wno-error=unused-private-field"

Note the equals sign I added and the quotes. It may also be that you need to use --copt instead of --cxxopt.

Please let me know if any of that works.
