### ISSUE TITLE
Build java rules failed with unsupported flag `-Xbootclasspath/p`

### ISSUE THREAD

**Issue by crowhou** [bazelbuild/bazel#10594]
### Description of the problem / feature request:

> ERROR: /private/var/tmp/_bazel_xxx/791f50d8fb4dd0e44201ce61f2acccfc/external/io_grpc_grpc_java/context/BUILD.bazel:1:1: Compiling Java headers external/io_grpc_grpc_java/context/libcontext-hjar.jar (4 source files) failed (Exit 1) java failed: error executing command external/remotejdk11_macos/bin/java -Xverify:none -Xbootclasspath/p:external/remote_java_tools_darwin/java_tools/javac-9+181-r4173-1.jar -jar ... (remaining 25 argument(s) skipped)
Use --sandbox_debug to see verbose messages from the sandbox
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
-Xbootclasspath/p is no longer a supported option.

### What operating system are you running Bazel on?

> Mac OS

### What's the output of `bazel info release`?

> release 2.0.0

### What's the output of `bazel info java-runtime`?

> OpenJDK Runtime Environment (build 11.0.2+7-LTS) by Azul Systems, Inc.

**Comment by comius** [comment]
What project were you building, what is the content of .bazelrc, in particular `--java_toolchain` option?
I would expect such error when using `*hostjdk8` over a JDK version > 8.

**Comment by aiuto** [comment]
closing for lack of action
