### ISSUE TITLE
Maven Mirrors fail to download as of 15th of January

### ISSUE THREAD

**Issue by mihaimaruseac** [bazelbuild/bazel#10595]
### Description of the problem / feature request:

As of January 15, 2020, requests via HTTP to Maven fail with `GET returned 501 HTTPS Required`

This causes all bazel builds that transitively download from Maven repositories (i.e, all?) to fail.

For example, see a TF failure at https://source.cloud.google.com/results/invocations/b15d98de-a35a-4020-8fdf-3d3978f2c401 (search for `step 5`)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`bazel build --nobuild //tensorflow/...` in TF repo.

###  Have you found anything relevant by searching the web?

https://support.sonatype.com/hc/en-us/articles/360041287334

### Any other information, logs, or outputs that you want to share?

The mirroring of the dependencies has to change from `http` to `https`.

**Comment by jin** [comment]
This is an upstream change that we've been aware of for a while, and have already implemented several mechanisms from Bazel 1.0 onwards:

* rules_jvm_external lets you switch repositories easily, with support for multiple mirrors.
* The native maven_jar rule has been removed in 2.0. From 1.0, maven_jar disallows using plain HTTP urls without checksums, both for security reasons and to encourage users to move to HTTPS.
* I am not aware of an arrangement for hosting a Maven mirror on the Bazel mirror.

Also see https://github.com/bazelbuild/bazel/issues/8607 for the list of mitigations from mid-2019.

**Comment by mihaimaruseac** [comment]
Should have opened this in `rules_closure` instead of in front-end of `bazel`.

As the dependency comes from `rules_closure`, I don't think the above mitigations work. In any case, https://github.com/bazelbuild/rules_closure/pull/455/files#diff-2e4ceb18bd69c42a94a1867209a48286R684-R685 (includes the mirroring setup) should fix this, as we have tested it with a patch locally.

**Comment by jin** [comment]
Sounds good, closing this for now.
