### ISSUE TITLE
linkopt for <cmath>

### ISSUE THREAD

**Issue by cnsgsz** [bazelbuild/bazel#1059]
in building a test for a library (the library has header files which includes <cmath> and uses std::log());

> INFO: Found 1 target...
> INFO: From Linking .../foo.pic.o: undefined reference to symbol 'logf@@GLIBC_2.2.5'
> //lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> ERROR: .../BUILD:7:1: Linking of rule '.../foo' failed: gcc failed: error executing command 
> 

> /usr/bin/gcc -o bazel-out/local_linux-fastbuild/bin/.../foo_test bazel-out/local_linux-fastbuild/bin/.../foo_test.pic.o -lstdc++ -B/usr/bin/ -pie -Wl,-z,relro,-z,now -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,-S)

it could be resolved by adding linkopt = ["-lm"] to the build rule for the library, but is it the right way to resolve the issue? why could bazel not automatically add the linkopt?

**Comment by damienmg** [comment]
Yes this is the right way to do it.

Bazel cannot adds it automatically because not everybody use libmath...
