### ISSUE TITLE
sh_binary cannot be in the WORKSPACE file (used by //external:test-shell)

### ISSUE THREAD

**Issue by boseabhishek** [bazelbuild/bazel#10608]
#10257 # Description of the problem / feature request:
Hello, I am trying to run `sh_binary` which is in  .bzl file inside a directory called hello and it looks like:
`
def test_shell(name):
    native.sh_binary(
        name = name,
        srcs = ["script.sh"],
    )

`

What I am trying is referring it from another projects WORKSPACE like below:
`
git_repository(
    name = "hello-repo",
    branch = "master",
    remote = "git@github.com:myorg/hello-repo.git",
)

load("@hello-repo/hello:shelltest.bzl", "test_shell")

test_shell(
    name = "test",
)
`
> But, I get the above error which is `sh_binary cannot be in the WORKSPACE file (used by //external:test-shell)`

### Feature requests: what underlying problem are you trying to solve with this feature?

> Run a shell so that I can perform something using a WORKSPACE file

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

> MacOS

### What's the output of `bazel info release`?

> Just like bazel build ...
`
ERROR: /Users/myname/projects/my-proj/WORKSPACE:58:1: Traceback (most recent call last):
        File "/Users/myname/projects/my-proj//WORKSPACE", line 58
                test_shell(name = "test")
        File "/private/var/tmp/_bazel_myname/3fd196aec6a1a3ada23d0601a6698c81/external/hello-repo/hello/shelltest.bzl", line 3, in test_shell
                native.sh_binary(name = name srcs = ["script..."])
sh_binary cannot be in the WORKSPACE file (used by //external:test)
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package 'external': Package 'external' contains errors
`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> bazel is installed using scripts from Bazel website not from source

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Didn't find anything relevant.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Can `sh_binary` not be used from WORKSPACE?
>
> If the files are large, upload as attachment or provide link.

**Comment by jin** [comment]
sh_binary is a regular rule, and thus can only be used from a BUILD file.
