### ISSUE TITLE
repository_rule implementation does not print anything

### ISSUE THREAD

**Issue by boseabhishek** [bazelbuild/bazel#10615]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> I am trying to write a very simple hello world repository_rule to examine how it works and I have put print, which doesn’t print at all when invoked from another WORKSPACE.

### Feature requests: what underlying problem are you trying to solve with this feature?

> Print something to see whether it’s working.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Just by putting a print inside an _impl fora repository_rule

### What operating system are you running Bazel on?

> MacOS

### What's the output of `bazel info release`?

> 

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> standard installation.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?
> none 
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by jin** [comment]
The repository rule does not get executed unless some target from your build depends on a target created by the repository rule. This is working as intended.
