### ISSUE TITLE
Closure sample from bazel website fails to build

### ISSUE THREAD

**Issue by domesticmouse** [bazelbuild/bazel#1061]
I'm attempting to build the sample app from the [Closure docs on the Bazel website](http://bazel.io/docs/be/closure.html), however I am hitting the following error:

```bash
$ bazel build //:hello
........
ERROR: /Users/brett/bazel-js-project/BUILD:23:1: every rule of type closure_stylesheet_library implicitly depends upon the target '//tools/build_rules/closure:closure_stylesheets', but this target could not be found because of: no such package 'tools/build_rules/closure': BUILD file not found on package path.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 70.385s
```

I've put my project up as a gist: https://gist.github.com/domesticmouse/f3016736399f6b951b6d

**Comment by damienmg** [comment]
Hi @domesticmouse,

Closure rules from the Bazel repositories are deprecated and will soon be moved, you can have a look at https://github.com/bazelbuild/rules_closure for the new rules.

I will close that bug, please file any problem you encounter with the new rules on the dedicated issue tracker. Thanks!
