### ISSUE TITLE
Many rule have string argument when they should be label

### ISSUE THREAD

**Issue by guibou** [bazelbuild/bazel#10617]
### Description of the problem / feature request:

Many rules have `string` argument for things which, from my point of view, must be `label`.

For example, `http_archive` contains a `patch_tool` argument, which is a `string` and can be filled with the path to a `patch` binary. However, I'm building my `patch` binary using an external bazel repository, so I don't know beforehand the path for my `patch` binary. If `patch_tool` was accepting a `label`, I may just set it to `@mypatch//:bin/patch` for example.

I already opened a bug report for some specific rules here: https://github.com/bazelbuild/bazel/issues/8438, but this bug report tries to be more general.

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm trying to have a fully reproducible build environment which does not depend on anything on the user system. To do that, I'm building / fetching everything in bazel, from simple tools such as `patch` to complex things such as CC toolchain. Unfortunately, a lot of rule in bazel expect `string` with the (absolute) path to utilities on the system, so that's technically non possible.

My current solution is to break a few bazel assumption and force my external repository rules to produce output in directories that I manage. Hence, I know beforehand the static path of my utilities.

The solution I'd like either:

- Allows `label` everywhere `string` are allowed, and simply replace them by the path to the `label`
- Allows `$(location)` (or similar invocation) in `string` argument for most rules.

### What operating system are you running Bazel on?

Linux, macos and windows.

### What's the output of `bazel info release`?

All bazel version are impacted.

###  Have you found anything relevant by searching the web?

no

**Comment by laurentlb** [comment]
Thanks for the feedback.
To clarify the request, I think it's mostly about repository functions.

In Starlark rules, I think the API is more consistent about the types.
