### ISSUE TITLE
Bazel 2.0 does not build itself on clearlinux

### ISSUE THREAD

**Issue by Meai** [bazelbuild/bazel#10624]
tested trunk as well, tested with a different --output_base as well, same result. Can you say what could be the cause?

> pc@mymachine~/workarea/test/bazel $ bazel build //src:bazel
> DEBUG: /home/pc/.cache/bazel/_bazel_pc/057958262ec626389ac6afcac66fcf94/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:9: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True 
> DEBUG: /home/pc/.cache/bazel/_bazel_pc/057958262ec626389ac6afcac66fcf94/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:9: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True 
> ERROR: infinite symlink expansion detected
> [start of symlink chain]
> /usr/include/c++/9/x86_64-generic-linux/32
> /usr/include/c++/9/x86_64-generic-linux
> [end of symlink chain]
> INFO: Call stack for the definition of repository 'remotejdk11_linux' which is a http_archive (rule definition at /home/pc/.cache/bazel/_bazel_pc/057958262ec626389ac6afcac66fcf94/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
>  - /home/pc/.cache/bazel/_bazel_pc/057958262ec626389ac6afcac66fcf94/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
>  - /DEFAULT.WORKSPACE.SUFFIX:216:1
> INFO: Call stack for the definition of repository 'openjdk_linux_minimal' which is a http_file (rule definition at /home/pc/.cache/bazel/_bazel_pc/057958262ec626389ac6afcac66fcf94/external/bazel_tools/tools/build_defs/repo/http.bzl:372:13):
>  - /home/pc/workarea/test/bazel/WORKSPACE:256:1
> ERROR: Analysis of target '//src:bazel' failed; build aborted: Analysis failed
> INFO: Elapsed time: 8.267s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (206 packages loaded, 9127 targets configured)
>

**Comment by philwo** [comment]
@Meai Sorry, I have no idea what might cause this. :/ Can you reproduce this with a recent Bazel version?
