### ISSUE TITLE
"Inconsistent filesystem operations" and sandboxing

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#1062]
This error message just popped up while using a Bazel at Github HEAD:

```
ERROR: /usr/local/google/home/lberki/bazel/github/WORKSPACE:24:1: no such package '': Inconsistent filesystem operations. readdir and stat disagree about whether /usr/local/google/home/lberki/bazel/github/bazel-github/bazel-sandbox/5153c58a-1d13-43b2-84b6-273da81f16d3-0/dev/fd/47 is a symlink. The results of the build are not guaranteed to be correct. You should probably run 'blaze clean' and investigate the filesystem inconsistency (likely due to filesytem updates concurrent with the build) and referenced by '//external:android_sdk_for_testing'.
```

I haven't looked into it very deeply, but my guess is that the sandbox leaves things around and then someone accesses them. although I don't immediately see who would read that directory aside from the sandbox...

**Comment by lberki** [comment]
@hermione521 @philwo

**Comment by lberki** [comment]
@kchodorow , any ideas where this operation might come from?

Note that in the general case, we can't be sure that the sandbox cleans up after itself, because we can `kill -9` everything at any time.

**Comment by kchodorow** [comment]
I have no idea where it's getting /dev/fd/47 from, I'd assume that's a sandbox setup thing.  I'm probably not the best person to look into that...

**Comment by lberki** [comment]
Aaaargh, I think I know. My guess is that the glob in the BUILD file in the root directory of the Bazel tree descends into the bazel-github directory.

**Comment by bsilver8192** [comment]
Is it maybe an outdated convenience symlink? I've seen similar issues from that.

As far as the actual error, /dev/fd/47 is just whatever file descriptor number 47 is. That switching between a directory and a file (or whatever) is almost expected.

**Comment by lberki** [comment]
@bsilver8192 : Yep, the fact that `/dev/fd/47` is not consistent is expected. It's a tad surprising, though, that it's accessible from under the output base.

I thought it's due to the `glob(["**"])` stanza in `/BUILD`, but it explicitly excludes `bazel-*/**`, so it shouldn't match. That said, `bazel query //:all-targets` returns a lot of stuff under the `.git` directory, which is also excluded in theory.

**Comment by lberki** [comment]
We apparently have a filegroup called `git` for whatever reason, which is an explanation for the `.git` files. Which means that the reason why we stat that file is still a mystery.

**Comment by philwo** [comment]
Closing this bug as obsolete. I have never seen other reports about this and lots of changes happened to Bazel and the sandbox between when this happened and now. Please feel free to re-open if this happens again.

**Comment by keith** [comment]
I have seen this with directories and files that we have gitignored, and may be removed before or during a build. Here's an example error when doing a query:

```
ERROR: /private/var/tmp/_bazel_iosci/3482a4e7aa2c5687a4da57f2a733a45e/external/bazel_tools/tools/jdk/BUILD:178:1: no such package '@local_jdk//': Inconsistent filesystem operations. readdir and stat disagree about whether /private/var/tmp/_bazel_iosci/3482a4e7aa2c5687a4da57f2a733a45e/external/local_jdk/project_generated.json is a symlink. The results of the build are not guaranteed to be correct. You should probably run 'bazel clean' and investigate the filesystem inconsistency (likely due to filesystem updates concurrent with the build) and referenced by '@bazel_tools//tools/jdk:jdk'
--
  | ERROR: /private/var/tmp/_bazel_iosci/3482a4e7aa2c5687a4da57f2a733a45e/external/bazel_tools/tools/jdk/BUILD:178:1: no such package '@local_jdk//': error globbing [bin/**] - [**/*%*/**]: com.google.devtools.build.lib.actions.InconsistentFilesystemException: Inconsistent filesystem operations. readdir and stat disagree about whether /private/var/tmp/_bazel_iosci/3482a4e7aa2c5687a4da57f2a733a45e/external/local_jdk/project_generated.json is a symlink. The results of the build are not guaranteed to be correct. You should probably run 'bazel clean' and investigate the filesystem inconsistency (likely due to filesystem updates concurrent with the build) and referenced by '@bazel_tools//tools/jdk:jdk'
  | ERROR: Evaluation of subquery "deps(//Modules/...)" failed (did you want to use --keep_going?): errors were encountered while computing transitive closure
```

This has happened after a `git clean -fdx` which removes this gitignored file, but possibly there isn't a `bazel clean` in between those

**Comment by nikoargo** [comment]
I am also seeing this, on 0.22.0:
```
/home/user/.cache/bazel/_bazel_user/933c2f549343e099e3a6911b282cb71c/external/bazel_tools/tools/jdk/BUILD:178:1: no such package '@local_jdk//': Inconsistent filesystem operations. readdir and stat disagree about whether /home/user/.cache/bazel/_bazel_user/933c2f549343e099e3a6911b282cb71c/external/local_jdk/BUILD is a symlink. The results of the build are not guaranteed to be correct. You should probably run 'bazel clean' and investigate the filesystem inconsistency (likely due to filesystem updates concurrent with the build) and referenced by '@bazel_tools//tools/jdk:jdk'
```
(The same error as above, but without the second two error lines.)

Just re-running the build command works the second time. The error happens regularly but very rarely.
The only thing maybe unusual about my setup is that the build happens inside of a Docker container.

**Comment by keith** [comment]
@philwo should we re-open this one or should we create a new issue?
