### ISSUE TITLE
`repository_ctx.which` can be used without declaring `PATH` in `environ`

### ISSUE THREAD

**Issue by uri-canva** [bazelbuild/bazel#10627]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

It is very easy to use `repository_ctx.which` an a `repository_rule` without declaring the `PATH` environment variable as a dependency using `environ`. If the resulting path is written to the external repository, for example by generating a `BUILD` file, the external repository will refer to a stale path when the `PATH` environment variable is changed.

See https://github.com/bazelbuild/rules_docker/pull/1391 for example.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Create a repository rule that uses `repository_ctx.which` to save the path to a binary to a generated `BUILD` file, for example `repository_ctx.which("bash")`.
2. Execute the repository rule with bazel passing in a `PATH` with that binary, for example `PATH=/usr/bin bazel build @repository_rule_test//:test`.
3. Verify the path to the binary has been saved to the `BUILD` file, for example `cat $(bazel info output_base)/external/repository_rule_test/BUILD`.
4. Execute the repository rule with bazel passing a `PATH` with a different binary, for example `PATH=/usr/local/bin bazel build @repository_rule_test//:test`.
5. Verify the path to the binary is still the previous one, instead of the new one, for example `cat $(bazel info output_base)/external/repository_rule_test/BUILD`.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 2.0.0- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Built with nix at this commit: https://github.com/NixOS/nixpkgs/blob/5f6df74f66246a2eb198b0bc3fe1f7d2dff57062/pkgs/development/tools/build-managers/bazel/default.nix

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

No.

**Comment by espindola** [comment]
I just hit this with cc_toolchain, which uses repository_ctx.which and therefore PATH to find the default system compiler. It is easy to work around by adding CC to action_env, but a nasty surprise anyway.
