### ISSUE TITLE
Unclear error in remote builds when authentication hasn't been properly set up

### ISSUE THREAD

**Issue by ebrevdo** [bazelbuild/bazel#10626]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Bazel errors out with the opaque message

```
ERROR: Error initializing RemoteModule
```

When performing a remote build, if I haven't set up authentication properly.  In particular, in my case I needed to run:

```
gcloud auth application-default login
```

to set up a default application auth, before I was able to progress in my testing.
### What operating system are you running Bazel on?

linux
### What's the output of `bazel info release`?

release 1.2.1
###  Have you found anything relevant by searching the web?

some details on how to get verbose logging out of the bazel build, but nothing that worked.

**Comment by philwo** [comment]
Pretty sure this is fixed by now, otherwise please comment.
