### ISSUE TITLE
Bazel creates non-compliant classpath jar

### ISSUE THREAD

**Issue by rivashin** [bazelbuild/bazel#10620]
Paths in the `Class-Path` attribute of `MANIFEST.MF` should be URL-encoded.
Currently, bazel only encodes spaces: https://github.com/bazelbuild/bazel/blob/912e822cd14710b2ebe8c7484c682d627f2906cb/src/tools/launcher/java_launcher.cc#L152

It should encode all other characters too, e.g. `%` - which is a valid character for a filename - should be replaced with `%25`. If path is not encoded correctly then Java will not find the jar and will silently ignore it, resulting in a puzzling NoClassDefFoundError.

Coursier generates paths with `%` when username/password or port is specified as part of maven repository URL: `cache/v1/https/username%40server.com%3a8080/foo.jar`. As a result, any java project built with bazel & jvm_rules_external will experience this issue when the classpath gets long enough.

See [this small example](https://github.com/rivashin/jar-classpath-bug) reproducing the issue.

**Comment by meteorcloudy** [comment]
Thanks for reporting this, I will look into this

**Comment by rivashin** [comment]
Any progress on this?
And why is it tagged with windows-team? This affects all platforms.

**Comment by meteorcloudy** [comment]
@rivashin Sorry, I currently don't have any bandwidth to look into this. But I wound very much like to review the change if you can contribute to a fix!

**Comment by philwo** [comment]
@mai93 maybe you want to look into this. :)

**Comment by Bencodes** [comment]
I just put up a PR that updates the other Java launcher path https://github.com/bazelbuild/bazel/pull/12946
