### ISSUE TITLE
Multiple aspects generating `CcInfo` generate clashing Middlemen actions

### ISSUE THREAD

**Issue by RNabel** [bazelbuild/bazel#10623]
### Description of the problem / feature request:

When defining two aspects which attach to the same target AND both generate and compile and link actions + return the `CcInfo` provider, the resulting Middlemen actions have conflicting file names and the build fails.

### Feature requests: what underlying problem are you trying to solve with this feature?

When expanding the cc actions for compilation/linking, Bazel sets the output filename of the Middlemen action(s) to be a function of the target name + the purpose (which is always `null`). Since the target is identical for both aspects, the resulting filenames conflict.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Minimal case: 
1. Create an aspect with a dummy code generator which attaches to a `proto_library` (e.g. `@com_google_protobuf//:descriptor_proto`).
0. Create a BUILD file
0. Add a target of type `cc_proto_library` and one of the custom aspect pointing to the same `proto_library`.
0. Compile both at the same time. If compiled in two Bazel runs, the build succeeds.

Observe error of the type (when attaching to `proto_library` target `@com_google_protobuf//:descriptor_proto`:
```
ERROR: file '_middlemen/@com_Ugoogle_Uprotobuf_S_S_Cdescriptor_Uproto-null' is generated by these conflicting actions:
Label: @com_google_protobuf//:descriptor_proto
RuleClass: proto_library rule
Configuration: 259377db41a8b93600f7738476a1b4d6f59dca22304658739c5ef52d71485166
Mnemonic: Middleman
Action key: 114c0908496ae0f5cd31a9b029883743ebd89b5f4f11e04ea938ca7513cac572
Progress message: (null)
PrimaryInput: File:[[<execution_root>]bazel-out/k8-gcc-opt/internal]_middlemen/<redacted: a dependency>-null, File:[[<execution_root>]bazel-out/k8-gcc-opt/internal]_middlemen/@com_Ugoogle_Uprotobuf_S_S_Cprotobuf-null
PrimaryOutput: File:[[<execution_root>]bazel-out/k8-gcc-opt/internal]_middlemen/@com_Ugoogle_Uprotobuf_S_S_Cdescriptor_Uproto-null
ERROR: com.google.devtools.build.lib.actions.MutableActionGraph$ActionConflictException: for _middlemen/@com_Ugoogle_Uprotobuf_S_S_Cdescriptor_Uproto-null, previous action: null for @com_google_protobuf//:descriptor_proto, attempted action: null for @com_google_protobuf//:descriptor_proto
```

### What operating system are you running Bazel on?

All of them.

### What's the output of `bazel info release`?

2.0.0

###  Have you found anything relevant by searching the web?

It can be seen above that the `purpose` for both actions is `null`. It appears possible to set it [here](https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/cpp/CcCompilationHelper.java;l=1110?q=middlemen&ss=bazel), but this is not available in Starlark (AFAICT).

A separate avenue of disambiguation would be incorporating the name of the aspect into the target name (i.e. modifying the mangled name of the target instead of changing the purpose). 

Happy to help out with this, just let me know which approach is best / if this is in the works already.

cc @hlopko (we discussed this issue over Slack ~6 months ago, but slack has deleted the message since then).

**Comment by oquenchil** [comment]
Hey Robin,

would you mind providing a minimal repro code example with BUILD and bzl files? I can then take a look, if it's just about setting the purpose we can fix that quickly.

**Comment by oquenchil** [comment]
Closing without repro, please re-open if this bug still exists.
