### ISSUE TITLE
Allow using netrc for grpc remote cache and remote executor endpoints

### ISSUE THREAD

**Issue by sitaktif** [bazelbuild/bazel#10636]
### Feature request:

Bazel supports netrc for HTTP endpoints. This change is to suggest supporting netrc for GRPC ones. 

Using netrc is a common way to configure auth for endpoints and is supported by most applications.

Bazel already supports netrc for HTTP endpoints and extending this to GRPC would allow using the same mechanism for grpc remote execution/caching instead of splitting a configuration into netrc (for HTTP) and something else (command line argument, bazelrc, ...).

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/7469
https://github.com/bazelbuild/bazel/issues/7770

**Comment by coeuvre** [comment]
Implemented in #12130, can you please have a try?

**Comment by coeuvre** [comment]
Closing. Feel free to reopen or create another issue if the implementation doesn't work for you.

**Comment by sitaktif** [comment]
Thanks @coeuvre, and sorry I haven't taken the time to test it yet but I do intend to. I'll chime back in either way.
