### ISSUE TITLE
Colored output not working on flag errors

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/bazel#10650]
This is something I've been observing for quite awhile already and still happens with Bazel 2.0.0.

Providing an invalid flag causes Bazel to abort the build as you might expect, but any coloring of the output doesn't work.

The simplest reproduction is to run `bazel build --config=foo` on Bazel's own source tree, which results in:

```
cherry:~/os/bazel> bazel build --config=foo
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=155
INFO: Reading rc options for 'build' from /Users/jmmv/os/bazel/.bazelrc:
  'build' options: --android_aapt=aapt2
INFO: Reading rc options for 'build' from /Users/jmmv/.bazelrc:
  'build' options: -c opt --nostamp
ERROR: Config value foo is not defined in any .rc file
```

I'd expect the `INFO:` and `ERROR:` line prefixes to be colored as usual, but the whole output has no colors.

I do not think this is specific to `--config=foo` because it seems to happen with any other kind of flag error. For example, the following results in the same uncolored behavior:

```
cherry:~/os/bazel> bazel build --jobs=foo  
ERROR: While parsing option --jobs=foo: Parameter 'foo' does not follow correct syntax. This flag takes an integer, or a keyword ("auto", "HOST_CPUS", "HOST_RAM"), optionally followed by an operation ([-|*]<float>) eg. "auto", "HOST_CPUS*.5".
```

**Comment by benjaminp** [comment]
Those errors come from the client, which isn't as smart as the server about console output.

**Comment by jmmv** [comment]
I don't think so. All of the messages pasted above come from the server, *including* `Config value foo is not defined in any .rc file`. See `BlazeOptionHandler.java`. And the failure for `--jobs` cannot come from the client because the client doesn't know about that flag at all.

Note that when the server prints the `Reading rc options for`... messages and similar during a successful build, those are printed with colors. But when there is an error, they are not.

**Comment by benjaminp** [comment]
Errr, right you are. The actual problem seems to be option parsing errors are always replayed onto unsophisticated `PrintingEventHandler` rather than setting up the fancy terminal (which requires having the options parsed).
