### ISSUE TITLE
Debugger breakpoints do not respect file path rules by platform

### ISSUE THREAD

**Issue by JayBazuzi** [bazelbuild/bazel#10654]
### Description of the problem / feature request:

Breakpoints don't account for file canonicalization across platforms.

For example, see https://github.com/bazelbuild/vscode-bazel/issues/167#issuecomment-578262179.

In [ThreadHandler.java#hasBreakpointMatchedAtLocation()](https://github.com/bazelbuild/bazel/blob/295274937ff7eef605c4dcebe1a8a50196ec7670/src/main/java/com/google/devtools/build/lib/skylarkdebug/server/ThreadHandler.java#L365) I see this lookup:

```
    SkylarkDebuggingProtos.Breakpoint breakpoint = breakpoints.get(locationProto);
```

Which does an exact match instead of matching by the platform's path equivalence rules.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

0. Wait for a fix for https://github.com/bazelbuild/vscode-bazel/issues/176 (or fix it yourself)
1. On Windows install vscode-bazel in VSCode
2. Set breakpoints in local .bzl files.
3. "Build Target with Starlark Debugger" on a target.

#### Result:

The breakpoint is not hit. 

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

`release 2.0.0`

###  Have you found anything relevant by searching the web?

- [Java's Files.isSameFile](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#isSameFile(java.nio.file.Path,%20java.nio.file.Path)) Maybe use this to match the keys in the `breakpoints` map.

### Any other information, logs, or outputs that you want to share?

I have been able to work around this by modifying vscode-bazel to covert file paths from `\` to `/` and correct the case of paths.

**Comment by laurentlb** [comment]
Thanks for the detailed report.
Feel free to send a PR.
