### ISSUE TITLE
Changing clang compiler version causes build failures

### ISSUE THREAD

**Issue by xykivo** [bazelbuild/bazel#10656]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Trying to build a C++ target after updating the clang compiler causes Bazel build errors - missing header file dependencies on platform specific headers.
this rule is missing dependency declarations for the following files included by 'some/cpp/src/source_file.cc':
  '/usr/lib/clang/9.0.0/include/stddef.h'
  '/usr/lib/clang/9.0.0/include/__stddef_max_align_t.h'
  '/usr/lib/clang/9.0.0/include/stdarg.h'
  '/usr/lib/clang/9.0.0/include/stdint.h'

Only by running bazel clean --expunge can the issue be corrected.

### Feature requests: what underlying problem are you trying to solve with this feature?

When the C++ compiler changes, the build system should detect any changes to platform header dependencies, and rebuild any dependent targets.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Build a C++ target using clang compiler version x.
2. Install a newer clang compiler version (y > x)
3. Make a change to a source file
4. Build the C++ target again using compiler y

### What operating system are you running Bazel on?

Ubuntu 18.04 & Ubuntu 19.10

### What's the output of `bazel info release`?

release 2.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

NA

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

NA

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

NA

**Comment by jin** [comment]
The C++ toolchain compiler is configured using a repository rule that looks at the system and generates a toolchain. `bazel sync --configure` forcefully re-runs the configure-like repository rules, so you don't need to clean and expunge. The repository rules currently do not automatically rerun even if the underlying files have changed (unlike regular rules).

**Comment by xykivo** [comment]
Thanks - the solution above works, but I still think that updates to local tools should be automatically detected, and cause the same behavior as bazel sync --configure as part of the build.

**Comment by oquenchil** [comment]
Closing this since jin's solution appears to have worked.

**Comment by shahms** [comment]
While the manual process works (if you know about it), it seems like it should be possible for bazel to detect changes in the compiler and re-run the relevant repository rules automatically.
