### ISSUE TITLE
CC=clang bazel build not working

### ISSUE THREAD

**Issue by elbaro** [bazelbuild/bazel#10659]
### Description of the problem / feature request:

```sh
CC=clang CXX=clang++ bazel build

ERROR: /home/../BUILD:2:1: undeclared inclusion(s) in rule '@...':
this rule is missing dependency declarations for the following files included by '../..cc':
  '/usr/include/errno.h'
  '/usr/include/features.h'
  '/usr/include/stdc-predef.h'
  '/usr/include/sys/cdefs.h'
  '/usr/include/bits/wordsize.h'
  ...

❯ which clang
/home/user/miniconda3/envs/my_env/bin/clang
```

### Feature requests: what underlying problem are you trying to solve with this feature?

Using clang

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Install gcc + clang with system package manager
2. Install miniconda + gcc + clang
3. activate conda env
4. `CC=clang CXX=clang++ bazel build ..`

### What operating system are you running Bazel on?
arch. I can produce with a simple Dockerfile from the base archlinux image.

### What's the output of `bazel info release`?
```
❯ bazel info release                        
ERROR: The 'info' command is only supported from within a workspace (below a directory having a WORKSPACE file).
See documentation at https://docs.bazel.build/versions/master/build-ref.html#workspace

❯ bazel info release
release 2.0.0- (@non-git)
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

arch system package

**Comment by oquenchil** [comment]
Did this ever work? When did it stop working?

**Comment by elbaro** [comment]
Did you try the above steps?
The key is having both the system (latest) gcc/clang + conda clang.

**Comment by elbaro** [comment]
Can reproduce in manjaro, arch, cent7, cent8.
