### ISSUE TITLE
BAZEL_VS environment variable does not work

### ISSUE THREAD

**Issue by jiandingzhe** [bazelbuild/bazel#10668]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

I'm using bazel 2.0.0 with VS Code bazel plugin. I have set `BAZEL_VS` env variable to `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools` globally. However, when I build a target in VS Code (clicking on *build target* from right-click menu in *BAZEL BUILD TARGETS* sidebar), it failed to probe compiler with following error logs:

```
ERROR: An error occurred during the fetch of repository 'local_config_cc':
   Traceback (most recent call last):
        File "C:/users/yangxi/_bazel_yangxi/y7qzzhw6/external/bazel_tools/tools/cpp/cc_configure.bzl", line 120                configure_windows_toolchain(<1 more arguments>)
        File "C:/users/yangxi/_bazel_yangxi/y7qzzhw6/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", 
line 690, in configure_windows_toolchain
                _get_msvc_vars(repository_ctx, <1 more arguments>)
        File "C:/users/yangxi/_bazel_yangxi/y7qzzhw6/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", 
line 535, in _get_msvc_vars
                setup_vc_env_vars(<2 more arguments>)
        File "C:/users/yangxi/_bazel_yangxi/y7qzzhw6/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", 
line 318, in setup_vc_env_vars
                _check_env_vars(env_map, cmd, <1 more arguments>)
        File "C:/users/yangxi/_bazel_yangxi/y7qzzhw6/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", 
line 324, in _check_env_vars
                auto_configure_fail(<1 more arguments>)
        File "C:/users/yangxi/_bazel_yangxi/y7qzzhw6/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, in auto_configure_fail
                fail(<1 more arguments>)

Auto-Configuration Error: Setting up VC environment variables failed, INCLUDE is not set by the following command:
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\\VCVARSALL.BAT" amd64
```

It seems the specified version of VS is not used. Instead it is still using VS 2015.

At current, I could only build targets inside *Developer Command Prompt for VS 2017*, which have set up many stuffs.

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

`release 2.0.0`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by laszlocsomor** [comment]
This might be fixed by https://github.com/bazelbuild/bazel/issues/10772.

As a workaround, see https://github.com/bazelbuild/bazel/issues/10772#issuecomment-585608398

**Comment by laszlocsomor** [comment]
Could you set `CC_CONFIGURE_DEBUG=1` globally and try again?

That'll tell Bazel to log more during C++ toolchain autoconfiguration, hopefully revealing why `BAZEL_VS` was ignored.

**Comment by philwo** [comment]
We assume that this is fixed, but @mai93 will try to reproduce to make sure. :)

**Comment by mai93** [comment]
I tried it and I think it is fixed, I will close it.
