### ISSUE TITLE
Unable to use "add-exports" option with java toolchain

### ISSUE THREAD

**Issue by unoexperto** [bazelbuild/bazel#10672]
I'm on bazel 2.0.0 and I'm trying to adopt my Java project to Sun JDK 13.

I have following options in my `.bazelrc`

```
build --javacopt="--add-exports java.base/com.sun.org.apache.xerces.internal.parsers=ALL-UNNAMED"
build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java11
build --java_toolchain=@bazel_tools//tools/jdk:toolchain_java11
```

I also tried

```
build --javacopt="--add-exports java.base/com.sun.org.apache.xerces.internal.parsers=ALL-UNNAMED -g -source 11 -target 11"
build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla
build --java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla
```

On build I get following error

```
java.lang.IllegalStateException: error: option --add-exports not allowed with target 1.7
	at jdk.compiler/com.sun.tools.javac.main.Arguments.reportDiag(Arguments.java:895)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.lambda$validate$3(Arguments.java:599)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
```

Why does it think I've set target 1.7 if I explicitly specified 11 ?

**Comment by avshenuk** [comment]
Hey guys,

Any updates on this one?

As far as I understand, this comes from the fact that Protobuf compiles with source and target Java 7: https://github.com/protocolbuffers/protobuf/blob/v3.11.0/BUILD#L657

**Comment by comius** [comment]
Unable to reproduce with given information on bazel 3.7.0. Dependency on that Protobuf would cause an exception like this, but newer versions of Protobuf don't seem to set javacopts.

There is a mechanism to set `javacopts` per package. See https://github.com/bazelbuild/bazel/issues/3427#issuecomment-367519584

**Comment by ckolli5** [comment]
Hey @unoexperto, can you please confirm if the mechanism provided in this [comment](https://github.com/bazelbuild/bazel/issues/10672#issuecomment-731628455) solved your issue? Thanks!

**Comment by unoexperto** [comment]
@comius Unfortunately I'm unable to confirm. I'm no longer at that company and ever since reject offers from companies that use Bazel.
