### ISSUE TITLE
Add support and rules for Python AppEngine

### ISSUE THREAD

**Issue by coptic-bola** [bazelbuild/bazel#1067]
I am trying to a build a python backend and using bazel as my build system but it has no support for Python App Engine like it has for Java. Is there a way to extend the current rule or build a new one to support Python?

**Comment by damienmg** [comment]
Hi, we don't plan to do it soon (though it is not really hard). I'll try to find back the code I used for my personal project.

**Comment by coptic-bola** [comment]
Sounds good. If you don't have time to clean up the code you used on previous projects, feel free to send it to me and I can make a PR after cleaning it up.

**Comment by kchodorow** [comment]
It would be good to add to https://github.com/bazelbuild/rules_appengine, if anyone does work on it.

**Comment by damienmg** [comment]
Here is my custom workspace file:
```
new_http_archive(
   name = "google_appengine_sdk_python",
   url = "https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.30.zip",
   sha256 = "d908f031672f8a95da0cc9230253a9985cfd57f6721d89606ccea21c8e00b471",
   build_file = "appengine.BUILD",
   strip_prefix = "google_appengine",
)
```

appengine.BUILD:
```
$ cat appengine.BUILD 

[genrule(
    name = "yaml-srcs-%s" % f.rsplit("/", 1)[1],
    srcs = [f],
    outs = ["yaml/%s" % f.rsplit("/", 1)[1]],
    cmd = "cp $< $@",
) for f in glob(["lib/yaml/lib/yaml/*.py"])]

py_library(
    name = "appengine-yaml",
    srcs = ["yaml/%s" % f.rsplit("/", 1)[1] for f in glob(["lib/yaml/lib/yaml/*.py"])],
)

py_library(
    name = "appengine",
    srcs = glob(["google/**/*.py"]),
    deps = [":appengine-yaml"],
    visibility = ["//visibility:public"],
)
```

And then my BUILD file add dependency to ["@google_appengine_sdk_python//:appengine"].

It's very custom and just works for compilation and tests. Making a full support shouldn't be hard though

**Comment by damienmg** [comment]
This is transferred to bazelbuild/rules_appengine#10
