### ISSUE TITLE
Persistence of execroot symlinks between build/run invocations

### ISSUE THREAD

**Issue by kastiglione** [bazelbuild/bazel#10680]
### Description of the problem / feature request:

We have recently noticed that symlinks in the execroot get cleared and reestablished to only the symlinks that are required for a given build. For example, building an iOS app followed by `bazel run` of some tool will result in all the removal of most or all of symlinks used for building the app.

For iOS, some of these paths can be embedded in the final binary (for debugging purposes), and so by calling `bazel run`, we inadvertently broke debugging. In our case, those paths were paths that are within our workspace, and so are available at their real paths.

Note that this isn't a problem for build outputs, only non-generated source inputs from the workspace. The paths and contents of `bazel-out` in the execroot do stay intact.

### Feature requests: what underlying problem are you trying to solve with this feature?

We have some precompiled frameworks in our workspace, and for debug builds, those files are accessed by the debugger. But when calling `bazel run`, those symlink paths are removed.

Ideally, a build should only setup or teardown symlinks for files that are used for a build. Other symlinks, preexisting ones especially, should be left intact.
 
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a workspace with two independent targets. Structure it as two source directories (two packages), each with a targets. Build one target, look at the contents of execroot, then build the other target, and it will show only symlinks to the subset of the build graph used in the build. For example:

```bash
% ls a b
a:
BUILD	a.c
b:
BUILD	b.c
% bazel build //a:a
# ...
% ls bazel-tmpproj
a		bazel-out	external
% bazel build //b:b    
# ...
% ls bazel-tmpproj
b		bazel-out	external
```

This shows that the symlinks from the first build are removed.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 2.0.0

**Comment by meteorcloudy** [comment]
> Create a workspace with two independent targets.

Why do you need `//a:a` for debugging when running `bazel run //b:b` if `//b:b` doesn't depend on `//a:a` at all? Can you somehow add the proper dependency?

**Comment by kastiglione** [comment]
In this case we're running a tool that consumes Bazel build output: the execution log proto. Would there be a way to model that, I presume no.

**Comment by tetromino** [comment]
We have [ExecRootPreparedEvent](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/buildtool/buildevent/ExecRootPreparedEvent.java) which is fired when the symlink forest is planted.

I'm thinking if we can add a flag to catch this event and replant the forest in some other (IDE-specific?) directory, optionally merging it with whatever forest that directory already contains.

(We already use that event for a somewhat similar purpose in Blaze internally.)

This would allow us to avoid changing existing execution root semantics.

**Comment by philwo** [comment]
I think this belongs more to the team-Core or team-Bazel as it's about fundamental semantics of our execroot.

**Comment by janakdr** [comment]
We're actually more interested in not staging symlinks in the execroot at all. I know that there are use cases for these symlinks, but our preference would be to teach debuggers, etc. to read directly from the source root, rather than via the execroot, which is half magic half hack.
