### ISSUE TITLE
.sh installer requirement : java 9 dont use rt.jar anymore

### ISSUE THREAD

**Issue by mikefaille** [bazelbuild/bazel#1068]
I'm using Opensuse Tumbleweed fully updated (rolling update distro) with Java 9 as default jvm (configured using JAVA_HOME). Refer to http://openjdk.java.net/jeps/220 : Removed: rt.jar and tools.jar.

```
sudo ./bazel-0.2.0-installer-linux-x86_64.sh 
Uncompressing......Extracting Bazel installation...
Problem with java installation: couldn't find/access rt.jar in /usr/lib64/jvm/java-1.9.0-openjdk-1.9.0
```

**Comment by mikefaille** [comment]
This error come from here : https://github.com/bazelbuild/bazel/blob/e5e3e9193a457ace9043bf70ff0253333c3435e5/src/main/cpp/blaze_startup_options.cc#L120

**Comment by damienmg** [comment]
Hello,

this is a known issue, see #428, unfortunately, we needs various change in our Java support to be able to run using a JRE 9. The java people at Google works on it but it will take some time.

In the time being, the compiler used by Bazel can actually handle Java 9 code but needs a JRE 8 to run.

Closing as duplucate of #428
