### ISSUE TITLE
 Bazel Examples failing with Bazel 2.1 rc

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#10697]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1373#_

```
(08:51:28) ERROR: An error occurred during the fetch of repository 'javax_servlet_api':
--
  | java.io.IOException: Error downloading [http://central.maven.org/maven2/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar] to D:/b/qadtosjt/external/javax_servlet_api/javax.servlet-api-3.1.0.jar: GET returned 501 HTTPS Required
```

**Comment by davido** [comment]
@laurentlb This doesn't seem to be a Bazel specific failure. Maven Central turned off HTTP access. It must be HTTPS now: [1]. See also this related issue in Gerrit: [2] and the fix: [3].

[1] https://blog.sonatype.com/central-repository-moving-to-https
[2] https://crbug.com/gerrit/12171
[3] https://gerrit-review.googlesource.com/c/gerrit/+/250502

**Comment by laurentlb** [comment]
Thanks @davido!

Closing this issue in favor of https://github.com/bazelbuild/examples/issues/144
