### ISSUE TITLE
java_library: Support non standard java source roots (other than java, javatests, src and testsrc)

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#10692]
It turns out, that if the Bazel package starts with non standard name (other than "src", "java", "javatests" and "testsrc") the content of created "libfoo-src.jar" artifact is misaligned and erroneously contains Bazel package prefix.

A similar problem was reported [here](https://github.com/bazelbuild/bazel/issues/8277), see this https://github.com/bazelbuild/bazel/issues/8277#issuecomment-581054330 on this issue, but it was already closed.

Minimal reproducer.

Consider this directory structure:

<workspace_root>/foo/org/example/app/Test.java

The build file is put in `foo` directory. The `java_library` rule is:

```python
java_library(
  name = "foo",
  srcs = glob(["org/**/*.java"]),
)
```

When building `foo` the java library is correct, but the `libfoo-src.jar` content is wrong: all entries are prefixed with "foo"-prefix:

"foo/org/example/app/Test.java"
instead of just
"org/example/app/Test.java"

Note, that if I rename the "foo" directory to one of these directories:

- java
- src
- src/main/java

then the Bazel package directory (say "java") is correctly stripped in `libfoo-src.jar`. However, let say that the project owners **cannot** rename the "foo"-directory to "java"-directory, so that we have to find a solution, to build "libfoo-src.jar" with sane content.

Why is it crucial to create src-JAR with sane libfoo-src.jar? Because the pipeline for publishing to Maven Central requires three artifacts: "jar", "source" and "javadoc". To create javadoc-JAR, we need correct source-JAR, otherwise the javadoc-machinery is broken. Moreover, for IDEs integration to work properly, source-JAR must be sane as well. Otherwise, Bazel users would mess around with IDE plugins, as can be seen [here](https://github.com/bazelbuild/intellij/issues/1206) and [here](https://github.com/bazelbuild/intellij/pull/120).

One approach to fix that would be to provide `source_strip_prefix` in `java_library` rule or even apply `resource_strip_prefix` on path normalization in "-src.jar" file.

One non intrusive workaround, that can be done already now, is to create `srcjar` manually and provide it as source to the `java_library` rule. Unfortunately, `zip_file` rule is still missing in Bazel, but was added to Buck years ago, so that it could be easily done there:

```python
  zip_file(
      name = "foo-sources",
      srcs = ["org/davido/app/Test.java"],
      out = "foo-sources.srcjar",
  )
```

And in action:

```shell
  $ buck build foo:foo-sources --show-output
//foo:foo-sources buck-out/gen/foo/foo-sources__/foo-sources.srcjar

  $ unzip -t buck-out/gen/foo/foo-sources__/foo-sources.srcjar
Archive:  buck-out/gen/foo/foo-sources__/foo-sources.srcjar
    testing: org/                     OK
    testing: org/davido/              OK
    testing: org/davido/app/          OK
    testing: org/davido/app/Test.java   OK
```

Of course, another option would be to use `genrule`, create zip archive manually and provide the right rule output name.

Using `java_binary`, the sources can be provided as `resources` and the path can be normalized using `resource_strip_prefix=foo`.

Unfortunately, `java_binary` produces hard coded output "[name].jar" with "jar"-suffix that must be renamed first so that it can be passed in as input to `java_library` rule, so something like:

WORKSPACE:
```python
workspace(name = "foo")

git_repository(
    name = "com_googlesource_gerrit_bazlets",
    remote = "https://gerrit.googlesource.com/bazlets",
    commit = "fbe2b2fd07c95d752dced6b8624c9d5a08e8c6c6",
)
```

foo/BUILD
```python
load("@com_googlesource_gerrit_bazlets//tools:javadoc.bzl", "java_doc")

# TODO(davido): This doesn't work: libfoo-src.jar is broken, unfortunately
#java_library(
#   name = "foo",
#   srcs = glob(["org/**/*.java"]),
#)

# TODO(davido): Remove that hack to create source package without the wrong path prefix.
# Unfortunately, Bazel is still missing zip_file() rule compared to Buck tool, see:
# https://buck.build/rule/zip_file.html
java_binary(
    name = "foo-src-binary",
    main_class = "Dummy.java",
    resources = glob(["org/**/*.java"]),
    resource_strip_prefix = "foo",
)

# Rename to .srcjar so that java_library rule can accept it
genrule(
    name = "foo-src",
    cmd = "mv $< $@",
    srcs = [":foo-src-binary_deploy.jar"],
    outs = ["foo.srcjar"],
)

java_library(
    name = "foo",
    srcs = [":foo-src"],
)

java_doc(
    name = "foo-javadoc",
    libs = [":foo"],
    pkgs = ["org.example.app"],
    title = "Fancy foo application",
)
```

**Comment by davido** [comment]
OK, this comments in JavaUtils.java confirms my observation:
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/java/JavaUtil.java#L31-L50:

```java
   [...]
   * This way of figuring out Java source roots is basically
   * broken.
   [...]
```

There should be a better way to extend it. So in my example above, with this patch, directory "foo" is now detected as Bazel root:

```diff
diff --git a/src/main/java/com/google/devtools/build/lib/rules/java/JavaUtil.java b/src/main/java/com/google/devtools/build/lib/rules/java/JavaUtil.java
index dc0116035f..8678f63e6d 100644
--- a/src/main/java/com/google/devtools/build/lib/rules/java/JavaUtil.java
+++ b/src/main/java/com/google/devtools/build/lib/rules/java/JavaUtil.java
@@ -60,7 +60,7 @@ public final class JavaUtil {
 
   /** Java source roots, used to relativize resource paths and infer main_class values. */
   public static final ImmutableSet<String> KNOWN_SOURCE_ROOTS =
-      ImmutableSet.of("java", "javatests", "src", "testsrc");
+      ImmutableSet.of("foo", "java", "javatests", "src", "testsrc");
 
   /**
    * Finds the index of the segment in a Java path fragment that precedes the source root. Starts

```

The correct mapping is added to the singlejar parameter file:

```
  $ cat .../bin/foo/libapp-src.jar-0.params
  [...]
  --resources
  foo/org/davido/app/Test.java:org/davido/app/Test.java
```

And as the consequence, the libapp-src.jar has correct content:

```
  $ b10 build foo:libapp-src.jar
 INFO: Found 1 target...
Target //foo:libapp-src.jar up-to-date:
  bazel-bin/foo/libapp-src.jar

  $ unzip -t bazel-bin/foo/libapp-src.jar
  Archive:  bazel-bin/foo/libapp-src.jar
    testing: META-INF/                OK
    testing: META-INF/MANIFEST.MF     OK
    testing: org/                     OK
    testing: org/davido/              OK
    testing: org/davido/app/          OK
    testing: org/davido/app/Test.java   OK
```

So, the better question is what is the most non intrusive way, to extend the src_roots? Bazel could borrow Buck's [java]. concept, and allow to extend it in .bazelrc file, e.g.:

```
src_roots
The paths to roots of Java code (where a root contains a tree of Java folders where the folder structure mirrors the package structure). This list of paths is comma-delimited. Paths that start with a slash are relative to the root of the project, and all other paths can match a folder anywhere in the tree. In the example below, we match all folders named src, and java and javatests at the root of the project.

[java]
  src_roots = src, /java/, /javatests/
```

[1] https://buck.build/files-and-dirs/buckconfig.html#java.src_roots

**Comment by cushon** [comment]
see #6353
