### ISSUE TITLE
Bootstrap Bazel cannot compile itself on Windows

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#1070]
`output/bazel build //src:bazel` returns:

```
ERROR: C:/tools/msys64/var/tmp/_bazel_lberki/72f8faba6c8d77fec9b3b58d043f6b66/external/bazel_tools/third_party/protobuf/BUILD:35:1: Extracting interface @bazel_tools//third_party/protobuf:protobuf failed: ijar.exe failed: error executing command external/bazel_tools/tools/jdk/ijar/ijar.exe external/bazel_tools/third_party/protobuf/protobuf-java-3.0.0-beta-1.jar ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 35584.
CreateFile(): The system cannot find the path specified.

      0 [main] ijar 718396 cygwin_exception::open_stackdumpfile: Dumping stack trace to ijar.exe.stackdump
```

The `CreateFile()` invocation is for one of the file handles used for memory mapping. I haven't investigated it more thoroughly, though.

**Comment by lberki** [comment]
Assigning to @dslomov  since I'll be OOO for a few days and he'll come back earlier.

**Comment by damienmg** [comment]
We should run the determinism tests, it will ensure that works (`./compile.sh compile,determinism`).

I will actually replace the Bazel job by only those for CI on other platforms (and run the test suite in a separate job).

**Comment by lberki** [comment]
We should run tests, except that no one has ever seriously tried to get any test to run on Windows :) (e.g. `LabelTest` works, `CcLibraryConfiguredTargetTest` doesn't, but is probably fixable by tweaking the test CROSSTOOL)

**Comment by damienmg** [comment]
So according to today's meeting this one is solved?

**Comment by lberki** [comment]
(sigh)

Almost. The error I get if I don't set `--output_base` to something short is because there is an output file called 
```
bazel-out/local_windows_msys64-fastbuild/bin/src/main/protobuf/libinvocation_policy_java_proto_srcjar.srcjar.proto_output/com/google/devtools/build/lib/runtime/proto/InvocationPolicyOuterClass.java
```

whose path is too long when under the default output base `C:/tools/msys64/var/tmp/_bazel_${USER}/${CHECKSUM}` .

Since that's an instance of the generic "What on Earth do we do with long file names?" problem, I'm  closing this bug.
