### ISSUE TITLE
BEP should include output of `bazel run`

### ISSUE THREAD

**Issue by segiddins** [bazelbuild/bazel#10718]
### Description of the problem / feature request:

The BEP output of `bazel run` does not include any events for the `run` bit, only the `build` part

### Feature requests: what underlying problem are you trying to solve with this feature?

I want to consolidate everything our CI does to happen through `bazel` commands. `bazel run` is awesome for being able to run stuff, while making sure everything is built. In particular, `bazel run` having access to `$BUILD_WORKSPACE_DIRECTORY` makes it possible to run scripts that `bazel test` wouldn't be able to run.

However, the build event output after a `bazel run` includes _nothing_ about what was run. It even includes a `buildFinished` event of `SUCCESS` after `bazel run` fails. I would like there to be some sort of run output event, that says what was run (e.g. the command line), the output (stdout and stderr), and the status code of the run. `buildFinished` should also take that status into account.

### What operating system are you running Bazel on?

```
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G2022
```

### What's the output of `bazel info release`?

`release 2.0.0`

###  Have you found anything relevant by searching the web?

No

**Comment by lberki** [comment]
This is unfortunately impossible with the current implementation. 

How `bazel run` works is that the client calls `exec()` on the process being run, thus, it's entirely out of our control.

It didn't used to be like that and the process used to be the child of the server, but that resulted in no terminal input being available to the process, no terminal output being printed before it finished and the server lock being held while the process was running, which was not a great state of affairs.
