### ISSUE TITLE
Numerous dead links under Providers documentation

### ISSUE THREAD

**Issue by mtrea** [bazelbuild/bazel#10725]
### Description of the problem / feature request:

Numerous dead links on https://docs.bazel.build/versions/0.17.1/skylark/lib/skylark-provider.html including:

- https://docs.bazel.build/versions/2.0.0/skylark/lib/cc_skylark_info.html
- https://docs.bazel.build/versions/2.0.0/skylark/lib/ParsedAndroidAssetsApi.html
- https://docs.bazel.build/versions/2.0.0/skylark/lib/ProguardMappingProvider.html
- https://docs.bazel.build/versions/2.0.0/skylark/lib/ValidatedAndroidDataApi.html
- https://docs.bazel.build/versions/2.0.0/skylark/lib/AndroidSkylarkApiProvider.html
- https://docs.bazel.build/versions/2.0.0/skylark/lib/AndroidAssetsInfo.html
- https://docs.bazel.build/versions/2.0.0/skylark/lib/AndroidBinaryData.html
- https://docs.bazel.build/versions/2.0.0/skylark/lib/AndroidCcLinkParamsInfo.html
- https://docs.bazel.build/versions/2.0.0/skylark/lib/AndroidFeatureFlagSetInfo.html
- https://docs.bazel.build/versions/2.0.0/skylark/lib/AndroidIdlInfo.html
- https://docs.bazel.build/versions/2.0.0/skylark/lib/AndroidInstrumentationInfo.html
- https://docs.bazel.build/versions/2.0.0/skylark/lib/AndroidLibraryAarInfo.html
- https://docs.bazel.build/versions/2.0.0/skylark/lib/AndroidLibraryResourceClassJarProvider.html
- https://docs.bazel.build/versions/2.0.0/skylark/lib/AndroidManifestApi.html
- https://docs.bazel.build/versions/2.0.0/skylark/lib/AndroidManifestInfo.html
- https://docs.bazel.build/versions/2.0.0/skylark/lib/AndroidPreDexJarInfo.html
- https://docs.bazel.build/versions/2.0.0/skylark/lib/AndroidResourcesInfo.html
- https://docs.bazel.build/versions/2.0.0/skylark/lib/ApkInfo.html

**Comment by gregestren** [comment]
It looks like the problem is all links are to the current Bazel version, no matter what version the original page is set to.

So to the extent there's deviation between defined providers and Bazel versions you get 404s.

**Comment by gregestren** [comment]
@aiuto  for reference (we were just chatting about version mismatching).
