### ISSUE TITLE
bazel test ... fails

### ISSUE THREAD

**Issue by laramiel** [bazelbuild/bazel#1072]
At the workspace level one should be able to run `bazel test ...`

Repro: https://github.com/laramiel/bazel-golang-vendor-test.git

See also https://github.com/bazelbuild/rules_go/issues/8

```
$ git clone https://github.com/laramiel/bazel-golang-vendor-test.git
$ cd bazel-golang-vendor-test
$ bazel test ...
```

Expected: tests in all subdirectories run.
Actual: bazel indicates a problem with bazel/baze_workspace/tools/build_rules/py_rules.bzl

**Comment by kchodorow** [comment]
It sounds like you've got either an old version of Bazel and/or an old .bazelrc laying around.  You can remove the `--package_path` lines from your .bazelrc (probably in your home directory or /usr/local/lib/bazel/etc).

**Comment by laramiel** [comment]
This was with a new build of bazel.
Removing ~/.bazelrc solved the problem.
