### ISSUE TITLE
onsigprof not completely async-safe

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#10726]
@alandonovan,
`cpu_profiler_posix.cc`'s `onsigprof` function has a comment explaining that, as a signal handler, it must only invoke async-safe libc functions. In the implementation, though, one finds:
https://github.com/bazelbuild/bazel/blob/329ec6dde90dd2e3392076ad116362c271844404/src/main/java/com/google/devtools/build/lib/syntax/cpu_profiler_posix.cc#L79-L80
`perror()` is not among POSIX's list of async safe functions. Indeed, it uses stdio. The practical effect of this function call probably is limited to a hang instead of a prompt `abort()` if this branch is reached. However, the rest of the function seems to be careful about signal safety even in error handling.

**Comment by benjaminp** [comment]
I don't think `strerror_r` is safe either. On glibc at least, it may enter arbitrary translation machinery.

**Comment by alandonovan** [comment]
It's possible, but vanishingly unlikely for the error codes returned by write. Even strerror (no _r) should be fine in this respect, and that's what I propose to use in the fix. The very worst outcome is a rare data race leading to a finite amount of junk or the wrong error message.

**Comment by benjaminp** [comment]
I noticed [patches](https://sourceware.org/pipermail/libc-alpha/2020-May/113935.html) have appeared to make `strerror` signal-safe on glibc. So, this may become completely safe in practical terms shortly.
