### ISSUE TITLE
Unable to use ed25519 ssh keys when pulling from remote repositores

### ISSUE THREAD

**Issue by thomaso-mirodin** [bazelbuild/bazel#1073]
Hey! :D

I was debugging a weird issue today, it looks like bazel (or more likely Jsch) doesn't support cloning from git servers when using a ed25519 key.

```
ERROR: /path/to/project/BUILD:11:1: no such package '@remote_fork//': Error cloning repository: git@github.com:remote/dependency.git: invalid privatekey: {hash removed} caused by git@github.com:remote/dependency.git: invalid privatekey: {hash removed} caused by git@github.com:remote/dependency.git: invalid privatekey: {hash removed} and referenced by '//remote_fork:remote'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 2.367s
```

I found a similar error on this issue: https://github.com/sheimi/SGit/issues/17. This issue seemed to suggest that it was failing due to Jsch so on a hunch I tried switching to an rsa key instead which fixed the issue.

But uh... I like my ed25519 key and would like to keep using it :P

**Comment by wolfgangmeyers** [comment]
@thomaso-mirodin was this with a git_repository rule? I tried without success to get an rsa key to work with git_repository before finding in the docs that only http was supported - http://bazel.io/docs/be/workspace.html#git_repository

**Comment by thomaso-mirodin** [comment]
Uhh, well we've been using ssh checkouts for a little while, so I think it might've snuck in without the documentation getting updated :S

**Comment by wolfgangmeyers** [comment]
Interesting. I found this today, which worked quite well for using git repositories over ssh - https://github.com/nelhage/bazel_git_repositories

**Comment by kchodorow** [comment]
bazel_git_repositories is a good workaround for this, so bumping down the priority.

**Comment by thomaso-mirodin** [comment]
#1408 would also fix this issue :D

**Comment by bluecmd** [comment]
If you're using a keyphrase on your SSH key and using the native git_repository you will get this error:
```
$ bazel build :main
ERROR: [...]/third_party/BUILD:957:1: no such package '@dropwizard_jersey//': Error cloning repository: git@github.com:bluecmd/dropwizard.git: Auth cancel caused by git@github.com:bluecmd/dropwizard.git: Auth cancel caused by Auth cancel and referenced by '//third_party:io_dropwizard_dropwizard_jersey'.
ERROR: Analysis of target '//:main' failed; build aborted.
INFO: Elapsed time: 0.137s
```

This error comes from Jsch failing to authenticate, so it's a +1 on the issues with Jsch.

**Comment by davidzchen** [comment]
#1408 Has been merged. Does using the Skylark `git_repository` rule work for you? https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/git.bzl

Also, is there anything blocking finishing the migration from the native Git rules to the Skylark Git rules? If not, I think we should go ahead and start encouraging people to switch over.

**Comment by bluecmd** [comment]
That's the one I'm using right now as a workaround yes.

**Comment by dslomov** [comment]
git_repository is no more.
