### ISSUE TITLE
[QUESTION] How to use a binary which compiled by another project?

### ISSUE THREAD

**Issue by membphis** [bazelbuild/bazel#10737]
### Description of the problem / feature request:

I have two projects, for example: 'luajit-src' and 'example'.

After the bazel compiled 'luajit-src', I will get the bin binary which named 'luajit'.

I need to use the binary `luajit` for compiling my 'example' project. But I do not know how to fetch the path of 'luajit'.

I take a look at the API but I still do not know how to do with this case. https://docs.bazel.build/versions/2.1.0/skylark/lib/skylark-overview.html

**Comment by dslomov** [comment]
It is best to refer such questions to bazel-discuss@googlegroups.com.

In a nutshell:
 * Bazel enforces strict dependency declarations. If you want to use a result of building a target in another target, you need to declatre a dependency. This is also true for tools (such as `luajit` in your case)
 * when you reference a target A from a target B, A's outputs (such as the resulting binary) are available to target B.

As a simple example, see [how it works for `genrule`](https://docs.bazel.build/versions/master/be/general.html#genrule_examples).

**Comment by membphis** [comment]
many thx @dslomov
