### ISSUE TITLE
objc_import missing deps argument

### ISSUE THREAD

**Issue by cpsauer** [bazelbuild/bazel#10739]
Hi wonderful Bazel folks,

This is a feature request, but hopefully a fairly straightforward one.

I'd noticed that objc_import--unlike most other rules--doesn't allow you to specify deps. But I really think it's worth allowing it to do so. It's not uncommon for .a files to have dependencies, and I think it's a good thing in terms of promoting modularity and reuse. 

Consider, for example, a closed-source library that depends on protobuf. Better to allow the library to easily depend on a shared protobuf that might be used elsewhere in the project, rather than encourage all dependencies to already be in the archive.

Thanks for your consideration,
Chris
(ex-Googler)

**Comment by cpsauer** [comment]
(Workarounds to this are somewhat complicated by #10738)

**Comment by cpsauer** [comment]
From the docs, this seems to have been fixed in master, though not in a yet released version of Bazel.
(Not in 4.0, unsure if in 4.1)

**Comment by cpsauer** [comment]
Whoops! The fix seems to have been reverted! For a brief, glorious moment, it looked like objc_import was on track to have the full complement of objc attributes, like deps and data, so I closed things, but it seems like I jumped the gun.

I'm going to reopen this and tag @googlewalt, since it looks like he's the one doing good work in there and making changes. (Thanks for all the improvements, @googlewalt! They're much appreciated.)

**Comment by cpsauer** [comment]
FWIW, if objc_library allowed archives (.a) in srcs, like its cc_library equivalent, I think that'd solve the problem, too. That'd make objc_library general enough to be used to either build or import an objc_library!

**Comment by cpsauer** [comment]
@bazelbuild/triage, this is still quite relevant and would be quite useful, IMO.

**Comment by googlewalt** [comment]
This should be fixed in https://github.com/bazelbuild/bazel/commit/0f19ef39919c79d472264b869a6e6263718886ec, though I see that the documentation was not updated.

**Comment by cpsauer** [comment]
(@bazelbuild/triage doesn't seem to create a tag (no link) so I'm going to tag @sgowroji and @Pavank1992 manually. Please coach me if you'd have preferred otherwise--and maybe update the bot's instructions)

**Comment by cpsauer** [comment]
Oh, amazing. Thanks @googlewalt! Will test--and leave this open for now to track docs?

**Comment by cpsauer** [comment]
Update: Have confirmed deps has been added as an attribute and seems to work in a quick test. 

[Sorry that I'd wrongly assumed the docs would be auto-synced.]

 Still think it makes sense to leave this open to track the docs.

[The original use case I'd planned to use this for--using a google library from bazel--is sadly also blocked by https://github.com/bazelbuild/bazel/issues/17018]

**Comment by googlewalt** [comment]
I'll fix the documentation.

**Comment by cpsauer** [comment]
Thanks so much @googlewalt! Really appreciate all you do--including knocking this out.
