### ISSUE TITLE
FR: mutual tls auth for remote cache/executor

### ISSUE THREAD

**Issue by gorilych** [bazelbuild/bazel#10735]
### Description of the problem / feature request:

I was under impression that [--tls_certificate](https://docs.bazel.build/versions/2.0.0/command-line-reference.html#flag--tls_certificate) can be used for mutual tls, but in code I see that it only configures trusted CA certs: [GoogleAuthUtils.java#L117](https://github.com/bazelbuild/bazel/blob/2.1.0/src/main/java/com/google/devtools/build/lib/authandtls/GoogleAuthUtils.java#L117)

In code it only uses `trustManager`, while mutual tls requires `keyManager` to set up client cert and private key. Example https://github.com/grpc/grpc-java/issues/4004#issuecomment-360576997

### Feature requests: what underlying problem are you trying to solve with this feature?

I need to use remote cache grpcs with mutual tls auth

### What operating system are you running Bazel on?

Debian 10

### What's the output of `bazel info release`?

release 2.1.0

**Comment by ulfjack** [comment]
I'm interested in seeing this happen. Bazel remote execution currently doesn't support a lot of authentication options out of the box, and I can think of use cases where this is more appropriate than Google access tokens.
