### ISSUE TITLE
Implement --watchfs for the Mac

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#1074]
We had to disable --watchfs on the Mac, because the WatchService shipped with the JDK is statting all the files, which makes it a lot slower than our own statting implementation.

We could experiment with this:
https://github.com/gjoseph/BarbaryWatchService

**Comment by ulfjack** [comment]
According to my profiling, the lack of watchfs is responsible for ~60% of the null build time on bazel itself.

**Comment by ulfjack** [comment]
I had a look at BarbaryWatchService, and it's probably not a good fit for us as-is. It contains a (complete?) copy of the watch service API, which we don't need as we can rely on Java 7 (no need to be backwards compatible with 6). It's also using JNA; we're already using normal JNI, and JNA itself also uses JNI (libffi, IIUC), so unless we actually converted some of our current JNI to JNA (which is unlikely, as we can't convert all of it), it seems like a large additional dependency for no significant benefit. The actual glue code to talk to the MacOS APIs isn't all that complicated, AFAICT, leaving us with several downsides and little upside if we went with BWS.

**Comment by damienmg** [comment]
This sounds like a good project for the next person to join the team :)

**Comment by damienmg** [comment]
Doc about FSEvents API: https://developer.apple.com/library/mac/documentation/Darwin/Conceptual/FSEvents_ProgGuide/UsingtheFSEventsFramework/UsingtheFSEventsFramework.html

**Comment by damienmg** [comment]
Ok there is a prototype here: https://bazel-review.googlesource.com/#/c/3420/ but @dmaclach has suggested using GCD: https://developer.apple.com/library/ios/documentation/General/Conceptual/ConcurrencyProgrammingGuide/GCDWorkQueues/GCDWorkQueues.html#//apple_ref/doc/uid/TP40008091-CH103-SW23 and I have been side track by more pressing issue, on hold

**Comment by damienmg** [comment]
GCD has a big blocker: fd usage, we cannot depends on it. Using the FSEvents prototype instead.
