### ISSUE TITLE
Make it easier to deprecate flags.

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#10749]
Instead of requiring people to introduce `--incompatible_*` flag for every deprecated flag, change the procedure:
 * Add a second kind of incompatible changes, "deprectaed flag"
 * for deprecated flags, require GitHub issue url in `deprecationWarning`.
Then the procedure for flag deprecation is:
 * File GitHub issue
 * submit a PR adding `deprecationWarning` to  the flag referencing the url
 * at major release time, just remove the flag

**Comment by laurentlb** [comment]
What's the action item here?
Is it just about updating the policy?

**Comment by philwo** [comment]
Closing as obsolete.
