### ISSUE TITLE
BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN causes error in presence of --incompatible_enable_cc_toolchain_resolution

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#10756]
### Description of the problem / feature request:

We have --incompatible_enable_cc_toolchain_resolution set and have custom toolchains for our platforms. When we try to set BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 to make sure detected toolchain is never picked up we get the error `ERROR: C:/builds/y77h45xt/external/local_config_cc/BUILD:28:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'x64_windows'`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

With --incompatible_enable_cc_toolchain_resolution **cc_toolchain_suite** should not be relevant at all. BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 causes generation of dummy cc_toolchain_suite ```cc_toolchain_suite(
    name = "toolchain",
    toolchains = {
        "local|local": ":local",
        "local": ":local",
    },
) ``` which does not contain toolchains for any cpu, which causes bogus error `cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu...` for any cpu. 

### What operating system are you running Bazel on?

Windows 10, but the problem does not seem OS specific.

### What's the output of `bazel info release`?

2.1

###  Have you found anything relevant by searching the web?

https://www.bountysource.com/issues/69193507-incompatible_enable_cc_toolchain_resolution-turn-on-toolchain-resolution-for-cc-rules - indicates the same problem and https://github.com/bazelbuild/bazel/pull/8459 does not fix it.

**Comment by katre** [comment]
This is internal to the CC rules implementation and doesn't involve configurability.

**Comment by oquenchil** [comment]
Fixed by chancila's patch.
