### ISSUE TITLE
why does moving target files require changes to copts paths and java.library.path? 

### ISSUE THREAD

**Issue by luxe** [bazelbuild/bazel#10754]
### Summary
This question is about building / running bazel targets.  After moving the source code of a target (as well as its BUILD file), additional paths are now required for `cc_library` and `java_binary` in order to get the code building/running again.  I'm wondering why this is the case, and hoping to get some clarity on why this happens and how best to specify these paths moving forward.  A working repository example is used throughout.

### Description of the problem:

We start with a working example, and then break it to discuss the issue.  
In this example, we want to call c code from java.  This is done through JNI (Java Native Interface).  
An example was written by @hlopko (https://github.com/hlopko/bazel-jni-example).   

We will use @enricobacis's patched version https://github.com/enricobacis/bazel-jni-example  
because it works with the newest bazel (2.1.0).

Building the JNI example:  
```
git clone https://github.com/luxe/bazel-jni-example
cd bazel-jni-example
bazel --version 
bazel 2.1.0
bazel run :Main 
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:Main (19 packages loaded, 344 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /home/thickey/.cache/bazel/_bazel_thickey/3cb1da8c24eb0f11fdcfaac57f79a3d7/sandbox
Target //:Main up-to-date:
  bazel-bin/Main.jar
  bazel-bin/Main
INFO: Elapsed time: 4.508s, Critical Path: 0.41s
INFO: 1 process: 1 linux-sandbox.
INFO: Build completed successfully, 2 total actions
INFO: Build completed successfully, 2 total actions
42
```

This worked correctly and printed 42.  
Now we want to move the target's source code into a folder.  
```
mkdir example 
mv Main.h example/   
mv Main.cc example/
mv Main.java example/ 
mv BUILD example/ 
```

Building this target now fails:  
```
bazel run //example:Main                                                                                                                                                                                             1
INFO: Analyzed target //example:Main (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/thickey/Desktop/bazel-jni-example/example/BUILD:1:1: C++ compilation of rule '//example:main-jni-lib' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 24 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
example/Main.cc:1:10: fatal error: jni.h: No such file or directory
 #include <jni.h>
          ^~~~~~~
compilation terminated.
Target //example:Main failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.311s, Critical Path: 0.08s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

we can remedy the problem by adding copts paths directly.  
**why is this the case?**
```
copts = ["-isystem","bazel-out/k8-fastbuild/bin/external/bazel_tools/tools/jdk/include","-isystem","bazel-out/k8-fastbuild/bin/external/bazel_tools/tools/jdk/include/linux"],
```

now we get a runtime error:  
```
bazel run //example:Main
INFO: Analyzed target //example:Main (1 packages loaded, 6 targets configured).
INFO: Found 1 target...
Target //example:Main up-to-date:
  bazel-bin/example/Main.jar
  bazel-bin/example/Main
INFO: Elapsed time: 0.415s, Critical Path: 0.14s
INFO: 1 process: 1 linux-sandbox.
INFO: Build completed successfully, 2 total actions
INFO: Build completed successfully, 2 total actions
Exception in thread "main" java.lang.UnsatisfiedLinkError: no main-jni in java.library.path: [.]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
	at java.base/java.lang.System.loadLibrary(System.java:1870)
	at Main.<clinit>(Main.java:3)
```

This can be fixed by changing `jvm_flags = [ "-Djava.library.path=." ],` to a direct path.
something like:  
```
jvm_flags = [ "-Djava.library.path=/home/thickey/Desktop/bazel-jni-example/bazel-bin/example" ],
```
**why is this the case?**

The program works again.

### what underlying problem are you trying to solve?

I'm looking to understand why this happens.  Does it have something to do with runfiles and/or not being on the root?  Is this expected behavior or some kind of bug?  I had assumed that moving the source code + the BUILD file would not require explicit paths.   I only thought the target path would be different for building/running.  

If this is indeed normal behavior, how should I actually be specifying these things?  It's probably incorrect to specify `bazel-out/k8-fastbuild` anywhere in the target rule (since it might now always be k8 and fastbuild).  I also couldn't get `java.library.path` to be anything other than a full path.  I tried doing things relative from the runfiles directory, but that didn't seem to work.  

#### Note 1:   
If I keep `jvm_flags = [ "-Djava.library.path=." ],` as is, and step into bazel bin,  I can run the java wrapper script and it works.  
```
cd bazel-bin/example/
./Main
42
```
#### Note 2:
building the jni headers separately according to this example:  
https://gist.github.com/bsidhom/108efc977074eafbb08329ed3910c32f#file-build-jni-L15
allowed me to add `jni` as a dep to `cc_library` and get rid of the explicit `copts` flags. 

#### Note 3:
related issue: https://github.com/bazelbuild/bazel/issues/6958

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The best way to reproduce this scenario is by doing:  
```
git clone https://github.com/luxe/bazel-jni-example
cd bazel-jni-example

bazel run :Main <- should work

mkdir example 
mv Main.h example/   
mv Main.cc example/
mv Main.java example/ 
mv BUILD example/ 

bazel run //example:Main <- should not work
```

### What operating system are you running Bazel on?
```
lsb_release -a                                                                                                                                                                                                       1
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

### What's the output of `bazel info release`?

```
bazel info release 
release 2.1.0
```

**Comment by aiuto** [comment]
@luxe  Do you consider this answered by the PR above?

**Comment by luxe** [comment]
Yes, a combination of [file build jni](https://gist.github.com/bsidhom/108efc977074eafbb08329ed3910c32f#file-build-jni-L15) and https://github.com/bazelbuild/bazel/issues/6958 for java.library.path resolve address my issue.  However,  I'm only able to get java.library.path to work by providing a full path.  I'll need to try https://github.com/bazelbuild/bazel/pull/7042 and see if patch works.
