### ISSUE TITLE
clean required after workaround to missing build file

### ISSUE THREAD

**Issue by wolfgangmeyers** [bazelbuild/bazel#1076]
As a follow up to https://github.com/bazelbuild/bazel/issues/1075

In order to work around the problem, I can copy closure/library/closure_library.BUILD into my project. However this doesn't seem to take effect until `bazel clean` is run.

Steps to reproduce:
1. unzip the project code from https://github.com/bazelbuild/bazel/files/186571/missing_closure_library.zip
2. run `bazel build //:main`
3. Copy the build file from rules_closure (https://github.com/bazelbuild/rules_closure/blob/master/closure/library/closure_library.BUILD) to `closure/library`
4. run `bazel build //:main` again. This build should fail with the same error message.
5. run `bazel clean`
6. run `bazel build //:main` a third time. This build should succeed.

**Comment by kchodorow** [comment]
Good find, we're not invalidating the BUILD file symlink.

**Comment by meisterT** [comment]
The example doesn't work with current Bazel anymore. Is this still an issue?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
