### ISSUE TITLE
bazel help requires a server

### ISSUE THREAD

**Issue by Profpatsch** [bazelbuild/bazel#10767]
### Description of the problem / feature request:

```
$ bazel help --long
Waiting for server to be started …
```

Surely the client could display the static help text without starting a server first.

This leads to funny interactions when a (looooong) build is running:

```
$ bazel help --long
Another command (pid=21738) is running.  Waiting for it to complete on the server...
```

### Feature requests: what underlying problem are you trying to solve with this feature?

Make `bazel help` a short codepath; ideally it should be pretty instant.

Alternatively: have manpage or offline docs

### What operating system are you running Bazel on?

NixOS 20.01

### What's the output of `bazel info release`?

```
> bazel info release
INFO: Invocation ID: 3b8ae36a-fe93-4316-8331-aa996743106f
release 2.0.0- (@non-git)
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/build-managers/bazel/default.nix

###  Have you found anything relevant by searching the web?

Prior work: [`--version` works without starting a server](https://github.com/bazelbuild/bazel/issues/1569)

**Comment by ulfjack** [comment]
We have been reluctant to move the help command to the client. Technically, the help pages are *dynamically* generated using reflection over the options classes. This could be done as part of the build, but that would increase the binary size.

**Comment by Profpatsch** [comment]
> This could be done as part of the build, but that would increase the binary size.

Even if the docs are 10kb, the binary is current 24MB on my system, I personally would be willing to handle that small overhead.

**Comment by jin** [comment]
FR for manpage: https://github.com/bazelbuild/bazel/issues/10519

**Comment by philwo** [comment]
I don't think it's worth it to add the complexity to our code just to make that command display faster.

We should rather make the server able to process multiple operations in parallel.

Manpages SGTM.
