### ISSUE TITLE
Mark --subcommands options with `terminal_output` tag

### ISSUE THREAD

**Issue by Profpatsch** [bazelbuild/bazel#10771]
### Description of the problem / feature request:

There’s a `Tags:` line with [categorizes command line arguments](https://docs.bazel.build/versions/0.19.2/command-line-reference.html#version-options) which is very helpful for finding related arguments.

`terminal_output` marks flag which change the terminal output:

![screenshot](https://user-images.githubusercontent.com/3153638/74358517-d83b1900-4dc1-11ea-99fb-24fe4f319ece.png)

`--subcommands` is a pretty obvious argument which does that, but it’s missing the tag:

![screenshot](https://user-images.githubusercontent.com/3153638/74358554-ed17ac80-4dc1-11ea-9bcb-bfacaea2b9a3.png)

### Feature requests: what underlying problem are you trying to solve with this feature?

Make it easier to discover related CLI arguments (the `help` output is sorted alphabetically and has no priorization).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Add the tag to `subcommands` and maybe check the tags on all other flags for consistency at the same time.

### What operating system are you running Bazel on?

Nixos 20.01

### What's the output of `bazel info release`?

```
> bazel info release
INFO: Invocation ID: 2d12afa9-6016-4535-ac1c-f36c20a8814c
release 2.0.0- (@non-git)
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

bazel from nixpkgs

**Comment by philwo** [comment]
This was fixed in https://github.com/bazelbuild/bazel/commit/1329798b8a60c2f36d9f441496bf38e3e4a0f692.
