### ISSUE TITLE
cc_library + cc_import combination bug

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#10770]
### Description of the problem / feature request:

First target produces expected output and the second target which depends on the first one does not produce any output.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

This is standard Bazel example: https://github.com/bazelbuild/bazel/tree/master/examples/windows/dll 
```
 # Build the shared library
  cc_binary(
      name = "foo.so",
      srcs = ["foo.cc", "foo.h"],
      linkshared = 1,
      #copts = ["/DCOMPILING_DLL"],
      copts = ["-fPIC"],
  )

  # Get the import library for the dll
  filegroup(
      name = "foo_imp_lib",
      srcs = [":foo.so"],
      output_group = "interface_library",
  )

  # Because we cannot directly depend on cc_binary from other cc
  # rules in deps attribute, we use cc_import as a bridge to depend
  # on the dll.
  cc_import(
      name = "foo_import",
      interface_library = ":foo_imp_lib",
      shared_library = ":foo.so",
  )

  # Create a new cc_library to also include the headers needed for
  # the shared library
  cc_library(
      name = "foo",
      hdrs = ["foo.h"],
      deps = [":foo_import"],
  )
```
Building ":foo" does not compile or link anything, but building "foo_imp_lib" does.

### What operating system are you running Bazel on?

Linux, Windows

### What's the output of `bazel info release`?

2.1

###  Have you found anything relevant by searching the web?

https://groups.google.com/forum/#!msg/bazel-discuss/r8GTp3jwfwU/91W2pXM1EwAJ

@laszlocsomor

**Comment by laszlocsomor** [comment]
Clarification: @konste found the problem using the example for Windows, not the BUILD file above. See: https://groups.google.com/d/msg/bazel-discuss/r8GTp3jwfwU/91W2pXM1EwAJ

The BUILD file above is just my adaptation for the same scenario on Linux, and I'm not fully certain it is correct. See: https://groups.google.com/d/msg/bazel-discuss/r8GTp3jwfwU/npMKGTqJAwAJ

**Comment by oquenchil** [comment]
I believe that the issue here is that the files do not get added to any action nor are they in the default output group when building the cc_library. I think the fix would be to add every file in an attribute of cc_import to filesToBuild.

**Comment by konste** [comment]
Here is direct Linux repro: https://github.com/Bazel-snippets/cc_library_repro_2
There are four build rules in there - cc_binary, cc_import, cc_library and cc_test (in this order).
When you request first (cc_binary) or last (cc_test) everything builds, but when you request second (cc_import) or third (cc_library) the response is `nothing to build`.

Why it is important to fix: the combination of cc_import with cc_library is very popular for many scenarios such as: 1. producing shared libs on Windows; 2. Making .dylib shared libs on OSX; 3. Importing of pre-build shared libs on all platforms. 

When cc_library target is requested and cc_library itself does not produce any files (all scenarios above, header only libraries, etc.) but its dependencies produce files - it is currently broken. Don't even get me started on the cases when one "file-less" cc_library depends on another file-less cc_library.
