### ISSUE TITLE
Add Multiplex Workers support for Android builds

### ISSUE THREAD

**Issue by nkoroste** [bazelbuild/bazel#10773]
### Description of the problem / feature request:

From what I can see from https://docs.bazel.build/versions/master/multiplex-worker.html and source code is that Multiplex Workers are only supported for Scala and maybe Java. It would be nice to get this support for Android build actions as well as Android builds tend to be large and slow. 

### Feature requests: what underlying problem are you trying to solve with this feature?

Improve Android's build performance.

### What operating system are you running Bazel on?

Linux & Mac

###  Have you found anything relevant by searching the web?

- https://docs.bazel.build/versions/master/multiplex-worker.html
- https://www.youtube.com/watch?v=MF2bahnAueM&list=PLxNYxgaZ8Rsf-7g43Z8LyXct9ax6egdSj&index=36&t=1339s
- https://stackoverflow.com/questions/58666030/gradle-vs-bazel-performance-of-builds/58667815#58667815

**Comment by jmmv** [comment]
This issue is specific about changing Android rules/workers to using multiplexing. The infrastructure changes are done, so this has nothing to do with local execution. (Nor remote execution.)

**Comment by larsrc-google** [comment]
If your Android workers are written in Java, take a look at [WorkRequestHandler](https://github.com/bazelbuild/bazel/blob/a4251eab6988d6cf4f5e35681fbe2c1b0abe48ef/src/main/java/com/google/devtools/build/lib/worker/WorkRequestHandler.java), a generic class to handle the request/response and multithreading parts of multiplexing. Of course, the worker itself needs to be thread-safe, including not sharing temp files between threads.
