### ISSUE TITLE
Visual Studio 2019 should be preferred over 2017

### ISSUE THREAD

**Issue by gjasny** [bazelbuild/bazel#10772]
### Description of the problem:

On my developer machine where Visual Studio 2017 and 2019 is co-installed Bazel 2.1.0 picks 2017. I would expect the newer (and of cause better) 2019 is used.

I believe it's related to this code comment:
https://github.com/bazelbuild/bazel/blob/2d1f3b905178663cfa2f1b973ff6c642c8789e74/tools/cpp/windows_cc_configure.bzl#L172

For VS2019 the registry key does not exist, therefore the loop and function returns once 2017 has been found.

IMHO the proper fix would be to check for the existence of `vswhere` and use it to query for Visual Studio installations with the C++ payload installed.

Do you think that would make sense and should I give it a try?

Thanks,
Gregor

CC: @laszlocsomor

**Comment by laszlocsomor** [comment]
Thanks for volunteering! Sounds great, let's do it! /cc @meteorcloudy 
Do I understand correctly that `vswhere` is installed with VS 2017 and newer?

**Comment by laszlocsomor** [comment]
For the record: to select a specific VS version for Bazel, use the `BAZEL_VC` and `BAZEL_VC_FULL_VERSION` envvars like so: https://docs.bazel.build/versions/2.1.0/windows.html#build-c-with-msvc

**Comment by shelllet** [comment]
BAZEL awaly use Visual Studio 2022,  even if i set BAZEL_VC BAZEL_VC_FULL_VERSION  to vs 2019。

**Comment by laszlocsomor** [comment]
@shelllet , try this in `cmd.exe`:

```
set CC_CONFIGURE_DEBUG=1

bazel --batch query @local_config_cc//...
```

What's the output?

**Comment by laszlocsomor** [comment]
Also, what does this print in `cmd.exe`?

```
set BAZEL_VC
```

**Comment by shelllet** [comment]
> Also, what does this print in `cmd.exe`?
> 
> ```
> set BAZEL_VC
> ```

BAZEL_VS 
![image](https://user-images.githubusercontent.com/16729017/140473817-0439cfc0-c1ba-4e2e-a055-b1fb04b44da0.png)

now i add `bazel_vc` and `bazel_vs`
![image](https://user-images.githubusercontent.com/16729017/140473988-3b320ae4-ff59-463c-9f48-c67d6ea53cad.png)

**Comment by shelllet** [comment]
> @shelllet , try this in `cmd.exe`:
> 
> ```
> set CC_CONFIGURE_DEBUG=1
> 
> bazel --batch query @local_config_cc//...
> ```
> 
> What's the output?

so many output messages

**Comment by shelllet** [comment]
is vcpkg's problem?

**Comment by laszlocsomor** [comment]
This error is interesting: Bazel client can't even start the server because the command is too long. So you don't get to the `local_config_cc` config step yet.

But in #14232 you wrote:
```
Auto-Configuration Error: Couldn't find undname.exe under C:\Program Files\Microsoft Visual Studio\2022\Community\VC, please check your VC installation and set BAZEL_VC environment variable correctly.
ERROR: Analysis of target '//tensorflow:tensorflow_cc.dll' failed; build aborted: Analysis failed
INFO: Elapsed time: 6.906s
```
which comes from the bazel server, so somehow you got past the "ERROR" point.

The command is long because Bazel is picking up a lot of settings from the bazelrc files. You can tell it to ignore rc files like so:

```
set CC_CONFIGURE_DEBUG=1

bazel --batch --ignore_all_rc_files query @local_config_cc//...
```

**Comment by shelllet** [comment]
if i manually build:

`bazel build //tensorflow/tools/pip_package:build_pip_package`

![image](https://user-images.githubusercontent.com/16729017/140479125-f176b00c-7d52-4200-835c-8f2cd000dcc7.png)

but `python3.exe` exit in that folder.

**Comment by laszlocsomor** [comment]
I think you're in the wrong directory. `x64-windows-dbg` looks like an output directory.
Change to the root directory of the Tensorflow source, i.e. the directory with the `WORKSPACE` file, and run Bazel from there.

For python, use a Windows-native Python3 binary, not an MSYS one.

**Comment by shelllet** [comment]
![image](https://user-images.githubusercontent.com/16729017/140481959-dc5ea079-ed00-4543-a850-db416cc65a25.png)

`WORKSPACE ` exist in `x64-windows-dbg`.

![image](https://user-images.githubusercontent.com/16729017/140482058-52b372ae-9840-47a9-86b6-bd66cc92f423.png)

![image](https://user-images.githubusercontent.com/16729017/140482385-80990b0c-75ed-4129-a878-8e9a1b0390b7.png)


seems `bazel script` can't get env variable value.

**Comment by shelllet** [comment]
Does bazel read the cached environment variables？

**Comment by laszlocsomor** [comment]
`PYTHON_BIN_PATH` must point to the binary itself, not just the directory containing it.

> Does bazel read the cached environment variables？

What do you mean by cached?

**Comment by laszlocsomor** [comment]
Hold on, my memory serves wrong. `PYTHON_BIN_PATH` doesn't seem to be used anywhere:

https://cs.opensource.google/search?q=PYTHON_BIN_PATH&ss=bazel%2Fbazel

**Comment by shelllet** [comment]
https://github.com/tensorflow/tensorflow/blob/master/third_party/py/python_configure.bzl

"""Repository rule for Python autoconfiguration.
`python_configure` depends on the following environment variables:
  * `PYTHON_BIN_PATH`: location of python binary.
  * `PYTHON_LIB_PATH`: Location of python libraries.
"""

**Comment by laszlocsomor** [comment]
There, "location of python binary", I think that means the binary itself, so `C:\users\admin\...\python39\python.exe` or whatever it is.

**Comment by shelllet** [comment]
> `PYTHON_BIN_PATH` must point to the binary itself, not just the directory containing it.
> 
> > Does bazel read the cached environment variables？
> 
> What do you mean by cached?

`bazel script` can't get the real env value , so i think it read value from another place .

**Comment by shelllet** [comment]
> There, "location of python binary", I think that means the binary itself, so `C:\users\admin\...\python39\python.exe` or whatever it is.
I have tried it, but I still get the same error
![image](https://user-images.githubusercontent.com/16729017/140484010-3ce933de-08c9-4184-b7e1-7ba618d86ce2.png)

**Comment by shelllet** [comment]
bazel script can't get the real env (`PYTHON_BIN_PATH`)  variable's value , 
the this same as `BAZEL_VC` and `BAZEL_VS` `BAZEL_VC_FULL_VERSION`.

**Comment by laszlocsomor** [comment]
From the `--define PYTHON_BIN_PATH=...` in the error message, I suspect something still picks up bazelrc files. Are you running Bazel with `--ignore_all_rc_files`?

Sorry, I probably can't help with Python problems.

To debug the VC version detection issue, try creating a clean Bazel workspace (= a new directory with an empty `WORKSPACE` and an empty `BUILD` file), and run the bazel query command I sent earlier from that directory.

**Comment by shelllet** [comment]
like this ? thks, i will try to create new directory and test.

![image](https://user-images.githubusercontent.com/16729017/140485920-18699e22-1fd5-47e8-9f1a-60da9a5ad859.png)

**Comment by laszlocsomor** [comment]
Ah, sorry if my instructions were misleading.

I meant using the `--ignore_all_rc_files` flag only for debugging why Bazel picks up the wrong VC version.

Don't use this flag if you're actually trying to build something. The bazelrc files _are_ necessary; but for debugging, i wanted to rule them out.

**Comment by shelllet** [comment]
i can't get more useful message from command `bazel --batch --ignore_all_rc_files query @local_config_cc//...`,  

becuase it faild to execute.
![image](https://user-images.githubusercontent.com/16729017/140489915-88b4e1f6-988f-425e-9d81-23e146c1c84b.png)

**Comment by laszlocsomor** [comment]
Yes, I think you need to try the query command in an empty workspace. (A directory with nothing but an empty `WORKSPACE` and `BUILD` file in it.)

**Comment by JackBoosY** [comment]
The question is why `undname` is not found in the Visual Studio 2022 directory.
I think it is correct for Bazel to use 2022 first, but there are the above problems.

**Comment by shelllet** [comment]
`windows_cc_configure.bzl`  does not seem to support vs2022. is this cause the above problem?

code snippet.
```
  for path in [
        "Microsoft Visual Studio\\2019\\Preview\\VC",
        "Microsoft Visual Studio\\2019\\BuildTools\\VC",
        "Microsoft Visual Studio\\2019\\Community\\VC",
        "Microsoft Visual Studio\\2019\\Professional\\VC",
        "Microsoft Visual Studio\\2019\\Enterprise\\VC",
        "Microsoft Visual Studio\\2017\\BuildTools\\VC",
        "Microsoft Visual Studio\\2017\\Community\\VC",
        "Microsoft Visual Studio\\2017\\Professional\\VC",
        "Microsoft Visual Studio\\2017\\Enterprise\\VC",
        "Microsoft Visual Studio 14.0\\VC",
    ]:
```

```
def _is_vs_2017_or_2019(vc_path):
...
```

**Comment by JackBoosY** [comment]
> @andrewkatson It looks like we don't have proper support for Vs2022 yet, can you help look into this?

See log content:
```
Auto-Configuration Error: Couldn't find undname.exe under C:\Program Files\Microsoft Visual Studio\2022\Community\VC, please check your VC installation and set BAZEL_VC environment variable correctly.
ERROR: Analysis of target '//tensorflow:tensorflow_cc.dll' failed; build aborted: Analysis failed
```
Please note The Visual Studio 2022 path `C:\Program Files\Microsoft Visual Studio\2022\Community\VC` is correct.

**Comment by meteorcloudy** [comment]
@JackBoosY Thanks! Have you figured out why undname.exe no longer exists in VS 2022? 
It's needed to build TensorFlow on Windows: https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/tools/def_file_filter/def_file_filter_configure.bzl;l=35?

**Comment by JackBoosY** [comment]
@meteorcloudy 
See my comment https://github.com/bazelbuild/bazel/issues/10772#issuecomment-962924219

![image](https://user-images.githubusercontent.com/47264268/140721746-70dfb0d7-6a41-439e-aaa4-3ac17e250736.png)

Please note the relative path of undname in Visual Studio has never been changed.

**Comment by meteorcloudy** [comment]
Oh, I see, then `find_vc_path` must have returned the wrong result. Can you show me what's under the VS 2022 path?
Maybe the directory structure changed again?
https://github.com/bazelbuild/bazel/blob/master/tools/cpp/windows_cc_configure.bzl#L260

**Comment by JackBoosY** [comment]
@meteorcloudy  As I said, the path structure of all files has not changed.

**Comment by SuperKogito** [comment]
**The path is actually different.** 
Although, Bazel does not account for VS2022 yet but the if condition for VS2017 and VS2019 can still do the trick. 
The **difference** between the old version and the new version is the `../Hostx64/..` label. This is lowercase in your case for example and mine too (VS2022). However, [the windows_cc_configure.bz script: line 325](https://github.com/bazelbuild/bazel/blob/9c96529fca4a135c162e35ce2882834b879438fb/tools/cpp/windows_cc_configure.bzl#L325C1-L326C1) looks for an uppercase `../HostX64/..` label. 

The solution here is either to edit ../Hostx64/.. label (https://github.com/bazelbuild/bazel/blob/9c96529fca4a135c162e35ce2882834b879438fb/tools/cpp/windows_cc_configure.bzl#L325C1-L326C1) and change the lines to 

```python3
    if _is_vs_2017_or_2019(repository_ctx, vc_path):
        lib = msvc_vars_x64["%{msvc_env_lib_x64}"]
        full_version = _get_vc_full_version(repository_ctx, vc_path)
        tools_path = "%s\\Tools\\MSVC\\%s\\bin\\Hostx64\\%s" % (vc_path, full_version, target_arch)

        # For native windows(10) on arm64 builds host toolchain runs in an emulated x86 environment
        if not repository_ctx.path(tools_path).exists:
            tools_path = "%s\\Tools\\MSVC\\%s\\bin\\Hostx86\\%s" % (vc_path, full_version, target_arch)
```

or you rename `\bin\\Hostx64\\` to `\bin\\HostX64\\`


also it is vital that these environment variables point to the right paths: 
```
BAZEL_SH=C:\msys64\usr\bin\bash.exe
BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC
BAZEL_VC_FULL_VERSION=14.36.32532
```


This was tested with:
Windows 10
Bazel 6.2.1
Python 3.9.7
Tensorflow 2.12

**Comment by JackBoosY** [comment]
cc @Cheney-W to check this path.
