### ISSUE TITLE
default build/test options?

### ISSUE THREAD

**Issue by cnsgsz** [bazelbuild/bazel#1079]
is there some setting/config to enable c++14 for example? rather than doing the following:

> bazel build //source/...:all --cxxopt "-std=c++14"

**Comment by Limdi** [comment]
Bazel configuration file(bazelrc) could be usefull.

One of the first topics here:
http://bazel.io/docs/bazel-user-manual.html

Try to put `build --cxxopt "-std=c++14"` into a .bazelrc at the root of your workspace or somewhere else.
