### ISSUE TITLE
Bazel docs M1 - tracking issue

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel#10790]
A focus group is forming to improve Bazel's documentation and provide guidance on doc contributions (like where to put a new page on topic X).

Doc work is a long-term effort. Some of this needs to be considered carefully and with an eye toward long-term sustainability. For example, every new URL implies a commitment to resolving that URL forever.

In that spirit we want to break doc work into incremental milestones aimed at achieving the best balance of regular improvement and sustainability.

----

This issue tracks **milestone M1**:

- **Scope:** All improvements we can make *now* that won't complicate long-term plans.
- **Timeline:** O(weeks). Push out *soon* without getting bogged down in analysis paralysis.
- **Rationale:** There's some obvious pain in the current docs and obvious benefit by relieving that pain *now*. Even the very act of an update - even if not comprehensive - shows evidence of a living and breathing ecosystem and promise of more.

We'll try to release all M1 changes simultaneously as a combined update. This may not be 100% possible due to versioned docs.

Track the milestone at https://github.com/bazelbuild/bazel/milestone/19.

This issue is considered closed when all other issues in the milestone are complete.

**Comment by jin** [comment]
Update for M1: The content refreshes, cleanup and site redesign are now complete. The only remaining piece of work is to roll out a centralized configuration model of all of our sites.

**Comment by aiuto** [comment]
Can we add moving to docsy as an M1 goal?

**Comment by gregestren** [comment]
Jin and I met today to exactly discuss M1 and what follows.

The momentum has been not to prioritize a tech stack change now. Especially
as Danielle is onboarding broader organizational work. It still isn’t even
clear Docsy is the group consensus.

Feel free to join our next docs chat if you’d like to pursue this question
further (same offer goes to anyone else reading this who has questions
about docs evolution).

**Comment by jin** [comment]
All issues in milestone 1 are complete \o/ https://github.com/bazelbuild/bazel/milestone/19?closed=1

Closing this now!
