### ISSUE TITLE
cc_library()  import precompiled shared libraries to a temp directory caused error while loading shared libraries

### ISSUE THREAD

**Issue by Mycaster** [bazelbuild/bazel#10803]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:
I'm trying to build a simple pytorch example with bazel, libtorch is a third precompiled shared library, the cmake example is [here](https://pytorch.org/tutorials/advanced/cpp_frontend.html)
 
and I found the doc here to add dependencies on precompiled-libraries with cc_library() 
[adding-dependencies-on-precompiled-libraries](https://docs.bazel.build/versions/2.0.0/cpp-use-cases.html#adding-dependencies-on-precompiled-libraries)

here is my Project Tree:
```
root@4bf9f1d29891:/libtorch/bazel-example# tree -L 1  *
example
├── BUILD
└── torch-example.cc
libtorch
├── BUILD
├── include
├── lib
WORKSPACE
```

and libtorch/BUILD file
```
root@4bf9f1d29891:/libtorch/bazel-example# cat libtorch/BUILD
package(
    default_visibility = ["//visibility:public"],
)
licenses(["notice"])  # BSD
exports_files(["LICENSE"])

TORCH_HEADERS = glob([
    "include/**/*.h",
])

TORCH_LIBRARIES = [
    "lib/libtorch.so",
    "lib/libc10_cuda.so",
    "lib/libc10.so",
    "lib/libcudart.so.10.1",
    "lib/libcudart-1b201d85.so.10.1",
    "lib/libnvToolsExt-3965bdd0.so.1",
]

cc_library(
    name = "libtorch",
    srcs = TORCH_LIBRARIES,
    hdrs = TORCH_HEADERS,
    includes = ["include", "include/torch/csrc/api/include"],
    linkopts = ["-lpthread"],
)
```

example/BUILD file:
```
root@4bf9f1d29891:/libtorch/bazel-example# cat example//BUILD
cc_binary(
    name = "torch-example",
    srcs = ["torch-example.cc"],
    deps = [
        "//libtorch:libtorch",
    ],
)
```

then I run 
```
bazel build  --verbose_explanations --color=yes --curses=yes   --verbose_failures  -s example:torch-example
```
**build success and run bazel-bin/example/torch-example success.**

However , when I copy `bazel-bin/example/torch-example` to `/usr/bin/torch-example`, 
it's not work:
```
root@4bf9f1d29891:/libtorch/bazel-example# torch-example
torch-example: error while loading shared libraries: libtorch.so: cannot open shared object file: No such file or directory
```

It's the difference ldd result between two same BinraryFiles :
```
root@4bf9f1d29891:/libtorch/bazel-example# ldd bazel-bin/example/torch-example
	linux-vdso.so.1 =>  (0x00007fffba570000)
	libtorch.so => /libtorch/bazel-example/bazel-bin/example/../_solib_k8/_U_S_Slibtorch_Clibtorch___Ulibtorch_Slib/libtorch.so (0x00007fcfbf6f1000)
	libc10_cuda.so => /libtorch/bazel-example/bazel-bin/example/../_solib_k8/_U_S_Slibtorch_Clibtorch___Ulibtorch_Slib/libc10_cuda.so (0x00007fcfbf4ba000)
	libc10.so => /libtorch/bazel-example/bazel-bin/example/../_solib_k8/_U_S_Slibtorch_Clibtorch___Ulibtorch_Slib/libc10.so (0x00007fcfbf26c000)
	libcudart.so.10.1 => /libtorch/bazel-example/bazel-bin/example/../_solib_k8/_U_S_Slibtorch_Clibtorch___Ulibtorch_Slib/libcudart.so.10.1 (0x00007fcfbefed000)
==============================
root@4bf9f1d29891:/libtorch/bazel-example# ldd /usr/bin/torch-example
	linux-vdso.so.1 =>  (0x00007ffd73782000)
	libtorch.so => not found
	libc10_cuda.so => not found
	libc10.so => not found
	libcudart.so.10.1 => not found
```

I recognize that bazel build will copy the precompiled library to bazel-bin/_solib_k8/XXXX/...
and locate the library when link.

then I tried to use absolute path to declare where library is ,but  it's not permitted.

also I tried to add linkopts=["-Wl,rpath,/usr/local/libpytorch/"], it's not work too.

So How Can I import the precompiled shared library and keep the Binrary can run everywhere???

### What operating system are you running Bazel on?
 Ubuntu

### What's the output of `bazel info release`?

release 0.24.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by oquenchil** [comment]
Since you moved the binary file, then it won't find the shared libraries where it expects them.

Please look at [cc_import](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_import), maybe it lets you do what you want.

Alternatively, see [this answer](https://stackoverflow.com/a/43225747) on StackOverflow:
