### ISSUE TITLE
Bazel CI: Gerrit and Kythe are broken with Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#10802]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1390

Gerrit:
```
javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
```

Kythe: [log](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/849b1e48-6bc4-4ade-9759-05713006f815/kythe/javatests/com/google/devtools/kythe/extractors/java/java_extractor_test/attempt_1.log)

Culprit: 8b1ef42bef4fca4e5b33f9a2d5ea5ea07c004d8d
https://buildkite.com/bazel/culprit-finder/builds/255
https://buildkite.com/bazel/culprit-finder/builds/256

/cc @davido @shahms

**Comment by philwo** [comment]
Interesting 🤔 This change only bumped the host JDKs from 11.0.1 or 11.0.3 to 11.0.6.

Googling for the error message shows that other projects (unrelated to Bazel) also ran into this issue with newer JDK versions. Maybe the bumped JDK is somehow stricter than the old when when it comes to this check?

**Comment by meteorcloudy** [comment]
Yeah, looks like this is an incompatible change from the JDK side.

@davido @shahms Can you help fixing this issue from Gerrit and Kythe side?

**Comment by davido** [comment]
@meteorcloudy Thanks, for reporting, will investigate it later today.

**Comment by davido** [comment]
I just sent the fix CL: [1].

[1] https://github.com/bazelbuild/bazel/issues/10802

**Comment by marco-miller** [comment]
> I've just sent the fix CL: [1]. It is still pending for review, though.
> 
> [1] https://gerrit-review.googlesource.com/c/gerrit/+/255454

Done. Reviewed, merged now.

**Comment by meteorcloudy** [comment]
@davido Thanks for the fix!

**Comment by shahms** [comment]
Happy to take a look at this for Kythe.

**Comment by shahms** [comment]
Please let me know whether or not that addresses the issue.

**Comment by meteorcloudy** [comment]
The is now fixed, thanks!
