### ISSUE TITLE
Building Bazel fails on Windows: package does not exist

### ISSUE THREAD

**Issue by 01ken** [bazelbuild/bazel#1080]
When I try to build bazel on Window7 machine, Building Bazel with Bazel fails as shown in the logs below.
Errors are "package ~ does not exist" and "cannot find symbol".

`$ ./compile.sh
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
INFO: Found 1 target...
ERROR: C:/tools/msys64/home/user/bazel/src/java_tools/junitrunner/java/com/google/testing/junit/runner/sharding/api/BUILD:11:1: Java compilation in rule '//src/java_tools/junitrunner/java/com/google/testing/junit/runner/sharding/api:api' failed: Worker process sent response with exit code: 1.
src\java_tools\junitrunner\java\com\google\testing\junit\runner\sharding\api\ShardingFilterFactory.java:17: エラー: パッケージorg.junit.runnerは存在しません
import org.junit.runner.Description;
                       ^
src\java_tools\junitrunner\java\com\google\testing\junit\runner\sharding\api\ShardingFilterFactory.java:18: エラー: パッケージorg.junit.runner.manipulationは存在しません
import org.junit.runner.manipulation.Filter;
                                    ^
src\java_tools\junitrunner\java\com\google\testing\junit\runner\sharding\api\ShardingFilterFactory.java:35: エラー: シンボルを見つけられません
  Filter createFilter(Collection<Description> testDescriptions, int shardIndex, int totalShards);
                                 ^
  シンボル:   クラス Description
  場所: インタフェース ShardingFilterFactory
src\java_tools\junitrunner\java\com\google\testing\junit\runner\sharding\api\ShardingFilterFactory.java:35: エラー: シンボルを見つけられません
  Filter createFilter(Collection<Description> testDescriptions, int shardIndex, int totalShards);
  ^
  シンボル:   クラス Filter
  場所: インタフェース ShardingFilterFactory
src\java_tools\junitrunner\java\com\google\testing\junit\runner\sharding\api\WeightStrategy.java:17: エラー: パッケージorg.junit.runnerは存在しません
import org.junit.runner.Description;
                       ^
src\java_tools\junitrunner\java\com\google\testing\junit\runner\sharding\api\WeightStrategy.java:29: エラー: シンボルを見つけられません
  int getDescriptionWeight(Description description);
                           ^
  シンボル:   クラス Description
  場所: インタフェース WeightStrategy
エラー6個
BazelJavaBuilder threw exception: java compilation returned status ERROR
Target //src:bazel.exe failed to build
INFO: Elapsed time: 37.241s, Critical Path: 29.52s

Building output/bazel
`

**Comment by damienmg** [comment]
Can we have the error message in non japanese, or maybe @philwo can understand them?

**Comment by damienmg** [comment]
oops sorry saw there was the error message at the top. it looks like junit is not linked with sharding.
A small though: maybe we should deactivate workers build on windows for now?

Assigning to @dslomov for further assistance.

**Comment by damienmg** [comment]
@dslomov ping?

**Comment by damienmg** [comment]
Inactive bug, closing. Windows support is still experimental sorry for that,
