### ISSUE TITLE
toolchain: provide clang toolchain on mingw out of the box

### ISSUE THREAD

**Issue by oakad** [bazelbuild/bazel#10810]
On Windows, bazel provides the following toolchains:

- mingw-gcc (with variants)
- msvc-cl
- clang-cl

What is missing is mingw-clang.

Why is it necessary?

Many useful programs are designed in posix-y fashion for portability reasons (thus, mingw), but need to link to native windows dlls. Increasing number of dlls these days relies on `vectorcall` calling convention, which is not supported by gcc (and it is not obvious what the timeline for support is). 

Fortunately, clang on mingw supports `vectorcall` just fine and thus constitutes the only usable option for programs like described.

**Comment by aiuto** [comment]
This belongs in https://github.com/bazelbuild/rules_cc/issues.
Contributions there are welcome.

**Comment by laszlocsomor** [comment]
@oakad : I believe the toolchain is missing simply because we never added it. I don't know of a technical reason against it. @meteorcloudy may know more.

@aiuto: AFAIK toolchain autodetection is still done inside Bazel (see `windows_cc_configure.bzl`). Why does this issue belong to rules_cc?

**Comment by meteorcloudy** [comment]
Hi @oakad , I believe this is doable with the current toolchain support in Bazel. I currently don't see a high demand for this feature. I wonder if you want to write a toolchain to support mingw-clang? I am not quite familiar with how clang works with mingw, but happy to do give some advice on writing cc toolchain for Windows.

**Comment by aiuto** [comment]
@oakad If you want to send a PR for this, that would be great, but it's low down on the bazel team's priority list.

**Comment by oakad** [comment]
I have hacked a toolchain config for that, but I'm afraid it's not of a PR quality, despite being quite useful. :(
