### ISSUE TITLE
Add support for Android NDK r21

### ISSUE THREAD

**Issue by hevrard** [bazelbuild/bazel#10811]
### Description of the problem / feature request:

Add support for Android NDK r21, which is the latest stable NDK.
https://developer.android.com/ndk/downloads

### Feature requests: what underlying problem are you trying to solve with this feature?

Among other things, this allow to use the Khronos unified Vulkan validation layer, which ships with NDK r21.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try to compile any Android project with NDK r21, you get the following warning:

```
WARNING: The major revision of the Android NDK referenced by
android_ndk_repository rule 'androidndk' is 21. The major revisions
supported by Bazel are [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20].
Bazel will attempt to treat the NDK as if it was r20. This may cause
compilation and linkage problems. Please download a supported
NDK version.
```

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 2.0.0

Given that Android NDK r21 support is nowhere to be seen on https://blog.bazel.build/2020/02/06/bazel-2.1.html, I guess it is not supported yet.

**Comment by hevrard** [comment]
For information, AGI https://github.com/google/agi compiles fine with NDK r21 and Bazel 2.0.0, so maybe there is no significant changes from r20 to r21 w.r.t. how Bazel treats the NDK.

**Comment by hevrard** [comment]
@jin thanks for your help on #10095 , what do you think is necessary to get NDK r21 in the list of the officially supported NDK versions?

For info we've been building AGI with Bazel 2.0.0 and NDK r21 for months now, without any issue.

**Comment by jin** [comment]
It's a matter of doing something like https://github.com/bazelbuild/bazel/commit/00e29b7cd80df6a2762bc8b4b035f5a99466f5f6, but following the [NDK for Build System Maintainer's guide](https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md) to make any changes for r21 if needed. If there are no changes needed, it could just be a one line change like this, where r20 reuses r19's cc toolchain configuration with a different clang version: https://github.com/bazelbuild/bazel/commit/00e29b7cd80df6a2762bc8b4b035f5a99466f5f6#diff-5e296871cb2f862994716d4195ab0016R55

I personally don't have the resources to work on this now. If you'd like to take it on, I can help to review changes.

**Comment by UebelAndre** [comment]
Any updates here?

**Comment by steeve** [comment]
I have opened a PR. I'm using r21 with Bazel 3.4.1 without issues myself, so I just added the necessary boilerplate based on @jin's comments.
