### ISSUE TITLE
Code coverage: JDK in the host system required to run

### ISSUE THREAD

**Issue by dbacchet-voyage** [bazelbuild/bazel#10825]
### Description of the problem / feature request:

do not depend on external JDK for code coverage, and use the one fetched by bazel itself.

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm generating code coverage info for a c++ project, and I had this failure at the beginning:
```
bazel coverage //...

Exception in thread "main" java.lang.IllegalArgumentException: external/local_jdk
        at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.isCurrentPlatform(Locations.java:1862)
(...)
        at DumpPlatformClassPath.main(DumpPlatformClassPath.java:67)
Caused by: java.nio.file.NoSuchFileException: external/local_jdk
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
(...)
        ... 14 more
```

I tracked down the problem to the fact that the external/local_jdk points to the root of the workspace when I don't have a JDK installed in the system (ubuntu 16.04 and 18.04 in my case).
When I install openjdk then everything works as expected.

Question: _since bazel is already fetching JDKs, why does it need to rely on having one installed in the host system when using the coverage option?_

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

A repository to reproduce the problem (with docker) is here: https://github.com/dbacchet/bazel-coverage-example

* checkout branch `without-jdk`
* run `docker/run.sh`
* `cd /code`
* `bazel coverage //...`

The same procedure on the `master` branch (that has the JDK installed in the container) works fine.

Also the same problem happens if I use the --experimental_cc_coverage flags, like the following:
```
bazel coverage --instrument_test_targets --experimental_cc_coverage --combined_report=lcov --coverage_report_generator=@bazel_tools//tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator:Main //...
```

### What operating system are you running Bazel on?

Linux Ubuntu 18.04

### What's the output of `bazel info release`?

`release 2.0.0`

**Comment by comius** [comment]
The culprit is `@bazel_tools//tools/test:coverage_report_generator`, which is written in Java.

Bazel defaults to execute code with local JDK (to prevent failures when user upgrades Bazel version).

You can use `--java_runtime_version=remotejdk` (Bazel@HEAD) or `--javabase=@remotejdk11_linux//:jdk` to use remote JDK also for execution and you won't need to install JDK locally.
