### ISSUE TITLE
http_cache doesn't work well with undeclared inclusion(s) (MSVC)

### ISSUE THREAD

**Issue by carpenterjc** [bazelbuild/bazel#10822]
### Description of the problem / feature request:

The inclusion detection system relies on MSVC outputting a file with where it picks up headers from. This file can sometimes contain the full path to the include it picks up. When you then have an incremental build after the fact these files can be downloaded from the cache and analyzed, at which point they will not match the expected paths on a machine with a different username.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run a MSVC build with a remote cache with one user.
Look in that cache and you will find the action_outs for the MSVC compile stage. In this file is the full path to the execroot. It should be a relative path. 

### What operating system are you running Bazel on?

Windows 10 / 2019 Core

### What's the output of `bazel info release`?

release 0.28.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.
N/A
### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
N/A

### Any other information, logs, or outputs that you want to share?

If there are partial misses in the cache you get the following error...

ERROR: C:/<path on machine>/BUILD:10:1: undeclared inclusion(s) in rule '//target':
this rule is missing dependency declarations for the following files included by 'target/auth.pb.cc':
  'C:/users/administrator/_bazel_administrator/hrm3ueym/execroot/ssp/src/sxl4protobuflib/auth.pb.h'
  'C:/users/administrator/_bazel_administrator/hrm3ueym/execroot/ssp/bazel-out/host/bin/imports/thirdparty/protobuf/_virtual_includes/protobuf/google/protobuf/stubs/common.h' 
  'C:/users/administrator/_bazel_administrator/hrm3ueym/execroot/ssp/bazel-out/host/bin/imports/thirdparty/protobuf/_virtual_includes/protobuf/google/protobuf/stubs/port.h'   
  'C:/users/administrator/_bazel_administrator/hrm3ueym/execroot/ssp/bazel-out/host/bin/imports/thirdparty/protobuf/_virtual_includes/protobuf/google/protobuf/stubs/platform_macros.h'
  'C:/users/administrator/_bazel_administrator/hrm3ueym/execroot/ssp/bazel-out/host/bin/imports/thirdparty/protobuf/_virtual_includes/protobuf/google/protobuf/stubs/macros.h' 
  'C:/users/administrator/_bazel_administrator/hrm3ueym/execroot/ssp/bazel-out/host/bin/imports/thirdparty/protobuf/_virtual_includes/protobuf/google/protobuf/stubs/logging.h'  'C:/users/administrator/_bazel_administrator/hrm3ueym/execroot/ssp/bazel-out/host/bin/imports/thirdparty/protobuf/_virtual_includes/protobuf/google/protobuf/stubs/mutex.h'  
  'C:/users/administrator/_bazel_administrator/hrm3ueym/execroot/ssp/bazel-out/host/bin/imports/thirdparty/protobuf/_virtual_includes/protobuf/google/protobuf/stubs/callback.h

Note the path "C:/users/administrator/" does not exist on the development machine, only on the build server. 

C:\dev\src\ssp\bazel-ssp\bazel-out\_tmp\action_outs\stdout-11-0-0

**Comment by meteorcloudy** [comment]
I thought this problem has already been fixed by https://github.com/bazelbuild/bazel/pull/6931 and https://github.com/bazelbuild/bazel/pull/9188.

The second PR is only released in 1.0.0, so can you try with a newer Bazel version?

**Comment by carpenterjc** [comment]
Currently upgraded my client to 2.0.0, I am testing now.

**Comment by carpenterjc** [comment]
I can't reproduce the current problem and have been running the original scenario that was causing me problems for a while.
