### ISSUE TITLE
Bazel CI: Tuisi is broken in downstream

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#10829]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1396#6d535840-9576-4458-b164-b7179038d561
```
//src/TulsiGeneratorIntegrationTests:AspectTests                         FAILED in 3 out of 3 in 37.5s
//src/TulsiGeneratorIntegrationTests:EndToEndGenerationTests             FAILED in 3 out of 3 in 61.1s
```
Culprit is 43c029f1049fa189e2016a062258ffa915ebc4fb
Culprit finder: https://buildkite.com/bazel/culprit-finder/builds/270

**Comment by googlewalt** [comment]
This is expected.  The Tulsi tests need to be remastered for this change, but the remastered tests would then break without the change.  I'm checking with the Tulsi team to see how to proceeded.
