### ISSUE TITLE
Do ObjC rules handle --cpu + select() differently?

### ISSUE THREAD

**Issue by scottcjt** [bazelbuild/bazel#10836]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

For the following BUILD file on a Macbook:

```python
config_setting(
    name = "macos",
    values = {
        "apple_platform_type": "macos",
        "cpu": "darwin",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "ios",
    values = {"apple_platform_type": "ios"},
    visibility = ["//visibility:public"],
)

cc_library(
    name = "foo",
    srcs = select({
        ":macos": ["xxx"],
        ":ios": ["yyy"],
    }),
)

objc_library(
    name = "bar",
    srcs = select({
        ":macos": ["xxx"],
        ":ios": ["yyy"],
    }),
)
```

If with `bazel build :foo`, bazel correctly takes "xxx" and complains about "xxx" does not exist.

However if `bazel build :bar`, bazel will complains about this:

```
Configurable attribute "srcs" doesn't match this configuration (would a default condition help?).
Conditions checked:
 //:macos
 //:ios
```

Which means no condition fulfills. This is inconsistent with the `:foo` target.

### Feature requests: what underlying problem are you trying to solve with this feature?

Bazel should have consistent behavior on different rules, or there should be document at clear location...since I did not find it.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Copying lines above into empty BUILD files, in an empty folder, `touch WORKSPACE` and run:

```shell
bazelisk build :foo
bazelisk build :bar
```

### What operating system are you running Bazel on?

MacOS 10.15.3.

### What's the output of `bazel info release`?

release 2.1.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

No. Note that I launch it with `bazelisk`.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Unrelated with this issue.

###  Have you found anything relevant by searching the web?

There are some discussions about internal design migration? But I am not sure if they are relevant.

**Comment by scottcjt** [comment]
@aiuto IMHO this is a bug. It has undefined behavior beyond what document says. It also cripples platform selection on all objective-c rules between MacOS and Linux.

**Comment by katre** [comment]
The allowable values for `cpu` are actually based on the cc crosstool being used. Are you using the automatic OSX toolchain that Bazel provides, or have you supplied your own?

**Comment by scottcjt** [comment]
@katre I am not sure if Bazel downloads another gcc/clang without notifying. I expect toolchain from XCode is being picked up since I did not do any toolchain setup. Does that help figure out the environment?

**Comment by katre** [comment]
Please run this and share your output:
```
bazel query --output=build @local_config_cc//:toolchain
```

This will output the default toolchain you are using, if you're not setting the `--crosstool_top` flag.

**Comment by scottcjt** [comment]
Sure.

```
scottcjt@mbp ~/xd> bazelisk query --output=build @local_config_cc//:toolchain
# /private/var/tmp/_bazel_scottcjt/d2e19d54de72f484fdf2a7458960f7cc/external/local_config_cc/BUILD:41:1
cc_toolchain_suite(
  name = "toolchain",
  tags = ["__CC_RULES_MIGRATION_DO_NOT_USE_WILL_BREAK__"],
  generator_name = "toolchain",
  generator_function = "cc_toolchain_suite",
  generator_location = "/private/var/tmp/_bazel_scottcjt/d2e19d54de72f484fdf2a7458960f7cc/external/local_config_cc/BUILD:41",
  toolchains = {"armeabi-v7a|compiler": "@local_config_cc//:cc-compiler-armeabi-v7a", "ios_armv7|compiler": "@local_config_cc//:cc-compiler-ios_armv7", "ios_arm64|compiler": "@local_config_cc//:cc-compiler-ios_arm64", "ios_arm64e|compiler": "@local_config_cc//:cc-compiler-ios_arm64e", "watchos_armv7k|compiler": "@local_config_cc//:cc-compiler-watchos_armv7k", "watchos_arm64_32|compiler": "@local_config_cc//:cc-compiler-watchos_arm64_32", "tvos_arm64|compiler": "@local_config_cc//:cc-compiler-tvos_arm64", "darwin_x86_64|compiler": "@local_config_cc//:cc-compiler-darwin_x86_64", "ios_i386|compiler": "@local_config_cc//:cc-compiler-ios_i386", "ios_x86_64|compiler": "@local_config_cc//:cc-compiler-ios_x86_64", "watchos_i386|compiler": "@local_config_cc//:cc-compiler-watchos_i386", "watchos_x86_64|compiler": "@local_config_cc//:cc-compiler-watchos_x86_64", "tvos_x86_64|compiler": "@local_config_cc//:cc-compiler-tvos_x86_64", "armeabi-v7a": "@local_config_cc//:cc-compiler-armeabi-v7a", "ios_armv7": "@local_config_cc//:cc-compiler-ios_armv7", "ios_arm64": "@local_config_cc//:cc-compiler-ios_arm64", "ios_arm64e": "@local_config_cc//:cc-compiler-ios_arm64e", "watchos_armv7k": "@local_config_cc//:cc-compiler-watchos_armv7k", "watchos_arm64_32": "@local_config_cc//:cc-compiler-watchos_arm64_32", "tvos_arm64": "@local_config_cc//:cc-compiler-tvos_arm64", "darwin_x86_64": "@local_config_cc//:cc-compiler-darwin_x86_64", "ios_i386": "@local_config_cc//:cc-compiler-ios_i386", "ios_x86_64": "@local_config_cc//:cc-compiler-ios_x86_64", "watchos_i386": "@local_config_cc//:cc-compiler-watchos_i386", "watchos_x86_64": "@local_config_cc//:cc-compiler-watchos_x86_64", "tvos_x86_64": "@local_config_cc//:cc-compiler-tvos_x86_64", "k8|compiler": "@local_config_cc//:cc-compiler-darwin_x86_64", "darwin|compiler": "@local_config_cc//:cc-compiler-darwin_x86_64", "k8": "@local_config_cc//:cc-compiler-darwin_x86_64", "darwin": "@local_config_cc//:cc-compiler-darwin_x86_64"},
)

Loading: 0 packages loaded
```

**Comment by katre** [comment]
So, based on the value of the `toolchains` attribute, you have the following valid CPU values:
- `armeabi-v7a|compiler`
- `ios_armv7|compiler`
- `ios_arm64|compiler`
- `ios_arm64e|compiler`
- `watchos_armv7k|compiler`
- `watchos_arm64_32|compiler`
- `tvos_arm64|compiler`
- `darwin_x86_64|compiler`
- `ios_i386|compiler`
- `ios_x86_64|compiler`
- `watchos_i386|compiler`
- `watchos_x86_64|compiler`
- `tvos_x86_64|compiler`
- `armeabi-v7a`
- `ios_armv7`
- `ios_arm64`
- `ios_arm64e`
- `watchos_armv7k`
- `watchos_arm64_32`
- `tvos_arm64`
- `darwin_x86_64`
- `ios_i386`
- `ios_x86_64`
- `watchos_i386`
- `watchos_x86_64`
- `tvos_x86_64`
- `k8|compiler`
- `darwin|compiler`
- `k8`
- `darwin`

(The `|compiler` syntax means that to select that toolchain, you would need to set both `--cpu` and `--compiler=compiler`. This isn't a common use and I wonder if it is intentional, but the Apple rules team is responsible for those.)

To get back to your original question, it looks like `darwin` is a valid option for `--cpu`, but may not be the default you have set. I don't actually know what the default value for `--cpu` is on macOS, unfortunately.

**Comment by scottcjt** [comment]
> To get back to your original question, it looks like `darwin` is a valid option for `--cpu`, but may not be the default you have set. I don't actually know what the default value for `--cpu` is on macOS, unfortunately.

But it seems that for the `cc_library` rule, assuming default cpu=`darwin` works correctly. If I change the **cpu** arg in `config_setting(name = "macos")` to another arbitary value and try `bazel build :foo`, I get different error.

I can't stop thinking that Objective-C rules are somewhat different when handling these options.

**Comment by katre** [comment]
I think you're right, so the owners of `objc_library` need to comment.

I'm sorrt this keeps getting passed around, the intersection of rules and `config_setting` gets complicated sometimes.

**Comment by scottcjt** [comment]
No problem, thanks.

**Comment by cpsauer** [comment]
Hey, all. Not an objc_library owner or blocked by this, but I ran across this page and got curious, so I dumped the config.

Problem still repros in the latest Bazel rolling (6.0.0-pre.20220112.2)

The config shows the objc_library has automagically changed the cpu to "darwin_x86_64" (at least on my Intel-based Mac), causing the match to fail. Probably has to do with the magic/strangeness of --cpu=darwin being a catchall, especially in the absence of any 32bit macs still being supported.

Some more leads on that:
https://github.com/bazelbuild/bazel/pull/7062
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/apple/ApplePlatform.java#L59 (By MACOS_TARGET_CPUS)

I assume @scottcjt is long gone or worked around the issue, but I'm pretty sure that's the cause.

---
Quick repro instructions for anyone else interested:
Grab this workspace: [bazeltest.zip](https://github.com/bazelbuild/bazel/files/7902765/bazeltest.zip)

```
bazel build :foo
bazel build :bar
```
Then run the `bazel config <ID>` command in the error message, and search for "cpu: "

**Comment by scottcjt** [comment]
@cpsauer This explanation sounds quite reasonable. Yes I already worked around it, but still thank you for figuring out.
