### ISSUE TITLE
Prepare java_import_external for --incompatible_load_java_rules_from_bzl option flip, continued

### ISSUE THREAD

**Issue by cpovirk** [bazelbuild/bazel#10838]
https://github.com/bazelbuild/bazel/issues/10046 / https://github.com/bazelbuild/bazel/commit/16c4ce47f26be7b8392ba9bc94bc209613eba6c3 appears to have fixed **jvm_maven**_import_external but not **java**_import_external. As a result, I am still seeing "Please load java_import from the rules_java repository." errors with `java_import_external` under Bazel 2.1.0.

It looks like `java_import_external` should pass in the same `load` line as `jvm_maven_import_external` now does:

```py
        rule_load = """load("@rules_java//java:defs.bzl", "java_import")""",
```

(But it should have the same logic to respect a value passed by the caller, too.)

As a workaround, callers of `java_import_external` can pass that line manually.

**Comment by lberki** [comment]
We gave up on that flag :(
