### ISSUE TITLE
--incompatible_load_java_rules_from_bzl breaks some bazel_tools BUILD files

### ISSUE THREAD

**Issue by cpovirk** [bazelbuild/bazel#10839]
```
ERROR: .../external/bazel_tools/src/java_tools/import_deps_checker/java/com/google/devtools/build/importdeps/BUILD:3:1: in java_import rule @bazel_tools//src/java_tools/import_deps_checker/java/com/google/devtools/build/importdeps:import_deps_checker_deploy_jar: The native Java rules are deprecated. Please load java_import from the rules_java repository. See http://github.com/bazelbuild/rules_java and https://github.com/bazelbuild/bazel/issues/8741. You can temporarily bypass this error by setting --incompatible_load_java_rules_from_bzl=false.
ERROR: .../external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/BUILD:3:1: in java_import rule @bazel_tools//src/tools/android/java/com/google/devtools/build/android:all_android_tools: The native Java rules are deprecated. Please load java_import from the rules_java repository. See http://github.com/bazelbuild/rules_java and https://github.com/bazelbuild/bazel/issues/8741. You can temporarily bypass this error by setting --incompatible_load_java_rules_from_bzl=false.
ERROR: .../external/bazel_tools/tools/android/BUILD:261:1: in java_binary rule @bazel_tools//tools/android:dexer: The native Java rules are deprecated. Please load java_binary from the rules_java repository. See http://github.com/bazelbuild/rules_java and https://github.com/bazelbuild/bazel/issues/8741. You can temporarily bypass this error by setting --incompatible_load_java_rules_from_bzl=false.
```

Similar issues about _other_ files that are currently open:
- https://github.com/bazelbuild/bazel/issues/8746
- https://github.com/bazelbuild/bazel/issues/9082
- https://github.com/bazelbuild/bazel/issues/10838

**Comment by cpovirk** [comment]
I started looking at this, and I'm confused.

(First, I should have mentioned that I'm testing with Bazel 2.1.1.)

I see changes to add `load()` where needed for the first 2 files:

- [src/java_tools/import_deps_checker/java/com/google/devtools/build/importdeps/BUILD](https://github.com/bazelbuild/bazel/commit/a4de484efe44c3e614ba7901a5e03e3958c148e9#diff-277c8c3eed92b8cb597044fb40bd4cf3R4) ([part of 2.1.1](https://github.com/bazelbuild/bazel/blob/2.1.1/src/java_tools/import_deps_checker/java/com/google/devtools/build/importdeps/BUILD#L4))
- [src/tools/android/java/com/google/devtools/build/android/BUILD](https://github.com/bazelbuild/bazel/commit/a4de484efe44c3e614ba7901a5e03e3958c148e9#diff-fb9092cda7cf5bf7218a7678cf32529aR3) ([part of 2.1.1](https://github.com/bazelbuild/bazel/blob/2.1.1/src/tools/android/java/com/google/devtools/build/android/BUILD#L3))

(tools/android/BUILD is still missing `load()` [as I look at it today](https://github.com/bazelbuild/bazel/blob/793964e8e4268629d82fabbd08bf1a7718afa301/tools/android/BUILD), but setting that aside for a moment....)

But I don't see the `load()` statements in the corresponding files under `$HOME/.cache/bazel/_bazel_cpovirk/.../external/bazel_tools`.

I would have assumed that [create_embedded_tools](https://github.com/bazelbuild/bazel/blob/2.1.1/src/BUILD#L326) packages the current contents of `bazel_tools` into each Bazel release, but I don't actually have any idea.

**Comment by cpovirk** [comment]
> (tools/android/BUILD is still missing `load()` [as I look at it today](https://github.com/bazelbuild/bazel/blob/793964e8e4268629d82fabbd08bf1a7718afa301/tools/android/BUILD), but setting that aside for a moment....)

Err, sorry, the current version of tools/android/BUILD no longer uses `java_binary` and `java_import`, so it has no need for the `load()`.

It's sounding like this is "fixed" by a4de484efe44c3e614ba7901a5e03e3958c148e9 and whichever commit removed the `java_*` usages from tools/android/BUILD. But a4de484efe44c3e614ba7901a5e03e3958c148e9 was 6 months ago, so I'm wondering if it's expected that it seems not to have made its way into the version of `bazel_tools` that I'm seeing.

**Comment by cpovirk** [comment]
Here's specifically what I'm seeing in case there's something weird about my environment or project:

```
$ bazel --version
bazel 2.1.1

$ git clone git@github.com:google/dagger.git && cd dagger && git co 12e9593a7dfce489b5f62748a7427defc3e68658 && bazel build --incompatible_load_java_rules_from_bzl -k //...
...
ERROR: .../5ee40ee7992de43c092e33a2e7d112f4/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/BUILD:3:1: in java_import rule @bazel_tools//src/tools/android/java/com/google/devtools/build/android:all_android_tools: The native Java rules are deprecated. Please load java_import from the rules_java repository. See http://github.com/bazelbuild/rules_java and https://github.com/bazelbuild/bazel/issues/8741. You can temporarily bypass this error by setting --incompatible_load_java_rules_from_bzl=false.
ERROR: .../5ee40ee7992de43c092e33a2e7d112f4/external/bazel_tools/src/java_tools/import_deps_checker/java/com/google/devtools/build/importdeps/BUILD:3:1: in java_import rule @bazel_tools//src/java_tools/import_deps_checker/java/com/google/devtools/build/importdeps:import_deps_checker_deploy_jar: The native Java rules are deprecated. Please load java_import from the rules_java repository. See http://github.com/bazelbuild/rules_java and https://github.com/bazelbuild/bazel/issues/8741. You can temporarily bypass this error by setting --incompatible_load_java_rules_from_bzl=false.
...
```

Note that there are additional errors from running without an Android SDK. But even when I run with the SDK present (at which point the other errors go away), the `java_*` errors persist. (To make the errors go away (and to get the other error about `@bazel_tools//tools/android:dexer`), you need to run the build with `ANDROID_HOME` pointing to [an appropriately prepared Android SDK](https://github.com/google/dagger/blob/master/CONTRIBUTING.md#building-dagger-from-the-command-line).)

**Comment by cpovirk** [comment]
(I thought perhaps that switching to [rules_android](https://github.com/bazelbuild/rules_android) would help, but it appears not, assuming that I got it right.)

**Comment by cpovirk** [comment]
I tried with 2.2.0 and on another machine, and the build still fails.

**Comment by cpovirk** [comment]
Also failing with 3.0.0.

**Comment by cpovirk** [comment]
Ditto 3.1.0.

**Comment by cpovirk** [comment]
I'm still seeing some errors with 3.3.1. Testing against https://github.com/google/dagger/commit/f3ff00a29d28941c798a417fdccbdfe33a8499c0 (which has some other errors related to `--incompatible_load_java_rules_from_bzl` nowadays, as I've stopped trying to keep it up to date), I see at least 2 of the original 3:

```
.../7cee73372ad52c17db7b6117de5a4f21/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/BUILD:3:12: in java_import rule @bazel_tools//src/tools/android/java/com/google/devtools/build/android:all_android_tools: The native Java rules are deprecated....
.../7cee73372ad52c17db7b6117de5a4f21/external/bazel_tools/src/java_tools/import_deps_checker/java/com/google/devtools/build/importdeps/BUILD:3:12: in java_import rule @bazel_tools//src/java_tools/import_deps_checker/java/com/google/devtools/build/importdeps:import_deps_checker_deploy_jar: The native Java rules are deprecated....
```

**Comment by aiuto** [comment]
cc/ @meteorcloudy  - because they have lots of recent experience with third party things. 

I finally caught a detail in the first entry "ERROR: .../external/bazel_tools/tools/android/BUILD:261:1: in java_binary rule @bazel_tools//tools/android:dexer"

Since it is in bazel_tools, it may be that we need to update an upstream dependency to get there.  This might be a build & packaging problem more than a java rules problem.

**Comment by meteorcloudy** [comment]
Sorry, the incompatible change is not currently owned by anyone. I'll take a look as soon as I have some free time.

**Comment by cpovirk** [comment]
I think this is expected, but FYI, I do still see this with 3.4.1:

> ERROR: .../7cee73372ad52c17db7b6117de5a4f21/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/BUILD:3:12: in java_import rule @bazel_tools//src/tools/android/java/com/google/devtools/build/android:all_android_tools: The native Java rules are deprecated. Please load java_import from the rules_java repository. See http://github.com/bazelbuild/rules_java and https://github.com/bazelbuild/bazel/issues/8741. You can temporarily bypass this error by setting --incompatible_load_java_rules_from_bzl=false.
> ERROR: .../7cee73372ad52c17db7b6117de5a4f21/external/bazel_tools/src/java_tools/import_deps_checker/java/com/google/devtools/build/importdeps/BUILD:3:12: in java_import rule @bazel_tools//src/java_tools/import_deps_checker/java/com/google/devtools/build/importdeps:import_deps_checker_deploy_jar: The native Java rules are deprecated. Please load java_import from the rules_java repository. See http://github.com/bazelbuild/rules_java and https://github.com/bazelbuild/bazel/issues/8741. You can temporarily bypass this error by setting --incompatible_load_java_rules_from_bzl=false.

**Comment by lberki** [comment]
This is obsolete; We gave up on `--incomplete_load_java_rules_from_bzl`.
