### ISSUE TITLE
Documentation issue: DefaultInfo

### ISSUE THREAD

**Issue by chengji77** [bazelbuild/bazel#10848]
Documentation URL: https://docs.bazel.build/versions/2.1.0/skylark/lib/DefaultInfo.html

The doc page doesn't mention this constructor: `DefaultInfo(runfiles = ...)`

On this page: https://docs.bazel.build/versions/2.1.0/skylark/rules.html#runfiles-features-to-avoid, Runfiles features to avoid, bullet point 2, it mentions that "Specify `DefaultInfo(runfiles = ...)` instead". I couldn't find any other places that documents this constructor neither.

**Comment by jin** [comment]
cc @laurentlb @c-parsons

**Comment by jfancher** [comment]
I just ran into this as well, and wanted to highlight that it's not just `DefaultInfo`; documentation of any provider constructor seems to have disappeared between 1.1.0 and 1.2.0:

`JavaInfo`:
https://docs.bazel.build/versions/1.1.0/skylark/lib/JavaInfo.html
https://docs.bazel.build/versions/1.2.0/skylark/lib/JavaInfo.html

`CcInfo`:
https://docs.bazel.build/versions/1.1.0/skylark/lib/CcInfo.html
https://docs.bazel.build/versions/1.2.0/skylark/lib/CcInfo.html

`OutputGroupInfo`:
https://docs.bazel.build/versions/1.1.0/skylark/lib/OutputGroupInfo.html
https://docs.bazel.build/versions/1.2.0/skylark/lib/OutputGroupInfo.html

And so on.

**Comment by laurentlb** [comment]
@alandonovan Do you if anything changed in this area? (it affects Bazel 1.2, so the change was in October).
