### ISSUE TITLE
Make d8 dex builder support `--incremental_dexing`

### ISSUE THREAD

**Issue by nkoroste** [bazelbuild/bazel#10844]
### Description of the problem / feature request:

Make d8 dex builder support `--incremental_dexing`

### Feature requests: what underlying problem are you trying to solve with this feature?

It looks like D8 doesn't support incremental dexing, users need to pass in `--noincremental_dexing` in order to use D8.

Related:
https://github.com/bazelbuild/bazel/issues/10241
https://github.com/bazelbuild/bazel/issues/10287
https://github.com/bazelbuild/bazel/issues/5150

**Comment by tokudu** [comment]
If I wanted to contribute to fix this issue, can someone from the Bazel team point me in the right direction?

**Comment by nkoroste** [comment]
At a closer look it looks like incremental is in fact supported and works as intended. Closing this issue for now.
