### ISSUE TITLE
Support running multiple tartgets in parallel

### ISSUE THREAD

**Issue by jjangga0214** [bazelbuild/bazel#10855]
Hi, currently `bazel` does not support multiple targets at once.

For example,
`bazel run //foo:bin //bar:bin`
only runs `//foo:bin`, not both.

I think it'd be really convenient in such a case when we want to run multiple processes in parallel (e.g. web applications) in a local development environment.

Though there's https://github.com/atlassian/bazel-tools/tree/master/multirun, its list has to be written statically. When there are many runnable targets, declaring every possible combination, or writing temporary `multirun` target would be somewhat cumbersome. 

So allowing multiple targets by CLI would still be helpful. 

P.S. For the case you wants to hear a use case, I share mine here. Currently my monorepo consist of microservices. I want to run binary targets dynamically (not static `multirun` target) in my development environment. Choosing what to run "dynamically" by CLI is our strong workflow requirement. Thus, I'm using Bazel only for "build", but not to "run(binary)" them right now. And this discrepancy make me feel not 100% assured of "built" services, as I haven't run them with Bazel. I hope to fully migrate to Bazel once the feature is implemented. But anyway I think this feature would be helpful to other people with different context and needs.

**Comment by bigkraig** [comment]
@jjangga0214 I use [Pulumi](https://www.pulumi.com) to deploy the development environment to a local Kubernetes cluster to run my services there. It's a bit more like reality with the caveat that rules_docker is [somewhat limited on what can be used as a tag](https://github.com/bazelbuild/rules_docker/issues/322) leading to the image tags changing for every Bazel run.

**Comment by mancini0** [comment]
if you are using rules_k8s you can use the k8s_objects rule to apply commands to all of your microservices. (Run, deploy, etc.)

**Comment by twheys** [comment]
In addition, it would be a nice feature if once could specify "run" dependencies. For example, if I run my node server, then I should start my backend server as well.

**Comment by pavi2410** [comment]
Any updates on this? Is this on the roadmap?

**Comment by keith** [comment]
There are some rules implementations out there for this like mine: https://github.com/keith/rules_multirun

**Comment by pavi2410** [comment]
It looks like it doesn't support Windows, does it?

**Comment by keith** [comment]
No it doesn't right now. I don't have a windows machine to test with but it shouldn't be hard to add support. Or write your own rules with the same idea

**Comment by lberki** [comment]
I'll close this as "not planned".

I do realize that this is a common need (this is the third most popular issue in our issue tracker), but Bazel cannot be everything for everyone and it's not a good idea to get into the business of process management after Bazel itself has finished running.

If we implemented this, we'd have to figure out (without an attempt at completeness):
* If the multiple run targets should be run in parallel or sequentially
* What happens when one binary errors out but another does not
* How to run the binaries in the background
* Where stdout/stderr/stdout of these binaries are connected to

All of which are interesting questions, but not ones for a build tool to solve. I could imagine doing this in custom code: specifying a single rule to run in a BUILD file that then depends on the binaries you actually want to run and which then runs them in the way you want like https://github.com/keith/rules_multirun , but it's not something we want to maintain as a core part of Bazel.

**Comment by AlexeyDmitriev** [comment]
@lberki the route of "run all commands as one invocation" does indeed raise a lot of hard questions.

I wonder if another route of "only get a lock while compilation is running" is possible, allowing multiple `bazel run`'s running in parallel. As far as I understand, currently (one of) the problem(s) is that there's a single output tree and we are not sure that next run will not overwrite relevant data there.

But
* Suggested workaround of "build and then just run the binary" has the same issue anyway
* it should be possible to create the shadow tree with only relevant data (the same way as it's done for compilation)

**Comment by lberki** [comment]
The binary built and executed by `bazel run` does not inhibit Bazel or other such binaries. from running. So if you say: `bazel run <binary1>; bazel run <binary2>; `bazel run<binary3>` and each binary takes a long time to run, what will happen is:

1. Bazel is building `binary1`
2. Bazel is building `binary2`  + `binary1` is running
3. Bazel is building `binary3`  + `binary1` is running + `binary2` is running
3. `binary1` is running + `binary2` is running + `binary3` is running

If the subsequent builds overwrite whatever the binaries run by previous builds need, well, tough luck, parallelism like the above is possible now.

**Comment by AlexeyDmitriev** [comment]
Thank you, it looks like a was confused with what part is under lock, the behaviour you said is exactly what I wanted
