### ISSUE TITLE
incompatible_objc_compile_info_migration

### ISSUE THREAD

**Issue by googlewalt** [bazelbuild/bazel#10854]
This flag is part of the efforts to migrate `ObjcProvider` compile info to `CcCompilationContext`.  It controls whether native Objective-C/C++ rules will use compile info from `ObjcProvider` or `CcInfo` (which contains the `CcCompilationContext`).  If the flag is false, bazel will get its compile info from `ObjcProvider` (pre-migration behavior).  If the flag is true, bazel will get its compile info from `CcInfo` (post-migration behavior).

See https://github.com/bazelbuild/bazel/issues/10674 for more details on the migration, and suggested migration steps.

Expected timeline:

* Available and default false in 3.0 (March 2020).
* Enabled in next major release (4.0, ~July 2020).
* Remove by the following release (4.0 or 4.1, ~July/August 2020).

**Comment by jin** [comment]
@susinmotion, could you replace the untriaged label with a [priority label](https://www.bazel.build/maintainers-guide.html#issues), please?

**Comment by keith** [comment]
> Default true in next release (~3.1, April 2020).

It looks like this wasn't flipped in 3.1? Is 3.2 the target now?

**Comment by googlewalt** [comment]
Thanks for checking.  It appears that bazel prefers to flip flag for major releases only, so I'm revising the plan to flip the flag in 4.0.

**Comment by susinmotion** [comment]
It looks like 3.6 is the next breaking release? Are things set to flip the flag then?

**Comment by googlewalt** [comment]
Yeah I'm ready to flip the flag at earliest opportunity, but I think 3.6 doesn't allow flag flip.  Hopefully soon.

**Comment by philwo** [comment]
Closing, because this flag has been flipped.
