### ISSUE TITLE
issue on windows since the release 2.0.0 acquireLock

### ISSUE THREAD

**Issue by fal-foyer** [bazelbuild/bazel#10850]
I downloaded and installed the bazel.exe version 2.0.0 and 2.1.1 for windows.
When I launch bazel, i get an acquirelock issue : Path not found.

FATAL: AcquireLock(d:\workspace_exzos\release\unc\domus\users_evo\fal\_bazel_fal\u5mzpase\lock): CreateFile failed: (error: 3): Le chemin d'accès spécifié est introuvable. (traduction : Path not found)

the correct path should be
c:\users\fal\_bazel_fal\u5mzpase\lock

I launched bazel in my wokspace "d:\workspace_exzos\release". And wherever I launch it, it try to find the file in LOCAL_DIRECTORY/unc/domus/users_evo/...

Before, i was on  the 1.0.1 version, and it worked fine.
I'am on windows 10.

Thanks to help me.

**Comment by laszlocsomor** [comment]
1. What shell / terminal do you run Bazel from? If you run it from MSYS2 Bash or from Git Bash, that may be the problem. (See https://docs.bazel.build/versions/master/windows.html#running-bazel-msys2-shell-vs-command-prompt-vs-powershell)
2. What if you pass `--ignore_all_rc_files` after `bazel`? If you have a `.bazelrc` file with `--output_user_root` or `--output_base` specified, then `--ignore_all_rc_files` will ignore it.
3. What's in your `HOME` and `USERPROFILE` envvars? They may be hardwired to some wrong value, which can also influence the output directory location.
4. Is the `TEST_TMPDIR` envvar set? It will make Bazel believe it's running inside a test, and behave differently than normal.

**Comment by fal-foyer** [comment]
Thank you.
Indeed, i used Git bash. With powershell or bazel plugin on intellij, it work fine.

**Comment by laszlocsomor** [comment]
Yay! Thanks for reporting back.
