### ISSUE TITLE
Report ExecuteStage updates to user

### ISSUE THREAD

**Issue by Qinusty** [bazelbuild/bazel#10861]
### Description of the feature request:

Bazel should report `ExecuteStage` from the metadata of the Execute service `google.longrunning.Operation.response`. 

### Feature requests: what underlying problem are you trying to solve with this feature?

The `ExecutionStage` metadata updates are never displayed to the user, leaving the user to believe an action is being executed remotely whilst it is actually queued.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

N/A

###  Have you found anything relevant by searching the web?

Related bazel logic somewhere around [here](https://github.com/bazelbuild/bazel/blob/38a732151d94e94bdc5d3f03ce3c535220a32af8/src/main/java/com/google/devtools/build/lib/remote/GrpcRemoteExecutor.java#L142)

**Comment by coeuvre** [comment]
This is fixed by #11922. Closing.
