### ISSUE TITLE
incompatible_require_linker_input_cc_api: Wrap Starlark C++ library objects with  linker_input

### ISSUE THREAD

**Issue by oquenchil** [bazelbuild/bazel#10860]
This disables several Starlark C++ API method parameters and getters.

create_linking_context  no longer accepts: libraries_to_link, user_link_flags and additional_inputs

linking_context no longer has the getters: libraries_to_link, user_link_flags and additional_inputs

**Flag**: --incompatible_require_linker_input_cc_api

This refactoring was necessary for the implementation of cc_shared_library. In order to reduce the surface of the API we are removing the old way of creating a linking context.

**Migration**
create_linker_input allows you to pass the same parameters that you were previously passing to create_linking_context: libraries_to_link, user_link_flags and additional_inputs

linking_context now has the getter linker_inputs. Each linker_input instance has all the getters that were removed from linking_context: libraries_to_link, user_link_flags and additional_inputs

**Comment by philwo** [comment]
Closing, because this flag has been flipped.
