### ISSUE TITLE
Disallow + operator for dicts in Skylark

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel#1086]
Currently, we define the `+` operator for concatenating dictionaries in Skylark. However, this is not valid in Python. This will be a problem when the Skylark docgen tool is available (see #712) since the tool will evaluate the Skylark code as Python.

Since Skylark is meant to be a subset of Python anyway, we should disallow `+` for dictionaries in Skylark and recommend an alternative.

**Comment by davidzchen** [comment]
Also see bazelbuild/skydoc#10

**Comment by MarkusTeufelberger** [comment]
How does skylark handle this case anyways?

````
a = {"foo":"bar"}
b = {"foo":"baz"}
a + b = ?
````

**Comment by laurentlb** [comment]
Duplicate of https://github.com/bazelbuild/bazel/issues/6461
