### ISSUE TITLE
io.bazel.rules.closure.webfiles.server.WebfilesServer run SEVERE: Webfiles server died

### ISSUE THREAD

**Issue by akdeepak** [bazelbuild/bazel#10879]
**### Description of the problem / feature request:**

Build is compiled successfully but run is failing on the tensoarboard (tensorflow) github repo

### Feature requests: what underlying problem are you trying to solve with this feature?

Build and run the tensorboard embedding projector - project for the development.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1 . Install Bazel Version 2.1.0
2. git clone https://github.com/tensorflow/tensorboard.git
3. bazel run tensorboard/plugins/projector/vz_projector:devserver

### What operating system are you running Bazel on?

Linux 

### What's the output of `bazel info release`?
INFO: Found 1 target...

[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //tensorboard/plugins/projector/vz_projector:devserver up-to-date:
[1 / 1] checking cached actions
  bazel-bin/tensorboard/plugins/projector/vz_projector/devserver.html
[1 / 1] checking cached actions
INFO: Elapsed time: 0.556s, Critical Path: 0.00s
[1 / 1] checking cached actions
INFO: 0 processes.
[1 / 1] checking cached actions
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/tensorboard/plugins/projector/vz_projector/devserver
INFO: Build completed successfully, 1 total action
Feb 29, 2020 8:45:01 PM io.bazel.rules.closure.webfiles.server.WebfilesServer run
SEVERE: Webfiles server died
java.net.SocketException: Protocol family unavailable
	at java.base/java.net.PlainSocketImpl.socketBind(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:381)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:243)
	at java.base/javax.net.DefaultServerSocketFactory.createServerSocket(ServerSocketFactory.java:231)
	at io.bazel.rules.closure.webfiles.server.NetworkUtils.createServerSocket(NetworkUtils.java:51)
	at io.bazel.rules.closure.webfiles.server.WebfilesServer.runForever(WebfilesServer.java:137)
	at io.bazel.rules.closure.webfiles.server.WebfilesServer.run(WebfilesServer.java:125)
	at io.bazel.rules.closure.webfiles.server.WebfilesServer.main(WebfilesServer.java:76)

###  Have you found anything relevant by searching the web?

set the jvm parameter 
-Djava.net.preferIPv4Stack=true
-Djava.net.preferIPv4Addresses=true

### Any other information, logs, or outputs that you want to share?
Tried the below commands as per bazel build document.
bazel --host_jvm_args="-Djava.net.preferIPv4Stack=true" --host_jvm_args="-Djava.net.preferIPv4Addresses=true" run tensorboard/plugins/projector/vz_projector:devserver

but still facing the same above mentioned issues.

**Comment by irengrig** [comment]
Hi @akdeepak , thank you for reporting the issue!

What happens if you bazel build XXX, and then run the binary without involving Bazel? Does it work?
I also noticed that the error comes from rules_closure library, should you maybe better ping rules_closure?

/cc @gkdn @Yannic

**Comment by gkdn** [comment]
> What happens if you bazel build XXX, and then run the binary without involving Bazel? 

I think that should work.

**Comment by jin** [comment]
Closing as this is related to rules_closure and a workaround has been suggested.

**Comment by MartinRenaudin** [comment]
I still have this issue, even with the fix (build then run binary) , I have "exec: ../io_bazel_rules_closure/java/io/bazel/rules/closure/webfiles/server/WebfilesServer: not found"
I use ubuntu 18.04 on docker, i tried with different versions of bazel until the latest 3.5.0.  I tried running bazel with --host_jvm_args="-Djava.net.preferIPv4Stack=true" . Nothing worked, when I try on my ubuntu 18.04 with no docker, I have no issue running vz_projector.
