### ISSUE TITLE
Process locks stdout file

### ISSUE THREAD

**Issue by Githubber2021** [bazelbuild/bazel#10878]
Hi,

I am using bazel in my GitLab pipeline and I often stumble over this error. I am not sure if a Gitlab runner locks the file, but I am wondering what I can do to find the cause. Any help is highly appreciated.

```
Execution platform: //_build:windows-clang-cl. Note: Remote connection/protocol failed with: execution failed
 Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(241):
nativeCreateProcess(\\?\C:\out\3kj43ht\execroot\bazel-out\_tmp\actions\stdout-1295-0):
The process cannot access the file because it is being used by another process.
```

**Comment by irengrig** [comment]
Hi @Githubber2021 , thank you for reporting the problem!
Seems that Bazel can not access its internal file.
Could you kindly check with https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer, what is the process holding the lock to the file?
Thank you!

**Comment by meteorcloudy** [comment]
It's also possible your Windows Defender or some other anti-virus software is holding the handle of the file. It is possible to whitelist the `c:/out` folder?

**Comment by Githubber2021** [comment]
Still on hold since I didn't receive this error for a while. Thanks for the responses so far

**Comment by jin** [comment]
Closing as error seems to be transient, please ping on issue if you're running into it again.
