### ISSUE TITLE
Documentation issue: External Dependencies

### ISSUE THREAD

**Issue by dmadisetti** [bazelbuild/bazel#10874]
Documentation URL: https://docs.bazel.build/versions/2.0.0/external.html#best-practices

Is using `http_archive` still best practice over using `git_repository`? The justification given is rather dated, since then shallow_since has been added (https://github.com/bazelbuild/bazel/commit/6496b1d1d25025f33406b1eaf9949cab126f08bd) in addition `git_repository` may have diverged from the original skylark implementation.

If there is a good justification maybe we can link this answer :)

**Comment by jin** [comment]
Solely based on the Starlark git rules' dependency on system `git(1)`, I would still recommend using `http_archive` over `git_repository` whenever possible.

**Comment by laurentlb** [comment]
* I think `http_repository` is faster for GitHub repositories (need to double-check).
* It's easier to provide mirrors.
* As jin said, `git_repository` depends on the git binary. It's not always installed (for example, on many Windows machines).

For using projects on GitHub, `http_repository` seems better to me.
