### ISSUE TITLE
Missing docs pages / broken links

### ISSUE THREAD

**Issue by aj-michael** [bazelbuild/bazel#1087]
I was reading through the Docs on http://bazel.io/docs/install.html and there are some broken links on the Skylark Rules section of the side menu.

These links return 404:

* Java AppEngine - http://bazel.io/docs/be/appengine.html
* C# - http://bazel.io/docs/be/dotnet.html
* D - http://bazel.io/docs/be/d.html
* Groovy - http://bazel.io/docs/be/groovy.html
* Go - http://bazel.io/docs/be/go.html
* Sass - http://bazel.io/docs/be/sass.html

This link returns a page with a redirect link, and that link returns 404:
* Scala - http://bazel.io/docs/be/scala.html

Apologies if this is the wrong repo to report this, but I couldn't find a better one in the bazelbuild org.

**Comment by kchodorow** [comment]
Thanks for the report!  We recently moved all of these rules to their own repos (e.g., https://github.com/bazelbuild/rule_appengine), and I think we're still updating how their documentation is generated.
