### ISSUE TITLE
Genrule refuses to build when adding Typescript support

### ISSUE THREAD

**Issue by anthanh** [bazelbuild/bazel#10884]
### Description of the problem / feature request:

Hi there!

Building NextJS projects seems to work with plain JS, but not with Typescript support.
You can try it [here](https://github.com/anthanh/bazel-next-typescript-monorepo).
FYI: NextJS generates artifacts in `.next` folder. Sources and node_modules still needed to run the NextJS webapp.

It works with `nodejs_binary`, but no output management.
Can't use `npm_package_bin` because NextJS build directory has several run-time generated hashed files, or cannot zip it (no cmd attr).
So I ended up using `genrule`.

### Feature requests: what underlying problem are you trying to solve with this feature?

next-cli under genrule with Typescript support.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

[Here](https://github.com/anthanh/bazel-next-typescript-monorepo) you can find an example project with 2 NextJS appplications:
* webapp: NextJS with JS => `bazelisk //packages/webapp:start` works.
* webapp2: NextJS with TS. => `bazelist //packages/webapp2:start` fail.

### What operating system are you running Bazel on?

OSX 10.14.6

### What's the output of `bazel info release`?

`release 2.1.1`

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
git@github.com:anthanh/bazel-next-typescript-monorepo.git
8d15f1a6dd1a48d63188cef2bef24bc45d81e870
8d15f1a6dd1a48d63188cef2bef24bc45d81e870
```

###  Have you found anything relevant by searching the web?

Not really, maybe related to this? https://github.com/bazelbuild/rules_nodejs/issues/312

### Any other information, logs, or outputs that you want to share?

```
yarn run v1.17.3
$ bazelisk run //packages/webapp2:start
INFO: Analyzed target //packages/webapp2:start (2 packages loaded, 11 targets configu
red).
INFO: Found 1 target...
ERROR: /Users/anthanh/code/github/bazel-js-monorepo/packages/webapp2/BUILD:49:1: Exec
uting genrule //packages/webapp2:build failed (Exit 1) bash failed: error executing c
ommand /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
It looks like you're trying to use TypeScript but do not have the required package(s)
 installed.

Please install typescript, @types/react, and @types/node by running:

        npm install --save-dev typescript @types/react @types/node

If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files).

Creating an optimized production build...
Target //packages/webapp2:start failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 11.772s, Critical Path: 10.94s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by irengrig** [comment]
Hi @anthanh , thank you for reporting the problem!

It is quite a long description so I did not really read it deeply, but just in case - there is this part in the reported error:

"Please install typescript, @types/react, and @types/node by running:
        npm install --save-dev typescript @types/react @types/node"

- does it help?

Also, it seems that this is completely rules_nodejs related and there is nothing we can do in Bazel itself.
Please report the issue for rules_nodejs.

**Comment by anthanh** [comment]
The reported error is pretty weird since @types/node, typescript are part of the devDependencies (@types/react is a dependency of @types/react-dom).
as defined here https://github.com/anthanh/bazel-next-typescript-monorepo/blob/master/packages/webapp2/package.json#L20
Looks like the rule cannot find it somehow.

Thanks @irengrig for your response.

**Comment by jin** [comment]
Please reopen this issue in rules_nodejs as it's not Bazel related.
