### ISSUE TITLE
macOS wrapped_clang should export ZERO_AR_DATE=1 to make linking hermetic

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/bazel#10886]
### Description of the problem / feature request:

`wrapped_clang`, unlike `bazel/libtool`, doesn't export `ZERO_AR_DATE=1`. This causes timestamps to be embedded in linked binaries.

### Feature requests: what underlying problem are you trying to solve with this feature?

`wrapped_clang` should export `ZERO_AR_DATE=1`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

On macOS, using the Xcode toolchain:

```
bazel clean
bazel build :some_objc_target
cp bazel-bin/some_objc_target /tmp/some_objc_target1
bazel clean
bazel build :some_objc_target
cp bazel-bin/some_objc_target /tmp/some_objc_target2
cmp /tmp/some_objc_target1 /tmp/some_objc_target2
```

The binaries will report differences because of the embedded timestamps.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 2.1.0

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/rules_swift/pull/136
https://github.com/bazelbuild/rules_swift/pull/120
https://github.com/bazelbuild/bazel/blob/0e1100f4a31c07ddf5efe3d4820032e0512cb91e/tools/objc/libtool.sh#L115

### Any other information, logs, or outputs that you want to share?

http://blog.llvm.org/2019/11/deterministic-builds-with-clang-and-lld.html

The above blog mentions setting this value to remove the timestamps.

**Comment by brentleyjones** [comment]
A workaround for now is to call the build with `--action_env=ZERO_AR_DATE=1`

**Comment by thii** [comment]
`ZERO_AR_DATE=1` is a subset of `-D`, so it looks like passing `-D` is the preferred way now. There's a PR for it: https://github.com/bazelbuild/bazel/pull/11576.

`ZERO_AR_DATE=1` also has [a bug](https://source.chromium.org/chromium/chromium/src/+/62848c8d298690e086e49a9832278ff56b6976b5?originalUrl=https%2F%2F:%2F%2F%2F%2Fcs.chromium.org%2F) with timezone.

> The problem with this flag is that it resets the file mtime on the file to epoch=0, e.g. 1970-1-1 or 1969-12-31 depending on timezone.

**Comment by brentleyjones** [comment]
This is still an issue, btw. While libtool uses `-D`, we need `wrapped_clang` to `export ZERO_AR_DATE=1` to fix linking binaries (not archives).

**Comment by keith** [comment]
PR to fix the link action https://github.com/bazelbuild/bazel/pull/13091
