### ISSUE TITLE
bazel-my-project/ symlink not affected by workspace(name=...)

### ISSUE THREAD

**Issue by HALtheWise** [bazelbuild/bazel#10888]
### Description of the problem / feature request:

The documentation [here](https://docs.bazel.build/versions/master/output_directories.html) implies that the generated symlink `bazel-<workspace_name>` uses the "name" of the workspace defined in the `WORKSPACE` file, but on bazel `2.0.0` I'm seeing it ignore that in favor of using the name of the parent directory.

We have developers install the code in differently-named folders, so this means we cannot build any scripts that depend on that symlink.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create an empty folder with a WORKSPACE file containing...

```
workspace(name = "customname")
```

Run `bazel build`

```
/tmp/bazeltest> ls
bazel-bazeltest@  bazel-bin@  bazel-out@  bazel-testlogs@  WORKSPACE
```

Expected:
```
bazel-customname@  bazel-bin@  bazel-out@  bazel-testlogs@  WORKSPACE
```

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

`release 2.0.0`

**Comment by philwo** [comment]
I can still reproduce this. 😅
