### ISSUE TITLE
Aliased test rule is not recognized as test

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#10893]
### Description of the problem / feature request:

cc_test rule is not recognized as the test when referred to through the alias.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have trivial cc_test rule in workspace subfolder tests/src:
```
cc_test(
    name = "hello-world",
    srcs = ["hello-world.cpp"],
)
```
Command `bazel test //tests/cpp:hello-world` runs the test as expected.
Now at the workspace root level I create the alias to make command line shorter:
```
alias(
    name = "hello-world",
    actual = "//tests/cpp:hello-world",
)
```
But when I run `bazel test hello-world` (running the same cc_test through the alias) I get the error: `ERROR: No test targets were found, yet testing was requested` 

### What operating system are you running Bazel on?

Reproduces on all OSs.

### What's the output of `bazel info release`?

2.2.0

**Comment by benjaminp** [comment]
5576269cba82578ee4e80c362b39d86e87c25780 and f2cb3c69413c74569f19232f89a5f0e86d4f15ac are relevant.

**Comment by laurentlb** [comment]
@lberki, can you comment why you rolled back the change?

**Comment by ulfjack** [comment]
The change introduced a subtle error in some Google-internal code. Getting
the semantics exactly right is unfortunately more difficult than we
expected.

**Comment by haxorz** [comment]
In addition to what @ulfjack said, it's also worth noting that the current behavior is documented at https://docs.bazel.build/versions/2.2.0/be/general.html#alias (this has been here since the `alias` feature was added to Bazel).

**Comment by konste** [comment]
The current behavior is very confusing though. If it would plain say "No, you cannot alias cc_test rule!" it would be weird, but ok. What actually happens is that alias is not rejected and works, but the target it points to is not understood as the test anymore. And the error is "no test rules found"!

**Comment by haxorz** [comment]
> [@konste ] The current behavior is very confusing though. If it would plain say "No, you cannot alias cc_test rule!" it would be weird, but ok

Sure. I wasn't condoning or defending the behavior; I was just pointed out that it's documented.

Fwiw, @ulfjack made made the same point in the Google-internal discussion of this a few months ago.

Imo, the initial addition of the `alias` feature in Bazel should have either gone all the way and added full support for alias->test edges (working around the Google-internal issues, at high cost), or just outright banned them from the get-go.

**Comment by jacky8hyf** [comment]
The Kleaf team has hit this as well (https://r.android.com/c/kernel/build/+/3513690/comment/e6dca748_6690d067/). We weren't able to use test_suite() as a replacement as the document https://docs.bazel.build/versions/2.2.0/be/general.html#alias suggested, because test_suite(tests=) attribute isn't configurable.
