### ISSUE TITLE
Build fails for 2.2.0, but succeeds when adding `--verbose_failures` flag

### ISSUE THREAD

**Issue by kgizdov** [bazelbuild/bazel#10895]
### Description of the problem:

Bazel 2.2.0 fails to build with unknown error. Passing `--verbose_failures` makes the build succeed with no issues or errors.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

fails to build with:
```bash
env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" ./compile.sh
./output/bazel build scripts:bazel-complete.bash
cd output
./bazel shutdown
```
but build successfully with:
```bash
env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk --verbose_failures" ./compile.sh
./output/bazel build scripts:bazel-complete.bash
cd output
./bazel shutdown
```

### What operating system are you running Bazel on?

Arch Linux x86_64, Java 11.0.6.u10, Protobuf 3.11.4, Python 3.8.1, GCC 9.2.1

### What's the output of `bazel info release`?

```bash
$ bazel info release
Starting local Bazel server and connecting to it...
release 2.2.0- (@non-git)
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

```bash
env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk --verbose_failures" ./compile.sh
./output/bazel build scripts:bazel-complete.bash
cd output
./bazel shutdown
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a

###  Have you found anything relevant by searching the web?

no

### Any other information, logs, or outputs that you want to share?

no

**Comment by meisterT** [comment]
I cannot repro this on my machine. What's the output of Bazel when it fails?

**Comment by james-stephenson** [comment]
I don't know what the OP was trying to convey about the issue, but I have a local Raspberry Pi build cluster whereby I build Bazel binaries for amv7l.

In trying to compile Bazel 2.2.0, I see the following:
```
ERROR: /workspace/bazel/src/main/java/com/google/devtools/build/lib/syntax/BUILD:150:1: C++ compilation of rule '//src/main/java/com/google/devtools/build/lib/syntax:libcpu_profiler.so' failed (Exit 1): gcc failed: error executing command
  (cd /tmp/bazel_XXENCNOJ/out/execroot/io_bazel && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/arm-opt/bin/src/main/java/com/google/devtools/build/lib/syntax/_objs/libcpu_profiler.so/cpu_profiler_unimpl.pic.d '-frandom-seed=bazel-out/arm-opt/bin/src/main/java/com/google/devtools/build/lib/syntax/_objs/libcpu_profiler.so/cpu_profiler_unimpl.pic.o' -fPIC -iquote . -iquote bazel-out/arm-opt/bin -iquote external/bazel_tools -iquote bazel-out/arm-opt/bin/external/bazel_tools -isystem external/bazel_tools/tools/jdk/include -isystem bazel-out/arm-opt/bin/external/bazel_tools/tools/jdk/include -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c src/main/java/com/google/devtools/build/lib/syntax/cpu_profiler_unimpl.cc -o bazel-out/arm-opt/bin/src/main/java/com/google/devtools/build/lib/syntax/_objs/libcpu_profiler.so/cpu_profiler_unimpl.pic.o)
Execution platform: //:default_host_platform
In file included from src/main/java/com/google/devtools/build/lib/syntax/cpu_profiler_unimpl.cc:17:
bazel-out/arm-opt/bin/external/bazel_tools/tools/jdk/include/jni.h:45:10: fatal error: jni_md.h: No such file or directory
 #include "jni_md.h"
          ^~~~~~~~~~
compilation terminated.
Target //src:bazel_nojdk failed to build
INFO: Elapsed time: 809.650s, Critical Path: 249.27s
INFO: 957 processes: 892 local, 65 worker.
FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel
```

This seems like yet another case similar to https://github.com/bazelbuild/bazel/pull/10748, and the fix there was just to patch the `select` for `jni_header`.  I'm assuming adding a clause for `arm` would be fine, but it seems like that code really should have a default for any linux so it's not a laundry list of architectures all pointing to the same result.

I could work on a patch for `arm` myself but don't know when I'll be able to get to it.

**Comment by james-stephenson** [comment]
Here's the original, offending commit: https://github.com/bazelbuild/bazel/commit/314cd3353b018420598188cf54c3f97358baa2e3#diff-96bd71d4e041b52d389d631025d2c09f

**Comment by meisterT** [comment]
cc @alandonovan

**Comment by kgizdov** [comment]
Hi, sorry for delay - traveling. The message from bazel was something along the lines of: ERROR: //some-module/foo failed to build. If you want to see a reason run the compilation with `--verbose_failures`. So I added the flag to see what the error was and bam, bazel compiled with no errors. Basically, I have no idea what the exact reason is. I will try and give actual output when I'm back from the trip.

**Comment by james-stephenson** [comment]
My apologies if this is different from what the OP saw here, I noticed there was very little context on this one and thought it may be the same as what I saw, and this was the only open issue I could find until I started digging into other PRs.

I might continue the conversation on one of the other fix PRs rather than here.

**Comment by kgizdov** [comment]
somehow, recompiling again the same way worked fine. It mat have been something in the underlying packages.
