### ISSUE TITLE
Consistent runfile paths across repositories

### ISSUE THREAD

**Issue by jart** [bazelbuild/bazel#1090]
I've written a [shell script](https://github.com/bazelbuild/rules_closure/blob/8f690d8eabffaa806269d8bb31344d0a8d30a8bc/third_party/phantomjs/phantomjs.sh) for the Closure Rules that references runfiles specified in `data` as follows:

```sh
if [[ "${RUNFILES}" == "" ]]; then
  if [[ "$(basename "$(pwd)")" =~ \.runfiles$ ]]; then
    RUNFILES="$(pwd)"
  else
    RUNFILES="${0}.runfiles"
  fi
fi

"${RUNFILES}/third_party/phantomjs/bin/phantomjs" "$@"
```

The problem is that, when my repository is included by another one, that line will fail unless it looks like the following:

```sh
"${RUNFILES}/external/io_bazel_rules_closure/third_party/phantomjs/bin/phantomjs" "$@"
```

What is the best strategy for dealing with this?

See also: bazelbuild/rules_closure/pull/23 and bazelbuild/rules_closure/issues/19

**Comment by kchodorow** [comment]
See https://github.com/bazelbuild/bazel/issues/848. 

The main thing I'm working on now is fixing this, actually.  Basically we'll be moving all of the external repositories "down" a couple directories, so your runfiles tree will look like:

```
bin.runfiles/
    io_bazel_rules_closure/
        WORKSPACE
        some-runfiles
    some_other_repo/
        ...
    another_repo/
        ...
```

This way, regardless of whether the repo is local or remote, it will be in the same place WRT runfiles.

**Comment by jart** [comment]
This is great news @kchodorow. Any estimate on when this will make it into HEAD?

**Comment by kchodorow** [comment]
I'm working on it, but it's a huge change.  I'm guessing a couple of weeks.
