### ISSUE TITLE
git_worker.bzl appears non-hermetic 

### ISSUE THREAD

**Issue by prestonvanloon** [bazelbuild/bazel#10909]
I believe this is the offending line
https://github.com/bazelbuild/bazel/blob/66f33ab9f732bf0ec2a96248444b4955384d7cd3/tools/build_defs/repo/git_worker.bzl#L113

I discovered this by following the steps for [Finding non-hermetic behavior in WORKSPACE rules](https://docs.bazel.build/versions/master/workspace-log.html). Every external dependency appears non-hermentic due to host environment variables. 

Is there any way to disable adding host environment variables?

**Comment by keith** [comment]
We execute bazel through a wrapper script with `env -i` and limited environment variables to solve this

**Comment by prestonvanloon** [comment]
@keith do you have an example? I'm using bazelisk, if that helps.

**Comment by keith** [comment]
It's definitely not ideal but at the root of our repo we have a script like this:

```sh
#!/bin/bash

# do some custom logic

env -i \
 HOME=$HOME \ # also we set other required environment variables
 PATH=/usr/bin:/bin \
 bazel "$@"
```

**Comment by prestonvanloon** [comment]
Thanks! That is very helpful. We'll start doing that as well.
