### ISSUE TITLE
Better error message when implicit output overlaps with file

### ISSUE THREAD

**Issue by jart** [bazelbuild/bazel#1092]
A tester in https://github.com/bazelbuild/rules_closure/issues/24#issuecomment-201979549 got confused by a cyclic dependency error when there wasn't any visible cycle. The problem was that the implicit output target of a Skylark rule (hello.js) was the same as a file that already existed in the folder (hello.js).

It would have been nice if Bazel raised an error that the implicit output file already exists in the package, before showing the cycle error.

**Comment by laurentlb** [comment]
We can close this if we get rid of implicit outputs.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
