### ISSUE TITLE
Documentation issue: Installing Bazel on Fedora and CentOS

### ISSUE THREAD

**Issue by parrondo** [bazelbuild/bazel#10920]
Documentation URL: https://docs.bazel.build/versions/2.0.0/install-redhat.html

Provided instructions don't install Bazel 2.0.0 but the version 1.2.1-1.el7.

**Comment by jin** [comment]
https://copr.fedorainfracloud.org/coprs/vbatts/bazel/build/1282540/

This is not a documentation issue. @vbatts graciously helps maintain the build, but as above, it looks like the build failed.
