### ISSUE TITLE
Bazel doesn't run any tests when your target is named test

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#1093]
Consider this repository

https://github.com/dfabulich/target-named-test

There are two identical `java_test` targets here, one named `test` and one named `should_fail`.

``` python
java_test(
    name='test',
    srcs=['javatests/FailingTest.java'],
    deps=['@junit//jar', '@hamcrest_core//jar'],
)

java_test(
    name='should_fail',
    srcs=['javatests/FailingTest.java'],
    deps=['@junit//jar', '@hamcrest_core//jar'],
)
```

`bazel test //:should_fail` correctly fails, but `bazel test //:test` runs no tests, and incorrectly passes.

**Comment by dfabulich** [comment]
I _also_ hit issue #354 and issue #393 on the way to reproducing this bug. Combined, these bugs made it extremely difficult to diagnose my actual problem. :-(

**Comment by kchodorow** [comment]
Interestingly, the behavior in C++ is different (tests named "test" always fail without running), but also incorrect.  Weird.

**Comment by ulfjack** [comment]
Does --nolegacy_bazel_java_test help?

**Comment by damienmg** [comment]
@ulfjack this flag is the default now. They should have a test_class attribute.

**Comment by ulfjack** [comment]
Ok, so it doesn't. The workaround is to add test_class="java.package.name.FailingTest". I'd like to push my proposal to automatically collect the tests using an annotation processor, though, because that's both easy to use and fast. Do we have a java rules repository yet?

**Comment by kchodorow** [comment]
No, you could include all of bazel (e.g., https://github.com/bazelbuild/dash/blob/master/WORKSPACE#L23-L27) though.

**Comment by yugui** [comment]
@kchodorow 
I guess the behavior of C++ is this bug, #1443.

**Comment by yugui** [comment]
Confirmed.

Put the following files into the top level package of a main repository.
* `success.cc`:
   
   ```c++
   int main() { return 0; }
   ```
* `BUILD`:
   
   ```bzl
   cc_test(
       name = "test",
       srcs = ["success.cc"],
   )
   ```

Then, `bazel test :test` fails but `bazel test :test --test_arg "1 = 1"` succeeds because I am running `/bin/test` instead of `bazel-bin/test`.

**Comment by ulfjack** [comment]
I can't reproduce this anymore. If there's no test_class attribute, I get this error from bazel:

    ERROR: /usr/local/google/home/ulfjack/Projects/experimental/BUILD:2:1: in java_test rule //:test: cannot determine test class
