### ISSUE TITLE
Link broken to the blog post on `spawn_strategy`

### ISSUE THREAD

**Issue by ymotongpoo** [bazelbuild/bazel#10944]
### Description of the problem / feature request:

In the description of `--spawn_strategy` on [Command Line Reference](https://docs.bazel.build/versions/master/command-line-reference.html) page, there is the URL string to the blog post on the option, and it includes an extra space inside the string. (a space after `bazel.`)

> See https://blog.bazel. build/2019/06/19/list-strategy.html for details.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Fix the string to elminate the extra space. What it seems weird is the description was auto generated from [the source code comment](https://github.com/bazelbuild/bazel/blob/c7ba3c18363de4d44a24307eebd123e755db8bd8/src/main/java/com/google/devtools/build/lib/exec/ExecutionOptions.java#L62-L72) where it doesn't include any extra spaces. I suppose this is a bug within the documentation build process.

### What operating system are you running Bazel on?

Linux (I think the OS doesn't matter here)

### What's the output of `bazel info release`?

N/A (documentaion bug)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A (documentaion bug)

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A (documentaion bug)

###  Have you found anything relevant by searching the web?

* https://github.com/bazelbuild/bazel/blob/c7ba3c18363de4d44a24307eebd123e755db8bd8/src/main/java/com/google/devtools/build/lib/exec/ExecutionOptions.java#L62-L72

### Any other information, logs, or outputs that you want to share?

Screenshot of the current page.

https://yabumi.cc/170c70f9cfc18bbc74ecda24.png

**Comment by susinmotion** [comment]
Wow, this is true for all of the links on that page! Thanks for noticing.

**Comment by laurentlb** [comment]
cc @jin

**Comment by Wyverald** [comment]
Fixed by https://github.com/bazelbuild/bazel/commit/989d064cb3719a2d20de32c14e62218d8f2c21ef
