### ISSUE TITLE
How to install bazel from source after compling?

### ISSUE THREAD

**Issue by jiapei100** [bazelbuild/bazel#1094]
Hi, all:

I successfully compile bazel-git, but how can I deploy bazel manually? 
I'm NOT running an installer as described here http://bazel.io/docs/install.html
I would like to install bazel all manually? It looks there is NO such a manual?

Cheers
Pei

**Comment by kchodorow** [comment]
You copy the bazel binary to somewhere on your path (e.g., `cp bazel-bin/src/bazel /usr/bin`).

**Comment by jiapei100** [comment]
Yup... You are right... Just copy and paste the executable "bazel" ... Thank you ....
