### ISSUE TITLE
Support for Windows Subsystem for Linux

### ISSUE THREAD

**Issue by phillipzada** [bazelbuild/bazel#10941]
### Description of the problem / feature request:

Bazel failing to build/execute sh files due to filepath conflicts with the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Enable the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
2. Try a bazel build/run that requires execution of a sh file e.g: an Angular project - https://angular.io/guide/bazel

Output: 

<pre><code>
iBazel [3:25PM]: Querying for files to watch...
Loading: 0 packages loaded
Loading: 215 packages loaded

Loading: 215 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded

Loading: 0 packages loaded
iBazel [3:25PM]: Running //src:devserver
Loading: 0 packages loaded
Loading: 0 packages loaded

Loading: 0 packages loaded
iBazel [3:25PM]: Launching with notifications
listening on :35729
Loading:
Loading: 0 packages loaded
Analyzing: target //src:devserver (1 packages loaded, 0 targets configured)
INFO: Analyzed target //src:devserver (216 packages loaded, 13859 targets configured).
INFO: Found 1 target...
[0 / 4] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: C:/users/phillip/source/bazeltest/src/BUILD.bazel:19:1: Compiling Sass failed (Exit 127)
/bin/bash: C:/users/phillip/_bazel_phillip/bgoxvxd4/execroot/project/bazel-out/host/bin/external/io_bazel_rules_sass/sass/sass.sh: No such file or directory
Target //src:devserver failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: C:/users/phillip/source/bazeltest/src/BUILD.bazel:121:1 Compiling Sass failed (Exit 127)
INFO: Elapsed time: 1.964s, Critical Path: 0.19s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully
iBazel [3:25PM]: Error starting process: fork/exec C:\Users\Phillip\AppData\Local\Temp\bazel_script_path052570151.bat: %1 is not a valid Win32 application.
iBazel [3:25PM]: Run start failed fork/exec C:\Users\Phillip\AppData\Local\Temp\bazel_script_path052570151.bat: %1 is not a valid Win32 application.
</code></pre>

### What operating system are you running Bazel on?

Windows 10 x64

### What's the output of `bazel info release`?

release 2.1.0

### Any other information, logs, or outputs that you want to share?

Originally logged with the Angular team here: https://github.com/angular/angular/issues/35981

**Comment by phillipzada** [comment]
After doing some research, I've found that the WSL supports wslpath to convert C:/... to /mnt/c 

This could be a solution to the problem

**Comment by blemaire** [comment]
@phillipzada Did you ever find a solution to this?

**Comment by phillipzada** [comment]
@blemaire only workaround I found was to disable WSL before using Bazel and turn it back on after. Can't remember if restarts were required in between.

**Comment by Socolin** [comment]
Hello,

I got this issue too and I found a workaround.

Bazel first try to use bash defined in `BAZEL_SH` environment variable, so if you define it, it should work. So far I was able to get it working with `bash.exe` from git bash (git for window)

https://github.com/bazelbuild/bazel/blob/master/tools/sh/sh_configure.bzl#L29

```
> echo $ENV:BAZEL_SH
C:\Program Files\Git\bin\bash.exe
```

Strange thing, it should not run `bash.exe` from windir according to this line, but it seems it does anyway

https://github.com/bazelbuild/bazel/blob/master/tools/sh/sh_configure.bzl#L42.

**Comment by philwo** [comment]
Hey,

I'm not sure what the right path forward here is - even if we would use `wslpath` to transform the paths, would this actually work with `bash` running inside Linux and making assumption that the host OS is Linux, while the outer Bazel is on Windows?

Maybe we should just document that Bazel doesn't work with the WSL bash? 🤔 

The workaround suggested seems fine to me.
