### ISSUE TITLE
Bazel hits process limit and doesn't yield.

### ISSUE THREAD

**Issue by engineerkatie** [bazelbuild/bazel#10952]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Bazel consumes my whole process allocation, meaning I can't run a kill command to kill it.

### Feature requests: what underlying problem are you trying to solve with this feature?

I run bazel on a shared machine which is itself a KVM guest. I have a reduced process ulimit, because it's a shared machine. I've set the batch flag which means bazel will shutdown after building leaving me with enough processes to carry on working. When a build fails, bazel does not shut down cleanly and uses all my process allocation.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Use a linux machine. Create user account with a much reduced process ulimit. Run bazel to build a moderately large C++ project. Do something that consumes processes in the background (a git pull will suffice). Bazel will fail the build (due to not being able to fork) but will consume all your processes due to not shutting down properly.

You will now not be able to issue shell commands; your shell will not be able to fork to launch them.

> Replace this line with your answer.

### What operating system are you running Bazel on?

It's a very recent stable Debian, marked:

Linux version 4.19.104-fysh-kvmguest
(gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)) #9 SMP Sat Feb 15 10:47:41 UTC 2020

### What's the output of `bazel info release`?

release 2.2.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

It's a pre-built.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

It's not a repo specific thing. It *IS* a C++ build problem. I do not have this issue with Python builds. I have not tried Java or Go in this evironment.

###  Have you found anything relevant by searching the web?

The general conclusion seems to be "just restart the computer", but 1) I don't have root access, 2) There are other people using it and 3) That's not really a practical long-term solution.

### Any other information, logs, or outputs that you want to share?

There has been some mention of job-scaling by Bazel. I think the issue is that I'm in a ulimit box in a VM box; and Bazel's looking at the system to ask things like how many cores there are and seeing what the ultimate hardware has, not the actual environmental constraints.

(We run it perfectly well on laptops for C++ builds on another project, and it behaves fine.)

**Comment by tetromino** [comment]
Questions: how low is the process limit? What exactly do you observe when you say "not shutting down properly"? (The exact error messages, Bazel terminal output etc. would be very helpful.)

As a workaround to unblock your work, you might consider running Bazel using a wrapper script that sets a lower `ulimit -u` value.

**Comment by jmmv** [comment]
I don't think Bazel should be attempting to limit its process consumption given that Bazel doesn't even know what it needs: you can tweak parallelism with `--jobs`, but whatever process is started by Bazel is then free to go and create even more processes. Limiting the number of processes is thus just going to cause a build failure.

In other words: to get a build to succeed, you must have sufficient resources for it, which means sufficient memory, process descriptors, file descriptors, etc. If these limits are too low, you may have to go with `--jobs=1` but even then the expectation is that every separate action will fit within the system limits (or else it'll fail).

Lastly, the levers to restrict what processes can do already exist as mentioned in the last reply: run Bazel under a reduced ulimit.
