### ISSUE TITLE
Windows sh_test invocation and test environment different from Linux causing unexpected results

### ISSUE THREAD

**Issue by sunjayBhatia** [bazelbuild/bazel#10959]
### Description of the problem / feature request:

bazel sh_test works differently on Windows than Linux (and presumably other *nix). The path to the shell script that is run is a resolved symlink within the bazel test tree. See the minimal repro below.

When we run the tests on Linux, the path of the executable shell script that is invoked is from within the runfiles directory but on Windows it is not. This causes differences in behavior in the test environment that lead to unexpected results/failures. It appears this is simply the result of symlinks being resolved on Windows and not Linux to invoke the script.

We ran across this issue first trying to get the `envoy` project tests compiling and running on Windows.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See this repo for a minimal reproduction example: https://github.com/greenhouse-org/bazel-issue-repro/tree/c7ebe740e6cf12b58c7c7e156d9f5d2670329aad/sh_test_symlinks

Envoy example: https://github.com/envoyproxy/envoy/tree/b7a8c98cfc20e3033819228d5a9c555a6c5c6aaa/test/exe

### What operating system are you running Bazel on?

`Microsoft Windows [Version 10.0.17763.973]` (output of `ver`)

### What's the output of `bazel info release`?

`release 2.0.0`

###  Have you found anything relevant by searching the web?

Not at the moment

### Any other information, logs, or outputs that you want to share?

See the linked repo `README.md` for logs of the expected and failed outputs.

**Comment by meteorcloudy** [comment]
@sunjayBhatia The root cause for this issue is that we don't build a runfiles symlink tree on Windows by default.
You have two options: 
-  Enable runfiles tree on Windows by [--enable_runfiles](https://docs.bazel.build/versions/master/command-line-reference.html#flag--enable_runfiles). This will requires the user has Windows admin right or Windows developer mode is enabled.
- Use runfiles library to access data files. See the documentation [here](https://github.com/bazelbuild/bazel/blob/master/tools/bash/runfiles/runfiles.bash#L15)

**Comment by sunjayBhatia** [comment]
@meteorcloudy we are enabling runfiles in our environment, symlinks are being created but the test program is not invoked via the symlink, the original sh script is invoked

**Comment by sunjayBhatia** [comment]
We're using this pattern of an sh wrapper script in Envoy to work around https://github.com/bazelbuild/bazel/issues/3510 apparently

workaround script: https://github.com/envoyproxy/envoy/blob/master/bazel/sh_test_wrapper.sh

invoked via rule: https://github.com/envoyproxy/envoy/blob/93dd9459b380bdb7c4a61d8e8c14fdb88580669c/bazel/envoy_test.bzl#L315-L322

**Comment by meteorcloudy** [comment]
@sunjayBhatia I see, I will make it work when runfiles is enabled on Windows.
