### ISSUE TITLE
--test_filter documentation contains internal link

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#10950]
eb2ee8cee4f1d6169e660af5ad0e4d42ae7f0e66 added a link to `http://go/testfilter` to the user manual, which not very useful for the wider world.

**Comment by benjaminp** [comment]
20971ebf6e251ad7b546688d08ac82c5aace48fe

**Comment by michajlo** [comment]
Thanks for following up, looks like I put the "Fixed/Fixes" thing in the wrong place.
