### ISSUE TITLE
Setting default_grte_top to a non-label gives unhelpful error message

### ISSUE THREAD

**Issue by glinscott** [bazelbuild/bazel#1095]
In the crosstool, set `default_grte_top: "sysroot"`, and then build.  You will get the following error with no context `ERROR: Not a label.`, coming from `LibcTopConverter`.

It would be great to have more context for this error (Ex: `default_grte_top` is set to invalid value `sysroot`.  It must be a label)

**Comment by hlopko** [comment]
default_grte_top has been removed a while ago as part of the CROSSTOOL to Starlark migration. Therefore I believe this issue can be closed. Thanks!
