### ISSUE TITLE
bazel-dist 0.29.1 build failed due to no such package '@local_jdk//'

### ISSUE THREAD

**Issue by openedev** [bazelbuild/bazel#10951]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

bazel-dist 0.29.1 build is failing due to no such package '@local_jdk//' on x86-64 host. 

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Download the bazel-dist 0.29.1 and extract it. setup the JAVA_HOME and then run below command on shell.

env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh

or create .mk in build like below and run 'make host-bazel-rebuild'

bazel.mk
------------
BAZEL_VERSION = 0.29.1
BAZEL_SOURCE = bazel-$(BAZEL_VERSION)-dist.zip
BAZEL_SITE = https://github.com/bazelbuild/bazel/releases/download/$(BAZEL_VERSION)
BAZEL_DEPENDENCIES += \
    host-openjdk-bin

BAZEL_CONF_OPTS += \
    EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk"

define HOST_BAZEL_EXTRACT_CMDS
    $(UNZIP) -d $(@D) $(HOST_BAZEL_DL_DIR)/$(BAZEL_SOURCE)
endef

define HOST_BAZEL_BUILD_CMDS
    (cd $(@D); \
        JAVA_HOME=$(HOST_DIR) \
        $(BAZEL_CONF_OPTS) \
        $(SHELL) ./compile.sh \
    )
endef

$(eval $(host-generic-package))  

### What operating system are you running Bazel on?

Ubuntu 18.04 x86-64
python -version 3.8
javac -version 12.0.2

### What's the output of `bazel info release`?

Don't have bazel command, I'm trying to build bootstrap.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

None, since no bazel command.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

I'm using bazel-dist-0.29.1 release zip file

###  Have you found anything relevant by searching the web?

None.

>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?
Build Log:
host-bazel 0.29.1 Building
(cd /home/open/br/output/build/host-bazel-0.29.1;
JAVA_HOME=/home/open/br/output/host
EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" /bin/bash
./compile.sh )
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
.WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil
(file:/tmp/bazel_y18G3zaa/archive/libblaze.jar) to field
java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of
com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further
illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: --batch mode is deprecated. Please instead explicitly shut
down your Bazel server using the command "bazel shutdown".
DEBUG: /tmp/bazel_y18G3zaa/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:9:
Current running Bazel is not a release version and one was not defined
explicitly in rbe_autoconfig target. Falling back to '0.27.1'
DEBUG: /tmp/bazel_y18G3zaa/out/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:9:
rbe_ubuntu1804_java11 not using checked in configs as detect_java_home
was set to True
DEBUG: /tmp/bazel_y18G3zaa/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:9:
Current running Bazel is not a release version and one was not defined
explicitly in rbe_autoconfig target. Falling back to '0.27.1'
DEBUG: /tmp/bazel_y18G3zaa/out/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:9:
rbe_ubuntu1604_java8 not using checked in configs as detect_java_home
was set to True
DEBUG: /tmp/bazel_y18G3zaa/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:49:5:
Current Bazel is not a release version, cannot check for compatibility.
DEBUG: /tmp/bazel_y18G3zaa/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:51:5:
Make sure that you are running at least Bazel 0.17.1.
ERROR: infinite symlink expansion detected
[start of symlink chain]
/home/open/br/output/host/usr
/home/open/br/output/host
[end of symlink chain]
INFO: Call stack for the definition of repository
'remote_java_tools_linux' which is a http_archive (rule definition at
/tmp/bazel_y18G3zaa/out/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /DEFAULT.WORKSPACE.SUFFIX:240:1
ERROR: /home/open/br/output/build/host-bazel-0.29.1/tools/jdk/BUILD:308:1:
//tools/jdk:jdk depends on @local_jdk//:jdk in repository @local_jdk
which failed to fetch. no such package '@local_jdk//': Infinite
symlink expansion
ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted:
Analysis failed
INFO: Elapsed time: 6.128s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (102 packages loaded, 1184 targets\
 configured)
    Fetching @local_jdk; Restarting.

ERROR: Could not build Bazel

**Comment by dslomov** [comment]
0.29 is pretty old... How does it fare at HEAD?
