### ISSUE TITLE
progress is not shown for exclusive tests

### ISSUE THREAD

**Issue by fechanti** [bazelbuild/bazel#1096]
If a test is tagged as exclusive, then no progress are shown when the test is run, regardless of the value of --progress_report_interval

Impact:
We rely on bazel output to detect if a test is stuck or if it's making progress. This is becoming a significant issue for us as some tests are running for a long time (10 minutes) and bazel is printing no progress for them, making the continuous integration engine (jenkins) believe the test is stuck and killing the process.

**Comment by helenalt** [comment]
re-triaged, seems accurate issue/priority

**Comment by aiuto** [comment]
Update. Still a good idea. I don't know if it is fixed. misc>testing is still a reasonable tag.

**Comment by ulfjack** [comment]
Are you aware of `--test_output=streamed`?

**Comment by aiuto** [comment]
Yes. But I was going through old issues labeled 'misc' that should be closed, and it was late at night, so I was not about to reproduce it. I just wanted to mark it as effectively - "looked at but not closed"

**Comment by ulfjack** [comment]
I think the request here is to stream by default if the test is marked exclusive.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
