### ISSUE TITLE
--symlink_prefix option leaves bazel-out symlink at the root

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#10974]
### Description of the problem / feature request:

Option --symlink_prefix does not have effect on bazel-out convenience symlink which is still created at the workspace root.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Set `--symlink_prefix=.bazel/`  Documentation suggests it ```will cause Bazel to create symlinks called bin (etc) inside a hidden directory .bazel.``` Indeed four convenience symlinks, including the one named `out` are created in directory .bazel, BUT symlink `bazel-out` is still created at the workspace root and points to the same location as the symlink `out` in .bazel directory. When --symlink_prefix is specified `bazel-out` should not be created at workspace root.

### What operating system are you running Bazel on?

Reproduces on Linux and Windows.

### What's the output of `bazel info release`?

2.2.0

**Comment by janakdr** [comment]
https://github.com/bazelbuild/bazel/issues/5506 may be related.

**Comment by benjaminp** [comment]
This particular issue can be fixed with `--experimental_no_product_name_out_symlink`.

**Comment by janakdr** [comment]
Thanks @benjaminp ! I think that closes this issue.
