### ISSUE TITLE
Add support for user-defined build settings in external repositories

### ISSUE THREAD

**Issue by chsigg** [bazelbuild/bazel#10975]
When trying it all out, `--//:myflag=foo` works, but `--@rules_my_language//:myflag=foo` does not. I've tried to make an alias and then go for the first alternative, but that fails as well with `ERROR: Unrecognized option: //:myflag`.

Is it a design choice to not allow command line flags from external dependencies? Is a bug so I should file a bug report? Is it a feature request to allow it in v2, possibly via the WORKSPACE file?

_Originally posted by @moroten in https://github.com/bazelbuild/bazel/issues/5577#issuecomment-541041733_

**Comment by moroten** [comment]
My example in #10499 exercises both `--//:myflag=foo` and `--@rules_my_language//:myflag=foo`. Which Bazel version are you using?

The problem in #10499 is that `@rules_my_language//:myflag` and `//:myflag` are not mapped to the same instance, so you end up in errors you would not expect. As a workaround, I do never define any build setting in the root workspace.

**Comment by chsigg** [comment]
That's wonderful, thanks for the info. Indeed, I got tripped by trying this out in the root workspace. When referencing from another repo, it works as expected. That is the actual use case for me. Closing.
