### ISSUE TITLE
Documentation issue: Installing Bazel on Ubuntu

### ISSUE THREAD

**Issue by Keryen** [bazelbuild/bazel#10988]
Hello,

I am trying to install bazel on an Ubuntu 18.04 VM using Bazel's apt repository, following the steps exactly as you say in your README. 

When I have done everything, when using bazel it says to me that it is at version **release 0.14.1**. Even if i retry to execute  `sudo apt update && sudo apt full-upgrade`, it does not update bazel. Any suggestions?

**Comment by jin** [comment]
cc @philwo

**Comment by philwo** [comment]
Hi @Keryen,

that's strange. Can you please send the output of `which bazel` and `apt policy bazel`?

Cheers,
Philipp

**Comment by Keryen** [comment]
Hi **@philwo,**

I attatch those outputs and also the `bazel help` output 

`enrique@enrique-VirtualBox:~$ which bazel
/usr/local/bin/bazel

enrique@enrique-VirtualBox:~$ sudo apt policy bazel
[sudo] contraseña para enrique: 
bazel:
  Instalados: 2.2.0
  Candidato:  2.2.0
  Tabla de versión:
 *** 2.2.0 500
        500 https://storage.googleapis.com/bazel-apt stable/jdk1.8 amd64 Packages
        100 /var/lib/dpkg/status
     2.1.1 500
        500 https://storage.googleapis.com/bazel-apt stable/jdk1.8 amd64 Packages
     2.1.0 500
        500 https://storage.googleapis.com/bazel-apt stable/jdk1.8 amd64 Packages
     2.0.1 500
        500 https://storage.googleapis.com/bazel-apt stable/jdk1.8 amd64 Packages
     2.0.0 500
        500 https://storage.googleapis.com/bazel-apt stable/jdk1.8 amd64 Packages
     1.2.1 500
        500 https://storage.googleapis.com/bazel-apt stable/jdk1.8 amd64 Packages
     1.2.0 500
        500 https://storage.googleapis.com/bazel-apt stable/jdk1.8 amd64 Packages
     1.1.0 500
        500 https://storage.googleapis.com/bazel-apt stable/jdk1.8 amd64 Packages
     1.0.1 500
        500 https://storage.googleapis.com/bazel-apt stable/jdk1.8 amd64 Packages
     1.0.0 500
        500 https://storage.googleapis.com/bazel-apt stable/jdk1.8 amd64 Packages
bazel help
                                                            [bazel release 0.14.1]
Usage: bazel <command> <options> ...

Available commands:
  analyze-profile     Analyzes build profile data.
  build               Builds the specified targets.
  canonicalize-flags  Canonicalizes a list of bazel options.
  clean               Removes output files and optionally stops the server.
  coverage            Generates code coverage report for specified test targets.
  cquery              Loads, analyzes, and queries the specified targets w/ configurations.
  dump                Dumps the internal state of the bazel server process.
  fetch               Fetches external repositories that are prerequisites to the targets.
  help                Prints help for commands, or the index.
  info                Displays runtime info about the bazel server.
  license             Prints the license of this software.
  mobile-install      Installs targets to mobile devices.
  print_action        Prints the command line args for compiling a file.
  query               Executes a dependency graph query.
  run                 Runs the specified target.
  shutdown            Stops the bazel server.
  test                Builds and runs the specified test targets.
  version             Prints version information for bazel.

Getting more help:
  bazel help <command>
                   Prints help and options for <command>.
  bazel help startup_options
                   Options for the JVM hosting bazel.
  bazel help target-syntax
                   Explains the syntax for specifying targets.
  bazel help info-keys
                   Displays a list of keys used by the info command.
`
As you can see when using bazel help, it says that the actual version is **bazel release 0.14.1**.

**Comment by philwo** [comment]
Hi @Keryen,

thanks for the info! We can see here that you have correctly installed the latest version of Bazel 2.2.0 via apt-get (which goes to `/usr/bin/bazel`), but you also have an older version of Bazel (0.14.1) installed manually in `/usr/local/bin/bazel`.

Because `/usr/local/bin` comes before `/usr/bin` in `$PATH`, you will get the old version if you just run `bazel`. To verify, you can try to directly run `/usr/bin/bazel version` and it should show you the new Bazel version.

I would recommend to remove the old binary via `sudo rm /usr/local/bin/bazel` and everything should work fine then :)

Cheers,
Philipp

**Comment by Keryen** [comment]
It worked! Thank you very much!
