### ISSUE TITLE
io_bazel_rules_go, git_repository, and offline builds

### ISSUE THREAD

**Issue by dmitri-d** [bazelbuild/bazel#10984]
### Description of the problem / feature request:

Projects that rely on io_bazel_rules_go cannot be built offline. The problem is two-fold: these are internal bazel dependencies that can be hard to discover and can change without a warning. The other side of the problem is that a bunch of the dependencies are defined via ```git_repository```, the results of which cannot be used with ```--distdir```.  

### Feature requests: what underlying problem are you trying to solve with this feature?

At a minimum extend ```--distdir``` to support git repositories. Ideally, provide a command to bundle *all* external dependencies into a distdir.

**Comment by djamaile** [comment]
Did you figure out a way to do this?
