### ISSUE TITLE
ctx.attr is poorly documented

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#1098]
I'm trying to implement a function to compute the outputs of my rule. As input this gets `ctx.attr` but the format is poorly documented.

http://bazel.io/docs/skylark/lib/ctx.html#attr

In particular it seems that `_`prefixed attributes are converted to `$` prefixed names.

**Comment by davidzchen** [comment]
De-duping with #945 since it is the same problem.

We would have to make some changes to how the documentation for the Skylark Library is generated.
