### ISSUE TITLE
ebb86fcdc202c440a362a54f6b0de8a049dfa84b breaks //third_party targets

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/bazel#10995]
### Description of the problem / feature request:

ebb86fcdc202c440a362a54f6b0de8a049dfa84b breaks (disabled) license checking for targets under `//third_party` if they are created by macros. Works fine with parent commit (2feb36fc51e085040d7978f919f0dcf9a14a2b5f).
/cc @alandonovan 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`third_party/foo/foo.bzl`:
```starlark
def _impl(ctx):
    pass

_foo = rule(implementation=_impl)

def foo(**kwargs):
    _foo(**kwargs)
```

`third_party/foo/BUILD`:
```starlark
load(":foo.bzl", "foo")
foo(name="foo")
```

```
$ bazel build //...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: df222c8b-cb02-4128-acba-7e71697f0a5f
ERROR: /Users/yannic/Downloads/foo/third_party/foo/BUILD:3:1: third-party rule '//third_party/foo:foo' lacks a license declaration with one of the following types: notice, reciprocal, permissive, restricted, unencumbered, by_exception_only
ERROR: package contains errors: third_party/foo
ERROR: error loading package 'third_party/foo': Package 'third_party/foo' contains errors
INFO: Elapsed time: 3.416s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
```

**Comment by aiuto** [comment]
Thanks for spotting this.
A side issue is why this check is even happening.  Enforcing for //third_party/... is an ancient Google policy. It should not happen in Bazel.

@alandonovan   licenses() has some ugly implementation details. The licenses() rule tries to behave like it would have been a default set in package() (e.g. default_compatible_with), but that behavior is scattered around.  IIRC, the value is only kept with the package. When the rule needs it, the code looks for the attribute set at the rule level. If not found, it gets it from the package. So there is special casing all over the place. 
FWIW, the replacement (applicable_liceneses) acts like a normal attribute. At target configuration, if the value was not set explicitly, we take the package default and copy it into the target. Then we never have to inspect the package again.

**Comment by alandonovan** [comment]
Thanks Tony for the diagnosis. I carelessly removed a negation operator in ebb86fc. Will restore it presently.

**Comment by aiuto** [comment]
Fix submitted

**Comment by Yannic** [comment]
Fix confirmed.

Was a test for this added as part of the fix (the public commit doesn't include one)? If not, could we add one to avoid breaking this in the future?

**Comment by jin** [comment]
Closing as this has been fixed.
