### ISSUE TITLE
Add end-to-end example

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/bazel#11]
Would be awesome if the docs had an example for a complete App with a Java backend (say),
to showcase Bazel's ability to build everything a developer needs.

**Comment by kchodorow** [comment]
Can you be more specific?  "I want to see an app that that has... at least x java_* rules... can serve a webpage... is a mobile app... has external dependencies... whatever?"  An example program that you think is about right?  (e.g., a todo list? libgdx?)

**Comment by cgrushko** [comment]
I probably posted this prematurely, but basically, I'd like to answer a question that's going to come up often: "why should I try Bazel? what does it give me that I don't get from Gradle or xcodebuild?"

A single build-system which builds my iOS app, my backend (written in Java) and my Android app sounds like an awesome advantage, and I wish we could showcase it :)

**Comment by damienmg** [comment]
Done in github.com/bazelbuild/example in the tutorial folder. Also the tutorial is now on bazel.io.
