### ISSUE TITLE
Bazel builds without internet connection

### ISSUE THREAD

**Issue by anthpi** [bazelbuild/bazel#11001]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Currently Bazel will download necessary dependencies on demand from the internet the first time they are needed. There are several scenarios when this is impossible/not working very well:
1) Builds are run on the machine with no internet access (by design or due to security).
2) Reproducibility of the builds can't be guaranteed because Bazel depends on external servers that can disappear or content be changed without our knowledge/control.

### Feature requests: what underlying problem are you trying to solve with this feature?

1. Enable Bazel to be run on machines without internet access.
2. Having self-contain Bazel installation so that no files need to be downloaded. Or a convenient way to populate a --distdir directory or internal HTTP storage, with all required files, without cumbersome patching of WORKSPACE files.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Clean the local Bazel cache
2. Start the build
3. Observe files being downloaded from the internet.

### What operating system are you running Bazel on?

RHEL7

### What's the output of `bazel info release`?

release 2.2.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

858a4b1a44f1058f5bbec9ea778421038ef34f10

###  Have you found anything relevant by searching the web?

There are many users raising similar concerns and would like to be able to run Bazel builds without internet access.

### Any other information, logs, or outputs that you want to share?

Currently we are applying some of the patches to the Bazel before building and releasing it for our internal use. There is a "--distdir" flag that can be used to specify additional read-only directories to look for files instead of fetching them. This flag is currently being used as a workaround but there is a lot of manual work involved to maintain the installation and there is no easy/reliable way (or at least one that we are aware of) to know all the possible files that Bazel going to need beforehand.

**Comment by jin** [comment]
I've written some docs on how to pack a distdir for a particular Bazel version in a reliable/easy way: https://docs.bazel.build/versions/master/guide.html#running-bazel-in-an-airgapped-environment

Note that this is still a manual process.

**Comment by kevgo** [comment]
@jin your instructions seem to archive only the "implicit runtime dependencies" of Bazel. A codebase I use with Bazel also depends on other dependencies like JUnit, Maven, etc. Here is a list of commands I have to run in order to get all dependencies:

```
bazel fetch '@bazel_tools//tools/build_defs/repo:*'
bazel fetch '@rules_java//java:*'
bazel fetch '@rules_cc//cc:*'
bazel fetch @local_config_platform//...
bazel fetch @local_config_sh//...
bazel fetch @maven//...
bazel fetch @org_opentest4j_opentest4j//jar:jar
bazel fetch @org_junit_jupiter_junit_jupiter_params//jar:jar
bazel fetch @org_junit_jupiter_junit_jupiter_engine//jar:jar
bazel fetch @org_junit_platform_junit_platform_console//jar:jar
bazel fetch @org_junit_platform_junit_platform_engine//jar:jar
bazel fetch @org_junit_platform_junit_platform_commons//jar:jar
bazel fetch @org_junit_platform_junit_platform_suite_api//jar:jar
bazel fetch @org_junit_platform_junit_platform_launcher//jar:jar
bazel fetch @org_apiguardian_apiguardian_api//jar:jar
bazel fetch @remote_coverage_tools//:coverage_report_generator
bazel fetch @remotejdk11_linux//:jdk
```

Is there a way to make Bazel download and export these dependencies as an archive as well in addition to its implicit runtime dependencies, so that I can make them available via `--distdir` or another way inside my airgapped environment? Thanks for all the great support you do for Bazel btw! Really appreciated!

**Comment by Spanni26** [comment]
Struggling at the same point....need to build a bazel project without a internet connection. I try it for days now....very frustrating.

**Comment by huangh12** [comment]
I have to say the indispensable internet connection and the repeat fresh downloading of dependencies(without caching) has make bazel a dammit disgusting tool for me.

**Comment by achauvin-wish** [comment]
Has there been any solution for this issue?

**Comment by fitzner** [comment]
With Bazel 5.0.0 Bzlmod has been introduced. It would be great if Bazel could retrieve the internal dependencies via Bzlmod instead of the WORKSPACE approach. Could be bound to the flag https://docs.bazel.build/versions/main/command-line-reference.html#flag--experimental_enable_bzlmod

**Comment by dieortin** [comment]
Any progress on this?

**Comment by orowith2os** [comment]
Also interested on hearing how one would go about achieving this; I previously attempted to build Mediapipe for Flathub, which requires offline builds, and it was not a pleasant experience. 

It would be amazing if there was a script or something along those lines to generate a list of sources (ideally with their checksums) to pull from and pipe into Bazel at build-time, and is what we at Flathub do with e.g. Cargo: we read all of the sources from the Cargo lockfile and download them before building.

**Comment by vowstar** [comment]
For security reasons, gentoo packages also require offline builds, so this feature is very useful.
