### ISSUE TITLE
Support assembling via the Extensions API

### ISSUE THREAD

**Issue by emusand** [bazelbuild/bazel#11013]
### Description of the problem / feature request:

It is not possible to build assembly code with the Extensions API. Function [cc_common.compile(...)](https://docs.bazel.build/versions/2.2.0/skylark/lib/cc_common.html#compile) only supports C/C++ sources:

`ERROR: ... '.../file.asm' has wrong extension. The list of possible extensions for 'srcs' is: .cc,.cpp,.cxx,.c++,.C,.c`

### Feature requests: what underlying problem are you trying to solve with this feature?

We need to assemble ".asm" files in a custom rule. We have have a complex code generator in our build chain, which generates both C and assembly sources. Unfortunately there is no way to feed these generated sources to a `cc_library` rule. Instead we have to compile and assemble them in a custom rule. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Write a custom rule that calls cc_common.compile(...) with an assembly source file, with file extensions ".s", ".S" or ".asm".

I can provide you with a minimal example, if need be.

### What operating system are you running Bazel on?

Linux, RHEL7.6

### What's the output of `bazel info release`?

release 2.1.0

**Comment by emusand** [comment]
I suppose that this feature request was solved in bazel 3.1, with the following commit?

`87e3b8fb2d - Allow assembly sources in cc_common.compile (6 weeks ago) [Googler]`

**Comment by oquenchil** [comment]
Yes, that commit should do the trick.
