### ISSUE TITLE
Support non-standard public header file extensions in cc_common

### ISSUE THREAD

**Issue by emusand** [bazelbuild/bazel#11015]
### Description of the problem / feature request:

It is not possible to use custom file name extensions for public header files, when compiling with function `cc_common.compile(...)` in a custom rule:

`ERROR: ... '.../file.custom' has wrong extension. The list of possible extensions for 'public_hdrs' is: .h,.hh,.hpp,.ipp,.hxx,.h++,.inc,.inl,.tlh,.tli,.H`

This differs from the behavior of `cc_library(hdrs=...)`, which accepts any file name extensions.

Support any file name extensions in parameter `cc_library(public_hdrs=...)` to align with the behavior of `cc_library(hdrs=...)`.

### Feature requests: what underlying problem are you trying to solve with this feature?

We need to compile some of our C sources in a custom rule. We use non-standard file name extensions for some of our .h files. We can use them in `cc_library` rules, but they do not work in our custom rule.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Write a rule that compiles a C file with `cc_common.compile(...)` and set parameter `public_hdrs` to a list that contains a non-standard .h file name extension.

I can provide a minimal example, if need be.

### What operating system are you running Bazel on?

Linux, RHEL7.6

### What's the output of `bazel info release`?

release 2.1.0

**Comment by liubang** [comment]
When I tried to compile fbthrift, the following error occurred:
```
bazel-out/k8-fastbuild/bin/test_thrift/if/gen-cpp2/echo_types.tcc' has wrong extension. The list of possible extensions for 'public_hdrs' is: .h,.hh,.hpp,.ipp,.hxx,.h++,.inc,.inl,.tlh,.tli,.H
```
Because fbthrift produces header file with suffix tcc，but bazel dose not support .tcc header file.

**Comment by oquenchil** [comment]
Support added in https://github.com/bazelbuild/bazel/pull/11158

**Comment by emusand** [comment]
Please reopen this ticket again,

This feature request is more general than @liubang's commit. He just added ".tcc" as a supported filename extension, but we need other extensions (".sig" and ".ifx" to be more precise). It should be possible to configure what filename extensions to support, and not just use a hardcoded list.

**Comment by oquenchil** [comment]
This keeps coming up. I've just filed https://github.com/bazelbuild/bazel/issues/11356 to track the more general issue of extensions being hard-coded everywhere.

Currently, we don't have plans to work on this but if it turns out to be one of the biggest pains for users, we can re-evaluate our priorities.
