### ISSUE TITLE
bazel hangs trying to get client lock of non-existing pid

### ISSUE THREAD

**Issue by thekyz** [bazelbuild/bazel#11020]
### Description of the problem / feature request:

While launching a bazel coverage run under docker, bazel hangs complaining about not being able to take the server lock:

```
>>> Starting Bazel coverage: /repo/builder/repo/vobs/esam/build/standalone/unittests:unittests
INFO:bazel_run:using DEV_BIN: /ap/local/devtools/bin/
Another command holds the client lock:
pid=3725
owner=client
cwd=/repo/builder/repo/vobs/esam/build/standalone/unittests
```

That call was done under `docker run` so no other bazel process can be running. We've started looking at the bazel source to understand what could cause that issue and stumbled upon that comment in `blaze_utils_posix.cc`:
```
  // Take the exclusive server lock.  If we fail, we busy-wait until the lock
  // becomes available.
  //
  // We used to rely on fcntl(F_SETLKW) to lazy-wait for the lock to become
  // available, which is theoretically fine, but doing so prevents us from
  // determining if the PID of the server holding the lock has changed under the
  // hood.  There have been multiple bug reports where users (especially macOS
  // ones) mention that the Blaze invocation hangs on a non-existent PID.  This
  // should help troubleshoot those scenarios in case there really is a bug
  // somewhere.
```

Now, is this a known issue or has that just been left here and nobody has been seing that error ?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal 

This has happened only once for now.

### What operating system are you running Bazel on?

docker image based on centos7

### What's the output of `bazel info release`?

```
~ bazel info release
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
release 2.0.0
```

**Comment by philwo** [comment]
We run Bazel inside Docker on Bazel's CI and I cannot remember a single time that I've observed this. It might be something environment specific, but if so, I don't know what.

If you can reproduce it (even if just once) it would be nice to hear about your Docker host details and the docker run command-line. I'll close this for now, but please feel free to reply if you see this again.

**Comment by weivall** [comment]
I had this error when I misconfigured the **output_base** and **output_user_root**. They can't have the same values.

WRONG: 
      --output_user_root=.bazel_cache \
      --output_base=.bazel_cache \

CORRECT:
      --output_user_root=.bazel_cache \
      --output_base=.bazel_cache/output \
