### ISSUE TITLE
RBE: INVALID_ARGUMENT: Input tree has 93944 files, above the maximum of 70000

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#11039]
Trying to build [Gerrit Code Review](https://gerrit.googlesource.com/gerrit) on RBE, on Bazel@HEAD (5c1c0d1ed8643c90fba239d1bc642e4ebd044c2c) failing with:

```
  $ bazel build --verbose_failures --config=remote :release
  [...]
  ERROR: /home/davido/projects/gerrit2/polygerrit-ui/app/BUILD:5:1: Bundling JavaScript polygerrit-ui/app/gr-app-bundle-js.js [rollup] failed (Exit 34): java.io.IOException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Input tree has 93944 files, above the maximum of 70000
	at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.executeRemotely(GrpcRemoteExecutor.java:192)
	at com.google.devtools.build.lib.remote.RemoteSpawnRunner.lambda$exec$0(RemoteSpawnRunner.java:291)
[...]
```

Downstream issue is [here](https://crbug.com/gerrit/12511).

**Comment by ulfjack** [comment]
You're saying that this might be a regression? Is there any way for you to narrow down the Bazel commit that might have introduced it?

**Comment by davido** [comment]
What I said is: it is a regression in Gerrit Code Review Build tool chains:

* All stable branches used bower build tool chain and rules_closure, e.g. stable-3.1
* On master, couple of weeks ago, PolyGerrit was migrated to npm, rules_nodejs, ES6 modules.

So that I can build without any issue `:release` target with Bazel@HEAD stable-3.1 branch, but not master.

**Comment by davido** [comment]
It was fixed in Gerrit project: [1].

[1] https://gerrit-review.googlesource.com/c/gerrit/+/261014
