### ISSUE TITLE
how to choose different compiler toolchain for different Bazel target. 

### ISSUE THREAD

**Issue by lxlmummy** [bazelbuild/bazel#11033]
Hi, I have two question:
First, after read the https://docs.bazel.build/versions/master/tutorial/cc-toolchain-config.html，this link seems it is too complex to support to build a target with a customer toolchain, is there any way easier？
Second,  my project has different targets and some targets need to be compiled with host toolchain，others need to be compiled with the third pard tool chain，how can I do it？

**Comment by torgil** [comment]
If you do custom rules (eg, your own version of for instance cc_library), you can specify either your own toolchain_type or provide the rule with a toolchain either through provider or attribute. I have an attribute example in this bug report (which also may hit you):  https://github.com/bazelbuild/bazel/issues/10897

If you don't want to depend on all compilers and want different constraints for different targets (for toolchain resolution) you can switch platform using transitions on "//command_line_option:platforms".

**Comment by lxlmummy** [comment]
export CC=clang (customer toolchain cc)
export CXX=clang++(customer  toolchain gcc)
bazel build [my target....]

Does Baze support above way for build my target with customer toolchain?

**Comment by lxlmummy** [comment]
I've cross-compiled successfully！Tannks！
