### ISSUE TITLE
Failure to bootstrap bazel build 2.2.0 and 2.1.1 in arm64v8 docker container

### ISSUE THREAD

**Issue by settle** [bazelbuild/bazel#11038]
### Description of the problem / feature request:

Bootstrap bazel builds fail in arm64v8 docker containers for bazel 2.2.0 and 2.1.1.

### Feature requests: what underlying problem are you trying to solve with this feature?

Provide a dockerized bazel build method for arm64v8 hosts

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Using the following bazel-arm64v8.Dockerfile:
[bazel-arm64v8.Dockerfile.txt](https://github.com/bazelbuild/bazel/files/4396525/bazel-arm64v8.Dockerfile.txt)

docker build --build-arg BAZEL_VERSION=2.2.0 -f bazel-arm64v8.Dockerfile -t arm64v8/bazel:2.2.0 .

### What operating system are you running Bazel on?

Ubuntu 18.04

### Any other information, logs, or outputs that you want to share?

ERROR: /bazel/src/BUILD:103:1: PythonZipper src/create_embedded_tools.zip failed (Exit 255)
Target //src:bazel_nojdk failed to build
INFO: Elapsed time: 2002.556s, Critical Path: 484.96s
INFO: 1190 processes: 1190 local.
FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel
The command '/bin/sh -c cd /bazel &&     env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh' returned a non-zero code: 1

**Comment by settle** [comment]
I also tried Bazel version 0.29.1 as mentioned in [#8382](https://github.com/bazelbuild/bazel/issues/8382), but that version also failed exactly the same way.

**Comment by philwo** [comment]
That should be fixed in recent Bazel versions.
