### ISSUE TITLE
Errors are swallowed when depending on a directory and file within it

### ISSUE THREAD

**Issue by migueloller** [bazelbuild/bazel#11032]
### Description of the problem / feature request:

When using `genrule` with a directory and a file contained in that directory, function errors are swallowed and instead Bazel fails with the following error:

```
ERROR: /path/to/BUILD:18:1: Action path/to/target failed: I/O exception during sandboxed execution: path/to/glob/root (File exists)
Target //path/to:target failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The following `BUILD` file is enough to reproduce this issue. Ensure an empty `dir` and `dir/file` exist next to the `BUILD` file. If the `cmd` is changed so that the exit code is `0`, Bazel runs without issue. If instead the exit code is left as `1` but `"dir"` or `"dir/file"` are removed from `srcs`, Bazel will not swallow the error and output `Boom!` as expected.

```starlark
genrule(
    name = "repro",
    srcs = [
        "dir",
        "dir/file",
    ],
    outs = ["out"],
    cmd = "touch $(execpath out) && >&2 echo Boom! && exit 1",
)
```

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 2.2.0

### Any other information, logs, or outputs that you want to share?

I originally found this issue while working with `rules_nodejs` and had opened an issue there: https://github.com/bazelbuild/rules_nodejs/issues/1744

**Comment by migueloller** [comment]
More than just error swallowing, it seems that this always just results in an error. Here's a repro BUILD file. Ensure that `dir` has a file, like `message.txt.`, for example.

```starlark
genrule(
    name = "repro",
    srcs = glob(
        ["dir/**"],
        exclude_directories = 0,
    ),
    outs = ["out"],
    cmd = "touch $(@)",
)
```

I'm also seeing some weird behavior in a more complicated setup. The error seems to go away if I can successfully build the target. This would be the equivalent of commenting out `exclude_directories = 0`, running it (it should succeed), uncommenting what was just commented, and running it again and then not seeing the error. I tried to reproduce this in a minimal way like shown above, but unfortunately I wasn't able to.

**Comment by philwo** [comment]
My guess is that the sandbox symlinks the directory `dir` first and then fails to symlink the file inside it, because doing so would mean overwriting a file in your workspace directory (because `dir` is now a symlink pointing into it).

Not sure if we can fix it - if someone comes up with a clever idea, happy to review a PR.
