### ISSUE TITLE
Allow selecting different python paths for different platforms

### ISSUE THREAD

**Issue by r4nt** [bazelbuild/bazel#11035]
Context:
In TF, we want to do ~full remote builds. Even full remote builds execute some python targets locally (for example to get git repo information).
We want to be able to have python interpreters in different paths locally vs. on the remote image, as changing the default python binary (/usr/bin/python*) on a linux distribution often breaks random things.

Thus, I'd like to be able to install python in /usr/local/bin, and call /usr/local/bin/python3.X remotely, while calling /usr/bin/python3 locally for local python tools.

I've tried to trick bazel into this using relative paths, but PyRuntime checks that the python path it gets is absolute and fails if it isn't.

**Comment by brandjon** [comment]
This is the exact use case python toolchains should be able to handle. You'll want to register toolchains in your WORKSPACE for the remote and local platforms, and bind toolchains to platforms using constraints. See python toolchain [docs](https://github.com/bazelbuild/rules_python/blob/master/docs/python.md) and general toolchain [docs](https://docs.bazel.build/versions/2.2.0/toolchains.html) (you can ignore the details for rule authors and focus on platforms, constraint values, and the `toolchain()` rule).

**Comment by r4nt** [comment]
That worked in general, thanks!
Now my next problem is that I can't convince the platform selection to *build* the py_binary that the genrule that runs locally uses to use the local platform/python toolchain.
I've tried with configuration transitions, but if I add platform/host_platform in the transition, it still uses the remote platform (not sure whether that interacts with me currently also passing --platforms on the command line).
If I just annotate the py_binary with an exec-compatible-with to the right constraint that only matches my local platform & python toolchain, it works splendidly, but annotating the py_binary to only be able to run locally seems like a big hack. Is there a way to change exec-compatible-with in a config transition?

**Comment by brandjon** [comment]
+@katre 

> I've tried with configuration transitions, but if I add platform/host_platform in the transition, it still uses the remote platform (not sure whether that interacts with me currently also passing --platforms on the command line).

I would imagine that transitioning on `--platform` changes the target platform, and transitioning on `--host_platform` would have no effect (since the host configuration is fixed at the time the build invocation begins).

The execution platform would be determined by the toolchain resolution process, which happens for each configured target. Toolchain resolution takes into account the requested target platform and selects an appropriate execution platform, such that all constraints between toolchains and platforms are satisfied.

I don't know how `genrule`s determine their execution platform -- if it's always the same as the host platform or what. But whatever toolchain resolution chooses ought to determine the target platform for building the `py_binary` in the `genrule`'s `exec_tools` attribute.

Note that if you're using `tools` instead of `exec_tools`, then your `py_binary` is being built in the host configuration, which is not necessarily the same platform as the execution platform. I don't know how `exec_compatible_with` behaves for the host config.

**Comment by katre** [comment]
You're correct that you can't meaningfully transition and change the value of "--host_platform": whatever you set will be ignored since the singleton host configuration already exists, and any host transitions will just use that.

Genrule does the same toolchain resolution process to select the execution platform, but doesn't have any toolchain dependencies so it will always end up selecting the highest priority execution platform. This may change a bit in the future, since we're working to unify execution platform selection and execution strategy selection, and there are ways to change the strategy for genrules (ie, make them local, remote, sandboxed, etc).

**Comment by r4nt** [comment]
I do tag the genrule with the right exec_compatible_with so that it has to select the right execution platform - the problem is that the py_binary I depend on in the genrule is *not* using that platform.

I've tried by using a local_genrule approach that Jakob created here:
https://github.com/buchgr/local-genrule/blob/master/local_genrule.bzl

but toolchain selection still tells me it's using the wrong platform.

**Comment by byronyi** [comment]
Any updates? I have been struggling to switch my TF nightly builds to support multi-python, but I am stuck in many different places.

**Comment by katre** [comment]
@r4nt: What platform is being selected, and what is being used? I'm afraid I don't understand your case enough to offer much advice. Do you have reproduction directions I can try?

**Comment by byronyi** [comment]
Another issue seems to come from pybind11. Re-using RBE cache from Python3.5 when building Python3.6 **occasionally** gives incorrect Python include/linkage:

```
ERROR: /tensorflow_src/tensorflow/python/keras/api/BUILD:121:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v1 failed (Exit 1)
Traceback (most recent call last):
  File "/bazel-buildfarm/default/operations/645f15ad-1f8e-4d83-86b0-0dfa2f3fd256/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/bazel-buildfarm/default/operations/645f15ad-1f8e-4d83-86b0-0dfa2f3fd256/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 64, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/bazel-buildfarm/default/operations/645f15ad-1f8e-4d83-86b0-0dfa2f3fd256/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/framework/framework_lib.py", line 24, in <module>
    from tensorflow.python.framework.device import DeviceSpec
  File "/bazel-buildfarm/default/operations/645f15ad-1f8e-4d83-86b0-0dfa2f3fd256/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/framework/device.py", line 24, in <module>
    from tensorflow.python.framework import device_spec
  File "/bazel-buildfarm/default/operations/645f15ad-1f8e-4d83-86b0-0dfa2f3fd256/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/framework/device_spec.py", line 21, in <module>
    from tensorflow.python.util.tf_export import tf_export
  File "/bazel-buildfarm/default/operations/645f15ad-1f8e-4d83-86b0-0dfa2f3fd256/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/util/tf_export.py", line 48, in <module>
    from tensorflow.python.util import tf_decorator
  File "/bazel-buildfarm/default/operations/645f15ad-1f8e-4d83-86b0-0dfa2f3fd256/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/util/tf_decorator.py", line 64, in <module>
    from tensorflow.python.util import tf_stack
  File "/bazel-buildfarm/default/operations/645f15ad-1f8e-4d83-86b0-0dfa2f3fd256/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/util/tf_stack.py", line 28, in <module>
    from tensorflow.python import _tf_stack
ImportError: Python version mismatch: module was compiled for Python 3.6, but the interpreter version is incompatible: 3.5.9 (default, May  5 2020, 11:39:11) 
[GCC 5.4.0 20160609].
ERROR: /tensorflow_src/tensorflow/tools/compatibility/BUILD:264:1 Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v1 failed (Exit 1)
```

I have added ``tags = ["no-cache"]`` to ``pybind_extension`` to workaround this issue.

cc @av8ramit @gunan

**Comment by r4nt** [comment]
@byronyi - this shouldn't be a blocker for TF multi-python, as we're working around that by tagging the rules.

**Comment by r4nt** [comment]
@katre - it uses the remote platform that is the default for the build. I don't have a small repro unfortunately, but why would you expect this to work? I'd expect that I need a platform in the transition.

**Comment by byronyi** [comment]
> @byronyi - this shouldn't be a blocker for TF multi-python, as we're working around that by tagging the rules.

Not with https://github.com/tensorflow/tensorflow/commit/9ca9a4f8e9b4d60408a092db4320805711367042 added. It goes well with the first Python version, but when I build with the next Python version, it incorrectly hit cache and pybind11 complains Python version mismatch. 

I could paste a detailed log on this error.

**Comment by r4nt** [comment]
I'd need to see your command line, as it worksforme(tm)

**Comment by byronyi** [comment]
`ubuntu16.04-gcc7_manylinux2014-cuda10.1-cudnn7-tensorrt6.0` is a port of the official manylinux2010 image, which install python version to `/usr` prefix due to my environment constraints. 

`/usr/bin/python3` points to `/usr/bin/python3.5`.

```
    tensorflow_rbe_config(
        name = "ubuntu16.04-gcc7_manylinux2014-cuda10.1-cudnn7-tensorrt6.0",
        compiler = "/dt7/usr/bin/gcc",
        compiler_prefix = "/usr/bin",
        cuda_version = "10.1",
        cudnn_version = "7",
        os = "ubuntu16.04-manylinux2014-multipython",
        python_versions = ["2.7", "3.5", "3.6", "3.7", "3.8"],
        tensorrt_install_path = "/usr",
        tensorrt_version = "6.0",
    )
```

Bazel command line:

```
bazel build \
    --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 \
    --config=avx2_linux \
    --config=short_logs \
    --config=xla \
    --crosstool_top="@ubuntu16.04-gcc7_manylinux2014-cuda10.1-cudnn7-tensorrt6.0//crosstool:toolchain" \
    --define=EXECUTOR=remote \
    --define=using_cuda_nvcc=true \
    --extra_execution_platforms="@ubuntu16.04-gcc7_manylinux2014-cuda10.1-cudnn7-tensorrt6.0_config_platform//:platform" \
    --extra_toolchains="@ubuntu16.04-gcc7_manylinux2014-cuda10.1-cudnn7-tensorrt6.0_config_cuda//crosstool:toolchain-linux-x86_64" \
    --jobs=192 \
    --platforms="@ubuntu16.04-gcc7_manylinux2014-cuda10.1-cudnn7-tensorrt6.0_config_platform//:platform" \
    --python_path="/usr/bin/python3.6" \
    --remote_cache=$CI_CLUSTER \
    --remote_download_toplevel \
    --remote_executor=$CI_CLUSTER \
    --remote_timeout=3600 \
    --repo_env=PYTHON_BIN_PATH="/usr/bin/python3.6" \
    --repo_env=TF_NEED_CUDA=1 \
    --repo_env=TF_NEED_TENSORRT=1 \
    --repo_env=TF_CUDA_VERSION=10.1 \
    --repo_env=TF_CUDNN_VERSION=7 \
    --repo_env=TF_CUDA_CONFIG_REPO="@ubuntu16.04-gcc7_manylinux2014-cuda10.1-cudnn7-tensorrt6.0_config_cuda" \
    --repo_env=TF_NCCL_CONFIG_REPO="@ubuntu16.04-gcc7_manylinux2014-cuda10.1-cudnn7-tensorrt6.0_config_nccl" \
    --repo_env=TF_PYTHON_CONFIG_REPO="@ubuntu16.04-gcc7_manylinux2014-cuda10.1-cudnn7-tensorrt6.0_config_python3.6" \
    --repo_env=TF_TENSORRT_CONFIG_REPO="@ubuntu16.04-gcc7_manylinux2014-cuda10.1-cudnn7-tensorrt6.0_config_tensorrt" \
    --spawn_strategy=remote,worker,sandboxed,local \
  //tensorflow/tools/pip_package:build_pip_package
````

**Comment by r4nt** [comment]
@katre - here's a repro:
https://github.com/r4nt/local-genrule/tree/platforms

@byronyi - installing python in /usr is going to mess with the system python, which is hard to debug - why does that matter on the remote machine? (also, this sounds like a bug we should discuss on the TF tracker, it has nothing to do with this bazel problem, other than debugging these setups taking many days for experts)

**Comment by byronyi** [comment]
Sure, I will open an issue on TF side.

**Comment by katre** [comment]
@r4nt: Thank you for the reproduction case. I'm still not clear: how would you prefer to identify a py_binary that  should use a specific python evrsion?

**Comment by r4nt** [comment]
@katre - I don't want to identify a py_binary to use a specific python version, I want to create a genrule that uses a specific platform & python_version, and that needs the py_binary the genrule runs to have the right PYTHON_BIN_PATH compiled into it.

To make sure I'm not running into xyproblem:
The original problem is that I:
- have a remote docker image that installs python into /usr/local/bin/python<version> and does that for multiple different python versions
- I do not want special requirements on the local host
- there are some genrules that require to be run locally, and I want to run them with the python version installed on the local host (e.g. /usr/bin/python3.5), while per default everything is run remotely (targeting, for example, /usr/bin/python3.7)

**Comment by katre** [comment]
We have an existing system where you can add the "local" tag to a target to force local execution. Currently, that doesn't interact properly with execution platforms, but working on that is my next goal (you can see the [design doc](https://docs.google.com/document/d/1U9HzdDmtRnm244CaRM6JV-q2408mbNODAMewcGjnnbM/edit#) for details).

It will, unfortunately, be a while until this is fully usable, but I think it's the right solution to your problem, and until then, can you use the workaround with the `exec_compatible_with` property?

**Comment by r4nt** [comment]
I don't yet understand how I can switch the *platform* with your proposal, especially in a config transition.

**Comment by katre** [comment]
There are two separate cases: if you just want a specific target to run on the host platform, you tag is as "local", and it will use a non-remote execution strategy (either standalone or sandbox, depending on your spawn strategy flags):

```
genrule(
    name = "run-local-script",
    ....
    exec_tools = [":script"],
    tags = ["local"],
)
```

The work I am doing now will cause the execution platform to consider the strategy, so this genrule will then also have an execution platform set to the host platform. Then, due to the use of `exec_tools`, the `script` target will be built to target that platform (effectively setting the target platform of that instance of `script` to be the host platform).

The second case is the more generic case, where you want to specify that a specific target is built for a specific platform. For that, you will need a custom Starlark transition to change the `--platforms` flag to the desired platform, which means writing a custom rule that can use the transition. We have plans to make this simpler, by adding a `platform` attribute to many rules, but we're holding off on that because it will cause a lot of complications for google-internal systems.

**Comment by r4nt** [comment]
1. Ok, and I can control the host platform with something like register_host_platforms?

2. btw, the example I put together based on Jakob's macro *does* set platforms in the transition, but that doesn't seem to have any effect - is that a bug that will change?

**Comment by katre** [comment]
You set the host platform with the `--host_platform` flag, but I'd be curious to know what about the current auto-detection doesn't work for you.

For your reproduction, I commented out the `exec_compatible_with`:
```
$ bazel build remote_version.txt local_version.txt && cat bazel-bin/remote_version.txt && cat bazel-bin/local_version.txt
Starting local Bazel server and connecting to it...
/usr/bin/python3.6
/usr/bin/python3

$ bazel cquery 'local_version.txt'
//:local_version.txt (92320c742c5d2b969e1b4712451344e487382d03c323ae0276bb271ba2ae0045)

$ bazel config 92320c742c5d2b969e1b4712451344e487382d03c323ae0276bb271ba2ae0045 | egrep '(platforms|host_platform)'
INFO: Displaying config with id 92320c742c5d2b969e1b4712451344e487382d03c323ae0276bb271ba2ae0045
  extra_execution_platforms: []
  host_platform: null
  incompatible_auto_configure_host_platform: true
  platforms: [@local_config_platform//:host]
  target_platform_fallback: @bazel_tools//platforms:target_platform
  incompatible_use_platforms_repo_for_constraints: false
```

So the platforms flag isn't being changed by the transition, as you suspected. I'm going to ask @juliexxia for her advice, since she knows more about transitions than I do.

**Comment by juliexxia** [comment]
Tried to clone the example repro and run the same command line as you to do some debugging and got the following error:

```
juliexxia-macbookpro11% /Users/juliexxia/bin/bazel build remote_version.txt local_version.txt && cat bazel-bin/remote_version.txt && cat bazel-bin/local_version.txt 
ERROR: While resolving toolchains for target //:py_script: No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type. Maybe --incompatible_use_cc_configure_from_rules_cc has been flipped and there is no default C++ toolchain added in the WORKSPACE file? See https://github.com/bazelbuild/bazel/issues/10134 for details and migration instructions.
ERROR: Analysis of target '//:local_version.txt' failed; build aborted: No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type. Maybe --incompatible_use_cc_configure_from_rules_cc has been flipped and there is no default C++ toolchain added in the WORKSPACE file? See https://github.com/bazelbuild/bazel/issues/10134 for details and migration instructions.
INFO: Elapsed time: 12.159s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (14 packages loaded, 83 targets configured)
    Fetching @local_config_cc; Restarting.
```

Potentially unrelated but maybe I'm missing a piece of set up?

I'm not fully caught up on all the context here, but I looked through the transitions code and it seems pretty run-of-the-mill so it should work fine. I noticed that you're transitioning on the exec_tool but it's the output itself whose configuration you're looking at for the result of the transition - is that expected? That an action run with a tool in a specific configuration will create outputs in that configuration? Is that confusion here?

I also notice you're directly cquerying the output of the genrule to get that configuration hash. I would expect you to want something like

`$ bazel cquery rdeps(//:*, //:local)`

or

`$ bazel cquery `local_version.txt` --universe_scope=//:local`

to get local_version.txt as its created by :local

Again, haven't taken the time to get the whole context here, so let me know if I'm missing anything!

**Comment by katre** [comment]
That failure is odd. I'm on a linux machine, and my cc toolchains work properly, so I'm not sure what's wrong.

Both of those cqueries give me the same configuration: 92320c742c5d2b969e1b4712451344e487382d03c323ae0276bb271ba2ae0045

That makes sense because output files are configured targets, so it should report the correct configuration.
