### ISSUE TITLE
Incorrect parsing of BRDA lines in LcovParser.java

### ISSUE THREAD

**Issue by paitel** [bazelbuild/bazel#11051]
### Description of the problem:

This snippet of code: https://github.com/bazelbuild/bazel/blob/master/tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator/LcovParser.java#L283

Is trying to parse BRDA lines which have the following format: BRDA:<line number>,<block number>,<branch number>,<taken>

<taken> is either "-" if branch block was never executed, or a number indicating how many times the branch was executed.

In case that LCOV file contains a line like this one: 

BRDA:52,0,1,-

Piece of code on line 283 will exception:

if (taken.equals(TAKEN)) {
        executionCount = Integer.parseInt(taken);
        wasExecuted = true;
}

An exception is logged (WARNING: Tracefile contains an invalid number BRDA line BRDA:52,0,1,-) and processing continues. Ultimately, this will lead to incorrect coverage numbers.

Seems like the line should say if (**!**taken.equals(TAKEN)){ ...

Example of a file where coverage will be incorrectly calculated:
[example.info.txt](https://github.com/bazelbuild/bazel/files/4417186/example.info.txt)

**Comment by c-mita** [comment]
`BRDA` does not appear to be handled correctly; unfortunately fixing this is a little more involved than reversing that test.

https://github.com/bazelbuild/bazel/blob/441586bec9048ba07d5960d5954c103783eed33f/tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator/SourceFileCoverage.java#L228

The source file maintains a mapping of `line -> (block_number, branch_number, execution_count)`, but this association isn't valid; multiple `branch_numbers` can occur on the same line.
