### ISSUE TITLE
`python_stub_template.txt` creates non-cacheable builds because the Python imports order vary from build to build

### ISSUE THREAD

**Issue by guillaumep** [bazelbuild/bazel#11050]
### Description of the problem:

`python_stub_template.txt` creates non-cacheable builds because the Python imports order vary from build to build

For example when building a particular py_test target, sometimes I get the following `python_imports` variable (in the python launcher script generated via `python_stub_template.txt`):

```
python_imports = 'outbox/tools/next_tag:pypi__py3__six_1_14_0:pypi__py3__pyparsing_2_4_0:pypi__py3__packaging_19_0:pypi__py3__zipp_0_5_1:pypi__py3__importlib_metadata_0_17:pypi__py3__pluggy_0_12_0:pypi__py3__py_1_8_0:pypi__py3__attrs_19_1_0:pypi__py3__more_itertools_7_0_0:pypi__py3__wcwidth_0_1_7:pypi__py3__pytest_5_3_5:outbox/tools/tests_utils'
```

and other times I get the following:

```
python_imports = 'outbox/tools/next_tag:pypi__py3__py_1_8_0:pypi__py3__zipp_0_5_1:pypi__py3__importlib_metadata_0_17:pypi__py3__pluggy_0_12_0:pypi__py3__more_itertools_7_0_0:pypi__py3__pyparsing_2_4_0:pypi__py3__six_1_14_0:pypi__py3__packaging_19_0:pypi__py3__wcwidth_0_1_7:pypi__py3__attrs_19_1_0:pypi__py3__pytest_5_3_5:outbox/tools/tests_utils'
```

You will see that the order of the imports is not the same, which means that the sha256 of the launcher script is not the same, resulting in the test not being cached.

By looking at the Bazel source code, I suspect that the issue might be here:

https://github.com/bazelbuild/bazel/blob/710955a422819b7fe951a271b2b4cc3bbe6edf7f/src/main/java/com/google/devtools/build/lib/bazel/rules/python/BazelPythonSemantics.java#L170

If I understand correctly, `common.getImports()` returns a set structure, which is then converted to a list. The `toList` function might not be deterministic, meaning the order of the items is probably not guaranteed. Should this list be sorted before being feed to the `Joiner`?

### How to reproduce and operating system

The build is being done on a CentOS 7 Docker image we generated, using Bazel 2.2.0. Just launching the build twice (we use TeamCity) is sufficient to reproduce.

I can see comparing the execution logs of both builds that the generated launcher script has a different hash, even though no source code change had been done.

### What's the output of `bazel info release`?

release 2.2.0

**Comment by guillaumep** [comment]
@brandjon The following patch seems to fix the issue:
https://github.com/guillaumep/bazel/commit/3ab0ee6af0fdf136f4ca538adc2a979c5fa7fdc1

Not too sure its proper Java so I have not proposed a PR. I'll gladly accept any comment to improve the code and submit a PR if you think its an appropriate fix!

**Comment by brandjon** [comment]
> If I understand correctly, `common.getImports()` returns a set structure, which is then converted to a list.

It actually returns a `NestedSet`, which in the Java code is how we spell [`depset`](https://docs.bazel.build/versions/2.2.0/skylark/lib/depset.html) -- it provides a deterministic iteration order, so any non-determinism must be in the inputs.

Sorting the path entries would give you a deterministic output, but you're clobbering whatever order the underlying targets gave you. It'd be better to root out the non-determinism at its source.

Are those paths being produced by `rules_python`? If so, you may need to use a commit after bazelbuild/rules_python#279.

**Comment by guillaumep** [comment]
Thanks for the very fast answer @brandjon. We are using a forked version of rules_python with patches to ease working with a mixture of Python 2 and 3 code:
https://github.com/guillaumep/rules_python

The rules includes the commit you mentionned -- I added the commit to our fork this morning but it did not fix our issue. I'll rebase our fork to the latest master from bazelbuild/rules_python, see if it helps.

Closing this issue, I hope I can find the non-determinism source in our own code base.

**Comment by guillaumep** [comment]
I was able to find and fix the source of non-determinsm in our fork of rules_python:

https://github.com/guillaumep/rules_python/commit/a5db1ba31d4308aa21aab0183fd40a8a87de1702

We introduced non-determinism when we introduced in our rules when we cherry-picked code that added handling of metadata in wheels:

https://github.com/guillaumep/rules_python/commit/64b4ef869c4a57409929467502afb8b59f750f0d

@brandjon I would like to add my voice to others reclaming an official upstream solution to handle extra dependencies handling taken from the wheel metadata.
