### ISSUE TITLE
Bazel coverage executes the coverage_report_generator before all tests have finished executing

### ISSUE THREAD

**Issue by d3vnu1l** [bazelbuild/bazel#11059]
### Description of the problem / feature request:

The executable pointed to by `--coverage_report_generator` is executed before all tests have completed running. This makes it impossible to consistently use this hook to generate coverage reports as not all code coverage artifacts have been produced yet.

### Feature requests: what underlying problem are you trying to solve with this feature?

Generate C/C++ Coverage reports using my own `coverage_report_generator` binary.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
```
bazel coverage //... --combined_report=lcov --coverage_report_generator=<(some executable)> --experimental_generate_json_trace_profile --experimental_profile_cpu_usage --experimental_json_trace_compression
```
### What operating system are you running Bazel on?
`MACOS 10.15.4`
### What's the output of `bazel info release`?
`release 2.0.0`
###  Have you found anything relevant by searching the web?
No
### Any other information, logs, or outputs that you want to share?
Here is an action graph illustrating the problem. I have added a 5 second delay to my coverage report generator to make it more visible.
<img width="1087" alt="Screen Shot 2020-04-01 at 10 19 59 PM" src="https://user-images.githubusercontent.com/1504900/78278379-cffe8080-74ca-11ea-8d07-7ce0db1d6fa5.png">

**Comment by c-mita** [comment]
I'm unable to reproduce this problem; if this is still an issue, can you provide an example project with test cases where this occurs?
