### ISSUE TITLE
Improve maven_jar 404 error message

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1105]
See http://stackoverflow.com/questions/36245923/failed-to-fetch-maven-dependency-javadoc-with-bazel.

Right now, we're stringifying the error message provided by aether, which isn't a very good explanation (https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/repository/MavenJarFunction.java#L220-L221).

**Comment by katre** [comment]
Currently, the error message is the following:

ERROR: no such package '@jdoc//jar': Failed to fetch Maven dependency: Could not find artifact javadoc:javadoc:jar:1.3 in jdoc (https://repo1.maven.org/maven2/).

Looks like Maven updated the message for the ArtifactResolutionException. Given the formatting of Maven artifacts, I'm not sure we can actually improve on this much, so I'd like to close this.

**Comment by katre** [comment]
Closing following previous comment.
