### ISSUE TITLE
bazel-1.0.0 : Depends: python but it is not installable

### ISSUE THREAD

**Issue by silentsnooc** [bazelbuild/bazel#11065]
I am trying to install bazel following the instructions for the apt repository.

Running:

```
$ sudo apt install bazel-1.0.0
```

gives the following error:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 bazel-1.0.0 : Depends: python but it is not installable
E: Unable to correct problems, you have held broken packages.
```

However, I do have an alias `python -> /usr/bin/python3`

```
$ python
Python 3.8.2 (default, Mar 13 2020, 10:14:16) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

Any ideas?

**Comment by philwo** [comment]
I assume that this is fixed by now, otherwise please respond with information about your Linux system (which distro, which version, what have you tried to resolve this - if you can't install the "python" package on your system it sounds like something on that system is broken).

**Comment by pperiucr** [comment]
I am getting the same error. If this issue is fixed, appreciate an answer, Thank you.
