### ISSUE TITLE
_gen_installer: 'NoneType' value has no field or method 'short_path'

### ISSUE THREAD

**Issue by fangism** [bazelbuild/bazel#11069]
### Description of the problem / feature request:

```
$ bazel test -c opt --cxxopt='--std=c++11' ...
Starting local Bazel server and connecting to it...
ERROR: /tmp/verible_copybared/BUILD:15:1: in _gen_installer rule //:_install_gen: 
Traceback (most recent call last):
	File "/tmp/verible_copybared/BUILD", line 15
		_gen_installer(name = '_install_gen')
	File "/usr/local/google/home/fangism/.cache/bazel/_bazel_fangism/b057478e5059923c8cf2d338db1da6fa/external/com_github_google_rules_install/installer/def.bzl", line 33, in _gen_install_binary_impl
		sources.append(file.short_path)
	File "/usr/local/google/home/fangism/.cache/bazel/_bazel_fangism/b057478e5059923c8cf2d338db1da6fa/external/com_github_google_rules_install/installer/def.bzl", line 33, in sources.append
		file.short_path
'NoneType' value has no field or method 'short_path'
ERROR: Analysis of target '//:install' failed; build aborted: Analysis of target '//:_install_gen' failed; build aborted
INFO: Elapsed time: 10.209s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (72 packages loaded, 5124 targets configured)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```bash
git clone git@github.com:google/verible.git
cd verible
bazel build ...
```

### What operating system are you running Bazel on?

`Linux hostname.xyz.com 5.2.17-1rodete3-amd64 #1 SMP Debian 5.2.17-1rodete3 (2019-10-21 > 2018) x86_64 GNU/Linux`

### What's the output of `bazel info release`?

`release 2.2.0`

###  Have you found anything relevant by searching the web?

Maybe issue #8598 ?

### Any other information, logs, or outputs that you want to share?

See stacktrace in description.

CC: @hzeller

**Comment by fangism** [comment]
b/153238985

**Comment by hzeller** [comment]
This looks more like an issue in bazel_rules_install: https://github.com/google/bazel_rules_install/issues/24

**Comment by fangism** [comment]
Moved to: https://github.com/google/bazel_rules_install/issues/24
