### ISSUE TITLE
Type ctx has no function execute(list)

### ISSUE THREAD

**Issue by mqy** [bazelbuild/bazel#1107]
With 0.2.0 and 0.2.1-rc1, on both Darwin and Linux, the following .bzl fails with error "Type ctx has no function execute(list)". Anybody help?

_def _impl(ctx):
        result = ctx.execute(["/bin/echo", "something"])
        print(result.stdout)

exec = rule(
        implementation=_impl,
)

**Comment by damienmg** [comment]
execute is not a `ctx` function but a `repository_ctx` function. Also not present in 0.2.0.
