### ISSUE TITLE
cquery non-determinism on loading phase flag changes

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel#11078]
### Description of the problem / feature request:

`cquery` can produce non-deterministic output when toggling `--expand_test_suites`.

### Feature requests: what underlying problem are you trying to solve with this feature?

The same command line should always produce the same result.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```sh
$ cat test/BUILD
cc_library(
    name = "hello-greet",
    srcs = ["hello-greet.cc"],
    hdrs = ["hello-greet.h"],
)

cc_test(
    name = "hello-world",
    size = "small",
    srcs = ["hello-world.cc"],
    deps = [
        ":hello-greet",
    ],
)

test_suite(
    name = "hello-world-test-suite",
    tests = [":hello-world"],
)

# Correct output
$ bazel shutdown
$ bazel cquery //test:all
//test:hello-greet (12e23b9...)
//test:hello-world (12e23b9...)

# Correct output
$ bazel cquery //test:all --noexpand_test_suites
//test:hello-greet (12e23b9...)
//test:hello-world (12e23b9...)
//test:hello-world-test-suite (12e23b9...)

# Incorrect output
$ bazel cquery //test:all
//test:hello-greet (12e23b9...)
//test:hello-world (12e23b9...)
//test:hello-world-test-suite (12e23b9...)
```

### What operating system are you running Bazel on?
macOS

### What's the output of `bazel info release`?
release 3.0.0

###  Have you found anything relevant by searching the web?
Discovered from https://github.com/bazelbuild/bazel/issues/11042#issuecomment-608802458.

**Comment by gregestren** [comment]
Assigning to @juliexxia for triage.

**Comment by gregestren** [comment]
The flag is defined at https://github.com/bazelbuild/bazel/blob/1f684e1b87cd8881a0a4b33e86ba66743e32d674/src/main/java/com/google/devtools/build/lib/pkgcache/LoadingOptions.java#L155.

**Comment by juliexxia** [comment]
Note that greg's fix for https://github.com/bazelbuild/bazel/issues/11042#issuecomment-608802458 makes this specific repro obsolete since cquery always sets --noexpand_test_suite now.

**Comment by gregestren** [comment]
I think I kind of know what's going on.

Recall that flags in `LoadingOptions` affect how a target pattern (`//foo:all`) resolves into a set of specific targets (`[//foo:foo1, //foo:foo2]`).

In debugging https://github.com/bazelbuild/bazel/issues/11222:

```
$ bazel shutdown

# Correct:
$ bazel cquery 'deps(//package_a/...)' --noimplicit_deps --notool_deps
//package_a:package_a (c4d60f5dd32...)
//package_b:package_b (c4d60f5dd32...)

# Incorrect, should be empty because --build_tag_filters should filter all targets
# in //package_a out of the build:
$ bazel cquery 'deps(//package_a/...)' --noimplicit_deps --notool_deps \
    --build_tag_filters=-foo
//package_a:package_a (c4d60f5dd32...)
//package_b:package_b (c4d60f5dd32...)

# Correct:
$ bazel shutdown 
$ bazel cquery 'deps(//package_a/...)' --noimplicit_deps --notool_deps \
    --build_tag_filters=-foo
INFO: Found 0 targets...
```

This concerns how cquery is implemented.

First, a "real" build happens, through the analysis phase. This turns `//package_a/...` into a list of specific targets, then analyzes, then stores the configured targets in Skyframe's cache. *Then* cquery kicks in and evaluates its queries over the contents of the cache.

On the first cquery above, `--build_tag_filters` doesn't exclude anything, so target `//package_a:package_a` gets built. This has a `deps` on `//package_b`. When cquery kicks in, it looks at `deps(//package_a/...)`, somehow learns that `//package_a:package_a` is one of the targets, asks Skyframe for the configured target for `//package_a:package_a`, gets a result, and correctly reports its deps.

On the second cquery, when the "build" starts `--build_tag_filters=-foo` tells it not to build any rule with `tags = ["foo"]`. So `//package_a:package_a` gets excluded from the build command and nothing gets built. *However*, the Skyframe cache is still there, so the old entry for `//package_a:package_a` still exists. When cquery kicks in, it again asks Skyframe for `//package_a:package_a`, gets the same result, and returns the same result. This is incorrect. In other words, cquery itself isn't honoring the `--build_tag_filters` flag.

On the third cquery, Bazel starts up with an empty Skyframe cache, `--build_tag_filters=-foo` immediately kicks in, so `//package_a:package_` never gets built and never makes it into Skyframe. So when cquery kicks in and asks for that target, it gets no results. Specifically this happens here: 

https://github.com/bazelbuild/bazel/blob/41a3cb021e0c7e2058f5104cbd80ae8766790a2b/src/main/java/com/google/devtools/build/lib/query2/cquery/ConfiguredTargetQueryEnvironment.java#L300-L302

So cquery is evaluating over every match in the for loop, which in this case is empty. Perhaps it makes sense to explicitly say "no targets build" or some such thing. 

One possible answer is to integrate LoadingOptions into however cquery itself expands target patterns. So cquery never asks for `//package_a:package_a` in the first place.

**Comment by limdor** [comment]
@bazelbuild/triage please keep in case the issue it's still there. Having none deterministic behaviour is very bad for big projects.
If it is really solved it would be good to close it as fixed and not because of inactivity.
