### ISSUE TITLE
Documentation issue: External dependencies

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#11070]
Documentation URL: https://docs.bazel.build/versions/master/external.html

This seems to be the page that defines how to work with external repositories yet there is no documentation of the flag `--override_repository`. I knew that a flag with this behavior existed but ended up having to search through the entire flag reference to find its name since it wasn't documented here.

**Comment by jin** [comment]
Sorry for the trouble. See https://github.com/bazelbuild/bazel/pull/11087
