### ISSUE TITLE
Release 3.2 - May 2020

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#11077]
Cut date: 2020-05-04

**Comment by philwo** [comment]
The downstream pipeline of today's build was green. I'll have a look at the one that'll run tonight and will then cut 3.2rc1 with either today's or tomorrow's commit as the baseline.

**Comment by philwo** [comment]
Pushed 3.2.0rc1:

```sh
RELEASE_NUMBER=3.2.0
BASELINE_COMMIT=1d93d26d9900328dcba0026bf21cb45cc37a4596
git clone https://github.com/bazelbuild/bazel.git ~/bazel-release-$RELEASE_NUMBER
cd ~/bazel-release-$RELEASE_NUMBER
scripts/release/release.sh create $RELEASE_NUMBER $BASELINE_COMMIT
scripts/release/release.sh push
```

**Comment by ifoox** [comment]
Any updates?

**Comment by philwo** [comment]
I'm not aware of any release blockers or complaints. I think we can release it tomorrow. :)

**Comment by philwo** [comment]
Bazel 3.2.0 has been pushed! 🚀 

Pinging package maintainers @vbatts @petemounce @excitoon @chenrui333.

**Comment by chenrui333** [comment]
On my way of upgrading the formula.

**Comment by konste** [comment]
@philwo We were specifically waiting for 3.2.0 for the flag [--experimental_windows_watchfs](https://docs.bazel.build/versions/master/command-line-reference.html#flag--experimental_windows_watchfs) but when we try to use it we get "ERROR: Unrecognized option: --experimental_windows_watchfs". Is it possible that [11334](https://github.com/bazelbuild/bazel/pull/11334) somehow did not make it to 3.2.0?

**Comment by benjaminp** [comment]
3.2.0 was branched at the beginning of the month thus excluding 33106877277e6bfb3944b5b65b5d700fb781764e.

**Comment by konste** [comment]
@benjaminp Thank you for the explanation!

**Comment by philwo** [comment]
@konste Bazel 3.3.0rc1 should be cut beginning of next week, so you can test it using that version then :)

**Comment by vbatts** [comment]
late to the party, but fedora and centos are built https://copr.fedorainfracloud.org/coprs/vbatts/bazel/build/1424821/
Still epel-7-aarch64 failed, but all the rest succeeded.

**Comment by philwo** [comment]
Thank you @vbatts 😊 I'll have a look at the epel7-aarch64 failure. Bazel "should" work on that platform...

**Comment by philwo** [comment]
```
+ env ./compile.sh
Building Bazel from scratcherror: Bad exit status from /var/tmp/rpm-tmp.pj9GrC (%build)
    Bad exit status from /var/tmp/rpm-tmp.pj9GrC (%build)
RPM build errors:
Child return code was: 1
```

@vbatts It's strange that the `compile.sh` command doesn't print any error and just exits with code 1 after printing `Building Bazel from scratch`. I currently don't have a CentOS 7 machine on that platform available, but if I have some time, I'll try to find out what's failing there.

**Comment by jiridanek** [comment]
@philwo I've filled https://github.com/vbatts/copr-build-bazel/issues/14 for the epel-7-aarch64 build failure.

**Comment by vbatts** [comment]
I welcome any testing that folks offer here :-D

**Comment by limdor** [comment]
What is the status? Is there any reason why this issue is not closed? Just asking before starting the process to upgrade to 3.2.

**Comment by philwo** [comment]
@limdor No reason, I think we just forgot to close it. 😊
