### ISSUE TITLE
Release 3.1 - April 2020

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#11076]
# Status of Bazel 3.1

- Target baseline: 2020-04-07
- Expected release date: April 20-24
- [List of release blockers](https://github.com/bazelbuild/bazel/labels/Release%20blocker)

To report a release-blocking bug, please file a bug using the `Release blocker` label, and cc me.

Task list:

- [x] Update GitHub issues for incompatible changes
- [x] Pick release baseline: 17ebbf15bea3733c0c21e0376fb5906e391edb49
- [x] Create release candidate: https://releases.bazel.build/3.1.0/rc1/index.html
- [x] Check downstream projects: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1451
- [ ] [Create draft release announcement](https://docs.google.com/document/d/1wDvulLlj4NAlPZamdlEVFORks3YXJonCjyuQMUQEmB0/edit)
- [ ] Send for review the release announcement PR:
- [ ] Push the release, notify package maintainers:
- [ ] Update the documentation
- [ ] Push the blog post
- [ ] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by laurentlb** [comment]
Created the candidate with:
scripts/release/release.sh create 3.1.0 17ebbf15bea3733c0c21e0376fb5906e391edb49

You can download it from: https://releases.bazel.build/3.1.0/rc1/index.html

**Comment by laurentlb** [comment]
I'll cherrypick aeee3e08356f781616e68287ec7f35749e981ba6 to fix #10029.

**Comment by laurentlb** [comment]
I'll also cherrypick 2f14b57110cbbc210538ad6315486056cd493bee to fix #11040.

I'm now waiting for a resolution of #11114.

**Comment by laurentlb** [comment]
Cherrypicking 344d64f881e3ca20702d84b47ee609f7e87f325b to fix #11114

**Comment by laurentlb** [comment]
Created a new candidate using:
scripts/release/release.sh create --force_rc=2 3.1.0 17ebbf15bea3733c0c21e0376fb5906e391edb49 aeee3e0  2f14b57  344d64f

You can download it from:
 https://releases.bazel.build/3.1.0/rc2/index.html

Unless an issue is reported, I expect Bazel 3.1 to be released next Monday.

**Comment by werkt** [comment]
#11140 Fixes a regression (and adds testing) with orphaned action result output directories, introduced with #10029. This should be a release blocker.

**Comment by laurentlb** [comment]
New candidate created:
scripts/release/release.sh create --force_rc=4 3.1.0 17ebbf15bea3733c0c21e0376fb5906e391edb49 aeee3e0 2f14b57 344d64f d5084589f3a549e520ea5f37af29faafce3c5bcf 24f97e15bfd0e9d076d215c9cd42ffd101829e90

You can download it from https://releases.bazel.build/3.1.0/rc4/index.html

**Comment by laurentlb** [comment]
Bazel 3.1 has been released and is available here: https://github.com/bazelbuild/bazel/releases/tag/3.1.0

**Comment by laurentlb** [comment]
cc @petemounce  @excitoon @vbatts

**Comment by vbatts** [comment]
fedora/centos build kicked off: https://copr.fedorainfracloud.org/coprs/vbatts/bazel/build/1344869/

**Comment by vbatts** [comment]
again, all succeed except for epel-7-aarch64

**Comment by jin** [comment]
The bazelbuild homebrew tap is still on 3.0.0 https://github.com/bazelbuild/homebrew-tap/blob/master/Formula/bazel.rb

Also please see https://github.com/bazelbuild/bazel/issues/11243 -- there are two homebrew formulas, with the community maintained one at 3.1.0 already. Should we consider de-duplicating the formulas?
