### ISSUE TITLE
C++ shared libraries generated on OSX get file extension .so instead of .dylib

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#11082]
# Description of the problem / feature request:

`cc_library` rule with `name = 'foo` and `linkstatic=False` attribute generates a shared library. 
On Linux the library is named `libfoo.so` - correct.
On Windows the library is named `foo.dll` - correct.
On MacOS the library is named `libfoo.so` - incorrect! It should be `libfoo.dylib`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Here is the repo with the minimal example: https://github.com/konste/bazel_repro_shared_lib
Clone it and build it on Mac. You get libbase_shared.so in the output, instead of libbase_shared.dylib

### What operating system are you running Bazel on?

MacOS 10.16

### What's the output of `bazel info release`?

2.2.0

**Comment by dwtj** [comment]
I think that I also just ran into this bug with a `cc_binary` rule with `linkshared = True`.

I'm using

- macOS v11.0.1
- Bazel v3.7.0
- The latest `@rules_cc` commit, `b1c40e1`

**Comment by konste** [comment]
At some moment minor problems with the built-in rules like this one started to cause us so much pain that we reimplemented most cc rules in Starlark. For compilation we use [cc_common.compile](https://docs.bazel.build/versions/master/skylark/lib/cc_common.html#compile), but for linking we cannot use [cc_common.link](https://docs.bazel.build/versions/master/skylark/lib/cc_common.html#link) because it brings back all the same problems, so linking is re-implemented all the way down to [actions.run](https://docs.bazel.build/versions/master/skylark/lib/actions.html#run).

**Comment by fmeum** [comment]
This is still an issue with `4.0.0`.

**Comment by KinanBab** [comment]
I ran into this with bazel 4.0.0, using `cc_binary` and `linkshared = True`

However, one quick fix seems to be to provide the full file name (with extension) as the name of the rule. So instead of using `name = "mylib"` which ends up generating `libmylib.so`, I use `name = "libmylib.dylib"` and it generates `libmylib.dylib`!

For my purposes this seem to work fine (I am doing something with JNI so I need the native libraries to have a very specific name with .dylib so that the JVM can load them properly).

**Comment by brentleyjones** [comment]
This should be re-opened until https://github.com/bazelbuild/bazel/pull/14354 is merged.

**Comment by redsun82** [comment]
As far as I can tell this is still the case with the autoconfigured toolchain. Can this be reopened, and https://github.com/bazelbuild/bazel/pull/14354 be resurrected?

**Comment by fmeum** [comment]
@redsun82 Which version of Bazel are you on? This should be working with at least Bazel 6.0.0.

**Comment by redsun82** [comment]
Ah, I did not think about testing with a newer version, I'm still on 5.x. Thanks!
