### ISSUE TITLE
Not able to create UNIX domain socket in TEST_TMPDIR

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel#11089]
### Description of the problem / feature request:

[Bazel Test encyclopedia](https://docs.bazel.build/versions/master/test-encyclopedia.html#test-interaction-with-the-filesystem) recommends that:

> Tests should create files only within the directories specified by $TEST_TMPDIR and $TEST_UNDECLARED_OUTPUTS_DIR (if set).

However, the paths to `$TEST_TMPDIR` and `$TEST_UNDECLARED_OUTPUTS_DIR` are too long in most macOS and Linux systems to write UNIX domain socket, which is limited to 108 bytes on Linux and 104 bytes on macOS: https://serverfault.com/questions/641347/check-if-a-path-exceeds-maximum-for-unix-domain-socket.

Where should tests write those socket files to?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```bash
$ git clone git@github.com:linzhp/bazel_examples.git
$ cd bazel_examples
$ bazel test //socket:go_default_test
```

### What operating system are you running Bazel on?

macOS and Linux

### What's the output of `bazel info release`?

release 2.2.0

**Comment by aiuto** [comment]
I'm not sure if this is local, remote all all execution, thus the dual teams.

**Comment by benjaminp** [comment]
The [test execution environment is required to have a `/tmp`](https://docs.bazel.build/versions/master/test-encyclopedia.html#filesystem), so typically you can simply stick unix sockets there.

**Comment by jmmv** [comment]
I don't think we can do much more here than documenting this as an issue and telling users to rely on `/tmp` directly...

**Comment by linzhp** [comment]
Given this issue, is it a good practice for a test rule to set `TMPDIR` to `TEST_TMPDIR`? Is it intentional for Bazel to keep them separate?

**Comment by aiuto** [comment]
I don't know the history, but it seems logical to distinguish them.
TMPDIR is a Unix/Posix standard. Even non-test programs expect that it to be set. Note that it is not necessarily a default on other OSes.
TEST_TMPDIR is a introduced by Bazel as something guaranteed to be set while executing in the test environment we have set up. 
I could imaging a very portable binary would use $TEST_TMPDIR as a temp work area. A *ix specific tool could use $TMPDIR and be compliant. If your binary is only intended for a specific OS, you make want to use other mechanisms.
