### ISSUE TITLE
New releases of Bazel should be usable using an Remote Build Environment

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#11099]
### Description of the problem / feature request:

When a new release of Bazel ships, there is a lag before a new version of https://github.com/bazelbuild/bazel-toolchains ships too. This slows adoption of new versions of bazel, especially for sophisticated users

### Feature requests: what underlying problem are you trying to solve with this feature?

Presumably there is a magic "release Bazel" button somewhere within Google. When a release of the main project is done, a simultaneous release of `bazel-toolchains` should also happen automatically.

### What's the output of `bazel info release`?

3.0.0

###  Have you found anything relevant by searching the web?

Discussion on the bazel Slack suggests that this is the right place to file this issue.

**Comment by aiuto** [comment]
We probably want to keep them independent, but your point is well taken. 
Since the toolchains should be compatible with the current and next version of Bazel, perhaps one of the "Release Bazel" checklist items should be to release bazel-toolchains first.

**Comment by shs96c** [comment]
That might be even better, since it would make it easier to beta test the forthcoming bazel release with their remote build environments.

**Comment by meisterT** [comment]
Side note, the magic release button is documented here: https://github.com/bazelbuild/continuous-integration/blob/master/docs/release-playbook.md

and the code for the script lives here:
https://github.com/bazelbuild/bazel/blob/master/scripts/release/release.sh

**Comment by meisterT** [comment]
@meteorcloudy

**Comment by philwo** [comment]
As the bazel-toolchains repository is going to be deprecated and the auto-released configs will be replaced by a CLI tool that can generate them on-demand, I'm closing this issue.

You can see https://github.com/bazelbuild/bazel-toolchains/releases/tag/v5.0.0 for some initial details, I think more docs will follow in the bazel-toolchains repository shortly.
