### ISSUE TITLE
bazel version showing unknown

### ISSUE THREAD

**Issue by npandey2385** [bazelbuild/bazel#11091]
Hi,

I compiled bazel 0.27.1 on RHEL6 using Gcc 6.3.0. But when I tried to check the version it showing unknown.

bash compile.sh                              
🍃  Building Bazel from scratch..find: `src/tools/xcode-common/java/com/google/devtools/build/xcode/common': No such file or directory                                                                                                                      
find: `src/tools/xcode-common/java/com/google/devtools/build/xcode/util': No such file or directory                           
....sed: invalid option -- 'E'                                                                                                
Usage: sed [OPTION]... {script-only-if-no-other-script} [input-file]...                                                       

  -n, --quiet, --silent
                 suppress automatic printing of pattern space
  -e script, --expression=script                             
                 add the script to the commands to be executed
  -f script-file, --file=script-file                          
                 add the contents of script-file to the commands to be executed
  -i[SUFFIX], --in-place[=SUFFIX]                                              
                 edit files in place (makes backup if extension supplied)      
  -l N, --line-length=N                                                        
                 specify the desired line-wrap length for the `l' command      
  --posix                                                                      
                 disable all GNU extensions.                                   
  -r, --regexp-extended                                                        
                 use extended regular expressions in the script.               
  -s, --separate                                                               
                 consider files as separate rather than as a single continuous 
                 long stream.                                                  
  -u, --unbuffered                                                             
                 load minimal amounts of data from the input files and flush   
                 the output buffers more often                                 
      --help     display this help and exit                                    
      --version  output version information and exit                           

If no -e, --expression, -f, or --file option is given, then the first
non-option argument is taken as the sed script to interpret.  All    
remaining arguments are names of input files; if no input files are  
specified, then the standard input is read.                          

E-mail bug reports to: bonzini@gnu.org .
Be sure to include the word ``sed'' somewhere in the ``Subject:'' field.
fgrep: write error: Broken pipe                                         

🍃  Building Bazel with Bazel.
.WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".                                                                                                                             
DEBUG: /tmp/bazel_rWj6vKcg/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:49:5:                
Current Bazel is not a release version, cannot check for compatibility.                                                       
DEBUG: /tmp/bazel_rWj6vKcg/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:51:5: Make sure that you are running at least Bazel 0.17.1.                                                                                        
INFO: Analyzed target //src:bazel_nojdk (215 packages loaded, 10668 targets configured).                                      
INFO: Found 1 target...                                                                                                       
INFO: From Compiling src/main/cpp/blaze_util_posix.cc:                                                                        
src/main/cpp/blaze_util_posix.cc: In function 'uint64_t blaze::AcquireLock(const string&, bool, bool, blaze::BlazeLock*)':    
src/main/cpp/blaze_util_posix.cc:650:30: warning: ignoring return value of 'int ftruncate(int, __off_t)', declared with attribute warn_unused_result [-Wunused-result]                                                                                      
   (void) ftruncate(lockfd, 0);                                                                                               
                              ^                                                                                               
INFO: From Compiling src/main/cpp/blaze.cc:                                                                                   
src/main/cpp/blaze.cc: In function 'void blaze::WriteFileToStderrOrDie(const char*)':                                         
src/main/cpp/blaze.cc:643:40: warning: ignoring return value of 'size_t fwrite(const void*, size_t, size_t, FILE*)', declared with attribute warn_unused_result [-Wunused-result]                                                                           
     fwrite(buffer, 1, num_read, stderr);                                                                                     
                                        ^                                                                                     
INFO: From Generating Java (Immutable) proto_library //src/main/protobuf:execution_statistics_proto:                          
[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/compiler/java/java_file.cc:228] The optimize_for = LITE_RUNTIME option is no longer supported by protobuf Java code generator and may generate broken code. It will be ignored by protoc in the future and protoc will always generate full runtime code for Java. To use Java Lite runtime, users should use the Java Lite plugin instead. See:                                                                                                  
  https://github.com/google/protobuf/blob/master/java/lite.md                                                                 
INFO: From JavacBootstrap src/main/java/com/google/devtools/build/lib/shell/libshell-skylark.jar [for host]:                  
warning: Implicitly compiled files were not subject to annotation processing.                                                 
  Use -proc:none to disable annotation processing or -implicit to specify a policy for implicit compilation.                  
1 warning                                                                                                                     
INFO: From JavacBootstrap src/java_tools/singlejar/java/com/google/devtools/build/singlejar/libbootstrap.jar [for host]:      
warning: Implicitly compiled files were not subject to annotation processing.                                                 
  Use -proc:none to disable annotation processing or -implicit to specify a policy for implicit compilation.                  
1 warning                                                                                                                     
INFO: From JavacBootstrap src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar [for host]:     
warning: Implicitly compiled files were not subject to annotation processing.                                                 
  Use -proc:none to disable annotation processing or -implicit to specify a policy for implicit compilation.                  
Note: Some input files use or override a deprecated API.                                                                      
Note: Recompile with -Xlint:deprecation for details.                                                                          
1 warning                                                                                                                     
INFO: From JavacBootstrap src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libbootstrap_VanillaJavaBuilder.jar [for host]:                                                                                                                   
warning: Implicitly compiled files were not subject to annotation processing.                                                 
  Use -proc:none to disable annotation processing or -implicit to specify a policy for implicit compilation.                  
Note: src/java_tools/buildjar/java/com/google/devtools/build/buildjar/VanillaJavaBuilder.java uses or overrides a deprecated API.                                                                                                                           
Note: Recompile with -Xlint:deprecation for details.                                                                          
1 warning                                                                                                                     
INFO: From Compiling src/main/tools/daemonize.c:                                                                              
src/main/tools/daemonize.c: In function 'WritePidFile':                                                                       
src/main/tools/daemonize.c:95:3: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]                                                                                                                    
   write(pid_done_fd, &dummy, sizeof(dummy));                                                                                 
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                  
Target //src:bazel_nojdk up-to-date:                                                                                          
  bazel-bin/src/bazel_nojdk                                                                                                   
INFO: Elapsed time: 3692.397s, Critical Path: 213.68s                                                                         
INFO: 1747 processes: 1511 local, 236 worker.                                                                                 
INFO: Build completed successfully, 1791 total actions                                                                        
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
DEBUG: /tmp/bazel_rWj6vKcg/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:49:5:                
Current Bazel is not a release version, cannot check for compatibility.                                                       
DEBUG: /tmp/bazel_rWj6vKcg/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:51:5: Make sure that you are running at least Bazel 0.17.1.                                                                                        

Build successful! Binary is here: bazel-v0.27.1/Linux/RHEL6.0-2013-x86_64/output/bazel
**bazel-v0.27.1/Linux/RHEL6.0-2013-x86_64/output/bazel version
WARNING: Output base '/.cache/bazel/_bazel_matrix/b8d184bb3eb098280ca163a529a5e5f4' is on NFS. This may lead to surprising failures and undetermined behavior.                                                                                  
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Build label: unknown- (@non-git)**
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Apr 7 16:06:28 2020 (1586275588)
Build timestamp: 1586275588
Build timestamp as int: 1586275588

**Comment by aiuto** [comment]
There are a bunch of errors (like the sed -E) there so I suspect it didn't build correctly.
You might try pinpointing what happens in scripts/bootstrap/buildenv.sh  get_last_version
to see if you are picking it up there.

**Comment by meisterT** [comment]
See the reply on bazel-discuss: https://groups.google.com/forum/#!topic/bazel-discuss/pxQnBXJhnFw

Feel free to reopen if that doesn't help you.
