### ISSUE TITLE
singlejar_cc_bin fails with segmentation fault on s390x

### ISSUE THREAD

**Issue by gerhard-pretorius** [bazelbuild/bazel#11098]
### Description of the problem / feature request:

singlejar_cc_bin fails with segmentation fault on s390x.

This occurs when using bazel to build a project that uses singlejar_cc_bin, for
example in tensorflow: `bazel test //tensorflow/java/...`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
cd ~/src
curl -sSLO https://github.com/bazelbuild/bazel/releases/download/0.26.1/bazel-0.26.1-dist.zip
mkdir bazel && cd bazel
unzip ../bazel-0.26.1-dist.zip

export BAZEL_JAVAC_OPTS="-J-Xms1g -J-Xmx1g"
env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh

PATH=~/src/bazel/output:$PATH

bazel --host_jvm_args="-Xms1024m" --host_jvm_args="-Xmx2048m" build \
--host_javabase="@local_jdk//:jdk" --verbose_failures --verbose_explanations \
//src:java_tools_java10.zip
```

### What operating system are you running Bazel on?

Linux (Ubuntu 18.04) on s390x.

### What's the output of `bazel info release`?

```
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
release 0.26.1- (@non-git)
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

```
cd ~/src
curl -sSLO https://github.com/bazelbuild/bazel/releases/download/0.26.1/bazel-0.26.1-dist.zip
mkdir bazel && cd bazel
unzip ../bazel-0.26.1-dist.zip

export BAZEL_JAVAC_OPTS="-J-Xms1g -J-Xmx1g"
env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh
```

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

A snippet of the resulting output:

```
ERROR: ~/src/bazel/src/java_tools/buildjar/BUILD:34:1: Building deploy jar src/java_tools/buildjar/VanillaJavaBuilder_deploy.jar failed (Segmentation fault): singlejar_cc_bin failed: error executing command
  (cd ~/.cache/bazel/_bazel_xxxx/1704e2cdcf4d37530827c5fbcd96c705/sandbox/linux-sandbox/367/execroot/io_bazel && \
  exec env - \
  bazel-out/host/bin/external/remote_java_tools_linux/singlejar_cc_bin @bazel-out/s390x-fastbuild/bin/src/java_tools/buildjar/VanillaJavaBuilder_deploy.jar-0.params)
Execution platform: //:default_host_platform
```

The following patch fixes the problem:

```
diff -Naur old/src/tools/singlejar/zip_headers.h new/src/tools/singlejar/zip_headers.h
--- old/src/tools/singlejar/zip_headers.h       2020-04-06 07:24:24.116584748 -0700
+++ new/src/tools/singlejar/zip_headers.h       2020-04-06 07:26:21.456564738 -0700
@@ -265,7 +265,7 @@
   void file_name(const char *filename, uint16_t len) {
     file_name_length_ = htole16(len);
     if (len) {
-      memcpy(file_name_, filename, file_name_length_);
+      memcpy(file_name_, filename, len);
     }
   }
   bool file_name_is(const char *name) const {
```

The problem is caused by using the little endian encoded value rather than the
host order. Using the local variable `len` (or the accessor `file_name_length()`)
instead will return the file name length in host order.

**Comment by aiuto** [comment]
Sending this to EngProd for lack of a more precise team.
Gerhard: Would you be willing to send a PR?  The snippet you sent looks correct. 
After pondering a bit, I believe the method works like this.

void file_name(const char *filename, uint16_t len)  // is a setter for the filename
 file_name_length_ = htole16(len);  // correctly set the header field to little endian
     if (len) {
-      memcpy(file_name_, filename, file_name_length_);
+      memcpy(file_name_, filename, len);   // copy the user specified number of bytes in
     }
   }

I think using len here is more appropriate than calling the accessor, because the
accessor only works after the side effect of setting file_name_length_

**Comment by gerhard-pretorius** [comment]
Sure, np.
