### ISSUE TITLE
Windows: bazel build @local_config_cc//... fails with missing file (link_dynamic_library.sh)

### ISSUE THREAD

**Issue by sunjayBhatia** [bazelbuild/bazel#11101]
### Description of the problem / feature request:

Running `bazel build @local_config_cc//...` on Windows fails with the following:

```
ERROR: missing input file 'external/local_config_cc/link_dynamic_library.sh', owner: '@local_config_cc//:link_dynamic_library.sh'
ERROR: C:/tools/msys64/_bazel_containeradministrator/dyuozru3/external/local_config_cc/BUILD:340:1: @local_config_cc//:link_dynamic_library: missing input file 'LabelCause{label=@local_config_cc//:link_dynamic_library.sh, msg=missing input file 'external/local_config_cc/link_dynamic_library.sh', owner: '@local_config_cc//:link_dynamic_library.sh'}'
ERROR: C:/tools/msys64/_bazel_containeradministrator/dyuozru3/external/local_config_cc/BUILD:340:1 1 input file(s) do not exist
```

### Feature requests: what underlying problem are you trying to solve with this feature?

We are trying to generate toolchains for msvc-cl to run with RBE on Windows for the Envoy project.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

On a Windows host, run `bazel build @local_config_cc//...`

### What operating system are you running Bazel on?

Windows 2019/Windows 2019 LTS container image

### What's the output of `bazel info release`?

`release 3.0.0`

### Any other information, logs, or outputs that you want to share?

- The missing file is included in the Windows BUILD file here: https://github.com/bazelbuild/bazel/blob/60c55f57701cfb4b7d4e67c3af8cc36e174b08c5/tools/cpp/BUILD.windows.tpl#L313
- It seems like simply adding the relevant file to be copied into the correct location here would solve the issue: https://github.com/bazelbuild/bazel/blob/60c55f57701cfb4b7d4e67c3af8cc36e174b08c5/tools/cpp/windows_cc_configure.bzl#L696
- the command succeeds after manually copying the missing file into the bazel build tree

**Comment by aiuto** [comment]
Not sure if this is C++ team or Configurability (because toolchains).  But @meteorcloudy touched the code last so  they may know best.

**Comment by meteorcloudy** [comment]
Thanks for reporting this issue. 
https://github.com/bazelbuild/bazel/blob/60c55f57701cfb4b7d4e67c3af8cc36e174b08c5/tools/cpp/BUILD.windows.tpl#L313-L316
This target is simply not needed on Windows, I'll send a change to delete it.

In the meantime, can you build the specific target you want to avoid this error?

**Comment by sunjayBhatia** [comment]
We can try to work around it for now until the change makes it way to a bazel release, but that `bazel build @local_config_cc//...` invocation comes from here: https://github.com/bazelbuild/bazel-toolchains/blob/d1a1da96c26dde3cc018190487cf4bc82583d4f6/rules/rbe_repo/container.bzl#L79-L81 which may not be ultimately possible to change too much

**Comment by meteorcloudy** [comment]
I see, the fix will be included in the next release.

**Comment by sunjayBhatia** [comment]
Related: https://github.com/bazelbuild/bazel-toolchains/issues/855
