### ISSUE TITLE
Add description parameter for cc rules

### ISSUE THREAD

**Issue by lisaonduty** [bazelbuild/bazel#11106]
### Description of the feature request:

We wish to automatically generate interface information.
By using Bazel query we can filter out the targets that are public.
Then we would also like to be able to get a description of the target.
So the best solution, as far as we can see, would be to also have a description parameter in the c/cc rules.
We use the `tags` parameter for several other reasons and it would be quite messy to also add descriptions in this parameter. We also think that this is something that more Bazel users than us would have use of and therfore we thought that it could be a good feature to add in the existing rules. 

### Feature requests: what underlying problem are you trying to solve with this feature?

In a fast and correct way get documentation of our interfaces, please see above.

### What operating system are you running Bazel on?

Linux 

### What's the output of `bazel info release`?

2.2.0

###  Have you found anything relevant by searching the web?

Wrote an bazel-discuss on this last year.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bazel-discuss/K33wgWm3PkE/sfe3TWUTAwAJ

**Comment by aiuto** [comment]
This seems like a feature for StarDoc rather than Bazel. Do you mind if I move it to that repo?

**Comment by lisaonduty** [comment]
Thanks for commenting. 
Please explain more how this can be solved in Stardoc.
I thought that it needed to be added a new parameter in the rules so therfore I see this as an Bazel feature. Then Stardoc can be used when generating documents but then the parameter must exist.

**Comment by jin** [comment]
Can you elaborate more on how using `tags` for this is messy?

```
rule(
    name = "special_target",
    # ...
    tags = [
        "description=Some description string to describe why this target is special",
        "other-tags",
    ],
)
```

versus

```
rule(
    name = "special_target",
    # ...
    description = "Some description string to describe why this target is special",
    tags = [
        "other-tags",
    ],
)
```

The former doesn't seem that messy.

If anything, this would be a generic attribute across *all* rules instead of just for `cc_*` ones. The ROI from this seems too little from the overhead of maintaining yet another attribute.

Tagging this over to Starlark/FrontEnd (cc @laurentlb)

**Comment by aiuto** [comment]
How about you experiment with it to show the use cases and value. Then put the code up on github somewhere and solicit community feedback. It is always easier for people to see if they like an idea once they see the value they get from it. It also allows easier and quicker iteration towards a good design before adding a cross-cutting feature to Bazel.

One idea:

- create your own cc_binary, cc_library wrapper macros
- it adds a description attribute
- it creates the native rule and a side-effect `target_description` rule

`target_description` is a rule with 3 attributes
- target_name
- tags
- description

It emits a provider which basically forwards that info, but does no actions.

Now you could find all the target_description rules with a query, you might be able to build an index of what packages are in a target by running an aspect down the provider.
Maybe you just build a master index by scanning and parsing BUILD files.

OTOH, if you are scanning BUILD files yourself, perhaps a structured comment tool would be simpler, and could apply to any rule/macro.  Something like

```
# libfoo provides ...  and the rest of your normal comments here
# @description(This is the public API to the foo library)
# @some_other_extractable_description_keyword(more text...)
cc_library(name='foo', ...)
```

**Comment by c-parsons** [comment]
Hi,
Author of Stardoc here. I have some clarifying questions and some comments.

> Then we would also like to be able to get a description of the target.

Can you elaborate on what you will be using this description for? Is this for documentation rendering, for example? (If so, what form does your documentation have?)

> We use the `tags` parameter for several other reasons and it would be quite messy to also add descriptions in this parameter

Can you elaborate on what particularly makes this messy? Particularly, is it the definition? Is is that the tags list becomes too long when visually inspecting it in a query?

As Jin has alluded to, an option for this would be to wrap your "public" cc_ rules in a macro, and call that. For example:

```
# public_cc_library.bzl
def public_cc_library(description = "", tags = [], **kwargs):
    new_tags = tags + ["public"]
    if description:
        new_tags.append("description=" + description)
    native.cc_library(tags = new_tags, **kwargs)

# BUILD
load(":public_cc_library.bzl", "public_cc_library")
public_cc_library(
    name = "foo",
    srcs = [...],
    description = "foo rule description",
    tags = ["manual"],
    ...
)
```

This way, you leverage the "tags" attribute but specify the additional details in alternative ways.


> This seems like a feature for StarDoc rather than Bazel. Do you mind if I move it to that repo?

Stardoc is a utility for documenting rules and macros, not targets. Thus, without a major overhaul of Stardoc, there is not much it can help with here.

**Comment by lisaonduty** [comment]
Hi,

Thanks for all comments!
I will try to explain what we want to do.

Our product can be considered as a platform, a simplified view is that we provide our own operative system and other functions that makes it possible to run applications on our own in-house hardware. We also provide the build system which now is based on Bazel. In other organizations in the company the platform applications are developed and those developers are considered our users (internal customers). We need to provide tables with description of our interfaces to our users so that they know what targets to add in their BUILD files. The tables have 3 columns: Bazel targets, Description, Header files. The Bazel targets are the public targets that we provide to our users/customers, the description is a description of the specific target and Header files are list of the public header files that the target contain.

It's really nice that we now by using different Bazel queries can generate these interface documents.

We who works with the build system has made several macros upon cc_library and cc_binary rules. They are just a help for both our platform developers and the application developers. In these macros we use the tags field for different purposes (for example to tag the test targets, to be able to query for all targets that belongs to a specific group e.g. all "threads"). The users of the macros can of course add their own tags. We strive for using Bazel without any changes so all parameters has the same names as in the Bazel documentation. We also refer to the Bazel documentation as much as possible.
When saying messy we thought that it would be more user friendly for our macro users if we kept that tags field separate from the target description. We have thousands application developers and must think of being user friendly. It's understandable to use the tags field for short simple tags like "thread_tag" and it would not be that intuitive to add a quite long description in this field. These tags are also parsed at different places, without any knowledge of the query implementation I assume that it's solved with parsing there as well. Bazel query is a good feature but it's not a fast feature. I haven't tested if the query performance is impacted by having a lots of long tags but it is likely that it will. 

The reason why I submitted this request is because we thought that other Bazel users might have the same need as we have so we thought that it could be good to have that attribute in the rules.
We can of course use the tags field and we can also implement work arounds as the one Jin has suggested. 

As I said above it's really nice that we now can generate the documentation from the code. Not just that it's a fast way to document we also know that it's correct. We can also reveal if we get targets in our tables that shall be internal but wrongly has been configured as public.

**Comment by c-parsons** [comment]
Thanks for the detail! Some followups:

> We who works with the build system has made several macros upon cc_library and cc_binary rules.

So you can hopefully implement this workaround in the existing macros, no? :) Hopefully shouldn't be any harder for your users than if "description" was a builtin attribute?

> We need to provide tables with description of our interfaces to our users so that they know what targets to add in their BUILD files

What's your current solution to this? do you have a custom documentation-building binary?

> We strive for using Bazel without any changes so all parameters has the same names as in the Bazel documentation.

Does this mean you are avoiding adding any extra attributes to your macros? 
If the motivation here is a documentation issue, I *would* suggest you take a look at Stardoc. It's fairly common (and best practice!) for rule/macro authors to produce their documentation using Stardoc.

> When saying messy we thought that it would be more user friendly for our macro users if we kept that tags field separate from the target description

The nice thing about the proposed approach is that users should have no idea that what they are adding via `description` attribute is being added to `tags` behind the scenes

> Bazel query is a good feature but it's not a fast feature. I haven't tested if the query performance is impacted by having a lots of long tags but it is likely that it will.

I don't anticipate this would greatly impact query performance, but I'm not 100% sure. Are you using `query` in performance-critical workflows? (I would not expect documentation generation to be performance critical, unless I'm misunderstanding)


In general, if there is a good-enough solution that may be implemented via Starlark macros (as opposed to requiring native Bazel changes), we strive to investigate the Starlark solution first. Major new Bazel features are approached with much more scrutiny, as:

- We need to wait for the next Bazel release for the solution to be available.
- We have to be wary of performance implications for all users (as opposed to the subset of users using the new feature)
-  We sign ourselves up for an API to be around for a long time; turning down or changing sparsely-used features is a long multi-release process

How does trying the Starlark workaround sound for now, and if this causes pain for you or your users, we can reassess?

**Comment by lisaonduty** [comment]
Hi,

The solution for documenting today is to have a script with Bazel queries. 
The script will use the function visible() in the bazel
query language. 
When all public targets are found the script will
search for the target's public header files (listed in
'hdrs' parameter). But at the moment we have no description column for the targets.
So in this solution an attribute in the macro makes no differences since the macro doesn't exist when the queries are executed. 
And no we don't use query for anything time critical it's just that when running our script its easy to think that it is hanging since it takes so long time. It's not anything that harm more than that it's something that is very obvious. I also quite soon after starting to use query found several faults in query and c-query features (and reported them) so it seems like an area that isn't as stable as the rest of the Bazel implementation. It's a really nice feature but the impression it gives is that it could be faster and more stable.

When I say that we strive for changing as little as possible it means that we do not want to write own cc-rules, we want to use the native ones. We do have additional attributes in our macros but they will be converted to other information in the macro implementation e.g. linker flags so it's still fully possible to use the native rules.
We also want to minimize the number of own attributes in the macro so that our user recognize the similarity between the macro and the native cc_ rule. So that the Bazel official documentation will be easier to follow.
We do have quite extensive documentation of our own macros, they are generated by a script. We have tried twice to use Stardoc but it has failed due to error (https://github.com/bazelbuild/stardoc/issues/40). I haven't tried since we lifted our Bazel version.

Anyhow we can implement a solution to solve this target description (there are several ways) we just thought that a description field in the native cc rules would be beneficial for many users not just us. That was the reason for submitting a feature request. But if that is not the case and/or if that gives too many drawbacks then just ignore this and close the case.

Thanks for paying attention to this case, I'm grateful for that!

Best Regards
Lisa

**Comment by c-parsons** [comment]
Okay! For now I think we would like to see this resolved using the above suggestions, and not provide a native solution. Please feel free to reach out if you have any other specific issues or the proposed solution becomes too much of a burden. Thanks for the feedback!
