### ISSUE TITLE
Documentation issue: Concepts and terminology

### ISSUE THREAD

**Issue by durian888** [bazelbuild/bazel#11109]
Documentation URL: https://docs.bazel.build/versions/master/build-ref.html
I'm following the Building a C++ Project directions and believe that I have done as instructed 
yet the suggested call 
bazel query --notool_deps --noimplicit_deps 'deps(//main:hello-world)'   --output graph

Throws an error
ERROR: invalid target format 'deps(//main:hello-world)': invalid package name 'deps(//main': package names may not contain '//' path separators
Loading: 0 packages loaded

According to the instructions the call should be made at project root - which is the case

C:\Users\dom\work\bazel_exps\examples\cpp-tutorial\stage1>dir
 Volume in drive C is Windows
 Volume Serial Number is BAD6-2D99

 Directory of C:\Users\dom\work\bazel_exps\examples\cpp-tutorial\stage1

04/09/2020  04:27 PM    <DIR>          .
04/09/2020  04:27 PM    <DIR>          ..
04/09/2020  04:27 PM    <JUNCTION>     bazel-bin [C:\users\dom\_bazel_dom\4325adtk\execroot\__main__\bazel-out\x64_windows-fastbuild\bin]
04/09/2020  04:27 PM    <JUNCTION>     bazel-out [C:\users\dom\_bazel_dom\4325adtk\execroot\__main__\bazel-out]
04/09/2020  04:27 PM    <JUNCTION>     bazel-stage1 [C:\users\dom\_bazel_dom\4325adtk\execroot\__main__]
04/09/2020  04:27 PM    <JUNCTION>     bazel-testlogs [C:\users\dom\_bazel_dom\4325adtk\execroot\__main__\bazel-out\x64_windows-fastbuild\testlogs]
04/09/2020  04:25 PM    <DIR>          main
04/09/2020  04:25 PM             1,142 README.md
04/09/2020  04:25 PM                 0 WORKSPACE
               2 File(s)          1,142 bytes
               7 Dir(s)  370,052,186,112 bytes free

**Comment by jin** [comment]
If you're on Windows, I think you have to use three slashes for workspace root, instead of two: `deps(///main:hello-world)`

@meteorcloudy

**Comment by durian888** [comment]
Hi  Meteorcloudy

Thank you for the response.  Sadly with three slashes I'm still getting an error.

C:\Users\dom\work\bazel_exps\examples\cpp-tutorial\stage1>bazel query --notool_deps --noimplicit_deps 'deps(///main:hello-world)'  --output graph
ERROR: invalid target format 'deps(///main:hello-world)': invalid package name 'deps(///main': package names may not contain '//' path separators
Loading: 0 packages loaded


Dominic


________________________________

**Comment by meteorcloudy** [comment]
Hi @durian888 ,

The reason is `cmd.exe` interprets single quote `'` differently than `bash`.

`bazel query --notool_deps --noimplicit_deps "deps(//examples/cpp:hello-world)"  --output graph` should work on both Linux and Windows.

I'll send a update to fix the document, thanks for reporting this!

**Comment by durian888** [comment]
Hi Yun

Thank you for the report and the fix!

Dominic
________________________________
