### ISSUE TITLE
Latest Bazel release (3.0.0) is not tagged with its version in GCR, only `latest`

### ISSUE THREAD

**Issue by booninite** [bazelbuild/bazel#11108]
### Description of the problem / feature request:

I am `container_pull`'ing the public Bazel image provided at l.gcr.io/google/bazel based on my current version of Bazel (using bazelbuild/skylib).  That won't currently work because the 3.0.0 image is only published as `latest`, and not `3.0.0`.  Tags for `2.x` version of Bazel exist: 

https://console.cloud.google.com/gcr/images/cloud-marketplace-containers/GLOBAL/google/bazel?gcrImageListsize=30

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```python
load("@bazel_skylib//lib:versions.bzl", "versions")
// buncha stuff importing rules_docker
container_pull(
    name = "bazel",
    tag = versions.get(),
    registry = "l.gcr.io",
    repository = "google/bazel",
)
```

### What operating system are you running Bazel on?

OSX

### What's the output of `bazel info release`?

release 3.0.0

###  Have you found anything relevant by searching the web?

https://console.cloud.google.com/gcr/images/cloud-marketplace-containers/GLOBAL/google/bazel?gcrImageListsize=30

**Comment by meisterT** [comment]
cc @meteorcloudy @katre

**Comment by katre** [comment]
I didn't even know we produced these images. Invetsigating.

**Comment by katre** [comment]
We don't create these, but I've found the team who is, so I'm going to pass this along.

**Comment by katre** [comment]
The team responsible added the tag.
