### ISSUE TITLE
Please digitally sign zip and tar.gz source code releases

### ISSUE THREAD

**Issue by olekw** [bazelbuild/bazel#11111]
### Description of the problem / feature request:

Please digitally sign zip and tar.gz source code releases at https://github.com/bazelbuild/bazel/releases. The binary releases there are currently digitally signed and it appears that source releases were previously signed at, for example, https://releases.bazel.build/0.5.4/release.

### Feature requests: what underlying problem are you trying to solve with this feature?

Since many developers compile from source code, it is important to know that the source code is authentic and has not been tampered with, especially if downloading from a mirror or shared team repository.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Look at https://github.com/bazelbuild/bazel/releases and observe that there are no digital signatures for the source code packages.

### What operating system are you running Bazel on?

Debian 10

### What's the output of `bazel info release`?

N/A

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

No, this is a repository issue, not a technical issue.

### Any other information, logs, or outputs that you want to share?

No. This is hopefully a very simple fix since signatures are already provided for the binary packages. Thanks in advance for your consideration!

**Comment by aiuto** [comment]
The source distribution packages do have signatures. 
- bazel-3.0.0-dist.zip
- bazel-3.0.0-dist.zip.sha256
- bazel-3.0.0-dist.zip.sig

Thus, I have to assume you are asking specifically about the last two asset links
- source code (zip)   https://github.com/bazelbuild/bazel/archive/3.0.0.zip
- source code (tar.gz) https://github.com/bazelbuild/bazel/archive/3.0.0.tar.gz

We can eventually make that happen, but it may take some time, as we would have to establish a new (and reviewed) secure workflow to sign those github generated artifacts. 

Timing aside, we recommend that people who want to build Bazel from source use the source distribution zip, as that has all of the needed dependencies included.  That is essentially what we use to create the signed binaries.

There are two workarounds for now:
- git clone the repo over ssh and check out the 3.0.0 tag.
- download both, diff the source trees and verify that the distribution-archive was a superset of the source tarball.

**Comment by olekw** [comment]
Hi @aiuto and thanks for pointing out the source dist packages, I actually missed those when I first looked at the downloads. I'm working with those now to get a bootstrap build working in Debian Experimental. 

Thanks also for the workaround recommendations. Once we can get a functional Bazel build system working in Debian Unstable, I'd like to transition to building with just the source package. Git buildpackage should allow us to use the first of those workarounds. Obviously we always prefer having digital signatures for the peace-of-mind of our users (we don't like to ask them to "just trust us") but the git clone method should definitely work in the meantime. Thanks!

**Comment by aiuto** [comment]
I'm glad to hear that unblocked you.

Producing the sigs for the github, auto-generated source zip looks easy at first glance, but gets complex when it meets the secure signing pipeline we have set up:
- signing keys for builds are not on machines that can reach the internet.
- fetching the source zip to sign (via those github links) requires reaching the internet.
Obviously, something would have to give.

**Comment by olekw** [comment]
Hi @aiuto. Ah, yes that does appear to be a bit non-trivial. Although, as a security nerd, it's nice to see that you have such a robust security process!

Is there a possibility that at some point in the future you might publish a source-only archive using whatever process you currently use to create the source+bootload (bazel-3.0.0-devel.zip) package?

**Comment by aiuto** [comment]
We can do that. OTOH, we can't suppress github from creating their automatic zip and tar links. So there are always a few unsigned unless we add this extra signing path.

**Comment by olekw** [comment]
Yeah, what a bother that GitHub doesn't let you disable that! That definitely seems like a bug rather than a feature...

From my downstream perspective, as long as there's a signed source package (is it too much to ask for a tar.xz? ;) ) I'm happy. Doesn't bother me if there's an extra un-signed source package sitting around.

**Comment by aiuto** [comment]
@fweikert @philwo  For an estimate of difficulty.
