### ISSUE TITLE
bazel uses clang instead of clang++ as C++ linker

### ISSUE THREAD

**Issue by dopiera** [bazelbuild/bazel#11122]
### Description of the problem / feature request:

When compiling C++ code base (e.g. https://github.com/googleapis/google-cloud-cpp/), bazel uses `clang` as the linker. `clang++` should be used instead, because otherwise, if undefined behavior sanitizer (ubsan) is used, linking yields errors (`undefined reference to __ubsan_handle_function_type_mismatch_v1'` among similar others).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Running:
```sh
$ cd /tmp/
$ git clone https://github.com/bazelbuild/examples
$ cd examples/cpp-tutorial/stage1
$ bazel build --copt=-Og --copt=-g --copt=-fsanitize=undefined --copt=-fno-omit-frame-pointer --linkopt=-fsanitize=undefined //main:hello-world
```
yields:
```
WARNING: Stripping enabled, but '--copt=-g' (or --per_file_copt=...@-g) specified. Debug information will be generated and then stripped away. This is probably not what you want! Use '-c dbg' for debug mode, or use '--strip=never' to disable stripping
INFO: Analyzed target //main:hello-world (13 packages loaded, 47 targets configured).
INFO: Found 1 target...
ERROR: /tmp/examples/cpp-tutorial/stage1/main/BUILD:3:1: Linking of rule '//main:hello-world' failed (Exit 1) clang failed: error executing command /usr/bin/clang @bazel-out/k8-fastbuild/bin/main/hello-world-2.params

Use --sandbox_debug to see verbose messages from the sandbox
main/hello-world.cc:19: error: undefined reference to '__ubsan_vptr_type_cache'
main/hello-world.cc:19: error: undefined reference to '__ubsan_handle_dynamic_type_cache_miss'
/usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/locale_facets.h:874: error: undefined reference to '__ubsan_vptr_type_cache'
/usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/locale_facets.h:874: error: undefined reference to '__ubsan_handle_dynamic_type_cache_miss'
/usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/locale_facets.h:875: error: undefined reference to '__ubsan_handle_dynamic_type_cache_miss'
/usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/locale_facets.h:876: error: undefined reference to '__ubsan_handle_dynamic_type_cache_miss'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
Target //main:hello-world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.377s, Critical Path: 0.82s
INFO: 1 process: 1 linux-sandbox.
FAILED: Build did NOT complete successfully
```
Manually running the linking phase with `clang++` works:
```
$ /usr/bin/clang++ @bazel-out/k8-fastbuild/bin/main/hello-world-2.params && echo "yay!"
yay!
```
### What operating system are you running Bazel on?

```sh
$ cat /etc/os-release 
NAME=Fedora
VERSION="31 (Container Image)"
ID=fedora
VERSION_ID=31
```

### What's the output of `bazel info release`?

```sh
$ bazel info release
release 2.0.0
```
###  Have you found anything relevant by searching the web?

Clang mentions this requirement (to use `clang++` rather than `clang`) explicitly in  [their documentation](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html):
> Use clang++ to compile and link your program with -fsanitize=undefined flag. Make sure to use clang++ (not ld) as a linker, so that your executable is linked with proper UBSan runtime libraries. You can use clang instead of clang++ if you’re compiling/linking C code.

**Comment by benjaminp** [comment]
This is very close to a dup of #4644.

**Comment by devjgm** [comment]
Throwing `--copt=-fno-sanitize=vptr` onto your command line makes the above work. Specifically, the following worked for me:

```shell
env CC=clang CXX=clang++ bazel build --copt=-Og --copt=-g --copt=-fsanitize=undefined --copt=-fno-omit-frame-pointer --linkopt=-fsanitize=undefined --copt=-fno-sanitize=vptr //main:hello-world
```

**Comment by oquenchil** [comment]
Closing as there is a work-around.

**Comment by carlosgalvezp** [comment]
Hi,

I have this very issue, and I think the solution is wrong, since you are just disabling a feature of the sanitizer! The documentation is very clear about the fact that the code must be linked with `clang++`, not `clang`. Why not let us users specify this in Bazel? Why does Bazel want "gcc" and "cpp" tools to be configured if it only uses the C one?

**Comment by carlosgalvezp** [comment]
Note: in more modern versions of Clang (e.g. Clang 12) you should use:

`-fno-sanitize=vptr,function`

**Comment by fmeum** [comment]
Using `clang++` as the linker instead of `clang` is just one of multiple ways to get the UBSan C++ runtime library linked in, so I don't think this is fundamentally a Bazel issue. Possible additional `linkopt` values that resolve the problem without losing features include:
* `-fsanitize-link-c++-runtime` to specifically link in sanitizer C++ runtimes,
* `--driver-mode=g++` to make `clang` behave like `clang++`.

See https://github.com/llvm/llvm-project/blob/17db125b487faa69d789b80d47b19da49522b168/clang/lib/Driver/SanitizerArgs.cpp#L904 for the relevant logic in the clang driver.

**Comment by tom-010** [comment]
This content of `.bazelrc`works for me
```
build --action_env=BAZEL_CXXOPTS="-std=c++20:-Wall:-fsanitize=address,undefined"
build --action_env=BAZEL_LINKOPTS="-fsanitize-link-c++-runtime:--driver-mode=g++:-fsanitize=address,undefined"
build --repo_env=CC=clang
```
