### ISSUE TITLE
Linker invocation uses transitive dynamic dependencies

### ISSUE THREAD

**Issue by kastiglione** [bazelbuild/bazel#11132]
### Description of the problem / feature request:

When using dynamic libraries on Apple platforms, Bazel's linker invocation is constructed to include the flattened dependency graph of all transitive dynamic libraries.

For example given this simplified dependency structure

```
Binary -> A -> B -> C
```

With Bazel, the `Binary` will have explicit references to  `A` `B` and `C`. Likewise `A` will dynamically load `B` and `C`. _Instead_, `Binary` should load only `A`, and `A` should load only `B`, etc. The dynamic loader handles loading the transitive dependency graph.

**Problem**

For a highly modular project with many small targets (which is advice given to achieve Bazel build performance), the top level binary can end up exceeding limits in the Mach-O structure. For our project to use dynamic libraries, we need the linker invocations to include only direct dynamic dependencies, not transitive.

**Questions**

* Was this by design, if so why?
* Does this same behavior exist for other platforms like Linux/ELF?
* How can we introduce a change to bazel so that only direct dynamic libraries are linked?

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

3.0

**Comment by kastiglione** [comment]
@jin do you know who we might be able to work with on this? If we were to implement this, who could help review and accept the work?

**Comment by jin** [comment]
Is this specific to C++, and not the ObjC rules?

**Comment by kastiglione** [comment]
I think this is specific to the ObjC rules.
