### ISSUE TITLE
Non-free license in source code (JSON Evil)

### ISSUE THREAD

**Issue by olekw** [bazelbuild/bazel#11135]
### Description of the problem / feature request:

There is a non-free license included in the source code at this location: https://github.com/bazelbuild/bazel/blob/master/third_party/java/jdk/langtools/LICENSE#L1507

This is the infamous JSON Evil license: https://wiki.debian.org/qa.debian.org/jsonevil

### Feature requests: what underlying problem are you trying to solve with this feature?

If some of the source code is actually under this license, then it should be removed and replaced with free source code. If no source code is actually under this license, then the license text should be removed.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Click on the first link. :)

### What operating system are you running Bazel on?

Debian

### Any other information, logs, or outputs that you want to share?

I know some people have made light of this license in the past and while it's funny at first glace it creates a great deal of uncertainty for both users and distributors of Open Source Software. What is Good, what is Evil, who is making that determination? Uncertainty (and risk) is not something that our community can afford.

**Comment by jin** [comment]
cc @aiuto @hicksjoseph @meisterT

**Comment by meisterT** [comment]
Yun, can you please have a look if that license snippet is up to date and what we could do to avoid it?

**Comment by meteorcloudy** [comment]
Sure, I'll look into this with @olekw
