### ISSUE TITLE
docker_build does not support docker 1.10

### ISSUE THREAD

**Issue by chenkan1994** [bazelbuild/bazel#1113]
Hi all:

I am using bazel to build docker images with following code:

``` bazel
load("@bazel_tools//tools/build_defs/docker:docker.bzl", "docker_build")

docker_build(
    name = "test_docker",
    base = "ubuntu.tar",
    directory = "/root",
    files = [
        "README.md"
    ],
    workdir = "/root",
    repository = "*******",
)
```

and it build successfully, but when I run
```shell
bazel run //test_docker:test_docker
```

it prints:
```
INFO: Reading 'startup' options from /home/user/.bazelrc: --batch
INFO: Found 1 target...
Target //test_docker:test_docker up-to-date:
  bazel-bin/test_docker/test_docker-layer.tar
INFO: Elapsed time: 7.684s, Critical Path: 1.80s

INFO: Running command line: bazel-bin/test_docker/test_docker
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.ISO-8859-1)
Loading a7574cb9918cfb685f21fab26e410ac15b934b806e32ae479af8f85ed1b506b0...
Tagging a7574cb9918cfb685f21fab26e410ac15b934b806e32ae479af8f85ed1b506b0 as ******/test_docker:test_docker
Warning: '-f' is deprecated, it will be removed soon. See usage.
Error response from daemon: no such id: a7574cb9918cfb685f21fab26e410ac15b934b806e32ae479af8f85ed1b506b0
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

Is there anybody knows why?

Thanks a lot!

**Comment by damienmg** [comment]
docker version?

**Comment by damienmg** [comment]
(it's failed on docker tag)

**Comment by chenkan1994** [comment]
```shell
~ docker -v
Docker version 1.10.3, build 20f81dd
```

**Comment by damienmg** [comment]
1.10 is not supported :( I am actually surprised it did not failed earlier

**Comment by chenkan1994** [comment]
ok.. then what's the latest version that is under support?

**Comment by damienmg** [comment]
1.9

**Comment by chenkan1994** [comment]
Got it, thanks!

**Comment by damienmg** [comment]
(it's a bit complex but supported 1.10 requires some effort and I need to free some time to work on it.

**Comment by chenkan1994** [comment]
Hey! @damienmg 

Is there any plan for fixing this problem? As my projects are now greatly depending on it...
So please update me if there is any progress, ok?

Thanks!

**Comment by damienmg** [comment]
Unfortunately we have no fix plan. I do hope to do it by the end of the quarter but it requires diving into the new image format they introduced with 1.10

**Comment by chenkan1994** [comment]
Got it. Seems can only try other methods, thank you any way!

**Comment by damienmg** [comment]
FWIW the CAS document from docker about the new format: https://gist.github.com/aaronlehmann/b42a2eaf633fc949f93b

the corresponding PR was https://github.com/docker/docker/pull/17924

And relevant bugs about load/save:
https://github.com/docker/docker/issues/20380
https://github.com/docker/docker/issues/18723

**Comment by damienmg** [comment]
Apparently the up-to-date doc is https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md

**Comment by guymers** [comment]
The Open Container Initiative has begun creating an image specification (https://github.com/opencontainers/image-spec) which is starting from the Docker 1.10 format. The new format seems to add more separation between layers and images with the image configuration file able to reference multiple layer tarballs. 

Taking the above into account, when updating to the new format should a new rule called something like container_build() be created instead? Maybe in order to distinguish between layers and images it could be split into container_layer() and container_image()? I've managed to get Bazel to build images in the OCI format, just wondering what the best way to integrate it would be.

**Comment by damienmg** [comment]
I think sticking with docker_build seems reasonable. Maybe we should just introduce a format attribute to it.

**Comment by ekuefler** [comment]
Any chance of this making 0.3.0 or will it not go out until 0.3.1?

**Comment by damienmg** [comment]
Probably not going to be in 0.3.0, We have to recut a canary so we can include it in 0.3.0.

I hope that by 0.3.1 docker rules will be out of bazel.
