### ISSUE TITLE
bazel not starting in tensorflow directory

### ISSUE THREAD

**Issue by arunjose696** [bazelbuild/bazel#11136]
I am not able to start bazel in the tensorflow directory in windows 10
steps to reproduce:
1)I have cloned tensorflow to my windows 10 pc with the below commands
```
git clone https://github.com/tensorflow/tensorflow
git checkout r2.1
cd tensorflow/
python configure.py
```

2) go inside the cloned repo bazel does not start. Even the "bazel version" command gives me the below message and does not execute

> Starting local Bazel server and connecting to it...
> ... still trying to connect to local Bazel server after 10 seconds ...
> ... still trying to connect to local Bazel server after 30 seconds ...

the "bazel version" command works fine for me in other directories other than tensorflow.

**Comment by philwo** [comment]
Hi @arunjose696,

sorry for the late reply. Are you still seeing this issue? If yes, we would need some more information about your system and Bazel version so that we can try to reproduce it.

Thanks,
Philipp
