### ISSUE TITLE
--experimental_replay_action_out_err does not gate the feature correctly

### ISSUE THREAD

**Issue by AlessandroPatti** [bazelbuild/bazel#11142]
### Description of the problem / feature request:
Action outputs are cached and shown even when the feature is disabled (default).
### Feature requests: what underlying problem are you trying to solve with this feature?
Replaying the action output generates confusion. E.g. we have seen an action outputting something on the lines of
```
...
Failed to execute...
....
Will retry...
```
which, if replayed, could lead into thinking the execution always fails and retries once.
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Execute the following:
```sh
TEMP_WORKSPACE=`mktemp -d`
pushd "$TEMP_WORKSPACE"
touch WORKSPACE
echo "genrule(name='Test', outs=['x.txt'], cmd='/bin/bash `pwd`/mock-echo Helloworld! | tee \$@')" > BUILD
echo 'echo $1' > 'mock-echo'
chmod 755 mock-echo
bazel build //:Test --remote_upload_local_results --disk_cache=cache
bazel clean
echo '' > 'mock-echo'
bazel build //:Test --disk_cache=cache
popd
rm -rf "$TEMP_WORKSPACE"
```
The second `bazel build` should not show the cached output 'Helloworld!', but it does.
### What operating system are you running Bazel on?

macOS 10.15.3

### What's the output of `bazel info release`?

3.0.0

**Comment by benjaminp** [comment]
This has always been the behavior of "remote" cached actions like those from `--disk_cache`. `--experimental_replay_action_out_err` only influences actions that are cached in memory by Skyframe.

**Comment by AlessandroPatti** [comment]
Thanks @benjaminp, I am indeed able to reproduce with an older version that does not have that flag. Unsure why I was not before.
Is there a way to disable cache stdout/err anyway?

**Comment by ulfjack** [comment]
I don't think there's a knob for that, no. You can disable all stdout/stderr, but you can't disable that from cache hits specifically. IIRC, the printing happens at a different level from the caching and doesn't even know whether it was a cache hit or not. What are your actions doing that requires a retry?

**Comment by coeuvre** [comment]
This is working as intended. Closing.
