### ISSUE TITLE
cuda_library uses cuda_library as dependency 

### ISSUE THREAD

**Issue by weidezhang** [bazelbuild/bazel#11154]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

**Currently I am building on cuda_library which depends on another cuda_library.**

### Feature requests: what underlying problem are you trying to solve with this feature?

Bazel complains 
target (rule class of 'cuda_library') doesn't have provider 'cc'. 
My cuda library rules looks like the following:
def cuda_library_impl(ctx):
    flags = ' '.join(ctx.attr.flags)
    output = ctx.outputs.out
    lib_flags = ["-std=c++11", "--shared", "--compiler-options -fPIC"]
    args = [f.path for f in ctx.files.srcs]
    deps_flags=[]
    for f in ctx.attr.deps:
      deps_flags += f.cc.link_flags
      deps_flags += ["-I" + d for d in f.cc.include_directories]
      deps_flags += ["-I" + d for d in f.cc.quote_include_directories]
      deps_flags += ["-I" + d for d in f.cc.system_include_directories]

    ctx.actions.run_shell(
            inputs=ctx.files.srcs + ctx.files.hdrs + ctx.files.deps,
            outputs=[ctx.outputs.out],
            arguments=args,
            env={'PATH':'/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/bin',},
            command="nvcc %s %s %s -I. %s -o %s" % (cuda_arch, ' '.join(lib_flags),  " ".join(args), " ".join(deps_flags), output.path)
     )

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
**have one cuda_library depends on another cuda_library**

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
release 0.5.3

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by jin** [comment]
What project is this? Bazel itself does not ship a cuda_library rule.

**Comment by jin** [comment]
Closing due to lack of information.
