### ISSUE TITLE
Some potential NPE  bugs

### ISSUE THREAD

**Issue by JulyChen728** [bazelbuild/bazel#11153]
Hi all, our bug scanner has reported some NPE bugs.

The first one is at [Profiler.java#L910](https://github.com/bazelbuild/bazel/tree/master/src/main/java/com/google/devtools/build/lib/profiler/Profiler.java#L910). Since the variable `data` is checked for `null` at [Profiler.java#L914](https://github.com/bazelbuild/bazel/tree/master/src/main/java/com/google/devtools/build/lib/profiler/Profiler.java#L914), a NPE bug may take place at [Profiler.java#L910](https://github.com/bazelbuild/bazel/tree/master/src/main/java/com/google/devtools/build/lib/profiler/Profiler.java#L910) if the `data` is `null`. Some familiar situations are at [ZipIn.java#L195](https://github.com/bazelbuild/bazel/tree/master/src/tools/android/java/com/google/devtools/build/android/ziputils/ZipIn.java#L195), since the variable `dirEntry` may be `null`, and [SignedJarBuilder.java#L327](https://github.com/bazelbuild/bazel/tree/master/third_party/java/apkbuilder/java/com/android/sdklib/internal/build/SignedJarBuilder.java#L327), since the variable `mMessageDigest` may be `null`.

The second one is at [OptionDefinition.java#L39](https://github.com/bazelbuild/bazel/tree/master/src/main/java/com/google/devtools/common/options/OptionDefinition.java#L39). A possible call chain is [OptionDefinition.java#L52](https://github.com/bazelbuild/bazel/tree/master/src/main/java/com/google/devtools/common/options/OptionDefinition.java#L52) => [OptionDefinition.java#L54](https://github.com/bazelbuild/bazel/tree/master/src/main/java/com/google/devtools/common/options/OptionDefinition.java#L54) =>[OptionDefinition.java#L39](https://github.com/bazelbuild/bazel/tree/master/src/main/java/com/google/devtools/common/options/OptionDefinition.java#L39). A NPE bug may take place at [OptionDefinition.java#L39](https://github.com/bazelbuild/bazel/tree/master/src/main/java/com/google/devtools/common/options/OptionDefinition.java#L39) when the variable `field` is `null`. 

Thanks.

**Comment by ulfjack** [comment]
@meisterT 

The OptionDefinition one is most likely benign (it'd crash bazel on startup so would be trivially caught by the integration tests). I'm not sure about the Profiler. The others are in Android code.
