### ISSUE TITLE
Make genrule.exec_tools consume provider

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#11157]
### Description of the feature request:

The idea would be for `genrule.exec_tools` to alternatively consume a Provider (perhaps `FilesToRunProvider`). This way it would be possibly to pass `my_py_binary` to `exec_tools` and have all necessary runtime files be added automatically.
So it no longer is necessary to specify all transitive runfiles of e.g. `py_binary`.

### Feature requests: what underlying problem are you trying to solve with this feature?

Transitive data dependencies of exec_tools have to be added for `py_binary`.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

`release 3.0.0`

**Comment by lberki** [comment]
`exec_tools` should consume` FilesToRunProvider`. Do you have evidence to the contrary?
