### ISSUE TITLE
Documentation issue: string

### ISSUE THREAD

**Issue by blackgnezdo** [bazelbuild/bazel#11168]
Documentation URL: https://docs.bazel.build/versions/master/skylark/lib/string.html#format

The {{ and }} are missing in the text below.
```
If you need to include a brace character in the literal text, it can be escaped by doubling: 
A replacement field can be either a name, a number, or empty.
```

**Comment by aiuto** [comment]
If anyone touches that, they should fix the examples so that the in order one is last. The utility should be name, position, and order. If you are just going to use order, you'd be just as well off with the % operator.

**Comment by laurentlb** [comment]
Thanks for the report!

Access in order is the simplest, and I think it's the most common.
The % operator has other issues and is not better than `.format`.
