### ISSUE TITLE
Provide standard output/error as an OutputGroupInfo when building cpp binaries/libraries

### ISSUE THREAD

**Issue by limdor** [bazelbuild/bazel#11177]
### Description of the problem / feature request:

Currently there is no way to get the standard output and the standard error of a cc_library or cc_binary when is compiled.

### Feature requests: what underlying problem are you trying to solve with this feature?

The underlying problem to try to solve would be to be able to access the output log of the compiler, with this way you could for example extract the warnings from the file and bind them to the target with an aspect.
A way to solve it without being to invasive would be to expose in a OutputGroupInfo two additional files, one for standard error and one for standard output.

**Comment by oquenchil** [comment]
You should see compiler errors on the command line, could you please write the bazel command you are using?

**Comment by limdor** [comment]
Yes, they appear in the consol but if they would be available as output it would provide better tools for warnings control and reporting. Any command that compiles a cc_library would be enough to reproduce.
bazel build //my_library

**Comment by oquenchil** [comment]
Maybe this helps:
https://docs.bazel.build/versions/master/build-event-protocol.html

**Comment by limdor** [comment]
As far as I understand this would require that is triggers the build per target and would not be possible to put it in an aspect as I was explaining in the underlying problem.
The idea would be to treat warnings in a similar way that you would do with an aspect for clang tidy.

**Comment by limdor** [comment]
I just realized that here I did not put all the information. Maybe the explanation is more complete in the slack
https://bazelbuild.slack.com/archives/CGA9QFQ8H/p1587319775067200?thread_ts=1587319775.067200&cid=CGA9QFQ8H

**Comment by oquenchil** [comment]
Can you please copy the information here for better tracking?

**Comment by limdor** [comment]
Sure

Hi, I am trying to find a way to properly report compiler warnings that a developer can run incrementally without having to do a clean build every time. I was considering to build an aspect with this way you could associate warnings to targets. The issue that I have there is that I would need to have access to the standard output of the compilation of the rules for later on being able to parse it, some warning could come from includes from other rules.
Is there a way to access the compilation log? What would be the strategy? Do you have a better idea on how to report compilation warnings per rule?

**Comment by oquenchil** [comment]
There was a separate feature request to allow passing any file from the Starlark API to the compilation action as an additional output in a generic way. Without Bazel having to know about what that file is for.

I'm not aware if the compiler allows you to pass a flag to tell it where it should store those errors/warnings.

We'd be open to allowing support for this as long as it's in that generic way and you would write your own aspect that takes care of the details. But we won't add support to keep the errors in a file that is propagated throughout the build.

**Comment by limdor** [comment]
Make sense. I also see it in a generic way, any rule could provide additional two files on request that provides you with the standard output and the standard error output. The combination of both of them is already available right now on the console.
Then of course is responsibility of the user to parse or do whatever it wants with the content of the files.
I was describing a use case just to show how could be beneficial and to show that is not a made up use case.

**Comment by oquenchil** [comment]
What I meant was that it came up before that people wanted flexibility in passing additional output files to cc_common.compile() unrelated to what you want to do here. The same mechanism could be used so that you would have to pass the additional output file and your custom flag that will the compiler print the errors to a file.

We won't add support ourselves to printing that information to a file.

**Comment by limdor** [comment]
Now I understand what you meant, make sense and should work. Thanks

**Comment by limdor** [comment]
> There was a separate feature request to allow passing any file from the Starlark API to the compilation action as an additional output in a generic way. Without Bazel having to know about what that file is for.

@oquenchil could you post the link of the feature that you talk about?

**Comment by limdor** [comment]
@bazelbuild/triage this is still relevant. Please keep the issue opened
