### ISSUE TITLE
Is there a way a new_git_repository BUILD can reference local skylark

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/bazel#1117]
suppose you are pulling in a github repo R but want to use a locally written skylark rule in the build file.
See the example below -- the idea is, you are pulling in sources from the remote R repo, but you have a local .bzl rule that is very useful and you want to use it in the BUILD.remote file. 
The current version results in an error
ERROR: /home/user/proj/WORKSPACE:20:1: error loading package '@R//': Extension file not found. Unable to load package for '@R//util:useful.bzl': BUILD file not found on package path and referenced by '//external:R'.

Is there a way to do this, or can the load be altered to reference the local .bzl?  Like load("@local//util:useful.bzl"), or something?

-- WORKSPACE
new_git_repository(
  name = "R_repo",
  remote = "https://github.com/user/R",
  tags = "1.0",
  build_file = "BUILD.remote",
)
bind(name="R", actual="@R_repo//:R")
-- BUILD.remote
load("//util:useful.bzl", "useful")

useful(
  name="R",
  srcs = [...]  # these come from the remote repo
)

**Comment by shahms** [comment]
You need to use a fully-qualified label in the `load()` statement:

load("@//util:useful.bzl", "useful")

**Comment by pmbethe09** [comment]
Ah, the '@' symbol is what I couldn't figure out.  Thanks!
