### ISSUE TITLE
apple_common.multi_arch_split should transition on platforms instead of crosstool_top

### ISSUE THREAD

**Issue by steeve** [bazelbuild/bazel#11181]
# Description of the problem / feature request:

Let `apple_common.multi_arch_split` transition on `platforms`/constraints instead of `crosstool_top`/`cpu`.

### Feature requests: what underlying problem are you trying to solve with this feature?

According to [osx_archs.bzl](https://github.com/bazelbuild/bazel/blob/3.0.0/tools/osx/crosstool/osx_archs.bzl), Apple toolchains are already constraint aware and thus can be selected by specifying a platform.

However, according to [AppleCrosstoolTransition](https://github.com/bazelbuild/bazel/blob/3.0.0/src/main/java/com/google/devtools/build/lib/rules/objc/AppleCrosstoolTransition.java), `apple_common.multi_arch_split` is still implemented by transiting `crosstool_top` and `cpu` instead of platforms.

This creates weird cases for downstream rules which have to transition on `crosstool_top`/`cpu` instead of letting the constraints apply directly to their toolchains as well.
For instance, rules could expose `CcInfo` and thus be used as dependencies of a rule using `multi_arch_split`.
See https://github.com/bazelbuild/rules_go/pull/2451.

Looking at `rules_apple`, I see the starlark transitions are are implemented but `apple_common.multi_arch_split` is still used.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

```
release 3.0.0
```

### Any other information, logs, or outputs that you want to share?

1. https://github.com/bazelbuild/rules_go/pull/2451

**Comment by jmmv** [comment]
@katre , could you triage? I see you are involved in the review of #2451 and I know little about this stuff right now.

**Comment by steeve** [comment]
Closing, wrong dup of #11180. Sorry for the noise.
