### ISSUE TITLE
Provide `weight` when defining a toolchain

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#11189]
### Description of the feature request:

Particularly when `WORKSPACE` configuration is complex, it is not always clear _which_ toolchain will be selected. The [resolution algorithm](https://docs.bazel.build/versions/master/toolchains.html#toolchain-resolution) says "the first available toolchain" will be used, but doesn't define "first". Presumably this has something to do with ordering of nodes within the graph, and not necessarily which toolchain gets defined by `register_toolchain` first.

This is problematic for cases where we may want to define a default toolchain for use with a ruleset, but allow users to later override this default in their own workspace. For example:

```py
load("@myamazingrules//foo:defs.bzl", "default_setup")

# This will register a default "FooToolchain" for use for foo_rules
default_setup()

# This also registers a "FooToolchain" which we would prefer to use
register_toolchain("//:foo-toolchain")
```

This pattern of providing a default and allowing overrides makes for a smooth user-experience.

### Feature requests: what underlying problem are you trying to solve with this feature?

 1. Allows users of rulesets to progressively enhance their use of rules by defining sensible defaults and then define more advanced toolchains if needed.
 2. When using a federated ruleset (eg `bazel-federation`) allow rulesets that are depended upon to be configured with sensible defaults, and later override them.

In both cases, allowing a toolchain to be registered with a weight would allow the "default" toolchain to be given a very low weight, and toolchains we actually declare directly to be given a higher weight.

An alternative would be to modify the toolchain selection algorithm to select the most recently defined toolchain (as specified by the order to calls to `register_toolchains` in the workspace file). That is a "last one in, wins" approach, with command-line overrides taking even higher precedence.

**Comment by aiuto** [comment]
cc: @katre

**Comment by katre** [comment]
I agree that this would be a useful feature, but I don't think we have bandwidth to make it a priority currently.

One tricky area is how to specify the weight for a toolchain passed on the command line. Is there a special weight for command-line toolchains, or is the flag complicated to specify the weight?

It wouldn't be a difficult feature for an external contributor to add. The relevant code is in a few places:
-  [SingleToolchainResolutionFunction](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/SingleToolchainResolutionFunction.java?ss=bazel&q=SingleToolchainResolutionFunction) - This is where toolchain resolution actually happens.
-  [RegisteredToolchainsFunction](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/RegisteredToolchainsFunction.java?ss=bazel&q=RegisteredToolchainsFunction) - This is where toolchains are aggregated from all sources (command line and WORKSPACE).
-  [WorkspaceGlobalsApi.registerToolchains](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/skylarkbuildapi/WorkspaceGlobalsApi.java;l=132) - The interface for the `register_toolchains` function.
