### ISSUE TITLE
all_incompatible_changes  produces incompatible_tls_enabled_removed warning

### ISSUE THREAD

**Issue by JayBazuzi** [bazelbuild/bazel#11193]
```
WARNING: Option 'incompatible_tls_enabled_removed' is deprecated: No-op. See #8061 for details.
```

_Originally posted by @limdor in https://github.com/bazelbuild/bazel/issues/8061#issuecomment-608626716_

**Comment by JayBazuzi** [comment]
This problem was mentioned in 8061 but since that issue is closed I figured we needed a new open issue.

**Comment by limdor** [comment]
@aiuto @coeuvre @JayBazuzi I would propose to close this ticket, considering https://github.com/bazelbuild/bazel/issues/13892 and https://github.com/bazelbuild/bazel/issues/13923 I don't think it is relevant anymore.

**Comment by JayBazuzi** [comment]
That makes sense to me.
