### ISSUE TITLE
Support C++/CX MSVC language extensions

### ISSUE THREAD

**Issue by kjteske** [bazelbuild/bazel#11199]
### Description of the problem / feature request:

Support for Windows [C++/CX](https://docs.microsoft.com/en-us/cpp/cppcx/visual-c-language-reference-c-cx?view=vs-2019) MS extensions for C++ files, i.e. with the [/ZW](https://docs.microsoft.com/en-us/cpp/build/reference/zw-windows-runtime-compilation?view=vs-2019) compilation flag passed to MSVC's cl.exe.

### Feature requests: what underlying problem are you trying to solve with this feature?

Enable building C++ libraries using C++/CX and producing [.winmd](https://docs.microsoft.com/en-us/uwp/winrt-cref/winmd-files) files.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Add the '/ZW' flag and attempt to build with Bazel's built-in MSVC
toolchain.

Example repo at https://github.com/kjteske/bazel_cppcx_example.

### What operating system are you running Bazel on?

Windows 10.

### What's the output of `bazel info release`?

release 3.1.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

I've got a few notes on what Compiling/Linking would look like in
a solution.

**Compiling**

Adding the `/ZW` flag to MSVC enables Microsoft extensions for interop with C#, and requires `#using` .winmd files provided by Visual Studio (or at least implicit `#using` commands done by the compiler). This is similar to `#include` for a regular header files.
Example common required winmd files:
* C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.25.28610/lib/x86/store/references/platform.winmd
* C:/Program Files (x86)/Windows Kits/10/UnionMetadata/10.0.18362.0/windows.winmd

When compiling with `/ZW`, the first error is that `platform.winmd` and `windows.winmd` files cannot be found. This can be resolved with either `/AI` compile flags, or by setting up the `LIBPATH` environment variable and using `--action_env=LIBPATH`. In my prototyping, I set up `LIBPATH` (by calling `vcvarsall.bat`), which gets us a little further along. Now, we can successfully finish compiling, but get caught by Bazel's dependency checks that parse 'including file' outputs due to MSVC's [/showIncludes](https://docs.microsoft.com/en-us/cpp/build/reference/showincludes-list-include-files?view=vs-2019) flag that Bazel turns on (and can't be disabled). MSVC will output something like this at the end of the compilation:
```
Note: including file: c:\program files (x86)\microsoft visual studio\2019\professional\vc\tools\msvc\14.24.28314\lib\x86\store\references\platform.winmd
Note: including file: c:\program files (x86)\windows kits\10\unionmetadata\10.0.17763.0\windows.winmd
Note: including file: C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.24.28314\\include\vccorlib.h
```
Bazel parses these files, and [HeaderDiscovery.java](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/cpp/HeaderDiscovery.java;l=136?q=discoverInputsFromDependencies&ss=bazel) does some inclusion checks, and errors:
```
ERROR: C:/users/kyle/dev/bazel_cppcx_example/BUILD:1:1: undeclared inclusion(s) in rule '//:cppcx_example':
this rule is missing dependency declarations for the following files included by 'Example.cpp':
  'C:/program files (x86)/microsoft visual studio/2019/professional/vc/tools/msvc/14.25.28610/lib/x86/store/references/platform.winmd'
  'C:/program files (x86)/windows kits/10/unionmetadata/10.0.18362.0/windows.winmd'
```
To avoid this error, I think we would want to permit the directories containing the winmd files, similar to how system include prefixes are permitted and Bazel doesn't error on seeing `vccorlib.h` here. This doesn't sound too hard to create a patch for.

Ideally, we wouldn't have to set up LIBPATH either. Maybe this could be implemented with features to pass appropriate /AI flags?

**Linking & Output**

We would also want to support the [/WINMDFILE](https://docs.microsoft.com/en-us/cpp/build/reference/winmdfile-specify-winmd-file?view=vs-2019) linker option so we can produce a .winmd file from the library, and include this in the Bazel outputs.

**Interest?**

Is there any interest in this feature, or would maintainers be willing to take a look at a PR or give some recommendations on how to implement support? Does this make sense to go into Bazel/rules_cc proper, or a separate toolchain outside of Bazel? Since this would re-use so much of the existing MSVC toolchain support in Bazel, I think this would be much easier to maintain if in Bazel/rules_cc.

**Comment by ianier** [comment]
Compiling for WinRT with Bazel is currently possible with workarounds (e.g. see what we've done for tensorflow-cc at https://github.com/microsoft/vcpkg/issues/14252).

As mentioned there, _Bazel calls VCVARSALL.BAT in windows_cc_configure.bzl to set the INCLUDE/LIB environment vars. While VCVARSALL.BAT supports specifying the environment type (e.g. VCVARSALL.BAT amd64 store), it looks like this is not foreseen in the current implementation of windows_cc_configure.bzl, by looking at [the code](https://github.com/bazelbuild/bazel/blob/8f9f83aaf35561b24850d2df9fcce9f10a1fa840/tools/cpp/windows_cc_configure.bzl#L371)._

BTW, it would also be great to support arm64 as a cross-compilation target.
