### ISSUE TITLE
Expose Artifact#isSymlink() to Starlark

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/bazel#11209]
This is a feature request to expose `Artifact#isSymlink()` to Starlark so users can check whether a file is a symlink.
Note that this only makes sense for unresolved symlinks, which are still experimental (`--experimental_allow_unresolved_symlinks`).

//cc @brandjon

**Comment by brandjon** [comment]
I requested this in #10695. Given that using the wrong kind of file in the wrong place causes an error, I figured there should be a mechanism for code to distinguish between them.

That said, the use is hypothetical, and I think it's fine to not prioritize unless/until real use cases pop up.

Documentation for the field should be clear that it only refers to whether the `File` was declared as a symlink, e.g. by using `ctx.actions.declare_symlink()`. In particular, even when `is_symlink` is false, the physical file path can still be a symlink that points to another `File`.

**Comment by tjgq** [comment]
@bazel-io fork 8.0.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 8.0.0 RC2](https://github.com/bazelbuild/bazel/releases/tag/8.0.0rc2). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=8.0.0rc2`. Thanks!
