### ISSUE TITLE
Improve error when user forgets 'native.'

### ISSUE THREAD

**Issue by chsigg** [bazelbuild/bazel#11204]
### Feature request:
I've had several instances where I forgot the 'native.' prefix inside a .bzl macro. Sometimes it takes me quite a while to realize what the problem is. I've heard of other people running into this as well. 

I'm wondering whether it would be hard to detect these cases and report a specific error message (`Did you forget 'native.'?`) to help your users, instead of just 'name is not defined'.

Ordinary typos are reported beautifully: 
`name 'fooo' is not defined (did you mean 'foo'?)`

BUILD:
```
load(":defs.bzl", "foo")
foo()
```
defs.bzl:
```
def foo():
  cc_library(name = "foo")
```

```
$ bazel build :foo
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: /usr/local/google/home/csigg/defs.bzl:2:3: name 'cc_library' is not defined
ERROR: Skipping ':foo': error loading package '': Extension 'defs.bzl' has errors
WARNING: Target pattern parsing failed.
ERROR: error loading package '': Extension 'defs.bzl' has errors
INFO: Elapsed time: 5.364s
INFO: 0 processes.
```

**Comment by laurentlb** [comment]
I wanted to do it at some point, but there are some difficulties. For example, we want the code of the interpreter to be independent from Bazel (it is used in other contexts too).

The long term goal is to get rid of the native prefix and make sure that rules are loaded from somewhere.

**Comment by sladyn98** [comment]
@laurentlb @aiuto Is this a good first issue to pick up and solve :)

**Comment by laurentlb** [comment]
@alandonovan: do you think there's a clean way to add this error message?

**Comment by aiuto** [comment]
It's probably not a good first issue. If Laurent asked Alan about it possible to do cleanly, it is almost certainly subtle.

**Comment by sladyn98** [comment]
@aiuto No worries I will look for other issues to solve. Thanks

**Comment by alandonovan** [comment]
This is not feasible. The "undefined name" error is reported statically, while compiling the .bzl file, before .bzl execution begins, and before the 'native' value even exists.

(It might be easy to add a Bazel-specific hack to the Starlark interpreter, but I have spent the last 9 months doing nothing but removing them.)

**Comment by chsigg** [comment]
That's fine. Thanks for looking into it. Feel free to close.
