### ISSUE TITLE
Add BUILD_TARGET environment variable to all build actions

### ISSUE THREAD

**Issue by Qinusty** [bazelbuild/bazel#11216]
### Description of the feature request:

Currently bazel adds TEST_TARGET as an environment variable to all test actions which is great for tracking down targets causing failures within actions executed remotely. Tracking down the related target for a failed build action is much harder.

### Feature requests: what underlying problem are you trying to solve with this feature?

It is currently quite awkward to trace a failed build action back to the target which created it.

###  Have you found anything relevant by searching the web?

The [test-encyclopedia](https://docs.bazel.build/versions/master/test-encyclopedia.html#initial-conditions) details TEST_TARGET but I haven't found anything for other actions.

**Comment by janakdr** [comment]
Could you expand a bit on the use case here? Within a Bazel invocation, Bazel should print out enough information to identify the failing rule. This is for the case of debugging failed actions on the remote execution server?

I don't think that currently build actions have any environment variables set, so this would be a completely new thing. I think that a two-line hacky change to [AbstractAction](https://github.com/bazelbuild/bazel/blob/cfe91cef9f2473836d2f8a64cdbeda84ec9ed442/src/main/java/com/google/devtools/build/lib/actions/AbstractAction.java#L149-L153) to set env to

```
    this.env = env.addFixedVariables(ImmutableMap.of("BUILD_TARGET", getPrimaryOutput().getExecPathString()));
```

would work. This seems to work for genrules and Starlark, but not for tests, which is maybe fine. I'm open to a PR implementing this, but we will have to think about how to limit this: I think we'd only want a very few such variables. Note that we could easily bork remote caching if we weren't careful.

As a current workaround, if the relevant rules are Starlark, you could manually add the action label to the command line, perhaps?
