### ISSUE TITLE
--worker_sandboxing fails to create output directories

### ISSUE THREAD

**Issue by jongerrish** [bazelbuild/bazel#11210]
### Description of the problem / feature request:

When performing builds of a android_kt_library and using sandboxed workers (on mac and linux) build fails as unable to create output directories. Bazel fails as it attempts to create child directories before parents. I see this with a Kotlin library but I guess this is an issue with any rules that pass outputs with directories more than one deep.

### Feature requests: what underlying problem are you trying to solve with this feature?

Not blowing up

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

bazel build --worker_sandboxing //some/kotlin/library

### What operating system are you running Bazel on?

mac + linux fail the same way

### What's the output of `bazel info release`?

2020/04/23 12:39:22 Using unreleased version at commit 27

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Version 3.X with some local patches.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git@github.sc-corp.net:XXXXXX/bazel.git
0c72f0e2d07b125c4c73dd7733b522f24003c4a3
0c72f0e2d07b125c4c73dd7733b522f24003c4a3

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

This can simply be fixed by moving this line

dirsToCreate.addAll(outputs.dirs());

from:-

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/worker/WorkerExecRoot.java#L103

to after the loop to build the ancestors right below as ancestor directories should be created before children.

I can send a PR for this.

**Comment by ulfjack** [comment]
That code is definitely not correct, and I'm wondering how this could be passing even basic testing. I'm not sure how best to fix it, though. What are you proposing?

**Comment by ulfjack** [comment]
@jmmv @philwo

**Comment by jongerrish** [comment]
I have a fix in our local fork, I'll upstream a PR for this today.
