### ISSUE TITLE
Inconsistent query help valid values for --output between long help and error message

### ISSUE THREAD

**Issue by stephenchu** [bazelbuild/bazel#1121]
Error message:

```
$ bazel query 'rdeps(//..., //1:file)' --output=foo
ERROR: Invalid output format 'foo'. Valid values are: label, label_kind, build, minrank, maxrank, package, location, graph, xml, proto.
```

Long:

```
$ bazel help query --long

...
--output (a string; default: "label")
  The format in which the query results should be printed. Allowed values 
  are: label, label_kind, minrank, maxrank, package, location, graph, xml, 
  proto, record.
```

Difference: `record` vs `build`

Bazel version:

```
Build label: head (@829d118)
Build target: bazel-out/local_linux-fastbuild/bin/src/main/java/bazel-main_deploy.jar
Build time: Fri Apr 1 18:04:16 2016 (1459533856)
Build timestamp: 1459533856
Build timestamp as int: 1459533856
```

**Comment by kchodorow** [comment]
Based on https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/query2/output/OutputFormatter.java#L63-L75, looks like it actually takes both.

**Comment by helenalt** [comment]
Now the help message in this file lists neither build nor record:
src/main/java/com/google/devtools/build/lib/query2/output/QueryOptions.java

But the implementation seems to have support for both RECORD and BUILD
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/query2/output/OutputFormatter.java#L63-L75

@juliexxia  Which is correct?

**Comment by juliexxia** [comment]
BUILD is supported but RECORD is not. Sending out a change for review now.
