### ISSUE TITLE
//tools/build_defs/pkg:incompatible_no_build_defs_pkg_deb Remove pkg_deb from Bazel

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#11217]
//tools/build_defs/pkg:pkg_deb has moved to https://github.com/bazelbuild/rules_pkg/tree/master/pkg and is no longer maintained as part of Bazel nor used in its build or tests.  Users should migrate to the new versions.

Migration:

1. Add WORKSPACE stanza as specified in a rule_pkg release
https://github.com/bazelbuild/rules_pkg/releases
2. Replace instances of
```
load("//tools/build_defs/pkg:pkg.bzl", "pkg_deb")
```
with
```
load("@rules_pkg//:pkg.bzl", "pkg_deb")
```
One line solution (for some users)
```
find . -name 'BUILD' -o -name '*.bzl' | xargs sed -i -e '/^load/s#//tools/build_defs/pkg:#@rules_pkg//:#'
```

Expected timeline:
- Flag flip at next major Bazel release
- Code removal by next minor release after that.

**Comment by siddharthab** [comment]
This flag is not yet available in bazel. Can we remove the `migration-3.y` labels from the issue because bazelisk uses it to check for migration readiness?

**Comment by aiuto** [comment]
Done. I'm not sure what happened there.

**Comment by siddharthab** [comment]
Thanks. Can you also remove the labels from #11218?

**Comment by aiuto** [comment]
Status update: Planned removal in March 2021

**Comment by aiuto** [comment]
Isn't this a "defeature request"? :-)

**Comment by aiuto** [comment]
Status update:
- Removal pkg_deb planned for March 1
- Latest presubmit: https://buildkite.com/bazel/google-bazel-presubmit/builds/43661
- Thanks to @dannysullivan for migrating Google to rules_pkg
