### ISSUE TITLE
C++ Able to access file via relative path only in Linux

### ISSUE THREAD

**Issue by Guang-yi** [bazelbuild/bazel#11212]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

https://stackoverflow.com/questions/46100906/c-bazel-project-with-a-data-repository/46100907#46100907

### Feature requests: what underlying problem are you trying to solve with this feature?

Simple example c++ program where read file, and try and output contents of a file works in Linux but not in Windows. For some reason `std::ifstream in("data/someData.txt");` does not recognize relative path in Windows environment. Only workaround is absolute path.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try taking this sample [repo](https://github.com/vincent-picaud/Bazel_with_Data/blob/master/bin/example.cpp) and build binary for Linux and Windows.

### What operating system are you running Bazel on?

Windows and Linux

**Comment by Guang-yi** [comment]
I suspect that perhaps the 'data' option is broken for bazel on windows

**Comment by aiuto** [comment]
Have you tried using the runfiles library?
https://github.com/bazelbuild/bazel/blob/master/tools/cpp/runfiles/runfiles_src.h

**Comment by Guang-yi** [comment]
Thanks for the tip! Here is how I got the file path from a relative path:
```
std::unique_ptr<Runfiles> runfiles(Runfiles::Create(argv[0], &error));
std::string path = runfiles->Rlocation("__main__/relative_path");
```

It should be noted that you have to prepend the relative path with `__main__` for this to work.
