### ISSUE TITLE
Remove pkg_rpm from Bazel

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#11218]
//tools/build_defs/pkg:pkg_rpm has moved to https://github.com/bazelbuild/rules_pkg/tree/master/pkg and is no longer maintained as part of Bazel nor used in its build or tests.  Users should migrate to the new versions.

Migration:

1. Add WORKSPACE stanza as specified in a rule_pkg release
https://github.com/bazelbuild/rules_pkg/releases
2. Replace instances of
```
load("//tools/build_defs/pkg:pkg.bzl", "pkg_rpm")
```
with
```
load("@rules_pkg//:pkg.bzl", "pkg_rpm")
```
One line solution (for some users)
```
find . -name 'BUILD' -o -name '*.bzl' | xargs sed -i -e '/^load/s#//tools/build_defs/pkg:#@rules_pkg//:#'
```

Expected timeline:
- Flag flip at next major Bazel release
- Code removal by next minor release after that.

**Comment by siddharthab** [comment]
This flag is not yet available in bazel. Can we remove the `migration-3.y` labels from the issue because bazelisk uses it to check for migration readiness?
