### ISSUE TITLE
Sharing violation

### ISSUE THREAD

**Issue by sebastianrath** [bazelbuild/bazel#11220]
Hi,

in the last days we often experienced the following issue on several compiling machines:

```
Execution platform: //_build:windows-clang-cl. Note: Remote connection/protocol failed with: execution failed

 Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(241):
nativeCreateProcess(\\?\C:\out\pdh7mf62\execroot\foo\bazel-out\_tmp\actions\stdout-2510-0):

The process cannot access the file because it is being used by another process.
```

I used `Process Monitor` to see where this error comes from and found that `java.exe` opens the log file twice in a row without closing it before. Since a shared read is requested, this might actually be intended. But since there is already a writer on this file, either a `CloseFile` is missing or a shared write access.

![Capture](https://user-images.githubusercontent.com/12844423/80243019-650d1900-8634-11ea-8a5f-588ae74e764d.PNG)

This is the source location that is causing the issue: https://github.com/bazelbuild/bazel/blame/master/src/main/native/windows/processes-jni.cc#L233

**Comment by aiuto** [comment]
Is there anything you can provide to help repo this?
Is is strictly windows or on other platforms?
Are there any particular kinds of targets?

**Comment by seb-mtl** [comment]
At the moment I can just reproduce this on Windows, since we don't use Bazel on macOS or Linux atm. I tried today to strip it down but couldn't create a reliable minimal example

**Comment by s-jeckel-mxn** [comment]
One important piece of information is that this runs inside a Docker container on mapped volume. We already disabled anti-virus software etc. to make sure no other applications access the files in the background.

**Comment by ax-lothas** [comment]
OS: Windows 10 Pro 21H2 x64
Bazel: 4.2.1
Java: 11.0.6.0 (shipped with bazel)
No Docker or other containers, no virtualization - just running on bare silicon.

During a build with bazel, I get (non-deterministically) the error message
```
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(279): nativeCreateProcess(\\?\C:\users\lothas\_bazel_lothas\f3rtzs7l\execroot\bauhaus\bazel-out\_tmp\actions\stdout-22-0): The process cannot access the file because it is being used by another process.
```
Disc-cache and remote cache are active. Writing the build results back into the disk-cache is allowed, writing them into the remote cache is forbidden.

I traced this with procmon:
The java process creates the file `stdout-22-0` with
 * Desired Access: Generic Write, Read Attributes
 * ShareMode: Read, Write
 * OpenResult: Created
 * Stacktrace shows that the call comes from java.dll: Java_java_io_FileOutputStream_open0 + 0x23

A bit later, the same java process tries to open the same file `stdout-22-0` with
 * Desired Access: Generic Write, Read Attributes
 * ShareMode: Read
 * Result: SHARING VIOLATION
 * Stacktrace shows that the call comes from windows_jni.dll: Java_com_google_devtools_build_lib_windows_WindowsProcesses_createProcess + 0x147

The ShareMode (only Read) of the second open attempt collides with the desired access (Generic Write) of the first open call.

![bazel share violation event](https://user-images.githubusercontent.com/98159917/150525248-da05fd7c-8838-45b2-bc7f-5c2634aaae48.png)

![bazel share violation stack](https://user-images.githubusercontent.com/98159917/150525270-b40bc69b-34da-4194-bd6b-295f12f0ab17.png)

**Comment by lummax** [comment]
To expand on @ax-lothas case (same company/code base)

> Disc-cache and remote cache are active. Writing the build results back into the disk-cache is allowed, writing them into the remote cache is forbidden.

The issue reproduces easily while using a cold disk-cache, ensuring `bazel` tries to upload to that disk-cache. I was repeatedly unable to reproduce the case when disabling the disk-cache.

Also to get it linked: https://github.com/bazelbuild/bazel/issues/10878

**Comment by dgrunwald** [comment]
Note that the two attempts to open the file are on different threads (this is a non-deterministic race condition).

A potential easy fix/workaround would be to add `| FILE_SHARE_WRITE` to https://github.com/bazelbuild/bazel/blob/ce1a5d0fbf1d935e50b26a85ea465e5d4eb6c7aa/src/main/native/windows/processes-jni.cc#L271
