### ISSUE TITLE
cquery ignoring --build_tags_filter since v2.1.0

### ISSUE THREAD

**Issue by FaBrand** [bazelbuild/bazel#11222]
### Description of the problem / feature request:

Bazel cquery seems to ignore changes in --build_tags_filter starting with bazel 2.1.0.

It can be reproduced on windows and linux (ubuntu window-subsystem-linux) using the provided scripts

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I created a minimal example here: https://github.com/FaBrand/bazel-learning/tree/master/bazel_cquery_tag_filter

#### Error case

Starting from bazel 2.1.0, Step 2 still returns the same result as step 1 even tough it should not. This is the case up to and including version 3.1.0

### What operating system are you running Bazel on?

MS Windows 10 1809 BUILD 17763.1158

Ubuntu installed under Windows Subsystem Linux
```
$ uname -a
Linux 4.4.0-17763-Microsoft #864-Microsoft Thu Nov 07 15:22:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linu
```

### What's the output of `bazel info release`?

`release 2.0.0` as tested working version 
`release 2.1.0` as tested broken version
`release 3.1.0` as tested broken version

###  Have you found anything relevant by searching the web?

No issues that seem to be directly related to this.

https://github.com/bazelbuild/bazel/issues/11078 sounds similar

### Any other information, logs, or outputs that you want to share?

I did a `git bisect` between the bazel tags 2.0.0 and 2.1.0 under windows.
Using `//src:bazel.exe` as the execuable to test cquery.
This lead to:

```
9f9b919ecc00cb36787ac0d0936394d983df51f9 is the first bad commit
commit 9f9b919ecc00cb36787ac0d0936394d983df51f9
Author: gregce <gregce@google.com>
Date:   Tue Jan 7 13:31:04 2020 -0800

    Make cquery 'somepath' more accurate.

    Specifically, make somepath(//foo, //bar) report results
    when //bar isn't built in the top-level configuration (because
    of a transition).

    To really work properly, this requires --universe_scope:

    $ blaze cquery 'somepath(//foo, //bar)' -- universe_scope=//foo

    Otherwise, //bar also gets built in the top-level configuration and
    somepath looks for *that* version, which is not the one in //foo's
    deps.

    RELNOTES: cquery 'somepath' returns more reliable results when the
    dep has a different configuration than the parent. To get a result for
    `somepath(//foo, //bar`) where //bar isn't in the top-level configuration,
    run your query with `--universe_scope=//foo`. See cquery docs for details.
    PiperOrigin-RevId: 288560710
```

**Comment by FaBrand** [comment]
@gregestren

**Comment by gregestren** [comment]
Agreed, this sounds similar to https://github.com/bazelbuild/bazel/issues/11078.

Offhand I don't know why 9f9b919ecc00cb36787ac0d0936394d983df51f9 would trigger that.

**Comment by FaBrand** [comment]
i double checked manually with https://github.com/bazelbuild/bazel/commit/9f9b919ecc00cb36787ac0d0936394d983df51f9 built the commit and the one before https://github.com/bazelbuild/bazel/commit/e6433404f18da686dd4b19a6a9ac9b489d602f1c

Same result, with https://github.com/bazelbuild/bazel/commit/9f9b919ecc00cb36787ac0d0936394d983df51f9 it does not work

I will try to further debug the commit and see what might have caused the issue

**Comment by FaBrand** [comment]
I could find something:
I commented the lines from https://github.com/bazelbuild/bazel/commit/9f9b919ecc00cb36787ac0d0936394d983df51f9#diff-875bd31f18543d83a185668a85aaf245R325 in https://github.com/FaBrand/bazel/commit/6c779efa5ca911a402c0074cf1431f1655d26280

With that change the error did not occur anymore

**Comment by gregestren** [comment]
Note that those lines were refactored away in https://github.com/bazelbuild/bazel/commit/f5b9d930a93fadd40295ffe38dec2bf80569e38b#diff-875bd31f18543d83a185668a85aaf245. I'm not sure if that's in the release yet, but even a build with the new lines exhibits the bug.

It still makes sense to me why this bug would happen, but still doesn't make sense why that change would trigger it. I'm trying to see if I can comment out the equivalent code that you did.

**Comment by gregestren** [comment]
Long update at https://github.com/bazelbuild/bazel/issues/11078#issuecomment-621389631.

**Comment by gregestren** [comment]
I think if we could clone this logic:

https://github.com/bazelbuild/bazel/blob/587c73610064b3b163b680ae49675b8e6177c518/src/main/java/com/google/devtools/build/lib/skyframe/TargetPatternPhaseFunction.java#L359-L361

here:

https://github.com/bazelbuild/bazel/blob/c880d352a103d47d545eb6f826fb6a3f3e9d63b7/src/main/java/com/google/devtools/build/lib/query2/PostAnalysisQueryEnvironment.java#L157

we could fix this immediate bug.

But it doesn't handle the other filter flags in `LoadingOptions`. I don't know if there's a way to keep them consistent or if they're all handled ad hoc at their own bits of code.
