### ISSUE TITLE
version_file is not reflected in build artifact the way version is (pkg_deb)

### ISSUE THREAD

**Issue by martinmaly** [bazelbuild/bazel#1123]
pkg_deb's version_file is compelling because our build bot can generate it on the fly without modifying the BUILD file itself.

Unfortunately version specified in version_file attribute is not reflected in the generated .deb file name, unlike version.

We end up with file names such as

package__amd64.deb

(there are two consecutive underscores where version would be had we used version attribute)

**Comment by dslomov** [comment]
dmarting@ please check the triage

**Comment by damienmg** [comment]
Problem is the build artifact path is constructed as analysis time whereas the content of the file is just available for the execution phase. Therefore there is no way to fix that. I suggest renaming the file by your CI.

Closing as infeasible

**Comment by c4urself** [comment]
This is something that's not clearly documented, wased a few hours on this. Expectation is that you get `version` and `version_file` work the same way, they do not. `version_file` does set the correct version in the metadata of the Deb but doesn't use that version in the name of the file... https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/pkg/pkg.bzl#L243
