### ISSUE TITLE
copts not working.

### ISSUE THREAD

**Issue by H1Gdev** [bazelbuild/bazel#11238]
### Description of the problem / feature request:

I create project like [stage2](https://docs.bazel.build/versions/master/tutorial/cpp.html#specify-multiple-build-targets).
```
<PROJECT>
├── main
│   ├── BUILD
│   ├── hello-world.cc
│   ├── hello-greet.cc
│   └── include
│       └── hello-greet.h
└── WORKSPACE
```

`main/BUILD` file is the following.
```
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "hello-greet",
    srcs = ["hello-greet.cc"],
    hdrs = glob(["include/*.h"]),
    includes = ["include"], # (1)
    copts = ["-Imain/include"], # (2)
    copts = ["-Iinclude"], # (3)
)

cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
    deps = [
        ":hello-greet",
    ],
)
```

if use `includes` (1) then build OK.
But use `copts` (2), (3) then build Error.

- (2)
```
ERROR: /home/vagrant/works/test.bazel/main/BUILD:12:1: C++ compilation of rule '//main:hello-world' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 20 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
main/hello-world.cc:1:25: fatal error: hello-greet.h: No such file or directory
compilation terminated.
Target //main:hello-world failed to build
```

- (3)
```
ERROR: /home/vagrant/works/test.bazel/main/BUILD:12:1: C++ compilation of rule '//main:hello-world' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 20 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
main/hello-world.cc:1:25: fatal error: hello-greet.h: No such file or directory
compilation terminated.
Target //main:hello-world failed to build
```

I use bazel 3.0.0.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Just move [stage2](https://docs.bazel.build/versions/master/tutorial/cpp.html#specify-multiple-build-targets) header file as above.

### What operating system are you running Bazel on?

Ubuntu 16

### What's the output of `bazel info release`?

`release 3.0.0`

###  Have you found anything relevant by searching the web?

#1175

**Comment by aiuto** [comment]
That is working as intended.
`includes` forces the -I up to everything depending on your cc_library.
`copts` only acts locally, so the hello_world target does not use the -I

That said. My advice is to not write big C++ projects that depend on includes or copts. Use full paths to includes.   E.g. `#include "main/include/hello_greet.h"`.
When you rely on short #include file names and you have lots of dependencies you can run into confusion about which one wins. Consider what would happen if you depended on three libraries, where each had the include 'config.h', and each just `#include`d without a qualifying path. The order of the `-I`s created by `includes` could vary at different points in your build graph and lead to the wrong config.h being used. If you are lucky, that would just be a compile fail. If not, you could have the wrong constants defined.

**Comment by H1Gdev** [comment]
Thanks for your advice !

It succeeded with following `BUILD` file.
```
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "hello-greet",
    srcs = ["hello-greet.cc"],
    hdrs = glob(["include/*.h"]),
    copts = ["-Imain/include"],
)

cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
    copts = ["-Imain/include"],
    deps = [
        ":hello-greet",
    ],
)
```

I understand difference between `includes` and `copts`.
