### ISSUE TITLE
 /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by soporteCluster** [bazelbuild/bazel#11234]
Hi,
I have already compiled bazel. It finished apparently OK but when I run:
env - ldd /share/apps/bazel-0.28/output/bazel

It has some errors like:
/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /share/apps/bazel-0.28/output/bazel)

That is OK because this library is too old in that path. I have installed a new version in another path and I need a way to say to Bazel to find that library in another path.

I realized about that issue because I'm trying to compile TensorFlow and I have this problem with this library. 
Thanks

**Comment by aiuto** [comment]
It is strange that Bazel linked, but then the resulting binary can't find the right libstdc. There are so many things to look at.
Did you build on one machine and move to a different one with a different OS version?
Did you hand adjust the C++ toolchain, or let it auto-discover clang?
You say "installed a new version".  Was that done by installing a package, or manually copying a .so somewhere?  
Have you tried relinking Bazel after the new package was installed in /usr/lib64? You really can have libstdc++.so in a different place without providing a wrapper to set LD_LIBRARY_PATH.

**Comment by soporteCluster** [comment]
Thanks for the answer.
I have already found the problem. I had installed the new version of the library in another path and I had put it in the LD_LIBRARY_PATH. So with the command "env - " it won't pay attention to the environment variables so then when ldd take a look in LD_LIBRARY_PATH it will be empty. 
If I only run:
 ldd /share/apps/bazel-test/output/bazel
The output is correct:
	linux-vdso.so.1 =>  (0x00007ffcc55ce000)
	libstdc++.so.6 => /share/apps/gcc-6.3.0/lib64/libstdc++.so.6 (0x00007f8e4b8af000)
	libm.so.6 => /lib64/libm.so.6 (0x0000003002c00000)
	librt.so.1 => /lib64/librt.so.1 (0x0000003003c00000)
	libdl.so.2 => /lib64/libdl.so.2 (0x0000003003000000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003003400000)
	libgcc_s.so.1 => /share/apps/gcc-6.3.0/lib64/libgcc_s.so.1 (0x00007f8e4b67c000)
	libc.so.6 => /lib64/libc.so.6 (0x0000003002800000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003002400000)
Sorry for my mistake.
After that maybe the problem is with tensorflow because it appears that bazel is joining the variables in a good way.
I will close the comment.
Thanks for the answer again.
