### ISSUE TITLE
A-server.jar should not contain .java files

### ISSUE THREAD

**Issue by olekw** [bazelbuild/bazel#11239]
### Description of the problem / feature request:

The A-server.jar archive currently contains a number of .java files (listed below). This is [inefficient since the .java files are already available in the source tree](https://lintian.debian.org/tags/jar-contains-source.html).

### Feature requests: what underlying problem are you trying to solve with this feature?

The .java files should be removed from the .jar to reduce the .jar size.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Open A-server.jar file with an archive viewer and browse to the javax/annotation directory.

### What operating system are you running Bazel on?

Debian

### Any other information, logs, or outputs that you want to share?

List of included java files:
javax/annotation/CheckForNull.java
javax/annotation/CheckForSigned.java
javax/annotation/CheckReturnValue.java
javax/annotation/Detainted.java
javax/annotation/MatchesPattern.java
javax/annotation/Nonnegative.java
javax/annotation/Nonnull.java
javax/annotation/Nullable.java
javax/annotation/OverridingMethodsMustInvokeSuper.java
javax/annotation/ParametersAreNonnullByDefault.java
javax/annotation/ParametersAreNullableByDefault.java
javax/annotation/PropertyKey.java
javax/annotation/RegEx.java
javax/annotation/Signed.java
javax/annotation/Syntax.java
javax/annotation/Tainted.java
javax/annotation/Untainted.java
javax/annotation/WillClose.java
javax/annotation/WillCloseWhenClosed.java
javax/annotation/WillNotClose.java
javax/annotation/concurrent/GuardedBy.java
javax/annotation/concurrent/Immutable.java
javax/annotation/concurrent/NotThreadSafe.java
javax/annotation/concurrent/ThreadSafe.java
javax/annotation/meta/Exclusive.java
javax/annotation/meta/Exhaustive.java
javax/annotation/meta/TypeQualifier.java
javax/annotation/meta/TypeQualifierDefault.java
javax/annotation/meta/TypeQualifierNickname.java
javax/annotation/meta/TypeQualifierValidator.java
javax/annotation/meta/When.java

**Comment by ulfjack** [comment]
The checked-in jsr-305.jar contains the source files as well as the .class files. It should be straightforward to replace the jar file with one that doesn't contain the sources... except that jsr 305 is dormant, and I'm not sure where the official repository is if there even is one.

**Comment by ulfjack** [comment]
I know there's a copy at https://github.com/amaembo/jsr-305, but that's definitely not the source of the current jar.

**Comment by meteorcloudy** [comment]
I just check the `/usr/share/java/jsr305.jar` file installed by `apt-get install libjsr305-java` doesn't contain the .java files.

Our plan is to replace the jar files under third_party directory if it's available in debian. I guess once we do that, this won't be a problem?

**Comment by olekw** [comment]
Good point, @meteorcloudy . That Debian package lists [the following](https://code.google.com/archive/p/jsr-305/) as the source for that package but that source no longer seems to exist. For now, it seems like what @ulfjack suggested would work if you used the Debian .jar but it sounds like we'll eventually need to find where the new upstream is for this code...

**Comment by ulfjack** [comment]
It looks like Guava is planning to migrate off of jsr 305 (https://github.com/google/guava/issues/2960), and that's also an option. I think the primary use is the @Nullable annotation - maybe use Checker Framework's annotations? That could also help with static analysis.

**Comment by olekw** [comment]
That's great news, @ulfjack! Once Bazel starts using the new Guava it sounds like this problem may just go away.

**Comment by meisterT** [comment]
This seems to be fixed.
