### ISSUE TITLE
incompatible_string_replace_count

### ISSUE THREAD

**Issue by zegl** [bazelbuild/bazel#11244]
This flag changes the behaviour of the count argument to `string.replace()` to work as according to the [spec](https://github.com/bazelbuild/starlark/blob/master/spec.md#stringreplace), and the Go and Python implementations of Starlark.

**Flag:** --incompatible_string_replace_count

**Motivation:** #9181

**Added flag and changed behaviour:** #9228

**Migration:** If your rules depend on the previous behaviour of `string.replace()` when `count` is negative (nothing is replaced), set `count` to 0 or None to achieve the same result.

**Comment by zegl** [comment]
cc @laurentlb

**Comment by jin** [comment]
cc @brandjon
