### ISSUE TITLE
Bazel CI: Android Testing, rules_jvm_external, rules_nodejs broken in downstream

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#11247]
Downstream: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1476
Bazel Auto Sheriff: https://buildkite.com/bazel/bazel-auto-sheriff-face-with-cowboy-hat/builds/134
Culprit: 77502091f06b84054921f4eeee3f1d093dd8427d
/cc @lberki

**Comment by lberki** [comment]
Rolled back.
