### ISSUE TITLE
Clarify macOS installation instructions and de-duplicate homebrew formulas

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#11243]
There exist two Homebrew formulas for Bazel:

Default tap: https://github.com/Homebrew/homebrew-core/blob/master/Formula/bazel.rb
bazelbuild tap: https://github.com/bazelbuild/homebrew-tap/blob/master/Formula/bazel.rb

Note that the default formula has a dependency on Python 3.8 and Java 1.8:

https://github.com/Homebrew/homebrew-core/blob/ac3ab999a2be2871e256819138a0fabb8f1c6787/Formula/bazel.rb#L14-L16

```
  depends_on "python@3.8" => :build
  depends_on :java => "1.8"
  depends_on :macos => :yosemite
```

whereas the bazelbuild tap does not depend on Java nor Python (which makes sense, given that we have an embedded JDK to run Bazel, and bring in a remote JDK to run Java tools).

Our [official macOS instructions](https://docs.bazel.build/versions/master/install-os-x.html#install-on-mac-os-x-homebrew) recommend using the bazelbuild tap. But given that most macOS Homebrew users would instinctively type "brew install bazel" without reading the installation instructions, they would end up using the default tap, bringing a system dependency on Java 8 and Python, and not using the brew tap the Bazel team maintains at all. 

Quote from a [user](https://twitter.com/bernaferrari/status/1255340067440254977?s=20): "I never actually read (the installation instructions). When I needed Bazel I just did brew install bazel (because that's how 98% of things work) and it worked.. until I updated Java and formula broke."

Can we merge the bazelbuild tap into the default tap, and drop the dependency on Java 1.8? That'll allow us to stop maintaining a custom tap during the release process as well, and actually release Bazel on the "blessed" path.

**Comment by tetromino** [comment]
Homebrew by policy [doesn't allow pre-built binary blobs](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md#we-dont-like-binary-formulae) in their core tap (similar to Debian and other distros with a strongly free/libre philosophy). This means building Bazel from source, which means a build-time dependency on Python and a build- and run-time dependency on some version of the JDK. Therefore, I think the best fix we could do would be along the following lines:

* Send a PR to update the core tap to use a Homebrew-managed OpenJDK 11 (so users won't accidentally uninstall a systemwide Java version outside of Homebrew's control accidentally breaking Bazel).
* Document that the bazelbuild tap provides the binary package (supported by the Bazel team) and the Homebrew core tap builds from source (supported by the community).
* Add some process/documentation for the Bazel release manager to update the bazelbuild tap and to ping Homebrew core when Bazel is released.

**Comment by tetromino** [comment]
Blocked by #11399

**Comment by tetromino** [comment]
Sent a PR to homebrew-core: https://github.com/Homebrew/homebrew-core/pull/54712

**Comment by jin** [comment]
Thank you so much @tetromino!
