### ISSUE TITLE
PATH variable does not contain current directory element (".") on Windows

### ISSUE THREAD

**Issue by sunjayBhatia** [bazelbuild/bazel#11241]
### Description of the problem / feature request:

When running at least the `sh_test` rule on Windows, we get a different PATH variable structure that does not contain `.` for the current directory. On Linux we do have `.` as a leading PATH element so we are able to do thinks in an `sh_test` executed script like the following:

```
#!/bin/bash

cd somedir

foo.sh
```

instead of having to use `./foo.sh`. Other than that sort of trivial example, there could be other use more useful use cases for wanting the current directory on the PATH. The main point of the issue is the fact that the execution environment is different on Linux and Windows is surprising.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See a minimal repro here: https://github.com/greenhouse-org/bazel-issue-repro/tree/481218c7a30560f7c758379ff771cbd2de79081c/sh_test_env_path (note that the repro does take into account a strict action environment and also pulling the PATH from the user's environment, in both cases it seems Bazel is behaving differently between Windows and Linux)

### What operating system are you running Bazel on?

Windows and Linux

### What's the output of `bazel info release`?

`release 3.1.0`

### Any other information, logs, or outputs that you want to share?

- See reproduction linked above
- We had to work around this in Envoy to support Windows and Linux/macOS here: https://github.com/envoyproxy/envoy/pull/10977
- So far messing around with bash on Linux and MSYS2, I don't have evidence this is a behavior difference between the two, bash on Linux doesn't seem to ever add `.` to the PATH itself but I can't immediately find where that would be happening in Bazel

**Comment by meteorcloudy** [comment]
Thanks for reporting this bug.

On Linux, we add the "." into PATH in `test-setup.sh` [here](https://github.com/bazelbuild/bazel/blob/master/tools/test/test-setup.sh#L224). But on Windows, we have a native binary implemented as the [test wrapper](https://github.com/bazelbuild/bazel/tree/master/tools/test/windows) which doesn't do this.

This should be an easy fix. I'll find time to do it, but a PR is also welcome!
