### ISSUE TITLE
maven_jar does not check format of sha1 attribute

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#1125]
I made the following change to a WORKSPACE

 maven_jar(
   name = 'commons_lang',
-  artifact = 'org.apache.commons:commons-lang3:3.1',
+#  artifact = 'org.apache.commons:commons-lang3:3.1',
+  artifact = 'org.apache.commons:commons-lang3:3.0',
 #  sha1 = '905075e6c80f206bbe6cf1e809d2caa69f420c76',
 )

then bazel fetch:

 $ bazel fetch //...
ERROR: /home/hanwen/vc/gitiles/lib/BUILD:5:2: no such package '@commons_lang//jar': Downloaded file at /home/hanwen/.cache/bazel/_bazel_hanwen/02a2d1f21f16c0d4f7890328f21d4ade/external/commons_lang/org/apache/commons/commons-lang3/3.0/commons-lang3-3.0.jar has SHA-1 of 8873bd0bb5cb9ee37f1b04578eb7e26fcdd44cb0, does not match expected SHA-1 (905075e6c80f206bbe6cf1e809d2caa69f420c76) and referenced by '//lib:commons-lang'.

then update the workspace to use the new SHA-1, try again:

$ bazel fetch //...
ERROR: /home/hanwen/vc/gitiles/lib/BUILD:5:2: no such package '@commons_lang//jar': Downloaded file at /home/hanwen/.cache/bazel/_bazel_hanwen/02a2d1f21f16c0d4f7890328f21d4ade/external/commons_lang/org/apache/commons/commons-lang3/3.0/commons-lang3-3.0.jar has SHA-1 of 8873bd0bb5cb9ee37f1b04578eb7e26fcdd44cb0, does not match expected SHA-1 (8873bd0bb5cb9ee37f1b04578eb7e26fcdd44cb0,) and referenced by '//lib:commons-lang'.

note that the 2 hashes are now equal, but the error message is still emitted.

**Comment by hanwen** [comment]
Ah, there is a "," in one of my checksums.

Could the SHA1 attribute be checked to be hex only?

**Comment by kchodorow** [comment]
That seems reasonable, yeah.

**Comment by damienmg** [comment]
@kchodorow: don't you have fixed that already?

**Comment by kchodorow** [comment]
Just need to submit it, got sidetracked by the doc fixit.
