### ISSUE TITLE
Tracking Issue for exec_groups work

### ISSUE THREAD

**Issue by juliexxia** [bazelbuild/bazel#11250]
Already submitted (in chronological order)

make execGroups available to the RuleClass (like requiredToolchains) 693048da3632616560d3791eac128f49b529f378
Create UnloadedToolchainContexts for exec_groups 71a80dc40b1b81f0aeaed1f4e0a31d4a4d4444cf
Resolve toolchains and thread through to RuleContext b5f9d748dfef278ccc63087f3a662db8b2ebabe4
Check non-default UnloadedToolchainContexts for errors e7e1c2638e8099f1e5c23f0b442aea1b48d4e77e
Add ExecGroupCollection and ExecGroupContext objects to starlark 0a0a13bd4eaeefc3cdf17e8e34dcca4e1453a491
Allow rule writers to create exec_group related exec transitions via cfg(config.exec(...)) ed5d504ba73a56bbdf673ffa74b784abc20fa882

**Comment by juliexxia** [comment]
Execution groups are live! Documentation can be found here: https://docs.bazel.build/versions/master/exec-groups.html

You still need --experimental_exec_group=true to use starlark rules that create execution groups.

**Comment by sventiffe** [comment]
Is there still work open on this issue or can it be closed?

**Comment by juliexxia** [comment]
There is some ongoing work, mostly getting rid of the --experimental_exec_group flag and migrating tags over to using exec groups. I plan to use this as a place to occasionally update on working progress. Is that a reasonable plan or should I be doing that elsewhere? Will also document in documentation but this is more update-y.

**Comment by juliexxia** [comment]
(Context: I'm moving on from Bazel on friday and spending some time triaging all bugs assigned to me before unassigning myself)

There is ongoing work for deprecating execution info in tags but that's not strictly in scope of exec groups so I'll close this.
