### ISSUE TITLE
test PWD should be TEST_SRCDIR/{workspace_name} 

### ISSUE THREAD

**Issue by shahms** [bazelbuild/bazel#1126]
At the moment, the current working directory is just TEST_SRCDIR, but it should be TEST_SRCDIR/{workspace_name} (see #1124).

**Comment by kchodorow** [comment]
After further inspection, this is WAI.

**Comment by shahms** [comment]
Then this is inconsistent with internal blaze.

**Comment by shahms** [comment]
Upon further inspection, I'm not sure how our PWD may be getting confused in #1124 as a very simple test shows that you're correct.

$ cat testenv.sh 
#!/bin/bash
echo "$PWD"
echo "$TEST_SRCDIR"
exit 1
$ bazel test //:testenv
$ bazel test --test_output=streamed //:testenv 
WARNING: Streamed test output requested so all tests will be run locally, without sharding, one at a time.
INFO: Found 1 test target...
.../testenv/bazel-out/local-fastbuild/bin/testenv.runfiles/WORKSPACE_NAME
.../testenv/bazel-out/local-fastbuild/bin/testenv.runfiles


Apologies for the distraction.

**Comment by shahms** [comment]
The bazel documentation should be updated, though :-)

**Comment by kchodorow** [comment]
Are you requesting more docs about it, or is the documentation incorrect somewhere?

**Comment by shahms** [comment]
The Test Encyclopedia is incorrect, both in the table and below:

PWD	$TEST_SRCDIR
The initial working directory shall be $TEST_SRCDIR.

**Comment by kchodorow** [comment]
Ah, quite.
