### ISSUE TITLE
Support disabling bitcode mode for iOS apps bundling a watchOS app

### ISSUE THREAD

**Issue by thii** [bazelbuild/bazel#11278]
### Description of the problem / feature request:

Our iOS app bundles a watchOS app. We're currently not building the iOS app with bitcode, but embedding bitcode to the watchOS app binary is mandatory if you want to submit the app to the App Store. There's currently no way to disable generating bitcode for iOS app only.

Feature request: Add support for only generating bitcode for watchOS app.

### What underlying problem are you trying to solve with this feature?

Unable to submit an iOS app without bitcode to the App Store if it has a watchOS app.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build an iOS app with a bundled watchOS app with `--apple_bitcode=embedded` flag produces an app that has bitcode embedded for both iOS app and watchOS app.

### What operating system are you running Bazel on?

macOS Catalina 10.15.4 (19E287)
### What's the output of `bazel info release`?

release 3.1.0

###  Have you found anything relevant by searching the web?

Only found https://github.com/bazelbuild/bazel/pull/7356 that added support bitcode for Apple platforms, but it forces bitcode for all platforms that you build for.

**Comment by susinmotion** [comment]
@trybka, is this in your wheelhouse?

**Comment by trybka** [comment]
@susinmotion sure, I can take a look. If this needs corresponding bazel changes, I'll ping it back, but I suspect this can be done in the crosstool alone.

**Comment by susinmotion** [comment]
Wonderful, thank you!

**Comment by thii** [comment]
@trybka Gently ping. Or maybe could you give some hints on this should be addressed?

**Comment by trybka** [comment]
Can you see https://bazel-review.googlesource.com/c/bazel/+/135960 ? 

Try patching it in and building with `--features=omit_bitcode_for_ios_arm64` (replace ios_arm64 with whichever CPU(s) you're targeting, you can set it multiple times)

**Comment by thii** [comment]
I got an error `MyFramework/MyFramework.__internal__.apple_binary.bcsymbolmap' was not created` while trying to build an app that has a dynamic framework.

**Comment by thii** [comment]
`.bcsymbolmap` files are still declared as action outputs. I'm guessing this might need corresponding changes from Bazel, and probably rules_swift too.

**Comment by trybka** [comment]
OK, let's take a step back then, and reconsider how this should work.

How is your project set up--rules / dependencies, etc.?

Do you just have an ios_application with a watchos_application set? 

Since watchos apps must have bitcode, as you say, perhaps we can just force that to happen independent of the bitcode/embedded mode for the outside application...

**Comment by thii** [comment]
I have a pretty typical setup: an ios_application with some ios_extensions, an ios_framework (used only by ios_exensions), and a watchos_application set. Most library targets are objc_library and swift_library, some are cc_library.

Yeah, I'm thinking of a new bitcode option just for watchos, maybe it's too much?

**Comment by thii** [comment]
@trybka Friendly ping — any updates? I could try to take a stab at it if you point me in the right direction.

**Comment by trybka** [comment]
No updates, but here's what I'm thinking needs to happen: 
In https://github.com/bazelbuild/rules_apple/blob/master/apple/internal/transition_support.bzl 

If the platform is for watch, then the transition should set the related bitcode embedded flags.

**Comment by thii** [comment]
Thanks.

> Since watchos apps must have bitcode

Just to clarify, watchos apps don't have to have bitcode, it's only required for the builds you upload to App Store Connect.

**Comment by allevato** [comment]
This can be closed now by https://github.com/bazelbuild/bazel/commit/a4acc1b2e44b747572a1b174591c6c5d60844693; Bitcode can be restricted to a single platform by passing that platform name to a new `key=value` form of the flag: `--apple_bitcode=watchos=embedded`. (The old behavior still remains if the platform name is omitted.)
