### ISSUE TITLE
Update error prone version to 2.4.0

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#11272]
Last EP upgrade attempt to 2.3.3 was reverted to `RefersToDaggerCodegen` breakage in rules_kotlin: [1],[2].

This is a feature request to update EP version to 2.3.4.

It turns out, that with EP 2.3.4 there are at least two breakages:

- rule_closure: [3]
- rules_kotlin: [4]

[1] bazelbuild/bazel#10023
[2] bazelbuild/bazel@d990746
[3] https://github.com/bazelbuild/rules_closure/issues/483
[4] https://github.com/bazelbuild/rules_kotlin/issues/321

**Comment by davido** [comment]
Fix for rules_kotlin is here: [1]. Fix for rules_closure is here: [2].

[1] https://github.com/bazelbuild/rules_kotlin/pull/320
[2] https://github.com/bazelbuild/rules_closure/pull/484

**Comment by meisterT** [comment]
For feature requests like this it would be nice to include a reason for the upgrade.

**Comment by davido** [comment]
> For feature requests like this it would be nice to include a reason for the upgrade.

Latest EP releases added bunch of new and shiny bug pattern check to increase code quality. Bazel eco-system would like to benefit from these enhancement.

**Comment by davido** [comment]
Upcoming EP version 2.4.0 is added the compatibility to JDK 14: https://github.com/google/error-prone/issues/1639.

**Comment by davido** [comment]
3.4.1 was released with EP 2.4.0 included.
