### ISSUE TITLE
Bazel incorrectly sends SIGKILL to process group when Ctrl-C is pressed

### ISSUE THREAD

**Issue by alanfalloon** [bazelbuild/bazel#11284]
### Description of the problem:

When a user presses Ctrl-C while a build is running, the process-wrapper handles the SIGTERM by sending a SIGKILL to the process group of its children

https://github.com/bazelbuild/bazel/blob/c95d27a32dfc5487ece9a88d9167d6a8f70b0ee8/src/main/tools/process-wrapper-legacy.cc#L108-L110

https://github.com/bazelbuild/bazel/blob/d002e450a8d23f84a22345e7c41599bbadfb5d1a/src/main/tools/process-tools.cc#L83-L97

This makes it impossible for actions to clean up after themselves. It also leaves children running if they were started in a fresh process group.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I provided a demonstration example [afalloon/bazel-ctrl-c-demo](https://github.com/alanfalloon/bazel-ctrl-c-demo). The `README.md` has instructions.

### What operating system are you running Bazel on?

We noticed the issue on macOS, but we use both macOS and Linux.

### What's the output of `bazel info release`?

```release 3.0.0```

###  Have you found anything relevant by searching the web?

This is perhaps related to #9285 and related to #3519 but that was only fixed for `bazel run` and not any other cases.

**Comment by jmmv** [comment]
As of 2bb3b73d5739fd9cae152a3626b4a6c203d8cef6, you can tag actions with `supports-graceful-termination` to request that a `SIGTERM` be sent instead.
