### ISSUE TITLE
System.exit in ManifestMergerAction killing persistent worker

### ISSUE THREAD

**Issue by justhecuke-zz** [bazelbuild/bazel#11285]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

In the ResourceProcessorBusyBox, it calls into ManifestMergerAction which has a System.exit that causes an improper exit of the worker without an indication of what went wrong.

### Feature requests: what underlying problem are you trying to solve with this feature?

N/A

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Throw a AndroidManifestProcessor.ManifestProcessingException in ManifestMergerAction's main try block to hit the System.exit call.

Do a build (after recompiling Bazel and hooking things up since this is a non-trivial insertion), and note that you get a build error `com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.` and no notice about exception that was thrown or any relevant error logs/prints that are related to the actual manifest merger error.

### What operating system are you running Bazel on?

Mac OS and Ubuntu.

### What's the output of `bazel info release`?

release 3.1.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git@github.com:lyft/instant-android.git
2c28d9de9e7dc6f6000314fa1c3ee0a2a537e66a
612664443af62bdb991bc76b87ec388af7e99242

###  Have you found anything relevant by searching the web?

No. This seems to be something that others either do not hit or do not report. It also looks similar to other worker-related issues and so can be difficult to differentiate from them.

### Any other information, logs, or outputs that you want to share?

No. The problem is that this lacks the outputs that are relevant to the error and instead gives a generic worker problem rather than the specific exception that we are concerned with.

**Comment by meisterT** [comment]
cc @larsrc-google

**Comment by larsrc-google** [comment]
Indeed. I see that also in a couple of other main() methods called from ResourceProcessorBusyBox. They should not call System.exit(), but ResourceProcessorBusyBox also ought not to call main(), but a separate method that doesn't think it's called from the command line.

ResourceProcessorBusyBox could instead set up a SecurityManager to prevent System.exit from actually exiting.
