### ISSUE TITLE
bazel run bash completion improvement

### ISSUE THREAD

**Issue by zimbatm** [bazelbuild/bazel#11292]
### Description of the problem / feature request:

When running a command like this:
```
$ bazel run //foo -- -i /home/zimbatm/bar<tab>
```
The bash-completion is not able to complete the path of the command. It would be nice if by default it would assume that extra commands could be paths.

### Feature requests: what underlying problem are you trying to solve with this feature?

Making it easier to use bazel in bash with the completions enabled.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I think that the description already does that.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> release 2.1.0- (@non-git)

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

This is on a private repository.

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/9358 might be related to this issue?

### Any other information, logs, or outputs that you want to share?
No

**Comment by zimbatm** [comment]
What can I do to help move this forward? :-)

**Comment by philwo** [comment]
> What can I do to help move this forward? :-)

Feel free to send a PR that improves this. :)
