### ISSUE TITLE
Documentation for Installing Bazel on Windows

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#11318]
https://docs.bazel.build/versions/3.1.0/install-windows.html

The page could be improved:
* Step 1. Make full sentences (the text is hard to understand). It's unclear what is "Developer Mode" and how to enable or disable it.
* Step 4. It's unclear what are the action items.
* Step 6. Maybe suggest running `bazel version` to check it's working?
* "Java SE Development Kit 10". Shall we add a link?

**Comment by aiuto** [comment]
Must coordinate with #11320

**Comment by sudoforge** [comment]
We should also consider #10520, which requests making Bazelisk the default front-end wrapper. I personally am not sure why we wouldn't want to do this; maintainer insight would be helpful.
