### ISSUE TITLE
Bazel coverage fails to compile target [Java + AspectJ]

### ISSUE THREAD

**Issue by shail-162** [bazelbuild/bazel#11327]
### Description of the problem / feature request:

> 

### Feature requests: what underlying problem are you trying to solve with this feature?

> Trying to run code coverage with bazel for monolithic project.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> bazel coverage TestCase
  you should have multiple modules in your project and Aspects defined as well.

### What operating system are you running Bazel on?

>  Mac and Ubuntu

### What's the output of `bazel info release`?

> release 1.2.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Its internal git repository

###  Have you found anything relevant by searching the web?

> No luck :-(
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> bazel test works just fine, i am getting error while running coverage. My guess it is giving problem while instrumentation of aspects which belongs to some other modules. 

Here are some log snippets:
ERROR: BUILD:28:1: Running ajc for xxx failed (Alarm clock): aspectj-XXX.sh failed: error executing command 
Compile : XXXAspect.java [error] Type referred to is not an annotation type: YYY
Compile :  
Compile : XXXAspect.java [error] formal unbound in pointcut 
Compile :  
Compile : XXXAspect.java [warning] no match for this type name: facadeYamlMethod [Xlint:invalidAbsoluteTypeName]
Compile :  
Compile : XXXAspect.java [error] bad parameter to pointcut reference
Compile :  
Compile : XXXAspect.java [error] formal unbound in pointcut 
Compile :  
Compile : XXXAspect.java [warning] no match for this type name: XXXAspect [Xlint:invalidAbsoluteTypeName]
Compile :  
Compile : XXXAspect.java [error] the parameter facadeYamlMethod is not bound in [all branches of] pointcut
Compile :  
Compile : XXXAspect.java [error] the parameter pjp is not bound in [all branches of] pointcut
>
> If the files are large, upload as attachment or provide link.

**Comment by lberki** [comment]
I don't think we'll be able to do much with this without a reproduction. Please re-open with one if this is still an issue and apologies for not tending to this bug for a long time.
