### ISSUE TITLE
Bazel build encountered error loading package PROXY ISSUE

### ISSUE THREAD

**Issue by louiselumapas** [bazelbuild/bazel#11332]
### Problem
I am trying to build tensorflow cpu(1.14) by source by using bazel (0.24.1) but i get this error once i run the command:  bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

```  
ERROR: error loading package '': Encountered error while reading extension file 'swift/repositories.bzl': no such package '@build_bazel_rules_swift//swift': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_swift/releases/download/0.9.0/rules_swift.0.9.0.tar.gz] to /home/domingo_cm/.cache/bazel/_bazel_domingo_cm/f08b2f8b39197d5a57f7b557c17f0caf/external/build_bazel_rules_swift/rules_swift.0.9.0.tar.gz: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
ERROR: error loading package '': Encountered error while reading extension file 'swift/repositories.bzl': no such package '@build_bazel_rules_swift//swift': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_swift/releases/download/0.9.0/rules_swift.0.9.0.tar.gz] to /home/domingo_cm/.cache/bazel/_bazel_domingo_cm/f08b2f8b39197d5a57f7b557c17f0caf/external/build_bazel_rules_swift/rules_swift.0.9.0.tar.gz: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
INFO: Elapsed time: 15.625s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
 ```
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I tried exporting my http_proxy and https_proxy(tried both uppercase and lowercase)
export http_proxy=http://[user]:[password]@[server]:[port]
export https_proxy=http://[user]:[password]@[server]:[port]

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

release 0.24.1

### Any other information, logs, or outputs that you want to share?
I'm running behind a corporate proxy network

**Comment by aiuto** [comment]
Have you tried a more recent version of Bazel? 0.24 is about a year old.

**Comment by louiselumapas** [comment]
Yes, i tried the latest. Same thing still happens. I used the 0.24.1 version since i’m following the bazel version used in tensorflow 1.14
![98ECB78C-41FE-4505-95EC-096287D7D5B9](https://user-images.githubusercontent.com/22358679/81488221-a9392400-9298-11ea-800d-507ae372155d.png)

Source of picture: https://www.tensorflow.org/install/source

**Comment by aiuto** [comment]
I think you'll get a better traction on a tensorflow list. If they recommended this version combination, it probably works, but there is little help the bazel team can offer for anything pre 1.0.

**Comment by louiselumapas** [comment]
But isnt just this a proxy issue?? Isnt there a way to build by if under a proxy network?? Because this would not have been an issue if im not under a corporate network.

**Comment by louiselumapas** [comment]
@damienmg maybe you have a solution?

**Comment by damienmg** [comment]
Sorry I no longer work on Bazel, and this is a pretty old version of Bazel.
I remember correctly there was no good proxy support at the time and the
solution was to download the repository cache and reuse it.

**Comment by aiuto** [comment]
A quick search finds this.
https://docs.bazel.build/versions/master/external.html#using-proxies
and this
https://stackoverflow.com/questions/52311486/bazel-build-behind-proxy

In both cases, the answer is to set the proxy information in the environment.

Personally, I think http download should be ripped out of the bazel binary and provided in a module that is much easier to rev and for an organization to replace entirely.

**Comment by hicksjoseph** [comment]
Is there a reason that you need to build this particular version of Tensorflow?

**Comment by louiselumapas** [comment]
@hicksjoseph I am trying to build tensorflow(1.14) by source and based on the official site of tensorflow based [here](https://www.tensorflow.org/install/source#tested_build_configurations) , i should use this specific version of bazel 0.24.1. I firstly tried the latest version of bazel 3.1.0 but it seems to have errors so i was thinking maybe the latest version has incompatible issues with the TF i'm using, thats why i decided using this specific version as this was officially tested by the tensorflow

**Comment by aiuto** [comment]
Did you try HTTP_PROXY in upper case?

**Comment by philwo** [comment]
It seems like Bazel 0.24.1 just does not support the kind of HTTP proxy authentication you need - sorry, but there's no way this will be fixed, as the version is just too old. Please download the required files manually, place them into a folder and use `--distdir` to tell Bazel it should pick them from there instead of downloading them from the internet.

**Comment by MaoJianwei** [comment]
here, it works for me.

cd ../zulu11.37.17-ca-jdk11.0.6-linux_x64/bin/
keytool -import -noprompt -trustcacerts -alias h -file a.crt -keystore ../lib/security/cacerts -storepass changeit
keytool -import -noprompt -trustcacerts -alias h2 -file /usr/local/share/ca-certificates/web.crt -cacerts -storepass changeit
bazel --host_jvm_args "-Djavax.net.ssl.trustStore=/root/mao/zulu11.37.17-ca-jdk11.0.6-linux_x64/lib/security/cacerts" build onos --action_env=HTTP_PROXY=$HTTP_PROXY
