### ISSUE TITLE
Documentation issue: Migrate information on generating dep graph images

### ISSUE THREAD

**Issue by floriographygoth** [bazelbuild/bazel#11342]
Documentation URL: https://blog.bazel.build/2015/06/17/visualize-your-build.html

There is good information in the "Generating dep graph images" blog, but it isn't in the canonical docs.

**Comment by haxorz** [comment]
What about https://docs.bazel.build/versions/3.4.0/query-how-to.html#Tracing_the_Dependency_Chain_bet ?
