### ISSUE TITLE
`ln` call fails with "operation not permitted" during `bazel test`

### ISSUE THREAD

**Issue by iuliand-db** [bazelbuild/bazel#11349]
### Description of the problem / feature request:

`bazel test` fails on Mac OS Catalina with "operation not permitted" when running `ln`:

```
INFO: From Testing //repl:org.apache.spark.repl.SingletonReplSuite:
==================== Test output for //repl:org.apache.spark.repl.SingletonReplSuite:
ln: /Users/iulian.dragos/.cache/bazel/_bazel_iulian.dragos/3f8a8ed88c7af0f90b1b2a7ead61bb31/sandbox/darwin-sandbox/1/execroot/runtime/bazel-out/darwin-fastbuild/bin/repl/org.apache.spark.repl.SingletonReplSuite.runfiles/runtime/tmp.Tc91VdbZ/librepl_test_resources-0.jar: Operation not permitted
================================================================================
```

I managed to intercept the `ln` call and replace it with a bash script that prints its arguments and waits. I can run the same `ln` command at that point in time and it succeeds.

#### Workaround:

Adding `--spawn_strategy=local ` gets around the issue.

### What operating system are you running Bazel on?

Mac OS 10.15 (Catalina)

### What's the output of `bazel info release`?

tls-bazel-0.25.2

###  Have you found anything relevant by searching the web?

A few other places where the error appeared, but none involving `ln` in the test step.

**Comment by jiridanek** [comment]
I had the same experience with `ps` command (in otherwise unrelated issue ticket  #11325). I wanted to have a fancy script which starts process on background, then checks the process is still running after one second. But the darwin-sandbox said "no".

```
+ ps -p 1217
/private/var/tmp/_bazel_cloud-user/e373d86e469780d831c8413f2f91c1bf/sandbox/darwin-sandbox/23/execroot/__main__/bazel-out/darwin-fastbuild/bin/listen_8902_inside_should_succeed.runfiles/__main__/listen_8902_inside_should_succeed: line 8: /bin/ps: Operation not permitted
```

**Comment by jmmv** [comment]
The `ps` issue is actually #7448.

As for the `ln` issue... we'll need more details to diagnose it. Can you run the build with `--sandbox_debug --verbose_failures`? When it fails, copy/paste the failing command (it'll be a very long command that `cd`s into a `darwin-sandbox` directory and then calls `sandbox-exec` with the actual thing to run) and try to run it by hand. Then please share the details.

**Comment by iuliand-db** [comment]
Hm, not sure why, but nothing else shows up, in particular there's no long command:

```
$ bazel test --verbose_failures --sandbox_debug //repl:org.apache.spark.repl.SingletonReplSuite
Using Bazel Cache
WARNING: Duplicate rc file: /Users/iulian.dragos/runtime/.bazelrc is read multiple times, most recently imported from /Users/iulian.dragos/runtime/.localrc
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [externalCache, buildCache]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Invocation ID: 9b227371-fb14-4cde-8f6b-c501ad9dca2f
INFO: Analyzed target //repl:org.apache.spark.repl.SingletonReplSuite (595 packages loaded, 7977 targets configured).
INFO: Found 1 test target...
FAIL: //repl:org.apache.spark.repl.SingletonReplSuite (see /Users/iulian.dragos/.cache/bazel/_bazel_iulian.dragos/3f8a8ed88c7af0f90b1b2a7ead61bb31/execroot/runtime/bazel-out/darwin-fastbuild/testlogs/repl/org.apache.spark.repl.SingletonReplSuite/test.log)
INFO: From Testing //repl:org.apache.spark.repl.SingletonReplSuite:
==================== Test output for //repl:org.apache.spark.repl.SingletonReplSuite:
ln: /Users/iulian.dragos/.cache/bazel/_bazel_iulian.dragos/3f8a8ed88c7af0f90b1b2a7ead61bb31/sandbox/darwin-sandbox/1/execroot/runtime/bazel-out/darwin-fastbuild/bin/repl/org.apache.spark.repl.SingletonReplSuite.runfiles/runtime/tmp.aqeg2DnA/librepl_test_resources-0.jar: Operation not permitted
================================================================================
Target //repl:org.apache.spark.repl.SingletonReplSuite up-to-date:
  bazel-bin/repl/org.apache.spark.repl.SingletonReplSuite
INFO: Elapsed time: 13.270s, Critical Path: 4.41s
INFO: 2 processes: 2 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//repl:org.apache.spark.repl.SingletonReplSuite                          FAILED in 0.1s
  /Users/iulian.dragos/.cache/bazel/_bazel_iulian.dragos/3f8a8ed88c7af0f90b1b2a7ead61bb31/execroot/runtime/bazel-out/darwin-fastbuild/testlogs/repl/org.apache.spark.repl.SingletonReplSuite/test.log

INFO: Build completed, 1 test FAILED, 2 total actions
```

**Comment by jiridanek** [comment]
Crazy idea, what if `ln` is natural logarithm, given we are talking about Spark, and not the ln utility? Probably not, but just a thought.

Can you post the ln command that is failing? what is the input and what is the ouput? Maybe it is trying to create the link somewhere it is not allowed to write.

`/Users/iulian.dragos/.cache/bazel/_bazel_iulian.dragos/3f8a8ed88c7af0f90b1b2a7ead61bb31/sandbox/darwin-sandbox/1/execroot/runtime/bazel-out/darwin-fastbuild/bin/repl/org.apache.spark.repl.SingletonReplSuite.runfiles/runtime/tmp.Tc91VdbZ/librepl_test_resources-0.jar` is source or destination of the `ln` command?

**Comment by jmmv** [comment]
That looks like the destination based on the `tmp.XXXXXXXX` path component... and the fact that this appears somewhere under runfiles looks very suspicious. So I suspect whatever tool/rule you are running is just not behaving well, and the sandbox is actually highlighting that :-P

**Comment by dragos** [comment]
> Crazy idea, what if ln is natural logarithm, given we are talking about Spark, and not the ln utility? Probably not, but just a thought.

I'm not sure I follow, isn't Bazel cleaning up the PATH variable anyway, so everything is sandboxed?

> Can you post the ln command that is failing? what is the input and what is the ouput? Maybe it is trying to create the link somewhere it is not allowed to write.

I'd love to but the only way I know how to do it is by replacing the `ln` executable, as I can't make Bazel print it.

>That looks like the destination based on the tmp.XXXXXXXX path component... and the fact that this appears somewhere under runfiles looks very suspicious. So I suspect whatever tool/rule you are running is just not behaving well, and the sandbox is actually highlighting that :-P

Why is it suspicious? Any help highlighting what's wrong with the rule would be already a good step forward. But I do have to mention that this same rule is building fine for 150+ other engineers, so there must be more than this to the story.

**Comment by jiridanek** [comment]
> > Crazy idea, what if ln is natural logarithm, given we are talking about Spark, and not the ln utility? Probably not, but just a thought.
> 
> I'm not sure I follow, isn't Bazel cleaning up the PATH variable anyway, so everything is sandboxed?

Sorry, that was not a helpful thing to say. BTW, whether PATH is purged or not depends on the specific rule. There is `ctx.actions.run_shell(use_default_shell_env=True)` which uses the full users env, including PATH. Again, sorry for unhelpful comment on my side.

> > Can you post the ln command that is failing? what is the input and what is the ouput? Maybe it is trying to create the link somewhere it is not allowed to write.
> 
> I'd love to but the only way I know how to do it is by replacing the `ln` executable, as I can't make Bazel print it.

Whatever way you can get the information is good, I think ;-P

I am guessing that `--verbose_failures` is not giving any additional output because what's happening is not seen as a failure. Shell has this interesting feature, that result of a sequence of commands is the result of the last command. Therefore, `cat IDoNotExist; echo hello` is considered, taken together, as success in shell (value of `$?` is 0), and therefore it would be reported successful to Bazel, despite the error output from first command.

In shell scripts, I tend to always begin with [`set -Eeuxo pipefail`](https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/). In Bazel, maybe put `&&` between your commands. Not sure what the practice is there.

> > That looks like the destination based on the tmp.XXXXXXXX path component... and the fact that this appears somewhere under runfiles looks very suspicious. So I suspect whatever tool/rule you are running is just not behaving well, and the sandbox is actually highlighting that :-P
> 
> Why is it suspicious? Any help highlighting what's wrong with the rule would be already a good step forward. But I do have to mention that this same rule is building fine for 150+ other engineers, so there must be more than this to the story.

Maybe they all turn off sandbox in their .bazelrc? :DDD

Details on sandboxing are not documented all that well (#11343). It might be helpful to just dump your current sandboxing config, to see if the `ln` is not trying to write somewhere the sandbox does not allow. From https://jmmv.dev/2019/11/macos-sandbox-exec.html (I don't know how to dump that config myself):

```
(version 1)
(debug deny)
(allow default)
(deny network*)
(allow network* (local ip "localhost:*"))
(allow network* (remote ip "localhost:*"))
(allow network* (remote unix-socket))
(deny file-write*)
(allow file-write*
    (subpath "/dev")
    (subpath "/private/var/tmp/_bazel_cooluser/2187421153de0d0eb425e00ad6f725cb/sandbox/darwin-sandbox/1/execroot/__main__")
    (subpath "/private/var/folders/p4/px0ds0qs4w58bk9fjp34q32h0000gn/C")
    (subpath "/private/var/tmp")
    (subpath "/Users/cooluser/Library/Logs")
    (subpath "/Users/cooluser/Library/Developer")
    (subpath "/private/var/folders/p4/px0ds0qs4w58bk9fjp34q32h0000gn/T")
    (subpath "/private/tmp")
)
```

In the `allow file-write` whitelist, there is nothing like your path, `[...]/execroot/runtime/bazel-out/[...]`.

Do you have some other tests that use the rule, that are passing for you in sandbox? If so, what's different? Can you put `set -x` at the beginning of the shell script containing that `ls`? That will print out commands as they are being executed.

**Comment by jiridanek** [comment]
Found it. You want to add `-s`, to get all executed commands printed, as per https://stackoverflow.com/a/50299772/1047788 and #10068.

**Comment by iuliand-db** [comment]
So, intercepting the ln call, here's what pstree shows:

```
-+= 00001 root /sbin/launchd
 \-+= 29857 iulian.dragos bazel(runtime) -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/Users/iulian.dragos/.cache/bazel/_bazel_iulian.dragos/3f8a8ed88c7af0f90b1b2a7ead61bb31 -XX:+UseParallelOldGC --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED -Xverify:none -Djava.util.logging.config.file=/Users/iulian.dragos/.cache/bazel/_bazel_iulian.dragos/3f8a8ed88c7af0f90b1b2a7ead61bb31/javalog.properties -Dcom.google.devtools.build.lib.util.LogHandlerQuerier.class=com.google.devtools.build.lib.util.SimpleLogHandler$HandlerQuerier -XX:-MaxFDLimit -Djava.library.path=/var/tmp/_bazel_iulian.dragos/install/e3f14e2a95a88014d134936691755b43/_embedded_binaries/embedded_tools/jdk/lib/jli:/var/tmp/_bazel_iulian.dragos/install/e3f14e2a95a88014d134936691755b43/_embedded_binaries/embedded_tools/jdk/lib:/var/tmp/_bazel_iulian.dragos/install/e3f14e2a95a88014d134936691755b43/_embedded_binaries/embedded_tools/jdk/lib/server:/var/tmp/_bazel_iulian.dragos/install/e3f14e2a95a88014d134936691755b43/_embedded_binaries/embedded_tools/tools/objc:/var/tmp/_bazel_iulian.dragos/install/e3f14e2a95a88014d134936691755b43/_embedded_binaries/ -Dfile.encoding=ISO-8859-1 -Dbazel.DigestFunction=SHA1 -Dbazel.DigestFunction=SHA1 -jar /var/tmp/_bazel_iulian.dragos/install/e3f14e2a95a88014d134936691755b43/_embedded_binaries/A-server.jar --max_idle_secs=10800 --shutdown_on_low_sys_mem=0 --connect_timeout_secs=30 --output_user_root=/var/tmp/_bazel_iulian.dragos --install_base=/var/tmp/_bazel_iulian.dragos/install/e3f14e2a95a88014d134936691755b43 --install_md5=e3f14e2a95a88014d134936691755b43 --output_base=/Users/iulian.dragos/.cache/bazel/_bazel_iulian.dragos/3f8a8ed88c7af0f90b1b2a7ead61bb31 --workspace_directory=/Users/iulian.dragos/runtime --default_system_javabase=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home --deep_execroot --expand_configs_in_place --idle_server_tasks --noexperimental_oom_more_eagerly --experimental_oom_more_eagerly_threshold=100 --write_command_log --watchfs --nofatal_event_bus_exceptions --client_debug=false --host_jvm_args=-Dbazel.DigestFunction=SHA1 --host_jvm_args=-Dbazel.DigestFunction=SHA1 --product_name=Bazel --noincompatible_windows_style_arg_escaping --option_sources=host_Ujvm_Uargs:/Users/iulian.dragos/runtime/.bazelrc:watchfs:/Users/iulian.dragos/runtime/.bazelrc
   \-+- 29868 iulian.dragos /var/tmp/_bazel_iulian.dragos/install/e3f14e2a95a88014d134936691755b43/_embedded_binaries/process-wrapper --timeout=2700 --kill_delay=15 external/bazel_tools/tools/test/test-setup.sh repl/org.apache.spark.repl.SingletonReplSuite
     \-+= 29869 iulian.dragos /bin/bash external/bazel_tools/tools/test/test-setup.sh repl/org.apache.spark.repl.SingletonReplSuite
       \-+- 29881 iulian.dragos /bin/bash /Users/iulian.dragos/.cache/bazel/_bazel_iulian.dragos/3f8a8ed88c7af0f90b1b2a7ead61bb31/sandbox/darwin-sandbox/1/execroot/runtime/bazel-out/darwin-fastbuild/bin/repl/org.apache.spark.repl.SingletonReplSuite.runfiles/runtime/repl/org.apache.spark.repl.SingletonReplSuite
         \-+- 29884 iulian.dragos /bin/bash /Users/iulian.dragos/bin/ln repl/librepl_test_resources.jar /Users/iulian.dragos/.cache/bazel/_bazel_iulian.dragos/3f8a8ed88c7af0f90b1b2a7ead61bb31/sandbox/darwin-sandbox/1/execroot/runtime/bazel-out/darwin-fastbuild/bin/repl/org.apache.spark.repl.SingletonReplSuite.runfiles/runtime/tmp.p6VOiw2j/librepl_test_resources-0.jar
           \--- 29885 iulian.dragos sleep 100
```

And bazel -s :

```
INFO: Found 1 test target...
SUBCOMMAND: # //repl:org.apache.spark.repl.SingletonReplSuite [action 'Testing //repl:org.apache.spark.repl.SingletonReplSuite']
(cd /Users/iulian.dragos/.cache/bazel/_bazel_iulian.dragos/3f8a8ed88c7af0f90b1b2a7ead61bb31/execroot/runtime && \
  exec env - \
    EXPERIMENTAL_SPLIT_XML_GENERATION=1 \
    JAVA_RUNFILES=bazel-out/darwin-fastbuild/bin/repl/org.apache.spark.repl.SingletonReplSuite.runfiles \
    PATH=/bin:/usr/bin:/usr/local/bin \
    PYTHON_RUNFILES=bazel-out/darwin-fastbuild/bin/repl/org.apache.spark.repl.SingletonReplSuite.runfiles \
    RUNFILES_DIR=bazel-out/darwin-fastbuild/bin/repl/org.apache.spark.repl.SingletonReplSuite.runfiles \
    RUN_UNDER_RUNFILES=1 \
    TEST_BINARY=repl/org.apache.spark.repl.SingletonReplSuite \
    TEST_INFRASTRUCTURE_FAILURE_FILE=bazel-out/darwin-fastbuild/testlogs/repl/org.apache.spark.repl.SingletonReplSuite/test.infrastructure_failure \
    TEST_LOGSPLITTER_OUTPUT_FILE=bazel-out/darwin-fastbuild/testlogs/repl/org.apache.spark.repl.SingletonReplSuite/test.raw_splitlogs/test.splitlogs \
    TEST_PREMATURE_EXIT_FILE=bazel-out/darwin-fastbuild/testlogs/repl/org.apache.spark.repl.SingletonReplSuite/test.exited_prematurely \
    TEST_SIZE=large \
    TEST_SRCDIR=bazel-out/darwin-fastbuild/bin/repl/org.apache.spark.repl.SingletonReplSuite.runfiles \
    TEST_TARGET=//repl:org.apache.spark.repl.SingletonReplSuite \
    TEST_TIMEOUT=2700 \
    TEST_TMPDIR=_tmp/c656ec3d4525e2e66d2996f96385835a \
    TEST_UNDECLARED_OUTPUTS_ANNOTATIONS=bazel-out/darwin-fastbuild/testlogs/repl/org.apache.spark.repl.SingletonReplSuite/test.outputs_manifest/ANNOTATIONS \
    TEST_UNDECLARED_OUTPUTS_ANNOTATIONS_DIR=bazel-out/darwin-fastbuild/testlogs/repl/org.apache.spark.repl.SingletonReplSuite/test.outputs_manifest \
    TEST_UNDECLARED_OUTPUTS_DIR=bazel-out/darwin-fastbuild/testlogs/repl/org.apache.spark.repl.SingletonReplSuite/test.outputs \
    TEST_UNDECLARED_OUTPUTS_MANIFEST=bazel-out/darwin-fastbuild/testlogs/repl/org.apache.spark.repl.SingletonReplSuite/test.outputs_manifest/MANIFEST \
    TEST_UNDECLARED_OUTPUTS_ZIP=bazel-out/darwin-fastbuild/testlogs/repl/org.apache.spark.repl.SingletonReplSuite/test.outputs/outputs.zip \
    TEST_UNUSED_RUNFILES_LOG_FILE=bazel-out/darwin-fastbuild/testlogs/repl/org.apache.spark.repl.SingletonReplSuite/test.unused_runfiles_log \
    TEST_WARNINGS_OUTPUT_FILE=bazel-out/darwin-fastbuild/testlogs/repl/org.apache.spark.repl.SingletonReplSuite/test.warnings \
    TEST_WORKSPACE=runtime \
    TZ=UTC \
    XML_OUTPUT_FILE=bazel-out/darwin-fastbuild/testlogs/repl/org.apache.spark.repl.SingletonReplSuite/test.xml \
  external/bazel_tools/tools/test/test-setup.sh repl/org.apache.spark.repl.SingletonReplSuite)
SUBCOMMAND: # //repl:org.apache.spark.repl.SingletonReplSuite [action 'Testing //repl:org.apache.spark.repl.SingletonReplSuite']
(cd /Users/iulian.dragos/.cache/bazel/_bazel_iulian.dragos/3f8a8ed88c7af0f90b1b2a7ead61bb31/execroot/runtime && \
  exec env - \
    PATH=/usr/bin:/bin \
    TEST_BINARY=repl/org.apache.spark.repl.SingletonReplSuite \
    TEST_NAME=//repl:org.apache.spark.repl.SingletonReplSuite \
    TEST_SHARD_INDEX=0 \
    TEST_TOTAL_SHARDS=0 \
  external/bazel_tools/tools/test/generate-xml.sh bazel-out/darwin-fastbuild/testlogs/repl/org.apache.spark.repl.SingletonReplSuite/test.log bazel-out/darwin-fastbuild/testlogs/repl/org.apache.spark.repl.SingletonReplSuite/test.xml 0 1)
FAIL: //repl:org.apache.spark.repl.SingletonReplSuite (see /Users/iulian.dragos/.cache/bazel/_bazel_iulian.dragos/3f8a8ed88c7af0f90b1b2a7ead61bb31/execroot/runtime/bazel-out/darwin-fastbuild/testlogs/repl/org.apache.spark.repl.SingletonReplSuite/test.log)
INFO: From Testing //repl:org.apache.spark.repl.SingletonReplSuite:
==================== Test output for //repl:org.apache.spark.repl.SingletonReplSuite:
ln: /Users/iulian.dragos/.cache/bazel/_bazel_iulian.dragos/3f8a8ed88c7af0f90b1b2a7ead61bb31/sandbox/darwin-sandbox/1/execroot/runtime/bazel-out/darwin-fastbuild/bin/repl/org.apache.spark.repl.SingletonReplSuite.runfiles/runtime/tmp.pFvLbta8/librepl_test_resources-0.jar: Operation not permitted
================================================================================
Target //repl:org.apache.spark.repl.SingletonReplSuite up-to-date:
  bazel-bin/repl/org.apache.spark.repl.SingletonReplSuite
```

I'll try to check the sandbox configuration, though I don't see it in the process tree. Not sure what `_embedded_binaries/process-wrapper` is, maybe that rings a bell. This is Bazel `release: tls-bazel-0.25.2`.

**Comment by jmmv** [comment]
> Why is it suspicious? Any help highlighting what's wrong with the rule would be already a good step forward. But I do have to mention that this same rule is building fine for 150+ other engineers, so there must be more than this to the story.

Writing to the runfiles tree is suspicious because the runfiles are the files staged by Bazel as dependencies of the given target. They are supposed to be read-only, so writing in there shouldn't be allowed.

> I am guessing that --verbose_failures is not giving any additional output because what's happening is not seen as a failure. Shell has this interesting feature, that result of a sequence of commands is the result of the last command. Therefore, cat IDoNotExist; echo hello is considered, taken together, as success in shell (value of $? is 0), and therefore it would be reported successful to Bazel, despite the error output from first command.

Why does this matter? The test/rule is *failing*, so certainly the exit code is propagated properly?

> I'll try to check the sandbox configuration, though I don't see it in the process tree. Not sure what _embedded_binaries/process-wrapper is, maybe that rings a bell. This is Bazel release: tls-bazel-0.25.2.

You won't see `sandbox-exec` in the process tree because this tool is not forking+waiting. It's using `exec(3)` instead to replace itself.

---

Going back to the failing path: `/Users/iulian.dragos/.cache/bazel/_bazel_iulian.dragos/3f8a8ed88c7af0f90b1b2a7ead61bb31/sandbox/darwin-sandbox/1/execroot/runtime/bazel-out/darwin-fastbuild/bin/repl/org.apache.spark.repl.SingletonReplSuite.runfiles/runtime/tmp.Tc91VdbZ/librepl_test_resources-0.jar`

I have to ask: what flags are you using? Are you changing the `--output_base` or `--output_user_root`, while nobody else is doing that? `~/.cache/bazel/` is *not* the default path for the output base under macOS, and if you are using that path whereas everybody else is using the default path, that would explain it: the sandbox is currently weaker when using the default path under `/private/var/tmp` (#11100).

**Comment by iuliand-db** [comment]
> Writing to the runfiles tree is suspicious because the runfiles are the files staged by Bazel as dependencies of the given target. They are supposed to be read-only, so writing in there shouldn't be allowed.

The failing file is a jar file containing only a logback configuration file, so in a sense it's a "dependency" of this test.

> I have to ask: what flags are you using? Are you changing the --output_base or --output_user_root, while nobody else is doing that? ~/.cache/bazel/ is not the default path for the output base under macOS, and if you are using that path whereas everybody else is using the default path, that would explain it: the sandbox is currently weaker when using the default path under /private/var/tmp (#11100).

I'm not using any of those flags, I'm building as much as I can tell the same as everyone else.  But your comment made me remember: there is a symlink from `/private/var/tmp_bazel...` into `~/.cache/bazel` so that's why my paths look like that. This is part of an "onboarding" setup script that I ran on my laptop (recent hire ;-)), so maybe this is a new thing and I'm the first to hit the problem.

However, given #11100 wouldn't this be expected to work?

**Comment by jmmv** [comment]
The problem is that the sandbox currently whitelists all of `/private/var/tmp`, so if the output base is anywhere under that hierarchy (as it is by default, hence why I mentioned #11100)... the sandbox is actually quite ineffective :(

By moving the output base elsewhere as you did, you are causing the sandbox to do the right thing -- and then I'm pretty sure it's capturing a bug in your rules / test. Try removing that symlink. I'm pretty sure it'll unblock you, but then you'll have to figure out what's wrong with your rules / test. I'm guessing there is an mkdtemp call in there that lacks a path prefix or is using the wrong path prefix.

**Comment by iuliand-db** [comment]
> By moving the output base elsewhere as you did, you are causing the sandbox to do the right thing -- and then I'm pretty sure it's capturing a bug in your rules / test. Try removing that symlink.

Indeed, that makes it work. Thanks! I'll close this ticket and investigate on our side why the link is in place and if our rules are doing something wrong!
