### ISSUE TITLE
`.bazelversion` blocks query of 'bazel version' and `bazel info release`

### ISSUE THREAD

**Issue by psigen** [bazelbuild/bazel#11346]
### Description of the problem / feature request:

The presence of a `.bazelversion` file that defines any non-matching version at the root of a directory structure prevents bazel from intepreting _any_ commands in any subdirectory, including `bazel version`, `help`, `info`.

However, these are the commands needed to debug why `.bazelversion` is not satisfied, or to query non-build-related help information.  For example, `bazel info` can _only_ be run from a workspace.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Create a new directory with two files:
  * `.bazelversion`
  * `WORKSPACE`
2. In `.bazelversion`, put a clearly incompatible version string, e.g. `5.0.0`.
3. Run `bazel version` within this directory.  Instead of returning the version, bazel will print:
```
$ bazel version
ERROR: The project you're trying to build requires Bazel 5.0.0 (specified in [...]/.bazelversion), but it wasn't found in /usr/bin.

You can install the required Bazel version via apt:
  sudo apt update && sudo apt install bazel-5.0.0

If this doesn't work, check Bazel's installation instructions for help:
  https://docs.bazel.build/versions/master/install-ubuntu.html
```
4. This prevents querying version information from the bazel CLI from any subdirectory, which is what a developer would need to amend the `.bazelversion` file or debug a pathing issue (e.g. if a wrong installation of bazel is being used).

(As an interesting side note, while testing I accidentally created a blank `WORKSPACE` and incompatible `.bazelversion` file in my user home directory-- this blocked me from running bazel commands in any subdirectory that was not a workspace itself.)

### What operating system are you running Bazel on?

Ubuntu 18.04 (also observed on OSX).

### What's the output of `bazel info release`?
```
$ bazel info release
Starting local Bazel server and connecting to it...
release 3.1.0
```

###  Have you found anything relevant by searching the web?

Mentioned in https://github.com/bazelbuild/bazel/issues/11264, which focuses on missing documentation for `.bazelversion`.  It's fine to close this as a duplicate, I just wanted to specifically describe the usability issue.

**Comment by aiuto** [comment]
That's a fun one. The behavior is both reasonably correct and blindingly stupid.

The same thing happens for `bazel --version`. 
The fix might be relatively easy - ./scripts/packages/bazel.sh implements the check.

**Comment by nikhilpothuru** [comment]
Hi, This is my first time working on the Bazel project. I wanted to ask some clarifying questions before I took on this issue. I was able to reproduce the problem as mentioned by psigen on OSX. I added an incompatible version string (i.e. 5.0.0) and I am unable to make queries like bazel version and bazel info release. 

I downloaded the sample project from the "Introduction to Bazel: Building a Java Project" page and tried bazel version. This is what I got:
''' Build label: 3.2.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed May 27 17:58:08 2020 (1590602288)
Build timestamp: 1590602288
Build timestamp as int: 1590602288 '''

**Do we want to check if the version string is invalid in the .bazelversion, and then send a proper output, with the most current build label?**

**Comment by nikhilpothuru** [comment]
Hi,

I was able to get some clarification regarding what the output should be from psigen. I will take a look at how I can modify./scripts/packages/bazel.sh. Based on psigen's clarification, I will try to get the output to be similar to the output when there is no .bazelversion file at all. 

-- Nikhil Pothuru

**Comment by philwo** [comment]
Thank you for your thoughts on this. Unfortunately I don't understand what your expected behavior is.

The output `bazel version` or `bazel info` of course depends on the version of Bazel that is invoked. The version of Bazel that is invoked is determined by the `.bazelversion` file. Thus, if the version that is referenced from that file is not installed, there is no way to print the correct output of `bazel version` or `bazel info`.

The error message seems sensible to me and I fail to see how you could end up with an "invalid" `.bazelversion` file in the first place?

**Comment by psigen** [comment]
Would it be possible to amend the error message to include meta-information about available versions of bazel?
