### ISSUE TITLE
Incorporate sandboxing details from blog posts into the documentation

### ISSUE THREAD

**Issue by floriographygoth** [bazelbuild/bazel#11343]
Documentation URL: https://blog.bazel.build/2015/09/11/sandboxing.html

There is good information in the "Sandboxing" blog, but it isn't in the canonical docs.

**Comment by laurentlb** [comment]
cc @philwo @jmmv

**Comment by jmmv** [comment]
Also https://blog.bazel.build/2018/04/13/preliminary-sandboxfs-support.html

**Comment by communikit** [comment]
https://docs.bazel.build/versions/master/sandboxing.html was created.
