### ISSUE TITLE
incompatible_objc_provider_remove_compile_info

### ISSUE THREAD

**Issue by googlewalt** [bazelbuild/bazel#11359]
This flag is part of the efforts to migrate `ObjcProvider` compile info to `CcCompilationContext`. It removes the Starlark APIs related to the definition and use of compile info in `ObjcProvider`.  See #10674 for more details on the overall efforts.

**6/3/2020** This flag also removes the merge_zip related Starlark APIs.  These usages should be migrated to `apple_resource_group` provided by `rules_apple`.  We piggyback this functionality to avoid adding yet another incompatible flag.

Specifically, the flag does the following:

* The compiler related-APIs (and merged_zip) to `ObjcProvider` will be removed: `define`, `framework_search_path_only`, `header`, `include`, `include_system`, `iquote`, `merge_zip`, and `compilation_context`.

* `apple_common.new_objc_provider()` will stop taking compile-related (and merge_zip) arguments: `define`, `framework_search_paths`, `include`, `include_system`, `iquote`, and `merge_zip`.  It will continue to take `header`, which is used to populate its direct fields (use by e.g. tulsi), but `header` will not populate any compile-related fields.

* `apple_common.new_objc_provider()` will stop taking `direct_dep_providers`.  Use `strict_include` instead.  Note this feature should only be used internally and should not affect bazel users.

Expected timeline:

* Available and default false in 3.4.
* Enabled and removed in next major release.

**Comment by philwo** [comment]
Closing, because this flag has been flipped.
