### ISSUE TITLE
Allow more flexibility for C++ file extensions given as input to rules or Starlark API

### ISSUE THREAD

**Issue by oquenchil** [bazelbuild/bazel#11356]
Currently, extensions are allowed for rules and the Starlark C++ API are hard-coded. This leads to users getting errors unnecessarily and we see a lot of PRs to add a new extension to the hard-coded list.

We should evaluate how to be more flexible with extensions in a safe way without breaking existing code.

**Comment by loshca** [comment]
How about to start with
1) removing extension validation for public headers and private headers in CcModule.java. 
2) removing extension validation in addPrivateHeader (CcCompilationHelper.java)?

This will not break existing code: cc_binary && cc_library still will use the hardcoded list to separate sources and private headers, but we can use any headers (including headers with no extension) in custom cc rules using cc_common.compile.
It looks cheap, but will help a lot!

**Comment by oquenchil** [comment]
Yes, that sounds excellent! If you want to send a PR we will review happily.
