### ISSUE TITLE
Can't invoke py_binary or java_binary from Skylark action

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#1136]
Consider this repository https://github.com/dfabulich/cannot-find-runfiles

There's a simple python script in `build_tools/whatevah.py` that accepts one CLI argument and writes a file to that location.

```python
import sys

with open (sys.argv[1], "w") as OUT:
	OUT.write("hello world")
```

It's declared as a simple `py_binary` in `build_tools/BUILD`.

```python
py_binary(
	name='whatevah',
	srcs=['whatevah.py'],
	visibility=['//visibility:public'],
)
```

There's a simple Skylark rule in `build_tools/example.bzl`; the `example` rule runs `whatevah` to generate a `%{name}.txt` file as output.

```python
def _impl(ctx):
	ctx.action(
		inputs = [ctx.executable._whatevah],
		outputs = [ctx.outputs.text],
		command = "{} {}".format(ctx.executable._whatevah.path, ctx.outputs.text.path),
	)

example = rule(
	implementation = _impl,
	attrs = {
		"_whatevah": attr.label(executable=True, allow_files=True, default=Label("//build_tools:whatevah"))
	},
	outputs = {
		"text": "%{name}.txt",
	}
)
```

Finally, `foo/BUILD` declares a `foo` target with the `example` rule.

```python
load('/build_tools/example', 'example')

example(
	name='foo',
)
```

When I `bazel build foo`, I expect it to succeed and generate `foo.txt`, but instead I get this error:

```
$ bazel build foo --verbose_failures
INFO: Found 1 target...
ERROR: /private/tmp/repro/foo/BUILD:3:1: error executing shell command: 'bazel-out/local_darwin-fastbuild/bin/build_tools/whatevah bazel-out/local_darwin-fastbuild/bin/foo/foo.txt' failed: bash failed: error executing command
  (cd /private/var/tmp/_bazel_dfabulich/92410d0e3373f265902564b48493ac12/repro && \
  exec env - \
  /bin/bash -c 'bazel-out/local_darwin-fastbuild/bin/build_tools/whatevah bazel-out/local_darwin-fastbuild/bin/foo/foo.txt'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Traceback (most recent call last):
  File "bazel-out/local_darwin-fastbuild/bin/build_tools/whatevah", line 110, in <module>
    Main()
  File "bazel-out/local_darwin-fastbuild/bin/build_tools/whatevah", line 66, in Main
    sys.argv[0])
AssertionError: Cannot find .runfiles directory for bazel-out/local_darwin-fastbuild/bin/build_tools/whatevah
Target //foo:foo failed to build
INFO: Elapsed time: 0.113s, Critical Path: 0.03s
```

`foo/BUILD` also declares a `bar` target as a `genrule` that does, as far as I understand, exactly the same thing as my Skylark rule.

```python
genrule(
	name='bar',
	tools=['//build_tools:whatevah'],
	outs=['bar.txt'],
	cmd="$(location //build_tools:whatevah) $@"
)
```

`bazel build foo:bar` succeeds and generates `bar.txt`, as expected.

**Comment by dfabulich** [comment]
```
$ bazel version
Build label: 0.2.1-homebrew
Build target: bazel-out/local_darwin-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Apr 1 00:35:17 2016 (1459470917)
Build timestamp: 1459470917
Build timestamp as int: 1459470917
```

**Comment by dfabulich** [comment]
Intriguingly, on Mac, where Bazel doesn't use a sandbox (as of 0.2.1), I can kinda workaround this issue by explicitly building `build_tools:whatevah`.

Which is to say, this succeeds:

```
bazel clean
bazel build build_tools:whatevah
bazel build foo
```

But this fails:

```
bazel clean
bazel build foo
```

On Ubuntu, where Bazel does use a sandbox, that workaround doesn't work; I even tried running it with `--spawn_strategy=standalone`, but the workaround still failed.

What am I missing?

**Comment by dfabulich** [comment]
As this repository shows, the same thing happens when you use a `java_binary`. https://github.com/dfabulich/skylark-depends-on-java-binary

In that sample, we start with the sample `BUILD` as documented in Bazel's [Getting Started](http://bazel.io/docs/getting-started.html) guide.

Then we add a simple Skylark rule to invoke `//:my-other-runner`

```python
def _impl(ctx):
	ctx.action(
		inputs = ctx.files._my_other_runner,
		outputs = [ctx.outputs.simple],
		command = "{} > {}".format(ctx.executable._my_other_runner.path, ctx.outputs.simple.path)
	)

simple = rule(
	implementation = _impl,
	attrs = {
		"_my_other_runner": attr.label(allow_files=True, executable=True, default=Label("//:my-other-runner"))
	},
	outputs = {
		"simple": "%{name}.txt"
	}
)
```

and add a `simple` rule to `BUILD`:

```python
simple(
	name='simple'
)
```

Expected: Success when running `bazel build //:simple`
Actual:

```
bazel-out/local_darwin-fastbuild/bin/my-other-runner: Cannot locate runfiles directory. (Set $JAVA_RUNFILES to inhibit searching.)
```

On OS X, explicitly building `//:my-other-runner` before building `//:simple` is a workaround, as above, and `bazel clean` makes it fail again. On Linux, where the sandbox is enabled, there is no workaround.

This is P2 annoying for `py_binary`, because I can just ship the scripts around directly. For `java_binary`, where there's a huge transitive set of `java_library` labels I need to depend on, this is P1. (I mean, I could try to marshal dozens of jars myself, reconstruct my own equivalent of `runfiles`, etc. etc. but but but that's a total mess.)

**Comment by damienmg** [comment]
Replacing:
```python
ctx.action(
        inputs = ctx.files._my_other_runner,
        outputs = [ctx.outputs.simple],
        command = "{} > {}".format(ctx.executable._my_other_runner.path, ctx.outputs.simple.path)
    )
```

with:
```python
ctx.action(
        inputs = ctx.files._my_other_runner,
       outputs = [ctx.outputs.simple],
       executable = ctx.executable._my_other_runner,
       arguments = [ctx.outputs.simple.path],
    )
```

would achieve what you want provided that you modify your runner to output the result to the first argument.

The reason it is P2 is that the ctx.action with a command line is shaky and we wonder if we want to support it.

However, there is a way to do it using the other syntax is to collect the runfiles of my_other_runner and add them as inputs.

**Comment by kamalmarhubi** [comment]
If you can't / don't want to modify the runner to output to first argument, you should be able to wrap it in a `sh_binary` that does it, and use that as the `executable` in `ctx.action()`.

I'm not yet a heavy bazel user, but I feel that having bash syntax in the build files is a bit questionable. It's certainly useful, but it gets unreadable very quickly with all the escaping necessary.

**Comment by dfabulich** [comment]
Wrapping it in a `sh_binary` doesn't work. I've added a new commit to the repository to demonstrate this.

In the new commit, I added a `simple-runner.sh` script:

```bash
./my-other-runner > $1
```

And I've added a `sh_binary` rule for it:

```python
sh_binary(
	name='simple-runner',
	srcs=['simple-runner.sh'],
	data=['my-other-runner'],
)
```

I verified that `bazel run //:simple-runner -- /tmp/outfile.txt` runs and that `/tmp/outfile.txt` contains `Hi!` as expected.

So I changed the `simple.bzl` rule to this, using `ctx.action`'s `executable` instead of `command`:

```python
def _impl(ctx):
	ctx.action(
		executable = ctx.executable._runner,
		arguments = [ctx.outputs.simple.path],
		outputs = [ctx.outputs.simple],
	)

simple = rule(
	implementation = _impl,
	attrs = {
		"_runner": attr.label(allow_files=True, executable=True, default=Label("//:simple-runner"))
	},
	outputs = {
		"simple": "%{name}.txt"
	}
)
```

Expected: `bazel build //:simple` should build without error.

Actual: It fails, because the `simple-runner` is missing its required data (the `java_binary`).

```
bazel-out/local_darwin-fastbuild/bin/simple-runner: line 1: ./my-other-runner: No such file or directory
```

**Comment by dfabulich** [comment]
I think it's no surprise that switching to `sh_binary` and `ctx.action`/`executable` didn't work, since #1147 is all about `sh_binary` and is also not helped by switching from `command` to `executable`.

**Comment by trainman419** [comment]
+1. I've seen this issue as well, but I had assumed it was an error on my part. Glad to know I'm not the only one having this issue.

**Comment by dfabulich** [comment]
By working around #1147 I'm able to wrap the `java_binary` in a carefully crafted `sh_binary` to work around this bug #1136 in the latest version of https://github.com/dfabulich/skylark-depends-on-java-binary

Note that Skylark `ctx.action` runs the `simple-runner` `sh_binary` from the root of the sandbox's workspace, but the `sh_binary` expects to be run from `bazel-bin/simple-runner.runfiles`.

The following `simple-runner.sh` bash script works around the incorrect working directory. (But only when using the `executable` argument for `ctx.action`; it doesn't work at all when using `command`.)

```bash
#!/bin/bash -eux
START_DIR=`pwd`
OUTPUT=$1
if [ "${OUTPUT:0:1}" != "/" ]; then
        OUTPUT=$START_DIR/$1
fi
cd ${BASH_SOURCE[0]}.runfiles
./my-other-runner > $OUTPUT
```

**Comment by dfabulich** [comment]
Er, this is probably less hacky:

```bash
#!/bin/bash
${BASH_SOURCE[0]}.runfiles/my-other-runner > $1
```

**Comment by dfabulich** [comment]
This bug is really talking about issue #1192 and issue #1147. This bug #1136 came first, but it's now a more confusing duplicate, so I'll close it.
