### ISSUE TITLE
Runfiles cannot open MANIFEST files on paths longer than 260 chars

### ISSUE THREAD

**Issue by ozio85** [bazelbuild/bazel#11362]
# Description of the problem / feature request:

Runfiles is not using wide char which means all MANIFEST files located on paths longer than 260, will not be possible to read, and will result in the runfiles default behavior:
Appending the path to the runfiles directory (which on Windows would mean, finding no file)

The runfiles cpp code is used in the Bazel internal test wrapper (tw), which means all tests which have a MANIFEST file on a path longer than 260 chars, will crash, since the test binary itself is located with the runfiles manifest.

### Feature requests: what underlying problem are you trying to solve with this feature?

Convert the runfiles to use wide character strings, and the "W" win API instead of the "A" win API

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try to read a MANIFEST file on windows using the cpp/runfiles

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

3.1.0

**Comment by ozio85** [comment]
I created a pull request.. please comment:
https://github.com/bazelbuild/bazel/pull/11364

**Comment by philwo** [comment]
Hey @ozio85, considering that the PR https://github.com/bazelbuild/bazel/pull/11364 was closed due to inactivity, is this still an open issue for you?

**Comment by ozio85** [comment]
Yeah it is an open issue, but it is not that major (therefore i did not prioritize it). However, manifest paths over 255 chars is not possible to read with the short API. You have to use the wchar api to be able to support and read files lobger than that
