### ISSUE TITLE
Java Builder Stub Action is by default using jdk11 as javabin, not the one specified in toolchain

### ISSUE THREAD

**Issue by ThomasCJY** [bazelbuild/bazel#11382]
### Description of the problem / feature request:
While creating java stub action, bazel is using the default java executable (jdk11, on mac that is `remotejdk11_macos`) to replace the `%javabin%` placeholder in `java_stub_template` file. [Code Link](https://github.com/bazelbuild/bazel/blob/77502091f06b84054921f4eeee3f1d093dd8427d/src/main/java/com/google/devtools/build/lib/bazel/rules/java/BazelJavaSemantics.java#L288-L291) 

Ideally, bazel should respect the java version specified in toolchain and align the stub javabin version with it. I know it's only a stub but in reality it's been used a lot in java-related build systems, for example, [rules_kotlin](https://github.com/bazelbuild/rules_kotlin/) is silently using this stub action on all compilation tasks, which partly contributed to [the issue](https://github.com/bazelbuild/rules_kotlin/issues/188) where kotlin target is always being built by jdk11 without respecting the java version defined in toolchain.

### What operating system are you running Bazel on?

macos 10.15.4

### What's the output of `bazel info release`?

2.2.0

**Comment by cushon** [comment]
what's the simplest way to reproduce the issue you're seeing? can you provide a minimal example?

**Comment by ThomasCJY** [comment]
@cushon simply build any kotlin targets can reproduce this issue. I added example code here https://github.com/ThomasCJY/bazel_example/pull/1

**Comment by cushon** [comment]
Isn't this a `rules_kotlin` bug and not a Bazel bug, then? It looks like it's accessing the template directly and doing its own substitution: https://github.com/bazelbuild/rules_kotlin/blob/484f116c1949984697556bcd371ef8eecacc08cb/kotlin/internal/jvm/impl.bzl#L67

**Comment by ThomasCJY** [comment]
@cushon well the [code you linked](https://github.com/bazelbuild/rules_kotlin/blob/484f116c1949984697556bcd371ef8eecacc08cb/kotlin/internal/jvm/impl.bzl#L67) doesn't apply to `kotlin_jvm_lib` rule, it is only applied for the binary target. I believe `kotlin_jvm_library` rule is following the default path to create a builder file.

**Comment by lberki** [comment]
@comius , WDYT? It looks like this is something for which a fix may fall out from your toolchain work?

**Comment by comius** [comment]
@ThomasCJY I downloaded your reproduction and tried it out.

I believe rules_kotlin as well as Bazel are working as intended. I believe you can support your usecases using Bazel configuration flags. How Bazel is working is a bit complicated so let me explain.

There are 2 to 4 JDKs that Bazel uses, one to execute built targets, one to execute targets that are needed during the build, and potentially two more that are used to compile for first and the second.

The builder file you're looking is executed during the build. This is prescribed in rules_kotlin here  https://github.com/bazelbuild/rules_kotlin/blob/484f116c1949984697556bcd371ef8eecacc08cb/kotlin/internal/toolchains.bzl#L87 with `cfg = "host"`. Default configuration for this is remotejdk11.

In Bazel you can configure which JDK is used. We're in fact just in the mid of transition how this configuration is done.

If you're using old Bazel <= 4.0.0, you can change the JDK the code is executed on using flags `--javabase=@local_jdk//:jdk --host_javabase=@local_jdk//:jdk`. In case of buildifier file, `--host_javabase` flags controls the JDK. In fact I checked your example and the builder file is correctly changed.

The code is compiled using remote JDK11, but it is configured in a way to produce code for the targeted JDK (which can be 8). On the old Bazel it is a bit tricky how to compile code using actually JDK<=8. You need to define `default_java_toolchain` for it.

The Bazel@head uses different configuration options. To execute on and compile for JDK 8, you can set `--java_runtime_version=8` and `--tool_java_runtime_version=8`. This will fail if you don't have a local JDK8.

To also compile with JDK8 (bazel@head) add a flag `--additional_toolchains=@local_jdk//:all`.
