### ISSUE TITLE
Remove -Xverify:none from Java invocations

### ISSUE THREAD

**Issue by guw** [bazelbuild/bazel#11381]
### Description of the problem / feature request:

Bazel currently add `-Xverify:none` to Java commands it executes. 

### Feature requests: what underlying problem are you trying to solve with this feature?

This is a dangerous option because it disables the byte code verifier. Having the option in place without justification/documentation reduces trust of our developers/users.

The option has been deprecated in Java 13 and will be removed in a future release.

Please remove the option. 

Alternatively please provide a flag to disable it and add documentation why it's needed and what the risks are of removing/disabling `-Xverify:none` with regards to Bazel.

**Comment by guw** [comment]
I found it in the following locations:
https://github.com/bazelbuild/bazel/blob/ff580817ae94859a858e9b155ba73566d68c4592/src/main/java/com/google/devtools/build/lib/analysis/actions/SpawnAction.java#L1036
https://github.com/bazelbuild/bazel/blob/0816a7d1ca525fa8144cfc2f28a81aee0b580a92/src/main/java/com/google/devtools/build/lib/rules/java/JavaHeaderCompileActionBuilder.java#L341

There might be more.

**Comment by jin** [comment]
cc @cushon / @lberki, do you have the context on why this flag is hardcoded?

**Comment by cushon** [comment]
The motivation was to improve startup performance of host tools that we trust. The hard-coded flags for JavaBuilder and turbine were made obsolete by `java_toolchain.jvm_opts`, which allows them to be configured in the toolchain instead.

I don't know a replacement for `SpawnAction`, but hard-disabling verification for all Java tools using `SpawnAction` seems kind of iffy.

I don't have any concerns with trying to remove these.

**Comment by lberki** [comment]
Echoing @cushon's opinion, at the very least, this should not be hardcoded into Bazel itself but in the individual Java toolchains.
