### ISSUE TITLE
Feature: Allow directory trees ignored via `.bazelignore` to become un-ignored

### ISSUE THREAD

**Issue by joeljeske** [bazelbuild/bazel#11380]
### Description of the problem / feature request:

Support a command line flag to "un-delete" a package (the inverse of `--deleted_packages`)

### Feature requests: what underlying problem are you trying to solve with this feature?

When working with packages that are unstable due to being work-in-progress or perhaps in the process of migrating to bazel, it is often helpful to mark those packages as "deleted" such that they are ignored by bazel.

It would be very helpful to support command line flags to undelete these packages when working on them. One could setup a bazelrc `config` that would "undelete" these packages for an easy authorship workflow. 

This workflow seems like a very cheap and easy way to feature gate works in progress while still allowing large teams to collaborate at HEAD.

**Comment by haxorz** [comment]
`--deleted_packages` is a legacy feature in Bazel's predecessor Blaze and is honestly something I'd like to remove if I had the time to do so.

It sounds like you are using `.bazelrc` or some other mechanism to cause `--deleted_packages=p1,p2,p3` to be passed to all the bazel invocations of you and your colleagues. For your use-case, what's wrong with passing the `--deleted_packages` flag again, overriding the initial value: `bazel build //foo --deleted_packages=p1,p2,p3 --deleted_packages=p2,p3`? Or am I misunderstanding your use-case and/or goal?

**Comment by joeljeske** [comment]
@haxorz So my use case is actually to have packages that appear in bazelignore become "unignored" under specific`--config`settings. I jumped to the conclusion that bazelignore and deleted_packages add packages to the same ignore mechanism, however that may not be true. 

Is there a way to have packages ignored in the bazelignore, and then have a cli args bring those packages into the build scope?

**Comment by haxorz** [comment]
Thanks for the context.

> I jumped to the conclusion that bazelignore and deleted_packages add packages to the same ignore mechanism, however that may not be true.

They use different mechanisms. So your FR is actually for `.bazelignore`.

> Is there a way to have packages ignored in the bazelignore, and then have a cli args bring those packages into the build scope?

No, don't think so.

**Comment by haxorz** [comment]
I assume you've already considered making pending modifications to your `.bazelignore` file (with no intent to commit these modifications). This would surely work, but I assume you've considered it an unacceptable replacement for this FR. Can you please explain why?

**Comment by joeljeske** [comment]
Currently, I have been commenting things out in the bazelignore, but it would be a more pleasant workflow to allow cli args to change the behavior instead. I am in the process of consolidating repositories and converting them to bazel. Typically I have scripts that copy the src code into the dest repo into dir that is ignored by git. While I am working on that migration, I need bazel to load that directory, but when I am on working on other tasks, I need bazel to ignore that migration directory. It is annoying to have keep local changes in a file.

**Comment by haxorz** [comment]
Ok, thanks! I've routed this to the team responsible for `.bazelignore`. It was originally routed for the team responsible for `--deleted_packages` (and sorry for the massive delay there!)
