### ISSUE TITLE
Bazel is unable to compile Java code importing JFR on Zulu-8 JDK.

### ISSUE THREAD

**Issue by ceronman** [bazelbuild/bazel#11390]
### Description of the problem:

I'm using the Zulu 8 JDK (OpenJDK Runtime Environment (Zulu 8.46.0.19-CA-macosx) (build 1.8.0_252-b14). This JDK has Java Flight Recorder backported from Java 11.

I have this code sample:

```java
// Test.java
import jdk.jfr.FlightRecorder;
public class Test {
}
``` 
Compiling this with plain `javac` works fine:

```
javac Test.java
```

However, when using Bazel (3.1.0):

```
java_library(
    name = "jfr",
    srcs = ["Test.java"]
)
```

The build fails:

```
$ bazel build :jfr
INFO: Analyzed target //:jfr (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/mceron/git_tree/sandbox/jfr/BUILD:1:1: Building libjfr.jar (1 source file) failed (Exit 1)
Test.java:1: error: cannot find symbol
import jdk.jfr.FlightRecorder;
              ^
  symbol:   class FlightRecorder
  location: package jdk.jfr
Target //:jfr failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.160s, Critical Path: 0.06s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

I tried to use `vanilla_toolchain`, but it didn't work:

```
bazel build --host_javabase=@local_jdk//:jdk --java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla -s :jfr
```

I also tried to use `absolute_toolchain`, it didn't work:

```
bazel build --define ABSOLUTE_JAVABASE=$JAVA_HOME --host_javabase=@bazel_tools//tools/jdk:absolute_javabase --java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla -s :jfr
```

Using `toolchain_java11` works, but this generates Java 11 bytecode which is not what I want:

```
bazel build --java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 -s :jfr
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Install Zulu 8.46.0.19-CA-macosx and try the file described above.

### What operating system are you running Bazel on?

macOS 10.13.6

### What's the output of `bazel info release`?

release 3.1.0

**Comment by comius** [comment]
Can't reproduce on Bazel@HEAD and latest Zulu JDK8. I assume the issue was fixed.

Reproduction is here https://github.com/comius/issue_11390.git
