### ISSUE TITLE
Request to show download link early when fetching packages

### ISSUE THREAD

**Issue by storypku** [bazelbuild/bazel#11406]
### Description of the feature request:
**Request to show download link early when fetching packages**
As can be seen from the following  log, when I tried to build my project using bazel, bazel starts to fetch the `boringssl` package for me. However, as my network connection was not stable for some reason, It takes bazel 49+ seconds before timeout and showing me that it can't make it work done. So, my suggestion is,  Is it better if bazel shows me the download link of `boringssl` from beginning ?  If so, I can see my network problem early and using alternative methods to pre-download `boringssl` from THAT link address and put it in my `--distdir` directory.

```
$ bazel build --distdir=/home/story/.cache/distdir //path/to/my/target/...
Starting local Bazel server and connecting to it...
(12:46:57) INFO: Current date is 2020-05-15
(12:47:49) Analyzing: 70 targets (99 packages loaded, 3621 targets configured)
    Fetching @boringssl; fetching 49s
 //path/to/my/target/...
Starting local Bazel server and connecting to it...
(12:46:57) INFO: Current date is 2020-05-15
(12:47:38) Analyzing: 70 targets (99 packages loaded, 3621 targets configured)
(12:47:55) INFO: Repository boringssl instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/story/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:16: in <toplevel>
(12:47:55) WARNING: Download from https://boringssl.googlesource.com/boringssl/+archive/83da28a68f32023fd3b95a8ae94991a07b1f6c62.tar.gz failed: class java.io.IOException connect timed out
(12:47:55) ERROR: An error occurred during the fetch of repository 'boringssl':
   java.io.IOException: Error downloading [https://boringssl.googlesource.com/boringssl/+archive/83da28a68f32023fd3b95a8ae94991a07b1f6c62.tar.gz] to /home/story/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/boringssl/83da28a68f32023fd3b95a8ae94991a07b1f6c62.tar.gz: connect timed out
```
### Feature requests: what underlying problem are you trying to solve with this feature?
As stated above, people with poor network connection can have a better experence if  bazel shows the link address early when start fetching packages.
 
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

PS: In this exact example, even if I put the exact `boringssl` package as linked above in my `--distdir` destination, it didn't recognize the tarball... And insist on fetching .... before timeout... I don't know why...

### What operating system are you running Bazel on?
nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04 docker container.

### What's the output of `bazel info release`?
```
release 3.1.0
```
### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

Nope.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

See above.

**Comment by storypku** [comment]
So, another question is, how does bazel's mechanism in checking user pre-downloaded tarballs in `--distdir` directory? Does it do so by comparing their checksums?

**Comment by jin** [comment]
> So, another question is, how does bazel's mechanism in checking user pre-downloaded tarballs in --distdir directory? Does it do so by comparing their checksums?

Yes, checksums and basename actually.

**Comment by storypku** [comment]
> > So, another question is, how does bazel's mechanism in checking user pre-downloaded tarballs in --distdir directory? Does it do so by comparing their checksums?
> 
> Yes, checksums and basename actually.

I can see why `--distdir` doesn't work for the `boringssl` case now:

My project depends on grpc-1.26.0 from https://github.com/grpc/grpc/archive/v1.26.0.tar.gz, boringssl was inderectly depended on there:

Excerpt from `grpc-1.26.0/bazel/grpc_deps.bzl`
```
104     if "boringssl" not in native.existing_rules():
105         http_archive(
106             name = "boringssl",
107             # NOTE: This URL generates a tarball containing dynamic date
108             # information, so the sha256 is not consistent.
109             url = "https://boringssl.googlesource.com/boringssl/+archive/83da28a68f32023fd3b95a8ae94991a07b1f6c62.tar.gz",
110         )
```

Since `grpc_deps.bzl` doesn't specify a fixed checksum for `boringssl`, bazel can't determine whether the file under `--distdir` is the package wanted based on its basename  alone. As can be seen from the following log:

```
(05:23:04) INFO: Current date is 2020-05-19
(05:23:14) INFO: SHA256 (https://boringssl.googlesource.com/boringssl/+archive/83da28a68f32023fd3b95a8ae94991a07b1f6c62.tar.gz) = 8ddb2cd7cf041e5afea9d7ea90d9e01075476a03e94014f2201e9216bddc7b06
(05:23:15) DEBUG: Rule 'boringssl' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "8ddb2cd7cf041e5afea9d7ea90d9e01075476a03e94014f2201e9216bddc7b06"
(05:23:15) DEBUG: Repository boringssl instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:16: in <toplevel>
```

```
