### ISSUE TITLE
Aspects requiring providers can't propagate through `bind()`

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#1140]
This is because `bind()` returns nothing as the set of advertised providers, so if an aspect requires a provider, it won't be propagated. However, the set of providers `bind()` actually has depends on the rule it's bound to and that can be anything., including providers that would trigger aspect propagation.

A disabled test case is available as `AspectTest#aspectCreationWorksThroughBind()`.

Note that if this is fixed, `bazel query` will need to be fixed, too.

**Comment by dslomov** [comment]
Yes, and I am actively working in that area, but it is a P2, so might slip.

**Comment by dslomov** [comment]
The actual bug is already fixed (quite a while ago actually); there are some extra complications with required/advertised providers that I am fixing now, but this request can be closed.
