### ISSUE TITLE
Bazel python equivalent to setuptools package_dir?

### ISSUE THREAD

**Issue by jxramos** [bazelbuild/bazel#11414]
### Description of the problem / feature request:
This is a feature request for how to get bazel to deploy python source with folder structures _not_ identical to the verbatim folder structure in source control.

There's a convention to have python repos under a `src` folder which gets mapped to the project name in `setuptools.setup` via the `package_dir` parameter.

In the documentation you'll see stuff like...

> If you use a different convention to lay out your source directory, that’s no problem: you just have to supply the `package_dir` option to tell the Distutils about your convention.
>
> https://docs.python.org/3.9/distutils/setupscript.html#listing-whole-packages 

### Feature requests: what underlying problem are you trying to solve with this feature?

I'll speak by way of example. Consider the following python project...

```bash
$ tree projX
projX
├── setup.py
└── src
    └── projX.py
```

where `setup.py` goes as...

```python
import setuptools

setuptools.setup(
    name="projX",
    package_dir={"projX": "src"}, # <==== how to achieve this remapping/aliasing capability ??
    packages=["projX"],
)
```

If I install that package it will deploy to the site-packages as

```bash
tree /home/$USERX/.local/lib/python3/site-packages/projX | grep -vE "(pyc|pycache)"
   /home/$USERX/.local/lib/python3/site-packages/projX
    ├── projX.py
```

The problem it seems is that bazel BUILD files have no such "remapping" capability to treat the `src` folder anything other than the literal string `src` when copied over to the runfiles.

### What operating system are you running Bazel on?

Linux 14

### What's the output of `bazel info release`?

release 0.24.1-2.11

### Commentary
I'd imagine this is a new use case beyond the simple imports functionality which deals with the python path manipulation to deploy the folders under the literal names. This feature may indeed need a new python attribute, perhaps `imports_as` which maps to a dict

```python
py_library(
   name="projX",
   imports_as={"projX":"src"},
```

something along those lines.

**Comment by aiuto** [comment]
Python folks: possibly move to rules_python?
