### ISSUE TITLE
error prone warning in BazelModuleContext.java

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#11411]
Ever since 9f2cab5d846, builds have produced warnings like this:
```
src/main/java/com/google/devtools/build/lib/packages/BazelModuleContext.java:34: warning: An @AutoValue property that is a primitive array returns the original array, which can therefore be modified by the caller. If this OK, you can suppress this warning with @SuppressWarnings("mutable"). Otherwise, you should replace the property with an immutable type, perhaps a simple wrapper around the original array.
  public abstract byte[] bzlTransitiveDigest();
```

**Comment by cushon** [comment]
This line needs an `@AutoValue.CopyAnnotations` [1], I'll take care of it:

https://github.com/bazelbuild/bazel/blob/0932d0e9fc9fb68e0745f1d5c0b46ca34b6b6f54/src/main/java/com/google/devtools/build/lib/packages/BazelModuleContext.java#L33

[1] https://github.com/google/auto/blob/master/value/userguide/howto.md#copying-to-the-generated-field

**Comment by benjaminp** [comment]
It looks like this also needs `@SupressWarnings("mutable")`?
