### ISSUE TITLE
Local action cache doesn't work on Windows

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#1141]
In this sequence of commands:

`output/bazel --batch build //src:bazel`
`output/bazel --batch build //src:bazel`

The second command re-runs all actions again. This doesn't seem to be the case for @dslomov , but was consistently reproducible on my workstation, so there is definitely something going on.

**Comment by meteorcloudy** [comment]
This is fixed at eb2f5ea16e66a07fc6217d79564e8602b11bd75a
