### ISSUE TITLE
Documentation: flag --experimental_enable_runfiles is not documented

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#11421]
### Description of the problem / feature request:

Bazel [Command-Line Reference](https://docs.bazel.build/versions/master/command-line-reference.html) misses the flag **--experimental_enable_runfiles**

### What's the output of `bazel info release`?

3.1.0

**Comment by aiuto** [comment]
The feature seems to be related to #9248.
It is not clear if we should document it, remove it, or flip it.
But... in general, there is no promise of documentation for experimental features. They are strictly use at your own risk, and it is possible to change their behavior at any commit.

**Comment by konste** [comment]
This flag enables runfiles symlinks on Windows. It exists for a couple years already and is very stable and useful, making runfiles support uniform across platforms. I would definitely prefer it to become the default and the flag removed, but in the short term a couple lines in the command line reference would be nice, just for discoverability.

**Comment by philwo** [comment]
@meteorcloudy Could you please have a look and advise what you think the blockers are for flipping this flag and removing it?

If you think we can enable it by default, I'd like to ask @mai93 to look into this. :)

**Comment by meteorcloudy** [comment]
This flag has already been renamed to --enable_runfiles and documented at https://docs.bazel.build/versions/master/command-line-reference.html#flag--enable_runfiles

We cannot flip its default value because creating file symlink still requires admin right or turning on developer mode on Windows. This will just continue to be a feature of Bazel on Windows.

**Comment by konste** [comment]
Do I understand it right that after flipping and removal of this flag runfiles on Windows are going to be controlled by the same flag `--enable_runfiles` as on other platforms? If so I support the move to flip and remove it.

**Comment by meteorcloudy** [comment]
`--experimental_enable_runfiles` is the [old name](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/config/CoreOptions.java;l=722?q=experimental_enable_runfiles&ss=bazel) of `--enable_runfiles`, I think we can just remove it.

**Comment by konste** [comment]
Ah, that actually clears things up. The fact that Bazel still accepts `--experimental_enable_runfiles` confused me and was the reason to open this issue. Indeed it should be removed.

**Comment by meteorcloudy** [comment]
Great, I'll send a change to remove the old flag, thanks for reporting this issue!
