### ISSUE TITLE
cfg must be either 'host' or 'target'

### ISSUE THREAD

**Issue by mengk007** [bazelbuild/bazel#11427]
(base) root@freevoice:/opt/tensorflow-1.15# bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --incompatible_disallow_filetype=false
WARNING: The following configs were expanded more than once: [cuda, using_cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=240
INFO: Reading rc options for 'build' from /opt/tensorflow-1.15/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include
INFO: Reading rc options for 'build' from /opt/tensorflow-1.15/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/local/anaconda3/bin/python --action_env PYTHON_LIB_PATH=/usr/local/anaconda3/lib/python3.7/site-packages --python_path=/usr/local/anaconda3/bin/python --config=xla --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda --action_env TF_CUDA_COMPUTE_CAPABILITIES=7.5 --action_env GCC_HOST_COMPILER_PATH=/usr/bin/gcc --config=cuda --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:xla in file /opt/tensorflow-1.15/.tf_configure.bazelrc: --define with_xla_support=true
INFO: Found applicable config definition build:cuda in file /opt/tensorflow-1.15/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file /opt/tensorflow-1.15/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:cuda in file /opt/tensorflow-1.15/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file /opt/tensorflow-1.15/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
ERROR: /root/.cache/bazel/_bazel_root/b954ea92673f80e3adb16ea9f62b377b/external/io_bazel_rules_closure/closure/compiler/closure_js_deps.bzl:82:17: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/b954ea92673f80e3adb16ea9f62b377b/external/io_bazel_rules_closure/closure/compiler/closure_js_deps.bzl", line 78
		rule(implementation = _impl, attrs = {"...")}, ..."})
	File "/root/.cache/bazel/_bazel_root/b954ea92673f80e3adb16ea9f62b377b/external/io_bazel_rules_closure/closure/compiler/closure_js_deps.bzl", line 82, in rule
		attr.label_list(cfg = "data", allow_files = True)
cfg must be either 'host' or 'target'.
ERROR: error loading package '': in /opt/tensorflow-1.15/tensorflow/workspace.bzl: in /root/.cache/bazel/_bazel_root/b954ea92673f80e3adb16ea9f62b377b/external/io_bazel_rules_closure/closure/defs.bzl: Extension file 'closure/compiler/closure_js_deps.bzl' has errors
ERROR: error loading package '': in /opt/tensorflow-1.15/tensorflow/workspace.bzl: in /root/.cache/bazel/_bazel_root/b954ea92673f80e3adb16ea9f62b377b/external/io_bazel_rules_closure/closure/defs.bzl: Extension file 'closure/compiler/closure_js_deps.bzl' has errors
INFO: Elapsed time: 0.435s

Bazel version 0.26.1
Tensorflow version 1.15.0

**Comment by aiuto** [comment]
There is not enough information here to act on. 
This is an old version of bazel and an old version of tensorflow, with an unknown WORKSPACE file and an unknown OS. Have you tried more recent releases of each?

**Comment by jin** [comment]
Please reopen the issue on the TF repository. 

```
"/root/.cache/bazel/_bazel_root/b954ea92673f80e3adb16ea9f62b377b/external/io_bazel_rules_closure/closure/compiler/closure_js_deps.bzl", line 82, in rule
attr.label_list(cfg = "data", allow_files = True)
cfg must be either 'host' or 'target'.
```

The problem comes from a transitive dependency in an (outdated?) closure compiler ruleset.
