### ISSUE TITLE
ctx.info_file and ctx.version_file are not documented

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#11422]
[Rule context reference page](https://docs.bazel.build/versions/master/skylark/lib/ctx.html) misses members **ctx.info_file** and **ctx.version_file** which are essential parts of the Workspace Status feature. Also there is no example how to read **bazel-out/stable-status.txt** or **bazel-out/volatile-status.txt** which are another moving parts of the same feature. 

### What's the output of `bazel info release`?

3.1.0

**Comment by laurentlb** [comment]
Duplicate with https://github.com/bazelbuild/bazel/issues/9363
