### ISSUE TITLE
cc_library and cc_import do not propagate runfiles from their input to the output

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#11425]
### Description of the problem / feature request:

Contrary to reasonable expectations the rules such as **cc_library** and **cc_import** do not propagate the runfiles from their inputs to the output. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I expected runfiles from the transitive dependencies to propagate through the build graph to dependent targets. For instance, I expected cc_test to collect runfiles from all its direct and transitive dependencies. For some reason I observe that cc_import and cc_library only include runfiles specified in their own **data** attribute, but runfiles which come from **srcs** or **shared_library** are dropped. If this behavior is by design it needs to be documented. If it is not by design I can provide a repro.

### What operating system are you running Bazel on?

Linux, Mac, Windows.

### What's the output of `bazel info release`?

3.1.0

**Comment by oquenchil** [comment]
Please provide a repro.

**Comment by konste** [comment]
@oquenchil here you go: https://github.com/Bazel-snippets/cc_library_repro_2
For your convenience the repro is tailored for Linux. Build command is `bazel build hello-world`.
There are four build rules involved, each adding one `data` file. In the output you can only see data files 3 and 4. 1 and 2 are lost.
