### ISSUE TITLE
Document that genrule has implicit dependencies to environment variables such as PATH which will cause it to rerun when those variables change.

### ISSUE THREAD

**Issue by philbinj** [bazelbuild/bazel#1142]
Please see https://groups.google.com/forum/#!msg/bazel-discuss/amRCj3ZQqUI/r4ddp_CYAQAJ for details.

**Comment by mhlopko** [comment]
Hello Florian and Klaus, is this still expected to be done in 0.5? Should we bump (or remove?) the milestone?
