### ISSUE TITLE
Implement Starlark Builtin Injection

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#11437]
[Design doc](https://docs.google.com/document/d/1GW7UVo1s9X0cti9OMgT3ga5ozKYUWLPk9k8c4-34rC4/edit#heading=h.e2vec9j9h1s9)

**Comment by alandonovan** [comment]
Status update: this work is underway.

**Comment by brandjon** [comment]
Status update: This is implemented, just need to flip the flag and remove the code path where injection is disabled. Then we can start migrating native logic to Starlark.

**Comment by brandjon** [comment]
Status update: This (internal) feature is enabled and we can proceed to cleanup old code paths.

**Comment by brandjon** [comment]
Nothing has changed on this project since the update last year. But we should at least remove the flag, since builtins injection is now an essential and mandatory piece of Bazel.

There's a bunch of minor TODOs that reference this issue so I'll leave it open for the moment.
