### ISSUE TITLE
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

### ISSUE THREAD

**Issue by LovelyBuggies** [bazelbuild/bazel#11431]
### Description of the problem request:

I am using Catalina on MacOS. When I follow the installation guide and use `curl -LO https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel-3.1.0-installer-darwin-x86_64.sh`, an error is thrown:

```bash
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
```

Any suggestions to deal with it?

**Comment by meisterT** [comment]
Can you repeat the command with `-v`?

Did you by any chance set `https_proxy`?

You can alternatively also download the file in a browser or with `wget`.

**Comment by LovelyBuggies** [comment]
@meisterT Thanks! But still not sure how to figure it out.

- `curl -LO -v ...` does not help :(

- how can i set https_proxy?

- no `wget` provided in MacOS Catalina (do you expect me to use `brew install wget`)?

**Comment by aiuto** [comment]
This is not a bazel problem. The curl command works for me on catalina, so the fact that it does not for you indicates that there is something different about your network configuration.

It could be that you are sitting behind a MITM-ing transparent proxy that attempts to decrypt and log all traffic.

What happens if you just type that URL into a browser window? That should download with no problems.

**Comment by LovelyBuggies** [comment]
> What happens if you just type that URL into a browser window?

It downloads the file as expected.

But if I do it in this way (i.e., downloading from browser, `chmod`, and then run the installer), I will get `“bazel-real” cannot be opened because the developer cannot be verified` as mentioned [there](https://docs.bazel.build/versions/master/install-os-x.html#step-3-run-the-installer).

**Comment by LovelyBuggies** [comment]
@aiuto Everytime I tried `./bazel-3.1.0-installer-darwin-x86_64.sh --user`, it asked for permission. After I gave it to `bazel-real`, the request is thrown out again in the next time. And I tried `brew install bazelbuild/tap/bazel` after `brew tap`, it throws `curl: (7) Failed to connect to releases.bazel.build port 443: Operation timed out`. I believe there is something wrong with my network, but not sure how to figure it out.

**Comment by LovelyBuggies** [comment]
A

> > What happens if you just type that URL into a browser window?
> 
> It downloads the file as expected.
> 
> But if I do it in this way (i.e., downloading from browser, `chmod`, and then run the installer), I will get `“bazel-real” cannot be opened because the developer cannot be verified` as mentioned [there](https://docs.bazel.build/versions/master/install-os-x.html#step-3-run-the-installer).

Alright, I have to `sudo spctl --master-disable` for convenience.

**Comment by meisterT** [comment]
What's the output when you run curl with `v`?

What's the output of `env | grep -i http`?

**Comment by LovelyBuggies** [comment]
> What's the output when you run curl with `v`?

```bash
Trying 52.74.223.119...
* TCP_NODELAY set
* Connected to github.com (52.74.223.119) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
... ... ...
< Content-Disposition: attachment; filename=bazel-3.1.0-installer-darwin-x86_64.sh
< Accept-Ranges: bytes
< Content-Type: application/octet-stream
< Content-Length: 39400250
< Server: AmazonS3
< 
  0 37.5M    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0{ [16360 bytes data]
  0 37.5M    0  153k    0     0   5250      0  2:05:04  0:00:29  2:04:35  6683
```

> What's the output of `env | grep -i http`?

No output.

**Comment by meisterT** [comment]
Does the output end there? I don't see the error message that you pasted in the first comment.

**Comment by LovelyBuggies** [comment]
> Does the output end there? I don't see the error message that you pasted in the first comment.

@meisterT I re-run with `-v` and it went well this time, thanks for your help!
