### ISSUE TITLE
Bazel is not picking up changes to PATH when running genrule targets while the server is running.

### ISSUE THREAD

**Issue by philbinj** [bazelbuild/bazel#1143]
Bazel will only pickup PATH changes when the server has shutdown.

Please see https://groups.google.com/forum/#!msg/bazel-discuss/amRCj3ZQqUI/r4ddp_CYAQAJ for details.

**Comment by dslomov** [comment]
@aehlig wdyt?

**Comment by damienmg** [comment]
This is fixed at HEAD, use --action_env PATH
