### ISSUE TITLE
Add suffix option to output_user_root

### ISSUE THREAD

**Issue by moroten** [bazelbuild/bazel#11435]
### Description of the feature request:

Please add an option to set `--output_user_root` in `~/.bazelrc`, but still override it in each Bazel invocation using a suffix to the already given `--output_user_root`.

### Feature requests: what underlying problem are you trying to solve with this feature?

Setting `--output_user_root=C:/build` is useful under Windows to reduce path length. Therefore, it is sensible to set that in user or system wide `.bazelrc`. Another use case is to point it to a specific storage, e.g. `/tmp` or a fast disk.

I've also observed use cases where I would like to start a second Bazel invocation from the same workspace, e.g. during long running `bazel run` or `bazel test`. Another example is to avoid discarding the analysis cache when switching configurations, even if not running in parallel. In these cases, I would just like to add a suffix to `--output_user_root` and not having to look it up in `~/.bazelrc`. (A discarding analysis cache can mean minutes of lost time the next build.)

###  Have you found anything relevant by searching the web?

#4248 is related.

### Any other information, logs, or outputs that you want to share?

https://github.com/bazelbuild/bazel/pull/11348 is a quick implementation of `--output_base_suffix`, but a design that also fits #4248 would be better.

**Comment by aiuto** [comment]
@moroten Just to be clear, this is purely a convenience, not enabling any new capability, right?

**Comment by aiuto** [comment]
Pressed too far left

**Comment by moroten** [comment]
> @moroten Just to be clear, this is purely a convenience, not enabling any new capability, right?

Correct. Convenience for both users and CI machinery, avoiding wrapper scripts around Bazel.
