### ISSUE TITLE
Add support for --incompatible_use_java_tools_beta_release flag for non disruptive way to bump java tool dependencies

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#11446]
Java tools are decoupled from Bazel distribution and downloaded from java_tools repository.

If some of the tools is updated, the archive name is changed in Bazel and new Bazel release is conducted. If, however, new tool has some breaking changes, then the upgrade needs to be rolled back.

To make user experience with upgrading tools less disruptive but still not unnecessary procrastinate releases of important Java tools like `javac` and Error Prone `--incompatible_use_java_tools_beta_release` should be added and CI-job should be set up to check all downstream projects against upcoming `java_tools` release.

**Comment by philwo** [comment]
I don't think we'll do this, the complexity of doing migrations between java_tools releases like that isn't worth the gain.
