### ISSUE TITLE
Android Test Runtime failed to load phonenumbers data from Robolectric's `android-all` due to class loading issue

### ISSUE THREAD

**Issue by ThomasCJY** [bazelbuild/bazel#11445]
### Description of the problem / feature request:
Android Unit Tests using `android.telephony.PhoneNumberUtils` are failing in bazel. The root cause is that bazel test runner is not loading the `org_robolectric_android_all` correctly. 

In my following example, I am using [robolectric-bazel](https://github.com/robolectric/robolectric-bazel) for the robolectric rule. It will package all the available versions into classpath so that in the test target's runfile we can see something like
```
CLASSPATH="
......
:${RUNPATH}../org_robolectric_android_all_9_robolectric_4913185_2/android-all-9-robolectric-4913185-2.jar
:${RUNPATH}../org_robolectric_android_all_8_1_0_robolectric_4611349/android-all-8.1.0-robolectric-4611349.jar
.... // all other versions for android-all
"
```
In the [robolectric.property](https://github.com/ThomasCJY/bazel_example/blob/master/android_local_test/src/test/resources/robolectric.properties#L1) file, we are defining `sdk=21`, that is, using android 5.0 in test runtime. However, after running the test we can see it starts to fail:

```
java.lang.IllegalStateException: empty metadata: /com/android/i18n/phonenumbers/data/PhoneNumberMetadataProto_US
	at com.android.i18n.phonenumbers.MultiFileMetadataSourceImpl.loadMetadataFromFile(MultiFileMetadataSourceImpl.java:115)
	at com.android.i18n.phonenumbers.MultiFileMetadataSourceImpl.getMetadataForRegion(MultiFileMetadataSourceImpl.java:80)
	at com.android.i18n.phonenumbers.PhoneNumberUtil.getMetadataForRegion(PhoneNumberUtil.java:1976)
	at com.android.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:2826)
	at com.android.i18n.phonenumbers.PhoneNumberUtil.parseAndKeepRawInput(PhoneNumberUtil.java:2719)
	at com.android.i18n.phonenumbers.PhoneNumberUtil.parseAndKeepRawInput(PhoneNumberUtil.java:2708)
	at android.telephony.PhoneNumberUtils.formatNumber(PhoneNumberUtils.java:1459)
```

After digging into it, I found out that there is an issue on class loading stage for test runtime. In the above example, the exception will be gone if we define `sdk=28` in the [robolectric.property](https://github.com/ThomasCJY/bazel_example/blob/master/android_local_test/src/test/resources/robolectric.properties#L1) file. And the reason is that by default `:${RUNPATH}../org_robolectric_android_all_9_robolectric_4913185_2/android-all-9-robolectric-4913185-2.jar`, which is the jar for android sdk 28, is ranked as the first robolectric android-all version in the CLASSPATH. For unknown reason, the classloading mechanism in bazel test runtime will take the order of CLASSPATH into account and load android classes from sdk 28 regardless of the definition in the properties file. 

In order to verify my theory, I kept the `sdk=21` in the `robolectric.properties` file, updated the test runfile to put `:${RUNPATH}../org_robolectric_android_all_5_0_2_r3_robolectric_r0/android-all-5.0.2_r3-robolectric-r0.jar` before all other robolectric_android_all files so that it is listed as the first in the classpath. Then I triggered the test using `exec` subcommand and the test passed. That means my theory for the root cause is right.

Should we only keep the robolectric_android_all version that is specified in `robolectric.properties` file in `CLASSPATH`? Or are we supposed to keep all of them as it is right now, and fix the issue in classloading stage?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Example test code: https://github.com/ThomasCJY/bazel_example/blob/master/android_local_test/src/test/java/com/example/bazel/RoboTest.java
Under `android_local_test` run `bazelisk test //src/test:main_activity_test`

### What operating system are you running Bazel on?
macos 10.15.4

**Comment by jongerrish** [comment]
It's interesting that all the android-all jars are on the classpath, is this the test runtime system classpath?

In theory, none of them should be on the classpath since RobolectricTestRunner is _supposed_ to load the correct android-all jar through a custom sandboxed classloader to create an isolated simulated device-like environment.

In actuality, I believe Robolectric requires the Android classes on the system classpath since there are some references to Android in the main RobolectricTestRunner (outside of the sandbox).

I think you should almost certainly remove all of those android-all jars from the system classpath and if you _have_ to pick one of them, maybe prefer the latest version?

**Comment by ThomasCJY** [comment]
close this since it has been fixed by https://github.com/robolectric/robolectric-bazel/pull/10
