### ISSUE TITLE
Documentation Navigation

### ISSUE THREAD

**Issue by marleypowell** [bazelbuild/bazel#11459]
Documentation URL: https://docs.bazel.build/versions/master/index.html
The documentation url redirects to this message `<script> window.location.replace("/versions/3.1.0/bazel-overview.html");`

**Comment by aiuto** [comment]
@Wyverald  Is there a chance that c9b9b4bc4f2d2f629ba76d083b22ed847b89bde8 
broke navigation.

**Comment by gregestren** [comment]
A rollback is in progress that should restore state. ETA ~30 mins.

**Comment by aiuto** [comment]
Filed #11462
