### ISSUE TITLE
'IllegalStateException` creating a symlink via `ctx.actions`

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#11453]
### Description of the problem

Attempting to create a symlink that points to the output of another rule causes an `IllegalStateException` to be thrown.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have attached a zip that reliably causes the problem. The `.bazelversion` is the one that I used for testing, but it's pretty recent.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

`release 3.2.0rc1`

[symlink-bug-repo.zip](https://github.com/bazelbuild/bazel/files/4658369/symlink-bug-repo.zip)

**Comment by aiuto** [comment]
Guessing local-exec, but it could be someone team's problem.

OTOH... I'm not sure if this is legitimate anyway. 
@shs96c What are you trying to accomplish that requires this symlink?

**Comment by shs96c** [comment]
I'm attempting to implement `alias` in Starlark so that I can use the aliases in `test_suite`.

**Comment by jmmv** [comment]
Could you post the whole stacktarce that you get please? (Can't get to try your repro right now, but that'll help anyway in looking at this issue.)

**Comment by Yannic** [comment]
This looks like an issue with unresolved symlinks, which are experimental. Repos with `bazel test`, but not with `bazel build`.

@shs96c Since the target is an artifact, I recommend using `target_file = ctx.file.actual` instead of `target_path`. `target_file` also doesn't require the experimental flag. That said, at least your repro `alias` will likely fail if the test requires runfiles in addition to the binary.

**Comment by tetromino** [comment]
I'm unable to reproduce the IllegalStateException: when I run `bazelisk test --experimental_allow_unresolved_symlinks all-tests` (i.e. using the same 3.2.0rc1 release you used) in the provided repro, all I get is an ordinary test failure:
```
INFO: Analyzed target //:first (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
FAIL: //:first (see /private/var/tmp/_bazel_arostovtsev/da303bb0daed9fbd509c33333e093b33/execroot/temp/bazel-out/darwin-fastbuild/testlogs/first/test.log)
Target //:first up-to-date:
  bazel-bin/exe
INFO: Elapsed time: 0.160s, Critical Path: 0.08s
INFO: 2 processes: 2 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//:first                                                                 FAILED in 0.0s
  /private/var/tmp/_bazel_arostovtsev/da303bb0daed9fbd509c33333e093b33/execroot/temp/bazel-out/darwin-fastbuild/testlogs/first/test.log

INFO: Build completed, 1 test FAILED, 2 total actions
```

What is the exact reproduction step? Is the failure transient and you only get it on some small percentage of the runs? Do you have another .bazelrc in your home directory or elsewhere that adds more build flags?

**Comment by tetromino** [comment]
Also, the full error output, test log, and server log (see `bazel info server_log`) would be very helpful in case this is an "only fails on some specific machines" sort of error.

**Comment by jmmv** [comment]
Given that @tetromino couldn't reproduce this issue with your same version of Bazel and the same scenario... we'll need more data. Happy to reopen this once we have it.
