### ISSUE TITLE
`test_suite` tests should be configurable

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#11455]
### Description of the problem / feature request:

The `tests` parameter for `test_suite` should be configurable. This would allow us to use command line flags and other conditions to construct test suites.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```py
test_suite(
  name = "all-tests",
  tests = select({
    "//conditions:default": [],
  }),
)
```

### What's the output of `bazel info release`?

3.1.0

### Other info

I'm aware that there's some work coming to do with skipping incompatible targets in #10945 but that's not the same thing at all. 

I also suspect that this rule is inexpressible in StarLark and the existing Bazel APIs, and so replacing with a macro or custom rule is also not an option.

**Comment by sdtwigg** [comment]
Unfortunate, for technical reasons on how top-level target pattern expression and test discovery is done, this is unlikely to be implementable at this time.

test_suites are expanded both during analysis time as a standard rule target but also during the loading phase when deciding the top-level targets to be expanded. The loading phase classically does not consider the configuration. Changing this target pattern expression logic has historically been error prone so it is not likely this will be considered worth the effort.

**Comment by ulfjack** [comment]
IIRC, there's an option to disable the expansion of `test_suite` rules during loading. That doesn't help immediately, but maybe Bazel should aim to enable that by default at some point?

**Comment by sdtwigg** [comment]
I'm unsure if that would be enough. I think ultimately there will be an issue for as long as the loading phase is principally responsible for determining what tests are run.

Drilling through https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/skyframe/TargetPatternPhaseFunction.java#L77.

`--expand_test_suites` is respected when determining `expandedTests` and that does lead into `targetLabels` in `TargetPatternPhaseValue` (which is often called `loading[Phase]Result` by callers) and `targets` in the `TargetParsingCompleteEvent`.

The `determineTests` function seems to expand test suites while ignoring the flag and is called to construct `testTargets`. `testTargets` use depends on other flags but often also gets dumped into targets and will always fill `testsToRun` when relevant.
