### ISSUE TITLE
bazel build target without specify `--config` param

### ISSUE THREAD

**Issue by yfheng** [bazelbuild/bazel#11466]
Due to different configuration for different targets, current I need run command `Bazel build --config=xxx //{target}` to build target, is there any way that I can give target related config information, so that I could build target just typing `Bazel build //{target}` which Bazel already know which config he should use

**Comment by aiuto** [comment]
You can do that with user defined transitions.
https://docs.bazel.build/versions/master/skylark/config.html
https://github.com/bazelbuild/examples/tree/master/rules/starlark_configurations/attaching_transitions_to_rules
