### ISSUE TITLE
experimental_spawn_scheduler leads to "undeclared inclusion(s)" error

### ISSUE THREAD

**Issue by dsilvasc** [bazelbuild/bazel#11464]
### Description of the problem:

Running a remote+local protobuf build with `--experimental_spawn_scheduler` fails with "undeclared inclusion(s) in rule '@com_google_protobuf//:protobuf'".  The build works without that flag, either in remote or in local mode.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Repro contents at https://github.com/dsilva/bazel-issue-11464

Remote worker started on a linux host with:
```bash
curl -LO https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel-3.1.0-dist.zip
unzip bazel-3.1.0-dist.zip
env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh
output/bazel  build src/tools/remote:worker
mkdir /tmp/cas
mkdir /tmp/work
bazel-bin/src/tools/remote/worker --work_path=/tmp/work --listen_port=8080 --cas_path=/tmp/cas --debug
```

Bazel execution inside a docker container:
```bash
git clone https://github.com/dsilva/bazel-issue-11464
cd bazel-issue-11464
docker run -it -v $(pwd):/src/workspace:delegated -v /tmp/bazel_build_output:/tmp/build_output:delegated -w /src/workspace  l.gcr.io/google/bazel:3.1.0 --output_user_root=/tmp/build_output build --config=remote  --config=debug ...
```

Error output:

```
ERROR: /tmp/build_output/a08c2e4811c846650b733c6fc815a920/external/com_google_protobuf/BUILD:209:1: undeclared inclusion(s) in rule '@com_google_protobuf//:protobuf':
this rule is missing dependency declarations for the following files included by 'external/com_google_protobuf/src/google/protobuf/any.cc':
  '/usr/local/lib/clang/11.0.0/include/stdarg.h'
  '/usr/local/lib/clang/11.0.0/include/stddef.h'
  ...
```

Full error output: https://gist.github.com/dsilvasc/5905953c234cc3769a22ff53b76585ee

explain.txt:
```
Build options: --config=remote --cpu=k8 --jobs=1 --host_javabase=@bazel_toolchains//configs/ubuntu16_04_clang/1.2:jdk8 --javabase=@bazel_toolchains//configs/ubuntu16_04_clang/1.2:jdk8 --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8 --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8 --crosstool_top=@bazel_toolchains//configs/ubuntu16_04_clang/1.2/bazel_0.25.0/default:toolchain --action_env='BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1' --extra_toolchains=@bazel_toolchains//configs/ubuntu16_04_clang/1.2/bazel_0.25.0/cpp:cc-toolchain-clang-x86_64-default --extra_execution_platforms=@bazel_toolchains//configs/ubuntu16_04_clang/1.2:rbe_ubuntu1604 --host_platform=@bazel_toolchains//configs/ubuntu16_04_clang/1.2:rbe_ubuntu1604 --platforms=@bazel_toolchains//configs/ubuntu16_04_clang/1.2:rbe_ubuntu1604 --spawn_strategy=remote --strategy='Javac=remote' --strategy='Closure=remote' --strategy='Genrule=remote' --genrule_strategy=remote --define='EXECUTOR=remote' --remote_executor=grpc://172.25.76.135:8080 --nogoogle_default_credentials --noremote_accept_cached --experimental_spawn_scheduler --internal_spawn_scheduler --spawn_strategy=dynamic --config=debug --verbose_failures --explain=explain.txt --verbose_explanations --toolchain_resolution_debug --subcommands=1
Executing action 'BazelWorkspaceStatusAction stable-status.txt': unconditional execution is requested.
Executing action 'Compiling external/com_google_protobuf/src/google/protobuf/any.cc': no entry in the cache (action is new).
```

### What operating system are you running Bazel on?

macos catalina 10.15.4, docker desktop for mac 2.3.0.2, docker engine 19.03.8, docker image l.gcr.io/google/bazel:3.1.0

### What's the output of `bazel info release`?

release 3.1.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/dsilva/bazel-issue-11464.git
295f566dc8322b78118b7efa4033708dd6cdd4d6
295f566dc8322b78118b7efa4033708dd6cdd4d6

###  Have you found anything relevant by searching the web?

Nothing related to both experimental_spawn_scheduler + undeclared inclusions.

**Comment by jmmv** [comment]
Note that enabling the dynamic scheduler can have side-effects on strategy selection. It is likely that the manual runs without dynamic scheduling don't match exactly and thus work (but I can't tell because I don't see the former in the snippets above, I think). See the `--dynamic_local_strategy` and `--dynamic_remote_strategy` flags.

Could you double-check if that's the issue?

**Comment by dsilvasc** [comment]
Thanks for looking into this.  I added the following to my .bazelrc, but it still fails the same way:

```
build:remote --dynamic_local_strategy=worker,sandboxed,local
build:remote --dynamic_remote_strategy=remote
```

**Comment by jmmv** [comment]
Could you try building the same thing, fully locally, with and without the sandbox?

**Comment by dsilvasc** [comment]
local build on macOS without docker succeeds: https://gist.github.com/dsilvasc/4984d272edd4619b3d03758eee070ce1

remote build from macOS without docker and a remote linux worker fails to find /usr/local/bin/clang: 
https://gist.github.com/dsilvasc/c6b09c3201d23ce34f5cf0f0137052e6

local build on docker desktop for mac succeeds:
https://gist.github.com/dsilvasc/a382eca8c08dbb22c77c5bd7cec07f91

remote build on docker desktop for mac fails:
https://gist.github.com/dsilvasc/335cf181bf6d2ff95637ec6be4e94398

**Comment by jmmv** [comment]
This sounds like a configurability issue. I'm not sure to what extent a Mac host can be mixed with a remote Linux worker today, nor what kind of contortions are needed to make that work (if at all). I know there are still missing features on the platforms side to make that work correctly today.

On one of your failure cases, Bazel is trying to use a path from one platform on another and thus failing because of execution platform mismatches. On the other, it seems that it's confusing the C++ toolchain configuration and failing to whitelist the right system-wide headers.

**Comment by dsilvasc** [comment]
Yeah, I noticed some open issues about remote builds not working when the host and remote OS are different.  That's why I'm running it inside docker -- so both the host and remote worker are linux.

**Comment by katre** [comment]
I am working on implementing the [Execution Platforms and Strategies](https://docs.google.com/document/d/1U9HzdDmtRnm244CaRM6JV-q2408mbNODAMewcGjnnbM/edit#) design that covers a lot of the incompatibilities between execution platform and execution strategies.

However, that doesn't remove the invariant that for the dynamic strategy, the action generated has to work both locally and remotely: this implies that the same execution platform has to be used for both. We don't have any plans now to support mixed mac/linux local/remote dynamic builds, although we should be able to better support each of those, and to show a better error when the build cannot work like that.

**Comment by dsilvasc** [comment]
For macs, would it be preferable to use fully remote builds or to run bazel inside a linux vm (for example with docker for mac) with the dynamic strategy?

**Comment by katre** [comment]
I don't actually know, we'll need to profile some sample builds and see. Well, someone with a Mac handy (@jmmv ?) will need to profile, once the changes are in.

**Comment by katre** [comment]
Closing this as out of date, please comment if this is still an issue.
