### ISSUE TITLE
Move docs generation to bazel-website repo

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#11462]
We should get doc building out of bazelbuild/bazel and moved to bazelbuild/bazel-website. This will decouple non-generated doc changes from Bazel-CI.

- it will allow doc changes to github first.
- it will make it easier to iterate on docs by decoupling 
- it will reduce the size of the bazel distribution (both files and dependencies)

Context: #11459 It is taking a ridiculous amount of time to roll back a docs breakage because of full Bazel CI.

cc: @floriographygoth @gregestren @jin

**Comment by jin** [comment]
Dupe this against https://github.com/bazelbuild/bazel/issues/8866?

**Comment by aiuto** [comment]
Yes. It is a dupe, but this one is better worded. I replaced that description with this one.
