### ISSUE TITLE
docs.bazel.build should reduce search scope to return more relevant results

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#11467]
There are two problems.

1. We let too much get indexed by web crawlers. We should prefer the current version over older versions, so older ones should be noindex.
https://support.google.com/webmasters/answer/93710?hl=en

2. Our internal search returns an answer from multiple versions. That is just confusing. E.g.
https://docs.bazel.build/search.html?cx=009927877080525621790%3A2pxlpaexqpc&cof=FORID%3A10&ie=UTF-8&q=transition#gsc.tab=0&gsc.q=transition&gsc.page=1

**Comment by floriographygoth** [comment]
Laurent fixed 2 a while ago. 
My understanding of 1 is that older versions are essentially read-only and we'd need to update the page headers with the noindex tag. Is there another way?

**Comment by aiuto** [comment]
I think no-index is the right method. This is just another of those little requirements to track in any pipeline rebuild.

**Comment by floriographygoth** [comment]
Okay. I think at this time we can't add noindex to our existing older docs, but I will add a note in the spreadsheet for infrastructure. Closing this out in the meantime as we resolved the issue of being able to filter results by version.
