### ISSUE TITLE
Bazel Query REPL

### ISSUE THREAD

**Issue by austince** [bazelbuild/bazel#11463]
### Description of the problem / feature request:

A Bazel query REPL

### Feature requests: what underlying problem are you trying to solve with this feature?

Running Bazel queries are great with the command line and hooking into other CLI tools, but creating the queries can be a lot of trial and error. A query REPL would be great for interactively querying the graph and, if possible, reusing variables in complicated query scripts.

###  Have you found anything relevant by searching the web?

Searched through issues, searched Google, came up with nothing. Has this idea been brought up before? 

If this is too big to fit here, I'm happy to email bazel-discuss@googlegroups.com as well.

**Comment by aiuto** [comment]
This is a reasonable feature to try to build. It seems like something that could be done as a standalone tool externally to Bazel, rather than into the code directly.

**Comment by austince** [comment]
Thanks for the reply @aiuto - yeah, I was thinking something like [ibazel](https://github.com/bazelbuild/bazel-watcher). What do you think would be the best way to get a prototype going?

**Comment by aiuto** [comment]
I guess to build it in your own github repository. Develop it until you
think it is worth sharing. Then advertise it on bazel-discuss. If it gets
traction, we can consider moving to the bazelbuild organization. But that
is not a prerequisite to having a useful and recommended tool.
