### ISSUE TITLE
sh_binary scripts can't find generated data when executed by Skylark action or genrule

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#1147]
Consider this repository https://github.com/dfabulich/wheres-my-data

There's a `data.txt` file in the `build_tools` directory, and a simple build script in `build_tools.sh` that accepts one CLI argument and copies `data.txt` to the given location.

data.txt:

```
data
```

build_tools.sh:

``` bash
#!/bin/bash
cp build_tools/data.txt $1
```

It's declared as a `sh_binary` in `build_tools/BUILD`.

``` python
sh_binary(
    name='build_tools',
    srcs=['build_tools.sh'],
    data=['data.txt'],
    visibility=['//visibility:public'],
)
```

There's a simple Skylark rule in `build_tools/example.bzl`; the example rule runs `build_tools` to generate a `%{name}.txt` file as output.

(EDIT: previously used the `command` parameter to `ctx.action`, which triggered issue #1192 as well as the current issue #1147; I've switched the example below to use `executable` instead.)

``` python
def _impl(ctx):
    ctx.action(
        executable = ctx.executable._build_tools,
        arguments = [ctx.outputs.text.path],
        outputs = [ctx.outputs.text],
    )

example = rule(
    implementation = _impl,
    attrs = {
        "_build_tools": attr.label(executable=True, allow_files=True, default=Label("//build_tools"))
    },
    outputs = {
        "text": "%{name}.txt",
    }
)
```

Finally, `foo/BUILD` declares a `foo` target with the `example` rule.

``` python
load('/build_tools/example', 'example')

example(
    name='foo',
)
```

When I `bazel build foo`, I expect it to succeed and generate `foo.txt`, and it _does_ succeed on OS X, but it fails on Linux, where the sandbox is enabled, with this error:

```
$ bazel build foo --verbose_failures
INFO: Found 1 target...
ERROR: /tmp/github/wheres-my-data/foo/BUILD:3:1: error executing shell command: 'bazel-out/local_linux-fastbuild/bin/build_tools/build_tools bazel-out/local_linux-fastbuild/bin/foo/foo.txt' failed: namespace-sandbox failed: error executing command
  (cd /home/bamboo/.cache/bazel/_bazel_bamboo/ac68465916372626e6b4e6f2ba11ef97/wheres-my-data && \
  exec env - \
  /home/bamboo/.cache/bazel/_bazel_bamboo/ac68465916372626e6b4e6f2ba11ef97/wheres-my-data/_bin/namespace-sandbox @/home/bamboo/.cache/bazel/_bazel_bamboo/ac68465916372626e6b4e6f2ba11ef97/wheres-my-data/bazel-sandbox/c76d9207-afd2-4fd5-a97c-cebd1a1e2303-0.params -- /bin/bash -c 'bazel-out/local_linux-fastbuild/bin/build_tools/build_tools bazel-out/local_linux-fastbuild/bin/foo/foo.txt').
cp: cannot stat 'build_tools/data.txt': No such file or directory
Target //foo:foo failed to build
```

**Comment by dfabulich** [comment]
You might notice that this bug bears similarity to #1136. I discovered it while trying to find a workaround for #1136. I'm nonetheless convinced that it's a different bug, because #1136 fails even on OS X after a `bazel clean`, whereas this bug #1147 never fails on OS X.

Furthermore, it's possible to workaround #1136 by replacing the Skylark rule with an equivalent `genrule`, like this:

```python
genrule(
    name='bar',
    tools=['//build_tools'],
    outs=['bar.txt'],
    cmd="$(location //build_tools) $@"
)
```

But `bazel build foo:bar` fails in this repo on Linux; whereas using a genrule to `bazel build foo:bar` in the #1136 repo doesn't fail.

**Comment by dfabulich** [comment]
This repo initially used the `command` parameter to `ctx.action`, so I tried switching it to use `ctx.action`'s `executable` parameter instead, to see if that helped.

Now the `_impl` function says:

```python
def _impl(ctx):
    ctx.action(
        executable = ctx.executable._build_tools,
        arguments = [
            ctx.outputs.text.path,
        ],
        outputs = [ctx.outputs.text],
    )
```

On Linux, this had no effect; `foo` continued to fail to build, with the same error message.

On OS X, this did seem to make `foo` build, but when I tried deleting the source file `data.txt` and replacing it with _generated_ data, like this, it failed again, even on OS X:

```python
sh_binary(
	name='build_tools',
	srcs=['build_tools.sh'],
	data=['data'],
	visibility=['//visibility:public'],
)

genrule(
	name='data',
	outs=['data.txt'],
	cmd="echo data > $@",
)
```

**Comment by dfabulich** [comment]
Aha! Switching `ctx.action` from `command` to `executable` _did_ help after all, but I didn't notice because it was being masked by another bug.

Adding a `find .` to the start of `build_tools.sh` showed me that the `runfiles` were, in fact, being incorporated into the sandbox, but since the working directory for the script was incorrect, the script couldn't find its data in `build_tools/data.txt` as it expected.

```
.
./build_tools
./build_tools/build_tools.sh
./bazel-out
./bazel-out/local_linux-fastbuild
./bazel-out/local_linux-fastbuild/bin
./bazel-out/local_linux-fastbuild/bin/build_tools
./bazel-out/local_linux-fastbuild/bin/build_tools/build_tools
./bazel-out/local_linux-fastbuild/bin/build_tools/build_tools.runfiles
./bazel-out/local_linux-fastbuild/bin/build_tools/build_tools.runfiles/build_tools
./bazel-out/local_linux-fastbuild/bin/build_tools/build_tools.runfiles/build_tools/build_tools
./bazel-out/local_linux-fastbuild/bin/build_tools/build_tools.runfiles/build_tools/data.txt
./bazel-out/local_linux-fastbuild/bin/build_tools/build_tools.runfiles/build_tools/build_tools.sh
./bazel-out/local_linux-fastbuild/bin/foo
```

Thus, I can get `bazel build foo` to pass if I use this `_impl` for my `example` rule:

```python
def _impl(ctx):
    ctx.action(
        executable = ctx.executable._build_tools,
        arguments = [
            ctx.outputs.text.path,
        ],
        outputs = [ctx.outputs.text],
    )
```

And I use this `build_tools.sh` instead:

```bash
#!/bin/bash
START_DIR=`pwd`
OUTPUT=$START_DIR/$1
cd ${BASH_SOURCE[0]}.runfiles
cp build_tools/data.txt $OUTPUT
```

That then breaks the script if `$1` is an absolute path, e.g. `bazel run build_tools -- /tmp/out.txt`

So one more hack to `build_tools.sh` fixes it to work both ways:

```bash
#!/bin/bash
START_DIR=`pwd`
OUTPUT=$1
if [ "${OUTPUT:0:1}" != "/" ]; then
        OUTPUT=$START_DIR/$1
fi
cd ${BASH_SOURCE[0]}.runfiles
cp build_tools/data.txt $OUTPUT
```

That also fixes the `genrule` build `bazel build foo:bar`.

**Comment by dfabulich** [comment]
Er, this is probably less hacky.

```bash
#!/bin/bash
RUNFILES=${BASH_SOURCE[0]}.runfiles
cp $RUNFILES/build_tools/data.txt $1
```

**Comment by damienmg** [comment]
Yes we have a problem of finding runfiles. This has been a headache for a
long time but we always find workarounds so never really got stressed to
work on it.

**Comment by dfabulich** [comment]
This bug started off as a mix of two issues; I've factored the issue with `ctx.action`'s `command` parameter out into a separate bug #1192.

**Comment by philwo** [comment]
> Adding a find . to the start of build_tools.sh showed me that the runfiles were, in fact, being incorporated into the sandbox, but since the working directory for the script was incorrect, the script couldn't find its data in build_tools/data.txt as it expected.

I'm curious about this - the working directory of executables should be the same, no matter if you use the sandbox or not.

**Comment by EdSchouten** [comment]
Pretty odd. Also running into this issue. For some weird reason, I can get it to work if I first place the `data` dependency in a `sh_library()` and then drag that `sh_library()` in as `data` of the `sh_binary()`.

**Comment by jscheid-ventana** [comment]
Hitting this also in 0.25.0.
Note that the bug does not exist when doing the same thing (generated file in data) in an equivalent py_binary.

**Comment by chrismcbride** [comment]
Also running in to this issue on 0.28.1, before I could work around it by manually collecting the default_runfiles and passing that as an input to the action, but now that --incompatible_no_support_tools_in_action_inputs has been flipped, that is no longer allowed since the default_runfiles of a sh_binary target contain executables.

**Comment by kposborne** [comment]
> Pretty odd. Also running into this issue. For some weird reason, I can get it to work if I first place the `data` dependency in a `sh_library()` and then drag that `sh_library()` in as `data` of the `sh_binary()`.

Thanks! Ran into this issue today in version 3.3.0, was able to work around it with this method.

**Comment by jmcmullan** [comment]
Still observing this issue in Bazel 5.1.0

**Comment by brandjon** [comment]
This should likely be dedupped against #12348, but I'll save that for whoever reviews these issues in detail.

**Comment by fmeum** [comment]
Pretty sure this was fixed in https://github.com/bazelbuild/bazel/commit/6f6d4cca36a3b64009ed9c8b3fb13cb3c7ed915a.
