### ISSUE TITLE
'failed: I/O exception during sandboxed execution: null' error when running tests using Bazel and remote caching

### ISSUE THREAD

**Issue by brianoh1979** [bazelbuild/bazel#11492]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

One of our customers running Bazel from remote caching of dependencies and testing is experiencing the following error when running test chunks via Bazel:

'failed: I/O exception during sandboxed execution: null' error 

### Feature requests: what underlying problem are you trying to solve with this feature?

Ensuring that these tests run in a stable fashion and not fail intermittently

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run bazel test //com/dummy:target using GCP remote caching.

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

release 1.2.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

I looked in GitHub issues: 'https://github.com/bazelbuild/bazel/issues' but this did not give an exact match for the issue. 

### Any other information, logs, or outputs that you want to share?

/home/brianoh/Documents/Document with log entries for Bazel Github case.odt

15:12:33 I: Started docker-compose run -e BASIC_OUTPUT=1 -e GOOGLE_STORAGE_CREDENTIALS -v /tmp/test-chunk-artifacts/<customer repo name>tests_bazel_test_chunks___services_ads_src_test_scala_com_<customer name>_<customer repo name>_adServer_ad_server_test_suite_AdServerUniversalTagTest_scala/try1/container-artifacts:/tmp/artifacts test-task test run --timeout=1800 <customer repo name>tests/bazel-test.chunks///services/ads/src/test/scala/com/<customer name>/<customer repo name>/adServer:ad_server_test_suite_AdServerUniversalTagTest.scala
15:12:34 E: Starting project_<customer repo name>-image_1_a1cfce47b369 ... 
15:12:34 E: Starting project_<customer repo name>-dev-storage-image_1_eee29f413682 ... 
15:12:35 E: [1A[2K
Starting project_<customer repo name>-dev-storage-image_1_eee29f413682 ... [32mdone[0m
[1BStarting project_temp-dev-storage_1_64035859b922      ... 
15:12:38 O: ------> Running chunk '<customer repo name>tests/bazel-test.chunks///services/ads/src/test/scala/com/<customer name>/<customer repo name>/adServer:ad_server_test_suite_AdServerUniversalTagTest.scala' with timeout 1800 seconds
15:12:38 O: Extracting Bazel installation...
15:12:41 O: Starting local Bazel server and connecting to it...
15:12:41 O: WARNING: ignoring LD_PRELOAD in environment.
15:12:44 O: INFO: Invocation ID: e7453d10-6a12-4ed7-88bb-d06e5ff8189b
15:12:44 O: Loading: 
15:12:44 O: Loading: 0 packages loaded
15:12:45 O: Loading: 0 packages loaded
15:12:46 O: Loading: 0 packages loaded
15:12:47 O: Loading: 0 packages loaded
15:12:53 O: Loading: 0 packages loaded
15:12:54 O: Loading: 0 packages loaded
15:12:55 O: Analyzing: target //services/ads/src/test/scala/com/<customer name>/<customer repo name>/adServer:ad_server_test_suite_AdServerUniversalTagTest.scala (1 packages loaded, 0 targets configured)
15:12:57 O: Analyzing: target //services/ads/src/test/scala/com/<customer name>/<customer repo name>/adServer:ad_server_test_suite_AdServerUniversalTagTest.scala (11 packages loaded, 6 targets configured)
15:12:59 O: Analyzing: target //services/ads/src/test/scala/com/<customer name>/<customer repo name>/adServer:ad_server_test_suite_AdServerUniversalTagTest.scala (88 packages loaded, 217 targets configured)
15:13:02 O: Analyzing: target //services/ads/src/test/scala/com/<customer name>/<customer repo name>/adServer:ad_server_test_suite_AdServerUniversalTagTest.scala (94 packages loaded, 240 targets configured)
15:13:04 O: Analyzing: target //services/ads/src/test/scala/com/<customer name>/<customer repo name>/adServer:ad_server_test_suite_AdServerUniversalTagTest.scala (114 packages loaded, 926 targets configured)
15:13:07 O: Analyzing: target //services/ads/src/test/scala/com/<customer name>/<customer repo name>/adServer:ad_server_test_suite_AdServerUniversalTagTest.scala (148 packages loaded, 1236 targets configured)
15:13:11 O: Analyzing: target //services/ads/src/test/scala/com/<customer name>/<customer repo name>/adServer:ad_server_test_suite_AdServerUniversalTagTest.scala (186 packages loaded, 1390 targets configured)
15:13:15 O: Analyzing: target //services/ads/src/test/scala/com/<customer name>/<customer repo name>/adServer:ad_server_test_suite_AdServerUniversalTagTest.scala (231 packages loaded, 1600 targets configured)
15:13:20 O: Analyzing: target //services/ads/src/test/scala/com/<customer name>/<customer repo name>/adServer:ad_server_test_suite_AdServerUniversalTagTest.scala (287 packages loaded, 2318 targets configured)
15:13:23 O: INFO: Analyzed target //services/ads/src/test/scala/com/<customer name>/<customer repo name>/adServer:ad_server_test_suite_AdServerUniversalTagTest.scala (311 packages loaded, 2559 targets configured).
15:13:23 O: INFO: Found 1 test target...
15:13:23 O: [0 / 121] [Prepa] BazelWorkspaceStatusAction stable-status.txt
15:13:29 O: [96 / 627] Compiling external/com_google_protobuf/src/google/protobuf/text_format.cc [for host]; 0s remote-cache ... (2 actions, 1 running)
15:13:36 O: [214 / 627] Compiling external/com_google_protobuf/src/google/protobuf/extension_set_heavy.cc [for host]; 0s remote-cache ... (2 actions, 1 running)
15:13:44 O: [709 / 1,002] Stamping manifest of @maven//:com_fasterxml_jackson_module_jackson_module_paranamer; 0s remote-cache ... (2 actions running)
15:13:53 O: [1,074 / 1,165] scala //shared/scala/service-common/src/main/scala/com/<customer name>/<customer repo name>/finagle/distributedTrace:distributedTrace; 0s remote-cache ... (2 actions, 1 running)
15:14:02 O: ERROR: /app/services/ads/src/test/scala/com/<customer name>/<customer repo name>/adServer/BUILD:142:1:  failed: I/O exception during sandboxed execution: null
15:14:02 O: Target //services/ads/src/test/scala/com/<customer name>/<customer repo name>/adServer:ad_server_test_suite_AdServerUniversalTagTest.scala up-to-date:
15:14:02 O:   /cache/bazel/output_base/execroot/<customer repo name>/bazel-out/k8-fastbuild/bin/services/ads/src/test/scala/com/<customer name>/<customer repo name>/adServer/ad_server_test_suite_AdServerUniversalTagTest.scala
15:14:02 O:   /cache/bazel/output_base/execroot/<customer repo name>/bazel-out/k8-fastbuild/bin/services/ads/src/test/scala/com/<customer name>/<customer repo name>/adServer/ad_server_test_suite_AdServerUniversalTagTest.scala.jar
15:14:02 O: INFO: Elapsed time: 83.076s, Critical Path: 8.47s
15:14:02 O: INFO: 753 processes: 753 remote cache hit.
15:14:02 O: FAILED: Build did NOT complete successfully
15:14:02 O: //services/ads/src/test/scala/com/<customer name>/<customer repo name>/adServer:ad_server_test_suite_AdServerUniversalTagTest.scala NO STATUS
15:14:02 O: 
15:14:02 O: Executed 0 out of 1 test: 1 was skipped.
15:14:02 O: FAILED: Build did NOT complete successfully
15:14:03 E: [1A[2K
Starting project_temp-dev-storage_1_64035859b922      ... [32mdone[0m
[1B[3A[2K
Starting project_<customer repo name>-image_1_a1cfce47b369             ... [32mdone[0m
[3B

**Comment by jmmv** [comment]
The only place where this can come from is: https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/sandbox/AbstractSandboxSpawnRunner.java;l=89 and I don't see how the cause passed to the exception construction (which I think is what's being shown as "null") could be possibly null.

You mention above that `bazel test //com/dummy:target` against GCP remote caching is a simple reproduction of this. I haven't been able to try it yet though (as I have no context on this). Is the failure deterministic? Could you try the same with a more recent Bazel version?

**Comment by tetromino** [comment]
The "I/O exception during sandboxed execution: null" message could arise if the *message* (not the exception object itself) of the IOException caught in AbstractSandboxSpawnRunner.exec() is null - see https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/actions/ExecException.java;l=65

**Comment by tetromino** [comment]
Unfortunately, without either a reproducer case that we can run or a backtrace or a specific error message (at minimum narrowing down which subclass of IOException got thrown!), we can't realistically diagnose this any further.

If you don't have permission to release a reproducer, would it be possible for your customer to get the Bazel server log immediately after hitting the error?  (You can obtain the log file path by running `bazel info server_log`; note that the log file changes when the server is stopped, so if they kill Bazel after getting the test failure, they may need to get a neighboring log file in the same directory.) Hopefully the relevant stack trace would be in the log file somewhere.

**Comment by jmmv** [comment]
We'll need more information to further debug this, as @tetromino found that there are too many places where this error might be coming from. If you can supply such information, we'll reopen this bug. Thanks!
