### ISSUE TITLE
Bazel unexpectedly ceases to function on Ubuntu 14.04

### ISSUE THREAD

**Issue by oweingrod** [bazelbuild/bazel#1149]
Have been using bazel on Ubuntu 14.04 for a number of tasks. Unfortunately, it seems that Bazel keeps...deleting itself? Or something like that.

After installing with the <bazelversionhere>.sh script and successfully running a few build processes, I return to my terminal to find that `bazel build` returns `bash- command bazel not found`. What gives? Is bazel not correctly being copied into my PATH? I'm confused as to why bazel sometimes functions wonderfully, but then other times stops working with no apparent indication.

**Comment by kchodorow** [comment]
What options are you running the installer with?  If you install it as root, it should be putting bazel at /usr/local/lib/bazel/bin/bazel and symlinking /usr/local/bin/bazel to that.  If you install it for your user, it's probably under ~/bin.  Can you track down where your binary is and check what the permissions are on it and run `file /path/to/your/bazel`?

**Comment by damienmg** [comment]
`which bazel`

`echo $PATH`

I suspect you are using different environment and your PATH change between the,

**Comment by damienmg** [comment]
friendly ping?

**Comment by damienmg** [comment]
Closing without activity. Ping back if you still need help.
