### ISSUE TITLE
IncompatibleClassChangeError when using Guava 1.7

### ISSUE THREAD

**Issue by helenaut** [bazelbuild/bazel#1150]
Hello! I run into a IncompatibleClassChangeError when trying to run java_tests while using Guava 1.7. I think the bazel runner uses a different version which is why I'm getting the error.

This is the error:

```java.lang.IncompatibleClassChangeError: com.google.common.base.CharMatcher and com.google.common.base.CharMatcher$NegatedMatcher disagree on InnerClasses attribute```

I was able to fix it using a ClasspathSuite and filtering out everything that wasn't on my classpath, but this  doesn't seem like intended behavior?

**Comment by damienmg** [comment]
Alas this is an intended behavior mostly. In Google, we just have one version of everything so we don't run into that problem...

I don't really have a good answer on how to fix that for now.

**Comment by ulfjack** [comment]
We could jarjar the guava dependency of the test runner, or rewrite the code to not depend on guava in the first place. Rewriting is a bunch of work, even if none of the individual dependencies is particularly complex or difficult to remove. We'd also have to make it work with our internal modifications. I guess that means jarjar or proguard time.
