### ISSUE TITLE
clean command errors if Starlark-defined flags are provided

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/bazel#11506]
### Description of the problem / feature request:

I have set a Starlark-defined flag in my `.bazelrc` file:
```
build --@io_bazel_rules_go//go/config:incompatible_package_conflict_is_error=True
```

Since `bazel clean` inherits the command-line flags from `build`, running `bazel clean` fails with the following error message:
```
INFO: Options provided by the client:
  [...]
INFO: Reading rc options for 'clean' from <redacted>/.bazelrc:
  Inherited 'common' options: [...]
INFO: Reading rc options for 'clean' from <redacted>/.bazelrc:
  Inherited 'build' options: --@io_bazel_rules_go//go/config:incompatible_package_conflict_is_error=True  [...]
ERROR: Unrecognized arguments: --@io_bazel_rules_go//go/config:incompatible_package_conflict_is_error=True
```

It's unclear to me why `bazel clean` looks at any flags defined for `bazel build` (AFAICT, clean unconditionally deletes everything, so it probably shouldn't even look at `.bazelrc` `common` flags). At the very least, `bazel clean` should ignore Starlark-defined flags.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

clone `https://github.com/bazelbuild/rules_go`
run `bazel clean --@io_bazel_rules_go//go/config:incompatible_package_conflict_is_error=True`

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

3.1.0 / 3.2.0rc1

**Comment by katre** [comment]
@juliexxia, is this fixed by your recent work on InfoCommand, or does that change (I think 2ec58f60ae1732f4c1d09330c4583050ac8d1f46) need to be repeated for CleanCommand?

**Comment by Yannic** [comment]
@katre Thanks, I remember seeing that commit some time ago (but didn't remember enough about it to find it again). I also see it with `last_green` (`4d19c0095b791f0c4ccccfaea5f279e373469b24`), so it probably needs to be repeated for `bazel clean`.

**Comment by juliexxia** [comment]
FWIW, you're totally right about clean not needing build commands and this is know technical debt for the bazel team (though not one that is prioritized right now): https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/runtime/commands/CleanCommand.java;l=58?q=CleanCommand&ss=bazel

Hoping I can do a similarly quick fix here as I did for blaze info. I'll take a look.
