### ISSUE TITLE
Bazel CI: Kythe is broken in downstream

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#11501]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1506#bf2de353-d426-4ebe-a09c-ba95dc83dfa5
```
kythe/cxx/indexer/proto/comments_test.cc:19:10: error: module //kythe/cxx/indexer/proto:comments_test does not depend on a module exporting 'gmock/gmock.h'
#include "gmock/gmock.h"
         ^
kythe/cxx/indexer/proto/comments_test.cc:20:10: error: module //kythe/cxx/indexer/proto:comments_test does not depend on a module exporting 'gtest/gtest.h'
#include "gtest/gtest.h"
         ^
2 errors generated.
```
Bazel Auo Sheriff: https://buildkite.com/bazel/bazel-auto-sheriff-face-with-cowboy-hat/builds/164
Culprit: 8b9f74649512ee17ac52815468bf3d7e5e71c9fa

**Comment by meteorcloudy** [comment]
FYI @oquenchil @scentini

**Comment by hlopko** [comment]
Uploaded https://github.com/kythe/kythe/pull/4528 to fix the problem in its root.
