### ISSUE TITLE
cc_library includes attribute shouldn't warn for external repositories

### ISSUE THREAD

**Issue by shahms** [bazelbuild/bazel#1151]
We (Kythe) are currently using a repository_rule to configure some system dependencies. In order to reference these with "standard" system paths, this requires using the `includes` attribute. With 0.2.1 that works fine, but since commit f0a18846461d4b7ecc76c36a659ff1e37f93d7dc there is a warning (which is obnoxious) implying that this will break at some point (which would be more than obnoxious).

Is there another recommended way to accomplish this if the ability to use `includes` outside of `@//third_party` is going away?

**Comment by damienmg** [comment]
Assigning to @janakdr who is currently following up on that.

**Comment by shahms** [comment]
Thanks!
