### ISSUE TITLE
Features to solve the problems with dll linking on Windows

### ISSUE THREAD

**Issue by vnvo2409** [bazelbuild/bazel#11515]
### Description of the problem / feature request:
Solving the problems with dll on Windows. If a package is dependent on 2 different dlls with the same name but different path, Bazel throw an error because it has to copy 2 dlls into the binary folder which causes name clash. The solution is renaming the dll to name-hash.dll and  use a .lib file as an interface library and a .DEF file to actually point to the name-hash.dll

### What operating system are you running Bazel on?

Windows 10

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/11482

### Any other information, logs, or outputs that you want to share?

With the guidance of @meteorcloudy , I will implement this feature
This is the progress tracker of this issue
- [x] Add a build option to enable this features. `--rename_dll`
- [x] Change the dll name on Windows to name-hash.dll, where hash will be calculated based on RepositoryName + the package path the DLL belongs to.
- [x] Add the name to .DEF file by using `LIBRARY name-hash`
- [x] Testing and document

**Comment by meteorcloudy** [comment]
Thanks for working on this!

Here are some places you probably want to look at:

Where the dynamic library is declared in CcLibrary.java:
https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/cpp/CcLibrary.java;l=623?q=CcLibrary.java&ss=bazel

Where the dynamic library is declared in CcBinary.java (`linkshared = 1`):
https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/cpp/CcBinary.java;l=350?q=CcBinary.java&ss=bazel%2Fbazel

Where the DEF file is created:
https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/cpp/CppHelper.java;drc=61d663a503710c8cb0d03d18f2eb776981b49e17;l=915

Note that, Bazel can create DLL from both cc_library and cc_binary. The difference is, the DLL built by cc_binary will contain all transitive dependencies, while the DLL built by cc_library only contains the srcs declared in the target.

**Comment by vnvo2409** [comment]
@meteorcloudy 
I have tried to build `bazel-dev` on master on windows and get this error a few days ago.
```
ERROR: D:/users/vnvo/bazel/bazel-dev/src/main/java/com/google/devtools/build/lib/syntax/BUILD:139:1: no such target '@bazel_tools//tools/jdk:jni':
target 'jni' not declared in package 'tools/jdk' defined by D:/users/vnvo/_bazel_vnvo/3jqcaqfr/external/bazel_tools/tools/jdk/BUILD and referenced by '//src/main/java/com/google/devtools/build/lib/syntax:libcpu_profiler.so'
```
Build with a release branch is fine. 
I think this commit cause the problems but I don't know is it the default behavior https://github.com/bazelbuild/bazel/commit/6255cb1b918f6af750fef4e306fac44b6d351c25

**Comment by meteorcloudy** [comment]
@vnvo2409 Can you show me the command line you used to build Bazel?

**Comment by meteorcloudy** [comment]
And which version of Bazel were you using? It's better to use newer version of Bazel. Old version may not be able to build the latest master branch.

**Comment by vnvo2409** [comment]
> And which version of Bazel were you using? It's better to use newer version of Bazel. Old version may not be able to build the latest master branch.
Sorry, I use the bazel 2.0 to build. I use bazelisk and it fix the problem. Thank you

**Comment by vnvo2409** [comment]
@meteorcloudy 
You think it is better to make a PR for each progress or only one PR at the end. In addition, does bazel use some kinds of linting ( clang-format, ... ) ? I have not seen anything in the contributing guide.

**Comment by meteorcloudy** [comment]
> You think it is better to make a PR for each progress or only one PR at the end.

Yes, I think you can implement it in one PR. But I'm not sure we should change CcBinary, because the target is defined explicitly by users, so they probably expect the DLL name to just be <name>.dll on Windows. However, the DLL built by cc_library is implicit when other cc_binary depends on it and specifies `linkstatic = 0`.

> Does bazel use some kinds of linting ( clang-format, ... ) ? I have not seen anything in the contributing guide

The code will be formatted when we import it into Google, but I don't think the tools are available outside.

**Comment by vnvo2409** [comment]
@meteorcloudy 
I find it is easier and better if we keep the name of the cc_library/cc_binary dll and when we copy to the binary directory using symlinkaction, we change the name to name_hash and edit the name in the def file ( or we could write the name_hash to the def file from the beginning since we will have to change it anyway )

Changing the dll name created by cc_library requires many changes in linking as well

**Comment by konste** [comment]
Please be careful not to break the existing behavior when the binary file produced by cc_binary is named exactly as cc_binary name attribute. It is often used to produce Windows .DLLs and also to produce OSX .dylibs. For some reason cc_library produces .so files on OSX.

**Comment by vnvo2409** [comment]
@konste @meteorcloudy I have created a draft PR so you can review what I did.
https://github.com/bazelbuild/bazel/pull/11524

**Comment by vnvo2409** [comment]
close by https://github.com/bazelbuild/bazel/commit/474c53094133ab1eb8dce16da036f4290290c77e

**Comment by vincyyou** [comment]
> ### Description of the problem / feature request:
> Solving the problems with dll on Windows. If a package is dependent on 2 different dlls with the same name but different path, Bazel throw an error because it has to copy 2 dlls into the binary folder which causes name clash. The solution is renaming the dll to name-hash.dll and use a .lib file as an interface library and a .DEF file to actually point to the name-hash.dll
> 
> ### What operating system are you running Bazel on?
> Windows 10
> 
> ### Have you found anything relevant by searching the web?
> #11482
> 
> ### Any other information, logs, or outputs that you want to share?
> With the guidance of @meteorcloudy , I will implement this feature
> This is the progress tracker of this issue
> 
> * [x]  Add a build option to enable this features. `--rename_dll`
> * [x]  Change the dll name on Windows to name-hash.dll, where hash will be calculated based on RepositoryName + the package path the DLL belongs to.
> * [x]  Add the name to .DEF file by using `LIBRARY name-hash`
> * [x]  Testing and document
