### ISSUE TITLE
Using lld as the linker with bazel?

### ISSUE THREAD

**Issue by bondhugula** [bazelbuild/bazel#11525]
I have bazel 3.0.0. Is there a way to ask bazel to use lld for linking? I've tried the following but it still winds up using ld.gold. 
```
CC=clang CXX=clang++ LD=lld bazel build -c dbg ...
CC=clang CXX=clang++ LD=lld bazel build -c dbg --cxxopt="-fuse-ld=lld" ...
```
(This was with the TensorFlow project: github.com/tensorflow/tensorflow/.)

**Comment by jin** [comment]
For support, please reach out on bazel-discuss@googlegroups.com, ask on StackOverflow, or post in slack.bazel.build.

**Comment by bondhugula** [comment]
This issue was resolved via a response received on the tensorflow/MLIR forum. Using `--linkopt="-fuse-ld=lld"` is the way to use lld as the linker:
```
CC=clang CXX=clang++ bazel build --linkopt="-fuse-ld=lld" ...
```
