### ISSUE TITLE
Maven checksum files breaking generate_workspace

### ISSUE THREAD

**Issue by yschimke** [bazelbuild/bazel#1153]
After running generate_workspace, I'm left with a broken build.

`ERROR: /Users/xxx/workspace/oksocial/BUILD:40:1: no such package '@commons_io_commons_io//jar': Downloaded file at /private/var/tmp/_bazel_xxx/3d64232f2bfe8a39646c9fe8cf2efeb6/external/commons_io_commons_io/commons-io/commons-io/2.4/commons-io-2.4.jar has SHA-1 of b1b6ea3b7e4aa4f492509a4952029cd8e48019ad, does not match expected SHA-1 (b1b6ea3b7e4aa4f492509a4952029cd8e48019ad  ./commons-io-2.4.jar) and referenced by '//:commons_io_commons_io'. `

Specifically the issue is the extra artefact name in the sha1 downloaded from the maven central repo

This is in the file quite deliberately

http://central.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.jar.sha1
b1b6ea3b7e4aa4f492509a4952029cd8e48019ad  ./commons-io-2.4.jar

Maven discussion here https://mail-archives.apache.org/mod_mbox/maven-dev/200901.mbox/%3C495DED17.6090704@udo.edu%3E

**Comment by yschimke** [comment]
This possibly relates to https://github.com/bazelbuild/bazel/issues/1125

**Comment by pgr0ss** [comment]
I think this is https://github.com/bazelbuild/bazel/issues/1461, which is fixed.
