### ISSUE TITLE
FeatureReq: option for checksum-only check for user pre-downloaded tarball with `--distdir` 

### ISSUE THREAD

**Issue by storypku** [bazelbuild/bazel#11533]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

As of bazel 3.2.0,  when `--distdir` option is enabled running `bazel build/test`, bazel will check BOTH basename and checksum of a tarball in the `--distdir` directory.
As I noticed,  if the user changed the filename of the tarball, even if the checksum (`sha256sum`) keeps consistent, bazel doesn't recognize the renamed tarball as a cache hit. It tries again to download the tarball from the original url, which maybe a waste of time for the end user.
So, my question is, can we only check the checksum of the tarball in this situation?
 
### Feature requests: what underlying problem are you trying to solve with this feature?
`--distdir` is quite useful an option for users with low network bandwidth or unstable network access,
and a project using bazel can have various dependencies over other packages.

Quite often than not,  the tarballs of dependency has opaque names, like `v3.3.7.tar.gz`, `release-1.10.0.tar.gz`, `7cf3cefd652008d0a64a419c34c13bdca6c8f178.zip`, to name just a few.

This is easy to cause filename conflicts when a lot of dependencies are specified, and we don't know who is who from these opaque names.

I know that checksum-only check can takes more time than the `filename-check-before-checksum` approach, and enabling it by default in this situation may not be feasible.  Maybe at least, there can  be an option to configure this behavior? 
Once implemented, users can have tarballs with formatted names like "$packagename-$version.tar.gz" or "$packagename-$version-$arch.zip", etc, which is easy to read and maintain. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

NA

### What operating system are you running Bazel on?

Ubuntu 18.04 / x86_64

### What's the output of `bazel info release`?

release 3.2.0

###  Have you found anything relevant by searching the web?
@jin 's answer in another issue:
https://github.com/bazelbuild/bazel/issues/11406#issuecomment-629297982_

>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?
NA

**Comment by rmohr** [comment]
What works pretty well for us in general is to name mirrored artifacts in GCS just with their shasum name. So e.g. v3.3.7.tar.gz` would simply be called in GCS `7cf3cefd652008d0a64a419c34c13bdca6c8f178` if that is the shasum of the file. Maybe this is an option for `--destdir` too, that looking up a filename with the shasum would be done first, followed by a shasum check and then it would proceed to the original file name.
