### ISSUE TITLE
remove dependencies on gflags

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#11544]
This is almost complete, but it is still in third_party and some integration tests seem to make use of it being in the source tree - which seems strangely brittle. Giving this to @meteorcloudy on the grounds that helps with debian cleanliness.

**Comment by jin** [comment]
Looks like gflags have been removed in 3.4 https://blog.bazel.build/2020/07/13/bazel-3-4.html#incompatible-changes

**Comment by aiuto** [comment]
It is still bundled in bazel third_party, even though bazel does not use it any more.
I am not sure if the note for 3.4 is correct. People might sill be able to use it.

**Comment by jin** [comment]
I received a user report from @stepango that the package was removed, during an upgrade to 3.4.x (so unfortunately it was a breaking change without an --incompatible flag)

**Comment by aiuto** [comment]
Whoops. We miss occasionally.  I wonder why it still shows up in the source tree? 
But I don't wonder enough to look right now. I am happy to leave this open so we remember to remove the code from the source tree. That should also make the Debian packaging people happier.

**Comment by philwo** [comment]
I think gflags is 100% gone now.
