### ISSUE TITLE
Aspects do not work when using implicit output targets 

### ISSUE THREAD

**Issue by jagobagascon** [bazelbuild/bazel#11545]
### Description of the problem:

I don't know if this a problem with the android rules, with bazel or maybe I'm just not understanding something about how do aspects or implicit output targets work.

I'm trying to use aspects on a rule that depends on an `android_library` [implicit output target](https://docs.bazel.build/versions/master/be/android.html#android_library_implicit_outputs): *name*.aar. This is the only way I know to generate an `aar` file but my aspect is not getting called.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I tried using the [example aspect from the documentation](https://docs.bazel.build/versions/master/skylark/aspects.html#advanced-example) and it is behaving the same as mine: it never gets called. Having the following code

```starlark
android_library(
    name = 'lib_name',
    srcs = glob(['*.java']),
    manifest = 'AndroidManifest.xml',
)

file_count_rule(
    name = 'count',
    deps = [':lib_name']
) # =>  WORKS FINE

file_count_rule(
    name = 'count_aar',
    deps = [':lib_name.aar']
) # => FAILS 
````

If I run `bazel build //:count` I get the number of files. But when I call `bazel build //:count_aar` I get the following error:
```<output file target lib_name.aar> doesn't contain declared provider 'FileCountInfo'```

I don't really understand what *implicit output target*s are, or how are they treated. **Is this an expected behaviour?**

### What operating system are you running Bazel on?

Ubuntu 16.04 and Debian GNU/Linux 10 (buster)

### What's the output of `bazel info release`?

release 3.2.0

###  Have you found anything relevant by searching the web?

nope

**Comment by jagobagascon** [comment]
I was trying to deploy the `lib_name.aar` to a maven repo, using aspects to detect dependencies and generate the `pom.xml` file and I wasn't understanding why aspects worked with  `:lib_name` and not with `:lib_name.aar`. I assumed it could be a bug cause I didn't find anything in the docs. 

I worked around it by using `:lib_name` to create the pom and then `:lib_name.aar` for deployment:
```starlark
generate_pom(
    name = 'generate_pom',
    target = ':lib_name',
    ...
)
publish_to_artifactory(
    name = 'publish',
    pom_file = ':generate_pom',
    target = ':lib_name.aar',
    sources = ':liblib_name-src.jar',
    ...
)
```

I still have some questions that maybe you can answer 😄:
- How are those implicit outputs defined in a rule?
- Can I define an implicit output in one of my rules?
- Or maybe `android_library` is just a macro wrapping several rules?

Anyway I think we can close this issue now. Thank you for your help!

**Comment by gregestren** [comment]
I believe in Starlark you declare implicit outputs as "predeclared outputs" and don't add them to `DefaultInfo` if you want them to be implicit, as documented at https://docs.bazel.build/versions/master/skylark/rules.html#outputs.

That doc does have comments about trying to avoid this pattern, though. I'm not sure if implicit outputs are encouraged best practice for newly written rules. For traditional rules like `android_library`, these are hard-coded into Bazel so use legacy logic (it works fine but doesn't use the modern Starlark APIs).

**Comment by gregestren** [comment]
Also check out https://docs.bazel.build/versions/3.2.0/skylark/lib/globals.html#rule.outputs, which includes some commentary on what's considered best practice.

**Comment by nacl** [comment]
Bah, sorry for the delayed response, @sdtwigg.  The flag apparently worked, but it may have additional consequences; I haven't been able to run a deep investigation to see how it might impact our use case.

Thanks for the suggestion!
