### ISSUE TITLE
Documentation issue: repository_ctx.download omits "success" field in return struct.

### ISSUE THREAD

**Issue by psigen** [bazelbuild/bazel#11559]
Documentation URL: https://docs.bazel.build/versions/master/skylark/lib/repository_ctx.html

The documentation for [`repository.ctx.download()`](https://docs.bazel.build/versions/master/skylark/lib/repository_ctx.html#download) and [`repository_ctx.download_and_extract()`](https://docs.bazel.build/versions/master/skylark/lib/repository_ctx.html#download_and_extract) 
omits that the return struct includes a `success` field that returns `true` if the download completed successfully, and `false` if it does not.

(At least, that's what I think it does-- I'm not entirely sure because it's not documented.)

I'm happy to make a PR with the above notes if someone can help me find the part of the repo where the source markdown for this part of the docs is located.

**Comment by communikit** [comment]
Hi @psigen ,

You can make a PR updating the documentation in the doc fields for download and download_and_extract in this part of the Bazel repo: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/starlarkbuildapi/repository/StarlarkRepositoryContextApi.java

**Comment by psigen** [comment]
Thanks @communikit .  Created https://github.com/bazelbuild/bazel/pull/13041 to address this.
