### ISSUE TITLE
Bazel hangs on java binary

### ISSUE THREAD

**Issue by Steroes** [bazelbuild/bazel#11557]
I am trying to reinstall bazel on a the same machine after an OS upgrade. Following the same steps the same bazel version is giving problem when calling it. I assume the problem has to do with the java binary, but I have no idea how to further debug it. Do you have suggestions on how to further debug this?

After calling the bazel 0.19.1 installer the build hangs on 
" Extracting Bazel installation..."
When calling strace on 'bazel help' or "bazel version" I get:
futex(0x7f93131bc9d0, FUTEX_WAIT, 8279, NULL
at the end

When calling `bazel --client_debug --batch version` I get:

[bazel INFO src/main/cpp/option_processor.cc:362] Looking for the following rc files: /etc/bazel.bazelrc,/export/home/sdc/.bazelrc
[bazel INFO src/main/cpp/blaze.cc:1549] Debug logging requested, sending all client log statements to stderr
[bazel INFO src/main/cpp/blaze.cc:1569] Acquired the client lock, waited 0 milliseconds
[bazel INFO src/main/cpp/blaze.cc:725] Starting Bazel in batch mode.
[bazel INFO src/main/cpp/blaze_util_posix.cc:226] Invoking binary /export/home/sdc/.cache/bazel/_bazel_sdc/install/4934d058a217b4818dc15e0efc1712e0/_embedded_binaries/embedded_tools/jdk/bin/java in /export/home1/sdc_bamboo/bamboo-agent-home/xml-data/build-dir/Z800-DEP-JOB1/tensorflow/build/deps

----

Additional information:
Bazel 0.19.1 installed using:
wget https://github.com/bazelbuild/bazel/releases/download/0.19.1/bazel-0.19.1-installer-linux-x86_64.sh
./bazel-0.19.1-installer-linux-x86_64.sh --prefix=`pwd`

OS: 
`lsb_release -a`
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: HELiOS
Description:    HELiOS release 6.10SP2 (Carbon)
Release:        6.10SP2
Codename:       Carbon

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

**Comment by aiuto** [comment]
You are probably better off asking on stackoverflow.  We do not have any Helios machines for testing and are not going to spend time on a version of Bazel that old.

**Comment by crorvick** [comment]
That version is only 18 months old.  It's pre-1.0, but it's not clear that 1.0 was much of a milestone when major (read "breaking") releases are every few months.

{fast, correct} ... unless it totally just doesn't work.

**Comment by Steroes** [comment]
It's not specifically about a bazel version. I just want to know how to further debug this sort of problem, which looks similar to https://github.com/bazelbuild/bazel/issues/748.

**Comment by jin** [comment]
Bazel works on a self-extracting client-server model, where the client is a C++ binary that extracts the Java server (A-server.jar) and launches it, and communicates with it over RPC. It looks like the client did execute successfully, but it's running into problems communicating with the server. Check if the Java process is running, and do a thread dump to see where it's stuck at?

Also consider trying this with a later Bazel version to see if the problem has been fixed in the mean time.

I'm going to close this issue now. Please reach out on bazel-discuss@ or slack.bazel.build for more visibility or debugging tips with Bazel.
