### ISSUE TITLE
Documentation incorrect --fission has no effect

### ISSUE THREAD

**Issue by andrewstevens-infineon** [bazelbuild/bazel#11561]
### Description of the problem / feature request:

The documentation suggestes that the --fission build option isimplement.   

> --fission (yes|no|[dbg][,opt][,fastbuild])
> 
> Enables Fission, which writes C++ debug information to dedicated .dwo files instead of .o files, where it would otherwise go. This substantially reduces the input size to links and can reduce link times.
> 
> When set to [dbg][,opt][,fastbuild] (example: --fission=dbg,fastbuild), Fission is enabled only for the specified set of compilation modes. This is useful for bazelrc settings. When set to yes, Fission is enabled universally. When set to no, Fission is disabled universally. Default is dbg. 

At least for linux/gcc this is not the case.  The option has no effect whatsoever.
To function correct with gcc the -gsplit-dwarf option should be used. This does not occur.
Additionally --gdb-index should be used with the gold linker.  Neither occurs

### Feature requests: what underlying problem are you trying to solve with this feature?

Documentation matching actual implementation status.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Use bazel C++ [examples]( https://github.com/bazelbuild/examples).

`cd examples/cpp-tutorial/stage1`

`bazel buiild  --fission=yes -c dbg --subcommands=yes //main:hello-world`

The gcc command-line still selects -g not -gsplit-dwarf.

`cat bazel-out/k8-dbg/bin/main/hello-world-2.params`

The linker command line has no -Wl,--gdb-index.

### What operating system are you running Bazel on?

Ubuntu 18.04.

### What's the output of `bazel info release`?

release 3.2.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/bazelbuild/examples

###  Have you found anything relevant by searching the web?

Yes. Very old article discussion formum article [here](https://groups.google.com/forum/#!searchin/bazel-discuss/fission%7Csort:date/bazel-discuss/GhP-gODplX0/aQBl7XUwCQAJ)

Inidicating fission option was non-functional for default toolchains.

**Comment by Riatre** [comment]
First, the [user manual](https://docs.bazel.build/versions/master/user-manual.html#flag--fission) say:

> When set to [dbg][,opt][,fastbuild] (example: --fission=dbg,fastbuild), Fission is enabled only for the specified set of compilation modes. This is useful for bazelrc settings. When set to yes, Fission is enabled universally. When set to no, Fission is disabled universally. Default is dbg.

However according to [Command-Line Reference](https://docs.bazel.build/versions/master/command-line-reference.html):
> --fission=<a set of compilation modes> default: "no"

I believe the command line reference is correct here.

If I manually enable feature `per_object_debug_info` via `--features=per_object_debug_info`, `--fission` seems to work. Still no `-Wl,--gdb-index` though. So at least the documentation is inaccurate here.

**Comment by ulfjack** [comment]
Fission may be enabled by default inside Google, which could explain the inconsistency in the docs. Most likely, fission requires a specific toolchain feature that isn't present in the auto-detected toolchain. Odd though that it has some of the features, but not all. In any case, the documentation definitely needs a scrub.

**Comment by andrewstevens-infineon** [comment]
Hi,

I dug a little deeper.  It seems things are a bit more complicated that just the docs being outdated. There seems to be an actual bazel Bug!

The default C++ toolchain  includes a definition of the `per_object_debug_info` feature intended to set `-gsplit-dwarf` when enabled,  
[unix_cc_toolchain_config.bzl:303](https://github.com/bazelbuild/bazel/blob/3.2.0/tools/cpp/unix_cc_toolchain_config.bzl).

However the flag_group is set as `expand_if_available` on  the `per_object_debug_info_file` build variable.  Glancing at  

 [CcToolchainProvider.java sources](https://github.com/bazelbuild/bazel/blob/3.2.0/src/main/java/com/google/devtools/build/lib/rules/cpp/CcToolchainProvider.java)

shows this is set for compile actions if fission is active _and_ `per_object_debug_info` is enabled.  However, for some reason this is not actually working.  Perhaps the flag_group condition is being evaluated before the per-action build variables are set?

As a crude workaround  `per_object_debug_info_file` can be set globally. if you do this
not only is the `-gsplit-dwarf` flag included but also the correct action  (i.e. _including_  the existence of the .dwo output ) is constructed. This is NOT the case if you simply set `--cxxopt=-gsplit-dwarf`.  E.g. when using remote execution setting 

`--define='per_object_debug_info_file=dummy' --fission=yes --features=per_object_debug_info`

results in  .dwo being copied back to the local environment wheras if

`--cxxopt=-gsplit-dwarf --fission=yes --features=per_object_debug_info`

is set they are missing.


Additionally there seems to be some confusion between different aspects of "fission" compiler/linker functionality.  The docs state
 
[here](https://docs.bazel.build/versions/master/cc-toolchain-config-reference.html#well-known-features)
`
per_object_debug_info | Enabled if the supports_fission feature is specified and enabled and the current compilation mode is specified in the   --fission flag.
`
 
However the symbol `supports_fission` is absent from the source code except for one reference
[here](https://github.com/bazelbuild/bazel/blob/master/src/main/protobuf/crosstool_config.proto)
 
where it indicates it is dead.  However there _is_ a confusingly-similarly named feature `fission_support` defined by the default C++ toolchain.  E.g. 

[unix_cc_toolchain_config.bzl:444](https://github.com/bazelbuild/bazel/blob/3.2.0/tools/cpp/unix_cc_toolchain_config.bzl) 

enabled if fission is active.  This triggers creation of gdb index in the link phase (which not _quite_ the same this as fission ).

Shall I raise the Bug as a separate Issue?

**Comment by thanksunix** [comment]
Got same problems.

It seems this `fission` does not work.

--

```shell
 bazel build --fission=yes //:hello
 bazel build --fission=yes //:hello.dwp
```

After running above commands, I get an empty hello.dwp.

Here is the BUILD FILE & hello.cc, I do open the gsplit-dwarf & gdb-index:

```shell
# shuyan.ycf @ i85c08157 in ~/hello [22:56:54]
$ cat  BUILD
cc_binary(
    name = "hello",
    srcs = ["hello.cc"],
    copts = ["-gsplit-dwarf"],
    linkopts = ["-Wl,--gdb-index"],
)

# shuyan.ycf @ i85c08157 in ~/hello [22:57:12]
$ cat hello.cc
#include <iostream>

int main() {
  std::cout << "hello world" << std::endl;
}
```
Here is the params files output:
```
$ cat bazel-bin/hello-2.params
-o
bazel-out/k8-fastbuild/bin/hello
-Wl,-S
-fuse-ld=gold
-Wl,-no-as-needed
-Wl,-z,relro,-z,now
-B/opt/rh/devtoolset-7/root/usr/bin
-pass-exit-codes
-lstdc++
-lm
bazel-out/k8-fastbuild/bin/_objs/hello/hello.pic.o
-Wl,--gdb-index

```

**Comment by mbinna** [comment]
The default-generated toolchain at `bazel-<workspace_name>/external/local_cc_config/cc_toolchain_config.bzl` contains the [feature](https://docs.bazel.build/versions/main/cc-toolchain-config-reference.html#features) `per_object_debug_info`, but it is disabled by defaul (i.e., it doesn't contain `enabled = True`). When I enable the feature with `--features=per_object_debug_info` as mentioned in https://github.com/bazelbuild/bazel/issues/11561#issuecomment-641058200

```
$ bazel build -c dbg --fission=yes --features=per_object_debug_info //:helloworld
```

the DWP file is created properly and `-Wl,--gdb-index` is used for linking. Tested with Bazel 4.1.0.

**Comment by keith** [comment]
I submitted https://github.com/bazelbuild/bazel/pull/14777 which should remove the need for passing `--features=per_object_debug_info` manually, instead just `--fission=yes` will be enough

**Comment by fzakaria** [comment]
@keith you might want to close this issue now.
