### ISSUE TITLE
Incorrect type 'string'  (should be 'dict') when attempting to iterate over dict error in Starlark

### ISSUE THREAD

**Issue by restingbull** [bazelbuild/bazel#11570]
### Description of the problem / feature request:
Given:
```
d = {}
a =  [(k, v) for (k, v) in d if v]
```

Expected:
`type 'dict' is not iterable`

Got:
`type 'string' is not iterable`

### What operating system are you running Bazel on?

macOS Catalina, 10.15.4 (19E287

### What's the output of `bazel info release`?
```
$ bazel info release
release 3.2.0
```

###  Have you found anything relevant by searching the web?

No, but the noise is pretty bad for the error query.

https://www.google.com/search?q=%22type+%27string%27+is+not+iterable%22+starlark

**Comment by laurentlb** [comment]
This is working as intended.

`[0 for i in d if v]` will iterate over the keys of the dictionary. If you replace `i` with a tuple, you'll try to unpack the value. If the dict keys are strings, it won't work because strings are not iterable.

Examples:

```python
d = {"abc": "def"}
[k for k in d]   # "abc"

d = {"ab": "cd"}
[fst for fst, snd in d] # would return "a" in Python; it's an error in Starlark
```
