### ISSUE TITLE
Release commits should be tagged

### ISSUE THREAD

**Issue by creachadair** [bazelbuild/bazel#1157]
Repro (assuming Bazel is checked out in `~/bazel`):

    cd ~/bazel
    git checkout master
    git pull
    git tag

**Expected:** The output of `git tag` should include a tag for the most recent release commit, which is 0.2.1 as I write this.

**Observed:** The most recent tag is 0.2.0.

Having a release branch would also be fine, but is probably overkill.

**Comment by damienmg** [comment]
Fetch tags? We have a release branch for release candidates and a tag for
released version. We do use the tag for homebrew recipe for example.

**Comment by creachadair** [comment]
Ah, sorry, I see what happened. I had configured my remote for Bazel to fetch tags, but I lost that setting when I had to start a fresh clone a while back. Sorry for the noise.
