### ISSUE TITLE
Symbols marked as visible not getting exported in shared lib without an --incompatible flag.

### ISSUE THREAD

**Issue by chetgnegy** [bazelbuild/bazel#11577]
### Description of the problem / feature request:
(from https://groups.google.com/forum/#!topic/bazel-discuss/7TMbBIMkptk)
I have a cc_binary "thingy.so" with linkshared=1. There is a symbol in my code exported as __attribute__ ((visibility("default")). Since bazel 1.0.0, this symbol will only make it to the generated binary if I use flag --incompatible_remove_legacy_whole_archive. This solution is fine for me, but documentation should be updated (perhaps in cc_binary's linkshared tag) regarding whether this is the proper way to deal with the issue or not.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I'm not actually sure this is a bug. It might be intended behavior, I just wanted to make sure this was documented (cause it took me a really long time to figure out the build system was the problem). Questions include: Is this the preferred way to prevent an unused exported symbol from being stripped? Will the flag I'm using continue to be supported.

In any case, laurentlb@ says they use this flag in google3, I imagine removing the flag and doing a diff on the output of nm is the easiest way to reproduce.

### What operating system are you running Bazel on?
Linux, Ubuntu 16.04

### What's the output of `bazel info release`?
release 1.0.0
1.0.0. but this happens in 3.1.0, too.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.
I built bazel using one of the sh scripts associated with the 1.0.0 release.

###  Have you found anything relevant by searching the web?
Couldn't find anything.

**Comment by jin** [comment]
Issue reference for the incompatible change flag: https://github.com/bazelbuild/bazel/issues/7362

**Comment by oquenchil** [comment]
Flag was flipped.

**Comment by chetgnegy** [comment]
You mean the flag was inverted? Do I need to keep providing the flag? Please clarify.

**Comment by oquenchil** [comment]
The incompatible flag was set to true by default, no need to keep providing it.
