### ISSUE TITLE
args escaping in executable rules

### ISSUE THREAD

**Issue by guibou** [bazelbuild/bazel#11587]
### Description of the problem / feature request:

Many executable rules provides an `args` attribute which is supposed to be a list of arguments to the command. However the semantic of it is confusing:

- arguments are passed without escaping to the sub command, so the list semantic is not respected. i.e. one argument in the bazel list can generate many arguments to the sub command
- some chars seems to be ignored.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build the following program:

```c
#include <stdio.h>

int main(int argc, char **argv)
{
    for(int i = 0; i < argc; ++i)
    {
        printf("%d) %s\n", i, argv[i]);
    }
}
```

using the following `BUILD.bazel`:

```python
cc_binary(
        name = "foo",
        srcs = ["foo.c"],
        args = ["hello world", "you are", "amazing", "'escape'", '"escape"'],
        )     
````

Then `bazel run //:foo`.

I'm expecting the following output:

```
1) hello world
2) you are
3) amazing
4) 'escape'
5) "escape"
```

Instead, I'm observing:

```
1) hello
2) world
3) you
4) are
5) amazing
6) escape
7) escape
```

See how `hello world` and `you are` are split to two arguments and both `escape` misses their quotes delimiters.

I observed the same thing with others rules, such as `sh_binary`, ....

### What operating system are you running Bazel on?

Linux.

### What's the output of `bazel info release`?

Sorry, I closed my docker container. It was a bazel 3.2.0, installed using the following procedure: https://docs.bazel.build/versions/master/install-ubuntu.html#install-with-installer-ubuntu

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

This unanswered stock overflow question two years ago: https://stackoverflow.com/questions/47957685/patterns-for-passing-args-to-binary-rules-in-bazel

I'll be tempted to submit a pull request, but this may be a breaking change, so it may need a deprecation process.

**Comment by fmeum** [comment]
@bazelbuild/triage Please reopen.

**Comment by kjw-enf** [comment]
Technically working as designed:

https://bazel.build/reference/be/common-definitions#binary.args

> List of strings; subject to [$(location)](https://bazel.build/reference/be/make-variables#predefined_label_variables) and ["Make variable"](https://bazel.build/reference/be/make-variables) substitution, and [Bourne shell tokenization](https://bazel.build/reference/be/common-definitions#sh-tokenization); [nonconfigurable](https://bazel.build/reference/be/common-definitions#configurable-attributes); default is []

The problem you are complaining about is the "Bourne shell tokenization".

Personally, I'd like to be able to turn on a "strict" mode which drops that. Yes, it means users need to be better about how they assemble the list, and in some cases it'll look funnier, but there is less guessing involved. For example:

args = [ "-k 1234" ] # if strict, most cli parsers barf on this with the error """ unknown flag 'k 1234' """ which means you should instead use preferably the '=' version (shell defensive programming) i.e. args = [ "-k=1234" ] but that's not always supported. Sometimes you have a long flag available which does allow = like args = [ "--key=1234" ]. Worst case, you can always use args = [ "-k", "1234" ].

If it's not obvious how this is "strict", go play with this shell script and pass these args to it:
#!/bin/sh
echo $1
echo $2
echo $3
