### ISSUE TITLE
incompatible_override_toolchain_transition: Migrate rules to use the toolchain transition

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#11584]
This flag unconditionally makes all rule uses the new [toolchain transition](https://github.com/bazelbuild/proposals/blob/master/designs/2019-02-12-toolchain-transitions.md). This means that any rule that uses [toolchain resolution](https://docs.bazel.build/versions/3.2.0/toolchains.html) to fetch tools will need to migrate so that tools are in the correct configuration.

**Flag:** `--incompatible_override_toolchain_transition`

**Migration:**

First, wait for the new feature to be released (presumably in the release after 3.3.0).

See [toolchain transition migration](https://github.com/bazelbuild/proposals/blob/master/designs/2020-02-07-toolchain-transition-migration.md) for details, but the process is fairly simple:
1. For rules that **create** toolchains (i.e., `cc_toolchain`, `go_toolchain`, `java_toolchain`), add the proper `cfg` attribute.
   1. If the attribute is a tool used in builds (a compiler, a linker, anything that is executed), add `cfg = 'exec'` so that it will be built for the correct execution platform.
   1. If the attribute is intended to be part of the final target (a library, included source, anything else), add `cfg = 'target'`, so that it will be built in the correct target configuration.
   1. At this point, there will be no change, because toolchains still use the host transition, and that overrides anything set on the toolchain rule itself.
2. For each rule that **uses** a toolchain (i.e., `cc_library`, `go_binary`, `java_test`), add the `incompatible_use_toolchain_transition = True` parameter to the rule definition in Starlark.
   1. This enables the toolchain transition, instead of the host transition, when this rule type depends on a toolchain.
   1. Every toolchain type this rule uses should have been migrated in step 1 above.
3. Once every rule has been migrated, wait for Bazel to flip the value of the `--incompatible_override_toolchain_transition` flag. This will take several releases for all rules to finish steps 1. and 2.
4. Once the flag has flipped, remove the `incompatible_use_toolchain_transition` parameter from the rule declaration.
5. Bazel will eventually deprecate the flag and rule parameter and remove them.

**Comment by konste** [comment]
@katre I have a question: we use custom C++ and Python toolchains, but to implement those toolchains we use native `cc_toolchain` rule and `toolchain` rule, like that:
```
py_runtime_pair(
    name = "tab_python_runtime_pair",
    py3_runtime = "@tab_toolchains//thirdparty/python:tab_python_runtime",
)

toolchain(
    name = "tab_python_toolchain",
    toolchain = ":tab_python_runtime_pair",
    toolchain_type = "@bazel_tools//tools/python:toolchain_type",
)
```
As far as I understand toolchain transition migration is to be done by the maintainers of the `cc_toolchain` rule and `toolchain` rule, right? The changes needed are in the implementation of those native rules, not at the place where they are used. Correct?

Specific reason I need to clarify that is because recently `bazel cquery` started to give us warnings like this:
```
WARNING: Targets were missing from graph: [ConfiguredTargetKey{label=@tab_msvc_toolchain_repo_64//:tab_msvc_cc_toolchain_64, config=BuildConfigurationValue.Key[5abb50d874a0ab83869e8c0d685014657df6f34d02bb0ebbb59b2108192fcfff]}]
WARNING: Targets were missing from graph: [ConfiguredTargetKey{label=@tab_toolchains//bazel/toolchains/python:tab_python_runtime_pair, config=BuildConfigurationValue.Key[5abb50d874a0ab83869e8c0d685014657df6f34d02bb0ebbb59b2108192fcfff]}]
```
I cannot make sense of those warnings, but both of them point to the rule directly related to the C++ and Python toolchain. This made me think it may be relevant to toolchain transition migration. 
Any advice?

**Comment by katre** [comment]
Both python rules and CC rules need to be migrated, this will be separate efforts. I'm not sure where you are using the cc toolchain: in your example, the `py_runtime_pair` target creates a specific python toolchain and the `toolchain` target allows Bazel to know it exists. I don't see an example of a `cc_toolchain` here. Note that [`toolchain`](https://docs.bazel.build/versions/3.4.0/be/platform.html#toolchain) and [`cc_toolchain`](https://docs.bazel.build/versions/3.4.0/be/c-cpp.html#cc_toolchain) are very different: `cc_toolchain` creates a specific type of toolchain that CC rules can use to build C and C++ files, whereas `toolchain` is a core configuration rule used to tell Bazel about specific toolchains that can be used.

I'm not sure what's happening with cquery: you will need to file a separate issue about that so we can route it to the appropriate experts.

**Comment by konste** [comment]
I see. I was just making sure that there is nothing for us to do if we only use cc_toolchain, but not implement it.

**Comment by katre** [comment]
There is nothing needed for users of rules.
