### ISSUE TITLE
Bazel failed to build on MacOS 10.15 because of Xcode headers

### ISSUE THREAD

**Issue by vnvo2409** [bazelbuild/bazel#11589]
### Description of the problem / feature request:
Bazel failed to build on MacOS 10.15 because of Xcode headers
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Build anything that include a C/C++ system header (e.g `<stdio.h>`) on MacOS with Xcode installed
### What operating system are you running Bazel on?
MacOS 10.15
### What's the output of `bazel info release`?
release 3.1.0
###  Have you found anything relevant by searching the web?
I found something related to Xcode in general but aren't related to Bazel.
### Any other information, logs, or outputs that you want to share?
```
this rule is missing dependency declarations for the following files included by 'external/gif/gif_err.c':
'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h'
'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_stdio.h'
'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h'
```
I think these files do not need to declare as dependencies. Before installing Xcode, Bazel worked fine with CommandLineTool. After installing Xcode, I have this error. In fact, I have many troubles with Xcode and CommandLineTool when updating to MacOS 10.15 ( many programs complained that they can not find CommandLineTool or XCode even both were already installed). I tried to remove Xcode but the problem still appears.

**Comment by jin** [comment]
Can you try running `bazel sync --configure` and run the bazel build command again?

**Comment by vnvo2409** [comment]
Thank you. It work. I will close the issue
