### ISSUE TITLE
Ability to namespace imported skylark functions?

### ISSUE THREAD

**Issue by jcoveney** [bazelbuild/bazel#1158]
This came up here https://github.com/bazelbuild/rules_scala/issues/31

It seems desirable to be able to namespace common functions, making migrating between implementations very easy. We can definitely go the other route @johnynek mentioned (of adding a scala_language_internal), but it seems suboptimal that all skylark rules will have to have this escape hatch.

**Comment by damienmg** [comment]
Isn't renaming enough?

You can do:
```python
load('...:def.bzl', orig_scala_library='scala_library')
```

And that will make `scala_library` available under the name `orig_scala_library`.

If that does not fulfill your requirements, can you give us a bit more explanation on what you would like?

**Comment by jcoveney** [comment]
I think that actually may be good enough...didn't realize that that was possible. Will reopen if I come up with a reason it won't... thank you!
