### ISSUE TITLE
Bazel not using latest version of CoverageOutputGenerator

### ISSUE THREAD

**Issue by paymog** [bazelbuild/bazel#11585]
### Description of the problem / feature request:

It seems like bazel is not using the latest version of CoverageOutputGenerator. When I run `bazel coverage --combined_report=lcov --coverage_report_generator=@bazel_tools//tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator:Main //...` I see the following lines of output:

```
Jun 11, 2020 2:14:20 PM com.google.devtools.coverageoutputgenerator.Main parseFiles
SEVERE: Parsing file bazel-out/darwin-fastbuild/testlogs/examples/bundles/nginx/go_default_test/coverage.dat
```

Note that this is a `SEVERE` log but that [this commit](https://github.com/bazelbuild/bazel/commit/21f633ca58d45b4d270668ddb147f680931efef3#diff-28066f583dd7408ef66042f7403845ea) changes that to an `INFO` log.

The commit exists on versions of bazel back to 2.2 and I'm on version 3.1. I've tried running `bazel clean` but that didn't help.

### Feature requests: what underlying problem are you trying to solve with this feature?

Not a feature request

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I don't have a minimal repro.

### What operating system are you running Bazel on?

osx 10.15.5

### What's the output of `bazel info release`?

`release 3.1.0`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

NA

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

I don't think this is relevant because I'm not building bazel

###  Have you found anything relevant by searching the web?

Yes, I've found the following:
* https://stackoverflow.com/questions/60751912/output-coverage-coverage-report-dat-was-not-created-when-using-bazel-coverag
* https://github.com/bazelbuild/bazel/issues/6450

### Any other information, logs, or outputs that you want to share?

I think because an old version of the coverage generator is being used, coverage fails to be combined:

```
ERROR: output '_coverage/_coverage_report.dat' was not created
ERROR: not all outputs were created or valid
```

**Comment by ulfjack** [comment]
Someone will need to create a new release (although note that will only affect future releases of Bazel).

**Comment by paymog** [comment]
A new release of the CovergeOutputGenerator?

**Comment by ulfjack** [comment]
Yes. I think someone from Google will have to do that. I don't think I have access to the right GCS buckets...

**Comment by paymog** [comment]
Got it. Any chance you know how I can find out which commit is being used
with my version of bazel?

**Comment by ulfjack** [comment]
If you're in a workspace, run `bazel build`, and then:
```
$ unzip -p bazel-workspace/../../install/A-server.jar com/google/devtools/build/lib/bazel/rules/coverage.WORKSPACE
<snip>
http_archive(
    name = "remote_coverage_tools",
    sha256 = "96ac6bc9b9fbc67b532bcae562da1642409791e6a4b8e522f04946ee5cc3ff8e",
    urls = [
        "https://mirror.bazel.build/bazel_coverage_output_generator/releases/coverage_output_generator-v2.1.zip",
    ],
)
```

**Comment by ulfjack** [comment]
@meisterT updated the generator in commit https://github.com/bazelbuild/bazel/commit/7c4f3ff7391862881056005db02c4be0d2bc147a, so this is probably now fixed.
