### ISSUE TITLE
Protobuf in TensorFlow not building with the right libstdc++

### ISSUE THREAD

**Issue by boubasse** [bazelbuild/bazel#11588]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

Hi everyone,

Please find a reccurent bug that i'm trying to resolve desperately...

### Description of the problem / feature request:

I'm trying to build TensorFlow from the source using Bazel (3.2.0), everything goes fine execpt that I'm facing an issue that I don't know how to correct since I'm not a Bazel expert. The build is stopping at the protobuf section, see below the build error :

``
ERROR: /nobackup/af261718/tensorflow/tensorflow/core/util/BUILD:660:17: ProtoCompile tensorflow/core/util/test_log_pb2.py failed (Exit 1): protoc failed: error executing command 
  (cd /nobackup/af261718/cache/bazel/_bazel_af261718/0773f41f5efd7b2afa75c2b5b53f9c82/execroot/org_tensorflow && \
  exec env - \
  bazel-out/host/bin/external/com_google_protobuf/protoc '--python_out=bazel-out/host/bin' -I. -Iexternal/com_google_protobuf/python -Ibazel-out/host/bin/external/com_google_protobuf/python tensorflow/core/util/test_log.proto)
Execution platform: @local_execution_config_platform//:platform
bazel-out/host/bin/external/com_google_protobuf/protoc: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by bazel-out/host/bin/external/com_google_protobuf/protoc)
bazel-out/host/bin/external/com_google_protobuf/protoc: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by bazel-out/host/bin/external/com_google_protobuf/protoc)
bazel-out/host/bin/external/com_google_protobuf/protoc: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by bazel-out/host/bin/external/com_google_protobuf/protoc)
bazel-out/host/bin/external/com_google_protobuf/protoc: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by bazel-out/host/bin/external/com_google_protobuf/protoc)
INFO: From ProtoCompile tensorflow/core/data/service/worker.pb.h:
bazel-out/k8-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 14.694s, Critical Path: 4.94s
INFO: 9 processes: 9 local.
FAILED: Build did NOT complete successfully
``

I'm launching the following command to build TF: 
`bazel build --config=opt --config=cuda --config=noaws --config=nogcp --config=nohdfs --config=v2 --linkopt=-Wl,-rpath,/path/to/lib64/ --linkopt=-L/path/to/lib64/ --verbose_failures //tensorflow/tools/pip_package:build_pip_package`

It seems like the linkopt are not taken into account... Moreover, the `exec env -` would erase all the env vars so LD_LIBRARY_PATH would be useless at this point.
I've tried to modify the TF toolchains by adding my own flags but it doesn't work. I've been digging a lot to find a solution to this problem but nothing help and in the third_party/gpu/crosstool directory of TF there is no CROSSTOOL file. And in the protobuf directory, there is no explicit way to tell using a custom location for libstdc++. 

It must be emphasized that I'm not the sysadmin of the machine and therfore I cannot create a symbolic link to the correct library.

Thank you in advance for your help.

### Feature requests: what underlying problem are you trying to solve with this feature?

Building TensorFlow with custom located libstdc++

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Just having an old libstdc++ in /lib64/ and trying to point to a newer version in another location

### What operating system are you running Bazel on?

Scientific Linux 7

### What's the output of `bazel info release`?

release 3.2.0- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Built from source

###  Have you found anything relevant by searching the web?

All solutions to the adressed issue are outdated and do not work or are irrelevant.

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by jin** [comment]
Please contact TensorFlow support or open an issue on the TensorFlow repository for TF's build issues.
