### ISSUE TITLE
Pulling images from GCR fails if gcloud auth helper is in use

### ISSUE THREAD

**Issue by teran** [bazelbuild/bazel#11596]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Bazel build/tests requiring external docker images from GCR fails with `Operation not permitted` on macOS 10.15.5 if docker is configured to use cloud authentication helper.

```
WARNING: Could not setup log file in <homedir>/.config/gcloud/logs, (IOError: [Errno 1] Operation not permitted: u'<homedir>/.config/gcloud/logs/2020.06.16/08.14.38.216798.log')
ERROR: (gcloud.auth.docker-helper) Unable to create private file [<homedir>/.config/gcloud/credentials.db]: [Errno 1] Operation not permitted: '<homedir>/.config/gcloud/credentials.db'
```

If `--spawn_strategy=standalone` is set the everything is working fine.

Adding `bazel-real` (`/usr/local/Cellar/bazel/3.2.0/libexec/bin/bazel-real`) with Full disk access (and obviously restarting the daemon) doesn't help.

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

On macOS Catalina 10.15.5:
- Install Google Cloud SDK
- Install docker or create ~/.docker/config.json file
- Configure Docker to use gcloud helper to authenticate in GCR: `docker auth login` ; `gcloud auth configure-docker`

### What operating system are you running Bazel on?

macOS 10.15.5

### What's the output of `bazel info release`?

```
release 3.2.0-homebrew
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

The issue is not about git.

###  Have you found anything relevant by searching the web?

Nothing related to macOS access control system.

### Any other information, logs, or outputs that you want to share?

Everything is in the description section.

**Comment by teran** [comment]
UPD: the helper named "standalone-helper" (written in Go, which means it's running without Python interpreter) in GCR docs works fine (with setting `$HOME` for actions) so it looks like the issue is about how bazel daemon runs external commands (and how macOS reacts on scripts).

**Comment by aiuto** [comment]
Given the message: ERROR: (gcloud.auth.docker-helper) Unable to create private file [<homedir>/.config/gcloud/credentials.db]:
This does sound like a docker message.  Have you asked this in the docker lists?

**Comment by teran** [comment]
@aiuto,

The thing is it works correctly out of bazel (`docker pull gcr.io/....`, `docker run gcr.io/....`). At the same time [rules_docker](https://github.com/bazelbuild/rules_docker) doesn't use docker itself but the tool called puller to fetch docker images, so I'm almost sure it's about spawning processes from bazel daemon but docker itself.

While `Operation not permitted` is a kinda specific error appears on MAC (Mandatory Access Control) systems like SIP in macOS or SELinux, AppArmor on Linux.

Thanks!

**Comment by jmmv** [comment]
Given that `--spawn_strategy=standalone` fixes the problem, this sounds like the sandbox at play. And it makes sense: actions shouldn't be allowed to poke at your home directory freely, and the sandbox denies that.

What exact command are you running? I don't have a lot of context on how we interact with Docker, so I'm wondering where that gcloud call comes from.

**Comment by teran** [comment]
@jmmv,

First of all thanks for your reply.

> Given that `--spawn_strategy=standalone` fixes the problem, this sounds like the sandbox at play. And it makes sense: actions shouldn't be allowed to poke at your home directory freely, and the sandbox denies that.
That sounds reasonable but I wondering if bazel have mechanisms allowing to return `EPERM` error on filesystem access?

> What exact command are you running? I don't have a lot of context on how we interact with Docker, so I'm wondering where that gcloud call comes from.
From bazel side I'm running `bazel test //...` (it will work with any command fetching dependencies from GCR).
In Docker (config.json) it's configured to run `gcloud` authentication helper which is actually:
```
/usr/local/bin/docker-credential-gcloud -> /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/docker-credential-gcloud
```

Please let me know if you need any further details.

Thanks in advance.

**Comment by teran** [comment]
@jmmv 

I've just also tested running exactly the same configuration on Linux with gcloud CLI and also doesn't work but with another error (bellow). So it looks you're right about sandboxing and it's not about macOS itself.

```
WARNING: Could not setup log file in /root/.config/gcloud/logs, (IOError: [Errno 30] Read-only file system: u'/root/.config/gcloud/logs/2020.06.25/08.23.28.733578.log')
ERROR: (gcloud.auth.docker-helper) Unable to create private file [/root/.config/gcloud/credentials.db]: [Errno 30] Read-only file system: '/root/.config/gcloud/credentials.db'
--- FAIL: TestMeterPrototypes (0.59s)
    suite.go:39:
        	Error Trace:	suite.go:39
        	            				suite.go:118
        	            				run_test.go:10
        	Error:      	Received unexpected error:
        	            	error getting credentials - err: exit status 1, out: ``
        	Test:       	TestMeterPrototypes
FAIL
```

Thanks!

**Comment by jmmv** [comment]
> That sounds reasonable but I wondering if bazel have mechanisms allowing to return EPERM error on filesystem access?

I'm not sure what you are asking for there. The gcloud call is already failing with an EPERM, isn't it?

Note that Bazel just runs a subprocess. It has no way to know what that subprocess will do I/O-wise upfront. That's why the sandbox exists: to prevent the subprocess accessing state it's not supposed to. But then, if the subprocess does any of this, you should expect it to fail.

> I've just also tested running exactly the same configuration on Linux with gcloud CLI and also doesn't work but with another error (below). So it looks you're right about sandboxing and it's not about macOS itself.

Note that the Linux and macOS sandboxes are not exactly equivalent -- and they cannot be because each OS offers different functionality for sandboxing. But yes, they both catch the problem of the tool trying to write into the user's home directory (with different error messages).

And this is very much intentional. Either whatever rule that runs docker should tell gcloud to put its configuration files elsewhere, or the rule should be marked as `no-sandbox` to always ignore the sandbox.
