### ISSUE TITLE
Support for lib groups?

### ISSUE THREAD

**Issue by rnburn** [bazelbuild/bazel#11593]
### Description of the problem / feature request:

What's the status of bazel's support for lib groups?

Is it possible to have multiple pre-compiles static libraries linked together as a group with something like
```
-Wl,--start-group libA.a libB.a … -Wl,--end-group
```
### Feature requests: what underlying problem are you trying to solve with this feature?

There are libraries out there that require being grouped on the link line.

Intel's MKL library is one example. These are the commands suggested by its [link-adviser](https://software.intel.com/content/www/us/en/develop/articles/intel-mkl-link-line-advisor.html)
```
 -Wl,--start-group ${MKLROOT}/lib/intel64/libmkl_intel_ilp64.a ${MKLROOT}/lib/intel64/libmkl_tbb_thread.a ${MKLROOT}/lib/intel64/libmkl_core.a -Wl,--end-group -ltbb -lstdc++ -lpthread -lm -ldl
```
It would be nice to be able to support vendored binaries for libraries like MKL within a project's repo.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Go try to set up a project with vendored, pre-compiled binaries for MKL.

###  Have you found anything relevant by searching the web?

Yes, I found lots of dated material discussing the problem. I'd like to know if it's now possible.

SO: https://stackoverflow.com/questions/45353395/how-to-handle-c-library-circular-dependency-in-bazel
Proposal (mentioned): https://docs.google.com/document/d/1hK2mWl3TYNL9oJYX_S020TKkXZvBw1aBoYERvTHVyfg/edit?ts=597b4f3d#
Issue: https://github.com/bazelbuild/bazel/issues/818

**Comment by rnburn** [comment]
Could this be accomplished by listing the static libraries in [data](https://docs.bazel.build/versions/master/be/common-definitions.html#common.data) and referencing them via `$(location libname)` in [linkopts](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library.linkopts)?

**Comment by oquenchil** [comment]
We don't have plans to work on this any time in the near future.

**Comment by rnburn** [comment]
@oquenchil - do you have a workaround for the use case I described?

**Comment by hohodu** [comment]
so sad.

**Comment by hlopko** [comment]
Some existing workarounds for people finding this issue:

* write a rule that un-archives multiple .a and re-archives them all into one .a
* create your own C++ toolchain (https://docs.bazel.build/versions/main/tutorial/cc-toolchain-config.html). That gives you a way to decouple files from their command line flags. So you can make those .a files be part of "compiler_files" in the toolchain, and in the `CcToolchainConfigInfo` you'll specify all the flags you need, in any order you need, as strings.

**Comment by dsciebu** [comment]
And that's it? Great job Google.

**Comment by ghorn** [comment]
I was successful using @rnburn's suggestion here https://github.com/bazelbuild/bazel/issues/11593#issuecomment-644423563, for intel mkl static libraries.

it looked like this:
```
cc_library(
    name = "mkl_static",
    srcs = [
        "@mkl_static//:lib/libmkl_core.a",
        "@mkl_static//:lib/libmkl_intel_lp64.a",
        "@mkl_static//:lib/libmkl_sequential.a",
    ],
    linkopts = [
        # These three libraries have circular dependencies in their symbols. The way to deal with
        # this in static archives is to use -Wl,start-group / -Wl,end-group around the archives.
        "-Wl,--start-group",
        "$(location @mkl_static//:lib/libmkl_intel_lp64.a)",
        "$(location @mkl_static//:lib/libmkl_sequential.a)",
        "$(location @mkl_static//:lib/libmkl_core.a)",
        "-Wl,--end-group",
        # These libraries also have some external symbols they depend on:
        "-lpthread",
        "-lm",
        "-ldl",
    ],
    linkstatic = 1,
    alwayslink = 1,
)
```
