### ISSUE TITLE
Tracefiles files are unparseable by CoverageOutputGenerator

### ISSUE THREAD

**Issue by paymog** [bazelbuild/bazel#11601]
### Description of the problem / feature request:

I believe there's a bug with how coverage.dat files are generated when using `bazel coverage`. 

Here's an example what what get's output when I examine one of these `coverage.dat` files:

```
mode: set
github.com/myorg/cnab-tools/pkg/terraform/mock_terraform.go:14.118,16.27 2 0
github.com/myorg/cnab-tools/pkg/terraform/mock_terraform.go:19.2,25.80 6 0
github.com/myorg/cnab-tools/pkg/terraform/mock_terraform.go:31.2,32.80 2 0
github.com/myorg/cnab-tools/pkg/terraform/mock_terraform.go:38.2,39.79 2 0
github.com/myorg/cnab-tools/pkg/terraform/mock_terraform.go:45.2,45.19 1 0
```

I believe this format to be incompatible with the [`LcovParser`](https://github.com/bazelbuild/bazel/blob/master/tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator/LcovParser.java#L73). The reason I believe this to be the case is that [this test](https://github.com/bazelbuild/bazel/blob/master/tools/test/CoverageOutputGenerator/javatests/com/google/devtools/coverageoutputgenerator/MainTest.java#L93) generates a sample tracefile which looks like [this](https://gist.github.com/paymog/e4fc7d690b2ac97e95491d7dadf609b2). These two file formats are quite different and when debugging the `CoverageOutputGenerator` with the generated format, I hit [this error condition](https://github.com/bazelbuild/bazel/blob/master/tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator/LcovParser.java#L101) which makes sense because the format isn't parseable.

### Feature requests: what underlying problem are you trying to solve with this feature?

NA

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

One simple way would be to point the CoverageOutputGenerator at a tracefile with the aforementioned format.
I'm still digging in to how these tracefiles get generated to see what's going on at generation time.

### What operating system are you running Bazel on?

OSX 10.15.5

### What's the output of `bazel info release`?

release 2.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

NA

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

NA

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Nope

**Comment by paymog** [comment]
I just checked that bazel 3.2.0 generates the tracefiles with the same format as bazel 2.0.0

**Comment by paymog** [comment]
Ah, it looks like when `bazel coverage` is called, the underlying coverage tool for the language is used. It looks like the unparseable output from above comes from the default go coverage tool: https://github.com/golang/go/blob/0104a31b8fbcbe52728a08867b26415d282c35d2/src/cmd/cover/profile.go#L56

**Comment by xingxinghuo1000** [comment]
```
#!/bin/bash
function run_ut_with_codecoverage() {
    echo "mode: set" > ./bazel-out/all_coverage.dat
    for cov in $(find ./bazel-out -name coverage.dat)
    do
        if [ -f $cov ]; then
            tail -q -n +2 $cov >> ./bazel-out/all_coverage.dat
        fi
    done
}
```

Maybe you need to remove first line of each coverage.dat
And then merge them

Convert to cobertura format xml
```
cat ./bazel-out/all_coverage.dat | /go/bin/gocover-cobertura > cover.xml
```

**Comment by c-mita** [comment]
The go rules (https://github.com/bazelbuild/rules_go) do not fully support coverage collection yet; `go_test` does not emit lcov data as expected by Bazel.

More background can be found on the comments here: https://github.com/bazelbuild/bazel/issues/6293#issuecomment-505557504
