### ISSUE TITLE
Documentation issue: ctx.version_file is undocumented

### ISSUE THREAD

**Issue by adam-azarchs** [bazelbuild/bazel#11607]
### Description of the problem / feature request:

A starlark rule can support stamping by looking at the `ctx.version_file` or `ctx.info_file` field.  However, this field does not appear in the [documentation for `ctx`](https://docs.bazel.build/versions/3.3.0/skylark/lib/ctx.html).  Same goes for `ctx.info_file`.

### Feature requests: what underlying problem are you trying to solve with this feature?

The semantics of version stamping in starlark rules are far from clear.  How can they use stamp information if and only if building with `--stamp`?  How can they specify stamping be on by default?  And so on.  I needed to read through the implementation of [go_binary](https://github.com/bazelbuild/rules_go/blob/280a1ed6be5a3c085aeb4ca72564b066cba64e62/go/private/rules/binary.bzl#L61) to figure out what I did.

It seems a little bit strange that the documentation is missing, because there does appear to be documentation attached to the field in the java definition of the starlark API: https://github.com/bazelbuild/bazel/blob/656cc0611b835a5fc2e549b7edf2e4501a4be0d3/src/main/java/com/google/devtools/build/lib/skylarkbuildapi/StarlarkRuleContextApi.java#L516
though I am not familiar with the process by which that documentation gets bubbled up to the documentation on the web.  That would be a good start, although as I said it would be nice to also document the conditions under which that field is or is not populated.

### What's the output of `bazel info release`?

```
release 3.3.0
```

###  Have you found anything relevant by searching the web?

There's uses of `ctx.version_file` in various rules repos including `rules_go`, `rules_nodejs` and so on.  That suggests to me that the API is expected to remain stable.

Related: https://github.com/bazelbuild/bazel/issues/4942

**Comment by laurentlb** [comment]
Duplicate with https://github.com/bazelbuild/bazel/issues/9363
