### ISSUE TITLE
incompatible_avoid_conflict_dlls: Rename DLL to avoids conflict on Windows

### ISSUE THREAD

**Issue by vnvo2409** [bazelbuild/bazel#11600]
Because DLL search paths on Windows are very limited. We choose to copy the DLLs to the binary directory. This cause DLL name conflicts when there are 2 `cc_library` with the same name but different packages (e.g `foo1:bar` and `foo2:bar`). This flag renames the DLLs that are generated by `cc_library` (`NODEPS_DYNAMIC_LIBRARY`) to avoid those conflicts. This flag will be turned on only on Windows and DynamicMode isn't off.

**Flag:** `--incompatible_avoid_conflict_dlls`

Specifically, the flag does the following:
- It calculates a hash based on repository name and package path directory.
- It generated the following file with a hash as suffix:
  + name_{hash}.dll
  + name_{hash}.dll-2.params
  + name_{hash}.pdb (generated by MSVC)
- Other files will be keep untouched
- It also changes the LIBRARY name in the .def file if the feature `windows_export_all_symbols` is turned on.

**Expected Timeline**
Will be flipped in 4.0

**Comment by vnvo2409** [comment]
cc @meteorcloudy

**Comment by vnvo2409** [comment]
@meteorcloudy I will have to make another PR for user provided .def file. I think we shouldn't rename the DLL in that case. what do you think ?

**Comment by meteorcloudy** [comment]
Oh,, you are right. If the DEF file is provided by user then it doesn't have the renamed DLL name.
Nice catch!

**Comment by meteorcloudy** [comment]
You can check Bazel's release plan by https://github.com/bazelbuild/bazel/issues?q=is%3Aopen+is%3Aissue+label%3Arelease
