### ISSUE TITLE
[Compile Failed]:Target //src:bazel failed to build

### ISSUE THREAD

**Issue by curioyang** [bazelbuild/bazel#11608]
when i compile bazel from binary source，“./compile.sh”

I got this.

`INFO: From Creating runfiles tree bazel-out/host/bin/third_party/grpc/cpp_plugin.runfiles [for host]:
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/host/bin/third_party/grpc/cpp_plugin.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/host/bin/third_party/grpc/cpp_plugin.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/host/bin/third_party/grpc/cpp_plugin.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/host/bin/third_party/grpc/cpp_plugin.runfiles_manifest: unexpected operator
INFO: From Creating runfiles tree bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer.runfiles:
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer.runfiles_manifest: unexpected operator
INFO: From Compiling src/main/cpp/blaze_util_posix.cc:
src/main/cpp/blaze_util_posix.cc: In function 'std::__cxx11::string blaze::RunProgram(const string&, const std::vector<std::__cxx11::basic_string<char> >&)':
src/main/cpp/blaze_util_posix.cc:201:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
INFO: From Creating runfiles tree bazel-out/host/bin/third_party/ijar/ijar.runfiles [for host]:
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/host/bin/third_party/ijar/ijar.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/host/bin/third_party/ijar/ijar.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/host/bin/third_party/ijar/ijar.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/host/bin/third_party/ijar/ijar.runfiles_manifest: unexpected operator
INFO: From Creating runfiles tree bazel-out/local-fastbuild/bin/third_party/java/apkbuilder/apkbuilder.runfiles:
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/third_party/java/apkbuilder/apkbuilder.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/third_party/java/apkbuilder/apkbuilder.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/third_party/java/apkbuilder/apkbuilder.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/third_party/java/apkbuilder/apkbuilder.runfiles_manifest: unexpected operator
INFO: From Creating runfiles tree bazel-out/local-fastbuild/bin/src/java_tools/junitrunner/java/com/google/testing/junit/runner/Runner.runfiles:
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/src/java_tools/junitrunner/java/com/google/testing/junit/runner/Runner.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/src/java_tools/junitrunner/java/com/google/testing/junit/runner/Runner.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/src/java_tools/junitrunner/java/com/google/testing/junit/runner/Runner.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/src/java_tools/junitrunner/java/com/google/testing/junit/runner/Runner.runfiles_manifest: unexpected operator
INFO: From Creating runfiles tree bazel-out/local-fastbuild/bin/src/java_tools/buildjar/JavaBuilder.runfiles:
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/src/java_tools/buildjar/JavaBuilder.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/src/java_tools/buildjar/JavaBuilder.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/src/java_tools/buildjar/JavaBuilder.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/src/java_tools/buildjar/JavaBuilder.runfiles_manifest: unexpected operator
INFO: From Creating runfiles tree bazel-out/local-fastbuild/bin/src/java_tools/singlejar/SingleJar.runfiles:
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/src/java_tools/singlejar/SingleJar.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/src/java_tools/singlejar/SingleJar.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/src/java_tools/singlejar/SingleJar.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/src/java_tools/singlejar/SingleJar.runfiles_manifest: unexpected operator
INFO: From Creating runfiles tree bazel-out/local-fastbuild/bin/src/java_tools/buildjar/java/com/google/devtools/build/java/turbine/turbine.runfiles:
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/src/java_tools/buildjar/java/com/google/devtools/build/java/turbine/turbine.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/src/java_tools/buildjar/java/com/google/devtools/build/java/turbine/turbine.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/src/java_tools/buildjar/java/com/google/devtools/build/java/turbine/turbine.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/src/java_tools/buildjar/java/com/google/devtools/build/java/turbine/turbine.runfiles_manifest: unexpected operator
INFO: From Creating runfiles tree bazel-out/local-fastbuild/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/genclass/GenClass.runfiles:
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/genclass/GenClass.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/genclass/GenClass.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/genclass/GenClass.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/genclass/GenClass.runfiles_manifest: unexpected operator
INFO: From Creating runfiles tree bazel-out/local-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/idlclass/classes.runfiles:
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/idlclass/classes.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/idlclass/classes.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/idlclass/classes.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/idlclass/classes.runfiles_manifest: unexpected operator
INFO: From Creating runfiles tree bazel-out/local-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/ziputils/all.runfiles:
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/ziputils/all.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/ziputils/all.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/ziputils/all.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/ziputils/all.runfiles_manifest: unexpected operator
INFO: From Creating runfiles tree bazel-out/local-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/ideinfo/classes.runfiles:
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/ideinfo/classes.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/ideinfo/classes.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/ideinfo/classes.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/ideinfo/classes.runfiles_manifest: unexpected operator
INFO: From Creating runfiles tree bazel-out/local-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/classes.runfiles:
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/classes.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 4: [: bazel-out/local-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/classes.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/classes.runfiles_manifest: unexpected operator
/tmp/bazel_lIP1aSJU/out/execroot/bazel/_bin/build-runfiles: 8: [: bazel-out/local-fastbuild/bin/src/tools/android/java/com/google/devtools/build/android/classes.runfiles_manifest: unexpected operator
ERROR: /home/curio/project/bazel/src/tools/android/java/com/google/devtools/build/android/ziputils/BUILD:20:1: Java compilation in rule '//src/tools/android/java/com/google/devtools/build/android/ziputils:ziputils_lib' failed: Worker process did not return a correct WorkResponse. This is probably caused by a bug in the worker, writing unexpected other data to stdout.
WARNING: Javac worker failed (java.io.IOException: ?????), invalidating and retrying with new worker...
Target //src:bazel failed to build
`
Because of JAVA!?   HELP ME!

**Comment by meisterT** [comment]
What's your platform?
