### ISSUE TITLE
--experimental_windows_watchfs fails when --symlink_prefix is specified

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#11619]
### Description of the problem / feature request:

Settings `--symlink_prefix=.build/` and `--experimental_windows_watchfs` together cause infinite symlink loop.

### Bugs: what's the simplest, easiest way to reproduce this bug?

Bazel user guide recommends setting `--symlink_prefix=.bazel/` to reduce clutter and that is what we do. With the arrival of Bazel 3.3.0 we tried new setting `common --experimental_windows_watchfs` in .bazelrc file and as the result we observe this in the build output: ```WARNING: Error encountered with local file system watcher java.nio.file.FileSystemException: D:\dev\bazel\product_root\.build\product_root\.build\product_root\.build\product_root\.build\product_root\.build\product_root\.build\product_root\.build\product_root\.build\product_root\.build\product_root\.build\product_root\.build\product_root\.build\product_root\.build\product_root\.build\product_root\.build\product_root\.build\product_root\.build: The name of the file cannot be resolved by the system.
... temporarily falling back to manually checking files for changes```

Apparently this is caused by the folder `.build` (specified by --symlink_prefix) where Bazel creates symlink `product_root` (root of the workspace). This somehow confuses file system watcher on Windows. 

### What operating system are you running Bazel on?

Windows 10 1806.

### What's the output of `bazel info release`?

3.3.0

###  Have you found anything relevant by searching the web?

Relevant pull request: https://github.com/bazelbuild/bazel/pull/11334

### Any other information, logs, or outputs that you want to share?

Author of the pull request: @tomdegoede

**Comment by tomdegoede** [comment]
Hi Konste, thanks for letting me know!

It seems that the default `bazel-*` symlinks are not symlinked in the execroot but when specifying `--symlink_prefix=.build/` the second invocation (after taking a long time) symlinks the .build folder in the execroot causing the infinite symlink loop.

I'm wondering how other OS scenarios are not hurt by this.

**Comment by tomdegoede** [comment]
Two more observations.
1. When I shutdown bazel after the .build symlink is created inside execroot, and reboot bazel again it seems to work properly.
2. I never get the exception you listed. Maybe that's due to my permissive path length settings?

I have a feeling that the watcher incorrectly registers the .build folder to be watched when it's created.

**Comment by konste** [comment]
Tom, thank you for looking into this! 
What setting do you mean when you said `my permissive path length settings`?

**Comment by tomdegoede** [comment]
I'm referring to the LongPathsEnabled setting that allows paths longer than 260 characters. It's just a guess to why I'm not seeing the same error. I do encounter a very long loading times so there's definitely something going wrong.

**Comment by konste** [comment]
So I have checked and apparently I have LongPathsEnabled setting enabled on my Windows machines. And still I see the warning `Error encountered with local file system watcher...` periodically.

**Comment by tomdegoede** [comment]
The only warning I encounter every now and then (e.g. after big checkouts) is "WARNING: Overflow when watching local filesystem for changes... temporarily falling back to manually checking files for changes". Are you still seeing "The name of the file cannot be resolved by the system"?

**Comment by konste** [comment]
We also mostly see `WARNING: Overflow when watching local filesystem for changes...` now.
@tomdegoede Any chance you can do something to make it more reliable?

**Comment by philwo** [comment]
@konste @tomdegoede Was this fixed by https://github.com/bazelbuild/bazel/commit/0cdd71fe9782c7817fc1e0294285699fb4db8040 or is this still an issue?

**Comment by konste** [comment]
The fix should be in 3.7.0. right? I am going to test it today and get back to you. The issue was intermittent, so it would take a full day to make sure.

**Comment by konste** [comment]
This is confusing: description of [0cdd71f](https://github.com/bazelbuild/bazel/commit/0cdd71fe9782c7817fc1e0294285699fb4db8040) contains this paragraph in strikethrough font: ~~The downside of this approach is that the convenience symlinks must be at the root of the workspace. When using --symlink_prefix with a sub-directory (which is the case for in the linked issue) both issues would still occur.~~

Current issue #11619 is specifically about using both flags together `--experimental_windows_watchfs` and `--symlink_prefix`. If the paragraph above is true, then current issue is NOT fixed. But strikethrough font confuses me. 

@tomdegoede could you please clarify? 

My best guess at the moment is that the current issue is not fixed.

**Comment by tomdegoede** [comment]
@konste please refer to #12054. It implements a second solution (hence the strikethrough) that should also have resolved your issue.

**Comment by konste** [comment]
Thank you @tomdegoede for response! I am happy to report that my testing shows this issue is indeed fixed and can be closed! Woohoo! Before we go I have a couple questions to understand the feature mechanics and implications.

Question 1: In the root workspace we have some folders not directly relevant to the build - some just don't have any BUILD files in there and some are explicitly excluded through .bazelignore. Are those folders being watched and does it have any implications? Is there perf or memory hit if those folders happen to be big? Specific reason I am asking is because I noticed that such folder (without BUILD files) become locked and cannot be deleted without Bazel shutdown first.

Question 2: some sources come from external repositories and live under Bazel output folder during the build. If such source is modified Bazel notices the change and rebuilds it. Is this behavior affected by --watchfs? Because as far as I understand Bazel output folder is not watched. If it still works, then how those changes get noticed?

I will try to get a clean repro for a folder locking and if it is reproducible open a separate issue for it. Thanks again!
