### ISSUE TITLE
Bazel build for Tensorflow fails - error: undefined reference to 'google::protobuf'

### ISSUE THREAD

**Issue by edualvarado** [bazelbuild/bazel#11610]
### Description of the problem / feature request:

I am trying to use `bazel build` like in this [example.](https://medium.com/jim-fleming/loading-a-tensorflow-graph-with-the-c-api-4caaff88463f). I already clonned Tensorflow, configure it and built it from source with Bazel with no errors.

When I try to do ` bazel build :loader` in the example of the previous link, the building ends and when it finishes, it gives me a bunch of huge command lines with several errors for `undefined references to...`. Many of them, are like this:

```
bazel-out/k8-opt/bin/tensorflow/core/protobuf/tpu/_objs/optimization_parameters_proto_cc_impl/optimization_parameters.pb.o:optimization_parameters.pb.cc:function tensorflow::tpu::ClippingLimits::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*): error: undefined reference to 'google::protobuf::FloatValue* google::protobuf::Arena::CreateMaybeMessage<google::protobuf::FloatValue>(google::protobuf::Arena*)'
```

Finally, the terminal displays:

```
Target //tensorflow/loader:loader failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1903.081s, Critical Path: 267.24s
INFO: 1840 processes: 1840 local.
FAILED: Build did NOT complete successfully
```

I have read that it may be a compatibility problem with `protobuf`, `bazel` or `gcc`. Therefore, I try building by using this command (according to the Tensorflow webpage):
`
bazel build --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" :loader
`
But it did not work either. I get the exact same error.

### What operating system are you running Bazel on?

`Ubuntu 18.04.4 LTS`

### What's the output of `bazel info release`?

I use a conda environment with `Bazel 3.1.0`.
My  `gcc` version is `7.5.0`

Any idea?
Thank you!

**Comment by aiuto** [comment]
You are probably best off asking in a tensorflow list on stackoverflow.
