### ISSUE TITLE
Delete all (or most of) the migration-* labels

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#11625]
They add clutter while triaging issues and most are empty.

For ongoing release windows, we could be using miilestones instead.

@philwo WDYT?

**Comment by laurentlb** [comment]
Which ones are empty?

**Comment by aiuto** [comment]
migration-0.* migration-1.*
Even when they are not empty, they are not irrelevant since we are are on 3.x

**Comment by laurentlb** [comment]
We need to make sure that people can still migrate out of old releases. We should be careful before deleting data.

**Comment by aiuto** [comment]
The breaking-change labels are the ones useful to users, because those tell you when the change actually went in. The migration ones are much noisier because they got added repeatedly until the feature landed.  e.g.
https://github.com/bazelbuild/bazel/issues?q=label%3Amigration-0.21+is%3Aclosed

**Comment by laurentlb** [comment]
They are used by Bazelisk.
I agree they can be noisy, but that's the process we agreed one year ago.

**Comment by aiuto** [comment]
I believe this is done.  Not sure who did it
