### ISSUE TITLE
Incremental builds still broken for C++

### ISSUE THREAD

**Issue by kayasoze** [bazelbuild/bazel#1162]
See the last few comments of https://github.com/bazelbuild/bazel/issues/473.

**Comment by damienmg** [comment]
@ulfjack ping? Can you have a look?

**Comment by ulfjack** [comment]
Yes, see #1286.

We shouldn't disable the inclusion checks when files are included through includes. This might break code both internally and externally, unfortunately.

**Comment by ulfjack** [comment]
I don't have any cycles to work on this, unfortunately, but I can help if someone else wants to tackle this.

**Comment by kayasoze** [comment]
Personally, I'd consider this a P1 or higher, as it turns Bazel's tagline into: "~~Correct~~, ~~reproducible~~, fast builds for everyone.", (or, alternatively, ~~fast~~, as incremental builds cannot be used) and this unsafety isn't documented.  However, I don't know how prevalent `includes` usage is.  In our builds, it's used extensively, not only for third-party builds, but to prevent extremely long include paths in our own code.

**Comment by ulfjack** [comment]
Excessive use of includes can significantly increase compile times. I tested both gcc and clang, and they both require quadratic time in the number of includes in a single compile invocation, though the constant factor is fairly low (that part of the compiler is highly optimized).

That doesn't solve this problem, of course.

**Comment by ulfjack** [comment]
I'm working to re-enable the checks for -isystem, but that requires an internal cleanup, which will take days or maybe weeks.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
