### ISSUE TITLE
Figure out what to do with non-runfiles symbolic links on Windows

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#1163]
https://github.com/bazelbuild/bazel/blob/0773430188885e075121ebf720c82bb05a39db21/src/main/java/com/google/devtools/build/lib/vfs/WindowsFileSystem.java#L45
Now, we are directly copying files, which is not right.@dslomov

**Comment by meteorcloudy** [comment]
Shall we use the same hack way we create junction to create hard link? Because there is no jni on windows yet.

**Comment by damienmg** [comment]
You can create hard links with Java, no need to shell out or to use JNI

**Comment by meteorcloudy** [comment]
Nice.

**Comment by laszlocsomor** [comment]
Indeed, I just tried this, [`java.nio.file.Files.createLink`](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#createLink(java.nio.file.Path,%20java.nio.file.Path)) works like a charm, even without elevation. Not so much with [`java.nio.file.Files.createSymbolicLink`](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#createSymbolicLink(java.nio.file.Path,%20java.nio.file.Path,%20java.nio.file.attribute.FileAttribute...)), that throws `FileSystemException` saying "A required privilege is not held by the client."

**Comment by laszlocsomor** [comment]
I have a pending fix for this.

**Comment by laszlocsomor** [comment]
Haha, not so fast. @dslomov points out in https://github.com/bazelbuild/bazel/issues/1212#issue-151841993 why hard links aren't a good idea...

**Comment by laszlocsomor** [comment]
Demoting to P2 since we've been doing fine with copying, so I don't see P1 justified.

**Comment by laszlocsomor** [comment]
Closing, since the bug title is "Figure out what to do ..." and we've been doing find with copying.
