### ISSUE TITLE
How to pass SDKROOT to remote mac workers with multiple SDKs?

### ISSUE THREAD

**Issue by thna123459** [bazelbuild/bazel#11635]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

When building remotely for MacOS, one typically uses an execution policy script to work around DEVELOPER_DIR and SDKROOT not being passed to the remote workers. In our case we have several sdk roots, so trying to force one SDKROOT results in errors:
`clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]`
It is also impractical to try to guess the sdk root in all the wrapper

### Feature requests: what underlying problem are you trying to solve with this feature?

We are trying to do remote build for multiple SDKs from the same code base and this seems to be unsupported at this point.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Use the iOS example from the tutorial, and build both an iOS and a macos app at the same time. This works locally. Then try to perform a remote build:

````
export DEVELOPER_DIR=/Applications/Xcode-1141.app/Contents/Developer
export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
export BAZEL_OPTS=" --action_env=DEVELOPER_DIR=$DEVELOPER_DIR --action_env=SDKROOT=$SDKROOT"
bazel build --remote_executor=grpc://buildfarm:8980 //ios-app:ios-app
```

Errors will be observed for one or the other SDKROOT value, it is not possible to have one value that works for both mac and ios targets.

Chances are, one will need to setup an execution policy to replace/inject the correct DEVELOPER_DIR/SDKROOT for each command. This becomes impactical when running rules that for example run pip. One basically has to parse every command to guess which SDK root to use.

Besides the lack of support for remote builds with multiple SDK, I believe that there should be some sort of environment variable/unique identifier propagated to the remote build to indicate what platform/configuration was intended.

### What operating system are you running Bazel on?

MacOS

### What's the output of `bazel info release`?

release 3.3.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by keith** [comment]
Discussed in slack a bit as well, but the remote execution server needs to take the environment variables that bazel does set, specifically:

- `XCODE_VERSION_OVERRIDE`
- `APPLE_SDK_PLATFORM`
- `APPLE_SDK_VERSION_OVERRIDE`

And resolve those outside of your bazel invocation to the correct paths. This way your builds remain reproducible even if Xcode paths differ per machine.

**Comment by thna123459** [comment]
We were confused by commands that will always run locally despite the remote build settings. Thank you for your answer!
