### ISSUE TITLE
--noremote_upload_local_results disables writing to remote cache AND local disk_cache completely

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#11631]
### Description of the problem / feature request:

When both `--disk_cache=<path>` and  `--noremote_upload_local_results` are specified local disk cache is effectively disabled.

### Feature requests: what underlying problem are you trying to solve with this feature?

It is typical to specify `--disk_cache=<path>` to accelerate the build using local disk cache.
Now when remote caching comes into play it is also typical to only allow CI build servers to populate the cache, while developers supposed to have read-only access to the cache. To achieve that read-only access the only option available is `--noremote_upload_local_results`. 
The problem is `--noremote_upload_local_results` not only disables populating remote cache, but also disables populating local disk_cache, which causes substantial degradation of the build performance.
`--noremote_upload_local_results` blocks local disk_cache even in the case when actual remote cache is not even used. 

### What operating system are you running Bazel on?

Linux, Windows and Mac.

### What's the output of `bazel info release`?

3.3.0

### Any other information, logs, or outputs that you want to share?

I know that `--disk_cache` is internally implemented as a "flavor" of remote cache, but it should not be affected by `--noremote_upload_local_results`. disk_cache is not enabled by default, it is only provided when `--disk_cache=<path>` is specified, so the presence of `--disk_cache=<path>` is the signal that disk_cache is requested and it should be read-write (it does not make sense for the local cache to be read-only). Therefore `--noremote_upload_local_results` should be applicable only to real remote cache and not to disk_cache.

**Comment by keith** [comment]
You can use `--incompatible_remote_results_ignore_disk` to fix this

**Comment by konste** [comment]
Wow that was fast! Thank you @keith!

**Comment by coeuvre** [comment]
Hi Konstantin, does `--incompatible_remote_results_ignore_disk` work for you? Can we close the issue?

**Comment by konste** [comment]
Yes, it works for us. Thank you!
