### ISSUE TITLE
InstrumentedFilesInfo is not available from Starlark

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/bazel#11632]
### Description of the problem / feature request:

https://docs.bazel.build/versions/master/skylark/rules.html#code-coverage-instrumentation and https://docs.bazel.build/versions/master/skylark/lib/InstrumentedFilesInfo.html describe a provider named `InstrumentedFilesInfo`. However, this provider cannot be used from Starlark rule/aspect implementations:

```console
$ bazel build mytarget
ERROR: foo.bzl:6:18: name 'InstrumentedFilesInfo' is not defined
```
I've also tried scoping to `native` and `coverage_common`.

### Feature requests: what underlying problem are you trying to solve with this feature?

I need to write a rule which rolls up all of the `.gcno` files created when building with `--collect_code_coverage`. I believe they would be available via `InstrumentedFilesInfo.metadata_files`. (The `.gcno` files will be deployed to an external integration test environment.)

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

`release 3.3.0-vmware`; this includes a backport of 2e5cb1a0f4efaeea2ccc96249f855c7a15c3dabf.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a

###  Have you found anything relevant by searching the web?

No.

**Comment by beasleyr-vmw** [comment]
@nacl is looking into internally and may generate a PR.

**Comment by benjaminp** [comment]
78bb263e46bf301900c1d4b1e04fabf3a6854762
