### ISSUE TITLE
FAILED: Build did NOT complete successfully (0 packages loaded)

### ISSUE THREAD

**Issue by MevadaRavikumar** [bazelbuild/bazel#11648]
Hi, 
I want to convert TensorFlow frozen quantized graph into tflite model.  To mkae this model I have used tensorflow version 1.15, Anaconda Spyder 3.7, 64 bit windows 10, Bazel 0.24.1. 

I was following this tutorial to convert the model. (https://github.com/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi)

When I am running "bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package ". It gives me this kind of error: 

    INFO: Options provided by the client:
      Inherited 'common' options: --isatty=1 --terminal_columns=120
    INFO: Options provided by the client:
      'build' options: --python_path=C:/Users/Ravi/anaconda3/envs/tensorflow-make/python.exe
    INFO: Reading rc options for 'build' from c:\tensorflow-make\tensorflow\.bazelrc:
      'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true -- 
       define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc -- 
        define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include -- 
        copt=-w --config=v1
        INFO: Reading rc options for 'build' from c:\tensorflow-make\tensorflow\.tf_configure.bazelrc:
           'build' options: --action_env PYTHON_BIN_PATH=C:/Users/Ravi/anaconda3/envs/tensorflow-make/python.exe --action_env 
         PYTHON_LIB_PATH=C:/Users/Ravi/anaconda3/envs/tensorflow-make/lib/site-packages -- 
        python_path=C:/Users/Ravi/anaconda3/envs/tensorflow-make/python.exe --config monolithic --copt=-w --host_copt=-w -- 
        copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI -- 
       verbose_failures --distinct_host_configuration=false --define=override_eigen_strong_inline=true --action_env  
        TF_CONFIGURE_IOS=0
        INFO: Found applicable config definition build:v1 in file c:\tensorflow-make\tensorflow\.bazelrc: --define=tf_api_version=1 -- 
       action_env=TF2_BEHAVIOR=0
        INFO: Found applicable config definition build:monolithic in file c:\tensorflow-make\tensorflow\.bazelrc: --define 
        framework_shared_object=false
        INFO: Found applicable config definition build:opt in file c:\tensorflow-make\tensorflow\.tf_configure.bazelrc: -- 
       copt=/arch:AVX --define with_default_optimizations=true
        INFO: Repository 'io_bazel_rules_docker' used the following cache hits instead of downloading the corresponding file.
     * Hash '6287241e033d247e9da5ff705dd6ef526bac39ae82f3d17de1b69f8cb313f9cd' for 
        https://github.com/bazelbuild/rules_docker/releases/download/v0.14.3/rules_docker-v0.24.1.tar.gz
        If the definition of 'io_bazel_rules_docker' was updated, verify that the hashes were also updated.
        ERROR: error loading package '': Encountered error while reading extension file 'toolchains/docker/toolchain.bzl': no such 
        package '@io_bazel_rules_docker//toolchains/docker': java.io.IOException: Error extracting 
        C:/users/ravi/_bazel_ravi/mxogbt5u/external/io_bazel_rules_docker/rules_docker-v0.24.1.tar.gz to 
        C:/users/ravi/_bazel_ravi/mxogbt5u/external/io_bazel_rules_docker: Prefix "rules_docker-0.24.1" was given, but not found in 
        the archive. Here are possible prefixes for this archive: "rules_docker-0.14.3".
       ERROR: error loading package '': Encountered error while reading extension file 'toolchains/docker/toolchain.bzl': no such 
         package '@io_bazel_rules_docker//toolchains/docker': java.io.IOException: Error extracting 
        C:/users/ravi/_bazel_ravi/mxogbt5u/external/io_bazel_rules_docker/rules_docker-v0.24.1.tar.gz to 
        C:/users/ravi/_bazel_ravi/mxogbt5u/external/io_bazel_rules_docker: Prefix "rules_docker-0.24.1" was given, but not found in 
        the archive. Here are possible prefixes for this archive: "rules_docker-0.14.3".
        INFO: Elapsed time: 7.326s
        INFO: 0 processes.
        FAILED: Build did NOT complete successfully (0 packages loaded)

I also have tried with "bazel --output_user_root=D:/build/tensorflow build --config=opt //tensorflow/tools/pip_package:build_pip_package --local_resources 2048,.5,1.0", but still errors. 

I got to know that you need to modify the WORKSPACE file. I did that also. 
My Tensorflow WORKSPACE file looks something like this: 

Path: C:\tensorflow-make\tensorflow

    workspace(name = "org_tensorflow")

    load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
    http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "aed1c249d4ec8f703edddf35cbe9dfaca0b5f5ea6e4cd9e83e99f3b0d1136c3d",
    strip_prefix = "rules_docker-0.7.0",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.7.0.tar.gz"],
)

    # Download the rules_docker repository at release v0.14.3
    http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "6287241e033d247e9da5ff705dd6ef526bac39ae82f3d17de1b69f8cb313f9cd",
    strip_prefix = "rules_docker-0.24.1",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.14.3/rules_docker-v0.24.1.tar.gz"],
)

    # OPTIONAL: Call this to override the default docker toolchain configuration.
    # This call should be placed BEFORE the call to "container_repositories" below
    # to actually override the default toolchain configuration.
    # Note this is only required if you actually want to call
    # docker_toolchain_configure with a custom attr; please read the toolchains
    # docs in /toolchains/docker/ before blindly adding this to your WORKSPACE.
     # BEGIN OPTIONAL segment:
    load("@io_bazel_rules_docker//toolchains/docker:toolchain.bzl",
    docker_toolchain_configure="toolchain_configure"
)
        docker_toolchain_configure(
           name = "docker_config",
          # OPTIONAL: Path to a directory which has a custom docker client config.json.
          # See https://docs.docker.com/engine/reference/commandline/cli/#configuration-files
          # for more details.
          client_config="<enter absolute path to your docker config directory here>",
         # OPTIONAL: Path to the docker binary.
          # Should be set explcitly for remote execution.
          docker_path="<enter absolute path to the docker binary (in the remote exec env) here>",
          # OPTIONAL: Path to the gzip binary.
          # Either gzip_path or gzip_target should be set explcitly for remote execution.
          gzip_path="<enter absolute path to the gzip binary (in the remote exec env) here>",
          # OPTIONAL: Bazel target for the gzip tool.
          # Either gzip_path or gzip_target should be set explcitly for remote execution.
          gzip_target="<enter absolute path (i.e., must start with repo name @...//:...) to an executable gzip target>",
          # OPTIONAL: Path to the xz binary.
          # Should be set explcitly for remote execution.
          xz_path="<enter absolute path to the xz binary (in the remote exec env) here>",
          # OPTIONAL: List of additional flags to pass to the docker command.
          docker_flags = [
        "--tls",
        "--log-level=info",
      ],

)
    # End of OPTIONAL segment.

    load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)
    container_repositories()

    # This is NOT needed when going through the language lang_image
    # "repositories" function(s).
    load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

    container_deps()

    load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
)

    container_pull(
      name = "java_base",
       registry = "gcr.io",
       repository = "distroless/java",
      # 'tag' is also supported, but digest is encouraged for reproducibility.
       digest = "sha256:deadbeef",
)

What I can do extra to build TensorFlow CPU version?

**Comment by jin** [comment]
Please file an issue on the Tensorflow repository for TF specific problems.
