### ISSUE TITLE
Starlark build  settings options on the command line does not take precedence over those in rc files.

### ISSUE THREAD

**Issue by liji-canva** [bazelbuild/bazel#11646]
### Description of the problem / feature request:

Starlark build  settings options on the command line does not take precedence over those in rc files.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Use `https://github.com/bazelbuild/examples` to reproduce this bug.

```bash
cd rules/starlark_configurations/basic_build_setting
echo 'build --//starlark_configurations/basic_build_setting:coffee-temp=HOT' > bazelrc
bazel --bazelrc=./bazelrc build :today --//starlark_configurations/basic_build_setting:coffee-temp=ICED
```

As the option on command line should take precedence over those in rc files. The expected output should be something like
`DEBUG: repopath/examples/rules/starlark_configurations/basic_build_setting/defs.bzl:36:5: ICED`, but the actual output is `DEBUG: repopath/examples/rules/starlark_configurations/basic_build_setting/defs.bzl:36:5: HOT`

### What operating system are you running Bazel on?

macOS Catalina Version 10.15.5

### What's the output of `bazel info release`?

release 3.3.0

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

No

**Comment by katre** [comment]
@juliexxia This is pretty concerning, can you take a look?

**Comment by gregestren** [comment]
I'm pretty sure this is a result of https://github.com/bazelbuild/bazel/blob/ddb9b9a60c4df7defcac7c7141dff5eaf411b1f4/src/main/java/com/google/devtools/build/lib/runtime/BlazeOptionHandler.java#L209-L217

So Bazel always parses explicit command-line options first, followed by bazelrc options. According to the "last one wins" principle, you'd think bazelrc options always take precedence, even for non-Starlark flags like `--cpu`.

But the reason non-Starlark falgs work is they also apply a priority ordering:

https://github.com/bazelbuild/bazel/blob/ddb9b9a60c4df7defcac7c7141dff5eaf411b1f4/src/main/java/com/google/devtools/build/lib/runtime/BlazeOptionHandler.java#L212

vs.

https://github.com/bazelbuild/bazel/blob/ddb9b9a60c4df7defcac7c7141dff5eaf411b1f4/src/main/java/com/google/devtools/build/lib/runtime/BlazeOptionHandler.java#L188

But these priorities aren't applied to Starlark flags, which are simply considered String-typed "residue" until retrieved at https://github.com/bazelbuild/bazel/blob/ddb9b9a60c4df7defcac7c7141dff5eaf411b1f4/src/main/java/com/google/devtools/build/lib/runtime/StarlarkOptionsParser.java#L88-L89

So I think the answer is to apply priority ordering to Starlark flags as well.

**Comment by jin** [comment]
Is this still a P1 bug?

**Comment by gregestren** [comment]
FYI configurability core devs reviewed and agree this is an issue worth pursuing. But we're not P1-prioritizing it now because it doesn't seem to be P1-level disruptive. 

Always happy to help guide anyone interesting in patching if we don't visit it soon enough.

**Comment by aranguyen** [comment]
This issue been verified to be fixed by this commit https://github.com/bazelbuild/bazel/commit/8dea9886df243491c461711e0b05b1e450174ee7. It is part of release https://github.com/bazelbuild/bazel/releases/tag/6.0.0-pre.20211101.2. Please re-open or create another issue if you still experience any issue.
