### ISSUE TITLE
List of providers returned by the rule cannot be appended to

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#11654]
### Description of the problem / feature request:

When the rule returns default provider and some other provider, then
```
    # This works.
    return [DefaultInfo(files = output_depset), my_provider]

    # This does not work
    return [DefaultInfo(files = output_depset)].append(my_provider)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have provided the minimal repro [here](https://github.com/Bazel-snippets/providers_list).

When the second variant of the return statement is selected, then there is no error, but the rule behaves like it is returning empty list.

Why I need that second form? Actual rule returns variable number of providers depending on configuration, therefore I need a way to build the list of providers to return dynamically.

### What operating system are you running Bazel on?

Linux, Windows, MacOS.

### What's the output of `bazel info release`?

3.3.0

**Comment by Yannic** [comment]
Isn't the problem here that `.append()` returns `None` and not the modified list [1] (like Python does)? 

Can you try the snipped below?
```starlark
providers = [DefaultInfo(files = output_depset)]
providers.append(my_provider)
return providers
```

[1] https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/syntax/StarlarkList.java;l=378;drc=b017468d07da1e45282b9d153a4308fdace11eeb

**Comment by konste** [comment]
@Yannic Indeed, you are right! Thanks a lot for the tip!
But it is so-o confusing. Even after I tried your snippet and learned that it works it was still not immediately obvious what is the difference between your code and my code. Your reference to Bazel source code helped.
