### ISSUE TITLE
bazel_external_repository_test: ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by ehrtro** [bazelbuild/bazel#11663]
### Description of the problem / feature request: 
When running **bazel_external_repository_test** we're encountering the following issue:
`fastbuild/bin/src/test/py/bazel/bazel_external_repository_test.runfiles/io_bazel/src/test/py/bazel/bazel_external_repository_test.py", line 19, in <module>
from six.moves import SimpleHTTPServer
ModuleNotFoundError: No module named 'six'`  

.. where the failing line in the tests looks like this: `from six.moves import SimpleHTTPServer
`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Reproducing this issue is fairly hard since we're not 100% sure about what's causing this issue in our specific environment.

### What operating system are you running Bazel on?
Red Hat Enterprise Linux 7 (RHEL7)

###  Have you found anything relevant by searching the web?
No

### Any other information, logs, or outputs that you want to share?
When looking in the relevant BUILD-file we find that the BUILD initially looks like:

`py_test(
    name = "bazel_external_repository_test",
    size = "medium",
    srcs = ["bazel_external_repository_test.py"],
    data = glob(["testdata/bazel_external_repository_test/**"]),
    tags = [
        "requires-network",
    ],
    deps = [
        ":test_base"
    ],
)`

Which results in the issue stated as above. 

But by adding: `//third_party/py/six` in the list of dependencies, resulting in 
`py_test(
    name = "bazel_external_repository_test",
    size = "medium",
    srcs = ["bazel_external_repository_test.py"],
    data = glob(["testdata/bazel_external_repository_test/**"]),
    tags = [
        "requires-network",
    ],
    deps = [
        ":test_base",
        "//third_party/py/six",
    ],
)`

This issue is fixed and no more issues are envoked when running the test. 

So now to the question: We do not understand how this test can pass in the orignial Bazel repo without this dependency added to the list. We're still not sure if this might is to be seen as a bug in the system, or if it is something related to our own environment? Thoughts on this?

**Comment by meisterT** [comment]
cc @brandjon

**Comment by ehrtro** [comment]
@meisterT , @brandjon 

Any further progress on this isse? It seems like https://github.com/bazelbuild/bazel/pull/11664 would solve this issue without breaking something else.

**Comment by meisterT** [comment]
cc @meteorcloudy 
Yun, do you have any idea whether we do anything special with this test on the Bazel CI images?

**Comment by meteorcloudy** [comment]
I guess it's because `six` is pre-installed in the docker we run on CI for bazel test?
https://github.com/bazelbuild/continuous-integration/blob/4d2a7dab6c4767e741683c5e68fc5b737a7b9805/buildkite/docker/ubuntu1804/Dockerfile#L40

**Comment by jtillwickEA** [comment]
Still no fix for this.
