### ISSUE TITLE
Bazel bootstrap fails on x86_64 Debian testing

### ISSUE THREAD

**Issue by tytso** [bazelbuild/bazel#11660]
### Description of the problem / feature request:

Following the instructions at https://docs.bazel.build/versions/master/install-compile-source.html fails with:

ERROR: infinite symlink expansion detected
[start of symlink chain]
/usr/bin/X11
/usr/bin

However, there is no symlink infinite expansion that I can see:

<tytso@lambda> {/usr/projects/bazel/source}  
1138% ls -ld /usr/bin/X11
0 lrwxrwxrwx 1 root root 1 May  3  2017 /usr/bin/X11 -> ./
<tytso@lambda> {/usr/projects/bazel/source}  
1139% ls -ld /usr/bin
136 drwxr-xr-x 2 root root 135168 Jun 28 19:14 /usr/bin/
<tytso@lambda> {/usr/projects/bazel/source}  
1140% (cd /usr/bin/X11 ;  /bin/pwd)
/usr/bin

... and uninstalling X Windows just so that Bazel can be built is not reasonable.  (I've already uninstalled Clang 6.0, since that was causing another "infinite Symlink" warning which was not actually a infinite recursive loop.)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Install a standard Debian testing system with X windows installed.   Unpack bazel-3.3.0-dist.zip (sha1sum source 2b78a9bd5572b6a0dedca81e943e9d373f66ce59) into /usr/projects/bazel/source.   Then run (as per directions):

%env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh

You will get the output:

🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
DEBUG: /tmp/bazel_Wyu6Z5Dn/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:14: 
Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '3.1.0'
DEBUG: /tmp/bazel_Wyu6Z5Dn/out/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True 
DEBUG: /tmp/bazel_Wyu6Z5Dn/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:14: 
Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '3.1.0'
DEBUG: /tmp/bazel_Wyu6Z5Dn/out/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True 
DEBUG: /tmp/bazel_Wyu6Z5Dn/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:47:14: 
Current Bazel is not a release version, cannot check for compatibility.
DEBUG: /tmp/bazel_Wyu6Z5Dn/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:49:14: Make sure that you are running at least Bazel 0.21.0.
DEBUG: /tmp/bazel_Wyu6Z5Dn/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:47:14: 
Current Bazel is not a release version, cannot check for compatibility.
DEBUG: /tmp/bazel_Wyu6Z5Dn/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:49:14: Make sure that you are running at least Bazel 0.21.0.
ERROR: infinite symlink expansion detected
[start of symlink chain]
/usr/bin/X11
/usr/bin
[end of symlink chain]
ERROR: /tmp/bazel_Wyu6Z5Dn/out/external/bazel_tools/tools/jdk/BUILD:336:6: no such package '@local_jdk//': Symlink issue while evaluating globs: Infinite symlink expansion: /usr/bin/X11- > /usr/bin and referenced by '@bazel_tools//tools/jdk:jdk'
ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted: Analysis failed
INFO: Elapsed time: 11.489s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (286 packages loaded, 7757 targets\
 configured)

ERROR: Could not build Bazel

### What operating system are you running Bazel on?

Linux -- Debian Testing

### What's the output of `bazel info release`?

N/A --- am trying to build a bootstrap version of debian

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A --- Bazel is not building using bootstrap mode

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A -- am using (per directions) the distribution version of Bazel:

<tytso@lambda> {/tmp}  
1144% sha1sum bazel-3.3.0-dist.zip
2b78a9bd5572b6a0dedca81e943e9d373f66ce59  bazel-3.3.0-dist.zip
<tytso@lambda> {/tmp}  
1145% gpg bazel-3.3.0-dist.zip.sig
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
gpg: assuming signed data in 'bazel-3.3.0-dist.zip'
gpg: Signature made Wed 17 Jun 2020 09:12:41 AM EDT
gpg:                using RSA key 71A1D0EFCFEB6281FD0437C93D5919B448457EE0
gpg: Good signature from "Bazel Developer (Bazel APT repository key) <bazel-dev@googlegroups.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 71A1 D0EF CFEB 6281 FD04  37C9 3D59 19B4 4845 7EE0

###  Have you found anything relevant by searching the web?

No; I've seen plenty of complaints about Bazel complaining about infinite symlink recursion, but none relating to doing a bootstrap build of Bazel.

### Any other information, logs, or outputs that you want to share?

No.

**Comment by olekw** [comment]
@tytso the Debian Bazel team is in the final stages of getting a Debian native Bazel package into testing (it's already in unstable). When that migrates to testing it will hopefully allow you to build there. If you have issues with that package, feel free to file a [Debian bug](https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=bazel-bootstrap) for it.
