### ISSUE TITLE
TESTBRIDGE_TEST_RUNNER_FAIL_FAST not documented in the test encyclopedia

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#11667]
Since 957554037ced26dc1860b9c23445a8ccc44f697e, one can ask the test runner to exit on first test failure with `--test_runner_fail_fast`. However, the `TESTBRIDGE_TEST_RUNNER_FAIL_FAST` environmental variable is not described in the test encyclopedia.

**Comment by haxorz** [comment]
@ericfelly was the reviewer of the internal commit

[For some reason github doesn't let me assign to him]

**Comment by keertk** [comment]
This problem can now be tracked [here](https://github.com/bazelbuild/bazel/issues/14641). Closing this issue.
