### ISSUE TITLE
Upgrade Jacoco to 0.8.5+ to fix Scala 2.12 lambda code coverage

### ISSUE THREAD

**Issue by gergelyfabian** [bazelbuild/bazel#11674]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

When building Scala 2.12 with https://github.com/bazelbuild/rules_scala coverage has a bug (Scala lambdas are not properly detected). This has been tracked down to a bug in Jacoco 0.8.3 + Scala 2.12 (Jacoco did not properly recognize Scala 2.12 lambdas in 0.8.3).
Jacoco 0.8.5 contains a bugfix for this problem.

To fix this issue Jacoco would need to be upgraded from 0.8.3 to 0.8.5 in Bazel.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Reproduction with Bazel:

1. Check out rules_scala repository on master branch.
2. Generate coverage data:
`bazel coverage  --extra_toolchains="//scala:code_coverage_toolchain" //test/coverage/...`
3. Generated coverage report:
`genhtml -o ${destdir} --ignore-errors source bazel-out/k8-fastbuild/testlogs/test/coverage/test-all/coverage.dat`
4. In coverage/D1.scala.gcov.html only the first line is shown as covered

Outside of Bazel:

Download http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.8.5/jacoco-0.8.5.zip and http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.8.3/jacoco-0.8.3.zip.

Take https://github.com/bazelbuild/rules_scala/blob/master/test/coverage/D1.scala and add a main method to it:

```
  def main(args: Array[String]) {
    D1.veryLongFunctionNameIsHereAaaaaaaaa()
  }
```

Steps:

```
# Install Scala 2.12 into ~/opt/scala-2.12.10
# Unpack jacoco archive (in this case 0.8.5).
unzip ~/Downloads/jacoco-0.8.5.zip
mkdir classes
# Added a main method to test/coverage/D1.scala and moved it to src/ folder.
scalac src/D1.scala -d classes
java -javaagent:lib/jacocoagent.jar -cp ~/opt/scala-2.12.10/lib/scala-library.jar:classes D1
java -jar lib/jacococli.jar report jacoco.exec --classfiles classes --sourcefiles src --html report
# Check the Jacoco report (a bit different graphical interface than for LCOV).
firefox report/index.html
```

1. When using Jacoco 0.8.3:
   a) Missed instructions: 3 of 32
   b) only the first line of veryLongFunctionNameIsHereAaaaaaaaa is covered.
2. When using Jacoco 0.8.5:
    a) Missed instructions: 3 of 295
    b) all lines of veryLongFunctionNameIsHereAaaaaaaaa are covered.

### What operating system are you running Bazel on?

Ubuntu 18.04.

### What's the output of `bazel info release`?

release 3.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/bazelbuild/rules_scala
056d5921d2c595e7ce2d54a627e8bc68ece7e28d
056d5921d2c595e7ce2d54a627e8bc68ece7e28d

###  Have you found anything relevant by searching the web?

Rules scala bug report details:
https://github.com/bazelbuild/rules_scala/issues/1056
https://github.com/bazelbuild/rules_scala/issues/1054

Scala 2.12 changes for lambda bytecode:
https://users.scala-lang.org/t/has-a-loop-recurs-comprehension-been-considered-for-scala/4787/21
https://www.scala-lang.org/news/2.12.0/

Jacoco Java lambda support:
https://stackoverflow.com/questions/45674950/jacoco-need-special-handling-fro-lambdas
https://stackoverflow.com/questions/32284326/code-coverage-for-lambda-function
https://github.com/jacoco/jacoco/pull/232

Jacoco Scala lambda fix:
https://github.com/jacoco/jacoco/pull/912
https://github.com/jacoco/jacoco/pull/922

### Any other information, logs, or outputs that you want to share?

More detailed information may be found at:

https://github.com/bazelbuild/rules_scala/issues/1056
https://github.com/bazelbuild/rules_scala/issues/1054

**Comment by comius** [comment]
JacocoCoverage is attached to java_toolchains. It should be possible to upgrade the version by configuring the toolchain.

**Comment by gergelyfabian** [comment]
I tried to configure the java_toolchain in my project with a custom JacocoCoverage_jarjar_deploy.jar (built from a modified Bazel source, with Jacoco 0.8.6). Unfortunately it seems there is binary incompatibility between 0.8.6 and 0.8.3 (did not try with 0.8.5).

**Comment by gergelyfabian** [comment]
I tried with 0.8.5, generating coverage data works, but I still see the old output (Scala lambdas - the for comprehension lines - are not covered).

Here is the example:

https://github.com/gergelyfabian/bazel-scala-example/tree/jacoco_coverage_fix

>     Manual steps:
>     tools/JacocoCoverage_jarjar_deploy.jar was built in bazel project, overriding
>     the jacoco jars in third_party/java/jacoco with 0.8.5 (small code fix is necessary in
>     src/java_tools/junitrunner/java/com/google/testing/coverage/BranchDetailAnalyzer.java
>     to remove deprectated Override annotation).
>     
>     Then run:
>     bazel build src/java_tools/junitrunner/java/com/google/testing/coverage:JacocoCoverage_jarjar_deploy.jar
>     And copy the file.

**Comment by gergelyfabian** [comment]
Now I know the reason is rules_scala is not using the jacocorunner from the Java toolchain, but it has the path to the runner hardcoded.

**Comment by gergelyfabian** [comment]
Customizable jacocorunner in rules_scala: https://github.com/gergelyfabian/rules_scala/tree/custom_jacocorunner

**Comment by gergelyfabian** [comment]
I managed to make this solution with java_toolchain work.

1. Check out https://github.com/gergelyfabian/jacoco/tree/0.8.3-scala-lambda-fix (has the Scala fixes backported to 0.8.3)
2. Build org.jacoco.core (mvn clean package)
3. **Modify the built jar file to replace org/jacoco/core/jacoco.properties in it with the version from Bazel's third_party/java/jacoco/org.jacoco.agent-0.8.3.jar**. (I guess this step is necessary also if I'd take the official Jacoco jars for e.g. 0.8.5) - I was missing this part so far, `internal_1f1cc91` is coming from here.
4. Copy the customized jar file to third_party/java/jacoco/org.jacoco.agent-0.8.3.jar in Bazel repo.
5. Run in Bazel repo: bazel build src/java_tools/junitrunner/java/com/google/testing/coverage:JacocoCoverage_jarjar_deploy.jar
6. Copy JacocoCoverage_jarjar_deploy.jar to tools/ in this project.
7. Use customized rules_scala from https://github.com/gergelyfabian/rules_scala/tree/custom_jacocorunner as the jacocorunner is hardcoded for the scala_test target (to be able to override that).
8. In bazel-scala-example: `tools/coverage.sh` and open the report with Firefox.

I believe the only missing part is to extend rules_scala to use jacocorunner from the Java toolchain (to avoid using a forked rules_scala version), or at least to enable scala_test users to override jacocorunner.

**Comment by gergelyfabian** [comment]
For the rules_scala fix we'd need to do. Does anyone know how to retrieve `jacocorunner` from `java_toolchain` with `ctx`? We'd like to modify `scala_test` rule, to automatically take the `jacocorunner` that has been defined on the `java_toolchain`.

**Comment by ittaiz** [comment]
@comius do you know that it's possible or you assume it's possible?
Because what I'm seeing I think you might be wrong.
We (at rules_scala) [point](https://github.com/bazelbuild/rules_scala/blob/master/scala/private/rules/scala_test.bzl#L76) to `@bazel_tools//tools/jdk:JacocoCoverage` which AFAIU actually [points](https://github.com/bazelbuild/bazel/blob/ddfc932380c8147c70bb3faf1bc999f0cc3652f2/tools/jdk/BUILD.tools#L282) to `@remote_java_tools//:jacoco_coverage_runner`. 
IIUC this means that if a rules_scala user overrides their `remote_java_tools with a release that has the needed jacoco (0.8.5 or patched 0.8.3) then that should work.
@gergelyfabian have you tried this already? If not can you try it and report back?
The java_tools [readme](https://github.com/bazelbuild/java_tools) has info on how to customize it

**Comment by comius** [comment]
> @comius do you know that it's possible or you assume it's possible?

I'm working on java toolchains. So it's possible to change jacoco_runner on the toolchain, i.e. by defining a custom default_java_toolchain rule and using it.

Problem is that there is currently no Starlark interface so that this setting could be used in Scala directly from the toolchain as it is in Java native rules implementation. 

> Because what I'm seeing I think you might be wrong.
> We (at rules_scala) [point](https://github.com/bazelbuild/rules_scala/blob/master/scala/private/rules/scala_test.bzl#L76) to `@bazel_tools//tools/jdk:JacocoCoverage` which AFAIU actually [points](https://github.com/bazelbuild/bazel/blob/ddfc932380c8147c70bb3faf1bc999f0cc3652f2/tools/jdk/BUILD.tools#L282) to `@remote_java_tools//:jacoco_coverage_runner`.
> IIUC this means that if a rules_scala user overrides their `remote_java_tools with a release that has the needed jacoco (0.8.5 or patched 0.8.3) then that should work.

Having java_tools is an alternative that also works. If somebody prepares it in a bazel branch, I could release it. I'm a bit reluctant to update it on the main branch, because Jacoco 0.8.3 is used internally and changing it is far from trivial. But I'm also reluctant to have an extra branch. But this seems to be the easiest/most usable option at the moment.

> @gergelyfabian have you tried this already and it failed? If not can you try it and report back?
> The java_tools [readme](https://github.com/bazelbuild/java_tools) has info on how to customize it

**Comment by gergelyfabian** [comment]
> If somebody prepares it in a bazel branch, I could release it.

@comius, Do you mean:

> Starlark interface so that this setting could be used in Scala directly from the toolchain

?

**Comment by gergelyfabian** [comment]
> @gergelyfabian have you tried this already and it failed? If not can you try it and report back?
> The java_tools [readme](https://github.com/bazelbuild/java_tools) has info on how to customize it

I'm not totally sure how I could do that if I already use a solution similar to this one: https://github.com/liucijus/bazel-scala211-jdk8

Can I use a custom java_tool (with custom Jacoco runner) if I also need to ensure my Java toolchain is running on JVM 8?

**Comment by ittaiz** [comment]
> Problem is that there is currently no Starlark interface so that this setting could be used in Scala directly from the toolchain as it is in Java native rules implementation.

How big would that a change be? Exposing to starlark that is. Would you be open to it?

**Comment by ittaiz** [comment]
> Can I use a custom java_tool (with custom Jacoco runner) if I also need to ensure my Java toolchain is running on JVM 8?

I think there should be. I haven't dived into the java_tools zip and so I don't know what exactly is java 8 related.
@comius maybe you know?

**Comment by gergelyfabian** [comment]
Latest proposal for rules_scala is to enable providing jacocorunner on `scala_toolchain` (similarly as it can be given for `java_toolchain`). This would be the way to configure jacocorunner until `java_toolchain` receives an API to be able to query it's settings from Starlark.

CC: @ittaiz

**Comment by gergelyfabian** [comment]
Btw. I found out that Jacoco e.g. 0.8.7 seems to be binary incompatible with current Bazel (3.7.1 I checked).
There seems to be a conflict with the asm version used by Jacoco and Bazel. A patched Jacoco 0.8.3 works.

**Comment by ittaiz** [comment]
@gergelyfabian how big is the jacoco jar? Maybe we should commit the patched jar to rules_scala and have that be the default? If it's not too big maybe you should write in one of the relating issues the full repro and Vaidas or me will commit it (given it's binary maybe it's better it will be done by us)

**Comment by gergelyfabian** [comment]
I think this may be a good idea. I have a script that I use to generate the
jacocorunner jar, so you could use that to build it and then upload it to
rules_scala.

FYI: I use the same script to create a different version as I have gone
further and started applying fixes for Scala itself in Jacoco (e.g branch
coverage for case class generated methods and fixes for Jacoco LCOV
Formatter in java_tools to respect Jacoco filtering for branch coverage).

I could contribute the script to rules_scala and you could use it according
to your wishes.

Ittai Zeidman <notifications@github.com> ezt írta (időpont: 2020. dec. 19.,
Szo 6:34):

**Comment by gergelyfabian** [comment]
This script could be also used by anyone to generate their own version of
jacocorunner and use it in their workspace (with any further fixes they
wish).

Fábián Gergely <gergo.fb@gmail.com> ezt írta (időpont: 2020. dec. 19., Szo
8:32):

**Comment by gergelyfabian** [comment]
The script for generating custom jacocorunner is available here: https://github.com/bazelbuild/rules_scala/pull/1173.
The built JacocoCoverage_jarjar_deploy.jar is 8.2MB.

**Comment by comius** [comment]
I don't like to see repositories diverge. We're working to upgrade Jacoco and I will also expose it from JavaToolchain. Sorry for the trouble.

**Comment by ittaiz** [comment]
Amazing. Thanks @comius!
Definitely our preferred solution

**Comment by gergelyfabian** [comment]
> I don't like to see repositories diverge. We're working to upgrade Jacoco and I will also expose it from JavaToolchain. Sorry for the trouble.

That's great news. Once that is available we can remove `jacocorunner` parameter from `scala_toolchain` in rules_scala and use the one from `java_toolchain` (that still will be usable if one wants to use a custom Jacoco version - as I need to at this moment).

**Comment by gergelyfabian** [comment]
Thanks @comius!

@ittaiz, as #12829 is now merged, what is the plan for rules_scala to adjust to that change? Do we need to wait for a new Bazel version?

**Comment by ittaiz** [comment]
Yes we do

**Comment by comius** [comment]
Update: upgrade is in progress, but it will take some time, because we need to resolve some issues first.

**Comment by davido** [comment]
jacoco (min 0.8.6) and asm (min 9.0 beta) update also needed for Java 16 toolchain support.
