### ISSUE TITLE
incompatible_force_strict_header_check_from_starlark: Prevent loose header checking in Starlark rules

### ISSUE THREAD

**Issue by c-mita** [bazelbuild/bazel#11679]
**Flag**: `--incompatible_force_strict_header_check_from_starlark`

Prevents use of the legacy loose header checking mode from Starlark.
See #11677 for details.

#### Migration
This is an incompatible change because it may break rules under obscure circumstances; if this happens then ensure all required headers are explicitly specified to the relevant targets.

This is only observable with the sandbox disabled, so more likely to be seen on Windows.

**Comment by meisterT** [comment]
Is this ready for migration?

**Comment by oquenchil** [comment]
It is.

**Comment by philwo** [comment]
Closing, because this flag has been flipped.
