### ISSUE TITLE
Build With Bazel And OpenSSL

### ISSUE THREAD

**Issue by Fla3inH0tCheet0s** [bazelbuild/bazel#11685]
### Description of the problem / feature request:
I'm trying to build grpc from local source on my repository with the minimal amount of http_archive calls. I had some difficulty because boringssl is linked. Unfortunately, when another target links both grpc and apt's libcurl4-openssl-dev, theres' a segfault on SSL_CTX_new.

I followed [this advice](https://github.com/bazelbuild/bazel/issues/1952#issuecomment-557726794) and got my local version of abseil to be used instead of the remote one. It doesn't seem to work for libssl.

I took a look at the [get_external_deps function](https://github.com/grpc/grpc/blob/master/bazel/grpc_build_system.bzl#L46-L62). I cannot figure out how to replace the `//external:` deps in bazel's `repo_mapping` label. I couldn't find the answer in [the provided doc](https://docs.bazel.build/versions/master/external.html#shadowing-dependencies). Is this why there are hard coded values in that function? If I add
```
elif dep.startswith("libssl"):
    ret += ["@boringssl//:ssl"]
```
to the function, `"@boringssl" : "@openssl",` will work in the `repo_mapping` label. I'm testing the changes with the following command
```
bazel query "deps(@com_github_grpc_grpc//:tsi)" | grep ssl
```

### What operating system are you running Bazel on?

Ubuntu 18.04.3 LTS

### What's the output of `bazel info release`?

release 2.1.1

###  Have you found anything relevant by searching the web?

https://github.com/grpc/grpc/issues/20193
https://github.com/bazelbuild/bazel/issues/1952
https://github.com/bazelbuild/bazel/issues/9120

### Any other information, logs, or outputs that you want to share?

grpc version 1.27.2

**Comment by philwo** [comment]
Sorry, no idea. Can you take this up on the bazel-discuss mailing list?
