### ISSUE TITLE
Handle Content-Encoding gzip in http_archive

### ISSUE THREAD

**Issue by ehrtro** [bazelbuild/bazel#11686]
### Description of the problem / feature request:
**SUMMARY:** The issue is regarding unmatching SHA256 sums, as a result of a downloaded file being unzipped before the comparison of the hash sums is taking place. This issue occurs when Content-Encoding: x-gzip is present in the HTTP header for the downloaded file. More information is to be found below. 

When performing builds where downloads of tar.gz files using http_archive is required, we're encountering issues due to Content-Encoding being present in the HTTP header. 

This is an example of how we are using http_archive. 
```

http_archive(
 name = "<example-file>",
 build_file = "@<PATH>:BUILD.cxa",
 sha256 = "<SHA256 sum for compressed example-file> ",
 type = "tar.gz",
 urls = [ "<example-URL without suffix>" ]
 )

```
... as you can see, the URL don't have any kind of suffix, why we are adding the "type"-field. But when executing the build, we're encountering the following error message:

```

java.io.IOException: Error downloading
[<example-URL without suffix>]
 to 
/<PATH>/<downloading target>.tar.gz
: Checksum was <checksum for uncompressed file> 
but wanted <checksum for compressed file>

```
We have isolated the problem to be related to  Content-Encoding: x-gzip being passed in the HTTP-header causing bazel to unzip the file before the SHA256 sums are compared, which causes the two sums to mismatch. 

```
$ curl -I <URL without suffix> | grep "Content-Encoding: x-gzip"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  136k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Content-Encoding: x-gzip

```
This isn't a problem when downloading files from servers where content-encoding isn't included in the HTTP-header. We can fix this by having the type: tar in http_archive and using the checksum for the unzipped file, but this is not doable in our situation since we don't have easy access to the checksum for the unzipped file.  

 According to the comment on line 82-84 this issue seems to have been brought to the table before: https://github.com/bazelbuild/bazel/blob/bf0b7585ac0e995e0d423774ffcfa41207fd34e2/src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/HttpStream.java#L82-L84 

### Feature requests: what underlying problem are you trying to solve with this feature?
We would like the behavior of unzipping files to be controlled by the type field in http_archive and not necessarily only by content-encoding as implemented for the moment being. 

We believe that extending the following if-statement: https://github.com/bazelbuild/bazel/blob/bf0b7585ac0e995e0d423774ffcfa41207fd34e2/src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/HttpStream.java#L85-L89 ... to include a check of the provided type in http_archive might be a solution of this issue. Do you think it's okay, in the if statement to also check if the type in http_archive is not tgz or tar.gz? When testing with excluding the call to GZIPInputStream, the issue is solved for files with Content-Encoding: x-gzip in the header.  
  
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
As mentioned above, this issue is encountered when trying to download a file using http_archive where the file is compressed when downloaded, and the HTTP-Header includes the Content-Encoding field and the type in http_archive is set to tar.gz.

### What operating system are you running Bazel on?
Red Hat Enterprise 7 (RHEL7)

###  Have you found anything relevant by searching the web?
As mentioned above, this issue seems to have been discussed before, especially in https://github.com/bazelbuild/bazel/issues/2136 

### Any other information, logs, or outputs that you want to share?
No, all the relevant information is stated above

**Comment by ehkloaj** [comment]
In #11738 you'll find our solution.
