### ISSUE TITLE
Release 3.4 - July 2020

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel#11687]
# Status of Bazel 3.4

- Target baseline: 2020-07-02
- Expected release date: 2020-07-13
- [List of release blockers](https://github.com/bazelbuild/bazel/labels/Release%20blocker)

To report a release-blocking bug, please file a bug using the `Release blocker` label, and cc me.

Task list:

- [x] Update GitHub issues for incompatible changes
- [x] Pick release baseline: 7404d17ac76da876ae0b432d1fccf222a9e991fe
- [x] Create release candidate: release-3.4.0rc1
- [x] Check downstream projects:
- [x] [Create draft release announcement](https://docs.google.com/document/d/1wDvulLlj4NAlPZamdlEVFORks3YXJonCjyuQMUQEmB0/edit)
- [x] Send for review the release announcement PR: https://github.com/bazelbuild/bazel-blog/pull/231
- [x] Push the release, notify package maintainers:
- [x] Update the documentation
- [x] Push the blog post
- [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by davido** [comment]
@meisterT Should we mention in the release notes that upcoming Release 3.4 includes new `java_tools` release 9.0 with major Error Prone version upgrade to 2.4.0, with a lot of fixes and out of the box support for Java 14?

And also warn, that some new EP checks were added and spome existing checks were extended so that more diagnostic could be reported for existing EP checks so that Bazel users may experience some issues or even build failures with upcoming Bazel release 3.4?

**Comment by jmillikin-stripe** [comment]
Would it be possible to get https://github.com/bazelbuild/bazel/pull/11659 reviewed and pulled into this release?

**Comment by Yannic** [comment]
Would it be possible to also get #11617 into 3.4?

**Comment by meisterT** [comment]
`release-3.4.0rc1` cut at https://github.com/bazelbuild/bazel/commit/7404d17ac76da876ae0b432d1fccf222a9e991fe

@jmillikin-stripe @Yannic both PRs are merged and included.

**Comment by meisterT** [comment]
WIP release announcement: https://docs.google.com/document/d/1wDvulLlj4NAlPZamdlEVFORks3YXJonCjyuQMUQEmB0/edit#heading=h.8vvjiikmd0sz

@davido please suggest your change there

**Comment by davido** [comment]
> @davido please suggest your change there

Thanks for the pointer. Done.

**Comment by meisterT** [comment]
Already known commit to 🍒 pick: https://github.com/bazelbuild/bazel/commit/f31f2d787116120b2b16e9aa9a64fab171c0d954

**Comment by meisterT** [comment]
just created a new candidate: `scripts/release/release.sh create --force_rc=2 3.4.0 7404d17ac76da876ae0b432d1fccf222a9e991fe f31f2d7`

**Comment by xingxinghuo1000** [comment]
@meisterT  Would you please give a plan to build a pakcage(installer.sh). I want to try a new feature. if it does not work, I'll notify the author ASAP.  Thanks

**Comment by meisterT** [comment]
You can download the most recent release candidate here:
https://releases.bazel.build/3.4.0/rc2/index.html

Another way to test releases is to use Bazelisk (https://github.com/bazelbuild/bazelisk) and set the environment variable `USE_BAZEL_VERSION` to `last_rc` (see more https://github.com/bazelbuild/bazelisk#how-does-bazelisk-know-which-bazel-version-to-run).

**Comment by meisterT** [comment]
I have just released Bazel 3.4.0:
https://github.com/bazelbuild/bazel/releases/tag/3.4.0
https://releases.bazel.build/3.4.0/release/

@vbatts @petemounce @excitoon please update your packages

**Comment by meisterT** [comment]
The release seems to be broken: https://github.com/bazelbuild/bazel/issues/11756

**Comment by meisterT** [comment]
Creating new candidate with `scripts/release/release.sh create 3.4.1 7404d17ac76da876ae0b432d1fccf222a9e991fe f31f2d7 08bf906 0415511`

**Comment by meisterT** [comment]
3.4.1 has been released, blog post https://blog.bazel.build/2020/07/13/bazel-3-4.html

https://github.com/bazelbuild/bazel/releases/tag/3.4.1
https://releases.bazel.build/3.4.1/release/

@vbatts @petemounce @excitoon sorry for the second ping, but this should now be ready to be published

**Comment by vbatts** [comment]
fedora and centos build is kicked off: https://copr.fedorainfracloud.org/coprs/vbatts/bazel/build/1553694/

**Comment by or-shachar** [comment]
@meisterT  - Do you know when is the next release and who's the owner of it?
I want to make sure that https://github.com/bazelbuild/bazel/commit/003f7664c91f4fec81e7607c0b59651915836d3a enters.

Thanks!

**Comment by meisterT** [comment]
I have just created https://github.com/bazelbuild/bazel/issues/11885 for the next release. @aiuto agreed to shepherd it.

**Comment by aiuto** [comment]
I will probably cut the baseline on August 5, so it will be in it.
