### ISSUE TITLE
Building bazel locally fails on Ubuntu on Intel x86_64 platform

### ISSUE THREAD

**Issue by cdavoudian** [bazelbuild/bazel#11697]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Building bazel on Ubuntu x86 platform fails with the following error: 

```sh
ERROR: /root/bazel-master/bazel/src/main/java/com/google/devtools/build/lib/syntax/BUILD:166:1: no such target '@bazel_tools//tools/jdk:jni': target 'jni' not declared in package 'tools/jdk' defined by /root/.cache/bazel/_bazel_root/197b6866cc9a63689172e497f6e75934/external/bazel_tools/tools/jdk/BUILD and referenced by '//src/main/java/com/google/devtools/build/lib/syntax:libcpu_profiler.so
```

### Feature requests: what underlying problem are you trying to solve with this feature?

N/A
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

First, make sure both an older version of bazel and OpenJDK11 is installed on your system

1. Clone the master branch from Github
2. Build Bazel

```sh
bazel build //src:bazel-dev
```

Which results in error

```sh
root@balloon1:~/bazel-master/bazel# bazel build //src:bazel-dev
DEBUG: /root/.cache/bazel/_bazel_root/197b6866cc9a63689172e497f6e75934/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:9: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True 
DEBUG: /root/.cache/bazel/_bazel_root/197b6866cc9a63689172e497f6e75934/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:9: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True 
ERROR: /root/bazel-master/bazel/src/main/java/com/google/devtools/build/lib/syntax/BUILD:166:1: no such target '@bazel_tools//tools/jdk:jni': target 'jni' not declared in package 'tools/jdk' defined by /root/.cache/bazel/_bazel_root/197b6866cc9a63689172e497f6e75934/external/bazel_tools/tools/jdk/BUILD and referenced by '//src/main/java/com/google/devtools/build/lib/syntax:libcpu_profiler.so'
ERROR: Analysis of target '//src:bazel-dev' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.271s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 3 targets configured)
    Fetching @remote_java_tools_linux; fetching
    Fetching @openjdk_linux; fetching
root@balloon1:~/bazel-master/bazel# 
```

### What operating system are you running Bazel on?

Ubuntu 16.04 LTS

### What's the output of `bazel info release`?

```sh
release 2.0.0- (@non-git)
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

1. Download the dist package from Github 
https://github.com/bazelbuild/bazel/releases/download/2.0.0/bazel-2.0.0-dist.zip

2. Unzip it

3. Build via

```sh
env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```sh
root@balloon1:~/bazel-master/bazel# git remote get-url origin
https://github.com/bazelbuild/bazel.git
```

```sh
root@balloon1:~/bazel-master/bazel# git rev-parse master
7404d17ac76da876ae0b432d1fccf222a9e991fe
```

```sh
root@balloon1:~/bazel-master/bazel# git rev-parse HEAD
7404d17ac76da876ae0b432d1fccf222a9e991fe
```

###  Have you found anything relevant by searching the web?

Yes, historical issues and issues affecting other platforms. Nothing for master.

### Any other information, logs, or outputs that you want to share?

N/A

**Comment by AustinSchuh** [comment]
You are trying to build bazel (master) which is 3.3 or so, with bazel 2.0.  That's a major release away from master.  Try building it with 3.3.1.
