### ISSUE TITLE
Bazel crashes when http_archive downloads an archive which contains an archive of the same name

### ISSUE THREAD

**Issue by carpenterjc** [bazelbuild/bazel#11699]
# Description of the problem / feature request:

http_archive downloads then expands the http_archive in place. This at best means the archive extraction is corrupted. 
I have seen a few different errors: `Unexpected end of ZLIB input stream` and/or ERROR: An error occurred during the fetch of repository 'archive_in_archive':
   java.io.IOException: Error extracting C:/dev/_bazel/3laerure/external/archive_in_archive/archive_in_archive.zip to C:/dev/_bazel/3laerure/external/archive_in_archive: The file 'archive_in_archive.zip' is nis not a correctly formatted zip file: Expected a Fileot a correctly formatted zip file: Expected a File Header at file offset 239, but was not present.
ERROR: java.io.IOException: Error extracting C:/dev/_bazel/3laerure/external/archive_in_archive/archive_in_archive.zip to C:/dev/_bazel/3laerure/external/archive_in_archive: The file 'archive_in_archive.zip' 
is not a correctly formatted zip file: Expected a File Header at file offset 239, but was not present.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> git clone https://github.com/carpenterjc/bazel_experiments.git
> cd bazel_experiments
Works:
> bazel fetch @archive_in_archive_new_name//...
Fails:
> bazel fetch @archive_in_archive//...

### What operating system are you running Bazel on?

Windows
### What's the output of `bazel info release`?

> INFO: Invocation ID: 14b242a8-8ca7-4d28-aa71-a559ed10bfec
> release 2.2.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> https://github.com/carpenterjc/bazel_experiments.git
108b8703d0fa3403de852deaa27bca8447895c2a
108b8703d0fa3403de852deaa27bca8447895c2a

###  Have you found anything relevant by searching the web?

Not with the same underlying cause. 

### Any other information, logs, or outputs that you want to share?

> Having looked into this the archive is extracted into the relevant external directory, it then starts expanding the archive directly into that archive. Which will trample over the archive being read. 

Suggest the archive is dowloaded to a different directory then expanded to the external directory.

**Comment by meisterT** [comment]
Note that this also fails on Linux with the same error message.

It comes from https://cs.opensource.google/bazel/bazel/+/master:src/java_tools/singlejar/java/com/google/devtools/build/zip/ZipEntryInputStream.java;l=48;drc=33b2f120914f7b8fcff80c07155c45024d3e30df

cc @cushon

**Comment by carpenterjc** [comment]
I cloned and patched `_http_archive_impl` from `@bazel_tools//tools/build_defs/repo:http.bzl` with the following (crude) workaround. 

```  
    
    # download_info = ctx.download_and_extract(
    #     all_urls,
    #     "test",
    #     ctx.attr.sha256,
    #     ctx.attr.type,
    #     ctx.attr.strip_prefix,
    #     canonical_id = ctx.attr.canonical_id,
    #     auth = auth,
    # )

    download_info = ctx.download(
        url = all_urls,
        output="___scatch___.zip",
        sha256 = ctx.attr.sha256,
        canonical_id = ctx.attr.canonical_id,
        auth = auth
    )
    ctx.extract(archive="___scatch___.zip", 
    output="", 
    stripPrefix = ctx.attr.strip_prefix
)```
