### ISSUE TITLE
cc_common.link has default stamp=0

### ISSUE THREAD

**Issue by ozio85** [bazelbuild/bazel#11693]
The default in cc_common.link is 0, and everywhere else it is -1, this caused some confusion when stamping is not propagated correctly.

Since 0 means "Do not perform any linkstamping at all" and -1 is "let the user decide", i think the default should be -1.

### Description of the problem / feature request:

Change default in cc_common.link from 0 to -1

### Feature requests: what underlying problem are you trying to solve with this feature?

Harmonize the default behavior, (and to enable --stamp on command line by default).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Check the default value of cc_common.link

### What operating system are you running Bazel on?

Linux and Windows

### What's the output of `bazel info release`?

3.3.0

###  Have you found anything relevant by searching the web?

No

**Comment by oquenchil** [comment]
We are not planning to change the default at this time since it would be an incompatible change and it would just need documentation.
