### ISSUE TITLE
warning about workspace name after upgrading

### ISSUE THREAD

**Issue by cnsgsz** [bazelbuild/bazel#1169]
any pointers? thanks!

> WARNING: /home/swang/.cache/bazel/_bazel_swang/0c7c3636aa25cf7b9c5a714c448ab26b/external/local_config_cc/WORKSPACE:1: Workspace name in /home/swang/.cache/bazel/_bazel_swang/0c7c3636aa25cf7b9c5a714c448ab26b/external/local_config_cc/WORKSPACE (@__main__) does not match the name given in the repository's definition (@local_config_cc); this will cause a build error in future versions.

**Comment by damienmg** [comment]
bazel version?

**Comment by cnsgsz** [comment]
I pulled from master yesterday and built myself with compile.sh. The git hash is d225acc.

**Comment by kchodorow** [comment]
I don't actually see d225acc in our commit log.  This should be fixed by 382b5881fc0f3e0ec162e78fb31569e8d36c2a8d.

**Comment by cnsgsz** [comment]
sorry, pulled the wrong commit hash. will try with the fix tonight.

**Comment by shahms** [comment]
see #1166; that commit only mostly fixed the issue, but doesn't appear to have done so in all cases.

**Comment by cnsgsz** [comment]
my original issue seems fixed already.

**Comment by damienmg** [comment]
Ok since this specific issue is fixed, #1166 will track the remaining ones. Closing this bug
