### ISSUE TITLE
incompatible_blacklisted_protos_requires_proto_info: Require ProtoInfo provider for proto_lang_toolchain.blacklisted_protos

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/bazel#11694]
**Flag**: `--incompatible_blacklisted_protos_requires_proto_info`

Prevents users from passing `.proto` files / `filegroups` to [proto_lang_toolchain.blacklisted_protos](https://docs.bazel.build/versions/master/be/protocol-buffer.html#proto_lang_toolchain.blacklisted_protos).

# Migration

For most users, migration is straight forward. All that is required is upgrading Protobuf to v3.13.0 (or later).

### When using `proto_lang_toolchain` directly

If you're using `proto_lang_toolchain` directly, you need to replace the files in
`proto_lang_toolchain.blacklisted_protos` with the `proto_library` targets containing these files.

For WKPs, this would mean replacing
```starlark
proto_lang_toolchain(
    name = "my_proto_toolchain",
    blacklisted_protos = [
        "@com_google_protobuf//:src/google/protobuf/any.proto",
        "@com_google_protobuf//:src/google/protobuf/descriptor.proto",
        # ...
    ],
    # ...
)
```
with
```starlark
proto_lang_toolchain(
    name = "my_proto_toolchain",
    blacklisted_protos = [
        "@com_google_protobuf//:any_proto",
        "@com_google_protobuf//:descriptor_proto",
        # ...
    ],
    # ...
)
```

**Comment by Yannic** [comment]
@meisterT FYI so it gets all the required labels for migration (expecting to flip in 4.0).

**Comment by meisterT** [comment]
cc @comius

**Comment by Yannic** [comment]
This is ready for flipping once https://github.com/googlecloudrobotics/core/pull/54 lands 🎉.
