### ISSUE TITLE
`JavaInfo` from a `java_test` lacks any `runtime_output_jars`

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#11705]
### Description of the problem:

When an aspect or rule obtains the `JavaInfo` of a `java_test`, it lacks any `runtime_output_jars`, even if the target has sources, and so _does_ produce an output jar.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Attached is a small reproduction of the probelm. Unpack, `cd` into the directory and run `bazel build --nobuild //... --aspects=//:output-info.bzl%list_outputs_aspect`

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

The example uses 3.1.0, but the problem still exists with 3.3.1

### Any other information, logs, or outputs that you want to share?

An example repo which demonstrates the problem [sample.zip](https://github.com/bazelbuild/bazel/files/4870162/sample.zip) The expected output is that `JavaInfo.runtime_output_jars` and `JavaInfo.outputs.jars[0].class_jar` should contain the same file.

**Comment by shs96c** [comment]
Sample output from my machine:

```
shs@machine ~/s/no-java-output> bazel build --nobuild //... --aspects=//:output-info.bzl%list_outputs_aspect
INFO: Invocation ID: 4c7b1ec9-2ba0-4963-b52d-033ca31b98b7
DEBUG: /Users/shs/src/no-java-output/output-info.bzl:5:3: Runtime output jars for <target //:lib>: [<generated file liblib.jar>]
DEBUG: /Users/shs/src/no-java-output/output-info.bzl:6:3: Jars in output for <target //:lib>: [<generated file liblib.jar>]
DEBUG: /Users/shs/src/no-java-output/output-info.bzl:5:3: Runtime output jars for <target //:test>: []
DEBUG: /Users/shs/src/no-java-output/output-info.bzl:6:3: Jars in output for <target //:test>: [<generated file test.jar>]
INFO: Analyzed 2 targets (0 packages loaded, 0 targets configured).
INFO: Found 2 targets...
INFO: Elapsed time: 0.101s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
```

The underlying aspect looks like:

```py
def _list_outputs_impl(target, ctx):
  if not JavaInfo in target:
    return

  print("Runtime output jars for %s: %s" % (target, target[JavaInfo].runtime_output_jars))
  print("Jars in output for %s: %s" % (target, [jar.class_jar for jar in target[JavaInfo].outputs.jars]))
  return []

list_outputs_aspect = aspect(
  _list_outputs_impl,
)
```

**Comment by lberki** [comment]
This is working as intended; `java_binary` and `java_test` don't produce a `JavaInfo` because that would make it possible for them to be in the `deps` of other Java rules, which would result in confusion between e.g. `java_binary` and `java_library`.
