### ISSUE TITLE
protobuf tests are broken at HEAD on darwin

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1170]
http://ci.bazel.io/job/protobuf/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/146/console

Seems to be related to the runfiles tree & test-setup.sh. That is weird.

/cc @kchodorow

**Comment by kchodorow** [comment]
It looks like this is at 951cea2a335878ceba83c6c188a59c19a0228d78, at the latest (790d2f6, http://ci.bazel.io/job/protobuf/149/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/console) it seems to pass.
