### ISSUE TITLE
--incompatible_load_cc_rules_from_bzl breaks cpp runfiles library

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/bazel#11704]
### Description of the problem:

Depending on `@bazel_tools//tools/cpp/runfiles` while enabling `--incompatible_load_cc_rules_from_bzl` will fail.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

* Define a cc target that depends on `@bazel_tools//tools/cpp/runfiles`.
* Try to build it with `--incompatible_load_cc_rules_from_bzl` enabled
* Observe the following error
  ```
  ERROR: .../external/bazel_tools/tools/cpp/runfiles/BUILD:3:1: in cc_library rule @bazel_tools//tools/cpp/runfiles:runfiles: The native C++/Objc rules are deprecated. Please load cc_library from the rules_cc repository. See http://github.com/bazelbuild/rules_cc and https://github.com/bazelbuild/bazel/issues/7643. You can temporarily bypass this error by setting --incompatible_load_cc_rules_from_bzl=false.
  ```

### What operating system are you running Bazel on?

Ubuntu 19.10

### What's the output of `bazel info release`?

```
release 2.1.0- (@non-git)
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Using nixpkgs, defined [here](https://github.com/tweag/rules_haskell/blob/8cfef32ee9b14fc404a3bc4302955d17c2f88ce7/shell.nix).

###  Have you found anything relevant by searching the web?

`@bazel_tools//tools/cpp/runfiles` is [defined within the Bazel repository](https://github.com/bazelbuild/bazel/blob/f31f2d787116120b2b16e9aa9a64fab171c0d954/tools/cpp/runfiles/BUILD.tools) using the builtin `cc_library` rule rather than `rules_cc`. This still seems to be the case at latest `master`.

### Any other information, logs, or outputs that you want to share?

The `rules_cc` repository [defines it's own runfiles library](https://github.com/bazelbuild/rules_cc/blob/5cbd3dfbd1613f71ef29bbb7b10310b81e272975/tools/runfiles/BUILD#L6). However, that one is marked as `testonly = 1`, making it not generally applicable. Even when working around that, the required header include `#include "tools/cpp/runfiles/runfiles.h"` will fail.

**Comment by oquenchil** [comment]
All of this has changed, we aren't going to flip that flag. More details on how all of it will play out will come in the future but I can close this issue now.
