### ISSUE TITLE
wrapper_clang should be compiled with DEVELOPER_DIR in the environment

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/bazel#11716]
### Description of the problem / feature request:

`wrapper_clang` should pass `DEVELOPER_DIR` to `xcrun` invocation. Without this, `xcode-select` needs to be set globally, which impacts multiple workspaces.

https://github.com/bazelbuild/bazel/blob/82e6b6a3b9589b93f4abcf3eb0f14cd1d50008ff/tools/cpp/osx_cc_configure.bzl#L114-L127

When using `DEVELOPER_DIR` as an `--action_env` to set the Xcode version to compile with, the current behavior results in cache misses that involve `wrapper_clang`, since different versions of Xcode could have been used to compile it.
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`wrapper_clang` being compiled with the correct version of Xcode, based on --action_env=DEVELOPER_DIR`.

### What operating system are you running Bazel on?

macOS 10.15.5

### What's the output of `bazel info release`?

release 3.3.0
###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/11635
https://github.com/bazelbuild/bazel/issues/8902

**Comment by keith** [comment]
Dup of https://github.com/bazelbuild/bazel/issues/8902

**Comment by brentleyjones** [comment]
Thanks! Closing.

**Comment by brentleyjones** [comment]
@keith This isn't a 100% dup of #8902, so I'm reopening it, and addressing it with #11719.
