### ISSUE TITLE
Build and test everything in one command (for CI)

### ISSUE THREAD

**Issue by gibfahn** [bazelbuild/bazel#11715]
### Description of the problem / feature request:

Want to be able to run the equivalent of `bazel test //... && bazel build //...` in a single command.

### Feature requests: what underlying problem are you trying to solve with this feature?

In CI it's common to want to build and test everything. In other build systems you would run `cargo build && cargo test`, or `go build && go test ...`. Often running the test command will itself run the build if that hasn't already happened.

However in Bazel this is slow, because you can't take advantage of the fact that Bazel will start running tests as soon as their targets are built.

So I believe the fastest way to do things today is `bazel test //... && bazel build //...`. But this is still slow as you have to wait for the last test to finish before finishing the build targets.

My understanding is that `bazel test //...` will build all `binary` and `test` targets, but not `library` targets.

I believe the options for implementation would be:
1. A new top-level command like `bazel ci //...`
2. A flag to pass to the `test` command: `bazel test --also_build_libs //...`

I assume the latter is more feasible.

I believe that would do the same as `bazel test //... && bazel build //...` does today.

###  Have you found anything relevant by searching the web?

Haven't found anything.

**Comment by jin** [comment]
`bazel test //...` builds and tests all targets. `bazel build //...` builds all targets. `bazel test //... --build_tests_only` builds only the transitive closure of test targets, and tests them.

The `//...` target pattern does not differentiate between binary (assuming `executable = True`) and library targets. Do you have a repro that shows otherwise?

**Comment by gibfahn** [comment]
Hmm, I don't have a good example to hand. I'll close this till I do.

I was _sure_ there was a difference, and had asked a couple of knowledgeable folks, but maybe things have changed or I'm just misremembering.
