### ISSUE TITLE
WARNING: Download from https://mirror.bazel.com/openjdk/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.7%2B10/OpenJDK11U-jdk_ppc64le_linux_hotspot_11.0.7_10.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: mirror.bazel.com

### ISSUE THREAD

**Issue by yesudeep** [bazelbuild/bazel#11714]
### Description of the problem / feature request:

The following warning is displayed when building with Bazel.

WARNING: Download from https://mirror.bazel.com/openjdk/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.7%2B10/OpenJDK11U-jdk_ppc64le_linux_hotspot_11.0.7_10.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: mirror.bazel.com

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Just try to build something with Bazel.

### What operating system are you running Bazel on?

Max OS 10.15.5
Clear Linux kernel 5.7.7-967 x86_64 

### What's the output of `bazel info release`?

release 3.3.1

###  Have you found anything relevant by searching the web?

I searched the repository and found [only one occurrence of `mirror.bazel.com`](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/java/jdk.WORKSPACE#L128). Also checked whether the URL actually worked—it didn't.

The URL should be: https://mirror.bazel.build/openjdk/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.7%2B10/OpenJDK11U-jdk_ppc64le_linux_hotspot_11.0.7_10.tar.gz

The typo was introduced by [this commit](https://github.com/bazelbuild/bazel/commit/66d84ef9864f89a879b0c5ccc56cb5dbaedcc36a).

### Any other information, logs, or outputs that you want to share?

I've sent a [pull request (11708)](https://github.com/bazelbuild/bazel/pull/11708) to fix this.

**Comment by meisterT** [comment]
PR merged, so closing
