### ISSUE TITLE
exec_compatible_with sets _where_ action will run, but doesn't transition cpp toolchain

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/bazel#11717]
Assuming you have:
* A `--crosstool_top` set pointing to a `cc_toolchain_suite` which has a `cc_toolchain` set up for `cpu=k8` and an `apple_cc_toolchain` set up for `cpu=darwin_x86_64`.
* Those toolchains added via `--extra_toolchains`.
* A remote execution cluster which supports both of those cpus.
* `--extra_execution_platforms` added where each of those toolchains can run.

If you make a `genrule` or `sh_test` which depends on a `cc_binary`, the `cc_binary` appears to be built on the correct machine, but is always built with the toolchain for whatever the `--cpu` flag of the entire bazel invocation is.

How can we make sure that the cc toolchain transitions along with the execution platform?

**Example repro cases:**

All of these targets work fine if you build them in isolation, with `--cpu=` set for whichever target you're building. I can't work out how to get these targets building in the same invocation.

Ideally this would work, where the `cc_binary`'s BUILD file doesn't know about its toolchain, but it is configured based on the `exec_tools` attribute of its dependeee:

`BUILD`:
```python
genrule(
    name = "generate_uname_c_linux",
    exec_compatible_with = ["@platforms//os:linux"],
    outs = ["uname_c_linux"],
    cmd = "$(location :uname) > $@",
    exec_tools = [":uname"],
)

genrule(
    name = "generate_uname_c_macos",
    exec_compatible_with = ["@platforms//os:macos"],
    outs = ["uname_c_macos"],
    cmd = "$(location :uname) > $@",
    exec_tools = [":uname"],
)

cc_binary(
    name = "uname",
    srcs = ["uname.c"],
)
```

`uname.c`:
```c
#include <stdio.h>
#include <sys/utsname.h>

int main(void) {
  struct utsname buf;

  if (uname(&buf) != 0) {
    return 1;
  }

  printf("%s\n", buf.sysname);

  return 0;
}
```

If this is slightly too magic, alternatively the `BUILD` file could look like this, where we manually expand out the transitions, but this also doesn't seem to work:
```python
genrule(
    name = "generate_uname_c_linux",
    exec_compatible_with = ["@platforms//os:linux"],
    outs = ["uname_c_linux"],
    cmd = "$(location :uname-linux) > $@",
    exec_tools = [":uname-linux"],
)

genrule(
    name = "generate_uname_c_macos",
    exec_compatible_with = ["@platforms//os:macos"],
    outs = ["uname_c_macos"],
    cmd = "$(location :uname-macos) > $@",
    exec_tools = [":uname-macos"],
)

cc_binary(
    name = "uname-linux",
    srcs = ["uname.c"],
    exec_compatible_with = ["@platforms//os:linux"],
)

cc_binary(
    name = "uname-macos",
    srcs = ["uname.c"],
    exec_compatible_with = ["@platforms//os:macos"],
)
```

**Comment by katre** [comment]
Until #7260 is fixed, by default C++ toolchains use the legacy system, which is not using toolchain resolution.

You can try setting the `--incompatible_enable_cc_toolchain_resolution` flag (and writing `toolchain` targets for any custom `cc_toolchain` targets you have). This should work as long as you are not also trying to build Android or Apple apps using native code.

**Comment by illicitonion** [comment]
Perfect - that indeed solves my problem - thanks for the quick help!
