### ISSUE TITLE
download_and_extract() doesn't create subdirectories specified in "output" argument

### ISSUE THREAD

**Issue by steven-johnson** [bazelbuild/bazel#1172]
given

    output = "my_subdir"
    repository_ctx.download_and_extract(url, output, sha256, type, strip_prefix)

this will generally fail (on Bazel OSX 0.22) because "my_subdir" doesn't exist in the newly-created cached dir, and download_and_extract isn't creating it.

Note that you can work around this by using 

    repository_ctx.file("my_subdir/empty_file", "") 

beforehand.

**Comment by damienmg** [comment]
Oh I though I filed a bug about that. Yes download and download and extract should create the necessary folder.
