### ISSUE TITLE
Regression in 3.4.0 release candidate: no such package '@bazel_tools//third_party/py/gflags'

### ISSUE THREAD

**Issue by mmorearty** [bazelbuild/bazel#11731]
### Description of the problem / feature request:

I'm trying out 3.4.0rc2 in our very large repro. I got the following error:

```
ERROR: /home/vagrant/.cache/bazel/_bazel_vagrant/a1dee352bc213c3de72700c6468c2f6f/external/io_bazel_rules_docker/container/BUILD:40:11: no such package '@bazel_tools//third_party/py/gflags': BUILD file not found in directory 'third_party/py/gflags' of external repository @bazel_tools. Add a BUILD file to a directory to mark it as a package. and referenced by '@io_bazel_rules_docker//container:build_tar_lib'
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Unfortunately my repro is very large, and I spent about an hour trying to make a small repro case, with no success. (This is in an area of our codebase that I am not at all familiar with, including the Bazel rules it uses). I'm hoping the error message, plus the fact that it's from io_bazel_rules_docker, helps you narrow this down.

I can give you partial information:

* The version of rules_docker that our codebase uses is https://github.com/bazelbuild/rules_docker/archive/174d7c2f5159c9144e999935e729c2faffc42495.zip

* I tried upgrading our rules_docker to https://github.com/bazelbuild/rules_docker/releases/download/v0.14.3/rules_docker-v0.14.3.tar.gz; that did not help.

### What operating system are you running Bazel on?

Ubuntu. Specifically:

```
$ uname -a
Linux ip-172-31-52-184 4.4.0-1106-aws #117-Ubuntu SMP Wed Apr 8 09:52:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### What's the output of `bazel info release`?

```
release 3.4.0rc2
```

###  Have you found anything relevant by searching the web?

No.

**Comment by Yannic** [comment]
gflags has been deleted from Bazel (and `@bazel_tools`) in https://github.com/bazelbuild/bazel/pull/11564. I believe this should be fixed in `rules_docker@HEAD`.

**Comment by mmorearty** [comment]
Confirmed, thanks. I did then get a different error, but it's an issue in rules_docker, not bazel. (If you're curious, my comment is [here](https://github.com/bazelbuild/rules_docker/pull/1535#issuecomment-655686705))

**Comment by aiuto** [comment]
It's fixed in rules_docker at head. Someone needs to nudge the to tag a new
release.

**Comment by philwo** [comment]
Looks like they did a release just a few hours ago that should fix it: https://github.com/bazelbuild/rules_docker/releases/tag/v0.14.4
