### ISSUE TITLE
Errors in external packages/rules are not descriptive

### ISSUE THREAD

**Issue by trainman419** [bazelbuild/bazel#1173]
When I put the following snippet in my WORKSPACE file:

```
new_local_repository(
    name = "foo-bar",
    path = "/usr",
    build_file = "build/BUILD.foo-bar",
)
```

(There is no `build/BUILD.foo-bar` file)

I get this error message:

```
ERROR: no such package '@foo-bar//': error loading package 'external': Could not load //external package.
```

I'm not entirely sure what this error message means. It may mean that the build file I specified is missing, or it may mean that the name I specified is incorrect.

Instead, I would like to have an error message telling me:

- Which file has an error
- The line number that has the error (or something close)
- A description of the error

Maybe: ERROR: WORKSPACE:5 in new_local_repository, build_file = BUILD.foo-bar does not exist

**Comment by damienmg** [comment]
There should be another error printed out that is more descriptive. As for getting the line number, unfortunately that is a bit tricky.

**Comment by trainman419** [comment]
I debugged this by changing each aspect in turn, and eventually found that it was due to a bad name in new_local_repository. Apparently `-` characters are not allowed in that context.

**Comment by kchodorow** [comment]
I think this is now more understandable, it prints:

```
ERROR: /usr/local/google/home/kchodorow/test/a/WORKSPACE:17:1: new_local_repository rule //external:foo-bar's name field must be a legal workspace name.
```
