### ISSUE TITLE
Support required_aspect_providers from the command-line

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/bazel#11736]
### Description of the feature request:

Aspects can access providers returned by other aspects through the `required_aspect_providers` attribute. However, currently this only works for aspects that are called from rules, e.g. via `attr.label(aspects = [...])`. The requested feature is to allow such aspect on aspect dependencies for aspects that are invoked from the command-line via the `--aspects` flag as well.

### Feature requests: what underlying problem are you trying to solve with this feature?

The motivating use-case is an [aspect that extracts compiler flags](https://github.com/tweag/rules_haskell/blob/5073048c9e307295ea1102459e214750d6a118ad/haskell/repl.bzl#L500) needed to load a transitive closure of Haskell targets into a REPL. The REPL aspect in turn depends on an aspect that applies additional transformations on C libraries. Currently, this aspect only works when it is called through a dedicated rule that sets up the correct aspect dependencies. It would be good to be able to call the aspect on any target on-the-fly from the command-line instead of having to define a dedicated target in a `BUILD.bazel` file.

To illustrate I've created the following minimal reproduction of the issue:

`repro.bzl`:
```
AspectAProvider = provider(fields = ["value"])
AspectBProvider = provider(fields = ["value"])

def _aspect_a_impl(target, ctx):
    print("aspect a", target, "has A", AspectAProvider in target, "has B", AspectBProvider in target)
    return [AspectAProvider(value = 1)]

def _aspect_b_impl(target, ctx):
    print("aspect b", target, "has A", AspectAProvider in target, "has B", AspectBProvider in target)
    return [AspectBProvider(value = target[AspectAProvider].value)]

aspect_a = aspect(
    _aspect_a_impl,
    attr_aspects = ["deps"],
    provides = [AspectAProvider],
)

aspect_b = aspect(
    _aspect_b_impl,
    attr_aspects = ["deps"],
    required_aspect_providers = [AspectAProvider],
)

def _my_rule_impl(ctx):
    return [DefaultInfo()]

my_rule = rule(
    _my_rule_impl,
    attrs = {
        "deps": attr.label_list(),  # Fails in aspect_b on //:a
        #"deps": attr.label_list(aspects = [aspect_a]),  # Fails in aspect_b on //:b
        #"deps": attr.label_list(aspects = [aspect_a, aspect_b]),  # Fails in aspect_b on //:b
    },
)

def _my_aspect_rule_impl(ctx):
    return [DefaultInfo()]

my_aspect_rule = rule(
    _my_aspect_rule_impl,
    attrs = {
        "deps": attr.label_list(aspects = [aspect_a, aspect_b]),
    },
)
```

`BUILD.bazel`:
```
load("//:repro.bzl", "my_rule", "my_aspect_rule")

my_rule(name = "a")
my_rule(name = "b", deps = [":a"])

my_aspect_rule(name = "aspect", deps = [":b"])
```

Trying to invoke the aspects `aspect_a` and `aspect_b` from the command-line fails:
```
$ bazel build //:b --aspects //:repro.bzl%aspect_a,//:repro.bzl%aspect_b
DEBUG: /home/aj/tweag.io/da/bazel-projects/repro/aspect_on_aspect/repro.bzl:5:10: aspect a <target //:a, keys:[OutputGroupInfo]> has A False has B False
DEBUG: /home/aj/tweag.io/da/bazel-projects/repro/aspect_on_aspect/repro.bzl:5:10: aspect a <target //:b, keys:[OutputGroupInfo]> has A False has B False
DEBUG: /home/aj/tweag.io/da/bazel-projects/repro/aspect_on_aspect/repro.bzl:9:10: aspect b <target //:a, keys:[OutputGroupInfo]> has A False has B False
ERROR: /home/aj/tweag.io/da/bazel-projects/repro/aspect_on_aspect/BUILD.bazel:3:8: in //:repro.bzl%aspect_b aspect on my_rule rule //:a:
Traceback (most recent call last):
        File "/home/aj/tweag.io/da/bazel-projects/repro/aspect_on_aspect/BUILD.bazel", line 3
                //:repro.bzl%aspect_b(...)
        File "/home/aj/tweag.io/da/bazel-projects/repro/aspect_on_aspect/repro.bzl", line 10, in _aspect_b_impl
                target[AspectAProvider]
<target //:a> (rule 'my_rule') doesn't contain declared provider 'AspectAProvider'
ERROR: Analysis of aspect '//:repro.bzl%aspect_b of //:b' failed; build aborted: Analysis of target '//:a' failed
```

However, invoking the aspects from a rule succeeds:
```
$ bazel build //:aspect
DEBUG: /home/aj/tweag.io/da/bazel-projects/repro/aspect_on_aspect/repro.bzl:5:10: aspect a <target //:a, keys:[OutputGroupInfo]> has A False has B False
DEBUG: /home/aj/tweag.io/da/bazel-projects/repro/aspect_on_aspect/repro.bzl:5:10: aspect a <target //:b, keys:[OutputGroupInfo]> has A False has B False
DEBUG: /home/aj/tweag.io/da/bazel-projects/repro/aspect_on_aspect/repro.bzl:9:10: aspect b <merged target //:a> has A True has B False
DEBUG: /home/aj/tweag.io/da/bazel-projects/repro/aspect_on_aspect/repro.bzl:9:10: aspect b <merged target //:b> has A True has B False
```

We can make some progress by defining `"deps": attr.label_list(aspects = [aspect_a])`. However, the same failure still occurrs on the target that the aspect is invoked on on the command-line, in this case `//:b`.

### What operating system are you running Bazel on?

Ubuntu 19.10

### What's the output of `bazel info release`?

release 3.3.1

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/5995 talks about the ordering of aspects and seems somewhat related.

**Comment by lberki** [comment]
In order to be able to evaluate aspected configured targets in every way Bazel can do for dependency edges, we'll actually need something else (required aspect providers only come into play when evaluating dependencies between different combinations of aspects attached to the same configured target).

The ideal data structure would be something like the input of `AspectCollection.create()`, that is, a list of aspects and their aspect parameters, and of course, a list of those so that we can have both independent aspects and ones depending on each other. Unfortunately, that's way too complicated for a command line argument...

**Comment by aherrmann** [comment]
@lberki Thank you for replying to this issue.

> This, in itself, is kinda-works-as-intended: the spec of `--aspects` says that the aspects are independently attached to the configured targets.

I see. However, I think this makes aspects less composable than they could be. It's also a bit of a stumbling block. The example described above does work so long as the aspect is only requested from the context of a rule implementation. So, an aspect author may not notice that their aspect does not work on the command line until much later. Having an aspect that works in a rule fail when invoked from the command line is quite surprising. Hence this feature request.

I guess your work on *aspects propagating aspects* may help with this.

> The ideal data structure would be something like the input of `AspectCollection.create()`, that is, a list of aspects and their aspect parameters, and of course, a list of those so that we can have both independent aspects and ones depending on each other. Unfortunately, that's way too complicated for a command line argument...

I'm not sure why such a data-structure would need to be provided in a command line argument. Reading my issue a second time I realize that the phrasing may be ambiguous, sorry about that. Let me try to clarify:

The dependencies between aspects A and B are fully defined in the `.bzl` files. `aspect_b` declares `required_aspect_providers = [AspectAProvider]` and `aspect_a` declares `provides = [AspectAProvider]`. Ideally, that should be enough information to Bazel to have the following command succeed.
```
$ bazel build //:b --aspects //:repro.bzl%aspect_b
```
I.e. Bazel should realize that evaluating `aspect_b` requires first evaluating `aspect_a`. That may not be possible in general as multiple aspects could declare `provides = [AspectAProvider]` and Bazel would have to choose or just error on ambiguity. However, with a command like
```
$ bazel build //:b --aspects //:repro.bzl%aspect_a,//:repro.bzl%aspect_b
```
Bazel could order aspect evaluation on each target by the `provides` and `required_aspect_providers` attributes so that all aspect dependencies are fulfilled. This should not require additional information to be passed on the command line, as all the aspect dependencies are already defined in the `.bzl` files.

**Comment by lberki** [comment]
`required_aspect_providers` is not enough information for Bazel to figure out that is `aspect_b` is attached, `aspect_a` must also be: neither `aspect_b` nor `AspectAProvider` contains a link back to `aspect_a` and as you say, it's also possible that another aspect also provides it. For all Bazel knows, `AspectAProvider` is just a provider. So it's not possible to implement what you are saying even in a simple case.

The semantics of `build //:x --aspects A,B` is currently "build `x+A` and `x+B`" separately. This request is perfectly reasonable, and is different from "build `x+A+B`. Ideally, the command line would be able to express both.

**Comment by aherrmann** [comment]
> The semantics of `build //:x --aspects A,B` is currently "build `//:x + A` and `//:x + B` separately". This request is perfectly reasonable, and is different from "build `//:x + A + B`". Ideally, the command line would be able to express both.

Expressing it on the command-line would be one option. Another approach would be to consider B's dependency on A an implementation detail that the user shouldn't need to know about. So, calling `build //:x --aspects B` should automatically evaluate aspect A as well and make it accessible to B. To that end B would explicitly declare it's dependency on aspect A. I think that would at least fit better with the motivating use-case from rules_haskell. In that case the user is really only interested in `haskell_repl_aspect`. That this aspect in turn depends on `haskell_cc_libraries_aspect` is an implementation detail and not something the user should have to worry about. It's also more explicit to define the dependency at `haskell_repl_aspect` rather than assuming that it will be available implicitly.

**Comment by lberki** [comment]
How would Bazel know that in order to evaluate aspect B, it also need to evaluate aspect A?

Aspect B has `required_aspect_providers`, but there is no way to get from the list of providers to the aspects that provide them.

**Comment by lberki** [comment]
This sounds similar to the half-baked "Aspects propagating other aspects" idea:

https://docs.google.com/document/d/1fVNyskIgMoiNeOOGt57LdDmEkAShkYUKYQTkf5yD1fA/edit

except that this would apply to the same target instead of only the dependencies.

**Comment by aherrmann** [comment]
> This sounds similar to the half-baked "Aspects propagating other aspects" idea:
> 
> https://docs.google.com/document/d/1fVNyskIgMoiNeOOGt57LdDmEkAShkYUKYQTkf5yD1fA/edit
> 
> except that this would apply to the same target instead of only the dependencies.

Yes, this is what I was referring to with *aspects propagating aspects* [above](https://github.com/bazelbuild/bazel/issues/11736#issuecomment-711840083) and why I thought it was relevant to bring up this feature request in the context of that proposal.

**Comment by lberki** [comment]
Absolutely! I'm not entirely convinced that that proposal is a good idea. I'll ponder a bit to see whether this use case could be accommodated somehow.

**Comment by janakdr** [comment]
This is not in core-team's competence. @lberki is there a better category for this?

**Comment by shahms** [comment]
Potentially related to this (but I can open a separate bug if desired) is that command-line aspects can't inspect providers or actions supplied by other aspects on the transitive dependencies they've propagated down.  For example:
```
proto_library(name = "base_proto")
proto_library(name = "leaf_proto", deps =[":base_proto"])
lang_proto_library(name = "leaf_cc_proto", deps = [":leaf_proto"])
```
Given the above, a command line aspect applied to `:leaf_cc_proto` can see the actions and providers on the `deps` edge between `:leaf_cc_proto` and `:leaf_proto` but cannot see those on the implicit edge between `:leaf_proto` and `:base_proto`.
