### ISSUE TITLE
Bazel never time-out on UNKNOWN Status from Remote Cache on Read

### ISSUE THREAD

**Issue by stefanhoelzl** [bazelbuild/bazel#11746]
### Description of the problem / feature request:
When a remote cache always response with UNKOWN status on a ByteStream::Read request, Bazel retries forever to download the blob.

### What operating system are you running Bazel on?
macOS 10.15 but should be independent from the OS

### What's the output of `bazel info release`?
release 3.3.1

**Comment by oquenchil** [comment]
Can you please provide a small repro and logs?

**Comment by aiuto** [comment]
Closing on lack of action.
