### ISSUE TITLE
Platform/toolchain support for Android rules

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel#11749]
This tracks a [Blaze configurability roadmap](https://bazel.build/roadmaps/configuration.html) effort.

This plus comparable support for Apple rules should also be sufficient to default on support for C++ as covered in https://github.com/bazelbuild/bazel/issues/6516

**Comment by ahumesky** [comment]
Is this complete?

**Comment by katre** [comment]
Indeed it can, thanks!
