### ISSUE TITLE
Short Starlark flags

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel#11750]
### Description of the problem / feature request:

Provide a way to alias [Starlark flags](https://docs.bazel.build/versions/master/skylark/config.html#user-defined-build-settings) so they don't take up so much space on the command line.

### Feature requests: what underlying problem are you trying to solve with this feature?

Keep command lines crisp, simple, focused, uncluttered, and clear.

Also, as we migrate native (built into Bazel) flags like `--cpu` to Starlark flags, we don't want that to bloat command lines.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```sh
# Native (built directly into Bazel) flag:
$ bazel build //:my_project --cpu=x86
```

```sh
# Same-repository Starlark flag:
$ bazel build //:my_project --//my/starlark_flags:flag=foo
```

```sh
# Different-repository Starlark flag:
$ bazel build //:my_project --@some_other_repo//my/starlark_flags:flag=foo
```

###  Have you found anything relevant by searching the web?

* [Starlark configuration docs](https://docs.bazel.build/versions/master/skylark/config.html)
* [Starlark configuration examples](https://github.com/bazelbuild/examples/tree/master/rules/starlark_configurations)

Design document forthcoming.

**Comment by WarkahScott** [comment]
Design Doc: [Starlark Shorthand Flag Mapping](https://docs.google.com/document/d/1qDz9VEJNEY-sybYCg53WqIQFbsBMR3gVDYbFFwS1OM4/edit?usp=sharing)

**Comment by gregestren** [comment]
FYI @WarkahScott authored and committed https://github.com/bazelbuild/bazel/commit/b47f2287d9d8f29af94cb5a3a1b1aae2a955b2ef, even though it self-attributes to "Googler". 

I believe future commits will correctly attribute @WarkahScott .

**Comment by WarkahScott** [comment]
Implemented, should be available in the next release 🎉
