### ISSUE TITLE
bazel.build website lists 3.3.0 as latest non-master version even though github lists more recent releases

### ISSUE THREAD

**Issue by lhorie** [bazelbuild/bazel#11760]
### Description of the problem / feature request:

Website appears to be out of date with regards to released versions

### Feature requests: what underlying problem are you trying to solve with this feature?

Ensure that the website lists up-to-date documentation

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Go to https://docs.bazel.build/versions/master/bazel-overview.html and open the dropdown on the left menu. Notice that it lists master and versions 3.3.0 and below, but not versions 3.3.1 and 3.4.0, even though those versions are listed in https://github.com/bazelbuild/bazel/releases. 

### What operating system are you running Bazel on?

N/A

### What's the output of `bazel info release`?

N/A

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

N/A

### Any other information, logs, or outputs that you want to share?

N/A

**Comment by katre** [comment]
Documentation build was broken by the problems with the 3.4.0 release. Once 3.4.1 is ready, we can rebuild documentation and upload it. Sorry for the inconvenience. See #11756 and #11687 for details.

Closing this, please track progress on the official release issue.
