### ISSUE TITLE
Any reason for bazel-3.4.1-linux-arm64 not provided in the releases page?

### ISSUE THREAD

**Issue by storypku** [bazelbuild/bazel#11767]
I noticed that bazel-3.4.0-linux-arm64 was provided for arm64 support, while bazel-3.4.1-linux-arm64 was missing.

My question is,  Can we expect the Bazel team to continue to provide arm64 bazel binary for every new release?

**Comment by meisterT** [comment]
For now the process for arm64 is manual, that's why the release is missing.

cc @philwo

**Comment by philwo** [comment]
I'll upload them tomorrow! In the future they will be built and uploaded automatically together with the other binaries :)

**Comment by storypku** [comment]
> I'll upload them tomorrow! In the future they will be built and uploaded automatically together with the other binaries :)

That's great! Thank you for the updates. 

Another related question, for https://github.com/bazelbuild/buildtools, could you please provide buildifier & buildozer arm64 binaries?

**Comment by philwo** [comment]
Bazel 3.4.1 Linux arm64 binaries are available now on our GitHub release page on and on https://releases.bazel.build/3.4.1/release/.

I'll look at buildifier & buildozer in the next days :)

**Comment by philwo** [comment]
I'm tracking that here: https://github.com/bazelbuild/buildtools/issues/874
