### ISSUE TITLE
--remote_download_minimal does not work with query

### ISSUE THREAD

**Issue by cheister** [bazelbuild/bazel#11770]
### Description of the problem / feature request:

`--remote_download_minimal` is documented as an option for `bazel query` https://docs.bazel.build/versions/master/command-line-reference.html#flag--remote_download_minimal but trying to use it causes the following error
```
bazel query --remote_download_minimal //baz/...
ERROR: --nobuild_runfile_links :: Unrecognized option: --nobuild_runfile_links
```

### What operating system are you running Bazel on?

macOS 10.15.5

### What's the output of `bazel info release`?

release 3.4.1

**Comment by oquenchil** [comment]
@meisterT

**Comment by meisterT** [comment]
This issue is not stale and needs to be fixed before we can make bwob the default (cc @tjgq @coeuvre).

**Comment by coeuvre** [comment]
This should be fixed since `--remote_download_minimal` no longer expands to `--nobuild_runfile_links`.
