### ISSUE TITLE
dummy_link for Windows runfiles can causes rare build failures

### ISSUE THREAD

**Issue by tomrenn** [bazelbuild/bazel#11779]
### Description of the problem / feature request:

In rare instances we have seen the following error in builds.

```
build-runfiles error: CreateSymbolicLinkW failed: (error: 183): Cannot create a file when that file already exists.
```

Further investigation found a `dummy_link` file was under a host config tool under `$EXECUTION_ROOT/bazel-out/host/...`. Our builds use dynamic scheduling and `--windows_enable_symlink`, although both of these seem irrelevant to cause the problem. 

Until we remove `dummy_link` all builds on our CI failed with the CreateSymbolicLinkW error. 

Since we use `--windows_enable_symlink`, we guarantee our Windows host is up to date and running with Developer Mode enabled. It should be possible then to avoid the creation of `dummy_link` for determining if symlinking is supported.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

We do not have a clear repro case

### What operating system are you running Bazel on?

Windows Server 2019.

### What's the output of `bazel info release`?

[modified 1.1.0] release

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

We have built a custom version of Bazel 1.1.0 with the following changes cherry-picked:

- https://github.com/bazelbuild/bazel/commit/cffd417a4c4ec4d082f815f57a771ad1010972dd
- https://github.com/bazelbuild/bazel/commit/08a15e795107ec76d574579223485a3efb9da274

**Comment by tomdegoede** [comment]
After upgrading to bazel 3.6 we are encountering this issue as well (at least three times now). I do not recall seeing it before. @meteorcloudy out ci machines are running with just the Create Symlink privilege enabled, not developer mode. I do see the dummy_link file existing on disk.
