### ISSUE TITLE
Allow *_test rules to define args

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#11772]
Currently, tests must be entirely self contained. That is, they specify both the sources and data files. This makes it difficult to reuse a common test framework binary with different parameters or data files.  For example, we might have a testing framework for fuzzy diffing against a golden file. We would like to create a rule that can be invoked as

```
fuzzy_diff_test(
  name = 'a_test',
  expected_content = 'expected_a_test.txt',
  content = ':my_rule'
)

fuzzy_diff_test(
  name = 'b_test',
  expected_content = 'expected_b_test.txt',
  content = ':my_rule'
  opts = ['ignore_intralline_spaces', 'no_ignore_blank_lines', 'ignore_dates'],
)
```

The rule would implicitly depend on the testing tool, so it need not be specified in srcs. The rule implementation would repackage `opts` as args to the tool.  We could also imagine this as a feature of the existing *_test rules. `build` of the rule would build the binary, `test` of the rule would create a new action in the graph which binds the rule to the args and execute that.

- `opts` should be select()able, so users can change them based on configuration.
- some form of Make style variable substitution would also be useful, but could be added later.

The main blocker to doing this today is that rules return only a DefaultInfo pointing to an executable. We would need to refactor that a bit to allow a provider for the test args.

Related to #7364

**Comment by aiuto** [comment]
cc: @sdtwigg

**Comment by jbms** [comment]
How does this compare to what can be done with the existing skylark macro ("def") facility?

**Comment by aiuto** [comment]
The goal is to build a binary once, then invoke it with different args. Current tests always need to create a binary, then run it with no args. In the basic form, it is like this.

```
cc_binary(name = "foo_test_tool", srcs=...)

test(
   name="a_test",
   tool = ":foo_test_tool",
   opts = ["-input", "$(location :a)"],
   data = [':a'],
)
```

a_test does not have its own executable, it only depends on things and has a run action. Current tests don't do a run, they only create the executable.  
The way people work around this with macros today is to generate have their custom test rule write a small shell script that runs their binary and return the script as the executable. The failure there is that it is hard to write portable and precise shell scripts.

**Comment by jbms** [comment]
Decoupling the command-line arguments (and ideally, environment variables), and data deps, from the test binary itself certainly makes sense.  I could imagine an alternative way to support that could be for bazel itself to deduplicate binaries where an identical binary would be built, so then this would be equivalent to just having multiple cc_test rules with the same srcs and deps but different args and data deps.  However, I think your proposal is cleaner, since separating building the binary from specifying the test arguments is pretty common in other build frameworks; in fact the way bazel couples it is kind of unusual.  I'd suggest maybe using `args` instead of `opts`, and perhaps `binary` instead of `tool`.  Being able to specify additional `deps` would also be useful in some cases, I think (e.g. where additional "drivers" are registered by linking them in), but of course that would require relinking so there would only be a gain in convenience, not efficiency.

**Comment by lberki** [comment]
Building a binary once and executing it multiple times is easily achievable by wrapping a `*_binary` rule in a `sh_test` and setting the `args` argument of the latter. Sure, there is a little shell script, but it is really that difficult to write

```
#!/bin/bash
exec <location of actual binary> "$@"
```

? If need be, the location can be filled in by a little Starlark rule.

**Comment by aiuto** [comment]
Using shell is, to me, a serious problem to be avoided. Doing shell
portably across all OSes and getting args with spaces in them parsed
correctly is hard.

**Comment by sdtwigg** [comment]
For sh_test, won't it actually accept the executable directly as the source file? Then you don't even need a wrapper.

**Comment by hashar** [comment]
@aiuto I was wondering how to pass arguments to a test utility #19661 and eventually found the issue you filed a few years ago which seems to match my use case. My approach was to use `arguments` when defining the rule, something such as:
```python
ctx.actions.run(
  arguments = ctx.attrs.opts
   ...
```
But when the `TestAction` is created, the `arguments` is not added to the resulting command.  However I found out that `args` from the `*_test` rule is passed so one can do:
```python
foobar_test(
  name = "test",
  args = ['ignore_intralline_spaces', 'no_ignore_blank_lines', 'ignore_dates'],,
)
foobar_test(
  name = "test_with_options",
)
```
`bazel test //:test` would then run with the set of options.

`bazel test //:test_with_options` would have no arguments passed but one can pass extra ones from the command line:
```
bazel test //:test_with_options 'ignore_dates'
```

**Comment by hashar** [comment]
**BUILD**
```python
load("//:rules.bzl", "fuzzy_diff_test")

fuzzy_diff_test(
  name = 'a_test',
)

fuzzy_diff_test(
  name = 'b_test',
  args = ['ignore_intralline_spaces', 'no_ignore_blank_lines', 'ignore_dates'],
) 
```

**rules.bzl**
```python
def _fuzzy_diff_impl(ctx):
    output_file = ctx.actions.declare_file(ctx.label.name + ".output")

    executable = ctx.actions.declare_file(ctx.executable._fuzzy_diff_cli.path)
    ctx.actions.symlink(
        output = executable,
        target_file = ctx.executable._fuzzy_diff_cli,
        is_executable = True,
    )
        
    print(executable)
    
    ctx.actions.run(
        executable = executable,
        outputs = [output_file],
    )       
        
    return [
        DefaultInfo(
            executable = executable,
        ),
    ]
    
fuzzy_diff_test = rule(
    implementation = _fuzzy_diff_impl,
    test=True,
    attrs = {
        "_fuzzy_diff_cli": attr.label(
            default = "//:fuzzy_diff",
            allow_single_file = True,
            executable=True,
            cfg="exec",
        ),
    }
)
```
**fuzzy_diff**
Dumps the arguments and always exit 2.
```python
#!/usr/bin/python3

import os
import sys

print("=== ARGUMENTS =====================")
print("Command: ", sys.argv[0])
num_args = len(sys.argv[1:])

print("Given %s argument%s:" % (num_args, '' if num_args==1 else 's'))
i = 0
for arg in sys.argv[1:]:
    i += 1
    print("#%s: '%s'" % (i, sys.argv[i]))

sys.exit(2)
```

Running `bazel test ...`:

`//:a_test` has no `args` and thus no arguments are passed to the command:
```
INFO: From Testing //:a_test:
==================== Test output for //:a_test:
=== ARGUMENTS =====================
Command:  execroot/__main__/bazel-out/k8-fastbuild/bin/fuzzy_diff.runfiles/__main__/fuzzy_diff
Given 0 arguments:
================================================================================
```

`//:b_test` has a list of arguments and they are passed down to the command:
```
INFO: From Testing //:b_test:
==================== Test output for //:b_test:
=== ARGUMENTS =====================
Command:  execroot/__main__/bazel-out/k8-fastbuild/bin/fuzzy_diff.runfiles/__main__/fuzzy_diff
Given 3 arguments:
#1: 'ignore_intralline_spaces'
#2: 'no_ignore_blank_lines'
#3: 'ignore_dates'
================================================================================
```


`bazel run //:a_test` has no arguments passed

`bazel run //:a_test hello foo bar` pass all three arguments to the command:
```
=== ARGUMENTS =====================
Command:  execroot/__main__/bazel-out/k8-fastbuild/bin/fuzzy_diff.runfiles/__main__/fuzzy_diff
Given 3 arguments:
#1: 'hello'
#2: 'foo'
#3: 'bar'
```

`bazel run //:b_test` has the three arguments passed to the command (`ignore_intralline_spaces`, `no_ignore_blank_lines` and `ignore_dates`)

`bazel run //:b_test ANOTHER_OPTION` appends `ANOTHER_OPTION` to the three args:
```
=== ARGUMENTS =====================
Command:  execroot/__main__/bazel-out/k8-fastbuild/bin/fuzzy_diff.runfiles/__main__/fuzzy_diff
Given 4 arguments:
#1: 'hello'
#2: 'foo'
#3: 'bar'
```

**Comment by hashar** [comment]
My conclusion is one can use `args` in the rule:
```python
fuzzy_diff_test(
  name = 'b_test',
  expected_content = 'expected_b_test.txt',
  content = ':my_rule'
  args = ['ignore_intralline_spaces', 'no_ignore_blank_lines', 'ignore_dates'],
  ^^^^
)
```
