### ISSUE TITLE
Consider to remove deprecated -Xverify:none option from javac invocation

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#11773]
Trying to build with [java toolchain 14](https://github.com/bazelbuild/bazel/pull/11514), I'm seeing this warning:

```
INFO: From Compiling Java headers javatests/com/google/gerrit/server/query/group/libabstract_query_tests-hjar.jar (1 source file):
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
```

This is because of: https://bugs.openjdk.java.net/browse/JDK-8214731.

We should consider to remove this option entirely.

**Comment by meisterT** [comment]
See https://github.com/bazelbuild/bazel/pull/11774#issuecomment-660182407 for some measurements. Since this would regress Bazel server startup performance by 25% we won't do this.
