### ISSUE TITLE
Docker image with file from genrule has incorrect name

### ISSUE THREAD

**Issue by pgr0ss** [bazelbuild/bazel#1178]
I noticed an issue where I have a top level `genrule` which has an outs (e.g. `abcd`):

```
genrule(
  name = "myfile",
  visibility = ["//visibility:public"],
  cmd = 'echo hello > $@',
  outs = ["abcd"],
  srcs = [],
)
```

And then I create a docker image with that genrule, the filename inside the image is always the last letter of the filename instead of the whole name:

```
docker_build(
  name = "mydocker",
  tars = ["alpine.tar"],
  files = ["//:myfile"],
)
```

Then, the filename will be `d` instead of `abcd`.

Here's a demo repository showing the bug: https://github.com/pgr0ss/bazel_docker_bug_reproduction

I saw this on bazel versions 0.2.0 and 0.2.2.

**Comment by damienmg** [comment]
Nice catch, don't it happens also with a simple file?

**Comment by pgr0ss** [comment]
You're right. It also happens with a simple file if the file is top level. If the file is not top level, it seems to work correctly.

**Comment by vladlosev** [comment]
Happens to me with bazel 0.4.4.

**Comment by yeputons** [comment]
[Happened to me](http://stackoverflow.com/questions/42241527/docker-image-created-by-bazel-does-not-have-repository-tag-files-are-packed-wit) with Bazel 0.4.4 as well, [gist](https://gist.github.com/yeputons/c90a5d3d6f8b819aadecf68260b1c5bb)
