### ISSUE TITLE
Feature Request: Support build rules for JavaScript transpilers (TypeScript, ES2015)

### ISSUE THREAD

**Issue by jonathantyates** [bazelbuild/bazel#1179]

**Comment by damienmg** [comment]
We are discussing opensourcing a TypeScript support. We also have support for closure (https://github.com/bazelbuild/rules_closure)

**Comment by jonathantyates** [comment]
Awesome, thanks for the update.  And for pointing out Closure support,  I had been searching for [JavaScript](http://bazel.io/search.html?cx=012346921571893344015%3Axv_nfgpzbu4&cof=FORID%3A10&ie=UTF-8&q=javascript).

**Comment by jin** [comment]
I believe we now have rules_typescript and rules_nodejs :-)
