### ISSUE TITLE
bazel run test does not work on Windows

### ISSUE THREAD

**Issue by sonukapoor** [bazelbuild/bazel#11808]
### Description of the problem / feature request:

When trying to run a test using `bazel run ...` the following error is thrown:

>Error: Cannot find module 'C:\users\sonukapoor\_bazel_sonukapoor\7lxopdvs\execroot\angular\bazel-out\x64_windows-fastbuild\bin\packages\core\test\bundling\forms\symbol_test.bat.runfiles\angular\c;C:\msys64\users\sonukapoor\_bazel_sonukapoor\7lxopdvs\execroot\angular\bazel-out\x64_windows-fastbuild\bin\packages\core\test\bundling\forms\symbol_test.bat.runfiles\angular\packages\core\test\bundling\forms\symbol_test_require_patch.js'

I believe the same works fine in a `MacOs` environment. 
In a windows environment, tests can only be run using `bazal test ...`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. clone the angular repo in a windows env.
2. yarn install
3. run `yarn bazel run packages/core/test/bundling/hello_world:symbol_test`

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

> C:\projects\Archive\angular>yarn bazel info release
yarn run v1.22.4
$ C:\projects\Archive\angular\node_modules\.bin\bazel info release
Starting local Bazel server and connecting to it...
release 3.2.0
Done in 28.25s.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

* git@github.com:sonukapoor/angular.git
* e382632473dc92b6292ec264c9120bd07ca926bd
* 37dc3f7d1bbe593f30cb512c6e10284463a28c34

**Comment by philwo** [comment]
What's the use-case for running a test with `bazel run`?
