### ISSUE TITLE
try-import is relative to CWD but should be relative to repository root

### ISSUE THREAD

**Issue by kerrick-lyft** [bazelbuild/bazel#11803]
### Description of the problem / feature request:

The [Bazel docs](https://docs.bazel.build/versions/master/best-practices.html) suggest that in order to manage user-specific settings, you add a `user.bazelrc` file to the root of your repository (and not check it in to Git), then add `try-import user.bazelrc` to your `.bazelrc`.

However, this has the issue that unless the CWD is the repository root, the file `user.bazelrc` will not be found, so the settings won't be applied.

Here are two possible fixes:
- Always make `try-import` search from the workspace root. It's possible that this will break some use-cases (e.g. maybe some people have `user.bazelrc` files in subdirectories in their workspaces?) but I'm guessing nobody will notice.
- Introduce some syntax like `try-import //:user.bazelrc` that allows users to specify a file in the repo root.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run the below commands. The expected behavior is that the second build command does not rebuild. The actual behavior is that it rebuilds, this time without `--copt=-w`.

```
cd $(mktemp -d)
git clone https://github.com/kerrick-lyft/bazel-try-import-issue.git
cd bazel-try-import-issue
bazel build //foo:bar
cd foo
bazel build :bar
```

### What operating system are you running Bazel on?

macOS 10.15.4 (19E266)

### What's the output of `bazel info release`?

```
release 3.3.0-homebrew
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
git@github.com:kerrick-lyft/bazel-try-import-issue.git
4369700060409a0ac0da12fa6c2f2acdc8851ffd
4369700060409a0ac0da12fa6c2f2acdc8851ffd
```

###  Have you found anything relevant by searching the web?

Nope.

### Any other information, logs, or outputs that you want to share?

N/A

**Comment by kerrick-lyft** [comment]
It looks like the syntax `%workspace%/user.bazelrc` is already supported and fixes this problem. I opened a pull request against the docs: https://github.com/bazelbuild/bazel/pull/11804

**Comment by philwo** [comment]
Thanks for the PR and glad that there was a workaround!

This still feels like a bug to me which we might want to fix, so I'll keep this open.
