### ISSUE TITLE
Win7-64: Bazel.exe fails with "Unexpected pipe read status: Connection refused"

### ISSUE THREAD

**Issue by fhein** [bazelbuild/bazel#1181]
I built Bazel.exe via msys shell. Starting ./bazel.exe gives the output below.

I wanted to have bazel to create a Win build of Tensorflow. Is there a chance to get further?

`$ ./bazel.exe
Verbindung erstellt f▒r C:\TEMP\Bazel\SbQZaNFG\install <<===>> C:\TEMP\_bazel_frank.hein\install\4f72339f88b0cfecb46f44126c219fce
.......
unexpected pipe read status: Connection refused
Server presumed dead. Now printing '/c/TEMP/Bazel/SbQZaNFG/server/jvm.out':
I/O Error: C:/TEMP/Bazel/SbQZaNFG/server/server.pid (No such file or directory)`

**Comment by damienmg** [comment]
We are not feature complete on windows and it requires the `--batch` flag.

Note that we have still many issue to build TensorFlow on windows and even if you will be able to run bazel, you won't be able to build TensorFlow yet. We are working actively on it and hope to make good progress in the next two months.

**Comment by fhein** [comment]
Ok. Thanks. I'll be back when it's ready.
