### ISSUE TITLE
embedded @platforms repo is old

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#11826]
Bazel currently embeds https://github.com/bazelbuild/platforms/commit/46993efdd33b73649796c5fc5c9efb193ae19d51 from November of last year. It'd be nice to bump this up to the current HEAD.

**Comment by katre** [comment]
Assigning to @aiuto to handle a release.

**Comment by aiuto** [comment]
I did the release, https://github.com/bazelbuild/platforms/releases/tag/0.0.2
Now we have to update bazel
