### ISSUE TITLE
bazel crashes with IllegalStateException when "remote_download_toplevel" is passed to local build

### ISSUE THREAD

**Issue by amarshat** [bazelbuild/bazel#11825]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

`bazel` crashes with `java.lang.IllegalStateException` when `--remote_download_toplevel` is passed to a local build. Often we run remote builds and local builds via a wrapper and keep the same arguments. If the build is not remote (i.e. no --remote_executor) is provided, bazel crashes. 

### Feature requests: what underlying problem are you trying to solve with this feature?

Consistent behaviour with incompatible flags. If the flag is not compatible, we should errorout. Ideally this flag should be a noop for local builds. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```sh
workspace=$(mktemp -d)
cd $workspace/
touch WORKSPACE BUILD.bazel
bazel build //... --remote_download_toplevel
```

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 3.4.1

**Comment by jin** [comment]
Linking back to the tracking issue: https://github.com/bazelbuild/bazel/issues/6862
