### ISSUE TITLE
bazel try to download same blob from remote cache multiple times

### ISSUE THREAD

**Issue by lizan** [bazelbuild/bazel#11827]
### Description of the problem / feature request:
Bazel send multiple same request to remote HTTP cache or gRPC cache.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
```bazel build @envoy//bazel/foreign_cc:nghttp2``` with remote cache from latest https://github.com/envoyproxy/envoy

### What operating system are you running Bazel on?
Ubuntu 18.04

### What's the output of `bazel info release`?
3.4.1

### Any other information, logs, or outputs that you want to share?
This triggers a bug in bazel-remote: https://github.com/buchgr/bazel-remote/issues/318, while that's bazel-remote's bug, bazel shouldn't request same blob multiple times with same hash.

If the blob happens to be big, this would impact performance negatively and incur unnecessary data transfer cost.

**Comment by coeuvre** [comment]
I think this is fixed by recent changes to RemoteCache which are included in the upcoming 5.0 release.
