### ISSUE TITLE
java_proto_library is missing transitive_source_jars

### ISSUE THREAD

**Issue by jfancher** [bazelbuild/bazel#11830]
### Description of the problem / feature request:

The `java_proto_library` rule creates a [JavaInfo](https://docs.bazel.build/versions/3.4.0/skylark/lib/JavaInfo.html) provider. Contrary to the documentation, the generated source files for the library are _not_ included in `transitive_source_jars`. They do, however, appear as `source_jars`.

The documentation for `transitive_source_jars` says "[...] of the current target and all of its transitive dependencies" so I would expect it to always be a superset of `source_jars` -- and this does seem to be the case for `java_library` at least.

Naturally, being missing from the transitive set prevents protobuf sources from being discovered when analyzing targets that use the proto library as a dep.

### Bugs: what's the simplest, easiest way to reproduce this bug?

Full reproducer here:
https://github.com/jfancher/bazel-issues/tree/java_proto_provider

This is also affecting the `java_export` example in `rules_jvm_external` -- when you run `//:example-export.publish` the published source and Javadoc jars are missing the protobuf library:
https://github.com/bazelbuild/rules_jvm_external/tree/3.3/examples/java-export

### What operating system are you running Bazel on?

Linux (WSL)

### What's the output of `bazel info release`?

`release 3.4.1`

###  Have you found anything relevant by searching the web?
#10055 is similar in terms of use case, but I'm unsure if the details are related.

**Comment by c-mita** [comment]
This had to be rolled back due to internal breakages; some investigation is still required.
