### ISSUE TITLE
Slow performance when resolving symbolic links

### ISSUE THREAD

**Issue by ehrtro** [bazelbuild/bazel#11831]
### Description of the problem / change request:
When building with Bazel, our code can currently be efficiently built with bazel caches only if we're getting cache hits in our workspace cache and have "warm" bazel Java processes running. Otherwise (e.g. if the cache hit is from disk-cache or remote-http-cache, or if running in batch mode) the build is very slow, especially if it involves many .so files. This is due to that we're creating unnecessarily many symlinks to the same files. As mentioned in https://github.com/bazelbuild/bazel/commit/fca63525158321e5a5f0ff67a8796992a7347c73, the usage of --experimental_multi_threaded_digest enhances the performance somewhat, but we're still experiencing unnecessarily long build times. We suspect there is something else problematic with SolibSymlink target. Our local patch resolves the symlinks before hashing the files in order to shorten the build times:

Our changes to [these lines in manuallyComputeDigest](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/actions/cache/DigestUtils.java#L244-L253) is to be found below 

```
    // Attempt a cache lookup if the cache is enabled.
    Cache<CacheKey, byte[]> cache = globalCache;
    CacheKey key = null;
    if (cache != null) {
      Path canonicalPath = path.resolveSymbolicLinks();
      key = new CacheKey(canonicalPath, canonicalPath.stat());
      digest = cache.getIfPresent(key);
      if (digest != null) {
        return digest;
      }
    }
```
What's your opinion regarding this patch in order to get a shorter build time? When using this patch in our local environment we've experienced a performance enhancement; A build that previously took 17 seconds to finish is now done in 8 seconds. Using this patch and  --experimental_multi_threaded_digest at the same time gives us the best result. 

### What operating system are you running Bazel on?
Red Hat Enterprise 7 (RHEL7) Linux kernel 3.10.0-1127.8.2.el7.x86_64

**Comment by ehkloaj** [comment]
Here is a pull request for this issue, #11832. 
Do you think that this functionality should be introduced together with a --experimental_... flag?

**Comment by meisterT** [comment]
Should this be closed now that the PR is merged?

**Comment by ehrtro** [comment]
Yes, we're satisfied with the solution! Thanks for fast response!

**Comment by joeleba** [comment]
Due to https://github.com/bazelbuild/bazel/issues/12225, we'll roll back 81245fd to minimize the impact and will perhaps get back to it later.
