### ISSUE TITLE
run and test on Windows require shorter path on D: drive than C: drive with runfiles enabled

### ISSUE THREAD

**Issue by plule-ansys** [bazelbuild/bazel#11833]
### Description of the problem / feature request:

Hello, on Windows, starting from Bazel 3.1 (not visible on Bazel 3.0), bazel run and bazel test will fail under the following condition:
 - --enable_runfiles
 - output user root is on the drive letter D:
 - label size is long (I get it starting from around 90 characters, with the shortest output user root possible)

The error is:

```
Executing tests from //very_long_path/very_long_path/very_long_path/very_long_path/very_long_path:very_long_path
-----------------------------------------------------------------------------
ERROR(tools/test/windows/tw.cc:1283) ERROR: src/main/native/windows/process.cc(95): WaitableProcess::Create(D:\a\d2ru2cha\execroot\__main__\bazel-out\x64_windows-fastbuild\bin\very_long_path\very_long_path\very_long_path\very_long_path\very_long_path\very_long_path.exe.runfiles\__main__\very_long_path\very_long_path\very_long_path\very_long_path\very_long_path\very_long_path.exe): ERROR: src/main/native/windows/util.cc(287): AsExecutablePathForCreateProcess(D:\a\d2ru2cha\execroot\__main__\bazel-out\x64_windows-fastbuild\bin\very_long_path\very_long_path\very_long_path\very_long_path\very_long_path\very_long_path.exe.runfiles\__main__\very_long_path\very_long_path\very_long_path\very_long_path\very_long_path\very_long_path.exe): ERROR: src/main/native/windows/util.cc(257): GetShortPathNameW(\\?\D:\a\d2ru2cha\execroot\__main__\bazel-out\x64_windows-fastbuild\bin\very_long_path\very_long_path\very_long_path\very_long_path\very_long_path\very_long_path.exe.runfiles\__main__\very_long_path\very_long_path\very_long_path\very_long_path\very_long_path\very_long_path.exe): cannot shorten the path enough
ERROR(tools/test/windows/tw.cc:1440) Failed to start test process (arg: D:\a\d2ru2cha\execroot\__main__\bazel-out\x64_windows-fastbuild\bin\very_long_path\very_long_path\very_long_path\very_long_path\very_long_path\very_long_path.exe.runfiles\__main__\very_long_path\very_long_path\very_long_path\very_long_path\very_long_path\very_long_path.exe)
```

The location of the source does not seem to matter.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Open attachement: [bazel31_long_path_repro.zip](https://github.com/bazelbuild/bazel/files/4972237/bazel31_long_path_repro.zip)

`bazel test //...`

This archive contains an appropriate .bazelrc with D: as a letter and `--enable_runfiles`. Changing the letter to C: or removing the runfiles option fixes the issue.

### What operating system are you running Bazel on?

Windows 10 1903

### What's the output of `bazel info release`?

release 3.4.1

reproducible with 3.1.0, not reproducible with 3.0.0.

###  Have you found anything relevant by searching the web?

(pure speculation):

d899a036bd043fcde7db8a7d568c102f50411c79 introduced a change so that when runfiles are enabled on windows, the executable from the runfiles tree will be used instead of the original. It looks like this change would add a huge length to the path size to execute (around twice as the label is duplicated in the path).

No sane explanation for the difference of behavior between `C:` and `D:`.

**Comment by meisterT** [comment]
cc @meteorcloudy

**Comment by mai12** [comment]
It can be because the short name is disabled on the D: volume. By default, it is only enabled on the system volume (C:). 

So you can run this command to enable 8dot3name settings (i.e. short name settings) on all volumes.

> fsutil 8dot3name set 0

Then delete the existing output directory (D:\a) and try again.

**Comment by meteorcloudy** [comment]
@plule-ansys , can you try if Mai's solution solves the problem for you?

**Comment by plule-ansys** [comment]
@mai12 It improves the situation, thank you! It might be worth documenting this setting in the documentation, long path are a recurring issue when working with Bazel on Windows.

**Comment by meteorcloudy** [comment]
@mai12 Can you help document this issue and solution at https://docs.bazel.build/versions/master/windows.html#best-practices?
