### ISSUE TITLE
Inconsistent failure (IOException) when .runfiles contains an possibly invalid symlink?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [bazelbuild/bazel#11843]
Note: This is a very hand wavy bug report, possibly due to an upgrade from Bazel 3.0.0 to 3.4.1.
Feel free to close if this is not sufficiently informative.

### Description of the problem / feature request:

I made a bad provisioning script that included symlinks, and it would only *occasionally* fail on our CI with something like this:
```
[0 / 591] [Prepa] Expanding template {toplevel_target} ... (6 actions, 0 running)
ERROR: {package_src}/BUILD.bazel:55:1: Couldn't build file {target}/test.log:  failed due to unexpected I/O exception: The file type of 'bazel-out/k8-opt/bin/{target}.runfiles/{pip_archive}/lib/python3.6/config-3.6dm-x86_64-linux-gnu/libpython3.6dm.so' is not supported.
java.io.IOException: The file type of 'bazel-out/k8-opt/bin/{target}.runfiles/{pip_archive}/lib/python3.6/config-3.6dm-x86_64-linux-gnu/libpython3.6dm.so' is not supported.
```

The issue wasn't that it failed on the symlink; rather, it was that it seemed to occasionally fail.

It had worked on my machine, and initially on CI, but then broke the next day.

We're fixing the symlink part ofc, but it'd be nice at some point to root cause this and make it deterministic?

### Feature requests: what underlying problem are you trying to solve with this feature?

For simplicity / compactness, we provision `pip` deps using `virtualenv` in a manual build process, then tar up a subset of the resulting files.

With only brief investigation, we had tried out switching over to `load("@rules_python//python:pip.bzl", "pip3_import", "pip_repositories")`, but found that it was slower on individual machine rebuilds for the num. of packages we rebuild, and we have a relatively homogeneous workstation setup.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I unfortunately do not have this answer at the moment - sorry :(

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

`release 3.4.1`

It may have also intermingled with artifacts from `3.0.0` ???

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Private.
(Self cookie-crumb: internal repo, issue 5101)

###  Have you found anything relevant by searching the web?

- GitHub issues: Did not see anything crop up here when doing brief search for "symlink IOException"

### Any other information, logs, or outputs that you want to share?

Not at the moment, sorry :(

**Comment by EricCousineau-TRI** [comment]
FTR, if it is due to cross-versions, I did not come across this when using the offending commit on our private repo, where it passed with Bazel 3.0.0, and still passed when I ran the test with Bazel 3.4.1.

(Granted, we may do more finicky artifact sharing in CI.)

**Comment by oquenchil** [comment]
Yes sorry Eric, let's close for now until you can provide a small repro that we can use to diagnose the problem.
