### ISSUE TITLE
bazel_apple_test is broken with latest push

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1184]
See http://ci.bazel.io/job/Bazel/490/JAVA_VERSION=1.8,PLATFORM_NAME=darwin-x86_64/testReport/junit/(root)/(empty)/test_swift_library/

Assigning to dmishe who authored the test

**Comment by dmishe** [comment]
It needs a current SDK version. How do we setup those for Jenkins?

**Comment by damienmg** [comment]
what do you mean?

**Comment by dmishe** [comment]
The test fails because the default --ios_sdk_version value (8.4) is not available on that machine. We need to pass it a current version of SDK that is installed. It's often equal to the Xcode version.

**Comment by damienmg** [comment]
Ah ok I see, thanks for fixing that so fast!
