### ISSUE TITLE
The OSX libtool wrapper increases incremental build times

### ISSUE THREAD

**Issue by michaeleisel** [bazelbuild/bazel#11846]
`tools/objc/libtool.sh` increases the incremental build time for a single-target app with 700 implementation files by ~3 seconds. It appears that /usr/bin/libtool takes only a fraction of a second, but the work being done beforehand with symlinks and hashing takes longer. This work is to prevent giving libtool object files with the same basename. A few things:

- libtool seems to just throw a warning, rather than error out. Is there really a problem here?
- If so, which parts of this  can we get rid of? E.g., reproducible hashing, symlinks for all files rather than just the duplicates, etc.

**Comment by michaeleisel** [comment]
@c-parsons can you provide some context on this?

**Comment by keith** [comment]
I would definitely be curious to know what the bug mentioned here is (or was):

https://github.com/bazelbuild/bazel/blob/6326ff803765b08fb09727835827f9d3a73d7d07/tools/objc/libtool.sh#L61-L64

**Comment by kastiglione** [comment]
Last I checked, basenames needs to be unique in Swift modules.

**Comment by c-parsons** [comment]
This change was from several years ago, so take my recollection with a grain of salt.
If I recall correctly, these libtool warnings for same-basename files was problematic for Xcode integration when compiling objective C sources. Given your findings on build performance, we should maybe revisit this.

**Comment by michaeleisel** [comment]
So we could either:
- detect if everything is unique, in which case take a fast path
- only for those that are not unique do this work
- try to optimize the specific operations being done
 
I don't like working in bash, so if I'm implementing it, I'm inclined towards the first option, especially because it couldn't have been working for people in Xcode anyways if they had duplicate basenames. But I'm curious what people would like.

**Comment by allevato** [comment]
cc @trybka who may have some thoughts on improvements to this script.

**Comment by michaeleisel** [comment]
Another alternative that @keith brought up is to provide some ability to just disable this whole thing and run /usr/bin/libtool directly

**Comment by michaeleisel** [comment]
@trybka ping. i'm happy to rewrite the current rule in c++, as i believe that will solve the performance issues here, if you're fine with that as well

**Comment by trybka** [comment]
The warning isn't spurious: It picks one and omits the other, which is ... problematic.

If you use xcodebuild, then it'll name outputs foo.o, foo0.o, etc. which does avoid the problem.

In Bazel, we had to resort to this ... workaround.

The current functionality (hashing/symlinking) is actually in Python: tools/objc/make_hashed_objlist.py
I have no objection to rewriting it in C++, and I think any of the optimizations you mentioned (detect unique and skip, only rename non-unique, make individual operations faster) are all fine with me.

**Comment by michaeleisel** [comment]
@trybka do we need the hash to be deterministic? bit more work in c++ if we have to add in md5 support

**Comment by michaeleisel** [comment]
@trybka PR opened: https://github.com/bazelbuild/bazel/pull/11958

**Comment by trybka** [comment]
I do believe it needs to be deterministic, otherwise it will invalidate caches.

If archives can be generated which contain bit-for-bit identical object files, but the names differ, that is a problem.

That "different" archive will be detected by Bazel to be a new input, and will cause re-linking to potentially occur, invalidating caches.

**Comment by michaeleisel** [comment]
this is now done, released in 3.5 (with a fix for a regression it introduced in 3.6 rc4). @trybka let's close?

**Comment by keith** [comment]
I don't think it made 3.5? 3.6 is the first release with both I think?

**Comment by michaeleisel** [comment]
ah is that right? (we've been on a fork with both anyways). in any case, this seems resolved

**Comment by trybka** [comment]
I don't think I have any specific bits to close these?

@oquenchil probably does.
