### ISSUE TITLE
Building Bazel fails as included protoc uses wrong libstd++

### ISSUE THREAD

**Issue by Flamefire** [bazelbuild/bazel#11852]
### Description of the problem / feature request:

When trying to build Bazel from source I'm getting to the stage `Building Bazel with Bazel` but then the protoc fails with

```
/tmp/easybuild-tmp/eb-29fXv_/bazel_RHR6AwjE/out/execroot/io_bazel/bazel-out/host/bin/external/com_google_protobuf/protoc: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/easybuild-tmp/eb-29fXv_/bazel_RHR6AwjE/out/execroot/io_bazel/bazel-out/host/bin/external/com_google_protobuf/protoc)
/tmp/easybuild-tmp/eb-29fXv_/bazel_RHR6AwjE/out/execroot/io_bazel/bazel-out/host/bin/external/com_google_protobuf/protoc: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /tmp/easybuild-tmp/eb-29fXv_/bazel_RHR6AwjE/out/execroot/io_bazel/bazel-out/host/bin/external/com_google_protobuf/protoc)
```

### Feature requests: what underlying problem are you trying to solve with this feature?

Building Bazel with a specified Toolchain, i.e. the correct libstdc++.so is in LD_LIBRARY_PATH

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- Install GCC into some path, e.g. /opt/gcc-8.3.0
- Setup environment PATH, LD_LIBRARY_PATH so gcc and libs can be found
- Build Bazel with ./compile.sh

### What operating system are you running Bazel on?

RHEL 7.6

### What's the output of `bazel info release`?

3.4.1

###  Have you found anything relevant by searching the web?

This sounds similar to #11588 but with Bazel itself, and also #8548 and #4510 (about using a non-system compiler)

**Comment by Flamefire** [comment]
I traced this with some printf-debugging into third_party/grpc/bazel/generate_cc.bzl where a `ctx.actions.run` doesn't pass `use_default_shell_env = True,` as all functions from protobuf do.

Adding that fixes the issue.

**Comment by oquenchil** [comment]
Could you please submit a PR?

**Comment by Flamefire** [comment]
Done: #11860
