### ISSUE TITLE
incorrect library order in the final linking command

### ISSUE THREAD

**Issue by zhaopengoog** [bazelbuild/bazel#11859]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

bazel version: bazel 3.3.1- 

Software: https://github.com/abseil/abseil-cpp.git

CC=clang BAZEL_CXXOPTS="-std=c++14:-stdlib=libc++:-isystem${LLVM_HDR}:-isystem${CLANG_HDR}" BAZEL_LINKOPTS="-v:-stdlib=libc++:-L${LLVM_LIB}:-lc++:-lc++abi:-lm:-Wl,-rpath=${LLVM_LIB}" bazel run -c opt --dynamic_mode=off --verbose_failures --sandbox_debug //absl/synchronization:mutex_benchmark

It generates errors like:

sysinfo.o:sysinfo.cc:construction vtable for std::__1::basic_istream<char, std::__1::char_traits<char> >-in-std::__1::basic_ifstream<char, std::__1::char_traits<char> >: error: undefined reference to 'virtual thunk to std::__1::basic_istream<char, std::__1::char_traits<char> >::~basic_istream()'

The final linking command is like below:
"/usr/bin/ld.gold" ...  -lc++ -lc++abi -lm *.o   --start-group -lgcc -lgcc_eh -lpthread -lc --end-group /usr/lib/gcc/aarch64-redhat-linux/8/crtend.o /usr/lib/gcc/aarch64-redhat-linux/8/../../../../lib64/crtn.o

If i move "-lc++ -lc++abi -lm "  after "*.o", the build finishes correctly.

Is there anything that I missed that cause this incorrect library order?

Thanks
### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Software: https://github.com/abseil/abseil-cpp.git

CC=clang BAZEL_CXXOPTS="-std=c++14:-stdlib=libc++:-isystem${LLVM_HDR}:-isystem${CLANG_HDR}" BAZEL_LINKOPTS="-v:-stdlib=libc++:-L${LLVM_LIB}:-lc++:-lc++abi:-lm:-Wl,-rpath=${LLVM_LIB}" bazel run -c opt --dynamic_mode=off --verbose_failures --sandbox_debug //absl/synchronization:mutex_benchmark
### What operating system are you running Bazel on?

Centos

### What's the output of `bazel info release`?

release 3.3.1- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

https://docs.bazel.build/install.html

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

I downloaded bazel-3.3.1-dist.zip

###  Have you found anything relevant by searching the web?

maybe this one? I am not sure it is the same issue. But it looks similar in the nature?
https://github.com/bazelbuild/bazel/issues/9254

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by oquenchil** [comment]
Try with --incompatible_linkopts_to_linklibs which should be flipped by 4.0.
