### ISSUE TITLE
Bazel does not refresh updated OAuth token

### ISSUE THREAD

**Issue by MikhailTymchukFT** [bazelbuild/bazel#11854]
### Description of the problem / feature request:

We use Google bucket as a remote cache for our MacOS builds. It worked for several weeks, but now all developers see that message in console:
```
[0 / 3] [Prepa] BazelWorkspaceStatusAction stable-status.txt
WARNING: Reading from Remote Cache:
400 Bad Request
{
  "error": "invalid_grant",
  "error_description": "reauth related error (invalid_rapt)",
  "error_subtype": "invalid_rapt"
}
```

Re-authenticating with `gcloud auth application-default login` and `gcloud auth login` does not help.

After removing GCloud permission from https://myaccount.google.com/permissions for Google Auth Library and Google Cloud SDK and re-authentication with `gcloud auth application-default login` and `gcloud auth login` bazel gives another error:

```
WARNING: Writing to Remote Cache:
400 Bad Request
{
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."
}
```

We are able to access the bucket freely with Google Cloud Console.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

* Setup a remote cache at GCS
* Setup your .bazelrc:
```
build --remote_http_cache=https://storage.googleapis.com/your-cache-name
build --google_default_credentials
```
* `$ gcloud auth login`
* `$ gcloud auth application-default login`
* Wait for refresh token to expire
* Perform bazel build
* Get `reauth related error (invalid_rapt)` error
* Remove `Google Auth Library` and `Google Cloud SDK` permissions from https://myaccount.google.com/permissions
* Re-authenticate with `$ gcloud auth login` and `$ gcloud auth application-default login`. Tokens are recreated as https://myaccount.google.com/permissions indicates.
* Perform bazel build
*  Get `Token has been expired or revoked.` error

### What operating system are you running Bazel on?

MacOS

### What's the output of `bazel info release`?

release 2.1.1

###  Have you found anything relevant by searching the web?

An article with a nice description of a client behavior: https://jpassing.com/2019/11/11/2019-11-23-impact-of-gcp-session-length-on-oauth-clients/
Looks like bazel should reinitiate an OAuth authorization flow, but it's not.

**Comment by MikhailTymchukFT** [comment]
The issue magically disappeared after several hours before I checked it with the latest version of Bazel.
I close the issue until I get more info.

**Comment by gkousik** [comment]
I just ran into this. I think Bazel is caching the Oauth2 token received from `gcloud auth application-default login`. Another quick workaround instead of waiting for several hours is to just restart the Bazel server process.

**Comment by RomanVlasenko** [comment]
The issue is still there. As suggested by @gkousik - killing the bazel process helps to make it work.
