### ISSUE TITLE
document that repository_ctx.template requires text files

### ISSUE THREAD

**Issue by guibou** [bazelbuild/bazel#11857]
### Description of the problem / feature request:

`repository_ctx.template` seems to corrupt binaries files. For example:

```
repository_ctx.template(outPath, binaryFilePath)
```

Will results in a corrupted file in `outPath`. Tested with `sha256sum`.

### Feature requests: what underlying problem are you trying to solve with this feature?

Using `repository_ctx.template` as a way to copy file. I do realize that it is an abuse of the API, but there is no `repository_ctx.copy`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

```
release 3.2.0- (@non-git)
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

nixpkgs

###  Have you found anything relevant by searching the web?

no.

**Comment by alandonovan** [comment]
As I commented at https://github.com/bazelbuild/bazel/issues/11858#issuecomment-686480642, yes, `template` will indeed not work for binary files. Strings, in the Java implementation of Starlark used by Bazel, are intended to be strings of UTF-16 codes (chars), like strings in Java, and are thus incapable of representing binary files. A copy function seems like a better approach.
