### ISSUE TITLE
git_repository redownloads the repository when flags change

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#11864]
Changing the flags passed to Bazel can force the reevaluation of the WORKSPACE. This is expected, but Bazel can spend a lot of time redownloading git repositories.

When I run `bazelisk --migrate test ...` in Stardoc, the command takes 15 minutes. Almost all the time is spent fetching and refetching git repositories.

Small repro:

WORKSPACE:
```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "io_bazel",
    commit = "b2b9fa00d7d168e9553cfc9fe381928e8e246176",  # 2020-07-28
    remote = "https://github.com/bazelbuild/bazel.git",
    shallow_since = "1595950714 -0700",
)
```

BUILD:
```
load("@io_bazel//:distdir.bzl", "distdir_tar")
```

Example commands to run:

```
$ bazel build ...
$ bazel build ... --record_rule_instantiation_callstack
$ bazel build ... --record_rule_instantiation_callstack --incompatible_restrict_string_escapes
```

Most of the incompatible flags force a redownload. Each of the command spends around one minute downloading io_bazel, according to the console output:

```
     Fetching @io_bazel; Cloning b2b9fa00d7d168e9553cfc9fe381928e8e246176 of https://github.com/bazelbuild/bazel.git 58s
```

**Comment by benjaminp** [comment]
older issue: #10961

**Comment by aiuto** [comment]
Copied text into #10961
