### ISSUE TITLE
bazel build for a Java workspace fails every other time when using annotation processors

### ISSUE THREAD

**Issue by friendly-pineapple** [bazelbuild/bazel#11861]
### Description of the problem / feature request:
Aloha!

`bazel build` for a Java workspace fails _every other time_ when using annotation processors.

Here is a minimal example:

**./WORKSPACE**
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JVM_EXTERNAL_TAG = "3.3"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")
load("@rules_jvm_external//:specs.bzl", "maven")

maven_install(
    artifacts = [
        maven.artifact("org.immutables", "value", "2.8.8"),
    ],
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
```

**./BUILD**
```
load("@rules_java//java:defs.bzl", "java_library", "java_plugin")

java_library(
    name = "bar",
    srcs = glob(["**/*.java"]),
    deps = [
        ":immutables_processor",
        "@maven//:org_immutables_value",
    ],
)

java_plugin(
    name = "immutables_processor",
    generates_api = True,
    processor_class = "org.immutables.processor.ProxyProcessor",
    deps = [
        "@maven//:org_immutables_value",
    ],
)
```

**./src/main/java/com/foo/Bar.java**
```
package com.foo;

import org.immutables.value.Value.Immutable;

@Immutable
public abstract class Bar {
  public abstract int value();
}
```

Running `bazel clean --expunge`, then `bazel build //...`, succeeds the very first time:

```
INFO: Analyzed 2 targets (1 packages loaded, 3 targets configured).
INFO: Found 2 targets...
INFO: Elapsed time: 0.379s, Critical Path: 0.27s
INFO: 1 process: 1 worker.
INFO: Build completed successfully, 2 total actions
```

However, the next time `bazel build //...` is run, we see the error:

```
INFO: Analyzed 2 targets (1 packages loaded, 5 targets configured).
INFO: Found 2 targets...
ERROR: /Users/friendly-pineapple/code/example/BUILD:3:1: Building libbar.jar (3 source files) and running annotation processors (ProxyProcessor) failed (Exit 1)
error: error reading bazel-bin/_javac/bar/libbar_sourcegenfiles/com/foo/ImmutableBar.java; /private/var/tmp/_bazel_friendly_pineapple/7ce7b18ca916b3bdbe00ac75920077d2/execroot/__main__/bazel-bin/_javac/bar/libbar_sourcegenfiles/com/foo/ImmutableBar.java
error: error reading bazel-out/darwin-fastbuild/bin/_javac/bar/libbar_sourcegenfiles/com/foo/ImmutableBar.java; /private/var/tmp/_bazel_friendly_pineapple/7ce7b18ca916b3bdbe00ac75920077d2/execroot/__main__/bazel-out/darwin-fastbuild/bin/_javac/bar/libbar_sourcegenfiles/com/foo/ImmutableBar.java
INFO: Elapsed time: 0.143s, Critical Path: 0.02s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

This continues, where every other `bazel build //...` invocation succeeds. This seems very strange!!

This is only alleviated if we place the `BUILD` file away from the root directory of the workspace, i.e. at `./src/main/java/com/foo/BUILD` instead.

### What operating system are you running Bazel on?

macOS Catalina 10.15.4 (19E287)

### What's the output of `bazel info release`?

```
>_ bazel info release
release 3.0.0
```

###  Have you found anything relevant by searching the web?

We haven't seen anything else related to this issue. We are curious if this points towards other possible bugs, perhaps in `java_plugin`?

**Comment by lberki** [comment]
"every other time" is weird.

**Comment by comius** [comment]
The first time (and even times) it is run `bar` is compile actions has parameters:
```
--processors
org.immutables.processor.ProxyProcessor
--sources
src/main/java/com/foo/Bar.java
```
and it works.


Second  time (and odd times) `bar` compile action has parameters:
```
--processors
org.immutables.processor.ProxyProcessor
--sources
bazel-bin/_javac/bar/libbar_sourcegenfiles/com/foo/ImmutableBar.java
bazel-out/k8-fastbuild/bin/_javac/bar/libbar_sourcegenfiles/com/foo/ImmutableBar.java
src/main/java/com/foo/Bar.java
```
and it fails.

**Comment by comius** [comment]
possibly related to https://github.com/bazelbuild/bazel/issues/11992

**Comment by cushon** [comment]
When the build succeeds, it generates sources to a temp directory in the output tree: `bazel-bin/_javac/bar/libbar_sourcegenfiles/com/foo/ImmutableBar.java`, `bazel-out/k8-fastbuild/bin/_javac/bar/libbar_sourcegenfiles/com/foo/ImmutableBar.java`.

The `BUILD` file at the workspace root has a `java_library` with `srcs = glob(["**/*.java"])`, which is globbing all files in the workspace *including the temporary generated sources in the output tree*.

The compilation starts by cleaning up the temp directory it writes generated sources to, which means that by the time it tries to compile those files on the second compilation they aren't there, so it fails. Because it cleaned up the temp directory, the next compilation doesn't see those sources and succeeds, and so on.

The underlying problem here seems like the fact that `srcs = glob(["**/*.java"])` in the workspace root traverses into `bazel-bin/`. Bazel folks, is that expected behaviour?

**Comment by comius** [comment]
> The underlying problem here seems like the fact that srcs = glob(["**/*.java"]) in the workspace root traverses into bazel-bin/. Bazel folks, is that expected behaviour?

This is a rather unusual edge case, that should be covered, but I wouldn't say it is a priority.

Thanks @cushon for investigating!
