### ISSUE TITLE
Truncated json trace profile

### ISSUE THREAD

**Issue by kastiglione** [bazelbuild/bazel#11863]
### Description of the problem / feature request:

Infrequently our bazel builds will produce a truncated json trace profile.

A json trace profile is generated when using `--experimental_generate_json_trace_profile` and `--profile=path/to/trace.json`.

From looking at a recent failure, it could be that the json file is not being "finalized".

The first line of the file is:

```
{"otherData":{"build_id":"<...>","output_base":"<...>","date":"<...>"},"traceEvents":[
```

This opens the `traceEvents` array. After this there are many trace events, each a single line, each a single json object.

The last line of the file is:

```
{"cat":"general information","name":"Finishing","ph":"i","ts":183949649,"pid":1,"tid":20}
```

Which looks like the final event of the trace. After this, the json appears to be missing a closing `]`, followed by a closing `}`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

This happens irregularly, we currently don't know of a way to deterministically reproduce the issue.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 3.4.1

###  Have you found anything relevant by searching the web?

We thought we had filed this before, as it's not a recent problem, but couldn't find anything related.

**Comment by larsrc-google** [comment]
You say "looking at a recent failure", do you mean failure to write the JSON trace or a failed compile? 

Have you had this happen when compiling something open-source? Does it seem to depend on what you're compiling? Roughly how often does it happen? Is it always just the last closing braces, or is it more random what's missing?

**Comment by ulfjack** [comment]
The documentation of the trace format (https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/edit) specifically allows a missing closing bracket, as it is not always possible to guarantee that the file is written properly (e.g. when the binary is killed by the system for some reason). That said, if the runs end normally, Bazel should be writing the closing bracket.

**Comment by meisterT** [comment]
Dave, let me close this issue since we currently have no way to repro and the missing closing bracket is ok per format spec.
