### ISSUE TITLE
Module maps don't seem to work for objc_library

### ISSUE THREAD

**Issue by michaeleisel** [bazelbuild/bazel#11877]
I have two objc_library targets, "Aa" and "Bb", each with `enable_modules = True`. Bb depends on Aa. When I add `@import Aa;` to a .m file in Bb, it tells me it can't find the module 'Aa'. I don't see the `-fmodule-map-file=...` flag getting added to Bb invocations like I see for swift_library (`import Aa` works fine for a swift_library rule depending on Aa). Any ideas what might be the issue?

### What operating system are you running Bazel on?

OS X 10.15

### What's the output of `bazel info release`?

release 3.4.0

###  Have you found anything relevant by searching the web?

I have not

### Any other information, logs, or outputs that you want to share?

a/BUILD.bazel:
```
objc_library(
    name = "Aa",
    module_name = "Aa",
    srcs = ["a.m"],
    hdrs = ["a.h"],
    enable_modules = True,
    visibility = ["//visibility:public"],
)
```
b/BUILD.bazel:
```
objc_library(
    name = "Bb",
    module_name = "Bb",
    enable_modules = True,
    srcs = ["b.m"],
    hdrs = ["b.h"],
    deps = ["//a:Aa"],
)
```
Where b/b.h consists of `@import Aa;`, running `bazel build //b:Bb` gives an error that the module is missing

**Comment by thii** [comment]
`enable_modules` doesn't work with user-provided modules, it only works with system modules like Foundation.

We have a drop-in replacement rule for `objc_library` that adds support for it: https://github.com/line/rules_apple_line/blob/master/docs/README.md#objc_library.

**Comment by michaeleisel** [comment]
got it, thanks for the info
