### ISSUE TITLE
FAILED: Build did NOT complete successfully on windows 

### ISSUE THREAD

**Issue by muhdmud** [bazelbuild/bazel#11881]
### Description of the problem / feature request:

FAILED: Build did NOT complete successfully

### Feature requests: what underlying problem are you trying to solve with this feature?

was trying to build verible 
https://github.com/google/verible

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

runnning bazel build -c opt //... 
following the build guide

### What operating system are you running Bazel on?

Version	10.0.19041 Build 19041
windows 10 home

### What's the output of `bazel info release`?

release 3.4.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N.A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git@github.com:muhdmud/verible.git
d811cea2c593985cabbd043d338daa4a8ed08493

###  Have you found anything relevant by searching the web?

could not find something specific to this error

### Any other information, logs, or outputs that you want to share?

C:\openSource\verible>bazel build -c opt //...
Starting local Bazel server and connecting to it...
INFO: Analyzed 1238 targets (75 packages loaded, 5976 targets configured).
INFO: Found 1238 targets...
ERROR: C:/opensource/verible/bazel/BUILD:20:15: error executing shell command: 'C:/Users/muhd/scoop/apps/msys2/current/usr/bin/bash.exe -c function cleanup_function() {
local ecode=$?
if [ $ecode -eq 0 ]; then
cleanup_on_success
else
cleanup_on_failure
fi
}
set -e
function cle...' failed (Exit -1). Note: Remote connection/protocol failed with: execution failed
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\Users\muhd\scoop\apps\msys2\current\usr\bin\bash.exe" -c "function cleanup_function() {
local ecode=$?
if [ $ecode -eq 0 ]; then
cleanup_on_success
else
cleanup_on_failure
fi
}
set -e
function cleanup_on_success() {
printf \"rules_foreign_cc: Cleaning temp directories\"
  rm -rf $BUILD_TMPDIR $EXT_BUILD_DEPS
}
function cleanup_on_failure() {
printf \"\nrules_foreign_cc: Build failed!\nrules_foreign_cc: Keeping temp build directory $BUILD_TMPDIR and dependencies directory $EXT_BUILD_DEPS(...)): The system cannot find the file specified.
 (error: 2)
INFO: Elapsed time: 26.653s, Critical Path: 4.58s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

C:\openSource\verible>g++ --version
g++ (MinGW.org GCC-8.2.0-3) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by fangism** [comment]
Ping.  Anyone able to help?

**Comment by aiuto** [comment]
I think the place to ask for help is in the verible project.

**Comment by fangism** [comment]
None of us in the Verible project have any experience building on Windows.

**Comment by jin** [comment]
I don't think rules_foreign_cc is supported on Windows. If Verible uses rules_foreign_cc transitively, then it can't be used on Windows until r_f_c supports it. 

Please file a bug against https://github.com/bazelbuild/rules_foreign_cc.
