### ISSUE TITLE
bazel test ignores --output_base

### ISSUE THREAD

**Issue by kevyang** [bazelbuild/bazel#11882]
### Description of the problem / feature request:

> The --output_base option appears to be ignored when running bazel test rather than bazel build

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> We are building the Envoy proxy project (https://github.com/envoyproxy/envoy) which uses Bazel. Running bazel --output_base=X build behaves as expected, but when we run bazel --output_base=X test, the output_base argument seems to be ignored and the output base defaults back to ~/.cache/bazel/_bazel_$USER/. 

### What operating system are you running Bazel on?

> Centos 7 within Docker

### What's the output of `bazel info release`?

> release 2.2.0

###  Have you found anything relevant by searching the web?

> I looked through other Github issues, StackOverflow, and the Google group and I was not able to locate anything that seemed relevant, though perhaps I missed something.

**Comment by meisterT** [comment]
I can't repro this behavior. Can you please elaborate how you determined that this is the case?

**Comment by kevyang** [comment]
I removed the ~/.cache/bazel directory and then ran a bazel --output_base=X test on our project. When it was finished running, the directory had been re-created and there were cached objects inside of it. Doing a bazel --output_base=X build seems to work appropriately but when I run test it defaults to that location.

**Comment by meisterT** [comment]
Can you please try the following steps:
1. `output_base=$(bazel info output_base)`
2. `echo "$output_base"`
3. `ls -al "$output_base"`
4. `bazel clean --expunge`
5. `bazel --output_base=/tmp/ob test //path/to/test:target`
6. `ls -al "$output_base"`
7. `ls -al /tmp/ob`

Replace the target in step 5 with your target. I do get "No such file or directory" in step 6 while in step 7 I see the output base as expected.

**Comment by kevyang** [comment]
I am actually running into a few problems running `bazel clean --expunge` as well; each time I run it (even from a new, clean docker container) it seems to wait for the server process to terminate, which it never does:
```# ~/bin/bazel clean --expunge
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
WARNING: Waiting for server process to terminate (waited 10 seconds, waiting at most 60)
WARNING: Waiting for server process to terminate (waited 30 seconds, waiting at most 60)
INFO: Waited 60 seconds for server process (pid=62) to terminate.
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 10)
WARNING: Waiting for server process to terminate (waited 10 seconds, waiting at most 10)
INFO: Waited 10 seconds for server process (pid=62) to terminate.
FATAL: Attempted to kill stale server process (pid=62) using SIGKILL, but it did not die in a timely fashion.
```
and if I issue an interrupt signal while this is happening, it segfaults:
```
# ~/bin/bazel clean --expunge
Starting local Bazel server and connecting to it...
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
^C
Bazel caught interrupt signal; shutting down.

Segmentation fault
```

Anyway, attempting to work around this:
```
# output_base=$(~/bin/bazel info output_base)
Starting local Bazel server and connecting to it...
# echo "$output_base"
/root/.cache/bazel/_bazel_root/f800b6f63033dee99a695ce807f708ab
# ls -al "$output_base"
total 56
drwxr-xr-x 4 root root  4096 Aug  3 19:23 .
drwxr-xr-x 5 root root  4096 Aug  3 19:23 ..
-rw-r--r-- 1 root root    33 Aug  3 19:23 DO_NOT_BUILD_HERE
-rw-r--r-- 1 root root   787 Aug  3 19:23 README
-rw-r--r-- 1 root root    64 Aug  3 19:23 command.log
drwxr-xr-x 2 root root  4096 Aug  3 19:23 execroot
lrwxrwxrwx 1 root root    71 Aug  3 19:23 install -> /root/.cache/bazel/_bazel_root/install/a968348e0a72afc534c7baff88ca46f1
lrwxrwxrwx 1 root root    57 Aug  3 19:23 java.log -> java.log.685f6b3a167b.root.log.java.20200803-192322.25929
-rw-r--r-- 1 root root 16031 Aug  3 19:23 java.log.685f6b3a167b.root.log.java.20200803-192322.25929
-rw-r--r-- 1 root root   524 Aug  3 19:23 javalog.properties
-rw-r--r-- 1 root root    76 Aug  3 19:23 lock
drwx------ 2 root root  4096 Aug  3 19:23 server
```
I skipped step 4 and instead rebuilt my container to have a clean bazel output_base. After doing this, we have:
```
# echo $output_base
/root/.cache/bazel/_bazel_root/f800b6f63033dee99a695ce807f708ab
# ls -al "$output_base"
total 56
drwxr-xr-x 4 root root  4096 Aug  3 21:33 .
drwxr-xr-x 5 root root  4096 Aug  3 21:33 ..
-rw-r--r-- 1 root root    33 Aug  3 21:33 DO_NOT_BUILD_HERE
-rw-r--r-- 1 root root   787 Aug  3 21:33 README
-rw-r--r-- 1 root root    64 Aug  3 21:33 command.log
drwxr-xr-x 2 root root  4096 Aug  3 21:33 execroot
lrwxrwxrwx 1 root root    71 Aug  3 21:33 install -> /root/.cache/bazel/_bazel_root/install/a968348e0a72afc534c7baff88ca46f1
lrwxrwxrwx 1 root root    57 Aug  3 21:33 java.log -> java.log.948caba3ec24.root.log.java.20200803-213329.18397
-rw-r--r-- 1 root root 16031 Aug  3 21:33 java.log.948caba3ec24.root.log.java.20200803-213329.18397
-rw-r--r-- 1 root root   524 Aug  3 21:33 javalog.properties
-rw-r--r-- 1 root root    76 Aug  3 21:33 lock
drwx------ 2 root root  4096 Aug  3 21:33 server
# ls -al /tmp/ob
total 3296
drwxr-xr-x  8 root root    4096 Aug  3 20:14 .
drwxrwxrwt  1 root root    4096 Aug  3 21:26 ..
-rw-r--r--  1 root root      33 Aug  3 20:12 DO_NOT_BUILD_HERE
-rw-r--r--  1 root root     787 Aug  3 20:12 README
drwxr-xr-x  2 root root    4096 Aug  3 21:26 action_cache
drwxr-xr-x  2 root root    4096 Aug  3 20:12 bazel-workers
-rw-r--r--  1 root root 2941663 Aug  3 21:26 command.log
-rw-r--r--  1 root root  304260 Aug  3 21:26 command.profile.gz
drwxr-xr-x  3 root root    4096 Aug  3 20:14 execroot
drwxr-xr-x 60 root root    4096 Aug  3 20:14 external
lrwxrwxrwx  1 root root      71 Aug  3 20:12 install -> /root/.cache/bazel/_bazel_root/install/a968348e0a72afc534c7baff88ca46f1
lrwxrwxrwx  1 root root      55 Aug  3 20:12 java.log -> java.log.948caba3ec24.root.log.java.20200803-201240.168
-rw-r--r--  1 root root   60811 Aug  3 21:26 java.log.948caba3ec24.root.log.java.20200803-201240.168
-rw-r--r--  1 root root     468 Aug  3 20:12 javalog.properties
-rw-r--r--  1 root root      74 Aug  3 20:12 lock
drwxr-xr-x  3 root root    4096 Aug  3 20:14 sandbox
drwx------  2 root root    4096 Aug  3 20:12 server
```

**Comment by meisterT** [comment]
Can you share which docker container exactly you are using and which command you run in step 5?

**Comment by kevyang** [comment]
Unfortunately I'm not sure I can share the container since the image contains some proprietary stuff in it. The command I run in step 5 is 
```
~/bin/bazel --output_base=/tmp/ob test //test/...:*
```
This step runs successfully, though the output base seems to be the default.

**Comment by philwo** [comment]
We can't repro this and Bazel 2.2.0 is an old version that we can't support. Please report back if you can repro this with the latest Bazel version.
