### ISSUE TITLE
extra_action doesn't document the proto it uses.

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#1188]
http://bazel.io/docs/be/extra-actions.html#extra_action

The extra_actions run as a command-line. The command-line tool gets access to a file containing a protocol buffer as $(EXTRA_ACTION_FILE) with detailed information on the original action it is shadowing. It also has access to all the input files the original action has access to.

I believe this is the proto:
https://github.com/bazelbuild/bazel/blob/master/src/main/protobuf/extra_actions_base.proto

**Comment by damienmg** [comment]
What???

**Comment by damienmg** [comment]
Oops sorry wasn't mean to go on the bug.

**Comment by helenalt** [comment]
Putting into documentation backlog

**Comment by keertk** [comment]
Hi there! Looks like the [documentation](https://github.com/bazelbuild/bazel/blob/master/src/main/protobuf/extra_actions_base.proto) has been updated and now includes this information.
