### ISSUE TITLE
Move Remote execution services section out of versioned docs

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#11883]
See:  https://docs.bazel.build/versions/3.4.0/remote-execution.html

This talks about the vague concept and lists commercial offerings. That is permanent information rather than documentation, and should move to bazel-website.

**Comment by communikit** [comment]
I can send in a PR moving it over - do you have any feelings about where exactly this should live? Perhaps under "Bazel internals"?

**Comment by aiuto** [comment]
It is not internals.  This is a listing of vendors, so it is a sibling in concept to the Bazel Experts page.
The "External resources" section of the sidebar is the most logical place for the link to the listing

It's not a direct "move". It is more of a split of https://docs.bazel.build/versions/3.4.0/remote-execution.html

The page title, description and requirements should stay in the versioned docs. The only part that should move to bazel.build is most of the "Remote execution services" part of that page.   It should be just git the general idea of


Remote execution services
There are several commercially supported remote execution services as well as self-service tools. You can find a current list at. <LINK TO NEW PAGE>

**Comment by communikit** [comment]
Ah, I see - I initially read this as wanting the entire remote-execution.md page moved.
