### ISSUE TITLE
Improve command line option documentation

### ISSUE THREAD

**Issue by oehme** [bazelbuild/bazel#11886]
### Description of the problem / feature request:

As a newcomer, trying to get an overview of Bazel's command line options, I ran into several issues with the current documentation structure.

#### Duplication
There are two chapters listing command line options:

1. https://docs.bazel.build/versions/master/user-manual.html and
2. https://docs.bazel.build/versions/master/command-line-reference.html

The user manual is very long, but still incomplete, missing some options that the reference contains. On the other hand, the reference has shorter descriptions. If I come from a Google search and end up in the reference, I might think this is all the information there is about this option, not realising there is the manual that might have more info on the same option. I think there should only be one list, ideally auto-generated from the source code so it is always in sync with the implementation. The user manual could then be shortened to highlight just the most important ones, linking to their description in the reference. That way, important sections like "Using Bazel for releases" would stand out more.

Edit: Also, the reference contains some options twice. E.g. search for `--execution_log_json_file`  and you'll see it listed twice under `Build Options`

#### Unclear status of incompatible/experimental options

There are many options called `incompatible_XXX` that do not have the `incompatible_change` metadata tag. Are they incompatible or not? Similarly, there are many options called `experimental_XXX` that don't have the `experimental` metadata tag. Are they experimental or not? This is very confusing to a newcomer.

#### False or misleading information

The [json trace file option](https://docs.bazel.build/versions/master/command-line-reference.html#flag--experimental_generate_json_trace_profile) is marked as `default: "false"`, which is not true. Running the latest Bazel version on a "hello world" project, a json trace is always created. Maybe this option is simply ignored now, in which case it should probably be marked as `deprecated` instead.

**Comment by jin** [comment]
cc @floriographygoth (should we create a team-Docs as a standalone team?)

**Comment by laurentlb** [comment]
Thanks for the feedback, we recently discussed this problem.

Some flags are available to multiple commands (e.g. `build` and `query`). I think these flags will show up multiple times in the documentation.

Maybe it would be better to list all flags for all commands, in alphabetical order, and have a way to filter the list (per command, maybe by tag too)?

> The user manual could then be shortened to highlight just the most important ones

Shall we add a tag "important" for those flags?

**Comment by communikit** [comment]
We are tracking improving this documentation internally as well, we will keep it in mind as we plan out our work for the future.
