### ISSUE TITLE
CppCompileAction does not fill Starlark argv

### ISSUE THREAD

**Issue by getim** [bazelbuild/bazel#11892]
### Description of the problem / feature request:

When using an aspect on a cc_library rule, the [argv attribute](https://docs.bazel.build/versions/master/skylark/lib/Action.html#argv) of actions accessed through target.actions with mnemonic CppCompile is None.

### Feature requests: what underlying problem are you trying to solve with this feature?

Access the full command line used for cpp compilation actions.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Add following snippet to the aspect implementation in one of the [aspects examples](https://docs.bazel.build/versions/master/skylark/aspects.html#advanced-example)
```
for action in target.actions:
    if action.mnemonic == 'CppCompile':
        print(action.argv)
```
This prints "None".

### What operating system are you running Bazel on?

Centos 7

### What's the output of `bazel info release`?

release 3.4.1

###  Have you found anything relevant by searching the web?

From comparing [CppLinkAction](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/cpp/CppLinkAction.java) and [CppCompileAction](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/cpp/CppCompileAction.java), it looks like `getStarlarkArgv` is just missing from CppCompileAction. All other requirements seem to be there. I copied that function from CppLinkAction to CppCompileAction and argv is now filled properly.

**Comment by shahms** [comment]
Note that the C++ rules make the command line arguments available via `action.args` (rather than `action.argv`): https://github.com/bazelbuild/bazel/blob/39bc97eab295bddb35b38bfc4a2ff3d2b15d034e/src/main/java/com/google/devtools/build/lib/starlarkbuildapi/ActionApi.java#L74

**Comment by getim** [comment]
Ok, thanks. In the end I don't need that info at analysis time for my use case so `action.args` should do it.

This still feels like something that can be aligned pretty easily though.
