### ISSUE TITLE
Failed to detect HOST OS - my OS is POP OS 20.04

### ISSUE THREAD

**Issue by jm9151821** [bazelbuild/bazel#11890]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:
INFO: Repository llvm_toolchain instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule llvm_toolchain defined at:
  /home/lukeskywalker/.cache/bazel/_bazel_lukeskywalker/c4d809ae0a83e6edfe2bff1941c9200b/external/com_grail_bazel_toolchain/toolchain/rules.bzl:24:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
   Traceback (most recent call last):
File "/home/lukeskywalker/.cache/bazel/_bazel_lukeskywalker/c4d809ae0a83e6edfe2bff1941c9200b/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 102
_download_llvm_preconfigured(<1 more arguments>)
File "/home/lukeskywalker/.cache/bazel/_bazel_lukeskywalker/c4d809ae0a83e6edfe2bff1941c9200b/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 120, in _download_llvm_preconfigured
fail(<1 more arguments>)
Failed to detect host OS version:

Unsupported linux distribution and version: pop, 20.04
ERROR: no such package '@llvm_toolchain//': Traceback (most recent call last):
File "/home/lukeskywalker/.cache/bazel/_bazel_lukeskywalker/c4d809ae0a83e6edfe2bff1941c9200b/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 102
_download_llvm_preconfigured(<1 more arguments>)
File "/home/lukeskywalker/.cache/bazel/_bazel_lukeskywalker/c4d809ae0a83e6edfe2bff1941c9200b/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 120, in _download_llvm_preconfigured
fail(<1 more arguments>)
Failed to detect host OS version:

Unsupported linux distribution and version: pop, 20.04

> It is failing to detect my ubuntu version, but why?

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Trying to build an ETH 2 Node setup I'm using ubuntu pop and I attempted to run this command  bazel build //beacon-chain:beacon-chain

from step 5 in this guide https://medium.com/@SomerEsat/guide-to-staking-on-ethereum-2-0-ubuntu-medalla-prysm-4d2a86cc637b

### What operating system are you running Bazel on?

> POP OS 20.04

### What's the output of `bazel info release`?

> release 3.2.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
https://github.com/prysmaticlabs/prysm

###  Have you found anything relevant by searching the web?

Nope,  a guy who asked a similar question got -1 on Stack over flow https://stackoverflow.com/questions/63089461/an-error-occurred-during-the-fetch-of-repository-maven
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> this is probably my first or second issue post ever.

> If the files are large, upload as attachment or provide link.

**Comment by aiuto** [comment]
There really is not much to go on here. Since we do not have the ability to test on POP OS, this may be a "working as intended" incompatibility.  Are you able to build prysm on one of the supported platforms?

**Comment by yesudeep** [comment]
Pop!_OS is basically Ubuntu 20.04 with some tweaks/packages added on.

**Comment by aiuto** [comment]
I looked at the repo instructions. They are far too complex and invasive to follow. The parts about
running an Ethereum server makes it basically a non-starter for us.

**Comment by jin** [comment]
The error is from `external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl`. Please file an issue against https://github.com/grailbio/bazel-toolchain instead.
