### ISSUE TITLE
Client cannot kill out-of-date servers on Windows

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#1189]
The reason is that it uses `kill()`, which only works for msys2 processes, which the server isn't, because it's Java. 

The solution will probably be to use Win32 APIs to terminate the server instead. Since we want to move away from msys2 anyway, this seems to be a wise choice.

**Comment by dslomov** [comment]
Blocking #1455

**Comment by dslomov** [comment]
This is fixed, right @lberki ?

**Comment by lberki** [comment]
Yep, forgot to close.
