### ISSUE TITLE
--jvmopt does not work for Java binaries in host configuration

### ISSUE THREAD

**Issue by Ubehebe** [bazelbuild/bazel#11893]
### Description of the problem / feature request:
This issue is related to, but more narrowly scoped than, https://github.com/bazelbuild/bazel/issues/6364.

The --jvmopt flag is [documented](https://docs.bazel.build/versions/3.4.0/command-line-reference.html#flag--jvmopt) to add to the "VM startup options of each java_binary target." But this seems to only be the case for Java binaries in target configuration. Java binaries that are used as build tools (e.g., used as a tool input to a genrule, or in Starlark attributes with `cfg = "host"`) don't receive the custom flags.

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm trying to use Java 14 preview features (records, etc.) in my codebase. This requires calling both javac and java with the `--enable-preview` flag, to allow preview features at the Java language and class file levels respectively.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Although my use case involves Java 14, the fundamental issue isn't about Java versions. Here's a minimal repro case involving a custom JVM flag.

```java
package scratch;

class PrintCustomJvmFlag {
  public static void main(String[] args) {
    System.out.printf("-Dfoo=%s%n", System.getProperty("foo"));
  }
}

```

```starlark
java_binary(
    name = "PrintCustomJvmFlag",
    srcs = ["PrintCustomJvmFlag.java"],
    main_class = "scratch.PrintCustomJvmFlag",
)

genrule(
    name = "use_java_binary_in_host_cfg",
    outs = ["prop.txt"],
    tools = [":PrintCustomJvmFlag"],
    cmd = "$(location :PrintCustomJvmFlag) > $(@)",
)
```

```bash
$ bazel run scratch:PrintCustomJvmFlag
-Dfoo=null # expected
$ bazel run scratch:PrintCustomJvmFlag --jvmopt -Dfoo=bar
-Dfoo=bar # expected
$ bazel build scratch:use_java_binary_in_host_cfg; cat bazel-bin/scratch/prop.txt
-Dfoo=null # expected
$ bazel build scratch:use_java_binary_in_host_cfg --jvmopt -Dfoo=bar; cat bazel-bin/scratch/prop.txt
-Dfoo=null # unexpected?
```

Other Bazel command-line flags related to Java come in host/target pairs, e.g. `--host_java_toolchain`/`--java_toolchain`, `--host_javabase`/`--javabase`. The fact that `--jvmopt` doesn't have a corresponding `--host_jvmopt` seems significant.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 3.4.1

###  Have you found anything relevant by searching the web?

Nope.

**Comment by lberki** [comment]
@katre , what do you think? It looks like it's a bad idea to add a `--host_jvmopts` command line option because then we'd eventually have to duplicate every configuration flag.

**Comment by katre** [comment]
Yes, that's the problem with host flags.

Currently, we're ignoring the value of `--javaopts` in [JavaOptions.getHost](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/java/JavaOptions.java;l=677;bpv=1;bpt=1?ss=bazel&q=JavaOptions), in favor of just setting them to `-XX:ErrorFile=/dev/stderr`. Does that still make sense? Should we be copying the javaopts from the previous flag to the host/exec configs?

**Comment by lberki** [comment]
You could ask the same question about almost every single language-specific configuration flag. 

I don't know whether that value in particular makes sense, but what I do know is that it comes from 2009 February (b/1632370 for the initiated), so I have my doubts. What's "the previous flag?"

**Comment by katre** [comment]
By "the previous flag" I meant "the value of `--javaopts` from the command line".

**Comment by lberki** [comment]
I think the current approach of the host flag being independent from the target flag is good for `--jvmopt` in particular. But then we'd either need a `--host_jvmopt` or some other way of saying "the value of this flag should be that in on the exec platform".

In the short term, adding yet another `--host_*` flag is reasonable, but it would be nice not to have to duplicate everything in the long term.
