### ISSUE TITLE
Add informative attributes to repository rules

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/bazel#11891]
### Description of the feature request:

Add informative attributes like version/last-update-date to repository rules

### Feature requests: what underlying problem are you trying to solve with this feature?

We are writing an automation tool to find outdated dependencies, which queries `//external:all` to find all the external repository rules, then analyzes the URLs (which is the only information that can be used for the work) to figure out if a new version is available.

It would be nice to have some additional informative attributes on those rules to simplify the implementation of such tools.

### What operating system are you running Bazel on?

macOS 10.15.6

### What's the output of `bazel info release`?

release 3.4.1-homebrew

**Comment by fmeum** [comment]
@meteorcloudy This will probably be superseded by modquery, right?

**Comment by meteorcloudy** [comment]
Yes
