### ISSUE TITLE
//tools/cpp/test:test_cc_configure-centos6.7-* fails because of grpc binary

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1190]
Failing tests:
```
//tools/cpp/test:test_cc_configure-centos6.7-opt
//tools/cpp/test:test_cc_configure-centos6.7-fastbuild
//tools/cpp/test:test_cc_configure-centos6.7-dbg
```

Error:
```
(cd /tmp/bazel.WWxj7HJY/out/workspace && \
  exec env - \
  /opt/rh/devtoolset-2/root/usr/bin/gcc -o bazel-out/host/bin/third_party/grpc/cpp_plugin -no-canonical-prefixes -B/opt/rh/devtoolset-2/root/usr/bin -B/usr/bin -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,-S -Wl,--gc-sections -Wl,@bazel-out/host/bin/third_party/grpc/cpp_plugin-2.params): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/opt/rh/devtoolset-2/root/usr/bin/ld: /opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-redhat-linux/4.8.2/libstdc++_nonshared.a(hashtable_c++0x44.o): undefined reference to symbol 'ceil@@GLIBC_2.2.5'
/opt/rh/devtoolset-2/root/usr/bin/ld: note: 'ceil@@GLIBC_2.2.5' is defined in DSO /lib64/libm.so.6 so try adding it to the linker command line
/lib64/libm.so.6: could not read symbols: Invalid operation
```

The binary has to be rebundled with earlier version GLIBC.

**Comment by lberki** [comment]
Where did we get the binaries under `protobuf/` from?

`README.md` says that they are from Maven, but I have my doubts, because I suppose those aren't linked to an old enough gcc are they?

**Comment by damienmg** [comment]
They were linked to an old enough library at least they passed. @philwo did the latest update and pulled them from maven

**Comment by lberki** [comment]
The problem is actually that `-lstdc++` on CentOS also needs `-lm`. So we can:

  * Add `-lm` unconditionally (meh)
  * Add `-lm` only on CentOS (There isn't a simple way in `cc_configure.bzl`, is there?)
  * Create a linker flags environment variable just like we have `CC`

At any rate, bouncing back to @damienmg since `cc_configure.bzl` is his game.
