### ISSUE TITLE
`bazel query` transitions/configurations

### ISSUE THREAD

**Issue by dgp1130** [bazelbuild/bazel#11907]
### Description of the problem / feature request:

I would like to `bazel query` for targets using specific configurations. An example syntax might look like:

```
$ bazel query "somepath(//foo/bar:baz, //hello:world[//my_flags:some_flag=\"test\"])"
```

This would look for a path from `//foo/bar:baz` to `//hello:world` where `//my_flags:some_flag` has been set to `"test"`. It would exclude any paths to `//hello:world` where `//my_flags:some_flag` has any other value.

This might be more of a `bazel aquery` feature, wherever it makes the most sense.

### Feature requests: what underlying problem are you trying to solve with this feature?

I've been doing a lot of work lately with transitions. There are a couple targets which should **never** be built with a particular configuration, so I need to do some work to make sure that doesn't happen. Unfortunately, it is quite difficult to trace back *why* the target was built with this configuration. Allowing `bazel query` to include configurations would make my transition work much easier to debug and trace.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

An example repository where this could be useful (I haven't fully tested this, but it should be close enough to get the point across):

```BUILD
# my_flags/BUILD
load("@bazel_skylib//rules:common_settings.bzl", "string_flag")

# Define a flag at //my_flags:some_flag.
string_flag(
    name = "some_flag",
    build_setting_default = "default_value",
)
```

```starlark
# build_defs.bzl
load("@build_bazel_rules_nodejs//:providers.bzl", "js_named_module_info")

# Defines a trivial Bazel rule `ts_library_transitioned()` which sets `//my_flags:some_flag=test` on its transitive deps.

def _trans_impl(settings, attr):
    return {
        "//my_flags:some_flag": "test",
    }

_transition = transition(
    implementation = _trans_impl,
    inputs = [],
    outputs = ["//my_flags:some_flag"],
)

def _rule_impl(ctx):
    # Propagate dependency info for TypeScript. I'm not entirely sure how this works, but it's not really important to the example.
    return [
        js_named_module_info(deps = ctx.attr.deps),
    ]

ts_library_transitioned = rule(
    implementation = _rule_impl,
    cfg = _transition,
    attrs = {
        "deps": attr.label_list(),
    },
)
```

```BUILD
# foo/bar/BUILD
load("...", "ts_library")
load("//:build_defs.bzl", "ts_library_transitioned")

# Top-level node, depends on a left side and a right side.
ts_library(
    name = "top",
    deps = [
        ":left",
        ":right",
    ],
)

# Left side depends on `:shared` normally, nothing fancy.
ts_library(
    name = "left",
    deps = [":shared"],
)

# Right side depends on `:shared`, but transitions it to use `//my_flags:some_flag="test"`.
ts_library_transitioned(
    name = "right",
    deps = [":shared"],
)

ts_library(
    name = "shared",
    deps = [],
)
```

```
$ bazel query "allpaths(//foo/bar:top, //foo/bar:shared)"
//foo/bar:top
//foo/bar:left
//foo/bar:shared

//foo/bar:top
//foo/bar:right
//foo/bar:shared
```

It would be great to have some means of filtering out the `:left` path based on the transition. Ideally I could do something like:

```
$ bazel query "allpaths(//foo/bar:top, //foo/bar:shared[//my_flags:some_flag=\"test\"])"
//foo/bar:top
//foo/bar:right[//my_flags:some_flag="test"]
//foo/bar:shared[//my_flags:some_flag="test"]
```

Even better if it can show the flag value in the results, so I can see where it was set! That might not scale well with N flags however, so I'll leave that up to the design.

**Comment by jin** [comment]
Have you looked into `cquery`? https://docs.bazel.build/versions/master/cquery.html

**Comment by dgp1130** [comment]
Thanks for pointing that out. I was not familiar with `cquery`, and it seems to be intended for this use case.

With this I can identify the different configurations used in a given build and track back how they got included, which is really helpful to me. Just to point out a couple things that immediately stand out to me about `bazel cquery`:
* I don't care about the configuration hash, I care about the value of a given flag. It would be great if the query `config()` function could search flags directly:
    ```
    $ bazel cquery "somepath(//foo/bar:top, config(//foo/bar:shared, //my_flags:some_flag, \"test\"))"
    ```
* Printing the configuration hash makes it hard to decouple multiple transitions. If I only care about one, but another is being used, then it may change the hash in a way that is very confusing and unrelated to what I'm interested in. In practice this hasn't been an issue for what I'm working on right now, but it certainly could become on as the number of transitions and configurations grow in a codebase.
* `bazel config` isn't very useful since it's just a list of all the configs with no labels or context given. If this could include the flags which were incorporated in each config, I could at least identify the one that I care about.

All that said, this is still really useful and sufficient for my current needs. So I think we can close this issue and just take that as general feedback about the feature.

**Comment by jin** [comment]
FYI @gregestren on the `cquery` feedback

**Comment by gregestren** [comment]
Hi Douglas,

It'd be great to have more fine-grained configuration querying vs. just the hash. The first challenge is figuring out the right API. We could go with something like what you proposed, or advance @alandonovan 's ideas about shifting to a Starlark-based approach for more complicated expressions. 

Re: `bazel config`, if you run `bazel config <specific hash>` it lists all flags and their values for that configuration.
