### ISSUE TITLE
Provide mechanism to transform URLs before downloading them.

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#11906]
### Description feature request:

When downloading remote resources, it would be useful to be able to transform, block, and allow particular URLs. This would allow companies to apply standard security policies, such as ensuring that only company-owned resources are hit during a build, without requiring people to review and modify everything that they use (eg. third party rule sets)

### Feature requests: what underlying problem are you trying to solve with this feature?

As a developer on a corporate owned laptop
I want to be able to transform URLs from maven central to my company's own maven repo
So that the security people do not eviscerate me

### What's the output of `bazel info release`?

3.4.1

###  Have you found anything relevant by searching the web?

The [Fetcher API](https://github.com/bazelbuild/proposals/blob/master/designs/2020-01-14-remote-downloads.md#the-fetcher-api) requires us to implement the whole of the CAS and ByteStream APIs as well as the Fetcher API since there's no way to ask bazel which grpc services it's using for those (and bazel may not be using a grpc service at all)

One possibility we are considering is a config file, containing a block list, and allow list, and a "transformation" dict containing patterns for URLs to match against, and regexs describing the transformations. This isn't particularly elegant, since the regexs will be Java ones, and the config file will likely be in Starlark, but it's better than nowt.

I believe that @katre did the review of the Fetcher API when it landed in bazel (particularly the grpc-based downloader) so he may have some input to make here.

**Comment by shs96c** [comment]
An alternative approach would be to have the `FetchBlobRequest` specify the end point of the CAS to use, and hard fail if no such endpoint was given.

**Comment by katre** [comment]
This sounds useful but I don't have any specific knowledge (and don't know anything about the Fetcher API, sorry).

I'd suggest discussing this on the mailing list and writing up a proposal. Is it possible to configure an external HTTP proxy to handle this, and having Bazel use the proxy instead of direct connections? The simpler this is, the sooner it can land.

**Comment by shs96c** [comment]
Thanks for the response @katre. 

I'd prefer not to rely on an outside service to ensure this: a modification to `.bazelrc` is easy to land and hard to forget. A local HTTP proxy for use by bazel is harder to remember to start, requires us to add that to people's developer workstations, and seems more prone to failure. 

I'll raise this on the mailing list and see where we end up from there.

**Comment by coeuvre** [comment]
Both #11944 and #12170 are merged. Is this still an issue for your use case?
