### ISSUE TITLE
Toolchains don't transition properly for tests marked local

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/bazel#11904]
### Description of the problem / feature request:

My repo has python toolchains configured for darwin and linux.

I am running Bazel on a darwin machine (host=darwin).
My target platform is linux (Set using `--platforms=//some/linux:platform`).
I have a linux execution platform registered (using `--extra_execution_platforms=//some/linux:platform`).

I have a `py_test` labelled `local = True`. It runs on my host Darwin machine, but tries to use the Linux python toolchain.

The test target should know at the time that transitions are being evaluated that it will need to transition to the host configuration, and should transition the toolchain accordingly.

### What's the output of `bazel info release`?

`release 3.3.1`

/cc @katre

**Comment by katre** [comment]
Yes, this is a known issue, that execution platforms are not aware of strategy selection. There's a plan to address this (https://docs.google.com/document/d/1U9HzdDmtRnm244CaRM6JV-q2408mbNODAMewcGjnnbM/edit#), and I am slowly starting on getting the work done.

I'm closing this and I'll refer you to the main tracking issue, #11432.
