### ISSUE TITLE
Remote downloader cannot be used with --remote-executor

### ISSUE THREAD

**Issue by Qinusty** [bazelbuild/bazel#11913]
### Description of the problem / feature request:

When trying to use the `--experimental_remote_downloader` flag with remote execution, bazel reports the following error:

```
ERROR: The remote downloader can only be used in combination with gRPC caching
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`bazel build //... --remote-executor="grpc://localhost:8980" --experimental_remote_downloader="grpc://localhost:8981"`

### What version of bazel are you running?

Release 3.3.1 

### What operating system are you running Bazel on?

Linux

### Any other information, logs, or outputs that you want to share?

A workaround for this is to also provide --remote_cache="grpc://localhost:8980" assuming your remote execution endpoint is also your cache endpoint.

**Comment by jmillikin-stripe** [comment]
I'm not sure exactly what your setup is, but here at Stripe we're using the remote downloader and remote executor together in dozens of workspaces.

Is it possible that this is a flag validation issue? If so, could the title be made more precise?
