### ISSUE TITLE
invalid literal for int(): "2b"

### ISSUE THREAD

**Issue by tmsimont** [bazelbuild/bazel#1191]
I installed latest 2b release and now TensorFlow [./tensorflow/tensorflow.bzl](https://github.com/tensorflow/tensorflow/blob/dc237a98ab7c28ca5d307fe523a6caf2bc6a4810/tensorflow/tensorflow.bzl) can't parse the version number with "2b" in there...

My assumption is that versions shouldn't have build labels with letters in them

`Build label: 0.2.2b`

This results in `invalid literal for int(): "2b"` in the version parsing script.

**Comment by meteorcloudy** [comment]
I already sent a pull request to tensorflow, maybe you can apply this change manually as a work around? 
https://github.com/tensorflow/tensorflow/pull/2094/files

**Comment by meteorcloudy** [comment]
Since tensorflow has merged the pull request, this bug should already be fixed.
