### ISSUE TITLE
There should be a `--netrc` command line option

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#11926]
### Description of the feature request:

The `.netrc` file is often used to store credentials for accessing network resources. In some cases, it would be helpful to pass additional information using this file (for example, a CI build on a shared machine). As such, it would be useful to be able to specify an additional `.netrc` file on the command line

### Feature requests: what underlying problem are you trying to solve with this feature?

Provide secure access to remote resources without leaving credentials in environment variables, and in such a way that Bazel will be able to use this information.

### What's the output of `bazel info release`?

3.4.1

**Comment by coeuvre** [comment]
Closing since `.netrc` support for remote build was added by #12130. Bazel will try to lookup env `$NETRC` for the location of `netrc` file or fallback to `~/.netrc`.
