### ISSUE TITLE
`strict_deps` should indicate when dependencies are no longer used

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#11925]
### Description of the problem / feature request:

Bazel has a mode called “strict deps” where rules need to declare all their first-order dependencies in their “deps” section. This is great for making sure that you’re clear about what you actually depend on. However, if this setting is enabled, it would be incredibly helpful for the build to also alert of unused deps. 

### Feature requests: what underlying problem are you trying to solve with this feature?

Dependency lists tend to only grow as there's no way of indicating that a dependency is no longer required. This makes refactoring codebases harder and increases the burden on developers.

### What's the output of `bazel info release`?

3.4.1

###  Have you found anything relevant by searching the web?

There is the `unused_deps` command, but this doesn't seem to support all languages equally. In addition, it's not integrated into bazel itself, and so is easier to forget to run.

**Comment by lberki** [comment]
This is indeed a very reasonable request. Unfortunately, it's also challenging to implement in a way that's both generic enough to be useful and simple enough to be supported.
