### ISSUE TITLE
Bazel should provide a generalised approach to publishing artefacts

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#11924]
### Description of the feature request:

Currently, each language supported by bazel needs to figure out how to interact with existing language ecosystems. While this tends to be handled to a greater-or-lesser extent by the language-specific rule sets, the adhoc approach makes it hard to work with these cohesively.

As an example, Artifactory is widely used for hosting java jars, npm packages, and docker images. There is no easy way to run a bazel build, identify artifacts that have changed, and publish those without writing ruleset-specific integrations (assuming those rulesets even offer that capability)

### Feature requests: what underlying problem are you trying to solve with this feature?

It should be possible to identify "publishable" targets, and handle that publishing in a consistent way. This is useful for (eg) CI systems and other frameworks that integrate with bazel-based builds. Ideally, something like `bazel publish` would be perfect, but multiple calls to `bazel run` would also work.

###  Have you found anything relevant by searching the web?

I wrote `java_export` for `rules_jvm_external` and a colleague added a `MavenPublishInfo` which seems like a reasonable start.

**Comment by haxorz** [comment]
This sounds more like "team-Bazel". The core team doesn't have relevant expertise here.
