### ISSUE TITLE
Unable to round-trip a JavaInfo

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#11928]
### Description of the feature request:

Given an existing `JavaInfo`, it is impossible to create a copy that is semantically equivalent. This precludes one taking an existing JavaInfo and adding or removing additional information.

### Feature requests: what underlying problem are you trying to solve with this feature?

I'd like to modify a single property of an existing JavaInfo.

### What's the output of `bazel info release`?

3.4.1

**Comment by gregestren** [comment]
For posterity, what's missing if you call the constructor?

**Comment by lberki** [comment]
Is this a good idea? If we allow people to construct any `JavaInfo` instance, it's possible to construct inconsistent ones.
