### ISSUE TITLE
URLs for downloads should be modifiable to known safe alternatives

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#11927]
### Description of the feature request:

Rule sets commonly download additional dependencies from (eg) GitHub or Maven Central (when using `rules_jvm_external`). Many corporate IT policies prevent machines in certain contexts from general Net access, providing "known safe" alternative URL locations (eg. a company-wide maven repo)

Reviewing and editing all used rulesets is error-prone and a high maintenance approach. Instead it would be helpful to be able to have a configuration file telling bazel's downloader:

* URLs it's safe to pass through directly
* URLs that should be re-written (eg. from Maven Central to the company's maven repo)
* URLs that should be blocked entirely

### Feature requests: what underlying problem are you trying to solve with this feature?

Conforming to a company's IT security policies.

### What's the output of `bazel info release`?

3.4.1

###  Have you found anything relevant by searching the web?

There is a `Fetcher` API that the downloader can use to access a gRPC endpoint for downloads, but since it's not possible to determine where the Action Cache, CAS, etc. are located, it is impractical to implement this without also implementing those services.

**Comment by Esben2** [comment]
For me this is a show stopper: I can't get Bazel to work on our buildservers in a simple way. The recommended way of downloading Bazel's internal dependencies in https://docs.bazel.build/versions/master/guide.html doesn't even work.

For me it is not even enough to be able to download from an internal server, I need to be able to put everything in a kind of archive to be put in the company document management, such we can build our software again after a few years if a customer needs to have something fixed.

I found the  --repository_cache option. I can probably make a list of files downloaded when I work with Bazel and maintain a list of files needed by making an internal script. It will be a hazzle, though: 1) I can't see anything about what is in those files are, the names are wiped out, only their hashes are available. 2) I have no clue of their licenses either (solved by bazel query?) 3) There is no connection between build targets and what is needed, so every buildserver needs to keep that cache updated, as I need to populate the cache outside Bazel (solved by bazel query?) 4) It will hard to find out when I can remove a file from the list again (solved by bazel query?)

I can propose a better solution that would work for me in the form of a "hook": Whenever Bazel wants to download something from an URL it doesn't use it's internal web-client but calls a user given command. In that I can download from a cache server or an archive. Bazel takes it from there and performs sha256 verification and unpacking etc. The arguments to the command could be the URL and the destination of the file. Bazel will shall still take care of the integrity checking, unpacking etc.

**Comment by philwo** [comment]
Closing this on the assumption that it was fixed in https://github.com/bazelbuild/bazel/pull/12170 :)
