### ISSUE TITLE
Skylark ctx.command doesn't incorporate runfiles from input executables; py_binary/java_binary executables fail

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#1192]
(I forked this bug off of issue #1136, because #1136 turned out to be a mix of several bugs.)

Consider this repository https://github.com/dfabulich/cannot-find-runfiles

There's a simple python script in `build_tools/whatevah.py` that accepts one CLI argument and writes a file to that location.

``` python
import sys

with open (sys.argv[1], "w") as OUT:
    OUT.write("hello world")
```

It's declared as a simple `py_binary` in `build_tools/BUILD`.

``` python
py_binary(
    name='whatevah',
    srcs=['whatevah.py'],
    visibility=['//visibility:public'],
)
```

There's a simple Skylark rule in `build_tools/example.bzl`; the `example` rule runs `whatevah` to generate a `%{name}.txt` file as output, but it uses the `command` parameter to `ctx.action` instead of the `executable` parameter.

``` python
def _impl(ctx):
    ctx.action(
        inputs = [ctx.executable._whatevah],
        outputs = [ctx.outputs.text],
        command = "{} {}".format(ctx.executable._whatevah.path, ctx.outputs.text.path),
    )

example = rule(
    implementation = _impl,
    attrs = {
        "_whatevah": attr.label(executable=True, allow_files=True, default=Label("//build_tools:whatevah"))
    },
    outputs = {
        "text": "%{name}.txt",
    }
)
```

Finally, `foo/BUILD` declares a `foo` target with the `example` rule.

``` python
load('/build_tools/example', 'example')

example(
    name='foo',
)
```

When I `bazel build foo`, I expect it to succeed and generate `foo.txt`, but instead I get this error:

```
$ bazel build foo --verbose_failures
INFO: Found 1 target...
ERROR: /private/tmp/repro/foo/BUILD:3:1: error executing shell command: 'bazel-out/local_darwin-fastbuild/bin/build_tools/whatevah bazel-out/local_darwin-fastbuild/bin/foo/foo.txt' failed: bash failed: error executing command
  (cd /private/var/tmp/_bazel_dfabulich/92410d0e3373f265902564b48493ac12/repro && \
  exec env - \
  /bin/bash -c 'bazel-out/local_darwin-fastbuild/bin/build_tools/whatevah bazel-out/local_darwin-fastbuild/bin/foo/foo.txt'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Traceback (most recent call last):
  File "bazel-out/local_darwin-fastbuild/bin/build_tools/whatevah", line 110, in <module>
    Main()
  File "bazel-out/local_darwin-fastbuild/bin/build_tools/whatevah", line 66, in Main
    sys.argv[0])
AssertionError: Cannot find .runfiles directory for bazel-out/local_darwin-fastbuild/bin/build_tools/whatevah
Target //foo:foo failed to build
INFO: Elapsed time: 0.113s, Critical Path: 0.03s
```

As discussed in issue #1136, you can workaround this issue by using the `executable` parameter to `ctx.action` instead of `command`.

``` python
def _impl(ctx):
    ctx.action(
        executable = ctx.executable._whatevah,
        arguments = [ctx.outputs.text.path],
        outputs = [ctx.outputs.text],
    )
```

**Comment by dfabulich** [comment]
Beware, if you try to workaround the this issue #1192 by converting your `ctx.action` command into a `sh_binary`, you'll probably also hit issue #1147, in which `sh_binary` scripts have an incorrect working directory when run via Skylark.

**Comment by umap341** [comment]
Hi,

Is there a way now to invoke py_binary through skylark rule?

Thanks,

**Comment by comius** [comment]
This issue is pretty old and API has changed a lot.
`ctx.actions.run` incorporates runfiles when somebody uses `ctx.executable.xxx` in it. So I believe this is solved.
