### ISSUE TITLE
`lang_proto_library` rules do not generate services

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#11934]
### Description of the problem / feature request:

The `lang_proto_library` rules do not appear to generate [services](https://developers.google.com/protocol-buffers/docs/proto#services). It's confusing to expect these to be generated when using protobufs, and then have nothing happen.

There are several options available:

* Warn that the services are being ignored
* Generate a basic stub grpc binding, assuming Google's own OSS grpc libraries are being used
* Fail the build and link to a ruleset that supports grpc services

### Feature requests: what underlying problem are you trying to solve with this feature?

The features of protobufs should be supported by the protobuf rules in bazel.

### What's the output of `bazel info release`?

3.4.1

###  Have you found anything relevant by searching the web?

There are a few rulesets that provide grpc support. Notable amongst them is [rules_proto_grpc](https://github.com/rules-proto-grpc/rules_proto_grpc).

**Comment by Yannic** [comment]
Trying to generate (gRPC) services for every `<lang>_proto_library` target, (even if the `.proto` file doesn't contain services) sounds expensive (we'd need to pull-in and link the gRPC runtime even for targets without services as we can't look into the `.proto` files during analysis).

I think the action here should be to mention that service stubs aren't generated for `{cc,java,java_lite}_proto_library` targets, and possibly link `{cc,java}_grpc_library` in the docs.
