### ISSUE TITLE
Protocol Buffer support lacks configurability

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#11933]
### Description of the feature request:

`protoc` configuration in bazel assumes a single configuration is used throughout the build. While this may be true in a small repo, it's possible for there to be more than one class of usage within a repo, eg.when using [ServiceTalk](https://apple.github.io/servicetalk/servicetalk-examples/SNAPSHOT/grpc/index.html) and regular protobufs.

Right now, there's a `proto_lang_toolchain` which allows a single configuration per language. This isn't sufficiently granular.

### Feature requests: what underlying problem are you trying to solve with this feature?

I'd like to compile protobufs for java using more than one configuration of `protoc`

### What's the output of `bazel info release`?

3.4.1

###  Have you found anything relevant by searching the web?

There are multiple rulesets out there that attempt to address this, such as [pubref/rules_protobuf](https://github.com/pubref/rules_protobuf) and [stackb/rules_protobuf](https://github.com/stackb/rules_proto) Neither of these is ideal, and it seems a pity that bazel's own baked in rules aren't sufficient.

**Comment by Yannic** [comment]
This will most-likely done as part of the protobuf-starlarkification (https://github.com/bazelbuild/bazel/issues/10005).
