### ISSUE TITLE
--repo_env causes fetch/query thrashing

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#11943]
> @laurentlb it is the `bazel build --repo_env` that causes the fetch/query thrashing. Both bazel query and bazel fetch do not have a `--repo_env` flag, but its presence in `bazel build` causes bazel to consider the fetch and build steps to be different, hence the thrashing.

_Originally posted by @TheButlah in https://github.com/bazelbuild/bazel/issues/10961#issuecomment-673606451_

**Comment by TheButlah** [comment]
For some additional context on why this is important in my particular use case - we rely on `bazel query` for several scripts/systems to interoperate with bazel, so it gets invoked about as frequently as `bazel build`. We also have set the default C/C++ compiler via a `build --repo_env=CXX=clang++-11 --repo_env=CC=clang-11` in our `.bazelrc` file. This means that we get consisent re-fetching of external workspaces. Suffice to say, its generating quite a bit of pain for our team.

**Comment by laurentlb** [comment]
If `--repo_env` forces a re-evaluation, the flag should be available for `bazel query` too.

**Comment by TheButlah** [comment]
Any movement here?

**Comment by liuliu** [comment]
One way I worked around this is to have a dedicated `output_base` when running bazel query. It seems to be the solution done by the VSCode Bazel plugin as well.

**Comment by pcjanzen** [comment]
A no-good, very bad thing that you absolutely should not do under any circumstances because it is undocumented and unsupported and could stop working at any moment is to put 
```
common --client_env=FOO=BAR
```
into your .bazelrc.

**Comment by bjacklyn** [comment]
@chancila -- I believe your `repo_env` change may also fix this issue
https://github.com/bazelbuild/bazel/commit/c2bdd034014f66ce14529cc353cda18a32320f6c

**Comment by chancila** [comment]
yea I think there's a bunch of duplicate issues around this https://github.com/bazelbuild/bazel/issues/12689

**Comment by fmeum** [comment]
@sgowroji Can be closed based on https://github.com/bazelbuild/bazel/issues/11943#issuecomment-825943367.

**Comment by sgowroji** [comment]
We are closing this issue w.r.t the above https://github.com/bazelbuild/bazel/issues/11943#issuecomment-1346238458. Thanks!
