### ISSUE TITLE
Output `bazel info client-env` with quotes to enable writing to file

### ISSUE THREAD

**Issue by TheButlah** [bazelbuild/bazel#11947]
### Description of the problem / feature request:

According to [here](https://bazel.build/designs/2016/06/21/environment.html#example-usages-of-environment-specifications), you can use `bazel info client-env > .user.bazelrc` in order to freeze the environment variables that bazel will see. This allows people to easily set their PATH variable and ensure that they don't get constant cache thrashing on changes to PATH when working with python venvs, for example.

However, in its current form (tested on bazel 3.2.0), the contents echoed by that command are not surrounded by quotes. This means that if your PATH has spaces in it, bazel claims that your .bazelrc is invalid.

Would it be possible to output the values surrounded by quotes?
Instead of:
```
build --action_env=HOME=/home/ryan
build --action_env=PATH=/home/ryan/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/bin:/home/ryan/.poetry/bin:/home/ryan/.pyenv/shims:/home/ryan/.pyenv/bin:/home/ryan/.poetry/bin:/home/ryan/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Users/Ryan/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Ryan/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/d/Program Files/Microsoft VS Code/bin
build --action_env=PYENV_ROOT=/home/ryan/.pyenv
build --action_env=PYENV_SHELL=zsh
build --action_env=ROBOTICS_DIR=/home/ryan/Programming/robotics
```
it would be:
```
build --action_env="HOME=/home/ryan"
build --action_env="PATH=/home/ryan/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/bin:/home/ryan/.poetry/bin:/home/ryan/.pyenv/shims:/home/ryan/.pyenv/bin:/home/ryan/.poetry/bin:/home/ryan/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Users/Ryan/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Ryan/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/d/Program Files/Microsoft VS Code/bin"
build --action_env="PYENV_ROOT=/home/ryan/.pyenv"
build --action_env="PYENV_SHELL=zsh"
build --action_env="ROBOTICS_DIR=/home/ryan/Programming/robotics"
```

### Feature requests: what underlying problem are you trying to solve with this feature?

Enable freezing the action environment via a `bazel info client-env > .user.bazelrc` and ensure that the resulting `.user.bazelrc` is valid

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Have spaces as a part of your PATH variable
2. Have a .bazelrc file with `build --action_env=PATH` in it and `try-import %workspace%/.user.bazelrc`
2. run  `bazel info client-env > .user.bazelrc`
3. Try `bazel build //...

### What operating system are you running Bazel on?

Ubuntu 20.04 on WSL2

### What's the output of `bazel info release`?

release 3.2.0

###  Have you found anything relevant by searching the web?

- https://bazel.build/designs/2016/06/21/environment.html#example-usages-of-environment-specifications

**Comment by gregestren** [comment]
I'm not sure this is the right team label. I assigned `team-XProduct` because as I understand `--ation_env` was first introduced for better remote repo support. Please re-label or CC back at me (as Bazel DevEx) if we should route this elsewhere.

@TheButlah thanks for the request!

**Comment by alandonovan** [comment]
The `client-env` feature was added in https://bazel-review.googlesource.com/c/bazel/+/6112, explicitly to interoperate with blazerc. Therefore it should output arbitrary key/value pairs using whatever literal notation is understood by the blazerc parser, and we should have a test that every printable character survives in transit. This may require changes the blazerc parser.
