### ISSUE TITLE
target visibility attribute pointing to its direct consumer causes cycle in dependency graph  

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#11945]
### Description of the problem / feature request:

When target A depends on target B and target B has visibility attribute pointing to target A Bazel sees it as the dependency loop and errors out.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Repro is [here](https://github.com/Bazel-snippets/repro_visibility_loop).
Short snippet:
```
# In one package:
cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
    deps = [
        "//hello-greet",
    ],
)
# In another package:
cc_library(
    name = "hello-greet",
    srcs = ["hello-greet.cc"],
    hdrs = ["hello-greet.h"],
    visibility = ["//hello-world"],
)
```
Bazel considers visibility as a dependency, while it is normally directed towards consumers, i.e. against the actual dependency direction.
```
bazel build //hello-world
ERROR: D:/dev/bazel/repro/repro_visibility_loop/hello-world/BUILD:3:10: in cc_binary rule //hello-world:hello-world: cycle in dependency graph:
    //hello-world:hello-world
    //hello-greet:hello-greet
.-> //hello-world:hello-world
|   //hello-greet:hello-greet
`-- //hello-world:hello-world
This cycle occurred because of a configuration option
```

### What operating system are you running Bazel on?

Mac, Linux, Windows

### What's the output of `bazel info release`?

3.5.0RC2

**Comment by ulfjack** [comment]
That is working as intended. There are only five things you are allowed to put in visibility attributes:
1. `//visibility:public`
2. `//visibility:private`
3. `//foo/bar:__pkg__`
4. `//foo/bar:__subpackages__`
5. `//foo/bar:baz` which must be a `package_group` rule

See documentation here: https://docs.bazel.build/versions/master/visibility.html

Pointing it at an individual rule does precisely nothing in terms of visibility, and returns an expected dependency cycle error.

**Comment by konste** [comment]
`Pointing it at an individual rule does precisely nothing in terms of visibility` What I was trying to express is that particular target in one package is only supposed to be used by exactly one specific target in another package and should not be visible to anything else. So it is not possible to express that? There is no way to specify visibility with more precise granularity than the package?

**Comment by konste** [comment]
If this is indeed the case then I would expect the error message to say exactly that: `visibility attribute cannot point to this kind of target.` The actual error message is misleading because visibility is not a dependency, so really there is no cycle.

**Comment by ulfjack** [comment]
Correct. You cannot grant visibility to anything less than the entire package. There was a long discussion about that back when it was added, and it was not deemed useful enough to add. The intention was that this would signal to other teams whether it's acceptable to depend on a rule or not, and granting them any access allows them to circumvent any more precise restrictions than at the package level.

Making the error message more precise is difficult because of how the analysis phase is implemented. I agree that it would be a good idea, but it might be a lot of work.

**Comment by ulfjack** [comment]
I'll also say that from our experience, it's a good idea to give the depending team some leeway in how they structure their rules - it's very common to want to rename a rule or restructure a package, and having overly precise visibility declarations can make that a lot more difficult.

**Comment by konste** [comment]
Thank you for your comments! I understand.
