### ISSUE TITLE
Documentation issue: Installing Bazel on Ubuntu using apt repository

### ISSUE THREAD

**Issue by FatemeKhodayari** [bazelbuild/bazel#11953]
Documentation URL: https://docs.bazel.build/versions/master/install-ubuntu.html

The repository and corresponding gpg key are not available. Running the second command in step 1 of the installation guide, I get the following error:

    ~$ curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
    curl: (22) The requested URL returned error: 403 
    gpg: no valid OpenPGP data found.

**Comment by ipetel** [comment]
Try to install Bazel by using Bazelisk as follows:

1. `cd ~` 
2. `wget https://github.com/bazelbuild/bazelisk/releases/download/v1.6.1/bazelisk-linux-amd64`
3. `chmod +x bazelisk-linux-amd64`
4. `sudo ln -s ~/bazelisk-linux-amd64 /usr/bin/bazel`
5. to test run: `bazel version`

**Comment by FatemeKhodayari** [comment]
Seems that the issue is solved now. So I'm closing this.
