### ISSUE TITLE
Delete `--experimental_ui_limit_console_output`?

### ISSUE THREAD

**Issue by michajlo** [bazelbuild/bazel#11959]
A non-negligible amount of complexity is required to support it. Removing it should simplify some internals and make it easier to make existing and future features more robust. I wanted to open this bug first, however, to see if anyone is relying on it.

Searching the internet, there aren't a lot of hits. https://github.com/bazelbuild/bazel/issues/4867#issuecomment-648982371 is one of them, but it's more suggesting the flag was an insufficient workaround for something else.

**Comment by laurentlb** [comment]
@ulfjack might have an opinion on this

**Comment by michajlo** [comment]
5bb3becc09ef535276576a31d98d8686b248bbea deletes this.

**Comment by RonRothman** [comment]
FWIW, we're currently using this internally. We're ok losing it if we must (TBH it was always a bit janky), but: is there another way to prevent Bazel's output on `bazel run`? We want to only see the output from the actual target program. (And `script_path` is not an ideal option in our case.)

**Comment by michajlo** [comment]
I'd try some combination of `--ui_event_filters=` and `--noshow_progress`. That, or run the resulting binary directly.
