### ISSUE TITLE
Rename the function convertLibraryToLinkListToLibraryToLinkList

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#11950]
Many people said it's their favorite method name.
But maybe we can find another name? :)

https://cs.opensource.google/bazel/bazel/+/97577290d27ad08e1bae72b4f6b67e608d4f9650:src/main/java/com/google/devtools/build/lib/rules/cpp/CppLinkActionBuilder.java;l=551

**Comment by alandonovan** [comment]
> But maybe we can find another name? :)

Maybe. What does it do? I couldn't really tell from its doc comment.

**Comment by agluszak** [comment]
Why are there two LibraryToLink classes in the first place?

**Comment by gregestren** [comment]
Fixed by https://github.com/bazelbuild/bazel/commit/13c784073c1962ff4858f27ab6cb02ffdb5cab0a#diff-96c7ce83762d0555ba7dfb3b1ad3aa50.
