### ISSUE TITLE
BUILD- and WORKSPACE-loaded bzl files should have the same predeclared environment

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#11954]
A .bzl file should define the same set of top-level symbols regardless of whether it was loaded on behalf of a BUILD file or WORKSPACE file. Today, the set of symbol names is the same, but the `native` modules of the two bzl types are different.

We want to avoid spurious differences between types of bzls files, both for the sake of simplicity and to be friendlier to tooling. Clearly there are features that do not apply to both contexts -- `native.glob()` makes no sense during WORKSPACE evaluation, and `native.register_toolchains` makes no sense during BUILD evaluation. But we can address this by failing at evaluation time if called from the wrong context. We already do that, for instance, if `native.glob()` is called at the top level in a bzl file rather than inside a macro.

Arguably we can also have BUILD and WORKSPACE files themselves share the same environment. But if we do that, let's track it in a separate bug.

@alandonovan

**Comment by alandonovan** [comment]
Agreed. One benefit is that the set of predeclared names is an input to the Starlark resolver (and thus compiler), so different names mean the .bzl file must be compiled differently.

**Comment by brandjon** [comment]
> so different names mean the .bzl file must be compiled differently.

Note that the set of names is currently the same (and there's a [test](https://github.com/bazelbuild/bazel/blob/968422dd6e6735b6066ccbe862b6bc6ab38ce4d6/src/test/java/com/google/devtools/build/lib/packages/BazelStarlarkEnvironmentTest.java#L59) to ensure it remains the same).

Deprioritizing this issue because the benefit is mostly aesthetic, and will become irrelevant as we migrate from the current repository mechanism to bzlmod.

**Comment by fmeum** [comment]
@brandjon Is it possible that `repository_rule` is a further difference that is not caught by https://github.com/bazelbuild/bazel/blob/968422dd6e6735b6066ccbe862b6bc6ab38ce4d6/src/test/java/com/google/devtools/build/lib/packages/BazelStarlarkEnvironmentTest.java#L59?

**Comment by brandjon** [comment]
We discussed this again more recently. We confirm that there's conceptually only one `.bzl` dialect, but that the `native` object is currently magical because its fields depend on the context. We'd like to simplify by merging all the `native` variants into a single object, whose fields may error out if called in the wrong context.

This is basically the same as what happens today if you try to `glob` in WORKSPACE context, or instantiate a repo rule in BUILD context. (Some of those may actually currently be crash bugs, in fact.) The only observable difference will be `dir`/`hasattr` behavior, which, aside from change detector tests, will only break users who are trying to determine whether they are in BUILD or WORKSPACE context. We think that usage is rare...

> Is it possible that repository_rule is a further difference that is not caught by

No, I don't think so. I believe all non-`native` objects in the top-level environment are treated the same. Even `native` should be covered by that test.
