### ISSUE TITLE
py_binary doesn't generate __init__.py file for workspace directory

### ISSUE THREAD

**Issue by eldenseropian** [bazelbuild/bazel#1196]
With this py_binary rule
```
py_binary(
    name = "kubectl_wrapper",
    srcs = [
        "kubectl_wrapper.py"
    ],
    deps = [
        "//asana/server/kinesis:kinesis",
        "//asana/server/kubernetes/tools:cloudformation",
    ]
)
```
The following is generated:
```
├── kubectl_wrapper.runfiles
│   ├── MANIFEST
│   └── asana2
│       └── asana
│           ├── __init__.py
│           └── server
│               ├── __init__.py
│               ├── kinesis
│               │   ├── __init__.py
│               │   └── kinesis_helpers.py -> /Users/eldenseropian/sandbox/asana/asana2/asana/server/kinesis/kinesis_helpers.py
│               ├── kubernetes
│               │   ├── __init__.py
│               │   ├── kubectl_wrapper -> /private/var/tmp/_bazel_eldenseropian/bab516a5c80085ba67cbbefbf571eae7/asana2/bazel-out/local_darwin-fastbuild/bin/asana/server/kubernetes/kubectl_wrapper
│               │   ├── kubectl_wrapper.py -> /Users/eldenseropian/sandbox/asana/asana2/asana/server/kubernetes/kubectl_wrapper.py
│               │   └── tools
│               │       ├── __init__.py
│               │       └── cloudformation_helpers.py -> /Users/eldenseropian/sandbox/asana/asana2/asana/server/kubernetes/tools/cloudformation_helpers.py
│               └── utils
│                   ├── __init__.py
│                   └── common.py -> /Users/eldenseropian/sandbox/asana/asana2/asana/server/utils/common.py
```

However, we need an `__init__.py` under `asana2` in order for our imports to work correctly. We import things from this workspace both within and outside of the workspace.

Note for anyone else with this problem:

We're currently getting around it by having a library in the root of our workspace depend on the `__init__.py` there:

```
py_library(
    name = "init",
    srcs = ["__init__.py"]
)
```
but this requires depending on this library in all entry points to our application.

**Comment by meteorcloudy** [comment]
I think if you are trying to import things within this workspace, everything should be fine. If it's outside of the workspace, is it an option to use local_repository?http://bazel.io/docs/be/workspace.html#local_repository

**Comment by eldenseropian** [comment]
Unfortunately not - we're not using bazel outside of this workspace. Everything's in one repository, and bazel is used on a subdirectory within that repository, and while that's not the desired end-structure, we need to make it work in the meantime.

**Comment by meteorcloudy** [comment]
Hello, I understand your situation now. Maybe we can work around like this:
Create the following files with specified content.
- asana2/tools/build_rules/BUILD  : empty file, just indicate this is a package

- asana2/tools/build_rules/init.bzl   : define your own py rules, add `//:init` in deps
```
def py_library(name, deps=[], **kwargs):
  deps = deps + (["//:init"] if name!="init" else [])
  native.py_library(name = name, deps = deps, **kwargs)

def py_binary(deps=[], **kwargs):
  native.py_binary(deps=deps+["//:init"], **kwargs)
```
- asana2/tools/build_rules/prelude_bazel  :This file is automatically prepended to every BUILD file loaded by Bazel.
```
load("/tools/build_rules/init", "py_library")
load("/tools/build_rules/init", "py_binary")
```
Now every py_library and py_binary will depend on `//:init` except `//:init` itself.
I hope this could help you. :)

**Comment by eldenseropian** [comment]
Perfect! That does it. Thanks so much!

**Comment by eldenseropian** [comment]
It'd be awesome if you could still consider fixing this - the workaround is great, but this still doesn't seem like desired behavior and I'd prefer to not need it.
