### ISSUE TITLE
[Android] Mobile-Install runtime crash caused by rewriting try-with-resources statements

### ISSUE THREAD

**Issue by ThomasCJY** [bazelbuild/bazel#11961]
**Background**
* Test repository and branch to repro the issue ([link](https://github.com/ThomasCJY/bazel_example/pull/2))

While using `mobile-intall` to install our android app target, we noticed an instant crash on app open with a stack trace:
```
 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.bazel, PID: 3197
    java.lang.IllegalAccessError: Illegal class access: 'com.google.devtools.build.android.desugar.runtime.ThrowableExtension' attempting to access 'com.google.devtools.build.android.desugar.runtime.ThrowableExtension$NullDesugaringStrategy' (declaration of 'com.google.devtools.build.android.desugar.runtime.ThrowableExtension' appears in /data/app/~~y9VAI4_h6duHtmrR-6cmMw==/com.example.bazel-F-lfB2AsjpB-6l3LfcfTGQ==/base.apk)
        at com.google.devtools.build.android.desugar.runtime.ThrowableExtension.<clinit>(ThrowableExtension.java:67)
        at com.google.devtools.build.android.desugar.runtime.ThrowableExtension.printStackTrace(ThrowableExtension.java:96)
        at com.google.common.base.Throwables.getStackTraceAsString(Throwables.java:352)
        at com.example.bazel.MainActivity.onCreate(MainActivity.java:27)
```
And the problematic line of code is:
```
import com.google.common.base.Throwables;
....
String s = Throwables.getStackTraceAsString(e);
```
After digging into the issue, I noticed that bazel is using [TryWithResourcesRewriter ](https://github.com/bazelbuild/bazel/blob/master/src/tools/android/java/com/google/devtools/build/android/desugar/TryWithResourcesRewriter.java#L97-L101) to replace `Throwables` with `ThrowableExtension`. Apparently, this change causes issue during runtime where dependency and access permissions has not been handled gracefully. 

**Repro Steps**
* Test repository and branch to repro the issue ([link](https://github.com/ThomasCJY/bazel_example/pull/2))
* Run `bazelisk mobile-install //src/main:app` and open the app, app will instantly crash

**Comment by nkoroste** [comment]
Any updates on this?

**Comment by arunkumar9t2** [comment]
My findings. After making the `*DesugaringStrategy` classes public, I no longer have this crash. Example patch [here](https://github.com/arunkumar9t2/bazel/commit/11387ae2c3c32e23e1ab4870505a9a2c97ae714d).

To try this locally

- `bazel build //src:bazel //tools/android/runtime_deps:android_tools.tar.gz`
- `mkdir /tmp/android_tools`
- `tar -xf bazel-bin/tools/android/runtime_deps/android_tools.tar.gz -C /tmp/android_tools`
- Run mobile-install with `--override_repository=android_tools=/tmp/android_tools`

**Comment by arunkumar9t2** [comment]
Fixed by https://github.com/bazelbuild/bazel/pull/15184

**Comment by ahumesky** [comment]
https://github.com/bazelbuild/bazel/pull/15184 was merged (also we moved to D8-based desugaring)
