### ISSUE TITLE
expose action owner to aspects

### ISSUE THREAD

**Issue by shahms** [bazelbuild/bazel#11978]
### Description of the problem / feature request:

Rule (and aspect) actions are currently exposed via `target.actions()` and (`ctx.rule.attr.<attr>.actions()`), but there is no way to distinguish between actions generated by the rule itself and those generated by an aspect which may have been applied to the rule.  (Related, there is no way to determine which of the dependencies were the result of an aspect application rather than an immediate rule, short of `str(dep).startswith("<merged target")`).

### Feature requests: what underlying problem are you trying to solve with this feature?

In trying to replace our use of extra actions with Aspects we've encountered a few snags related to aspects-on-aspects, particularly from the command line. We have a few requirements for parity with the extra-action based behavior:

1. Apply only to top-level targets specified directly on the command line (`--experimental_extra_action_top_level_only`)
  a. Mostly doable by not having the aspect propagate on any attributes, but the semantics aren't quite the same.
  b. This is to reduce redundant visitation of targets via their dependencies.  We will include the desired targets specifically at the top-level.
1. Retrieve actions generated by top-level rules implemented by aspects (the language-specific proto_library rules being the prime example):
  a. Currently doable by allowlisting a set of rules known to be implemented this way and inspecting the specific relevant attribute (typically `deps`) for their actions.
  b. Hard-coding this behavior for specific attribute/rule combinations is not ideal.
  c. We could probably implement this ourselves with a custom provider if there were more control over command-line aspect application order and traversal behavior.
1. Apply command-line aspects to the results of other command-line aspects
  a. This is likely #11736 
  b. Currently, extra action listeners are applied to the actions produced by command line aspects, but there's not any way of doing so with aspects.

Being able to determine which actions were generated by aspects applied to a dependency rather than by the rule itself would allow doing bullet 2 in a generic fashion, rather than having to hard-code and allowlist of rules and attributes.

### What operating system are you running Bazel on?

Rodete-like custom distribution.

### What's the output of `bazel info release`?

release 3.4.1

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git@github.com:shahms/kythe.git
6cae87ed060c7218d31c789e2c96307313592b66
6cae87ed060c7218d31c789e2c96307313592b66

###  Have you found anything relevant by searching the web?

#11736

**Comment by comius** [comment]
cc @mai93 

> Rule (and aspect) actions are currently exposed via target.actions() and (ctx.rule.attr.<attr>.actions()), but there is no way to distinguish between actions generated by the rule itself and those generated by an aspect which may have been applied to the rule.

Exposing owner info on actions() seems doable. What’s your use case for actions? I’m asking because I wish that feature wasn’t too popular.

> Apply only to top-level targets specified directly on the command line (--experimental_extra_action_top_level_only)
a. Mostly doable by not having the aspect propagate on any attributes, but the semantics aren't quite the same.

What do you mean? I don’t think there’s any difference in semantics. If you say aspect shouldn’t propagate on aspect_attrs and don’t add any other requirements on the providers it’s going to be applied exactly to top level targets.

> Retrieve actions generated by top-level rules implemented by aspects 

Are those actions generated by for example java_proto_library, by java_proto_aspect directly on jpl or transitively by the aspect?

I’m not following the solutions you’re mentioning. Likely because I don’t know what’s the problem you’re solving.

> Apply command-line aspects to the results of other command-line aspects

This is most likely already solved by a new way how to propagate aspects over aspect. See aspect requires parameter, where you can list other aspects that should propagate before the current one.

**Comment by shahms** [comment]
Yes, I think aspects-on-aspects is the proper solution for this.  While it doesn't work for natively-implemented rules like `cc_proto_library`, it's not worth the additional complexity over just finishing that migration to Starlark :-)

**Comment by shahms** [comment]
As for the use case for actions: we use them to get the command line for bundling action inputs and commands into a hermetic bundle for indexing.  Conceptually, something like compile_commands.json
