### ISSUE TITLE
Generate table of contents in documentation

### ISSUE THREAD

**Issue by ip** [bazelbuild/bazel#1198]
For example, in [User Manual](http://bazel.io/docs/bazel-user-manual.html) there is a lot of text, and lack of contents table forces you to scroll to no purpose. Please implement it, see for example any Wikipedia article. Thanks!

**Comment by davidzchen** [comment]
Agreed. I'll take this one.

**Comment by helenalt** [comment]
Updated link to the User Manual is https://docs.bazel.build/versions/master/user-manual.html
@spomorski to review what's the best way to organize this page.

**Comment by spomorski** [comment]
Reorganizing the User Manual is a long-term effort. I'll be looking into it this or next quarter.

**Comment by laurentlb** [comment]
Each page has now a table of content on the right.

Closing this bug.
