### ISSUE TITLE
Documentation issue: Installing Bazel on Arm

### ISSUE THREAD

**Issue by mattsplats** [bazelbuild/bazel#11994]
Documentation URL: https://docs.bazel.build/versions/master/install-ubuntu.html

Install instructions cover using the Debian repo, but do not mention that this will not work for `arm64` systems. `arch` is specified as `amd64`, but specifying `arm64` will also fail because the Debian repo does not contain this build currently.

Instructions should state that the Debian repo and build scripts are not available for `arm64` systems. Bazelisk, the pre-built binary, or building from source should be used instead.

Perhaps:
```
Install Bazel on Ubuntu using one of the following methods:
- Use Bazelisk (recommended)
- Use our custom APT repository
- Use the binary installer
- Compile Bazel from source

APT installation is not available for Arm-based systems. Instead, use one of the following methods:
- Use Bazelisk (recommended)
- Use the pre-built arm64 binary
- Compile Bazel from source
```

**Comment by mattsplats** [comment]
Related: should make it clear that Bazelisk will work for Redhat-based and other distros. Another page may be useful for this.

**Comment by mattsplats** [comment]
Just following up on this - I can submit a PR if it would help. Thanks!

**Comment by philwo** [comment]
@mattsplats Thank you! Sorry, I didn't get around to update the docs myself, but I'd be happy to review a PR.

**Comment by mattsplats** [comment]
No worries. There seems to be a delta between [the Github readme](https://github.com/bazelbuild/bazel/blob/master/site/docs/install-ubuntu.md) and the [web instructions](https://docs.bazel.build/versions/3.5.1/install-ubuntu.html#install-on-ubuntu) - is there a pipeline that should publish the document? I can submit changes but want to be sure they make it to the website.

**Comment by philwo** [comment]
@mattsplats This part of the webseite is versioned together with Bazel and the linked commit came after Bazel 3.5.x was cut from the `master` branch. If you switch the shown version to `master` in the drop-down in the top-left corner of the website, it should show the latest version. :)

**Comment by mattsplats** [comment]
Ahh, got it, thanks.
