### ISSUE TITLE
attr.label single_file does not imply allow_files

### ISSUE THREAD

**Issue by trainman419** [bazelbuild/bazel#1199]
If I pass a file to a rule attribute which is defined as `"src": attr.label(single_file=True)`, I get an error:

```
 in src attribute of _redacted rule //pkg:file.foo: file '//pkg:file.foo' is misplaced here (expected no files).
```

This is surprising since I've specified that I would like this attribute to accept only a single file.

I would expect either of the following behaviors:
- `single_file=True` implies `allow_files=True`
- **OR** `single_file=True` throws an error if `allow_files` is not True

**Comment by dslomov** [comment]
Isn't this fixed by now?

**Comment by laurentlb** [comment]
Yes, it's fixed. Use allow_single_file instead.
