### ISSUE TITLE
Build fails if Annotation Processor generates output once processing is over

### ISSUE THREAD

**Issue by currankbhatia** [bazelbuild/bazel#11992]
### Description of the problem / feature request:

We have an annotation processor that we attach as a plugin to a java library rule. And the java library rule fails to compile all the source code that includes the generated java code from the annotation processor when we try to generate output after the processing is over, instead of generating the output before the processing is over.

We don’t know if this is a bug in the java library rule or if this is an issue with our annotation processor generating java code at the end of processing.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Here is a snippet of code from the Annotation Processor’s processor method as seen attached in the AnnProcExample.zip. When the generateCode method is placed such that the condition env.processingOver() or annotations.isEmpty() is met, we get an error. However, when we place the generateCode method right after processAnnotations() such that we generate output even before we check that processing is over using env.processingOver(),  there is no error. I am wondering why there is a discrepancy from generating output at the end of processing vs during the processing.

```java
    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment env) {

        try {
            if (env.processingOver() || annotations.isEmpty()) {
                if (env.errorRaised()) {
                    final String msg = "Errors are preventing wrapper code generation. Please fix the errors.";
                    processingEnv.getMessager().printMessage(Diagnostic.Kind.MANDATORY_WARNING, msg);

                } else {
                    // generate source code only when there are no errors, and after the processing is over
                    generateCode();
                }
            } else {
                processAnnotations();
            }

        } catch (Exception e) {
            messager.printMessage(Diagnostic.Kind.ERROR, "Exception occurred: " + e.getMessage());

        }

        return true;
    }
```
```starlark


load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "ProjectRunner",
    main_class = "Hello",
    srcs = [ 
        "src/main/java/Hello.java",
        "src/main/java/Language.java",
        ],  
    plugins = ["ap"],
    deps = [ 
        "//AnnProc:ann_proc",
    ]   
)

java_plugin( 
    name = "ap",
    processor_class = "MyProcessor",
    deps = ["//AnnProc:ann_proc", "@javapoet"]


)
```

```java
import samplepackage.FactoryClassName;

@Factory (
        id = "English",
        type = Language.class
)
public class Hello {
    public static void main(String args[]) {
        System.out.println("Number from generated file FactoryClassName: " + FactoryClassName.getNumber());
    }
}
```

```
ERROR: /Users/curran.bhatia/dev4/AnnProcExample/Printer/BUILD:4:12: Building Printer/ProjectRunner.jar (2 source files) and running annotation processors (MyProcessor) failed (Exit 1)
warning: File for type 'samplepackage.FactoryClassName' created in the last round will not be subject to annotation processing.
Printer/src/main/java/Hello.java:3: error: package samplepackage does not exist
import samplepackage.FactoryClassName;
                    ^
Target //Printer:ProjectRunner failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.192s, Critical Path: 2.46s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```
Full sample project can be found here: [AnnProcExample.zip](https://github.com/bazelbuild/bazel/files/5110722/AnnProcExample.zip)

### What operating system are you running Bazel on?

macOS Catalina 10.15.6

### What's the output of bazel info release?

release 3.4.1-homebrew

 ### Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

See the attached [AnnProcExample.zip](https://github.com/bazelbuild/bazel/files/5110728/AnnProcExample.zip), the annotation processor is in the AnnProc directory and it is used in the Printer directory. To run, ‘cd Printer’ and ‘bazel run :ProjectRunner’.

**Comment by currankbhatia** [comment]
This pattern seems to work fine with the JDT compiler but not with Javac.

**Comment by cushon** [comment]
This reproduces with command-line javac, so whether or not this is a javac bug I don't think this is an issue with Bazel / `java_library`:

```
$ javac -fullversion
javac full version "11.0.9+11"

$ wget https://repo1.maven.org/maven2/com/squareup/javapoet/1.1.0/javapoet-1.1.0.jar
$ javac -cp javapoet-1.1.0.jar ./AnnProc/src/main/java/MyProcessor.java ./AnnProc/src/main/java/Factory.java --release 8 -d output && (cd output; jar cvf ../lib.jar .)
$ javac --release 8 -processorpath javapoet-1.1.0.jar:lib.jar -classpath lib.jar -processor MyProcessor ./Printer/src/main/java/Language.java ./Printer/src/main/java/Hello.java
...
./Printer/src/main/java/Hello.java:3: error: package samplepackage does not exist
import samplepackage.FactoryClassName;
                    ^
warning: File for type 'samplepackage.FactoryClassName' created in the last round will not be subject to annotation processing.
1 error
1 warning
```

I filed https://bugs.openjdk.java.net/browse/JDK-8256826 against javac to get clarification on whether or not this is expected behaviour.
