### ISSUE TITLE
Eclipse support

### ISSUE THREAD

**Issue by benmccann** [bazelbuild/bazel#12]
I'm hoping the Eclipse support can be open sourced :-)  All the open-source build tools I currently use like Maven, Gradle, and SBT have Eclipse support built-in.

**Comment by damienmg** [comment]
Ok I don't know if we ever going to ship the current Eclipse support but having an IDE support is definitely something high on our list

**Comment by cgruber** [comment]
I've sort of generalized this in #31 beyond eclipse.

**Comment by PerfectCarl** [comment]
interested in this too

**Comment by digulla** [comment]
@damienmg Do you already have working support for Eclipse internally which you can't share? Or is the quality of the Eclipse support code just too poor to open it?

**Comment by damienmg** [comment]
We have a Eclipse support internally that also include a lot of internal stuff such as integration with our control version system and it doesn't make much sense to open-source it (not that it is too poor, just not suited for outside Google).

**Comment by wrwg** [comment]
Eclipse (and IntelliJ) support can just mean being able to generate project files of the IDE via a command line. The IDEs typically listen for changes on their metadata, and then just magically update (at least Eclipse does). 

Gradle eclipse and idea plugins do it this way, for example. I don't think it's too much work, but then it is still a bit too much if one just wants to use bazel.

**Comment by kayasoze** [comment]
Should this have been closed?

**Comment by damienmg** [comment]
No, why?

**Comment by wolfgangmeyers** [comment]
I have something that might help. Not quite a general purpose solution, but I think it should be easy enough to adapt it to your needs. Basically it involves building _deploy jars that roll up all of the compile-time dependencies using bazel and then constructing eclipse files that reference those jar files. I may do some work to make this general-purpose and put it on github, but for now here is the work in progress - https://gist.github.com/wolfgangmeyers/49d8edaa763f5fcdcdf7

**Comment by dburnette** [comment]
As a former Googler (Eclipse/C++ user), I find it extremely painful using Bazel with a lack of Eclipse support :(. Even if the internal source control stuff can't/shouldn't be open sourced, dependency graph info and incremental build tools would be greatly appreciated!

**Comment by wolfgangmeyers** [comment]
Sounds like an eclipse plugin might be a better general solution.

**Comment by rohitsaboo** [comment]
As yet another ex-Googler on this thread, would love to see the Eclipse integration part open-sourced :) Also, if you have an idea how long this would take, it would be helpful to know.

**Comment by wolfgangmeyers** [comment]
Awesome!
