### ISSUE TITLE
An error occurred during the fetch of repository 'py_deps'

### ISSUE THREAD

**Issue by ZhiyuanChen** [bazelbuild/bazel#12000]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

```
Starting local Bazel server and connecting to it...
INFO: Call stack for the definition of repository 'py_deps' which is a pip_import (rule definition at /home/zyc/.cache/bazel/_bazel_zyc/39b260e0bf5907af3cbafa99781719d7/external/rules_python/python/pip.bzl:44:14):
 - <builtin>
 - /home/zyc/test-infra/WORKSPACE:88:1
ERROR: An error occurred during the fetch of repository 'py_deps':
   pip_import failed:  (src/main/tools/process-wrapper-legacy.cc:58: "execvp(python2.7, ...)": No such file or directory
)
ERROR: no such package '@py_deps//': pip_import failed:  (src/main/tools/process-wrapper-legacy.cc:58: "execvp(python2.7, ...)": No such file or directory
)
INFO: Elapsed time: 59.052s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```zsh
bazel run //prow/cmd/tackle
```

under https://github.com/kubernetes/test-infra

### What operating system are you running Bazel on?

ubuntu 20.04 lts

### What's the output of `bazel info release`?

```
release 3.0.0
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
https://github.com/kubernetes/test-infra
5ad5702344de1dd0a5916e737ccabecf635bb9e2
5ad5702344de1dd0a5916e737ccabecf635bb9e2
```

###  Have you found anything relevant by searching the web?

Nope

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by erikgb** [comment]
@ZhiyuanChen I had a similar problem, and in my case it was resolved by making sure that the python-executable that Bazel looks for, was available **on your PATH**. In my case, I had an alias in my `.bashrc` file:
```shell
alias python=python3
```

This alias will not be used by the Bazel server, so it has to be on the path. I fixed it by creating a symlink:
```shell
sudo ln -s /usr/bin/python3 /usr/local/bin/python
```

Hope this helps! 😄

**Comment by stmcginnis** [comment]
Erik's suggestion worked for me. I think this is just a workaround though.

Newer distros like Ubuntu 20.04 are not aliasing `python` to `python3`, so bazel should probably be explicit about calling `python3`. All distros, as far as I'm aware of, will have `python3` available if Python is installed, whether they also alias to just `python` or not.
