### ISSUE TITLE
JAVA_HOME is not passed to tests from java_runtime

### ISSUE THREAD

**Issue by MikhailTymchukFT** [bazelbuild/bazel#12004]
### Description of the problem / feature request:

When `[host_]javabase` is defined and `java_runtime` is used to configure downloaded JDK, `JAVA_HOME` environment variable is not passed to tests.

### Feature requests: what underlying problem are you trying to solve with this feature?

We have a third party dependency [Google Cloud Datastore](https://search.maven.org/search?q=g:com.google.cloud%20AND%20a:google-cloud-datastore&core=gav) , which uses $JAVA_HOME to locate installed JDK and run an emulator used in tests. 
When local JDK is missing, bazel does not pass configured $JAVA_HOME to tests and emulator fails to start.
That means we cannot get hermetic build and have to maintain local JDK on every build host.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

This is the complete example which illustrates the problem: https://github.com/MikhailTymchukFT/bazel-coursier-java-home-bug

.bazelrc:
```
build --javabase=@openjdk8u202_darwin_archive//:runtime
build --host_javabase=@openjdk8u202_darwin_archive//:runtime
build --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
test --test_env=JAVA_HOME
```

WORKSPACE (jdk part):
```

http_archive(
    name = "openjdk8u202_darwin_archive",
    build_file_content = """
package(default_visibility = ["//visibility:public"])

java_runtime(
    name = 'runtime',
    srcs =  glob(['**']),
    java='//:Contents/Home/bin/java',
    java_home='abc'
)
""",
    sha256 = "059f7c18faa6722aa636bbd79bcdff3aee6a6da5b34940b072ea6e3af85bbe1d",
    strip_prefix = "jdk8u202-b08",
    urls = ["https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08/OpenJDK8U-jdk_x64_mac_hotspot_8u202b08.tar.gz"],
)
```

Test class:

```java
package src;
import org.junit.*;

public class A {
    @Test
    public void test(){
        System.out.println("JAVA_HOME: " + System.getenv("JAVA_HOME"));
    }
}
```

Expected output:

```
JAVA_HOME: abc
```

Actual output:
```
JAVA_HOME: null
```

### What operating system are you running Bazel on?

MacOS 10.15.6

### What's the output of `bazel info release`?

```
release 3.4.1
```

###  Have you found anything relevant by searching the web?

Just found that [cloud emulator works with JDK 8](https://stackoverflow.com/questions/46994787/google-cloud-sdk-datastore-emulator-jre-version-mismatch/47005977#47005977), but no info about bazel [java_home](https://docs.bazel.build/versions/master/be/java.html#java_runtime.java_home) specifics.

**Comment by lberki** [comment]
Why is this needed? Java tests should generally find the JVM even without this variable.

**Comment by MikhailTymchukFT** [comment]
@lberki 
As I mentioned earlier:

> We have a third party dependency [Google Cloud Datastore](https://search.maven.org/search?q=g:com.google.cloud%20AND%20a:google-cloud-datastore&core=gav), which uses $JAVA_HOME to locate installed JDK and run an emulator used in tests.
