### ISSUE TITLE
'WindowsApps\python.exe' is not executable

### ISSUE THREAD

**Issue by lostmsu** [bazelbuild/bazel#12029]
### Description of the problem / feature request:

I have Python installed through Windows Store. Bazel fails to use it:

> --define PYTHON_BIN_PATH='C:\Users\user\AppData\Local\Microsoft\WindowsApps\python.exe' is not executable. Is it the python binary?

I can run `python` from command line: `C:\Users\user\AppData\Local\Microsoft\WindowsApps` is in `PATH`. However, file size is zero (I am guessing it uses some form of redirection).

### Feature requests: what underlying problem are you trying to solve with this feature?

Use standard Python 3.6 for Windows from Store.

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 3.3.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/google/mediapipe.git
c0124fb83c667917c7bf6a84f442a0136e8f2cf7
c0124fb83c667917c7bf6a84f442a0136e8f2cf7

###  Have you found anything relevant by searching the web?

Potentially linked to https://github.com/bazelbuild/bazel/issues/11612

### Any other information, logs, or outputs that you want to share?

N/A

**Comment by arnoutdekimo** [comment]
Same issue here

**Comment by sgowroji** [comment]
Hello @lostmsu, Could you please try the above with latest versions as i see MediaPipe is also updated to use the latest Bazel versions in execution. Thanks!

**Comment by sgowroji** [comment]
As there is no significant update on this issue for long time, We are closing this issue now. Please feel free to reopen if you are still looking resolution for the above query. Thanks!

**Comment by yskan** [comment]
For those still looking for a solution to this problem: it is proably related to the fact that in the installations of Windows that have `bash.exe` map to WSL, the normal windows paths are not recognized by WSL and so in `third_party/py/python_configure.bzl` the `_check_python_bin` fails. You have to translate the paths between Windows and WSL (bash) using the `wslpath` util.

**Comment by GeorgeS2019** [comment]
@yskan 

DO you have an up-to-date solving the famous **PYTHON_BIN_PATH** problem to install e..g mediapipe in **Windows** for my case.
