### ISSUE TITLE
Bazel test (py_test) fails to import some files that are imported for bazel run

### ISSUE THREAD

**Issue by b33pr** [bazelbuild/bazel#1202]
This may be WAI, but I doubt it - if I import protobuf as a native git repository and use the py_proto_library rule, I can run my test fine only if I use 'bazel run' - if I use 'bazel test', I get

from google.protobuf import descriptor_pb2
ImportError: cannot import name descriptor_pb2

I'm imagining this has something to do with how bazel run and bazel test deal with external, but I'm not really sure

**Comment by b33pr** [comment]
running with --spawn-strategy=standalone works, so I guess this has to do with sandboxing - thing is, my build seems pretty hermetic, unless having an external git repo breaks that assumption

**Comment by meteorcloudy** [comment]
cc @damienmg Can you take look at this? I'm not sure what's wrong.

**Comment by damienmg** [comment]
I think this is due to undeclared dependencies that are not shipped into the sandbox. What does the BUILD file looks like?

**Comment by b33pr** [comment]
It's a bit complicated - I copied and pasted the entire chain here:

tile_py_test(
  name="tests",
  srcs=["tests.py"],
  deps=[
    ":tlib",
    "//tile/proto:proto_py",
  ],)

tile_proto_library(
  name="proto",
  srcs=glob(["*.proto"]),
  visibility=["//visibility:public"], )

def py_proto_library(name,
                     srcs=[],
                     deps=[],
                     py_libs=[],
                     py_extra_srcs=[],
                     include=None,
                     has_services=False,
                     srcs_version="PY2AND3",
                     default_runtime="@protobuf//:protobuf_python",
                     protoc="@protobuf//:protoc",
                     **kargs):

  outs = _PyOuts(srcs)

  includes = []
  if include != None:
    includes = [include]

  grpc_plugin = None
  if has_services:
    grpc_plugin = "//external:grpc_python_plugin"

  _proto_gen(name=name + "_genproto",
             srcs=srcs,
             deps=[s + "_genproto" for s in deps],
             includes=includes,
             protoc=protoc,
             grpc_plugin=grpc_plugin,
             gen_py=1,
             outs=outs,
             visibility=["//visibility:public"],)

  if default_runtime and not default_runtime in py_libs + deps:
    py_libs += [default_runtime]

  native.py_library(name=name,
                    srcs=outs + py_extra_srcs,
                    deps=py_libs + deps,
                    imports=includes,
                    srcs_version=srcs_version,
                    **kargs)

The external 'protobuf_python' is just exactly what's in the public protobuf project - it includes all the proto sources as deps via a private rule - it seems like it's definitely depending on things - I'm assuming transitive deps are okay? It really seems like the external thing is throwing something off. Haven't had time to dig into the bazel code at all

**Comment by damienmg** [comment]
Sorry for taking so long to come back but I tried to understand the build. It's kind of hard to see what's wrong. Can you do the following: `bazel query deps(//package:tests) | grep protobuf` and gives the result?

**Comment by damienmg** [comment]
Closing, Please ping back if you still encounter the issue.

**Comment by nicknezis** [comment]
@brianretford Did you ever find a fix to this? I think I'm having the same issue.
