### ISSUE TITLE
output directory layout to platform directory if using --platform other than k8-opt directory

### ISSUE THREAD

**Issue by chengwei920412** [bazelbuild/bazel#12036]
if using --platforms option, the build result to "bazel-out/k8-opt" directory, i want to "bazel-out/{platforms-opt}"

**Comment by katre** [comment]
This would be a fairly disruptive, but @gregestren has some plans for output directories, so I'll let him respond.

**Comment by yicm** [comment]
I also have this need. Switching to a different platform and then switching back will cause the platform to be recompiled, which will reduce the efficiency of multi-platform compilation.

**Comment by jpieper** [comment]
@gregestren Is the current best workaround for this still (1 year later? [1]) to specify an otherwise non-functional `--crosstool_top`?

1. https://groups.google.com/g/bazel-discuss/c/g2jL4Le01Lg/m/lhCCwY_ICwAJ

**Comment by aiuto** [comment]
Closing because we are working on solutions to this on a number of fronts. 
The short explanation is that  it will never be bazel-out/${platform}-opt/, the output directory will be some function of the configuration used by any target.
