### ISSUE TITLE
Race condition with runfiles tree creation on Windows

### ISSUE THREAD

**Issue by nikhilm** [bazelbuild/bazel#12033]
### Description of the problem / feature request:

There is a race condition on Windows where Bazel can create the runfiles tree _before_ the runfiles dependencies, leading to runfiles containing _file symlinks_ even when the actual dependency is a directory (and a directory symlink is expected).
This manifests when running with `--experimental_enable_runfiles`.

This prevents reliable use of directories in runfiles trees.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Needs some custom rules, so I've created this repository, which should be usable out of the box. Please see the README in the repository for details steps to reproduce.

https://github.com/nikhilm/demo-runfiles-dir/

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 3.4.1

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Please see the README in the repository.

**Comment by fmeum** [comment]
Fixed in https://github.com/bazelbuild/bazel/pull/12018
