### ISSUE TITLE
bazel query --output=maxrank doesn't work across repository boundaries

### ISSUE THREAD

**Issue by dmitrig01** [bazelbuild/bazel#12045]
GOOD:

```
/foo/BUILD:
sh_binary(
	name = "a",
	srcs = ["a.sh"],
)

sh_binary(
	name = "b",
	srcs = ["b.sh"],
	data= [":a"]
)

####

% cd foo && bazel query --output=minrank '//...'
0 //:b
1 //:a
```

BAD:

```
/foo/BUILD
sh_binary(
	name = "a",
	srcs = ["a.sh"],
	visibility = ["//visibility:public"],
)

sh_binary(
	name = "b",
	srcs = ["b.sh"],
	data = ["@bar//:x"]
)

/bar/BUILD
alias(
	name = "x",
	actual = "@foo//:a",
	visibility = ["//visibility:public"],
)
####

% cd foo && bazel query --output=minrank '//...'
0 //:b
0 //:a
```

What I would expect in this scenario is something like:
```
0 //:b
1 @bar//:x
2 //:a
```

**Comment by meisterT** [comment]
cc @Wyverald

I am surprised to see that this cyclic reference works. Xudong, do you know whether that's officially supported?

**Comment by dmitrig01** [comment]
Cyclic reference between the two repositories you mean? interesting – I use it frequently. specifically, I have my main monorepo, but I have various http_archive dependencies for which I specify a build_file, which uses rules from my main repository, imported like this.

Is it not officially supported in general for all usage, or specifically within the scope of returning interesting/intelligent results from queries?

**Comment by Wyverald** [comment]
Sorry for the delay (astonishingly I still don't know how to properly set up GitHub notifications) but yeah, this is supported behavior. Cyclic references do already exist between external repositories and are okay as long as there's no cycle between targets. The (in)famous example is that stardoc depends on bazel-skylib, which depends on stardoc.
