### ISSUE TITLE
Release 3.6 - September 2020

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#12040]
# Status of Bazel 3.6

- Target baseline: 2020-09-10
- Expected release date: 2020-10-06
- [List of release blockers](https://github.com/bazelbuild/bazel/labels/Release%20blocker)

To report a release-blocking bug, please file a bug using the `Release blocker` label, and cc me.

Task list:

- [x] Update GitHub issues for incompatible changes
- [x] Pick release baseline: aa0d97c0bfc4c09ec6f45303aa80052ba28afbd9
- [x] Create release candidate: https://releases.bazel.build/3.6.0/rc2/index.html
- [x] Check downstream projects: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1681
- [x] [Create draft release announcement](https://docs.google.com/document/d/1wDvulLlj4NAlPZamdlEVFORks3YXJonCjyuQMUQEmB0/edit)
- [x] Send for review the release announcement PR: https://github.com/bazelbuild/bazel-blog/pull/239
- [x] Push the release, notify package maintainers:
- [x] Update the documentation
- [x] Push the blog post
- [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by keith** [comment]
If possible I think we should cherry pick https://github.com/bazelbuild/bazel/pull/12046 once it lands. Without it in sandboxed builds on darwin you get log spew for every static archive action:

```
external/local_config_cc/libtool: line 40: /private/var/tmp/_bazel_iosci/4988be46b65c576ca5906aacc315f576/sandbox/darwin-sandbox/333/execroot/lyftios/external/local_config_cc/libtool_check_unique: No such file or directory
external/local_config_cc/libtool: line 40: /private/var/tmp/_bazel_iosci/4988be46b65c576ca5906aacc315f576/sandbox/darwin-sandbox/375/execroot/lyftios/external/local_config_cc/libtool_check_unique: No such file or directory
external/local_config_cc/libtool: line 40: /private/var/tmp/_bazel_iosci/4988be46b65c576ca5906aacc315f576/sandbox/darwin-sandbox/376/execroot/lyftios/external/local_config_cc/libtool_check_unique: No such file or directory
external/local_config_cc/libtool: line 40: /private/var/tmp/_bazel_iosci/4988be46b65c576ca5906aacc315f576/sandbox/darwin-sandbox/381/execroot/lyftios/external/local_config_cc/libtool_check_unique: No such file or directory
external/local_config_cc/libtool: line 40: /private/var/tmp/_bazel_iosci/4988be46b65c576ca5906aacc315f576/sandbox/darwin-sandbox/378/execroot/lyftios/external/local_config_cc/libtool_check_unique: No such file or directory
external/local_config_cc/libtool: line 40: /private/var/tmp/_bazel_iosci/4988be46b65c576ca5906aacc315f576/sandbox/darwin-sandbox/438/execroot/lyftios/external/local_config_cc/libtool_check_unique: No such file or directory
```

**Comment by katre** [comment]
My work to remove TransitionMode introduced some issues with Android builds: the symptoms are that android builds that set `--fat_apk_cpu` start seeing errors during one version checking (which appears to be in Bazel). To fix it, we need to cherrypick 1ae143b005f6982dc3150ae49d6f5ae9e9fd6b33 and 23b0b8a45a103f78d37f9338f0e80caffa076d6f, which I think will apply clearly.

Also, #12069 was filed about a regression in 3.5, and could be fixed if we cherrypick 144d5149a0c50e464dd1be0769fed2ce33ab26a4 as well.

**Comment by meteorcloudy** [comment]
b3ac8f60973ba60d578ae6a653cdd993a2d206d7 and 26cbf776e0cdd8fbb9a40aca4c1be6f5313b6eb4 was cherry picked for 3.5.1 for fixing https://github.com/bazelbuild/bazel/issues/12056, we should probably cherry-pick for 3.6.0 as well.

**Comment by laurentlb** [comment]
I'll create a new candidate with the cherrypicks on Monday (sorry for the delay, I'm on vacation this week).

**Comment by konste** [comment]
I just opened a bug https://github.com/bazelbuild/bazel/issues/12117. Don't know if it is big enough to be considered a release blocker for 3.6.0, but on the other hand, it looks like a glaring omission and hopefully is easy to fix.

**Comment by trybka** [comment]
#12046 is in, and per @keith's comments, it would be good to cherry pick this.

**Comment by laurentlb** [comment]
Cherrypick list so far: 1ae143b, 23b0b8a, 144d514, b3ac8f6, 26cbf77

#12117 doesn't seem critical and I haven't seen any fix for it.
I've added a comment to clarify https://github.com/bazelbuild/bazel/pull/12046#issuecomment-697696840

**Comment by laurentlb** [comment]
Created 3.6.0rc3 using:
`scripts/release/release.sh create --force_rc=3 3.6.0` aa0d97c0bfc4c09ec6f45303aa80052ba28afbd9 1ae143b005f6982dc3150ae49d6f5ae9e9fd6b33 23b0b8a45a103f78d37f9338f0e80caffa076d6f 144d5149a0c50e464dd1be0769fed2ce33ab26a4 b3ac8f60973ba60d578ae6a653cdd993a2d206d7 26cbf776e0cdd8fbb9a40aca4c1be6f5313b6eb4

https://releases.bazel.build/3.6.0/rc3/index.html

**Comment by laurentlb** [comment]
Created 3.6.0rc4 using:

`scripts/release/release.sh create --force_rc=4 3.6.0` aa0d97c0bfc4c09ec6f45303aa80052ba28afbd9 1ae143b005f6982dc3150ae49d6f5ae9e9fd6b33 23b0b8a45a103f78d37f9338f0e80caffa076d6f 144d5149a0c50e464dd1be0769fed2ce33ab26a4 b3ac8f60973ba60d578ae6a653cdd993a2d206d7 26cbf776e0cdd8fbb9a40aca4c1be6f5313b6eb4 8b29b6a2dda8d2a9424f43380023ea7141b5c417

https://releases.bazel.build/3.6.0/rc4/index.html

**Comment by thii** [comment]
May I request to cherry-pick abc2211329d3b4c9016a96e2cd1a25c469e87c35? This is a long-standing bug that the only workaround was to uninstall `python@2` from Homebrew, even though we're not using any Homebrew installed tools.

**Comment by laurentlb** [comment]
Cherrypicks are usually for recent regressions (something that worked with the previous version of Bazel). Since we're already late with Bazel 3.6 (and Bazel 3.7 process is starting this week), I'd rather not add any delay.

**Comment by thii** [comment]
Totally makes sense. We can wait for 3.7.

**Comment by laurentlb** [comment]
Released Bazel 3.6
https://github.com/bazelbuild/bazel/releases/tag/3.6.0

cc @vbatts @petemounce @excitoon

**Comment by philwo** [comment]
Bazel 3.6.0 arm64 binaries uploaded to GitHub and https://releases.bazel.build/3.6.0/release/.

**Comment by vbatts** [comment]
Fedora and Centos builds kicked off
https://copr.fedorainfracloud.org/coprs/build/1696184

**Comment by vbatts** [comment]
@philwo can you share the full build flags used to invoke your arm64 builds? I'm wondering if it's memory issues or such, that cause all the aarch64 builds to fail on fedora and epel.

**Comment by philwo** [comment]
@vbatts Sure! This is the full script used to build the binaries. There aren't any special flags, except the `--sandbox_tmpfs_path=/tmp` due to https://github.com/bazelbuild/bazel/issues/3236.

```bash
git fetch origin master
git fetch --force origin refs/notes/*:refs/notes/*
git checkout ${BUILDKITE_BRANCH}

release_name=$(buildkite-agent meta-data get "release_name")
echo "release_name = \"$release_name\""

bazel build --sandbox_tmpfs_path=/tmp //src:bazel
mkdir output
cp bazel-bin/src/bazel output/bazel

output/bazel build \
    -c opt \
    --stamp \
    --sandbox_tmpfs_path=/tmp \
    --embed_label "${release_name}" \
    --workspace_status_command=scripts/ci/build_status_command.sh \
    src/bazel

mkdir artifacts
cp "bazel-bin/src/bazel" "artifacts/bazel-\${release_name}-linux-arm64"

cd artifacts
buildkite-agent artifact upload "*"
```

It runs inside this Docker container (`centos7-releaser`): https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/docker/centos7/Dockerfile#L50

In order to get the initial `bazel` binary for the first Bazel release, I used the `compile.sh` bootstrap. I just tested that this still works on Ubuntu 18.04 and CentOS 7:

```bash
mkdir bazel-3.6.0
cd bazel-3.6.0
curl -O https://releases.bazel.build/3.6.0/release/bazel-3.6.0-dist.zip
unzip bazel-3.6.0-dist.zip
./compile.sh
```

Our arm64 machine is hosted by packet.net and described as an "Ampere® eMAG processor, which features 32 Arm cores operating at 3.3 GHz, with 128GB of RAM, 480GB of SSD storage and dual 10Gbps network ports" (though of course building Bazel should work on a smaller machine, too 😅).

**Comment by vbatts** [comment]
@philwo good info. I don't have direct access to the arm machines used on the copr.fedorainfracloud.org/ build-infra, but fired up a pine64 (2G ram/1G swap; 4 cores), and the `./compile.sh` got the system load up to 56 and then it seized.
So maybe only beefy machines like the Ampere on Packet (Equinix Metal?) will work now?

**Comment by vbatts** [comment]
alrighty. I spun up a c1.large.arm on equinixmetal (on flatcar :train:  ), ran a docker fedora:32 container, and in it:
```shell
dnf install -y rpm-build make xz git
git clone https://github.com/vbatts/copr-build-bazel
cd copr-build-bazel/
make rebuild # also 'make rpm' will work
```
And it successfully built the binary rpm in 570s or so. (`/root/rpmbuild/RPMS/aarch64/bazel3-3.6.0-0.fc32.aarch64.rpm`)

Given the cryptic failures I'm seeing on aarch64 on the copr.fedorainfracloud.org, it is my guess that their machines are too small, or that the bazel build is [too] demanding. (this c1.large.arm does have 96 cores/130G ram)

**Comment by meisterT** [comment]
We missed a cherry pick in 3.6.0, see https://github.com/bazelbuild/bazel/issues/12086#issuecomment-708073451

**Comment by laurentlb** [comment]
Bazel 3.7 is out and should be used instead.
