### ISSUE TITLE
Skylark: improve documentation on cc provider

### ISSUE THREAD

**Issue by trainman419** [bazelbuild/bazel#1206]
I'm trying to do deeper integration with the native cc_library targets, and I would like to retrieve additional providers from those targets like exported include paths and the names of the output files.

The [Target documentation](http://bazel.io/docs/skylark/lib/Target.html) says that other providers exist for many targets, but I have not found the documentation for the providers available on a cc_library Target.

Since this information is not documented, I'm investigating other ways to discover it.

I'm passing some cc_library targets into my rule as a `deps` argument, and trying to list the properties of these dependencies with:

```
  print("%d depdendencies to %s" % ( len(ctx.attr.deps), ctx.file.src ))
  for dep in ctx.attr.deps:
    print(dep)
    print(dep.to_proto())
```

Unfortunately, this results in an error:

```
struct has no method 'to_proto'.
```

Which directly contradicts the struct documentation at: http://bazel.io/docs/skylark/lib/struct.html

I get a similar error if I try to use `to_json()`

I'm using bazel 0.2.1.

**Comment by kchodorow** [comment]
The target documentation is talking about Skylark rules, in particular.  cc_library is a native rule ([source](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/cpp/CcLibrary.java)), so it's providers are not Python structs, but implementations of the Java class, TransitiveInfoProvider.  These can be exposed to Skylark, but each one has to be (manually).  Basically, by default, native rules are completely opaque to Skylark.   

You might want to take a look at https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/cpp/CcSkylarkApiProvider.java. The only example usage I see of it is the (somewhat opaque) [intellij_info.bzl](https://github.com/bazelbuild/bazel/blob/master/src/test/java/com/google/devtools/build/lib/ideinfo/intellij_info.bzl), which uses some cc properties.

**Comment by trainman419** [comment]
Thanks! That's very informative, and I think it provides the information that I'm looking for.

I'd like to keep this ticket open to track improvement to the documentation so that others aren't confused in the same way.

**Comment by hlopko** [comment]
I believe this is fully fixed now. We have quite some docs on https://docs.bazel.build/versions/master/bazel-and-cpp.html.
