### ISSUE TITLE
File layout in sandbox for genrule too complicated

### ISSUE THREAD

**Issue by Esben2** [bazelbuild/bazel#12065]
### Description of the problem / feature request:

I try to use Bazel in an existing code base going from make. We have our own "compiler" in some ways similar to C's pre-compiler, collecting snippets of files to generate one big output file via "includes". In my first tries this worked splendidly in a genrule():

Everything I declare as a dependency is placed in a file hierarchy similarly to our source tree. The tool is executed at the root of the sandbox and all path in the "include" directives matches because in our includes are given relative to the top-level, where I have placed the WORKSPACE file. 

However, when I start to use the tool on files including generated files it doesn't work: The file layout is split it two, one for original src files, and one for generated files. It seems like an extremely odd design, that the "user" of a file shall know whether it is an original source file or a generated file from another rule. 

Since the "include" directives are given all the files to be collected, there is no chance I can use $(location ...) to figure out where they are in the sandbox.

### Feature requests: what underlying problem are you trying to solve with this feature?

Can't genrule - at least trough an option for backward combability - make just on file hierarchy in the sandbox used for genrule?
Or stated in a another way: The genrule() sandbox should be a "copy" (symlinks) with an identical structure as the declared source code and generated files.

### What operating system are you running Bazel on?

Linux, Fedora 31

### What's the output of `bazel info release`?

release 3.4.1

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/6680

**Comment by ulfjack** [comment]
The short answer is no, unless we'd be willing to break genrules that run outside the sandbox.

Are you aware of the $(location) function? You should use that to get the location of a file from a label, like so:
```
genrule(
  name = "foo",
  srcs = ["maybe-generated.txt"],
  outs = ["output.foo"],
  cmd = "compiler $(location maybe-generated.txt) -o $(location output.foo)",
)
```

If you have a single input file, you can also use `$<` and if you have a single output file, you can also use `$@` (like make).

**Comment by Esben2** [comment]
> The short answer is no, unless we'd be willing to break genrules that run outside the sandbox.

I wouldn't care :-) I always use Linux, and I plan to always sandbox to check that the dependencies are correct.
I also asked for an option to enable this - and that option will not be portable as you say, because only the sandbox functionality will be able to "overlay" the generated files with the source files the way I ask - unless there is a general option to Bazel to put all generated files into the source tree, which would make it work again without a sandbox.

The reason I ask is, that I come from a make system, where we build intermediate files into the source tree (i.e. we mix generated and source files), and I therefore never have had the need to look in both places, but can look for includes in just one place.

> 
> Are you aware of the $(location) function? You should use that to get the location of a file from a label, like so:
> 
> ```
> genrule(
>   name = "foo",
>   srcs = ["maybe-generated.txt"],
>   outs = ["output.foo"],
>   cmd = "compiler $(location maybe-generated.txt) -o $(location output.foo)",
> )
> ```
> 
> If you have a single input file, you can also use `$<` and if you have a single output file, you can also use `$@` (like make).

I can't do that. The thing is that I don't give all the files to compiler from the command line. It works similarly to C's pre-compiler with includes in the top level source file, which again has includes to other files, which have includes to other files... But the includes are all relative to our top level directory, where I have placed the WORKSPACE and therefore everything works nicely in the sandbox. I get errors if I forget to declare an included file as I should.  The problem comes when I want to include generated files, which all the sudden is placed in a different directory.

**Comment by ulfjack** [comment]
I don't think the team will implement this 'just for you'. If your compiler doesn't support having the generated files in a separate tree, then either fix the compiler or copy the files to a temporary merged tree. I understand that it's more work for you, but adding code to Bazel 'just for you' is probably even more work.

**Comment by janakdr** [comment]
@Esben2 Normally we handle a situation like the one you're describing by providing the compiler with two include paths to search. You can give it the output root and the source root. Is that an option for you?

Otherwise, I don't really see how to implement this feature, even if we wanted to. There would have to be checks that output files and source files didn't have the same names, which is not currently an error in Bazel.
