### ISSUE TITLE
Bazel Remote Cache miss warning message unclear for "overlapping" files/directories in custom rule

### ISSUE THREAD

**Issue by sschwebach** [bazelbuild/bazel#12067]
### Description of the problem / feature request:

Using Bazel's remote cache will always miss if a rule has an action that generates both a declared directory (via `ctx.actions.declare_directory`) and a declared file (via `ctx.actions.declare_file`) that resides within the previously-declared directory. Trying to use a remote cache will result in a warning message that `<output_file>.tmp` cannot be found (see example below).

This issue is more about the warning message displayed than the actual behavior of the caching mechanism, which can be avoided by better declaring my outputs and following the best practices for output directories [on this page](https://docs.bazel.build/versions/master/skylark/rules.html#actions).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I've made a simpler example compared to my actual rule, which will build successfully but always miss in the remote cache:

```python
def _my_tmp_rule(ctx):
    my_dir = ctx.actions.declare_directory("some/dir")
    my_file = ctx.actions.declare_file("some/dir/some_file.txt")

    ctx.actions.run_shell(
        inputs = [],
        outputs = [my_dir, my_file],
        command = "sleep 2 && mkdir -p {dir} && touch {file}".format(dir = my_dir.path, file = my_file.path),
    )

    return [DefaultInfo(files = depset([my_file]))]

my_tmp_rule = rule(
    implementation = _my_tmp_rule,
)
```

BUILD file contents:

```python
# Load the rule...

my_tmp_rule(
    name = "my_tmp"
)
```

Run the build twice, using either a remote cache or a disk cache:

```bash
bazel build --disk_cache=~/disk_cache //:my_tmp
bazel clean
bazel build --disk_cache=~/disk_cache //:my_tmp
```

When run the second time, the following warning is displayed and the action is re-run. I've replaced my actual `outputBase` with `$OUTPUT_BASE` in the message:

```bash
WARNING: Reading from Remote Cache:
$OUTPUT_BASE/execroot/__main__/bazel-out/k8-fastbuild/bin/some/dir/some_file.txt.tmp (No such file or directory)
```

Removal of all references of `my_dir` in the above example (as a declaration and output) will cause
the cache to hit correctly and no warning to be displayed:

```python
def _my_tmp_rule(ctx):
    my_file = ctx.actions.declare_file("some/dir/some_file.txt")

    ctx.actions.run_shell(
        inputs = [],
        outputs = [my_file],
        command = "sleep 2 && touch {file}".format(file = my_file.path),
    )

    return [DefaultInfo(files = depset([my_file]))]

my_tmp_rule = rule(
    implementation = _my_tmp_rule,
)
```

### What operating system are you running Bazel on?

```
CentOS Linux release 7.4.1708 (Core)
```

### What's the output of `bazel info release`?

```
release 3.2.0
```

###  Have you found anything relevant by searching the web?

None

### Any other information, logs, or outputs that you want to share?

This only affects scenarios where the same action generates both the directory and the file inside of it; Bazel does not allow these two items to be generated in separate actions.

**Comment by akok-vmw** [comment]
I believe there is an underlying issue here. According to the execution log (below), a new `.tmp` file gets generated on each execution. Since the `.tmp` file is temporary and auto-generated by Bazel, shouldn't Bazel ignore it instead of caching it?

```
actual_outputs {
    path: "bazel-out/darwin-dbg-obj/.../some_file.txt"
    ...
}
actual_outputs {
    path: "bazel-out/darwin-dbg-obj/.../some_file.txt.tmp"
    ...
}
actual_outputs {
  path: "bazel-out/darwin-dbg-obj/.../some_file.txt.tmp.tmp"
    ...
}
```

**Comment by akok-vmw** [comment]
> I believe there is an underlying issue here. According to the execution log (below), a new `.tmp` file gets generated on each execution. Since the `.tmp` file is temporary and auto-generated by Bazel, shouldn't Bazel ignore it instead of caching it?

Sorry for not being clear on the effect of the issue. If my interpretation is correct, we are burning an AC entry on each execution with the pathname growing by 4 chars and (maybe?) Bazel downloads all `.tmp` files because they are part of the `actual_output` but only to get deleted before the end of the build because they are temporary files.

**Comment by eric-skydio** [comment]
This is hitting us too, and also seems to be resulting in actual `.tmp` files being created in `bazel-bin/` for __every__ output from the offending action, even those not in the conflicting directory. Interestingly, it appears that this _might_ only be happening for files created _after_ the first conflicting file.

This is a build correctness issue for us, since the directory artifact is a declared output it should have exactly the same content that the action placed in it, not a bunch of extra files created by Bazel.

**Comment by sschwebach** [comment]
> Interestingly, it appears that this _might_ only be happening for files created _after_ the first conflicting file.

Doing a bit more digging the definition of _after_ seems to be based on the path of the output files (alphabetically by the looks of it). This means if `some/dir/some_file.txt` is the first conflicting file, `test_file.txt` will result in a `.tmp` file being created (and placed in `bazel-bin`) while the file `another_file.txt` would not have this issue. It indeed seems to apply to any output file from the action (and not just files in the problem directory) once a conflicting file has been listed.

**Comment by kkpattern** [comment]
We also encountered this bug. We use `configure_make` to build cpython with bazel:

```python
configure_make(
    name = "interpreter",
    lib_source = ":all_src",
    install_prefix = "py_install",
    out_data_dirs = ["lib"],
    out_static_libs = ["libpython3.10.a"],
    out_include_dir = "include/python3.10",
    targets = ["", "install"],
    visibility = ["//visibility:public"],
)
```

We need `out_data_dirs = ["lib"]` because we need the generated python libraries and so extensions. However, the `libpython.a` also resides in `lib` directory. Hence then conflict.

Luckily, cpython configure has a parameter to rename the python library directory so we can workaround it:

```python
configure_make(
    name = "interpreter",
    lib_source = ":all_src",
    configure_options = ["CFLAGS='-Dredacted=\"redacted\"'", "--with-platlibdir=lib64", "--enable-optimizations"],
    install_prefix = "py_install",
    out_data_dirs = ["lib64"],
    out_static_libs = ["libpython3.10.a"],
    out_include_dir = "include/python3.10",
    targets = ["", "install"],
    visibility = ["//visibility:public"],
)
```

**Comment by coeuvre** [comment]
should be fixed via #15329.

**Comment by rpwoodbu** [comment]
This appears still to be an issue as of `6.0.0`. The problem changed slightly, but still seems to persist. Please see ljessendk/bazel-avr-crossplatform#1 for more.

**Comment by coeuvre** [comment]
Bazel@HEAD no longer supports `declare_file` whose location is under `declare_directory so this issue is not relevant.
