### ISSUE TITLE
Android SDK and NDK paths must be set for desktop use cases after Bazel 3.5.0

### ISSUE THREAD

**Issue by jiuqiant** [bazelbuild/bazel#12069]
### Description of the problem / feature request:

MediaPipe (https://github.com/google/mediapipe) gets a GitHub issue (https://github.com/google/mediapipe/issues/1094), reporting that the Android SDK and NDK paths or the $ANDROID_HOME env variable must be set even the user only builds MediaPipe for desktop usage. It seems to be a new behavior of Bazel 3.5.0 (I don't see this requirement with Bazel 3.4.0). MediaPipe is a cross-platform framework that supports Linux, macOS, Windows, Android, and iOS. So, we put android_ndk_repository and android_sdk_repository in the WORKSPACE file and expect that only Android users will setup Android SDK and NDK and hit those two rules when they build the Android apps. 

However, the new behavior requires that all the users must specify the Android SDK and NDK paths even they are not used, which is inconvenience for Linux, macOS, Windows, and iOS users. If we simply remove android_ndk_repository and android_sdk_repository rules from the WORKSPACE file, the users must manually add them back for building Android targets. Is there a way to keep them in the WORKSPACE file and conditionally check them for the Android targets only (like the behavior before Bazel 3.5.0)?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
git clone https://github.com/google/mediapipe.git
cd mediapipe
bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world

# Outputs:
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Either the path attribute of android_sdk_repository or the ANDROID_HOME environment variable must be set.
INFO: Elapsed time: 18.121s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (8 packages loaded, 11 targets configured)
FAILED: Build did NOT complete successfully (8 packages loaded, 11 targets configured)
    currently loading: @rules_foreign_cc//tools/build_defs/shell_toolchain/toolchains ... (3 packages)
    Fetching @local_config_cc_toolchains; Restarting.
    Fetching @local_execution_config_python; fetching
```

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

Extracting Bazel installation...
Starting local Bazel server and connecting to it...
release 3.5.0

**Comment by katre** [comment]
This should be dealt with by #12070, but that will have to wait for another release. I don't think [Bazel 3.6](https://github.com/bazelbuild/bazel/issues/12040) has been cut yet, so this might make it in, or you can ask the release manager whether this bug constitutes a regression.

**Comment by nickgeorge** [comment]
What is the best way for repos to inoculate themselves to this?  I tried exporting  a bogus dir for ANDROID_HOME but it expects a real sdk.  Or are we saying that 3.5 is just borked?

**Comment by nickgeorge** [comment]
FYI - we seem to be tickling this bug through @io_bazel_rules_go//proto:def.bzl- in other words, we don't have any control over the android_sdk_repository rules in question

**Comment by katre** [comment]
If you can't remove the `android_sdk_repository`, you'd need to set ANDROID_HOME to a real SDK checkout, until 3.6 is released with the fix.
