### ISSUE TITLE
Feature request: netrc support for http remote caching

### ISSUE THREAD

**Issue by wisechengyi** [bazelbuild/bazel#12074]
### Description of the problem / feature request:

Feature Request

### Feature requests: what underlying problem are you trying to solve with this feature?

Support netrc when fetching remote cache

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Running any bazel command with "write to remote cache" turned on will get authentication errors because the request does not carry netrc credentials.

### What operating system are you running Bazel on?

mac and linux

###  Have you found anything relevant by searching the web?

The best workaround I have so far from bazelbuild slack is to use
```
bazel build --remote_header=<encoded username:password>
```
but the issue is that
1. the command line option will expose the credential in CI
2. if placed in a bazelrc file, we will have to put it in a separate file out of the dev repo because secrets shouldn't be checked in, but also we will have no way syncing the settings between the repo and what's distributed to prod machines.

Github issues: https://github.com/bazelbuild/bazel/issues?q=is%3Aissue+netrc+remote+cache+ there isn't one related to the netrc support for http remote cache.
DIscuss thread: https://groups.google.com/g/bazel-discuss/search?q=netrc%20cache, doesn't seem very related.

**Comment by coeuvre** [comment]
Implemented in #12130

**Comment by coeuvre** [comment]
Closing. Feel free to reopen or create another issue if the implementation doesn't work for you.

**Comment by wisechengyi** [comment]
Thanks so much, @coeuvre !
