### ISSUE TITLE
Changing workspace name does not trigger necessary changes

### ISSUE THREAD

**Issue by eldenseropian** [bazelbuild/bazel#1207]
We need to change our workspace name, and the change is causing builds to fail.

We're trying to run a target called `postcss`, which has an external dependency on node.
```
bazel-out/local_linux-fastbuild/bin/tools/web/postcss: 7: bazel-out/local_linux-fastbuild/bin/tools/web/postcss: bazel-out/local_linux-fastbuild/bin/tools/web/postcss.runfiles/asana2/external/node_linux/bin/node: not found
```
When we look in `bazel-out/local_linux-fastbuild/bin/tools/web/postcss.runfiles`, we see that we have all the necessary files under `luna2` (the old workspace name). If we run `bazel clean` and rebuild, the build succeeds and the runfiles end up under `asana2` (the new workspace name). We'd appreciate help understanding this, since we're under the impression that incremental builds and clean builds should either both succeed or both fail. We think that maybe Bazel isn't noticing the workspace name change, or is failing to invalidate something as a result of the workspace name change. 

cc @rjaquino

Thanks!

**Comment by kchodorow** [comment]
This actually should be fixed as of a few hours ago 😃
https://github.com/bazelbuild/bazel/commit/b8e2d49b77b153a6cc56080f7927b9d1a50fdf4f

**Comment by eldenseropian** [comment]
That's wonderful! if we want to stay with the release schedule, is there a known workaround in the meantime?

**Comment by kchodorow** [comment]
`bazel clean` will clear the old version out so the next build will regenerate it in the right place.
