### ISSUE TITLE
why fetching one url by fetch is so slowly as different as wget?

### ISSUE THREAD

**Issue by angrad** [bazelbuild/bazel#12089]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

fetching one url http://.....a.tar.gz  on my local server looks like idle, which is so slowly,
but when I use command 'wget http://.....a.tar.gz' in the terminal,  that is so fast.
any suggestion for me, my boss?
thanks a lot.

### Feature requests: what underlying problem are you trying to solve with this feature?

1. I post url http://.....a.tar.gz on Firefox, downloading seems idle.
2. I try to get Fetching progress on the bazel source code, found no answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
just bazel build my project

### What operating system are you running Bazel on?

UBuntu 16.04

### What's the output of `bazel info release`?

release 2.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

...

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

bazel-bin

###  Have you found anything relevant by searching the web?
I have searched, no information found.

### Any other information, logs, or outputs that you want to share?
just 'fetching 450s'

**Comment by jin** [comment]
We need more information about your setup to proceed further. What host are you on? What does your network setup look like? Are you using any proxies? Do you have any data to describe the actual performance of the fetches?
