### ISSUE TITLE
Permission denied in Bazel container: /usr/local/lib/bazel only accessible by root 

### ISSUE THREAD

**Issue by SanjayVas** [bazelbuild/bazel#12094]
### Description of the problem / feature request:

Running the Bazel container [as documented](https://docs.bazel.build/versions/3.5.0/bazel-container.html) results in the following error:
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/usr/local/bin/bazel\": stat /usr/local/bin/bazel: permission denied": unknown

Exploring the container shows that the `/usr/local/bin/bazel` in `PATH` is a symlink to `/usr/local/lib/bazel/bin/bazel`. However, the directory `/usr/local/lib/bazel` has permissions of 0600/drw-------. Therefore, bazel can only be executed by root and cannot be run when specifying an alternative user via the `-u` option to `docker run`.

Tested with latest (3.5.0), 3.4.1, and 3.3.1.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run `docker run --entrypoint='/bin/bash' l.gcr.io/google/bazel:latest -c 'stat /usr/local/lib/bazel'`

Observed: access is 0600/drw-------
Expected: access is 0755/drwxr-xr-x

### What operating system are you running Bazel on?

Linux (5.2.17-1rodete3-amd64 #1 SMP Debian 5.2.17-1rodete3 (2019-10-21 > 2018) x86_64 GNU/Linux)

### What's the output of `bazel info release`?

Not relevant - running Bazel container. See tags tested above.

###  Have you found anything relevant by searching the web?

No, which somewhat surprised me as I expected others to run into this issue.

###  Any other information, logs, or outputs that you want to share?

Using rootless Docker.

```shell
$ docker --version
Docker version 19.03.11, build 42e35e61f3
```

**Comment by philwo** [comment]
@smukherj1 Is this something you could look into? 🤔

If you tell me (just one more time, promise.. 😆) where the Dockerfile for this `l.gcr.io/google/bazel` container is, I can also add the required fix.

**Comment by smukherj1** [comment]
The build logic is collectively defined [here](https://github.com/GoogleCloudPlatform/layer-definitions/blob/master/layers/ubuntu1604/bazel/BUILD) and [here](https://github.com/GoogleCloudPlatform/container-definitions/tree/master/ubuntu1604_bazel).

The image build is done using rules_docker + Bazel. Not using Dockerfiles. You might be able to inject the command [here](https://github.com/GoogleCloudPlatform/layer-definitions/blob/master/layers/ubuntu1604/bazel/BUILD#L81)

**Comment by smukherj1** [comment]
Also I'm looking into why the Bazel 3.5.1 & 3.6.0 images weren't published.

**Comment by philwo** [comment]
@smukherj1 Did you find out what's up with Bazel 3.5.1 & 3.6.0?

Just checked and `latest` still gives 3.5.0.
