### ISSUE TITLE
Virtual File System For Git got unsupported since the 3.5.0 release

### ISSUE THREAD

**Issue by loshca** [bazelbuild/bazel#12098]
### Description of the problem / feature request:

[Virtual File System For Git](https://github.com/microsoft/VFSForGit) got unsupported since the 3.5.0 release

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Make build with Bazel in mounted GVFS repository 

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

release 3.5.0

###  Have you found anything relevant by searching the web?
No

### Any other information, logs, or outputs that you want to share?

I found a [broken commit](https://github.com/bazelbuild/bazel/commit/95bad272d1075924443db83449fba08524c292de) using git bisect: the optimization in the commit resolves symlinks, but [file.cc](https://github.com/bazelbuild/bazel/blob/b9bb10252a004047f9a997165aa1ab7d6c6fa2e7/src/main/native/windows/file.cc#L528) return `kUnknownLinkType`for GVFS.

I made a PR to fix the issue, please see: #12097

**Comment by jin** [comment]
The associated PR looks like this is impacts Windows hosts. Categorizing as `area-Windows`.

**Comment by meteorcloudy** [comment]
The PR has been merged. I'll close this issue now.

**Comment by aiuto** [comment]
This is causing RBE problems.

**Comment by meteorcloudy** [comment]
https://github.com/bazelbuild/bazel/commit/acd33154322de3447c016009754e2ed275017c81 will fix the RBE breakage

**Comment by philwo** [comment]
After Yun's comment, I'm assuming this is fixed.
