### ISSUE TITLE
Gcno instrumentation for cc_binary

### ISSUE THREAD

**Issue by 4ilo** [bazelbuild/bazel#12099]
### Description of the problem / feature request:

When executing bazel build on a cc_binary or cc_library with gcc option --coverage gcno files are generated next to the object files. However the gcno files are not present in the bazel-out folder. 
When executing Bazel with --sandbox_debug the gcno files are generated inside of the sandbox, but not extracted as build artifacts.

### Feature requests: what underlying problem are you trying to solve with this feature?

Make gcno files available in bazel-out as build artifacts.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
cc_binary(
    name = "hello",
    srcs = [
        "main.c",
    ],
    copts = [
        "--coverage",
    ],
    linkopts = [
        "--coverage",
    ]
)

```

### What operating system are you running Bazel on?

Linux/CentOS7

### What's the output of `bazel info release`?

release 3.4.1- (@non-git)

###  Have you found anything relevant by searching the web?

Only questions/answers related to cc_test coverage. Not for cc_binary/cc_library instrumentation

**Comment by qwerty123443** [comment]
any updates on this? I'm running into the same issue

**Comment by avielas** [comment]
you can use --collect_code_coverage flag with bazel build/run to generates the GCNO files under bazel-out directory.
see here:
https://docs.bazel.build/versions/main/command-line-reference.html#flag--collect_code_coverage

**Comment by UlrichEckhardt** [comment]
I think this and #15646 are different views on the same underlying problem.
