### ISSUE TITLE
Bazel CI: Tulsi broken in downstream

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#12102]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1646#1191460e-5611-4c21-b712-4a4ecf0d2d8e
```
(04:05:35) ERROR: /Users/buildkite/builds/bk-imacpro-18/bazel-downstream-projects/tulsi/src/TulsiGeneratorIntegrationTests/BUILD:48:23: every rule of type macos_unit_test implicitly depends upon the target '@bazel_tools//tools/objc:gcov', but this target could not be found because of: no such target '@bazel_tools//tools/objc:gcov': target 'gcov' not declared in package 'tools/objc' defined by /private/var/tmp/_bazel_buildkite/8213825f69f7d2f09ff921d51ae435bf/external/bazel_tools/tools/objc/BUILD
(04:05:35) ERROR: /Users/buildkite/builds/bk-imacpro-18/bazel-downstream-projects/tulsi/src/TulsiGeneratorIntegrationTests/BUILD:48:23: every rule of type macos_unit_test implicitly depends upon the target '@bazel_tools//tools/objc:mcov', but this target could not be found because of: no such target '@bazel_tools//tools/objc:mcov': target 'mcov' not declared in package 'tools/objc' defined by /private/var/tmp/_bazel_buildkite/8213825f69f7d2f09ff921d51ae435bf/external/bazel_tools/tools/objc/BUILD
```

Probably caused by https://github.com/bazelbuild/bazel/commit/f8b51ffc2a8a953f64657ae4a21c9e1f1793dae2

**Comment by jmmv** [comment]
Yes, f8b51ff is most likely the cause. We should probably roll that back until Tulsi is fixed...

cc @trybka @DavidGoldman

**Comment by trybka** [comment]
Rollback seems reasonable to me. Surprised that wasn't caught in CI during
presubmit...

**Comment by DavidGoldman** [comment]
On the Tulsi side we'd need to make sure that the new tools/objc targets are available in the mock workspace which seems a bit tricky.

**Comment by trybka** [comment]
We could just revert the gcov/mcov targets?

**Comment by DavidGoldman** [comment]
Ah I missed that, yeah it does seem like a breakage in `macos_unit_test`, but it looks like that was removed in rules_apple in https://github.com/bazelbuild/rules_apple/commit/9822cfe2cf5347198413bd7427adb51c9d0179a5. This might just be a versioning issue using the new Bazel with an older rules_apple?

**Comment by meteorcloudy** [comment]
Yes, I think eventually the solution is for Tulsi to update the rules_apple version. But we should remove the dead code after Tulsi migrated in order not to cause breakage in downstream.

**Comment by DavidGoldman** [comment]
Yeah, that should need to be updated here: https://github.com/bazelbuild/tulsi/blob/e890fb6c88846454c4f69abd8d265a302c0e80e4/WORKSPACE#L5.

But not removing the gcov/mcov targets for now makes sense

**Comment by keith** [comment]
Here's the fix, but yea if we want to not remove those for now that's fine https://github.com/bazelbuild/tulsi/pull/175

**Comment by keith** [comment]
Not removing those for now is likely safer because other projects with upstream tests could use rules_apple and therefore would also be broken. It's too bad there's not a better way to do this in lockstep.

**Comment by keith** [comment]
Given https://github.com/bazelbuild/continuous-integration/commit/4a79466336de761bd28d00065d3791938c5b5d10 maybe it's only tulsi that's broken? In which case maybe it's fine to fix it forward?

**Comment by keith** [comment]
Here's a partial rollback for these empty scripts https://github.com/bazelbuild/bazel/pull/12103

New plan is to do a release with rules_apple that doesn't reference these, give users some time to update, and then remove these in the future

**Comment by meteorcloudy** [comment]
Thanks for the fix, I'll reenable Tulsi in downstream now.
