### ISSUE TITLE
build with gcc/windows

### ISSUE THREAD

**Issue by peter197321** [bazelbuild/bazel#12100]
I've got running gcc/g++ compiler on Win10 machine...

```
Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\> gcc --version
gcc.exe (Rev1, Built by MSYS2 project) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

PS C:\> g++ --version
g++.exe (Rev1, Built by MSYS2 project) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

PS C:\> bazel version
Build label: 3.5.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Sep 2 20:16:28 2020 (1599077788)
Build timestamp: 1599077788
Build timestamp as int: 1599077788

```

I'd like to set a project build with this compiler. How can I get info on which compiler is applied or how to set up this compiler for the C/C++ project build?

**Comment by meteorcloudy** [comment]
Looks like you have gcc installed via MSYS. Bazel supports building with MSYS gcc compiler via `--compiler=msys-gcc`.
See https://github.com/bazelbuild/bazel/blob/master/tools/cpp/BUILD.windows.tpl#L55

**Comment by peter197321** [comment]
Is that possible to have gcc/windows10 which installed with MSYS, to be used in Bazel?

**Comment by meteorcloudy** [comment]
Yes, `--compiler=msys-gcc` should make the gcc installed with MSYS2 work. 
Does `c:\msys64\usr\bin\gcc` actually exist?

**Comment by peter197321** [comment]
I do have gcc :)

**Comment by meteorcloudy** [comment]
Oh, I see, maybe you only have the mingw gcc installed. Can you try with `--compiler=mingw-gcc`?

**Comment by peter197321** [comment]
> Executing task: bazel build //main:hello-world --compiler=mingw-gcc -c dbg 

> FATAL: corrupt installation: file 'C:\_bazel_nxa18908\install\5ae8cabc4b9be067994d8893f859e371\A-server.jar' is missing or 
> modified.  Please remove 'C:/_bazel_nxa18908/install/5ae8cabc4b9be067994d8893f859e371' and try again.
> The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command bazel build //main:hello-
> world --compiler=mingw-gcc -c dbg" terminated with exit code: 1.

**Comment by peter197321** [comment]
I have installed MSYS2, gcc under 64-bit environment.

**Comment by meteorcloudy** [comment]
Did you somehow touched `C:/_bazel_nxa18908/install/5ae8cabc4b9be067994d8893f859e371`? If so, you have to completely delete this directory, otherwise Bazel will complain its installed directory is modified.

**Comment by peter197321** [comment]
OK - deleted - now build. Thank you!

How about to debug?

**Comment by meteorcloudy** [comment]
> OK - deleted - now build. Thank you!

Great!

> How about to debug?

Sorry I don't have any knowledge about configuring debug in VS Code.

**Comment by carlosedubarreto** [comment]
@peter197321 @meteorcloudy 
I found this instructions on how to use with vscode. I didnt test it
https://medium.com/swlh/configuring-bazel-build-with-gnu-c-c-on-windows-e27b2c66bed6
