### ISSUE TITLE
Mutiple projects with one WORKSPACE

### ISSUE THREAD

**Issue by yfheng** [bazelbuild/bazel#12101]
Current I have multiple projects share with one WORKSPACE, so I put all package in the WORKSPACE file
The problem is every time when I  build projectA, it would download unnecessary packages which may use by projectB

Is there any way that Bazel manage them without downloading unnecessary packages

**Comment by jin** [comment]
> The problem is every time when I build projectA, it would download unnecessary packages which may use by projectB

If you have a way to reproduce this, that would be great. Bazel would not download external dependencies unless the requested targets to build transitively depends on them. 

Closing as there is not enough information to proceed further.
