### ISSUE TITLE
Documentation issue: Concepts and terminology

### ISSUE THREAD

**Issue by bduffany** [bazelbuild/bazel#12107]
Documentation URL: https://docs.bazel.build/versions/3.5.0/build-ref.html

This page references the term "rule" (in the repositories section) before defining what a rule is.

**Comment by gregestren** [comment]
Candidate for a glossary link? https://docs.bazel.build/versions/master/glossary.html#rule

**Comment by bduffany** [comment]
I feel like that would break the linear flow of that article, since the `Rule` is such a central concept.

**Comment by philwo** [comment]
@sventiffe Can we have a `team-Documentation` and our tech writers on GitHub so that they could directly look into this? I don't think this is really actionable for my team, but I also don't know a better team to assign it to. 🤔

**Comment by sventiffe** [comment]
Yes, this sounds plausible. I'll take this one for the time being as well.

**Comment by gregestren** [comment]
Let's get @floriographygoth's input on this as a next step.
