### ISSUE TITLE
Duplicate file uploads over gRPC

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#12113]
### Description of the problem / feature request:

Bazel does not deduplicate file uploads across actions, so it may attempt multiple uploads of the same content in parallel. If these are large files, then this causes significant network overhead.

For remote builds of TensorFlow over the public internet, this makes the build take a very long time.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
[genrule(
  name = "bar-%s" % i,
  srcs = ["input.txt"],
  outs = ["bar-%s.txt" % i],
  cmd = "cp $< $@",
) for i in range(0, 100)]
```

Enable a remote gRPC cache or executor.

### What operating system are you running Bazel on?

Linux.

###  Have you found anything relevant by searching the web?

This was previously also reported here, but I could not find a matching bug report:
https://github.com/bazelbuild/remote-apis/pull/131#issuecomment-615312235

@EdSchouten

**Comment by ulfjack** [comment]
I have a patch to deduplicate uploads, which has shown significant reductions in build times across a number of different builds and network configurations.

**Comment by ulfjack** [comment]
My patch is here: https://github.com/ulfjack/bazel/tree/blob-existence-cache

I am currently in the process of cleaning it up and splitting it into smaller PRs.

**Comment by moroten** [comment]
I have been using (a rebased variant of) https://github.com/moroten/bazel/commits/optimize-remote-execution for a while now. With these patches, I usually run into limited CPU capacity on my laptop, with no network or remote execution limitations.

One part of the patch chain is the in memory caches, which I've put command line options to adjust the size of. That seems like a clumsy solution, it would be better to automatically scale the size according to available memory. @ulfjack What are your thoughts about the memory management? I see that you use `ConcurrentHashMap` on your branch as well.

**Comment by ulfjack** [comment]
We haven't seen any memory issues so far, but you're right @moroten, it's probably a good idea to limit memory use. I don't have a good proposal at this time.

**Comment by moroten** [comment]
We keep the Bazel server running "forever" on our CI servers, so we will eventually fill the memory. One idea we have is to port our C++ rules to Starlark and thereby avoid loading .d files. That will mean that I can turn off the CAS and the memory footprint of the AC can increase.

Is one option to have a command line flag saying either specify number of bytes to use or, if specified with % suffix, a percentage of available memory when the Bazel server starts? How is the memory management handled more generally in Bazel?

**Comment by ulfjack** [comment]
In the patch we're using, the cache is dropped after every build, so it shouldn't keep growing over a sequence of builds.

**Comment by moroten** [comment]
I see, that solves your use case. In my case, I want to keep information between builds, also when the user switches between compilations options that invalidates the analysis cache.

**Comment by ulfjack** [comment]
Oh, I think you may have misunderstood - we only drop the upload cache, not the analysis cache or any of the other cross-build caches.
