### ISSUE TITLE
Advice on testing bazel trunk

### ISSUE THREAD

**Issue by luxe** [bazelbuild/bazel#12116]
### Description of the problem / feature request:

We'd like to test the latest commits of bazel prior to releases.  This will help us catch upgrade issues early.
Building from source was easy, thanks! [(docs)](https://docs.bazel.build/versions/master/install-compile-source.html)  
```
git@github.com:bazelbuild/bazel.git
bazelisk build //src:bazel-dev
```

Would this be the ideal way to test the latest bazel, or if you have any other general advice in doing so?
I suppose we'll use `--compilation_mode=opt` also, since we intend to observe any performance changes.

I noticed that the dev builds don't have a version.  
```
./bazel-bin/src/bazel-dev --version
[FATAL 19:06:49.404 src/main/cpp/archive_utils.cc:67] Failed to find member 'build-label.txt' in zip file '/proc/self/exe'
```

Hopefully, that's expected, but let me know if you think we should change that.  Maybe have it say dev-{SHA} or something.
This works:  
```
./bazel-bin/src/bazel-dev info release
Starting local Bazel server and connecting to it...
development version
```

**Comment by jin** [comment]
You can look at the exact set of test targets Bazel CI runs on postsubmit here: https://github.com/bazelbuild/bazel/blob/master/.bazelci/postsubmit.yml

**Comment by ulfjack** [comment]
You can build a dev release like so:
```
bazelisk build -c opt --embed_label=dev-${SHA} //src:bazel
```

I'd recommend not to use `//src:bazel-dev` as it may not accurately reflect the release (the main difference is in how much of the JDK is embedded into the binary).

**Comment by meisterT** [comment]
Instead of building your own bazel binary, you can use bazelisk with `USE_BAZEL_VERSION=last_green`, see https://github.com/bazelbuild/bazelisk#how-does-bazelisk-know-which-bazel-version-to-run

**Comment by luxe** [comment]
thanks all.  Bazelisk is the easiest to integrate with its latest_* options.
we'll only build from source if we need to test something not landed
