### ISSUE TITLE
Unmount sandboxfs if we detect that it was left behind by a killed Bazel instance

### ISSUE THREAD

**Issue by Mathiasdm** [bazelbuild/bazel#12151]
### Description of the problem / feature request:

When interrupting Bazel with multiple Ctrl-C's, sandboxfs gets in a stuck state in the next builds. You need some (bad) luck: you need to press Ctrl-C fast enough to get this issue.

Interrupted build:
```
ERROR: build interrupted
[2,301 / 2,771] checking cached actions
^C
Bazel caught interrupt signal; shutting down.
[2,301 / 2,771] checking cached actions
^C
Bazel caught third interrupt signal; killed.

^C
Bazel caught third interrupt signal; killed.

^C
Bazel caught third interrupt signal; killed.

```

Later build:

```
INFO: Analyzed 543 targets (364 packages loaded, 31859 targets configured).
INFO: Found 543 test targets...
INFO: Deleting stale sandbox base /repo/mdemare/bazel-cache/sw/sandbox
ERROR: Failed to initialize sandbox: fchmodat(/repo/mdemare/bazel-cache/sw/sandbox/sandboxfs) (Transport endpoint is not connected)
INFO: Elapsed time: 13.788s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Start Bazel with sandboxfs, press Ctrl-C a bunch of times in a short time period.

### What operating system are you running Bazel on?

Linux, CentOS 7

### What's the output of `bazel info release`?

release 3.5.0

###  Have you found anything relevant by searching the web?

This bug seemed related (but already fixed): https://github.com/bazelbuild/bazel/issues/5271

### Any other information, logs, or outputs that you want to share?

I can workaround it by manually unmounting the sandboxfs filesystem. But it's still annoying for users.

**Comment by meisterT** [comment]
Cc @jmmv

**Comment by jmmv** [comment]
Can you define "stuck state?

Do you mean that sandboxfs is left mounted and you have to manually unmount it for the next Bazel to work?

This is kinda... normal. If you forced Bazel to exit with repeated Ctrl+Cs, then Bazel does not have a chance to unmount sandboxfs and it will be left behind.

If that's the case, we probably should add some extra logic to attempt to unmount the sandboxfs instance if it's found to be already mounted.

**Comment by Mathiasdm** [comment]
With stuck state, I indeed mean that a manual unmount is needed for the next Bazel call to work.

I understand this is normal behaviour, but it would indeed be more user-friendly if Bazel would be able to handle this by doing the unmount at startup.

In our case, we now do the unmount as part of a Bazel wrapper.

**Comment by sketchc89** [comment]
What are you actually unmounting when you manually unmount sandboxfs? I ran into the same error, but looking at `/proc/mounts` I don't see sandboxfs or anything like it.
