### ISSUE TITLE
how to specify platforms while querying 

### ISSUE THREAD

**Issue by CaichaoGitHub** [bazelbuild/bazel#12152]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

i wanted to query the dependencies at specific target and platform , but i did not know how to specify platforms while querying ;

if i queried target's dependencies by default , the bazel would complain platforms' errors , so i need to specify platforms while querying

My command is at blew:
bazel query "deps(mediapipe/examples/desktop/autoflip:run_autoflip)"

### What operating system are you running Bazel on?

MAC OS .

### What's the output of `bazel info release`?

bazel 2.1.1-homebrew

###  Have you found anything relevant by searching the web?

i  searched google , github issue and stackoverflow 

### Any other information, logs, or outputs that you want to share?

ERROR: /Users/xx/Documents/Code/Github/mediapipe/third_party/BUILD:178:1: no such package '@windows_opencv//': The repository's path is "C:\opencv\build" (absolute: "/Users/xx/Documents/Code/Github/mediapipe/C:\opencv\build") but this directory does not exist. and referenced by '//third_party:opencv_binary'
ERROR: /Users/xx/Documents/Code/Github/mediapipe/mediapipe/util/BUILD:93:1: no such package '@androidndk//': Either the path attribute of android_ndk_repository or the ANDROID_NDK_HOME  environment variable must be set. and referenced by '//mediapipe/util:cpu_util'

**Comment by katre** [comment]
Bazel's `query` command is not aware of configurations, such as the target platform, or other flags. You might want to use `cquery`, which is aware of the configuration, and uses the same set of flags as `bazel build`. See the docs on [`query` vs `cquery`](https://docs.bazel.build/versions/master/configurable-attributes.html#bazel-query-and-cquery) for more details on how they are different.

Your error, however, is not related to `query`: you have errors in your WORKSPACE. Specifically, it looks like you haven't set up the `@windows_opencv` repository correctly (the path seems to be invalid), and you are referencing the `@androidndk` repository but haven't defined where that is located.

**Comment by CaichaoGitHub** [comment]
> Bazel's `query` command is not aware of configurations, such as the target platform, or other flags. You might want to use `cquery`, which is aware of the configuration, and uses the same set of flags as `bazel build`. See the docs on [`query` vs `cquery`](https://docs.bazel.build/versions/master/configurable-attributes.html#bazel-query-and-cquery) for more details on how they are different.
> 
> Your error, however, is not related to `query`: you have errors in your WORKSPACE. Specifically, it looks like you haven't set up the `@windows_opencv` repository correctly (the path seems to be invalid), and you are referencing the `@androidndk` repository but haven't defined where that is located.

thanks for replay 
the project is a cross platform project [mediapipe](https://github.com/google/mediapipe) ,  if i am working on my mac , i can't configure the windows and android environment , 
anyway ,
