### ISSUE TITLE
Add support for C++ precompiled headers

### ISSUE THREAD

**Issue by ip** [bazelbuild/bazel#1215]
This is very important, please implement it at least for GCC/Clang.
Handy pages:
- https://gcc.gnu.org/onlinedocs/gcc/Precompiled-Headers.html
- https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html

**Comment by ip** [comment]
I managed to use a workaround for now, something like this:

1. `alias bzb="bazel build //my_target"`
1. `bzb -s --spawn_strategy=standalone`
1. We need to compile precompiled headers with the same options as source files. From output of previous command, find a line compiling any of .cpp files from `//my_target` (should start with `/usr/bin/gcc`)
    - Remove options: `-Wl,...`, `-o /output/path`
    - Replace `-c /input/path` by path of your precompiled header
    - Add `-x c++-header`
1. After executing this command, .h.gch file should be generated in the same directory as input .h.
1. Check if compile use our new .h.gch instead of original .h:
    - Add to your cc_binary/cc_library rule: `copts = ["-H"]`
    ```
    bazel clean
    bzb --spawn_strategy=standalone
    ```
    - In the output, in case of success there must be `!` before our header and `x` in case of failure. From `man gcc`:
    ```
   -H  Print the name of each header file used, in addition to other normal
       activities.  Each name is indented to show how deep in the #include stack
       it is.  Precompiled header files are also printed, even if they are found
       to be invalid; an invalid precompiled header file is printed with ...x
       and a valid one with ...! .
    ```

**Comment by ulfjack** [comment]
For Clang, we're supporting modules, which - according to our testing - performs better than precompiled headers, but requires a recent Clang version. We don't currently have any plans to support precompiled headers for GCC. We investigated it, but IIRC, there were a number of problems, including that the precompiled headers were non-deterministic, because GCC simply did a memory dump of its inmemory data structures. This was a while ago, and I may misremember.

Maybe you can give some background as to why you're interested in precompiled headers?

**Comment by ip** [comment]
Ok, that sounds reasonable, you can close it.

**Comment by yasushi-saito** [comment]
Is the clang modules support already present in blaze, or is it just planned? I see some support for Objective C in the source code, but not for C or C++

**Comment by jgavris** [comment]
+1, are there any efforts planned to add support for `-fmodules` for C/++?

**Comment by ulfjack** [comment]
It's all there already, I believe, although I can't say off the top of my head how to enable it in Bazel, and it requires a fairly recent version of Clang.

**Comment by stefan1000** [comment]
Are there any workarounds to somehow use precompiled headers (MSVC) ? Using boost and other header-heavy libraries we see a good performance improvement using PCHs, and we are far from porting to clang and modules....we still include all the headers (in cpp as well as in precompiled header files, which are autogenerated from the sources), so up-to-date checks. should be ok.

**Comment by keith** [comment]
FYI for folks who are interested in rolling their own here, here's an example  https://github.com/envoyproxy/envoy/pull/13788
