### ISSUE TITLE
Improved Jacoco coverage support

### ISSUE THREAD

**Issue by dorranh** [bazelbuild/bazel#12159]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

I'd like to discuss/request a feature which improves coverage support for developers of rules for JVM languages: a new format for Bazel's internally-used `-paths-for-coverage.txt` file.  I've experimented with an implementation of this feature request, but wanted to get some general feedback from you all before submitting a PR since you may have other ideas for solving this problem.

cc @iirina 

### Feature requests: what underlying problem are you trying to solve with this feature?

When providing uninstrumented JVM class files to the Jacoco coverage methods used by `bazel coverage`, `JacocoCoverageRunner` looks for an optional `-paths-for-coverage.txt` in the input JAR which provides a list of source files to be used when computing line coverage [(source)](https://github.com/bazelbuild/bazel/blob/master/src/java_tools/junitrunner/java/com/google/testing/coverage/JacocoCoverageRunner.java#L264). 

This works as expected for Java, where the source and JAR directory trees have the same structure, but will work unexpectedly in cases where the source and JAR trees have different structures, which is possible in other JVM languages like Scala or Kotlin. In these cases, line coverage is omitted for sources which reside in a different file tree than what their package specifies. 

For example, `rules_scala` constructs a `-paths-for-coverage.txt` with the true paths to the source files when calling Bazel's java toolchain, but the `JacocoLCOVFormatter` fails to match the source and class files when a source resides in a different directory than its declared package. See https://github.com/bazelbuild/rules_scala/issues/1101 for a longer discussion.

A possible solution is an updated format for `-paths-for-coverage.txt` which allows rule authors to optionally specify the mapping between source and JAR paths (e.g. allow for `jar_path:src_path` entries in addition to the current `src_path` entries). While this could be patched downstream on the rules_scala end, I think this feature is generally useful for other languages like Kotlin, which have [yet to implement](https://github.com/bazelbuild/rules_kotlin/issues/300) code coverage using Bazel, and worthwhile to incorporate into the main java toolchain.  

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See https://github.com/sjoerdvisscher/bazel-scala-tests for an example of missing line coverage with rules_scala + Scala

### What operating system are you running Bazel on?

Ubuntu 18.04.5 LTS

### What's the output of `bazel info release`?

release 3.5.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
    git@github.com:bazelbuild/bazel.git
    f426564613e1f40210b947909a5f859e8d68eb14
    f426564613e1f40210b947909a5f859e8d68eb14

**Comment by sjoerdvisscher** [comment]
Note that this problem also applies to Java. I have updated https://github.com/sjoerdvisscher/bazel-scala-tests to show this.

**Comment by comius** [comment]
This sounds like a reasonable solution. Currently we are not focusing on coverage work, but we would be happy to accept PRs.

**Comment by emise** [comment]
Is this issue fixed? We're looking to set up Kotlin coverage tests, and we're running into the same problem of not finding source files

**Comment by dorranh** [comment]
@emise, the core support for this was added in #12627, but I'm not sure if the rules for Kotlin are leveraging this feature. Last time I checked `rules_scala` had also yet to add support for it.

**Comment by avbhandaru** [comment]
Closing the loop on this one, five years late: @dorranh noted above that the core support landed in #12627 but that `rules_scala` had never adopted it. That is still true, so I have opened [bazel-contrib/rules_scala#1967](https://github.com/bazel-contrib/rules_scala/pull/1967) to make `JacocoInstrumenter` emit the `<real source path>///<class-derived path>` mappings, which fixes [bazel-contrib/rules_scala#1101](https://github.com/bazel-contrib/rules_scala/issues/1101).

No change is needed in Bazel — the mapping format works as designed. Noting it here in case anyone lands on this issue looking for the Scala side, and since `rules_kotlin` was mentioned above as being in the same position.
