### ISSUE TITLE
Global max worker instances limit

### ISSUE THREAD

**Issue by viveksjain** [bazelbuild/bazel#12165]
### Description of the problem / feature request:

Provide some way to provide a global limit on worker instances across all instance types, shutting down older workers as needed.

### Feature requests: what underlying problem are you trying to solve with this feature?

In our large multi-language repo, if we run `bazel build //...`, the workers usually OOM crash (causing build to fail) because each one takes 1GB+ of memory, they are never shutdown in the middle of a build command, and combined it's too much memory. We could limit each worker type to a very small concurrency (like 1) with `worker_max_instances` but that seems like it would affect performance (and still doesn't address the root issue that total workers is unbounded). Ideal behavior would be maintaining a list of workers capped at some number (probably as much as our RAM can support), with some LRU-type scheme to shutdown older workers. I tried `--worker_max_instances=4` but this appears to limit each instance type to a max of 4, rather than enforcing that at any point in time, only 4 workers are alive.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 1.0.0
Can try an upgraded version if that might help but couldn't find anything in docs suggesting that.

**Comment by larsrc-google** [comment]
Hi Vivek,

Yes, --worker_max_instances sets the max number of instances per WorkerKey (~=mnemonic). If you have an unbounded number of WorkerKeys for a given mnemonic, you should fix that.

Do try with --worker_max_instances=1, some other users have found that to be the fastest, much to my surprise. 

Using multiplex workers would help, since there would then only be one actual process per WorkerKey. They're available for Java currently, though not enabled in the toolchain just yet.

Having an LRU-style cap would mitigate this, indeed. We're looking into how to cap resource usage for workers. It would be nice in this case if --workers_quit_after_build would actually quit as soon as the build no longer needs them. I'm not sure how easy that is to reason about, though.

**Comment by alexeagle** [comment]
I think we have another valid use case for this flag.

In rules_nodejs we have workers for a TypeScript compile rule (`ts_project`). Unlike the google3 TypeScript rule (`ts_library`) this doesn't run a custom bazel-specific compiler, but rather just the regular one shipped by the team at Microsoft. This is a vast simplification and reduction in scope for our team, and also makes it more obvious that any compiler for a compile-to-JS language works with Bazel, not requiring a herculean effort to write a custom compiler.

To make this work, we run a "linker" process that makes the third-party dependencies available to the compiler process before it runs. This means that a given process will always see that exact set of dependencies regardless of what WorkRequests come over stdin.

For this reason we think the right design is to have one Worker process per `ts_project` rule, though this goes against your wisdom "the root issue that total workers is unbounded" - we think this is actually a feature.

So we would like to have the LRU behavior of shutting down workers to save resources, as well as possibly switching the SpawnStrategy to non-worker if Bazel can tell that spawning a new worker process would exceed some limit.

**Comment by larsrc-google** [comment]
I'm not sure I follow. 

You want one worker per ts_project - how many ts_projects do you expect there to be? If there are more than the max number of global worker instances, you'll be doing a more complicated version of local execution, it seems. 

Does the "linker" process run as part of the worker? If not, where does it know the exact set of dependencies from? How does it handle changes in dependencies? 

I'm not sure why one would need a custom compiler in the first place, Java and C++ does not require that.

**Comment by larsrc-google** [comment]
Dropping some notes here from investigating better worker resource management: If workers were to hold on to their own resources (memory, essentially), we could risk all the resources eventually being held by workers and little progress becomes possible. Killing off idle workers would get us out of that, at the risk of cycling through creation and destruction of workers.

**Comment by alexeagle** [comment]
Sorry I missed your questions earlier

> how many ts_projects do you expect there to be
This is up to users. A large app that expects to compile every directory independently could have hundreds, but I would advise them against that. More typical in TypeScript to have a handful of them (we could look at how many "composite projects" VSCode has, as an example)

Yes, in a non-incremental build you'd have the deoptimization of acting like local/sandboxed execution. I think in a typical incremental build you'd only be rebuilding/typechecking up the spine from a leaf edit, which would more likely fit within the max worker processes. Of course we'd like Bazel's execution strategy heuristic to be the thing responsible for making incremental and non-incremental builds be scheduled appropriately.

The third-party dependencies are baked into the worker process, and if they change, then the worker itself has changed inputs and is restarted by Bazel.

And we totally have a custom JavaBuilder in Bazel :)

**Comment by larsrc-google** [comment]
I guess it's a matter of definition what counts as a custom compiler. 

So is the compiler process one that stays alive along with the worker process, and thus can avoid re-parsing/re-type-checking the third-party dependencies? And typically the third-party dependencies change much less often than first-party ones, yet are usually different between different ts_projects? Have you measured how much of a ts_project build step is repeatedly handling the third-party dependencies?

I'm trying to figure out if the third-party dependencies are different enough from first-party dependencies that it makes sense to entirely kill off a worker when they change. Then you'll have to reprocess all the third-party dependencies, not just the ones that changed. Does the compiler do something significantly different with the third-party dependencies, or is it just a matter of scale?

**Comment by facundominguez** [comment]
`rules_haskell` needs a global limit for the maximum amount of workers to make a persistent worker feasible. The details are discussed [here](https://github.com/tweag/rules_haskell/issues/1758).

In this use case, there is only one mnemonic, but there are multiple build configurations and multiple libraries, and each combination of library and build configuration requires a different persistent worker.

One could avoid modifying Bazel by asking the persistent worker to be smarter about dropping internal caches that are the least used, but the reality of GHC makes this a complex endeavor.

An alternative to limiting the total amount of workers could be to limit the total amount of physical memory given to persistent workers. So bazel would refrain from spawning more workers than can fit a memory limit, and would use a LRU cache to decide which workers to kill when new workers are needed and no space is left. But I regard this solution as harder to support across platforms.

> Do try with --worker_max_instances=1

Unfortunately, using `--worker_max_instances=1` leads to much lost parallelism when the build is waiting on a few libraries to build to unlock further actions.

**Comment by larsrc-google** [comment]
We're looking into doing exactly the total max memory thing you're suggesting. And that's not even that hard to support across platforms (except Windows).

**Comment by larsrc-google** [comment]
@wilwell has implemented a system for limiting workers to a given amount of memory, see flags `--experimental_total_worker_memory_limit_mb` and `--experimental_shrink_worker_pool`.

**Comment by smocherla-brex** [comment]
Any ideas if these flags (`--experimental_total_worker_memory_limit_mb` and `--experimental_shrink_worker_pool`) be available in an upcoming release? We're facing significant resource hogging of workers with rules_kotlin and rules_java when running lots of tests, and the only solution that prevents OOMs is using `--local_test_jobs=1` (and that reduces the parallelism of tests a lot). Even using `--worker_max_instances=1` didn't seem to help much. Switching off workers (with `--spawn_strategy=processwrapper-sandbox`) helped but slowdown in compilation was quite a bit, so we're hoping to use these flags if we could restrict the memory usage of workers.

**Comment by larsrc-google** [comment]
Yes, these flags will be part of the 7.0 release. @wilwell should we backport to a 6.X release?
