### ISSUE TITLE
Bazel fails to build when moving generated header file

### ISSUE THREAD

**Issue by tobbe76** [bazelbuild/bazel#12169]
### Description of the problem / feature request:
Build fails when moving location of a generated header file, the header file is still present in bazel-out under its old location. 
The compiler will take the header file that is first in the include search paths.

When used together with a cache it's very hard to clean up after the error has occurred.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Generate a gen_header.h file into inc/ folder.
2. Build c file that include "gen_header.h"
3. Move header file to src/ folder
4. Build again now the build fails.

BUILD:32:10: undeclared inclusion(s) in rule '//:test':
this rule is missing dependency declarations for the following files included by 'src/main.c':
  'bazel-out/x64_windows-fastbuild/bin/inc/gen_header.h'

Small example:
git clone https://github.com/tobbe76/gen_hdrs.git
bazel build //:test -s --//:hdr_destination=inc
bazel build //:test -s --//:hdr_destination=src

### What operating system are you running Bazel on?

Windows 10, no sandbox

### What's the output of `bazel info release`?

release 3.5.0

###  Have you found anything relevant by searching the web?

Nothing found:

**Comment by oquenchil** [comment]
If it's a generated file under bazel-out/ you cannot move it.
