### ISSUE TITLE
timezone in sandbox

### ISSUE THREAD

**Issue by cnsgsz** [bazelbuild/bazel#1216]
my code use mktime to convert time of the day to epoch time, which implicitly relies on machine's timezone, which is different from sandbox's timezone. that causes some regression tests to fail as the "correct" output is generated not in the sandbox. adding local=1 to build rule for the test didn't seem to make a difference.

proper way is probably for me to get rid of my code's implicit dependency on machine timezone, but is there some setting in bazel to resolve that for now (e.g. setting sandbox timezone, easily generate "correct" file in sandbox)?

**Comment by damienmg** [comment]
The timezone is set through environment variable so setting those environment variables in your test should be the correct one.

I'll leave this open but I think we cannot do much here.

**Comment by cnsgsz** [comment]
that makes sense. thanks!
