### ISSUE TITLE
Allow rule attributes to be a list of lists of strings

### ISSUE THREAD

**Issue by chandlerc** [bazelbuild/bazel#12178]
### Description of the feature request:

Currently, rule attributes can be a list of strings (`string_list`) or a dictionary of lists of strings (`string_list_dict`), but not a list of lists of strings (maybe `string_list_list`?). I'd like to see that last one added.

### Feature requests: what underlying problem are you trying to solve with this feature?

At least for a `repository_rule` it is often useful to pass a list of lists. For example, list of possible `linkopts` to use, where each candidate is, itself, a list.

### Alternative

Alternatively, document how I can provide a custom schema for an attribute.

**Comment by benjaminp** [comment]
https://cs.opensource.google/bazel/bazel/+/c924b4d42a4e74975bf9f96a4ea978682f147915:src/main/java/com/google/devtools/build/lib/packages/Type.java;l=57-80

**Comment by Monnoroch** [comment]
Perhaps a more productive solution would be to add a proper generic list type. Something like `attr.list_of(attr.string)`.

**Comment by oquenchil** [comment]
Going by the comment linked by Benjamin above I will close this feature request. There are alternatives and it seems the benefits of adding a new type are not worth the cost.
