### ISSUE TITLE
cpp regression test framework in bazel?

### ISSUE THREAD

**Issue by cnsgsz** [bazelbuild/bazel#1217]
I am trying to use bazel for regression-style tests for my cpp project. the workflow is like run some binary, and compare its output -- either cout or file, to some "correct" ones.

it seems my options are either: have some system("diff correct.txt new.txt") at the end of my cpp_test program, or: use some cpp binary to generate the output and then a dependent py_test rule to compare the outputs. 

since regression test might be a widely-used feature, and what I can thought of above is adhoc and inconvenient (e.g. repeated boiler plate code for different regression tests, need to manually generate "correct" files and add those to some build rule's data -- and the "correct" file generated outside sandbox can differ from those generated inside  #1216), is there a better way to do regression-style testing with bazel that I am missing?

**Comment by damienmg** [comment]
We use shell tests in google for the same thing (wrapped around a skylark rules) and that works pretty well. What would you want to see?

**Comment by cnsgsz** [comment]
is it possible to open source the skylark rule for shell tests?

**Comment by damienmg** [comment]
There is not one skylark rule per se, the projects that does that inside Google use a custom skylark macros to avoid boilerplate. I don't think this requires any feature from Bazel itself.

It would be something like compare_output(name = "regression_test", tool = ":my_binary", golden = "in.txt") that will generate a sh_test calling my_binary and diffing the output. So it just the process you proposed but wrapped in a specific macros to avoid boilerplate.

**Comment by cnsgsz** [comment]
is it possible to post some example here?

**Comment by damienmg** [comment]
Sorry it felt off my radar. I don't have ready to use example so I'll recategorize that as a documentation issue.

**Comment by oquenchil** [comment]
shell_tests are documented here:
https://docs.bazel.build/versions/master/be/shell.html#sh_test

In the example the `data` attribute is used. There you can pass whatever you want, even a binary that you then run inside the test.
