### ISSUE TITLE
`--instrument_test_targets` doesn't apply if source rule and test rule are split

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#12176]
When using `--instrument_test_targets=false` (the default), sources from test target's single dep are not excluded. This affects test targets which do not accept `srcs`.

For example if you have this setup:

```bzl
objc_library(
    name = "lib",
    testonly = True,
    srcs = ...
)

ios_unit_test(
...
    deps = ["lib"]
)
```

The sources from `lib` will still be instrumented even though they are actually test sources.

Ideally there would be some way to exclude these source files from instrumentation (outside of changing the `--instrumentation_filter` which isn't always ergonomic to do) for cases where source rules and test rules are split.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 3.5.0

**Comment by oquenchil** [comment]
I don't see how Bazel could ever know that's the behavior you want without introducing yet another flag. Since the instrumentation filter flag should work for that I will close this bug for now. Feel free to re-open if you come up with a way that wouldn't add much more complexity.

**Comment by ulfjack** [comment]
I think the existing `--instrument_test_targets` flag should *also* consider the `testonly` flag. That seems like it may be sufficiently close to current semantics without too much of a migration period.

**Comment by keith** [comment]
+1 to that option, alternatively a tag could work for this.

I find that working in these detached source and test targets actually need this knowledge quite a bit, for example to compile a bit differently including paths to test dependencies you don't also want to leak into production builds. Currently in rules_apple / rules_swift we do use `testonly` for this.

> Since the instrumentation filter flag should work for that

I was getting at the issue with this above, but what is the solution to having hundreds of modules you want to filter this way? For example a source tree with:

```
a/BUILD
a/srcs
a/tests
b/BUILD
b/srcs
b/tests
```

Where you want to test `a` and `b` would require a target entry for each module, which doesn't scale well. I can see this would be more doable if you had:

```
srcs/a/BUILD
srcs/b/BUILD
tests/a/BUILD
tests/b/BUILD
```

But not all projects will make sense to lay out this way.

**Comment by keith** [comment]
I wonder if another option for this info is to use a `features = ["test_target"]`? The interesting thing about `testonly` is you could have `testonly` targets that you still want coverage info for. In our case this is running the unit tests against a "test helpers" type module. The "test helpers" module is `testonly = True,` but we still want to see coverage for it when running its own unit tests. In this case we don't want to change the semantics by flipping it to `testonly = False`.

**Comment by alokpr** [comment]
This affects `testonly` `cc_library` rules as well. Any hope for bumping the priority or a workaround in the meantime?
