### ISSUE TITLE
Bazel should provide an error message if it can't write to the output base

### ISSUE THREAD

**Issue by nickgeorge** [bazelbuild/bazel#12183]
### Description of the problem / feature request:

I've hit a failure mode where any bazel command just hangs, except for bazel --version (3.4.1)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

bazel info release

### What operating system are you running Bazel on?
linux (glinux workstation)

### What's the output of `bazel info release`?

hangs indefinitely

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

$ git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
fatal: No such remote 'origin'
2ec81d37eab0e9ca799b275eda95dbd4706c435a
2ec81d37eab0e9ca799b275eda95dbd4706c435a

###  Have you found anything relevant by searching the web?
no

### Any other information, logs, or outputs that you want to share?

Recently reimaged machine so it's possible that somethings wrong on my end, but it's a failure mode that bazel gives no help debugging.

**Comment by keith** [comment]
Can you test out the `SIGQUIT` instructions mentioned here https://docs.bazel.build/versions/3.5.0/guide.html and provide the stack trace it reports?

**Comment by nickgeorge** [comment]
Tried runnign `kill -3 $(bazel info server_pid)` but it doesn't return, because.... bazel info hangs indefinitely

**Comment by nickgeorge** [comment]
in case it's relevant, 
^\kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]

**Comment by keith** [comment]
this wouldn't cause it to return, just to write some extra info to the file mentioned in the docs

**Comment by nickgeorge** [comment]
Ah gotcha.  Do you know what `$(bazel info output_base)` should resolve to on glinux?  I can't find the file because `bazel info` doesn't return :(  I also don't see any generated bazel-out/in/genfiles directories

**Comment by nickgeorge** [comment]
Not sure I understand how to follow this:
`Since you may not be able to run bazel info if bazel is hung, the output_base directory is usually the parent of the bazel-<workspace> symlink in your workspace directory.`

My WORKSPACE is /tmp/fhir/WORKSPACE, and I don't see any bazel-out/bin/genfiles directories getting created

**Comment by nickgeorge** [comment]
That workaround has stopped working.  I'm pretty jammed here, unable to build any targets even after entirely uninstalling and reinstalling bazel

**Comment by meisterT** [comment]
Can you use `strace` to see where it hangs?

**Comment by jmmv** [comment]
If `bazel info` hangs, Bazel is most likely already running (unless we are hanging in the client). Use `ps ax` to find the PID of the Bazel server process and then use `jstack PID` to get the state of that server.

**Comment by philwo** [comment]
Closing this, as we haven't heard back in a while. Please comment on this issue if you can provide strace or jstack output of the hanging process.
