### ISSUE TITLE
Runfile path needs to be specified with leading '__main__' prefix

### ISSUE THREAD

**Issue by JanJamaszyk-FlyNow** [bazelbuild/bazel#12186]
As described in https://github.com/bazelbuild/bazel/issues/11212#issuecomment-619418866
We need to append a leading `__main__` to our relative path in order to reference data dependencies from our tests:
```
std::unique_ptr<Runfiles> runfiles(Runfiles::Create(argv[0], &error));
std::string path = runfiles->Rlocation("__main__/relative_path");
```
This looks like a python artifact and should likely be appended inside the `runfiles->Rlocation` function.

**Comment by driftregion** [comment]
I am seeing the same issue on linux, bazel 5.4.1.  I am attempting to locate executables produced by `cc_binary`, declared under the `data` attribute of a `py_binary`


```py
from python.runfiles import runfiles
r = runfiles.Create()

# yields invalid path to target
target = r.Rlocation("x/y/z/target")

# yields valid path to target
target = r.Rlocation("__main__/x/y/z/target")
```

I see the same behavior on two versions of rules_python: 0.12.0 and 0.31.0 (most recent at time of writing).
