### ISSUE TITLE
Fish completion complete: -l requires a non-empty string

### ISSUE THREAD

**Issue by uri-canva** [bazelbuild/bazel#12207]
### Description of the problem / feature request:

When sourcing fish completions:

```
complete: -l requires a non-empty string
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Source fish completions.

### What operating system are you running Bazel on?

> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2

> fish --version
fish, version 3.1.2

### What's the output of `bazel info release`?

release 3.3.0

###  Have you found anything relevant by searching the web?

Issue requesting fish completions: https://github.com/bazelbuild/bazel/issues/5088
Initial implementation: https://github.com/bazelbuild/bazel/pull/11450/files

### Any other information, logs, or outputs that you want to share?

This is caused by leading whitespace in lines from the output of `bazel help` being split with `string split ' ' $line`, and can be fixed by passing `--no-empty` like `string split --no-empty ' ' $line`.

**Comment by uri-canva** [comment]
cc @tmandry @akirabaruah

**Comment by akirabaruah** [comment]
@uri-canva were you able to verify whether adding `--no-empty` to the `string split` calls fixed this issue for you? (I can't reproduce the error on fish 3.1.2 and bazel 3.5.0)

**Comment by uri-canva** [comment]
Yes it does. (I tested it with `-n` which is the equivalent short option)

I also verified it happens with bazel 3.5.1, albeit with bazel 3.3.1's completions (brew doesn't install fish completions for bazel, only for bash and zsh: https://github.com/Homebrew/homebrew-core/blob/d7d8324f0c48640a6b9acf70e4f3442a6ccce7fb/Formula/bazel.rb#L44).

**Comment by uri-canva** [comment]
Reproed it on bazel 3.5.1 with bazel 3.5.1 completions (still on macOS though, not Linux).

**Comment by uri-canva** [comment]
cc me on the PR and I can test it locally.
