### ISSUE TITLE
Fish completion string match unknown option

### ISSUE THREAD

**Issue by uri-canva** [bazelbuild/bazel#12206]
### Description of the problem / feature request:

When sourcing fish completions:

```
string match: Unknown option '--[no]worker_sandboxing'

~/.nix-profile/share/fish/vendor_completions.d/bazel.fish (line 55): 
    if string match -qr boolean $desc
       ^
in function '__bazel_complete_option' with arguments '__bazel_seen_subcommand\ aquery "" "" --\[no\]worker_sandboxing \(a boolean\; default: \"false\"\)'
	called on line 121 of file ~/.nix-profile/share/fish/vendor_completions.d/bazel.fish
in function '__bazel_complete_subcommand' with arguments 'aquery'
	called on line 136 of file ~/.nix-profile/share/fish/vendor_completions.d/bazel.fish
in function '__bazel_complete_subcommands'
	called on line 141 of file ~/.nix-profile/share/fish/vendor_completions.d/bazel.fish
from sourcing file ~/.nix-profile/share/fish/vendor_completions.d/bazel.fish
in command substitution

(Type 'help string' for related documentation)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Source fish completions.

### What operating system are you running Bazel on?

> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2

> fish --version
fish, version 3.1.2

### What's the output of `bazel info release`?

release 3.3.0

###  Have you found anything relevant by searching the web?

Issue requesting fish completions: https://github.com/bazelbuild/bazel/issues/5088
Initial implementation: https://github.com/bazelbuild/bazel/pull/11450/files

### Any other information, logs, or outputs that you want to share?

This is caused by fish commands interpreting their inputs as options to the command itself. It can be solved by using `--` to separate options to the fish command from its input. For example `string split ' ' -- $line` instead of `string split ' ' $line`, and `string match -qr boolean -- $desc` instead of `string match -qr boolean $desc`.

**Comment by uri-canva** [comment]
cc @tmandry @akirabaruah

**Comment by akirabaruah** [comment]
Hmm, I'm unable to repro using fish 3.1.2 and bazel 3.5.0 on linux. Nonetheless, I agree that we should use `--` to avoid parsing inputs as options to the `string` command.

@uri-canva since I can't repro myself, would you mind testing the script on your machine with the `--` replacements that you mentioned to verify the fix? I'm happy to upload a patch for you to try if needed - just let me know.

**Comment by uri-canva** [comment]
Yup, I've tested adding it in a couple of places and it resolved the issue.
