### ISSUE TITLE
--experimental_remote_grpc_log and --build_event_binary_file together result in bazel hanging

### ISSUE THREAD

**Issue by asuffield** [bazelbuild/bazel#12203]
This one's bizarre. I've been able to get it to happen with bazel 3.4.1 and 3.5, but haven't narrowed down a reproduction case yet; filing the bug now in case it's more obvious to somebody else what is going on. I also have remote cache enabled for this particular build.

The build will complete normally, and then bazel will print "Waiting for build events: BinaryFormatFileTransport" forever and never exit.

**Comment by oquenchil** [comment]
It would be really hard to know what's going on without more data, please feel free to close until you have a repro.

**Comment by coeuvre** [comment]
Closing since it should be fixed by #12416. Feel free to reopen if it is still an issue.
