### ISSUE TITLE
Documentation issue: Command-Line Reference

### ISSUE THREAD

**Issue by vonschultz** [bazelbuild/bazel#12218]
Documentation URL: https://docs.bazel.build/versions/master/command-line-reference.html

`"auto" sets a reasonable default based onhost resources.` should be `"auto" sets a reasonable default based on host resources.` (missing space, `onhost` should be `on host`).

It looks like it comes from https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/runtime/LoadingPhaseThreadsOption.java where strings are concatenated without including a space.
```
              + ". \"auto\" sets a reasonable default based on"
              + "host resources. Must be at least 1.")
```

**Comment by meisterT** [comment]
thanks: https://bazel-review.googlesource.com/c/bazel/+/141810
