### ISSUE TITLE
analyze-profile: Docs are out of date? `--html`, `--dump`, etc. are not in `help --long`?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [bazelbuild/bazel#12212]
### Description of the problem / feature request:

Docs seem stale; seems like it documents the old profiling setup (ye olde profile file), not the current one (JSON).
Also, `--dump` and `--html` do not seem to work as indicated on the docs.

### Feature requests: what underlying problem are you trying to solve with this feature?

Just profiling build, namely to get test timing info w/o parsing text / JSON / whatevs.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See docs here:
https://docs.bazel.build/versions/3.5.0/user-manual.html#analyze-profile
https://docs.bazel.build/versions/3.5.0/guide.html#profiling

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

release 3.5.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A. See standalone repro script below, and its output.

###  Have you found anything relevant by searching the web?

* #10140
* Code doesn't smell like it matches the docs: https://github.com/bazelbuild/bazel/blob/3.5.0/src/main/java/com/google/devtools/build/lib/runtime/commands/ProfileCommand.java

### Any other information, logs, or outputs that you want to share?

See standalone reproduction script and output:
https://github.com/EricCousineau-TRI/repro/blob/9cc40aa7bd7d0e3370afe0e0cef41c6daacb96c5/bazel/bazel_3.5.0_profile_example/repro.sh
https://github.com/EricCousineau-TRI/repro/blob/9cc40aa7bd7d0e3370afe0e0cef41c6daacb96c5/bazel/bazel_3.5.0_profile_example/repro.output.txt

**Comment by benjaminp** [comment]
03b527073531119aec19d2aacebf3b567e024b9b

**Comment by EricCousineau-TRI** [comment]
Sweet! But that only tackles `--html` - is there something that can be used for `--dump=raw`?

**Comment by meisterT** [comment]
Feel free to send a PR to update the docs, otherwise I'll fix this next week.

**Comment by EricCousineau-TRI** [comment]
I think @benjaminp's PR resolves the `--html` side of things.

I actually just went through some steps to view the JSON output in Chrome / Chromium, so I'll send a WIP PR covering those bits too.

**Comment by EricCousineau-TRI** [comment]
Filed: https://github.com/bazelbuild/bazel/pull/12234
