### ISSUE TITLE
multiple package paths can hide files in the root package

### ISSUE THREAD

**Issue by janakdr** [bazelbuild/bazel#1221]
FileSystemUtils does not consider the package with empty name when deciding if a directory can have files coming from a parent [package](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/vfs/FileSystemUtils.java#L146) (called when planting the [link forest](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/vfs/FileSystemUtils.java#L714)). This causes the following bug. Execute from the root of a Bazel workspace:
```
echo "sh_binary(name = 'root', srcs = ['a/root.sh'])" >> BUILD
mkdir -p a
touch a/root.sh
chmod +x a/root.sh
mkdir -p ../other-bazel/a/b
echo "sh_library(name = 'b')" >> ../other-bazel/a/b/BUILD
bazel build //:root //a/b:b  --package_path='%workspace%:../other-bazel'
# prints error:
ERROR: /usr/local/google/home/janakr/bazel/BUILD:53:1: 'a/root.sh' is not a file.

bazel build //:root --package_path='%workspace%:../other-bazel'
# succeeds

```
One solution might be banning the package_path flag in Bazel. Getting rid of this special-casing logic might be tricky because of Google-internal issues.

**Comment by damienmg** [comment]
The good solution would be to fix FileSystemUtils.
