### ISSUE TITLE
Latest release (3.5.1) lacks an arm64 build, breaks Bazelisk

### ISSUE THREAD

**Issue by mattsplats** [bazelbuild/bazel#12222]
Not sure if this is intentional or there's been a silent regression. [3.5.1 lacks an arm64 build for Linux](https://github.com/bazelbuild/bazel/releases/tag/3.5.1) that was [present on 3.5.0](https://github.com/bazelbuild/bazel/releases/tag/3.5.0) and since 3.4.

This also breaks installing via Bazelisk:
```
> bazel --version
2020/10/05 21:52:04 Downloading https://releases.bazel.build/3.5.1/release/bazel-3.5.1-linux-arm64...
2020/10/05 21:52:04 could not download Bazel: HTTP GET https://releases.bazel.build/3.5.1/release/bazel-3.5.1-linux-arm64 failed with error 404
```

**Comment by philwo** [comment]
I'm sorry - I'll push that right away (and will finally add the missing automation for arm64). 😬

**Comment by philwo** [comment]
This is fixed now!
