### ISSUE TITLE
__init__.py still created, despite --incompatible_default_to_explicit_init_py

### ISSUE THREAD

**Issue by staalb** [bazelbuild/bazel#12238]
### Description of the problem / feature request:

When `--incompatible_default_to_explicit_init_py` is passed, no `__init__.py` files are created for a `py_binary` target. However, when that target is used in a `genrule`, still the `__init__.py` files are created.

### Feature requests: what underlying problem are you trying to solve with this feature?
I have a code generator written in Python, which depends on third party code which uses python [namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/).

Invoking the `py_binary` target of the code generator works fine (provided that `--incompatible_default_to_explicit_init_py` is passed to Bazel). Using this target as a tool in a `genrule` or with `ctx.actions.run` fails because Bazel still creates `__init__.py` files in that case.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Consider the following `BUILD` file:
```
py_library(
    name = "lib1",
    srcs = glob(["pylib1/**/*.py"]),
    imports = ["pylib1"],
)

py_library(
    name = "lib2",
    srcs = glob(["pylib2/**/*.py"]),
    imports = ["pylib2"],
)

py_binary(
    name = "test",
    srcs = ["test.py"],
    deps = [":lib1", ":lib2"],
)

genrule(
    name = "gen",
    outs = ["out.txt"],
    cmd = "$(location :test)",
    tools = [":test"],
)
```

And `test.py`:
```
import foo.bar.a
import foo.bar.b
```

Furthermore, the following empty files exist:
- `WORKSPACE`
- `pylib1/foo/bar/a.py`
- `pylib2/foo/bar/b.py`

This command works as expected:
`bazel run --incompatible_default_to_explicit_init_py :test`

While this command unexpectedly fails:
`bazel build --incompatible_default_to_explicit_init_py :gen`

... with this error:
```
Traceback (most recent call last):
  File "/home/bart/.cache/bazel/_bazel_bart/6a2c2a526fcecf9ab777dfd64f329e17/sandbox/linux-sandbox/6/execroot/__main__/bazel-out/host/bin/test.runfiles/__main__/test.py", line 2, in <module>
    import foo.bar.b
ModuleNotFoundError: No module named 'foo.bar.b'
```

Probably caused because Bazel created `__init__.py` files:
```
$ find bazel-out/ -name __init__.py
bazel-out/host/bin/test.runfiles/__main__/pylib2/foo/__init__.py
bazel-out/host/bin/test.runfiles/__main__/pylib2/foo/bar/__init__.py
bazel-out/host/bin/test.runfiles/__main__/pylib2/__init__.py
bazel-out/host/bin/test.runfiles/__main__/pylib1/foo/__init__.py
bazel-out/host/bin/test.runfiles/__main__/pylib1/foo/bar/__init__.py
bazel-out/host/bin/test.runfiles/__main__/pylib1/__init__.py
```

> Replace this line with your answer.

### What operating system are you running Bazel on?

This issue is reproducible on both Linux and Windows.

### What's the output of `bazel info release`?

`release 3.4.1` and `release 3.6.0` on Linux
`release 3.5.0` on Windows

###  Have you found anything relevant by searching the web?

I tried to search the github issue database and stackoverflow/google.

### Any other information, logs, or outputs that you want to share?

Nope.

**Comment by LiyouZhou** [comment]
Is there a workaround for this?
