### ISSUE TITLE
Failed to build on Arch : undeclared inclusion

### ISSUE THREAD

**Issue by thomascello** [bazelbuild/bazel#1223]
I want to install Tensorflow but I don't manage to install Bazel. I get the following error:
`🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
INFO: Found 1 target...
ERROR: /tmp/yaourt-tmp-tm/aur-bazel/src/bazel-0.2.2b/src/main/cpp/BUILD:53:1: undeclared inclusion(s) in rule '//src/main/cpp:blaze_abrupt_exit':
this rule is missing dependency declarations for the following files included by 'src/main/cpp/blaze_abrupt_exit.cc':
  '/usr/include/stdc-predef.h'.
Target //src:bazel failed to build`

I tried the following patch but it keeps failing:
[https://github.com/bazelbuild/bazel/issues/292#issuecomment-122036161](url)

Thanks in advance for your help

**Comment by damienmg** [comment]
Maybe you are hitting issue #1204. Can you try using the patch proposed to tools/cpp/cc_configure.bzl?

**Comment by thomascello** [comment]
Thank you for your help. 
Unfortunately, I tried the patch proposed to tools/cpp/cc_configure.bzl, but I get exactly the same error message: 
 `ERROR: /tmp/yaourt-tmp-tm/aur-bazel/src/bazel-0.2.2b/src/main/cpp/BUILD:53:1: undeclared inclusion(s) in rule '//src/main/cpp:blaze_abrupt_exit':
this rule is missing dependency declarations for the following files included by 'src/main/cpp/blaze_abrupt_exit.cc':
  '/usr/include/stdc-predef.h'.
Target //src:bazel failed to build
`
Do you have an other idea? 
Thanks

**Comment by damienmg** [comment]
So investigation step, could you report the result of the following commands:

- `which gcc`
- `echo "x${CC}x"`
- `echo | gcc -xc++ -E - -v`

?

**Comment by thomascello** [comment]
Please find the results:

- which gcc

`/usr/bin/gcc`
- echo "x${CC}x"

`xx`
- echo | gcc -xc++ -E - -v
`Utilisation des specs internes. (ENG: Using the internal specifications)
COLLECT_GCC=gcc
Cible (ENG: Target) : x86_64-unknown-linux-gnu
Configuré avec (ENG: Configured with) : /build/gcc-multilib/src/gcc-5-20160209/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release
Model of thread: posix
gcc version 5.3.0 (GCC) 
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/cc1plus -E -quiet -v -D_GNU_SOURCE - -mtune=generic -march=x86-64
le répertoire (ENG: repertory) « /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../x86_64-unknown-linux-gnu/include » est ignoré car inexistant (ENG: is ignored because it does not exist) 
la recherche pour (ENG: the Research for) #include "..." débute ici (ENG: start here):
la recherche pour (ENG: the Research for) #include <...> débute ici (ENG: start here):
 /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0
 /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/x86_64-unknown-linux-gnu
 /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/backward
 /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include
 /usr/local/include
 /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include-fixed
 /usr/include
Fin de la liste de recherche. (ENG: End of the research list)
# 1 "<stdin>"
# 1 "<interne>"
# 1 "<ligne-de-commande>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<ligne-de-commande>" 2
# 1 "<stdin>"
COMPILER_PATH=/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/:/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/:/usr/lib/gcc/x86_64-unknown-linux-gnu/:/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/:/usr/lib/gcc/x86_64-unknown-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/:/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/:/lib/../lib/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64`

(My archlinux is in french so I translated in English the french words in the output :) )

**Comment by damienmg** [comment]
Don't worry for french word, I am french :) I edited the formatting to see it better.

Oh maybe our parsing is wrong again. I guess it doesn't catch the "/usr/include" line from `gcc -xc++ -E - -v` I need to look at it a bit more.

**Comment by damienmg** [comment]
Is the raw output like:
```
Utilisation des specs internes.
COLLECT_GCC=gcc
Cible (ENG: Target) : x86_64-unknown-linux-gnu
Configuré avec (ENG: Configured with) : /build/gcc-multilib/src/gcc-5-20160209/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release
Model of thread: posix
gcc version 5.3.0 (GCC) 
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/cc1plus -E -quiet -v -D_GNU_SOURCE - -mtune=generic -march=x86-64
le répertoire « /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../x86_64-unknown-linux-gnu/include » est ignoré car inexistant 
la recherche pour #include "..." débute ici:
la recherche pour #include <...> débute ici:
 /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0
 /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/x86_64-unknown-linux-gnu
 /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/backward
 /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include
 /usr/local/include
 /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include-fixed
 /usr/include
Fin de la liste de recherche.
# 1 "<stdin>"
# 1 "<interne>"
# 1 "<ligne-de-commande>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<ligne-de-commande>" 2
# 1 "<stdin>"
COMPILER_PATH=/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/:/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/:/usr/lib/gcc/x86_64-unknown-linux-gnu/:/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/:/usr/lib/gcc/x86_64-unknown-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/:/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/:/lib/../lib/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64
```
?

**Comment by thomascello** [comment]
Yes, this is exactly what I get !

Merci pour tout en tout cas ;)

**Comment by damienmg** [comment]
Ok sorry for the delay, I had some other issue to deal with + public holiday.

Anyway the detection code applied to that does returns `/usr/include` so it's not my initial guess.

Can you comment https://github.com/bazelbuild/bazel/blob/master/scripts/bootstrap/buildenv.sh#L96 and add an `echo ${DIR}` line there, re-run ./compile.sh and then look the external/local_cc_config/CROSSTOOL file under the directory printed by the echo? If you could send the file that would be helpful.

**Comment by thomascello** [comment]
Don't worry for the delay, I perfectly understand!

Please find attached the `external/local_cc_config/CROSSTOOL` file. I hope this will help!

[CROSSTOOL.zip](https://github.com/bazelbuild/bazel/files/252539/CROSSTOOL.zip)

Best

**Comment by damienmg** [comment]
Ok for some reason the include directories where not detected at all, can you try applying the following patch, ./compile.sh and give the output:
```
diff --git a/tools/cpp/cc_configure.bzl b/tools/cpp/cc_configure.bzl
index 1250d23..6189ece 100644
--- a/tools/cpp/cc_configure.bzl
+++ b/tools/cpp/cc_configure.bzl
@@ -138,6 +138,9 @@ def _get_cxx_inc_directories(repository_ctx, cc):
   else:
     inc_dirs = result.stderr[index1 + 1:index2].strip()
 
+  print("result.stderr = '%s'" % result.stderr)
+  print("result.stdout = '%s'" % result.stdout)
+  print("inc_dirs = '%s'" % str(inc_dirs))
   return [repository_ctx.path(_cxx_inc_convert(p))
           for p in inc_dirs.split("\n")]
```

**Comment by thomascello** [comment]
I just applied the patch that you proposed and it seems that the patch does not work. I get the following output :
`==> Lancement de prepare()...
patching file tools/cpp/cc_configure.bzl
patch unexpectedly ends in middle of line
Hunk #1 FAILED at 138.
1 out of 1 hunk FAILED -- saving rejects to file tools/cpp/cc_configure.bzl.rej
==> ERREUR : Une erreur s’est produite dans prepare().
`
I may have done something wrong but I have not idea of what could it be.

**Comment by damienmg** [comment]
Humm I guess that's because of the version, you could just do `git checkout HEAD tools/cpp/cc_configure.bzl` and then add the following three lines around line 140:
```python
  print("result.stderr = '%s'" % result.stderr)
  print("result.stdout = '%s'" % result.stdout)
  print("inc_dirs = '%s'" % str(inc_dirs))
```

**Comment by thomascello** [comment]
I don't why the patch was not working. I add manually the three lines and it's ok now. Please find attached the corresponding output:
[output.zip](https://github.com/bazelbuild/bazel/files/252733/output.zip)

Thanks

**Comment by damienmg** [comment]
Did you killed the execution?

Also, could you replace the line below the prints:
```
  return [repository_ctx.path(_cxx_inc_convert(p))
          for p in inc_dirs.split("\n")]
```

with
```
  r = [repository_ctx.path(_cxx_inc_convert(p))
          for p in inc_dirs.split("\n")]
  print("result = '%s'" % str(r))
```

and return the output (without interrupt if possible)?

**Comment by thomascello** [comment]
Yes I killed the execution because I thought the rest was not interesting. 
Please find attached the output with the modifications you asked

**Comment by damienmg** [comment]
Oops the change would obviously not work.

Can you add `  return r` after the print line?

**Comment by thomascello** [comment]
Thanks! It seems to work much better but I still have an error message:
[output3.zip](https://github.com/bazelbuild/bazel/files/255995/output3.zip)

(Just to let you know, I fork and modify the `tools/cpp/cc_configure.bzl` file [here](https://github.com/thomascello/bazel) and I'm using this [PKGBUILD](https://github.com/bazelbuild/bazel/files/256014/PKGBUILD.zip) to make a bazel package for my distribution (arch linux))

**Comment by thomascello** [comment]
And this is what my `.bazelrc` file looks like: 

`build --crosstool=//tools/cpp:toolchain
build --crosstool_top=//tools/cpp:toolchain
build --crosstool_top=//tools/cpp:toolchain
build --crosstool_top=//tools/cpp:toolchain`

**Comment by thomascello** [comment]
And I try with this `.bazelrc`: `build --crosstool_top=//tools/cpp:toolchain ` and do also this [modification](http://stackoverflow.com/a/35274720).

I get this error message:
[output4.zip](https://github.com/bazelbuild/bazel/files/256594/output4.zip)

I'm frustrated because I really need to install tensorflow...

Tanks again

**Comment by damienmg** [comment]
Remove everything in your bazelrc and retry.

**Comment by damienmg** [comment]
Ok so from what I have seen, it should just work from bazel head (no need to patch cc_configure, those are just debug information), if you remove your .bazelrc.

Tell me if that works.

**Comment by thomascello** [comment]
It is working now ! Thanks you so much for your help ! 

Bonne journée à vous !

**Comment by thomascello** [comment]
I jus try to install tensorflow but I have an error message related I think to bazel... 

[tensorflow_output.zip](https://github.com/bazelbuild/bazel/files/257428/tensorflow_output.zip)

Do you have an idea ? 

Thanks again

**Comment by damienmg** [comment]
It's a bug on TensorFlow side. I think they fixed it recently.

**Comment by thomascello** [comment]
Thanks for this info! It does not seem fixed in the AUR depo...  I just found that : [https://github.com/tensorflow/tensorflow/pull/2094/files](https://github.com/tensorflow/tensorflow/pull/2094/files)

But thanks so much your help on bazel !

**Comment by damienmg** [comment]
Your welcome :)
