### ISSUE TITLE
Provide documentation for sandboxing (e.g. block-network)

### ISSUE THREAD

**Issue by glukasiknuro** [bazelbuild/bazel#12239]
### Description of the feature request:

Sandboxing is very nice feature of bazel, but there is no single place with detailed documentation.
Best documentation I found so far is https://bazel.build/designs/2016/06/02/sandboxing.html , which has disclaimer that it's not description of current functionality.

Would be great to have documentation of sandboxing somewhere in https://docs.bazel.build/

For example, "block-network" tag and flag `sandbox_default_allow_network` is not really well documented. From what I see it e.g. allows multiple tests to bind to same localhost port in linux-sandbox by creating new  network namespace (see [linux-sandbox.cc](https://github.com/bazelbuild/bazel/blob/731e87e9620c629d7506396f89726bb61825fc95/src/main/tools/linux-sandbox.cc#L161) and [linux-sandbox-pid1.cc](https://github.com/bazelbuild/bazel/blob/cd84ef30b6b6cdf4db75ac5307a79aeff999f9f7/src/main/tools/linux-sandbox-pid1.cc#L322)) which is very nice feature, but it may not work for other sandboxes, this could be more clearly stated somewhere.

###  Have you found anything relevant by searching the web?

Some current documentation:

https://blog.bazel.build/2015/09/11/sandboxing.html
https://bazel.build/designs/2016/06/02/sandboxing.html

Description of `block-network': https://docs.bazel.build/versions/master/be/common-definitions.html#common.tags

Somewhat related bugs:
https://github.com/bazelbuild/bazel/issues/11325 `block-network allows tcp access to unsandboxed localhost servers in darwin-sandbox, but not in linux-sandbox`

https://github.com/bazelbuild/bazel/issues/7303 `blocks-network and allows-network are different for different spawn strategies`

**Comment by anton-abashkin-mongodb** [comment]
+1 , this would be greatly appreciated

**Comment by communikit** [comment]
A sandboxing page was added recently: https://docs.bazel.build/versions/master/sandboxing.html

Does this sufficiently address your needs?

**Comment by communikit** [comment]
Closing this issue since there is now dedicated sandboxing documentation on https://docs.bazel.build

Feel free to open a new issue or send in a PR for any additional updates to the page.
