### ISSUE TITLE
4b71d2e1bc3afa0ce0a5b6e68dac3c559654d975 seems to have broken android tests

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1224]
See http://ci.bazel.io/job/Bazel/518/
and http://ci.bazel.io/job/Tutorial/268/

**Comment by damienmg** [comment]
commit 4b71d2e1bc3afa0ce0a5b6e68dac3c559654d975 to get an easy link.

**Comment by kchodorow** [comment]
The paths are just incorrect in tools/android, but I'm unable to reproduce the failure so far which makes me a bit nervous about "fixing" them.

**Comment by damienmg** [comment]
Did you set-up the android repositories to activate those test? @ahumesky can help I think

**Comment by damienmg** [comment]
wait that's a duplicate of #1214, @serynth has a fix for that I think

**Comment by damienmg** [comment]
Oops no he has a fix for something else.  Anyway closing this one as duplicate.
