### ISSUE TITLE
Behavior change for query exit codes

### ISSUE THREAD

**Issue by janakdr** [bazelbuild/bazel#12259]
https://github.com/bazelbuild/bazel/commit/dec757f712ee334751b66844d1d55f2060fc6a65 added a new flag, `--experimental_query_failure_exit_code_behavior`. Its current value maintains existing behavior, but I plan to flip the default value soon. Currently, a query that fails will almost always return exit code 3 for a failed `--keep_going` query and exit code 7 for a failed `--nokeep_going` query, regardless of the actual cause of the failure.

I plan to change the behavior to return an exit code that corresponds to the cause of the failure. That tends to be 1 in the case of normal package errors, and 7 in the case of syntax errors in the query itself.

This behavior can be turned off by setting `--experimental_query_failure_exit_code_behavior=three_and_seven`. However, if this behavior breaks you, please let me know, because I would like to remove the flag soon.

If this behavior is too breaking a change, I may settle for `--experimental_query_failure_exit_code_behavior=seven`, which will make failed queries return exit code 7, even if they are `--keep_going`. You can try that instead of `three_and_seven` if you're broken by the flag flip.

**Comment by janakdr** [comment]
cc @michajlo

**Comment by keith** [comment]
This breaks our CI use case where we do `keep_going` queries to determine what needs to be rebuilt, and the query partially failing gives us info that we need to build things outside of the build graph, while also returning some valuable results about what specific packages were changed before the failure.

**Comment by janakdr** [comment]
@keith can you say a bit more about how this breaks you? The actual behavior of a --keep_going query won't change, just the exit code. A --keep_going query will continue to execute as fully as possible. Perhaps I'm misunderstanding your use case?

**Comment by keith** [comment]
Our logic looks something like this:

```python
try:
    output = subprocess.check_output(
        the bazel query
    ).decode()
except subprocess.CalledProcessError as e:
    # 3 is the code for keep_going failing but still having output
    if keep_going and e.returncode == 3:
        output = e.output.decode()
    else:
        raise
```

So we differentiate based on the code about how valid the result is, and we differ based on whether or not the query is invalid because a file isn't part of a package, vs a BUILD file being entirely invalid, is handled differently.

**Comment by janakdr** [comment]
Thanks for the explanation. To clarify, when you say that you handle different failure modes differently, you're doing that based on bespoke parsing of the error, correct? Because currently exit code 3 will be returned for both those errors, I think.

If you switched to checking for the return code being 1 or 7, rather than 3, you should continue to capture all current cases of exit code 3. Would it be acceptable to do that? 7 would include some cases where the query syntax was invalid, and so the query wasn't executed at all. If your queries can hit that case, then this would be a regression. On the plus side with this change, if there were a failure due to (say) an I/O exception in the filesystem, you could fail fast based on the exit code, which is currently not possible because even I/O exceptions get transformed into exit code 3.

If that isn't acceptable, then it sounds like the switch to exit code 7 for these errors also wouldn't be good enough, because you want different exit codes for a partially successful query and one where the syntax was bad, so nothing got done.

**Comment by keith** [comment]
Ah I see your original point, I guess we're not handling this correctly then and were assuming the 3 would not be the case for invalid BUILD files for example (since yea query syntax errors shouldn't be a problem for us).

So I guess this won't be a regression for us, but also doesn't provide the original use case we were hoping for. Sorry for the trouble!

**Comment by janakdr** [comment]
No worries, this was very helpful to understand query use cases! It's good to know that there's a demand out there for finer-grained errors in this situation.

**Comment by janakdr** [comment]
Update: we're actually not going to proceed with this migration. It looks a bit too risky for some existing use cases.
