### ISSUE TITLE
Bazel does not build on Linuxbrew

### ISSUE THREAD

**Issue by baranyildirim** [bazelbuild/bazel#12253]
On Linuxbrew, the compilation script does not seem to work.
The JAVA_HOME directory is incorrect in the formula, but even after fixing that bazel will not successfully build.
Trying to fix this with https://github.com/Homebrew/linuxbrew-core/pull/21161 but cannot figure out a way to fix the build error.

### Description of the problem / feature request:

Bazel does not build correctly on Linuxbrew

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

brew install bazel

### What operating system are you running Bazel on?

Ubuntu 20.04 

### Any other information, logs, or outputs that you want to share?

See https://github.com/Homebrew/linuxbrew-core/pull/21161

**Comment by baranyildirim** [comment]
Is there a way to prevent bazel from resetting the environment while bootstrapping? This seems to be causing the issue for brew.

**Comment by philwo** [comment]
@baranyildirim Which step fails - the compile.sh or the `bazel build` step after that?

**Comment by baranyildirim** [comment]
@philwo I think the `bazel build` step is failing. The full log is [here](https://github.com/Homebrew/linuxbrew-core/pull/21161/checks?check_run_id=1329741335).

**Comment by philwo** [comment]
If you can figure out which environment variables `gcc-9` complains about, I think you could `--action_env=` flags here, similar to how it's done for PATH: https://github.com/bazelbuild/bazel/blob/master/compile.sh#L67

I haven't looked into how and to which extent we reset the environment for actions recently, unfortunately I can't offer much more help here :/
