### ISSUE TITLE
Java Build fails on using toolchain_hostjdk8 but passes on toolchain_vanilla

### ISSUE THREAD

**Issue by aman-harness** [bazelbuild/bazel#12263]
### Description of the problem / feature request:

I am seeing some weird compilation failures in bazel.
If I use the above config everything compiles seemlessly.
```
build --javabase=@bazel_tools//tools/jdk:absolute_javabase
build --host_javabase=@bazel_tools//tools/jdk:absolute_javabase
build --host_java_toolchain=@bazel_tools//tools/jdk:toolchainvanilla
build --java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla

```
But when I switch to toolchain_hostjdk8   compilation starts failing with error:
<Repeatable Annotation> is incorrectly reported as "not repeatable".
Although the annotation is marked as repetable and it works with toolchain_vanilla. I tried to look at the implementation of toolchain but couldn't find anything which can cause this.
```
build --javabase=@bazel_tools//tools/jdk:absolute_javabase
build --host_javabase=@bazel_tools//tools/jdk:absolute_javabase
build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
build --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
```

### What operating system are you running Bazel on?

> MacOs

### What's the output of `bazel info release`?

> release 3.5.1-homebrew

###  Have you found anything relevant by searching the web?
This is one bug I found on JDK. Could be related but I am not sure: https://bugs.openjdk.java.net/browse/JDK-8199392

**Comment by comius** [comment]
What JDK are you using? toolchain_vanilla is designed to support any JDK, while toolchain_hostjdk8 is for JDK8 and won't work with later versions.

**Comment by aiuto** [comment]
Closing for lack of action
