### ISSUE TITLE
Unable to build my android_binary due to IllegalArgumentException

### ISSUE THREAD

**Issue by paladine** [bazelbuild/bazel#1228]
I had a problem building my Android app due to issue #1222, so when it was fixed I wanted to see if I could build again. Turns out I can't - due to another issue.

These TODD print statements come from modifying src/main/java/com/google/devtools/build/lib/pkgcache/LoadingPhaseRunner.java to print 
pkg.getPackageIdentifier() and pkg.getSourceRoot() inside collectPackageRoots()

```
TODD [@bazel_tools//src/tools/android/java/com/google/devtools/build/android][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@local_jdk//][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@bazel_tools//tools/jdk][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [external][/home/tcj/src]
TODD [@bazel_tools//third_party/java/jdk/langtools][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@local_config_cc//][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@bazel_tools//tools/android][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@bazel_tools//src/tools/android/java/com/google/devtools/build/android/ziputils][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@bazel_tools//tools/python][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@bazel_tools//third_party/py/gflags][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [java/com/jeffreys/euchre][/home/tcj/src/blaze_workspace]
TODD [java/com/jeffreys/soyrenderer][/home/tcj/src/blaze_workspace]
TODD [@aopalliance_aopalliance//jar][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@args4j_args4j//jar][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@com_google_code_findbugs_jsr305//jar][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@com_google_guava_guava//jar][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@com_google_inject_extensions_guice_assistedinject//jar][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@com_google_inject_extensions_guice_multibindings//jar][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@com_google_inject_guice//jar][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@com_google_template_soy//jar][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@com_ibm_icu_icu4j//jar][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@javax_inject_javax_inject//jar][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@org_ow2_asm_asm_analysis//jar][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@org_ow2_asm_asm_commons//jar][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@org_ow2_asm_asm_tree//jar][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@org_ow2_asm_asm_util//jar][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@org_ow2_asm_asm//jar][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [external/soy][/home/tcj/src/blaze_workspace]
TODD [@bazel_tools//tools/genrule][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [java/com/jeffreys/euchre/googleplay][/home/tcj/src/blaze_workspace]
TODD [@bazel_tools//third_party/py/concurrent][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@bazel_tools//third_party/java/jarjar][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@androidsdk//][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@bazel_tools//third_party/java/apkbuilder][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@bazel_tools//src/tools/android/java/com/google/devtools/build/android/idlclass][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [@bazel_tools//src/tools/android/java/com/google/devtools/build/android/incrementaldeployment][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [java/com/jeffreys/common/euchre/android][/home/tcj/src/blaze_workspace]
TODD [@com_google_protobuf_nano//jar][/home/tcj/.cache/bazel/_bazel_tcj/aab2853d4c27e90a447e9dab0d19b96b]
TODD [android/rules][/home/tcj/src/blaze_workspace]
TODD [euchre][/home/tcj/src/blaze_workspace]
TODD [tools/jdk][/home/tcj/src/blaze_workspace]
TODD [third_party][/home/tcj/src/blaze_workspace]
TODD [third_party/protobuf][/home/tcj/src/blaze_workspace]
TODD [java/com/jeffreys/common/euchre][/home/tcj/src/blaze_workspace]
TODD [java/com/fortysevendeg/swipelistview][/home/tcj/src/blaze_workspace]
TODD [java/com/nineoldandroids][/home/tcj/src/blaze_workspace]
TODD [java/com/jeffreys/common/euchre/common][/home/tcj/src/blaze_workspace]
TODD [java/com/jeffreys/common/euchre/engine][/home/tcj/src/blaze_workspace]
TODD [java/com/jeffreys/common/euchre/platform][/home/tcj/src/blaze_workspace]
TODD [java/com/larvalabs/svgandroid][/home/tcj/src/blaze_workspace]
TODD [java/fr/nicolaspomepuy/discreetapprate][/home/tcj/src/blaze_workspace]
TODD [java/net/margaritov/preference/colorpicker][/home/tcj/src/blaze_workspace]
TODD [external][/home/tcj/src]
Unhandled exception thrown during build; message: Multiple entries with same key: external=/home/tcj/src and external=/home/tcj/src
INFO: Elapsed time: 0.426s
java.lang.IllegalArgumentException: Multiple entries with same key: external=/home/tcj/src and external=/home/tcj/src
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:136)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:98)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:84)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:295)
	at com.google.devtools.build.lib.pkgcache.LoadingPhaseRunner.collectPackageRoots(LoadingPhaseRunner.java:79)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:245)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:483)
	at com.google.devtools.build.lib.buildtool.BuildTool.runAnalysisPhase(BuildTool.java:470)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:195)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:344)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:71)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:479)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:317)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:49)
	at com.google.devtools.build.lib.server.RPCService.executeRequest(RPCService.java:70)
	at com.google.devtools.build.lib.server.AfUnixServer.executeRequest(AfUnixServer.java:411)
	at com.google.devtools.build.lib.server.AfUnixServer.serve(AfUnixServer.java:215)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:861)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:643)
	at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)
```
The source of the duplication is [external] pointing to /home/tcj/src, which is really strange because my bazel root is /home/tcj/src/blaze_workspace, so why would getPackageRoot() point *outside* it?

I hacked up collectPackageRoots to handle duplicates by using a HashMap instead of an ImmutableMap.Builder, and I can build my target successfully. Though the issue is how did the duplicate key get in the system with getPackageRoot() pointing outside my workspace?

**Comment by kchodorow** [comment]
Can you share what your WORKSPACE file looks like?  

The reason it's got /home/tcj/src instead of /home/tcj/src/blaze_workspace is due to some hackery shoehorning //external into being a package.  Generally, the package defined by foo/bar/BUILD finds its source root by stripping the two pieces of package name (foo/bar) off of the full directory path (/home/tcj/src/blaze_workspace/foo/bar becomes /home/tcj/src/blaze_workspace).  However, for the external package, its name "package name" is "external" and it's already rooted at /home/tcj/src/blaze_workspace, so Bazel assumes there is one path piece to strip off and removes the blaze_workspace.

**Comment by paladine** [comment]
Sure no problem. It's pretty tame - just a bunch of maven_jars and the Android SDK setup

[Here it is](http://pastebin.com/MZbbbjf0)

**Comment by paladine** [comment]
Here's my BUILD file in question, trying to build :googleplay

Perhaps the duplication comes from having multiple //external:android deps?

`
package(
  default_visibility = ["//visibility:public"],
)

genrule(
  name = "manifest",
  srcs = ["//java/com/jeffreys/euchre:manifest_template"],
  outs = ["AndroidManifest.xml"],
  cmd = "$(location //java/com/jeffreys/soyrenderer) $(location //java/com/jeffreys/euchre:manifest_template) com.jeffreys.euchre.manifest package com.jeffreys.euchre application com.jeffreys.common.euchre.common.GooglePlayFreeApplication > \"$@\"",
  tools = ["//java/com/jeffreys/soyrenderer"],
)

android_binary(
  name = "googleplay_proguard",
  manifest = ":manifest",
  proguard_specs = ["//java/com/jeffreys/euchre:proguard"],
  proguard_generate_mapping = 1,
  resource_files = ["//java/com/jeffreys/euchre:resources"],
  deps = [
    "//java/com/jeffreys/common/euchre/android",
    "//external:android/appcompat_v4",
    "//external:android/mediarouter_v7",
    "//external:android/palette_v7",
  ],
)

android_binary(
  name = "googleplay",
  manifest = ":manifest",
  resource_files = ["//java/com/jeffreys/euchre:resources"],
  deps = [
    "//java/com/jeffreys/common/euchre/android",
    "//external:android/appcompat_v4",
    "//external:android/mediarouter_v7",
    "//external:android/palette_v7",
  ],
)
`

**Comment by kchodorow** [comment]
I've been trying to reproduce it (and found another bug), but haven't been able to, yet.  Do you have a simpler case that reproduces the issue?

**Comment by paladine** [comment]
This rule crashes it immediately:

android_library(
  name = "test",
  deps = [
    "//external:android/mediarouter_v7",
    "//external:android/palette_v7",
  ],
)

Basically anything with multiple "//external" will cause the error.

**Comment by damienmg** [comment]
@kchodorow is this bug fixed?

**Comment by kchodorow** [comment]
No, I just found the AST bug while trying to reproduce this.

**Comment by paladine** [comment]
Quick & Dirty fix
```
public static ImmutableMap<PackageIdentifier, Path> collectPackageRoots(
      Collection<Package> packages) {
    // Make a map of the package names to their root paths.
    Map<PackageIdentifier, Path> packageRoots = new HashMap<>();
    for (Package pkg : packages) {
      Path previousPath = packageRoots.put(pkg.getPackageIdentifier(), pkg.getSourceRoot());
      checkState(
          previousPath == null || previousPath.equals(pkg.getSourceRoot()),
          "Attempted to add multiple PackageIdentifiers with different paths!");
    }
    return ImmutableMap.copyOf(packageRoots);
  }

```

**Comment by kchodorow** [comment]
And reproduced (finally).  A less invasive workaround is using @repo syntax instead of //external.

**Comment by kchodorow** [comment]
I'm going to decrease the priority of this to P2 since there is a viable workaround, but here's what I've found debugging:

Two different Package(external)s are added to the configured target's transitive packages.  One is added by resolveConfiguredTargetDependencies() and the other is added by resolveAspectDependencies, so I'm guessing that something about the aspect dependencies is not resolving //external right.

**Comment by kchodorow** [comment]
@lberki another //external issue.

**Comment by lberki** [comment]
There is something sinister going on here: `PackageFunction#compute()` is executed three times with `PackageIdentifier`s that are `equals()` and even their hash codes are the same. How can that be?

**Comment by lberki** [comment]
Dumb me. Skyframe restarts. Still debugging...

**Comment by lberki** [comment]
Actually, no. There really are two invocations of `PackageFunction#compute()` for keys that are equals. Wat.

**Comment by janakdr** [comment]
I think the problem is that in [WorkspaceFactory.setParent](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/packages/WorkspaceFactory.java#L260) we blindly add targets to a builder that already have a different containing package, from an earlier segment of the workspace. At that point, the targets in this package have a different package than this package, which seems straight-up wrong. I'm honestly not sure why there isn't a check for this in [LegacyBuilder.addRule](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/packages/Package.java#L1192). I would urge that we add that check when this bug is fixed, maybe putting it in checkForConflicts. Finally, this bug is exposed in aspects because we call getPackage in [AspectFunction](https://github.com/bazelbuild/bazel/blob/5d80fddc70d43cb0051d2774cf7d5b1bcfa92439/src/main/java/com/google/devtools/build/lib/skyframe/AspectFunction.java#L286)
