### ISSUE TITLE
Failed to build tutorials_example_trainer

### ISSUE THREAD

**Issue by mayrsh** [bazelbuild/bazel#1229]
Hi, I've started to use ubuntu15.10 to try tensorflow lately. But after installing cuda or cudnn and so on , came across errors to build tutorial. So please help me , thanks in advance.

When I type "bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
" I'm getting
"
low6Device21BuildDeviceAttributesERKSsNS_10DeviceTypeENS_3gtl7IntTypeINS_10Bytes_tag_ExEENS_12BusAdjacencyES2_+0x2d): undefined reference to `google::protobuf::internal::empty_string_'
bazel-out/local_linux-opt/bin/tensorflow/core/libcore_cpu_internal.lo(device.o): In function `tensorflow::Device::Device(tensorflow::Env*, tensorflow::DeviceAttributes const&, tensorflow::Allocator*)':
device.cc:(.text._ZN10tensorflow6DeviceC2EPNS_3EnvERKNS_16DeviceAttributesEPNS_9AllocatorE+0xe0): undefined reference to `tensorflow::ResourceMgr::ResourceMgr(std::string const&)'
bazel-out/local_linux-opt/bin/tensorflow/core/libcore_cpu_internal.lo(threadpool_device.o): In function `tensorflow::ThreadPoolDevice::MakeTensorFromProto(tensorflow::TensorProto const&, tensorflow::AllocatorAttributes, tensorflow::Tensor*)':
threadpool_device.cc:(.text._ZN10tensorflow16ThreadPoolDevice19MakeTensorFromProtoERKNS_11TensorProtoENS_19AllocatorAttributesEPNS_6TensorE+0x69): undefined reference to `tensorflow::ProtoDebugString(tensorflow::TensorProto const&)'
threadpool_device.cc:(.text._ZN10tensorflow16ThreadPoolDevice19MakeTensorFromProtoERKNS_11TensorProtoENS_19AllocatorAttributesEPNS_6TensorE+0xa8): undefined reference to `tensorflow::strings::StrCat(tensorflow::strings::AlphaNum const&, tensorflow::strings::AlphaNum const&)'
bazel-out/local_linux-opt/bin/tensorflow/core/libfunctional_grad.lo(functional_grad.o): In function `_GLOBAL__sub_I__ZN10tensorflow17MapAccumulateGradERKNS_9AttrSliceEPNS_11FunctionDefE':
functional_grad.cc:(.text.startup._GLOBAL__sub_I__ZN10tensorflow17MapAccumulateGradERKNS_9AttrSliceEPNS_11FunctionDefE+0x83): undefined reference to `tensorflow::gradient::RegisterOp(std::string const&, std::function<tensorflow::Status (tensorflow::AttrSlice const&, tensorflow::FunctionDef*)>)'
bazel-out/local_linux-opt/bin/tensorflow/core/libfunctional_grad.lo(functional_grad.o): In function `tensorflow::MapAccumulateGrad(tensorflow::AttrSlice const&, tensorflow::FunctionDef*)':
functional_grad.cc:(.text._ZN10tensorflow17MapAccumulateGradERKNS_9AttrSliceEPNS_11FunctionDefE+0x306): undefined reference to `tensorflow::FunctionDefHelper::FunctionRef(std::string const&, tensorflow::gtl::ArraySlice<std::pair<std::string, tensorflow::FunctionDefHelper::AttrValueWrapper> >)'
functional_grad.cc:(.text._ZN10tensorflow17MapAccumulateGradERKNS_9AttrSliceEPNS_11FunctionDefE+0xb0b): undefined reference to `tensorflow::FunctionDefHelper::Define(tensorflow::gtl::ArraySlice<std::string>, tensorflow::gtl::ArraySlice<std::string>, tensorflow::gtl::ArraySlice<std::string>, tensorflow::gtl::ArraySlice<tensorflow::FunctionDefHelper::Node>)'
collect2: error: ld returned 1 exit status
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.159s, Critical Path: 2.07s
"
something like the text above. 
and i dont know what to do now.
something like the text above

**Comment by damienmg** [comment]
Hello,

I have no idea it doesn't sounds like bazel related, have you tried filing a bug to github.com/tensorflow/tensorflow?

**Comment by mayrsh** [comment]
Hi, Damienmg. Thanks for the comment! 
I failed to downgrade gcc and g++. After downgrading using update-alternatives, I succeeded to build!!
