### ISSUE TITLE
Canonicalize flags after reading configuration files? (to enable composing tag filters)

### ISSUE THREAD

**Issue by EricCousineau-TRI** [bazelbuild/bazel#12296]
### Description of the problem / feature request:

I'd like `canonicalize-flags` (or some related command) to output canonical flags *after* parsing RC files.
At present, they do not seem to:

```
  % bazel canonicalize-flags -- --config=any_name --test_tag_filters="-lint"
  --config=any_name
  --test_tag_filters=-lint
```

### Feature requests: what underlying problem are you trying to solve with this feature?

I'd like to compose tag filters (w/ custom logic), and would love to not create add'l `--config` entries in an RC file.

Ultimately, this is poor-man's workaround to #6477 - we've tinkered w/ Bazel's scheduling on a single machine w/ multiple GPUs, and haven't found a Bazel-expressible way to prevent bottlenecks unless we explicitly separate our `bazel test` statements.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

N/A

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

```
$ bazel info release 
INFO: Invocation ID: 77860539-db2e-43c1-9916-b3f9271a31da
release 3.5.0
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

Closest thing was #10213, but that looked like a bug.

### Any other information, logs, or outputs that you want to share?

N/A

**Comment by EricCousineau-TRI** [comment]
FTR The workaround for this is to just re-parse the `.rc` files, or use a dummy test target and use `--announce_rc`, and just intercept the output and hope for stability in this formatting.

**Comment by juliexxia** [comment]
Agree that this would be a nice feature to have and thanks for the docs updates. A potential complication would be breaking anyone that does expect --configs to stay unexpanded. 

We're not prioritizing this as a feature request right now, but I'll leave open in case we prioritize in the future/so others can chime in as well.

**Comment by EricCousineau-TRI** [comment]
Sounds great, thanks!

Perhaps that kind of thing could be made explicit, with a direct flag, like
`bazel canonicalize-flags --expand_config -- --config blerg`
or something indirect / more encompassing
`bazel canonicalize-flags --flatten -- --config blerg`
