### ISSUE TITLE
maven_jar documentation is wrong

### ISSUE THREAD

**Issue by is03wlei** [bazelbuild/bazel#1230]
I wrote WORKSPACE and BUILD after the follow description from bagel.io:
Examples

Suppose that the current repostory contains a java_library target that needs to depend on Guava. Using Maven, this dependency would be defined in the pom.xml file as:
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>18.0</version>
</dependency>
With Bazel, add the following lines to the WORKSPACE file:
maven_jar(
    name = "com_google_guava_guava",
    artifact = "com.google.guava:guava:18.0",
    sha1 = "cce0823396aa693798f8882e64213b1772032b09",
)
Targets can specify @guava//jar as a dependency to depend on this jar.

What I want to import is http://mvnrepository.com/artifact/commons-cli/commons-cli/1.3.1

<dependency>
	<groupId>commons-cli</groupId>
	<artifactId>commons-cli</artifactId>
	<version>1.3.1</version>
</dependency>

My WORKSPACE:

maven_jar(
    name = "commons_cli_commons_cli",
    artifact = "commons_cli:commons_cli:1.3.1",
    server = "maven",
)

maven_server(
    name = "maven",
    url = "http://central.maven.org/maven2/",
)

My BUILD:
java_binary(
    name = "RideFinish",
    srcs = ["RideFinish.java"],
    deps = [
        "//java/jar:weka",
        "@commons_cli//jar",
    ],
)

bazel build java/com/didi/strategy/ridefinish:all
ERROR: /Users/didi/git/anti-strategy/java/com/didi/strategy/ridefinish/BUILD:1:1: no such package '@commons_cli//jar': error loading package 'external': The repository named 'commons_cli' could not be resolved and referenced by '//java/com/didi/strategy/ridefinish:RideFinish'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 0.095s

**Comment by damienmg** [comment]
It should be `@commons_cli_commons_cli//jar` not `@commons_cli//jar`

**Comment by is03wlei** [comment]
Could you modify maven_jar part on the following page
http://bazel.io/docs/be/workspace.html

**Comment by damienmg** [comment]
The documentation state @guava but we updated the name with the new convention but not the following line:
`Targets can specify @guava//jar as a dependency to depend on this jar.`
