### ISSUE TITLE
[FR] Fail fast and don't retry only in case of action timeout

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/bazel#12314]
### Description of the problem / feature request:
Sometimes there’s a change in some core library that fails the CI builds in a horrific way: Everything compiles, but it does fail all the most expensive long running test target fail on ACTION TIMEOUT… 

In addition, our CI runs with two essential flags that makes it even worse:
* `-k` - to give a complete feedback and not fail fast.
* `--flaky_test_attempts=3` - to avoid failures on possible flaky tests

This means that when the above case happens - it takes a huge chunk of our remote workers 
> _**Example**: E2E test target is configured to 15m timeout to use large worker. Each re-attempt will take additional 15 minutes. So in the above case we use 45 minutes of a large worker for nothing. Imagine that we have hundreds of those, and only 600 large workers in our pool_

I wish we could distinguish between failed actions and timeout actions in the flags so that on timeout we will fail fast, but on real failures we will keep going / try again.

### Feature requests: what underlying problem are you trying to solve with this feature?
I want to allow a little more flexibility in the keep-going flag and flaky tests flag to fix the issues.
Right now - bazel flags forces me to choose either more robust builds (with possible remote workers burn out) or flaky/fail fast builds. 

A different alternative is to implement our own BES receptor and in case of TIMEOUT event - manually cancel the build process - which I think is a rather awkward workaround.

**Comment by or-shachar** [comment]
@aiuto - thanks for triaging!

I'm not sure if it relates to remote execution exactly.
It's more around bazel flags `-k` and `--flaky_test_attempts`  and distinction on how they work according to type of action failures (failed/timeout).

Some users may find this useful even without remote execution.

**Comment by aiuto** [comment]
Yes. I don't know what was going through my mind.

**Comment by philwo** [comment]
@or-shachar On the one hand, I agree with you! I had some tests timeout due to failure modes where repeating them was just a waste of time.

On the other hand, we definitely have tests on Bazel's CI that timeout due to some transient issue and pass when you rerun them. So a "don't retry on timeout" seems also problematic. :/

**Comment by or-shachar** [comment]
I agree... how can we leave the choice to the users? 
Leave the existing behavior with the flags the same but give other flags that allows to separate behavior per more specific cases.
