### ISSUE TITLE
skylark enhancement: label_list_dict and label_dict

### ISSUE THREAD

**Issue by dhbaird** [bazelbuild/bazel#1232]
For use in Skylark rules:

`label_list_dict`: Creates an attribute of type dict mapping from string to list of `Target` (label_list).

`label_dict`: Creates an attribute of type dict mapping from string to `Target` (label).

**Comment by dhbaird** [comment]
It may be okay to close this issue because I found an adequate (and satisfactory) workaround. The workaround for `label_dict`, is `zip(string_names, files)` along with a constraint check of `len(string_names) == len(files)`. E.g.,

```
my_rule(
    ...
    string_names = ["foo", "bar"],
    files = ["foo.txt", "bar.txt"],
    ...
)
```

Similarly, `label_list_dict` could be worked around by also using `filegroup`:

```
filegroup(
    name = "foogroup",
    srcs = ["foo1.txt", "foo2.txt"],
)

my_rule(
    ...
    string_names = ["foo", "bar"],
    files = [":foogroup", "bar.txt"],
    ....
)
```

**Comment by abergmeier-dsfishlabs** [comment]
I could REALLY use this. Like now.

**Comment by abergmeier-dsfishlabs** [comment]
Started https://github.com/bazelbuild/bazel/pull/2208 for this.

**Comment by brandjon** [comment]
See the cautionary comment I added [here](https://github.com/bazelbuild/bazel/blob/968422dd6e6735b6066ccbe862b6bc6ab38ce4d6/src/main/java/com/google/devtools/build/lib/packages/Type.java#L58-L80). We won't add new attribute types unless there's a pretty compelling use that can't reasonably be satisfied with workarounds.
