### ISSUE TITLE
env DEVELOPER_DIR and SDKROOT missing when linking executable file 

### ISSUE THREAD

**Issue by daimagou** [bazelbuild/bazel#12321]
### Description of the problem / feature request:
```
Use --sandbox_debug to see verbose messages from the sandbox
Error: SDKROOT not set.
external/local_config_cc/cc_wrapper.sh: line 58:  6153 Abort trap: 6           "$(/usr/bin/dirname "$0")"/wrapped_clang "$@"
```
### Feature requests: what underlying problem are you trying to solve with this feature?
```
manual export SDKROOT and DEVELOPER_DIR  env in external/local_config_cc/cc_wrapper.sh 
```
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

build an executable file for ios/macos

### What operating system are you running Bazel on?
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/11716

### Any other information, logs, or outputs that you want to share?
```
// Returns the DEVELOPER_DIR environment variable in the current process
// environment. Aborts if this variable is unset.
std::string GetMandatoryEnvVar(const std::string &var_name) {
  char *env_value = getenv(var_name.c_str());
  if (env_value == nullptr) {
    std::cerr << "Error: " << var_name << " not set.\n";
    abort();
  }
  return env_value;
}
```

**Comment by haolongzhangm** [comment]
any update for this issue ,

sames caused by upgrade the lastest xcode

**Comment by susinmotion** [comment]
It looks like the installation might be incomplete and/or Bazel might be looking in the wrong place for the developer tools. 

Could you try if you haven't:
accepting the license?
installing the command line tools for the new Xcode version?
using --xcode_version or xcode-select to point to the new Xcode version?
running `blaze shutdown`?

**Comment by daimagou** [comment]
@susinmotion I tried the method you said, but there is still the same problem

add more info:

1.Env can be found in the compile stage
```
(cd /private/var/tmp/_bazel_xxx/19af71a3f2eee621aed0a0ca59e12662/execroot/xxxx && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=13.6 \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin \
    XCODE_VERSION_OVERRIDE=11.6.0.11E708 \
  external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG '-std=c++11' -iquote 

  .....

  ...../utils.cpp -o bazel-out/ios_arm64-opt/bin/..../utils.o

```

2. Env cannot be found in the executable file generation stage
```
 (cd /private/var/tmp/_bazel_mac_ci/19af71a3f2eee621aed0a0ca59e12662/execroot/xxxx && \
 exec env - \
 external/local_config_cc/cc_wrapper.sh bazel-out/ios_arm64-opt/bin/xxxxx/libmy_test.internal_cc_library.a 
 ....

ERROR: /Users/mac/...path.../BUILD:24:1: Linking bazel-out/ios_arm64-opt/bin/....path.../my_test.unstripped... failed (Aborted): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh bazel-out/ios_arm64-opt/bin/...path..../libmy_test.internal_cc_library.a ... (remaining 15 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh bazel-out/ios_arm64-opt/bin/...path..../libmy_test.internal_cc_library.a ... (remaining 15 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Error: DEVELOPER_DIR not set.
external/local_config_cc/cc_wrapper.sh: line 56:  9557 Abort trap: 6           "$(/usr/bin/dirname "$0")"/wrapped_clang "$@"
```
I don’t understand why it will be different at different stages

**Comment by susinmotion** [comment]
Ahhh thanks for looking into this. The "missing env" issue is real. It's this one: #12049. 

But I still think there might be something else going on here... Passing to cc rules for more input.

**Comment by keith** [comment]
FWIW with my issue I've never seen an action not get the apple env that requires it.

**Comment by daimagou** [comment]
Thanks everyone for your help, close this question
