### ISSUE TITLE
Intentional compilation errors for test/java/net/starlark/java/annot/processor/testsources/ or not?

### ISSUE THREAD

**Issue by mahmoudimus** [bazelbuild/bazel#12335]
### Description of the problem / feature request:

Compilation error when attempting to build starlark tests in maven.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

It's unclear if this is intentional, but I'm unable to run the tests because of a few compilation errors:

- https://github.com/bazelbuild/bazel/blob/master/src/test/java/net/starlark/java/annot/processor/testsources/MultipleSelfCallMethods.java#L34 
-https://github.com/bazelbuild/bazel/blob/master/src/test/java/net/starlark/java/annot/processor/testsources/MultipleSelfCallMethods.java#L39

Is that intentional or would a patch like this be needed?

```patch
@@ -31,11 +31,11 @@ public class MultipleSelfCallMethods implements StarlarkValue {
       },
       documented = false)
   public StarlarkInt selfCallMethod(String one, StarlarkInt two) {
-    return 0;
+    return StarlarkInt.of(0);
   }

   @StarlarkMethod(name = "selfCallMethodTwo", selfCall = true, documented = false)
   public StarlarkInt selfCallMethodTwo() {
-    return 0;
+    return StarlarkInt.of(0);
   }
 }
```
and 

- https://github.com/bazelbuild/bazel/blob/master/src/test/java/net/starlark/java/annot/processor/testsources/StructFieldWithInvalidInfo.java#L28

```patch
@@ -15,6 +15,7 @@
 package net.starlark.java.annot.processor.testsources;

 import net.starlark.java.annot.StarlarkMethod;
+import net.starlark.java.eval.StarlarkThread;
 import net.starlark.java.eval.StarlarkValue;
```

### What operating system are you running Bazel on?

MacOS X Catalina 10.15.7

### What's the output of `bazel info release`?

Probably not relevant.. but "development version"

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Probably not relevant.. but `mvn clean package`

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
https://github.com/bazelbuild/bazel
898f27602c1f8cfea233df36d91f2cc9bc7d01f9
898f27602c1f8cfea233df36d91f2cc9bc7d01f9
```

**Comment by brandjon** [comment]
Do we even support running Starlark's tests from Maven? I'm unfamiliar with that.

These tests are supposed to fail an annotation processor check. They also happen to contain other compilation errors, but apparently those don't supersede the expected annotation errors, so the test still passes.

It'd be harmless to fix the compilation errors if you want to send a PR, but I'm unclear on what it's blocking.

**Comment by mahmoudimus** [comment]
@brandjon thanks for the response. I'm happy to submit a PR and just to clarify, obviously these are not blocking anything on bazel's side. However, for the folks who are using bazel and not maven, the compilation errors do make it inconvenient for non-bazel projects. 

I maintain a patch that I apply and totally happy to continue to maintain, but if we can patch upstream, it has beneficial side effects without (hopefully!) any downsides that I can see.

**Comment by brandjon** [comment]
Sure, you can send the PR my way.
