### ISSUE TITLE
bazel_appengine broken by 4b71d2e1bc3afa0ce0a5b6e68dac3c559654d975

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/bazel#1233]
As of commit 4b71d2e1bc3afa0ce0a5b6e68dac3c559654d975

bazel run :some_appengine_war 

 local-fastbuild/bin/refapp.runfiles/external/bazel_tools/tools/zip/zipper/zipper: No such file or directory
Error: Could not find or load main class com.google.appengine.tools.development.DevAppServerMain

Using the io_bazel_rules_appengine pattern.

**Comment by kchodorow** [comment]
Skylark's short_path should point to the runfiles path, it's currently pointing at the exec root.

**Comment by pmbethe09** [comment]
Happened again -- but this time opened as:
https://github.com/bazelbuild/rules_appengine/issues/15
