### ISSUE TITLE
`maven_jar` requires system installed `mvn`

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#12331]
### Description of the problem / feature request:

`maven_jar` requires `mvn` to be installed on the system running the build. 

### Feature requests: what underlying problem are you trying to solve with this feature?

Requiring `mvn` leads Bazel builds to have an implicit dependency on this binary being installed. Worse, the download of the jar sidesteps bazel's own downloader, and it's not entirely clear how to configure mvn to respect (eg) custom proxies.

It's not clear why this isn't just a transformation of the repo and the artifact coordinates, delegating down to `http_file` or `http_jar`

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 3.1.0

**Comment by jin** [comment]
This is pretty much not maintained anymore, and is just outperformed by pretty much every solution out there, in terms of raw performance and feature set. I'm inclined to close this as wontfix.

**Comment by philwo** [comment]
I agree with Jin. The built-in Maven rules will be removed at some point and are not maintained, as the community has developed much better support for Maven in the meantime.

**Comment by kylecordes** [comment]
Would it be reasonable to mark this deprecated somehow, as a step toward eventual removal?
