### ISSUE TITLE
ctx.build_file_path omits "external/" prefix starting in Bazel 3.7.0

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel#12344]
### Description of the problem / feature request:

This is a potential regression. In Bazel 3.6.0, `ctx.build_file_path` included an `external/` prefix for build files in external repositories. This prefix is no longer present in Bazel 3.7.0.

This caused bazelbuild/rules_go#2685, though that was a (newly exposed) pre-existing bug. rules_go will stop using `ctx.build_file_path` in the next patch release.

The documentation for [`ctx.build_file_path`](https://docs.bazel.build/versions/3.6.0/skylark/lib/ctx.html#build_file_path) says "Returns path to the BUILD file for this rule, relative to the source root.", so perhaps the new behavior is correct.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
bazel build @write//:write

-- BUILD.bazel --

-- WORKSPACE --
workspace(name = "main")

load(":def.bzl", "write_repo")

write_repo(name = "write")
-- def.bzl --
def _write_repo_impl(ctx):
    ctx.file("BUILD.bazel", """load("@main//:def.bzl", "write_build_file_path")

write_build_file_path(
    name = "write",
    out = "write.txt",
)
""")

write_repo = repository_rule(
    implementation = _write_repo_impl,
)

def _write_build_file_path_impl(ctx):
    ctx.actions.write(ctx.outputs.out, ctx.build_file_path)

write_build_file_path = rule(
    implementation = _write_build_file_path_impl,
    attrs = {
        "out": attr.output(mandatory = True),
    },
)
```

### What operating system are you running Bazel on?

macOS 10.15.6

### What's the output of `bazel info release`?

3.7.0

**Comment by jin** [comment]
This seems potentially related to the "external" prefix refactoring work recently.

cc @gyias

**Comment by lberki** [comment]
Yeah, it looks like its related to the refactoring @gyias is doing these days. The reason why I thought this isn't a big deal is that the concept of "source root" is not very relevant in the analysis/execution phases and thus there isn't a really "principled" use of this method.

What do you use it for? All things being equal, I'd prefer to keep it as it is -- @gyias changed where the "source root" starts, so the behavior change is consistent with the documentation.

**Comment by jayconrod** [comment]
It was used to produce `-I` flags for cgo (mixed Go and C) code. The includes were meant to be relative to the package directory, and there might not actually be any source files there.

That wasn't a very principled use of `ctx.build_file_path`, either from the Bazel perspective (probably wouldn't work for generated headers) or for setting cgo include paths (Go normally requires all files to be in the same directory).  rules_go will stop using it in the next patch release.

I think it's fine if this is closed WAI. Mostly wanted to check if it was an intentional change or if it was affecting other rule sets.

**Comment by lberki** [comment]
Let's close this as WAI then. TBH, I was surprised that `ctx.build_file_path` is even a thing :)

**Comment by sitaktif** [comment]
FYI this broke rules_rust as well - https://github.com/bazelbuild/bazel/issues/12344

We're working around the issue but still haven't found a stable API to get the directory path of the current (external) package relative to the exec root.

**Comment by lberki** [comment]
@sitaktif , I'm having a hard time connecting the thread of https://github.com/bazelbuild/rules_rust/issues/467 to changes in `ctx.build_file_path`. Is it the change that caused it?

I thought `Label.workspace_root` + `Label.package` together would give the location of the source files in the package relative to the exec root. Am I mistaken?

**Comment by sitaktif** [comment]
@lberki https://github.com/bazelbuild/rules_rust/issues/467 refers to https://github.com/bazelbuild/rules_rust/pull/464/files#diff-ecce7f6cdb4bc2f884f23fccb9a20174ad2b357dc6745314054e5eb8b784d2e0R450, which is a fix in response to the `ctx.build_file_path` change in Bazel.

This was what the code looked like before: https://github.com/sitaktif/rules_rust/blob/d76df03551232ac69c10c81c3dadac88fb02cf21/rust/private/rustc.bzl#L456 - and stopped working when the value changed for external packages.

We ended up testing for Bazel's version (`< 3.7.0` vs `>= 3.7.0`) in the meantime until we find a better solution.

**Comment by gyias** [comment]
FYI, it'll change once again in the next release, so that the returned `build_file_path` value won't even have the repo name, either. Looking at the fix change, I think it'll make it simpler since you won't have to modify `workspace_root_items` before inserting it, though you'll still need the version check?

**Comment by sitaktif** [comment]
Thanks for the heads up @gyias.

Given we know this is going to change again, it would be nice to have some API that allows computing "a path relative to the exec root" with the guarantee that it won't break in a future release. Do you think we could have either a starlark function/method for this (or a guarantee it won't change again)?

**Comment by gyias** [comment]
A new method to return the exec path to the rule's BUILD file sounds reasonable to me. It'll be more useful than `build_file_path` at least, I imagine. Will need to make sure the use case is valid, though. @jin @lberki What do you think?

BTW, have you tried using `$(execpath <filename>)` instead? Not sure if it's compatible with your use case, but it's guaranteed to return the exec path to the given rule or file.

https://github.com/bazelbuild/examples/tree/master/make-variables

**Comment by sitaktif** [comment]
> I thought Label.workspace_root + Label.package together would give the location of the source files in the package relative to the exec root. Am I mistaken?

@lberki sorry I realised I didn't address your second point and... I think you nailed it, thanks! I'm testing with a couple of projects / examples but it seems to work like a charm so far.

**Comment by lberki** [comment]
/thumbs up I'm glad to hear that :)
