### ISSUE TITLE
rdeps not working for java_library

### ISSUE THREAD

**Issue by dmivankov** [bazelbuild/bazel#12359]
### Description of the problem / feature request:

Reverse dependencies of a java_library don't include java_libraries referring to it via deps

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

BUILD
```python
java_library(
	name = "a",
)
java_library(
	name = "b",
	deps = [":a"],
)
```
```sh
$ bazel query 'deps(:b) intersect //...'
//:b
//:a
$ bazel query 'rdeps(:a, //...)'
//:a
```
### What operating system are you running Bazel on?

NixOS

### What's the output of `bazel info release`?

release 3.3.1- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

NixOS nixpkgs collection

**Comment by benjaminp** [comment]
The first argument of `rdeps` is the universe, so the OP's query asks what the transitive rdeps of `//...` intersected with `//:a` are.

**Comment by dmivankov** [comment]
Oh, right
```sh
$ bazel query 'rdeps(//..., :a)'
//:b
//:a
```
not an issue then
