### ISSUE TITLE
How to set the cwd when a genrule's cmd is executed

### ISSUE THREAD

**Issue by lgmcode** [bazelbuild/bazel#12351]
Hi,
My project depends on an external git repository and I add it to the WORKSPACE file using `new_git_repository`. This external git repository has a python module and I need to execute it with `python -m module_name` to generate some C++ source and header files for the main repository. I use genrule with a `cmd = "python -m module_name"`, but bazel outputs: No module named module_name. Then I use `cmd = "pwd"` to see where I am, it tells me I'm not in the root directory of the external git repository. How to change the cwd of the execution of the `cmd` to the root directory of the external git repository or how to run a python module in the external git repository?

### What operating system are you running Bazel on?

> Ubuntu 16.04

### What's the output of `bazel info release`?

> release 3.7.0

###  Have you found anything relevant by searching the web?

> Google "bazel genrule change cwd"

**Comment by lgmcode** [comment]
`cmd = "cd external/my_repo_name && python -m module_name --out-path=output`
Use the `cmd` above it can generate the source files in the `output` directory, now the question is what is the target label to locate these generated files?

Actually, I want to use [glad](https://github.com/Dav1dde/glad) in my project, this is my `WORKSPACE` file
```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")

new_git_repository(
    name = "glad",
    build_file = "glad/BUILD",
    remote = "https://github.com/Dav1dde/glad.git",
    tag = "v0.1.34",
)
```
and this is my `external/glad/BUILD` file
```
load("@rules_cc//cc:defs.bzl", "cc_library")

genrule(
    name = "glad_srcs",
    srcs = glob(["glad/**/*"]),
    outs = [
        "output/src/glad.c",
        "output/include/glad/glad.h",
        "output/include/KHR/khrplatform.h",
    ],
    cmd = " && ".join([
        "cd external/glad",
        "python -m glad --profile=compatibility --api=gl=2.1 --generator=c --spec=gl --extensions=GL_EXT_framebuffer_object --out-path=output --reproducible",
    ]),
)

cc_library(
    name = "glad",
    srcs = [":glad_srcs"],
    hdrs = [":glad_srcs"],
    includes = ["output/include"],
    linkopts = ["-dl"],
    visibility = ["//visibility:public"],
)
```

**Comment by lberki** [comment]
This is not possible by design; the working directory of every action is the execroot. As you said, `cd` is a workaround, which invalidates `$(location)`. 

There are a number workarounds we use:

```
genrule(cmd='FOO_PATH="$$PWD/$(location :foo)"; cd <somewhere>; process $FOO')
```

Or:

```
genrule(cmd='FOO_PATH="$$(readlink -f $(location :foo))"; cd <somewhere>; process $FOO_PATH')
```

**Comment by lgmcode** [comment]
@lberki Thanks, I think I got your philosophy

**Comment by allsey87** [comment]
> This is not possible by design; the working directory of every action is the execroot. As you said, `cd` is a workaround, which invalidates `$(location)`.
> 
> There are a number workarounds we use:
> 
> ```
> genrule(cmd='FOO_PATH="$$PWD/$(location :foo)"; cd <somewhere>; process $FOO')
> ```
> 
> Or:
> 
> ```
> genrule(cmd='FOO_PATH="$$(readlink -f $(location :foo))"; cd <somewhere>; process $FOO_PATH')
> ```

Is this still best practice with Bazel? As of this comment, this Github issue is the top result for the Google search "genrule bazel working directory". Is there more information in the official Bazel documentation?

**Comment by lberki** [comment]
Yep, this is still best practice. As far as I understand, the aforementioned workaround is reasonable enough and I haven't heard a lot of people complaining about this particular rough edge. I'll send a change to add documentation about their cwd to genrule.
