### ISSUE TITLE
`repository_ctx.download_and_extract` should create necessary directories

### ISSUE THREAD

**Issue by colinmarc** [bazelbuild/bazel#1235]
This is exactly the same as https://github.com/bazelbuild/bazel/issues/1078. `repository_ctx.download_and_extract` doesn't create the destination dir, so you have to do something like:

```
ctx.file(ctx.path("empty"), "")
ctx.download_and_extract(...)
```

**Comment by zaphar** [comment]
This bug caused my no end of confusion while implementing mono as an external repository. Thanks for the workaround 👍

**Comment by damienmg** [comment]
This is a duplicate of #1172
