### ISSUE TITLE
marketplace.gcr.io/google/bazel is missing recent Bazel releases

### ISSUE THREAD

**Issue by shikhar** [bazelbuild/bazel#12367]
I reported in https://github.com/GoogleCloudPlatform/container-definitions/issues/12037 but this is perhaps the more appropriate place:

`latest` release is currently 3.5.0 here https://console.cloud.google.com/gcr/images/cloud-marketplace/GLOBAL/google/bazel

**Comment by philwo** [comment]
@shikhar Thanks for reporting this. We're on it, but it'll take a bit more time to fix this.

**Comment by kylecordes** [comment]
If anyone knows where the code is located that creates this, it would be helpful for those of us looking to create an as-similar-as-possible workaround.

**Comment by philwo** [comment]
The current Bazel docker image is built using github.com/bazelbuild/rules_docker + Bazel. The source code for the image is [here](https://github.com/GoogleCloudPlatform/container-definitions/blob/e7f54f6f94a806bfeca005a14a37034ba802a99c/ubuntu1604_bazel/BUILD#L53). The image is built using Google Cloud Build ([config](https://github.com/GoogleCloudPlatform/container-definitions/blob/e7f54f6f94a806bfeca005a14a37034ba802a99c/ubuntu1604_bazel/cloudbuild.yaml)).

Here's my tracking issue for the future plan: https://github.com/bazelbuild/continuous-integration/issues/1060
