### ISSUE TITLE
cc_library's strip_include_prefix broke in 3.7.0.

### ISSUE THREAD

**Issue by otisonoza** [bazelbuild/bazel#12361]
### Description of the problem / feature request:

strip_include_prefix seems to be broken in 3.7.0.
In 3.6.0 it was fine.

`BUILD:9:11: in cc_library rule //bazel/libs/google_breakpad:breakpad_client: header 'external/google_breakpad/src/tools/windows/converter_exe/http_download.h' is not under the specified strip prefix 'external/google_breakpad/src'`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
cc_library(
    name = "breakpad_client",
    srcs = [
        "@google_breakpad//:srcs",
    ],
    hdrs = [
        "@google_breakpad//:hdrs",
    ],
    linkopts = [
        "-lpthread",
    ],
    strip_include_prefix = "/external/google_breakpad/src",
    visibility = ["//visibility:public"],
)
```

WORKSPACE:
```
new_git_repository(
    name = "google_breakpad",
    build_file = "//bazel/libs/google_breakpad:repo.BUILD",
    commit = "792e6b2143bffd46c93e8f80c10d00d8289b8d73",
    remote = "https://github.com/google/breakpad.git",
)
```
repo.BUILD:
```
filegroup(
    name = "srcs",
    srcs = [
        "src/client/linux/crash_generation/crash_generation_client.cc",
        "src/client/linux/dump_writer_common/thread_info.cc",
        "src/client/linux/dump_writer_common/ucontext_reader.cc",
        "src/client/linux/handler/exception_handler.cc",
        "src/client/linux/handler/minidump_descriptor.cc",
        "src/client/linux/log/log.cc",
        "src/client/linux/microdump_writer/microdump_writer.cc",
        "src/client/linux/minidump_writer/linux_dumper.cc",
        "src/client/linux/minidump_writer/linux_ptrace_dumper.cc",
        "src/client/linux/minidump_writer/minidump_writer.cc",
        "src/client/minidump_file_writer.cc",
        "src/common/convert_UTF.h",
        "src/common/convert_UTF.cc",
        "src/common/linux/elfutils.cc",
        "src/common/linux/file_id.cc",
        "src/common/linux/guid_creator.cc",
        "src/common/linux/linux_libc_support.cc",
        "src/common/linux/memory_mapped_file.cc",
        "src/common/linux/safe_readlink.cc",
        "src/common/md5.cc",
        "src/common/simple_string_dictionary.cc",
        "src/common/string_conversion.cc",
    ],
    visibility = ["//visibility:public"],
)
     
filegroup(
    name = "hdrs",
    srcs = glob(["src/**/*.h"]),
    visibility = ["//visibility:public"]
)
```

### What operating system are you running Bazel on?

Debian 9.

### What's the output of `bazel info release`?

release 3.7.0

###  Have you found anything relevant by searching the web?

In 3.7.0 there doesn't seem to be any breaking changes: https://blog.bazel.build/2020/10/20/bazel-3-7.html

**Comment by otisonoza** [comment]
getRootRelativePath != getRepositoryRelativePath ?

* https://github.com/bazelbuild/bazel/blob/3.6.0/src/main/java/com/google/devtools/build/lib/rules/cpp/CcCompilationHelper.java#L886
* https://github.com/bazelbuild/bazel/blob/3.7.0/src/main/java/com/google/devtools/build/lib/rules/cpp/CcCompilationHelper.java#L928

**Comment by otisonoza** [comment]
build@as:~/.cache/bazel$ find . -name "linux_ptrace_dumper\.h" -type f
./_bazel_build/46b74a3c1f9a666f55591a5719d9f2ba/external/google_breakpad/src/client/linux/minidump_writer/linux_ptrace_dumper.h

**Comment by gyias** [comment]
The change was intentional; `strip_include_prefix` is not supposed to include the workspace root path.
https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library.strip_include_prefix
"If it's a relative path, it's taken as a package-relative one. **If it's an absolute one, it's understood as a repository-relative path.**"

I'll check with the team how we'll handle this kind of external header direct references via `hdrs` with `strip_include_prefix`.

In the meantime, I believe you can fix it by referencing the breakpad files as a library by changing `repo.BUILD` like this:
```
cc_library(
    name = "breakpad_lib",
    srcs = [
        "src/client/linux/crash_generation/crash_generation_client.cc",
        "src/client/linux/dump_writer_common/thread_info.cc",
        "src/client/linux/dump_writer_common/ucontext_reader.cc",
        "src/client/linux/handler/exception_handler.cc",
        "src/client/linux/handler/minidump_descriptor.cc",
        "src/client/linux/log/log.cc",
        "src/client/linux/microdump_writer/microdump_writer.cc",
        "src/client/linux/minidump_writer/linux_dumper.cc",
        "src/client/linux/minidump_writer/linux_ptrace_dumper.cc",
        "src/client/linux/minidump_writer/minidump_writer.cc",
        "src/client/minidump_file_writer.cc",
        "src/common/convert_UTF.h",
        "src/common/convert_UTF.cc",
        "src/common/linux/elfutils.cc",
        "src/common/linux/file_id.cc",
        "src/common/linux/guid_creator.cc",
        "src/common/linux/linux_libc_support.cc",
        "src/common/linux/memory_mapped_file.cc",
        "src/common/linux/safe_readlink.cc",
        "src/common/md5.cc",
        "src/common/simple_string_dictionary.cc",
        "src/common/string_conversion.cc",
    ],
    hdrs = glob(["src/**/*.h"]),
    strip_include_prefix = "/src",
    visibility = ["//visibility:public"],
)
```

And then, change the `breakpad_client` build rule so that it simply depends on `breakpad_lib` instead of directly accessing its src and hdr files. This way you can include its header files without specifying `external/google_breakpad/src` in your clients.

Note that the clients of `breakpad_client` will need to depend on `breakpad_lib` as well, **if** their source files include `breakpad_lib`'s header files. (though bazel currently doesn't detect this as an error.)
https://docs.bazel.build/versions/master/be/c-cpp.html#hdrs

**Comment by oquenchil** [comment]
Closing as this is WAI it seems.
