### ISSUE TITLE
`target_compatible_with` failing with `analysis_test`

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#12366]
Using the new [`target_compatible_with` feature](https://github.com/bazelbuild/bazel/pull/10945) with an [`analysis_test`](https://github.com/bazelbuild/bazel-skylib/blob/182046f090d6ecae264c7e5d520da096370287e2/rules/analysis_test.bzl) fails with this error on incompatible platforms:

```
ERROR: /workdir/test/BUILD:13:29: in coverage_xcode_prefix_map_test rule //test:coverage_settings_xcode_prefix_map: rules with analysis_test=true must return an instance of AnalysisTestResultInfo
ERROR: Analysis of target '//test:coverage_settings_xcode_prefix_map' failed; build aborted: Analysis of target '//test:coverage_settings_xcode_prefix_map' failed
```

https://buildkite.com/bazel/rules-swift-swift/builds/1980#af8b4f17-01b9-4e2d-99d0-93ef5abc6203

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Example failure here for a test that is only compatible with macOS, and therefore fails with the above error on Linux https://github.com/bazelbuild/rules_swift/pull/514

Flipping the `target_compatible_with` condition to only support Linux also makes it fail the same way on macOS.

### What operating system are you running Bazel on?

macOS / Linux

### What's the output of `bazel info release`?

```
2020/10/27 17:39:36 Using unreleased version at commit f3604a6c9c433c42f3adfa2bc1551150482aa73e
development version
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

`USE_BAZEL_VERSION=last_green` with bazelisk

**Comment by philsc** [comment]
Looking at this now.
