### ISSUE TITLE
Bazel should not crash when receiving gRPC Goaway load_shed

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#12363]
In https://github.com/bazelbuild/continuous-integration/issues/1055 a few users reported that Bazel crashes with a stack trace when we receive a "Goaway" or "load_shed" reply from the remote execution service.

These replies are sent by load balancers when they're approaching or have reached their load limit and should cause Bazel to reconnect (?), but certainly not crash.

**Comment by ulfjack** [comment]
I've previously seen cases kinda like this, and Bazel was properly retrying up to its retry limit. I'm not sure that there's a bug here.

**Comment by bergsieker** [comment]
This has been root caused to bad server behavior sending GOAWAY frames in a way that was out of spec. No code change is required in Bazel.

I think the error in bazelbuild/continuous-integration#1055 was mischaracterized: that's just the exception logged via --verbose_failures. Bazel did not crash and correctly terminated the build with an error.

**Comment by philwo** [comment]
I'm not sure that Bazel should crash with an exception though for cases that it handles "correctly"?

IMHO exceptions indicate an unexpected condition and should not occur in expected cases - a user-friendly error message would be more appropriate then.

**Comment by coeuvre** [comment]
> I'm not sure that Bazel should crash with an exception though for cases that it handles "correctly"?

Bazel didn't crash in that case (failed to read remote cache due to GOAWAY), instead, it prints `WARNING: Reading from Remote Cache:` with exception details (enabled by `--verbose_failures`) and fallbacks to execute the action.

**Comment by philwo** [comment]
@coeuvre Thanks for the explanation!
