### ISSUE TITLE
out of `genrule` does not inherit tags from parent genrule

### ISSUE THREAD

**Issue by guibou** [bazelbuild/bazel#12365]
### Description of the problem / feature request:

I observed that when using `--build_tag_filters`, the `out` of some `genrule` are filtered in an explicit bazel build even if their parent `genrule` does have the required `tags`.

Said otherwise, if I have a genrule `//:motor_genrule` which produces `motor.elf` as `out` and does have the `tags` `stm32`, building `//:motor.elf` with `--build_tag_filters=stm32` won't build the target.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

file `BUILD`:
```bazel
genrule(
    name = "motor_genrule",
    srcs = [],
    outs = ["motor.elf"],
    cmd = "echo 'hello' > $@",
    tags = ["stm32"],
)
```

file `WORKSPACE`:

```
workspace(name="test")
```

building `//:motor_genrule` with or without `--build_tag_filters` does build the file:

```
$ bazel build //:motor_genrule
INFO: Analyzed target //:motor_genrule (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:motor_genrule up-to-date:
  bazel-bin/motor.elf
INFO: Elapsed time: 0.055s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

$ bazel build //:motor_genrule --build_tag_filters=stm32
INFO: Analyzed target //:motor_genrule (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:motor_genrule up-to-date:
  bazel-bin/motor.elf
INFO: Elapsed time: 0.066s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

(see the "is up to date")

On the other hand, building `//:motor.elf` (the `out` of the `genrule`) does not work when `--build_tag_filters` appears.

```
$ bazel build //:motor.elf
INFO: Analyzed target //:motor.elf (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:motor.elf up-to-date:
  bazel-bin/motor.elf
INFO: Elapsed time: 0.055s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

$ bazel build //:motor.elf --build_tag_filters=stm32
INFO: Analyzed 0 targets (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 0.030s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

### What operating system are you running Bazel on?

Linux (NixOS)

### What's the output of `bazel info release`?

```
release 3.3.1- (@non-git)
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Build from `nixpkgs`.

**Comment by lberki** [comment]
Good catch! I think this should be fixed, but I can't give you a timeline.
