### ISSUE TITLE
incompatible_macos_set_install_name: Set -install_name when linking dynamic libraries on macOS

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/bazel#12370]
**Flag**: `--incompatible_macos_set_install_name`

This incompatible change will add `-install_name=@rpath/<runtime_solib_name>` to the comman-line of link actions for creating dynamic libraries on macOS. This will allow us to remove the hacky wrapper scripts that rely on the runtime solibs being symlinks.

# Migration

TBD.

**Comment by keith** [comment]
@steeve this change https://github.com/bazelbuild/bazel/pull/12304 only broke cgo, since you've been around that area it might interest you

**Comment by steeve** [comment]
absolutely! thank you i'll take a look, cc @jayconrod

**Comment by fmeum** [comment]
I just discovered this flag while working on enabling all remote tests on macOS (https://github.com/bazelbuild/bazel/pull/23085). Without it, dylib discovery from runfiles will not work correctly for tools (see `test_cc_binary_tool_with_dynamic_deps`).
