### ISSUE TITLE
Downstream projects broken by toolchain change

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#12374]
Culprit: 22b4dbcaf05756d506de346728db3846da56b775

Looks like this defines `target_compatible_with` in native rule definitions, which breaks starlark rules which themselves define `target_compatible_with`.

Example failure: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1730#4d3a9a33-e977-4628-a935-215399f01bc2

```
ERROR: Traceback (most recent call last):
--
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/16110e835b9d4ea88c095e954d089457/external/bazel_toolchains/rules/rbe_repo.bzl", line 621, column 34, in <toplevel>
  | _rbe_autoconfig = repository_rule(
  | Error in repository_rule: There is already a built-in attribute 'target_compatible_with' which cannot be overridden
```

**Comment by c-parsons** [comment]
@gregestren @katre @philsc @AustinSchuh

**Comment by katre** [comment]
Looks like `target_compatible_with` is declared differently than `exec_compatible_with`:

- `target_compatible_with` is declared in [`BaseRuleClasses.commonCoreAndStarlarkAttributes`](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/BaseRuleClasses.java;drc=22b4dbcaf05756d506de346728db3846da56b775;l=339), which means it is picked up by all rules, native, starlark, and repository
- `exec_compatible_with` is declared twice separately:
   - [`BaseRuleClasses.RuleBase`](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/BaseRuleClasses.java;drc=3ce5531d9c1b1431b6e44ae6dfffd946e842cb28;l=451), which is the ancestor of all native non-repository rules
   - [`StarlarkRuleClassFunctions.baseRule`](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleClassFunctions.java;drc=3ce5531d9c1b1431b6e44ae6dfffd946e842cb28;l=145), which is the ancestor of all Starlark non-repository rules.

So a simple fix is to make `target_compatible_with` like `exec_compatible_with`.

I'll send out a PR shortly to address this.
