### ISSUE TITLE
0.2.3 release

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1238]
We should cherry-pick the homebrew fix 87a58589d6770a6e9a0f998274bfe69f1feb6014.

Baseline will be 85834ad with cherry-pick of 5d5a3cc

**Comment by damienmg** [comment]
oops wrong commit.
baseline is a7fea8a cherry-pick is correct at 5d5a3cc

**Comment by damienmg** [comment]
I cannot identify other changed that need cherry-picking, I'll wait for ci push to complete and cut the release.

/cc @johnynek fyi this will include the fix for homebrew.

**Comment by damienmg** [comment]
Unfortunately there is still an issue with 87a5858, I need to roll it back so I can find the correct way.

**Comment by damienmg** [comment]
6dab815eaf86fcaa451d21d194d6897bf825f246 is the fix for homebrew. if everything's ok I am going to cut the release soonish

**Comment by johnynek** [comment]
`\o/`

**Comment by damienmg** [comment]
Ok we have to cherry-pick also ec2657f

As there is a new release inside google3, baselining on this new one, that is 5a2dd7a2099cfa5a50b07d2b407e478043727472

Good thing is with that RC, no cherry-pick needed. So creating 0.2.3 \o/

**Comment by damienmg** [comment]
Released. PR for Homebrew on homebrew/homebrew-core#1232
