### ISSUE TITLE
Documentation issue: fragments

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel#12392]
Documentation URL: https://docs.bazel.build/versions/master/skylark/lib/fragments.html

This link looks pretty malformed:

> See [rules documentation](https://docs.bazel.build/versions/master/skylark/rules.DOC_EXT#configuration-fragments) for details.

**Comment by MatthewBerk** [comment]
To add on to this,
link for 'See _rules documentation_ for details' is this
https://docs.bazel.build/versions/master/skylark/rules.DOC_EXT#configuration-fragments

when it should be this
https://docs.bazel.build/versions/master/skylark/rules.html#configuration-fragments

**Comment by keith** [comment]
The C++ / `cpp` fragment docs are also entirely missing https://docs.bazel.build/versions/master/skylark/lib/skylark-configuration-fragment.html https://docs.bazel.build/versions/master/skylark/lib/cpp.html

**Comment by brandjon** [comment]
I think the current versions of these pages fixed whatever issues are described above.

* https://bazel.build/rules/lib/fragments
* https://bazel.build/rules/lib/cpp
