### ISSUE TITLE
ci.bazel.io's Bazel job is failing on Linux

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1239]
ERROR: /home/ci/workspace/Bazel/JAVA_VERSION/1.8/PLATFORM_NAME/linux-x86_64/src/main/tools/BUILD:31:1: C++ compilation of rule '//src/main/tools:namespace-sandbox' failed: namespace-sandbox failed: error executing command /home/ci/.cache/bazel/_bazel_ci/5f3cd5a16c8c04003810da50910b348c/linux-x86_64/_bin/namespace-sandbox ... (remaining 39 argument(s) skipped).
src/main/tools/namespace-sandbox.c:707: execvp(argv[0], argv): No such file or directory

**Comment by damienmg** [comment]
http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=linux-x86_64/526/console

**Comment by damienmg** [comment]
It fails while `src:dummy_darwin_tool_src_tools_xcode_xcrunwrapper_xcrunwrapper`.

Not reproducible on my workstation

**Comment by damienmg** [comment]
oops that's in determinism test.

**Comment by damienmg** [comment]
Ok that's C++ compilation so definitely coming from the C++ auto-configuration. Let see what's wrong

**Comment by Cescante** [comment]
Why is the commit rolled back? I'm getting this issue on ubuntu 16.04 for all bazel versions starting 0.2.2, and
`error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]`
for bazel 0.2.1 and before, which may or may not be related to the "D_FORCE_INLINES" issue with compiling tensorflow for Xerus.
