### ISSUE TITLE
Remote Downloader: No retry after receiving a CacheNotFoundException

### ISSUE THREAD

**Issue by mmikitka** [bazelbuild/bazel#12417]
### Description of the problem / feature request:

Using `--experimental_remote_downloader` with a https://github.com/buchgr/bazel-remote remote cache, the build failed with the following error, upon encountering a CacheNotFoundException.

I expected Bazel to fallback to fetching the artifact in the event of a cache miss.

```
INFO: Repository build_bazel_rules_nodejs instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/gitlab/.cache/bazel/_bazel_gitlab/856f582f3053cc7df99ab29b906d93f4/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'build_bazel_rules_nodejs':
   com.google.devtools.build.lib.remote.common.CacheNotFoundException: Missing digest: 0f2de53628e848c1691e5729b515022f5a77369c76a09fbe55611e12731c90e3/1000820
ERROR: no such package '@build_bazel_rules_nodejs//': com.google.devtools.build.lib.remote.common.CacheNotFoundException: Missing digest: 0f2de53628e848c1691e5729b515022f5a77369c76a09fbe55611e12731c90e3/1000820
INFO: Elapsed time: 35.390s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Job failed: command terminated with exit code 1
```

### Feature requests: what underlying problem are you trying to solve with this feature?

More reliable builds.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Unsure.

### What operating system are you running Bazel on?

Linux Ubuntu 18.04

### What's the output of `bazel info release`?

release 3.4.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Here are all the remote-related configs:
```
common:ci-remote-cache --remote_cache=grpc://bazel-remote-cache.bazel-remote-cache.svc.cluster.local:9092
common:ci-remote-cache --experimental_remote_downloader=grpc://bazel-remote-cache.bazel-remote-cache.svc.cluster.local:9092
common:ci-remote-cache --remote_local_fallback
common:ci-remote-cache --remote_max_connections=50
common:ci-remote-cache --remote_retries=1
common:ci-remote-cache --remote_timeout=60
common:ci-remote-cache --experimental_guard_against_concurrent_changes
```

**Comment by dhalperi** [comment]
This is also happening for us with 3.7.0

**Comment by jmillikin-stripe** [comment]
This indicates a bug in the remote downloader, not in Bazel -- it should not be returning an OK response for resources that are not present in the remote cache.

**Comment by mmikitka** [comment]
Thank you @jmillikin-stripe . I submitted the following ticket against `buchgr/bazel-remote`: https://github.com/buchgr/bazel-remote/issues/377

**Comment by dhalperi** [comment]
I've had no issues (for almost 3 weeks) along these lines after upgrading `buchgr/bazel-remote` past the version with concurrency fixes.

**Comment by coeuvre** [comment]
Closing since this is fixed by bazel-remote.

**Comment by mostynb** [comment]
Just to clarify, there was a bug in an older version of bazel-remote that caused these downloads to sometimes fail on the cache server.

It is a separate question if the bazel should attempt to download assets itself if the cache server fails (eg #12528). IMO it would be good if bazel at least had an option to do this.
