### ISSUE TITLE
Bazel can't find the following tools:     cl.exe, link.exe, lib.exe, ml64.exe for x64 target architecture

### ISSUE THREAD

**Issue by amitkayal** [bazelbuild/bazel#12433]
Hi,

I am trying to build the demo application with visual 2017 VS Code installed but facing this issue. Have seen earlier similar issue and tried workaround but did not work.

C:\Users\akayal\mediapipe_repo\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:/Users/akayal/AppData/Local/Continuum/anaconda3/python.exe" mediapipe/examples/desktop/hello_world
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (55 packages loaded, 1315 targets configured).
INFO: Found 1 target...
ERROR: C:/users/akayal/_bazel_akayal/awz7mfov/external/com_google_protobuf/BUILD:120:11: C++ compilation of rule '@com_google_protobuf//:protobuf_lite' failed (Exit 1)

The target you are compiling requires Visual C++ build tools.
Bazel couldn't find a valid Visual C++ build tools installation on your machine.

Visual C++ build tools seems to be installed at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC
But Bazel can't find the following tools:
    cl.exe, link.exe, lib.exe, ml64.exe
for x64 target architecture

Please check your installation following https://docs.bazel.build/versions/master/windows.html#using

Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 18.112s, Critical Path: 4.12s
INFO: 133 processes: 133 internal.
FAILED: Build did NOT complete successfully

C:\Users\akayal\mediapipe_repo\mediapipe>bazel --version
bazel 3.6.0

C:\Users\akayal\mediapipe_repo\mediapipe>

**Comment by philwo** [comment]
@amitkayal Could you please check whether you are using 32-bit or 64-bit Windows and report back?

Here's an article that explains how to check it: https://support.microsoft.com/en-us/windows/32-bit-and-64-bit-windows-frequently-asked-questions-c6ca9541-8dce-4d48-0415-94a3faa2e13d

**Comment by arianatri** [comment]
have you found the solution?
