### ISSUE TITLE
Create runfiles without dedicated target for each executable

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/bazel#12459]
There is a limitation (at least in Starlark) that every executable (with runfiles) must be in a separate target.

I'd like to create multiple executables with runfiles and use them within a rule, without being forced to create separate rules for each one.

AFAIK there isn't a significant reason to tie runfiles to targets. 

---

I've tried creating DefaultInfo, but the files_to_run is only populated when used in an executable rule.

**Comment by brandjon** [comment]
The concept of runfiles is intimately tied to the notion of providers, which themselves are associated with targets. I think it would be a very invasive change to do this.

**Comment by pauldraper** [comment]
That surprises me....no one has ever wanted to create multiple executables from a single target?

**Comment by brandjon** [comment]
Multiple executables, sure, but I believe you only get one "FilesToRunProvider", describing the thing to execute when you do `bazel run` or invoke the target as a tool. I'm not an expert in this area though.

**Comment by comius** [comment]
I see simplicity as good enough reason to tie runfiles to a target.

**Comment by pauldraper** [comment]
Yes, and I don't realistically see this changing.

Using macros is workable enough.
