### ISSUE TITLE
Concatenation of dict select expressions

### ISSUE THREAD

**Issue by alandonovan** [bazelbuild/bazel#12457]
(Re-reporting on behalf of @sitaktif; see https://github.com/bazelbuild/starlark/issues/114.)

Starlark allows the concatenation of select statements that return lists, such as:
```
my_binary(
  name = "greatbin",
  deps = ["some", "deps"]
    + select({"//:special_cpu": ["//some:target_for_special_cpu"], "//conditions:default": []})
    + select({"//:special_os": ["//some:target_for_special_os"], "//conditions:default": []})
)
```
This is very handy when generating code, which commonly happens when writing bazel rules.

Unfortunately, one cannot concatenate selects that return dicts:
```
my_rule(
  name = "greatbin",
  extra_env = {"FROB_PATH": "somepath"}
    + select({"//:special_cpu": {"SPECIAL_CPUFLAGS": "myspecialcpu"}, "//conditions:default": {}})
    + select({"//:special_os": {"SPECIAL_OSFLAGS": "myspecialos"}, "//conditions:default": {}})
    + select({"//:debug_mode": {"DEBUG": "true"}, "//conditions:default": {}})
    + ...
)
```
as this results in the following error: type 'dict(label, string)' doesn't support select concatenation.

This error is hit both when concatenating a dict and a select(), and when concatenating two select()s.

Related to see https://github.com/bazelbuild/starlark/issues/14.

**Comment by stepancheg** [comment]
There's inconsistency here:

```
{1: 2} + {3: 4}
```

doesn't work, but these three work:

```
{1: 2} + select({"//conditions:default": {3: 4})
select({"//conditions:default": {1: 2}) + {3: 4}
select({"//conditions:default": {1: 2}) + select({"//conditions:default": {3: 4})
```

while intuitively they look equivalent.

**Comment by sitaktif** [comment]
> but these three work
```
{1: 2} + select({"//conditions:default": {3: 4})
select({"//conditions:default": {1: 2}) + {3: 4}
select({"//conditions:default": {1: 2}) + select({"//conditions:default": {3: 4})
```

@stepancheg if you look at #114, you will notice that this is incorrect: unless it changed very recently, the `+` operator is only supported for selects that return lists, not for ones that return dicts.

**Comment by fffonion** [comment]
With starlark's support of `|` operator of dicts (https://github.com/bazelbuild/starlark/issues/14), it would be
awesome to add union operator support to `select | dict` and `select | select`.
Currently it's recognized as binary operator:
```
		env = nfpm_envs | {
Error: unsupported binary operation: select | dict
```

**Comment by sgowroji** [comment]
We are closing this FR with respect to the above [commit](https://github.com/bazelbuild/bazel/issues/12457#issuecomment-1406304710). Please feel free to reach us for any further information. Thanks !
