### ISSUE TITLE
Bazel 3.7.0 can't be compiled on Alpine linux

### ISSUE THREAD

**Issue by kigero** [bazelbuild/bazel#12460]
### Description of the problem / feature request:

Bazel 3.7.0 can't be compiled on Alpine linux; I get the following error:
```
$ wget https://github.com/bazelbuild/bazel/releases/download/3.7.0/bazel-3.7.0-dist.zip && unzip bazel-3.7.0-dist.zip
$ env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh
Building Bazel from scratch......
Building Bazel with Bazel.
<snip>
    Compiling src/main/tools/linux-sandbox.cc; 0s local
src/main/tools/linux-sandbox-pid1.cc: In function 'int WaitForChild()':
src/main/tools/linux-sandbox-pid1.cc:402:23: error: 'TEMP_FAILURE_RETRY' was not declared in this scope
  402 |     const pid_t pid = TEMP_FAILURE_RETRY(wait(&status));
      |                       ^~~~~~~~~~~~~~~~~~
```

It seems that TEMP_FAILURE_RETRY is only available on GNU libc, where Alpine uses musl libc.  The last Bazel version I tried on Alpine was 3.5.0 and that was compiling/running fine.

### What operating system are you running Bazel on?

Alpine linux, 3.13.0_alpha20200917.  Running within docker using the `alpine:edge` tag.

###  Have you found anything relevant by searching the web?

1. The line that errors was added in commit 1517af14afea988083756bd33a476d1100f46cff.
1. I found a definition for TEMP_FAILURE_RETRY [on StackOverflow](https://stackoverflow.com/a/41446972/1322) that does seem to work (meaning, compilation succeeds) when added to the `linux-sandbox-pid1.cc` file, but this is not my area of expertise so I can't tell if it's actually doing what it's supposed to do, or if it just looks like it is.

**Comment by philwo** [comment]
@kigero Sorry for that. I'll see that we revert this part or fix it in a way that works with non-glibcs.

**Comment by foopub** [comment]
Same problem with bazel 4.0 and musl. This fix seems fairly straightforward, other projects seem to be implementing too:

https://git.sailfishos.org/mer-core/profiled/merge_requests/5/diffs

I've successfully built Bazel by adding the snippet from the above push to linux-sandbox-pid1.cc as suggested by kigero. 

I don't know much about Java, but if there are any tests you'd like me to run on my musl system to verify that it works correctly, please let me know - it's a real shame that such a small thing is preventing musl support.

**Comment by philwo** [comment]
@foopub Do you want to send us a PR that fixes this (the diff that you linked seems fine to be)? Please ping me in the PR and I can import it asap.
