### ISSUE TITLE
incompatible_genquery_use_graphless_query: Incompatible flag for graphless genquery

### ISSUE THREAD

**Issue by zhengwei143** [bazelbuild/bazel#12464]
**Flag:** `--incompatible_genquery_use_graphless_query`
**Available since:** Yet to be released
**Will be flipped in:** To be confirmed

## Motivation

Genquery will now be using graphless query by default since it seems stable enough.

## Changes

This changes the default output order of genquery to mainly be in lexicographical order as in graphless query (with the exception of `somepath` which prints in dependency order - see https://github.com/bazelbuild/bazel/commit/93090e160860112385550925644cd3204e79e867)

**Comment by meteorcloudy** [comment]
FYI, The flip of this flag is causing https://github.com/bazelbuild/rules_jvm_external/issues/529
