### ISSUE TITLE
Incremental builds broken when changing rules: Old target files still present in bazel-bin.

### ISSUE THREAD

**Issue by Esben2** [bazelbuild/bazel#12462]
### Description of the problem / feature request:

I triggered a bug (see below of how to reproduce) where Bazel didn't gave me a safe incremental build. The issue is that I could make a mistake such that my build was all ok until made a fresh checkout. 

The core reason is that old target files are left behind in bazel-bin even though a change to a BUIILD or .bzl file have renamed the output file. This confuses the user - which in my case is the old Makefile modified to call Bazel and copy some targets from the bazel-bin into, where Make expects the targets to end up, such we gradually can convert from Make to Bazel.

The main reason why I am looking at Bazel as an replacement for Make in the first place, is that we can rely on incremental builds: No need to clean our workspaces on the buildserver, Bazel is supposed to handle _all_ changes correctly. If a developer make a mistake in a BUILD or .bzl, file it will be caught in the pre-push build and not merged into master. The pre-push build is also just an incremental build.
With this bug, I have an example of an error which I (and therefore others) could make, where a broken build is left undiscovered, and merged into master and potentially first discovered, when someone makes a new checkout.

### Feature requests: what underlying problem are you trying to solve with this feature?

Ensure incremental builds when BUILD and .bzl files are changed.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

First create a BUILD file with
```
genrule(name="foo",
        outs=["foo.txt"],
        cmd="echo foobar > $@")
```

run ``bazel build foo.txt``

Now change (imagine a git commit here) the BUILD file to

```
genrule(name="foo.txt",
        outs=["foo.txt.txt"],
        cmd="echo something > $@")
```
run ``bazel build foo.txt``

Notice that foo.txt is _still_ present in bazel-bin - and the build command still works. There is no way the scripts or the developer running Bazel can catch the above error. The change to the BUILD file only takes effect when you make a clean checkout. 

The key argument for Bazel, namely supporting safe incremental builds, is thus gone.

### What operating system are you running Bazel on?

Linux, Ubuntu 16.04

### What's the output of `bazel info release`?
release 3.7.0

###  Have you found anything relevant by searching the web?

No

**Comment by oquenchil** [comment]
This doesn't sound like a bug to me. If you are interested in migrating from Make to Bazel, see https://github.com/bazelbuild/rules_foreign_cc.

Anyway, I will leave the issue open and leave it to someone else to close this issue with WAI.

**Comment by Esben2** [comment]
@oquenchil : This bug has nothing to do with integrating Make. It is about integrationg Bazel into X, X being any build system or build server wanting to make Bazel build a file, and copy the file out of Bazel. In my case X is just Make. It isn't about Bazel calling Make at all.

The issue is that if in X, I make a "bazel build foo.txt" call and use, what I see as the official way to get the foo.txt out of Bazel's build folder, foo.txt is not up-to-date. I need to do a clean build. That is directly contradicting Bazel's overall goal of delivering correct incremental builds.

Things that can be done:
1) Remove foo.txt from Bazel's out put folder, when Bazel discovers that there is no rule generating it.
2) Make a better "official" way to get files out of Bazel output directories. Simlilar to "bazel run <command>" there could be a "bazel  copyfile <file(s)> <distination>", which checks that those files are really generated and up-to-date.
3) Avoid mixing build target labels with real output files. Then "bazel build foo.txt" would fail after the change to the Build file above.

**Comment by janakdr** [comment]
I agree this can be confusing in your specific example, but it is WAI. Bazel does not guarantee that your output tree after a incremental build is indistinguishable from that of a clean build. Instead, it guarantees that the files that you requested on this build are the same as if you had built them from a clean build.

Changing behavior would definitely cause lots of problems: if you did `bazel build a && bazel build b && bazel build a` the third build would have to redo work because the intermediate `bazel build b` would have deleted a's outputs.

If you want to see what top-level files Bazel has actually produced, you can consume Bazel's BEP stream to see what files to copy.

**Comment by Esben2** [comment]
@janakdr What do you mean by WAI?

> Bazel does not guarantee that your output tree after a incremental build is indistinguishable from that of a clean build. Instead

Since there is no API to get to the files in the output tree, the output tree is the state exposed to the user, and therefore it must be invariant to incremental builds. As suggested, a solution could be to supply an API, then I shouldn't care about the output tree.
But if Bazel want users to actually use the output tree (speed could be an argument), the output tree must be invariant wrt. incremental builds.

> Changing behavior would definitely cause lots of problems: if you did bazel build a && bazel build b && bazel build a the third build would have to redo work because the intermediate bazel build b would have deleted a's outputs.

That is not at all what I said: I ask for a deletion of files from the output tree, when BUILD (and .bzl) files are changed. I.e. if "bazel build a" produces a file "a.txt" and the rule is changed to no longer produce "a.txt" it should be removed when the BUILD file is reloaded, such I as a user immediately can detect it, and fail the build if such change have been done wrongly. Failure is also part of a "state", which should be the same if we do incremental or clean builds. At least there could be a "bazel prune" command to clean out all files left over from old rules.
And yes, internally Bazel's state is fine, but Bazel is never alone: There will always be a "consumer", and it can't help that Bazel internally has a 100% good incremental build system, if the system "Bazel + consumer" requires a clean to be correct.

It comes to me, that there here might be a misinterpretation of the term "incremental builds". When I say "incremental builds". I mean that I can change the source code - and BUILD files - type "bazel build foo.txt" repeatedly without ever having to clean my workspace, and the output is always the same as if I had cleaned the workspace. I have never before seen the interpretation that typing "bazel build a" followed by a  "bazel build b" deserves the term _incremental build_.

> If you want to see what top-level files Bazel has actually produced, you can consume Bazel's BEP stream to see what files to copy.

I can see that I could do that, but it will require lots of uncertain code for the "consumer" to fix, what I still consider a bug in Bazel.

**Comment by janakdr** [comment]
Determining whether some existing rule produces a given file for every file in the output tree would require Bazel to do significantly more work, even if it were restricted to when BUILD/bzl files changed. Perhaps the fundamental disconnect is that we definitely consider the situation I gave to be an "incremental build" that we optimize for. I'm sorry Bazel's constructs don't agree with yours in this setting.
