### ISSUE TITLE
STUPID design of bazel fetch!

### ISSUE THREAD

**Issue by mocowo** [bazelbuild/bazel#12469]
What's the file format in ~/.cache/bazel/_bazel_$USER/cache/repos/v1/ after using bazel build or fetch??? And how to use them?  Can they be used by -distdir?

Why these files are not the right format  of --distdir required when build offline? How should I get those tars defined in http_archive when using build--distdir offline? Download them one by one manually? Oh, shit, It's really a stupid design!
Why not provide the right tars when using bazel fetch? 

BTW, Bazel document is really  in a mess as like bazel itself.  And about bazel design,  just handling c++ compile is good enough, pls do not try to cover all the things. java and go themselves have great compile toolchain, less need bazel.  It's really like C++ design, a language from Jurassic Period. stupid enough. Trying to handle the world everything, but no thing can be done in fact. More and more complex grammar and feature that stop anyone wants to learn and use. Bazel is on the way.

**Comment by dzintars** [comment]
Great first contribution to the OSS. :)

**Comment by sventiffe** [comment]
@mocowo Thank you for reaching out. Issues on GitHub are supposed to be used for bug reports and feature requests. For both we require some more detail than what you've provided so far. For support requests and discussions, please consider using one of the channels described at https://bazel.build/support.html

Please also note that we consider your language offensive. You seem to be unhappy with design choices and scope of Bazel and you're of course free to express yourself. If you are interested in a conversation, please express yourself in a way that allows everyone to participate to the discussion without getting pushed into a defensive position. Thanks.
