### ISSUE TITLE
Ability to specify "default" and "available" platforms

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/bazel#12473]
Suppose you have remote execution environments where some platforms are cheap to provide (say Linux), and others expensive (say Windows).

It would be nice to be able to say "Run all tests on the cheap platform if possible. Run any tests which can _only_ run on the expensive platform on the expensive platform. But if a test can run on either/both, run it only on the cheap one".

As an example, suppose you have:

test1(only_on_linux)
test2(only_on_windows)
test3(all_platforms)

I'd like to be able to construct a command line where test1 and test3 run only on Linux, and test2 runs only on Windows.

**Comment by katre** [comment]
Currently, [toolchain resolution](https://docs.bazel.build/versions/3.7.0/toolchains.html#toolchain-resolution) uses execution platforms in priority order: the priority is:
1. Platforms specified via `--extra_execution_platforms`, in order.
2. Platforms specified via `register_execution_platforms` in the WORKSPACE, in order.
    1. That's "order as encountered during WORKSPACE evaluation", which can be complicated to figure out if there are lots of WORKSPACE macros.
3. Finally, the host platform is the lowest priority execution platform.

Given that, you should be able to add the platforms in the correct order to prioritize the cheaper linux execution platform, and have the more expensive windows platform only used for targets that require it.

Does that address your request?

**Comment by illicitonion** [comment]
Oh wow, this has come on a long way since I last tried it! Yes, this is perfect - thanks!

**Comment by illicitonion** [comment]
Actually, @katre, I'm not seeing fall-back to the host platform for execution...

I'm running `bazel` on a Mac, with a connection to a Linux-only remote execution cluster. What I see is bazel trying to run both targets on the remote execution cluster, and fatally erroring when it tries to run the macOS and the remote execution system replies saying `FAILED_PRECONDITION: No workers exist for instance "remote-execution" platform {}`.

I'm using the following invocation:

```
bazel test \
  --platforms=//remote/linux:platform \
  --extra_execution_platforms=//remote/linux:platform \
  --crosstool_top=//cc_toolchain_suite/for/k8_and_darwin_and_darwin_x86_64 \
  --incompatible_enable_cc_toolchain_resolution \
  --extra_toolchains=//cc_toolchain:k8,//cc_toolchain:darwin_x86_64 \
  --remote_executor=REDACTED --remote_instance_name=REDACTED \
  //compiles_c_multiple_platforms:test-linux //compiles_c_multiple_platforms:test-macos
```

`//remote/linux:platform` specifies the following constraint values:
```
    constraint_values = [ 
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],  
```

Where the `compiles_c_multiple_platforms` folder looks like:

`BUILD`:
```python
cc_binary(
    name = "mini-uname",
    srcs = ["mini-uname.c"],
)

sh_test(
    name = "test-linux",
    size = "small",
    srcs = ["test-individual-platform.sh"],
    args = [ 
        "$(location :mini-uname)",
        "Linux",
    ],  
    data = [":mini-uname"],
    exec_compatible_with = ["@platforms//os:linux"],
)

sh_test(
    name = "test-macos",
    size = "small",
    srcs = [":test-individual-platform.sh"],
    args = [ 
        "$(location :mini-uname)",
        "Darwin",
    ],  
    data = [":mini-uname"],
    exec_compatible_with = ["@platforms//os:macos"],
)
```

`mini-uname.c`:
```c
#include <stdio.h>
#include <sys/utsname.h>

int main(void) {
  struct utsname buf;

  if (uname(&buf) != 0) {
    return 1;
  }

  printf("%s\n", buf.sysname);

  return 0;
}
```

`test-individual-platform.sh`:
```shell
#!/bin/bash -eu

if [[ "$#" -ne 2 ]]; then
  echo >&2 "Usage: $0 command-to-run expected-uname"
  exit 1
fi
uname_command="$1"
expected_uname="$2"

actual_uname="$("${uname_command}")"

[[ "${expected_uname}" == "${actual_uname}" ]] || { echo "Expected ${expected_uname} got ${actual_uname}" ; exit 1; }
```

So it looks like Bazel assumes my remote execution environment can provide a macos environment, even though I haven't told it that it can?

**Comment by illicitonion** [comment]
Oh, actually, that case is https://github.com/bazelbuild/bazel/issues/11432 (which I've already filed an issue which got duped to that!)

Great seeing the progress on toolchains/platforms so far, and looking forward to that piece landing too!
