### ISSUE TITLE
Starlark: per-thread descriptor cache for builtin types

### ISSUE THREAD

**Issue by stepancheg** [bazelbuild/bazel#12476]
Follow-up to this PR: https://github.com/bazelbuild/bazel/pull/11759 (Cache descriptor resolution in getattr)

That PR did not work because caching would be inefficient when semantics change.

The alternative idea is to implement per-thread cache of descriptors for builtin-types. I assume that the most descriptor lookups in Starlark are list, dict, string operations (like `list.append` or `list(...)`), which could be significantly optimized at cost of minor slowdown of lookup of types unknown to the Starlark interpreter or for non-repeated lookups of builtin types.

The outline of the idea:

```java
// Current CallUtils.CacheValue
class PerTypeDescriptors {
    @Nullable MethodDescriptor selfCall;
    // All StarlarkMethod-annotated Java methods, sans selfCall, sorted by Java method name.
    ImmutableMap<String, MethodDescriptor> methods;
    // Subset of CacheValue.methods for which structField=True, sorted by Java method name.
    ImmutableMap<String, MethodDescriptor> fields;
}

class PerThreadCaches {
  @Nullable PerTypeDescriptors listDescriptors;
  @Nullable PerTypeDescriptors dictDescriptors;
  @Nullable PerTypeDescriptors strDescriptors;
  ... probably also bool, int, tuple
}

class StarlarkThread {
  caches = new PerThreadCaches();

  ...
}

class Starlark {
  public static Object getattr(
      Mutability mu,
      StarlarkSemantics semantics,
      PerThreadCaches caches, // <-- new argument
      Object x,
      String name,
      @Nullable Object defaultValue) {
    PerTypeDescriptors descriptors;
    if (x.getClass() == StarlarkList.class) {
      descriptors = caches.listDescriptors;
      if (descriptors == null) {
        descriptors = caches.listDescriptors = CacheUtils.getDescriptors(semantics, StarlarkList.class); 
      }
    } else if (x.getClass() == Dict.class) {
      descriptors = caches.dictDescriptors;
      if (descriptors == null) {
        descriptors = caches.dictDescriptors = CacheUtils.getDescriptors(semantics, Dict.class); 
      }
    } else if ... {
    } else {
      // default case, slower lookup
      descriptors = CacheUtils.getDescriptors(semantics, x.class());
    }
    MethodDescriptor = descriptors.getMethodDescriptor(name);
    ...
  }
}
```

This optimization would be similar to having a special-case for `type` operation: https://github.com/bazelbuild/bazel/pull/11783.

Before rushing to implementing it, what do you think of that idea? @alandonovan, @laurentlb?

**Comment by brandjon** [comment]
I was in the middle of reviewing this change with Alan but had to put it down for time constraints. Assigning to myself to remember to pick it back up again.

**Comment by brandjon** [comment]
We're not in a position to work on micro-optimizations to the interpreter at the moment. Leaving this as P4 since it's nonetheless in-scope.
