### ISSUE TITLE
FP: build cache for external dependencies

### ISSUE THREAD

**Issue by vnvo2409** [bazelbuild/bazel#12488]
### Description of the problem / feature request:

`Bazel` invalidates build caches of external dependencies when updating the dependencies using `http_archive`

### Feature requests: what underlying problem are you trying to solve with this feature?

The whole build caches (`cc_*`) will be invalidates when we update the `sha256` of an external repo. I would like to ask if we could have an attribute `cached_sha256` or `cached_version` in `http_archive` rule. This way, we will download 2 versions of source code, one for the new version and one for the old version. When compiling, we could do something like:
- if a file in the new version differs from that file in the old version, recompile that file.
- if a file in the new version is the same as in the old version:
  - if that file is already in cache, skip.
  - if that file isn't in cache, compile that file.

### What's the output of `bazel info release`?

3.1.0

### Any other information, logs, or outputs that you want to share?

With this FP, we could save a lot of resources. TensorFlow for an example, TF updates `LLVM` daily and it takes a lot of time to recompile `LLVM` and the modules which depend on `LLVM` ( which are almost everything in TF )

If you need help, I would be happy to contribute toward this FP.

**Comment by philwo** [comment]
Could you use `--disk_cache=/some/path` for that? It should fix the problem easily without requiring additional complexity in Bazel.

**Comment by vnvo2409** [comment]
After futher investigation, I find that there is nothing to do with Bazel. Thank you !
