### ISSUE TITLE
Compilation error on 32 bit machine.

### ISSUE THREAD

**Issue by manjurajv** [bazelbuild/bazel#1249]
```
bazel (master)$ uname -m
i686

diff --git a/tools/cpp/cc_configure.bzl b/tools/cpp/cc_configure.bzl
index 7f33475..89fc1f5 100644
--- a/tools/cpp/cc_configure.bzl
+++ b/tools/cpp/cc_configure.bzl
@@ -105,7 +105,7 @@ def _get_cpu_value(repository_ctx):
     return "x64_windows"
   # Use uname to figure out whether we are on x86_32 or x86_64
   result = repository_ctx.execute(["uname", "-m"])
-  return "piii" if result.stdout.strip() == "i386" else "k8"
+  return "piii" if result.stdout.strip() == "i686" else "k8"
 
 
 _INC_DIR_MARKER_BEGIN = "#include <...>"


src/main/native/unix_jni.cc:867:49: error: cannot convert 'jlong* {aka long long int*}' to 'long int*' for argument '2' to 'int portable_sysctlbyname(const char*, long int*, size_t*)'
   if (portable_sysctlbyname(name_chars, &r, &len) == -1) {

```

**Comment by manjurajv** [comment]
Other information.

bazel (master)$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
OpenJDK Server VM (build 25.91-b14, mixed mode)
bazel (master)$ 
bazel (master)$ gcc --version
gcc (Ubuntu 5.3.1-14ubuntu2) 5.3.1 20160413
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

bazel (master)$ uname -r
4.4.0-21-generic
bazel (master)$ uname -a
Linux gerrit-server 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:34:49 UTC 2016 i686 i686 i686 GNU/Linux

**Comment by aehlig** [comment]
Yue, can you have a look please since you changed that part of the code recently? Probably, it's only a question of correct casts to ``void *`` to make portable_sysctlbyname match the sysctlbyname(3) interface which expects a ``void *`` as second argument.

Marking as P4 though, as we do not have proper test coverage for 32-bit machines.
