### ISSUE TITLE
No toolchain found for cpu 'piii'. Valid cpus are [k8, armeabi-v7a]

### ISSUE THREAD

**Issue by srib** [bazelbuild/bazel#1251]
I am trying to compile bazel from source from the latest head. I had an old version of bazel on my machine which worked fine till I updated the head and now I get this error:

```
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
.WARNING: /tmp/bazel.cxHNIgBu/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel.cxHNIgBu/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.
ERROR: No toolchain found for cpu 'piii'. Valid cpus are: [
  k8,
  armeabi-v7a,
].
INFO: Elapsed time: 6.194s

Building output/bazel

```

I see https://github.com/bazelbuild/bazel/issues/1122 and I don't think I modified anything in here. Any help on what is wrong with the way I am trying to compile?

FWIW, here is what I get it from ```uname -m```: ```i686```.

I have a 32 bit machine running XUbuntu.

**Comment by ahumesky** [comment]
Looks like this is the problem:
https://github.com/bazelbuild/bazel/blob/master/tools/cpp/cc_configure.bzl#L107-108

srib, you can work around this in the short term by changing that check to "i686" while we fix this.

**Comment by srib** [comment]
Thanks @ahumesky. Let me try to change it to "i686".

I am trying to understand as to what caused this to break. I would appreciate any help in trying to understand why this changed and caused 32 bit builds to break.

**Comment by damienmg** [comment]
srib: we use auto configuration for detecting C++ toolchain now and it had a bug that did not recognize i686. Fixing it right now.

**Comment by JoyChopra1298** [comment]
I am facing the same error while building bazel 4.5 Could you write down the lines that need to be changed.
