### ISSUE TITLE
Package boundary crossing warning missing information

### ISSUE THREAD

**Issue by ilanbiala** [bazelbuild/bazel#12527]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:
I'm getting a number of warnings of the form:
```
WARNING: null crosses package boundary into package rooted at ...
```

### What operating system are you running Bazel on?

Linux, Ubuntu 16.04.7 LTS.

### What's the output of `bazel info release`?

release 3.4.1

###  Have you found anything relevant by searching the web?

I haven't found anything that is closely related to this issue of "null" being mentioned in the warning, which seems to substitute for what is normally more useful information in other people's cases.

**Comment by sventiffe** [comment]
Can you share information how to reproduce the issue, please?

**Comment by ilanbiala** [comment]
I'm not sure of the exact way to reproduce, but I believe it has to do with having the following config setting in `.bazelrc`:
```
# https://github.com/bazelbuild/bazel/commit/c64421bc35214f0414e4f4226cc953e8c55fa0d2
# https://github.com/bazelbuild/bazel/issues/8450
startup --host_jvm_args=-DBAZEL_TRACK_SOURCE_DIRECTORIES=1
```
and including a `pkg_tar` in a Docker image built using https://github.com/bazelbuild/rules_docker.

**Comment by aiuto** [comment]
Do you have anything self contained?

**Comment by benjaminp** [comment]
You have see from the code how trigger this:

**Comment by benjaminp** [comment]
You can see from the code how to trigger this:
```
$ mkdir -p dir/subdir
$ touch dir/subdir/BUILD
$ cat > BUILD
filegroup(
   name = 'data',
   srcs = ['dir'],
)
$ bazel --host_jvm_args=-DBAZEL_TRACK_SOURCE_DIRECTORIES=1 build //:data
INFO: Analyzed target //:data (1 packages loaded, 2 targets configured).
INFO: Found 1 target...
WARNING: null crosses package boundary into package rooted at dir/subdir
Target //:data up-to-date (nothing to build)
INFO: Elapsed time: 0.857s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```
`RecursiveFilesystemTraversalFunction` is written for fileset semantics not experimental, apparently abandoned feature `TRACK_SOURCE_DIRECTORIES`.

**Comment by ilanbiala** [comment]
Not the particular case I had hit, but that above works. Is it possible to make it so that `null` is replaced with something more useful in this case?
