### ISSUE TITLE
Provide the ability to interrupt certain bazel commands

### ISSUE THREAD

**Issue by daveyc123** [bazelbuild/bazel#12524]
### Description of the problem / feature request:

The bazel server has a single lock that ensures that multiple commands do not run concurrently. When a command is run it obtains the lock and holds on to the lock until it completes (see BlazeCommandDispatcher#exec). If a second command is run and the first command is running, the second command will wait until the first command completes and the lock is released before it runs - "Another command (".... ") is running. Waiting for it to complete on the server..." There are a few GitHub issues raised related to this issue (such as https://github.com/bazelbuild/bazel/issues/532 and https://github.com/bazelbuild/bazel/issues/1541). 

Unfortunately, this model poses problems for tools who wish to present information about a user's project, but not interfere with their traditional workflows.

Consider the case where a visual tool provides information regarding the available targets for a given bazel project. When the tool opens, it executes bazel query to find the list of targets so that it can present them to the user. For large projects and those with many large externals, this first query can take a long time. Unfortunately, during this time, if the user were to do a bazel build, they'll receive a message indicating a bazel command is already running. It's not obvious to them what is happening under the hood.

Ideally, I'd like the ability to indicate that a bazel invocation is "interruptible". If another command is subquently run, the interruptible command would stop and the subsequent command would run. This would allow tools who leverage bazel "under the hood" to mark their commands as "interruptible" so that they don't interfere with other workflows. They could then re queue their bazel invocations.

### What's the output of `bazel info release`?
release 3.5.0

**Comment by daveyc123** [comment]
This is my first foray into the bazel codebase. I'd like to contribute a PR for this issue, and have started to put some code together that can accomplish this by updating CommandManager#RunningCommand to have an "interruptible" flag. GrpcServerImpl#executeCommand would then ask the command manager to interrupt all interruptible commands when a new command is run. That part is fairly straight forward.

My question is how to plumb in the --interruptible flag. Currently, GrpcServerImpl#executeCommand doesn't parse out the command options (it only has the startup options). Looking at the other start up options, I don't think --interruptible makes sense there.

The BlazeCommandDispatcher is where the command options are parsed. At the moment though it doesn't have access to RunningCommand. It could in some fashion but that seems leaky.

@ulfjack - your name seems to come up in a lot of the blame lines in the relevant code. Any thoughts on the above?

**Comment by michajlo** [comment]
Off the top of my head, I think this could actually be a bit in the grpc request to the bazel server with the option handling happening purely on the client side, sort of like the `client_debug` and `local_startup_timeout_secs` options.

**Comment by daveyc123** [comment]
@michajlo thanks for the quick reply. I'll have a look at implementing it similar to those options.

**Comment by daveyc123** [comment]
@michajlo that was fairly straightforward. Thanks for the tips. I've posted a PR. Please let me know if this looks like an acceptable implementation and I can clean up any comments and add tests. Thanks!

**Comment by michajlo** [comment]
Approach looks good, once it's ready for review it'll likely just be terminology and style comments from me. Before we get too far - what do you think of changing the name of the feature to "preemptible" or something similar. The interruptible terminology is already largely claimed, and it's easy to mix the new bit up with "this command is allowed to be interrupted (aka cancelled)".

**Comment by daveyc123** [comment]
Yes, I agree that preemptible is more clear. I'll fix that up and the other comments you made. Thanks for the feedback.
