### ISSUE TITLE
Documentation issue: Build Tutorial - Java

### ISSUE THREAD

**Issue by yaojingguo** [bazelbuild/bazel#12536]
Documentation URL: https://docs.bazel.build/versions/3.7.0/tutorial/java.html

There is no need to set JAVA_HOME since Bazel 3.7.0 uses its own JDK. I have verified it on macOS.

**Comment by comius** [comment]
Not entirely true, if JAVA_HOME not set, Bazel uses `which` and it probably discovered JDK that's in path.

**Comment by yaojingguo** [comment]
I installed Bazel 3.7.0. And this is the content of `Bazel`:

```
#!/bin/bash
JAVA_HOME="/usr/local/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home" exec "/usr/local/Cellar/bazel/3.7.0_1/libexec/bin/bazel"  "$@"
```

It does not use `which` to find java for running.
