### ISSUE TITLE
Bazel unexpectly disables compiler warnings

### ISSUE THREAD

**Issue by rcls** [bazelbuild/bazel#12533]
### Description of the problem / feature request:

The attached C code should generate two compiler warnings (and does if compiled manually using gcc -Wall -Imylib).
Compiled with Bazel, one of the compiler warnings disappears.

### Feature requests: what underlying problem are you trying to solve with this feature?

Get compiler warnings correctly generated when building my code.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Bazel file:
```
cc_library(
    name = "mylib",
    hdrs = ["mylib/mylib.h"],
    includes = ["mylib"],
)
cc_library(
    name = "myprog",
    srcs = ["myprog.c"],
    deps = [":mylib"],
)
```
mylib/mylib.h:
```
#ifndef MYLIB_H_
#define MYLIB_H_
#include <stdio.h>
#define warnme(X, ...) printf("At %s:%i: " X "\n", __FILE__, __LINE__, __VA_ARGS__)
#endif
```
myprog.c:
```
#include "mylib.h"
#define warnmeagain(X, ...) printf("At %s:%i: " X "\n", __FILE__, __LINE__, __VA_ARGS__)
int main()
{
    // Both of these have identical expansions.  warnmeagain() correctly gets a
    // compiler warning from gcc.  But warnme() does not, because Bazel
    // is suppressing compiler warnings.
    warnme("%s", 1);
    warnmeagain("%s", 1);
    return 0;
}
```

### What operating system are you running Bazel on?

Linux Fedora 33 x86_64

### What's the output of `bazel info release`?

bazel info release
release 3.7.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Not a git repo.

###  Have you found anything relevant by searching the web?

This is due to Bazel using the gcc option -isystem inappropriately for non-system includes.

There used to be a Bazel option to use the correct -I, but this option was removed in 2016 (f223689843a37268d0dd338aa10c94d0626d6e23, that commit has no explanation of the reason for the removal).

**Comment by limdor** [comment]
Dear @bazelbuild/triage please consider keeping this issue and revisiting the priority. I've been working in a project with around 1k developers for several years now and still several times a week I have to explain why includes shall not be used in our project. In safety critical systems were you usually you care about compiler warnings, this is a problem.
People increase the warning level but they end up using includes. It is far from intuitive that a library target you declared is using -isystem.

**Comment by oquenchil** [comment]
@lberki Do you remember the reason for that change?

**Comment by oquenchil** [comment]
In any case I'd prefer if this were solved with different attributes in the cc_library rule instead of a configuration option.

**Comment by limdor** [comment]
> In any case I'd prefer if this were solved with different attributes in the cc_library rule instead of a configuration option.

I would agree, there should be an attribute for system includes and one for normal includes. Is there any way to contribute on that direction? What would be the next steps?

**Comment by limdor** [comment]
@bazelbuild/triage please reopen
