### ISSUE TITLE
Bug: The file name is wrong in the tar file produced by pkg_tar()

### ISSUE THREAD

**Issue by leo-yinle** [bazelbuild/bazel#1253]
Hi,

I found a bug of pkg_tar(), which can be reproduced.

My BUILD file has the following snippet.

java_library(
    name = "util",
    srcs = glob(["java/com/google/callbuilder/util/*.java"]),
)

pkg_tar(
  name = "test",
  files = [":util"],
  package_dir = "Runtime/bin/lib",
)

'bazel build //:test' will produce a tar file of the contents as follows.

$ tar tf test.tar
./
./Runtime/
./Runtime/bin/
./Runtime/bin/lib/
./Runtime/bin/lib/r

That is, only a file named r is packed. 

To reproduce the issue, 
1) pkg_tar()'s files attribute should be a label of some java_library().
2) the pkg_tar() and java_library() rules should be in the BUILD in the root directory (where WORKSPACE file is).

Regards,
-Leo

**Comment by kchodorow** [comment]
Thanks for the detailed repro, we aren't handling the top-level package correctly in pkg_tar. I've got a fix in review.
