### ISSUE TITLE
Documentation issue: Installing Bazel on Ubuntu

### ISSUE THREAD

**Issue by yaojingguo** [bazelbuild/bazel#12537]
Documentation URL: https://docs.bazel.build/versions/3.7.0/install-ubuntu.html

There is no need to install OpenJDK since Bazel 3.7.0 uses its own JDK.

**Comment by comius** [comment]
Not entirely true, if JAVA_HOME not set, Bazel uses `which` and it probably discovered JDK that's in path.

**Comment by yaojingguo** [comment]
On Ubuntu 18.04.5 LTS with Bazel 3.7.0. `JAVA_HOME` is not set and `java` is not in `PATH`.

```
$ echo $JAVA_HOME
$ which java
```

But Bazel still works.

**Comment by jin** [comment]
It says it's optional, only needed if you want to build java targets.

"However, if you want to build Java code using Bazel, you have to install a JDK."

**Comment by yaojingguo** [comment]
@jin Thanks for pointing this out
