### ISSUE TITLE
`--run_under` doesn't work with script in external repository

### ISSUE THREAD

**Issue by lizan** [bazelbuild/bazel#12545]
### Description of the problem / feature request:

We use --run_under with collect_coverage to get fuzz-coverage in Envoy:
https://github.com/envoyproxy/envoy/blob/master/.bazelrc#L149

This works perfectly with Bazel 3.6.0 but broken in Bazel 3.7.0

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Checkout https://github.com/envoyproxy/envoy/
Run: ci/run_envoy_docker.sh "ci/do_ci.sh bazel.fuzz_coverage //test/integration:h1_capture_fuzz_test"

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

release 3.7.0

### Any other information, logs, or outputs that you want to share?

With subcommands, bazel 3.6.0 generates:
```
external/bazel_tools/tools/test/test-setup.sh external/bazel_tools/tools/test/collect_coverage.sh external/envoy/bazel/coverage/fuzz_coverage_wrapper.sh test/integration/h1_capture_fuzz_test ...
```

While bazel 3.7.0 generates:
```
external/bazel_tools/tools/test/test-setup.sh external/bazel_tools/tools/test/collect_coverage.sh envoy/bazel/coverage/fuzz_coverage_wrapper.sh test/integration/h1_capture_fuzz_test ...
```

Lacking of `external/` in the 2nd parameter is why this is broken.

Our failing CI logs can be found at https://dev.azure.com/cncf/envoy/_build/results?buildId=58183&view=logs&j=7b6d60aa-b5de-5f9b-678c-063d31881e76&t=e31ced1d-8def-5d31-02c0-2d875dd6ed2d

**Comment by meisterT** [comment]
Do you have simple Bazel repro that doesn't involve running multiple shell scripts?

**Comment by lizan** [comment]
@meisterT https://github.com/lizan/bazel-12545 is the minimal reproducer, it appears run_under is broken and not related to coverage at all.

**Comment by meisterT** [comment]
Thanks, that was super helpful!

https://github.com/bazelbuild/bazel/commit/301b96b223b0c0e0294435efcc30af00d4e77dc7 is the culprit CL.

cc @lberki @gyias

**Comment by gyias** [comment]
a689d673abadf80f1efaf8ddaeee92d56fc2847b fixes this.

**Comment by wrowe** [comment]
Note this bugfix picked to both 4.0.0rc and 3.7.2rc
