### ISSUE TITLE
Regenerate test.xml with generate-xml.sh when testing remotely with --remote_download_minimal

### ISSUE THREAD

**Issue by coeuvre** [bazelbuild/bazel#12554]
### Description of the problem:

Normally, when running a test, Bazel expects the test to produce a `test.xml`. If it is not produced, Bazel will run a separate action using `generate-xml.sh` to generate that file.

When testing remotely with `--remote_download_minimal`, Bazel doesn't download the XML file, and then observes that it doesn't exist and so tries to regenerate it, regardless of whether the action actually produced it or not.

Bazel shouldn't regenerate the `test.xml` if the action actually produced it.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Java tests with junit produce `test.xml` automatically. You can verify by running a junit test locally (and Bazel won't run the `generate-xml.sh` action) and find the file under `bazel-testlogs` folder.

However, when running the test remotely with  `--remote_download_minimal`, you will notice that Bazel will run an additional `generate-xml.sh` action.

### What's the output of `bazel info release`?

release 3.7.0

###  Have you found anything relevant by searching the web?

#6862
#11558

**Comment by coeuvre** [comment]
The root cause is that, "minimal" mode only [inject metadata](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/remote/RemoteCache.java;l=604) of output which is an instance of `Artifact` into the filesystem. However, [`test.xml`](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/test/TestRunnerAction.java;l=282) is an instance of [`BasicActionInput`](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/actions/ActionInputHelper.java;l=61) which is not a subclass of `Artifact`. Hence, Bazel won't know the existence of that file.

**Comment by sventiffe** [comment]
@coeuvre this issue is marked as P1 bug but stalled since end of last year. Is this still active work or can it be bumped down to P2?

**Comment by coeuvre** [comment]
The linked patch works for Bazel but need some work on internal code to pass the tests. Bumping down to P2.

**Comment by daveyc123** [comment]
@coeuvre What's the plan for this patch? This is impacting us significantly. Is there a way we can help with the patch? When you refer to "internal code", is this bazel tests or blaze tests?

**Comment by coeuvre** [comment]
"internal code" was referred to blaze tests. I updated the patch to pass internal tests and it is now under review. Should be merge in a few days.
