### ISSUE TITLE
Add a warning that STARLARK_SEMANTICS changed

### ISSUE THREAD

**Issue by sjoerdvisscher** [bazelbuild/bazel#12569]
Bazel was pretty slow for us, seemingly randomly refetching external dependencies. After we finally found a way to reproduce this, we found that in the marker files of the refetched external dependencies the value of `STARLARK_SEMANTICS ` changed. It turns out that we had `build --experimental_allow_tags_propagation` in our `.bazelrc` file, which should have been `common --experimental_allow_tags_propagation`. So every time we did a `bazel query` or `bazel info`, and then `bazel build`, external dependencies were refetched.

It would be nice if bazel would issue a warning saying that the Starlark semantics changed, and ideally mentioning the cause (change of `--experimental_allow_tags_propagation` in our case), just like it does for discarding the analysis cache.

**Comment by brandjon** [comment]
Wow, that's actually a pretty compelling reason for the warning. I can imagine a lot of users getting tripped up over the same thing.

**Comment by laurentlb** [comment]
See also: https://github.com/bazelbuild/bazel/issues/10961

This is a very common source of problems.

**Comment by appuser999** [comment]
same issue here.
