### ISSUE TITLE
Improve transition scalability by considering visibility of user-defined build setting

### ISSUE THREAD

**Issue by ulrfa** [bazelbuild/bazel#12568]
[I'm creating a separate ticket too keep #6526 focused] 

An optimal solution for efficient action caching and small graph size, in combination with transitions, [seems far away](https://github.com/bazelbuild/bazel/issues/6526#issuecomment-732389698). At least as a generic solution for all use cases.

But could transition scalability be improved for some use cases, by filtering out user-defined build settings having a visibility that assure they can not affect parts of the build graph?

Preferably by automatic trimming the build graph, by removing build options derived from user-defined build settings that are not visible to the current package. And also not visible in transitive dependency!

Or alternatively avoid hashing such non-visible build options when calculating output directories.

Would it help that rule visibility is [nonconfigurable](https://docs.bazel.build/versions/master/be/common-definitions.html#configurable-attributes) and does not require resolving select()? Or is the problem still of the same complexity, as detecting which options actually have an effect, due to the build options used via transitive dependencies?

@gregestren, do you think a feature like this would make sense? (if not, feel free to close this ticket)

**Comment by ulrfa** [comment]
Thanks @gregestren!

Could the output directory calculation start from the leafs in the build graph? (that don’t have any dependencies)

And let the output directory hash of each action, be calculated based on the output directory hashes of its direct dependencies?

Like `hash ( all_options_except_from_non_visible_user_defined_build_settings + output_directory_hashes_of_all_direct_dependencies )`

I’m afraid tagging the targets would be too error prone and cumbersome in our code base, even if automated with a tool.

**Comment by gregestren** [comment]
> Like `hash ( all_options_except_from_non_visible_user_defined_build_settings + output_directory_hashes_of_all_direct_dependencies )`

That's an interesting idea. Maybe?

It reads to me like basically doing "manual tagging"  in a more automated way. In other words, 

    build_setting(
        name = "my_setting",
        visibility = ["//foo:__pkg__"]
    )

is similar to manually tagging every target not in `//foo` with `does_not_use = ["my_setting"]`. This wouldn't work for graph size (i.e. stripping `my_setting` from the configuration) but could possibly work for output path stripping.

Caveats:
  * We'd have to make sure any output path a rule computes is in fact *that rule's* outputs. I think it's possible for rules to request output paths without actually creating an action out of them. 
  * If a target applies a transition that reads or writes `"my_setting"`, does that mean the target depends on "my_setting"? I don't think visibility would restrict this.

You said your use case involves a bunch of `cc_library` targets that *would* read the flag. Given that, how much of the subgraph can you imagine practically visibility-restricting?

**Comment by ulrfa** [comment]
Now I'm back from vacation.

> Caveats:
> 
> * We'd have to make sure any output path a rule computes is in fact _that rule's_ outputs. I think it's possible for rules to request output paths without actually creating an action out of them.

I don’t have enough insight to comment on that.

> * If a target applies a transition that reads or writes `"my_setting"`, does that mean the target depends on `"my_setting"`? I don't think visibility would restrict this.

It could be problematic for graph size trimming, but I believe it would be OK if we aim for only output path stripping. Transitions writing private options might be compared with setting private flags on the command line, which should be OK.

But in this context, I'm worried about #12669. What do you think about that?

> You said your use case involves a bunch of `cc_library` targets that _would_ read the flag. Given that, how much of the subgraph can you imagine practically visibility-restricting?

The majority of our settings are visible only in the package it is defined in, and used by test cases testing code in its own package. Those should not have to affect all the cc_libraries deeper in the dependency graph.

We also have public settings, that might be set by transitions from the top and affect cc_libraries deep down in the dependency tree, but I expect those to be fewer and hopefully resulting in a limited set of combinations.

**Comment by gregestren** [comment]
> But in this context, I'm worried about #12669. What do you think about that?
>

Looks like we're making some progress on that. :) Can you remind me specifically where `config_setting` / `select()` fits into the larger request?
 
> > You said your use case involves a bunch of `cc_library` targets that _would_ read the flag. Given that, how much of the subgraph can you imagine practically visibility-restricting?
> 
> The majority of our settings are visible only in the package it is defined in, and used by test cases testing code in its own package. Those should not have to affect all the cc_libraries deeper in the dependency graph.
> 

Okay, this is really helpful input. This is precisely where I think there's the best practical possibility for making improvements. I think this is orthogonal to the visibility-restricted approach.

The limitation of the visibility-restricted approach is that you have to know the entire graph's transitive dependencies before knowing the full visibility scope. This requires instantiating the entire graph with original configurations (including the flag you want to remove), which already eliminates graph size trimming. As we've already discussed I believe we could conceptually get output path trimming with this approach.

But if we have some confidence that only, say, the top target in the build reads the flag, we could auto-remove the flag for all of it dependents. But that knowledge would have to come from a different place than visibility.

So... we do have options. Either of these approaches could yield benefits. If you want to continue exploring this I'd want to really lock down the use cases we'd want to optimize and understand the expected benefit. I wrote a tool [ctexplain](https://github.com/bazelbuild/bazel/commit/c1d7087b252e7c946a07fb782f64fb892af3208d) a while ago that could help. Any approach we take is some effort so we need to be as clear as possible how generally valuable the benefit would be on practical builds.

**Comment by ulrfa** [comment]
> > But in this context, I'm worried about #12669. What do you think about that?
> 
> Looks like we're making some progress on that. :) Can you remind me specifically where `config_setting` / `select()` fits into the larger request?

Yes good progress on #12669! Thanks @gregestren!

My idea is that user defined build settings could be ignored when calculating output path for an action, if that action (and its transitive dependencies) can not see the user defined build setting, due to the visibility. The config_setting could be seen as part of a transitive dependency chain (between the select() and the user defined build setting). But the dependency chain would not be reliable if the visibility of the config_setting could be circumvented. Right?

> If you want to continue exploring this I'd want to really lock down the use cases we'd want to optimize and understand the expected benefit. I wrote a tool ctexplain a while ago that could help. Any approach we take is some effort so we need to be as clear as possible how generally valuable the benefit would be on practical builds.

I hope to find time to investigate that next week. I got feedback from my colleagues that we might have build options that I was not aware, that affects cc_libraries deeper down in the dependency graph.
