### ISSUE TITLE
Can I build C/C++ project in XCode using bazel ？ 

### ISSUE THREAD

**Issue by Corezcy** [bazelbuild/bazel#12577]
### Description of the  feature request:

Can I build C/C++ project in XCode using bazel ? If possible , how to?

### What operating system are you running Bazel on?

Macos 10.14.6

### What's the output of `bazel info release`?

release 3.6.0-homebrew

**Comment by keith** [comment]
Yes you can, see the C++ documentation for examples / usage 

- https://docs.bazel.build/versions/master/tutorial/cpp.html
- https://docs.bazel.build/versions/master/be/c-cpp.html
- https://docs.bazel.build/versions/master/cpp-use-cases.html

**Comment by Corezcy** [comment]
> Yes you can, see the C++ documentation for examples / usage
> 
> * https://docs.bazel.build/versions/master/tutorial/cpp.html
> * https://docs.bazel.build/versions/master/be/c-cpp.html
> * https://docs.bazel.build/versions/master/cpp-use-cases.html

Currently , I use bazel in VSCode on MacOS , I want to change into XCode ,but find none tutorial. In the links you give me , I still dont know ··· ···

**Comment by Corezcy** [comment]
I give up, using VSCode  continually

**Comment by thii** [comment]
If you're building macOS tools, take a look at [Tulsi](https://tulsi.bazel.build).

**Comment by Corezcy** [comment]
> If you're building macOS tools, take a look at [Tulsi](https://tulsi.bazel.build).

Thanks ! I saw it ,but it is used to build swift project .

**Comment by thii** [comment]
I don't think it's limited to Swift (but it is limited to Apple platforms)—whatever Apple targets you can build with Bazel, then it can generate an Xcode project that you can work with.
