### ISSUE TITLE
ERROR: Analysis of target failed; build aborted: invalid registered execution platform '//:default_host_platform': no such target '//:default_host_platform': target 'default_host_platform' not declared in package

### ISSUE THREAD

**Issue by whogodemo** [bazelbuild/bazel#12585]
### Description of the problem / feature request:
run this command to print hello world.
=> bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world

then error occured.
error message 
=>
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: invalid registered execution platform '//:default_host_platform': no such target '//:default_host_platform': target 'default_host_platform' not declared in package '' defined by /home/money/mediapipe/BUILD.bazel
INFO: Elapsed time: 4.284s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (6 packages loaded, 6 targets conf\
FAILED: Build did NOT complete successfully (6 packages loaded, 6 targets conf\
igured)

### Feature requests: what underlying problem are you trying to solve with this feature?
I am trying to use mediapipe in ubuntu. Printing hello world is just checking bazel..

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
run
bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

release 2.0.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/google/mediapipe.git
f15da632dec186f2c1d3c780f47086477e2286a9
f15da632dec186f2c1d3c780f47086477e2286a9

###  Have you found anything relevant by searching the web?

> - https://github.com/tensorflow/tensorflow/issues/4279
> - https://qiita.com/soyeiji1220/items/732d125a35dd26d89036

Please Please Please help me..... Because I am not good at English, you may not understand well... sorry

**Comment by meteorcloudy** [comment]
We are seeing the same failure in https://github.com/bazelbuild/bazel/issues/12578

**Comment by meteorcloudy** [comment]
I couldn't reproduce the error following the instruction in this issue.

However, I was using Bazel 3.7.1 because the minimal required version is 3.4.0 at commit f15da632dec186f2c1d3c780f47086477e2286a9

Can you check if your WORKSPACE file was modified?

**Comment by victornain** [comment]
I have the exact same problem. But using Ubuntu 20.04 and Bazel 3.7.1. 
https://github.com/google/mediapipe/issues/1336#issue-751006779

**Comment by whogodemo** [comment]
> I couldn't reproduce the error following the instruction in this issue.
> 
> However, I was using Bazel 3.7.1 because the minimal required version is 3.4.0 at commit f15da632dec186f2c1d3c780f47086477e2286a9
> 
> Can you check if your WORKSPACE file was modified?

yes, I searched the error and found this solution. and I modified WORKSPACE file. sol: https://releases.bazel.build/bazel-toolchains.html
Is there any problem???

**Comment by whogodemo** [comment]
> I have the exact same problem. But using Ubuntu 20.04 and Bazel 3.7.1.
> [google/mediapipe#1336 (comment)](https://github.com/google/mediapipe/issues/1336#issue-751006779)

Haha I already saw that and modified WORKSPACE... But still same problem .....

**Comment by katre** [comment]
I can't reproduce this, either. The target `//:default_host_platform` really isn't present in mediapipe, although we do have a target named that in Bazel proper.

Can either @whogodemo or @victornain run the following and give me the output?
```
bazel run --announce_rc --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world
```

This will help determine if there's a bazelrc option that's contributing to the issue.

**Comment by whogodemo** [comment]
> I can't reproduce this, either. The target `//:default_host_platform` really isn't present in mediapipe, although we do have a target named that in Bazel proper.
> 
> Can either @whogodemo or @victornain run the following and give me the output?
> 
> ```
> bazel run --announce_rc --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world
> ```
> 
> This will help determine if there's a bazelrc option that's contributing to the issue.

This is the output. Thanks!!

Starting local Bazel server and connecting to it...

INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'run' from /home/money/mediapipe/.bazelrc:
  Inherited 'common' options: --enable_platform_specific_config
DEBUG: /home/money/.cache/bazel/_bazel_money/f8fa67832b324a524cf2546304b89b98/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:9: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True 
DEBUG: /home/money/.cache/bazel/_bazel_money/f8fa67832b324a524cf2546304b89b98/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:9: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True 
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: invalid registered execution platform '//:default_host_platform': no such target '//:default_host_platform': target 'default_host_platform' not declared in package '' defined by /home/money/mediapipe/BUILD.bazel
INFO: Elapsed time: 3.330s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (6 packages loaded, 6 targets conf\
FAILED: Build did NOT complete successfully (6 packages loaded, 6 targets conf\
igured)

**Comment by katre** [comment]
Nothing obvious there.

I'm a bit confused: in https://github.com/bazelbuild/bazel/issues/12585#issuecomment-736189608 you mentioned that you changed WORKSPACE for bazel-toolchains, but that's not present in the stock mediapipe WORKSPACE. Can you push your changes to a fork I can look at to see the exact state of your repository?

**Comment by victornain** [comment]
> I can't reproduce this, either. The target `//:default_host_platform` really isn't present in mediapipe, although we do have a target named that in Bazel proper.
> 
> Can either @whogodemo or @victornain run the following and give me the output?
> 
> ```
> bazel run --announce_rc --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world
> ```
> 
> This will help determine if there's a bazelrc option that's contributing to the issue.

<pre>Starting local Bazel server and connecting to it...
<font color="#C4A000">DEBUG: </font>/home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
<font color="#C4A000">DEBUG: </font>/home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True 
<font color="#C4A000">DEBUG: </font>/home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
<font color="#C4A000">DEBUG: </font>/home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True 
<font color="#C4A000">DEBUG: </font>/home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
<font color="#C4A000">DEBUG: </font>/home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: rbe_default not using checked in configs; Bazel version 3.4.0 was picked/selected but no checked in config was found in map {&quot;0.20.0&quot;: [&quot;8.0.0&quot;], &quot;0.21.0&quot;: [&quot;8.0.0&quot;], &quot;0.22.0&quot;: [&quot;8.0.0&quot;, &quot;9.0.0&quot;], &quot;0.23.0&quot;: [&quot;8.0.0&quot;, &quot;9.0.0&quot;], &quot;0.23.1&quot;: [&quot;8.0.0&quot;, &quot;9.0.0&quot;], &quot;0.23.2&quot;: [&quot;9.0.0&quot;], &quot;0.24.0&quot;: [&quot;9.0.0&quot;], &quot;0.24.1&quot;: [&quot;9.0.0&quot;], &quot;0.25.0&quot;: [&quot;9.0.0&quot;], &quot;0.25.1&quot;: [&quot;9.0.0&quot;], &quot;0.25.2&quot;: [&quot;9.0.0&quot;], &quot;0.26.0&quot;: [&quot;9.0.0&quot;], &quot;0.26.1&quot;: [&quot;9.0.0&quot;], &quot;0.27.0&quot;: [&quot;9.0.0&quot;], &quot;0.27.1&quot;: [&quot;9.0.0&quot;], &quot;0.28.0&quot;: [&quot;9.0.0&quot;], &quot;0.28.1&quot;: [&quot;9.0.0&quot;], &quot;0.29.0&quot;: [&quot;9.0.0&quot;], &quot;0.29.1&quot;: [&quot;9.0.0&quot;, &quot;10.0.0&quot;], &quot;1.0.0&quot;: [&quot;9.0.0&quot;, &quot;10.0.0&quot;], &quot;1.0.1&quot;: [&quot;10.0.0&quot;], &quot;1.1.0&quot;: [&quot;10.0.0&quot;], &quot;1.2.0&quot;: [&quot;10.0.0&quot;], &quot;1.2.1&quot;: [&quot;10.0.0&quot;], &quot;2.0.0&quot;: [&quot;10.0.0&quot;], &quot;2.1.0&quot;: [&quot;10.0.0&quot;], &quot;2.1.1&quot;: [&quot;10.0.0&quot;, &quot;11.0.0&quot;], &quot;2.2.0&quot;: [&quot;11.0.0&quot;], &quot;3.0.0&quot;: [&quot;11.0.0&quot;], &quot;3.1.0&quot;: [&quot;11.0.0&quot;]}
<font color="#CC0000"><b>ERROR: </b></font>Analysis of target &apos;//mediapipe/examples/desktop/hello_world:hello_world&apos; failed; build aborted: invalid registered execution platform &apos;//:default_host_platform&apos;: no such target &apos;//:default_host_platform&apos;: target &apos;default_host_platform&apos; not declared in package &apos;&apos; defined by /home/victor/mediapipe/BUILD.bazel
<font color="#4E9A06">INFO: </font>Elapsed time: 13.700s
<font color="#4E9A06">INFO: </font>0 processes.
<font color="#CC0000"><b>FAILED:</b></font> Build did NOT complete successfully (6 packages loaded, 6 target\
<font color="#CC0000"><b>FAILED:</b></font> Build did NOT complete successfully (6 packages loaded, 6 target\
s configured)
<font color="#4E9A06"><b>victor@Vickrp</b></font>:<font color="#3465A4"><b>~/mediapipe</b></font>$ bazel run --announce_rc --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world
Starting local Bazel server and connecting to it...
<font color="#4E9A06">INFO: </font>Options provided by the client:
  Inherited &apos;common&apos; options: --isatty=1 --terminal_columns=74
<font color="#C4A000">DEBUG: </font>/home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
<font color="#C4A000">DEBUG: </font>/home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True 
<font color="#C4A000">DEBUG: </font>/home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
<font color="#C4A000">DEBUG: </font>/home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True 
<font color="#C4A000">DEBUG: </font>/home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
<font color="#C4A000">DEBUG: </font>/home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: rbe_default not using checked in configs; Bazel version 3.7.1 was picked/selected but no checked in config was found in map {&quot;0.20.0&quot;: [&quot;8.0.0&quot;], &quot;0.21.0&quot;: [&quot;8.0.0&quot;], &quot;0.22.0&quot;: [&quot;8.0.0&quot;, &quot;9.0.0&quot;], &quot;0.23.0&quot;: [&quot;8.0.0&quot;, &quot;9.0.0&quot;], &quot;0.23.1&quot;: [&quot;8.0.0&quot;, &quot;9.0.0&quot;], &quot;0.23.2&quot;: [&quot;9.0.0&quot;], &quot;0.24.0&quot;: [&quot;9.0.0&quot;], &quot;0.24.1&quot;: [&quot;9.0.0&quot;], &quot;0.25.0&quot;: [&quot;9.0.0&quot;], &quot;0.25.1&quot;: [&quot;9.0.0&quot;], &quot;0.25.2&quot;: [&quot;9.0.0&quot;], &quot;0.26.0&quot;: [&quot;9.0.0&quot;], &quot;0.26.1&quot;: [&quot;9.0.0&quot;], &quot;0.27.0&quot;: [&quot;9.0.0&quot;], &quot;0.27.1&quot;: [&quot;9.0.0&quot;], &quot;0.28.0&quot;: [&quot;9.0.0&quot;], &quot;0.28.1&quot;: [&quot;9.0.0&quot;], &quot;0.29.0&quot;: [&quot;9.0.0&quot;], &quot;0.29.1&quot;: [&quot;9.0.0&quot;, &quot;10.0.0&quot;], &quot;1.0.0&quot;: [&quot;9.0.0&quot;, &quot;10.0.0&quot;], &quot;1.0.1&quot;: [&quot;10.0.0&quot;], &quot;1.1.0&quot;: [&quot;10.0.0&quot;], &quot;1.2.0&quot;: [&quot;10.0.0&quot;], &quot;1.2.1&quot;: [&quot;10.0.0&quot;], &quot;2.0.0&quot;: [&quot;10.0.0&quot;], &quot;2.1.0&quot;: [&quot;10.0.0&quot;], &quot;2.1.1&quot;: [&quot;10.0.0&quot;, &quot;11.0.0&quot;], &quot;2.2.0&quot;: [&quot;11.0.0&quot;], &quot;3.0.0&quot;: [&quot;11.0.0&quot;], &quot;3.1.0&quot;: [&quot;11.0.0&quot;]}
<font color="#CC0000"><b>ERROR: </b></font>Analysis of target &apos;//mediapipe/examples/desktop/hello_world:hello_world&apos; failed; build aborted: invalid registered execution platform &apos;//:default_host_platform&apos;: no such target &apos;//:default_host_platform&apos;: target &apos;default_host_platform&apos; not declared in package &apos;&apos; defined by /home/victor/mediapipe/BUILD.bazel
<font color="#4E9A06">INFO: </font>Elapsed time: 4.812s
<font color="#4E9A06">INFO: </font>0 processes.
<font color="#CC0000"><b>FAILED:</b></font> Build did NOT complete successfully (6 packages loaded, 6 target\
<font color="#CC0000"><b>FAILED:</b></font> Build did NOT complete successfully (6 packages loaded, 6 target\
s configured)</pre>

Same output :c

**Comment by katre** [comment]
Why is bazel-toolchains being used at all? Can you please share your WORKSPACE files?

**Comment by whogodemo** [comment]
> Nothing obvious there.
> 
> I'm a bit confused: in [#12585 (comment)](https://github.com/bazelbuild/bazel/issues/12585#issuecomment-736189608) you mentioned that you changed WORKSPACE for bazel-toolchains, but that's not present in the stock mediapipe WORKSPACE. Can you push your changes to a fork I can look at to see the exact state of your repository?

This is my WORKSPACE file.. Thank you so much
[WORKSPACE.txt](https://github.com/bazelbuild/bazel/files/5627948/WORKSPACE.txt)

**Comment by katre** [comment]
That is the WORKSPACE from Bazel (http://github.com/bazelbuild/bazel/), not the WORKSPACE from mediapipe (https://github.com/google/mediapipe). It refers to targets and packages that only exist in Bazel, not in mediapipe, such as `//:default_host_platform`.

I'm not sure why you've copied Bazel's WORKSPACE into your mediapipe repo, but it won't work and can't work. Revert back to the default mediapipe WORKSPACE file and this error will stop happening.

**Comment by victornain** [comment]
@katre by following the getting starting installation guide in https://mediapipe.dev/ I got the Bazel's WORKSPACE into the mediapipe repo, I didn't copy anything. 

Still, I followed your advice about getting the original mediapipe WORKSPACE file in the repository. But now I'm getting the following error. 

<pre><font color="#4E9A06">INFO: </font>SHA256 (https://github.com/bazelbuild/rules_foreign_cc/archive/master.zip) = 3e6b0691fc57db8217d535393dcc2cf7c1d39fc87e9adb6e7d7bab1483915110
<font color="#C4A000">DEBUG: </font>Rule &apos;rules_foreign_cc&apos; indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = &quot;3e6b0691fc57db8217d535393dcc2cf7c1d39fc87e9adb6e7d7bab1483915110&quot;
<font color="#C4A000">DEBUG: </font>Repository rules_foreign_cc instantiated at:
  /home/victor/mediapipe/WORKSPACE:39:13: in &lt;toplevel&gt;
Repository rule http_archive defined at:
  /home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in &lt;toplevel&gt;
<font color="#CC0000"><b>ERROR: </b></font>Traceback (most recent call last):
	File &quot;/home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/org_tensorflow/third_party/gpus/cuda_configure.bzl&quot;, line 1409, column 40, in &lt;toplevel&gt;
		remote_cuda_configure = repository_rule(
Error in repository_rule: in call to repository_rule(), parameter &apos;remotable&apos; is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_repo_remote_exec
<font color="#4E9A06">INFO: </font>Repository io_bazel_rules_closure instantiated at:
  /home/victor/mediapipe/WORKSPACE:356:13: in &lt;toplevel&gt;
Repository rule http_archive defined at:
  /home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in &lt;toplevel&gt;
<font color="#CC0000"><b>ERROR: </b></font>error loading package &apos;&apos;: in /home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/org_tensorflow/tensorflow/workspace.bzl: Extension file &apos;third_party/gpus/cuda_configure.bzl&apos; has errors
<font color="#4E9A06">INFO: </font>Elapsed time: 22.713s
<font color="#4E9A06">INFO: </font>0 processes.
<font color="#CC0000"><b>FAILED:</b></font> Build did NOT complete successfully (0 packages loaded)
<font color="#CC0000"><b>FAILED:</b></font> Build did NOT complete successfully (0 packages loaded)</pre>

**Comment by katre** [comment]
I can't visit mediapipe.dev due to a certificate error, but if the directions they are providing are not accurate you'll need to submit an issue to them. Copying the entire WORKSPACE file from another repository is not a safe approach in general, and specifically with Bazel's own WORKSPACE file.

Since I can't visit mediapipe.dev, I can't follow the directions, but I was able to clone mediapipe from Github and build from there. I think you'll need to file further issues with mediapipe or tensorflow, this does not appear to be a problem with Bazel itself and this github issue isn't a good way to provide user support for other projects that use Bazel.

**Comment by philwo** [comment]
@victornain @whogodemo I checked the documentation of MediaPipe and I agree that it can lead to accidentally overwriting your MediaPipe source code with the Bazel code. I'll send the team a fix for the docs that will prevent this in the future!

**Comment by victornain** [comment]
@philwo Thanks! In the meanwhile, what do you suggest we can do?

**Comment by philwo** [comment]
Assuming you're on Linux x86_64 (please let me know if you're on a different OS or architecture):

1. Install Bazel:

```
curl -O https://releases.bazel.build/3.7.1/release/bazel-3.7.1-linux-x86_64
mv bazel-3.7.1-linux-x86_64 /usr/local/bin/bazel
chmod +x /usr/local/bin/bazel
```

2. Install MediaPipe (Warning: this will delete any "mediapipe" folder in your home directory, in case you have one):

```
cd $HOME
rm -rf mediapipe
git clone https://github.com/google/mediapipe.git
cd mediapipe
```

Now continue with step 3: "Install OpenCV and FFmpeg" of the MediaPipe installation guide: https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu
