### ISSUE TITLE
Build process should not have hard-coded compiler paths

### ISSUE THREAD

**Issue by yurivict** [bazelbuild/bazel#1258]
Currently tools/cpp/CROSSTOOL has hard-coded compiler paths. For example, on FreeBSD it assumes that compiler is /usr/bin/clang. This is wrong because ports framework normally sets the compiler in a CC/CPP/CXX variables and it can be different from /usr/bin/clang. For example on FreeBSD 9.X /usr/bin/clang is of too old version, and different version needs to be used.

Additionally, external/local_config_cc is sometimes used for the compiler executable which is completely wrong.

compile.sh should respect CC/CPP/CXX/CFLAGS/CXXFLAGS passed through the environment variables or arguments.

**Comment by aehlig** [comment]
While this certainly is a legitimate feature request to honor the environment in the bootstrap
process, it, however, is low priority. The tools and flags to be used can still be specified
at a single place in an easy-to-generate format. So a port can, e.g., provide its own
``CROSSTOOL`` file, most likely using the ``SUB_FILES`` (and ``SUB_LIST``) mechanism
to generate it from a template.

**Comment by helenalt** [comment]
@katre is this going to be addressed by platforms & toolchains work?

**Comment by katre** [comment]
This is unrelated, since the platform-specific toolchain would still have hard-coded paths. This would need to be fixed by the CC rules themselves.

**Comment by bedbad** [comment]
Is there any progress on this? I repeatedly find wrong CC compiler flags when compiling dependencies such as tensorflow, which select wrong hardcoded flags like cpp standard. Additionally its very hard to debug for rules-users.
