### ISSUE TITLE
Error when using bazel build in angular 8

### ISSUE THREAD

**Issue by amitkatyal** [bazelbuild/bazel#12596]
I'm trying to build angular project with bazel build & getting below error.  

ERROR: /Users/ztna_userportal_applogo/gateway/ui/src/app/BUILD.bazel:37:10: Compiling Angular templates (ngc) //ui/src/app:app failed (Exit 1): ngc-wrapped.sh failed: error executing command 

  (cd /private/var/tmp/_bazel_amit.katyal/c6d6c66a668f2db56ab82b64d688c088/execroot/ztna_gateway && \

  exec env - \

  bazel-out/host/bin/external/npm/@angular/bazel/bin/ngc-wrapped.sh '--node_options=--expose-gc' '--node_options=--stack-trace-limit=100' '--node_options=--max-old-space-size=4096' @@bazel-out/darwin-fastbuild/bin/ui/src/app/app_es5_tsconfig.json)

Execution platform: @local_config_platform//:host

ui/src/app/user-layout/user-layout.component.ts(37,10): error TS2742: T**he inferred type of 'transform' cannot be named without a reference to '../../../../external/npm/node_modules/@angular/platform-browser/platform-browser'. This is likely not portable. A type annotation is necessary.**

Code changes
import { Component, OnInit } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { ApplicationService } from '../service/application.service';

@Component({
  selector: 'app-user-layout',
  templateUrl: './user-layout.component.html',
  styleUrls: ['./user-layout.component.scss'],
})

  **public transform(encodedString) { ==============> BUILD ERROR** 

    return this.domSanitizer.bypassSecurityTrustResourceUrl('data:image/png;base64,' + encodedString);

  }

Any idea what is the issue here ?

**Comment by aiuto** [comment]
This looks like an Angular usage question. You should try asking in a repository for their rules or an appropriate stack-overflow category.

**Comment by amitkatyal** [comment]
> This looks like an Angular usage question. You should try asking in a repository for their rules or an appropriate stack-overflow category.

okay, thanks.
