### ISSUE TITLE
Multiple bazel servers of same pid run concurrently  in the same workspace

### ISSUE THREAD

**Issue by yancl** [bazelbuild/bazel#12591]
### Description of the problem / feature request:

When we run bazel commands of same repo & same path on the same box, we expect only one Bazel server can run, but if the pid of the bazel servers in ${outputBase}/server/server.pid.txt are of same, they can run simultaneously. This would generate unexpected artifacts that may be wrong .

Background:
We use Bazel to build&test on CI(multiple containers of different jobs run on same host concurrently), but we want to use **incremental** build, so we mount a common host path(/home/bazel/.cache/bazel/, for example) to the containers. Then all the repos' output are shared across all the containers. We think Bazel use the server.pid as a mutex lock(or similar mechanism) to keep bazel command's result safety. But as the example shows, It can't guarantee that in this case.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I made a simple demo, please see here: https://github.com/yancl/bazel-concurrent-run-test/blob/master/README.md

### What operating system are you running Bazel on?

Both macOS&Linux

### What's the output of `bazel info release`?

/demo# bazel info release
Starting local Bazel server and connecting to it...
release 3.7.1

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

please see the example provided above.

**Comment by yancl** [comment]
Thanks @aiuto, I think "team-Core" may be more accurate than "team-Remote-Exec" since we didn't use Remote Execution yet :)

**Comment by michajlo** [comment]
Sharing an output base across what is essentially multiple hosts isn't really supported (bazel will emit warnings about the output base being on NFS).

What's happening in the same-pid situation in your demo is the bazel launcher sees that there's actually no process with the pid in `/proc/` so it (reasonably) assumes the server is gone and starts a new one. In the different pid situation, I'm pretty sure it's the same deal, except the server-side pid watcher notices that the `server.pid.txt` file changed and bails.

Could you set up your CI so that all jobs don't share the same output base? Workarounds in bazel might be possible, but they also might open up a big can of worms.

**Comment by yancl** [comment]
@michajlo Thank you for pointing out the logic behind the server.pid exactly and I have confirmed that, very appreciate.

> Sharing an output base across what is essentially multiple hosts isn't really supported (bazel will emit warnings about the output base being on NFS).

Yes, we didn't use NFS that is shared by multi host, we just run some bazel servers in each host and they share the same output path.

> Could you set up your CI so that all jobs don't share the same output base? 

Yes, we plan to do the following to make CI(incremental build) fast&correct:
* each bazel server in container has its own namespace isolated `outputUserRoot`(just isolate the `outputBase` is much better, but we can't configure the dynamic path with CI now)
* mount some host path to `${outputUserRoot}/install` & `${outputUserRoot}/cache`(no need to extract bazel into container fs(overlay fs is slow) and download the external repo artifacts through network each time)
* use local **host** disk cache through `--disk-cache` that is shared and mounted into the containers(incremental build)
* configure remote cache & remote execution(when local disk cache miss it helps a lot)

> Workarounds in bazel might be possible, but they also might open up a big can of worms.

Yes, totally understand. But I still have some questions:
* Is this behavior expected and reasonable?
* should Bazel guarantee its correctness when user misuse it like us(you see we know the client `lock` and server `pid` and though it was the mechanism behind concurrent control and we are just one of ten of thousands users of bazel, maybe others will misuse it like us)?

**Comment by michajlo** [comment]
I think the current behavior is expected and reasonable by virtue of the usage being pretty firmly in undefined behavior territory.

At a minimum documentation should be updated to include the caveats of this setup, if it isn't already. We could augment the pid-watcher functionality that caused the diff-pid case to bail, though that will only improve awareness, not safety, as it's unclear how much damage can be done between the "duplicate" server starting and it being detected.

**Comment by yancl** [comment]
Thanks, I will leave this open for some time since it's tagged P4 now.
