### ISSUE TITLE
flag_alias doesn't accept "-" in name

### ISSUE THREAD

**Issue by chsigg** [bazelbuild/bazel#12613]
### Description of the problem:

The new bazel command line option `--flag_alias` doesn't accept '-' in the alias name.

My hope is that this would be trivial to support.

### Bugs: what's the simplest, easiest way to reproduce this bug?

`bazel build --flag_alias=a-b=//:foo :all`

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

Using unreleased version at commit 8306b428d59f5c5624eefd774792f85d85ba0837

**Comment by aiuto** [comment]
I'm not sure we want to support that.  Is there a compelling need to use '-' instead of '_', beyond liking that style?
'-' is often a separator in command lines while '_' is generally part of an identifier. I think '-' in a name leads to confusion.

**Comment by juliexxia** [comment]
This isn't supported because the rules controlling what words are allowed to be flag aliases are the same rules governing native flag names AKA word characters. You should be able to use "_" instead. Feel free to reopen if you have more questions!

**Comment by chsigg** [comment]
Thanks for looking into it.

> I think '-' in a name leads to confusion.

Should bazel have an opinion on the user's choice of flag names? ;-)

I wanted to carry over clang's [--cuda-gpu-arch](https://llvm.org/docs/CompileCudaWithLLVM.html#invoking-clang) to bazel. 

`--cuda_gpu_arch` is acceptable, I don't mind if this issues is closed as WAI.

Thanks!
