### ISSUE TITLE
Build failure caused by name conflict between user defined repo name in local worksacpe and repo name in indirected depended repo name

### ISSUE THREAD

**Issue by hemisp** [bazelbuild/bazel#12611]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:
When we wanna to declare dependency of both abseil-cpp and protobuf in WORKSPACE at the same time as below:

    if "com_google_protobuf" not in native.existing_rules():
        git_repository(
            name = "com_google_protobuf",
            remote = "git@code.faw.cn:third_party_repos/protobuf.git",
            tag = "v3.9.0",
        )
.....
    if "com_google_absl" not in native.existing_rules():
        git_repository(
            name = "com_google_absl",
            commit = "d5bc72dbb6c50cdd2ab85bf6bd6a56f858da78bb",
            remote = "git@code.faw.cn:third_party_repos/abseil-cpp.git",
            shallow_since = "1603691491 +0800",
        )
and target is declared in BUILD as below:
cc_library(
    name = "status",
...
    deps = [
        "@com_google_absl//absl/status",
        "@glog",
    ],
)

Then there will be build error as below:
ERROR: /home/....../status/BUILD:3:11: no such package '@com_google_absl//absl/status': BUILD file not found in directory 'absl/status' of external repository @com_google_absl. Add a BUILD file to a directory to mark it as a package. and referenced by '//common/status:status'
ERROR: Analysis of target '//common/status:status' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.523s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (17 packages loaded, 108 targets configured)

BUT when i try to rename  absl dependency in WORKSPACE instead of "com_google_absl", for example:
if "absl" not in native.existing_rules():
        git_repository(
            name = "absl",
            commit = "d5bc72dbb6c50cdd2ab85bf6bd6a56f858da78bb",
            remote = "git@code.faw.cn:third_party_repos/abseil-cpp.git",
            shallow_since = "1603691491 +0800",
        )

bazel build :status  succeed. 
> Replace this line with your answer.

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Declare dependency of both abseil-cpp and protobuf in WORKSPACE at the same time as below:
    if "com_google_protobuf" not in native.existing_rules():
        git_repository(
            name = "com_google_protobuf",
            remote = "git@code.faw.cn:third_party_repos/protobuf.git",
            tag = "v3.9.0",
        )
.....
    if "com_google_absl" not in native.existing_rules():
        git_repository(
            name = "com_google_absl",
            commit = "d5bc72dbb6c50cdd2ab85bf6bd6a56f858da78bb",
            remote = "git@code.faw.cn:third_party_repos/abseil-cpp.git",
            shallow_since = "1603691491 +0800",
        )
and target is declared in BUILD as below:
cc_library(
    name = "status",
...
    deps = [
        "@com_google_absl//absl/status",
        "@glog",
    ],
)

then bazel build :status
> Replace this line with your answer.

### What operating system are you running Bazel on?
Ubuntu LTS18.04

> Replace this line with your answer.

### What's the output of `bazel info release`?
hemy@hemy-NUC8i7BEH:~/development/faw-ai/simulation/common/status$ bazel info release
INFO: Invocation ID: 00f8fe63-5202-42d9-8d4b-d26582ea0ae7
release 3.5.0

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?
We checked that protobuf depends on gtest which depends on absl at the same time in its WORKSPACE
third_party/googletest/WORKSPACE:

# Abseil http_archive(      
        name = "com_google_absl",      
        urls = ["https://github.com/abseil/abseil-cpp/archive/master.zip"],      
        strip_prefix = "abseil-cpp-master",
.....

suppose, so we doubt that there is name conflict between direct and indirect dependency, which we can't know the dependency of what we depended, so we can not know which name is conflict. And it's should be some kind of bug that bazel should handle with automatically.

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by hemisp** [comment]
@jin any progress on this issue?

**Comment by philwo** [comment]
Yes, this is currently working as intended and nothing we can do about.

We are addressing this in a redesign of the entire external dependency feature: https://docs.google.com/document/d/1moQfNcEIttsk6vYanNKIy3ZuK53hQUFq1b1r0rmsYVg/edit

**Comment by jwnimmer-tri** [comment]
Possibly related: #2704, and using `repo_mapping` for scoped renaming.
