### ISSUE TITLE
Accept config_settings in target_compatible_with

### ISSUE THREAD

**Issue by chsigg** [bazelbuild/bazel#12614]
### Description of the feature request:

bazel 4.0 adds a `target_compatible_with` common attribute that accepts a list `constraint_value`s. It would be great if it could also accept `config_setting`s.

### What underlying problem are you trying to solve with this feature?

I would like to mark a target to be compatible only if `:my_config_setting` is true, so that the target itself and all inverse dependencies don't build otherwise.

I can currently work around this by translating a `config_setting` into a `constraint_value` by `select()`ing the `constraint_setting`'s `default_constraint_value`. But apparently constraint_settings are supposed to be configuration independent, so that workaround is bad style:

```
config_setting(
  name = "my_config",
  ...
)
constraint_setting(
  name = "my_constraint",
  default_constraint_value = select({
    ":my_config": ":my_value",
    "//conditions_default": None,
  }),
)
constraint_value(
  name = "my_value",
  constraint_setting = ":my_constraint",
)
cc_binary(
  ...
  target_compatible_with = [
    # feature request: allow ":my_config" here instead
    ":my_value",
  ],
)
```

**Comment by gregestren** [comment]
Interesting. What conditions are you interested in?

CC @AustinSchuh @philsc

**Comment by gregestren** [comment]
We've also had some interesting discussion on compatibility based on toolchain properties (like compiler type) from the advent of this feature. So maybe there's conceptual overlap?

**Comment by chsigg** [comment]
> What conditions are you interested in?
I hope I understand your question correctly, that you are referring to the attributes of `config_setting`. I would probably only need config_settings that use the flag_values attribute.

**Comment by AustinSchuh** [comment]
@gregestren, This is in our original proposal, but was deferred until a second phase so we could get something working first.  It was how I've been thinking about implementing toolchain property based skipping.  So yea, sounds great!

**Comment by philsc** [comment]
Just so I understand properly. Is this functionally equivalent to creating a helper like this?
```python
def config_compatible(config_setting_target):
    return select({
        config_setting_target: [],
        "//conditions:default": ["@platforms//:incompatible"],
    })
```
and then using it like so:
```python
cc_binary(
  ...
  target_compatible_with = config_compatible(":my_value"),
)
```
Pretty sure you can do the above today.

Again, so I'm clear exactly what we're talking about, you'd like to get rid of the need for a helper function like `config_compatible()` above?

**Comment by chsigg** [comment]
Ha! Thanks a lot for thinking of this Philipp.

Yes, `select`ing on the target_compatible_with would be a perfectly fine alternative. I don't mind the helper function.

In fact, that's what I used before I realized that you can (currently, and I hear it might go away) `select` on the `default_constraint_value`. But by the time I wrote this issue I had already forgotten :-(

I'm happy with Philipp's approach and as far as I'm concerned you can close this issue.

Thanks for your help!

**Comment by gregestren** [comment]
Closing as acknowledged. 

To be clear, my preference is to try to limit built-in Bazel support to `constraint_value` and the mentioned to-be-implemented toolchain properties.

I like that a reasonable user-space approach was identified here, so you can get what you need without stretching Bazel's core API complexity.
