### ISSUE TITLE
bazel midl rule generated c++ header file and winmd file locates in different folder

### ISSUE THREAD

**Issue by sammi** [bazelbuild/bazel#12624]
When I use bazel to generate c++ header source code and winmd file from midl file, I found MyType.winmd file is  in output folder, while MyType.h locates at same directory as source code MyType.idl. What I want is that my generated header file locates at the same folder as MyType.winmd file.

MyType.idl:
```
namespace NS
{
    [default_interface]
    runtimeclass MyType
    {
    }
}
```

BUILD:
```
load(":cmd.bzl", "midl")
sh_binary(
    name = "midlCmd.bat",
    srcs = ["midl.bat"],
)
midl(
    name = "midlcc.bat",
    idl = "MyType.idl",
    winmd = "MyType.winmd",
)
```

cmd.bzl:
```
def _impl(ctx):
    winmd = ctx.outputs.winmd
    idl = ctx.file.idl
    ctx.actions.run(
        inputs = [idl],
        outputs = [winmd],
        arguments = [winmd.path, idl.path],
        progress_message = "Generate winmd from idl file: %s" % idl,
        executable = ctx.executable.code_gen_tool,
    )
midl = rule(
    implementation = _impl,
    output_to_genfiles = True,
    attrs = {
        "idl": attr.label(allow_single_file = True, mandatory = True),
        "winmd": attr.output(mandatory = True),
        "code_gen_tool": attr.label(
            executable = True,
            cfg = "exec",
            allow_files = True,
            default = Label("//cmd:midlCmd.bat"),
        ),
    },
)
```

midl.bat:
```
"C:\Program Files (x86)\Windows Kits\10\bin\10.0.20206.0\x64\midl.exe" ^
/metadata_dir "%WindowsSdkDir%References\%WindowsSDKVersion%Windows.Foundation.FoundationContract\4.0.0.0" ^
/reference "%WindowsSdkDir%References\%WindowsSDKVersion%Windows.Foundation.FoundationContract\4.0.0.0\Windows.Foundation.FoundationContract.winmd" ^
/cpp_cmd "C:\PROGRA~2\MICROS~1\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\cl.exe" ^
/notlb ^
/winrt ^
/nomidl ^
/nologo ^
/enum_class ^
/ns_prefix ^
/client none ^
/server none ^
/winmd %1 %2
```

run command:
```
bazel build //cmd:all
```
Generated MyType.h here:
```
C:\Users\songy\source\repos\tuware\cmd>dir
Directory of C:\Users\songy\source\repos\tuware\cmd
2020-12-02  10:41 PM    <DIR>          .
2020-12-02  10:40 PM    <DIR>          ..
2020-12-02  10:41 PM               188 BUILD
2020-12-02  10:33 PM               746 cmd.bzl
2020-12-02  10:30 PM            10,975 midl.bat
2020-12-02  10:41 PM             6,987 MyType.h
2020-11-02  08:41 PM                82 MyType.idl
```
Generated MyType.winmd is here:
```
C:\Users\songy\source\repos\tuware\bazel-bin\cmd>dir
2020-12-02  10:30 PM            10,975 midlCmd.bat
2020-12-02  10:40 PM    <DIR>          midlCmd.bat.runfiles
2020-12-02  10:40 PM               247 midlCmd.bat.runfiles_manifest
2020-12-02  10:41 PM             1,536 MyType.winmd
2020-12-02  10:40 PM    <DIR>          setupCppDesktopDevEnvironment.bat.runfiles
2020-12-02  10:40 PM               293 setupCppDesktopDevEnvironment.bat.runfiles_manifest
```

Anything I'm missing?

**Comment by sammi** [comment]
If I adding generated header file in outputs, it make it worse, the MyType.h would not be generated.

BUILD:
```
load(":cmd.bzl", "midl")

sh_binary(
    name = "midlCmd.bat",
    srcs = ["midl.bat"],
)
```

midl(
    name = "MyType",
    idl = "MyType.idl",
    winmd = "MyType.winmd",
    header = "MyType.h",
)


cmd.bzl
```
def _impl(ctx):
    
    winmd = ctx.outputs.winmd
    header = ctx.outputs.header
    idl = ctx.file.idl

    ctx.actions.run(
        inputs = [idl],
        outputs = [winmd, header],
        arguments = [winmd.path, idl.path],
        progress_message = "Generate winmd from idl file: %s" % idl.path,
        executable = ctx.executable.code_gen_tool,
    )

    print("Generated winmd file: %s" % winmd.path)
    print("Generated header file: %s" % header.path)


midl = rule(
    implementation = _impl,
    output_to_genfiles = True,
    attrs = {
        "idl": attr.label(allow_single_file = True, mandatory = True),
        "winmd": attr.output(mandatory = True),
        "header": attr.output(mandatory = True),
        "code_gen_tool": attr.label(
            executable = True,
            cfg = "exec",
            allow_files = True,
            default = Label("//cmd:midlCmd.bat"),
        ),
    },
)

```

it complains that cmd/MyType.h was not created.
C:\users\songy\_bazel_songy\ii27dtnu\execroot\com_github_sammi_tuware>"C:\Program Files (x86)\Windows Kits\10\bin\10.0.20206.0\x64\midl.exe" /metadata_dir "C:\Program Files (x86)\Windows Kits\10\References\10.0.20206.0\Windows.Foundation.FoundationContract\4.0.0.0" /reference "C:\Program Files (x86)\Windows Kits\10\References\10.0.20206.0\Windows.Foundation.FoundationContract\4.0.0.0\Windows.Foundation.FoundationContract.winmd" /cpp_cmd "C:\PROGRA~2\MICROS~1\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\cl.exe" /notlb /winrt /nomidl /nologo /enum_class /ns_prefix /client none /server none /winmd bazel-out/x64_windows-fastbuild/bin/cmd/MyType.winmd cmd/MyType.idl
ERROR: C:/users/songy/source/repos/tuware/cmd/BUILD:8:5: output 'cmd/MyType.h' was not created
ERROR: C:/users/songy/source/repos/tuware/cmd/BUILD:8:5: not all outputs were created or valid

**Comment by philwo** [comment]
If I understand correctly the `MyType.h` and `MyType.winmd` files are both created by your `midl.cmd` tool, right? But the `.h` is generated next to the source file and the `.winmd` file is generated in the output dir?

In that case, you have to somehow convince the midl Tool that you're calling to generate the `.h` file not next to the source file but also in the output dir file (like the `.winmd` file).

Hope this helps! I would advise to continue the discussion on https://groups.google.com/forum/?nomobile=true#!forum/bazel-discuss otherwise, as other users are more likely to be able to have encountered this in their builds. :)

I'm closing this, as I don't think this is an actual bug in Bazel itself.

**Comment by sammi** [comment]
Thanks for the comment, it is being solved by using /out option. Details are here:
https://stackoverflow.com/questions/65121191/bazel-midl-rule-generated-c-header-file-and-winmd-file-locates-in-different-fo
