### ISSUE TITLE
new_http_archive doesn't work Go Appengine SDK

### ISSUE THREAD

**Issue by vertix** [bazelbuild/bazel#1263]
I'm trying to pull Go Appengine SDK into my repository. Bazel has hard time unzipping the archive.

I run it on MacOS 10.11.4. In order to reproduce create an empty directory with two files:
WORKSPACE:
> new_http_archive(
>    name = "goappsdk",
>  url = "https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_darwin_amd64-1.9.37.zip",
>  sha256 = "5b7313f9b77224caad9af07f743cc1c7bf52a7395f79edd5b348e2dd4e6627fd",
>  build_file = "BUILD.app",
>  strip_prefix = "go_appengine",
>)

BUILD.app:
> filegroup(
>     name = "sdk",
>     srcs = glob(["**"]),
>     visibility = ["//visibility:public"],
> )

and run:
`bazel build @goappsdk//:sdk`

It downloads file but then fails with:
> ERROR: no such package '@goappsdk//': Error extracting /private/var/tmp/_bazel_vertix/53d2bd49c7f06d36ba52bebd208f8819/external/goappsdk/go_appengine_sdk_darwin_amd64-1.9.37.zip to /private/var/tmp/_bazel_vertix/53d2bd49c7f06d36ba52bebd208f8819/external/goappsdk: /private/var/tmp/_bazel_vertix/53d2bd49c7f06d36ba52bebd208f8819/external/goappsdk/demos (File exists).

Droping `strip_prefix` attribute from new_http_archive doesn't help

**Comment by vertix** [comment]
And yes, this is Mac OS 10.11.4

**Comment by kchodorow** [comment]
Reproduced, I'd guess that the zip file has demos/ twice and Bazel's unzip code isn't handling that properly.  As a workaround for now, you can download and manually extract the .zip, then replace new_http_archive() with:

```
new_local_repository(
    name = "goappsdk",
    path = "/path/to/your/download/go_appengine",
    build_file = "BUILD.app",
)
```

**Comment by kchodorow** [comment]
Okay, nope, the go appengine binary just lists demos/ as being of type "regular file" (not directory). "Fixing" bazel to assume paths ending in / are dirs, regardless of type...
