### ISSUE TITLE
bazel coverage -s //... error for cpplint

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/bazel#12641]
bazel test -s //... success while bazel coverage -s //... report an error, below was error log, I used cpplint in my project

notice I‘m use zsh insted bash

or how to ignore cpplint test, I have define --test_tag_filters in .bazelrc file

SUBCOMMAND: # //src:http_data_util_test_cpplint [action 'Testing //src:http_data_util_test_cpplint', configuration: 5c6cb178eea3eb4c64a77d784918faadbe81ba8b06403957b6288323679003c0, execution platform: @local_config_platform//:host]
(cd /home/tiger/.cache/bazel/_bazel_tiger/37f3d6e8649c38bf59c18a5fb56d595c/execroot/demo_server && \
  exec env - \
    PATH=/usr/bin:/bin \
    TEST_BINARY=src/http_data_util_test_cpplint \
    TEST_NAME=//src:http_data_util_test_cpplint \
    TEST_SHARD_INDEX=0 \
    TEST_TOTAL_SHARDS=0 \
  external/bazel_tools/tools/test/generate-xml.sh bazel-out/k8-opt/testlogs/src/http_data_util_test_cpplint/test.log bazel-out/k8-opt/testlogs/src/http_data_util_test_cpplint/test.xml 0 1)
SUBCOMMAND: # //src:http_data_util_cpplint [action 'Testing //src:http_data_util_cpplint', configuration: 5c6cb178eea3eb4c64a77d784918faadbe81ba8b06403957b6288323679003c0, execution platform: @local_config_platform//:host]
(cd /home/tiger/.cache/bazel/_bazel_tiger/37f3d6e8649c38bf59c18a5fb56d595c/execroot/demo_server && \
  exec env - \
    PATH=/usr/bin:/bin \
    TEST_BINARY=src/http_data_util_cpplint \
    TEST_NAME=//src:http_data_util_cpplint \
    TEST_SHARD_INDEX=0 \
    TEST_TOTAL_SHARDS=0 \
  external/bazel_tools/tools/test/generate-xml.sh bazel-out/k8-opt/testlogs/src/http_data_util_cpplint/test.log bazel-out/k8-opt/testlogs/src/http_data_util_cpplint/test.xml 0 1)
FAIL: //src:http_data_util_test_cpplint (see /home/tiger/.cache/bazel/_bazel_tiger/37f3d6e8649c38bf59c18a5fb56d595c/execroot/demo_server/bazel-out/k8-opt/testlogs/src/http_data_util_test_cpplint/test.log)
SUBCOMMAND: # //src:demo_cpplint [action 'Testing //src:demo_cpplint', configuration: 5c6cb178eea3eb4c64a77d784918faadbe81ba8b06403957b6288323679003c0, execution platform: @local_config_platform//:host]
(cd /home/tiger/.cache/bazel/_bazel_tiger/37f3d6e8649c38bf59c18a5fb56d595c/execroot/demo_server && \
  exec env - \
    PATH=/usr/bin:/bin \
    TEST_BINARY=src/demo_cpplint \
    TEST_NAME=//src:demo_cpplint \
    TEST_SHARD_INDEX=0 \
    TEST_TOTAL_SHARDS=0 \
  external/bazel_tools/tools/test/generate-xml.sh bazel-out/k8-opt/testlogs/src/demo_cpplint/test.log bazel-out/k8-opt/testlogs/src/demo_cpplint/test.xml 0 1)
SUBCOMMAND: # //src:http_service_cpplint [action 'Testing //src:http_service_cpplint', configuration: 5c6cb178eea3eb4c64a77d784918faadbe81ba8b06403957b6288323679003c0, execution platform: @local_config_platform//:host]
(cd /home/tiger/.cache/bazel/_bazel_tiger/37f3d6e8649c38bf59c18a5fb56d595c/execroot/demo_server && \
  exec env - \
    PATH=/usr/bin:/bin \
    TEST_BINARY=src/http_service_cpplint \
    TEST_NAME=//src:http_service_cpplint \
    TEST_SHARD_INDEX=0 \
    TEST_TOTAL_SHARDS=0 \
  external/bazel_tools/tools/test/generate-xml.sh bazel-out/k8-opt/testlogs/src/http_service_cpplint/test.log bazel-out/k8-opt/testlogs/src/http_service_cpplint/test.xml 0 1)
FAIL: //src:http_data_util_cpplint (see /home/tiger/.cache/bazel/_bazel_tiger/37f3d6e8649c38bf59c18a5fb56d595c/execroot/demo_server/bazel-out/k8-opt/testlogs/src/http_data_util_cpplint/test.log)
FAIL: //src:demo_cpplint (see /home/tiger/.cache/bazel/_bazel_tiger/37f3d6e8649c38bf59c18a5fb56d595c/execroot/demo_server/bazel-out/k8-opt/testlogs/src/demo_cpplint/test.log)
FAIL: //src:http_service_cpplint (see /home/tiger/.cache/bazel/_bazel_tiger/37f3d6e8649c38bf59c18a5fb56d595c/execroot/demo_server/bazel-out/k8-opt/testlogs/src/http_service_cpplint/test.log)
INFO: Elapsed time: 0.393s, Critical Path: 0.25s

**Comment by nwf5d** [comment]
@xiedeacc are you fix this error? I guess is the command parameter not used correct, but I don't known which is the key parameter. any reply will be appreciated!

**Comment by xiedeacc** [comment]
> @xiedeacc are you fix this error? I guess is the command parameter not used correct, but I don't known which is the key parameter. any reply will be appreciated!

oops, it's too long to remenber,  it seems cpplint was uncompatible to python3 in my long away memory
