### ISSUE TITLE
Support compressed Bytestream transfers for remote execution

### ISSUE THREAD

**Issue by bergsieker** [bazelbuild/bazel#12670]
### Description of the problem / feature request:

The RE API is close to finalizing support for API-level compression on Bytestream (https://github.com/bazelbuild/remote-apis/pull/168). Using compression is optional, but Bazel should support it at some point.

### Feature requests: what underlying problem are you trying to solve with this feature?

Remote builds can use significant bandwidth. Compression reduces the bandwidth used, which can also lead to significant performance improvements for bandwidth-constrained network connections.

### What operating system are you running Bazel on?

This applies to all operating systems that Bazel supports.

**Comment by bergsieker** [comment]
Assigning to Philipp for triage and prioritization.

**Comment by philwo** [comment]
@coeuvre Could you have a look and apply a P-label that you deem correct? :)

Quick guidance:
 - **P0:** This is an emergency and more important than other current work. (Assignee required)
 - **P1:** I'll work on this now. (Assignee required)
 - **P2:** We'll work on this soon. (Assignee optional)
 - **P3:** I won't work on this soon, but happy to review a PR. (No assignee)
 - **P4:** This is probably out of scope and will be closed soon. (No assignee)

**Comment by coeuvre** [comment]
Thanks. I am happy to implement this.

**Comment by chancila** [comment]
any movement on this feature?

**Comment by philwo** [comment]
@chancila Thanks for checking in! I actually just this week thought of it and have found a colleague who would like to implement it :) We'll follow up with details here soon.

**Comment by coeuvre** [comment]
Closing since this is implemented by #14041.
