### ISSUE TITLE
Supporting 64bit RISC-V

### ISSUE THREAD

**Issue by advancedwebdeveloper** [bazelbuild/bazel#12683]
### Description of the problem / feature request:

Providing support for 64 bit RISC-V

### Feature requests: what underlying problem are you trying to solve with this feature?

Ensuring the availability of fully functional RPM, DEB packages on RISC-V ports of Debian/Ubuntu, OpenSUSE and Fedora.
Ordinary VM options assumed, as also as binfmt/nspawn qemu(JeOS)-inside-containers.
As for the hardware support (not under Qemu) - enabling specific RISC-V extensions, to improve the performance on concrete SoC boards. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
The nearest bug is the lack of properly configured amount of vRAM, required to build a "bootstrapped" version of Bazel, under (specifically) rv64gc (estimation).

### What operating system are you running Bazel on?

I only tried to build Bazel on https://en.opensuse.org/openSUSE:RISC-V . I followed those instructions.

**Comment by advancedwebdeveloper** [comment]
CC @mzeren-vmw

**Comment by advancedwebdeveloper** [comment]
Found first related bug:

> oceanfish81@riscv:/home/oceanfish81/bazel> env EXTRA_BAZEL_ARGS='--jvmopt="-Xmx3G"  --host_javabase=@local_jdk//:jdk' bash ./compile.sh
> 🍃  Building Bazel from scratch......
> 🍃  Building Bazel with Bazel.
> .OpenJDK 64-Bit Zero VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
> DEBUG: /tmp/bazel_DaaLPRWl/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:14: 
> Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '3.1.0'
> DEBUG: /tmp/bazel_DaaLPRWl/out/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True 
> DEBUG: /tmp/bazel_DaaLPRWl/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:14: 
> Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '3.1.0'
> DEBUG: /tmp/bazel_DaaLPRWl/out/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True 
> DEBUG: /tmp/bazel_DaaLPRWl/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:47:14: 
> Current Bazel is not a release version, cannot check for compatibility.
> DEBUG: /tmp/bazel_DaaLPRWl/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:49:14: Make sure that you are running at least Bazel 0.21.0.
> ERROR: /tmp/bazel_DaaLPRWl/out/external/local_config_cc/BUILD:47:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'unknown'
> ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed
> INFO: Elapsed time: 684.978s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (28 packages loaded, 69 targets co\
> nfigured)
> 
>

**Comment by advancedwebdeveloper** [comment]
@adrianschroeter , what is the best way to check whether an application is running under systemd-nspawn + qemu-linux-user (JeOS) ?
It makes sense to form such a configuration, for Bazel.

**Comment by olekw** [comment]
> > ERROR: /tmp/bazel_DaaLPRWl/out/external/local_config_cc/BUILD:47:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'unknown'
> > ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed

@advancedwebdeveloper Have you looked at the Debian packaging of Bazel recently? I tried a trivial fix for this issue as part of my experiments to see if it's possible to support RISC-V. I no longer get this error. However, the build still freezes partway through and I have been unable to determine why. Feel free to take a look at what I have and use the [riscv64.Dockerfile](https://salsa.debian.org/bazel-team/bazel-bootstrap/-/blob/olek-mips-riscv/debian/riscv64.Dockerfile) to build on any architecture.

**Comment by advancedwebdeveloper** [comment]
> oceanfish81@riscv:/home/oceanfish81/bazel-4.0.0> env EXTRA_BAZEL_ARGS='--jvmopt="-Xmx3G" --host_javabase=@local_jdk//:jdk' bash ./compile.sh
> 🍃  Building Bazel from scratch......
> 🍃  Building Bazel with Bazel.
> .OpenJDK 64-Bit Zero VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
> DEBUG: /tmp/bazel_PAChtKwT/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:14: 
> Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '3.1.0'
> DEBUG: /tmp/bazel_PAChtKwT/out/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True 
> DEBUG: /tmp/bazel_PAChtKwT/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:14: 
> Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '3.1.0'
> DEBUG: /tmp/bazel_PAChtKwT/out/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True 
> ERROR: /tmp/bazel_PAChtKwT/out/external/local_config_platform/BUILD.bazel:4:9: no such target '@platforms//cpu:riscv64': target 'riscv64' not declared in package 'cpu' defined by /tmp/bazel_PAChtKwT/out/external/platforms/cpu/BUILD and referenced by '@local_config_platform//:host'
> ERROR: While resolving toolchains for target //src:bazel-bin_nojdk: Target @local_config_platform//:host was referenced as a platform, but does not provide PlatformInfo
> ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted: Analysis failed
> INFO: Elapsed time: 563.704s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (4 packages loaded, 0 targets conf\
> igured)
>

**Comment by olekw** [comment]
@advancedwebdeveloper If you're not in a huge hurry, I'd wait a little bit. @meteorcloudy and I have been talking about how to move the Debian patches supporting RISC-V 64 (and MIPS 64) to mainline Bazel. Once that happens, (and assuming there are no unanticipated problems!) it will be *MUCH* easier for you to do this build. :)

**Comment by olekw** [comment]
@advancedwebdeveloper and other interested parties: We have just had the first successful [experimental build of Bazel in Debian for RISC-V](https://packages.debian.org/source/experimental/bazel-bootstrap). You can download both the source package and the binaries at this link. If it seems to work (I have no easy way of testing it) I will put these changes into unstable and request a freeze exemption for Debian 11. Feedback welcome!

**Comment by olekw** [comment]
Today I uploaded a version of Bazel (as bazel-bootstrap) to [Debian unstable](https://packages.debian.org/source/sid/bazel-bootstrap) with support for 64bit RISC-V. It is still building but should be available for download in the next day or two. It is currently slated for release with Debian 11 (Bullseye) on amd64. arm64, ppc64el, s390x, ppc64, and riscv64. (and mips64el if we can address an OpenJDK bug on that architecture). Thanks to the Bazel team (and especially @meteorcloudy) for their advice and assistance with helping to make this happen!

**Comment by advancedwebdeveloper** [comment]
@gdams, would you test it?

**Comment by advancedwebdeveloper** [comment]
Ahead of my checks: is it possible to migrate it to https://cdimage.ubuntu.com/ubuntu-server/daily-preinstalled/current/hirsute-preinstalled-server-riscv64.img.xz ?

**Comment by olekw** [comment]
@advancedwebdeveloper Ubuntu pulled the latest version of bazel-bootstrap a few days ago. On the 25th, if I remember correctly. So if that's a daily CD image then it should be on there.

If you're asking for the package to be included on Ubuntu's default install media, and if it currently is not, then I can't help you. You would probably need to discuss that with a member of Ubuntu's release team.

**Comment by olekw** [comment]
Oh, also, the RISC-V version is available through the Debian Unstable link above as of about a day ago.

**Comment by advancedwebdeveloper** [comment]
> root@ubuntu:~/mc# apt search bazel
> Sorting... Done
> Full Text Search... Done
> root@ubuntu:~/mc# uname -a
> Linux ubuntu 5.8.0-16-generic #18+21.04.3-Ubuntu SMP Wed Feb 10 14:27:31 UTC 2021 riscv64 riscv64 riscv64 GNU/Linux

**Comment by advancedwebdeveloper** [comment]
> # cat /etc/*release*
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=21.04
> DISTRIB_CODENAME=hirsute
> DISTRIB_DESCRIPTION="Ubuntu Hirsute Hippo (development branch)"

**Comment by olekw** [comment]
> > root@ubuntu:~/mc# apt search bazel
> > Sorting... Done
> > Full Text Search... Done
> > root@ubuntu:~/mc# uname -a
> > Linux ubuntu 5.8.0-16-generic #18+21.04.3-Ubuntu SMP Wed Feb 10 14:27:31 UTC 2021 riscv64 riscv64 riscv64 GNU/Linux

Looking at [Ubuntu's package page](https://launchpad.net/ubuntu/+source/bazel-bootstrap), the riscv64 architecture is showing a "Pending publication" status. I would assume that means it will be available soon.

**Comment by advancedwebdeveloper** [comment]
Could I compile your package now, via sbuild?

**Comment by olekw** [comment]
> Could I compile your package now, via sbuild?

Absolutely! If it's working on the build daemons it should work just fine on your machine as well. Feel free to file a bug with [Debian](https://www.debian.org/Bugs/Reporting) if you run into any problems.

**Comment by olekw** [comment]
And looks like the vanilla Bazel should build now as well!

**Comment by advancedwebdeveloper** [comment]
I shall check that, today

**Comment by 6eanut** [comment]
Now I want to compile bazel6.1.0 on risc-v, is there a way？

**Comment by meteorcloudy** [comment]
Check how support was added for "s390x" https://cs.opensource.google/search?q=%22s390x%22&ss=bazel%2Fbazel and make sure the same code exists for "rsicv64". PRs are welcome!

**Comment by 6eanut** [comment]
@meteorcloudy 
thanks for answering!
i am working on building tensorflow from source on risc-v. when building the tensorflow(2.15.0)'s wheel, bazel(6.1.0) is needed.
i download the [dist file](https://github.com/bazelbuild/bazel/releases/download/6.1.0/bazel-6.1.0-dist.zip). and then, there are two ways:
1.bazel build bazel:
i can `dnf install bazel`. but when run `bazel build //src:bazel`, meet the trobule `[tf@openeuler-riscv64-worker1 bazel-source]$ bazel build //src:bazel
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...
Illegal instruction (core dumped)
`
2.build from source:
when i run `./compile`, i can get the binary file. but when i run ./bazel , i meet the trouble `Illegal instruction (core dumped)
`

**Comment by meteorcloudy** [comment]
Yeah, unfortunately, we don't officially support risc-v yet.

**Comment by 6eanut** [comment]
@meteorcloudy thanks for help!
