### ISSUE TITLE
`--repo_env` should be a `common` option

### ISSUE THREAD

**Issue by sjoerdvisscher** [bazelbuild/bazel#12689]
### Description of the problem / feature request:

Currently [`--repo_env`](https://docs.bazel.build/versions/master/command-line-reference.html#flag--repo_env) is not a `common` argument. I don't see how it could be useful if I just set it on `build`: If I first do `bazel build` it applies the `repo_env` and downloads the repository data. But if I then do `bazel query` `repo_env` is no longer applied, the repository cache is invalidated and all the repository data is downloaded again.

If I could just set `--repo_env` on `common` this would not happen.

**Comment by philwo** [comment]
This was fixed via https://github.com/bazelbuild/bazel/commit/c2bdd034014f66ce14529cc353cda18a32320f6c.
