### ISSUE TITLE
closures are a great way to smuggle state

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#12701]
Bazel has a few ways to defer Starlark work to execution. For instance, `Args.add_all` takes a `map_each` parameter that is called during execution for every element in a sequence. Here's a silly example of that:
```
def _append_foo(f):
    return f.path + "-foo"

def rule_implementation(ctx):
    ...
    args = ctx.actions.args()
    args.add_all(ctx.files.srcs, map_each=_append_foo)
    ctx.actions.run(
        args = [args],
        ...
    )
    ...
```
Historically, a large restriction on this technique has been the lack of nested functions and closures, which means execution-time callbacks are restricted to whatever Bazel sees fit to pass into them. Now that Starlark has closures and nested functions, though, much more interesting `map_each` functions are a possible:
```
def rule_implementation(ctx):
    ...
    args = ctx.actions.args()
    args.add_all(ctx.files.srcs, map_each=lambda f: f.path + "-" + ctx.label.name)
    ctx.actions.run(
        args = [args],
        ...
    )
    ...
```
There's new power here but also danger. Presumably, the above lambda, closing over `ctx`, "leaks" everything `RuleContext` transitively references into execution. Subtle adjustments can have large ramifications—if I wrote `name = ctx.label.name` in the rule implementation above and closed over the simple string `name`, the memory usage would be less concerning. There's not good mechanism to detect these problems; [existing Starlark memory profiling](https://docs.bazel.build/versions/master/skylark/performance.html#memory-profiling) isn't set up to catch cross-phase leaks.

**Comment by meisterT** [comment]
cc @alandonovan

**Comment by alandonovan** [comment]
The ctx object, like many bazel built-in data types, already has safety checks to ensure that it is only called from threads in the appropriate phase. After that point, it becomes an empty shell of an object that fails when its methods are called and doesn't retain references that would extend the lifetimes of other objects. (At least, that's my recollection.)

I'm a little surprised that map_each and similar interfaces don't accept a "clientdata" parameter that is passed through to the function call, analogous to callback interfaces in C (which doesn't have closures) which require two parameters---one for code, one for data. The introduction of closures makes the data argument redundant; but the omission of the the data parameter unduly restricts what the code can express. I think you are suggesting that there may be places in Bazel where correctness or performance relies on that restriction. I'm not aware of any. Certainly we should be cognizant of the power of closures when adding callback interfaces in future, but I don't yet see any compelling reason to deny ourselves their benefits.

**Comment by benjaminp** [comment]
> The ctx object, like many bazel built-in data types, already has safety checks to ensure that it is only called from threads in the appropriate phase. After that point, it becomes an empty shell of an object that fails when its methods are called and doesn't retain references that would extend the lifetimes of other objects. (At least, that's my recollection.)

This is [true](https://cs.opensource.google/bazel/bazel/+/70c0e617b37d46aa09b4fd9c80607e1cdb5b1ef9:src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleContext.java;l=389). So, my OP example would fail as literally written. However, I intended `ctx` to stand for any large analysis-time object. (Either one the user could creates themselves or one from some attribute of `ctx`.)

> 
> I'm a little surprised that map_each and similar interfaces don't accept a "clientdata" parameter that is passed through to the function call, analogous to callback interfaces in C (which doesn't have closures) which require two parameters---one for code, one for data. The introduction of closures makes the data argument redundant; but the omission of the the data parameter unduly restricts what the code can express. I think you are suggesting that there may be places in Bazel where correctness or performance relies on that restriction. I'm not aware of any. Certainly we should be cognizant of the power of closures when adding callback interfaces in future, but I don't yet see any compelling reason to deny ourselves their benefits.

I don't dispute the utility of closures; certainly I have places I'd like to use them lined up. I had always assumed (perhaps erroneously) that the constrained interface of `map_each` was a design choice to keep late Starlark execution purely a function of data already available in the execution phase. (I don't remember if there was a public design doc for `ctx.action.args`.) If that was indeed the intention, nested functions represent an implicit expansion of the API surface.

If this issue is NOTABUG, that's fine with me. At least the discussion of the tradeoffs has been (publicly) documented. I just want to record that with closures, 1) it's very easy to hang onto large objects and 2) it's tricky to detect that that is the cause of a memory regression.

**Comment by alandonovan** [comment]
> I intended ctx to stand for any large analysis-time object. (Either one the user creates themselves or one from some attribute of ctx.)

I think all the ctx.attr subobjects behave the same way as ctx (with self-destruct semantics), but I take your point that the range of analysis objects is broad.



> I had always assumed (perhaps erroneously) that the constrained interface of map_each was a design choice to keep late Starlark execution purely a function of data already available in the execution phase. (I don't remember if there was a public design doc for ctx.action.args.) If that was indeed the intention, nested functions represent an implicit expansion of the API surface.

Good point. I did some archaeology and found this doc, excerpted below:
  https://docs.google.com/document/d/1-XEr6YLHXVpleAKxeKEXNZrVXotWB7ZTFW0y95sp0Po
```
Alternatives considered
Passing general functions 
We considered passing general functions with data as args. This is very general but unfortunately very unwieldy, requiring to pass all the state from action-generating function to args-building function in a special data structures, and control flow is reversed.

Lambdas/nested function definitions might make it slightly nicer, but with those it is too easy to close over something inappropriate such as targets or providers.

Args mechanism is a nice, safe and "powerful-enough" compromise.
```

I suppose the question now is what to do about it. Some options:
a) do nothing and hope for the best.
b) improve dynamic tooling for detecting large values.
c) make nested def/lambda a file-level option, so that Bazel can disable it.
d) add a method to detect whether a StarlarkFunction is a top-level function. Args.map_each could then impose its restriction locally.
I'm not optimistic about (a); (b) would be good to pursue in any case, but will take time; (c) throws out the baby with the bathwater; (d) is unfortunately nonorthogonal, but seems like the prudent choice.

Thanks for flagging this so astutely.

**Comment by brandjon** [comment]
Checking the [current](https://github.com/bazelbuild/bazel/blob/e22c6160d8be488a1a8e2231904a467bb6f0a2c4/src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkCustomCommandLine.java#L830-L832) expected signature, it looks like map_each functions can have default args, though in the absence of nested functions that doesn't capture anything from the analysis phase.

(Interestingly, the check is whether there are two params, not two params capable of receiving positional args, leading to an unnecessary error for a map_each func with signature `f(arg, *, kwonly=defaultval)`.)

**Comment by brandjon** [comment]
The restriction to global functions added by d73656d7c80e33a5b74f7ed289ef4ad4f547f6b0 was undone in #13730. Now I'm aiming to rein this back in in a principled way. See design discussion in #18825.
