### ISSUE TITLE
Bazel gRPC java server throws java.lang.NoSuchMethodError: 'io.grpc.Deadline$Ticker io.grpc.Deadline.getSystemTicker()'

### ISSUE THREAD

**Issue by neonelect** [bazelbuild/bazel#12718]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Problem building gRPC java server with bazel

### Feature requests: what underlying problem are you trying to solve with this feature?

-

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Dependencies:
```
"org.mockito:mockito-all:1.10.19",
        "org.apache.logging.log4j:log4j-api:2.13.3",
        "org.apache.logging.log4j:log4j-core:2.13.3",
        "io.grpc:grpc-protobuf:1.34.1",
        "io.grpc:grpc-stub:1.34.1",
        "io.grpc:grpc-services:1.34.1",
        "io.grpc:grpc-netty-shaded:1.34.1",
        "org.apache.tomcat:annotations-api:6.0.53",
        "com.google.inject:guice:5.0.0-BETA-1",
        "com.squareup.okhttp:okhttp:2.7.5",
        "com.google.guava:guava:30.0-jre"
```

Just try to start the server like:

```
server = NettyServerBuilder.forPort(<some port in int>)
            .addService(<valid server instance>)
      .build();

...

LOGGER.info("Starting gRPC server ... ");
    server.start();
    LOGGER.info("GRPC server started @ " + this.port);
    server.awaitTermination();
```

### What operating system are you running Bazel on?

MacOS Catalina 10.15.7

### What's the output of `bazel info release`?

release 3.7.0-homebrew

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

-

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

-

###  Have you found anything relevant by searching the web?

Only one mentioning here: https://spectrum.chat/gauge/general/error-message~b41ff6ed-e7af-45a6-ba2f-ee9a6d89f262

### Any other information, logs, or outputs that you want to share?

```
Exception in thread "main" java.lang.NoSuchMethodError: 'io.grpc.Deadline$Ticker io.grpc.Deadline.getSystemTicker()'
	at io.grpc.internal.ServerImplBuilder.<init>(ServerImplBuilder.java:85)
	at io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder.<init>(NettyServerBuilder.java:176)
	at io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder.forAddress(NettyServerBuilder.java:148)
	at io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder.forPort(NettyServerBuilder.java:126)
	
	the rest are my classes leading to server.start();
```

**Comment by jin** [comment]
This is probably an issue with the Maven 3rd party dependency resolver. Please file an issue in the dependency resolver project instead.
