### ISSUE TITLE
objc_library does not use the right C++ dialect when compiling .mm files

### ISSUE THREAD

**Issue by camillol** [bazelbuild/bazel#12716]
### Description of the problem / feature request:

Let's say you have a project that uses C++ and Objective-C[++], and you want to use C++17. You [pass](https://github.com/google/mediapipe/blob/39309bedba255aee2a4f31b29b65609857698ada/.bazelrc#L25) `--cxxopt=-std=c++17` when building. But your project depends on Abseil, and you start getting link errors where Objective-C++ .o files depend on missing symbols such as `absl::string_view` (which doesn't exist under C++17, since it just becomes an alias for `std::string_view`).

It turns out that `objc_library` is trying to build `.mm` files using `std=gnu++11`, even though you have requested a different C++ dialect. Using different C++ dialects for different files [breaks Abseil](https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#how-to-i-set-the-c-dialect-used-to-build-abseil) (and probably other things).

### Feature requests: what underlying problem are you trying to solve with this feature?

I want to set the C++ dialect uniformly for the entire build, e.g. by putting `--cxxopt=-std=c++17` in by `.bazelrc`, and I want it to apply to Objective-C++ code too.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

A cc_binary depending on an objc_library containing an `.mm` file that uses `absl::string_view`; build with `--cxxopt=-std=c++17`.

### What operating system are you running Bazel on?

macOS, targeting iOS.

### What's the output of `bazel info release`?

release 3.7.1

### Any other information, logs, or outputs that you want to share?

- The first workaround one would try is to globally set the C++ dialect for Objective-C++ separately from that for plain C++.
  However, there is no command line argument to set options for Objective-C++ only (i.e. no `--objcxxopt`).
  Using `--objccopt` does not work either, because it tries passing the C++ options to play Objective-C files too, which fails.

- So we have to fall back on a much more cumbersome workaround, which is to set the option separately for each `objc_library` rule. But this is also not enough, because we run into the same problem with rule arguments as we do with command line options: no way of specifying separate options for `.m` and `.mm`. If there are targets containing both, we have to split them into separate targets.

  This works, but it's a pain. In MediaPipe's case, it also needs to include a [patch](https://github.com/google/mediapipe/blob/2b58cceec9953f0d97059934f0de85dd60adbe9b/third_party/org_tensorflow_objc_cxx17.diff) for its TensorFlow dependency.

- The third possible workaround would be to replace objc_library with cc_library using `copts = ["-x objective-c++", "-fobjc-arc"]`, but that requires renaming `.mm` files to `.cc` IIRC.

### Related bugs

Issue #2268 is about the inability to supply a separate `copts` for Objective-C++ files only. Issue #5318 is a duplicate of it, with more activity. I am filing this as a separate issue because my goal is different (setting the C++ dialect globally); those issues just complicate the workaround.

**Comment by camillol** [comment]
It looks like there's a better [workaround](https://github.com/bazelbuild/bazel/issues/5318#issuecomment-765689061), which is to use `--per_file_copt=.*\.mm\$@-std=c++17` globally.

**Comment by kkpattern** [comment]
We also encounter this problem. A `--objcxxopt` would be really helpful.

Thanks @camillol for the nice workaround.

**Comment by brentleyjones** [comment]
Not stale.

**Comment by jiawen** [comment]
Not stale.

While there's a workaround, it's not particularly satisfying.

**Comment by keith** [comment]
here's a pass at this #issuecomment-2390377559
