### ISSUE TITLE
Build event protocol reports incorrect firstStartTimeMillis and lastStopTimeMillis when test is scheduled

### ISSUE THREAD

**Issue by MikhailTymchukFT** [bazelbuild/bazel#12725]
### Description of the problem:

When test target is scheduled, build event protocol reports incorrect times of start and finish of the test.
Reported time is measured from the queueing time, not an actual execution of a test.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. `git clone https://github.com/MikhailTymchukFT/bazel-bep-test.git`
2. `bazel test //... --build_event_json_file=/tmp/bep.json --profile=/tmp/profile.gz`
3. Open `/tmp/profile.gz` and locate the test which runs last (or almost last):
<img width="1257" alt="Screenshot 2020-12-17 at 23 20 52" src="https://user-images.githubusercontent.com/62020066/102539319-930d0500-40be-11eb-9f5b-59137c061226.png">

It's `Test8`  in the example above.
4. Open `/tmp/bep.json` and locate `testSummary` for `//:Test8`:

```json
"testSummary": {
        "totalRunCount": 1,
        "passed": [{
            "uri": "file:///private/var/tmp/_bazel_mikhailtymchuk/258c69cbc0006b1e65a9792ecf89ec89/execroot/java/bazel-out/darwin-fastbuild/testlogs/Test8/test.log"
        }],
        "overallStatus": "PASSED",
        "firstStartTimeMillis": "1608233688583",
        "lastStopTimeMillis": "1608233718928",
        "totalRunDurationMillis": "30345",
        "runCount": 1
    }
```

5. Convert `firstStartTimeMillis` and `lastStopTimeMillis` to date representation. I use browser's console for that:
```
> new Date(1608233688583)
Thu Dec 17 2020 22:34:48 GMT+0300 (Moscow Standard Time)

> new Date(1608233718928)
Thu Dec 17 2020 22:35:18 GMT+0300 (Moscow Standard Time)
```

6. Open `bazel-testlogs/Test8/test.log` and locate `Test started:` and `Test finished:` times:
```
.[1] Test started: 2020-12-17T19:38:52.329Z
[1] Test finished: 2020-12-17T19:39:22.331Z
```

These are real test times (with timezone correction).
To make sure these log times are correct, do the same for the first executed test. Times will match.

### What operating system are you running Bazel on?

MacOS 10.15.7

### What's the output of `bazel info release`?

release 3.7.2

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

Sample [profile.gz](https://github.com/bazelbuild/bazel/files/5711906/profile.gz)
Sample [bep.json.zip](https://github.com/bazelbuild/bazel/files/5711915/bep.json.zip)

**Comment by meisterT** [comment]
Note that the repro (thanks for creating it) has a `.bazelrc` which I didn't see at first and which is the reason that the builds/tests are running sequentially.

@michaeledgar might have more info whether it's intentional that the BEP covers the time from when the test was scheduled, not executed.

**Comment by michaeledgar** [comment]
I've confirmed the behavior you're seeing:

- We select the start time before scheduling the action for the test.
 - When execution happens remotely, "scheduling" may include uploading missing inputs and waiting for remote execution resources to become available.
 - When running with local sandboxing and scheduling using resource limits (`--local_ram_resources`, `--local_cpu_resources`), we select the start time before acquiring local resources.

- The end time is computed and does not correspond to a real instant measured from a clock.
 - When tests are run locally, we measure the execution wall-time and preserve this as the test "duration".
 - Only local test execution has this wall-time - in all other cases, the test duration is determined by taking the time when the test action is complete and subtracting the pre-scheduling start time.

It is tempting to simply change the start time measurement to be after acquiring local execution resources. The code changes wouldn't be terribly difficult, but it would be adding a semantic difference in the BEP compared to other execution strategies, which also "start" before they're ready to begin executing.

The most straightforward change I see that would eliminate the behavior differences across execution strategies would be to toss out the wall-time from BEP during local execution. In the tracing screenshot you shared, this would lead `//:Test8` to report a `lastStopTimeMillis` ~170s after `firstStartTimeMillis` and a `totalRunDurationMillis` of ~170000. The difference is just including the resource scheduling time. With a bit of elbow grease I could preserve the 30s execution time in the `totalRunDurationMillis` field, but note that this combines all test action executions (with `--runs_per_test=10` it would be 300s).

**Comment by michaeledgar** [comment]
The work being done for [issue #19471](https://github.com/bazelbuild/bazel/issues/19471) suggests an implementation strategy here: add a `repeated google.protobuf.Any strategy_details` field that picks up the action execution's `strategy_details`.
