### ISSUE TITLE
Starlark: provide a way to probe builtins availability

### ISSUE THREAD

**Issue by divanorama** [bazelbuild/bazel#12735]
### Description of the problem / feature request:

It seems that it's not possible to test whether some builtin is available or not from within Starlark
- no hasglobal/getglobal/globals (https://github.com/bazelbuild/bazel/issues/7428#issuecomment-465534716)
- can't check if <insert_module_name> is None
- can get bazel version, but can't get flags to interpret it, also can't do conditional load to avoid "name <builtin_module_name> is not defined"

### Feature requests: what underlying problem are you trying to solve with this feature?

It is nice to have new built-in modules, like json (https://github.com/bazelbuild/bazel/issues/3732), but it's hard to use them in Starlark libraries and/or repo rules in a way compatible with older bazel versions.

### Example
some.bzl
```
load("@bazel_skylib//:lib.bzl", "versions")
load("//third_party/bazel_json/lib:json_parser.bzl", "json_parse")
def foo(s):
  if versions.is_at_least("4.0.0", versions.get()):
    return json.decode(s)
  return json_parse(s)
```
That would almost work if there was a way to not fail if "json" isn't a global name. Ideally though 2nd load() should also be conditional (maybe on workspace level somehow?).

**Comment by divanorama** [comment]
Maybe it's a candidate for skylib:
- add a repository rule that knows builtins based on bazel version
- it re-exports them if they exist in current version
- if they don't exist, export stubs like: "def f(): fail()", "x = None"
- exports list of builtin names for given bazel version to allow for fallbacks on caller side
- additionally may add json_compat layer that'd add bazel_json repository and re-export its methods instead of "def f(): fail()" ones

**Comment by aiuto** [comment]
We've talked about this a lot. It almost seems useful, but you soon want to do something different enough so that you hit the wall you hinted at about conditional load. One of the things we are thinking of is that rule sets versions should be explicitly tied to bazel versions. Depending on bazel version we swap the entire WORKSPACE to get a compatible suite.  Of course, home grown rules would also have to be versioned, which could be a burden for monorepos.

**Comment by brandjon** [comment]
See also related issues #8305 and #10907.

**Comment by fmeum** [comment]
https://github.com/bazelbuild/bazel/issues/12735#issuecomment-748408219 now has an official implementation at https://github.com/bazel-contrib/bazel_features.
