### ISSUE TITLE
build broken at HEAD with FullyQualifiedName.java:131: error: no suitable method found

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/bazel#1274]
Appears to be from commit 0ad5fe69c0111276b19980440ddee360356cb4c3

OSX 10.11.5 Java 1.8.0_74

ERROR: .../bazel/src/tools/android/java/com/google/devtools/build/android/BUILD:52:1: Java compilation in rule '//src/tools/android/java/com/google/devtools/build/android:android_builder_lib' failed: Worker process sent response with exit code: 1.
src/tools/android/java/com/google/devtools/build/android/FullyQualifiedName.java:131: error: no suitable method found for from(ResourceQualifier[])
          .append(FluentIterable.from(config.getQualifiers()).transform(QUALIFIER_TO_STRING))
                                ^
    method FluentIterable.<E#1>from(Iterable<E#1>) is not applicable
      (cannot infer type-variable(s) E#1
        (argument mismatch; ResourceQualifier[] cannot be converted to Iterable<E#1>))
    method FluentIterable.<E#2>from(FluentIterable<E#2>) is not applicable
      (cannot infer type-variable(s) E#2
        (argument mismatch; ResourceQualifier[] cannot be converted to FluentIterable<E#2>))
  where E#1,E#2 are type-variables:
    E#1 extends Object declared in method <E#1>from(Iterable<E#1>)
    E#2 extends Object declared in method <E#2>from(FluentIterable<E#2>)

**Comment by Sabrewarrior** [comment]
Same error on Windows msys2, Java 1.8.0_91. Build succeeded on [https://github.com/bazelbuild/bazel/commit/5d7ac1a2d88a662a5196d1e485d91d807ee3360d](https://github.com/bazelbuild/bazel/commit/5d7ac1a2d88a662a5196d1e485d91d807ee3360d).

**Comment by kchodorow** [comment]
Fixed by 67116c7443c93b71e522cee36c72fc4af358358d.
