### ISSUE TITLE
Require option to disable annotation processing for `java_common.compile()`

### ISSUE THREAD

**Issue by jongerrish** [bazelbuild/bazel#12754]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

In [bazelbuild/rules_kotlin](https://github.com/bazelbuild/rules_kotlin), annotation processors are run first using `KAPT`. `java_common.compile()` is then used to build any source generated via annotation processors with `KAPT` along with any project Java source. Since annotation processing has already happened we don't want annotation processing to occur in JavaBuilder / Turbine so we do not pass in any `plugins` argument in order to skip annotation processing.

However presence or absence of annotation processors as specified with the `plugins` argument also determines whether `Turbine` makes use of the the direct dependencies optimization described here: https://github.com/bazelbuild/bazel/blob/009ce7b1d296e8f6b6e3d68189e6f26b47636663/src/main/java/com/google/devtools/build/lib/rules/java/JavaHeaderCompileActionBuilder.java#L274

The problem is that if `java_common.compile()` is building source already generated by annotation processors externally (i.e: via KAPT and passed in via the `source_jars` parameter) then header compilation can fail because the annotation processor generated code _can_ refer to symbols defined in transitive dependencies of the target.

### Feature requests: what underlying problem are you trying to solve with this feature?

Decouple Turbines direct dependencies optimization from the running of annotation processors.

Either:

1. Callers should pass in a non-empty `plugins` argument even in the case of the Kotlin rules where annotation processors have run externally using KAPT. This still controls whether the `useDirectClasspath` optimization can be employed but in the case of a non-empty `plugins` argument add an option to disable annotation processing both for Javac and Turbine, e.g: 

```
java_common.compile(
    source_jars = kapt_generated_source_jar,
    plugins = plugins,
    skip_annotation_processing = True)
```

2. Ask callers to pass in an empty `plugins` argument to skip annotation processing but provide some way to also disable the `useDirectClasspath` optimization 
```
java_common.compile(
    source_jars = kapt_generated_source_jar,
    plugins = [],
    use_turbine_direct_jars_optimization = False)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Call `java_common.compile()` with a non-empty `plugins` argument, note that annotation processing always occurs even when `javac_opts = ["-proc:none"]` is specified.

Call `java_common.compile()` with an empty `plugins` argument, note `useDirectClasspath` optimization code path is followed. If a source jar of annotation processor generated code is passed in to `source_jars` that contains references from transitive dependencies header compilation will fail due to missing symbols.

### What operating system are you running Bazel on?

OSX

### What's the output of `bazel info release`?

development version

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Our custom fork based on Bazel 3.4.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git@github.sc-corp.net:Snapchat/bazel.git
366b1d16a0f80a7d27830ad09ce1fb0d80fa838b
366b1d16a0f80a7d27830ad09ce1fb0d80fa838b

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

No

**Comment by jongerrish** [comment]
@cushon @kevin1e100 - thoughts? I'm happy to submit a PR for this.

**Comment by cushon** [comment]
> Call `java_common.compile()` with a non-empty plugins argument, note that annotation processing always occurs even when `javac_opts = ["-proc:none"]` is specified.

`javac_opts = ["-proc:none"]` should disable annotation processing in `java_common.compile()`, and it works for me in this example: https://gist.github.com/cushon/4359aab8eb6e39dffd7e1afbed428c08

**Comment by jongerrish** [comment]
Ah, got it. I think the thing that threw me off there was the progress message includes the string `and running annotation processors (..., ...)` even when `javac_opts = ["-proc:none"]` is specified. Would you be open to a PR making that progress message conditional on `javac_opts = ["-proc:none"]`?

Finally, is there any value in using the direct header compilation action in these cases albeit with a full or reduced (i.e: not `directJars`) classpath for these cases?

**Comment by comius** [comment]
@jongerrish can the issue be closed?

**Comment by jongerrish** [comment]
@comius - what you think about making the progress message a little clearer when annotation processors are disabled?

**Comment by cushon** [comment]
All else being equal I agree it would be nice to omit that part of the progress message when annotation processing is disabled, but it would also mean we'd have to do more parsing of javac options in bazel, which isn't ideal. (Doing a `contains("-proc:none")` gets us most of the way there, but that only works if you don't have multiple `-proc:` flags, etc.)

That'd be an argument to have `skip_annotation_processing`, because then bazel would have a principled way of knowing whether or not annotation processing was enabled, but that seems kind of heavy-weight for a slightly better progress message.

**Comment by kevin1e100** [comment]
skip_annotation_processing would also allow knowing that no annotation
processors are needed for header compilation, among other things.  So
seemingly, a flag like that might also offer opportunities for streamlining
builds, besides a better error message.

**Comment by cushon** [comment]
50cfd4596ead2d3e3827d9d87146baa61f7246c3

**Comment by cushon** [comment]
This has been implemented as `java_common.compile(..., enable_annotation_processing = False)`
