### ISSUE TITLE
The `*-offline.jar` files generated and used by Bazel coverage need to include directories as well as files.

### ISSUE THREAD

**Issue by deanwampler** [bazelbuild/bazel#12762]
### Description of the problem / feature request:

Using this command,

```
$ bazel coverage --extra_toolchains=@io_bazel_rules_scala//scala:code_coverage_toolchain --combined_report=lcov --coverage_report_generator=@bazel_tools//tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator:Main --test_filter='*MyFunkyTest*' //myproject:unit-tests
```

(FYI, this is a Scala project.)

A `null` is returned when `MyFunkyTest` tries to fetch a _directory_ resource, say `/testdata`, `getClass.getResource("/testdata")`. The test finds the directory resource when `bazel test --test_filter='*MyFunkyTest*' //myproject:unit-tests` is run.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In fact, the transformed jar file, `unit-tests-offline.jar` does _not_ contain the directories, only the files, whereas the original `unit-tests.jar` contained the directories and files. Hence, `getClass.getResource("/testdata")` returns `null` when the "offline" jar is used. This behavior isn't unique to Bazel; it would happen with any jar without directories in the table of contents (`jar t` output).

I'm not sure how the new jar file is generated, but if the equivalent of the following is used, it will work, as I demonstrated for myself:

```
$ find . > all.lst
$ jar cf unit-tests-offline.jar @all.lst
```

Currently it behaves like the first shell command is `find . -type f > files.lst`.

### What operating system are you running Bazel on?

MacOS Catalina, 10.15.7

### What's the output of `bazel info release`?

Starting local Bazel server and connecting to it...
INFO: Invocation ID: 108a8592-2b69-459f-bc1d-6982b1062124
release 3.7.2

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

My code is in a private repo.

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

None.

**Comment by comius** [comment]
@deanwampler Could you provide a repo with minimal reproduction? A test that needs resources? Does it happen using only Java or is this truely a scala issue?

**Comment by deanwampler-domino** [comment]
I apparently wasn't subscribed to updates, so apologies for the late reply. I just attempted to create a reproducing, simplified example, but both Java and Scala examples worked as expected. I'm still using Bazel 3.7.2. Hence, I'm not sure why it failed before and this item can be closed.

**Comment by deanwampler** [comment]
Now signed in with the correct account...

**Comment by BillyAutrey** [comment]
@deanwampler For what it's worth, I ran into this exact issue and was able to create a reproducer.  This should now be fixed in the latest `rules_scala`.

**Comment by ddl-deanwampler** [comment]
That's great to hear!
