### ISSUE TITLE
[documentation] Tutorials for Go language/project

### ISSUE THREAD

**Issue by ionutnechita** [bazelbuild/bazel#12766]
Hi Bazel Team,

I noticed on your documentation page, 4 languages with related tutorials. ( C++, Java, Android and iOS ).
https://docs.bazel.build/versions/3.7.0/bazel-overview.html#tutorials

Would it be possible to create an example in Go language?

It would be a starting point for those with projects in Go.

I intend to use the bazel for a new project in the future.

Thanks.

**Comment by communikit** [comment]
Since this also asking for a Go tutorial, closing as dupe of #3396
