### ISSUE TITLE
.ipp files are not allowed in hdrs of cc_inc_library rule

### ISSUE THREAD

**Issue by chenkan1994** [bazelbuild/bazel#1276]
Boost library uses *.ipp to represent implementation of header file, but it is not allowed in hdrs attribute of cc_inc_library.
But seems allowed in hdrs of cc_library, which is weird.

**Comment by chenkan1994** [comment]
@damienmg Hello? Do you have any suggestions?

**Comment by damienmg** [comment]
We should just fix it, I don't think this is meant to be different.

**Comment by chenkan1994** [comment]
OK. Thanks!

**Comment by ulfjack** [comment]
I'm not sure we'll get to this soon, but I'd be happy to review a pull request.

**Comment by WillEwing** [comment]
Neither are files with no extension.  The Guideline Support Library ( https://github.com/Microsoft/GSL ), for example uses <gsl/gsl> for their main header.

**Comment by mhlopko** [comment]
Ipp files are supported since c43cabff4046bf5805ffbf1c5fa6f286e67b9227. I'm not sure we want to allow files without extension though. Can you create a separate issue for that so we can discuss alternative options please?
