### ISSUE TITLE
Provide a way to create a toolchain from an autodetected one

### ISSUE THREAD

**Issue by limdor** [bazelbuild/bazel#12767]
### Description of the problem / feature request:

Bazel has two ways to deal with toolchains, one is to use toolchains provided by the user, and the other one is to automatically provide toolchains depending on the tools that are installed in the computer where Bazel is executed.
The auto-detected toolchains are very useful for anyone starting with Bazel but soon people start running into the challenge of wanting to change some settings of the default toolchain (i.e: compiler flags).

The way to do it, is to create a toolchain like the auto-detected one (you can figure out the one used with `--toolchain_resolution_debug`) and change the desired flag, but this can be very tedious. Some of the auto-detected toolchains are more than 1.000 lines long and with autodetected paths of the tools to be used.

### Feature requests: what underlying problem are you trying to solve with this feature?

In the same way that there is `--toolchain_resolution_debug` to know what toolchain is selected, provide an option to print all the information of the selected toolchain that would be needed to create it manually.
https://docs.bazel.build/versions/master/be/platform.html#toolchain

Some of the information that should contain:

- Absolut path of the compiler/linker from the host being used
- Compiler flags being used
- Anything else that would be needed in order to create a toolchain following https://docs.bazel.build/versions/master/tutorial/cc-toolchain-config.html if you want to recreate the automatically detected one.

### What's the output of `bazel info release`?

4.0.0rc7

###  Have you found anything relevant by searching the web?

Some links showing why this might be relevant:
https://github.com/bazelbuild/bazel/issues/12737
https://github.com/bazelbuild/bazel/issues/2209
https://stackoverflow.com/questions/63204551/how-to-tell-bazel-which-compiler-to-use-without-configuring-a-new-toolchain
https://stackoverflow.com/questions/59092579/bazel-add-compile-flags-to-default-c-toolchain
https://stackoverflow.com/questions/63264512/bazel-windows-10-toolchain-configuration-with-mingw64-compiler

**Comment by katre** [comment]
There is, unfortunately, no generic toolchain-discovery system. The CC, Java, Python, etc, all deal with this separately. You'll need to file this issue against the specific rules whose auto-discovered toolchain you want to specialize. It looks like CC rules from your description, so I'll start by re-assigning this to the language owners.
