### ISSUE TITLE
Support for ARM64 Linux

### ISSUE THREAD

**Issue by jeraldliu** [bazelbuild/bazel#12776]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

It seems there is [support for building C++ binaries on ARM64+Windows](https://github.com/bazelbuild/bazel/commit/1f77972536c69c27ce3076de9f634e1a02a14a5e#diff-89a237784c63ef1b97979702430787d86126537d6d0c50347c5101f74bd00b31). Are there plans to support ARM64+Linux?

### Feature requests: what underlying problem are you trying to solve with this feature?

I am using bazel to build multi-arch images, using --platform as input, namely cpu:arm64+os:linux. But, it seems that there does not exist a toolchain that supports that cpu/os combination.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a rule that depends on `@bazel_tools//tools/cpp:toolchain_type` and define a platform to use as input to `bazel build <target> --platforms=<platform>`: e.g,

```
# Defines an arm platform
platform(
    name = "arm64_linux",
    constraint_values = [
       "@platforms//cpu:arm64",
       "@platforms//os:linux",
    ],
)
```

### What operating system are you running Bazel on?

OSX 10.15.6

### What's the output of `bazel info release`?

release 3.3.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

NA

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

NA (get an error)

###  Have you found anything relevant by searching the web?

NA

### Any other information, logs, or outputs that you want to share?

```
ERROR: While resolving toolchains for target //third_party/server/private_jvm/scala_2_12/io/sentry:sentry_logback: No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type. Maybe --incompatible_use_cc_configure_from_rules_cc has been flipped and there is no default C++ toolchain added in the WORKSPACE file? See https://github.com/bazelbuild/bazel/issues/10134 for details and migration instructions.
```

**Comment by meteorcloudy** [comment]
/cc @philwo Since Bazel already runs natively on arm64 Linux, I assume it can already build arm64 Linux binaries? 
However, if we want to do cross-compiling from x86 to arm64, we do need more toolchain support.

**Comment by philwo** [comment]
@meteorcloudy Yes, that's my understanding as well! :)

**Comment by jeraldliu** [comment]
@meteorcloudy Yes, cross-compiling from x86 to arm64 for CPP binaries is what I was alluding to. Is there any plan to do so?

**Comment by meteorcloudy** [comment]
@jeraldliu Hi Jerald, I don't think adding native support for that is on the current priority list of the C++ rules team.
But Bazel is extensible, you can always set up your own C++ toolchain for cross-compiling, see https://docs.bazel.build/versions/master/tutorial/cc-toolchain-config.html
