### ISSUE TITLE
Incorrect test_wrapper path on Windows

### ISSUE THREAD

**Issue by moroten** [bazelbuild/bazel#12785]
### Description of the problem:

Bazel tries to use `external/bazel_tools/tools/test/tw` under Windows, which fails as the `.exe` is needed.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
touch foo_test.sh
cat > BUILD.bazel <<EOF
sh_test(
    name = "foo_test",
    srcs = ["foo_test.sh"],
)
EOF

bazel test //:foo_test
INFO: Analyzed target //:foo_test (0 packages loaded, 2 targets configured).
INFO: Found 1 test target...
ERROR: C:/git/.../BUILD.bazel:1:8: Testing //:foo_test failed: missing input file 'external/bazel_tools/tools/test/tw', owner: '@bazel_tools//tools/test:tw'
Target //:foo_test up-to-date:
  bazel-bin/foo_test
  bazel-bin/foo_test.exe
ERROR: C:/git/visioncore/BUILD.bazel:30:8 Testing //:foo_test failed: 2 input file(s) do not exist
INFO: Elapsed time: 1.302s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
FAILED: Build did NOT complete successfully
```

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

Patched build based on 4.0.0rc6 + [a87d7ed](https://github.com/bazelbuild/bazel/commit/a87d7ed2411d5382bac58a20b79e09c464ad13b9).

###  Have you found anything relevant by searching the web?

Could not find any relevant GitHub issues mentioning `test_wrapper`, `tw` or `tw.exe`.

### Any other information, logs, or outputs that you want to share?

I don't know if my `.bazelrc` is involved in the problem. If you think so, I can dig deeper into that.

**Comment by moroten** [comment]
@philwo This feels like a release blocker for 4.0.0.

**Comment by meteorcloudy** [comment]
Thanks for reporting this, I'm taking a look now!

**Comment by meteorcloudy** [comment]
I cannot reproduce this issue with Bazel built at 4.0.0rc6 + a87d7ed, it indeed looks like you have some wrong setup in .bazelrc file. Can you build with `--announce_rc` and show me the output?

And we do select `tw.exe` on Windows and `tw` on other platform, my guess is that you set `--cpu` to some other value?
https://github.com/bazelbuild/bazel/blob/3b2d3100e4f70c3cfdd79ac074a26f660e24d969/tools/test/BUILD.tools#L53-L54

**Comment by moroten** [comment]
We have defined custom platforms and have migrated away from `--cpu`. By adding `@platforms//os:windows` as a constraint value to our platform definition, it works again. Before 4.0, we did not have to use any `@platforms//...` label at all.

Sorry for late reply, I missed the notification.
