### ISSUE TITLE
Unpredictable generation of static libraries

### ISSUE THREAD

**Issue by jonpsy** [bazelbuild/bazel#12798]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

I'm building tensorlfow-lite version 2.3.0 and building its XNNPACK delegate. I've noticed that the static libraries of the external dependencies fail to generate at the ```bazel-bin/external/XNNPACK``` folder sometimes? This seems to occur randomly(or so my experience suggests) and it's really bad. How do I get the static libraries of the external dependencies inside the ```bazel-bin``` folder?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
```bash
git clone https://github.com/tensorflow/tensorflow.git
git chekcout v2.3.0
bazel build -c opt --config=android_arm64 //tensorflow/lite:libtensorflowlite.so
bazel build --copt="-fpic" -c opt --config android_arm64 tensorflow/lite/delegates/xnnpack:xnnpack_delegate
```
The ```bazel-bin/external/delegates/XNNPACK/``` folder sometimes contain the ````libxnnpack_f32.a``` , and sometimes it doesn't.

### What operating system are you running Bazel on?
Ubuntu 20.04 LTS

### What's the output of `bazel info release`?

for  ```bazel build --copt="-fpic" -c opt --config android_arm64 tensorflow/lite/delegates/xnnpack:xnnpack_delegate``` https://pastebin.com/hHz7N48v

for ```bazel build -c opt --config=android_arm64 //tensorflow/lite:libtensorflowlite.so
https://pastebin.com/Ksjfm04q

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by aiuto** [comment]
This looks WAI from the outputs you pasted.  You get with the .so or bazel-bin/tensorflow/lite/delegates/xnnpack/libxnnpack_delegate.a

If you want bazel-bin/**external**/delegates/XNNPACK/... then you probably have to build  @whatever://XNNPACK/...,  where whatever is the repo name tensorflow uses to pull in the dependencies.

**Comment by jonpsy** [comment]
Thanks, that helped!

I have two questions
1) Previously I needn't do all these steps, and tensorflow would automatically compile & store the external libraries in static form inside the ```bazel-bin/external``` folder. Why so?
2) XNNPACK itself has some dependencies, how can I make bazel to compile & store all external dependencies in static form inside bazel-bin/external folder?

Have a nice day!

**Comment by aiuto** [comment]
You could do a blaze query deps(whatever you are building) to find the external targets.
Then you could explictly build them.
But this is theoretical. I don't know the tensorflow build setup. Some libraries may only be shared, rather than static. This is a question for their project.

**Comment by jonpsy** [comment]
The original problem was solved. I had to use "bazel ...../delegates/xnnpack:all". 

Off record, can bazel recursively compile all dependencies and store them?
