### ISSUE TITLE
can't find the header file

### ISSUE THREAD

**Issue by davidxiaozhi** [bazelbuild/bazel#12794]
n one of my c++ projects, the directory structure atom:hello_atom relies on neuropod under third_parts, and neuropod is the built dynamic library and header file

The build configuration in third_parts is as follows
`
cc_library(
    name = "neuropod",
    srcs = glob(
        [
            "libneuropod.so",
        ],
        exclude = [
        ],
    ),
    hdrs = glob([
        "neuropod/neuropod.hh",
    ]),
    copts = ["-Ithird_parts/neuropod/include/","-Lthird_parts/neuropod/lib/"],
    #linkopts = ["-pthread"],
    visibility = ["//visibility:public"],
)
`
The build file under atom is as follows

`
cc_binary(
    name = "hello_atom",
    srcs = ["hello_atom.cc"],
    #hdrs = ["sandwich.h"],#头文件和源文件都可以使用正则匹配例如glob(["*.h"])
    # linkopts = select({
    #     "@bazel_tools//src/conditions:darwin": ["-Wl,-rpath,@loader_path"],
    #     "//conditions:default": ["-Wl,-rpath,$$ORIGIN"],
    # }),
    # linkshared = True,
    # linkstatic = True,
    visibility = [
        "//visibility:public",
    ],
    deps = [
        #"@gtest//:main",
        #"@absl//absl/strings",
        #"@folly//:main",
        #"//third_parts:neuropod"
        "//third_parts:neuropod"
        ],
    #includes = ["third_parts/neuropod/include/"],
    copts = ["-Ithird_partsss/neuropod/include/"],
)`
run command
bazel clean;bazel  run   //atom:hello_atom 
![image](https://user-images.githubusercontent.com/6194818/104083063-5b851900-5276-11eb-8223-19fb7f3dda37.png)

But the file under third_parts does exist
![image](https://user-images.githubusercontent.com/6194818/104083080-85d6d680-5276-11eb-9d18-d78693b0a207.png)
I tried various configurations in hello_atom, but I couldn't find the source file at run time

**Comment by aiuto** [comment]
This sounds like general help needed. If it is that, try asking on StackOverflow. If you have an actual bug, please provide enough information to reproduce it.

**Comment by jin** [comment]
Closing, please reach out to the Bazel mailing list, StackOverflow or Slack.
