### ISSUE TITLE
WindowsSubprocess does not implement available() on its outputstream

### ISSUE THREAD

**Issue by larsrc-google** [bazelbuild/bazel#12791]
### Description of the problem / feature request:

In `src/main/java/com/google/devtools/build/lib/windows/WindowsSubprocess.java`, stdout is exposes as an InputStream, but the implementation in `src/main/native/windows/processes-jni.cc` does not implement the available() function. 

### Feature requests: what underlying problem are you trying to solve with this feature?

I need to be able to check non-blocking for input on a pipe from a subprocess for the WorkerMultiplexer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Compile Bazel with https://bazel-review.googlesource.com/c/bazel/+/148651 and try to compile anything on Windows that involves multiplex workers.

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

"development version"

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

As mentioned above.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

The [PeekNamedPipe](https://docs.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-peeknamedpipe) function can be told to not read anything, but return the number of bytes available to read.

### Any other information, logs, or outputs that you want to share?

Buildkite failure example: https://buildkite.com/bazel/google-bazel-presubmit/builds/42603

**Comment by meteorcloudy** [comment]
@mai93 Can you help with this issue?
Basically, what we need is to override the `available()` method here:
https://github.com/bazelbuild/bazel/blob/d69744dca68f8258762d53a01d8dca3afb7ed2ac/src/main/java/com/google/devtools/build/lib/windows/WindowsSubprocess.java#L65
with some corresponding implementation in our JNI code on Windows: [process-jni.cc](https://github.com/bazelbuild/bazel/blob/master/src/main/native/windows/processes-jni.cc)

**Comment by meteorcloudy** [comment]
@larsrc-google I believe this is already fixed, right?

**Comment by meteorcloudy** [comment]
Fixed at https://cs.opensource.google/bazel/bazel/+/082d98772690946ed29c157e60640c97a6e1195b

**Comment by larsrc-google** [comment]
Yes, that is correct. Thanks for closing.
