### ISSUE TITLE
error occured when running 'hello world' :  parameter 'remotable' is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_repo_remote_exec

### ISSUE THREAD

**Issue by whogodemo** [bazelbuild/bazel#12799]
### Description of the problem / feature request:

> I'm using ubuntu 18.04/openCV 3.4.0/bazel 3.4.0. I already asked another error before,and then it solved. But now, a new problem occured.... 
when I running this following command :
`bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world`

then the following error occured .

ERROR: /home/money/.cache/bazel/_bazel_money/f8fa67832b324a524cf2546304b89b98/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:1409:40: in call to repository_rule(), parameter 'remotable' is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_repo_remote_exec
ERROR: in /home/money/.cache/bazel/_bazel_money/f8fa67832b324a524cf2546304b89b98/external/org_tensorflow/tensorflow/workspace.bzl: Extension file 'third_party/gpus/cuda_configure.bzl' has errors
INFO: Elapsed time: 0.632s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
    Fetching @io_bazel_rules_closure; fetching

### Feature requests: what underlying problem are you trying to solve with this feature?

> I am testing to print 'hello world' using bazel .. and then I will use mediapipe.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> `cd mediapipe`
and then
`bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world`

### What operating system are you running Bazel on?

> ubuntu 18.04

### What's the output of `bazel info release`?

> release 3.4.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> https://github.com/google/mediapipe.git
f15da632dec186f2c1d3c780f47086477e2286a9
f15da632dec186f2c1d3c780f47086477e2286a9

###  Have you found anything relevant by searching the web?

> I found similar error, but I cannot find exactly same error..
>
> Places to look:
> - StackOverflow: https://stackoverflow.com/questions/61414272/building-tensorflow-from-source-cpu-noavx-errors
> - GitHub issues: https://github.com/bazelbuild/intellij/issues/976
> - https://docs.bazel.build/versions/master/skylark/lib/globals.html

### Any other information, logs, or outputs that you want to share?

> 
money@moneymany:~$ cd mediapipe
money@moneymany:~/mediapipe$ bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world
ERROR: /home/money/.cache/bazel/_bazel_money/f8fa67832b324a524cf2546304b89b98/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:1409:40: in call to repository_rule(), parameter 'remotable' is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_repo_remote_exec
ERROR: in /home/money/.cache/bazel/_bazel_money/f8fa67832b324a524cf2546304b89b98/external/org_tensorflow/tensorflow/workspace.bzl: Extension file 'third_party/gpus/cuda_configure.bzl' has errors
INFO: Elapsed time: 0.097s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by whogodemo** [comment]
[cuda_configure.txt](https://github.com/bazelbuild/bazel/files/5792728/cuda_configure.txt)

and this is my cuda_configure.bzl file.

**Comment by aiuto** [comment]
You should ask this in a tensorflow forum.

**Comment by whogodemo** [comment]
> You should ask this in a tensorflow forum.

ok I got it. thank you

**Comment by manosh7n** [comment]
@whogodemo have you solved this problem?
