### ISSUE TITLE
4.0 breaking change: Java coverage

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#12793]
I'm not sure if there is a bug, or if this is just missing documentation (and if such documentation would be in the 4.0 release)

It seems that 4.0 introduces a breaking change for `bazel coverage` on Java targets, where the jacocorunner must now be configured in a toolchain. The default auto-discovered toolchain does not have one set, and after some digging I have not been able to create my own.

Every attempt to make a `default_java_toolchain` gives me an error like this:

```
(16:42:43) ERROR: Misconfigured toolchains: @remote_java_tools_darwin//:toolchain is declared as a toolchain but has inappropriate dependencies. Declared toolchains should be created with the 'toolchain' rule and should not have dependencies that themselves require toolchains.
.-> RegisteredToolchains
|   @remote_java_tools_darwin//:toolchain
|   @bazel_tools//tools/jdk:proguard_whitelister
|   toolchain types @bazel_tools//tools/python:toolchain_type, @bazel_tools//tools/cpp:toolchain_type
|   toolchain type @bazel_tools//tools/cpp:toolchain_type
`-- RegisteredToolchains
```

Is it expected that users need to create their own java_toolchain to keep coverage working? If so, how?

**Comment by comius** [comment]
Toolchains defined in java_tools all have jacoco set.
default_java_toolchain macro does not set it, so I will prepare a fix for it (unfortunately the code on master already diverged too much to cherry pick it)

@alexeagle could you provide more details about autoconfiguration that you're mentioning? Are you using bazel-toolchains?

Just using default_java_toolchain target I cannot reproduce the error.
From the error message it seems there is a call of register_toolchains or --extra_toolchains flag on a java_toolchain target, whereas this should be called on toolchain target.

**Comment by alexeagle** [comment]
@comius thanks for looking, my repro is pretty simple:

`.bazelrc`:
```
build --javacopt="-source 8"
build --javacopt="-target 8"
build --host_javabase=@bazel_tools//tools/jdk:remote_jdk11
build --javabase=@bazel_tools//tools/jdk:remote_jdk11
build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java11
build --java_toolchain=@bazel_tools//tools/jdk:toolchain_java11
```

`.bazelversion`:
```
4.0.0rc7
```

`WORKSPACE`:
```
workspace(name = "repro")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file", "http_jar")


http_archive(
    name = "rules_java",
    sha256 = "f3f75b52e1a70c0e2c6f8c4387feca5dbbb9f9d9cc9f64031994411291516877",
    strip_prefix = "rules_java-d43b0aa2d3b2173fcc54d3c194e89fa66cdc6e1a",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_java/archive/d43b0aa2d3b2173fcc54d3c194e89fa66cdc6e1a.tar.gz",
        "https://github.com/bazelbuild/rules_java/archive/d43b0aa2d3b2173fcc54d3c194e89fa66cdc6e1a.tar.gz",
    ],
)

load("@rules_java//java:repositories.bzl", "rules_java_dependencies", "rules_java_toolchains")

rules_java_dependencies()

rules_java_toolchains()
```

`BUILD.bazel`:
```
load("@rules_java//java:defs.bzl", "java_binary", "java_test")

java_binary(
    name = "bin",
    srcs = ["Main.java"],
    main_class = "Main",
)
```

```
% bazel coverage :all
ERROR: /Users/alex.eagle/repros/java_coverage/BUILD.bazel:3:12: in java_binary rule //:bin: jacocorunner not set in java_toolchain:@bazel_tools//tools/jdk:toolchain_java11
```

I see that if I comment out `--java_toolchain` in the .bazelrc then it's not reproducible anymore. That line was added in our repo for `java_proto_library` FWIW

**Comment by alexeagle** [comment]
AFAICT we don't need these java_toolchain override lines in the .bazelrc for this repo. I'll confirm that our upgrade is unblocked, and then I think the severity here is probably low (unless you know of a reason other Bazel users might need to select those toolchains from bazel_tools)
/cc @redisliu

**Comment by comius** [comment]
Thanks for reproduction. I'm confirming the bug as well as that the PR fixes it.

@alexeagle Do you also have reproduction for the `ERROR: Misconfigured toolchains`? I'd like to make sure there isn't another problem.
