### ISSUE TITLE
Get errors with gcc when trying to compile tensorflow 2.4.0 with gcc 6

### ISSUE THREAD

**Issue by tupq** [bazelbuild/bazel#12827]
Iam trying to compile the tensorflow 2.4.0 with gcc 6 ( version 6.3 ) and bazel 3.4.1 but it always throws below exception:

> ERROR: /root/tensorflow/tensorflow/python/BUILD:6068:24: Linking of rule '//tensorflow/python:_pywrap_tensorflow_internal.so' failed (Exit 1): gcc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc @bazel-out/host/bin/tensorflow/python/_pywrap_tensorflow_internal.so-2.params)
Execution platform: @local_execution_config_platform//:platform
/usr/bin/ld.gold: internal error in maybe_apply_stub, at ../../gold/aarch64.cc:5407
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: /root/tensorflow/tensorflow/tools/pip_package/BUILD:69:10 Linking of rule '//tensorflow/python:_pywrap_tensorflow_internal.so' failed (Exit 1): gcc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc @bazel-out/host/bin/tensorflow/python/_pywrap_tensorflow_internal.so-2.params)

here's my command:
 `bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package --jobs 8 --verbose_failures`

What operating system are you running Bazel on?
Debian GNU/Linux 9.13 (stretch)

It take me weeks to find the solution.... please help !

**Comment by jin** [comment]
Please reach out to the TensorFlow repository / mailing lists for support.
