### ISSUE TITLE
Unable to suppress many stderr outputs

### ISSUE THREAD

**Issue by ptarjan** [bazelbuild/bazel#12831]
### Description of the problem / feature request:

A simple run currently looks like:
```
$ bazel test //main-street/...
(13:12:23) INFO: Invocation ID: 3013b97f-5400-4b60-b380-1c895d415941
(13:12:23) INFO: Current date is 2021-01-13
(13:12:23) INFO: Analyzed 364 targets (0 packages loaded, 0 targets configured).
(13:12:23) INFO: Found 257 targets and 107 test targets...
(13:12:23) INFO: Elapsed time: 0.430s, Critical Path: 0.01s
(13:12:23) INFO: 1 process: 1 internal.
(13:12:23) INFO: Build completed successfully, 1 total action
(13:12:23) INFO: Build completed successfully, 1 total action
```

I'd prefer to have:
```
$ bazel test //main-street/... --no-debug-info
107 tests passed
```

Or:
```
$ bazel test //main-street/... --stop-the-noise
FAILED  //main-street/mainst/db:db_test
1 test failed. 106 tests passed.
```

If I create a PR for this, would it be accepted?

### Feature requests: what underlying problem are you trying to solve with this feature?

An option to remove many addition log lines

### What operating system are you running Bazel on?

OS X

### What's the output of `bazel info release`?

```
$ bazel info release
(10:47:45) INFO: Invocation ID: 3064f676-d831-4e12-8d61-45b542e38062
release 3.7.2
```

**Comment by erenon** [comment]
FYI https://docs.bazel.build/versions/master/command-line-reference.html#flag--ui_event_filters
Aside from the documented values, it accepts:  error, warning, info, progress, debug, start, finish, subcommand, stdout, stderr, pass, fail, timeout, cancelled or depchecker.

**Comment by ptarjan** [comment]
Thanks for pointing that out! It is pretty close to what I wanted but still somehow shows two `INFO:` lines as well as a blank link. Do you know how to remove those?

```
$ bazel test --ui_event_filters=-DEBUG,-INFO //main-street/...
INFO: Build completed successfully, 1 total action
Test cases: finished with 4223 passing and 0 failing out of 4224 test cases (some targets did not have test case information)

INFO: Build completed successfully, 1 total action
```

**Comment by ptarjan** [comment]
I also tried to create a `--config=verbose` mode so my users can turn them back on, but it doesn't seem to work. Here is my `.bazelrc` excerpt:

```
test --ui_event_filters=-DEBUG,-INFO
test:verbose --ui_event_filters=+DEBUG,+INFO
```

but this still does the same thing:
```
 $ bazel test //main-street/... --config=verbose
INFO: Build completed successfully, 1 total action
Test cases: finished with 4223 passing and 0 failing out of 4224 test cases (some targets did not have test case information)

INFO: Build completed successfully, 1 total action
```

**Comment by michajlo** [comment]
Try `--noshow_progress`? Haven't looked in a while, but I believe "progress" messages are separate from "events", though they may be prefixed with `INFO` etc as if they were events.

**Comment by ptarjan** [comment]
`--noshow_progress` does indeed supress those:
```
$ bazel test main-street/... --ui_event_filters=-DEBUG,-INFO --noshow_progress
Test cases: finished with 4223 passing and 0 failing out of 4224 test cases (some targets did not have test case information)

Executed 0 out of 108 tests: 108 tests pass.
```

but then, as the name suggests, I don't get to see the progress messages as the tests run, which are quite a nice user experience. Can I keep the progress messages but not have the two extra `INFO` lines?

**Comment by michajlo** [comment]
Not off the top of my head, you'd likely need to make a code change to classify them as different kinds of events or make them stop masquerading as `INFO` events. See also https://github.com/bazelbuild/bazel/issues/12117#issuecomment-695113868

**Comment by communikit** [comment]
Doc check-in: Looks like https://docs.bazel.build/versions/master/command-line-reference.html#flag--ui_event_filters answers a lot of questions here - can the conversation be moved to #12117 from here, instead of staying open under the Documentation label?

Is there anything missing in the documentation that needs to be updated?

**Comment by communikit** [comment]
Closing since I don't see an immediate documentation need. Please feel free to follow discussion on #12117 and reopen a documentation bug if needed.
