### ISSUE TITLE
`java_test` and `java_binary` should add `runtime_deps` to their `JavaInfo`

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#12836]
### Description of the problem / feature request:

The fact that neither `java_test` nor `java_binary` are interchangeable with `java_library` breaks the "[Principle of Least Astonishment](https://wiki.c2.com/?PrincipleOfLeastAstonishment)", leading to non-obvious failures in builds.

To identify the problem, one must find #11705 and then read the [final comment in the thread](https://github.com/bazelbuild/bazel/issues/11705#issuecomment-703513666). The reasoning seems arbitrary and precludes legitimate possibilities where one might want to depend upon a `java_binary` or `java_test`. As an example, since both of these rules compile code, it seems reasonable to want to write a unit test that verifies behaviour is correct (though, admittedly, that's a bit of a stretch for `java_test` 😃 )

More prosaically, not exporting all dependencies in a way consistent with `java_library` breaks the mental model that most people will have about how java rules work, and how the classpath works in java itself. 

### Feature requests: what underlying problem are you trying to solve with this feature?

It would be good if all `java_*` rules exported their `JavaInfo` in a consistent way. The alternative would be to limit `java_binary` and `java_test` to only accept runtime dependencies, and to not compile any code themselves. This is the approach that Buck's [java_binary](https://buck.build/rule/java_binary.html) has taken.

### What operating system are you running Bazel on?

N/A

### What's the output of `bazel info release`?

release 3.7.1

###  Have you found anything relevant by searching the web?

#11705

**Comment by comius** [comment]
What you're saying is true from the perspective of a Java user. In Java, `java_binary` and `java_library` are the same.

However, mind that Bazel supports multiple languages and there are languages where binary is different from a library. It is impossible to fit those languages into the Java model. Even if Java model is really cool.

Therefore, being able to use `java_binary` the same way as `java_library` would break the Principle of Least Astonishment. The proposed alternative to remove `src` attribute from `java_binary` has the same problem when you look from multi-lang perspective.

Note also that Bazel doesn't have functionality to run a `java_library`, even if Java might support it.

If we did the proposed feature: we'd get user bases with java_binary -> java_library -> java_binary dependency chains, which would be really hard to query or reason about. If we did the alternative: we'd break user bases that already use `src` attribute in `java_application`.
