### ISSUE TITLE
new_http_repository fails when archive contains non-ASCII filenames

### ISSUE THREAD

**Issue by AlexTalks** [bazelbuild/bazel#1284]
When trying to build a target that depends on the following:
```
new_http_archive(
  name = "boost_remote",
  url = "https://downloads.sourceforge.net/project/boost/boost/1.59.0/boost_1_59_0.tar.bz2",
  sha256 = "727a932322d94287b62abb1bd2d41723eec4356a7728909e38adb65ca25241ca",
  build_file = "boost.BUILD",
  strip_prefix = "boost_1_59_0"
)
```
we get the following error due to the archive containing a non-ASCII filename, despite the fact that the rule does not depend on this file at all (it is an unrelated HTML documentation file):
```
ERROR: /.../WORKSPACE:22:1: no such package '@boost_remote//': /private/var/tmp/_bazel_sarkesian/b32f3f08e1126427f0a6301158a60fe5/external/boost_remote/libs/preprocessor/doc/Appendix A ? An Introduction to Preprocessor Metaprogramming.html (No such file or directory) and referenced by '//external:boost'.
ERROR: Loading failed; build aborted.
```

This same archive, when extracted to a local directory, works just fine for building the target when using the equivalent `new_local_repository` function in the WORKSPACE file.

Have discussed this issue with @kchodorow

**Comment by kchodorow** [comment]
This actually works for me (I have an empty boost.BUILD file and I'm building @boost_remote//:all).  What target are you building/what does your BUILD file look like?

**Comment by damienmg** [comment]
No answer so closing.
