### ISSUE TITLE
cc_library doesn't trigger build of dependent objc_library

### ISSUE THREAD

**Issue by AlexTalks** [bazelbuild/bazel#1285]
When we have a objc_library target that is in the deps of a cc_library target, when building the cc_library it does not trigger a build of the objc_library that it depends on.  However, if we have a subsequent cc_test that depends on the cc_library (which in turn depends on the objc_library), the dependency build is kicked off correctly.

Discussed this with @calpeyser

**Comment by mhlopko** [comment]
@calpeyser Is this still an issue? Sounds surprising to me.

**Comment by calpeyser** [comment]
I don't think this is an issue anymore.
