### ISSUE TITLE
remote_download_minimal: downloaded inputs shouldn't be deleted after the build

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/bazel#12855]
### Description of the problem / feature request:

When using `--remote_download_minimal`, downloaded inputs shouldn't be deleted after the build.

### Feature requests: what underlying problem are you trying to solve with this feature?

Currently, when bazel needs to download inputs for a locally run action while using `--remote_download_minimal`, it deletes these inputs after the build: https://github.com/bazelbuild/bazel/blob/570f01968093d943b1f878f2cf57da4c20ba5355/src/main/java/com/google/devtools/build/lib/remote/RemoteModule.java#L788-L810

This makes incremental compilation less efficient.

For example, if we set a bundling rule to run locally, bazel will download all of the various artifacts that need to be bundled together, and if we incrementally only change a single artifact in that bundle, bazel will have to re-download all of the artifacts, even though they didn't change since the last build. The fact that disk_cache doesn't work with remote builds ensure that this is a slow download as well.

### What operating system are you running Bazel on?

macOS 10.15.7

### What's the output of `bazel info release`?

release 4.0.0rc10

###  Have you found anything relevant by searching the web?

- https://github.com/bazelbuild/bazel/issues/12635
- https://github.com/bazelbuild/bazel/issues/12665

**Comment by coeuvre** [comment]
Fixed by f0c32de0823307ec293a882af6a9c7a48631d33b.

**Comment by brentleyjones** [comment]
Thank you!

**Comment by brentleyjones** [comment]
@coeuvre One "benefit" of this issue, that I've come to like since filing the bug, is that it allows large working sets to happen on space constrained machines (ones that the build would fail on before reaching the end, where one could call `bazel clean`). I wonder if we want this to be configurable in some way?

**Comment by coeuvre** [comment]
I don't think unconditionally delete downloaded intermediate outputs is a good way to manage the content of output base. `bazel clean` is a valid work around in this case since you will hit remote cache next time running `bazel build` and only download necessary files.

One way I could image is that we can collect the usages of these downloaded output files and delete those which are not used after a certain period of time.

**Comment by brentleyjones** [comment]
For my (new) specific use case, the build will fail if it doesn't delete the intermediate outputs during the build, since the local machine doesn't have enough space to have all of them at once. If it deletes as it goes the build succeeds. I'm not saying that my use case warrants a change, but this might count as a breaking change because of that?

**Comment by coeuvre** [comment]
`deleteDownloadedInputs` was called after a build command. I don't think we were able to delete intermediate outputs **during** the build.

**Comment by brentleyjones** [comment]
Hmm. I was seeing that the local inputs were deleted during the build. For example, we run tests locally, so the tests themselves are being downloaded, but then deleted right after each one is run (at least it looks that way).
