### ISSUE TITLE
All remote repos pointed to by a select are fetched, even for unmatched arms

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#12861]
Forked from https://github.com/bazelbuild/bazel/pull/12846.

Currently, the labels of all arms of a `select` are loaded, even for the unmatched arms. That is, if you write `select({"true": "@A//:thing", "false": "@B//:thing"})`*, the repo B would be fetched.

As the PR demonstrates, inserting an alias in the middle somehow works around this. That is, if you introduce an alias to `@B//:thing` in the current package (say `:B_thing`) and use `:B_thing` in the `false` arm, the repo B wouldn't be fetched.

This is problematic for conditional external dependencies in the new design. A user could try to fetch some Linux-only deps via nixpkgs (which only runs on Linux) and use a `select` to guard its usage. Those deps would be completely missing on Windows, but since they're properly guarded by a `select`, we shouldn't fail the build.

cc @meteorcloudy @gregestren @comius @katre 

\* This is obviously not real syntax.

**Comment by meteorcloudy** [comment]
Wow, thanks for catching this. This is really surprising..

**Comment by gregestren** [comment]
This has something to do specifically with repo prefixes. Here's proof (skipping targets in the default repo):

```
$  cat testapp/defs.bzl
def _impl(ctx):
    return []

simple_rule = rule(
    implementation = _impl,
    attrs = {"deps": attr.label_list()})

$  cat testapp/BUILD
load("//testapp:defs.bzl", "simple_rule")

config_setting(
    name = "a",
    define_values = {"a": "1"})

simple_rule(
    name = "s",
    deps = select({
        ":a": ["//testapp/a:adep"],
        "//conditions:default": ["//testapp/b:bdep"],
    }))

$  cat testapp/a/BUILD
load("//testapp:defs.bzl", "simple_rule")

simple_rule(
    name = "adep",
    visibility = ["//testapp:__pkg__"],
)

$  cat testapp/b/BUILD
load("//testapp:defs.bzl", "simple_rule")

THIS IS A BAD BUILD FILE
```

```
$  bazel build //testapp:s
ERROR: /home/testapp/b/BUILD:3:6: syntax error at 'IS': expected newline
ERROR: /home/testapp/BUILD:8:12: no such target '//testapp/b:bdep': target 'bdep' not declared
    in package 'testapp/b' 
```

```
$  bazel build //testapp:s --define a=1
INFO: Analyzed target //testapp:s (0 packages loaded, 11 targets configured).
INFO: Build completed successfully, 1 total action
```

**Comment by gregestren** [comment]
In other words, the logic that implements `select()` only evaluates the chosen dep. Whatever's pulling the unchosen dep is coming from some other logic.

**Comment by gregestren** [comment]
I updated the above to put `//testapp/b:b` in a different repo:

```
$ cat WORKSPACE
...
local_repository(
    name = "myrepo",
    path = "/home/thisdirectorydoesntexit"
)

$  cat testapp/BUILD
load("//testapp:defs.bzl", "simple_rule")

config_setting(
    name = "a",
    define_values = {"a": "1"})

simple_rule(
    name = "s",
    deps = select({
        ":a": ["//testapp/a:adep"],
        "//conditions:default": ["@myrepo//testapp/b:bdep"],
    }))
```

**Select the bad dep:**
```
$  bazel build //testapp:s
ERROR: /home/testapp/BUILD:8:12: //testapp:s depends on @myrepo//testapp/b:bdep in repository @myrepo
which failed to fetch. no such package '@myrepo//testapp/b': The repository's path is "/home/thisdirectorydoesntexit" 
but this directory does not exist.
```

**Select the good dep (//testapp/a:a):**
```
$  bazel build //testapp:s --define a=1
INFO: Analyzed target //testapp:s (0 packages loaded, 11 targets configured).
INFO: Build completed successfully, 1 total action
```

Is `select()` really a culprit here?

**Comment by gregestren** [comment]
Hey @comius - can you verify `select()` is indeed the culprit for #12846? Could you share a minimal repro that shows this?

**Comment by comius** [comment]
I failed to make a simple minimal reproduction so far, it seems a bit elusive.

So the reproduction is to build gerrit using bazel before change to aliases. 

Is there a way that I figure out what is triggering download in that setup? I could bisect targets being build in gerrit and try reducing them. How would somebody catch a something like genquery in gerrit running over //tools/jdk:...?

**Comment by gregestren** [comment]
I really don't know anything repo-related logic. But... are you saying this is all happening within a `genquery`?

**Comment by comius** [comment]
It was my hypothesis it is happening within a `qenquery`, and I confirmed it! :)

The fetching of repositories is caused by gerrit, when building `bazel test //javatests/com/google/gerrit/pgm:pgm_license_test`.

BUILD
```
license_test(
    name = "pgm_license_test",
    target = "//java/com/google/gerrit/pgm",
)
```

license.bzl
```
def license_test(name, target):
    """Make sure a target doesn't depend on DO_NOT_DISTRIBUTE license"""
    txt = name + "-forbidden.txt"

    # fully qualify target name.
    if target[0] not in ":/":
        target = ":" + target
    if target[0] != "/":
        target = "//" + native.package_name() + target

    forbidden = "//lib:LICENSE-DO_NOT_DISTRIBUTE"
    native.genquery(
        name = txt,
        scope = [target, forbidden],
        # Find everything that depends on a license file, but remove
        # the license files themselves from this list.
        expression = 'rdeps(%s, "%s", 1) - rdeps(%s, "%s", 0)' % (target, forbidden, target, forbidden),
    )
    native.sh_test(
        name = name,
        srcs = ["//tools/bzl:test_license.sh"],
        args = ["$(location :%s)" % txt],
        data = [txt],
    )
```

**Comment by katre** [comment]
Ah, that explains it: query cannot evaluate selects, and so every branch is included. I'm confused about why it stops at the alias, however.

**Comment by gregestren** [comment]
What's the exact dependency path in question? Queries don't necessarily follow the entire build graph, so my guess would be it's looking at the deps of a target with a `select` but not at the deps' deps. @comius would you like us to continue to diagnose why aliases solve the problem?

Also, would you like to close this bug or keep it open?

Following all `select` paths is pretty intrinsic to`genquery`. It's really hard to get `genquery` to understand `select`s. I think we have a FR for that somewhere but it's an involved change with unclear consequences to Skyframe. So it's not on any practical roadmap. 

We could imagine some other variant that "follows" the dep but doesn't invoke fetching in a `genquery` context. That could actually be an interesting idea. But I don't know what's technically involved.

**Comment by comius** [comment]
I'm not very familiar with `rdep` query, but thinking about it. Isn't a proper behaviour, that repos are not downloaded, when it is used? How could a target in a remote repo depend on current repo?

If that is true, behaviour on `alias` is correct, while on `select` it's not.

I don't have much interest in solving this, because the newly introduce aliases are going away with next rolling release.

**Comment by katre** [comment]
@Wyverald: Can you clarify how bzlmod will interact with this issue?

**Comment by thefallentree** [comment]
the rdeps questions are discussed here https://github.com/bazelbuild/bazel/issues/13190 , the answer right now is that we needs a new flag to disable fetching external repos when running rdeps query

**Comment by Wyverald** [comment]
This is a known behavior of `bazel query`, so I'm closing this.
