### ISSUE TITLE
Documentation issue: Migrating from Maven to Bazel

### ISSUE THREAD

**Issue by herry-c** [bazelbuild/bazel#12878]
Documentation URL: https://docs.bazel.build/versions/master/migrate-maven.html

Does BAZEL support Maven-based plugins, such as codegen?

**Comment by divanorama** [comment]
Afaik, no. Though maybe there should be a list of replacements for popular plugins. Do you have any specific plugins in mind?

**Comment by herry-c** [comment]
We need to convert some interface files such as YAML files into Java files for compilation. If Bazel is used, how should we use the plug-in?

**Comment by divanorama** [comment]
Codegen is very doable, you can try starting with [genrule](https://docs.bazel.build/versions/master/be/general.html#genrule) and adding its outputs as src for java targets. Ideally, all the codegen tools can also be defined in bazel (rather than relying on fixed paths on host machine): toolchains or even simply targets compiled/built by bazel (plus maybe a set of rules or macros to make it easier to use), but that'd probably be a next step as it takes extra implementation efforts.

**Comment by philwo** [comment]
team-xProduct cannot help here, we don't know anything about Maven. Reassigning to team-Documentation.

**Comment by floriographygoth** [comment]
Hi @divanorama 

is this something where you can provide a draft for us or create a PR? Happy to help from an editorial standpoint, but we don't have the immediate expertise to create the docs. 

Thanks!

**Comment by divanorama** [comment]
One simple fix to do is just add a line like
> Maven plugins can't be directly run by bazel as there's no maven compatibility layer. 

There's a lot of plugins to cover https://maven.apache.org/plugins/, https://www.mojohaus.org/plugins.html and more. I could potentially spend some time looking for how to port some concrete plugin example, but don't have any collection of replacements or a generic recipe.

Maybe also follow with few recommended/popular extensions, which could include (corresponding manuals/readmes may need to be written first)
- adding spotbugs https://github.com/spotbugs/spotbugs for tests
- using junit5 (WIP) https://github.com/junit-team/junit5-samples/pull/133
- using protobuf&grpc
- using nullaway https://github.com/uber/nullaway
- using java annotation processors in general (there are probably existing docs on that)
- writing codegen rules in general (link to existing genrule section for example)
- using aspects&rules to do advanced reporting (link to docs)

But in short it boils down to
- writing your own rules = links to other parts of docs
- using existing rules = links to bazel section of a project/plugin in question, or to rules_something

Also rules_jvm_external https://github.com/bazelbuild/rules_jvm_external/ may be the place to put wrappers for common annotation processors and plugins, people migrating from maven to bazel would likely visit that project and maybe add an issue on missing bits & get answers there.

**Comment by communikit** [comment]
Closing this after https://github.com/bazelbuild/bazel/commit/6eb4597ffb5174475fb9fbbf70dbf114a85e96e7 was merged.
