### ISSUE TITLE
warning on build file created by bazel

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#1287]
with bazel 0.2.3, I see the following warning:
```
WARNING: /private/var/tmp/_bazel_oscar/cff0ec2cf472ebc5cb4402685dc7edf3/external/com_twitter__scalding_date/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_oscar/cff0ec2cf472ebc5cb4402685dc7edf3/external/com_twitter__scalding_date/WORKSPACE (@__main__) does not match the name given in the repository's definition (@com_twitter__scalding_date); this will cause a build error in future versions.
```

but that `WORKSPACE` name is just what bazel creates from adding a `maven_jar`, so I think that means bazel has made the error, not the code that has named the `maven_jar`.

**Comment by johnynek** [comment]
to be clear, I think this warning is on every maven_jar in the repo, which is super noisy.

**Comment by kchodorow** [comment]
Is this on an incremental build?  I think this might be fixed by https://bazel-review.googlesource.com/c/3660/ (not yet merged).

**Comment by johnynek** [comment]
This seems to happen on every build (bazel clean && bazel build src/... does not make it go away).

Is there a way to silence this warning until there is a fix? One fix I can think of is making a repo rule instead of using maven_jar, but that seems pretty heavy weight.

**Comment by johnynek** [comment]
actually, off-thread @smparkes suggested: `rm -rf /var/tmp/_bazel_oscar/` and that worked for me. Now I only have one warning, which may be a legit error.
