### ISSUE TITLE
.bazelrc next to the Bazel binary is ignored

### ISSUE THREAD

**Issue by yoerg** [bazelbuild/bazel#12881]
### Description of the problem:

The [guide](https://github.com/bazelbuild/bazel/blob/4.0.0/site/docs/guide.md#the-global-bazelrc-file) mentions that bazel looks for a `.bazelrc` file next to its binary, but this seems to have been disabled [long ago](https://github.com/bazelbuild/bazel/commit/ec83598cb6ee4136166bb562a24dc5dfa58921db):

> In addition to your personal .bazelrc file, Bazel reads global bazelrc files in this order: $workspace/tools/bazel.rc, .bazelrc next to the Bazel binary, and /etc/bazel.bazelrc. (It's fine if any are missing.)

Which is a shame, because I actually wanted to use that feature to provide offline build machines with bazel+distdir packages.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- Copy bazel release as C:\Users\me\mybazel\bazel.exe
- Create an invalid `C:\Users\me\mybazel\bazel.bazelrc` file next to the binary, e.g:
`common --not-a-flag`
- Run `C:\Users\me\mybazel\bazel.exe --client_debug version`

Expected an error, but bazel returns the version output and doesn't mention the binary bazel.rc.

### What operating system are you running Bazel on?

Windows 10
Also tested on Ubuntu Bionic

### What's the output of `bazel info release`?

release 4.0.0

**Comment by brandjon** [comment]
I don't take a position on whether the rc file next to the binary is useful or not, but if we keep the current behavior then we should document it.
