### ISSUE TITLE
Update java_toolchain documentation

### ISSUE THREAD

**Issue by anzdaddy** [bazelbuild/bazel#1288]
0.2.3 tags a bunch of java_toolchain properties as required, which breaks the examples in [the Java Configuration](http://bazel.io/blog/2015/07/08/Java-Configuration.html) blog post and [the java_toolchain documentation](http://bazel.io/docs/be/java.html#java_toolchain).

**Comment by davidstanke** [comment]
Assigning to @spomorski -- note that the example in the docs still omit required attributes.

**Comment by comius** [comment]
Closing, the documentation has been updated in https://github.com/bazelbuild/bazel/commit/2fb9f3cfe3ef152325335fb03e6ae8e7c2a5ee0d
