### ISSUE TITLE
Bazel 4.0.0 breaks macOS Mojave support (for some XCode CLT versions)

### ISSUE THREAD

**Issue by dhalperi** [bazelbuild/bazel#12894]
### Description of the problem / feature request:

Several folks on my team are reporting issues after upgrading to 4.0.0. One user is on 10.13.6 (High Sierra) and another is on 10.14.2 (Mojave). Both are able to build fine with 3.7.2, and both have build failures with libtool on 4.0.0:

```
ERROR: /private/var/tmp/_bazel_matt/c2cb640b277cd35f816879cfba9892ed/external/com_google_protobuf/BUILD:334:11: Linking external/com_google_protobuf/libprotoc_lib.a failed: (Exit 1): libtool failed: error executing command /usr/bin/libtool @bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/libprotoc_lib.a-2.params
Use --sandbox_debug to see verbose messages from the sandbox libtool failed: error executing command /usr/bin/libtool @bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/libprotoc_lib.a-2.params
Use --sandbox_debug to see verbose messages from the sandbox
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: no output file specified (specify with -o output)
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]
```

From what I can tell, this is extremely reminiscent of #7397 -- seems related to `AR` resolution.

### Feature requests: what underlying problem are you trying to solve with this feature?

Be able to build on old versions of macOS. Unless minimum version of macOS is planned and documented somewhere?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

* get a macbook with 10.13.6, and XCode CLT installed.
* checkout bazelbuild/bazel at HEAD today
* install JDK, e.g., via `brew tap AdoptOpenJDK/openjdk ; brew install adoptopenjdk11`
* `bazel build //src:bazel_nojdk` with 4.0.0

Try again with 3.7.2, and it builds successfully.

### What operating system are you running Bazel on?

macOS High Sierra 10.13.6 or Mojave 10.14.2 or Mojave 10.14.6

### What's the output of `bazel info release`?

`release 3.7.2` or `release 4.0.0` 

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Redundant with above, but built from https://github.com/bazelbuild/bazel/commit/660f5b2cf36fbd75908cf7c93cc59d98ee092eb2

###  Have you found anything relevant by searching the web?

No. I specifically looked for release notes announcing this as a breaking change, didn't find any [here](https://blog.bazel.build/2021/01/19/bazel-4-0.html#incompatible-changes) or [here](https://github.com/bazelbuild/bazel/releases/tag/4.0.0)

**Comment by dhalperi** [comment]
Since High Sierra is effectively EOL now (no longer receiving security patches as of this month), probably skip worrying about that one.

I have obtained a test machine and can repro with Mojave easily.

**Comment by keith** [comment]
Can you verify the error you're seeing in the latest supported Xcode version on that OS is the same as the libtool one above and not https://github.com/bazelbuild/bazel/issues/12905 ?

If it is the libtool issue it's likely https://github.com/bazelbuild/bazel/pull/12265 in which case we'd likely need to add some OS version checking to disable this behavior

**Comment by dhalperi** [comment]
I just expunged and removed `/var/tmp/_bazel_$USER`, and made sure I was on 4.0.0.

I am not 100% certain I have the "latest supported Xcode version" -- Apple has made this harder to get recently.

Command Line Tools 11.3 requires 10.15.4 minimum, so won't work on Mojave.

I think I have CLT 10.3 ish:

`xcode-select -v` gives me version 2354.
`clang -v` gives me Apple LLVM version 10.0.1 (clang-1001.0.46.4)
==> Running `pkgutil --pkg-info=com.apple.pkg.CLTools_Executables` gives me `version 10.3.0.0.1.1562985497`

This is the latest returned by `xcode-select --install` (which I ran immediately after installing Mojave). After that it tells me to use `Software Update`, which has no updates for me.

So that's the caveat, but with that, yes: the error I get is the same `libtool` error above.

**Comment by keith** [comment]
The version question here is just what version of Xcode added support for params files to `libtool`. It looks like the answer to that is 11.0

**Comment by dhalperi** [comment]
Update!

I went back to the developer tools site, found that I was wrong about minimum version requirements. 11.5 requires 10.15 (Catalina), but 11.3.1 I could install on Mojave. That actually seems to work fine, without any caveats, on Mojave.

version: `11.3.1.0.1.1576735732`

**Comment by philwo** [comment]
Hi, we cannot test Bazel on or develop any patches for macOS Mojave ourselves, as we usually upgrade quickly after a new version comes out. However I'm happy to take patches if someone wants to contribute.

That said, does the last update mean that this issue is resolved now (by upgrading Xcode)?

**Comment by dhalperi** [comment]
Is it obvious why CI can't have older versions of OS X -- I imagine mainly maintainer time.

I'd say the best resolution would be to advertise expected support for macOS (and other platforms): which versions are tested, which are used by developers, etc. And to update in release notes when they change. Presumably this issue can serve as notification of resolution for macOS users who have developer accounts. (You can't get into the download without one.)

**Comment by philwo** [comment]
> Is it obvious why CI can't have older versions of OS X -- I imagine mainly maintainer time.

Maintainer time and effort is one factor, also limited hardware - we only have 20x iMac Pros to run Bazel CI on and as we don't use virtualization for performance reasons, it's not (easily) possible to run different versions of macOS side-by-side. :/

It's a good idea to document the supported / tested macOS versions, I agree. Currently we are still running Catalina on the CI machines, so all recent Bazel versions up to 4.0 are built on and tested on that version.

**Comment by dhalperi** [comment]
At this point 4 is one major version behind, and Mojave is 3 behind (soon to be 4), I think it's worth closing.
