### ISSUE TITLE
Allow the `attr` parameter `default` to accept `select` statements

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/bazel#12895]
### Description of the problem / feature request:

The `default` parameter of [ctx.attr](https://docs.bazel.build/versions/master/skylark/lib/attr.html) types do not accept [select](https://docs.bazel.build/versions/master/be/functions.html#select) statements.

### Feature requests: what underlying problem are you trying to solve with this feature?

The following code blocks is what I'm attempting to implement. I'd like to pass a select statement to the `default` parameter of some attribute a rule I've written.

#### BUILD.bazel
```python
load("//:my_rule.bzl", "my_rule")

config_setting(
    name = "is_debug",
    values = {"compilation_mode": "dbg"},
)

my_rule(
    name = "hello",
)
```

#### my_rule.bzl
```python
def _my_rule_impl(ctx):
    pass

my_rule = rule(
    implementation = _my_rule_impl,
    attrs = {
        "is_debug": attr.bool(
            default = select({
                "//:is_debug": True,
                "//conditions:default": False,
            }),
        ),
    },
)
```

#### WORKSPACE.bazel
```python
workspace(name = "bool")
```

### What operating system are you running Bazel on?

macOS 11.1

### What's the output of `bazel info release`?

release 4.0.0

###  Have you found anything relevant by searching the web?

I was recommended twice to open a ticket in https://github.com/bazelbuild/bazel/pull/12071#issuecomment-767199568 and [on slack](https://bazelbuild.slack.com/archives/CA31HN1T3/p1611188463076900)

### Any other information, logs, or outputs that you want to share?

Running
```command
bazel build //...
```

with the example above results in

```output
ERROR: Traceback (most recent call last):
	File "/Users/user/Code/tests/bool/my_rule.bzl", line 7, column 30, in <toplevel>
		"is_debug": attr.bool(
Error in bool: in call to bool(), parameter 'default' got value of type 'select', want 'bool'
ERROR: error loading package '': Extension file 'my_rule.bzl' has errors
```

I would expect this to work.

**Comment by katre** [comment]
Does this work for other attribute types? I'm very surprised if `select` works in rule definitions at all.

**Comment by UebelAndre** [comment]
Ah good call. It appears I was mistaken
#### my_rule.bzl
```python
def _my_rule_impl(ctx):
    pass

my_rule = rule(
    implementation = _my_rule_impl,
    attrs = {
        "a_label": attr.label(
            default = select({
                "//:is_debug": "//:foo",
                "//conditions:default": "//:bar",
            }),
        ),
    },
)
```

#### Output
```output
	File "/Users/user/Code/tests/bool/my_rule.bzl", line 7, column 31, in <toplevel>
		"is_debug": attr.label(
Error in label: in call to label(), parameter 'default' got value of type 'select', want 'Label, string, LateBoundDefault, function, or NoneType'
```

So then this would be a feature request and not a bug

**Comment by gregestren** [comment]
Thanks for filing this. I didn't realize when you first mentioned it you were referring to default values. I'm going to close this for https://github.com/bazelbuild/bazel/issues/287, which covers the same issue. Short story is we'd need input from the Starlark folks.

As always, an alias (or a macro, mentioned in the other bug) is a workaround.
