### ISSUE TITLE
Investigate whether filegroup can use platform-conditional selects

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#12899]
Branched from https://github.com/bazelbuild/bazel/pull/12071:

Currently, the `filegroup` rule doesn't participate in toolchain resolution (see https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/bazel/rules/common/BazelFilegroupRule.java;l=78), which means the target platform doesn't exist and so platform-conditional selects don't work.

As I recall, it led to a cycle in evaluation, because filegroups were needed at a low-enough level that we couldn't process loading platforms without them.

I'll investigate whether this is still an issue and whether this can be re-enabled.

**Comment by katre** [comment]
To clarify, we have a test for this specific behavior: https://cs.opensource.google/bazel/bazel/+/master:src/test/java/com/google/devtools/build/lib/analysis/ConfigurableAttributesTest.java;l=1232

**Comment by gregestren** [comment]
Before advancing, what do you think of my question in https://github.com/bazelbuild/bazel/pull/12071#issuecomment-767586628?  Could it be `select` that instantiates the platform info when it's not already available? Would that also require a toolchain or could it just directly load the platform?

How would that compare to opting `filegroup` back into toolchains?

That's really interesting about the test. Was that intentional?

**Comment by katre** [comment]
I made the change and ran tests (see https://github.com/bazelbuild/bazel/pull/12901). All the failures, including ConditionalAttributesTest, were just using `filegroup` as a placeholder rule that doesn't use toolchain resolution.

To reply to your comment: I think it does make sense that even without toolchain resolution, configured targets always have a target platform. This shouldn't be a major change to how things happen now, and I can file a (low-priority) issue to investigate further.

As far as changing `filegroup` it looks very reasonable to me and I'm going to continue with the PRs to make that change. Once the tests are cleaned up I'll need to be sure to run internal tests for the same behavior and make sure there are no further blockers.

**Comment by katre** [comment]
Re-opening because I undid this in #13194.

I need to add a test and figure out the right solution for the issue of split internal/external filegroup implementations.
