### ISSUE TITLE
Bazel 4.0.0 does not work with XCode 11.3

### ISSUE THREAD

**Issue by jbms** [bazelbuild/bazel#12905]
This line here:

https://github.com/bazelbuild/bazel/blob/8959dff512fe4505af786bcf2ef981ec7082a913/tools/osx/crosstool/cc_toolchain_config.bzl#L5369

introduced in this commit:

https://github.com/bazelbuild/bazel/commit/0cb8757781e3ab9b4aee06483b74b46a2e4c6126

causes Bazel 4.0.0 to not work with XCode 11.3 because it does not support the `-fdebug-compilation-dir` flag:

clang --version
Apple clang version 11.0.0 (clang-1100.0.33.16)

clang: error: unknown argument: '-fdebug-compilation-dir'

That version of XCode is still in pretty common use.

**Comment by keith** [comment]
https://github.com/bazelbuild/bazel/pull/12882

**Comment by dyrone** [comment]
Found this problem too

**Comment by keith** [comment]
FYI to workaround this now you can pass `--features=-debug_prefix_map_pwd_is_dot`

**Comment by dyrone** [comment]
> FYI to workaround this now you can pass `--features=-debug_prefix_map_pwd_is_dot`

Thank you, it works as usual now
