### ISSUE TITLE
The query language lacks a way to query rules that are target_compatible_with

### ISSUE THREAD

**Issue by luna-duclos** [bazelbuild/bazel#12917]
### Description of the problem / feature request:

The query language lacks a way to express "I want to query all targets that are compatible with a certain platform. This is because even though you can use attr() with cquery to ask for values of the attribute, thats not good enough as the attribute is transitive and dependencies might be incompatible, causing the target to still be incompatible even though it has no attribute itself.

We had to work around this by manually running over the proto output of cquery and checking the target_compatible_with attribute of a rule and its dependencies manually in Go code.

The query language should have a function that allows one to query if a rule is compatible, something along the lines of `compatible_with(<rule>, <constraint>)`, with `compatible_with(<rule>)` defaulting to `@local_config_platform//:host` as constraint.

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm trying to avoid needing to manually run over the analysis proto manually, which is slow, error prone, easy to get wrong and also restricts my ability to meaningfully use other operators alongside

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

This is a feature request, any use of `target_compatible_with` in a dependency and then trying to cquery compatible rules in any way will stumble on this.

### What operating system are you running Bazel on?

We use bazel on MacOS and Linux.

### What's the output of `bazel info release`?

`release 4.0.0`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

I've discussed this on the bazel slack and was told I should likely log a feature request

**Comment by philsc** [comment]
@gregestren , @katre

I've not thought about this, but I think it's a good idea to solve this. If you build up your CI target list from a query, there should be a way to filter those out.

**Comment by gregestren** [comment]
`cquery` haw new functionality that can query over providers, which incompatible target skipping uses to honor these transitive effects. Let me look up the docs on that.

Caveat is it only works on Starlark-readable providers, which incompatible target skipping isn't yet.

**Comment by gregestren** [comment]
https://docs.bazel.build/versions/master/cquery.html#providers

**Comment by philsc** [comment]
That's a cool idea @gregestren , thanks!

**Comment by philsc** [comment]
I think this could work pretty well:
https://github.com/philsc/bazel/commit/3d0c66550858631f57bf470878959640bb6ce7d6#diff-a982fd7588855b07d791b1b297ffc662b316c80313943ec6998af93edb331c5e

Re-posting the relevant snippet here for simplicity:
```console
$ cat > compatibility.cquery <<EOF
def format(target):
    if "IncompatiblePlatformProvider" in providers(target):
        result = "incompatible"
    else:
        result = "compatible"
    return "%s is %s" % (target.label, result)
EOF
$ bazel cquery :all  --output=starlark --starlark:file=target_skipping/compatibility.cquery
```

@luna-duclos , would that server your use case?  For incompatible targets you can return an empty string so it wouldn't print anything.

**Comment by luna-duclos** [comment]
It would!

**Comment by philsc** [comment]
Cool. I'll get that turned into a pull request then.

**Comment by gregestren** [comment]
Happy to review promptly.
