### ISSUE TITLE
--nobuild_runfile_links does not clean runfile links

### ISSUE THREAD

**Issue by guibou** [bazelbuild/bazel#12914]
### Description of the problem / feature request:

`--nobuild_runfile_links` does not seem to clean previously built runfiles links.

### Feature requests: what underlying problem are you trying to solve with this feature?

I recently started to use `--nobuild_runfile_links` in order to address #2951 that I've it on our project.

Some of our rules are not working with the option and I need to enable it again for them. However I observed that they are broken only after a `bazel clean`, or on a run of a clean configuration (CI runners).

This is an issue with reproducible build, because I cannot ensure the result is the same when bazel is called with the same option, but with a different history.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- `bazel build` a target which generates runfiles.
- locate the associated runfiles in the base, e.g. `/home/user/.cache/bazel/_bazel_user/HASH/execroot/workspace/bazel-out/k8-fastbuild/bin/path/to/rule.runfiles`
- `bazel build --nobuild_runfile_links`
- observes that the runfiles are still in the associated directory.
- `bazel clean`
- `bazel build --nobuild_runfile_links`
- observes that the runfiles are not in the associated directory.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

```
INFO: Invocation ID: 083819ef-cfaf-4280-8b76-e3cb3901c5c3
release 3.3.1- (@non-git)
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

from nixpkgs.

**Comment by janakdr** [comment]
Thanks for the report. I'm fairly sure that if we changed this behavior, it would break someone else's workflow. This is also part of the general fact that Bazel does not delete previous outputs from the output tree before performing the next build.

Have you tried sandboxing your actions? If they're not sandboxed, you don't really have reproducibility anyway, and if they're sandboxed, this issue should go away.

**Comment by guibou** [comment]
@janakdr You ask a really good question about sandboxing.

You are right, even if the generated files are generated by `bazel build` (as described in this ticket), the reproducibility issue only appears when `bazel run` which is not sandboxed.

I need to check if there is a way to sandbox the `bazel run`, never thought about this.
