### ISSUE TITLE
Bazel CI: downstream projects broken due to visibility check on select() keys

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#12925]
https://buildkite.com/bazel/bazel-auto-sheriff-face-with-cowboy-hat/builds/413

Caused by: https://github.com/bazelbuild/bazel/commit/cac82cf00649217e621e86825e9e99b3e56b0d34

TensorFlow:
```
(02:11:27) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/6ba24013571fc441abf8cb89e73a856e/external/curl/BUILD.bazel:34:11: in cc_library rule @curl//:curl: alias '//tensorflow:macos' referring to target '//tensorflow:macos_arm64' is not visible from target '@curl//:curl'. Check the visibility declaration of the former target if you think the dependency is legitimate
```

Envoy:
```
(02:11:05) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/08eac9c5b682112ef6dbfa42e405abe6/external/com_github_google_tcmalloc/tcmalloc/internal/BUILD:217:11: in cc_library rule @com_github_google_tcmalloc//tcmalloc/internal:mincore: target '@com_github_google_tcmalloc//tcmalloc:llvm' is not visible from target '@com_github_google_tcmalloc//tcmalloc/internal:mincore'. Check the visibility declaration of the former target if you think the dependency is legitimate
```

I'll try to send PRs to downstream projects to fix this.

**Comment by meteorcloudy** [comment]
FYI @gregestren

**Comment by meteorcloudy** [comment]
The Envoy breakage is due to com_google_tcmalloc, so I have to fix tcmalloc then update its version in Envoy.

**Comment by meteorcloudy** [comment]
FYI @htuch

**Comment by gregestren** [comment]
Thanks for the info, @meteorcloudy. This is a delicate one. If it comes to it we may have to roll back the PR. But fixing the depot is exactly what we ultimately want to do. I'm not completely clear yet if the first option is necessary. 

Keep me updated from your end.

**Comment by meteorcloudy** [comment]
Not too many downstream projects are broken, and it's an easy fix, so I don't think it should block you from making progress ;)

**Comment by htuch** [comment]
@yanavlasov for visibility; @meteorcloudy Yan is the new Envoy - Bazel relationship owner :)

**Comment by meteorcloudy** [comment]
@htuch Thanks for the introduce. 
@yanavlasov Can you help upgrading tcmalloc to the latest commit to fix this breakage?
https://github.com/google/tcmalloc/commit/4c7646615556688de98b6995197de4c3e74515fc

**Comment by sventiffe** [comment]
Any update on this issue?

**Comment by meteorcloudy** [comment]
It looks like Envoy has been green for a while. I believe they have fixed the breakage. Closing.

**Comment by gregestren** [comment]
Note this is getting reintroduced behind *two* incompatible flags:

- https://github.com/bazelbuild/bazel/issues/12932
- https://github.com/bazelbuild/bazel/issues/12933

But thank you for the effort you'd already put in to clean up ahead of time.
