### ISSUE TITLE
cquery should support --query_file

### ISSUE THREAD

**Issue by luna-duclos** [bazelbuild/bazel#12924]
### Description of the problem / feature request:

`bazel cquery` should support the `--query_file=` argument, similar to `bazel query`, 

### Feature requests: what underlying problem are you trying to solve with this feature?

this would allow us not to have to care about, for example, the relatively short command line length on macOS when writing queries.
As well as being able to programatically generate big queries and not have to worry about their length at all

### What operating system are you running Bazel on?

We run bazel on linux and macOS

### What's the output of `bazel info release`?

release 4.0.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

**Comment by jin** [comment]
Greg, is the premise of this FR sound? Folks using Bazel in AOSP could use this. Also pinged on the internal doc.

**Comment by brentleyjones** [comment]
@gregestren Seems like https://github.com/bazelbuild/bazel/commit/fb2324620a4adee19bb4e8a030b6fba58f672dc0 could go into a 6.x release (as in cherry-picked right now)? I saw it mentioned [here](https://github.com/bazelbuild/bazel/issues/17403#issuecomment-1431890667) and I was surprised it didn't make it into 6.0

**Comment by aiuto** [comment]
@sgowroji Can you take care of the backport to the next 6.x release?

**Comment by sgowroji** [comment]
Sure @aiuto. Thanks for tagging.

**Comment by keertk** [comment]
@bazel-io fork 6.2.0

**Comment by keertk** [comment]
Included in the release-6.2.0 branch: https://github.com/bazelbuild/bazel/pull/17823.
Closing this issue.
