### ISSUE TITLE
query of `kind("package group"` can not be filtered via `attr(`

### ISSUE THREAD

**Issue by joscha** [bazelbuild/bazel#12937]
### Description of the problem request:

Package groups can be queried via:

```bash
bazel query 'kind("package group", //...:*)'
```
and the return is a list of package groups, e.g.:

```bazel
package_group(
    name = "my-group-target",
    packages = [
        "//some/...",
        "//more/...",
        "//things/...",
    ],
)
```

inside a package `xyz`

would yield a:

```bazel
//xyz:my-group-target
```

adding another `attr()` selector around it always yields an empty list.

### Feature requests: what underlying problem are you trying to solve with this feature?

filtering a package group query by an attribute:

if I rerun the same query from above with `--output xml` then I get:

```xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<query version="2">
    <package-group location="~/path/o/some/BUILD:7:14" name="//xyz:my-group-target">
        <list name="includes"/>
        <list name="packages">
            <string value="some/..."/>
            <string value="more/..."/>
            <string value="things/..."/>
        </list>
    </package-group>
</query>
```

going by that I should be able to:

`query 'attr("packages", ".*", kind("package group", //...:*))' --output xml`

but it yields:
```bash
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<query version="2"/>
INFO: Empty results
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

se the query above: `attr("packages", ".*", kind("package group", //...:*))`

### What operating system are you running Bazel on?

OSX (Big Sur, via nixos)

### What's the output of `bazel info release`?

`release 3.7.0`

`bazel version` yields:

```
Build label: 3.7.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Oct 20 13:31:07 2020 (1603200667)
Build timestamp: 1603200667
Build timestamp as int: 1603200667
```

cc @uri-canva

**Comment by meisterT** [comment]
This is unfortunately how `attr` works:

From https://docs.bazel.build/versions/master/query.html#attr:
> The attr(name, pattern, input) operator applies a filter to a set of targets, and **discards targets that are not rules**

A `package_group` is not a `rule`.

**Comment by joscha** [comment]
Is there an alternative of running this query? And if it is not supported to do this, would it make sense to error instead of just returning nothing and exiting zero?

**Comment by meisterT** [comment]
I am not aware of an alternative (other than parsing the output and filtering on your own).

> And if it is not supported to do this, would it make sense to error instead of just returning nothing and exiting zero?

Unfortunately, no. The query operators operate on their input, e.g. a set of targets, without knowledge of how that set was produced.
