### ISSUE TITLE
`--symlink_prefix` leaves `bazel-<WORKSPACE_NAME>` and `bazel-out` in the root of the workspace

### ISSUE THREAD

**Issue by menny** [bazelbuild/bazel#1294]
Running `bazel build app --symlink_prefix=/`will not produce any symlinks, but running `bazel build app --symlink_prefix=/tmp/` or `bazel build app --symlink_prefix=tmp/` will produce some of the links at the requested path, but will leave `bazel-<WORKSPACE_NAME>` and `bazel-out` at the root of the workspace.

**Comment by davidstanke** [comment]
Closing this; see #3796 for a more recent discussion of this same issue, with explanation for why it happens.
