### ISSUE TITLE
Update l.gcr.io/google/bazel:latest bazel docker image to bazel version 4.0.0

### ISSUE THREAD

**Issue by bjacklyn** [bazelbuild/bazel#12952]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

 `l.gcr.io/google/bazel:latest` is currently using bazel 3.5.0, let's get this upgraded to 4.0.0

### Feature requests: what underlying problem are you trying to solve with this feature?

Wanting to use bazel 4.0.0

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ docker run l.gcr.io/google/bazel:latest --version
bazel 3.5.0
```

### What operating system are you running Bazel on?

Ubuntu 20.04

### What's the output of `bazel info release`?

N/A

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

No

**Comment by philwo** [comment]
We're tracking this in https://github.com/bazelbuild/continuous-integration/issues/1060.
