### ISSUE TITLE
Java annotation processors do not have access to resources

### ISSUE THREAD

**Issue by lgalfaso** [bazelbuild/bazel#12964]
When executing a Java annotation processor, it does not have access to the resources referenced by the originating class.

```
java_library(
    name = "processor",
    srcs = ...,
)

java_plugin(
    name = "processor_plugin",
    deps = [":processor"],
#    generates_api = 1,  # tried with and without this.
)

java_library(
    name = "annotation_processor",
    exported_plugins = [":processor_plugin"],
    exports = [":processor"],
)

java_library(
    name = "res",
    resources = ...,
)

java_library(
    name = "target",
    srcs = ...,
    deps = [":res"],
)
```

Where `target` contains a class that has an annotation that makes reference to a resource in `:res`.

The resources are attempted to be loaded doing
```
processingEnv.getFiler().getResource(StandardLocation.CLASS_OUTPUT, "", fileName);
```
and if that fails, with
```
processingEnv.getFiler().getResource(StandardLocation.CLASS_PATH, "", fileName);
```

At first, it looks like the issue was that in the classpath there were only java headers/interfaces present, so tried with
- Adding `--nojava_header_compilation --nouse_ijars`
- Adding `--nojava_header_compilation --nouse_ijars` and creating a dummy class in `:res`
None worked.

Using bazel release 4.0.0-homebrew

**Comment by comius** [comment]
@lgalfaso What does it fail with? It seems that you pasted wrong text into the description.

Could you provide also sample code for processor? Do I understand correctly that you're accessing downstream resources from the processor? If I understand this correctly - this looks like a fishy design to me - could you support it with some use cases or an OSS annotation processor that does this?

**Comment by whs** [comment]
I believe I might be affected by this with [pf4j](https://github.com/pf4j/pf4j/blob/d18706e9d0efec02e6b543a2c3f1110f260ab8ec/pf4j/src/main/java/org/pf4j/processor/LegacyExtensionStorage.java#L67)

```
java_plugin(
	name="pf4j_plugin",
	processor_class = "org.pf4j.processor.ExtensionAnnotationProcessor",
	deps = [
		"@maven//:org_pf4j_pf4j",
	],
)

java_library(
	name = "pf4j",
	exported_plugins = [":pf4j_plugin"],
	visibility = ["//:__subpackages__"],
	exports = [
		"@maven//:org_pf4j_pf4j",
	],
)

// in app folder
kt_jvm_library(
	name = "provider",
	srcs = glob(["src/main/kotlin/**/provider/*"]),
	visibility = ["//visibility:public"],
	deps = [
		"//:kotlinx_serialization",
	],
)
```

I expect to have `META-INF/extensions.idx` in the resulting jar but it does not show up

**Comment by Zetten** [comment]
I think this issue also affects the Spring Boot Configuration Processor.

I'm using a `java_plugin` with processor class `org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor` (from`org.springframework.boot:spring-boot-configuration-processor:2.5.3`). The plugin correctly finds my `@ConfigurationProperties` and generates `META-INF/spring-configuration-metadata.json` in my jar.

According to https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html#configuration-metadata.annotation-processor.adding-additional-metadata we can add some custom hand-written properties in a resource resource `META-INF/additional-spring-configuration-metadata.json`, which should be merged into the main metadata file during compilation. But this doesn't happen - both files are in the resulting jar, unmodified.

The documentation suggests:
> If you are using an additional-spring-configuration-metadata.json file, the compileJava task should be configured to depend on the processResources task, as shown in the following example:
> 
> ```groovy
> compileJava.inputs.files(processResources)
> ```
>
> This dependency ensures that the additional metadata is available when the annotation processor runs during compilation.

But it's not clear how to achieve this with Bazel. Perhaps a solution is to provide another `java_plugin` rule attribute like `generates_api`; something like `process_java_resources`?

I've created an example repo with both Gradle (passing) and Bazel (failing) configurations: https://github.com/Zetten/bazel-java-annotation-processor-resources.

**Comment by factuno-db** [comment]
Ran into this issue as well. My current workaround is (1) to expose the resources in question to java_plugin via its "resource_jars" attribute and (2) to let the annotation processor search for the resources within StandardLocation.ANNOTATION_PROCESSOR_PATH. This, of course, requires a separate java_plugin declaration for each library that needs processing. Ugly workaround, but works for me.

**Comment by sgowroji** [comment]
We are closing this issue w.r.t the above [comment](https://github.com/bazelbuild/bazel/issues/14095#issuecomment-978200548) And thank you for sharing your [workaround](https://github.com/bazelbuild/bazel/issues/12964#issuecomment-1036635296). This will be useful to the community who are looking for similar enhancement.

**Comment by bdleitner** [comment]
Please reconsider.  Needing a separate `java_plugin` declaration for library that needs processing as opposed to being able to use `exported_java_plugin` on the build target for the annotation makes things unwieldy _at best_.  As noted, it's an "ugly" workaround.

**Comment by cushon** [comment]
There's some related history in internal issue b/198685781.

One of the options discussed is to do with with a separate attribute on library rules that would make files available to annotation processing, e.g. `java_library.plugin_data`.

**Comment by softprops** [comment]
does anyone have a working demo of how to make this possible available on github?

I have a usecase I'd like to scan a set of annotations at compile time collect the data into a resource which another library can then consume. the path to accomplish that with bazel semantics + sandboxing is still a bit unclear

**Comment by fmeum** [comment]
@bazelbuild/triage not stale
