### ISSUE TITLE
Gzipped profiles don't load in chrome

### ISSUE THREAD

**Issue by jdai8** [bazelbuild/bazel#12965]
### Description of the problem / feature request:
Gzipped profiles (e.g. `command.profile.gz`) don't load in `chrome://tracing`, with this error in the console:
```
Uncaught (in promise) RangeError: Invalid typed array length: 4096
    at new Uint8Array (<anonymous>)
    at HTMLElement.isProtobufTrace_ (tracing.js:5570)
    at HTMLElement.setActiveTrace (tracing.js:5568)
    at HTMLElement.<anonymous> (tracing.js:5577)
```

### Feature requests: what underlying problem are you trying to solve with this feature?
N/A

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
1. Run a build (I used https://github.com/bazelbuild/examples). I ran `bazel build :ProjectRunner` in the java tutorial. Loading `command.profile.gz` works.
2. Run another build. Loading `command.profile.gz` fails with the error above.
3. Run a build with `--profile some_non_gzipped_file`. Loading it works.

The first build after a `bazel clean` also works, so I'm guessing there's some corrupt state.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

`release 4.0.0`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.
N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
```
https://github.com/bazelbuild/examples
4183fc709c26a00366665e2d60d70521dc0b405d
4183fc709c26a00366665e2d60d70521dc0b405d
```
###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Chrome version: `Version 88.0.4324.96 (Official Build) (x86_64)`

I'm happy to email a problematic `command.profile.gz` if it's helpful.

**Comment by pcjanzen** [comment]
IIRC this is an error in chrome, not in bazel: gzipped files smaller than 4k don't work.

**Comment by jdai8** [comment]
Confirmed that the files were smaller than 4k, and unzipping them works. Thanks @pcjanzen !
