### ISSUE TITLE
[request] robust way to specify LD_LIBRARY_PATH for java/javac

### ISSUE THREAD

**Issue by divanorama** [bazelbuild/bazel#12978]
### Description of the problem / feature request:

Bazel builds aren't fully hermetic in many cases
- some build rules rely on `#!/usr/bin/env bash` + common utilities
- repository rules rely on host commands (env, git, gcloud, go, tar, zip, python, grep, which, sed, bash, node,...)
- compilers (like remote_jdk11 javac) may be dynamically linked and relying on host libraries (like libz.so.1)
- dynamic linkers may rely on ld.so.cache in default locations, or shared libraries in default locations (in case executable doesn't specify search paths, which it usually doesn't for non-bundled dependencies)

But on the other hand bazel tries to cleanup environment variables and sandbox actions, which in turn may break non-hermetic cases, not always with an easy fix.
- `--action_env` may not work for rules without `use_default_shell_env=True` including some built-in rules (like DumpPlatformClassPath https://github.com/bazelbuild/bazel/blob/667ae2adc793d376267c85e81ca6be600a4f2fbd/tools/jdk/default_java_toolchain.bzl#L222)
- `--repo_env` seems to cover repo rules
- `--run_under` doesn't seem to work for build or repo rules (could try `--run_under='env PATH=.. LD_LIBRARY_PATH=..'`)
- `--sandbox_add_mount_pair` refuses to create paths, only overrides existing
- supplying per-host toolchains feels non-hermetic and code-intrusive (can't just edit `.bazelrc`, also need to patch bzl code in the project)
- `--experimental_sandboxfs_path` may be an option, but may not cover repository rules(?) and requires patching sandboxfs

As an initial crude fix, maybe being able to non-conditionally set/extend PATH&LD_LIBRARY_PATH for rules&actions would work.

### Feature requests: what underlying problem are you trying to solve with this feature?

Be able to build bazel projects (on NixOS) without a lot of patching bazel or doing brittle host (or container) setup.

Starting with semi-hermetic solutions like `--action_env` sounds ok for a start
- remote cache won't be easily reused, but local cache will work
- in case with NixOS setting `*PATH=/nix/store/looonghash-smth/{bin,lib}` is actually safe to cache and should be reproducible, assuming other bits are

Ideally of course it would be nice to be able to specify all dependencies explicitly, at least in built-in and core rules. If not as build targets/bazel dependencies, then at least like a `./configure` step _with_ ability to always easily specify custom paths.

### What operating system are you running Bazel on?

NixOS

### What's the output of `bazel info release`?

3.3.1, but should apply to 4.0.0 too

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

NixOS packages

###  Have you found anything relevant by searching the web?

NixPkgs already have few patches to bazel code like
- replacing `/usr/bin/env something` with `nix path of something`
- making bazel shell rules use patched bash that has special default search path (bash/env/glibc go to /bin, /usr/bin and such when PATH is empty; that won't help finding binaries on NixOS, patch is to add few common utils to bazel-bash default search path)
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/build-managers/bazel/bazel_3/default.nix#L324

There's a `buildFHSUserEnv` helper in NixPkgs to create FHS sandboxes/containers https://nixos.org/manual/nixpkgs/stable/#sec-fhs-environments . `buildFHSUserEnv` + `..._env=PATH=...` + `..._env=LD_LIBRARY_PATH=...` may be used to make most of rules work in NixOS, but FHS environment feels like an overkill

- sandbox filesystem customization request https://github.com/bazelbuild/bazel/issues/6994
- on actions ignoring *_env https://github.com/bazelbuild/bazel/issues/3320
- also on sandbox filesystem https://github.com/bazelbuild/bazel/issues/7313
- non-hermiticity wrt system libs https://github.com/bazelbuild/bazel/issues/4558

**Comment by divanorama** [comment]
Another a bit involved case is https://github.com/bazelbuild/rules_nodejs/blob/stable/internal/providers/node_runtime_deps_info.bzl#L148 - here a rule does _some_ `env` setup, so it can't(?) even apply `use_default_shell_env=True` or `--action_env=...`/`--repo_env=...`. When it is used to call typescript compiler wrapper `tsc.sh` which has `#!/usr/bin/env bash` + the script uses tools like grep, which in turn assumes `env - A=B C=D bash -c grep` works on the host (which isn't necessarily true on NixOS with/without FHS wrapper)

**Comment by divanorama** [comment]
One more thing that can negate fix attempts is that rules can disable sandboxing (I'd say an .bazelrc option to enforce sandboxing can be useful) via `execution_requirements` or `tags`, also not very clear if fixes via sandbox setup would apply to process workers when `--worker_sandboxing` isn't set

**Comment by meisterT** [comment]
cc @larsrc-google

**Comment by larsrc-google** [comment]
There's an implicit fallback from sandboxed to local that since recently can be controlled with the `--[no]legacy_local_fallback` flag. I've not yet managed to switch the default due to some subtle test interactions with the `local` tag.

Workers without `--worker_sandboxing` would indeed not benefit from any fixes to the sandbox setup.
