### ISSUE TITLE
what's project root path variable in bazelrc file

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/bazel#12975]
bazel 3.7.2
I want to generate gperftools cpu perf file under project root directory(contains WORKSPACE file), so I put
build --test_env="CPUPROFILE=%workspace%:prof.out"  in .bazelrc file, but bazel didn't generate it, If I change 
build --test_env="CPUPROFILE=%workspace%:prof.out" to build --test_env="CPUPROFILE=/path/to/project_root_dir/prof.out", bazel generate cpu profile file, so how can I use project root directory variable in bazelrc file ?

**Comment by oquenchil** [comment]
Please ask on StackOverflow or bazel-discuss.
