### ISSUE TITLE
The override_repository path is parsed incorrectly if it contains equals signs

### ISSUE THREAD

**Issue by odisseus** [bazelbuild/bazel#12987]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

If the path to the repository contains `=` (e. g. `/foo/bar=/baz`), Bazel fails to parse it properly.

### Feature requests: what underlying problem are you trying to solve with this feature?

Allow to store the local repository under a path that contains equals signs.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
```
$ bazel build --override_repository=quux=/foo/bar=/baz //src:bazel-dev
ERROR: While parsing option --override_repository=quux=/foo/bar=/baz: Repository overrides must be of the form 'repository-name=path'
```

### What operating system are you running Bazel on?

Fedora 31

### What's the output of `bazel info release`?

```
$ bazel info release
release 3.7.1
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
$ git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
https://github.com/bazelbuild/bazel.git
2910d3d860044ef5fb0989306bafebc1c5545e42
2910d3d860044ef5fb0989306bafebc1c5545e42
```

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

No

**Comment by sventiffe** [comment]
@jin unsure how to route this bug and PR. Are you familiar with that code? Any suggestions?

**Comment by jin** [comment]
I routed this to the external deps area, since it deals with repositories.

**Comment by odisseus** [comment]
Is there any chance that this issue will be resolved?
