### ISSUE TITLE
pseudo actions omitted from Target.actions

### ISSUE THREAD

**Issue by shahms** [bazelbuild/bazel#12985]
### Description of the problem / feature request:

When accessing Target.actions from an aspect, pseudo actions are absent.

### Feature requests: what underlying problem are you trying to solve with this feature?

Replacing extra_actions with aspects.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Given BUILD:
```
# BUILD
action_listener(
    name = "py_listener",
    extra_actions = [":debug"],
    mnemonics = ["Python"],
)

extra_action(
    name = "debug",
    cmd = "echo 'Action Executed' > $(output $(ACTION_ID).txt)",
    out_templates = [
        "$(ACTION_ID).pb",
    ],
)

py_library(
    name = "library",
    srcs = ["library.py"],
)
```

And aspect.bzl
```
def _impl(target, ctx):
    print([a.mnemonic for a in target.actions])
    return []

debug = aspect(
    implementation = _impl,
)
```

Running the commands yields:
```
$ bazel build --experimental_action_listener=//dummy:py_listener //dummy:library
...
$ cat $ cat bazel-out/k8-fastbuild/extra_actions/dummy/debug/dummy/5a77db9045fb63dcc930dd78ea2df50dabf4ae0aabadcd8176ede0cbff2b5c1e.txt
Action Executed
$ bazel build --aspectc=//dummy:aspect.bzl%debug //dummy:library
$ bazel build --aspects=dummy/aspect.bzl%debug //dummy:library
INFO: Build option --experimental_action_listener has changed, discarding analysis cache.
DEBUG: /usr/local/google/home/shahms/src/kythe/dummy/aspect.bzl:2:10: []
...
$
```
(Note, in particular, the empty list of action mnemonics in the DEBUG line)
### What operating system are you running Bazel on?

Ubuntu

### What's the output of `bazel info release`?

release 4.0.0

**Comment by shahms** [comment]
It looks like this is somewhat intentional:
```
  void addPyExtraActionPseudoAction() {
    if (ruleContext.getConfiguration().getActionListeners().isEmpty()) {
      return;
    }
```

Just removing that check fixes the issue, although I'm not sure about other impact it may have.

**Comment by comius** [comment]
I believe pseudo actions were added just to support `extra_actions` and will be removed.

Is there something you can't access using an aspect? The info should be there.

**Comment by shahms** [comment]
When migrating from `extra_actions` to aspects, it's simplest to avoid changing too much at once and there remain rule implementations which only expose relevant information via pseudo actions (which were, indeed, only added to support `extra_action`). I don't think it's particularly critical that they remain, but it's a stumbling block when migrating.

**Comment by comius** [comment]
Ah ok, if it helps you move faster, please submit a PR (maybe you need to update Starlarkified calls as well). But consider pseudo actions deprecated.

**Comment by shahms** [comment]
At this point I believe we've already worked around the problem, but it was a speedbump to do so.
