### ISSUE TITLE
XcodeConfigInfo.macosMinimumOsVersion is incorrectly set for host configuration

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/bazel#12988]
### Description of the problem / feature request:

When building a target with the host configuration, the `macosMinimumOsVersion` is being set to the SDK version instead of what is set for `--macos_minimum_os`. The relevant lines are:

https://github.com/bazelbuild/bazel/blob/24c980b6d4adef456cf4b4f84ac3b8ec4580b172/src/main/java/com/google/devtools/build/lib/rules/apple/XcodeConfig.java#L149-L152

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build a `genrule` that has a `swift_binary` `tool`, with `--macos_minimum_os` lower than the SDK version (say `10.15` when using Xcode 12.4.0, which has its SDK version at `11.1`). The tool will have an incorrect `-target` (`x86_64-apple-macosx11.1` for the example given).

### What operating system are you running Bazel on?

macOS 11.2.1

### What's the output of `bazel info release`?

release 4.0.0

###  Have you found anything relevant by searching the web?

Nothing.

**Comment by keith** [comment]
I think the issue is that the minimum version isn't set for the host configuration here? https://github.com/bazelbuild/bazel/blob/660f5b2cf36fbd75908cf7c93cc59d98ee092eb2/src/main/java/com/google/devtools/build/lib/rules/apple/AppleCommandLineOptions.java#L456-L468

But maybe that's intentional

**Comment by brentleyjones** [comment]
If it's intentional, could we get a `--host_minimum_os` flag? Hopefully it's not intentional though 😄.

**Comment by brentleyjones** [comment]
I just realized this might be semi-intentional, since we only need to support a minimum OS of the host, not any lower. In my example though, by using Xcode 12.4, the `macOsSdkVersion` is `11.1`, while my OS version (in a previous test) was `10.15`. Ideally we wouldn't try targeting an OS version _higher_ than the current one?

**Comment by keith** [comment]
> minimum OS of the host

To ensure caching across developers even this isn't particularly true is it? I get that you won't back deploy the binary directly, but it could result in a different output

**Comment by brentleyjones** [comment]
>To ensure caching across developers even this isn't particularly true is it? I get that you won't back deploy the binary directly, but it could result in a different output

True. So then I would want to set a minimum OS version that might be lower than the OS version of the host.

**Comment by keith** [comment]
https://github.com/bazelbuild/bazel/pull/13001

**Comment by aiuto** [comment]
cc @susinmotion  Any thoughts on #13001?

**Comment by susinmotion** [comment]
It's in good hands with trybka and allevato!
