### ISSUE TITLE
aquery produces invalid `proto`, but valid `textproto`

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#12984]
We have a case where we run an aquery like this:

```
bazel aquery "mnemonic(SwiftCompile, deps(set(A B)))" --output=proto > /tmp/foo.proto
```

Where the output proto cannot be parsed:

```
protoc --decode_raw < /tmp/foo.proto
```

It also cannot be parsed via C++ or SwiftProtobuf.

But if you change it to output `textproto` instead, it can successfully be parsed with SwiftProtobuf.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I can send over the proto / textproto via slack, but don't want to attach them here.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 4.0.0

**Comment by joeleba** [comment]
I've received the files from @keith.

**Comment by carolosfw** [comment]
I have also seen a similar issue with Bazel 5.0.0 strangely it only affects Mac OS and only a small percentage of Mac OS machines not all.
