### ISSUE TITLE
missing method `to_json` on `struct` type

### ISSUE THREAD

**Issue by dududko** [bazelbuild/bazel#12983]
### Description of the problem / feature request:

Missing method `to_json` on `struct` type. This is a breaking change which is not documented, and it results in build failure of many bazel extensions including `rules_docker`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
rule.bzl
```
def  my_rule_impl(ctx):
    s = struct()
    print(s.to_json())

my_rule = rule(
    implementation = my_rule_impl,
)
```

BUILD.bazel
```
load("//:rule.bzl", "my_rule")

my_rule(
    name = "my_target"
)
```

`bazel build //:my_target`

### What operating system are you running Bazel on?

macOS Catalina 10.15.7

### What's the output of `bazel info release`?

release 4.0.0

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

```
bazel build //...
(19:10:58) INFO: Invocation ID: 724bb149-9541-4e98-b610-e620c46a1572
(19:10:59) INFO: Current date is 2021-02-09
(19:11:39) INFO: SHA256 (https://golang.org/dl/?mode=json&include=all) = 7008033e0ab99ec03d6eb9593445b9a94bec029ac91450ffb4318c059ca427dc
(19:12:15) ERROR: /Users/dududko/myproject/chart/frontend/test/test-frontend/BUILD.bazel:14:16: in container_layer_ rule //chart/frontend/test/test-frontend:layer:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_dududko/14485085ed56a1ffbc0109316724dc49/external/io_bazel_rules_docker/container/layer.bzl", line 232, column 42, in _impl
		unzipped_layer, diff_id = build_layer(
	File "/private/var/tmp/_bazel_dududko/14485085ed56a1ffbc0109316724dc49/external/io_bazel_rules_docker/container/layer.bzl", line 146, column 46, in build_layer
		ctx.actions.write(manifest_file, manifest.to_json())
Error: 'struct' value has no field or method 'to_json'
Available attributes: debs, empty_dirs, empty_files, empty_root_dirs, files, symlinks, tars
(19:12:15) ERROR: Analysis of target '//chart/frontend/test/test-frontend:layer' failed; build aborted: Analysis of target '//chart/frontend/test/test-frontend:layer' failed
(19:12:15) INFO: Elapsed time: 76.346s
(19:12:15) INFO: 0 processes.
(19:12:15) FAILED: Build did NOT complete successfully (259 packages loaded, 8837 targets configured)
    Fetching @com_github_aws_aws_sdk_go; fetching 25s
    Fetching @io_cirello_dynamolock; fetching 25s
    Fetching @com_github_stretchr_testify; fetching 25s
    Fetching @com_github_pelletier_go_toml; fetching 24s
```

**Comment by dmivankov** [comment]
https://github.com/bazelbuild/bazel/commit/258dfe95f2c8ebb1a479eed3411f64b100c93de2
is `--incompatible_struct_has_no_methods` on?

**Comment by dmivankov** [comment]
Shouldn't be on by default I think, looking at 4.0.0 release info https://blog.bazel.build/2021/01/19/bazel-4-0.html#starlark

**Comment by dududko** [comment]
I did not enable this option. I can confirm that build is successful if this option is explicitly disabled `--incompatible_struct_has_no_methods=false`.

**Comment by brandjon** [comment]
Are you using `--all_incompatible_changes`? That would turn it on. Also check your bazelrc file.

**Comment by dududko** [comment]
@brandjon yes I do
I totally forgot about this option. 
Sorry for you time, you can close this ticket.
