### ISSUE TITLE
Autoconfigure compiler system includes

### ISSUE THREAD

**Issue by zrlk** [bazelbuild/bazel#130]
We're using clang to build our code. clang has a different set of `cxx_builtin_include_directory` entries than are included in the default CROSSTOOL file (and these differ from version to version). We need to autodetect these entries in our one-time setup script right now, but it would be nice if Bazel would handle this as part of the normal cc_* rules.

For reference, the code we use for autodetection is at the bottom of  https://github.com/google/kythe/blob/master/setup_bazel.sh .

**Comment by damienmg** [comment]
There is no plan to put that kind of autodetection directly in the cc_* rules but I am working on something similar I will keep you posted when I make significant progress.

**Comment by hanwen** [comment]
We could have our standard CROSSTOOL be generated in compile.sh.

**Comment by damienmg** [comment]
Hi this now exists. See https://groups.google.com/d/msg/bazel-discuss/MSunz2ZUOq0/U5tE7uQLJQAJ
