### ISSUE TITLE
Clarify wording around optional attributes in cpp tutorial

### ISSUE THREAD

**Issue by dabrahams** [bazelbuild/bazel#13004]
Documentation URL: https://docs.bazel.build/versions/master/tutorial/cpp.html

This text is confusing.  In context, the 2nd sentence reads like it's supposed to be demonstrating an optional attribute, but it doesn't go on to say that srcs is optional (as far as I can tell, it's optional as far as bazel is concerned, but the build fails if you don't supply it, so it probably doesn't make a good example).

> The attributes in the target explicitly state its dependencies and options. While the name attribute is mandatory, many are optional. For example, in the hello-world target, name is self-explanatory, and srcs specifies the source file(s) from which Bazel builds the target.

Sorry, but I can't offer a patch, because I encountered it while trying to learn bazel.  I'm not sure what to say that would be accurate.

**Comment by dabrahams** [comment]
And no, I can't offer a patch, because I encountered it while trying to learn bazel.  I'm not sure what to say that would be accurate.

**Comment by communikit** [comment]
Seems to me that the sentence "While the name attribute is mandatory, many are optional. " implies that srcs is one of the optional attributes. The next sentence just goes on to explain what the given example in the tutorial means.

We can maybe try and make the wording a little clearer here.
