### ISSUE TITLE
Build API Roadmap: discussion

### ISSUE THREAD

**Issue by comius** [bazelbuild/bazel#13008]
This is a non-technical issue just meant as a connection point for discussion, thoughts, questions, concerns, etc. about Bazel's Build API work as prioritized in https://www.bazel.build/roadmaps/build-api.html.

It's also a step toward integrating our project workflow deeper into the Bazel community.

My current thinking is to maintain one of these issues and roadmaps for each year. But I'm open to suggestions for other venues like bazel-dev, etc.

I also want to have a dedicated GitHub issue for each individual roadmap item. As of this writing we're
about halfway there. So individual priorities can be discussed on their own threads and this thread can cover big picture stuff.

**Comment by erenon** [comment]
HTTP 404 https://www.bazel.build/roadmaps/build-api.html

**Comment by comius** [comment]
> HTTP 404 https://www.bazel.build/roadmaps/build-api.html
https://github.com/bazelbuild/bazel-website/pull/292
The website needs some time to be refreshed and I wanted to have a link to the Issue in the doc as well.

**Comment by dws** [comment]
How is this work coming along? It would be great to have an update to https://bazel.build/roadmaps/build-api.html
