### ISSUE TITLE
Simplify description of workspace on Concepts page

### ISSUE THREAD

**Issue by dabrahams** [bazelbuild/bazel#13023]
Documentation URL: https://docs.bazel.build/versions/master/build-ref.html

> A workspace is a directory on your filesystem that contains the source files for the software you want to build, as well as symbolic links to directories that contain the build outputs.

This would seem to suggest (since I happen to know WORKSPACE files are typically checked in to project repositories) that it would be very difficult to set up a build of a read-only copy of a project's source, because I'd need to at least write those symlinks to the build output directories.  However, https://docs.bazel.build/versions/master/guide.html suggests that you _can_ build from a completely read-only filesystem.  Which is it? (please resolve this apparent contradiction in the docs)

**Comment by jin** [comment]
I would suggest adding `Bazel-generated` so that it reads `Bazel-generated symbolic links`. We can also omit that part altogether, since it's not necessary for users to know about the `bazel-*` symlink shortcuts at this time. cc @communikit

**Comment by communikit** [comment]
It may be simpler to omit that part altogether here, I can make an update.
