### ISSUE TITLE
Unable to build //src/test/shell/bazel:doc-srcs at head

### ISSUE THREAD

**Issue by janakdr** [bazelbuild/bazel#1303]
Synced to c1b417549cf4ba719662f7562e99e807c606eae7, I get:
$ bazel build //src/test/shell/bazel:doc-srcs
INFO: Found 1 target...
ERROR: /Users/janakr/bazel/src/test/shell/bazel/BUILD:137:1: Executing genrule //src/test/shell/bazel:doc-srcs failed: bash failed: error executing command /bin/bash bazel-out/local-fastbuild/genfiles/src/test/shell/bazel/doc-srcs.genrule_script.sh: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
bazel-out/local-fastbuild/genfiles/src/test/shell/bazel/doc-srcs.genrule_script.sh: line 2: /usr/bin/zip: Argument list too long
Target //src/test/shell/bazel:doc-srcs failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.558s, Critical Path: 0.06s

**Comment by hermione521** [comment]
@hhclam ＠kchodorow Can you look at this? Thanks.
