### ISSUE TITLE
Link to target patterns from labels section

### ISSUE THREAD

**Issue by dabrahams** [bazelbuild/bazel#13030]
Documentation URL: https://docs.bazel.build/versions/master/build-ref.html

Says

> Every label uniquely identifies a target

But I have learned that I could write

```
bazel test //...:all
```

to build and run all test targets.  Does that mean `//...:all` is not a label?

There are actually two problems here:
1. I could not find the command above by reading any of the tutorials; had to learn by pestering my teammates.  If someone has given me a bazel project and told me how to set up the tooling, a very common first step is build-and-test-everything, and the fact that it was hard to find out how to do that makes bazel and bazel-based projects less accessible.
2. Once the above is corrected,  the statement about uniquely identifying targets will be confusing to many more people without some explanation in the concepts section of what the `//...:all` syntax actually is.

**Comment by communikit** [comment]
Linking https://docs.bazel.build/versions/master/guide.html#specifying-targets-to-build in the label section would probably help! Thanks @jin
