### ISSUE TITLE
Update wording around build tool error

### ISSUE THREAD

**Issue by dabrahams** [bazelbuild/bazel#13035]
Documentation URL: https://docs.bazel.build/versions/master/build-ref.html

> If, by mistake, you refer to testdepot.zip by the wrong label, such as //my/app:testdata/testdepot.zip or //my:app/testdata/testdepot.zip, you will get an error from the build tool saying that the label "crosses a package boundary". 

This is confusing; it makes it sound as though it's illegal to reference a target in a different package.  Also, I was unable to reproduce the “crosses a package boundary” message, myself.

**Comment by communikit** [comment]
This section points out incorrect semantics.

Correct: 

- //my/app/testdata:testdepot.zip 

Incorrect:

- //my/app ":" testdata "/" testdepot.zip
- //my ":" app/testdata "/" testdepot.zip

I think we could just leave the documentation at ".... you will get an error from the build tool".

**Comment by dabrahams** [comment]
Well, that's only true if no other target exists with that label, right?  Otherwise, you end up referring to the other target.

I should think it goes without saying at this point in the documentation that if you mess up in a way that bazel can detect, e.g. by using an invalid target name, it will give you an error.  So, FWIW, I think the doc would be better with this whole sentence removed.

**Comment by aiuto** [comment]
I think this tip is helpful as is.

In the best of all worlds, error messages would explain the likely fix for the error.
That is not always possible becuase the explanation might be long. In that case, you want a concise message that you can look up in documentation for a full explanation.
In this case, when you do get crosses a package boundary errors, you don't really know what to do.
Someone could search the docs for the message and get the explanation here.

**Comment by dabrahams** [comment]
To me that sounds like what a FAQ is for.  Speaking as an actual user of the documentation, trying to understand the system: the tip as is, in its current location, doesn't serve the purpose of that part of the documentation, which is to clearly define concepts and terms.  Furthermore, because of the incorrect implication that cross-package references are illegal, if I got that error during use and Google led me to this part of the document, I would *at best* decide that this part of the doc was to be ignored, and at worst, be confused.

**Comment by gregestren** [comment]
I think this remains valuable information: there's a legitimate point being made, and it's subtle enough that I wouldn't expect people to understand on first experience.

As to where it belongs, no idea. @floriographygoth - any ideas? It's referring to a subtle error you can experience w.r.t. a core concept (referencing a label). But it's probably only relevant when people get build errors, vs. the first time reading about the concept. Even more broadly, what's your take on FAQs? Is it useful to have some Bazel-wide FAQ inspired by known problem cases?

Technically, I'm not sure if we're all talking about the same thing. To be explicit:

```
$ cat t/BUILD
# empty
$ cat t/subpackage/BUILD
cc_binary(
    name = "bin",
    srcs = ["bin.cc"],
)

$ bazel query //t:subpackage/bin
ERROR: no such target '//t:subpackage/bin': target 'subpackage/bin' not declared in package 't' defined by /bazel/t/BUILD

$ bazel query //t/subpackage:bin
//t/subpackage:bin
```

This involves the concept of crossing a package boundary, even though the error doesn't mention it. Also see relevant code at https://github.com/bazelbuild/bazel/blob/45d82cadb52f9fa0ee23cf2c45eb1cd149587852/src/main/java/com/google/devtools/build/lib/skyframe/RecursiveFilesystemTraversalFunction.java#L192

Oh, if you reference the target incorrectly from a target in `t/BUILD`, the error's a bit clearer:

```
ERROR: /bazel/t/BUILD:1:10: Label '//t:subpackage/bin' is invalid because 't/subpackage' is a subpackage;
perhaps you meant to put the colon here: '//t/subpackage:bin'?
```

**Comment by dabrahams** [comment]
It's your project, but if it was me, I'd accept https://github.com/bazelbuild/bazel/pull/13079 while this issue gets figured out.  The text that is currently there doesn't begin to express the nuance @gregestren outlined above, and is just confusing in the context where it appears.  I don't expect I have anything further to say here.

**Comment by gregestren** [comment]
What I didn't appreciate in my earlier comment is the immediately preceding code block and paragraph show the same point. So I get the redundancy you're arguing, and I'm sold on your point.

What would make this even clearer, IMO, would be to break up the "Label" section further. It's wall-o-texty as is and the whole section doesn't fit on my screen. This specific issue (package boundaries) is focused enough to merit its own sub-section, and can help with the discoverability concerns some of us have expressed.

@dabrahams I'm not asking to condition your PR on all that. @communikit do you have any thoughts on ongoing options to further ease the organization on this particularly dense page?

**Comment by communikit** [comment]
We could potentially rework the Labels section with different sub-sections for readability. Is there enough there to warrant a separate page for Labels under the Core Concepts section? 

What about a "types of errors" section to address some of these subtle errors one can run into?

**Comment by gregestren** [comment]
I suspect not a separate page. I honestly don't know what the right priority is for deeper refactoring. It's just a broader thought.

For right now, would you support me merging this PR as-is? (just a deletion in the interest of removing redundant statements). I agree with @dabrahams 's point now.

**Comment by communikit** [comment]
Yes, refactoring can be a separate conversation. We can merge the PR.
