### ISSUE TITLE
Tests should warn if size doesn't match memory usage.

### ISSUE THREAD

**Issue by adam-azarchs** [bazelbuild/bazel#13036]
### Description of the problem / feature request:

Currently, if a test's timeout is inappropriate compared to its actual duration, a warning is printed indicating that the timeout is reduced.  Great!  There should also be a similar warning if a test's memory usage is far off from the [memory usage expected for its size](https://docs.bazel.build/versions/master/be/common-definitions.html#test.size).

While admittedly perfect memory monitoring under linux is a bit of a mess (rusage reports the maximum of the rss high-water-marks of each process across transitively waited-on child processes, not the high-water-mark of the sum of rss, and it's not even clear that the latter would be accurate if the processes share many pages), rusage is at least good enough to indicate when a test is consuming more than it ought to for its given size.

### Feature requests: what underlying problem are you trying to solve with this feature?

Our code base has a lot of unit tests which were written by people who are at best grudging in their knowledge of bazel.  Quite a few of them use a lot of memory (~1gb), but do not specify a `size` (or specify it based on the required timeout with no consideration for memory consumption).  This sometimes OOMs our CI because it attempts to run too many of these in parallel. 
 There's little instrumentation to easily detect whether a test is misbehaving in this way and needs to have its `size` increased.

### What operating system are you running Bazel on?

linux

### What's the output of `bazel info release`?

release 4.0.0

**Comment by aiuto** [comment]
This is essentially unsolvable purely within Bazel.  We would need the test infrastructure for each language to support the reporting back to us.  Within Google, we are considering replacing test_size with something more precise for this and other reasons.

**Comment by adam-azarchs** [comment]
I'm not sure I understand - the builder executes the test process as a child.  When it waits on that child process, it gets the `rusage` back.  There's nothing there that's more language-specific than the timeouts.

**Comment by aiuto** [comment]
With sharded tests, it would be useful to have a way to be able to say an individual test has a time or memory limit. And then you want to aggregate them up into the appropriate class execution environment based on how you shard them.  You could imagine bazel splitting a test binary apart so that all the long running tests are in parallel, and the remaining fast ones are done together in one process.  I'm talking time here rather than size, but we also want to break the falsehood of using "size" as a proxy for both memory requirements and duration.

**Comment by adam-azarchs** [comment]
I think it would be great to break the assumption that memory and time requirements are always correlated, and it would be great if test adapters knew how to run tests with finer granularity than treating a test target as a single opaque binary that gets run as a single process, but both of those seem to me orthogonal to the feature request of offering a warning when the memory consumption of a test exceeds what was specified (or defaulted), in the same way as is already offered for timeouts.

**Comment by meisterT** [comment]
cc @wilwell

**Comment by meisterT** [comment]
cc @larsrc-google

**Comment by matshch** [comment]
@bazelbuild/triage it is still an issue, and looks like there is no easy way to validate tests sizes.
