### ISSUE TITLE
Bazel query: visible() operator does no filtering when first arg is an empty package

### ISSUE THREAD

**Issue by FrancescoScappatura** [bazelbuild/bazel#13045]
### Description of the problem / feature request:

Bazel query visible feature seems to provide wrong output when the BUILD file of a package is empty.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Considers 3 different packages:

- package_core     #that's a library !
- dummy_clientx
- dummy_clienty

package_core build file content is:

```
cc_library(
    name = "hello-time1",
    srcs = ["hello-time.cc"],
    hdrs = ["hello-time.h"],
    visibility = [":clients"],
)


cc_library(
    name = "hello-time2X",
    srcs = ["hello-time.cc"],
    hdrs = ["hello-time.h"],
    visibility = [":clients"],
)


cc_library(
    name = "hello-time3",
    srcs = ["hello-time.cc"],
    hdrs = ["hello-time.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "hello-time4",
    srcs = ["hello-time.cc"],
    hdrs = ["hello-time.h"],
    visibility = ["//visibility:private"],
)



package_group(
    name="clients",
    packages=[
        "//package_core/...",
        "//dummy_clientx/...",
	"//dummy_clienty/...",
	],
)
```
 dummy_client X build file content is:
```
cc_library(  
  name = "hello-greet",
)
```

while dummy_clienty build file is **empty**!

The command bazel query shows different visibility for the following queries:
```
 bazel query 'visible(//dummy_clientx/..., //package_core/...)' 
//package_core:hello-time3
//package_core:hello-time2X
//package_core:hello-time1
```
```
bazel query 'visible(//dummy_clienty/..., //package_core/...)' 
//package_core:hello-time4  **<<---PRIVATE targets are shown as visible!**
//package_core:hello-time3
//package_core:hello-time2X
//package_core:hello-time1
```

 

 

 

### What operating system are you running Bazel on?
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

### What's the output of `bazel info release`?

```
bazel info release
release 3.7.2

```
 

 

 
### Any other information, logs, or outputs that you want to share?

 
[bazel_visibility_issue_playground.zip](https://github.com/bazelbuild/bazel/files/5982412/bazel_visibility_issue_playground.zip)

**Comment by brandjon** [comment]
My guess is that `//dummy_clienty/...` does not match any targets when the BUILD file is empty (not even `//dummy_clienty:BUILD`, or else visibility doesn't include file targets). If the set of targets is empty, then vacuously everything is visible to the targets in that set. So we need to investigate whether that is indeed the reason and perhaps clarify the documentation.
