### ISSUE TITLE
[Feature-Request] Separate Cache-Folder per toolchain / platform

### ISSUE THREAD

**Issue by JanJamaszyk-FlyNow** [bazelbuild/bazel#13042]
### Description of the problem / feature request:

As soon as a new toolchain is used e.g. by specifying `--platform` option bazel should create a new cache folder containing the name of the toolchain / platform in the folder name. 

### Feature requests: what underlying problem are you trying to solve with this feature?

In our build flow we are constantly switching between different toolchains / platforms.
Since bazel reuses the same cache folder, with each change of the platform / toolchain bazel invalidates the complete cache and starts a full rebuild.
If bazel would keep separate cache folders per toolchain / platform e.g.:
- `.cache/bazel/_bazel_root/e07e82e3ab273e3e0595387e603e3c95/execroot/__main__/bazel-out/k8-toolchain1-fastbuild`
- `.cache/bazel/_bazel_root/e07e82e3ab273e3e0595387e603e3c95/execroot/__main__/bazel-out/k8-toolchain2-fastbuild`

Bazel could reuse the cache folder after a switch of the toolchain / platform. This in turn would improve caching and dramatically shorten build times.

### What operating system are you running Bazel on?

Distributor ID: Ubuntu
Description: Ubuntu 20.04.1 LTS
Release: 20.04
Codename: focal
Kernel: 5.8.0-40-generic

### What's the output of `bazel info release`?

release 4.0.0

**Comment by gregestren** [comment]
Would https://docs.bazel.build/versions/master/user-manual.html#flag--output_base help?

Interestingly, what you're describing already happens *after transitions*.  i.e. if there's any target in the build that uses a different configuration from the top level command line flags, that does pretty much exactly what you describe. 

One challenge of doing this universally is we don't want to break caching for targets that are legitimately the same in both configurations.

**Comment by JanJamaszyk-FlyNow** [comment]
Hi Greg,
we already knew about --output_base, the problem is that this is a startup option. In our build flow we build with different configs right after another e.g.:
```
bazel build --config=fancy_host_config //...
bazel build --config=fancy_target_config //...
```
we did not find any way of changing output_base dynamically based on the supplied config in the `.bazelrc` given it is a startup option. If this would be possible this would also fulfill our needs!

**Comment by chandpriyankara** [comment]
@JanJamaszyk-FlyNow any workaround for this? I had to do with each docker container for each tool chain so it map  cache in different folders... but still love to have this feature to make is simple and as a bazel feature..
