### ISSUE TITLE
Documentation issue: Using the Android Native Development Kit with Bazel

### ISSUE THREAD

**Issue by mchinen** [bazelbuild/bazel#13059]
Documentation URL: https://docs.bazel.build/versions/master/android-ndk.html

An example project should be referenced.  The build instructions are missing various steps.
For example,
@io_bazel_rules_go//go/toolchain:android_arm64_cgo is referenced but is not defined anywhere - the user will have to search for the repo and add it to the WORKSPACE if they realize that is the issue.
An example would help with all of this.  This is generally an issue with bazel toolchain docs - they are quite complicated, there are missing steps, and example projects are not given.

**Comment by jin** [comment]
There's nothing related to go on this page. Are you trying this tutorial out on a clean workspace?

**Comment by mchinen** [comment]
If you search for the string "io_bazel_rules_go//go/toolchain:android_arm64_cgo" it will hit in the example code in https://docs.bazel.build/versions/master/android-ndk.html#integration-with-platforms-and-toolchains

On another note, I was incorrect about the lack of examples.  There is an example posted on that page: https://github.com/bazelbuild/examples/tree/master/android/ndk

**Comment by ahumesky** [comment]
The main point of that documentation is to say that if your build uses the `--platforms`, then to get the NDK to work, you'll also need `--extra_toolchains=@androidndk//:all`. The actual value to `--platforms` (the Go toolchain in the example) doesn't matter too much here.
