### ISSUE TITLE
sh_binary can't declare Skylark-generated targets as data dependencies

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#1305]
Consider this repository. https://github.com/dfabulich/sh_binary_built_data

In the `skylark-built` directory, there's a trivial Skylark rule that generates a file.

```python
def _impl(ctx):
	ctx.file_action(
		content="hello\n",
		output=ctx.outputs.out,
	)		

custom_rule=rule(
	implementation=_impl,
	outputs = {
		"out": "%{name}.txt"
	},
)
```

The `BUILD` file is also trivial:

```python
load('rule', 'custom_rule')

custom_rule(
	name='skylark-built',
	visibility=['//visibility:public'],
)
```

In the `sh-binary-dependent` directory, we define a `sh_binary` target that depends on `//skylark-built`.

```python
sh_binary(
	name='sh-binary-dependent',
	srcs=['sh-binary-dependent.sh'],
	data=['//skylark-built'],
)
```

The shell script is a one-liner that depends on `skylark-built.txt`:

```bash
#!/bin/bash -x

cat skylark-built/skylark-built.txt
```

If you `bazel run sh-binary-dependent`, I would expect it to succeed and print "hello", but it fails.

```
cat: skylark-built/skylark-built.txt: No such file or directory
```

And, sure enough, there's no `skylark-built.txt` anywhere in the sandbox.

**Comment by dfabulich** [comment]
As a workaround, I added a pointless `filegroup` target to `sh-binary-dependent/BUILD` that just wraps `//skylark-built`, and created a new `sh_binary` depending on the `filegroup` instead of on `//skylark-built` directly.

```python
filegroup(
	name='workaround-skylark-built',
	srcs=['//skylark-built'],
)

sh_binary(
	name='workaround',
	srcs=['sh-binary-dependent.sh'],
	data=['workaround-skylark-built'],
)
```

That works.

**Comment by hermione521** [comment]
@laurentlb Can you help with this? Thanks.

**Comment by laurentlb** [comment]
Data dependency is used for files that are needed at runtime (not compile time). To ensure your rule provides the files for the runtime execution, you have to use runfiles. See "Runfiles" section in http://bazel.io/docs/skylark/rules.html

By default, outputs go only in the files provider (which is why filegroup can see them).

**Comment by dfabulich** [comment]
This is not the behavior I would expect; I argue that it's incorrect. When adding a dependency to `data`, all of its `.files` should be provided to the `sh_binary`.

1) "runfiles" is intended for rules with executable outputs who themselves require runfiles to execute. When generating a pure data file, it makes no sense to declare the data file twice, once as output, and then again as its own runfile.

2) If I'd used a genrule to generate the file, it would have worked:

```python
genrule(
    name='skylark-built',
    outs=['skylark-built.txt'],
    cmd='echo genrule > $@',
    visibility=['//visibility:public'],
)
```

At no point in the `genrule` definition did I specify that the output file was (or wasn't) a "runfile," and I wouldn't expect to. It's a simple file output.

3) In context, this was part of a broader build; I didn't really need/intend to `bazel run` the `sh_binary`. Instead, I was using it in the context of other rules, like this `genrule`:

```python
genrule(
	name='genrule',
	tools=['sh-binary-dependent'],
	outs=['genrule.txt'],
	cmd="$(location sh-binary-dependent) > $@",
)
```

This fails, too, of course, because even though the `genrule` is running at "compile time," the `genrule`'s compile time is the `sh_binary`'s run time.

4) I would at least expect a warning when adding a `data` dependency that has no effect. But what would  the warning say? Why would it "warn" me of anything when it could instead DTRT and provide the `.files` to the `sh_binary`?

**Comment by ahumesky** [comment]
You could alternatively depend on the output file itself, which should also
work:

sh_binary(
name='sh-binary-dependent',
srcs=['sh-binary-dependent.sh'],
data=['//skylark-built:skylark-built.txt'],
)

**Comment by bsilver8192** [comment]
@laurentlb: I'm pretty sure `outputs` doesn't make its way into the files provider (ie `FilesToRunProvider`). Reading the code, it looks like those are considered implicit outputs, which the documentation doesn't make clear at all.

@dfabulich: You want something like this at the end of your Skylark implementation function:
```python
  return struct(files = set([ctx.outputs.out]))
```
That will actually set the files provider, which is how a rule gets converted to a generic set of files, like the `data` and `tools` attributes do.

**Comment by dslomov** [comment]
Setting 'files' provider should work. Closing this unless anyone sees any more work to do.

**Comment by rightfold** [comment]
Either way, implicitly ignoring this and not even printing a warning is very bad.
