### ISSUE TITLE
bazel 4.0.0: "Not all outputs were created or valid" when using java tools for java 14

### ISSUE THREAD

**Issue by MikhailTymchukFT** [bazelbuild/bazel#13053]
### Description of the problem / feature request:

We use a JDK 8 which is specified in WORKSPACE file:
```
http_archive(
    name = "openjdk8u242_darwin_archive",
    build_file_content = """
package(default_visibility = ["//visibility:public"])

java_runtime(
    name = 'runtime',
    srcs =  glob(['**']),
    java='//:Contents/Home/bin/java'
)
""",
    sha256 = "06675b7d65bce0313ee1f2e888dd44267e8afeced75e0b39b5ad1f5fdff54e0b",
    strip_prefix = "jdk8u242-b08",
    urls = ["https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u242-b08/OpenJDK8U-jdk_x64_mac_hotspot_8u242b08.tar.gz"],
)
```

`.bazelrc` is configured to use embedded JDK to execute repo rules, so build is self-contained:
```
common --enable_platform_specific_config
build --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
# workaround to run coursier using embedded JDK: https://github.com/bazelbuild/rules_jvm_external/issues/445
build --repo_env=JAVA_HOME=../bazel_tools/jdk
build:macos --javabase=@openjdk8u242_darwin_archive//:runtime
build:macos --host_javabase=@openjdk8u242_darwin_archive//:runtime
```

We transition to JDK 14 from JDK 8, so we have 2 different versions of `.bazelrc` to test our java code against different JDKs.
However, we cannot have multiple WORKSPACE files, so we put JDK 8 and JDK 14 download there as `http_archive` rules.
Also, we have to download java rules 14 to use them with JDK 14.

But build fails when there is a java tools for java 14 added to WORKSPACE **and** bazel 4.0.0 is used:
```
http_archive(
    name = "remote_java_tools_darwin",
    sha256 = "ceebee0618e838a0aa904f010e382a407e4ef6302d5d35c803e77b29612c3224",
    urls = [
            "https://mirror.bazel.build/bazel_java_tools/releases/javac14/v2.0/java_tools_javac14_darwin-v2.0.zip",
            "https://github.com/bazelbuild/java_tools/releases/download/javac14_v2.0/java_tools_javac14_darwin-v2.0.zip",
        ],
)
```

If bazel is reverted to 3.7.2, build succeeds.
If `remote_java_tools_darwin` rule is removed from the WORKSPACE file, build succeeds.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ git clone https://github.com/MikhailTymchukFT/bazel4-java14-rules-bug.git
$ cd bazel4-java14-rules-bug/
$ bazel build //...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:main (23 packages loaded, 954 targets configured).
INFO: Found 1 target...
ERROR: /Users/mikhailtymchuk/repos/bazel4-java14-rules-bug/BUILD:1:13: output 'libmain.jar_manifest_proto' was not created
ERROR: /Users/mikhailtymchuk/repos/bazel4-java14-rules-bug/BUILD:1:13: Building libmain.jar (1 source file) failed: not all outputs were created or valid
Target //:main failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 8.297s, Critical Path: 1.39s
INFO: 2 processes: 1 internal, 1 worker.
FAILED: Build did NOT complete successfully
```

Change the bazel version in `.bazelversion` file to 3.7.2 and build again:
```
$ bazel build //...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:main (18 packages loaded, 821 targets configured).
INFO: Found 1 target...
Target //:main up-to-date:
  bazel-bin/libmain.jar
INFO: Elapsed time: 15.928s, Critical Path: 2.74s
INFO: 2 processes: 1 internal, 1 worker.
INFO: Build completed successfully, 2 total actions
```

### What operating system are you running Bazel on?

MacOS 11.2.1

### What's the output of `bazel info release`?

release 4.0.0

###  Have you found anything relevant by searching the web?

There is an open issue which describes the same problem: https://github.com/bazelbuild/bazel/issues/8125
However, no info why it happens and how to workaround that behavior without changing bazel version. 

### Any other information, logs, or outputs that you want to share?

When using `multiplex-worker` strategy, build can hang.
If this strategy is disabled with `--noexperimental_worker_multiplex` option, the error message specified above appears immediately.

**Comment by doompadee** [comment]
Should be same as #13065

**Comment by comius** [comment]
Please **don't** use javac14 release of java_tools, it's incompatible with Bazel 4.0.0.

Please use java_tools 10.5 (https://github.com/bazelbuild/java_tools/releases/tag/javac11_v10.5) with both Bazel 3.7.2, 4.0.0.
They support both Java 14 and Java 15.
