### ISSUE TITLE
Windows not detecting Bazel

### ISSUE THREAD

**Issue by DrewGlinsman** [bazelbuild/bazel#13058]
Hey all I've been having a ton of problems getting my windows to detect bazel through multiple different ways.

The first way I tried was setting bazel.exe's location as a environment variable. I had some success with this route but I couldn't get just bazel to work as a command only %bazel% in my command prompt but it still had issues building files that I know should work. 
Here's Bazels Location on my PC (C:/Program Files/ Bazel)
![image](https://user-images.githubusercontent.com/31940539/108558138-7d3adc80-72c7-11eb-85bd-7ccac9de65ba.png)
Here's my user specific PATH variable
![image](https://user-images.githubusercontent.com/31940539/108558200-9479ca00-72c7-11eb-8efa-281e5763638d.png)
Here's the system wide PATH variable
![image](https://user-images.githubusercontent.com/31940539/108558243-a3f91300-72c7-11eb-9a10-8648c93b070f.png)
Error when I try to check the version of my bazel
![image](https://user-images.githubusercontent.com/31940539/108558300-b7a47980-72c7-11eb-9a02-d87834e5efa0.png)

Second I tried the visual studio code plugin but I could not get it to even recognize bazel as a command despite setting the BAZEL variable to the path of the bazel.exe file.

Third I tried using msys2 but ran into the same issue as visual studio. So I was wondering if anyone had experience setting up bazel on windows 10 because I haven't been able to have any success with it despite trying multiple different ways to set it up.

**Comment by KanzaSheikh** [comment]
Has this problem been solved? I am facing the same issue

**Comment by DrewGlinsman** [comment]
Update I solved this by changing my bazel executables filename from bazel.exe to just bazel.

**Comment by kuldeep1A** [comment]
1) First download the bazel with suiteable system in .exe
2) after rename bazel.exe
3) save this "bazel.exe" to any preferable location on system for example "D:\software\development\bazel\bazel.exe"
4) set PATH=%PATH%;D:\software\development\bazel
5) run bazel --version

this above easy five step solve the problem
