### ISSUE TITLE
Got:  Error in string: string() got unexpected keyword argument 'allow_multiple'

### ISSUE THREAD

**Issue by dzdeping** [bazelbuild/bazel#13064]
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

**Add below ctx in my.bzl file**

```
ModuleProvider = provider(fields = ['type'])
modules = ["","","",""]
def _custom_impl(ctx):
    raw_modules = ctx.build_setting_vaule
    if raw_modules not in modules:
       fail(str(ctx.label) + "build setting allowed to take value {" + ",".join(modules) + "} but was set to unallowed value " + raw_modules)
    return ModuleProvider(Type = raw_modules)

module_flag = rule(
    implementation = _custom_impl,
    build_setting = config.string(flag = True, allow_multiple = True)
)
```

### What operating system are you running Bazel on?

**Ubuntu 18.04.2 LTS \n \l**

### What's the output of `bazel info release`?

**release 4.0.0**

### Any other information, logs, or outputs that you want to share?
when i run :  `bazel coverage //...`

i got: 

`ERROR: Traceback (most recent call last):
        File "/opt/code/bepcloudbazel/bepcloud/bepcloud-parent/bzl/pkg_war.bzl", line 167, column 34, in <toplevel>
                build_setting = config.string(flag = True, allow_multiple = True)
Error in string: string() got unexpected keyword argument 'allow_multiple'
`

**Comment by brandjon** [comment]
Bazel 4.0.0's baseline was cut on Nov 18. The `allow_multiple` parameter to `config.string()` was added on Dec 10. You can use a version of Bazel closer to head if you want to experiment with this feature.
