### ISSUE TITLE
Multiplex workers hanging on compile error

### ISSUE THREAD

**Issue by larsrc-google** [bazelbuild/bazel#13065]
From [a thread on the Bazel Slack](https://bazelbuild.slack.com/archives/CA31HN1T3/p1613409822097600):

> I updated bazel to 4.0.0, MacOS, and now I see that my compilation hangs with multiplex-worker strategy.
Multiple worker logs are empty in bazel-workers dir.
How can I debug that?
Or, at least, disable multiplex-workers to unblock compilation. (edited) 

> When I use different spawn strategy or disable multiplex workers, I end up with the following error:
ERROR: somepath/BUILD:1:13: output 'sometarget.jar_manifest_proto' was not created
ERROR: somepath/BUILD:1:13: Building sometarget.jar (5 source files) failed: not all outputs were created or valid
I found similar open issue, but it does not really help: https://github.com/bazelbuild/bazel/issues/8125
I don't understand how to workaround this situation without reverting to older bazel versions (3.7.0) does not have this problem.

> I found the problematic place.
We migrate our code from java 8 to java 14, so we added jdk 14 for and java tool 14 to our WORKSPACE file which in minimal state looks like this:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")
http_archive(
    name = "remote_java_tools_darwin",
    sha256 = "e20f002ceb3f3353d64c022e1f3400d8539ee56ffcfd4a6680d73d6a2cac938b",
    urls = [
        "https://mirror.bazel.build/bazel_java_tools/releases/javac14/v1.0/java_tools_javac14_darwin-v1.0.zip",
        "https://github.com/bazelbuild/java_tools/releases/download/javac14-v1.0/java_tools_javac14_darwin-v1.0.zip",
    ],
)
http_archive(
    name = "openjdk8u242_darwin_archive",
    build_file_content = """
package(default_visibility = ["//visibility:public"])
java_runtime(
    name = 'runtime',
    srcs =  glob(['**']),
    java='//:Contents/Home/bin/java'
)
""",
    sha256 = "06675b7d65bce0313ee1f2e888dd44267e8afeced75e0b39b5ad1f5fdff54e0b",
    strip_prefix = "jdk8u242-b08",
    urls = ["https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u242-b08/OpenJDK8U-jdk_x64_mac_hotspot_8u242b08.tar.gz"],
)
```
> Now if we have simple BUILD file
```
java_library(
    name = "main",
    srcs = ["ClassA.java"],
)
```
> and empty ClassA, `bazel build :main --noexperimental_worker_multiplex` will result in above errors (or hang if `-noexperimental_worker_multiplex` is omitted).
But if we revert to bazel 3.7.2 or remove
```
http_archive(
    name = "remote_java_tools_darwin",
    sha256 = "e20f002ceb3f3353d64c022e1f3400d8539ee56ffcfd4a6680d73d6a2cac938b",
    urls = [
        "https://mirror.bazel.build/bazel_java_tools/releases/javac14/v1.0/java_tools_javac14_darwin-v1.0.zip",
        "https://github.com/bazelbuild/java_tools/releases/download/javac14-v1.0/java_tools_javac14_darwin-v1.0.zip",
    ],
)
```
> then everything is fine.

The multiplex workers should not hang, even when there are errors.

**Comment by doompadee** [comment]
I have the same issue on Linux when using JDK 14 for compilation. Build runs fine with Bazel 3.7.2, hangs with Bazel 4.0.

**Comment by larsrc-google** [comment]
I can reproduce this with just the `remote_tools_java_darwin` part of the `WORKSPACE` file, and without workers enabled:

```
$ bazel --bazelrc=/dev/null build :main --noexperimental_worker_multiplex --spawn_strategy=local --verbose_failures --worker_verbose
INFO: Analyzed target //:main (5 packages loaded, 249 targets configured).
INFO: Found 1 target...
ERROR: /Users/larsrc/git/bazel-repro-13065/BUILD:1:13: output 'libmain.jar_manifest_proto' was not created
ERROR: /Users/larsrc/git/bazel-repro-13065/BUILD:1:13: Building libmain.jar (1 source file) failed: not all outputs were created or valid
Target //:main failed to build
INFO: Elapsed time: 5.932s, Critical Path: 0.99s
INFO: 2 processes: 1 internal, 1 local.
FAILED: Build did NOT complete successfully
```

It works with Bazel 3.7.2. Interestingly, the jdk14 version exhibits this even without JDK14 installed. I'm getting other errors when trying to do a jdk11 version. 

@comius for advice since this is not actually worker-related.

**Comment by doompadee** [comment]
Repro for Linux can be found here: https://github.com/doompadee/multiplex

Simply doing a `bazel build //...` triggers the issue (build hangs). I don't even have to actually enable the JDK 14 (via --define etc).

**Comment by doompadee** [comment]
On further inspection, I think this issue is moot. Bazel 4.0 has Javac 14/15 support already build-in and the java_tools v14 package is no longer necessary.

**Comment by comius** [comment]
> @comius for advice since this is not actually worker-related.

Please use java_tools 10.5 (https://github.com/bazelbuild/java_tools/releases/tag/javac11_v10.5) with both Bazel 3.7.2, 4.0.0.
They support Java 15.

javac14 release was deprecated.

**Comment by comius** [comment]
Again please don't use javac14 release of java_tools, it's incompatible with Bazel 4.0.0.

java_tools javac11 10.5 supports both Java 14 and Java15.

**Comment by meisterT** [comment]
Do I understand it correctly that we can close this issue?

**Comment by meisterT** [comment]
I am closing it, please reply if you think we should reopen it.
