### ISSUE TITLE
cannot load '@rules_cc//examples:experimental_cc_shared_library.bzl'

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/bazel#13074]
bazel version: 3.7.2

ERROR: /data/src/cpp/BazelDemo/src/context/BUILD:14:11: error loading package 'src/service/proto': in /home/tiger/.cache/bazel/_bazel_tiger/807b0cad572b2c6af326ed0c01dff942/external/org_tensorflow/tensorflow/core/platform/default/build_config.bzl: in /home/tiger/.cache/bazel/_bazel_tiger/807b0cad572b2c6af326ed0c01dff942/external/org_tensorflow/tensorflow/tensorflow.bzl: in /home/tiger/.cache/bazel/_bazel_tiger/807b0cad572b2c6af326ed0c01dff942/external/org_tensorflow/tensorflow/core/platform/rules_cc.bzl: in /home/tiger/.cache/bazel/_bazel_tiger/807b0cad572b2c6af326ed0c01dff942/external/org_tensorflow/tensorflow/core/platform/default/rules_cc.bzl: cannot load '@rules_cc//examples:experimental_cc_shared_library.bzl': no such file and referenced by '//src/context:process_context'

need import rules_cc manual?

**Comment by aiuto** [comment]
I can't tell what this problem or question is. Can you provide simple reproduction instructions.

**Comment by xiedeacc** [comment]
> I can't tell what this problem or question is. Can you provide simple reproduction instructions.

I fixed this problem by import rules_cc manual, I will provide a small project on github for U to check

**Comment by xiedeacc** [comment]
> I can't tell what this problem or question is. Can you provide simple reproduction instructions.

I'm too busy to reproduce this problem, but others meet same problem can use below code to avoid this problem

``git_repository(
    name = "rules_cc",
    commit = "40548a2974f1aea06215272d9c2b47a14a24e556",
    remote = "https://github.com/bazelbuild/rules_cc.git",
)
