### ISSUE TITLE
I want to know how arm64 should be built? 

### ISSUE THREAD

**Issue by kekxv** [bazelbuild/bazel#13083]
I want to know how arm64 should be built?

```shell
➜  stage1 git:(master) ✗ gcc main/hello-world.cc -lstdc++                    
➜  stage1 git:(master) ✗ file a.out 
a.out: Mach-O 64-bit executable x86_64
➜  stage1 git:(master) ✗ arch --arm64e  gcc main/hello-world.cc -lstdc++                   
➜  stage1 git:(master) ✗ file a.out                                     
a.out: Mach-O 64-bit executable arm64
➜  stage1 git:(master) ✗ 
```

### What operating system are you running Bazel on?

> MacBook Air (M1, 2020)
> MacOs big sur

> Build label: 4.0.0-homebrew
> Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
> Build time: Sat Jan 23 02:10:29 2021 (1611367829)
> Build timestamp: 1611367829
> Build timestamp as int: 1611367829

**Comment by aiuto** [comment]
The best place to ask general questions like this is StackOverflow.

**Comment by cpsauer** [comment]
...but, @kekxv, if you're looking to compile for (just) Apple silicon, you should pass `--macos_cpus=arm64` (or arm64e) either on the command line or in .bazelrc.

If the system architecture is not being picked up as the default for host on an Apple-silicon-based system, I think that'd be a valid bug or feature request?

**Comment by kekxv** [comment]
@aiuto Thank you for your reply. I've looked for many places, but I didn't find any effective information. So I'd like to ask the developers if they have encountered or have any solutions.😭

@cpsauer I tried, but it didn't work.
