### ISSUE TITLE
In profile.json, action counter args field changed from "cpu" to "action" on Last Green

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/bazel#13089]
### Description of the problem / feature request:

On the last green bazel build, the `action counters` event in profile.json, has an `args.action` field instead of `args.cpu`. This is a breaking change.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Generate a profile.json with a build that has at least one build action. Notice that for the `action counters` event, the `args` field is now called `action` instead of `cpu`:

```
{"name":"action counters","ph":"C","ts":606095,"pid":1,"tid":490,"args":{"action":"0.020000000000000018"}},
```

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

```
development version
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

```
Using unreleased version at commit dcf2bbe3a53b9726a9be19a628f8a262b20229dc
```

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/commit/c5f87ea56a8b1f90525b8a6407dba8778524ca60 is the breaking commit.

**Comment by meisterT** [comment]
I am sorry that this broke your use case - is this something that you can easily fix on your side? We would like to keep the new behavior - and didn't expect anyone to rely on that.

With the new LTS releases (https://blog.bazel.build/2020/11/10/long-term-support-release.html) this change won't make it into a non-preview release until ~September 2021.

**Comment by brentleyjones** [comment]
This change is slated for Bazel 5.0? All good on our end then.

Is everything on HEAD by default the next LTS release? Where can I track what would be going into 4.x.x?

**Comment by philwo** [comment]
Hi @brentleyjones,

yes, everything on HEAD is going into the next LTS release (which will be Bazel 5.0). We will do cherry-picks only for the 4.x minor releases. All 4.x releases will preserve compatibility to 4.0 and not contain any breaking changes.

I'll create a tracking issue for Bazel 4.1 and will also document the whole process better in the next week.
