### ISSUE TITLE
//:third_party/objective_c/Cronet/cronet_c_for_grpc.h' crosses boundary of subpackage 

### ISSUE THREAD

**Issue by JaidenChiang** [bazelbuild/bazel#1309]
When I use the bazel to compile the grpc,it shows the follow errors:

_#/home/jaiden/Workstation/bazel/output/bazel build //:grpc --ignore_unsupported_sandboxing.
ERROR: /home/jaiden/Workstation/grpc/BUILD:1517:10: Label '//:third_party/objective_c/Cronet/cronet_c_for_grpc.h' crosses boundary of subpackage 'third_party/objective_c' (perhaps you meant to put the colon here: '//third_party/objective_c:Cronet/cronet_c_for_grpc.h'?).
ERROR: error loading package '': Package '' contains errors.
INFO: Elapsed time: 0.464s_

Anyone tells me how to resolve it? Thanks!

**Comment by hermione521** [comment]
Hi, it looks more like a grpc problem?

**Comment by dslomov** [comment]
Closing, > 7days "Under investigation"
