### ISSUE TITLE
[Bug] error: invalid zip file with overlapped components : zip -qn third_party/asm/asm-6.0-sources.jar -d /tmp/bazel_khaDGROH/classes during execution of compile.sh

### ISSUE THREAD

**Issue by DylanWake** [bazelbuild/bazel#13108]
### Description of the problem / feature request:

I downloaded the bazel-0.10.0-dist.zip from github releases and was building it from source with the `compile.sh`, it did run the compiling commands, but returns this exception after starting for about 20 seconds :
```
🍃  Building Bazel from scratch...unzip -qn third_party/asm/asm-6.0-sources.jar -d /tmp/bazel_khaDGROH/classes
error: invalid zip file with overlapped components (possible zip bomb)
```

### Feature requests: what underlying problem are you trying to solve with this feature?

Compile the Bazel

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1: download the zip file `bazel-0.10.0-dist.zip` from github releases
2: unzip it on the Nvidia Jetson tx2's system
3: run `compile.sh`

### What operating system are you running Bazel on?

Linux jetson1 4.9.201-tegra #1 SMP PREEMPT Fri Jan 15 14:54:23 PST 2021 aarch64 aarch64 aarch64 GNU/Linux

### What's the output of `bazel info release`?

installation is not completed

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

installation is not completed

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

null: not a git repository, I used the zip files in releases

###  Have you found anything relevant by searching the web?

I tried multiple versions of the unzip following instructions on stackOverflow, no help :(

### Any other information, logs, or outputs that you want to share?

```
🍃  Building Bazel from scratch...unzip -qn third_party/asm/asm-6.0-sources.jar -d /tmp/bazel_khaDGROH/classes
error: invalid zip file with overlapped components (possible zip bomb)
```
I followed the `installTensorFlowTX2` project on github and used their sh files, details attached:
```sh
#!/bin/bash
# NVIDIA Jetson TX2
# TensorFlow Installation
# Install Bazel
# Version 0.10.0
# We use the release distribution so that we don't have to build protobuf
#
INSTALL_DIR=$PWD
cd $HOME
#wget --no-check-certificate https://github.com/bazelbuild/bazel/releases/download/0.10.0/bazel-0.10.0-dist.zip
unzip bazel-0.10.0-dist.zip -d bazel-0.10.0-dist
sudo chmod -R ug+rwx $HOME/bazel-0.10.0-dist
# git clone https://github.com/bazelbuild/bazel.git
cd bazel-0.10.0-dist
./compile.sh
echo complete compile process....
sudo cp ~/bazel-0.10.0-dist/output/bazel /usr/local/bin
```

**Comment by xelmirage** [comment]
I encountered the same bug with 0.15.2,0.16.0 and around versions. 

Finally changing to 3.7.1 fixed the error, hope this can help :)

**Comment by fweikert** [comment]
Please upgrade to a newer version of Bazel, which should fix your problem. 0.10.0 is pretty much ancient at this point.
