### ISSUE TITLE
Standard cross-platform shell tools

### ISSUE THREAD

**Issue by schroederc** [bazelbuild/bazel#1311]
It's currently difficult to create cross-platform Skylark rules (or `sh_test`s).  Even creating symlinks between different Unix systems can be error-prone due to having different supported flags in `ln`.

Perhaps Bazel can help by providing a more standardized set of tools in each spawn action's environment.

**Comment by Helcaraxan** [comment]
@dslomov Is this really targeted for 0.6 or will initial development already be part of 5.x?

I'm asking as I am currently facing the issue of needing to make a Skylark rule compatible with Linux & MacOS and would also like to include Windows at the same time.

**Comment by pcj** [comment]
Related issue: #1797

**Comment by Helcaraxan** [comment]
Thanks for the information @pcj! This does not give me a direct solution but I do find it to give a good perspective on the context.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
