### ISSUE TITLE
IOException error for Android Instrumentation Test in Bazel

### ISSUE THREAD

**Issue by FareesHussain** [bazelbuild/bazel#13129]
### Description of the problem / feature request:

IOException error for Android Instrumentation Tests in Bazel

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

Tried to run tests with all of the following
- release 3.6.0- (@non-git)
- release 3.7.0- (@non-git)
- release 4.0.0- (@non-git)
- release 4.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

@non-git version were built using bootstraping as mentioned [here](https://docs.bazel.build/versions/4.0.0/install-compile-source.html#bootstrap-unix)

 

### Any other information, logs, or outputs that you want to share?

Trying to run Android instrumentation tests using bazel but everytime I run the test it failes with the folllowing error

This error is the same for Espresso and UiAutomator (Tests I've run are using form [android-testing-samples](https://github.com/android/testing-samples#experimental-bazel-support))

 > FAIL: //src/test:greeter_test (see /home/farees/.cache/bazel/_bazel_farees/42da2736b097f0159fc1e0ee4c3ce062/execroot/__main__/bazel-out/k8-fastbuild/testlogs/src/test/greeter_test/test_attempts/[attempt_1.log](https://github.com/bazelbuild/rules_jvm_external/files/6056767/attempt_1.log))
FAIL: //src/test:greeter_test (see /home/farees/.cache/bazel/_bazel_farees/42da2736b097f0159fc1e0ee4c3ce062/execroot/__main__/bazel-out/k8-fastbuild/testlogs/src/test/greeter_test/test_attempts/[attempt_2.log](https://github.com/bazelbuild/rules_jvm_external/files/6056768/attempt_2.log))
FAIL: //src/test:greeter_test (see /home/farees/.cache/bazel/_bazel_farees/42da2736b097f0159fc1e0ee4c3ce062/execroot/__main__/bazel-out/k8-fastbuild/testlogs/src/test/greeter_test/[test.log](https://github.com/bazelbuild/rules_jvm_external/files/6056764/test.log))

#### Environments:
Bazel - 3.6.0 , 3.7.0, 4.0.0
OS - Ubuntu 18.04

I've installed the prerequisites mentioned in the [documentation](https://docs.bazel.build/versions/master/android-instrumentation-test.html#prerequisites)
 - KVM
 - Xvfb

**Comment by FareesHussain** [comment]
@jin all the errors in the log shows the same error
```
Cannot run program "/home/farees/.cache/bazel/_bazel_farees/42da2736b097f0159fc1e0ee4c3ce062/sandbox/linux-sandbox/8/execroot/__main__/_tmp/460ffc733e95b13fc1eca23e7ea87627/16374156318087477600/com/google/android/apps/common/testing/broker/dexdump_annotations": error=2, No such file or directory

```

Is there any thing I'm missing here?

**Comment by ahumesky** [comment]
The problem might be that dexdump_annotations is a 32-bit binary, and your system is 64-bit and missing the 32-bit support files.

Can you try installing 32-bit support with `apt-get install libc6-i386` and run the build again?

Also, using `ldd` will say if there missing dependencies for the binary:
```
ldd bazel-<workspace-name>/external/android_test_support/tools/device_broker/java/com/google/android/apps/common/testing/broker/dexdump_annotations
```

**Comment by FareesHussain** [comment]
@ahumesky Thanks for the help `apt-get install libc6-i386` didn't actually work but the idea that dexdump_annotations is a 32-bit binary really helped a lot.

I remembered that it was mentioned in the [Android Documentation](https://developer.android.com/studio/install#64bit-libs) that we need to install some 32-bit binary libraries 

`sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386`

Thanks a lot.

Can we close this issue now or do we need to add this point to the documentation.

**Comment by ahumesky** [comment]
Glad you were able to get this working!
We'll update the documentation to include these steps
