### ISSUE TITLE
Documentation issue: `//...` and `:all` are barely documented.

### ISSUE THREAD

**Issue by dabrahams** [bazelbuild/bazel#13121]
Documentation URL: https://docs.bazel.build/versions/4.0.0/getting-started.html

I was starting on a project using bazel the other day, and trying to figure out how to ensure that I had all the build tools set up and I was ready to develop from a solid foundation.  I wanted a build-and-test-everything command, a basic ingredient in most developers' workflow.

I couldn't find it anywhere, so I asked my teammates.  They seemed surprised that I would be asking such an obvious question, and pointed me at the bazel tutorials, which I then dutifully re-read… finding nothing.  Figuring the tutorial had not really explained the system I was using, I then went on to try to read the tool's reference documentation. Just going through the "Concepts and Terminology" doc generated 10s of documentation issues and PRs for doc improvements from me, trying to sort out things that were confusing or internally self-contradictory, but *still* did not reveal the information I was looking for.  Fortunately one of my teammates had already told me the secret was `bazel test //...:all`, so I wasn't stuck.

It turns out, grepping through the project's documentation, that these critical constructs are barely mentioned (see below).  I tell the whole story here because I thought the team might want to understand and address the new user experience, in addition to placing the specific information about `//...` and `:all` more prominently.

```
git grep  -nHE -e  '//\.\.\.| :all| :[*]'
docs/best-practices.md:28:A project should always be able to run `bazel build //...` and `bazel test //...` successfully on
docs/build-ref.html:294:<h4 id="name">Target names, <code>//...:<b>target-name</b></code></h4>
docs/glossary.md:517:in combination, for example, `//...:*` means all rule and file targets in all
docs/guide.md:298:$ bazel fetch //...
docs/migrate-maven.md:232:   file. Run `bazel build //...` to ensure all of your targets still build.
docs/platforms.md:121:Linux machine with `//...`. Use the
docs/platforms.md:152:$ bazel build --platforms=//:myplatform //...`
docs/platforms.md:249:$ bazel cquery //... --output=starlark --starlark:file=example.cquery
docs/skylark/deploying.md:254:  - bazel build //...
docs/skylark/deploying.md:255:  - bazel test //...
docs/skylark/rules-tutorial.md:97:$ bazel query :all
docs/skylark/rules-tutorial.md:117:$ bazel build :all
docs/skylark/rules-tutorial.md:143:If you run `bazel build :all` now, you will get an error:
```

**Comment by gregestren** [comment]
@communikit - do you mind attaching a P[1-4] tag to this issue depending on your interpretation of priority? Each tag includes a brief description of what it's priority level means.

**Comment by communikit** [comment]
Ah, looks like I meant to close this after the commit was added.
