### ISSUE TITLE
Make sandboxing unsupported message more helpful

### ISSUE THREAD

**Issue by kamalmarhubi** [bazelbuild/bazel#1313]
The message printed right now (bazel 0.2.3) points the user to the docs, but could potentially suggest distro-specific fixes. Eg, suggesting `sudo sysctl kernel.unprivileged_userns_clone=1` on systems with `/proc/sys/kernel/unprivileged_userns_clone`, or adding `user_namespace.enable=1` to kernel boot params on RHEL 7 / Centos 7.

See also mailing list discussion: https://groups.google.com/d/topic/bazel-discuss/0LKrGf5CyYA/discussion

**Comment by hermione521** [comment]
Thanks for your suggestion. I think I can do it, but may not be very soon.

**Comment by hermione521** [comment]
`sudo sysctl kernel.unprivileged_userns_clone=1` is already in the doc. And we use pid namespace now.
