### ISSUE TITLE
build fails on AArch64, Fedora 33 for 3.7.2 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [bazelbuild/bazel#13139]
[jw@cn05 bazel]$ env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
DEBUG: /tmp/bazel_mbgxGyKj/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:14:
Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '3.1.0'
DEBUG: /tmp/bazel_mbgxGyKj/out/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True
DEBUG: /tmp/bazel_mbgxGyKj/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:14:
Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '3.1.0'
DEBUG: /tmp/bazel_mbgxGyKj/out/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True
DEBUG: /tmp/bazel_mbgxGyKj/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:47:14:
Current Bazel is not a release version, cannot check for compatibility.
DEBUG: /tmp/bazel_mbgxGyKj/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:49:14: Make sure that you are running at least Bazel 0.21.0.
ERROR: /tmp/bazel_mbgxGyKj/out/external/local_jdk/BUILD.bazel:189:10: @local_jdk//:jdk-lib: invalid label 'lib/systemd/system/system-systemd\x2dcryptsetup.slice' in element 17680 of attribute 'srcs' in 'filegroup' rule: invalid target name 'lib/systemd/system/system-systemd\x2dcryptsetup.slice': target names may not contain '\'
ERROR: /tmp/bazel_mbgxGyKj/out/external/bazel_tools/tools/jdk/BUILD:66:26: every rule of type java_runtime_alias implicitly depends upon the target '@local_jdk//:jdk', but this target could not be found because of: Target '@local_jdk//:jdk' contains an error and its package is in error
INFO: Repository remote_java_tools_linux instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:237:6: in <toplevel>
  /tmp/bazel_mbgxGyKj/out/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  /tmp/bazel_mbgxGyKj/out/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted: Analysis failed
INFO: Elapsed time: 19.611s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (314 packages loaded, 7935 targets\
 configured)
    Fetching ..._linux; Extracting /tmp/bazel_mbgxGyKj/out/external/remote_jav\
a_tools_linux/temp15794111830786448853/java_tools_javac11_linux-v10.0.zip

ERROR: Could not build Bazel
[jw@cn05 bazel]$

**Comment by philwo** [comment]
Something in the local JDK installed on your system contained an invalid path:
> @local_jdk//:jdk-lib: invalid label 'lib/systemd/system/system-systemd\x2dcryptsetup.slice' in element 17680 of attribute 'srcs' in 'filegroup' rule: invalid target name 'lib/systemd/system/system-systemd\x2dcryptsetup.slice': target names may not contain ''

I don't think there is anything that Bazel can do to fix this. If you still see this problem, please let us know which OpenJDK you have installed.
