### ISSUE TITLE
Build Event Protocol: targetConfigured event with aborted payload

### ISSUE THREAD

**Issue by qaisjp** [bazelbuild/bazel#13142]
When would a [targetConfiguredId](https://github.com/bazelbuild/bazel/blob/3b60948815400fc24fad89c1375575d689a0b3db/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto#L96-L114) be sent with an [aborted](https://github.com/bazelbuild/bazel/blob/3b60948815400fc24fad89c1375575d689a0b3db/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto#L266-L268) payload?

Unfortunately I don't have a minimal reproduction example to provide, but the aborted payload I'm [receiving](https://docs.bazel.build/versions/master/build-event-protocol.html) has reason `UNKNOWN` and a blank description.

**Comment by qaisjp** [comment]
Additional context: the rule that is aborted is a build setting rule: https://docs.bazel.build/versions/master/skylark/config.html#the-build_setting-rule-parameter

**Comment by gregestren** [comment]
I did some BEP extensions to better support build settings a bit back. I'm not sure they directly address your observation but I'll have to poke around there to get feedback.

**Comment by aiuto** [comment]
@qaisjp  Could you provide a small reproduction?

**Comment by qaisjp** [comment]
It took a while but we found a way to reproduce it with a tag from https://github.com/bazelbuild/rules_go.

```
bazel test --cache_test_results=no --@io_bazel_rules_go//go/config:race --build_event_json_file=bep.json //gotest/...
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                   this tag causes the below event to be sent
```

produces

```
{"id":{"targetConfigured":{"label":"@io_bazel_rules_go//go/config:race"}},"aborted":{},"lastMessage":true}
```

I've included a repo + instructions + sample BEP JSON here: https://github.com/qaisjp/bazel-targetConfigured-aborted-payload

**Comment by qaisjp** [comment]
Oh and to clarify, this happens for any flag configured like this, and isn't specific to rules_go.

https://github.com/bazelbuild/rules_go/blob/f2d2516caad22c23d4a3e6d4612e2ed9b3f216d9/go/config/BUILD.bazel#L19-L23

**Comment by qaisjp** [comment]
I took my reproduction branch and:
* upgraded it to rules_go-v0.39.0
* go toolchian version 1.19.3
* bazel 6.1.1

```diff
diff --git a/WORKSPACE b/WORKSPACE
index 1143128..7ac5d16 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -2,10 +2,10 @@ load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

 http_archive(
     name = "io_bazel_rules_go",
-    sha256 = "69de5c704a05ff37862f7e0f5534d4f479418afc21806c887db544a316f3cb6b",
+    sha256 = "6b65cb7917b4d1709f9410ffe00ecf3e160edf674b78c54a894471320862184f",
     urls = [
-        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.27.0/rules_go-v0.27.0.tar.gz",
-        "https://github.com/bazelbuild/rules_go/releases/download/v0.27.0/rules_go-v0.27.0.tar.gz",
+        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.39.0/rules_go-v0.39.0.zip",
+        "https://github.com/bazelbuild/rules_go/releases/download/v0.39.0/rules_go-v0.39.0.zip",
     ],
 )

@@ -13,4 +13,4 @@ load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_depe

 go_rules_dependencies()

-go_register_toolchains(version = "1.16")
+go_register_toolchains(version = "1.19.3")
```

I can no longer reproduce the issue. Thanks!
