### ISSUE TITLE
--spawn_strategy=sandboxed  works incorrectly

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/bazel#13153]
### Description of the problem:

> when build project with --spawn_strategy=sandboxed option, target generated files in a wrong directory, like /home/user/.cache/bazel/_bazel_user/cd27d2986e9f23e87dc66c4d99689eb8/sandbox/linux-sandbox/4777/execroot/demo_generate/feature,  not in workspace/bazel-{out, bin, demo_generate}/feature, so led later build process failed.

>if with--spawn_strategy=local or with--spawn_strategy=standalone also generated file in wrong directory, generated file in my original source directory, not in workspace/bazel-{out, bin, demo_generate}/feature, 

both situations have same error build log, log belowest

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> later I will provide a small project

### What operating system are you running Bazel on?

> ubuntu 20.04

### What's the output of `bazel info release`?

> 3.7.2

###  Have you found anything relevant by searching the web?

> failed get answer from google, stackoverflow and bazel-discuss

### logs
> ERROR: /data/src/cpp/demo-generate/feature/BUILD:32:16: output 'feature_1.cc' was not created
ERROR: /data/src/cpp/demo-generate/feature/BUILD:32:16: output 'feature_1.h' was not created
ERROR: /data/src/cpp/demo-generate/feature/BUILD:32:16: output 'feature_2.cc' was not created
ERROR: /data/src/cpp/demo-generate/feature/BUILD:32:16: output 'feature_2.h' was not created

**Comment by meisterT** [comment]
Cc @larsrc-google

**Comment by xiedeacc** [comment]
fixed by change my plugin implement
