### ISSUE TITLE
Add TOC to help find flags in Commmand Line Reference

### ISSUE THREAD

**Issue by nkoroste** [bazelbuild/bazel#13158]
Documentation URL: https://docs.bazel.build/versions/master/command-line-reference.html

Very hard to tell what command a flag applies to at a glance. If you take a flag in the middle of the page, you have to scroll way up to find which section it's in and make sure not to miss it. 

Is it possible to add a TOC at the very top?

**Comment by keertk** [comment]
Hi there! There's now a navigation pane on the right that tells you which section you're in as you scroll through the flags on the [same page](https://docs.bazel.build/versions/master/command-line-reference.html). Closing this issue.
