### ISSUE TITLE
Incorrect Traceback-like Message in GitCloner.java

### ISSUE THREAD

**Issue by llchan** [bazelbuild/bazel#1315]
The changes in 717edaf5d399d2ffaf7b960ff3faa0606020b307 are a step in the right direction to provide a traceback-like message to git clone problems.  However, the message that gets appended at each level is always the original message, so you get stuff like this (newlines added for clarity):
```
ERROR: /path/to/tensorflow/tensorboard/bower/BUILD:5:1:
no such package '@paper_menu_button//':
Error cloning repository:
https://github.com/polymerelements/paper-menu-button.git: cannot open git-upload-pack
caused by https://github.com/polymerelements/paper-menu-button.git: cannot open git-upload-pack
caused by https://github.com/polymerelements/paper-menu-button.git: cannot open git-upload-pack
caused by https://github.com/polymerelements/paper-menu-button.git: cannot open git-upload-pack
caused by https://github.com/polymerelements/paper-menu-button.git: cannot open git-upload-pack
and referenced by '//tensorflow/tensorboard/bower:bower'.
```

In the exception hander [here](https://github.com/bazelbuild/bazel/blob/2fba42e27ec517a8819236d15e45a42bfd5c1823/src/main/java/com/google/devtools/build/lib/bazel/repository/GitCloner.java#L177-L187) I think
```java
errmsg.append(" caused by " + e.getMessage());
```
should be
```java
errmsg.append(" caused by " + throwable.getMessage());
```

(Is there a way to format a code diff in issues markdown?)

**Comment by hermione521** [comment]
Not familiar with this :(
Maybe @kchodorow can help?

**Comment by damienmg** [comment]
Also @davidzchen

**Comment by llchan** [comment]
Added a [link](https://github.com/bazelbuild/bazel/blob/2fba42e27ec517a8819236d15e45a42bfd5c1823/src/main/java/com/google/devtools/build/lib/bazel/repository/GitCloner.java#L177-L187) to the relevant code in the original post.

It should be fairly self-explanatory what it's trying to do, loop through the exception stack and concatenate the messages.  It's just concatenating the original message N times rather than the actual messages at each level.

**Comment by davidzchen** [comment]
@llchan Thanks, you're right about the fix. It should be `throwable.getMessage()` in this case.

I have sent a fix internally for review.
