### ISSUE TITLE
How to support grpclb protocol in the remote execution scenarios.

### ISSUE THREAD

**Issue by timmyhu** [bazelbuild/bazel#13174]
Hello.
We now use remote cache and remote execution in our building scenario, and set --remote_cache build parameter to our remote  cache server DNS.  But if we want to  use load balance,we should setup LVS or nginx as Layer4/7 proxy and set --remote_cache to the proxy.  That is not our ideal deployment model. We want to use a lookaside load balancer which is the grpclb API specification of grpc,and set --remote_cache to the lookaside load balancer.

Does Bazel support grpclb(look aside load balancing) now? and how to use it without change any Bazel source code.

Thanks a lot!

**Comment by aiuto** [comment]
You should ask this question on StackOverflow or slack. There is a a large community of people building remotely there.
