### ISSUE TITLE
Link to "Challenges of Writing Rules" is missing from the "Getting Started" Page.

### ISSUE THREAD

**Issue by JRodDynamite** [bazelbuild/bazel#13172]
### Description of the problem:

There seems to be a missing/incorrect link in the documentation on the [Getting Started page](https://bazel.build/basics/getting_started.html#bazels-code-description), section Bazel's code description, Point 3 sub-point 2. The phrase "Challenges of Writing Rules" points to an invalid link.

Missing link is https://bazel.build/basics/docs/rule-challenges.html

Correct link seems to be https://docs.bazel.build/versions/master/rule-challenges.html
I couldn't find the source of the "Getting started" page. If anyone can help point that out. I can help in raising a PR fixing this.

**Comment by communikit** [comment]
Hi @JRodDynamite , the location of the Getting started page is here: https://github.com/bazelbuild/bazel-website/blob/master/basics/getting_started.md (in the bazel-website repo).

Sorry about the delay in response, do you still have the bandwidth to help with a PR?

**Comment by JRodDynamite** [comment]
Raised a PR for it. https://github.com/bazelbuild/bazel-website/pull/307
