### ISSUE TITLE
Bazel coverage not working on java_tests

### ISSUE THREAD

**Issue by ThomasCJY** [bazelbuild/bazel#13178]
### Description of the problem / feature request:
bazel coverage will generate empty report of `coverage_report.dat` file and the test coverage feature is not working correctly.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I created a [test repository](https://github.com/ThomasCJY/bazel_example/tree/jchen-testCoverage-upstream/android_instrumentation_test) and it can be easily reproduced by running bazel coverage command

### What operating system are you running Bazel on?
Linux Ubuntu 20.04

### What's the output of `bazel info release`?
release 4.0.0

###  Have you found anything relevant by searching the web?
no

**Comment by nkoroste** [comment]
could be related to: https://github.com/bazelbuild/bazel/issues/5426

**Comment by ulfjack** [comment]
The problem is that Bazel uses an automatically computed default for `--instrumentation_filter`, which is 
```
INFO: Using default value for --instrumentation_filter: "^//src/main/java/com/example/unit[/:]".
```

However, the `JavaUtil.java` file is in `src/main/java/com/example/JavaUtil.java` and therefore doesn't match the filter.

**Comment by comius** [comment]
@c-mita can you triage this?

**Comment by c-mita** [comment]
As pointed out, the issue appeared to be the inappropriate instrumentation filter.
