### ISSUE TITLE
broken homepage link (!!)

### ISSUE THREAD

**Issue by palladius** [bazelbuild/bazel#13175]
# REPRO

1. Open home page: https://bazel.build/
2. Click GET STARTED -> https://docs.bazel.build/guide.html/getting-started.html
3. Get nice Page not found:

`404 - Page not found
$ bazel build :what-you-were-looking-for
...............
ERROR: no such page ':what-you-were-looking-for': BUILD file not found on package path.
INFO: Elapsed time: 0.567s`

**Comment by philwo** [comment]
Thanks for reporting the breakage. I currently can't reproduce this. I'll close this bug and have followed up on your internal issue.
