### ISSUE TITLE
experimental_sibling_repository_layout seems to create remote execution actions with invalid working_directory/output relationships

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/bazel#13188]
### Description of the problem / feature request:

When testing out an unrelated feature, using remote execution (with buildbarn), I ran into issues where Bazel errored that it could not compile DumpPlatformClassPath.class because:
```
JavaToolchainCompileClasses tools/jdk/platformclasspath_classes/DumpPlatformClassPath.class failed: not all outputs were created or valid
```

I'm running in a workspace with name `example_all`.

As far as I can tell, this error is because on the `Command` we're setting `working_directory: example_all` but also prefixing the `output_files` with `example_all/`, for example the `output_files` for my execution is `example_all/bazel-out/bazel_tools/darwin-fastbuild/bin/tools/jdk/platformclasspath_classes/DumpPlatformClassPath.class`.

The remote execution API specifies that `output_files` should be relative to the `working_directory`, rather than relative to the `input_root`, so I believe this prefixing shouldn't be happening. See this section of the remote API spec:

https://github.com/bazelbuild/remote-apis/blob/0943dc4e70e1414735a85a3167557392c177ff45/build/bazel/remote/execution/v2/remote_execution.proto#L547-L551

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run a buildbarn cluster, and try to build any Java with `--experimental_sibling_repository_layout=true`.

### What operating system are you running Bazel on?

The Bazel client is on macOS, the buildbarn cluster is running Ubuntu Focal.

### What's the output of `bazel info release`?

development version

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Checked out f1826459f21b5ee8aec4f93686dd7ce8d063466e and ran `bazel build //src:bazel`

If I revert 7149f578006a4ad0d51df69830a6986749b34df5 this error goes away (though others are introduced), so I'll cc @lberki who may have some thoughts :)

**Comment by lberki** [comment]
This is probably because RBE has a bug where the output directory is interpreted relative to `input_root` instead of according to the spec, so this is what Bazel did. 

@eytankidron, do I understand correctly that if Bazel makes it so that output file paths are relative to `working_directory`, it will keep working with RBE since it's been partially fixed there?

@coeuvre , can you take this?

**Comment by eytankidron** [comment]
@lberki that is correct. This bug is now fixed in RBE. Sending output paths relative to the working directory will now work.

**Comment by ulfjack** [comment]
Changing this now is a breaking change for remote execution for users that are using `--experimental_sibling_repository_layout`.
