### ISSUE TITLE
Support filtering on JUnit @Category annotations

### ISSUE THREAD

**Issue by khogeland** [bazelbuild/bazel#13197]
### Description of the problem / feature request:

The JUnit test runner does not support filtering tests by category.

### Feature requests: what underlying problem are you trying to solve with this feature?

JUnit provides `@Category` annotations that can be used to filter tests in Gradle/Maven/SBT/etc. Bazel's default JUnit test runner should also support this feature.

**Comment by aiuto** [comment]
@comius

**Comment by comius** [comment]
The category annotation is in experimental package: `org.junit.experimental.categories.Category` and in JUnit5 it is replaced with @Tag annotation.

The PR is well written, however I'm not inclined to include this on the grounds that Gradle/Maven/SBT have it. 

New feature requires maintenance.

There are also requests to upgrade to JUnit5. This migration in itself is not easy and including a feature like this would make it more complicated (figuring out how to do change/deprecate newly added flags when we have JUnit5, how to migrate tests with @Category annotations).
