### ISSUE TITLE
Unable to use android_ndk_repository rule

### ISSUE THREAD

**Issue by oakad** [bazelbuild/bazel#13191]
Bazel v4.0.0/Linux

Upon specifying an `android_ndk_repository` rule the following error is reported:

> ERROR: Error fetching repository: java.io.IOException: Expected directory at `<SDK>/ndk-bundle/platforms`
> but it is not a directory or it does not exist. Unable to read the Android NDK at `<SDK>/ndk-bundle`, the path
> may be invalid. Is the path in android_ndk_repository() or ANDROID_NDK_HOME set correctly? If the path is
> correct, the contents in the Android NDK directory may have been modified.

The error is barely surprising, considering:

> The deprecated `<NDK>/platforms` and `<NDK>/sysroot` directories have been
> removed. These directories were merged and relocated into the toolchain during
>  r19. The location of these contents should not be relevant to anyone,
> including build systems, since the toolchain handles them implicitly. If you
> are using a build system that hasn't adapted to the changes introduced in NDK
 > r19, file a bug with your build system maintainer. See the [Build System
 > Maintainers Guide] for information on using the NDK in your own build system.

Can somebody kindly address this? Right now the NDK support appears to be broken outright.

**Comment by ahumesky** [comment]
This looks like the same issue as #12889. Does android_ndk_repository still work for r21 for you?
