### ISSUE TITLE
Protobuf fails to compile on x64_windows_msvc

### ISSUE THREAD

**Issue by rokstrnisa** [bazelbuild/bazel#1319]
Environment: Bazel 0.2.3, Windows 10, Visual Studio Community 2015 (14.0.25123.00) Update 2.

After disabling the warnings flags in `COPTS` and adding `nocopts="/WX"` to `//:protobuf_lite`, I tried to build the target:

    Rok@Void MINGW64 /c/protobuf-3.0.0-beta-3
    $ /home/Rok/bazel/output/bazel.exe build --cpu='x64_windows_msvc' //:protobuf_lite -s
    ...
    >>>>> # //:protobuf_lite [action 'Compiling src/google/protobuf/io/zero_copy_stream.cc']
    cd C:/tools/msys64/var/tmp/Bazel/gCo59nC$/protobuf-3.0.0-beta-3
      SET PATH=external/local_config_cc/wrapper/bin
      external/local_config_cc/wrapper/bin/msvc_cl.bat -m64 /DOS_WINDOWS=OS_WINDOWS /DCOMPILER_MSVC /DNOGDI /DNOMINMAX /DPRAGMA_SUPPORTED _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /D_USE_MATH_DEFINES /DWIN32_LEAN_AND_MEAN /nologo /bigobj /Zm500 /J /Gy /GF /W3 /EHsc /wd435ternal/bazel_tools -iquote bazel-out/vc_14_0_x64-fastbuild/genfiles/external/bazel_tools -isystem src -isystem bazel-out/vc_14_0_x64-f/protobuf_lite/src/google/protobuf/io/zero_copy_stream.o -MD -MF bazel-out/vc_14_0_x64-fastbuild/bin/_objs/protobuf_lite/src/google/pr/google/protobuf/io/zero_copy_stream.o
    ERROR: C:/protobuf-3.0.0-beta-3/BUILD:70:1: undeclared inclusion(s) in rule '//:protobuf_lite':
    this rule is missing dependency declarations for the following files included by 'src/google/protobuf/stubs/common.cc':
      'C:/Program Files (x86)/Windows Kits/8.1/include/um/windows.h'
      'C:/Program Files (x86)/Windows Kits/8.1/include/shared/winapifamily.h'
      'C:/Program Files (x86)/Windows Kits/8.1/include/shared/sdkddkver.h'
      'C:/Program Files (x86)/Windows Kits/8.1/include/shared/windef.h'
    ...

It compiles fine without the `--cpu` argument.

**Comment by dslomov** [comment]
Windows support is very experimental at this point... /cc @meteorcloudy

**Comment by meteorcloudy** [comment]
Can you try to build bazel from HEAD? 
This "missing dependency declarations" error should already be fixed at [352f7e7](https://github.com/bazelbuild/bazel/commit/352f7e7b5f3adae4128a6041bdfe1324c433ce28).

Since `C:/Program Files (x86)/Windows Kits/8.1/include` has already been filtered in [CROSSTOOL](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/CROSSTOOL#L568) file, there should be no problem. 

And it did succeed on my machine.

```
pcloudy@PCLOUDY1-W MSYS ~/workspace/protobuf-3.0.0-beta-3
$ bazel version
Build label: 0.2.3-2016-05-19 (@9f046cb)
Build target: bazel-out/local_windows_msys64-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu May 19 09:28:06 2016 (1463650086)
Build timestamp: 1463650086
Build timestamp as int: 1463650086

pcloudy@PCLOUDY1-W MSYS ~/workspace/protobuf-3.0.0-beta-3
$ bazel build --cpu='x64_windows_msvc' //:protobuf_lite
WARNING: C:/tools/msys64/home/pcloudy/workspace/protobuf-3.0.0-beta-3/BUILD:105:16: in includes attribute of cc_library rule //:protobuf_lite: 'src/' resolves to 'src' not in 'third_party'. This will be an error in the future.
INFO: Found 1 target...
Target //:protobuf_lite up-to-date:
  C:/temp/Bazel/S8XKQGAE/execroot/protobuf-3.0.0-beta-3/bazel-out/vc_14_0_x64-fastbuild/bin/libprotobuf_lite.a
INFO: Elapsed time: 3.996s, Critical Path: 0.02s
```

**Comment by rokstrnisa** [comment]
Cannot get Bazel to build from HEAD (9aafb15589fc0267f4705effa10c251c64cf398b) in a clean repository.

Sometimes it hangs like this:

    Rok@Void MINGW64 ~/bazel
    $ ./compile.sh
    INFO: You can skip this first step by providing a path to the bazel binary as second argument:
    INFO:    ./compile.sh compile /path/to/bazel
    Building Bazel from scratch...
    1 [main] bash 8988 C:\tools\msys64\usr\bin\bash.exe: *** fatal error in forked process - MapViewOfFileEx 'shared.5'(0x9C), Win32 error 6.  Terminating.
    1136 [main] bash 8988 cygwin_exception::open_stackdumpfile: Dumping stack trace to bash.exe.stackdump
    0 [main] bash 3040 fork: child -1 - forked process 8988 died unexpectedly, retry 0, exit code 0x100, errno 11
    scripts/bootstrap/compile.sh: fork: retry: No child processes
    1 [main] bash 4832 C:\tools\msys64\usr\bin\bash.exe: *** fatal error in forked process - MapViewOfFileEx 'shared.5'(0x9C), Win32 error 6.  Terminating.
    1158 [main] bash 4832 cygwin_exception::open_stackdumpfile: Dumping stack trace to bash.exe.stackdump
    2238897 [main] bash 3040 fork: child -1 - forked process 4832 died unexpectedly, retry 0, exit code 0x100, errno 11
    scripts/bootstrap/compile.sh: fork: retry: No child processes

Sometimes like this:

    [700 / 1,083] Still waiting for 46 jobs to complete:
          Running (standalone):
            GenProtoSrcJar src/main/protobuf/libpackage_manifest_java_proto_srcjar\
    .srcjar, 11 s
            GenProtoSrcJar src/main/protobuf/libdeps_java_proto_srcjar.srcjar, 11 \
    s
            GenProtoSrcJar src/tools/android/java/com/google/devtools/build/androi\
    d/proto/libserialize_format_proto_srcjar.srcjar, 11 s
            GenProtoSrcJar src/main/protobuf/libjava_compilation_java_proto_srcjar\
    .srcjar, 10 s
            GenProtoSrcJar src/main/protobuf/libandroid_studio_ide_info_java_proto\
    _srcjar.srcjar, 10 s
            GenProtoSrcJar src/main/protobuf/libbundlemerge_java_proto_srcjar.srcj\
    ar, 10 s
            GenProtoSrcJar src/main/protobuf/libplmerge_java_proto_srcjar.srcjar, \
    10 s
            GenProtoSrcJar src/main/protobuf/libdash_java_proto_srcjar.srcjar, 10 \
    s
          Scheduling:
            Executing genrule //src:dummy_darwin_tool_src_tools_xcode_actoolwrappe\
    r_actoolwrapper, 109 s
            Executing genrule //src:java-version, 108 s
            Linking src/main/tools/namespace-sandbox.exe, 107 s
            Linking src/main/tools/libprocess-tools.a, 107 s
            Linking src/main/tools/build-runfiles.exe, 106 s
            Linking third_party/zlib/libzlib.a [for host], 106 s
            Linking third_party/ijar/libzip.a [for host], 104 s
            Linking third_party/protobuf/libprotobuf_lite.a [for host], 100 s
            Linking third_party/protobuf/libprotobuf_clib.a [for host], 80 s
            ... 29 more jobs

**Comment by meteorcloudy** [comment]
Can you try to build Bazel using MSYS instead of MINGW64?
Never seen this error before, I guess it could be the reason.
http://www.bazel.io/docs/windows.html

**Comment by rokstrnisa** [comment]
I used MINGW in msys2, because I originally hit [this issue](https://www.bountysource.com/issues/29333469-failed-to-fork-child-process-no-such-file-or-directory). Reinstalling msys2 seems to have fixed the problem.

I can confirm that protobuf compiles fine using `x64_windows_msvc` within MSYS using Bazel 9aafb15. Thanks!

**Comment by meteorcloudy** [comment]
\o/
