### ISSUE TITLE
Unable to download External depedencies

### ISSUE THREAD

**Issue by badrinathvm** [bazelbuild/bazel#13209]
### Description of the problem / feature request:

Failing to fetch external dependencies say for eg: RxSwift.

Issue reproducible: 
Step 1: Clone this https://github.com/badrinathvm/bazel-test
Step 2:  `bazel build @Rx//:RxSwift`

Actual Result : 

<img width="846" alt="Screen Shot 2021-03-11 at 2 52 29 PM" src="https://user-images.githubusercontent.com/1479179/110866052-67db2180-8279-11eb-8493-4261ab5cced9.png">

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

> Mac OS Catalina v10.15.7

### What's the output of `bazel info release`? 

4.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

NA

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

NA

###  Have you found anything relevant by searching the web?

None

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?
 Updated the screenshot above which has the logs.

**Comment by aiuto** [comment]
Since it says something like "not a regular file .... BUILD", my hunch is that RxSwift has a  BUILD file and a build directory and you are using a case-insensitive file system.  Can you try again on a case sensitive one.

**Comment by aiuto** [comment]
Closing on staleness
