### ISSUE TITLE
Starting with an error in the build file when compilation fails misdirects attention (and tools)

### ISSUE THREAD

**Issue by dabrahams** [bazelbuild/bazel#13202]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

When compilation of some source file fails in a bazel project, the first diagnostic printed points into a `BUILD` file, even though the problem is in the source file.  That means humans (and tools!) need to ignore the first error to get to the useful stuff.  In my emacs configuration, I actually had to add this hack/workaround to avoid visiting the BUILD file when I really want to fix my source code.

```lisp
;; Downgrade bazel errors, because bazel prints an error every time compilation
;; fails and it's not what I want to jump to.
(use-package bazel-mode
  :defer
  :config
  (setcar (cddr (cl-cdddr (assoc 'bazel-mode-error compilation-error-regexp-alist-alist))) 1))
;; Eagerly pull this in before a compile so we can fix up the initial error.
(require 'bazel-mode (not :filename) :noerror)
```
I suggest that in these cases, if you must print a diagnostic pointing into the build file, you print that *after* the build step's errors.

### Feature requests: what underlying problem are you trying to solve with this feature?

Distracting with almost-always-irrelevant information, poor editor integration characteristics.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Find any bazel project, introduce a syntax error in one of the non-build files, then `bazel build`.

### What operating system are you running Bazel on?

MacOS

### What's the output of `bazel info release`?

2021/03/10 18:30:48 Using unreleased version at commit 748c442c7062ba40fa667824b8c3bad767a0c5ca
development version

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

bazelisk got it for me, I don't know more.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Sorry, can't say.

###  Have you found anything relevant by searching the web?
no

**Comment by aiuto** [comment]
Looking at stdout for IDE/editor integration is a going to be an ongoing game of whack-a-mole.  Users can define all sorts of things in action mnemonics.

**Comment by dabrahams** [comment]
I don't know what you mean by “action mnemonics,” but the issue here is not what users define.  It's about what bazel does OOTB.

**Comment by aiuto** [comment]
The action mnemonic is the name of the action. But that is actually not the point I was trying  to make. It's just that parsing unstructured text to get a precise error location is a hopeless game.  You need to use a structured event stream that indicates the location in the build file, the action being executed, and if the error is in the rule structure itself or if the error comes from the tool being run in the action.
