### ISSUE TITLE
--strict_proto_deps=warn indistinguishable from error

### ISSUE THREAD

**Issue by aaliddell** [bazelbuild/bazel#13208]
### Description of the problem:

The `--strict_proto_deps` CLI argument appears to be somewhat unpredictable in its application:
- `--strict_proto_deps=warn` is documented but indistinguishable from error or strict: https://github.com/bazelbuild/bazel/blob/3e3814475c08cb47b7e2ea832030389ca052d00a/src/main/java/com/google/devtools/build/lib/rules/proto/ProtoCommon.java#L527
- ~It is not erroring in cases where it apparently should. See:~
  - ~https://github.com/rules-proto-grpc/rules_proto_grpc/issues/119~
  - ~https://github.com/grpc-ecosystem/grpc-gateway/blob/master/internal/descriptor/apiconfig/BUILD.bazel~
  - ~The above example should error, since `http.proto` is imported in `apiconfig.proto`, but is not in the deps list and is coming transitively from `@go_googleapis//google/api:annotations_proto`.~
  - ~This seems to trip on certain builds but not others, with no discernable difference in structure.~

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build https://github.com/aaliddell/strict_protos_test with `--strict_proto_deps=warn`. The build will fail the same as with `error` or `strict`. It may not be possible to only get protoc to warn, in which case the `warn` flag could at least be removed from the documentation?

~Pull grpc-gateway and run `bazel build --strict_proto_deps=error -s //internal/descriptor/apiconfig:apiconfig_go_proto`~

~The generated command contains non-direct dependencies in the `--direct_dependencies` flag:~

```
--direct_dependencies external/go_googleapis/google/api/annotations.proto:google/api/annotations.proto:external/go_googleapis/google/api/client.proto:google/api/client.proto:external/go_googleapis/google/api/field_behavior.proto:google/api/field_behavior.proto:external/go_googleapis/google/api/http.proto:google/api/http.proto:external/go_googleapis/google/api/resource.proto:google/api/resource.proto:internal/descriptor/apiconfig/apiconfig.proto
```

~This should only contain `annotations.proto` and `apiconfig.proto`, but instead contains additional transitive deps and `annotations.proto` is repeated. This is causing protoc to not error with `--direct_dependencies_violation_msg`~

~As a counter example, see https://github.com/aaliddell/strict_protos_test, which does error but is structurally similar.~

### What operating system are you running Bazel on?

Ubuntu 20.10

### What's the output of `bazel info release`?

`release 4.0.0`

Also present on older releases

###  Have you found anything relevant by searching the web?

No

**Comment by aaliddell** [comment]
rules_go [patches `go_googleapis`](https://github.com/bazelbuild/rules_go/blob/0b2afde488a1eefe6ca468029e94e24b927b0cea/third_party/go_googleapis-gazelle.patch#L2695-L2706), which defines `annotations_proto` differently from the upstream source repo, leading to the unexpected behaviour seen with grpc-gateway. Depending on how `go_googleapis` is loaded into the workspace, the deps tree will be different...

So the only issue is that `warn` does not work.

**Comment by aiuto** [comment]
It is unclear if this is a problem with Bazel or rules_go.

**Comment by aaliddell** [comment]
There were originally two related issues listed, but the second of these turned out to be linked to rules_go doing odd things with go_googleapis.

The remaining issue that is Bazel related is that there are multiple strict_proto_deps modes with the same behaviour:

- strict and error are identical
- warn does not warn but is instead again the same as error
- off works as expected

Most of that is fine, but warn not warning is at least a bit unexpected. Based on other flags, I would expect a warn mode to print the error messages but then continue.

Due to the way this mode works, it may not be easy to get warning to work though, since it depends on protoc internals which will always fail when the checking is active.

If you don’t expect to get warn working, perhaps the mode could be deprecated and then removed?

**Comment by Yannic** [comment]
This is known issue with native proto rules. I'd like to get `warn` to work, but it's not entirely straight forward IIRC and may require a patch to `protoc` to support that.

Probably `P3` or `P4`.

/cc @comius

**Comment by comius** [comment]
The Starlark doesn't provide a call to emit a warning - due to a very strong belief that warnings are ignored by the users and they serve just to populate the logs. That's the reason `=warn` setting will remain to be an error as well.

We could update documentation on it - but even the name is misleading.
We could remove WARN, that might break some users, but I think this is the best option we have.
