### ISSUE TITLE
Documentation issue: IDE integration

### ISSUE THREAD

**Issue by chandlerc** [bazelbuild/bazel#13238]
Documentation URL: https://docs.bazel.build/versions/master/ide.html

The page claims there is an official plugin for IDEs including CLion. This seems quite misleading to users.

The link points to an *IntelliJ* plugin: https://ij.bazel.build/

The support matrix makes it pretty clear that CLion is *not* supported or official in any way:
https://ij.bazel.build/docs/bazel-support.html

There is a box that claims Linux CLion support is "best effort", but that doesn't seem to match reality for users. See the reviews here:
https://plugins.jetbrains.com/plugin/9554-bazel/reviews

For exxample, a recent review:
> Tried it. It does not work. No Bazel menu, no sync options anywhere. Apparently it is incompatible with the current Clion 2020.3.2.
> 
> As JetBrain products auto-upgrade frequently, plugins which require older versions are for all practical purposes useless. There is NO Bazel support in CLion.

An even more recent review has less detail, but seems to confirm the latest release still doesn't work.

Either this plugin needs to be fixed to work (at all) with CLion, or the claim that it is an official plugin for CLion should be removed from Bazel's website to avoid misleading users.

FWIW, if there are Bazel (or IntelliJ) folks interested in supporting CLion or improving it, I can connect you with an active user who might be motivated to help test and give feedback. But really, this only makes sense if there is a serious chance of sustaining support here.

**Comment by Bellagitout16** [comment]
I reverted this CL (which removed mention of CLion) per Danielle's request since the CLion issue will be resolved soon

**Comment by Bellagitout16** [comment]
Note from aliceks@
As in the last years, the IntelliJ team is still exporting the Bazel IntelliJ plugin and this includes a version for CLion. We're currently just lagging a bit behind with the IDE versions but are working on catching up (b/175568614; see also go/bazel-plugin-2021 but please don't spread it further, especially not outside of Google). Catching up takes some time as especially 2020.3 broke several APIs we use. For IntelliJ, we've recently published a beta version of the plugin for 2020.3 (see https://github.com/bazelbuild/intellij/issues/2102#issuecomment-801242977). For CLion 2020.3, we haven't done so yet as CLion still needed additional fixes at that time. We're getting closer, though.

If users complain that the plugin doesn't work in 2020.3, they must have manually installed an incompatible version as JetBrains' plugin marketplace shouldn't provide them the plugin in IDE versions >2020.2. We don't have any way to guard against that.

**Comment by chandlerc** [comment]
> I reverted this CL (which removed mention of CLion) per Danielle's request since the CLion issue will be resolved soon

The issue will be resolved soon? That's awesome news -- do you have a link to the issue? Any way I can follow along?

**Comment by alice-ks** [comment]
We tracked the compatibility of the Bazel plugin with IntelliJ/CLion 2020.3 in https://github.com/bazelbuild/intellij/issues/2102. As written on that issue, we pushed a version of the plugin compatible with IntelliJ/CLion 2020.3 to the public plugin repository on April 16. It should be available to you if you search in the marketplace.

We're aware that IntelliJ/CLion 2021.1 have been released by now. The compatibility work for the plugin for 2021.1 is tracked by https://github.com/bazelbuild/intellij/issues/2406. We've started with that work but it may take a while until we've fixed all issues.

**Comment by sgowroji** [comment]
Hello @chandlerc, Above issue about [CLion](https://ij.bazel.build/) support is now available. Could you please reply on the above issue update. Thanks!

**Comment by fweikert** [comment]
cc @mai93 since her work might have already fixed this issue.

**Comment by mai93** [comment]
We made improvements to the plugin development process that helped us support newer versions of CLion and IntelliJ faster than before. You can now use the plugin with the latest CLion version, [CLion 2022.3](https://plugins.jetbrains.com/plugin/9554-bazel/versions/stable/248255). We are also putting more effort in reviewing/merging users PRs to help improve the plugin for CLion (and the other IntelliJ IDEs).

**Comment by keertk** [comment]
Closing this issue since it has been addressed above. Please reopen if needed. Thanks!
