### ISSUE TITLE
Not possible to override string flag in the config section of bazelrc file from command line

### ISSUE THREAD

**Issue by AndersSundman** [bazelbuild/bazel#13231]
### Description of the problem / feature request:

Flags added to the `build:linux` config (from `--enable_platform_specific_config=true`), can't be overridden from the command line. 

The command line flag value should take precedence, as it does when the flag is added to any other config, but right now the command line option is ignored.

See repro below for a more detailed description of the issue.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

We would like to set a [skylib](https://github.com/bazelbuild/bazel-skylib/blob/master/rules/common_settings.bzl) `string_flag` (a build_config rule) to a default value for Linux but with the option to override that value from the command line.

Here is a small BUILD file that introduces the `color` flag and uses it to select a define or another in a `cc_binary` rule.

```
load("@bazel_skylib//rules:common_settings.bzl", "string_flag")

config_setting(
    name = "is_red",
    flag_values = {
        ":color": "red",
    },
)

config_setting(
    name = "is_black",
    flag_values = {
        ":color": "black",
    },
)

string_flag(
    name = "color",
    build_setting_default = "undefined",
    values = [
        "red",
        "black",
        "undefined",
    ],
)

cc_binary(
    name = "test",
    srcs = ["test.cpp"],
    copts = select({
        ":is_red": ["-DRED"],
        ":is_black": ["-DBLACK"],
    }),
)
```

Here is a `.bazelrc` file

```
build --enable_platform_specific_config=true
build:linux --//:color=red
```

The intention is for `color` to be `undefined` for all platforms except linux. For linux it gets set to `red` in the `.bazelrc` file. 

**The bug is that it's not possible to override this `color` value from the command line**

`bazel build //:test --//:color=black`

Even when doing this ^ (on linux), the value of `color` is `red`.

Without the `build:linux` in the `.bazelrc`, overriding works as expected:

This `bazel build //:test --//:color=red --//:color=black` makes `color` black.

Even adding another `build:red --//:color=red` config to the `.bazelrc` works as expected. I.e. `bazel build //:test --config=red --//:color=black` makes `color` black.

The `build:linux` config must be special in some (faulty) way.

### What operating system are you running Bazel on?

Linux (but I expect that this is the same with auto detected windows config, etc)

### What's the output of `bazel info release`?

release 4.0.0

###  Have you found anything relevant by searching the web?

We have looked, but haven't been able to find any other reports of this bug.

**Comment by AndersSundman** [comment]
Here is a complete repro example: [example.tar.gz](https://github.com/bazelbuild/bazel/files/6151020/example.tar.gz)

**Comment by aiuto** [comment]
@meteorcloudy You added this flag. Can you comment on it? It's not really Configurability's wheelhouse.

**Comment by meteorcloudy** [comment]
This looks like a bug, I'll take a look

**Comment by aiuto** [comment]
This feature has some problems as implemented. Most of the time people use config:xx to specify the **target** platform configuration.  The examples that people pointed out in #5055 are mostly about the need to auto-specify different options based on the **host** platform.

The fact that it just selects on 'linux' makes it too easy to fall into the trap of putting both host specific and target specific configuration under the same heading 'linux'. 

Proposal:
- change behavior so it picks up   `build:host=linux`    instead of `build:linux`
- enable_platform_specific_config is True by default.   Or, just remove it because we have just changed the --config processing to be a little more useful.

**Comment by meteorcloudy** [comment]
> change behavior so it picks up build:host=linux instead of build:linux

The documentation says it clearly it will pick based on the host configurations, anyone who uses this flag should be aware of that. I agree we should have picked a better name, but changing it now will just break our uesrs.

> enable_platform_specific_config is True by default. Or, just remove it because we have just changed the --config processing to be a little more useful.

I don't quite understand why should we turn it on by default or just remove it.

**Comment by meteorcloudy** [comment]
@AndersSundman 

I looked a bit in to this, it doesn't seem to be caused by the `--enable_platform_specific_config` flag. Because if you turn off `--enable_platform_specific_config` and do
`bazel build //:test --config=linux --//:color=black`. The color would still be red.

**Comment by meteorcloudy** [comment]
> Even adding another build:red --//:color=red config to the .bazelrc works as expected. I.e. bazel build //:test --config=red --//:color=black makes color black.

@AndersSundman Are you sure this works?

**Comment by AndersSundman** [comment]
> > Even adding another build:red --//:color=red config to the .bazelrc works as expected. I.e. bazel build //:test --config=red --//:color=black makes color black.
> 
> @AndersSundman Are you sure this works?

I can confirm that it seems to be related to the string flags.

I tested the config experiment again and it doesn't seem to work. I must have confused something before.

`bazel build //:test --config=red --//:color=black` with a `build:red --//:color=red` in `.bazelrc` still makes it red.

**Comment by wudisheng** [comment]
I experienced exactly the same bug in 4.2.1 release.
