### ISSUE TITLE
Error requiring "bazel clean" when generating files inside what was previously a directory artifact

### ISSUE THREAD

**Issue by HALtheWise** [bazelbuild/bazel#13233]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

When attempting to generate a directory artifact in a location that _previously_ contained an explicitly-named file output, Bazel throws an I/O exception.

This can be resolved by running `bazel clean`, which is problematic because we are trying to train our developers to never do that.

```
ERROR: /home/eric/git/bazel_repro/BUILD.bazel:9:12: Action some failed: I/O exception during sandboxed execution: Could not move output artifacts from sandboxed execution
Target //:new_rule failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.230s, Critical Path: 0.07s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

I originally encountered this bug in a persistent worker, which resulted in a much less readable error message but ultimately the same behavior.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Check out this repo, https://github.com/HALtheWise/bazel-directory-failure, run `bazel build //...`, edit BUILD.bazel by switching which rule is commented out, then run `bazel build //...` again.

### What operating system are you running Bazel on?

Ubuntu

### What's the output of `bazel info release`?

`release 4.0.0`

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/2235 from four years ago seems similar

**Comment by HALtheWise** [comment]
Tagging my work account as @eric-skydio

**Comment by benjaminp** [comment]
Same as #13229?

**Comment by HALtheWise** [comment]
Looks like it.
