### ISSUE TITLE
Pseudolocalized string resources not generated even though default is true

### ISSUE THREAD

**Issue by tamerc** [bazelbuild/bazel#13236]
### Description of the problem / feature request:

Trying to generated pseudolcalized strings for English `res/values-en-rXA` and Arabic `values-ar-rXB`

`Aapt2ConfigOptions`  has the default value as true for the `generatePseudoLocale` option, yet they were not being generated when inspecting the apk.

```
 @Option(
      documentationCategory = OptionDocumentationCategory.UNCATEGORIZED,
      effectTags = {OptionEffectTag.UNKNOWN},
      name = "generatePseudoLocale",
      defaultValue = "true",
      category = "config",
      help = "Whether to generate pseudo locales during compilation.")
  public boolean generatePseudoLocale;
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Build an app that has string resources defined in `res/values/strings.xml`
2. Inspect the generated apk and check for `res/values-en-rXA/strings.xml` and Arabic `res/values-ar-rXB/strings.xml`

### What operating system are you running Bazel on?

Both Mac/Linux

### What's the output of `bazel info release`?

release 4.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Custom fork of Bazel

###  Have you found anything relevant by searching the web?

I have looked, but haven't found anything relevant to this issue.

### Any other information, logs, or outputs that you want to share?

Found that this is related to the `generatePseudoLocale` flag being set to false here: https://github.com/bazelbuild/bazel/blob/master/src/tools/android/java/com/google/devtools/build/android/aapt2/ResourceCompiler.java#L172

The following line of code invokes `compile` with the value set to true only when `generatedResourcesOut.isPresent`.

`generatedResourcesOut.ifPresent(
            out -> compile(directoryName, filename, results, out, file, true));`

Not sure why it depends on this condition of  generated resources being present, and not during aapt's compile phase when processing strings.xml files for the default locale.  Setting to true on line 172 correctly generates the pseudolocale strings.

**Comment by ahumesky** [comment]
To enable pseudolocalization, the one or both of the pseudo locales `en_XA` and `ar_XB` have to be added to the `resource_configuration_filters` of android_binary:

```
android_binary(
    name = "app",
    manifest = "AndroidManifest.xml",
    deps = [":lib"],
    resource_configuration_filters = ["en_XA", "ar_XB"],
)
```

Also, I believe that the string resources don't get added as (binary?) xml files into the apk, but appear in the resources.arsc, which can be dumped with appt2:

```
$ ~/android-sdk/build-tools/30.0.3/aapt2 dump resources bazel-bin/app/src/main/app.apk | grep -C5 Bazel
      () "Collapse"
      (ar) "تصغير"
      (en-rXA) "[Çöļļåþšé one two]"
      (ar-rXB) "‏‮Collapse‬‏"
    resource 0x7f0b001f string/app_name
      () "Built By Bazel"
      (en-rXA) "[βûîļţ βý βåžéļ one two three]"
      (ar-rXB) "‏‮Built‬‏ ‏‮By‬‏ ‏‮Bazel‬‏"
    resource 0x7f0b0020 string/search_menu_title
      () "Search"
      (ar) "البحث"
      (en-rXA) "[Šéåŕçĥ one two]"
      (ar-rXB) "‏‮Search‬‏"
```

This is not at all obvious, so I'll add this to the documentation for https://docs.bazel.build/versions/main/be/android.html#android_binary.resource_configuration_filters

(And, for what it's worth, I would add similar documentation for the `generatePseudoLocale` flag, but this flag is for a tool that wraps aapt2 that bazel invokes as an action, which happens to use the same options processor as bazel, so this flag doesn't show up anywhere in bazel's generated flag documentation.)
