### ISSUE TITLE
Exception in thread "main" java.lang.AssertionError

### ISSUE THREAD

**Issue by chsigg** [bazelbuild/bazel#13241]
### Description of the problem / feature request:
TensorFlow build recently started to hit the following error:
```
ERROR: /tmpfs/bazel_output/_bazel_kbuilder/f2d52ca1f092ccbe254cc98c3dc90790/external/bazel_tools/tools/jdk/BUILD:350:14: Action external/bazel_tools/tools/jdk/platformclasspath.jar failed (Exit 1): java failed: error executing command external/local_jdk/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' -cp ... (remaining 4 argument(s) skipped)
Exception in thread "main" java.lang.AssertionError: 
Could not find java.lang.Object on bootclasspath; something has gone terribly wrong.
Please file a bug: https://github.com/bazelbuild/bazel/issues
	at DumpPlatformClassPath.writeEntries(DumpPlatformClassPath.java:136)
	at DumpPlatformClassPath.writeClassPathJars(DumpPlatformClassPath.java:174)
	at DumpPlatformClassPath.dumpJDK8BootClassPath(DumpPlatformClassPath.java:77)
	at DumpPlatformClassPath.main(DumpPlatformClassPath.java:65)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Sorry, I don't know of a simple repro. This is happening in one of the TensorFlow CI builds. Full logs are [here](https://source.cloud.google.com/results/invocations/33b5588e-fb89-4020-8da7-dee299476384)

### What operating system are you running Bazel on?
Ubuntu 16.04

### What's the output of `bazel info release`?
```
$ bazel info release
release 3.7.2

$ java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

The issue does not reproduce consistently (about 50% flaky) and started appearing when we switched the OS image to one with a newer CUDA version (I don't know exactly what else could have changed, I checked that the java version is the same).

**Comment by meteorcloudy** [comment]
@comius Any idea on this issue?

**Comment by hyeygit** [comment]
Is anyone looking at the issue? Could someone help find an assignee possibly?

**Comment by meteorcloudy** [comment]
Ping @comius @cushon

**Comment by meteorcloudy** [comment]
It's mostly like something is wrong with the JDK installed. I reply to the internal issue and hopefully we can find a way to debug this.

**Comment by comius** [comment]
The issue has been resolved internally by using JDK11.

There are inherently problems using JDK8, because tensorflow is using `distinct_host_configuration=false` configuration flag, which "melds" together JDK11 that's part of Bazel and JDK8 on the local system. Without flag compilation takes substantially longer time.
