### ISSUE TITLE
Documentation issue: Starlark language says that lambdas aren't supported

### ISSUE THREAD

**Issue by nothorian** [bazelbuild/bazel#13249]
Documentation URL: https://docs.bazel.build/versions/master/skylark/language.html

In the "Differences with Python" section:
"lambda and nested functions."

But lambdas are now supported: https://github.com/google/skylark/blob/master/doc/spec.md#lambda-expressions

**Comment by brentleyjones** [comment]
@Wyverald To prevent https://docs.bazel.build/versions/5.0.0/skylark/language.html (once it exists) from saying the wrong thing, should this be cherry-picked into 5.0.0?
