### ISSUE TITLE
AutoML zero error

### ISSUE THREAD

**Issue by Modu03** [bazelbuild/bazel#13244]
**This error is coming while executing the run_demo.sh file.
Is there any issue with bazel version?**

![image](https://user-images.githubusercontent.com/31035583/111775556-ec135180-88d6-11eb-819a-f9dfb96a1e4b.png)

![image](https://user-images.githubusercontent.com/31035583/111775601-fa616d80-88d6-11eb-82aa-961a31a4648e.png)

**Comment by oquenchil** [comment]
Please use the template for filing issues. Among the information required is the command line used and clear instructions for reproducing.

What is AutoML and the run_demo.sh file? I don't see such file in the Bazel codebase. Should this issue be filed against other project?
