### ISSUE TITLE
Unpacking certain tar archives fail on case insensitive filesystems

### ISSUE THREAD

**Issue by nresare** [bazelbuild/bazel#13268]
### Description of the problem:

Certain tar archives will currently fail to unpack with trunk bazel on popular systems with case insensitive file systems, instead failing with an `IOException Permission denied`. To the casual user, this problem is a bit tricky to get to the bottom of as the failure happens early in bazel execution and the `tar.gz` referenced unpacks successfully using the `tar` utility present on the system.

While it might seem like an esoteric set of conditions that wold trigger this unfortunately some toolchain archives, notably ones containing the linux kernel headers, will typically have restrictive file permissions and contains files that only differs by case. Unpacking such archives will currently fail with bazel on macOS installed with the default case insensitive file system.

### Feature requests: what underlying problem are you trying to solve with this feature?

The underlying problem is that the unpacking code iteratively applies file permissions which prevents later files with names shadowing earlier ones from overwriting those files as there might now exist a file without write permission in the place where the unpacker expects to be able to unpack the next file.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Unpacking any tar file with two files that differs only in letter case with restrictive permissions will fail.
I have created a branch with a commit containing a test case that exercises this problem at it's tip:
https://github.com/nresare/bazel/tree/case_sensitive_files_in_archive_testcase
(please note that I have not yet figured out the details on how to get on the list for the Corporate CLA, and also we might want to do some refactoring) 

### What operating system are you running Bazel on?

macOS Big Sur 11.2.3

### What's the output of `bazel info release`?

I originally reproduced the problem with `release 4.0.0-homebrew`, but I constructed the test case
using latest master, b65e38d at the time of writing.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

This was triggered using a repository not publicly available.

###  Have you found anything relevant by searching the web?

I did try to see if if this was already reported, but going through all bazel issues with the word `insensitive` revealed nothing.

### Any other information, logs, or outputs that you want to share?

Addressing the problem is fairly straight forward, but the naive solution (checking for file existence and changing permissions before writing onto any existing files) would cause some extra IO that can be avoided. 

To my mind, the best solution would be to
* catch IOExceptions arising from opening the output file stream in truncating write mode
* check whether `filePath.toFile().getCanonicalPath()` returns a value different from filePath's absolute path
* if it doesn't, re-throw the exception. If it does, delete the file and re-attempt to write to it

**Comment by aiuto** [comment]
I assume this is in the context of an HTTP archive, so I sent it to external deps.
Personally, I think this is not Bazel's problem. There is no good way to win with most development tools using case-insensitive file systems.

**Comment by nresare** [comment]
Thank you for tagging it to the right recipient. It is in the context of an http archive, yes.

I can definitely agree that in an ideal world, everyone would 1) have their filesystem be case sensitive and 2) have their toolchain tarballs be set up such that they could be unpacked using bazel (u+w permission everywhere) but I think that there is an argument to be made that bazel can be user friendly in cases where neither of these two are feasible. Having unpacking tar files with bazel behaving like unpacking tar files with the system shipped `tar` tool seems to me to be desirable if there is no performance impact.

It can also be noted that there is special code to handle case insensitive file systems in CompressedTarFunctionTest already present for dealing with symlinks in `CompressedTarFunction`, so there is  a precedent.

**Comment by Wyverald** [comment]
Happy to accept a PR, but otherwise we probably won't have the bandwidth to work on this.

**Comment by aiuto** [comment]
Going back to the original problem and the test case
```
$ tar tzvf Downloads/case_sensitive.tar.gz
drwxrwxr-x  0 noa    noa         0 Mar 25  2021 dir/
-r--r--r--  0 noa    noa         4 Mar 25  2021 dir/a.txt
-r--r--r--  0 noa    noa         4 Mar 25  2021 dir/A.txt
```
There is no generic solution for this. As the file exists, it requires a case sensitive file system. Doing anything to elide a.txt and A.txt presupposes that they are identical. If they were not, there could be many  possible "right" things to do. For example. 
- if the content were the same, you might just leave one. But what if the permissions were different? Which do you pick
- if A.txt were content and a.txt was `#include "A.txt"`, then you would just leave A.txt. 
- if A.txt was a symlink to a.txt, then you can drop the symlink, and use a.txt's file mode
- if they had totally different content, then fail the build? Maybe have a rename map?  But at that point you are better off vendoring the library in and making your local workaround explicit.

**Comment by aiuto** [comment]
> Aligning the tar expansion semantics with the operating system provided tar tool seems aligned with the principle of least astonishment.

I don't agree. It might be least astonishing to a single user on a single OS, but that is not the Bazel use case.  The capability we aim for is that an organization can have developers using all platforms and doing remote build on servers of any OS, targeting any other OS. We need to have semantics that works the same on all platforms.
