### ISSUE TITLE
PersistentStringIndexer should keep the journal if it is small

### ISSUE THREAD

**Issue by oehme** [bazelbuild/bazel#13272]
As mentioned in #13271, I'm writing tests for a system that integrates with Bazel and I'm trying to make my tests as fast as possible. I've noticed that saving the filename index takes a considerable amount of time for small changes. I dug into the code and found that the action map [keeps its journal](https://github.com/bazelbuild/bazel/blob/8346ea4cfdd9fbd170d51a528fee26f912dad2d5/src/main/java/com/google/devtools/build/lib/actions/cache/CompactPersistentActionCache.java#L105) as long as it is less than 1% of the whole cache size. The filename index [does not](https://github.com/bazelbuild/bazel/blob/8346ea4cfdd9fbd170d51a528fee26f912dad2d5/src/main/java/com/google/devtools/build/lib/actions/cache/PersistentStringIndexer.java#L141) have that same optimization. I suggest that it should do the same, to speed up scenarios that run many small builds in quick succession (i.e. tests for Bazel itself).

Here's a [flame graph](https://github.com/bazelbuild/bazel/files/6216386/bazel-flamegraph.html.gz) showing what happens when I run many builds in the same workspace, each build touching a single Java file.

**Comment by larsrc-google** [comment]
The tests for Bazel itself actually mostly start a fresh Bazel, for hermeticity reasons, so they wouldn't benefit much from this. I'm curious what forces you to run each test as a separate Bazel invocation (IIUC), that's definitely not the behaviour that Bazel optimizes for.

**Comment by oehme** [comment]
> The tests for Bazel itself actually mostly start a fresh Bazel, for hermeticity reasons, so they wouldn't benefit much from this.

My tests reuse the workspace and output base for performance reasons. They just clean up the project-specific parts in between test methods. Waiting several seconds per test case for Bazel to start up and do all its analysis again is not an option for me, as I expect to have 1000+ test cases, just like we have for Maven and Gradle integration.

> I'm curious what forces you to run each test as a separate Bazel invocation (IIUC), that's definitely not the behaviour that Bazel optimizes for.

I think you misunderstood what I'm doing - My tests invoke Bazel, not the other way round :)

**Comment by oehme** [comment]
I can send a PR for this change if you'd like.

**Comment by larsrc-google** [comment]
Yes, please!

-Lars
