### ISSUE TITLE
The G3_BUILD_TARGET, G3_TARGET_NAME and GPLATFORM are passed with escape characters on Windows

### ISSUE THREAD

**Issue by ozio85** [bazelbuild/bazel#13277]
### Feature requests: what underlying problem are you trying to solve with this feature?
The the values of the following flags:
-DG3_BUILD_TARGET=\\"bazel-out/path_to_my_binary:target\\"
-DG3_TARGET_NAME=\\"@workspace//path_to_my_binary:target\\"
-DGPLATFORM=\\"my_platform\\"

Are passed to the compiler with escape character (\\" instead of ") on Windows.

It seems like:
src\main\java\com\google\devtools\build\lib\rules\cpp\CppLinkstampCompileHelper.java
has OK escaping, but another layers seems to add another layer of escaping on Windows, havn't really gone further right now.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

bazel build a binary on windows

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

4.0.0

**Comment by aiuto** [comment]
This may depend on what your command interpreter is.
With bash, bazel build **-Dfoo=\"bar\"**   would result in   **foo** having the value **"bar"**, so it should be escaped when passed to a subprocess.
Are you using cmd.exe or something else?

**Comment by ozio85** [comment]
These options are internal Bazel flags added on linkstamp compilation

**Comment by ozio85** [comment]
These options are internal Bazel flags added on linkstamp compilation

**Comment by aiuto** [comment]
Then this is the C++ team's problem. Re-triaged
