### ISSUE TITLE
FilesystemValueChecker should use a shared Thread pool

### ISSUE THREAD

**Issue by oehme** [bazelbuild/bazel#13271]
I'm writing tests for a system that interacts with Bazel and I'm trying to get the test times as low as possible. I got to a minimum of 30ms for a no-op Bazel invocation. About 20ms are spent in `handleDiffs` (even when nothing has changed). During profiling I noticed that [FilesystemValueChecker creates new threads on every build](https://github.com/bazelbuild/bazel/blob/1e7e51978a4872a28b8354a73aeba46c0c541e8b/src/main/java/com/google/devtools/build/lib/skyframe/FilesystemValueChecker.java#L207). I think this thread pool should be created once and reused rather than being recreated on every call to that class. This will mostly be visible in testing scenarios like mine, but would also marginally improve real world build times.

Here's a [CPU flame graph](https://github.com/bazelbuild/bazel/files/6216171/bazel-flamegraph.html.gz) of my tests running a ton of tiny builds. There are a couple other places that create new executors on every build, but the above-mentioned one is the most prominent.

**Comment by meisterT** [comment]
@oehme did you verify that after keeping the threadpool around it's actually any faster?

**Comment by oehme** [comment]
[Yes, significantly so.](https://github.com/bazelbuild/bazel/files/6242495/profiles.zip)

The reason is simple: The default size for this thread pool is 200 threads, which Bazel eagerly starts at the beginning of each build. That takes a long time. Reusing that thread pool completely removes that cost.

**Comment by meisterT** [comment]
I am confused - the line that you link above in the `FilesystemValueChecker` is not controlled by any flag (and is not 200), but depends on the number of cores on the machine, see line 190. What am I misunderstanding? Feel also free to just send a PR (if you already have one).

**Comment by oehme** [comment]
Sorry I had linked the wrong executor line, here's the [right one.](https://github.com/bazelbuild/bazel/blob/1e7e51978a4872a28b8354a73aeba46c0c541e8b/src/main/java/com/google/devtools/build/lib/skyframe/FilesystemValueChecker.java#L587). The argument applies to any thread pool though - If it is unlikely to change size between builds, it should probably be reused.

I don't have a PR, I only quickly hacked something together with a static variable.

**Comment by larsrc-google** [comment]
ThreadPoolExecutor doesn't create these threads eagerly, but only by need. Are you saying that setting the size of the thread pool to 1 makes it faster? Is the flag you mention `--experimental_fsvc_threads`?

**Comment by oehme** [comment]
Yes, that's the flag and yes it makes it faster, as you can see in the profiles I've provided above. You're right that it might not eagerly start them, but simply pushing a bunch of requests into that thread pool will start a ton of threads given the high core pool size. I assume these requests are for external locations that Bazel doesn't use file system watching for.

**Comment by oehme** [comment]
Another option (if you don't want the complexity of a reused pool) would be to have a smaller core pool size (say, number of processors) and a high max size. That way it would only start up lots of threads if there is significant work to do. I haven't tried this, but it might be a good balance.

I can send a PR if you'd like.
