### ISSUE TITLE
Add capability to serve head docs as https://docs.bazel.build/versions/head/...

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#13289]
This is a would be a convenient first step towards #12200 
- versions/master/... and versions/head/... would both serve the same document
- this allows us to change all of the /docs/... tree and bazel-website before renaming the branch itself.

Next steps after all .md files are fixed
- in Bazel CI, push tarball under the new branch name
- eventually, stop serving the old links.

@philwo @floriographygoth 

Design questions
- Is the current "master" version "head" or "nightly" or "latest release".   I could not tell from looking at the doc building scripts.

**Comment by fweikert** [comment]
Master (now "main") corresponded to head. Closing this issue since we're deprecating docs.bazel.build soon.
