### ISSUE TITLE
Documentation issue: Remote caching does not explain how caching works

### ISSUE THREAD

**Issue by weegreenblobbie** [bazelbuild/bazel#13282]
Documentation URL: https://docs.bazel.build/versions/master/remote-caching.html

I'm looking for information on how caching works, for example, if I build an executable, which has objects and library dependencies, will bazel check for the executable in the cache first and just pull that binary on cache hit?  Or does it always evaluate all actions and either builds or pulls the outputs for all actions?  Please add these details to the docs or a link to them from the remote-caching page.

**Comment by meisterT** [comment]
cc @coeuvre

**Comment by coeuvre** [comment]
It depends:
  - If you build from scratch (clean build), Bazel will evaluate all actions and pull the outputs of actions which hit the remote cache.
  - If you build incrementally (build, edit, build), Bazel will only evaluate targets which are transitive dependencies of changed files, and pull outputs from remote cache if neccessary.

**Comment by sgowroji** [comment]
Hello @weegreenblobbie, Did you get a chance to go through the above [comment](https://github.com/bazelbuild/bazel/issues/13282#issuecomment-822210149). Please feel free to reopen the above issue, if your query is not resolved. Thanks!

**Comment by weegreenblobbie** [comment]
No, the comment doesn't actually explain what happens.  Building from scratch, I'd expect object files get produced from compiling c++ code for example, these get composed into an executable.

Now if I make another edit, I'd expect the same thing to happen when I build again, the compiler is invoked creating object files, these get composed into an executable.

What happens if I hit CTRL+Z to undo my changes since I built last?  I'd expect no compiling or linking will occur, since it should be a cache hit.  Is there any documentation that explains what happens?  A link to source code may be helpful here.

Thanks!
