### ISSUE TITLE
C:/tools/msys64 is not properly expanded [Bazel 0.2.3 on Windows]

### ISSUE THREAD

**Issue by jameslarus** [bazelbuild/bazel#1328]
In /tools/cpp/CROSSTOOL for local_windows_msys64, the directory path

   cxx_builtin_include_directory: "C:/tools/msys64/"

is not properly expanded and causes numerous errors of the form:

this rule is missing dependency declarations for the following files included by 'src/main/tools/process-tools.c':
  '/c/tools/msys64/usr/lib/gcc/x86_64-pc-msys/5.3.0/include/stddef.h'
  '/c/tools/msys64/usr/lib/gcc/x86_64-pc-msys/5.3.0/include/stdarg.h'
  '/c/tools/msys64/usr/lib/gcc/x86_64-pc-msys/5.3.0/include/stdbool.h'.

Replacing the directory path by

   cxx_builtin_include_directory: "/c/tools/msys64/"

fixes the problem and enables building bazel on Windows.

**Comment by dslomov** [comment]
I believe this is fixed at HEAD
