### ISSUE TITLE
bazel does not honour certain mac qos settings

### ISSUE THREAD

**Issue by dmaclach** [bazelbuild/bazel#13291]
Bazel does not honour certain mac quality of service settings (notably user-interactive, user-initiated, default). The posix spawn APIs on Darwin do not let you set those levels.

It appears that https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/blaze_util_darwin.cc#L203 is expecting `posix_spawnattr_set_qos_class_np` to return a -1 on error when it actually returns an errno value (in these cases EINVAL).

**Comment by aiuto** [comment]
@susinmotion

**Comment by Wyverald** [comment]
Hmm, it looks like this is actually already fixed in https://github.com/bazelbuild/bazel/commit/688a2376d997dfa795c02eb475ae8a4204d1ba37. Closing for now.
