### ISSUE TITLE
Documentation: default values of git_repository attributes - init_submodules

### ISSUE THREAD

**Issue by uday-cb** [bazelbuild/bazel#13293]
This is purely related to the documentation at
https://docs.bazel.build/versions/master/repo/git.html
Can this doc specify what the default values of some of key attributes are? For eg., it's not clear what the default value for `init_submodules` is, which may be pretty important to know. I assume the default is to not clone submodules. On this note, cloning submodules is different from "init" (one can init but not clone). If this option is really about cloning submodules, shouldn't it be `clone_submodules`?

```
init_submodules 
Boolean; optional Whether to clone submodules in the repository.
```

**Comment by Wyverald** [comment]
For optional Boolean attributes the default is always `False` unless otherwise specified. I believe `init_submodules` is simply named after [`git submodule init`](https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt-init--ltpathgt82308203) command.
