### ISSUE TITLE
No way to add generated metadata files to InstrumentedFilesInfo

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/bazel#13292]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Currently there is no constructor available for InstrumentedFilesInfo and coverage_common.instrumented_files_info does not allow a way to add generated files. For example, if my rule implementation generates .gcno files, then there is no way to add these to the metadata_files field of the provider. I suppose this will also be a problem when rules_cc actually switches to Starlark based implementations.

### Feature requests: what underlying problem are you trying to solve with this feature?

This feature will allow coverage information to be communicated uniformly.

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

release 4.0.0

###  Have you found anything relevant by searching the web?

No relevant discussion for generated metadata files anywhere.

**Comment by tomdegoede** [comment]
Exposing the metadata fields in Starlark would be beneficial for custom coverage rules we are implementing as well.

**Comment by fmeum** [comment]
Fixed at HEAD: https://bazel.build/rules/lib/toplevel/coverage_common
