### ISSUE TITLE
sigaction(sig, &sa, NULL): Invalid argument

### ISSUE THREAD

**Issue by jart** [bazelbuild/bazel#1330]
I noticed a build flake where this happened:

```
ERROR: /home/travis/build/bazelbuild/rules_closure/closure/templates/test/BUILD:63:1: Compiling 903 JavaScript files to closure/templates/test/greeter_idom_test_bin.js failed: compiler failed: error executing command 
[...]
com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
src/main/tools/process-tools.c:87: sigaction(sig, &sa, NULL): Invalid argument
```

https://travis-ci.org/bazelbuild/rules_closure/builds/134718996
https://github.com/bazelbuild/bazel/blob/4b5992929d5e59d76db132a77a7d7ecc786aef90/src/main/tools/process-tools.c#L87

The sigaction man page is illuminating:

> EINVAL: An invalid signal was specified.  This will also be generated if an attempt is made to change the action for SIGKILL or SIGSTOP, which cannot be caught or ignored.

Maybe Travis sent one of those signals and then process-wrapper.c or namespace-sandbox.c tried to call `UnHandle` to instate the default handler on them? I've only glanced at the code.

**Comment by jart** [comment]
It [keeps happening](https://travis-ci.org/bazelbuild/rules_closure/builds/134727307) :(

Two things to take into consideration:

1. I just enabled Bazel workers on my project a few hours ago.
2. My Travis CI is a heavily constrained 256MB VM where Bazel runs with `--local_resources=1000,1,1.0`.
3. This error happens at the fifteen minute mark, which is right when you'd expect the entire thing to be finished, based on [build timing history](https://travis-ci.org/bazelbuild/rules_closure/builds).

**Comment by jart** [comment]
Update: When I turned off workers in my Travis CI config, this problem went away.

**Comment by dslomov** [comment]
@philwo @hermione521 I added "sandboxing" because  we do not have "workers". Could you take a look? Seems blocking for workers on CI.

**Comment by philwo** [comment]
@jart I think your idea is good - we don't check the signal that we try to "UnHandle", so if it is SIGSTOP or SIGKILL, this would throw the error.

I have no clue why it only happens with workers enabled, but let's see what output we get when that is fixed. :) I'll send a patch today.

**Comment by philwo** [comment]
Patch sent for code review.

**Comment by philwo** [comment]
@jart Could you please try if workers are fine now on your Travis CI? If they still fail, it would be very interesting to get the error output (which I expect to be different after the change :)).

**Comment by jart** [comment]
I can only do that if you cut a release.

**Comment by damienmg** [comment]
Can't you install from a ci.bazel.io artifact?
http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=linux-x86_64/lastSuccessfulBuild/artifact/output/ci/bazel--installer.sh

**Comment by jart** [comment]
It seems ok so far.
