### ISSUE TITLE
Wrong line number reported for `type 'string' is not iterable` errors

### ISSUE THREAD

**Issue by tetromino** [bazelbuild/bazel#13304]
Consider the following .bzl file with an attempt to iterate over the characters of a string in the inner loop:

```
def my_func():
    for i in range(10):
        for j in "foo":
            pass
    return 42
```

When we try to use my_func from a BUILD file, we will get the following confusing error, implying that the problem is with the completely legal `range(10)` expression in the  _outer_ loop:

```
ERROR: Traceback (most recent call last):
	File "/home/me/tmp/BUILD", line 6, column 19, in <toplevel>
		args = my_func(),
	File "/home/me/tmp/my.bzl", line 2, column 5, in my_func
		for i in range(10):
Error: type 'string' is not iterable
```

By contrast, other kinds of type errors have the line number reported correctly. For example, if we have

```
def my_func():
    for i in range(10):
        for j in "foo"["bar"]:
            pass
    return 42
```

the error would be (correctly) reported as

```
...
	File "/home/me/tmp/my.bzl", line 3, column 23, in my_func
		for j in "foo"["bar"]:
Error: got string for string index, want int
```

Tested with Bazel 4.0.0 and current git HEAD.

**Comment by brandjon** [comment]
Discussed offline, sounds like we need to add a `setErrorLocation` call to a try/catch around the `toIterable` in `Eval#execFor`.
