### ISSUE TITLE
Workspace name warning when using local_repository

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#1331]
In my `WORKSPACE` I use the following:

    local_repository(
	name = "brotli",
	path = "3rdparty/brotli",
    )

The location `3rdparty/brotli` is mostly due to legacy reasons.
In `3rdparty/brotli` I do not have a `WORKSPACE`.

When executing `bazel build` it warns:

    Workspace name in /home/andreas/.cache/bazel/_bazel_andreas/e95e268031a1536aa07d29382953e9de/external/brotli/WORKSPACE (@__main__) does not match the name given in the repository's definition (@brotli); this will cause a build error in future versions.

which IMO makes no sense because my intention was to make `3rdparty/brotli` accessible as `brotli` no matter what a `3rdparty/brotli/WORKSPACE` defined.
Now the question is, how do I do this in a way that it will work in future releases, too?

**Comment by kchodorow** [comment]
You can say:

```
new_local_repository(
    name = "brotli",
    path = "3rdparty/brotli",
    # Depending on whether 3rdparty/brotli/BUILD exists, either
    build_file = "3rdparty/brotli/BUILD" # Reuse the existing BUILD file
    # or
    build_file_content = "" # Create an empty BUILD file
)
```

**Comment by abergmeier** [comment]
That does erase the warnings. A little annoying that I have to explicitly tell it to use the `BUILD` file. Thanks.
