### ISSUE TITLE
Provide an option to run bazel server as a container 

### ISSUE THREAD

**Issue by xyt0056** [bazelbuild/bazel#13318]
### Description of the problem / feature request:
We use docker containers to test our builds in CI and use bazel query to query the targets needed to be tested. However, since our monorepo is large containing hundreds of project, we found that the query takes long to finish in each container; compared to if we run the job directly on host without docker, subsequent queries can take advantage of previous bazel query and finish fast. It's maybe because our bazel server is started in container, when container is terminated, the internal state in memory is thrown away and ifnotify is stopped too

Since bazel has Client/server implementation. Do you think it's beneficial to provide an option to isolate the server components out as a service? So that we can run it on CI as a long running container and let it share query memory. 

I'm also curious how others deal with this issue or if there's an existing solution with containerization.

### Feature requests: what underlying problem are you trying to solve with this feature?

different containers  can share the same bazel server, reducing CI jobs overhead.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
specific to our scenario
we just run docker-compose -f config.yml run ...

### What operating system are you running Bazel on?

Amazon Linux AMI 2

### What's the output of `bazel info release`?

release 3.7.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

###  Have you found anything relevant by searching the web?

no

**Comment by haxorz** [comment]
Hi @xyt0056, thanks for the FR.

Something like "Bazel-query-as-a-service" or even "Bazel-as-a-service" would be cool to have. This would be a very big undertaking though. Bazel is designed to be used as a single long-running server process, not as a single node in a distributed network of Bazel instances [running in containers]. I added the label "P4" to reflect the amount of work this would involve.

> I'm also curious how others deal with this issue or if there's an existing solution with containerization.

`team-Core` doesn't have insight into the various ways Bazel is used. So I think the next steps here would for a Bazel product stakeholder to do some research.
