### ISSUE TITLE
Bazel head breaks RBE tests

### ISSUE THREAD

**Issue by agoulti** [bazelbuild/bazel#13321]
This is a tracking bug to ensure that all the fixes are cherrypicked into the release.

**Comment by meisterT** [comment]
Can you please be more specific. What is broken, what needs to be cherry picked? Is it broken in 4.0?

**Comment by meisterT** [comment]
cc @philwo

**Comment by coeuvre** [comment]
This is referring to recent changes to output paths semantics.

These changes aren't included in 4.1 release but in the future if we release 7149f578006a4ad0d51df69830a6986749b34df5, make sure to include others 24c980b6d4adef456cf4b4f84ac3b8ec4580b172, e6f1066deef066df82e3e2771ef521c03c252f01, 4efeac9cb5f85325ed73f64e133a078c483cac01 and #13339.

**Comment by katre** [comment]
@coeuvre Can you confirm that this is fine and the needed cherrypicks are present?

**Comment by coeuvre** [comment]
Yes, the needed cherrypicks are included.

**Comment by sethkoehler** [comment]
Just to verify, I was clicking on the cherrypicks and the last one was a PR (#13339).  Unlike the other entries (e.g., https://github.com/bazelbuild/bazel/commit/4efeac9cb5f85325ed73f64e133a078c483cac01), I didn't see a label indicating this was included in 5.0.0-pre.20210708.4 (when I clicked on specific commits in https://github.com/bazelbuild/bazel/pull/13339/commits), I noticed there was a warning banner saying certain commits weren't included in any release (e.g., https://github.com/bazelbuild/bazel/commit/6636dc2026b67d3afd31e68d12a9f278ae38f17d)?  I am probably using github wrong (I don't have much experience with it), but just wanted to double check the last set of commits really is included in the release?

**Comment by katre** [comment]
@sethkoehler Because of the degree of divergence between 4.2.0 and 5.0.0-pre, the commits require changes to merge cleanly. This changes the commit id and causes git to report that it is only on the release branch. These are still cherrypicked commits from the master branch on bazelbuild/bazel.

Some commits are also fixes for specific release blockers and may not yet be in a released version of Bazel.

**Comment by sethkoehler** [comment]
Ok, glad to hear all is well, thank you for confirming those commits are indeed in the upcoming 5.0.0 release!
