### ISSUE TITLE
FR: Make it easy to run `clang-tidy` with bazel

### ISSUE THREAD

**Issue by devjgm** [bazelbuild/bazel#13337]
### Description of the problem / feature request:

Feature Request

### Feature requests: what underlying problem are you trying to solve with this feature?

I want to run `clang-tidy` over my large C++ project. It's easy to do with CMake, but I don't know how to do this with bazel.

I *do* know how to use https://github.com/grailbio/bazel-compilation-database to get a compilation DB out of bazel, but that's a bad solution for clang-tidy because then I have to run clang-tidy on *every* file. This is too slow.

The value/beauty of bazel is its awesome dependency analysis handling, and bazel _could_ do an awesome job of only running clang-tidy on translation units that possibly changed, and skipping it on all unchanged things. This would greatly speed up clang-tidy runs.

### What operating system are you running Bazel on?

Linux, macOS

### What's the output of `bazel info release`?

release 4.0.0 

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git@github.com:devjgm/google-cloud-cpp.git
39e0065a9634e4ed2f4c8bd1ee3a12fa28384068
1938682b3dcd5109727993b46fb3d79ab51b055b

###  Have you found anything relevant by searching the web?

* https://github.com/erenon/bazel_clang_tidy looks cool, but it appears to be untouched for a year and I couldn't get it to work.
* https://github.com/grailbio/bazel-compilation-database works for outputting a compile_commands.json file, but again this is NOT the feature request here.

### Any other information, logs, or outputs that you want to share?

Not that I can think of.

**Comment by theimeto** [comment]
I believe action listener is the most reasonable approach:

`bazel build --experimental_action_listener=<clang_tidy_listener> foo:bar`

Where `clang_tidy_listener` is target in some BUILD file as:
```
action_listener(
   name = "clang_tidy_listener",
   extra_actions = [":clang_tidy_action"],
   mnemonics = ["CppCompile"],
)
extra_action(
  name = "clang_tidy_action", 
  cmd = "$(location :clang_tidy_launcher)  $(EXTRA_ACTION_FILE)",
  data = [ 
       ":clang_tidy_launcher",
      "//third_party/llvm:clang-tidy",
   ]
)
```

The `clang_tidy_launcher` will be invoked (in parallel with the normal build action) with a filepath to a serialized `ExtraActionInfo` proto and in an environment identical with the build action (i.e. all headers, sources will be accessible). From the serialized proto one can reach to the command line for the build action -- for C++ there is `CppCompileInfo` extension.

With the above in hand: construct clang_tidy launch options and ultimately invoke the clang_tidy binary.

A few tips:
- probably want `--extra-arg -Wno-unknown-warning-option`
- probably need `--extra-arg-before -isystem <CLANG_INCLUDE_DIR>`
- may need to invent own suppression policy based on source filename/path.

 `clang_tidy_launcher` can be  written in arbitrary language - python, go, c++ and will be build by Bazel. Alternatively one can use a precompiled binary.

**Comment by colatkinson** [comment]
I actually implemented something like this, though it's admittedly a bit of a hack: https://git.sr.ht/~colatkinson/boios/tree/92371b4219d18b1c09ec82edcaa9855b5134138e/item/utils/rules/clang_tidy.bzl

`clang-tidy` runs are represented as tests, and are attached to each target via a macro. Notably it does one run per target, not per TU, though I think that could be changed.

It leverages the compdb rules that were linked above to generate a `compile_commands.json` for each target. This isn't strictly necessary, but let me avoid reimplementing all the [arg extraction logic](https://github.com/grailbio/bazel-compilation-database/blob/aa58494efdf31c3e3525832b3d44d48bb3bc2b0b/aspects.bzl#L161) in its `aspect()`.

Obviously the fact that it every `cc_*` target has to be wrapped in a macro, among other things, kinda precludes it from being a drop-in solution. But I figured it might serve as inspiration for anyone looking for a stopgap solution.

---

@theimeto It looks like [action listeners are marked as deprecated](https://docs.bazel.build/versions/master/be/extra-actions.html#action_listener) in the latest docs. I think an `aspect()` could achieve a pretty similar result, although admittedly I'm not super familiar with either API.

**Comment by devjgm** [comment]
Thanks for the ideas and inspiration @theimeto and @colatkinson. Those may be good ideas for the bazel team. However, I want to make it clear that this Feature Request is

... for the **bazel team** to provide an **easy out-of-the-box** solution for users run clang-tidy over their code.

Like, I want to run something like `bazel test --run_checker=clang-tidy //...` (I made up the `--run_checker` flag for this example).

**Comment by erenon** [comment]
FTR, there's also https://github.com/erenon/bazel_clang_tidy
