### ISSUE TITLE
`--modify_execution_info` should be additive

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/bazel#13342]
### Description of the problem / feature request:

Calling `--modify_execution_info` multiple times results in the last version being used, instead of allowing the addition/removal of current execution info. It should be additive, or a new flag should exist that allows it to be called multiple times.

### Feature requests: what underlying problem are you trying to solve with this feature?

In different `--config` we want to set different execution info. In particular, when conditionally using remote execution, and conditionally running on CI, we want to set different execution info.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 4.0.0

**Comment by brentleyjones** [comment]
This is still pretty annoying for us. We've had to switch in conditionally importing different `.bazelrc` based on if we are using remote exec or not.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.2.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.2.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.2.0rc1. Thanks!
