### ISSUE TITLE
Documentation issue: Macros

### ISSUE THREAD

**Issue by jayeye** [bazelbuild/bazel#13345]
Documentation URL: https://docs.bazel.build/versions/master/skylark/macros.html

Where does `native` come from? I get
`ERROR: /home/ji/foo/src/WORKSPACE:131:5: name 'native' is not defined`

**Comment by jin** [comment]
`native` can only be used in `.bzl` files, not WORKSPACE or BUILD. Perhaps we can improve the documentation to add a note about where `native` can be used? cc @communikit
