### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#1334]

**Comment by dslomov** [comment]
/scripts/release/release.sh create 0.3.0 a9301fac1ab3e0b99aa86fd89dff31fd890641c3 ff30a7319fc495c1f2d4c58b233e7bd7690da27f

**Comment by dslomov** [comment]
./scripts/release/release.sh create 0.3.0 a9301fac1ab3e0b99aa86fd89dff31fd890641c3 ff30a7319fc495c1f2d4c58b233e7bd7690da27f aeee3b8e4cccc95fa7932fe45abbc6279bfb72d0

**Comment by damienmg** [comment]
And the release went through \o/
