### ISSUE TITLE
Documentation issue: Building JavaScript Outputs

### ISSUE THREAD

**Issue by brunobely** [bazelbuild/bazel#13350]
Documentation URL: https://docs.bazel.build/versions/master/build-javascript.html

From #6319:
> `%workspace%/tools/bazel.rc` is replaced by `%workspace%/.bazelrc`

But this docs page still uses the old file and Bazel issues a warning when running:

```
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/path/to/tools/bazel.rc
```

**Comment by jin** [comment]
cc @alexeagle
