### ISSUE TITLE
Feature request: support file deletion on docker_build

### ISSUE THREAD

**Issue by justinsb** [bazelbuild/bazel#1335]
Could we / should we add the ability to delete files from a docker layer as part of docker_build?

The primary use case I am thinking of is that we install a deb package, but then we remove e.g. the man pages or the locale files, so as to keep the image size small.

**Comment by mattmoor** [comment]
Moving to rules_docker issue: https://github.com/bazelbuild/rules_docker/issues/7

**Comment by mattmoor** [comment]
@damienmg I can't close bazel issues...

**Comment by damienmg** [comment]
I added you to the ACL you should be able to do so now.
