### ISSUE TITLE
Homebrew installation broken

### ISSUE THREAD

**Issue by wintermoon9** [bazelbuild/bazel#13353]
I am trying to install Bazel. I have successfully installed Bazel many times with this command. My CI started failing yesterday. It seems the OpenJDK is no longer at this URL ? 

`brew install bazel
`

I am getting this error.

```
==> Downloading https://homebrew.bintray.com/openjdk%4011-11.0.10.catalina.bottl
##O#- #                                                                       
curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://ghcr.io/v2/homebrew/core/openjdk%4011-11.0.10.catalina.b
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "openjdk@11"
Download failed: https://ghcr.io/v2/homebrew/core/openjdk%4011-11.0.10.catalina.bottle.tar.gz
```

What can we do about this ? I'm sure this must be effecting anyone trying to install bazel right now.

**Comment by tsawada** [comment]
Can [bazelisk](https://github.com/bazelbuild/bazelisk) be used as a workaround in your case?
`brew install bazelisk`

if not, this looks more like a homebrew issue so I recommend seeking help at homebrew community.

**Comment by Wyverald** [comment]
as @tsawada, please ask the homebrew community for help.
