### ISSUE TITLE
Custom toolchain & ccache don't mix.

### ISSUE THREAD

**Issue by vlovich** [bazelbuild/bazel#13367]
### Description of the problem / feature request:

There's no way to override the compiler used via CC/CXX environment variables to point to a compiler not on the path AND use ccache simultaneously. In other words, I want to CC to be invoked as "ccache <path to compiler>". bazel fails with:
`Error in which: Program argument of which() may not contain a / or a \ ('ccache /home/vlovich/myproject/deps/v8/third_party/llvm-build/Release+Asserts/bin/clang' given)`. If I pass the absolute path to ccache & the compiler, I get `src/main/tools/linux-sandbox-pid1.cc:390: "execvp(/usr/bin/ccache /home/vlovich/myproject/deps/v8/third_party/llvm-build/Release+Asserts/bin/clang, 0x55a24d245ff0)": No such file or directory`

Open to any solution although hopefully not one that I can enscone within our build system & ideally not one that requires me to muck about with the PATH (sccache is even trickier in this respect).

### Feature requests: what underlying problem are you trying to solve with this feature?

CMake offers a variable you can provide (`RULE_LAUNCH_COMPILE`) which is prepended to the compiler line without interfering with it.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

CC="ccache cc" CXX="ccache c++" bazel build ...

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 4.0.0

###  Have you found anything relevant by searching the web?

Not that I could find. All existing usages use the more common mechanism of having ccache's bin directory at the front of the path & the underlying compiler also on the path.

**Comment by chancila** [comment]
bazel already has caching mechanisms built in, both local and remote. Using ccache is unnecessary, add `--disk_cache` to enable it, there's also `--remote_cache`.

**Comment by vlovich** [comment]
Thanks.
