### ISSUE TITLE
Cannot run Bazel without /usr/bin/python, even if /usr/bin/python3 exists

### ISSUE THREAD

**Issue by ted-xie** [bazelbuild/bazel#13379]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Bazel relies on /usr/env/bin python, which no longer exists in the newest update to my operating system.

### Feature requests: what underlying problem are you trying to solve with this feature?

N/A.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Remove /usr/bin/python symlink and run literally any Bazel workload.

### What operating system are you running Bazel on?

Proprietary OS vaguely similar to Ubuntu 20.04.

### What's the output of `bazel info release`?

```
INFO: Invocation ID: f21f4240-c757-4848-ac49-2acef7ed1685
release 4.0.0
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A, using pre-built binary.

###  Have you found anything relevant by searching the web?

Looks like https://github.com/bazelbuild/bazel/issues/8665 was never *truly* fixed Bazel-side. Users should not have to create system-level symlinks to run Bazel.

### Any other information, logs, or outputs that you want to share?

N/A.

**Comment by keith** [comment]
This is a dup of https://github.com/bazelbuild/bazel/issues/8685

**Comment by ted-xie** [comment]
I acknowledge that but there has been little/no traction on that bug. I was hoping to revive the discussion/raise the visibility of this issue by filing a new bug.

**Comment by philwo** [comment]
Hey @ted-xie, I'm sorry that this still isn't fixed. We'll get to it hopefully soon.

**Comment by lberki** [comment]
It looks like this is fixed by https://github.com/bazelbuild/bazel/pull/13414 ?

**Comment by philwo** [comment]
@lberki Indeed! This looks like it might be an elegant fix for this :)

**Comment by sventiffe** [comment]
@philwo #13414 however stalled a while ago. Is anything preventing us from moving on? Would that PR also be included in a future 4.x update?

**Comment by philwo** [comment]
We need to merge that PR, I think it's the best fix we have.
