### ISSUE TITLE
How to use authorization when bazel build --remote_executor?

### ISSUE THREAD

**Issue by kekxv** [bazelbuild/bazel#13378]
### Description of the problem / feature request:

> How to use authorization when bazel build --remote_executor?

### Feature requests: what underlying problem are you trying to solve with this feature?

>  use authorization.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> bazel build --remote_executor.

### What operating system are you running Bazel on?

> MacOS m1

### What's the output of `bazel info release`?

> release 4.0.0-homebrew

### Any other information, logs, or outputs that you want to share?

> ```shell
> bazel build --tool_tag=ijwb:CLion --curses=no --color=yes --progress_in_terminal_title=no -- //...
> INFO: Invocation ID: 9655c35e-72a1-4eb9-8e34-3a2838477c3c
> ERROR: Failed to query remote execution capabilities: PERMISSION_DENIED: HTTP status code 403
> invalid content-type: text/html
> headers: Metadata(:status=403,server=nginx/1.18.0 (Ubuntu),date=Tue, 20 Apr 2021 01:22:31 GMT,content-type=text/html,content-length=162)
> DATA-----------------------------
> <html>
> <head><title>403 Forbidden</title></head>
> <body>
> <center><h1>403 Forbidden</h1></center>
> <hr><center>nginx/1.18.0 (Ubuntu)</center>
> </body>
> </html>
> ```

**Comment by kekxv** [comment]
In addition, when I use remote compilation, use mingw to compile in ubuntu. define the command like `wine ${command}` in cc_test when I execute it?

**Comment by kekxv** [comment]
> In addition, when I use remote compilation, use mingw to compile in ubuntu. define the command like `wine ${command}` in cc_test when I execute it?

`--run_under=wine` is working.
```
  | test:mingw32            --run_under=wine
  | run:mingw32             --run_under=wine
```

**Comment by kekxv** [comment]
is FAILED when run `bazel test:mingw32            --run_under=wine`?

remote test:
```log
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //Basic/serialport:serialport-test
-----------------------------------------------------------------------------
Running main() from gmock_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from CppHttplibTest
[ RUN      ] CppHttplibTest.Empty
2021-04-21 01:21:00[D][ logger:62 ]log save to Z:\tmp\worker\default_memory_instance\operations\f5d163fc-3138-4047-992f-f58ca6629058\bazel-out\mingw32-fastbuild\bin\Basic\serialport\serialport-test.exe.runfiles\TerminalService\Basic\serialport\logs\logging.log
2021-04-21 01:21:00[E][ serialportWin ]open serialport fail
2021-04-21 01:21:00[I][ serialportWin ]~serialportWin
[       OK ] CppHttplibTest.Empty (102 ms)
[----------] 1 test from CppHttplibTest (102 ms total)

[----------] Global test environment tear-down

[ FATAL ] external/com_google_googletest/googletest/src/gtest.cc:207:: Unable to open file "Z:\tmp\worker\default_memory_instance\operations\f5d163fc-3138-4047-992f-f58ca6629058\bazel-out\mingw32-fastbuild\bin\Basic\serialport\serialport-test.exe.runfiles\TerminalService\tmp\worker\default_memory_instance\operations\f5d163fc-3138-4047-992f-f58ca6629058\bazel-out\mingw32-fastbuild\testlogs\Basic\serialport\serialport-test\test.xml"
```

local test:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //Basic/serialport:serialport-test
-----------------------------------------------------------------------------
wineserver: error creating /run/user/1000/wine/server-b302-a0371/lock: Read-only file system
```

**Comment by coeuvre** [comment]
You can use `--remote_header` to pass authorization header. If your server accept username and password, `.netrc` can also be used.

**Comment by coeuvre** [comment]
As far as I know, wine is not supported.

**Comment by kekxv** [comment]
> You can use `--remote_header` to pass authorization header. If your server accept username and password, `.netrc` can also be used.

is working. 

https://github.com/bazelbuild/bazel-buildfarm/issues/756#issuecomment-847890721

**Comment by kekxv** [comment]
> As far as I know, wine is not supported.

wine is working, https://github.com/bazelbuild/bazel/issues/13378#issuecomment-823707998 like cannot read file?
