### ISSUE TITLE
Error: unexpected EOF from Bazel server

### ISSUE THREAD

**Issue by MaeThird** [bazelbuild/bazel#1338]
==> tensorflow : r0.9 bazel : 0.2.3 gcc:6.1.1 python: 3.5
When i try to compile tensorflow from source on my archlinux(kernel : 4.5.4-1) ,errror occured. Something like " Linking tensorflow/cc/ops/data_flow_ops_gen_cc [for host]
Error: nexpected EOF from Bazel server."

And when i tried again ,i got the same error :
tensorflow/core/kernels/reduce_join_op.cc:108:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for (int32 index = 0; index < index_is_reduced.size(); ++index) {
~~~~^~~~~~~~~~~~~~~~~~~~~~~
[1,652 / 2,403] Compiling tensorflow/core/common_runtime/simple_graph_execution_state.cc
Error: unexpected EOF from Bazel server.

Maybe there is a bug in GCC-6.1.1 ?? How can I change the default compiler ? Thanks

**Comment by meteorcloudy** [comment]
Hi, Damein. Can you take a look at this? /cc @damienmg

**Comment by damienmg** [comment]
Can you give me the output of:

```
cat  $(dirname $(dirname $(readlink bazel-tensorflow)))/java.log
cat  $(dirname $(dirname $(readlink bazel-tensorflow)))/server/jvm.out
```
?

**Comment by MaeThird** [comment]
Occupied by work during the past 3 days ,Sorry.
This is most likely to occur with "Out of memory". So I compiled it with "bazel build -c opt --jobs 20 ...",and everything is OK .

**Comment by damienmg** [comment]
\o/

Great to hear that --jobs did the work :)
