### ISSUE TITLE
specify `-Wl,-rpath,` with relative path

### ISSUE THREAD

**Issue by joehattori** [bazelbuild/bazel#13388]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

specify `-Wl,-rpath,` with relative path

### Feature requests: what underlying problem are you trying to solve with this feature?

Currently I cannot specify relative path to `-Wl, -rpath` in `linkopts` of `cc_library`.
If I need to specify it with absolute path, I couldn't figure out how to obtain `pwd` and embed it in `linkopt`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Please take a look at https://github.com/joehattori/wasmer-go/tree/support-bazel

### What operating system are you running Bazel on?

MacOS BigSur 11.2.3

### What's the output of `bazel info release`?

release 4.0.0-homebrew

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

- StackOverflow: https://stackoverflow.com/questions/67130317/how-can-i-control-what-symbols-are-exported-from-a-shared-library-in-bazel

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?
```
$ bazel test --test_output=errors //wasmer:wasmer_test
INFO: Analyzed target //wasmer:wasmer_test (0 packages loaded, 27 targets configured).
INFO: Found 1 test target...
FAIL: //wasmer:wasmer_test (see /private/var/tmp/_bazel_joe/717c1713f53d174ae144fec780230653/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/wasmer/wasmer_test/test.log)
INFO: From Testing //wasmer:wasmer_test:
==================== Test output for //wasmer:wasmer_test:
dyld: Library not loaded: @rpath/libwasmer.dylib
...
```
> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by sgammon** [comment]
@joehattori how did you solve this?
