### ISSUE TITLE
ERROR: error loading package '': in C:/users/windows10-desktop/_bazel_windows10-desktop/gbkcodrx/external/org_tensorflow/tensorflow/workspace.bzl: Extension file 'third_party/gpus/cuda_configure.bzl' has errors

### ISSUE THREAD

**Issue by halhwadi** [bazelbuild/bazel#13389]
### Description of the problem / feature request:

I'm trying to implement [tf3d](https://github.com/google-research/google-research/blob/master/tf3d/ops/README.md), by running the followings commands:
```
  ./configure.sh
  bazel build build_pip_pkg
  bazel-bin/build_pip_pkg artifacts
```

when ruuning `bazel build build_pip_pkg` I got the below error :
**_"ERROR: Traceback (most recent call last):
        File "C:/users/windows10-desktop/_bazel_windows10-desktop/gbkcodrx/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1390, column 40, in <toplevel>
                remote_cuda_configure = repository_rule(
Error in repository_rule: in call to repository_rule(), parameter 'remotable' is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_repo_remote_exec
INFO: Repository io_bazel_rules_closure instantiated at:
  C:/users/windows10-desktop/tf3d/ops/WORKSPACE:13:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/windows10-desktop/_bazel_windows10-desktop/gbkcodrx/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: error loading package '': in C:/users/windows10-desktop/_bazel_windows10-desktop/gbkcodrx/external/org_tensorflow/tensorflow/workspace.bzl: Extension file 'third_party/gpus/cuda_configure.bzl' has errors
INFO: Elapsed time: 19.224s"_**

### Feature requests: what underlying problem are you trying to solve with this feature?

> building the pip pkg

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> running the below line of code:
 `bazel build build_pip_pkg`

### What operating system are you running Bazel on?

> windows 10, CPU (No GPU)
when running configure.sh I select [y,y]

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> [bazel release 4.0.0]

**Comment by philwo** [comment]
Hi @halhwadi,

it seems like TensorFlow 2.3.0 is not yet compatible with Bazel 4.0.0. Could you please try the same with Bazel 3.1.0?

I found this information on the TensorFlow site about "Tested build configurations": https://www.tensorflow.org/install/source_windows#gpu.

Thanks! Please feel free to comment on this bug if it doesn't help and we can reopen it.

Cheers,
Philipp
