### ISSUE TITLE
Bazel 4.1.0rc4 fails to build on RBE

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#13397]
Hi @comius,

I noticed this breakage when building Bazel 4.1.0rc4 on RBE: https://buildkite.com/bazel/bazel-bazel-release-candidate/builds/2#3ed2a267-143a-4a85-bb22-1986d550e650

> (07:38:28) ERROR: Traceback (most recent call last):
> 	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/rbe_ubuntu1604_java8/java/BUILD", line 19, column 60, in <toplevel>
> 		load("@bazel_tools//tools/jdk:local_java_repository.bzl", "local_java_runtime")
> Error: file '@bazel_tools//tools/jdk:local_java_repository.bzl' does not contain symbol 'local_java_runtime'
> (07:38:28) ERROR: Analysis of target '//src:bazel_jdk_minimal' failed; build aborted: error loading package '@rbe_ubuntu1604_java8//java': Package 'java' contains errors

Any idea what it could be and how to fix it?

**Comment by comius** [comment]
@meteorcloudy already asked about that.

There is a condition in bazel_toolchains and in rules_appengine, that checks Bazel's version from it's label. If there is no label (or the version >=5.0.0), it uses changes that only work at HEAD.

**Comment by philwo** [comment]
Oh.. sorry. :/ I checked that the version of Bazel has a correctly embedded label:

```
bazel --nomaster_bazelrc --bazelrc=/dev/null version
  | Build label: 4.1.0rc4
```

But maybe the version check is broken and doesn't understand release candidates?

**Comment by philwo** [comment]
Indeed, they use `go-semver` to parse the Bazel version number, but because our release candidate version numbers are not valid SemVer versions (we use: `4.1.0rc4` but correct form would be `4.1.0-rc.4`), the parsing and ordering would not work correctly. If they had used https://github.com/hashicorp/go-version like we do in Bazelisk, it would be fine. We should change our release candidate numbers to follow correct SemVer with Bazel 5.0.0.

**Comment by philwo** [comment]
Thanks @comius for confirming that this is the same issue, I'll close this and ignore it then! 😊
