### ISSUE TITLE
Why dropped "clang module support" and "include scanning support"

### ISSUE THREAD

**Issue by bytearth** [bazelbuild/bazel#13392]
In the [roadmap](https://bazel.build/roadmaps/build-api.html), the state of feature which about "**clang module support**" and "**include scanning support**" turned to be dropped. I want to know what's going on, because these features are really powerful for us.

Have you encountered any difficulties, if so, could you tell me the detail of the reason you dropped these features.  If not, what's your plan?

I am looking forward to your reply, best wishes of you.

**Comment by oquenchil** [comment]
Priorities changed. We also have limited bandwidth in our team right now. Include scanning uses heuristics that cause builds to give really hard to track errors when outside the tightly controlled environment we have internally when it comes to headers. It was hypothesized that this would increase the amount of support that we have to give our users to a level that we cannot really afford right now.

Once rules are in Starlark and we can more easily accept contributions, we might revisit this idea.

For now we are implementing a change that has [this](https://github.com/bazelbuild/bazel/pull/8482) functionality. With the right build layout and a refactoring of your BUILD files you may be able to achieve results as good as include scanning.

**Comment by jwnimmer-tri** [comment]
> For now we are implementing a change that has 8482 functionality. With the right build layout and a refactoring of your BUILD files you may be able to achieve results as good as include scanning.

For anyone else who stumbled by here, a good search term for this new feature is `interface_deps` and is currently guarded by experimental flag `--experimental_cc_interface_deps`.
