### ISSUE TITLE
Invalid link in bazel/site/docs/tutorial/cc-toolchain-config.md 

### ISSUE THREAD

**Issue by jonesmz** [bazelbuild/bazel#13391]
### Description of the problem

This paragraph in the file indicated in the issue subject has two invalid links:
> When you build your [target](../build-ref.html#targets) with `bazel build --config=clang_config //main:hello-world`, Bazel uses your custom toolchain from the [cc_toolchain_suite](../be/c-cpp.html#cc_toolchain_suite) `//toolchain:clang_suite`. The suite may list different [toolchains](../be/c-cpp.html#cc_toolchain) for different CPUs, and that's why it is differentiated with the flag `--cpu=k8`.

[cc_toolchain_suite](../be/c-cpp.html#cc_toolchain_suite)
and
[toolchains](../be/c-cpp.html#cc_toolchain)
don't exist.

**Comment by katre** [comment]
The documentation is written for our doc site (https://doc.bazel.build). Viewed there, the links are correct (see https://docs.bazel.build/versions/master/tutorial/cc-toolchain-config.html).

The rule documentation (like for `cc_toolchain_suite` and `cc_toolchain`) is built from the relevant source code as part of the release process, and can't possibly work from the raw pages.

I'm not sure if there's a way to indicate that these aren't intended to be read directly in Github, but that's not currently a way we deliver documentation, and anything linking correctly is by accident.

Thanks for reporting this, I'm sorry there's not much we can do. Please do check out https://docs.bazel.build, though!
