### ISSUE TITLE
Documentation issue: Installing Bazel on Ubuntu

### ISSUE THREAD

**Issue by Vitalik-sobolev** [bazelbuild/bazel#13396]
Documentation URL: https://docs.bazel.build/versions/4.0.0/install-ubuntu.html

I had to install tensorflow, but it had error. ubuntu version: ubuntu-18.04-desktop-amd64.iso

Uncompressing..error [./bazel-2.0.0-installer-linux-x86_64.sh]:  missing 1232 bytes in zipfile
  (attempting to process anyway)
error: invalid zip file with overlapped components (possible zip bomb)

**Comment by philwo** [comment]
Hi @Vitalik-sobolev,

is it possible that your download as been truncated or corrupted? For comparison, here's the SHA256 sum of the file:

```
$ sha256sum bazel-2.0.0-installer-linux-x86_64.sh 
2fbdc9c0e3d376697caf0ee3673b7c9475214068c55a01b9744891e131f90b87  bazel-2.0.0-installer-linux-x86_64.sh
```

I tried to run the setup in a fresh Ubuntu 18.04 VM and it seems to work fine:

```
$ sudo apt update && sudo apt install unzip
$ wget https://github.com/bazelbuild/bazel/releases/download/2.0.0/bazel-2.0.0-installer-linux-x86_64.sh
$ bash bazel-2.0.0-installer-linux-x86_64.sh --user
$ ~/bin/bazel version
Build label: 2.0.0
```

Cheers,
Philipp
