### ISSUE TITLE
Audit uses of LazyWritePathsFileAction

### ISSUE THREAD

**Issue by cushon** [bazelbuild/bazel#13390]
https://github.com/bazelbuild/bazel/commit/8ba48ad869006d87abc84e2f699fbc59eb8470f8 fixed one use of `LazyWritePathsFileAction` that was causing incorrect paths to files in external repositories by migrating to `SourceManifestAction`. From the description for that commit:

> There are more places that use `LazyWritePathsFileAction` and I suspect
> that all of them are broken:
> 
> - persistent test runner support in BazelJavaSemantics (AFAIK, this
>   doesn't work in Bazel anyway)
> - coverage w/ metadata jars in BazelJavaSemantics (not used by
>   JavaBinary)
> - coverage source list file ('-paths-for-coverage.txt'); this probably
>   results in non-functioning coverage for *source files* in external
>   repositories

**Comment by comius** [comment]
cc @brandjon
