### ISSUE TITLE
`@local_jdk` references fail with Ubuntu 20.10 OpenJDK

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#13406]
### Description of the problem / feature request:

As of https://github.com/bazelbuild/bazel/commit/3733065ddd418357e0e74091789ace5884b01fef, references to `@local_jdk` lead to an error when running with the OpenJDK installed by the `openjdk-15-jre-headless` package of Ubuntu 20.10.

The stack trace is as follows:
```
INFO: Repository local_jdk instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:27:6: in <toplevel>
  /home/fabian/.cache/bazel/_bazel_fabian/018e1cccb754ba18b7604abc85e7cd0d/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
  /home/fabian/.cache/bazel/_bazel_fabian/018e1cccb754ba18b7604abc85e7cd0d/external/bazel_tools/tools/jdk/local_java_repository.bzl:226:32: in local_java_repository
Repository rule _local_java_repository_rule defined at:
  /home/fabian/.cache/bazel/_bazel_fabian/018e1cccb754ba18b7604abc85e7cd0d/external/bazel_tools/tools/jdk/local_java_repository.bzl:197:46: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_jdk':
   Traceback (most recent call last):
File "/home/fabian/.cache/bazel/_bazel_fabian/018e1cccb754ba18b7604abc85e7cd0d/external/bazel_tools/tools/jdk/local_java_repository.bzl", line 147, column 105, in _local_java_repository_impl
version = repository_ctx.attr.version if repository_ctx.attr.version != "" else _detect_java_version(repository_ctx, java_bin)
File "/home/fabian/.cache/bazel/_bazel_fabian/018e1cccb754ba18b7604abc85e7cd0d/external/bazel_tools/tools/jdk/local_java_repository.bzl", line 32, column 26, in _detect_java_version
(major, minor, rest) = version_value.split(".", 2)
Error: too few values to unpack (got 1, want 3)
```

With that package installed, the command `java -XshowSettings:properties`, which is invoked in https://github.com/bazelbuild/bazel/commit/3733065ddd418357e0e74091789ace5884b01fef#diff-8d3287c1b6c0d3bbfc4e6a4b8a6f6966a357c29464f58aedb91309dbf7252f24R18, returns a line of the form:
```
    java.version = 15
```

The error seems to arise since this version number does not conform to the `major.minor.patch` scheme.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Install Bazel after https://github.com/bazelbuild/bazel/commit/3733065ddd418357e0e74091789ace5884b01fef (or e.g. release-4.1.0-rc4) on Ubuntu 20.10 and specify the `openjdk-15-jre-headless` installation as `JAVA_HOME`.
2. Build any rule with a dependency on `@local_jdk` (e.g. to get the JNI headers).

### What operating system are you running Bazel on?

Ubuntu 20.10

### What's the output of `bazel info release`?

```
2021/04/26 21:15:44 Using unreleased version at commit 4cf59697f1e65ba927f007e59c2d87e2684512d6
development version
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

With Bazelisk and `.bazelversion` set to `4cf59697f1e65ba927f007e59c2d87e2684512d6`

**Comment by keith** [comment]
I see this on macOS as well

**Comment by keith** [comment]
Can you test with https://github.com/bazelbuild/bazel/pull/13407 to see if it works as expected?

**Comment by fmeum** [comment]
Thanks, that fixes the issue.
