### ISSUE TITLE
release version keeps showing 4.0.0 even though I installed older versions

### ISSUE THREAD

**Issue by halhwadi** [bazelbuild/bazel#13411]
### Feature requests: what underlying problem are you trying to solve with this feature?

> Install compatible bezel version for tensorflow 2.3.0 and 2.4.0 ([check the map table](https://www.tensorflow.org/install/source_windows))

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> 

1. download the desired [bazel version](https://github.com/bazelbuild/bazel/releases)
2. type bazel in cmd

### What operating system are you running Bazel on?

> windows 10 CPU only (No GPU)

### What's the output of `bazel info release`?

>                                                           [bazel release 4.0.0]
Usage: bazel <command> <options> ...

Available commands:
  analyze-profile     Analyzes build profile data.
  aquery              Analyzes the given targets and queries the action graph.
  build               Builds the specified targets.
  canonicalize-flags  Canonicalizes a list of bazel options.
  clean               Removes output files and optionally stops the server.
  coverage            Generates code coverage report for specified test targets.
  cquery              Loads, analyzes, and queries the specified targets w/ configurations.
  dump                Dumps the internal state of the bazel server process.
  fetch               Fetches external repositories that are prerequisites to the targets.
  help                Prints help for commands, or the index.
  info                Displays runtime info about the bazel server.
  license             Prints the license of this software.
  mobile-install      Installs targets to mobile devices.
  print_action        Prints the command line args for compiling a file.
  query               Executes a dependency graph query.
  run                 Runs the specified target.
  shutdown            Stops the bazel server.
  sync                Syncs all repositories specified in the workspace file
  test                Builds and runs the specified test targets.
  version             Prints version information for bazel.

Getting more help:
  bazel help <command>
                   Prints help and options for <command>.
  bazel help startup_options
                   Options for the JVM hosting bazel.
  bazel help target-syntax
                   Explains the syntax for specifying targets.
  bazel help info-keys
                   Displays a list of keys used by the info command.

**Comment by Wyverald** [comment]
This doesn't sound like a bazel bug, rather a PATH setup issue. Please ask for help on bazel-discuss@googlegroups.com or StackOverflow.
