### ISSUE TITLE
Support --compile_one_dependency in Starlark

### ISSUE THREAD

**Issue by phst** [bazelbuild/bazel#13419]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

`--compile_one_dependency` officially works only for built-in rules. Starlark rules can pass `attr.label_list(flags = ["DIRECT_COMPILE_TIME_INPUT"])`, but that is undocumented and doesn't work for single-label attributes (`attr.label` doesn't have a `flags` parameter). It would be great to give `attr.label` and `attr.label_list` an officially-supported parameter like `direct_compile_time_input = True/False`.

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm trying to write a Starlark rule that has rough feature parity with the builtin rules, including support for `--compile_one_dependency`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a Starlark rule with an attribute like `"srcs": attr.label_list()`. Use that rule in some BUILD file. Try running `bazel build --compile_one_dependency source-file`. Bazel will print an error like "Couldn't find dependency on target …".

### What operating system are you running Bazel on?

GNU/Linux (but this is OS-independent).

### What's the output of `bazel info release`?

release 4.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

I searched through GitHub issues for this repository, but found nothing related.
https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/test/java/com/google/devtools/build/lib/pkgcache/CompileOneDependencyTransformerTest.java#L75 is an example that "documents" the current support.

**Comment by brandjon** [comment]
What does this block? What rule are you trying to create or migrate?

@comius FYI.

**Comment by phst** [comment]
In this case I've been using the workaround for my Emacs Lisp rules (https://github.com/phst/rules_elisp/commit/66ad6e257e083323a49a14f55016c37346eb17fb). It doesn't really block anything, it would just be nice to officially support this in Starlark to bring Starlark-written rules on par with native ones.
