### ISSUE TITLE
Permit distribution of bazel on Flathub

### ISSUE THREAD

**Issue by albert-tomanek** [bazelbuild/bazel#13412]
Hi,
I've [packaged bazel](https://github.com/albert-tomanek/flathub/tree/org.freedesktop.Sdk.Extension.bazel) for distribution on [Flathub](https://flathub.org/about) and as part of the publishing requirements I need to contact the authors to check whether they approve.
Could you confirm that this is ok?
Thanks

**Comment by oquenchil** [comment]
@sventiffe

**Comment by Wyverald** [comment]
Sorry for the late response, but this seems fine (Bazel is distributed under the Apache 2.0 license). Thank you!
