### ISSUE TITLE
Confusing typo in genrule documentation in build encyclopedia

### ISSUE THREAD

**Issue by davidmankin** [bazelbuild/bazel#13426]
### Description of the problem / feature request:

> Confusing typo in genrule documentation in build encyclopedia.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

[This section](https://docs.bazel.build/versions/master/be/general.html#genrule-environment) of the build encyclopedia says:

> However, Bazel (but not Bazel) passes through the value of the user's PATH environment variable. Any change to the value of PATH will cause Bazel to re-execute the command on the next build.

It's quite confusing what "Bazel but not Bazel" means here.

**Comment by sgowroji** [comment]
Hello @davidmankin, Thank you for reporting us. Its updated in the latest [documentation](https://bazel.build/reference/be/general#genrule-environment). We are closing this issue. Feel free to reach us if you still have any further queries.
