### ISSUE TITLE
Locale dependent buildjar code

### ISSUE THREAD

**Issue by hkwi** [bazelbuild/bazel#1342]
hasRecognizedError in (bazel/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/ReducedClasspathJavaLibraryBuilder.java ) parses command line output messages, which varies by system language setting. So build failed on my computer with Japanese locale. I could successfully built the binary from scratch when I changed the system language to English on Windows 10, which requires log off and log on.

Possible fix are:
- add something like "-J-Duser.language=en" to javac arguments, or
- inject arguments like [this](https://blogs.oracle.com/LetTheSunShineIn/entry/windows_injecting_argument_no_matter), or
- change the system locale on every bazel build

**Comment by ulfjack** [comment]
We could disable the reduced classpath. Or you could do that as a workaround.

I think this is the right flag:
--experimental_java_classpath=off

**Comment by cushon** [comment]
Yep, `--experimental_java_classpath=off` should work around it.

It would be nice to avoid hard-coding a locale. We might be able to have the reduced classpath compilation emit structured diagnostics, and then do the locale-dependent formatting after checking if fallback was needed.
