### ISSUE TITLE
bazel_app_test is broken on darwin

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#1343]
http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD-jdk7,PLATFORM_NAME=darwin-x86_64/34/console

Possibly caused by 6d07acbfb9a45e58d9f2dcc95758cb9add1ad2b5 or 696a4a7e8bb96a3a1955730130f8da2a755a5356
@dmishe Please take a look. :)

**Comment by dmishe** [comment]
Looks like we forgot to set the iOS SDK, will fix shortly.
