### ISSUE TITLE
Documentation issue: links to skylark/lib are broken for some cc rules

### ISSUE THREAD

**Issue by glukasiknuro** [bazelbuild/bazel#13439]
Documentation URL: https://docs.bazel.build/versions/master/integrating-with-rules-cc.html
   `CcToolchainInfo` points to https://docs.bazel.build/versions/master/skylark/lib/CcToolchainInfo.html which returns 404

https://docs.bazel.build/versions/master/cc-toolchain-config-reference.html
   `cc_common.create_cc_toolchain_config_info()` leads to https://docs.bazel.build/versions/master/skylark/lib/cc_common.html#create_cc_toolchain_config_info which return 404 as well

Possibly there is more.

**Comment by jdai8** [comment]
Same thing for Java. https://docs.bazel.build/versions/master/bazel-and-java.html links to:
- https://docs.bazel.build/versions/master/skylark/lib/java_common.html
- https://docs.bazel.build/versions/master/skylark/lib/JavaInfo.html

which return 404s.

**Comment by sgowroji** [comment]
This issue is fixed. Hence we are closing it.Feel free to reach us for any further questions or to reopen this issue.

**Comment by fweikert** [comment]
The old page has been deprecated. Links in the new page work: https://bazel.build/configure/integrate-cpp
