### ISSUE TITLE
Iterating over settings.items() in transition implementation yields invalid list values

### ISSUE THREAD

**Issue by torgil** [bazelbuild/bazel#13436]
### Description of the problem / feature request:

Below is a minimal example, running `bazel-dev build --features=y //:lib_with_feature_x` on it results in `Error: unsupported binary operation: List + list`.
This object has `type(value) != type([])` and normal list operations cannot be performed on it. Trying to use it in a test with not operator even results in a java exception with `invalid Starlark value: class com.google.common.collect.SingletonImmutableList`

Both `settings["//command_line_option:features"]`  and `settings.items()[0][1]` works as expected.

=== rules.bzl ====
```
def _add_feature_x_transition_impl(settings, attrs):
    build_settings = {}
    for key, value in settings.items():
        if key == "//command_line_option:features":
            value = value + ["x"]  # <-------- FAULTY VALUE HERE
        build_settings[key] = value
    return build_settings

add_feature_x_transition = transition(
    implementation = _add_feature_x_transition_impl,
    inputs = ["//command_line_option:features"],
    outputs = ["//command_line_option:features"],
)

def _apply_feature_x_impl(ctx):
    return cc_common.merge_cc_infos(cc_infos = [dep[CcInfo] for dep in ctx.attr.deps])

apply_feature_x = rule(
    cfg = add_feature_x_transition,
    implementation = _apply_feature_x_impl,
    attrs = {
        "deps": attr.label_list(providers=[CcInfo]),
        "_whitelist_function_transition": attr.label(
            default = "@bazel_tools//tools/whitelists/function_transition_whitelist"),
    },
)
```
==== BUILD.bazel ====
```
load("@rules_cc//cc:defs.bzl", "cc_library")
load(":rules.bzl", "apply_feature_x")

cc_library(
    name = "lib",
)

apply_feature_x(
    name = "lib_with_feature_x",
    deps = [":lib"],
)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Unpack this archive:
[transition_list_values.tar.gz](https://github.com/bazelbuild/bazel/files/6434722/transition_list_values.tar.gz)

Run this command:
`bazel-dev build --features=y //:lib_with_feature_x`

### What operating system are you running Bazel on?

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

### What's the output of `bazel info release`?

development version

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

$ # checkout latest git version on bazelbuild/master
$ bazel-4.0.0-linux-x86_64 build --javabase=@bazel_tools//tools/jdk:remote_jdk11 //src:bazel-dev
$ git status
HEAD detached at bazelbuild/master
nothing to commit, working tree clean

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/bazelbuild/bazel.git
b5bfcc1ed0388fb5f0e3924d8fd33ea1bb3db0e1
b5bfcc1ed0388fb5f0e3924d8fd33ea1bb3db0e1

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

See files above.

**Comment by outermeasure** [comment]
Hi, I reproduced it locally and would like to try to fix this.

**Comment by gregestren** [comment]
Note that there *is* a pending PR on this now.

**Comment by outermeasure** [comment]
Fixed in https://github.com/bazelbuild/bazel/commit/9f87aa7b352a2caea44cebd5b8cd0fc0b2a4728b

**Comment by torgil** [comment]
> Fixed in [9f87aa7](https://github.com/bazelbuild/bazel/commit/9f87aa7b352a2caea44cebd5b8cd0fc0b2a4728b)

@outermeasure This patch was rolled back due to "Breaks some targets". Do we know why this is?

**Comment by outermeasure** [comment]
It was rolled back because it broke some tests unfortunately.

**Comment by fmeum** [comment]
> It was rolled back because it broke some tests unfortunately.

@outermeasure Could you explain the path forward in more detail? Can those tests be fixed or does the original fix require modifications?
