### ISSUE TITLE
Tried to set properties for non-existent exec group 'cpp_link'.

### ISSUE THREAD

**Issue by tgerdes-cohesity** [bazelbuild/bazel#13438]
### Description of the problem / feature request:

Attempting to set exec_properties for the group `cpp_link` for `cc_binary`, `cc_library`, and `cc_test` rules does not appear to work.  The docs at https://docs.bazel.build/versions/master/exec-groups.html#execution-groups-for-native-rules  indicate that this group should be defined by native rules.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
cc_binary(
    name = "my_binary",
    srcs = ["my_binary.cc"],
    exec_properties = {
        "cpp_link.resource": "value"
    },
)
```
```
$  bazel build --experimental_exec_groups=true //:my_binary
ERROR: Analysis of target '//:my_binary' failed; build aborted: Tried to set exec property 'resource' for non-existent exec group 'cpp_link'.
INFO: Elapsed time: 0.227s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

### What operating system are you running Bazel on?

Ubuntu 18.04.

### What's the output of `bazel info release`?

```
$ bazel info release
release 4.0.0
```

Also tried with a recent build on master using commit f6cce242420cad432797e0e2501475e821553af7 , built with `bazel build //src:bazel`

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
$ git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
https://github.com/bazelbuild/bazel
f6cce242420cad432797e0e2501475e821553af7
f6cce242420cad432797e0e2501475e821553af7
```

###  Have you found anything relevant by searching the web?

Not specific to the group `cpp_link`, but there's some discussion of the implementation of the group `test` on https://github.com/bazelbuild/bazel/issues/10799 which I only got to work on master, not version 4.0.0

**Comment by quval** [comment]
Looks like this is because the CcLinkingRule, which the `cpp_link` execution group is defined on, isn't an ancestor of the cc_binary rule (or any cc rule, actually). Should `CppRuleClasses.CcLinkingRule.class` be an ancestor of CcBaseRule?

**Comment by vmrob** [comment]
Any updates on this issue? It does appear that the features described the in docs can't be used because the execution group is effectively nonexistent.

In my particular use case, I was hoping I could run our link steps on larger remote workers as they typically require more resources than compile steps. To do this, I was hoping to leverage the `cpp_link` execution group to set an execution property for all `cpp_link` actions.
