### ISSUE TITLE
try-import dies on Windows if path is invalid

### ISSUE THREAD

**Issue by erenon** [bazelbuild/bazel#13443]
### Description of the problem / feature request:

From The Users Guide: "The difference between import and try-import is that Bazel fails if the import‘ed file is missing (or can’t be read), but not so for a try-import‘ed file." However, if a  `.bazelrc` contains `try-import /no/such/file`, on windows, bazel dies. (On Linux, the import ignored as expected).

### Feature requests: what underlying problem are you trying to solve with this feature?

I'd like to make this .bazelrc work:

```
try-import /mnt/shared/defaults.bazelrc
try-import E:/shared/defaults.bazelrc
```

This would allow cross-platform projects to pick up platform specific defaults easily.
(Note: --enable_platform_specific_config is not good enough for two reasons: (a) it can't differentiate different windows and linux versions (b) it still needs a single path that can be imported on both platforms (windows and linux))

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

On windows:

```
> cat .bazelrc
try-import /mnt/shared/defaults.bazelrc
> bazel info
[...] network paths are unsupported
```

And it dies.

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

Bazel 4.0.0

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

Root cause: `RcFile::ParseFile` invokes `blaze_util::ReadFile`, that converts the string filename to a `Path`, and the `Path` constructor invokes `BAZEL_DIE`. The issue can be easily avoided e.g: by making `ParseFile` use iostreams instead of blaze_util. I'm happy to provide a PR, if this is viable.

**Comment by aiuto** [comment]
It seems like we should make the posix and windows ReadFile implementations the same rather than add a special purpose Readfile for parsing RC files.

**Comment by erenon** [comment]
That's OK. However, I couldn't figure out what the windows implementation does in extra (I have only Linux experience). I do no understand why the windows Path implementation rejects certain kinds of paths. Thank for taking a look!

**Comment by lberki** [comment]
Routing to @meteorcloudy .

My non-binding opinion is that the reason why this happens is that we thought calling `BAZEL_DIE()` when Bazel encounters a path it cannot parse was both easy and correct. This is almost always true, except during parsing `try-import` because then errors are supposed to be ignored.

If I had to fix this issue, I'd make it possible for `ConvertPath()` to tell its caller that the path in question is invalid, then handle the error with `BAZEL_DIE()` except during `try-import`. 

@aiuto : I think it makes sense to prohibit network paths (it's unexpected network access at best and a security issue at worst). I don't know whether the current approach of parsing paths ourselves is the best approach to do so, though; maybe Windows provides an easier way to tell whether a given path is local.

**Comment by meteorcloudy** [comment]
> If I had to fix this issue, I'd make it possible for ConvertPath() to tell its caller that the path in question is invalid, then handle the error with BAZEL_DIE() except during try-import.

I agree with this approach, will work on a fix.

**Comment by erenon** [comment]
Thanks for taking a look! Here's another use-case that relates to UNC paths: I work on linux, my home is on NFS, and I edit my files on linux. This is a multiplatform project, so I want to test my changes on windows as well. My home is accessible from windows, through a network drive. As you might expect now, starting bazel.exe in a workspace that resides on a network device doesn't work: it prints a WARNING first, that my `.bazelrc` is ignored, then it hangs and starts to eat up memory steadily. (A debug version is being built now to figure out why).

Is this setup planned to be supported, or completely out of reach?

**Comment by meteorcloudy** [comment]
> Is this setup planned to be supported, or completely out of reach?

Sorry, I don't think we currently have the capacity to work on this very use case.

**Comment by lberki** [comment]
@meteorcloudy , would you accept pull requests?

**Comment by meteorcloudy** [comment]
Yes, PRs are always welcome!

To be clear, I'll still look into the `try-import` problem reported in this issue, but don't have time to reproduce the use case mentioned in https://github.com/bazelbuild/bazel/issues/13443#issuecomment-858615263.
