### ISSUE TITLE
Sets cannot be "subtracted"

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#1344]
Since I wanted to get all subdirectories of a certain directory I tried the obvious:

```
only_subdirectories = set( glob(["*"], exclude_directories=0) ) - set( glob(["*"] )
```

Sadly it seems as if the minus operator is not implemented for `set`s :(

**Comment by abergmeier** [comment]
Problem is that I assume it is implemented in `SkylarkNestedSet` but couldn't figure out yet, where the operators are implemented (according to docs `|` should be present).

**Comment by abergmeier** [comment]
@meteorcloudy Will give this a shot.

**Comment by abergmeier** [comment]
@meteorcloudy Are you in irc?
Is it ok to use `HashSet` in Bazel code?
For _difference_, should `immutableItems` be wrapped or is it ok to merge the `NestedSet`? I think I am asking whether the `order` needs to be preserved.

**Comment by meteorcloudy** [comment]
Sorry for the late reply. I am not quite familiar with this. //cc @laurentlb  Can you help us?

**Comment by dslomov** [comment]
We'll take a look at this during genuine set api design

**Comment by laurentlb** [comment]
To filter elements, use a comprehension, e.g.
  only_subdirectories = [f for f in only_subdirectories if ...]

**Comment by laurentlb** [comment]
I don't think we should support that natively. `set` is renamed to `depset` and we don't want to encourage this kind of operation (which removes all benefits of the depset). Documentation has been recently improved: https://bazel.build/versions/master/docs/skylark/depsets.html

So I'd encourage to write an intersection function in a .bzl file instead.
