### ISSUE TITLE
cquery is broken for //external package

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#13454]
### Description of the problem / feature request:

bazel cquery  //external:*     causes crash.
bazel cquery //external:all    is also broken but differently.

query (instead of cquery) works fine in both cases.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create tiny workspace which only defines and loads skylib and run the cquery commands above in it.
For convenience I created sample repo [here](https://github.com/Bazel-snippets/cquery_external).

### What operating system are you running Bazel on?

Linux, Mac, Windows

### What's the output of `bazel info release`?

4.0.0
4.1.0 rc4

**Comment by gregestren** [comment]
@lberki - do you have any ideas on the right way to approach this?

**Comment by lberki** [comment]
I'm somewhat surprised that `:*` and `:all` misbehave differently.

My guess is that this is because `//external:` contains repository rules and those never participate in the analysis phase.

If I had to fix this would be to look at what happens in the analysis phase when one depends  `//external:` and do the same thing in `cquery`.

**Comment by Wyverald** [comment]
I think the right idea is probably simply to disallow cquerying `//external`. Its targets aren't build targets, and can't be configured, so what is cquery really going to tell you?

I don't believe there's anything we can do on the external deps side. Greg, back to you if you want to make it fail fast, or just close it (this is a P4 as far as I'm concerned).

**Comment by konste** [comment]
Targets from `//external` package are very much buildable targets! The only difference is that they are defined in other workspaces, but after they get pulled in by the repository rules they are the same - buildable targets.

For example a fragment from my `bazel query //external:*` output looks like
```
//external:zlib
//external:zlib__winD32
//external:zlib__winD64
//external:zlib__winR32
//external:zlib__winR64
```
We see five `zlib`s because the right one for the target platform is picked up by `select`
Naturally I want to run `bazel cquery //external:*` to see the one used for the current platform.

**Comment by Wyverald** [comment]
> The only difference is that they are defined in other workspaces, but after they get pulled in by the repository rules they are the same - buildable targets.

They are *not* defined in other workspaces; they **are** the "other workspaces". The target `//external:foo` simply corresponds to the external repo `@foo`. There is nothing configurable about them. When you do `bazel build //external:foo`, nothing happens.

> We see five `zlibs` because the right one for the target platform is picked up by `select`

I don't know exactly how your workspace is set up, but these aren't the targets being picked up by `select`. Each of these represents an external repo and what `select` is picking up are the targets _within_ those repos (e.g. `@zlib__winD32//:zlib__winD32`), not the target in `//external` (e.g. `//external:zlib__winD32`).

**Comment by konste** [comment]
Hm-m... okay, this makes sense. Indeed `@zlib__winD32//:zlib__winD32` is what gets selected. I guess what I really need is a way to run `cquery` on ALL workspaces - primary and external. Like to get the list of all targets in the build regardless which workspace they come from.

**Comment by gregestren** [comment]
I suggested in https://github.com/bazelbuild/bazel/issues/14855#issuecomment-1061118184 that we resolve this by disallowing `bazel build` on `//external`, since I reproduced a crash on `build` as well. And `cquery` would inherit that fix.

Can we get a consensus on that being the right way to close these issues?

**Comment by Wyverald** [comment]
I'm okay with duping all those against each other, and fail early in `build` or something.

**Comment by gregestren** [comment]
I'm still confused. From bazel's repo:

**Builds:**
```
$  bazel build //external:re
INFO: Found 1 target...
Target @com_googlesource_code_re2//:re2 up-to-date:
  bazel-bin/external/com_googlesource_code_re2/libre2.a
  bazel-bin/external/com_googlesource_code_re2/libre2.so
INFO: Elapsed time: 6.650s, Critical Path: 1.36s
INFO: 27 processes: 3 internal, 24 linux-sandbox.
INFO: Build completed successfully, 27 total action
```

**Fails:**
```
$ bazel build //external:six
ERROR: /home/bazel/WORKSPACE:690:10: in http_archive rule //external:six: Found reference to a workspace rule in a context where a build rule was expected; probably a reference to a target in that external repository, properly specified as @reponame//path/to/package:target, should have been specified by the requesting rule.
ERROR: /home/bazel/WORKSPACE:690:10: Analysis of target '//external:six' failed
ERROR: Analysis of target '//external:six' failed; build aborted: 
INFO: Elapsed time: 0.139s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 1 target configured)
```

**Crashes:**
```
$ bazel build //external:WORKSPACE
ATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//external:WORKSPACE, config=null}' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:674)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Unknown Source)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:245)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:1108)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:980)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:368)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:590)
```

I think it's only source files in `//external` that crash?
