### ISSUE TITLE
Documentation- java_test use_testrunner mistake

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#1345]
Hi,
I think the documentation of the java_test use_testrunner property is mistaken.
It talks about `com.google.testing.junit.runner.GoogleTestRunner` while I think that was superseded by `BazelTestRunner` which is also mentioned which adds to the confusion.
I think the first mention should also change to `BazelTestRunner`.
Hope I'm not talking gibberish.

**Comment by meteorcloudy** [comment]
The default value of `use_testrunner` is 1 and default behavior is to use `BazelTestRunner`, if a user needs to use this property, he would set `use_testrunner = 0` to use `GoogleTestRunner`.

Maybe we should make it more clear. ;)

**Comment by meteorcloudy** [comment]
Sorry, what I said above was totally wrong. The GoogleTestRunner doesn't exist in Bazel code. Setting `use_testrunner = 0` will just run the test java binary without any test runner. We should definitely update the document!

**Comment by ittaiz** [comment]
PR?

**Comment by meteorcloudy** [comment]
Yeah, that would be nice. :)
