### ISSUE TITLE
Coursier is not a valid Win32 Application

### ISSUE THREAD

**Issue by andrewkatson** [bazelbuild/bazel#13458]
### Description of the problem / feature request:

I am getting an error about coursier not being a valid Win32 application when unpacking maven. 

### Feature requests: what underlying problem are you trying to solve with this feature?

I would like to be able to build java protos on Windows. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Go on Windows and use rules_jvm_external

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 4.0.0.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/andrewkatson/KeirosPublic.git
master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
0bcf8a9dc630bbcbc1dff3310481ecdb240e9335

###  Have you found anything relevant by searching the web?

https://github.com/google/copybara/issues/116
https://github.com/bazelbuild/rules_jvm_external/issues/464

### Any other information, logs, or outputs that you want to share?

```
INFO: Repository maven instantiated at:
  C:/users/katso/documents/github/denarii/external/keirospublic/WORKSPACE:145:14: in <toplevel>
  C:/msys64/home/katso/_bazel_katso/cjrunvaw/external/rules_jvm_external/defs.bzl:89:19: in maven_install
Repository rule coursier_fetch defined at:
  C:/msys64/home/katso/_bazel_katso/cjrunvaw/external/rules_jvm_external/coursier.bzl:712:33: in <toplevel>
INFO: Repository 'maven' used the following cache hits instead of downloading the corresponding file.
 * Hash '8f35f92fb8e021f96b3aa8145c66c3b2e29295baabb28ff50569e613438afcbd' for https://github.com/coursier/coursier/releases/download/v2.0.0-RC3-4/coursier.jar
If the definition of 'maven' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
        File "C:/msys64/home/katso/_bazel_katso/cjrunvaw/external/rules_jvm_external/coursier.bzl", line 409, column 13, in _coursier_fetch_impl
                fail("Unable to run coursier: " + exec_result.stderr)
Error in fail: Unable to run coursier: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\msys64\home\katso\_bazel_katso\cjrunvaw\external\maven\coursier"): %1 is not a valid Win32 application.
 (error: 193)
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/msys64/home/katso/_bazel_katso/cjrunvaw/external/rules_jvm_external/coursier.bzl", line 409, column 13, in _coursier_fetch_impl
                fail("Unable to run coursier: " + exec_result.stderr)
Error in fail: Unable to run coursier: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\msys64\home\katso\_bazel_katso\cjrunvaw\external\maven\coursier"): %1 is not a valid Win32 application.
 (error: 193)
ERROR: no such package '@maven//': Unable to run coursier: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\msys64\home\katso\_bazel_katso\cjrunvaw\external\maven\coursier"): %1 is not a valid Win32 application.
 (error: 193)

```

**Comment by aiuto** [comment]
Thanks for the reference.  This is not a pure Bazel problem, it is really a dup of https://github.com/bazelbuild/rules_jvm_external/issues/464

**Comment by andrewkatson** [comment]
In the other bug someone answered and their solution worked.
