### ISSUE TITLE
Flip incompatible_enable_exports_provider

### ISSUE THREAD

**Issue by comius** [bazelbuild/bazel#13457]
*Flag:* --incompatible_enable_exports_provider
*Available since:* 2021-05-10
*Flipped to **`false`** in:* Bazel 5.0.0

Removes JavaInfo.transitive_exports.

# Migration

Collect export labels using an aspect.

**Comment by martis42** [comment]
This is labeled with `breaking-change-5.0`, which I interpret as the intention to flip this with Bazel 5.0.0.
The flag is however still inactive by default: 
https://github.com/bazelbuild/bazel/blob/5.0.0/src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java#L151

Please update the issue status.

**Comment by comius** [comment]
> This is labeled with `breaking-change-5.0`, which I interpret as the intention to flip this with Bazel 5.0.0. The flag is however still inactive by default: https://github.com/bazelbuild/bazel/blob/5.0.0/src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java#L151
> 
> Please update the issue status.

The flipped state is "false". During the flag review, there were comments to name it without using negation, i.e. using `disable` in the name.

**Comment by meteorcloudy** [comment]
Should we close this issue if the incompatible change is already enabled by default?

**Comment by comius** [comment]
And removed. Closing it.
