### ISSUE TITLE
[BUG] genrule ignores .bazelrc when building their dependencies

### ISSUE THREAD

**Issue by thinlizzy** [bazelbuild/bazel#13478]
### Description of the problem / feature request:

I use .bazelrc to specify compiler options (in my case it contains build --cxxopt=-std:c++17) and I am compiling all my rules with it. However, when I add a genrule which depends on other of my cc_binary/cc_library targets, that genrule is ignoring whatever I have in .bazelrc (and the targets are recompiled without C++17 in my case)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

make sure you have a .bazelrc with build --cxxopt=-std:c++17 and that your cc_* targets are using C++17 . then make a genrule which depends on any of them and see their compilation failing

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

release 4.0.0

**Comment by aiuto** [comment]
Can you provide a BUILD file snippet. Perhaps this is the way your genrule dependencies are set up.

**Comment by thinlizzy** [comment]
Here is a simple example:

```
filegroup(
	name = "txt",
	srcs = glob(["*.txt"]),
)

cc_binary(
	name = "DataProcessor",
	srcs = [
# main.cpp uses std::filesystem and it requires C++17 to compile
		"main.cpp",
	],
)

genrule(
	name = "data",
	srcs = [":txt"],
	outs = ["data.dat"],
	exec_tools = [":DataProcessor"],
	cmd = "$(location :DataProcessor) $(OUTS) -files $(SRCS)",
)
```

From my workspace directory, if I do `bazel build DataProcessor` , it works because my .bazelrc contains `build --cxxopt=-std:c++17`

But when I do `bazel build data` , it tries to build DataProcessor *again* w/o C++17 and it fails.

**Comment by benjaminp** [comment]
Employing `--host_cxxopt` is likely the solution.

**Comment by thinlizzy** [comment]
> Employing `--host_cxxopt` is likely the solution.

I am not familiar with it. Can you please elaborate more? Perhaps using the example I put here?
Thanks!

**Comment by thinlizzy** [comment]
> > Employing `--host_cxxopt` is likely the solution.
> 
> I am not familiar with it. Can you please elaborate more? Perhaps using the example I put here?
> Thanks!

I took a look at Bazel's site and I think you are suggesting me to use this flag in every bazel invocation I make?

**Comment by oquenchil** [comment]
The problem is that the dependencies in your genrule are built using the host configuration. The solution is what Benjamin is pointing to.

You can use that flag in every bazel invocation you make in the same way you are using --cxxopt in every invocation, i.e. via the .bazelrc file.
