### ISSUE TITLE
compiler warning about mismatched new[]/delete

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/bazel#1347]
src/main/native/fsevents.cc:88:3: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete]
  delete pathsArray;
  ^
        []
src/main/native/fsevents.cc:78:29: note: allocated with 'new[]' here
  CFStringRef *pathsArray = new CFStringRef[length];

**Comment by meteorcloudy** [comment]
@damienmg I think we can fix this warning.
