### ISSUE TITLE
objc_library: alwayslink not working when depended on transitively via cc_library

### ISSUE THREAD

**Issue by dflems** [bazelbuild/bazel#13510]
Though it's not technically documented, `objc_library` accepts `alwayslink`. I would expect it to behave like `cc_library` and _always_ `-force_load` the library. It works in some cases, but not in others. For example:

```starlark
# objc_lib has alwayslink set
objc_library(
    name = "objc_lib",
    srcs = ["objc_lib.m"],
    alwayslink = 1,
)

# cc_lib depends on objc_lib
cc_library(
    name = "cc_lib",
    srcs = ["cc_lib.cpp"],
    deps = [":objc_lib"],
)

# mybin depends on cc_lib
# objc_lib is NOT force-loaded =(
apple_binary(
    name = "mybin",
    platform_type = "macos",
    binary_type = "executable",
    deps = [":cc_lib"],
)
```

If this situation is reversed, a `cc_library` with `alwayslink` IS force-loaded when depended on transitively by an `objc_library`.

If both libraries are `cc_library` or both libraries are `objc_library`, the transitive dep with `alwayslink` is force loaded.

The only case where this doesn't work is `binary -> cc_library -> objc_library w/ alwayslink`

Using Bazel 4.1.0 on macOS 11.3.1, though I suspect this has been an issue for longer.

**Comment by trybka** [comment]
+cc @googlewalt

**Comment by keith** [comment]
Should be fixed these days. At least by removing the objc linking logic
