### ISSUE TITLE
Including more writable dirs or setting XDG_RUNTIME_DIR

### ISSUE THREAD

**Issue by kurt-google** [bazelbuild/bazel#13516]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the feature request:

Include /run/user in the default writable sandbox mounts, or set XDG_RUNTIME_DIR

### Feature requests: what underlying problem are you trying to solve with this feature?

Some tools expect the be able to write to the /run tmpfs and prefer it to /tmp,$TEMP as it is defined to be a tmpfs. Either ensuring it is writable similar to /tmp or redirecting tools via $XDG_RUNTIME_DIR similar to the sandbox's $TEMP would help avoid problems in the future.

This was discussed for podman when trying to use it as a rootless replacement for docker when using the https://github.com/bazelbuild/rules_docker packages. https://github.com/containers/podman/issues/10433

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 4.1.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

###  Have you found anything relevant by searching the web?

I can manually set `--sandbox_writable_path` but this is a very rarely used flag so its not easy to find when searching such generic permissions issues.

**Comment by meisterT** [comment]
cc @larsrc-google
