### ISSUE TITLE
Analysis of target '@local_config_cc//:toolchain' failed

### ISSUE THREAD

**Issue by SepCzp** [bazelbuild/bazel#13511]
E:\file\AndroidStudioProjects\lyra-main>bazel build android_example:lyra_android_example --config=android_arm64 --copt=-DBENCHMARK
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
Analyzing: target //android_example:lyra_android_example (1 packages loaded, 0 targets configured)
Analyzing: target //android_example:lyra_android_example (11 packages loaded, 7 targets configured)
Analyzing: target //android_example:lyra_android_example (11 packages loaded, 7 targets configured)
ERROR: C:/users/administrator/_bazel_administrator/rnnf5ikd/external/local_config_cc/BUILD:47:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'arm64-v8a'
ERROR: Analysis of target '//android_example:lyra_android_example' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed
INFO: Elapsed time: 5.339s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (48 packages loaded, 486 targets configured)
FAILED: Build did NOT complete successfully (48 packages loaded, 486 targets configured)

The construction of Google new audio codec Lyra problems, how to solve.In addition, building the Android process to operate on the Bazel website is problematic

**Comment by jin** [comment]
Please file an issue on https://github.com/google/lyra.
