### ISSUE TITLE
bazel-build/bundle-push: line 48: syntax error near unexpected token `fi'

### ISSUE THREAD

**Issue by indera-shsp** [bazelbuild/bazel#13517]
### Description of the problem / feature request:

Builds in Jenkins are failing

```
INFO: Running command line: .bazel/bin/tmp-bazel-build/bundle-push
INFO: Build completed successfully, 1 total action
/root/.cache/bazel/_bazel_root/be0ee4db2d15e1dd2afc87f2aa5fb8e9/execroot/backend/bazel-out/k8-fastbuild/bin/tmp-bazel-build/bundle-push: line 48: syntax error near unexpected token `fi'

```

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Can't share private code

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

Downloading https://releases.bazel.build/3.7.1/release/bazel-3.7.1-linux-x86_64

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

I suspect this issue is related to 
https://github.com/bazelbuild/rules_docker/issues/1814

**Comment by fweikert** [comment]
Unfortunately we cannot debug this issue without any context (logs, code, or repro instructions).
