### ISSUE TITLE
FR: Option for collapsing runfile tree paths on Windows

### ISSUE THREAD

**Issue by JohanLaineTobii** [bazelbuild/bazel#13525]
### Description of the problem / feature request:

Feature request: Create a flag that (at least on Windows) collapses part of the runfile tree in a similar way as https://github.com/bazelbuild/bazel/issues/4149 was done for a similar issue. The commit message gives a pretty good explanation: https://github.com/bazelbuild/bazel/commit/bb9ae6a174b8cd255a62249f01919426f1d817f8

### Feature requests: what underlying problem are you trying to solve with this feature?

From what I can tell, Windows symlinks don't work if the path of the origin is too long. At least not symlinks to executables. Note that this is not related to the testrunner or any other Bazel wrapper, this is an issue with the symlink itself. It's not even possible to manually run executables through symlinks where the origin is too long.

This creates issues with symlink'd runfile trees when running tests on Windows. The issue here is with Windows and not Bazel, so I mean this to be a feature request allowing a workaround.

Some more background: We have a repository that is fairly "deep", so Bazel runfiles paths get very long. As stated above, such symlinks don't seem to work on Windows (verified on 3 machines). From what I can tell this is a Windows bug that I currently cannot work around other than:
* Creating a flatter structure in our repository
* Setting --output_user_root to something short

###  Have you found anything relevant by searching the web?
Only the issue above (https://github.com/bazelbuild/bazel/issues/4149) which has a very similar motivation.

This may sound similar to an issue I posted over two years ago (https://github.com/bazelbuild/bazel/issues/7479) but it's actually different since there doesn't seem to be a workaround.

**Comment by meteorcloudy** [comment]
bb9ae6a is only for shorten the path for generated object files, because MSVC compiler cannot take long path. The optimazation doesn't make sense for runfiles. I think there are ways to work around long path issues on Windows

Useful links:
https://betanews.com/2016/05/29/long-paths-windows-10/#:~:text=Navigate%20to%20Local%20Computer%20Policy,paths%20option%20and%20enable%20it.
https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd
