### ISSUE TITLE
Provide a query to list the available kinds

### ISSUE THREAD

**Issue by jpeach** [bazelbuild/bazel#13520]
### Description of the problem / feature request:

One of the available query filters is [kind](https://docs.bazel.build/versions/master/query.html#kind).
However, because builds can create their own rules, the set of available kinds can't be known without prior knowledge of the build (i.e. reading the Bazel files).
It would be useful to have a query that would return the kinds that were defined in a workspace.

### Feature requests: what underlying problem are you trying to solve with this feature?

Figure out what are the set of valid kinds that I can specify in a [kind](https://docs.bazel.build/versions/master/query.html#kind) query filter.

###  Have you found anything relevant by searching the web?

No.

**Comment by meisterT** [comment]
Does `bazel query --output=label_kind //foo/bar/...` give you enough information?

**Comment by meisterT** [comment]
Closing because there was no response. Feel free to comment and I will reopen.
