### ISSUE TITLE
Fix incompatible flags infra failures due to new release policy

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/bazel#13524]
Examples:
- Downstream postsubmit: https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/884#834ef18e-773d-4453-98fd-ac0698fcfc4e
- ci presubmit: https://buildkite.com/bazel/continuous-integration/builds/2315#9fd225bd-0e80-4135-9916-c22ca88adb28

Diagnosis:
We've recently moved to a new "LTS + rolling releases" model. IIUC incompatible flags are no longer a thing in this new world. However, some of our infra still depends on them. We should decide what to do, which most likely means to remove the corresponding code from bazelci.py and probably Bazelisk.

**Comment by philwo** [comment]
@fweikert I remember you made some improvements to Bazelisk in this regard - do you think this issue is fixed or is there something left to do?
