### ISSUE TITLE
Fix versions linked in navigator

### ISSUE THREAD

**Issue by daveb68** [bazelbuild/bazel#13533]
Documentation URL: https://docs.bazel.build/versions/4.1.0/platforms-intro.html

The links "Platforms and toolchains" and "Visibility" under the left site navigator "Using Bazel-->Concepts" headers link to master instead of 4.1.0.  I first noticed this because in the master branch on the day I did this many of the other help topics on the left were missing.  For example, al Guides, Rules, ... were missing from the left menu.

**Comment by fweikert** [comment]
Unfortunately the docs for older releases are read-only at this point since we deprecated docs.bazel.build. Documentation for future releases (starting with 6.0) will be available on https://bazel.build.
