### ISSUE TITLE
Release 3.1.0 lacks an arm64 build for linux. 

### ISSUE THREAD

**Issue by leah-jo** [bazelbuild/bazel#13541]
~~~
root@nano-4gb-jp441:/workspace/io-0.16.0# bazel build -s --verbose_failures //tensorflow_io/...
2021/05/28 11:05:41 Downloading https://releases.bazel.build/3.1.0/release/bazel-3.1.0-linux-arm64...
2021/05/28 11:05:42 could not download Bazel: HTTP GET https://releases.bazel.build/3.1.0/release/bazel-3.1.0-linux-arm64 failed with error 404
~~~

I think release 3.1.0 lacks an arm64 build for linux. I know 3.1.0 is the old one, but I have to build through it. Could you update the 3.1.0 assets to include linux-arm64?

**Comment by nobodyCloak** [comment]
I actually just ran into the exact same issue trying to build tensorflow as well. I'm not sure why some releases have ARM64 and others do not, but if something as big as Tensorflow is still wanting Bazel 3.1.0 in the latest release then it would be nice to include the binary for all architectures if that's possible.

I do wonder if this is a Bazelisk issue though.

**Comment by meteorcloudy** [comment]
We only support Linux arm64 from 3.4.0, can you please upgrade Bazel to this version? (For TF, just change the .bazelversion file)
https://github.com/bazelbuild/bazel/releases/tag/3.4.0 
It should be backwards compatible with 3.1.0.

FYI @philwo IIRC, the Bazel 3.1.0 source doesn't compile on Linux arm64, right?

**Comment by philwo** [comment]
@meteorcloudy I haven't tried actually. I think technically Bazel built fine on Linux arm64 relatively early, but we only started building release binaries and pushing them later. In the beginning there might also have been some tweaks required, e.g. bootstrapping with the local system JDK instead of using the embedded one.

If possible I would recommend just upgrading to the latest 3.x release.

**Comment by meteorcloudy** [comment]
@leah-jo Hopefully upgrading Bazel can be a solution for you. I'll close this issue since we have no plan to provide arm64 Linux binary for older Bazel versions.
