### ISSUE TITLE
Build on aarch64 fails

### ISSUE THREAD

**Issue by samcom12** [bazelbuild/bazel#13554]
### Description of the problem :

 While building Bazel with SPACK on aarch64, getting below errors.
```
external/bazel_tools/third_party/ijar/zlib_client.h:64:71: error: '::max' has not been declared; did you mean 'std::max'?
   64 |   static const size_t MAX_BUFFER_SIZE = std::numeric_limits<int32_t>::max();

```

Please  see attached logs

[spack-build-01-bootstrap-out.txt](https://github.com/bazelbuild/bazel/files/6596711/spack-build-01-bootstrap-out.txt)
[spack-build-env.txt](https://github.com/bazelbuild/bazel/files/6596712/spack-build-env.txt)
[spack-build-out.txt](https://github.com/bazelbuild/bazel/files/6596713/spack-build-out.txt)

**Comment by philwo** [comment]
@samcom12 What is SPACK? 😊

**Comment by samcom12** [comment]
> @samcom12 What is SPACK? 😊

Spack is a multi-platform package manager that builds and installs multiple versions and configurations of software.

You can visit it at- https://github.com/spack/spack
