### ISSUE TITLE
Documentation issue: Starlark language

### ISSUE THREAD

**Issue by daveb68** [bazelbuild/bazel#13552]
Documentation URL: https://docs.bazel.build/versions/4.1.0/skylark/language.html

The following section does not include tuple.  Being new to bazel and a novice of python, I initially took this to mean that you could not use set or tuple in Starlark.  Based on text later in the page, I realized the inconsistency.  So anyone who reads the full page will not have an issue.

The following Python types are supported:

    None
    bool
    dict
    function
    int
    list
    string

The link to tuple is:  https://docs.bazel.build/versions/4.1.0/skylark/lib/globals.html#tuple

**Comment by fweikert** [comment]
This has been fixed for the new site: https://bazel.build/rules/language

Unfortunately we cannot change the legacy site at docs.bazel.build any longer.
