### ISSUE TITLE
Documentation issue: there is no package cc_library in the native package

### ISSUE THREAD

**Issue by yaojingguo** [bazelbuild/bazel#13571]
Documentation URL: https://docs.bazel.build/versions/main/skylark/lib/native.html. The document says:

> All native rules appear as functions in this module, e.g. native.cc_library. 

But there is no rule `cc_library` in native package.

**Comment by haxorz** [comment]
`native.cc_library` exists for me:

```
nharmata@nharmata1:~/scratch-bazel-WORKSPACE$ bazel info release
release 4.2.1
nharmata@nharmata1:~/scratch-bazel-WORKSPACE$ cat p/BUILD
load("//p:foo.bzl", "foo")
foo()
nharmata@nharmata1:~/scratch-bazel-WORKSPACE$ cat p/foo.bzl
def foo():
  print(dir(native))
nharmata@nharmata1:~/scratch-bazel-WORKSPACE$ bazel query p:all
DEBUG: /usr/local/google/home/nharmata/scratch-bazel-WORKSPACE/p/foo.bzl:2:8: ["aar_import", "action_listener", "alias", "android_binary", "android_device", "android_device_script_fixture", "android_host_service_fixture", "android_instrumentation_test", "android_library", "android_local_test", "android_sdk", "android_tools_defaults_jar", "apple_binary", "apple_cc_toolchain", "apple_static_library", "available_xcodes", "cc_binary", "cc_host_toolchain_alias", "cc_import", "cc_libc_top_alias", "cc_library", "cc_proto_library", "cc_test", "cc_toolchain", "cc_toolchain_alias", "cc_toolchain_suite", "config_feature_flag", "config_setting", "constraint_setting", "constraint_value", "environment", "existing_rule", "existing_rules", "exports_files", "extra_action", "fdo_prefetch_hints", "fdo_profile", "filegroup", "genquery", "genrule", "glob", "j2objc_library", "java_binary", "java_import", "java_library", "java_lite_proto_library", "java_package_configuration", "java_plugin", "java_proto_library", "java_runtime", "java_runtime_alias", "java_test", "java_toolchain", "java_toolchain_alias", "label_flag", "label_setting", "ninja_build", "ninja_graph", "objc_import", "objc_library", "package", "package_group", "package_name", "platform", "propeller_optimize", "proto_lang_toolchain", "proto_library", "py_binary", "py_library", "py_runtime", "py_test", "repository_name", "sh_binary", "sh_library", "sh_test", "test_suite", "to_json", "to_proto", "toolchain", "toolchain_type", "xcode_config", "xcode_config_alias", "xcode_version"]
INFO: Empty results
Loading: 0 packages loaded
nharmata@nharmata1:~/scratch-bazel-WORKSPACE$ 
```

I'm therefore going to interpret this as an ask to make the docs slightly more helpful by linking to the list of all native rules.

If you're still having issues, please provide more information. A demo like I did above would be helpful.

**Comment by haxorz** [comment]
> I'm therefore going to interpret this as an ask to make the docs slightly more helpful by linking to the list of all native rules.

Actually, I'm going to keep the docs as-in for now.

**Comment by yaojingguo** [comment]
native package has the following members:

<img width="899" alt="截屏2021-09-21 上午9 46 33" src="https://user-images.githubusercontent.com/516386/134099691-79c334b3-3ec3-48ca-bc6b-d3c2d77f8df8.png">

And a check of `StarlarkNativeModuleApi.java` also shows that the native package actually has the above members. Rule `cc_library` is documented in https://docs.bazel.build/versions/main/be/c-cpp.html. And its source code`BazelCcLibraryRule.java` is in `src/main/java/com/google/devtools/build/lib/bazel/rules/cpp`.  So I think that `cc_library ` does not exist in the native package.

And I have tried your script with Bazel. I also got `cc_library` in the output.  It seems that __native__ in `existing_rules` imports some other definitions besides the members listed in https://docs.bazel.build/versions/main/skylark/lib/native.html.
```
$ bazel info release
release 4.2.1
$ bazel query p:all
...
DEBUG: /Users/jing/code/github/build/test/p/foo.bzl:2:8: ["aar_import", "action_listener", "alias", "android_binary", "android_device", "android_device_script_fixture", "android_host_service_fixture", "android_instrumentation_test", "android_library", "android_local_test", "android_sdk", "android_tools_defaults_jar", "apple_binary", "apple_cc_toolchain", "apple_static_library", "available_xcodes", "cc_binary", "cc_host_toolchain_alias", "cc_import", "cc_libc_top_alias", "cc_library", "cc_proto_library", "cc_test", "cc_toolchain", "cc_toolchain_alias", "cc_toolchain_suite", "config_feature_flag", "config_setting", "constraint_setting", "constraint_value", "environment", "existing_rule", "existing_rules", "exports_files", "extra_action", "fdo_prefetch_hints", "fdo_profile", "filegroup", "genquery", "genrule", "glob", "j2objc_library", "java_binary", "java_import", "java_library", "java_lite_proto_library", "java_package_configuration", "java_plugin", "java_proto_library", "java_runtime", "java_runtime_alias", "java_test", "java_toolchain", "java_toolchain_alias", "label_flag", "label_setting", "ninja_build", "ninja_graph", "objc_import", "objc_library", "package", "package_group", "package_name", "platform", "propeller_optimize", "proto_lang_toolchain", "proto_library", "py_binary", "py_library", "py_runtime", "py_test", "repository_name", "sh_binary", "sh_library", "sh_test", "test_suite", "to_json", "to_proto", "toolchain", "toolchain_type", "xcode_config", "xcode_config_alias", "xcode_version"]
```

**Comment by haxorz** [comment]
> And a check of StarlarkNativeModuleApi.java also shows that the native module actually has the above members... And its source codeBazelCcLibraryRule.java is in src/main/java/com/google/devtools/build/lib/bazel/rules/cpp.

It seems like you're concerned about the relationship between the organization of Bazel's Java source code and the user-facing documentation.

The docs are talking about "the native module" from the perspective of user `bzl` code using `native`; the organization of Bazel's source code is irrelevant for this user-facing documentation. Does that satisfy your concern, or have I misinterpreted your concern?

> So I think that cc_library does not exist in the native module... And I have tried your script with Bazel. I also got cc_library in the output.

Cool, thanks for trying. So that means I am correct and there's no issue here right?

**Comment by yaojingguo** [comment]
Thanks for the explanation. I am clear now.
