### ISSUE TITLE
Better debugging story for recursive calls

### ISSUE THREAD

**Issue by alecb-stripe** [bazelbuild/bazel#13576]
### Description of the problem / feature request:

In non-obvious cases of recursive function calls (function A calls B calls C .... calls A), it's very difficult to debug where the recursion is coming from. There should be guidance on how to debug such issues, possibly with changes to tooling to make it easier. Eg., macros that can print the current stack trace, or even just printing the current stack trace whenever recursion is detected.

### Feature requests: what underlying problem are you trying to solve with this feature?

Being able to debug recursive calls to eliminate them.

###  Have you found anything relevant by searching the web?

Nope, mostly just feature requests for allowing recursion.

**Comment by oquenchil** [comment]
Can you give an example? I'm afraid I can't tell what you are referring to. Starlark does not allow recursion.

**Comment by alecb-stripe** [comment]
> Starlark does not allow recursion.

Yes I know, the problem is when code ends up recursing in unexpected ways (and thus starlark errors for recursing), it becomes difficult to debug where exactly the recursion is occurring.

I can try and provide a self-contained example in a bit.

**Comment by oquenchil** [comment]
I see. I'm not sure if it's possible to give better errors when recursion happens accidentally.

@brandjon Is there room for improvement here?

**Comment by alecb-stripe** [comment]
Why not? Don't we have access to a stack trace?

**Comment by brandjon** [comment]
Tried this just now with a cycle `f() -> g() -> h() -> f()`. Here's the output I get in Bazel 5.3.2.

```
ERROR: Traceback (most recent call last):
	File "/home/brandjon/src/test/pkg/foo.bzl", line 12, column 2, in <toplevel>
		f()
	File "/home/brandjon/src/test/pkg/foo.bzl", line 4, column 4, in f
		g()
	File "/home/brandjon/src/test/pkg/foo.bzl", line 7, column 4, in g
		h()
	File "/home/brandjon/src/test/pkg/foo.bzl", line 10, column 4, in h
		f()
	File "/home/brandjon/src/test/pkg/foo.bzl", line 3, column 5, in f
		def f():
Error: function 'f' called recursively
```

So we're currently including the stack trace. Is there anything else that would be needed?
