### ISSUE TITLE
install tulsi failed on Mac

### ISSUE THREAD

**Issue by sek790c** [bazelbuild/bazel#13589]
I build mediapipe examples using bazel on Mac. 'Hello world' is succeed. Then I need to build tulsi.

 I think it is a question about bazel, not tulsi.

Mac os 10.13.6
bazel 4.1.0

liuchiyudeMacBook-Pro:tulsi lcy$ sh build_and_run.sh
Starting local Bazel server and connecting to it...
Analyzing: target //:tulsi (44 packages loaded, 217 targets configured)
Fetching @local_config_cc; fetching 99s

after 105s, I got this:

liuchiyudeMacBook-Pro:tulsi lcy$ sh build_and_run.sh
Starting local Bazel server and connecting to it...
ERROR: /private/var/tmp/_bazel_lcy/5c49963cb3cdabd3637667642b95bec0/external/local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_x86_64'

I could not solve the problem for a long time. I come from China, is this a network problem? How can I find this "@local_config_cc"

**Comment by keith** [comment]
Can you try the workarounds on https://github.com/bazelbuild/bazel/issues/9303

**Comment by sek790c** [comment]
Here is the BUILD file where the  error occur:
......
cc_toolchain_suite(
    name = "toolchain",
    toolchains = {
        "darwin|clang": ":cc-compiler-darwin",
        "darwin": ":cc-compiler-darwin",
        "armeabi-v7a|compiler": ":cc-compiler-armeabi-v7a",
        "armeabi-v7a": ":cc-compiler-armeabi-v7a",
    },
)
.......
So there is just 'darwin',no'darwin_x86_64' .Do I need to get a toolchain for cpu 'darwin_x86_64'?And how?

Here is the .bazelrc file of tulsi:

build --cpu=darwin_x86_64. //I found this line is not used, remove or change it got the same error
build --apple_platform_type=macos
...

Then I add this:
build --macos_cpus=xxx

I got error as follow:
。。。。does not contain a toolchain for cpu 'darwin_xxx'

so I think bazel just add the value of macos_cpus to the end of "darwin_", but maybe I just need "darwin"
 I want to know where I can fix the code, do I need to change the code and compile bazel myself?

**Comment by kvark** [comment]
Two independent users with similar issues reported that they solved this by (re)installing XCode/command-line-tools and rebuilding the project:
  - https://github.com/bazelbuild/bazel/issues/9303#issuecomment-603346106
  - https://github.com/bazelbuild/rules_apple/issues/650#issuecomment-1095561928

**Comment by sgowroji** [comment]
Hello @sek790c, Could you please confirm the above mentioned issues [resolutions](https://github.com/bazelbuild/bazel/issues/13589#issuecomment-1095567824) helped you in resolving your issue.  Thanks!

**Comment by sgowroji** [comment]
As there is no significant update on this issue for long time, We are closing this issue now. Please feel free to reopen if you are still looking resolution for the above query. Thanks!
