### ISSUE TITLE
[URGENT] bazel.build SSL cert expired

### ISSUE THREAD

**Issue by brandon-leapyear** [bazelbuild/bazel#13585]
https://bazel.build's SSL cert expired 10 minutes ago

**Comment by yanii** [comment]
This is indeed urgent and kind of unbelievable.

**Comment by keith** [comment]
Conversation in slack https://bazelbuild.slack.com/archives/CA31HN1T3/p1623947706196700

**Comment by vmax** [comment]
If you happen to use Bazelisk, this can be mitigated by using GitHub Releases instead:

```
export BAZELISK_BASE_URL=https://github.com/bazelbuild/bazel/releases/download/
```

**Comment by keith** [comment]
Note that even if you download bazel some internal archives bazel downloads still point to that mirror without other fallback URLs https://github.com/bazelbuild/bazel/search?q=mirror.bazel.build

**Comment by keith** [comment]
The cert has been update

**Comment by brandon-leapyear** [comment]
Thanks! Looks like it expires in Sept. I assume this will get updated regularly, before that expiration?

**Comment by philwo** [comment]
Sorry for the trouble everyone and thanks for bringing this to my attention quickly. This has been fixed shortly after the reports came in, so I'm closing this issue, but let me know if you have any other questions!

@brandon-leapyear I'll copy & paste my answer from Slack here:

> We can only get short-lived certs from Google CA (similar to LetsEncrypt and ZeroSSL ACME certs). Due to.. historic reasons.. the renewal process was manual so far. We had monitoring for the certs and verified them regularly, but apparently we missed one (we'll do some follow-up in the team to figure out what went wrong) 😞 I'll take this as an opportunity to switch us to the new shiny SSL cert handling setup that will automatically refresh them in the future, so this will no longer be a problem.
