### ISSUE TITLE
Problems with bazel on windows when --output_user_root contains a space in the path.

### ISSUE THREAD

**Issue by Akhil22222** [bazelbuild/bazel#13598]
### Description of the problem / feature request:

> I have been trying to build bazel from the source and encountered following errors.

F:\kibana-Development\bazel-src>bazel build //src:bazel-dev.exe
WARNING: Output user root "C:/Users/TEMP/_bazel_akhil patel" contains a space. This will probably break the build. You should set a different --output_user_root.
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...

DEBUG: C:/users/temp/_bazel_akhil patel/pdesem4e/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.

DEBUG: C:/users/temp/_bazel_akhil patel/pdesem4e/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True

DEBUG: C:/users/temp/_bazel_akhil patel/pdesem4e/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.

DEBUG: C:/users/temp/_bazel_akhil patel/pdesem4e/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True

INFO: Analyzed target //src:bazel-dev.exe (334 packages loaded, 9326 targets configured).

INFO: Found 1 target...

INFO: From Compiling third_party/address_sorting/address_sorting.c:
cl : Command line warning D9002 : ignoring unknown option '-std=c99'

INFO: From Compiling third_party/address_sorting/address_sorting_posix.c:
cl : Command line warning D9002 : ignoring unknown option '-std=c99'

INFO: From Compiling third_party/address_sorting/address_sorting_windows.c:
cl : Command line warning D9002 : ignoring unknown option '-std=c99'

INFO: From Compiling src/main/cpp/blaze.cc:
src/main/cpp/blaze.cc(83): warning C4273: '__p__environ': inconsistent dll linkage
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdlib.h(1158): note: see previous definition of '__p__environ'

INFO: From Compiling upb/encode.c:
C:\users\temp\_bazel_akhil patel\pdesem4e\execroot\io_bazel\external\upb\upb\encode.c(212) : warning C4715: 'upb_encode_scalarfield': not all control paths return a value

INFO: From Compiling upb/decode.c:
C:\users\temp\_bazel_akhil patel\pdesem4e\execroot\io_bazel\external\upb\upb\decode.c(407) : warning C4715: 'decode_toarray': not all control paths return a value

INFO: From Compiling upb/upb.c:
external/upb/upb/upb.c(197): warning C4116: unnamed type definition in parentheses

INFO: From Compiling src/core/lib/slice/slice.cc:
C:\users\temp\_bazel_akhil patel\pdesem4e\execroot\io_bazel\external\com_github_grpc_grpc\src\core\lib\slice\slice.cc(240) : warning C4700: uninitialized local variable 'slice' used
C:\users\temp\_bazel_akhil patel\pdesem4e\execroot\io_bazel\external\com_github_grpc_grpc\src\core\lib\slice\slice.cc(260) : warning C4700: uninitialized local variable 'slice' used

INFO: From Generating Java (Immutable) proto_library //src/main/protobuf:execution_statistics_proto:
[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/compiler/java/java_file.cc:247] The optimize_for = LITE_RUNTIME option is no longer supported by protobuf Java code generator and is ignored--protoc will always generate full runtime code for Java. To use Java Lite runtime, users should use the Java Lite plugin instead. See:
  https://github.com/protocolbuffers/protobuf/blob/master/java/lite.md

INFO: From Generating Java (Immutable) proto_library @googleapis//:google_bytestream_bytestream_proto:
google/bytestream/bytestream.proto:19:1: warning: Import google/api/annotations.proto is unused.

ERROR: C:/users/temp/_bazel_akhil patel/pdesem4e/external/googleapis/BUILD.bazel:123:18: Action external/googleapis/google_bytestream_bytestream_java_grpc_srcs.jar failed: (Exit -1): bash.exe failed: error executing command c:/tools/msys64/usr/bin/bash.exe -c ... (remaining 1 argument(s) skipped)
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("c:\tools\msys64\usr\bin\bash.exe" -c "bazel-out/host/bin/external/com_google_protobuf/protoc.exe --plugin=protoc-gen-grpc-java=bazel-out/host/bin/third_party/grpc/grpc-java-plugin_checked_in.exe --grpc-java_out=enable_deprecated=false:bazel-out/x64_windows-fastbuild/bin/external/googleapis/google_bytestream_bytestream_java_grpc_srcs.jar -Igoogle/bytestream/bytestream.proto=external/googleapis/google/bytestream/bytestream.proto -Igoogle/api/annotations.proto=external/googleapis/google/api/a(...)): The system cannot find the file specified.
 (error: 2)
Target //src:bazel-dev.exe failed to build
Use --verbose_failures to see the command lines of failed build steps.

ERROR: F:/kibana-development/bazel-src/src/main/java/com/google/devtools/build/lib/bazel/BUILD:122:13 Building src/main/java/com/google/devtools/build/lib/bazel/libmain.jar (1 source file) failed: (Exit -1): bash.exe failed: error executing command c:/tools/msys64/usr/bin/bash.exe -c ... (remaining 1 argument(s) skipped)

INFO: Elapsed time: 1433.895s, Critical Path: 117.73s
INFO: 2028 processes: 173 internal, 1812 local, 43 worker.

FAILED: Build did NOT complete successfully

### Feature requests: what underlying problem are you trying to solve with this feature?

I am developing Kibana 7.13.2 from the source and it needs bazel so trying to compile bazel from the source.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I ran bazel build //src:bazel-dev.exe and I got this error.

### What operating system are you running Bazel on?

> Windows 10 64-bit

### What's the output of `bazel info release`?

> release 4.1.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> downloaded installer of Bazel. Added it in the path for environmental variables. 

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
> https://github.com/Akhil22222/bazel.git
> "2813dce3361dff0292a764e0bc57b3e5d6daddce"
> "2813dce3361dff0292a764e0bc57b3e5d6daddce"

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> No, I did not find anything.

**Comment by aiuto** [comment]
Can you first try with a different output root
> WARNING: Output user root "C:/Users/TEMP/_bazel_akhil patel" contains a space. This will probably break the build. You should set a different --output_user_root. 
> Extracting Bazel installation...
