### ISSUE TITLE
Experimental UI: bazel test --java_debug prints port on wrong line

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1359]
It prints:

```
Listening for transport dt_socket at address: 5005
[316 / 317] Testing //src/test/java/com/google/devtools/build/lib:ideinfo_test 25s
```

The lines should be the other way around, so it's obvious that the test is not running.

**Comment by aehlig** [comment]
> ```
> Listening for transport dt_socket at address: 5005
> [316 / 317] Testing //src/test/java/com/google/devtools/build/lib:ideinfo_test 25s
> ```
> 
> The lines should be the other way around, so it's obvious that the test is not running.

I'm not quite sure, what your expectation is.

The output is consistent with the general layout that, if --test_output=streamed
is given, the test output flows into the scroll-back buffer and the
progress bar stays below at the bottom of the terminal. Also note that,
technically, the test is running from bazel's point of view in the sense
that the test action has started but not completed yet (that the action
itself is waiting for some external interaction is a thing).

Can you please clarify what you would like to see and why?

Thanks,
Klaus

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by kchodorow** [comment]
I'd like it to be more obvious when Bazel is waiting for me to start up the debugger. I kept on checking back to see if it was ready yet and not noticing.

With the non-experimental UI, it looks like:

```
INFO: Found 1 test target...
Listening for transport dt_socket at address: 5005

```

Which isn't the most gorgeous status message in the world, but at least it's hard to miss.

**Comment by aehlig** [comment]
I don't think it's technically incorrect to have a status line below the streamed output; it might be a layout the user is not used to, but it contains all the relevant information.
