### ISSUE TITLE
Support for Bazel 3.7.2 on aarch64

### ISSUE THREAD

**Issue by shortcipher3** [bazelbuild/bazel#13595]
### Description of the problem / feature request:

I am building tensorflow-lite on aarch64 Fedora 32 with `bazel`.  `bazel` suggests I download a binary, but when I attempt to download I get a 404.

```
# bazel build -c opt //tensorflow/lite:libtensorflowlite.so
ERROR: The project you're trying to build requires Bazel 3.7.2 (specified in /opt/tensorflow/.bazelversion), but it wasn't found in /usr/bin.

Bazel binaries for all official releases can be downloaded from here:
  https://github.com/bazelbuild/bazel/releases

You can download the required version directly using this command:
  (cd "/usr/bin" && curl -fLO https://releases.bazel.build/3.7.2/release/bazel-3.7.2-linux-aarch64 && chmod +x bazel-3.7.2-linux-aarch64)

$ curl -fLO https://releases.bazel.build/3.7.2/release/bazel-3.7.2-linux-aarch64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
```
 
### Feature requests: what underlying problem are you trying to solve with this feature?

Trying to build tensorflow-lite on aarch64 Fedora 32, I followed the instructions provided in the bazel build error, which gave another error.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have a Dockerfile to reproduce:
```
FROM arm64v8/fedora:32

RUN dnf update -y \
  && dnf install -y \
  dnf-plugins-core \
  gcc \
  g++ \
  cmake \
  curl \
  findutils \
  git \
  pkg-config \
  python3-pip \
  vim \
  wget \
  zip

RUN dnf copr enable -y vbatts/bazel \
  && dnf install -y \
  bazel3
#  && cd "/usr/bin" \
#  && curl -fLO https://releases.bazel.build/3.7.2/release/bazel-3.7.2-linux-aarch64 \
#  && chmod +x bazel-3.7.2-linux-aarch64

ENV TENSORFLOW_DIR=/opt/tensorflow
WORKDIR $TENSORFLOW_DIR
RUN git clone https://github.com/tensorflow/tensorflow.git $TENSORFLOW_DIR \
  && cd tensorflow \
  && bazel build -c opt //tensorflow/lite:libtensorflowlite.so
```

### What operating system are you running Bazel on?

Fedora 32 aarch64

### What's the output of `bazel info release`?

```
# bazel info release
ERROR: The project you're trying to build requires Bazel 3.7.2 (specified in /opt/tensorflow/.bazelversion), but it wasn't found in /usr/bin.

Bazel binaries for all official releases can be downloaded from here:
  https://github.com/bazelbuild/bazel/releases

You can download the required version directly using this command:
  (cd "/usr/bin" && curl -fLO https://releases.bazel.build/3.7.2/release/bazel-3.7.2-linux-aarch64 && chmod +x bazel-3.7.2-linux-aarch64)
```

###  Have you found anything relevant by searching the web?

References to trying to build tensorflow-lite for aarch64, but none with the same error.

**Comment by shortcipher3** [comment]
My hack to get the build to complete was by removing the bazel version requirement file:

```rm .bazelversion```

Tested the build and libtensorflow seems to work.

**Comment by shortcipher3** [comment]
My hack to get the build to complete was by removing the bazel version requirement file:

```rm .bazelversion```

Tested the build and libtensorflow seems to work.

**Comment by philwo** [comment]
Hi @shortcipher3,

This is apparently a bug in our `.bazelversion` wrapper: https://cs.opensource.google/bazel/bazel/+/master:scripts/packages/bazel.sh

The binary is called `bazel-3.7.2-linux-arm64` instead of `bazel-3.7.2-linux-aarch64` (see https://github.com/bazelbuild/bazel/releases/tag/3.7.2).

We should probably rewrite `aarch64` to `arm64` in the wrapper.

I think your workaround of removing the `.bazelversion` file is OK for now. Sorry for the issue.
