### ISSUE TITLE
Bazel build fails if the output_user_root is a directory in the workspace

### ISSUE THREAD

**Issue by RajivKurian** [bazelbuild/bazel#13601]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

If Bazel is given an output_user_root (via the __output_user_root startup option) that points to any child directory of the workspace directory, a build fails with cryptic messages

### Feature requests: what underlying problem are you trying to solve with this feature?

Not a feature request

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run a bazel build with some variant of 
`bazel --output_user_root=./some_output_folder build //...`
Expected: successful build.
Actual result:
```
ERROR: error loading package 'bazel_build/a2c243acddb395e730bcba922df62265/external/bazel_skylib/lib': cannot load '//:bzl_library.bzl': no such file
```
Sometimes, some other external package file shows up as not showing.

### What operating system are you running Bazel on?

Linux, Ubuntu 20.04

### What's the output of `bazel info release`?

`release 4.0.0`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

Cryptic errors seem similar to the issue at https://github.com/bazelbuild/bazel/issues/10653

### Any other information, logs, or outputs that you want to share?
It seems like the problem occurs no matter what child directory of the workspace I provide. It could be 2 levels down and I get similar problems.
So far I have only seen `bazel build //...` fail. When I build specific targets, it always seems to work.

**Comment by RajivKurian** [comment]
There was a user error involved :)

**Comment by aiuto** [comment]
This seems like a documentation problem. It is not allowed but we don't say that on https://docs.bazel.build/versions/main/command-line-reference.html

**Comment by philwo** [comment]
We should catch this and print an error message.
