### ISSUE TITLE
--watchfs malfunctions on an NFS mount

### ISSUE THREAD

**Issue by kayasoze** [bazelbuild/bazel#1361]
It would appear that `--watchfs` should be automatically disabled when the source tree is mounted over NFS, as it does not operate correctly.

**Comment by ulfjack** [comment]
Is there a cheap way to detect nfs mounts? Should we parse /proc/mounts?

**Comment by meisterT** [comment]
mount -t $filesystemtype prints all mountpoints with the given file system type on Linux. I don't know how portable this is.

**Comment by damienmg** [comment]
works on OS X too.

**Comment by ulfjack** [comment]
Subprocessing to mount on every build? :-/

**Comment by meisterT** [comment]
I don't understand why on every build. --watchfs is a startup option and IMO it's a valid assumption that the file system type stays the same across builds.

**Comment by damienmg** [comment]
Because Ulf is making it a build option. We could however call mount once
instead of at ever build.

**Comment by ulfjack** [comment]
Well, if we're going to make it magic, I'd rather make it reliable magic,
and there are a couple of corner cases that we might want to cover.

Fortunately, mount is pretty fast (at least on my machine), and parsing
/proc/mounts is also not entirely out of the question (but specific to
Linux).

**Comment by meisterT** [comment]
We do a check here for the output base already:
https://cs.opensource.google/bazel/bazel/+/master:src/main/cpp/blaze_util_linux.cc;l=78;drc=479c904695571579d9bccbee8a2d6b74f962ef20

We could do a similar check for the WORKSPACE file and pass that on.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
