### ISSUE TITLE
Unable to install jaxlib on Windows using bazel

### ISSUE THREAD

**Issue by keepingupwithdeeplearning** [bazelbuild/bazel#13617]
>I have been trying to install jaxlib on Windows10 using bazel 4.0.0 and msys2. But it keeps giving me the following cuda related error:
![Screenshot (54)](https://user-images.githubusercontent.com/32151860/123502615-196b5a80-d691-11eb-9dc7-ae2ca40d81b5.png)

If I use bazel 4.1.0, I get the following cpu related error:

![Screenshot (55)](https://user-images.githubusercontent.com/32151860/123502704-b8905200-d691-11eb-8247-afe86d11383e.png)

**Comment by aiuto** [comment]
Can you provide a short set of steps to reproduce this issue.

**Comment by keepingupwithdeeplearning** [comment]
I'm building jaxlib on Windows10 from source:
[https://jax.readthedocs.io/en/latest/developer.html#building-jaxlib-from-source](url)

After downloading jaxlib source code and installing bazel 4.0.0 and msys2, I used the following command :

python .\build\build.py --enable_cuda --cuda_path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1" --cudnn_path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1" --cuda_compute_capabilities="6.1" --cuda_version="10.1" --cudnn_version="7.6.5"

Thanks.

**Comment by aiuto** [comment]
You should ask this question wherever jaxlib go for support. Someone would have to trace down their build.py script and understand that to make any useful comments. That is not something the Bazel team would know about.
