### ISSUE TITLE
Bazel doesn't build with openjdk 11  Release 4.1.0 (2021-05-21)

### ISSUE THREAD

**Issue by makingglitches** [bazelbuild/bazel#13611]
So...

> ./compile.sh
> 
> /usr/bin/which: no javac in (/home/john/perl5/bin:/usr/bin/pycharm-community-2021.1.1/bin:/home/john/perl5/bin:/home/john/.local/bin:/home/john/bin:/usr/bin/pycharm-community-2021.1.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/john/.dotnet/tools:/usr/local/lib/nodejs/node-v16.0.0-linux-x64/bin:/usr/local/lib/nodejs/node-v16.0.0-linux-x64/bin)
> readlink: missing operand
> Try 'readlink --help' for more information.
> Building Bazel from scratchfind: ‘/usr/share/java/netty-buffer.jar’: No such file or directory
> find: ‘/usr/share/java/netty-codec-dns.jar’: No such file or directory
> find: ‘/usr/share/java/netty-codec-haproxy.jar’: No such file or directory
> find: ‘/usr/share/java/netty-codec-http2.jar’: No such file or directory
> find: ‘/usr/share/java/netty-codec-http.jar’: No such file or directory
> find: ‘/usr/share/java/netty-codec.jar’: No such file or directory
> find: ‘/usr/share/java/netty-codec-memcache.jar’: No such file or directory
> find: ‘/usr/share/java/netty-codec-mqtt.jar’: No such file or directory
> find: ‘/usr/share/java/netty-codec-redis.jar’: No such file or directory
> find: ‘/usr/share/java/netty-codec-smtp.jar’: No such file or directory
> find: ‘/usr/share/java/netty-codec-socks.jar’: No such file or directory
> find: ‘/usr/share/java/netty-codec-stomp.jar’: No such file or directory
> find: ‘/usr/share/java/netty-common.jar’: No such file or directory
> find: ‘/usr/share/java/netty-handler.jar’: No such file or directory
> find: ‘/usr/share/java/netty-handler-proxy.jar’: No such file or directory
> find: ‘/usr/share/java/netty-resolver-dns.jar’: No such file or directory
> find: ‘/usr/share/java/netty-resolver-dns-native-macos.jar’: No such file or directory
> find: ‘/usr/share/java/netty-resolver.jar’: No such file or directory
> find: ‘/usr/share/java/netty-transport.jar’: No such file or directory
> find: ‘/usr/share/java/netty-transport-native-epoll.jar’: No such file or directory
> find: ‘/usr/share/java/netty-transport-native-kqueue.jar’: No such file or directory
> find: ‘/usr/share/java/netty-transport-native-unix-common.jar’: No such file or directory
> find: ‘/usr/share/java/netty-transport-sctp.jar’: No such file or directory
> find: ‘/usr/share/java/gson.jar’: No such file or directory
> find: ‘/usr/share/java/tomcat9-annotations-api.jar’: No such file or directory
> find: ‘/usr/share/java/tomcat9-annotations-api.jar’: No such file or directory
> find: ‘/usr/share/java/java-allocation-instrumenter.jar’: No such file or directory
> find: ‘/usr/share/java/protobuf.jar’: No such file or directory
> find: ‘/usr/share/java/protobuf-util.jar’: No such file or directory
> find: ‘/usr/share/java/protobuf.jar’: No such file or directory
> find: ‘/usr/share/java/protobuf-util.jar’: No such file or directory
> find: ‘/usr/share/java/commons-collections3.jar’: No such file or directory
> find: ‘/usr/share/java/commons-lang.jar’: No such file or directory
> find: ‘/usr/share/java/commons-compress.jar’: No such file or directory
> find: ‘/usr/share/java/commons-logging.jar’: No such file or directory
> find: ‘/usr/share/java/commons-pool2.jar’: No such file or directory
> find: ‘/usr/share/java/velocity.jar’: No such file or directory
> find: ‘/usr/share/java/asm.jar’: No such file or directory
> find: ‘/usr/share/java/jackson-core.jar’: No such file or directory
> find: ‘/usr/share/java/jcip-annotations.jar’: No such file or directory
> find: ‘/usr/share/java/jcip-annotations.jar’: No such file or directory
> find: ‘/usr/share/java/jsr305.jar’: No such file or directory
> find: ‘/usr/share/java/jsr305.jar’: No such file or directory
> find: ‘/usr/share/java/netty-tcnative.jar’: No such file or directory
> find: ‘/usr/share/java/javapoet.jar’: No such file or directory
> find: ‘/usr/share/java/jaxb-api.jar’: No such file or directory
> find: ‘/usr/share/java/xz.jar’: No such file or directory
> find: ‘/usr/share/java/geronimo-annotation-1.3-spec.jar’: No such file or directory
> find: ‘/usr/share/java/com.android.tools.common.jar’: No such file or directory
> find: ‘/usr/share/java/com.android.tools.repository.jar’: No such file or directory
> find: ‘/usr/share/java/com.android.tools.layoutlib.layoutlib-api.jar’: No such file or directory
> find: ‘/usr/share/java/guava.jar’: No such file or directory
> find: ‘/usr/share/java/guava.jar’: No such file or directory
> find: ‘/usr/share/java/org.jacoco.agent.jar’: No such file or directory
> find: ‘/usr/share/java/org.jacoco.agent.jar’: No such file or directory
> find: ‘/usr/share/java/org.jacoco.core.jar’: No such file or directory
> find: ‘/usr/share/java/org.jacoco.core.jar’: No such file or directory
> find: ‘/usr/share/java/org.jacoco.core.jar’: No such file or directory
> find: ‘/usr/share/java/org.jacoco.core.jar’: No such file or directory
> find: ‘/usr/share/java/org.jacoco.report.jar’: No such file or directory
> find: ‘/usr/share/java/org.jacoco.report.jar’: No such file or directory
> find: ‘/usr/share/java/org.jacoco.agent.jar’: No such file or directory
> find: ‘/usr/share/java/org.jacoco.agent.jar’: No such file or directory
> find: ‘/usr/share/java/auto-common.jar’: No such file or directory
> find: ‘/usr/share/java/auto-service.jar’: No such file or directory
> find: ‘/usr/share/java/auto-service-annotations.jar’: No such file or directory
> find: ‘/usr/share/java/escapevelocity.jar’: No such file or directory
> find: ‘/usr/share/java/auto-value.jar’: No such file or directory
> find: ‘/usr/share/java/auto-value-annotations.jar’: No such file or directory
> find: ‘/usr/share/java/auto-value.jar’: No such file or directory
> find: ‘/usr/share/java/auto-value-annotations.jar’: No such file or directory
> find: ‘/usr/share/java/auto-common.jar’: No such file or directory
> find: ‘/usr/share/java/escapevelocity.jar’: No such file or directory
> find: ‘/usr/share/java/javapoet.jar’: No such file or directory
> find: ‘/usr/share/java/google-api-client.jar’: No such file or directory
> find: ‘/usr/share/java/google-api-client-jackson2.jar’: No such file or directory
> find: ‘/usr/share/java/google-http-client.jar’: No such file or directory
> find: ‘/usr/share/java/google-http-client-jackson2.jar’: No such file or directory
> find: ‘/usr/share/java/google-auth-library-oauth2-http.jar’: No such file or directory
> find: ‘/usr/share/java/google-auth-library-credentials.jar’: No such file or directory
> find: ‘/usr/share/java/error-prone-annotations.jar’: No such file or directory
> find: ‘/usr/share/java/error-prone-type-annotations.jar’: No such file or directory
> find: ‘/usr/share/java/error-prone-annotations.jar’: No such file or directory
> find: ‘/usr/share/java/java-diff-utils.jar’: No such file or directory
> find: ‘/usr/share/java/opencensus-api.jar’: No such file or directory
> find: ‘/usr/share/java/opencensus-contrib-grpc-metrics.jar’: No such file or directory
> find: ‘/usr/share/java/perfmark-api.jar’: No such file or directory
> find: ‘/usr/share/java/flogger.jar’: No such file or directory
> find: ‘/usr/share/java/flogger-system-backend.jar’: No such file or directory
> find: ‘/usr/share/java/google-extensions.jar’: No such file or directory
> find: ‘/usr/share/java/flogger.jar’: No such file or directory
> find: ‘/usr/share/java/flogger-system-backend.jar’: No such file or directory
> find: ‘/usr/share/java/google-extensions.jar’: No such file or directory
> find: ‘/usr/share/java/checker-qual.jar’: No such file or directory
> find: ‘/usr/share/java/grpc-api.jar’: No such file or directory
> find: ‘/usr/share/java/grpc-auth.jar’: No such file or directory
> find: ‘/usr/share/java/grpc-context.jar’: No such file or directory
> find: ‘/usr/share/java/grpc-core.jar’: No such file or directory
> find: ‘/usr/share/java/grpc-netty.jar’: No such file or directory
> find: ‘/usr/share/java/grpc-protobuf.jar’: No such file or directory
> find: ‘/usr/share/java/grpc-protobuf-lite.jar’: No such file or directory
> find: ‘/usr/share/java/grpc-stub.jar’: No such file or directory
> 
> ERROR: JDK not found, please set $JAVA_HOME.
> 

I set JAVA_HOME same error.

>  1050  JAVA_HOME=/lib/jvm/java-11-openjdk-11.0.11.0.9-4.fc34.x86_64
>  1051  PATH=$PATH:$JAVA_HOME/bin
>  1052  export JAVA_HOME
>  1053  export PATH

**Comment by makingglitches** [comment]
Setting javahome and path results in this: 
This is a source release.

> ERROR: Must specify PROTOC if not bootstrapping from the distribution artifact
> 
> --------------------------------------------------------------------------------
> NOTE: This failure is likely occuring if you are trying to bootstrap bazel from
> a developer checkout. Those checkouts do not include the generated output of
> the protoc compiler (as we prefer not to version generated files).
> 
> * To build a developer version of bazel, do
> 
>     bazel build //src:bazel
> 
> * To bootstrap your first bazel binary, please download a dist archive from our
>   release page at https://github.com/bazelbuild/bazel/releases and run
>   compile.sh on the unpacked archive.
> 
> The full install instructions to install a release version of bazel can be found
> at https://docs.bazel.build/install-compile-source.html
> For a rationale, why the bootstrap process is organized in this way, see
> https://bazel.build/designs/2016/10/11/distribution-artifact.html
> --------------------------------------------------------------------------------
>

**Comment by makingglitches** [comment]
Strange repo organization,   need to download the archive with -dist as its suffix before even beginning to build is possible.
This needs to be added to the documentation. Its not there.

**Comment by xlla** [comment]
hi @makingglitches, I'v encounter same issue while build bazel 5.2.0, how to resolve it?

**Comment by makingglitches** [comment]
@xlla I was doing this to build tensorflow I think, i can't remember now for sure. Anyway  issue I think was you had to bootstrap from bazel itself and it also needed to grab a bunch of software from google. As I said this was awhile ago. I don't like self-dependent build systems heh.

**Comment by xlla** [comment]
@makingglitches I see, I manage extract many files from -dist archive file and put them into the source folder, now it get compiled, thank you!
