### ISSUE TITLE
Prefer ANDROID_SDK_ROOT to ANDROID_HOME

### ISSUE THREAD

**Issue by hevrard** [bazelbuild/bazel#13612]
### Description of the problem / feature request:

Bazel uses `ANDROID_HOME` to lookup the SDK, as documented in https://docs.bazel.build/versions/main/tutorial/android-app.html#integrate-with-the-android-sdk

However, Android Studio and other command-line tools have deprecated `ANDROID_HOME` in favor of `ANDROID_SDK_ROOT`: https://developer.android.com/studio/command-line/variables#envar

In order to be consistent, Bazel should probably lookup `ANDROID_SDK_ROOT`, and prefer it over `ANDROID_HOME`.

### Feature requests: what underlying problem are you trying to solve with this feature?

Be consistent in how Android-related environment variables are used across projects.

**Comment by hevrard** [comment]
Thanks for the follow-up!

The Android documentation pointed to via the second link starts by saying that `ANDROID_HOME` is **deprecated**:

```
ANDROID_HOME, which also points to the SDK installation directory, is deprecated.
```

So my request is not so much about the priority between the two envvars, but rather to have Bazel directly use `ANDROID_SDK_ROOT`. Currently, I don't think Bazel looks for `ANDROID_SDK_ROOT` at all?

I guess best would be for Bazel to actually check for both envvars and implement the resolution logic described in the doc?

**Comment by ted-xie** [comment]
You're entirely correct that `ANDROID_HOME` is deprecated according to the documentation, and that Bazel currently does not check for `ANDROID_SDK_ROOT`.

I agree with your suggestion: the best course of action at the moment is for Bazel to check both environment variables and attempt some basic resolution strategy for the various corner cases.

**Comment by ted-xie** [comment]
Hi @hevrard,

I've just learned that Android Studio has chosen to deprecate ANDROID_SDK_ROOT, so we will remove the functionality to consider that environment variable as the SDK installation location.

See https://developer.android.com/studio/command-line/variables, and screenshot below, taken on 2022 Apr 19.

![androidsdkrootandroidstudio](https://user-images.githubusercontent.com/4371677/164074211-64f7d664-4e7a-4376-8b57-8878c89dbd62.png)

**Comment by hevrard** [comment]
Thanks for the notice, and thanks for keeping up with the latest Android envvar choices!
