### ISSUE TITLE
Build artifacts are missing with "--remote_download_toplevel" cache option

### ISSUE THREAD

**Issue by loshca** [bazelbuild/bazel#13625]
### Description of the problem / feature request:

Assume we have two targets, one dependency of another: 
```
genrule(
    name = "echo", 
    outs = ["echo.txt"],
    cmd = "echo \"something\" > $@",
)

genrule(
    name = "cat",  
    srcs = [":echo"],
    outs = ["cat.txt"],
    cmd = "cat $(locations :echo) > $@",
)
```

If we get `cat` target from cache with `--remote_download_toplevel`: `bazel build cat --disk_cache=D:\bazel_disk_cache --remote_download_toplevel`, then we will not be able to get output for `echo` with `bazel build echo --disk_cache=D:\bazel_disk_cache --remote_download_toplevel`. Instead we got an up to date message and that's it, `bazel-bin/echo.txt` is not presented :
```
INFO: Invocation ID: d8e174cf-83cd-49bf-9f51-3367241fd6e1
INFO: Analyzed target //:echo (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:echo up-to-date:
  bazel-bin/echo.txt
INFO: Elapsed time: 0.153s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

### What operating system are you running Bazel on?

Windows & MacOS

### What's the output of `bazel info release`?

4.0.0

**Comment by loshca** [comment]
Probably we need a little bit more complicated logic with [shouldTrustRemoteArtifacts](https://github.com/bazelbuild/bazel/blob/300c11ef5eb00978cbaa4d3a14ccfee10d9c87f8/src/main/java/com/google/devtools/build/lib/vfs/OutputService.java#L85).

**Comment by coeuvre** [comment]
IIUC, in your example, the second command for `echo` is ran right after the first one for `cat`. In this case, the ActionCache checked that no change between these two commands so the action will not be re-executed. Since downloading outputs only happens within action execution, the output of `echo` will not be downloaded.

This is a known issue and I am working on it. https://github.com/bazelbuild/bazel/issues/12665

**Comment by appuser999** [comment]
@coeuvre Hi, I have encountered the same problem, is there any workaround?
```bzl
load("//tools/docker:web.bzl", "web_container")
load("@npm//vite:index.bzl", "vite")

package(default_visibility = ["//visibility:public"])

_package_segments = len(package_name().split("/"))

vite(
    name = "build",
    outs = ["dist"],
    ...
)
web_container(
    name = "frontend",
    dist = [":build"],
)
```
error log:
```
ERROR: /data/xxx/BUILD.bazel:8:14: output 'xxx/dist' was not created
```
I tried to add `tags = ["no-remote"]` to the **vite** rule, and build with `--experimental_allow_tags_propagation` to get around the problem, but this target can't use the remote cache anymore.  Once I change the tags to `no-remote-exec` (remote-cache enabled), bazel will not download outputs **dist** to *bazel-out* and the problem will be reproduced.

Thanks.
