### ISSUE TITLE
Default remote config toolchain invocation

### ISSUE THREAD

**Issue by av8ramit** [bazelbuild/bazel#13623]
### Description of the problem / feature request:

We are looking to use the default remote config toolchain with a CPU only build. What is the proper way to invoke this? 

### Feature requests: what underlying problem are you trying to solve with this feature?

Use the CPU only toolchain for CPU builds on TensorFlow RBE presubmits. 

### What operating system are you running Bazel on?

Linux Ubuntu 16.

As of right now the toolchain for GPU builds is referenced like so:
`host_crosstool_top="@ubuntu18.04-gcc7_manylinux2010-cuda11.2-cudnn8.1-tensorrt7.2_config_cuda//crosstool:toolchain"`

What would the appropriate toolchain target be for a CPU only toolchain as defined [here](https://github.com/tensorflow/toolchains/blob/master/toolchains/remote_config/configs.bzl#L10-L15).

**Comment by av8ramit** [comment]
Adding @mihaimaruseac as well.

**Comment by oquenchil** [comment]
@katre John would you know by looking at the bzl file linked by Amit?

**Comment by katre** [comment]
I'm sorry, but I don't understand what is being asked. @av8ramit, what do you mean by a "CPU only toolchain"? What are you trying to do that you cannot do with the existing `--host_crosstool_top` flag?

**Comment by av8ramit** [comment]
So I'm very sorry, but I'm very unfamiliar with toolchains terminology. I guess what would be the equivalent value for the argument `--host_crosstool_top` for the following [toolchain](https://github.com/tensorflow/toolchains/blob/master/toolchains/remote_config/configs.bzl#L10-L15) using remote config? I imagine it would be something like `@ubuntu18.04-gcc7_manylinux2010//crosstool:toolchain`, but I'm not sure. If my question does not make sense please feel free to close as we have a working solution by using the GPU toolchain with CUDA for both CPU and GPU.

**Comment by katre** [comment]
Sorry for the delay in answering, I had trouble re-finding this issue. The `--host_crosstool_top` flag specifically sets the value of the `--crosstool_top` flag when building in host mode: ie when building tools that will be run as part of a build on the local host. Unfortunately, that has no meaning with remote builds: you could have multiple types of remote workers executing build actions.

The equivalent with toolchains is to set the execution platform, and then let the correct toolchain be chosen for each execution platform. The relevant docs are [Building with platforms](https://docs.bazel.build/versions/4.1.0/platforms-intro.html), so take a look at that and see if that help to clarify issues.

**Comment by aiuto** [comment]
Closing on WAI an inactivity.
