### ISSUE TITLE
watchfs makes race conditions for builds much more likely.

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#1362]
OS: OSX
I started using watchfs, and was able to observe issues in watch fs that I was not able to replicate without it.

The race condition is that I will save a file using my editor and then immediately trigger a build. In particular, I do not wait for my editor to acknowledge the save, I just switch over and start the build. (:wq<return><ctrl-T><ctrl-T><ctrl-P><return>, write out the vim buffer, switch tmux windows, and rerun my last terminal command). Without watchfs I have not been able to make blaze build with the old version of the file, but with watchfs I have made changes and then not seen those reflected in the build. This is likely because the notification system is adding latency between when the file is written and when listeners are notified.

**Comment by damienmg** [comment]
Yes this is expected. Maybe the FsEvents version is too slow and we will have to remove it.
/cc @ulfjack fyi

**Comment by damienmg** [comment]
kFSEventStreamCreateFlagNoDefer seems to help a little, still investigating.

**Comment by damienmg** [comment]
But it returns folders instead of files...

**Comment by damienmg** [comment]
Ok this flag fix all flakiness on my side, rolling-it out for 0.4 :)

**Comment by damienmg** [comment]
change is in-flight
