### ISSUE TITLE
When I use `toolchain`, it should be choosen  `@platforms//os:windows` instead of `@platforms//os:osx`.

### ISSUE THREAD

**Issue by kekxv** [bazelbuild/bazel#13622]
When I use `toolchain`, it should be choosen  `@platforms//os:windows` instead of `@platforms//os:osx`.

```bazel
select({
  "@platforms//os:windows":{"CMAKE_SYSTEM_NAME": "Windows",},
  "@platforms//os:osx":{"CMAKE_SYSTEM_NAME": "osx",},
  "//conditions:default":{}
}),
```

**Comment by oquenchil** [comment]
Can you please provide command line, bazel version, the BUILD file with your target and the system you are on?
