### ISSUE TITLE
`no-remote` and `no-remote-cache` are affecting the disk cache

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/bazel#13621]
### Description of the problem / feature request:

When an action is tagged with `no-remote` or `no-remote-cache`, it's not properly using the disk cache. Only with `no-cache` should it exclude the disk cache as well.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```shell
bazel build --disk_cache=/tmp/disk_cache -- //some/cacheable:target
bazel clean
bazel build --disk_cache=/tmp/disk_cache --modify_execution_info='.*=+no-remote-cache' -- //some/cacheable:target
```

The second build won't check the disk cache.

### What operating system are you running Bazel on?

macOS 11.4

### What's the output of `bazel info release`?

4.1.0, but is still broken at HEAD.

**Comment by coeuvre** [comment]
For the given repro, the second build missed the cache because the `actionKey` is changed - adding `no-remote-cache` [changes](https://github.com/bazelbuild/bazel/blob/0f812eb5e561cc5415d0c9931675e58dc37a5850/src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java#L262)  filed `do_not_cache` of `Action` message from `false` to `true`.

However, we do expect the second build hit the disk cache if the first build has the same flag `--modify_execution_info='.*=+no-remote-cache'`. The culprit is that we doesn't upload the AC to disk cache due to the [check in the upload code](https://github.com/bazelbuild/bazel/blob/18c82168433719b400a705a4a0222969a7a026ba/src/main/java/com/google/devtools/build/lib/remote/RemoteCache.java#L195) checked `do_not_cache` field is `false` which is obviously wrong in this case.

**Comment by brentleyjones** [comment]
> For the given repro, the second build missed the cache because the `actionKey` is changed - adding `no-remote-cache` [changes](https://github.com/bazelbuild/bazel/blob/0f812eb5e561cc5415d0c9931675e58dc37a5850/src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java#L262) field `do_not_cache` of `Action` message from `false` to `true`. I am not sure what's the expected behavior here.

Seems to me that `do_not_cache` shouldn't be part of the `actionKey`.



> However, we do expect the second build hit the disk cache if the first build has the same flag `--modify_execution_info='.*=+no-remote-cache'`. The culprit is that we doesn't upload the AC to disk cache due to the [check in the upload code](https://github.com/bazelbuild/bazel/blob/18c82168433719b400a705a4a0222969a7a026ba/src/main/java/com/google/devtools/build/lib/remote/RemoteCache.java#L195) checked `do_not_cache` field is `true` which is obviously wrong in this case.

This is my main use, I'm not flipping the flag, I'm just setting it globally, and I noticed that those with `no-remote-cache` were causing the disk cache to not work.

**Comment by coeuvre** [comment]
> Seems to me that `do_not_cache` shouldn't be part of the `actionKey`.

That's defined by [REAPI](https://github.com/bazelbuild/remote-apis/blob/main/build/bazel/remote/execution/v2/remote_execution.proto#L491) used to tell remote server whether the action result should be cached. I understand that this field doesn't make sense in our case but I am not sure the correct way to handle this, considering we may combine disk cache with remote cache.

**Comment by coeuvre** [comment]
The linked PR should fix this issue.

For the combined cache, it is currently considered as remote cache i.e. if `no-remote-cache` is set, both disk and remote cache are not touched for the action. I am not sure whether this is expected so I leave it unchanged. But I would think, in this case, the disk cache should be used and leave remote cache untouched.

**Comment by brentleyjones** [comment]
The description of the tags say to use `no-cache` to exclude from both disk and remote cache, and that `no-remote-cache` only applies to the `remote` cache. This is a regression from that original behavior.

https://docs.bazel.build/versions/main/be/common-definitions.html#common.tags
https://github.com/bazelbuild/bazel/issues/7932#issuecomment-502789602
https://github.com/bazelbuild/bazel/issues/7932#issuecomment-510410467

**Comment by brentleyjones** [comment]
Wow, I guess I missed this part, which I feel is the main issue? I feel it's wrong:
> If a combined cache is specified (i.e. a cache with local and remote components), it's treated as a remote cache and disabled entirely.

**Comment by coeuvre** [comment]
Thanks for the pointers!

Yes, for the combined cache, it seems reasonable that `no-remote-cache` only disables remote cache, the disk cache should still be enabled. Maybe I can reuse the `incompatible_remote_results_ignore_disk` flag to change this behavior.

**Comment by brentleyjones** [comment]
Thanks @coeuvre!
