### ISSUE TITLE
Expose urldecode in native

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#1363]
Wondering whether it would be possible to expose `urldecode` for Skylark. Reason is that you cannot use symbolic links when using P4 and thus we encode the link information in the path. Now in Bazel we would like to have a chance to decode that info again.
Or if someone has a better approach I am all ears :+1:

**Comment by hermione521** [comment]
No idea.. @laurentlb Can you help with this? Thanks.

**Comment by laurentlb** [comment]
You mean a function like this: https://docs.oracle.com/javase/7/docs/api/java/net/URLDecoder.html?
Can you write yourself it using str.replace?

**Comment by abergmeier** [comment]
@laurentlb Mostly although handling UTF is a bigger task. Perhaps it would be better to have a general way of handling URLs exposed?

**Comment by laurentlb** [comment]
Handling URLs seems a bit unrelated to the job of a build system. I'd prefer keep the API small when possible.
Any change you can delegate this task to an external tool?

**Comment by abergmeier** [comment]
Yes, we are already looking into that.
