### ISSUE TITLE
FilesystemValueCheckerTest#testPropagatesRuntimeExceptions fails on new Windows VM image

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#13638]
While preparing a new Windows VM image, I noticed that there's one test method apparently consistently failing now:

```
Executing tests from //src/test/java/com/google/devtools/build/lib/skyframe:SkyframeTests
[...]
There was 1 failure:
1) testPropagatesRuntimeExceptions(com.google.devtools.build.lib.skyframe.FilesystemValueCheckerTest)
java.lang.NullPointerException
	at com.google.common.truth.ThrowableSubject.hasMessageThat(ThrowableSubject.java:58)
	at com.google.devtools.build.lib.skyframe.FilesystemValueCheckerTest.testPropagatesRuntimeExceptions(FilesystemValueCheckerTest.java:1005)
```

The main differences between the old image and the new one are:
- Windows version (old: Windows 10 build 1909, new: Windows 10 20H2)
- Visual Studio Build Tools that provide e.g. the C++ compiler (old: 2017, new: 2019)
- System JDK (old: Azul Zulu OpenJDK 8, new: Azul Zulu OpenJDK 11)
- Windows SDK (old: v10.1, new: v2004)

Full log is here: https://storage.googleapis.com/bazel-testing-buildkite-artifacts/c777f519-3c2c-4cf0-9c5b-14b2adb0f142/src%5Ctest%5Cjava%5Ccom%5Cgoogle%5Cdevtools%5Cbuild%5Clib%5Cskyframe%5CSkyframeTests%5Cattempt_1.log

This test method failed with this message even after three retries.

@janakdr Any idea why this would fail with a NullPointerException? Unfortunately you can't yet easily test it yourself, as the new Windows VM image isn't live yet, but if you want to try a fix, I can help. Or we could disable the test method, roll the image out and then you could iterate on it until it works. Not sure if you're the right person, but saw that you touched the file recently. 😊

**Comment by philwo** [comment]
Oh wow, it looks like the test is actually flaky. I ran another job and then it succeeded after one retry: https://buildkite.com/bazel-testing/bazel-bazel/builds/8260#23027803-d4f4-429a-a7bd-bdbc859dec32

**Comment by janakdr** [comment]
Looks impossible. Browsing the ThrowableSubject code, I think the line that's throwing is

```
    return check.that(actual.getMessage());
```

`check` isn't null, so `actual` must be null, but `actual` comes from `assertThrows` above. Can you add a `Preconditions.checkNotNull` above the failing line to confirm that the RuntimeException is actually present? I think the contract of assertThrows guarantees that.

**Comment by janakdr** [comment]
Assigning to Phil to try the suggestions above.

**Comment by janakdr** [comment]
Whoops, looks like I was reading the wrong code. Sorry Philipp!
