### ISSUE TITLE
bazel FATAL: corrupt installation

### ISSUE THREAD

**Issue by thna123459** [bazelbuild/bazel#13631]
### Description of the problem / feature request:

Observed on several CI instances today:
```
bazel-4.1.0 clean
FATAL: corrupt installation: file '/foo/.cache/bazel/_bazel_user-agent/install/f95ca91ebcfff56aa0f8ad499de9abcd/tools/WORKSPACE' is missing or modified.
Please remove '/foo/.cache/bazel/_bazel_user-agent/install/f95ca91ebcfff56aa0f8ad499de9abcd' and try again.
```

Recovering from the error requires manual intervention.

### Feature requests: what underlying problem are you trying to solve with this feature?

Bazel should be able to recover from the error without requiring manual intervention (`bazel clean` and `bazel clean --expunge` fail).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

This is not easily reproduced.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 4.1.0

###  Have you found anything relevant by searching the web?

No.

**Comment by oquenchil** [comment]
Have you seen this again?

If there is no way to reproduce I'm afraid it will be near impossible to debug.

**Comment by thna123459** [comment]
I cannot reproduce it anymore, will re-open with more information if it occurs again.
