### ISSUE TITLE
"debian_java_deps" repo causes bazel query to fail on non-Linux platform in Bazel repo

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#13636]
### Description of the problem:

Inside the Bazel repository:
`bazel query "deps(//src/main/java/com/google/devtools/build/skydoc:skydoc_lib)"` fails on macOS with
```
ERROR: Error fetching repository: java.io.IOException: The repository's path is "/usr/share/java" (absolute: "/usr/share/java") but this directory does not exist.
ERROR: /Users/pcloudy/workspace/bazel/third_party/BUILD:368:20: no such package '@debian_java_deps//': The repository's path is "/usr/share/java" (absolute: "/usr/share/java") but this directory does not exist. and referenced by '//third_party:error_prone_annotations'
```

The `debian_java_deps` repo only makes sense on Linux, but because the `bazel query` command tries to reach every possible dependency, it will still be fetched on other platforms. I think it's tricky to solve this without some kind of conditional external dependency support.

Note that, `bazel cquery` still works well.

### What operating system are you running Bazel on?

macOS

**Comment by philwo** [comment]
This is now also happening on CentOS 7 when you install a newer JDK (e.g. Azul Zulu OpenJDK 11) - apparently those third-party JDKs do not create the `/usr/share/java` folder: https://buildkite.com/bazel/google-bazel-presubmit/builds/50842#073588dc-e99d-4920-8de4-a8c2550d3bbd
