### ISSUE TITLE
Documentation issue: One-Page Overview

### ISSUE THREAD

**Issue by ssiano** [bazelbuild/bazel#13637]
Documentation URL: https://docs.bazel.build/versions/main/skylark/lib/skylark-overview.html

The internal page navigation links in the upper right corner do not work, e.g.,

[Global Functions](https://docs.bazel.build/versions/main/skylark/lib/skylark-overview.html#--global-functions)
[Global Constants](https://docs.bazel.build/versions/main/skylark/lib/skylark-overview.html#--global-constants)
etc.

They seem to work if I remove the `--`, e.g., `#global-functions` instead of `#--global-functions`, although that might not be the right solution.

**Comment by fweikert** [comment]
Links are fixed in the new version of the site: https://bazel.build/rules/lib/starlark-overview

**Comment by ssiano** [comment]
Thank you, @fweikert!
