### ISSUE TITLE
C++ rules includes argument should not use -isystem, but -I

### ISSUE THREAD

**Issue by xykivo** [bazelbuild/bazel#13642]
### Description of the problem / feature request:

The C++ rules includes argument should use the -I to add the includes paths specified to any dependent C++ target.
Using -isystem forces a behaviour that should be reserved to system or toolchain headers.
There is no other reasonable way to propagate includes to any other C++ targets that directly or indirectly depend on a C++ library.
If the behaviour of using -isystem is still needed then it should be under an argument names system_includes, or sys_includes.

### Feature requests: what underlying problem are you trying to solve with this feature?

Propagating includes to C++ targets that depend directly on indirectly on a C++ library without having to copy paste the include paths, and without having to use -isystem.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

NA

### What operating system are you running Bazel on?

Ubuntu 20.04

### What's the output of `bazel info release`?

release 4.1.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

NA

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

NA

###  Have you found anything relevant by searching the web?

The bazel docs, and web searches only yield the includes argument, and that it uses -isystem. The docs also state to use -I<path> in the copts argument, however this causes bug prone copy paste behaviour.

### Any other information, logs, or outputs that you want to share?

No

**Comment by erenon** [comment]
"what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible."
I can not repro this, by default, `-iquote` is used, or `-I` if `strip_include_prefix`/`include_prefix` is specified.

**Comment by xykivo** [comment]
If I understand the documentation correctly the strip_include_prefix/include_prefix only affects the hdrs attribute of a cc_library.
I want a change to the includes argument of a cc_library, so that any include paths exported from it use the -I, and not the -isystem option.

**Comment by erenon** [comment]
Can you show an example that produces `-isystem`? Having `includes` does that, but it is also documented, and usually not needed either.

**Comment by xykivo** [comment]
I tried to create a sample that I feel illustrates the issue.
See https://github.com/xykivo/percipio/tree/bzl-cc-libs-includes/issues/bzl_cc_libs_includes

**Comment by erenon** [comment]
Hi,

The behavior in the `use_includes` package is expected, works as documented: "Each string is prepended with -isystem and added to COPTS" (see [includes](https://docs.bazel.build/versions/main/be/c-cpp.html#cc_library.includes))

To make the `use_copts` package work, instead of:

```
copts = ["-Iissues/bzl_cc_libs_includes/use_copts/foo/include"],
```

use:

```
strip_include_prefix = "include",
```

This will add the equivalent of `-Iissues/bzl_cc_libs_includes/use_copts/foo/include` transitively.
