### ISSUE TITLE
AarImport does not import databinding package from aars leading to runtime crash.

### ISSUE THREAD

**Issue by arunkumar9t2** [bazelbuild/bazel#13640]
### Description of the problem / feature request:

When using aars via aar import, currently databinding package [is not extracted](https://github.com/bazelbuild/bazel/blob/4ccb2cced62e4fc070349e1b8ea6c941074bccbb/src/main/java/com/google/devtools/build/lib/rules/android/AarImport.java#L463) and given to `DatabindingV2Provider`. This causes [direct dependency pkgs](https://github.com/bazelbuild/bazel/blob/4ccb2cced62e4fc070349e1b8ea6c941074bccbb/src/main/java/com/google/devtools/build/lib/rules/android/databinding/DataBindingV2Context.java#L98) to not have the package name and at runtime DatabindingMapper fails to find the `Binding` class.

### Feature requests: what underlying problem are you trying to solve with this feature?

Runtime crash when consuming aar that contains databinding generated `Binding` classes.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Create an AAR that has a layout xml file with databinding enabled
2. Import the AAR into project and launch any screen that using the AAR layout's Binding class. 
3. Observe runtime crash.

```java
java.lang.IllegalStateException: DataBindingUtil.inflate(…layout, container, false) must not be null
```

### What operating system are you running Bazel on?
MacOs Catalina 10.15.7

### What's the output of bazel info release?
release 4.1.0

### If bazel info release returns "development version" or "(@non-git)", tell us how you built Bazel.
NA

### What's the output of git remote get-url origin ; git rev-parse master ; git rev-parse HEAD ?
NA

### Related info

According to [this](https://cs.android.com/androidx/platform/frameworks/data-binding/+/mirror-goog-studio-master-dev:compilerCommon/src/main/java/android/databinding/tool/DataBindingBuilder.java;l=164;drc=1001418c00cabaa48bc849041fb60faf58c96262), the package name should be extracted from `-br.bin` file instead of the one from AndroidManifest.xml. 

Related #2694

**Comment by arunkumar9t2** [comment]
Repro project:

[databindingstrictdeps.zip](https://github.com/bazelbuild/bazel/files/6763060/databindingstrictdeps.zip)


```bash
bazelisk build //app
./gradlew app:assembleDebug
```

Gradle generated DatabindingMapperImpl has correct packages imported from dependency. For example

```java
  @Override
  public List<DataBinderMapper> collectDependencies() {
    ArrayList<DataBinderMapper> result = new ArrayList<DataBinderMapper>(1);
    result.add(new androidx.databinding.library.baseAdapters.DataBinderMapperImpl());
    return result;
  }
```

Bazel generated

```java
  @Override
  public List<DataBinderMapper> collectDependencies() {
    ArrayList<DataBinderMapper> result = new ArrayList<DataBinderMapper>(1);
    result.add(new DataBinderMapperImpl());
    return result;
  }
```

Notice `androidx.databinding.library.baseAdapters.DataBinderMapperImpl()` is missing on Bazel generated file. This causes `java.lang.IllegalStateException: DataBindingUtil.inflate(…layout, container, false) must not be null` at runtime.

**Comment by ahumesky** [comment]
Is this still an issue with the Starlark version of aar_import? if so please feel free to reopen and we'll migrate this issue to rules_android
