### ISSUE TITLE
Get rid of _bin / embedded_tools

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1365]
The embedded tools is mounted in the execroot under a _bin directory for legacy reason. We should move every binary out of the _bin directory into the @bazel_tools repository and remove this folder.

**Comment by damienmg** [comment]
Internal ref: b/28963443

**Comment by helenalt** [comment]
Reviewed, still P3, to be considered in backlog for the future work.

**Comment by meisterT** [comment]
I think this is done - at least I cannot see `_bin` anymore.
