### ISSUE TITLE
Documentation issue: User manual -- how to define default build attributes?

### ISSUE THREAD

**Issue by hostirosti** [bazelbuild/bazel#13657]
Documentation URL: https://docs.bazel.build/versions/main/be/general.html

If I got a rule using build variables like this:
```
container_push(
    name = "custom_app_image_publish",
    format = "Docker",
    image = ":custom_app",
    registry = "gcr.io",
    repository = "$(GCR_PROJECT)/custom_app",
    tag = "$(VERSION)"
)
```

How can I define default values for `$(GCR_PROJECT)` and `$(VERSION)` that are chosen if build/run is run without `--define ...`?

**Comment by oquenchil** [comment]
https://docs.bazel.build/versions/main/be/make-variables.html

See section for Starlark defined variables.

**Comment by comius** [comment]
This seems to have been answered. Please reopen if there are further questions.
