### ISSUE TITLE
native_test do not inherit data

### ISSUE THREAD

**Issue by guibou** [bazelbuild/bazel#13652]
### Description of the problem / feature request:

Using `@bazel_skylib//rules:native_binary.bzl", "native_test"` does not uses `data` from dependencies.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The following build file:

```
load("@bazel_skylib//rules:native_binary.bzl", "native_test")

cc_binary(
        name = "cpp",
        srcs = ["poulet.cpp"],
        data = ["Chien.txt"],
        copts = ['-DDATA_PATH=\\"$(rootpath :Chien.txt)\\"'],
        )

native_test(
        name = "cpp-test",
        src = ":cpp",
        out = "cpp_",
        )

native_test(
        name = "cpp-test2",
        src = ":cpp",
        out = "cpp2_",
        data = ["Chien.txt"],
)

```

define a `cpp` target which compiles a `poulet.cpp` file which at runtime loads`Chien.txt`. `Chien.txt` is available in the runfiles for this `cc_binary` and the correct path is passed using a macro definition.

Running `bazel run :cpp` displays the content of `Chien.txt`, the file is correctly found, thank to the `data` attribute.

There is then a `native_test` which just wrap the `cpp` binary.

Running `bazel run :cpp-test` or `bazel test :cpp-test` leads to a failure, the file cannot be found.
Running `bazel test :cpp-test2`, which is the same as `:cpp-test`, but with additional `data` argument is a success.

The content of the `poulet.cpp` file is:

```cpp
#include <iostream>
#include <fstream>
#include <string>

int main () {
  std::ifstream myfile(DATA_PATH);
  if(!myfile.is_open())
  {
      std::cout << "file not found" << std::endl;
      return 1;
  }
  std::string line;
  while ( getline (myfile,line) )
  {
        std::cout << line << '\n';
  }
  myfile.close();
  return 0;
}
```

The content of the `Chien.txt` file can be random, as long as the file exists and do have a content, what about:

```
Hello, I'm an happy bazel user
```

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

```
$ bazel info release
INFO: Invocation ID: 1b64c949-14d2-4a69-9ac3-f91cde16eb53
release 4.0.0- (@non-git)
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

From nixpkgs.

**Comment by oquenchil** [comment]
Can you please file this in https://github.com/bazelbuild/bazel-skylib/?

Thanks!

**Comment by guibou** [comment]
Done. Thank you.
