### ISSUE TITLE
experimental_forward_instrumented_files_info_by_default doesn't work with pkg_tar's files = {}

### ISSUE THREAD

**Issue by cocasema** [bazelbuild/bazel#13659]
### Description of the problem / feature request:

```
--[no]experimental_forward_instrumented_files_info_by_default default: "true"
If specified, rules that don't configure InstrumentedFilesInfo will still forward the contents of InstrumentedFilesInfo from transitive dependencies.
```

I found this only works for the dependencies of `pkg_tar` mentioned in `srcs = [...]`, and anything from `files = {}` is ingored.
Not sure if this is specific to pkg_tar `files`, of if it's only limited to `srcs` attributes names in general.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`WORKSPACE`
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_pkg",
    sha256 = "038f1caa773a7e35b3663865ffb003169c6a71dc995e39bf4815792f385d837d",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/0.4.0/rules_pkg-0.4.0.tar.gz",
        "https://github.com/bazelbuild/rules_pkg/releases/download/0.4.0/rules_pkg-0.4.0.tar.gz",
    ],
)
load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")
rules_pkg_dependencies()
```

`BUILD`
```
load("@rules_pkg//:pkg.bzl", "pkg_tar")
load(":instrumented-files.bzl", "instrumented_files")

pkg_tar(
    name = "pkg",
    srcs = ["instr-files"],
)

instrumented_files(
    name = "instr-files",
    srcs = [":bin"],
)

pkg_tar(
    name = "bin",
    srcs = [
        ":main1",
        # UNCOMMENT this ":main2",
    ],
    files = {
        ":main2": "main",
    },
)

cc_binary(
    name = "main1",
    srcs = ["main1.cpp"],
)

cc_binary(
    name = "main2",
    srcs = ["main2.cpp"],
)
```

`instrumented-files.bzl`
```
def _instrumented_files_impl(ctx):
    files = []

    for src in ctx.attr.srcs:
        if src[InstrumentedFilesInfo].instrumented_files:
            files.append(src[InstrumentedFilesInfo].instrumented_files)
        if src[InstrumentedFilesInfo].metadata_files:
            files.append(src[InstrumentedFilesInfo].metadata_files)

    return [
        DefaultInfo(files = depset(transitive = files)),
    ]

instrumented_files = rule(
    implementation = _instrumented_files_impl,
    attrs = {
        "srcs": attr.label_list(),
    },
)
```

`main1.cpp` / `main2.cpp`
```
int main() { return -1; }
```

Repro with:
```
bazel build :pkg --features coverage --collect_code_coverage  --experimental_forward_instrumented_files_info_by_default

tar -tvf bazel-bin/pkg.tar 
drwxr-xr-x 0/0               0 1999-12-31 16:00 ./
-r-xr-xr-x 0/0              25 1999-12-31 16:00 ./main1.cpp
-r-xr-xr-x 0/0             220 1999-12-31 16:00 ./main1.pic.gcno
```

After uncommenting `# UNCOMMENT this ":main2",` in srcs of pkg_tar:
```
bazel build :pkg --features coverage --collect_code_coverage  --experimental_forward_instrumented_files_info_by_default

tar -tvf bazel-bin/pkg.tar 
drwxr-xr-x 0/0               0 1999-12-31 16:00 ./
-r-xr-xr-x 0/0              25 1999-12-31 16:00 ./main1.cpp
-r-xr-xr-x 0/0              25 1999-12-31 16:00 ./main2.cpp
-r-xr-xr-x 0/0             220 1999-12-31 16:00 ./main1.pic.gcno
-r-xr-xr-x 0/0             220 1999-12-31 16:00 ./main2.pic.gcno
```

### What operating system are you running Bazel on?

`Linux Mint 20.1 Ulyssa`

### What's the output of `bazel info release`?

`release 4.1.0`

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

N/A

**Comment by oquenchil** [comment]
@sfreilich Hi Samuel , could you please take a look?

**Comment by sfreilich** [comment]
It certainly has nothing to do with the attribute name, it's definitely an issue with the attribute type.

That pkg_tar rule indeed doesn't provide InstrumentedFilesInfo explicitly:
https://github.com/bazelbuild/rules_pkg/blob/41a00ee70e7ec5eafe77e9fc21e042fde39a5339/pkg/pkg.bzl#L383

But I'm not sure that returning:

```
coverage_common.instrumented_files_info(
    ctx,
    source_attributes = ["scrs", "files"],
)
```

would fix things. The logic for both looks at only label and label_list attributes, not label_keyed_string_dict:
https://github.com/bazelbuild/bazel/blob/024deb58265cf1538cabe4c64f7f6c6793053b74/src/main/java/com/google/devtools/build/lib/analysis/test/InstrumentedFilesCollector.java#L449
https://github.com/bazelbuild/bazel/blob/024deb58265cf1538cabe4c64f7f6c6793053b74/src/main/java/com/google/devtools/build/lib/analysis/test/InstrumentedFilesCollector.java#L461

Which I think is a matter of the new logic extending a bug in the existing config.

I think instead it needs the more general:

```
attr.getType().getLabelClass() == LabelClass.DEPENDENCY
```

I'll work on a fix.

**Comment by sfreilich** [comment]
I think that change (9015f38) should fix the issue, and this can be closed.

**Comment by cocasema** [comment]
> I think that change ([9015f38](https://github.com/bazelbuild/bazel/commit/9015f383220892b638d47257ddbd407b2ea07055)) should fix the issue, and this can be closed.

Thanks a lot for fixing this!

**Comment by aiuto** [comment]
Closing on the presumption that this really is fixed, as stated in the last comment.
