### ISSUE TITLE
Build Bazel from source 3.7.2 in alpine 3.12.7, but with error locating and symbol not found

### ISSUE THREAD

**Issue by r03942139** [bazelbuild/bazel#13658]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Symbol errors when building Bazel from source in the alpine platform. 

### Feature requests: what underlying problem are you trying to solve with this feature?

Run Bazel to build a Bazel binary, choosing Bazel-3.7.2 is because the other project opentelemetry-cpp use this Bazel revision.
https://github.com/open-telemetry/opentelemetry-cpp.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Platform: alpine:3.12.7
bazel-3.7.2-dist.zip is already downloaded
 === In Dockerfile ===
ENV JAVA_HOME='/usr/lib/jvm/default-jvm' 
RUN apk add openjdk8 build-base alpine-sdk python3 zip unzip \
 && ln -sf python3 /usr/bin/python
COPY ["./bazel-3.7.2-dist", "/bazel-src"]
RUN chmod +x bazel-src \
 && cd bazel-src \
 && env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh \
 && cp output/bazel /usr/local/bin/bazel
RUN cd bazel-src && bazel info release
RUN cd bazel-src && output/bazel build //src:bazel-dev

### What operating system are you running Bazel on?

Platform: alpine:3.12.7

### What's the output of `bazel info release`?

release 3.7.2- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

release 3.7.2- (@non-git)

Followed the official guide: https://docs.bazel.build/versions/main/install-compile-source.html#bootstrap-unix-prereq
- Build Bazel from scratch (bootstrapping)
1. Download bazel-3.7.2-dist.zip, then unzip and rename as bazel-src
2. apk add openjdk11 build-base alpine-sdk python3 zip unzip
3. cd bazel-src
4. env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh
5. cp output/bazel /usr/local/bin/bazel
6. bazel build //src:bazel-dev

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git

###  Have you found anything relevant by searching the web?

https://github.com/tensorflow/tensorflow/issues/25078
This post mentioned that it looked like an alpine/musl issue: https://bugs.freedesktop.org/show_bug.cgi?id=35268
Getting rid of STATIC_TLS is the current workaround.
But no idea how to get rid of STATIC_TLS in Bazel.

### Any other information, logs, or outputs that you want to share?

**RUN which bazel && bazel version**
/usr/local/bin/bazel
Extracting Bazel installation...
Build label: 3.7.2- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 9 04:15:01 2021 (1625804101)
Build timestamp: 1625804101
Build timestamp as int: 1625804101

**RUN cd bazel-src  && output/bazel build //src:bazel-dev**
DEBUG: /root/.cache/bazel/_bazel_root/5e0196bc67862fb292e381663934bf9f/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /root/.cache/bazel/_bazel_root/5e0196bc67862fb292e381663934bf9f/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True 
DEBUG: /root/.cache/bazel/_bazel_root/5e0196bc67862fb292e381663934bf9f/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /root/.cache/bazel/_bazel_root/5e0196bc67862fb292e381663934bf9f/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True 

......
[911 / 960] Executing genrule //src:embedded_tools_jdk_allmodules; 13s processwrapper-sandbox ... (8 actions, 7 running)
INFO: From Generating Java (Immutable) proto_library @googleapis//:google_devtools_build_v1_build_events_proto:
google/devtools/build/v1/build_events.proto:20:1: warning: Import google/api/annotations.proto is unused.
INFO: From Generating Java (Immutable) proto_library @googleapis//:google_api_auth_proto:
google/api/auth.proto:19:1: warning: Import google/api/annotations.proto is unused.
INFO: From Generating Java (Immutable) proto_library @googleapis//:google_bytestream_bytestream_proto:
google/bytestream/bytestream.proto:19:1: warning: Import google/api/annotations.proto is unused.
INFO: From Generating Java (Immutable) proto_library @googleapis//:google_devtools_build_v1_build_status_proto:
google/devtools/build/v1/build_status.proto:20:1: warning: Import google/api/annotations.proto is unused.
INFO: From Generating Java (Immutable) proto_library //src/main/protobuf:execution_statistics_proto:
[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/compiler/java/java_file.cc:247] The optimize_for = LITE_RUNTIME option is no longer supported by protobuf Java code generator and is ignored--protoc will always generate full runtime code for Java. To use Java Lite runtime, users should use the Java Lite plugin instead. See:
  https://github.com/protocolbuffers/protobuf/blob/master/java/lite.md
ERROR: /root/.cache/bazel/_bazel_root/5e0196bc67862fb292e381663934bf9f/external/bazel_tools/tools/jdk/BUILD:350:14: Action external/bazel_tools/tools/jdk/platformclasspath_classes/DumpPlatformClassPath.class failed (Exit 127): javac failed: error executing command external/remotejdk11_linux/bin/javac -source 8 -target 8 -Xlint:-options -cp external/remotejdk11_linux/lib/tools.jar -d ... (remaining 2 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox javac failed: error executing command external/remotejdk11_linux/bin/javac -source 8 -target 8 -Xlint:-options -cp external/remotejdk11_linux/lib/tools.jar -d ... (remaining 2 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Error relocating /root/.cache/bazel/_bazel_root/5e0196bc67862fb292e381663934bf9f/external/remotejdk11_linux/bin/../lib/jli/libjli.so: __strdup: symbol not found
Error relocating /root/.cache/bazel/_bazel_root/5e0196bc67862fb292e381663934bf9f/external/remotejdk11_linux/bin/../lib/jli/libjli.so: __rawmemchr: symbol not found
Target //src:bazel-dev failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 423.273s, Critical Path: 30.83s
INFO: 1086 processes: 135 internal, 1 local, 950 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by philwo** [comment]
Hi @r03942139,

it looks like Bazel is trying to run binaries from its default JDK ("remotejdk11_linux") which is linked against glibc, thus doesn't run under Alpine. Unfortunately I don't know how to fix this, but because Bazel 3.x will no longer receive fixes, there isn't really a "bug" here that we can fix. It's possible that you might get this working with just adding a flag that tells Bazel to use the correct JDK. Would you mind asking on the [bazel-discuss@ mailing list ](https://groups.google.com/g/bazel-discuss)? I think other users will probably have encountered this before and might be able to help you out!

Thanks,
Philipp
