### ISSUE TITLE
sandbox path leaked into llvm coverage output

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/bazel#13668]
### Description of the problem / feature request:

When generating source-based coverage, llvm embeds absolute paths to the output file. Which causes non-reproducible builds, and may potentially poisoning the cache.

Although the same issue has been [addressed](https://github.com/bazelbuild/bazel/commit/e794ee695819660af67599308bffb489eb6abf22) for debugging, weirdly enough, LLVM uses a different flag `-fprofile-prefix-map` for coverage. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/bazelbuild/bazel/blob/7bc0199c37e2999fbcbbf8359cb9ddca74458cf3/tools/osx/crosstool/cc_toolchain_config.bzl#L1810-L1840

### What operating system are you running Bazel on?

macOS 11.4

### What's the output of `bazel info release`?

4.1

### Any other information, logs, or outputs that you want to share?

As pointed out in https://reviews.llvm.org/D83154?id=275480 and https://reproducible-builds.org/docs/build-path/, we should probably use `-ffile-prefix-map` to fix all these abs path leaking issues once for all.

**Comment by keith** [comment]
I agree using file-prefix-map is probably the best path forward here. Iirc I considered this change in the past but didn't make it because of old clang version support.

Also note profile-prefix-map was renamed to coverage-prefix-map in a later diff
