### ISSUE TITLE
Bazel Deps not linking on `cc_library` but links on `cc_binary`

### ISSUE THREAD

**Issue by yaadhavraajagility** [bazelbuild/bazel#13665]
I am attempting to include a library called pytorch in my project

```
cc_library(
    name = "torch_cpu",
    srcs = [
        "lib/libtorch.so",
        "lib/libtorch_cpu.so",
        "lib/libc10.so",
        "lib/libcaffe2_detectron_ops.so",
    ],
    #srcs = glob(["lib/*.so"]),
    linkopts = [
        "-ltorch",
        "-ltorch_cpu",
        "-lcaffe2_detectron_ops",
        "-lc10",
    ],
    hdrs = glob(["include/**/*.h"]),
    includes = [
        "include",
        "include/torch/csrc/api/include",
        "include/THC",
        "include/TH",
    ],
    copts = ["-D_GLIBCXX_USE_CXX11_ABI=0"],
    visibility = ["//visibility:public"]
)
```

When I am building a binary as such:
```
cc_binary(
    name = "bin",
    srcs = ["bin.cpp"],
    linkshared = True,
    deps = [
        "@libtorch//:torch_cpu",
    ],
)
```
It generates a `libbin.so` and i see libtorch is linked when i do ldd on it
```
 ldd bazel-bin/libbin.so
	linux-vdso.so.1 (0x00007fff84792000)
	libtorch.so => /home/raaj/.cache/bazel/_bazel_raaj/be6e4ec0d0de66f5dc2830250d02e4c6/external/pytorch_cpu/libtorch/lib/libtorch.so (0x00007fd987bcc000)
...
```

But when i am build a library:

```
cc_library(
    name = "lib",
    srcs = ["lib.cpp"],
    hdrs = ["lib.hpp"],
    deps = [
        "@libtorch//:torch_cpu",
    ],
)
```

It generates a `liblib.so` and i do not see it linked

```
 ldd bazel-bin/liblib.so
	linux-vdso.so.1 (0x00007ffe5e887000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2715b4d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f27157af000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2715597000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f27151a6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2715f5a000)
```

Why is this?

**Comment by erenon** [comment]
Bazel does not link libraries to libraries - it postpones linking to the point when the final cc_binary is linked. This can reduce the number of times a library need to be linked (e.g: when `A -> [B,C] -> D`), and this allows the binary to select the type of linkage (static/dynamic).

**Comment by oquenchil** [comment]
What erenon says is correct, one more detail is that the shared libraries created by cc_libraries are not really proper shared libraries that have their dependencies linked in. They are mostly created for faster development for dynamic linking in cc_tests so that when you change a file that is part of a target not everything has to be relinked.

For proper shared libraries use a cc_binary or the experimental [cc_shared_library](https://github.com/bazelbuild/rules_cc/blob/main/examples/test_cc_shared_library/BUILD)
