### ISSUE TITLE
test_filter doesn't work for Python

### ISSUE THREAD

**Issue by haifeng-jin** [bazelbuild/bazel#13664]
### Description of the problem / feature request:

> test_filter doesn't filter out any test, it always runs all the tests in the test file.
> However, it works in blaze.
> I tried to run the exact same command in bazel and blaze. It works in blaze but not in bazel.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> It should be reproducible with any Python project using bazel.
> I was running tests for https://github.com/keras-team/keras/
> The command I use is
```
bazel test keras:backend_test --test_filter=BackendCrossEntropyLossesTest.test_binary_crossentropy_from_logits_no_warnings_test_mode_eager --test_sharding_strategy=disabled
```
> To see if it runs other tests in the file, you can just add `assert False` to any other test that not suppose to run, and see if it fails or not.

### What operating system are you running Bazel on?

> Docker python3.9

### What's the output of `bazel info release`?

> 
```
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=149
INFO: Reading rc options for 'info' from /workspaces/keras/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --define open_source_build=true --define=use_fast_cpp_protos=false --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --config=short_logs --config=v2
INFO: Found applicable config definition build:short_logs in file /workspaces/keras/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /workspaces/keras/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
release 4.1.0
```
### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
git@github.com:haifeng-jin/keras.git
1b9f7e5da8a49882c560b1aaf67d1a77782080d6
1b9f7e5da8a49882c560b1aaf67d1a77782080d6
```

**Comment by haifeng-jin** [comment]
Feel free to setup a meeting. I can give a demo of the problem.

**Comment by oquenchil** [comment]
Whether that works depends on the runner/framework. It could be possible that the internal and external Python rules don't use the same runner. Perhaps someone with knowledge of Python rules can clarify.

**Comment by haifeng-jin** [comment]
It is using `tf.test.TestCase`, which is a subclass of `googletest.TestCase`.

**Comment by comius** [comment]
cc @gpshead @rickeylev @brandjon

**Comment by bhack** [comment]
@haifeng-jin [Are we using instead `absltest_main`](https://github.com/tensorflow/tensorflow/blob/1b0947a3fd956256d2dd5414d6c2d9f27440df44/tensorflow/python/platform/googletest.py#L52-L55)?

So, Is this under the hood https://github.com/abseil/abseil-py/issues/128 ?

**Comment by comius** [comment]
assigned for triaging

**Comment by haifeng-jin** [comment]
As suggested in keras-team/keras#15338, test_arg works for our case.
So this issue can be closed, unless we just want to support test_filter.

**Comment by bhack** [comment]
@haifeng-jin I think instead that this ticket it Is useful, if It Is not in the abseil mentioned perimeter.
Often you need to use wildcards as you don't know the test extended name and so you need to use filter

**Comment by haifeng-jin** [comment]
@bhack I think that is based on the fact that test_filter support regular expressions.
However, test_filter only support regex for some language like C++ and Java, but not Python.

**Comment by bhack** [comment]
@haifeng-jin Test filter was resolved  https://github.com/abseil/abseil-py/issues/173#event-5339072920. Supporting glob is https://github.com/abseil/abseil-py/issues/128

**Comment by haifeng-jin** [comment]
Thanks for the update!
