### ISSUE TITLE
--bazelrc=/dev/null does not seem to work

### ISSUE THREAD

**Issue by ljusten** [bazelbuild/bazel#13673]
### Description of the problem / feature request:

Despite passing --bazelrc=/dev/null, Bazel still reads configuration from bazelrc files.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- Have a git repo with a .bazelrc file in the root directory.
- Run bazel --bazelrc=/dev/null test --announce_rc <some_test_target>
-  I'm seeing this log despite --bazelrc=/dev/null:

INFO: Reading rc options for 'test' from <path_to_my_repo>\.bazelrc:
  Inherited 'build' options: <some options defined in the bazelrc file>

### What operating system are you running Bazel on?

Windows 10. Also verified on Linux.

### What's the output of `bazel info release`?

INFO: Invocation ID: e86ea335-f61f-4bf0-9c42-c281415fb85c
release 3.4.1

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

sso://team/yeti/yeti
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
master
fcd3cb4ce20350f1286c4528b56fe04057290762

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

-

**Comment by michajlo** [comment]
There are a lot of knobs for rc files. `--bazelrc` is for user-specified rc files, and `--bazelrc=/dev/null` is a way of saying "ignore any other _user-supplied_ bazelrcs". I think what you're looking for is `--noworkspace_rc`, and possibly the others in https://docs.bazel.build/versions/main/guide.html#where-are-the-bazelrc-files.

**Comment by ljusten** [comment]
Was just typing exactly that. Thanks for the quick response! Closing.
