### ISSUE TITLE
SkyQuery hangs: concurrency design deficiencies lead to thread pool exhaustion, priority inversion

### ISSUE THREAD

**Issue by michaeledgar** [bazelbuild/bazel#13682]
### Description of the problem / feature request:

Queries using [SkyQuery](https://docs.bazel.build/versions/main/query.html#sky-query) may hang the Bazel server due to design deficiencies in the parallel query engine used by SkyQuery. This query engine's threading model uses fixed-size shared thread pools, which can lead to priority inversion. It will also use one blocking task for each function that does parallel graph traversal, which can lead to thread exhaustion. This is referenced as a necessary cleanup [in this TODO](https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/main/java/com/google/devtools/build/lib/query2/ParallelVisitorUtils.java#L77-L79).

Issue #13359 is an example of this issue, as is [a recent comment on issue #906 (but not issue #906 in general)](https://github.com/bazelbuild/bazel/issues/906#issuecomment-873320707).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

To observe threadpool exhaustion, fork https://github.com/BenHenning/demo-bazel-query-issue and run the sole Github Action workflow.

### What operating system are you running Bazel on?

This impacts all operating systems.

### What's the output of `bazel info release`?

4.1.0

**Comment by michaeledgar** [comment]
If you are experiencing hangs while using SkyQuery, the recommended workaround is to rewrite your query to avoid running functions in parallel. For example, in #13359, the user's original query was:

```
(siblings(rbuildfiles($build_files_with_commas)))
  union (allrdeps(set(${changed_files[@]})))
  union (allrdeps(siblings(rbuildfiles($build_files_with_commas))))
```

This query occasionally hung because of a priority inversion between the `siblings()` and `rbuildfiles()` functions. This can be rewritten as follows to force one function to evaluate before the next proceeds, guaranteeing the correct priority at the expense of throughput:

```
let rb = rbuildfiles($build_files_with_commas) in
  let sib = siblings($rb) in
    $sib + allrdeps($sib + set(${changed_files[@]}))
```

**Comment by BenHenning** [comment]
Thanks for filing this @michaeledgar & your additional context in https://github.com/bazelbuild/bazel/issues/13359#issuecomment-879930714. We recently migrated the script that performed this query to Kotlin, and our mitigation was essentially exactly your recommendation: we split up the query into multiple queries: https://github.com/oppia/oppia-android/pull/3416/files#diff-1e798d9f6f6e6059ff0d747cc961c02e0ba9bf4bf588dfe9db710be512d0c63dR58. So far, this has been working great in CI/GitHub Actions.

**Comment by fmeum** [comment]
@bazelbuild/triage Still relevant, especially for search
