### ISSUE TITLE
Rolling Release: Bazel coverage failed for buildifier_test and container_test

### ISSUE THREAD

**Issue by sluongng** [bazelbuild/bazel#13690]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Rolling release `bazel 5.0.0-pre.20210623.2` is breaking our `bazel coverage //...` runs because the test rules like `buildifier_test` (https://github.com/bazelbuild/buildtools/blob/master/buildifier/def.bzl#L12) and `container_test` (https://github.com/bazelbuild/rules_docker/blob/master/contrib/test.bzl#L125) does not provide coverage.dat

### Feature requests: what underlying problem are you trying to solve with this feature?

N/A

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
# Sample failing build target
load("@com_github_bazelbuild_buildtools//buildifier:def.bzl", "buildifier_test")

buildifier_test(
    name = "check_starlark_format",
    srcs = ["//:starlark_files"],
    lint_mode = "warn",
    mode = "diff",
)

filegroup(
    name = "starlark_files",
    srcs = glob(
        [
            "**/*.BUILD",
            "**/*.bzl",
            "**/*.sky",
            "**/BUILD",
            "**/BUILD.*.bazel",
            "**/BUILD.*.oss",
            "**/BUILD.bazel",
            "**/WORKSPACE",
            "**/WORKSPACE.*.bazel",
            "**/WORKSPACE.*.oss",
            "**/WORKSPACE.bazel",
            "*.BUILD",
            "*.bzl",
            "*.sky",
            "BUILD.*.bazel",
            "BUILD.*.oss",
            "WORKSPACE.*.bazel",
            "WORKSPACE.*.oss",
        ],
        exclude = [
            "bazel-*/**",
            ".git/**",
        ],
    ),
)
```

```
# .bazeliskrc
USE_BAZEL_VERSION=rolling
```

```
# sample error

ERROR: /home/sluongng/my/repo/BUILD.bazel:32:16: output 'check_starlark_format/coverage.dat' was not created
ERROR: /home/sluongng/my/repo/BUILD.bazel:32:16: Testing //:check_starlark_format failed: not all outputs were created or valid
```

Then run `bazel coverage //...`

### What operating system are you running Bazel on?

Linux CentOS7

### What's the output of `bazel info release`?

```
bazel info release
INFO: Invocation ID: 00b41c4e-ddef-4150-aae5-d1b9fa02bd02
release 5.0.0-pre.20210623.2
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

Tried rolling back to LTS version and it was working ok

```
--- a/.bazeliskrc
+++ b/.bazeliskrc
@@ -1,2 +1,2 @@
+USE_BAZEL_VERSION=4.1.0
-USE_BAZEL_VERSION=rolling
```

### Any other information, logs, or outputs that you want to share?

First reported in https://github.com/bazelbuild/bazel/issues/13505#issuecomment-881252946

**Comment by meisterT** [comment]
cc @comius @c-mita

**Comment by fweikert** [comment]
FYI, I just pushed https://github.com/bazelbuild/bazel/releases/tag/5.0.0-pre.20210708.4. Can you please check whether the problem still persists in this release? I cannot repro myself since I don't know which version of com_github_bazelbuild_buildtools you're using.

**Comment by sluongng** [comment]
Yeah, I got the same issue with your latest version

```
% bazel info release
INFO: Invocation ID: e5cc240e-27ee-4b8c-a6fa-0303c1ae3b84
release 5.0.0-pre.20210708.4
```

```
http_archive(
    name = "com_github_bazelbuild_buildtools",
    sha256 = "932160d5694e688cb7a05ac38efba4b9a90470c75f39716d85fb1d2f95eec96d",
    strip_prefix = "buildtools-4.0.1",
    urls = [
        "https://github.com/bazelbuild/buildtools/archive/4.0.1.zip",
    ],
)
```

I don't think the issue is isolated to `buildtools` as container_test rule on `rules_docker` is also facing similar issue.

There must be something changed in coverage collection that demand a test rule to emit coverage data even though it does not have any.

**Comment by sluongng** [comment]
Close this since i no longer have access to the repo
