### ISSUE TITLE
libstdc++ depends on libm

### ISSUE THREAD

**Issue by hermione521** [bazelbuild/bazel#1370]
Mentioned by Douglas:

I'm getting link errors when trying to build a static C++ binary using bazel.  I've created a minimal test case at ...  It's a simple hello world that happens to pull in the part of libstdc++ that depends on libm.  Compiling shared works (since the .so includes the reference to libm), compiling static breaks:

$ bazel run :test-shared  
INFO: Found 1 target...
Target //:test-shared up-to-date:
  bazel-bin/test-shared
INFO: Elapsed time: 0.580s, Critical Path: 0.24s

INFO: Running command line: bazel-bin/test-shared
Yo

$ bazel run :test-static
INFO: Found 1 target...
INFO: From Linking test-static:
/usr/lib/gcc/x86_64-linux-gnu/4.8/libstdc++.a(hashtable_c++0x.o): In function `std::__detail::_Prime_rehash_policy::_M_next_bkt(unsigned long) const':
(.text._ZNKSt8__detail20_Prime_rehash_policy11_M_next_bktEm+0x69): undefined reference to`ceil'
/usr/lib/gcc/x86_64-linux-gnu/4.8/libstdc++.a(hashtable_c++0x.o): In function `std::__detail::_Prime_rehash_policy::_M_next_bkt(unsigned long) const':
(.text._ZNKSt8__detail20_Prime_rehash_policy11_M_next_bktEm+0xf3): undefined reference to`ceil'
/usr/lib/gcc/x86_64-linux-gnu/4.8/libstdc++.a(hashtable_c++0x.o): In function `std::__detail::_Prime_rehash_policy::_M_need_rehash(unsigned long, unsigned long, unsigned long) const':
(.text._ZNKSt8__detail20_Prime_rehash_policy14_M_need_rehashEmmm+0x6f): undefined reference to`floor'
/usr/lib/gcc/x86_64-linux-gnu/4.8/libstdc++.a(hashtable_c++0x.o): In function `std::__detail::_Prime_rehash_policy::_M_need_rehash(unsigned long, unsigned long, unsigned long) const':
(.text._ZNKSt8__detail20_Prime_rehash_policy14_M_need_rehashEmmm+0xc7): undefined reference to`floor'
collect2: error: ld returned 1 exit status
ERROR: .../snippets/bazel-cpp-static/BUILD:1:1: Linking of rule '//:test-static' failed: gcc failed: error executing command /usr/bin/gcc -o bazel-out/local_linux-fastbuild/bin/test-static -static -B/usr/bin/ -Wl,-z,relro,-z,now -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,-S ... (remaining 1 argument(s) skipped).
Target //:test-static failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.430s, Critical Path: 0.13s
ERROR: Build failed. Not running target.

**Comment by mhlopko** [comment]
Obsolete, bazel's crosstool already emits -lstdc++ and -l.
