### ISSUE TITLE
Worker implementations have no control over where --worker_extra_flag values are put

### ISSUE THREAD

**Issue by larsrc-google** [bazelbuild/bazel#13710]
The `--worker_extra_flag` option provides a way to adjust how workers behave at runtime. However, they are always put at the end of the command line, after `--persistent_worker`. For the Javac worker, this is not very useful, as the worker itself doesn't take any extra flags, but passing flags to the JVM, i.e. before the jar file, would allow tweaking memory settings, attaching debuggers, etc. 

One possible approach would be to have a magic flag-file argument `@extraArgs` that the WorkerSpawnRunner understands and replaces with the extra flags if found. However, this flag-file would not exist for other strategies, and special-casing it everywhere else would be hacky.

**Comment by alexjski** [comment]
I have an alternative design in mind where we would enhance the `Args` to allow something like this:

```
args = ctx.actions.args()
args.add("--argument1")
args.add("--persistent_argument", restriction=WORKER_ONLY)
args.add("--regular_argument", restriction=REGULAR_ONLY)
args.add("--argument2")

ctx.actions.run(bin=bin, arguments=[args], ...)
```

In this case, regular invocation of the action would be `bin --argument1 --regular_argument --argument2 @param1 @param2...` and as persistent worker it would be `bin --argument1 --persistent_argument --argument2 --persistent_worker`.

The virtue of this is that it would allow for not duplicating the computation of the action key--we would basically compute the command line by adding all arguments for the sake of action key computation (with some extra fuzzing to avoid clashing).

This probably is worth writing down a proposal doc which I am planning to do. For now, I am going to experiment with JavaBuilder alone and see how good we can make it as a first step before we commit to a new public API.
