### ISSUE TITLE
Unable to install bazel 2.1.0 via spack

### ISSUE THREAD

**Issue by adamjstewart** [bazelbuild/bazel#13720]
### Description of the problem:

I'm unable to install bazel 2.1.0. I'm using OpenJDK 11.0.11:
```console
$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```console
$ git clone https://github.com/spack/spack.git
$ . spack/share/spack/setup-env.sh
$ spack install bazel@2.1.0
```

### What operating system are you running Bazel on?

Ubuntu 18.04

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Here are the appropriate build logs:

[spack-build-out.txt](https://github.com/bazelbuild/bazel/files/6849021/spack-build-out.txt)
[spack-build-env.txt](https://github.com/bazelbuild/bazel/files/6849022/spack-build-env.txt)

**Comment by meisterT** [comment]
Is there a reason why you need that old bazel version? Have you considered using bazelisk?

I don't know how spack works, how does it know what to build?

**Comment by adamjstewart** [comment]
> Is there a reason why you need that old bazel version?

I'm trying to build `tensorboard-plugin-wit` and others have reported that it doesn't work with newer bazel. I just tried again with bazel 4.0 and the installation crashes with a bunch of obscure warnings about regexes.

> Have you considered using bazelisk?

Never heard of it.

> I don't know how spack works, how does it know what to build?

Spack works just like any other package manager, it has a build recipe that explains how to compile it. See https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/bazel/package.py

**Comment by meisterT** [comment]
> > Is there a reason why you need that old bazel version?
> 
> I'm trying to build `tensorboard-plugin-wit` and others have reported that it doesn't work with newer bazel. I just tried again with bazel 4.0 and the installation crashes with a bunch of obscure warnings about regexes.

tensorflow seems to prefer 3.7.2 these days: https://github.com/tensorflow/tensorflow/blob/master/.bazelversion
 
> > Have you considered using bazelisk?
> 
> Never heard of it.

https://github.com/bazelbuild/bazelisk is our recommended way to use older/selected bazel versions.

Bazelisk understands the above `.bazelversion` file and will just install and run the right bazel version.
 
> > I don't know how spack works, how does it know what to build?
> 
> Spack works just like any other package manager, it has a build recipe that explains how to compile it. See https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/bazel/package.py

I assume it's then a problem in their recipe not with Bazel itself.

**Comment by sventiffe** [comment]
If you need to use 2.1.0 please use one of the installers/binaries from our site.
https://github.com/bazelbuild/bazel/releases/tag/2.1.0
