### ISSUE TITLE
Bazel Memory Tracker is broken

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#13726]
### Description of the problem / feature request:

Per [docummentation](https://docs.bazel.build/versions/main/skylark/performance.html#enabling-memory-tracking) Bazel allows to instrument memory allocations. This feature seems to be broken.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

[Here](https://github.com/Bazel-snippets/bazel_memory_tracker) is my repro repository. It only contains empty WORKSPACE file, .bazerc file with the two flags necessary to enable memory tracking and allocation_instrumenter.jar copied from the Bazel source tree. Command to run is `bazel info`. Seems any command would do. After running the command check the Java log in the output folder. I observe the log to grow by 4 Mb and get full of ```210721 14:12:43.187:WT 1 [com.google.monitoring.runtime.instrumentation.AllocationInstrumenter.instrument] Failed to instrument class.
java.lang.IllegalArgumentException```

### What operating system are you running Bazel on?

Windows, Mac, Linux

### What's the output of `bazel info release`?

4.1.0, 4.2.0rc1

**Comment by katre** [comment]
@meisterT: Can you triage this and let me know if it's a release blocker for 4.2.0?

**Comment by meisterT** [comment]
This is apparently broken for a long time, so technically not a release blocker. Updating the version of the tracker library seems to help (the old version stopped working with JDK11).
