### ISSUE TITLE
Formatting error on http://www.bazel.io/roadmap.html

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#1373]
http://www.bazel.io/roadmap.html has a formatting error on its table.

![image](https://cloud.githubusercontent.com/assets/96150/15973178/d4c6082c-2ef6-11e6-9716-a10c87aaa92a.png)

**Comment by damienmg** [comment]
Known issue fix already on his way :)

**Comment by damienmg** [comment]
The fix is 0c083ecd8e38d9d5430e1d0882dabdaaa3e6e66b. ci.bazel.io is rebuilding everything so we should wait until the website is pushed.
