### ISSUE TITLE
"not included in runfiles" error on false targets clash

### ISSUE THREAD

**Issue by dmivankov** [bazelbuild/bazel#13746]
### Description of the problem / feature request:

External repository files can clash with rule outputs and produce "main program File.... not included in runfiles" errors.
Doesn't seem to happen with rule-generated external targets.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

A/WORKSPACE: empty file
A/foo: empty file
A/bar/foo: empty file
A/BUILD:
```python
exports_files(["foo"])
```
A/bar/BUILD:
```python
exports_files(["foo"])
```
B/WORKSPACE:
```python
local_repository(
  name = "A",
  path = "../A",
)
```
B/bar/BUILD:
```python
load("//:rule.bzl", "myrule")

myrule(
  name = "foo",
  something = "@A//bar:foo",
)
```
B/rule.bzl:
```python
def _myrule(ctx):
  ctx.actions.write(
      output = ctx.outputs.executable,
      content = "#!/bin/sh\necho myrule ",
  )
  runfiles = ctx.runfiles(
      files = [ctx.outputs.executable, ctx.executable.something],
      collect_data = True,
  )
  return [DefaultInfo(
      executable = ctx.outputs.executable,
      runfiles = runfiles,
  )]
  

myrule = rule(
  attrs = { "something": attr.label(
    cfg = "exec", 
    executable = True, 
    allow_single_file = True,
  ) },
  executable = True,
  implementation = _myrule,
)
```

```sh
$ cd B
$ bazel run //bar:foo
ERROR: ..B/bar/BUILD:3:7: in myrule rule //bar:foo:
..B/rule.bzl:10:22: main program File:[[<execution_root>]bazel-out/k8-fastbuild/bin]bar/foo not included in runfiles
ERROR: Analysis of target '//bar:foo' failed; build aborted: Analysis of target '//bar:foo' failed
```
various changes that each make error go away
- replacing `@A//bar:foo` with `@A//:foo` in B/bar/BUILD
- replacing `name = "foo"` with `name = "not-foo"` in B/bar/BUILD
- removing `ctx.executable.something` from runfiles in B/rule.bzl

### What operating system are you running Bazel on?

NixOS

### What's the output of `bazel info release`?

release 4.1.0- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

NixPkgs

### Any other information, logs, or outputs that you want to share?

`local_repository` could also be `http_archive` containing file `bar/foo` or `foo` with same error

error message location https://github.com/bazelbuild/bazel/blob/4.1.0/src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleConfiguredTargetUtil.java#L648
map that gets conflicts https://github.com/bazelbuild/bazel/blob/4.1.0/src/main/java/com/google/devtools/build/lib/analysis/Runfiles.java#L537
various path flavors https://github.com/bazelbuild/bazel/blob/4.1.0/src/main/java/com/google/devtools/build/lib/actions/Artifact.java

**Comment by aiuto** [comment]
Using short_path doesn't seem right. 
If you want to write a file that will successfully point to an input Label, you probably need .path.

**Comment by dmivankov** [comment]
short_path part is just for debugging purposes, can be safely removed from example

**Comment by dmivankov** [comment]
removed it now
