### ISSUE TITLE
Constrain a target to specific constraint values

### ISSUE THREAD

**Issue by mbinna** [bazelbuild/bazel#13740]
### Description of the feature request:

This feature request is about a potential new attribute `constrain_to`. The concept is a generalization of [`testonly`](https://docs.bazel.build/versions/main/be/common-definitions.html#common.testonly). `constrain_to` constrains a target to one or more `constraint_value`s. Those constraints propagate virally through the dependency tree.

A good example to demonstrates how this feature should work is the [Automotive Safety Integrity Level](https://en.wikipedia.org/wiki/Automotive_Safety_Integrity_Level) (ASIL) that imposes certain restrictions on the code and has an ordering such that QM < ASIL A < ASIL B < ASIL C < ASIL D, and A < B means that A has a lower integrity than B.

```starlark
# file asil/BUILD

constraint_setting(name = "asil")

constraint_value(
    name = "qm",
    constraint_setting = ":asil",
)

constraint_value(
    name = "a",
    constraint_setting = ":asil",
)

constraint_value(
    name = "b",
    constraint_setting = ":asil",
)

constraint_value(
    name = "c",
    constraint_setting = ":asil",
)

constraint_value(
    name = "d",
    constraint_setting = ":asil",
)

# The order of the values is significant. A target constrained to ASIL B can
# depend on targets constrained to ASIL B, ASIL C, and ASIL D, but not on
# targets constrained to QM and ASIL A.
constraint_order(
    order = [
        ":qm",
        ":a",
        ":b",
        ":c",
        ":d",
    ],
)
```

`constraint_order` establishes a total ordering for the `constraint_value`s of a `constraint_setting`. This rule is useful when the `constraint_value`s aren't independent of each other, but instead relate to each other and the relationship has an inherent ordering.

```starlark
# file example/BUILD

# QM library can depend on all libraries, because it is unconstrained.
cc_library(
    name = "qm",
    srcs = ["qm.cc"],
    hdrs = ["qm.h"],
    deps = [
        ":b",
        ":d",
    ],
)

# ASIL B library con only depend on ASIL B, ASIL C, and ASIL D libraries.
cc_library(
    name = "b",
    srcs = ["b.cc"],
    hdrs = ["b.h"],
    constrain_to = ["//asil:b"],
    deps = [":d"],
)

cc_library(
    name = "d",
    srcs = ["d.cc"],
    hdrs = ["d.h"],
    constrain_to = ["//asil:d"],
)

# QM binary can depend on all libraries, because it is unconstrained.
cc_binary(
    name = "qm_app",
    srcs = ["qm_app.cc"],
    deps = [
        ":b",
        ":d",
        ":qm",
    ],
)

# ASIL B binary can only depend on ASIL B, ASIL C, and ASIL D libraries.
cc_binary(
    name = "b_app",
    srcs = ["b_app.cc"],
    constrain_to = ["//asil:b"],
    deps = [
        ":b",
        ":d",
    ],
)

# ASIL D binary can only depend on ASIL D libraries.
cc_library(
    name = "d_app",
    srcs = ["d_app.cc"],
    constrain_to = ["//asil:d"],
)
```

#### Use Case: Constrain Dependencies

Enforce at build time that libraries of higher integrity (e.g., [ASIL](https://en.wikipedia.org/wiki/Automotive_Safety_Integrity_Level) D) don't depend on libraries of lower integrity.

#### Use Case: Verify Constraint Compliance

Examples:

1. `bazel query` all sources of ASIL-B-constrained `cc_*` targets and check if they are compliant with this integrity level. For example, the safety manual of the C++ standard library of a vendor states that `#include <iostream>` is not allowed in ASIL B code.
1. `bazel query` ASIL-B-constrained `cc_*` targets and check if the C++ toolchain compiles them only with the expected compiler and linker flags of the compiler safety manual.

###  Have you found anything relevant by searching the web?

- https://github.com/bazelbuild/bazel/issues/10720 suggests to extend the constraints language.
- https://github.com/bazelbuild/bazel/issues/8763 could be used as an alternative to the suggested `constraint_order`. Without a constraint order, listing all valid constraint values per target would achieve a similar effect. A constraint order would be more expressive and easier to maintain from a users perspective, though.
- https://github.com/bazelbuild/bazel/issues/4923 suggests to model relationships between constraint values with a new attribute `includes`, which expresses the same thing as `constraint_order`, but might be more flexible.

### Any other information, logs, or outputs that you want to share?

Example project: see https://github.com/mbinna/bazel_constrain_to

**Comment by katre** [comment]
@aiuto, is this similar to your work with licensing?

**Comment by gregestren** [comment]
It sounds like you're already familiar with the intentionally under-documented constraints language (that adds `compatible_with` and `restricted_to` for all targets)? With that plus `fulfills`, I wonder if that already accomplishes what you're proposing?

See:

- https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/test/java/com/google/devtools/build/lib/packages/EnvironmentGroupTest.java#L40-L41
- https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/test/java/com/google/devtools/build/lib/analysis/constraints/ConstraintsTest.java#L295-L296
- https://docs.bazel.build/versions/main/be/common-definitions.html#common.compatible_with
- https://docs.bazel.build/versions/main/be/common-definitions.html#common.restricted_to

That said, our larger concerns about this kind of semantics aren't necessarily making them work, but implementing use cases that make sense and don't unnecessarily confuse rule writers.

For example, what would you like to happen if you depend on a library that you don't own, and isn't already tagged? Or if someone else depends on your libraries, which are tagged?

There's also the concern of API convergence. Would you use these `constraint_values` in other attributes, like the standard `target_compatible_with` and `exec_compatible_with`?

**Comment by aiuto** [comment]
This does sound a lot like compatible_with would do it. You would have a series of environments that encompass each other. 

To answer Greg's question about libraries that are untagged, I think the initial request requires tags all the way down, just like compatible_with.  If the restrictions are really things like "can't use <iostream>", then you need to assert that on every library.
