### ISSUE TITLE
Option --starlark_cpu_profile is completely broken on Windows

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#13748]
### Description of the problem / feature request:

[--starlark_cpu_profile](https://docs.bazel.build/versions/main/command-line-reference.html#flag--starlark_cpu_profile) command-line option crashes Bazel server on Windows.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

For absolutely any Bazel build on Windows adding `--starlark_cpu_profile=pprof.gz` to the command line causes immediate server failure: `Server terminated abruptly (error code: 2, error message: 'Stream removed', log file: 'c:\_\jjgeprbx\server\jvm.out')`
jvm.out file mentioned is absolutely empty.
I have verified the problem is present on multiple Windows machines, but does not reproduce on Mac and Linux.

### What operating system are you running Bazel on?

Windows 10 20H2

### What's the output of `bazel info release`?

4.1.0, 4.2.0rc1

**Comment by konste** [comment]
@meteorcloudy could you please take a peek as the Windows expert? It is trivial to repro and broken completely, so I hope it may be a small fix.

**Comment by meteorcloudy** [comment]
Thanks for the report! I'll look into it.
/cc @meisterT

**Comment by andrewkatson** [comment]
I got a stack trace 

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.UnsupportedOperationException: this platform does not support Starlark profiling
	at net.starlark.java.eval.CpuProfiler.start(CpuProfiler.java:131)
	at net.starlark.java.eval.Starlark.startCpuProfile(Starlark.java:963)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:367)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:231)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:547)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:611)
	at io.grpc.Context$1.run(Context.java:579)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by meteorcloudy** [comment]
Looks like this isn't a bug, but a feature request since the cpu profiler is not yet implemented on Windows.
https://cs.opensource.google/bazel/bazel/+/master:src/main/java/net/starlark/java/eval/BUILD;l=95;bpv=0

**Comment by meisterT** [comment]
I guess it still shouldn't crash hard

**Comment by meteorcloudy** [comment]
IIUC, Andrew is looking into porting cpu_profiler_posix.cc to Windows. If that doesn't work, we'll make it fail gracefully.

**Comment by konste** [comment]
@andrewkatson could you please comment for me how you got that stack trace?

**Comment by andrewkatson** [comment]
It was actually in ```jvm.out```!

**Comment by konste** [comment]
Weird! For me `jvm.out` was completely empty.

**Comment by andrewkatson** [comment]
Still working on this! Should have something to test out soon.

**Comment by andrewkatson** [comment]
Havent gotten the chance to look at this for a bit. Hoping I can do something soon
