### ISSUE TITLE
Additional "repository-private" visibility

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/bazel#1374]
It was requested that an additional visibility value be added to simplify having
a target visible to all packages in the same repository but not cross repository
boundaries. An example could be a library shared between the packages in
that repository.

@aragos and @lberki already expressed opinions wrt this proposal; moving the
discussion to the appropriate bug tracker.

**Comment by lberki** [comment]
Tl;DR: like.

**Comment by laurentlb** [comment]
As far as I see, this makes a target repository-private:
```python
    visibility = ["//:__subpackages__"],
```

**Comment by meisterT** [comment]
Laurent, if that exists, can we close this issue?
