### ISSUE TITLE
Feature Request: Support sparse-checkout to git_worker

### ISSUE THREAD

**Issue by sluongng** [bazelbuild/bazel#13747]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Recently, git.git has been adding feature to enable sparse-checkout possible.
This help reducing the amount of git-fetch data to a selected subset of trees and blob inside the repository instead of having to download all trees and blobs.

https://git-scm.com/docs/git-sparse-checkout

### Feature requests: what underlying problem are you trying to solve with this feature?

In a multi-repo setup where a small repo A running Bazel depends on components in a relatively big repo B, it's undesirable that `git_repository(B)` in A has to download the entire checkout copy of big repo B. Leveraging git-sparse-checkout command, we can limit the download of B as well as the size-on-disk of B to be minimal.

Add a `sparse_checkout_spec: List[str]` attribute in `git_repository()` rule that would enable git repositories to be fetched
with sparse-checkout enabled.

Also added a `sparse_checkout_code_mode: bool` attribute, default to `true` if `sparse_checkout_spec` is none-empty that would enable sparse checkout code mode in git. This is a sensible mode that would include all the blobs in the parent trees of a dir inside `sparse_checkout_spec`.

### Propose Implementation

In https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/git_worker.bzl `_update()` we can add an optional stage `enable_sparse_checkout()` between `add_origin()` and `fetch()` and execute the logic there.

**Comment by cameron-martin** [comment]
Maybe we instead want to use a partial clone here rather than a sparse checkout, since a sparse checkout still downloads the entire repository.

**Comment by manuelnaranjo** [comment]
FYI we introduced this feature into rules_booking in https://github.com/bookingcom/rules_booking/commit/a11099373a6f12dc058943d4c8a395528e538cfa, I don't have the time to make that into an official bazel change, but maybe someone can?
