### ISSUE TITLE
(minor) incorrect signedness fprintf params in WstringToCstring

### ISSUE THREAD

**Issue by ariccio** [bazelbuild/bazel#13759]
### Description of the problem / feature request:
In [WstringToCstring](https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/main/cpp/util/strings.cc#L363), the error path nicely prints a diagnostic before `exit`ing. :

```
  uint32_t err;
  if (!WcsToUtf8(input, &result, &err)) {
    fprintf(stderr,
            "WstringToCstring: failed with error %d (0x%08x), "
            "invalid input \"%ls\"\n",
            err, err, input.c_str());
    exit(blaze_exit_code::INTERNAL_ERROR);
  }
```
MSVC code analysis reports: `src\main\cpp\util\strings.cc(367) : warning C6340: Mismatch on sign: 'unsigned int' passed as _Param_(3) when some signed type is required in call to 'fprintf'.` 

I think you want to use a `%u` instead of a `%d`. Same thing going the other way a few lines down.

There's a whole bunch of stuff in the issue template, but honestly there's nothing fancy going on here!

**Comment by philwo** [comment]
Thank you for filing these!

**Comment by ariccio** [comment]
I was poking around bazel to prep for a job interview. I didn't get the job, but I always like poking around and finding bugs 😉🤗

You're welcome! Stay (type) safe.
