### ISSUE TITLE
Turbine: error: missing required annotation argument: <clinit>

### ISSUE THREAD

**Issue by mskonovalov** [bazelbuild/bazel#13758]
### Description of the problem / feature request:

Have a java + spring target that builds successfully but fails during Intellij sync.
```
Server.java:56: error: missing required annotation argument: <clinit>
@CrossOrigin(
^
```

I was able to checkout `turbine` and reproduce the bahavior - it works on latest master of turbine.
It seems this has been fixed in `turbine` 5 month ago https://github.com/google/turbine/commit/617a8f61b47d31f710386331b4380ba3c9c93872 but bazel still has the old version of turbine.

### What operating system are you running Bazel on?

MacOs, Linux

### What's the output of `bazel info release`?

`release 4.1.0- (@non-git)`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

from nix

###  Have you found anything relevant by searching the web?

https://stackoverflow.com/questions/45656877/crossorigin-annotation-doesnt-compile
https://github.com/google/turbine/commit/617a8f61b47d31f710386331b4380ba3c9c93872

**Comment by aiuto** [comment]
This seems like just updating the third_party dependency will fix it.

**Comment by mskonovalov** [comment]
I hope it should. What is the process around this?

**Comment by aiuto** [comment]
Someone on the bazel team has to update things in //third_party.
It has the appropriate label, so the right people should pick it up in their triage.

**Comment by cushon** [comment]
cc @comius 

The turbine fix made it into java_tools v11.2 per https://github.com/bazelbuild/bazel/issues/13144#issuecomment-793523465, this will be fixed in Bazel 4.2

**Comment by twheys** [comment]
I was running into this issue on Bazel 4.1.0. Just tried upgrading to Bazel 4.2.0 and I still have the issue. Was this maybe missed? Does anyone know if there's a work-around for the time being?

**Comment by cushon** [comment]
@comius did the java_tools update not make it into 4.2.0?

@twheys does adding this to your `WORKSPACE` to update to the latest java_tools version make a difference? https://github.com/bazelbuild/java_tools/releases/tag/java_v11.3

**Comment by twheys** [comment]
Hi @cushon - I tried adding the java_tools 11.3 rules to my WORKSPACE file and that results in some errors about missing targets. I tried running `bazel clean --expunge` to no avail. I am on Bazel 4.2.0
```
ERROR: /private/var/tmp/_bazel_theys/c47bd7bac752f67cacbe3862d74d80c0/external/bazel_tools/tools/jdk/BUILD:279:28: no such target '@remote_java_tools_darwin//:java_tools/JacocoCoverage_jarjar_deploy.jar': target 'java_tools/JacocoCoverage_jarjar_deploy.jar' not declared in package '' defined by /private/var/tmp/_bazel_theys/c47bd7bac752f67cacbe3862d74d80c0/external/remote_java_tools_darwin/BUILD and referenced by '@bazel_tools//tools/jdk:JacocoCoverageFilegroup'
```

**Comment by philwo** [comment]
FYI @comius

**Comment by comius** [comment]
Bazel 4.2.x is using the old Java resolution mechanism, so it has java_tools 10.6. (java_tools 11.x don't work with it).

Since it's a LTS, we should update old java_tools. It requires hand crafting a back-patch.

**Comment by oliviernotteghem** [comment]
4.2.0 lists [turbine fix](https://github.com/bazelbuild/bazel/commit/57672aca01b3be895382c952b550c9f8edf6c9f2) as [cherry picked](https://github.com/bazelbuild/bazel/commit/a04cb1bfad4734f801c48bae3070a799067bda4e). However, I think it was missed, as the version on 4.2.0 is not right (see below). This probably why folks are still seeing issue on 4.2.x ? cc @comius  

```
git log third_party/turbine/turbine_direct.jar
commit 1ce553e8999a838a8a8a7ef48e63465be3bfda16
Author: Liam Miller-Cushon <cushon@google.com>
Date:   Tue Feb 2 14:21:56 2021 -0800

    Update turbine

    Built at
    https://github.com/google/turbine/commit/1bbb1366145029c39bf8174de2516a0d6511a859

    Fixes https://github.com/bazelbuild/bazel/issues/12926

    Partial commit for third_party/*, see #12950.

    Signed-off-by: Philipp Wollermann <philwo@google.com>
```

**Comment by comius** [comment]
I made a new release of java_tools v10.7, https://github.com/bazelbuild/java_tools/releases/tag/javac11_v10.7.

This issue should be fixed by including http_archives mentioned in the release notes into the WORKSPACE files (without any need to do custom toolchains). That is if you're on Bazel 4.x.x.

Bazel 5.0.0 should have no such issues.
