### ISSUE TITLE
Documentation issue: sandboxfs / osxfuse sysctl missing

### ISSUE THREAD

**Issue by mhansen** [bazelbuild/bazel#13783]
Documentation URL: https://docs.bazel.build/versions/main/sandboxing.html

I tried running the suggested command for osxfuse after restarting and installing osxfuse, and got this error:

```
$ sudo sysctl -w vfs.generic.osxfuse.tunables.allow_other=1
sysctl: unknown oid 'vfs.generic.osxfuse.tunables.allow_other'
```

If I list all the sysctls I don't see any for `osxfuse`.

I'm using macFUSE 4.1.2, the latest stable from https://osxfuse.github.io/.

**Comment by rcarcasses** [comment]
it seems like instead of `osxfuse` we have to use `macfuse`:
```shell
sysctl -w vfs.generic.macfuse.tunables.allow_other=1
```

**Comment by mhansen** [comment]
The linked docs page no longer references osxfuse. So I think this is obsolete.
