### ISSUE TITLE
Builds with the local toolchain fail when it is using OpenJDK 16

### ISSUE THREAD

**Issue by mlen** [bazelbuild/bazel#13784]
### Description of the problem / feature request:

Builds with the local toolchain fail when it is using OpenJDK 16, because `UseParallelOldGC` option was deprecated in [JEP 366](http://openjdk.java.net/jeps/366) and then subsequently removed in https://hg.openjdk.java.net/jdk/jdk/rev/62a003539b0c.

It seems that this can be fixed by removing problematic option from [`default_java_toolchain.bzl`](https://cs.opensource.google/search?q=%22-XX:%2BUseParallelOldGC%22&sq=&ss=bazel) or by making it conditional on the JDK version.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ java --version
openjdk 16 2021-03-16
OpenJDK Runtime Environment (build 16+36-nixos)
OpenJDK 64-Bit Server VM (build 16+36-nixos, mixed mode, sharing)
$ touch WORKSPACE
$ touch repro.java
$ cat >BUILD <<EOF
java_library(
    name = "repro",
    srcs = ["repro.java"],
)
EOF
$ bazel build :repro
INFO: Analyzed target //:repro (1 packages loaded, 2 targets configured).
INFO: Found 1 target...
ERROR: /home/m/foo/BUILD:4:13: Building librepro.jar (1 source file) failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at /home/m/.cache/bazel/_bazel_m/ad4941ca20510a8f644f458a54fce8cf/bazel-workers/multiplex-worker-2-Javac.log ---8<---8<---
Unrecognized VM option 'UseParallelOldGC'
Did you mean '(+/-)UseParallelGC'? Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
---8<---8<--- End of log ---8<---8<---
Target //:repro failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.186s, Critical Path: 0.05s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

`release 4.1.0- (@non-git)`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

via nixpkgs

**Comment by comius** [comment]
It shouldn't be removed from older toolchain, because it affects performance.
Additional conditional could be problematic, because source and target version don't necessarily match JDK version and it could make it impossible to use JDK16 with smaller values.
I'd go by removing the offending option from default configuration and adding it back to BUILD.tools definitions of older JDKs. 

This might reduce performance for people using custom toolchains, but it should break anything.

**Comment by mlen** [comment]
Another option is to add `-XX:+IgnoreUnrecognizedVMOptions`. This should also fix the issue for jdk16

**Comment by kylecordes** [comment]
This is a frustrating situation... even with Java 15 (well behind current LTS), logs are full of:

```
INFO: From Compiling Java headers apidef/libapi_proto-speed-hjar.jar (1 source jar):
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: Ignoring option UseParallelOldGC; support was removed in 15.0
```
