### ISSUE TITLE
bazel build invalid external libary on windows

### ISSUE THREAD

**Issue by InvisibleLeVen** [bazelbuild/bazel#13781]
I try to build mediapipe on Windows system.It uses babel build system.When I installed the relevant dependencies and started to build, an error occurred during the link.

`avx512f_ukernels.lib(vrndz-avx512f-x16.obj) : error LNK2001: unresolved external symbol _cvtu32_mask16`
`....`

I thought it was a problem with the msvc compiler at first.But I wrote a deme test _cvtu32_mask16 and found that my msvc supports AVX256. It works.The error appeared in the lib of XNNPACK, so I downloaded the code of XNNPACK and compiled it with msvc, the compilation was successful.

The lib in error is avx512f_ukernels.lib.I checked the link parameters that generated it.Then use the same parameters to find the relevant obj files in the successfully compiled XNNPACK project, and then link them

It is found that the new avx512f_ukernels.lib has 2000kb. The one generated by bazel build is only a few hundred kb. After replacing it, the error disappears

I set the bazel compiler to msvc, I don’t know why the size of lib compiled by the same compiler is so different

**Comment by aiuto** [comment]
This is not a Bazel problem itself. You may have better luck finding an answer on StackOverflow.
