### ISSUE TITLE
allow genquery to be depended upon

### ISSUE THREAD

**Issue by grimreaper** [bazelbuild/bazel#13787]
### Description of the problem / feature request:

It should be possible to depend on genquery output in another rule. Specifically a test should be possible to read the output of genquery.

### Feature requests: what underlying problem are you trying to solve with this feature?

In our monorepo we have several "code structure rules" which we'd like to enforce. To understand lets look at a fairly typical layout:
```
yoda/src/main/scala/com/example/yoda
yoda/src/test/scala/com/example/yoda
harrypotter/src/main/scala/com/example/harrypotter
harrypotter/src/test/scala/com/example/harrypotter
wand/src/main/scala/com/example/wand
wand/src/tests/scala/com/example/wand
deprecated/src/main/scala/example/deprecated
```

In this example yoda and harrypotter are services and each depends on the "wand" library.

In our simplified example we'd like to ensure the following:
- yoda and harry potter can't depend on each other
- wand can't depend on either yoda or harry potter.
- anything/src/main can't depend on anything/src/tests
- only a fixed set of targets can depend on deprecated.

One way of thinking about the most general code structure rules is that we'd like to enforce constraints on the output of "bazel query". In the specific case we'd mainly looking at in/transitive dependencies. 

Lets look at how this might be handled and some of the issues
- package visibility.  - This works in reverse of the direction we want. It allows a target to restrict what depends on it, but not vice versa. It also does not handle more complex rules ("no code outside of "/sandbox/foo is allowed to depend on sandbox/foo" or ("no source code may depend on test libraries")
- external tests. This works but requires additional non-bazel tests to be run in the submit queue system. This is likely to be confusing and not easy extracted from the build graph

Note that even with this feature not all rules can be expressed since `genquery` does not support wildcards. This is resolvable either outside of bazel with a BUILD file generator by a separate feature request to permit wildcard genquery.

**Comment by benjaminp** [comment]
Is something besides putting the `genquery` rule in the `data` attribute of a test needed? E.g.,
```
genquery(
    name = "query",
    expression = "deps(//some/targets)",
    scope = "//some/targets",
)

sh_test(
   name = "test",
   srcs = ["test.sh"], # Gets "query" from runfiles.
   data = [":query"],
)
```

**Comment by grimreaper** [comment]
so I tried this and ran into issues. This may have been specific to my rules/environment though.  I'll close this and reopen if I actually found an issue
