### ISSUE TITLE
Parcel V2 sandbox issue

### ISSUE THREAD

**Issue by kohlerm** [bazelbuild/bazel#13799]
### Description of the problem / feature request:

Bazel sandbox on Linux is causing problems with parcel V2 RC

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I trying to run parcel V2 similiar to 
the example for parcel V1 at
https://github.com/bazelbuild/rules_nodejs/tree/stable/examples/parcel
replacing 
parcel.bzl

with
https://gist.github.com/kohlerm/b41c6b14f63db757341a618ed9bdb5de

(still not completely working)

it fails with 

**Error: Bad file descriptor
  Error: Bad file descriptor**

when running with the optoin

--spawn_strategy=standalone 

the message disappears. 

I suspect this is because parcel V2 is using memory mapped files for their cache see https://v2.parceljs.org/blog/rc0/

### What operating system are you running Bazel on?

Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2020.3
Codename:       kali-rolling

WSL2 on Windows 10

### What's the output of `bazel info release`?

> Replace this line with your answer.

release 3.7.2- (@non-git)

installed via nix package manager

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

```
bazel  build --subcommands bundle
INFO: Analyzed target //:bundle (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
SUBCOMMAND: # //:bundle [action 'Bundling JavaScript bundle.js [parcel]', configuration: de16027a7878784780b32c21a23af2a4b61e42de13ca1bc3615d29f2d1aacb01, execution platform: @local_config_platform//:host]
(cd /home/kohlerm/.cache/bazel/_bazel_kohlerm/bbfa98f54bdb6f11a7cff30094948c96/execroot/examples_parcel && \
  exec env - \
    BAZEL_NODE_MODULES_ROOTS='' \
    COMPILATION_MODE=fastbuild \
  bazel-out/host/bin/external/npm/parcel/bin/parcel.sh build foo.js --dist-dir bazel-out/k8-fastbuild/bin --cache-dir /tmp/cache '--bazel_node_modules_manifest=bazel-out/k8-fastbuild/bin/_bundle.module_mappings.json')
ERROR: /home/kohlerm/bazel_parcel/BUILD.bazel:4:7: Bundling JavaScript bundle.js [parcel] failed (Exit 1): parcel.sh failed: error executing command bazel-out/host/bin/external/npm/parcel/bin/parcel.sh build foo.js --dist-dir bazel-out/k8-fastbuild/bin --cache-dir /tmp/cache ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox parcel.sh failed: error executing command bazel-out/host/bin/external/npm/parcel/bin/parcel.sh build foo.js --dist-dir bazel-out/k8-fastbuild/bin --cache-dir /tmp/cache ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
**Error: Bad file descriptor
  Error: Bad file descriptor**
Building...
Bundling...
Packaging & Optimizing...
✨ Built in 783ms

bazel-out/k8-fastbuild/bin/foo.js    60 B    157ms


Target //:bundle failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.375s, Critical Path: 6.26s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully

```

**Comment by alexeagle** [comment]
You can opt-out of sandboxing in your parcel rule by requesting the "local" execution strategy
`execution_requirements = {"local": "1"}`
like
https://github.com/bazelbuild/rules_nodejs/blob/22673fcc436e207e7821a02914005e9e610d40d2/internal/pkg_npm/pkg_npm.bzl#L293
