### ISSUE TITLE
Bazel installer script fails with Syntax error: redirection unexpected'

### ISSUE THREAD

**Issue by haberman** [bazelbuild/bazel#13791]
### Description of the problem / feature request:

The Bazel installer fails with the following message:

```
++ sudo ./bazel-5.0.0-pre.20210722.2-installer-linux-x86_64.sh --prefix=/usr/local/bazel/5.0.0-pre.20210722.2
./bazel-5.0.0-pre.20210722.2-installer-linux-x86_64.sh: 1: ./bazel-5.0.0-pre.20210722.2-installer-linux-x86_64.sh: Syntax error: redirection unexpected
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`use_bazel.sh latest` in a Kokoro build.

### What operating system are you running Bazel on?

Ubuntu

I previously reported this issue in https://github.com/bazelbuild/bazel/issues/13526#issuecomment-852229300. That bug was closed, but the error is still occurring, most recently in [this Kokoro build](https://source.cloud.google.com/results/invocations/7117e2ac-f8d3-400f-8439-cfdf5c575047/targets/upb%2Fubuntu%2Fpresubmit/log)

**Comment by sgowroji** [comment]
I will close this issue now. Please reach us back if you are looking for support.
