### ISSUE TITLE
bash_completion_test fails with "set -eu" enabled

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#1379]
Commit 713a78c88ae900b3cab08460a4b1428bf19a680c enables better error checking for failures in tests caused by "set -eu" being enabled. It uncovered an issue in bash_completion_test, which fails with the following errors when errexit is enabled.

I have added a workaround that temporarily disabled errexit for the problematic part of the test, but we should remove it as soon as possible, as it looks like it's actually hiding a test failure:

FAILED: terminated because this command returned a non-zero status:
/private/var/tmp/_bazel_forgeonmac/a1cdb8eb0afd9376b92570a4d7551921/bazel.UnjQujYU/bazel-out/darwin_x86_64-fastbuild/bin/scripts/bash_completion_test.runfiles/scripts/bazel-complete.bash:350: in call to _bazel__complete_pattern
scripts/bash_completion_test:173: in call to assert_expansion_function
scripts/bash_completion_test:370: in call to test_complete_pattern
## -- Test log: -----------------------------------------------------------

test_complete_pattern FAILED: Expected 'abc ', was 'test_complete_pattern '.
scripts/bash_completion_test:173: in call to assert_expansion_function
scripts/bash_completion_test:370: in call to test_complete_pattern
FAILED: test_complete_pattern

To reproduce, please remove the "disable_errexit" statement from the test and run it:
blaze test //devtools/blaze/bazel/mac:mac_scripts_test

**Comment by meteorcloudy** [comment]
Internal ref: b/26176432

**Comment by helenalt** [comment]
@meteorcloudy is this still an issue and is P3 accurate?

**Comment by meteorcloudy** [comment]
This bug was filed originally by @philwo internally. I think it's already obsolete. I'm closing this.
