### ISSUE TITLE
Linux Sandbox Log Spam 

### ISSUE THREAD

**Issue by GMNGeoffrey** [bazelbuild/bazel#13798]
### Description of the problem / feature request:

I was trying to debug something earlier and ran my build with `--verbose_failures --sandbox_debug`. Bazel spewed out tons of logs about what the sandbox was doing. I thought that was kind of annoying, since I just wanted the sandbox repro command, as described in https://blog.bazel.build/2016/03/18/sandbox-easier-debug.html, but perhaps WAI. The logs look like this sort of thing repeated over and over for each action: https://gist.github.com/GMNGeoffrey/fc875c9858d24b857e5f0cde272404a9

Now I'm building *without* `--verbose_failures --sandbox_debug` and it's still spitting out the same log lines. I've tried:
* bazel shutdown
* bazel clean
* bazel clean --expunge
* Closing the terminal and reopening (resetting the env)
* building with `--disk_cache=""` (I have `build --disk_cache=~/.cache/bazel-disk-cache` in my ~/.bazelrc)

And the last one mysteriously worked. Now when building without that I don't get the sandbox debug messages.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have no idea. Perhaps you can suggest some things to try.

### What operating system are you running Bazel on?

Linux Debian

### What's the output of `bazel info release`?

release 4.0.0

### What's the output of `git remote get-url upstream ; git rev-parse main ; git rev-parse HEAD` ?

(note, I modified the command to get the info I'm pretty sure you actually want)

```
git@github.com:llvm/llvm-project.git
fe3ba90830f6ee84f9bb305606dec38451c4c884
fe3ba90830f6ee84f9bb305606dec38451c4c884
```

I'm currently working on a local draft to build lld and the command I was running was `bazel build @llvm-project//lld:lld`. The build is done from the utils/bazel directory.

###  Have you found anything relevant by searching the web?

No

**Comment by GMNGeoffrey** [comment]
Perhaps a further hint. I just ran a build with `--config=rbe` and then a build without again and in the build without I got the log spam again

**Comment by benjaminp** [comment]
Some flags related to execution, such as `--sandbox_debug`, are not included in the remote or local cache keys for actions. So, if you end up an action run with `--sandbox_debug` in a cache, that's what Bazel will claim as the output until the cache entry dies or the action's key change.

**Comment by GMNGeoffrey** [comment]
Hmm yeah I was beginning to suspect that this was cache poisoning. That seems bad. It's also not consistent with how other output flags like `--test_output` and `--subcommands` work. I guess those operate at a different level?

Just more generally, I didn't really want any of that sandbox debug logging in the first place. I just wanted the command it ran. I only ran with `--sandbox_debug` because the docs said I needed to in order to get the subcommand. I vaguely recall that without that the directory the command changed into no longer existed when I went to reproduce, but I was also fiddling with remote running through RBE (which made the subcommand totally unusable because it was for the RBE executor), so my recollection may be off here.

**Comment by benjaminp** [comment]
> Hmm yeah I was beginning to suspect that this was cache poisoning. That seems bad. It's also not consistent with how other output flags like `--test_output` and `--subcommands` work. I guess those operate at a different level?

IIt is actually exactly the same as how those flags work, but `--sandbox_debug` causes extra output to be emitted by the action where as `--test_output` and `-s` only affect what Bazel prints to the console.

**Comment by GMNGeoffrey** [comment]
> It is actually exactly the same as how those flags work,

I meant how they work as perceived by the user. That is, if you remove the flag Bazel stops printing the thing.

> but `--sandbox_debug` causes extra output to be emitted by the action where as `--test_output` and `-s` only affect what Bazel prints to the console.

Yeah this is what I meant by "a different level". It seems that `--sandbox_debug` is being treated like these other flags, but doesn't work the same way they do.

Also it's interesting because I remember previous complaints that if an action is cached Bazel won't replay the output (e.g. clang diagnostic warnings). Maybe this is something that was recently fixed (saving action output in the cache and replaying it) and this behavior with `--sandbox_debug` has shown up because of it?

**Comment by chrisdothtml** [comment]
Also seeing this. We've never had these debug logs before, but are experimenting with different CI machines/containers, and on the new containers, we're seeing the noisy debug logs.

I've spent the last day googling the very confusing intricacies of the different bazel flags that affect output verbosity, and am still stumped.

This issue was marked as a documentation update, but can someone from the team just tell me how to disable the logs? I'm happy to make a PR to update the docs, I just need to know how to do it

**Comment by GMNGeoffrey** [comment]
[I'm not on the Bazel team]

I think you may be seeing different logs? Can you post an example? The specific thing I'm reporting here has to do with doing a run with `--sandbox_debug` that is cached and then doing a run without `--sandbox_debug` that will replay those logs from the cache.

**Comment by chrisdothtml** [comment]
Here's an example of some of the debug logs I'm seeing during a build step on one of our targets:
```
1685558114.277624001: src/main/tools/linux-sandbox-pid1.cc:400: remount rw: /tmp
1685558114.277628236: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /tmp/[...]
1685558114.277632932: src/main/tools/linux-sandbox-pid1.cc:400: remount rw: /dev/shm
1685558114.277697303: src/main/tools/linux-sandbox-pid1.cc:491: calling fork...
1685558114.277851078: src/main/tools/linux-sandbox-pid1.cc:521: child started with PID 2
1685558127.380204577: src/main/tools/linux-sandbox-pid1.cc:538: wait returned pid=2, status=0x00
1685558127.380227996: src/main/tools/linux-sandbox-pid1.cc:556: child exited normally with code 0
1685558127.381023451: src/main/tools/linux-sandbox.cc:233: child exited normally with code 0
```

It doesn't seem to be specific to our repo or targets (other stacks in our company are getting the same thing on these new CI containers), and I ran `printenv | grep BAZEL_` to see if maybe something was in the env that was causing it, but no such luck

**Comment by GMNGeoffrey** [comment]
Are your builds using caching? Are the actions with the extra logging cached? The issue described is that `--nosandbox_debug` will work for new actions but won't affect the logs of cached actions.

**Comment by tjgq** [comment]
This is the same as https://github.com/bazelbuild/bazel/issues/16689.
