### ISSUE TITLE
Failed to find default application credential and get authentication error

### ISSUE THREAD

**Issue by coeuvre** [bazelbuild/bazel#13804]
### Description of the problem:

When building with RBE, Bazel sometimes failed to detect the default application credentials with `--google_default_credentials` and results in following authentication error:

```
ERROR: Failed to query remote execution capabilities: 400 Bad Request
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
```

Workaround:
  1. Remove `~/.config/gcloud` and re-login.
  2. Manually specify the credential file with `--google_credentials`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

No stable way to reproduce but it usually happens when setting up a new project with RBE.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

Bazel 4.1.0.

**Comment by tomrenn** [comment]
We had a report of someone on our team experiencing this issue, and using `--google_credentials` worked for them.

They can no longer reproduce the error, and I suspect it may have something to do with Bazel caching a previous or different credential file? A sufficient workaround may be to `bazel shutdown` to use the new default credentials if they have changed, but I've not tested this

**Comment by thii** [comment]
This is 100% reproducible for us with Bazel 5.0.0-pre.20210831.2.

**Comment by coeuvre** [comment]
@thii Can you share a minimal repro?

**Comment by thii** [comment]
@coeuvre We have a pretty typical setup using a GCS bucket as the remote cache.

```
# .bazelrc
build --google_default_credentials
build --remote_cache=https://storage.googleapis.com/your-bucket
```

Repro steps:

1. Run
```
gcloud config configurations create <your-config>
gcloud config set project <your-project>
gcloud auth application-default login
```

2. The command opens a page in the browser to login to your Google account and allow permissions.
3. Go back to terminal, run
```
gcloud config configurations activate <your-config>
bazel build //target
```
