### ISSUE TITLE
Allows running the javac compiler in a separate process.

### ISSUE THREAD

**Issue by HTQianqian** [bazelbuild/bazel#13809]
### Description of the problem / feature request:

>  feature request: Allows running the javac compiler in a separate process.

### Feature requests: what underlying problem are you trying to solve with this feature?

> we are using the bazel, is there a way to set a fork parameter to allow the  javac compiler running in a separate process? 

### What operating system are you running Bazel on?

> X86 Linux

### What's the output of `bazel info release`?

> 4.1.0

**Comment by comius** [comment]
@larsrc-google can you reply and triage?

**Comment by larsrc-google** [comment]
I'm not sure what you're asking. All actions, including the Javac compiler, runs in processes separate from the Bazel process. Could you share more about what the problem you're seeing is?

**Comment by comius** [comment]
@larsrc-google can you triage?

**Comment by larsrc-google** [comment]
Closing due to lack of explanation. @HTQianqian, feel free to reopen with further information on what your problem is.
