### ISSUE TITLE
FR: Common definitions for native rules should apply to all rules

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/bazel#13805]
### Description of the problem / feature request:

Currently, there are some [common test definitions](https://docs.bazel.build/versions/4.0.0/be/common-definitions.html#common-attributes-tests), namely `env`, which are only set for native rules (`cc_test`, `py_test`, `sh_test`). These definitions should be allowed to apply to all rules.

### Feature requests: what underlying problem are you trying to solve with this feature?

[rules_rust](https://github.com/bazelbuild/rules_rust) has implemented the same functionality for `env` by introducing it's own [launcher](https://github.com/bazelbuild/rules_rust/blob/73f228f824b7b34549d3c7113056a40d87c17185/util/launcher/launcher_main.rs) but this is reported to have now caused issues in workflows which ran `rust_test` targets under a debugger (using [--run_under](https://docs.bazel.build/versions/4.0.0/command-line-reference.html#flag--run_under)). This appears to be caused by the process being started now runs the launcher binary before being replaced with the desired test process. There should be a way to set environment variables for tests and still allow that the test is the first thing executed with whatever is passed to `--run_under`. This would solve for the reported issue, however, if possible, there should be a mechanism for allowing rules to hook into commonly defined variables defined in the built-in launcher.

Or perhaps a way to allow rules to implement their own launcher and control when `--run_under` is applied (as an afterthought).

### What operating system are you running Bazel on?

Linux, MacOS, Windows

### What's the output of `bazel info release`?

release 4.0.0

###  Have you found anything relevant by searching the web?

A brief search did not result in me finding a similar feature request.

**Comment by UebelAndre** [comment]
cc @hlopko

**Comment by brandjon** [comment]
I don't quite understand the request. Test attributes like `size`, `flaky`, `shard_count`, and `timeout` make no sense for non-test targets.

**Comment by UebelAndre** [comment]
> I don't quite understand the request. Test attributes like `size`, `flaky`, `shard_count`, and `timeout` make no sense for non-test targets.

That's not what I'm suggesting. There are some "common definitions" for `test` rules which are only applied to rules written in Java (built into Bazel). Rules written in starlark have to re-implement these. The one I'm most familiar with is `env` and was trying to describe how `rules_rust` implemented similar functionality at the cost of a workflow where users would use `--run_under` to start a rust binary in a debugger. I would like to find a solution where `rules_rust` doesn't need to re-implement these "common definitions" and restore this `--run_under` workflow.

**Comment by hlopko** [comment]
https://github.com/bazelbuild/bazel/issues/7364 is the canonical issue for the `env` attribute.

**Comment by hlopko** [comment]
@UebelAndre is there any other attribute with special behavior in native rules that we need for Starlark rules?

**Comment by UebelAndre** [comment]
@hlopko To my knowledge, there's only `env` and `env_inherit`. Having those would satisfy my needs in `rules_rust`.
