### ISSUE TITLE
Support local maven_server

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#1380]
Bazel support specifying remote maven server. Yet, one cannot point to a local maven repo (by default under ~/.m2/repository) to fetch jars there. One use case here is to use bazel partially in one project, which has some dependency projects that use maven.

Internal ref: b/26058097

**Comment by kchodorow** [comment]
This can now be done in a skylark repository rule.

**Comment by davidzchen** [comment]
Do we have a Skylark repository rule that does this? If not, should we keep this bug open or open a new bug for the feature request?

**Comment by kchodorow** [comment]
Created #1410.
