### ISSUE TITLE
Fix failing tests after upgrading Windows image

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#13816]
The following tests fail after I upgraded our Windows image on CI:

- [//src/test/shell/bazel:resource_compiler_toolchain_test](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/a6ffbeec-a5ce-4d8a-91c6-c372437e7afa/src%5Ctest%5Cshell%5Cbazel%5Cresource_compiler_toolchain_test%5Cattempt_1.log)
- [//src/test/shell/integration:loading_phase_tests](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/a6ffbeec-a5ce-4d8a-91c6-c372437e7afa/src%5Ctest%5Cshell%5Cintegration%5Cloading_phase_tests%5Cattempt_1.log)
- [//src/test/shell/integration:target_compatible_with_test](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/a6ffbeec-a5ce-4d8a-91c6-c372437e7afa/src%5Ctest%5Cshell%5Cintegration%5Ctarget_compatible_with_test%5Cattempt_1.log)
- [//src/test/shell/bazel:python_version_test](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/a6ffbeec-a5ce-4d8a-91c6-c372437e7afa/src%5Ctest%5Cshell%5Cbazel%5Cpython_version_test%5Cattempt_1.log)

I have sent a fix for python_version_test and will disable the other three temporarily.

The difference between the old Windows image and the new one is:
- All the updates that happened in MSYS2 and Chocolatey in the meantime
- [Upgrade OpenJDK from 8 to 11 in Windows VM](https://github.com/bazelbuild/continuous-integration/commit/7f03fa5ad1fcbc8311faeb016a5ead48e78c0749)
- [Upgrade Windows SDK to 2004 in Windows VM](https://github.com/bazelbuild/continuous-integration/commit/bdf67367e48617bbe181d51c54a80a839f1d9efc)
- [Upgrade Python 3 to latest version in Windows VM](https://github.com/bazelbuild/continuous-integration/commit/6b03c3b2ff17494a6d47e2bc0ccc82d1d5d8a4f1)
- [Upgrade buildkite-agent to latest version in Windows VM](https://github.com/bazelbuild/continuous-integration/commit/fb8c33385627c62602399d1b14ba81b336edbcd0)
- [Upgrade Android SDK tools to latest version in Windows VM](https://github.com/bazelbuild/continuous-integration/commit/c0fb04939b5da83516146af4481e49458a9ce811)

**Comment by philwo** [comment]
@meteorcloudy If you have time, could you help me figure out how to fix them on Monday? 😊

**Comment by meteorcloudy** [comment]
Sure, looking into them!

**Comment by meteorcloudy** [comment]
Ha, looks like `grep` somehow failed to match Windows line endings, let me check why this is happening..

**Comment by philwo** [comment]
Maybe a bug or update in MSYS2? 🤔 

Also I remembered one more thing that changed - I upgraded the base image from Windows 10 build 1909 to build 20H2.

**Comment by meteorcloudy** [comment]
https://github.com/msys2/MSYS2-packages/pull/2163#issuecomment-700216927

Turned out this is an incompatible change in grep after upgrading grep to 3.5 in MSYS. We'll fix this by removing the line ending match in those tests.
