### ISSUE TITLE
bazel run //some/java/path:file_deploy.jar fails with wrong message

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#1381]
```
$ bazel run examples/java-native/src/main/java/com/example/myproject:hello-world_deploy.jar 
. 
INFO: Found 1 target... 
Target 
//examples/java-native/src/main/java/com/example/myproject:hello-world_deploy.jar 
up-to-date: 

bazel-bin/examples/java-native/src/main/java/com/example/myproject/hello-world_deploy.jar 
INFO: Elapsed time: 10.278s, Critical Path: 1.97s 

INFO: Running command line: 
bazel-bin/examples/java-native/src/main/java/com/example/myproject/hello-world_deploy.jar 
Exception in thread "main" java.lang.UnsupportedClassVersionError: 
com/example/myproject/Greeter : Unsupported major.minor version 52.0 
at java.lang.ClassLoader.defineClass1(Native Method) 
at java.lang.ClassLoader.defineClass(ClassLoader.java:803) 
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) 
at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) 
at java.net.URLClassLoader.access$100(URLClassLoader.java:71) 
at java.net.URLClassLoader$1.run(URLClassLoader.java:361) 
at java.net.URLClassLoader$1.run(URLClassLoader.java:355) 
at java.security.AccessController.doPrivileged(Native Method) 
at java.net.URLClassLoader.findClass(URLClassLoader.java:354) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:425) 
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:358) 
at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482) 
```

Interanl ref: b/21263003

**Comment by ulfjack** [comment]
Bazel marks all output files as executable and leaves it to the underlying OS to give an error message. On Linux, you can configure the kernel with custom 'launchers' for files that are marked as executable; maybe that's actually setup on your machine, but uses an older version of Java? (Ubuntu default is still 6, IIRC.)

**Comment by ulfjack** [comment]
Damien posted a different error message as well for MacOS:
INFO: Running command line: bazel-bin/java/test/test_deploy.jar
/private/var/tmp/_bazel_dmarting/ed5d94f1f29da4ca2fc9866ec50b91ad/google3/bazel-out/local_darwin-dbg/bin/java/test/test_deploy.jar: line 1: PK: command not found
/private/var/tmp/_bazel_dmarting/ed5d94f1f29da4ca2fc9866ec50b91ad/google3/bazel-out/local_darwin-dbg/bin/java/test/test_deploy.jar: line 2: syntax error near unexpected token `??
                                                  ?\?\P?E?'
/private/var/tmp/_bazel_dmarting/ed5d94f1f29da4ca2fc9866ec50b91ad/google3/bazel-out/local_darwin-dbg/bin/java/test/test_deploy.jK-*??ϳR0?3??r.JM,IM?u??RH?I?J?-??K?I?J,???M???u?I,.?R(???
                                                        ?\?\P?E?(LM!build-data.properties]?M?0????K]??"QIzv.I?+mH}h????h??ff??X??VS6????՗t?L.?t??C??$?QH?????į?Pr?sW??PK'R?ݸ<.?\??u?
ERROR: Non-zero return code '2' from command: Process exited with status 2.

**Comment by ulfjack** [comment]
It looks like MacOS is trying to execute the .jar file as a shell script, which will obviously not work.

In either case, I'm not sure there are any useful action items we could take to improve the situation. We could not mark output files as executable, but that's also problematic - on linux, jar files _may_ be executable (or maybe not). File a bug against Apple?

**Comment by ulfjack** [comment]
I'm closing this because I don't see anything we could do here. Feel free to reopen if you have a proposal of how Bazel could handle this better.

**Comment by damienmg** [comment]
We should refuse to execute the deploy jar and print a useful error message to the user.

**Comment by ulfjack** [comment]
I don't think we should refuse to do so. You can setup (at least) Linux such that this works.

**Comment by ulfjack** [comment]
I also don't think we should hard-code executable file extensions in Bazel, except if the underlying OS guarantees that it will never execute anything other than that.

**Comment by aiuto** [comment]
Re-closing. 2 years went by without a good proposal.
