### ISSUE TITLE
site documentation should have a build stamp

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#1382]
Hanwen was trying to troubleshoot why changes aren't appearing on bazel.io , and it would help tremendously if bazel.io would show the git commit or piper CL from which it is generated.

internal ref: b/24457716

**Comment by davidzchen** [comment]
We should have this and versioned documentation. I will work on this once I am done with what I currently have on my plate.

**Comment by davidzchen** [comment]
De-duping with #579
