### ISSUE TITLE
xcode-locator `kLSApplicationNotFoundErr` with Xcode 13 beta

### ISSUE THREAD

**Issue by OliverKoo** [bazelbuild/bazel#13830]
### Description of the problem:

I downloaded the newest Xcode13 beta 5. 
```
buildkite-agent$ xcode-select -p
/Applications/Xcode-13.beta.5.app/Contents/Developer
```
fresh clone bazel `git clone https://github.com/bazelbuild/bazel.git` then 
build `bazel build //tools/osx:xcode-locator-genrule` then run the xcode-locator binary 
```
buildkite-agent$ /private/var/tmp/_bazel_buildkite-agent/50e22d36fca4f06cb4501fd8f3501200/execroot/io_bazel/bazel-out/darwin-fastbuild/bin/tools/osx/xcode-locator 
error: Error Domain=NSOSStatusErrorDomain Code=-10814 "kLSApplicationNotFoundErr: E.g. no application claims the file" UserInfo={_LSLine=1483, _LSFunction=runEvaluator}
```

cc [xcode-locator.m ](https://github.com/bazelbuild/bazel/blob/master/tools/osx/xcode_locator.m) authors/contributors. 
@c-parsons @jmmv @katre @keith @aragos @sayrer @kjteske @segiddins and @goodspark 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. install Xcode13 beta 5
2. clone and build with steps above
3. run xcode-locator binary

### What operating system are you running Bazel on?

Mac Big Sur

### What's the output of `bazel info release`?

$ bazel info release
Starting local Bazel server and connecting to it...
release 4.1.0-homebrew

###  Have you found anything relevant by searching the web?

might have something to do with open URL https://stackoverflow.com/questions/46319937/canopenurl-failed-for-url-fbauth2-osstatus-error-10814

--**Update**--

If I install Xcode 12.5.1 then the `xcode-locator` works...so it seems like it has to do with Xcode13 Beta.

```
 buildkite-agent$ xcodes installed
12.5.1 (12E507)                 /Applications/Xcode-12.5.1.app
13.0 Beta (13A5212g) (Selected) /Applications/Xcode-13.beta.5.app
buildkite-agent$ /private/var/tmp/_bazel_buildkite-agent/50e22d36fca4f06cb4501fd8f3501200/execroot/io_bazel/bazel-out/darwin-fastbuild/bin/tools/osx/xcode-locator 
2021-08-11 23:49:02.480 xcode-locator[6672:40791] Found bundle com.apple.dt.Xcode in file:///Applications/Xcode-12.5.1.app/; contents on disk: (
    "file:///Applications/Xcode-12.5.1.app/Contents/"
)
2021-08-11 23:49:02.481 xcode-locator[6672:40791] Version strings for file:///Applications/Xcode-12.5.1.app/: short=12.5.1, expanded=12.5.1
{
        "12.5.1": "/Applications/Xcode-12.5.1.app/Contents/Developer",
        "12E507": "/Applications/Xcode-12.5.1.app/Contents/Developer",
        "12": "/Applications/Xcode-12.5.1.app/Contents/Developer",
        "12.5.1.12E507": "/Applications/Xcode-12.5.1.app/Contents/Developer",
        "12.5": "/Applications/Xcode-12.5.1.app/Contents/Developer"
}```

**Comment by keith** [comment]
Have you launched the new version to have it "install additional components" (or via the command line with `sudo xcodebuild -runFirstLaunch`)?

**Comment by OliverKoo** [comment]
This was resolved by needing to update my macOS version form 11.1 to 11.5.1 👍 

Note to future that `xcode-locator` error can mean that the OS version is not up to the version that Xcode requires
