### ISSUE TITLE
Separate `--features` and `--host_features`

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#13839]
Currently if you flip a feature like `--features=tsan` that affects compilation, any host / exec tools you depend on for your build will be recompiled with the tsan features, even though you likely only care about that for your target build, not your host tools.

I think there should be some way to separate these, for example having `--features` only apply to your `target` configuration and having a separate `--host_features` for the host / exec configuration similar to `--copt` and `--host_copt` (I'm sure there are many other potential solutions to this though)

### Have you found anything relevant by searching the web?

I really thought there was a tracking issue for this somewhere, but here are some slightly related issues:

- https://github.com/bazelbuild/bazel/issues/13315
- https://github.com/bazelbuild/bazel/issues/13308
- https://github.com/bazelbuild/bazel/issues/13048

**Comment by jyknight** [comment]
There's a bug in this change: it doesn't pass on `--host_features` _itself_ to the exec config, so a further transition within exec will drop all features. That is, it's missing a line like:
`exec.hostFeatures = ImmutableList.copyOf(hostFeatures);`

**Comment by keith** [comment]
@jyknight ah yes thanks, do you have a transition example where you saw this that I can use for a test case

**Comment by keith** [comment]
Submitted https://github.com/bazelbuild/bazel/pull/17625 in the meantime, but an example would be helpful

**Comment by jyknight** [comment]
Sorry, I don't have a standalone example. This issue broke builds with an action conflict in my codebase when I tried to pass `--incompatible_use_host_features --host_features foo`.

I'll guess it probably arises from a binary "X" requiring two exec tools "A" and "B" to generate code, where exec tool "B" also requires "A" as an exec tool. I think that'd result in `X -exec> A; X -exec> B -exec> A`. And with this bug, the second A will have a different feature set than the first A.
