### ISSUE TITLE
How do I specify the number of CPU cores bazel uses?

### ISSUE THREAD

**Issue by machomachopadre** [bazelbuild/bazel#1383]
I am building syntaxnet(tensorflow fork) with bazel. It's working very slowly and keeps hanging up.

The last time I had this problem(with caffe) someone tolad me to change the number of cores I was using by adding -j4. In bazel this command did not work. Any custom command for bazel like this?

CPU Specs: 3.8ghz clock, Quadcore

CPU Model: AMD 4800(or something along those lines).

Thanks!!

**Comment by hermione521** [comment]
Hi,

Please check `--local_resources` [here](http://www.bazel.io/docs/bazel-user-manual.html)
eg. `bazel build --local_resources=10000,3,100`

**Comment by machomachopadre** [comment]
thanks it worked
