### ISSUE TITLE
verbose_failures command line option should not cause full rebuild

### ISSUE THREAD

**Issue by oakad** [bazelbuild/bazel#13837]
Consider a larger build, many thousands of targets. The build failed for some obscure reason after a long time. No problem, we can use `verbose_failures`!

Alas, full rebuild is triggered and instead of quickly diagnosing and fixing the problem another long wait ensues.

And another, after the option is removed to revert to normal mode.

**Comment by meisterT** [comment]
I can't reproduce this with a build of Bazel itself. Do you have simple reproduction instructions?

**Comment by oakad** [comment]
It's not an easy one.
On my side I have a large number of externals, both local and http. I think it somehow interferes with how externals are being built.

**Comment by Wyverald** [comment]
I still can't reproduce by building Bazel itself (which definitely contains external repositories).

Please provide more reproduction info; otherwise, we can't feasibly work on this.
