### ISSUE TITLE
open source print_action command

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#1385]
This would allow YouCompleteMe (ycm) integration, among other things.

**Comment by dionescu** [comment]
The recent IDE efforts were a nice addition to Bazel. Is this one still on the radar?

**Comment by dslomov** [comment]
Assigning 0.6 milestone provisionnaly

**Comment by bogardon** [comment]
I would love to have this for my own clang based tools for objective-C projects. Has there been any movement here?

**Comment by ulfjack** [comment]
I'm afraid there hasn't been any progress. :-/

**Comment by ulfjack** [comment]
Thanks to an anonymous contributor, we just merged 6be3af9e3369b9b84b57c2dbe32525f45910408e.
