### ISSUE TITLE
when linkig MacOS SDK (Frameworks) - cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_x86_64'

### ISSUE THREAD

**Issue by buahaha** [bazelbuild/bazel#13855]
### Description of the problem / feature request:

I'm building with Bazel on MacOS. Somehow in one moment I've go this error, and can't get rid of it.

```
neosb@Szymons-MacBook-Air cpp_pro % bazel build  --config=clang_config //test:hello_test
ERROR: /private/var/tmp/_bazel_neosb/e834e65c3e7053cdbf2a63d1622160b3/external/local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_x86_64'
ERROR: Analysis of target '//test:hello_test' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed
INFO: Elapsed time: 0.200s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 3 targets conf\
igured)
```

### Feature requests: what underlying problem are you trying to solve with this feature?

This is a simple test case for google test where I want to link MacOS frameworks aka SDK's, primarly for use with Vulkan, but the program which is to be run here is not linked to Vulkan libraries, so it's easier to reproduce the bug/feature request.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

[my github repo](https://github.com/buahaha/game-cpp_pro)
run `bazel build  --config=clang_config //test:hello_test`

### What operating system are you running Bazel on?

MacOS Big Sur 11.5.2

### What's the output of `bazel info release`?

release 4.0.0
I have tried also a newest repo - 5.0.0-pre.20210802.5 and the proposed one by @keith - 4.2.0rc4

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Is this really neccesairly?

###  Have you found anything relevant by searching the web?

I have tried `bazel clean --expunge` with no avail.

I'v been searching for a whole day.

I tried [this](https://github.com/vsco/bazel-toolchains/tree/master/toolchains), with my changes, they didn't worked so I deleted them.

I do not understand [this](https://stackoverflow.com/questions/44993136/where-does-bazel-look-for-osx-sdks-and-what-to-do-if-its-not-finding-them), 'cos it's nothing that help.

### Any other information, logs, or outputs that you want to share?

This happens when I link `MacOS frameworks` with `objc_library` using `sdk_frameworks` option.

I do not have Xcode installed, I have an old machine, so it will not be up to date, my space is low and I do not want to code in big IDE, I use. VS Code. // or maybe I should?

**Comment by keith** [comment]
Can you test with the 4.2.0rc4 and see if that fixes the issue? https://releases.bazel.build/4.2.0/rc4/index.html

**Comment by buahaha** [comment]
Both the newest available version `5.0.0-pre.20210802.5` and the one you proposed `4.2.0rc4` gave me this result:

```
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/40548a2974f1aea06215272d9c2b47a14a24e556.zip) = 56ac9633c13d74cb71e0546f103ce1c58810e4a76aa8325da593ca4277908d72
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "56ac9633c13d74cb71e0546f103ce1c58810e4a76aa8325da593ca4277908d72"
DEBUG: Repository rules_cc instantiated at:
  /Volumes/musicianship/docs/Phoenix2/cpp_pro/WORKSPACE:50:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_neosb/e834e65c3e7053cdbf2a63d1622160b3/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'com_google_googletest' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "0134d73a4902574269ff2e42827f7573d3df08ae", shallow_since = "1628872955 -0400" and dropping ["visibility", "branch"]
DEBUG: Repository com_google_googletest instantiated at:
  /Volumes/musicianship/docs/Phoenix2/cpp_pro/WORKSPACE:41:15: in <toplevel>
Repository rule git_repository defined at:
  /private/var/tmp/_bazel_neosb/e834e65c3e7053cdbf2a63d1622160b3/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: /private/var/tmp/_bazel_neosb/e834e65c3e7053cdbf2a63d1622160b3/external/local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_x86_64'
INFO: Repository remote_java_tools_darwin instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:245:6: in <toplevel>
  /private/var/tmp/_bazel_neosb/e834e65c3e7053cdbf2a63d1622160b3/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_neosb/e834e65c3e7053cdbf2a63d1622160b3/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//test:hello_test' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed
INFO: Elapsed time: 25.920s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (26 packages loaded, 234 targets c\
onfigured)
    Fetching @remotejdk11_macos; fetching
    Fetching ..._macos; Extracting /private/var/tmp/_bazel_neosb/e834e65c3e705\
3cdbf2a63d1622160b3/external/remotejdk11_macos/temp16375752087899556083/zulu11\
.37.17-ca-jdk11.0.6-macosx_x64.tar.gz
```

That's exactly the same result, meaning that I see darwin_x86_64 is not an option...

**Comment by keith** [comment]
> I do not have Xcode installed

Oops, I should have read more carefully first, you have to have Xcode, or at least the separate command line tools package, regardless of if you use it as an IDE.

**Comment by buahaha** [comment]
Hey @keith , I still have this problem, even after installing Xcode.

**Comment by keith** [comment]
if you just installed it (and have launched it at least once to setup everything) and your `xcode-select -p` points to the right place, make sure to `bazel clean --expunge` once and try again to make it reconfigure that

**Comment by buahaha** [comment]
Thank you @keith everything is almost where it should be, I think I will close that.

To do it you have to:
`install Xcode`
`bazel clean --expunge`
optionally `remove all unnecesairly targets (all)`
run `bazal build` again

**Comment by guw** [comment]
We observed that `bazel sync --configure` is sufficient instead of a potentially expensive `bazel clean --expunge`. However, this problem happens quite often on developer machines and seems to be related to environmental changes (OS updates?).
