### ISSUE TITLE
Doc bug: "Genrule Environment" doc is confusing (typo suspected)

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#13885]
### Description of the problem / feature request:

[Genrule Environment](https://docs.bazel.build/versions/main/be/general.html#genrule-environment) contains this sentence: `However, Bazel (but not Bazel) passes through the value of the user's PATH environment variable` This is confusing, but more importantly it obscures the answer to the primary question this doc is supposed to answer: Does genrule inherit PATH from the environment or not!

### What's the output of `bazel info release`?

4.2.0

**Comment by communikit** [comment]
Closing as duplicate of #13426
