### ISSUE TITLE
[Feature Request] Avoid rebuilding external packages when chang `.bazelrc`

### ISSUE THREAD

**Issue by hiberabyss** [bazelbuild/bazel#13880]
Sometimes, when change copts in `.bazelrc` will also caused the external packages be rebuilt, could this be avoid?

**Comment by oquenchil** [comment]
Can't be avoided because the configuration is applied to all packages including external.

**Comment by hiberabyss** [comment]
> Can't be avoided because the configuration is applied to all packages including external.

Is it possible to accomplish this via a flag?

In many cases, the external package is not expected changed when change option like `compilation_mode` and the  external package may need a lot time to rebuild.
