### ISSUE TITLE
Question as regards dependency on fresher glibc

### ISSUE THREAD

**Issue by fgeorgatos** [bazelbuild/bazel#1388]
Hello @damienmg,

Per #760 and much other tribal gossip, rhel6's glibc 2.12* does not appear to cut it much for bazel [1];
however, I am inclined to ask why, ie. which is the strictly technical cause for this.
Is it just a matter of setting up the build environment correctly or, what?

[1] N.B. You're not alone; I have seen at least Clang/3.4 and friends complain in similar ways, I'll spare you the details of the whys.

**Comment by damienmg** [comment]
It is just setting the build environment correctly. We test rhel6 and this should work pretty well now. Tell me if you have repro cases (especially with a docker container we can set-up for test).

**Comment by damienmg** [comment]
No answer, closing, please ping again if you think this should be reopened.

**Comment by fgeorgatos** [comment]
sry, I haven't tested it yet (but a user reported to me some success, so
something must be working).
I will come back to this once I have confirmed it in first-person mode.

On 27 June 2016 at 12:14, Damien Martin-Guillerez <notifications@github.com>
wrote:

> Closed #1388 <https://github.com/bazelbuild/bazel/issues/1388>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bazelbuild/bazel/issues/1388#event-704797008>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABdgQHnN1Kh-fSd6_cIB_uywvlu4MBcYks5qP7CsgaJpZM4I0c4a>
> .
>



-- 
echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum

**Comment by damienmg** [comment]
Ok reopening then.

**Comment by damienmg** [comment]
Re-closing no answer, please ping back if you have more data.
