### ISSUE TITLE
Doc bug: "Predefined genrule variables" is unclear and confusing

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#13886]
### Description of the problem / feature request:

[Predefined genrule variables](https://docs.bazel.build/versions/main/be/make-variables.html#predefined_genrule_variables) contains this sentence: `WARNING: The Make variable RULEDIR should be used instead because it has simpler semantics and behaves in the same way regardless of the number of output files of the rule.` 
What is absolutely unclear from the context is WHAT it should be used instead? 
"RULEDIR should be used instead..." instead of WHAT?

### What's the output of `bazel info release`?

4.2.0

**Comment by gregestren** [comment]
Also added https://github.com/bazelbuild/examples/pull/219 to fill out the examples more clearly. If/when that PR lands I'll also add more "see examples" links to the docs.
