### ISSUE TITLE
http_jar rule doesn't allow specifying file name when downloading

### ISSUE THREAD

**Issue by rabisg** [bazelbuild/bazel#13887]
### Description of the problem / feature request:

> http_jar rule doesn't have a parameter to specify downloaded file name. This is ok in most cases but if a http_jar is used in conjunction with docker rules this becomes a problem because multiple files are called `downloaded.jar`. In this case all but one file gets replaced. 
A simple fix would be to include a parameter to specify the name of the file. I believe keeping the name as downloaded.jar would ensure backward compatibility as well.

**Comment by rabisg** [comment]
Happy to send a PR something like [this](https://github.com/bazelbuild/bazel/compare/master...rabisg:http_jar?expand=1)

**Comment by philwo** [comment]
Thank you for the report and also the proposed patch! This looks fine to me, @meteorcloudy @Wyverald what do you think?

**Comment by meteorcloudy** [comment]
That looks fine, just need to ensure the `downloaded_file_path` should always be a relative path. Happy to review the PR!

**Comment by rabisg** [comment]
Hey @meteorcloudy  PR is here: https://github.com/bazelbuild/bazel/pull/13961
