### ISSUE TITLE
Remove the --all_incompatible_changes flag

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#13892]
The `--all_incompatible_changes` flag should be removed.

- Its intent is not clear since the introduction of LTS tracks
  -  It originally was used to gather all breaking changes for the next major release. The team does not do that any more since changes can be introduced at HEAD at any time
- Sometimes distinct `--incompatible_*` flags can interfere with each other.
  - in theory you could have conflicts that make Bazel unusable
  - in practice, it interferes with flag deprecation #11193
- The mechanism does not capture Starlark defined flags. As we move flags out of the Bazel core and into Starlark it will become less useful.

**Comment by aiuto** [comment]
Plan over several PRs:
- Make it a no op
- Remove from any Blaze and Bazel CI configurations
- Delete the option Metadata tag TRIGGERED_BY_ALL_INCOMPATIBLE_CHANGES
- Delete it
- Clean up user test data that observes it

**Comment by brandjon** [comment]
Has there been any decision on whether the extra expansion flag logic, which was added to the options parser expressly for the implementation of `--all_incompatible_changes`, should be deleted?

I feel like options parsing is enough of a mess that removing it won't necessarily make a dent in its complexity, absent a larger scale effort.

If it remains but is now unused, we should add a TODO to consider deprecating it.

**Comment by aiuto** [comment]
We did not decide that yet. Even if we do, I would like to do it in
multiple PRs. One to get rid of the use, another to remove the mechanism.
Opened https://github.com/bazelbuild/bazel/issues/13923 to track making the
choice
