### ISSUE TITLE
Transitions cannot read Starlark flags as `@repository_name//:flag_name` in 4.2.0

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#13890]
Bazel 4.2.0 introduced a regression in the handling of Starlark flags: In a transition, the value of such a flag cannot be read if the flag is referred to as `@repository_name//:flag_name` instead of `//:flag_name`, which as far as I know is required for that transition to be usable by other workspaces. Reading the flag does not work even if it is set via both `--@repository_name//:flag_name` and `--//:flag-name` on the commandline.

I noticed this while working on [rules_fuzzing](https://github.com/bazelbuild/rules_fuzzing), whose tests no longer pass with Bazel 4.2.0. Usage of `rules_fuzzing` by other workspaces does not seem to be affected.

I [created a reproducer](https://gist.github.com/fmeum/4e2b5d08aa9a7ed8df39e4362f4bfa3b) that prints 

- `regressed`with
  - Bazel 4.2.0
- `not_regressed` with
  - Bazel 4.0.0
  - Bazel 4.1.0
  - Bazel 5.0.0-pre.20210810.4
  - Bazel 4.2.0 with 80c59dea59 reverted

Unfortunately 98d376faeb206f14838156ce4cb305ddbfce08fa cannot be cleanly cherry-picked on top of Bazel 4.2.0 by itself, so reverting 80c59dea59 appears to be the safest way to mitigate this regression.

_Originally posted by @fmeum in https://github.com/bazelbuild/bazel/issues/13558#issuecomment-903488624_

**Comment by katre** [comment]
Investigating now. Please also file an issue at https://github.com/bazelbuild/continuous-integration/issues/new/choose to have rules_fuzzing added to our downstream CI, to prevent this happening in the future.

**Comment by katre** [comment]
This will be fixed in 4.2.1.
