### ISSUE TITLE
Migrate dependency on error prone to use git_repository

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1389]
Internal ref: b/22298755

**Comment by ulfjack** [comment]
Why? I think doing so would currently break bootstrap, as we now have a hard dependency on error prone from guava. (I also think we may be better off with the monorepo approach.)

**Comment by damienmg** [comment]
That was thought to simplify the update of error-prone. Actually a git submodules or vendoring might be enough. Our approach to vendoring is difficult and we need to reconsider it at some point.

**Comment by ulfjack** [comment]
The argument made on b/22191155 is thus:
"The best tested configuration is always going to be the current internal release, so keeping things up to date and avoiding version skew should make breakages less likely."

Posting it here for future reference.
