### ISSUE TITLE
Define Symbol Globally (C++, assert and NDEBUG)

### ISSUE THREAD

**Issue by aarossig** [bazelbuild/bazel#139]
I am writing C++11 and using assert to test for programmer error. I would like to disable the assertions by defining the symbol NDEBUG as per http://www.cplusplus.com/reference/cassert/assert/

How can I define this symbol for all targets when building an optimized build?

**Comment by ulfjack** [comment]
We should update the CROSSTOOL file to set that flag in the opt config. Then you can build with:
bazel build -c opt //foo/bar

As a workaround, you can modify your CROSSTOOL file yourself.

**Comment by hanwen** [comment]
The current crosstool has NDEBUG for opt mode.
