### ISSUE TITLE
[Question] How to fix cpp library order problem

### ISSUE THREAD

**Issue by hiberabyss** [bazelbuild/bazel#13900]
In my case, I have two library:

- `folly` is installed in system and linked with link option `-lfolly`
- `fmt` library, which is the dependency of `folly`

When I add `fmt` as deps of folly, there will be compiling error because of the library order (fmt is placed before folly).

If I place the libfmt with path in linkopts after folly, there is no error. Is there any method to fix the library dependency order problem?

Thanks!

![image](https://user-images.githubusercontent.com/2898670/130751234-84e83816-3c46-40c4-9958-9e3295485d1c.png)

**Comment by oquenchil** [comment]
It looks like fmt then depends on folly too? What you can do then is add folly to the linkopts of fmt.

**Comment by hiberabyss** [comment]
> It looks like fmt then depends on folly too? What you can do then is add folly to the linkopts of fmt.

No, fmt did not depend on folly and it could be compiled sucessfully.

**Comment by oquenchil** [comment]
It does look like you are not declaring dependencies in the right way. Not sure what depends on what in the actual code.

**Comment by regisd** [comment]
I also don't understand the question. Instead of a screenshot, I suggest you write the two rules (what works, what doesn't work).

Also, if you have a working solution, what problem are you trying to solve?

**Comment by hiberabyss** [comment]
> I also don't understand the question. Instead of a screenshot, I suggest you write the two rules (what works, what doesn't work).
> 
> Also, if you have a working solution, what problem are you trying to solve?

My project depends on folly, which was installed as system library since it's difficult to compile folly with `bazel`.

Folly depends on other libraries like `fmt` which need also be installed as system library.

However, I would like my project has as little system library dependencies as possible. I compile `fmt` with bazel and add it as the dependency of `folly`, then the problem occur (there will be compiling error because of the library order).

The possible way to fix the problem is to add bazel compiled `fmt` library path into linkopts, however, it's ugly and could not work if the compile_mode changed.

The problem could be solved if bazel label supported in linkopts.

**Comment by hiberabyss** [comment]
Seems could specify library path via `'$(BINDIR)/external/fmt/libfmt/lib64/libfmt.a',`
