### ISSUE TITLE
bazel branch coverage

### ISSUE THREAD

**Issue by yanglimingcn** [bazelbuild/bazel#13919]
I use Bazel-3.7.2 to build c++ project
I use the command below, I can not get branch coverage data from "bazel-out/_coverage/_coverage_report.dat" file, is Bazel support branch coverage?

bazel --output_base=../output coverage //test/unittest/... --jobs=32 --collect_code_coverage=true --compilation_mode=dbg -s --copt -DHAVE_ZLIB=1 --define=with_glog=true --define=libunwind=true --copt -DGFLAGS_NS=google --copt -Wno-error=format-security --copt -msse4.2 --incompatible_linkopts_to_linklibs --cxxopt -std=c++17 --instrumentation_filter="-/javatests[/:],-/test/java[/:]" --experimental_cc_coverage --combined_report=lcov --coverage_report_generator=@bazel_tools//tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator:Main

**Comment by yanglimingcn** [comment]
bazel coverage --action_env=COVERAGE_GCOV_OPTIONS=-b , add COVERAGE_GCOV_OPTIONS=-b option will generate branch coverage

**Comment by chenqingguo** [comment]
Same question. Add --action_env=COVERAGE_GCOV_OPTIONS=-b get branch  @yanglimingcn, I wonder where did you find the flag.

**Comment by qiuyeyijian** [comment]
Very useful
