### ISSUE TITLE
Support Jack compilation for Bazel

### ISSUE THREAD

**Issue by serynth** [bazelbuild/bazel#1391]
Although Jack is technically supported, it's not part of the `android_sdk_repository` rule yet. And it can't be for a little while; in order to support Bazel's current integration with Jack, the version of Jack must support both the new workflow for Jack (supported in Brest, present in 23.0.1+) and the `--tolerant` flag (not yet released AFAIK). Since the latter is not supported yet, this feature should be on hold for a little while; this issue just tracks this actually getting done.

As for the work that actually needs to be done - there are some wrapper scripts internally designed to smooth over any difficulties in calling Jack. These need to be released and integrated with the `android_sdk_repository` rule based on the build tools version being appropriate.

**Comment by hermione521** [comment]
Added labels, feel free to change.

**Comment by iamironz** [comment]
Jack is now deprecated (https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html). Feature request are not actual.
