### ISSUE TITLE
Documentation issue: C++  toolchain configuration

### ISSUE THREAD

**Issue by jwbee** [bazelbuild/bazel#13916]
Documentation URL: https://docs.bazel.build/versions/4.2.0/cc-toolchain-config-reference.html

There's nothing about this stanza which is syntactically valid:

```action_configs = [
    action_config (
        config_name = "ACTION_NAMES.cpp_link_executable",
        action_name = "ACTION_NAMES.cpp_link_executable",
        tools = [
            tool(
                with_features = [
                    with_feature(features=["generate-debug-symbols"]),
                ],
                tool_path = "toolchain/mac/ld-with-dsym-packaging",
            ),
            tool (tool_path = "toolchain/mac/ld"),
        ],
    ),
]
```

* `action_config` does not have `config_name` parameter.
* `action_name` doesn't want a literal string as a value, it wants the value of the variable
* `tool` does not have a `tool_path` parameter; it has `path`.

I'm not smart enough to do it but this whole doc wants an audit.

**Comment by keertk** [comment]
Hi there! Please refer to this [new documentation](https://bazel.build/rules/lib/cc_common). Feel free to reopen if you see any issues here.

**Comment by afoxley** [comment]
This example section still has the old arg names: https://bazel.build/docs/cc-toolchain-config-reference#example-usage
