### ISSUE TITLE
lang_proto_toolchain behaving inconsistently for javalite vs java toolchains RE: blacklisted_protos

### ISSUE THREAD

**Issue by perezd** [bazelbuild/bazel#13928]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

I'm attempting to use the `blacklisted_protos` argument of `lang_proto_toolchain` and getting inconsistent behavior between java and javalite toolchain definitions.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The diff we've made is here:
https://github.com/protocolbuffers/protobuf/pull/8942

we've been testing dupes with this reproducer: https://github.com/eikemeier/proto-java
Simply pull this PR, and use `local_repository` in the WORKSPACE of this reproducer to get our results.

For java_proto_library we get no dupe warnings, but for java_lite_proto_library we're getting dupe warnings for `@com_google_protobuf//:timestamp_proto`.

We _were_ seeing that as well in main, but properly configuring `blacklisted_protos` fixed java but not lite for some reason.

### What operating system are you running Bazel on?

MacOS

### What's the output of `bazel info release`?

release 4.0.0

###  Have you found anything relevant by searching the web?

Nope.

**Comment by comius** [comment]
Inspecting the code, the `blacklisted_protos` mechanism is not implemented in `java_lite_proto_library` rule in particular in `JavaLiteProtoAspect` class. 

I don't know if there were historical reasons for not implementing it - for example there are some issues with pre-generated/provided code and javalite proto libraries - any such problems would bubble up when trying to implement it.

There shouldn't be much work to do this, but I'm a bit swamped at the moment.

cc @Yannic who was recently touching this mechanism

**Comment by Yannic** [comment]
I agree that this should be straight forward to implement.

Java Lite protos do not allow mixing versions of protoc and the runtime [1] (which contains all/most WKPs), so doing that should be safe.

I can send a PR later this week, @comius do you have the bandwidth to import it and run it through presubmit?

[1] `we will NOT guarantee API/ABI stability for Java Lite`: https://github.com/protocolbuffers/protobuf/blob/master/java/lite.md

**Comment by comius** [comment]
> I can send a PR later this week, @comius do you have the bandwidth to import it and run it through presubmit?

I'll make time, thanks!

**Comment by perezd** [comment]
We (protobuf team) appreciate the help!

**Comment by perezd** [comment]
Is this change present in any published releases?
