### ISSUE TITLE
bazel can not generate enumeration related function xxx_Name.

### ISSUE THREAD

**Issue by TUT-jiayou** [bazelbuild/bazel#13926]
### Description of the problem / feature request:

Hi, all 

* I want to use bazel to build protobuf for Enumerations to generate related functions.
 follow the documents, the function *xxx_Name* should be generated, but I can not find the function in my generated cpp header file.
* But I can got the related *xxx_MIN*, *xxx_MAX* 
* This is across-compile in x86 machine for aarch64.
![image](https://user-images.githubusercontent.com/21277368/131465337-f6519048-4168-4648-b2b7-713a8d72e372.png)

* About my environment:
 1. Ubuntu 18.04 x86_64 across-compile for aarch64
 2. bazel 0.13.0
 3. protobuf 3.10.1

* I directly use the protobuf software, I can got the function *xxx_Name*.  When the protobuf version is used in my bazel project , the some errors are got.
eg: 
  1.  rules_python/python/private/reexports.bzl:40:19: name 'PyInfo' is not defined (did you mean 'ApkInfo'?)
  2.  Extension file not found. Unable to load file '@bazel_tools//tools/python:toolchain.bzl': file doesn't exist or isn't a file.
* I want to know if the reason are right.  would you give me some guide?

### Feature requests: what underlying problem are you trying to solve with this feature?

* about import protobuf package information in *WORKSPACE*
```
http_archive(
    name = "com_google_protobuf",
    sha256 = "d7a221b3d4fb4f05b7473795ccea9e05dab3b8721f6286a95fffbffc2d926f8b",
    strip_prefix = "protobuf-3.6.1",
    urls = [
        "https://cnbj1.fds.api.xiaomi.com/mace/third-party/protobuf/protobuf-3.6.1.zip",
        "https://github.com/google/protobuf/archive/v3.6.1.zip",
    ],
)

```
* about proto cpp configurate in the realted directory *BUILD* file
```
cc_proto_library(
    name = "bench_proto_cc",
    srcs = glob(["base.proto",
                "aibench.proto"]),
    # default_runtime = "@com_google_protobuf//:protobuf_lite",
    default_runtime = "@com_google_protobuf//:protobuf",
    protoc = "@com_google_protobuf//:protoc",
)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

> Replace this line with your answer.

### What's the output of `bazel info release`?

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by aiuto** [comment]
This is really a question for protobuf people. 
But, it is also for bazel 0.x, you should at least try with the 4.x distribution.
