### ISSUE TITLE
Building a project with Java record types fails with `error: unexpected identifier 'record'`

### ISSUE THREAD

**Issue by neilg** [bazelbuild/bazel#13924]
### Description of the problem / feature request:

Building a project with Java record types fails with `error: unexpected identifier 'record'` if a target depends on the target with record types. That is, if consumer depends on  records then the build fails, however,  if the dependency is removed then the build succeeds.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

A project demonstrating the build failure is available: https://github.com/neilg/bazel-records
The main branch fails to build, the [working](https://github.com/neilg/bazel-records/tree/working) branch builds.

### What operating system are you running Bazel on?

Linux pinot 5.13.13-arch1-1 #1 SMP PREEMPT Thu, 26 Aug 2021 19:14:36 +0000 x86_64 GNU/Linux

### What's the output of `bazel info release`?

release 5.0.0-pre.20210824.2

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a

###  Have you found anything relevant by searching the web?

> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

Nothing in any of these places.

### Any other information, logs, or outputs that you want to share?
No

**Comment by eikemeier** [comment]
As a workaround, you can use `build --nojava_header_compilation`, see https://github.com/melsicon/value-comparison

**Comment by comius** [comment]
cc @cushon, ijar will probably need to support new constructs in newer Java versions
