### ISSUE TITLE
Docs: repository_ctx no longer documented on "main"

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#13921]
### Description of the problem / feature request:

`repository_ctx` is not documented on the [main version](https://docs.bazel.build/versions/master/skylark/lib/repository_ctx.html), only on [4.2.0](https://docs.bazel.build/versions/4.2.0/skylark/lib/repository_ctx.html).

`ctx` is documented on both branches.

###  Have you found anything relevant by searching the web?

I searched the issues for `repository_ctx` but nobody else filed this.

I see no mention of "repository_ctx" in the 5.0.0 rc release notes, so I don't think it's going away.

[It's still there in the code too.](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryContext.java?q=%5C%22repository_ctx%5C%22&ss=bazel%2Fbazel)

**Comment by Wyverald** [comment]
Thanks for filing this! Most likely due to https://cs.opensource.google/bazel/bazel/+/5e5350311426eeab98db31809ccf627f55511d51 . I'll look into this ASAP.

**Comment by laszlocsomor** [comment]
Thank you!

**Comment by Wyverald** [comment]
A bit of an update: this seems to be some class loader weirdness. Nothing in the package `com.google.devtools.build.lib.bazel` nor its subpackage `com.google.devtools.build.lib.bazel.repository.starlark` (which is where the StarlarkRepositoryContext class lives) is found by the documentation generator. The weird thing is, though, that other subpackages there (for example `com.google.devtools.build.lib.repository.rules`) _are_ found.

Will keep digging tomorrow.

**Comment by laszlocsomor** [comment]
Thanks for the rapid fix!
