### ISSUE TITLE
downloader prints SHA256 for each file at INFO level

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#13935]
Also the downloader prints SHA256 for each file at INFO level:

 https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/DownloadManager.java;l=237?q=DownloadManager.java

__Originally posted by @alexeagle in https://github.com/bazelbuild/bazel/issues/13764#issuecomment-898196346__

**Comment by keith** [comment]
https://github.com/bazelbuild/bazel/pull/13937
