### ISSUE TITLE
Integrating AudioKit in Bazel

### ISSUE THREAD

**Issue by LeoWPereira** [bazelbuild/bazel#13947]
Hi all,

Currently in a xcode project I use the AudioKit framework and Cocoapods for its management.

I do wanna switch to Bazel though, and I've been able to do everything but support AudioKit. Has anyone been able to use it in a Bazel project?

I though about either using the .xcframework or cloning AudioKit's repository and building it from scratch, but I couldn't make neither of them work.

**Comment by aiuto** [comment]
You would be better off asking on Stackoverflow or slack about this.
