### ISSUE TITLE
Allow multiple executables (w/ runfiles) from in a single rule

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/bazel#13949]
### Description of the problem / feature request:

Feature: Allow creating multiple executablew (with runfile trees) within a single rule.

### Feature requests: what underlying problem are you trying to solve with this feature?

Example: I want a rule that set up multiple related tools for a language.

```python
example_tools(
  name = ":example",
  lib = "@example_1_0_0//:lib",
)
```

And this would provide `ExampleToolsInfo`:

```
ExampleToolsInfo = provider(
  fields = {
    "compiler": "Compiler", # executable
    "format": "Format", # executable
    "linker": "Linker", # executable
    "lint": "Lint" # executable
)
```

The `ExampleToolsInfo` would be used by various language-specific rules.

---

However, rules can only produce a single executable and runfile tree.

Current workarounds:

1. Create a separate rule for each. Cumbersome for the user. A macro could solve that, but has the usual downsides of macros.
2. Use self-contained executables. Not easily for many runtimes.
3. Combine all executables into one (`example compile`, `example format`, etc.). Extra work. Contradicts the principle of minimal inputs.
4. Include a pseudo-runfiles abstraction that downstream actions use. Awkwardly reimplements something that Bazel already has support for. Makes ad-hoc testing of the tools more involved.

###  Have you found anything relevant by searching the web?

There's a Google Groups thread where I discover this limitation, but I can't find it now.

**Comment by aiuto** [comment]
This looks like you are setting up a toolchain. Did you look at that, or do you have something else in mind? 
From the little you said, it feels like you could have rules to build each executable and make those private inputs to the example_tools() rule. That, in turn, would take the DefaultInfo from each and bundle them into a different provider. But, I may be mis-guessing your real intent.

**Comment by benjaminp** [comment]
Is different from #12459?

**Comment by pauldraper** [comment]
Well that's embarrassing.

**Comment by pauldraper** [comment]
> you are setting up a toolchain

AFAIK toolchains are global. E.g. I can't have one, say compiler version, for target A and another for target B.
