### ISSUE TITLE
Can Java Plugin srcs attribute be optional? 

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#1395]
You can close this issue if you think this is an edge case but I was just reading once more through the java rules documentation where I saw the `srcs` attribute documentation.
It says the attribute is optional and is usually required unless you use the `main_class` or `runtime_deps` attributes.
Problem is that java_plugin has neither of these attributes.
I know the attribute, and so the documentation, is shared but maybe it shouldn't be? Maybe for this case it's required?

**Comment by damienmg** [comment]
It is optional, if you specify deps and the processor_class

**Comment by ittaiz** [comment]
got you.
Then I think there are three options-
1. Add a reference to processor_class in the general attribute documentation
2. Duplicate the documentation since it's a bit misleading (also the java_library one talks about main_class)
3. Ignore it as an edge case in understanding

**Comment by ittaiz** [comment]
@damienmg wdyt? I can do whatever change you think is best.
If you're good with either I'll just pick one and send a PR

**Comment by ulfjack** [comment]
It's already referencing main_class, which is only on java_binary, right? Maybe call this out more explicitly, like so:
"<general documentation on srcs>

On java_binary, srcs is optional if ...

On java_plugin, srcs is optional if ..."
