### ISSUE TITLE
Unable to build 4.2 bazel version

### ISSUE THREAD

**Issue by anthpi** [bazelbuild/bazel#13955]
### Description of the problem / feature request:

Unable to build 4.2.* Bazel using 4.0.0 Bazel.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Fetch 4.2.0 or 4.2.1 tag
Bazel built using 4.0.0 bazel as well as JDK11.
Same command that I use works fine for building Bazel 4.0.0

### What operating system are you running Bazel on?

RHEL 7.8

### What's the output of `bazel info release`?

release 4.0.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/bazelbuild/bazel.git
c6c63890460546c2d605812ad7e7baef19eb7100
02ad3e3bc6970db11fe80f966da5707a6c389fdd

###  Have you found anything relevant by searching the web?

I was not able to find anything

### Any other information, logs, or outputs that you want to share?

ERROR: <path_to_bazel_repo>/tools/jdk/BUILD:41:15: //tools/jdk:dummy_toolchain: missing value for mandatory attribute 'java_runtime' in 'java_toolchain' rule
ERROR: <path_to_bazel_repo>/tools/jdk/BUILD:353:23: //tools/jdk:toolchain_hostjdk8: missing value for mandatory attribute 'java_runtime' in 'java_toolchain' rule
ERROR: <path_to_bazel_repo>/tools/jdk/BUILD:362:23: //tools/jdk:legacy_toolchain: missing value for mandatory attribute 'java_runtime' in 'java_toolchain' rule
ERROR: <path_to_bazel_repo>/tools/jdk/BUILD:402:23: //tools/jdk:toolchain_vanilla: missing value for mandatory attribute 'java_runtime' in 'java_toolchain' rule
ERROR: <path_to_bazel_repo>/tools/jdk/BUILD:414:27: //tools/jdk:toolchain_java8: missing value for mandatory attribute 'java_runtime' in 'java_toolchain' rule
ERROR: <path_to_bazel_repo>/tools/jdk/BUILD:414:27: //tools/jdk:toolchain_java9: missing value for mandatory attribute 'java_runtime' in 'java_toolchain' rule
ERROR: <path_to_bazel_repo>/tools/jdk/BUILD:414:27: //tools/jdk:toolchain_java10: missing value for mandatory attribute 'java_runtime' in 'java_toolchain' rule
ERROR: <path_to_bazel_repo>/tools/jdk/BUILD:414:27: //tools/jdk:toolchain_java11: missing value for mandatory attribute 'java_runtime' in 'java_toolchain' rule
ERROR: <path_to_bazel_repo>/src/java_tools/buildjar/BUILD:58:15: //src/java_tools/buildjar:bootstrap_toolchain: missing value for mandatory attribute 'java_runtime' in 'java_toolchain' rule
ERROR: <path_to_bazel_repo>/src/main/native/BUILD:17:8: Target '//tools/jdk:jni_header' contains an error and its package is in error and referenced by '//src/main/native:copy_link_jni_header'
INFO: Repository remotejdk11_linux instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:41:6: in <toplevel>
  <output_user_root>/a797661ce993429e2d5292901ceba3c4/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
  <output_user_root>/a797661ce993429e2d5292901ceba3c4/external/bazel_tools/tools/jdk/remote_java_repository.bzl:48:17: in remote_java_repository
Repository rule http_archive defined at:
  <output_user_root>/a797661ce993429e2d5292901ceba3c4/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//src:bazel' failed; build aborted: Analysis failed
INFO: Elapsed time: 3.099s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (153 packages loaded, 2744 targets configured)

**Comment by dmivankov** [comment]
What is the full command? Is it building bazel 4.2.1 with bazel 4.0.0 or with bazel 5.x?
Tried 4.2.1 with .4.0.0 and it seems to be getting progress
Also found similar error message in https://github.com/bazelbuild/rules_appengine/issues/119#issue-779737390 referring to https://github.com/bazelbuild/bazel/commit/c8e179fc7676ec8c0f4787d470b51e9837fc9750 which I think is not a part of 4.x
