### ISSUE TITLE
A stable Bazel release with Java 17 support

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#13966]
### Description of the problem / feature request:

A release of Bazel that supports compiling Java 17 projects (#13965)

### Feature requests: what underlying problem are you trying to solve with this feature?

A stable release of Bazel that supports Java 17 out of the box, including being able to specify a custom Java 17 JDK.

**Comment by cushon** [comment]
@comius I'm not entirely clear on the interaction between the versioning of java_tools and Bazel, and LTSs. I think #13965 is going to be fixed in time for the cutoff for 5.0. Is there anything else to be done here?

**Comment by comius** [comment]
> @comius I'm not entirely clear on the interaction between the versioning of java_tools and Bazel, and LTSs. I think #13965 is going to be fixed in time for the cutoff for 5.0. Is there anything else to be done here?

I think this is it. java_tools has been release and are used by default @head, and will make it into LTS release.

If we make changes later, we can release java_tools again, users can use the new version of java_tools manually or we can also patch LTS release for the newer version of java_tools to be used by default.
