### ISSUE TITLE
Remove hard-coded path of /bin/bash

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/bazel#1396]
While `bash(1)` is available for most Unix-like systems, assuming it to be installed under `/bin` is not a portable assumption. This causes problems under FreeBSD and, reportedly, also under NixOS. 

It would help users of systems with bash installed at a different place if they could specify where the bash is installed to. Part of this already addressed with the introduction of the `BAZEL_SH` environment variable, but there are still many places with hard-coded `/bin/bash` left that cause problems.

**Comment by laszlocsomor** [comment]
Another user is requesting the same: https://groups.google.com/d/msg/bazel-dev/s8gJKk6vpuA/9n0ehEdjCAAJ

@aehlig, do you know who could make a decision about this?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
