### ISSUE TITLE
Separate out Bazel's ``tools`` directory

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/bazel#1397]
It can be desirable to unbundle Bazel from its `tools` directory and maybe even split the latter into language-specific repositories. Some care has to be taken to ensure compatibility between the Bazel version and the version of the tools. Proposed versions include
- making Bazel verify correct version of the tools or event downloading the correct version istelf, and
- keeping backwards compatibility

where currently the first solution seems to be favored.

@damienmg, @lberki, and @kchodorow expressed opinions on this matter.

**Comment by lberki** [comment]
This sounds like a reasonable idea, although keep in mind that we'd then need to synchronize between Bazel releases and this repository somehow.

**Comment by laurentlb** [comment]
Is it about removing `@bazel_tools`?
We can keep this bug open, but I think it's useful to have more specific bugs (some of the files are already moving out).

**Comment by meisterT** [comment]
I agree with Laurent, there's nothing actionable in here.
