### ISSUE TITLE
"test" exec_group is not present on starlark defined rules

### ISSUE THREAD

**Issue by djmarcin** [bazelbuild/bazel#13986]
### Description of the problem / feature request:

The "test" exec_group added in https://github.com/bazelbuild/bazel/commit/0b3a5aad5818dd5bc1fd3c6b5c3ada77de85f328 does not work for starlark defined rules. It appears to only work for native rules.

### Feature requests: what underlying problem are you trying to solve with this feature?

All TestRunner actions should have the "test" exec_group

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

An example repo where I have been playing with remote exec & exec_groups is https://github.com/djmarcin/bazel-remote-exec, but the easiest way to reproduce the bug is to attempt to set the "test" exec group on a `rust_test` rule directly and observe the following error:
```
ERROR: Analysis of target '//:hello_rs_test' failed; build aborted: Tried to set properties for non-existent exec groups: test.
```

### What operating system are you running Bazel on?

Linux, macOS

### What's the output of `bazel info release`?

release 4.2.1
or
release 5.0.0-pre.20210831.2

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a

###  Have you found anything relevant by searching the web?

The bazel documentation seems to indicate that this ought to work https://docs.bazel.build/versions/main/exec-groups.html#execution-groups-for-native-rules

### Any other information, logs, or outputs that you want to share?

Issue filed as a result of discussion at https://github.com/bazelbuild/bazel/pull/13110#issuecomment-917345432
@katre

**Comment by djmarcin** [comment]
In addition to the analysis error, the execution log from `--execution_log_json_file=` indicates that setting the exec_properties on the platform does not propagate to these actions unless the rules_rust rust_test is augmented to declare the "test" exec group explicitly, as mentioned on the bazel slack here: https://bazelbuild.slack.com/archives/CA31HN1T3/p1631384272260600

**Comment by katre** [comment]
Thanks, this is definitely an oversight in the implementation.

**Comment by quval** [comment]
Since I've started to draft a patch for this back when @djmarcin first posted a comment on #13110, I thought I might send it as a PR to make sure this makes the cut into Bazel 5. Hope this is all right.

**Comment by katre** [comment]
Thanks very much! I've been overwhelmed with other work and hadn't been able to tackle this, but your approach is exactly what I would have done.

**Comment by quval** [comment]
Glad this helps! Thank you for the prompt feedback.
