### ISSUE TITLE
Regression: Compilation Unnecessarily Restricted By Scheduler in Rolling Release

### ISSUE THREAD

**Issue by cpsauer** [bazelbuild/bazel#13988]
Hey awesome Team Bazel,

There seems to be a regression around parallelism. With the rolling releases, I'm seeing compilation restricted to 2 or 3 threads, with the rest (I think) held up by the scheduler.

Concretely, during build, I'm seeing output like the following, and moderately slower build times to match:
```
bazel build //:rule
INFO: ...<omitted>
[1 / 200] 8 actions, 2 running
    Compiling <...>; 5s darwin-sandbox
    Compiling <...>; 7s darwin-sandbox
    [Sched] Compiling <...>; 24s
    [Sched] Compiling <...>; 24s
    [Sched] Compiling <...>; 24s
    [Sched] Compiling <...>; 24s
    [Sched] Compiling <...>; 24s
    [Sched] Compiling <...>; 24s

```

[My interpretation is that the scheduler is having the jobs wait; please correct me if I'm wrong.]

Setting, e.g. `--jobs=HOST_CPUS` or `--noexperimental_local_memory_estimate` doesn't have any impact. (Hence different from https://github.com/envoyproxy/envoy/issues/12455.) And linking/non-compiling jobs don't seem to count against the lower cap.

With the latest normal release, 4.2.1 and all previous releases I've seen, all cores are utilized, I don't see `[Sched]` and the build runs a bit faster. (But not 4x faster or anything, so the bottleneck is somewhere else--the disk perhaps?)

Version details: I'm seeing this on 5.0.0-pre.20210831.2 (and for all the rolling versions we've tried, which are just those after the release of 4.2). I'm using the latest macOS, 11.6, and I'm seeing it all the way back at least to 10.14.

Thanks so much,
Chris
(ex-Googler)

**Comment by cpsauer** [comment]
Interestingly, it doesn't seem to happen for other compile types, even .mm and .m files (for Apple platforms). It seems to be just cpp compilation

**Comment by benjaminp** [comment]
One might investigate the impact of 4af342870cd5a777701a3188dffcbba82ae737a5.

**Comment by cpsauer** [comment]
Blazingly fast crossref. Thanks, Benjamin!

I think something isn't working as intended here, though. There's more than an order of magnitude more memory available for the job but unused, but we're nonetheless blocking on it.

**Comment by cpsauer** [comment]
Can confirm that the issue is present in the rolling release just after that commit (5.0.0-pre.20210615.3) but not in the one immediately before (5.0.0-pre.20210604.6).  @wilwell, any chance I could ask you to take a peek?

**Comment by wilwell** [comment]
Hi!
It looks like my changes could be the reason for this type of regression. 
To make investigation easier could you please answer following questions:
1) Do you have some small open-source reproducible variant of this regression?
2) How much memory do you have on the machine, which runs this target?
3) Could you please collect more information about Compiling actions, e.g. number of inputs. You could do it using `bazel aquery`.

**Comment by cpsauer** [comment]
Hey all--I gave this quite a good effort on an open-source repro (hence the delay), but couldn't make it happen. That said, it is 100% reproducible across platforms on the repo I can't release :/

So for (1), unfortunately no. It seemed unlikely a toy repo would reproduce it (since we need more compile actions than cores) and there are surprisingly few sizable, open-source C++ repos that build with bazel rolling. But even after some hackery to get, e.g. Tensorflow building, I couldn't reproduce the issue. However, it doesn't seem to be, e.g. just some weird flag in bazelrc--I tried disabling as many of them as I could to no effect. I'm not sure what's triggering the issue.

For (2): 16GB on this machine. Happens with >8GB free, and the memory usage by the actions seems to be negligible. Memory pressure extremely low--though mac does of course make temporary use of that free memory to cache files.

For (3): Definitely. Here's the aquery info for a compile action I saw scheduled. Looks pretty standard to me, though.

```
action 'Compiling Vision/VisionHandle.cpp'
  Mnemonic: CppCompile
  Target: //Vision:VisionHandle
  Configuration: ios-armv7-min9.0-applebin_ios-ios_armv7-opt-ST-f16a07a96057
  Execution platform: @local_config_platform//:host
  ActionKey: 2b2d1e11c2de7da59596aa12520b54640ff584dc6f1caee5b939832b8ed70a1f
  Inputs: [Vision/VisionHandle.cpp, bazel-out/ios-armv7-min9.0-applebin_ios-ios_armv7-opt-ST-f16a07a96057/internal/_middlemen/_S_SVision_CVisionHandle-BazelCppSemantics_build_arch_ios-armv7-min9.0-applebin_ios-ios_armv7-opt-ST-f16a07a96057, external/bazel_tools/tools/cpp/grep-includes.sh, external/local_config_cc/cc_wrapper.sh, external/local_config_cc/libtool, external/local_config_cc/libtool_check_unique, external/local_config_cc/make_hashed_objlist.py, external/local_config_cc/wrapped_clang, external/local_config_cc/wrapped_clang_pp, external/local_config_cc/xcrunwrapper.sh]
  Outputs: [bazel-out/ios-armv7-min9.0-applebin_ios-ios_armv7-opt-ST-f16a07a96057/bin/Vision/_objs/VisionHandle/VisionHandle.d, bazel-out/ios-armv7-min9.0-applebin_ios-ios_armv7-opt-ST-f16a07a96057/bin/Vision/_objs/VisionHandle/VisionHandle.o]
  Environment: [PATH=/bin:/usr/bin:/usr/local/bin]
  ExecutionInfo: {requires-darwin: '', supports-xcode-requirements-set: ''}
  Command Line: (exec external/local_config_cc/wrapped_clang_pp \
    '-D_FORTIFY_SOURCE=1' \
    -fstack-protector \
    -fcolor-diagnostics \
    -Wall \
    -Wthread-safety \
    -Wself-assign \
    -fno-omit-frame-pointer \
    -g0 \
    -O2 \
    -DNDEBUG \
    '-DNS_BLOCK_ASSERTIONS=1' \
    '-std=c++11' \
    'DEBUG_PREFIX_MAP_PWD=.' \
    -iquote \
    . \
    -iquote \
    bazel-out/ios-armv7-min9.0-applebin_ios-ios_armv7-opt-ST-f16a07a96057/bin \
    -iquote \
    external/boost \
    -iquote \
    bazel-out/ios-armv7-min9.0-applebin_ios-ios_armv7-opt-ST-f16a07a96057/bin/external/boost \
    -iquote \
    external/eigen \
    -iquote \
    bazel-out/ios-armv7-min9.0-applebin_ios-ios_armv7-opt-ST-f16a07a96057/bin/external/eigen \
    -iquote \
    external/GBDeviceInfo \
    -iquote \
    bazel-out/ios-armv7-min9.0-applebin_ios-ios_armv7-opt-ST-f16a07a96057/bin/external/GBDeviceInfo \
    -iquote \
    external/GCEM \
    -iquote \
    bazel-out/ios-armv7-min9.0-applebin_ios-ios_armv7-opt-ST-f16a07a96057/bin/external/GCEM \
    -isystem \
    external/boost \
    -isystem \
    bazel-out/ios-armv7-min9.0-applebin_ios-ios_armv7-opt-ST-f16a07a96057/bin/external/boost \
    -isystem \
    external/boost/libs/math/include_private \
    -isystem \
    bazel-out/ios-armv7-min9.0-applebin_ios-ios_armv7-opt-ST-f16a07a96057/bin/external/boost/libs/math/include_private \
    -isystem \
    external/eigen \
    -isystem \
    bazel-out/ios-armv7-min9.0-applebin_ios-ios_armv7-opt-ST-f16a07a96057/bin/external/eigen \
    -MD \
    -MF \
    bazel-out/ios-armv7-min9.0-applebin_ios-ios_armv7-opt-ST-f16a07a96057/bin/Vision/_objs/VisionHandle/VisionHandle.d \
    -DEIGEN_MPL2_ONLY \
    '-DEIGEN_MAX_ALIGN_BYTES=64' \
    '-DEIGEN_HAS_TYPE_TRAITS=0' \
    '-frandom-seed=bazel-out/ios-armv7-min9.0-applebin_ios-ios_armv7-opt-ST-f16a07a96057/bin/Vision/_objs/VisionHandle/VisionHandle.o' \
    -isysroot \
    __BAZEL_XCODE_SDKROOT__ \
    -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks \
    -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/iPhoneOS.platform/Developer/Library/Frameworks \
    '-miphoneos-version-min=9.0' \
    -no-canonical-prefixes \
    -pthread \
    -flto \
    '-std=gnu++17' \
    -fno-aligned-allocation \
    -no-canonical-prefixes \
    -Wno-builtin-macro-redefined \
    '-D__DATE__="redacted"' \
    '-D__TIMESTAMP__="redacted"' \
    '-D__TIME__="redacted"' \
    -target \
    armv7-apple-ios \
    -c \
    Vision/VisionHandle.cpp \
    -o \
    bazel-out/ios-armv7-min9.0-applebin_ios-ios_armv7-opt-ST-f16a07a96057/bin/Vision/_objs/VisionHandle/VisionHandle.o)
  ExecutionInfo: {requires-darwin: '', supports-xcode-requirements-set: ''}
```

**Comment by lingithub1** [comment]
If I understand the consequences of 4af3428 correctly, build steps with (massive) unused inputs are penalized by reduced parallelization. Right?

**Comment by cpsauer** [comment]
Thanks for your conscientiousness, @wilwell.

Is your read of the aquery output (above) that there are a large number of (unused) inputs? I see a short inputs list, but perhaps the heuristic counts, e.g., large numbers of system/library headers, not listed? 

I obviously don't know the internals as well as you do--but want to make sure that this does indeed fall into that case. [Unlike the other issue back linked above (#14092), which seems to explicitly be about the case where a large number of inputs are expected.]

I feel a bit bad that this is ending up on the release blockers list. I thought I should flag the issue and give a heads, but also say honestly that the moderate performance degradation wouldn't stop my team from upgrading.

**Comment by Wyverald** [comment]
It sounds like the regression was fixed already. I'm going to go ahead and remove this from the 5.0 release blockers. If there's further investigation to be done, feel free to continue.

**Comment by gregestren** [comment]
Do we want to keep this open?

**Comment by cpsauer** [comment]
Up to you guys! I'm not sure of the current status of the feature that caused the issue after it got flagged out--probably worth leaving open as needing a fix if the plan is still to roll it forward some day?
