### ISSUE TITLE
Update JaCoCo to 0.8.7

### ISSUE THREAD

**Issue by Kernald** [bazelbuild/bazel#13987]
### Description of the problem / feature request:

JaCoCo is [currently pinned to 0.8.6](https://github.com/bazelbuild/bazel/blob/4b3ed3bd04084dd455aea42f206a9e917ed6dbc0/third_party/java/jacoco/BUILD#L15), which has some issues with Kotlin (I'm currently hitting https://github.com/jacoco/jacoco/issues/1155). It has been fixed in [JaCoCo 0.8.7](https://github.com/jacoco/jacoco/releases/tag/v0.8.7)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try to run `bazel coverage` in some code using kotlinc 1.5 and coroutines.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 4.2.1

###  Have you found anything relevant by searching the web?

https://github.com/jacoco/jacoco/issues/1155

**Comment by cushon** [comment]
We're using 0.8.7 internally and it's been working fine. Note that it still needs the same patches as 0.8.6
