### ISSUE TITLE
Extending loading phase file introspective

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#1399]
We currently try to prototype using Bazel on Windows.
On *nix we mainly use `glob` (on symlinks) in Macros to express dependencies. Porting this to Windows we face some serious problems:

- In loading phase we cannot read files
- Symlinks require special permission combinations that we cannot satisfy.
- Perforce does not support symlinks natively on Windows. They produce a file containing the path to the link target.
- We tried substituting symlinks with hard links but exceeded the 1024 link limit.
- Copying the files works but obviously generates a ton of disk IO.

All this makes encoding dependencies in the file path rather hard.
The working solution that we came up with to encode the symlink via urlencoding:

    parent_dir
    |- child
    |- child.symlink.a%2Furl%2Fencoded%2Fpath

This of course forces us to decode the paths in Skylark.

Now the question is whether it would be possible to lift the loading phase requirements a bit.
For example would it be possible to read the first line of a file to be able to emulate symlinks on Windows (in a way that works with Perforce, too).

**Comment by hermione521** [comment]
@meteorcloudy Can you help with this? Thanks.

**Comment by abergmeier** [comment]
@damienmg Mentioned whether we could perhaps use `filegroup` instead. We are currently giving that a shot.

**Comment by dslomov** [comment]
Reading first line of a file during a loading phase is infeasible, sorry.

**Comment by abergmeier** [comment]
@dslomov Sorry for not updating this. We actually found ways to work around that.
