### ISSUE TITLE
Bazel3.7.2 compiles C++ inference code of tensorflow 2.6.0 to generate so file ，anyway，fail，“cannot use 'throw' with exceptions disabled，cannot use 'try' with exceptions disabled“

### ISSUE THREAD

**Issue by shiyalun** [bazelbuild/bazel#14004]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

>Bazel3.7.2 compiles C++ inference code of tensorflow 2.6.0 to generate so file ，anyway，fail，“abort_wrapper.cc:19:3: error: cannot use 'throw' with exceptions disabled throw std::runtime_error("abort called!");“

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> my code:
#include <new>
#include <stdexcept>
#define CHECK_PTR(PTR) { if(!(PTR)) throw std::bad_alloc(); }
extern "C" {
void __real_abort();
void* __real_calloc(size_t nmemb, size_t size);
void* __real_malloc(size_t size);
void* __real_realloc(void* ptr, size_t size);
void __wrap_abort();
void* __wrap_calloc(size_t nmemb, size_t size);
void* __wrap_malloc(size_t size);
void* __wrap_realloc(void* ptr, size_t size);
}
void __wrap_abort() {
  throw std::runtime_error("abort called!");
}
void* __wrap_calloc(size_t nmemb, size_t size) {
  void *ptr = __real_calloc(nmemb, size);
  CHECK_PTR(ptr);
  return ptr;
}
void* __wrap_malloc(size_t size) {
  void *ptr = __real_malloc(size);
  CHECK_PTR(ptr);
  return ptr;
}
void* __wrap_realloc(void* ptr, size_t size) {
  void *new_ptr = __real_realloc(ptr, size);
  CHECK_PTR(ptr);
  return new_ptr;
}

**Comment by philwo** [comment]
Hi @shiyalun, this seems to be more a question about how to use Bazel to achieve something. I don't think it's a Bazel bug. Could you ask this question on our mailing list instead: https://groups.google.com/g/bazel-discuss? Maybe another user has found a solution for this already.

Thanks,
Philipp

**Comment by shiyalun** [comment]
[image: image.png]

I executed the following command “bazel build //rnn_dict_full:all -s
--cxxopt="-std=c++14" --cxxopt="-D_FORTIFY_SOURCE=2"
--cxxopt="-fpermissive"    --copt="-O2" --copt="-fstack-protector-strong"
 --copt="-fpic"  --copt='-fpie' --copt='-pie' --copt="-enable-bind-now"
 --strip=always  --config=android  --cpu=arm64-v8a
--fat_apk_cpu=arm64-v8a” to generate the SO file, but an error was
reported. Some people said that the parameter
"--experimental_repo_remote_exec" should be added, but other problems
occurred,
,the error is "common/abort_wrapper.cc:22:3: error: cannot use 'throw' with
exceptions disabled
  throw std::runtime_error("abort called!");", my code is below:

#include <new>
#include <stdexcept>

#define CHECK_PTR(PTR) { if(!(PTR)) throw std::bad_alloc(); }

extern "C" {
void __real_abort();
void* __real_calloc(size_t nmemb, size_t size);
void* __real_malloc(size_t size);
void* __real_realloc(void* ptr, size_t size);

void __wrap_abort();
void* __wrap_calloc(size_t nmemb, size_t size);
void* __wrap_malloc(size_t size);
void* __wrap_realloc(void* ptr, size_t size);
}

void __wrap_abort() {
  throw std::runtime_error("abort called!");
}

void* __wrap_calloc(size_t nmemb, size_t size) {
  void *ptr = __real_calloc(nmemb, size);
  CHECK_PTR(ptr);
  return ptr;
}

void* __wrap_malloc(size_t size) {
  void *ptr = __real_malloc(size);
  CHECK_PTR(ptr);
  return ptr;
}

void* __wrap_realloc(void* ptr, size_t size) {
  void *new_ptr = __real_realloc(ptr, size);
  // Technically it breaks spec...
  CHECK_PTR(ptr);
  return new_ptr;
}

**Comment by shiyalun** [comment]
> Hi @shiyalun, this seems to be more a question about how to use Bazel to achieve something. I don't think it's a Bazel bug. Could you ask this question on our mailing list instead: https://groups.google.com/g/bazel-discuss? Maybe another user has found a solution for this already.
> 
> Thanks,
> Philipp

When I compiled SO, the problem occurred, my BUILD configuration and errors are as follows, :
        the error is "common/abort_wrapper.cc:22:3: error: cannot use 'throw' with exceptions disabled
        throw std::runtime_error("abort called!");",

SO uses the following configuration ：
        "-Wl,--wrap=abort",
        "-Wl,--wrap=calloc",
        "-Wl,--wrap=malloc",
        "-Wl,--wrap=realloc",
==========================================================
SO BUILD file:
cc_library(
    name = "rnn_dict_lib",
    srcs = [
        "native/rnn_dict.cc",
        "native/rnn_dict_wrap.cxx",
        "//common:abort_wrapper.cc",
    ],
    hdrs = [
        "native/rnn_dict.h",
    ],
    copts = tflite_copts() + [
        "-ffunction-sections",
        "-fdata-sections",
    ],
    linkopts = if_android([
        "-landroid",
        "-latomic",
        "-ldl",
        "-llog",
        "-lm",
        "-Wl,-z,relro,-z,now",
        "-Wl,--wrap=abort",
        "-Wl,--wrap=calloc",
        "-Wl,--wrap=malloc",
        "-Wl,--wrap=realloc",
        "-z defs",
        "-s",
        "-Wl,--gc-sections",
        "-Wl,--version-script,$(location {})".format(LINKER_SCRIPT),
    ]),
    linkstatic = 1,
    tags = [
        "manual",
        "notap",
    ],
    deps = [
        "//nndriver:nndriver",
        "//common:jni_includes",
        "@org_tensorflow//tensorflow/core:portable_tensorflow_lib",
        "@org_tensorflow//tensorflow/lite:framework",
        "@org_tensorflow//tensorflow/lite:builtin_ops",
        "@org_tensorflow//tensorflow/lite/core/api",
        LINKER_SCRIPT,
    ],
)

cc_binary(
    name = "librnn_dict.so",
    deps = [
        ":rnn_dict_lib",
        LINKER_SCRIPT,
    ],
    linkshared = 1,
)
