### ISSUE TITLE
Bazel can not work in my Mac.

### ISSUE THREAD

**Issue by omercanyigit1** [bazelbuild/bazel#14029]
I have a big problem with about the bazel. I am using the Macos Big Sur with Apple M1 and i can not load the bazel files and it can not find my npm files. Can you help me?

Error:

> ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_omercanyigit/100a58fa745a5d1002a5089e0960865d/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 693, column 31, in _yarn_install_impl
		node = repository_ctx.path(get_node_label(repository_ctx))
Error in path: Unable to load package for @nodejs_darwin_arm64//:bin/node: The repository '@nodejs_darwin_arm64' could not be resolved
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_omercanyigit/100a58fa745a5d1002a5089e0960865d/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 693, column 31, in _yarn_install_impl
		node = repository_ctx.path(get_node_label(repository_ctx))
Error in path: Unable to load package for @nodejs_darwin_arm64//:bin/node: The repository '@nodejs_darwin_arm64' could not be resolved
ERROR: Skipping '//apps/desktop/server:desktop-server-bin': no such package '@npm//@bazel/esbuild': Unable to load package for @nodejs_darwin_arm64//:bin/node: The repository '@nodejs_darwin_arm64' could not be resolved
WARNING: Target pattern parsing failed. 
ERROR: no such package '@npm//@bazel/esbuild': Unable to load package for @nodejs_darwin_arm64//:bin/node: The repository '@nodejs_darwin_arm64' could not be resolved
INFO: Elapsed time: 0.165s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: apps/desktop/server
error Command failed with exit code 1.

**Comment by keith** [comment]
This is an issue with rules nodejs. It looks like this has already been filed as https://github.com/bazelbuild/rules_nodejs/issues/2733 but if the solutions there don't work you should file another issue on that repo

**Comment by oquenchil** [comment]
Thanks Keith.
