### ISSUE TITLE
attribute "build_setting_default" is not configurable

### ISSUE THREAD

**Issue by carlosgalvezp** [bazelbuild/bazel#14022]
Hi,

I want to make the "build_setting_default" of a config_setting configurable based on a select:

```
my_conf = rule(
    implementation = _my_conf_impl,
    build_setting = config.string(flag = True),
)

my_conf(
        name = "my_conf",
        build_setting_default = select({
            "cpu:x86_64": "foo",
            "cpu:aarch64": "bar",
        }),
    )
```
However I get the error:
```
attribute "build_setting_default" is not configurable
```

Why is that? Is there a workaround to achieve what I intend above?

**Comment by gregestren** [comment]
The simple reason is "configurable" means "is a function of the configuration" and a build_setting is a piece of the configuration.

i.e. the configuration includes both `--cpu` and `--my_config`, without guarantees that one is set before the other. So the two can't rely on each other.

What's your larger goal? The pertinent question, I think, is where else you can embed the logic "foo if x86_64 else bar" somewhere that *is* downstream from the configuraiton.

**Comment by sdtwigg** [comment]
It would actually be fairly technically challenging. (In particular, if the requested input build setting of a Starlark-defined transitions is not currently set, the infrastructure will lookup the build_setting_default for that build setting and temporarily explicitly set the transition's input build options set to that value. Similarly, if the output of a transition is changed/still at its defauly, then we actually drop the build setting from the propagated build options set, for consistency purposes. Neither of these mechanisms work well if build_setting_default is configurable.)

In practice, this can usually be worked around by setting the build setting to some sentinel value. Then, consumers (either a select statement on the consuming rule or in the rule implementation itself) are responsible for reading the sentinel value and calculating the true value.

**Comment by gregestren** [comment]
Closing on account of the comments above. But we're happy to continue elaborating on alternative approaches, i.e. the sentinel approach @sdtwigg mentions.

**Comment by GMNGeoffrey** [comment]
I am encountering a similar issue. For concreteness, this is my build file: https://github.com/iree-org/iree/blob/main/runtime/src/iree/hal/drivers/BUILD. I want to enable Cuda by default on some platforms. If `build_setting_default` was configurable, this would be easy:

```starlark
string_list_flag(
    name = "enabled_drivers",
    build_setting_default = [
        "local-sync",
        "local-task",
        "vulkan",
    ] + select({
      ":myspecialconfiguration": ["cuda"],
      "//conditions:default": [],
    }),
)
```

Can you elaborate on how this can be done otherwise? I see the general idea, but it looks like it would involve a sentinel default of `["notarealdriver"]` (seems like empty list could be user-specified?) and then several layers of indirection on top of that...

**Comment by GMNGeoffrey** [comment]
This is the file: https://github.com/iree-org/iree/blob/300335a6fa/runtime/src/iree/hal/drivers/BUILD

We'd like to enable Cuda by default if OS=X, for some value(s) of X.
