### ISSUE TITLE
STAT 545- Group 14

### ISSUE THREAD

**Issue by oftheheavens** [bazelbuild/bazel#14024]
This is an issue created for Exercise 4 for our STAT 545 collaborative project.

I'm trying to test out Github issues and wanting to see how to communicate best with my teammates, as well as introduce myself.

My name is Abigail, and I'm a recent BA (Hons) Psychology grad from UBC. I'm taking STAT 545 because I want to learn more about R, having forgotten most of what I picked up in my undergrad. I hope my skills will be useful in grad school since R is such a powerful analysis tool. 

My research interests involve clinical forensic psychology, psychopathy, and personality disorders. I also do some research in stereotypes and perfectionism as well! Outside of academics, I love to read fiction novels, sing in my choir, and visit new places. Thanks for reading!

Tagging my teammates for ease: 
@asanto0803
@secedie
@jyyin98

**Comment by oftheheavens** [comment]
Editted a line

**Comment by oquenchil** [comment]
Hi Abigail, I believe you meant to file this issue on a different repository so I will close it now. Let me know if I misunderstood the goal of the project and if there is anything we can do to help. Good luck.
