### ISSUE TITLE
pkg_tar documentation inconsistent

### ISSUE THREAD

**Issue by a1k0n** [bazelbuild/bazel#1403]
http://www.bazel.io/docs/be/pkg.html#pkg_tar

The documentation lists the arguments as `pkg_tar(name, extension, *data_path*, *directory*, files, mode, modes, deps, symlinks)` but the documentation below it shows `strip_prefix` and `package_dir`, which is confusing. Which one is it?

**Comment by hermione521** [comment]
Hi,
The variables `strip_prefix` and `package_dir` are also available in the rule. I will add them to the document. Thank you for pointing out :)

**Comment by a1k0n** [comment]
The documentation for `strip_prefix` still refers to `data_path` -- are data_path and directory still arguments of pkg_tar? It looks to me like they were renamed to strip_prefix and package_dir, respectively.

> **strip_prefix**	String, optional
> Root path of the files.
> 
> The directory structure from the files is preserved inside the tarball but a prefix path determined by strip_prefix is removed from the directory structure. This path can be absolute from the workspace root if starting with a / or relative to the rule's directory. A relative path may start with "./" (or be ".") but cannot use ".." to go up level(s). By default, the **data_path** attribute is unused and all files are supposed to have no prefix. A **data_path** of "" (the empty string) means the same as the default.
>

**Comment by hermione521** [comment]
Sorry for the inconvenience. Working on it.

**Comment by a1k0n** [comment]
LGTM, thanks
