### ISSUE TITLE
Drop experimental_multi_threaded_digest

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel#14034]
This options defaults to true since a while and should just be removed, likely with the whole `SsdModule`.

**Comment by bjacklyn** [comment]
@meisterT -- `checking cached actions` now takes 5-6x longer in my local builds after `6ac6954224b2b74c18d3218dfa299424cbc944fb` was merged, that is what used to take 30 seconds for bazel to determine there was nothing to do in an already fully cached build, it now takes 2 mins 30 seconds

**Comment by bjacklyn** [comment]
There used to be a check against this boolean which I assume was defaulting to `true`:
```
-  private static final AtomicBoolean MULTI_THREADED_DIGEST = new AtomicBoolean(false);
...
-    if (fileSize > MULTI_THREADED_DIGEST_MAX_FILE_SIZE && !MULTI_THREADED_DIGEST.get()) {
+    if (fileSize > MULTI_THREADED_DIGEST_MAX_FILE_SIZE) {
       // We'll have to read file content in order to calculate the digest.
       // We avoid overlapping this process for multiple large files, as
       // seeking back and forth between them will result in an overall loss of
       // throughput.
       digest = getDigestInExclusiveMode(path);
     } else {
-      digest = getDigestInternal(path);
+      digest = path.getDigest();
     }
```
But now it always takes the slow path. I revived the fast `checking cached actions` with this:
```
+    if (fileSize > MULTI_THREADED_DIGEST_MAX_FILE_SIZE && !true) {
```

**Comment by meisterT** [comment]
Ouch, that's definitely a mistake. I'm OOO this week but feel free to send a PR to fix the behavior.

cc @Wyverald  this is a release blocker

**Comment by Wyverald** [comment]
Cherrypicks are still open.

**Comment by brentleyjones** [comment]
Should be reopened as it's still blocking 5.0 (needs to be cherry-picked).

**Comment by Wyverald** [comment]
Cherrypicked.
