### ISSUE TITLE
FreeBSD port

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1404]
Main tracking bug for the FreeBSD work by @aehlig .

**Comment by aehlig** [comment]
Related/blocked on #1396

**Comment by aehlig** [comment]
Patches so far in that direction include 2571982bbfdda44b176628e3354527970cb61407, 6dbcc2da5144ad819ef8d219977b4c2fd85852c0, b692917a73e73d05a65979992f87ad93445dee97, and f16397f33108116119e28952660370fc2e9d67a3.

**Comment by ulfjack** [comment]
What's left to do here?

**Comment by damienmg** [comment]
Ci machines to ensure no regression

**Comment by damienmg** [comment]
Closing this issue now there is a CI tests, there is still some progress to run more tests on CI but this should be addressed in a separate bug.
