### ISSUE TITLE
bazel3.7.2 compiles tensorflow2.6.0 error

### ISSUE THREAD

**Issue by shiyalun** [bazelbuild/bazel#14046]
### When I used bazel3.7.2 to compile tensorflow2.6.0, error occurred:

> My command is as follows
> bazel build   //rnn_dict_full:all   --cxxopt="-std=c++14" --cxxopt="-D_FORTIFY_SOURCE=2" --cxxopt="-fpermissive"    --copt="-O2" --copt="-fstack-protector-strong"  --copt="-fpic"  --copt='-fpie' --copt='-pie' --copt="-enable-bind-now"  --strip=always  --config=android  --cpu=arm64-v8a   --fat_apk_cpu=arm64-v8a

### the following error occurred

> ERROR: An error occurred during the fetch of repository 'go_sdk':
   Traceback (most recent call last):
        File "/home/shiyalun/.cache/bazel/_bazel_shiyalun/899e6eb6dd5de290496a7205f1ef1b01/external/io_bazel_rules_go/go/private/sdk.bzl", line 51, column 16, in _go_download_sdk_impl
                _remote_sdk(ctx, [url.format(filename) for url in ctx.attr.urls], ctx.attr.strip_prefix, sha256)
        File "/home/shiyalun/.cache/bazel/_bazel_shiyalun/899e6eb6dd5de290496a7205f1ef1b01/external/io_bazel_rules_go/go/private/sdk.bzl", line 128, column 17, in _remote_sdk
                fail("error extracting Go SDK:\n" + res.stdout + res.stderr)
Error in fail: error extracting Go SDK:
Timed out
ERROR: Analysis of target '//rnn_dict_full:librnn_dict_inference_native' failed; build aborted: error extracting Go SDK:
Timed out
INFO: Elapsed time: 855.532s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (5 packages loaded, 1 target configured)

**Comment by oquenchil** [comment]
Please file an issue on the [Tensorflow repository](https://github.com/tensorflow/tensorflow)
