### ISSUE TITLE
Documentation issue: C   toolchain configuration

### ISSUE THREAD

**Issue by daveb68** [bazelbuild/bazel#14055]
Documentation URL: https://docs.bazel.build/versions/main/cc-toolchain-config-reference.html

                actions = ["ACTION_NAMES.cpp_compile"],

As I understand it, none of these uses of ACTION_NAMES should be in quotes except in the load statement.

**Comment by sgowroji** [comment]
This issue is fixed. Hence we are closing it.Feel free to reach us for any further questions or to reopen this issue.

**Comment by sgowroji** [comment]
Please find the [reference](https://bazel.build/docs/cc-toolchain-config-reference)
