### ISSUE TITLE
`--show_task_finish` does nothing

### ISSUE THREAD

**Issue by simon-swanson-leapyear** [bazelbuild/bazel#14052]
### Description of the problem / feature request:

I'd like to enable [`--show_task_finish`](https://docs.bazel.build/versions/main/command-line-reference.html#flag--show_task_finish) for better output in CI runs, but the flag seems to do nothing at all. This seems like it might be related to this other issue here: https://github.com/bazelbuild/bazel/issues/12133, and when I search for `showTaskFinish` in GitHub (I know, very trustworthy), I see only a declaration and no usages: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/runtime/UiOptions.java#L129.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Navigate to a workspace with tests. Remove your `${WORKSPACE}/.bazelrc` and `${HOME}/.bazelrc`, then run:

```shell
bazel \
    test //... \
    --nocache_test_results \
    --announce_rc \
    --curses=no \
    --show_task_finish
```

Change the last flag to be `--noshow_task_finish` and compare the output. There will be no difference except for the section describing the flags that were set.

### What operating system are you running Bazel on?

MacOS 11.6

### What's the output of `bazel info release`?

```
bazel info release
release 5.0.0-pre.20210817.2
```

###  Have you found anything relevant by searching the web?

Only this:

* Duplicate? https://github.com/bazelbuild/bazel/issues/12133

**Comment by michajlo** [comment]
This just came up for other reasons (looking into flag reduction). Looks like it hasn't worked in over two years, since https://github.com/bazelbuild/bazel/commit/3e9eec42f9523bd835d3185f98e5cacc431bb4bd at least. Might be best to just remove the flag...

**Comment by simon-swanson-leapyear** [comment]
I'd prefer no flag to a non-functional flag personally :)

If the flag is removed, is there any replacement for its functionality? I'd like to see the list of tests that were targeted at a minimum, and was hoping this flag would show me the information I wanted. This may be a question for the mailing list, but I'm trying to solve the case of the totally useless output:

```
$ bazel test //...
...
(07:15:13) Analyzing: 48 targets (0 packages loaded, 0 targets configured)
(07:15:15) INFO: Analyzed 48 targets (0 packages loaded, 13806 targets configured).
(07:15:15) INFO: Found 25 targets and 23 test targets...
(07:15:15) [0 / 366] [Prepa] BazelWorkspaceStatusAction stable-status.txt
(07:15:17) INFO: Elapsed time: 23.013s, Critical Path: 0.56s
(07:15:17) INFO: 24 processes: 24 remote cache hit.
(07:15:17) INFO: Build completed successfully, 24 total actions
Test cases: finished with 417 passing and 0 failing out of 417 test cases

Executed 0 out of 23 tests: 23 tests pass.
(07:15:17) INFO: Build completed successfully, 24 total actions
```

**Comment by michajlo** [comment]
Looks like we agree then :). This has piqued my interested for various reasons, so I'll work on seeing it through (have some internal things to clean up first).

**Comment by simon-swanson-leapyear** [comment]
Awesome, looking forward to it!

For those here looking for more CI output, I've found an ok workaround: `--show_result` with a very large number to show all the targets that were run by the command, and it turns out the `short` test summary prints out more than the `detailed` summary if the tests all passed:

```
common:ci --show_result=100000000
test:ci --test_summary=short
```
