### ISSUE TITLE
FR: Allow "Note" output from javac to be suppressed

### ISSUE THREAD

**Issue by ekuefler** [bazelbuild/bazel#1405]
When Bazel builds a Java target, it very frequently ends up printing lines like this:

```
INFO: From Building src/main/java/com/myapp/libmyapp.jar (81 source files):
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

For a moderately large build, these lines can end up repeated hundreds of times, creating lots of terminal scrolling and noise in the output. It would be nice if there were some way to suppress javac's Note output.

This is really a javac issue rather than a Bazel issue, since javac provides [no good way](http://stackoverflow.com/questions/1858021/suppress-deprecated-import-warning-in-java) to suppress deprecation warnings in general. But Bazel exacerbates the problem by encouraging fine-grained targets where javac is invoked many times per build, so it might be reasonable to do some processing of javac's output within Bazel.

**Comment by cushon** [comment]
Internally we modified javac to stop emitting those deferred notes for unchecked, deprecation, and sunapi. A cleaner option would be to use the javac API (instead of calling its main method) so we can get structured diagnostics back, and filter out the notes. That would also help with #1342.
