### ISSUE TITLE
Upgrade invocation_policy.proto to proto3

### ISSUE THREAD

**Issue by sushain97** [bazelbuild/bazel#14061]
### Description of the problem / feature request:

Please upgrade the `invocation_policy.proto` file to the `proto3` syntax.

It's currently `proto2`:
https://github.com/bazelbuild/bazel/blob/936196a5397ad056a79cfccfc6d436ccb4a3c770/src/main/protobuf/invocation_policy.proto#L15

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm attempting to generate Ruby bindings for the BES protos defined here:
https://github.com/bazelbuild/bazel/blob/936196a5397ad056a79cfccfc6d436ccb4a3c770/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/BUILD#L25-L35

Unfortunately, it doesn't support proto2: https://developers.google.com/protocol-buffers/docs/reference/ruby-generated.
> For the moment only proto3 is supported. Support for proto2 is planned, but not available yet.

Fortunately, this is the only transitive dependency of the BES protos which uses proto2.

**Comment by sushain97** [comment]
Sorry for the late reply -- it took a while to get a new version rolled out. I agree that the stated rationale is no longer valid. Thanks for the pointer!

However, it still seems like it would be good hygiene to have everything in proto3?

Either way, I'll leave it to the maintainers on whether to close this issue or not.

**Comment by coeuvre** [comment]
Thanks for the issue. We cannot simply upgrade it proto3 due internal usages. Closing.
