### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by joshburkart** [bazelbuild/bazel#1406]
Here's my BUILD file:
```python
py_library(
    name="basis",
    srcs=["basis.py"],
    srcs_version="PY3ONLY",
)

py_test(
    name="basis_test",
    srcs=["basis_test.py"],
    deps=[
        ":basis",
    ],
    srcs_version="PY3ONLY",
)
```
Unfortunately, when I execute `bazel test basis_test`, I get
```shell
ERROR: /blah/BUILD:7:1: in py_test rule //blah:basis_test: Rule '//blah:basis_test' can only be used with Python 3, and cannot be converted to Python 2.
ERROR: Analysis of target '//blah:basis_test' failed; build aborted.
INFO: Elapsed time: 1.560s
ERROR: Couldn't start the build. Unable to run tests.
```
Is there an easy workaround? I have Python 3 installed and all. Thanks!

**Comment by hermione521** [comment]
Sorry, we don't have Python 3 support yet. @lberki do we have any workaround?

**Comment by lberki** [comment]
Does adding `--force_python=PY3` to the command line of Bazel work?

**Comment by bsilver8192** [comment]
I've been having success with `default_python_version = "PY3",` on each rule too (in addition to `srcs_version`).

I think `--force_python=PY3 --host_force_python=PY3` should work without needing to set two attributes on each rule, but I haven't actually gotten around to trying it.

**Comment by joshburkart** [comment]
Thanks for the responses! Working great now. Just needed to set `srcs_version = "PY3"` on everything, and `default_python_version = "PY3"` only on tests and binaries.

**Comment by IrynaWilson** [comment]
I am using --force_python=PY3 --host_force_python=PY3 options with the code below, and getting 'Converting to Python 3: failed' error

py_library(
    name = "foo",
    srcs = ["foo.py"],
    srcs_version = "PY3",
)

py_test(
    name = "foo_test",
    srcs = glob(["foo_test.py",]),
    default_python_version = "PY3",
    srcs_version = "PY3",
    deps = [":foo"]
)

I was thinking about trying py_runtime, but haven't been successful yet. Anyone has any solutions to this? I lso have tried --define PYTHON_BIN_PATH=/usr/local/bin/python3 option, and no luck

**Comment by lc0** [comment]
Seems like `force_python=py2` was removed https://github.com/tensorflow/serving/commit/5369880e9143aa00d586ee536c12b04e945a977c#diff-4c3a4e61471476647ad1c0987a744414L4

Does it mean you officially support python 3?
