### ISSUE TITLE
Tests from nested WORKSPACE don't launch

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#14068]
When running a test from a nested workspace they fail to launch because the test-setup script attempts to run an empty string instead of the path to the binary.

This appears to be because this logic is incorrect for this case:
https://github.com/bazelbuild/bazel/blob/fad21dae0b01d5f9b2274542c89f4c8163c2ff36/tools/test/test-setup.sh#L237

Here's some sample output from running this with `set -x`:

```
rlocation envoy_mobile_private/external/envoy_mobile/test/java/org/chromium/net/net_tests
is_absolute envoy_mobile_private/external/envoy_mobile/test/java/org/chromium/net/net_tests
[[ envoy_mobile_private/external/envoy_mobile/test/java/org/chromium/net/net_tests = /* ]]
[[ envoy_mobile_private/external/envoy_mobile/test/java/org/chromium/net/net_tests =~ ^[a-zA-Z]:[/\].* ]]
[[ -e /home/ksmiley/.cache/bazel/_bazel_ksmiley/2c0bea9d21d9871b2474ec5952600519/execroot/envoy_mobile_private/bazel-out/k8-fastbuild/bin/external/envoy_mobile/test/java/org/chromium/net/net_tests.runfiles/envoy_mobile_private/external/envoy_mobile/test/java/org/chromium/net/net_tests ]]
[[ -e /home/ksmiley/.cache/bazel/_bazel_ksmiley/2c0bea9d21d9871b2474ec5952600519/execroot/envoy_mobile_private/bazel-out/k8-fastbuild/bin/external/envoy_mobile/test/java/org/chromium/net/net_tests.runfiles/MANIFEST ]]
 grep '^envoy_mobile_private/external/envoy_mobile/test/java/org/chromium/net/net_tests ' /home/ksmiley/.cache/bazel/_bazel_ksmiley/2c0bea9d21d9871b2474ec5952600519/execroot/envoy_mobile_private/bazel-out/k8-fastbuild/bin/external/envoy_mobile/test/java/org/chromium/net/net_tests.runfiles/MANIFEST
```

I think the binary this is searching for is actually `bazel-out/k8-fastbuild/bin/external/envoy_mobile/test/java/org/chromium/net/net_tests.runfiles/envoy_mobile/test/java/org/chromium/net/net_tests`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

With [envoy-mobile](https://github.com/envoyproxy/envoy-mobile/) run:

```
bazel test @envoy//test/...
```

### What operating system are you running Bazel on?

Ubuntu 20.04

### What's the output of `bazel info release`?

4.1.0

**Comment by keith** [comment]
It looks like the test manifest being grepped in this case has this line:

```
envoy_mobile/test/java/org/chromium/net/net_tests /home/ksmiley/.cache/bazel/_bazel_ksmiley/2c0bea9d21d9871b2474ec5952600519/execroot/envoy_mobile_private/bazel-out/k8-fastbuild/bin/external/envoy_mobile/test/java/org/chromium/net/net_tests
```

But this is missing the `envoy_mobile_private/external` prefix

**Comment by keith** [comment]
RFC https://github.com/bazelbuild/bazel/pull/14069

**Comment by ahumesky** [comment]
Is this still an issue with Starlark android_local_test?
