### ISSUE TITLE
Negative target patterns with toolchain registration

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#14074]
To investigate:

Toolchains (and execution platforms) are currently registered as target patterns. Do we currently allow negative target patterns? Should we?

I.e, given the following BUILD file:
```py
# //toolchains:BUILD
toolchain(name = "A", ...)
toolchain(name = "B", ...)
toolchain(name = "C", ...)
```

Then the following are equivalent currently:
```
register_toolchains('//toolchains:all')
```
and
```
register_toolchains('//toolchains:A', '//toolchains:B', '//toolchains:C')
```

But are these the same:
```
register_toolchains('//toolchains:all', '-//toolchains:B')
```
and
```
register_toolchains('//toolchains:A', '//toolchains:C')
```

**Comment by katre** [comment]
Ping @wyverald, this relates to your recent work on target patterns and toolchain registration.

**Comment by Wyverald** [comment]
What I did in the recent change was: you can pass negative patterns in flags (the PlatformConfiguration stuff), but not in `register_toolchains` calls (it sounds a bit weird to me that a macro could just say `register_toolchains("-//...")` and essentially disable any previous `register_toolchains` calls). Do you think that's fine?

I haven't actually tested whether the negative patterns actually work, though it should be easy to add some unit tests for them.

**Comment by katre** [comment]
Makes sense, thanks for the comments.

**Comment by katre** [comment]
Leaving this issue open, I'm happy to accept PRs, but we won't be prioritizing this in the future.
