### ISSUE TITLE
maven_jar should allow a testonly attribute

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/bazel#1407]
The easiest example is:

maven_jar(
    name = "junit_repo",
    artifact = "junit:junit:4.12",
    testonly = 1, # would be nice to add this
    sha1 = "2973d150c0dc1fefe998f834810d68f278ea58ec",
)

**Comment by kchodorow** [comment]
Closing this in favor of #1410, reimplementing the maven_jar rule in Skylark (which should give us testonly "for free").
