### ISSUE TITLE
Documentation issue: Configuring C   toolchains Fails to build

### ISSUE THREAD

**Issue by johncblacker** [bazelbuild/bazel#14083]
Opened issue by mistake, trying to follow another tutorial:
https://docs.bazel.build/versions/4.2.0/tutorial/cpp.html
Will see if I have any luck with this one.  Tried the cross compile arm toolchain tutorial and got this output:
jb@jb-VirtualBox-dev:~/bazel-tutorial/examples/cpp/main$ bazel build --config=clang_config //main:hello-world
INFO: Analyzed target //main:hello-world (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/jb/bazel-tutorial/examples/cpp/main/BUILD:1:10: Linking main/hello-world failed: (Exit 1): clang failed: error executing command /usr/bin/clang -o bazel-out/k8-fastbuild/bin/main/hello-world bazel-out/k8-fastbuild/bin/main/_objs/hello-world/hello-world.o bazel-out/k8-fastbuild/bin/main/_objs/hello-world/hello-lib.o -Wl,-S

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/ld: bazel-out/k8-fastbuild/bin/main/_objs/hello-world/hello-lib.o: in function `hello::HelloLib::HelloLib(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
hello-lib.cc:(.text+0x21): undefined reference to `operator new(unsigned long)'
/usr/bin/ld: hello-lib.cc:(.text+0x3b): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: hello-lib.cc:(.text+0x63): undefined reference to `operator delete(void*)'
/usr/bin/ld: bazel-out/k8-fastbuild/bin/main/_objs/hello-world/hello-lib.o: in function `hello::HelloLib::greet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
hello-lib.cc:(.text+0x8b): undefined reference to `std::cout'
/usr/bin/ld: hello-lib.cc:(.text+0x97): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: hello-lib.cc:(.text+0xa9): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
/usr/bin/ld: hello-lib.cc:(.text+0xb5): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: hello-lib.cc:(.text+0xbe): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&)'
/usr/bin/ld: hello-lib.cc:(.text+0xc7): undefined reference to `std::ostream::operator<<(std::ostream& (*)(std::ostream&))'
/usr/bin/ld: bazel-out/k8-fastbuild/bin/main/_objs/hello-world/hello-lib.o: in function `__cxx_global_var_init':
hello-lib.cc:(.text.startup+0xf): undefined reference to `std::ios_base::Init::Init()'
/usr/bin/ld: hello-lib.cc:(.text.startup+0x15): undefined reference to `std::ios_base::Init::~Init()'
/usr/bin/ld: bazel-out/k8-fastbuild/bin/main/_objs/hello-world/hello-lib.o:(.eh_frame+0x2ab): undefined reference to `__gxx_personality_v0'
/usr/bin/ld: bazel-out/k8-fastbuild/bin/main/_objs/hello-world/hello-world.o: in function `main':
hello-world.cc:(.text+0x25): undefined reference to `std::allocator<char>::allocator()'
/usr/bin/ld: hello-world.cc:(.text+0x37): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/usr/bin/ld: hello-world.cc:(.text+0x57): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/usr/bin/ld: hello-world.cc:(.text+0x60): undefined reference to `std::allocator<char>::~allocator()'
/usr/bin/ld: hello-world.cc:(.text+0x73): undefined reference to `std::allocator<char>::allocator()'
/usr/bin/ld: hello-world.cc:(.text+0x88): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/usr/bin/ld: hello-world.cc:(.text+0x96): undefined reference to `std::allocator<char>::~allocator()'
/usr/bin/ld: hello-world.cc:(.text+0xb1): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(char const*)'
/usr/bin/ld: hello-world.cc:(.text+0xd7): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/usr/bin/ld: hello-world.cc:(.text+0xe0): undefined reference to `std::allocator<char>::~allocator()'
/usr/bin/ld: hello-world.cc:(.text+0xf5): undefined reference to `std::allocator<char>::~allocator()'
/usr/bin/ld: hello-world.cc:(.text+0x10a): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/usr/bin/ld: hello-world.cc:(.text+0x131): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/usr/bin/ld: bazel-out/k8-fastbuild/bin/main/_objs/hello-world/hello-world.o: in function `__clang_call_terminate':
hello-world.cc:(.text.__clang_call_terminate[__clang_call_terminate]+0x2): undefined reference to `__cxa_begin_catch'
/usr/bin/ld: hello-world.cc:(.text.__clang_call_terminate[__clang_call_terminate]+0xb): undefined reference to `std::terminate()'
/usr/bin/ld: bazel-out/k8-fastbuild/bin/main/_objs/hello-world/hello-world.o: in function `std::default_delete<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*) const':
hello-world.cc:(.text._ZNKSt14default_deleteIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEclEPS6_[_ZNKSt14default_deleteIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEclEPS6_]+0x27): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/usr/bin/ld: hello-world.cc:(.text._ZNKSt14default_deleteIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEclEPS6_[_ZNKSt14default_deleteIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEclEPS6_]+0x33): undefined reference to `operator delete(void*)'
/usr/bin/ld: bazel-out/k8-fastbuild/bin/main/_objs/hello-world/hello-world.o:(.eh_frame+0x1cb): undefined reference to `__gxx_personality_v0'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //main:hello-world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.709s, Critical Path: 0.34s
INFO: 3 processes: 2 internal, 1 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by oquenchil** [comment]
Please if you still need support, ask on StackOverflow. Thank you.
