### ISSUE TITLE
Annotation Processor does not run on a resources change.

### ISSUE THREAD

**Issue by bdleitner** [bazelbuild/bazel#14095]
### Description of the problem / feature request:

I have an annotation processor that looks up files (expected to be included via `resources`) and uses them to generate code. 
When the content of the `resources` directory changes, the `java_library` target on which the plugin is applied does not rebuild, so the generated code is not updated.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

[Minimal Example](https://github.com/bdleitner/annotation_processor_staleness_demo)

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 4.2.1

###  Have you found anything relevant by searching the web?

I have found some other issues about the difficulty of accessing resources "properly" from the annotation processor (hence the `new File("").getAbsolutePath()` approach, but this seems orthogonal to the `java_library's `resources` changing not triggering a rebuild.

I haven't found anything about this specific issue.

**Comment by comius** [comment]
This looks like correctness issue. @cushon wdyt?

**Comment by cushon** [comment]
> This looks like correctness issue

From the comment in the other bug, my understanding is that the repro is reading files outside the build directory, so this isn't an annotation processing specific correctness issue: https://github.com/bazelbuild/bazel/issues/12964#issuecomment-939564367

I think this would be prevented by sandboxing?

**Comment by bdleitner** [comment]
> From the comment in the other bug, my understanding is that the repro is reading files outside the build directory, so this isn't an annotation processing specific correctness issue: [#12964 (comment)](https://github.com/bazelbuild/bazel/issues/12964#issuecomment-939564367)
> 
> I think this would be prevented by sandboxing?

It is true that, because the processor cannot read the resources directly, I am reading from outside the build directory, but the files I read from are a copy of those from the resources directory which are included using the resources element.  So when the resources glob changes those files do change, but a rebuild is not triggered so the annotation processor is not triggered to run.

If we were able to read the resources directly (#12964) I suspect the same problem might occur as if those changes don't cause the processor to run now, they still wouldn't even if the processor code read from a different location.

**Comment by cushon** [comment]
If the FR in #12964 was implemented, it would be by making the resources inputs to the action, so Bazel would track changes to those files and rerun the action when they changed. Currently they aren't inputs to the action, and while it's still possible to read them by going through the local filesystem and looking outside the build directory, Bazel don't consider them inputs to this action.

I think this is WAI, and an expected consequence of #12964 not being supported.

**Comment by bdleitner** [comment]
Ok, so functionally this is a dupe of #12964.
