### ISSUE TITLE
action sandbox elides empty directories from tree artifacts

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/bazel#14094]
### Description of the problem / feature request:

I happened upon a tree artifact edge case involving empty directories.

Consider two tree artifacts, `treeA` and `treeB`.  Both contain an empty directory named `empty`, but `treeB` also contains a file named `dummy`.

```console
$ tree tree*
treeA
└── empty
treeB
├── dummy
└── empty
```

When these tree artifacts are provided as inputs to a sandboxed action, Bazel elides the empty directory from `treeB`.  If, however, a tree artifact's only content is an empty directory, then the empty directory appears in the action's sandbox. A `find -L .` in a genrule having both `treeA` and `treeB` reports the following to stdout:

```console
.
./external
./external/bazel_tools
./external/bazel_tools/tools
./external/bazel_tools/tools/genrule
./external/bazel_tools/tools/genrule/genrule-setup.sh
./bazel-out
./bazel-out/k8-fastbuild
./bazel-out/k8-fastbuild/bin
./bazel-out/k8-fastbuild/bin/treeA
./bazel-out/k8-fastbuild/bin/treeA/empty
./bazel-out/k8-fastbuild/bin/treeB
./bazel-out/k8-fastbuild/bin/treeB/dummyfile
```

(Observe that `treeB/empty` is missing.)

#### Motivation

I'm trying to implement `pkg_tree` in `rules_pkg` (https://github.com/bazelbuild/rules_pkg/issues/388) but my test cases fail because something in spawn/sandbox-land is eating my empty input directories.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See repro at https://github.com/beasleyr-vmw/repro-treeartifact-emptysubdir

### What operating system are you running Bazel on?

CentOS 8

### What's the output of `bazel info release`?

`release 4.2.1`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a

###  Have you found anything relevant by searching the web?

The following appear to be somewhat related.
- https://github.com/bazelbuild/bazel/issues/1928
- https://github.com/bazelbuild/bazel/commit/3f008a0bec454a9f83415b5f23ddd7c710e25b7c

**Comment by larsrc-google** [comment]
@alexjski  What is the proper behaviour for tree artifacts wrt empty directories?

**Comment by alexjski** [comment]
> @alexjski What is the proper behaviour for tree artifacts wrt empty directories?

I would say that we should create those empty directories to be in parity with `local` execution. I think that we can have problems with tree artifacts which are generated remotely -- I am not sure if we always have non-files in those.

**Comment by coeuvre** [comment]
Sorry I missed the notification. For remote execution, [only files are downloaded](https://github.com/bazelbuild/bazel/blob/40c69ed1bb03d443dfbe27169cbdd90fce37abb4/src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java#L1019-L1027), empty directories are not downloaded.
