### ISSUE TITLE
Is here a way to just somply run a shell command in bzl function?

### ISSUE THREAD

**Issue by 424778940z** [bazelbuild/bazel#14103]
let's say i have list of strings needs to be printed out. (I now there is print() but that's not the point)
I read all documents but just can't figure out a way to do it directly.
Both `ctx.actions.run_shell` and `ctx.actions.run` REQUIRES an output attr.

```Starlark
def _cc_library_headers_impl(ctx):

    for x in ctx.attr.deps:
        for y in x[CcInfo].compilation_context.headers.to_list():
            #How to do following from shell? (Linux)
            print('{}/{}'.format(ctx.attr.path_include_root, y.short_path))

cc_library_headers = rule(
    implementation = _cc_library_headers_impl,
    attrs = {
        "deps": attr.label_list(),
        "header_only": attr.bool(default=True),
        "path_include_root": attr.string(default="_install")
    },
)
```

**Comment by gregestren** [comment]
@424778940z you may also want to try one of the user support channels at docs.bazel.build (see bottom of the page for the list) for community response.

**Comment by brandjon** [comment]
Closing as not-a-bug. FYI, you can't have a rule or macro that dispatches to another process and then resumes Starlark control flow -- that would break hermeticity, incrementality, etc. You can have a rule that registers actions that, when run at execution time, invoke shell scripts. That's done via `run_shell`.
