### ISSUE TITLE
Confusion about the logs when running two identical builds in parallel

### ISSUE THREAD

**Issue by ljiang-dev** [bazelbuild/bazel#14104]
### Description of the problem / feature request:

When running two identical bazel builds in parallel, the log output show that they both had the same number of remote cache hits. The builds were run on separate machines. The previous understanding was that two parallel builds would be able to download off each other at the action granularity, and that this would translate to remote cache hits. This lead to the expectation that the number of remote cache hits logged on each build should be different, which wasn't the case. 

This was tested by invalidating the cache, running `bazel clean` and building the same targets on two machines in parallel.   Metrics from the remote cache for these builds showed that the cache was being hit. 

### Feature requests: what underlying problem are you trying to solve with this feature?

I would like to understand the behaviour described above.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build the same target on two separate machines in parallel configured with the same remote cache and observe the logs.

**Comment by ulrfa** [comment]
Is the issue occurring only when running in parallel on separate machines? Do you get more hits if:
- Running in sequence on separate machines?
- Running in parallel on same machine?
- Running in sequence on same machine, without `bazel clean` in between? (to get hits from local workspace cache)

Have you changed default values for any cache related settings? E.g. `--remote_upload_local_results` or `--experimental_remote_cache_async`?

**Comment by coeuvre** [comment]
In theory, there is no guarantee to for the two builds to have same cache hits. Can you provide a repro or some logs from your setup so we can investigate more?

**Comment by coeuvre** [comment]
Please reopen if you have a concrete repro case.
