### ISSUE TITLE
Offer buildozer fix for missing C/C++ headers

### ISSUE THREAD

**Issue by malkia** [bazelbuild/bazel#14102]
Bazel detects C/C++ include problems, which is great, wondering if this can go further and offer automatically a buildozer command-line that if executed would fix the file? For example as done here for Java jar issues - 

https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/dependency/DependencyModule.java#L351

(reference for the IncludeProblems):
https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/main/java/com/google/devtools/build/lib/rules/cpp/IncludeProblems.java#L40

**Comment by gregestren** [comment]
Interesting idea. I'd think the next step would be to clarify how formally we want to support/reference buildozer in core Bazel messaging.

**Comment by gregestren** [comment]
But I agree with the general principle of making errors as clear, actionable, and fixable as possible.
