### ISSUE TITLE
How to use protobuf well-known types in Bazel 4.2.1

### ISSUE THREAD

**Issue by vsramadanov** [bazelbuild/bazel#14101]
### Problem description

I'd like to use google protobuf + bazel to set up communication between C++ and python parts of my program. I've got the following WORKSPACE file:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_google_protobuf",
    strip_prefix = "protobuf-master",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/master.zip"],
)
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
protobuf_deps()
```
and the BUILD file:
```
load("@com_google_protobuf//:protobuf.bzl", "cc_proto_library")
load("@com_google_protobuf//:protobuf.bzl", "py_proto_library")

cc_proto_library(
    name = "container_cc_proto",
    srcs = ["container.proto"],
    visibility = ["//visibility:public"],
    deps = ["@com_google_protobuf//:any_proto",],
)

py_proto_library(
    name = "container_py_proto",
    srcs = ["container.proto"],
    visibility = ["//visibility:public"],
    deps = ["@com_google_protobuf//:any_proto",],
)
```
The container.proto tries to `include "google/protobuf/any.proto"`. On my command `bazel build //:container_cc_proto` I see the following error:
```
ERROR: /home/*user*/sandbox/bypass/BUILD:31:17: no such target '@com_google_protobuf//:any_proto_genproto': target 'any_proto_genproto' not declared in package '' defined by /home/*some path*/external/com_google_protobuf/BUILD and referenced by '//:container_cc_proto_genproto'
```
Could anyone please tell me how to include any.proto correctly, or any other known workarounds. Thanks!

### What operating system are you running Bazel on?

> Ubuntu 20.04.2

### What's the output of `bazel info release`?

> release 4.2.1

**Comment by vsramadanov** [comment]
no, I haven't. Do you think it would be better to ask on the protobuf side?

**Comment by vsramadanov** [comment]
moreover, the officially provided example https://github.com/cgrushko/proto_library fails to build with bazel 4.2.1:
```
proto_library$ bazel build //src:person_cc_proto 
ERROR: *some path*/external/com_google_protobuf/BUILD:1006:21: in proto_lang_toolchain rule @com_google_protobuf//:cc_toolchain: '@com_google_protobuf//:cc_toolchain' does not have mandatory provider 'ProtoInfo'.
```
Other proto targets compile OK.

please keep all documentation updated!

**Comment by gregestren** [comment]
Hi @vsramadanov. I don't think this issue refers to a bug or feature request for Bazel. I agree with @aiuto about routing your question to https://github.com/protocolbuffers or https://github.com/cgrushko/proto_library, or possibly https://stackoverflow.com/questions/tagged/bazel for better user support help.

I'll close this bug accordingly, but if you think you need more direct support here happy to re-open.
