### ISSUE TITLE
bazel build onos failed

### ISSUE THREAD

**Issue by Amazing8** [bazelbuild/bazel#14112]
ubuntu18046@ubuntu:~/onos_v1/onos$ bazel build onos --action_env=HTTP_PROXY=$HTTP_PROXY
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...
INFO: Analyzed target //:onos (1675 packages loaded, 53313 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /home/ubuntu18046/.cache/bazel/_bazel_ubuntu18046/d738dbe5c37e5b9bdb6f90a405b43c7c/sandbox
[243 / 594] checking cached actions
INFO: From Compiling TypeScript (prodmode) //web/gui2/src/main/webapp/app/view/processor:gui2-view-processor:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (devmode) //web/gui2/src/main/webapp/app/view/apps:gui2-view-apps:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (devmode) //web/gui2/src/main/webapp/app/view/link:gui2-view-link:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (devmode) //web/gui2/src/main/webapp/app/view/flow:gui2-view-flow:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (devmode) //web/gui2/src/main/webapp/app/view/processor:gui2-view-processor:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (devmode) //web/gui2/src/main/webapp/app/view/device:gui2-view-device:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (devmode) //apps/yang-gui/yang-gui2-lib:yang-gui2-lib:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (devmode) //web/gui2/src/main/webapp/app/view/host:gui2-view-host:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (devmode) //web/gui2/src/main/webapp/app/view/cluster:gui2-view-cluster:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (devmode) //web/gui2/src/main/webapp/app/view/meter:gui2-view-meter:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (devmode) //web/gui2/src/main/webapp/app/view/group:gui2-view-group:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (prodmode) //web/gui2-topo-lib:gui2-topo-lib:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (devmode) //web/gui2/src/main/webapp/app/view/settings:gui2-view-settings:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (devmode) //web/gui2/src/main/webapp/app/view/port:gui2-view-port:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (prodmode) //web/gui2/src/main/webapp/app/view/partition:gui2-view-partition:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (devmode) //web/gui2/src/main/webapp/app/view/intent:gui2-view-intent:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (devmode) //web/gui2/src/main/webapp/app/view/partition:gui2-view-partition:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (devmode) //web/gui2/src/main/webapp/app/view/pipeconf:gui2-view-pipeconf:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (devmode) //apps/roadm/web/roadm-gui:roadm-gui:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (devmode) //web/gui2-topo-lib:gui2-topo-lib:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (devmode) //web/gui2/src/main/webapp/app/view/tunnel:gui2-view-tunnel:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (devmode) //apps/faultmanagement/fm-gui2-lib:fm-gui2-lib:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (prodmode) //web/gui2/src/main/webapp/app/view/port:gui2-view-port:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (prodmode) //web/gui2/src/main/webapp/app/view/meter:gui2-view-meter:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (prodmode) //web/gui2/src/main/webapp/app/view/host:gui2-view-host:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (prodmode) //web/gui2/src/main/webapp/app/view/intent:gui2-view-intent:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (prodmode) //web/gui2/src/main/webapp/app/view/link:gui2-view-link:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (prodmode) //web/gui2/src/main/webapp/app/view/cluster:gui2-view-cluster:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (prodmode) //web/gui2/src/main/webapp/app/view/apps:gui2-view-apps:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (prodmode) //web/gui2/src/main/webapp/app/view/pipeconf:gui2-view-pipeconf:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (devmode) //web/gui2/src/main/webapp/app:app:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (prodmode) //web/gui2/src/main/webapp/app:app:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (prodmode) //apps/roadm/web/roadm-gui:roadm-gui:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (prodmode) //web/gui2/src/main/webapp/app/view/device:gui2-view-device:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (prodmode) //web/gui2/src/main/webapp/app/view/tunnel:gui2-view-tunnel:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (prodmode) //apps/faultmanagement/fm-gui2-lib:fm-gui2-lib:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (prodmode) //web/gui2/src/main/webapp:gui2:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (prodmode) //web/gui2/src/main/webapp/app/view/group:gui2-view-group:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (prodmode) //web/gui2/src/main/webapp/app/view/settings:gui2-view-settings:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (prodmode) //apps/inbandtelemetry/intApp-gui2/intApp:intapp-gui2-lib:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Compiling TypeScript (prodmode) //apps/yang-gui/yang-gui2-lib:yang-gui2-lib:
(node:25) ExperimentalWarning: The fs.promises API is experimental
INFO: From Generating Descriptor Set proto_library @com_github_onosproject_onos_topo//:topo_device_proto:
external/com_github_onosproject_onos_topo: warning: directory does not exist.
INFO: From Generating Java (Immutable) proto_library @com_github_onosproject_onos_topo//:topo_device_proto:
external/com_github_onosproject_onos_topo: warning: directory does not exist.
INFO: From Building utils/misc/libonlab-misc-native-class.jar (206 source files):
utils/misc/src/main/java/org/onlab/util/RichComparable.java:25: warning: [ComparableType] Type of Comparable (T) is not the same as implementing class (RichComparable<T>).
public interface RichComparable<T> extends Comparable<T> {
       ^
    (see https://errorprone.info/bugpattern/ComparableType)
ERROR: /home/ubuntu18046/onos_v1/onos/BUILD:52:8: Executing genrule //:onos-karaf failed (Exit 126): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: tools/package/onos-prep-karaf: Permission denied
Target //:onos failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 696.769s, Critical Path: 132.01s
INFO: 79 processes: 4 internal, 66 linux-sandbox, 9 worker.
FAILED: Build did NOT complete successfully

**Comment by gregestren** [comment]
I'm not sure what onos is, but I think this would be better served asking in that project. Closing accordingly.
