### ISSUE TITLE
macOS ar make error

### ISSUE THREAD

**Issue by wenshiqi0** [bazelbuild/bazel#14118]
### Description of the problem / feature request:

bazel build cpp project with musl, but ar make error.

ERROR: /Users/munong/Documents/wasm/web-container/third_party/musl/BUILD:3:11: Linking third_party/musl/libwasm.a failed: (Exit 1): ar failed: error executing command /usr/bin/ar rcsD bazel-out/wasm-fastbuild/bin/third_party/musl/libwasm.a bazel-out/wasm-fastbuild/bin/third_party/musl/_objs/wasm/strlen.o

### Feature requests: what underlying problem are you trying to solve with this feature?

I think the ar default options is not right, or maybe my xcode verision is little bit old.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have a cc_binary and a cc_library, and cc_library to compile musl libc. Also I use clang to compile to wasm.

### What operating system are you running Bazel on?

macOS Catalina 10.15.7

### What's the output of `bazel info release`?

INFO: Analyzed target //kernal:core.wasm (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/munong/Documents/wasm/web-container/third_party/musl/BUILD:3:11: Linking third_party/musl/libwasm.a failed: (Exit 1): ar failed: error executing command /usr/bin/ar rcsD bazel-out/wasm-fastbuild/bin/third_party/musl/libwasm.a bazel-out/wasm-fastbuild/bin/third_party/musl/_objs/wasm/strlen.o

Use --sandbox_debug to see verbose messages from the sandbox
/Library/Developer/CommandLineTools/usr/bin/ar: illegal option -- D
usage:  ar -d [-TLsv] archive file ...
        ar -m [-TLsv] archive file ...
        ar -m [-abiTLsv] position archive file ...
        ar -p [-TLsv] archive [file ...]
        ar -q [-cTLsv] archive file ...
        ar -r [-cuTLsv] archive file ...
        ar -r [-abciuTLsv] position archive file ...
        ar -t [-TLsv] archive [file ...]
        ar -x [-ouTLsv] archive [file ...]
Target //kernal:core.wasm failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.150s, Critical Path: 0.05s
INFO: 2 processes: 2 internal.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

bazel 4.2.1-homebrew 

### Any other information, logs, or outputs that you want to share?

I use cc_toolchain_config to replace compiler to clang, the config is below

load("@bazel_tools//tools/build_defs/cc:action_names.bzl", "ACTION_NAMES")

load(
    "@bazel_tools//tools/cpp:cc_toolchain_config_lib.bzl",
    "feature",
    "flag_group",
    "flag_set",
    "tool_path",
    "action_config",
    "tool",
    "with_feature_set",
)

all_compile_actions = [
    ACTION_NAMES.c_compile,
    ACTION_NAMES.cpp_compile,
    ACTION_NAMES.linkstamp_compile,
    ACTION_NAMES.assemble,
    ACTION_NAMES.preprocess_assemble,
    ACTION_NAMES.cpp_header_parsing,
    ACTION_NAMES.cpp_module_compile,
    ACTION_NAMES.cpp_module_codegen,
    ACTION_NAMES.clif_match,
    ACTION_NAMES.lto_backend,
]

all_link_actions = [
    ACTION_NAMES.cpp_link_executable,
    ACTION_NAMES.cpp_link_dynamic_library,
    ACTION_NAMES.cpp_link_nodeps_dynamic_library,
]

all_ar_actions = [
    ACTION_NAMES.cpp_link_static_library,
]

def _impl(ctx):
    tool_paths = [
        tool_path(name = "gcc", path = "/usr/local/opt/llvm/bin/clang"),
        tool_path(name = "cpp", path = "/usr/bin/cpp"),
        tool_path(name = "ld", path = "/usr/bin/ld"),
        tool_path(name = "compat-ld", path = "/usr/bin/ld"),
        tool_path(name = "objdump", path = "/usr/bin/objdump"),
        tool_path(name = "ar", path = "/usr/bin/ar"),
        tool_path(name = "gcov", path = "/usr/bin/gcov"),
        tool_path(name = "nm", path = "/usr/bin/nm"),
        tool_path(name = "dwp", path = "/usr/bin/dwp"),
        tool_path(name = "objcopy", path = "/usr/bin/objcopy"),
        tool_path(name = "strip", path = "/usr/bin/strip"),
    ]

    action_configs = []

    features = [
        feature(
            name = "wasm_compile",
            enabled = True,
            flag_sets = [
                flag_set(
                    actions = all_compile_actions + all_link_actions,
                    flag_groups = ([
                        flag_group(
                            flags = [
                                "--target=wasm32",
                                "-nostdlib",
                                "-Wl,--no-entry",
                                "-Wl,--export-all",
                            ],
                        ),
                    ]),
                ),
            ],
        ),
    ]

    return cc_common.create_cc_toolchain_config_info(
        ctx = ctx,
        features = features,
        tool_paths = tool_paths,
        action_configs = action_configs,
        toolchain_identifier = "wasm-toolchain",
        host_system_name = "wasm",
        target_system_name = "wasm",
        target_cpu = "wasm",
        target_libc = "unknown",
        compiler = "clang",
        abi_version = "unknown",
        abi_libc_version = "unknown",
    )

cc_toolchain_config = rule(
    implementation = _impl,
    attrs = {},
    provides = [CcToolchainConfigInfo],
)

Is there any way I can change the ar action params?

**Comment by alejandroarmas** [comment]
Hi @wenshiqi0 , 

I'm running into the same problem. Do you have an example of how you added the `archiver_flags` feature? Thanks in advance!

**Comment by alejandroarmas** [comment]
Ok I was able to redefine the 'archiver_flags` feature and get compilation working for my custom toolchain.

My `toolchain/BUILD` file:
```
cc_toolchain_config(
    name = "k8_toolchain_config",
    archive_flags = [],
)
```

My `toolchain/cc_toolchain_config.bzl`:

```
load("@bazel_tools//tools/build_defs/cc:action_names.bzl", "ACTION_NAMES")
load(
     "@bazel_tools//tools/cpp:cc_toolchain_config_lib.bzl",
     "feature",
     "flag_group",
     "flag_set",
     "tool_path",
     "variable_with_value",
     "with_feature_set",
 )

all_link_actions = [ # NEW
     ACTION_NAMES.cpp_link_executable,
     ACTION_NAMES.cpp_link_dynamic_library,
     ACTION_NAMES.cpp_link_nodeps_dynamic_library,
 ]


def _impl(ctx):

    print(ctx.attr.my_custom_string)

    tool_paths = [
        tool_path(
            name = "gcc",
            path = "/opt/opencilk/bin/clang++"
        ),
        tool_path(
            name = "ld",
            path = "/usr/bin/ld",
        ),
        tool_path(
            name = "ar",
            path = "/usr/bin/ar",
        ),
        tool_path(
            name = "cpp",
            path = "/bin/false",
        ),
        tool_path(
            name = "gcov",
            path = "/bin/false",
        ),
        tool_path(
            name = "nm",
            path = "/bin/false",
        ),
        tool_path(
            name = "objdump",
            path = "/bin/false",
        ),
        tool_path(
            name = "strip",
            path = "/bin/false",
        ),
    ]

    archiver_flags_feature = feature(
        name = "archiver_flags",
        flag_sets = [
            flag_set(
                actions = [ACTION_NAMES.cpp_link_static_library],
                flag_groups = [
                    flag_group(flags = ["rcs"]),
                    flag_group(
                        flags = ["%{output_execpath}"],
                        expand_if_available = "output_execpath",
                    ),
                ],
                with_features = [
                    with_feature_set(
                        not_features = ["libtool"],
                    ),
                ],
            ),
            flag_set(
                actions = [ACTION_NAMES.cpp_link_static_library],
                flag_groups = [
                    flag_group(flags = ["-static", "-s"]),
                    flag_group(
                        flags = ["-o", "%{output_execpath}"],
                        expand_if_available = "output_execpath",
                    ),
                ],
                with_features = [
                    with_feature_set(
                        features = ["libtool"],
                    ),
                ],
            ),
            flag_set(
                actions = [ACTION_NAMES.cpp_link_static_library],
                flag_groups = [
                    flag_group(
                        iterate_over = "libraries_to_link",
                        flag_groups = [
                            flag_group(
                                flags = ["%{libraries_to_link.name}"],
                                expand_if_equal = variable_with_value(
                                    name = "libraries_to_link.type",
                                    value = "object_file",
                                ),
                            ),
                            flag_group(
                                flags = ["%{libraries_to_link.object_files}"],
                                iterate_over = "libraries_to_link.object_files",
                                expand_if_equal = variable_with_value(
                                    name = "libraries_to_link.type",
                                    value = "object_file_group",
                                ),
                            ),
                        ],
                        expand_if_available = "libraries_to_link",
                    ),
                ],
            ),
            flag_set(
                actions = [ACTION_NAMES.cpp_link_static_library],
                flag_groups = ([
                    flag_group(
                        flags = ctx.attr.archive_flags,
                    ),
                ] if ctx.attr.archive_flags else []),
            ),
        ],
    )

    features = [
         feature(
             name = "default_linker_flags",
             enabled = True,
             flag_sets = [
                 flag_set(
                     actions = all_link_actions,
                     flag_groups = ([
                         flag_group(
                             flags = [
                                "-lstdc++",
                             ],
                         ),
                     ]),
                 ),
             ],
         ),
     ]

    return cc_common.create_cc_toolchain_config_info(
        ctx = ctx,
        features = features + [archiver_flags_feature],
        cxx_builtin_include_directories = [
            "/opt/opencilk/lib/clang/14.0.6/include",
            "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk",
        ],
        builtin_sysroot = "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk",
        toolchain_identifier = "k8-toolchain",
        host_system_name = "local",
        target_system_name = "local",
        target_cpu = "k8",
        target_libc = "unknown",
        compiler = "clang",
        abi_version = "unknown",
        abi_libc_version = "unknown",
        tool_paths = tool_paths,
    )

cc_toolchain_config = rule(
    implementation = _impl,
    attrs = {
        "archive_flags": attr.string_list(),
        },    
    provides = [CcToolchainConfigInfo],
)
```

**Comment by keith** [comment]
Updating Xcode if you can is the right solution.

**Comment by alejandroarmas** [comment]
Thanks for the help @Keith, it's not obvious to me why that would be the right solution. Do you mind giving a simple explanation? Thanks!

**Comment by keith** [comment]
Actually I got this confused with a different issue. The problem is macOS `ar` doesn't support the `D` flag but that's the default in some cases with the default unix toolchain. I think the intent is that you use libtool instead on macOS, but maybe this condition isn't hitting:

https://github.com/bazelbuild/bazel/blob/1620b6eb0f19ef60a87ede9eb7b69ce5d0ee78ce/tools/cpp/unix_cc_toolchain_config.bzl#L1210

You can attempt to pass `--features=libtool` to force things 🤔
