### ISSUE TITLE
Distributed caching: hazelcast_node argument does nothing

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#1412]
Consider this repository. https://github.com/dfabulich/hazelcast-test

It has two targets, one artificially slow target, and another target that depends on it.

```python
genrule(
	name='x',
	outs=['x.txt'],
	cmd='sleep 5; echo hello > $@',
)

genrule(
	name='y',
	srcs=['x'],
	outs=['y.txt'],
	cmd='cp $(location x) $@',
)
```

`tools/bazel.rc` instructs it to use a hazelcast node for distributed artifact caching, following the instructions here: https://raw.githubusercontent.com/bazelbuild/bazel/79adf59e2973754c8c0415fcab45cd58c7c34697/src/main/java/com/google/devtools/build/lib/remote/README.md

```
build --hazelcast_node=127.0.0.1:5701 --spawn_strategy=remote
```

```
java -jar hazelcast-3.5.4.jar &

bazel clean && bazel build :y
bazel clean && bazel build :y
```

Expected: The second run should be fast, as it retrieves the built `x` file from the cache.
Actual: It sleeps 5s even with the cache.

**Comment by dfabulich** [comment]
This makes me pretty suspicious, setting a junk value for `hazelcast_node` returns no error, presumably because it's not even trying to use it.

```
$ bazel clean && bazel build --hazelcast_node=DOES_NOT_EXIST --spawn_strategy=remote :y
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
INFO: Found 1 target...
Target //:y up-to-date:
  bazel-genfiles/y.txt
INFO: Elapsed time: 6.416s, Critical Path: 5.02s
```

**Comment by anupcshan** [comment]
I think `--genrule_strategy=remote` is needed to remote-execute/cache genrule actions.

**Comment by hhclam** [comment]
Like Anup said genrule by default does not use remote spawn strategy.

2016-06-15 20:43 GMT-04:00 Anup Chenthamarakshan <notifications@github.com>:

**Comment by dfabulich** [comment]
Didn't help; filed #1414
