### ISSUE TITLE
Pip timeout too low

### ISSUE THREAD

**Issue by joshua-ostrom** [bazelbuild/bazel#14121]
### Description of the problem / feature request:

Bazel build fails on on large pip installs (numpy, pandas etc)

### Feature requests: what underlying problem are you trying to solve with this feature?

Trying to run bazel without errors

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

A clean python install lacking numpy, pandas, scikit learn

### What operating system are you running Bazel on?

OSX BigSur

### What's the output of `bazel info release`?

Temporary fix via editing pip.bzl to add in `quiet=False, timeout=6000`
```
result = repository_ctx.execute([
        repository_ctx.attr.python_interpreter,
        repository_ctx.path(repository_ctx.attr._script),
        "--python_interpreter",
        repository_ctx.attr.python_interpreter,
        "--name",
        repository_ctx.attr.name,
        "--input",
        repository_ctx.path(repository_ctx.attr.requirements),
        "--output",
        repository_ctx.path("requirements.bzl"),
        "--directory",
        repository_ctx.path(""),
    ], quiet=False, timeout=6000)
```
It would be great to provide a command line option to extend the timeout or similar

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

release 4.0.0

**Comment by Wyverald** [comment]
Please report this to https://github.com/bazelbuild/rules_python (assuming you're using the pip rules from there).
