### ISSUE TITLE
[FreeBSD/OpenBSD] Unable to build bazel on systems where `bash` does not exist at `/bin/bash` 

### ISSUE THREAD

**Issue by yesudeep** [bazelbuild/bazel#14137]
### Description of the problem / feature request:

Tools used by Bazel to bootstrap itself and others written in Bash assume a non-portable location for the `bash` executable binary.
The binary is located at different locations on different operating systems. For example:

- [ ] GNU/Linux distributions (generally): `/bin/bash`
- [ ] MacOS: `/bin/bash`
- [ ] FreeBSD: `/usr/local/bin/bash`
- [ ] OpenBSD: `/usr/local/bin/bash`

The use of `#!/bin/bash` in the shebang line for shell scripts is non-portable and may require a lot of selective patching for Bazel to build successfully on multiple operating systems if done on a case by case basis. Fortunately, there appears to be a portable workaround if one is acceptable. Please consider using:

`#!/usr/bin/env bash` instead of `#!/bin/bash` in the shebang line.

### Feature requests: what underlying problem are you trying to solve with this feature?

- [ ] Allow Bazel to build portably on multiple operating systems.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Attempt to build Bazel from source on FreeBSD 13.0 using

```
❯ bazel build //src:bazel
INFO: Analyzed target //src:bazel (5 packages loaded, 310 targets configured).
INFO: Found 1 target...
ERROR: /usr/home/yesudeep/code/yesudeep/bazel/src/main/starlark/builtins_bzl/BUILD:16:8: Executing genrule //src/main/starlark/builtins_bzl:builtins_bzl_zip failed: (Exit 126): bash failed: error executing command /usr/local/bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/usr/local/bin/bash: bazel-out/host/bin/src/zip_builtins: /bin/bash: bad interpreter: No such file or directory
Target //src:bazel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.776s, Critical Path: 0.01s
INFO: 4 processes: 3 internal, 1 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
```

### What operating system are you running Bazel on?

```
❯ uname -a
FreeBSD ghostname 13.0-STABLE FreeBSD 13.0-STABLE GENERIC  amd64
```

### What's the output of `bazel info release`?

```
❯ bazel info release
release 4.2.1
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
❯ git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
git@github.com:yesudeep/bazel.git
85296b1f93fa0ded5eeb46859bb609c0ba31a45d
85296b1f93fa0ded5eeb46859bb609c0ba31a45d
```

###  Have you found anything relevant by searching the web?

-[ ] [`/bin/bash` on FreeBSD](https://sgeos.github.io/freebsd/bash/2016/02/20/bin-bash-on-freebsd.html)

### Any other information, logs, or outputs that you want to share?

None.

**Comment by keith** [comment]
> #!/usr/bin/env bash instead of #!/bin/bash in the shebang line.

Note that this isn't always preferred IMO since this could result in significantly different versions for users who install their own. This _likely_ isn't an issue but we've experienced developers writing shell scripts testing against their newer version just to find they fail on other older versions. (this is significantly worse on macOS since it ships with a super old version of bash)

Regardless I imagine trying to fix this everywhere in bazel would be quite the lift!
