### ISSUE TITLE
Turbine build issue with Micronaut

### ISSUE THREAD

**Issue by sgammon** [bazelbuild/bazel#14142]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

[Micronaut](https://micronaut.io) performs annotation processing to facilitate pre-wired DI. Through their [`TypeElementVisitorProcessor.java#L432`](https://github.com/micronaut-projects/micronaut-core/blob/3.1.x/inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java#L432), when Turbine is active via `--java_header_compilation`, [a call is made](https://github.com/micronaut-projects/micronaut-core/blob/2.5.x/inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java#L355) to [`TurbineElements.java#L293`](https://github.com/google/turbine/blob/main/java/com/google/turbine/processing/TurbineElements.java#L293), which promptly throws an `UnsupportedOperationException`.

### Feature requests: what underlying problem are you trying to solve with this feature?

I am trying to get Turbine to work with Micronaut

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. `git clone git@github.com:sgammon/elide.git -b turbine-repro && cd ./elide`
2. build via `bazel build //java/...`
3. after a short time, the error above is thrown

### What operating system are you running Bazel on?

`macOS Big Sur 11.6`

### What's the output of `bazel info release`?

```
> bazel info release
release 4.2.1

> bazel version
Build label: 4.2.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 30 15:24:28 2021 (1630337068)
Build timestamp: 1630337068
Build timestamp as int: 1630337068
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

- Running on latest `remote_java_tools` (`11.5`), as described in #13758
- Tried on `11.5`, `11.2`, standard Bazel with no override of `remote_java_tools`

### Any other information, logs, or outputs that you want to share?

Cross-filed with Micronaut team at micronaut-projects/micronaut-core#6381

**Comment by comius** [comment]
@sgammon is this issue resolve if you use java_tools 11.6 https://github.com/bazelbuild/java_tools/releases/tag/java_v11.6?

**Comment by sgammon** [comment]
@comius yes! the build now completes on that branch for me
