### ISSUE TITLE
Remove bazel run --script_path and scripts/bazel-run.sh

### ISSUE THREAD

**Issue by uri-canva** [bazelbuild/bazel#14153]
### Description of the problem / feature request:

`bazel run --script_path` and `scripts/bazel-run.sh` were introduced to work around https://github.com/bazelbuild/bazel/issues/2337 and https://github.com/bazelbuild/bazel/issues/2737.
Those two issues have been fixed in the bazel client in the meantime, but the presence of `--script_path` and `scripts/bazel-run.sh` can be confusing to users, implying they're still needed.

### What operating system are you running Bazel on?

```
> sw_vers
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165
```

### What's the output of `bazel info release`?

```
> bazel info release
release 4.1.0- (@non-git)
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Got it from https://github.com/NixOS/nixpkgs.

**Comment by gregestren** [comment]
@uri-canva do you know who fixed this in Bazel? Trying to route this issue accurately.

**Comment by uri-canva** [comment]
This is where direct run was introduced: https://github.com/bazelbuild/bazel/commit/4741aa83145fd2d3ab0599314f7732c5b80977bd

**Comment by sventiffe** [comment]
@lberki

**Comment by lberki** [comment]
`--script_path` is an ancient feature that *way* predates 4741aa8 and it's too widely used at Google to be just removed like that (I have my doubts as to whether it's very useful, but it doesn't look completely useless)

I'll send out a change to remove `bazel-run.sh`. That one is indeed truly useless now.
