### ISSUE TITLE
BEP artifact upload opens all files up-front

### ISSUE THREAD

**Issue by oehme** [bazelbuild/bazel#14161]
Follow-up ticket for https://github.com/bazelbuild/bazel/issues/14120#issuecomment-950696246

The BEP upload logic can end up opening a large number of files before the remote service responds with `ready`. This is because it calls [seek](https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/main/java/com/google/devtools/build/lib/remote/ByteStreamUploader.java#L512) before making the remote call. In a project with tons of little files, it can quickly lead to `too many open files` exceptions. I'm not sure why the seek call is outside of the listener, but if possible it would be great if the file was only opened when the remote is actually ready to receive it.

**Comment by janakdr** [comment]
@michaeledgar wrote to me, "we may want to cap the number of files-being-uploaded (eg. w/ semaphore)"

**Comment by coeuvre** [comment]
I may also look into this by lazily seeking after the connection is ready. But it is not on the top of my list.

**Comment by coeuvre** [comment]
Fixed by 46104c6948dc4ca66797e413c62b58bd21981c51 that introduced a new flag `----bep_maximum_open_remote_upload_files` to limit the max number of open files when uploading.

**Comment by meisterT** [comment]
cc @carriemittl @michaeledgar
