### ISSUE TITLE
second build fails with "Source forest creation failed" if I have top level package starting with "bazel-"

### ISSUE THREAD

**Issue by amkartashov** [bazelbuild/bazel#14167]
### Description of the problem / feature request:

Second build fails with "Source forest creation failed" if I have top level package starting with "bazel-"

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try to build https://github.com/gorilych/rbe-rs/tree/62e88968c770088a5b098e7c8dbc8f2cbfd55391

First run will be OK, second run fails:

```
rbe-rust$ bazel build rbe-rust
INFO: Invocation ID: 4fcb565e-7ff6-431f-bcda-804899a0df17
INFO: Analyzed target //rbe-rust:rbe-rust (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: Source forest creation failed
INFO: Elapsed time: 0.126s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

### What operating system are you running Bazel on?

```
rbe-rust$ uname -a
Linux sshct 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 x86_64 x86_64 GNU/Linux
```

### What's the output of `bazel info release`?

`release 4.2.1`. Also tested with 5.0.0-pre.20211011.2 - error is the same.

###  Have you found anything relevant by searching the web?

Yes, there are bugs with similar error message reported: https://github.com/bazelbuild/bazel/search?q=Source+forest+creation+failed&type=issues

But they have slightly different reasons.

### Any other information, logs, or outputs that you want to share?

strace reveals that bazel server fails on symlink call:

```
1570972 16:29:24 symlink("/home/me/git/gorilych/rbe-rust/bazel-remote-apis", "/home/me/.cache/bazel/_bazel_me/623f00f02379be57edb6c1e5a16fef79/execroot/rbe-rust/bazel-remote-apis" <unfinished ...>
1570936 16:29:24 <... gettid resumed>)  = 1570936 <0.000023>
1570972 16:29:24 <... symlink resumed>) = -1 EEXIST (File exists) <0.000011>
```

Renaming `bazel-remote-apis` to `bzl-remote-apis` (and fixing references in code, ofc) - fixes the error.

**Comment by gorilych** [comment]
the repo is private now, hope the issue has enough details.

**Comment by oquenchil** [comment]
Probably the Bazel code should do a better job of discerning which directories to delete but the workaround is trivial. Do not name packages this way.
