### ISSUE TITLE
Remove dependency of unix library on Windows

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#1416]
We need to refactor the code so that `//src/main/java/com/google/devtools/build/lib:unix` will not be used on Windows.

**Comment by ulfjack** [comment]
I have a set of patches that may help here. But I'm not sure what exactly you want to achieve. My patches make it so :unix is no longer a dependency of :util, but instead only a dependency of :runtime, and we use reflection to correctly instantiate :unix or :windows as needed.

**Comment by meteorcloudy** [comment]
Nice, that is exactly what we wanted to achieve. Thanks!
