### ISSUE TITLE
overlay script is not compatible with recent windows environment(including windows 11)

### ISSUE THREAD

**Issue by alanpurple** [bazelbuild/bazel#14176]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

tensorflow bazel build failed due to OSError(privilege error) by llvm overlay script

### Feature requests: what underlying problem are you trying to solve with this feature?

build feature of bazel with windows environment

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

git clone tensorflow
./configure
bazel build //tensorflow/tools/pip_package:build_pip_package

### What operating system are you running Bazel on?

Windows 11

### What's the output of `bazel info release`?

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

4.2.1

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/tensorflow/tensorflow.git
f25e38920bf0753243022a25adcc49d49016870f
88d7f690c4c5c1d2c9078c1afb15aeb093ddfdfa

###  Have you found anything relevant by searching the web?

https://github.com/tensorflow/tensorflow/issues/52131

### Any other information, logs, or outputs that you want to share?

https://github.com/tensorflow/tensorflow/issues/52131

**Comment by alanpurple** [comment]
It looks like bazel+llvm needs admin privilege execution of powershell in windows...
is this solvable?

**Comment by oquenchil** [comment]
It looks like this bug should be filed with Tensorflow, @meteorcloudy can you confirm and if so close the bug?

**Comment by meteorcloudy** [comment]
If the tool requires admin privilege to run, then it's not a Bazel bug, I don't think there is anything we can do from the Bazel side.
