### ISSUE TITLE
Bazel 4.2.1 doesn't respect --remote_max_connections

### ISSUE THREAD

**Issue by Vertexwahn** [bazelbuild/bazel#14178]
### Description of the problem:

There is a problem with Bazel 4.2.1. For some reason, it does not respect the [--remote_max_connections flag](https://docs.bazel.build/versions/4.2.1/command-line-reference.html#flag--remote_max_connections). Builds that run with this version of Bazel open up thousands of sockets when they should in fact be restricted to 100.

We do not see this behavior with Bazel 4.0.0.

When using socketstat (we do here always a build with a remote cache - the system has around 240 sockets open before Bazel starts) we see a large increase of max sockets:

| RUN_ID |  Bazel version |  Max Sockets |
| -------- | ------------| ------------- |
| 1           | 4.0.0         |     341           |
| 2           | 4.2.1         |    1241          |
| 3           | 4.0.0         |     332          |
| 4           | 4.2.1         |    1804          |
| 5           | 4.0.0         |     360           |
| 6           | 4.2.1         |    1813          |
| 7           | 4.2.1         |    2643          |

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

TODO (we work on it)

### What operating system are you running Bazel on?

Ubuntu 20.04 LTS

### What's the output of `bazel info release`?

`release 4.0.0` or `release 4.2.1`

###  Have you found anything relevant by searching the web?

Nope.

### Further notes

We are using Buildbarn

**Comment by brentleyjones** [comment]
@Wyverald Can this get the release blocker milestone instead of https://github.com/bazelbuild/bazel/pull/14202, and can it be reopened until the cherry-pick is in?

**Comment by Wyverald** [comment]
Cherrypicked \o/
