### ISSUE TITLE
no such attribute 'platform_type' in 'apple_binary' rule

### ISSUE THREAD

**Issue by akuseru** [bazelbuild/bazel#1418]
As it is currently part of the documentation I assume that this is an error. 

```
~/git/sfproj  bazel build //Clients:sfios
ERROR: /Users/adam/git/sfproj/Clients/BUILD:6:1: //Clients:sfios: no such attribute 'platform_type' in 'apple_binary' rule.
ERROR: error loading package 'Clients': Package 'Clients' contains errors.
INFO: Elapsed time: 0.596s
```

```
 ~/git/sfproj bazel version
Build label: 0.3.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 10 11:38:43 2016 (1465558723)
Build timestamp: 1465558723
Build timestamp as int: 1465558723
```

**Comment by hermione521** [comment]
Hi, could you also paste your BUILD file here? Thanks!

**Comment by akuseru** [comment]
Hi thanks!

https://github.com/akuseru/BazelTest

**Comment by philwo** [comment]
Hi @akuseru,

the "platform_type" attribute was added very recently (in https://github.com/bazelbuild/bazel/commit/f6a45fda097fcdae4704915c530403a90e9d6745), so it is not yet available in a released Bazel version. Sorry - we should probably version our docs together with the releases! I filed a feature request for this here: https://github.com/bazelbuild/bazel/issues/1429

If you want to develop for iOS, you can probably just leave out that attribute. :)

Cheers,
Philipp

**Comment by philwo** [comment]
I'm closing this issue - feel free to reopen if there's anything else you'd like to know!
