### ISSUE TITLE
path.readdir should cause the path to become an input of the repo rule

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/bazel#14200]
### Description of the problem / feature request:

[path.readdir()](https://docs.bazel.build/versions/3.3.0/skylark/lib/path.html#readdir) returns out of date results.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

**WORKSPACE.bazel**

```py
load(":workspace.bzl", "repo")

repo(
  name = "example",
)
```

**BUILD.bazel**

```py
```

**workspace.bzl**

```py
_content = """
package(default_visibility = ["//visibility:public"])

exports_files(["example.txt"])
"""

def _repo_impl(ctx):
    ctx.file("WORKSPACE.bazel", executable = False)
    ctx.file("BUILD.bazel", content = _content, executable = False)
    content = ""
    for child in ctx.path("/tmp/example").readdir():
        print(child.basename)
        content += child.basename + "\n"
    ctx.file("example.txt", content = content, executable = False)

repo = repository_rule(
    implementation = _repo_impl,
    local = True,
)
```

```sh
$ rm -fr /tmp/example
$ mkdir /tmp/example
$ bazel build @example//:example.txt
INFO: Analyzed target @example//:example.txt (1 packages loaded, 1 target configured).
INFO: Found 1 target...
INFO: Elapsed time: 0.160s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action

$ touch /tmp/example/file
$ bazel build @example//:example.txt
INFO: Analyzed target @example//:example.txt (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
INFO: Elapsed time: 0.059s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action

$ bazel shutdown
$ bazel build @example//:example.txt
Starting local Bazel server and connecting to it...
DEBUG: /home/paul/dev/rivethealth/test56/workspace.bzl:12:14: file
INFO: Analyzed target @example//:example.txt (1 packages loaded, 1 target configured).
INFO: Found 1 target...
INFO: Elapsed time: 1.899s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

Note that only after restarting, does `DEBUG: /home/paul/dev/rivethealth/test56/workspace.bzl:12:14: file` appear. 

Even though the repository rule is marked "local", Bazel has to be restarted for it to  see the new file /tmp/example/file. I believe this is due to improper caching of the readdir result.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

release 4.2.1

---

Re-reading a directory is ESSENTIAL to write rules like `new_local_repository`, as they need to update the symlinks whenever something changes.

Those rules of course lucked out, as they are native rules and not subject to Starlark limitations. But Starlark rules are left without recourse.

**Comment by keith** [comment]
I believe you can avoid this by changing your BUILD file to contain a filegroup using a glob, and make a genrule that depends on that write your example.txt file

**Comment by pauldraper** [comment]
This example was merely the demonstration that readdir() returns out-of-date results.

The motivation was creating rules similar to `new_local_repository`. And for that, readdir() must return up-to-date results every invocation.

**Comment by Wyverald** [comment]
readdir() isn't special here -- we don't rerun repository rules until some input has changed. And the stat of a random directory on disk isn't something we watch for (not realistically anyway). A repository rule being "local" just means that it's run on every Bazel server restart, even if no input has changed.

Now we _could_ say that as soon as `some_path.readdir()` is called, the stat of `some_path` should now be watched (as in, it's now part of the input of the repo rule). But that is very fragile. What is your use case?

**Comment by pauldraper** [comment]
@Wyverald local_repository is re-run every time.

**Comment by Wyverald** [comment]
`local_repository` _is_ a "local" repository rule: https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/repository/LocalRepositoryFunction.java;l=36;drc=9732d233dd3ef2ef94fe3ad588044d4ae788cbcc

**Comment by pauldraper** [comment]
I think this issue has confusing conversation and has been renamed poorly.

I've created #16217 which is hopefully more clear.

**Comment by jacky8hyf** [comment]
The only place that Kleaf uses readdir is here (ATTOW):
https://cs.android.com/android/kernel/superproject/+/common-android-mainline:prebuilts/clang/host/linux-x86/kleaf/user_clang_toolchain_repository.bzl;l=58;drc=7f17fbadc9ee07a636afb6083bf84c481a7cc2ab

... and there are no dependency on the actual content. So this bug does not affect Kleaf ATTOW.

**Comment by Wyverald** [comment]
This is fixed in https://github.com/bazelbuild/bazel/issues/20952
