### ISSUE TITLE
Log file output from --execution_log_json_file flag is not valid JSON

### ISSUE THREAD

**Issue by codeman9** [bazelbuild/bazel#14209]
### Description of the problem / feature request:

Output to `execution_log_json_file` is not a valid JSON file when multiple actions are recorded.

### Feature requests: what underlying problem are you trying to solve with this feature?

We are trying to parse the JSON execution log to gather some data with custom python and swift tools. `jq` seems to work with the file as output, but Python's `json.load` error:

```
  File "./tools/bazel_execution_trace.py", line 52, in <module>
    _main()
  File "./tools/bazel_execution_trace.py", line 19, in _main
    for execution in json.load(args.execution_log)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 135 column 2 (char 5713)
```

Swift's `JSONSerialization(with: stream)` error:
```
Fatal error: error: Error Domain=NSCocoaErrorDomain Code=3840 "Garbage at end." UserInfo={NSDebugDescription=Garbage at end.}
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Add `--execution_log_json_file=path/to/log/file.log` to the bazel invocation and inspect the file. Observe that there is no beginning or ending `[]`s to indicate a top-level JSON array object and the objects aren't separated with `,`s. Instead we see something like this:

```json
{
  "commandArgs": [...],
  ...
} {
  "commandArgs": [...],
  ...
}
```

### What operating system are you running Bazel on?

MacOS Big Sur 11.6.1

### What's the output of `bazel info release`?

release 5.0.0-pre.20211006.1

###  Have you found anything relevant by searching the web?

No, I've searched StackOverflow, GitHub Issues, and the email threads for `execution_log_json_file`

### Any other information, logs, or outputs that you want to share?

I used the `jq` query from issue #13845 to verify that `jq` does, indeed, work with the output file.
`jq  -r '.progressMessage, "Primary output: " + .listedOutputs[0], "Properties: ", .platform.properties, ""' log.json`

**Comment by meisterT** [comment]
Not sure since when this is broken but I will happily accept a PR to fix it.
