### ISSUE TITLE
error when ./compile.sh:  /usr/lib64/libstdc++.so.6: version GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by vitamin** [bazelbuild/bazel#1420]
If I just use command ./compile.sh

./compile.sh 
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel

.WARNING: /tmp/bazel.80BD16BI/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel.80BD16BI/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.
WARNING: /root/wangwei/bazel/src/main/native/BUILD:52:16: in includes attribute of cc_binary rule //src/main/native:libunix.so: '.' resolves to 'src/main/native' not in 'third_party'. This will be an error in the future.
WARNING: /root/wangwei/bazel/src/main/protobuf/BUILD:36:1: in includes attribute of cc_library rule //src/main/protobuf:command_server_cc_proto: '.' resolves to 'src/main/protobuf' not in 'third_party'. This will be an error in the future. Since this rule was created by the macro 'cc_grpc_library', the error might have been caused by the macro implementation in /root/wangwei/bazel/tools/build_rules/genproto.bzl:104:18.
INFO: Found 1 target...
INFO: From Compiling src/main/cpp/blaze_util_posix.cc:
src/main/cpp/blaze_util_posix.cc: In function 'std::__cxx11::string blaze::RunProgram(const string&, const std::vector<std::__cxx11::basic_string<char> >&)':
src/main/cpp/blaze_util_posix.cc:199:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
ERROR: /root/wangwei/bazel/src/main/protobuf/BUILD:36:1: Executing genrule //src/main/protobuf:command_server_cc_proto_codegen failed: bash failed: error executing command 
  (cd /tmp/bazel.80BD16BI/out/bazel && \
  exec env - \
    PATH=/root/CRClientTools/arcanist/bin:/usr/local/mysql/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/java/jdk1.8.0_91/bin:/usr/local/python2.7/bin:/root/bin:/root/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; third_party/protobuf/protoc-linux-x86_64.exe\
    --plugin=protoc-gen-grpc=bazel-out/host/bin/third_party/grpc/cpp_plugin\
    --cpp_out=bazel-out/local-fastbuild/genfiles\
    --grpc_out=bazel-out/local-fastbuild/genfiles\
    src/main/protobuf/command_server.proto'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
bazel-out/host/bin/third_party/grpc/cpp_plugin: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by bazel-out/host/bin/third_party/grpc/cpp_plugin)
bazel-out/host/bin/third_party/grpc/cpp_plugin: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by bazel-out/host/bin/third_party/grpc/cpp_plugin)
bazel-out/host/bin/third_party/grpc/cpp_plugin: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by bazel-out/host/bin/third_party/grpc/cpp_plugin)
bazel-out/host/bin/third_party/grpc/cpp_plugin: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by bazel-out/host/bin/third_party/grpc/cpp_plugin)
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
Target //src:bazel failed to build
INFO: Elapsed time: 61.721s, Critical Path: 53.64s

Building output/bazel

-----------------------------------------
If I use follow command:
LD_LIBRARY_PATH="/some/crosstool/lib:/some/more/lib" CPLUS_INCLUDE_PATH="/some/include/path" CC="/some/crosstool/bin/some-gcc" ./compile.sh

.WARNING: /tmp/bazel.0sxXLpCn/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel.0sxXLpCn/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.
WARNING: /root/wangwei/bazel/src/main/native/BUILD:52:16: in includes attribute of cc_binary rule //src/main/native:libunix.so: '.' resolves to 'src/main/native' not in 'third_party'. This will be an error in the future.
WARNING: /root/wangwei/bazel/src/main/protobuf/BUILD:36:1: in includes attribute of cc_library rule //src/main/protobuf:command_server_cc_proto: '.' resolves to 'src/main/protobuf' not in 'third_party'. This will be an error in the future. Since this rule was created by the macro 'cc_grpc_library', the error might have been caused by the macro implementation in /root/wangwei/bazel/tools/build_rules/genproto.bzl:104:18.
INFO: Found 1 target...
ERROR: /root/wangwei/bazel/src/main/cpp/BUILD:53:1: C++ compilation of rule '//src/main/cpp:blaze_abrupt_exit' failed: some-gcc failed: error executing command 
  (cd /tmp/bazel.5oMECmwO/out/bazel && \
  exec env - \
    PATH=/root/CRClientTools/arcanist/bin:/usr/local/mysql/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/java/jdk1.8.0_91/bin:/usr/local/python2.7/bin:/root/bin:/root/bin \
  /some/crosstool/bin/some-gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/some/crosstool/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer '-std=c++0x' -I/some/include/path -MD -MF bazel-out/local-fastbuild/bin/src/main/cpp/_objs/blaze_abrupt_exit/src/main/cpp/blaze_abrupt_exit.pic.d '-frandom-seed=bazel-out/local-fastbuild/bin/src/main/cpp/_objs/blaze_abrupt_exit/src/main/cpp/blaze_abrupt_exit.pic.o' -fPIC -iquote . -iquote bazel-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c src/main/cpp/blaze_abrupt_exit.cc -o bazel-out/local-fastbuild/bin/src/main/cpp/_objs/blaze_abrupt_exit/src/main/cpp/blaze_abrupt_exit.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 127.
/tmp/bazel.5oMECmwO/out/bazel/_bin/process-wrapper: line 12: /some/crosstool/bin/some-gcc: No such file or directory
Target //src:bazel failed to build
INFO: Elapsed time: 3.675s, Critical Path: 0.04s

Building output/bazel

we use company's linux version
Linux anti06.qq.diditaxi.com 2.6.32.43-tlinux-1.0.8-default #1 SMP Tue Jul 9 18:07:14 CST 2013 x86_64 x86_64 x86_64 GNU/Linux

which gcc
/usr/local/sbin/gcc

gcc --version
gcc (GCC) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

java -version 
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by hermione521** [comment]
@damienmg can you help with this?

**Comment by damienmg** [comment]
@lberki: this is failing building using GRPC

**Comment by philwo** [comment]
For one, this is also yet another classic example where we shouldn't reset the PATH to a hard-coded list but instead take it from the environment. :|

The first build fails because somehow gcc is generating a cpp_plugin binary that can't run on your system due to incompatible libcxx versions (maybe it compiles using a different one than what is used to run the binary?):

```bazel-out/host/bin/third_party/grpc/cpp_plugin: /usr/lib64/libstdc++.so.6: version GLIBCXX_3.4.20' not found (required by bazel-out/host/bin/third_party/grpc/cpp_plugin) bazel-out/host/bin/third_party/grpc/cpp_plugin: /usr/lib64/libstdc++.so.6: versionCXXABI_1.3.8' not found (required by bazel-out/host/bin/third_party/grpc/cpp_plugin)
bazel-out/host/bin/third_party/grpc/cpp_plugin: /usr/lib64/libstdc++.so.6: version GLIBCXX_3.4.18' not found (required by bazel-out/host/bin/third_party/grpc/cpp_plugin) bazel-out/host/bin/third_party/grpc/cpp_plugin: /usr/lib64/libstdc++.so.6: versionGLIBCXX_3.4.21' not found (required by bazel-out/host/bin/third_party/grpc/cpp_plugin)```

I'm not sure why the second one fails. This suggests that the CC binary you used doesn't exist:

```/tmp/bazel.5oMECmwO/out/bazel/_bin/process-wrapper: line 12: /some/crosstool/bin/some-gcc: No such file or directory```

Could you make sure that /some/crosstool/bin/some-gcc really works when you call it from your terminal manually?

(Also, note to others and myself: This build doesn't use sandboxing, so it couldn't cause any issues here.)

**Comment by philwo** [comment]
Oh, well, yes: If you need a special LD_LIBRARY_PATH for that gcc in the second build, it won't work, because we remove that environment variable during the build.

Could you please tell me whether /some/crosstool/bin/some-gcc actually exists?

**Comment by vitamin** [comment]
thx you two。
I fix this error by the following commands:
```
cp /usr/local/gcc-5.3.0/lib64/libstdc++.so.6.0.21 /usr/lib64/
ln -sf libstdc++.so.6.0.21 libstdc++.so.6
```

**Comment by damienmg** [comment]
@vitamin what about the /some/crosstool?

Is your LD_LIBRARY_PATH correctly set? If yes then it means we did not detected it correctly.
