### ISSUE TITLE
JSON workers should delimit work requests with newlines

### ISSUE THREAD

**Issue by wolfd** [bazelbuild/bazel#14218]
### Description of the problem / feature request:

JSON workers are difficult to write because work requests are not newline delimited. This issue was [brought up](https://github.com/bazelbuild/bazel/issues/13599#issuecomment-867900602) in #13599, and the discussion generally indicated that this is a usability bug.

The proposal is to add a newline between requests according to [ndjson](http://ndjson.org/).

### Feature requests: what underlying problem are you trying to solve with this feature?

Right now an implementation of a JSON worker work request loop using python looks like this:
```python
# This is a pretty cumbersome way of getting work requests.
# It waits for something to be available on stdin, and then tries parsing
# whatever text is available as JSON. It keeps accumulating more text until a
# full work request is available.
def wait_for_stdin_json():
    stdin = open("/dev/stdin", "rb")
    os.set_blocking(stdin.fileno(), False)
    stream_bytes = b""
    while True:
        _, _, _ = select.select([stdin.fileno()], [], [])
        maybe_bytes = stdin.read()
        if maybe_bytes is None:
            continue
        stream_bytes += maybe_bytes
        try:
            work_request = json.loads(stream_bytes)
        except json.decoder.JSONDecodeError:
            # stream couldn't decode, wait until next select
            sys.stderr.write(f"failed to decode: {stream_bytes.decode('utf-8')}\n")
            sys.stderr.flush()
            continue

        yield work_request
        stream_bytes = b""  # reset
```

With newline-delimited JSON it would look like this:

```python
# Simplified json loop with newline-delimited json.
def wait_for_stdin_json():
    while True:
        yield json.loads(sys.stdin.readline())
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

[Current version](https://github.com/wolfd/json_worker_example/tree/8238b21e623eea2b73174e927ab6601d5504cf57)

[Proposed version](https://github.com/wolfd/json_worker_example/tree/3063a5b5fdb9293d6f0b22eb54039430ae7b3d49)

**Comment by meisterT** [comment]
I agree, see https://github.com/bazelbuild/bazel/issues/13599#issuecomment-868254182

**Comment by meisterT** [comment]
cc @larsrc-google

**Comment by brentleyjones** [comment]
@wolfd Do you want to make a PR against the 5.0 rc? Seems like a good thing to try to get in.

**Comment by wolfd** [comment]
> @wolfd Do you want to make a PR against the 5.0 rc? Seems like a good thing to try to get in.

Sure: https://github.com/bazelbuild/bazel/pull/14314
