### ISSUE TITLE
Encourage users to use release versions for dependencies used by Bazel

### ISSUE THREAD

**Issue by limdor** [bazelbuild/bazel#14217]
### Description of the problem / feature request:

Ticket to continue the discussion started in https://github.com/bazelbuild/bazel/pull/14171#issuecomment-953813615

In our company we had several times the situation that we want to update Bazel and we need to update also the different Bazel rules. In order to decide which ones to use there two approaches:
* You can take the same version of the dependencies that Bazel is using for the specific release that you want to use. For example in Bazel 4.2.1 you could take the same version of the dependencies like specified in https://github.com/bazelbuild/bazel/blob/02ad3e3bc6970db11fe80f966da5707a6c389fdd/WORKSPACE#L147
* You can take the latest release version of the rules that you want to update
Regarding the first option I do not think it is a good practice, Bazel generally depends on specific commit hashes and not in releases. I would assume that releases are more tested than specific hashes (correct me if I'm wrong).

Note that in addition there are two additional approaches that currently are not possible but were or will be possible:
* In the past, when Bazel federation was alive, the recommended one by Bazel federation was taken
* In the future, once BazelMod comes into play, you could take the latest version specified in BazelMod

### Feature requests: what underlying problem are you trying to solve with this feature?

My request does not involve any code change, just a comment in https://github.com/bazelbuild/bazel/blob/master/distdir_deps.bzl#L14
The idea would be to add a comment in this file saying that people do not have to use this specific versions and that they are encourage to use the latest releases for the dependencies. The exact text can be discussed but the idea would be to discourage the use of specific commits and encourage the use of releases for Bazel rules.

### What's the output of `bazel info release`?

4.2.1

###  Have you found anything relevant by searching the web?

This is the ticket created after the discussion in https://github.com/bazelbuild/bazel/pull/14171#issuecomment-953813615

**Comment by limdor** [comment]
@meteorcloudy @aiuto here the ticket. If you agree I could start drafting the PR.

**Comment by limdor** [comment]
@meteorcloudy I created a PR. If you could review it or point to the person that could it that would be great

**Comment by aiuto** [comment]
I think the comment should be simply that end users should never look at distdir_deps.bzl. It is internal source code and independent of the user experience.  The advice about specific versions is only going to get us in to trouble because
- we don't follow that advice
- sometimes it is impossible for users to follow the advice

**Comment by limdor** [comment]
> I think the comment should be simply that end users should never look at distdir_deps.bzl. It is internal source code and independent of the user experience. The advice about specific versions is only going to get us in to trouble because
> 
> * we don't follow that advice
> * sometimes it is impossible for users to follow the advice

Ok, second try: https://github.com/bazelbuild/bazel/pull/14379

**Comment by fweikert** [comment]
I'll close this issue since the comment was added. Feel free to reopen.
