### ISSUE TITLE
target failed when executing `turbine_direct_binary_deploy.jar`

### ISSUE THREAD

**Issue by dieend** [bazelbuild/bazel#14210]
### Description of the problem / feature request:
When running a rules_proto target, the target failed with the following stderr:
```
java.util.zip.ZipException: invalid zip archive
	at com.google.turbine.zip.Zip$ZipIterable.<init>(Zip.java:163)
	at com.google.turbine.main.Main.parseAll(Main.java:316)
	at com.google.turbine.main.Main.compile(Main.java:136)
	at com.google.turbine.main.Main.compile(Main.java:130)
	at com.google.turbine.main.Main.main(Main.java:87)
```

Example of command line being executed (based on execution_log file).
```

external/remotejdk11_linux/bin/java
-Xverify:none
-XX:+UseParallelOldGC
-XX:-CompactStrings
--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar
--patch-module=jdk.compiler=external/remote_java_tools_linux/java_tools/jdk_compiler.jar
--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
--add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED
--add-opens=java.base/java.nio=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
-jar
external/remote_java_tools_linux/java_tools/turbine_direct_binary_deploy.jar
--output
bazel-out/k8-fastbuild/bin/protos/growth/payout/enums/libbrex_growth_payout_enums_proto-speed-hjar.jar
--output_deps
bazel-out/k8-fastbuild/bin/protos/growth/payout/enums/libbrex_growth_payout_enums_proto-speed-hjar.jdeps
--bootclasspath
bazel-out/k8-fastbuild/bin/external/bazel_tools/tools/jdk/platformclasspath.jar
--source_jars
bazel-out/k8-fastbuild/bin/protos/growth/payout/enums/brex_growth_payout_enums_proto-speed-src.jar
--injecting_rule_kind
java_proto_library
--javacopts
-source
8
-target
8
-XDskipDuplicateBridges=true
-XDcompilePolicy=simple
-g
-parameters
--
--target_label
//protos/growth/payout/enums:brex_growth_payout_enums_proto
--classpath
bazel-out/k8-fastbuild/bin/external/protobuf_elixir/libbrex_elixirpb_proto-speed-hjar.jar
bazel-out/k8-fastbuild/bin/external/com_google_protobuf/java/core/libcore-hjar.jar
bazel-out/k8-fastbuild/bin/external/com_google_protobuf/java/core/liblite-hjar.jar
--reduce_classpath_mode
NONE

```
### Feature requests: what underlying problem are you trying to solve with this feature?

I have no idea how to investigate the issue, as it happened in CI. The only way I can mitigate this was by purging remote-cache (we are using https://github.com/buchgr/bazel-remote and S3 to store remote cache). The bazel-output are ephemeral, except the external rules. Most likely there is a corrupted file in the S3 uploaded by bazel-remote.

I'm expecting the logs to tell me:
1. What input is broken and can't be processed
2. A way for me to identify what file in s3 is corrupted and can be deleted.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
non-deterministic

### What operating system are you running Bazel on?
ubuntu-bionic docker

### What's the output of `bazel info release`?
release 4.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.
not development version

###  Have you found anything relevant by searching the web?
No, the zip error wasn't particularly specific and helpful

**Comment by cushon** [comment]
This is the line in turbine where it's seeing the invalid jar: https://github.com/google/turbine/blob/7db5cb2f1914f3547a206547d87cdc1252967114/java/com/google/turbine/main/Main.java#L316

That logic is handling `--source_jars`, which suggests the invalid jar here is `bazel-out/k8-fastbuild/bin/protos/growth/payout/enums/brex_growth_payout_enums_proto-speed-src.jar`

That exception is thrown for archives that are too small to contain a valid end of central directory record, i.e. < 22 bytes: https://github.com/google/turbine/blob/ffe8d01aa9a5233b764bb78845a5cbf3ce49da28/java/com/google/turbine/zip/Zip.java#L162-L163

**Comment by comius** [comment]
> I'm expecting the logs to tell me:
> 1. What input is broken and can't be processed
> 2. A way for me to identify what file in s3 is corrupted and can be deleted.

So if I understand correctly, your feature request is to instead of saying
`java.util.zip.ZipException: invalid zip archive`
say
`java.util.zip.ZipException: invalid zip archive 'bazel-out/k8-fastbuild/bin/protos/growth/payout/enums/brex_growth_payout_enums_proto-speed-src.jar'` or something close to that?
