### ISSUE TITLE
bazel-test broken on ci

### ISSUE THREAD

**Issue by hermione521** [bazelbuild/bazel#1422]
breakage: http://ci.bazel.io/job/bazel-tests/71/
commit: https://github.com/bazelbuild/bazel/commit/bdfd58a8ca2ed5735d6aaa5b238fb0f689515724

**Comment by kchodorow** [comment]
Even broke the [Windows build](http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=windows-x86_64/609/console)! Rollback in progress.
