### ISSUE TITLE
cc_library with subpackage fails with duplicate action error

### ISSUE THREAD

**Issue by thhous-msft** [bazelbuild/bazel#14237]
### Description of the problem :

When creating a cc_library target with a subpackage (I think thats the right name for it, I'm not sure), a conflicting actions error occurs.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Use the following BUILD.bazel contents (lib.cc is just `void func() {}` and main.cc is just `int main() {}`

```
cc_library(
    name = "sub/mylib",
    srcs = [ "lib.cc" ]
)

cc_binary(
    name = "sub/myexe",
    srcs = [ "main.cc" ]
)
```

And build the target `:sub/mylib`. This will result in the following output.

```
C:\Users\Thad\Documents\bztest>bazel build :sub/mylib
ERROR: file 'sub/libmylib.a' is generated by these conflicting actions:
Label: //:sub/mylib
RuleClass: cc_library rule
Configuration: 3760312c3f985e91b4e995aa2f6d771a8963101f8157a8d259773188e8ab6b59
Mnemonic: Fail
Action key: ca06770c0ba6cbf0a626f7fd9363cd7fe8afc743bf2396949210a2707d52b4b5, 8f7e22df52c69ee015d4103f114da3459e32d366db52add76768eeb4d9f2e4d1
Progress message: Reporting failed target //:sub/mylib located at C:/users/thad/documents/bztest/BUILD.bazel:1:11
PrimaryInput: (null)
PrimaryOutput: File:[[<execution_root>]bazel-out/x64_windows-fastbuild/bin]sub/libmylib.a
Owner information: ConfiguredTargetKey{label=//:sub/mylib, config=BuildConfigurationValue.Key[3760312c3f985e91b4e995aa2f6d771a8963101f8157a8d259773188e8ab6b59]}
MandatoryInputs: are equal
Outputs: are equal
ERROR: Analysis of target '//:sub/mylib' failed; build aborted: for sub/libmylib.a, previous action: action 'Reporting failed target //:sub/mylib located at C:/users/thad/documents/bztest/BUILD.bazel:1:11', attempted action: action 'Reporting failed target //:sub/mylib located at C:/users/thad/documents/bztest/BUILD.bazel:1:11'
INFO: Elapsed time: 0.097s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 1 target configured)
```

However, if you attempt to build `:sub/myexe` that builds fine. So its a bug specific to cc_library.

### What operating system are you running Bazel on?

Windows 11

### What's the output of `bazel info release`?

```
> bazel info release
release 4.2.1
```

###  Have you found anything relevant by searching the web?

The error looks similar to this, but its not the exact same.
https://github.com/bazelbuild/bazel/issues/13464

**Comment by thhous-msft** [comment]
Doing some testing on Linux, this bug does not occur there. It looks to be a windows exclusive bug.

**Comment by wrowe** [comment]
Ping, this appears to be a blocker to porting wasm support on Windows
