### ISSUE TITLE
Bazel should give more context for errors generated in .bzl files

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1424]
If you create a rule that could cross a package boundary, like this:

```
def _impl(ctx):
  output = ctx.outputs.out
  ctx.file_action(
      output = output,
      content = "")

touch = rule(
    attrs = {"output": attr.string()},
    outputs = {"out": "%{output}"},
    implementation = _impl,
)
```

And then someone makes it do so:

```
load("//:rf.bzl", "touch")

touch(
    name = "cross",
    output = "bar/baz",
)
```

The error message is unclear:

```
$ bazel build :cross
ERROR: /home/kchodorow/test/a/BUILD:51:1: Label '//:bar/baz' crosses boundary of subpackage 'bar' (perhaps you meant to put the colon here: '//bar:baz'?).
ERROR: error loading package '': Package '' contains errors.
INFO: Elapsed time: 0.263s
```

This is a contrived example to be as obvious as possible, but still as far as the user knows they've never created a label //:bar/baz (they just passed in a string).  In the actual user case this came from, it was even less obvious because the .bzl file was munging a user-provided string and combining it into a path.

Not sure what the optimal error message should be, maybe something like:

```
ERROR: /home/kchodorow/test/a/BUILD:51:1: touch() creates output '//:bar/baz', which crosses boundary of subpackage 'bar'
ERROR: error loading package '': Package '' contains errors.
```

**Comment by meisterT** [comment]
This succeeds now (when passing `--incompatible_new_actions_api=false`).
Laurent, can we close it?
