### ISSUE TITLE
Can the bazel plugin for Clion support toolchain so it can use bazel binary within a docker container?

### ISSUE THREAD

**Issue by smartbarbarian** [bazelbuild/bazel#14248]
Documentation issue: IDE integration Documentation URL: https://docs.bazel.build/versions/main/ide.html
Currently I can't find an IDE which can support bazel and docker at the same time for C++.
CLion support importing a bazel project but it can't import the project within docker.
VScode need users to generate the compile_commands.json for bazel by themselves. 
I really need to enable intellisense for a bazel project within docker. Please help me to solve the problem. 
THANK YOU SO MUCH!

**Comment by Lorite** [comment]
Is there any solution to use a custom clangd executable and command-line flags with the bazel plugin in CLion? Or at least to tell it to use the compile_commands.json file?
