### ISSUE TITLE
Bzlmod: a project cannot provide a macro that uses select statement

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#14259]
For example in rules_pkg, [//private:private_stamp_detect](https://github.com/bazelbuild/rules_pkg/blob/b83be9ce26ff9708c9b9ebe658a175527cc74ff1/pkg/pkg.bzl#L50) is a config setting in rules_pkg for filling the value of [private_stamp_detect](https://github.com/bazelbuild/rules_pkg/blob/b83be9ce26ff9708c9b9ebe658a175527cc74ff1/pkg/pkg.bzl#L494), which is defined in a macro `pkg_tar`.

In rules_pkg, the final condition label string is calculated as:
```
_stamp_condition = str(Label("//private:private_stamp_detect"))
```
This is because:

- we cannot just use `//private:private_stamp_detect` as the select key, because it will be relative to the main repo that uses the `pkg_tar` macro.
- then rules_pkg has to convert it to a label with a specific repo name via `Label(//private:private_stamp_detect)`, this made sure the package path is relative to rules_pkg.
- But **`select` doesn't accept label as key**, then rules_pkg has to convert it back to a string.

In Bzlmod, we enforces repo level [strict deps](https://github.com/bazelbuild/bazel/issues/13793) via repo mapping, each repo has a repo mapping that contains all the repos it can see. In this case, if A depends on rules_pkg at version 0.5.1, then there is a mapping `@rules_pkg`(local name) -> `@rules_pkg.0.5.1`(canonical name). We resolve the repo mapping when constructing a Label from a label string.

This will break the above use case, because `_stamp_condition` will have to go through repo mapping twice. The first time, `//private:private_stamp_detect` is resolved to `@rules_pkg.0.5.1//private:private_stamp_detect` with rules_pkg's repo mapping, and the second time the `select` statement tries to resolve `@rules_pkg.0.5.1//private:private_stamp_detect` with A's repo mapping but only finds out `@rules_pkg.0.5.1` (local name) doesn't exist because the local repo name should be `@rules_pkg`.

The solution is to let `select` accept Label as the key type, therefore we can skip the second repo mapping.

**Comment by fmeum** [comment]
@meteorcloudy Is this something that you would work on for Bazel 5.1.0? I am asking because it currently blocks `rules_fuzzing` from becoming a module and if you are busy with other things, I could look into working on it.

**Comment by meteorcloudy** [comment]
@fmeum It would be awesome if you could help looking into this! Thanks!

**Comment by Wyverald** [comment]
I'm happy to provide guidance!

**Comment by Wyverald** [comment]
@bazel-io fork 5.1
