### ISSUE TITLE
Compile Line Length Limit hit under Windows 10.0 with bazel 4.0.0

### ISSUE THREAD

**Issue by lee-csu** [bazelbuild/bazel#14256]
### Description of the problem / feature request:
I tried to compile the Java project on Windows 10, but because the project has too many dependencies, an error message is displayed during dependency parsing, indicating that command is longer than CreateProcessW's limit. My maven_install() defines nearly 500 dependencies.

Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
### workspace
maven_install(
   artifacts = [
       "org.apache.zookeeper:zookeeper-jute:3.6.0",
       "org.apache.zookeeper:zookeeper-jute:3.6.2",
       "org.apache.zookeeper:zookeeper:3.6.2-h0.gdd.sop.r18",
       "io.grpc:grpc-api:1.36.1",
       ...
       # ....nearly 500 dependencies
]
)
### What operating system are you running Bazel on?
windows10 Bazel verison：4.0.0 rules_jvm_external version：4.0

### What's the output of bazel info release?
no such package '@maven//': Error while fetching artifact with coursier: java.io.IOException: ERROR: 
src/main/native/windows/process.cc(165): CreateProcessWithExplicitHandles("D:\tools\javajdk\bin\java" -noverify -jar 
C:/users/xxx/esyrauaw/external/maven/coursier fetch org.apache.zookeeper:zookeeper-jute:3.6.0 
org.apache.zookeeper:zookeeper-jute:3.6.2 org.apache.zookeeper:zookeeper:3.6.2-h0.gdd.sop.r18 io.grpc:grpc-api:1.36.1 
io.grpc:grpc-context:1.36.1 io.grpc:grpc-core:1.36.1 io.grpc:grpc-grpclb:1.36.1 io.grpc:grpc-netty:1.36.1 io.grpc:grpc-protobuf-
lite:1.36.1 io.grpc:grpc-protobuf:1.36.1 io.grpc:grpc-stub:1.36.1 org.quartz-scheduler.in(...)): command is longer than 
CreateProcessW's limit (32767 characters)

**Comment by gregestren** [comment]
@meteorcloudy

**Comment by meteorcloudy** [comment]
@lee-csu This is a limitation of Windows and should be fixed in rule_jvm_external. Please file a bug to https://github.com/bazelbuild/rules_jvm_external.

FYI @jin, maybe we could add parameter file support for `coursier` to workaround this?

**Comment by lee-csu** [comment]
ok, thanks
