### ISSUE TITLE
select() doesn't resolve labels to the correct repository

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1425]
See http://stackoverflow.com/questions/37884031/how-to-write-a-bazel-select-macro-that-works-inside-or-outside-of-defining-works: `select({"//foo" : ...})` resolves //foo relative to whatever repository loads the macro, not the repository the macro is defined in.

**Comment by dmansfield** [comment]
[bazel-issue-1425.zip](https://github.com/bazelbuild/bazel/files/321214/bazel-issue-1425.zip)

Attached zip is my "test case" for the bug.  It will only work in bt/child or in bt/base (but not in both) depending on how you define the macro in bt/base/main/macros.bzl.

I tested in 0.2.2b and 0.3.0

**Comment by lingz** [comment]
Seems that this one is related to report #1551 I submitted.

**Comment by dslomov** [comment]
Use 
```
def if_development(if_true, if_false = []):
    return select({
        str(Label("//main:development")) : if_true,
        str(Label("//conditions:default")): if_false
    })
```

This will refer to the right targets
