### ISSUE TITLE
flag_alias with special boolean syntax breaks various Bazel commands

### ISSUE THREAD

**Issue by uhthomas** [bazelbuild/bazel#14269]
### Description of the problem / feature request:

Various Bazel commands do not work when using a flag alias with [special boolean syntax](https://docs.bazel.build/versions/main/skylark/config.html#using-build-settings-on-the-command-line).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

**BUILD.bazel**
```py3
load("@bazel_skylib//rules:common_settings.bzl", "bool_flag")

bool_flag(
    name = "fips",
    build_setting_default = True,
)

config_setting(
    name = "use_fips",
    flag_values = {":fips": "True"},
)
```

**.bazelrc**
```bash
build --flag_alias=nofips=no//:fips
build --nofips
```

Run `bazel clean`, or `bazel info`.

### What operating system are you running Bazel on?

```
❯ uname -mrs
Darwin 20.6.0 x86_64
```

### What's the output of `bazel info release`?

```
❯ bazel info release
(06:44:10) INFO: Invocation ID: ede2dd6e-56fe-43f6-8929-3cb5b6330818
release: release 4.2.1
(06:44:10) ERROR: unknown key(s): '--no//:fips'
```

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

```
❯ bazel clean
(06:45:39) INFO: Invocation ID: 8a46aebd-ca5c-463f-a6e2-8e534a02d9f5
(06:45:39) ERROR: Unrecognized arguments: --no//tools/config:fips
❯ bazel info
(06:45:43) INFO: Invocation ID: 7cb3b3fe-9ca0-47f3-bd68-46e5f537879f
(06:45:43) ERROR: unknown key(s): '--no//tools/config:fips'
```

**Comment by aranguyen** [comment]
Have you tried using later releases? I'm using 6.0.0-pre.20211101.2 with the same example you provided and did not see the same error.

**Comment by gregestren** [comment]
@aranguyen - since we expect this work and this is a pretty old bug now, let's close it. @uhthomas feel free to re-open if the suggestion above doesn't work.

**Comment by uhthomas** [comment]
The commands seem to work okay now, though there is excessive noise.

```
(00:03:47) WARNING: Blaze clean does not support starlark options. Ignoring options: [--@io_bazel_rules_go//go/config:linkmode=pie]
```

What makes this a warning? Can this be silenced?

**Comment by gregestren** [comment]
See https://github.com/bazelbuild/bazel/issues/13473#issuecomment-1024734270 and above discussion.

Maybe it can? Someone would have to review the history of the rationale behind the warning. My comment there suggests the warning is meaningful to `bazel info`. Maybe not `bazel clean`?
