### ISSUE TITLE
download_and_extract needs kwargs

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1426]
Right now it has 5 positional arguments with unreadable documentation and a couple of undocumented variants.  It is impressively difficult to use.

**Comment by damienmg** [comment]
I was already working on it :)

Yes it is definitely terrible and I wanted to have it support kwargs at first but skylark construct does not support it yet (so working on supporting it).

**Comment by damienmg** [comment]
Update: I should finish this one this week hopefully. The skylark construct is alsmost there, just the documentation generator doesn't support it, then migrating to kwargs for all repository_ctx method should be straightforward \o/
