### ISSUE TITLE
https://github.com/google/tf_mesh_renderer - fail

### ISSUE THREAD

**Issue by CGMikeG** [bazelbuild/bazel#14271]
I was hoping somebody can direct me to the right direction. I was trying to compile tf_mesh_renderer but I keep getting below error.

I tried to compile in colab, windows 10, linux mint but it keep failing. Any suggestions?

https://github.com/google/tf_mesh_renderer

INFO: Build options --define and --python_path have changed, discarding analysis cache.
DEBUG: Rule 'com_google_googletest' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "a51d42cd1e7c5d20222759b13912151bfe74e0aab95f29bbf544d0159d3bb524"
DEBUG: Repository com_google_googletest instantiated at:
  /home/vl/Desktop/tf_mesh_renderer/WORKSPACE:6:13: in <toplevel>
Repository rule http_archive defined at:
  /home/vl/.cache/bazel/_bazel_vl/a8bce1ccbc527a5302caf84fe881b543/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /home/vl/Desktop/tf_mesh_renderer/mesh_renderer/kernels/BUILD:20:8: in cmd attribute of genrule rule //mesh_renderer/kernels:rasterize_triangles_kernel: $(PYTHON) not defined
ERROR: Analysis of target '//mesh_renderer:rasterize_triangles_test' failed; build aborted: Analysis of target '//mesh_renderer/kernels:rasterize_triangles_kernel' failed
INFO: Elapsed time: 0.334s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 58 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 58 targets configured)

**Comment by gregestren** [comment]
Can you get support from the tf_mesh_renderer project?

**Comment by Timothychance** [comment]
same error

**Comment by gregestren** [comment]
I would see support from https://github.com/google/tf_mesh_renderer or the TensorFlow project, as they'll be familiar with the details of their projects.
