### ISSUE TITLE
Error linking c/c++ code

### ISSUE THREAD

**Issue by rsteiger** [bazelbuild/bazel#1427]
I'm getting an error linking c and c++ code on my mac.

I put together this sample:
https://gist.github.com/anonymous/51c2c087bdc3d586177db35e664ec6c8

While there are no errors building, when the binary is run the following error message is printed:

ld: lazy symbol binding failed: Symbol not found: __Z4testv
  Referenced from: /Users/steigerwald/Downloads/51c2c087bdc3d586177db35e664ec6c8-9c442aef9c9c998457824a727454067d3f37e368/./bazel-bin/test
  Expected in: flat namespace

dyld: Symbol not found: __Z4testv
  Referenced from: /Users/steigerwald/Downloads/51c2c087bdc3d586177db35e664ec6c8-9c442aef9c9c998457824a727454067d3f37e368/./bazel-bin/test
  Expected in: flat namespace

Trace/BPT trap: 5

**Comment by rsteiger** [comment]
User error, was missing:

extern "C" { }

Perhaps a warning or linker error would have been useful. Marking this as closed.

**Comment by yuanzhedong** [comment]
Hi @rsteiger, what do you mean by missing `extern "C" { }`? I've got similar error with your demo code. Thanks!
