### ISSUE TITLE
Document / Example how to use external android dependency like: Appcompat-v7 

### ISSUE THREAD

**Issue by jvmvik** [bazelbuild/bazel#1428]
The Android documentation does not explain how to deals with external android dependency like: Appcompat-v7.
http://www.bazel.io/docs/tutorial/android-app.html

The example should also illustrate such common task.

**Comment by ahumesky** [comment]
Yes, this is all unfortunately under-documented, which we're working on.
The short answer is that you can depend on appcompat v7 with `@android-sdk//:appcompat_v7`
"Android Support Library" must be downloaded in the SDK manager for the dependency to work.

The the rules created for the SDK are available at
https://github.com/bazelbuild/bazel/blob/master/tools/android/android_sdk_repository_template.bzl

**Comment by aj-michael** [comment]
Keeping this issue open because this is still under-documented. In case anyone sees this in the future, the current syntax for external dependencies from the Android SDK is documented in issue #1745.

**Comment by aj-michael** [comment]
This was documented in c3c4f36d90f33cedc61a22ffd34daa72a36f1f7d. The docs are now live on https://bazel.build/versions/master/docs/be/workspace.html#android_sdk_repository.

**Comment by TastyPi** [comment]
Seems the android_sdk_repository is no longer documented on that page and @android-sdk//:appcompat_v7 no longer works. What's the correct way to add support library dependencies now?

**Comment by ahumesky** [comment]
The documentation has been moved to the Android rules page:
https://docs.bazel.build/versions/master/be/android.html#android_sdk_repository

**Comment by JakeWharton** [comment]
They're available from maven.google.com as standard Maven artifacts. There's no need to pull them from the SDK anymore.

**Comment by TastyPi** [comment]
Yeah, I started trying to get the Maven artifacts working but got stuck. See https://github.com/bazelbuild/bazel/issues/3633.
