### ISSUE TITLE
Bazel build java programe error

### ISSUE THREAD

**Issue by wuhuZhao** [bazelbuild/bazel#14282]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

```
ERROR: /private/var/tmp/_bazel_zhaohaokai/e08fe969eaf5b527102d1d41203352db/external/bazel_tools/tools/jdk/BUILD:346:14: Action external/bazel_tools/tools/jdk/platformclasspath.jar failed: (Exit 1): java failed: error executing command external/remotejdk11_macos/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' ... (remaining 6 argument(s) skipped)
```

my macbook use jdk8  but bazel always deafaultly use the jdk11 ,when i sync the bazel in idea , the error occured . i have tried a lot , but i can't find the resolution  

my JAVA_HOME is

```
/Library/java/JavaVirtualMachines/jdk1.8.0_291.jdk/Contents/Home
```
and 
```
HAOKAIZHAO-MB0 ~ % /usr/libexec/java_home -V
Matching Java Virtual Machines (2):
    1.8.301.09 (x86_64) "Oracle Corporation" - "Java" /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
    1.8.0_291 (x86_64) "Oracle Corporation" - "Java SE 8" /Library/Java/JavaVirtualMachines/jdk1.8.0_291.jdk/Contents/Home
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
```
and my idea version is 2020.2 community  and use the bazel plugin

bazel --version  is  4.2.0

**Comment by cushon** [comment]
> ```
> ERROR: /private/var/tmp/_bazel_zhaohaokai/e08fe969eaf5b527102d1d41203352db/external/bazel_tools/tools/jdk/BUILD:346:14: Action external/bazel_tools/tools/jdk/platformclasspath.jar failed: (Exit 1): java failed: error executing command external/remotejdk11_macos/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' ... (remaining 6 argument(s) skipped)
> ```

That line is showing part of the failing command, but not what the error is. What appears in the bazel log after that line?

**Comment by comius** [comment]
For compilation Bazel by default uses JDK11  (the path remote_jdk11 you see, means it uses JDK11 from remote repository).  

To execute itself Bazel uses JAVA_HOME  (https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/blaze_util_darwin.cc#L169). 

The run the code Bazel also uses JAVA_HOME (Bazel version 5.0.0 sets up JDK11 to produce code for JDK8 if that's in JAVA_HOME). How to set up older versions for JDK8, see https://docs.bazel.build/versions/4.2.1/bazel-and-java.html#configuring-the-jdk

**Comment by ken4ward** [comment]
This error still persists. I have been trying to build a simple project using Bazel for over 5 days. It's from one issue to another. Today, I ran into this issue:

ERROR: /project/steps/BUILD.bazel:1:13: Building project/steps/liblogin_steps.jar (2 source files) failed: (Exit 1): java failed: error executing command (from target project/steps:login_steps) external/remotejdk11_macos/bin/java -XX:-CompactStrings '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 18 arguments skipped)
Web/src/main/java/io/christdoes/com/steps/HomeSteps.java:29: error: cannot find symbol
        page.fill(homePage.getSearch(), productName);

I have JAVA_HOME setup. It works fine for other projects but only fails when trying to build with Bazel. Bazel ignores the local JAVA_HOME but always uses the remote JDK. I assume there are config differences of how the remote JDK builts which might not work on different systems. Someone please help. I have to present this project anytime soon.
