### ISSUE TITLE
`--ios_multi_cpus` defaults to x86_64 on M1 Macs

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/bazel#14284]
### Description of the problem / feature request:

`--ios_multi_cpus` should default to `sim_arm64` on M1 Macs, but still defaults to `x86_64`.

### Feature requests: what underlying problem are you trying to solve with this feature?

M1 Mac users shouldn't have to override `--ios_multi_cpus` to get the proper default.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build an `ios_application` target on an M1 Mac, see that the architecture is for the x86_64 simulator.

I think that this might be the issue:
https://github.com/bazelbuild/bazel/blob/e50b2034688990cc86c6aefa40b315f3a2e407f4/src/main/starlark/builtins_bzl/common/objc/transitions.bzl#L70-L73

https://github.com/bazelbuild/bazel/commit/d7628e1b566be353fe7172241ac8f15d5f8e7ff5 changed the default in one place already.

### What operating system are you running Bazel on?

macOS 11.6.1 (arm64)

### What's the output of `bazel info release`?

release 6.0.0-pre.20211101.2

**Comment by brentleyjones** [comment]
Probably can reopen https://github.com/bazelbuild/bazel/pull/13873 instead?

**Comment by keith** [comment]
That Pr Was merged so probably want a new one instead

**Comment by keith** [comment]
We think now this is likely related to this transition https://github.com/bazelbuild/rules_apple/pull/1154

**Comment by gregestren** [comment]
If https://github.com/bazelbuild/rules_apple/pull/1154 fixes this, can we mark as such in the description to close this issue when ready?

**Comment by brentleyjones** [comment]
Done. When it's merged it will close this.

**Comment by keith** [comment]
Didn't work because of ACL, but that's merged
