### ISSUE TITLE
Bazel HEAD and 5.0.0 RC2 breaks Worker sandboxing JSON worker communication

### ISSUE THREAD

**Issue by Bencodes** [bazelbuild/bazel#14293]
### Description of the problem / feature request:

Bazel HEAD breaks JSON worker communication by not sending `requestId` to the worker.

I was able to git bisect the issue back to this commit https://github.com/bazelbuild/bazel/commit/97643ad92d

I'm able to reproduce the issue by creating a worker implementation with the following execution requirements:

```python
    ctx.actions.run(
       ...
        execution_requirements = {
            "supports-workers": "1",
            "supports-multiplex-workers": "1",
            "requires-worker-protocol": "json",
        },
        ...
    )
```

And when streaming the `System#in` using a JSON reader, I see all work request fields except `requestId`. The worker executes as expected with worker sandboxing disabled using `--worker_sandboxing=false`.

**Comment by Bencodes** [comment]
@zshmeis I believe you added this commit

**Comment by Bencodes** [comment]
Cc @Wyverald

**Comment by meteorcloudy** [comment]
Ping @larsrc-google

**Comment by larsrc-google** [comment]
Sorry I missed this, must update my email filters.

My first guess is that the logic for falling back to singleplex under sandboxing is broken. Looking further into this.

**Comment by larsrc-google** [comment]
Wait, no, this is working as intended. Multiplex workers cannot be sandboxed (yet), so when asking for sandbox and multiplex, it falls back to singleplex to obey the sandboxing. You can confirm this by running with `--worker_verbose` and seeing the worker creation messages stating that they are sandboxed but not multiplex. As per protocol buffer standards, a missing int field should be understood as 0, which means it's a singleplex request.

**Comment by meteorcloudy** [comment]
Do I understand correctly that 97643ad didn't actually cause any regression? If so, @Bencodes can you confirm this? (I'll reopen this for now to make sure it's clarified)

**Comment by meteorcloudy** [comment]
ping @Bencodes

**Comment by brentleyjones** [comment]
Ben is out this week for Thanksgiving. I've pinged him to let him know about this though, so he might be able to respond sooner than Monday.

**Comment by meteorcloudy** [comment]
@brentleyjones Thank you!

**Comment by Bencodes** [comment]
> Do I understand correctly that 97643ad didn't actually cause any regression?

I do believe that this might be a regression of some sort, even if the prior behavior was incorrect given the spec. Using the same worker configuration as above with JSON and sandboxing enabled, I see the request IDs being incremented for each request to the worker.

**Comment by meteorcloudy** [comment]
@larsrc-google Is there anything we can do?

**Comment by larsrc-google** [comment]
@Bencodes Are you talking about the previous behaviour in your last comment? Otherwise I'm confused.

The point is what happens when you specify sandboxing and multiplex. Since multiplex doesn't allow sandboxing (yet), one or the other has to be turned off. Prior to that change, Bazel would actually lie about what it was doing and claim to be making a sandboxed multiplex worker, even to the point of naming the sandbox directories `multiplex-worker-<n>-<mnemonic>`. But there is a process for each worker, these are effectively singleplex workers that get requestids. That's also why your request ids have gaps, they get spread over 4 workers.

**Comment by keith** [comment]
Should multiplexing + worker sandboxing just be an error right now? Considering that worker sandboxing is disabled by default that seems relatively safe to me
