### ISSUE TITLE
string split/rsplit do not accept named parameters

### ISSUE THREAD

**Issue by nanaze** [bazelbuild/bazel#14309]
Python strings accept named parameters for the string.strip/rstrip functions

```
$ python3
>>> "a-b-c-d".split("-", maxsplit=2)
['a', 'b', 'c-d']
>>> "a-b-c-d".rsplit("-", maxsplit=2)
['a-b', 'c', 'd']
>>> 
```

I was surprised that this failed when used in a .bzl file

adding the following to src/test/java/net/starlark/java/eval/testdata/string_split.star will cause the test to fail

```
assert_eq("a-b-c-d".split("-", maxsplit=2), ["a", "b", "c-d"])
assert_eq("a-b-c-d".rsplit("-", maxsplit=2),  ["a-b", "c", "d"]);
```

error:
```
Error in split: split() got named argument for positional-only parameter 'maxsplit'
```

Marking these methods as "named" in src/main/java/net/starlark/java/eval/StringModule.java fixes the problem.

I have a Google-internal demonstration change at go/kvlhy

**Comment by brandjon** [comment]
Looks like we don't say in the spec whether maxsplit is a named param. Filed bazelbuild/starlark#210.
