### ISSUE TITLE
`extractArgumentsForDynamicLinkParamFile` causes arguments that start with `@rpath` to be interpreted as a param file

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/bazel#14316]
### Description of the problem / feature request:

While updating rules_apple we couldn't use `@rpath` arguments as it would result in a build failure. Instead we had to pass the arguments in a different way:

https://github.com/bazelbuild/rules_apple/pull/1207/files#diff-d84498974951b9a579baeeaf19d52ffb0a42a15b520c4359dac92448e2b806ceR670

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

This code needs to be updated to support arguments that start with `@rpath`:

https://github.com/bazelbuild/bazel/blob/1c3a2456c95fd19974a5b2bd33c5ebdb2b2277e4/src/main/java/com/google/devtools/build/lib/rules/cpp/LinkCommandLine.java#L295

### What operating system are you running Bazel on?

macOS 11.6.1

### What's the output of `bazel info release`?

5.0.0rc2

**Comment by keith** [comment]
FWIW this was a bit of an intentional tradeoff when we added params files support. In the shell scripts we check if the file exists, and assume that if it doesn't it's an intentional arg otherwise, so we could do the same here to fix it probably.

**Comment by sventiffe** [comment]
So is this working as intended?

**Comment by keith** [comment]
We should fix anywhere we can easily, but most of the time the recommendation is to change whoever is passing the flag to use the `-Wl,@rpath` format to avoid this.

**Comment by keith** [comment]
https://github.com/bazelbuild/bazel/pull/14650

**Comment by brentleyjones** [comment]
@bazel-io fork 5.1
