### ISSUE TITLE
validateDirectPrerequisiteFileTypes fails for empty filegroup in label_list

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#1431]
I have a filegroup `foo` which is actually an empty list (just so every package exposes this filegroup).
Now if I use `foo` for an attribute

```
"foo_list": attr.label_list(allow_files=[".blub"])
```

analysis complains that `foo` never produces a `.blub` file.
The error seems to be produced from https://github.com/bazelbuild/bazel/blob/0e17046797f6cfed21755f2eed7c52c0a340d40c/src/main/java/com/google/devtools/build/lib/analysis/RuleContext.java#L1713

Reading the comment above in the code I am wondering whether this is an oversight in `validateDirectPrerequisiteFileTypes` or intended this way.

IMO the check is wrong. From reading the documentation I would expect it to test every `sourceArtifact.getFilename()` and call `attributeError` for the first failing test.

**Comment by philwo** [comment]
I think you're right regarding the wrong check - would you like to send us a patch? I could code review it and get it merged quickly. :)

**Comment by philwo** [comment]
Assigning to Ulf just to make sure I'm not missing something here.

**Comment by ulfjack** [comment]
I think it's reasonable to have it accept an empty list rather than error on an empty list.

**Comment by ulfjack** [comment]
Wrong button. Sorry.

**Comment by kyliau** [comment]
@ulfjack Some guidance on adding test case, please?

This is the Bazel files I used to test:

```
# BUILD
load(":myrule.bzl", "my_rule")

filegroup(
  name = "empty",
  srcs = [],
)

my_rule(
  name = "foo",
  srcs = [":empty"],
)
```

```
# myrule.bzl
def _my_rule_impl(ctx):
  return []

my_rule = rule(
  implementation = _my_rule_impl,
  attrs = {
    "srcs": attr.label_list(
      allow_files = [".xyz"],
    ),
  }
)
```

Behavior before change:
```
BUILD:10:10: in srcs attribute of my_rule rule //:foo: '//:empty' does not produce any my_rule srcs files (expected .xyz)
```

Behavior after change:
```
Build completed successfully
```

**Comment by kyliau** [comment]
similar to #7516

**Comment by ulfjack** [comment]
I think this has the infrastructure to run Starlark tests and check for analysis errors:
https://github.com/bazelbuild/bazel/blob/master/src/test/java/com/google/devtools/build/lib/skylark/SkylarkRuleContextTest.java

There isn't currently a test there to check the code in question, but there are tests that look similar enough to me, i.e., I would start there to try to write a test for this.

**Comment by brandjon** [comment]
As best I can tell, this issue is now a special case of #7516, which intends to decide whether the change suggested here is desirable. Closing this as a (retroactive) dup.
