### ISSUE TITLE
tensorflow building issue on ubuntu 14.04: missing input file '@grpc//:src/core/lib/support/tmpfile.h'.

### ISSUE THREAD

**Issue by YongCHN** [bazelbuild/bazel#1432]
Has anyone encountered similar issue?

ERROR: missing input file '@grpc//:src/core/lib/support/tmpfile.h'.
ERROR: /home/yong/workarea/gitlab/tensorflow/tensorflow/contrib/metrics/BUILD:31:1: Creating runfiles tree bazel-out/host/bin/tensorflow/contrib/metrics/gen_set_ops_py_wrappers_cc.runfiles [for host] failed: build-runfiles failed: error executing command /home/yong/.cache/bazel/_bazel_yong/1fca9a2a43129bbfd1d77a89027ab9c0/execroot/tensorflow/_bin/build-runfiles bazel-out/host/bin/tensorflow/contrib/metrics/gen_set_ops_py_wrappers_cc.runfiles_manifest ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 15.
ERROR: /home/yong/.cache/bazel/_bazel_yong/1fca9a2a43129bbfd1d77a89027ab9c0/external/grpc/BUILD:38:1: @grpc//:gpr: missing input file '@grpc//:src/core/lib/support/tmpfile.h'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/yong/.cache/bazel/_bazel_yong/1fca9a2a43129bbfd1d77a89027ab9c0/external/grpc/BUILD:38:1 1 input file(s) do not exist.
INFO: Elapsed time: 3.404s, Critical Path: 1.59s

**Comment by philwo** [comment]
```Process terminated by signal 15``` sounds like one of the tools crashed.

Could you run the build again using --verbose_failures, which should print the full command-line of the failed command? Maybe running that command yourself in a terminal prints more helpful errors?

Feel free to also paste the output of the build using --verbose_failures here.
