### ISSUE TITLE
Rename non_empty

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#1433]
Aside from possible double negative, it is not totally clear what the Parameter `non_empty` (e.g. in `attr.label_list`) does from the name alone. IMO renaming it to `allow_empty` would make meaning and values clearer.

**Comment by laurentlb** [comment]
Good idea! We'll discuss it in our next design meeting. Thanks!

**Comment by ulfjack** [comment]
non_empty is deprecated, so this feature request is technically done. Should we keep this issue open for the removal of non_empty or should we move that to a separate issue?

**Comment by laurentlb** [comment]
Removal will be tracked on https://github.com/bazelbuild/bazel/issues/5818
