### ISSUE TITLE
py_binary can not be used on Windows with the sandbox and custom python runtime created by repository rule

### ISSUE THREAD

**Issue by loshca** [bazelbuild/bazel#14350]
### Description of the problem:

I am trying launch a py_binary as an executable in my custom rule with custom python runtime created by repository rule.
Without sandbox it works, but with sandbox it fails with `LAUNCHER ERROR: Cannot launch process: "python.exe` error.

I found that there is a launcher for windows [which requires a manifest file](https://github.com/bazelbuild/bazel/blob/56d624be4dc79a94ed763c07d302c6270bc8c43b/src/tools/launcher/launcher.cc#L84), I also checked the command line for the sandbox and found there is no manifest file in it, so launcher tries to find python in the wrong place. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I created the repo to reproduce: https://github.com/loshca/bazel_python_repro/tree/main

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

4.2.0

###  Have you found anything relevant by searching the web?

No

**Comment by comius** [comment]
I don't think you can define a python toolchain by simply exporting python.exe and not the other dependencies. I believe there exist working hermetic Python toolchains.

**Comment by loshca** [comment]
@comius 

> I don't think you can define a python toolchain by simply exporting python.exe and not the other dependencies. I believe there exist working hermetic Python toolchains.

That's a problem, the non hermetic toolchain works as a charm!

But when I'm trying to add **hermetic** toolchain [here](https://github.com/loshca/bazel_python_repro/blob/712e5f784972b686a1a67308779473fb06238d0a/BUILD.bazel#L5) it fails, because of the windows launcher specialty.
