### ISSUE TITLE
could not link to the class constructor library

### ISSUE THREAD

**Issue by linghuchong-bayarea** [bazelbuild/bazel#14362]
### Description of the problem / feature request:

When the constructor is defined in C++, cc_test could not link the library

in task.h file
```

class Task
  {
  public:
    Task(const std::string &name,
         std::function<void()> &&f,
         const absl::Time &run_time,
         bool repeat = false,
         const absl::Duration &interval = absl::Seconds(0))
        : name_(name), f_(f), repeat_(repeat), interval_(interval), run_time_(run_time)
    {
    }

    Task(const std::string &name,
         std::function<void()> &&f,
         const std::string &run_time,
         const std::string &time_zone,
         bool repeat = false,
         const absl::Duration &interval = absl::Seconds(0))
        : name_(name), f_(f), repeat_(repeat), interval_(interval)
    {
      run_time_ = util::ParseFromString(run_time, time_zone);
    }

    virtual ~Task() {}

    void Run();

    void IncrementRunTime();

    bool GetRepeat();

    absl::Time GetRunTime();

    std::string GetName();

  private:
    std::string name_;

    std::function<void()> f_;

    bool repeat_;

    absl::Duration interval_;

    absl::Time run_time_;
  };
```

in client.cpp file

```
shared_ptr<Task> begin_task =
                make_shared<Task>(
                    StrJoin({string("begin_task_for_client"), config_.name()}, "_"),
                    [this]()
                    {
                       // a bunch of work.
                    },
                    begin_time,
                    true,
                    Hours(24));

            Scheduler::Get().InsertTask(begin_task);
```

if I define the constructor in .h file, cc_test build fine.

But if I define the constructor in .cpp file, cc_test build gives this error

gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/system/module/data/client/client_test-2.params

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-opt/bin/_solib_k8/libsystem_Smodule_Sdata_Sclient_Slibclient.so: error: undefined reference to 'module::Task::Task(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()>&&, absl::lts_20210324::Time const&, bool, absl::lts_20210324::Duration const&)'
collect2: error: ld returned 1 exit status

### Feature requests: what underlying problem are you trying to solve with this feature?

N/A

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Seems a link error.

### What operating system are you running Bazel on?

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

### What's the output of `bazel info release`?

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

release 4.2.1

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

fatal: ambiguous argument 'master': unknown revision or path not in the working tree.

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

N/A

**Comment by linghuchong-bayarea** [comment]
Some dependency analysis

```
bazel query "allpaths(:ctp_future_data_client_test, //system/module/scheduler:task)" --output graph
digraph mygraph {
  node [shape=box];
  "//system/module/data/client:ctp_future_data_client_test"
  "//system/module/data/client:ctp_future_data_client_test" -> "//system/module/data/client:ctp_future_data_client"
  "//system/module/data/client:ctp_future_data_client"
  "//system/module/data/client:ctp_future_data_client" -> "//system/module/scheduler:scheduler"
  "//system/module/scheduler:scheduler"
  "//system/module/scheduler:scheduler" -> "//system/module/scheduler:thread_pool"
  "//system/module/scheduler:thread_pool"
  "//system/module/scheduler:thread_pool" -> "//system/module/scheduler:task"
  "//system/module/scheduler:task"
}
```

**Comment by oquenchil** [comment]
Please ask on StackOverflow for support.
