### ISSUE TITLE
`http_file` and `http_archive` can't make authenticated calls to Azure storage

### ISSUE THREAD

**Issue by robin-wayve** [bazelbuild/bazel#14372]
### Description of the problem / feature request:

Allow extra request headers to be passed to `http_archive` / `http_file`

### Feature requests: what underlying problem are you trying to solve with this feature?

In order to download files from private Azure Storage, clients need to provide an OAuth2 token (which can be done via `auth_patterns` and a `netrc` file) and additionally set an `x-ms-version` header.

Docs: https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-azure-active-directory

### What operating system are you running Bazel on?

Ubuntu Linux 18.04

### What's the output of `bazel info release`?

release 4.2.1

###  Have you found anything relevant by searching the web?

We checked if this might be possible through bazel-skylib or `repository_ctx.download(_and_extract)` but it does not seem so.

**Comment by thekyz** [comment]
This is a must have for companies relying on Azure for their cloud services (and can probably be used for other things as well).

**Comment by tjgq** [comment]
You should be able to use a [credential helper](https://github.com/bazelbuild/proposals/blob/main/designs/2022-06-07-bazel-credential-helpers.md) to do this.

**Comment by robin-wayve** [comment]
So this closes with the 6.3.0 release?

**Comment by tjgq** [comment]
Yes, 6.3.0 will be the first release to support this (it was cherry picked in https://github.com/bazelbuild/bazel/pull/18429).
