### ISSUE TITLE
py_rules.bzl no longer exported into @bazel_tools

### ISSUE THREAD

**Issue by ioctl0** [bazelbuild/bazel#1438]
It appears the only .bzl file in tools/build_rules that's accessible is test_rules.bzl

**Comment by philwo** [comment]
@lberki Could you have a look at this for triaging? I'm not sure where this bug report fits best.

**Comment by lberki** [comment]
I'm inclined to close this as Working As Intended, since Bazel has native Python rules, which work better than the Skylark rules in this file. What do @ioctl0 , what do you need this file for?
