### ISSUE TITLE
Bazel 4.2.2 cannot build gerrit plugin, target not declared in package plugins, 'target pattern parsing failed"

### ISSUE THREAD

**Issue by PengKuang** [bazelbuild/bazel#14382]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

I couldn't build the Gerrit plugin we developed under the Gerrit tree (3.5.2)/directory. 

### Feature requests: what underlying problem are you trying to solve with this feature?

use Bazel to build a Gerrit plugin

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. clone the gerrit tree
"git clone https://gerrit.googlesource.com/gerrit"
2. cd to the gerrit tree and run "bazel build gerrit"
3. git clone my plugin repo to the gerrit tree
4. run "bazel build plugins/xxxx-gerrit-plugin"

### What operating system are you running Bazel on?

ubuntu 20.04

### What's the output of `bazel info release`?

xxxx@lap955:~/gerrit-tree/gerrit$ sudo bazel build plugins/name-gerrit-plugin
Starting local Bazel server and connecting to it...
INFO: Invocation ID: b0866822-aa44-4030-9fac-43c1b367140b
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=73
INFO: Reading rc options for 'build' from /home/xxxx/gerrit-tree/gerrit/.bazelrc:
  'build' options: --workspace_status_command=python3 ./tools/workspace_status.py --repository_cache=~/.gerritcodereview/bazel-cache/repository --action_env=PATH --disk_cache=~/.gerritcodereview/bazel-cache/cas --java_toolchain=//tools:error_prone_warnings_toolchain_java11 --incompatible_strict_action_env --announce_rc --experimental_worker_multiplex=false
ERROR: Skipping 'plugins/name-gerrit-plugin': no such target '//plugins:name-gerrit-plugin': target 'name-gerrit-plugin' not declared in package 'plugins' defined by /home/xxxx/gerrit-tree/gerrit/plugins/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//plugins:name-gerrit-plugin': target 'name-gerrit-plugin' not declared in package 'plugins' defined by /home/xxxx/gerrit-tree/gerrit/plugins/BUILD
INFO: Elapsed time: 10.093s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Starting local Bazel server and connecting to it...
INFO: Invocation ID: 4018f21d-c996-4ef1-9b53-f5fc5f8b07f0
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=95
INFO: Reading rc options for 'info' from /home/xxxxx/gerrit-tree/gerrit/.bazelrc:
  Inherited 'build' options: --workspace_status_command=python3 ./tools/workspace_status.py --repository_cache=~/.gerritcodereview/bazel-cache/repository --action_env=PATH --disk_cache=~/.gerritcodereview/bazel-cache/cas --java_toolchain=//tools:error_prone_warnings_toolchain_java11 --incompatible_strict_action_env --announce_rc --experimental_worker_multiplex=false
release 4.0.0

I built bazel using apt install tool

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

[
](https://gerrit.googlesource.com/gerrit
aac93a16b5c3c02b301089e6e7f65cd285e626de
aac93a16b5c3c02b301089e6e7f65cd285e626de
)

###  Have you found anything relevant by searching the web?

https://github.com/protocolbuffers/protobuf/issues/3677

> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?
Nil
>
> If the files are large, upload as attachment or provide link.

**Comment by PengKuang** [comment]
It turns out that the plugin I want to build should be placed in the gerrit/plugins directory instead of the WORKPLACE. But I ran into this new error:

`xxxxx@xxxx:~/gerrit-tree/gerrit$ bazel build plugins/mean-gerrit-plugin
INFO: Invocation ID: 96205193-3a20-4243-b791-70d314ad0b76
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'build' from /home/xxxx/gerrit-tree/gerrit/.bazelrc:
  'build' options: --workspace_status_command=python3 ./tools/workspace_status.py --repository_cache=~/.gerritcodereview/bazel-cache/repository --action_env=PATH --disk_cache=~/.gerritcodereview/bazel-cache/cas --java_toolchain=//tools:error_prone_warnings_toolchain_java11 --incompatible_strict_action_env --announce_rc --experimental_worker_multiplex=false
ERROR: Traceback (most recent call last):
	File "/home/xxxx/gerrit-tree/gerrit/plugins/mean-gerrit-plugin/BUILD", line 29, column 18, in <toplevel>
		polygerrit_plugin(
	File "/home/xxxxx/gerrit-tree/gerrit/tools/bzl/js.bzl", line 53, column 5, in polygerrit_plugin
		def polygerrit_plugin(name, app, plugin_name = None):
Error: polygerrit_plugin() got unexpected keyword argument: srcs
ERROR: error loading package 'plugins/mean-gerrit-plugin': Package 'plugins/mean-gerrit-plugin' contains errors
INFO: Elapsed time: 1.875s
INFO: 0 processes.`

It seems this is caused by the srcs attribute for the ploygerrit plugin in my BUILD file:
`polygerrit_plugin(
    name = "feedback-button",
    srcs = glob([
        "feedback-button/*.html",
        "feedback-button/*.js",
    ]),
    app = "mean.html",
)`
But if I commented it out, I will see a new error like this:

`xxxxx@xxxxx:~/gerrit-tree/gerrit$ bazel build plugins/mean-gerrit-plugin
Starting local Bazel server and connecting to it...
INFO: Invocation ID: aa2efd79-7a88-4940-a8ac-925e4d857c07
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'build' from /home/xxxxx/gerrit-tree/gerrit/.bazelrc:
  'build' options: --workspace_status_command=python3 ./tools/workspace_status.py --repository_cache=~/.gerritcodereview/bazel-cache/repository --action_env=PATH --disk_cache=~/.gerritcodereview/bazel-cache/cas --java_toolchain=//tools:error_prone_warnings_toolchain_java11 --incompatible_strict_action_env --announce_rc --experimental_worker_multiplex=false
ERROR: /home/xxxxx/gerrit-tree/gerrit/plugins/mean-gerrit-plugin/BUILD:29:18: in src attribute of terser_minified rule //plugins/mean-gerrit-plugin:feedback-button.min: source file '//plugins/mean-gerrit-plugin:mean.html' is misplaced here (expected .js, .map or .mjs). Since this rule was created by the macro 'polygerrit_plugin', the error might have been caused by the macro implementation
ERROR: /home/xxxxx/gerrit-tree/gerrit/plugins/mean-gerrit-plugin/BUILD:29:18: in src attribute of terser_minified rule //plugins/mean-gerrit-plugin:feedback-button.min: '//plugins/mean-gerrit-plugin:mean.html' does not produce any terser_minified src files (expected .js, .map or .mjs). Since this rule was created by the macro 'polygerrit_plugin', the error might have been caused by the macro implementation
ERROR: Analysis of target '//plugins/mean-gerrit-plugin:mean-gerrit-plugin' failed; build aborted: Analysis of target '//plugins/mean-gerrit-plugin:feedback-button.min' failed
INFO: Elapsed time: 33.849s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (226 packages loaded, 5528 targets\
 configured)`

How can I resolve this?

**Comment by oquenchil** [comment]
Please ask on StackOverflow for support or contact the authors of polygerrit_plugin.
