### ISSUE TITLE
Wrong encoding of filename in bazel action inputs

### ISSUE THREAD

**Issue by appuser999** [bazelbuild/bazel#14381]
### Description of the problem / feature request:
Hi,
  I got the following error when using remote execution: `FileNotFoundError: [Errno 2] No such file or directory: 'xxx/task/docs/qtaweb部署.txt'`
Then I printed the information of the action using `bazel aquery` and found that there is an problem in the file name.

![image](https://user-images.githubusercontent.com/7702772/144813595-8871b43c-8f1e-46d7-b1a9-906c5194be1d.png)

### What operating system are you running Bazel on?
CentOS 7.6

### What's the output of bazel info release?

release 3.7.2

### Have you found anything relevant by searching the web?

I tried to modify the .bazelrc file by adding `startup --host_jvm_args=-Dfile.encoding=en_US.UTF-8`
Then I retry and find that the problem still exists.
Checking the process cmdline shows that the changes have not taken effect and the old settings are still in place.

![image](https://user-images.githubusercontent.com/7702772/144813937-c6401e0f-ca0f-4813-bf7d-810f25717ed2.png)

How can I solve this problem?
Thanks.

**Comment by appuser999** [comment]
Querying the action inputs information stored in the rbe cluster, the file name also has an encoding error problem. Then we can confirm that the cause is due to bazel local server.

<img width="1066" alt="2a9ab0d1-66fc-4f93-8b3a-f970354d1034" src="https://user-images.githubusercontent.com/7702772/144844613-f9d4f0ee-e654-483c-829a-f89eaa3d1f00.png">

**Comment by tjgq** [comment]
@appuser999, do you have a minimal self-contained repro? Or, failing that, could you tell us which rule this file is an input to?

Bazel has some limitations in this area because it was originally designed for ASCII-only filenames. #374 tracks fixing this in its entirety, but that's a large undertaking. With more concrete information, I might be able to fix the specific instance you're facing.

**Comment by appuser999** [comment]
rules_go go_test.  I've changed all the file names to avoid this problem. Thanks

**Comment by jmillikin** [comment]
I've encountered the same issue. Here's a minimal reproduction:

```python
# BUILD
load("//:rules.bzl", "unicode_args")
unicode_args(name = "unicode_args", greeting = glob(["*.txt"])[0])
```

```python
# rules.bzl
def _unicode_args(ctx):
    out_file = ctx.actions.declare_file(ctx.attr.name)
    ctx.actions.run_shell(
        inputs = [],
        outputs = [out_file],
        command = 'echo "$1" > "$2"',
        arguments = [ctx.file.greeting.path, out_file.path],
    )
    return DefaultInfo(files = depset([out_file]))

unicode_args = rule(
    implementation = _unicode_args,
    attrs = {
        "greeting": attr.label(allow_single_file = True),
    },
)
```

```
$ bazel-5.1.0 build --config=remote //:unicode_args
[...]
Target //:unicode_args up-to-date:
  bazel-bin/unicode_args
$ ls *.txt
挨拶.txt
$ cat bazel-bin/unicode_args
æ¨æ¶.txt
$ python3 -c 'print(open("bazel-bin/unicode_args", "rb").read())'
b'\xc3\xa6\xc2\x8c\xc2\xa8\xc3\xa6\xc2\x8b\xc2\xb6.txt\n'
```

The corrupted filename was generated by treating UTF-8 bytes as Unicode:
```
>>> "挨拶".encode("utf8")
b'\xe6\x8c\xa8\xe6\x8b\xb6'
>>> "\xe6\x8c\xa8\xe6\x8b\xb6".encode("utf8")
b'\xc3\xa6\xc2\x8c\xc2\xa8\xc3\xa6\xc2\x8b\xc2\xb6'
```

**Comment by jmillikin** [comment]
Proposed fix: https://github.com/bazelbuild/bazel/pull/15333

**Comment by brentleyjones** [comment]
@bazel-io flag
