### ISSUE TITLE
Using tmpfs as output_user_root leads to an error

### ISSUE THREAD

**Issue by JSGette** [bazelbuild/bazel#14388]
### Description of the problem / feature request:

1. Mount tmpfs to your system
2. Add `startup --output_user_root=/tmpfs/bazel_cache` into .bazelrc. (Use tmpfs as output_user_root)
It leads to a following error independent of command:
> Extracting Bazel installation...
> Starting local Bazel server and connecting to it...
> FATAL: waitpid failed: (error: 10): No child processes

I tried bazel version, bazel build //..., bazel test.

**Comment by meisterT** [comment]
I can't repro this. What version of Bazel are you using?

**Comment by dpoluyanov** [comment]
Had the same issue today. In my case it was caused by `noexec` option in `/etc/fstab` for bazel project directory, so I'd recommend to check whether `/tmpfs/bazel_cache` mounted with `noexec` option or not in your case

**Comment by bonly** [comment]
same issue in guix system
