### ISSUE TITLE
Bazel patch for tool/action specific CPU time

### ISSUE THREAD

**Issue by jijizg** [bazelbuild/bazel#14402]
### Description of the problem / feature request:

The CPU times reported in bazels profile log and build event logs, only include bazels own CPU consumption, not invoked tools such as compilers.

### Feature requests: what underlying problem are you trying to solve with this feature?

Bazel has partial support for messuring user and system cpu time for everything executed in sandbox by enabling --experimental_collect_local_sandbox_action_metrics.
Bazel has support for collecting the measurements and store internally in ActionResult.java, but the numbers are currently not reported in any log file.
This feature request is about reporting cpu user time and cpu system time per tool/action. it could be store in profile file like:

    {"cat":"action processing",
     "name":"Compiling foo.c",
     "ph":"X",
     "ts":4797014,
     "dur":168969,
     "pid":1,
     "args":{"mnemonic":"CppCompile", "cpuTimeUser":45678, "cpuTimeSystem":12345},
     "tid":310}

**Comment by KevinKe-kk** [comment]
May I know the progress of this request? Thanks a lot.

**Comment by larsrc-google** [comment]
Sorry, none of us have had time to work on this.
