### ISSUE TITLE
Bazel@HEAD prevents modules from using `//visibility`

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#14403]
### Description of the problem / feature request:

With Bazel@HEAD, specifically 103ea9d3f3a0d85a0d7c1ad98fd8dbb422505d95, modules are no longer able to see the now removed "default" repository via repo mappings. This makes it an error if a module references `//visibility`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
git clone https://github.com/fmeum/rules_jni
cd rules_jni/tests
USE_BAZEL_VERSION=103ea9d3f3a0d85a0d7c1ad98fd8dbb422505d95 bazel test --config=bzlmod //...
```
prints
```
ERROR: /home/fmeum/.cache/bazel/_bazel_fmeum/27ab8d6bcf9e822e87fc15cbcbda5200/external/bazel_skylib.1.0.3/toolchains/unittest/BUILD:5:15: no such package 'visibility': Invalid package reference visibility crosses into repository @: did you mean to use visibility instead? and referenced by '@bazel_skylib.1.0.3//toolchains/unittest:toolchain_type'
ERROR: /home/fmeum/.cache/bazel/_bazel_fmeum/27ab8d6bcf9e822e87fc15cbcbda5200/external/bazel_skylib.1.0.3/toolchains/unittest/BUILD:5:15: no such package 'visibility': Invalid package reference visibility crosses into repository @: did you mean to use visibility instead? and referenced by '@bazel_skylib.1.0.3//toolchains/unittest:toolchain_type'
ERROR: /home/fmeum/git/rules_jni/tests/analysis/cc_jni_library/BUILD.bazel:3:11: While resolving toolchains for target //analysis/cc_jni_library:platform_collision_test: com.google.devtools.build.lib.skyframe.ConfiguredValueCreationException: Analysis failed
ERROR: Analysis of target '//analysis/cc_jni_library:platform_collision_test' failed; build aborted: 
INFO: Elapsed time: 8.957s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (14 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (14 packages loaded, 0 targets configured)
    Fetching https://bcr.bazel.build/bazel_registry.json
```
### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

`development version`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Used Bazelisk to download  103ea9d3f3a0d85a0d7c1ad98fd8dbb422505d95

###  Have you found anything relevant by searching the web?

The removal of [this line](https://github.com/bazelbuild/bazel/commit/103ea9d3f3a0d85a0d7c1ad98fd8dbb422505d95#diff-126fa441a9a0c29c84c9ae48ef384fc7c1e9916851c963d0f6f7042838ddca98L85) appears to be responsible. Adding `repositoryName.equals(RepositoryName.MAIN) ||` to the condition fixes the issue.

@Wyverald

**Comment by Wyverald** [comment]
oops! thanks for the report. I'll try to fix this ASAP.

**Comment by Wyverald** [comment]
Update: I didn't get around to the actual fix (adding the "MAIN" check isn't the long-term solution). Hopefully I can land the fix early next week.
