### ISSUE TITLE
I need a way to not scan all external files on every command

### ISSUE THREAD

**Issue by ptarjan** [bazelbuild/bazel#14400]
### Description of the problem / feature request:

I'd like an equivalent feature to `--noexperimental_check_output_files` but for all external files. These files aren't touched by developers in our CI.

### Feature requests: what underlying problem are you trying to solve with this feature?

We have a large monorepo at Robinhood with many many external files (tons of `pypi` and `npm` packages). In our CI testing environment we run `bazel test //...` for every commit. We also run other small `bazel run` commands and `bazel query` commands in the test runner script to do various other tasks but each of them currently takes 24 seconds irrespective of their complexity because of the `fsvc.getDirtyKeys` task. In the logs we see things like:
```
211209 17:31:21.590:I 1004 [com.google.devtools.build.lib.skyframe.FilesystemValueChecker.lambda$getDirtyValues$2] Spent 24383190001 nanoseconds checking 2987282 filesystem nodes (10254570 scanned)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Make a project with 10M external files. See that no matter what, your `bazel run` and even `bazel info` times will be 24 seconds.

### What operating system are you running Bazel on?

Linux and OSX

### What's the output of `bazel info release`?

```
release 4.2.0
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

(not a public repo)

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by janakdr** [comment]
@ptarjan thanks for the report. I see that you have a commit to fix this. Are you interested in submitting it to Bazel? (I must admit to not knowing much about the aspect-build/bazel fork.)

**Comment by keith** [comment]
@janakdr PR is here https://github.com/bazelbuild/bazel/pull/14404

**Comment by janakdr** [comment]
Great, thanks!
