### ISSUE TITLE
License is inconsistent with visibility, other properties. Needs simplification/better opensource support.

### ISSUE THREAD

**Issue by michaelsafyan** [bazelbuild/bazel#1440]
For consistency, package-level `license()` should be replaced with `default_license` in the `package()` declaration (to mimic the `default_visibility` and `default_testonly` declarations).

On top of this, I think the value of `license` should be a target, not a simple string so that you can more properly specify the license (including the text). That is, it should be possible to define something like:

```
     license(
        name = "simplified_bsd",
        srcs = ["simplified_bsd.txt"],
        copyleft = false,
        modification_allowed = true,
        ... other properties ....
     )
```

And then elsewhere:

```
     # third_party/some/package
     package(
          default_license = ["//licenses/opensource:simplified_bsd"]
     )
```

If that were done, it would also be ideal to provide a github repo with such license declarations already predefined, so that one can easily refer to licenses by their name (like "//licenses/opensource:gpl_v3"), without having to figure out if they are "unencumbered", "restricted", "reciprocal", etc.

**Comment by philwo** [comment]
This is a very nice idea. Thanks :)

**Comment by rahul-malik** [comment]
@philwo - Any chance this can be prioritized sooner than 1.0? Debating writing a custom skylark rule to get around this if not

**Comment by philwo** [comment]
@ulfjack Any idea on this?

**Comment by ulfjack** [comment]
I'm afraid we won't be able to work on this sooner than 'some time next year'. It's a big change, and we'll have to run it by a number of stakeholders that are using the existing system. If someone wants to write up a more complete proposal, I'd be happy to run it by our internal stakeholders and provide feedback.

**Comment by aiuto** [comment]
Obsolete. Please follow the issue in #7444
