### ISSUE TITLE
FR: bias build order towards current workspace (rather than external)

### ISSUE THREAD

**Issue by dhalperi** [bazelbuild/bazel#14406]
### Description of the problem / feature request:

We have tasks like "can I upgrade to a new version of an external dependency (rules_foo, external C++ project, external Java project, etc)?". Often, the easiest answer is to just try.

Suppose the external project made a breaking API change. I'd like to find that as quickly as possible. 

For example, suppose if I have to build a local Java library `//:a` that depends on an external Java library `@ext//:b`. Suppose that we can get `b`'s hjar quickly, but the full `libb.jar` and all its transitive dependencies takes 20 minutes. I'd like to build `liba.jar` as soon as its direct compile dependencies are ready, rather than waiting for all the transitive libraries to be built.

I believe this generalizes to testing as well -- start running local unit tests if parts of the external workspace are built, without waiting for the full compilation.

I'm sure this problem is smaller with arbitrary resources in remote builders and executors, but that's just not the reality in smaller outfits.

### Feature requests: what underlying problem are you trying to solve with this feature?

Bias (compile, test, run) towards the current repository rather than external repositories, so things like build steps or test suites fail faster.

### What operating system are you running Bazel on?

macOS latest

### What's the output of `bazel info release`?

release 4.2.1

###  Have you found anything relevant by searching the web?

I created this Slack thread (right before leave, so it's a month old): https://bazelbuild.slack.com/archives/CA31HN1T3/p1635797351174800

**Comment by Wyverald** [comment]
This actually doesn't necessarily seem to be a main vs external repo thing; we should probably always try to build the target nearer to the top-level target if possible (which would conveniently solve this).

I have no idea how feasible this is, though. If we want to change the build order, the hardest part certainly isn't telling whether a file is from the main repo or an external repo.

Assigning to the performance team to take a look. (IMO this isn't very high priority in any case.)

**Comment by meisterT** [comment]
Actually when thinking about performance, you probably want first to build the things that are the furthest from the top level targets first because they likely have the longest critical path.

That being said: we do have some ongoing work to merge analysis and execution phases which in summary will start executing as soon as a subgraph of a top level target has been analyzed completely. That might address the suggestion to "start running local unit tests" naturally.
