### ISSUE TITLE
Is there any instability in sandbox mounting?

### ISSUE THREAD

**Issue by yejw5** [bazelbuild/bazel#14410]
### Description of the problem / feature request:

We have implemented a CUDA bazel toolchain for cross compiling. And then nvcc will generate intermedia temporary files in `/tmp` directory, which is mounted in every compiling action in bazel sandbox. However we have encountered with random error like:

```
ptxas fatal   : Input file '/tmp/tmpxft_00000017_00000000-0' could not be opened
ptxas fatal   : Ptx assembly aborted due to errors
```

The message may be caused by no permission to `/tmp` directory or the device has no space. But when we retry the building (or try a few times), the building will come to success. And the left storage is enough. So it looks like the `/tmp` directory inaccessible occasionally. Therefore, we tried nvcc `--keep` option to avoid the most temporary file generated in `/tmp` directory, and the success rate in one time building reached to about 90% (only 20% before). The related discussion in Nvidia forums located at: https://forums.developer.nvidia.com/t/avoid-generating-temp-files-in-tmp-while-nvcc-compiling/197657

So is there any instability in sandbox mounting like my case at one time? And this error may not be caused by bazel sandbox, just looking for help...

### What operating system are you running Bazel on?

> ubuntu18.04

### What's the output of `bazel info release`?

> 4.1.1

**Comment by meisterT** [comment]
I wonder if this is the same as https://github.com/bazelbuild/bazel/issues/3236

Can you please try https://github.com/bazelbuild/bazel/issues/3236#issuecomment-587752609 ?

**Comment by yejw5** [comment]
@meisterT 

Yeap! We have many tries on this problem. It seems that `nvcc` will use `pid` to generate temporary files in `/tmp` directory. But the `/tmp` is shared in multi sandboxes and the conflicts happened. So we fix the problem with bazel option `--sandbox_add_mount_pair=.:/tmp` at last. It seems working the same with `--sandbox_tmpfs_path=/tmp` in https://github.com/bazelbuild/bazel/issues/3236#issuecomment-587752609
