### ISSUE TITLE
Enable spaces in exports_files

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#1441]
We put a binary Python archive in an external repo.

For that repository we had the `BUILD` file:

    all_files = glob(["**"])

    exports_files(srcs=all_files)

which is making Bazel complain about a target having a space (setuptools has a file with spaces in basename). Which I understand as a limitation for targets, but it is not always an option to remove paths with spaces from thirdparty libraries.

**Comment by philwo** [comment]
The fact that not all filenames are valid label identifiers is unfortunately a long-standing issue with Bazel. I totally agree with you here, that this should just work. Unfortunately a lot of code currently relies on the fact that labels contain no special characters or whitespace - it will take a while to sort this all out. We hope to fix this soon, though!

**Comment by kchodorow** [comment]
Possibly a dup of #167.

**Comment by damienmg** [comment]
Definitely dup of #167
