### ISSUE TITLE
Official Bazel Docker container has not been released since 3.5.0

### ISSUE THREAD

**Issue by ipopov** [bazelbuild/bazel#14413]
The Bazel website advertises the availability of Bazel as a Docker container: https://docs.bazel.build/versions/4.2.2/bazel-container.html.

However, this container seems not to have been built or published since version 3.5.0, in September 2020. This is easy to verify by navigating to https://l.gcr.io/google/bazel.

**Comment by alexeagle** [comment]
This is tracked in https://github.com/bazelbuild/continuous-integration/issues/1060

**Comment by meteorcloudy** [comment]
Duplicated issue: https://github.com/bazelbuild/bazel/issues/12367
