### ISSUE TITLE
Inconsistent behavior between rdeps and allrdeps

### ISSUE THREAD

**Issue by segonpin** [bazelbuild/bazel#14438]
### Description of the problem / feature request:

Inconsistent behavior between rdeps and allrdeps. When there are missing BUILD files, rdeps fails to do the query because it notices the missing dependencies, while allrdeps does not complain, just return the reverse dependencies available in the known universe ignoring that there are missing files for generating the transitive closure.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Having three targets with the dependency graph `//:A -> //subdirectory:B -> //:C`, we obtain different behaviors from rdeps and allrdeps even if we specify the same universe.

Doing normal query
```
$ bazelisk query --universe_scope=//...  --order_output=no "allrdeps(//:C)"
//:C
//subdirectory:B
//:A

```
and doing a SkyQuery
```
$ bazelisk query "rdeps(//..., //:C)"
//:A
//subdirectory:B
//:C
```

After renaming/removing the BUILD file in `subdirectory`, that hides `//subdirectory:B`, 
```
$ mv subdirectory/BUILD subdirectory/hidden.BUILD
```
doing normal query
```
$ bazelisk query --universe_scope=//...  --order_output=no "allrdeps(//:C)"
//:C
```
and doing a SkyQuery
```
$ bazelisk query "rdeps(//..., //:C)"
ERROR: /home/sebas/src/bazelbuild/bazel_rdeps_differ_allrdeps/BUILD:3:11: no such target '//subdirectory:B': target 'B' not declared in package 'subdirectory' defined by /home/sebas/src/bazelbuild/bazel_rdeps_differ_allrdeps/subdirectory/BUILD and referenced by '//:A'
ERROR: /home/sebas/src/bazelbuild/bazel_rdeps_differ_allrdeps/BUILD:3:11: no such target '//subdirectory:B': target 'B' not declared in package 'subdirectory' defined by /home/sebas/src/bazelbuild/bazel_rdeps_differ_allrdeps/subdirectory/BUILD and referenced by '//:A'
ERROR: Evaluation of query "rdeps(//..., //:C)" failed: errors were encountered while computing transitive closure
Loading: 0 packages loaded
```
Can be reproduced using [https://github.com/segonpin/bazel_rdeps_differ_allrdeps](https://github.com/segonpin/bazel_rdeps_differ_allrdeps)

### What operating system are you running Bazel on?

Ubuntu 20.04

### What's the output of `bazel info release`?

release 4.2.2

**Comment by brandjon** [comment]
I'd think the normal query result is correct and that the malformed client shouldn't cause an error when querying rdeps of a downward-transitively-correct target. But let's send this to Core team for comment.

**Comment by janakdr** [comment]
I don't think `allrdeps` and `rdeps` are guaranteed to always agree, especially in the face of errors. If you add `-k` what happens? `--universe_scope` implicitly does some things in keep-going mode, regardless of the flag passed on the command line. /cc @haxorz 

(small note: the allrdeps/--universe_scope query is the "SkyQuery", not the rdeps one.)

**Comment by segonpin** [comment]
Adding `-k` it finishes the search and returns a result

```
$ bazelisk query -k "rdeps(//..., //:C)"
ERROR: /home/sebas/src/bazelbuild/bazel_rdeps_differ_allrdeps/BUILD:3:11: no such package 'subdirectory': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /home/sebas/src/bazelbuild/bazel_rdeps_differ_allrdeps/subdirectory and referenced by '//:A'
ERROR: /home/sebas/src/bazelbuild/bazel_rdeps_differ_allrdeps/BUILD:3:11: no such package 'subdirectory': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /home/sebas/src/bazelbuild/bazel_rdeps_differ_allrdeps/subdirectory and referenced by '//:A'
ERROR: Evaluation of query "rdeps(//..., //:C)" failed: errors were encountered while computing transitive closure
WARNING: --keep_going specified, ignoring errors. Results may be inaccurate
//:C
Loading: 0 packages loaded
```

I guess this is enough to explain the different behavior.
