### ISSUE TITLE
Support android_sdk toolchains created in skylark

### ISSUE THREAD

**Issue by mauriciogg** [bazelbuild/bazel#14452]
### Description of the problem / feature request:

I'm trying to declare a custom `android_sdk` toolchain in skylark withouth having to use the `android_sdk_repository` rule y replicating the logic in [AndroidSdkRepositoryFunction.java](https://sourcegraph.com/github.com/bazelbuild/bazel/-/blob/src/main/java/com/google/devtools/build/lib/bazel/rules/android/AndroidSdkRepositoryFunction.java) in Skylark. Essentially we have a repo rule that downloads an SDK from GCS unpacks it and creates the toolchains calling `create_android_sdk_rules` and after that registering the toolchain `register_toolchains("@snap_tool_android_sdk//dist:sdk-30-toolchain")` but building `bazel build $tgt --android_sdk=@snap_tool_android_sdk//dist:sdk-30` yields `failed; build aborted: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type. Is this expected? Is there a way to create an android_sdk toolchain from skylark?

### What operating system are you running Bazel on?

Mac OS

### What's the output of `bazel info release`?

release 4.2.2.0

**Comment by keith** [comment]
Can you post some of your rule code? Are you setting the toolchain type correctly on the rule? https://github.com/bazelbuild/bazel/blob/98dab462a4a5c3a3ccb17fd75d72ad62e8cd98bc/src/main/java/com/google/devtools/build/lib/bazel/rules/android/BazelSdkToolchainRule.java

**Comment by mauriciogg** [comment]
Im using the same code as the native rules. We just call out to create_android_sdk_rules (https://sourcegraph.com/github.com/bazelbuild/bazel/-/blob/tools/android/android_sdk_repository_template.bzl?L163&subtree=true) which creates the toolchain like this

```
       native.toolchain(
            name = "sdk-%d-toolchain" % api_level,
            toolchain_type = "@bazel_tools//tools/android:sdk_toolchain_type",
            exec_compatible_with = HOST_CONSTRAINTS,
            target_compatible_with = [
                "@bazel_tools//platforms:android",
            ],
            toolchain = ":sdk-%d" % api_level,
         )
```

**Comment by gregestren** [comment]
@mauriciogg are you triggering this with the [new platforms API](https://docs.bazel.build/versions/main/platforms-intro.html#android)?

Based on `failed; build aborted: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type.` I'd expect your build's target and execution platforms don't match whatever's registered with `target_compatible_with` and `exec_compatible_with`.  I'm also not sure if, when you set `--android_sdk`, that does the necessary work to declare you're targeting `@bazel_tools//platforms:android"`.

Since `team-Configurability`'s doing a bunch of backend work to make Android work with platforms, I'm happy to help walk through this more.

**Comment by arunkumar9t2** [comment]
We were able to use Starlark declared toolchain in the build when commenting out `target_compatible_with`.

```python
toolchain(
    name = "toolchain",
    exec_compatible_with = [
        "@bazel_tools//platforms:x86_64",
        "@bazel_tools//platforms:linux",
    ],
    # target_compatible_with = [
    #     "@bazel_tools//platforms:android",
    # ],
    toolchain = ":sdk",
    toolchain_type = "@bazel_tools//tools/android:sdk_toolchain_type",
)
```

Here `:sdk` is a `android_sdk` target.

In bazelrc:

```python
build --extra_toolchains=<path>android:toolchain
build --android_sdk=<path>android:sdk
```
