### ISSUE TITLE
Workspace detection does not work on Windows

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#1445]
When the two following conditions hold:
* Bazel is not run from a directory that has a WORKSPACE file in an ancestor directory
* The Bazel binary is copied from its location in the Bazel output tree to another location (I used `/tmp`)

Things don't work:

```
$ /tmp/bazel build wtf
ERROR: invalid target format '(x86) --client_env=ChocolateyInstall=C:\ProgramData\chocolatey --client_env=PATH=/usr/local/bin:/usr/bin:/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:a': invalid package name '(x86) --client_env=ChocolateyInstall=C': package names may contain only A-Z, a-z, 0-9, '/', '-', '.' and '_'.
```

**Comment by ulfjack** [comment]
You said it seemed likely related to --batch.

**Comment by lberki** [comment]
But then I realized that it comes in non-batch mode, but then I realized that if you are not in a workspace, we always do batch mode :)

My best guess is that this is related to the argument escaping we do for `CreateProcess()`.

**Comment by lberki** [comment]
This is the offending part of the command line:

`"--client_env=VSSDK140Install=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VSSDK\" --client_env=PROCESSOR_LEVEL=6 "--client_env=ProgramFiles(x86)=C:\Program Files (x86)" --client_env=ChocolateyInstall=C:\ProgramData\chocolatey`

, in particular, the `ProgramFiles(x86)=C:\Program Files (x86)"` part. I wonder, though how come this is  a problem with `bazel build wtf` and not `bazel --batch build wtf`, even though they both run in batch mode.

**Comment by lberki** [comment]
Oooh, I see -- when `--batch` is explicitly passed, we don't pass `--client_env` on the command line for whatever reason. And that's where the quoting breaks.

**Comment by lberki** [comment]
...and the issue is that `CreateCommandLine` is broken when an environment variable ends with a backslash *and* contains spaces: then quotes are added around it, but the backslash itself is not quoted, thus the argument will end with `\"`, which quotes the final quote that should end the argument.
