### ISSUE TITLE
Feature Request: sh_test "command" argument to avoid having to use srcs for trivial one liners

### ISSUE THREAD

**Issue by vorburger** [bazelbuild/bazel#14465]
If only [`sh_test`](https://docs.bazel.build/versions/main/be/shell.html#sh_test) offered a `command` argument.

This would often avoid having to write an `test.sh` script which contains just a single short command.

BUILD files would be more readable without the indirection through an "artificial" extra script file.

The expected behaviour would exactly like `sh_test` - just save me having to write the tiny `test.sh`.

**Comment by comius** [comment]
Sounds like a useful feature with not too much new maintenance introduced I guess.

The Bazel team is working on Starlarkifying sh rules. Perhaps it would be easier to introduce such feature once the rules are Starlarkified.
