### ISSUE TITLE
It was reported, that the path can be retrieved using `bazel query` and replacing `BUILD` with the script name, so that the whole `py_binary_path` hack can be avoided:

### ISSUE THREAD

**Issue by Schoemiees666** [bazelbuild/bazel#14496]
It was reported, that the path can be retrieved using `bazel query` and replacing `BUILD` with the script name, so that the whole `py_binary_path` hack can be avoided:

```
`bazel query @com_googlesource_gerrit_bazlets//tools/eclipse:project --output location | sed s/BUILD:.*//`project.py 
```

_Originally posted by @davido in https://github.com/bazelbuild/bazel/issues/2452#issuecomment-316895752_

**Comment by DavyCrocket88** [comment]
#2452 (comment)

>

**Comment by Schoemiees666** [comment]
`bazel query @com_googlesource_gerrit_bazlets//tools/eclipse:project --output location | sed s/BUILD:.*//`project.py

**Comment by sgowroji** [comment]
As there is no significant update on this issue for long time, We are closing this issue now. Please feel free to reopen if you are still looking resolution for the above query. Thanks!
