### ISSUE TITLE
Arcanist Integration

### ISSUE THREAD

**Issue by schroederc** [bazelbuild/bazel#145]
It'd be nice to have support for Bazel as a ArcanistUnitTestEngine so that `arc unit` and `arc diff` run all of a workspace's tests before submitting a review to Phabricator.

[Kythe](http://github.com/google/kythe) current has primitive arcanist support for its Bazel-like build system.  It shouldn't be too hard for me to port it specifically for Kythe, but perhaps it would make a good contribution to the Bazel repo for other projects.  Thoughts?

**Comment by ulfjack** [comment]
Not having worked with Phabricator or Arcanist, I don't follow what the
proposal is. Can you point us at relevant documentation? I looked for
ArcanistUnitTestEngine, which doesn't seem to apply, and is not really
documented.

**Comment by hanwen** [comment]
I'm trying to get a bazel-examples repo out there, which would be a good place for contributions like these.

**Comment by schroederc** [comment]
`arc` supports running a set of unit tests based on the files within a particular change (or `--everything`).  It accomplishes this through a plugin system where each unit test system must write a PHP class that will execute the tests and parse the results into an array of ArcanistUnitTestResults.

See [CampfireTestEngine.php](https://github.com/google/kythe/blob/master/buildtools/arc/unit/engine/CampfireTestEngine.php) for Kythe's current support.

**Comment by ulfjack** [comment]
That's cool. Yes, I guess we could hook that up with blaze query. For the
test results, we're planning to output the 'junit' xml format (which is
really ant xml) from the test runners.

**Comment by schroederc** [comment]
Is there any current way to output a structured format of the test results?

**Comment by hanwen** [comment]
we write a .cache_status file which is a protobuf. It's not been intended as a public API, but the analogon inside google is used to collect test/build status results.

**Comment by schroederc** [comment]
I also found that it is hard to query a file's rdeps when a file may or may not be covered by a build target.  Bazel will just fail if it is given some random file.  Is there a way to ignore such files during a query?

**Comment by ulfjack** [comment]
How does it fail?

**Comment by schroederc** [comment]
If you query a file path that is used in a target, it prints the path as a target of the same package:

```
$ bazel query kythe/go/storage/tools/write_entries/write_entries.go
//kythe/go/storage/tools:write_entries/write_entries.go
```

Querying a file that is not declared ends up with this kind of error:

```
bazel query kythe/go/storage/tools/CAMPFIRE
ERROR: no such target '//kythe/go/storage/tools:CAMPFIRE': target 'CAMPFIRE' not declared in package 'kythe/go/storage/tools'; however, a source file of this name exists.  (Perhaps add 'exports_files(["CAMPFIRE"])' to kythe/go/storage/tools/BUILD?) defined by /usr/local/google/home/schroederc/kythe/kythe/go/storage/tools/BUILD.
```

This makes it hard to do this general query:

```
files=($(git ls-files -m))
bazel query "rdeps(//..., set(${files[@]}))"
```

The above query also fails when given `files` contains a path at the root of the WORKSPACE (no dirname).

**Comment by ulfjack** [comment]
Does -k help?

**Comment by schroederc** [comment]
Yeah, `-k` helps the query.  Thanks

**Comment by perezd** [comment]
Any updates on this? I'd love for this to be supported natively.

**Comment by damienmg** [comment]
The Java test runner has landed in 0e396b827bca5ee507aadc875169e47d959a7136 and Philip has a inflight change for making sandboxing allow to output XML file. It should arrive somewhere next week. For now you can have the xml outputs by disabling sandboxing.

For the rest of the piping to Arcanist, we would welcome any contribution :)

**Comment by perezd** [comment]
OK, I can give it a shot. Any docs on how to utilize it?

**Comment by damienmg** [comment]
I don't really know what kind of doc you are expecting but if you run bazel
with `--spawn_strategy=standalone --nolegacy_bazel_java_test` you should
get XML output for every java test available in `bazel-testlogs`.

**Comment by perezd** [comment]
Oh, this hasn't hit a release version yet has it?

**Comment by damienmg** [comment]
No it should be in 0.2 (somewhere at the end of the month).

**Comment by damienmg** [comment]
(and even then it should still requires the --nolegacy_bazel_java_test flag)

**Comment by perezd** [comment]
Cool, please ping this thread when its in a release and I'll make it happen.

**Comment by kchodorow** [comment]
It is now in a release.

**Comment by damienmg** [comment]
I am closing this one as we now have XML output for every test and query. There is no more feature that should be needed on bazel side.

**Comment by igorgatis** [comment]
I managed to make a more lightweight version of Kythe's bazel-arcanist integration. It uses --build_event_json_file and it is (IMHO) more developer friendly because it shows progress using bazel's output: https://github.com/igorgatis/bazel-arcanist
