### ISSUE TITLE
Documentation issue: Label - What happens when label sections are blank?

### ISSUE THREAD

**Issue by psigen** [bazelbuild/bazel#14503]
Documentation URL: https://docs.bazel.build/versions/main/skylark/lib/Label.html

Would it be possible to add documentation around what happens with this API when portions of a label are empty?

Here are some examples I was having trouble with:
- if no package is specified, i.e. `//:abc`, does `package` return `"."` or `""` or `None`?
- if the name is not specified, i.e. `//pkg`, does it automatically set `name` to `"pkg"`?
- if the workspace is not specified, i.e. `//pkg:abc`, does `workspace_name` automatically resolve to `""`  or `"__main__"` or dynamically resolve to the workspace name specified in `WORKSPACE`?
- if the workspace is not specified, i.e. `//pkg:abc`, does `workspace_root` get set to `"."` or `None` or some other value?

**Comment by Wyverald** [comment]
A number of documentation improvements in this area have been made to address some of the concerns raised here. Other questions like `if the name is not specified, i.e. //pkg, does it automatically set name to "pkg"?` can be answered by simply reading the docs (in this case, `//pkg` behaves exactly the same as `//pkg:pkg`). So I'll go ahead and close this.
