### ISSUE TITLE
Make sure java_binary can run in runfiles-less mode

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#1451]
On Windows, we do not have runfiles tree per se.
Blocks #1212.

**Comment by dslomov** [comment]
This is fixed, but only works under msys, right @meteorcloudy

**Comment by meteorcloudy** [comment]
That is correct, we stilll need to figure out a way to run java binary out of msys, but it definitely can run in runfiles-less mode now.

**Comment by dslomov** [comment]
To be clear, ``bazel run ...`` will work fine either way. The "binary" itself is a shell script though.
