### ISSUE TITLE
remote_cache upload very slow for long list of outs

### ISSUE THREAD

**Issue by jablin** [bazelbuild/bazel#14513]
### Description of the problem / feature request:

I've got a genrule that creates ~11,000 files (total 21MB). When using a remote cache with `--remote_upload_local_results`, the upload takes 50 seconds to two minutes.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I'll try. Later.

### What operating system are you running Bazel on?

Linux 3.10.0 on RHEL 7.9 

### What's the output of `bazel info release`?

release 4.2.2

###  Have you found anything relevant by searching the web?

No.

**Comment by brentleyjones** [comment]
Which remote cache are you using? This could be an issue with the service instead of Bazel.

cc: @coeuvre

**Comment by jablin** [comment]
@brentleyjones , I don't know (yet!) which software the remote cache uses. However, when I re-tried with a bare nginx&webdav, the performance issues disappeared: the upload took less than 5s.

**Comment by brentleyjones** [comment]
Is the remote cache on the same machine, same network, or actually remote (far away)? gRPC caches are sensitive to latency, so the deployment, and the software itself, can play a huge part in the performance of the cache.

If you can provide a gRPC log (https://docs.bazel.build/versions/main/command-line-reference.html#flag--experimental_remote_grpc_log) along with a Timing Profile (https://docs.bazel.build/versions/main/command-line-reference.html#flag--profile) for a slow build, it can help us know what is slow.

**Comment by brentleyjones** [comment]
Sounds like an issue for https://github.com/buchgr/bazel-remote then 😄. I'm just glad it's not an inherit Bazel bug.

**Comment by jablin** [comment]
Yes, sounds like a problem with the caching server. And me too, I'm glad it's probably not a Bazel bug.

However, one more question:

I've executed this command:

    bazelisk build --experimental_remote_grpc_log=/tmp/remote-rpc.log --profile=/tmp/profile.json.gz //vobs/zenith/workspace:slang-build

I've got a Timing Profile now. However, I did _not_ get the gRPClog. `/tmp/remote-rpc.log` just does not exist. Why?

**Comment by jablin** [comment]
[profile.json.gz](https://github.com/bazelbuild/bazel/files/7815798/profile.json.gz)

**Comment by brentleyjones** [comment]
Are you using bazel-remote in HTTP or gRPC mode? If HTTP mode, that log won't get produced, as there wasn't any gRPC requests made.

**Comment by coeuvre** [comment]
Closing as it seems to be a cache server issue.
