### ISSUE TITLE
`print` in a module appears to be different from `print` in a workspace rule

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#14526]
### Description of the problem / feature request:

`print` appears to behave differently between workspace rules and when used in a module.

When called from a workspace, the output of `print` is prefixed by a `DEBUG` statement, and then the path to the file, whereas this is missing when the same function is called from a module.

### What's the output of `bazel info release`?

5.0.0rc3

### Any other information, logs, or outputs that you want to share?

The way that `print` works when called from a workspace is nicer: it makes the output easy to identify and it's easy to grep for.

**Comment by oquenchil** [comment]
@meteorcloudy

**Comment by Wyverald** [comment]
Yeah there's a bunch of quality-of-life changes we should make around the Starlark-running part of bzlmod before official launch.

**Comment by fmeum** [comment]
This goes even further: If a module extension specifies incorrect attributes for a repository rule, an error is printed but the build doesn't fail.
