### ISSUE TITLE
bazel-5.0.0 removed the flag --noincompatible_blacklisted_protos_requires_proto_info

### ISSUE THREAD

**Issue by finecci** [bazelbuild/bazel#14524]
### Description of the problem / feature request:

ERROR: --noincompatible_blacklisted_protos_requires_proto_info :: Unrecognized option: --noincompatible_blacklisted_protos_requires_proto_info

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

bazel build --noincompatible_blacklisted_protos_requires_proto_info

### What operating system are you running Bazel on?

Ubuntu 18.04.3 LTS

### What's the output of `bazel info release`?

bazel-5.0.0rc3 and bazel-5.0.0-pre.20211011.2

###  Have you found anything relevant by searching the web?

the same question here
https://github.com/bazelbuild/bazel/issues/13572#issuecomment-859586718

while the flag is supported in bazel-4.x, will it be added into 5.x later?

**Comment by Wyverald** [comment]
It was intentionally removed in https://github.com/bazelbuild/bazel/pull/12431. Being a major release, 5.x will contain backwards incompatible changes, so you should look into migrating off that flag.

**Comment by weimch** [comment]
@Wyverald I have the same issue when I upgrade bazel to 5.x. It really bothers us because many projects relay on an older version of protobuf. They need this flag to be used on higher version of bazel. Why not add this flag back for backward compatibility?

**Comment by Wyverald** [comment]
> Why not add this flag back for backward compatibility?

The simple answer is that it adds technical debt. We'd have to maintain the extra knobs forever if nobody migrates.

Anyhow, this isn't the place to debate policy; see the [docs on backwards compatibility](https://docs.bazel.build/versions/main/backward-compatibility.html) for our general stance on this topic.
