### ISSUE TITLE
Add option to `bazel sync` to get `sha256` and `urls` in a format like `json`

### ISSUE THREAD

**Issue by kriswuollett** [bazelbuild/bazel#14538]
### Description of the problem / feature request:

Add an option to `bazel sync` to output the resolved repository `sha256` and `urls` to a more consumable format like `json`.

### Feature requests: what underlying problem are you trying to solve with this feature?

Currently using `bazel sync --experimental_repository_resolved_file`. Would be great to avoid having a checked in `repository.bzl` file in a repo which isn't directly consumable by non-Bazel tools which also:

* fails `buildifier` linter: bazelbuild/bazel#14537
* doesn't use `buildifier` format: bazelbuild/bazel#14454
* requires the use of some `sed`, and optionally `hjson` (bazelbuild/rules_python#602) processing on it in order to write scripts to populate [distribution file directories](https://docs.bazel.build/versions/main/guide.html#distribution-files-directories)

Having something directly consumable with a tool like `jq` would be great. I currently have something working okay, but if those `--experimental_repository_resolved_file` formatting issues mentioned above gets fixed, then text processing to get the file into format like `json` for further processing will get slightly more complicated (docstring, trailing commas).

### What operating system are you running Bazel on?

Linux, macOS

### What's the output of `bazel info release`?

```
INFO: Invocation ID: b759df50-bd68-41a1-9aa7-39cc71905a2a
release 4.2.1
```

**Comment by kriswuollett** [comment]
I think it would be reasonable to alternatively add an additional option to specify the format of `json` for the `--experimental_repository_resolved_file`, or auto-detect it from the specified file's extension.

**Comment by Anrock** [comment]
I'm still interested in that. No idea how to reach the triage team since provided @bazelbuild/triage doesn't seem like a proper username or whatever it was meant to be.

**Comment by fmeum** [comment]
`bazel sync` will go away as it doesn't support repos defined via `MODULE.bazel`. `bazel mod show_repo` and `bazel mod show_extension` have json output and give you access to all attributes of repo rules.
