### ISSUE TITLE
`json` module has no `decode` member in bzlmod module implementation

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#14541]
### Description of the problem / feature request:

It is impossible to parse json in a bzlmod module implementation since the [json](https://docs.bazel.build/versions/main/skylark/lib/json.html) module doesn't contain a `decode` method

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```starlark
def _my_module_impl(mctx):
    print("Attributes: %s" % dir(json))

my_module = module_extension(
    _my_module_impl,
)
```

The output I see from Bazel 5rc3 is:

`Attributes: ["to_json", "to_proto", "write_artifact_spec", "write_exclusion_spec", "write_override_license_types_spec", "write_repository_credentials_spec", "write_repository_spec"]`

###  Have you found anything relevant by searching the web?

No

**Comment by fmeum** [comment]
The entries in the output seem to coincide with the attributes of [this struct named `json`](https://github.com/bazelbuild/rules_jvm_external/blob/d4706966087ddcb2a8e067d50e003ad00e1c7b04/specs.bzl#L239) in rules_jvm_external. Perhaps that definitions shadows the Bazel-defined `json` global here?

**Comment by oquenchil** [comment]
@meteorcloudy

**Comment by Wyverald** [comment]
The output I see with 5.0.0rc3 is:

```
/Users/wyv/test/bzlmod-json/extensions.bzl:2:10: Attributes: ["decode", "encode", "encode_indent", "indent"]
```

@fmeum is likely right here.

**Comment by shs96c** [comment]
You're right. The module was being shadowed, and I'd not noticed the `load` statement at the top. Fixing that, fixes the problem. My apologies.
