### ISSUE TITLE
Meet 'ERROR: Unable to write all BEP events to file' while bazel build large multiple repos and output build event to json file

### ISSUE THREAD

**Issue by summylight** [bazelbuild/bazel#14544]
### Description of the problem / feature request:

When I bazel build large multiple repos (about 27000 targets and triggered 31020 total actions) and want to analyze bep json file generated by `bazel build --build_event_json_file=test.json` to get failed/timeout unit test, I met this error:
```
ERROR: Unable to write all BEP events to file due to 'java.io.IOException: io.grpc.StatusRuntimeException: OUT_OF_RANGE: size 96944768 exceeds 67108864'
```
I think this happened due to a large UnstructuredCommandLine or BuildStarted event, the size of this event is too large for google protocol buffer (limitation size : 64MB->67108864) to be serialized into event protocol stream.

I tried some flags provided by bazel like `--bes_outerr_chunk_size`/` --build_event_max_named_set_of_file_entries=2`/ 
`--build_event_binary_file=test.json`, and these didn't work.
Any help would be appreciated, thanks!
### Feature requests: what underlying problem are you trying to solve with this feature?

Adding a flag to bazel to omit too large event may be helpful.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Bazel build large multiple repos.
my bazel command: 
```
bazel build XXtarget -c fastbuild --remote_upload_local_results=false 
   --build_event_json_file=/tmp/bep_github_remote.json 
   --remote_cache=--remote_cache=bazel-192.168.1.10:30443 --config=remote
```
Remote config:
```
build:remote --remote_local_fallback
build:remote --remote_max_connections=100
build:remote --remote_retries=2
build:remote --remote_upload_local_results=false
```
### What operating system are you running Bazel on?

ubuntu 18.04

### What's the output of `bazel info release`?

release 4.0.0

###  Have you found anything relevant by searching the web?

I found no same issue on web. Have tried many flags and failed.

**Comment by meisterT** [comment]
cc @michaeledgar

**Comment by summylight** [comment]
I tested building some targets without `--remote-cache` and `--config=remote` flags then passed. But the build process failed after adding these flags. So I doubt `Stuctured Commandline` and other configure events are too large for google protobuf serializing after adding these flags.

**Comment by summylight** [comment]
In my tests, I found that bazel tried to serialize the target I built using google protobuf, but the process failed because the target (96944768) was too large. But after removing `--build_event_json_file=/tmp/bep.json`, it worked. So I wonder why bep is trying to serialize the built target?

**Comment by summylight** [comment]
Do we have any updates in subsequent versions?

**Comment by summylight** [comment]
cc @michaeledgar

**Comment by summylight** [comment]
Done with adding `--experimental_build_event_upload_strategy=local`

**Comment by coeuvre** [comment]
> So I wonder why bep is trying to serialize the built target with -remote_upload_local_results=false?

If you use Bazel 5.0.0+ that should be working as expected.
