### ISSUE TITLE
Auto-detect and configure hard-coded paths on Windows 

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#1454]
1. Location of Visual Studio for MSVC compatibility scripts
1. Location of python
1. Location of msys bintools and msys-2.0.dll

Needed for #1453.

**Comment by dslomov** [comment]
@meteorcloudy what is left here?

**Comment by meteorcloudy** [comment]
Detecting msys-2.0.dll?  But do we need to do this in cc_configure.bzl?

**Comment by dslomov** [comment]
We can't really help with msys-2.0.dll, since we need it to run bazel.exe itself.
