### ISSUE TITLE
genrule: It seems that some folders are missing in the sandbox when I use genrule 

### ISSUE THREAD

**Issue by qchenzi** [bazelbuild/bazel#14545]
### It seems that some folders are missing:

> As shown below, the comm, pal2 and tdr are missing in the sandbox when I use the cmd 'ls' to list all files(folders) in 'lib_src' dirs. 

<img width="1592" alt="企业微信截图_649991e6-1827-4653-8047-2a8decff83ab" src="https://user-images.githubusercontent.com/21999330/148880786-facb6406-43ad-4abc-80c3-a8d7a8eaf04d.png">

**Comment by fmeum** [comment]
Do the missing directories contain `BUILD` files? Since `glob` doesn't reach into such directories, that may explain their absence from the sandbox.

**Comment by qchenzi** [comment]
> Do the missing directories contain `BUILD` files? Since `glob` doesn't reach into such directories, that may explain their absence from the sandbox.

Absolutely, the missing directories was contained  in `BUILD` files.  Besides, I try to use the attribute 'local = 1' in genrule to disable sandbox, it works.

**Comment by fmeum** [comment]
You could declare a [`filegroup`](https://docs.bazel.build/versions/main/be/general.html#filegroup) in e.g. `comm` to wrap its sources in a single target that you could then reference in this genrule in addition to the glob. In that way, you would still have access to all sources without disabling the sandbox.

**Comment by qchenzi** [comment]
> 

Thank you so much, I will try it.
