### ISSUE TITLE
Bazel error: ERROR: error loading package '': in android/aosp/tensorflow/tensorflow/workspace3.bzl: Label '//third_party:tf_runtime/workspace.bzl' is invalid because 'third_party' is not a package; perhaps you meant to put the colon here: '//:third_party/tf_runtime/workspace.bzl'?

### ISSUE THREAD

**Issue by git-gmali** [bazelbuild/bazel#14546]
### Description of the problem / feature request:
Facing error while building Tensorflow lite 2.7.0 C++ libraries for Android using Bazel.
ERROR: error loading package '': in /source/platform_r_gl/android/aosp/tensorflow/tensorflow/workspace3.bzl: Label '//third_party:tf_runtime/workspace.bzl' is invalid because 'third_party' is not a package; perhaps you meant to put the colon here: '//:third_party/tf_runtime/workspace.bzl'?

### Feature requests: what underlying problem are you trying to solve with this feature?
Trying to build the TensorFlow Lite C++ Libraries to work with Android.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Not sure.

### What operating system are you running Bazel on?
Windows 10.

### What's the output of `bazel info release`?
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [no_tfrt]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=237
INFO: Reading rc options for 'info' from \source\platform_r_gl\android\aosp\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  Inherited 'build' options: --python_path=C:/Users/gmali/Anaconda3_/python.exe
INFO: Reading rc options for 'info' from \source\platform_r_gl\android\aosp\tensorflow\.bazelrc:
  Inherited 'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'info' from \source\platform_r_gl\android\aosp\tensorflow\.tf_configure.bazelrc:
  Inherited 'build' options: --action_env PYTHON_BIN_PATH=C:/Users/gmali/Anaconda3_/python.exe --action_env PYTHON_LIB_PATH=C:/Users/gmali/Anaconda3_/lib/site-packages --python_path=C:/Users/gmali/Anaconda3_/python.exe --config=rocm --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions --action_env ANDROID_NDK_HOME=android-ndk-r21b-linux-x86_64android-ndk-r21b --action_env ANDROID_NDK_API_LEVEL=21 --action_env ANDROID_BUILD_TOOLS_VERSION=aarch64-linux-android-4.9 --action_env ANDROID_SDK_API_LEVEL=29 --action_env ANDROID_SDK_HOME=android-ndk-r21b-linux-x86_64android-ndk-r21b
INFO: Found applicable config definition build:short_logs in file \source\platform_r_gl\android\aosp\tensorflow\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file \source\platform_r_gl\android\aosp\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:rocm in file \source\platform_r_gl\android\aosp\tensorflow\.bazelrc: --crosstool_top=@local_config_rocm//crosstool:toolchain --define=using_rocm_hipcc=true --repo_env TF_NEED_ROCM=1 --config=no_tfrt
INFO: Found applicable config definition build:no_tfrt in file \android\aosp\tensorflow\.bazelrc: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/fallback,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:windows in file \source\platform_r_gl\android\aosp\tensorflow\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --distinct_host_configuration=false --config=no_tfrt
INFO: Found applicable config definition build:monolithic in file \android\aosp\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Found applicable config definition build:no_tfrt in file android\aosp\tensorflow\.bazelrc: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/fallback,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
release 4.2.2

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
https://android.googlesource.com/platform/external/tensorflow
800bcb8ad463b44730ae604802b2c353d8cb32e8
800bcb8ad463b44730ae604802b2c353d8cb32e8

###  Have you found anything relevant by searching the web?
No nothing on the web relevant to the error that I am facing.

**Comment by oquenchil** [comment]
Please file a bug on the Tensorflow repo.
