### ISSUE TITLE
Unclear whether it's possible to exclude the bazel-central-registry when using `bzlmod`

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#14553]
### Description of the problem / feature request:

As a corporate user, I don't want my developers accessing repos that are not hosted on our internal servers. From usage, it seems that the `bazel-central-registry` is added automatically, which means that it's not possible. It would be helpful to be able to remove the BCR from the list of registries, and if it's present ensure that it is the last registry that is checked.

### Feature requests: what underlying problem are you trying to solve with this feature?

I want to have complete control over where dependencies are downloaded from since build machines may not have public Internet access.

### What's the output of `bazel info release`?

`release 5.0.0rc3`

**Comment by Wyverald** [comment]
> From usage, it seems that the bazel-central-registry is added automatically

Is it? That would be a bug. The intended behavior is that when no `--registry=X` is set, the BCR is used by default; if any `--registry=X` is set, we don't append BCR. Could you double-check?

**Comment by meteorcloudy** [comment]
I'm pretty sure `--registry` will override the default registry (BCR)
