### ISSUE TITLE
Bazel deleting cache for multiple terminals

### ISSUE THREAD

**Issue by sualehasif** [bazelbuild/bazel#14567]
### Description of the problem / feature request:

Our current codebase is run on [gitpod](gitpod.io) and uses Bazel for building all the c++ code. Unfortunately, recently when building the c++ codebase, changing the terminal is causing everything to rebuild in the sandbox. 

We use grpc and starting the daemon and the server in two different terminals causes rebuilds everytime. We really like the sandboxing but we have not been able to turn it off for our work. (We tried `build --spawn_strategy=local` but that causes grpc to not build :(

Is there a way to prevent complete rebuilds everytime?

### What operating system are you running Bazel on?

```
gitpod /workspace/anysphere $ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
```

### What's the output of `bazel info release`?

```
release 4.2.1-homebrew
```

**Comment by meisterT** [comment]
Do you have a repro case for us?
Also can you please check whether there are any environmental variable differences between the two terminals?

**Comment by meisterT** [comment]
closing for a lack of response - I am happy to reopen if you have a way to repro
