### ISSUE TITLE
Add a built-in `http` module extension

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#14570]
### Description of the problem / feature request:

Quite often rulesets depend on resources that are downloaded using `http_file`. As an example, `rules_jvm_external` depends on downloading both `coursier` and `jq` as tools that it uses. In a `WORKSPACE` file, this is easy: a call to `http_file` and the job is done. `bazel_dep` doesn't allow this behaviour, which means that it's impossible to use these kinds of dependencies when using a purely modularised build.

Further, some of these dependencies are only used using development, so the equivalent of `bazel_dep`'s `dev_dependency` flag is needed to prevent unnecessary downloads for users.

### Feature requests: what underlying problem are you trying to solve with this feature?

I'd like to be able to download useful tools and artifacts and expose them in a purely modularised build.

### What's the output of `bazel info release`?

release 5.0.0rc3

**Comment by Wyverald** [comment]
What's wrong with using an extension?

**Comment by Wyverald** [comment]
I think it's probably cleaner to go with @fmeum's example -- this way, you don't have to copy http_file's attributes into a tag class. You don't need to write what you want to download in the MODULE.bazel file anyway -- just write them in the extension impl function.

**Comment by fmeum** [comment]
@Wyverald Now that I've thought more about it, I think that this issue should be reopened. While the "put repository rules in a static module extension" approach works well for rulesets, it may be difficult to sell to Bazel end users. If `MODULE.bazel` is assumed to fully replace `WORKSPACE` some day, I think it would need to offer simple to use analogues for end users to download their custom external repos and files (e.g., via a `http.file` tag).

**Comment by Wyverald** [comment]
Ah, true -- we were thinking about introducing an `http.archive` tag too.

**Comment by Wyverald** [comment]
Update: @SalmaSamy sent a draft PR (#16000). The repo name conflict issue makes it not worth it to create this built-in module extension (see https://github.com/bazelbuild/bazel/pull/16000#discussion_r957276786) IMO.

**Comment by Wyverald** [comment]
Chatted with @shs96c ; we decided that writing a separate module extension every time works well enough that this shouldn't be needed.

**Comment by meteorcloudy** [comment]
https://github.com/bazelbuild/bazel/issues/17141 is a duplicated issue.
