### ISSUE TITLE
Bazel not compatible with Hazelcast 3.6

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#1457]
The Hazelcast 3.5 client isn't compatible with the Hazelcast 3.6 server.

https://github.com/hazelcast/hazelcast/issues/8457

Apparently Hazelcast 3.5 includes a prototype build of a "new" client protocol which is finalized in Hazelcast 3.6.

Bazel is using Hazelcast 3.5.4, and should upgrade to the new thing.

**Comment by dfabulich** [comment]
This is not the first time Hazelcast has broken backwards compatibility in minor version updates. Here's a thread about a breakage in 3.2.

As far as I'm aware, the Hazelcast team has made no commitment to ensuring backwards compatibility in minor updates in the future, so upgrading to the `java-client-new` Hazelcast 3.6 client does not guarantee that the client will work in Hazelcast 3.7.

**Comment by hhclam** [comment]
dfabulich: you're right. The direction is that we'll move the bazel <-> distributed cache server protocol to be based on gRPC and not based on the native protocol of the key value store used.

**Comment by noctarius** [comment]
This is what it was in the past. The new client protocol was created to ensure exactly that. The plan was that starting with the dev preview in 3.5 this is true, however we found some flaw in the protocol that had to be fixed and broke backwards compatibility. Starting with 3.6 the protocol can evolve in both directions forwards and backwards.

I wasn't aware of this project to use Hazelcast but since I am now, we're happy to help if necessary :)

**Comment by ihsandemir** [comment]
@dfabulich  We also released our Open Binary Client Protocol as of version 3.6 here: http://hazelcast.org/documentation/

The protocol is guaranteed to be backward compatible for minor versions starting at 3.6, hence you should be OK with 3.6 and forward. The new client in 3.5 was as @noctarius mentioned was a dev-preview version, and it was finalized at 3.6.

**Comment by dfabulich** [comment]
@noctarius @ihsandemir if you can weigh in on https://groups.google.com/forum/#!msg/hazelcast/KPdH-4cVzyw/KEyJnqQqBQAJ and/or https://groups.google.com/forum/#!topic/bazel-discuss/sWjUalkGIwg that would be a huge help.

**Comment by noctarius** [comment]
I asked engineering to look into it, unfortunately there is a lot going for 3.7 release at the moment but it will cool down over the next days. We're looking into this, I'll keep you posted!

**Comment by dfabulich** [comment]
Enes Akar replied to my post on the Hazelcast list, asking if we could reproduce this issue with Hazelcast 3.6. https://groups.google.com/forum/#!msg/hazelcast/KPdH-4cVzyw/KEyJnqQqBQAJ

That would, of course, require upgrading to Hazelcast 3.6. I'll start on that tomorrow (unless someone else can get to it before me).

**Comment by noctarius** [comment]
If you have any question ping me on twitter or here. I'm on-site a customer but I'll try to keep an eye on messages from you :)

**Comment by dfabulich** [comment]
My PR merged; this is now fixed.
