### ISSUE TITLE
`--bes_timeout` is ignored in Bazel 5

### ISSUE THREAD

**Issue by BalestraPatrick** [bazelbuild/bazel#14576]
### Description of the problem / feature request:

`--bes_timeout` doesn't seem to be respected anymore in Bazel 5.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
This will complete successfully and upload the full BES even though it shouldn't because the timeout is set to a very low 1ms:
```
$ git clone git@github.com:bazelbuild/rules_apple.git
$ cd rules_apple
$ env USE_BAZEL_VERSION=5.0.0rc4 bazelisk build --remote_cache=grpcs://remote.buildbuddy.io --bes_backend=grpcs://remote.buildbuddy.io --bes_results_url=https://app.buildbuddy.io/invocation/ //examples/iOS/StickersApp --bes_timeout=1ms --cpu=ios_x86_64
```

While this will fail as expected in Bazel 4.2.1:
```
$ env USE_BAZEL_VERSION=4.2.1 bazelisk build --remote_cache=grpcs://remote.buildbuddy.io --bes_backend=grpcs://remote.buildbuddy.io --bes_results_url=https://app.buildbuddy.io/invocation/ //examples/iOS/StickersApp --bes_timeout=1ms --cpu=ios_x86_64
ERROR: The Build Event Protocol upload timed out. com.google.common.util.concurrent.TimeoutFuture$TimeoutFutureException: Timed out: com.google.common.util.concurrent.Futures$NonCancellationPropagatingFuture@43553e48[status=PENDING, info=[delegate=[com.google.common.util.concurrent.SettableFuture@4d92c852[status=PENDING]]]]
```

### What operating system are you running Bazel on?

> Replace this line with your answer.

macOS 12.1

**Comment by brentleyjones** [comment]
cc @coeuvre

**Comment by coeuvre** [comment]
After 4.2, we introduced async upload for remote module and we added code to block waiting unfinished futures at the end of build command. However, this piece of code is executed before relevant code in BES module where the flag `--bes_timeout` is used at.

I have some quick-and-dirty fixes which I am not satisfied with. I have a long-term fix but it maybe too risky to put into 5.0rc4. WDYT if we fix this in 5.1?

**Comment by brentleyjones** [comment]
Since 5.0 was just released, whatever the next release is, 5.0.1 or 5.1 sounds good.

**Comment by BalestraPatrick** [comment]
This is not a blocker for us to adopt Bazel 5.0, so we're fine with a fix in a future version.

**Comment by brentleyjones** [comment]
@Wyverald its not fixed yet, but once it is, I think this would be good for a 5.0.1.

**Comment by Wyverald** [comment]
@bazel-io fork 5.1
