### ISSUE TITLE
Sandboxing replaces some empty files with char device 1, 3 (/dev/null).

### ISSUE THREAD

**Issue by ioctl0** [bazelbuild/bazel#1458]
When setting up the sandbox, bazel mounts /dev/null in place of at least some empty files, producing character device nodes instead of regular files. This can cause subtle problems in code that explicitly checks the S_IFREG bit.

In particular, this causes mysterious failures when loading python3 namespace modules due to importlib performing isfile() checks on `__init__.py` files.

**Comment by philwo** [comment]
This is "fixed" in the new sandbox implementation, however the new sandbox uses symlinks for all input files, which generally work fine, but may cause other issues.

If this is still a problem for you, please let me know and re-open this bug.

**Comment by duggelz** [comment]
This still seems to be a problem in Bazel 0.3.2.  See associated bugs I filed against Python below.

http://bugs.python.org/issue28424
http://bugs.python.org/issue28425

**Comment by duggelz** [comment]
To expand on this, if __init__.py is a symlink to a regular file, it's fine, but if it's a symlink to /dev/null, it doesn't work correctly.  So the fix would be to create a regular empty file and link to that.  I guess there must be some reason we don't make all the __init__.py files regular empty files.

**Comment by duggelz** [comment]
The relevant code seems to be this:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/sandbox/SpawnHelpers.java#L167

I can generate a minimal testcase but I don't see that Bazel currently has any Python tests in the repo, so I'm not sure where to put it.  Basically

```
=== BUILD ===
py_binary(name="a",srcs=["a.py","mypackage/b.py"])
```
```
=== a.py ===
import mypackage.b
assert hasattr(mypackage, "__file__")
```
```
=== b.py doesn't matter ===
```

**Comment by duggelz** [comment]
```
$ git clone -b dgreiman/bazel-issue-1458 https://github.com/google/subpar.git

$ /opt/bin/bazel version
..........
Build label: 0.3.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Oct 7 17:25:10 2016 (1475861110)
Build timestamp: 1475861110
Build timestamp as int: 1475861110

$ /opt/bin/bazel test //...
//:a_PY2                                                                 PASSED in 0.1s
//:a_PY3                                                                 FAILED in 0.1s
```

**Comment by ulfjack** [comment]
Does this also affect 0.4?

**Comment by duggelz** [comment]
Yes.  Just tested in Bazel 0.4.2, and the sandbox still creates symlinks to /dev/null

The Python folks have decided not to fix this in Python, for compatibility reasons: /dev/null is not a regular file, so there would have to be some tricky special casing, and some portability concerns for all the various OS's that handle this slightly differently, all to support a fairly unusual use case.

The Python docs are going to be clarified that `__init__.py` must be a regular file, i.e. symlinking to /dev/null is not supported.

```
$ /opt/bin/bazel test --test_output=streamed //...
WARNING: Streamed test output requested so all tests will be run locally, without sharding, one at a time.
INFO: Found 2 test targets...
total 12
lrwxrwxrwx 1 nobody nogroup   9 Dec  8 18:35 __init__.py -> /dev/null
```

**Comment by duggelz** [comment]
I also tested normal module (i.e. not __init__) source files, and Python 3 doesn't handle those either.  So you shouldn't link anything that supposed to be a Python source file to /dev/null, you should just create a regular 0 length file.

**Comment by philwo** [comment]
Totally agree. Symlinking to /dev/null is the wrong thing to do here, creating an empty file instead is the right thing.

The culprit is here: https://github.com/bazelbuild/bazel/blob/fa3f55a8785c28253b2f836ddc84e994e48edd7f/src/main/java/com/google/devtools/build/lib/sandbox/SpawnHelpers.java#L142

I'll definitely fix this, but not sure if I can get it done before my vacation in January, as I only have ~3 working days left before the holidays start here.

**Comment by philwo** [comment]
A fix for this is now (finally) in code review. Sorry that it took so long.
