### ISSUE TITLE
Tag requires-fakeroot does not work in docker

### ISSUE THREAD

**Issue by nstng** [bazelbuild/bazel#14594]
### Description of the problem / feature request:

We are working on a make to bazel migration in a monorepo. Most development happens in a remote docker container in vscode (the repo is mounted from the host).

A test executed with tag  "requires-fakeroot" does not change the runtime user.

### Feature requests: what underlying problem are you trying to solve with this feature?

Running test that need the root user during runtime.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
../tests/Build.bazel
[..]
sh_test(
    name = "echo_uid",
    srcs = ["echo_uid.sh"],
    tags = ["requires-fakeroot"]
)
```

```
../tests/echo_uid.sh
#!/bin/sh

id
```

```
bazel test --test_output=all //.../tests:echo_uid
```
output in docker
* docker without tag "requires-fakeroot" -> uid=1000
* docker with tag "requires-fakeroot" -> uid=1000

expected output (here via native system)
* native without tag "requires-fakeroot" -> uid=1000
* native with tag "requires-fakeroot" -> uid=0

### What operating system are you running Bazel on?

1. docker with ubuntu:focal
2. native Ubuntu 20.04.2

### What's the output of `bazel info release`?

1. docker: release 4.2.2
2. native: release 4.2.2

###  Have you found anything relevant by searching the web?

no

### Any other information, logs, or outputs that you want to share?

no

**Comment by aiuto** [comment]
It might help if you provided more information about your setup and configuration.

**Comment by meisterT** [comment]
cc @larsrc-google
