### ISSUE TITLE
bazel-5.0.0-dist.zip badly packaged

### ISSUE THREAD

**Issue by sionescu** [bazelbuild/bazel#14607]
A release archive should contain exactly one toplevel directory named, for example "bazel-5.0.0".
bazel-5.0.0-dist.zip instead is a zip bomb which spewed a bunch of source files in my PWD.
Furthermore, the top-level files are all executable, including the .md files, which makes no sense.

**Comment by Wyverald** [comment]
It looks like this is how all our dist archives have been packaged. I'm not aware of a standard way to pack release archives (happy to be corrected), so unless we have a citation, I'm leaning to close this as WAI. @fweikert @aiuto do you have anything to add?

**Comment by aiuto** [comment]
The world is uneven on this. Some projects add an intermediate, others don't.
IMO, we should reevaluate producing the dist.zip archive at all. I'm not convinced it adds enough value over the raw source archive.

**Comment by divanorama** [comment]
dist.zip includes more files than just source code though, namely bootstrap files under derived/ and few other files like coverage.WORKSPACE or jdk.WORKSPACE
