### ISSUE TITLE
Bazel sandboxed python multiprocessing file not found error

### ISSUE THREAD

**Issue by ronxperiel** [bazelbuild/bazel#1460]
When trying to bazel build a python script that uses mutex locks on /dev/shm, it fails if the number of cores is greater than 1 (we desire greater than 1). To fix this we need to specify a bazel flag  '--spawn_strategy=standalone' , which we do not desire. 

we give this command to the ctx.action
cmd += "echo \"import _multiprocessing as ms \nfh = ms.SemLock(1,1,1) \nfh.label\" > p.py;"
cmd += "python p.py;"

Error (only if #cores > 1):
pool = multiprocessing.Pool(processes=cores)
  File "/usr/lib/python2.7/multiprocessing/**init**.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 138, in **init**
    self._setup_queues()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 234, in _setup_queues
    self._inqueue = SimpleQueue()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 352, in __init__
    self._rlock = Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.**init**(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in **init**
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 2] No such file or directory

**Comment by bsilver8192** [comment]
What distribution (I'm assuming Linux) is this? Where is the `_multiprocessing.x86_64-linux-gnu.so` (or similar, basically `_multiprocessing.*.so`) file on your system? On my Debian Jessie system, `dpkg -S _multiprocessing.*.so` gets me `/usr/lib/python2.7/lib-dynload/_multiprocessing.x86_64-linux-gnu.so`. If you find where that is on your system and pass the containing directory to [--sandbox_add_path](http://www.bazel.io/docs/command-line-reference.html#flag--sandbox_add_path), it might work. Depending where that is, it might make sense to have Bazel add the path itself too.

**Comment by philwo** [comment]
/dev/shm is not available in the current sandbox - could you try to --sandbox_add_path=/dev/shm and see if that makes it work? We should probably mount a fresh tmpfs there instead.
