### ISSUE TITLE
`bazel build @local_config_cc//...` failed on macOS Big Sur

### ISSUE THREAD

**Issue by kkpattern** [bazelbuild/bazel#14603]
### Description of the problem :

`bazel build @local_config_cc//...` failed on macOS Big Sur.

Error: `no such target '@local_config_cc_toolchains//:osx_archs.bzl': target 'osx_archs.bzl' not declared in package '';`.

The complete error output:

```bash
bazel build @local_config_cc//... --sandbox_debug
Starting local Bazel server and connecting to it...
ERROR: /private/var/tmp/_bazel_.../8f777a299a24713562d3cc77c8ffd989/external/local_config_cc/BUILD:12:6: no such target '@local_config_cc_toolchains//:osx_archs.bzl': target 'osx_archs.bzl' not declared in package ''; however, a source file of this name exists.  (Perhaps add 'exports_files(["osx_archs.bzl"])' to /BUILD?) defined by /private/var/tmp/_bazel_.../8f777a299a24713562d3cc77c8ffd989/external/local_config_cc_toolchains/BUILD and referenced by '@local_config_cc//:osx_archs.bzl'
ERROR: Analysis of target '@local_config_cc//:osx_archs.bzl' failed; build aborted: Analysis failed
INFO: Elapsed time: 3.041s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (4 packages loaded, 0 targets configured)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

run `bazel build @local_config_cc//...` on macOS Big Sur.

### What operating system are you running Bazel on?

macOS Big Sur 11.6

### What's the output of `bazel info release`?

release 4.2.2

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

Command output:

```bash
bazel build @local_config_cc//... --sandbox_debug
Starting local Bazel server and connecting to it...
ERROR: /private/var/tmp/_bazel_.../8f777a299a24713562d3cc77c8ffd989/external/local_config_cc/BUILD:12:6: no such target '@local_config_cc_toolchains//:osx_archs.bzl': target 'osx_archs.bzl' not declared in package ''; however, a source file of this name exists.  (Perhaps add 'exports_files(["osx_archs.bzl"])' to /BUILD?) defined by /private/var/tmp/_bazel_.../8f777a299a24713562d3cc77c8ffd989/external/local_config_cc_toolchains/BUILD and referenced by '@local_config_cc//:osx_archs.bzl'
ERROR: Analysis of target '@local_config_cc//:osx_archs.bzl' failed; build aborted: Analysis failed
INFO: Elapsed time: 3.041s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (4 packages loaded, 0 targets configured)
```

**Comment by keith** [comment]
Please provide the specific error output you're seeing

**Comment by kkpattern** [comment]
> Please provide the specific error output you're seeing

Hi, the error is `no such target '@local_config_cc_toolchains//:osx_archs.bzl': target 'osx_archs.bzl' not declared in package ''; `. I put it in the `Any other information, logs, or outputs that you want to share?` section. I added it in the problem description now.

**Comment by keith** [comment]
Can you test with this patch? I think this was meant to solve the same issue https://github.com/bazelbuild/bazel/pull/13529

**Comment by kkpattern** [comment]
> Can you test with this patch? I think this was meant to solve the same issue #13529

Thanks. I will try this patch. I haven't built bazel from source before so it may take a little time.

**Comment by kkpattern** [comment]
> Can you test with this patch? I think this was meant to solve the same issue #13529

I applied this patch to tag 4.2.2, now the command produces a new error:

`ERROR: While resolving toolchains for target @local_config_cc//:malloc: invalid registered toolchain '@local_config_cc_toolchains//:all': while parsing '@local_config_cc_toolchains//:all': error loading package '@local_config_cc_toolchains//': cannot load '@local_config_cc_toolchains//:osx_archs.bzl': no such file`.


I also tried the current master branch. The command succeeds.

**Comment by fmeum** [comment]
> I applied this patch to tag 4.2.2, now the command produces a new error:
> 
> `ERROR: While resolving toolchains for target @local_config_cc//:malloc: invalid registered toolchain '@local_config_cc_toolchains//:all': while parsing '@local_config_cc_toolchains//:all': error loading package '@local_config_cc_toolchains//': cannot load '@local_config_cc_toolchains//:osx_archs.bzl': no such file`.

This is the issue I am seeing with last_green as reported here https://github.com/bazelbuild/bazel/issues/14459.

**Comment by keith** [comment]
If you can reproduce that easily, can you test with last_green + my patch?

**Comment by fmeum** [comment]
> If you can reproduce that easily, can you test with last_green + my patch?

I'll try to get a custom bazel build into the CI tomorrow, but it may take a few days for the error to show up.

**Comment by cgrindel** [comment]
I was experiencing the same issue as described in this ticket. @keith patch applied to Bazel master appears to have fixed the  issue for me.

**Comment by fmeum** [comment]
@keith While I haven't seen the original issue since last_green started to include your patch, I'm now seeing a similar issue spuriously in CI:
```
ERROR: /Users/runner/work/rules_jni/rules_jni/tests/analysis/cc_jni_library/BUILD.bazel:3:11: Target '//analysis/cc_jni_library:libplatform_collision_native_lib.dylib' depends on toolchain '@local_config_cc//:cc-compiler-darwin', which cannot be found: no such target '@local_config_cc//:cc-compiler-darwin': target 'cc-compiler-darwin' not declared in package '' defined by /private/var/tmp/_bazel_runner/57f9d677e76d4e13231fc402e5e47107/external/local_config_cc/BUILD'
```

Note that I am in fact referencing `@local_config_cc//:cc-compiler-darwin` explicitly from my test, but I would have expected it to always be defined. 

Would it help if I printed the output of `$(bazel info output_base)/external/local_config_cc/BUILD` in CI and posted it here?

**Comment by keith** [comment]
Yes the contents of that BUILD file would be useful

**Comment by fmeum** [comment]
> Yes the contents of that BUILD file would be useful

I have added a step to my CI setup [here](https://github.com/fmeum/rules_jni/pull/50/files) and will post an update if it shows up again.
