### ISSUE TITLE
Tag convention for test targets to reserve more RAM

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#14601]
From https://docs.bazel.build/versions/main/test-encyclopedia.html#other-resources

> You can increase the reservation to a higher number of CPU cores by adding the tag "cpu:n" (where n is a positive number) to a test rule.

This allows a test target to ensure enough CPUs will be reserved for it to run, but there is no similar affordance for RAM. Instead there is only

https://docs.bazel.build/versions/main/be/common-definitions.html#common-attributes-tests

> size | String "enormous", "large" "medium" or "small", default is "medium"; optional
> ...
> Test sizes correspond to the following default timeouts and assumed peak local resource
usages:
> ...
> Size | RAM (in MB) | CPU (in CPU cores) | Default timeout
> small | 20 | 1 | short (1 minute)
> medium | 100 | 1 | moderate (5 minutes)
> large | 300 | 1 | long (15 minutes)
> enormous | 800 | 1 | eternal (60 minutes)

That seems to show that users can never reserve more than 800MB for a test target.
As a result, Bazel will OOM when scheduling too many parallel local spawns for tests that need more than 800MB.

**Comment by gregestren** [comment]
FYI https://docs.bazel.build/versions/main/exec-groups.html#using-execution-groups-to-set-execution-properties.

That's not a drop in replacement for this. It is a newer, more generic API intended to support broader resource needs.

I'd think about that API for whoever wants to address this.
