### ISSUE TITLE
`--use_top_level_targets_for_symlinks` doesn't apply through `alias()` targets

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#14602]
With this BUILD file:

```bzl
load("@build_bazel_rules_apple//apple:macos.bzl", "macos_command_line_application")

alias(
    name = "alias",
    actual = "cli",
)

cc_library(
    name = "lib",
    srcs = ["main.c"],
)

macos_command_line_application(
    name = "cli",
    minimum_os_version = "10.10",
    deps = ["lib"],
)
```

Building the CI directly with `--use_top_level_targets_for_symlinks` correctly results in a top level symlink:

```
% bazel build cli  --use_top_level_targets_for_symlinks
INFO: Analyzed target //:cli (23 packages loaded, 387 targets configured).
INFO: Found 1 target...
Target //:cli up-to-date:
  bazel-bin/cli
INFO: Elapsed time: 2.727s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

But building the alias target still uses the transition path:

```
% bazel build alias --use_top_level_targets_for_symlinks
INFO: Analyzed target //:alias (0 packages loaded, 1 target configured).
INFO: Found 1 target...
Target //:cli up-to-date:
  bazel-out/applebin_macos-darwin_x86_64-fastbuild-ST-45701c223259/bin/cli
INFO: Elapsed time: 0.218s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

repro project: [aliasrepro.zip](https://github.com/bazelbuild/bazel/files/7901022/aliasrepro.zip)

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 5.0.0 (not a regression, also repros on 4.2.2)

**Comment by joeleba** [comment]
Reassigning to Janak who added `--use_top_level_targets_for_symlinks` for triage. Thanks!

**Comment by janakdr** [comment]
Looks like this was actually added by the configurability team (I just moved the flag around). Passing over.

**Comment by sdtwigg** [comment]
This seems to be that the logic in //src/main/java/com/google/devtools/build/lib/buildtool/ExecutionTool.java is not sophisticated enough to consider 'look-through' aliases when doing the filtering.

(Really technically, by default, alias is treated as a rule that forwards all the providers of the aliased rule. In this case, the alias isn't experiencing the self-transition, its target is so the alias has an untransitioned top-level configuration. Consumers, like the logic handling `--use_top_level_targets_for_symlinks` have to specifically remember to dealias the alias if appropriate.)

**Comment by keith** [comment]
I've submitted https://github.com/bazelbuild/bazel/pull/15316 which appears to fix this
