### ISSUE TITLE
generate_workspace generates incorrect sha1 on some maven jars

### ISSUE THREAD

**Issue by pgr0ss** [bazelbuild/bazel#1461]
Most maven jars work just fine, but I've run into a few that generate an incorrect WORKSPACE. For example:

```
% ./output/bazel run //src/tools/generate_workspace -- --artifact=com.puppycrawl.tools:checkstyle:jar:6.11.2

INFO: Running command line: bazel-bin/src/tools/generate_workspace/generate_workspace '--artifact=com.puppycrawl.tools:checkstyle:jar:6.11.2'
Wrote:
/tmp/1467328940834-0/WORKSPACE
/tmp/1467328940834-0/BUILD
```
```
% tail -n 8 /tmp/1467328940834-0/WORKSPACE

# com.puppycrawl.tools:checkstyle:jar:6.11.2
maven_jar(
    name = "antlr_antlr",
    artifact = "antlr:antlr:2.7.7",
    sha1 = "83cd2cd674a217ade95a4bb83a8a14f351f48bd0  /home/maven/repository-staging/to-ibiblio/maven2/antlr/antlr/2.7.7/antlr-2.7.7.jar",
)
```

As you can see, it somehow put a path into the `sha1` field. I'm running latest master:

```
% ./output/bazel version
Another command is running (pid = 16736).  Waiting for it to complete...
Build label: 0.3.0-2016-06-30 (@a18add1)
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jun 30 23:15:38 2016 (1467328538)
Build timestamp: 1467328538
Build timestamp as int: 1467328538
```

**Comment by pgr0ss** [comment]
Upon further investigation, it seems like there are different formats to the sha1 file in maven:

```bash
% curl https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar.sha1
5fe28b9518e58819180a43a850fbc0dd24b7c050

% curl https://repo1.maven.org/maven2/antlr/antlr/2.7.7/antlr-2.7.7.jar.sha1
83cd2cd674a217ade95a4bb83a8a14f351f48bd0  /home/maven/repository-staging/to-ibiblio/maven2/antlr/antlr/2.7.7/antlr-2.7.7.jar
```

Would you be open to a pull request that splits on whitespace and returns the first entry here? https://github.com/bazelbuild/bazel/blob/7d265e07e7a1e37f04d53342710e4f21d9ee8083/src/tools/generate_workspace/src/main/java/com/google/devtools/build/workspace/maven/Resolver.java#L275-L276

**Comment by aehlig** [comment]
> Would you be open to a pull request that splits on whitespace and returns the first entry here? https://github.com/bazelbuild/bazel/blob/7d265e07e7a1e37f04d53342710e4f21d9ee8083/src/tools/generate_workspace/src/main/java/com/google/devtools/build/workspace/maven/Resolver.java#L275-L276

Yes, thanks! Feel free to send a pull request for this issue.


-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle
