### ISSUE TITLE
issue installing bazel under ubuntu

### ISSUE THREAD

**Issue by onyx22574** [bazelbuild/bazel#14619]
Per recommendation, I can't get [bazel installed](https://docs.bazel.build/versions/main/install-ubuntu.html#install-on-ubuntu) under Ubuntu

>:~/projects/tflite-micro$  sudo apt update && sudo apt install bazel
Ign:1 http://ppa.launchpad.net/team-gcc-arm-embedded/ppa/ubuntu focal InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 https://storage.googleapis.com/bazel-apt stable InRelease
Hit:5 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal InRelease
Hit:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Err:7 http://ppa.launchpad.net/team-gcc-arm-embedded/ppa/ubuntu focal Release
  404  Not Found [IP: 91.189.95.85 80]
Hit:8 http://security.ubuntu.com/ubuntu focal-security InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/team-gcc-arm-embedded/ppa/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely and is therefore disabled by default.

Can you please help how to fix the problem?

**Comment by aiuto** [comment]
Can you point point to the page that says how to install?
