### ISSUE TITLE
`--bes_upload_mode=fully_async` is ignored in Bazel 5

### ISSUE THREAD

**Issue by lukaciko** [bazelbuild/bazel#14620]
### Description of the problem / feature request:

Running a build with the `--bes_upload_mode=fully_async` doesn't have the expected effect. The build events are still uploaded synchronously after the command is run. This seems to happen when remote cache is used.

### Bugs: what's the simplest, easiest way to reproduce this bug? 

```
git clone git@github.com:bazelbuild/rules_java.git && cd rules_java
```
And then run at least twice so the Bazel server is running and the cache is populated:
```
env USE_BAZEL_VERSION=5.0.0 bazelisk build --remote_cache=grpcs://remote.buildbuddy.io --bes_backend=grpcs://remote.buildbuddy.io //java:srcs --bes_upload_mode=fully_async
```

After the build is complete it still takes a bit of time to do something, which I believe is uploading the BEP events. Changing `USE_BAZEL_VERSION` to 4.2.0 makes it snappier. This upload time is more noticeable in short builds that run more targets.

### What operating system are you running Bazel on?

macOS 12.0.1

### What's the output of `bazel info release`?

`release 5.0.0`

###  Have you found anything relevant by searching the web?

This seems similar to https://github.com/bazelbuild/bazel/issues/14576.

**Comment by Wyverald** [comment]
@bazel-io fork 5.1
