### ISSUE TITLE
http_achive should support 'maybe' parameter

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#14633]
There is a common idiom of writing workspace dependencies such that we are happy to take what the main repository defines, and only add our own if needed. Thus people write
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

def my_pkg_dependencies():
    maybe(
        http_archive,
        name = "bazel_skylib",
        urls = [...],
        ...
    )
    ...
```
This is ugly.  Instead of now having what looks like a rule, where `name` is the first arg, we have a wrapper that follows its own pattern. `http_archive` and related rules should allow one or more arguments that allow us to use whatever the workspace defines
- without warning
- or with a warning if they conflict

**Comment by Wyverald** [comment]
I don't think we should change this long-established pattern when we're focusing on Bzlmod anyway, where `maybe` doesn't even work. You can also no longer have repo name conflicts at all in Bzlmod (it's a hard error), so this issue becomes moot. Please feel free to reopen if you disagree though!

**Comment by aiuto** [comment]
I think we have a year before bzlmod rolls through all the repositories.
It may take longer to roll into older versions of rules used by people
still on the 4.x track.
