### ISSUE TITLE
download_and_extract failing

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#1464]
I changed a call to `new_http_archive` to now use a custom `repository_rule`. Inside the rule I try to use `download_and_extract` to fetch an archive:

    ctx.download_and_extract(
      "http://server/linux.tar.xz",
      ".",
    )

Which fails with:

    ERROR: /BUILD:20:1: no such package '@foo//': java.io.IOException: Error downloading from http://server/linux.tar.xz to /.../external/foo/@foo: Error downloading http://server/linux.tar.xz to /.../external/foo/@foo/linux.tar.xz: /.../external/foo/@foo/linux.tar.xz (No such file or directory) and referenced by '@bar//:blub'.

When executing `wget http://server/linux.tar.xz` downloading works fine.

Seems like multiple people have this problem: https://github.com/bazelbuild/bazel/issues/623

**Comment by damienmg** [comment]
Yes this is a known issue but #623 is unrelated.

ctx.file("empty") before it should fix. I believed I fixed this bug at HEAD.

**Comment by damienmg** [comment]
Yes this was fixed (see #1172), the fix is b0119d7

**Comment by abergmeier** [comment]
Indeed. Dumb me was running a stock 0.3 instead of our internal version (with b0119d7 in). Thanks.
