### ISSUE TITLE
--incompatible_disallow_empty_glob fails with local JDK

### ISSUE THREAD

**Issue by erikkerber** [bazelbuild/bazel#14646]
### Description of the problem / feature request:

Setting `--incompatible_disallow_empty_glob` fails on an empty blob in the local_jdk BAZEL.build file:

```
ERROR: Traceback (most recent call last):
--
  | File "/private/var/tmp/_bazel_user/757d2abf201e5b6570ee61ba6989ac5c/external/local_jdk/BUILD.bazel", line 177, column 16, in <toplevel>
  | srcs = glob(["include/**"]),
  | Error in glob: glob pattern 'include/**' didn't match anything, but allow_empty is set to False (the default value of allow_empty can be set with --incompatible_disallow_empty_glob).
```

### Feature requests: what underlying problem are you trying to solve with this feature?

Use `--incompatible_disallow_empty_glob`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I believe have a local JDK installed and attempt to build with `--incompatible_disallow_empty_glob`

### What operating system are you running Bazel on?

macOS 15.2

### What's the output of `bazel info release`?

```
release 5.0.0
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

I have not

### Any other information, logs, or outputs that you want to share?

> Replace this line with your answer.

**Comment by comius** [comment]
The problem is here https://github.com/bazelbuild/bazel/blob/cb01bde9369f8197cb54c34b14aa41f0dcc903cf/tools/jdk/jdk.BUILD#L174


It's also interesting, because `include` directory is present on Mac OS. 

@erikkerber Do you care to reveal what JDK version you're using? It should be located under `/Library/Java/JavaVirtualMachines/*/Contents/Home`

**Comment by erikkerber** [comment]
Looks like `jdk1.8.0_271.jdk`

It might help to clarify I only see this on our CI environment, which uses hosted macOS machines where the configuration ownership is one step away from my team.

**Comment by brentleyjones** [comment]
@Wyverald Could this get in 5.0.1?

**Comment by brentleyjones** [comment]
@bazel-io fork 5.1

**Comment by keith** [comment]
Related https://github.com/bazelbuild/rules_java/pull/101
