### ISSUE TITLE
test result xml remains even after test is deleted and `bazel test` is invoked

### ISSUE THREAD

**Issue by hanneskaeufler** [bazelbuild/bazel#14648]
### Description of the problem / feature request:

Old test xmls are not removed, even if the test target was deleted. Why is this a problem? If you e.g. run `bazel test //...` with a pipeline using the `junit` plugin to collect every junit, you will collect old/outdated xmls even with failing tests that no longer exist.

I created a small simple reproducing example in https://github.com/hanneskaeufler/bazel-test-logs-repro

### Feature requests: what underlying problem are you trying to solve with this feature?

Always having `test logs/**/*.xml` be an accurate reflection of what tests there are

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/hanneskaeufler/bazel-test-logs-repro

### What operating system are you running Bazel on?

macOS 12.1, Ubuntu Linux 18.04, Windows 10

### What's the output of `bazel info release`?

release 5.0.0-homebrew

###  Have you found anything relevant by searching the web?

I didn't find anything exactly matching my issue, but, one could imagine the issue also
being solved by producing an aggregate test.xml for all the tests that were actually run (or cached) such
as suggested in https://stackoverflow.com/questions/70130555/aggregating-bazel-test-reports-when-testing-many-targets

**Comment by comius** [comment]
This seems WAI. Any integration with Bazel shouldn't scan bin-dir for the outputs. Either parsing output of `bazel test //...` or even better parsing output of a query should provide the other end with the correct set of xmls that were produced.

**Comment by hanneskaeufler** [comment]
I guess yeah if diving into `bazel-*` is not intended and instead querying or parsing the stdout is the way to go, that solves it. It isn't what I had hoped would be the resolution, but I can understand that :)

**Comment by brentleyjones** [comment]
Instead of parsing the stdout, you can look at the [BEP](https://bazel.build/docs/build-event-protocol).

**Comment by haxorz** [comment]
Yes this is WAI. @brentleyjones 's suggestion to use the BEP is a good one.
