### ISSUE TITLE
`Error in path: Not a regular file` when using `repository_ctx.path("$(ALIASED_LABEL)")`

### ISSUE THREAD

**Issue by lummax** [bazelbuild/bazel#14644]
### Description of the problem / feature request:

When using `repository_ctx.path()` on a label that points to an `alias()` rule, `bazel` produces the following error:

```
ERROR: An error occurred during the fetch of repository 'some_repository':
   Traceback (most recent call last):
	File "/home/XXX/repos/other/bazel-repository-path-alias-reproducer/main/defs.bzl", line 2, column 30, in _impl
		print(repository_ctx.path(repository_ctx.attr.ref))
Error in path: Not a regular file: /home/XXX/.cache/bazel/XXX/c0e0ba2d225c59d86e3f0cdfb7e8204a/external/other/file
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I've created a simple reproducer in https://github.com/lummax/bazel-repository-path-alias-reproducer

- `main` is the main workspace and sets up a `local_repository()` pointing to `other`
- `other` contains a file `some_file` and defines an `alias()` called `file` to it
- when defining and calling a `repository_rule()` in `main` that resolves the alias via `repository_ctx` we get the error

```
git clone https://github.com/lummax/bazel-repository-path-alias-reproducer.git
cd bazel-repository-path-alias-reproducer/main
bazelisk build //...
```

### What operating system are you running Bazel on?

Ubuntu 20.04 LTS and Windows 10

### What's the output of `bazel info release`?

- `release 5.0.0`
- reproduces also with `release 6.0.0-pre.20220112.2`

###  Have you found anything relevant by searching the web?

No

**Comment by Wyverald** [comment]
This is working as intended. `repository_ctx.path` ([docs](https://docs.bazel.build/versions/main/skylark/lib/repository_ctx.html#path)) can only point to plain files, not build targets (even if it's an `alias` to a plain file).

**Comment by lummax** [comment]
Alright, thank you!

I did read the documentation, but did not connect that this applies to `alias()` aswell, maybe I got confused by "the label should point to a non-generated file" and thought this is only about actual outputs.
