### ISSUE TITLE
repository_ctx label attributes not properly bound

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#1465]
This might not be a bug.
Implementing repository_rule like so:

```
repository_ctx.symlink(repository_ctx.attr.mylabel, "BUILD")
```

and in `WORKSPACE`:

```
my_repo_rule(
  mylabel = "third_party/BUILD.spec",
)
```

Leads to it not searching `BUILD.spec` in the root but in external.
Changing to:

```
  mylabel = "//:third_party/BUILD.spec",
```

works though.

Intended?

**Comment by abergmeier** [comment]
Find it strange that `third_party/BUILD.spec` works in the build-in repo-rules.

**Comment by damienmg** [comment]
Ok this is WAI if mylabel is of type string.

The string get then converted directly to a path, not converting to a label in between. Declaring it as a label should works (although third_party/BUILD.spec would be converted to //external:third_party/BUILD.spec in the context of the workspace).

**Comment by abergmeier** [comment]
Here is the missing rule:

    def _impl(ctx):
      ctx.symlink(ctx.attr.mylabel, "BUILD")

    my_repo_rule = repository_rule(
      implementation = _impl,
      local = False,
      attrs = {
        "mylabel": attr.label(allow_files = True, mandatory = True)
      }
    )

**Comment by damienmg** [comment]
Ok this is definitely a bug then :)

**Comment by damienmg** [comment]
After much reflexion, I am unsure this is a bug.

It resolve the label in the context of the repository therefore it is relative to the package. The expected behavior is that it is relative to the root package. That the whole strangeness in the WORKSPACE file defining a external package.

Dropping priority anyway.

**Comment by dslomov** [comment]
WAI
