### ISSUE TITLE
Clarify `genfile()` example in Macros documentation

### ISSUE THREAD

**Issue by fricklerhandwerk** [bazelbuild/bazel#14662]
### Description of the problem / feature request:

The [file generator example in Macros#Usage](https://docs.bazel.build/versions/main/skylark/macros.html#usage) is confusing for newcomers as it is not obvious if `//:generator` is something that belongs to Bazel/Starlark. In this case it is an arbitrary name that could as well be `//:foo`.

Clarify by rewording, see [my proposal](https://github.com/fricklerhandwerk/bazel/commit/2769825fbeb4193d23d4ea06773da68408fd40b0).

**Comment by fweikert** [comment]
A note regarding your proposal: The file was moved to https://github.com/bazelbuild/bazel/blob/master/site/en/extending/macros.md when migrating to the new site.

**Comment by keertk** [comment]
Hi @fricklerhandwerk Could you please submit a new PR/proposal if you're still interested in pursuing this? We're closing this issue for now to clean up. Thank you!
