### ISSUE TITLE
cquery returns SOURCE_FILE entries for directories

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/bazel#14678]
I'm currently trying to write code which hashes the transitive inputs to rules, to determine when they've changed. When directories are referred to in source lists, they're reported in cquery as of type SOURCE_FILE. It's unclear whether the correct behaviour should be to ignore the directory, note its existence but ignore its contents, or recurse into it. I'd suggest that in any case, a change in the output would be useful.

With the following set-up:
```console
% cat >BUILD <<EOF
filegroup(
    name = "fg",
    srcs = ["directory"],
)
EOF

% mkdir directory
% touch directory/file1
```

CQuerying about the filegroup says it depends on the directory:

```console
% bazel cquery --output=jsonproto //:directory 2>/dev/null
{
  "results": [{
    "target": {
      "type": "SOURCE_FILE",
      "sourceFile": {
        "name": "//:directory",
        "location": "/Users/dwagnerhall/tmp/bazelplay/BUILD:1:10",
        "visibilityLabel": ["//visibility:private"]
      }
    },
    "configuration": {
      "checksum": "null"
    }
  }]
}
```

And cquerying about the directory says it's a source file:

```console
% bazel cquery --output=jsonproto //:fg 2>/dev/null
{
  "results": [{
    "target": {
      "type": "SOURCE_FILE",
      "sourceFile": {
        "name": "//:directory",
        "location": "/Users/dwagnerhall/tmp/bazelplay/BUILD:1:10",
        "visibilityLabel": ["//visibility:private"]
      }
    },
    "configuration": {
      "checksum": "null"
    }
  }]
}
```

I would expect any of the following:
1. A glob expansion to happen, and either `//:fg`'s ruleInputs to be expanded to a set of source files, or for `//:directory` to in some way indicate there are multiple files it represents (like a middleman-ish).
2. No glob expansion to happen, and directory is somehow noted to be a "EMPTY_SOURCE_DIRECTORY" rather than a "SOURCE_FILE".
3. No glob expansion to happen, and the directory is pruned from the ruleInputs because it's spurious.
4. An error, because the rule is invalid.

Referring to a directory as a SOURCE_FILE seems odd, particularly, for my use-case of trying to has transitive rule inputs.

/cc @katre - this is similar to https://github.com/bazelbuild/bazel/issues/14611

**Comment by katre** [comment]
You're right, this is the same as with #14611: since Bazel doesn't do a stat for every unrecognized name, it assumes that each name is an input file.

The solution would be the same, also: a mode for {c,}query where files _are_ statted to see if they exist and what they actually are. I'm not sure this is anything we'd be able to prioritize, however.

**Comment by larsrc-google** [comment]
cc @meisterT

**Comment by meisterT** [comment]
cc @alexjski
