### ISSUE TITLE
Increase flexibility for transitions, for deploys

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/bazel#14672]
### Description of the problem / feature request:

1. Allow transitions to output any settings.
2. Allow Starlark to read platforms.

I realize this is a two-in-one, but I think it would be hard to describe the motivation separately.

### Feature requests: what underlying problem are you trying to solve with this feature?

I want to write an executable deploy target. It has an attribute for the user specify an artifact, and a private attribute for the deployment executable itself.

```bzl
example_deploy(
  name = "example.deploy",
  package = ":example",
)
```

Running `bazel run //:example.deploy` uploads the artifact to some repository.

There are three configurations at play:

* exec: Where the artifact and deployment executable is built.
* target/host: The platform the deployment executable runs on.
* artifact: The settings for the deployed artifact itself.

I can do a user-definition transition for the last one and read from build settings

```sh
bazel run --//deploy:cpu=arm --//deploy:compilation_mode=opt
```

However, there are many settings that could be used to build the artifact, *unknown the the author of the deploy rule.* (The artifact may have multi-language parts, like a C shared library.)

So it'd be nice to allow the end user to define any settings for the artifact.

```sh
bazel run --//deploy:setting=//command_line_option:cpu=arm --//deploy:setting=//comand_line_option:compilation_mode=opt
```

However, the output possibilities for the transition must be enumerated by the transition.

Additional, it would be nice to specify the platform, like the user can do elsewhere.

```sh
bazel run --//deploy:platform=@platforms//os:windows
```

However, AFAIK the platform specifics are not available.

###  Have you found anything relevant by searching the web?

Deploys/publishing are *extremely* common actions.

And though there are certainly deploy rules (Maven, Docker), I can't quite figure out how anyone addresses this problem. I think it's just ignored.

It's very possible I'm missing something, but it seems like `bazel run` deploys require an additional configuration, and there is no ergonomic was to provide generic options to that configuration.

### Any other information, logs, or outputs that you want to share?

An alternative is to run Bazel in multiple steps: Run `bazel build`, then `bazel run` with arguments to bazel-bin directory.

This seems unfortunate, as transitions should allow us to avoid this.

**Comment by katre** [comment]
It seems like you're approach this backwards: you should have the artifact built in the target configuration with no change (allowing the user to specify any flags that they normally would for such a build), and then use a transition for the command that actually runs the upload. This would have the benefit that you, as the author of `example_deploy`, know exactly what flags your transition cares about (or make sense for users to use), so there's no need to allow for a general set of flags to transition.

I'm not clear what you're asking for with platforms: You can use the [`ctx.target_platform_has_constraint`](https://docs.bazel.build/versions/5.0.0/skylark/lib/ctx.html#target_platform_has_constraint) method to find out what the current target platform looks like in a rule. Further, you can define your own custom platforms and then transition the `--platforms` flag to that new value if you want to.

One idea, using your `example_deploy` rule:
```
platform(
    name = "deployment_site",
    constraint_values = [ ... whatever makes sense ],
)
example_deploy(
    name = "example.deploy",
    package = ":example",
    platform = ":deployment_site",
)
```

Your rule's transition could then make sure that `:example` is built with all command-line flags kept in place, but the value of `--platforms` changed to `:deployment_site`.

**Comment by katre** [comment]
One of our long-term goals is to remove users' need to set flags as much as possible: if a value can be set in the build graph (ie, in a BUILD file or as part of a rule definition) it should be, so that users only need to specify the targets they want to build and any configuration overrides they need.
