### ISSUE TITLE
objc_library not passing along cc deps

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#1467]
We have the following setup.

    cc_library(
      name = "base",
      hdrs = [ "include/base.h" ],
      includes = [ "include" ],
    )
    objc_library(
      name = "objc",
      srcs = [ "my.mm"],
      deps = [ ":base" ],
    )
    
Now if a cc_library `foo` depends on `objc`, it can not access `base.h`.

For that to work I have to add:

    cc_library(
      name = "objc_cc",
      deps = [ ":objc", ":base" ],
    )

and then have `foo` depend on `objc_cc` and it can access `base.h`.
Is this intentional?

**Comment by aehlig** [comment]
> Now if a cc_library foo depends on objc, it can not access `base.h`

This is working as intended, as `base.h` would only be an indirect dependency of
that new library. See the [header inclusion checking](http://www.bazel.io/docs/be/c-cpp.html#hdrs) section of the [cc_library_rule](http://www.bazel.io/docs/be/c-cpp.html#cc_library).
