### ISSUE TITLE
container_import config is not optional

### ISSUE THREAD

**Issue by vishrantgupta** [bazelbuild/bazel#14674]
### Description of the problem / feature request:

> The documentation of container_import says `config` is an optional field, but the build is failing when `config` value is not set https://github.com/bazelbuild/rules_docker/blob/master/docs/container.md#container_import

The source code suggests it's a mandatory field:

https://github.com/bazelbuild/rules_docker/blob/9096572c4b3744493dbce513aa1407c68dd1e39a/container/import.bzl#L99
```
    container_parts = {
        # A list of paths to the layer digests.
        "blobsum": blobsums,
        # The path to the v2.2 configuration file.
        "config": ctx.files.config[0],
        "config_digest": _sha256(ctx, ctx.files.config[0]),
```

### Feature requests: what underlying problem are you trying to solve with this feature?

> Either fix the documentation or fix the source code

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Declare the `container_import` and run the build command

### What operating system are you running Bazel on?

```
root@ba5cc0a3f0b7:/tcx# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### What's the output of `bazel info release`?

> release 4.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> N?A

### Any other information, logs, or outputs that you want to share?

> N/A

**Comment by gregestren** [comment]
Hi Vishrant,

Does this issue fit here or in [ @bazelbuild/rules_docker?](https://github.com/bazelbuild/rules_docker)?

**Comment by sgowroji** [comment]
Hello Vishrant, Hope you are doing well!
I wanted to check with you on the above [comment](https://github.com/bazelbuild/bazel/issues/14674#issuecomment-1026307509), Could you please confirm on the same with complete details. It will be closed very soon, if no further activity occurs on this issue. Thank you.

**Comment by sgowroji** [comment]
Hello @vishrantgupta, We are closing this issue as there is no significant response from you from last 7 days. Thanks!
