### ISSUE TITLE
Provide the exec CPU to repository rules

### ISSUE THREAD

**Issue by uhthomas** [bazelbuild/bazel#14685]
### Description of the problem / feature request:

Repository rules already have access to `repository_os` which allows rules to change their behaviour based on the exec OS. Repository rules should also know the exec architecture. Repository rules currently work around this limitation by  `uname -m`, which isn't ideal. See [rules_go](https://github.com/bazelbuild/rules_go/blob/fd11dd2768669dc2cc1f3a11f2b0b81d84e81c32/go/private/sdk.bzl#L253).

### Feature requests: what underlying problem are you trying to solve with this feature?

Repository rules create potentially brittle and strange workarounds to get the exec CPU. There is no standardisation and no official guidance on how best to create repository rules which target multiple platforms.

### What operating system are you running Bazel on?

Linux x86_64

### What's the output of `bazel info release`?

```sh
❯ bazel info release
Starting local Bazel server and connecting to it...
release 5.0.0
```

###  Have you found anything relevant by searching the web?

> Replace this line with your answer.

- https://github.com/bazelbuild/bazel/issues/11655#issuecomment-734212603
- https://github.com/bazelbuild/bazel/issues/4636 (request was target, not exec)

### Any other information, logs, or outputs that you want to share?

N/A

**Comment by brentleyjones** [comment]
I've found the need for this as well, when trying to target x86_64 macOS RBE from arm64 macOS. Repository rules incorrectly use arm64 binaries which fail to run on RBE.

**Comment by uhthomas** [comment]
Also see [rules_rust](https://github.com/bazelbuild/rules_rust/blob/14468f97b9a06ab6b33e94bc87c1d24b2433e5f8/crate_universe/private/util.bzl#L18).

**Comment by fmeum** [comment]
I started working on this in #14738, but then noticed that this is more subtle than expected: The natural implementation would be to just return `System.getProperty("os.arch").toLowerCase(Locale.ROOT)`, but that is just the architecture of the JDK Bazel is running on, which is not necessarily the same as the architecture of the operating system Bazel is running on. For example, which value should this have in the case of an x86_64 JDK executing Bazel using Rosetta on an aarch64/arm64 M1 Mac?

@uhthomas @brentleyjones Could you clarify what exactly you would want to know the architecture of? You also referred to RBE, but repository rules could only ever provide the _host_ CPU, not the _exec_ CPU (which isn't even known during the loading phase since it depends on the result of toolchain resolution). Is that sufficient for your use cases?

**Comment by keith** [comment]
For a M1 mac running through Rosetta x86_64 is right IMO, since the emulation should affect everything.

**Comment by uhthomas** [comment]
My intended use-case is to solve the multi cpu/os repository problem where rule maintainers write odd hacks to detect the exec (host?) CPU. For example the Go rules declare a signal repository, `go_sdk` which will automatically detect the correct SDK to use. The `go_download_sdk()` rule uses [uname](https://github.com/bazelbuild/rules_go/blob/fd11dd2768669dc2cc1f3a11f2b0b81d84e81c32/go/private/sdk.bzl#L253) to do this detection.

It's been suggested that multiple repositories for the corresponding cpu and os should be declared ([ref](https://github.com/bazelbuild/bazel/issues/11655#issuecomment-734212603)), but this can be really messy and weird.

`select` does not work with repository rules and there is no clear guidance on how to actually do this, which is weird considering this is extremely common.

The M1 situation is a bit weird and I don't really know what the right answer is. I think it should depend on whether the architecture of the Bazel binary, as there is no other way to differentiate between native and rosetta at current.

Does what I've written make sense, and is it clear what the goal of this issue is?

**Comment by brentleyjones** [comment]
>Could you clarify what exactly you would want to know the architecture of? You also referred to RBE, but I think that repository rules could only ever provide the host CPU, not the exec CPU (which isn't even known during the loading phase since it depends on the result of toolchain resolution). Is that sufficient for your use cases?

I would like the know the architecture of `--host_platform`. If I don't run Bazel through Rosetta, all repository rules will see arm64, even if I set `--host_platform` to a platform with `x86_64` cpu.

**Comment by uhthomas** [comment]
Awesome @fmeum, your PR looks great. Thanks for taking a look at this! :)

Is there some reference which lists the possible values of `os.arch` and `os.name`?

For my own sanity also, are repository rules executed on the host platform, or the execution platform? More specifically, will the values of `os.arch` and `os.name` be of the host platform, or execution platform?

**Comment by uhthomas** [comment]
Additionally, how does this all fit into platforms? If at all. I think it might be strange to use the Platforms API in most cases, but the repository_os struct in others. What are your thoughts?

**Comment by fmeum** [comment]
> Is there some reference which lists the possible values of `os.arch` and `os.name`?

The two sources I usually refer to are the OpenJDK sources and Bazel's [CPU](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/util/CPU.java) and [OS](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/util/OS.java) classes.

> For my own sanity also, are repository rules executed on the host platform, or the execution platform? More specifically, will the values of `os.arch` and `os.name` be of the host platform, or execution platform?

> Additionally, how does this all fit into platforms? If at all. I think it might be strange to use the Platforms API in most cases, but the repository_os struct in others. What are your thoughts?

My understanding is that repository rules are always executed locally (i.e., on the host), even with RBE, and don't really have a concept of platforms. Rather, platforms could be used to select the correct repository among the instances of a repository rule for the different platforms. Bazel would then only fetch the repository rules that are relevant for the current configuration. In this context, `repository_os` is more of a shortcut geared towards local execution, whereas sophisticated RBE setups would probably favor the approach described in https://github.com/bazelbuild/bazel/issues/11655#issuecomment-734212603.

**Comment by meteorcloudy** [comment]
I think https://github.com/bazelbuild/bazel/pull/14738 solves exactly the request of this issue. The `repository_ctx.os.name` and `repository_ctx.os.arch` return the values for the host platform (which is the one Bazel runs on), this should be enough as in most cases repository rules run locally. 

But we do have a way to make `repository.execute` [run commands on RBE](https://docs.bazel.build/versions/main/skylark/lib/globals.html#repository_rule(implementation,%20attrs,%20local,%20environ,%20configure,%20remotable,%20doc)), but this is a very much experimental feature and currently unmaintained.

I also agree if Bazel runs in a simulation it should just get the simulated arch. We do provide native arm64 binaries for Linux and macOS, arm64 support for Windows has also been [added](https://github.com/bazelbuild/bazel/issues/14339) recently.

**Comment by brentleyjones** [comment]
@bazel-io flag

**Comment by brentleyjones** [comment]
(I miss-read what that command was for, this isn't a blocker, sorry.)

**Comment by meteorcloudy** [comment]
OK, I removed the flag. But I guess we could still cherry-pick this to 5.1? @Wyverald

**Comment by meteorcloudy** [comment]
@bazel-io block 5.1

**Comment by meteorcloudy** [comment]
The fork command will create an associate issue to track the cherry-pick, feel free to send a PR!

**Comment by brentleyjones** [comment]
FYI, the fork command doesn't work for everyone: https://github.com/bazelbuild/bazel/pull/14272#issuecomment-1032639208

**Comment by uhthomas** [comment]
Amazing, thank you for the work on this. I look forward to using it! I'll make contributions for the major rules to also take advantage of this new attribute when available.

For clarification; this only provides info for the host OS, correct? What happens in a remote execution context? Are those actions still executed locally? I suppose it depends on the declared toolchains.

Is there any official guidance on how best to write repository rules for compatibility with remote execution? It seems to me like it may still be the case that rule authors must declare every cpu/os combination as repositories and reference them via toolchains.

Maybe I'm missing something 🙂
