### ISSUE TITLE
Bazel traverses generated symlink and fails to build

### ISSUE THREAD

**Issue by kbatra3** [bazelbuild/bazel#14683]
### Description of the problem / feature request:

Occasionally when I try to build with bazel I get the error 
```
[kbatra@dev-1 test-repo] bazel build -c opt //...
INFO:  Scaled resource values: 128 cores, 131072 MB
Starting local Bazel server and connecting to it...
ERROR: error loading package 'bazel-test-repo/external/bazel_tools/src/main/protobuf': Label '//third_party/grpc/bazel:cc_grpc_library.bzl' is invalid because 'third_party/grpc/bazel' is not a package; perhaps you meant to put the colon here: '//:third_party/grpc/bazel/cc_grpc_library.bzl'?
INFO: Elapsed time: 131.090s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (125 packages loaded)
    currently loading: bazel-test-repo/external/bazel_tools/src/main/native ... (5 packages)
```
Bazel seems to enter into the symlink that it creates (`bazel-test-repo`) and tries to build the files in `bazel-test-repo/external/bazel_tools/src/main/protobuf`. When I add `bazel-test-repo` to the `.bazelignore` the issue seems to go away.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The issue is nondeterministic, but I can get this issue by building at the root of my project with `bazel build //...`

### What operating system are you running Bazel on?

CentOS Linux release 7.7.1908 (Core)

### What's the output of `bazel info release`?

release 4.1.0

**Comment by sgowroji** [comment]
Hello @kbatra3 , Hope you are doing well!
I wanted to check with you on the above issue whether if you are still able to reproduce or resolved, Can you please share the complete details. It will be closed very soon, if no further activity occurs on this issue. Thank you.
