### ISSUE TITLE
Bazel build event file lost `test.xml` reference in `test_action_output` for cached test with `--remote_download_minimal` flag

### ISSUE THREAD

**Issue by bozaro** [bazelbuild/bazel#14698]
### Description of the problem / feature request:
I want to check compiltaion and get test result using remote build farm without transfering large binary files to bazel client.

For this I try run `bazel build //... --remote_download_minimal --remote_executor=grpcs://... --build_event_binary_file=bazel.events.bin` and try get remote test results by parsing build event file.

Unfortunately when I use `--remote_download_minimal` flag I don't have `test.xml` reference in build events file.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

NOTE: This example reproduce this issue using `--disk_cache`, but it can be stable reproduced with bazel buildfarm `--remote_executor=grpcs://...`.

#### 1. Checkout really small repository (branch `test_action_output`): https://github.com/bozaro/bazel-play/tree/test_action_output
Repository contains:
 - empty `WORKSPACE` file;
 - build script `BUILD` file:
```
sh_test(
    name = "simple_test",
    srcs = ["simple.sh"],
)
```
 - minimal test script `simple.sh` file:
```sh
#!/bin/sh
echo '<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="simple_test" tests="1" failures="0" errors="0">
    <testcase name="simple_test" status="run" duration="5" time="5">
      <system-out>Hello, world!!!</system-out>
    </testcase>
  </testsuite>
</testsuites>
' | tee ${XML_OUTPUT_FILE}
```

#### 2. Clean run tests:
```
rm -fR .cache
bazel clean
bazel test //... --remote_download_minimal --build_event_binary_file=bazel.events.bin --build_event_text_file=bazel.events.txt --disk_cache=.cache
``` 
After that I can find `test.log` and `test.xml` reference in `bazel.events.bin` and `bazel.events.txt` files.

For example:
```
test_result {
  test_action_output {
    name: "test.log"
    uri: "file:///home/bozaro/.cache/bazel/_bazel_bozaro/57ca677fe0293e8ce868d480187c263c/execroot/__main__/bazel-out/k8-fastbuild/testlogs/simple_test/test.log"
  }
  test_action_output {
    name: "test.xml"
    uri: "file:///home/bozaro/.cache/bazel/_bazel_bozaro/57ca677fe0293e8ce868d480187c263c/execroot/__main__/bazel-out/k8-fastbuild/testlogs/simple_test/test.xml"
  }
  test_attempt_duration_millis: 14
  status: PASSED
  test_attempt_start_millis_epoch: 1643891931292
  execution_info {
    strategy: "linux-sandbox"
  }
  test_attempt_start {
    seconds: 1643891931
    nanos: 292000000
  }
  test_attempt_duration {
    nanos: 14000000
  }
}
```

#### 3. Run locally cached tests:
```
bazel test //... --remote_download_minimal --build_event_binary_file=bazel.events.bin --build_event_text_file=bazel.events.txt --disk_cache=.cache
```
I still can find `test.log` and `test.xml` reference in `bazel.events.bin` and `bazel.events.txt` files.

#### 4. Run remote cached tests:
```
bazel clean
bazel test //... --remote_download_minimal --build_event_binary_file=bazel.events.bin --build_event_text_file=bazel.events.txt --disk_cache=.cache
```
I still can find `test.log` reference in `bazel.events.bin` and `bazel.events.txt` files. But I can't find `test.xml` reference in `bazel.events.bin` and `bazel.events.txt` files.

But I expects to see some `test.xml` reference to remote cache or disk cache.

For binary files I can see cache reference to complied executable files.

### What operating system are you running Bazel on?
Ubuntu 21.10

### What's the output of `bazel info release`?
```
bazel info release
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
INFO: Invocation ID: 46b9e66b-fe2b-4d3b-97fa-2c314975b6bc
release 5.0.0
```

**Comment by tjgq** [comment]
Not stale, I'll take a look to see if it's still an issue.

**Comment by tjgq** [comment]
This seems to no longer be an issue in 6.2.1.
