### ISSUE TITLE
Support partial build cheat mode for building only specific targets

### ISSUE THREAD

**Issue by guw** [bazelbuild/bazel#14699]
### Description of the feature request:

We would like to be able to build a list of targets with Bazel where only the specific targets get build and not any of its required dependencies.
```
cat targets.bzl:
//some/package:all  
//other/package:all
//app/app:binary
bazel build --skip-dependencies  $(cat targets.bzl)
```

### What underlying problem are you trying to solve with this feature?

We are migrating a Java+Maven monolith to Bazel.
Our Maven build today works in a similar mode. It allows to build only a reactor subset.
Developers are able to select the subset (their "working set") and build only those jars.

Unfortunately, our graph is not well balanced. It's more like a hourglass.
We know exactly what needs to happen but this will take years to transform.

Introducing Bazel will make the developer experience worse in the beginning.
While we are working on addressing the issues in the graph we would like our developers to continue using a "cheat mode".

**Comment by aiuto** [comment]
See: https://groups.google.com/g/bazel-discuss/c/7S_wo-RYvJk/m/gg35mYubAwAJ

**Comment by gregestren** [comment]
I'm not sure `team-Core` are the right people to triage, but it's the closest team label I can think of for this. `team-Core` folks: we can figure out who else should look at this if you don't have answers.

That said, I think this is unlikely to be something we'll want Bazel to support. Targets depend on their dependencies by definition. It's not safe or correct, generally speaking, to build a target without building its deps first. I assume for your case you know that's safe. Which begs the question: why are those deps in the first place if they don't matter?

Your issue may make most sense as a "how can I easily migrate to Bazel" question. If we take it that way I'll see if I can link in someone who pays attention to migration challenges.

**Comment by guw** [comment]
> Targets depend on their dependencies by definition. It's not safe or correct, generally speaking, to build a target without building its deps first. I assume for your case you know that's safe.

To clarify: I'm asking for building a set of targets **while** forcing all its dependencies (and everything in the graph) from the local (or remote) cache, ignoring any local input changes, which would trigger a rebuild of dependencies and dependents.

> Your issue may make most sense as a "how can I easily migrate to Bazel" question. If we take it that way I'll see if I can link in someone who pays attention to migration challenges.

Correct. Our dependency/build graph looks like an hourglass. Certain modifications will trigger a rebuild of almost the entire graph. Most of these rebuilds are unnecessary even though they are correct. It will take time to transform our graph into a better state. Till then we want to make developers suffer less by allowing them to cheat (as we are currently doing in Maven).

**Comment by gregestren** [comment]
> Correct. Our dependency/build graph looks like an hourglass. Certain modifications will trigger a rebuild of almost the entire graph. Most of these rebuilds are unnecessary even though they are correct. It will take time to transform our graph into a better state. Till then we want to make developers suffer less by allowing them to cheat (as we are currently doing in Maven).

What would be an example of one of those modifications?

**Comment by guw** [comment]
> What would be an example of one of those modifications?

We have a code generator that relies on *.xml input files in a central directory. The rate of change in that directory is unfortunately quite high (several commits per day). The code generator is used in hundreds of packages to generate package specific code. All these generator targets depend on the central directory. Any change causes re-execution of all generator targets even though only one package would be needed.

To make it worse, the generator is not producing a Java jar with class filed but a source jar. This source jar gets compiled together with the main java_library of such packages (because of circular dependencies between the generated code and the code using the generated code). Thus, the whole package will get recompiled. One of these packages has a compilation time of 10 minutes.

Another example is improper separation of impl/api code in combination with too many dependents. This leads to many public signature changes in Java code, which triggers recompilation of dependents (again Java).

**Comment by gregestren** [comment]
That makes sense, thank you. I was wondering if there were silly dependencies we might conceptually be able to optimize out. But for scenarios like that I think it's going to be hard to avoid ultimate refactoring, as you already know.

**Comment by uri-canva** [comment]
You can implement your own cheating rules by abusing `unused_inputs_list`: https://bazel.build/rules/lib/actions#run.
That lets your rule pretend it didn't use inputs it actually used. That switches the problem to "how do I force a rule that is cached to execute again" which is a better understood problem, for which you can find plenty of workarounds.

**Comment by guw** [comment]
That's an interesting idea. I did some searching and it does not seem to be supported by any of the Java actions, though.

**Comment by uri-canva** [comment]
Yeah I don't think you can use `java_common.compile` for that, you'd have to implement java compilation yourself in starlark.
