### ISSUE TITLE
--dynamic_mode=off still results in shared library creation attempt 

### ISSUE THREAD

**Issue by kayasoze** [bazelbuild/bazel#147]
I have one C++ toolchain which does not support shared libraries, but other toolchains that do.  I'd like to disable `-shared`, but only when compiling with this particular toolchain.  Invoking bazel with `--dynamic_mode=off` still results in a `-shared` flag, however, which in my case causes link-time errors against the (non-relocatable) runtime.

**Comment by kayasoze** [comment]
To be clear: the -shared flag is merely the byproduct of an attempt to create a shared library, which will fail.

**Comment by kayasoze** [comment]
Note that it is not possible to specify cc_library's linkstatic via select()

**Comment by ulfjack** [comment]
That should only happen if you build cc_library rules 'directly' on the command-line. If you build the cc_binary, then it should work. If you want to build something like //foo/..., you can try something like this:
blaze build `blaze query "//foo/... - kind(cc_library, //foo/...)"`

We're planning some changes to cc_library that should fix this, namely removing the implicit .a and .so outputs of cc_library - that will break rules that try to refer to them directly, but then you should never do that.

**Comment by kayasoze** [comment]
That is indeed my situation: I'm building the library directly; not out of necessity, but rather convenience.  Thanks for the rapid explanation.

**Comment by hanwen** [comment]
@kayasoze - is there still a bug left to address here, or is your problem resolved?

**Comment by kayasoze** [comment]
It might be confusing to new users to see this behavior, and the workaround reduces the utility of Bazel globbing (e.g. /...) but I'm good.

**Comment by oquenchil** [comment]
https://docs.bazel.build/versions/master/command-line-reference.html explicitly says it will turn off dynamic mode for **binaries**.
