### ISSUE TITLE
No param docs available for Skylark methods that are SkylarkCallables

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel#1470]
Currently, there are no param docs available for Skylark methods that are Java methods (as opposed to Skylark builtins). This is because, unlike `SkylarkSignature`, the `SkylarkCallable` annotation does not supporting documenting individual params.

**Comment by damienmg** [comment]
I was working on fixing that along with adding description of parameters to enable kwargs for skylark remote repository. I have a CL almost ready for it but I had to put it on hold for other higher priorities items.

**Comment by davidzchen** [comment]
Awesome!

**Comment by damienmg** [comment]
blocking #1426
