### ISSUE TITLE
Can't use non-bazel native libs with java_import

### ISSUE THREAD

**Issue by arohner** [bazelbuild/bazel#14719]
Bazel 3.7.2 and 4.0.0

I'm trying to include in the build a java library that requires a native library on the library path at runtime. I've tried `rules_foreign_cc` and plain `cc_import`, in both cases I get:

```
in runtime_deps attribute of java_import rule @deps//:caesium_caesium: cc_import rule '//native:libsodium' is misplaced here (expected java_library, java_import, cc_library or cc_binary) and '//native:libsodium' does not have mandatory providers: 'JavaInfo'
```

I would like a way to include the native library without having to convert its build to Bazel

**Comment by comius** [comment]
java_import at the moment only allows cc_library and cc_binary rules in runtime_deps. Perhaps you can wrap cc_import as a workaround?
