### ISSUE TITLE
How to compile c++ JNI binary? CreateJavaVMs

### ISSUE THREAD

**Issue by hcoona** [bazelbuild/bazel#14720]
I learned to depends on `@bazel_tools//tools/jdk:jni` for JNI c++ library targets. However, I need to write a c++ program in which call Java library. How to do so?

depends on `@bazel_tools//tools/jdk:jni` would generate the following error messages:

```
ld.lld: error: undefined symbol: JNI_GetCreatedJavaVMs
>>> referenced by jni_helper.c
>>>               bazel-out/k8-fastbuild/bin/cpputil/libhdfs/_objs/hdfs/jni_helper.pic.o:(getGlobalJNIEnv)

ld.lld: error: undefined symbol: JNI_CreateJavaVM
>>> referenced by jni_helper.c
>>>               bazel-out/k8-fastbuild/bin/cpputil/libhdfs/_objs/hdfs/jni_helper.pic.o:(getGlobalJNIEnv)
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```

I also tried to put `@bazel_tools//tools/jdk:current_java_runtime` into `srcs`. But this would link against all dynamic libraries in JDK, which is not necessary. In particular, this would involve many X11 related libraries.

**Comment by fmeum** [comment]
This use case is covered by [rules_jni](https://github.com/fmeum/rules_jni), specifically the [libjvm_stub](https://github.com/fmeum/rules_jni/tree/main/tests/libjvm_stub) example. @hcoona Feel free to file an issue over at rules_jni if you run into issues using it.
