### ISSUE TITLE
Ability to clean stale configuration data from config/cquery without shutting all the way down

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/bazel#14725]
### Description of the problem / feature request:

Currently, running `bazel config` or `bazel cquery` may return stale data. In particular:
* https://docs.bazel.build/versions/main/cquery.html has a warning about `cquery` picking up results from past queries
* Running `bazel cquery ... && bazel config && bazel cquery --test_arg=foo && bazel config` - the second `bazel config` will return configurations from the first invocation which would not be returned if a `bazel shutdown` was performed between the runs.

As a workaround to this, I have scripts which run `bazel shutdown` between these invocations, but this is very expensive - repositories need re-fetching, and build files need re-loading from scratch.

It would be useful to either give these commands a `--clear_previous_state` flag, which drops a targeted subset of state to avoid this, or to have a top-level `bazel drop-stale-configs` or similar command.

I'd be happy to try out implementing either of these solutions, if someone can point me at roughly what the solution would look like.

/cc @gregestren

**Comment by gregestren** [comment]
Would https://github.com/bazelbuild/bazel/blob/33f7648fbaa875f73416be47f0b3c10ed93f30d6/src/main/java/com/google/devtools/build/lib/analysis/AnalysisOptions.java#L44 help?

As an experiment, what would doing a `cquery`, then doing an empty build with that flag, then another `cquery` or `bazel config` do?
