### ISSUE TITLE
Document linux-sandbox vs processwrapper-sandbox

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/bazel#14734]
There seems to be underdocumentation here.

For example, if I run Bazel in Linux, I get the linux-sandbox.

But if I run Bazel in Linux *in Docker*, I get the processwrapper-sandbox.

Why? Is linux-sandbox more strict? Would get more strict sandboxing by running builds outside of Docker containers?

**Comment by larsrc-google** [comment]
processwrapper-sandbox is generic, while linux-sandbox makes use of some Linux-specific things to be faster and/or more hermetic (can't say which off the top of my head). src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxedSpawnRunner.java will show you how the availability of linux-sandbox gets detected. 

Which of the two is more hermetic might not be an easy question to answer. It's entirely possible that they are more/less hermetic in different areas. I agree that there is a lack of documentation here.

**Comment by pauldraper** [comment]
Wow @philwo, that's really helpful!

Which of these (if any) use sandboxfs?

In particular I am working with Node.js builds have thousands of files, so anything that avoids the overhead of symlink creation sounds great.

**Comment by pauldraper** [comment]
Related: #13995

**Comment by larsrc-google** [comment]
I've added philwo@'s nice explanation to the sandboxing page.

**Comment by philwo** [comment]
Thank you Lars!
