### ISSUE TITLE
[5.1] Provide the exec CPU to repository rules

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#14747]
Forked from #14685

**Comment by cameron-martin** [comment]
I'm confused. https://github.com/bazelbuild/bazel/issues/14685#issuecomment-1032433790 says that `repository_ctx.os.name` and `repository_ctx.os.arch` provide information about the host platform. However, this task is closed which implies there is a way of getting information about the execution platform. How do you do this?

**Comment by fmeum** [comment]
You can't - I think this issue's title was populated incorrectly when it was forked from #14685.
