### ISSUE TITLE
Documentation issue: Provide Roadmap for 2022

### ISSUE THREAD

**Issue by beingminimal** [bazelbuild/bazel#14745]
Hello, 

Please update roadmap document and add roadmap for 2022.

Documentation URL: https://bazel.build/roadmap.html

**Comment by brentleyjones** [comment]
Btw, that link doesn't work for me, but https://bazel.build/roadmap.html does.

**Comment by codecycleteam** [comment]
@brentleyjones thanks for link error i have updated in main issue also. now can you please answer when it will goes live for public a roadmap for 2022?

**Comment by sventiffe** [comment]
Done.
