### ISSUE TITLE
Bazel test or clean fails with "Failed to initialize sandbox" when unix domain socket file is in sandbox tmp

### ISSUE THREAD

**Issue by adam-singer** [bazelbuild/bazel#14746]
### Description of the problem / feature request:

We are observing a problem when a previous test failure (early termination/exit) occurs and doesn't properly have a chance to clean up a unix domain socket created, following bazel commands that interact/invalidate the sandbox fails. We are using java and embedded mysql (java code that launches mysqld embedded for a test to execute against) that creates domain sockets in `java.io.tmpdir`, our setup uses the default `java.io.tmpdir` provided by bazel which is in `<sandbox path>/execroot/__main__/_tmp/`.  We know why the early termination happens and have a way to mitigate that, it is due to domain socket path lengths being longer then expected because our sandbox path is very deeply rooted. 

The pattern where we see this problem, first we run a test that exits without ability to delete the domain socket (in this case `mysql.sock`), then on follow up executions of `bazel clean --expunge` or `bazel test <target>`, invalidating or deleting of sandbox fails hard and bazel is unable to move forward.

```
bazel clean --expunge
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
ERROR: opendir (/<VERY_LONG_REDACTED_PATH>/.cache/bazel/_bazel-service/43fc79bd5b2f5921a45f3c115456767c/sandbox/linux-sandbox/3331/execroot/__main__/_tmp/8820f2ae0e02db6ddef3bcc3df0b4814/finagle-mysql/5-7-19/data/a5034d9a-c0b5-42af-b89a-311d85245fab/mysql.sock) (Not a directory)
``` 

```
bazel test <test_target>

INFO: Found 1 test target...
INFO: Deleting stale sandbox base /<VERY_LONG_REDACTED_PATH>/sandbox
ERROR: Failed to initialize sandbox: opendir (/<VERY_LONG_REDACTED_PATH>/sandbox/.cache/bazel/_bazel-service/43fc79bd5b2f5921a45f3c115456767c/sandbox/linux-sandbox/3331/execroot/__main__/_tmp/8820f2ae0e02db6ddef3bcc3df0b4814/finagle-mysql/5-7-19/data/a5034d9a-c0b5-42af-b89a-311d85245fab/mysql.sock) (Not a directory)
```

I have done some light digging tracing the error message `Failed to initialize sandbox` and where `opendir` code points are, but don't have enough context to fully understand why it has failed. The environment we notice this happening in and when/how it happens isn't easy to reproduce. A possible reproduction setup would be to isolate creation of a domain socket in a test and fail/exit hard after creation.

* [Failed to initialize sandbox: %s](https://github.com/bazelbuild/bazel/blob/02ad3e3bc6970db11fe80f966da5707a6c389fdd/src/main/java/com/google/devtools/build/lib/sandbox/SandboxModule.java#L154)
* [Deleting stale sandbox base](https://github.com/bazelbuild/bazel/blob/02ad3e3bc6970db11fe80f966da5707a6c389fdd/src/main/java/com/google/devtools/build/lib/sandbox/SandboxModule.java#L238)
* [static Dirents readdir(String path, ReadTypes readTypes)](https://github.com/bazelbuild/bazel/blob/02ad3e3bc6970db11fe80f966da5707a6c389fdd/src/main/java/com/google/devtools/build/lib/unix/NativePosixFiles.java#L280)
* [Collection<Dirent> readdir(Path path, boolean followSymlinks)](https://github.com/bazelbuild/bazel/blob/02ad3e3bc6970db11fe80f966da5707a6c389fdd/src/main/java/com/google/devtools/build/lib/unix/UnixFileSystem.java#L155)
* [static Dirent.Type convertToDirentType(Dirents.Type type)](https://github.com/bazelbuild/bazel/blob/02ad3e3bc6970db11fe80f966da5707a6c389fdd/src/main/java/com/google/devtools/build/lib/unix/UnixFileSystem.java#L139)
* [Dirents.Type.UNKNOWN](https://github.com/bazelbuild/bazel/blob/02ad3e3bc6970db11fe80f966da5707a6c389fdd/src/main/java/com/google/devtools/build/lib/unix/NativePosixFiles.java#L224)

I think something between those call paths/code is interpreting the `mysql.sock` file as a directory, possibly because the `Dirents` isn't aware of unix domain sockets.  

### Feature requests: what underlying problem are you trying to solve with this feature?

Trying to successfully remove the sandbox or invalidate it so that clean and test can execute if the previous temp folder in the existing sandboxes have stale domain sockets. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I don't have one on hand. A possible setup could be

1) Create a test that creates a unix domain socket in the bazel temp directory of a sandbox. 
2) Have the terminate early without cleaning up the domain socket. 
3) Run `bazel clean --expunge` or `bazel test` and see if it bulks at the leftover domain socket. 

### What operating system are you running Bazel on?

linux

### What's the output of `bazel info release`?

`release 4.2.1`

###  Have you found anything relevant by searching the web?

Not really, https://github.com/bazelbuild/bazel/issues/10363 seems like it could be related to bazel not knowing how to delete files. https://docs.bazel.build/versions/main/test-encyclopedia.html#test-interaction-with-the-filesystem points out the problem with domain socket path lengths, but nothing indicating that deleting them in sandboxes would be an issue.

**Comment by larsrc-google** [comment]
If you run this with `--verbose_failures`, do you get some stack traces? It's interesting that it tries to `opendir()` the socket, that hints at something misidentifying the file type.
