### ISSUE TITLE
Bug: Compilation fails when using iJars for scala_library

### ISSUE THREAD

**Issue by ckilian867** [bazelbuild/bazel#14759]
### Description of the problem / feature request:

We've found a problem when using iJars for some scenarios while using `scala_library` (we've only noticed it while using `scala_library`, but we can't confirm if its an issue only when using `scala_library`). When using `scalactic_2.11-3.0.5`, compilation will fail when iJars are enabled with the following stack trace:

```
Exception in thread "main" java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file org/scalactic/source/PositionMacro$
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
```

However, adding `build --nouse_ijars` to `.bazelrc` allows compilation to succeed. We can also build the exact same target using buck with iJar support enabled. When using the luyten decompiler, we can see the iJars bazel and buck produce are different. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Recreated in this repository: https://github.com/ckilian867/bazel-ijar-bug

This includes the jars needed to run the target in buck and bazel as well as the iJars produced by buck and bazel. 

### What operating system are you running Bazel on?

```
$  cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### What's the output of `bazel info release`?

```
$ bazel info release
INFO: Invocation ID: bcf63c63-8839-4284-95ba-afc659c46265
release 4.2.2
```

We were also able to recreate this on release 5.0.0.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
$ git remote get-url origin ; git rev-parse main ; git rev-parse HEAD
https://github.com/ckilian867/bazel-ijar-bug.git
e46bbb5b6b833aa3bb88be9b9896a81cac1d0be2
e46bbb5b6b833aa3bb88be9b9896a81cac1d0be2
```

###  Have you found anything relevant by searching the web?

[This post](https://www.giters.com/johnynek/bazel-deps/issues/269) ran into the same stack trace with a different version of the same library. 

### Any other information, logs, or outputs that you want to share?

Link to repro: https://github.com/ckilian867/bazel-ijar-bug

**Comment by cushon** [comment]
I think you need to use [`scala_import`](https://github.com/bazelbuild/rules_scala/blob/master/docs/scala_import.md#scala_import), see the comment in its docs about macros:

```diff
diff --git a/ijar-test/BUILD.bazel b/ijar-test/BUILD.bazel
index ad78b1f..f11659c 100644
--- a/ijar-test/BUILD.bazel
+++ b/ijar-test/BUILD.bazel
@@ -1,17 +1,18 @@
 load("@rules_java//java:defs.bzl", "java_import")
 load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library", "scala_test")
+load("@io_bazel_rules_scala//scala:scala_import.bzl", "scala_import")

-java_import(
+scala_import(
     name = "scalactic",
     jars = [
         "scala-library-2.11.12.jar",
         "scala-reflect-2.11.12.jar",
-        "scalactic_2.11-3.0.5.jar"
-    ]
+        "scalactic_2.11-3.0.5.jar",
+    ],
 )

 scala_library(
-   name = "ijartest",
-   srcs = ["Problem.scala"],
-   deps = [":scalactic"]
+    name = "ijartest",
+    srcs = ["Problem.scala"],
+    deps = [":scalactic"],
 )
```

```
$ bazel build --incompatible_java_common_parameters=false //ijar-test:ijartest
...
INFO: Build completed successfully
```

See also https://github.com/bazelbuild/bazel/issues/632
