### ISSUE TITLE
Documentation issue: Android fragment docs missing

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#14776]
There should be docs for the android fragment as there are for the other fragments

https://docs.bazel.build/versions/main/skylark/lib/java.html
https://docs.bazel.build/versions/main/skylark/lib/apple.html

It looks like this never existed even when fragments docs listed the available fragments https://docs.bazel.build/versions/3.2.0/skylark/lib/fragments.html

**Comment by keith** [comment]
Oof thanks, I missed that, given that it has been not documented, but still required in some cases, for 4 years, I wonder if we should just remove that now?

**Comment by ahumesky** [comment]
this is only intended for the starlark migration of the android rules, so we'll be deleting this at some point
