### ISSUE TITLE
Bazel linking wrong crtbegin variant.

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#1477]
It currently seems like you cannot use `linkopts=['-static']` for shared libraries.
I have the following define:

```
cc_binary(
  name = "libfoo.so",
  srcs = glob([
    "src/*.cpp",
  ]),
  linkopts=['-static'],
  linkshared = 1,
)
```

Finally `ld` complains:

```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/crtbeginT.o: relocation R_X86_64_32 against `__TMC_END__' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/crtbeginT.o: error adding symbols: Bad value
```

which is of course a valid complaint, since a shared library should be produced. So it should link against `crtbeginS.o`.

Since I do not see any argument in the commandline which would enforce `crtbeginT.o` it probably is necessary to replace it's linking when compiling with _gcc_.

**Comment by steven-johnson** [comment]
I'm experiencing this too -- not sure if I'm doing something else wrong or not. AFAICT 100% of my C code is being compilied with -fPIC.

**Comment by ulfjack** [comment]
Can you run with -s and provide the command line here?

**Comment by mhlopko** [comment]
Polite ping, is this still a problem?

**Comment by abergmeier-dsfishlabs** [comment]
@mhlopko So you want me to write a unit test for that!?

**Comment by mhlopko** [comment]
? I just pinged this issue since it appears the ball is on your side (as Ulf asked for the command line in December). And unsurprisingly, I don't want to waste time reproducing if this is not an issue anymore.

**Comment by abergmeier** [comment]
Have no use for this anymore. So will drop the ball.
