### ISSUE TITLE
Documentation Issue: android_common docs missing

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#14771]
0.17.0 seems to have been the last time docs on android_common were published https://docs.bazel.build/versions/0.17.2/skylark/lib/android_common.html

These would still be useful (at least until the android transition to starlark is done). These docs should be updated with the newest version of these APIs https://github.com/bazelbuild/bazel/blob/7a652714bcd231421b2f7dfe969c9e867e530014/src/main/java/com/google/devtools/build/lib/starlarkbuildapi/android/AndroidStarlarkCommonApi.java

**Comment by ahumesky** [comment]
we're replacing this with a starlark implementation in the near future (in particular, android_common.multi_cpu_configuration is the most important thing in there)
