### ISSUE TITLE
Keep repackaged 'allmodules' and 'minimized' JDKs up to date

### ISSUE THREAD

**Issue by cushon** [bazelbuild/bazel#14785]
[This is a continuation of discussion in internal review cl/427236699]

https://github.com/bazelbuild/bazel/commit/095f1e24ae3fa0860bdda5af7befe74c1123a078 consolidated the handling the versions of remote JDKs referenced in Bazel in `distdir_deps.bzl`, as a follow-up to https://github.com/bazelbuild/bazel/commit/b74111671713f132869b94cf3686cc427c67663a.

The only exception are the 'minimized' and 'allmodules' JDKs that are used for Bazel's embedded JDK:

* https://github.com/bazelbuild/bazel/blob/06a3d826bffd5c4708b0c2c8e562aaf49ed9025a/WORKSPACE#L135-L141
* https://github.com/bazelbuild/bazel/blob/06a3d826bffd5c4708b0c2c8e562aaf49ed9025a/WORKSPACE#L148-L153

Those JDKs are currently out of sync with the other versions.

They should be updated, and if possible the process for creating those derived JDKs should be improve to keep them in sync with the other versions instead of requiring manual updates. It would be nice if it was possible to create them at build-time instead.

The current process uses:

* https://buildkite.com/bazel-trusted/build-embedded-minimized-jdk
* https://github.com/bazelbuild/continuous-integration/blob/master/pipelines/build-embedded-minimized-jdk.yml
* *https://github.com/bazelbuild/bazel/blob/master/src/BUILD#L250

**Comment by meteorcloudy** [comment]
@meisterT Why did we use prebuilt 'allmodules' and 'minimized' JDKs? Was it for shorten the total build time of Bazel?

**Comment by cushon** [comment]
I think one of the reasons was that the repackaged JDK is significantly smaller, which makes the bazel installer smaller:

```
191M zulu11.37.17-ca-jdk11.0.6-linux_x64.tar.gz
 19M zulu11.37.17-ca-jdk11.0.6-linux_x64-minimal-b23d4e05466f2aa1fdcd72d3d3a8e962206b64bf-1581689068.tar.gz
 51M zulu11.37.17-ca-jdk11.0.6-linux_x64-linux_x64-allmodules-b23d4e05466f2aa1fdcd72d3d3a8e962206b64bf-1581689070.tar.gz
```

**Comment by meisterT** [comment]
There are two main reasons: it really takes quite a while (multiple minutes) so you don't want to do this on every build. Secondly, it is unfortunately non-deterministic. So it throw all caching out of the window.

**Comment by meteorcloudy** [comment]
Oh, I understand why we are embedding the repacked JDK, but I'm asking the same question as yours: why not "create them at build-time instead."

**Comment by meteorcloudy** [comment]
@meisterT I see..

**Comment by meteorcloudy** [comment]
> Secondly, it is unfortunately non-deterministic. So it throw all caching out of the window.

Do we know why it is non-deterministic?

**Comment by cushon** [comment]
How are the 'allmodels' JDKs used at this point? I remember some history from when the embedded JDK could be used by other tools that ran during the build, which might need modules Bazel doesn't. Is that still supported, or is everything else using local or remote JDKs instead of the embedded one?

**Comment by comius** [comment]
re allmodules JDK: I hope @comius knows the answer whether / how it is used today.

I don't. I would need to investigate.

**Comment by cushon** [comment]
I found some internal discussion about allmodules from 2019 that included

> with suffix allmodules: this is a full blown JDK with all the modules but doesn't include examples/documentation and so on --> this should be fine to use as --host_javabase

That matches my recollection that `--host_javabase` was a motivating use-case.

I'm not sure there's a reason to keep the allmodules JDK around at this point. The vanilla remote JDKs seem to be fine for the JDKs that are used in toolchains. I think it's worth considering dropping it, unless we discover it's still being used for something important.

> re non-determinism: when I last looked into it, the `jlink` tool internally used data structures to collect information and later process that information in a non-deterministic order (think `HashMap` vs `LinkedHashMap`).

If the non-determinism is the main blocker and you're interested in generating these during the build, I can try to help chase that down. It sounds like something we ought to be able to upstream a fix for.

**Comment by meisterT** [comment]
I did look into the time it takes to minimize the JDK and it it is less than 15s on my laptop so I guess if we can fix the non-determinism we can actually get rid of the cached version.

**Comment by meteorcloudy** [comment]
Fixing the non-determinism sounds great!

**Comment by meteorcloudy** [comment]
BTW, I'm wondering how does Bazel know the action is non-deterministic and then decide to throw away the cache?

**Comment by cushon** [comment]
Did you verify you're still seeing non-determinism from `jlink`? Any chance you'd be willing to put together a minimal repro for that?

**Comment by meisterT** [comment]
Yep, it's still there:

```
$ wget https://mirror.bazel.build/zulu/bin/zulu11.52.13-ca-jdk11.0.13-linux_x64.tar.gz
$ tar xf zulu11.52.13-ca-jdk11.0.13-linux_x64.tar.gz
$ cd zulu11.52.13-ca-jdk11.0.13-linux_x64
$ for i in 1 2 3 4 5; do
   ./bin/jlink --module-path ./jmods/ --add-modules "java.base,java.compiler,java.instrument,java.logging,java.management,java.naming,java.sql,java.xml,jdk.management,jdk.sctp,jdk.unsupported,jdk.crypto.ec" --vm=server --strip-debug --no-man-pages --output attempt${i}
   md5sum attempt${i}/lib/modules
done
```

```
4aaa27887a7b0a76e77995a60283307e  attempt1/lib/modules
164fb4bbccafa9cc4738c98e7373bac2  attempt2/lib/modules
9813c9c12cf47c4c462415ac37a087a1  attempt3/lib/modules
4aaa27887a7b0a76e77995a60283307e  attempt4/lib/modules
9813c9c12cf47c4c462415ac37a087a1  attempt5/lib/modules
```
