### ISSUE TITLE
Output of failing actions is not shown on Console on Windows

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#1478]
Repro is easy: write a genrule that fails but writes something to stdout before, build it, observe the lack of the message on the console.

I suspected my Windows JNI changes, but this is even the case with `--host_jvm_args=-Dio.bazel.EnableJni=0`, so I don't think it's that. @meteorcloudy suspects 
https://github.com/bazelbuild/bazel/commit/1e37a5375f918376c132fa537e25695f673f41b8

Maybe an interaction between @philwo 's and my changes to `Command.java`?

**Comment by lberki** [comment]
I'll take a look, at least as far as to figure out what the root cause is.

**Comment by meteorcloudy** [comment]
@dslomov is also taking a look

**Comment by lberki** [comment]
Great (I'm currently in a pit I dug myself into on a very different front)

**Comment by laszlocsomor** [comment]
This seems to be working now:
```
$ cat foo/BUILD
...
genrule(
    name = 'fail',
    outs = ['fail.out'],
    cmd = 'echo cica ; false',
)


$ bazel build foo:fail
...
ERROR: C:/work/bazel2/foo/BUILD:42:1: Executing genrule //foo:fail failed: bash.exe failed: error executing command C:/tools/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; echo cica ; false: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1
cica
Target //foo:fail failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.678s, Critical Path: 0.21s
FAILED: Build did NOT complete successfully
```

**Comment by laszlocsomor** [comment]
We even print "cica" to the console if the action succeeds, but we do so on Linux too.
