### ISSUE TITLE
Documentation issue: Workspace Rules ///How to add depandency package org.apache.felix.scr.annotations  in WORKSPACE file 

### ISSUE THREAD

**Issue by Echogsh** [bazelbuild/bazel#14792]
Documentation URL: https://docs.bazel.build/versions/main/be/workspace.html
How to add depandency package org.apache.felix.scr.annotations  in WORKSPACE file ,when I compile new build APP in ONOS project , got the follow error report

Testing started at 3:39 PM ...
/usr/bin/setsid --wait bazel test --tool_tag=ijwb:IDEA:community --curses=no --color=yes --progress_in_terminal_title=no --runs_per_test=1 --flaky_test_attempts=1 --build_event_binary_file=/tmp/intellij-bep-d711bfa6-bd31-4c2d-8e15-09602cd256b0 --nobuild_event_binary_file_path_conversion -- //apps/helloworld:all
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: apps/helloworld
Analyzing: 9 targets (1 packages loaded, 0 targets configured)
Analyzing: 9 targets (14 packages loaded, 15 targets configured)
Analyzing: 9 targets (48 packages loaded, 16 targets configured)
Analyzing: 9 targets (127 packages loaded, 1205 targets configured)
INFO: Analyzed 9 targets (136 packages loaded, 2553 targets configured).
INFO: Found 9 targets and 0 test targets...
[0 / 16] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[5 / 28] checking cached actions
[67 / 73] Generating javadocs jar for onos-apps-helloworld-javadoc; 0s linux-sandbox ... (2 actions running)
INFO: From Generating javadocs jar for onos-apps-helloworld-javadoc:
**apps/helloworld/src/main/java/me/ononproject/helloworld/AppComponent.java:19: error: package org.apache.felix.scr.annotations does not exist
import org.apache.felix.scr.annotations.Activate;**
                                       ^

**Comment by Wyverald** [comment]
This does not look like a Bazel issue; please ask the ONOS project for help.

**Comment by Echogsh** [comment]
> This does not look like a Bazel issue; please ask the ONOS project for help.

OK~thx
