### ISSUE TITLE
Packaging rules: Remove documentation for pkg_tar

### ISSUE THREAD

**Issue by steple** [bazelbuild/bazel#14797]
### Description of the problem / feature request:

Inaccurate documentation for deprecated rules.
These rules are deprecated and they should be removed soon.  Delete the documentation now to discourage use of these rules.  (Also the documentation is outdated.)

https://docs.bazel.build/versions/main/be/pkg.html

**Comment by aiuto** [comment]
You should use https://github.com/bazelbuild/rules_pkg for a replacement for pkg_tar.

**Comment by steple** [comment]
I know this package will be removed.  But when?   #8857 is referenced in the documentation as the reason why the documentation won't be updated, but that issue is closed.

If we offer documentation, I would argue that it should be accurate.  Anyone searching for documentation will likely find this page first.

**Comment by aiuto** [comment]
Now that I am thinking about it. The right thing to do is remove the documentation.  No one should be using this any more.

**Comment by steple** [comment]
I can follow up with a second change to remove it.

**Comment by steple** [comment]
Should the rules be removed as well?  Or is that handled under  #11183?

**Comment by aiuto** [comment]
11183 will slowly remove the rules until they are just the mini_tar.
https://github.com/bazelbuild/bazel/pull/14935  starts the ball rolling
by removing bazel's dependency on tools/build_defs/pkg/pkg.bzl

Now the only problem is some projects and users that have depending on that
rule from outside the bazel code base.
I'm trying to migrate them away before dropping anything.
