### ISSUE TITLE
Querying reverse dependencies  of a cc_proto_library returns wrong results

### ISSUE THREAD

**Issue by skeptic-monkey** [bazelbuild/bazel#14799]
### Description of the problem / feature request:

Since bazel 5.0.0, Querying reverse dependencies of a cc_proto_library returns wrong results, including lots of interal dependencies rather than reverse dependencies.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Using a minimal example available [here](https://github.com/skeptic-monkey/bazel_bug_rdeps), run the following commands:

```
➜  ~/Downloads/bazel-5.0.0-linux-x86_64 cquery "rdeps(//..., //src:myproto)"
INFO: Analyzed 4 targets (0 packages loaded, 0 targets configured).
INFO: Found 4 targets...
//src:myproto (28ff575)
//src:myproto_cc (28ff575)
@bazel_tools//tools/cpp:toolchain_type (28ff575)
@local_config_platform//:host (28ff575)
@com_google_protobuf//:cc_toolchain (28ff575)
@bazel_tools//tools/cpp:toolchain (28ff575)
@com_google_protobuf//:protoc (5601329)
//src:myproto.proto (null)
@local_config_cc//:cc-compiler-k8 (28ff575)
//src_native:myproto (28ff575)
//src_native:myproto.proto (null)
@bazel_tools//tools/cpp:compiler (28ff575)
@bazel_tools//tools/cpp:current_cc_toolchain (28ff575)
@com_github_protocolbuffers_protobuf//:protobuf (28ff575)
@zlib//:zlib (28ff575)
@com_github_protocolbuffers_protobuf//:protobuf_lite (28ff575)
@com_github_protocolbuffers_protobuf//:wrappers_proto (28ff575)
@com_github_protocolbuffers_protobuf//:any_proto (28ff575)
@com_github_protocolbuffers_protobuf//:duration_proto (28ff575)
@com_github_protocolbuffers_protobuf//:compiler_plugin_proto (28ff575)
@com_github_protocolbuffers_protobuf//:api_proto (28ff575)
@com_github_protocolbuffers_protobuf//:empty_proto (28ff575)
@com_github_protocolbuffers_protobuf//:field_mask_proto (28ff575)
@com_github_protocolbuffers_protobuf//:source_context_proto (28ff575)
@com_github_protocolbuffers_protobuf//:struct_proto (28ff575)
@com_github_protocolbuffers_protobuf//:descriptor_proto (28ff575)
@com_github_protocolbuffers_protobuf//:timestamp_proto (28ff575)
@com_github_protocolbuffers_protobuf//:type_proto (28ff575)
@com_github_protocolbuffers_protobuf//:cc_toolchain (28ff575)
//src_native:myproto_cc (28ff575)
@com_github_protocolbuffers_protobuf//:msvc (28ff575)
INFO: Elapsed time: 0.155s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions

```
When using bazel 4.2.2, the result is **correct**:

```
➜  ~/Downloads/bazel-4.2.2-linux-x86_64 cquery "rdeps(//..., //src:myproto)"
Starting local Bazel server and connecting to it...
INFO: Analyzed 4 targets (22 packages loaded, 467 targets configured).
INFO: Found 4 targets...
//src:myproto (96d6638)
//src:myproto_cc (96d6638)
INFO: Elapsed time: 5.401s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
```

### What operating system are you running Bazel on?

Ubuntu 20.04.1 LTS

### What's the output of `bazel info release`?

release 5.0.0

###  Have you found anything relevant by searching the web?

Found nothing so far.

### Any other information, logs, or outputs that you want to share?

I tried to use both native rules (cc_library, cc_proto_library) and the rules coming from `bazelbuild/rules_cc` and `bazelbuild/rules_proto/`

I also tried a pre release of the version 6.0.0, and the bug is still there.

But using bazel query instead of cquery works:
```
➜  ~/Downloads/bazel-5.0.0-linux-x86_64 query --universe_scope=//... "allrdeps(//src:myproto)"
//src:myproto
//src:myproto_cc
Loading: 0 packages loaded
```

**Comment by glukasiknuro** [comment]
We found the same issue for some other rules. Bisect on bazel code-base shown that it's because `--include_aspects` was flipped by default to true in https://github.com/bazelbuild/bazel/commit/44e46b836a580c2fe3e96f39f4c6e02516ca4a0b

Setting `--include_aspects=false` in the example provided in the bug description brings back old more sane behavior.

This looks like regression between 4.2 and 5.0, possibly this should be fixed in 5.1?

**Comment by joeleba** [comment]
I can confirm that for `aquery` and `cquery` we want to always include aspects by default.

cc @gregestren for `cquery`.

**Comment by glukasiknuro** [comment]
To add to previous comment - the rdeps right now displays platforms, but because a lot of targets are depended on those very large number of targets is returned in the response for real life code-base. It makes the the rdeps not usable with `--include_aspects=true`.

**Comment by gregestren** [comment]
This starts from Skyframe (Bazel's graph data structure and traversal engine). 

Specifically https://github.com/bazelbuild/bazel/blob/d533996b2c8eabaa8e796f3aad57bca13878f460/src/main/java/com/google/devtools/build/skyframe/DelegatingWalkableGraph.java#L132

This is where `cquery` and `aquery` ask Skyframe what the target's reverse deps are. When an aspect attaches to a target, that makes the aspect a reverse dep of that target. These builds (all builds?) implicitly attach a `ValidateTarget` aspect to all targets:

https://github.com/bazelbuild/bazel/blob/69be39985ec4f08d30b5db274d5a747ab6fb42c0/src/main/java/com/google/devtools/build/lib/rules/core/ValidateTarget.java#L37

I'm not familiar with `ValidateTarget`, but the point is it's an implicit rdep. Once that's identified, this triggers:

https://github.com/bazelbuild/bazel/blob/a01210f135c027b1815a0afc586f4dd33b141e42/src/main/java/com/google/devtools/build/lib/query2/PostAnalysisQueryEnvironment.java#L460

In particular `graph.getDirectDeps(key)`, where `key` is the aspect. That picks up the toolchain deps, etc.

`cquery` and `aquery` don't have the features to explicitly list aspects. Instead they collect the aspects (forward) deps so they're counted in a traditional `deps`-style query. Obviously this breaks down for `rdeps`.

One option is to fork `targetifyValues` so it doesn't alway follow aspects' forward deps.
Another option is to support aspects as first-class query output: 

https://github.com/bazelbuild/bazel/blob/a01210f135c027b1815a0afc586f4dd33b141e42/src/main/java/com/google/devtools/build/lib/query2/PostAnalysisQueryEnvironment.java#L415-L420

I think the second is the better answer. But it's a more involved project.

**Comment by skeptic-monkey** [comment]
any chance this issue will get any attention ? 
What would be the expected impact to keep the include_aspects=false on our project compare --include_aspects=true ?

**Comment by joeleba** [comment]
Hi. 

> What would be the expected impact to keep the include_aspects=false on our project compare --include_aspects=true ?

I can't think of any drawback with setting `--include_aspects=false` if it fits your use case. We don't plan to remove that flag.

**Comment by skeptic-monkey** [comment]
thanks, will proceed that way then.

**Comment by gregestren** [comment]
Re: better solution, see https://github.com/bazelbuild/bazel/issues/16310.  I'm going to try to do it but it'll certainly go through the rest of this year.

I agree that `--include_aspects=false` is likely safe for `rdeps` queries, and is probably a safe workaround for the time being.
