### ISSUE TITLE
feature request: method to list members of a package group

### ISSUE THREAD

**Issue by grimreaper** [bazelbuild/bazel#14791]
### Description of the problem / feature request:

there should be an operator to list the members of a [package_group](https://bazel.build/reference/be/functions#package_group) and/or `deps` should be expanded to list said members.

### Feature requests: what underlying problem are you trying to solve with this feature?

It is desirable to be able to understand what package groups exists and all metadata about this from the command line. It is also useful to use this data from e.g., genquery.

**Comment by wisechengyi** [comment]
From twitter's perspective, this would be useful as well. e.g. if a package group's definition is modified, we'd like to figure out what tests are affected that references it.

That said, the exactly UX probably needs to be worked out (what to and not to include, with various options)

**Comment by brandjon** [comment]
It sounds like you're talking about exposing this information to `bazel query`. The transitive contents of a `package_group` are formed during the analysis phase, not unlike a provider of a rule. I believe `query` does its own separate traversal of BUILD files to gather this information at loading time, so it may be possible to dump this information out.
