### ISSUE TITLE
Allow `--experimental_remote_cache_compression` to be used as `common` option

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#14802]
If you'd like to always enable `--experimental_remote_cache_compression` it's natural to put it in your `.bazelrc` as:

```
common --experimental_remote_cache_compression
```

But this ends up breaking commands that don't support this flag:

```
% bazel help
INFO: Reading rc options for 'help' from .../.bazelrc:
  Inherited 'common' options: --experimental_remote_cache_compression
ERROR: --experimental_remote_cache_compression :: Unrecognized option: --experimental_remote_cache_compression
```

It would be great if this flag was ignored instead as others such as `--experimental_downloader_config` are.

### What's the output of `bazel info release`?

release 5.0.0

**Comment by larsrc-google** [comment]
Does this flag have any effect outside of `build` commands (and their derivatives like `test` etc)? If not, put it in your `.bazelrc` as `build --experimental_remote_cache_compression`.

**Comment by keith** [comment]
It is mentioned in the docs that it's also compatible with `query`, although I'm not sure how much that matters, but I think practically for flags like this, there should be some consistent way users can say "apply this all the time!" without having to know exactly which commands it affects. I imagine most folks just throw everything under `build`, but that can be risky depending on the flag https://github.com/bazelbuild/bazel/issues/10961

**Comment by tjgq** [comment]
I believe this has been addressed by https://github.com/bazelbuild/bazel/pull/18130.
