### ISSUE TITLE
Python toolchain error PY2 vs PY3

### ISSUE THREAD

**Issue by codeman9** [bazelbuild/bazel#14814]
### Description of the problem / feature request:

The following error is being seen on commit d988e8b3bace4b2bb2ec4adc17d9bf7b4f49a907 and later but not on 60dedb7231 and earlier without any changes:

```
----------------
Note: The failure of target //issue:main (with exit code 1) may have been caused by the fact that it is running under Python 3 
instead of Python 2. Examine the error to determine if that appears to be the problem. Since this target is built in the host 
configuration, the only way to change its version is to set --host_force_python=PY2, which affects the entire build.

If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as 
PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for 
more information.
----------------
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See attached zip file for a minimal project that demonstrates the issue.
1) Build a Bazel binary from any commit after (including): d988e8b3bac
1a) Run command: `/path/to/bazel-dev-d988e8b3bac test -s //issue:issue_diff_test --nocache_test_results` and observe failing tests
1b) `cat` the `test.log` file to see the error written to the test file
2) Build a Bazel binary from any commit before (including): 60dedb7231
2a) Run command: `/path/to/bazel-dev-60dedb7231 test -s //issue:issue_diff_test --nocache_test_results` and observe passing tests
2b) `cat` the `test.log` file to see no error written to the test file

### What operating system are you running Bazel on?

macOS 12.2

### What's the output of `bazel info release`?

"development version"

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

I checked out the commits mentioned and then ran: `bazel build //src:bazel-dev` where `bazel info release` == "release 5.0.0"

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Failure case:
git@github.com:bazelbuild/bazel.git
5480f5be6b206b5921e1f129ec14265cc290b369
5480f5be6b206b5921e1f129ec14265cc290b369

Success case:
git@github.com:bazelbuild/bazel.git
5480f5be6b206b5921e1f129ec14265cc290b369
60dedb723131e2eb0070fc19bb218e0019351917

###  Have you found anything relevant by searching the web?

No. I `git bisect`ed to this commit: d988e8b3bace4b2bb2ec4adc17d9bf7b4f49a907 as being the first commit that introduced the failure.

### Any other information, logs, or outputs that you want to share?

[python-exec-host-issue.zip](https://github.com/bazelbuild/bazel/files/8063615/python-exec-host-issue.zip)

Adding:

```
    python_version = "PY3",
```

to the `py_binary` is successful as a workaround.

**Comment by keith** [comment]
cc @comius

**Comment by keith** [comment]
I'm surprised warnings like this can ever be hit when the workspace isn't even setup with python2:

```
py_runtime(
    name = "py3_runtime",
    interpreter_path = "/usr/bin/python3",
    python_version = "PY3",
    stub_shebang = "#!/usr/bin/python3",
)

py_runtime_pair(
    name = "py_runtime_pair",
    py2_runtime = None,
    py3_runtime = ":py3_runtime",
)

toolchain(
    name = "py_toolchain",
    toolchain = ":py_runtime_pair",
    toolchain_type = "@rules_python//python:toolchain_type",
)
```

**Comment by comius** [comment]
Python rules have a configuration transition.
Before https://github.com/bazelbuild/bazel/commit/d988e8b3bace4b2bb2ec4adc17d9bf7b4f49a907: First python transition happened and then host transition.
After https://github.com/bazelbuild/bazel/commit/d988e8b3bace4b2bb2ec4adc17d9bf7b4f49a907: First exec transition happens and then python transition.

I believe this order is better and more precise.

The detection apparently now works better, and your workaround is actually a fix for a latent bug.

**Comment by keith** [comment]
@comius if we only support a single python version, why do we need to specify a python version? We also only see this for these type of genrule + test targets, it's not a problem for just `bazel run`ning things
