### ISSUE TITLE
Bazel needlessly downloads un-select()'d external deps

### ISSUE THREAD

**Issue by jart** [bazelbuild/bazel#1482]
Assume I have the following:

```python
genrule(
    name = "clang_format_extract",
    srcs = select({
        ":darwin": ["@clang_macosx//file"],
        "//conditions:default": ["@clang_linux_x86_64//file"],
    }),
    # ...
)

config_setting(
    name = "darwin",
    values = {"cpu": "darwin"},
    visibility = ["//visibility:private"],
)
```

Bazel will download `@clang_macosx` even if I'm Linux, and vice versa. This forces Linux users to pay the price of an additional 139MB download + disk space that they don't need.

It would be nice if Bazel was smart enough to not take into consideration references to external dependencies, within `select()` clauses that aren't selected.

**Comment by kchodorow** [comment]
Unfortunately, the WORKSPACE file is evaluated before `select` can be used.  As a workaround, you could change it to @clang and then create a repository_rule that downloaded the right clang based on what uname returns.

**Comment by abergmeier** [comment]
@jart is creating a `clang_repository = repository_rule(` not an option for you? That's at least the way we usually handle this.
In `WORKSPACE` you would then only have a `clang_repository( name = "clang" )`.

**Comment by jart** [comment]
I can employ that workaround. Thank you.

**Comment by abergmeier** [comment]
@kchodorow Curious whether you would see using `repository_rule` as a workaround or whether this would be the intended approach.

**Comment by jart** [comment]
It's hard to say. I think the select solution is already ugly. I do however wish it did the right thing. I'm not sure how I'm going to use `uname` in the correct manner yet. It's probably going to be a lot more code for me to write the custom repo rule. But I don't care as long as it saves the user a gigantic download.

**Comment by kchodorow** [comment]
I see it as a workaround, but probably a long-term one.  I think we do need to "fix" select (or something like it) to be usable from the WORKSPACE file. Maybe as we make it easier to define a "platform" this will  work itself out.

**Comment by jart** [comment]
Having select() work from a workspace file would be awesome.

**Comment by kchodorow** [comment]
This has come up before, I filed #1485 as a general FR.
