### ISSUE TITLE
[5.0] execpath helper is unaware of experimental_no_product_name_out_symlink

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#14821]
Under `--experimental_no_product_name_out_symlink`
(which defaults to true in Bazel 5 https://github.com/bazelbuild/bazel/commit/06bd3e8c0cd390f077303be682e9dec7baf17af2 )
the `$(execpath)` make variable substitution (as well as `$(location)`) continue to print `bazel-out/...` paths even though no such path exists.

Repro with `BUILD`:

```
genrule(
    name = "write_foo",
    outs = ["foo"],
    cmd = "echo hello > $@",
)

genrule(
    name = "build",
    cmd = " && ".join([
        "echo $(execpath :foo) >> $@",
        "echo $(rootpath :foo) >> $@",
        "echo $(location :foo) >> $@",
    ]),
    srcs = [":foo"],
    outs = ["bar"],
)
```

Then run

```
$ bazel build --symlink_prefix=.bazel/ :build
$ cat .bazel/bin/bar
bazel-out/k8-fastbuild/bin/foo
./foo
bazel-out/k8-fastbuild/bin/foo
```

This is breaking for programs which rely on `$(execpath)` to point to the generated file.

**Comment by alexeagle** [comment]
What's more, that commit message says

> If this causes problems for you, set --experimental_no_product_name_out_symlink=false in your builds and file an issue.

But the flag was also **removed** in 5.0 by
https://github.com/bazelbuild/bazel/commit/b621b1b1866868a1dcb060fe7b6833df0c729761
so there is no way to restore the prior behavior.

I think it was a mistake to remove the flag in the same release that flipped the default? There seems to be no way to get this working again, aside from manually symlinking `bazel_out -> [symlink_prefix]-out`

**Comment by meisterT** [comment]
cc @justinhorvitz

**Comment by brentleyjones** [comment]
The path still _is_ `bazel-out/` under the execroot, even if no such symlink exists in the workspace.

**Comment by justinhorvitz** [comment]
To clarify what @brentleyjones said, the generated input is under `bazel-out` when it is staged in the sandbox in which the action runs. `$(location)` expands to the location relative to the working path of the action. @alexeagle are you using the result of `$(location)` outside the scope of the action?

**Comment by alexeagle** [comment]
Yes, the motivating use case here is where you build a program that you want to run from the workspace.

For example, 
https://github.com/bazelbuild/bazel-skylib/blob/main/docs/private/stardoc_with_diff_test.bzl#L83
creates a little `sh_binary` for the user to run which copies files out of the `bazel-out` folder. In that example the `bazel-bin` symlink  is hardcoded, since the .bazelrc in that repo has a `--symlink_prefix` flag. Using `$(execpath)` in that script makes it robust to whatever the `--symlink_prefix` is set to, however due to this issue such a program breaks in Bazel 5.0.

**Comment by brentleyjones** [comment]
I have use cases that would break if it respected `symlink_prefix` 🙃.

I don't think any build actions know about the workspace layout, only the execroot layout, which is hard-coded to `bazel-out` for bindir and `external` for external repositories. To reach into the workspace I've used `bazel run` and `$BUILD_WORKSPACE_DIRECTORY` in the script, but it wouldn't know what the value of `--symlink_prefix` is, true. Maybe that has to be exposed as a different value somewhere?

**Comment by haxorz** [comment]
@alexjski Can you please assess this?

**Comment by alexjski** [comment]
About the problem as initially stated--I want to say that is WAI. I think there is an important distinction between the layout within the exec root and the workspace, the convenience symlinks talk about the latter.

Please note the difference between:

```
bazel build //foo && bazel-bin/foo.out
```

and

```
bazel run //foo
```

I would recommend using the latter in your case. For scripts which are intended to be run from the workspace, I would advise the authors to use paths relative to `$0` instead of `${PWD}` which would solve this and other issues.

**Comment by alexeagle** [comment]
Thanks @alexjski , yes that's the bazel-idiomatic resolution (expand the bazel "boundary" to include executing the program).

There are cases where that's hard though. A simple one is I want to `bazel build` some files and then upload them to AWS S3. AWS already distributes a CLI that most users are trained on. Should they really be forced to figure out how to host that tool under Bazel before they can upload their app?

**Comment by alexjski** [comment]
> A simple one is I want to bazel build some files and then upload them to AWS S3. AWS already distributes a CLI that most users are trained on. Should they really be forced to figure out how to host that tool under Bazel before they can upload their app?

Can you share more about the layout in this case? I strongly suspect a simple wrapper could be built which would cd to proper directory, derived from `$0` which you could `blaze run`. If you could share more details, I would be able to provide more concrete guidelines.

**Comment by alexeagle** [comment]
Sorry, I conflated two things on the thread. The original problem statement was both wrong (these make variable expansions are intended for the execroot, not the repository root) and as you point out, someone who understands Bazel can always write their tooling differently so that the path of the generated script is used, rather than how the bazel-skylib example I linked to does a `cd ${BUILD_WORKSPACE_DIRECTORY}` and thus exits the directory where the outputs would have been a relative lookup.

So, I'm okay with closing this issue, especially as it only manifests when using `--symlink_prefix`. (Though perhaps there's some value in assessing whether this flag is truly "experimental" as it's now on-by-default.)

However this related follow-up discussion is more about a naive user and their expectations. It feels very strange to them that a build system would perform a build and then provide them no way to get the results, without diving deeper into the build system to write additional tooling that executes under `bazel run`. In fact that's why the `cd ${BUILD_WORKSPACE_DIRECTORY}` pattern made sense, as it emulates the same commands a user would perform manually after running `bazel build` and then trying to locate the results to pass to another command they run.

So, I fear we are making Bazel even harder to use.

**Comment by alexjski** [comment]
> However this related follow-up discussion is more about a naive user and their expectations. It feels very strange to them that a build system would perform a build and then provide them no way to get the results, without diving deeper into the build system to write additional tooling that executes under bazel run.

Sorry for nitpicking, but I want to say that the outputs are available under given symlinks. It's just that if the output expects to be ran from the same structure as exec root and `--symlink_prefix` is specified, then it will not work from the workspace. One thing a user could do such case is to run `cd $(bazel info execution_root)` instead of `cd ${BUILD_WORKSPACE_DIRECTORY}`.

> So, I fear we are making Bazel even harder to use.

That is certainly true that the more knobs we have, the more complex potential usage can get. My recommendation would be not to customize `--symlink_prefix` if having the same layout in the workspace and in the exec root is desirable.
