### ISSUE TITLE
BazelShutdownLoggerModule deactivates all Bazel logs

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#1483]
The first thing [`BazelMain.java`](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/BazelMain.java#L42) does on startup is to shutdown all JDK logs.

[`BazelShutdownLoggerModule.java`](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/BazelShutdownLoggerModule.java)

```java
/**
 * Shutdown log output when Bazel runs in batch mode
 */
public class BazelShutdownLoggerModule extends BlazeModule {
  private Logger globalLogger;

  @Override
  public void blazeStartup(OptionsProvider startupOptions, BlazeVersionInfo versionInfo,
      UUID instanceId, BlazeDirectories directories, Clock clock) {
    LogManager.getLogManager().reset();
    globalLogger = Logger.getGlobal();
    globalLogger.setLevel(java.util.logging.Level.OFF);
  }
}
```

The comment says, "Shutdown log output when Bazel runs in batch mode" but in fact it shuts down all log output all the time.

This is pretty baffling in the context of [`BlazeStartupOptions::AddJVMArguments`](https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/blaze_startup_options.cc#L158) whose sole purpose appears to be to configure a JDK file logger at the INFO level.

I wasted a lot of time trying to tweak the settings in `BlazeStartupOptions::AddJVMArguments` and with `--host_jvm_args` to try to get Bazel to log anything to its log file. In the end, getting any actual logs required commenting out this module completely.

Is it really supposed to deactivate all Bazel logs, or is it only supposed to do it in certain modes? (What does batch mode have to do with logging?)

**Comment by ulfjack** [comment]
Yeah, it's weird. In the beginning, we had a bug that bazel was spewing log output to stderr when passing --batch as a startup option, i.e., in 'batch mode'. The module creation predates the AddJvmArguments - maybe someone forgot to remove the module when fixing the startup arguments?

If everything works without the module now, then we should probably drop it.

**Comment by dfabulich** [comment]
Did a batch build with the module removed and stderr looks fine. https://bazel-review.googlesource.com/3990

**Comment by ulfjack** [comment]
Did you try both with --batch and without? We may not have full test
coverage on github for that (sorry).

**Comment by dfabulich** [comment]
Yes, it looked fine both ways.

**Comment by ulfjack** [comment]
I earlier tried to run it against our internal tests, but didn't manage to
import the change. I'll have to do it manually. I'll get back to you on
Monday; it's getting late here (feel free to ping me if I don't).

**Comment by dfabulich** [comment]
@ulfjack ping!

**Comment by ulfjack** [comment]
I didn't forget it. I tried to run the tests on Monday, but they were broken for unrelated reasons. Then again yesterday, but I had to leave before it was done. Now I got the results, and it's looking good.

Unfortunately, I didn't manage to import the change. I'll need to manually fix it up and then get it submitted.

**Comment by dfabulich** [comment]
My PR merged; this is now fixed.
