### ISSUE TITLE
Running Bazel on a Go project fails on Windows with error: 'doskey' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Danaozhong** [bazelbuild/bazel#14838]
### Description of the problem / feature request:

Running Bazel for projects using Go on Windows fails, with the error message:
`'doskey' is not recognized as an internal or external command, operable program or batch file.`

Full log is attached.
Running the same project using Bazel using WSL2 works. I therefore suspect some strange issue with Windows, and possible some name aliases.

I would need support on how to debug this issue, and see what is the root cause.

I tried two different versions of Bazel (5.0.0, and 6.0.0)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Clone git@github.com:tweag/tendermint-bazel.git (just some random Go project using Bazel).
2. Open Powershell and run `bazel build //...`
3. expected result: The build is successful.
4. actual result: The build fails, with the error message `"doskey" is not recognized as an internal or external command.`
[bazel_error_log.txt](https://github.com/bazelbuild/bazel/files/8080698/bazel_error_log.txt)

```
SUBCOMMAND: # @go_sdk//:builder [action 'GoToolchainBinaryCompile external/go_sdk/builder.exe.a [for tool]', configuration: dff40dd41fd8cedbdb78e34aebdb66d236f9a8cd5b3e9790a925d399398cd7cc, execution platform: @local_config_platform//:host]
cd /d C:/users/10990/_bazel_10990/eunmr6e2/execroot/com_github_tendermint_tendermint
  SET GOROOT=external/go_sdk
  bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\external\go_sdk\builder.exe.bat
# Configuration: dff40dd41fd8cedbdb78e34aebdb66d236f9a8cd5b3e9790a925d399398cd7cc
# Execution platform: @local_config_platform//:host
ERROR: C:/users/10990/_bazel_10990/eunmr6e2/external/go_sdk/BUILD.bazel:43:15: GoToolchainBinaryCompile external/go_sdk/builder.exe.a [for tool] failed: (Exit 1): builder.exe.bat failed: error executing command (from target @go_sdk//:builder) bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\external\go_sdk\builder.exe.bat
'doskey' is not recognized as an internal or external command,
operable program or batch file.
INFO: Elapsed time: 6.184s, Critical Path: 1.80s
INFO: 2 processes: 2 internal.
```

### What operating system are you running Bazel on?

Windows 10
```
WindowsBuildLabEx                                       : 19041.1.amd64fre.vb_release.191206-1406
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : Enterprise
WindowsProductName                                      : Windows 10 Enterprise

```
### What's the output of `bazel info release`?

`release 6.0.0-pre.20220201.3`

###  Have you found anything relevant by searching the web?

Seems no one else had this issue so far.

### Any other information, logs, or outputs that you want to share?

It is unlikely that this is actual an issue with Bazel itself, rather some environment issue. Nevertheless, debugging this issue might requires more insight in how Bazel is actually working, so some support would be great. Thank you.

**Comment by aiuto** [comment]
Do all projects using Go fail? It seems like this is a bug for rules_go, rather than bazel.

**Comment by sgowroji** [comment]
Hello @Danaozhong, Could you please reply on the above [comment](https://github.com/bazelbuild/bazel/issues/14838#issuecomment-1051411386).It will be closed very soon, if no further activity occurs on this issue. Thank you.

**Comment by Danaozhong** [comment]
Yes, all Go projects failed. I never managed to identify what was the root cause. I reinstalled Windows and Bazel and it worked. From my point of view, you can close this problem report. Thank you!

**Comment by ckolli5** [comment]
@Danaozhong Closing this issue with reference to the above [comment](https://github.com/bazelbuild/bazel/issues/14838#issuecomment-1143219176). Thanks!
