### ISSUE TITLE
undefined: gomock.AssignableToTypeOf while using github third party package "github.com/golang/mock" in Golang Project using bazel as a Build tool

### ISSUE THREAD

**Issue by divesh979** [bazelbuild/bazel#14846]
Information About how project is setup: My Project is Built using Bazel tool, My task is to update all Third Party Dependencies of Golang as well as to update bazel,Update bazel rules,Update gazelle and docker Rules, Update Go all with Latest Versions in WORKSPACE file.

Issue: The issue is undefined: gomock.AssignableToTypeOf Occuring While using function gomock.AssignableToTypeOf of package "github.com/golang/mock"

No issues in Code while Using Below Versions: Bazel Version: 3.7.1 Bazel Rules Version: v0.27.0 bazel_gazelle Version: v0.23.0 Go Version: 1.16 Docker Rules Version: 0.14.4

Issues There is No code changes Done Just the Update of Versions in WORKSPACE file of Project and issue undefined: gomock.AssignableToTypeOf starts appearing Bazel Version: 4.2.1 Bazel Rules Version: v0.30.0 bazel_gazelle Version: v0.24.0 Go Version: 1.17.6 Docker Rules Version: 0.23.0

Even When i have tried using latest Version(v1.6.0) of Package github.com/golang/mock as well as current version which is already used in Code and that is also not working when we upgrade all these above packages As mentioned here https://github.com/bazelbuild/rules_go/releases i have Upgraded to latest Version (org_golang_x_tools,org_golang_x_sys,org_golang_google_genproto,go_googleapis) for these packages in WORKSPACE even then I am facing same issue. Can Anyone Help or Guide in this case?

**Comment by aiuto** [comment]
I think you should ask this question in https://github.com/bazelbuild/rules_go

**Comment by ckolli5** [comment]
Hey @divesh979, I can see that you have already created an [issue](https://github.com/bazelbuild/rules_go/issues/3069) in [rules_go](https://github.com/bazelbuild/rules_go) repository. So, are we good to close this issue? Thanks!

**Comment by sgowroji** [comment]
As there is no significant update on this issue from long time, We are closing this issue now. Please feel free to reopen if you are still looking resolution for the above query. Thanks!
