### ISSUE TITLE
Symlinks from ctx.runfiles are not created on Windows

### ISSUE THREAD

**Issue by alexsharoff** [bazelbuild/bazel#14845]
### Description of the problem / feature request:

Symlinks specified in `symlinks` or `root_symlinks` parameters of `ctx.runfiles` are not created when calling `bazel run`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

BUILD:
```bazel
load('//:rules.bzl', 'test_data_symlink')
test_data_symlink(
    name = 'symlink',
    target = 'test/data.txt',
    path = 'test_data.txt',
)
cc_binary(
  name = 'symlink_test',
  srcs = ['main.cpp'],
  data = [':symlink'],
)
```

rules.bzl:
```bazel
def test_data_symlink_impl(ctx):
  return struct(
    runfiles = ctx.runfiles(
      symlinks = {
        ctx.attr.path: ctx.file.target,
      },
    )
  )
test_data_symlink = rule(
  implementation = test_data_symlink_impl,
  attrs = {
    'target': attr.label(allow_single_file = True, mandatory = True),
    'path': attr.string(mandatory = True),
  },
)
```

main.cpp:
```cpp
#include <fstream>
#include <iostream>
int main() {
    std::ifstream f("test_data.txt");
    if (!f.is_open()) {
        std::cerr << "Failed to open test_data.txt" << std::endl;
        return 1;
    }
    return 0;
}
```

test/data.txt: should exist

Explanation:
- `ctx.runfiles` creates a `test_data.txt` symlink pointing to `test/data.txt`
- `symlink_test` executable depends on `test_data.txt` during runtime
- to test, run `bazel run symlink_test`. It should not print `Failed to open test_data.txt`

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

release 5.0.0

###  Have you found anything relevant by searching the web?

This explains symlink creation: https://docs.bazel.build/versions/main/skylark/rules.html#runfiles-symlinks. If I understand it correctly, it should work as I described above.

**Comment by meteorcloudy** [comment]
I think this belongs to the Build API team, @comius can you take a look?

**Comment by brandjon** [comment]
By default, symlinks aren't created under windows. See [here](https://bazel.build/docs/windows#symlink) for enabling them (thanks to tetromino@ for the link).

When symlinks are disabled, you can instead access runfiles using the appropriate library for the language underneath `@bazel_tools`, e.g. `@bazel_tools//tools/cpp/runfiles:runfiles`. This allows for indirecting through a manifest file. Not sure if that works for runfiles that are themselves symlinks.

**Comment by brandjon** [comment]
(Leaving open pending verification that what I described works.)

**Comment by brandjon** [comment]
> That manifest is only exposed to bz run, correct? How does one know where to look for a host compiled binary that needs data?

The runfiles library will locate the runfiles (either symlink-based or manifest-based) using environment vars that are passed to the process by a launcher. That applies when the binary being run is a tool that's executing as part of the build, but I believe it also applies in the case of an executable target invoked by `bazel run`.

> Related, Swift isn't listed there, and rules_swift doesn't have a similar library afaik.

I don't have an answer for languages that don't have a runfiles library -- I imagine that's up to the owners of the rules for those languages, if windows (or at least a symlink-less environment) is supported.

**Comment by brentleyjones** [comment]
> The runfiles library will locate the runfiles (either symlink-based or manifest-based) using environment vars that are passed to the process by a launcher. That applies when the binary being run is a tool that's executing as part of the build, but I believe it also applies in the case of an executable target invoked by bazel run.

At least in my experience with rules_swift (and it might be doing something wrong?) the environment variables aren't set and there is no manifest symlinked in, when the tool is run as part of a build versus `bazel run`.

**Comment by anguslees** [comment]
Question from ignorance: Can we just create full file copies on Windows, when symlinks are disabled - rather than do nothing and impose a different calling convention on everyone?
