### ISSUE TITLE
Could not release for iOS

### ISSUE THREAD

**Issue by tanuuuu** [bazelbuild/bazel#14841]
I have building the Facemeshgpu project in XCode, I tried to archive from (Product -> Archive).
The building and the archiving processes are completing successfully (as shown in the attached snapshots). However, on opening the archive, xcode is showing 'The archive contains nothing that can be signed
<img width="922" alt="Screenshot 2022-02-15 at 11 48 06 AM" src="https://user-images.githubusercontent.com/29446590/154302055-9ec2b390-2c48-48aa-a7c2-58b92849d4f9.png">

**Comment by aiuto** [comment]
Can you provide a reproduction. This report does not enough information to work from.

**Comment by sgowroji** [comment]
Hello @tanuuuu, Am sure this is not a bazel issue and I would recommend you to try the workarounds mentioned [here](https://stackoverflow.com/questions/44966406/archive-export-error-the-archive-contains-nothing-that-can-be-signed). And please reach us back, if you have any specific query on the same with complete details and error logs . Thanks!
