### ISSUE TITLE
404 at https://bazel.build/bazel-release.pub.gpg

### ISSUE THREAD

**Issue by nairb774** [bazelbuild/bazel#14858]
### Description of the problem / feature request:

https://docs.bazel.build/versions/main/install-ubuntu.html references a GPG key at https://bazel.build/bazel-release.pub.gpg which seems to have gone missing.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Follow install instructions at https://docs.bazel.build/versions/main/install-ubuntu.html

### What operating system are you running Bazel on?

Specifically `cimg/base:2022.02` from CircleCI - an Ubuntu/Debian based image. However, browsing to https://bazel.build/bazel-release.pub.gpg generates a 404 as well.

### What's the output of `bazel info release`?

Not relevant - pre-install.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Not relevant - pre-install.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Not relevant - pre-install.

###  Have you found anything relevant by searching the web?

No issues seem to be filed yet.

### Any other information, logs, or outputs that you want to share?

N/A

**Comment by nairb774** [comment]
Seems to be back to working. Was this fixed, or is the result flaky?

**Comment by iangudger** [comment]
Still broken for me.

**Comment by tkbrex** [comment]
still broken +1

**Comment by jshamble** [comment]
I'm still getting this error.

**Comment by sbc100** [comment]
This is currently blocking releases of emsdk: https://github.com/emscripten-core/emsdk/pull/990

**Comment by fweikert** [comment]
We're rolling out a fix, apologies for the breakage.

**Comment by jin** [comment]
https://bazel.build/bazel_release.pub.gpg has been restored.

**Comment by eric-google** [comment]
It looks like the original url was https://bazel.build/bazel-release.pub.gpg but the url listed in the fix is https://bazel.build/bazel_release.pub.gpg (underscore) - is that intentional?

**Comment by jin** [comment]
Definitely not intentional (and quite embarassing) - will roll out another fix.

**Comment by jin** [comment]
https://bazel.build/bazel-release.pub.gpg is fixed now.
