### ISSUE TITLE
bazel coverage failed with "collect_coverage.sh: line 165: 49163 Segmentation fault      (core dumped) "

### ISSUE THREAD

**Issue by yangelaboy** [bazelbuild/bazel#14850]
when runing bazel coverage, all tests passed, but core happens in file external/bazel_tools/tools/test/collect_coverage.sh: line 165: 49163

![image](https://user-images.githubusercontent.com/16263873/154492505-139f3059-057a-4f2e-9f9f-391e858612d0.png)

**Comment by keith** [comment]
This is indicating your test binary crashed, on the line where the runner invoked it

**Comment by ckolli5** [comment]
Hey @yangelaboy, did you get any chance to check the above [comment](https://github.com/bazelbuild/bazel/issues/14850#issuecomment-1043172061). Let us know if it is already resolved. Thanks.

**Comment by sgowroji** [comment]
As there is no significant update on this issue for long time, We are closing this issue now. Please feel free to reopen if you are still looking resolution for the above query. Thanks!
