### ISSUE TITLE
Bazel 5: no matching toolchains found for types @bazel_tools//tools/jdk:runtime_toolchain_type

### ISSUE THREAD

**Issue by devhanos5** [bazelbuild/bazel#14864]
### Description of the problem / feature request:
We override the `remotejdk11_macos` with on-prem URLs. The same works on Bazel 4 but errors out with the following message on Bazel 5. This is not an issue with Bazel but I would appreciate if someone can help with what extra steps are needed to make it work. 
```
While resolving toolchains for target @bazel_tools//tools/jdk:remote_jdk11: no matching toolchains found for types @bazel_tools//tools/jdk:runtime_toolchain_type
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

[repro.zip
](https://drive.google.com/file/d/1kzDK5eOsAlmvZCtbjaMhn52WrdO2ZMYG/view?usp=sharing)

repro directory
   - bazel4.2.2
   - bazel5

Steps:

1. Go to repro/bazel4.2.2. Execute `./bazel-4.2.2-darwin-x86_64 build :ExampleLib`. The build will be successful.
2. Go to repro/bazel5. Execute `./bazel-5.0.0-darwin-x86_64 build :ExampleLib`. The build will fail with the following error:
```
ERROR: /private/var/tmp/_bazel_devh/c6ae263ac387a0f59fbd632245d48237/external/bazel_tools/tools/jdk/BUILD:474:27: While resolving toolchains for target @bazel_tools//tools/jdk:remote_jdk11: no matching toolchains found for types @bazel_tools//tools/jdk:runtime_toolchain_type
ERROR: Analysis of target '//:ExampleLib' failed; build aborted: 
INFO: Elapsed time: 4.268s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (34 packages loaded, 313 targets configured)
    Fetching @local_config_cc; Running xcode-locator

```

### What operating system are you running Bazel on?

OS: macOS Big Sur 11.6
Bazel 4.2.2, 5.0.0

### What's the output of `bazel info release`?

`release 5.0.0`

### Any other information, logs, or outputs that you want to share?
NA

**Comment by limdor** [comment]
Maybe related to https://github.com/bazelbuild/bazel/issues/7849?

**Comment by comius** [comment]
The WORKSPACE files have changed because of Java toolchainisation. See https://github.com/bazelbuild/bazel/blob/5.0.0/src/main/java/com/google/devtools/build/lib/bazel/rules/java/jdk.WORKSPACE.tmpl#L87-L100

Nonetheless the same override trick should work with some changes:

```
load("@bazel_tools//tools/jdk:remote_java_repository.bzl", "remote_java_repository")

remote_java_repository(
  name = "remotejdk11_macos",
  sha256 = "e1fe56769f32e2aaac95e0a8f86b5a323da5af3a3b4bba73f3086391a6cc056f",
  strip_prefix = "zulu11.50.19-ca-jdk11.0.12-macosx_x64",
  urls = [
    "https://mirror.bazel.build/openjdk/azul-zulu11.37.17-ca-jdk11.0.6/zulu11.37.17-ca-jdk11.0.6-macosx_x64.tar.gz",
    ],
   target_compatible_with = [
        "@platforms//os:macos",
        "@platforms//cpu:x86_64",
    ],
    version = "11",
)
```
