### ISSUE TITLE
--null option for query

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#1486]
In order for other programs to be able to easier process the Bazel query output it would be great if Bazel had an option to replace the line break with `\0`. E.g. for grep it is `--null`.

**Comment by abergmeier** [comment]
Giving this a shot. Any preferences?

**Comment by dslomov** [comment]
What is the motivation for adding this? Why line breaks are not good enough? (I do not think Bazel supports line breaks in file names very well anyway)

**Comment by abergmeier-dsfishlabs** [comment]
If you e.g. want to

1. write the output of query to a file
2. mmap that file
3. use the path strings found in that file directly (without having to copy or modify memory)

it is way easier/faster to do this when the separate paths are already `\0` terminated.
A lot of BSD + GNU utils have options to null terminate output.

Implementation wise I implemented it "inline", without an additional indirection layer (e.g. converting `\n` to `\0`) so the VM might have an easier time to optimize it and not degrade performance. Also while Bazel may not support line breaks, at least this patch is pretty agnostic.

**Comment by damienmg** [comment]
That's fixed IIUC

**Comment by abergmeier-dsfishlabs** [comment]
Indeed.
