### ISSUE TITLE
Documentation: Duplicate entries for repository_rule

### ISSUE THREAD

**Issue by cpsauer** [bazelbuild/bazel#14879]
Hey wonderful Bazel folks,

Friendly heads that something's up with the documentation of `repository_rule` in globals. 

It's listed twice, and unlike all the other entries, it's parameters are listed as part of the method name in the table of contents.

This is true in both the [old](https://docs.bazel.build/versions/main/skylark/lib/globals.html#repository_rule(implementation,%20attrs,%20local,%20environ,%20configure,%20remotable,%20doc)) and [new](https://bazel.build/rules/lib/globals#repository_rule(implementation,%20attrs,%20local,%20environ,%20configure,%20remotable,%20doc)) docs.

The problem seems to have happened first in 5.0--docs before then don't show the issue.

Cheers!
Chris,
(ex-Googler)

**Comment by Wyverald** [comment]
Dupe of
