### ISSUE TITLE
Enable adding custom fragments

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#1487]
While `ctx.fragments.[fragment name]` is nice it currently seems like we cannot use it for custom tools.
It would be great if it would be able to add custom fragments either with the .rc mechanism or from a `repository_rule`.
Would imaging that `ctx.fragments[<repo_name>//<fragment name>]` would be a good way of accessing them.

**Comment by dslomov** [comment]
Yes, agreed. This is something we plan to have at some point, but it is not
around the corner.

Dmitry

On Fri, Jul 8, 2016 at 11:39 AM, Andreas Bergmeier <notifications@github.com
> wrote:

> While ctx.fragments.[fragment name] is nice it currently seems like we
> cannot use it for custom tools.
> It would be great if it would be able to add custom fragments either with
> the .rc mechanism or from a repository_rule.
> Would imaging that ctx.fragments[<repo_name>//<fragment name>] would be a
> good way of accessing them.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bazelbuild/bazel/issues/1487>, or mute the thread
> <https://github.com/notifications/unsubscribe/AExrXyb-eX3uhAoA0K024qQ4ShjKZJ4zks5qThrsgaJpZM4JH3_F>
> .
>



-- 
Google Germany GmbH
*Erika-Mann-Straße 33, 80636 München, Germany*

**Comment by gregestren** [comment]
Custom fragments can now be modeled by [Starlark configuration](https://docs.bazel.build/versions/4.0.0/skylark/config.html) (see the notes on "fragments" in the doc).

In other words, Starlark is now powerful enough that anyone can model a fragment without needing special Bazel support. This can work with both native and Starlark flags. The details would depend on exactly what you mean by custom tools.
