### ISSUE TITLE
files/runfiles (or any other 'reserved' name provider) mandatory provider never resolves

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#1490]
Specifying that a provider named one of a list of undocumented reserved names (at least "files", "runfiles",  be mandatory always fails to resolve:

mandatory_provider_rule.bzl:

```
def _mandatory_provider_impl(ctx):
    return struct(files=set(ctx.files.deps))

mandatory_provider_rule = rule(
  _mandatory_provider_impl,
  attrs={
      "deps": attr.label_list(providers=["files"])
  }
)
```

BUILD:

```
load(":mandatory_provider_rule.bzl", "mandatory_provider_rule")

mandatory_provider_rule(name="a")
mandatory_provider_rule(name="b", deps=[":a"])
```

Obviously runfiles, files, instrumented_files, and some other overloaded reserved-name provider are being treated differently here.  Using a value of a type that is anything other than each keyword expects, e.g. int for "files", results in a differentiated error related to type mismatch, implying implicit typing/usage/interpretation.  I would expect that there are several possible resolutions here:
1. Pass through reserved-name providers to be observable by dependent targets in RuleContext::validateRuleDependency
2. Document the reserved names, and fail on providers=[...] specification containing reserved names that cannot not be resolved with a helpful error message
3. Use a different mechanism for transferring these reserved-name providers than the return of a struct impl - something mutable/assignable in ctx.

**Comment by kchodorow** [comment]
@katre, could you take a look?

**Comment by katre** [comment]
Will investigate.

**Comment by katre** [comment]
Looks like the issue is in https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/SkylarkRuleConfiguredTargetBuilder.java#L234

It's setting runfiles but ignoring the actual value from the rule impl return struct.

**Comment by abergmeier-dsfishlabs** [comment]
Can you please remove the runfile example from the cookbook!

**Comment by werkt** [comment]
I want to make sure that this is not treated as being limited to runfiles - any of the reserved words in that if chain will fail to satisfy provider requirements.
