### ISSUE TITLE
Using bazelisk on Raspberry Pi 3B

### ISSUE THREAD

**Issue by goulaoalex** [bazelbuild/bazel#14918]
I'm trying to install bazel on my raspberry pi 3b (using debian bullseye). After installing bazelisk and trying to run it on the command line I get the following error:

"2022/02/28 22:54:23 could not download Bazel: could not determine path segment to use for Bazel binary: unsupported machine architecture "arm", must be arm64 or x86_64"

Does anyone know how to fix this or why does this happen?

**Comment by kouckma** [comment]
Have you solved this issue? I run into the same problem.
