### ISSUE TITLE
Documentation: search returns results from old site

### ISSUE THREAD

**Issue by mattem** [bazelbuild/bazel#14916]
When using the search on the new documentation site, it returns results from the versioned URLs, which you then have to click the deprecation notice to get back to the new documentation URL.

eg:
Search for `dict`: https://bazel.build/s/results?q=dict

Take the first result: https://www.google.com/url?client=internal-element-cse&cx=a22348c75f26d1e6e&q=https://docs.bazel.build/versions/main/skylark/lib/dict.html&sa=U&ved=2ahUKEwjktJem_Z_2AhVBj4kEHRqDBCoQFnoECAUQAQ&usg=AOvVaw1zOeQfrhjQW4JAWAfpZJ0d

**Comment by sgowroji** [comment]
Hello @mattem, Above query is fixed.Could you please verify with the [latest](https://bazel.build/rules/lib/dict). Thanks!
