### ISSUE TITLE
Out of Date Documentation issue: Building JavaScript Outputs

### ISSUE THREAD

**Issue by sbussard** [bazelbuild/bazel#14915]
Documentation URL: https://docs.bazel.build/versions/5.0.0/build-javascript.html

`ts_devserver` has been renamed.

**Comment by sgowroji** [comment]
Hello @sbussard, Could you please elaborate your query with complete details Or can you send a PR with the above mentioned changes. I can help you in arranging the review. Thanks!

**Comment by sbussard** [comment]
I no longer have context for this issue. Closing.
