### ISSUE TITLE
execv error executing PEX in custom rule

### ISSUE THREAD

**Issue by nickbreen** [bazelbuild/bazel#14921]
### Description of the problem / feature request:

> Attempting to write a `rule` to use [pex](https://github.com/pantsbuild/pex/releases/download/v2.1.67/pex) to build PEX's.
> 
> Getting a strange error from `ctx.actions.run` that does not manifest with a `genrule` or direct invocation outside of bazel.

### Feature requests: what underlying problem are you trying to solve with this feature?

> Define a simple `pex_binary` rule.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Minimal reproduction: https://github.com/nickbreen/bazel_pex

### What operating system are you running Bazel on?

> Fedora 34, Python 3.6 and 3.9

### What's the output of `bazel info release`?

> release 4.2.0

###  Have you found anything relevant by searching the web?

> I've found a number of repos and issues on github for bazel and rules_python, etc; all of which appear to be inconclusive or appear ancient/abandoned:
> - https://github.com/bazelbuild/bazel/issues/11931
> - https://github.com/borancar/mishmash/commit/928cd7bb75c93472c3931f3f8f56941786ec6116#diff-6b9d2d187ff982cd6100e3a5e0813e450351d5164262d0c1d9acc43522d994db
> - https://github.com/benley/bazel_rules_pex
> - https://gist.github.com/simeonf/062af826e79259bc7686
> - https://www.shearn89.com/2021/04/15/pex-file-creation

### Any other information, logs, or outputs that you want to share?

> Please see https://github.com/nickbreen/bazel_pex

**Comment by comius** [comment]
Quick look, this looks like an error thrown by an action during its execution (not something thrown by Bazel).
