### ISSUE TITLE
bazel is trying to access non-existing c:\tools\msys64\usr\bin\bash.exe

### ISSUE THREAD

**Issue by korDen** [bazelbuild/bazel#14928]
### Description of the problem / feature request:

Using PowerShell to invoke bazel, genrule is trying to execute bash.exe at location that does not contain bash.exe, and fails:

 bazel build --verbose_failures blank_txt
INFO: Analyzed target //:blank_txt (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: C:/develop/vrst/BUILD:19:8: Executing genrule //:blank_txt failed: (Exit -1): bash.exe failed: error executing command
  cd /d C:/tmp/bazel/output/iakn3uvv/execroot/vrst
  SET PATH=c:\tools\msys64\usr\bin;c:\tools\msys64\bin;C:\WINDOWS;C:\WINDOWS\System32;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Users\Ana Stone\AppData\Local\bazelisk\downloads\bazelbuild\bazel-5.0.0-windows-x86_64\bin;C:\develop\vulkan-sdk-1.3.204.0\Bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Insta360Stitcher\tools\proStitcher;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\Ana Stone\.cargo\bin;C:\Users\Ana Stone\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Insta360Stitcher\tools\proStitcher;c:\Program Files\Sublime Text 3;;C:\Users\Ana Stone\AppData\Local\Programs\Microsoft VS Code\bin
    SET RUNFILES_MANIFEST_ONLY=1
  c:\tools\msys64\usr\bin\bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; echo '' > bazel-out/x64_windows-fastbuild/bin/blank.txt
# Configuration: d3c850f58454fe64128fb65ae959a3298f814fc96a98786b5d1160cfd6f82b65
# Execution platform: @local_config_platform//:host
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("c:\tools\msys64\usr\bin\bash.exe" -c "source external/bazel_tools/tools/genrule/genrule-setup.sh; echo '' > bazel-out/x64_windows-fastbuild/bin/blank.txt"): The system cannot find the file specified.
 (error: 2)
Target //:blank_txt failed to build
INFO: Elapsed time: 0.137s, Critical Path: 0.01s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully

### Feature requests: what underlying problem are you trying to solve with this feature?

n/a

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

genrule(
    name = "blank_txt",
    outs = ["blank.txt"],
    cmd = "echo '' > $(OUTS)",
)

bazel build blank_txt

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 5.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

No.

**Comment by gregestren** [comment]
@meteorcloudy

**Comment by meteorcloudy** [comment]
@korDen Bazel's genrule by default runs Bash command, that's why it tries to find the Bash.exe on your system.
You have two options, 

- You can install MSYS2 on your machine and set `BAZEL_SH` to point to the bash.exe (Bazel can also [detect](https://cs.opensource.google/bazel/bazel/+/master:src/main/cpp/blaze_util_windows.cc;l=1423) it from the `PATH` env var)
- Or you can write equivalent Batch or Powershell command via the `cmd_bat` or `cmd_ps` attribute of genrule, then it won't try to run the bash command on Windows.

**Comment by meteorcloudy** [comment]
Since this is WAI, I'm closing this.
