### ISSUE TITLE
[5.1] Bazel crashes with InterruptedException when certain benign errors happen

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#14932]
Forked from #14787

**Comment by gregestren** [comment]
@Wyverald what's the right way to triage a 5.1 bug?

**Comment by Wyverald** [comment]
@gregestren I think "ignore" would be fine, but I don't know what our tooling currently works with. If leaving an issue unlabeled is hard to work with, we could repurpose the "release blocker" label to mean "this is to track a bug for a release, don't triage".
