### ISSUE TITLE
interface_deps in C++ rules is not backwards compatible

### ISSUE THREAD

**Issue by eric-skydio** [bazelbuild/bazel#14950]
Recently, Bazel added experimental support for `implementation_deps` in C++ rules, which has the potential to significantly improve compile times and incrementality by limiting the propagation of transitive header files. We're _really_ excited for this, and have started using it in our large repo in Bazel 5.x with promising initial results, including performing large-scale rewrites of rules for all the code we control.

Concerningly, it appears that https://github.com/bazelbuild/bazel/commit/56409448dfd7507f551f65283b4214020754c25c recently landed in the master branch, which switches the semantics so that `deps` is the old `implementation_deps` and `interface_deps` is the old `deps`. Unfortunately, this completely breaks our use case because significant amounts of third-party code we load into our workspace immediately breaks as soon as we flip the experimental flag, since it uses `deps` and then proceeds to #include those things in header files. If unresolved, this will be a major blocker for us updating to Bazel 6.x

Double-unfortunately, this version upgrade problem seems to be fundamental, and I can't think of any way for the community to work around it. In particular, it will be impossible to write a Bazel cc_library target that works correctly both in Bazel <=5.x and in Bazel 6.x with the experimental flag enabled, which means any open-source libraries will _de facto_ need to keep using the old semantics indefinitely, and flipping the flag will be permanently impossible for anyone who imports significant third-party code. 

I think the right solution here is to simply revert the above commit and live with the slightly awkward API of "implementation_deps". Changing an API like this is _possible_, but would require either a multi-year feature rollout strategy or renaming `cc_library` and deprecating the old one, neither of which seems like a desirable option.

@oquenchil

**Comment by oquenchil** [comment]
The reason for this change in semantics is to make it be inline with the exports attribute in other rules like java_library and proto_library. We wouldn't have done such an invasive change if this wasn't behind an experimental flag.

I see your point about migration and this is something that I already added code for internally. I wasn't planning to move this feature into production for OSS Bazel yet but we can apply the same solution. Opting into the new behavior per target would be done via a tag in the cc_library.tags (`__INTERFACE_DEPS__`). You can send a PR to change the logic in https://cs.opensource.google/bazel/bazel/+/master:src/main/starlark/builtins_bzl/common/cc/semantics.bzl;drc=7a4b146a406dbe085c14b96c9fb23a176072617c;l=66:
```
    has_interface_deps_tag = "__INTERFACE_DEPS__" in ctx.attr.tags
    if ((len(ctx.attr.interface_deps) or has_interface_deps_tag) and
            not ctx.fragments.cpp.experimental_cc_interface_deps()):
        fail(attr = "interface_deps", msg = "Some informative error")

    if len(ctx.attr.interface_deps) and not has_interface_deps_tag:
        fail(attr = "interface_deps", msg = "Please include the tag '__INTERFACE_DEPS__'" +
                                            " in tags when using the 'interface_deps' attribute")
   
     return has_interface_deps_tag
``` 

Starlark cc_library will definitely be flipped for 6.0, it will be flipped in the next few weeks. If you are working with a head version of Bazel, then you'd have to change the logic here too:
https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/bazel/rules/cpp/BazelCppSemantics.java;l=171


At the same time I advise against relying heavily on this experimental feature for now as we reserve the right to make breaking changes at any time.

**Comment by eric-skydio** [comment]
That could work for us, although it's still pretty gross that we need to use a wrapper macro or clutter up our build files, and I _think_ a similar (although somewhat less severe) issue will be present if Bazel ever wants to remove the need for the tag by default. One thing that would help would be to publish a `@rules_cc_legacy` repository that wraps `@rules_cc` and provides the old semantics, so that the `repo_mapping =` argument can be used to provide legacy semantics for relevant third-party code. That does still notably require everyone switching from `native.cc_*`, although it sounds like that's coming soon anyway.

**Comment by martis42** [comment]
@oquenchil Is there an issue or a public discussion somewhere where one can read more details about the decision to move forward with `interface_deps` and drop `implementation_deps`?

**Comment by oquenchil** [comment]
> That could work for us, although it's still pretty gross that we need to use a wrapper macro or clutter up our build files, and I _think_ a similar (although somewhat less severe) issue will be present if Bazel ever wants to remove the need for the tag by default. One thing that would help would be to publish a `@rules_cc_legacy` repository that wraps `@rules_cc` and provides the old semantics, so that the `repo_mapping =` argument can be used to provide legacy semantics for relevant third-party code. That does still notably require everyone switching from `native.cc_*`, although it sounds like that's coming soon anyway.

When I have more bandwidth to work on this, I can create a document where we can brainstorm the best ways to make migration easy. We can have an allowlist per repo too which controls behavior, whether something on the allowlist means that it should use legacy or new behavior can be decided by the repo owner. I won't have time for this this quarter or the next.




> @oquenchil Is there an issue or a public discussion somewhere where one can read more details about the decision to move forward with `interface_deps` and drop `implementation_deps`?

Nope, as I mentioned earlier, this is behind an experimental flag. If such an invasive change were not behind an experimental flag it is very likely that we would have left the old API or at the very least there would have been public discussion about this.

The decision was based on being more consistent with other rulesets and the fact that it's still experimental.

**Comment by oquenchil** [comment]
> I won't have time for this this quarter or the next.

I will make some room in Q2 for a document where we can discuss migration ideas publicly.

**Comment by martis42** [comment]
@oquenchil 
I see `interface_deps` has been reverted back to `implementation_deps`. Can we expect it to stay this time, or are there further breaking changes planned for this feature?

Should we close this issue, now that `interface_deps` and the associated migration issues are no longer present?

**Comment by oquenchil** [comment]
You can expect it to stay like this.
