### ISSUE TITLE
Insufficient error checking in GenQuery

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#1495]
When comparing `GenQuery` with `QueryCommand` there is a huge discrepancy between what the latter validates and the former misses. Perhaps would make sense to merge more code of these 2 so they can employ singular error checking.

**Comment by janakdr** [comment]
Can you give an example?

On Sun, Jul 10, 2016 at 3:23 PM, Andreas Bergmeier <notifications@github.com

**Comment by ulfjack** [comment]
Closing due to insufficient information.
