### ISSUE TITLE
Document requirement for fusermount executable for sandboxfs

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/bazel#14973]
`--experimental_use_sandboxfs` requires the fusermount executable (e.g. Debian fuse package) to work.

This requirement isn't listed (nor strictly necessary) in the install instructions of the sandboxfs project. The instructions list libfuse2, but not fuse.

(Terribly unspecific error message make the problem worse. #5369)

**Comment by benjaminp** [comment]
217fafe2b492de7349547cc3be2b9eef38628055
