### ISSUE TITLE
repository_ctx.symlink produces invalid workspace absolute symlinks

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#1498]
When I try to `symlink` e.g. the directory `@//mydir` into `foo` like this:

    repository_ctx.symlink("@//mydir", "foo")

It produces a symlink to ...`/external/myrepo/@/mydir`. Same behavior for `__main__`.
A similar behavior gets evident if you try to use `repository_ctx.path("@//mydir")`.

Sadly this is a major show stopper for us :(

**Comment by abergmeier** [comment]
@damienmg Would it make sense to fix this behavior now, since your rework seems to be at least 2 weeks away?

**Comment by kchodorow** [comment]
You need to use `Label("@//mydir")` if you want it to be interpreted as a label.

**Comment by abergmeier** [comment]
AFAIK you cannot refer to directories as labels.

When trying `Label("@//mydir")`it is complaining:

    no such package '@mydir//': Unable to load package for //mydir:mydir: not found.

When trying `Label("@//:mydir")` it is complaining:

    no such package '@mydir//': Not a file: /myproject/mydir

**Comment by kchodorow** [comment]
You have to expose mydir as a target, e.g., add to your BUILD file (in the directory mydir is in):

```
exports_files(["mydir"])
```

**Comment by abergmeier-dsfishlabs** [comment]
> You have to expose mydir as a target, e.g., add to your BUILD file (in the directory mydir is in):
>
>     exports_files(["mydir"])

Have tried this now in https://github.com/abergmeier-dsfishlabs/examples. Either I am doing something wrong or it does not work. If you want try building with `bazel build @foo//...`

**Comment by kchodorow** [comment]
Well, you had `export_files` (not `exports_files`), but I realized that's not going to work anyway, because you can't use a directory as a target.  However, you can use __workspace_dir__ in the WORKSPACE file to refer to your source directory, so you could do:

```
foo_repository(
  name = "foo",
  build_path = __workspace_dir__ + "/bar",
)
```

**Comment by abergmeier-dsfishlabs** [comment]
> However, you can use workspace_dir in the WORKSPACE file to refer to your source directory, so you could do:

That works great. Thanks a mill.

**Comment by kchodorow** [comment]
Great, np!
