### ISSUE TITLE
Bazel CI: rules_apple broken with Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#14996]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2389#6040b623-0901-48a9-b1e0-2e53b246accd
```
test/starlark_tests/targets_under_test/tvos:basic_framework_with_transitive_dependency:
Traceback (most recent call last):
	File "/Users/buildkite/builds/bk-imacpro-7/bazel-downstream-projects/rules_apple/apple/internal/tvos_rules.bzl", line 396, column 58, in _tvos_dynamic_framework_impl
		link_result = linking_support.register_linking_action(
	File "/Users/buildkite/builds/bk-imacpro-7/bazel-downstream-projects/rules_apple/apple/internal/linking_support.bzl", line 160, column 58, in _register_linking_action
		linking_outputs = apple_common.link_multi_arch_binary(
Error in link_multi_arch_binary: link_multi_arch_binary() got unexpected keyword argument 'should_lipo'
```

According to https://buildkite.com/bazel/bazel-auto-sheriff-face-with-cowboy-hat/builds/840, the culprit is:
https://github.com/bazelbuild/bazel/commit/3073f1b72fd6a9df758d059391b1f6791ea5eb1b

**Comment by keith** [comment]
The fix is that we have to include https://github.com/bazelbuild/rules_apple/pull/1383

But unless this change is valid to cherry pick to 5.1, this change makes it impossible for the rules to support both bazel@HEAD and the LTS releases at the same time, which is a downside for users and maintainers.

**Comment by meteorcloudy** [comment]
> But unless this change is valid to cherry pick to 5.1, this change makes it impossible for the rules to support both bazel@HEAD and the LTS releases at the same time, which is a downside for users and maintainers.

**Comment by Wyverald** [comment]
> this change makes it impossible for the rules to support both bazel@HEAD and the LTS releases at the same time

This was always going to happen, unfortunately. Obviously we'd all like to develop new features and also magically have them be backwards compatible, but that's not going to happen. LTS releases are inevitably going to be incompatible with HEAD.

> which is a downside for users and maintainers.

I think this is a compromise we debated at length and ended up happy with. Most people who want to stick with the newest features should use rolling releases. Bzlmod/BCR will also alleviate the problem by having compatibility matrices.

---

I don't think we should cherry-pick any breaking changes into 5.1. IMO there should simply be a version X of rules_apple which is the last one that supports Bazel 5.x; rules_apple >X can work with rolling releases. If it's really needed, rules_apple can branch from X to backport 5.x compatible changes.

**Comment by meteorcloudy** [comment]
I think a more practical question is how https://github.com/bazelbuild/rules_apple/pull/1383 could pass the presubmit since it's still being tested with Bazel 5.0 (disable builds with Bazel 5.0?)

Ideally, when introducing an incompatible change X, there should be a solution for downstream project that allows it to work with X enabled and disabled. Unfortunately, it seems hard to find such a solution when people remove/rename some arguments from the API.. 😕

**Comment by keith** [comment]
Last time around we just disabled the latest release / latest RC jobs at HEAD, which I guess we will do again

**Comment by Wyverald** [comment]
hmm. I seem to remember that there's a way for bazelci.py to specify whether we want HEAD or latest release Bazel. If we adopt the model I described above for rules_apple, we could simply stick with Bazel HEAD always, and only change to release Bazel for the "X" release (and any further backported commits on that branch). Would that be reasonable?

**Comment by keith** [comment]
I ended up coming up with a huge hack to do a bazel version check (give or take) to determine whether or not this argument should be passed so that we can continue to provide updates for bazel 5.x users https://github.com/bazelbuild/rules_apple/pull/1385

Either way we can close this issue now.

**Comment by meteorcloudy** [comment]
@keith That's a clever hack, thanks for fixing this!
