### ISSUE TITLE
Severe performance degradation for filesystem operations

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#1499]
When I execute

```
result = repository_ctx.execute([
        "cp", "-R", "-l", src, dst
    ]
)
```

it takes more than a minute to finish.

Executing the same command in a terminal takes:

```
real     0m0.496s
user     0m0.112s
sys      0m0.380s
```

I imagine there is some sandboxing behavior that is problematic. Any ideas?

**Comment by abergmeier** [comment]
_strace_ for in Bazel:

_trying to figure out how to get -c working for Bazel_

_strace_ for in terminal:

    % time     seconds  usecs/call     calls    errors syscall
    ------ ----------- ----------- --------- --------- ----------------
     46.67    0.000651           0     94741           stat
     19.78    0.000276           0     94740           lstat
     16.92    0.000236           0     40777           getdents
      9.03    0.000126           0     20391           open
      4.30    0.000060           0     20394           close
      3.30    0.000046           0     20391           fstat
      0.00    0.000000           0         9           read
      0.00    0.000000           0         1         1 lseek
      0.00    0.000000           0        24           mmap
      0.00    0.000000           0        16           mprotect
      0.00    0.000000           0         1           munmap
      0.00    0.000000           0        12           brk
      0.00    0.000000           0         2           rt_sigaction
      0.00    0.000000           0         1           rt_sigprocmask
      0.00    0.000000           0         9         9 access
      0.00    0.000000           0         1           execve
      0.00    0.000000           0         1           getrlimit
      0.00    0.000000           0         1           sysinfo
      0.00    0.000000           0         1           geteuid
      0.00    0.000000           0         2         2 statfs
      0.00    0.000000           0         1           arch_prctl
      0.00    0.000000           0         1           set_tid_address
      0.00    0.000000           0         1           set_robust_list
    ------ ----------- ----------- --------- --------- ----------------
    100.00    0.001395                291518        12 total

**Comment by damienmg** [comment]
Can you try to do a loop to measure the mean exec time of ls? Bazel taking a long time is not suprising but the exec should be pretty fast.

**Comment by abergmeier** [comment]
> Can you try to do a loop to measure the mean exec time of ls?

`ls -R src` time in Bazel:
    real 0.60
    user 0.30
    sys 0.29

`ls -Risah src` time in terminal:
    real 1.44
    user 0.59
    sys 0.29

Looks pretty fine to me.

> Bazel taking a long time is not suprising but the exec should be pretty fast.

Do not really get what you are trying to say. I can look at `iotop` and see that `cp` runs way longer than in terminal - although not the whole Bazel waiting time.

**Comment by abergmeier-dsfishlabs** [comment]
Times of `cp -R` in Bazel are BTW:

    real 16.26
    user  0.12
    sys   1.04

**Comment by abergmeier-dsfishlabs** [comment]
I think the main culprit is probably related to file system caches.

It seems when Bazel is starting processing it is doing something that is poison to the file system cache (and effectively invalides `src` cache).
The reason for the numbers to get so high is that both `src` and `dst` are on a HDD and thus happy spinning is in order. Since `src` contains 100.000 inodes, this then takes a "while" and is getting IO bound at times (according to _iotop_).
My worry now is that by experience, the worst file system operation runtimes on Linux are the default ones for Windows. This then means using `cp -R -l` is not an option anymore and I have to find another way of setting up the repository :-1:

**Comment by damienmg** [comment]
I will be out for a week but I'll try to understand what's going on when I am back.

**Comment by damienmg** [comment]
Ok I think this a bit too complex to resolve soonish.

**Comment by abergmeier-dsfishlabs** [comment]
At least we do not need this "resolved" anymore. We changed our data structure internally and thus this is no longer a problem.
