### ISSUE TITLE
--run_under failure for empty string

### ISSUE THREAD

**Issue by chriscraws** [bazelbuild/bazel#15002]
### Description of the problem / feature request:

I have `test:linux --run_under="xvfb-run -a"` set in my .bazelrc - there's not an easy way to override this flag to remove the command prefix from the command line. Attempting to set it to an empty string results in: 

`ERROR: While parsing option --run_under=: Empty command`

### Feature requests: what underlying problem are you trying to solve with this feature?

Allow an empty string to be passed to the `--run_under` flag

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run any bazel test or binary with `--run_under=""`

### What operating system are you running Bazel on?

Arch Linux

### What's the output of `bazel info release`?

release 5.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Not at this time

**Comment by chriscraws** [comment]
Workaround I'm using now:

Added a `sh_binary` target at `//tools:run`

source:
```
#!/bin/bash
exec $@
```

Now I can overwrite with `--run_under="//tools:run"`

**Comment by haxorz** [comment]
Hey @chriscraws, thanks for the FR and nice workaround!

We'd definitely accept a PR that adds and documents a way to override a previously specified value of `--run_under`.
