### ISSUE TITLE
layering_check missing layering violation

### ISSUE THREAD

**Issue by GMNGeoffrey** [bazelbuild/bazel#15004]
### Description of the problem / feature request:

`layering_check` is not finding a layering violation in our Bazel build which is caught by the internal version.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```shell
git clone https://github.com/google/iree iree-repro-bazel
cd iree-repro-bazel
python3 configure_bazel.py
git checkout 36fb4d3e
cd integrations/tensorflow
bazel build iree_tf_compiler/TF
```

This command should fail with a layering_check error, but it succeeds.

### What operating system are you running Bazel on?

Linux Debian

### What's the output of `bazel info release`?

release 5.0.0

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Running with the internal version of Bazel and layering_check I get an error like this, which is expected:

```
ERROR: integrations/tensorflow/iree_tf_compiler/TF/BUILD:24:11: Compiling integrations/tensorflow/iree_tf_compiler/TF/Passes.cpp failed: (Exit 1)
integrations/tensorflow/iree_tf_compiler/TF/Passes.cpp:14:10: error: module //integrations/tensorflow/iree_tf_compiler/TF:TF does not depend on a module exporting 'mlir/Transforms/Passes.h'
#include "mlir/Transforms/Passes.h"
         ^
1 error generated.
```

Indeed this target does not depend on a target exporting that header. It needs to depend `@llvm-project//mlir:Transforms`. When fixing that error, I get a further error for the include of "mlir/Dialect/Affine/Utils.h", which is also a layering violation. You can see the exact version of the LLVM build file being used at https://github.com/llvm/llvm-project/blob/7c65d2288bfd03ca3c3e829c7746b5e4e495357f/utils/bazel/llvm-project-overlay/mlir/BUILD.bazel (the path to determine this is rather convoluted, but you should also be able to look in the Bazel-generated directory under integrations/tensorflow)

**Comment by scentini** [comment]
I believe this is due to tensorflow [overriding](https://github.com/tensorflow/tensorflow/blob/e66ec6fda0988353caa4c46f13ea96f07281df83/tensorflow/workspace0.bzl#L108) the Bazel provided toolchain configuration with the one from [`@rules_cc`](https://github.com/bazelbuild/rules_cc).

Initially, the plan was to move the toolchain configuration to `@rules_cc`, but that plan hasn't yet materialized; the current state is that `@rules_cc` has a copy of the toolchain configuration mechanism which was not kept up to date, and it doesn't support `layering_check`. I'd try removing the override.

**Comment by GMNGeoffrey** [comment]
![image](https://user-images.githubusercontent.com/5732088/158479103-f6df3f01-991a-437c-aec1-df4986bc454f.png)

I'll give that a try

**Comment by GMNGeoffrey** [comment]
Indeed, going into the Bazel directory and editing `bazel-tensorflow/external/org_tensorflow/tensorflow/workspace0.bzl` to remove the call to `rules_cc_toolchains` fixes the issues (correctly reports the error). So is the current advice that TF should *not* be doing that?

**Comment by oquenchil** [comment]
Yes, I'd advise not to rely on rules_cc. 

Thank you @scentini .
