### ISSUE TITLE
Question: Is junit forkmode (per-test) supported?

### ISSUE THREAD

**Issue by brettwooldridge** [bazelbuild/bazel#15012]
I have been digging through the documentation, and Googling, but I cannot find how to use the JUnit "forkmode" for ``java_test`` rules. Or whether it is supported?

I am porting our project over from Buck, and in Buck there is a concept of *fork_mode*:
```
java_test(
    name = 'test',
    srcs = glob(['test/src/**/*.java']),
    vm_args = ['-Djdk.attach.allowAttachSelf'],
    fork_mode = "per_test",
    ...
```
Obviously, this is not a concept unique to Buck, as it is supported by Maven, Ant, and possibly others. Is this supported directly in Bazel, or through a tag or system property, or via a workaround?

**Comment by comius** [comment]
I'm not familiar with `fork_mode` or what it does. There is a bunch of attributes you can set on any _test rule: https://bazel.build/reference/be/common-definitions#common-attributes-tests

Also see https://bazel.build/reference/test-encyclopedia#test-sharding

I hope something there helps answer your question.
