### ISSUE TITLE
Add warning if local action uses much more memory than specified

### ISSUE THREAD

**Issue by glukasiknuro** [bazelbuild/bazel#15018]
### Description of the feature request:

Currently one is able to specify resource_set for a given `ctx.action.run` or `ctx.action.run_shell`. It would be useful to emit a warning if actual memory used by a local action is way bigger than requested. There are already two options that allow to collect memory usage: `--experimental_collect_local_sandbox_action_metrics` and `--experimental_collect_local_action_metrics`, it would be useful to add an option like `--experimental_warn_local_action_memory_usage_threshold==2` that would in this case print a warning whenever a given action used 2x of requested memory.

### Feature requests: what underlying problem are you trying to solve with this feature?

Automatically find local actions that have their resources specified too low.

### What operating system are you running Bazel on?

Ubuntu 20.04

###  Have you found anything relevant by searching the web?

There is `--experimental_local_memory_estimate` option that tries to automatically estimate available memory, but it seems it's buggy now: https://github.com/bazelbuild/bazel/issues/13217

**Comment by meisterT** [comment]
cc @larsrc-google

**Comment by larsrc-google** [comment]
@wilwell has run some statistics on memory usage, and there are frequently outliers that we don't see an easy way to predict. I suspect there are some cases where it's just the behaviour of the tool, particularly VM-based tools, but an easier way to find this problems could be useful.

**Comment by wilwell** [comment]
I am leaving the Bazel team, and it looks like that issue has low priority, so closing it.
