### ISSUE TITLE
Support `key` callback parameter for `min()`, `max()` starlark builtin functions

### ISSUE THREAD

**Issue by tetromino** [bazelbuild/bazel#15022]
See https://github.com/bazelbuild/starlark/blob/master/spec.md#max

**Comment by tetromino** [comment]
I light of #15022 - let me clarify how I see the feature needs to be implemented. Naturally, we do not want to call `sorted` (finding a min or max is an O(n) time and O(1) space problem; creating a temporary a sorted copy of the list is O(n log n) time and O(n) space). But we also do not want trivial comparator-based implementations that might evaluate `key` twice on each element of the list - the `key` function might be heavy, it might hypothetically have side effects, we want to call it only once on each element.

Thus ideally, I'd like to see an efficient, lightweight sort-key helper that would be shared between the implementations of `sorted`, `min` and `max`.

**Comment by fmeum** [comment]
@bazel-io fork 7.2.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.2.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.2.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.2.0rc1. Thanks!
