### ISSUE TITLE
Bazel generates files in /tmp

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#1504]
https://github.com/Homebrew/homebrew-core/pull/1887#issuecomment-225380825

Even when setting `TEST_TMPDIR`, Bazel generates files in `/var/tmp/_bazel_$USERNAME`.

**Comment by damienmg** [comment]
This is fixed by 276a8cd19d4cde6245ed3323cee695e7834a0b9d and 276a8cd19d4cde6245ed3323cee695e7834a0b9d

**Comment by dfabulich** [comment]
… and a3381b6ac136a0cab3ba86020c739fe16b42cee9
