### ISSUE TITLE
bzlmod: bazel query doesn't work with imported repos

### ISSUE THREAD

**Issue by zecke** [bazelbuild/bazel#15044]
### Description of the problem / feature request:

`bazel query --experimental_enable_bzlmod @default_node16_host//...` fails instead of listing targets.

```
INFO: Analyzed 15 targets (3 packages loaded, 2875 targets configured).
INFO: Found 15 targets...
ERROR: Error doing post analysis query: Evaluation of query "@default_node16_host//..." failed: no targets found beneath ''
INFO: Elapsed time: 1.223s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

### Feature requests: what underlying problem are you trying to solve with this feature?

I would like to discover the targets of a repository that I imported from a module. Or in a larger context, discover the repositories that I could import from a module.

The closest to working is this:

```
bazel query --experimental_enable_bzlmod @rules_nodejs.4.5.1.node.default_node16_host//...
@rules_nodejs.4.5.1.node.default_node16_host//:bin/node_repo_args.sh
@rules_nodejs.4.5.1.node.default_node16_host//:node
@rules_nodejs.4.5.1.node.default_node16_host//:node_bin
...
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ cat MODULE.bazel 
module(
  name = "app",
  version = "1.0",
  compatibility_level = 1,
)

bazel_dep(
  name = "rules_nodejs",
  version = "4.5.1",
)

node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node")
node.toolchain(name = "default_node16", node_version = "16.10.0")
use_repo(node, "default_node16_host")
```

`$ bazel query  --experimental_enable_bzlmod @default_node16_host//...`

### What operating system are you running Bazel on?

MacOS 11.6 on the M1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

bazel info release                                                 
release 5.0.0

### Any other information, logs, or outputs that you want to share?

> Replace this line with your answer.

**Comment by meteorcloudy** [comment]
Changing to P1 since this is blocking the cut of Bazel 6.0 release.

**Comment by fmeum** [comment]
@gregestren I looked into this once and wasn't able to figure out whether and how `bazel query` can get it's hand on the `RepositoryMapping` of the main repository. If that were possible, the fix shouldn't be difficult.

**Comment by Wyverald** [comment]
This is already being worked on by @andyrinne12 and is close to completion (in internal review).

**Comment by meteorcloudy** [comment]
I believe this is already fixed by https://github.com/bazelbuild/bazel/commit/e3e544587fec613fa01e54fb5248fed53c68ba57
