### ISSUE TITLE
sh_binary's data dependencies are not triggered during the build

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel#15043]
### Description of the problem / feature request:

When a `sh_binary` has a target in the `data` attribute, the target is not built automatically when the `sh_binary` target is built.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

* Check out [rules_docker](https://github.com/bazelbuild/rules_docker/tree/0b1a033eff28eeff474573c7ed2d5b9d9bec4af1)
* `bazel clean`
* `bazel build //docs:update`
* `ls bazel-bin/docs/container.md_`
Although `bazel-bin/docs/container.md_` is the output of `//docs:container_doc`, which is depended by `//docs:update`, it is not built.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 5.0.0-homebrew

**Comment by linzhp** [comment]
Sorry for the delay. I pull from #15052, and built `//src:bazel-dev`. But when I used the built binary to build `//docs:update` of rules_docker, I got:

```
DEBUG: /private/var/tmp/_bazel_zplin/d6323f9e3146540840037c805ccd73ff/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:14: 
Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '4.0.0'
ERROR: /private/var/tmp/_bazel_zplin/d6323f9e3146540840037c805ccd73ff/external/bazel_tools/src/tools/launcher/BUILD:9:14: While resolving toolchains for target @bazel_tools//src/tools/launcher:launcher: No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type. Maybe --incompatible_use_cc_configure_from_rules_cc has been flipped and there is no default C++ toolchain added in the WORKSPACE file? See https://github.com/bazelbuild/bazel/issues/10134 for details and migration instructions.
ERROR: Analysis of target '//docs:update' failed; build aborted: 
INFO: Elapsed time: 6.538s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (50 packages loaded, 309 targets configured)
```

**Comment by fmeum** [comment]
@linzhp The build succeeds for me following the instructions from your initial post. Are you on Linux and does `bazel build //...` succeed for you on the repo on the commit prior to mine? The change may cause building new transitive dependencies for `//docs:update`, but if those weren't broken before, they shouldn't be now. The result of rerunning the command with `--toolchain_resolution_debug='.*'` would also be useful to figure out what broke.

**Comment by linzhp** [comment]
Switched to macOS for Intel and tried your fix again. It worked. Thanks!

I was on macOS for Apple Silicon before. The commit before yours fails too, but Bazel 5.0.0 works. I saw:

```
INFO: ToolchainResolution:     Type @bazel_tools//tools/cpp:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @local_config_cc//:cc-compiler-darwin_arm64; mismatching values: arm64
```

**Comment by fmeum** [comment]
That looks more like an unrelated regression. Could you create a separate issue and perhaps rerun the test with 5.1.0rc2? 5.1.0 will be released soon.

**Comment by brandjon** [comment]
Dupping against #12348.

**Comment by brandjon** [comment]
Sorry, I missed that #15052 is being actively developed, so I'll keep this issue alive as the author's preferred tracking bug.

**Comment by rickeylev** [comment]
As an FYI, there may be some dependencies on this behavior between the Python rules and some other Google-internal rules. i.e. enabling the flag introduced by this will likely show failures in the Google global regression tests (TGP). See the large comment block in blaze/python/common.bzl#collect_runfiles for more details. The gist, though, is some Google-internal rules have different default outputs vs data/default runfiles, and have come to rely on this so that otherwise unused outputs (some of which can be very large) don't get included in the runfiles.

**Comment by fmeum** [comment]
@rickeylev Thanks for mentioning this. I added a workaround to the migration guide at https://github.com/bazelbuild/bazel/issues/16654. Could that even work for Google?
