### ISSUE TITLE
HardenedBSD 13 java examples does not compile

### ISSUE THREAD

**Issue by UlasSAYGINIM** [bazelbuild/bazel#15057]
### Description of the problem / feature request:

> I tried to compile java tutorial project on hardenedbsd 13 but it didnt compile

### Feature requests: what underlying problem are you trying to solve with this feature?

> root@hbsdb03:~/examples/java-tutorial # bazel build //:ProjectRunner
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...
... still trying to connect to local Bazel server after 20 seconds ...
... still trying to connect to local Bazel server after 30 seconds ...
... still trying to connect to local Bazel server after 40 seconds ...
ERROR: /root/.cache/bazel/_bazel_root/9318dfd54d71a6b918f8033146aeac2a/external/bazel_tools/tools/jdk/BUILD:474:27: While resolving toolchains for target @bazel_tools//tools/jdk:remote_jdk11: no matching toolchains found for types @bazel_tools//tools/jdk:runtime_toolchain_type
ERROR: Analysis of target '//:ProjectRunner' failed; build aborted:
INFO: Elapsed time: 61.756s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (42 packages loaded, 774 targets configured)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> try to compile example project of java for bazel

### What operating system are you running Bazel on?

> HardenedBSD 13 but i think it is same for FreeBSD 13 , i will test it also.

### What's the output of `bazel info release`?

> release 5.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

>  # git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
https://github.com/bazelbuild/examples
master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
d1a1f1fcf460a7f3aa0eb845b22dab061eff8ec9

###  Have you found anything relevant by searching the web?

> i think this problem continue : https://github.com/bazelbuild/bazel/issues/7219 , https://github.com/bazelbuild/bazel/issues/6245 , https://github.com/bazelbuild/bazel/issues/8750

### Any other information, logs, or outputs that you want to share?

>  bazel build //:ProjectRunner --announce_rc
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=237
INFO: Reading rc options for 'build' from /usr/local/etc/bazel/bazel.bazelrc:
  'build' options: --strategy=Javac=standalone --java_runtime_version=11 --tool_java_runtime_version=11 --action_env=PATH=/bin:/usr/bin/:/usr/local/bin
ERROR: /root/.cache/bazel/_bazel_root/9318dfd54d71a6b918f8033146aeac2a/external/bazel_tools/tools/jdk/BUILD:474:27: While resolving toolchains for target @bazel_tools//tools/jdk:remote_jdk11: no matching toolchains found for types @bazel_tools//tools/jdk:runtime_toolchain_type
ERROR: Analysis of target '//:ProjectRunner' failed; build aborted:
INFO: Elapsed time: 0.293s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

**Comment by comius** [comment]
Can you provide output when running with `--toolchain_resolution_debug`? What CPU/architecture are you running on?

**Comment by sgowroji** [comment]
Hello @UlasSAYGINIM, Did you get a chance to look at the above [comment](https://github.com/bazelbuild/bazel/issues/15057#issuecomment-1075260280) and provide the requested details. Thanks!

**Comment by UlasSAYGINIM** [comment]
hi @sgowroji , i couldnt have time to look. i will look it in couple of days. i will inform you about result.
thank you for interest.

**Comment by ckolli5** [comment]
@UlasSAYGINIM Just a friendly reminder, could you please provide us with details requested in this [comment](https://github.com/bazelbuild/bazel/issues/15057#issuecomment-1075260280). Thanks!

**Comment by UlasSAYGINIM** [comment]
@ckolli5  thank. it was virtual machine. i moved files and i couldnt look which one. i will provide information soon.
thank you for kind reminder.

**Comment by UlasSAYGINIM** [comment]
```
root@hbsdb03:~/examples/java-tutorial # bazel build //:ProjectRunner
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...
... still trying to connect to local Bazel server after 20 seconds ...
... still trying to connect to local Bazel server after 30 seconds ...
... still trying to connect to local Bazel server after 40 seconds ...
... still trying to connect to local Bazel server after 50 seconds ...
ERROR: /root/.cache/bazel/_bazel_root/9318dfd54d71a6b918f8033146aeac2a/external/bazel_tools/tools/jdk/BUILD:474:27: While resolving toolchains for target @bazel_tools//tools/jdk:remote_jdk11: no matching toolchains found for types @bazel_tools//tools/jdk:runtime_toolchain_type
ERROR: Analysis of target '//:ProjectRunner' failed; build aborted:
INFO: Elapsed time: 56.016s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (42 packages loaded, 705 targets configured)
root@hbsdb03:~/examples/java-tutorial # bazel build //:ProjectRunner --toolchain_resolution_debug
ERROR: Expected value after --toolchain_resolution_debug
root@hbsdb03:~/examples/java-tutorial # bazel --toolchain_resolution_debug build //:ProjectRunner
[FATAL 02:13:09.011 src/main/cpp/blaze.cc:1295] Unknown startup option: '--toolchain_resolution_debug'.
  For more info, run 'bazel help startup_options'.

```

**Comment by UlasSAYGINIM** [comment]
```
root@hbsdb03:~/examples/java-tutorial # bazel build //:ProjectRunner --toolchain_resolution_debug="-.*"
INFO: Build option --toolchain_resolution_debug has changed, discarding analysis cache.
ERROR: /root/.cache/bazel/_bazel_root/9318dfd54d71a6b918f8033146aeac2a/external/bazel_tools/tools/jdk/BUILD:474:27: While resolving toolchains for target @bazel_tools//tools/jdk:remote_jdk11: no matching toolchains found for types @bazel_tools//tools/jdk:runtime_toolchain_type
ERROR: Analysis of target '//:ProjectRunner' failed; build aborted:
INFO: Elapsed time: 0.621s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 644 targets configured)


root@hbsdb03:~/examples/java-tutorial # bazel build //:ProjectRunner --verbose_failures --sandbox_debug --toolchain_resolution_debug="-.*"
ERROR: /root/.cache/bazel/_bazel_root/9318dfd54d71a6b918f8033146aeac2a/external/bazel_tools/tools/jdk/BUILD:474:27: While resolving toolchains for target @bazel_tools//tools/jdk:remote_jdk11: no matching toolchains found for types @bazel_tools//tools/jdk:runtime_toolchain_type
ERROR: Analysis of target '//:ProjectRunner' failed; build aborted:
INFO: Elapsed time: 0.473s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 138 targets configured)



```
