### ISSUE TITLE
osx_cc_wrapper.sh wrongly treats the Mac magic tokens (i.e. @executable_path, @loader_path, @rpath) as parameter files

### ISSUE THREAD

**Issue by saltylin** [bazelbuild/bazel#15069]
### Description of the problem / feature request:

osx_cc_wrapper.sh treats every parameter in form of @* as a parameter file. However, some external libraries (like `zstd`)
built with rules_foreign_cc may include the Mac magic tokens (i.e. `@executable_path`, `@loader_path`, `@rpath`) as trivial
parameters. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build `zstd-1.5.2` with `rules_foreign_cc-0.7.1` `cmake`

### What operating system are you running Bazel on?

Mac OS X

### What's the output of `bazel info release`?

release 5.0.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/bazelbuild/bazel.git
6613f6fbbcf85aac0ee5865d7d5273aad2a5813a
6613f6fbbcf85aac0ee5865d7d5273aad2a5813a

###  Have you found anything relevant by searching the web?

No

**Comment by keith** [comment]
Fixed by https://github.com/bazelbuild/bazel/pull/13148

**Comment by sgowroji** [comment]
Hello @saltylin, Could you please verify the Fix mentioned in the above [comment](https://github.com/bazelbuild/bazel/issues/15069#issuecomment-1072596435) after it is reflected in the release.

**Comment by keith** [comment]
This can be closed
