### ISSUE TITLE
Misleading error message when glob expands to empty list of files

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#1507]
I moved a test target from the root of my project to a sub package and forgot to update the glob expression of my sources (was `glob(["src/test/java/com/example/*.java"])` and should have been changed to `glob(["*.java"])` after the move).

When I ran the build I got an error message which IMHO is somewhat misleading.
The error message says that `deps` is not allowed without `srcs` and suggests to move them to `runtime_deps`. Only after a bit of digging I realized that the glob expanded to an empty list and so Bazel thinks I did not declare any sources. Problem is that when you "statically" look at the target you see that `srcs` is defined.

```
ERROR: /Users/ittaiz/workspace/bazel-playground/java-getting-started/src/test/java/com/example/BUILD:5:12: in deps attribute of java_test rule //src/test/java/com/example:hola: deps not allowed without srcs; move to runtime_deps?
```

WDYT about adding to the error message something which says that maybe the `srcs` is defined but is actually empty?

**Comment by kchodorow** [comment]
Good idea.

**Comment by ittaiz** [comment]
If you want a PR I'd be happy to give it a try given a pointer to the relevant place.
In any case this isn't in a hurry for me.

**Comment by kchodorow** [comment]
Thanks! Should just be adding another `isExplicitlySpecified` to https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/java/JavaCommon.java#L567.

**Comment by ittaiz** [comment]
So you're talking about changing the implementation and not the error message, right?
replace
`&& ruleContext.attributes().get("srcs", BuildType.LABEL_LIST).isEmpty()`
with 
`&& !ruleContext.getRule().isAttributeValueExplicitlySpecified("srcs")`?

**Comment by kchodorow** [comment]
I think you'd need to add the `&& !ruleContext.getRule().isAttributeValueExplicitlySpecified("srcs")` clause, you still need the `isEmpty()` check.  I haven't tested it or anything, though.

**Comment by ittaiz** [comment]
ok, will handle it from here.
Thanks!

**Comment by laurentlb** [comment]
This will change with https://github.com/bazelbuild/bazel/issues/8195

In the future, the glob function will fail if the pattern doesn't match anything. This will help you find the bug quickly in this case (the attribute `allow_empty` lets you opt in the old behavior).
