### ISSUE TITLE
Text Block syntax unsupported by turbine, making valid java 15 syntax fail bazel build

### ISSUE THREAD

**Issue by nresare** [bazelbuild/bazel#15083]
### Description of the problem / feature 

The java Text Block was landed as JEP 378 in Java 15. Unfortunately, it seems all recent versions of bazel fails to accept the text block syntax when the turbine header compiler is used.

Looking at the main branch of the [turbine lexer](https://github.com/google/turbine/blob/main/java/com/google/turbine/parse/StreamLexer.java#L411), it is clear that it does not have support for Text Blocks and will fail parsing any input java file containing the new syntax.

A workaround for now is to add the `--nojava_header_compilation` command line option.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Any bazel build invocation which invokes the turbine header compiler on a file that contains a JEP 378 style text block will illustrate the problem. For example if a `java_binary` target depends on a `java_library` target which has a text block in one of it's source files. I created https://github.com/nresare/bazel-multiline-problem as a minimal test project.

```bash
$ git clone https://github.com/nresare/bazel-multiline-problem
$ bazelisk build //:test
```

Expected outcome: successful build
Actual outcome: 
```bash
error executing command external/remotejdk17_macos_aarch64/bin/java '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 36 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Multiline.java:2: error: unterminated string literal
    String s = """
                  ^
<snip>
```

### What operating system are you running Bazel on?

MacOS 12.3, MacBook Air M1

### What's the output of `bazel info release`?

release 5.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

This problem is also visible when building from lastest master, I tried just now with 00d74ff737cccd60305ee58d85313556a077152a

### What's the output of `git remote get-url origin ; git rev-parse main ; git rev-parse HEAD` ?

```
$ git remote get-url origin ; git rev-parse main ; git rev-parse HEAD
git@github.com:nresare/bazel-multiline-problem.git
e9b12dbf08c12974c0f76fcd2dd40d6c40bc15f3
e9b12dbf08c12974c0f76fcd2dd40d6c40bc15f3
```

###  Have you found anything relevant by searching the web?

I did a casual search among the issues, but failed to find this reported previously.

**Comment by comius** [comment]
Our current [tests](https://cs.opensource.google/bazel/bazel/+/master:src/test/shell/bazel/bazel_java17_test.sh;l=112-137;drc=c81e175a42e17d084a5975a2d5dd4e4057f12689) are only covering java_binary, which doesn't cover turbine.

As soon as text block is in a library, turbine breaks.

cc @cushon

**Comment by vorburger** [comment]
FTR: It looks like this regressed; it appears to be broken (still or again; haven't tested) at least in Bazel 7.0.0 & 7.0.2.

**Comment by cushon** [comment]
> FTR: It looks like this regressed; it appears to be broken (still or again; haven't tested) at least in Bazel 7.0.0 & 7.0.2.

This bug is about text blocks, which is a different language feature from string templates. I responded in https://github.com/bazelbuild/bazel/issues/21119
