### ISSUE TITLE
Compile Warning -Wreturn-type

### ISSUE THREAD

**Issue by Phhere** [bazelbuild/bazel#1508]
I tried to compile bazel from master@ca8db60193b93968902a5c25f3786a8d0e71268c and got a gcc warning about return type.

`INFO: From Compiling src/main/cpp/blaze_util_posix.cc:
src/main/cpp/blaze_util_posix.cc: In function 'std::__cxx11::string blaze::RunProgram(const string&, const std::vector<std::__cxx11::basic_string<char> >&)':
src/main/cpp/blaze_util_posix.cc:199:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
`

I am using gcc 6.1.0 on Redhat 6.7

**Comment by kchodorow** [comment]
Yeah, we should fix those.  Control literally cannot reach the end of that function, so it's not actually an problem, but we should supress the warning or just add a dummy return.

**Comment by abergmeier** [comment]
Is `qdie` not marked with `noreturn`?

**Comment by jin** [comment]
Closing this as the source tree has changed significantly. Please create a new issue if you're facing the same problem with the latest source tree.
