### ISSUE TITLE
`cc_test` rules trigger remote JDK download (~200 MB)

### ISSUE THREAD

**Issue by junyer** [bazelbuild/bazel#15088]
### Description of the problem / feature request:

`cc_test` rules trigger remote JDK download (~200 MB), which is undesirable when operating under constraints on storage capacity and/or network capacity. https://en.wikipedia.org/wiki/Principle_of_least_astonishment also applies.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ rm -rf $HOME/.cache/bazel
$ git clone https://github.com/google/re2.git
$ cd re2
$ bazel build //:all --experimental_repository_resolved_file=resolved.bzl
$ grep openjdk resolved.bzl
$ bazel query 'somepath(//:all, @remote_coverage_tools//:all)'
```

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

```
release 5.0.0
```

**Comment by Wyverald** [comment]
cc @comius @c-mita

**Comment by meteorcloudy** [comment]
It's seems the issue is that cc_tests unconditionally pulls those coverage tools dependencies.
https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/test/TestConfiguration.java;l=255-270
