### ISSUE TITLE
Documentation issue: Installing Bazel on macOS

### ISSUE THREAD

**Issue by wingdi** [bazelbuild/bazel#15082]
Documentation URL: https://docs.bazel.build/versions/4.2.1/install-os-x.html

https://docs.bazel.build/versions/4.2.1/install-os-x.html#install-on-mac-os-x-homebrew,  This not work. this method install the newest version, not 4.2.1.

**Comment by sgowroji** [comment]
Hello @wingdi, We have updated the latest installation [documentation](https://bazel.build/install/os-x#install-on-mac-os-x-homebrew)  and we recommend installing using [bazelisk](https://bazel.build/install/bazelisk).

**Comment by wingdi** [comment]
Ok .
