### ISSUE TITLE
Pushing docker images to GCR fails with 0.3.0

### ISSUE THREAD

**Issue by simonhorlick** [bazelbuild/bazel#1509]
If I build a docker image normally using 0.3.0 and push to the Google Container Repository I get the following error:

`gcr manifest invalid: "Failed to parse v1 compatibility"`

Not sure if this is a bazel issue, or GCR.

**Comment by kchodorow** [comment]
@mattmoor, could you take a look?

**Comment by simonhorlick** [comment]
Apologies, I've just tried this with the latest commit on master and I don't see the error any more.

**Comment by damienmg** [comment]
I bet this issue is due to GCR not handling v1 image anymore and we have a commit to support v2 format at HEAD.
