### ISSUE TITLE
`java_test` and `py_test` do not collect `cc_binary` coverage

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#15098]
### Description of the problem / feature request:

Any `java_test` or `py_test` that executes a `cc_binary` at runtime will not report coverage for the `cc_binary`'s sources.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Reproducers are available as integration tests [for Java](https://github.com/bazelbuild/bazel/pull/15096/files#diff-d83550ae3a6908b17ae59f42abc9abdd916104bf3e7f525a4b7f8bf9c37d2cbc) and [Python](https://github.com/bazelbuild/bazel/pull/15097/files#diff-0fdd597c5a567d232e5b25ce87040d2292c11ed43bf7c33abe07ebac6b9b25c8).

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

5.0.0, 5.1.0rc3 (but also affects HEAD)

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

I submitted fixes as https://github.com/bazelbuild/bazel/pull/15096 (Java) and https://github.com/bazelbuild/bazel/pull/15097 (Python).

Individual test targets can work around this issue by adding:
```python
*_test(
    ...,
    data = [
        ...,
        "@bazel_tools//tools/test:collect_cc_coverage.sh"
    ],
    env = {
        ...,
        "CC_CODE_COVERAGE_SCRIPT": "$$RUNFILES_DIR/$$TEST_WORKSPACE/$(execpath @bazel_tools//tools/test:collect_cc_coverage.sh)",
    },
)
```

**Comment by fmeum** [comment]
@bazel-io fork

**Comment by brentleyjones** [comment]
@bazel-io flag

**Comment by ckolli5** [comment]
@bazel-io fork 5.2.0
