### ISSUE TITLE
Provide `interface_library` for `cc_binary` with `linkshared = False`

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#15107]
### Description of the problem / feature request:

On Windows, dynamically linking a DLL against dynamic symbols exported by a binary requires an interface library, but it does seem like Bazel only populates the `"interface_library"` output group of a `cc_binary` with `linkshared = True`. When the `cc_binary` represents an executable, the output group is always empty.

I have prepared a failing integration test for this feature request at https://github.com/bazelbuild/bazel/pull/15105.

If creating interface libraries for every `cc_binary` (the overwhelming majority of which will not export symbols dynamically) should not be an option, maybe a feature could be introduced to selectively enable this functionality.

### Feature requests: what underlying problem are you trying to solve with this feature?

Over at [Jazzer](https://github.com/CodeIntelligenceTesting/jazzer), we have a real need for this feature: Jazzer consists of an executable that invokes a JVM via the Java Invocation API and heavily relies on JNI to let Java code call back into the binary. However, certain performance optimizations offered by the JVM are only available to native functions contained in shared libraries loaded using `System.loadLibrary()`, so Jazzer also ships shared libraries. But in order for these libraries to reference symbols in the main binary, the shared libraries have to be explicitly linked against the main executable on Windows. Due to Bazel's inability to create the required interface_library, we currently can't enable the performance optimization on Windows.

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

5.0.0/5.1.0rc3/HEAD

###  Have you found anything relevant by searching the web?

A potential workaround based on `shadowed_action` has been suggested [on Slack](https://bazelbuild.slack.com/archives/CGA9QFQ8H/p1647277088870169?thread_ts=1647078702.320449&cid=CGA9QFQ8H), but I haven't been able to flesh out the details yet. It does seem rather complicated.

**Comment by fmeum** [comment]
@meteorcloudy It looks like you wrote most of the integration tests for Windows dynamic linking. If you provide some pointers, I could look into providing a PR.

**Comment by meteorcloudy** [comment]
Hmm, this seems to be a very rare use case? I didn't even know that you could link to a .exe binary. @oquenchil is now the C++ rule expert, I'll let him decide whether we should support this.

If we do, we probably need to change the code here: https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/cpp/CcBinary.java;l=892-896
And also the C++ rules are being starlarkified, so maybe something in https://cs.opensource.google/bazel/bazel/+/master:src/main/starlark/builtins_bzl/common/cc/cc_binary.bzl also have to change?

However, maybe you can work around it by creating an identical cc_binary with linkshared = True and use the [win_def_file](https://docs.bazel.build/versions/main/be/c-cpp.html#cc_binary.win_def_file) attribute to pass [a DEF file](https://docs.microsoft.com/en-us/cpp/build/exporting-from-a-dll-using-def-files?redirectedfrom=MSDN&view=msvc-170) that contains
```
LIBRARY   foo.exe
```
this way the interface library you get from the new cc_binary should point to the .exe file as the target DLL, but still have the same symbols exported. However, I haven't tested if linking to a .exe file work, but I assume it does?

**Comment by meteorcloudy** [comment]
Did a quick test, it seems it works, the generated interface library are identical:
```
pcloudy@PCLOUDY2-W C:\tools\msys64\home\pcloudy\workspace\bazel
$ git diff
diff --git a/examples/cpp/BUILD b/examples/cpp/BUILD
index 3048a0d48e..c2064f5a19 100644
--- a/examples/cpp/BUILD
+++ b/examples/cpp/BUILD
@@ -6,6 +6,14 @@ cc_library(
     hdrs = ["hello-lib.h"],
 )

+cc_binary(
+    name = "hello-world_shared",
+    srcs = ["hello-world.cc"],
+    deps = [":hello-lib"],
+    linkshared = True,
+    win_def_file = ":def_file.def",
+)
+
 cc_binary(
     name = "hello-world",
     srcs = ["hello-world.cc"],
diff --git a/examples/cpp/hello-world.cc b/examples/cpp/hello-world.cc
index be435c3256..b81bd7d891 100644
--- a/examples/cpp/hello-world.cc
+++ b/examples/cpp/hello-world.cc
@@ -5,6 +5,8 @@
 using hello::HelloLib;
 using std::string;

+__declspec(dllexport) int foo = 1;
+
 /**
  * This prints "Hello world". If it is run with arguments, it will use the first
  * argument instead of "world". Build and run //examples/cpp:hello-world to see

pcloudy@PCLOUDY2-W C:\tools\msys64\home\pcloudy\workspace\bazel
$ sha256sum bazel-out/x64_windows-fastbuild/bin/examples/cpp/hello-world.lib
e8d80dc8fa84c59ff7257b7884e8357b0bed73cad5d45d890349b830364f97a5 *bazel-out/x64_windows-fastbuild/bin/examples/cpp/hello-world.lib

pcloudy@PCLOUDY2-W C:\tools\msys64\home\pcloudy\workspace\bazel
$ sha256sum bazel-out/x64_windows-fastbuild/bin/examples/cpp/hello-world_shared.if.lib
e8d80dc8fa84c59ff7257b7884e8357b0bed73cad5d45d890349b830364f97a5 *bazel-out/x64_windows-fastbuild/bin/examples/cpp/hello-world_shared.if.lib
```

**Comment by fmeum** [comment]
Thanks for the pointers and the workaround. I will give it a try in Jazzer.

**Comment by fmeum** [comment]
@meteorcloudy I turned your idea into a macro that works very well for my use cases. I'm sharing it here in the hope that it will be useful for others that run into this rare situation. 

I will close the issue as I think that more direct Bazel support isn't needed and wouldn't even be that useful: Since linking to an interface library creates a dependency of the dynamic library on the executable, the executable wouldn't be able to data-depend on the library. Even with executable support added to the `interface_library` output group, a macro and target duplication would probably still be needed to prevent a cyclic dependency.

```starlark
load("@bazel_skylib//rules:write_file.bzl", "write_file")

def cc_interface_binary(
        name,
        win_exports,
        win_lib_name = None,
        data = None,
        tags = None,
        visibility = None,
        **kwargs):
    dll_name = "_%s_dll" % name
    win_def_name = "_%s_def" % name
    win_def_file_name = "%s.def" % name
    interface_filegroup_name = "_%s.if" % name
    interface_import_name = "%s.if" % name

    def_library_name = (win_lib_name or name) + ".exe"
    write_file(
        name = win_def_name,
        out = win_def_file_name,
        content = [
            "LIBRARY   " + def_library_name,
            "EXPORTS",
        ] + [
            "   {symbol}   @{id}".format(
                id = id,
                symbol = symbol,
            )
            for id, symbol in enumerate(win_exports, 1)
        ],
        tags = ["manual"],
    )

    native.cc_binary(
        name = name,
        data = data,
        tags = tags,
        visibility = visibility,
        win_def_file = ":" + win_def_name,
        **kwargs
    )

    # Intentionally omits data so that the main binary target can data-depend on
    # a shared library dynamically linked against it without creating a cyclic
    # dependency.
    native.cc_binary(
        name = dll_name,
        linkshared = True,
        tags = ["manual"],
        visibility = ["//visibility:private"],
        win_def_file = ":" + win_def_name,
        **kwargs
    )

    native.filegroup(
        name = interface_filegroup_name,
        srcs = [":" + dll_name],
        output_group = "interface_library",
        tags = ["manual"],
        visibility = ["//visibility:private"],
    )

    native.cc_import(
        name = interface_import_name,
        interface_library = ":" + interface_filegroup_name,
        system_provided = True,
        tags = ["manual"],
        visibility = visibility,
    )

```
