### ISSUE TITLE
GitHub codeowners group not working

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#15101]
It looks like the rules apple team who is supposed to be an owner of some of the objc logic is not working correctly

https://github.com/bazelbuild/bazel/pull/14844#issuecomment-1061239960

You can see github reporting errors on https://github.com/bazelbuild/bazel/pull/14614/files

I believe it's because the team doesn't include the bazel repo https://github.com/orgs/bazelbuild/teams/rules_apple-team/repositories, and I wonder what level of access the team would have to have for this to work, if just "read" would be enough or not.

@aiuto can you debug? I assume you need admin access to fix anything here

**Comment by aiuto** [comment]
I'm about to do an audit and clean up of lots of group memberships. I'll check as part of that.

**Comment by keith** [comment]
@aiuto bump

**Comment by aiuto** [comment]
Sorry. I did not get a chance to look at this. But it really does belong to @meteorcloudy\'s team, so passing it to him.

**Comment by meteorcloudy** [comment]
@keith Added read access to Bazel repo for rules apple team, let me know if it works.

**Comment by brentleyjones** [comment]
I'm thinking write access is what will be needed:

> Unknown owner on line 34: make sure the team `@bazelbuild/rules_apple-team` exists, is publicly visible, and has **write access to the repository**.

**Comment by meteorcloudy** [comment]
OK, this should be fixed now.

**Comment by keith** [comment]
thanks!
