### ISSUE TITLE
Document attr.label_list

### ISSUE THREAD

**Issue by evmar** [bazelbuild/bazel#1510]
If you search the bazel docs for e.g. `allow_files`, you only find mention of it in example code with no description of what it means.

**Comment by kchodorow** [comment]
Quick definition: you can provide files (instead of just targets) for that attribute.  Useful for, say, a srcs field (whereas you might want all deps to be non-files).

**Comment by evmar** [comment]
I found it here: http://www.bazel.io/docs/skylark/lib/attr.html#label_list .  Lesson learned: the search box in the docs does not do anything useful.
