### ISSUE TITLE
Documentation issue: General Rules

### ISSUE THREAD

**Issue by bedbad** [bazelbuild/bazel#15110]
Documentation URL: https://docs.bazel.build/versions/main/be/general.html
"
However, Bazel (but not Bazel) passes through the value of the user's PATH environment variable.

?

**Comment by sgowroji** [comment]
Hi @bedbad, Could you please share more details with respect to your above query. Thanks!

**Comment by bedbad** [comment]
That part of documentation is incomprehensible.

**Comment by pizzaz93** [comment]
Duplicate of #13426 but the branch/link has been updated to `main`.

**Comment by sgowroji** [comment]
Closing w.r.t Dupe https://github.com/bazelbuild/bazel/issues/13426#issuecomment-1139545181.
