### ISSUE TITLE
BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 does not work for the execution platform

### ISSUE THREAD

**Issue by limdor** [bazelbuild/bazel#15120]
### Description of the problem / feature request:

BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 prevents taking the autodetected toolchain for the target platform but not for the execution platform.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I'm trying to make sure that our project use only hermetic toolchains, I would expect that BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 can be used for that but it seems to work only for the target platform and not for the execution platform.

### What operating system are you running Bazel on?

Ubuntu 20.04

### What's the output of `bazel info release`?

4.2.2

###  Have you found anything relevant by searching the web?

I could not find anywhere proper documentation of BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN to say if it is really intended or it is a bug. I took a look in https://github.com/bazelbuild/bazel/issues/7260 that is closely related but does not say a lot about BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN.

There is also https://github.com/bazelbuild/bazel/issues/12712 but there I would say it is expected because BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN is not use but also use the old way to use toolchains.

**Comment by limdor** [comment]
@bazelbuild/triage, with this bug BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 is not very useful. Please keep the issue.

**Comment by fmeum** [comment]
I could look into this, but I do not really understand the issue. 

@limdor Could you provide steps to reproduce the undesired behavior?
