### ISSUE TITLE
`@bazel_tools`'s `unix_cc_configure.bzl` breaks when other link opts contain `lld`

### ISSUE THREAD

**Issue by rrbutani** [bazelbuild/bazel#15126]
## Problem

When creating [`@local_config_cc` during autoconfiguration](https://github.com/bazelbuild/bazel/blob/0ba4caa5fc4bfd2d7f9af2a1653ef5b4bd83d176/tools/cpp/cc_configure.bzl#L125), `unix_cc_configure.bzl`'s [`_find_linker_path`](https://github.com/bazelbuild/bazel/blob/0ba4caa5fc4bfd2d7f9af2a1653ef5b4bd83d176/tools/cpp/unix_cc_configure.bzl#L174-L218) is used to parse [`-v` command line output from a compiler invocation](https://github.com/bazelbuild/bazel/blob/0ba4caa5fc4bfd2d7f9af2a1653ef5b4bd83d176/tools/cpp/unix_cc_configure.bzl#L197) to figure out if [`lld`/`gold` are present](https://github.com/bazelbuild/bazel/blob/0ba4caa5fc4bfd2d7f9af2a1653ef5b4bd83d176/tools/cpp/unix_cc_configure.bzl#L421-L422) and what their paths are.

The parsing essentially looks for the [first space separated occurrence of the linker name](https://github.com/bazelbuild/bazel/blob/0ba4caa5fc4bfd2d7f9af2a1653ef5b4bd83d176/tools/cpp/unix_cc_configure.bzl#L208-L210) in the [first line containing the linker name](https://github.com/bazelbuild/bazel/blob/0ba4caa5fc4bfd2d7f9af2a1653ef5b4bd83d176/tools/cpp/unix_cc_configure.bzl#L205-L207) in the verbose output and then [strips spaces and quotes from it](https://github.com/bazelbuild/bazel/blob/0ba4caa5fc4bfd2d7f9af2a1653ef5b4bd83d176/tools/cpp/unix_cc_configure.bzl#L213).

The [compiler invocation](https://github.com/bazelbuild/bazel/blob/0ba4caa5fc4bfd2d7f9af2a1653ef5b4bd83d176/tools/cpp/unix_cc_configure.bzl#L186-L198) is essentially: `$CXX -xc - <<<"int main() {}" -o /dev/null -Wl,--start-lib -Wl,--end-lib -fuse-ld=$linker`.

All together that's essentially:
```bash
$CXX -xc++ - <<<"int main() {}" -o /dev/null -Wl,--start-lib -Wl,--end-lib -fuse-ld=$linker -v \
  |& grep $linker \
  | xargs -n 1 \
  | grep $linker \
  | tr -d ' ''"'"'" \
  | head -1
```

The problem is that this can potentially isolate things other than the path to the linker.

I ran into this issue when using a [nix-shell](https://nixos.org/manual/nix/stable/command-ref/nix-shell.html) with `lldb` present; `nix` by default [wraps](https://github.com/NixOS/nixpkgs/tree/master/pkgs/build-support/cc-wrapper) its compilers (including the compiler it exposes as `$CC` and `$CXX` which Bazel's cc toolchain autoconfiguration picks up by default to make `@local_config_cc`) in a shell script that adds the contents of `$NIX_LDFLAGS` (and other env vars) to the actual compiler invocation.

In its verbose output, `clang` prints out the actual compiler invocation; `_find_linker_path` interprets the `-L` include that `nix`'s wrapper adds to the invocation for `lldb`'s library files to be the linker path.

This manifests in compile errors on `cc_binary`s that look like:
```
INFO: Found 1 target...
ERROR: .../BUILD.bazel:127:10: Linking <some_target> [for host] failed: (Exit 1): clang failed: error executing command /nix/store/q52j3nyvc8947za806109xrxaz4dqdzf-clang-wrapper-13.0.0/bin/clang @bazel-out/host/bin/external/some/target.params

Use --sandbox_debug to see verbose messages from the sandbox
clang-13: error: invalid linker name in argument '-fuse-ld=/nix/store/izgkyvmb4m35pary1blnpypa9l9j059y-lldb-13.0.0-dev/include'
```

### Using a `nix-shell`

In `nix-shell -p bazelisk -p lldb -p llvmPackages_13.bintools -p llvmPackages_13.clang`:
```bash
cd $(mktemp -d)
touch WORKSPACE
echo "int main() { return 3; }" >> main.cc
echo "5.0.0" >> .bazelversion
cat <<EOF > BUILD.bazel
cc_binary(
  name = "test",
  srcs = ["main.cc"],
)
EOF

export BAZEL_USE_CPP_ONLY_TOOLCHAIN=1
bazelisk build --action_env=CC=clang --action_env=CXX=clang++ //:test -s
````

Note the use of `bazelisk` to get Bazel 5.0+; [this commit](https://github.com/bazelbuild/bazel/commit/00e30ca5968d42b4a1e42327fa683debc1063b89) introduces the use of `lld` in autoconfiguration and it landed in Bazel 5.0.

Also note that this is currently not reproducible on macOS on arm64, [even with `BAZEL_USE_CPP_ONLY_TOOLCHAIN=1`](https://github.com/bazelbuild/bazel/blob/be21f194ae00d1a21e8e36a6fbb30be9e449086c/tools/cpp/cc_configure.bzl#L121-L125), because of a [bug in `nix`'s cc-wrapper](https://github.com/NixOS/nixpkgs/issues/154203) that causes it to error when attempting to sign the output "file" (`/dev/null`). Thus, `lld` and `gold` are just not used by Bazel in these cases since the compiler invocation fails.

### The Verbose Output

Alternatively, here is the output of `clang++ -xc++ - <<<"int main() {}" -o /dev/null -Wl,--start-lib -Wl,--end-lib -fuse-ld=lld -v` in such a shell:
<details> <summary>Click to expand (grep for "lld")</summary>

```
clang version 13.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /nix/store/qrmngdzjyvl4qdr049dwnslrh462am3z-clang-13.0.0/bin
Found candidate GCC installation: /nix/store/mlfy9ifzszg7z2q6aiblvm5qkfn3bmwb-gcc-10.3.0/lib/gcc/x86_64-unknown-linux-gnu/10.3.0
Found candidate GCC installation: /nix/store/mlfy9ifzszg7z2q6aiblvm5qkfn3bmwb-gcc-10.3.0/lib64/gcc/x86_64-unknown-linux-gnu/10.3.0
Selected GCC installation: /nix/store/mlfy9ifzszg7z2q6aiblvm5qkfn3bmwb-gcc-10.3.0/lib64/gcc/x86_64-unknown-linux-gnu/10.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/nix/store/qrmngdzjyvl4qdr049dwnslrh462am3z-clang-13.0.0/bin/clang-13" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj --mrelax-relocations -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=none -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -v -fcoverage-compilation-dir=/run/user/12064113/tmp.sqsgMmvY2k -nostdsysteminc -resource-dir /nix/store/pbfj9cqpg9m1x64jq9fj8q4fardqmk2q-clang-wrapper-13.0.0/resource-root -idirafter /nix/store/sr2bm5pp15dhb80w16vrwyhgh40kd4yf-glibc-2.33-59-dev/include -isystem /nix/store/vbbk1rqm9na1czcggw25s6j4z95jx9wl-lldb-13.0.0-dev/include -isystem /nix/store/mp5y1kdgslrn1nxpk3s04dlgqd8almh3-compiler-rt-libc-13.0.0-dev/include -isystem /nix/store/vbbk1rqm9na1czcggw25s6j4z95jx9wl-lldb-13.0.0-dev/include -isystem /nix/store/mp5y1kdgslrn1nxpk3s04dlgqd8almh3-compiler-rt-libc-13.0.0-dev/include -isystem /nix/store/vbbk1rqm9na1czcggw25s6j4z95jx9wl-lldb-13.0.0-dev/include -isystem /nix/store/mp5y1kdgslrn1nxpk3s04dlgqd8almh3-compiler-rt-libc-13.0.0-dev/include -isystem /nix/store/mlfy9ifzszg7z2q6aiblvm5qkfn3bmwb-gcc-10.3.0/include/c++/10.3.0 -isystem /nix/store/mlfy9ifzszg7z2q6aiblvm5qkfn3bmwb-gcc-10.3.0/include/c++/10.3.0/x86_64-unknown-linux-gnu -D _FORTIFY_SOURCE=2 -internal-isystem /nix/store/mlfy9ifzszg7z2q6aiblvm5qkfn3bmwb-gcc-10.3.0/lib64/gcc/x86_64-unknown-linux-gnu/10.3.0/../../../../include/c++/10.3.0 -internal-isystem /nix/store/mlfy9ifzszg7z2q6aiblvm5qkfn3bmwb-gcc-10.3.0/lib64/gcc/x86_64-unknown-linux-gnu/10.3.0/../../../../include/c++/10.3.0/x86_64-unknown-linux-gnu -internal-isystem /nix/store/mlfy9ifzszg7z2q6aiblvm5qkfn3bmwb-gcc-10.3.0/lib64/gcc/x86_64-unknown-linux-gnu/10.3.0/../../../../include/c++/10.3.0/backward -internal-isystem /nix/store/pbfj9cqpg9m1x64jq9fj8q4fardqmk2q-clang-wrapper-13.0.0/resource-root/include -O2 -Wformat -Wformat-security -Werror=format-security -fdeprecated-macro -fdebug-compilation-dir=/run/user/12064113/tmp.sqsgMmvY2k -ferror-limit 19 -fwrapv -stack-protector 2 -stack-protector-buffer-size 4 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -vectorize-loops -vectorize-slp -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /run/user/12064113/--158e23.o -x c++ -
clang -cc1 version 13.0.0 based upon LLVM 13.0.0 default target x86_64-unknown-linux-gnu
ignoring duplicate directory "/nix/store/vbbk1rqm9na1czcggw25s6j4z95jx9wl-lldb-13.0.0-dev/include"
ignoring duplicate directory "/nix/store/mp5y1kdgslrn1nxpk3s04dlgqd8almh3-compiler-rt-libc-13.0.0-dev/include"
ignoring duplicate directory "/nix/store/vbbk1rqm9na1czcggw25s6j4z95jx9wl-lldb-13.0.0-dev/include"
ignoring duplicate directory "/nix/store/mp5y1kdgslrn1nxpk3s04dlgqd8almh3-compiler-rt-libc-13.0.0-dev/include"
ignoring duplicate directory "/nix/store/mlfy9ifzszg7z2q6aiblvm5qkfn3bmwb-gcc-10.3.0/include/c++/10.3.0"
ignoring duplicate directory "/nix/store/mlfy9ifzszg7z2q6aiblvm5qkfn3bmwb-gcc-10.3.0/include/c++/10.3.0/x86_64-unknown-linux-gnu"
#include "..." search starts here:
#include <...> search starts here:
 /nix/store/vbbk1rqm9na1czcggw25s6j4z95jx9wl-lldb-13.0.0-dev/include
 /nix/store/mp5y1kdgslrn1nxpk3s04dlgqd8almh3-compiler-rt-libc-13.0.0-dev/include
 /nix/store/mlfy9ifzszg7z2q6aiblvm5qkfn3bmwb-gcc-10.3.0/include/c++/10.3.0
 /nix/store/mlfy9ifzszg7z2q6aiblvm5qkfn3bmwb-gcc-10.3.0/include/c++/10.3.0/x86_64-unknown-linux-gnu
 /nix/store/mlfy9ifzszg7z2q6aiblvm5qkfn3bmwb-gcc-10.3.0/lib64/gcc/x86_64-unknown-linux-gnu/10.3.0/../../../../include/c++/10.3.0/backward
 /nix/store/pbfj9cqpg9m1x64jq9fj8q4fardqmk2q-clang-wrapper-13.0.0/resource-root/include
 /nix/store/sr2bm5pp15dhb80w16vrwyhgh40kd4yf-glibc-2.33-59-dev/include
End of search list.
 "/nix/store/kcg1vn8a2xf0fzd789fq16mww4wqvg0n-llvm-binutils-wrapper-13.0.0/bin/ld.lld" -z relro --hash-style=gnu --hash-style=both --enable-new-dtags --eh-frame-hdr -m elf_x86_64 -o /dev/null /nix/store/s9qbqh7gzacs7h68b2jfmn9l6q4jwfjz-glibc-2.33-59/lib/crt1.o /nix/store/s9qbqh7gzacs7h68b2jfmn9l6q4jwfjz-glibc-2.33-59/lib/crti.o /nix/store/mlfy9ifzszg7z2q6aiblvm5qkfn3bmwb-gcc-10.3.0/lib/gcc/x86_64-unknown-linux-gnu/10.3.0/crtbegin.o -L/nix/store/lhimspyyv7cg448gzdjzin05jm4xisp9-lldb-13.0.0-lib/lib -L/nix/store/lhimspyyv7cg448gzdjzin05jm4xisp9-lldb-13.0.0-lib/lib -L/nix/store/lhimspyyv7cg448gzdjzin05jm4xisp9-lldb-13.0.0-lib/lib -L/nix/store/lhimspyyv7cg448gzdjzin05jm4xisp9-lldb-13.0.0-lib/lib -L/nix/store/s9qbqh7gzacs7h68b2jfmn9l6q4jwfjz-glibc-2.33-59/lib -L/nix/store/mlfy9ifzszg7z2q6aiblvm5qkfn3bmwb-gcc-10.3.0/lib/gcc/x86_64-unknown-linux-gnu/10.3.0 -L/nix/store/lwkpcfphv5nwymi0bvnvfga6q4p72v8i-gcc-10.3.0-lib/x86_64-unknown-linux-gnu/lib -L/nix/store/svzwv5yhcp03rysmc0lh5922a6f7qgp8-clang-13.0.0-lib/lib -L/nix/store/mlfy9ifzszg7z2q6aiblvm5qkfn3bmwb-gcc-10.3.0/lib64/gcc/x86_64-unknown-linux-gnu/10.3.0 -L/nix/store/mlfy9ifzszg7z2q6aiblvm5qkfn3bmwb-gcc-10.3.0/lib64/gcc/x86_64-unknown-linux-gnu/10.3.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/nix/store/qrmngdzjyvl4qdr049dwnslrh462am3z-clang-13.0.0/bin/../lib -L/lib -L/usr/lib -dynamic-linker=/nix/store/s9qbqh7gzacs7h68b2jfmn9l6q4jwfjz-glibc-2.33-59/lib/ld-linux-x86-64.so.2 /run/user/12064113/--158e23.o --start-lib --end-lib -rpath /nix/store/4ibh63jd2lzx03mrhjn9km8ihha9wq55-shell/lib64 -rpath /nix/store/4ibh63jd2lzx03mrhjn9km8ihha9wq55-shell/lib -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /nix/store/mlfy9ifzszg7z2q6aiblvm5qkfn3bmwb-gcc-10.3.0/lib/gcc/x86_64-unknown-linux-gnu/10.3.0/crtend.o /nix/store/s9qbqh7gzacs7h68b2jfmn9l6q4jwfjz-glibc-2.33-59/lib/crtn.o
```

</details>

## Potential Solutions

A trivial fix would be to search for the linker name plus a space or end quote (i.e. `lld `/`lld"`/`lld'`, `gold `/`gold"`/`gold'`) or, for `lld` specifically, to search for `.lld` (afaik all the flavors of `lld` *for unix platforms* are `<something>.lld`: `ld64.lld`, `ld.lld`). This _seems_ like it'd fix this issue without relying on compiler-specific output.

Another potential solution is to only use the _last_ line of the verbose output. However, I am not sure we can rely on this always being the linker invocation, especially for compilers that aren't `clang`.

Ideally we'd just ask the compiler for the path to the linker but I don't know of any way to do so that's well supported across different compilers.

If any of these solutions are deemed a reasonable fix (or if a better path forward is proposed), I'm happy to make a PR.

## Workarounds

To anyone facing a similar issue, my workaround for now was to simply wrap the `lldb` derivation and have it use another name:
```nix
with nixpkgs; stdenvNoCC.mkDerivation {
  pname = "llvm-debugger";
  inherit (lldb) version outputs;
  lldb_outputs = lldb.all;
  src = "${lldb}";
  disallowedReferences = [lldb];
  buildPhase = ''
    i=0
    lldb_outs=($lldb_outputs)
    outs=($outputs)
    for o in "''${outs[@]}"; do
      echo "[$o]" "''${lldb_outs[$i]}" to "''${!o}"

      # can't symlink because then the paths used for `LDFLAGS` still
      # contain "lldb":
      cp -R "''${lldb_outs[$i]}" "''${!o}"
      : $((++i))
    done

    # Remove some lingering references to the actual lldb package so that it's
    # not registered as a runtime dep of this package.
    scrub() {
      local i=0
      for o in "''${outs[@]}"; do
        substituteInPlace "$1" \
          --replace "''${lldb_outs[$i]}" "''${!o}"

        : $((++i))
      done
    }

    scrub "$out/bin/lldb"
    scrub "$dev/nix-support/propagated-build-inputs"
  '';
  installPhase = "true";
}

# Alternatively the below will work too but will cause you to rebuild `lldb` from source:
# nixpkgs.lldb.overrideDerivation (o: { name = "llvm-debugger"; })
```

**Comment by keith** [comment]
It looks like I need to fixup that PR but can you test and verify your case?

**Comment by rrbutani** [comment]
@keith thank you! I totally missed your PR when I was searching the issue tracker

I haven't tried running a patched Bazel with your PR yet but I think it should work! The `-I` includes get filtered out because they aren't quoted at all and lines like these:
```
ignoring duplicate directory "/nix/store/vbbk1rqm9na1czcggw25s6j4z95jx9wl-lldb-13.0.0-dev/include"
```
are filtered because they don't _start_ with a quote.

I'll try it out later tonight just to be sure.
