### ISSUE TITLE
https://zlib.net/zlib-1.2.11.tar.gz Not Found

### ISSUE THREAD

**Issue by gkuga** [bazelbuild/bazel#15136]
### Description of the problem

It seems that http_archive tries to download the zlib, but it is Not Found and build fails. Is this related to the release of zlib 1.2.12?

```
WARNING: Download from https://zlib.net/zlib-1.2.11.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.do
wnloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'zlib':
   java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /go/src/github.com/ca-dp/bazel-cache/ex
ternal/zlib/zlib-1.2.11.tar.gz: GET returned 404 Not Found
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

We are doing bazel build on CI using bazelisk, I couldn't reproduce it on mac, would it be a work around to put zlib in the build image? Deleting the remote cache did not help. Or am I missing something else? 

### What operating system are you running Bazel on?

bazel-3.0.0-linux-x86_64
VM: Container-Optimized OS
K8s: 1.20.11-gke.1801
Image: customized build image (based on ubuntu:18.04)

**Comment by mathis98** [comment]
I have the exact same issue. Does someone know a solution?

### Description of the problem

When trying to use bazel it tries to download zlib from 'https://zlib.net/zlib-1.2.11.tar.gz' which fails with a 404.

Here is my log:

`INFO: Call stack for the definition of repository 'zlib' which is a http_archive (rule definition at /usr/ports/science/libtensorflow1/work/bazel_out/2a82c1c57c084b7f4e69f9760a9e5701/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /usr/ports/science/libtensorflow1/work/bazel_out/2a82c1c57c084b7f4e69f9760a9e5701/external/io_bazel_rules_closure/closure/repositories.bzl:1003:5
 - /usr/ports/science/libtensorflow1/work/bazel_out/2a82c1c57c084b7f4e69f9760a9e5701/external/io_bazel_rules_closure/closure/repositories.bzl:175:9
 - /usr/ports/science/libtensorflow1/work/tensorflow-1.15.5/WORKSPACE:23:1
WARNING: Download from https://zlib.net/zlib-1.2.11.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'zlib':
   java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz]to /usr/ports/science/libtensorflow1/work/bazel_out/2a82c1c57c084b7f4e69f9760a9e5701/external/zlib/zlib-1.2.11.tar.gz: GET returned 404 Not Found
INFO: Call stack for the definition of repository 'eigen_archive' which is a tf_http_archive (rule definition at /usr/ports/science/libtensorflow1/work/tensorflow-1.15.5/third_party/repo.bzl:124:19):
 - /usr/ports/science/libtensorflow1/work/tensorflow-1.15.5/tensorflow/workspace.bzl:168:5
 - /usr/ports/science/libtensorflow1/work/tensorflow-1.15.5/WORKSPACE:19:1
ERROR: /usr/ports/science/libtensorflow1/work/bazel_out/2a82c1c57c084b7f4e69f9760a9e5701/external/com_google_protobuf/BUILD:148:1: @com_google_protobuf//:protobuf depends on @zlib//:zlib in repository @zlib which failed to fetch. no such package '@zlib//': java.io.IOException: Error downloading [https://zlib.net/zlib-17f4e69f9760a9e5701/external/zlib/zlib-1.2.11.tar.gz] to /usr/ports/science/libtensorflow1/work/bazel_out/2a82c1c57c084b7f4e69f9760a9e5701/external/zlib/zlib-1.2.11.tar.gz: GET returned 404 not Found
ERROR: Analysis of target '//tensorflow/rools/lib_package:libtensorflow.tar.gz failed; build aborted: no such package '@zlib//': java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /urs/ports/science/libtensorflow1/work/bazel_out/2a82c1c57c084b7f4e69f9760a9e5701/external/zlib/zlib-1.2.11.tar.gz: GET returned 404 Not Found`

### Bugs: what's the simplest, easiest way to reproduce this bug?

I tried to install the FreeBSD port of libtensorflow which uses bazel. This fails with aforementioned error.

### What operating system are you running Bazel on?

FreeBSD 12.2-RELEASE-p13


### What's the output of `bazel info release`?

`Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'info' from /usr/local/etc/bazel/bazel.bazelrc:
  Inherited 'build' options: --strategy=Javac=standalone --host_javabase=@local_jdk//:jdk --action_env=PATH=/bin:/usr/bin/:/usr/local/bin
INFO: Reading rc options for 'info' from /usr/ports/science/libtensorflow1/work/tensorflow-1.15.5/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr/local --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --copt=-w --config=v1
INFO: Reading rc options for 'info' from /usr/ports/science/libtensorflow1/work/tensorflow-1.15.5/.tf_configure.bazelrc:
  Inherited 'build' options: --action_env PYTHON_BIN_PATH=/usr/local/bin/python3.8 --action_env PYTHON_LIB_PATH=/usr/local/lib/python3.8/site-packages --python_path=/usr/local/bin/python3.8 --define=PREFIX=/usr/local --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v1 in file /usr/ports/science/libtensorflow1/work/tensorflow-1.15.5/.bazelrc: --define=tf_api_version=1 --action_env=TF2_BEHAVIOR=0
release 0.29.0`

###  Have you found anything relevant by searching the web?

Not really. I tried changing the version manually from 1.2.11 to 1.2.12 in the workspace.bzl file but that did not work either.


I hope this helps. Let me know if you know a solution.

**Comment by gkuga** [comment]
Sorry, I found the cause of my problem. The dependency we are using was prior to this commit.

https://github.com/protocolbuffers/protobuf/commit/516f8b15603b7f7613e2fb957c55bc56a36b64a6

**Comment by gkuga** [comment]
@mathis98 

> Not really. I tried changing the version manually from 1.2.11 to 1.2.12 in the workspace.bzl file but that did not work either.

Do you need to use tensorflow v1.15.5 ? If so, v1.15.5 uses protobuf v3.8.0, and it has also zlib dependency. you may be able to specify protobuf v3.10.0 or higher to build.

**Comment by gkuga** [comment]
> I found the cause of our problem. The dependency we are using was prior to [this](https://github.com/protocolbuffers/protobuf/commit/516f8b15603b7f7613e2fb957c55bc56a36b64a6) commit. But we can't raise the dependency version for some reason, is there any other way?

I found a patching workaround in the tensorflow repository. I will rewrite the mirror URL in this way.

https://github.com/tensorflow/tensorflow/blob/48d0db92b9c87a255c1951e498662988a5c5a3e7/third_party/protobuf/protobuf.patch

I will close this Issue if no other good workaround seems to be available.

**Comment by mathis98** [comment]
Alright. Thanks for your help. I will try the patch then.
