### ISSUE TITLE
`rules_pkg` does not work with `bzlmod`

### ISSUE THREAD

**Issue by redsun82** [bazelbuild/bazel#15156]
### Description of the problem / feature request:

I cannot use `rules_pkg` when pulling the dependency via experimental `bzlmod`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See this minimal example:

https://github.com/redsun82/bzlmod-rules_pkg-problem

When running

```
bazel build :archive
```
I get
```
ERROR: Analysis of target '//:archive' failed; build aborted: no such package '@rules_pkg.0.5.1//private': The repository '@rules_pkg.0.5.1' could not be resolved: Repository '@rules_pkg.0.5.1' is not visible from repository '@'
```

### What operating system are you running Bazel on?

Ubuntu 21.10

### What's the output of `bazel info release`?

release 5.1.0

###  Have you found anything relevant by searching the web?

I could not find something specifically related to my problem.

### Any other information, logs, or outputs that you want to share?

I suspect this has to do with an issue with `bzlmod` and not with `rules_pkg`, because if I download and extract the `rules_pkg` archive indicated by the [bazel central registry](https://github.com/bazelbuild/bazel-central-registry/blob/main/modules/rules_pkg/0.5.1/source.json), I add there the [`MODULE.bazel`](https://github.com/bazelbuild/bazel-central-registry/blob/main/modules/rules_pkg/0.5.1/MODULE.bazel) also from the registry, and then add a `local_path_override`, the problem disappears.

**Comment by meteorcloudy** [comment]
I think you are hitting https://github.com/bazelbuild/bazel/issues/14259

We have fixed the issue from the Bazel side, but we'll need to fix rules_pkg as well. 

/cc @fmeum

**Comment by meteorcloudy** [comment]
Essentially in pkg/private/tar/tar.bzl:
We should change:
`_stamp_condition = str(Label("//pkg/private:private_stamp_detect"))` -> `_stamp_condition = Label("//pkg/private:private_stamp_detect")`

/cc @aiuto 

In the meantime, we can add a patch file in the BCR for rules_pkg 0.5.1

**Comment by meteorcloudy** [comment]
After https://github.com/bazelbuild/bazel-central-registry/pull/75, it should work with Bazel 5.1 or later.

**Comment by aiuto** [comment]
I am really confused as to how the internals of the rule set impact bzlmod.
It looks like you end up with a reference to ***@***.***_pkg.0.5.1//private'.
That seems like a problem. Why doesn't this manifest in the WORKSPACE
as ***@***.***_pkg'
instead of ***@***.***_pkg.0.5.1"?

With that patch in place does the --stamp flag still work?

**Comment by meteorcloudy** [comment]
@aiuto The context is https://github.com/bazelbuild/bazel/issues/14259
