### ISSUE TITLE
git_repository .sh is losing +x permission

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1515]
See https://github.com/bazelbuild/rules_closure/issues/113. Seems like something related to environment, I can't reproduce locally (and neither can @gramic).

**Comment by kchodorow** [comment]
99% sure this is jGit issue.  I recommend working around it by downloading the rules_closure .zip (or whatever) as a http_archive:

```
http_archive(
    name = "io_bazel_rules_closure",
    url = "https://github.com/bazelbuild/rules_closure/archive/0.2.3.zip",
)
```

**Comment by gramic** [comment]
After replacing git_repository with your suggestion it works correctly every time.

**Comment by kchodorow** [comment]
Cool, glad to hear it.

**Comment by damienmg** [comment]
@kchodorow: can we actually get this fixed, or should we start deprecating the native instead?

Also ping @davidzchen.

**Comment by davidzchen** [comment]
I think we should deprecate the native implementation and move to the Skylark one. I don't think we would want to be maintaining jgit in addition to the rules.

**Comment by damienmg** [comment]
Ok closing as obsolete then.

Please use the new git repository rules with:

```python
load("@bazel_tools//tools/build_defs/repo:git_repositories.bzl", git_repository="new_git_repository")
```
