### ISSUE TITLE
Avoid creating test runfile trees when using sandboxfs

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/bazel#15153]
### Description of the problem / feature request:

Avoid creating test runfile trees when using sandboxfs.

### Feature requests: what underlying problem are you trying to solve with this feature?

The entire point of sandboxfs is avoiding creating symlinks.

But when running `bazel test`, the symlink tree is created anyway. This seems unnecessary, no?

**Comment by sgowroji** [comment]
Hello @pauldraper,  Could you please provide more details with respect to your query. Thanks!

**Comment by pauldraper** [comment]
Even with sandboxfs being used, runfiles trees are still being created in the output root.

**Comment by larsrc-google** [comment]
Possibly related to issue #7470. 

Could you show a command line that prompts this behaviour, and what you're seeing that you didn't expect? A couple of tries didn't get me to get sandboxfs to work for tests at all.

**Comment by pauldraper** [comment]
**WORKSPACE.bazel**

```bzl
workspace(name = "example")
```

**BUILD.bazel**

```bzl
sh_binary(
  name = "test",
  data = ["data.txt"],
  srcs = ["test.sh"],
)
```

**test.sh**

```sh
#!/bin/sh
```

**data.txt**

```txt
```

Run

```sh
bazel  test --experimental_use_sandboxfs :test
```

Notice that the symlink `bazel-bin/test.runfiles/example/data.txt` is created. If there are many files (scripting languages, external dependencies, end-to-end tests, etc), the runfile tree can take a long time to populate.

Sandboxfs (when enabled) could be used to avoid materializing the runfile tree.

**Comment by benjaminp** [comment]
217fafe2b492de7349547cc3be2b9eef38628055

**Comment by tjgq** [comment]
FYI, we do have a flag to suppress the creation of runfile symlink trees (`--nobuild_runfile_links`). This is orthogonal to sandboxing, because the purpose of sandboxing is not to manage the output tree, but to create a hermetic environment separate from the output tree where an action can run.
