### ISSUE TITLE
bazel does not build with latest macOS gcc

### ISSUE THREAD

**Issue by nresare** [bazelbuild/bazel#15168]
### Description of the problem / feature request:

Since Apple charmingly combines their security and feature updates, it is important to be on the latest released version of their operating system and Xcode command line tools. A recent upstream update seems to have broken the ability to compile bazel.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

* Clone and attempt to build bazel with `bazel build //src:bazel` on a fully up to date macOS

Expected outcome: successful compilation

Actual outcome: 

Compilation fails with the following error: 
```
external/com_google_absl/absl/functional/function_ref.h:124:16: error: definition of implicit copy constructor for 'FunctionRef<void (absl::string_view)>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  FunctionRef& operator=(const FunctionRef& rhs) = delete;
               ^
```

### What operating system are you running Bazel on?

macOS 12.3.1 on an M1 MacBook Air
Command Line Tools for Xcode 13.2

```shell
% gcc --version
Apple clang version 13.1.6 (clang-1316.0.21.2)
Target: arm64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### What's the output of `bazel info release`?

```shell
% bazel info release
release 5.1.0
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
git@github.com:bazelbuild/bazel.git
436d04d22347fc6ee9810e50fbda8778e4c179f5
436d04d22347fc6ee9810e50fbda8778e4c179f5

The same problem manifests when checking out version 5.1.0, 93677c68f0bc688dbfa75484688160cdbdae7328

###  Have you found anything relevant by searching the web?

It seems there was a fix landed upstream that is referenced here https://github.com/abseil/abseil-cpp/issues/948

It seems from the [commit](https://github.com/abseil/abseil-cpp/commit/702cae1e762dc6f2f9d31777db04e1adbdb36697) closing the issue that there is a straight forward one line fix, but it is unclear to me how to patch this in the bazel code base.

When I update the grpc version referenced in `distdir_deps.bzl` from v1.41.1 to v1.45.1, I can no longer reproduce this problem.

**Comment by nresare** [comment]
Looking at the previous PR to update gRPC, making the switch seems to be a bit of work. https://github.com/bazelbuild/bazel/pull/15169 does the super ugly "add a patch containing a patch" but it works for me^TM and being able to compile bazel on one of the supported platforms seems like a valuable thing ¯\_(ツ)_/¯

**Comment by nresare** [comment]
I can confirm that this problem is no longer reproducible in my environment as of commit ab77bd5b81ed

Since "being able to build with latest stable release of the main platforms" seems like a pretty important thing to have, I assume that this might be something to consider doing a point release for?

**Comment by meteorcloudy** [comment]
@nresare Are you sure? b47aa71b21d93c9499103e9a37a6c2ffa79865b9 was just submitted after https://github.com/bazelbuild/bazel/commit/ab77bd5b81ed54d985a9a6da584afd3bfd4fdf09

**Comment by nresare** [comment]
Sorry, my mistake. I had my fix to the problem as a local change in my repository. 

With that out of the way, I can now confirm that the problem is indeed present with ab77bd5 but not with ab77bd5

**Comment by Wyverald** [comment]
@bazel-io fork 5.1.1
