### ISSUE TITLE
Create a way for macros to "reify" string labels into label objects

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#15172]
The immediately obvious answer seems to be "just call `Label(...)`", except that would anchor the string label at the current .bzl file's context. For a macro that receives string labels from BUILD files, it would probably want to convert string labels with the BUILD file's context. Example:

```bzl
# @myproject//pkg/BUILD
load("@myrule//myrule:defs.bzl", "mymacro")
mymacro(
    name = "mytarget",
    deps = [":hello"],  # Intended to be @myproject//pkg:hello
)
filegroup(name = "hello")


# @myrule//myrule/defs.bzl
DEFAULT_DEP = Label("//myrule:compiler")  # Always points to @myrule//myrule:compiler, regardless of repo mappings
def mymacro(name, deps):
    if DEFAULT_DEP not in deps:  # THIS LINE DOES NOT WORK
        deps += [DEFAULT_DEP]
    myrule(name, deps)
```

Here `mymacro` simply includes an extra dep before forwarding the call to `myrule`. But the check is almost never true because `deps` almost always contains only strings! We can't do `[Label(dep) for dep in deps]` because that would mean `":hello"` gets turned into `@myrule//myrule:hello` instead of `@myproject//pkg:hello`. We also can't check `if str(DEFAULT_DEP) not in deps` because `deps` can contain non-absolute labels, whereas `str(DEFAULT_DEP)` is an absolute label.

We need a way to turn a string into a Label using the calling package's context. This is actually exactly the deprecated `Label(..., relative_to_caller_package=True)` constructor that we removed, thinking nobody would ever use it. It turns out that's not true (see https://github.com/protocolbuffers/protobuf/issues/9688). We should maybe add it back, and maybe think of a better API for it.

cc @brandjon @meteorcloudy

**Comment by pcjanzen** [comment]
does
`Label(native.repository_name() + "//" + native.package_name()).relative(dep)`
solve this problem? 
(since native.repository_name() and native.package_name() are relative to the caller package?)

**Comment by Wyverald** [comment]
That's a nice trick! Unfortunately it breaks when repo mappings are involved. `Label(...)` resolves the text using the current .bzl file's repo mapping, but `native.repository_name()` is the "canonical" repo name (post-mapping).

However, this idea could still be valuable if we decide to fix https://github.com/bazelbuild/bazel/issues/14580 by allowing some sort of "canonical-repo-name absolute label literals".

**Comment by Wyverald** [comment]
Duping against https://github.com/bazelbuild/bazel/issues/15593
