### ISSUE TITLE
Make `sort_index` in trace_profile.json consistent

### ISSUE THREAD

**Issue by larrytaowang** [bazelbuild/bazel#15174]
### Description of the problem / feature request:

When we build `--profile bazel_trace_profile.json`, in the generated file, the metadata event for the critical path for thread 0 has a `sort_index` value of `long`.
```
{"name":"thread_sort_index","ph":"M","pid":1,"tid":0,"args":{"sort_index":0}}
```

However, for all other lines, the values of `sort_index` are `String`. For example,
```
{"name":"thread_sort_index","ph":"M","pid":1,"tid":820,"args":{"sort_index":"1"}},
...
{"name":"thread_sort_index","ph":"M","pid":1,"tid":1327,"args":{"sort_index":"10000"}},
```

I think we should make the type of `sort_index` value consistent. Ideally, we can simply change [this line](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/profiler/Profiler.java#L1097) from 
 `writer.name("sort_index").value(CRITICAL_PATH_SORT_INDEX);`
to `writer.name("sort_index").value(String.valueof(CRITICAL_PATH_SORT_INDEX));`. But I am not sure if this intended behavior.

### Feature requests: what underlying problem are you trying to solve with this feature?

Make the type of `sort_index` value consistent, i.e., for thread one, change from 
```
{"name":"thread_sort_index","ph":"M","pid":1,"tid":0,"args":{"sort_index":0}}
```
 to 
```
{"name":"thread_sort_index","ph":"M","pid":1,"tid":0,"args":{"sort_index":"0"}}
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

build `--profile bazel_trace_profile.json` and check the profile json file

### What operating system are you running Bazel on?

MacOS 12.3

### What's the output of `bazel info release`?

release 5.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace this line with your answer.

### Any other information, logs, or outputs that you want to share?

> Replace this line with your answer.

**Comment by sgowroji** [comment]
Hello @larrytaowang , Thank you for sharing the above details. Have you encounter any error with sort_index value of long. Could you please share the exact steps to reproduce that error.

**Comment by larrytaowang** [comment]
Hi @sgowroji , sorry for the late reply. Our service will parse the content of the generated  trace profile. For the `args` in the JSON file, originally we have this type `Args map[string]string`, but now we have to use `Args map[string]interface{}` since the value can be either a string or long.

This is not a big issue. But we thought it would be great if we can keep the value type of `args` consistent.

Steps to reproduce:
- git clone https://github.com/bazelbuild/examples
- cd cpp-tutorial/stage1
- bazel build //main:hello-world --profile bazel_trace_profile.json

In the generated file `cpp-tutorial/stage1/bazel_trace_profile.json`, we can see the first `sort_index` has a value of long.
```
{"otherData":{"build_id":"a7bfb392-496d-4915-b8e5-139f27c0570b","output_base":"/private/var/tmp/_bazel_tawang/54883d2a9fc3b6fca9c12697bc592da9","date":"Mon Apr 11 20:50:54 PDT 2022"},"traceEvents":[
    {"name":"thread_name","ph":"M","pid":1,"tid":0,"args":{"name":"Critical Path"}},
    {"name":"thread_sort_index","ph":"M","pid":1,"tid":0,"args":{"sort_index":0}},
    {"name":"thread_name","ph":"M","pid":1,"tid":21,"args":{"name":"Main Thread"}},
    {"name":"thread_sort_index","ph":"M","pid":1,"tid":21,"args":{"sort_index":"1"}},
```

**Comment by meteorcloudy** [comment]
I think this belongs to the build productivity team, @meisterT can you take a look?

**Comment by meisterT** [comment]
@larrytaowang can you send a PR that makes it consistent?

**Comment by larrytaowang** [comment]
Hi @meisterT  I created a PR for this fix.
