### ISSUE TITLE
It is recommended to add which line is wrong when commond executes error

### ISSUE THREAD

**Issue by TheadySong** [bazelbuild/bazel#15197]
### Description of the feature request:

Prompt how the specific line is wrong  when commond executes error

### What underlying problem are you trying to solve with this feature?

For example，the following rule:

def init(name = "test"):
    native.genrule(
        name = name,
        srcs = ["1.txt"],
        outs = ["1.out"],
        cmd = """
            echo "aaaaa"
            echo "bbbbb"
            grep ""
            echo "ccccc"
            echo "ddddd"
            cp $(SRCS) $@
        """,
    )

This Command will run an error in the grep line.  And tip the entire Command run error. But I want it to prompt the error is grep line.

ERROR: /work/oppo_80233408/test/bazel/BUILD:5:5: Executing genrule //:test failed: (Exit 1): bash failed: error executing command
  (cd /work/oppo_80233408/.bazel_cache/_bazel_80233408/1d042587785b64110014eadf50489378/sandbox/linux-sandbox/2/execroot/__main__ && \
  exec env - \
    PATH=/work/oppo_80233408/bin:/work/oppo_80233408/.local/bin:/work/coverity/analysis_2020_06/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/bin:/pkg/qct/software/python/3.8.2/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
            echo "aaaaa"
            echo "bbbbb"
            grep ""
            echo "ccccc"
            echo "ddddd"
            cp 1.txt bazel-out/k8-fastbuild/bin/1.out
        ')
Execution platform: @local_config_platform//:host

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

release 4.2.2

**Comment by comius** [comment]
@sgowroji  I don't see what this has to do with python.

**Comment by sgowroji** [comment]
Hello @TheadySong, Could you please provide steps and code changes to reproduce the  above error. Thanks!

**Comment by TheadySong** [comment]
> Hello @TheadySong, Could you please provide reproducing steps and code changes to reproduce the above error. Thanks!

The problem is that after I run bazel build, bazel prompts that a certain piece of shell code fails to execute, but it can't tell me exactly which line went wrong. If the shell code is long, this can make troubleshooting more difficult.
And if we add set -x to the shell code, we can see which line of code execution fails when executing the shell code.
It is not possible for me to add set -x directly to all called shell code, because that would make the log huge. So I hope to only increase set -x for the shell code segment that fails to run.
My current personal solution is that when running bazel build and an error occurs, I parse out the error shell code segment from the error log. After I automatically add set -x, run the code segment again, so that I can accurately prompt Which line in the whole shell snippet is wrong.

**Comment by meteorcloudy** [comment]
This isn't a bug in Bazel, there is no way we cannot change the genrule to promot the exact location of the failure, a work around is to write your command into a shell script with `set -x`, then run that shell script in the genrule.

**Comment by TheadySong** [comment]
> 

Yes, this is not a bug.
But if bazel can support it, it will improve the user experience and facilitate troubleshooting. Our approach of adding set -x to the failing shell script doesn't look pretty.
