### ISSUE TITLE
Starlarkify `java_import` rule

### ISSUE THREAD

**Issue by comius** [bazelbuild/bazel#15196]
Bazel team would like to rewrite all rules that are part of Java to Starlark. We're making good progress, but this could be even faster with contributions from the community.

`java_import` rule is a good "medium" difficulty rule to rewrite to Starlark by the community. Some previous experience in Starlark, previous PRs are probably needed. **This is not a good starter project.** Bazel team can provide support on ambiguous problems and solutions, however our time is limited and we can't help with everything.

There are other "medium" difficulty rules to rewrite: `java_runtime`, `java_package_configuration` or `java_toolchain`. Each of them contains something tricky - the code is shorted, but probably also not a good starter project without previously agreeing on how to solve tricky part.

Instructions:
- rewrite to Starlark `JavaImport`, `JavaImportBaseRule`, `BazelJavaImportBaseRule` classes (and their dependencies)
- [use builtin `bzl` files](https://cs.opensource.google/bazel/bazel/+/master:src/main/starlark/builtins_bzl/), see examples of already Starlarkfied rules, follow the style of `java_library.bzl` implementation
- test the rule by enabling it temporarily in `exports.bzl`
- make the final PR without the rule exported (additional tests and benchmark will be done by Bazel team)
- make the first rewrite as close to the native rule as possible (to have the tests pass)
- ensure your place in Starlarkification hall of fame!

Details:
- `semantics.checkRule` can be removed, Bazel's implementation is noop
- JavaConfiguration.getUseIjar, JavaToolchainProvider.getIJar can be exposed to builtins only (not Starlark) - see [checkPrivateAccess](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/java/JavaStarlarkCommon.java;l=336-344;drc=4d506c5d737c5785263deeb58fa1715fc5cf03f4)
- Starlarkify `ijar_action`
- Starlarkify `import_deps_check_action` 
- Reuse [collectProguardSpecs](https://cs.opensource.google/bazel/bazel/+/master:src/main/starlark/builtins_bzl/common/java/proguard_validation.bzl)
- return `JavaInfo` created with `JavaInfo` constructor (it might needs extensions - be conservative)

**Comment by comius** [comment]
cc @cushon, @hvadehra

**Comment by fmeum** [comment]
I worked on this for a bit and starlarkified `ijar_action` and `import_deps_check_action` in https://github.com/fmeum/bazel/tree/starlark-java-import. For anyone interested in picking up this issue, feel free to use any bits of these commits (disclaimer: entirely untested).

**Comment by kotlaja** [comment]
I'm starting to work on this task. If anyone is doing it in parallel with me, please let me know so we don't do double work. 

PS. Thanks @fmeum, I'll check your code.

**Comment by kotlaja** [comment]
I'm closing this issue since java_import is fully in Starlark for a few months by now. :)
