### ISSUE TITLE
Add config to generate_workspace to specify output paths

### ISSUE THREAD

**Issue by pgr0ss** [bazelbuild/bazel#1520]
What do people think of adding flags to `generate_workspace` to configure where it writes the `WORKSPACE` and `BUILD` files? Something like:

```
bazel run //src/tools/generate_workspace -- \
  --artifact=... \
  --workspace_output=/path/to/project/WORKSPACE \
  --build_output=/path/to/project/third-party/BUILD
```

This would let me skip the step of copying over the generated files from a randomly named tmp directory.

If there is interest, I might take a stab at implementing it.

**Comment by kchodorow** [comment]
That sounds good to me.

**Comment by petroseskinder** [comment]
@kchodorow I believe this issue should be closed, as it has implemented in #1553

**Comment by pgr0ss** [comment]
@petroseskinder It doesn't look like #1553 was merged: https://github.com/bazelbuild/bazel/pull/1553#issuecomment-239987143

**Comment by kchodorow** [comment]
Update on this: I'm working on moving generate_workspace out of the Bazel source to https://github.com/bazelbuild/migration-tooling. So all changes will happen there, instead.

That said, does `--output_dir` cover your situation? Because that's an option, now.

**Comment by pgr0ss** [comment]
Yeah, `--output_dir` seems sufficient.

**Comment by kchodorow** [comment]
Cool.
