### ISSUE TITLE
How to install Bazel on Docker image for Raspbery Pi

### ISSUE THREAD

**Issue by zmajew** [bazelbuild/bazel#15207]
Hi, I am trying to install Bazel on a docker image for the ARM (Raspberry) environment. I do not see a clear example so I have followed [this](http://interstellarengine.com/build-automation/Compiling-Bazel-from-source-on-raspberry-pi.html) one. My finall goal is to install TensorFlow Lite with Bazel for some Go project.

Here is the Dockerfile:

```
FROM balenalib/raspberry-pi-debian-golang:latest

RUN install_packages openjdk-8-jdk -y

# downloaded and extracted in local directory
COPY /bazel /bazel
WORKDIR /bazel
RUN chmod u+w ./* -R
RUN env BAZEL_JAVAC_OPTS="-J-Xms12G -J-Xmx12g" \
JAVA_TOOL_OPTS="-Xmx12g" \
EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" 
# Here it brokes
RUN bash compile.sh
```
What ever the size of the "-Xmx12g" am getting the error:
`The system is out of resources.
Consult the following stack trace for details.
java.lang.OutOfMemoryError: Java heap space`
...

How to install the Bazel on the docker image, or how to install TensorFlow Lite with Bazel on the docker image for Raspberry Pi?

**Comment by meteorcloudy** [comment]
@zmajew Can you download the Bazel binary built for Linux ARM64 platform from https://github.com/bazelbuild/bazel/releases?

> how to install TensorFlow Lite with Bazel on the docker image for Raspberry Pi

This is a question can be better answered in the TensorFlow github repo.

**Comment by zmajew** [comment]
> @zmajew Can you download the Bazel binary built for Linux ARM64 platform from https://github.com/bazelbuild/bazel/releases?
> 
> > how to install TensorFlow Lite with Bazel on the docker image for Raspberry Pi
> 
> This is a question can be better answered in the TensorFlow github repo.

Are there here some official examples of how to install Bazel inside the docker image, since on the internet I found only some old examples from developers?

**Comment by meteorcloudy** [comment]
Since this is not a Bazel bug, I'm closing this.
