### ISSUE TITLE
Release 5.2 - April 2022

### ISSUE THREAD

**Issue by ckolli5** [bazelbuild/bazel#15210]
# Status of Bazel 5.2

-   Expected release date: 2022-06-07
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/36)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 5.2, simply send a PR against the `release-5.2.0` branch.

Task list:

-   [x] [Create draft release announcement](https://docs.google.com/document/d/1wDvulLlj4NAlPZamdlEVFORks3YXJonCjyuQMUQEmB0/edit)
-   [x] Send for review the release announcement PR:
-   [x] Push the release, notify package maintainers:
-   [x] Update the documentation
-   [x] Push the blog post
-   [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by foxandi** [comment]
Is it possible to get https://github.com/bazelbuild/bazel/pull/15306 into this release and have an updated/regenerated embedded JDK for Windows? If yes, I will create a PR with the change against the release branch.

**Comment by Wyverald** [comment]
Should be possible. I'm not entirely sure what updating the embedded JDK entails; @hvadehra @comius to comment

**Comment by foxandi** [comment]
Thanks :) I created the PR: https://github.com/bazelbuild/bazel/pull/15342

**Comment by linzhp** [comment]
Can you also include #15341?

**Comment by AustinSchuh** [comment]
I'm unable to run our tests on a remote execution cluster with 5.2.

The description from @TLATER on the following ticket describes exactly the symptoms I'm seeing, and reverting the patch he mentions fixes it for me.  https://github.com/bazelbuild/bazel/issues/12821  Can we get https://github.com/bazelbuild/bazel/commit/00805727b867d33fd922e63ca82b0d9825ad79fe reverted, or the C++ rules fixed?

**Comment by AustinSchuh** [comment]
I'm still unable to run our tests with bazel 5.2.0rc1, which is blocking us from upgrading from bazel 5.0.  This looks like a regression in how cc_test, external repositories, and remote execution interact.  The suggested fix in to add `linkstatic = 1` to every `cc_test`, which is an incompatible change.  The discussion on https://github.com/bazelbuild/bazel/issues/12821 has stalled.  Reverting https://github.com/bazelbuild/bazel/commit/00805727b867d33fd922e63ca82b0d9825ad79fe continues to fix the problem.  Could we get a revert cherry-picked, or the C++ rules fixed?

**Comment by ckolli5** [comment]
5.2 is now out!

[@vbatts](https://github.com/vbatts) [@petemounce](https://github.com/petemounce) [@excitoon](https://github.com/excitoon) Could you please update relevant package managers? Thanks!

**Comment by Wyverald** [comment]
@ckolli5 could you update the release page to point to the release notes blog post? (see last item in the checklist at the top of this page) Then this issue can be closed.
