### ISSUE TITLE
bash completion fails if user has a "grep" alias that produces unexpected output formatting

### ISSUE THREAD

**Issue by smu-ggl** [bazelbuild/bazel#1521]
Example:
alias grep="grep -P"

This could be avoided by using absolute paths for grep (and possibly other commands) or by protecting the relevant parts of the completion with "shopt -u expand_aliases" while executing the expansions.

I haven't done too much research yet, but this probably mostly affects
bazel-complete-template.bash lines [229](https://github.com/bazelbuild/bazel/blob/master/scripts/bazel-complete-template.bash#L229) [320](https://github.com/bazelbuild/bazel/blob/master/scripts/bazel-complete-template.bash#L320) [360](https://github.com/bazelbuild/bazel/blob/master/scripts/bazel-complete-template.bash#L360) [405](https://github.com/bazelbuild/bazel/blob/master/scripts/bazel-complete-template.bash#L405) but probably _not_ [190](https://github.com/bazelbuild/bazel/blob/master/scripts/bazel-complete-template.bash#L190).

I'd suggest to just replace all occurrences of "grep" with /bin/grep (and probably do the same for sed)

**Comment by damienmg** [comment]
This was done 86a40472a490e8cc8b1793db17b012b0fc21cd23
