### ISSUE TITLE
[5.2.0] Update java_tools 11.7

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#15230]
Forked from #15209

**Comment by hvadehra** [comment]
PR: https://github.com/bazelbuild/bazel/pull/15231

**Comment by hvadehra** [comment]
There are failures due to error prone, should I also cherry pick 1987af2216b3adb7d0e19a70f0e1778eee519d4c to fix them?

@coeuvre

**Comment by coeuvre** [comment]
probably yes.

**Comment by hvadehra** [comment]
#15231 is merged
