### ISSUE TITLE
Skylark operator list * int missing

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#1523]
Currently it is not supported to write `[foo] * 5`.
Message is:

```
unsupported operand type(s) for *: 'list' and 'int'.
```

**Comment by dslomov** [comment]
Isn't this fixed already?

**Comment by fweikert** [comment]
Andreas's fix is still pending: https://github.com/bazelbuild/bazel/pull/1524

**Comment by abergmeier-dsfishlabs** [comment]
Is merged.

**Comment by fweikert** [comment]
Thank you!
