### ISSUE TITLE
bazel coverage generate empty _coverage_report.dat

### ISSUE THREAD

**Issue by luojc0517** [bazelbuild/bazel#15254]
### Description of the bug:
<img width="997" alt="image" src="https://user-images.githubusercontent.com/13957771/163352524-29247974-ebd5-4d23-a0aa-31d65fc5babf.png">

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/13957771/163371188-a38c2dec-b1c8-493a-ac91-cd48ef243223.png">

### Which operating system are you running Bazel on?

CentOS Linux release 7.2 (Final)
gcc version 7.5.0 (GCC) 

### What is the output of `bazel info release`?

release 4.2.1

**Comment by luojc0517** [comment]
> gcov version before 7.0 is not supported.

**Comment by celkas** [comment]
@luojc0517 how did You solve Your issue?

**Comment by ergleb78** [comment]
It looks like I'm facing the same issue. No matter what I test the report file has zero bytes in length.

**Comment by fmeum** [comment]
@ergleb78 Are you using Bazel 5.3.1? A number of possible causes have been fixed since the original report.

**Comment by ergleb78** [comment]
@fmeum I'm on 5.3.2, actually
It looks like all the tests are being executed, but the report file is empty:

-5.3.2-linux-x86_64...
bazel 5.3.2

//<package....>/tests:test_service_endpoints                                PASSED in 3.4s
//<package...>/tests:test_code                                                        PASSED in 15.5s

Executed 2 out of 2 tests: 2 tests pass.
INFO: Build completed successfully, 9 total actions

but when generating HTML:

>genhtml --output genhtml "$(bazel info output_path)/_coverage/_coverage_report.dat"
Reading data file /home/<username>/.cache/bazel/_bazel_ergleb/6c84692c8d10b09402b3dc737b3add17/execroot/__main__/bazel-out/_coverage/_coverage_report.dat
genhtml: ERROR: no valid records found in tracefile /home/<username>/.cache/bazel/_bazel_ergleb/6c84692c8d10b09402b3dc737b3add17/execroot/__main__/bazel-out/_coverage/_coverage_report.dat

When listing the output dir: 

drwxrwxrwx 2 user user 4096 Oct 19 00:24 ./
drwxrwxr-x 8 user user 4096 Oct 21 05:28 ../
-r-xr-xr-x 1 user user    0 Oct 19 00:24 _coverage_report.dat*
-r-xr-xr-x 1 user user  507 Oct 19 00:23 lcov_files.tmp*

**Comment by luojc0517** [comment]
> @luojc0517 how did You solve Your issue?

by upgrademy gcov version
