### ISSUE TITLE
Can we get rid of all the "breaking-change" and "migration" labels?

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#15265]
They are clutter and, AFAIK, we don't use them for anything any more with the switch to LTS releases.
We can also remove that code from bazelisk

cc: jdob@ meteorcloudy@

**Comment by meteorcloudy** [comment]
Yeah, I guess we can. @sgowroji Can you help deleting all `breaking-change-*` and `migration-*` labels?

**Comment by sgowroji** [comment]
Fixed https://github.com/bazelbuild/bazel/labels?q=breaking-change+%7C%7C+migration.

**Comment by aiuto** [comment]
Thanks!
