### ISSUE TITLE
Bazel@HEAD lacks `env_inherit` on `cc_test`

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#15268]
### Description of the bug:

With the Starlark flip of `cc_test` in https://github.com/bazelbuild/bazel/commit/e04735d8f5d2dc7df0eac60f2589a26d3d21710b, the rule no longer provides the `env_inherit` attribute.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See https://pipelines.actions.githubusercontent.com/serviceHosts/e1b19da9-c261-489f-82be-008378a078a0/_apis/pipelines/1/runs/1251/signedlogcontent/14?urlExpires=2022-04-15T08%3A25%3A30.3485429Z&urlSigningMethod=HMACV1&urlSignature=hEga7PwNt42ZQYwL232J1U%2BEmPtUJJu%2B30dfi0c0M6g%3D, but really any use of `env_inherit` on `cc_test` will fail at analysis time.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

development version

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

Using Bazelisk to fetch 22c91dab43558503a1d6759ccfd77587d87b28cd.

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
22c91dab43558503a1d6759ccfd77587d87b28cd
```

### Any other information, logs, or outputs that you want to share?

https://github.com/bazelbuild/bazel/commit/ee9727df980f268bfb2b05637d199d55963fb6d8 can potentially be used to implement `env_inherit` in Starlark.

**Comment by fmeum** [comment]
@trybka since you authored https://github.com/bazelbuild/bazel/commit/e04735d8f5d2dc7df0eac60f2589a26d3d21710b.

**Comment by trybka** [comment]
The log you provided is expired, FWIW, but you're right--`cc_test` (and Starlark tests in general) lack `env_inherit` -- I'm sorry this slipped past me (none of the Bazel or downstream tests caught it!). 

Since this is not an easy fix, I'll roll it back for now until we get this straightened out.

**Comment by trybka** [comment]
Oh, for some reason I missed that the commit you linked is in -- nevertheless, I will rollback while I work on that to minimize the breakage window.

**Comment by trybka** [comment]
I don't think I can close this bug or anything, but the rollback is submitted:
https://github.com/bazelbuild/bazel/commit/098e3977d492471623d9c460d234b108424f10b8

**Comment by fmeum** [comment]
With https://github.com/bazelbuild/bazel/pull/15232, the analogue of `testing.TestEnvironment` for the run environment will become available. This would allow implementing `env` and `env_inherit` for both `cc_binary` and `cc_test` in the same way. Perhaps it makes sense to wait for it land.

**Comment by fmeum** [comment]
@trybka FYI: There is a subtle difference in behavior between `env_inherit` on native rules and the `inherited_environment` parameter on `testing.TestEnvironment`, see https://github.com/bazelbuild/bazel/pull/14849#issuecomment-1042849614. If you want to maintain complete compatibility with native rules, you would have to drop those variables from `inherited_environment` that are also keys in `environment`. But apart from this very minor backwards compatibility concern, having inherited variables take precedence over fixed variables would seem more useful going forward (see also https://github.com/bazelbuild/bazel/pull/14849#discussion_r840558727).

**Comment by trybka** [comment]
@fmeum concretely, you're saying:

a) for proper native compatibility, we should filter keys in `environment` out of `inherited_environment`
b) except that might be genuinely more useful and might be preferred?

I believe I implemented (b) in https://github.com/bazelbuild/bazel/commit/4ed40eea4a0a07af6d709ea24a59d4a3d19dd527, but if there's a concern, I could go add filtering. 

Whatever we land on, I should update to add a test case.

**Comment by fmeum** [comment]
If b) was meant to say something like "except that might be genuinely less useful and the alternative might be preferred", then yes. I prefer the solution you implemented in https://github.com/bazelbuild/bazel/commit/4ed40eea4a0a07af6d709ea24a59d4a3d19dd527 and would argue that if no one speaks up about any experienced breakage (unlikely), then this is the better of the two alternatives.

+1 on adding a test case codifying this decision.

**Comment by fmeum** [comment]
@trybka Looks like this could be closed?

**Comment by trybka** [comment]
Yes, though I don't appear to have access to. @oquenchil can you take care of it?
