### ISSUE TITLE
enable_platform_specific_config had flag overrides has surprising behavior

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#15270]
### Description of the bug:

If you have a bazelrc with these contents:

```
build --enable_platform_specific_config
build --action_env=PATH
build:macos --action_env=PATH=/usr/bin:/macos
```

The `PATH` that is actually used is the passthrough defined by `--action_env=PATH`, not `/usr/bin:/macos`. If you flip the ordering to:

```
build --action_env=PATH
build --enable_platform_specific_config
build:macos --action_env=PATH=/usr/bin:/macos
```

I would expect `--enable_platform_specific_config` to take effect after the other options have been added, but maybe there is no great default for this.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

With this repro case run `bazel build foo -s`, and change the `.bazelrc` as needed.

[pathrepro.zip](https://github.com/bazelbuild/bazel/files/8498010/pathrepro.zip)

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 5.1.1

### Have you found anything relevant by searching the web?

Nope

**Comment by meteorcloudy** [comment]
I think this is WAI, if you replace `build --enable_platform_specific_config` with `build --config=macos`, you'll get the same result when running on macOS. I think the idea is the latter one that gets expanded always wins in the .bazelrc file.
