### ISSUE TITLE
--enable-preview causes issues when using a custom toolchain

### ISSUE THREAD

**Issue by kjcartledge** [bazelbuild/bazel#15272]
### Description of the bug:

While attempting to use Java 17 (with preview features), I've run into an issue with the `--enable-preview` option.

```
load(
  "@bazel_tools//tools/jdk:default_java_toolchain.bzl",
  "default_java_toolchain", "DEFAULT_TOOLCHAIN_CONFIGURATION", "BASE_JDK9_JVM_OPTS", "DEFAULT_JAVACOPTS"
)

default_java_toolchain(
  name = "repository_default_toolchain",
  configuration = DEFAULT_TOOLCHAIN_CONFIGURATION,
  java_runtime = "@bazel_tools//tools/jdk:remotejdk_17",
  jvm_opts = BASE_JDK9_JVM_OPTS + ["--enable-preview"],
  javacopts = DEFAULT_JAVACOPTS + ["--enable-preview"],
  source_version = "17",
  target_version = "17",
)
```
Is basically straight from https://bazel.build/docs/bazel-and-java#config-compilation-toolchains.

I've tried a few different permutations in the `.blazerc` to make it happy:

```
build --java_language_version=17
build --java_runtime_version=remotejdk_17
```

Causes errors like `error: could not locate class file for java.lang.Record` if making use of certain Java 17 features.

```
build --java_language_version=17
build --java_runtime_version=remotejdk_17
build --tool_java_language_version=17
build --tool_java_runtime_version=remotejdk_17
```

Works _if_ `--enable-preview` is removed from the toolchain definition, but otherwise causes an error:

```
error: invalid source release 8 with --enable-preview
(preview language features are only supported for release 17)
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I'm attempted to assemble a minimal repro at https://github.com/kjcartledge/bazel-java17-repro.

Basically, creating two targets (one that depends on the other) that use Java 17 features while `--enable-preview` is enabled in the toolchain seems to not work.

### Which operating system are you running Bazel on?

Debian GNU/Linux 10 (buster)

### What is the output of `bazel info release`?

release 5.1.1

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
git@github.com-google:kjcartledge/bazel-java17-repro.git
10617bf004d766710b75775f118d7624e7f540b5
10617bf004d766710b75775f118d7624e7f540b5
```

### Have you found anything relevant by searching the web?

Not that I could find.

### Any other information, logs, or outputs that you want to share?

The command that causes the second (`--enable-preview`) failure seems to reference `external/remote_java_tools/java_tools/JavaBuilder_deploy.jar`

**Comment by cushon** [comment]
It's possible to work around this by adding the flag directly to the target, but that's obviously not ideal:

```diff
 java_library(
@@ -21,6 +24,7 @@ java_library(
 java_library(
     name = "repro",
     srcs = ["Repro.java"],
+    javacopts = ["--enable-preview"],
     deps = [":guava"],
 )
 ```
 
The failure is from `external/rules_jvm_external/private/tools/java/rules/jvm/external/jar/AddJarManifestEntry.jar`, which explicitly passes `-source 8 -target 8`:

https://github.com/bazelbuild/rules_jvm_external/blob/433a989abe1ac26449d48c243c560bef1195939c/private/tools/java/rules/jvm/external/jar/BUILD#L1-L8

The new default toolchain configuration in the repro unconditionally passes `--enable-preview`, and javac doesn't support combining the flags.
 
Bazel does some javac flag normalization to solve related problems with `--add-exports=`, which isn't allowed to be combined with `-source 8 -target 8` either: https://github.com/bazelbuild/bazel/commit/90b0714d4827ac21281ba655d500f7bde78ddec5. I'll look at doing something similar for `--enable-preview`.
