### ISSUE TITLE
Bazel 5.0.0: _coverage directory no write permissions

### ISSUE THREAD

**Issue by SimonVleugels** [bazelbuild/bazel#15307]
### Description of the bug:

When running `bazel coverage` for our unittests using sandboxfs, we are getting a permission denied when creating a symbolic link to the `gcov` binary in `bazel/tools/test/collect_cc_coverage.sh`.

The `collect_cc_coverage.sh` script tries to create a symlink:
```
ln -s "${COVERAGE_GCOV_PATH_ABS}" "${GCOV}"
```
Which translates into:
```
ln -s "/repo/vleugels/sw4/bazel-cache/base/sandbox/sandboxfs/41/__main__/.../bin/x86_64-pc-linux-gnu-gcov" "/repo/vleugels/sw4/bazel-cache/base/sandbox/sandboxfs/41/__main__/bazel-out/k8-fastbuild/testlogs/.../_coverage/gcov"
```
And results in a permission denied.

When printing out the permissions of the directory we get following:
```
ls -alF /repo/vleugels/sw4/bazel-cache/base/sandbox/sandboxfs/41/__main__/bazel-out/k8-fastbuild/testlogs/.../_coverage
dr-xr-xr-x 2 builder builder 2 Apr 13 08:28 ./
drwxrwxr-x 2 builder builder 2 Apr 13 08:28 ../
dr-xr-xr-x 2 builder builder 2 Apr 13 08:28 bazel-out/'
```
So no write permissions for our builder user.

In Bazel 4.2 this was working fine. I noticed that the directory structure is changed and the `_coverage` dir was directly under `__main__` for bazel4:
```
ls -alF /repo/vleugels/sw/bazel-cache/base/sandbox/sandboxfs/127/__main__
drwxrwxr-x 2 builder builder 2 Apr 13 08:35 ./
dr-xr-xr-x 2 builder builder 2 Apr 13 08:35 ../
drwxr-xr-x 2 builder builder 2 Apr 13 08:35 _coverage/
drwxr-xr-x 2 builder builder 2 Apr 13 08:35 _tmp/
drwxrwxr-x 2 builder builder 2 Apr 13 08:35 bazel-out/
dr-xr-xr-x 2 builder builder 2 Apr 13 08:35 buildroot-symlinks/
dr-xr-xr-x 2 builder builder 2 Apr 13 08:35 external/
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Not yet possible to reproduce this outside our build environment.
Used sandbox and coverage related bazel flags:
```
--sandbox_writable_path=/repo/builder/ccache-buildroot
--sandbox_writable_path=/repo/builder/repo/vobs/esam/build/reborn/ccache-buildroot
--repository_cache=/repo/shared-bazel-cache
--strategy TestRunner=processwrapper-sandbox
--sandbox_tmpfs_path=/tmp
--sandbox_fake_hostname
--experimental_allow_tags_propagation
--java_language_version=17
--java_runtime_version=local_jdk
--tool_java_language_version=17
--tool_java_runtime_version=local_jdk
--repo_env=JAVA_HOME=/usr/lib/jvm/java-17-openjdk
--experimental_split_coverage_postprocessing
--experimental_fetch_all_coverage_outputs
--sandbox_debug
--experimental_use_sandboxfs
--spawn_strategy=sandboxed
--experimental_sandboxfs_map_symlink_targets
--collect_code_coverage
--test_output=all
```

### Which operating system are you running Bazel on?

Centos7

### What is the output of `bazel info release`?

development version

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

```
git clone -n https://github.com/bazelbuild/bazel.git
cd bazel
git checkout 5.0.0
bazelisk build //src:bazel --extra_toolchains=@bazel_tools//tools/python:autodetecting_toolchain_nonstrict
```

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
git remote get-url origin; git rev-parse master; git rev-parse HEAD
error: Unknown subcommand: get-url
006be04d9fd64ff8227a3aeaa211eb05603657b9
4b97aa4678ebae72084ce2b1aad09bef2fcd667a
```

**Comment by c-mita** [comment]
I can't find anything likely that's changed between 4.2.0 and 5.0.0; the code that sets up the coverage directory (where `gcov` gets linked to) doesn't appear to have changed since early 2020.
That was when the `--experimental_fetch_all_coverage_outputs` flag was added.

**Comment by SimonVleugels** [comment]
@c-mita can you point me to the file where the `_coverage` dir is created?

**Comment by c-mita** [comment]
In your case, I believe it would be https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/test/TestActionBuilder.java;l=391

**Comment by SimonVleugels** [comment]
Closing in favor of [issue-15363](https://github.com/bazelbuild/bazel/issues/15363)
