### ISSUE TITLE
`cc_test` on Bazel@HEAD breaks with `--experimental_enable_bzlmod` on Windows

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#15317]
### Description of the bug:

On d5c788f684314916748bf418ce99014b2ef41f66, `cc_test` deps suddenly fail to link on Windows with `--experimental_enable_bzlmod`. On 092884b0118f1b8b14ba2277851baa6dcce5cac2, this did not occur.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. On Windows, clone https://github.com/fmeum/rules_jni/commit/d626fe78bbf6cbdc95edb16e356f8896f3f76666.
2. In the `tests` subdirectory, execute:
```
USE_BAZEL_VERSION=d5c788f684314916748bf418ce99014b2ef41f66 bazelisk test --config=ci --config=bzlmod  //...
```

This will error on a link action (different one each time), with an error similar to:
```
ERROR: C:/users/runneradmin/_bazel_runneradmin/bkrwcep2/external/rules_jni.override/jni/tools/libjvm_stub/BUILD.bazel:45:11: Linking external/rules_jni.override/jni/tools/libjvm_stub/libjvm_stub_lib_34418d9fbc.dll failed: (Exit 1120): link.exe failed: error executing command (from target @rules_jni.override//jni/tools/libjvm_stub:libjvm_stub_lib) C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe ... (remaining 1 argument skipped)
   Creating library bazel-out/x64_windows-fastbuild/bin/external/rules_jni.override/jni/tools/libjvm_stub/libjvm_stub_lib.if.lib and object bazel-out/x64_windows-fastbuild/bin/external/rules_jni.override/jni/tools/libjvm_stub/libjvm_stub_lib.if.exp
libjvm_stub.obj : error LNK2019: unresolved external symbol rules_jni_internal_get_bazel_java_home referenced in function init
bazel-out\x64_windows-fastbuild\bin\external\rules_jni.override\jni\tools\libjvm_stub\libjvm_stub_lib_34418d9fbc.dll : fatal error LNK1120: 1 unresolved externals
```

With `--experimental_builtins_injection_override=-cc_test`, the checks pass.

### Which operating system are you running Bazel on?

Windows

### What is the output of `bazel info release`?

development version

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

Bazelisk with `USE_BAZEL_VERSION=d5c788f684314916748bf418ce99014b2ef41f66`.

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
d5c788f684314916748bf418ce99014b2ef41f66
```

**Comment by fmeum** [comment]
@trybka since this seems related to the `cc_test` Starlark flip.
@meteorcloudy since it seems to be bzlmod-specific.

**Comment by trybka** [comment]
Does it fail only with bzlmod enabled? 

Note that there was a slight behavior change in `cc_test` -- namely previously it would link cc_test statically if the host was Windows, regardless of the target platform.

Now, it will link statically if the _target_ is Windows. The change in behavior is intentional, for two reasons:
1) we can't inspect the host in Starlark in the same way
2) this was the presumed "intent" here (tests _for_ windows should not link dynamically).

Another interesting testcase would be if it passes with `--dynamic_mode=off`

**Comment by meteorcloudy** [comment]
> bazel-out\x64_windows-fastbuild\bin\external\rules_jni.override\jni\tools\libjvm_stub\libjvm_stub_lib_34418d9fbc.dll : fatal error LNK1120: 1 unresolved externals

It indeed looks like Bazel is trying to link cc_test dynamically on Windows, which it shouldn't. Not sure why Bzlmod has anything to do with it.

**Comment by fmeum** [comment]
> > bazel-out\x64_windows-fastbuild\bin\external\rules_jni.override\jni\tools\libjvm_stub\libjvm_stub_lib_34418d9fbc.dll : fatal error LNK1120: 1 unresolved externals
> 
> It indeed looks like Bazel is trying to link cc_test dynamically on Windows, which it shouldn't. Not sure why Bzlmod has anything to do with it.

It could be the case that it is not involved in the fact that `cc_test` links dynamically on Windows directly, but maybe some code that triggers (e.g. https://github.com/bazelbuild/bazel/blob/f970db58be060a0d96faba51d05d5e72bd37fef5/src/main/java/com/google/devtools/build/lib/rules/cpp/CppHelper.java#L899) is not aware of repo mappings.

**Comment by meteorcloudy** [comment]
@fmeum I think the code is : https://cs.opensource.google/bazel/bazel/+/master:src/main/starlark/builtins_bzl/common/cc/cc_test.bzl;l=43-47

**Comment by trybka** [comment]
BTW, given that this is an experimental flag, and you have a workaround (also curious if `--dynamic_mode=off` helps), can I work on a fix forward, or is this causing significant blockage?

**Comment by fmeum** [comment]
@meteorcloudy Nice catch, didn't think about the possibility that the mapping of `@platforms` may be an issue.

@trybka No, you can fix forward. Both `--dynamic_mode` and the bzl override are decent workarounds: https://github.com/fmeum/rules_jni/actions/runs/2208189263

**Comment by trybka** [comment]
Interesting. So we actually check the constraints here: 
https://cs.opensource.google/bazel/bazel/+/master:src/main/starlark/builtins_bzl/common/cc/cc_helper.bzl;l=825-831;drc=faf818b3f25314248400cad18c98f57c435a31b0

So, perhaps the canonical name (e.g. `@platforms.0.0.4`) is used when iterating through the constraints, but the attribute is using the local-ish name?

**Comment by meteorcloudy** [comment]
I'll do some debugging and report back.

**Comment by meteorcloudy** [comment]
<img width="924" alt="image" src="https://user-images.githubusercontent.com/4171702/164751167-1a7de3f8-0191-4219-9cd1-3483f62a2774.png">

It looks like indeed the labels passed to `ctx.target_platform_has_constraint` wasn't going through repo mappings. My guess it because the cc_helper.bzl file is defined in a special place, so Bzlmod has no idea how to get its repo mappings. /cc @Wyverald
