### ISSUE TITLE
[Bug] Lombok @Generated not added to generated code

### ISSUE THREAD

**Issue by ckilian867** [bazelbuild/bazel#15314]
### Description of the bug:

In `lombok.config` file, we specify `lombok.addLombokGeneratedAnnotation = true`. However, after decompiling the generated code, the `@Generated` annotation is not added to the code. Inspecting what Lombok is doing using a debugger, it seems that lombok is adding the annotation, but the end result does not have it. 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Minimal example: https://github.com/ckilian867/bazel-lombok-generated-annotation

Building the target using Buck and decompiling it, the generated code is annotated with @Generated. However, after building the target in Bazel and decompiling it, the annotation is not present.

### Which operating system are you running Bazel on?

```
PRETTY_NAME="Debian GNU/Linux 10 (buster)" 
NAME="Debian GNU/Linux" 
VERSION_ID="10" 
VERSION="10 (buster)" 
VERSION_CODENAME=buster 
ID=debian 
HOME_URL="https://www.debian.org/" 
SUPPORT_URL="https://www.debian.org/support" 
BUG_REPORT_URL="https://bugs.debian.org/"
```

### What is the output of `bazel info release`?

Tested on 4.2.2, 5.0.0, and 5.1.0

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```
$ git remote get-url origin; git rev-parse main; git rev-parse HEAD
https://github.com/ckilian867/bazel-lombok-generated-annotation.git
9a48b43255206e0be8ea0b62d3a5679c475f47cc
9a48b43255206e0be8ea0b62d3a5679c475f47cc
```

### Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Included in the README in the minimal example.

**Comment by sgowroji** [comment]
Hello @ckilian867, Not able to reproduce it with latest  Bazel 5.1.1. Can you please try and let us know. Attaching the screenshot for reference. 
<img width="1061" alt="Screen Shot 2022-04-22 at 12 25 19 PM" src="https://user-images.githubusercontent.com/48122892/164621121-984027f5-268f-4983-9778-dd2d32a5bb35.png">

**Comment by cushon** [comment]
I can repro with `--strategy=Javac=sandboxed`.

```
$ bazel clean; bazel shutdown; bazel build --strategy=Javac=sandboxed  //example:problem
$ 
$ javap -v -p -cp bazel-bin/example/libproblem.jar Problem |& grep Generated
...
```

```
$ bazel clean; bazel shutdown; bazel build --strategy=Javac=standalone  //example:problem
$ javap -v -p -cp bazel-bin/example/libproblem.jar Problem |& grep Generated
  #20 = Utf8               Llombok/Generated;
        lombok.Generated
        lombok.Generated
```

I think the issue is the way Lombok configuration works:

```
cat ./example/lombok.config
config.stopBubbling = true
lombok.addLombokGeneratedAnnotation = true
```

It tries to read that file off disk in the same location as the `.java` files being compiled, which isn't possible with Bazel's hermetic sandboxing approach: the files that are inputs to the action need to be declared in the build language, Lombok can't just find them on disk

**Comment by ckilian867** [comment]
Thanks for the responses. I think the strategy is sandboxed by default, so I tried added the following to my project's `.bazel.rc`:

```
build --strategy=Javac=local
```

This allows the `lombok.config` file to be picked up and `@Generated` is showing up in produced jars now. However, we'd like to keep keep the strategy as sandboxed. Is there any way to put the `lombok.config` file in the directory as the `.java` files? It can't be included in the `srcs` since it doesn't end with `.java`, `.srcjar` or `.properties`.

**Comment by cushon** [comment]
I think if you added it to [`java_toolchain.javabuilder_data`](https://docs.bazel.build/versions/main/be/java.html#java_toolchain.javabuilder_data) it would be available as an input of all Java compilation actions, which would allow Lombok to find it.

Alternately it would be nice if Lombok supported a more explicit configuration mechanism (a command line flag, or even a flag to specify the path to the config file), to avoid having to search the filesystem for it.

**Comment by ckilian867** [comment]
Thanks Liam! I was able to get one `lombok.config` to get picked up by putting it in `java_toolchain.javabuilder_data`, which is a huge step forward.

The example only had a single `lombok.config` file, but my actual project has several, some of which have conflicting keys. Is there a straightforward way to swap out what java_toolchain is used dynamically? The only way I've found to set it are statically through WORKSPACE and `bazelrc`. If not, we can probably explore moving away from the use of conflicting `lombok.config` keys.

**Comment by cushon** [comment]
> Is there a straightforward way to swap out what java_toolchain is used dynamically?

Not one I'd recommend. In theory you could define a `java_toolchain` with a `select()` in its `data` and use [starlark transitions](https://docs.bazel.build/versions/2.1.0/skylark/config.html#user-defined-transitions) to swap out different versions of it for different targets.

But if you can use a single config that's going to be a lot easier.

**Comment by ckilian867** [comment]
> Alternately it would be nice if Lombok supported a more explicit configuration mechanism (a command line flag, or even a flag to specify the path to the config file), to avoid having to search the filesystem for it.

Hi Liam, we're playing around with working lombok to accept a flag to the config file, but we're still running into issues. We're using a genrule to copy the lombok.config file into the sandbox and passing $(location) on the file in the javacopts since they are subject to Make variable expansions. However, the file does not seem to show up in the sandbox and is unavailable to the annotation processor at runtime. I tried add the genrule to the `deps`, but the file was not present. I tried renaming the lombok.config to `lombok.properties` and passing it to the `srcs`, but this file was not available in the sandbox either. The only success I had was zipping the file in the genrule that output ` .srcjar` and including that in the `srcs`, but this requires unzipping the file within lombok. 

What is the intended mechanism to ensure the file is in sandbox so we can pass a command line option to lombok to pick it up? I asked a similar question in the bazel-discuss group with more information: https://groups.google.com/g/bazel-discuss/c/JbkbaZl7htU

**Comment by cushon** [comment]
I was wondering about using javac flags to configure `addLombokGeneratedAnnotation` directly, e.g. something like `-Alombok.addLombokGeneratedAnnotation`, not passing the path to a config file.

`java_package_configuration` supports `data` and `javacopts` and will do location expansion, but using that would still require a custom `java_toolchain`.

**Comment by ckilian867** [comment]
I think sending a map over through `-A` would work, or sending individual fields through multiple options, but Starlark can't read files so converting the `lombok.config` file to a map to send over wouldn't be possible. We'd need convert all our existing `lombok.config` files to be `lombok.bzl` files that contain a map, unless there's an easier way. 

Maybe off topic, but do you know why `.properties` files don't show up in the sandbox, but `.srcjar` files do? If  `.properties` files showed up in the sandbox we could use the genrule to rename `lombok.config` to `lombok.properties` in the sandbox and just pass the location of `lombok.properties` to lombok, although this might be a bit hacky.
