### ISSUE TITLE
Bazel CI: Bazel's test_size_less_than_312MB is failing in downstream pipeline

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#15334]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2448#2d430eaa-4fd2-45da-a511-abf67bafe3f3
```
test_size_less_than_312MB FAILED: Size of install_base is 322912 kB, expected it to be less than 319488 kB..
```

<del> Potential culprit: https://github.com/bazelbuild/bazel/commit/c94572bea5ce6bdc0ccda9789e5be6fb3f4c173b </del>
Culprit: https://github.com/bazelbuild/bazel/commit/18c17dab8fece0a02b53911711ebba497e7fea2a

**Comment by meteorcloudy** [comment]
@meisterT It's very strange that this is only failing with Bazel@HEAD but not with Bazel 5.1.1

**Comment by meisterT** [comment]
Is that commit even in 5.1.1?

**Comment by meteorcloudy** [comment]
That commit isn't in 5.1.1, but it's in the Bazel source tree @ HEAD, which is tested in:
- Main pipeline: Bazel 5.1.1 + Bazel source @ HEAD
- Downstream pipeline: Bazel @ HEAD + Bazel source @ HEAD

**Comment by meteorcloudy** [comment]
OK, looks like https://github.com/bazelbuild/bazel/commit/c94572bea5ce6bdc0ccda9789e5be6fb3f4c173b isn't the culprit. 

I did a bisect and it points to https://github.com/bazelbuild/bazel/commit/18c17dab8fece0a02b53911711ebba497e7fea2a

To reproduce:
```
# Reset the source tree to an old commit that contains neither of the suspected commit
$ git reset https://github.com/bazelbuild/bazel/commit/18c17dab8fece0a02b53911711ebba497e7fea2a --hard

# Test with Bazel built at the culprit commit
$ export USE_BAZEL_VERSION=18c17dab8fece0a02b53911711ebba497e7fea2a
$ bazelisk test //src/test/shell/integration:minimal_jdk_test   # Fail

# Test with Bazel built at the parent of culprit commit
$ export USE_BAZEL_VERSION=128e4b32d6279fd76d403d37be2a2d485a51acc1
$ bazelisk test //src/test/shell/integration:minimal_jdk_test   # Pass
```

**Comment by meteorcloudy** [comment]
@cushon Can you take a look at this?

**Comment by meteorcloudy** [comment]
If https://github.com/bazelbuild/bazel/commit/18c17dab8fece0a02b53911711ebba497e7fea2a doesn't have fundamental problem, we can always increase the limit of  test_size_less_than_312MB.

**Comment by cushon** [comment]
cc @comius 

This change switched to using the stock OpenJDK 11.0.15 javac instead of the vendored one.

The change is due to this patch in the custom vendored javac: https://github.com/google/error-prone-javac/commit/cb15a5810d5ae85894d72cbe88c7bc75e93469c4.

The bytecode size of `//src/main/java/com/google/devtools/build/lib/bazel:BazelServer_deploy.jar` increases from about 41MB to 41.6, and the change is from extra synthetic bridge methods.

I think it probably makes sense to just increase the threshold for the size test.
