### ISSUE TITLE
Enabling the user to request messages from remote execution

### ISSUE THREAD

**Issue by exoson** [bazelbuild/bazel#15336]
### Description of the feature request:

Bazel gets RemoteExecuteResponses with a field messages when using remote execution: https://github.com/bazelbuild/remote-apis/blob/2af1c432ce11b01e46cf70d7933f71a3310282d6/build/bazel/remote/execution/v2/remote_execution.proto#L1376
Currently these messages are only printed for test actions when the test has failed. It would be great to be able to request bazel to unconditionally print those.

### What underlying problem are you trying to solve with this feature?

Buildbarn sends paths to the action results and the action CAS entry through the messages interface. We would need some way of accessing this data unconditionally in the build event stream.

### Which operating system are you running Bazel on?

N/A

### What is the output of `bazel info release`?

N/A

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
N/A
```

**Comment by coeuvre** [comment]
I think these messages are printed for **any** actions that are failed. But since the protocol says the message should be also displayed when user requested explicitly, yes, Bazel should provide a way for user to request it.

**Comment by exoson** [comment]
How about something like https://github.com/bazelbuild/bazel/pull/15557

**Comment by exoson** [comment]
https://github.com/bazelbuild/bazel/pull/15557 Fixed this. Closing
