### ISSUE TITLE
Public bazel binary target for integration testing

### ISSUE THREAD

**Issue by gonzojive** [bazelbuild/bazel#15332]
### Description of the feature request:

I'm writing integration tests that require a bazel binary.

I was attempting to write these tests like I would write other such tests: Add the bazel repository to my WORKSPACE file and depend on the executable target from the project as a "data" attribute in my `go_test`.

I don't see any public targets I can depend on to make this work. Is the following the right rule?
"//scripts/packages:bazel-sh-with-jdk"

https://github.com/bazelbuild/bazel-integration-testing/blob/master/tools/repositories.bzl seems to be out of date

### What underlying problem are you trying to solve with this feature?

I would like to write hermetic tests of my bazel tooling (https://github.com/gonzojive/bazelgopackagesdriver).

### Which operating system are you running Bazel on?

Ubuntu x86_64

### What is the output of `bazel info release`?

release 5.1.1

### Have you found anything relevant by searching the web?

This repository provides relevant binaries but is out of date:
https://github.com/bazelbuild/bazel-integration-testing/blob/master/tools/repositories.bzl

**Comment by brentleyjones** [comment]
https://github.com/bazel-contrib/rules_bazel_integration_test might be of use to you.

**Comment by meteorcloudy** [comment]
Sounds like https://github.com/bazel-contrib/rules_bazel_integration_test  is the solution ;)
