### ISSUE TITLE
Make rlocation function works with wildcard [duplicate of #4334]

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#1533]
For example, `junit_jar=$(rlocation io_bazel/third_party/junit/junit-*.jar)` should return the right result.

**Comment by dslomov** [comment]
Is this still blocking 0.4?

**Comment by meteorcloudy** [comment]
No

**Comment by laszlocsomor** [comment]
Duplicate of https://github.com/bazelbuild/bazel/issues/4334
