### ISSUE TITLE
Enable github discussion for this repo to discuss matters about bazel

### ISSUE THREAD

**Issue by beingminimal** [bazelbuild/bazel#15343]
### Description of the feature request:

Enable github discussion for this repo to discuss matters about bazel
Benefits
- People can open discussion before opening an issue, which will help to decrease the number of issues being opened in this repo.
- People can vote for features implementation and bug fixes so contributors can prioritise easily for their contribution
- Past discussions can be referenced to solve the same errors or bugs or questions, which can save community time
- We can categorize groups for discussion like github has done here https://github.com/github/feedback/discussions/categories/copilot-feedback

Hey @hicksjoseph @lberki 
Please enable github discussion and categorize it to drive communication in a healthy way like we do in slack channels.
We will be so grateful to you if you enable this in favour of the community. 

Awaiting your response.
Thanks a lot for everything.

**Comment by sventiffe** [comment]
@jdob let's discuss this request

**Comment by meisterT** [comment]
This was done some time ago, see https://github.com/bazelbuild/bazel/discussions
