### ISSUE TITLE
Bazel architecture changing doesn't rerun repository rules

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#15350]
### Description of the bug:

When switching between bazel architectures of the same bazel version on macOS M1 machines, repository rules do not get re-run, leading to potential failures. You have to run a `bazel clean --expunge` to recover.

```
% ./bazelisk-darwin run hello
INFO: Analyzed target //:hello (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:hello up-to-date:
  bazel-bin/hello_/hello
INFO: Elapsed time: 0.116s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
hi

% arch -x86_64 ./bazelisk-darwin run hello
Starting local Bazel server and connecting to it...
ERROR: /private/tmp/archexample/BUILD:3:10: While resolving toolchains for target //:hello: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
ERROR: Analysis of target '//:hello' failed; build aborted:
INFO: Elapsed time: 9.674s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (35 packages loaded, 238 targets configured)
FAILED: Build did NOT complete successfully (35 packages loaded, 238 targets configured)
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Using rules_go, and this attached project:
[archexample.zip](https://github.com/bazelbuild/bazel/files/8564868/archexample.zip) on an M1 machine run:

```
./bazelisk-darwin run hello
```

and then

```
arch -x86_64 ./bazelisk-darwin run hello
```

Note: the bazelisk binary in this zip is the fat binary, but the same happens if you download the specific arches separately and run them.

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 5.1.1

**Comment by meteorcloudy** [comment]
I think the reason is that we never record the current architecture in the marker file of repository rules. Is there any environment variable we can declare as the dependency of repository rule here: https://github.com/bazelbuild/bazel/blob/master/tools/cpp/cc_configure.bzl#L144 ?

**Comment by brentleyjones** [comment]
Wouldn't we want all repository rules to rerun though? Seems we should put the arch in the marker.

**Comment by keith** [comment]
As a workaround folks could use some random variable to store that value 🙃. That might be a fine enough solution given this is likely only going to happen during Apple's Intel -> arm transition

**Comment by meteorcloudy** [comment]
> Wouldn't we want all repository rules to rerun though? Seems we should put the arch in the marker.

I don't think so. For example, all http_archive repo rules shouldn't rerun, the arch change won't affect what source you download from the URL, right?

**Comment by brentleyjones** [comment]
Ahh, yes. I mean all repositories that run repositories rule (i.e. `local_repository` and their native equivalents).

**Comment by meteorcloudy** [comment]
>  all repositories that run repositories rule

I don't quite understand this? What do you mean exactly? `local_repository` is a native repository rule. 

I think this really depends on how a repository rule is implemented, is it depending on architecture specific things. And I guess the `environs` attribute is a good way to declare such dependency.

**Comment by keith** [comment]
I'd say given the rarity, it would be practical to just invalidate everything like changing the bazel version would

**Comment by meteorcloudy** [comment]
>  like changing the bazel version would

This is not true. Changing a bazel version (eg. 5.1.0 -> 5.1.1) will not invalidate everything. Only if the starlark semantic changes, see https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryFunction.java;l=97

**Comment by meteorcloudy** [comment]
I think we should try to fix this for local_config_cc, but not sure which env var will be the best to reflect the architecture.

**Comment by brentleyjones** [comment]
What I meant by my comment is that repository rules can, and do, look at the architecture and make decisions based on that. They usually reach out with a shell command to determine that. So all `local_repository` rules at a minimum, and ideally any other native ones that do something similar, should be invalidated.

Or like Keith said, let's just invalidate everything when the arch changes, as it's not a normal thing to be happening anyway, and the user wouldn't be surprised if the world has to be reevaluated.

**Comment by meteorcloudy** [comment]
> Or like Keith said, let's just invalidate everything when the arch changes, as it's not a normal thing to be happening anyway, and the user wouldn't be surprised if the world has to be reevaluated.

OK, I don't feel strongly against this. Feel free to send a PR to add the arch info to the marker data: Or like Keith said, let's just invalidate everything when the arch changes, as it's not a normal thing to be happening anyway, and the user wouldn't be surprised if the world has to be reevaluated.

**Comment by keith** [comment]
https://github.com/bazelbuild/bazel/pull/16417
