### ISSUE TITLE
Bazel 5.0.0: Operation not permitted using bazel coverage with sandboxfs 

### ISSUE THREAD

**Issue by SimonVleugels** [bazelbuild/bazel#15363]
### Description of the bug:

Running `bazel coverage` using sandboxfs on unittests in docker result in `Operation not permitted` errors.

Bazel logs:
```
root@fcbeec7e9e2c:/unittests# bazel coverage --config=remotejava --config=coverage --config=sandbox --sandbox_debug unittests
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Using default value for --instrumentation_filter: "^//".
INFO: Override the above default with --instrumentation_filter
INFO: Analyzed target //:unittests (48 packages loaded, 808 targets configured).
INFO: Found 1 test target...
INFO: Mounting sandboxfs instance on /root/.cache/bazel/_bazel_root/6ead8fc09c749551b9e243753df404bc/sandbox/sandboxfs
FAIL: //:unittests (see /root/.cache/bazel/_bazel_root/6ead8fc09c749551b9e243753df404bc/execroot/__main__/bazel-out/k8-fastbuild/testlogs/unittests/test.log)
Target //:unittests up-to-date:
  bazel-bin/unittests
INFO: Leaving sandboxfs mounted because of --sandbox_debug
INFO: Elapsed time: 64.899s, Critical Path: 6.01s
INFO: 40 processes: 15 internal, 24 processwrapper-sandbox, 1 worker.
INFO: Build completed, 1 test FAILED, 40 total actions
//:unittests                                                             FAILED in 0.0s
  /root/.cache/bazel/_bazel_root/6ead8fc09c749551b9e243753df404bc/execroot/__main__/bazel-out/k8-fastbuild/testlogs/unittests/test.log

INFO: Build completed, 1 test FAILED, 40 total actions
```

Test logs:
```
[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 1 test.
ln: failed to create symbolic link '/root/.cache/bazel/_bazel_root/6ead8fc09c749551b9e243753df404bc/sandbox/sandboxfs/24/__main__/bazel-out/k8-fastbuild/testlogs/unittests/_coverage/gcov': Operation not permitted
cp: cannot create regular file '/root/.cache/bazel/_bazel_root/6ead8fc09c749551b9e243753df404bc/sandbox/sandboxfs/24/__main__/bazel-out/k8-fastbuild/testlogs/unittests/_coverage/bazel-out/k8-fastbuild/bin/_objs/unittests/test_hello_world.pic.gcno': Operation not permitted
external/bazel_tools/tools/test/collect_cc_coverage.sh: line 152: /root/.cache/bazel/_bazel_root/6ead8fc09c749551b9e243753df404bc/sandbox/sandboxfs/24/__main__/bazel-out/k8-fastbuild/testlogs/unittests/_coverage/gcov: No such file or directory
external/bazel_tools/tools/test/collect_cc_coverage.sh: line 157: /root/.cache/bazel/_bazel_root/6ead8fc09c749551b9e243753df404bc/sandbox/sandboxfs/24/__main__/bazel-out/k8-fastbuild/testlogs/unittests/_coverage/gcov: No such file or directory
external/bazel_tools/tools/test/collect_cc_coverage.sh: line 167: /root/.cache/bazel/_bazel_root/6ead8fc09c749551b9e243753df404bc/sandbox/sandboxfs/24/__main__/bazel-out/k8-fastbuild/testlogs/unittests/_coverage/_cc_coverage.gcov: Operation not permitted
rm: cannot remove '*.gcov': No such file or directory
cp: cannot create regular file '/root/.cache/bazel/_bazel_root/6ead8fc09c749551b9e243753df404bc/sandbox/sandboxfs/24/__main__/bazel-out/k8-fastbuild/testlogs/unittests/_coverage/bazel-out/k8-fastbuild/bin/src/_objs/hello-greet/hello-greet.pic.gcno': Operation not permitted
external/bazel_tools/tools/test/collect_cc_coverage.sh: line 152: /root/.cache/bazel/_bazel_root/6ead8fc09c749551b9e243753df404bc/sandbox/sandboxfs/24/__main__/bazel-out/k8-fastbuild/testlogs/unittests/_coverage/gcov: No such file or directory
external/bazel_tools/tools/test/collect_cc_coverage.sh: line 157: /root/.cache/bazel/_bazel_root/6ead8fc09c749551b9e243753df404bc/sandbox/sandboxfs/24/__main__/bazel-out/k8-fastbuild/testlogs/unittests/_coverage/gcov: No such file or directory
external/bazel_tools/tools/test/collect_cc_coverage.sh: line 167: /root/.cache/bazel/_bazel_root/6ead8fc09c749551b9e243753df404bc/sandbox/sandboxfs/24/__main__/bazel-out/k8-fastbuild/testlogs/unittests/_coverage/_cc_coverage.gcov: Operation not permitted
rm: cannot remove '*.gcov': No such file or directory
```

Bazel flags:
```
--java_runtime_version=remotejdk_11
--experimental_split_coverage_postprocessing 
--experimental_fetch_all_coverage_outputs 
--experimental_use_sandboxfs 
--strategy TestRunner=processwrapper-sandbox 
--sandbox_debug
```

When further analyzing the bazel cache we see that indeed the permissions of the `_coverage` directory is too limited (no write permissions) and thus the `collect_cc_coverage.sh` script doesn't have the permissions to create the `gcov` symbolic link in the `_coverage` dir.
```
ls -alF /root/.cache/bazel/_bazel_root/6ead8fc09c749551b9e243753df404bc/sandbox/sandboxfs/24/__main__/bazel-out/k8-fastbuild/testlogs/unittests/
total 0
drwxr-xr-x 2 root root 2 Apr 28 10:10 ./
drwxr-xr-x 2 root root 2 Apr 28 10:10 ../
dr-xr-xr-x 2 root root 2 Apr 28 10:10 _coverage/
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

We have created a small Dockerfile based on Ubuntu, which installs Bazel 5.0.0 ([explained here](https://docs.bazel.build/versions/main/install-ubuntu.html#install-on-ubuntu)) and sandboxfs ([explained here](https://docs.bazel.build/versions/main/sandboxing.html#sandboxfs))

- Download and extract: [unittests.tar.gz](https://drive.google.com/file/d/1wwfd1-wK0_Bz8NijmXToZxaG5kbXj4k4/view?usp=sharing)
- Build image based on Ubuntu: `cd unittests && docker build --tag unittest-example .`
- Start docker container: `docker run -ti -v <path to unittest dir>:/unittests --privileged --rm unittest-example`
- Run bazel coverage (will download jdk): `cd /unittests && bazel coverage --config=remotejava --config=coverage --config=sandbox --sandbox_debug unittests`

### Which operating system are you running Bazel on?

Ubuntu 22.04 docker image. Also reproducible in centos7 container and on native centos7

### What is the output of `bazel info release`?

release 5.0.0

### Have you found anything relevant by searching the web?

This issue is related to [issue-15307](https://github.com/bazelbuild/bazel/issues/15307), but now with a reproducible example.

**Comment by SimonVleugels** [comment]
@c-mita any progress on this issue? This is a blocking issue for updating our buildsystem to bazel 5

**Comment by SimonVleugels** [comment]
We got the coverage working.

- In Bazel 4.2.0 it was required to use [this patch](https://github.com/bazelbuild/bazel/issues/4685#issuecomment-579692958). Apparently it's also still required in Bazel 5.0.0 (refactored to apply on v5). 

- Removing `--experimental_split_coverage_postprocessing` and `--experimental_fetch_all_coverage_outputs` ([issue-4685](https://github.com/bazelbuild/bazel/issues/4685#issuecomment-1088473824)). Because those result in empty `coverage.dat` files.

**Comment by c-mita** [comment]
With regards to the sandboxfs issues, the only fix I can see is to add the following:

```
    for (PathFragment input : inputs.getFiles().keySet()) {
      dirsToCreate.add(input.getParentDirectory());
    }
```
to `SandboxfsSandboxedSpawn::createFileSystem` (https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/sandbox/SandboxfsSandboxedSpawn.java;l=191).
This is basically what happens for the regular sandboxing system; all directories are created with write permissions.

I'm not a good person to judge if this is a suitable change or not. @meisterT, can you help here?

Adding the coverage directory as an output doesn't work because that'll cause its content to be copied back out of the sandbox; this fails when `--experimental_split_coverage_postprocessing` is enabled because that means it'll attempt to copy files into the `_coverage` dir initially created by the test action which loses its write permissions after the test action has finished.

**Comment by meisterT** [comment]
Lars is the best person to comment here, but he is currently OOO so you have to wait a little bit.

**Comment by larsrc-google** [comment]
Yes, it would be appropriate to create the directories for the inputs. That would add a lot of directories to create. It'd be best to use the code in src/main/java/com/google/devtools/build/lib/sandbox/SandboxHelpers.java, which has been optimized a fair bit by now.

**Comment by haneul** [comment]
any updates on this?

**Comment by benjaminp** [comment]
217fafe2b492de7349547cc3be2b9eef38628055
