### ISSUE TITLE
maven_test is failing on CI

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1537]
See http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/128/console.  It times out locally, too, so I'm guessing the SHA-1 checking is wrong.

**Comment by katre** [comment]
git bisect fingered commit c760f133604877e7b6d8ac3f2bcb9b13b0983f4e: Check maven_jar sha1s for validity (https://github.com/bazelbuild/bazel/commit/c760f133604877e7b6d8ac3f2bcb9b13b0983f4e).

**Comment by katre** [comment]
And reverting that commit causes the tests to begin passing again.
