### ISSUE TITLE
Does bazel support visual studio vs2019 debug mode?

### ISSUE THREAD

**Issue by hitbuyi** [bazelbuild/bazel#15376]
When tensorflow .lilb and tensorflow.dll are generated by 
`
bazel build --config=v1  --config=opt   //tensorflow
`

they can be loaded and works well in visual studio 2019 Release mode,  BUT failed in debug mode
So if I want to build tensorlfow.lib  which can be used by vs2019's debug mode, how to choose bazel options ?
in other words,  selecting  bazel build options  equals to cmake's  Debug option

**Comment by meteorcloudy** [comment]
Replace `--config=opt` with `--config=dbg` may work.
