### ISSUE TITLE
Support relative label_flag values relative to the label_flag rule definition

### ISSUE THREAD

**Issue by shahms** [bazelbuild/bazel#15370]
### Description of the feature request:

`label_flag()` rules allow setting label-valued flags to targets, but those targets must be absolute.  This can make using this flag awkward as the valid labels will frequently (though not always) reside in the same package as the flag definition.  Even the [example](https://github.com/bazelbuild/examples/tree/HEAD/rules/starlark_configurations/label_typed_build_setting) uses this layout.  Allowing labels relative to the rule would make the experience of using these flags much more user friendly.

It *should* just be a matter of providing context to the `LABEL.convert()` call at https://github.com/bazelbuild/bazel/blob/2992ed9e4bde6921294c347fccb577cd70faa937/src/main/java/com/google/devtools/build/lib/rules/LabelBuildSettings.java#L69 but I'm unsure.

### What underlying problem are you trying to solve with this feature?

Improving the user experience for the common case of label_flag values.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 5.0.0

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
git@github.com:shahms/kythe.git
afc2b6cb5bc09625a293b20979527608e2298c86
afc2b6cb5bc09625a293b20979527608e2298c86
```

**Comment by gregestren** [comment]
To clarify, do you mean relative labels in the `.bzl` file that defines the rule that has an attribute which references the flag? Can you link the line (or repaste what specifically you're asking here)?

**Comment by shahms** [comment]
No, specifically labels relative to the BUILD file which defines the named flag.  Using the linked example:

```
load(":defs.bzl", "tool", "toolbox")

# Define a label_flag (or setting) using the built in bazel rules.
# It's default value it the default target this flag should point to. 
label_flag(name = 'tool', build_setting_default = ":hammer")

# A target that depends on the label flag.
toolbox(name = "my-toolbox")

# Some targets that are potential values of the label flag.
tool(name = "hammer")
tool(name = "screwdriver")
```

It would be nice to allow for:
`bazel build :my-toolbox --//starlark_configurations/label_typed_build_setting:tool=:screwdriver` rather than requiring `bazel build :my-toolbox --//starlark_configurations/label_typed_build_setting:tool=//starlark_configurations/label_typed_build_setting:screwdriver`.

**Comment by Wyverald** [comment]
I don't think this is a good idea. Having the flag value be from a diffrent "base package" than the build target seems like it could muddle the waters too much, when all it does is save a few keystrokes (which you can define --config settings for in your .bazelrc file anyhow).

**Comment by shahms** [comment]
I don't think the objection makes sense, especially for the common case of having label-valued build flags defined in the same package as a reasonable set of expected values for that flag and fact that, at least in my experience, it's rare for there to be but a singular build target with which the flag value's package could be confused.  The package which contains the flag definition, however, is a logical (to me) context in which to interpret relative values.

Defining an alias in a `.bazelrc` is only viable if you're working in a project for which that alias is reasonable globally, rather than, say, a large monorepo with many different subprojects.

**Comment by Wyverald** [comment]
Consider `bazel build :foo @repo//pkg:flag=:value`, where `:foo` refers to `@//bar:foo. You might say that `:value` refers to `@repo//pkg:value`. What about `bazel build :foo @repo//pkg:flag=//pkg:value`? Is it `@//pkg:value` or `@repo//pkg:value`?

Worse, if there are repo mappings, this change might even be backwards incompatible -- `bazel build :foo @repo//pkg:flag=@repo//pkg:value` could mean different things depending on what repo mappings `@repo` has, if we adopted this change.

**Comment by gregestren** [comment]
I see what you're proposing. Thanks for clarifying.

I also worry that overloading the interpretation of `:foo` on the command line adds API complexity. I'm also not sure it's the norm for values to be defined in the same package as the flag: one common use case IMO is when the flag represents an interface that different project owners can implement in their respective places. I do acknowledge the "same package" pattern can be real and legitimate, though.

Stepping back, what scenarios are you trying to model? When the set of expected values is in the same package, I can imagine alternate models. But it really depends on what you're trying to do.

Marking as P3 while we discuss.

**Comment by shahms** [comment]
Thanks, Greg. I didn't have anything specific in mind at the moment. This came up when I was looking into label-valued flags to help someone out who was trying to use a string-valued setting with an existing rule set. I noticed that the label-flag implementation an example lacked a context but that resulted in pretty repetitive values.

More concretely I could see a hypothetical with something like the protobuf full runtime versus lite being selected for a project via something like:
`--//third_party/protobuf:runtime=full` vs `--//third_party/protobuf:runtime=lite` while still allowing users to specify their own runtime via label if necessary.

Definitely not high priority, just seemed like a potential usability win for label-valued flags.

**Comment by gregestren** [comment]
Acknowledged. Let's keep this conversation transcript for reference now.
