### ISSUE TITLE
[5.2.0] Wrong encoding of filename in bazel action inputs

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#15398]
Forked from #14381

**Comment by ckolli5** [comment]
https://github.com/bazelbuild/bazel/pull/15447

**Comment by meteorcloudy** [comment]
This change cannot be cleanly cherry picked to 5.2, see https://github.com/bazelbuild/bazel/pull/15455

**Comment by meteorcloudy** [comment]
This change cannot be cleanly cherry picked to 5.2, see https://github.com/bazelbuild/bazel/pull/15455
