### ISSUE TITLE
Bazel not using the latest CoverageOutputGenerator code

### ISSUE THREAD

**Issue by gwjo** [bazelbuild/bazel#15396]
### Description of the bug:

Bazel is using version 2.5 of the coverage_output_generator (see [distdir_deps.bzl](https://github.com/bazelbuild/bazel/blob/master/distdir_deps.bzl#L276-L278)), which dates from October 2020:

```
<Key>bazel_coverage_output_generator/releases/coverage_output_generator-v2.5.zip</Key>
<Generation>1601544711356173</Generation>
<MetaGeneration>1</MetaGeneration>
<LastModified>2020-10-01T09:31:51.356Z</LastModified>
<ETag>"f2c7b30d375402c0083ad888e5add849"</ETag>
<Size>4221347</Size>
```

This is missing some important fixes, eg #8731, resulting in not all files being included in the coverage output,

Can a new version of the coverage_out_generator be published and the distribution updated to use it?

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

n/a

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 5.1.0

### Have you found anything relevant by searching the web?

#11585 tracked an earlier instance of this same problem - the CoverageOutputGenerator package being stale.

**Comment by meteorcloudy** [comment]
@sgowroji Coverage related issues should be assigned to team-Rules-Server ;)
