### ISSUE TITLE
Easy to mistakenly install bazel without specifying "--user"

### ISSUE THREAD

**Issue by adrianludwin** [bazelbuild/bazel#1540]
When installing Bazel for the first time, I made the fairly obvious mistake of omitting the "--user" flag. The error I got back suggested I should use "sudo," which I did. Since I don't seem to be the only person to make this mistake (cf the title of #962), perhaps if the installer is about to error out due to insufficient permissions, it would be better to say something like:

`If you are just installing this for yourself, use --user, but if you would like it to be accessible to everyone on the machine, ensure you have access to...`

**Comment by katre** [comment]
The error I get does not mention sudo, it says:

```
The Bazel installer must have write access to /usr/local/bin!

Usage: bazel-0.3.0-jdk7-installer-linux-x86_64.sh [options]
```

and then prints the usage string.

What version of the installer are you using?

**Comment by adrianludwin** [comment]
My mistake, I simply interpreted the lack of permissions as "I need to use sudo." I then avoided looking a few lines down to see the help text that referenced "--user".

Again, it's a bit of an embarrassing mistake, I only filed the issue because I found someone else who made the same mistake. So I'm just suggesting a slight change to the message.
