### ISSUE TITLE
Documentation issue: Visibility

### ISSUE THREAD

**Issue by abz041** [bazelbuild/bazel#15409]
Documentation URL: https://docs.bazel.build/versions/main/visibility.html

**Comment by sgowroji** [comment]
Hello @abz041, Can you please elaborate your query with complete details. Thanks!

**Comment by sgowroji** [comment]
Hello @abz041, Please find the latest documentation on [Visibility](https://bazel.build/concepts/visibility) and above shared. is not the latest. And reach us back if you still have any further queries on the same.  Thanks!
