### ISSUE TITLE
Misleading error message "The include path './bin/gcov' is not normalized."

### ISSUE THREAD

**Issue by UlrichEckhardt** [bazelbuild/bazel#15410]
### Description of the bug:

The error message has two issues:

- It mentions an include path, but it has nothing to do with "include".
- It says "normalized", but what does that even mean?

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Define a C++ toolchain and use "./something" as path for one of the tools.

### Which operating system are you running Bazel on?

Ubuntu, MS Windows

### What is the output of `bazel info release`?

release 5.1.1

### Any other information, logs, or outputs that you want to share?

This error seems to come from CcToolchainProviderHelper.java:
```
      if (!PathFragment.isNormalized(pathStr)) {
        throw new IllegalArgumentException("The include path '" + pathStr + "' is not normalized.");
      }
```
I'd suggest using `"The path fragment '" + pathStr + "' for tool '" +tool.getFirst() + "' is not normalized.");` or something like that.

BTW: The docstring for `PathFragment.isNormalized()` says 

> Returns true if the passed path contains uplevel references ".." or single-dot references "."

...which is the exact opposite of what it actually does.

BTW2: Interestingly, Bazel doesn't complain when the path is something like `foo///bar`.

**Comment by comius** [comment]
@c-mita Can you triage?
