### ISSUE TITLE
Can't type "bazel help" while a build is in progress in the same workspace

### ISSUE THREAD

**Issue by adrianludwin** [bazelbuild/bazel#1541]
This is easy to work around (just chdir out of the workspace) but it would be nice if "bazel help" would work from within a workspace even if the build is in progress.

**Comment by ulfjack** [comment]
Yes, this is a known issue. Unfortunately, it's not easy to fix. I've made some changes towards fixing this, but we're not there yet.

**Comment by meisterT** [comment]
Closing in favor of #532
