### ISSUE TITLE
Allow native repo rule usage in module extension impl functions

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#15412]
Right now we can't use native repo rules in module extension impl functions. We should fix that.

Example:

```bzl
def _impl(ctx):
  native.local_repository(name="foo", path="bar")
my_extension=module_extension(implementation=_impl)
```

**Comment by fmeum** [comment]
@Wyverald If it helps, I could starlarkify `local_repository` and `new_local_repository`. Now that `repository_ctx.workspace_root` is available, making fully-featured replacements should be possible.

Assuming that using `bind` in module extensions is a bad idea, this would cover all native rules. Maybe making native repo rules work in module extension wouldn't even be necessary anymore?

**Comment by wondfor** [comment]
> `new_local_repository`

when i use bazel test, i want deps some *.so， in /opt/buildtools/, special ,i run remotely with buildfarm, is there a example in bzlmod

**Comment by Wyverald** [comment]
Closing in favor of https://github.com/bazelbuild/bazel/issues/18285
