### ISSUE TITLE
cannot install tensorflow from source

### ISSUE THREAD

**Issue by lecterquadpartisan** [bazelbuild/bazel#1542]
Hi, trying to build tensorflow from source. Getting the error message below -

"/home/lec/Downloads/tensorflow/tensorflow/tools/proto_text/BUILD:31:1: Linking of rule '//tensorflow/tools/proto_text:gen_proto_text_functions' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -o bazel-out/host/bin/tensorflow/tools/proto_text/gen_proto_text_functions ... (remaining 31 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1"

**Comment by katre** [comment]
Can you please clarify:

1. What source repository you are using
2. What bazel version you are using
3. What compiler you have installed
4. What bazel command-line you are calling to get this error

**Comment by lecterquadpartisan** [comment]
Environment info

Bazel 0.3.0

Operating System: Ubuntu 16.04
Installed version of CUDA and cuDNN: CUDA 8.0, cuDNN 5

Compiler : gcc 4.9

Ran this step :
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

**Comment by lecterquadpartisan** [comment]
Repository used :
git clone https://github.com/tensorflow/tensorflow

**Comment by damienmg** [comment]
Hi can you run with --verbose_failures?

Also is there a reason to file a bug to bazel instead of TensorFlow?

**Comment by hermione521** [comment]
No response for 2 weeks, so close. Feel free to reopen when come back.
