### ISSUE TITLE
Test for supported sandboxing falsely fails when client is killed during startup

### ISSUE THREAD

**Issue by brian-peloton** [bazelbuild/bazel#1543]
The test for determining if sandboxing is supported sometimes fails when it shouldn't if the client is killed at just the wrong time. I've seen the usual `WARNING: Sandboxed execution is not supported on your system [...] turn off this warning via --ignore_unsupported_sandboxing.` message from multiple machines which do support sandboxing. The message is printed with every build command until the Bazel server process is restarted, and then it works fine. It seems like it only happens when the client is killed (via ctrl+c from a terminal or SIGTERM) when the server is first starting up.

**Comment by philwo** [comment]
Interesting. The "is sandboxing supported" field is indeed cached across the entire lifetime of the server. So if we get this check wrong, we'll never revisit that until you shutdown and restart the server.

I'll think about what we can do here.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
