### ISSUE TITLE
bazel-5.1.1-installer-linux-x86_64.sh: 83: Bad substitution

### ISSUE THREAD

**Issue by liuyang77886** [bazelbuild/bazel#15456]
### Description of the bug:

(tf2) test@test-VirtualBox:/home/soft$ sh bazel-5.1.1-installer-linux-x86_64.sh
Bazel installer
---------------

Bazel is bundled with software licensed under the GPLv2 with Classpath exception.
You can find the sources next to the installer on our release page:
   https://github.com/bazelbuild/bazel/releases

#

## Build information
   - [Commit](https://github.com/bazelbuild/bazel/commit/0f5dc11)
bazel-5.1.1-installer-linux-x86_64.sh: 83: Bad substitution
(tf2) test@test-VirtualBox:/home/soft$ sha256sum  bazel-5.1.1-installer-linux-x86_64.sh
b5c3dd502159440810a07c0cf4ab8d6e64d083180eb0e1bde166612624348eff  bazel-5.1.1-installer-linux-x86_64.sh

**Comment by sgowroji** [comment]
Hello @liuyang77886, Could you please elaborate your above request with complete details. Thanks!

**Comment by sgowroji** [comment]
Closing this issue as there is no significant  update  from long duration.

**Comment by ahassan2995** [comment]
Hello I need help to install bazel via WSL and I have ubunto version Ubuntu 20.04.5 LTS

and I get this error when I ever I try to install it?
![image](https://user-images.githubusercontent.com/38376775/219124263-be41e290-a315-47e2-b6a5-6e3e7a27868d.png)

I downloaded the bazel installation files from this link
https://github.com/bazelbuild/bazel/releases/download/5.3.0/bazel-5.3.0-installer-linux-x86_64.sh

**Comment by ahassan2995** [comment]
and this is the ubuntu version 
![image](https://user-images.githubusercontent.com/38376775/219124841-f459d6b8-9d0f-499d-aac6-5eaaf4793b26.png)

**Comment by ZhaoWeir** [comment]
问题解决了么?
