### ISSUE TITLE
remote_coverage_tools / coverage_output_generator-v2.6.zip lacks provenance, instructions to build from source

### ISSUE THREAD

**Issue by ghost** [bazelbuild/bazel#15459]
### Description of the bug:

Inside each of the java_tools distribution artifacts is a README.md including instructions to rebuild the artifacts from source.

Example from https://github.com/bazelbuild/java_tools/releases/download/java_v11.7.1/java_tools_linux-v11.7.1.zip

```markdown
This Java tools version was built from the bazel repository at commit hash 190533739ce4457cd5a3b31573fc2ae66f92d53e
using bazel version 5.1.1 on platform linux.
To build from source the same zip run the commands:

$ git clone https://github.com/bazelbuild/bazel.git
$ git checkout 190533739ce4457cd5a3b31573fc2ae66f92d53e
$ bazel build //src:java_tools_prebuilt.zip
```

However remote_coverage_tools / coverage_output_generator-v2.6.zip lacks comparable information. As a result, end users have no idea where these bits came from or how to patch and compile this artifact from source.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```console
$ wget https://mirror.bazel.build/bazel_coverage_output_generator/releases/coverage_output_generator-v2.6.zip
$ unzip coverage_output_generator-v2.6.zip
$ ls
all_lcov_merger_tools_deploy.jar  
BUILD  
coverage_output_generator-v2.6.zip  
WORKSPACE
```

Observe that there is no README. Additionally there are no breadcrumbs in the included `all_lcov_merger_tools_deploy.jar`. (I see no hints of build stamping.)

### Which operating system are you running Bazel on?

Linux (CentOS 8)

### What is the output of `bazel info release`?

release 5.1.1

**Comment by comius** [comment]
cc @c-mita

**Comment by beasleyr-vmw** [comment]
This is still valid today.

**Comment by ulfjack** [comment]
I believe the coverage output generator jar is built from here: https://github.com/bazelbuild/bazel/blob/master/tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator/Main.java

**Comment by hauserx** [comment]
Just for reference, seems the build instructions are here, and looks like building it is a manual process:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/BUILD
```
# To generate an updated version of CoverageOutputGenerator:
# 1. bazel build tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator:coverage_output_generator_zip
# 2. Copy and rename the zip file with a new version locally.
# 3. Upload the file under https://mirror.bazel.build/bazel_coverage_output_generator/releases.
# 4. Update //workspace_deps.bzl and //tools/test/extensions.bzl to point to the new release.
```
