### ISSUE TITLE
Cannot build host Linux PIE executables with Bazel 5.1.1

### ISSUE THREAD

**Issue by digit-google** [bazelbuild/bazel#15468]
### Description of the bug:

I am trying to build PIE host Linux executables with Bazel, which, according to the documentation, should be as simple as using the `--force_pic` flag when invoking `bazel build` [1], however this clearly does not work.

See https://github.com/digit-google/bazel-experiments/tree/main/pic-vs-pie for a small Bazel workspace that tries to 

[1] https://docs.bazel.build/versions/main/command-line-reference.html#flag--force_pic

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See https://github.com/digit-google/bazel-experiments/tree/main/pic-vs-pie and invoke:

```
bazel build --force_pic //:pic_mode
bazel-bin/pic_mode
```

The output should be something like:

```
executable mode: pie, library mode: pie
```

But is:

```
executable mode: pic, library mode: pic
```

Alternatively, invoke the `run_tests.sh` script which will try to run `bazel build` with other configuration switches (e.g. `--features=pie`, as well as build various variants of the program + library). It seems that the only way to get the executable and its library built with PIE is to force the `-fPIE` compiler and linker flags explicitly, which is inconvenient.

It is possible to force everything with `--copt=-fPIE --linkopts=-fPIE` but I also need to generate shared library in my projects which definitely require `-fPIC` instead. Also, the same `cc_library()` in my projects can be a dependency of both an executable and a shared library, and in this case would need to be compiled twice (once in PIE mode, once in PIC mode).

### Which operating system are you running Bazel on?

Linux Debian

### What is the output of `bazel info release`?

release 5.1.1

### Have you found anything relevant by searching the web?

I didn't find anything related to this on Github, Stackoverflow or the mailing list.

### Any other information, logs, or outputs that you want to share?

I work on the Fuchsia team at Google (https://fuchsia.dev) and am looking at how we can port our platform build system to Bazel. Being able to build PIE executables and PIC shared libraries in a single build invocation is a very strong requirement for us.

I am looking for a way to do that with native cc_binary() and cc_library() rules, instead of introducing Fuchsia-specific macros or rules that would not be portable to other systems. In particular because we are looking forwards to reusing existing BUILD.bazel files for several hundreds open-source projects that we depend on.

**Comment by pcjanzen** [comment]
The way that `--force_pic` works is by compiling all of the objects with `-fPIC` and then linking with `-pie`, and then putting those objects into both the `.so` and the `.a`.  I think you're actually creating position independent executables (you can check with `file`) despite the fact that you're not compiling any of the objects with `-fPIE`. 

If you really care about the distinction between `-fPIC` and `-fPIE` then you would have to create a custom toolchain with a modified version of the `pic` feature: https://cs.opensource.google/bazel/bazel/+/master:tools/cpp/unix_cc_toolchain_config.bzl;l=371?q=pic_feature&ss=bazel%2Fbazel
that does something like

```
                flag_groups = [
                    flag_group(flags = ["-fPIC"], expand_if_available = "pic"),
                    flag_group(flags = ["-fPIE"], expand_if_not_available = "pic"),
                ],
```

 and then _not_ use `--force_pic`.

**Comment by digit-google** [comment]
Thanks for the clarification.

I think I was confused because PIE is a somewhat ambiguous acronym: it can reference both the fact that an executable is position-independent (which can be achieved with code compiled with `-fPIC` or `-fPIE`) or a way to generate machine code at compile time (enforced by `-fPIE`).

So it looks like Bazel does not support compiling with `-fPIE` by default, but a toolchain-based solution would work. Do you know if this would support building shared libraries, and their dependencies with `-fPIC` though?

**Comment by digit-google** [comment]
Just to update this topic a little, my investigation shows that we will need a custom toolchain as well as transitions to achieve our goal (which essentially mandates that some libraries will be built twice in certain build invocations, once with -fPIC, and once with -fPIE).

I confirm that this is not a bug in Bazel, I was confused by terminology. The current design of cc_binary and cc_library simply provides different semantics than I expected or what I need, but there are ways around this. I'm closing this. Thanks.
