### ISSUE TITLE
Bazel@HEAD `bazel test` fails with "'@remote_coverage_tools' is not visible from repository '@bazel_tools'"

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#15478]
### Description of the bug:

Bazel after 156d9c092c9c6f7985c601c38709ede3992dae06 seems to fail to run tests with bzlmod since `@bazel_tools`, which is now a special module, lacks visibility into the `@remote_coverage_tools` repository.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```shell
$ git clone https://github.com/fmeum/rules_jni
$ git checkout b97529401471351c3f43434879a1ad889ba4e918
$ cd rules_jni/tests
$ USE_BAZEL_VERSION=2ad10c38e8f4ce794d8763fcec4fe88efb15f2fb bazel test --config=bzlmod //analysis/jni_headers:tests
...
INFO: Build completed successfully, 1 total action
//analysis/jni_headers:provider_test                           PASSED in 0.1s
$ USE_BAZEL_VERSION=156d9c092c9c6f7985c601c38709ede3992dae06 bazel test --config=bzlmod //analysis/jni_headers:tests
ERROR: /home/fhenneke/.cache/bazel/_bazel_fhenneke/27ab8d6bcf9e822e87fc15cbcbda5200/external/bazel_tools/tools/test/BUILD:36:6: no such package '@remote_coverage_tools//': The repository '@remote_coverage_tools' could not be resolved: Repository '@remote_coverage_tools' is not visible from repository '@bazel_tools' and referenced by '@bazel_tools//tools/test:coverage_report_generator'
ERROR: Analysis of target '//analysis/jni_headers:provider_test' failed; build aborted:
```

### Which operating system are you running Bazel on?

Linux/macOS/Windows (as confirmed by CI)

### What is the output of `bazel info release`?

development version

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

Used Bazelisk to fetch 156d9c092c9c6f7985c601c38709ede3992dae06

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
156d9c092c9c6f7985c601c38709ede3992dae06
```

It might be a good idea to update the question: Many people think they are supposed to run this opaque command in their project's Git repo. Most people probably don't build Bazel from source, but use Bazelisk to fetch a prebuilt version.

**Comment by fmeum** [comment]
@Wyverald Sorry for being the "human downstream failure" again. I really hope https://github.com/bazelbuild/bazel/commit/156d9c092c9c6f7985c601c38709ede3992dae06 can be fixed forward easily.

**Comment by Wyverald** [comment]
FYI I'm working on this, just running into some difficulty with my local toolchain setup. Will try to get it fixed today.
