### ISSUE TITLE
GCOV 9+ race condition (and suggested workaround)

### ISSUE THREAD

**Issue by ishaangandhi** [bazelbuild/bazel#15485]
### Description of the bug:

When using GCOV 9+, some coverage is dropped.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

BUILD:
```
cc_test(
    name="test_lib0",
    srcs=["test_lib0.cpp"],
    deps = [
        ":lib",
    ],
)
    
cc_test(
    name="test_lib1",
    srcs=["test_lib1.cpp"],
    deps = [
        ":lib",
    ],
)

cc_library(
    name="lib",
    srcs=["lib.h", "lib.cpp"],
)
```
test_lib_*.cpp:
```
#include "lib.h"
int main() {
    int b = both(0) + both(1);
    return 0;
}
```

lib.h:
```
int both(int input);

```

lib.cpp:
```
int both(int input) {
    if (input)
        return 1;
    return 0;
}
```

## Command
```
$ bazel coverage ...
//src:test_lib0               PASSED in 0.4s
  /var/tmp/igandhi/bazel-output-user-root/src/test_lib0/coverage.dat
//src:test_lib1               PASSED in 0.4s
```

You can see that only one of the two files got coverage. Which one of the two changes from invocation to invocation. I believe this is a race condition caused by this line: https://github.com/bazelbuild/bazel/blob/1a7083ebc76ab4c7100cc92913555596ffdc2049/tools/test/collect_cc_coverage.sh#L166

If I change that from `mv` to `cp`, I get coverage for both files. If you add `--jobs=1` you also get coverage for both files.

### Which operating system are you running Bazel on?

Red Hat 8

### What is the output of `bazel info release`?

4.2.1

**Comment by c-mita** [comment]
I can't reproduce this; do you have any bazelrc files in effect? Is the second coverage.dat file truly missing? What do the test logs say?

**Comment by ishaangandhi** [comment]
Yeah, there are bazelrc files in effect, but because its a race condition, perhaps its only happening sometimes? The test logs don't report anything out of the ordinary. The second coverage.dat file truly is missing. Could you perhaps run this in a loop with `--jobs 32`? Or maybe copy and paste the test target and source n times for a large value of n (99?) When I do that, I see about 1/3 of the coverage is missing.

**Comment by ishaangandhi** [comment]
Which version of gcov are you using?

**Comment by ishaangandhi** [comment]
I apologize if this isn't a very useful or actionable bug report. Is there something else I could provide besides a bazelrc that might help
I should also note I am running bazel on a slow NFS mount, which might make it easier for this bug to show up?
