### ISSUE TITLE
Documentation issue: Configurations

### ISSUE THREAD

**Issue by oldsj** [bazelbuild/bazel#15484]
Documentation URL: https://docs.bazel.build/versions/main/skylark/config.html

The "[End to end example](https://github.com/bazelbuild/examples/tree/HEAD/rules/starlark_configurations/basic_build_setting)"
link 404s. Looks like a folder got renamed and it should point to https://github.com/bazelbuild/examples/tree/main/configurations/basic_build_setting

**Comment by sgowroji** [comment]
Fixed. It will be reflecting in the next release at this [page](https://bazel.build/rules/config). Thanks!
