### ISSUE TITLE
Bazel build failing locally on MacBook with Apple M1 chip

### ISSUE THREAD

**Issue by Rishabh1901** [bazelbuild/bazel#15495]
### Description of the bug:

I'm trying to build locally using Bazel. My Bazel version is Bazel@3.7.1 , Golang version is go@1.14.15, and it gives error when I try to build. 

ERROR: An error occurred during the fetch of repository 'org_golang_google_grpc':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_rishabhshukla/877117b30352da854febc88b94403321/external/bazel_gazelle/internal/go_repository.bzl", line 126, column 17, in _go_repository_impl
                fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
Error in fail: failed to fetch org_golang_google_grpc: fetch_repo: unexpected end of JSON input

Initially, I was using go@1.18, then also it was giving an error. Can someone help me with this? 

### Which operating system are you running Bazel on?

Mac OS Monterey (Version 12.3.1)

### What is the output of `bazel info release`?

release 3.7.1

**Comment by sgowroji** [comment]
Hello @Rishabh1901, Can you please provide complete steps to reproduce the above error. Thanks!

**Comment by keith** [comment]
Note that bazel didn't really support m1 machines until 4.x, and rules_go had some changes as well. I would recommend updating both

**Comment by meteorcloudy** [comment]
As @keith suggested, please try with newer version of Bazel and rules_go.
