### ISSUE TITLE
python_stub_template.txt doesn't find runfiles associated with pyz file.

### ISSUE THREAD

**Issue by jonathan-enf** [bazelbuild/bazel#15502]
### Description of the bug:

In this scenario:
* a py_binary file ("foo.py) has a data dependency on another py_binary ("bar.py")
* foo.py calls bar as a subprocess.

This works if invoked as "blaze run :foo" because "foo" executes in a context where a "foo.runfiles" directory exists, and all of "bar.py"'s dependencies are easily found in "foo.runfiles" directories.

However, if "foo.zip" is built using the "--build_python_zip" option, "python3 foo.zip" is invoked, execution of the "bar" resource will fail because the python stub that is compiled into "bar" is calling FindModuleSpace.  FindModuleSpace searches for any runfiles directory that is named dot-runfiles (".runfiles").  Unfortunately, the runfiles directory created when CreateModuleSpace unzips the python zip archive is only named "runfiles" (no dot).  Thus, execution fails.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
git clone git@github.com:jonathan-enf/bazel.git
cd bazel/src/test/py/bazel
bazel run :foo  # this succeeds
bazel build :foo-zip
python3 ../../../../bazel-bin/src/test/py/bazel/foo.zip  # this fails
```

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

release 5.1.1

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
$ git remote get-url origin; git rev-parse master; git rev-parse HEAD
git@github.com:jonathan-enf/bazel.git
96fa291cb1515706ece1be7f9510ff4ed2a40625
96fa291cb1515706ece1be7f9510ff4ed2a40625
```

### Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

My reproduction case:

```
$ blaze run :foo
INFO: Analyzed target //src/test/py/bazel:foo (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //src/test/py/bazel:foo up-to-date:
  bazel-bin/src/test/py/bazel/foo
INFO: Elapsed time: 0.165s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
/home/jonathan/.cache/bazel/_bazel_jonathan/6927f7db41681c7b78bbbe76b3487de9/execroot/io_bazel/bazel-out/k8-fastbuild/bin/src/test/py/bazel/bar
hello world.
bum be bum bum.
goodbye world.

$ blaze build :foo-zip
INFO: Analyzed target //src/test/py/bazel:foo-zip (0 packages loaded, 1 target configured).
INFO: Found 1 target...
Target //src/test/py/bazel:foo-zip up-to-date:
  bazel-bin/src/test/py/bazel/foo.zip
INFO: Elapsed time: 0.204s, Critical Path: 0.03s
INFO: 3 processes: 2 internal, 1 linux-sandbox.
INFO: Build completed successfully, 3 total actions
(master*) [681] ~/git/bazel/src/test/py/bazel

$ python3 ~/git/bazel/bazel-bin/src/test/py/bazel/foo.zip
/tmp/Bazel.runfiles_iz2vifz9/runfiles/io_bazel/src/test/py/bazel/bar
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_iz2vifz9/runfiles/io_bazel/src/test/py/bazel/bar", line 392, in <module>
    Main()
  File "/tmp/Bazel.runfiles_iz2vifz9/runfiles/io_bazel/src/test/py/bazel/bar", line 292, in Main
    module_space = FindModuleSpace()
  File "/tmp/Bazel.runfiles_iz2vifz9/runfiles/io_bazel/src/test/py/bazel/bar", line 122, in FindModuleSpace
    raise AssertionError('Cannot find .runfiles directory for %s' % sys.argv[0])
AssertionError: Cannot find .runfiles directory for /tmp/Bazel.runfiles_iz2vifz9/runfiles/io_bazel/src/test/py/bazel/bar
goodbye world.
```

**Comment by comius** [comment]
This probably should be addressed in pyz archive - but that would break current users. 
So providing a second archive that's correctly packaged is probably better?

**Comment by comius** [comment]
cc @rickeylev
