### ISSUE TITLE
load() doesn't work inside function

### ISSUE THREAD

**Issue by jart** [bazelbuild/bazel#1550]
If a WORKSPACE file calls a function containing `native.load()` then the imported symbol will not be available to the function namespace in subsequent statements.

### Further explanation

Bazel projects oftentimes specify a `foo_repositories()` function so dependent repositories can easily schlep in transitive dependencies. (Here's the [convention](https://github.com/bazelbuild/rules_closure/blob/master/closure/repositories.bzl) used by Closure Rules.) But what if one of those dependencies is another Bazel project following the same convention?

Assume I wanted to define the following:

```bzl
def io_bazel_rules_closure():
  native.local_repository(
      name = "io_bazel_rules_closure",
      path = "/usr/local/google/home/jart/code/rules_closure",
  )
  load("@io_bazel_rules_closure//closure:defs.bzl", "closure_repositories")
  closure_repositories(
      omit_gson = True,
      omit_guava = True,
      omit_icu4j = True,
      omit_json = True,
      omit_jsr305 = True,
      omit_jsr330_inject = True,
      omit_protobuf_java = True,
  )
```

Then I get the following error: 

```
function 'load' does not exist.
```

If I change `load` to `native.load` then I get a different error:

```
function 'closure_repositories' does not exist.
```

The workaround is that all repositories providing a foo_repositories() function must be explicitly specified in the WORKSPACE file. This makes the external dependency convention that Closure Rules has adopted less useful.

**Comment by damienmg** [comment]
This is WAI. Bazel needs to knows the dependencies before analysis. This could be lifted a little but with a lot of engineering. Unless we have a strong use case for it, it is not going to be implemented.

Closing but feel free to argue :)

**Comment by davidzchen** [comment]
Do we have a way to make this less cumbersome yet? Skydoc has a similar problem since it depends on `rules_saas`, and currently, users would have to copy and paste a rather significant chunk of workspace rules:

```python
git_repository(
    name = "io_bazel_rules_sass",
    remote = "https://github.com/bazelbuild/rules_sass.git",
    tag = "0.0.1",
)
load("@io_bazel_rules_sass//sass:sass.bzl", "sass_repositories")
sass_repositories()

git_repository(
    name = "io_bazel_skydoc",
    remote = "https://github.com/bazelbuild/skydoc.git",
    tag = "0.0.3",
)
load("@io_bazel_skydoc//skylark:skylark.bzl", "skydoc_repositories")
skydoc_repositories()
```

**Comment by davidzchen** [comment]
I can move the `git_repository` for sass into `skydoc_repositories`, but then it is still not possible to `load()` and call `sass_repositories()` from within the `skydoc_repositories` macro:

```
ERROR: /Users/dzc/Projects/bazelbuild/skydoc/skylark/skylark.bzl:267:3: function 'sass_repositories' does not exist
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension 'skylark/skylark.bzl' has errors
INFO: Elapsed time: 0.135s
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by damienmg** [comment]
It's a really complex issue, making load available from macro make cycle inside a macro possible:
e.g.:
```
def macro():
   native.local_repository('foo', ...)
   native.load("@foo//:bar.bzl", "baz")
```

Then calling macro would require foo to be defined because of the load statement, However this whole statement is evaluated inside the same sky function. There is probably a solution to this but it would make the code really complex and take a long time to make right.

**Comment by jart** [comment]
Please help me understand why that's a cycle, because I'm very curious about why this issue is so complicated. Please keep in mind I know very little about the Bazel core.

I would have assumed that Skylark does evaluation of the WORKSPACE file in a single pass evaluator, where the WORKSPACE file AST is treated like it's the body of a function def. Therefore it would stand to reason that the things which can be done in the WORKSPACE file can also be done when the evaluator recurses into the function defs it loads. But it sounds like there might be a separate evaluator that happens in multiple passes.

**Comment by pauldraper** [comment]
> Unless we have a strong use case for it, it is not going to be implemented.

The original case by @jart is well-stated. I thinks that as good as the use case gets:

> The workaround is that all repositories providing a foo_repositories() function must be explicitly specified in the WORKSPACE file. This makes the external dependency convention that Closure Rules has adopted less useful.
