### ISSUE TITLE
[CC Shared Library] CC Shared Library does not link in all transitive dependencies

### ISSUE THREAD

**Issue by ankit-agarwal1999** [bazelbuild/bazel#15500]
### Description of the bug:

On release 5.1.1 and I believe on latest master as well (since there haven't been very many changes), it is possible for cc shared library to not link in all of its transitive dependencies referred to by CcInfo providers. I am currently trying to migrate some of my features for cc_binary(linkshared = 1) to cc_shared_library.  

The issue happens in the experimental_cc_shared_library.bzl file itself, in the `_filter_inputs` function. There is a nother function, called in `_filter_inputs` called `_separate_static_and_dynamic_link_libraries` which are supposed to separate which linker inputs have owners that should be linked in statically and which ones have owners that should be linked in dynamically. 

However, this list is gathered from the GraphNodeInfo aspect, but the owners are compared against the CcInfo linker input list which is in `dependency_linker_inputs`. It is possible that the union of the outputs `link_statically_labels` and  `link_dynamically_labels` don't contain all of `dependency_linker_inputs`. The `cc_binary` version of this rule would link in all inputs in the `dependency_linker_inputs`, from what I would gather. 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I ran into this issue when trying to link against grpc and in particular against upb generated c files. 

### Which operating system are you running Bazel on?

Linux 18.04 (in docker)

### What is the output of `bazel info release`?

Have our own custom release but its mostly just 5.1.1

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

Built it by forking bazel and building it from source in docker.

**Comment by sgowroji** [comment]
Hello @ankit-agarwal1999, Could you please share the steps to reproduce the above error. Thanks!

**Comment by sgowroji** [comment]
Closing this issue as there is no significant update from long duration. Please feel free to reopen if the above issue still exists. Thank you!
