### ISSUE TITLE
jvm_maven_import_external not using .netrc file content

### ISSUE THREAD

**Issue by guw** [bazelbuild/bazel#15506]
### Description of the bug:

When defining repository access with `.netrc` file it looks like `jvm_maven_import_external` is not using this. This is unexpected as `.netrc` should work everywhere in Bazel.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create dependency consumption with `jvm_maven_import_external` from a password protected source.
Create `.netrc` file.

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

release 5.1.0

**Comment by sgowroji** [comment]
Hello @guw, There is already an open issue with same details [here](https://github.com/bazelbuild/bazel/issues/13709). Please confirm if the above issue is not relevant to it. Thanks!

**Comment by guw** [comment]
Thanks. I was overlooking the details. Indeed, fixing #13709 would address this one.
