### ISSUE TITLE
Bazel 5.1.1 bootstrap with llvm fails

### ISSUE THREAD

**Issue by railwaycat** [bazelbuild/bazel#15501]
### Description of the bug:

I tried to bootstrap bazel 5.1.1 with llvm/clang, following this document: https://bazel.build/install/compile-source#bootstrap-bazel.

I end with the following error:

```
$ env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" bash ./compile.sh
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
INFO: Analyzed target //src:bazel_nojdk (367 packages loaded, 10179 targets configured).
INFO: Found 1 target...
[0 / 31] checking cached actions
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.devtools.build.lib.unsafe.StringUnsafe (file:/tmp/bazel_D833Wx7h/archive/libblaze.jar) to constructor java.lang.String(byte[],byte)
WARNING: Please consider reporting this to the maintainers of com.google.devtools.build.lib.unsafe.StringUnsafe
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
ERROR: /tmp/bazel_D833Wx7h/out/external/com_github_grpc_grpc/BUILD:1254:16: Compiling src/core/lib/iomgr/event_engine/timer.cc failed: undeclared inclusion(s) in rule '@com_github_grpc_grpc//:grpc_base_c':
this rule is missing dependency declarations for the following files included by 'src/core/lib/iomgr/event_engine/timer.cc':
  'bazel-out/k8-opt/bin/external/com_google_absl/absl/synchronization/synchronization.cppmap'
  'bazel-out/k8-opt/bin/external/upb/upb.cppmap'
Target //src:bazel_nojdk failed to build
INFO: Elapsed time: 106.197s, Critical Path: 11.62s
INFO: 628 processes: 157 internal, 471 local.
FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Install the dependencies document requires: `openjdk-11-jdk`, `zip`, `unzip`.
2. Install clang.
3. download the dist package of bazel 5.1.1: https://github.com/bazelbuild/bazel/releases/download/5.1.1/bazel-5.1.1-dist.zip and unzip it.
4. `export CC=clang` and `export CXX=clang++`.
5. run command: `env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" bash ./compile.sh`

### Which operating system are you running Bazel on?

ubuntu 20.04

### What is the output of `bazel info release`?

N/A. bootstrapping, no bazel command available. 

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
Not build from a git repo.
```

### Have you found anything relevant by searching the web?

No. 

### Any other information, logs, or outputs that you want to share?

I tried bootstrapping with gcc and it is good, only fails on clang/llvm.

**Comment by meteorcloudy** [comment]
Similar issue here: https://github.com/bazelbuild/bazel/issues/15359, but we never officially supported bootstrap with clang though.

**Comment by railwaycat** [comment]
Thank you @meteorcloudy! I didn't know bootstrap with llvm/clang is not officially supported.
