### ISSUE TITLE
[Mirror] certificate of mirror.bazel.build has expired

### ISSUE THREAD

**Issue by dhiller** [bazelbuild/bazel#15515]
### Please list the URLs of the archives you'd like to mirror:

The SSL sertificate seems to have expired just now:

```
$ curl -v https://mirror.bazel.build/                                                                                                                                                                      *   Trying 130.211.22.235:443...
* Connected to mirror.bazel.build (130.211.22.235) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, certificate expired (557):
* SSL certificate problem: certificate has expired
* Closing connection 0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

See https://github.com/kubevirt/project-infra/pull/2058#issuecomment-1129811612 for reference

**Comment by bretanac93** [comment]
Same happened to me here, my CI pipelines failed due to expired certificate

```shell
2022/05/18 10:00:53 could not download Bazel: HTTP GET https://releases.bazel.build/4.2.2/release/bazel-4.2.2-linux-x86_64 failed: Get "https://releases.bazel.build/4.2.2/release/bazel-4.2.2-linux-x86_64": x509: certificate has expired or is not yet valid: current time 2022-05-18T10:00:53Z is after 2022-05-18T09:43:13Z
```

**Comment by dmivankov** [comment]
same for https://docs.bazel.build

**Comment by ar3s3ru** [comment]
This looks more like a P1 than a P2 👀

**Comment by gabrielrussoc** [comment]
FWIW, overwriting repositories like `@remote_coverage_tools` on my own workspace seems to be a no-op and Bazel still tries to download from the mirror

**Comment by dmivankov** [comment]
adding ` build --jvmopt=-Dcom.sun.net.ssl.checkRevocation=false` to `.bazelrc` may be a temporary workaround

**Comment by neumann-nico** [comment]
Works again!

**Comment by dmivankov** [comment]
cert is restored :tada:

**Comment by fweikert** [comment]
Sorry for the problems!

We actually switched to automatically managed SSL certificates to avoid such problems. However, the update process got confused by a change to the domain lists and just stalled (without notifying us). Manually building and deploying new certificates solved the problem.

**Comment by jaronsummers** [comment]
As a follow-up, is it possible/desirable to add a second download source for the odd archives here, including remote_download_tools?

https://github.com/bazelbuild/bazel/blob/master/distdir_deps.bzl#L291

**Comment by fweikert** [comment]
cc @Wyverald wrt the last question
