### ISSUE TITLE
bazel 3.7.2 can't build TensorFlow Lite 2.7.0 for iOS

### ISSUE THREAD

**Issue by snowuyl** [bazelbuild/bazel#15510]
### Description of the bug:

I am trying to build TensorFlow Lite 2.7.0 for iOS on macOS 12.3.1 m1 (arm64 CPU). But it failed to build it successfully.  

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

git clone https://github.com/tensorflow/tensorflow tensorflow-2.7.0_ios
cd tensorflow-2.7.0_ios
git checkout r2.7
./configure
default for all except the following option
Do you wish to build TensorFlow with iOS support? [y/N]: y
iOS support will be enabled for TensorFlow.
bazel build --config=ios_fat -c opt //tensorflow/lite/ios:TensorFlowLiteC_framework

### Which operating system are you running Bazel on?
macOS 12.3.1 m1 (arm64 CPU)

### What is the output of `bazel info release`?

release 3.7.2

### Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

ERROR: /Users/andyueng/samba/workspace_TensorFlow2/tensorflow-2.7.0_ios/tensorflow/lite/ios/BUILD:104:21: Bundling Preprocessed_TensorFlowLiteC_framework failed (Exit 127): bundletool failed: error executing command 
  (cd /private/var/tmp/_bazel_andyueng/6c55a359b06f2067a8d1d18d335cb317/execroot/org_tensorflow && \
  exec env - \
  bazel-out/host/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool bazel-out/darwin-opt/bin/tensorflow/lite/ios/Preprocessed_TensorFlowLiteC_framework-intermediates/bundletool_control.json)
Execution platform: @local_execution_config_platform//:platform
env: python: No such file or directory
Target //tensorflow/lite/ios:TensorFlowLiteC_framework failed to build
INFO: Elapsed time: 197.909s, Critical Path: 37.87s
INFO: 1960 processes: 150 internal, 1810 local.
FAILED: Build did NOT complete successfully

**Comment by snowuyl** [comment]
How can I force bazel 3.7.2 to use python3 instead python?

**Comment by keith** [comment]
You can try `--host_force_python=PY3`, but you might need to update bazel or provide a local shim for `python` which points to `python3` 😬

**Comment by snowuyl** [comment]
Thanks Keith's reply! I modify command as follows.
bazel build --host_force_python=PY3 --verbose_failures --config=ios --ios_multi_cpus=armv7,arm64 -c opt //tensorflow/lite/ios:TensorFlowLiteC_framework

But bazel still can't build TensorFlow Lite 2.7.0 for iOS. The following is log messages.
INFO: Found 1 target...
ERROR: /Users/andyueng/samba/workspace_TensorFlow2/tensorflow-2.7.0_ios/tensorflow/lite/ios/BUILD:104:21: Bundling Preprocessed_TensorFlowLiteC_framework failed (Exit 127): bundletool failed: error executing command 
  (cd /private/var/tmp/_bazel_andyueng/6c55a359b06f2067a8d1d18d335cb317/execroot/org_tensorflow && \
  exec env - \
  bazel-out/host/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool bazel-out/darwin-opt/bin/tensorflow/lite/ios/Preprocessed_TensorFlowLiteC_framework-intermediates/bundletool_control.json)
Execution platform: @local_execution_config_platform//:platform
env: python: No such file or directory
Target //tensorflow/lite/ios:TensorFlowLiteC_framework failed to build
INFO: Elapsed time: 209.710s, Critical Path: 38.35s
INFO: 1960 processes: 150 internal, 1810 local.
FAILED: Build did NOT complete successfully

**Comment by keith** [comment]
Yea looks like you'll have to try one of the other options then

**Comment by snowuyl** [comment]
I would like to try any options.

**Comment by keith** [comment]
yea i mean the other 2 i mentioned above:

> you might need to update bazel or provide a local shim for python which points to python3 😬

**Comment by snowuyl** [comment]
Unfortunately TensorFlow Lite 2.7.0 can only build with bazel 3.7.2. I also try to create symbolic link for python. But it still can't work.
% which python
/opt/homebrew/bin/python
% ls -al /opt/homebrew/bin/python
lrwxr-xr-x  1 root  admin  25  5 18 11:55 /opt/homebrew/bin/python -> /opt/homebrew/bin/python3

The following is error messages.
INFO: Found 1 target...
ERROR: /Users/andyueng/samba/workspace_TensorFlow2/tensorflow-2.7.0_ios/tensorflow/lite/ios/BUILD:104:21: Bundling Preprocessed_TensorFlowLiteC_framework failed (Exit 127): bundletool failed: error executing command 
  (cd /private/var/tmp/_bazel_andyueng/6c55a359b06f2067a8d1d18d335cb317/execroot/org_tensorflow && \
  exec env - \
  bazel-out/host/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool bazel-out/darwin-opt/bin/tensorflow/lite/ios/Preprocessed_TensorFlowLiteC_framework-intermediates/bundletool_control.json)
Execution platform: @local_execution_config_platform//:platform
env: python: No such file or directory
Target //tensorflow/lite/ios:TensorFlowLiteC_framework failed to build
INFO: Elapsed time: 184.770s, Critical Path: 35.91s
INFO: 1960 processes: 150 internal, 1810 local.
FAILED: Build did NOT complete successfully

**Comment by keith** [comment]
It must not be including `/opt/homebrew/bin` in your `$PATH` (or the `$PATH` it sets instead). You will probably need to inject that somehow, maybe with `--action_env=PATH`

**Comment by snowuyl** [comment]
/opt/homebrew/bin is in my $PATH environment variable.
echo $PATH
/opt/homebrew/opt/python@3.9/libexec/bin:/opt/homebrew/bin:/opt/homebrew/sbin

**Comment by keith** [comment]
Yes but tensorflow may not use that specifically in the build. You can potentially see what path is used for the action that fails by passing -s

**Comment by snowuyl** [comment]
The following is error messages after adding -s option to bazel build command.
SUBCOMMAND: # //tensorflow/lite/ios:Preprocessed_TensorFlowLiteC_framework [action 'Symlinking bazel-out/apl-ios_armv7-opt-ST-96e8508176c3/bin/tensorflow/lite/ios/Preprocessed_TensorFlowLiteC_framework.apple_static_library_lipo.a to bazel-out/darwin-opt/bin/tensorflow/lite/ios/Preprocessed_TensorFlowLiteC_framework-intermediates/TensorFlowLiteC', configuration: b00bf51fbfae70951d8f3ef471cc42e2af1f12a0598889fcbe0e1fcf046c2025, execution platform: @local_execution_config_platform//:platform]
(cd /private/var/tmp/_bazel_andyueng/6c55a359b06f2067a8d1d18d335cb317/execroot/org_tensorflow && \
  exec env - \
  /bin/bash -c 'mkdir -p "$1"; if [[ "$(uname)" == Darwin ]]; then   ln -s "$("$4" "$2")" "$3"; else   cp "$2" "$3"; fi' '' bazel-out/darwin-opt/bin/tensorflow/lite/ios/Preprocessed_TensorFlowLiteC_framework-intermediates bazel-out/apl-ios_armv7-opt-ST-96e8508176c3/bin/tensorflow/lite/ios/Preprocessed_TensorFlowLiteC_framework.apple_static_library_lipo.a bazel-out/darwin-opt/bin/tensorflow/lite/ios/Preprocessed_TensorFlowLiteC_framework-intermediates/TensorFlowLiteC bazel-out/host/bin/external/build_bazel_rules_apple/tools/realpath/realpath)
SUBCOMMAND: # //tensorflow/lite/ios:Preprocessed_TensorFlowLiteC_framework [action 'Bundling Preprocessed_TensorFlowLiteC_framework', configuration: b00bf51fbfae70951d8f3ef471cc42e2af1f12a0598889fcbe0e1fcf046c2025, execution platform: @local_execution_config_platform//:platform]
(cd /private/var/tmp/_bazel_andyueng/6c55a359b06f2067a8d1d18d335cb317/execroot/org_tensorflow && \
  exec env - \
  bazel-out/host/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool bazel-out/darwin-opt/bin/tensorflow/lite/ios/Preprocessed_TensorFlowLiteC_framework-intermediates/bundletool_control.json)
ERROR: /Users/andyueng/samba/workspace_TensorFlow2/tensorflow-2.7.0_ios/tensorflow/lite/ios/BUILD:104:21: Bundling Preprocessed_TensorFlowLiteC_framework failed (Exit 127): bundletool failed: error executing command 
  (cd /private/var/tmp/_bazel_andyueng/6c55a359b06f2067a8d1d18d335cb317/execroot/org_tensorflow && \
  exec env - \
  bazel-out/host/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool bazel-out/darwin-opt/bin/tensorflow/lite/ios/Preprocessed_TensorFlowLiteC_framework-intermediates/bundletool_control.json)
Execution platform: @local_execution_config_platform//:platform
env: python: No such file or directory
Target //tensorflow/lite/ios:TensorFlowLiteC_framework failed to build
INFO: Elapsed time: 389.114s, Critical Path: 36.92s
INFO: 1960 processes: 150 internal, 1810 local.
FAILED: Build did NOT complete successfully

**Comment by snowuyl** [comment]
It can build successfully after upgrading TensorFlow to 2.9.0 and bazel to 5.0.0.
