### ISSUE TITLE
`bazel query //external:<repo> --output=build` result inconsistent with what Bazel does

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#15529]
### Description of the bug:

When one overrides a repository in the embedded WORKSPACE file suffix with one in the main WORKSPACE file, the override takes effect, but `bazel query //external:<repo> --output=build` .

Curiously, this is not the case when one declares two repositories with the same name in the main WORKSPACE file.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create empty workspaces e.g. under `/tmp/t1` and `/tmp/t2`:

```
mkdir -p /tmp/{t1,t2}
touch /tmp/{t1,t2}/WORKSPACE
echo 'filegroup(name="t1")' > /tmp/t1/BUILD
echo 'filegroup(name="t2")' > /tmp/t2/BUILD
```

Then create the main workspace:
```
cat >WORKSPACE <<EOF
local_repository(name="a", path="/tmp/t1")
local_repository(name="a", path="/tmp/t2")
local_repository(name="rules_cc", path="/tmp/t1")
EOF
```

Then observe the following:
* `bazel query @rules_cc//:all`  yields `@rules_cc//:t1`
* `bazel query --output=build //external:rules_cc` yields a `http_archive` rule
* `bazel query @a//:all` yields `@a//:t2`
* `bazel query --output=build //external:a` yields a `local_repository` pointing to `/tmp/t2`

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

5.1.1, also reproduces at HEAD

**Comment by pcjanzen** [comment]
related: https://github.com/bazelbuild/bazel/issues/12947

**Comment by meteorcloudy** [comment]
Close as duplication of https://github.com/bazelbuild/bazel/issues/12947
