### ISSUE TITLE
proguard_whitelister_test fails and build also fails because of it

### ISSUE THREAD

**Issue by takipsizad** [bazelbuild/bazel#15547]
### Description of the bug:

ERROR: C:/users/pc/_bazel_pc/nvciri4m/external/bazel_tools/tools/jdk/BUILD:432:8: In rule 'proguard_whitelister_test', size 'medium' is not a valid size.
ERROR: C:/users/pc/_bazel_pc/nvciri4m/external/bazel_tools/tools/jdk/BUILD:432:8: In rule 'proguard_whitelister_test', timeout 'illegal' is not a valid timeout.
ERROR: Analysis of target '//:libyara' failed; build aborted: error loading package '@bazel_tools//tools/jdk': Package 'tools/jdk' contains errors

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

i have no idea how to reproduce it sadly,trying to build in my config perhaps will work ( simply try building it)

### Which operating system are you running Bazel on?

Windows 10 19043.1288

### What is the output of `bazel info release`?

release 5.1.1

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
https://github.com/VirusTotal/yara
ee6b2363f7d3bcb6b6bbe655ad8a71a451cc3af8
ee6b2363f7d3bcb6b6bbe655ad8a71a451cc3af8
```

### Have you found anything relevant by searching the web?

nope

### Any other information, logs, or outputs that you want to share?

ERROR: C:/users/pc/_bazel_pc/nvciri4m/external/bazel_tools/tools/jdk/BUILD:432:8: In rule 'proguard_whitelister_test', size 'medium' is not a valid size.
ERROR: C:/users/pc/_bazel_pc/nvciri4m/external/bazel_tools/tools/jdk/BUILD:432:8: In rule 'proguard_whitelister_test', timeout 'illegal' is not a valid timeout.
ERROR: Analysis of target '//:libyara' failed; build aborted: error loading package '@bazel_tools//tools/jdk': Package 'tools/jdk' contains errors
INFO: Elapsed time: 0.171s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
    Fetching @local_jdk; fetching

**Comment by sgowroji** [comment]
Hello @takipsizad, Without reproducing steps it is not easy for us to troubleshoot/ find the root cause of the issue. Please provide complete details to work on the above request. Thanks!

**Comment by takipsizad** [comment]
i kinda tried to build, thats it, didnt do something special to reproduce it

**Comment by takipsizad** [comment]
@sgowroji Hello, you may have misunderstood what i was trying to say.
I was trying to report a bug, not to get support.

**Comment by takipsizad** [comment]
https://github.com/bazelbuild/bazel/issues/14891 I have found another related issue, i think the root cause is same here @sgowroji 
( gonna try to downgrade python to 3.8)

**Comment by takipsizad** [comment]
tried and it fixes

**Comment by takipsizad** [comment]
Hello
Root cause was me having Turkish as display language
