### ISSUE TITLE
bzlmod external repo name and copts

### ISSUE THREAD

**Issue by fitzner** [bazelbuild/bazel#15553]
### Description of the bug:

Bzlmod stores modules as external repos in external/\<module\>.\<version\>. By using labels in rules the correct locations are resolved.

However in some cases it is necessary to use copts from cc_binary and cc_library to include further headers and in that case there is no option to define the external workspace via a variable in the rules copts.

Depending on how bzlmod includes external repos the name is different.

*Use of the registry*
bazel_dep(name = "foo", version = "0.1.0")
=> external/foo.0.1.0

*Use of local_path_override*
local_path_override(
    module_name = "foo",
    path = "../projects/foo/"
)
=> external/foo

This behaviour is problematic when referencing an external workspace in the copts.

For an example please see the attachment [example.tar.gz](https://github.com/bazelbuild/bazel/files/8755922/example.tar.gz).

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See example

### Which operating system are you running Bazel on?

MacOS Monterey 12.3.1

### What is the output of `bazel info release`?

release 5.1.1

**Comment by fmeum** [comment]
Not saying this is a good answer, but you can create a `.bzl` file containing:
```python
def canonical_repo_name():
    return native.repository_name()[1:] # Skip over the leading '@'
```
Then, call that function from a BUILD file in `foo` to get the correct name. Caveat: This will not work if `foo` is your (main) workspace as `native.repository_name` returns just `@` in that case - if you replace the return value with `foo` if it is empty, this should work in all situations.

**Comment by fitzner** [comment]
I just stumbled over the following; this could be used as a workaround.

```
def _var_workspace_root_impl(ctx):
    return [
      platform_common.TemplateVariableInfo({
          "WORKSPACE_ROOT": ctx.label.workspace_root,
      }),
    ]

var_workspace_root = rule(
    implementation = _var_workspace_root_impl,
    attrs = {}
)
```

```
var_workspace_root(
    name = "set_workspace_root_var",
)

cc_library(
    name = "test",
    srcs = [
        "src/foo.cc",
        "include/foo_private.h",
    ],
    hdrs = [
        "include/foo.h"
    ],
    copts = ["-I$(WORKSPACE_ROOT)/include"],
    strip_include_prefix = "include",
    linkstatic = True,
    toolchains = [":set_workspace_root_var"],
)
```

**Comment by cameron-martin** [comment]
[This feature](https://github.com/bazelbuild/bazel/issues/16472) would make this unnecessary in one case, which in my experience is the most common case.

**Comment by Wyverald** [comment]
This is partially addressed by the REPO.bazel proposal (https://github.com/bazelbuild/bazel/issues/18077), except that `default_copts` is no longer a thing in Bazel. So I'm keeping this open to figure out next steps.

**Comment by meteorcloudy** [comment]
Bazel also has to work around a similar issue by
https://github.com/bazelbuild/bazel/blob/b264850ef404450e8b1672efd12a9b5de1aa2228/src/tools/bzlmod/utils.bzl#L17-L21

I'll close this one since there is workaround and not much else we can do from Bzlmod side.
