### ISSUE TITLE
[rules_cc]: Bazel 5 is not matching case sensitive file extensions on Windows correctly

### ISSUE THREAD

**Issue by oakad** [bazelbuild/bazel#15550]
### Description of the bug:

Bazel considers ".c" (lowercase c) files to be plain c files and would not apply cxxopts when compiling files with this extension. However, Bazel considers ".C" (uppercase C) files to be C++ files and all the cxxopts apply.

It so happens, that on Windows Bazel will match all the "*.c" files as "C++ sources" because of case insensitive matching. This sort of works for normal compiles, because MSVC compiler tends to silently ignore C++ specific flags passed to compiler when compiling C files.

However, when cross compiling to something like Android, clang will refuse to compile the C sources, because "c++ flags are "not allowed with 'C'".

Some sort of mitigation is necessary here.

It is rather unfortunate, that to this day Bazel has no way to designate plain C files explicitly.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Cross compile any C library on Windows with Android clang compiler.

Compile any C library on Windows and observe C++ flags added to the compiler command line (even though the compilation may work).

### Which operating system are you running Bazel on?

Windows 10

### What is the output of `bazel info release`?

release 5.1.1

**Comment by oakad** [comment]
I would like to further add that Windows now supports case sensitive file name matching which can be enabled on per-directory level. Alas, implementation in com.google.devtools.build.lib.vfs.WindowsOsPathPolicy is totally not friendly to this sort of development - it forces case conversion blindly, which is rather wrong. I'd say, there should be a command line flag to control VFS behaviour on windows, allowing Unix-style behaviour where enabled.

**Comment by oakad** [comment]
Here: https://github.com/oakad/bazel_issue_15550

The issue triggers always on most basic of setups. :-)

On Linux: `bazel run :t1` compiles and runs, no issues, no warnings.

On Windows, with default MSVC toolchain, we get the following warning:

> cl : Command line warning D9002 : ignoring unknown option '-bogus_c++_flag'

The issue here is that t1.c gets classified as C++ source and cxxopt gets applied, incorrectly.

Of course, MSVC goes on to compile the program anyway, because it is lenient like that.

But any cross-compiling, non MSVC based toolchain will break.

**Comment by foxandi** [comment]
Might be related to: https://github.com/bazelbuild/bazel/issues/15073

**Comment by oakad** [comment]
@foxandi  It does look like the same issue.

**Comment by fmeum** [comment]
Appears to be a duplicate of https://github.com/bazelbuild/bazel/issues/15073.
