### ISSUE TITLE
Allow bazel run @tool as shorthand for bazel run @tool//:tool

### ISSUE THREAD

**Issue by emidln-imc** [bazelbuild/bazel#15562]
### Description of the feature request:

Allow `bazel run @tool` as shorthand for `bazel run @tool//:tool`. This is already possible for dependencies in BUILD.bazel files.

Assuming I have an external repo named `jq` with a `BUILD.bazel` in the root and an executable target `jq` inside that BUILD.bazel, I should be able to use:

```
bazel run @jq -- --help
```

instead of the current:

```
bazel run @jq//:jq -- --help
```

### What underlying problem are you trying to solve with this feature?

Allow `bazel run @tool` as shorthand for `bazel run @tool//:tool`.

### Which operating system are you running Bazel on?

Centos 7.9

### What is the output of `bazel info release`?

release 5.1.1

**Comment by fmeum** [comment]
This has been fixed in https://github.com/bazelbuild/bazel/commit/24f6fe802ebb68da71e1e071c9e84c89b4aa0772.
