### ISSUE TITLE
GPG Key expired

### ISSUE THREAD

**Issue by danmacklin10** [bazelbuild/bazel#15563]
### Description of the bug:

The install steps outlined at https://bazel.build/install/ubuntu no longer work as the GPG key expired today at 07:37

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Follow the ubuntu install steps.  You get the error:

` The following signatures were invalid: EXPKEYSIG 3D5919B448457EE0 Bazel Developer (Bazel APT repository key)`

### Which operating system are you running Bazel on?

ubuntu 18.04 lts

**Comment by Wyverald** [comment]
Dupe: https://github.com/bazelbuild/bazel/issues/15558#issuecomment-1136150886
