### ISSUE TITLE
rules_rust are broken on Darwin with Bazel HEAD

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1556]
See http://ci.bazel.io/job/rules_rust/202/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/console

It is broken since http://ci.bazel.io/job/Bazel/685/ 

Ok assigning several people:
  - philwo@ for the inflight release, this is probably a release blocker.
  - kchodorow@ for help because it seems like related to remote repository.
  - davidzchen@ for help on rules_rust
  - and myself because sheriff.

**Comment by philwo** [comment]
Investigating now.

**Comment by damienmg** [comment]
I repro'd it but weirdly even at 609e876996361fba2341a6f5f4ebfdc794849871

**Comment by damienmg** [comment]
It does work with 0.3.0 so let's try to do some jump back

**Comment by damienmg** [comment]
This is fixed at HEAD. Woohoo. Now let me bisect for the must-be cherry-pick

**Comment by damienmg** [comment]
Humm still happens for me at HEAD... weird.

**Comment by damienmg** [comment]
Ok there is something weird in the execroot layout creation.

The local_config_cc does not appears in the execroot even though it is in the external folders of the output base.

@kchodorow : any idea?

**Comment by damienmg** [comment]
Ok I have diagnose the issue:
rules_rust use C++ compilation but have no way to declare a depdency on the c++ compiler (feature not yet existing in skylark). It seems like the external repository link is not created in the execroot until an action that declares the dependency is analyzed.

@kchodorow : I leave this bug assigned to you, we need to fix it ASAP IMO.

@davidzchen: fetch //... is actually fetching everything, ls $(bazel info output_base)/external should show it to you but it does not create the symlink under the execroot which might be your issue on the TF auto-configuration for CUDA.

**Comment by damienmg** [comment]
(leaving @philwo  assigned for cherry-picking the fix in the release)

**Comment by damienmg** [comment]
latest push is broken again.

**Comment by kchodorow** [comment]
Really? Opening a pull request that says "fixes whatever" actually marks the bug as fixed?  Seems like GitHub should wait until the fix is actually merged in...

**Comment by damienmg** [comment]
Great no cherry-pick needed :)
