### ISSUE TITLE
Ubuntu PPA Key Expired

### ISSUE THREAD

**Issue by joeshao1** [bazelbuild/bazel#15565]
### Description of the bug:

Inside Docker, trying to run:

RUN curl https://bazel.build/bazel-release.pub.gpg | apt-key add - \
  && echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" > /etc/apt/sources.list.d/bazel.list \

RUN apt-get update

Same deal as the bugs before (looks like these keys expire every two years around May 24th)

W: GPG error: https://storage.googleapis.com/bazel-apt stable InRelease: The following signatures were invalid: EXPKEYSIG 3D5919B448457EE0 Bazel Developer (Bazel APT repository key) <bazel-dev@googlegroups.com>
E: The repository 'https://storage.googleapis.com/bazel-apt stable InRelease' is not signed.

These seem to get resolved in a day or so, I haven't seen any other issues floating around for 2022 (only comments and tags on old 2020 and 2018 closed versions)

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

RUN curl https://bazel.build/bazel-release.pub.gpg | apt-key add - \
  && echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" > /etc/apt/sources.list.d/bazel.list \

RUN apt-get update

### Which operating system are you running Bazel on?

Docker with a ubuntu 20.04 base

### What is the output of `bazel info release`?

release 5.0.0

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/11470

**Comment by keith** [comment]
https://github.com/bazelbuild/bazel/issues/15558#issuecomment-1136150886

**Comment by joeshao1** [comment]
Looks like since we're downloading a key and putting it in a specific location [this](https://github.com/bazelbuild/bazel/issues/15558#issuecomment-1136348580) answer was pretty relevant
