### ISSUE TITLE
not possible to select platform start with @repo_name

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/bazel#15573]
### Description of the bug:

bazel release: 5.1.1
my repo need be referred by another repo, so my select condition must be start with @repo_name style, but bazel5.1.1 think this is not a valid condition. I think bazel should support a platform condition started with @repo_name style
```
select({
    "@bazel_build_file_repo//platforms:linux_gcc10_aarch64_none_elf": ["--host=armv7-none-eabi"],
    "//conditions:default": [],
}),
```

```
platform(
    name = "linux_gcc10_aarch64_none_elf",
    constraint_values = [
        "@platforms//cpu:aarch64",
        "@platforms//os:linux",
        ":gcc_10",
        ":elf",
    ],
)
```

**Comment by katre** [comment]
Is this different from #15575? As I mentioned in [my recent response on #14604](https://github.com/bazelbuild/bazel/issues/14604#issuecomment-1133046469), we don't currently support using **platform** labels in select, only **constraint values**. For those, using labels in a different repository should work fine.
