### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yangxinliang** [bazelbuild/bazel#15586]
### Description of the bug:

 no such package '@com_google_protobuf//': The repository '@com_google_protobuf' could not be resolved: Repository '@com_google_protobuf' is not defined and referenced by '@build_bazel_rules_swift//tools/worker:compile_with_worker'

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

How to solve this problem?

### Which operating system are you running Bazel on?

bazel

### What is the output of `bazel info release`?

bazel build

**Comment by sgowroji** [comment]
Hello @yangxinliang, Could you please provide complete steps to reproduce the above issue. Thanks!

**Comment by sgowroji** [comment]
As there is no significant update on this issue from long time, We are closing this issue now. Please feel free to reopen if you are still looking resolution for the above query. Thanks!
