### ISSUE TITLE
Documentation issue: Historical documentation has link to file issues, new documentation does not.

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#15584]
Documentation URL: https://docs.bazel.build/versions/main/

On this page and every page on the old documentation site there is a link in the upper right hand corner to create an issue related to that piece of documentation. I cannot do that with the new site in any obvious way.

**Comment by fweikert** [comment]
We recently added two buttons ("report an issue" and "view source") to all pages that actually contain content (e.g. https://bazel.build/start/cpp)
