### ISSUE TITLE
sha256 sum for bazel_nojdk for 61fd06d92706d64fbcef64f0f54cded91c88afff does not match

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#15582]
### Description of the bug:

Obtaining the linux bazel_nojdk and its sha256 checksum from links provided via GCS for the most recent release, `6.0.0-pre.20220517.1`:

https://storage.googleapis.com/bazel-builds/metadata/61fd06d92706d64fbcef64f0f54cded91c88afff.json

It appears that checksumming the linux nojdk binary does not match its checksum.

It **does** match for the previous release, [6.0.0-pre.20220421.3](https://github.com/bazelbuild/bazel/releases/tag/6.0.0-pre.20220421.3)

**Comment by ifoox** [comment]
I also spot checked a few other binaries from the same release and they are also not matching.

**Comment by janakdr** [comment]
Nathan, not sure why I was assigned to this. Is there a doc somewhere that needs to be updated?

**Comment by haxorz** [comment]
> [@janakdr] Nathan, not sure why I was assigned to this. Is there a doc somewhere that needs to be updated?

Afaik, no. Also, `team-Core` is not the most appropriate label since we're not in any way responsible for Bazel releases. @ckolli5 please followup with the Bazel team separately about both of these topics. Apologies if any of the triage documentation was stale (Janak recently transferred off the team) or incorrect (some sort of statement about Bazel releases belonging to `team-Core`).

**Comment by Wyverald** [comment]
For posterity, @fweikert is the go-to person for issues with rolling releases (`X.0.0-preXXXX...`).

**Comment by meteorcloudy** [comment]
Those binaries and hash are uploaded here: https://github.com/bazelbuild/continuous-integration/blob/cb67e5c599732ad8e733a6ea285ff3443b4e768a/buildkite/bazelci.py#L3287-L3343

**Comment by meteorcloudy** [comment]
No Bazel releases are affected, only Bazel binaries built and published at each commit are affected.

**Comment by meteorcloudy** [comment]
This is no longer a problem after rerunning the pipeline to reupload the artifacts.
