### ISSUE TITLE
Release 1.11 - how to use bazelist to build projects

### ISSUE THREAD

**Issue by wangzy0327** [bazelbuild/bazel#15599]
why I cannot use bazelisk or bazel to build project? cannot find bazel,but bazel is downloaded

![image](https://user-images.githubusercontent.com/22990858/171176522-32b853bc-21d9-4ab9-9859-8d2a37a67097.png)

**Comment by Wyverald** [comment]
You need to alias `bazel` to `bazelisk`. Also, please use the proper support channels for questions such as this (this is more relevant for TensorFlow).
