### ISSUE TITLE
json.decode is too strict; fails on duplicate keys

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#15605]
### Description of the bug:

A couple of packages are published to npm with a JSON descriptor which is valid in every context it's used.

However `json.decode` fails on this part of the file:
```
  "typeCoverage": {
    "atLeast": 100,
    "detail": true,
    "strict": true
  },
  "typeCoverage": {
    "atLeast": 100,
    "detail": true,
    "strict": true,
    "ignoreCatch": true
  }
```
More context here:
https://github.com/aspect-build/rules_js/issues/148

I agree with the library author that it's really a Bazel bug, which should follow the https://en.wikipedia.org/wiki/Robustness_principle of "be permissive in what you accept". Author points this out:
https://github.com/wooorm/decode-named-character-reference/issues/2
https://github.com/wooorm/stringify-entities/issues/11

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
json.decode("""
{
  "typeCoverage": {
    "atLeast": 100,
    "detail": true,
    "strict": true
  },
  "typeCoverage": {
    "atLeast": 100,
    "detail": true,
    "strict": true,
    "ignoreCatch": true
  }
}
""")
```

### What is the output of `bazel info release`?

5.x

**Comment by emidln-imc** [comment]
What is the most useful and still rational behavior here? You could plausibly argue four approaches:

1. keep the value of the first key seen
2. keep the value of the last key seen
3. merge the values of duplicates if the value is an object
4. error

**Comment by brandjon** [comment]
Taking the last entry seems preferable over taking the first, since it's more consistent with `dict.update`, the `dict()` constructor, etc. But it's not clear whether that's better or worse than failing. We could also make it an option, i.e. a named arg to decode, but I'm not sure I want to complicate that API.

**Comment by alexeagle** [comment]
ping! @brandjon will you take PRs for this?

**Comment by aherrmann** [comment]
[ECMA-262](https://262.ecma-international.org/13.0/#sec-json.parse) says under 25.5.1.1
> Note 2 In the case where there are duplicate name Strings within an object, lexically preceding values for the same key shall be overwritten.

This aligns with option 2.

**Comment by alexeagle** [comment]
ping! @brandjon would you accept a PR? Another user on Slack tripped over this.

**Comment by tetromino** [comment]
Different JSON parsers diverge on this point: https://stackoverflow.com/questions/21832701/does-json-syntax-allow-duplicate-keys-in-an-object

Javascript, and anything that tries to be compatible with Javascript, of course allows duplicate keys and keeps the last value.

C and C++ based JSON parsers typically don't allow duplicate keys.

I have no strong opinion on which way to go, but given the need to integrate with npm, we may as well follow Javascript's behavior.

**Comment by alexeagle** [comment]
I think the critical observation is that Bazel is meant to be the orchestration for a bunch of third-party package managers and tools, so it should follow the https://en.wikipedia.org/wiki/Robustness_principle
Meaning, even if parsers typically reject some input, Bazel's job is to "be permissive in what it accepts" to maximize compatibility.
Same argument I made for https://github.com/bazelbuild/bazel/commit/c9e2be52a067dd9abf5efa4f5f55bb5b98cf5d3b

**Comment by brandjon** [comment]
Rationale for accepting the change:

* The JSON RFC apparently leaves this unspecified, so we're not prohibited from doing it.
* JavaScript will allow it, with the unsurprising (and consistent with `dict`) semantics that last key wins.
* It supports this Node-related use case.

(The "Robustness principle" can be problematic -- think HTML. But we're maintaining a parser, not writing a new standard.)

**Comment by LavaToaster** [comment]
@brandjon @tetromino I don't suppose you guys know which release this will hit?

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by fmeum** [comment]
Given that this doesn't change the behavior on inputs that didn't hard fail before this change, I would propose to cherry-pick it into 6.2.0. Otherwise it would naturally make its way into 7.0.0.

**Comment by tetromino** [comment]
I am asking for a cherry-pick at https://github.com/bazelbuild/bazel/pull/17868
