### ISSUE TITLE
bazel Windows: Error: Unable to access jarfile C:\\SPB_Data\\_bazel_...\\A-server.jar

### ISSUE THREAD

**Issue by felixf4xu** [bazelbuild/bazel#15601]
### Description of the bug:

Hi,

I installed bazel v 4.2.2 on Windows by downloading the exe file. when I run `bazel version`, I have this error:

```
Error: Unable to access jarfile C:\\SPB_Data\\_bazel_User???\\install\\6ece1c08582de19efc011e4c994a5b03\\A-server.jar
```

Please note the `???` in the path of `SPB_Data\\_bazel_User???\\` and I guess it's because of some unicode char in my Window user name.

I can't change my Windows user name, is there a way to change the default path setting so that bazel can work in it?

### Which operating system are you running Bazel on?

Windows 10

**Comment by sgowroji** [comment]
Hello @felixf4xu, Did you get a chance to go through the resolutions provided in the duplicate [issue](https://github.com/bazelbuild/bazel/issues/11649). Thanks!

**Comment by sgowroji** [comment]
As there is no significant update on this issue for more than 7 days, We are closing this issue now. Please feel free to reopen if you are still looking resolution for the above query. Thanks!
