### ISSUE TITLE
Bazel coverage fails to return coverage results for src code with external in class path

### ISSUE THREAD

**Issue by luyiyang16** [bazelbuild/bazel#15609]
### Description of the bug:

`bazel coverage --instrumentation_filter="^//java/com/…/external/something[/:]"  javatests/com/…/external/something/...:all`

The above bazel command doesn't return coverage .dat file for me.

I suspect is because this line in the source code that filters out my class path: https://github.com/bazelbuild/bazel/blob/master/tools/test/collect_coverage.sh#L233

### Which operating system are you running Bazel on?

mac

### What is the output of `bazel info release`?

release 5.1.1

**Comment by sgowroji** [comment]
Hello @luyiyang16, Is there any way we can reproduce this at our end. Thanks!

**Comment by luyiyang16** [comment]
No longer needed
