### ISSUE TITLE
inaccurate error message with --remote_download_outputs=toplevel

### ISSUE THREAD

**Issue by dmivankov** [bazelbuild/bazel#15612]
### Description of the bug:

enabling just `--remote_download_outputs=toplevel` produces error message
> ERROR: --experimental_remote_download_outputs=minimal requires --experimental_inmemory_jdeps_files to be enabled

which in reality should've been mentioning `--remote_download_minimal` or `--remote_download_outputs=anything_but_all`
https://github.com/bazelbuild/bazel/blob/4879106fabdf4af9395743941987d4297d232296/src/main/java/com/google/devtools/build/lib/bazel/rules/BazelRulesModule.java#L571

**Comment by ckolli5** [comment]
Hey @dmivankov, could you please provide us with the steps to reproduce this issue? Thanks!

**Comment by dmivankov** [comment]
Should be as simple as running
```console
$ bazel build --remote_download_outputs=toplevel
ERROR: --experimental_remote_download_outputs=minimal requires --experimental_inmemory_jdeps_files to be enabled
```
but may depend on whether project has C/C++ or Java targets defined, can try to make a self-contained repro scenario later

**Comment by coeuvre** [comment]
Not relevant anymore because BwoB no longer requires `--experimental_inmemory_jdeps_files`.
