### ISSUE TITLE
platformclasspath_classes folder not writable since 6.0.0-pre.20220517.1

### ISSUE THREAD

**Issue by deepy** [bazelbuild/bazel#15616]
### Description of the bug:

Starting in `6.0.0-pre.20220517.1` the `platformclasspath_classes` is no longer writable which prevents `DumpPlatformClassPath.class` from being deleted.
This is causing our tests to fail when trying to cleanup or work with the directory.

```
rm: cannot remove '/home/deepy/.cache/bazel/_bazel_deepy/8edfe17b4be90513bcf6c070303d6f06/execroot/__main__/bazel-out/k8-fastbuild/bin/external/bazel_tools/tools/jdk/platformclasspath_classes/DumpPlatformClassPath.class': Permission denied
```
```
$ ls -la .
dr-xr-xr-x 2 deepy deepy  4096 Jun  3 10:20 .
drwxr-xr-x 3 deepy deepy  4096 Jun  3 10:20 ..
-r-xr-xr-x 1 deepy deepy 10139 Jun  3 10:20 DumpPlatformClassPath.class
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build `examples/java-tutorial` with `--output_base`
```
bazel --output_base=mytest build //:ProjectRunner
```
Then `rm -rf mytest`

```
rm: cannot remove './mytest/execroot/__main__/bazel-out/k8-fastbuild/bin/external/bazel_tools/tools/jdk/platformclasspath_classes/DumpPlatformClassPath.class': Permission denied
```

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

6.0.0-pre.20220526.1

**Comment by fmeum** [comment]
This changed with https://github.com/bazelbuild/bazel/commit/ae523f82d39daf01cf31e40733de0c6345f0935c. Before that commit, the output of the action that compiles `DumpPlatformClassPath` was a non-writable class file, now it is a non-writable directory containing a class file. The same would apply to any other directory output produced by a Bazel rule. While probably working as intended from the perspective of Bazel (rule outputs should not be writable), it is inconvenient that a simple `rm -rf` isn't able to remove the tree. 

@deepy Can you use `chmod -R u=rwx mytest` before doing the `rm -rf mytest`?

**Comment by deepy** [comment]
The problem there is that when we add changing permissions into the mix we can't rely on automatic cleanup by other tools any longer and with multiple operating systems in the mix this becomes even less fun to deal with.
And if we delete it too eagerly it's going to impact test execution times :disappointed:

**Comment by fmeum** [comment]
Have you tried `bazel clean --expunge --output_base=my_test`? This is Bazel-specific, but should work on all OSes.

**Comment by deepy** [comment]
We've worked around this, thank you for the explanation, all the information, and the workaround suggestions!

**Comment by hashar** [comment]
I encounter the same issue with Bazel 5.3.1. To start a fresh build we do `find bazel-out -delete` and that chokes on the lack of writable permission ([see also our issue tracker](https://phabricator.wikimedia.org/T320251))
