### ISSUE TITLE
Add `rules_rust` to recommended rules

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/bazel#15625]
### Description of the feature request:

I think [rules_rust](https://github.com/bazelbuild/rules_rust) fits the criteria [here](https://github.com/bazelbuild/bazel-website/blob/master/recommended-rules.md) for becoming a recommended set of rules (https://bazel.build/rules#recommended-rules). I'm filing this issue per the guidance there as well.

**Comment by UebelAndre** [comment]
cc @hlopko, the current Googler admin for `rule_rust`.

**Comment by hlopko** [comment]
+1 @Wyverald 

I think the criteria are a bit outdated (I think "No change in Bazel may break a recommended rule (with the default set of flags). If it happens, the change should be fixed or rolled back." is not followed anymore), so I don't know what the purpose of recommended rules is besides the increased visibility for Bazel newcomers.

In any case I think `rules_rust` do meet the criteria and I support adding them to the set of recommended rules.

**Comment by Wyverald** [comment]
@philomathing Could we make a decision on where to host this "recommended rules" thing before 6.0? Would be nice to somewhat officially say "people, please go and look at the rules-SIG recommended list from now on".

**Comment by sventiffe** [comment]
Is this depending on a 6.0 release? You could setup the external page and link to it from https://bazel.build/rules#recommended-rules later. 

Can the external page be mirrored so that we can change the link in case the page goes down for any reason?

**Comment by alexeagle** [comment]
The BCR official launch is now complete, which is the last prerequisite mentioned on this thread. I guess we should bring this up at the SIG meeting on 24 January again.

**Comment by UebelAndre** [comment]
I would still like this.

**Comment by Emasoft** [comment]
We need this. We also need official Rust support in Bazel.

**Comment by alexeagle** [comment]
What does official support mean to you?

**Comment by UebelAndre** [comment]
As a maintainer of `rules_rust`, it would certainly feel good to have the rules on the recommended page. Are there any reservations to including it?

**Comment by Wyverald** [comment]
This has dragged on long enough -- I say we just add it to the recommended page. The "rules catalog" will come when it comes. Happy to review a PR.

**Comment by UebelAndre** [comment]
Where does the change need to be made?

**Comment by Wyverald** [comment]
Go to https://bazel.build/rules#recommended-rules, and click "View source"
