### ISSUE TITLE
Bazel build for rules_docker#java_image fails with "No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type. Maybe --incompatible_use_cc_configure_from_rules_cc has been flipped and there is no default C++ toolchain added in the WORKSPACE file"

### ISSUE THREAD

**Issue by xushaoxiao** [bazelbuild/bazel#15629]
### Description of the bug:

While resolving toolchains for target //cover:cover_app_image.binary: No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type. Maybe --incompatible_use_cc_configure_from_rules_cc has been flipped and there is no default C++ toolchain added in the WORKSPACE file? See https://github.com/bazelbuild/bazel/issues/10134 for details and migration instructions.

### Which operating system are you running Bazel on?

bazel build ...

### What is the output of `bazel info release`?

5.1.1

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

INFO: Invocation ID: 3799285a-78e6-44e4-842b-138b573a0955
release 5.1.1-homebrew

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
ERROR: /Users/shaoxixu/Repos/big-gov-mono/cover/BUILD.bazel:91:11: While resolving toolchains for target //cover:cover_app_image.binary: No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type. Maybe --incompatible_use_cc_configure_from_rules_cc has been flipped and there is no default C++ toolchain added in the WORKSPACE file? See https://github.com/bazelbuild/bazel/issues/10134 for details and migration instructions.
ERROR: Analysis of target '//cover:cover_app_image' failed; build aborted: 
INFO: Elapsed time: 3.252s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 859 targets configured)
    Fetching @local_config_xcode; Building xcode-locator
    Fetching @com_github_google_go_containerregistry; fetching
    Fetching @com_github_pkg_errors; fetching
```

**Comment by sgowroji** [comment]
Hello @xushaoxiao, Did you try the workarounds mentioned in added [issue](https://github.com/bazelbuild/bazel/issues/10134#issuecomment-1079880746). If still you are not resolved can you provide more details.

**Comment by tuananh** [comment]
> Hello @xushaoxiao, Did you try the workarounds mentioned in added [issue](https://github.com/bazelbuild/bazel/issues/10134#issuecomment-1079880746). If still you are not resolved can you provide more details.

that one works for go_image, what about `java_image`?

**Comment by comius** [comment]
cc @gravypod have there been changes in rules_docker? Could you investigate?

I'm not aware of any changes in Bazel that would have caused this.

**Comment by xushaoxiao** [comment]
resolved, thanks.
