### ISSUE TITLE
How to I build my project like using CPLUS_INCLUDE_PATH and LD_LIBRARY_PATH env in bazel tool?

### ISSUE THREAD

**Issue by wangzy0327** [bazelbuild/bazel#15628]
### Description of the bug:

I have a local library project, I want to depends it in my another project.
how to use it in bazel to build?

I only just build it in cmake.But I am new for bazel.Can you help me ?

this is CMakeLists.txt

`project(oneDNN-example)

set(DPCPP_HOME "/home/wzy/sycl_workspace")
set(LLVM_HOME "${DPCPP_HOME}/build-cuda-debug")
set(DNN_HOME "${DPCPP_HOME}/oneDNN-cuda-debug")

message(STATUS "dpcpp_home : "${DPCPP_HOME})
message(STATUS "llvm_home : "${LLVM_HOME})
message(STATUS "dnn_home : "${DNN_HOME})

include_directories("${LLVM_HOME}/include/sycl")
include_directories("${LLVM_HOME}/build-cuda-debug/include")
include_directories("${DNN_HOME}/include")

link_directories("${LLVM_HOME}/lib")
link_directories("${DNN_HOME}/lib64")

#set(CMAKE_INSTALL_RPATH "${DPCPP_HOME}/llvm/build-cuda-debug/lib" "${DNN_HOME}/lib")

set(CMAKE_BUILD_TYPE "Debug")
set(CMAKE_CXX_FLAGS_DEBUG "$ENV{CXXFLAGS} -O0 -Wall -g -ggdb -std=c++17")
set(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O3 -Wall -std=c++17")

aux_source_directory(. DIR_SRCS)
add_executable(t3s ${DIR_SRCS})
target_link_libraries(t3s -lsycl -ldnnl )`

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`project(oneDNN-example)

set(DPCPP_HOME "/home/wzy/sycl_workspace")
set(LLVM_HOME "${DPCPP_HOME}/build-cuda-debug")
set(DNN_HOME "${DPCPP_HOME}/oneDNN-cuda-debug")

message(STATUS "dpcpp_home : "${DPCPP_HOME})
message(STATUS "llvm_home : "${LLVM_HOME})
message(STATUS "dnn_home : "${DNN_HOME})

include_directories("${LLVM_HOME}/include/sycl")
include_directories("${LLVM_HOME}/build-cuda-debug/include")
include_directories("${DNN_HOME}/include")

link_directories("${LLVM_HOME}/lib")
link_directories("${DNN_HOME}/lib64")

#set(CMAKE_INSTALL_RPATH "${DPCPP_HOME}/llvm/build-cuda-debug/lib" "${DNN_HOME}/lib")

set(CMAKE_BUILD_TYPE "Debug")
set(CMAKE_CXX_FLAGS_DEBUG "$ENV{CXXFLAGS} -O0 -Wall -g -ggdb -std=c++17")
set(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O3 -Wall -std=c++17")

aux_source_directory(. DIR_SRCS)
add_executable(t3s ${DIR_SRCS})
target_link_libraries(t3s -lsycl -ldnnl )`

### Which operating system are you running Bazel on?

Centos 7.9 Core

### What is the output of `bazel info release`?

bazel 3.7.2

**Comment by meteorcloudy** [comment]
This is not a Bazel bug, it's better to ask on StackOverflow or send an email to bazel-discuss@googlegroup.com
