### ISSUE TITLE
> I tried native_test --test_arg=--gtest_output=xml with bazel test, but no luck:

### ISSUE THREAD

**Issue by wondfor** [bazelbuild/bazel#15621]
> I tried --test_arg=--gtest_output=xml with bazel test, but no luck:
> 
> This command:
> *** bazel test --test_arg="--gtest_output=xml:a.xml" my_test
> Produces a.xml somewhere deep in bazel-out/... (actually where the default test_detail.xml is).
> 
> This command:
> *** bazel-bin/my_test --gtest_output=xml:a.xml
> Produces a.xml in the current working directory (or whatever dir I specify).

it doesn't work in general this way, no output seems to be there....

_Originally posted by @Huzuri in https://github.com/bazelbuild/bazel/issues/158#issuecomment-801031619_

**Comment by sgowroji** [comment]
Hello @wondfor, Could you please provide your complete use case with respect to the above query. Thanks!

**Comment by wondfor** [comment]
> Hello @wondfor, Could you please provide your complete use case with respect to the above query. Thanks!
Description of the bug:
when I used the command: bazel test //test/protocols/nfs/common:llt_test_nfsCommon_bzl -s --test_arg="--gtest_output=xml:./DTCenter.xml"
I can not get the file "DTCenter.xml" .
What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
my BUILD.bazel
load("@bazel_skylib//rules:native_binary.bzl", "native_test")

native_test(
    name = "llt_test_nfsCommon_bzl",
    src = "llt_test_nfsCommon",
    out = "llt_test_nfsCommon_out",
    data = ["//:test_lib"]
        + [
            "@usr_lib//:usr_lib",
            "@usr_local//:usr_local"
        ],
    #shard_count = 1,
    #args = ["--gtest_output=xml:bazel-out/k8-fastbuild/testlogs/test/protocols/nfs/common/llt_test_nfsCommon_bzl/DTcenter.xml"],
)

but when I only run bazel-bin/test/protocols/nfs/common/llt_test_nfsCommon_out --gtest_output=xml:./DTCenter.xml, I can get that output file.
Which operating system are you running Bazel on?
NAME="EulerOS"
VERSION="2.0 (SP3)"
bazel release: release 4.0.0
Have you found anything relevant by searching the web?

**Comment by Wyverald** [comment]
I think this is WAI. The working directory of the test binary when you use `bazel run` is that deep directory in bazel-out, not your CWD.
