### ISSUE TITLE
Support link deps in different ways

### ISSUE THREAD

**Issue by xcxclin** [bazelbuild/bazel#15624]
### Description of the feature request:

when I define deps in my BUILD file, the dependencies are linked either static or dynamic way, is it possible to link some of them in static and others in shared way?

### What underlying problem are you trying to solve with this feature?

my code structure is somehow like

-src
  - a
    -BUILD
    -a.cc 
  - b
    -BUILD
    -b.cc 
  - c
    -BUILD
    -c.cc 
-external
  - glog
  - gflags
  - ...

a/b/c are all librarys, b and c is in a's deps, and i what to build a into a single .so file.
If I use cc_library, b and c are not linked into the target .so file, so I declare a like the following:
```
cc_binary(
    name = "a.so",
    srcs = glob([
        "a.h",
        "a.cc",
    ]),
    deps = [
        "//external:glog",
        "//external:gflags",
        "//src/b:libb",
        "//src/c:libc",
    ],
    visibility = ["//visibility:public"],
    linkshared = True,
    linkstatic = 1,
)
```

But it seems that glog and gflags are static linked into a.so, when I use a.so and also use gflags in dynamic linking, it will cause problems.

### Which operating system are you running Bazel on?

centos7

### What is the output of `bazel info release`?

release 3.7.2

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/1920

**Comment by oquenchil** [comment]
You can use: https://cs.opensource.google/bazel/bazel/+/master:src/main/starlark/builtins_bzl/common/cc/experimental_cc_shared_library.bzl
