### ISSUE TITLE
Conflict documents about --strategy_regexp

### ISSUE THREAD

**Issue by 0xtyls** [bazelbuild/bazel#15636]
### Description of the bug:

In user manual (https://docs.bazel.build/versions/main/user-manual.html#flag--strategy_regexp), it says "The last regex_filter that matches the description is used". In command line reference(https://docs.bazel.build/versions/main/command-line-reference.html#flag--strategy_regexp), it says "The first regex_filter that matches the description is used."  Which one is right?

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

documents conflicts at

https://docs.bazel.build/versions/main/user-manual.html#flag--strategy_regexp
https://docs.bazel.build/versions/main/command-line-reference.html#flag--strategy_regexp

### Which operating system are you running Bazel on?

Any

### What is the output of `bazel info release`?

None

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

None

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
None
```

**Comment by haxorz** [comment]
Thanks for filing this issue!

Looks like commit e194c827f363f1a0de42e757759daa0fc9052db9 changed the behavior from "first" to "last" and aptly updated the user manual but didn't update the help string for the flag (which is used to populate the command line reference).

@jylinv0 , the author of that commit, is OOO until Apr 2023. @susinmotion and @katre were the reviewers. Can one of you please fix?

**Comment by katre** [comment]
I'll take a look.
