### ISSUE TITLE
"strict transitive dependency mode" not work ?

### ISSUE THREAD

**Issue by daohu527** [bazelbuild/bazel#15632]
### Description of the bug:

Suppose there is the following dependency a->b->c, **a contains the header file of c, but does not use anything**, then a's build file depends on b, but not on c. Then this forms an **implicit dependency,** and bazel will not report a error!

### Which operating system are you running Bazel on?

ubuntu 18.04

### What is the output of `bazel info release`?

(11:37:20) INFO: Invocation ID: b93b0d49-edac-4215-9d9a-366bf997e477 release 3.7.1

**Comment by sgowroji** [comment]
Hello @daohu527, Can you provide more details to reproduce the above problem. Thanks!

**Comment by daohu527** [comment]
I modified https://github.com/bazelbuild/examples/tree/main/cpp-tutorial/stage3 as an example.

as you see `hello-world.cc` contain `lib/hello-time.h` but no use it. and then `hello-world` deps on `hello-greet`, which deps on `//lib:hello-time`. **In other words `hello-world` implicit deps on `//lib:hello-time`**, but bazel will success, which violates the strict transitive dependency mode.  

## cpp-tutorial/stage3/main/BUILD
```c++
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "hello-greet",
    srcs = ["hello-greet.cc"],
    hdrs = ["hello-greet.h"],
    deps = [
        "//lib:hello-time",
    ],
)

cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
    deps = [
        ":hello-greet",
    ],
)
```

## cpp-tutorial/stage3/main/hello-world.cc
```c++
#include "lib/hello-time.h"
#include "main/hello-greet.h"
#include <iostream>
#include <string>

int main(int argc, char** argv) {
  std::string who = "world";
  if (argc > 1) {
    who = argv[1];
  }
  std::cout << get_greet(who) << std::endl;
  // print_localtime();
  return 0;
}
```

**Comment by fmeum** [comment]
Strict deps checking for C++ on that level of granularity requires passing the flag `--features=layering_check` as it may not work with all compilers. Does that give you the expected failure?

**Comment by daohu527** [comment]
yes, it thrown out an error like below. 
```
main/hello-world.cc:1:10: error: module //main:hello-world does not depend on a module exporting 'lib/hello-time.h'
#include "lib/hello-time.h"
```

Then my question is, since bazel lets users use `strict transitive dependency` in best practice, why doesn't it check by default?

**Comment by martis42** [comment]
@daohu527 This project of mine might be interesting for you: https://github.com/martis42/depend_on_what_you_use

It aims at linting the usage of headers in Bazel C++ targets compared to the targets dependency list.

It is still in an early phase, but maybe it can help you.

**Comment by daohu527** [comment]
@martis42 Thanks for your work, I will check out this project in detail !
