### ISSUE TITLE
Maven Install Rule Dependency Resolution Of Many Defined Artifacts Leads To CLI Overload On Windows

### ISSUE THREAD

**Issue by cjohnstoniv** [bazelbuild/bazel#15641]
### Description of the bug:

We have a WORKSPACE file that defines the maven_install rule and has upwards of 400+ dependencies listed in the rule directly. This works just fine on Mac/Linux machines however on Windows we are hit with a too big of a CLI error.

The error seems to point at Coursier and the execution of it passing each and every artifact that is in Maven install definition into Coursier via the CLI.

Is there anyway to have it call Couriser but instead of passing all the artifacts via the CLI instead pass it a file and Coursier reads from the file instead? This would prevent the explosion of the CLI at a slight overhead cost of writing to and reading from a file.

Log output (slightly adjusted to remove proxy info):

```
Error while fetching artifact with coursier: java.io.IOException: ERROR: src/main/native/windows/process.cc(165): CreateProcessWithExplicitHandles("C:\apps\java\jdks\8\8.302.08\bin\java.exe" -noverify -jar C:/users/chjohnst/_bazel_chjohnst/esihirt4/external/java-third-party-maven/coursier fetch antlr:antlr:2.7.7(...)): command is longer than CreateProcessW's limit (32767 characters)
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a workspace file with Maven install as a rule, put 400+ artifacts in it, and run this on Windows.

### Which operating system are you running Bazel on?

Windows

### What is the output of `bazel info release`?

release 5.1.1

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
N/A
```

### Have you found anything relevant by searching the web?

I have found other Bazel issues with Windows and too large of CLI's however none of them seem related to Coursier and it being driven by the number of Maven Install artifacts defined.

**Comment by sgowroji** [comment]
Hello @cjohnstoniv, Could you please follow up duplicate issue https://github.com/bazelbuild/bazel/issues/14256 for further updates.
