### ISSUE TITLE
Java header compilation fails to resolve generated class

### ISSUE THREAD

**Issue by ashyralyyev** [bazelbuild/bazel#15650]
### Description of the bug:

Header compilation fails when a generated source file uses another generated class from within the same `java_library` but a different package.

Example:
`Foo` has `@Value.Immutable` annotation. It generates `ImmutableFoo`. Similarly, `Bar` has `@Value.Immutable` annotation. It generates `ImmutableBar`. `ImmutableFoo` uses `ImmutableBar`.

When `Foo.java` and `Bar.java` are in the same package, header compilation works.

When `Foo.java` and `Bar.java` are in different packages within the same `java_library` target, turbine fails:
```bash
com/example/myproject/foo/ImmutableFoo.java:145: error: could not resolve ImmutableBar
    public final Builder bar(ImmutableBar bar) {
                             ^
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/ashyralyyev/header-compilation-repro contains a minimal example with instructions to reproduce. It contains both working and failing examples.

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 5.1.1

**Comment by comius** [comment]
cc @chushon

**Comment by hisener** [comment]
cc @cushon (There is a typo above 🙂)

**Comment by comius** [comment]
ups, thanks!

**Comment by cushon** [comment]
This is an issue with the immutables annotation processor, which special-cases javac and ecj and relies on internal APIs: https://cs.github.com/immutables/immutables/blob/888232ddc7d2ab7c76d289be2da02cc551fdded5/generator/src/org/immutables/generator/SourceExtraction.java#L382

**Comment by hisener** [comment]
As @cushon mentioned, indeed `org.immutables.generator.SourceExtraction.JavacSourceExtractor` only works when the type element is `com.sun.tools.javac.code.Symbol.ClassSymbol`.

![image](https://user-images.githubusercontent.com/7688949/193810419-9871f8ee-0b78-4319-91e4-813774710b31.png)

I think we can introduce a new `SourceExtractor` to handle `TurbineTypeElement`s.

```java
private static final class TurbineSourceExtractor implements SourceExtractor {
  @Override
  public boolean claim(Element element) {
    return element instanceof TurbineTypeElement;
  }

  @Override
  public CharSequence extract(ProcessingEnvironment environment, TypeElement typeElement) {
    if (typeElement instanceof TurbineTypeElement) {
      TurbineTypeElement turbineTypeElement = (TurbineTypeElement) typeElement;
      if (turbineTypeElement.info() instanceof SourceTypeBoundClass) {
        return ((SourceTypeBoundClass) turbineTypeElement.info()).source().source();
      }
    }

    return UNABLE_TO_EXTRACT;
  }

  @Override
  public CharSequence extractReturnType(ExecutableElement executableElement) {
    return UNABLE_TO_EXTRACT;
  }
}
```

However, there are two problems:
1. `com.google.turbine:turbine` is not available on Maven Central.
2. I had to make `TurbineElement.TurbineTypeElement` and `TurbineElement.TurbineTypeElement#info` public to avoid reflection in Immutables code.

Do you think we can address these before asking [Immutables](https://github.com/immutables/immutables) maintainers what they think of adding a `TurbineSourceExtractor`?

**Comment by cushon** [comment]
> I had to make `TurbineElement.TurbineTypeElement` and `TurbineElement.TurbineTypeElement#info` public to avoid reflection in Immutables code

Those classes are deliberately non-public, the expectation is that processors should go through the supported JSR-269 APIs, instead of relying on processor-specific internal data structures.

**Comment by hisener** [comment]
That's fair, but I am not sure how much work that would require on the Immutables side. :man_shrugging:  Do you have any recommendations?
