### ISSUE TITLE
`rlocation` returns different results for a target and an alias of that target.

### ISSUE THREAD

**Issue by psigen** [bazelbuild/bazel#15662]
### Description of the bug:

Define a simple `sh_binary` called `\\:foo1`, and create
an alias target `\\:foo2` that refers to `\\:foo1`. 

Then create another `sh_binary` called `\\:bar` that depends on
the foo1 and foo2 target and resolves them using `$(rlocation ...)`.

The desired behavior would be for `rlocation` calls on both targets
to resolve to the same path, since they represent the same resource.
However, the actual behavior is that true target returns a result,
while the alias is not found.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See the following repository:
https://github.com/psigen/bazel-issue-15662

### Which operating system are you running Bazel on?

Ubuntu 18.04.6 LTS

### What is the output of `bazel info release`?

release 5.2.0

### Have you found anything relevant by searching the web?

Related discussion and workaround in Bazel Slack:
https://bazelbuild.slack.com/archives/CA31HN1T3/p1654808996442259

### Any other information, logs, or outputs that you want to share?

**Workaround 1:** use `sh_binary` to wrap the target instead of an `alias`:
```starlark
sh_binary(
    name = "foo2",
    srcs = ":foo1",
)
```

**Workaround 2:** use skylib's `native_binary` to wrap the target instead of an `alias`:
```starlark
native_binary(
    name = "foo2",
    src = ":foo1",
    out = "foo",
)
```

**Comment by psigen** [comment]
I realize now that this is even more tricky -- at the root of the issue is that `rlocation` does not actually know what to point to.

So the solution here might involve having a way for the bash runfiles to resolve the default execution target of `bazel run` for an alias.  I am not sure if this would require a new macro like `elocation`

**Comment by comius** [comment]
The solution is to use a path returned by `$(rlocationpath //alias_label)` used in the rule attribute (passing it to sh script). The function knows how to resolve aliases. On older Bazel versions <6, `rootpath` can be used.

cc @fmeum

**Comment by fmeum** [comment]
What @comius said, just want to add that `rlocationpath` is already in Bazel 5.4.0.

**Comment by psigen** [comment]
Thanks guys.  It was pretty hard to find examples of this usage anywhere.  For other folks looking for it, [see the documentation here](https://bazel.build/reference/be/make-variables#:~:text=rlocationpath%3A%20The%20path%20a%20built%20binary%20can%20pass%20to%20the%20Rlocation%20function%20of%20a%20runfiles%20library%20to%20find%20a%20dependency%20at%20runtime%2C%20either%20in%20the%20runfiles%20directory%20(if%20available)%20or%20using%20the%20runfiles%20manifest.)

I am not sure where the best documentation outside of this is.
