### ISSUE TITLE
fishy strategy for order-independent hashing

### ISSUE THREAD

**Issue by oconnor663** [bazelbuild/bazel#15660]
### Description of the bug:

With apologies, this isn't a bug that I can reproduce in practice. It's just a concern I have reading the code. The code in question is [MetadataDigestUtils.java](https://github.com/bazelbuild/bazel/blob/f0e63c4c934dfd9e85d2e55ede7c5bc0409946c7/src/main/java/com/google/devtools/build/lib/actions/cache/MetadataDigestUtils.java#L49-L60):

```java
/**
 * @param env A collection of (String, String) pairs.
 * @return an order-independent digest of the given set of pairs.
 */
public static byte[] fromEnv(Map<String, String> env) {
  byte[] result = new byte[0];
  Fingerprint fp = new Fingerprint();
  for (Map.Entry<String, String> entry : env.entrySet()) {
    fp.addString(entry.getKey());
    fp.addString(entry.getValue());
    result = DigestUtils.xor(result, fp.digestAndReset());
  }
  return result;
}
```

(Similarly, the `fromMetadata` method immediately above that one.)

In short, this code XOR's a bunch of different hashes together, with the goal of getting a final result that's independent of the order of the inputs. My concern is that XOR'ing hashes is a fishy thing to do in general, because if two inputs are ever identical to each other, their hashes will also be identical, and XOR'ing them will cancel them both out. This makes it possible to change both inputs at the same time, as long as they remain the same as each other. Their hashes will always cancel out, and the final answer will be totally independent of the values of those inputs.

Now in this case, it looks like part of the input is a key from a hash map, so we might hope that those keys are guaranteed to be unique. If that was the whole story, I think it would still be worth a comment in the code. ("NB: The following is only valid because we're hashing the keys of a map. Do not copy this approach if you can't guarantee the inputs are all distinct.") But I'm not so sure it's the whole story. One detail that jumps out to me is that hashing appears to be done by encoding each string into Protobuf bytes. That entails a conversion from Java's UTF-16 strings to Protobuf's UTF-8 strings. Can two different Java strings ever wind up getting converted to the same Protobuf bytes? I don't know the answer to that, but the first thing I'd want to look at is invalid UTF-16 strings with "isolated surrogates". It's common for UTF-8 conversions of invalid UTF-16 strings to be lossy, which could trigger this bug. Even if this particular issue doesn't pan out, I think it's a good example of how this XOR strategy entails some pretty beefy assumptions about what a lot of underlying libraries are doing, which could change over time in unexpected ways.

For a more robust approach to order-independent hashing, I'd recommend taking all the hashes-of-inputs, sorting them, and then hashing the concatenation of all those sorted hashes. That requires a bit more work and linear memory, but it's simple to implement and robust to identical inputs. If constant memory was a hard requirement, you could think about getting fancy with e.g. scalar multiplication of elliptic curve points, but that's way more complicated and also much more expensive.

Anyway, fingers crossed that I haven't wasted your time by misreading the code :)

**Comment by justinhorvitz** [comment]
`fromEnv` is only used to compute a digest of the client environment for purposes of the action cache. We could easily change that to use a sorted map, but changing the digest function would result in the action cache having mismatches across bazel versions. It would be easy to keep the same digest for the common case of an empty map, but if the map is non-empty the user could see confusing messages that the client env has changed when in fact it hasn't: http://google3/third_party/bazel/src/main/java/com/google/devtools/build/lib/actions/ActionCacheChecker.java;l=238;rcl=461281665.

A compromise could be to move `fromEnv` out of a common place to discourage any new uses.

**Comment by fmeum** [comment]
I recently learned of another reason that makes `xor` fishy for this purpose and that applies even if keys in a map are unique: If hashes have N bits, then the security properties of hash functions make it likely that N random inputs hash to N N-bit strings that are linearly independent over `F_2` (field with two elements) when viewed as elements in `F_2^N`. As a result, Gaussian elimination provides an efficient algorithm to compute, for every desired target hash, a subset of these inputs such that their xored hashes result in that crafted hash value. 

Under adversarial conditions, this makes it very easy to generate collisions assuming sufficiently large inputs to the hash combiner function. Collisions by chance are still pretty unlikely, but since Bazel generally uses cryptographic hash functions rather than just "good" hash functions, this still feels like something we should fix. Discarding local action caches doesn't sound that bad when we do it in a major release, which likely discards them anyway (e.g. due to Bzlmod repo name changes).

@haxorz @justinhorvitz What do you think?

**Comment by justinhorvitz** [comment]
I'm happy to approve a fix. The easiest thing to do seems like sorting, so long as there is no performance concern. Did you have anything else in mind?

**Comment by fmeum** [comment]
I went with `+` instead of `^`, which is used by both Guava and the JDK's `Set` `hashCode`. It avoids the pressing problems while being as fast as `^`.
