### ISSUE TITLE
Bazel does not create top level __init__.py in runfiles

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#1567]
This is related to the runfiles changes in Bazel 0.2.3.  

Given a workspace named "workspace", with a package "foo" containing a BUILD file like so:

== foo/BUILD ==
```
# py_binary(name="bar", srcs=["bar.py"])

Bazel will create this structure:
    bazel-bin/
      foo/
        bar.runfiles/
          workspace/
            # __init__.py <---- Missing
            foo/
              __init__.py
              bar.py
```

The file `bazel-bin/foo/bar.runfiles/workspace/__init__.py` should be created in order for python imports like
```python
from workspace.foo import bar
```
to work.

The workaround is to add something like this to every python target:
```python
    deps = ["//:__init__.py"],
```

**Comment by brandjon** [comment]
The overall pattern of automatically inserting `__init__.py` files is something we [want to get rid of](https://docs.bazel.build/versions/master/be/python.html#py_binary.legacy_create_init). The current behavior should be documented, but there's probably no need to change it prior to deprecation.
