### ISSUE TITLE
Starlark flags in a activated by `--config` cannot be overridden on the command line

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#15679]
### Description of the bug:

When I put a Starlark flag in a `--config` stanza in a .bazelrc file and activate that stanza using `--config`,  Starlark flags in it cannot be overridden from the command line. This works with hard-coded command line options.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

bazelrc:
```
build:red --//f:color=red
build:red --color=no
```

f/BUILD:
```
load(":f.bzl", "color", "r")

color(
    name = "color",
    build_setting_default = "white",
)

r(name = "r")
```

f/f.bzl:
```
ColorValue = provider("color")

def _color_impl(ctx):
    return [ColorValue(color = ctx.build_setting_value)]

color = rule(
    implementation = _color_impl,
    build_setting = config.string(flag = True),
)

def _r_impl(ctx):
    print(ctx.attr._color[ColorValue].color)
    return [DefaultInfo()]

r = rule(
    implementation = _r_impl,
    attrs = {"_color": attr.label(default = "//f:color")},
)
```

After this, `bazel --bazelrc=bazelrc build --nobuild //f:r --config=red  --//f:color=green --color=yes`  prints `red` in the message but the console output will be colorized.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

bazel 5.2.0

**Comment by wudisheng** [comment]
This seems a long-lived bug in Bazel, I personally suffer from it too.

See https://github.com/bazelbuild/bazel/issues/13231.
