### ISSUE TITLE
Release 5.3 - August 2022

### ISSUE THREAD

**Issue by ckolli5** [bazelbuild/bazel#15685]
# Status of Bazel 5.3

-   Expected release date: 08/22/2022
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/39)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 5.3, simply send a PR against the `release-5.3.0` branch.

Task list:
-   [ ] [Create draft release announcement](https://docs.google.com/document/d/1wDvulLlj4NAlPZamdlEVFORks3YXJonCjyuQMUQEmB0/edit)
-   [ ] Send for review the release announcement PR:
-   [ ] Push the release, notify package maintainers:
-   [ ] Update the documentation
-   [ ] Push the blog post
-   [ ] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by wisechengyi** [comment]
Hello :wave: general question on release cadence - https://github.com/bazelbuild/bazel/issues/15682 is a bug in 5.2.0. Should it be picked into a 5.2.x patch release, or is 5.3.0 is the patch release? Just wanted to make sure whichever release it lands only contains the bug fixes, and no new development.

**Comment by ananta-code** [comment]
Hello - there is a ticket https://github.com/bazelbuild/bazel/issues/15762 .Are you also planning to pick it for the next patch release

**Comment by ckolli5** [comment]
> Hello 👋 general question on release cadence - #15682 is a bug in 5.2.0. Should it be picked into a 5.2.x patch release, or is 5.3.0 is the patch release? Just wanted to make sure whichever release it lands only contains the bug fixes, and no new development.

@wisechengyi We have already cherry picked the fix that is addressing this issue to release-5.3.0. At this point we are not planing to perform any patch release.

**Comment by ckolli5** [comment]
> Hello - there is a ticket #15762 .Are you also planning to pick it for the next patch release

@ananta-code Since we are not planing for any patch release at this point, this will be cherry picked to release-5.3.0.

**Comment by sluongng** [comment]
I was wondering if a change like https://github.com/bazelbuild/bazel/commit/d7f0724b6b91b6c57039a1634ff00ccebd872714 would be considered too disruptive have left for Bazel 6.x or if it's ok to be considered for 5.3?

cc: @wilwell

**Comment by kshyanashree** [comment]
Hello all, we have decided to push the release date to 08/15/2022. Just wanted to keep you all updated. Thanks!

**Comment by AustinSchuh** [comment]
Ran 5.3 RC1 on our build against our remote execution cluster and it fails to run tests.  https://github.com/bazelbuild/bazel/issues/16003 is the bug I filed. This is a regression from 5.0, which worked with the exact same version of the code being built and the exact same command.

**Comment by UebelAndre** [comment]
Hello, would it be possible to cherry-pick https://github.com/bazelbuild/bazel/commit/9c98120f33579b72561e02826d9fccf222eccb3c (https://github.com/bazelbuild/bazel/issues/15130) for `5.3`?

**Comment by kshyanashree** [comment]
> Ran 5.3 RC1 on our build against our remote execution cluster and it fails to run tests. #16003 is the bug I filed. This is a regression from 5.0, which worked with the exact same version of the code being built and the exact same command.

Hi @AustinSchuh, we are awaiting review on 16008 which fixes the issue.

**Comment by kshyanashree** [comment]
> Ran 5.3 RC1 on our build against our remote execution cluster and it fails to run tests. #16003 is the bug I filed. This is a regression from 5.0, which worked with the exact same version of the code being built and the exact same command.



> > Ran 5.3 RC1 on our build against our remote execution cluster and it fails to run tests. #16003 is the bug I filed. This is a regression from 5.0, which worked with the exact same version of the code being built and the exact same command.
> 
> Hi @AustinSchuh, we are awaiting review on 16008 which fixes the issue.



> > Ran 5.3 RC1 on our build against our remote execution cluster and it fails to run tests. #16003 is the bug I filed. This is a regression from 5.0, which worked with the exact same version of the code being built and the exact same command.
> 
> Hi @AustinSchuh, we are awaiting review on 16008 which fixes the issue.

Hello @AustinSchuh! Just an update, as 16008 fixes the issue, it has been reviewed and merged to release 5.3.0. Thanks!

**Comment by nresare** [comment]
I would like to put forward https://github.com/bazelbuild/bazel/pull/16095 a trivial change to add support for java language level 17 to the linux-aarch64 platform

**Comment by kshyanashree** [comment]
Hello @nresare , Just to let you know it is not possible for this release-5.3.0. We can pick it in next release. Thanks!

**Comment by kshyanashree** [comment]
> I would like to put forward #16095 a trivial change to add support for java language level 17 to the linux-aarch64 platform

Hello @nresare, Just to let you know it is not possible for this release-5.3.0. We can pick it in next release. Thanks!

**Comment by dws** [comment]
Will there be a 5.3.0rc2 before the final release?

**Comment by kshyanashree** [comment]
> Will there be a 5.3.0rc2 before the final release?

Hi @dws! yes, we are going to announce 5.3.0rc2 before the final release. Thanks!

**Comment by nresare** [comment]
> > I would like to put forward #16095 a trivial change to add support for java language level 17 to the linux-aarch64 platform
> 
> Hello @nresare, Just to let you know it is not possible for this release-5.3.0. We can pick it in next release. Thanks!

I see. Is there a branch cut for this release next release, to open PRs against?

**Comment by kshyanashree** [comment]
> > > I would like to put forward #16095 a trivial change to add support for java language level 17 to the linux-aarch64 platform
> > 
> > 
> > Hello @nresare, Just to let you know it is not possible for this release-5.3.0. We can pick it in next release. Thanks!
> 
> I see. Is there a branch cut for this next release, to open PRs against?

Hi @nresare! Not as of yet, we will be cutting the branch for next release after this release. Thanks!

**Comment by dws** [comment]
I see that https://releases.bazel.build/5.3.0/rc2/index.html exists and is dated yesterday (2022-08-17) but I have not seen an announcement email.
Are these the official rc2 bits?

**Comment by kshyanashree** [comment]
5.3 is now out!

@petemounce @excitoon [@vbatts](https://github.com/vbatts) Could you please update relevant package managers? Thanks!

**Comment by dan-cohn-sabre** [comment]
> > Hello - there is a ticket #15762 .Are you also planning to pick it for the next patch release
> 
> @ananta-code Since we are not planing for any patch release at this point, this will be cherry picked to release-5.3.0.

@ckolli5 I don't see this listed in the 5.3 [release notes](https://blog.bazel.build/2022/08/23/bazel-5.3.html). Can you confirm the fix has been included? Both #15762 and #15865 are still open.

**Comment by fmeum** [comment]
https://github.com/bazelbuild/bazel/pull/16008#issuecomment-1224267553 is a first report of a 5.3.0 regression my fix for #16003 introduced - the existing tests didn't cover local execution.

**Comment by kshyanashree** [comment]
> > > Hello - there is a ticket #15762 .Are you also planning to pick it for the next patch release
> > 
> > 
> > @ananta-code Since we are not planing for any patch release at this point, this will be cherry picked to release-5.3.0.
> 
> @ckolli5 I don't see this listed in the 5.3 [release notes](https://blog.bazel.build/2022/08/23/bazel-5.3.html). Can you confirm the fix has been included? Both #15762 and #15865 are still open.

Hi @dan-cohn-sabre! As we are working on it, we will keep you updated of any progress. Thanks!

**Comment by kshyanashree** [comment]
> Hello - there is a ticket #15762 .Are you also planning to pick it for the next patch release

Hi @ananta-code ! As this issue is marked as P3, we don't have any resource to work on this. But please feel free to send PR. Thanks!

**Comment by kshyanashree** [comment]
5.3.1 is now out!

[@vbatts](https://github.com/vbatts) [@petemounce](https://github.com/petemounce) [@excitoon](https://github.com/excitoon) Could you please update relevant package managers? Thanks!

**Comment by Wyverald** [comment]
@meteorcloudy FYI, we could maybe look into this

**Comment by meteorcloudy** [comment]
@petemounce Thanks! I filed an issue to track this: https://github.com/bazelbuild/continuous-integration/issues/1456

**Comment by kshyanashree** [comment]
5.3.2 is now out!

@petemounce @excitoon [@vbatts](https://github.com/vbatts) Could you please update relevant package managers? Thanks!

**Comment by petemounce** [comment]
Done. Ping on https://github.com/bazelbuild/continuous-integration/issues/1456

**Comment by ananta-code** [comment]
> #15762

Hi ,
I can see https://github.com/bazelbuild/bazel/issues/15762 is showing as closed but https://github.com/bazelbuild/bazel/issues/15865 is still open .
Could you please check?
