### ISSUE TITLE
Remote-cache not work in 5.2.0

### ISSUE THREAD

**Issue by Smile-Autra** [bazelbuild/bazel#15682]
### Description of the bug:

When upgrade to the latest version of bazel. Bazel remote seems not to work. Bazel can only put but can not get. When use bazel 5.1.1 bazel remote works again. More strange, bazel 5.2.0 can use the cache of 5.1.1. It seems that the artifact put by bazel 5.2 has problem.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Use bazel 5.2.0 and use `https://github.com/buchgr/bazel-remote` as remote cache like `bazel build --remote_cache=http://localhost:9090`

### Which operating system are you running Bazel on?

Ubuntu 20.04

### What is the output of `bazel info release`?

release 5.2.0

**Comment by chancila** [comment]
people are reporting this is causing the issue

https://bazelbuild.slack.com/archives/CA31HN1T3/p1655638147979559?thread_ts=1655544708.176529&cid=CA31HN1T3

https://github.com/bazelbuild/bazel/commit/4d900ceea12919ad62012830a95e51f9ec1a48bb

**Comment by brentleyjones** [comment]
@coeuvre

**Comment by coeuvre** [comment]
What's error message looks like? Does it also the case for HEAD?

**Comment by mistic** [comment]
I also confirm this is a problem. We didn't notice at the beginning of the upgrade as we were using the previously populated remote cache but after a couple of days we were having mostly cache misses and less and less cache hits. The problem happens both when using the buildbuddy grpc cache or a simple GCS Bucket. Reverting to 5.1.1 makes everything working again.

**Comment by coeuvre** [comment]
I am not able to reproduce this locally. Do you know which actions are not uploading artifacts?

**Comment by mistic** [comment]
@coeuvre it actually happens in rules from `rules_nodejs` we are using like `TsProject` https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/typescript/index.bzl#L109

**Comment by nickbreen** [comment]
We reverted back to 5.1.1 due to this, however we do not use `rules_nodejs` (mainly `java_library` and `genrule`).

We noticed because the bazel-remote logs were **all** GET 404.

**Comment by Smile-Autra** [comment]
> 

Same error.

**Comment by fmeum** [comment]
@nickbreen Are you using directory inputs/outputs? `rules_nodejs` does and 5.2 includes https://github.com/bazelbuild/bazel/commit/26f878325e915e0905626a0e4c8bbacffd72f875, but if you are facing the same issues without relying on TreeArtifacts, then that commit is less likely to be the culprit.

**Comment by nickbreen** [comment]
We have various rules using TreeArtifacts (`ctx.actions.declare_directory`) and rules that produce a directory output using `ctx.outputs` and genrules doing the same.

**Comment by adam-singer** [comment]
We have also noticed this similar bug where caching seems to have broken on 5.2.0. When I was tracing the request logs something seemed odd in terms of the action cache `GET` missing and content addressable `PUT`. I could be missing a detail here, maybe this will help narrow down to what other folks might be seeing.


Before doing a build there is a miss on the action cache `GET 404       127.0.0.1 /ac/877dcafd4dc610e6cc734aa39f91aaf9a8e9a7f730e5bd1021c557c5c74bfda5` 
https://gist.github.com/adam-singer/0c73500e47d1a2410924dc5be4da0a3a#file-gistfile1-txt-L1 

Bazel/rules go along their business and build/calculate results, then I would assume that the next time `877dcafd4dc610e6cc734aa39f91aaf9a8e9a7f730e5bd1021c557c5c74bfda5` is seen in the request logs it would be a `PUT` to `/ac/877dcafd4dc610e6cc734aa39f91aaf9a8e9a7f730e5bd1021c557c5c74bfda5`, but what I've seen in our request logs is the remote uploader is making the request to `PUT 200       127.0.0.1 /cas/877dcafd4dc610e6cc734aa39f91aaf9a8e9a7f730e5bd1021c557c5c74bfda5` https://gist.github.com/adam-singer/0c73500e47d1a2410924dc5be4da0a3a#file-gistfile1-txt-L62 the content addressable cache.

Could someone confirm or verify seeing similar behavior and if that is expected?
