### ISSUE TITLE
Question: Does bazel use gradle?

### ISSUE THREAD

**Issue by WildOrangutan** [bazelbuild/bazel#15689]
I just came across bazel. I'm wondering, does bazel make use of gradle to build the project? I'm thinking about Android projects.

**Comment by keith** [comment]
No, bazel is its own build system that directly calls the underlying tools for the given ecosystem. It supports Android out of the box though, here is a good place to start: https://bazel.build/tutorials/android-app

**Comment by WildOrangutan** [comment]
That's nice to hear. I'm desperately looking for gradle alternatives. Thanks!
