### ISSUE TITLE
Provide "rules_perl" repository with Skylark rules for Perl

### ISSUE THREAD

**Issue by PiotrSikora** [bazelbuild/bazel#1568]
Please add  `rules_perl` Skylark repository, maintained by the Bazel team, that provides `perl_binary`, `perl_library` and `perl_test`.

See [this post](https://groups.google.com/forum/#!msg/bazel-discuss/q4ZQFkPYsPw/9OVzu_UUGAAJ) for previous discussion.

Feel free to reach out internally for existing `perl.bzl`, which could be used for this.

**Comment by damienmg** [comment]
We are not going to maintain a rules_perl. However we can endorse a maintained rule set like we did for scala or groovy. If you wish to maintain such a rule set, just create a repository and point it to us then we can make it a bazelbuild repository.

**Comment by PiotrSikora** [comment]
Done: https://github.com/bazelbuild/rules_perl
