### ISSUE TITLE
`bazel version` launches a server; is slow

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#1569]
When running `bazel version` in a directory with a `WORKSPACE` file, it launches a server before spitting out the version number.

`bazel version` takes 1.2s if the server isn't running yet or if you launch in `--batch` mode; it still takes 100ms if the server is running.

We wanted to query `bazel version` in `tools/bazel`. Adding `bazel version` to `tools/bazel` makes our Bazel startup slower.

<details><summary>

Click here for timings on my machine</summary>

``` bash
dfab: ~ $ cd /tmp
dfab: /tmp $ touch WORKSPACE
dfab: /tmp $ time bazel version
.
Build label: 0.3.1rc2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 22 09:54:53 2016 (1469181293)
Build timestamp: 1469181293
Build timestamp as int: 1469181293

real    0m1.188s
user    0m0.063s
sys 0m0.035s
dfab: /tmp $ time bazel version
Build label: 0.3.1rc2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 22 09:54:53 2016 (1469181293)
Build timestamp: 1469181293
Build timestamp as int: 1469181293

real    0m0.104s
user    0m0.062s
sys 0m0.034s
dfab: /tmp $ bazel shutdown
dfab: /tmp $ time bazel version
.
Build label: 0.3.1rc2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 22 09:54:53 2016 (1469181293)
Build timestamp: 1469181293
Build timestamp as int: 1469181293

real    0m1.200s
user    0m0.064s
sys 0m0.035s
dfab: /tmp $ time bazel --batch version
Build label: 0.3.1rc2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 22 09:54:53 2016 (1469181293)
Build timestamp: 1469181293
Build timestamp as int: 1469181293

real    0m0.771s
user    0m1.272s
sys 0m0.139s
```

</details>

**Comment by damienmg** [comment]
Yes that's really sad but it's due to the java code which actually read the information and return it to the user.

/cc @ulfjack for finer triage, I am unsure we want to change that in the long term.

**Comment by ulfjack** [comment]
I don't have much to add. I'd certainly like to fix it. It's also odd that it's taking 100ms for a running server - it ought to be faster than that.

**Comment by ulfjack** [comment]
It looks like it's due to grpc connection overhead. The Java process isn't doing anything.

**Comment by ulfjack** [comment]
Let me clarify - bazel version takes ~120ms on my machine, and the profiler says it's not spending the time in the Java process. I conclude that it's spending the time in grpc. IIRC, we've had a similar problem in the past and it was grpc at the time. Summoning @lberki, who wrote the grpc code.

**Comment by meisterT** [comment]
I think we close this now, since we have `bazel --version` which doesn't start a server.
