### ISSUE TITLE
Can't disable error-prone in Bazel 0.3.1rc2

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#1570]
Consider the repository here. https://github.com/dfabulich/disable-errorprone

It has a blank `WORKSPACE` and a single `App.java` file, which compiles in `javac` but fails under [Error Prone](https://github.com/google/error-prone).

```java
public class App {
	public static void main(String[] args) {
		System.out.println("" + args);
	}
}
```

```python
java_binary(
	name='x',
	srcs=['App.java'],
	main_class='App',
	javacopts = ['-extra_checks:off'],
)
```

When I `bazel build :x` in Bazel 0.3.0, the build succeeds.

In Bazel 0.3.1rc2, the build fails, `blaze javac: invalid flag: -extra_checks:off`. If I comment out `javacopts`, the build fails with an `ArrayToStringConcatenation` error from Error Prone.

<details><summary>Click here for build logs</summary>
```
dfab: /tp/disable-errorprone $ bazel version
Build label: 0.3.1rc2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 22 09:54:53 2016 (1469181293)
Build timestamp: 1469181293
Build timestamp as int: 1469181293

dfab: /tp/disable-errorprone $ bazel build :x
INFO: Found 1 target...
ERROR: /private/tmp/tp/disable-errorprone/BUILD:1:1: Java compilation in rule '//:x' failed: java failed: error executing command external/local_jdk/bin/java -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac.jar -XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -jar ... (remaining 2 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 2.
blaze javac: invalid flag: -extra_checks:off
Usage: blaze javac <options> <source files>
use -help for a list of possible options
blaze javac: no source files or class names
Usage: blaze javac <options> <source files>
use -help for a list of possible options
Target //:x failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.403s, Critical Path: 0.33s

dfab: /tp/disable-errorprone $ # comment out javacopts

dfab: /tp/disable-errorprone $ bazel build :x
INFO: Found 1 target...
ERROR: /private/tmp/tp/disable-errorprone/BUILD:1:1: Java compilation in rule '//:x' failed: java failed: error executing command external/local_jdk/bin/java -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac.jar -XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -jar ... (remaining 2 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
App.java:3: error: [ArrayToStringConcatenation] Implicit toString used on an array (String + Array)
		System.out.println("" + args);
		                      ^
    (see http://errorprone.info/bugpattern/ArrayToStringConcatenation)
  Did you mean 'System.out.println("" + Arrays.toString(args));'?
1 error
Target //:x failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.895s, Critical Path: 0.80s
```
</details>

**Comment by dfabulich** [comment]
Note also that the URL the build message provides, [http://errorprone.info/bugpattern/ArrayToStringConcatenation](http://errorprone.info/bugpattern/ArrayToStringConcatenation) is 404. (But I get the idea.)

Note that I'm compiling legacy code here that I can't afford to update to fix Error Prone's issues.

**Comment by cushon** [comment]
That happened in d861a005d27d0e95070d0807d8da5f6b6fdb9d2e. The `-extra_checks` flag was put in when Error Prone was first integrated with Bazel, in case we needed a way to turn it off in a hurry. You can still use e.g. `-Xep:ArrayToStringConcatenation:OFF` to suppress errors. It'd be easy enough to add `-extra_checks` back if it's useful, though.

Just curious, were they any particular errors you wanted to disable? The diagnostic in that example looks legitimate.

Also - the diagnostic name will match the docs again after 8f5b5945379c558dfa21195ffd9a1df8ff0eccb4. ArrayToStringConcatenation has been renamed to [ArrayToString](http://errorprone.info/bugpattern/ArrayToString).

**Comment by dfabulich** [comment]
`-extra_checks:off` is critical to me. Error Prone uses dozens of checks by default and disabling them one at a time is not reasonable.

I have no complaints about the diagnostic itself (I agree that it's almost never a good idea to concatenate an array with a string) but I have no idea how long it would take me to fix all the random stuff Error Prone turns up, weeks probably, and I can't justify working on that this quarter (this year, more likely).

**Comment by damienmg** [comment]
I would say we revert that change for the release. @cushon Was the removal of this flag just because it is unused in Google?
