### ISSUE TITLE
Add cquery support for --order_output flag

### ISSUE THREAD

**Issue by brenden** [bazelbuild/bazel#15717]
### Description of the feature request:

Right now the ordering of the results from cquery cannot be controlled by `--order_output` (as they can be for query). It would be nice if this flag were supported on cquery as well.

### What underlying problem are you trying to solve with this feature?

I am using the output of `bazel query` in a CI system to identify which tests need to be run before merging each pull request. The process is:
  1. run `bazel query --order_output full 'deps(//...)'` on the PR branch
  2. run `bazel query --order_output full 'deps(//...)'` on the master branch
  3. using the two dependency graphs, identify all changed targets and find all test targets that are downstream of them

See [bazel-diff](https://github.com/Tinder/bazel-diff.git) for an implementation of similar logic.

I now want to replace `bazel query` with `bazel cquery` so that changes to configured dependencies will trigger tests to run. However `bazel cquery` does not support the `--order_output` flag and its default results are not in topological order.

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

4.2.2

**Comment by brenden** [comment]
Thanks for the fast reply! I'll take a swing at implementing this then.

**Comment by gregestren** [comment]
If the change looks simple feel free to just put up a PR. If more complicated I suggest reviewing what you find here so we can do some design analysis before going too deeply down one route.
