### ISSUE TITLE
[5.3] Cherry pick cc_shared_library commits

### ISSUE THREAD

**Issue by learning-to-play** [bazelbuild/bazel#15713]
### Description of the bug:

Can you cherry pick the commits that fix bugs or add features to cc_shared_library including:
- Adding regular library in interface_library group of cc_shared_library
- Remove unnecessary files from the runfiles of cc_shared_library

### Which operating system are you running Bazel on?

Linux, macOS, Windows

**Comment by oquenchil** [comment]
Yes, I can confirm!

**Comment by learning-to-play** [comment]
It seems cc_shared_library is using the actual library rather than the interface library to link on Windows. Is this something that needs to be fixed on the Bazel size? If so, can you cherry pick that one, too?

**Comment by ckolli5** [comment]
Closed https://github.com/bazelbuild/bazel/pull/15754
