### ISSUE TITLE
//src/test/shell/bazel/android:android_integration_test is time out flaky

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1572]
See http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=latest-jdk7,PLATFORM_NAME=darwin-x86_64/142/console

Assigning to @ahumesky for triage.

**Comment by damienmg** [comment]
@ahumesky ping?

**Comment by ahumesky** [comment]
Sorry, I haven't had time to look at this

**Comment by hermione521** [comment]
It seems not flaky any more?

**Comment by hermione521** [comment]
Closing it. Feel free to reopen if it gets flaky again.
