### ISSUE TITLE
target pattern file with nothing but an EOL cause build failure

### ISSUE THREAD

**Issue by fa93hws** [bazelbuild/bazel#15722]
### Description of the bug:

When target pattern is empty, `bazel build` is happy but when target pattern contains nothing but an EOL, it's not.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
touch foo
bazel build --target_pattern_file=foo --nobuild
```
exit code is 0

But
```
touch foo
echo "" >> foo
bazel build --target_pattern_file=foo --nobuild
```
it shows error
>ERROR: Skipping '': The package part of '' should not end in a slash
WARNING: Target pattern parsing failed.
ERROR: The package part of '' should not end in a slash
INFO: Elapsed time: 0.549s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

### Which operating system are you running Bazel on?

mac

### What is the output of `bazel info release`?

release 4.2.2- (@non-git)

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
org-2562356@github.com:Canva/canva.git
22e68df641fae6d8ad7e23050791fcff0e870483
d56ce1c083cc5130a9a28bf024cdbbd5b90d35ca
```

**Comment by fa93hws** [comment]
My point is that it may be better not to give an error.
I think it can be more user friendly if it can trim empty lines?

**Comment by michajlo** [comment]
I believe this is WAI. A completely empty target-pattern file is equivalent to `bazel build --nobuild`, while a target-pattern file with a single blank line is equivalent to `bazel build --nobuild ""`. In the former case we're explicitly requesting to build nothing, in the latter case we're explicitly requesting building "", which is an invalid target name.
