### ISSUE TITLE
Add command line completion files to github releases

### ISSUE THREAD

**Issue by redsun82** [bazelbuild/bazel#15723]
### Description of the feature request:

I think it would make sense to provide a public link from where one can download pre-built bash and zsh completion files for a given Bazel release.

### What underlying problem are you trying to solve with this feature?

The [instrcutions to set up completion](https://docs.bazel.build/versions/main/completion.html) leave only two possibilities:
* having bazel installed on the system via a package manager or with the full installer downloaded from github
* building the completion from source

This leaves out use cases where the bazel binary has been directly pulled off in isolation, and in particular when bazelisk is involved.

Having a fixed url per release from which to download completion would make it much, much easier and faster to set up in these cases.

**Comment by meteorcloudy** [comment]
@redsun82 If you download https://github.com/bazelbuild/bazel/releases/download/6.0.0-pre.20220601.1/bazel-6.0.0-pre.20220601.1-installer-linux-x86_64.sh and install Bazel with this sh script, the bash completion file will be installed.
