### ISSUE TITLE
Warn if test duration approaches timeout

### ISSUE THREAD

**Issue by jonathan-enf** [bazelbuild/bazel#15731]
### Description of the feature request:

We have a `--test_verbose_timeout_warnings` that warns if a test's execution time is too small for the specified timeout.  But what would be more useful to me would be a warning if a test's execution time is within some configurable percentage (2%) of the maximum timeout.  This warning would emit something to the tune of "WARNING: this test nearly timed out, consider extending the timeout to avoid flaky behavior."

### What underlying problem are you trying to solve with this feature?

Performance of tests in our CI cluster is variable.  A test that doesn't time out during presubmit testing might cause sporadic timeout failures in CI.  We'd like to avoid that.

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

release 5.1.1

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/5015 is similar but is primarily concerned with making the lower-bound for warnings configurable.  This issue is about adding a higher-bound for warnings.  Ideally, both numbers should be configurable.

**Comment by fmeum** [comment]
@bazelbuild/triage not stale
