### ISSUE TITLE
sed version problems when is used in gnu linux

### ISSUE THREAD

**Issue by seoanezonjic** [bazelbuild/bazel#1575]
Compiling bazel from source I get this error:
`Building Bazel from scratch......sed: opción inválida -- E`

I have found this link related with this issue:
http://blog.dmitryleskov.com/small-hacks/mysterious-gnu-sed-option-e/

You can do something to detect which option use in each platform?

**Comment by damienmg** [comment]
Can you specify on which platform exactly you are getting that?

**Comment by seoanezonjic** [comment]
Here results of
uname:
`Linux  3.0.13-0.27-default #1 SMP Wed Feb 15 13:33:49 UTC 2012 (d73692b) x86_64 x86_64 x86_64 GNU/Linux`
SO distro:
`LSB_VERSION="core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64"
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 2`

When I changed the -E flafs to -r the compilation process has continued but now I get this error:
`ERROR: /mnt/home/users/pab_001_uma/pedro/test/tensorflow/git_hub_rep/bazel/bazel-0.3.0/src/main/tools/BUILD:31:1: C++ compilation of rule '//src/main/tools:namespace-sandbox' failed: gcc failed: error executing command 
  (cd /localscratch/users/tmp/bazel.3PCeJD0j/out/bazel-0.3.0 && \
  exec env - \
    PATH=/mnt/home/users/pab_001_uma/pedro/test/tensorflow/git_hub_rep/jdk/jdk1.8.0_101/bin:/mnt/home/soft/git/programs/git_1.9.0/bin:/mnt/backup/soft/compiladores/programs/x86_64/make/4.0/bin:/mnt/backup/soft/compiladores/programs/x86_64/4.9.1/bin:/mnt/home/soft/python/programs/x86_64/bin:/mnt/home/users/pab_001_uma/pedro/tools:/mnt/home/soft/soft_cvi_114/programs/repositorio:/mnt/home/users/pab_001_uma/pedro/bamtools/bin:/mnt/home/users/pab_001_uma/pedro/EMBOSS/emboss:/mnt/home/users/pab_001_uma/pedro/iprscan/bin:/mnt/home/users/pab_001_uma/pedro/.gem/ruby/1.9.1/bin:/mnt/home/users/pab_001_uma/pedro/utils:/mnt/home/users/pab_001_uma/pedro/rubyscripts:/mnt/home/users/cvi_114_uma/pedro/.gem/ruby/1.9.1/bin:/mnt/home/soft/ruby19/programs/x86_64/lib/ruby/gems/1.9.1/bin:/mnt/home/soft/ruby19/programs/x86_64/bin:/mnt/home/users/pab_001_uma/pedro/bin:/mnt/home/users/pab_001_uma/pedro/bin/x86_64:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/games:/opt/bin:/opt/kde3/bin:/usr/lib64/jvm/jre/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/mnt/home/soft/modules/programs/x86_64/scripts \
    TMPDIR=/localscratch/users/tmp \
  /mnt/backup/soft/compiladores/programs/x86_64/4.9.1/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/mnt/backup/soft/compiladores/programs/x86_64/4.9.1/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -fPIC -iquote . -iquote bazel-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 '-std=c99' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -MD -MF bazel-out/local-fastbuild/bin/src/main/tools/_objs/namespace-sandbox/src/main/tools/namespace-sandbox.pic.d -c src/main/tools/namespace-sandbox.c -o bazel-out/local-fastbuild/bin/src/main/tools/_objs/namespace-sandbox/src/main/tools/namespace-sandbox.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from src/main/tools/namespace-sandbox.c:38:0:
src/main/tools/namespace-sandbox.c: In function 'SetupDirectories':
src/main/tools/namespace-sandbox.c:518:43: error: 'MS_REC' undeclared (first use in this function)
   CHECK_CALL(mount("/proc", "proc", NULL, MS_REC | MS_BIND, NULL));
                                           ^
src/main/tools/process-tools.h:34:8: note: in definition of macro 'CHECK_CALL'
   if ((x) == -1) {                                \
        ^
src/main/tools/namespace-sandbox.c:518:43: note: each undeclared identifier is reported only once for each function it appears in
   CHECK_CALL(mount("/proc", "proc", NULL, MS_REC | MS_BIND, NULL));
                                           ^
src/main/tools/process-tools.h:34:8: note: in definition of macro 'CHECK_CALL'
   if ((x) == -1) {                                \
        ^
src/main/tools/namespace-sandbox.c: In function 'main':
src/main/tools/namespace-sandbox.c:784:39: error: 'MS_REC' undeclared (first use in this function)
   CHECK_CALL(mount("none", "/", NULL, MS_REC | MS_PRIVATE, NULL));
                                       ^
src/main/tools/process-tools.h:34:8: note: in definition of macro 'CHECK_CALL'
   if ((x) == -1) {                                \
        ^
src/main/tools/namespace-sandbox.c:784:48: error: 'MS_PRIVATE' undeclared (first use in this function)
   CHECK_CALL(mount("none", "/", NULL, MS_REC | MS_PRIVATE, NULL));
                                                ^
src/main/tools/process-tools.h:34:8: note: in definition of macro 'CHECK_CALL'
   if ((x) == -1) {                                \
        ^
Target //src:bazel failed to build`

**Comment by seoanezonjic** [comment]
Sorry, I have not seen this sed related issue: Compatibility Issue of lower-version `sed`. #1552
But I  addressed the problem in my first message and now I don't know how to fix the last compilation error.

**Comment by damienmg** [comment]
FWIW, SLES 11 is too old so we are probably not going to add native support for it.

Anyway, we can always fix your specific issues.

For the last issue, you can replace "linux-sandbox.cc" by "dummy-sandbox.cc" at https://github.com/bazelbuild/bazel/blob/master/src/main/tools/BUILD#L38

**Comment by seoanezonjic** [comment]
Thank you, it worked perfectly so I'll use it to build tensorflow.

**Comment by damienmg** [comment]
You're welcome :)
