### ISSUE TITLE
[5.0.0/5.2.0] external_include_paths no work for emitting warnings for external sources

### ISSUE THREAD

**Issue by qchenzi** [bazelbuild/bazel#15762]
###  external_include_paths no work for emitting warnings for external sources

I added the following to my project's `.bazelrc` file, 
`build --features=external_include_paths`

I hope that will emit warnings for external deps, but it is not helping me, it is still giving me errors.

<img width="1275" alt="企业微信截图_5967e582-a368-483f-b325-28d046587805" src="https://user-images.githubusercontent.com/21999330/176384893-00559081-66e6-4daf-8092-0178a0cbead2.png">

**Comment by qchenzi** [comment]
@sgowroji Thanks for your reply, I added `com_github_jupp0r_prometheus_cpp` as the external deps by using `http_archive`. 
Besides, I added `build --features=external_include_paths` to my project's .bazelrc file as following:
<img width="1152" alt="企业微信截图_d66907af-6b26-45d5-b1d5-67c49829c265" src="https://user-images.githubusercontent.com/21999330/176404443-053e9f34-a105-4c2d-ab5c-1ea220b39abc.png">

Finally, I executed command `bazel build //myproject/...`, but I still get this error.

**Comment by lripoche** [comment]
still occurring with bazel 5.3.2, any update on this ?
