### ISSUE TITLE
Add new_local_repository() argument to generate MODULE.bazel file as well.

### ISSUE THREAD

**Issue by digit-google** [bazelbuild/bazel#15786]
### Description of the feature request:

BlzMod will soon allow native.local_repository() and native.new_local_repository() to be called from module extension implementation functions (see issue 15412).

This feature request is to add new optional arguments to new_local_repository() to generate MODULE.bazel files, in addition to BUILD.bazel and WORKSPACE.bazel ones.

e.g. `module_file` and `module_file_content`, which would mirror `build_file` + `build_file_content` or `workspace_file`+ `workspace_file_content`.

### What underlying problem are you trying to solve with this feature?

Allow new repositories created in BzlMod module extension functions to call new_local_repository() to create repositories to workspaces that don't have a MODULE.bazel file yet.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 5.2.0

### Have you found anything relevant by searching the web?

I'm filing this as suggested in the bazel-discuss@ group: https://groups.google.com/g/bazel-discuss/c/FQ7yGpXHS-E/m/pY8P1CWlAQAJ

**Comment by Wyverald** [comment]
Actually, after thinking about this a bit, this doesn't really make sense -- by the time we can call `new_local_repository` (i.e. in module extension evaluation), all MODULE.bazel files have already been processed. In other words, `new_local_repository` cannot be used to create a _module_, only a _repo_, so this feature request doesn't really solve anything.

The only possible usage I can think of is if we can create some sort of override using `new_local_repository` (say if we added a new BUILD file attribute to `local_path_override`).

**Comment by digit-google** [comment]
Ah, I see what you mean by "all MODULE.bazel files have already been processed".

In the current WORKSPACE-based scheme, it is possible to use http_archive() to download a tarball and add a missing WORKSPACE to the extracted content. It is also possible to use new_local_repository() to do the same with a the pre-extracted content.

It looks like a registry can provide the missing MODULE.bazel file directly to cover the http_archive() case, but I don't see a way to handle the second one for now.

Another reason for this feature request is the ability to generate a repository / module definition from a separate input file (for example by reading an Android repo manifest in Starlark and extracting the relevant information to generate the module info). It looks like this is not possible at all with the new module (which is ok, but a new restriction that should probably be very clearly documented in the migration guide, unless I am mistaken).

**Comment by Wyverald** [comment]
> In the current WORKSPACE-based scheme, it is possible to use http_archive() to download a tarball and add a missing WORKSPACE to the extracted content. It is also possible to use new_local_repository() to do the same with a the pre-extracted content.

Yes, but both of those actions don't actually do anything (i.e. are non-features, are poorly thought through, shouldn't have been there at all). Inserting a WORKSPACE file also does nothing because Bazel simply doesn't read any WORKSPACE other than the one in the main repo. So Bzlmod doesn't actually remove any functionality here.

> Another reason for this feature request is the ability to generate a repository / module definition from a separate input file (for example by reading an Android repo manifest in Starlark and extracting the relevant information to generate the module info).

You can use module extensions to generate a repo from reading whatever input file (that's exactly what they're designed to do, in fact). You just cannot generate _modules_ from extensions, because that would be a chicken-egg problem (module extensions are run after all modules are resolved, because extensions themselves have their code hosted in modules).

**Comment by digit-google** [comment]
Closing the issue since this is not possible, simply because, as I know understand, a repo is not a module so there is no need to define a MODULE.bazel file in repositories generated through an extension.
