### ISSUE TITLE
Sample Android app loads popup error

### ISSUE THREAD

**Issue by aj-michael** [bazelbuild/bazel#1578]
`//examples/android/java/bazel:hello_world` displays an error message on the screen when run on Sdk 24.

![example_warning](https://cloud.githubusercontent.com/assets/7756476/17179014/a4565782-53e5-11e6-9914-243dfae76ef6.png)

logcat shows a warning:

```
07-27 10:31:07.205  4767  4767 W linker  : /data/app/bazel.android-2/lib/x86/libhello_world.so: is missing DT_SONAME will use basename as a 
replacement: "libhello_world.so"
```

**Comment by aj-michael** [comment]
On SDK23, the logcat warning is present, but no popup is displayed.

**Comment by damienmg** [comment]
(or @aj-michael please self-assign if you are working on it).

**Comment by aj-michael** [comment]
I did self assign. The fix is in Gerrit for review. :smile:
