### ISSUE TITLE
Incorrect error from cquery when configuration flag has the default value

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#15797]
### Description of the bug:

cquery produces incorrect error `transition inputs [@//:flavor] do not correspond to valid settings` when the flag is not set on the command line or set to the default value.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Minimal repro provided here: https://github.com/Bazel-snippets/cquery_transition_error

The following command demonstrates the incorrect error:
 `bazel cquery somepath(transistor,dummy) --transitions=lite --//:flavor=opt`

Error: `transition inputs [@//:flavor] do not correspond to valid settings`

Omiting of the flag `flavor`or setting it to the default value `opt` causes the error. Setting it to `dbg` avoids the error.

Using `--transitions=lite` and `somepath` query function both required to reproduce the problem.

### Which operating system are you running Bazel on?

Mac, Linux, Windows

### What is the output of `bazel info release`?

5.2

**Comment by konste** [comment]
This is weird! I cloned [my repository](https://github.com/Bazel-snippets/cquery_transition_error), run `bazel cquery somepath(transistor,dummy) --transitions=lite --//:flavor=opt` and it reproduced the error just fine! Definitely no syntax errors. 
[command.log](https://github.com/bazelbuild/bazel/files/9040717/command.log)

@sgowroji what is the full error you are seeing? I wonder what line it complains about.

**Comment by gregestren** [comment]
Confirmed, thanks.

Triage comment: as you observed, this requires `--transitions=lite`. I believe what's happening is that the `--transitions` has to "rerun" transitions in a limited form to produce its output. It's likely re-staging the transition without preemptively loading the build setting defaults, as the *actual* transition would do.

In other words, Bazel has to know about a build setting to reason about that build setting. When you build with `--//:my_setting=foo` you're explicitly telling Bazel your build cares about that build setting, so Bazel loads it up, which includes reading its default. When you omit that flag, Bazel has no way of knowing that setting exists until it finds the transition's requirements. In builds *that's* where the setting is loaded and its default is determined. I suspect cquery's `--transitions=lite` fails to do that loading.

**Comment by gregestren** [comment]
Indeed, check out:
https://github.com/bazelbuild/bazel/blob/4c735c150ee72330b7e6769a22d57c0e77e9b41d/src/main/java/com/google/devtools/build/lib/query2/cquery/CqueryTransitionResolver.java#L172-L174)

**Comment by konste** [comment]
That explanation makes sense to me, but it is still a bug with cquery, right?

**Comment by gregestren** [comment]
Yes.
