### ISSUE TITLE
Replace `module.{execution_platforms,toolchains}_to_register` with `register_{execution_platforms,toolchains}`

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#15829]
Currently a MODULE.bazel file might look like this:

```bzl
module(
  name = "foo",
  version = "2.0",
  toolchains_to_register = ["@toolchain_repo//:toolchain"],
)

ext = use_extension("//:extensions.bzl", "ext")
ext.some_tag()
use_repo(ext, "toolchain_repo")
```

The `toolchains_to_register` values way precede the definition of the used repo (`toolchain_repo`). If we had a `register_toolchains` API, we could request to register the toolchain after the `use_repo` call instead, which is easier to read and maintain.

This change should have absolutely no impact on the behavior of toolchain/execution platform registration.

**Comment by Wyverald** [comment]
Now we just need to migrate all existing modules in BCR: see https://github.com/bazelbuild/bazel-central-registry/issues/127

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by ckolli5** [comment]
@bazel-io fork 5.3.0
