### ISSUE TITLE
An --explain-like option that shows which inputs and outputs changed.

### ISSUE THREAD

**Issue by rsalvador** [bazelbuild/bazel#15834]
### Description of the feature request:

The --explain option no longer shows which inputs changed. Analyzing the execution logs is possible to extract that information but it is an involved process. The request is to have a new option that provides the changed inputs so that information is easily available to all bazel users.

This pull request adds a new experimental option implementing this feature request: #15833

Let me know if this option+implementation makes sense and I can add tests to that PR and any other required changes.

### What underlying problem are you trying to solve with this feature?

To optimize bazel builds it is very useful to get information about what input changes triggered each action and if the output of the action did change as a result of those input changes.

### Which operating system are you running Bazel on?

OSX

### What is the output of `bazel info release`?

development version

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

Following the instructions in https://bazel.build/contribute/getting-started#compile-bazel

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
ssh://git@github.com/bazelbuild/bazel.git
94e366a315582e1113d4e5aa48ac27f3f5457c6c
11925130ce1e32e82cb54144c06b36dc39341ded
```

**Comment by meisterT** [comment]
As mentioned on the PR (https://github.com/bazelbuild/bazel/pull/15833#issuecomment-1197805434) I think this is better done outside of Bazel.
