### ISSUE TITLE
Bzlmod: set a default value for version attribute of bazel_dep

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#15830]
We should allow the following usage (version isn't required, when override is used):
```
bazel_dep(name = "A")
local_path_override(
    module_name = "A",
    path = "./A",
)
```

Currently, we have to write `bazel_dep(name = "A", version = "")`, see https://github.com/bazelbuild/examples/blob/5a8696429e36090a75eb6fee4ef4e91a3413ef13/bzlmod/02-override_bazel_module/MODULE.bazel#L33

**Comment by Wyverald** [comment]
This was fixed in https://github.com/bazelbuild/bazel/commit/263c24ec96e8773bdedf90c6d38830cc5a3826f5
