### ISSUE TITLE
bazel coverage fails on windows because test_wrapper cannot find "collect_coverage.sh"

### ISSUE THREAD

**Issue by futt-bucker** [bazelbuild/bazel#15835]
### Description of the bug:

`bazel coverage //cpp/test:mytest`

```
ERROR(tools/test/windows/tw.cc:1294) ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\users\user\_bazel_user\jh7tqry3\execroot\project\bazel-out\x64_windows-fastbuild\bin\cpp\test\mytest.exe.runfiles\project\external\bazel_tools\tools\test\collect_coverage.sh"  cpp/test/mytest.exe
```

My .bazelrc **does not** contain 
```
startup --windows_enable_symlinks
build --enable_runfiles
```

Note how test_wrapper resolved path to `collect_coverage.sh` as to a data file under RUNFILES_DIR. The bug is that on Windows this file does not exist, because runfiles are not enabled.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. have bazel project with `cc_test`
2. run `bazel coverage :test` on windows (does not matter if you use MSVC or MSYS compiler).
3. see the error above.

### Which operating system are you running Bazel on?

Windows 10

### What is the output of `bazel info release`?

development version

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

`bazel build //src:bazel-dev.exe`

Then used `bazel-bin/src/bazel-dev.exe`.

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
https://github.com/futt-bucker/bazel.git
300111212f984587415ad8a1f00bf9d60b31e430
89301f45a7d2bcc3b82b918f96b9ff0037599e4c
```

### Have you found anything relevant by searching the web?

No

**Comment by fmeum** [comment]
The logic in https://github.com/bazelbuild/bazel/blob/d35f923b098e4dc9c90b1ab66b413c216bdee638/tools/test/windows/tw.cc#L438
seems to be causing the chdir to `RUNFILES_DIR`. But it's intended not to run with coverage, see
https://github.com/bazelbuild/bazel/blob/d35f923b098e4dc9c90b1ab66b413c216bdee638/tools/test/windows/tw.cc#L468
I don't have access to a Windows machine, but have you been able to confirm that this check doesn't work as intended?

**Comment by futt-bucker** [comment]
@fmeum I found that this func does not work properly for coverage:
https://github.com/bazelbuild/bazel/pull/15836/files#diff-0724a58c375abd86828d80bc7dd2982dcc6b73eeddda123561f7e6fee0dcf715R1131

It uses `runfiles->Rlocation` which can return non-existing path. The issue I observe is related to this code path.

https://github.com/bazelbuild/bazel/pull/15836

**Comment by fmeum** [comment]
`runfiles->Rlocation` is the correct way to access runfiles. It can return non-existing paths, but only if something else is wrong: If there is no `RUNFILES_DIR` variable because runfiles aren't enabled on Windows, then `runfiles->Rlocation` should use the runfiles manifest instead, which is available.

**Comment by futt-bucker** [comment]
@fmeum if file does not exist under RUNFILES_DIR, and manifest file exist, should `runfiles->Rlocation` return path to `$(bazel info output_base)/external/bazel_tools/test/collect_coverage.sh` or resulting path is expected to be under RUNFILES_DIR?

**Comment by fmeum** [comment]
The former, it should return the oath relative to the exec root, which is what's contained in the runfiles manifest.

**Comment by KrishnaM256** [comment]
can anyone help how to solve this issue ?
@bazelbuild/triage
