### ISSUE TITLE
Source forest creation fails with inconsistently-capitalised path references

### ISSUE THREAD

**Issue by rokstrnisa** [bazelbuild/bazel#1583]
I think Bazel doesn't handle capitalised letters in directories very well, and having some inconsistencies in referencing a directory within BUILD files can lead to this.

```
ERROR: Source forest creation failed: Command failed cmd.exe /c mklink /J "C:\tools\msys64\var\tmp\Bazel\$KNt4ZiP\execroot\<dir>" "C:\tools\msys64\home\rok\<dir>".
```

Note that the above `<dir>` will have the same capitalisation in both cases, which makes this problem even more difficult to debug.

**Comment by dslomov** [comment]
What is actual the value of <dir> in your case?

**Comment by rokstrnisa** [comment]
I don't know exactly what `<tmp>` was, but I do know it didn't include any special letters, e.g. `foo/bar`.

**Comment by hermione521** [comment]
friendly ping @dslomov

**Comment by petemounce** [comment]
This is affecting me, too, on bazel 0.3.2.

**Comment by laszlocsomor** [comment]
I don't have access to my Windows machine right now, but I suspect we should be making all `Path`s and `PathFragment`s lowercase on case-insensitive filesystems.

**Comment by petemounce** [comment]
This is still an issue on bazel 0.4.0-rc3

**Comment by petemounce** [comment]
@laszlocsomor @dslomov friendly ping?

**Comment by laszlocsomor** [comment]
Sorry about the delay. How do I repro this? Do you have maybe an example?

**Comment by abergmeier-dsfishlabs** [comment]
Have the same now on Windows 0.4.0:

    INFO: Found 2 targets and 11 test targets...
    ERROR: Source forest creation failed: D:/msys64/var/tmp/Bazel/DY8I2EUN/execroot/tools/tools (No such file or directory).

**Comment by abergmeier-dsfishlabs** [comment]
Execroot and python sounds like problems you mentioned @dslomov!?

**Comment by laszlomakk** [comment]
Bump.

I just ran into this problem as well, and as I couldn't find a fix; I have actually ended up setting up my whole working environment on Ubuntu instead - where this issue didn't come up at all.

**Comment by laszlocsomor** [comment]
Path handling went through tremendous improvements in the last year, and so did junction creation, so I'm guessing this must be an obsolete bug. If anyone has repro instructions, I'd be happy to test it :)
I'll close this bug for now, please reopen if you have any updates.

**Comment by dooman87** [comment]
I've got the similar problem on bazel 0.26. When rerunning Junit tests:

`
Testing started at 8:03 AM ...
bazel test --tool_tag=ijwb:IDEA:ultimate --curses=no --color=yes --progress_in_terminal_title=no --runs_per_test=1 --flaky_test_attempts=1 --build_event_binary_file=C:\Users\DPOKID~1.OFF\AppData\Local\Temp\intellij-bep-a937d346-6a97-4641-ad71-e9e4f46d38b6 --nobuild_event_binary_file_path_conversion --test_filter=com.dpokidov.cmd.MainTest# --java_debug --test_arg=--wrapper_script_flag=--debug=5005 -- //:tests
WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time
Loading: 
Loading: 0 packages loaded
INFO: Build options --cache_test_results, --test_arg, --test_sharding_strategy, and 1 more have changed, discarding analysis cache.
Analyzing: target //:tests (0 packages loaded, 0 targets configured)
INFO: Analyzed target //:tests (0 packages loaded, 584 targets configured).
INFO: Found 1 test target...
Building: checking cached actions
ERROR: Source forest creation failed: C:/users/dpokidov.officeworks/_bazel_dpokidov/ujvmg64f/execroot/__main__/external/local_jdk (Directory not empty)
INFO: Elapsed time: 11.300s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
ERROR: Couldn't start the build. Unable to run tests
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

Test runtime terminated unexpectedly with exit code 36.
`
Eventually on the next run tests will run successfully.

**Comment by laszlocsomor** [comment]
@meteorcloudy FYI this sounds like https://github.com/bazelbuild/bazel/issues/5907,

**Comment by meteorcloudy** [comment]
This looks more likely using the delete function in Bazel's JNI library. The error message was thrown from [here](https://github.com/bazelbuild/bazel/blob/9835cb4135503768cdf1161746b95d7969ccb938/src/main/java/com/google/devtools/build/lib/buildtool/ExecutionTool.java#L458). I had a change to simplify and optimize `plantSymlinkForest`, but it broke something else and was rollbacked. I will follow up on this.

**Comment by meteorcloudy** [comment]
Filed a new issue for this: https://github.com/bazelbuild/bazel/issues/8545
