### ISSUE TITLE
native.genrule's tools reference ignores --cpu='x64_windows_msvc'

### ISSUE THREAD

**Issue by rokstrnisa** [bazelbuild/bazel#1584]
When using `bazel build --cpu='x64_windows_msvc'` on Windows, any rule using `native.cc_library` still uses `C:/tools/msys64/usr/bin/gcc`.

**Comment by meteorcloudy** [comment]
Can you give more detail about how did you use `native.cc_libray` and which target you tried to build?
I tried to write a simple macro using native.cc_libray and it worked.

**Comment by rokstrnisa** [comment]
I did some digging, and realised it's not actually `native.cc_library`; it's a reference to a tool in `native.genrule`. Apologies for confusion. Details below.

In a `BUILD`:

    load("//tools/build_rules:genschema.bzl", "schema_cc_library")
    
    schema_cc_library(
      name = "schema_cc",
      ...
    )

In `genschema.bzl`:

    def schema_cc_library(name, ...):
      ...
      native.genrule(
        ...
        tools = [<tool>],
        ...
      )

`bazel build --cpu='x64_windows_msvc' <tool>` works fine. `bazel build --cpu='x64_windows_msvc' schema_cc`, however, tries to re-compile `<tool>` with `C:/tools/msys64/usr/bin/gcc`.

Context: Bazel 0.3.0.

**Comment by dslomov** [comment]
Try using `bazel build --host-cpu='x64_windows_msvc' --cpu='x64_windows_msvc'` (tools are built with host CPU)

**Comment by rokstrnisa** [comment]
Yes, that works, with the underscore, i.e. `bazel build --host_cpu='x64_windows_msvc' --cpu='x64_windows_msvc'`. Thanks!

I guess something should still be done about this, however, so I'm not closing the issue.

**Comment by dslomov** [comment]
This will be "fixed" when we switch our default cc toolchain on Windows to x64_windows_msvc. Currently our default toolchain is the msys one, so everything here is working as expected.
