### ISSUE TITLE
--config in .bazelrc doesn't appear to follow build to test inheritance

### ISSUE THREAD

**Issue by srdo-humio** [bazelbuild/bazel#15845]
### Description of the bug:

We are using a config flag (`--config=ci`) to override some defaults from the workspace-level .bazelrc on CI. We set this on CI in the home `~/.bazelrc` as `build --config=ci`.

We are seeing Bazel pick defaults instead of overrides when the command being run is `bazel test`. It works as expected with `bazel build`. Switching the command in `~/.bazelrc` to `test` also works as expected.

We have a minimal reproducer described below.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

WORKSPACE:
```
Empty
```

BUILD.bazel:
```
genrule(
    name = "demo",
    outs = ["hello.txt"],
    cmd_bash = "echo 'hello' > $@"
)
```

`.bazelrc` (workspace level):
```
test --color=no
test:ci --color=yes
```

`~/.bazelrc` (home directory):
```
build --config=ci
```

Run `bazel test demo`. Colors are disabled. We expected colors to be on, since `test` inherits from `build`, and `--config=ci` is set for `build`, and the workspace level RC file enables colors for test when `--config=ci` is enabled.

#### Workarounds
* Changing `build` to `test` in the home `.bazelrc`, or just setting the config for both `build` and `test`.
* Setting `--config=ci` explicitly when invoking Bazel.
* Changing `test` to `build` in the workspace `.bazelrc` and running `build` instead also causes colors to be enabled.

### Which operating system are you running Bazel on?

MacOS Monterey

### What is the output of `bazel info release`?

6.0.0-pre.20220608.2

**Comment by aranguyen** [comment]
With inheritance, precedence depends on specificity. Commands such as test and release inherit flags from build. The inheriting command is said to be more specific and thus the associated flags take precedence https://docs.bazel.build/versions/main/guide.html#bazelrc-syntax-and-semantics. So in this case because you have `test --color=no` and `test` is more specific than `build`, `test --color=no` always take precedence over your `build --config=ci`. 

What were you trying to achieve with defining a test config `test:ci` and use it for build? Why not defining a build config and let inheritence takes place when testing? This is your workaround 3.

**Comment by srdo-humio** [comment]
@aranguyen The above is simplified to show the slightly odd behavior. Our actual use case for this was this:

When doing local development, we wanted `--test_output=errors` configured for our devs. When running on CI, we wanted `--test_output=all` instead. We attempted to do this by having the following lines in `.bazelrc` in the project root:

```
test --test_output=errors
test:ci --test_output=all
```

On CI, rather than adding `--config=ci` to every command, we thought we'd just write a home-dir `.bazelrc` before starting the build, containing 

```
build --config=ci
```

This turned out to not work. Running `bazel test someTarget` on CI would use the errors-only output. In order to fix it, we needed to change the CI `.bazelrc` to say 

```
build --config=ci
test --config=ci
``` 

Since the docs say the home `.bazelrc` is interpreted before the project-level `.bazelrc`, I expected something like this order:

```
# home bazelrc
build --config=ci # 1: CI config is enabled for test immediately due to inheritance

# project-level bazelrc
test --test_output=errors # 2: This line is applied
test:ci --test_output=all # 3: Since CI config is enabled, this line is applied, overriding step # 2.
```

If I understand you correctly, Bazel instead does something like this:

```
# home bazelrc
build --config=ci # 1: Not immediately applied, since we are running "test" and not "build"

# project-level bazelrc
test --test_output=errors # 2: Output is set to error since we are running "test"
test:ci --test_output=all # 3: Since CI config is not enabled, this line is skipped

# home bazelrc
build --config=ci # 4: Applied due to inheritance
```
