### ISSUE TITLE
`bazel clean --expunge` often fails on Windows

### ISSUE THREAD

**Issue by rokstrnisa** [bazelbuild/bazel#1586]
```
$ bazel clean --expunge
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
ERROR: C:/tools/msys64/var/tmp/Bazel/$KNt4ZiP/command.log (Permission denied).
```

`command.log` contains no information about the `bazel clean --expunge` failure, only output of the previous build commands.

**Comment by chenyosef** [comment]
Saw that issue as well - after killing the java process (probably hanged their from previous build), 'bazel clean --expunge' succeed.

**Comment by laszlocsomor** [comment]
The `command.log` is what contains the output above, so the `clean` command is trying to log the clean event and delete the log file at the same time.

**Comment by laszlocsomor** [comment]
I did some debugging. On Linux we can delete the `command.log` at any time using `rm`, but on Windows we always get "Device or resource busy" as long as the bazel server is running (i.e. until you run `bazel shutdown`).

**Comment by jakemac53** [comment]
I get a similar issue when using new_local_repository, it seems the `tools\msys64` directory is read only, and it keeps reverting back to read only on its own if I change it....

**Comment by laszlocsomor** [comment]
@jakemac53 : Thanks for reporting that. It doesn't sound like the same issue to me. Is it reproducible? If so, could you please report a separate issue for it?

As for this bug I made sure the `command.log` is closed before attempting to actually clean the output tree and now the command can proceed, but then finds another open file `jvm.out`. We may need to find a principled way to close all file handles before cleaning. The alternative would be to open files with delete permission (I recall `CreateFile` has something similar on Windows) but I haven't found any way to do that with `java.io`/`java.nio`.

**Comment by petemounce** [comment]
Is 7f3ffbc in 0.4.0-rc3?

```
λ bazel clean --expunge
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
ERROR: C:/tools/msys64/var/tmp/Bazel/pkGed45b/command.log (Permission denied).
```

**Comment by laszlocsomor** [comment]
The release candidate was cut prior to this commit. :(
@damienmg , can we cut the new RC at a later commit? This is not the first change I'd like to get into 0.4

**Comment by damienmg** [comment]
+Kristina Chodorow <kchodorow@google.com> is the 0.4 release manager. I
guess we can cherry-pick it since a RC today still means we can release on
wednesday. How important it is?

**Comment by laszlocsomor** [comment]
It's a P1, so important. When's the next release expected, if this doesn't make into 0.4?

**Comment by damienmg** [comment]
Every month so somewhere in November.

**Comment by ulfjack** [comment]
It's certainly in 0.4.2 now.

**Comment by laszlocsomor** [comment]
We still see "bazel clean" failures sometimes, and it may be due to the persistent java workers holding on to open files, which is also the suspected culprit of https://github.com/bazelbuild/bazel/issues/2538.

**Comment by philwo** [comment]
I think we have a fix this now (https://github.com/bazelbuild/bazel/commit/dc857b3f0785e15d48500a4f45cea804612ad3a0), but I haven't had the time to verify on Windows.

I've checked an idle JavaBuilder using http://file-leak-detector.kohsuke.org/ and couldn't see leaked file handles anymore after the fix, so let's hope that this helped.

**Comment by laszlocsomor** [comment]
Sorry, dcaee09 is an irrelevant commit.

**Comment by damienmg** [comment]
Steren probably have the wrong bug number in he change

**Comment by Helcaraxan** [comment]
This is still an issue.
From what I have seen @laszlocsomor's comment https://github.com/bazelbuild/bazel/issues/1586#issuecomment-281970927 is spot-on as I know have to kill all Bazel processes manually before the `bazel clean` works again.

**Comment by philwo** [comment]
I ran into this just now:

```
> bazel clean --expunge                                                                                                   
INFO: Reading 'startup' options from C:\Users\philwo/.bazelrc: --output_user_root=c:/src/_bazel_philwo                    
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
ERROR: C:/src/_bazel_philwo/o7dye3qe/java.log (Permission denied)                                                         
```

@laszlocsomor explained that it happens because the Java server tries to delete its log file, which it holds an open handle to (because its stdout is redirected to that file) and thus fails to delete it. We could create the file with delete sharing permissions, which would allow the server to delete it despite the open handle, but then writes to the deleted file will be lost.

@philwo pointed out that we only try to delete the log file with clean --expunge, but when doing so, we also exit the server process after the clean command finished - so the situation where we try to write to the deleted log file should actually never happen (and even if it happens, it's probably rather irrelevant).

**Comment by laszlocsomor** [comment]
> @laszlocsomor explained that it happens because the Java server tries to delete its log file

I realized this is wrong. The file in question is "java.log", which is created and held open by the java process, see [startup_options.cc:416](https://github.com/bazelbuild/bazel/blob/c7696b47a4a12b1e56e41246770cbd44ad1c9c3e/src/main/cpp/startup_options.cc#L416). The file I talked about earlier was "jvm.log", which is indeed created in [blaze::CreateJvmOutputFile](https://github.com/bazelbuild/bazel/blob/c7696b47a4a12b1e56e41246770cbd44ad1c9c3e/src/main/cpp/blaze_util_windows.cc#L637-L647) so we could open that with deletion sharing.

**Comment by laszlocsomor** [comment]
Related bugs: #3043, #2480, #1906
