### ISSUE TITLE
JSON worker protocol doesn't match docs

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/bazel#15864]
### Description of the bug:

https://docs.bazel.build/versions/5.2.0/creating-workers.html

The docs have the JSON worker protocol as

```json
{
  "exit_code" : 1,
  "output" : "Action failed with the following message:\nCould not find input file \"/path/to/my/file/1\"",
  "request_id" : 12
}
```

But in reality, the protocol uses camel case, not snake case fields https://github.com/bazelbuild/bazel/blob/22f63d3981bfcbf20367252385aff24ff288199b/src/main/java/com/google/devtools/build/lib/worker/JsonWorkerProtocol.java

Most significantly, it should be `"exitCode"`. That's a pretty important field.

(Maybe having everything optional+ignored in data formats isn't the greatest...... :/ )

**Comment by larsrc-google** [comment]
I have updated the documentation.
