### ISSUE TITLE
Documentation issue: Windows How to overwrite the original bazel settings?

### ISSUE THREAD

**Issue by wz2wd** [bazelbuild/bazel#15879]
I have VS2017 and VS2019 installed on my current computer, and I have successfully set up bazel through MSYS2, but I just want to keep the bazel settings of VS2019. How should I solve it?

**Comment by meteorcloudy** [comment]
@wz2wd Do you mean to keep using VS2019? You can just set the `BAZEL_VC` environment variable, this also works in MSYS2.
See https://bazel.build/configure/windows#build_cpp
