### ISSUE TITLE
We build and test against a very old version of rules_cc

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#15878]
### Description of the bug:

distdir_deps.bzl points to a commit from 2020.
src/test/py/bazel/test_base.py points to a different, even older one.
Just updating them breaks some integration tests that build workspaces

My hunch is that the old versions have fewer dependencies, so they don't have problems with deps.  The newer rules_cc seems to bring in rules_pkg, but we get a cryptic error message
```
ERROR: Every .bzl file must have a corresponding package, but '//pkg:deps.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Update distdir_deps
```
diff --git a/distdir_deps.bzl b/distdir_deps.bzl
index c3f3a78d5c..bd06247197 100644
--- a/distdir_deps.bzl
+++ b/distdir_deps.bzl
@@ -53,12 +53,11 @@ DIST_DEPS = {
     # Note: This is not in sync with src/test/java/com/google/devtools/build/lib/blackbox/framework/BlackBoxTestEnvironment.java.
     #       Perhaps it should be.
     "rules_cc": {
-        "archive": "b1c40e1de81913a3c40e5948f78719c28152486d.zip",
-        "sha256": "d0c573b94a6ef20ef6ff20154a23d0efcb409fb0e1ff0979cec318dfe42f0cdd",
-        "strip_prefix": "rules_cc-b1c40e1de81913a3c40e5948f78719c28152486d",
+        "archive": "rules_cc-0.0.1.tar.gz",
+        "sha256": "4dccbfd22c0def164c8f47458bd50e0c7148f3d92002cdb459c2a96a68498241",
         "urls": [
-            "https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/b1c40e1de81913a3c40e5948f78719c28152486d.zip",
-            "https://github.com/bazelbuild/rules_cc/archive/b1c40e1de81913a3c40e5948f78719c28152486d.zip",
+            "https://mirror.bazel.build/github.com/bazelbuild/rules_cc/releases/download/0.0.1/rules_cc-0.0.1.tar.gz",
+            "https://github.com/bazelbuild/rules_cc/releases/download/0.0.1/rules_cc-0.0.1.tar.gz",
         ],
         "used_in": [
             "additional_distfiles",
```
```
bazel test   //src/test/py/bazel:bazel_workspace_test
```

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

head

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?
 
As of July 14, 2022

**Comment by aiuto** [comment]
Ah, but updating it seems to break things, so we have badly built tests.
I'm taking a look at half the problem in a PR I am working on.
That will at least get stop using a URL embedded in the python sources and
align with distdir_deps. It should also be one less thing to hunt down when
you update integration tests for bzlmod rather than workspace.

**Comment by meteorcloudy** [comment]
Oh, maybe I clicked LGTM too fast? Feel free to roll it back if necessary.

**Comment by aiuto** [comment]
It was not too fast. The change about using distdir_deps.bzl is the right path forward because it aligns the tests use of rules_cc with the rules_cc we use in other places. Having different ones is confusing.
It leaves the second problem of using a rules_cc which is nearly 2 years old, which is what this issue is about.

**Comment by fmeum** [comment]
This is controlled by Bzlmod now.
