### ISSUE TITLE
Even with BAZEL_PYTHON set, cc_configure.bzl shows a warning

### ISSUE THREAD

**Issue by rokstrnisa** [bazelbuild/bazel#1587]
$ which python
    /c/Python27/python
    $ echo $BAZEL_PYTHON
    /c/Python27/python
    $ bazel version
    Build label: 0.3.1-2016-07-29 (@1f49b6b)
    ...
    $ bazel build --cpu='x64_windows_msvc'
    WARNING: C:/tools/msys64/var/tmp/Bazel/$KNt4ZiP/external/bazel_tools/tools/cpp/cc_configure.bzl:57:3:
    Auto-Configuration Warning: 'BAZEL_PYTHON' is not set, start finding python in PATH.
    ...

**Comment by meteorcloudy** [comment]
Try `bazel clean` and then run build to configure it again?
And currently, cc_configure.bzl only accept Windows style path as BAZEL_PATH, so please set it to `BAZEL_PATH=C:/Python27/python.exe`

**Comment by rokstrnisa** [comment]
After `bazel clean`, I haven't seen this. Closing issue; will re-open if I see it again.
