### ISSUE TITLE
Protobuf fails to build with Bazel 0.3.1

### ISSUE THREAD

**Issue by rokstrnisa** [bazelbuild/bazel#1589]
With the following in `WORKSPACE`:

    http_archive(
      name = "protobuf",
      url = "https://github.com/google/protobuf/archive/v3.0.0-beta-2.zip",
      sha256 = "f7df9a584e2f09c93e8397c905f9c0d85a0cc698c179a134983ba5146419ad5c",
      strip_prefix = "protobuf-3.0.0-beta-2",
    )

`bazel build --cpu='x64_windows_msvc' --verbose_failures @protobuf//:protobuf` succeeds with Bazel 0.3.0, but fails with Bazel 0.3.1:

    INFO: Found 1 target...
    ERROR: C:/tools/msys64/var/tmp/Bazel/$KNt4ZiP/external/protobuf/BUILD:64:1: C++ compilation of rule '@protobuf//:protobuf' failed: msvc_cl.bat failed: error executing command
      cd C:/tools/msys64/var/tmp/Bazel/$KNt4ZiP/execroot/everything
      SET PATH=external/local_config_cc/wrapper/bin
      external/local_config_cc/wrapper/bin/msvc_cl.bat -m64 /D__inline__=__inline /DOS_WINDOWS=OS_WINDOWS /DCOMPILER_MSVC /DNOGDI /DNOMINMAX /DPRAGMA_SUPPORTED /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /D_USE_MATH_DEFINES /nologo /bigobj /Zm500 /J /Gy /GF /W3 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /DNDEBUG /Od -Xcompilation-mode=fastbuild /Iexternal/protobuf /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/protobuf /Iexternal/bazel_tools /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/bazel_tools /Iexternal/protobuf/src /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/protobuf/src /Iexternal/bazel_tools/tools/cpp/gcc3 /DEPENDENCY_FILE bazel-out/vc_14_0_x64-fastbuild/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/api.pb.d /c external/protobuf/src/google/protobuf/api.pb.cc /Fobazel-out/vc_14_0_x64-fastbuild/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/api.pb.o -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-error=unused-function: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
    The system cannot find the path specified.
    Target @protobuf//:protobuf failed to build
    INFO: Elapsed time: 1.069s, Critical Path: 0.12s

**Comment by dslomov** [comment]
Can it be the '$' in the temp directory name?

**Comment by laszlocsomor** [comment]
I can repro the problem, and it's not because of the "$" in the temp path.
Alas, I don't yet know what's causing it.

### With bazel-0.3.0 and "$" in the path
```
$ /c/work/bazelbin/\$blah/bazel.0.3.0.exe build --cpu='x64_windows_msvc' --verbose_failures \
    @protobuf//:protobuf >&/dev/null ; echo $?
0
```

### With bazel-0.3.1, no "$" in the path
```
$ /c/work/bazelbin/bazel.0.3.1.exe build --cpu='x64_windows_msvc' --verbose_failures \
  @protobuf//:protobuf ; echo $?
WARNING: C:/tempdir/Bazel/MGAgSgPx/external/bazel_tools/tools/cpp/cc_configure.bzl:57:3:
Auto-Configuration Warning: 'BAZEL_PYTHON' is not set, start finding python in PATH.
.
INFO: Found 1 target...
ERROR: C:/tempdir/Bazel/MGAgSgPx/external/protobuf/BUILD:64:1: C++ compilation of rule '@protobuf//:protobuf' failed: msvc_cl.bat failed: error executing command
  cd C:/tempdir/Bazel/MGAgSgPx/execroot/bazel2
  SET PATH=external/local_config_cc/wrapper/bin
  external/local_config_cc/wrapper/bin/msvc_cl.bat -m64 /D__inline__=__inline /DOS_WINDOWS=OS_WINDOWS /DCOMPILER_MSVC /DNOGDI /DNOMINMAX /DPRAGMA_SUPPORTED /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /D_USE_MATH_DEFINES /nologo /bigobj /Zm500 /J /Gy /GF /W3 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /DNDEBUG /Od -Xcompilation-mode=fastbuild /Iexternal/protobuf /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/protobuf /Iexternal/bazel_tools /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/bazel_tools /Iexternal/protobuf/src /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/protobuf/src /Iexternal/bazel_tools/tools/cpp/gcc3 /DEPENDENCY_FILE bazel-out/vc_14_0_x64-fastbuild/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/api.pb.d /c external/protobuf/src/google/protobuf/api.pb.cc /Fobazel-out/vc_14_0_x64-fastbuild/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/api.pb.o -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-error=unused-function: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 2.
Warning: Unmatched arguments: -Wwrite-strings -Woverloaded-virtual -Wno-error=unused-function
c1xx: fatal error C1083: Cannot open compiler intermediate file: 'C:\work\bazel2\C;C:\tools\msys64\tempdir\_CL_a91b31ffex': Invalid argument
Target @protobuf//:protobuf failed to build
INFO: Elapsed time: 5.433s, Critical Path: 3.76s
1
```

### With bazel-0.3.1 and "$" in the path
```
$ /c/work/bazelbin/\$blah/bazel.0.3.1.exe build --cpu='x64_windows_msvc' \
  --verbose_failures @protobuf//:protobuf ; echo $?
WARNING: C:/tempdir/Bazel/MGAgSgPx/external/bazel_tools/tools/cpp/cc_configure.bzl:57:3:
Auto-Configuration Warning: 'BAZEL_PYTHON' is not set, start finding python in PATH.
.
INFO: Found 1 target...
ERROR: C:/tempdir/Bazel/MGAgSgPx/external/protobuf/BUILD:64:1: C++ compilation of rule '@protobuf//:protobuf' failed: msvc_cl.bat failed: error executing command
  cd C:/tempdir/Bazel/MGAgSgPx/execroot/bazel2
  SET PATH=external/local_config_cc/wrapper/bin
  external/local_config_cc/wrapper/bin/msvc_cl.bat -m64 /D__inline__=__inline /DOS_WINDOWS=OS_WINDOWS /DCOMPILER_MSVC /DNOGDI /DNOMINMAX /DPRAGMA_SUPPORTED /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /D_USE_MATH_DEFINES /nologo /bigobj /Zm500 /J /Gy /GF /W3 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /DNDEBUG /Od -Xcompilation-mode=fastbuild /Iexternal/protobuf /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/protobuf /Iexternal/bazel_tools /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/bazel_tools /Iexternal/protobuf/src /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/protobuf/src /Iexternal/bazel_tools/tools/cpp/gcc3 /DEPENDENCY_FILE bazel-out/vc_14_0_x64-fastbuild/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/unknown_field_set.d /c external/protobuf/src/google/protobuf/unknown_field_set.cc /Fobazel-out/vc_14_0_x64-fastbuild/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/unknown_field_set.o -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-error=unused-function: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 2.
Warning: Unmatched arguments: -Wwrite-strings -Woverloaded-virtual -Wno-error=unused-function
c1xx: fatal error C1083: Cannot open compiler intermediate file: 'C:\work\bazel2\C;C:\tools\msys64\tempdir\_CL_1f4d0528ex': Invalid argument
Target @protobuf//:protobuf failed to build
INFO: Elapsed time: 5.122s, Critical Path: 3.56s
1
```

**Comment by laszlocsomor** [comment]
Something's not right.

First, Bazel picks up the value of $TMP upon startup and holds on to it as long as the server runs. I'll open a separate issue for that.

Second, whether $TMP points to an absolute Windows-style or absolute Unix-style path, and whether Bazel runs in server or batch mode, have effects on the success of the build.

**Server mode, TMP is an absolute Windows path**
```
$ export TMP=c:/tempdir/i_am_the_captain
$ /c/work/bazelbin/bazel.0.3.1.exe shutdown
$ /c/work/bazelbin/bazel.0.3.1.exe build --cpu=x64_windows_msvc --verbose_failures @protobuf//:protobuf
...
c1xx: fatal error C1083: Cannot open compiler intermediate file: 'C:\work\bazel2\c;C:\tools\msys64\tempdir\i_am_the_captain\_CL_4bc2ecbdex': Invalid argument
```

**Server mode, TMP is an absolute Unix path**
```
$ export TMP=/c/tempdir/i_like_trains
$ /c/work/bazelbin/bazel.0.3.1.exe shutdown
$ /c/work/bazelbin/bazel.0.3.1.exe build --cpu=x64_windows_msvc --verbose_failures @protobuf//:protobuf
...
c1xx: fatal error C1083: Cannot open compiler intermediate file: 'C:\tempdir\i_like_trains\_CL_65582202ex': No such file or directory
```

**Batch mode, TMP is an absolute Windows path**
```
$ export TMP=c:/tempdir/i_am_the_captain
$ /c/work/bazelbin/bazel.0.3.1.exe --batch build --cpu=x64_windows_msvc --verbose_failures @protobuf//:protobuf ; echo "Exit: $?"
...
WARNING: C:/tempdir/Bazel/MGAgSgPx/external/bazel_tools/tools/cpp/cc_configure.bzl:57:3:
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
...
INFO: Elapsed time: 15.345s, Critical Path: 0.37s
Exit: 0
```

**Batch mode, TMP is an absolute Unix path**
```
$ export TMP=/c/tempdir/i_like_trains
$ /c/work/bazelbin/bazel.0.3.1.exe --batch build --cpu=x64_windows_msvc --verbose_failures @protobuf//:protobuf ; echo "Exit: $?"
...
WARNING: C:/tempdir/Bazel/MGAgSgPx/external/bazel_tools/tools/cpp/cc_configure.bzl:57:3:
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
...
INFO: Elapsed time: 15.763s, Critical Path: 0.35s
Exit: 0
```

**Comment by laszlocsomor** [comment]
https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/option_processor.cc#L424-L426 explain the Warnings in the `--batch` builds.

https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/option_processor.cc#L427-L439 explain why the server holds on to `$TMP` (see also issue #1683).

Still to explain:

- why @rokstrnisa's build is failing
- why MSVC uses a weird temp path when `$TMP` is an absolute Windows path

**Comment by laszlocsomor** [comment]
Found the culprit for the weird `$TMP` value: issue #1684.

Still unknown why @rokstrnisa's build is failing, but now I'm back to square one. :)

**Comment by laszlocsomor** [comment]
@rokstrnisa, I suspect your build fails because of #1684.

Could you please try the following with bazel 0.3.1 and tell us what happens?

```
$ export TMP=/c/tempdir
$ mkdir $TMP
$ bazel build --cpu='x64_windows_msvc' --verbose_failures @protobuf//:protobuf
```

**Comment by rokstrnisa** [comment]
$ export TMP=/c/tempdir
    $ mkdir $TMP
    $ bazel build --verbose_failures --cpu='x64_windows_msvc' --host_cpu='x64_windows_msvc' @protobuf//:protobuf
    INFO: Found 1 target...
    ERROR: C:/tools/msys64/var/tmp/Bazel/$KNt4ZiP/external/protobuf/BUILD:64:1: C++ compilation of rule '@protobuf//:protobuf' failed: msvc_cl.bat failed: error executing command
      cd C:/tools/msys64/var/tmp/Bazel/$KNt4ZiP/execroot/everything
      SET PATH=external/local_config_cc/wrapper/bin
      external/local_config_cc/wrapper/bin/msvc_cl.bat -m64 /D__inline__=__inline /DOS_WINDOWS=OS_WINDOWS /DCOMPILER_MSVC /DNOGDI /DNOMINMAX /DPRAGMA_SUPPORTED /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /D_USE_MATH_DEFINES /nologo /bigobj /Zm500 /J /Gy /GF /W3 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /DNDEBUG /Od -Xcompilation-mode=fastbuild /Iexternal/protobuf /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/protobuf /Iexternal/bazel_tools /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/bazel_tools /Iexternal/protobuf/src /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/protobuf/src /Iexternal/bazel_tools/tools/cpp/gcc3 /DEPENDENCY_FILE bazel-out/vc_14_0_x64-fastbuild/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/descriptor_database.d /c external/protobuf/src/google/protobuf/descriptor_database.cc /Fobazel-out/vc_14_0_x64-fastbuild/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/descriptor_database.o -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-error=unused-function: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
    The system cannot find the path specified.
    Target @protobuf//:protobuf failed to build
    INFO: Elapsed time: 1.167s, Critical Path: 0.14s

**Comment by rokstrnisa** [comment]
The same issue happens for me on HEAD:

    $ bazel version
    Build label: 0.3.1-2016-08-26 (@0b701b2)
    $ bazel build --verbose_failures --cpu='x64_windows_msvc' --host_cpu='x64_windows_msvc' @protobuf//:protobuf
    Extracting Bazel installation...
    Cannot terminate server process with PID 5768
    .
    INFO: Found 1 target...
    ERROR: C:/tools/msys64/var/tmp/Bazel/$KNt4ZiP/external/protobuf/BUILD:64:1: C++ compilation of rule '@protobuf//:protobuf' failed: msvc_cl.bat failed: error executing command
      cd C:/tools/msys64/var/tmp/Bazel/$KNt4ZiP/execroot/everything
      SET PATH=external/local_config_cc/wrapper/bin
      external/local_config_cc/wrapper/bin/msvc_cl.bat -m64 /D__inline__=__inline /DOS_WINDOWS=OS_WINDOWS /DCOMPILER_MSVC /DNOGDI /DNOMINMAX /DPRAGMA_SUPPORTED /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /D_USE_MATH_DEFINES /nologo /bigobj /Zm500 /J /Gy /GF /W3 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /DNDEBUG /Od -Xcompilation-mode=fastbuild /Iexternal/protobuf /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/protobuf /Iexternal/bazel_tools /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/bazel_tools /Iexternal/protobuf/src /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/protobuf/src /Iexternal/bazel_tools/tools/cpp/gcc3 /DEPENDENCY_FILE bazel-out/vc_14_0_x64-fastbuild/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/map_field.d /c external/protobuf/src/google/protobuf/map_field.cc /Fobazel-out/vc_14_0_x64-fastbuild/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/map_field.o -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-error=unused-function: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
    The system cannot find the path specified.
    Target @protobuf//:protobuf failed to build
    INFO: Elapsed time: 12.299s, Critical Path: 0.59s

**Comment by laszlocsomor** [comment]
I cannot repro the issue.

What happens if you do exactly like this?
Note that `TMP` and `TEMP` are slightly different this time than before.

```
$ git checkout 0b701b2
Checking out files: 100% (344/344), done.
...

$ export TMP=C:/tempdir

$ cat <<EOF >>WORKSPACE
http_archive(
  name = "protobuf",
  url = "https://github.com/google/protobuf/archive/v3.0.0-beta-2.zip",
  sha256 = "f7df9a584e2f09c93e8397c905f9c0d85a0cc698c179a134983ba5146419ad5c",
  strip_prefix = "protobuf-3.0.0-beta-2",
)
EOF

$ ./compile.sh
...

$ export TEMP=$TMP

$ /c/work/bazel-msys/output/bazel.exe --batch version
Build label: 0.3.1-2016-09-05 (@0b701b2)

$ /c/work/bazel-msys/output/bazel.exe --batch build --verbose_failures --cpu='x64_windows_msvc' --host_cpu='x64_windows_msvc' @protobuf//:protobuf
...
Target @protobuf//:protobuf up-to-date:
  C:/tools/msys64/var/tmp/Bazel/0UKZel2Y/execroot/bazel-msys/bazel-out/vc_14_0_x64-fastbuild/bin/external/protobuf/libprotobuf.a
INFO: Elapsed time: 37.175s, Critical Path: 21.79s
```

**Comment by rokstrnisa** [comment]
Followed the exact commands above. Fails on `$ ./compile.sh` with

    Target //src:bazel.exe up-to-date:
      C:/tempdir/bazel_DImOOQ1x/out/execroot/bazel/bazel-out/local-fastbuild/bin/src/bazel.exe
    INFO: Elapsed time: 176.038s, Critical Path: 166.08s
    cp: cannot stat ‘bazel-bin/src/bazel.exe’: No such file or directory

So the `cp` failed, but the `tempdir` also doesn't contain the output, i.e.

    $ ls /c/tempdir/
    hsperfdata_rok
    $ find /c/tempdir -name bazel.exe
    $

**Comment by rokstrnisa** [comment]
Doing a `git clean -xdf` and repeating the process got around the above problem, and worked on 0b701b2. Thanks!

**Comment by laszlocsomor** [comment]
Wow, glad to hear that! Thanks for having given it another try. I hope you won't have to report this issue again :)
