### ISSUE TITLE
objc_library targets cannot have .h files in the "srcs" attribute

### ISSUE THREAD

**Issue by jbeder** [bazelbuild/bazel#159]
cc_library lets you specify .h files in "srcs", but objc_library does not. Is this intended?

An obvious workaround is to put the .h files in "hdrs", but that allows them to be included in later dependent targets, which isn't always desired.

**Comment by ulfjack** [comment]
I don't think this is intended.

**Comment by ob** [comment]
This is fixed AFAICT.
