### ISSUE TITLE
Shell commands don't work in rolling release on Windows any more (Bash not found)

### ISSUE THREAD

**Issue by phst** [bazelbuild/bazel#15919]
### Description of the bug:

When using any rule that uses a shell action (e.g. `genrule`), the `rolling` release now hardcodes `c:\tools\msys64\usr\bin\bash.exe` as location of Bash, no matter where MSys64 is actually installed. Setting `BAZEL_SH` doesn't work any more. In the `latest` release, Bazel would find the MSys tools with or without BAZEL_SH.
Maybe commit eeb2e04e52cfad165a1bde33ce2d83a392f53d00 is related since it touches this code.
Note that the default installation directory for MSys64 is C:\MSys64, not C:\Tools\MSys64, so I think even as a fallback/default value the filename would be incorrect.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create an empty WORKSPACE file and the following BUILD file:

```python
genrule(
    name = "foo",
    outs = ["foo.txt"],
    cmd = "echo bar > $@",
)
```

Then run

```cmd
SET USE_BAZEL_VERSION=rolling
bazelisk build //:all
```

No matter whether BAZEL_SH is set or not, Bazel will try to find Bash at `c:\tools\msys64\usr\bin\bash.exe`, which fails unless it's actually installed at that location. (The default installation directory is C:\MSYS64, not C:\Tools\MSYS64.)

### Which operating system are you running Bazel on?

Microsoft Windows [Version 10.0.17763.2803]

### What is the output of `bazel info release`?

release 6.0.0-pre.20220630.1

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
irrelevant
```

**Comment by Wyverald** [comment]
cc @susinmotion

**Comment by phst** [comment]
Sorry, forgot to add the logs:

```none
C:\Users\p\bazel-bash>bazel build --verbose_failures //...
INFO: Invocation ID: 2bb645e4-822f-493d-b6bf-1213783b0097
INFO: Analyzed target //:foo (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: C:/users/p/bazel-bash/BUILD:1:8: Executing genrule //:foo failed: (Exit -1): bash.exe failed: error executing command (from target //:foo)
  cd /d C:/users/p/_bazel_p/tuh2xazr/execroot/__main__
  SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\Windows;C:\Windows\System32;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Users\p\AppData\Local\bazelisk\downloads\bazelbuild\bazel-6.0.0-pre.20220630.1-windows-x86_64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Python39\Scripts\;C:\Program Files\Python39\;C:\ProgramData\GooGet;C:\Program Files\Google\Compute Engine\metadata_scripts;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\PowerShell\7\;C:\Program Files\Google\Compute Engine\sysprep;C:\Program Files\Python310\;C:\Program Files\Python310\Scripts\;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files\Bazelisk;C:\ProgramData\chocolatey\bin;C:\Program Files\LLVM\bin;C:\Users\p\AppData\Local\Microsoft\WindowsApps;
    SET RUNFILES_MANIFEST_ONLY=1
  c:\tools\msys64\usr\bin\bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; echo bar > bazel-out/x64_windows-fastbuild/bin/foo.txt
# Configuration: 64dc20357653b94da3c5d5476f9b679a282363d051772df15f87d009a03bfe4b
# Execution platform: @local_config_platform//:host
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("c:\tools\msys64\usr\bin\bash.exe" -c "source external/bazel_tools/tools/genrule/genrule-setup.sh; echo bar > bazel-out/x64_windows-fastbuild/bin/foo.txt"): The system cannot find the file specified.
 (error: 2)
Target //:foo failed to build
INFO: Elapsed time: 0.290s, Critical Path: 0.04s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully

C:\Users\p\bazel-bash>echo %BAZEL_SH%
C:\msys64\usr\bin\bash.exe
```

**Comment by susinmotion** [comment]
Thanks for bringing this to my attention--I almost certainly messed this up for you with my recent change to sh paths.

My intention was to use the default for cases where we care about the execution platform and to allow the override in cases where we care about the host platform. Would it work to change the default to C:\MSYS64?

**Comment by phst** [comment]
> My intention was to use the default for cases where we care about the execution platform and to allow the override in cases where we care about the host platform.

Hmm, but what about the cases where the platforms are the same (i.e. the default)? Wouldn't it be confusing to respect the override for only one platform?

> Would it work to change the default to C:\MSYS64?

I guess that would solve my specific problem (and would be the right thing in any case since the default directory is C:\MSYS64), but Bazel would still need a way to override the default in case the installation directory differs.

**Comment by phst** [comment]
If you intend to change the semantics of the BAZEL\_SH environment variable, please update https://bazel.build/install/windows?hl=en#bazel_does_not_find_bash_or_bashexe to document how to specify the location of Bash for both host and execution platforms.

**Comment by fmeum** [comment]
@meteorcloudy I think that this should be labeled a release blocker. For example, `rules_jvm_external` uses `genrule` to generate its `@maven` "alias" repo, which means that it currently can't be used on Windows at all.

**Comment by meteorcloudy** [comment]
OK, I'll look into this today
