### ISSUE TITLE
remote strategy doesn't incorporate runfiles as inputs

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#1593]
Consider this repository https://github.com/dfabulich/remote-cache-key-runfiles

The repository has an empty `WORKSPACE` and a trivial `sh_binary`, `cp.sh`, designed to copy its runfile (called `runfile`) to a parameterized destination.

``` bash
cp runfile $1
```

The `runfile` is just a text file containing the number `0`.

The `BUILD` file declares `cp.sh` as a `sh_binary` with the `runfile` in its `data`, and declares a `genrule` called `x` that runs `cp.sh` to generate an output file, `out.txt`.

``` python
sh_binary(
    name='cp',
    srcs=['cp.sh'],
    data=['runfile'],
)

genrule(
    name='x',
    tools=['cp'],
    outs=['out.txt'],
    cmd='$(location cp) $@',
)
```

If you run `bazel build :x && more bazel-genfiles/out.txt` you'll see that it has copied the runfile to `bazel-genfiles/out.txt` and the output is `0`. If you change the runfile to contain the number `1` the `out.txt` file will change when you re-run the build as expected.

Now set the `runfile` back to `0`, launch a Hazelcast server, and run the build like this:

``` bash
bazel clean && bazel build --hazelcast_node=localhost:5701 \
  --genrule_strategy=remote --spawn_strategy=remote :x && more bazel-genfiles/out.txt
```

You'll correctly see the output is `0`. Now change the runfile contents to `1` and run the build again.

Expected: When the runfile contents change, the cache should be invalidated and the output should be regenerated as `1`
Actual: The old cached output is reused and the output remains `0`

<details><summary>

full console output</summary>

```
dfab: /tp/remote-cache-key-runfiles $ bazel clean && bazel build --hazelcast_node=localhost:5701 --genrule_strategy=remote --spawn_strategy=remote :x && more bazel-genfiles/out.txt
.
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
INFO: Found 1 target...
Target //:x up-to-date:
  bazel-genfiles/out.txt
INFO: Elapsed time: 2.304s, Critical Path: 0.07s
0
dfab: /tp/remote-cache-key-runfiles $ echo 1 > runfile
dfab: /tp/remote-cache-key-runfiles $ bazel clean && bazel build --hazelcast_node=localhost:5701 --genrule_strategy=remote --spawn_strategy=remote :x && more bazel-genfiles/out.txt
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
INFO: Found 1 target...
Target //:x up-to-date:
  bazel-genfiles/out.txt
INFO: Elapsed time: 1.622s, Critical Path: 0.02s
0
dfab: /tp/remote-cache-key-runfiles $ bazel version
Build label: 0.3.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 29 09:05:18 2016 (1469783118)
Build timestamp: 1469783118
Build timestamp as int: 1469783118
```

</details>

**Comment by dfabulich** [comment]
Inspecting in a debugger, the runfiles are attached to the action as a "middleman" artifact. `RemoteSpawnStrategy` dutifully calls `ActionInputHelper.expandArtifacts` to expand the runfiles, but the `actionExecutionContext`'s `ArtifactExpanderImpl` has an empty `expandedInputs` map; thus the middleman's inputs are not expanded and are omitted from the cache key.

This, in turn, is happening because `ActionExecutionFunction.checkInputs`, which (I think) is responsible for populating the `expandedInputs`, doesn't know how to handle middleman artifacts. It treats middleman artifacts as ordinary `FileArtifactValue`s.

**Comment by dfabulich** [comment]
Looks like there was an incriminating `TODO` in 0.3.1

https://github.com/bazelbuild/bazel/blob/740b7689ae6d6c5fa7f867f30d7c390473587027/src/main/java/com/google/devtools/build/lib/skyframe/ActionExecutionFunction.java#L578

```java
// TODO(bazel-team): Make sure middleman "virtual" artifact data is properly processed.
```

That `TODO` was eliminated but apparently not addressed in https://github.com/bazelbuild/bazel/commit/ad77f9722e5adb5c997859ea4a0f0f66e7f583bb because this test fails on the latest master, too.

**Comment by dfabulich** [comment]
Wait a minute. We're just computing a hash; we don't need to expand the middlemen. We can use their original value. I'll pull together a PR

**Comment by dfabulich** [comment]
https://bazel-review.googlesource.com/4230

**Comment by meteorcloudy** [comment]
//cc @dslomov Can you review this change?

**Comment by ulfjack** [comment]
Closing because there's a commit that references this bug. Please reopen if this isn't fixed.

**Comment by benjaminp** [comment]
I don't think this is fixed. I can't find the commit that references this bug. Moreover, the latest master still expands the input file artifacts before computing the cumulative input digest and consequently fails to consider the runfiles middleman.

**Comment by ulfjack** [comment]
The commit is linked just above my comment, hash 6734f43.

**Comment by benjaminp** [comment]
That's a fork of Bazel, not the canonical repo.

**Comment by ulfjack** [comment]
Doh!

**Comment by dslomov** [comment]
@ulfjack is this the right category?

**Comment by ulfjack** [comment]
Let me put it under service APIs, which is marginally better.

**Comment by ulfjack** [comment]
I have some changes in flight to prepare for open sourcing the code we're using internally to handle runfiles.
