### ISSUE TITLE
Bazel test for syntaxnet fails inside Docker: cannot download gmock

### ISSUE THREAD

**Issue by kimjunh** [bazelbuild/bazel#1594]
I'm building syntaxnet from inside a docker. It was building fine up until last week, but starting getting this error:

ERROR: /opt/tensorflow/models/syntaxnet/tensorflow/tensorflow/workspace.bzl:84:3: no such package '@gmock_archive//': Error downloading from https://archive.openswitch.net/gmock-1.7.0.zip to /root/.cache/bazel/_bazel_root/5b21cea144c0077ae150bf0330ff61a0/external/gmock_archive: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and referenced by '//external:gtest'.

I'm running bazel test --genrule_strategy=standalone syntaxnet/... util/utf8/...
using protobuf==3.0.0b2, and bazel-0.2.2b

**Comment by meteorcloudy** [comment]
//cc @kchodorow Can you take a look? :)

**Comment by kimjunh** [comment]
Hi, any updates on this?

**Comment by meteorcloudy** [comment]
Can you upgrade bazel to the latest version? I tried with bazel 0.3.1, and it works.

**Comment by kimjunh** [comment]
I did some searching around and I'm actually getting the same error as the one here:
https://github.com/bazelbuild/bazel/issues/587
where jmugan reported:
```
ERROR: /home/jmugan/workspace/models/syntaxnet/tensorflow/tensorflow/workspace.bzl:84:3: no such package '@gmock_archive//': Error downloading from https://archive.openswitch.net/gmock-1.7.0.zip to /home/jmugan/.cache/bazel/_bazel_jmugan/1fd2d6dd907f68126bdeed691eb1f38b/external/gmock_archive: Error downloading https://archive.openswitch.net/gmock-1.7.0.zip to /home/jmugan/.cache/bazel/_bazel_jmugan/1fd2d6dd907f68126bdeed691eb1f38b/external/gmock_archive/gmock-1.7.0.zip: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and referenced by '//external:gtest'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 3.211s
ERROR: Couldn't start the build. Unable to run tests.
```
Has there been any fix for this? I cannot use the proposed solution of manually downloading this file and serving it locally since I'm running everything from a docker

**Comment by kimjunh** [comment]
Also tried the latest version but it doesn't work..

**Comment by hermione521** [comment]
friendly ping @kchodorow

**Comment by kchodorow** [comment]
jGit does some weird stuff with SSL.  We now have git rules in Skylark that use the system git, so if you can run `git clone <whatever>` on that image then those rules should work.  Unfortunately, they are not yet part of a release.  You could either try using Bazel from head or add the following line before your `git_repository` call in WORKSPACE:

```
load('@bazel_tools//tools/build_defs/repo:git_repositories.bzl', 'git_repository')
```

Or put https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/git_repositories.bzl in your local repository tree for now and load it from there (e.g., `load('//myrules:git_repositories.bzl', 'git_repository')`).

**Comment by anthonylake** [comment]
@kchodorow I added the line of code above to the syntaxnet WORKSPACE (I'm assuming that's the right place for it) and received the following error:

`ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file not found. Unable to load package for '@bazel_tools//tools/build_defs/repo:git_repositories.bzl': BUILD file not found on package path.`

Not sure how to run git clone on your Skylark image. any assistance to get this up and running welcome...

**Comment by kchodorow** [comment]
Copy the `git_repositories.bzl` file to your repository and `load()` it from wherever you put it.  So, if you put it next to your WORKSPACE file, you'd say `load('//:git_repositories.bzl', 'git_repository')`.  Create a BUILD file in that directory if one does not exist yet, too (it doesn't have to contain anything, just be present).

**Comment by anthonylake** [comment]
Thanks Kristina :)

**Comment by LStrom929** [comment]
I'm also having the same issue and the above instructions didn't seem to work for me.

**Comment by xuanhua** [comment]
Hi, @kchodorow , when I tried syntaxnet and follow the readme i got the same issue when run below command:
bazel test   --linkopt=-headerpad_max_install_names     syntaxnet/... util/utf8/...

**Comment by kchodorow** [comment]
xuanhua, what is the error you get when you use the workaround mentioned above?

**Comment by kchodorow** [comment]
Feel free to comment if this is still an issue.
