### ISSUE TITLE
py_library, py_binary srcs attribute should be able to accept *.zip

### ISSUE THREAD

**Issue by pcj** [bazelbuild/bazel#1598]
Similar to how the `java_library` rule can accept a `*.srcjar`, I would expect python rules to accept zip files that contain *.py files.  Either it's not supported or I'm doing something wrong.

Would be particularly useful in in concert with source generation tools e.g. protoc.

**Comment by ulfjack** [comment]
It's not supported right now, AFAIK.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
