### ISSUE TITLE
How to generate java code from proto without using protoc

### ISSUE THREAD

**Issue by is03wlei** [bazelbuild/bazel#1599]
Now I use the following commands to build my project:
#!/bin/sh

protoc ./proto/coord.proto --java_out=../../../
bazel build location

Is it possible to let bazel generate proto code automatically?

**Comment by meteorcloudy** [comment]
Should be something like this:
```
java_proto_library(
    name = "foo_java_proto",
    deps = [":foo_proto"],
)

proto_library(
    name = "foo_proto",
    srcs = ["foo.proto"],
)
```
