### ISSUE TITLE
Changing --legacy_whole_archive does not trigger recompilation in Bazel 0.3.0

### ISSUE THREAD

**Issue by ahyangyi** [bazelbuild/bazel#1600]
The flag changes the linking behavior, and could cause bloated libraries when set or libraries with too few symbols when unset. Therefore, when one change the setting, recompilation is probably desired.

The flag value should probably be included in computeKey() in src/main/java/com/google/devtools/build/lib/rules/cpp/CppLinkAction.java, so a change in the flag causes a change in the key.

**Comment by ahyangyi** [comment]
I think adding the following one liner to computeKey() should fix this:

f.addBoolean(getCppConfiguration().legacyWholeArchive());

**Comment by ahyangyi** [comment]
I'm not sure if putting this into configurability is justified: I'm concerned about _correctness_, and correctness issues triggered by changing configurations should still be seen as correctness issues.

**Comment by ulfjack** [comment]
The legacy whole archive method is called before the CppLinkAction is created, and (supposedly) affects the link command line, and the entire link command line is part of the key already, so I don't think adding it to computeKey() will do anything. Unless the command line is identical between the flag and not the flag, in which case caching it is correct.

Can you check if the output files are actually different in the case where you flip the flag? I.e., if you do this 1. bazel build, 2. bazel build --nolegacy_whole_archive (no rebuild), 3. checksum the output file, 4. bazel clean, 5. bazel build --nolegacy_whole_archive, 6. checksum the output file. Can you confirm that the checksums are different? Make sure to use --nostamp in all builds (or at least, not use --stamp).

**Comment by ahyangyi** [comment]
I am convinced by your argument.

The only worrying component might be that the key might use the split command line and the `--whole-archive`s would be moved to the param file and miss the calculation. But I read the v0.4.0 Bazel source code and it seems not to be this case. I'll close this issue since I no longer touch this option and I do not believe it will cause problems in the current iteration and probably all the previous versions too.

I did remember some weird things happening in my earlier experiments. But I can't quickly test it.
