### ISSUE TITLE
ijar zipper creates directories with wrong permission on OSX

### ISSUE THREAD

**Issue by ekuefler** [bazelbuild/bazel#1601]
This issue looks very similar to #630, in a slightly different context.

I'm using ijar zipper to extract a war that contains entries for files, but not for the directories containing those files. This works on my Linux machine whether running in sandbox or standalone. It fails on a coworker's Macbook. When passing "xv" to the zipper to get verbose output, we see output like this on OSX:

```
/Users/[path]/BUILD:3:1: Executing genrule //[path]/editor:editor failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 6.
f 644 BUILD
f 644 editor/Images/Dev/gameboard_blank.png
Cannot create folder /private/var/tmp/_bazel_root/c435e5cceb9c31b5a6ba1d5afff082fd/Master/war/editor/Images: Permission denied
/bin/bash: line 6: 19908 Abort trap: 6           ../external/bazel_tools/tools/zip/zipper/zipper xv ../$file
```

Inspecting the filesystem afterwards, we see that `.../Master/war`, which is created by the genrule, has the correct 755 permissions. However, `.../Master/war/editor`, which should have been created implicitly by the zipper, only has 644 permissions. So the zipper dies when it tries to create `Images` inside of `editor`.

We're on Bazel 0.3.1 but the issue appears to be present in earlier versions. Again, this looks OSX specific, building the same target works fine on Linux.

**Comment by meteorcloudy** [comment]
//cc @damienmg Should we change the permission?

**Comment by damienmg** [comment]
This is definitely a weird bug. We do set the +x flag on all directory we create, it's probably missing somewhere.

**Comment by jin** [comment]
Closing this as obsolete (Bazel 0.3.1), please reopen if this is still affecting you with the latest Bazel versions.
