### ISSUE TITLE
Bazel does not provide the right path to runfiles in c++

### ISSUE THREAD

**Issue by Nov0cx** [bazelbuild/bazel#16013]
### Description of the bug:

Im trying to access runfiles within c++. Im using Bazel 5.2.0. I tried to access like this:
```
std::string error;
std::unique_ptr<Runfiles> runfiles(Runfiles::Create(argv[0], &error));
if (!runfiles) {
    std::cerr << error << std::endl;
    return 1;
}

std::string path = runfiles->Rlocation("Test/Example.tx");
std::cout << "Example.tx: " << path << std::endl;

std::ifstream in(path);

if (!in.is_open())
{
    std::cout << "Example.tx not found" << std::endl;
    return -1;
}
```

(Example.tx is right, just to lazy to change)<br/> The program is finding a path but the path starts from the bazelisk directory and doesn't point to the binary dir.
```
Example.tx: C:\users\nikla\_bazel_nikla\d47dtf2d\execroot\__main__\bazel-out\x64_windows-fastbuild\bin\Test\Test.exe.runfiles/Test/Example.tx
Example.tx not found
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

using "@bazel_tools//tools/cpp/runfiles" as dependency on Windows to access runfiles (using --enable_runfiles).
Running with "bazel run --enable_runfiles //Test:Test"

### Which operating system are you running Bazel on?

Windows 10

### What is the output of `bazel info release`?

release 6.0.0-pre.20220706.4

### Any other information, logs, or outputs that you want to share?

![Path](https://user-images.githubusercontent.com/68678245/182185322-69485b8f-2adb-468d-a114-4a39694f4052.PNG)
Maybe the run command should run this .exe but just an spontaneous thought.

**Comment by fmeum** [comment]
The path you have to pass to `Rlocation` always includes the repository name, even if the runfile is contained in the main repository (aka the workspace). Based on the screenshot, you don't have a workspace name set in `WORKSPACE`, so you have to use the path `__main__/Test/Example.tx` instead.

**Comment by Nov0cx** [comment]
Thank you. It is working now.
Closed.
