### ISSUE TITLE
Bazel Determinsim Test is failing on ci.bazel.io

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#1602]
http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/729/

**Comment by damienmg** [comment]
Diagnostic: the slaves does not have IPv6 loopback and the bind simply fails. The server dies with "bind failed".

**Comment by damienmg** [comment]
(note: for those kind of breakage, once the culprit is identified, rollback first, fix forward after)

**Comment by damienmg** [comment]
Culprit: deee73f24883df51a65248c9409f51531739c498 (confirmed by ssh on the machine and  `./compile.sh && ./ouput/bazel`).
