### ISSUE TITLE
Feature request: allow undeclared test outputs to be collected unzipped

### ISSUE THREAD

**Issue by paullewis** [bazelbuild/bazel#16024]
### Description of the feature request:

I currently have some test runners that output XML reports, which can be collected in `TEST_UNDECLARED_OUTPUTS_DIR`. However these files are always zipped as per https://github.com/bazelbuild/bazel/blob/master/tools/test/test-setup.sh#L409-L419

I was wondering if it would be possible to add a flag/option that bypasses the zipping process and instead puts the files as-is in the `testlogs` dir where the `outputs.zip` file would have been?

### What underlying problem are you trying to solve with this feature?

I don't always want the unspecified test outputs to be zipped to `outputs.zip` as I end up having to unzip them again to do further processing on their contents.

### Which operating system are you running Bazel on?

Mac

### What is the output of `bazel info release`?

release 5.2.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
9c00adcf27f75cb9d606c3d90fc0b0307830b952
```

### Have you found anything relevant by searching the web?

A few items, but all the stuff I found assumes that there will always be an `outputs.zip` (which tallies with how I read the Bazel source).

### Any other information, logs, or outputs that you want to share?

N/A

**Comment by benjaminp** [comment]
#14568

**Comment by paullewis** [comment]
Woo! Thanks!
