### ISSUE TITLE
Incompatible Target Skipping ignores visibility restrictions

### ISSUE THREAD

**Issue by philsc** [bazelbuild/bazel#16044]
### Description of the bug:

With #14096, we're fixing a few usability issues with Incompatible Target Skipping. That is accomplished by moving the code to a much earlier stage of the analysis phase. Unfortunately, that means it runs before visibility is checked.

This is not _inherently_ a problem as it doesn't allow you to bypass visibility restrictions for building code. Compatible targets still obey visibility restrictions. And incompatible targets cannot be built.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create an incompatible target in package `//a`.
```python
# a/BUILD
filegroup(
    name = "private_filegroup",
    visibility = ["//visibility:private"],
    srcs = [...],
)
filegroup(
    name = "private_incompatible_filegroup",
    visibility = ["//visibility:private"],
    target_compatible_with = ["@platforms//:incompatible"],
    srcs = [...],
)
```
Create a target that is either directly incompatible or indirectly incompatible in a different package that depends on one of the private targets.
```python
# b/BUILD
filegroup(
    name = "directly_incompatible",
    srcs = [
        "//a:private_filegroup",
    ],
    target_compatible_with = ["@platforms//:incompatible"],
)
filegroup(
    name = "indirectly_incompatible",
    srcs = [
        "//a:private_incompatible_filegroup",
    ],
)
```
Neither `//b:directly_incompatible` nor `//b:indirectly_incompatible` will generate errors about visibility restrictions.

One possible course of action is to move the visibility checking earlier. https://github.com/bazelbuild/bazel/pull/14096#issuecomment-1189589626

### Which operating system are you running Bazel on?

x86_64 Debian 11

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

This is cbe25324ab but with #14096 merged in.

I'm filing the bug report preemptively.

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
$ git remote get-url upstream; git rev-parse master; git rev-parse HEAD
https://github.com/bazelbuild/bazel
e860453a7be19cc557d02b4edec13819358945fe
21a5fd1b5e091d4fb26ba683bfb3ff31d2f16621
```

### Any other information, logs, or outputs that you want to share?

The hope is to merge #14096 and separately work on this bug.

**Comment by philsc** [comment]
To clarify, I think that a _directly_ incompatible target should be allowed to depend on private targets without error. The point here is that directly incompatible targets don't have their dependencies analysed. This also means avoiding visibility checking.

_Indirectly_ incompatible targets, however, should honor visibility restrictions.

@gregestren , does that sound right to you?

**Comment by gregestren** [comment]
i.e. if target A depends on B and B is both private and incompatible, we'd want a build of A to report a visibility erorr?

**Comment by philsc** [comment]
Yes, that's correct. Does that sound reasonable?

**Comment by gregestren** [comment]
Yep!

**Comment by philsc** [comment]
@gregestren , do you happen to have some advice for me on fixing this?

I think part of the simplest solution is to call [`ConfiguredTargetFactory::convertVisibility()`](https://github.com/bazelbuild/bazel/blob/19b8d24531fb728701a85ec050361d434600b5d2/src/main/java/com/google/devtools/build/lib/analysis/ConfiguredTargetFactory.java#L108) from [`IncompatibleTargetChecker`](https://github.com/bazelbuild/bazel/blob/19b8d24531fb728701a85ec050361d434600b5d2/src/main/java/com/google/devtools/build/lib/analysis/constraints/IncompatibleTargetChecker.java) instead of the [`convertVisibility()` stub](https://github.com/bazelbuild/bazel/blob/19b8d24531fb728701a85ec050361d434600b5d2/src/main/java/com/google/devtools/build/lib/analysis/constraints/IncompatibleTargetChecker.java#L267) that's currently there
Unfortunately I can't figure out how to pass a function as an argument to another function. Everything I find online makes it look tedious or overly complicated.

I considered moving `ConfiguredTargetFactory::convertVisibility()` into a separate `java_library`, but that's proving difficult because it would introduce circular dependencies with `:analysis_cluster`. So I _think_ passing a function pointer around is simplest. But maybe I'm not thinking "java-like" enough.

What's your thought on this? My Java-fu is not good enough to make a decision.

**Comment by gregestren** [comment]
How do you imagine passing the function pointer (i.e. where is the pointer defined and where does it get passed into `IncompatibleTargetChecker`)?   

Would a direct function call from `IncompatibleTargetChecker::convertVisibility()` into `ConfiguredTargetFactory::convertVisibility()` trigger the circular dependency?

**Comment by philsc** [comment]
I am embarrassed. I got `ConfiguredTargetFactory` and `ConfiguredTargetFunction` mixed up in my head. I don't think there's a problem. I should be able to call `ConfiguredTargetFactory::convertVisibility()` from `IncompatibleTargetChecker::convertVisibility()`.

Sorry about the noise.

**Comment by SamB** [comment]
@bazelbuild/triage

This issue is still linked from the docs: <https://bazel.build/extending/platforms#known_issues>

It's not clear if it is fixed to the extent that it can be, or exactly what that means. If the code isn't going to get better, the documentation should probably be clarified a bit, perhaps with an example of how this can happen?
