### ISSUE TITLE
Download via bazelisk fails with 404 on AARCH64

### ISSUE THREAD

**Issue by elfringham** [bazelbuild/bazel#16061]
### Description of the bug:

If using .bazelversion to specify a commit hash, it fails to download the required artifact with a 404 error like this
`$ bazel --version
2022/08/06 09:47:13 Using unreleased version at commit f440f8ec3f63e5d663e1f9d9614f05a39422102a
2022/08/06 09:47:13 Downloading https://storage.googleapis.com/bazel-builds/artifacts/ubuntu1404_arm64/f440f8ec3f63e5d663e1f9d9614f05a39422102a/bazel...
2022/08/06 09:47:13 could not download Bazel: HTTP GET https://storage.googleapis.com/bazel-builds/artifacts/ubuntu1404_arm64/f440f8ec3f63e5d663e1f9d9614f05a39422102a/bazel failed with error 404
`
Assuming that URL used by bazelisk is correct that suggests that bazel is not building or uploading the AARCH64 binary for intermediate builds referenced only by a commit hash. Is that possible? Or is the URL used not correct?

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Setup .bazelversion like this and using bazelisk 1.12.0
`$ cat .bazelversion 
f440f8ec3f63e5d663e1f9d9614f05a39422102a
$ bazel version`

### Which operating system are you running Bazel on?

Ubuntu 18.04

### What is the output of `bazel info release`?

As above, fails to run

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
`$ git remote get-url origin; git rev-parse master; git rev-parse HEAD
https://github.com/tensorflow/tensorflow.git
6479186fba791386a5962f53c1e2d2cbf51c3dc0
b265fdbcce6b9cd960a4c482a5bd487489fbd641
`
```

### Have you found anything relevant by searching the web?

This is linked to bazelisk issue https://github.com/bazelbuild/bazelisk/issues/317 which seems to have been resolved with the 1.12.0 release, at least at the bazelisk end and assuming that the URL being used is correct.

**Comment by elfringham** [comment]
@sgowroji 

On a AARCH64 architecture machine
$ mkdir wksp
$ cd wksp
$ touch WORKSPACE
$ echo f440f8ec3f63e5d663e1f9d9614f05a39422102a>.bazelversion
$ wget https://github.com/bazelbuild/bazelisk/releases/download/v1.12.0/bazelisk-linux-arm64
$ chmod +x bazelisk-linux-arm64
$ ./bazelisk-linux-arm64 version

> 2022/08/08 09:30:31 Using unreleased version at commit f440f8ec3f63e5d663e1f9d9614f05a39422102a
>2022/08/08 09:30:31 Downloading https://storage.googleapis.com/bazel-builds/artifacts/ubuntu1404_arm64/f440f8ec3f63e5d663e1f9d9614f05a39422102a/bazel...
>  2022/08/08 09:30:31 could not download Bazel: HTTP GET https://storage.googleapis.com/bazel-builds/artifacts/ubuntu1404_arm64/f440f8ec3f63e5d663e1f9d9614f05a39422102a/bazel failed with error 404

**Comment by elfringham** [comment]
@sgowroji github keeps turning the git commit hash in the above into a link, which is wrong. You should get this
`$ cat .bazelversion
f440f8ec3f63e5d663e1f9d9614f05a39422102a
`

**Comment by fweikert** [comment]
We stopped supporting Ubuntu 14.04 binaries in June 2019: https://github.com/bazelbuild/bazel/commit/b6d78a5d0e9038fdf21732f6c6b98fc8379e7eb2

**Comment by elfringham** [comment]
@sgowroji What is the reason for the 'more data needed' tag? I do not see a question being asked.

Also FWIW https://storage.googleapis.com/bazel-builds/artifacts/ubuntu1404/f440f8ec3f63e5d663e1f9d9614f05a39422102a/bazel is a valid download link, so while Ubuntu 14.04 may not be a supported platform, for some reason it works as a download link to reach the x86 artifact.

**Comment by fweikert** [comment]
https://github.com/bazelbuild/bazelisk/releases/tag/v1.12.1 contains the fix

**Comment by elfringham** [comment]
Not fixed.
