### ISSUE TITLE
TensorFlow Build issue with Bazel

### ISSUE THREAD

**Issue by ky-xt** [bazelbuild/bazel#1607]
WARNING: /home/ky-xt/tensorflow/util/python/BUILD:11:16: in includes attribute of cc_library rule //util/python:python_headers: 'python_include' resolves to 'util/python/python_include' not in 'third_party'. This will be an error in the future.
ERROR: /home/ky-xt/tensorflow/tensorflow/core/platform/default/build_config/BUILD:56:1: no such package '@gif_archive//': Error downloading from http://ufpr.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz  to /home/ky-xt/.cache/bazel/_bazel_ky-xt/23e265f9b267426aec6293fae27ff1d8/external/gif_archive: Error downloading http://ufpr.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz to /home/ky-xt/.cache/bazel/_bazel_ky-xt/23e265f9b267426aec6293fae27ff1d8/external/gif_archive/giflib-5.1.4.tar.gz: Connection timed out and referenced by '//tensorflow/core/platform/default/build_config:platformlib'. 
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted. 
### Environment info
ubuntu14.04_x64
cuda8.0
cudnn7.5 v5
GTX1070
Bazel 0.3.1

**Comment by hermione521** [comment]
Hi, it looks more like a network problem rather than bazel problem. Do you have any problem downloading that file manually?
