### ISSUE TITLE
java_binary doesn't work with runfiles

### ISSUE THREAD

**Issue by tiechengsu** [bazelbuild/bazel#16084]
### Description of the bug:

A `java_binary` target which depends on `java_library` with data dependency doesn't seem to work. If used with com.google.devtools.build.runfiles.Runfiles to access the runfiles, it gives the following error during [Runfiles runfiles = Runfiles.create()](https://github.com/bazelbuild/bazel/blob/6064a33b15251110421e566edd9ab55a8b426376/tools/java/runfiles/Runfiles.java#L52):

```
java.io.IOException: Cannot find runfiles: $RUNFILES_DIR and $JAVA_RUNFILES are both unset or empty
```

This works when I run bazel test, but doesn't work if I build a `name_deploy.jar` and try to run via `java -jar`. I was able to bypass the error by setting the environment variable manually `export RUNFILES_DIR=`, but the runfiles is not part of the `deploy.jar`, so not sure how this would work on runtime. For context, I need the jar in order to submit to spark.

### Have you found anything relevant by searching the web?

see a similar issue for java_image: https://github.com/bazelbuild/rules_docker/issues/506

**Comment by nresare** [comment]
While I am no expert, it seems your expectations on the semantics of the data attribute does not line up with the features provided by the `data` attribute to the `java_binary` and `java_library` rules. The files referenced by a data attribute will be made available when `bazel run` is invoked, whether the data is added directly on the java_binary target or transitively to a java_library target.

Some light experimentation with the _deploy.jar generation logic seems to indicate that it simply creates a jar for classes and dependencies, without any support for unpacking data content onto a file system and setting up the environment variables such that the `Runfiles` class can locate them.

Maybe adding your data files using the `resources` parameters and making them available in java code using [ClassLoader.getResourceAsStream](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/ClassLoader.html#getResourceAsStream(java.lang.String)) would fit your use case?
