### ISSUE TITLE
"Build completed successfully" reported twice when using `bazel run` and second one isn't filtered with `--ui_event_filters=-INFO`

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/bazel#16085]
### Description of the bug:

When a `bazel run` build completes successfully it reports the success twice in the terminal output:

```
INFO: Build completed successfully, 2 total actions
INFO: Build completed successfully, 2 total actions
```

When  using `--ui_event_filters=-INFO`, it still reports the extra line once:

```
INFO: Build completed successfully, 2 total actions
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

On any project, run `bazel run //a:label` and note the duplicated `Build completed successfully` output.

### Which operating system are you running Bazel on?

macOS 12.4

### What is the output of `bazel info release`?

release-5.2.0

**Comment by brentleyjones** [comment]
Possibly a duplicate of https://github.com/bazelbuild/bazel/issues/12117.

**Comment by haxorz** [comment]
Oh I missed that @meisterT already mailed a PR for fixing the underlying issue. https://github.com/bazelbuild/bazel/pull/16495#issue-1412693170 has his summary of the situation :)

**Comment by brentleyjones** [comment]
@bazel-io flag

**Comment by meisterT** [comment]
Brentley, I am not sure whether we should cherry pick this already into Bazel 6. I would like to see it used a bit both internally (through Blaze) and externally (through rolling releases) before making a call.

**Comment by brentleyjones** [comment]
Sure. Can we leave it flagged for now to keep it on the radar?

**Comment by meteorcloudy** [comment]
Since the original commit was rollbacked, I'll remove the "potential release blocker" label.

**Comment by brentleyjones** [comment]
Should this be reopened then?

**Comment by brentleyjones** [comment]
@bazel-io flag

**Comment by meisterT** [comment]
@brentleyjones this is an incompatible change, so we can't cherry-pick it in 6.1

**Comment by brentleyjones** [comment]
Ohh, sad. Okay.
