### ISSUE TITLE
Annotation processors are incorrectly run multiple times in android_local_test when using Kotlin

### ISSUE THREAD

**Issue by Chang-Eric** [bazelbuild/bazel#16087]
### Description of the bug:

If two annotation processors are triggered on Kotlin sources within the same compilation target and then used as deps within an `android_local_test`, the annotation processors are incorrectly triggered multiple times. This usually results in a failure because the annotation processor hits conflicts trying to write the same file twice.

This occurs with Bazel 5.2.0, but not Bazel 4.2.0. Because this issue requires Kotlin to reproduce, I am using the Kotlin rules from https://github.com/bazelbuild/rules_kotlin. However, only changing the Bazel version from 4.2.0 to 5.2.0 is enough to reproduce this error. I'm using v1.6.0 for the Kotlin rules.

This seems to happen with all sorts of annotation processors. I've tried Dagger, Hilt, AutoValue, and AutoService. It requires two annotation processors to be triggered (i.e. it does not trigger just when the plugins are included with the exported plugins targets being in deps).

For example:

```
android_local_test(
    name = "FooTest",
    srcs = ["FootTest.java"],
    manifest_values = {
        "minSdkVersion": "14",
    },
    deps = [
        ":TestKtLib",
        ...
    ],
)

kt_android_library(
    name = "TestKtLib",
    testonly = True,
    srcs = [
        "TestAutoService.kt",
        "TestAutoValue.kt",
    ],
    deps = [
        # auto service dep
        # auto value dep
    ],
)
```

```kotlin
package foo

import com.google.auto.service.AutoService

@AutoService(String::class)
public class Foo {}
```

```kotlin
package foo

import com.google.auto.value.AutoValue

@AutoValue
abstract class TestAutoValue {
  abstract fun foo(): Long

  companion object {
    fun of(foo: Long): TestAutoValue {
      return AutoValue_TestAutoValue(foo)
    }
  }
}
```

Note that interestingly building `TestKtLib` does not cause the error, just running the test does, which is strange in itself. Running the test in this case however will give an error like the following due to the processors being run twice and both hitting errors from writing the same file twice.

```
warning: /tmp/pwd4144296603390009720/_kotlinc/javatests_foo-TestAutoValue_kt_jvm/temp/stubs/foo/TestAutoValue.java:7: warning: [AutoValueCouldNotWrite] Could not write generated class foo.AutoValue_TestAutoValue: javax.annotation.processing.FilerException: Attempt to recreate a file for type foo.AutoValue_TestAutoValue
public abstract class TestAutoValue {
                ^
error: error: FATAL ERROR: Unable to create META-INF/services/java.lang.String, javax.annotation.processing.FilerException: Attempt to reopen a file for path /tmp/pwd4144296603390009720/_kotlinc/javatests_foo-TestAutoValue_kt_jvm/generated_classes/META-INF/services/java.lang.String
```

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 5.2.0

**Comment by ahumesky** [comment]
@cushon

**Comment by ahumesky** [comment]
The native version of android_local_test has been removed in bazel 8 and migrated to Starlark in https://github.com/bazelbuild/rules_android/, if this is still an issue with the Starlark version, or newer versions of the kotlin rules, please feel free to reopen there.
