### ISSUE TITLE
Bazel allows compilation of cc_library when code uses headers not listed in hdrs

### ISSUE THREAD

**Issue by keddad** [bazelbuild/bazel#16083]
### Description of the bug:

Examples in [documentation](https://bazel.build/reference/be/c-cpp#cc_library) disallow including headers from library you are dependent on if they are not listed under hdrs. (In the example, foo.h can include bar.h, but can't include bar-impl.h since it is not listed in hdrs). However, this appears to not work properly, since BUILD file like this compiles just fine:
```
cc_library(
    name = "bar",
    hdrs = [], # No exported interface
    srcs = [
        "bar.cpp",
        "bar.h",
    ]
)

cc_library(
    name = "foo",
    hdrs = [
        "foo.h",
    ],
    srcs = [
        "foo.cpp", # foo.cpp actually includes bar.h inside itself
    ],
    deps = [
        ":bar",
    ],
)
```

That leads to an undeclared inclusion not caught by Bazel.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I've uploaded a minimal reproducible example here: https://github.com/keddad/bazel_bug
bazel build //main:foo shouldn't work, but it does

### Which operating system are you running Bazel on?

Fedora Linux

### What is the output of `bazel info release`?

release 5.2.0

### Have you found anything relevant by searching the web?

I originally thought that [this issue](https://github.com/bazelbuild/bazel/issues/13513) may be related, since I first found that bug when using includes, but I was able to reproduce the issue without includes.

**Comment by oquenchil** [comment]
This should be caught if you enable the layering_check.
