### ISSUE TITLE
Multiply-defined external repositories act as if the first is in use, but are reported by bazel query as if the last is in use

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/bazel#16097]
### Description of the bug:

Given this WORKSPACE:
```starlark
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "685052b498b6ddfe562ca7a97736741d87916fe536623afb7da2824c0211c369",
    urls = [ 
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.33.0/rules_go-v0.33.0.zip",
    ],  
)

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "ab21448cef298740765f33a7f5acee0607203e4ea321219f2a4c85a6e0fb0a27",
    urls = [ 
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.32.0/rules_go-v0.32.0.zip",
    ],  
)
```

rules_go version 0.33.0 (the first defined) is actually used in the repo.

However, bazel query reports that 0.32.0 (the second defined) is in use:
```console
% bazel query --output=build //external:io_bazel_rules_go
# /Users/dwagnerhall/tmp/bazelplay/WORKSPACE:11:13
http_archive(
  name = "io_bazel_rules_go",
  urls = ["https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.32.0/rules_go-v0.32.0.zip"],
  sha256 = "ab21448cef298740765f33a7f5acee0607203e4ea321219f2a4c85a6e0fb0a27",
)
# Rule io_bazel_rules_go instantiated at (most recent call last):
#   /Users/dwagnerhall/tmp/bazelplay/WORKSPACE:11:13 in <toplevel>
# Rule http_archive defined at (most recent call last):
#   /private/var/tmp/_bazel_dwagnerhall/cf279943ab270dce28569a2931051f04/external/bazel_tools/tools/build_defs/repo/http.bzl:364:31 in <toplevel>
```

This is very misleading.

I would suggest that the correct solution to this problem is to _require_ the use if `maybe` if pulling in multiple definitions of a repo, such that the above WORKSPACE is a hard error. (See https://github.com/bazelbuild/bazel/issues/8433).

I believe this is trivial to implement (behind an incompatible flag), just throwing here https://github.com/bazelbuild/bazel/blob/ecf9ac90f34c72562fc4a3fd4525c660082ef371/src/main/java/com/google/devtools/build/lib/packages/WorkspaceFactoryHelper.java#L182 but that this would currently break all users of bazel, because the default workspace suffixes aren't all behind `maybe`s (in particular `//src/main/java/com/google/devtools/build/lib/bazel/rules:workspace_with_coverage_output_generator` and `//src/main/java/com/google/devtools/build/lib/bazel/rules/cpp:workspace_with_rules_cc`, as well as `tools/cpp/cc_configure.bzl`'s `native.bind(name = "cc_toolchain", ...`.

However, putting all of those targets behind `maybe`s seems reasonable. I'm not sure why they're not already?

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 5.2.0

**Comment by pcjanzen** [comment]
related: https://github.com/bazelbuild/bazel/issues/12947

**Comment by Wyverald** [comment]
As @pcjanzen noted, this is a dupe.
