### ISSUE TITLE
bazel run <docker_target> fails with "dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?"

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/bazel#1609]
Per the [using docker](https://github.com/bazelbuild/bazel/tree/master/tools/build_defs/docker#using) bazel documentation, I should be able to run `bazel run <docker_target>` to update the changed docker layers from my `docker_build()` target. However, doing so results in the following error:

```
time="2016-08-07T21:13:40-07:00" level=fatal msg="Get http:///var/run/docker.sock/v1.18/images/json?all=1: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?" 
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

This is very likely because `/var/run/docker.sock` is [not mounted](https://groups.google.com/forum/m/#!msg/bazel-discuss/9lFLLJ02Ibs/ZPtHDffTCAAJ) in the hermetic sandbox which the `docker` command is run from. Am I doing something wrong here? If so, could the documentation be updated?

For context, running `docker load -i bazel-bin/lathamlabs/ll_docker.tar` directly succeeds.

**Comment by hermione521** [comment]
Hi, it seems your problem is the same with the one in [that thread](https://groups.google.com/forum/m/#!msg/bazel-discuss/9lFLLJ02Ibs/ZPtHDffTCAAJ). Can you try the suggested fix there? Or you can also try with "--sandbox_add_path=/var/run/docker.sock"?

**Comment by hochhaus** [comment]
@hermione521 Thanks. Yes, `--sandbox_add_path=/var/run/docker.sock` in my `~/.bazelrc` file resolves the issue. Could [the documentation](https://github.com/bazelbuild/bazel/tree/master/tools/build_defs/docker#using) be updated to include this workaround if it the commands mentioned in the docs are not expected to work by default?

**Comment by hermione521** [comment]
Actually we have a new implementation of sandbox which fix this problem. The OS X version is already in HEAD (if not reverted soon), the Linux version is also on the way. So I don't think it's necessary to update the doc now. But I will come back when the new sandbox is submitted.

**Comment by hochhaus** [comment]
Thanks for the extra context. This makes sense. I'll look forward to the new sandbox on linux.

**Comment by ulfjack** [comment]
The new sandbox is in now.
