### ISSUE TITLE
`bazel clean --expunge` is sometimes necessary after installing Xcode to fix "clang: error: unknown argument: '-fno-canonical-system-headers'"

### ISSUE THREAD

**Issue by jfirebaugh** [bazelbuild/bazel#16107]
### Description of the bug:

This has been reported in various venues, but I can't find a canonical bug tracking the issue. I just saw a coworker encounter it. The problem seems to be that if you run Bazel before installing Xcode or Xcode command line tools, and then install Xcode, then builds will fail with "clang: error: unknown argument: '-fno-canonical-system-headers'" until you run `bazel clean --expunge`.

* https://groups.google.com/g/bazel-discuss/c/8zaLf60Kikw
* https://github.com/bazelbuild/bazel/issues/3063#issuecomment-331307435
* https://zpjiang.me/2019/03/23/bazel-unknown-argument-fno-canonical-system-headers/

### Which operating system are you running Bazel on?

macOS 12.5

### What is the output of `bazel info release`?

release 5.2.0

**Comment by kshyanashree** [comment]
Hi @jfirebaugh, Could you please provide the complete steps to reproduce the above request? Thanks!

**Comment by fmeum** [comment]
Does `bazel sync --configure` fix this as well or is `bazel clean --expunge` required?

**Comment by sgowroji** [comment]
I'll close the issue. If you still can reproduce it, please reopen.
