### ISSUE TITLE
Support for Ubuntu Focal (20.*)

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/bazel#16104]
### Description of the feature request:

Ubuntu Focal (20.04) came up in April 2020 - https://wiki.ubuntu.com/Releases.  Since most tooling has been supporting it for a while, seems like bazel/bazelisk should support it with packages so apt-get/etc. work instead of having to manually fetch things oneself.

### What underlying problem are you trying to solve with this feature?

Needing protobuf (which just switched the preferred build system to bazel) on a for focal based tests.

### Which operating system are you running Bazel on?

Ubuntu Focal

### What is the output of `bazel info release`?

N/A

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
N/A
```

**Comment by jwnimmer-tri** [comment]
The instructions at https://bazel.build/install/ubuntu#install-on-ubuntu worked just fine[1] for me on Ubuntu 20.  It's not clear to me what the call to action is here.

Could you clarify?

---

[1]
```
curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
sudo apt update
sudo apt install bazel-5.3.1
```
