### ISSUE TITLE
Progress updates become ever more scarce without terminal cursor control

### ISSUE THREAD

**Issue by tom-cnops** [bazelbuild/bazel#16119]
### Description of the bug:

[The docs](https://bazel.build/docs/user-manual#--progress_report_intervaln) for the option `--progress_report_interval=n` read:
`This option sets the reporting frequency, progress will be printed every n seconds.`

But this seems to not work when Bazel can not update the terminal output in place. The delay between progress updates grows linearly as time increases.

I had a quick look at the code and according [to the comments](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/runtime/UiEventHandler.java#L858) this was implemented intentionally. [The commit message](https://github.com/bazelbuild/bazel/commit/fa2917522b99dd28aee757b41b0e087eb6cfcb1d ) also mentions this.

The behavior as described in the docs would be nice for us, as then we can automatically check whether Bazel is still running correctly for some very long-running actions. There also seems no real benefit to increasing the update interval to 10 minutes or more, as we have encountered.

Of course, if I'm missing why this works this way, it would still be useful if the docs could be updated with the behavior for non-overwritable output.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run a test that just sleeps and redirect stderr to a file.

```
cat > sleep.sh << 'EOF'
#!/usr/bin/env bash
sleep 10000
EOF
chmod +x sleep.sh
cat > BUILD.bazel << 'EOF'
sh_test(
    name = "sleep_test",
    size = "enormous",
    srcs = ["sleep.sh"],
)
EOF
touch WORKSPACE
bazel test //:sleep_test --progress_report_interval=2 2> output.txt
```

Initially the progress updates will be written every 2 seconds as requested, but after 40 seconds the delay between them will start increasing noticeably.

### Which operating system are you running Bazel on?

Ubuntu 20.04

### What is the output of `bazel info release`?

release 5.2.0

**Comment by larsrc-google** [comment]
`show_progress_rate_limit` is also involved. The [option description](https://github.com/bazelbuild/bazel/blob/96ed590939798d24848bd6d7fc99a45b6c2932de/src/main/java/com/google/devtools/build/lib/runtime/UiOptions.java#L126) says it's a _minimum_ time. The [docs](https://bazel.build/docs/user-manual#show-progress-rate) say it's a fixed interval.

**Comment by tom-cnops** [comment]
As far as I can see `show_progress_rate_limit` does indeed set a _minimum_ time. The docs could perhaps be formulated a bit better, but they also seem to suggest a minimum to me?

But this seems mostly orthogonal to the issue of the interval increasing if there is no cursor control:

- If `progress_report_interval` is longer than `show_progress_rate_limit`, the latter basically does nothing. 
- If `progress_report_interval` is shorter, then it will initially be overridden by `show_progress_rate_limit`, but the drift still happens and the time between progress messages will increase with ~15s per 100 seconds.

**Comment by meteorcloudy** [comment]
Looks like the performance team has more expertise on this, so reassigning to team-Performance

**Comment by larsrc-google** [comment]
"expertise" is such a strong word. :)

**Comment by tom-cnops** [comment]
Is there anything I could do to make a review easier? I could make myself available for a call or try to write some more background on this change.
