### ISSUE TITLE
Support prepending destination path in http_archive.

### ISSUE THREAD

**Issue by inazarenko** [bazelbuild/bazel#16136]
### Description of the feature request:

Add a parameter (e.g. `add_prefix`) to `http_archive` that would cause the downloaded archive to be unpacked into `repo_path/prefix` directory. 

`download_and_extract` already supports that through its `output` parameter, so the implementation changes are minimal.

### What underlying problem are you trying to solve with this feature?

Many 3-rd party C++ libraries contain files directly in the root of the repository (e.g. [Dear ImGui](https://github.com/ocornut/imgui)).

Projects that depend on such libraries have two options: 

1. Include those headers without any path, e.g. `#include "imgui.h"`
2. Prepend a prefix using `include_prefix` parameter of `cc_library`, allowing project code to do something like `#include "imgui/imgui.h"`

Both are problematic. The first one may lead to clashes when two libraries bring in a header called something like `utils.h`.

The second turns out to be a foot-gun. Since `cc_library` always adds the repository root to include path, the headers can still be found by their file name, i.e. both `#include "imgui.h"` and `#include "imgui/imgui.h"` compile, even though they find different files (with identical contents). That works fine, until they *both* end up in the same compilation unit. At that point, libraries that moved from header guards to `#pragma once` stop compiling due to duplicate definitions. Again, ImGui is a practical example. Basically, `include_prefix` AKA virtual-includes mechanism is unsafe when the headers are directly in the repository root.

Allowing `http_archive` to unpack into a subdirectory of the repository would solve this nicely.

### Which operating system are you running Bazel on?

Ubuntu Linux

### What is the output of `bazel info release`?

5.2.0

**Comment by ismell** [comment]
Which release did this land in?

**Comment by rdesgroppes** [comment]
I was also in the need for it, but is still not available as of Bazel 5.3.2, albeit documented: https://bazel.build/rules/lib/repo/http#http_archive-add_prefix
