### ISSUE TITLE
how to switch to compiling with g++.exe from microsoft cl.exe?

### ISSUE THREAD

**Issue by wangruitang** [bazelbuild/bazel#16133]
hey, there!
when i tried to build the tcmalloc/testing:hello_main target, cl.exe was used and an error: D8021: invalid parameter “/Werror” appeared.
so, i want to switch to g++, instead of cl.
i've installed MinGW-w64, and i could use g++ in terminal or CMD.
i tried reinstall bazel but it does't work. bazel still uses cl.exe.
if anyone knows how to switch, please tell me or just post a link, thanks very much.

**Comment by wangruitang** [comment]
at the begining, g++ had not been installed and i installed bezal.
so cl.exe was used as default compiler, i guess.
then i want g++.exe to be default, so i reinstalled bazel. but it's doesn't work.
i also deleted the environment variable of cl.exe and installed g++(filled in the PATH environment variable)
but bazel still uses cl.exe as default.
that confuses me and i've tried checking out many doc of bazel but don't find what i need.
if you know hot to switch, please tell me.
thanks very much! @sgowroji

**Comment by fmeum** [comment]
You could try `bazel sync --configure`, which let's Bazel repeat the compile search.

**Comment by wangruitang** [comment]
i found this in `windows_cc_toolchain_config.bzl` :
```python
def _use_msvc_toolchain(ctx):
    return ctx.attr.cpu in ["x64_windows", "arm64_windows"] and (ctx.attr.compiler == "msvc-cl" or ctx.attr.compiler == "clang-cl")
```

so i tried to change it to return false, maybe it won't use cl.exe(MSVC) again i guess.
but after i change it, bazel rejected to work and ask me to reinstall bazel.
so i think, bazel use MSVC as default in Windows.
and i don't know how to change it.

i tried, and bazel use cl.exe still.@fmeum

**Comment by meteorcloudy** [comment]
You can try `--compiler=mingw-gcc`, check this test case: https://cs.opensource.google/bazel/bazel/+/master:src/test/py/bazel/bazel_windows_cpp_test.py;l=953?q=%22--compiler%3Dmingw-gcc%22&ss=bazel
