### ISSUE TITLE
Promote experimental_reuse_sandbox_directories to stable

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#16138]
### Description of the feature request:

https://github.com/bazelbuild/bazel/commit/1adb51287f5826ac1a8b469c417780c84ea4b467 introduced this flag.

It has been useful to fix performance problems in actions that have a large number of inputs, such as JavaScript https://github.com/bazelbuild/bazel/issues/8230#issuecomment-1129264658 and C++ with a hermetic sysroot https://github.com/aspect-build/gcc-toolchain/issues/85#issue-1340427935

I don't see any description on that commit of why this flag is thought to be risky. Do we have any criteria to judge the success of the experiment, and a commitment to maintain this feature in the future, such that it can be a non-experimental flag?

### What underlying problem are you trying to solve with this feature?

Avoid most users hitting the same performance issues.

**Comment by larsrc-google** [comment]
I've had no problems with it, so yes, it could reasonably be flipped.

**Comment by alexeagle** [comment]
Thanks @larsrc-google I hope it could be this simple to flip it: https://github.com/bazelbuild/bazel/pull/16490

Would be nice to have for 6.0 since it seems necessary for good rules_js performance, and some users are averse to being experimented on :)
