### ISSUE TITLE
Passing wrapper command to compile command

### ISSUE THREAD

**Issue by ybagarka1** [bazelbuild/bazel#16141]
### Description of the feature request:

Hi, 

For doing the static code analysis we need to pre append a command before the compiling options in bazel. 

### What underlying problem are you trying to solve with this feature?

Unable to pass the wrapper command for compiling the code.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 5.2.0

**Comment by ybagarka1** [comment]
@sgowroji Sure, We are trying to use a tool called Testwell CTC++ for MC/DC reports. I order to get these reports we need to instrument the code using ctcwrap utility. This utility needs to be pre-appended to the existing compiler commands. As per my understanding we don't have such mechanism in bazel to append something before the compiler commands. It would be good to have this feature or a work around. 

Hope so this clears :)

**Comment by meteorcloudy** [comment]
If it's for C++ compiling, you can already setup your own C++ toolchain.

**Comment by ybagarka1** [comment]
@meteorcloudy Yes, it is C++ compiling. Can you please share the links on how can I setup my own tool chain and how would it benefit me ?
