### ISSUE TITLE
Allow one module extension to `load` and use labels from a repo generated by another module extension

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#16143]
Right now, module extensions cannot `load` or otherwise use any labels from a repo generated by another module extension. This would cause a cycle in Skyframe evaluation since any `load`s of a label from an extension-generated repo would request evaluation of all extensions (ModuleExtensionResolutionFunction).

Technically, this isn't strictly necessary: when a `load` from an extension-generated repo is requested, we _could_ identify the exact extension generating that repo by using the revese of the `extensionId -> extensionUniqueName` mapping. For example, the repo named `foo~1.0~my_extension~blah` is definitely generated by the extension `my_extension` defined by `foo@1.0`.

If such a `load` causes a cycle in module extension evaluation (e.g. if extension A loads from repo `foo` generated by extension B, and extension B loads from repo `bar` generated by extension A), we should have a cycle reporter properly report this in human-readable error messages.

**Comment by Wyverald** [comment]
cc @fmeum

**Comment by meteorcloudy** [comment]
Is this one done as https://github.com/bazelbuild/bazel/commit/ae2e930a19f52f604031a4bddafea98efbe7803a landed?

**Comment by Wyverald** [comment]
The change to report the cycles is still pending.
