### ISSUE TITLE
`site/en/build` and `site/en/BUILD` make it hard to develop bazel on case insensitive filesystems.

### ISSUE THREAD

**Issue by uri-canva** [bazelbuild/bazel#16147]
### Description of the bug:

https://github.com/bazelbuild/bazel/commit/3697ca55b04ce308d8afcfeeee6bbea14ff9dbb4 introduced a conflict on case insensitive filesystems, since there is now a directory `site/en/build` which conflicts with the build file `site/en/BUILD`.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Check out https://github.com/bazelbuild/bazel/commit/3697ca55b04ce308d8afcfeeee6bbea14ff9dbb4 on case insensitive filesystem, note git shows `site/en/BUILD` as deleted.

### Which operating system are you running Bazel on?

macOS 12.5.1 21G83

### What is the output of `bazel info release`?

N/A

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
git@github.com:bazelbuild/bazel.git
a2e9f6e401c3fea92a6d515083553ffefdafc24a
a2e9f6e401c3fea92a6d515083553ffefdafc24a
```

### Have you found anything relevant by searching the web?

No.

**Comment by Wyverald** [comment]
@fweikert what do you think we should do here?

also cc @philomathing

**Comment by uri-canva** [comment]
Workaround I'm using in the meantime:
```
echo "site/en/BUILD" >> .git/info/exclude
echo "site/en/build" >> .git/info/exclude
git update-index --assume-unchanged site/en/BUILD
git update-index --assume-unchanged site/en/build
```

**Comment by fmeum** [comment]
Maybe `BUILD` can just be renamed to `BUILD.bazel`?

**Comment by Wyverald** [comment]
This has been fixed (see updates in https://github.com/bazelbuild/bazel/pull/16163)
