### ISSUE TITLE
`prelude_bazel` definitions not included in `bazel info build-language` output

### ISSUE THREAD

**Issue by tpasternak** [bazelbuild/bazel#16150]
### Description of the bug:

`bazelisk info build-language` provides information about rules and attributes that is very useful for external tools (in particular, the official IntelliJ Plugin). Unfortunately it ignores the rules defined in `tools/build_rules/prelude_bazel`.

## Project structure:
```
.
├── BUILD
├── WORKSPACE
└── tools
    └── build_rules
        ├── BUILD
        └── prelude_bazel
```

`//BUILD` content:
```
my_macro_rule(name="abc")
```

`//tools/build_rules/prelude_bazel` content:
```
def _my_macro(ctx):
  output_file = ctx.actions.declare_file(ctx.label.name + ".output")
  ctx.actions.write(output_file, "foo")
  

my_macro_rule = rule(
  implementation = _my_macro,
)
```

Other files empty

## Build language command execution:
```
curl -LO https://github.com/bazelbuild/bazel/raw/630275b657cb64bcfc5cd5603725d7480d2250a4/src/main/protobuf/build.proto
bazel info build-language | protoc --decode=blaze_query.BuildLanguage build.proto
``` 

### Expected output:
Contains 
```
rule {
  name: "my_macro_rule"
  ...
}
```

### Which operating system are you running Bazel on?

Ubuntu 22.04.1

### What is the output of `bazel info release`?

release 5.3.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
N/A
```

**Comment by brandjon** [comment]
This FR would require adding the ability to export Starlark-defined rules as `RuleDefinition` protos, and applying this process to top-level symbols defined in the prelude.

The prelude is only semi-supported to begin with -- we accept its existence but don't encourage its use. It's not clear to me we want to double down on it by blurring the line between it and native-defined symbols.

In any case, it's not something we can prioritize at the moment. @comius FYI.
