### ISSUE TITLE
Release 6.0.0 - December 2022

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#16159]
# Status of Bazel 6.0.0

-   Target baseline: 2022-10-24
-   Expected release date: 2022-12-19
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/38)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

Task list:

-   [x] Pick release baseline
-   [x] Create release candidate
-   [x] Check downstream projects
-   [x] [Create draft release announcement](https://docs.google.com/document/d/1pu2ARPweOCTxPsRR8snoDtkC9R51XWRyBXeiC6Ql5so/edit?usp=sharing)
-   [x] ~Send for review the release announcement PR~
-   [x] Push the release, notify package maintainers
-   [x] Update the documentation
-   [x] Push the blog post
-   [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by limdor** [comment]
It would be nice if this would go it, I guess it got forgotten https://github.com/bazelbuild/bazel/pull/15960

**Comment by alexeagle** [comment]
FYI @fmeum has one more commit to finish with https://github.com/bazelbuild/bazel/issues/10298 and it's quite important to me and @ulfjack that we have symlinks working so that rules_js can support RBE. Will link the remaining PR when we have it.

**Comment by Wyverald** [comment]
Given the number of release blockers present and the unresolved redness in the downstream pipeline, we'll tentatively push out the branch cut date by two weeks (to 2022-09-26).

**Comment by Wyverald** [comment]
There are still many release blockers outstanding (most importantly #16124 and #10298), we're going to push the branch cut date by another two weeks (to 2022-10-10).

**Comment by meteorcloudy** [comment]
We still need more time to finish implementing features (https://github.com/bazelbuild/bazel/issues/16124, https://github.com/bazelbuild/bazel/issues/11261), fix breakages (https://github.com/bazelbuild/bazel/issues/16296) and flip incompatible flags, therefore we are pushing the 6.0 cut by another two weeks (to 2022-10-24).

**Comment by meteorcloudy** [comment]
Bazel 6.0.0rc1 is now available for those that want to try it out. 

You can download it from:
https://releases.bazel.build/6.0.0/rc1/index.html.

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

For any cherry-pick requests, please send PRs to the [release-6.0.0](https://github.com/bazelbuild/bazel/tree/release-6.0.0) branch.

**Comment by UebelAndre** [comment]
Would it be possible to get some resolution for the following PRs to see if we can get that in the 6.0 release?
- https://github.com/bazelbuild/bazel/pull/16430
- https://github.com/bazelbuild/bazel/pull/16540

**Comment by konste** [comment]
Something is wrong with no-jdk Windows binary https://releases.bazel.build/6.0.0/rc1/bazel_nojdk-6.0.0rc1-windows-x86_64.exe
It fails to start with the message `FATAL: Failed to find member 'install_base_key' in zip file 'C:\1\bazel.exe'`

**Comment by meteorcloudy** [comment]
@konste I'll look into the Windows issue

**Comment by fmeum** [comment]
@meteorcloudy rules_jni Windows CI builds running against `last_green` with a local JDK 17 started failing with `Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make java.lang.String(byte[],byte) accessible: module java.base does not "opens java.lang" to unnamed module` in `ParameterFilesWriteAction` on 902a0b5763dddc445f75637c08a1396de8395411 and last succeeded on 50b87c1ec0a5696e46dec7122de130d13112ffdd. This is interesting since that can only happen if [this line](https://cs.opensource.google/bazel/bazel/+/f5711170da68d0d212710283f0e6e2b3254ccc86:src/main/cpp/blaze.cc;l=367) isn't executed, that is, if the embedded JRE isn't found. This seems related to https://github.com/bazelbuild/bazel/issues/16159#issuecomment-1292560531, so it might be that more than just no-jdk builds on Windows are affected.

**Comment by meteorcloudy** [comment]
@konste @fmeum OK, I filed an issue to track this problem.

**Comment by gregmagolan** [comment]
@meteorcloudy This commit would be useful to cherry pick into 6.0 if possible https://github.com/bazelbuild/bazel/commit/4959d34e844714b793b2c6fa05016a9a6eaa7044. Fixes a minor annoyance in downstream rule sets. 🙏

**Comment by meteorcloudy** [comment]
@gregmagolan Can you send a PR to the `release-6.0.0` branch?

**Comment by Kernald** [comment]
@meteorcloudy e7d50fcd46f4383ab2dc61cd0873f262b580158b seems to be required for Android + bzlmod to work fine. Any chance to get it in 6.0.0?

**Comment by Wyverald** [comment]
@Kernald https://github.com/bazelbuild/bazel/pull/16772

**Comment by kshyanashree** [comment]
Bazel 6.0.0rc2 is now available for those that want to try it out.

You can download it from:
https://releases.bazel.build/6.0.0/rc2/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by vogelsgesang** [comment]
Is there already a release announcement draft? The "[Create draft release announcement](https://docs.google.com/document/d/1wDvulLlj4NAlPZamdlEVFORks3YXJonCjyuQMUQEmB0/edit)" seems to not contain anything for Bazel 6, yet

**Comment by purkhusid** [comment]
Any chance that dce6ed777d958d65c7f3d4a2f54f8117778a449e could be cherry picked into 6.0? It fixes #11920 which is a pretty big UX fix

**Comment by kshyanashree** [comment]
> Any chance that [dce6ed7](https://github.com/bazelbuild/bazel/commit/dce6ed777d958d65c7f3d4a2f54f8117778a449e) could be cherry picked into 6.0? It fixes #11920 which is a pretty big UX fix

Thanks @purkhusid for bringing it up! Here It is concluded #16821

**Comment by MiraaChan** [comment]
Hi, is jdk embedded in 6.0.0rc2 ?
 I've tried the  [example](https://github.com/bazelbuild/examples)(cpp-tutorial/stage1), and run `bazel info java-runtime`, 
it will output with the error`FATAL: Could not find system javabase. Ensure JAVA_HOME is set, or javac is on your PATH.`.
Which in release version like 5.1.0 or 5.3.2, it will ouput the version of embedded_tools/jdk as
`OpenJDK Runtime Environment (build 11.0.6+10-LTS) by Azul Systems, Inc` .

**Comment by mattrobmattrob** [comment]
@keertk likely means https://releases.bazel.build/6.0.0/rc3/index.html for testing Bazel 6.0.0rc3.

**Comment by kshyanashree** [comment]
Bazel 6.0.0rc4 is now available for those that want to try it out.

You can download it from:
https://releases.bazel.build/6.0.0/rc4/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by gregmagolan** [comment]
Narrowed down another interesting regression in Bazel 6. I tested as far back as rc1 and it was there: https://github.com/bazelbuild/bazel/issues/16978

**Comment by kshyanashree** [comment]
Bazel 6.0.0rc5 is now available for those that want to try it out.

You can download it from:  
https://releases.bazel.build/6.0.0/rc5/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by kshyanashree** [comment]
6.0.0 is now out!

@petemounce Could you please update Chocolatey? Thanks!

@excitoon [@vbatts](https://github.com/vbatts) Could you please update Scoop & Fedora package with 6.0.0? Thanks!

**Comment by Wyverald** [comment]
Blog post on standby; will publish when 6.0 docs are pushed

**Comment by alexeagle** [comment]
Congratulations! Are you going to make a Docker container? https://github.com/bazelbuild/continuous-integration/issues/1060 has been parked for a long time, another major is another chance :)

**Comment by meteorcloudy** [comment]
The docker container with the latest Bazel version is already published to gcr.io/bazel-public/bazel

**Comment by petemounce** [comment]
Done; ping for [adding to CI](https://github.com/bazelbuild/continuous-integration/issues/1456) cc @meteorcloudy

**Comment by kshyanashree** [comment]
> Done; ping for [adding to CI](https://github.com/bazelbuild/continuous-integration/issues/1456) cc @meteorcloudy

Thanks @petemounce!

**Comment by kshyanashree** [comment]
Bazel 6.1.0rc1 is now available for those that want to try it out.

You can download it from:  https://releases.bazel.build/6.1.0/rc1/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.
