### ISSUE TITLE
No way to JUST generate an instrumented binary

### ISSUE THREAD

**Issue by hemanthsridhar** [bazelbuild/bazel#16169]
### Description of the feature request:

For example,
 In golang we have the ability to generate an instrumented binary without running any tests.
I don’t see any documentation on how to just generate an instrumented binary. So i am assuming that this feature isn’t available

### What underlying problem are you trying to solve with this feature?

The reason this will be helpful is that we can use this binary, deploy and run different tests against it ( functional, unit, system etc ) and get the entire coverage.

### Which operating system are you running Bazel on?

Mac OSX

**Comment by hemanthbsridhar** [comment]
@kshyanashree can someone please help us with this?

**Comment by hemanthsridhar** [comment]
Hi, any updates on this request? It’s been a week. Will be helpful if this is looked into.

**Comment by hemanthsridhar** [comment]
@sgowroji  would Be helpful if I can get an update on this?
Or even an answer would be fine.

**Comment by c-mita** [comment]
`--collect_code_coverage`, combined with an appropriate `--instrumentation_filter` should enable instrumentation, even if you're just doing a build. This allows you to build an instrumented binary.

But there are caveats; Bazel performs a few extra steps for generating coverage reports during test execution. These steps obviously won't happen. For C++ this means you will simply get the output `gcda` files during execution, as well as `gcno` files after the build.

The location and name of these files may depend on the specific version of gcc or llvm version you have, but I think they can be found under `bazel-out/[platform]/bin/[target-path]/_objs`.

**Comment by keertk** [comment]
Closing this since it seems to be resolved/addressed. Thanks!
