### ISSUE TITLE
`cc_binary` ignores `env` attribute

### ISSUE THREAD

**Issue by crugwoben** [bazelbuild/bazel#16167]
### Description of the bug:

It looks like `cc_binary` doesn't take into account the `env` attribute in `6.0.0-pre.20220818.1`. It works correctly with `cc_test` rules, though (I believe [this](https://github.com/bazelbuild/bazel/blob/b671079e6cc3864cdbf6018474c9e417bc062453/src/main/starlark/builtins_bzl/common/cc/cc_test.bzl#L30) is the relevant code). It also works when setting `--experimental_builtins_injection_override=-cc_binary`.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

**`test.cc`**
```cc
#include <iostream>

int main() {
  const char *foo = std::getenv("FOO");
  std::cout << "FOO=" << (foo ? foo : "<NOT_FOUND>") << std::endl;
  return 0;
}
```

**`BUILD`**
```starlark
cc_test(
    name = "test",
    srcs = ["test.cc"],
    env = {"FOO": "bar"},
)

cc_binary(
    name = "bin",
    srcs = ["test.cc"],
    env = {"FOO": "bar"},
)
```

**Experiments**
+ `6.0.0-pre.20220818.1`
```bash
USE_BAZEL_VERSION=6.0.0-pre.20220818.1 bazelisk run :bin
# FOO=<NOT_FOUND>

USE_BAZEL_VERSION=6.0.0-pre.20220818.1 bazelisk run :bin --experimental_builtins_injection_override=-cc_binary
# FOO=bar

USE_BAZEL_VERSION=6.0.0-pre.20220818.1 bazelisk run :test
# FOO=bar
```
+ `5.3.0`
```bash
USE_BAZEL_VERSION=5.3.0 bazelisk run :bin
# FOO=bar

USE_BAZEL_VERSION=5.3.0 bazelisk run :bin --experimental_builtins_injection_override=-cc_binary
# FOO=bar

USE_BAZEL_VERSION=5.3.0 bazelisk run :test
# FOO=bar
```

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

release 6.0.0-pre.20220818.1

**Comment by fmeum** [comment]
@trybka Is `cc_binary` lacking the same handling you added for `cc_test`?

**Comment by crugwoben** [comment]
(@sgowroji I believe this issue is mislabeled. Should probably be "team-Rules-CPP`)

**Comment by trybka** [comment]
> @trybka Is `cc_binary` lacking the same handling you added for `cc_test`?

It appears that it is. Lemme see about adding it.

**Comment by trybka** [comment]
I've got an internal change in review. Hopefully land that by early next week if not sooner.
