### ISSUE TITLE
bazel build remote downloads fail to use proxy settings

### ISSUE THREAD

**Issue by brown** [bazelbuild/bazel#16161]
### Description of the bug:

I run "bazel build" with shell environment variables http_proxy and https_proxy set.  Bazel fails to use the proxy when downloading **some** remote repositories.

I run "bazel sync" and Bazel **does** use the proxy settings to download all remote repos that "bazel build" failed to download.

Here are some representative error messages from a failed "bazel build" run.  I was trying to build target src://bazel_nojdk of bazel checked out at tag 5.3.0 using a downloaded copy of Bazel 5.3.0.

WARNING: Download from https://github.com/bazelbuild/java_tools/releases/download/java_v11.7.1/java_tools-v11.7.1.zip failed: class java.net.SocketException Unexpected end of file from server
ERROR: An error occurred during the fetch of repository 'remote_java_tools':
   Traceback (most recent call last):
        File "/home/reb/.cache/bazel/_bazel_reb/6cebb7564442df2bbd714dd2a1fa6f1c/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://mirror.bazel.build/bazel_java_tools/releases/java/v11.7.1/java_tools-v11.7.1.zip, https://github.com/bazelbuild/java_tools/releases/download/java_v11.7.1/java_tools-v11.7.1.zip] to /home/reb/.cache/bazel/_bazel_reb/6cebb7564442df2bbd714dd2a1fa6f1c/external/remote_java_tools/temp7840296867495722652/java_tools-v11.7.1.zip: Unexpected end of file from server
ERROR: /DEFAULT.WORKSPACE.SUFFIX:392:6: fetching http_archive rule //external:remote_java_tools: Traceback (most recent call last):
        File "/home/reb/.cache/bazel/_bazel_reb/6cebb7564442df2bbd714dd2a1fa6f1c/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://mirror.bazel.build/bazel_java_tools/releases/java/v11.7.1/java_tools-v11.7.1.zip, https://github.com/bazelbuild/java_tools/releases/download/java_v11.7.1/java_tools-v11.7.1.zip] to /home/reb/.cache/bazel/_bazel_reb/6cebb7564442df2bbd714dd2a1fa6f1c/external/remote_java_tools/temp7840296867495722652/java_tools-v11.7.1.zip: Unexpected end of file from server

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I'm not sure how to reproduce this without a proxy.  Bazel appears to use the proxy environment variables for some download execution paths but not others.  I've run the proxy with debug settings that appear to confirm that "bazel build" for certain artifacts is not contacting the proxy.

### Which operating system are you running Bazel on?

Debian Linux 10

### What is the output of `bazel info release`?

I'm running Bazel 5.3.0 downloaded from the releases page.

### Any other information, logs, or outputs that you want to share?

I am running Bazel with a flag needed for communication with the proxy.
--host_jvm_args -Djavax.net.ssl.trustStore=/path/to/java/lib/security/cacerts

Perhaps this flag setting is not being used for some downloads?  I don't think that's likely to be the case, since the proxy did not output any log lines when "bazel build" failed to download remote repos, but it's a possibility.

**Comment by brown** [comment]
The team-ExternalDeps label may be better than team-Remote-Exec for this bug.

**Comment by meteorcloudy** [comment]
@brown Can you provide a minimal reproduce case?

**Comment by brown** [comment]
I described in my bug report how I believe the problem can be reproduced.  Here are some more details.  You need to run Bazel in a configuration where it is unable to download remote repositories without using a proxy.  In this configuration check out tag 5.3.0 of the Bazel source code and perform a build using Bazel version 5.3.0 as follows:

    bazel build --jobs=2 //src:bazel_nojdk //scripts:bash_completion

That build should fail with error messages similar to the ones I reported.  If instead you execute "bazel sync" first, then the build succeeds because the sync command has successfully fetched artifacts that the build command was unable to fetch.  The sync command appears to use the proxy while the build command sometimes does not.

**Comment by brown** [comment]
Today I cannot reproduce the problem using Bazel 5.3.1 compiling tag 5.3.1 of the Bazel source code, so I will close this issue.
