### ISSUE TITLE
"bazel run <docker_target>" fails to tag the image

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/bazel#1616]
After working around https://github.com/bazelbuild/bazel/issues/1609 with `--sandbox_add_path=/var/run/docker.sock` I am seeing an error tagging the docker image. It appears that bazel thinks the image id is `ad890a78c35054564f924dfadbf46dd40891fef51a4f599cebf12c865644e95d` however docker instead uses the image id `6374cbe2f1c6`.

```
ahochhaus@debian:~/ll$ docker images 
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
ahochhaus@debian:~/ll$ bazel run //lathamlabs:jessie
INFO: Found 1 target...
Target //lathamlabs:jessie up-to-date:
  bazel-bin/lathamlabs/jessie-layer.tar
INFO: Elapsed time: 0.106s, Critical Path: 0.00s

INFO: Running command line: bazel-bin/lathamlabs/jessie
Loading ad890a78c35054564f924dfadbf46dd40891fef51a4f599cebf12c865644e95d...
Tagging ad890a78c35054564f924dfadbf46dd40891fef51a4f599cebf12c865644e95d as bazel/lathamlabs:jessie
time="2016-08-08T12:48:51-07:00" level=fatal msg="Error response from daemon: could not find image: no such id: ad890a78c35054564f924dfadbf46dd40891fef51a4f599cebf12c865644e95d" 
ERROR: Non-zero return code '1' from command: Process exited with status 1.
ahochhaus@debian:~/ll$ docker images 
REPOSITORY          TAG                 IMAGE ID            CREATED                VIRTUAL SIZE
<none>              <none>              6374cbe2f1c6        292.471209 years ago   125.1 MB
ahochhaus@debian:~/ll$ docker tag 6374cbe2f1c6 bazel/lathamlabs:jessie
ahochhaus@debian:~/ll$ docker images 
REPOSITORY          TAG                 IMAGE ID            CREATED                VIRTUAL SIZE
bazel/lathamlabs    jessie              6374cbe2f1c6        292.471209 years ago   125.1 MB
ahochhaus@debian:~/ll$ 
```

Note above that manually applying the tag with `docker tag` and the correct image id works as expected. Can I provide any additional information to help debug?

**Comment by hermione521** [comment]
@damienmg can you look at this?

**Comment by damienmg** [comment]
Can you give the version of docker you are using and the version of bazel?

**Comment by hochhaus** [comment]
Thanks @damienmg.

I'm running Debian Jessie with bazel 0.3.1 installed from [bazel_0.3.1-linux-x86_64.deb](https://github.com/bazelbuild/bazel/releases/download/0.3.1/bazel_0.3.1-linux-x86_64.deb).

```
ahochhaus@debian:~$ bazel version
Build label: 0.3.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 29 09:09:52 2016 (1469783392)
Build timestamp: 1469783392
Build timestamp as int: 1469783392
```

I'm using docker 1.6.2 installed from the [Debian jessie-backports repository](https://packages.debian.org/jessie-backports/docker.io).

```
ahochhaus@debian:~$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

Any other information I can provide to be helpful?

**Comment by hochhaus** [comment]
@damienmg Any other information I can provide to help troubleshoot this?

**Comment by damienmg** [comment]
Oh sorry, I missed that bug. /cc @guymers who did the work to make docker_build works with 1.10

It's really weird, can you upload the file `bazel-bin/lathamlabs/jessie`?

**Comment by hochhaus** [comment]
Thanks @damienmg and @guymers. I've attached the file as [jessie.zip](https://github.com/bazelbuild/bazel/files/452559/jessie.zip) to work around github file type limitations.

As a bit more context, in my WORKSPACE file, I've got:

```
new_http_archive(
    name = "docker_debian",
    build_file = "third_party/com_github_tianon_docker_debian/debian.BUILD",
    sha256 = "aadde05fadc556ff0f7b21374500f6389606748d3392a56212d8dd751bef8be8",
    type = "zip",
    url = "https://codeload.github.com/tianon/docker-brew-debian/zip/c2882c541f5bd5cfdd28a505a4e635d42c7fd946",
)
```

And `third_party/com_github_tianon_docker_debian/debian.BUILD` is:

```
load("@bazel_tools//tools/build_defs/docker:docker.bzl", "docker_build")

# Extract .xz files
genrule(
    name = "jessie_tar",
    srcs = ["docker-brew-debian-c2882c541f5bd5cfdd28a505a4e635d42c7fd946/jessie/rootfs.tar.xz"],
    outs = ["jessie_tar.tar"],
    cmd = "cat $< | xzcat >$@",
    visibility = ["//visibility:public"],
)
```

Lastly `lathamlabs/BUILD` contains:

```
docker_build(
    name = "jessie",
    tars = ["@docker_debian//:jessie_tar"],
)

docker_build(
    name = "ll_docker",
    base = ":jessie",
    cmd = "cat ll_bin.js",
    files = [
        ":ll_bin",
    ],
)
```

Please let me know if I can do anything else to help debug further.

**Comment by guymers** [comment]
The problem is caused by https://bazel-review.googlesource.com/#/c/3730/5..6/tools/build_defs/docker/incremental_load.sh.tpl because Docker < 1.8 does not have a format flag.

Changing the default version to 1.5 and using the code you provided, bazel run successfully loaded the container on Ubuntu 14.04 with Docker 1.6.2.

I have put that change into a patch https://bazel-review.googlesource.com/#/c/5771/1/tools/build_defs/docker/incremental_load.sh.tpl

**Comment by hochhaus** [comment]
@guymers Thanks.

**Comment by hochhaus** [comment]
@guymers I noticed that the change you sent didn't get reviewed/merged. Could someone review the code?

**Comment by damienmg** [comment]
The change has been merge but we forgot to close that bug.
