### ISSUE TITLE
Undesired output behavior for cc_test srcs

### ISSUE THREAD

**Issue by jfirebaugh** [bazelbuild/bazel#16174]
### Description of the bug:

This is a UX bug in Bazel's output for `bazel test <target>` when `<target>` is a `cc_test` with `srcs`.

Rather than printing an individual "Compiling foo.cpp" line for each file in `cc_test`s `srcs`, as it does for `cc_library` or `cc_binary`, bazel prints a combined "Testing //:test [2s, 4s]" line. This is misleading because it's not testing at that point, and undesired because it hides useful information about what's happening with the build.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Minimal example: https://github.com/jfirebaugh/bazel_cc_test_output

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 5.3.0

**Comment by kshyanashree** [comment]
Hello @jfirebaugh, Could you please provide the complete steps to reproduce the above request like sample repo? Thanks!
