### ISSUE TITLE
Compiling errors on ARM64 board

### ISSUE THREAD

**Issue by alephman** [bazelbuild/bazel#1617]
Hi, 
I want to port bazel to my arm64 board( debian jessie + arm64 + aarch64 gcc 4.9), but got an error when I tried to compile it:
1)
java -version
Picked up JAVA_TOOL_OPTIONS: -Dgnu.io.rxtx.SerialPorts=/dev/tty96B0
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-1~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

git clone https://github.com/google/protobuf.git

cd protobuf
git checkout d5fb408d
./autogen.sh
./configure --prefix=/usr
make -j 4
sudo make install

cd java
mvn package

git clone https://github.com/bazelbuild/bazel.git
cd bazel
git checkout 0.2.1
sudo cp /usr/bin/protoc third_party/protobuf/protoc-linux-arm32.exe
sudo cp ../protobuf/java/core/target/protobuf-java-3.0.0-beta-2.jar third_party/protobuf/protobuf-java-3.0.0-beta-1.jar

./compile.sh

🍃  Building Bazel with Bazel.
.Unrecognized option: -client
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

2)  If I checkout the master branch of bazel code, and then compile it:

./compile.sh 
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch
gRPC Java plugin not found in

**Comment by hermione521** [comment]
Not sure if we support this.. @damienmg can you look at this?

**Comment by alephman** [comment]
@hermione521 @damienmg  any way to debug this issue?

**Comment by bsilver8192** [comment]
I *think* that flag does nothing on modern amd64 JVMs anyways, so it's safe to just remove it. Try a version after 7f60883548753a8c290ad484cf26605a61edaaea (or you could cherry-pick that if you want to stick with the old version).

A quick grep reveals another instance in src/main/java/com/google/devtools/build/lib/rules/java/DeployArchiveBuilder.java  you might need to remove too.

**Comment by damienmg** [comment]
Brian got the answer right :), closing for now.
