### ISSUE TITLE
Crosstool_tops have to support k8 even if there's no build target needing a host compiler -- intended?

### ISSUE THREAD

**Issue by ahyangyi** [bazelbuild/bazel#1618]
Steps to reproduce:
- Create a crosstool top that does not have support for k8.
- Try to build with that crosstool top from a k8 workstation (which is basically every workstation), and setting some other value for --cpu=.
- Failure

I understand that having a working host compiler is a nice thing to have and in the long run is almost mandatory in any large project. However, won't it be nicer if I can work without a host compiler until I have to do so?

**Comment by ulfjack** [comment]
Bazel currently creates all configurations eagerly, including the host configuration, and it needs a working crosstool top for that. You can set --host_cpu if you want to work around this for now. We're working on some changes to stop doing that, but it's not there yet.

**Comment by ahyangyi** [comment]
Thanks. I understand this is not a blocker in almost all situations. The developers (that is, the users of Bazel) were able to quickly install a toolchain to satisfy Bazel's requirements. Closing it.
