### ISSUE TITLE
Implement `bazel_compatibility` on the `module` directive

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#16183]
See [section in the original design doc](https://docs.google.com/document/d/1moQfNcEIttsk6vYanNKIy3ZuK53hQUFq1b1r0rmsYVg/edit#heading=h.vxty4pj7bwk8).

Also a bit more background in https://github.com/bazelbuild/bazel-skylib/issues/384

**Comment by meteorcloudy** [comment]
Reopen since we have an additional feature to implement for optionally disabling this check
