### ISSUE TITLE
add support for `arm64` architecture for watchOS devices (Xcode 14)

### ISSUE THREAD

**Issue by aleksandergrzyb** [bazelbuild/bazel#16182]
### Description of the feature request:

Xcode 14 adds `arm64` architecture for watchOS devices:

<img width="364" alt="Screenshot 2022-08-29 at 12 33 42" src="https://user-images.githubusercontent.com/3186691/187184897-ab3ed0f8-5001-44ca-94d4-0ea46b251a93.png">

Currently Bazel [only supports `armv7k` and `arm64_32`](https://github.com/bazelbuild/bazel/blob/26509a7b6c684adcab34d00ef765f069f4c8ac13/src/main/java/com/google/devtools/build/lib/rules/apple/ApplePlatform.java#L51-L52).

When you would like to build for watchOS device using `arm64` architecture (`watchOS_arm64`) currently it will get [incorrectly mapped to watchOS simulator](https://github.com/bazelbuild/bazel/blob/26509a7b6c684adcab34d00ef765f069f4c8ac13/src/main/java/com/google/devtools/build/lib/rules/apple/ApplePlatform.java#L141-L142) which already [supports `arm64` architecture](https://github.com/bazelbuild/bazel/blob/26509a7b6c684adcab34d00ef765f069f4c8ac13/src/main/java/com/google/devtools/build/lib/rules/apple/ApplePlatform.java#L49-L50).

I've already submitted PR (#16181) with proposed changes:
* Adds `watchos_arm64` to supported watchOS device architectures.
* Renames `watchos_arm64` to `watchos_sim_arm64` (following the convention as for tvOS and iOS).

### What underlying problem are you trying to solve with this feature?

I would like to build in Xcode 14 for watchOS devices with `arm64` architecture.

### Which operating system are you running Bazel on?

macOS Monterey 12.5.1

### What is the output of `bazel info release`?

release 5.3.0

**Comment by keith** [comment]
This CPU was added in https://github.com/bazelbuild/bazel/commit/ce611646969cfe72ae5e22083708684eae11e478 but I just submitted rules support to cover it https://github.com/bazelbuild/apple_support/pull/289 https://github.com/bazelbuild/rules_apple/pull/2342

if you still see issues with those please file an issue!
