### ISSUE TITLE
Incorrect JUnit parameterized testsuite name in `test.xml`

### ISSUE THREAD

**Issue by swarren12** [bazelbuild/bazel#16191]
### Description of the bug:

When running a parameterised JUnit test via Bazel, the output in `test.xml` incorrectly sets the parameters as the name of the testsuite, rather than the fully-qualified test class. For example:

```
simple-test/test.xml
2:<testsuites>
3:  <testsuite name='com.example.SimpleTest' timestamp='2022-08-30T15:59:25.093Z' hostname='localhost' tests='1' failures='1' errors='0' time='0.015' package='' id='0'>
```
vs
```
parameterised-test/test.xml
2:<testsuites>
3:  <testsuite name='com.example.ParameterisedTest' timestamp='2022-08-30T15:59:25.099Z' hostname='localhost' tests='4' failures='2' errors='0' time='0.015' package='' id='0'>
7:  <testsuite name='[true,true]' timestamp='2022-08-30T15:59:25.099Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.013' package='' id='1'>
12:  <testsuite name='[true,false]' timestamp='2022-08-30T15:59:25.113Z' hostname='localhost' tests='1' failures='1' errors='0' time='0.001' package='' id='2'>
55:  <testsuite name='[false,true]' timestamp='2022-08-30T15:59:25.114Z' hostname='localhost' tests='1' failures='1' errors='0' time='0.0' package='' id='3'>
98:  <testsuite name='[false,false]' timestamp='2022-08-30T15:59:25.114Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='4'
```

In the above snippet, it seems that the class name is included in the file, but it is as an empty `<testsuite>`. It seems as though the parameters are being used as a key for the `<testsuite>` elements, but this is kind of redudant as that information is duplicated on the `<testcase>`s.

**Expected behaviour**: `test.xml` contains a `<testsuite>` using the class name, and then child elements of `<testcase>` that are parameterised.
**Actual behaviour**: `testxml` contains multiple `<testsuite>`s using the parameters, each containing child elements of `<testcase>`.
**Steps to reproduce**: see below

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See [bug.tar.gz](https://github.com/bazelbuild/bazel/files/9454610/bug.tar.gz), or:

1. Create a new Bazel project;
2. Download the latest `bazel` binary;
3. Add an empty `WORKSPACE` file;
4. Download `junit-4.12.jar` and `hamcrest-core-1.3.jar` into the root of the workspace;
5. Create a parameterised test;
6. Create a `BUILD` file for the test;
7. Run the test via Bazel;
8. View the content of the generated `test.xml`.

If you have a tool like `xidel` (anything that supports xPath 2.0) to hand, you can evaluate an xPath of `//testsuite/testcase/concat("suite=", ../@name, ", case=", @name)` to further highlight the problem, e.g.
```
$ ./xidel --xpath2='//testsuite/testcase/concat("suite=", ../@name, ", case=", @name)' bazel-testlogs/simple-test/test.xml
**** Retrieving: bazel-testlogs/simple-test/test.xml ****
**** Processing: bazel-testlogs/simple-test/test.xml ****
suite=com.example.SimpleTest, case=should_be_normal

$ ./xidel --xpath2='//testsuite/testcase/concat("suite=", ../@name, ", case=", @name)' bazel-testlogs/parameterised-test/test.xml
**** Retrieving: bazel-testlogs/parameterised-test/test.xml ****
**** Processing: bazel-testlogs/parameterised-test/test.xml ****
suite=[true,true], case=should_be_parameterised[true,true]
suite=[true,false], case=should_be_parameterised[true,false]
suite=[false,true], case=should_be_parameterised[false,true]
suite=[false,false], case=should_be_parameterised[false,false]
```

I would expect the output of the second run to be something like:
```
suite=com.example.ParameterisedTest, case=should_be_parameterised[true,true]
suite=com.example.ParameterisedTest, case=should_be_parameterised[true,false]
suite=com.example.ParameterisedTest, case=should_be_parameterised[false,true]
suite=com.example.ParameterisedTest, case=should_be_parameterised[false,false]
```

**Script for the above steps**:
```
# Set-up workspace
mkdir bazel-test && cd bazel-test
wget https://github.com/bazelbuild/bazel/releases/download/5.3.0/bazel-5.3.0-linux-x86_64
chmod +x ./bazel-5.3.0-linux-x86_64
touch WORKSPACE

# Download test deps
wget https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.jar
wget https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

# Create the test
mkdir -p src/com/example/ && echo "package com.example;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

import static org.junit.Assert.assertEquals;

@RunWith(Parameterized.class)
public class ParameterisedTest {

    @Parameterized.Parameter(value = 0)
    public boolean a;
    @Parameterized.Parameter(value = 1)
    public boolean b;

    @Test
    public void should_be_parameterised()
    {
        assertEquals(a, b);
    }


    @Parameterized.Parameters(name = \"{0},{1}\")
    public static Object[][] data()
    {
        return new Object[][] {
                new Object[] { true, true, },
                new Object[] { true, false, },
                new Object[] { false, true, },
                new Object[] { false, false, },
        };
    }

}" > src/com/example/ParameterisedTest.java

# Create the BUILD file
echo "java_library(
    name=\"tests-lib\",
    srcs=glob([\"src/**/*.java\"]),
    deps=[\":junit\"]
)

java_test(
    name=\"parameterised-test\",
    size=\"small\",
    test_class=\"com.example.ParameterisedTest\",
    runtime_deps=[\":tests-lib\", \":junit\"]
)

java_import(
    name=\"hamcrest-core\",
    jars=[\"hamcrest-core-1.3.jar\"],
)

java_import(
    name=\"junit\",
    jars=[\"junit-4.12.jar\"],
    deps=[\":hamcrest-core\"],
)" > BUILD

# Run the test
./bazel-5.3.0-linux-x86_64 test //...

# Check the output XML
cat bazel-testlogs/parameterised-test/test.xml
```

### Which operating system are you running Bazel on?

Fedora 34

### What is the output of `bazel info release`?

release 5.3.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
n/a
```

### Have you found anything relevant by searching the web?

No

**Comment by kshyanashree** [comment]
Hello @swarren12 , Could you please provide the complete steps to reproduce the above request like sample repo? Thanks!

**Comment by swarren12** [comment]
Added more detailed steps to reproduce

**Comment by blindpirate** [comment]
Fixed in https://github.com/bazelbuild/bazel/pull/16200

I'm surprised this issue has been there for many years unnoticed.
