### ISSUE TITLE
Bzlmod dependencies are not visible in WORKSPACE file

### ISSUE THREAD

**Issue by cameron-martin** [bazelbuild/bazel#16197]
### Description of the bug:

Repositories loaded via bzlmod are not available in the WORKSPACE file for loading macros from. Although I believe the intention is for bzlmod to fully replace WORKSPACE macros, it is convenient to have a mixture during the transition phase.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

An example is available in this github repo: https://github.com/cameron-martin/bzlmod-workspace-repro

If you run `bazel build //...` in the root module, I get the following error:

```
ERROR: Failed to load Starlark extension '@sub_module//:foo.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
 - @sub_module
This could either mean you have to add the '@sub_module' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
ERROR: cycles detected during target parsing
INFO: Elapsed time: 0.030s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

However, I would expect the `@sub_module` repository to be loaded by bzlmod and available in the WORKSPACE file.

### Which operating system are you running Bazel on?

Ubuntu 20.04

### What is the output of `bazel info release`?

release 5.3.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

I also tried using the latest green, using bazelisk and I still get the same error

```
2022/08/31 20:10:14 Using unreleased version at commit dcc54d5ddb567b7c93af4a7dcd5f77e7b56fdc72
development version
```

### Have you found anything relevant by searching the web?

No, I didn't.

**Comment by Wyverald** [comment]
This is not supported by design. You could write a module extension to call the macro you'd otherwise call.

What is your expected use case?

**Comment by cameron-martin** [comment]
Thanks for clarifying that this is intentional.

My use case is to allow intermediate working states while transitioning a package to using bzlmod, where I can have some dependencies specified in MODULE.bzl, but others specified in the WORKSPACE file.

Specifically, this issue arose when attempting to [add support for bzlmod to rules_rust](https://github.com/bazelbuild/rules_rust/pull/1528). At least to somebody fairly unfamiliar with bzlmod adding this support is non-trivial, and being able to test while only some dependencies are specified via bzlmod and others via the WORKSPACE file is useful.

**Comment by meteorcloudy** [comment]
From WORKSPACE, you can actually see the Bzlmod repos under their canonical repo name, for example
```
load("@@sub_module~override//:foo.bzl", "do_nothing")
```

Maybe this is useful for testing purpose, but you certainly shouldn't depend on it.

Also see the [WORKSPACE.bzlmod](https://docs.google.com/document/d/1JtXIVnXyFZ4bmbiBCr5gsTH4-opZAFf5DMMb-54kES0/edit#heading=h.y054fjub9max) support here.

**Comment by cameron-martin** [comment]
Thanks, this is sufficient for my use case. I'll close this.
