### ISSUE TITLE
Unable to find package for @rules_license//rules:license.bzl

### ISSUE THREAD

**Issue by codeman9** [bazelbuild/bazel#16203]
### Description of the bug:

Starting with commit: https://github.com/bazelbuild/bazel/commit/56d8134fd527510c18f07bd0dfb5bbe8723c68ba#diff-54646449081f58de68930e03663255fa5ff6e34e93743ef66db84b1f146b1639 , and with no other changes to our configuration, we started getting the following error:

```
preloading transitive closure failed: error loading package '@bazel_tools//third_party/zlib': Unable to find
package for @rules_license//rules:license.bzl: The repository '@rules_license' could not be resolved:
Repository '@rules_license' is not defined
```

Adding a dependency in our `WORKSPACE` file to `rules_license`, like so: 

```
http_archive(
     name = "rules_license",
     sha256 = "00ccc0df21312c127ac4b12880ab0f9a26c1cff99442dc6c5a331750360de3c3",
     url = "https://github.com/bazelbuild/rules_license/releases/download/0.0.3/rules_license-0.0.3.tar.gz",
 )
```

resolves the issue. It seems like this dependency should be handled by `bazel` itself?

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I had a hard time paring down all of our dependencies in our project to figure out which one caused it for us. I'm hoping the description above is enough to track something down.

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 6.0.0-pre.20220816.1

**Comment by Wyverald** [comment]
This is fixed in https://github.com/bazelbuild/bazel/commit/4ce63be94362c5c0e62785bead57da9885b556dd. Could you try with the latest rolling release and report back if it's still broken? Thanks!
