### ISSUE TITLE
`native.existing_rules()` may not always show fully qualified labels in `deps`?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [bazelbuild/bazel#16209]
### Description of the bug:

I would assume `native.existing_rules()` would show the same level of content for a rule as expressed in a `BUILD.bazel` file, e.g. you should be able to infer the repository, package, and name that a label refers to.

For some reason, that doesn't seem to be case? (at least in internal codebase, and minimal reproduction example)

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Example in this folder: https://github.com/EricCousineau-TRI/repro/tree/5a4d09bf80f813b322473629415477217fb2651f/bazel/bazel_existing_rules_bug
```sh
git clone https://github.com/EricCousineau-TRI/repro
cd repro/
git checkout 5a4d09bf80f813b322473629415477217fb2651f
cd bazel/bazel_existing_rules_bug/
./repro.sh
```
What I see is a lack of information - the repository for the deps is missing :crying_cat_face: 
```
DEBUG: ${PWD}/analysis.bzl:5:14: workspace_lib: (":a_lib", ":b_lib")
DEBUG: ${PWD}/analysis.bzl:5:14: b_lib: (":a_lib",)
DEBUG: ${PWD}/analysis.bzl:5:14: a_lib: ()
```

What I *expect* to see is some way to infer cross-repository deps
```
DEBUG: ${PWD}/analysis.bzl:5:14: workspace_lib: ("@a//:a_lib", "@b//:b_lib")
DEBUG: ${PWD}/analysis.bzl:5:14: b_lib: ("@a//:a_lib",)
DEBUG: ${PWD}/analysis.bzl:5:14: a_lib: ()
```

### Which operating system are you running Bazel on?

Ubuntu 20.04

### What is the output of `bazel info release`?

release 5.3.0

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
git@github.com:EricCousineau-TRI/repro.git
5a4d09bf80f813b322473629415477217fb2651f
5a4d09bf80f813b322473629415477217fb2651f
```

### Have you found anything relevant by searching the web?

#1195 / #2883 are marginally relevant. I see advice against `native.existing_rules()` there and in documentation, which I understand.
However
- It seems relatively easily to canonicalize / normalize all paths using `native.package_name()` and `native.repository_name()` ?
- ~It also seems relatively easy to sort the results from this so it is not order dependent?~ Ah, definition is order-dependent... I mean, yeah? It's nice to have ability to roll-up for free, and lint tests can be added to ensure auto roll-ups are last.

### Any other information, logs, or outputs that you want to share?

My workflow is to take existing C++ libraries that are normally statically linked, collect the C++ headers + sources + deps, then remap that to relevant information to recompile into shared libraries for use with CPython API extensions via pybind. This is meant to alleviate weird stuff like this:
https://github.com/RobotLocomotion/drake-external-examples/blob/a4c9bda846eaa11708ebec636ee2d76c6c4cecc4/drake_bazel_external/apps/BUILD.bazel#L82-L121

Additional alternatives considered:
- Wrap nominal `cc_library` usages, instrument with additional providers. A bit of overkill IMO, esp. given that information that I want (package-local, basic deps) is already available.
- `aspect()` looks decent, but it can sometimes be a bit hard to munge together with `rule()` implementations - e.g. https://github.com/RobotLocomotion/drake-ros/pull/124#pullrequestreview-1086142049
  - Additionally, it'd be nice if my consuming `rule()` could produce just filegroups for lists of labels to then consume via `cc_library(srcs, hdrs, deps)` and `py_library(deps`); however, it seems like I have to be a bit more judicious on what providers can belong where.

**Comment by EricCousineau-TRI** [comment]
FWIW,  here is downstream motivating use case:
https://github.com/EricCousineau-TRI/repro/tree/cf66d0d27ca9faad922d38f343bd693a43537483/drake_stuff/drake_downstream_pybind

Since filing this issue, I did rejigger it to not rely on `existing_rules()` at all, so it has more "transitive analysis" powers.

That being said, properly working `existing_rules()` would be nice for prototyping!
(and/or maybe a more performant implementation? above stuff is kinda slow)

**Comment by brandjon** [comment]
This sounds inconvenient and definitely not ideal, but I'm not sure what fix would result in the smallest amount of churn for users already dependent on the format of `deps`.

Note that due to repo remapping, if we did include the repo name as part of the stringification of label-valued attributes, that value would still not be portable across repos. I.e., if you retrieved `@foo//...` from the deps in one package, stuffed it in a (string-valued) attribute of your package, and then depended on that string from a target in a different repo, it wouldn't make sense. Admittedly this is a contrived example, but it could manifest in more subtle ways.

I think for this issue to proceed we'd need to examine use cases more carefully. Unfortunately, it's not something we can prioritize at the moment.

**Comment by Wyverald** [comment]
> Note that due to repo remapping, if we did include the repo name as part of the stringification of label-valued attributes, that value would still not be portable across repos. I.e., if you retrieved @foo//... from the deps in one package, stuffed it in a (string-valued) attribute of your package, and then depended on that string from a target in a different repo, it wouldn't make sense. Admittedly this is a contrived example, but it could manifest in more subtle ways.

Just FYI, this bug no longer surfaces if canonical label literals are used (`@@foo//...` doesn't get remapped), although right now this is only true if Bzlmod is enabled.
