### ISSUE TITLE
repository_rule.local doesn't work

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/bazel#16217]
### Description of the bug:

The `local` argument to `repository_rule` doesn't work.

According to documentation,

> Indicate that this rule fetches everything from the local system and should be reevaluated at every fetch.

However, in actuality, operations are cached are not re-evaluated when `local = True`.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

**workspace.bzl**

```bzl
def _my_local_impl(ctx):
  for child in ctx.path("/tmp/bazel-test").readdir():
    print(child)
  ctx.file("BUILD.bazel", content = "")
  result = ctx.execute(["ls", "/tmp/bazel-test"])
  for line in result.stdout.split("\n"):
    if line:
      print(line)

my_local = repository_rule(
  local = True,
  implementation = _my_local_impl,
)
```

**BUILD.bazel**

```bzl
```

**WORKSPACE.bazel**

```bzl
load(":workspace.bzl", "my_local")

my_local(name = "other")
```

Create the directory and start Bazel:

```sh
mkdir /tmp/bazel-test
bazel build '@other//:*'
```

Add a file to the directory, and note that the rule does not see it, neither through `readdir()` nor `execute()`.

```sh
touch /tmp/bazel-test/example
bazel build '@other//:*'
```
```txt
```

If Bazel is restarted, the rule does see the new file /tmp/bazel-test/example.

```sh
bazel shutdown
bazel build '@other//:*'
```

```txt
DEBUG: /home/ubuntu/test/workspace.bzl:3:10: /tmp/bazel-test/example
DEBUG: /home/ubuntu/test/workspace.bzl:8:12: example
```

### Which operating system are you running Bazel on?

Ubuntu 20.04

### What is the output of `bazel info release`?

release 5.3.0

### Any other information, logs, or outputs that you want to share?

Perhaps `local = True` does cause the rule to be technically "re-evaluated" but all the file operations and command executions are cached? If so, that's absolutely useless.

Somehow the built-in rule `local_repository` is able to pick up on changes (it has to create new symlinks for any top-level files). Probably because it's a native rule and doesn't have to deal with Starlark.

**Comment by Wyverald** [comment]
This is working as intended. The documentation for `local` is indeed very confusing -- what does "every fetch" mean? In reality, local repo rules are additionally rerun at every Bazel server restart. "Additionally", as in, it's also rerun when any other trigger for normal repo rules are fired, such as the definition of the repo rule being changed, some label dependency of the rule being changed, etc.

`local_repository` doesn't need to create new symlinks for top-level files. Maybe you're thinking of `new_local_repository`?

**Comment by pauldraper** [comment]
> what does "every fetch" mean?

I assumed it meant on every Bazel invocation.

> In reality, local repo rules are additionally rerun at every Bazel server restart

That is.....the weirdest possible implementation. 99% of the time Bazel server restarts are determined by activity. So....it's refetched when Bazel has been inactive for a long time?

> local_repository doesn't need to create new symlinks for top-level files

Well, it does.

But I suppose `new_local_respository` is a better example.

In any case, it is doing something magic that other repo rules can't.

**Comment by pauldraper** [comment]
So what does `local` do?
