### ISSUE TITLE
 --incompatible_no_support_tools_in_action_inputs=false

### ISSUE THREAD

**Issue by wangligen1995** [bazelbuild/bazel#16211]
### Description of the bug:

**this is my .bazelrc**
build --cxxopt="--std=c++17"
build --copt=-O2
build --incompatible_no_support_tools_in_action_inputs=false
  
but it is error :
  'build' options: --cxxopt=--std=c++17 --copt=-O2 --incompatible_no_support_tools_in_action_inputs=false
ERROR: --incompatible_no_support_tools_in_action_inputs=false :: Unrecognized option: --incompatible_no_support_tools_in_action_inputs=false

### Which operating system are you running Bazel on?

mac

### What is the output of `bazel info release`?

 Inherited 'build' options: --cxxopt=--std=c++17 --copt=-O2 --incompatible_no_support_tools_in_action_inputs=false ERROR: --incompatible_no_support_tools_in_action_inputs=false :: Unrecognized option: --incompatible_no_support_tools_in_action_inputs=false

**Comment by keith** [comment]
This flag has been removed, you need to remove it from your `.bazelrc`

**Comment by wangligen1995** [comment]
But it is OK on my Linux system
<img width="851" alt="image" src="https://user-images.githubusercontent.com/45448722/188257442-a15202ee-aab9-405f-b7d4-b8e14760d705.png">

**Comment by keith** [comment]
You're on a very old bazel there. If you remove the config and run bazel version successfully I imagine you'll see a newer version from after the flag was removed. Either way you should try to update bazel in general since 1.x is long unsupported.
