### ISSUE TITLE
Impossible to apply --no-as-needed to libraries when linking

### ISSUE THREAD

**Issue by aaron-michaux** [bazelbuild/bazel#16222]
### Description of the bug:

The `--no-as-needed` flag exists to force the linker to link in libraries (including shared libraries) even if the linker thinks the library is not needed. (No symbols are used.) This flag needs to appear before the linked library. Like:

```
gcc ... -Wl,--no-as-needed -lmylib1 ...
```

However, adding "--no-as-needed" to the toolchain, or the linkopts of a cc_library, results in the flag always being shunted after the libraries being linked.

```
cc_library(
    name = "mylibrary1",
    srcs = ["libmylib1.so"],
    deps = [":libmylib1.so"],
    linkopts = ["-Wl,--no-as-needed"],
#    alwayslink = True, # NOTE, seems to have no effect on shared libraries
)
```

Results in:

```
gcc ... -lmylib1 -lotherlibrary -lwhatever ...  -Wl,--no-as-needed
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```

cc_binary(
    name = "libmylib1.so",
    srcs = ["lib1.cc"],
    linkshared = True,
)

cc_binary(
    name = "libmylib2.so",
    srcs = ["lib2.cc"],
    linkshared = True,
)

cc_library(
    name = "mylibrary1",
    srcs = ["libmylib1.so"],
    deps = [":libmylib1.so"],
    linkopts = ["-Wl,--no-as-needed"],
    alwayslink = True,
)

cc_library(
    name = "mylibrary2",
    srcs = ["libmylib2.so"],
    deps = [":libmylib2.so"],
    linkopts = ["-Wl,--no-as-needed"],
    alwayslink = True, 
)

cc_test(
    name = "hello_world",
    srcs = [
        "hello_world.cc",
    ],
    deps = [":mylibrary1", ":mylibrary2"],
)
```
Hello World
```
#include <iostream>
#include <string>
#include <cstdlib>
void test_fun1();
void test_fun2();
int main(int, char**) {
  std::cout << std::string{"Hello World!"} << std::endl;
  test_fun1();
  // test_fun2();
  return EXIT_SUCCESS;
}
```

lib1.cc
```
#include <iostream>
void test_fun1() { std::cout << "test-fun 1" << std::endl; }
```

lib2.cc
```
#include <iostream>
void test_fun2() { std::cout << "test-fun 2" << std::endl; }
```

Created my own gcc toolchain. It _shouldn't_ be relevant; however, when using the builtin toolchain rule, I get some mysterious build output including temporary files (e.g `@/tmp/ccHjtK9Q`) with no indication of how they're generated. My own toolchain is producing the command line that I expect, except there is no way to convince bazel to put `--no-as-needed` *before* the libraries that are supposed to be effected.

### Which operating system are you running Bazel on?

Ubuntu 20.04

### What is the output of `bazel info release`?

release 4.2.1

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
fatal: not a git repository

(We don't use git!)
```

### Have you found anything relevant by searching the web?

I asked the question here:
https://stackoverflow.com/questions/73611945/bazel-shared-librarys-and-no-as-needed

**Comment by oquenchil** [comment]
We should fix alwayslink so that it affects shared libraries too and --no-as-needed precedes the files on the command line. But a more important underlying theme is the lack of flexibility in the C++ rules to construct the exact command line that you want, although that'd be a different fix to the one needed here.

**Comment by oquenchil** [comment]
I think the latter problem (lack of flexibility) could be solved here if cc_library had the attribute additional_linker_inputs like [cc_binary](https://cs.opensource.google/bazel/bazel/+/master:src/main/starlark/builtins_bzl/common/cc/cc_binary_attrs.bzl;drc=1746a7958d8c332cae563333d9028b066373e547;l=48), then subtsituting the location to the file in the linkopts attribute like it's done [here](https://cs.opensource.google/bazel/bazel/+/master:src/main/starlark/builtins_bzl/BUILD;drc=203a5061f90598d678c7018e817ce2af4a0e14a3;l=21).

For whatever is placed in the `additional_linker_inputs`, the user is responsible of adding the correct flag to pass to the linker.
