### ISSUE TITLE
Ordering of `genquery` output does not match the output of `bazel query --order_output=full`

### ISSUE THREAD

**Issue by Faqa** [bazelbuild/bazel#16234]
### Description of the bug:

According to docs on the `genquery` rule [here](https://bazel.build/reference/be/general#genquery), output from the rule is supposed to match the order dictated by the flag value `--order_output=full`, and it doesn't seem to be.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/Faqa/bazel_query_ordering

Example repo here. You can compare the output of `//:b_query` to the command `bazel query --notool_deps --order_output=full 'deps(//:b)'` - in the former, the first thing seen is `//:a`, and in the latter, the first target is `//:b`. 

### Which operating system are you running Bazel on?

OSX

### What is the output of `bazel info release`?

release 5.2.0

**Comment by zhengwei143** [comment]
This is working as intended: genquery sorts outputs lexicographically with the following exceptions:
1. If the genquery uses somepath as the top level function (e.g. `somepath(//:b, //:a)`)
2. For the remaining output options where it doesn't quite make sense to: `--output=graph|minrank|maxrank`

This is intended to ensure that genquery produces deterministic results whilst being much more performant (as compared to `--order_output=full`).  This is a bug in the documentation that you've [referenced](https://bazel.build/reference/be/general#genquery).
