### ISSUE TITLE
git_repository strips git repo for patch_cmds

### ISSUE THREAD

**Issue by nvanfleet** [bazelbuild/bazel#16246]
### Description of the bug:

I have a git_repository that I have a patch_cmd that wants to look at the git repo, accessing some tags and the commit hash. However I get an error "fatal: No names found, cannot describe anything." I ended up going into the directory and it seems as if the checkout is there and all the files are except for the git repo, so I can't access the tags and commit hash.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Seems like creating a git_repository, adding a patch_cmd that tries to access the git history of that repository.

### Which operating system are you running Bazel on?

Mac OS

### What is the output of `bazel info release`?

release 6.0.0-pre.20220630.1

**Comment by Wyverald** [comment]
This is working as intended. `git_repository` does not promise to *clone* a repository; it simply checks out a specific commit, applies any patches if necessary, and makes it available as a repo.

**Comment by nvanfleet** [comment]
> This is working as intended. `git_repository` does not promise to _clone_ a repository; it simply checks out a specific commit, applies any patches if necessary, and makes it available as a repo.

Okay wasn't sure if that was the intent or if there was a way to get around that. Thanks
