### ISSUE TITLE
No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type.

### ISSUE THREAD

**Issue by rajhlinux** [bazelbuild/bazel#16248]
### Description of the bug:

```
ERROR: /usr/home/user/.cache/bazel/_bazel_user/dce2e5f5daa25516313b94e75e515765/external/com_google_protobuf/BUILD:515:10: While resolving toolchains for target @com_google_protobuf//:protoc: No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type. Maybe --incompatible_use_cc_configure_from_rules_cc has been flipped and there is no default C++ toolchain added in the WORKSPACE file? See https://github.com/bazelbuild/bazel/issues/10134 for details and migration instructions.

ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: 
```

Pastebin to the error: https://pastebin.com/Cu57nw0b

![screenshot](https://user-images.githubusercontent.com/61344181/189511709-6d7bcc28-4c0d-4810-ab38-e71e43bda768.jpg)

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I followed the installation for c++:

`$ bazel build --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11
`
Then wanted to run c++ hello world example:

`$ bazel run --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/hello_world:hello_world`

I get the error mentioned above.

### Which operating system are you running Bazel on?

FreeBSD 13.1

### What is the output of `bazel info release`?

release 5.3.0

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
https://github.com/google/mediapipe.git
6cdc6443b6a7ed662744e2a2ce2d58d9c83e6d6f
6cdc6443b6a7ed662744e2a2ce2d58d9c83e6d6f
```

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/10134

### Any other information, logs, or outputs that you want to share?

Pastebin to the error: https://pastebin.com/Cu57nw0b

I have an AMD Radeon RX 580 GPU and would like to use MediaPipe using my GPU for the examples.

**Comment by mcramer-billgo** [comment]
@sgowroji I am seeing this same error on bazel 5.3.2
