### ISSUE TITLE
using clang-cl doesn't set the current cpu

### ISSUE THREAD

**Issue by Nov0cx** [bazelbuild/bazel#16249]
### Description of the bug:

I'm using a platform for compiling with clang-cl and setting the cpu to x86_64 but llvm-lib.exe isn't called correctly.
```
ERROR: D:/panthera/pch/BUILD.bazel:3:11: Linking pch/pch.lib failed: (Exit 1): llvm-lib.exe failed: error executing command C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\bin\llvm-lib.exe @bazel-out/x64_windows-dbg/bin/pch/pch.lib-2.params
bazel-out/x64_windows-dbg/bin/pch/_objs/pch/ppch.obj: file machine type x86 conflicts with library machine type x64 (from '/machine:X64' flag)
```
!!! Compiling is working just linking is broken !!!

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

My Platform build file (located in 'bazel/Platforms'):
```
package(default_visibility = ["//:__subpackages__"])

platform(
    name = "cl_x64_windows",
    constraint_values = [
            "@platforms//cpu:x86_64",
            "@platforms//os:windows",
            "@bazel_tools//tools/cpp:msvc",
    ],
)

platform(
    name = "x64_windows-clang-cl",
    constraint_values = [
            "@platforms//cpu:x86_64",
            "@platforms//os:windows",
            "@bazel_tools//tools/cpp:clang-cl",
    ],
)
```

the important part from the workspace:
```
register_execution_platforms(
    "//bazel/Platforms:x64_windows-clang-cl"
)

register_toolchains(
      "@local_config_cc//:cc-toolchain-x64_windows-clang-cl",
)
```

build config:
```
build:clang_cl_win_x64_dbg --enable_runfiles --incompatible_enable_cc_toolchain_resolution --platforms=//bazel/Platforms:x64_windows-clang-cl  --define build_type=debug --compilation_mode=dbg
```

### Which operating system are you running Bazel on?

Windows 10

### What is the output of `bazel info release`?

release 5.3.0

### Have you found anything relevant by searching the web?

following these instructions: https://docs.bazel.build/versions/main/windows.html#build-c-with-clang

### Any other information, logs, or outputs that you want to share?

```
ERROR: D:/panthera/pch/BUILD.bazel:3:11: Linking pch/pch.lib failed: (Exit 1): llvm-lib.exe failed: error executing command C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\bin\llvm-lib.exe @bazel-out/x64_windows-dbg/bin/pch/pch.lib-2.params
bazel-out/x64_windows-dbg/bin/pch/_objs/pch/ppch.obj: file machine type x86 conflicts with library machine type x64 (from '/machine:X64' flag)
```
Visual Studio 2022, 14.33.31629

**Comment by Nov0cx** [comment]
Any changes on this?

**Comment by joliveraortega** [comment]
Hi there! This issue reproduces for me as well (with Visual Studio 2019). Any news about it? I am also interested on a fix for this issue. Thanks.

**Comment by joliveraortega** [comment]
https://github.com/bazelbuild/bazel/issues/12144 made me wonder about the LLVM compiler version installed and the Bazel version used. I use 5.2.0 locally and was using LLVM 12.0.0. I tried LLMV 11.0.0 and the issue is gone.

**Comment by adam-azarchs** [comment]
I was able to solve this problem by setting `BAZEL_LLVM=".../VC/Tools/Llvm/x64"` rather than the auto-detected `BAZEL_LLVM=".../VC/Tools/Llvm"`.
