### ISSUE TITLE
rules_foreign_cc (examples) failing on macOS with Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#16267]
First reported at https://github.com/bazelbuild/bazel/issues/16265
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2615#01831adf-c5cd-4ec5-9802-aaa52dc2a45d
Log:
```
(06:06:56) FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Cannot allocate memory
	at java.base/java.lang.ProcessHandleImpl.getProcessPids0(Native Method)
	at java.base/java.lang.ProcessHandleImpl.descendants(Unknown Source)
	at com.google.devtools.build.lib.worker.WorkerMetricsCollector.getSubprocesses(WorkerMetricsCollector.java:115)
	at com.google.devtools.build.lib.worker.WorkerMetricsCollector.collectMemoryUsageByPid(WorkerMetricsCollector.java:85)
	at com.google.devtools.build.lib.worker.WorkerMetricsCollector.collectMetrics(WorkerMetricsCollector.java:194)
	at com.google.devtools.build.lib.worker.WorkerMetricsCollector.collectMetrics(WorkerMetricsCollector.java:188)
	at com.google.devtools.build.lib.worker.WorkerLifecycleManager.run(WorkerLifecycleManager.java:62)
```

Culprit finder: https://buildkite.com/bazel/culprit-finder/builds/3570#01833508-0419-4ca3-a6c1-19f5b143383a
```
first bad commit is 8e674324d18b715fd09c7fcfedd97be28caa525c
git --no-pager log -n 1 8e674324d18b715fd09c7fcfedd97be28caa525c
commit 8e674324d18b715fd09c7fcfedd97be28caa525c
Author: Googler <wilwell@google.com>
Date:   Wed Aug 24 04:46:58 2022 -0700
 
    Control worker lifecycle via `WorkerLifecycleManager`.
 
    We want to control the abusing of resources (e.g. memory) by workers, so we decided to start with total memory limit for all workers. To control this use the option `experimental_total_worker_memoty_limit_mb`.
 
    To do it we use standard `evict()` function of `GenericKeyedObjectPool`. Indeed we use this call twice: first to collect the idle workers, and for the second time to evict the largest idle workers.
 
    PiperOrigin-RevId: 469693732
    Change-Id: Ib0e51587f6b1744b128678f6e341964820bb1aec
```

**Comment by fmeum** [comment]
Just a thought from the sideline: The rules_foreign_cc build/test suite appears to be running many parallel CMake builds at the time of the crash, which likely take way more RAM than Skyframe accounts for. Is it possible that this has always been close to OOM and this commit just happened to push it over the edge?

**Comment by meteorcloudy** [comment]
Possible, is there a way to limit the number of CMake builds running in parallel? 
/cc worker expert @larsrc-google

**Comment by wilwell** [comment]
1) I also supposed that the problem appears only when we are close to the OOM, but I found it already for the second time, so maybe there is a problem with taking defendants of the process, which is strange. 
2) We have a flag to limit the number of workers for each mnemonic, e.g. `--worker_max_instances=Javac=2`
3) I will guard collecting behind the flag and it should resolve the problem for now.
