### ISSUE TITLE
strict_test_suite

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#16276]
This flag can be flipped pending downstream project migration. See https://github.com/bazelbuild/bazel/pull/15259

**Comment by Wyverald** [comment]
Removing the labels above since they just cause the incompatible flag pipeline to barf, due to `--strict_test_suite` being a `bazel query`-only flag.

**Comment by keith** [comment]
Are there downstreams failing because of this potential flip?

**Comment by Wyverald** [comment]
No, downstream only tests `bazel test`-able targets. We have no way to know if people are using `bazel query` for stuff.
