### ISSUE TITLE
Bug in unix_cc_configure.bzl's _find_linker_path

### ISSUE THREAD

**Issue by dom96** [bazelbuild/bazel#16286]
### Description of the bug:

The [`_find_linker_path`](https://github.com/bazelbuild/bazel/blame/master/tools/cpp/unix_cc_configure.bzl#L175) function attempts to find the linker path by compiling an empty C file with multiple linkers, then reading `clang`'s output to parse out the linker path. One of these is `lld` and is where the issue occurs.

The resulting error on macOS for the project I am compiling is:

```
clang: error: invalid linker name in argument '-fuse-ld=-debugger-tuning=lldb'
```

This appears to be because `_find_linker_path` returns "-debugger-tuning=lldb". See repro for details of how that happens.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have gone ahead and executed the same `clang` command that `_find_linker_path` makes and ran the algorithm in `_find_linker_path` to see what it outputs. The output of the `clang` command as well as a repro script containing the same logic as is currently in `_find_linker_path` is here: https://gist.github.com/dom96/b5ab06d1a1077bcd555aa6204346691e.

Hopefully that shows why there is a bug in `_find_linker_path`.

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 5.3.0-homebrew

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
git@github.com:dom96/capnproto.git
b242153c9c437b6c5e0cb2ea18375f34c91f054c
b242153c9c437b6c5e0cb2ea18375f34c91f054c
```

### Any other information, logs, or outputs that you want to share?

This appears to be a simple fix, however I am not sure what the easiest way for me to test a fix would be. Any tips appreciated.

**Comment by keith** [comment]
Fix is here https://github.com/bazelbuild/bazel/pull/15006, can you test with that branch?

**Comment by keith** [comment]
dup of https://github.com/bazelbuild/bazel/issues/16053
