### ISSUE TITLE
Remote executor used in tests does not support dangling symlinks

### ISSUE THREAD

**Issue by tjgq** [bazelbuild/bazel#16289]
When attempting to remotely execute an action that produces a dangling symlink, the remote executor throws an exception here: https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/remote/UploadManifest.java;l=194;drc=93029d8f1f01be440d8e06cce9585ad912f9169b

This must be fixed before integration tests for dangling symlinks can be added. This may be a blocker for #10298.

**Comment by tjgq** [comment]
The remote execution spec definitely supports actions that create a symlink, but it doesn't say whether the symlink must point to an existing file or directory or not (at least according to my reading). The relevant protocol fields are [`output_file_symlinks`](https://cs.opensource.google/bazel/bazel/+/master:third_party/remoteapis/build/bazel/remote/execution/v2/remote_execution.proto;l=998;drc=29ac010f3754c308de2ff13d3480b870dc7cb7f6), [`output_directory_symlinks`](https://cs.opensource.google/bazel/bazel/+/master:third_party/remoteapis/build/bazel/remote/execution/v2/remote_execution.proto;l=1098;drc=29ac010f3754c308de2ff13d3480b870dc7cb7f6) and [`output_symlinks`](https://cs.opensource.google/bazel/bazel/+/master:third_party/remoteapis/build/bazel/remote/execution/v2/remote_execution.proto;l=1014;drc=29ac010f3754c308de2ff13d3480b870dc7cb7f6). Note that the former two are deprecated in favor of the latter, but Bazel follows the older spec.

The Google Cloud RBE implementation, as far as I can tell, silently fails to report a dangling output symlink. I don't know about other implementations. A minimal repro is at https://github.com/tjgq/bazel-rbe-unresolved-symlink (but note that, even if the RBE implementation worked, the build would still fail on the Bazel side due to #16290).

**Comment by meisterT** [comment]
cc @bazelbuild/remote-execution

**Comment by lberki** [comment]
Oof. For some reason, I thought that the Google's version of remote execution does handle both input and output symlinks. Then there is no alternative than to implement it in our mock backend if we want to test the functionality and we should definitely do so.

**Comment by tjgq** [comment]
I've confirmed with folks who work on Google RBE that output symlinks are not currently implemented (specifically, symlinks that resolve successfully are reported as the regular files or directories that they resolve to, and dangling symlinks are omitted from the outputs entirely). So we do need to test against the mock backend.

**Comment by tjgq** [comment]
This was fixed by 5b46a48.
