### ISSUE TITLE
incompatible_remove_rule_name_parameter

### ISSUE THREAD

**Issue by comius** [bazelbuild/bazel#16301]
There are semantic problems with using `rule(name=..., ...)` instead of using `name = rule(...)` on the top-level, because there can be multiple rules with the same name exported from a single `bzl` file.

We decided to remove `name` parameter from the `rule` call.

Expected timeline:
- Flip the flag with Bazel release 6.0.0
- Remove the flag and implementation from Bazel@HEAD in Q4 2022.

**Comment by fmeum** [comment]
I am relying on a potentially less problematic version of this over at [rules_meta](https://github.com/fmeum/rules_meta/blob/64ef1ae48adecb50d3101a7e7dff6c5c489cdc43/meta/internal/forwarding.bzl#L30). There, I only need a way to declare and use a rule in a macro without having to return it from the macro and force the user to assign it to a global variable. @cpsauer who built something similar.

@comius Would it be possible to retain this capability of declaring "anonymous rules" while getting rid of the semantic problems by having Bazel generate a known unique name? The return value of `rule` could then still be used in the macro that declared it.

**Comment by comius** [comment]
> I am relying on a potentially less problematic version of this over at [rules_meta](https://github.com/fmeum/rules_meta/blob/64ef1ae48adecb50d3101a7e7dff6c5c489cdc43/meta/internal/forwarding.bzl#L30)

Why do you need to set the name? The rule is returned and eventually exported on top level. Unless I'm missing something your wrapper should work without setting the name. And would even probably assign a better name.

> Would it be possible to retain this capability of declaring "anonymous rules" while getting rid of the semantic problems by having Bazel generate a known unique name? 

We deem this too problematic to fix. The "identity" of all rules is not know anymore when bzl file is loaded. The pattern can be used to generate anonymous rules from a `for` loop. Keeping it would necessitate optimising rule classes that are created. Too much trouble.

**Comment by fmeum** [comment]
> Why do you need to set the name? The rule is returned and eventually exported on top level. Unless I'm missing something your wrapper should work without setting the name. And would even probably assign a better name.

The rule is returned, but not eventually exported at the top level: It is only used in a macro calling the rule-generating function and what is ultimately returned to the top level is only the wrapper macro around the rule. 

I can of course work around this by returning the actual rule as an additional return value and have users assign some name to it. This does make the API for this "flagless builds" concept worse, but not by too much.

> > Would it be possible to retain this capability of declaring "anonymous rules" while getting rid of the semantic problems by having Bazel generate a known unique name?
> 
> We deem this too problematic to fix. The "identity" of all rules is not know anymore when bzl file is loaded. The pattern can be used to generate anonymous rules from a `for` loop. Keeping it would necessitate optimising rule classes that are created. Too much trouble.

Agreed, generating rules in a loop would be pathological. If this is too troublesome to keep around, I'm fine with it being removed and will use the workaround.

**Comment by meteorcloudy** [comment]
> Flip the flag with Bazel release 6.0.0

Is it really realistic to flip before the 6.0 cut? Running a incompatible flag test here: https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1267
I think it's going to break every single downstream project, including Bazel itself.

**Comment by comius** [comment]
> I think it's going to break every single downstream project, including Bazel itself.

It shouldn't break anything :)

**Comment by meteorcloudy** [comment]
OK, maybe there is some issue in the implementation? Check this one:
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1267#01835a0c-7d49-4ffd-94cd-c6e0a8ceb390
```
(08:44:21) ERROR: Traceback (most recent call last):
	File "/virtual_builtins_bzl/common/cc/cc_test.bzl", line 141, column 44, in <toplevel>
	File "/virtual_builtins_bzl/common/cc/cc_test.bzl", line 121, column 16, in _make_cc_test
Error in rule: in call to rule(), parameter 'name' is deprecated and will be removed soon. It may be temporarily re-enabled by setting --incompatible_remove_rule_name_parameter=false
(08:44:21) ERROR: Skipping '//:bazel-distfile.zip': error loading package '': Internal error while loading Starlark builtins: Failed to load builtins sources: at /virtual_builtins_bzl/exports.bzl:25:5: at /virtual_builtins_bzl/common/exports.bzl:19:6: initialization of module 'common/cc/cc_test.bzl' (internal) failed
```

**Comment by meteorcloudy** [comment]
All failures I see so far are due to `/virtual_builtins_bzl/common/cc/cc_test.bzl`, but this one seem to be easy to fix?

**Comment by meteorcloudy** [comment]
Bumping to P1 since it's blocking 6.0 release

**Comment by cpsauer** [comment]
[Hopping in since tagged. Thanks @fmeum.]

I'd like to second that there's a valuable, fairly broad use case that'd be hampered by the removal of the ability to have "anonymous" rules. 

#12873 has all the good details, including a short example, but basically this enabled clean, higher order functions wrapping rule creation. In that case, and with fmeum's rules_meta, they were enabling easy rule reuse while adding custom configuration to the build graph. More generally, it seems a bit of a bummer to remove the power of higher order functions around rules.

One quick fix might be to automatically export all otherwise-unexported rules under a hash, eliminating the error case completely? Or, to retain the error for true mistakes, to only do so when it has been captured by a function? Or perhaps there's a more direct way to implement exporting captured rules namelessly?

[@fmeum, am I right that one could work around a removal of the functionality manually by returning both the rule and macro to the user, with the instructions to store the rule in an arbitrarily-named, unused variable? Kinda gross to have to expose the implementation like that through the interface...but at least that might not make it a totally hard blocker for rules_meta.]

[Tagging also @gregestren, since he'd been involved in #12873, has thought about this way more than I have, and might be interested. Maybe there are also other, separate solutions in the works that he'd know about.]

**Comment by fmeum** [comment]
The issue I believe @cpsauer intended to link to is https://github.com/bazelbuild/bazel/issues/14673.

**Comment by cpsauer** [comment]
Yep. Derp. Not sure how I messed that one up, but thank you. Edited the above for clarity.

**Comment by shahms** [comment]
The status quo ante causes serious user confusion and frequent problems where rule authors *do not realize* that the name given to the left hand side of the rule assignment is part of that rule's *public API* no matter how many underscores they put in front of it or how many layers of macros they bury it in. This causes real problems when rule authors refactor their rules and think that the "public" macro is the only relevant aspect.

While this fact exists in the documentation, it is hidden and obscure.

**Comment by shahms** [comment]
Please reconsider.

**Comment by comius** [comment]
The `rule.name` was never designed to support "anonymous rules" or to fix problems how rule classes are defined. I can see how it became useful, but I think those uses still look very 'workaroundish". There is also the problem that the name appears in queries and is used by the tools to recognize the rule - only the name part, not the 'bzl' file the rule is in.

I believe the problems you're stating need be addressed and they need to be addressed holistically.

`rule.name` accidentally solves them, but only partially. This will make the complete solution more difficult. And the implementation has other problems I mentioned before.

Sorry, but it's going away.

**Comment by cpsauer** [comment]
Totally. If anything, "workaroundish" is too kind of a word, and I totally get how name collisions could make reasoning about things hard.

Just figured I'd try to explain the need in case there was a relatively easy way to keep supporting those anonymous rules, while you were in there removing the parameter.

Cheers and thanks for all you do,
Chris

**Comment by meteorcloudy** [comment]
Closed by https://github.com/bazelbuild/bazel/commit/59e51fe625f485dc664928ae0ad93035808779f3
