### ISSUE TITLE
Persistent worker not receiving data

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#1630]
I have a persistent worker written in Python/C++, which reads data via:

```
google::protobuf::io::IstreamInputStream istream(&std::cin);
google::protobuf::io::CodedInputStream input(rawInput); // This blocks
```

(C++ is a native module loaded from Python).
I read that `CodedInputStream` blocks in the constructor until it gets any data (`Refresh` which in turn calls `Next`).

Now, when using this code as a worker it block infinitely.
When I pipe data with `echo` it works fine.

I traced that the Java part does and returns from `flush`, so it "should" send data.
Does anyone have an idea what is going on?

**Comment by hermione521** [comment]
@philwo do you have any idea?

**Comment by abergmeier-dsfishlabs** [comment]
It does work if after `flush` I `close` the OutputStream.

**Comment by abergmeier-dsfishlabs** [comment]
@hermione521 Calling `close` is not a solution just a hack which then breaks the persistant process. Please reopen :smiling_imp:

**Comment by abergmeier-dsfishlabs** [comment]
It might be the `py_binary` in between...

**Comment by abergmeier-dsfishlabs** [comment]
What does work though is to read `sys.stdin.read(2)` from `stub_template`.

**Comment by philwo** [comment]
@abergmeier-dsfishlabs I will look into this further when I'm back from vacation on next Tuesday, but just as an FYI: Bazel workers use the "delimited stream" format for protobufs, e.g. https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/MessageLite#writeDelimitedTo(java.io.OutputStream). Trying to read / write using the undelimited functions won't work.

Unfortunately, C++ protocol buffers do not support delimited form natively. I see you already found this pull request (https://github.com/google/protobuf/pull/710) so you probably handle this in your code, but just wanted to point it out for other readers as well.

I'm not aware of any other worker written in C++ yet, so we don't have a working example to point out. Maybe there's really something weird going on. I'll try to create a C++ version of the ExampleWorker used in my integration tests and put it through them next week.

**Comment by abergmeier-dsfishlabs** [comment]
@philwo Can you perhaps get in touch with the protobuf devs and make them solve this "delimited stream" mess. They defined the protocol de facto but we cannot easily use if from anything other than Java.

**Comment by abergmeier-dsfishlabs** [comment]
Reading through code of `CodedInputStream`, the problem seems that it want to read the buffer of istream (8k by default). When I do `google::protobuf::io::IstreamInputStream istream(&std::cin, 1);` it starts to work (horrible performance incoming).

**Comment by abergmeier-dsfishlabs** [comment]
I do get Exception `com.google.protobuf.InvalidProtocolBufferException: Protocol message tag had invalid wire type.` every once in a while.
Using the Protobuf lib is really no fun.

**Comment by philwo** [comment]
Which data format would you prefer instead of protobufs? I'm open to adding support for others, just had no good reason so far.

**Comment by abergmeier-dsfishlabs** [comment]
I am ok with protobuf but:
- not with its documentation. `IstreamInputStream`, `CodedInputStream` does so much under the hood that is documented nowhere.
- The specific wire format that you chose is only implemented for Java.
- Using stdin and out might be a fine thing for *nix but I fear will pose some problems (encodings, consoles) on Windows.

How about allowing REST or GRPC?

**Comment by abergmeier-dsfishlabs** [comment]
Closing since I will close account.
