### ISSUE TITLE
Regression: RPATH incorrectly set for binaries built in external workspaces

### ISSUE THREAD

**Issue by carlosgalvezp** [bazelbuild/bazel#16307]
### Description of the bug:

Hi,

We have bumped Bazel from 5.1.1 to 5.3.0 and noticed it breaks setting `deps` on `cc_binary`s across workspaces.

For a `cc_binary` defined in external workspace `@foo`, that has a `dep` on a `cc_library`  `@bar//:baz` from the current workspace `@bar`, the RPATH looks like this:

```
5.1.1: $ORIGIN/../../_solib_x86_64/...     OK
5.3.0: $ORIGIN/../bar/_solib_x86_64/...   NOK
```

This leads to the binary from `@foo` not being able to find the libraries it needs at runtime.

Is this intended? Providing a minimal example is not straightforward so I'd like to get some quick initial feedback on whether this is intended or a known/duplicated issue.

### Which operating system are you running Bazel on?

Ubuntu 18.04

### What is the output of `bazel info release`?

release 5.3.0

**Comment by Wyverald** [comment]
@fmeum is this fixed in 5.3.1?

**Comment by fmeum** [comment]
@Wyverald Yes, I assume this is fixed in 5.3.1.

**Comment by Wyverald** [comment]
@carlosgalvezp please try again with 5.3.1 and reopen if the issue persists. Thanks!

**Comment by carlosgalvezp** [comment]
Thanks for the quick answer! Will check the next version.
