### ISSUE TITLE
Merge https://github.com/bazelbuild/bazel/commit/d0ee889fca77e36f2c76ac07de3048055b8428c9 to 4.x

### ISSUE THREAD

**Issue by gn-harness** [bazelbuild/bazel#16304]
### Description of the feature request:

Is it possible to do a minor release for 4.X with https://github.com/bazelbuild/bazel/commit/d0ee889fca77e36f2c76ac07de3048055b8428c9

We are using 4.2.2 in production and starting to hit classpath limits. We started extending class path limits earlier, but now running into "too many arguments" issue.

This commit fixes the underlying issue of handling long classpaths correctly

### What underlying problem are you trying to solve with this feature?

Trying to run our applications having very long class path

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 4.2.2

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
git@github.com:harness/harness-core.git
f89c9dd134112a79cc08ab79efbb69301a708e65
5578c5152a569d0d76d0e16de54dd2ad84532d3e
```

**Comment by Wyverald** [comment]
Since 5.x is the current LTS track, we only provide critical security/incompatibility issues with previous LTS tracks (4.x and older).
