### ISSUE TITLE
Will v6.0 support the newest NDK(r25)?

### ISSUE THREAD

**Issue by holoyangpeng** [bazelbuild/bazel#16316]
### Description of the feature request:

add the support to the newest NDK

### What underlying problem are you trying to solve with this feature?

We are trying to integrate the [Filament](https://github.com/google/filament) and failed because bazel only supports NDK r21 and filament uses r25.

**Comment by keith** [comment]
Newer NDK support is being worked on over here outside of bazel core: https://github.com/bazelbuild/rules_android_ndk

We're using this new rule set successfully today, but please file any issues you find over there! The bazel folks would have to chime in on the actual plan but I would imagine this rule set will be the recommendation going forward

**Comment by ahumesky** [comment]
Yes like keith said, please try https://github.com/bazelbuild/rules_android_ndk, it supports NDK 25

NDK integration going forward will happen there.

(We should update the documentation on NDK integration: https://github.com/bazelbuild/bazel/issues/16396)
