### ISSUE TITLE
Performance regression in `ctx.runfiles`

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#16318]
### Description of the bug:

Since 04e8b638, specifically https://github.com/bazelbuild/bazel/commit/04e8b638023068b637eb159511e755eae2ec0717#diff-1ec6b14026b1888bf81a2f0a262fdb7232a54670b8d3cdaffb0bc99a61ab6e6cR973, `ctx.runfiles` flattens the depset passed as the `transitive_files` parameter. This can cause CPU and memory usage to become quadratic in the number of targets, depending on the particular nature of the dependency tree.

### Which operating system are you running Bazel on?

Any

### What is the output of `bazel info release`?

Bazel@HEAD

**Comment by meteorcloudy** [comment]
/cc @hvadehra @comius 
This is probably something we need to fix for 6.0.0, see https://github.com/bazelbuild/bazel/commit/04e8b638023068b637eb159511e755eae2ec0717#r84588112

**Comment by fmeum** [comment]
Is it really necessary to catch this at analysis time? If the execution time error could be handled gracefully, e.g. as an action failure rather than a server crash, changed to `ctx.runfiles` may not even be necessary.

**Comment by hvadehra** [comment]
Sorry, didn't mean to auto-close this

**Comment by fmeum** [comment]
@hvadehra The linked commit seems to resolve the regression, so closing this was fine.
