### ISSUE TITLE
"command interrupted while computing main repo mapping" without any indication of progress

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#16338]
### Description of the bug:

When I build a Fuchsia example project, Bazel@HEAD hangs for a few minutes while Bazel 5.3.0 provides reasonable progress reporting. 

`--profile` indicates that it's repository fetching that's happening during the hang. 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Following the instructions here while using a Bazel built from HEAD:

https://fuchsia.googlesource.com/sdk-samples/fortune-teller/

essentially:

```
git clone https://fuchsia.googlesource.com/sdk-samples/fortune-teller
cd fortune-teller
git submodule update --recursive --init
bazel build @fuchsia_sdk//:fuchsia_toolchain_sdk
```

Then the console output is:
```
>> bazel build @fuchsia_sdk//:fuchsia_toolchain_sdk
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
# Hangs for >1 minute
^C
Bazel caught interrupt signal; shutting down.

ERROR: command interrupted while computing main repo mapping
```

This is in constrast with Bazel 5.3.0, which tells me on the console that it's currently busy fetching repositories.

### Which operating system are you running Bazel on?

Linux

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

From commit 8a53266b6e8011691ebb2683127f12851e3a8245 .

**Comment by meteorcloudy** [comment]
Why is this `area-Bzlmod`?

**Comment by lberki** [comment]
AFAIU bzlmod is the only significant user of repo mapping, so mainly by association

**Comment by lberki** [comment]
I'm glad my crystal ball worked well this time :)
