### ISSUE TITLE
Input prefetcher handles partial tree artifacts and nested artifacts incorrectly

### ISSUE THREAD

**Issue by tjgq** [bazelbuild/bazel#16333]
It's possible for artifacts to nest (i.e., to have a declare_file or declare_directory that descends from another declare_directory). If two nested inputs are presented to the input prefetcher, the common files will be downloaded twice and race against each other, potentially corrupting the input tree.

https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/remote/AbstractActionInputPrefetcher.java;l=289;drc=05b97393ff7604f237d9d31bd63714f27fbe83f2
https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/remote/AbstractActionInputPrefetcher.java;l=230;drc=05b97393ff7604f237d9d31bd63714f27fbe83f2

**Comment by tjgq** [comment]
In addition, it's possible for an action to consume only one of the files in a tree artifact (see `SpawnActionTemplate`), in which case the prefetcher will try to fetch the entire tree artifact; this currently fails because the metadata for the entire tree artifact isn't present (see https://github.com/bazelbuild/bazel/issues/16987).

**Comment by tjgq** [comment]
Reopening because https://github.com/bazelbuild/bazel/commit/25ba76c1b8d420ebae43c1f59890ae46153c2240 was just a workaround, and we have yet to fix it properly.

**Comment by tjgq** [comment]
Yes, but I'm not sure 6.1.0 is still accepting cherry-picks. If we decide to do an rc3, I'll cherry-pick it there. Otherwise, it will have to go into 6.2.0.

**Comment by kshyanashree** [comment]
@bazel-io fork 6.2.0
