### ISSUE TITLE
[Mirror] https://github.com/protocolbuffers/upb/archive/e5f26018368b11aab672e8e8bb76513f3620c579.tar.gz

### ISSUE THREAD

**Issue by limdor** [bazelbuild/bazel#16344]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/protocolbuffers/upb/archive/e5f26018368b11aab672e8e8bb76513f3620c579.tar.gz

**Comment by limdor** [comment]
Needed for https://github.com/bazelbuild/bazel/pull/16343

**Comment by sgowroji** [comment]
Please find the Updated artifact. 
https://mirror.bazel.build/github.com/protocolbuffers/upb/archive/e5f26018368b11aab672e8e8bb76513f3620c579.tar.gz
