### ISSUE TITLE
tools/jdk/TestRunner_deploy.jar pollutes the classpath for java_test targets

### ISSUE THREAD

**Issue by jleyba** [bazelbuild/bazel#1634]
tools/jdk/TestRunner_deploy.jar includes guava 19.0, which creates conflicts for any workspaces that attempt to use a different version of guava (i.e. 20.0-SNAPSHOT).

I've put together a sample project that can reproduce the problem with bazel 0.3.1:

https://github.com/jleyba/bazel-classpath

**Comment by hermione521** [comment]
I think @iirina is working on this.

**Comment by ulfjack** [comment]
Let's consider this a dupe of #1150.
