### ISSUE TITLE
[Mirror] https://github.com/protocolbuffers/upb/archive/a5477045acaa34586420942098f5fecd3570f577.tar.gz

### ISSUE THREAD

**Issue by limdor** [bazelbuild/bazel#16348]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/protocolbuffers/upb/archive/a5477045acaa34586420942098f5fecd3570f577.tar.gz

**Comment by limdor** [comment]
Sorry @sgowroji, I put the wrong link in https://github.com/bazelbuild/bazel/issues/16344, indeed I put the link of the artifact that was already in the bazel mirror.

**Comment by sgowroji** [comment]
Please find the updated mirror link https://mirror.bazel.build/github.com/protocolbuffers/upb/archive/a5477045acaa34586420942098f5fecd3570f577.tar.gz
