### ISSUE TITLE
Building a CMake project using Bazel

### ISSUE THREAD

**Issue by mikejack07** [bazelbuild/bazel#16347]
I am trying to build a CMake project using Bazel. The folder structure looks like this:

BazelCmake

1. WORKSPACE.bazel

2. Source

3. Build

BazelCmake is the parent folder and Source subfolder contains the source files. I created the Build folder where i will be putting the build files. The Source folder looks like this:

Source

1. BUILD.bazel

2. CMakeLists.txt

3. tutorial.cpp

The contents of the workspace file are:

```
workspace(name = "rules_foreign_cc_usage_example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Rule repository, note that it's recommended to use a pinned commit to a released version of the rules
http_archive(
   name = "rules_foreign_cc",
   sha256 = "c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e",
   strip_prefix = "rules_foreign_cc-0.1.0",
   url = "https://github.com/bazelbuild/rules_foreign_cc/archive/0.1.0.zip",
)

load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")

# This sets up some common toolchains for building targets. For more details, please see
# https://github.com/bazelbuild/rules_foreign_cc/tree/main/docs#rules_foreign_cc_dependencies
rules_foreign_cc_dependencies()

_ALL_CONTENT = """\
filegroup(
    name = "all_srcs",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)
"""

# pcre source code repository
http_archive(
    name = "pcre",
    build_file_content = _ALL_CONTENT,
    strip_prefix = "pcre-8.43",
    urls = [
        "https://mirror.bazel.build/ftp.pcre.org/pub/pcre/pcre-8.43.tar.gz",
        "https://ftp.pcre.org/pub/pcre/pcre-8.43.tar.gz",
    ],
    sha256 = "0b8e7465dc5e98c757cc3650a20a7843ee4c3edf50aaf60bb33fd879690d2c73",
)
```
This is the same as directed in the [official documentation](https://bazelbuild.github.io/rules_foreign_cc/main/cmake.html).

Apart from that, the Build.bazel file inside the Source folder looks like this:

```
load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake")

cmake(
    name = "pcre",
    cache_entries = {
        "CMAKE_C_FLAGS": "-fPIC",
    },
    lib_source = "@pcre//:all_srcs",
    out_static_libs = ["libpcre.a"], )
```
This is also the same as given in the [official documentation](https://bazelbuild.github.io/rules_foreign_cc/main/cmake.html).

The contents of tutorial.cpp are:

```
#include <cmath>
#include <cstdlib>
#include <iostream>
#include <string>
using namespace std;

int main()
{
 cout << "Hello "<<endl;
  return 0;
}
```
The contents of CMakeLists.txt are:

```
cmake_minimum_required(VERSION 3.23.2)

project(Tutorial VERSION 1.0)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED True)

add_executable(Tutorial tutorial.cxx)

target_include_directories(Tutorial PUBLIC
                           "${PROJECT_BINARY_DIR}"
                           )
```
Now, when I open command prompt, enter the Build directory and type:

` bazel build //:pcre`

from there, I get the error:

```
Starting local Bazel server and connecting to it...
ERROR: error loading package '': Label '@rules_foreign_cc//foreign_cc:repositories.bzl' is invalid because 'foreign_cc' is not a package; perhaps you meant to put the colon here: '@rules_foreign_cc//:foreign_cc/repositories.bzl'?
INFO: Elapsed time: 6.982s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```
I am very much new to Bazel and want to build CMake projects using Bazel. How do I resolve the error and build CMake projects using bazel?

Thanks.

**Comment by sgowroji** [comment]
Hello @mikejack07, Can you share a reproducible code to test and verify. Thanks!

**Comment by mikejack07** [comment]
The above mentioned codes are all I have. I am trying out Bazel and trying to integrating Bazel to build Cmake project. To get my hands on how it works, I created this demo project as mentioned above. I have given all the codes above.

**Comment by sgowroji** [comment]
@mikejack07, May be you should reach here https://github.com/bazelbuild/rules_foreign_cc for more help. Thanks!

**Comment by mikejack07** [comment]
Here is the link to the discussion for anyone facing the same problem:
https://github.com/bazelbuild/rules_foreign_cc/issues/969
