### ISSUE TITLE
incompatible_package_group_has_public_syntax

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#16355]
**Description:** This flag adds the new string constants `"public"` and `"private"` as allowed values for `package_group`'s `packages` attribute. `"public"` admits every package into the package group, which is the same behavior as `"//..."` prior to `--incompatible_fix_package_group_reporoot_syntax` (#16323). `"private"` admits no packages and has the same effect as omitting it from the list; it is provided merely for symmetry / readability.

**Migration:** This flag is an incompatible change because, in the output of `bazel query --output=proto` (or `--output=xml`), the names "public" and "private" will stringify in a way that's ambiguous with the hypothetical packages `//public` and `//private`. To fix this, `--incompatible_package_group_includes_double_slash` should be enabled whenever this flag is used. There is no separate migration needed just for `--incompatible_package_group_has_public_syntax`, except that any tooling that statically processes `BUILD` files or which consumes query output should be prepared for the possibility of the `"public"` and `"private"` values.

Note that in .bzl visibility, the values `"public"` and `"private"` are always available regardless of this flag.

**Rationale:** Flipping this change is a prerequisite to #16323 since without `"public"` there is no replacement for `"//..."`.

**Comment by lberki** [comment]
To make our discussion on Friday less obscure: why is this planned to be implemented in the `packages=` attribute as opposed to e.g. two new `public=` / `private=` attributes which would be mutually exclusive with each other or `packages=` or in some other way that doesn't involve making `packages=` possibly mean two different things?

One of the long-standing and nigh-unfixable issues with the rule-level visibility system is that the `visibility=` attribute is used for both for things that give rise to dependencies (package group references) and things that don't (`//visibility:public` and `:__pkg__` / `:__subpackages`) and that makes it interpreting quite ugly.

Whereas it doesn't look like you have the same problem here because you don't ever have dependencies here, heterogenous lists still make me uneasy.

**Comment by brandjon** [comment]
The reason to support these in the `packages` attribute is to avoid asymmetry between `package_group` and bzl visibility. Under this approach, the only difference in the kinds of package specifications they accept is that bzl visibility can't tolerate negations.

Having "public"/"private" be valid package specifications for `package_group` is more of an aesthetic benefit than a practical one. I don't expect people to, e.g., set `my_allowlist = ["public"]` and then pass it to both `visibility()` and to a `packages` attr. But I do like good aesthetics -- it means fewer differences to document and explain.

The reason to have "public"/"private" be package specifications at all, as opposed to special forms of `visibility()`, is that this lets them compose naturally with other allowlists. I.e., if someone refactors an allowlist between public or private and anything that's in-between, downstream composers of that allowlist are unaffected. Syntactically, it also is a little nicer because it means `visibility("public")` is just a special case of the syntactic sugar for `visibility(["public"])`.

If we didn't put "public"/"private" in the `packages` attr, I probably wouldn't bother implementing `public=`/`private=` attrs for `package_group`.

Actually, I forgot the best reason of all for "public": We already have it in the form of misinterpreting `"//..."`, and I want to fix that in a way that doesn't force people off `package_group` if possible.

**Comment by meteorcloudy** [comment]
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1291

This flag should be safe to flip (the rules_nodejs failure is unrelated).

**Comment by meteorcloudy** [comment]
> To fix this, --incompatible_package_group_includes_double_slash should be enabled whenever this flag is used.

Oh, I see, this flag depends on the other one.

**Comment by meteorcloudy** [comment]
OK, IIUC, flipping this flag would actually fix breakages of https://github.com/bazelbuild/bazel/issues/16323, if so, please do so.

**Comment by brandjon** [comment]
One potential migration issue is that users who have `packages = ["//..."]` in their package groups, and who want this to mean public, will have to change to `packages = ["public"]` in sync with their upgrade to use Bazel 6.0. Rewriting to `public` before upgrading Bazel isn't possible, and upgrading Bazel before rewriting to `public` means that in the interim the package group will have reduced visibility. Perhaps this reduced visibility isn't a problem if the user doesn't cut a release of their project during that window, since it will still be visible within their local repo.

We could possibly side-step this issue if we cut a 5.x release that flipped this flag, under the justification that this change isn't *really* incompatible, it just creates a minor ambiguity in an edge case for bazel query output. But we'd still have to release a new 5.x just for the sake of migrating to 6.0, which sounds like overkill.

I'm also a little worried about bootstrapping bazel itself. Building 6.0 with 5.x breaks when I fix the Starlark interpreter's package to be `public` instead of `//...`. We could avoid this by allowing the interpreter's visibility to regress in 6.0 and fixing it in a follow-up patch release. We don't really support public use of the Starlark interpreter outside of Copybara and I suppose Stardoc -- and those projects can simply not point to / not vendor in the 6.0 release.

I ran into issues with allowlists in `@bazel_tools` breaking, but I think I can fix that by splitting a couple `BUILD` files into `BUILD.tools` files.

**Comment by brandjon** [comment]
Now that I write that out, it sounds like a reasonable plan: Change the `@bazel_tools` allowlists to be `public` and split them into `BUILD.tools` files to not break bootstrapping of Bazel. Do that atomically with flipping this flag. Run the downstream projects pipeline with a pending change to do that and flip the other two incompatible flags. If it passes, submit these changes into 6.0. After 6.0 is released, re-broaden the Starlark interpreter visibility to `public`.


With the `BUILD` files split into `BUILD.tools`, it builds

**Comment by brandjon** [comment]
I ran a [downstream test run](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2677) with all three flags flipped. Test failures would most likely be from `--incompatible_fix_package_group_reporoot_syntax`, though it's possible we'll see one from `--incompatible_package_group_includes_double_slash`.

This test run missed an android change for `@bazel_tools`, so it's possible the android tests would've failed if they hadn't been disabled.

**Comment by brandjon** [comment]
Failures are:
- Bazel Remote Cache: CalledProcessError from .bazelci/migration-test.sh, looks like a failure to obtain a Go environment during setup.
- TensorFlow: already failing in latest [scheduled build](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2673)
- rules_kotlin: couldn't get `@io_bazel_rules_kotlin//kotlin` while computing main repo mapping. Sounds like an unrelated flake.
- rules_python (already failing)
- rules_rust: `//util/import:import_internal_test` failed. The log isn't attached, but given that it occurs at execution time and only on one platform, I think it's very unlikely to be related.

So I think that this change and the related changes of #16391 and #16323 are good to go, as far as downstream projects are concerned. Just working on some blockers internal to Bazel..

**Comment by brandjon** [comment]
Planning on submitting flips to these flags' defaults in the Java code tomorrow.
