### ISSUE TITLE
incompatible_remote_downloader_send_all_headers

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/bazel#16356]
**Description**: This flag changes the JSON sent to the gRPC remote downloader as qualifier `bazel.auth_headers` from a map of strings to a map of list of strings.

**Rationale**: Headers can, in general, be defined multiple times, not just once.

**Migration**: Flipping this flag might cause failures when using the Remote Assets API when the server supports reading this qualifier. Contact your service provider for more information.

**Comment by Yannic** [comment]
cc @tjgq 

Please add the following labels: `breaking-change-6.0`, `incompatible-change`

**Comment by meteorcloudy** [comment]
Please don't forget adding `migration-ready` label, otherwise the incompatible flags pipeline won't test this one.
