### ISSUE TITLE
incompatible_remote_dangling_symlinks

### ISSUE THREAD

**Issue by tjgq** [bazelbuild/bazel#16353]
**Description**: This flag causes dangling symlinks found in the outputs of a locally executed action to be uploaded to a remote cache as such. The current behavior is for Bazel to throw an error in the presence of a dangling symlink.

**Rationale**: Output symlinks, including the dangling kind, are a feature of the Remote Execution API.

**Migration**: Flipping this flag might cause previously failing actions to start succeeding. If it's important that these actions fail, they should check for the presence of a dangling symlink explicitly (or ensure one isn't produced) rather than rely on Bazel to catch it.

**Comment by meteorcloudy** [comment]
Should we close this issue since `incompatible_remote_dangling_symlinks` is already true at HEAD?

**Comment by lberki** [comment]
@coeuvre can you tell me a bit more about why the decision is made solely based on whether the symlink is dangling or not?

Naively, I would think that `UploadManifest.addFiles()` would take into account whether the action output being uploaded is an unresolved symlink or not, but that information is not even available in that method.

**Comment by coeuvre** [comment]
Inside `UploadManifest` if the path is symlink, it is unresolved symlink. Resolved symlink will be resolved to the target ahead of time.

**Comment by meteorcloudy** [comment]
Can we close this one since the default value is already true for this flag? Is there any other follow up work needed?

**Comment by coeuvre** [comment]
Yeah, I think we can close this issue.
