### ISSUE TITLE
MacOS + Docker + Cache on the VirtioFS volume => "ERROR: Failed to initialize sandbox: /sandbox/inaccessibleHelperDir (Permission denied)"

### ISSUE THREAD

**Issue by Gorbush** [bazelbuild/bazel#16364]
### Description of the bug:

When I run the bazel build (Even of bazel itself) inside the Docker container on the MacOS host, with the build cache residing on the mounted volume - the build fails with the error below.
I have found a way to patch the flow to make it pass for this case - by reordering the operations of setting the attributes for file and folder "inaccessible".
See the zip file with the example to reproduce it and suggested patch file.

```
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
DEBUG: /opt/workspace/.bazel-cache/_bazel_root/29b5c9e3503449f7bb32226438a9d9d7/external/build_bazel_rules_nodejs/index.bzl:122:10: WARNING: check_rules_nodejs_version has been removed. This is a no-op, please
remove the call.
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Analyzing: target //src:bazel-dev (1 packages loaded, 0 targets configured)
Analyzing: target //src:bazel-dev (335 packages loaded, 7171 targets configured)
Analyzing: target //src:bazel-dev (374 packages loaded, 9106 targets configured)
Analyzing: target //src:bazel-dev (375 packages loaded, 9113 targets configured)
Analyzing: target //src:bazel-dev (378 packages loaded, 9139 targets configured)
Analyzing: target //src:bazel-dev (378 packages loaded, 9139 targets configured)
Analyzing: target //src:bazel-dev (378 packages loaded, 9139 targets configured)
Analyzing: target //src:bazel-dev (378 packages loaded, 9139 targets configured)
INFO: Analyzed target //src:bazel-dev (379 packages loaded, 10165 targets configured).
INFO: Found 1 target...
ERROR: Failed to initialize sandbox: /opt/workspace/.bazel-cache/_bazel_root/29b5c9e3503449f7bb32226438a9d9d7/sandbox/inaccessibleHelperDir (Permission denied)
INFO: Elapsed time: 174.186s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

zip file with docker container is provided

### Which operating system are you running Bazel on?

MacOS Monterey 12.6 (21G115) CPU Intel 3.6 GHz 10-Core Intel Core i9 Docker version 4.11.1 (84025)

### What is the output of `bazel info release`?

development version

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

git clone, bazel build, steps are show in the progress.sh file in the attached archive

### Have you found anything relevant by searching the web?

not at all.

### Any other information, logs, or outputs that you want to share?

provided in the zip file.

**Comment by Gorbush** [comment]
Docker container [bazel-mac-issue.zip](https://github.com/bazelbuild/bazel/files/9686911/bazel-mac-issue.zip)
Includes:
diff.patch - suggested patch to reorder the file operations
error.message - the error message I see

**Comment by Gorbush** [comment]
To reproduce the issue - run 
`make build run`

And it will produce the volume folder with the following files:
* 00_build_original.log  - log of the build to check that the regular run is good
* 01_build_patched.log - log of the build to produce the patched version of bazel-dev
* 02_build_broken.log - log of the build with the cache residing on the mounted volume (/opt/workspace)
* 03_build_by_patched.log - log of the build using the patched version of bazel
* bazel - folder with bazel sources
* bazel-dev - patched version of bazel to verify that patching helped in the case

**Comment by Gorbush** [comment]
the last build is also failing with some other error, much after the initial failure with unpatched version

**Comment by Gorbush** [comment]
BTW this is also reproducible using any other way of redirecting the cache folder:
* ln -s /opt/workspace/.bazel-cache  ~/.cache/bazel
* adding startup --output_base=/opt/workspace/.bazel-cache to .bazelrc
* defining export TEST_TMPDIR=/opt/workspace/.bazel-cache

**Comment by Gorbush** [comment]
It feels like the VirtioFS does not allow to change the permissions if the file is not Readable.
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxedStrategy.java#L58
I tried to change the order of the operations, and it passed that stage.
Instead of current
```
    Path inaccessibleHelperFile = sandboxBase.getRelative("inaccessibleHelperFile");
    FileSystemUtils.touchFile(inaccessibleHelperFile);
    inaccessibleHelperFile.setReadable(false);
    inaccessibleHelperFile.setWritable(false);
    inaccessibleHelperFile.setExecutable(false);

    Path inaccessibleHelperDir = sandboxBase.getRelative("inaccessibleHelperDir");
    inaccessibleHelperDir.createDirectory();
    inaccessibleHelperDir.setReadable(false);
    inaccessibleHelperDir.setWritable(false);
    inaccessibleHelperDir.setExecutable(false);
```

I reordered them into
```
    Path inaccessibleHelperFile = sandboxBase.getRelative("inaccessibleHelperFile");
    FileSystemUtils.touchFile(inaccessibleHelperFile);
    inaccessibleHelperFile.setExecutable(false);
    inaccessibleHelperFile.setWritable(false);
    inaccessibleHelperFile.setReadable(false);

    Path inaccessibleHelperDir = sandboxBase.getRelative("inaccessibleHelperDir");
    inaccessibleHelperDir.createDirectory();
    inaccessibleHelperDir.setExecutable(false);
    inaccessibleHelperDir.setWritable(false);
    inaccessibleHelperDir.setReadable(false);
```

**Comment by larsrc-google** [comment]
An interesting behaviour of VirtioFS, but the reordering looks fine, so I'm applying that.
