### ISSUE TITLE
Document How to Properly Document a Rule

### ISSUE THREAD

**Issue by aryeh-looker** [bazelbuild/bazel#16374]
i.e. should it be `"""docstring"""` at the top of a `def.bzl` file? etc.

Should probably live here https://bazel.build/extending/rules

**Comment by sgowroji** [comment]
Hello @aryeh-looker, Could you please elaborate your query with complete details. Thanks!

**Comment by fweikert** [comment]
They are documented at https://bazel.build/rules/bzl-style#docstring, leading to https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring

**Comment by sgowroji** [comment]
Please find the details [here](https://github.com/bazelbuild/bazel/issues/16374#issuecomment-1320490905). We are closing this issue now. Feel free to reach us for any further details. Thanks!
