### ISSUE TITLE
linux sandbox fails on Centos 7 with "UID 65534 not found in passwd file"

### ISSUE THREAD

**Issue by znull** [bazelbuild/bazel#1637]
69fa69983b26c1059c99c7709162fbe778fe690f moved the [call to SetupDirectories](https://github.com/bazelbuild/bazel/blob/master/src/main/tools/linux-sandbox.c#L798) to come after [user namespaces](http://man7.org/linux/man-pages/man7/user_namespaces.7.html) are configured. On systems where `/etc/passwd` maps user `nobody` to uid 65534 this still works, but on systems like Centos 7 where `nobody` is mapped to uid 99, this causes the [getpwud check in SetupDirectories](https://github.com/bazelbuild/bazel/blob/master/src/main/tools/linux-sandbox.c#L562) to fail, breaking all uses of sandboxing.

**Comment by znull** [comment]
pushed possible fix for review at https://bazel-review.googlesource.com/5410. I've confirmed this fixes sandboxing on affected systems.

**Comment by hermione521** [comment]
Thank you for your PR. A new sandbox implementation is on the way, so I'm not sure if @philwo want to review this.

**Comment by znull** [comment]
I should mention that this isn't strictly a Centos issue - it's more that you can globally break sandboxing on any linux machine by doing `echo 5555 > /proc/sys/kernel/overflowuid` (or any value that isn't the `nobody` uid)

**Comment by bsilver8192** [comment]
Basically, #481 came back, except with a nicer error message... Sounds like time for a test, which I just uploaded as [Ib785c874cdb9192920f9935b696bfd6c9c0e5f4f](https://bazel-review.googlesource.com/#/q/Ib785c874cdb9192920f9935b696bfd6c9c0e5f4f).
