### ISSUE TITLE
Link to `rule(...)` Documentation from https://bazel.build/rules/lib/rule

### ISSUE THREAD

**Issue by aryeh-looker** [bazelbuild/bazel#16373]
https://bazel.build/rules/lib/rule has little information about how to use the `rule` callable. Add a link to https://bazel.build/extending/rules to help users learn more.

**Comment by sgowroji** [comment]
Hello @aryeh-looker, Could you please elaborate your query on the above request. Thanks!

**Comment by sgowroji** [comment]
Attached PR is merged. We are closing this issue now. Thank you for contributing in PR.
