### ISSUE TITLE
`-std=c++14` in `tools/bazel.rc` ignored when building external repos

### ISSUE THREAD

**Issue by veblush** [bazelbuild/bazel#16371]
### Description of the bug:

Recently gRPC bumped the version of C++ to 14 and its [tools/bazel.rc](https://github.com/grpc/grpc/blob/6fdbe6794695be853cdb87095a6b90868517f985/tools/bazel.rc#L5) got `--cxxopt='-std=c++14'` option to handle this. This worked and gRPC started having more C++14 code. But this began to have an issue when gRPC tried to upgrade protobuf to the version which started using C++14 code.

```
$ bazel build :grpc++
bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/src/google/protobuf/io/_virtual_includes/printer/google/protobuf/io/printer.h:539:3:
  error: 'auto' return without trailing return type; deduced return types are a C++14 extension
```

But when I built this with `BAZEL_CXXOPTS="-std=c++14"`, it worked.

```
$ export BAZEL_CXXOPTS="-std=c++14"
$ bazel build :grpc++
successfully built it.
```

If I'm doing wrong, what would be the right way to configure to use C++14 with bazel?

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

$ git clone https://github.com/veblush/grpc.git
$ git checkout 10bbf8e50dcbed1401d4ea8ddf08eb2151cc3d5f
$ bazel build :grpc++

### Which operating system are you running Bazel on?

Linux/Debian

### What is the output of `bazel info release`?

release 5.3.0

**Comment by ChrisCummins** [comment]
+1. I can reproduce the same issue with the same external dependency (grpc).

**Comment by fmeum** [comment]
`bazel build //:grpc++` builds protobuf in the `exec` configuration, i.e., to be run in an action during the build. Thus, the C/C++ compilation flags are configured via `--host_cxxopt`, not `--cxxopt`. If I make that change in `tools/bazel.rc`, I get `//:grpc++` to compile.

**Comment by ChrisCummins** [comment]
Thanks!

**Comment by fmeum** [comment]
@sgowroji Can be closed.

**Comment by sgowroji** [comment]
Hello @veblush, We are closing this issue w.r.t above [comment](https://github.com/bazelbuild/bazel/issues/16371#issuecomment-1347826838). Please feel free to reach us if you  have any further queries.
