### ISSUE TITLE
Allow ctx.expand_location to skip mixing in hard-coded attributes

### ISSUE THREAD

**Issue by rickeylev** [bazelbuild/bazel#16382]
### Description of the feature request:

Essentially, add an arg to `ctx.expand_location` to tell it to _not_ mixin hard-coded attribute names. Or otherwise expose args to help control this behavior.

Today, ctx.expand_location will automatically mixin files from various attributes in [LocationExpander.java](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/analysis/LocationExpander.java). The set of attributes and the files taken from them is a bit complicated. In short, the attributes deps and tools are always mixed in; I'm not sure if srcs is or not. data isn't _always_ mixed in, but can be, depending on what the native rule does. Depending on the attribute/settings, LocationExpander will expand to the default outputs or just the executable. In comparison, ctx.expand_location will always expand to just the default outputs, plus inherit a subset of the behavior of LocationExpander. It is really quite confusing.

None of this is documented. It's also very confusing/surprising and differs from if native code (as done with `args` performs expansion).

I think there's a few different options here; some ideas:

1. "add_extra_stuff=true/false" arg. This would control if LocationExpander mixins in any attributes.
2. "attrs" arg. This would control which attributes LocationExpander mixes in.
3. Add args for srcs, deps, tools, and data. This would replace LocationExpander looking up the attributes themselves so the caller can selectively include/exclude them.
4. Add "executables" arg. This would replace the logic that looks at deps/data/tools and allow the caller to specify which targets should expanded to only their executable, if available.

IMHO, the (4: executables arg) is the most appealing. It allows the caller to control the expansion while keep the API pretty minimal. It doesn't sound unreasonable for a rule to want to exclude/include targets based on some arbitrary condition.

cc @f0rmiga who would probably be interested in this, too.

### What underlying problem are you trying to solve with this feature?

The underlying problem to solve is making ctx.expand_location behave more similarly to native rule expansion and with less surprising behavior.

### Have you found anything relevant by searching the web?

* request to document expand_location: https://github.com/bazelbuild/bazel/issues/11321
* PR to change expand_location to treat executables differently: https://github.com/bazelbuild/bazel/pull/16381

**Comment by f0rmiga** [comment]
Thanks. I'd add that this makes moving native rules to Starlark rules more easily without unexpectedly breaking current behaviours.

**Comment by f0rmiga** [comment]
Also interested in more control over `expand_location`: https://github.com/bazelbuild/rules_python/pull/846.
