### ISSUE TITLE
incompatible_disallow_java_import_empty_jars

### ISSUE THREAD

**Issue by kotlaja** [bazelbuild/bazel#16385]
**Description:** We’re making java_import stricter by not allowing users to use it without specifying at least one jar file. In other words, “jars” attribute of java_import must not be empty. 

In case you’re affected with this migration (you have an empty java_import.jars attribute), you’ll get the error “empty java_import.jars is no longer supported”. 
Until you completely migrate, use the incompatible_disallow_java_import_empty_jars flag to mask the error.

**Migration:** Depending on the usage of java_import with empty “jars” attribute, use one of the changes in the following order:
1. Use [alias](https://bazel.build/reference/be/general#alias) whenever you have the name of the java_import and only one label inside deps or exports.  

   Example: 

	`java_import(
		name = “test”,
		deps = [“test_dep”]
	)`

   change to

	`alias(
		name = “test”,
		actual = “test_dep”
	)`

2. Try using [java_library](https://bazel.build/reference/be/java#java_library) instead of java_import.

3. If the last two approaches don’t work, define and use a dummy file inside java_import.jars. **Please** try to avoid this option and use it only as a last choice.

**Comment by keertk** [comment]
Hi @kotlaja I see that this flag is not breaking any downstream projects. Can we close this issue?

**Comment by kotlaja** [comment]
Yes, we can. Thanks for the reminder.
