### ISSUE TITLE
register_toolchains and other globals are documented twice

### ISSUE THREAD

**Issue by jfirebaugh** [bazelbuild/bazel#16383]
### Description of the bug:

`register_toolchains` is documented twice with slightly different documentation text.

https://bazel.build/rules/lib/globals#register_toolchains() is the permalink to both. If you visit that link you'll see both items. One reads "Register an already-defined toolchain..." and the other "Specifies already-defined toolchains...".

`register_execution_platforms()` and `repository_rule(implementation, attrs, local, environ, configure, remotable, doc)` are also duplicated.

**Comment by Wyverald** [comment]
This is an unfortunate result of our documentation setup. One `register_toolchains` is for the WORKSPACE function and the other is for the MODULE.bazel function. cc @fweikert @meteorcloudy I was planning to do something about this after the branch cut.

**Comment by sgowroji** [comment]
Similar issue with documentation https://github.com/bazelbuild/bazel/issues/14879#top
