### ISSUE TITLE
incompatible_package_group_includes_double_slash

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#16391]
**Description:** This flag causes the values in `package_group`'s `packages` attribute to no longer have the leading `"//"` stripped when output in `bazel query --output=proto` (or `--output=xml`). For instance, `//pkg/foo` would previously output as `"pkg/foo"`. This bug did not arise for package specifications that live outside the main repo, which always printed as `"@repo//pkg/foo"`.

**Migration:** Any tooling that consumes the query proto or xml formats must be able to tolerate package specification strings with leading double-slashes. This has no impact on the build itself (except possibly via `genquery`).

**Rationale:** This is a prerequisite to #16355, to avoid ambiguity between `"public"` and `"//public"`.

**Comment by meteorcloudy** [comment]
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1291
```
ERROR: --incompatible_package_group_includes_double_slash :: Unrecognized option: --incompatible_package_group_includes_double_slash
```
Looks like this flag is query only, the incompatible flag pipeline cannot test query only incompatible flags. But you can still do a [downstream test](https://github.com/bazelbuild/continuous-integration/blob/master/docs/downstream-testing.md) manually.
