### ISSUE TITLE
More versatile worker_max_instances

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#1639]
Should it be the plan to keep `worker_max_instances` (not sure whether it is the best configuration method) we would need for it to be more versatile.
We'd have the following requirements:
1. We have certain third-party libraries, which open threads. For this we want to limit instance count to _CPU_CORES_/2 for a certain mmenomic.
2. At any time we do not want the total number of workers to exceed _CPU_CORES_.
3. 1 and 2 still leave us with the problem that while workers from 1 are running no others must be running.

As a result I think it would be better to have a slot mechanism. Given that you could decide whether you want to match slots to cpu cores or moon cycles or whatever.
- By default count of slots then would match _CPU_CORES_.
- For every worker (type) you would specify how many slots it needs (e.g. `1`, `CPU_CORES`, `int(CPU_CORES/2)` .

**Comment by philwo** [comment]
We made some improvements here (https://github.com/bazelbuild/bazel/commit/0c12603bedd4a270094137269b910a8587d3f93c#diff-0e04d0b60b52d9ae0a29b39a8b8e824a).

**Comment by larsrc-google** [comment]
@abergmeier-dsfishlabs Did philwo's improvements help you? Are you using them? In most cases, 1 or 2 workers give you a lot of speedup anyway, adding more adds more memory usage without necessarily giving more speed (see https://github.com/bazelbuild/bazel/pull/8701 for some data).
