### ISSUE TITLE
Improve documentation for create_cc_toolchain_config_info

### ISSUE THREAD

**Issue by jfirebaugh** [bazelbuild/bazel#16395]
### Description of the feature request:

It would be helpful for developers of custom toolchains to have more complete documentation for [create_cc_toolchain_config_info](https://bazel.build/rules/lib/cc_common#create_cc_toolchain_config_info).

The existing documentation does not really explain many of the parameters. Specifically, the documentation for `features`, `action_configs`, `artifact_name_patterns`, `tool_paths`, and `make_variables` are not much more than links into to source code (and they link to code on the `master` branch, which is now a location in the source unrelated to the parameter).

**Comment by keertk** [comment]
Hi there! Missing descriptions have been added to those 5 params to start and pointers to incorrect lines in the source code have been fixed. Hope this helps!
