### ISSUE TITLE
Create a tag or command line option for downloading final target results from remote cache server without local rebuild

### ISSUE THREAD

**Issue by OparinE** [bazelbuild/bazel#16398]
### Description of the feature request:

Let take a look on example. Bazel 5.3.1
BUILD.bazel:
```
cc_library(
    name = "lib",
    srcs = ["lib.cpp"],
    hdrs = ["lib.h"],
)
cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = ["lib"]
)
```
build commands:
1) `bazel build :main --remote_cache=http://127.0.0.1:8080 –remote_download_toplevel --modify_execution_info=CppCompile.*=+no-remote-cache-upload`
2) `bazel clean`
3) `bazel build :main --remote_cache=http://127.0.0.1:8080 –remote_download_toplevel --modify_execution_info=CppCompile.*=+no-remote-cache-upload`

I expect, that result of command_3 is the fetched data from remote cache server. However, I see recompilation of `main.cpp`, `lib.cpp`.

Based on cache server size I make assumptions, that command_1 works fine. Intermediate results were not sent to cache server.

### What underlying problem are you trying to solve with this feature?

Reduce cache server capacity. Do NOT send .obj files
Reduce data traffic between cache server and users 

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

5.3.1

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

INFO: Invocation ID: befc814e-0f79-4ca2-a820-5683124e543c
release 5.3.1

### Have you found anything relevant by searching the web?

googling on a web, searching on official bazel doc

**Comment by coeuvre** [comment]
I see you have `--modify_execution_info=CppCompile.*=+no-remote-cache-upload` in the command 1 which means the results of compilation (.obj files) will not be updated to remote cache. I think this explains why you see recompilation in command 3.

**Comment by oev88** [comment]
Yes, but how can I force the bazel to get libs and exes from cache server and not to rebuild source files? (This is the major motivation, because we spend server and net resources)

**Comment by coeuvre** [comment]
Bazel will get libs and exes from cache server if these are actually there.

In your example, since objs are not uploaded to remote cache in command 1, Bazel will not able to get them from cache server for command 3. But I believe Bazel will download the outputs from link actions (e.g. libs and exes) from cache server for command 3.

**Comment by oev88** [comment]
But this not happens. 
Anyway, does bazel have another mechanism for uploading step results only without publishing intermediate steps?
I don't want to publish .obj files and recompile source files when results of the target (.exe(s), .lib(s)) were sent to the server.

**Comment by oev88** [comment]
Otherwise, how do you tell the exe is built from the most recently modified sources? 
-> As compiler does. Look on the changes of source files

Can you please provide more information, e.g execution log?
-> I'll publish test example with logs on github soon
