### ISSUE TITLE
Add extra mount directories for sandbox, project wise

### ISSUE THREAD

**Issue by ahyangyi** [bazelbuild/bazel#1640]
Here is something I'm trying to do today: run a test of a C++ library that uses CUDA. `bazel run` succeeds, while `bazel test` fails. A closer examination reveals that this is due to the sandbox not mounting devices `/dev/nvidia*`.

For now I simply hacked the Bazel source code to add these extra paths for the sandbox to mount. However, is there a configurable setting somewhere that allows me to do the same without touching the Bazel source code? Thanks!

(From my little experience of Tensorflow they probably did something similar in their repos. But I failed to find out how they got that done.)

**Comment by davidzchen** [comment]
AFAIU, TensorFlow builds without sandboxing: https://github.com/tensorflow/tensorflow/blob/master/tools/bazel.rc.template

+ @martinwicke to confirm.

**Comment by martinwicke** [comment]
We have it generally disabled because disabling it generates fewer support
requests than enabling it.

**Comment by ahyangyi** [comment]
Yeah, that makes sense for Tensorflow, which runs in diverse environments. I guess for the closer environment I'm looking at, hacking the sandbox source code to mount /dev/nvidia* is a sensible solution.

**Comment by bsilver8192** [comment]
Would `build --sandbox_add_path=/dev/nvidiafoo` lines in tools/bazel.rc work?

**Comment by ahyangyi** [comment]
@bsilver8192  Thanks, that works. That's exactly what I'm looking for.
