### ISSUE TITLE
Symbol error when consuming transitive imported static libraries with linkstatic = False

### ISSUE THREAD

**Issue by cameron-martin** [bazelbuild/bazel#16410]
### Description of the bug:

I have three libraries: test, foo, bar, where test depends on foo and foo depends on bar. Bar is a static library imported using `cc_import`, foo is a library built from source using `cc_library`, and test is a `cc_test`. Because by default `cc_test` uses `linkstatic = False`, test is linked to foo dynamically. However, bar is statically linked into test, presumably because there is no dynamic version to use.

With `g++`, the symbols of bar end up local when in the test executable and therefore inaccessible to foo. Interestingly when using gcc they end up global and this works. This can be observed in the repository below by changing the extensions to .c and .h, causing bazel to use gcc.

This can be worked around by specifying `linkstatic = True` on this test, but I feel like the consumers of foo should not have to be aware of the implementation of bar.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

A minimal reproducible example is here: https://github.com/cameron-martin/bazel-linking-imported-archives

The commands in the README can be run to reproduce this.

### Which operating system are you running Bazel on?

Ubuntu 18.04

### What is the output of `bazel info release`?

release 5.3.1

### Have you found anything relevant by searching the web?

No

**Comment by cameron-martin** [comment]
A fix for this issue could be to make `cc_import` also expose a dynamic library in the case that it is only given a static library. Unfortunately going the other way is not possible (creating a static library from a dynamic one).

**Comment by cameron-martin** [comment]
In the readme of the [linked reproducer](https://github.com/cameron-martin/bazel-linking-imported-archives) there is essentially such a shell script. Does running these commands not produce a linker error?

**Comment by pcjanzen** [comment]
```
$ g++ -c bar.cpp -o bar.o
bar.cpp:1:10: fatal error: bar.h: No such file or directory
    1 | #include "bar.h"
      |          ^~~~~~~
```

but if i do
```
$ ln -s bar.hpp bar.h
$ g++ -c bar.cpp -o bar.o
$ ar -rcs bar.a bar.o
$ bazel test //:test
[...]
//:test                                                                  PASSED in 0.0s
```

**Comment by cameron-martin** [comment]
You're right, I'm not sure how I messed up the reproducer so much. I'll investigate some more and get back to you.
