### ISSUE TITLE
linker warnings on macOS XCode 14: `ld: warning: -undefined dynamic_lookup may not work with chained fixups`

### ISSUE THREAD

**Issue by garymm** [bazelbuild/bazel#16413]
### Description of the problem / feature request:

`cc_binary` built on MacOS with XCode 14 results in warnings link the following being printed:
`ld: warning: -undefined dynamic_lookup may not work with chained fixups`

Maybe due to this?
https://github.com/bazelbuild/bazel/blob/32d56b67eeb93c52cb9393d1d7f72d8d1506407f/tools/osx/crosstool/cc_toolchain_config.bzl#L1130

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```sh
git clone https://github.com/bazelbuild/examples
cd examples/cpp-tutorial/stage3
bazel build //...
```

Output:
```
➜  bazel build //...
Starting local Bazel server and connecting to it...
INFO: Analyzed 3 targets (38 packages loaded, 172 targets configured).
INFO: Found 3 targets...
INFO: From Linking main/libhello-greet.so:
ld: warning: -undefined dynamic_lookup may not work with chained fixups
INFO: From Linking lib/libhello-time.so:
ld: warning: -undefined dynamic_lookup may not work with chained fixups
INFO: From Linking main/hello-world:
ld: warning: -undefined dynamic_lookup may not work with chained fixups
```

### What operating system are you running Bazel on?

MacOS 12.6

### What's the output of `bazel info release`?

`release 5.3.1`

### What version of rules_cc do you use? Can you paste the workspace rule used to fetch rules_cc? What other relevant dependencies does your project have?

built in, but also tried `0.0.4`

### What Bazel options do you use to trigger the issue? What C++ toolchain do you use?

Didn't specify any bazel options or configure any custom toolchain.

###  Have you found anything relevant by searching the web?

https://github.com/python/cpython/issues/97524
https://github.com/ruby/ruby/pull/6193
https://issues.guix.gnu.org/issue/57849

**Comment by keith** [comment]
As a temporary workaround you can pass `--linkopt=-Wl,-no_fixup_chains` to disable the chained fixup feature of the linker. AFAIUI that feature has runtime (or maybe just launch time) performance benefits, but it isn't otherwise required and only defaults to enabled on newer OS versions. I doubt this will ever change on the linker side given that `-undefined dynamic_lookup` says that it's deprecated (although it has said that for many years on some platforms). If there is a bazel specific fix here it's probably to remove the use of `-undefined dynamic_lookup` all together

**Comment by garymm** [comment]
From reading [this](https://openradar.appspot.com/radar?id=5536824084660224), it seems like there are legitimate uses of this linker flag that don't have work-arounds.

**Comment by keith** [comment]
Yes there are definitely legit use cases, but I don't think it needs to be the default, since I believe most use cases are pretty specific scenarios
