### ISSUE TITLE
Upgrade JaCoCo from 0.8.7 to 0.8.9-SNAPSHOT

### ISSUE THREAD

**Issue by somethingvague** [bazelbuild/bazel#16412]
### Description of the feature request:

Please upgrade to the latest JaCoCo distribution which adds official support for Java 17/18 and experimental support for Java 19 classes.

Happy to try workarounds if there are any suggestions.

### What underlying problem are you trying to solve with this feature?

Instrumentation for Java 19 targets

### Which operating system are you running Bazel on?

Debian GNU/Linux

### What is the output of `bazel info release`?

release 5.3.1

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
This is a internal corporate git repository hosted on GitLab.
```

### Have you found anything relevant by searching the web?

https://www.jacoco.org/jacoco/trunk/doc/changes.html

### Any other information, logs, or outputs that you want to share?

```
java.io.IOException: Error while instrumenting bazel-out/k8-fastbuild/bin/<path/to/Class>.
        at org.jacoco.core.instr.Instrumenter.instrumentError(Instrumenter.java:161)
        at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:110)
        at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:135)
        at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:155)
        at com.google.devtools.build.buildjar.instrumentation.JacocoInstrumentationProcessor$1.visitFile(JacocoInstrumentationProcessor.java:141)
        at com.google.devtools.build.buildjar.instrumentation.JacocoInstrumentationProcessor$1.visitFile(JacocoInstrumentationProcessor.java:113)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
        at com.google.devtools.build.buildjar.instrumentation.JacocoInstrumentationProcessor.instrumentRecursively(JacocoInstrumentationProcessor.java:111)
        at com.google.devtools.build.buildjar.instrumentation.JacocoInstrumentationProcessor.processRequest(JacocoInstrumentationProcessor.java:85)
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.buildJar(SimpleJavaLibraryBuilder.java:151)
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:120)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.build(BazelJavaBuilder.java:105)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.parseAndBuild(BazelJavaBuilder.java:85)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:69)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at org.jacoco.core.internal.instr.InstrSupport.classReaderFor(InstrSupport.java:280)
        at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:76)
        at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:108)
        ... 13 more
```

**Comment by comius** [comment]
cc @cushon

**Comment by cushon** [comment]
```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
```

Is the jacoco in Bazel using a vendored ASM, or is the immediate problem actually that we need a newer ASM?

Either way, upgrading to the latest versions SGTM. Anyone want to send a PR?

**Comment by somethingvague** [comment]
Hi @cushon 

Apologies for the delayed response.

I noticed that the latest release version of jacoco is 0.8.8 which should also be fine, it does not require an upgrade to ASM. 

I started making the first commit (see https://github.com/somethingvague/bazel/commit/fa2b2cdf0737cb0fca3046ba89595f92f1dd6da5) and then I noticed the two patches under `/third_party/java/jacoco` which appear to have been applied to pre-existing 0.8.7 jars.

I think the process is
1. check out 0.8.8 jacoco release tag and make equivalent changes to the patches.
3. maven install to create the patched JARs (any particular bytecode version?)
4. check in the patched JARs along with the diffs for documentation. Are these diffs just for reference, do they need to be separate files and do they need to be a specific format?

Please confirm.

Thanks.

**Comment by cushon** [comment]
I don't know exactly how this was done for Bazel in 21e2794ed8bb834581c82b248d35dfe724f813b8, but that sounds about right to me.

I think it might be OK to drop `0001-Disable-use-of-constant-dynamic-bytecode.patch` at this point.

The patches could be applied with something like:

```
$ git checkout v0.8.8
$ git am ~/src/bazel/third_party/java/jacoco/*.patch
```

It doesn't look like there are merge conflicts, but if there were I would apply them against v0.8.7 instead and then use git to do the rebase onto v0.8.8.

And then I would use `git format-patch v0.8.8` to regenerate the patches.

**Comment by somethingvague** [comment]
Thanks for the tips.

 think an ASM upgrade might be needed after all, however I am struggling to verify the changes I am making to my fork. The process I'm following is:

1. Add the Jacoco and ASM jars and update any references I find
2. Build `//src:bazel-dev`
3. Execute `bazel-bin/src/bazel-dev` against a sample project which has a similar configuration as my work setting (`remote_java_repository` with a `default_java_toolchain`)

I can see that `bazel-bin/src/java_tools/buildjar/JavaBuilder_deploy.jar` contains the updated JARs but when I run coverage against my sample project Bazel internally runs `external/remote_java_tools/java_tools/JavaBuilder_deploy.jar` which has the older asm@9.2 and jacoco@0.8.7 packed inside. 

I tried configuring the toolchain with `NONPREBUILT_TOOLCHAIN_CONFIGURATION` but the outcome was the same. 

Is there a way to have Bazel use the JavaBuilder that is being built in my source?

**Comment by cushon** [comment]
> Is there a way to have Bazel use the JavaBuilder that is being built in my source?

Yes, there's one more step that's need to use a newer build of JavaBuilder: https://github.com/bazelbuild/java_tools/issues/43#issuecomment-1346822307

**Comment by somethingvague** [comment]
I managed to get this working on sample project https://github.com/somethingvague/bazel-jdk19-coverage-repro/tree/repro with a branch on my bazel fork which updates java_tools https://github.com/somethingvague/bazel/tree/jacoco-asm-upgrade-repro

ASM needed to be upgraded to 9.3.

If you think the repro looks correct please take a look at PR #17514

**Comment by somethingvague** [comment]
Any thoughts on this issue please?

**Comment by cushon** [comment]
Sorry, the mechanics of the upgrade look good, I didn't realize it wasn't passing tests yet.

I am not sure if this is relevant or not, but internally we're using a newer jaococ version than the last tagged release (specifically `4d09eceb478338680ca87c38e8b282035a3b5abd`), there are some changes to support JDK 19 that haven't been released yet. We're also using ASM 9.4. I'd be curious to see if using the latest versions makes a difference.

**Comment by somethingvague** [comment]
https://github.com/somethingvague/bazel/commit/2e3f566ff80f46cd6a820c8c0b13a973e9ee32ec on the [forked bazel repro branch](https://github.com/somethingvague/bazel/tree/jacoco-asm-upgrade-repro) upgrades jacoco to https://github.com/jacoco/jacoco/commit/4d09eceb478338680ca87c38e8b282035a3b5abd and ASM 9.4. Unfortunately I get the same error in https://github.com/bazelbuild/bazel/issues/16412#issuecomment-1433087461 when running on the [test project](https://github.com/somethingvague/bazel-jdk19-coverage-repro/tree/repro).

Unsure if it's anything to do with the java toolchain or bazel configuration on the [test project](https://github.com/somethingvague/bazel-jdk19-coverage-repro/tree/repro). Would you mind taking a look please?

**Comment by cushon** [comment]
I was able to reproduce and have a possible workaround, can you verify this resolves the NPE for you?

```diff
diff --git a/src/java_tools/junitrunner/java/com/google/testing/coverage/ClassProbesMapper.java b/src/java_tools/junitrunner/java/com/google/testing/coverage/ClassProbesMapper.java
index 0633e1acf2..be814fe903 100644
--- a/src/java_tools/junitrunner/java/com/google/testing/coverage/ClassProbesMapper.java
+++ b/src/java_tools/junitrunner/java/com/google/testing/coverage/ClassProbesMapper.java
@@ -52,7 +52,6 @@ public class ClassProbesMapper extends ClassProbesVisitor implements IFilterCont
   public ClassProbesMapper(String className) {
     classLineToBranchExp = new TreeMap<Integer, BranchExp>();
     stringPool = new StringPool();
-    className = stringPool.get(className);
   }

   @Override
@@ -80,6 +79,7 @@ public class ClassProbesMapper extends ClassProbesVisitor implements IFilterCont
       String signature,
       String superName,
       String[] interfaces) {
+    className = stringPool.get(name);
     superClassName = stringPool.get(name);
   }
```

**Comment by somethingvague** [comment]
Thanks for this, it resolves the NPE. 

I have updated PR https://github.com/bazelbuild/bazel/pull/17514 to include JaCoCo v0.8.8, ASM 9.4, + the fix in https://github.com/bazelbuild/bazel/issues/16412#issuecomment-1464627828. 

I have confirmed it works with the subsequent `BUILD.java_tools` changes and the `remote_java_tools` repository overridden. Please let me know the next steps.

**Comment by somethingvague** [comment]
Thanks for merging, PR 2 of 3 raised https://github.com/bazelbuild/bazel/pull/17785

**Comment by cushon** [comment]
Personally I would be fine with trying JaCoCo snapshot builds.

> Also, do you think the mechanics of the 3 stage change to upgrade JaCoCo could be optimized in future?

@comius do you have any thoughts on options for streamlining the update process? (The 3-stage process referred to is the one documented in https://github.com/bazelbuild/bazel/blob/28001f6109ede0bd28ec00eb8d1a59d30cdb3bde/third_party/java/jacoco/README.md)

**Comment by hvadehra** [comment]
> streamlining the update process

There is an ongoing effort (by @meteorcloudy ) to empty `third_party`  and fetch the deps from maven: https://github.com/bazelbuild/bazel/blob/2a3ab5c45b42321cf1495be7e294e5ec01298ca1/WORKSPACE#L650 

However, for now this is only being done for dependencies that only require class jars . Doing this for dependencies that also need source jars, while possible, is yet to figured out. Once that happens though, upgrading versions can happen in a single PR with other changes.

**Comment by cushon** [comment]
That sounds great, although there may still be some added complexity here since we're carrying patches for modifications to JaCoCo.

**Comment by somethingvague** [comment]
@hvadehra makes sense, thanks for explaining.

@cushon I was able to verify that Bazel HEAD + JaCoCo 0.8.8  produces coverage data for Java 20 features built with a JDK 20 toolchain, though I'm not confident the coverage data is meaningful. Should we push ahead with upgrading JaCoCo to 0.8.9-SNAPSHOT on https://github.com/bazelbuild/bazel/pull/17836? (I've also confirmed this version works)

**Comment by meteorcloudy** [comment]
@cushon Can you elaborate a bit more on how those patches are applied to the jar files? Do we still need those patches after upgrading to a new JaCoco version? Can we upstream those changes?

**Comment by cushon** [comment]
> Can you elaborate a bit more on how those patches are applied to the jar files?

I would do something like https://github.com/bazelbuild/bazel/issues/16412#issuecomment-1405364155. I think @comius did the first Bazel update that used those patches in a0dec280808b1fe319aeccd11adb8734d6ea9528 and may have additional context.

> Can we upstream those changes?

I tried: https://github.com/jacoco/jacoco/issues/1151

> Do we still need those patches after upgrading to a new JaCoco version? 

JaCoCo hasn't changed. At this point support for condy should be more ubiquitous, so I think it's worth trying to drop that patch.

**Comment by somethingvague** [comment]
I've confirmed 0.8.9-SNAPSHOT with updated `BUILD.java_tools` works against my repro project so I've updated https://github.com/bazelbuild/bazel/pull/17836.

Also, I noticed Bazel pre-release [7.0.0-pre.20230316.2](https://github.com/bazelbuild/bazel/releases/tag/7.0.0-pre.20230316.2) does not include https://github.com/bazelbuild/bazel/pull/17785/commits/c22f29b7cb19d5c73b1d54d5133852ca0d9d98ba updating `BUILD.java_tools` to JaCoCo 0.8.8, when do you think this might be released?

**Comment by somethingvague** [comment]
I see that the latest pre-release includes the change. I notice that Bazel 7 is targeted for late 2023 vhttps://bazel.build/about/roadmap#bazel_70_release , is there a chance of this being released in a 6.x version?
