### ISSUE TITLE
Incorrect -isystem usage for non-system paths

### ISSUE THREAD

**Issue by gustavla** [bazelbuild/bazel#1642]
This a subtle but critical bug that showed up as a compilation error in Tensorflow (https://github.com/tensorflow/tensorflow/issues/3743). It can be summarized as follows: bazel reports that certain files were not declared when they clearly were. Long story short, non-system paths are being added to `gcc -M` as `-isystem` and not `-I`, which results in fatal errors in certain situations.

### The Error
Upon inspecting the `.pic.d` file of the offending file, I kept seeing absolute paths that corresponded to the files that bazel was complaining about. I tracked the error down to `CppCompileAction.discoverInputsFromDotdFiles` and the if statement starting with `execPathFragment.isAbsolute()` ([CppCompileAction:955](https://github.com/bazelbuild/bazel/blob/936c2c2c815b64525bc6d3c6ac8f049655589370/src/main/java/com/google/devtools/build/lib/rules/cpp/CppCompileAction.java#L955)). It only allows two kinds of absolute paths: system paths or paths starting with whatever is in `execRoot` (although even this is referred to as "funky but tolerable"). The offending files were absolute paths but did not start with `execRoot`, so let's explore how they got in there.

### The Cause
The `.d` files are generated by bazel making a subprocess call to `gcc -M`. This happens in `CppCompileAction`. It turns out that the commands that bazel generated for me used `-isystem` for non-system paths (instead of `-I`). Let's see what behavior in gcc causes this to be a problem for bazel:
```
$ cd /var/tmp
$ mkdir foo
$ touch foo/inc.h
$ mkdir abcdefghijklmnopqrustvwxyz
$ ln -s /var/tmp/foo abcdefghijklmnopqrustvwxyz/
$ echo '#include "inc.h"' > code.cc
```
Now, let's generate auto-dependency output for this toy example:
```
$ gcc -M -isystem abcdefghijklmnopqrustvwxyz code.cc
code.o: code.cc \
 /var/tmp/foo/inc.h
```
Absolute path! Note that the long directory name is **not included** since it **resolves symbolic links**. This is key. Now let's rename the long directory and try again:
```
$ mv abcdefghijklmnopqrustvwxyz abc
$ gcc -M -isystem abc code.cc
code.o: code.cc \
 abc/inc.h
```
Relative! What happened? It turns out that GNU gcc picks between the relative path and the resolved absolute path **depending on which one is shortest** (fascinating!). You can demonstrate this by adding back one letter at a time and see when it switches back to absolute paths. A tie will result in a relative path.

I have tested this on various setups (adaptive meaning it will pick the shortest):

Compiler | Platform | Option | Behavior
---|---|---|---
gcc 4.8.5 | CentOS | `-isystem` | adaptive
gcc 4.9.2 | CentOS | `-isystem` | adaptive
gcc 6.1.0 | Mac | `-isystem` | adaptive
clang 7.3.0 | Mac | `-isystem` | relative
* | * | `-iquote` | relative
* | * | `-I` | relative

The behavior persists between many versions of gcc, but clang for instance does not have this behavior. If I change to the related options `-iquote` or `-I`, I always get relative paths. Note that `-isystem` is an alternative to `-I` that treats the paths as system paths, so the fact that it is used here for non-system paths can be considered **a bug in bazel**.

### The Bug
There are plenty of places in the code base that are careful about using `-isystem` for system paths and `-I` for the regular include paths, so why am I seeing no `-I` and all `-isystem` in the subprocess calls?

Take a look at where system and regular include paths are added for C++ compilation ([CcLibraryHelper.java:1118](https://github.com/bazelbuild/bazel/blob/936c2c2c815b64525bc6d3c6ac8f049655589370/src/main/java/com/google/devtools/build/lib/rules/cpp/CcLibraryHelper.java#L1118)). If I print those, it turns out that `includeDirs` is empty and all the `systemIncludeDirs` contains non-system paths. I trace this back to [CcLibraryHelper.java:339](https://github.com/bazelbuild/bazel/blob/936c2c2c815b64525bc6d3c6ac8f049655589370/src/main/java/com/google/devtools/build/lib/rules/cpp/CcLibraryHelper.java#L339) where only system paths are populated. Those are in turn populated from `CcCommon.getSystemIncludeDirs`, which iterates the attribute `includes` (that includes only non-system paths in my Tensorflow example) and skips paths with absolute paths ([CcCommon.java:392](https://github.com/bazelbuild/bazel/blob/936c2c2c815b64525bc6d3c6ac8f049655589370/src/main/java/com/google/devtools/build/lib/rules/cpp/CcCommon.java#L392)).

### The Fix
The immediate ugly fix is to name your cache directory really long. This will make the relative paths shorter and thus avoid the absolute paths.

I am not entirely sure of what the correct fix is yet. If I populate the `includeDirs` instead so that the `-isystem` are switched to `-I`, then I am noticing that certain files that were registered using an `includes` directive in a `BUILD` file all of a sudden are not recognized. For Tensorflow, this first happens to `gif_lib_private.h` and `gif_hash.h`. If I try adding these to `hdrs` in `gif.BUILD` (shouldn't they be anyway?), I can get past it. There are more after that though and I imagine you don't want a change that will break things downstream.

Another solution is perhaps to allow two absolute paths (the execroot one and the regular one). I have not experimented with this and I don't know enough yet about how to `execRoot` really works. A third option might be to turn this behavior off in gcc, but I am unaware of such an option.

I'm happy to try to put together a PR with whatever solution is agreed upon.

**Comment by bsilver8192** [comment]
I've seen this behavior before, and adding `compiler_flag: "-fno-canonical-system-headers"` to the CROSSTOOL fixed it. @lberki did this for Bazel's builtin CROSSTOOL in 763f1397155fc7c12e1f1071a1bc942f91b867c4, but it looks like it hasn't made it to cc_configure.bzl which I think should add that if the compiler supports it.

This whole "choose the shortest of a few different ways of manipulating the path to write in the .d file" behavior of GCC seems to be pretty poorly documented, and the different behavior with `-I` and `-isystem` surprises me, but the whole thing surprised me too, so...

**Comment by bsilver8192** [comment]
On second thought, that takes less time to write than to type that comment. Review sent out as [Ia05788243d0128ea4921f12c437ef6cebd83a4ff](https://bazel-review.googlesource.com/#/q/Ia05788243d0128ea4921f12c437ef6cebd83a4ff).

@gustavla: it looks like you don't have a Gerrit account, so I'll ask here: can you take a look at that change?

**Comment by gustavla** [comment]
I still get a build error after this change. The paths are still absolute in the `.d` file, so I don't think the compiler flag was added. I confirmed though that gcc gives me relative paths if I add`-fno-canonical-system-headers`.

**Comment by gustavla** [comment]
What looks to be happening is that `-fno-canonical-system-headers` is indeed part of the subprocess call. However, the call runs a Python script in Tensorflow (`third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc`) that generates the actual call from its argument list. However, it does not acknowledge and propagate `-fno-canonical-system-headers` when doing this.

This puts the blame back on Tensorflow and I have confirmed that this build error can be fixed by editing this Tensorflow Python script. Actually, even reverting the latest change made by @bsilver8192, `-fno-canonical-system-headers` is still included, so at least from my perspective, there is nothing that needs to be updated in bazel and I will thus close this issue. I'll leave it to you @bsilver8192 to judge whether or not the suggested change is still necessary.

I am re-opening the Tensorflow issue at https://github.com/tensorflow/tensorflow/issues/3743.

**Comment by bsilver8192** [comment]
Thanks for the update. Looks to me like tensorflow is using a hard-coded CROSSTOOL which already has the flag, but somebody's going to hit this sooner or later with cc_configure so my change adding it there is still a good idea.

**Comment by gustavla** [comment]
Sounds reasonable.
