### ISSUE TITLE
[Mirror] zstd-jni v1.5.2-3

### ISSUE THREAD

**Issue by sluongng** [bazelbuild/bazel#16436]
### Please list the URLs of the archives you'd like to mirror:

Please help mirror `zstd-jni v1.5.2-3` to help with https://github.com/bazelbuild/bazel/pull/16394

URL: https://github.com/luben/zstd-jni/archive/refs/tags/v1.5.2-3.zip

**Comment by sgowroji** [comment]
Below mirror artifact : 
https://mirror.bazel.build/github.com/luben/zstd-jni/archive/refs/tags/v1.5.2-3.zip
