### ISSUE TITLE
global archive_override does not support patch_cmds as implied by docs

### ISSUE THREAD

**Issue by pjk25** [bazelbuild/bazel#16441]
### Description of the bug:

Using `patch_cmds` with `archive_override` yields

```
Starting local Bazel server and connecting to it...
ERROR: Traceback (most recent call last):
	File "<root>/MODULE.bazel", line 52, column 17, in <toplevel>
Error in archive_override: archive_override() got unexpected keyword argument 'patch_cmds' (did you mean 'patches'?)
```

https://bazel.build/rules/lib/globals#archive_override suggests the attribute should be supported.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a directory with an empty `WORKSPACE` and empty `BUILD.bazel`.

Create a `MODULE.bazel` with:

```
module(
    name = "patch_cmds_demo",
    version = "1.0.0",
)

bazel_dep(
    name = "rules_erlang",
    version = "3.7.2",
)

archive_override(
    module_name = "rules_erlang",
    urls = [
        "https://github.com/rabbitmq/rules_erlang/archive/refs/heads/main.zip",
    ],
    strip_prefix = "rules_erlang-main",
)
```

run `bazel build //... --experimental_enable_bzlmod` with success.

Add an `patch_cmds` to `MODULE.bazel` `archive_override`:

```
archive_override(
    module_name = "rules_erlang",
    urls = [
        "https://github.com/rabbitmq/rules_erlang/archive/refs/heads/main.zip",
    ],
    patch_cmds = ["echo hello"],
    strip_prefix = "rules_erlang-main",
)
```

run `bazel build //... --experimental_enable_bzlmod` and see error.

### Which operating system are you running Bazel on?

macos

### What is the output of `bazel info release`?

release 5.3.1

**Comment by meteorcloudy** [comment]
The `patch_cmds` attribute is only added recently at HEAD, it'll be available in 6.0 but will not be backported to 5.x, so please try with Bazel@HEAD
