### ISSUE TITLE
Error message for `%sysroot%` refers to nonexistent option

### ISSUE THREAD

**Issue by jfirebaugh** [bazelbuild/bazel#16447]
### Description of the bug:

If you use an include directory that contains the prefix `%sysroot%` with a toolchain that does not pass a `builtin_sysroot` value to [`create_cc_toolchain_config_info`](https://bazel.build/rules/lib/cc_common#create_cc_toolchain_config_info), then Bazel [issues the following error](https://github.com/bazelbuild/bazel/blob/8e9b667961fbb4e704c90a6926f2fe1594b09ebe/src/main/java/com/google/devtools/build/lib/rules/cpp/CcToolchainProviderHelper.java#L311):

> A %sysroot% prefix is only allowed if the default_sysroot option is set

The only instance of `default_sysroot` in the Bazel codebase is this error message; I don't think this option actually exists. Presumably, the error message means to reference `builtin_sysroot`.

**Comment by sgowroji** [comment]
Hello @jfirebaugh, Could you please provide minimal steps to reproduce the above issue with sample code changes. Thanks!

**Comment by jfirebaugh** [comment]
@sgowroji I don't think it's really necessary because I linked to the error message in the source, and the issue is self-evident.
