### ISSUE TITLE
"Cycle detected but could not be properly displayed due to an internal problem. Please file an issue."

### ISSUE THREAD

**Issue by pjk25** [bazelbuild/bazel#16452]
### Description of the bug:

This occurs when a platform is chosen that affects toolchain resolution, in the context of bzlmod.

Given the project in question, it's not clear to me there actually is a cycle. The implication from the logs to me is that a `platform` target depends on a `constraint_value`, and vice versa, but that is not how I understand platforms to work.

```
ERROR: Cycle detected but could not be properly displayed due to an internal problem. Please file an issue. Raw display: topLevelKey: ConfiguredTargetKey{label=//:app_file, config=BuildConfigurationValue.Key[5b92fcf9c061d0d0def8b5d2a0e592c565715b131b62f17b29518a583ae6f3a2]}
alreadyReported: false
path to cycle:
ConfiguredTargetKey{label=//:app_file, config=BuildConfigurationValue.Key[5b92fcf9c061d0d0def8b5d2a0e592c565715b131b62f17b29518a583ae6f3a2]}
ToolchainContextKey{configurationKey=BuildConfigurationValue.Key[5b92fcf9c061d0d0def8b5d2a0e592c565715b131b62f17b29518a583ae6f3a2], requiredToolchainTypeLabels=[@rules_erlang.override//tools:toolchain_type], execConstraintLabels=[], forceExecutionPlatform=Optional.empty, debugTarget=false}
cycle:
ConfiguredTargetKey{label=//bzl/platforms:erlang_linux_25_platform, config=BuildConfigurationValue.Key[5b92fcf9c061d0d0def8b5d2a0e592c565715b131b62f17b29518a583ae6f3a2]}
ConfiguredTargetKey{label=@rules_erlang.override.erlang_config.erlang_config//:erlang_25, config=BuildConfigurationValue.Key[5b92fcf9c061d0d0def8b5d2a0e592c565715b131b62f17b29518a583ae6f3a2]}
ToolchainContextKey{configurationKey=BuildConfigurationValue.Key[5b92fcf9c061d0d0def8b5d2a0e592c565715b131b62f17b29518a583ae6f3a2], requiredToolchainTypeLabels=[], execConstraintLabels=[], forceExecutionPlatform=Optional.empty, debugTarget=false}
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I'm not sure what is the simplest case yet. Since analysis fails, it's hard to trim this down. The project in question is OSS, so I could push a branch that demonstrates it, if needed.

### Which operating system are you running Bazel on?

macos

### What is the output of `bazel info release`?

release 5.3.1

**Comment by pjk25** [comment]
I am also able to reproduce this without bzlmod

**Comment by pjk25** [comment]
I have narrowed this down, the cycle occurs with `rules_erlang 3.7.2`, but not with `rules_erlang 3.6.3`. I'll be taking a look at the diff.

**Comment by pjk25** [comment]
rules_erlang is probably not the cause. I forgot that there are other changes at play, mainly moving dependencies from a module extension to top level `bazel_dep`s

**Comment by katre** [comment]
Can you share your repository, or a minimized reproduction? It's unclear to me from the cycle report exactly what's wrong, but it seems to be related to platform `//bzl/platforms:erlang_linux_25_platform` and I'd like to see how that is declared.

**Comment by pjk25** [comment]
https://github.com/rabbitmq/ra will repro this if the `rules_erlang` version in the MODULE.bazel is updated to `3.7.2`. With `bazel test //... --config=rbe-25`, it will fail. `bazel test //...` will not fail analysis, but will probably fail later if you don't have erlang.

**Comment by katre** [comment]
Thanks, I'll take a look.

**Comment by pjk25** [comment]
replacing the selects with the `//conditions:default` value didn't seem to make a difference

**Comment by pjk25** [comment]
I think I have some more info on this.

`rules_erlang` contains a repository rule, `erlang_config`, that generates constraints and platforms according to the host erlang and any erlang versions that should be build internally in bazel. They are generated in such a way that it's intended to be possible to be able to target an erlang major, matching the first of any erlang minors of that major.

Here is an example of the generated BUILD file:

```starlark
load("@bazel_skylib//lib:selects.bzl", "selects")

package(
    default_visibility = ["//visibility:public"],
)

constraint_setting(
    name = "erlang_internal_external",
    default_constraint_value = ":erlang_external",
)

constraint_setting(
    name = "erlang_version",
    default_constraint_value = ":erlang_25_0",
)

constraint_value(
    name = "erlang_external",
    constraint_setting = ":erlang_internal_external",
)

constraint_value(
    name = "erlang_internal",
    constraint_setting = ":erlang_internal_external",
)

constraint_value(
    name = "erlang_25_0",
    constraint_setting = ":erlang_version",
)

platform(
    name = "erlang_25_0_platform",
    constraint_values = [
        ":erlang_25_0",
    ],
)

constraint_value(
    name = "erlang_25_1",
    constraint_setting = ":erlang_version",
)

platform(
    name = "erlang_25_1_platform",
    constraint_values = [
        ":erlang_25_1",
    ],
)

selects.config_setting_group(
    name = "erlang_25",
    match_any = [":erlang_25_0", ":erlang_25_1"],
)

platform(
    name = "erlang_25_platform",
    constraint_values = [
        ":erlang_25",
    ],
)

constraint_value(
    name = "erlang_24_3",
    constraint_setting = ":erlang_version",
)

platform(
    name = "erlang_24_3_platform",
    constraint_values = [
        ":erlang_24_3",
    ],
)

selects.config_setting_group(
    name = "erlang_24",
    match_any = [":erlang_24_3"],
)

platform(
    name = "erlang_24_platform",
    constraint_values = [
        ":erlang_24",
    ],
)
```

My guess is that somehow there is an non-obvious cycle. Updating `//bzl/platforms:erlang_linux_25_platform` to:

```starlark
platform(
    name = "erlang_linux_25_platform",
    constraint_values = [
        "@erlang_config//:erlang_25_1",
    ],
    parents = ["@rbe//config:platform"],
)
```

allows things to build successfully, where we avoid the "give me any erlang 25" behavior.

**Comment by pjk25** [comment]
The `selects.config_setting_group` rules in the generated `erlang_config` repo were introduced in the diff between `rules_erlang 3.6.3 and 3.7.2`, so I think there is a good chance they are the culprit. I don't yet totally understand why that is the case yet.

**Comment by pjk25** [comment]
I had a look at the implementation of [selects.config_setting_group](https://github.com/bazelbuild/bazel-skylib/blob/main/lib/selects.bzl), and they expand to a chain of aliases with selects. This effectively puts selects in the plaform defintion, which, unsurprisingly, is not recommended: https://bazel.build/docs/configurable-attributes#faq-select-platforms

**Comment by pjk25** [comment]
I've narrowed down the breakage to `3.6.3` and `3.7.0`: https://github.com/rabbitmq/rules_erlang/compare/3.6.3...3.7.0

This commit introduced platforms with constraints that are `selects.config_setting_group` instances, and this does seem to be the source of the problem. I guess I can see how that's a cycle. The platform is setting a constraint_value, which due to the way the macro expands, depends on which constraint value is set, though the platform has of course not picked which constraint is set.

**Comment by katre** [comment]
@pjk25 after a lot of work, I've concluded that the only way to "fix" this is to make the situation impossible. Can you please test rules_erlang with a bazel containing https://github.com/bazelbuild/bazel/pull/16686 and let me know the results? It doesn't appear to be on our downstream projects pipeline. But it could be! [Add it here](https://github.com/bazelbuild/continuous-integration/issues/new?assignees=&labels=new-project&template=adding-your-project-to-bazel-ci.md&title=Request+to+add+new+project+%5BPROJECT_NAME%5D).

**Comment by pjk25** [comment]
I just gave this a try and it still fails.

I tried with [ra@cb29a0017d21efafc317d794fd77d2d148cf15c4](https://github.com/rabbitmq/ra/tree/cb29a0017d21efafc317d794fd77d2d148cf15c4) and this patch:
```diff
diff --git a/MODULE.bazel b/MODULE.bazel
index edf84d3..1ef09d7 100644
--- a/MODULE.bazel
+++ b/MODULE.bazel
@@ -5,7 +5,7 @@ module(
 
 bazel_dep(
     name = "rules_erlang",
-    version = "3.6.2",
+    version = "3.7.2",
 )
 
 erlang_config = use_extension(
```

And ran: `bazel build :erlang_app --config=rbe-25`

This is the bazel version:
```shell
bazel version
2022/11/10 09:12:14 Using unreleased version at commit f0fca21a876323f49233f43dab87b68bfa5dd879
Bazelisk version: development
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 01 00:00:00 1970 (0)
Build timestamp: Thu Jan 01 00:00:00 1970 (0)
Build timestamp as int: 0
```

which should contain the fix according to https://github.com/bazelbuild/bazel/commits/f0fca21a876323f49233f43dab87b68bfa5dd879

**Comment by pjk25** [comment]
and thanks for looking into this @katre

**Comment by pjk25** [comment]
Looking at the diff for https://github.com/bazelbuild/bazel/pull/16686 I can see how this issue might still remain. The `platform` rules the generated `@erlang_config` repository don't use `select` directly, only indirectly through the `alias`s produced by `selects.config_setting_group`.

**Comment by pjk25** [comment]
Oh, one more thing. My machine has erlang 25.0 installed, and that will affect which erlang version is selected as the default when `@erlang_config` is generated. Therefore, one might actually need erlang installed on the host machine to reproduce the issue.
