### ISSUE TITLE
[Mirror] rules_cc 2f8c04c04462ab83c545ab14c0da68c3b4c96191

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#16453]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/rules_proto/blob/fcfc67b0ab862ff54d312970548fb91b2b721334/proto/private/dependencies.bzl#L110

**Comment by sgowroji** [comment]
Please find the below mirror artifact

https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/2f8c04c04462ab83c545ab14c0da68c3b4c96191.tar.gz
