### ISSUE TITLE
[Android] `proguard_top` option failed to pass the target binary data runfile correctly

### ISSUE THREAD

**Issue by ThomasCJY** [bazelbuild/bazel#16471]
### Description of the bug:

When `build --proguard_top={proguard_binary_target}` is applied in android repo, the `data` file defined under `proguard_binary_target` didn't get correctly pulled into sandbox environment. 

```
java_binary(
    name = "proguard_binary_target",
    srcs = ["TestJavaBinary.java"],
    main_class = "example.java.src.main.com.example.TestJavaBinary",
    data = ["//data:data.txt"],
    jvm_flags = ["-Ddata.path=data/data.txt"], # The data/data.txt doesn't exist in sandbox if target is applied through --proguard_top option
)
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I created this sample repo with detailed repro steps. https://github.com/ThomasCJY/bazel_example/tree/jvmflag-example/simple

### Repro steps
First clone the test repo and go to the `simple` sub-project. In this test repo, we created this `TestJavaBinary` which will always fail if file with relative path `data/data.txt` cannot be located. 
We passed this file into the java binary using `data` and `jvm_flags = ["-Ddata.path=data/data.txt"],`.
Vanilla Java bin works if you call it directly through command line.
```bash
bazelisk build //example/java/src/main/com/example:test_java_bin
bazel-bin/example/java/src/main/com/example/test_java_bin

--- output ---
Data file exists! Content:example data2
```

However, the data class will not be picked up correctly if the binary is passed through `--proguard_top="//example/java/src/main/com/example:test_java_bin"` build flag

```bash
bazelisk build //:my_app

---- output ----
ERROR: /Users/jchen/Snapchat/Dev/bazel_local_test_example/simple/BUILD:8:15: Trimming binary with Proguard: //:my_app failed: (Exit 1): test_java_bin failed: error executing command (from target //:my_app) bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/example/java/src/main/com/example/test_java_bin -forceprocessing -injars bazel-out/darwin_arm64-fastbuild/bin/my_app_deploy.jar -outjars ... (remaining 11 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Exception in thread "main" java.lang.RuntimeException: No data file found under path - data/data.txt
        at example.java.src.main.com.example.TestJavaBinary.main(TestJavaBinary.java:18)
```

### Which operating system are you running Bazel on?

osx

### What is the output of `bazel info release`?

release 6.0.0-pre.20220922.1

**Comment by ahumesky** [comment]
The native Android rules have been deleted in bazel 8 and migrated to Starlark in https://github.com/bazelbuild/rules_android, if this is still an issue with the Starlark rules, please feel free to reopen there.
