### ISSUE TITLE
`JavaBuilder` Worker JVM does not use jvm flags specified with `--jvmopt`

### ISSUE THREAD

**Issue by arunkumar9t2** [bazelbuild/bazel#16486]
### Description of the bug:

When compiling a large Android app we are seeing too many open files error when using workers similar to issue described [here](https://github.com/bazelbuild/bazel/issues/15278). We would like to let worker JVMs use max open file descriptors limit specified on the shell with `-XX:-MaxFDLimit` JVM args. 

Ideally this can be done with `build --jvmopt="-XX:-MaxFDLimit"` which would attach the flag to `java_binary` targets or attach the jvm flag to `java_binary` as done [here](https://github.com/bazelbuild/rules_kotlin/pull/811)

But it seems that JavaBuilder receive their jvm flags from [toolchain](https://github.com/bazelbuild/bazel/blob/b12f3a93a55019276879bd2d3edbd201c913675a/src/main/java/com/google/devtools/build/lib/rules/java/JavaHeaderCompileActionBuilder.java#L359) and it does not add user specified flags like `java_binary` impl [does](https://github.com/bazelbuild/bazel/blob/b12f3a93a55019276879bd2d3edbd201c913675a/src/main/java/com/google/devtools/build/lib/rules/java/JavaBinary.java#L274).

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```python
genrule(
    name = "gen_sample",
    outs = ["Sample.java"],
    cmd = """
cat << EOF > $@
class Sample {{
}}
EOF
""",
)

java_library(
    name = "sample",
    srcs = ["Sample.java"],
    visibility = ["//visibility:public"],
)
```

```bash
bazelisk build //:sample --jvmopt="-XX:-MaxFDLimit"
```

```bash
> jcmd external/remote_java_tools/java_tools/JavaBuilder_deploy.jar VM.command_line
61633:
VM Arguments:
jvm_args: -XX:-CompactStrings --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.resources=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --patch-module=java.compiler=external/remote_java_tools/java_tools/java_compiler.jar --patch-module=jdk.compiler=external/remote_java_tools/java_tools/jdk_compiler.jar
java_command: external/remote_java_tools/java_tools/JavaBuilder_deploy.jar --persistent_worker
java_class_path (initial): external/remote_java_tools/java_tools/JavaBuilder_deploy.jar
Launcher Type: SUN_STANDARD
```

As shown above, user specified flags are not added to JavaBuilder's JVM

### Which operating system are you running Bazel on?

MacOS 12.6 (21G115)

### What is the output of `bazel info release`?

release 5.3.1

### Have you found anything relevant by searching the web?

- Requires https://github.com/bazelbuild/bazel/pull/15978
- Similar fix applied in rules_kotlin: https://github.com/bazelbuild/rules_kotlin/pull/848
- https://github.com/bazelbuild/bazel/issues/15278

**Comment by USB-05** [comment]
We have solved this issue by directly passing the flag to toolchain.
```
load(
    "@bazel_tools//tools/jdk:default_java_toolchain.bzl",
    "BASE_JDK9_JVM_OPTS",
    "DEFAULT_TOOLCHAIN_CONFIGURATION",
    "default_java_toolchain",
)

default_java_toolchain(
    name = "harness_no_fdLimit_jdk11_toolchain",
    configuration = DEFAULT_TOOLCHAIN_CONFIGURATION,  # One of predefined configurations
    jvm_opts = BASE_JDK9_JVM_OPTS + ["-XX:-MaxFDLimit"],  # Additional JDK options
    source_version = "11",
    target_version = "11",
)
```
