### ISSUE TITLE
Inconsistent naming convention in rctx.download_and_extract for `stripPrefix`

### ISSUE THREAD

**Issue by carlosgalvezp** [bazelbuild/bazel#16496]
### Description of the bug:

All arguments to `rctx.download_and_extract` are written in `snake_case` format, except `stripPrefix`. It should be renamed to `strip_prefix` for consistency.

**Comment by sgowroji** [comment]
Hello @carlosgalvezp, Can you point us more details on the above request like document links or any other references. Thanks!

**Comment by carlosgalvezp** [comment]
Hi @sgowroji ! Sure, the documentation is here:
https://bazel.build/rules/lib/repository_ctx#download_and_extract

You can see the function has an argument `stripPrefix`.

**Comment by fmeum** [comment]
For backwards compatibility, we could add a new parameter for the correct spelling while keeping the old but making it undocumented.

**Comment by carlosgalvezp** [comment]
@fmeum Perhaps mark it as deprecated?

**Comment by carlosgalvezp** [comment]
This creates a lot of confusion when you also use e.g. `cc_library`'s `strip_include_prefix`:
https://bazel.build/reference/be/c-cpp#cc_library.strip_include_prefix

**Comment by Wyverald** [comment]
yep, this is rather annoying. Should be fairly easy to fix though, so if anyone could send a PR, it would be greatly appreciated :)

**Comment by Mash707** [comment]
I have sent PR request , Can someone arrange a review for it

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 8.0.0 RC2](https://github.com/bazelbuild/bazel/releases/tag/8.0.0rc2). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=8.0.0rc2`. Thanks!
