### ISSUE TITLE
Bazel 6 regression: cc_library() targets do not collect runfiles from data dependencies correctly.

### ISSUE THREAD

**Issue by digit-google** [bazelbuild/bazel#16499]
### Description of the bug:

When trying to use the latest Bazel 6.0.0-pre.20220922.1 pre-release (or even ToT from 2022-10-18), our build rules actually fail to work properly. I could debug it to a regression when the implementation of `cc_library()` was switched from Java to Starlark.

I have uploaded a reproduction case, but a potential fix and my analysis of the problem at: https://github.com/digit-google/bazel-experiments/tree/main/runfiles/bazel6-data-deps-runfiles-regression

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/digit-google/bazel-experiments/tree/main/runfiles/bazel6-data-deps-runfiles-regression

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

6.0.0-pre.20220922.1

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

This also reproduces when building from source using the instructions at https://docs.bazel.build/versions/0.21.0/install-compile-source.html#build-bazel-using-bazel (using an existing Bazel binary).

Also applying my one-line patch to cc_library.bzl seems to solve the issue, but I didn't find instructions to run the regression test suite locally.

**Comment by oquenchil** [comment]
LGTM

I can send a change with David's solution and Fabian's addition.

**Comment by digit-google** [comment]
Thank you, I was not aware of #15043 but I agree that adding the DefaultInfo.files as well seems much more logical here (and that the fact that the Java implementation didn't collect them for CcLibrary was a bug).

**Comment by oquenchil** [comment]
Please take a look at the PR. I will write the proper attribution when merging internally.
