### ISSUE TITLE
Better Error for Build Generates Bash Command That Exceeds Max Argument Length

### ISSUE THREAD

**Issue by nathantchan** [bazelbuild/bazel#1650]
I had a build command that generated a bash command that was too long. However, the error reported by bazel was not very helpful:

```
ERROR: ./BUILD:5:1: error executing shell command: '...' failed: linux-sandbox failed: error executing command  ... (remaining 5 argument(s) skipped).
Target ... failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

We were eventually able to deduce it was an arg list too long error by executing the following command and using bash to run the dump:

```
bazel build :.. -s --jobs=1 --verbose_failures=true |& tee /tmp/dump
/tmp/dump: line 3: /usr/bin/env: Argument list too long
```

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
