### ISSUE TITLE
[Mirror] zlib-1.2.13

### ISSUE THREAD

**Issue by Vertexwahn** [bazelbuild/bazel#16511]
Please mirror https://zlib.net/zlib-1.2.13.tar.gz
should be available under "https://mirror.bazel.build/zlib.net/zlib-1.2.13.tar.gz"

Required here: https://github.com/nelhage/rules_boost/pull/270 and here: https://github.com/AcademySoftwareFoundation/openexr/pull/1288

**Comment by sgowroji** [comment]
Please verify the above it is mirrored. Fixed.
