### ISSUE TITLE
bazel run docker_build fails on osx

### ISSUE THREAD

**Issue by pcj** [bazelbuild/bazel#1651]
Running a [docker_build rule](http://bazel.io/docs/be/docker.html#using) should install the docker image like `docker load -i bazel-genfiles/.../image.tar`.  

Running this rule generates an executable bash script.  The script template from https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/docker/incremental_load.sh.tpl#L27-L28 assumes the presence of gnu sed.  BSD sed (osx) does not support the `-r` `--regexp-extended` flag and the script fails.

```sh
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

Fix could involve use awk instead, i.e. `docker version -f '{{.Server.Version}}' | awk -F\. '{ print $1 }'` that IIRC is more general-purpose for this task.

**Comment by mickeyreiss** [comment]
Here's a workaround for OS X that will work for me until #1716 is released:

```bash
brew install gnu-sed
PATH=/usr/local/opt/gnu-sed/libexec/gnubin/:$PATH bazel run //application:docker # My docker_build target
```
