### ISSUE TITLE
[Mirror] bzip2-1.0.8

### ISSUE THREAD

**Issue by Vertexwahn** [bazelbuild/bazel#16529]
Please mirror:

- https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz

Expected mirror URL:
- https://mirror.bazel.build/sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz

Intended use: 
- https://github.com/nelhage/rules_boost/pull/273

**Comment by sgowroji** [comment]
Please find the below mirror artifact
https://mirror.bazel.build/sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz
