### ISSUE TITLE
Some tests still require a `python` binary (Python 2)

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/bazel#16526]
### Description of the bug:

On our new M1 Mac Studio CI workers the following tests fail due to Python 2 no longer being installed by default:

- //src/test/shell/bazel:bazel_example_test fails with `io_bazel/src/test/shell/bazel/bazel_example_test: line 135: python: command not found` [log](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/0183fa35-2b92-4a37-a98f-cc52f0f2432c/src/test/shell/bazel/bazel_example_test/shard_1_of_3/test.log)
- //src/test/py/bazel:runfiles_test fails with `Could not find python binary: python` [log](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/0183fa35-2b92-4a37-a98f-cc52f0f2432c/src/test/py/bazel/runfiles_test/test.log)

Obviously it would be easy to fix them by installing Python 2. However, I'd argue that the right thing is to switch to Python 3 given that it's 2022.

### Which operating system are you running Bazel on?

MacOS monterey 12.6 (Bazel CI)

### What is the output of `bazel info release`?

5.3.2

**Comment by fweikert** [comment]
Some more failing tests:

- [//src/test/shell/bazel:python_version_test](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/0183fad8-e903-41d9-9390-287093f4c8fa/src/test/shell/bazel/python_version_test/test.log)
- [//src/test/shell/bazel:bazel_workspaces_test](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/0183fae5-7499-46b8-bccc-e52aeda9336f/src/test/shell/bazel/bazel_workspaces_test/test.log)
- [//src/test/shell/bazel:bazel_repository_cache_test](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/0183fae5-7499-46b8-bccc-e52aeda9336f/src/test/shell/bazel/bazel_repository_cache_test/shard_1_of_6/test.log)
- [//src/test/shell/bazel:external_integration_test](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/0183fae5-7499-46b8-bccc-e52aeda9336f/src/test/shell/bazel/external_integration_test/shard_1_of_15/test.log)
- [//src/test/shell/bazel:external_integration_test](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/0183fae5-7499-46b8-bccc-e52aeda9336f/src/test/shell/bazel/external_integration_test/shard_14_of_15/test.log)

**Comment by fweikert** [comment]
Most (all?) tests are actually PY3 compatible, i.e. a symlink to the python3 binary solved most of the problems.

//src/test/shell/bazel:python_version_test is the only remaining failing test since it requires a `python2` binary.

**Comment by rickeylev** [comment]
FYI: I recently (~Jan 2023) did some work cleaning out Python 2 in Bazel. The aforementioned tests are probably OK now (several look familiar from what I cleaned up). You should also be able to set `--incompatible_python_disable_py2=true` (with a recent bazel build) to fail earlier when a py2 target is detected.

**Comment by larsrc-google** [comment]
FWIW, several tests are failing this way today: https://buildkite.com/bazel/google-bazel-presubmit/builds/63119#01861694-4c8b-4d10-8232-67d46c3390cb

**Comment by fweikert** [comment]
`Could not find python binary`:
- //src/test/shell/bazel/android:android_instrumentation_test_integration_test_with_platforms: [log](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/018616c9-35e4-4faa-bba2-a48690131cbd/src/test/shell/bazel/android/android_instrumentation_test_integration_test_with_platforms/shard_1_of_4/test_attempts/attempt_1.log)
- //src/test/shell/bazel/android:android_instrumentation_test_integration_test:  [log](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/018616c9-35e4-4faa-bba2-a48690131cbd/src/test/shell/bazel/android/android_instrumentation_test_integration_test/shard_1_of_4/test_attempts/attempt_2.log)
- //src/test/shell/bazel/android:android_instrumentation_test_integration_test_with_head_android_tools: [log](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/018616c9-35e4-4faa-bba2-a48690131cbd/src/test/shell/bazel/android/android_instrumentation_test_integration_test_with_head_android_tools/shard_1_of_4/test_attempts/attempt_1.log)
- //src/test/shell/bazel/android:android_instrumentation_test_integration_test_with_head_android_tools: [log](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/018616c9-35e4-4faa-bba2-a48690131cbd/src/test/shell/bazel/android/android_instrumentation_test_integration_test_with_head_android_tools/shard_1_of_4/test_attempts/attempt_2.log)
- //src/test/py/bazel:runfiles_test: [log](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/018616c9-35e4-4faa-bba2-a48690131cbd/src/test/py/bazel/runfiles_test/test_attempts/attempt_1.log)

`Error occurred while attempting to use the default Python toolchain (@rules_python//python:autodetecting_toolchain).\nNeither 'python3' nor 'python' were found on the target platform's PATH`
- //tools/python:pywrapper_test: [log](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/018616c9-35e4-4faa-bba2-a48690131cbd/tools/python/pywrapper_test/test_attempts/attempt_1.log)

**Comment by rickeylev** [comment]
For pywrapper_test, this is some sort of issue with copying the `which` binary to another location. The basic gist of this test is this:
```
mkdir /tmp/testdir
cp /usr/bin/which /tmp/testdir
touch /tmp/testdir/python
cd /tmp/testdir
PATH=/tmp/testdir which python
```

When copied to another location, the `which` binary simply fails with `Killed: 9`. The only mention I found about this behavior is in https://apple.stackexchange.com/questions/258623/how-to-fix-killed-9-error-in-mac-os, which says something about the OS not liking the binary being elsewhere and failing if so.

In any case, this shouldn't be too hard to work around in the test. I'll prep a PR.

**Comment by rickeylev** [comment]
Looks like src/test/shell/bazel/remote_helpers.sh is another culprit using `python` (this time directly as part of a shell script, not via build rules). The file it's running looks like it's py3 compatible, so it probably just needs to be sed/awk'd to use `python3`

**Comment by rickeylev** [comment]
I wasn't able to get the android stuff working and I have to put this down for now, so won't be sending any more PRs on this for at least a few weeks. That said:

I did some grepping and saw some places where `--incompatible_use_python_toolchains` is being disabled. Removing that flag will probably Just Work. If not, it's fairly easy to define a custom toolchain that works for the tests (define a py_runtime(), define a py_runtime_pair() pointing to the runtime, define a toolchain() pointing to the pair, then use --extra_toolchains to point to the toolchain; see tools/python/toolchains internally for some examples, or contact me and I can help walk through it)

The `//src/test/shell/bazel:starlark_repository_test` test might be fixed now; I recall seeing remote_helpers mentioned in its failures; the previous commit might have fixed that.

**Comment by meteorcloudy** [comment]
@rickeylev @fweikert Are there any more tests left broken due to this issue?

**Comment by meteorcloudy** [comment]
Oh, I guess:
      - "-//src/test/shell/bazel/android:android_instrumentation_test_integration_test"
      - "-//src/test/shell/bazel/android:android_instrumentation_test_integration_test_with_head_android_tools"
      - "-//src/test/shell/bazel/android:android_instrumentation_test_integration_test_with_platforms"
