### ISSUE TITLE
Some Android shell tests don't build on Apple Silicon CI workers

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/bazel#16521]
### Description of the bug:

I'm working on adding M1 Mac Studio Ultra machines to our CI worker pool. These machines come with Android build-tools 31.0.0 since the older versions running on CI so far (28.0.2 and 30.0.3) cannot be installed on M1 machines.

Unfortunately this means that some of our Android shell tests started failing. This is due to 31.0.0 replacing dx with d8, but some of our tests still rely on dx.jar:

```
ERROR: /Users/buildkite/builds/bk-macstudio-1/bazel/google-bazel-presubmit/src/test/shell/bazel/android/BUILD:86:16: Middleman _middlemen/src_Stest_Sshell_Sbazel_Sandroid_Sproguard_Uintegration_Utest-runfiles failed: missing input file 'external/androidsdk/build-tools/31.0.0/lib/dx.jar', owner: '@androidsdk//:build-tools/31.0.0/lib/dx.jar'
```
(https://buildkite.com/bazel/google-bazel-presubmit/builds/60433#0183f649-476f-4153-bc42-673a96e5065a)

I've added some "magic" flags suggested by @ahumesky, but without any success:

```
--define=android_incremental_dexing_tool=d8_dexbuilder
--define=android_dexmerger_tool=d8_dexmerger
--nouse_workers_with_dexbuilder
```

So far this bug affects at least three tests:
- `//src/test/shell/bazel/android:android_integration_test`
- `//src/test/shell/bazel/android:desugarer_integration_test`
- `//src/test/shell/bazel/android:proguard_integration_test`

### Which operating system are you running Bazel on?

Bazel CI on MacOS monterey 12.6

### What is the output of `bazel info release`?

5.3.2

**Comment by meteorcloudy** [comment]
Please re-enable the failing tests in Bazel's [presubmit.yml](https://github.com/bazelbuild/bazel/blob/master/.bazelci/presubmit.yml) and [postsubmit.yml](https://github.com/bazelbuild/bazel/blob/master/.bazelci/postsubmit.yml) file after fixing them!

**Comment by meteorcloudy** [comment]
Looks like https://issuetracker.google.com/issues/190734097#comment23 is related.

@ahumesky @ted-xie Do you have any plan to fix this? I'm trying to make sure all Bazel integration tests work on arm64 mac so that we can deprecate Intel Mac machines in future.

**Comment by meteorcloudy** [comment]
We are not going to fix those tests since we are moving out android rules from Bazel
