### ISSUE TITLE
Apple Silicon: Some tests fail with '@bazel_tools//tools/cpp:everything' does not contain a toolchain for cpu 'darwin_arm64'

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/bazel#16525]
### Description of the bug:

- //src/test/java/com/google/devtools/build/lib/buildtool:KeepGoingTest: [log](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/0183fa35-2b92-4a37-a98f-cc52f0f2432c/src/test/java/com/google/devtools/build/lib/buildtool/KeepGoingTest/test.log)
- //src/test/java/com/google/devtools/build/lib/buildtool:DanglingSymlinkTest: [log](
https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/0183fa35-2b92-4a37-a98f-cc52f0f2432c/src/test/java/com/google/devtools/build/lib/buildtool/DanglingSymlinkTest/test.log)

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://buildkite.com/bazel/google-bazel-presubmit/builds/60478#0183fa35-2b92-4a37-a98f-cc52f0f2432c

### Which operating system are you running Bazel on?

MacOS monterey 12.6 (Bazel CI)

### What is the output of `bazel info release`?

5.3.2

**Comment by fweikert** [comment]
More failing tests:

- [//src/test/java/com/google/devtools/build/lib/buildtool:CompileOneDependencyIntegrationTest](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/0183fad8-e903-41d9-9390-287093f4c8fa/src/test/java/com/google/devtools/build/lib/buildtool/CompileOneDependencyIntegrationTest/test.log)
- [//src/test/java/com/google/devtools/build/lib/rules/objc:BazelJ2ObjcLibraryTest](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/0183fad8-e903-41d9-9390-287093f4c8fa/src/test/java/com/google/devtools/build/lib/rules/objc/BazelJ2ObjcLibraryTest/test.log)
- [//src/test/java/com/google/devtools/build/lib/skyframe/rewinding:RewindingTest](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/0183fad8-e903-41d9-9390-287093f4c8fa/src/test/java/com/google/devtools/build/lib/skyframe/rewinding/RewindingTest/shard_1_of_6/test.log)
- [//src/test/java/com/google/devtools/build/lib/buildtool:MiscAnalysisTest](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/0183fae5-7499-46b8-bccc-e52aeda9336f/src/test/java/com/google/devtools/build/lib/buildtool/MiscAnalysisTest/test.log)
- [//src/test/java/com/google/devtools/build/lib/rules/objc:ObjcRulesTests](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/0183fae5-7499-46b8-bccc-e52aeda9336f/src/test/java/com/google/devtools/build/lib/rules/objc/ObjcRulesTests/shard_1_of_20/test.log)

**Comment by meteorcloudy** [comment]
Please re-enable the failing tests in Bazel's [presubmit.yml](https://github.com/bazelbuild/bazel/blob/master/.bazelci/presubmit.yml) and [postsubmit.yml](https://github.com/bazelbuild/bazel/blob/master/.bazelci/postsubmit.yml) file after fixing them!
