### ISSUE TITLE
Add docs for concept of "yanked version"

### ISSUE THREAD

**Issue by hobofan** [bazelbuild/bazel#16538]
Yanked versions have recently been implemented (https://github.com/bazelbuild/bazel/issues/16180), and the first modules have been yanked as well. However there doesn't seem to be an section in the official documentation that explains the purpose and behaviour of yanked versions yet.

In order to provide a good user experience on https://registry.bazel.build as well and not leave users puzzled what a "yanked version" is, it would be good if we could link them to proper explanation.

**Comment by meteorcloudy** [comment]
This is documented in the BCR repo: https://github.com/bazelbuild/bazel-central-registry/tree/main/docs#yank-a-module-version

We'll probably also add doc on yanked version when we polish the Bzlmod doc on bazel.build.

**Comment by Wyverald** [comment]
This is done: https://bazel.build/external/module#yanked_versions
