### ISSUE TITLE
Recent test runner changes broke some tests

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#1654]
See the TODOs in junit/runner/model/TestSuiteModel.java.

**Comment by philwo** [comment]
Not sure about the details of this issue, but "recent change broke some tests" sounds like P0 and either rollback or immediate fix if trivial?

**Comment by ulfjack** [comment]
Ah, my bad. The code was changed such that the tests are ok but we need to investigate if there's more to do.

See Commit 20703c2667539202ca8fcbe93ebd9a5450c7e6ab.

**Comment by damienmg** [comment]
@ulfjack there is no repro nor clear instruction. Either update the bug or close it. I believe it should be closed since a P1 open since 3 months is probably not a P1

**Comment by ulfjack** [comment]
Irina made the original change, this issue is assigned to her, and she should have enough background to reproduce it. I'm just the messenger here.

**Comment by damienmg** [comment]
ping @iirina can we have a correct triaging of this issue? At least an update. a P0 opened since 3 months seems indicative of a probable non issue.

**Comment by iirina** [comment]
I investigated this a while ago and everything seemed fine, but I'll leave this open to investigate some more since now I have more background on the test runner. I lowered the priority for now.
