### ISSUE TITLE
Allow `cc_helper` to be consumed by end users

### ISSUE THREAD

**Issue by maxwellE** [bazelbuild/bazel#16546]
### Description of the feature request:

Currently [`cc_helper`](https://github.com/bazelbuild/bazel/blob/675172439552055398c480990e277bb2f39d6aaa/src/main/starlark/builtins_bzl/common/cc/cc_helper.bzl) contains generally useful functionality that should be publicly available to rulesets 

### What underlying problem are you trying to solve with this feature?

Preventing duplication of this logic across rulesets 

### Which operating system are you running Bazel on?

N/A

### What is the output of `bazel info release`?

N/A

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
N/A
```

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/rules_swift/pull/923/files

**Comment by oquenchil** [comment]
We are not planning to do this until we have finished starlarkifying the C++ rules. The future owners of the C++ ruleset can then properly review the functionality there to create a proper public API that may have be maintained for a long time. For now feel free to copy the code there.

**Comment by keith** [comment]
FYI this is in rules_cc now and intentional or not is public so it is usable now from starlark
