### ISSUE TITLE
Release 5.x - 'rules_jvm_external' not found in repo

### ISSUE THREAD

**Issue by cshsoft** [bazelbuild/bazel#16557]
INFO: Repository rules_jvm_external instantiated at:
  E:/opensource/lyra/WORKSPACE:143:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/cshsoft/_bazel_cshsoft/xcvtuzjs/external/bazel_tools/tools/build_defs/repo/http.bzl:370:31: in <toplevel>
DEBUG: Rule 'com_google_protobuf' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "fd8aabf32d1d1ae3319e280fed07aa6eb24d150d", shallow_since = "1614800268 -0800" and dropping ["tag"]
DEBUG: Repository com_google_protobuf instantiated at:
  E:/opensource/lyra/WORKSPACE:26:15: in <toplevel>
Repository rule git_repository defined at:
  C:/users/cshsoft/_bazel_cshsoft/xcvtuzjs/external/bazel_tools/tools/build_defs/repo/git.bzl:176:33: in <toplevel>
WARNING: Download from https://github.com/bazelbuild/rules_jvm_external/archive/4.0.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'rules_jvm_external':
   Traceback (most recent call last):
        File "C:/users/cshsoft/_bazel_cshsoft/xcvtuzjs/external/bazel_tools/tools/build_defs/repo/http.bzl", line 130, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_jvm_external/archive/4.0.zip] to C:/users/cshsoft/_bazel_cshsoft/xcvtuzjs/external/rules_jvm_external/temp8625613266728458292/4.0.zip: GET returned 404 Not Found
ERROR: E:/opensource/lyra/WORKSPACE:143:13: fetching http_archive rule //external:rules_jvm_external: Traceback (most recent call last):
        File "C:/users/cshsoft/_bazel_cshsoft/xcvtuzjs/external/bazel_tools/tools/build_defs/repo/http.bzl", line 130, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_jvm_external/archive/4.0.zip] to C:/users/cshsoft/_bazel_cshsoft/xcvtuzjs/external/rules_jvm_external/temp8625613266728458292/4.0.zip: GET returned 404 Not Found
ERROR: Error computing the main repository mapping: no such package '@rules_jvm_external//': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_jvm_external/archive/4.0.zip] to C:/users/cshsoft/_bazel_cshsoft/xcvtuzjs/external/rules_jvm_external/temp8625613266728458292/4.0.zip: GET returned 404 Not Found

**Comment by sgowroji** [comment]
Hello @cshsoft, Could you please provide more details on the above request. Thanks!

**Comment by Wyverald** [comment]
This looks like the URL is returning a 404 for you. (It worked fine for me.) Please check your network settings.

**Comment by cshsoft** [comment]
I'm try to build lyra (An audio encoder ) on windows ,this project using bazel build，when i try to build it,  an error occurred, In my experience, the hint is that this file is not found in the repo,   https://github.com/bazelbuild/rules_jvm_external/archive/4.0.zip,  In fact, the file does not exist,  I'm in downtown Shenzhen, China,  Even though we've been dubbed the world's largest LAN,  but However, access to external networks is fine,  Because I have a VPN on google cloud server,  Please forgive my Chinglish... thanks
