### ISSUE TITLE
How to get valgrind xml report

### ISSUE THREAD

**Issue by chenqingguo** [bazelbuild/bazel#16554]
Bazel version is 5.3.1. Here is my test job
`bazel test --test_verbose_timeout_warnings --run_under='valgrind --tool=memcheck --leak-check=full --xml=yes --xml-file=valgrind.xml'  --test_output=streamed //...`
The tests running is ok, but where is the valgrind.xml that should be produced?
Anyone can help? Thanks.

**Comment by sgowroji** [comment]
@chenqingguo Did you check it in bazel-testlogs ?  If not did you see any error stacktrace ?

**Comment by chenqingguo** [comment]
@sgowroji I checked bazel-testlogs as well as bazel-bin&bazel-doe&bazel-out, which doe is my project name. My gtest running is ok, And I didn't see any error stacktrace.
If I run this `bazel test --test_verbose_timeout_warnings --run_under='valgrind --tool=memcheck --leak-check=full' --test_output=streamed //...`,I can see valgrind's memory check result printing on my terminal. I think every thing is ok, but can not produce report file.

**Comment by meteorcloudy** [comment]
@chenqingguo Bazel will run the test in a sandbox, and it sandbox root will be deleted after running the test, that's why you cannot find this file. 

I found out by using `--run_under="pwd"` and check the output in test log:
```
$ bazel test --run_under="pwd" examples/cpp:hello-success_test --test_output=all
$ cat bazel-out/darwin_arm64-fastbuild/testlogs/examples/cpp/hello-success_test/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="examples/cpp/hello-success_test" tests="1" failures="0" errors="0">
    <testcase name="examples/cpp/hello-success_test" status="run" duration="0" time="0"></testcase>
      <system-out>
Generated test.log (if the file is not UTF-8, then this may be unreadable):
<![CDATA[exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //examples/cpp:hello-success_test
-----------------------------------------------------------------------------
/private/var/tmp/_bazel_pcloudy/829441223e9fec5a5a2e3d1dd743fdf0/sandbox/darwin-sandbox/5/execroot/io_bazel/bazel-out/darwin_arm64-fastbuild/bin/examples/cpp/hello-success_test.runfiles/io_bazel]]>
      </system-out>
    </testsuite>
</testsuites>
```

**Comment by meteorcloudy** [comment]
This is not a Bazel bug, so I'm closing it
