### ISSUE TITLE
"bazel build ..." fails with any project.

### ISSUE THREAD

**Issue by digit-google** [bazelbuild/bazel#16553]
### Description of the bug:

Trying to build the "..." target with any project, even simple one, fails with messages related to labels used in @bazel_tools being invalid (e.g. `//tools/build_rules:java_rules_skylark.bzl`, but the exact error can change between build attempts, or bazel projects / releases).

An example when trying to run one of the projects from https://github.com/digit-google/bazel-experiments

```sh
Starting local Bazel server and connecting to it...
ERROR: error loading package 'bazel-transitions-4/external/bazel_tools/third_party/jformatstring': Label '//tools/build_rules:java_rules_skylark.bzl' is invalid because 'tools/build_rules' is not a package; perhaps you meant to put the colon here: '//:tools/build_rules/java_rules_skylark.bzl'?
INFO: Elapsed time: 2.434s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (39 packages loaded)
    currently loading: src ... (100 packages)
```
Inspection shows that `$OUTPUT_BASE/external/bazel_tools` is a symlink to the Bazel builtin embedded_tools directory that was extracted on first use, i.e.:

```sh
O=$(bazel info output_base)
ls -l $O/external/bazel_tools
lrwxrwxrwx 1 digit primarygroup 110 Oct 26 10:16 /usr/local/google/home/digit/.cache/bazel/_bazel_digit/83858c5ed34963ff9281ded806ea9696/external/bazel_tools -> /usr/local/google/home/digit/.cache/bazel/_bazel_digit/install/cbf972266931ad9fad1857441b832915/embedded_tools
```

There, we can see that the file `@bazel_tools/third_party/jformatstring/BUILD` contains lines like:

```python
load("//tools/build_rules:java_rules_skylark.bzl", "bootstrap_java_library")
```

So it looks like the `//` is not interpreted correctly as relative to the current @bazel_tools workspace for some reason, (because `@bazel_tools/tools/build_rules/BUILD` does exis)t, even though the file `@bazel_tools/WORKSPACE` does exist and contains:

```python
workspace(name = "bazel_tools")
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run `bazel build ...` from any Bazel project.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

5.3.2 but also tried with 6.0.0-pre.20221012.2

**Comment by fmeum** [comment]
I ran `USE_BAZEL_VERSION=5.3.2 bazel build ...` in some of the projects in your repo (`bazel6-data-deps-runfiles-regression`, `custom-flags-with-define`) and it worked (with 5.3.2).

Could you share more concrete instructions that reproduce this issue for you?

**Comment by digit-google** [comment]
Sure, try https://github.com/digit-google/bazel-experiments/tree/main/pic-vs-pie/transitions-4

We also see the problem in the Fuchsia platform build (but you don't want to check out our sources): https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=113184

**Comment by fmeum** [comment]
Instead of the failure you described, I get:
```
bazel-experiments on  main on ☁️   
❯ cd pic-vs-pie/transitions-4 && USE_BAZEL_VERSION=5.3.2 bazelisk build ...
INFO: Invocation ID: 16f6fe71-e95a-4db7-ac9d-ee0434ee787c
ERROR: file 'src/common.cc' is generated by these conflicting actions:
Label: //src:generate_common, //src:generate_common.genrule
RuleClass: _wrap_unique_genrule rule, genrule rule
Configuration: 6167a43bee81d7c4ceebdf8986e0027b728c609e76e2c99eb3032efb76afa9e5
Mnemonic: Symlink, Genrule
Action key: d7773cd91ffd7932031eb8962471d065e41bfad384f2ed5d8d1925666f92ac3f, bea42f16cc513106d88e8f88f0739b713931b9efa6879cbd42f015a9d0d5e4d1
Progress message: Creating symlink bazel-out/k8-fastbuild/bin/src/common.cc, Generating common library sources //src:generate_common.genrule
PrimaryInput: File:[[<execution_root>]bazel-out/k8-fastbuild/bin]src/common.cc, File:[/home/fhenneke/git/bazel-experiments/pic-vs-pie/transitions-4[source]]src/generate_common_lib.sh
PrimaryOutput: File:[[<execution_root>]bazel-out/k8-fastbuild/bin]src/common.cc, File:[[<execution_root>]bazel-out/k8-fastbuild/bin]src/common.h
ERROR: file 'src/common.h' is generated by these conflicting actions:
Label: //src:generate_common, //src:generate_common.genrule
RuleClass: _wrap_unique_genrule rule, genrule rule
Configuration: 6167a43bee81d7c4ceebdf8986e0027b728c609e76e2c99eb3032efb76afa9e5
Mnemonic: Symlink, Genrule
Action key: d7773cd91ffd7932031eb8962471d065e41bfad384f2ed5d8d1925666f92ac3f, bea42f16cc513106d88e8f88f0739b713931b9efa6879cbd42f015a9d0d5e4d1
Progress message: Creating symlink bazel-out/k8-fastbuild/bin/src/common.h, Generating common library sources //src:generate_common.genrule
PrimaryInput: File:[[<execution_root>]bazel-out/k8-fastbuild/bin]src/common.h, File:[/home/fhenneke/git/bazel-experiments/pic-vs-pie/transitions-4[source]]src/generate_common_lib.sh
PrimaryOutput: File:[[<execution_root>]bazel-out/k8-fastbuild/bin]src/common.h
ERROR: com.google.devtools.build.lib.skyframe.ArtifactConflictFinder$ConflictException: com.google.devtools.build.lib.actions.MutableActionGraph$ActionConflictException: for src/common.h, previous action: action 'Generating common library sources //src:generate_common.genrule', attempted action: action 'Creating symlink bazel-out/k8-fastbuild/bin/src/common.h'
INFO: Elapsed time: 2.990s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (40 packages loaded, 481 targets configured)
```

**Comment by fmeum** [comment]
Based on the Fuchsia ticket, it seems like you may be picking up an old version of `rules_java` or Bazel itself.

What is the output of `bazel query --output=build //external:rules_java`?

**Comment by digit-google** [comment]
This is puzzling. My output is:

```sh
# /DEFAULT.WORKSPACE.SUFFIX:429:6
http_archive(
  name = "rules_java",
  generator_name = "rules_java",
  generator_function = "maybe",
  urls = ["https://mirror.bazel.build/github.com/bazelbuild/rules_java/archive/7cf3cefd652008d0a64a419c34c13bdca6c8f178.zip", "https://github.com/bazelbuild/rules_java/archive/7cf3cefd652008d0a64a419c34c13bdca6c8f178.zip"],
  sha256 = "bc81f1ba47ef5cc68ad32225c3d0e70b8c6f6077663835438da8d5733f917598",
  strip_prefix = "rules_java-7cf3cefd652008d0a64a419c34c13bdca6c8f178",
)
# Rule rules_java instantiated at (most recent call last):
#   /DEFAULT.WORKSPACE.SUFFIX:429:6                                                                                                                     in <toplevel>
#   /usr/local/google/home/digit/.cache/bazel/_bazel_digit/457ac8d91c73867105cd9c4a1ba5f668/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18 in maybe
# Rule http_archive defined at (most recent call last):
#   /usr/local/google/home/digit/.cache/bazel/_bazel_digit/457ac8d91c73867105cd9c4a1ba5f668/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31 in <toplevel>

Loading: 0 packages loaded
```

**Comment by digit-google** [comment]
It looks like `bazel clean --expunge` does not get rid of the problem, but nuking my `~/.cache/bazel/bazel_digit/` repository does actually solve it (the conflict you see is normal for this sample).

Note that I routinely switch between different versions of Bazel for my work, but I would expect them to place their data files under different sub-directories of my `output_user_dir`. I will try to come with reproduction steps since we have the issue on other people's machines as well.

**Comment by digit-google** [comment]
Oh, and for clarity, the query output after removing the `output_user_dir` and rebuilding is now is the same:

```sh
# /DEFAULT.WORKSPACE.SUFFIX:429:6
http_archive(
  name = "rules_java",
  generator_name = "rules_java",
  generator_function = "maybe",
  urls = ["https://mirror.bazel.build/github.com/bazelbuild/rules_java/archive/7cf3cefd652008d0a64a419c34c13bdca6c8f178.zip", "https://github.com/bazelbuild/rules_java/archive/7cf3cefd652008d0a64a419c34c13bdca6c8f178.zip"],
  sha256 = "bc81f1ba47ef5cc68ad32225c3d0e70b8c6f6077663835438da8d5733f917598",
  strip_prefix = "rules_java-7cf3cefd652008d0a64a419c34c13bdca6c8f178",
)
# Rule rules_java instantiated at (most recent call last):
#   /DEFAULT.WORKSPACE.SUFFIX:429:6                                                                                                                     in <toplevel>
#   /usr/local/google/home/digit/.cache/bazel/_bazel_digit/457ac8d91c73867105cd9c4a1ba5f668/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18 in maybe
# Rule http_archive defined at (most recent call last):
#   /usr/local/google/home/digit/.cache/bazel/_bazel_digit/457ac8d91c73867105cd9c4a1ba5f668/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31 in <toplevel>

Loading: 0 packages loaded
```

**Comment by Wyverald** [comment]
> Note that I routinely switch between different versions of Bazel for my work, but I would expect them to place their data files under different sub-directories of my output_user_dir.

That's not the case; we don't want a Bazel version update to cause users to have to rebuild their entire tree. If you switch between Bazel versions and want different directories when you switch, you could pass in `--output_base=...` manually.

**Comment by lberki** [comment]
Have you by any chance used `--experimental_sibling_repository_layout`?

I have two guesses:

1. You ran Bazel from the execroot of another Bazel instance (bazel then emits a warning, but it continues to run). This is a bad idea, but it used to be common enough that we had to add a warning, so this is my first guess.
2. There is some sort of odd bug when one flips the value of `--experimental_sibling_repository_layout` (I'd be surprised, since packages are not looked up in the execroot so the `external/` directory there should not cause problems)

Either case, I'd be interested in a reproduction with precise instructions.

**Comment by digit-google** [comment]
Thanks.

I never used `--experimental_sibling_repository_layout`, and also never run Bazel from an execroot.

In the case of the Fuchsia build, we use `--output_user_root`  and `--output_base`  to point to specific directories under our Ninja build directory, so `~/.cache/bazel/` is never used. But I do routinely change the bazel binary that is invoked to perform the build (to verify that our rules work with both Bazel 5.3.x and the upcoming Bazel 6.x since we intend to use BzlMod as soon as possible).

I will try to come up with a reproduction case is possible.

**Comment by lberki** [comment]
Thanks! I'm looking forward to it, I love mysteries :)
