### ISSUE TITLE
Feature request: Add pic_libs in CC Skylark Provider

### ISSUE THREAD

**Issue by ahyangyi** [bazelbuild/bazel#1656]
Currently, `CcSkylarkApiProvider.java` only provides the following API:

```
  @SkylarkCallable(
      name = "libs",
      structField = true,
      doc =
          "Returns the immutable set of libraries for either "
              + "FULLY STATIC mode (linkopts=[\"-static\"]) or MOSTLY STATIC mode (linkstatic=1) "
              + "(possibly empty but never None)")
  public NestedSet<Artifact> getLibraries() {
    NestedSetBuilder<Artifact> libs = NestedSetBuilder.linkOrder();
    CcLinkParamsProvider ccLinkParams = getInfo().getProvider(CcLinkParamsProvider.class);
    if (ccLinkParams == null) {
      return libs.build();
    }   
    for (LinkerInput lib : ccLinkParams.getCcLinkParams(true, false).getLibraries()) {
      libs.add(lib.getArtifact());
    }   
    return libs.build();
  }
```

It's adequate if one wants to build an executable (that is, emulate a `cc_binary` without supporting `linkshared = 1`). However, if building shared libraries is also to be supported, this would be inadequate.

It could be solved either by adding a new API, or adding a `bool` parameter to the existing one. 

**Since the CC Provider API is not stable yet (actually it's not even documented yet), fixing it sooner is better than later. Therefore, although this is just a feature request, I wish it could be done (or at least taken into consideration) before you finalize the provider APIs.**

(I haven't signed the CLA, so cannot contribute my own patch for now. But it should be an easy one to implement)

**Comment by mboes** [comment]
I think I'm running into the same problem. I can get a list of transitive static lib dependencies, but not a list of transitive dynamic lib dependencies. With the following dependency structure,

```
libA -> libB -> libC
```

I can see `libB.so` in the outputs of libB, and `libC.a` in the `libs` field of the `CcSkylarkApiProvider` for libB, but not `libC.so`. Any solution to that?

**Comment by benjaminp** [comment]
Now that `CcInfo.linking_context.libraries_to_link.pic_static_library` exists, this can probably be closed.

**Comment by hlopko** [comment]
I agree. If there are feature requests for the new api, please open a separate issue. Thank you all!
