### ISSUE TITLE
[Mirror] Gazelle v0.28.0

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel#16576]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.28.0/bazel-gazelle-v0.28.0.tar.gz

**Comment by sgowroji** [comment]
Mirror artifact:

https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.28.0/bazel-gazelle-v0.28.0.tar.gz
