### ISSUE TITLE
Tracking issue for standard builtins API inconsistencies

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#16574]
This bug is for collecting known API inconsistencies with the Starlark spec and/or Python 3. At some point we should do a full audit of all standard builtins.

Mainly the kinds of inconsistencies I expect involve parameter processing, e.g.:
- accepting a keyword arg when the param should be positional-only
- keyword parameters that have the wrong name
- optional parameters whose default value behavior doesn't match what happens when the supposed default is explicitly passed in

Current list of known issues in this repo:
- #8726
- #14309
- #15022

What we should do is systematically look at all method signatures in the spec, compare those against Python 3, and ensure that Starlark-in-Java and Starlark-in-Go are consistent with the spec.

Note that full consistency with Python 3 is not necessarily required, since in some cases it makes sense to intentionally deviate from Python (e.g. due to Starlark's lack of error recovery, or a preference for stricter fail-fast behavior).

**Comment by LavaToaster** [comment]
Hopping in here to state that the `bytes` type is not implemented.
