### ISSUE TITLE
Non-runfile files from an executable get included in the input for `ctx.actions.run()`

### ISSUE THREAD

**Issue by binoche9** [bazelbuild/bazel#16573]
### Description of the bug:

(Not 100% sure if it's a bug but it didn't match my expectation so at least asking here)

When a run a `ctx.actions.run()` action with an executable label, the `DefaultInfo.files` files always seems to get added to the input of the action even though I try to prevent that by not including it in `DefaultInfo.runfiles`.

When I run `bzl aquery //:foo_library` with the setup below, the output is: 

```
action 'run foo_library'
  Mnemonic: run
  Target: //:foo_library
  Configuration: k8-fastbuild
  Execution platform: @local_config_platform//:host
  ActionKey: e7ce4e79f3bff6702acba4bd5d9a9819249d00bd3b29f4c1c02af16d39cdf1ce
  Inputs: [bazel-out/k8-opt-exec-2B5CBBC6/bin/foo_binary, bazel-out/k8-opt-exec-2B5CBBC6/internal/_middlemen/foo_Ubinary-runfiles, foo.bzl]
  Outputs: [bazel-out/k8-fastbuild/bin/foo_library]
  Command Line: (exec bazel-out/k8-opt-exec-2B5CBBC6/bin/foo_binary \
    bazel-out/k8-fastbuild/bin/foo_library)
# Configuration: dde22220b12a34d64e2cd228935ffae0496402664dcb41d2a7ef95178a5feda3
# Execution platform: @local_config_platform//:host
```

The expectation is that since I try to signal that `foo.bzl` is not needed at runtime by not including it in the runfiles it isn't included as an input to the action, but unfortunately it seems that everything in `DefaultInfo.files` becomes an input to the action.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```py
# foo.bzl
def _foo_library_impl(ctx):
    output = ctx.actions.declare_file(ctx.label.name)
    ctx.actions.run(
        inputs = [],
        outputs = [output],
        mnemonic = "run",
        executable = ctx.executable.binary,
        arguments = [output.path],
    )

def _foo_binary_impl(ctx):
    ctx.actions.write(
        output = ctx.outputs.executable,
        content = "echo 'hi' > $1"
    )

    return [
        DefaultInfo(
            files = depset(ctx.files.extra_file),
            runfiles = ctx.runfiles([]),
        )
    ]

foo_library = rule(
    implementation = _foo_library_impl,
    attrs = {
        "binary": attr.label(
            default = Label("//:foo_binary"),
            executable = True,
            cfg = "exec"
        )
    }
)

foo_binary = rule(
    implementation = _foo_binary_impl,
    executable = True,
    attrs = {
        "extra_file": attr.label(
            default = Label("//:foo.bzl"),
            allow_single_file = True,
        )
    }
)
```

```py
# BUILD.bazel
load(":foo.bzl", "foo_binary", "foo_library")

foo_binary(name = "foo_binary")
foo_library(name = "foo_library")
```

### Which operating system are you running Bazel on?

Ubuntu 18.04.5 LTS (Bionic Beaver)"

### What is the output of `bazel info release`?

release 5.2.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
n/a
```

### Have you found anything relevant by searching the web?

Unfortunately not. I did ask in the [Bazel Slack](https://bazelbuild.slack.com/archives/CA31HN1T3/p1666809024373969) but only got some guesses and no definitive answer.

**Comment by fmeum** [comment]
With this diff I get the desired behavior:
```diff
diff --git a/foo.bzl b/foo.bzl
index c23fd34..3daabe8 100644
--- a/foo.bzl
+++ b/foo.bzl
@@ -9,14 +9,16 @@ def _foo_library_impl(ctx):
     )
 
 def _foo_binary_impl(ctx):
+    script = ctx.actions.declare_file(ctx.label.name)
     ctx.actions.write(
-        output = ctx.outputs.executable,
-        content = "echo 'hi' > $1"
+        output = script,
+        content = "echo 'hi' > $1",
+        is_executable = True,
     )
 
     return [
         DefaultInfo(
-            files = depset(ctx.files.extra_file),
+            executable = script,
             runfiles = ctx.runfiles([]),
         )
     ]
```

Given that `ctx.outputs.executable` is [marked as deprecated](https://bazel.build/rules/lib/ctx#outputs), maybe this behavior is just one of the reasons for why that is so?

**Comment by binoche9** [comment]
Doesn't that work because you removed `files` from `DefaultInfo`? Adding `files` back in doesn't give me the right behavior because I want some output to show up in my bazel output by default without showing up in my runfiles

**Comment by binoche9** [comment]
Thanks for going the extra mile to dig in the source code and come up with a workaround! I really appreciate it ❤️ 

> A potential downside of this approach is that the action depends on all the individual runfiles instead of just the runfiles middleman artifact, which may take more RAM/make analysis slower if you have many runfiles

Unfortunately in my case I have npm dependencies which makes for a long list of runfiles 😅 I'll have to see if it's worth it.

> so this workaround is only applicable if the runfiles of the binary aren't user-controlled

I don't think I fully follow the reasoning here

**Comment by fmeum** [comment]
> > so this workaround is only applicable if the runfiles of the binary aren't user-controlled
> 
> I don't think I fully follow the reasoning here

Only the actual files in runfiles are staged for the action, other runfiles features such as `symlinks` and `root_symlinks` are not supported with this workaround. If you know that the `runfiles` object provided by `foo_binary` doesn't use those features, that would not be a problem.

A completely different and much less hacky way to get what you want could be to move the files from `DefaultInfo.files` to an output group, which won't automatically be included in the runfiles. However, without `--output_groups`, these files wouldn't automatically be built if their targets are requested on the command line.

**Comment by comius** [comment]
After discussion in person: this is the intended behaviour of DefaultInfo.files and runfiles. Probably best solution is to move the file from DefaultInfo.files into validation output group - that models the desired behaviour of typechecking a TS file. It will run when building the binary target directy, but not when it's used as a tool. Flags can further control when it's run.

Possible, but unadvised alternative, is to use a special hidden output group OutputGroupInfo.HIDDEN_TOP_LEVEL, which will builds its file only when run from command line.
