### ISSUE TITLE
Bazel CI: Cargo, rules_rust & Kythe are broken with Bazel@HEAD

### ISSUE THREAD

**Issue by SalmaSamy** [bazelbuild/bazel#16571]
Following projects: [Cargo](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2706#01841278-52d1-41bf-964a-cb6a0bc3e821), [rules_rust](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2706#01841278-52d1-41bf-964a-cb6a0bc3e821), and [Kythe](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2706#01841277-c6cd-4440-8ca2-d4d6936565fe) are failing.
According to [Auto-Sheriff](https://buildkite.com/bazel/bazel-auto-sheriff-face-with-cowboy-hat/builds/1077), they are all failing due to same [commit](https://github.com/bazelbuild/bazel/commit/986852e268fb3bd00edeb6577b5a20cba7baec67) with error:
```
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/2f1dc3d4e337e7afcfcf49eb337215e4/external/rules_rust/util/process_wrapper/BUILD.bazel:6:36: in rust_binary_without_process_wrapper rule @rules_rust//util/process_wrapper:process_wrapper:
--
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/2f1dc3d4e337e7afcfcf49eb337215e4/external/rules_rust/rust/private/rust.bzl", line 366, column 32, in _rust_binary_impl
  | return rustc_compile_action(
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/2f1dc3d4e337e7afcfcf49eb337215e4/external/rules_rust/rust/private/rustc.bzl", line 879, column 52, in rustc_compile_action
  | dep_info, build_info, linkstamps = collect_deps(
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/2f1dc3d4e337e7afcfcf49eb337215e4/external/rules_rust/rust/private/rustc.bzl", line 174, column 65, in collect_deps
  | linkstamps.append(cc_info.linking_context.linkstamps())
  | Error in linkstamps: Rule in 'rust/private' cannot use private API

```

**Comment by kshyanashree** [comment]
Hello @SalmaSamy! It would be really helpful if you can provide a minimal reproduce case with Sample code, Thank you!
