### ISSUE TITLE
How to use bazel to build a MPI program?

### ISSUE THREAD

**Issue by gclouding** [bazelbuild/bazel#1658]
Now, suppose we have a simple MPI program, namely, hello_world.c, and below is its source code:
"
# include <mpi.h>
# include <stdio.h>

int main(int argc, char*\* argv) {
    MPI_Init(NULL, NULL);
    int world_size;
    MPI_Comm_size(MPI_COMM_WORLD, &world_size);
    int world_rank;
    MPI_Comm_rank(MPI_COMM_WORLD, &world_rank);
    char processor_name[MPI_MAX_PROCESSOR_NAME];
    int name_len;
    MPI_Get_processor_name(processor_name, &name_len);
    printf("Hello world from processor %s, rank %d"
           " out of %d processors\n",
           processor_name, world_rank, world_size);
    MPI_Finalize();
}
"

And then we have a makefile as:
"
EXECS=mpi_hello_world
MPICC?=mpicc
all: ${EXECS}
mpi_hello_world: mpi_hello_world.c
    ${MPICC} -o mpi_hello_world mpi_hello_world.c
clean:
    rm ${EXECS}
"
In this makefile, we use mpicc which is a compiler for MPI based programs. 

Now, how can we use bazel for building our mpi_hello_world program ? Can bazel replace the "make" tool and use the mpicc compiler to build our program ?

Anyone has any ideas? I am not quite familiar with bazel.

**Comment by philwo** [comment]
Hi @gclouding,

would you mind posting your question to our mailing list "bazel-discuss"? Bazel engineers and lots of community members regularly read, post and help each other there - I think you'll be able to get an answer quicker over there. :)

Here's the URL to get to the list: https://groups.google.com/forum/#!forum/bazel-discuss

Some ideas you could try:
- Run "CC=mpicc bazel build :mpi_hello_world" (I think it should pick up the new C compiler automatically then).
- Use a "genrule" to compile your code manually. (http://www.bazel.io/docs/be/general.html#genrule)
- Write a Skylark macro or rule to teach Bazel how to compile e.g. an mpi_cc_binary. (http://www.bazel.io/docs/skylark/concepts.html)

Considering that I can't find anything about this issue in our documentation myself, but it comes up frequently, I'll still leave this open as a documentation bug. I think users should find the answer to such a question by searching for "custom compiler" or similar terms in our docs.

**Comment by ahyangyi** [comment]
@gclouding 
If you are using OpenMPI, `$(shell mpicc --showme:compile)` and `$(shell mpicc --showme:link)` will give you flags that you can simply give to bazel as `copts` and `linkopts`, and then you can simply use the default toolchain.

Related documentation: https://www.open-mpi.org/faq/?category=mpi-apps#override-wrappers-after-v1.0

**Comment by mxwell** [comment]
@ahyangyi 
Not sure that's enough, because bazel complains about inclusion of undeclared header files.

@gclouding 
I think a better approach is to add a toolchain with CROSSTOOL. Here is a minimal example I came up with: https://github.com/mxwell/bazel-openmpi

**Comment by ahyangyi** [comment]
@mxwell Yes, writing a CROSSTOOL is the better approach. My suggestion was just given as a quick fix, but if that doesn't work, going back to the standard solution is better.

**Comment by jin** [comment]
Hi @gclouding, please contact bazel-discuss if you have any further questions about MPI support. Closing this for now.
