### ISSUE TITLE
[6.0.0] Remove references to io_bazel repository

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#16584]
Forked from #16559

**Comment by meteorcloudy** [comment]
Is the fix for https://github.com/bazelbuild/bazel/pull/16559 got cherry picked? Can you provide some information when closing the issue?

**Comment by meteorcloudy** [comment]
@kshyanashree Can you put a link to the PR that cherry-pick the change when you close the issue?

**Comment by sgowroji** [comment]
Cherrypicked at https://github.com/bazelbuild/bazel/pull/16633
