### ISSUE TITLE
cquery --output=files ignores source files

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/bazel#16599]
### Description of the bug:

I try to use `bazel cquery --output=files` to replace `bazel run --run_under=echo` in order to find the path to files which may later be run (or e.g. passed as arguments to other scripts).

Sometimes this is for complex targets, e.g. an alias where on some platform we use a pre-built binary and on another we build a binary, e.g. something like:

```starlark
alias(
    name = "my_binary",
    actual = select({
        "//some:condition": ":prebuilt_file_for_some_platform",
        "//some/other:condition": ":build_a_binary",
    }),
)
```

However, `bazel cquery --output=files :my_binary` ignores source files because of [this filtering](https://github.com/bazelbuild/bazel/blob/50b87c1ec0a5696e46dec7122de130d13112ffdd/src/main/java/com/google/devtools/build/lib/query2/cquery/FilesOutputFormatterCallback.java#L56-L63).

I think there should be a way to ask bazel "what file(s) does this resolve to?", regardless of whether the file is generated or checked in.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```console
% touch WORKSPACE && touch prebuilt && chmod 0755 prebuilt && echo 'exports_files(["prebuilt"])' > BUILD.bazel && bazel cquery --output=files :prebuilt 2>/dev/null
```

Expect to see `prebuilt` output, but actually see nothing.

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 5.3.2

### Any other information, logs, or outputs that you want to share?

/cc @fmeum @gregestren

**Comment by fmeum** [comment]
This was done to mimic the output of `bazel build <target>`, but I agree that having this functionality would be very useful, not just for complex `select` statements but already for simple `filegroup`s.

@gregestren What do you think, could we mimic `--starlark:expr` and add a flag similar to `--files:include_source_files`?

**Comment by fmeum** [comment]
I created #16602 with a proposal for an implementation. It is not touching the default value.

@illicitonion Could you check whether that PR works as expected in the realistic scenarios you would want to use it in?

**Comment by illicitonion** [comment]
That works perfectly for my use-cases - thanks so much!

**Comment by gregestren** [comment]
Fixed by https://github.com/bazelbuild/bazel/pull/16602
