### ISSUE TITLE
params files don't correctly encode utf-8 filenames

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#16594]
### Description of the bug:

When you have a source file named `a 进行正式友好访问 2.swift` and use a rule that uses args objects with params files, the params file content incorrectly encodes the file name, such that in this case the content is:

```
% cat bazel-out/darwin_arm64-fastbuild/bin/foo-0.params
a è¿è¡æ­£å¼åå¥½è®¿é® 2.swift
```

Which likely leads the underlying tool to fail, as the file path here doesn't exist.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

[swiftfilename.zip](https://github.com/bazelbuild/bazel/files/9881535/swiftfilename.zip)

With this repro case run:

```
USE_BAZEL_VERSION=last_green bazelisk build foo
```

You will see a print debug showing the args contain the correctly encoded argument name:

```
DEBUG: /private/tmp/swiftfilename/foo.bzl:10:10: actual args are a 进行正式友好访问 2.swift bazel-out/darwin_arm64-fastbuild/bin/foo
```

Then the rule will fail, leaving the params file, which when you inspect you will see the incorrect encoding

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

1935539eaab3ce1acd1f2bb87ad0d00f46f3c6ea

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

bazelisk

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/rules_swift/issues/928

**Comment by brandjon** [comment]
Encoding problems are a well-known issue for us, and we hope to address them this year by fixing UTF-8 encoding of BUILD/.bzl files, adding support for a `bytes` type, and fixing individual APIs.

Right now, BUILD/.bzl files are interpreted as if they were latin-1, so only code points <0xff are generated. This filename data is coming from `glob()` but it may be the same story there. It looks like the param content is all code points <0xff so it sounds like that's what's happening -- utf-8 filename consumed as latin-1 but emitted as utf-8.

**Comment by fmeum** [comment]
This is fixed in Bazel 7. The build still fails since `cp` doesn't support param files (at least on my Mac), but the param file looks like this:
```
a 进行正式友好访问 2.swift
bazel-out/darwin_arm64-fastbuild/bin/foo
```
