### ISSUE TITLE
Provider custom initialization fails

### ISSUE THREAD

**Issue by mobileink** [bazelbuild/bazel#16597]
### Description of the bug:

I copied the code at [Custom initialization of providers](https://bazel.build/extending/rules#custom_initialization_of_providers):

```
_core_headers = []
def _exampleinfo_init(*, files_to_link, headers = None, allow_empty_files_to_link = False):
    if not files_to_link and not allow_empty_files_to_link:
        fail("files_to_link may not be empty")
    all_headers = depset(_core_headers, transitive = headers)
    return {'files_to_link': files_to_link, 'headers': all_headers}

ExampleInfo, _new_exampleinfo = provider(
    init = _exampleinfo_init)
```

Then I load it (but do not use the provider), and when I build I get this:

```
File ... <toplevel>
		ExampleInfo, _new_exampleinfo = provider(
Error in provider: provider() got unexpected keyword argument 'init'
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Copy the example code and edit (e.g. delete the '...') in a .bzl file, then load it.

### Which operating system are you running Bazel on?

MacOS

### What is the output of `bazel info release`?

5.3.2

### Have you found anything relevant by searching the web?

No

**Comment by fmeum** [comment]
[The commit](https://github.com/bazelbuild/bazel/commit/fc13ba271f138c804869d0f99d751e25518b5326) doesn't seem to be in 5.3.2. Could you run your example with 6.0.0rc1?

**Comment by brandjon** [comment]
Probably just version confusion but I'd be interested to know if there is any real blocker for using this feature. Will close if there's no response in O(week).

**Comment by mobileink** [comment]
It works with "last_green" in .bazelversion:

```
$ bazel version
2022/11/02 21:10:42 Using unreleased version at commit 9b420b5698c4be200f03c027800e01e57835def9
Bazelisk version: development
```

The core problem is that you documented something that did not exist. Please don't do that.

**Comment by brandjon** [comment]
Ah, yes, I believe the docs on bazel.build are not yet versioned but will be in the near future, so this shouldn't happen again. (+@philomathing to refute if I'm wrong.)
