### ISSUE TITLE
Matching platform constraints do not match

### ISSUE THREAD

**Issue by HappyCerberus** [bazelbuild/bazel#16607]
### Description of the bug:

Using platform constraints on a target:

```
cc_test(
    name = "library_test",
    srcs = ["library_test.cc"],
    deps = [":library"],
    target_compatible_with = [
        '@platforms//cpu:x86_64',
        '@platforms//os:linux',
    ]
)
```

Results in an error:
```
Dependency chain:
    //platforms:library_test (1f7c4b)   <-- target platform (@local_config_platform//:host) didn't satisfy constraints [@platforms//cpu:x86_64, @platforms//os:linux]
```

Despite the autodetected configuration in `constraints.bzl` being this:
```
# DO NOT EDIT: automatically generated constraints list for local_config_platform
# Auto-detected host platform constraints.
HOST_CONSTRAINTS = [
  '@platforms//cpu:x86_64',
  '@platforms//os:linux',
]
```

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 6.0.0-pre.20220922.1

**Comment by HappyCerberus** [comment]
One extra data point I can provide is that when I define a local platform with the same content, then bazel fails to match the linux version of jdk (fails to match any version for that matter).

This implies to me that the constraints in my BUILD files for whatever reason never match the constraints in the dependencies, despite referring to the same target.

**Comment by HappyCerberus** [comment]
After writing my last post I had a lightbulb moment and tried explicitly depending on platforms in my `MODULE.bazel`. This fixed the issue.

As far as I understand, this is bug in module resolution:

- I should be implicitly depending on platforms already
- the implicitly pulled version of platforms is the same
- even if this isn't the case, this should result in a dependency error, not resolve to incompatible targets (I still have no idea why)

**Comment by HappyCerberus** [comment]
OK, further into the strangeness. So this seems to be the crux of the issue here:

This is an expected failure, but I have no idea where the expansion to `@platforms~0.0.5` is coming from, I'm guessing that the reason why this matches `@platforms//cpu:x86_64` is because that also silently expands into `@platforms~0.0.5//cpu:x86_64`, both in `@local_config_platform//:host` and in the constraint.

```
Dependency chain:
    //platforms:library_test (1f7c4b)   <-- target platform (@local_config_platform//:host) didn't satisfy constraint @platforms~0.0.5//os:windows
```

**Comment by fmeum** [comment]
It would be helpful to know whether this reproduces if you create an empty `WORKSPACE.bzlmod` to disable any kind of `WORKSPACE` dependency loading. I suspect that is where the incompatible `@platforms` is coming from.

**Comment by HappyCerberus** [comment]
That seems to be the place:

```
ERROR: Analysis of target '//platforms:library_test' failed; build aborted: no such package '@[unknown repo 'platforms' requested from @]//os': The repository '@[unknown repo 'platforms' requested from @]' could not be resolved: Repository '@platforms' is not visible from repository '@'
```

**Comment by sgowroji** [comment]
Hello @HappyCerberus, Can you provide an example to reproduce the above error logs. Thanks!

**Comment by fmeum** [comment]
@sgowroji I think that this fits the external deps team better since it only occurs when mixing `WORKSPACE` and `MODULE.bazel`.

**Comment by HappyCerberus** [comment]
This is the repository where I'm running into the problem:
https://github.com/HappyCerberus/meetingcpp22-bazel

Try building `//platforms:library_test` when `bazel_dep(name = "platforms", version = "0.0.5")` is commented out. It will complain not only about the OS, but also the CPU.

For a reproducible environment, either open in VSCode (with docker installed) or just use the Dockerfile from .devcontainer.

**Comment by fmeum** [comment]
I think what's happening here is that `local_config_platform` uses the constraints from the Bazel module `platforms` (canonical name `platforms~<version>`), whereas your BUILD file uses the constraints from the `WORKSPACE`-defined `platforms` repository.

That is a very confusing situation. I don't have a good idea how to detect and prevent this automatically though.

**Comment by HappyCerberus** [comment]
The thing that I'm a bit puzzled about is that this is actually possible (to have multiple versions of the same dependency).

This would imply that I can accidentally end up with multiple versions of an external library, leading to ABI issues.

My previous understanding was that to have multiple versions, I have to explicitly pull them in under different names.

**Comment by Wyverald** [comment]
Hmm, this might be a bug in `local_config_platform`. I'll take a look later.
