### ISSUE TITLE
[6.0.0] Fix race condition in package-bazel.sh

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#16615]
Forked from #16614

**Comment by meteorcloudy** [comment]
@kshyanashree Why this is closed?

**Comment by meteorcloudy** [comment]
https://github.com/bazelbuild/bazel/pull/16614 is not yet merged.

**Comment by meteorcloudy** [comment]
https://github.com/bazelbuild/bazel/pull/16614 is now merged, @kshyanashree can you help cherry pick this into release-6.0.0?

**Comment by kshyanashree** [comment]
> #16614 is now merged, @kshyanashree can you help cherry pick this into release-6.0.0?

Sure @meteorcloudy, Thanks!

**Comment by sgowroji** [comment]
Cherrypicked at https://github.com/bazelbuild/bazel/pull/16642
