### ISSUE TITLE
Create static lib (.a) failure

### ISSUE THREAD

**Issue by ywsswy** [bazelbuild/bazel#16627]
### Description of the bug:

run command `bazel build //:mylib`, 'libmylib.a' not found, it seems ilke 'alwayslink = 1' in 'BUILD" file not worked ???

![image](https://user-images.githubusercontent.com/25153243/199420695-33fb5eab-ec1e-4c1a-a04d-55f42a09298a.png)

the 'BUILD' file:
```
cc_library(
    name = "mylib",
    linkstatic = True,
    deps = [
        "//:depend1",
        "//:depend2",
    ],
    alwayslink = 1,
)

cc_library(
    name = "depend2",
    srcs = ["depend2.cc"],
    hdrs = ["depend2.h"],
    deps = [
        "//:depend1",
    ],
    alwayslink = 1,
)

cc_library(
    name = "depend1",
    srcs = ["depend1.cc"],
    hdrs = ["depend1.h"],
    alwayslink = 1,
)
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/ywsswy/test_static_lib

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 3.7.2

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
git@github.com:ywsswy/test_static_lib.git
25f645f3538146ed326b582a7ea8007f9b92d7d2
25f645f3538146ed326b582a7ea8007f9b92d7d2
```

**Comment by fmeum** [comment]
If you want to build a shared library as a build output, use `cc_binary` with `linkshared = True`. That might be a bit unintuitive, but `<language>_library` rules aren't really meant to produce final build outputs.

**Comment by ywsswy** [comment]
@fmeum 
i want to build a 'static' library, not shared library.

how could i build a static library ?

**Comment by fmeum** [comment]
@ywsswy Sorry, I published my comment too quickly but have edited it to address that part.
