### ISSUE TITLE
New command bazel pid

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#1663]
In order to be able to query child processes of the bazel server it would be good to be able to retrieve the pid of the server.
For that either add a new command `pid` or add information to `version`.

Scenario is that I want to attach a debugger once a certain action is executed. For that I need the bazel server pid so I can `pgrep` its children for the action command line.

**Comment by abergmeier** [comment]
Just read that there is `info server_pid`. Apparently my google foo is weak.
