### ISSUE TITLE
Repository mapping manifest does not exist in test sandbox

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#16643]
### Description of the bug:

The `.repo_mapping` file does not appear in test sandboxes.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
# WORKSPACE
# MODULE.bazel
# pkg/BUILD
sh_test(
  name = "test",
  srcs = ["test.sh"],
)
# pkg/test.sh
#!/usr/bin/env bash

runfiles_dir="$TEST_SRCDIR/../test.runfiles"
if [[ ! -d "$runfiles_dir" ]]; then
  echo "$runfiles_dir does not exist"
  exit 1
fi
repo_mapping="$TEST_SRCDIR/../test.repo_mapping"
if [[ ! -f "$repo_mapping" ]]; then
  echo "$repo_mapping does not exist"
  exit 1
fi
```

`USE_BAZEL_VERSION=last_green bazel test //pkg:test --enable_bzlmod` fails
`USE_BAZEL_VERSION=last_green bazel run //pkg:test --enable_bzlmod` passes
`USE_BAZEL_VERSION=last_green bazel test //pkg:test --enable_bzlmod --spawn_strategy=local` passes

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

HEAD

**Comment by fmeum** [comment]
@Wyverald

**Comment by fmeum** [comment]
My guess (it really is only a guess) is that we have to explicitly add the repo mapping manifest to the input mapping in [`SpawnInputExpander`](https://cs.opensource.google/bazel/bazel/+/bbc221f60bc8c9177470529d85c3e47a5d9aaf21:src/main/java/com/google/devtools/build/lib/exec/SpawnInputExpander.java;l=119;drc=0a23d46976c3fc999d44fbd1e37732ec2442d485) for it to show up in sandboxed and remote execution. That in turn requires adding a getter for it to `RunfilesSupplier`.

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by meteorcloudy** [comment]
Fix cherry picked in https://github.com/bazelbuild/bazel/pull/16733, removing the `potential release blocker` label.
