### ISSUE TITLE
Bazel repository cache is not safe for parallel builds

### ISSUE THREAD

**Issue by artem-zinnatullin** [bazelbuild/bazel#16645]
### Description of the bug:

Hi Bazel team.

We're optimizing our CI build times and one of the slowest things for us is how Bazel resolves its repository caches which for our regular Android build is about 10GB of internet downloads.

Our CI builds run in k8s as containers, so sometimes one physical/virtual host fits multiple concurrent Bazel builds in their separate containers.

What we're trying to do: persist Bazel repository cache between CI jobs so they don't have to start by downloading half of the internet.

If we point `$HOME/.cache` to a disk dir that is shared between containers, we start to observe all sorts of errors.

```java
error loading package '': Every .bzl file must have a corresponding package, but '@com_google_protobuf//:protobuf_deps.bzl' does not have one.
```

or

```java
FATAL: opening /mnt/shared-disk-cache/bazel_repo_cache/_bazel_root/7b7747ec045ae606eb720a1222f56098/server/jvm.out failed: (error: 2): No such file or directory
```

or

```java
ERROR: no such package '@com_google_protobuf//': java.io.FileNotFoundException: /mnt/shared-disk-cache/bazel_repo_cache/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/com_google_protobuf/temp740102768690522313/v3.12.2.zip (No such file or directory)
```

or

```java
Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/mnt/shared-disk-cache/bazel_repo_cache/_bazel_root/7b7747ec045ae606eb720a1222f56098/server/jvm.out')```

or

```java
ERROR: /build/WORKSPACE:142:10: fetching pip_repository rule //external:pip_deps: Traceback (most recent call last):
	File "/mnt/shared-disk-cache/bazel_repo_cache/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/rules_python/python/pip_install/pip_repository.bzl", line 171, column 13, in _pip_repository_impl
		fail("rules_python failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: rules_python failed:  (The folder you are executing pip from can no longer be found.
```

or

```java
File "/mnt/shared-disk-cache/bazel_repo_cache/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/rules_python/python/pip_install/pip_repository.bzl", line 20, column 18, in _construct_pypath
		rctx.path(Label("@" + repo + "//:BUILD.bazel")).dirname
Error in path: Unable to load package for @pypi__pip//:BUILD.bazel: BUILD file not found in directory '' of external repository @pypi__pip. Add a BUILD file to a directory to mark it as a package.
```

and such.

Bazel even writes logs to the same file in repository cache it seems which is a design that can't stand parallel builds at all I guess `$HOME/.cache/_bazel_root/7b7747ec045ae606eb720a1222f56098/server/jvm.out`.

---

For now our workaround is to atomically acquire a safe subdir within shared disk dir between containerized CI jobs, like 

`/mnt/shared-disk-cache/0/bazel_repo_cache`, `/mnt/shared-disk-cache/1/bazel_repo_cache`, 2, 3... and so on but that dramatically reduces chance of hitting the repository cache because our CI cluster autoscales and we kill machines at the end of the day.

---

With this issue being open and logs reported for Google search hits I hope to start a discussion on moving Bazel towards more atomic and parallel / concurrent safe use of repository cache.

Perhaps Bazel could inflate tmp directories while they're not completed and move files atomically-ish to final destination in repository cache. And not use shared files like `$HOME/.cache/_bazel_root/7b7747ec045ae606eb720a1222f56098/server/jvm.out`

Bazel already works with individual files in repository cache atomically:

https://github.com/bazelbuild/bazel/blob/21993354846ff9177e4e228e2caf4234103fb478/src/main/java/com/google/devtools/build/lib/bazel/repository/cache/RepositoryCache.java#L236

Hopefully it's not too hard to make its repository cache concurrent safe overall.

This should also help move Bazel towards parallel builds within same Bazel server.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

How: Run two concurrent Bazel builds isolated to different Linux containers or Unix users pointed to same repository cache directory.

Observation: weirdest build errors due to files being deleted, not available, directories being removed from underneath the package managers like `pip` ran by Bazel, etc.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 5.3.2

### Have you found anything relevant by searching the web?

https://github.com/GoogleContainerTools/skaffold/issues/6047

**Comment by jwnimmer-tri** [comment]
FYI See https://bazel.build/remote/output-directories for layout information.  As I understand it, each of your builds should have a dedicated `outputBase`. 

You might want to keep `~/.cache` inside the container, and instead set [--repository_cache](https://bazel.build/reference/command-line-reference#flag--repository_cache) to a shared mound, instead.  That way, only the download cache is shared across builds, rather than dangerous things like `execRoot`.

**Comment by Wyverald** [comment]
Everything @jwnimmer-tri said is correct -- you're not supposed to make different Bazel servers share the same output base.
