### ISSUE TITLE
//src/test/shell/bazel:bazel_windows_example_test never finishes

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#1664]
Our CI is in trouble, because on Windows the test //src/test/shell/bazel:bazel_windows_example_test never finishes and also no time out kicks in, which means that it happily sits there waiting 12 hours for the thing to be done. This blocks all the rest of the CI system.

Here's what happened:
http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=windows-x86_64/761/console

@lberki Please fix ASAP or disable the test, thanks :)

**Comment by lberki** [comment]
Hm, that's odd. I ran it on my workstation, and it passes. Investigating...

**Comment by lberki** [comment]
I see. Test timeouts don't work on Windows. Investigating more...

**Comment by philwo** [comment]
If you can give me working timeouts, I'm fine with leaving the test flaky in exchange. Deal? 😁

**Comment by lberki** [comment]
That's exactly what I had in mind :)

**Comment by lberki** [comment]
Well, this explains it... :P

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/standalone/StandaloneSpawnStrategy.java#L94

**Comment by philwo** [comment]
Haha! But didn't we have some special windows-only JNI magic with JobObjects that should handle all this, instead of the process wrapper?

**Comment by lberki** [comment]
This is the exact feature that wasn't implemented in the JNI code... yet :)

**Comment by dslomov** [comment]
Tests seems ok now?

**Comment by lberki** [comment]
Yep, this hasn't repeated itself since the fixes to process control.
