### ISSUE TITLE
Java test runner tests aren't running

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#1665]
First of all, the tests are missing from Bazel, even though they are correctly licensed in our internal tree.

Also, many of the tests are written in JUnit3 style, and are not being picked up by the (internal) ClasspathSuite. This means many of the tests are not running right now.

I tried running some of the tests that aren't currently running in CI, and they fail.

Here's what I'd suggest:
1. use explicit @SuiteClasses enumeration of all the tests we want to run; avoid ClasspathSuite
2. convert the tests to Junit4; there's no point in still using Junit3 for these
3. use the vanilla Junit4 test runner; do _not_ use the more advanced Bazel test runner
4. ship the .java test files as open source

The 3. step is mainly to ensure that potential bugs in the test runner that cause tests not to be run don't affect the test runner tests themselves.

Queue "we must go deeper" meme.

**Comment by lberki** [comment]
@ulfjack : I checked and there are 21 files that end with `Test.java` under `src/java_tools/junitrunner/javatests`, all of which are being run when running all the test targets under that directory. Am I missing something?

**Comment by ulfjack** [comment]
What about the nested classes?

**Comment by iirina** [comment]
The work is completed here, all 4 points have been implemented. 
@ulfjack Junit doesn't run inner classes by default. The nested classes we have are test classes annotated with @RunWith, that are used when testing the test runner :)

**Comment by ulfjack** [comment]
Great, thanks!
