### ISSUE TITLE
The order of WORKSPACE load should not matter - or at least give clearer warnings

### ISSUE THREAD

**Issue by njlr** [bazelbuild/bazel#16658]
### Description of the bug:

Many rules interfere with each-other such that the order in which they are loaded in the `WORKSPACE` matters. 

If the order is wrong, then the error message from Bazel does not help the user discover how to fix the issue. 

Ideally, the order would not matter. Short of that, Bazel should give clear messages to help debug the issue. 

Here is an example in the wild: 
https://github.com/scionproto/scion/blob/bd72960be4f3176839f5016cd2b7e6dfb175078f/WORKSPACE#L87-L96

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try `rules_python` and `rules_docker` then change the ordering. 

### Which operating system are you running Bazel on?

Ubuntu and macOS

### What is the output of `bazel info release`?

release 5.3.1

### Have you found anything relevant by searching the web?

The error message is unrelated to the problem so it's hard to find help. 

However, I eventually stumbled on this: https://github.com/scionproto/scion/blob/bd72960be4f3176839f5016cd2b7e6dfb175078f/WORKSPACE#L87-L96

**Comment by keith** [comment]
FWIW realistically at this point I think the solution to this will be "use bzlmod"

**Comment by Wyverald** [comment]
Indeed. This is a known issue, and so ingrained into how the whole WORKSPACE mechanism works that we decided to fix it by building a new system instead! Please take a look at https://bazel.build/docs/bzlmod.

**Comment by njlr** [comment]
> Indeed. This is a known issue, and so ingrained into how the whole WORKSPACE mechanism works that we decided to fix it by building a new system instead! Please take a look at https://bazel.build/docs/bzlmod.

Thank you I will take a look!
