### ISSUE TITLE
Ship an embedded Jvm or installer

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#1666]
We've gotten feedback that the dependency on Java makes it unnecessarily harder to install Bazel, and we should consider if bundling a Jvm or triggering a Jvm install from our installer would be workable options. What are our options here?

**Comment by damienmg** [comment]
Adding Helen also, I think we also need to evaluate the benefit of doing so.

I am pretty sure we can do it with putting an engineer one month on it. The underlying maintenance is less clear. Probably around 1 day per Java update (so a day per month I would say) is a big overestimation.

I'd rather we work on that if that's higher priority that other thing. We agree it is nice to do, just not clear how nice.

**Comment by damienmg** [comment]
(note: those costs are rough estimation of the engineering time, we probably needs to speak to legal about what we can do exactly, though this might be covered by the recent fix on GPL with classpath exception code).

**Comment by damienmg** [comment]
Reassigning priority so we can get rid of the JDK 7 build. Seems like the perfect solution for it. Philip has agreed to investigate further.

**Comment by philwo** [comment]
The feature is complete, integrated with our build process and in code review & pending final verification on Windows now.

**Comment by damienmg** [comment]
It would need to integrate with our release pipeline too, but I guess this is just another target to build

**Comment by philwo** [comment]
Yes, the current approach is that this is just another target that we can build (//src:bazel_with_jdk instead of //src:bazel). :)

**Comment by philwo** [comment]
All required code changes have been made as of https://github.com/bazelbuild/bazel/commit/9504827b21217aaa28a248ce499dd25c6a415d6e.

The last step is to actually integrate this into our release pipeline so that we build release artifacts of the new target. I think @damienmg wanted to have a look at this when he has some time.

**Comment by damienmg** [comment]
I don't think I will have time for it soon enough, but just adding the target in //scripts/package to build the deb and .sh with jdk and then reference them in scripts/ci/build.sh for them to be pushed should be enough.

**Comment by abergmeier-dsfishlabs** [comment]
Just as an input - we have a JDK for every platform in our repo just because the dependency on Java. Would also greatly appreciate, if that would be solved automagically.

**Comment by damienmg** [comment]
As per @philwo  report this is now working, we still need to figure out #2943 but this one is good to close. Thanks @philwo for making that possible!
