### ISSUE TITLE
Release 5.4.0 - December 2022

### ISSUE THREAD

**Issue by kshyanashree** [bazelbuild/bazel#16663]
# Status of Bazel 5.4.0

-   Expected release date: 2022-12-15
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/45)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 5.4, simply send a PR against the `release-5.4.0` branch.

Task list:

-   [x] [Create draft release announcement](https://docs.google.com/document/d/1pu2ARPweOCTxPsRR8snoDtkC9R51XWRyBXeiC6Ql5so/edit#heading=h.1ldj0zgvx6cd)
-   [x] Send for review the release announcement PR
-   [x] Push the release, notify package maintainers
-   [x] Update the documentation
-   [x] ~Push the blog post~
-   [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by aiuto** [comment]
Is there an updated timeline for this?
Is there a public list of changes we want to hold the release for?

**Comment by aiuto** [comment]
+Radhika Advani ***@***.***> +Yun Peng ***@***.***>

But what I should have asked is "who is the release manager?"
Someone should be vetting all backported features and fixes so that we know
they are relevant and don't break backwards compatibility.

**Comment by aiuto** [comment]
OK. I have 2 PRs in flight now.

**Comment by meteorcloudy** [comment]
@kshyanashree is managing the release and all cherry picks have been reviewed by a Bazel team member (either the change author or reviewer) to make sure they are backwards compatible.

**Comment by meteorcloudy** [comment]
> OK. I have 2 PRs in flight now.

Can you mark those PRs with `6.0.0 release blockers" milestone?

**Comment by meteorcloudy** [comment]
Sorry, I meant `5.4.0 release blockers`, I updated the comment in the github issue, but maybe you received the old comment in email.

**Comment by kshyanashree** [comment]
Bazel 5.4.0rc1 is now available for those that want to try it out.

You can download it from:
 https://releases.bazel.build/5.4.0/rc1/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by aiuto** [comment]
@Jon Brandvein ***@***.***>

Is there any chance of getting the starlark provider "init" functionality
into 5.4?

**Comment by Wyverald** [comment]
properly cc'ing @brandjon

**Comment by aiuto** [comment]
The changes are in Bazel, but I don't know the difficulty.
I asked about it because:
- I tried to use an init method in a provider constructor in rules_license.
- that helped improve the security of a rule used for compliance work
- but then CI fails because it runs with 5.x

So, I could sweep the issue under the rug and wait until CI is all 6.x,
but that won't help with having a single rule set that is compatible with
5 and 6. OTOH.... initializers are an obscure feature that helps with
visibility protection. Mostly users need it, but rule authors do not.
I could make a case that we do not want to put it in 5.x so that
we encourage users to migrate to 6.

**Comment by meteorcloudy** [comment]
> I could make a case that we do not want to put it in 5.x so that we encourage users to migrate to 6.

OK, then we'll release 5.4.0 as planned. We can encourage users to use 6, and if really necessary we can make a 5.5.0 release for the changes.

**Comment by comius** [comment]
Hey, can we have one more cherry-pick on 5.4.0? The [Exec platform per toolchain](https://docs.google.com/document/d/1-rbP_hmKs9D639YWw5F_JyxPxL2bi6dSmmvj_WXak9M/edit?usp=sharing), needs a new parameter on `ctx.actions.run`. Adding a no-op parameter would make the transition smoother. But we'd need to cherry-pick it to 6.0.0 as well.

**Comment by meteorcloudy** [comment]
I think it's fine, @comius Can you or @kotlaja send a PR to the release-5.4.0 branch?

**Comment by kotlaja** [comment]
Following @comius comment: https://github.com/bazelbuild/bazel/commit/a247502d28d8d70d648390de52952189b99a0bb7. Thanks!

**Comment by meteorcloudy** [comment]
@kshyanashree Can you cherry pick https://github.com/bazelbuild/bazel/commit/a247502d28d8d70d648390de52952189b99a0bb7 to both 5.4.0 and 6.0.0?

**Comment by kshyanashree** [comment]
> @kshyanashree Can you cherry pick [a247502](https://github.com/bazelbuild/bazel/commit/a247502d28d8d70d648390de52952189b99a0bb7) to both 5.4.0 and 6.0.0?

Yes @meteorcloudy! I am on it. Thanks :)

**Comment by kshyanashree** [comment]
Bazel 5.4.0rc2 is now available for those that want to try it out.

You can download it from: 
https://releases.bazel.build/5.4.0/rc2/index.html

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by aiuto** [comment]
It looks like there are some UTF-8 manglings in the list of contributors
section.

**Comment by kshyanashree** [comment]
5.4.0 is now out!

[@vbatts](https://github.com/vbatts) [@petemounce](https://github.com/petemounce) [@excitoon](https://github.com/excitoon) Could you please update relevant package managers? Thanks!

**Comment by petemounce** [comment]
Done. Ping for [adding into CI](https://github.com/bazelbuild/continuous-integration/issues/1456) cc @meteorcloudy.

**Comment by kshyanashree** [comment]
> Done. Ping for [adding into CI](https://github.com/bazelbuild/continuous-integration/issues/1456) cc @meteorcloudy.

Thanks @petemounce!

**Comment by keertk** [comment]
We're working on a patch release (5.4.1) to address a few compatibility issues -- RC1 is now available for those that want to try it out.
You can download it from: https://releases.bazel.build/5.4.1/rc1/index.html
Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

Release notes can be found [here](https://docs.google.com/document/d/1pu2ARPweOCTxPsRR8snoDtkC9R51XWRyBXeiC6Ql5so/edit#heading=h.6ke4hvqbh7sl).

**Comment by aiuto** [comment]
We need a better scheme for understanding the release timelines. There are
some things I would have backported to 5.x if I had known we were doing a
new release.
Is a 5.5.0 planned?

**Comment by keertk** [comment]
Hi @aiuto there's no 5.5.0 planned. 
We planned to do 5.4.1 just 2 days ago to address some incompatibility issues discussed here: https://github.com/bazelbuild/bazel/issues/17958#issuecomment-1495969904

We won't be doing the final release-5.4.1 release until at least 7 days from now as per the release policy, so feel free to submit additional cherry-picks to the `release-5.4.1` branch if needed. We can create an additional RC.
