### ISSUE TITLE
[Mirror] make 4.4

### ISSUE THREAD

**Issue by jsharpe** [bazelbuild/bazel#16676]
### Please list the URLs of the archives you'd like to mirror:

Please mirror http://ftpmirror.gnu.org/gnu/make/make-4.4.tar.gz for `rules_foreign_cc`

**Comment by sgowroji** [comment]
Please find the below mirror artifact

https://mirror.bazel.build/ftpmirror.gnu.org/gnu/make/make-4.4.tar.gz
