### ISSUE TITLE
Support spaces in paths

### ISSUE THREAD

**Issue by c-ning** [bazelbuild/bazel#167]
Example path in MacOS:
/Users/alice/Google Drive/Bazel/bazel

Also the rm commands in https://github.com/google/bazel/blob/master/compile.sh#L124 failed with messages: rm: /Users/alice/Google: is a directory

**Comment by kchodorow** [comment]
I can fix compile.sh by throwing in some "s, but the resulting Bazel won't actually build things (as it does not allow spaces in paths to runfiles).  Let me see if we can fix that, but for now, can you use a path without spaces in it?

**Comment by c-ning** [comment]
Thanks. I am now using a path without spaces, and it's working fine now.

As a suggestion, it would be good to clarify somewhere (e.g. the "Installing Bazel" page or in the script) that bazel currently does not work for paths with spaces.

**Comment by damienmg** [comment]
Closing this issue in favor of #374 that is more precise.

**Comment by sharmila-polamuri** [comment]
Please help me anyone , i got same issue but i am working in google colab i mount google drive .This is the file path i am working ```/content/gdrive/My Drive/TextSummaryPaperswithCode ``` . I am trying to change ```My Drive ``` name but not happened. How can i solve this problem ?
