### ISSUE TITLE
Allow per-repository customization of the name of BUILD/BUILD.bazel file

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#16707]
### Description of the feature request:

It would be nice if each repository could tell how BUILD/BUILD.bazel files are called.

The "official" way of pulling in external dependencies is using external repositories, but reality is that a lot of code bases vendor their dependencies into their source trees. If those dependencies contain BUILD files, there is a high probability that they are not actually usable in their vendored form.

This could be worked around by calling BUILD files differently in each such "composite" repository.

Counter-arguments:
1. It's easier to deal with this by changing the import script so that BUILD files are deleted / renamed when one vendors a source tree
2. Customizable BUILD file names would make it difficult for IDEs to determine that the file is, in fact, a BUILD file
3. It's confusing for humans

I'm leaning towards _not_ implementing this unless there are convincing arguments that the alternative approach of changing import scripts is globally worse.

**Comment by lberki** [comment]
cc @brandjon @comius

**Comment by brandjon** [comment]
Discussed offline with lberki@. Marking P4 for reference but may be bumped higher if we determine this use case is compelling.
