### ISSUE TITLE
Windows Build 5.3.2 issues

### ISSUE THREAD

**Issue by dibakch** [bazelbuild/bazel#16719]
I'm running Bazel via Bazelisk on a Windows test machine.  Upgrading from 5.3.0 to 5.3.2 does not seem to work and running `bazelisk build ...` results in a noop without any output or any files written.

Minimal example (without Bazelisk):
```
T:>curl -o bazel-5.3.2 https://releases.bazel.build/5.3.0/release/bazel-5.3.2-windows-x86_64.exe 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0100   127  100   127    0     0     42      0  0:00:03  0:00:03 --:--:--    35

T:>bazel-5.3.2 version
```
This command does not show any output.

Any ideas for how to debug this further?  Was there a change in how the release is build, e.g., static linking vs dynamic linking?

**Comment by fmeum** [comment]
@meteorcloudy Could 5.3.2 be affected by the recently fixed Windows build issue?

**Comment by meteorcloudy** [comment]
Cool, let me know if you have other questions, I'll close this one for now.

**Comment by dibakch** [comment]
To fix this issue you can use the newest version of the [vcredist140 package via choco](https://community.chocolatey.org/packages/vcredist140).
