### ISSUE TITLE
[C++] Exclusion markers not working during run bazel coverage

### ISSUE THREAD

**Issue by Changqing-JING** [bazelbuild/bazel#16716]
### Description of the bug:

// LCOV_EXCL_START and // LCOV_EXCL_STOP not working when run bazel coverage.

### Which operating system are you running Bazel on?

Ubuntu 22.04

**Comment by sgowroji** [comment]
Hello @Changqing-JING, Could you please provide a minimal steps followed in reproducing the above issue with a sample example code. Thanks !

**Comment by Changqing-JING** [comment]
Hello @sgowroji, 
Sorry due to my network problem this ticket is not correctly created. The correct one is
https://github.com/bazelbuild/bazel/issues/16718

**Comment by sgowroji** [comment]
Thanks can we close this issue ?

**Comment by Changqing-JING** [comment]
Yes, we can close this one and continue in #16718
