### ISSUE TITLE
[bazel.build] Problem with /install/ubuntu

### ISSUE THREAD

**Issue by jwhpryor** [bazelbuild/bazel#16726]
Trying to install a fresh install on both Debian and Ubuntu I'm unable to install Bazel onto the stock image of a cloud VM from Google. 

When I run `sudo apt update && sudo apt install bazel` from the instructions I get: 

Hit:1 http://us-west1.gce.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://us-west1.gce.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://us-west1.gce.archive.ubuntu.com/ubuntu bionic-backports InRelease [83.3 kB]
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
Fetched 172 kB in 0s (499 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
19 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package bazel

**Comment by meteorcloudy** [comment]
You'll have to add Bazel's APT repository by following https://bazel.build/install/ubuntu#install-on-ubuntu
