### ISSUE TITLE
`print` statements are deduplicated in Bazel 6.0.0rc1

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#16721]
### Description of the bug:

With Bazel 6.0.0rc1, calling `print` multiple times with the same message in the same location results in only a single line being printed.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```shell
$ touch WORKSPACE
$ echo '[print(x) for x in ["foo", "bar", "foo"]]' > BUILD.bazel
$ USE_BAZEL_VERSION=5.3.2 bazel build //...
DEBUG: .../BUILD.bazel:1:7: foo
DEBUG: .../BUILD.bazel:1:7: bar
DEBUG: .../BUILD.bazel:1:7: foo
$ USE_BAZEL_VERSION=6.0.0rc1 bazel build //...
DEBUG: .../BUILD.bazel:1:7: foo
DEBUG: .../BUILD.bazel:1:7: bar
```

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

6.0.0rc1

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by fmeum** [comment]
My local bisect points to 3f5edd841ef1af7a65793df6a1a1d0d68b689d97.

@justinhorvitz Is it possible that 3f5edd841ef1af7a65793df6a1a1d0d68b689d97 resulted in events being deduped if they compare equal?

**Comment by justinhorvitz** [comment]
Quite possibly. I can see how that change might affect print statements. I will look into this.

**Comment by justinhorvitz** [comment]
`--notrack_incremental_state` still prints twice because it doesn't store the events and bypasses the deduplication filter. Also, print statements within a rule's implementation function will still print multiple times for different rules, since the event gets "tagged" with the rule label.

I'll try to restore the previous behavior.

**Comment by justinhorvitz** [comment]
There's another curious case which as far as I can tell never worked. Two different packages call the same macro in a bzl file, and that calls print. That was always deduplicated because it was from different sky functions (assuming no other prints or other events involved).

**Comment by fmeum** [comment]
@justinhorvitz Thanks for the quick fix! Could you cherry-pick it to the `release-6.0.0` branch?

**Comment by meteorcloudy** [comment]
@bazel-io fork 6.0.0

**Comment by kshyanashree** [comment]
> Yes, I think we should cherry pick this one

Hello @meteorcloudy! Here we are #16762. Thanks!
