### ISSUE TITLE
Path to copts include in external repo

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#1672]
I have the following library:

```
cc_library(
  name = "foo",
  copts = ["-I", "abs/repo/path"],
```

which is in `new_local_repository` `blub`.

Now trying to compile `@blub//:foo` if fails since source cannot find headers of `abs/repo/path`.
It probably would have to be `external/blub/abs/repo/path` but I cannot seem to find any way of retrieving that path (`location` is only working with labels).

Can anyone point me to the docs or tell me how one is supposed to do this?

**Comment by kchodorow** [comment]
This is a little complicated. For now, you could hard-code `external/blub/abs/repo/path` as workaround. #1681 will change the location to `../blub/abs/repo/path`.  At that point, it might make sense to add a skylark function or something that can resolve this relative to the local repository.

**Comment by lucaquerella** [comment]
Hi everyone :)

`external/name` used to work with Bazel 4.5 but I can't make it work with master anymore, I've also tried `../name` as suggested here but it doesn't work for me. 

At the moment, as work around, I'm hardcoding the full path in in my local machine but I can't share the project with my colleagues anymore :/ - do you have a better suggestion? 

Thanks!

**Comment by kchodorow** [comment]
It's still external/name. Are you adding the files as a dependency to your cc_library? What's the error you're getting? Do you have a reproducible test case you can share?

**Comment by abergmeier-dsfishlabs** [comment]
Closing since I will close account.

**Comment by likan999** [comment]
If it is "-Iexternal/blub/abs/repo/path", then if I build it within the blub repository, it won't work.
Do you mean it has to be ["-Iexternal/blub/abs/repo/path", "-Iabs/repo/path"] ?
