### ISSUE TITLE
incompatible_strict_conflict_checks

### ISSUE THREAD

**Issue by tjgq** [bazelbuild/bazel#16729]
Turning on this flag forbids the creation of nested artifacts (where one is a prefix of the other). For example, a regular artifact referring to a file inside a tree artifact, or a tree artifact referring to a subdirectory of another tree artifact. They are currently allowed as long as they're both produced by the same action.

When the flag is flipped, nested artifacts will produce an error:

```
One of the output paths 'blaze-out/k8-fastbuild/bin/foo' (belonging to //:foo) and 'blaze-out/k8-fastbuild/bin/foo/bar' (belonging to //:foo) is a prefix of the other. These actions cannot be simultaneously present; please rename one of the output files or build just one of them
```

Nested artifacts create unnecessary complications for sandboxing and input prefetching, and we would prefer not to support them. To migrate, rules that consume the inner artifact should be modified to consume the outer artifact instead.

**Comment by keith** [comment]
@tjgq I don't believe the linked downstream pipeline [mentioned here](https://github.com/bazelbuild/bazel/pull/16864) ran with your commit, If you look at this job:

https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1346#0184bbc5-53e8-476c-9b39-f84daa8de193

You see:

```
2022/11/28 02:12:05 Using unreleased version at commit 1af61b21df99edc2fc66939cdf14449c2661f873
```

And it appears to me that this sha was a few commits before your change on master flipping this to true: https://github.com/bazelbuild/bazel/compare/1af61b21df99edc2fc66939cdf14449c2661f873...d5880ddf6d9af228a9ce87603edc723201c25ae2

It appears this change broke rules_apple ([example failure](https://buildkite.com/bazel/rules-apple-darwin/builds/6432#0184c0c8-92f5-40d6-9bf8-224736b9bafd)), but if I'm right about it not running on the correct sha I suppose it could have broken other projects as well.

**Comment by tjgq** [comment]
The bazelisk-plus-incompatible-flags pipeline explicitly sets the incompatible flags on the command line; it's meant to be run *before* submitting the flag flip CL (see https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1346#0184bbc5-53e8-476c-9b39-f84daa8de193 and look for `Running Bazel with --incompatible_strict_conflict_checks`).

What happened here is that `--incompatible_strict_conflict_checks` was badly implemented, and setting it doesn't invalidate the build (!), so we got the cached results for the build without the flag set.

So you are right, rules_apple is broken, and so could be any other downstream projects. I'll roll back the flag flip for now; thanks for noticing this.

**Comment by meteorcloudy** [comment]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/4171702/204842642-d5692b62-df8d-4aed-9cfa-34cd386f8029.png">

It looks like in the latest run, the rules_apple breakage was detected: https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1349

But no other projects failing.

**Comment by meteorcloudy** [comment]
Did the caching issue got fixed by https://github.com/bazelbuild/bazel/pull/16822?

**Comment by tjgq** [comment]
No, #16822 is unrelated to this. I have an internal CL to fix the caching issues when the value of `--incompatible_strict_conflict_checks`. I suppose the pipeline might sometimes work, depending on the order in which things run. Either way, it's definitely not safe to flip the flag at this time.

**Comment by tjgq** [comment]
Yes, I'm still planning to flip this for Bazel 7.0, but we're not ready to start migrating yet (I need to fix the issue described in https://github.com/bazelbuild/bazel/issues/16729#issuecomment-1330340176 first).
