### ISSUE TITLE
when setting up bazel on ubuntu running on ARM64, getting "bazel-real: cannot execute binary file: Exec format error"

### ISSUE THREAD

**Issue by juliays** [bazelbuild/bazel#16748]
### Description of the bug:

downloaded bazel-4.2.3-installer-darwin-arm64.sh and bazel-5.3.2-installer-darwin-arm64.sh and followed [instructions]( https://bazel.build/install/ubuntu) using binary installer to set up.

Getting this error when running the installer bash script for both installer versions - 

**_Uncompressing....../home/vscode/bin/bazel: line 220: /home/vscode/.bazel/bin/bazel-real: cannot execute binary file: Exec format error_**

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run this script on an ubuntu VM running on arm64 macbook. This is based on set up instructions [here](https://bazel.build/install/ubuntu#:~:text=Installing%20Bazel%20on%20Ubuntu%201%20Step%201%3A%20Add,...%203%20Step%203%3A%20Install%20a%20JDK%20%28optional%29) using the binary installer. 

    sudo apt install g++ unzip zip -y
    sudo apt-get install openjdk-11-jdk -y
    #wget https://github.com/bazelbuild/bazel/releases/download/5.3.2/bazel-5.3.2-installer-darwin-arm64.sh
    #chmod +x bazel-5.3.2-installer-darwin-arm64.sh
    #./bazel-5.3.2-installer-darwin-arm64.sh --user
    wget https://github.com/bazelbuild/bazel/releases/download/4.2.3/bazel-4.2.3-installer-darwin-arm64.sh
    chmod +x bazel-4.2.3-installer-darwin-arm64.sh
    ./bazel-4.2.3-installer-darwin-arm64.sh --user
    export PATH="$PATH:$HOME/bin"

### Which operating system are you running Bazel on?

ubuntu

### What is the output of `bazel info release`?

doesn't run because it failed ruing set up

### Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?
 complete command run output

```
songy@ubuntu:~$ ./bazel-5.3.2-installer-darwin-arm64.sh --user
Bazel installer
---------------

Bazel is bundled with software licensed under the GPLv2 with Classpath exception.
You can find the sources next to the installer on our release page:
   https://github.com/bazelbuild/bazel/releases

# Binary package at HEAD (@bc087f49584a6a6)
   - [Commit](https://github.com/bazelbuild/bazel/commit/bc087f49584a6a6)
Uncompressing....../home/songy/bin/bazel: line 220: /home/songy/.bazel/bin/bazel-real: cannot execute binary file: Exec format error
/home/songy/bin/bazel: line 220: /home/songy/.bazel/bin/bazel-real: Success
```

**Comment by meteorcloudy** [comment]
> Run this script on an ubuntu VM running on arm64 macbook.

Have you tried to run the Bazel arm64 binary on a actual Linux arm64 machine? I'm guessing you are running a docker container on arm64 macbook? That might cause this issue.

**Comment by juliays** [comment]
I don't have a Linux arm64 machine. I need to get it working in a container. What's the difference? What's involved making it working in a container? Thanks!

**Comment by meteorcloudy** [comment]
If you are in a ubuntu VM, you probably should install Bazel with the Linux installer: https://github.com/bazelbuild/bazel/releases/download/5.3.2/bazel-5.3.2-installer-linux-x86_64.sh
