### ISSUE TITLE
exec_properties in constraint_values do not propagate

### ISSUE THREAD

**Issue by moroten** [bazelbuild/bazel#16742]
### Description of the bug:

The field `exec_properties` in a [constraint_value](https://bazel.build/reference/be/platform#constraint_value) does not propagate to remote execution.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Example code:
```
# BUILD.bazel
constraint_setting(name = "gpu")

constraint_value(
    name = "gpu_blue",
    constraint_setting = ":gpu",
    exec_properties = {"gpu": "blue"},
)

constraint_value(
    name = "gpu_green",
    constraint_setting = ":gpu",
    exec_properties = {"gpu": "green"},
)

platform(
    name = "blue_hardware",
    constraint_values = [":gpu_blue"],
    exec_properties = {"os": "linux"},
)

genrule(
    name = "foo",
    srcs = [],
    outs = ["foo.txt"],
    cmd = "echo foo > \"$@\"",
    tools = [],
)
```
then run
```
> bazel build :foo --host_platform=//:blue_hardware --remote_executor=grpc://localhost:8980
INFO: Invocation ID: 4c832268-f309-46da-87d2-47f3bf732580
INFO: Analyzed target //:foo (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /tmp/constraint_value_test/BUILD.bazel:29:8: Executing genrule //:foo failed: (Exit 34): UNAVAILABLE: No workers exist for instance name prefix "" platform {"properties":[{"name":"os","value":"linux"}]}
Target //:foo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.468s, Critical Path: 3.38s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

Expected: {"properties":[{"name":"os","value":"linux"}, {"name":"gpu", "value":"blue"}]}
Actual: {"properties":[{"name":"os","value":"linux"}]}

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 5.3.2

### Have you found anything relevant by searching the web?

No relevant GitHub issue or bazel-discuss thread with the word `exec_properties` apart from a question about 
[Toolchain specific exec_properties](https://groups.google.com/g/bazel-discuss/c/YeEsT4q037c/m/CoZmpaR1AgAJ).

**Comment by coeuvre** [comment]
@katre I saw your comment in https://github.com/bazelbuild/bazel/issues/16743#issuecomment-1313950393 saying that `exec_properties` attribute in `toolchain` will be removed. Is that also true for `exec_properties` in `constraint_values`?

**Comment by katre** [comment]
Yes, that will also be removed. What actions do you expect to get the `exec_properties` from a `constraint_value` target?

**Comment by moroten** [comment]
As I wrote in the description, I though it was logical to set `exec_properties` for e.g. GPU in the `constraint_value` if the GPU is reused in multiple platforms. This is handy when defining your own `constraint_values`. On the other hand, different remote execution systems might define `exec_properties` differently and it would be difficult to override third-party `constraint_values`, much easier to enumerate all available execution platforms. I'm happy with having it removed.
