### ISSUE TITLE
How can i query which repository the indirect-repository is added by？

### ISSUE THREAD

**Issue by ywsswy** [bazelbuild/bazel#16744]
### Description of the bug:

I find `@some_rep_a//:xxx` in some repository's BUILD file, but don't know what & where `some_rep_a` it is.

The `WORKSPACE` file use git_repository rule to add external repositories, such as `some_rep_b`, `some_rep_c`, but no 
`some_rep_a`.
I guess that the `some_rep_a` may be added in `some_rep_x`'s `WORKSPACE` file, or other repository's `WORKSPACE` file else.
How can i query which repository `some_rep_a` is added by？

So what i expected is that the result could be showed like this:
```
> bazel query where_is @some_rep_a
the root repository add `some_rep_x`,
the repository `some_rep_x` add `some_rep_y`,
the repository `some_rep_y` add `some_rep_a`
```
or
```
> bazel query where_is @some_rep_a
root -> `some_rep_x` -> `some_rep_y` -> `some_rep_a`
```

Do this so I can finally know `some_rep_a`'s git_url/tag/branch in `some_rep_y`'s `WORKSPACE` file.

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

release 3.7.2

**Comment by fmeum** [comment]
Does `bazel query --output=build //external:some_rep_a` provide the output your are looking for?

**Comment by ywsswy** [comment]
@fmeum Yes it is, thank you very much.
