### ISSUE TITLE
executable bit not being set with (--remote_download_minimal or --remote_download_toplevel) and --define=apple.experimental.tree_artifact_outputs=1

### ISSUE THREAD

**Issue by codeman9** [bazelbuild/bazel#16754]
### Description of the bug:

Prior to this commit: https://github.com/bazelbuild/bazel/commit/dfccbf975358da93a5ef0fe0f9438873e2a06ee5, our iOS app was getting the executable bit set, as it should. After that commit, the app no longer has the executable bit set. This only happens using either `--remote_download_minimal` or `--remote_download_toplevel`.

There may be a correlation to this flag: `--define=apple.experimental.tree_artifact_outputs=1`. (see repro steps)

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

[incremental-alley.zip](https://github.com/bazelbuild/bazel/files/9993666/incremental-alley.zip)

```bash
# .bazelversion
b8d0e26357065740d4007223cf20f488a120290e
# ^--- Works no matter what

# dfccbf975358da93a5ef0fe0f9438873e2a06ee5
# ^--- Doesn't work with --remote_download_toplevel and --define=apple.experimental.tree_artifact_outputs=1

# 6.0.0rc1
# and later
# ^--- Doesn't work with --remote_download_toplevel and --define=apple.experimental.tree_artifact_outputs=1
```

Between trials below, be sure to `bazel clean` and when going from Works -> Doesn't work and back, be sure to `rm -rf ~/.bazel_cache_incremental_alley`

Works as expected:

1) Unzip the attached

```bash
# .bazelrc
build \
  --disk_cache=~/.bazel_cache_incremental_alley \
  --execution_log_json_file=tmp/logs/execution.json \
  --features=swift.partially_explicit_modules \
  --features=swift.use_global_module_cache \
  --swiftcopt=-enable-incremental-imports \
  --remote_download_toplevel
```

2) Run `bazel build :IncrementalAlley-iOS`
3) Change the name of `bazel-out/applebin_ios-ios_sim_arm64-fastbuild-ST-9c82d69884d3/bin/Modules/iOSApp/IncrementalAlley-iOS.ipa` to `/private/var/tmp/_bazel_user/3af7db76104a2df6189bfd78bfcdce2e/execroot/__main__/bazel-out/applebin_ios-ios_sim_arm64-fastbuild-ST-9c82d69884d3/bin/Modules/iOSApp/IncrementalAlley-iOS.zip` and unzip
4) `ls -l bazel-out/applebin_ios-ios_sim_arm64-fastbuild-ST-9c82d69884d3/bin/Modules/iOSApp/Payload/IncrementalAlley-iOS.app/IncrementalAlley-iOS`

Observe something like the following (notice the executable bits set): 

```bash
-rwxr-xr-x  1 user  staff  121808 Jan  1  1980 /private/var/tmp/_bazel_user/3af7db76104a2df6189bfd78bfcdce2e/execroot/__main__/bazel-out/applebin_ios-ios_sim_arm64-fastbuild-ST-9c82d69884d3/bin/Modules/iOSApp/Payload/IncrementalAlley-iOS.app/IncrementalAlley-iOS
```

Works as expected:

1) Unzip the attached

```bash
# .bazelrc
build \
  --disk_cache=~/.bazel_cache_incremental_alley \
  --execution_log_json_file=tmp/logs/execution.json \
  --features=swift.partially_explicit_modules \
  --features=swift.use_global_module_cache \
  --swiftcopt=-enable-incremental-imports
  # removed --remote_download_toplevel
```

2) Run `bazel build :IncrementalAlley-iOS`
3) Change the name of `bazel-out/applebin_ios-ios_sim_arm64-fastbuild-ST-9c82d69884d3/bin/Modules/iOSApp/IncrementalAlley-iOS.ipa` to `/private/var/tmp/_bazel_user/3af7db76104a2df6189bfd78bfcdce2e/execroot/__main__/bazel-out/applebin_ios-ios_sim_arm64-fastbuild-ST-9c82d69884d3/bin/Modules/iOSApp/IncrementalAlley-iOS.zip` and unzip
4) `ls -l bazel-out/applebin_ios-ios_sim_arm64-fastbuild-ST-9c82d69884d3/bin/Modules/iOSApp/Payload/IncrementalAlley-iOS.app/IncrementalAlley-iOS`

Observe something like the following (notice the executable bits set): 

```bash
-rwxr-xr-x  1 user  staff  121808 Jan  1  1980 /private/var/tmp/_bazel_user/3af7db76104a2df6189bfd78bfcdce2e/execroot/__main__/bazel-out/applebin_ios-ios_sim_arm64-fastbuild-ST-9c82d69884d3/bin/Modules/iOSApp/Payload/IncrementalAlley-iOS.app/IncrementalAlley-iOS
```

Works as expected:

1) Unzip the attached

```bash
# .bazelrc
build \
  --disk_cache=~/.bazel_cache_incremental_alley \
  --execution_log_json_file=tmp/logs/execution.json \
  --features=swift.partially_explicit_modules \
  --features=swift.use_global_module_cache \
  --swiftcopt=-enable-incremental-imports \
  --define=apple.experimental.tree_artifact_outputs=1 # <--- added this flag which skips the .ipa and creates .app
```

2) Run `bazel build :IncrementalAlley-iOS`
3) Change the name of `bazel-out/applebin_ios-ios_sim_arm64-fastbuild-ST-9c82d69884d3/bin/Modules/iOSApp/IncrementalAlley-iOS.ipa` to `/private/var/tmp/_bazel_user/3af7db76104a2df6189bfd78bfcdce2e/execroot/__main__/bazel-out/applebin_ios-ios_sim_arm64-fastbuild-ST-9c82d69884d3/bin/Modules/iOSApp/IncrementalAlley-iOS.zip` and unzip
4) `ls -l bazel-out/applebin_ios-ios_sim_arm64-fastbuild-ST-9c82d69884d3/bin/Modules/iOSApp/IncrementalAlley-iOS.app/IncrementalAlley-iOS`

Observe something like the following (notice the executable bits set) (also notice that the write flag is no longer set): 

```bash
-r-xr-xr-x  1 user  staff  121808 Jan  1  1980  /private/var/tmp/_bazel_user/3af7db76104a2df6189bfd78bfcdce2e/execroot/__main__/bazel-out/applebin_ios-ios_sim_arm64-fastbuild-ST-9c82d69884d3/bin/Modules/iOSApp/IncrementalAlley-iOS.app/IncrementalAlley-iOS
```

Does not work as expected:

1) Unzip the attached

```bash
# .bazelrc
build \
  --disk_cache=~/.bazel_cache_incremental_alley \
  --execution_log_json_file=tmp/logs/execution.json \
  --features=swift.partially_explicit_modules \
  --features=swift.use_global_module_cache \
  --swiftcopt=-enable-incremental-imports \
  --remote_download_toplevel \ # <--- added this back
  --define=apple.experimental.tree_artifact_outputs=1 # <--- added this flag which skips the .ipa and creates .app
```

2) Run `bazel build :IncrementalAlley-iOS`
3) Change the name of `bazel-out/applebin_ios-ios_sim_arm64-fastbuild-ST-9c82d69884d3/bin/Modules/iOSApp/IncrementalAlley-iOS.ipa` to `/private/var/tmp/_bazel_user/3af7db76104a2df6189bfd78bfcdce2e/execroot/__main__/bazel-out/applebin_ios-ios_sim_arm64-fastbuild-ST-9c82d69884d3/bin/Modules/iOSApp/IncrementalAlley-iOS.zip` and unzip
4) `ls -l bazel-out/applebin_ios-ios_sim_arm64-fastbuild-ST-9c82d69884d3/bin/Modules/iOSApp/IncrementalAlley-iOS.app/IncrementalAlley-iOS`

Observe something like the following (notice the executable bits are not set): 

```bash
-rw-r--r--  1 user  staff  121808 Jan  1  1980  /private/var/tmp/_bazel_user/3af7db76104a2df6189bfd78bfcdce2e/execroot/__main__/bazel-out/applebin_ios-ios_sim_arm64-fastbuild-ST-9c82d69884d3/bin/Modules/iOSApp/IncrementalAlley-iOS.app/IncrementalAlley-iOS
```

### Which operating system are you running Bazel on?

macOS Ventura 13.0

### What is the output of `bazel info release`?

2022/11/11 15:34:12 Using unreleased version at commit b8d0e26357065740d4007223cf20f488a120290e INFO: Invocation ID: 8a3b1297-1269-45f1-8ed9-87a8abe14154 development version

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

Using bazelisk

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
git@github.com:bazelbuild/bazel.git
839ce7f5c40240d8b6f49c416c3769e226f43fee
839ce7f5c40240d8b6f49c416c3769e226f43fee
```

### Have you found anything relevant by searching the web?

Not really. There are some issues regarding executable bits like this one: https://github.com/bazelbuild/bazel/issues/12137 but it didn't seem exactly relevant.

**Comment by keith** [comment]
cc @tjgq

**Comment by keith** [comment]
hopefully @codeman9 who did the work here can test that one

**Comment by codeman9** [comment]
@tjgq Using this commit has solved this issue. Thanks!

**Comment by coeuvre** [comment]
Thanks for confirming!
