### ISSUE TITLE
can not found third_party dependency

### ISSUE THREAD

**Issue by fansehep** [bazelbuild/bazel#16768]
### Description of the bug:

We have a rpc project. He relies on a number of other open source projects. The other source projects don't provide the bazel build. so we write the rules. but when we want to make it be a third_party to depend. The bazel give us many erros. can not found ourself rules for other projects.
a workspace dep like :
```c++
http_archive(
    name = "com_github_madler_zlib",  # 2017-01-15T17:57:23Z
    build_file = "//bazel/third_party/zlib:zlib.BUILD",
    sha256 = "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1",
    strip_prefix = "zlib-1.2.11",
    urls = [
        "https://downloads.sourceforge.net/project/libpng/zlib/1.2.11/zlib-1.2.11.tar.gz",
        "https://zlib.net/fossils/zlib-1.2.11.tar.gz",
    ],
)
```
![2022-11-15_14-11-1668495269](https://user-images.githubusercontent.com/75058860/201910845-5aab3487-0d35-449c-a30a-0ad287826052.jpg)

but we have write the build file in WORKSPACE.
bazel version: 4.2.2

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

ok, the opensource workspace is in https://github.com/apache/incubator-brpc/blob/master/WORKSPACE.

we can create a easy project workspace like this:
```c++
git_repository(
    name = "apache_brpc",
    branch = "release-1.3",
    remote = "https://github.com/apache/incubator-brpc",
)
```
and can add file deps like:
```
cc_test(
   ...
   deps = [
    "@apache_brpc//:bthread",
  ],
)
```

### Which operating system are you running Bazel on?

docker debian9

**Comment by Wyverald** [comment]
Have you tried asking our support channels, such as bazel-discuss@googlegroups.com and the Slack server (slack.bazel.build)?
