### ISSUE TITLE
ArrayIndexOutOfBoundsException when using macOS watchfs

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#1676]
We enabled `--watchfs` by default at our organization, and got the following stack trace.

```
java.lang.ArrayIndexOutOfBoundsException: 605134
    at com.google.devtools.build.lib.skyframe.MacOSXFsEventsDiffAwareness.poll(Native Method)
    at com.google.devtools.build.lib.skyframe.MacOSXFsEventsDiffAwareness.getCurrentView(MacOSXFsEventsDiffAwareness.java:103)
    at com.google.devtools.build.lib.skyframe.DiffAwarenessManager.getDiff(DiffAwarenessManager.java:90)
    at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.handleDiffs(SequencedSkyframeExecutor.java:339)
    at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.sync(SequencedSkyframeExecutor.java:265)
    at com.google.devtools.build.lib.runtime.CommandEnvironment.setupPackageCache(CommandEnvironment.java:371)
    at com.google.devtools.build.lib.runtime.commands.QueryCommand.exec(QueryCommand.java:88)
    at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:488)
    at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:324)
    at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:49)
    at com.google.devtools.build.lib.server.RPCService.executeRequest(RPCService.java:70)
    at com.google.devtools.build.lib.server.AfUnixServer.executeRequest(AfUnixServer.java:418)
    at com.google.devtools.build.lib.server.AfUnixServer.serve(AfUnixServer.java:215)
    at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:737)
    at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:519)
    at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)
```

<details><summary>

bazel version</summary>

```
Build label: 0.3.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 29 09:05:18 2016 (1469783118)
Build timestamp: 1469783118
Build timestamp as int: 1469783118
```

</details>

**Comment by damienmg** [comment]
Hi Dan,

This is most probably happening at this line: https://github.com/bazelbuild/bazel/blob/master/src/main/native/fsevents.cc#L132 

However it is unclear why this is happening. Can you tell me more about the circumstances of the failure? 605134 seems like a large number of paths for a single poll. Were their a large number of files changed at once?

**Comment by dfabulich** [comment]
We don't have a reliable repro case for this, but perhaps knowing that it has to do with a large number of paths for a single poll, that can help us repro the bug.

**Comment by damienmg** [comment]
Ok I will wait for more info. Thanks for reporting it!

**Comment by dfabulich** [comment]
How often does it poll? Does the server poll in the background even if I'm not executing Bazel commands, or does it wait to drain the poll until a build starts?

**Comment by damienmg** [comment]
Apparently only on command. This would explain why the number of change is so important.

**Comment by dfabulich** [comment]
It seems like it would be prudent to use a thread to drain the queue from time to time.

**Comment by damienmg** [comment]
re-ping @haxorz

**Comment by znull** [comment]
I find this is fairly easy to reproduce by

1. having a directory with a lot of files (npm 2 is particularly good at making `node_modules` dirs like this)
2. running bazel build on a target in that package
3. simultaneously running `rm -r node_modules`

**Comment by damienmg** [comment]
I have a pending fix, just need to repro to make sure we actually do fix the problem

**Comment by damienmg** [comment]
Unfortunately I cannot reproduce with a simple example. @znull: if you have a workspace in which you can reproduce this behavior, please send it to me.

I'll send out my patch whatever happens and hopefully this will address this issue.

**Comment by dfabulich** [comment]
Here's a semi-reliable repro. https://github.com/dfabulich/watch-repro

The `WORKSPACE` is empty, and the `BUILD` file is a single target:

```python
genrule(
	name='x',
	srcs=glob(['data/*.txt']),
	outs=['x.txt'],
	cmd='echo hello > $@',
)
```

`repro.sh` is a bash script:

```bash
#!/bin/sh
mkdir -p data
DATE=`date`
for I in {1..100000}; do
	echo $I $DATE > data/$I.txt
done
bazel build :x & rm -rf data
```

When I run `./repro.sh` I have about a 75% chance of reproing this AIOOBE on OS X El Capitan 10.11.6

<details><summary>bazel version</summary>
```
$ bazel version
INFO: Reading 'startup' options from /private/tmp/tp/watch-repro/tools/bazel.rc: --watchfs
Build label: 0.3.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Oct 7 17:25:52 2016 (1475861152)
Build timestamp: 1475861152
Build timestamp as int: 1475861152

```
</details>

**Comment by damienmg** [comment]
Ok that's basically what I was trying but with a bit less files.

**Comment by damienmg** [comment]
Thanks for the repro, it worked.

**Comment by damienmg** [comment]
Seems like https://bazel-review.googlesource.com/c/6613/2 fixes it, neat :)

**Comment by damienmg** [comment]
And weirdly enough https://bazel-review.googlesource.com/c/6614/2 seems to fix it too. I am going ahead and will submit the flag change. If you still get that ISE after please ping back. I'll leave that bug open until milestone 0.6 for following-up

**Comment by dfabulich** [comment]
I'm confused by the state of this issue. It doesn't look like 6613/2 or 6614/2 actually merged in? The bug repros in Bazel 0.4.0.

**Comment by damienmg** [comment]
6613/2 is merged, if you repro with 0.4.0, is it with the given repro? I was not able to repro after testing. I keep that bug open because it is not easy to say if that's actually fixed.

**Comment by dfabulich** [comment]
Yeah, I just ran the same repro on my Mac. It took three tries. (LMK if you need a new stack trace.)

**Comment by dfabulich** [comment]
ping?

**Comment by damienmg** [comment]
Sorry I had no time to work on it. I'll try to give a quick look ASAP but do not expect news before next week.

**Comment by jmmv** [comment]
I'm currently looking into this. Could reproduce and might have found what the problem is.
