### ISSUE TITLE
Feature request: an official "file" rule?

### ISSUE THREAD

**Issue by ahyangyi** [bazelbuild/bazel#1677]
I need some simple "file" rule that allows me to put content to files:

```
file(
   name = "a.txt",
   content = "Hello, world!",
   )
```

But simple as it is, I can't seem to actually find an official rule for it. Making a custom rule is simple enough (by using a simple `file_action`), but shouldn't a rule simple as this be included in the official distribution?

**Comment by davido** [comment]
Try this:

```
genrule(
    name = "a",
    cmd = "echo 'Hello, world!' >$@",
    outs = ["a.txt"],
)
```

**Comment by ahyangyi** [comment]
That's exactly what I'm using. But for a file with multiple lines, I need careful escaping newlines and special characters.

That's fine, but a bit time consuming, and ultimately not very satisfactory when I still need to maintain that messy genrule now and then.

**Comment by kchodorow** [comment]
You could probably use HEREDOC, but I don't think creating a multiline file in your BUILD file is a great idea.  If it starts getting complicated it should probably live in an sh_binary anyway.

**Comment by ahyangyi** [comment]
@kchodorow Maybe I need to clarify it a bit. I'm using `http_archive`s with a supplied `BUILD` file. Said `http_archive` is a source pack and I need to build it with a customized configuration. So I want to provide my version of `config.h` instead of running `configure` which is not portable across machines.

In this case, how could a `sh_binary` help? A multiline shell script that lives in a separate file is even more messy than a messy BUILD file, and how can I reference that file from the external repository created by `http_archive` at all?

**Comment by ahyangyi** [comment]
@kchodorow  Now I think my question should be "how can I make extra files available in an external workspace created in `http_archive`?"

Providing an official `file` rule is an easy way to do that, but maybe it's not optimal, as you have argued.

**Comment by kchodorow** [comment]
There are a couple of options.  You could do something like:

```
new_http_archive(
    ...
    build_file_content = """
cc_library(
    name = "my-source-pack",
    ...
    hdrs = ["@//:config.h"],
)
""",
)
```

And then, in your main repository's top-level BUILD file, you'd say `exports_files(["config.h"])` (or create a cc_library that you depend on from the my-source-pack rule).

Alternatively, you could write a skylark repository rule, which lets you add any files you want to the external repository, e.g.,

```
def _impl(repo_ctx):
  repo_ctx.download_and_extract(...)
  repo_ctx.file('BUILD', content = ...)
  repo_ctx.file('config.h', content = ...)

my_source_lib = repository_rule(
  implementation = _impl,
  local = False,
)
```

(See https://www.bazel.io/versions/master/docs/skylark/lib/repository_ctx.html for ref.)

**Comment by ahyangyi** [comment]
I see. I'll go with the first solution as it seems to go with Bazel's usual idiom. Thanks a lot, Kristina.

**Comment by kchodorow** [comment]
You're welcome!
