### ISSUE TITLE
[bazel.build] Problem with /reference/be/general: view source went to wrong place

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#16778]
I wanted to contribute an edit to the genrule documentation, but the "View Source" button goes to https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/docgen/templates/be/rules.vm which seems like a velocity template that dynamically pulls the content.
Ideally this page would need a view source on each of the rules that goes to the actual text for that rule: https://github.com/bazelbuild/bazel/blob/2ee79b8946559bead113db042dccc85b106c1c8f/src/main/java/com/google/devtools/build/lib/bazel/rules/genrule/BazelGenRuleRule.java#L68

**Comment by fweikert** [comment]
There is now a "view rule source" button for every rule.
