### ISSUE TITLE
Bazel's Java version parsing is too restrictive

### ISSUE THREAD

**Issue by ascenator** [bazelbuild/bazel#1678]
I am trying to compile Bazel from source. However, Bazel complains that it can not determine the Java version:

```
-bash-4.2$ ./compile.sh 
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel

🍃  Building Bazel from scratch
Cannot determine JDK version, please set $JAVA_HOME.
```

This is pretty strange to me, because Java _is_ installed and $JAVA_HOME is set:

`echo $JAVA_HOME`:
`/sw/env/system-gcc/oracle-jdk8/8u66`

`java -version`:
```
Java HotSpot(Tbash -c 'java -version'
M) 64-Bit Server VM warning: Insufficient space for shared memory file:
   27818
Try using the -Djava.io.tmpdir= option to select an alternate temp location.

java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```

`which java`:
`/sw/env/system-gcc/oracle-jdk8/8u66/bin/java`

`bash -c 'java -version'`:
```
Java HotSpot(TM) 64-Bit Server VM warning: Insufficient space for shared memory file:
   21095
Try using the -Djava.io.tmpdir= option to select an alternate temp location.

java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```

Any ideas?

**Comment by JonathanxD** [comment]
Make sure you're using JDK not JRE, or try to use OpenJDK instead of OracleJDK.

**Comment by ascenator** [comment]
`java -version` and `javac -version` do work, thus I assume JDK is installed correctly. `JDK8u66` is supplied by the administrators of the cluster I am trying to build bazel on. However, I have just manually downloaded `JDK8u101` and stored it to a directory of my user and adjusted the environment variables:
`which java` now points to `/work/my-user/jdk1.8.0_101/bin/java` and `$JAVA_HOME` as well as `$PATH` is set correctly.

`java -version` and `javac -version` now return `1.8.0_101`...

...but running `./compile.sh` still complains:

```
-bash-4.2$ ./compile.sh 
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch
Cannot determine JDK version, please set $JAVA_HOME.
```

**Comment by JonathanxD** [comment]
Version pattern is not matching version correclty.
https://github.com/bazelbuild/bazel/blob/master/scripts/bootstrap/buildenv.sh#L241

**Comment by ascenator** [comment]
So you think this might be a bug in Bazel?

**Comment by JonathanxD** [comment]
Yes.

**Comment by katre** [comment]
I've updated the title to be more descriptive. I'll try and take a look at this today.

**Comment by katre** [comment]
@ascenator: Can you provide the exact output of "javac -version" for your JDK? I'm trying to see why it's different than the JDKs I have access to here.

**Comment by ascenator** [comment]
```
javac -version
Java HotSpot(TM) 64-Bit Server VM warning: Insufficient space for shared memory file:
   22707
Try using the -Djava.io.tmpdir= option to select an alternate temp location.

javac 1.8.0_101
```

For some reason (bug) the default tmpdir on the cluster (SLURM environment) is currently pretty busy. Thus, this "insufficient space" message appears and the regex that looks for the java version fails. I've built bazel by commenting several lines and manually specified the java version & paths.

I guess making the regex more robust would solve the problem.

**Comment by katre** [comment]
That entire message is in stdout? Odd. I'll see what can be done.

**Comment by ascenator** [comment]
Yep. Really strange. It is somehow related to the SLURM environment on the cluster. Normally some $WORK/tmp should be used, so seperated tmp's for each user. Instead, the system's main /tmp is used and pretty busy. Thus, Java complains about /tmp being full...and for some reason Java responds to stdout, not stderr.
