### ISSUE TITLE
--local_test_jobs causes bazel to ignore local resource limitations

### ISSUE THREAD

**Issue by drewmacrae** [bazelbuild/bazel#16786]
### Description of the bug:

I apply a cpu:4 tag to a set of sh_tests that requires 4 cores to run without timing out. When I set `--local_tests_jobs` the tests are dispatched regardless of the requirement.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run 2 sh_tests that "sleep 10" with a cpu:1000 tag and `--local_tests_jobs=2` on a multicore system and observe that they finish in ~10s total.

### Which operating system are you running Bazel on?

Rolling debian testing Rodette

### What is the output of `bazel info release`?

release 5.3.2

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
https://github.com/bazelbuild/bazel
d2aaf0cd66f10745aedee16330c2c053b848a507
ea1646d8d58f5252e55bb891b5eaee67778f23c7
```

### Any other information, logs, or outputs that you want to share?

This is related to and motivated by work on https://github.com/bazelbuild/bazel/pull/16785 but affects bazel in general and the cpu tag in an undocumented way.

**Comment by drewmacrae** [comment]
Here's what it says in the docs:
"[--local_test_jobs](https://docs-staging.bazel.build/2338/versions/0.29.1/command-line-reference.html#flag--local_test_jobs)=<an integer, or a keyword ("auto", "HOST_CPUS", "HOST_RAM"), optionally followed by an operation ([-|*]<float>) eg. "auto", "HOST_CPUS*.5"> default: "auto"
The max number of local test jobs to run concurrently. Takes an integer, or a keyword ("auto", "HOST_CPUS", "HOST_RAM"), optionally followed by an operation ([-|*]<float>) eg. "auto", "HOST_CPUS*.5". 0 means local resources will limit the number of local test jobs to run concurrently instead. Setting this greater than the value for --jobs is ineffectual."

It does document that if 0, local resource limitations will limit the number, which implies that if non-zero they might not, but it's not explicitly stated, and having the cpu:n tags become a no-op isn't so user friendly and contradicts the spec here: https://bazel.build/reference/test-encyclopedia#other-resources

**Comment by DavidANeil** [comment]
I ran into this too.  I only figured out what was going on by reading the bazel source code.
