### ISSUE TITLE
Make it possible to express desired Xcodes and sdks as platform constraints

### ISSUE THREAD

**Issue by blorente** [bazelbuild/bazel#16783]
### Description of the feature request:

Currently, Bazel offers configuration flags (`--xcode_version`, `--macos_sdk_version`...) to select which of the (potentially conflicting) Xcode installations to use.

However, we would like to offer Xcode configurations (Xcode and SDK versions) as platform constraints, to be able to select toolchains and other things on them. The global flags get in the way of it.

To do that, we'd like Bazel to ignore those global flags, and listen instead to a platform definition we provide, through the usual platform and toolchain codepaths.

As a bonus, this would provide nicer and easier to debug error messages.

### What underlying problem are you trying to solve with this feature?

We would like to offer Xcode configurations (Xcode and SDK versions) as platform constraints, to be able to select toolchains and other things on them. The global flags get in the way of it.

### Which operating system are you running Bazel on?

macOS, for the purposes of this issue.

### What is the output of `bazel info release`?

Currently running 5.3.2

**Comment by katre** [comment]
What do you envision these constraints looking like? To be honest, I'm not convinced that constraints are the right solution here: what xcode version to use isn't a factor of the host platform or the target platform, it's something the developer should decide. My ideal solution would be to make these build settings, but add machinery to targets like `ios_application` to set the correct levels.

**Comment by aiuto** [comment]
cc: @keith @brentleyjones You may want to weigh in on this.
