### ISSUE TITLE
error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by HITalexwang** [bazelbuild/bazel#1679]
I am trying to build tensorflow from source
When building the pip package with bazel, I got this error: invalid command 'bdist_wheel'

But I have python 2.7.5 and wheel 0.29.0 in my linux, could you help me out？

The commit hash (git rev-parse HEAD):6d04d601e9e8758ec4642fa9d548b7321d804d63
The output of bazel version:0.3.1
Logs:

[yxwang@gpu02 tensorflow]$ wheel version
wheel 0.29.0
[yxwang@gpu02 tensorflow]$ python -V
Python 2.7.5
[yxwang@gpu02 tensorflow]$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
Tue Aug 23 10:37:26 EDT 2016 : === Using tmpdir: /tmp/tmp.OMZ3S3VXj1
/tmp/tmp.OMZ3S3VXj1 ~/local/tensorflow
Tue Aug 23 10:37:27 EDT 2016 : === Building wheel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help

error: invalid command 'bdist_wheel'

**Comment by damienmg** [comment]
Hello, sorry this is not a Bazel bug.

I suggest you file a bug report to TensorFlow at https://github.com/tensorflow/tensorflow
