### ISSUE TITLE
Malformed link to module in node based project build

### ISSUE THREAD

**Issue by ProPablo** [bazelbuild/bazel#16790]
### Description of the bug:

Hello, recently tried to build this repo: https://github.com/lewish/asciiflow and had issues regarding webpack. Never used bazel so I  am a bit unfamiliar with how to fix this, and it could potentially be an issue with the repo itself. As the readme advises, I have installed bazelisk and simply ran `bazel run client:devserver`. 

I had some issues with wsl, same as this issue: https://github.com/bazelbuild/bazel/issues/10941 but I resolved them by running `$env:Path = 'C:\Program Files\Git\bin;' + $env:Path` and using git bash in that terminal. 

Here is the output I get with that:
```
bazel run client:devserver
INFO: Invocation ID: 02d91e64-8286-458b-a7d1-e8c60e054d3f
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/02d91e64-8286-458b-a7d1-e8c60e054d3f
INFO: Analyzed target //client:devserver (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //client:devserver up-to-date:
  bazel-bin/client/devserver.sh
  bazel-bin/client/devserver_loader.js
  bazel-bin/client/devserver_require_patch.js
  bazel-bin/client/devserver.bat
INFO: Elapsed time: 1.291s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Running command line: bazel-bin/client/devserver.bat '--config=client/webpack.config.js' '--output=./app.bundle.js'
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/02d91e64-8286-458b-a7d1-e8c60e054d3f
INFO: Build completed successfully, 1 total action
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'c:\users\anhad\_bazel~1\mnlrl4uj\execroot\asciif~1\bazel-~1\x64_wi~1\bin\client\devser~2.run\client\webpack.config.js'
- c:\users\anhad\_bazel~1\mnlrl4uj\execroot\asciif~1\node_modules\webpack-cli\bin\utils\convert-argv.js
- c:\users\anhad\_bazel~1\mnlrl4uj\execroot\asciif~1\node_modules\webpack-dev-server\bin\webpack-dev-server.js
- D:\asciiflow\node_modules\import-local\index.js
- D:\asciiflow\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at WEBPACK_OPTIONS (c:\users\anhad\_bazel~1\mnlrl4uj\execroot\asciif~1\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (c:\users\anhad\_bazel~1\mnlrl4uj\execroot\asciif~1\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at c:\users\anhad\_bazel~1\mnlrl4uj\execroot\asciif~1\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (c:\users\anhad\_bazel~1\mnlrl4uj\execroot\asciif~1\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at Object.<anonymous> (c:\users\anhad\_bazel~1\mnlrl4uj\execroot\asciif~1\node_modules\webpack-dev-server\bin\webpack-dev-server.js:84:40) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\users\\anhad\\_bazel~1\\mnlrl4uj\\execroot\\asciif~1\\node_modules\\webpack-cli\\bin\\utils\\convert-argv.js',
    'c:\\users\\anhad\\_bazel~1\\mnlrl4uj\\execroot\\asciif~1\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js',
    'D:\\asciiflow\\node_modules\\import-local\\index.js',
    'D:\\asciiflow\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'
  ]
}
```
Not too sure what this entails but it seems like the module path is badly malformed as the correct path it wants to link to is 
`C:\Users\anhad\_bazel_anhad\mnlrl4uj\execroot\asciiflow\client`. I have noticed that this is a symlink back to the original repository if that helps.

Thank you

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

git pull https://github.com/lewish/asciiflow and run `bazel run client:devserver`.

### Which operating system are you running Bazel on?

Windows 10

### What is the output of `bazel info release`?

INFO: Invocation ID: 0cfeb006-d39a-4891-a272-22b8ea6c2358 release 3.3.0

### Have you found anything relevant by searching the web?

I've tried searching several things including "webpack malformed url bazel", "typescript malformed url bazel", this seems to be the closest thing but their URI seems to be correct: https://stackoverflow.com/questions/71760604/imports-from-tsconfig-paths-not-working-with-bazel-cannot-find-module.

**Comment by meteorcloudy** [comment]
This is likely an problem with rules_nodejs not working well on Windows, please file an issue against https://github.com/bazelbuild/rules_nodejs
