### ISSUE TITLE
File downloads are extremely slow

### ISSUE THREAD

**Issue by KimiNewt** [bazelbuild/bazel#16807]
### Description of the bug:

When bazel has to download a file, whether through `http_archive` or otherwise, it downloads very slowly (on the order of 10KBps), when downloading the same file via browser or another way on the same machine produces significantly higher speeds (~100MBps). 

This seems to be repeating itself on many machines on our project.

### Which operating system are you running Bazel on?

Linux Mint 21 and also macOS 12.6.1

### What is the output of `bazel info release`?

release 5.2.0

### Have you found anything relevant by searching the web?

No

**Comment by sgowroji** [comment]
Hello @KimiNewt, Could you please provide minimal steps to reproduce the above issue. Thanks !

**Comment by Wyverald** [comment]
Without more data, this is impossible to triage.
