### ISSUE TITLE
Race in bazel run means command output is sometimes lost

### ISSUE THREAD

**Issue by Timmmm** [bazelbuild/bazel#16811]
### Description of the bug:

For very fast binaries, sometimes `bazel run :binary` sometimes does not show the output of the binary. It seems to depend on how long the binary runs for - adding `sleep()`s in the code seems to make it reliably but that's obviously pretty shitty. This suggests to me there is a race in `test-setup.sh` which doesn't seem that surprising given that it is a long and complicated Bash script (I was quite surprised to find such a hack given Bazel's focus on reliability!).

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Fortunately this is easy to reproduce.

1. Create this `BUILD.bazel`:

```
cc_test(
    name = "foo",
    srcs = [
        "foo.cpp",
    ],
)
```

2. Create an empty `WORKSPACE.bazel`

3. Create this `foo.cpp`:

```
#include <iostream>
#include <thread>
#include <chrono>

int main(int argc, char* argv[]) {
  std::this_thread::sleep_for (std::chrono::milliseconds(1));

  std::cout << "Hello world\n";
  return 0;
}
```

Run `bazel run :foo` a bunch of times. Depending on the `sleep_for()` value it will output `Hello world` a certain percentage of the time like this:

```
INFO: Analyzed target //:foo (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:foo up-to-date:
  bazel-bin/foo
INFO: Elapsed time: 0.077s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //:foo
-----------------------------------------------------------------------------
Hello world
```

And some of the time it will not output anything:

```
INFO: Analyzed target //:foo (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:foo up-to-date:
  bazel-bin/foo
INFO: Elapsed time: 0.074s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //:foo
-----------------------------------------------------------------------------
```

For me, 0 delay means it almost always *doesn't* print `Hello world`. 1 ms means it's about 50:50, and 1 second means it always prints it.

### Which operating system are you running Bazel on?

MacOS 12.5.1 (on an M1 Mac)

### What is the output of `bazel info release`?

release 5.3.0-homebrew

### Have you found anything relevant by searching the web?

No

**Comment by Timmmm** [comment]
Also with the following code:

```
#include <iostream>
#include <thread>
#include <chrono>

int main(int argc, char* argv[]) {
  for (int i = 0; i < 1000; ++i) {
      std::cout << i << "\n";
  }
  std::this_thread::sleep_for (std::chrono::milliseconds(10));
  return 0;
}
```

It sometimes just cuts off the output and adds a `%` at the end like this:

```
...
630
631
632
633
634
635
6%                                                                                                                                                        
```

**Comment by meisterT** [comment]
@Timmmm are you able to repro this with bazel from HEAD?

**Comment by Timmmm** [comment]
Yep. Well I haven't compiled HEAD but I tried with 6.0.0. I don't have access to a Mac anymore but I was able to reproduce it in WSL. It's not as common as it was before and I didn't see a %, but I did see cut off output and no output a couple of times.

Was there something that changed that should have fixed it?

**Comment by brentleyjones** [comment]
I believe a change on HEAD (maybe one of the 7.0 rolling releases?) has a fix for this.

**Comment by meisterT** [comment]
@Timmmm you could use Bazelisk with `last_green` (see https://github.com/bazelbuild/bazelisk#how-does-bazelisk-know-which-bazel-version-to-run) to confirm it is fixed at head.

**Comment by meisterT** [comment]
I assume this is fixed by https://github.com/bazelbuild/bazel/commit/c04f0d41317bfe1f6ff42da94dddb4023587fc26 - @Timmmm, can you please verify?

**Comment by Timmmm** [comment]
Yep works for me!
