### ISSUE TITLE
Enable tests that require exclusive access to hardware to be run without the exclusive tag.

### ISSUE THREAD

**Issue by drewmacrae** [bazelbuild/bazel#16817]
### Description of the feature request:

In OpenTitan, we use bazel to coordinate and direct tests, and we have long running tests on simulators and on FPGAs. The FPGA tests require exclusive access to attached FPGAs, but don't conflict with any of the non-FPGA actions in our WORKSPACE.
https://github.com/bazelbuild/bazel/pull/16785 and it's predecessors offer a means to introduce extra resources like our fpga boards and issue tests in parallel with other actions, but without issuing multiple tests that require the FPGAs.

I can't find an open issue referenced in this work so I'm writing it up

### What underlying problem are you trying to solve with this feature?

We're trying to make our WORKSPACE aware of resource limitations that aren't covered by the CPU/Memory limits and aren't covered by "exclusive" tags or controlling the number of jobs without incurring a large overhead.

### Which operating system are you running Bazel on?

Rolling debian testing Rodette

### What is the output of `bazel info release`?

release 5.3.2

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
https://github.com/bazelbuild/bazel
d2aaf0cd66f10745aedee16330c2c053b848a507
ea1646d8d58f5252e55bb891b5eaee67778f23c7
```

### Have you found anything relevant by searching the web?

More discussion here: https://github.com/bazelbuild/bazel/pull/16785

**Comment by eric-skydio** [comment]
I think this is resolved now, if #17229 works
