### ISSUE TITLE
genrule() not triggered when srcs changed

### ISSUE THREAD

**Issue by sageyun1057** [bazelbuild/bazel#16825]
### Description of the bug:

I use genrule to make some cpp/ header files. (hidl-gen for android's .hal)
But when I change .hal, genrule is not triggered.

My BUILD file simply looks like this

genrule(
    name = "test_genrule",
    srcs = [
        "temp.cpp",
    ],
    outs = [
        "test.cpp",
    ],
    cmd = """
          ORG=$$PWD;
          echo ORG : $$ORG
          echo GENDIR : $(GENDIR)
          touch $(GENDIR)/test.cpp
          echo touch $(GENDIR)/test.cpp
        """
)

cc_library(
    name = "test_lib",
    srcs = [
        "test.cpp",
    ],
    deps = [
        ":test_genrule",
    ],
)

I want that when I change temp.cpp, genrule() works and test.cpp should made.
But 
echo ORG : $$ORG
echo GENDIR : $(GENDIR)
is not shown when I change temp.cpp

### Which operating system are you running Bazel on?

ubutu 20.04

### What is the output of `bazel info release`?

bazel 6.0.0-pre.20220823.1

**Comment by sgowroji** [comment]
Hello @sageyun1057, Could you please provide an example to reproduce the above issue. Thanks!

**Comment by fmeum** [comment]
I can't reproduce this with the following reproducer:
```
# WORKSPACE
# BUILD.bazel
genrule(
    name = "test_genrule",
    srcs = [
        "temp.cpp",
    ],
    outs = [
        "test.cpp",
    ],
    cmd = """
ORG=$$PWD;
echo ORG : $$ORG
echo GENDIR : $(GENDIR)
touch $(GENDIR)/test.cpp
echo touch $(GENDIR)/test.cpp
""",
)

cc_library(
    name = "test_lib",
    srcs = [
        "test.cpp",
    ],
)
```

Listing `:test_genrule` in the `deps` of `test_lib` gives an error as `genrule` doesn't provide `CcInfo`, so I had to remove that bit.

Now, `USE_BAZEL_VERSION=6.0.0-pre.20220823.1 bazel build //:test_lib` prints the `ORG` and `GENDIR` lines if and only if I changed the contents of `temp.cpp` before the build.

@sageyun1057 Could you clarify the issue or let me know what changes I need to make to the reproducer to encounter the issue?

**Comment by sageyun1057** [comment]
@fmeum 
In my environ, I didn't show CcInfo error.
So, I test on other environment with your code.
But I also can't show echo `ORG`, `GENDIR`....
![image](https://user-images.githubusercontent.com/54614655/203525522-61dd327c-e52a-4d5a-965f-f596683a3107.png)

TO test it.
1. I copy your `BUILD.bazel` and touch `WORKSPACE`
2. remove temp.cpp to newly build
3. touch temp.cpp and build bazel :test_lib -> `ORG / GENDIR `printed
4. touch temp.cpp and build bazel :test_lib -> `ORG / GENDIR` is not printed

**Comment by fmeum** [comment]
@sageyun1057 Bazel doesn't necessarily rerun actions if the mtime of an input changes: It will hash the file and not rerun actions of the contents are identical. In order to test this properly, you thus have to make a non-trivial edits to the file.

**Comment by sageyun1057** [comment]
@fmeum 
Thanks for your reply.
I understand it.
This issue was a sample to simplify matters.
I will create an issue that is exactly right for my situation.
