### ISSUE TITLE
[Mirror] Archives for rules_go 0.36.0

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel#16833]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/golang/sys/archive/refs/tags/v0.2.0.zip
https://github.com/googleapis/go-genproto/archive/16455021b5e60501e2adf67e15f857d2f5d95388.zip
https://github.com/bazelbuild/rules_go/releases/download/v0.36.0/rules_go-v0.36.0.zip

**Comment by sgowroji** [comment]
Please find the below mirror artifacts are

1. https://mirror.bazel.build/github.com/golang/sys/archive/refs/tags/v0.2.0.zip
2.https://mirror.bazel.build/github.com/googleapis/go-genproto/archive/16455021b5e60501e2adf67e15f857d2f5d95388.zip
3.https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.36.0/rules_go-v0.36.0.zip
