### ISSUE TITLE
[Mirror] rules_rust 0.13.0

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/bazel#16835]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/rules_rust/releases/download/0.13.0/rules_rust-v0.13.0.tar.gz

**Comment by sgowroji** [comment]
Please find the below mirror artifact

1. https://mirror.bazel.build/github.com/bazelbuild/rules_rust/releases/download/0.13.0/rules_rust-v0.13.0.tar.gz
