### ISSUE TITLE
Add `--incompatible` flag that disables transitions to host configuration

### ISSUE THREAD

**Issue by jfirebaugh** [bazelbuild/bazel#16840]
### Description of the feature request:

Add an `--incompatible` flag that disables transitions to the "host" configuration (e.g. `--incompatible_disable_host_configuration`), for projects that wish to enforce use of the "exec" configuration.

### What underlying problem are you trying to solve with this feature?

I [recently debugged an issue](https://bazelbuild.slack.com/archives/CA31HN1T3/p1669245285806309) where build-time tools (e.g. `genrule` `tools` or `run_binary` `tool`) were getting spuriously recompiled. The cause turned out to be `genrule` targets that were using `tools` rather than `exec_tools`, and not having a recent enough version of bazel-skylib to include https://github.com/bazelbuild/bazel-skylib/commit/67bfa0ce4de5d4b512178d5f63abad1696f6c05b.

After fixing these issues, I'd like to be able to ensure that nobody reintroduces use of the host configuration inadvertently. Given that the host configuration is deprecated per the note [here](https://bazel.build/extending/rules#configurations), I think it makes sense to have a flag that can be enabled in projects which have completed the transition to the exec configuration, to avoid backsliding.

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 5.3.2

**Comment by gregestren** [comment]
Hi @jfirebaugh - note that "host" has been an alias for "exec" for some time. i.e. `tools` is an alias for `exec_tools`.

I'm trying to find the commit history to figure out which version of Bazel that takes effect. I also believe before then there was a flag doing as you suggest.

**Comment by gregestren** [comment]
Okay, so https://github.com/bazelbuild/bazel/commit/d988e8b3bace4b2bb2ec4adc17d9bf7b4f49a907 changed `genrule.tools` from the host to exec config on Jan 11, 2022.

Note similar changes to other rules around the same time: https://github.com/search?q=org%3Abazelbuild+%22Change+host+transitions+to+execution+transitions%22&type=commits.

https://github.com/bazelbuild/bazel/commit/6e6c4cf1bd6edaa15ecc4417cd0be70581181def updated Starlark rules around the same time.

There's also https://github.com/bazelbuild/bazel/commit/6464f1cbdf14f0b8e8f29f7b57990a40ea584062 which adds `--incompatible_disable_starlark_host_transitions` to make .bzl declarations `cfg = "host"` illegal.

There's no flag to disable *all* host configs. But if you can use Bazel 6.0 or newer you should find it's impossible to actually instantiate host configs. Would you be able to simply upgrade Bazel?
