### ISSUE TITLE
QNX with Bazel

### ISSUE THREAD

**Issue by DhanalakshmiDurairaj** [bazelbuild/bazel#16846]
### Description of the bug:

QNX compiler tries to write lock file in the file system during sandbox execution.  Host file system is read only in bazel during sandbox execution. How to enable the compiler to write file in the file system? without writing files, compiler is not working. How to fix this issue?

Acquisition timed out after 10 seconds. Check that the file and containing folder have write permissions set for this user, and that no other processes are using this file

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Please provide minimal example if possible

### Which operating system are you running Bazel on?

Linux 18.04

### What is the output of `bazel info release`?

bazel 5.0.0

**Comment by fmeum** [comment]
Where exactly does it write the file? You can use `--sandbox_tmpfs_path` to make a particular directory writable in the sandbox without interfering with the host system.

**Comment by sgowroji** [comment]
Hello @DhanalakshmiDurairaj, Could you please provide minimal steps to reproduce the above error. Thanks !

**Comment by DhanalakshmiDurairaj** [comment]
> Where exactly does it write the file? You can use `--sandbox_tmpfs_path` to make a particular directory writable in the sandbox without interfering with the host system.

Thank you so much for your response. I tried this option. 

The gave the below command in .bazelrc
build --sandbox_tmpfs_path=path/to/license/directory

But I get the following error regarding license 


# Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
license check failed
Target //main:hello-world failed to build
INFO: Elapsed time: 0.304s, Critical Path: 0.02s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully


solution
I tried this option

build --sandbox_writable_path=path/to/license/directory

It is working 

Thank you for your support

**Comment by larsrc-google** [comment]
Sounds like you got it worked out, great!
