### ISSUE TITLE
Add realpath method for Skylark repositories

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel#1685]
It would be great to have a method in Skylark, similar to Python's [`os.path.realpath`](https://docs.python.org/2/library/os.path.html#os.path.realpath).

There are use cases where we want to resolve the canonical path for a file pointed to by a symlink. One example of this is getting the canonical CUDA header path to set in the TensorFlow CROSSTOOL file (see tensorflow/tensorflow#3985). The main problem with just shelling out is that `readlink -f` is not compatible with OS X. Bazel itself uses a [number of wrapper scripts](https://github.com/bazelbuild/bazel/search?utf8=%E2%9C%93&q=readlink) to work around this issue.

**Comment by damienmg** [comment]
@davidzchen : can you precise: you want that for a remote repository (for SkylarkPath) or for artifacts in rules?

**Comment by davidzchen** [comment]
For my use case, I would like that for a remote repository. Specifically, the default CUDA install path on a system is `/usr/local/cuda`, but that is a symlink to `/usr/local/cuda-<version>`, and in order to fix tensorflow/tensorflow#3985, we need to resolve the symlink to the canonical path and add it to the CROSSTOOL file as a `cxx_builtin_include_directory` entry.

**Comment by damienmg** [comment]
Ok so this confirmed this is for remote repository. Retriaging
