### ISSUE TITLE
[bazel.build] Problem with /install/completion

### ISSUE THREAD

**Issue by andersroos** [bazelbuild/bazel#16855]
Hi, where are the auto completion files if you install with bazelisk?

**Comment by sgowroji** [comment]
Hello @andersroos, Could you please elaborate your issue with complete details and followed urls or resources.

**Comment by andersroos** [comment]
Yes, sorry, this is not a really a bug report, it is more of a question.

Here you recommend using Bazelisk to install Bazel: https://bazel.build/install

Not 100% sure what is going on, but it seems like everything is contained in a fat binary or possibly it is downloading stuff and putting it somewhere. I want autocomplete to work in zsh and here you describe how to do that: https://bazel.build/install/completion

However none of those describe how to do it when using Bazelisk, so how do I do it in that case?

**Comment by keertk** [comment]
Hi @andersroos since this isn't a bug report/feature request, we're closing this issue. You can use our [Slack](https://slack.bazel.build) for more discussions and questions, as well as our [Google Group](https://groups.google.com/g/bazel-discuss).
Thank you!
