### ISSUE TITLE
Missing linkopts when building a cc_test

### ISSUE THREAD

**Issue by stnma7e** [bazelbuild/bazel#16877]
### Description of the bug:

I noticed recently that a cc_test that I am using in the Android Bazel rules doesn't seem to respect the linkopts flag. I think I tracked down where this is coming from. I ran a bisection to find that the error started when the incompatible_unambiguous_label_stringification flag flipped to default to true.

I noticed that the [_filter_libraries_that_are_linked_dynamically](https://github.com/bazelbuild/bazel/blob/master/src/main/starlark/builtins_bzl/common/cc/cc_binary.bzl#L375) function was filtering out the LinkerInput for the `cc_test` that I was building. All of the deps (and their flags) were being added to the LinkerInputs list properly, but the cc_test target itself (and its flags) were being filtered out. I noticed that when incompatible_unambiguous_label_stringification is set to True then the output of _get_canonical_form(ctx.label) is no longer [equal to owner](https://github.com/bazelbuild/bazel/blob/master/src/main/starlark/builtins_bzl/common/cc/cc_binary.bzl#L402) because the former is missing the leading @ in the target name. By making a change in _get_canonical_form I was able to make my error go away.

I don't have a ton of context on the incompatible_unambiguous_label_stringification change, but it seems to me that the [strings in two lines](https://github.com/bazelbuild/bazel/blob/master/src/main/starlark/builtins_bzl/common/cc/cc_binary.bzl#L371) could be flipped? Right now it says

```
def _get_canonical_form(label):
    repository = label.workspace_name
    if repository == "@":
        repository = ""
    return repository + "//" + label.package + ":" + label.name
```

and my errors went away when I changed this to

```
def _get_canonical_form(label):
    repository = label.workspace_name
    if repository == "":
        repository = "@"
    return repository + "//" + label.package + ":" + label.name
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I was encountering this when working on [Bazel for Android](https://source.android.com/docs/setup/build/bazel/introduction), but I wasn't able to make a minimal reproduction. 

### What is the output of `bazel info release`?

This issue started happening at this commit (determined via bisect): b1113f801da87ed2e089ff4122aa13400c177804

**Comment by stnma7e** [comment]
I have a fix pending that I've discussed with @meteorcloudy, Xudong, and Giorgi to replace `_get_canonical_form(label)` with `_str(label)`.

**Comment by meteorcloudy** [comment]
@bazel-io fork 6.0.0
