### ISSUE TITLE
incompatible_exclusive_test_sandboxed: flip

### ISSUE THREAD

**Issue by gasparev** [bazelbuild/bazel#16871]
Tests tagged with `exclusive` cannot use sandboxing and/or remote caching.  This behavior was not intended and was a leftover from open-sourcing Bazel. See https://github.com/bazelbuild/bazel/issues/3791.
From release 4.0 users could conditionally enable sandboxing and remote caching for the `exclusive` tag with `--incompatible_exclusive_test_sandboxed`.

- What's going to change? The default value of `--incompatible_exclusive_test_sandboxed` used to be False. It will change to True.
- How to update your code? If a test fails, use `--noincompatible_exclusive_test_sandboxed` to keep the old behavior.

**Comment by gasparev** [comment]
@meteorcloudy can you `incompatible-change` and `migration-ready` here, please?

**Comment by meteorcloudy** [comment]
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/4171702/204547991-226f0265-c8c1-4cc2-be0c-baea618614eb.png">
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1348

Looks like we can safely flip this one. ;)
