### ISSUE TITLE
[6.0.0] Missing linkopts when building a cc_test

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#16878]
Forked from #16877

**Comment by meteorcloudy** [comment]
@kshyanashree Please cherry pick https://github.com/bazelbuild/bazel/commit/cd40666001e8d599bb61735898c195c6d2fae55b to close this one, thanks!

**Comment by meteorcloudy** [comment]
After cherry pick this one, we can create rc3 ;)

**Comment by kshyanashree** [comment]
> @kshyanashree Please cherry pick [cd40666](https://github.com/bazelbuild/bazel/commit/cd40666001e8d599bb61735898c195c6d2fae55b) to close this one, thanks!

Hi @meteorcloudy ! I have already cherry-picked this one here , but  pre-submit is failing due to missing CLA #16886 . Wanted to check with you. Thanks!

**Comment by Wyverald** [comment]
For some reason the original commit was showing up as being authored by "noreply@google.com", which can't pass the CLA check. I think we can just force merge that PR.

**Comment by Wyverald** [comment]
Merged in #16886

Let's create an rc3!

**Comment by kshyanashree** [comment]
Sure, Thanks @Wyverald!
