### ISSUE TITLE
Stop using absl flags in python based helpers

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#16882]
### Technical debt

We depend on absl flags instead of argparse in many android helpers.
We could switch to argparse to reduce footprint.

- [x] tools/build_defs/pkg/build_tar.py
- [ ] tools/android/incremental_install.py
- [ ] tools/android/strip_resources.py
- [ ] tools/android/instrumentation_test_check.py
- [ ] tools/android/aar_embedded_jars_extractor.py
- [ ] tools/android/aar_resources_extractor.py
- [ ] tools/android/aar_embedded_proguard_extractor.py
- [ ] tools/android/build_split_manifest.py
- [ ] tools/android/stubify_manifest.py
- [ ] tools/android/aar_native_libs_zip_creator.py
- [ ] tools/aquery_differ/aquery_differ.py
- [x] tools/jdk/proguard_whitelister.py
- [ ] tools/ctexplain/ctexplain.py

**Comment by idanakav** [comment]
Apart from tech debt, I'm noticing an issue as well in `tools/android/incremental_install.py` after parsing the `extra_adb_arg` will end up with duplicated values if they are read from a `flagfile`.

**Comment by limdor** [comment]
Is it limited to these files? I'm asking because I saw is used in scripts/generate_fish_completion.py
I created a PR for it https://github.com/bazelbuild/bazel/pull/18407

**Comment by aiuto** [comment]
> Is it limited to these files?
It only pays back the effort if done in the helpers. That reduces the size of the Bazel image and eliminates one runtime dependency.
