### ISSUE TITLE
Remote execution cannot cope with large tree artifacts

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#16899]
### Description of the bug:

When an action creates a tree artifact of many tiny files, Bazel takes a lot of time trying to execute it, then fails anyway with the following error message:

```
ERROR: <redacted>/BUILD:3:2: Action r/d failed: (Exit 34): Remote Execution Failure:
Internal: failed to upload outputs: failed to upload files: rpc error: code = Unknown desc = while trimming the cache: cannot fit -- the incoming items (100001 files, 794006 bytes) exceeds the cache limits (70000 files, 53687091200 bytes)
  Unrecognized error detail: type_url: "type.googleapis.com/google.devtools.remotebuildbot.CommandStatus"
value: "\b\n
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The following Starlark code:

```
cat > r.bzl <<'EOF'
def _r_impl(ctx):
    ta = ctx.actions.declare_directory("d")
    ctx.actions.run(
        outputs = [ta],
        inputs = [],
        executable = ctx.executable._gen,
        arguments = [ta.path],
    )
    return [DefaultInfo(files = depset([ta]))]

r = rule(
    implementation = _r_impl,
    attrs = {
        "_gen": attr.label(default = "//r:gen", executable = True, cfg = "exec"),
    },
)
EOF

cat > BUILD <<'EOF'
load(":r.bzl", "r")

r(name = "ta")
EOF

cat > gen.sh <<'EOF'
#!/bin/bash

OUT="$1"
mkdir -p "$OUT"

for i in $(seq 1 10); do
  for j in $(seq 1 100); do
    for k in $(seq 1 100); do
      mkdir -p "$OUT/$i/$j"
      echo "$i $j $k" > "$OUT/$i/$j/$k"
    done
  done
done
echo hello > "$OUT/hello"
EOF

chmod +x gen.sh
```

Then running

`bazel build <args to make it run things remotely> :ta`

It's debatable whether tree artifacts of 100K files are useful, but at least erroring out early wold be nice.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 5.3.2

**Comment by meisterT** [comment]
I assume the 70k files limit comes from the specific RBE implementation that you used, not Bazel. There is currently no way to query for this, so nothing that Bazel can do about it.

**Comment by lberki** [comment]
Ack. The error message could probably simpler to understand, though. Given that *I* had no clue what it means, I assume others won't, either (not that this would rank the bug above P3, but still)
