### ISSUE TITLE
About resources for java_test

### ISSUE THREAD

**Issue by is03wlei** [bazelbuild/bazel#1689]
From the page https://www.bazel.io/docs/be/java.html#java_test 
It's said that:
If that is not found, Bazel then looks for the topmost directory named "java" or "javatests" (so, for example, if a resource is at <workspace root>/x/java/y/java/z, Bazel will use the path y/java/z. This heuristic cannot be overridden.

I think 'topmost' here contradicts with y/java/z.
If it's topmost,then the path should be x/java/y.
By the way, right bracket missed here.

**Comment by jin** [comment]
@lberki do you mind verifying this? is the documentation wrong?

**Comment by lberki** [comment]
As I read it, the documentation is right, but I can see how it could be misunderstood and the closing parentheses is indeed missing. Let me send a change...
