### ISSUE TITLE
Handle SIGINT correctly with "blaze run"

### ISSUE THREAD

**Issue by claridge** [bazelbuild/bazel#169]
If "bazel run" is terminated with SIGINT, then it kills the child process with something other than SIGINT. (I suspect it's using SIGKILL, but I'm not sure how to confirm that other than finding the right place in the Bazel code.)

More details at https://groups.google.com/d/topic/bazel-discuss/I6TWUv8AI5o/discussion.

**Comment by helenalt** [comment]
Re-triaged, still a P3

**Comment by meisterT** [comment]
This seems done:
```
WARNING:root:Sleeping for 10 seconds
^CWARNING:root:Handling SIGINT
```
