### ISSUE TITLE
[bazel.build] Problem with /rules/lib/starlark-overview

### ISSUE THREAD

**Issue by dws** [bazelbuild/bazel#16909]
The following entries on this page are duplicated:

[register_execution_platforms()](https://bazel.build/rules/lib/globals#register_execution_platforms())
[register_execution_platforms()](https://bazel.build/rules/lib/globals#register_execution_platforms())
[register_toolchains()](https://bazel.build/rules/lib/globals#register_toolchains())
[register_toolchains()](https://bazel.build/rules/lib/globals#register_toolchains())
[repository_rule(implementation, attrs, local, environ, configure, remotable, doc)](https://bazel.build/rules/lib/globals#repository_rule(implementation,%20attrs,%20local,%20environ,%20configure,%20remotable,%20doc))
[repository_rule(implementation, attrs, local, environ, configure, remotable, doc)](https://bazel.build/rules/lib/globals#repository_rule(implementation,%20attrs,%20local,%20environ,%20configure,%20remotable,%20doc))

**Comment by Wyverald** [comment]
dupe of https://github.com/bazelbuild/bazel/issues/16383
