### ISSUE TITLE
Windows 10 / msys2: cannot remove junction points upon consecutive builds

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#1690]
See https://github.com/bazelbuild/bazel/issues/947#issuecomment-240427984

**Comment by laszlocsomor** [comment]
This bug is rooted in a deeper issue with symlink recognition for dangling junctions. Still investigating.

**Comment by laszlocsomor** [comment]
Found it, fixing in the internal repo, will push to github later.

**Comment by dslomov** [comment]
This is fixed now?

**Comment by laszlocsomor** [comment]
Yes, similar to https://github.com/bazelbuild/bazel/issues/1680#issuecomment-246583954.
