### ISSUE TITLE
Incorrect handling of `#include` paths relative to the WORKSPACE root that includes symlinks

### ISSUE THREAD

**Issue by ton** [bazelbuild/bazel#16926]
### Description of the bug:

Suppose we have some directory structure as follows:

```
WORKSPACE
libs/foo/src/foo.cpp
libs/foo/itf/foo.h
libs/foo/BUILD
foo -> libs/foo
```

Where `foo` in the root directory is a symlink to `libs/foo`. Suppose we have:

foo.h:

```
#pragma once 

void foo();
```

foo.cpp:

```
#include "foo/itf/foo.h"

void foo() {}
```

BUILD:

```
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "foo",
    srcs = ["src/foo.cpp"],
    hdrs = ["itf/foo.h"],
)
```

In this case, `bazel build //...` gives the following error message:

```
Starting local Bazel server and connecting to it...
INFO: Analyzed 2 targets (38 packages loaded, 166 targets configured).
INFO: Found 2 targets...
ERROR: [...]/foo/libs/foo/BUILD:3:11: Compiling libs/foo/src/foo.cpp failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 16 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging

libs/foo/src/foo.cpp:1:10: fatal error: foo/itf/foo.h: No such file or directory
    1 | #include "foo/itf/foo.h"
      |          ^~~~~~~~~~~~~~~
```

I expect the `#include` to resolve to the correct header through the `foo` symlink. Is this a known issue, or am I making some incorrect assumptions?

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See bug description.

### Which operating system are you running Bazel on?

Arch Linux

### What is the output of `bazel info release`?

5.3.2

**Comment by martis42** [comment]
Disclaimer, I am not a Bazel developer or associated with Google.

> Is this a known issue, or am I making some incorrect assumptions?

Bazel executes its actions in a sandbox. Only inputs known to the actions are available in the sandbox. For example source files or files/artifacts from dependencies.
Your cc_library target has no knowledge about the symlink and thus it is not present in the sandbox which causes the compilation to fail.

**Comment by ton** [comment]
@martis42, thank you, that makes sense. Then a natural follow-up question would be, how to make this symlink known to the sandbox? I will do a bit of research, this at least gives me something to investigate, thank you!

**Comment by ton** [comment]
It seems Bazel is thoroughly confused here; even specifying:

```
#include "libs/foo/itf/foo.h"
```

instead of an include through the symlink results in a compiler error saying it cannot find `foo.h`. I need to remove the symlink for it to work...this seems buggy.

**Comment by ton** [comment]
Ok, final update for now; if I put `foo` in `.bazelignore`, at least the

`#include "libs/foo/itf/foo.h`

works, but I would like to be able to specify an `#include` through the symlink there instead, which still does not work after putting `foo` in `.bazelignore`.
