### ISSUE TITLE
[6.0.0] --experimental_remote_download_regex doesn't work with a cache in 6.0.0rc4

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#16923]
Forked from #16922

**Comment by brentleyjones** [comment]
@keertk I believe this is now a blocker again (please see the most recent comments in the linked issue). The title changed in that issue, so we probably want to change this title as well.

**Comment by meteorcloudy** [comment]
Fix cherry picked in https://github.com/bazelbuild/bazel/pull/16958
