### ISSUE TITLE
java_library equivalent of Maven's scope=provided

### ISSUE THREAD

**Issue by tharakadesilva** [bazelbuild/bazel#16929]
We are hitting an issue similar to https://github.com/bazelbuild/bazel/issues/1402. We are creating a set of libraries for our organization and we want something like this:
- Define a header library
- Add multiple implementations for the header to support different frameworks. This is similar to [this](https://github.com/brettwooldridge/HikariCP/tree/dev/src/main/java/com/zaxxer/hikari/metrics).
- We want the dependencies for these to be available during compilation like [this](https://github.com/brettwooldridge/HikariCP/blob/dev/pom.xml#L167), but we don't want to be attached to the library's jar.

https://github.com/bazelbuild/bazel/issues/1402 mentions how to do something similar with `java_binary`, but we need this at the `java_library` level.

You might ask us why not have these implementations in two different `java_library`s. We can't do that right now as that breaks backwards compatibility for our current implementations. Currently our libs are tightly coupled to a single framework and we are trying to remove this coupling while maintaining backwards compatibility. This is to allow our application owners to migrate at their own pace.

So my question is, can we do the Maven's `scope=provided` equivalent in a `java_library`?

**Comment by davido** [comment]
This is a known missing feature in Bazel.

See also [this](https://github.com/bazelbuild/bazel/issues/1402) feature request that was rejected.

It worth noting, that there is a way to achieve dependency exclusion using `deploy_env` in `java_binary` rule. See for example [Gerrit Code Review](https://gerrit.googlesource.com/gerrit) code base how it could be used.

**Comment by hvadehra** [comment]
The semantics of `scope=provided` for a java_library does not make sense to me. I concur with the decision in https://github.com/bazelbuild/bazel/issues/1402 to use `java_binary` and `deploy_env` if absolutely needed.
