### ISSUE TITLE
[Mirror] rules_go 0.37.0

### ISSUE THREAD

**Issue by JamyDev** [bazelbuild/bazel#16934]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/rules_go/releases/download/v0.37.0/rules_go-v0.37.0.zip

**Comment by sgowroji** [comment]
Please find the below mirror url:

https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.37.0/rules_go-v0.37.0.zip
