### ISSUE TITLE
[Mirror] rules_rust 0.11.0

### ISSUE THREAD

**Issue by seanmajorpayne** [bazelbuild/bazel#16940]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/rules_rust/releases/download/0.11.0/rules_rust-v0.11.0.tar.gz

**Comment by sgowroji** [comment]
Please find the below mirror url:

https://mirror.bazel.build/github.com/bazelbuild/rules_rust/releases/download/0.11.0/rules_rust-v0.11.0.tar.gz
