### ISSUE TITLE
query doesn't recurse into remote repos.

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#1694]
looks like query filters out external repo dependencies

$ grep maven_jar WORKSPACE | wc
    111     120    1283
$ bazel query '//...'|grep '@' | wc
      0       0       0

I tried 

 --force_experimental_external_repositories --experimental_external_repositories

to no avail.

**Comment by katre** [comment]
If you query //... it should only query the main repo. If you want to query a specific repo, you should use the 'bazel query @maven//...' syntax.

We should probably figure out a syntax for wildcards for the repo name, or just all repo names, however.

**Comment by hanwen** [comment]
PEBKAC - deps(//...) does recurse into remote repos.
