### ISSUE TITLE
Runfiles tree creation fails on Windows

### ISSUE THREAD

**Issue by ozio85** [bazelbuild/bazel#16955]
### Description of the bug:

The runfiles tree creation currently fails on Windows.

The error is:
ERROR: ../BUILD.bazel:1:10: Creating runfiles tree bazel-out/x64_windows-fastbuild/bin/....exe.runfiles failed: java.io.FileNotFoundException: .../MANIFEST (No such file or directory), However the MANIFEST file is created and exists after the action crashes.

It started in release 6.0.0-pre.20221020.1, and a git bisect shows that #16477 is the culprit.

I will analyze the commit tomorrow, and see what might be the cause

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create an actions.run that use a py_binary tool

### Which operating system are you running Bazel on?

Windows

### What is the output of `bazel info release`?

6.0.0-pre.20221020.1

**Comment by sgowroji** [comment]
Hello @ozio85, Could you please give complete steps to reproduce the above issue. Thanks!

**Comment by brentleyjones** [comment]
@bazel-io flag

**Comment by ozio85** [comment]
Ok SO now i have made a small repro. The bug manifests with remote_cache enable AND remote_download_toplevel set
build:cache --remote_cache=grpc://my.remote.adress:8980
build:cache --remote_instance_name=remote-execution
build:cache --remote_download_toplevel

**Comment by ozio85** [comment]
Note that you have to do a clean build in order to retrigger the runfiles tree build action, and this action has to be run in combination with the remote cache

**Comment by coeuvre** [comment]
I cannot reproduce this on macOS. It seems that the issue only occurs on Windows (because IIRC, MANIFEST based solution is only used for Windows). I will setup a Windows machine tomorrow to investigate more.

**Comment by meteorcloudy** [comment]
@bazel-io fork 6.0.0
