### ISSUE TITLE
bazel build last git commit but not uncommitted changes

### ISSUE THREAD

**Issue by cnsgsz** [bazelbuild/bazel#1695]
I often find myself working on new features, and at the same time want to compile some code from the last git commit. Is there a way in bazel to specify which commit to compile without stashing uncommitted files/checking out that that commit?

**Comment by katre** [comment]
Bazel isn't aware of git directly, and doesn't interact with the repository, just with the filesystem. If this is something you need, you'd want to create your own wrapper script to stash changes and build your target, then unstash them.
