### ISSUE TITLE
Skylark attr type "Function"

### ISSUE THREAD

**Issue by pcj** [bazelbuild/bazel#1696]
It would be useful to support a skylark attribute type "Function" to allow rule implementations to  be configured with user-definable behavior.  For example, I'd like to be able to say:

```python
# external defs.bzl
def _impl(ctx):
   data = {}
   ctx.attr.precompile(ctx, data)

def noop(ctx, data):
   print("I don't do anything with %s" % data)

proto_language = rule(
   implementation = _impl,
   attrs = {
       "precompile": attr.function(default = noop),
   },
)
```

```python
# client BUILD
load("external/:defs.bzl", "proto_language")
load("foo.bzl", "precompile")

proto_language(
   name = "Foo",
   precompile = precompile,
)
```

```python
# client foo.bzl 

def precompile(ctx, data):
    ctx.action(...)

```

The main use case is to be able to design rules where some behavior can originate from the client WORKSPACE, but not violate the load/analyze/execute phase design.  In my case I'd like to avoid having users to specify rules_go as a WORKSPACE dependency unless they really need it, but still support a go_proto_library.

I believe it's possible and within the spirit of bazel, let me know if there is interest for a PR to implement this.

**Comment by laurentlb** [comment]
I'd recommend you to find another way. For example, you can have a predefined list of values for precompile, and change the behavior based on the value.

We don't plan to allow functions in the short-term. If we want it in the future, it has to be designed carefully (in particular, how this interacts with 'blaze query' and other tools).

**Comment by pcj** [comment]
OK I'll close this for now.
