### ISSUE TITLE
Generate core dump and print the core dump path when the bazel test program crashes

### ISSUE THREAD

**Issue by zgaze** [bazelbuild/bazel#16989]
### Description of the bug:

I do not know when the program coredump and bazel test now cannot produce coredump

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Source code:
```cpp
// bazel_test.cc
#include <stdio.h>
#include <stdlib.h>
int main() {
  abort();
  return 0;
}
```
bazel build file:
```starlark
cc_test(
  name = "bazel_test",
  srcs = ["bazel_test.cc",]
)
```

Use bazel test

```shell
$bazel test :bazel_test
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //:bazel_test
-----------------------------------------------------------------------------
external/bazel_tools/tools/test/test-setup.sh: line 368:    13 Killed                  ( if ! ( ps -p $$ &>/dev/null || [ "`pgrep -a -g $$ 2> /dev/null`" != "" ] ); then
    exit 0;
fi; while ps -p $$ &>/dev/null || [ "`pgrep -a -g $$ 2> /dev/null`" != "" ]; do
    sleep 10;
done; kill_group SIGKILL $childPid )

$ $ find ./ -name core* | wc -l
0
```

Use build and execute 

```shell
$bazel build :bazel_test && bazel-bin/bazel_test
INFO: Analyzed target //:bazel_test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:bazel_test up-to-date:
  bazel-bin/bazel_test
INFO: Elapsed time: 0.225s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
Aborted (core dumped)
$ ls core.*
core.bazel_test.25509
```

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

4.2.1

### Have you found anything relevant by searching the web?

https://stackoverflow.com/questions/61885006/where-is-the-core-dump-file-when-bazel-test-failed

**Comment by haxorz** [comment]
This seems WAI because the core dump file is not a declared output of the test action.

Did you consider configuring things such that the core dump file would be written to `$TEST_UNDECLARED_OUTPUTS_DIR`? See https://bazel.build/reference/test-encyclopedia.

**Comment by zgaze** [comment]
thanks

**Comment by withtimesgo1115** [comment]
> thanks

@zgaze hi bro, how to expose the core dump error during the running of baze test jobs ?

**Comment by nikhilkalige** [comment]
Atleast when using processwrapper-sandbox, the coredumps are generated correctly. The key thing to note is that, any changes you make like setting ulimit with `ulimit -c unlimited` will only affect the current shell. So you will have to restart the bazel server, for those changes to influence the server too.
