### ISSUE TITLE
Add support to use files generated using Java plugin

### ISSUE THREAD

**Issue by pavi2410** [bazelbuild/bazel#16984]
### Description of the feature request:

There should be built-in support in `java_library` (and its descendants, such as `android_library`) to make the plugin-generated sources directory visible, for use in different targets.

### What underlying problem are you trying to solve with this feature?

I am trying to get generated Java files to compile a `gwt_application`. Those files are generated using a `java_plugin` that is applied on a `java_library`. As per my research, I found that the generated sources are put into a temporary directory `bazel-bin/<package>/_javac/<target>/lib<target>_sources/` which is synonymous to this property https://github.com/bazelbuild/bazel/blob/09da33b417e798cd0059a88dcfd4634af91e6322/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/JavaLibraryBuildRequest.java#L251-L253

Minimal example:
```
- MyProject/
  - MyGwtApp/
    - src/         -- depends on the generated Java file
    - BUILD
  - MyAndroidLib
    - src/
    - plugin_src/  -- generates a Java file
    - BUILD
  - WORKSPACE
```

file: MyGwtApp/BUILD
```
gwt_application(
  name = "GwtApp",
  srcs = ...,
  deps = [
    "//MyProject/MyAndroidLib:AndroidLib" # -- to depend on the generated Java file (?) [need help here]
  ]
)
```
file: MyAndroidLib/BUILD
```
java_plugin(
  name = "MyPlugin",
  srcs = ...,
  processor_class = ...
)

android_library(
  name = "AndroidLib",
  srcs = ...,
  plugins = [
    ":MyPlugin"
  ],
  visibility = [
    "//MyProject/MyGwtApp:__pkg__"
  ]
)
```

On a successful compilation of `//MyProject/MyAndroidLib:AndroidLib`, I see three places where I can find the generated files. But I don't know how to access them :(
- `bazel-bin/<package>/_javac/<target>/lib<target>_sources/`
- `bazel-bin/<package>/lib<target>-src.jar`
- `bazel-bin/<package>/lib<target>-gensrc.jar`

### Which operating system are you running Bazel on?

Windows

### What is the output of `bazel info release`?

release 5.3.2

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
https://github.com/pavi2410/appinventor-sources.git
ba246713b53fa1a0337ebc433dd708f8c7325ee2
db7cc3507c44f5a95b5d801782f6ad317c13652d
```

### Have you found anything relevant by searching the web?

https://groups.google.com/g/bazel-discuss/c/M3m-nGoU6qc -- I tried the hack, but it didn't work.

### Any other information, logs, or outputs that you want to share?

Slack thread: https://bazelbuild.slack.com/archives/CA31HN1T3/p1670519498644389

**Comment by cushon** [comment]
The generated sources can be accessed via starlark

* https://bazel.build/rules/lib/java_output#generated_source_jar
* https://bazel.build/rules/lib/JavaInfo#source_jars

**Comment by pavi2410** [comment]
I have tried using that but I can't use it without extracting the jar file which seems unnecessary. When I pass the jar file extracted via a custom rule, it doesn't accept it because it is not a java, srcjar, or properties file.

Is it possible to either mark the generated sources jar as `srcjar` file type or expose the raw files generated by the annotation processors?

**Comment by pavi2410** [comment]
Since there are multiple plugins generating different files for different purposes. I can't rely on a single jar. I must use files separately or have a different jar for each of the applied plugins.

**Comment by pavi2410** [comment]
I had to resort to copying the generated files with hardcoded paths.

**Comment by cushon** [comment]
I think the best option for now is to write a small starlark rule or just use a genrule to either extract the `.jar` file to a directory, or rename it to `.srcjar`.
