### ISSUE TITLE
[Mirror] Dependencies from rules_go 0.37.0

### ISSUE THREAD

**Issue by LINKIWI** [bazelbuild/bazel#16981]
### Please list the URLs of the archives you'd like to mirror:

[rules_go 0.37.0](https://github.com/bazelbuild/rules_go/releases/tag/v0.37.0), released a few days ago, depends on a few new mirror URLs that currently 404:

```
WARNING: Download from https://mirror.bazel.build/github.com/golang/sys/archive/refs/tags/v0.3.0.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://mirror.bazel.build/github.com/googleapis/googleapis/archive/83c3605afb5a39952bf0a0809875d41cf2a558ca.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
```

The associated callsites are here:

* https://github.com/bazelbuild/rules_go/blob/1a8fe64877c6e71dbbf51cdc8ceb2eb10c13e521/go/private/repositories.bzl#L91
* https://github.com/bazelbuild/rules_go/blob/1a8fe64877c6e71dbbf51cdc8ceb2eb10c13e521/go/private/repositories.bzl#L252

---

Please mirror the following URLs:

* https://github.com/golang/sys/archive/refs/tags/v0.3.0.zip
* https://github.com/googleapis/googleapis/archive/83c3605afb5a39952bf0a0809875d41cf2a558ca.zip

**Comment by sgowroji** [comment]
Please find the below mirror artifacts.

1. https://mirror.bazel.build/github.com/golang/sys/archive/refs/tags/v0.3.0.zip
2. https://mirror.bazel.build/github.com/googleapis/googleapis/archive/83c3605afb5a39952bf0a0809875d41cf2a558ca.zip
