### ISSUE TITLE
env: python: No such file or directory

### ISSUE THREAD

**Issue by lktinh2018** [bazelbuild/bazel#16980]
### Description of the bug:

Hello all, I'm using macbook pro m1 macos 12.
I compiling tensorflow lite for ios but got this error.
Please help me, I really appreciat every your support!
Thanks you so much!

env: python: No such file or directory

**Comment by sgowroji** [comment]
Hello @lktinh2018, Could you please provide minimal steps to reproduce the above issue. Thanks!

**Comment by sgowroji** [comment]
We are closing this issue as there is no response on the above comment.
