### ISSUE TITLE
CentOS 7.2  how to change default compiler (--compiler option)

### ISSUE THREAD

**Issue by jgrzybek** [bazelbuild/bazel#1699]
Hi all

I saw [#1201](https://github.com/bazelbuild/bazel/issues/1201) but it didn't help me a lot. I am using bazel3.0 and trying to build tensorflow. Default gcc is 4.8.5. I have installed locally gcc 6.1.0 which I want to use to compile TF. TF should be linked to default glibc. I tried to use --compiler switch but I get some errors about toolchain. These are my logs:

```
$ bazel build -c opt --compiler=gcc-6.1.0 --verbose_failures 
//tensorflow/tools/pip_package:build_pip_package
Warning: ignoring _JAVA_OPTIONS in environment.
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions 
cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more 
information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: No toolchain found for --cpu='k8' --compiler='gcc-6.1.0'. Valid toolchains are: [
  --cpu='armeabi-v7a' --compiler='compiler' --glibc='armeabi-v7a',
  --cpu='k8' --compiler='compiler' --glibc='local',
].
INFO: Elapsed time: 0.524s
```

Before running bazel I set:
CXX to /home/jgrzybek/memcpy_tests/gcc-6.1.0-binary/bin/g++
CC to /home/jgrzybek/memcpy_tests/gcc-6.1.0-binary/bin/gcc
and added  /home/jgrzybek/memcpy_tests/gcc-6.1.0-binary/bin/ to my PATH

Any suggestions?

**Comment by damienmg** [comment]
This should work out of the box without specifying `--compiler`. Can you try to do a `bazel clean --expunge` first?

**Comment by damienmg** [comment]
I am closing this bug now (12 days of inactivity). Please ping back if you still have the issue
