### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/user/0/com.google.mediapipe.examples.facemesh/incrementallib/libmediapipe_jni.so" is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by dharmeshdevstree** [bazelbuild/bazel#16990]
![imgpsh_fullsize_anim (1)](https://user-images.githubusercontent.com/86298602/207053517-7ecb6023-8170-4bb2-8c60-8b4ebeb9664e.png)

Hello,
Any one have an idea on this 
i have been using android-ndk-r21b-linux-x86_64 NDK in Ubuntu 20.02 64 bit.

**Comment by sgowroji** [comment]
We are closing this issue due to lack of information. Please reach us and provide complete details, if you are still looking support on this issue.
