### ISSUE TITLE
Improve install process

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#17]
We need a better installation process for Bazel.  Distributing binaries would be nice.  We should make packages for brew and ubuntu/debian, and a minimum, plus binary installers for Linux & OS X.

**Comment by kjiwa** [comment]
Which files should be installed and to where? Off the top of my head I would expect:

* ```/etc/bazelrc```
* ```/usr/bin/bazel```
* ```/usr/share/bazel/base_workspace```

Does Bazel support a system-wide bazelrc?

**Comment by damienmg** [comment]
I will close this issue as there is now installer. We have other issue to track specific issues with it.
