### ISSUE TITLE
bazel query --output xml insensitive to select()

### ISSUE THREAD

**Issue by kayasoze** [bazelbuild/bazel#170]
While writing a script to convert a Bazel source tree to a set of CMakeFiles (for use with CLion's project and parsing features), I noticed that the output includes the superset of all `select()` expressions, and not just those predicated on the current configuration.  If this is expected behavior, perhaps it should be documented.  It would be nice if one could force the emitted XML to respect `select()`, though.

**Comment by ulfjack** [comment]
We're planning to show select in the query output, but we haven't quite
decided how to do that yet.

**Comment by gregestren** [comment]
FYI code is already streaming into Bazel that basically makes this work, with caveats:

1. Not all query functions work (although `deps()`, importantly, does)
1. It's not quite the same interface as traditional query
1. Supporting `select()` means the queries take more time and memory (more analogous to a real build)

Also, I don't think XML output is yet supported, although it should be easy to add as a follow up.

We'll integrate pointers into the documentation. But in the meantime if anyone wants to know more please ping here.

**Comment by gregestren** [comment]
The newly developed `cquery` follows selects, although it doesn't support `--output=xml` yet. If you specifically need `--output=xml`, please re-open this bug.

See 07c4e3648e3b7a521b6706ffc5cbcdeca1ebf4e1, available in the next Bazel release.
