### ISSUE TITLE
Profiling disk I/O in Bazel's trace profile

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel#17002]
### Description of the feature request:

Bazel trace profile includes both CPU and memory usage: https://bazel.build/rules/performance#memory-profiling

It would be helpful to also include disk I/O to decide whether some slow actions are due to disk I/O.

### What underlying problem are you trying to solve with this feature?

We saw some Go linker actions sometimes take 10x-40x longer on CI than on local builds, but trace profile showed us that the CPU and memory utilization during that action was low. We suspect that it was due to high disk I/O during that build, but we have no way to find out.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 5.3.2

**Comment by larsrc-google** [comment]
Not sure that we can get good disk I/O information without being root.

**Comment by linzhp** [comment]
Bazel could run `iostat` or equivalent in Java or C, which doesn't require root, right?

**Comment by wilwell** [comment]
We could run `pidstat -d` and parse it.

**Comment by meisterT** [comment]
We have added the flag `--experimental_collect_pressure_stall_indicators` (see https://docs.kernel.org/accounting/psi.html#psi-pressure-stall-information) which should add info about I/O to the profile.

**Comment by stefanobaghino** [comment]
@meisterT Thanks for the update! Is this exclusive to Linux or can this be used on macOS and/or Windows as well?

**Comment by wilwell** [comment]
Unfortunately this functionality requires Linux OS, because it reads info from ` /proc/pressure/` directory.
