### ISSUE TITLE
MacOS debug not work with bazel 

### ISSUE THREAD

**Issue by Laughingtt** [bazelbuild/bazel#17015]
# Status of Bazel 5.1.1
### bazel's functionality and third-party package management are friendly and hopefully better for debugging and use

run the following code with macos

```
#include <ctime>
#include <string>
#include <iostream>

std::string get_greet(const std::string& who) {
  return "Hello " + who;
}

void print_localtime() {
  std::time_t result = std::time(nullptr);
  std::cout << std::asctime(std::localtime(&result));
}

int main(int argc, char** argv) {
  std::string who = "world";
  if (argc > 1) {
    who = argv[1];
  }
  std::cout << get_greet(who) << std::endl;
  print_localtime();
  return 0;
}
```
# g++ build cpp file then I can debug using vscode
g++ hello-world.cpp -g

![image](https://user-images.githubusercontent.com/56598312/207525733-d464ccd9-292a-4d0d-b138-862192a1f03a.png)

# bazel build cpp file ; can`t debug cpp file, Breakpoint not effective

bazel build -c dbg  //main:hello-world.cpp

![image](https://user-images.githubusercontent.com/56598312/207526718-c1e42ef3-f512-4f61-a6b1-e21c182b0071.png)

**Comment by Laughingtt** [comment]
> I Could able to debug the Cpp code in Vscode using bazel and with Clion using bazel plugin in MACOS Ventura.
> 
> <img alt="Screenshot 2022-12-14 at 1 27 17 PM" width="1792" src="https://user-images.githubusercontent.com/48122892/207538618-e1ba4985-a866-498b-aa87-6330165408f3.png">

1. What is the specific operation procedure on your side, let me see what is different?
2. Configuring gdb still doesn't debug it , It doesn't seem to be a problem with the plugin
![image](https://user-images.githubusercontent.com/56598312/207542913-cecdf352-7813-4840-b1a7-56b0a5235362.png)

**Comment by sgowroji** [comment]
Please try the latest version for Clion https://github.com/bazelbuild/intellij/issues/2101 it is fixed now.
