### ISSUE TITLE
Remove hard-coded -L/-l command line flags from CppLinkActionBuilder

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#1701]
CppLinkActionBuilder contains a few hard-coded linker options:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/cpp/CppLinkActionBuilder.java#L1469

This directly stands in the way of writing a CROSSTOOL file that works with Visual Studio.

The best approach is probably to create build variables with the parent directory, the soname (the part after -l) and the full path of the library and use a flag set to add the necessary `-L` /  `-l`options to the command line.

**Comment by lberki** [comment]
@calpeyser

**Comment by mhlopko** [comment]
Fixed in f63ea7a5e00eb86ba8caa3db8bcb586abea70ac4
