### ISSUE TITLE
Refactor C++ linking rules so that they use the `tool_path` in `action_config` to find the tool

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#1702]
We currently hard-code information about which tool needs to be used for which link target, for example, here:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/cpp/LinkCommandLine.java#L435

Instead, we should use the `action_config` for the link action to determine that so that it can be changed depending on how the toolchain actually works, like the way we do with Objective C archives (see in the case branch just below) or with C++ compile actions:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/cpp/CppCompileAction.java#L1329

**Comment by lberki** [comment]
@calpeyser

**Comment by mhlopko** [comment]
Long done. Closing.
