### ISSUE TITLE
[bazel.build] Problem with /community/users

### ISSUE THREAD

**Issue by kevmoo** [bazelbuild/bazel#17029]
Fix the stripe logo! 😄

**Comment by sgowroji** [comment]
Hello @kevmoo, Could you please elaborate your query with complete details like Url or page where you see the problem. Thanks !

**Comment by kevmoo** [comment]
![image](https://user-images.githubusercontent.com/17034/207766983-db7e873e-f065-4d3e-88ab-48a4b5abfc41.png)

https://bazel.build/community/users#stripe
