### ISSUE TITLE
I/O exception during sandboxed execution

### ISSUE THREAD

**Issue by liyuyun-lyy** [bazelbuild/bazel#17038]
### Description of the bug:

I'm using Bazel to build C++, with setting --sandbox_base=/mnt/ram/ and make directory /mnt/ram as ramfs. And I can get this I/O error sometimes, I still cannot find any routine to reproduce this bug, because the same source code may end with success or fail randomly. Is there any way to get more info about this error?
![ioexception](https://user-images.githubusercontent.com/105282436/208049388-20bfe5c9-6882-4446-ab9e-7a6a3ee16cec.png)

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

5.2.0

**Comment by sgowroji** [comment]
Hello @liyuyun-lyy, Could you please share minimum steps required to reproduce the above issue!!
