### ISSUE TITLE
Documentation: Titles on https://bazel.build/docs ambiguous

### ISSUE THREAD

**Issue by saraadams** [bazelbuild/bazel#17049]
### Description of the bug:

[`site/en/_book.yaml`](https://github.com/bazelbuild/bazel/blob/master/site/en/_book.yaml#L157-L194) lists titles that are included on https://bazel.build/docs
However, https://bazel.build/docs does not show the headings also included in that file. The titles are therefore in some cases not meaningful or ambiguous, or duplicated and not distinguishable from another.
This is particularly visible in the "Remote Distrubition" section, where three "Overview" entries are listed:

<img width="1489" alt="Screenshot 2022-12-16 at 16 25 27" src="https://user-images.githubusercontent.com/4410333/208425566-e656eb4e-710d-47f7-bea7-df3bbce109b1.png">
``

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Visit https://bazel.build/docs
2. Scroll to "Remote distribution" section
3. Find three items called "Overview"

### Which operating system are you running Bazel on?

n/a

### What is the output of `bazel info release`?

n/a

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
n/a
```

**Comment by keertk** [comment]
Hi @saraadams thanks for pointing this out!
They should be fixed/hopefully more clear now - https://bazel.build/docs.
