### ISSUE TITLE
Flag --incompatible_disable_starlark_host_transitions will break Bazel in 7.0

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#17043]
Incompatible flag `--incompatible_disable_starlark_host_transitions` will be enabled by default in Bazel 7.0. Please migrate and unblock the flip of this flag.

The flag is documented here: [bazelbuild/bazel#17032](https://github.com/bazelbuild/bazel/issues/17032).

Please check the following CI builds for build and test results:

- [CentOS OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-bc2e-4b38-9c75-6796aac984b0)
- [MacOS OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-bc3a-48c6-8207-5c0bdf88d419)
- [MacOS OpenJDK 8](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-bc3d-451e-b39e-a9981bc86633)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-bc32-4cd2-a2fd-84b8972cd0f3)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-bc43-478a-a293-e1729e1334ee)
- [Ubuntu 20.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-bc38-4117-9062-7b7ef4e4317f)
- [Windows OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-bc40-4929-bd12-04225b0f6f22)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-bc35-4d25-bebc-4fbb63c69528)
- [CentOS OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-e789-41e2-84d5-5c72e1059b49)
- [MacOS OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-e795-4151-8b71-36fb530e492a)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-e78c-44cb-9c51-b6fdfb604bc2)
- [Ubuntu 20.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-e792-4fc0-a5eb-d0d55ce0d7e8)
- [Windows OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-e798-4ab9-8218-9ed7736c88ac)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-e78f-40e7-b6cc-aad49488d72e)

<img width="858" alt="image" src="https://user-images.githubusercontent.com/110264242/208147403-3a1d1032-341f-4bc9-9260-44637438bb51.png">

**Comment by brandjon** [comment]
Looks like an issue for stardoc, but apparently the downstream CI build of Bazel itself somehow depends on stardoc?

Guess we'll have to address bazelbuild/stardoc#145, cut a stardoc release, and update whatever is pulling it into this build to the new version. Sasha will be back in January so may as well wait until then, since we have some time before 7.0.

**Comment by gregestren** [comment]
Note that https://bazel-review.googlesource.com/c/bazel/+/208644 enables this flag by default, which I believe we can re-ping when we've closed this and https://github.com/bazelbuild/bazel/issues/17032.
