### ISSUE TITLE
repository_ctx is unable to get another repository_rule's attributes

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#1704]
I'm currently trying to implement a couple of `repository_rule` rules in Skylark. 

My `maven_rules.bzl` file looks like this:

``` bzl
def maven_jar_impl(repo_ctx):
   ...

maven_jar_attrs = { 
  server: attr.label(), # refers to a maven_server target
  ... 
}

maven_jar = repository_rule(
  maven_jar_impl, 
  attrs=maven_jar_attrs, 
  ...
)

def maven_server_impl(repo_ctx):
  ...

maven_server_attr = { 
  url=attr.string(),
  ...
}

maven_server = repository_rule(
  maven_server_impl,
  attrs=maven_server_attr,
  ...
)
```

How do you retrieve the `url` attribute of the referenced `maven_server` target within `maven_jar_impl`, hopefully via `repo_ctx`? I've looked around and found `native.existing_rules()` and `native.existing_rule(name)`, but they do not work in the analysis phase.

**Comment by damienmg** [comment]
There is no way to do that currently.

**Comment by damienmg** [comment]
Oh sorry, it should be possible. native.existing_rule should just work but only at the macros level, so you can wrap maven_jar as a macro that calls the real maven_jar passing along the url to the actual maven_jar

**Comment by damienmg** [comment]
I would live it as a documentation issue.

**Comment by kchodorow** [comment]
> you can wrap maven_jar as a macro that calls the real maven_jar passing along the url to the actual maven_jar

What?

**Comment by jin** [comment]
I got this to work:

In `WORKSPACE`
```bzl

load(":maven_rules.bzl", "maven_jar_macro")

maven_server(
    name = "maven_uk_server",
    url = "http://uk.maven.org/maven2"
)

maven_jar_macro(
    name = "com_google_guava_guava",
    artifact = "com.google.guava:guava:18.0",
    sha1 = "cce0823396aa693798f8882e64213b1772032b09",
    repository = "http://repo.exist.com/maven2",
)
```
`maven_rules.bzl`
```BUILD
maven_jar_macro(
    name = "com_google_guava_guava",
    artifact = "com.google.guava:guava:18.0",
    sha1 = "cce0823396aa693798f8882e64213b1772032b09",
    repository = "http://repo.exist.com/maven2",
)
```

However, the `maven_server` rule now needs to come _before_ the `maven_jar_macro` rule for it to be included in `native.existing_rules`. This makes the BUILD file rules positional.

**Comment by jin** [comment]
@damienmg Why is `native.existing_rules` available in the macros level and not during WORKSPACE analysis? Wouldn't the rules and macros be parsed into `existing_rules` dictionary prior to WORKSPACE analysis?

**Comment by damienmg** [comment]
something along this should work:
```python
maven_server = repository_rule(...)
_maven_jar = repository_rule(... attrs = { "server_url": attr.string(),  ... } ...)

def maven_jar(server=None, **kwargs):
  if server:
    server_rule = native.existing_rule(server)
    server_url = server_rule["url"]
  else:
    server_url = "repo.maven.apache.org"
  _maven_jar(server = server_url, **kwargs)
```

**Comment by damienmg** [comment]
Ok cross-post. So seems like @jin understood what I meant :)

This is how skylark is made. It was not necessary to access them from other rule before. We could probably add it to repository_ctx. This need to be thought through though.

**Comment by jin** [comment]
It still feels a little fragile and not obvious that the `maven_server` declaration needs to come before `maven_jar`.

What are the implications of allowing `native.existing_rules()` to be called during the analysis phase?

**Comment by damienmg** [comment]
There is no real action we can take on this one, closing.
