### ISSUE TITLE
Header inclusion checking in src/hdrs for cc_library is broken

### ISSUE THREAD

**Issue by silvergasp** [bazelbuild/bazel#17055]
### Description of the bug:

Header inclusion checking seems to be broken. In the [documentation for cc_library](https://bazel.build/reference/be/c-cpp#hdrs), it mentions that adding header files to the `srcs` attribute should make them private to dependent targets. However, this is not the case.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a skeleton repository based on the [example in the Bazel documentation](https://bazel.build/reference/be/c-cpp#hdrs);
```python
cc_binary(
    name = "foo",
    srcs = [
        "foo.cc",
        "foo.h",
    ],
    deps = [":bar"],
)

cc_library(
    name = "bar",
    srcs = [
        "bar.cc",
        "bar-impl.h",
    ],
    hdrs = ["bar.h"],
    deps = [":baz"],
)

cc_library(
    name = "baz",
    srcs = [
        "baz.cc",
        "baz-impl.h",
    ],
    hdrs = ["baz.h"],
)
```

Try and include `bar-impl.h` from `foo.cc`. According to the documentation, this should produce an error, however, it does not and instead builds successfully.

<html>
<body>

Including file | Allowed inclusions
-- | --
foo.h | bar.h
foo.cc | foo.h bar.h
bar.h | bar-impl.h baz.h
bar-impl.h | bar.h baz.h
bar.cc | bar.h bar-impl.h baz.h
baz.h | baz-impl.h
baz-impl.h | baz.h
baz.cc | baz.h baz-impl.h

</body>
</html>

### Which operating system are you running Bazel on?

Ubuntu 20.04 (WSL)

### What is the output of `bazel info release`?

5.4.0

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/14346
https://github.com/bazelbuild/bazel/issues/7030
https://github.com/bazelbuild/bazel/issues/3828

**Comment by fmeum** [comment]
If you include `bar-impl.h` from `foo.cc`, use clang and enable the `layering_check` feature, you get this error:

```
bazel build //:foo --repo_env=CC=clang --features=layering_check
foo.cc:3:10: error: use of private header from outside its module: 'bar-impl.h' [-Wprivate-header]
#include "bar-impl.h"
         ^
1 error generated.
```

This works even better then the docs mention. While they say "For example, Bazel would not complain if in the example above foo.cc directly includes baz.h.", if you try that, you get this error:

```
bazel build //:foo --repo_env=CC=clang --features=layering_check
foo.cc:3:10: error: module //:foo does not depend on a module exporting 'baz.h'
#include "baz.h"
         ^
1 error generated.
```

**Comment by silvergasp** [comment]
Hmm, so in the example, you gave above, it's pretty clear that this feature is working (with the layering check feature enabled). Perhaps, it's just a documentation error and the docs should just mention the layering_check feature I'm unsure.

**Comment by fmeum** [comment]
I submitted #17057 to improve the documentation of this feature.
