### ISSUE TITLE
bazel compile on arm32 machine with error information: gRPC Java plugin not found in 

### ISSUE THREAD

**Issue by Momotyust** [bazelbuild/bazel#1705]
i try to install tensorflow on arm32 platform follow the tutorial:
https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/GUIDE.md

when i try to compile bazel (release 0.3.1) using command "./compile.sh", then error comes out:
"
norco@ubuntu:~/Tools/bazel$ ./compile.sh
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch
gRPC Java plugin not found in
"
HOW CAN I SOLVE THIS PROBLEM?

i try to google using keywords like "gRPC Java plugin not found in","bazel gRPC Java plugin not found in ", but answers gain.

BUT, i get some information from 
https://github.com/bazelbuild/bazel/blob/master/scripts/bootstrap/compile.sh
it's just the  compile.sh.

i find something in the shell script .
"
[1]
case "${PLATFORM}" in
linux)
  # JAVA_HOME must point to a Java installation.
  JAVA_HOME="${JAVA_HOME:-$(readlink -f $(which javac) | sed 's_/bin/javac__')}"
  if [ "${MACHINE_IS_64BIT}" = 'yes' ]; then
    PROTOC=${PROTOC:-third_party/protobuf/protoc-linux-x86_64.exe}
    GRPC_JAVA_PLUGIN=${GRPC_JAVA_PLUGIN:-third_party/grpc/protoc-gen-grpc-java-0.15.0-linux-x86_64.exe}
  else
    if [ "${MACHINE_IS_ARM}" = 'yes' ]; then
      PROTOC=${PROTOC:-third_party/protobuf/protoc-linux-arm32.exe}
    else
      PROTOC=${PROTOC:-third_party/protobuf/protoc-linux-x86_32.exe}
      GRPC_JAVA_PLUGIN=${GRPC_JAVA_PLUGIN:-third_party/grpc/protoc-gen-grpc-java-0.15.0-linux-x86_32.exe}
    fi
  fi
  ;;
.........
.........
.........
[2]
[[ -x "${GRPC_JAVA_PLUGIN-}" ]] \
    || fail "gRPC Java plugin not found in ${GRPC_JAVA_PLUGIN-}"
.........
.........
.........
[3]
if [ -z "${BAZEL_SKIP_JAVA_COMPILATION}" ]; then
  log "Compiling Java stubs for protocol buffers..."
  for f in $PROTO_FILES ; do
    run "${PROTOC}" -Isrc/main/protobuf/ --java_out=${OUTPUT_DIR}/src \
        --plugin=protoc-gen-grpc="${GRPC_JAVA_PLUGIN-}" \
        --grpc_out=${OUTPUT_DIR}/src "$f"
  done
"
in [1], "GRPC_JAVA_PLUGIN" is not set when platform is arm. but in [2], where check it and give error information.
i want to delete [2], but in [3], "GRPC_JAVA_PLUGIN" come again.....then i do not know how to do.

**Comment by lberki** [comment]
Ugh, that's bad. We don't provide protobuf binaries for protoc or grpc, thus, the TensorFlow people tell their users to compile protobuf, however, they don't have instructions for gRPC yet.

(Paging @damienmg)

We have two options here: either provide arm32 binaries or get rid of checked-in binaries in favor of checked-in generated protobuf sourrces. The former is probably easier in the short term, but the latter is much nicer, because distributing pre-compiled binary blobs is not very transparent.

**Comment by samjabrahams** [comment]
Hey guys- I stumbled upon this thread while building the next release of the (unofficial) RPi binaries. I'll be working toward building gRPC for Raspberry Pi and updating the guide. My repo is unofficial, so don't feel like you have to bend over backwards to support us unless you think it's beneficial to you all.

**Comment by lberki** [comment]
The vague plan is to distribute a source tree which has the generated sources, too, so that it can be built even if you don't have protoc on your platform. It'll take a while to materialize, though, because, well, we all have things to do.

**Comment by Momotyust** [comment]
Thanks for everyone! Finally i have installed  tensorflow on arm32 platform. I use a bazel version 0.2.1, and a earlier version tensorflow 0.1.0. Maybe it is time to close this issues.

**Comment by cerisara** [comment]
I'm having the same issue, trying to compile tensorflow on Android tablet with GNURoot + arm 32 bits.
Even checking out Bazel v0.2.1 does not solve it: compile.sh just ends silently, but no bazel executable is made. @Momotyust How did you manage to compile v0.2.1 ?
