### ISSUE TITLE
[Mirror] Boost 1.81.0

### ISSUE THREAD

**Issue by Vertexwahn** [bazelbuild/bazel#17067]
### Please list the URLs of the archives you'd like to mirror:

Please mirror
https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.gz

Expected mirror URL:
https://mirror.bazel.build/boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.gz

Needed here: 
https://github.com/nelhage/rules_boost/blob/c37cb35c641d9520e46923ebf2d38be7350fa8bd/boost/boost.bzl#L213

**Comment by sgowroji** [comment]
Please find the below mirror url

https://mirror.bazel.build/boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.gz
