### ISSUE TITLE
Bazel 6.0.0 upgrade not possible due to "command is longer than CreateProcessW's limit (32767 characters)"

### ISSUE THREAD

**Issue by diegohavenstein** [bazelbuild/bazel#17068]
### Description of the bug:

While attempting to upgrade from Bazel 5.4.0 to Bazel 6.0.0, we found that we hit an error during linking of our "main" library. This library takes a long parameter list, more than 41k characters long. Until now, that was fine, because we used `linker_param_file ` feature.

When building with `-s` and Bazel 5.4.0, the name of the file is shown
```
external\clang_windows\bin\llvm-lib.exe @bazel-out/x64_windows-dbg/bin/ourProject/ourMainLib.lib-2.params
```

With Bazel 6.0.0 and `-s`, our parameters are shown, and the error from the title
```
ERROR: D:/tc/work/953952133bf40cea/ourProject/BUILD.bazel:7:17: Linking ourProject/ourMainLib.lib failed: (Exit -1): llvm-lib.exe failed: error executing command
...
: command is longer than CreateProcessW's limit (32767 characters)
```

so it seems Bazel 6 is ignoring the `link_input_params` feature, given the linker call we see. This is reproducible also with the toy example in https://github.com/bazelbuild/bazel/issues/5163

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Use the repro from https://github.com/bazelbuild/bazel/issues/5163 on Windows. With `link_input_params` enabled, it should work with Bazel 5.4.0. Bazel 6 should fail with the error I posted above

### Which operating system are you running Bazel on?

Windows

### What is the output of `bazel info release`?

release 6.0.0

### Any other information, logs, or outputs that you want to share?

There's an ongoing Slack thread: https://bazelbuild.slack.com/archives/CA31HN1T3/p1671645326680889

**Comment by konste** [comment]
There is no built-in `link_input_params` feature. Do you mean `linker_param_file` feature?

**Comment by diegohavenstein** [comment]
yeah, sorry, that's a typo

**Comment by oquenchil** [comment]
Could you please provide a minimal repro that reproduces it? That will make it easier to track down.

**Comment by diegohavenstein** [comment]
@oquenchil This is reproducible with the toy example in https://github.com/bazelbuild/bazel/issues/5163

**Comment by oquenchil** [comment]
See here: https://github.com/bazelbuild/bazel/issues/5163#issuecomment-1370841422

You probably don't have the feature in your toolchain. I cannot reproduce it.

**Comment by diegohavenstein** [comment]
we have the feature enabled. What seems to be the problem is that the value of `supports_param_files` (arg to `cc_toolchain`) is ignored on Windows. We have a `select` there, but I hardcoded it to `True` to double check.

On Windows, when I set `supports_param_files = True` as described above, the `linker_param_file` feature is not available. I verified this by using the following flag groups:

**Comment by gregoryT5** [comment]
I found that enabling the new `archive_param_file` feature (build with `--features=archive_param_file`) addressed a similar issue for me.

That new option was intentionally disabled on macOS because of a performance hit (generates an archive per library), but I think it may have also been accidentally disabled on Windows as part of the relevant change (bff973031a65c139a4878c87e5f335a895964ab9). If that is the issue, it would probably be good to have that feature enabled by default for MSVC, since link command line length is a common problem on Windows.

**Comment by diegohavenstein** [comment]
Thanks @gregoryT5! After passing in `archive_param_file` in our toolchain, we're able to build now

Will not close the issue yet though, since I agree that this should be default behaviour on Windows

**Comment by oquenchil** [comment]
That indeed seems to be the culprit. @googlewalt archive_param_file should set `enabled = True` just like for the unix toolchain. I think this was unintentional. Could you please send a fix?

Thank you @gregoryT5 !

**Comment by googlewalt** [comment]
Sorry about the bug.  Should be fixed now.

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by kshyanashree** [comment]
@bazel-io fork 6.1.0

**Comment by Bobarshad** [comment]
can you please have look at the same issue [here](https://github.com/bazelbuild/bazel/issues/17919)
