### ISSUE TITLE
[bazel.build] Problem with /tutorials/ccp-toolchain-config - Mispelled Directory Name: toolchainS

### ISSUE THREAD

**Issue by jlpoolen** [bazelbuild/bazel#17076]
The directory the reader created, toolchain [_singular, not plural_], is incorrectly spelled by adding an "s" at the end of Instruction 6.

Existing:
>  To use the cc_toolchain_config rule, add a load statement to toolchains/BUILD:

should be:
>    To use the cc_toolchain_config rule, add a load statement to toolchain/BUILD:

**Comment by jlpoolen** [comment]
Location:  https://bazel.build/tutorials/ccp-toolchain-config

Next to the last paragraph in Step 6.

**Comment by keertk** [comment]
This has been fixed [here](https://bazel.build/tutorials/ccp-toolchain-config). Thanks for pointing it out!
