### ISSUE TITLE
[bazel.build] Problem with /tutorials/ccp-toolchain-config

### ISSUE THREAD

**Issue by jlpoolen** [bazelbuild/bazel#17075]
Step 6 towards the end has:

```
To use the cc_toolchain_config rule, add a load statement to toolchains/BUILD:

load(":cc_toolchain_config.bzl", "cc_toolchain_config")
```
Placement of the load statement in toolchains/BUILD is critical. At first, I placed the statement at the end of the file and got:

    eos /home/jlpoole/tutorial/examples/cpp-tutorial/stage1B # bazel build --config=clang_config //main:hello-world
    ERROR: Traceback (most recent call last):
            File "/home/jlpoole/tutorial/examples/cpp-tutorial/stage1B/toolchain/BUILD", line 26, column 1, in <toplevel>
                    cc_toolchain_config(name = "k8_toolchain_config")
    Error: global variable 'cc_toolchain_config' is referenced before assignment.
    ERROR: /home/jlpoole/tutorial/examples/cpp-tutorial/stage1B/main/BUILD:3:10: every rule of type cc_binary implicitly depends upon the target '//toolchain:clang_suite', but this target could not be found because of: Target '//toolchain:clang_suite' contains an error and its package is in error
    ERROR: Analysis of target '//main:hello-world' failed; build aborted: Analysis failed
    INFO: Elapsed time: 0.082s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
    eos /home/jlpoole/tutorial/examples/cpp-tutorial/stage1B # 

I then moved the load statement to become the 2nd active line in the file and the reran "bazel build..." and got the desired and expected error message:

    eos /home/jlpoole/tutorial/examples/cpp-tutorial/stage1B # bazel build --config=clang_config //main:hello-world
    INFO: Analyzed target //main:hello-world (1 packages loaded, 6 targets configured).
    INFO: Found 1 target...
    ERROR: /home/jlpoole/tutorial/examples/cpp-tutorial/stage1B/main/BUILD:3:10: Compiling main/hello-world.cc failed: (Exit 1): DUMMY_GCC_TOOL failed: error executing command toolchain/DUMMY_GCC_TOOL -MD -MF bazel-out/k8-fastbuild/bin/main/_objs/hello-world/hello-world.d '-frandom-seed=bazel-out/k8-fastbuild/bin/main/_objs/hello-world/hello-world.o' -iquote . -iquote ... (remaining 9 arguments skipped)

    Use --sandbox_debug to see verbose messages from the sandbox
    src/main/tools/linux-sandbox-pid1.cc:478: "execvp(toolchain/DUMMY_GCC_TOOL, 0x56320e275df0)": No such file or directory
    Target //main:hello-world failed to build
    Use --verbose_failures to see the command lines of failed build steps.
    INFO: Elapsed time: 0.337s, Critical Path: 0.03s
    INFO: 4 processes: 4 internal.
    FAILED: Build did NOT complete successfully
    eos /home/jlpoole/tutorial/examples/cpp-tutorial/stage1B #

The instruction should indicate _where_ in the file the added line goes.  Example:

>To use the cc_toolchain_config rule, add immediately below the first line package statement a load statement to toolchains/BUILD...`

Since the added line is position dependent, the instruction to add a line to a file should include the desired position.

**Comment by sgowroji** [comment]
Hello @jlpoolen, Could you please provide complete details on the above issue. URl of the Page or source your referring.

**Comment by jlpoolen** [comment]
My apologies, this was the 2nd documentation bug I logged, and I neglected to provide the URL which is:

https://bazel.build/tutorials/ccp-toolchain-config

See Step 6, next to the last paragraph of Step 6, and read what I have above.
