### ISSUE TITLE
[bazel.build] Problem with /install/docker-container

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#17070]
This page suggests using an old registry that's stuck in the past
```
docker run --rm -it l.gcr.io/google/bazel:latest version
Build label: 3.5.0
```

but Yun documented here
https://github.com/bazelbuild/continuous-integration/issues/1060#issuecomment-1360942408
that the correct place for new versions is now gcr.io/bazel-public/bazel

**Comment by alexeagle** [comment]
Note near the bottom of the page, the example is quite dated as well
`Build label: 0.17.1`

**Comment by sgowroji** [comment]
Hello @alexeagle, Can you provide the page link which you referring on above comments.  Thanks!

**Comment by alexeagle** [comment]
Ah, I didn't include that since it was automatically captured in the bug title by the Report Issue button link.

**Comment by alexeagle** [comment]
https://bazel.build/install/docker-container is the page that has that button. If the process isn't clear, maybe @fweikert could change the buttons to include the domain name in addition to the path?

**Comment by keertk** [comment]
Created a [separate issue](https://github.com/bazelbuild/bazel/issues/17176) to update the buttons/include more details in the title & description - thanks @alexeagle! 
(We're looking into the original issue in the meantime as well.)
