### ISSUE TITLE
Cc_library toolchain resolution not working in 6.0

### ISSUE THREAD

**Issue by tobbe76** [bazelbuild/bazel#17074]
### Description of the bug:

exec_compatible_with no longer works with cc_library.

Cc_library is missing attribute cc_toolchain_type.
If cc_toolchain_type is added the same way as for cc_binary it works as expected.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Use exec_compatible_with to select different exec platform

### Which operating system are you running Bazel on?

Windows

### What is the output of `bazel info release`?

6.0 official release

**Comment by sgowroji** [comment]
Hello @tobbe76, Could you please elaborate your query with more details with a sample code. Thanks!
