### ISSUE TITLE
Output files from --output_groups do not appear when cache is ON and output_groups is provided by the aspect

### ISSUE THREAD

**Issue by oev88** [bazelbuild/bazel#17090]
### Description of the bug:

There is a bazel project with turning ON remote caching.
Some targets are build using aspect, which provides `OutputGroupInfo` for `--output_groups` command option.

All requested generated files preset when we build target without remote caching.
And we have output files miss for files from `--output_groups` when we build with cache hits and remote caching.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/oev88/bazel_issues

### Which operating system are you running Bazel on?

Linux, Windows

### What is the output of `bazel info release`?

release 5.2.0-17

### Have you found anything relevant by searching the web?

no

**Comment by tjgq** [comment]
This is no longer reproducible on Bazel 6.0.0. @oev88 are you able to upgrade?

**Comment by oev88** [comment]
Thanks for fast feedback. I can check in a week

**Comment by oev88** [comment]
There is no issue on bazel-6.0
Thank you!

**Comment by sgowroji** [comment]
Thank you for the update. We are closing this issue now. Feel free to reach us for any further queries on the same.
