### ISSUE TITLE
How can I make some build args as required and fail the bazel build when the arg is not provided?

### ISSUE THREAD

**Issue by satishhiremath** [bazelbuild/bazel#17096]
How can I make some build args as required and fail the bazel build when the arg is not provided? I have a bazel build <target> --config=X, I need a way to fail the bazel build if X is not provided.

**Comment by fmeum** [comment]
[Bazelisk](https://github.com/bazelbuild/bazelisk), the recommended Bazel wrapper, will in turn run a script at `tools/bazel` in your workspace if it exists. You can place all kinds of logic there to verify that developers invoke `bazel` itself in the correct way.

**Comment by satishhiremath** [comment]
@fmeum  Thanks for your answer.

Issue with bazelisk is, we have to change the way we call the build in our repo i.e. bazelisk build <target> instead of bazel build <target>. I was searching for any inbuilt argument parser for bazel which I might be unaware of.

**Comment by fmeum** [comment]
While I'm not aware of that capability, I usually recommend installing Bazelisk in `PATH` as `bazel`. That additionally ensures that developers always use the pinned version of Bazel.

**Comment by pcjanzen** [comment]
bazelisk is not required, `tools/bazel` will also be invoked by the `bazel` that installers put on your $PATH

**Comment by satishhiremath** [comment]
Ah nice. 

So if I understand correctly, I need to place the script inside `tools/bazel` folder inside my workspace and it will be automatically invoked. Correct me If I am wrong.

Could someone point me to the example scripts to be placed in `tools/bazel` and which will be invoked when I call `bazel build <target>`.

**Comment by meteorcloudy** [comment]
Since this is not a Bazel bug or feature request, I'll close this one
