### ISSUE TITLE
repository_ctx.sha256 for safer repository rules

### ISSUE THREAD

**Issue by pcj** [bazelbuild/bazel#1711]
Repository context should expose a sha256 function that returns a sha256 string for a given path file artifact.  Makes it easier to write safer repository rules.  Please indicate if a PR for such a function would be welcome.

**Comment by damienmg** [comment]
That makes sense to me but we need to do an API review first. However the full skylark repository hasn't gone through such an API review yet. I am cleaning it as a first step and then we can discuss this further.

**Comment by kchodorow** [comment]
This is probably more easily solvable via #1410.  See also #991 (closed in favor of #1410).

**Comment by pcj** [comment]
Could also be addressed via allowing FileURLConnection's (file urls) in `ctx.download`, at which it becomes a generic `cp` with sha256 checking capability.

**Comment by jin** [comment]
I believe this is now handled by @aehlig's work on repository rule return values and `bazel sync`.
