### ISSUE TITLE
Invalid bzlmod overrides are ignored

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#17125]
If you have some `archive_override` in your MODULE.bazel file that attempts to override a repository that doesn't exist, bazel silently ignores it. I think ideally bazel would error in this case, since it likely points to you trying to override something that you're not pulling in at all.

**Comment by sgowroji** [comment]
Hello @keith, Could you please provide minimal steps to reproduce the above issue. Thanks!

**Comment by keith** [comment]
I think the description should be enough!

**Comment by keith** [comment]
Yea the repro case is if you have a MODULE.bazel with:

```
archive_override(
    integrity = "sha256-+T69g/MobVF0j4bpoOToa6eQqinQULa6w6dqhymuEjc=",
    module_name = "foo",
    strip_prefix = "apple_support-441103ea05ffbde2da9f77252e27e4f519e01c72",
    urls = [
        "https://github.com/bazelbuild/apple_support/archive/441103ea05ffbde2da9f77252e27e4f519e01c72.tar.gz",
    ],
)
```

and you have a BUILD file with:

```bzl
cc_library(name = "main", srcs = ["main.c"])
```

and `main.c` is:

```
int main() { return 0; }
```

building with `bazel build main --enable_bzlmod` will work, where I think it should potentially fail because we're trying to override `foo` which doesn't exist. I'm not sure if all the info available to do this exists, but since it's less lazy than the WORKSPACE I assume it might be possible

**Comment by Wyverald** [comment]
This should be easy to check. A line around https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModuleResolutionFunction.java;l=85;drc=9860051afe7ccf0902f1ce3dbbc9066088d7c849  should suffice. PRs welcome :)

**Comment by brentleyjones** [comment]
@keertk not stale, triaged and not waiting for input

**Comment by yokeshwaran1** [comment]
Hi @keith @Wyverald and Bazel team,
I read the details of this issue and suggested fix. I like to work on this and provide a PR to fix the problem with 'archive_override' in 'MODULE.bazel'. I will start by checking the code at the provided link in BazelModuleResolutionFunction.java and come up with approach to introduce the necessary checks. Pls let me know if there r any additional considerations or if anyone else is already working on this.

**Comment by keith** [comment]
Sounds good!

**Comment by TomerPacific** [comment]
@keith / @Wyverald - Is this issue still up for grabs?
