### ISSUE TITLE
bzlmod changes repository_rule names used in module extensions

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#17129]
### Description of the bug:

If you have a normal repository rule:

```
artifactory_archive = repository_rule(
    implementation = _impl,
...
```

And you call it from a module extension:

```
    artifactory_archive(
        name = "foo",
        ...
    )
```

In the implementation of the repository_rule, `ctx.attr.name` is `foo` if you're using a WORKSPACE, and it is `@_main~extension_name~foo` in the case you're using bzlmod.

I imagine this could cause some confusion as folks attempt to migrate if they previously used the name for other purposes, like in our case creating a URL for downloading an archive

### What is the output of `bazel info release`?

6.0.0rc4

**Comment by Wyverald** [comment]
It can also be surprising if `ctx.attr.name` ends up *not* being the canonical name of the repo, so what we've been recommending is to pass the name explicitly as an additional attribute.
