### ISSUE TITLE
Platform-specific C++ defines

### ISSUE THREAD

**Issue by mnbittorrent** [bazelbuild/bazel#1712]
How should one include a platform-specific flag in bazel?

Say we have a cross-platform library that we want to change defines on.

Can we do something like:
```
defines = ["FEATURE_A"]
if somehow_detect_the_platform == 'ios':
    defines.extend("FEATURE_B")

cc_library(
    name = "foo",
    srcs = ["foo.cc"],
    defines = defines,
    hdrs = ["foo.h"],
)
```

Since bazel doesn't support conditionals, is there an elegant solution here?

Also note that this concept can apply to other things like includes, cflags, sources, headers, etc.

**Comment by kayasoze** [comment]
Does something like this work for you?

```
copts = select({
  "//config:foo": ["-DFOO"],
  "//conditions:default": [],
}),
```

**Comment by mnbittorrent** [comment]
Thanks, that's probably what I'm looking for...I'm still new to bazel, so I'm trying to piece these things together.

Is there a more complete example of using config + conditions that you could suggest?
