### ISSUE TITLE
bzlmod's archive_override drops MODULE.bzl file

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#17131]
If you depend on something like:

```
bazel_dep(name = "protobuf", repo_name = "com_google_protobuf", version = "21.7")
```

And then override it like:

```
archive_override(
    integrity = "sha256-db5CvXNvTfbXAqDk5NMN6e5A6sAkxLhF0XrkzIMf5K4=",
    module_name = "protobuf",
    patches = ["//bazel/third_party:protobuf.patch"],
    strip_prefix = "protobuf-21.7",
    urls = [
        "https://github.com/protocolbuffers/protobuf/archive/v21.7.tar.gz",
    ],
)
```

The MODULE.bazel file that is provided by the central registry is dropped and you get an error like this:

```
ERROR: Error computing the main repository mapping: MODULE.bazel expected but not found at /private/var/tmp/_bazel_ksmiley/6bbe7127907f07fd26fff2d7f0a48a86/external/protobuf~override/MODULE.bazel
```

I think this behavior matches that from before if you override something, but when you'd otherwise have to copy the MODULE.bazel file from the central registry it feels a bit worse than before.

**Comment by keith** [comment]
This is actually worse than I thought because it also drops all the patches https://github.com/bazelbuild/bazel-central-registry/tree/f28f72969ad0f16830bbf9984025fb554860314c/modules/protobuf/21.7/patches and so far patches seem very encouraged in the central registry

**Comment by keith** [comment]
also there's no way to provide the MODULE.bazel file except as a patch, unlike http_archive and friends with `build_file`

**Comment by Wyverald** [comment]
`archive_override` intentionally causes the module to not be requested from the registry at all; everything about the overridden module is specified through the override itself.

What is the intended use case here? If you want to use the module from the registry as normal but just apply an additional patch, you can simply use `single_version_override` without specifying a version on the override.

**Comment by keith** [comment]
ah yes `single_version_override` is what i really wanted!
