### ISSUE TITLE
Cleanup progress when using bzlmod

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#17130]
Currently when using bzlmod your action's progress can look something like `@_main~bzlmod_tool_dependencies~Yams//:Yams`, in the past this would have been displayed as `@Yams//:Yams` and generally IMO this adds a lot of visual noise if you have many dependencies like this.

**Comment by fmeum** [comment]
I have a PR that should fix this: https://github.com/bazelbuild/bazel/pull/17045
