### ISSUE TITLE
genrule failed with `realpath` on outs directory

### ISSUE THREAD

**Issue by taozhou-glean** [bazelbuild/bazel#17151]
### Description of the bug:

our gennrule starts failing with Mac M1 while still works fine on i386 Mac and linux.

I was able to make a minimum code to repro this issue reliably as shown below, looks like the `folder` in `outs` was not yet generated here

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

BUILD.bazel
```
package(default_visibility = ["//visibility:public"])

genrule(
    name = "test",
    srcs = [
        "test.sh",
    ],
    outs = [
        "dist",
    ],
    cmd = "$(location test.sh) $(location dist)",
    stamp = 1,
)
```

test.sh
```
#!/bin/bash
set -e

DIST=$1
echo $1
DIST_REALPATH=$(realpath "$DIST")
echo $DIST_REALPATH
OUTPUT=$(dirname "$(realpath "$DIST")")
echo $OUTPUT
```

just run `bazel :test`

### Which operating system are you running Bazel on?

Mac Pro M1: `uname`: `22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64`

### What is the output of `bazel info release`?

release 6.0.0

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
n/a
```

### Any other information, logs, or outputs that you want to share?

full error log from `bazel build :test --sandbox_debug`
```
INFO: Analyzed target //:test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/taozhou/workspace/tmp/BUILD.bazel:4:8: Executing genrule //:test failed: (Exit 1): sandbox-exec failed: error executing command
  (cd /private/var/tmp/_bazel_taozhou/ec9ed3492ee3e49243fb20d883ae78df/sandbox/darwin-sandbox/3/execroot/test && \
  exec env - \
    PATH=/Users/taozhou/Library/Caches/bazelisk/downloads/bazelbuild/bazel-6.0.0-darwin-arm64/bin \
    TMPDIR=/var/folders/sq/hzfg58t16wb_xqyx2m6svx8c0000gn/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_taozhou/ec9ed3492ee3e49243fb20d883ae78df/sandbox/darwin-sandbox/3/sandbox.sb /var/tmp/_bazel_taozhou/install/730b09b9d9f2bfd30b4c0a074ba23835/process-wrapper '--timeout=0' '--kill_delay=15' '--stats=/private/var/tmp/_bazel_taozhou/ec9ed3492ee3e49243fb20d883ae78df/sandbox/darwin-sandbox/3/stats.out' /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; ./test.sh bazel-out/darwin_arm64-fastbuild/bin/dist')
realpath: bazel-out/darwin_arm64-fastbuild/bin/dist: No such file or directory
bazel-out/darwin_arm64-fastbuild/bin/dist
Target //:test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.094s, Critical Path: 0.02s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

**Comment by taozhou-glean** [comment]
FYI: This happens on bazel 5.4.0 as well

**Comment by benjaminp** [comment]
Why do you think this is due to Bazel rather than `realpath(1)` having different semantics on different platforms?

**Comment by taozhou-glean** [comment]
ah that's a really good point! so I just tested, and apparently `realpath` did behave differently, on my Mac M1 machine, it will throw error if the target folder does not exist, while it works just fine on my linux.
```
$ ls
BUILD.bazel    WORKSPACE      bazel-bin      bazel-out      bazel-testlogs bazel-tmp      test.sh
$ realpath abc
realpath: abc: No such file or directory
```

while on linux:
```
$ ls
BUILD.bazel    WORKSPACE      bazel-bin      bazel-out      bazel-testlogs bazel-tmp      test.sh
$ realpath abc
/path_to_pwd/abc
$ realpath abc/a
realpath: abc/a: No such file or directory
```

seems it only starts reporting `No such file or directory` on nested folders.

Thank you!

**Comment by taozhou-glean** [comment]
just want to circle back here and provide an update in case anyone hits the same issue, I asked the coreutils and apparently the `realpath` I was using is actually from Mac (i assume), which implements `realpath(3)` instead of `realpath(`)`, which explains the difference.
https://lists.gnu.org/archive/html/bug-coreutils/2023-01/msg00017.html
