### ISSUE TITLE
Bazel 6.0.0 execroot path bug

### ISSUE THREAD

**Issue by bedbad** [bazelbuild/bazel#17152]
### Description of the bug:

Automatic upgrade of bazelisk to bazel 6.0 has broken cc_rules_foreign (cmake) build with the following error:

```
CMake Error at src/corelib/Qt6CoreMacros.cmake:2286 (add_library):
  Cannot find source file:
    /private/var/tmp/_bazel_im/10b8d2a29b3dccb35935c1caea4c1429/execroot/Qt/execroot/Qt/bazel-out/darwin_arm64-opt/bin/qtbase_gui.build_tmpdir/src/plugins/platforms/cocoa/.rcc/qcocoaresources.qrc
```

Which happens because wrong execroot path is searched:
`/execroot/Qt/execroot/Qt/` is descended twice

downgrading to bazel 5.1.0 fixes this issue 
`echo "5.1.0" >> .bazelversion`

### Which operating system are you running Bazel on?

MascOS Ventura, Darwin arm64

### What is the output of `bazel info release`?

release 6.0.0

**Comment by sgowroji** [comment]
Hello @bedbad, Could you please provide minimal steps to reproduce the above error. Thanks!
