### ISSUE TITLE
ActionMetadataHandler.constructTreeArtifactValueFromFilesystem() causes files to be considered modified

### ISSUE THREAD

**Issue by tbaing** [bazelbuild/bazel#17162]
### Description of the bug:

We are using `--experimental_guard_against_concurrent_changes` and producing a TreeArtifact from a directory where files have 0755 permissions. When Bazel builds this target, it executes our code (producing files with 0755 permissions), but then https://source.corp.google.com/piper///depot/google3/third_party/bazel/src/main/java/com/google/devtools/build/lib/skyframe/ActionMetadataHandler.java;l=347 iterates through the TreeArtifact and chmods each file to 0555 permissions. The permission change doesn't cause us problems, but this updates the ctime for those files, so when [RemoteSpawnCache.checkForConcurrentModifications()](https://source.corp.google.com/piper///depot/google3/third_party/bazel/src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnCache.java;l=203) confirms that no concurrent modifications were made, it flags those ctime changes and refuses to upload the artifacts to the remote cache.

My observations of this behavior came from using the --host_jvm_debug flag when invoking Bazel, and setting breakpoints within the code from the 6.0.0 tag.

### Which operating system are you running Bazel on?

gLinux

### What is the output of `bazel info release`?

release 6.0.0-pre.20221012.2

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
https://github.com/bazelbuild/bazel.git
f2cdf9e65eadfb5365127eabcc72dedce7781405
06deebfb5b73f848de5a0ea0e00fcfaa26788d1f
```

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/5566 describes other instances of fragility with this flag, including an example from djmarcin for symlinks in tree artifact output, but nothing about file permissions for tree artifacts.

**Comment by coeuvre** [comment]
I can't reproduce this locally. By looking at the code, the chmods you mentioned look fine to me since they happened before the downstream actions started. So the metadata of input for the check inside `checkForConcurrentModifications` is the one after chmods.

Can you please share a minimal repro?

**Comment by tbaing** [comment]
Will do, hopefully tomorrow. Our use case is non-minimal (we're exploding an archive with 290k files), so my attempts to step through with the debugger were hampered by multiplying the debugger's overhead by 290k on some of the loops, so I'll set up a small reproducer soon and share it.

**Comment by sgowroji** [comment]
Hi @tbaing, Can you share the minimal repro as mentioned above. Thanks!

**Comment by tbaing** [comment]
In the time since I first submitted this, we've refactored our Bazel action graph to remove the action that was causing this, so I've not managed to reproduce the behavior either. I'll spend a little more time today trying to force it to happen, but if not we may have to just abandon this bug report.

**Comment by amybzhao** [comment]
Hi! I think we might have a repro using an example from [rules_js](https://github.com/aspect-build/rules_js), which I believe [stores npm packages as TreeArtifacts](https://github.com/aspect-build/rules_js/blob/5012a5be03e125c0ea6f05e7b1d20397cfd89d1a/npm/private/npm_package_info.bzl#L8)!

When running `bazel clean --expunge && bazel --bazelrc=/tmp/minimal.bazelrc test --remote_cache=grpc://localhost:21000 //examples/npm_deps:test_peer` repeatedly from the main rules_js workspace, I'm consistently seeing warnings like:
```
WARNING: /home/vagrant/.cache/bazel/_bazel_vagrant/796f13da7bd5ffef695ab9bc1e716bf9/execroot/aspect_rules_js/bazel-out/k8-fastbuild/bin/node_modules/.aspect_rules_js/@rollup+plugin-commonjs@21.1.0_rollup@2.70.2/node_modules/@rollup/plugin-commonjs/CHANGELOG.md was modified during execution
```
(The specific file may change but the warning always shows up after the test has executed)

The output of bazel info release is: release 6.0.0

`/tmp/minimal.bazelrc` contents:
```
build --experimental_guard_against_concurrent_changes
```

And we're using `bazel-remote` for our remote cache

This is currently blocking my team from upgrading to bazel 5.4.0 -> 6.0.0

**Comment by coeuvre** [comment]
Sorry, I am currently under high load. Maybe 2 weeks later, I can look into this. Please remind me again if I didn't at that time. Thanks!

**Comment by amybzhao** [comment]
hey @coeuvre! just wanted to check in again!

**Comment by coeuvre** [comment]
I can reproduce the warning with example from rules_js, but it's caused by unresolved symlink (which is always [considered modified](https://cs.opensource.google/bazel/bazel/+/refs/heads/master:src/main/java/com/google/devtools/build/lib/actions/FileArtifactValue.java;l=739;drc=6446607f6eb2ce2b1ff5e5d8d429456dcdfec01f)) which is different from the original issue.

I can fix the unresolved symlink case but I still cannot reproduce the warning with tree artifact.

**Comment by tjgq** [comment]
Per https://github.com/bazelbuild/bazel/issues/17162#issuecomment-1577050958, it sounds like this was caused by a different issue. Please reopen otherwise.
