### ISSUE TITLE
Redundant memory consumption when nesting java_common.merge

### ISSUE THREAD

**Issue by Andrius-B** [bazelbuild/bazel#17170]
### Description of the bug:

We have been using `java_common.merge` to exporting transitive dependencies. An example of this would be a dependency chain like this:
`java_library` (multiple) -> `module` (custom rule) [-> `module`] -> `java_test`
There was a proposal made for an API fulfilling this use-case here: #8867
@iirina seems to have concluded that this approach is sufficient to merge `JavaInfo` providers:
```py
def _impl(ctx):
  return [java_common.merge([dep[JavaInfo] for dep in ctx.attr.deps])]
```
However in some cases this uses way more memory then required (we started seeing OOM crashes when analysing big targets). The issue lies in `JavaSourceJarsProvider`, which contains two collections for source jar artifacts:
```java
ImmutableList<Artifact> sourceJars
NestedSet<Artifact> transitiveSourceJars
```
usually when creating a library like this:
```py
java_library(
    name="test",
    srcs = ["Test.java"],
    deps = [java_deps],
)
```
the `sourceJars` list will only contain a single jar (with the sources from the current library, others in the `transitiveSourceJars` Set) however when using `java_common.merge` there is no way of transitioning the jars from `sourceJars` to `transitiveSourceJars`. This causes lots of duplicates and memory inefficiency with the `sourceJars` collection.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Here is a small reproduction case, in a single `macros.bzl` file:
```py
load("@rules_java//java:defs.bzl", "java_library")

def _java_merge_impl(ctx):
    java_infos = [src[JavaInfo] for src in ctx.attr.srcs if JavaInfo in src]
    return java_common.merge(java_infos)

java_merge = rule(
    implementation = _java_merge_impl,
    attrs = {
        "srcs": attr.label_list(
            allow_files = False,
        ),
    },
)

def define_libraries():
    libs = []
    for x in range(1000):
        name = "lib%s" % x
        java_library(
            name = name,
            srcs = ["Library.java"],
        )
        libs.append(name)

    merged_libs = []
    for x in range(100):
        merged_name = "merged%s" % x
        java_merge(
            name = merged_name,
            srcs = merged_libs + libs,
        )
        merged_libs.append(merged_name)
    java_merge(
        name = "merged",
        srcs = merged_libs,
    )
```
_assume`Library.java` exists & compiles without dependencies_
when `define_libraries()` macro is called it will define:
* 1000 identical `java_library` targets, each one having an identical artifact in `sourceJars` and the same artifact in `transitiveSourceJars` (observed by attaching debugger)
* 100 `java_merge` targets each one merging all the `java_library` targets and additionally all the previous `java_merge` targets
The first `java_merge` target `//:merged0` has `sourceJars.size=1000` and `transitiveSourceJars.transitiveSets.size = 1000`
`//:merged1` has `sourceJars.size=2000` and `transitiveSourceJars.transitiveSets.size = 1001`
`//:merged2` has `sourceJars.size=4000` and `transitiveSourceJars.transitiveSets.size = 1002`
`//:merged3` has `sourceJars.size=8000` and `transitiveSourceJars.transitiveSets.size = 1003`
[...]
highest I can get up to without crashing is `//:merged17` which has a *long* list of `sourceJars`. Here is a debugger screenshot with a breakpoint on `JavaSourceJarsProvider.merge` return line where `result` is a `JavaSourceJarsProvider.Builder`:
![Screenshot 2023-01-09 at 11 43 40](https://user-images.githubusercontent.com/10669773/211302946-fbf2a9cc-85ca-45c2-81c8-af1bad3ab7f4.png)
Ideally in this case `sourceJars` should be empty as all the information should be in `transitiveSourceJars`, though the API provides no way of achieving this.

### Which operating system are you running Bazel on?

Mac OS

### What is the output of `bazel info release`?

release 5.3.2

### Have you found anything relevant by searching the web?

In bazel 6.0.0 this change by @comius  landed: https://github.com/bazelbuild/bazel/commit/4c26c3a1768f69ccff8517862bd5b09a958b3564
Which might alleviate this issue, but it is private API, so not so straightforward to test:
```
return java_common.merge(java_infos, merge_source_jars = False)
Error in merge: Rule in '' cannot use private API
```
Anyways dropping the source jars does not make the build more _correct_ so this would not be ideal either.

**Comment by fmeum** [comment]
@keertk Not stale
