### ISSUE TITLE
Unclear what `--noforce_pic` does to inclusion of `-fPIC` flag for GCC on Linux?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [bazelbuild/bazel#17175]
### Description of the bug:

**Disclaimer**: This is purely out of curiosity / sharing. If y'all think it's "Not A Problem", please close this with prejudice!

I'm trying to figure out when exactly Bazel adds `-fPIC`. Does anyone happen to know?
I tried to see what flags would remove it (not using `cc_library(..., nocopts)`), but both `--noforce_pic` + `cc_library(..., linkstatic=True)` didn't seem to change anything.
Context: https://github.com/RobotLocomotion/drake-ros/issues/151#issuecomment-1376533912
Example: https://github.com/EricCousineau-TRI/repro/tree/1f03ded043481760617a537d0848c42ea256b14e/bazel/bazel_pic

Seems to come in through this:
https://github.com/bazelbuild/bazel/blob/5.3.1/tools/cpp/unix_cc_toolchain_config.bzl#L370-L389

And from quick perusal, I don't see immediate connection between this and `--force_pic`, which seems to do more about `-pie`:
https://github.com/bazelbuild/bazel/blob/5.3.1/tools/cpp/unix_cc_toolchain_config.bzl#L1023-L1039

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See https://github.com/EricCousineau-TRI/repro/tree/1f03ded043481760617a537d0848c42ea256b14e/bazel/bazel_pic

### Which operating system are you running Bazel on?

Ubuntu 22.04

### What is the output of `bazel info release`?

```
$ bazel info release
INFO: Invocation ID: 7635b5e3-8bc1-434c-8a00-990b50d59927
release 5.3.1
```

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

See above link.

### Have you found anything relevant by searching the web?

Searched issues, didn't see anything immediately relevant.

### Any other information, logs, or outputs that you want to share?

Nothing more than what's stated above.

**Comment by pcjanzen** [comment]
I believe that `-fPIC` is always used when creating shared libraries. When `--force_pic` is active, static archives will use the same (position-independent) objects, and position-independent executables will be built. When `--noforce_pic` (the default) is active, static archives will be built from distinct, non-pic objects.
