### ISSUE TITLE
build_tar attempts to use python2 when upgrading to Bazel 6.0.0

### ISSUE THREAD

**Issue by nicknezis** [bazelbuild/bazel#17179]
### Description of the bug:

After upgrading to Bazel 6.0.0. I am getting the following failure when building the Apache Heron project. 

`failed: (Exit 127): build_tar failed: error executing command (from target //scripts/packages:heron-core-lib-downloader) bazel-out/darwin-py2-opt-exec-2B5CBBC6/bin/external/rules_pkg/build_tar`

When testing with Bazel 5.1.0 the issue does not occur. Is there something relating to this toolchain definition that is failing? https://github.com/bazelbuild/bazel/blob/6.0.0/tools/python/toolchain.bzl

My build machine is a `darwin` (MacOS), and I have `brew` installed Python 3.9 and 3.10. I do not have any form of Python 2 installed.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

git clone git@github.com:apache/incubator-heron.git
echo 6.0.0 > .bazelversion
bazel build scripts/packages:heron-bin

### Which operating system are you running Bazel on?

macOS Ventura 13.1

### What is the output of `bazel info release`?

release 6.0.0

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
https://github.com/apache/incubator-heron
8aa05b8449ad5a3c2cd27f12c82f75d192c99da9
e49a043e5f046132a88e9242c30df96f718976bb
```

**Comment by nicknezis** [comment]
Sample build log output: https://app.travis-ci.com/github/apache/incubator-heron/builds/259485593#L435

**Comment by sgowroji** [comment]
Seems that project as support upto 4.2.2 https://github.com/apache/incubator-heron#heron-requirements

**Comment by nicknezis** [comment]
Sorry, I should of linked to the feature branch in which I am attempting to upgrade to Bazel 6.0.0. I am one of the maintainers of this Apache project.

https://github.com/apache/incubator-heron/pull/3863

**Comment by nicknezis** [comment]
Actually I think it's ok to keep this closed. I think with the removal of `pkg_tar` from 6.0.0, this uncovered an implicit dependency on skylib that `rules_python` has. It's documented here. https://github.com/bazelbuild/rules_python/issues/932
