### ISSUE TITLE
Improve the error message when concurrent modification occurs with --experimental_guard_against_concurrent_changes enabled

### ISSUE THREAD

**Issue by tbaing** [bazelbuild/bazel#17173]
### Description of the feature request:

The logging that occurs when concurrent modification of output files occurs when `--experimental_guard_against_concurrent_changes` is specified didn't jump out to me as the explanation for why my outputs weren't being uploaded to the remote cache. Adding a bit more explanation to the error message would have helped me identify the connection between these things, and is especially important since the plan is to make that flag the default behavior in a future version.

### What underlying problem are you trying to solve with this feature?

It wasn't obvious to me that the warning about a file that was modified during the build was the reason my build artifacts weren't being uploaded to the remote cache.

### Which operating system are you running Bazel on?

gLinux

### What is the output of `bazel info release`?

experimental_guard_against_concurrent_changes

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
https://github.com/bazelbuild/bazel.git
f2cdf9e65eadfb5365127eabcc72dedce7781405
06deebfb5b73f848de5a0ea0e00fcfaa26788d1f
```

**Comment by coeuvre** [comment]
Fixed by https://github.com/bazelbuild/bazel/pull/17174.
