### ISSUE TITLE
"Unknown generator option" building java_lite_proto_library

### ISSUE THREAD

**Issue by zvh** [bazelbuild/bazel#1718]
I am trying to build a java_lite_proto_library but am getting an error:

```
> bazel build --proto_compiler=@protobuf//:protoc :lite_test
ERROR: /usr/local/google/bazel_workspace_playground/BUILD:1:1: Generating Java proto_library //:test failed: linux-sandbox failed: error executing command /usr/local/google/home/zachh/.cache/bazel/_bazel_zachh/0e447f8b1ae6fb3c23b3d7dae37f43b1/execroot/bazel_workspace_playground/_bin/linux-sandbox ... (remaining 6 argument(s) skipped).
--java_out: test.proto: Unknown generator option: lite

```

Here is my WORKSPACE file:

```
local_repository(
    name = "protobuf",
    path = "../protobuf-3.0.0",
)

bind(name = "protobuf/javalite_runtime", actual = "@protobuf//:protobuf_java"

```

Here is my BUILD:

```
proto_library(
    name = "test",
    srcs = ["test.proto"]
)

java_lite_proto_library(
    name = "lite_test",
    deps = [":test"],
)
```

@cgrushko has more context and may be able to fix

**Comment by cgrushko** [comment]
This is kinda fixed, but requires lengthy user setup. Once https://github.com/google/protobuf/issues/2583 is fixed, `java_lite_proto_library` will be trivial to use.

If you want to try `java_lite_proto_library` before that, I can help you setup your workspace.

**Comment by cgrushko** [comment]
See https://bazel.build/blog/index.html#protocol-buffers-in-bazel .
I also plan to update the Build Encyclopedia (http://be.bazel.build).

JavaLite is currently blocked on https://github.com/google/protobuf/issues/2762, https://github.com/google/protobuf/pull/2761 and https://github.com/google/protobuf/issues/2434 (for javalite).

But, we can look into a workaround.

**Comment by thaidn** [comment]
+1 for a workaround.

Also what can we do to prioritize fixing the blocking issues?

**Comment by Stokestack** [comment]
Anybody know what the status is on this? Why was it closed?
