### ISSUE TITLE
Java: Overriding record toString() can't be referred to as a dependency

### ISSUE THREAD

**Issue by rfevang** [bazelbuild/bazel#17181]
### Description of the bug:

The compiler complains about an ambiguous reference when trying to refer to an overriden `toString()` method of a `record`. The error only happens when the `record` class is a dependency, not when it is listed in `srcs`.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Empty `WORKSPACE`. (It also fails when loading `rules_java` 5.4.0

.bazelrc:
```
build --java_language_version=17 --java_runtime_version=remotejdk_17
build --tool_java_language_version=17 --tool_java_runtime_version=remotejdk_17
```
MyRecord.java:
```java
public record MyRecord(String value) {
  public String toString() {
    return "Custom toString(): " + value;
  }
}
```
DoubleToString.java:
```java
import java.util.function.Supplier;

public class DoubleToString {
  public Supplier<String> foo(MyRecord myRecord) {
    return myRecord::toString;
  }
}
```
BUILD.bazel:
```py
java_library(
    name = "my_record",
    srcs = ["MyRecord.java"],
)

# Failing rule:
java_library(
    name = "record_to_string_fails",
    srcs = ["DoubleToString.java"],
    deps = [":my_record"],
)

# Working rule:
java_library(
    name = "no_dep_to_string_works",      
    srcs = ["MyRecord.java", "DoubleToString.java"],
)
```

Doing a `bazel build :record_to_string_fails` results in the following output:
```
$ bazel build :record_to_string_fails
INFO: Analyzed target //:record_to_string_fails (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/fevang/debug/bazel_bug/BUILD.bazel:6:13: Building librecord_to_string_fails.jar (1 source file) failed: (Exit 1): java failed: error executing command (from target //:record_to_string_fails) external/remotejdk17_linux/bin/java '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 16 arguments skipped)
DoubleToString.java:5: error: incompatible types: invalid method reference
    return myRecord::toString;
           ^
    reference to toString is ambiguous
      both method toString() in MyRecord and method toString() in MyRecord match
Target //:record_to_string_fails failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.075s, Critical Path: 0.02s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

Building `:no_dep_to_string_works` works just fine.

### Which operating system are you running Bazel on?

Ubuntu 22.04.1 LTS

### What is the output of `bazel info release`?

release 6.0.0

### Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Ran into this issue when trying to convert a maven project to bazel.

Building with `javac` works, even when `MyRecord.java` is removed after compiling `MyRecord.class`.

**Comment by rfevang** [comment]
Similar (probably related) issue involving extra constructors:

MyRecord.java:
```
public record MyRecord(String value) {

  public MyRecord(String a, String b) {
    this(a + ", " + b);
  }  

  public String toString() {
    return "Custom toString(): " + value;
  }
}
```
ExtraConstructor.java:
```
public class ExtraConstructor {
  public void foo() {
    new MyRecord("string");
  }
}
```
Compiling both in a rule works. If `MyRecord` is a dependency when compiling `ExtraConstructor`, the following error is printed:
```
ExtraConstructor.java:3: error: constructor MyRecord in record MyRecord cannot be applied to given types;
    new MyRecord("string");
    ^
  required: String,String
  found:    String
  reason: actual and formal argument lists differ in length
```

**Comment by rfevang** [comment]
Thanks for looking at this @cushon!.

Are there more steps needed? I tried building with HEAD bazel and I still see the same error. Any way I can test this locally?

**Comment by cushon** [comment]
This will require a java_tools release, I think it's going to be included in https://github.com/bazelbuild/java_tools/issues/60

Until then, testing this requires additional steps: https://github.com/bazelbuild/java_tools/issues/43

**Comment by rfevang** [comment]
Thanks, I was indeed looking at the outdated documentation on how to run a local java_tools.

Can confirm an updated java_tools fixes the issue in the bug. The related error in my first comment is still there, so opening up a separate issue for that (#17250).
