### ISSUE TITLE
[bazel.coverage] Problem with coverage reports in multiple modes(set, atomic)

### ISSUE THREAD

**Issue by ahmsb8884** [bazelbuild/bazel#17194]
Team,
I am running coverage on several services together and the coverage reports for some are in mode: set or mode:atomic. due to these different mode aggregation of coverage report is not happening.  

Trying to figure out how can I set `covermode` when running `bazel coverage`? such that all reports are generated in one single mode. can we provide this flag or if it is there how can i use it?

I am getting error `error loading and merging go coverage files: multiple coverage modes found: set and atomic`

when i run 
`./bazel coverage --config=gocov src/services/... --collect_code_coverage --combined_report=lcov  --coverage_report_generator="//src/cmd/gocoverage-lcov:gocoverage-lcov"`

```
Bazelisk version: v1.11.0
Bazelisk version: v1.11.0
Build label: 5.1.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Apr 8 15:57:36 2022 (1649433456)
Build timestamp: 1649433456
Build timestamp as int: 1649433456
```

**bazelrc**
```
coverage:gocov --combined_report=lcov --coverage_report_generator="//src/cmd/gocoverage-lcov:gocoverage-lcov"
coverage:gocov-all --combined_report=lcov --instrument_test_targets --instrumentation_filter="^//src[/:]" --coverage_report_generator="//src/cmd/gocoverage-lcov:gocoverage-lcov"
```

**Comment by c-mita** [comment]
What is `//src/cmd/gocoverage-lcov:gocoverage-lcov`? This looks like a specific oddity of the rules or tools you are using, not a Bazel issue.

**Comment by sgowroji** [comment]
Hi @ahmsb8884, Could you please respond to the above [comment](https://github.com/bazelbuild/bazel/issues/17194#issuecomment-1429748780). Thanks

**Comment by comius** [comment]
Long time with no reply.
