### ISSUE TITLE
`--remote-download-minimal` does not behave correctly with RBE and `bazel test`.

### ISSUE THREAD

**Issue by antter** [bazelbuild/bazel#17190]
### Description of the bug:

When I set `--remote-download-minimal`, the behavior for downloading outputs is different depending on whether I am running `bazel test` or `bazel build` (during RBE). With `bazel build`, everything works as normal. with `bazel test`, it appears that the top-level artifacts of a target are downloaded.

I stumbled upon this because our CI runs `bazel test //...`. We noticed that on each invocation, we are downloading a large amount of outputs from the remote cache.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

With remote execution enabled and `--remote_download_minimal`, create a target. `bazel build` that target. Check that the target's outputs are not in the output base. Now `bazel test` that target. Confirm that the target's outputs are indeed in the output base.

### Which operating system are you running Bazel on?

M1 Mac 12.3.1

### What is the output of `bazel info release`?

release 6.0.0

### Any other information, logs, or outputs that you want to share?

slack thread here
https://bazelbuild.slack.com/archives/CA31HN1T3/p1673458583459269

and an example repo here
https://github.com/antter/bazel_remote_error

**Comment by antter** [comment]
seems like the offending line is here: https://github.com/bazelbuild/bazel/blob/ccfeeff06cdc0266b92781213bbdf33c4288b1c5/src/main/java/com/google/devtools/build/lib/remote/ToplevelArtifactsDownloader.java#L184

I'm in pretty deep over my head though when it comes to fixing this, unless it would just be as easy as removing this check, or having it check for the `downloadToplevel` attribute.

**Comment by joeljeske** [comment]
Could we pick this fix into an earlier 6.0 release? This looks like a recent regression

**Comment by brentleyjones** [comment]
It will be in the 6.1.0 release, which is the next planned release.

**Comment by joeljeske** [comment]
Great thank you. I was not sure if there would be a 6.0.1 that this could make it into.
