### ISSUE TITLE
bazel test no such package '@gtest//'

### ISSUE THREAD

**Issue by HaohanWang** [bazelbuild/bazel#1720]
I hope this is not a trivial question. 
Originally, my bazel works fine, but recently, it never works with the command bazel test, with the following error:

/usr/src/genamap/Models/BUILD:68:1: no such package '@gtest//': Error downloading from https://googletest.googlecode.com/files/gtest-1.7.0.zip to /root/.cache/bazel/_bazel_root/b837f432e18cbb79ee71409d6368a32b/external/gtest: Error downloading https://googletest.googlecode.com/files/gtest-1.7.0.zip to /root/.cache/bazel/_bazel_root/b837f432e18cbb79ee71409d6368a32b/external/gtest/gtest-1.7.0.zip: 404

what shall I do?

**Comment by ahyangyi** [comment]
I don't think it's a problem in Bazel itself.

Rather, the WORKSPACE you are working on is using outdated third-party dependencies.

**Comment by ahyangyi** [comment]
FYI: gtest-1.7.0 is available at https://github.com/google/googletest/archive/release-1.7.0.zip

**Comment by kchodorow** [comment]
Please leave a comment if @ahyangyi's solution is insufficient.
