### ISSUE TITLE
'Output null download failed' at HEAD

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#17206]
### Description of the bug:

We started seeing errors like this when testing HEAD bazel:

```
(12:16:40) ERROR: /private/var/tmp/_bazel_iosci/55999a8b204202b24d155a660922ad42/external/IDL/pb/api/models/v1/driver_pre_ride_dispatch/BUILD:3:4: Linking external/IDL/pb/api/models/v1/driver_pre_ride_dispatch/libIDLApiModelsV1DriverPreRideDispatch.a failed: Exec failed due to IOException: 15 errors during bulk transfer:
com.google.devtools.build.lib.remote.common.OutputDigestMismatchException: Output null download failed: Expected digest 'a5e4656fb8de088ce00ef119e3021fb8d7b6d464a98eed3dbfc47481d77939f3/6568' does not match received digest '338aae3389ee5261f5336964a3eae78b8cf524cfed2d9bb8a17da2d875cd2fcc/13136'.
com.google.devtools.build.lib.remote.common.OutputDigestMismatchException: Output null download failed: Expected digest 'af179899e1d19530f330899f4725868ff4bec9b00f5bfb0868c61b08ac5b3e91/31992' does not match received digest '09caa7c68d836cfe637f17f4b49bc2d2e486753e9cd47b96dbd39984375921ae/63984'.
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I might be able to come up with a repro case.

I believe it is in this diff https://github.com/bazelbuild/bazel/compare/ccfeeff06cdc0266b92781213bbdf33c4288b1c5...11729dc35e15a656c8475829e575e02c640b3ac9 given we test ~daily and just started seeing it today

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

11729dc35e15a656c8475829e575e02c640b3ac9

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

bazelisk last_green

**Comment by brentleyjones** [comment]
@coeuvre Maybe https://github.com/bazelbuild/bazel/commit/9971445667af255a5e45fadea8b693d6ae91439b?

**Comment by coeuvre** [comment]
Not sure. I don't see why that commit would trigger the error. Let's see whether I can eazily repro it locally.

**Comment by coeuvre** [comment]
I cannot reproduce it locally.

@keith How often do you see the error in your test?
