### ISSUE TITLE
bazel-1.0.0: Depends: python but it is not installable

### ISSUE THREAD

**Issue by jbuttle63** [bazelbuild/bazel#17213]
### Description of the bug:

I'm trying the install bazel 1.0.0 (a C++ package depends on this version specifically). When I attempt to install it I get the following message:
`$ sudo apt install bazel-1.0.0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 bazel-1.0.0 : Depends: python but it is not installable
E: Unable to correct problems, you have held broken packages.`

I have python 3.10.6 installed on my system:
`python
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()`

All other dependences are installed. My system is Ubuntu command line installed through WSL2:
`$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy`

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Attempt to install Bazel 1.0.0 on Ubuntu 22.04 through WSL2 on Windows 11.

### Which operating system are you running Bazel on?

Ubuntu 22.04 - jammy

### What is the output of `bazel info release`?

NA

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

NA

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
NA
```

### Have you found anything relevant by searching the web?

There was a closed submission on this site. No resolution was listed.

**Comment by meteorcloudy** [comment]
Please try to use Bazelisk to download Bazel. You can download Bazelisk from https://github.com/bazelbuild/bazelisk/releases.
Check https://github.com/bazelbuild/bazelisk#how-does-bazelisk-know-which-bazel-version-to-run on how to fetch a specific Bazel version.
