### ISSUE TITLE
[Mirror] Gazelle 0.29.0

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel#17219]
### Please list the URLs of the archives you'd like to mirror:

Please mirror https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.29.0/bazel-gazelle-v0.29.0.tar.gz

**Comment by sgowroji** [comment]
Please find the mirror artifact :
https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.29.0/bazel-gazelle-v0.29.0.tar.gz
