### ISSUE TITLE
Resizing the terminal kills `bazel run` tests

### ISSUE THREAD

**Issue by the-mikedavis** [bazelbuild/bazel#17215]
### Description of the bug:

Resizing the terminal while running `bazel run TARGET` when `TARGET` is a test rule makes the bazel process exit with code 156. This doesn't occur when `TARGET` is an executable but non-test rule.

I can reproduce this on Linux and macOS with Kitty, Alacritty and WezTerm terminal emulators with terms `xterm-kitty` and `xterm-256color`. Whether `$PAGER` is set or not doesn't seem to make a difference.

https://user-images.githubusercontent.com/21230295/212404989-0387682b-cbb3-4ac5-9826-46877aa31e66.mp4

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I put together a MWE here: https://gist.github.com/the-mikedavis/6b34a7f445a30fb34331d1fa19b89201

Most minimally, a directory with an empty `WORKSPACE` file, a `BUILD` file with contents like so:

```starlark
load("//:defs.bzl", "build")
build(name = "hello")
```

and `defs.bzl`:

```starlark
def _impl(ctx):
    output = ctx.actions.declare_file(ctx.label.name)
    script = """echo "..."
    sleep 60
    echo "Hi!"
    """
    ctx.actions.write(
        output = output,
        content = script,
    )
    return [DefaultInfo(executable = output)]

build = rule(
    implementation = _impl,
    test = True,
)
```

Altogether the directory should look like so:

```
$ tree .
.
├── BUILD
├── defs.bzl
└── WORKSPACE

3 files
```

Run `bazel run //:hello` in this directory. Once you see the "...", resize the terminal. For resizing done through a window manager, you need to resize the terminal twice: the first resize doesn't kill bazel. The `bazel` process should exit with code 156.

### Which operating system are you running Bazel on?

Linux, macOS

### What is the output of `bazel info release`?

release 6.0.0

**Comment by brentleyjones** [comment]
Not stale.
