### ISSUE TITLE
HttpConnector should retry 502 bad gateway errors

### ISSUE THREAD

**Issue by exoson** [bazelbuild/bazel#17223]
### Description of the feature request:

502 bad gateway errors should be retried in HttpConnector.java as those are often transient. Relevant PR https://github.com/bazelbuild/bazel/pull/17222 

### What underlying problem are you trying to solve with this feature?

A single http request returning 502 inside HttpConnector.java can fail the whole build. Adding retries when this error happens adds resiliency against infra issues causing this error.

**Comment by Wyverald** [comment]
I don't think 502 errors should be retried. This often happens when the reverse proxy is overloaded, and retrying immediately can only make matters worse.

**Comment by exoson** [comment]
I mean that's why you have the exponential backoff in the retries so that all the retries won't just be bombarded right away.
