### ISSUE TITLE
how to make a dependent repository hidden?

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/bazel#17227]
### Description of the bug:

my project import grpc and brpc at same time, for some reason, brpc must use openssl, but grpc use boringssl, so link will failed for  duplicated symbols, so how to make boringssl only visible to grpc?

### Which operating system are you running Bazel on?

ubuntu 22.04

### What is the output of `bazel info release`?

5.2.0

**Comment by Wyverald** [comment]
Does this page help? https://bazel.build/build/external#shadowing-dependencies

P.S. Please use our support channels (slack.bazel.build or bazel-discuss@googlegroups.com) for such questions.
