### ISSUE TITLE
Is there a way to access rule struct fields from a function definition?

### ISSUE THREAD

**Issue by mrdomino** [bazelbuild/bazel#1723]
This is an attempt to distill what I just ran into in mrdomino/sandstorm-bazel#1.

If I have a `defs.bzl` containing something like this:

```
def _impl(ctx):
  return struct(
    foo='bar',
  )

_gen = rule(
  attrs = {},
  implementation=_impl,
)

def main(name):
  _gen(name = name + "_gen")
  native.genrule(
    name = name,
    outs = [name + "_stub.txt"],
    cmd = "touch $@"
  )
```

Is there any way to get at `foo` from main?

Alternatively, is there a way to cause a cc_library to be created in _impl?

And the reason I actually need this in the first place is that I'm trying to make a rule available across repository boundaries, i.e. have a capnp library in my root workspace with source files in @capnproto. So if there's some other way to do that, then for my purposes it would also resolve this issue.

**Comment by ahyangyi** [comment]
Disclaimer again: I'm not currently working in Google nor a Bazel team member. I'm also a Bazel user.

> Is there any way to get at foo from main?
If you know the output is called `"bar"`, would the label `":bar"` work?
> Alternatively, is there a way to cause a cc_library to be created in _impl?
It's easier if you create it in `main()` and pass it to `_impl` as a `attr`.
> And the reason I actually need this in the first place is that I'm trying to make a rule available across repository boundaries, i.e. have a capnp library in my root workspace with source files in @capnproto. So if there's some other way to do that, then for my purposes it would also resolve this issue.
I'm not sure what you are trying to achieve. Would a `filegroup` in your sub-repository suffice?

**Comment by kchodorow** [comment]
> Sure, that'd be nice, but then how do I get capnproto.bzl to be available from that external? Keep in mind that you can't reference Skylark rules in the //external namespace for some reason.

You should be able to do, e.g., `load("@sandstorm//:capnproto.bzl", "whatever")`, is that what you mean?

**Comment by damienmg** [comment]
Seems like this was answered, closing, feel free to ping back if you still need help
