### ISSUE TITLE
Different starlark functions generated from the same source calling each other triggers recursion check

### ISSUE THREAD

**Issue by torgil** [bazelbuild/bazel#17236]
### Description of the bug:

If two functions that are generated from the same function calls each other, bazel triggers recursion check. Below example results in (current dir replaced with $PWD):
```
ERROR: /Users/torgil/src/bazel/lambda_calling_lambda/BUILD.bazel:2:12: in return_srcs rule //:fail: 
Traceback (most recent call last):
        File "$PWD/rules.bzl", line 13, column 44, in lambda
                implementation = lambda ctx: result(ctx = ctx),
        File "$PWD/rules.bzl", line 4, column 29, in lambda
                return lambda *, ctx: fn(ctx = ctx, **kw)
        File "$PWD/rules.bzl", line 7, column 69, in lambda
                default_info = lambda *, ctx, files_cb: DefaultInfo(files = files_cb(ctx = ctx))
        File "$PWD/rules.bzl", line 4, column 12, in lambda
                return lambda *, ctx: fn(ctx = ctx, **kw)
Error: function 'lambda' called recursively
```
This is unexpected as they are two separate functions and not the same function calling itself as in #8921 which needs recursion allowed ( #9163 ).

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Download bazel-6.0.0 (make sure it has that name, is executable and available in $PATH)
2. Open a terminal with zsh or bash
3. Create a directory, cd into it, paste below script into the terminal and press enter

```
touch WORKSPACE

cat <<EOF > rules.bzl
def partial(fn, **kw):
    # Different instances of this lambda is treated as the same function
    # resulting in "Error: function 'lambda' called recursively"
    return lambda *, ctx: fn(ctx = ctx, **kw)

get_files = lambda *, ctx, attribute: depset(getattr(ctx.files, attribute))
default_info = lambda *, ctx, files_cb: DefaultInfo(files = files_cb(ctx = ctx))

def create_return_files_rule(attribute):
    files = partial(get_files, attribute = attribute)
    result = partial(default_info, files_cb = files)
    return rule(
        implementation = lambda ctx: result(ctx = ctx),
        attrs = {attribute: attr.label_list(allow_files = True)},
    )

return_srcs = create_return_files_rule("srcs")
EOF

cat <<EOF > BUILD.bazel
load("rules.bzl", "return_srcs")
return_srcs(
    name = "fail",
    srcs = ["WORKSPACE", "rules.bzl", "BUILD.bazel"],
)
EOF

bazel-6.0.0 build //:fail
```

### Which operating system are you running Bazel on?

Seen on Ubuntu 22.04 and Mac OS Ventura 13.1

### What is the output of `bazel info release`?

release 6.0.0-homebrew

### Have you found anything relevant by searching the web?

#8921 and #9163 are related to the same error message.

**Comment by brandjon** [comment]
Thanks for the report.

This is WAI. The [recursion check](https://github.com/bazelbuild/bazel/blob/9fce5fc166bf170ecd50870903768f6d3c8054ef/src/main/java/net/starlark/java/eval/StarlarkThread.java#L360-L362) is based on the static function definition text, not the dynamic function value. This is to prevent arbitrary unbounded computation (i.e. circumventing the recursion check) by dynamically creating new function values. (If we decided to allow that, at that point we may as well disable the recursion check entirely.)
