### ISSUE TITLE
Stringification of an apparent label that fails repo mapping produces an incorrect canonical form

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/bazel#17258]
### Description of the bug:

In a macro I produce an apparent label that fails repo mapping. When I stringify it, it produces an invalid canonical form instead of erroring. Calling `.workspace_name` on the label correctly errors:

```
Error: 'workspace_name' is not allowed on invalid Label @[unknown repo 'SwiftLint' requested from @rules_xcodeproj~override]//:swiftlint
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```starlark
print(str(Label("@SwiftLint//:swiftlint")))
```

It prints `@@SwiftLint//:swiftlint`, but should error, since `@@SwiftLint//:swiftlint` isn't a valid label.

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 6.0.0

### Any other information, logs, or outputs that you want to share?

@fmeum asked me to file this 😄.

**Comment by Wyverald** [comment]
I actually noticed this myself yesterday and have a change in flight to fix it :)

**Comment by brentleyjones** [comment]
@bazel-io flag

**Comment by Wyverald** [comment]
@bazel-io fork 6.1.0
