### ISSUE TITLE
"fopen(/proc/self/uid_map)": No such file or directory

### ISSUE THREAD

**Issue by YongCHN** [bazelbuild/bazel#1725]
The bazel is installed the docker environment (OS:CentOS)

I followed the GetStarted doc and write the below BUILD file:

> 
genrule(
  name = "hello",
  outs = ["hello_world.txt"],
  cmd = "echo Hello World > $@",
)`

And the bazel show below error message:
>
#bazel build :hello --verbose_failures
INFO: Found 1 target...
ERROR: /root/source/sandbox/hello_bazel/BUILD:1:1: Executing genrule //:hello failed: linux-sandbox failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/76d3310ffc8625d0408c2ca3bae397b0/bazel-sandbox/39ff867e-03f5-465d-92e8-8c38b58b74a4-0/execroot && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/satools:/root/source/bazel/output/ \
  /root/.cache/bazel/_bazel_root/76d3310ffc8625d0408c2ca3bae397b0/execroot/hello_bazel/_bin/linux-sandbox @/root/.cache/bazel/_bazel_root/76d3310ffc8625d0408c2ca3bae397b0/bazel-sandbox/39ff867e-03f5-465d-92e8-8c38b58b74a4-0/linux-sandbox.params -- /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; echo Hello World > bazel-out/local-fastbuild/genfiles/hello_world.txt').
src/main/tools/linux-sandbox-pid1.cc:95: "fopen(/proc/self/uid_map)": No such file or directory
Target //:hello failed to build
INFO: Elapsed time: 0.308s, Critical Path: 0.06s

Does the bazel not support the docker building environment?
Thanks.

**Comment by kchodorow** [comment]
It looks like user namespaces are a fairly new feature of Docker (https://integratedcode.us/2016/02/05/docker-1-10-security-userns/), is it possible you're using an older version?

(You can also turn off the sandbox, if you want: https://github.com/bazelbuild/bazel/wiki/How-to-turn-off-sandboxing.)

**Comment by kchodorow** [comment]
Closing, as there has been no response for a month.
