### ISSUE TITLE
F tensorflow/stream_executor/cuda/cuda_blas.cc:263] Check failed: f != nullptr could not find cublasCreate_v2 in cuBLAS DSO; dlerror: bazel-bin/tensorflow/cc/tutorials_example_trainer: undefined symbol: cublasCreate_v2

### ISSUE THREAD

**Issue by NacyLiu** [bazelbuild/bazel#1726]
Ubuntu: 16.04
GCC: 5.4
Cuda: 8.0
Cudnn: cudnn-8.0-linux-x64-v5.0

Here is the bazel build result:
INFO: From Compiling tensorflow/core/kernels/tile_ops_gpu.cu.cc:
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
INFO: From Compiling tensorflow/core/kernels/tile_ops_gpu.cu.cc:
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
Target //tensorflow/cc:tutorials_example_trainer up-to-date:
  bazel-bin/tensorflow/cc/tutorials_example_trainer
INFO: Elapsed time: 985.075s, Critical Path: 952.03s

it seems the target build sucessfully.
But I got an error when i bazel-bin, here is the output:
server@server:~/tensorflow$ bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu
I tensorflow/stream_executor/dso_loader.cc:105] Couldn't open CUDA library libcublas.so.8.0. LD_LIBRARY_PATH: 
I tensorflow/stream_executor/cuda/cuda_blas.cc:2289] Unable to load cuBLAS DSO.
I tensorflow/stream_executor/dso_loader.cc:105] Couldn't open CUDA library libcudnn.so.5. LD_LIBRARY_PATH: 
I tensorflow/stream_executor/cuda/cuda_dnn.cc:3304] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:105] Couldn't open CUDA library libcufft.so.8.0. LD_LIBRARY_PATH: 
I tensorflow/stream_executor/cuda/cuda_fft.cc:343] Unable to load cuFFT DSO.
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] Couldn't open CUDA library libcurand.so.8.0. LD_LIBRARY_PATH: 
I tensorflow/stream_executor/cuda/cuda_rng.cc:333] Unable to load cuRAND DSO.
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:02:00.0
Total memory: 11.92GiB
Free memory: 11.38GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:02:00.0)
F tensorflow/stream_executor/cuda/cuda_blas.cc:263] Check failed: f != nullptr could not find cublasCreate_v2 in cuBLAS DSO; dlerror: bazel-bin/tensorflow/cc/tutorials_example_trainer: undefined symbol: cublasCreate_v2

where am i wrong?

**Comment by kchodorow** [comment]
It looks like it can't find libcublas.so.8.0 on your library path.  Can you try running `LD_LIBRARY_PATH=/path/to/lib bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu` (replacing /path/to/lib with the actual path to the directory containing libcublas.so.8.0)?

**Comment by NacyLiu** [comment]
Thanks so much! I've fixed it.

**Comment by TingjinLuo** [comment]
I have meet the same problem. Could you give me more details to solve this problem? How did you solved it? Thanks.

**Comment by damienmg** [comment]
@TingjinLuo please reopen a bug with a precise repro. The suggested change is to set LD_LIBABRY_PATH correctly

**Comment by NacyLiu** [comment]
@TingjinLuo i've set the LD_LIBABRY_PATH as @kchodorow suggested, and it works, good luck

**Comment by TingjinLuo** [comment]
Thanks

2016年10月9日星期日，NacyLiu <notifications@github.com> 写道：
