### ISSUE TITLE
[Mirror] rules_cc-0.0.2.tar.gz, rules_java-5.4.0.tar.gz, (rules_proto) 5.3.0-21.7.tar.gz

### ISSUE THREAD

**Issue by nacl** [bazelbuild/bazel#17262]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/rules_cc/releases/download/0.0.2/rules_cc-0.0.2.tar.gz
https://github.com/bazelbuild/rules_java/releases/download/5.4.0/rules_java-5.4.0.tar.gz
https://github.com/bazelbuild/rules_proto/archive/refs/tags/5.3.0-21.7.tar.gz

Currently, as a part of building bazel itself, archives are downloaded only from github as mentioned distdir_deps.bzl:

https://github.com/bazelbuild/bazel/blob/bfa72889ec6cb9bfb359226124c43ecffa44b078/distdir_deps.bzl#L56-L97

They should also be made available on the mirror and perhaps downloaded from there when building bazel. Let me know if I should make a separate task for this, thanks!

**Comment by sgowroji** [comment]
Please find the below mirror artifacts
1. https://mirror.bazel.build/github.com/bazelbuild/rules_cc/releases/download/0.0.2/rules_cc-0.0.2.tar.gz
2. https://mirror.bazel.build/github.com/bazelbuild/rules_java/releases/download/5.4.0/rules_java-5.4.0.tar.gz
3. https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/refs/tags/5.3.0-21.7.tar.gz
