### ISSUE TITLE
[bazel.build] Problem with /install/ubuntu

### ISSUE THREAD

**Issue by Bear-Witness-98** [bazelbuild/bazel#17286]
When trying to execute the installer of the 5.4.0version on a raspberry pi 4, with raspbian, the --user flag is not properly recognise. The installer asked for permissions instead.

**Comment by sgowroji** [comment]
Hi @Bear-Witness-98, Could you please provide complete steps to reproduce the above issue. And also give the documentation changes are you expecting in the above. Thanks !

**Comment by Bear-Witness-98** [comment]
Sorry, I was using a 64bit bazel on a 32bit Raspberry OS, now I could install it properly.

Thanks for the quick response

**Comment by sgowroji** [comment]
We are closing this issue now. Please reach if you still have any queries. Thanks!
