### ISSUE TITLE
//src/test/java/com/google/devtools/build/lib/skylark:SkylarkTests broken on Windows

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1729]
http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=windows-x86_64/791/console

Suspected culprit: https://github.com/bazelbuild/bazel/commit/0d5ecf708f5e4c88b370bbab2ccc313fafe74348

**Comment by kchodorow** [comment]
No good deed goes unpunished. Please fix or rollback.

**Comment by meteorcloudy** [comment]
I am going to send a change to fix this soon.
