### ISSUE TITLE
deps, runtime_deps, and licenses for maven_jar

### ISSUE THREAD

**Issue by jart** [bazelbuild/bazel#1733]
Proposal: add `deps`, `runtime_deps`, and `licenses` attributes to `maven_jar` which get passed through unmodified to the generated `java_import` rule.

This is a super simple change that would fix 50% of the transitive dependency problem. As you know, half the problem is that if I reference something like `@closure_compiler//jar` in my deps list, I also have to reference all of its dependencies too. This change would fix that, without needing to change the downloading infrastructure.

It would also fix some of the licensing problems. For example, `@closure_compiler//jar` has both notice and restricted sources. I want to be able to declare that, without creating an intermediary rule.

**Comment by kchodorow** [comment]
@jin, please don't add these features to https://bazel-review.googlesource.com/c/5770/ (enough going on there as it is), but they should be trivial to add once 5770 is in.

**Comment by ittaiz** [comment]
When you talk about adding deps and runtime_deps do you mean transitive dependencies?

**Comment by jart** [comment]
Basically what I want to do is automate writing files like [this](https://github.com/bazelbuild/rules_closure/blob/abb9cb100bec78e1b36c12668c1d1936042c3dd5/third_party/java/jscomp/BUILD):

![image](https://cloud.githubusercontent.com/assets/49262/18299855/30c83d30-7479-11e6-8edc-3c17cd9f2119.png)

It would be better if I could write this:

```python
maven_jar(
    name = "closure_compiler",
    artifact = "com.google.javascript:closure-compiler-unshaded:v20160822",
    sha1 = "227153aedf239124c2b0c5a680e912c95480fbe6",
    server = "closure_maven_server",
    deps = [
        "@args4j//jar",
        "@gson//jar",
        "@guava//jar",
        "@jsr305//jar",
        "@protobuf_java//jar",
    ],
    licenses = [
        "notice",  # Apache License 2.0 (Closure Compiler)
        "reciprocal",  # Mozilla Public License Version 1.1 (Rhino AST)
    ],
)
```

When it comes to these rules, `deps` would be defined as the statically linked dependencies of the jar and `runtime_deps` would be defined as the dependencies which are needed at runtime, because the jar might do something like use reflection to load classes from the dependency.

**Comment by ittaiz** [comment]
Oh ok, so valuable for me but not what I thought.
Though I probably just need something like generate workspace as a Java
library.

**Comment by jart** [comment]
@kchodorow I've defined the Skylark rule [java_import_external](https://github.com/bazelbuild/rules_closure/blob/master/closure/private/java_import_external.bzl) which has served Nomulus, TensorFlow, Closure Rules, and Webtesting Rules well for months. This Skylark rule addresses all the concerns raised in this issue.

Is it time for this rule to graduate to the Bazel project? If so, please take a look at cl/151653566. I'm attempting to add documentation, but want to hear your thoughts before proceeding further.

**Comment by kchodorow** [comment]
I like it, ship it.  

Maybe we could have a wrapper that makes it a bit more like your example in https://github.com/bazelbuild/bazel/issues/1733#issuecomment-245172371: takes an artifact identifier and populates some likely repos.

**Comment by dslomov** [comment]
Is there anything more to do @jart ?

**Comment by jart** [comment]
We're probably better off just recommending people use [java_import_external](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/java.bzl) which is now in the Bazel codebase and used by a whole bunch of projects. It has all these important attributes. There's also an Apps Script microservice web GUI for generating these configs: https://github.com/bazelbuild/bazel/pull/3946
