### ISSUE TITLE
Zipapps no longer deleting Bazel.runfiles_* directories placed in /tmp

### ISSUE THREAD

**Issue by sethasadi** [bazelbuild/bazel#17342]
### Description of the bug:

As of Bazel 6.0.0, a change was made to [bazel/rules/python/python_stub_template.txt](https://github.com/bazelbuild/bazel/commit/9d0163002ca63f4cdbaff9420380d72e2a6e38b3#diff-fa3ae340fea197099f8d4b5101d1d71bccc3ceece3517b4ea9126e2d448eab01) that [gates the deletion](https://github.com/bazelbuild/bazel/commit/9d0163002ca63f4cdbaff9420380d72e2a6e38b3#diff-fa3ae340fea197099f8d4b5101d1d71bccc3ceece3517b4ea9126e2d448eab01R336-R337) of the `Bazel.runfiles_*` directory that is created in `/tmp`. This is because it depends on workspace being set, and workspace is only set [when `RUN_UNDER_RUNFILES` is set](https://github.com/bazelbuild/bazel/commit/9d0163002ca63f4cdbaff9420380d72e2a6e38b3#diff-fa3ae340fea197099f8d4b5101d1d71bccc3ceece3517b4ea9126e2d448eab01R501-R507). This is a regression from the previous behavior where the directory placed in `/tmp` would be deleted as long as it was [running under a zip](https://github.com/bazelbuild/bazel/commit/9d0163002ca63f4cdbaff9420380d72e2a6e38b3#diff-fa3ae340fea197099f8d4b5101d1d71bccc3ceece3517b4ea9126e2d448eab01L296-L303). This should be fixed so that the `Bazel.runfiles_*` directories are cleaned up whenever it is running under a zip.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build a zipapp target on Bazel 6.0.0 (without `RUN_UNDER_RUNFILES` set) and on whatever machine you consume that zipapp there will be a `Bazel.runfiles_<sha>` directory with the zipapp contents left around from execution.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 6.0.0

**Comment by sethasadi** [comment]
Pinging this issue. @rickeylev I noticed you've been making changes around the Python rules here. Would you be able to take a look? This issue is coming up more and more as more projects are upgraded to Bazel 6.

**Comment by rickeylev** [comment]
What is this "RUN_UNDER_RUNFILES" environment variable? Is there some doc about this? As near as I can tell it's only set when Bazel runs a target as a test?

Anyways, yeah, bug. I was able to repro.

**Comment by sethasadi** [comment]
@rickeylev thank you for getting this done so quickly. Can you merge this into the Bazel 6.1 branch so that it can go out as soon as possible?

**Comment by rickeylev** [comment]
I suppose so. I've never done or requested a backport, so I'll have to ask around how to do that.

**Comment by sethasadi** [comment]
@rickeylev this mentions how: https://github.com/bazelbuild/bazel/issues/17212#issuecomment-1439198224

**Comment by keertk** [comment]
Hi all, can this wait till the next release (6.2)? We've already created the third release candidate for 6.1 and plan to do the final release on Monday.

**Comment by rickeylev** [comment]
Hi,

Yes, if it's too late for 6.1, then 6.2 is fine.

**Comment by keertk** [comment]
@bazel-io fork 6.2.0

**Comment by mpereira** [comment]
I was seeing this on 6.3.2 and tried upgrading to 7.1.1 to see if it fixed it, but it still happens.

Anyone else still seeing this?
