### ISSUE TITLE
[bazel.build] Problem with /reference/be/python

### ISSUE THREAD

**Issue by sebastian-nomi** [bazelbuild/bazel#17364]
Python_rules Sha256 checksums are not matching. 

Example for [0.10.0](https://github.com/bazelbuild/rules_python/releases/tag/0.10.0):
- Expected sha256 = "56dc7569e5dd149e576941bdb67a57e19cd2a7a63cc352b62ac047732008d7e1"
- Sha256 generated from 0.10.0.tar.gz: "647033f647a346e6eb9243c09788cb10e646add323302e11becc46cbc3e970b1"

This is causing Bazel to fail builds.

**Comment by sgowroji** [comment]
Hello @sebastian-nomi, Could you please elaborate your query with complete details. Like Links or resources  which required to share. Thanks!

**Comment by sgowroji** [comment]
This is [fixed](https://github.com/bazelbuild/rules_python/releases?page=2#:~:text=Compare-,0.10.0,-WORKSPACE%20setup%3A.)  We are closing this issue now. Feel free to reach us for any further information.
