### ISSUE TITLE
attr.label does not accept 'aspects'

### ISSUE THREAD

**Issue by pcj** [bazelbuild/bazel#1739]
Documentation for aspects https://www.bazel.io/versions/master/docs/skylark/aspects.html#applying-aspects-to-rule-attributes suggests attr.label is compatible.  However, when I try it with 0.3.1/1469783118 the following error occurs:

```sh
unexpected keyword 'aspects' in call to label(*, 
default: Label or Label-returning function or NoneType = None, 
executable: bool = False, 
allow_files = None, 
allow_single_file = None, 
mandatory: bool = False, 
providers: sequence = [], 
allow_rules: sequence of strings or NoneType = None, 
single_file: bool = False, 
cfg = None)
```

attr.label_list does work though.

**Comment by brandjon** [comment]
Right, aspects= should probably be added for label() to work the same as for label_list().

**Comment by pcj** [comment]
Looks like it would go in here, to start https://github.com/bazelbuild/bazel/blob/180d1b56b8aea8fab974cfa57e9182598990710c/src/main/java/com/google/devtools/build/lib/rules/SkylarkAttr.java#L548-L589
