### ISSUE TITLE
https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/: could not fetch https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/: Get "https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/": dial tcp 142.251.42.234:443: i/o timeout

### ISSUE THREAD

**Issue by jinfagang** [bazelbuild/bazel#17405]
### Description of the feature request:

In China, all google related url were blocked. Even with VPN, is not work.

### What underlying problem are you trying to solve with this feature?

Can u switch to **any** github based url instead???

### Which operating system are you running Bazel on?

windows

### What is the output of `bazel info release`?

latest

**Comment by sgowroji** [comment]
Hi @jinfagang, Can you share the complete description and links which you are using above , which are blocked. Thanks !

**Comment by jinfagang** [comment]
@sgowroji Please help[

**Comment by fweikert** [comment]
You're using https://github.com/bazelbuild/bazelisk - remove it from your system and install Bazel manually from https://github.com/bazelbuild/bazel/releases/tag/6.0.0

**Comment by fweikert** [comment]
There's also a workaround: https://github.com/bazelbuild/bazelisk/issues/234#issuecomment-830832075

**Comment by jinfagang** [comment]
@fweikert I didn't even know where does bazelisk installed on windows.

installation I fixed yesterday.

Now I got a new issue:

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/21303438/216745655-f68b820a-375e-4ba5-9bcf-2456685dbac1.png">

I don't know why, the python I specific is exist

this is caused by one of google product mediapipe build: `bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="D:\anaconda\python.exe"`

the python.exe actually does existed

**Comment by sgowroji** [comment]
@jinfagang, Above error logs seems to Python path setup. And the error logs doesn't seems to related to Bazel. I am closing this issue now. Please reach us back if you still have any query or facing error with respect to Bazel. Thanks!
