### ISSUE TITLE
tool(tool="//some:target") doesn't declare a dependency on the target

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/bazel#17401]
### Description of the bug:

The `tool` macro provided by `cc_toolchain_config_lib.bzl` claims the following in its arguments:

```
        path: Location of the tool; Can be absolute path (in case of non hermetic
            toolchain), or path relative to the cc_toolchain's package. If this
            parameter is set, tool must not be set.
        tool: The built-artifact that should be used as this tool. If this is
            set, path must not be set.
```

My understanding after reading this is that using `tool="//some:target"` should cause the given target to be built as a dependency of the tool -- but this does not seem to be the case. Even if the provided target exists and can be built correctly when given explicitly to `bazel build`, the target won't be picked up as a dependency of the tool.

---

The reason I'm trying to do this is because I need to write a wrapper script for the linker (because of #17368) and I wanted to use a `genrule` to auto-generate the script based on certain string replacements. Unfortunately, I've found no way to do this, and I had to end up checking in the "auto-generated" script and using that instead. This is a problem because now I have to remember to maintain this checked-in script, and I had to add logic to our toolchain definitions to attempt to spot stale files.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Write a `genrule` that creates a shell script.
2. Declare a `tool`, using the macro from `@bazel_tools//tools/cpp:cc_toolchain_config_lib.bzl`, that depends on the `genrule` via the `tool` attribute.
3. Try to use the `tool` and notice how the dependency is never built.

### Which operating system are you running Bazel on?

Linux, but this is irrelevant

### What is the output of `bazel info release`?

bazel release 6.0.0

**Comment by sgowroji** [comment]
Hi @jmmv, Could you please provide a sample code to reproduce the above mentioned steps. Thanks!
