### ISSUE TITLE
package default visibility does not appear in the --output=xml query result of a rule target

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel#17402]
### Description of the bug:

When we have something like `package(default_visibility=["//visibility:public"])` at the top of a build file, and the targets in the build file does not have `visibility` attribute defined, Bazel query result has visibility in all file targets but not rule targets.

This affects the availability to calculate target hash from query result like [this](https://github.com/bazelbuild/bazel/issues/7962#issuecomment-553042506), because we want the target hash to change when visibility of a target changes

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Create a workspace like this:
```
-- WORKSPACE --
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "dd926a88a564a9246713a9c00b35315f54cbd46b31a26d5d8fb264c07045f05d",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.38.1/rules_go-v0.38.1.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.38.1/rules_go-v0.38.1.zip",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(version = "1.19.5")
-- BUILD.bazel --
-- foo/BUILD.bazel --
load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility=["//visibility:public"])

go_library(
    name = "foo",
    importpath = "example.com/foo",
    srcs = ["foo.go"],
)
-- foo/foo.go --
package foo
```
2. Run `bazel query --output=xml //foo:all-targets`:
```xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<query version="2">
    <source-file location="/private/tmp/visibility/foo/BUILD.bazel:1:1" name="//foo:BUILD.bazel">
        <visibility-label name="//visibility:public"/>
    </source-file>
    <rule class="go_library" location="/private/tmp/visibility/foo/BUILD.bazel:5:11" name="//foo:foo">
        <string name="name" value="foo"/>
        <string name="generator_name" value="foo"/>
        <string name="generator_function" value="go_library_macro"/>
        <string name="generator_location" value="foo/BUILD.bazel:5:11"/>
        <list name="srcs">
            <label value="//foo:foo.go"/>
        </list>
        <string name="importpath" value="example.com/foo"/>
        <rule-input name="//foo:foo.go"/>
        <rule-input name="@bazel_tools//tools/allowlists/function_transition_allowlist:function_transition_allowlist"/>
        <rule-input name="@io_bazel_rules_go//:go_context_data"/>
    </rule>
    <source-file location="/private/tmp/visibility/foo/foo.go:1:1" name="//foo:foo.go">
        <visibility-label name="//visibility:public"/>
    </source-file>
</query>
```

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 6.0.0-homebrew

**Comment by haxorz** [comment]
Try additionally passing `--xml:default_values`. I did that on a simpler example and it worked for me.

> This affects the availability to calculate target hash from query result like https://github.com/bazelbuild/bazel/issues/7962#issuecomment-553042506, because we want the target hash to change when visibility of a target changes

Ack. I appreciate the context :)

You may be interested in `--proto:include_synthetic_attribute_hash`.

**Comment by linzhp** [comment]
Thanks `--xml:default_values` works

**Comment by haxorz** [comment]
I'm inclined to close this as WAI. WDYT?

Maybe the documentation for https://bazel.build/query/language#xml-defaultvalues could give this behavior as an example?

**Comment by linzhp** [comment]
That would be helpful
