### ISSUE TITLE
Remove dependency on Velocity from //third_party dir

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#17416]
Once the stardoc renderer binary is migrated to the bazelbuild/stardoc repo instead of the bazelbuild/bazel repo, we shouldn't need to have bazel depend on the velocity templating engine. This issue is a reminder to cull that dep. cc @tetromino

**Comment by tetromino** [comment]
For future reference: Bazel is using Apache Velocity for build encyclopedia / api doc generation (see Page.java and the .vm template files in https://github.com/bazelbuild/bazel/tree/master/src/main/java/com/google/devtools/build/docgen/templates) - so we cannot remove this dependency.
