### ISSUE TITLE
--remote_download_toplevel downloads stuff silently

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/bazel#17417]
### Description of the bug:

When building anything on a remote build farm with `--remote_download_toplevel`, Bazel gets "stuck" after the `INFO: Build completed successfully` message. When this happen, the network is busy like crazy downloading the request artifacts, which "works" but has a bad UI.

Compare this to building without any `--remote_download_*` flags, where Bazel will properly print progress messages for every download it executes.

I traced this down to the BwtB downloader code, which enqueues downloads as futures and then... forgets about them until the command shutdown hook waits for their completion without any kind of progress reporting.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Write a `genrule` that produces a multi-GB file.
2. Build the target with `--remote_download_toplevel`.
3. Notice how Bazel pauses after completing the command but before returning control to the user. Monitor network activity and notice the download happening in the background.

### Which operating system are you running Bazel on?

Doesn't matter.

### What is the output of `bazel info release`?

bazel release 6.0.0

**Comment by brentleyjones** [comment]
@coeuvre

**Comment by keertk** [comment]
@bazel-io flag 6.1.0

**Comment by keertk** [comment]
@bazel-io fork 6.1.0
