### ISSUE TITLE
Update java_tools

### ISSUE THREAD

**Issue by cushon** [bazelbuild/bazel#17427]
https://github.com/bazelbuild/bazel/commit/a1a5f3341f2e3052886fee79cffb5c6fcc80c1bd recently added a new flag to singlejar, and the prebuilt in java_tools needs to be updated before the rules can start using the new flag. Would it be possible to get another java_tools release?

cc @kshyanashree @comius @hvadehra

**Comment by kshyanashree** [comment]
@cushon v11.11 is released: https://github.com/bazelbuild/java_tools/releases/tag/java_v11.11
