### ISSUE TITLE
[6.0] accelerated file corruption on macos with Bazel 6.0

### ISSUE THREAD

**Issue by jerrymarino** [bazelbuild/bazel#17428]
### Description of the bug:

After updating to Bazel 6.0 I have observed significant disk cache corruption on macOS. A handful of previously working rule outputs started show up in the disk_cache often with size 0 or in a rare case was partially written. The rules work fine without a `disk_cache` and on Bazel 6.0 are working fine under load.

There were no other changes to the rule in question. Further, the rules are scoped to `no-remote`.

I wrote _accelerated_ in the title because after further investigation I have reason to believe it might have happened on 5.3.2 to the same rules.

### Which operating system are you running Bazel on?

macOS 12.5.2

### What is the output of `bazel info release`?

6.0.0

### Bazel 6.0 potentially related changes

I noticed that this change was added in Bazel 6.0  
https://github.com/bazelbuild/bazel/commits/9cb5e0a31665d3b3f25bf58ec2dee696e828d8b9

What isn't obvious if we should to start calling `fsync` in our Bazel rules prior to closing as well, or there is some other race condition at play here that led to this being cherry picked cc @artem-zinnatullin 

Filing this for posterity or if anyone else has a suggestion

**Comment by coeuvre** [comment]
I know it's probably hard, but can you please provide a minimal repro that can trigger this corruption?

**Comment by coeuvre** [comment]
BTW, what file system are you using?

**Comment by coeuvre** [comment]
Did you see any errors in the logs related to the disk cache?

**Comment by jerrymarino** [comment]
> I know it's probably hard, but can you please provide a minimal repro that can trigger this corruption?
If I can get one I'll post it up 

> BTW, what file system are you using?

This is running on the macOS 12.5.2 default APFS in the most vanilla device configuration:
```
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *1.0 TB     disk0
   1:                        EFI ⁨EFI⁩                     314.6 MB   disk0s1
   2:                 Apple_APFS ⁨Container disk1⁩         1.0 TB     disk0s2

/dev/disk1 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +1.0 TB     disk1
                                 Physical Store disk0s2
   1:                APFS Volume ⁨Preboot⁩                 297.9 MB   disk1s2
   2:                APFS Volume ⁨Recovery⁩                1.7 GB     disk1s3
   3:                APFS Volume ⁨VM⁩                      1.1 GB     disk1s4
``` 

> Did you see any errors in the logs related to the disk cache?

There's no errors or info on this in the build that caused it or afterwards. The best info I have at this point is very concrete evidence of it _afterwards_ happening:

I've found Bazel to succeeded w/o error but flush ( broken ) transitive dependency AC records into the cache. The AC records in question are 100% required for to the build in question to pass.  A build that lands this same box won't fail until it has a fresh ` `bazel-out` - for instance the build at `Fri Feb  3 07:07:38 2023` passed w/o errors but then future builds failed because that build left a bad AC record in the cache 

```
# Bad AC record a7d0291bef4809f67bee08f3779a9e602245d052d392ac3263c63b0d65ceab81
$ stat -x /cache/cas/a7/a7d0291bef4809f67bee08f3779a9e602245d052d392ac3263c63b0d65ceab81
  File: "/cache/cas/a7/a7d0291bef4809f67bee08f3779a9e602245d052d392ac3263c63b0d65ceab81"
  Size: 165          FileType: Regular File
  Mode: (0644/-rw-r--r--)         Uid: (  501/   build)  Gid: (   20/   staff)
Device: 1,5   Inode: 3650318460    Links: 1
Access: Tue Feb  7 06:29:37 2023
Modify: Fri Feb  3 07:07:38 2023
Change: Fri Feb  3 07:07:38 2023
 Birth: Fri Feb  3 07:07:38 2023
```

**Comment by coeuvre** [comment]
You mentioned build failed, can you share the error message?

**Comment by jerrymarino** [comment]
I see it manifesting as a clang compiler errors in future builds on the same host with a new `bazel-out`, when it pulls the busted AC records from the disk cache e.g. `/cache/cas/a7/a7d0291bef4809f67bee08f3779a9e602245d052d392ac3263c63b0d65ceab81` 

```
[2023-02-06T18:20:12.292Z] # Execution platform: @local_config_platform//:host
[2023-02-06T18:20:12.292Z] Some.m:15:9: fatal error: 'UIImage+Diff.h' file not found
[2023-02-06T18:20:12.292Z] #import "Some+Diff.h"
[2023-02-06T18:20:12.292Z]         ^~~~~~~~~~~~~~~~
````
The file `/cache/cas/a7/a7d0291bef4809f67bee08f3779a9e602245d052d392ac3263c63b0d65ceab81` was a "header map" intermediate provided into the compile that'd map the import `"Some+Diff.h"` to it's path on disk. Clang fails when you give it a null `.hmap`.

I don't see any errors or exceptions pertaining to a disk cache. This said, I'm wondering if these are either being swallowed somehow. I also wonder if the disk cache client somehow regressed e.g. does forcing [fsync](https://github.com/bazelbuild/bazel/commit/9cb5e0a31665d3b3f25bf58ec2dee696e828d8b9#diff-6a12ac95951e6ab46724aae184daa3f414763f43f93163c6e91c8da01ea1d241R185) really exasturbate an existing race? I'm going to try to run the disk cache from Bazel 5.0 and see if it fixes it.

**Comment by coeuvre** [comment]
It seems that disk cache didn't verify the content of the blob when retrieving it from CAS. Did you set `--remote_verify_downloads` to `false`? If so, can you set the flag to `true` and see if there is any error printed out?

**Comment by jerrymarino** [comment]
Yeah that was my thought as well, but I don’t think checking is enabled for a disk cache in this scenario 👀

Do you have any background on why these 2 changes ( BWOB checking, fsync change ) were added to the disk cache in Bazel 6 ? Both of those look related and the former checking looks like it’d reject bad disk cache entire..

**Comment by jerrymarino** [comment]
We certainly don’t disable it

**Comment by jerrymarino** [comment]
We certainly don’t disable checking

**Comment by coeuvre** [comment]
I looked at your linked PR https://github.com/bazel-ios/rules_ios/pull/652 and combine with the error message you provided above, here is my thought:

1. You enabled the `--remote_verify_downloads`, Bazel will verify the content of entries in CAS when downloading them to make sure it matches the digest. Since there is no error message regarding to the mismatch, I assume the content in the CAS matches the digest. (Can you also calculate the sha256 digest of the corruption file and check whether it matches the filename?)
2. The action that generates hmap [didn't check](https://github.com/bazel-ios/rules_ios/pull/652/files#diff-22832e485949e22278c3af6640a76d9fcc4a2f2f5f770c49259cb60630ca189bL200) the return value of `close(fd)`. It is possible that the action failed to close the file, leaving the file in the wrong state, and exited normally. Bazel sees the corrupted file and save it into disk cache.
3. The downstream action sees the corrupted input either from just executed action or disk cache, reports the error you provided above.

This doesn't explain why you didn't see the same error after disabled disk cache though.

However, since the PR, which updates the code to correctly handle the return value of `close`, is merged, can you try with new version the rule can check whether the issue is still reproducible?

**Comment by jerrymarino** [comment]
Thanks for your time digging into this. 

>  It is possible that the action failed to close the file, leaving the file in the wrong state, and exited normally.

I agree will further confirm the rule is to blame of bad cas records ( but acceptable from a caching standpoint ) and will circle back on this thread 

> This doesn't explain why you didn't see the same error after disabled disk cache though.

Basically we reverted back to Bazel 5.0 and builds started passing again with the original version of the rule.

Given all that I suspect this compiler error and corruption that Bazel 6 _has accelerated write failures_ in some way.. The current hmap rule is defective given write failure but it's just surfacing on this update

**Comment by jerrymarino** [comment]
FWIW that rule has been running at scale for a couple year and we hadn't heard about a report from rules_ios users or internally till Bazel 6.0..

**Comment by ivan-golub** [comment]
@jerrymarino @coeuvre we also observed weird cases of fs corruption that might or might not be related to this issues. We observe it on with bazel 6.x and using main ie 7.x. It happens only on apple silicon and affects various repro_rules that are fetched as tar.gz. After inspecting outputs we confirmed that tar.gz files are valid and correct but unarchived versions in external output are corrupted.
For example we saw errors like:
```
[Bazel Compilation Error] external/zlib/inftrees.c:273:17: error: use of undeclared identifier 'left'; did you mean 'eft'?
                left <<= 1;
                ^~~~
                eft
external/zlib/inftrees.c:46:10: note: 'eft' declared here
    int (eft;                   /* number of prefix codes available */
```
or
```
2023-01-17 15:15:03 23:15:03 [0;31m  File "/Users/foo/.cache/bazel/arm64/200c81ba794154ad95d9a76cac3f836f/external/tool_py_3_9_macos_arm64/dist/lib/python3.9/subprocess.py", line 49, in <module>[0m
2023-01-17 15:15:03 23:15:03 [0;31m    import signal[0m
2023-01-17 15:15:03 23:15:03 [0;31m  File "/Users/foo/cache/bazel/arm64/200c81ba794154ad95d9a76cac3f836f/externaltool_py_3_9_macos_arm64/dist/lib/python3.9/signal.py", line 16[0m
2023-01-17 15:15:03 23:15:03 [0;31m    lambda name: na na na('SIG_DFL', 'SIG_IGN'))[0m
2023-01-17 15:15:03 23:15:03 [0;31m                    ^[0m
2023-01-17 15:15:03 23:15:03 [0;31mSyntaxError: invalid syntax[0m
```

**Comment by coeuvre** [comment]
> I agree will further confirm the rule is to blame of bad cas records ( but acceptable from a caching standpoint ) and will circle back on this thread

Thanks for confirming. I have changed the title to reflect that.

**Comment by larsrc-google** [comment]
@ivan-golub We suspect that is a separate issue.

@jerrymarino Are you running your rules in a sandbox? If so, could you run without sandboxing, i.e. `--strategy=YourMnemonic=standalone` and see if it still reproduces? We're trying to rule out various influences here - at least we have remote ruled out, which makes it simpler.

**Comment by coeuvre** [comment]
cc @Wyverald for the issues of external deps in https://github.com/bazelbuild/bazel/issues/17428#issuecomment-1423338695.

**Comment by jerrymarino** [comment]
Sorry for the late reply, we're now working to get 6.0 rolled out again, and it's now looking like more of a reality 👏 

>@jerrymarino Are you running your rules in a sandbox? If so, could you run without sandboxing, i.e. --strategy=YourMnemonic=standalone and see if it still reproduces? We're trying to rule out various influences here - at least we have remote ruled out, which makes it simpler.

Yeah we run these rules 100% with the sandbox already. `HmapCreate` was also set to `no-remote` due to not wanting to remote cache or disk cache it.

After looking more into this, I found the `HmapCreate` in the 6.0 disk cache. That seems to be because in the first cut of 6.0, the feature `incompatible_remote_results_ignore_disk` was set to `true`. That [code implicates](https://github.com/bazelbuild/bazel/blob/d60ce2c7c86393638c77698c00c2168a7a936a53/src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java#L289) this:

```
 313           // If --incompatible_remote_results_ignore_disk is set, we treat the disk cache part as
 314           // local cache. Actions which are tagged with `no-remote-cache` can still hit the disk
 315           // cache.
 ```

This also broke RBE on 6.0 for us too, because we set many menmonic of RBE inputs to `no-remote-cache` though they are dependencies of RBE are test actions.  Put otherwise, we have hundreds of GB of local action outputs that we don't want to disk cache, but need inside of our RBE actions and don't want in the disk cache.

Further testing and evidence points to this macOS file system and disk failing under this severe of load. Now that I have a better idea about this change, we can verify in isolated and controlled environment in `5.4.1` .

**Comment by jerrymarino** [comment]
I wonder if this is also the we wanted to start calling `fsync` in the disk cache - e.g. wanting to mitigate macOS file system write errors induced by the severe load:
> I noticed that this change was added in Bazel 6.0
https://github.com/bazelbuild/bazel/commits/9cb5e0a31665d3b3f25bf58ec2dee696e828d8b9
Per that PR message this:
> Fsync before rename after copy in DiskCacheClient
> Debugging `disk_cache` at work, found this TODO in the code, decided to implement.

I'm curious to know if flipping `incompatible_remote_results_ignore_disk=false` back to false fixes the "bug" for others! 🤞

**Comment by ivan-golub** [comment]
small update on my report https://github.com/bazelbuild/bazel/issues/17428#issuecomment-1423338695
we observed this issue on MacOS 12.3 MacStudio CI builders but upgrading to MacOS 13.4 "fixed" the problem, we have not see more corruptions for couple months.

**Comment by jerrymarino** [comment]
@ivan-golub awesome - I'm relieved to hear that 13.4 fixed up some of the write problems 🍎  !

I'm vetting our config with `6.3.0` with `incompatible_remote_results_ignore_disk=false` to see if it clears the flake issues 🤞 . Last week when we tried 6.x.x again we tried again -  we saw it still flake, but on a lower release than 13.4.

**Comment by jerrymarino** [comment]
Last week we replicated the CI in question to run on Bazel 6.0 and confirmed the disk cache issues are resolved by setting `incompatible_remote_results_ignore_disk=false`.

This feature was removed in Bazel 7.0 recently so we'll need some alternate answer to better control the disk cache writes
