### ISSUE TITLE
Windows 10 / MSYS64: CreateFile error upon first (installation) Bazel run

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#1744]
I just deleted `C:\tools\msys64\var\tmp\Bazel\MGAgSgPx` because of https://github.com/bazelbuild/bazel/issues/1743 and ran bazel, and it showed the following error. I've seen this before, so it's not new.

```
$ bazel test //src/test/java/com/google/devtools/build/lib:* --test_arg=com.google.devtools.build.lib.unix.NativePosixFilesTest
ERROR: CreateFile(C:\tools\msys64\var\tmp\Bazel\MGAgSgPx\install): The system cannot find the file specified.
...
```

Fortunately Bazel can continue afterwards, but we should find out what's causing this.

**Comment by petemounce** [comment]
This still happens in 0.3.2

**Comment by petemounce** [comment]
Still happens in 0.4.0-rc3.

**Comment by petemounce** [comment]
Still happens in 0.4.0

**Comment by laszlocsomor** [comment]
The culprit is that the installation directory doesn't exist beforehand.
If I delete the parent of `$(bazel info output_root)` before running bazel, I can see this error, but if I create some of these directories beforehand then I don't.

**Comment by laszlocsomor** [comment]
FYI this won't yet get fixed in 0.4.1 either, sorry.

**Comment by laszlocsomor** [comment]
Fixing this depends on implementing [blaze_util::MakeDirectories](https://github.com/bazelbuild/bazel/blob/8820f10876cbb88bfbcba6ada2ea55167efdcdb9/src/main/cpp/util/file_windows.cc#L354) (`mkdir -p` on Windows).

**Comment by laszlocsomor** [comment]
For the record this doesn't happen with the msys-less version.

**Comment by laszlocsomor** [comment]
I haven't seen this for a long time, even in the msys-ful version.
