### ISSUE TITLE
add a command to output all build directory variable

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/bazel#17446]
### Description of the feature request:

I know bazel has variables about build directory structure, but I don't know how to get it and use it, when I need write some rules, I often need know directory variable name,  like $HOME/.cache/bazel/_bazel_root/{WORKSPACE HASH) etc. current I have to use ../.../../ to get a directory, it's really annoying!!!!!!!!

**Comment by xiedeacc** [comment]
anyway, where can I find a doc about these variables?

**Comment by tjgq** [comment]
You can find some information at https://bazel.build/remote/output-directories.

Why does your rule need to know this, though? That sounds like a [non-hermetic](https://bazel.build/basics/hermeticity) thing to do. If you explain the end goal you're trying to achieve, we might be able to provide better advice.

**Comment by xiedeacc** [comment]
@tjgq https://github.com/bazelbuild/examples/tree/main/make-variables#custom-starlark-defined-variables this is the project exactlly I need
