### ISSUE TITLE
Writing to standard out from a java annotation processor produces incomprehensible error message

### ISSUE THREAD

**Issue by rfevang** [bazelbuild/bazel#17448]
### Description of the bug:

I was trying to reproduce a bug in a minimal test case, and in the process wanted to write things to standard out in an annotation processor. Doing so however makes bazel fail, and not in a way that makes it obvious to a user what is wrong.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

MyAnnotation.java:
```java
public @interface MyAnnotation{}
```

MyProcessor.java:
```java
import javax.annotation.processing.*;
import javax.lang.model.element.*;
import java.util.*;

@SupportedAnnotationTypes(value = "MyAnnotation")
public class MyProcessor extends AbstractProcessor {
  public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment environment) {
    System.out.println("Hello from process()!");    
    return false;
  }
}
```

SomeClass.java:
```java
@MyAnnotation
public class SomeClass {}
```

BUILD.bazel:
```py
java_library(
    name = "my_annotation",
    srcs = ["MyAnnotation.java"],
)

java_plugin(
    name = "my_processor",
    srcs = ["MyProcessor.java"],
    processor_class = "MyProcessor",
)

java_library(
    name = "some_class",
    srcs = ["SomeClass.java"],
    deps = [":my_annotation"],
    plugins = [":my_processor"],
)
```

Executing `bazel build :some_class` results in the following output:
```
$ bazel build :some_class
INFO: Invocation ID: 46d862af-30ac-4995-9810-010bc7dbf16c
INFO: Analyzed target //:some_class (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/fevang/debug/bazel_bug2/BUILD.bazel:12:13: Building libsome_class.jar (1 source file) and running annotation processors (MyProcessor) failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at /home/fevang/.cache/bazel/_bazel_fevang/de94cda180ac28d114c9ec223c526675/bazel-workers/multiplex-worker-12-Javac.log ---8<---8<---
(empty)
---8<---8<--- End of log ---8<---8<---
Target //:some_class failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.682s, Critical Path: 0.63s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

Replacing `System.out` with `System.err` in `MyProcessor.java` makes everything work fine (though the output doesn't show up).

### Which operating system are you running Bazel on?

Ubuntu 22.04.1 LTS

### What is the output of `bazel info release`?

release 6.0.0

### Have you found anything relevant by searching the web?

Possibly https://github.com/bazelbuild/bazel/issues/11948 is related (same issue?) It's the issue that made me think writing to standard out might be the problem.

### Any other information, logs, or outputs that you want to share?

I've seen on a few invocations the processor output (`Hello from process()!`) ends up in the error message instead of `(emtpy)`, though it's been rare.

**Comment by tjgq** [comment]
The Java rules use [persistent workers](https://bazel.build/remote/persistent), which communicate with Bazel via their stdin/stdout using a structured message format.

If you're printing things just for the sake of debugging, try disabling wokers (`--strategy=Javac=standalone`). Then stdout/stderr should work.

**Comment by larsrc-google** [comment]
This problem should be fixed with https://github.com/bazelbuild/bazel/pull/14201, but that didn't make it into the 6.0.0 release. I'll make sure it gets into 6.1.0.

**Comment by rfevang** [comment]
Thanks, building from `last_green` indeed works just fine, I don't know why I didn't try that before submitting this bug report.

It even writing the messages to standard out, very nice!
