### ISSUE TITLE
could add the cammad line "--output_base=xxx" into .bazelrc file ?

### ISSUE THREAD

**Issue by linjunmian** [bazelbuild/bazel#17442]
### Description of the feature request:

current my bazel version is 5.1.1.
when I try to add "--output_base=xxx" into .bazelrc file such as 
`build --output_base=xxx`
it will return the error : `ERROR: --output_base=xxx :: Unrecognized option: --output_base=xxx`
the correct way is use it when run cammnd in bash like `bazel --output_base=xxx build //xxx`
but it's not convenient because i need add --output_base to both "bazel run" and "bazel clean".
if not, bazel clean will clean the default path ("/root/.cache"),and "bazel run" will rebuild in default path "/root/.cache".

So, could you please add this cammad to .bazelrc？

**Comment by tjgq** [comment]
Put `startup --output_base=xxx` in your `.bazelrc`.

**Comment by linjunmian** [comment]
@tjgq thanks
