### ISSUE TITLE
@bazel_tools//tools/java/runfiles:auto_bazel_repository_processor does not compile with JDK 8

### ISSUE THREAD

**Issue by nacl** [bazelbuild/bazel#17458]
### Description of the bug:

Our internal build uses JDK 11 to build code against JDK 8, using the JDK 8 bootclasspath.  When upgrading to Bazel 6, the Java runfiles library fails to compile:

```
external/bazel_tools/tools/java/runfiles/AutoBazelRepositoryProcessor.java:84: error: method iterate in interface Stream<T#2> cannot be applied to given types;
        Stream.iterate(
              ^
  required: T#1,UnaryOperator<T#1>
  found: TypeElement,(element)-[...]ement,Element::g[...]ement
  reason: cannot infer type-variable(s) T#1
    (actual and formal argument lists differ in length)
  where T#1,T#2 are type-variables:
    T#1 extends Object declared in method <T#1>iterate(T#1,UnaryOperator<T#1>)
    T#2 extends Object declared in interface Stream
Target @bazel_tools//tools/java/runfiles:auto_bazel_repository_processor failed to build
```

This appears to be occurring because the three-argument `Stream.iterate` method used here:

https://github.com/bazelbuild/bazel/blob/338bbc02132da7de8681196b6a0afbb6297038aa/tools/java/runfiles/AutoBazelRepositoryProcessor.java#L84-L90 

does not exist in JDK 8, there is only a [two-argument one](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#iterate-T-java.util.function.UnaryOperator-).  It was added in JDK 9 (JDK 11 docs [here](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/Stream.html#iterate(T,java.util.function.Predicate,java.util.function.UnaryOperator)).

A simple enough fix would be to replace this `Stream` call with a `for` loop, which seems to work for me locally.  I can prepare a PR should this be desirable.  My understanding is that while Bazel itself needs JDK 11, Bazel should still be able to compile code for JDK 8, including libraries intended to be loaded by end-users like this one.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Since this only uses the standard library, you can just use `javac` from JDK 8 without invoking Bazel:

```javac tools/java/runfiles/AutoBazelRepositoryProcessor.java```

Reproduced using OpenJDK 11 using the OpenJDK 8 bootclasspath, and OpenJDK 8 itself.

### Which operating system are you running Bazel on?

Linux (Alma 8 aarch64, CentOS 7 amd64)

### What is the output of `bazel info release`?

6.0.0-vmware

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/17281 is in the same area, but does not correspond to this precise issue.

**Comment by fmeum** [comment]
Thanks for the detailed report, I prepared a fix at https://github.com/bazelbuild/bazel/issues/17458 that can be cherry-picked into Bazel 6.1.

**Comment by pete-gillin-privitar** [comment]
I'm seeing this issue with bazel 6.1.2. (It worked in 5.3.2.) Looking at https://github.com/bazelbuild/bazel/commit/420659a9ad2a98f57e057d8c22eb621e3b12803e, it looks like it made it into various `7.0.0-pre.*` builds, but not into any `6.*` build. Is it possible to cherry-pick it?
