### ISSUE TITLE
ctx.actions.declare_directory() - all contents is read-only

### ISSUE THREAD

**Issue by nettle** [bazelbuild/bazel#17468]
### Description of the bug:

When using **ctx.actions.declare_directory()**, any directory contents resulting from a **ctx.actions.run()** (or **ctx.actions.run_shell()**) created as read-only... and remain read-only even after bazel shutdown.

### BUILD:
```py
load(
    "test.bzl",
    "test_declare_directory",
)

test_declare_directory(
    name = "test",
)
```

### test.bzl:
```py
def _declare_directory_impl(ctx):
    test_files = ctx.actions.declare_directory(ctx.label.name + ".files")
    path = test_files.path
    ctx.actions.run_shell(
        outputs = [test_files],
        command = "mkdir -p %s && echo aaa > %s && echo bbb > %s" %
                  (path, path + "/a.txt", path + "/b.txt"),
    )
    return [DefaultInfo(files = depset([test_files]))]


test_declare_directory = rule(
    implementation = _declare_directory_impl,
)
```

### Steps to reproduce:
```bash
bazel build ...
bazel shutdown
# Now try to remove all files in cache
rm -rf $HOME/.cache/bazel
```

### Expected behavior

All files in cache should be removed

### Actual behavior

Files created by **run_shell** under **declare_directory** cannot be removed:
```
rm: cannot remove '/home/user/.cache/bazel/_bazel_user/.../execroot/__main__/bazel-out/k8-fastbuild/bin/test.files/a.txt': Permission denied
rm: cannot remove '/home/user/.cache/bazel/_bazel_user/.../execroot/__main__/bazel-out/k8-fastbuild/bin/test.files/b.txt': Permission denied
```

### Which operating system are you running Bazel on?

Red Hat Enterprise Linux Server release 7.9 (Maipo)

### What is the output of `bazel info release`?

release 6.0.0

### Have you found anything relevant by searching the web?

This problem is similar to #6530

**Comment by tjgq** [comment]
I think this is working as intended, and not exclusive to directories. We make outputs non-writable to mitigate against non-sandboxed local actions accidentally overwriting files other than their declared outputs. There's an `--experimental_writable_outputs` flag to disable it, but I'm not sure if it made it into the 6.0.0 release.

**Comment by comius** [comment]
I also believe this is WAI.

**Comment by comius** [comment]
> JFI: As I know **ctx.actions.declare_directory()** is only function which leaves directory contents as read-only.

I thought all the artifacts are readonly, not just directories.

**Comment by fmeum** [comment]
All artifacts are read-only, but `rm -rf` handles read-only files just fine whereas it gets stuck on read-only directories.
