### ISSUE TITLE
Add command line option to ignore data dependencies at build time

### ISSUE THREAD

**Issue by jrajahalme** [bazelbuild/bazel#17472]
### Description of the feature request:

Add a command line option that causes `bazel build` to ignore data dependencies declared in `cc_test.data`, and make sure these data dependencies are available when running `bazel run` or `bazel test`, if they were ignored at `bazel build` time.

### What underlying problem are you trying to solve with this feature?

Currently bazel fetches data dependencies at build time, so that they are available when the built tests are run. Sometimes it would be beneficial to perform this fetching later, e.g., when in `bazel run` or `bazel test`.

For further detail, see https://github.com/bazelbuild/bazel/issues/15017.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 5.1.1

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
Using bazel release, not git, so not relevant here.
```

### Have you found anything relevant by searching the web?

Yes, a closed issue that requested the behavior of Bazel to be changed: https://github.com/bazelbuild/bazel/issues/15017.

The difference here is that in this issue I'm suggesting a new command line option to achieve the same without changing the default behavior.

**Comment by peakschris** [comment]
@bazelbuild/triage this is still a valid and needed request
