### ISSUE TITLE
test_verbose_timeout_warnings giving strange results

### ISSUE THREAD

**Issue by mightyguava** [bazelbuild/bazel#1748]
I ran the test below with `--runs_per_test=3 --test_verbose_timeout_warnings`.

The test is sized `medium`, which is documented to expect to fall within `30s-300s`. Yet you can see below that it ran in 61.8 seconds, and I'm still getting a warning.

Also, the warning always states that the test ran in 0.0s. This is what it shows for every test, no matter how long it actually took.

```
//tests/java/com/urbancompass/listing:mongo                              PASSED in 61.8s
  Stats over 3 runs: max = 61.8s, min = 61.7s, avg = 61.8s, dev = 0.0s
  WARNING: //tests/java/com/urbancompass/listing:mongo: Test execution time (0.0s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
  WARNING: //tests/java/com/urbancompass/listing:mongo: Test execution time (0.0s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
  WARNING: //tests/java/com/urbancompass/listing:mongo: Test execution time (0.0s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
```

**Comment by laszlocsomor** [comment]
As I understand it, this is the key:
```
(0.0s excluding execution overhead)
```

Looks like your tests finished instantaneously and the 61.8s was just overhead. Could that be the case?

**Comment by mightyguava** [comment]
What does bazel consider overhead? The test suite has 180 test cases, each of which use a Junit @Rule to set up and tear down a real mongo DB database running on localhost.

Even if the mongo setup time was counted as overhead, given the number of tests and that some of the tests are actually a bit slow in code, that should account for at least a 0.1s run time in total?

**Comment by hermione521** [comment]
Friendly ping @laszlocsomor

**Comment by laszlocsomor** [comment]
Hey, sorry about the long silence. I don't know what Bazel considers overhead; I can find it out tomorrow.

**Comment by laszlocsomor** [comment]
@mightyguava : Have you seen this occurring recently? What OS did you run Bazel on? Do you see this happening with other tests too?

**Comment by mightyguava** [comment]
@laszlocsomor I just ran the command again with the `0.3.2` release, on Ubuntu 14.04. Still seeing the same results

```
//tests/java/com/urbancompass/listing:mongo                              PASSED in 71.5s
  Stats over 3 runs: max = 71.5s, min = 71.1s, avg = 71.3s, dev = 0.2s
  WARNING: //tests/java/com/urbancompass/listing:mongo: Test execution time (0.0s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
  WARNING: //tests/java/com/urbancompass/listing:mongo: Test execution time (0.0s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
  WARNING: //tests/java/com/urbancompass/listing:mongo: Test execution time (0.0s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
```

It happens with all of our test targets, whether or not they use mongo. Are you able to reproduce at all?

I wonder if it may have to do with the fact that we auto-generate the test suite with this rule:

```python
"""
Bazel requires the use of JUnit Suite files to define Suites of tests and how
tests should be run within the Suite. In most cases, we don't care to customize
this functionality. This rule automatically generates a dumb suite that just
references all of the *Test.java in the input sources.
"""
def junit_suite_test(name, srcs, deps, size="small", resources=[], resource_strip_prefix=None, classpath_resources=[], jvm_flags=[], tags=[], data=[]):
  tests = []

  if (deps and '//src/java/com/urbancompass/mongo:mongo_test_support' in deps
      and (not tags or 'exclusive' not in tags or 'mongo' not in tags)):
    fail('Tests that use MongoTestDB must be tagged as "exclusive" and "mongo"', 'tags')

  # Convert test source file names to full class references
  package = PACKAGE_NAME \
    .replace("tests/java/", "") \
    .replace("tests/app_startup/", "") \
    .replace("tests/integration/java/", "") \
    .replace("/", ".")
  for src in srcs:
    if src.endswith("Test.java"):
      if "/" in src:
        src = package + "." + src.replace("/", ".")
      tests += [src.replace(".java", ".class")]

  # Generate a JUnit Suite to run all of the tests included.
  suite_class_name = "AllTestsGen" + name.replace("-", "_")
  suite_file = suite_class_name + ".java"

  native.genrule(
    name = name + "-AllTests-gen",
    outs = [suite_file],
    cmd = """
      cat <<EOF >> $@
package %s;
import org.junit.runner.RunWith;
import org.junit.runners.Suite;
@RunWith(Suite.class)
@Suite.SuiteClasses({
  %s
})
public class %s {}
EOF
    """ % (package, ",\n".join(tests), suite_class_name)
  )

  native.java_test(
    name = name,
    srcs = srcs + [suite_file],
    test_class = package + "." + suite_class_name,
    resources = resources,
    resource_strip_prefix = resource_strip_prefix,
    classpath_resources = classpath_resources,
    data = data,
    size = size,
    tags = tags,
    jvm_flags = jvm_flags,
    deps = deps + [
      "//3rdparty:junit",
    ],
```

**Comment by mightyguava** [comment]
I'll spend some time trying to make a github repo for an isolated repro, but I may not be able to get to it for a good while.

**Comment by ulfjack** [comment]
I think it's more likely that our test strategy implementation isn't tracking the time correctly.

**Comment by jwnimmer-tri** [comment]
I have the same problem with a simple `cc_test` rule for a gtest-based unit test with `timeout="moderate"` (or `size="medium"`), so I don't think its Java-only:
```
jwnimmer@call-cc:~/jwnimmer-tri/drake-distro$ bazel clean
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.

jwnimmer@call-cc:~/jwnimmer-tri/drake-distro$ bazel test --test_verbose_timeout_warnings drake/solvers:system_identification_test
INFO: Found 1 test target...
Target //drake/solvers:system_identification_test up-to-date:
  bazel-bin/drake/solvers/system_identification_test
INFO: Elapsed time: 37.082s, Critical Path: 36.16s
//drake/solvers:system_identification_test                               PASSED in 19.2s
  WARNING: //drake/solvers:system_identification_test: Test execution time (0.0s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
Executed 1 out of 1 test: 1 test passes.

jwnimmer@call-cc:~/jwnimmer-tri/drake-distro$ bazel
                                                           [bazel release 0.4.2]
```

Given the fuzzy match, 19s should be okay as "moderate".  The "0.0s" is bogus; the test really does take tens of seconds to run, so I concur with _"I think it's more likely that our test strategy implementation isn't tracking the time correctly"_.

**Comment by ulfjack** [comment]
I checked and StandaloneTestStrategy indeed does not track test process times, so this couldn't possibly work.

**Comment by ulfjack** [comment]
That's not right. It does track the process time (incorrectly), but it doesn't add the time to the result proto, so the analyzer doesn't have it.

**Comment by ulfjack** [comment]
I think I have a fix.

**Comment by ulfjack** [comment]
Confirmed fix works.

**Comment by ulfjack** [comment]
My bad. I didn't realize that Bazel is reading the protos from disk. My change was assuming that the proto is generated by the same version of Bazel, and it broke when it encountered a proto from a previous version. Therefore the rollback.

**Comment by jwnimmer-tri** [comment]
As I understand it, this bug emits a warning for anyone who declares a non-small test.  That ends up confusing my new users on a regular basis.  Is there any re-push of the fix in the works?

If not, perhaps you could elaborate on how to repro the failure mode that led to the rollback, and I will work on a PR?

**Comment by ulfjack** [comment]
I did roll my change forward again with a safeguard to prevent crashes when it sees protos from an old Bazel binary. If you're still seeing incorrect warnings, that's either a regression or a separate issue. Can you describe the symptoms you're seeing?

**Comment by jwnimmer-tri** [comment]
Actually, it's working fine.  My sincere apologies for the complaint!

(I somehow didn't notice in github that this issue was (re-)closed, and took a user report of a warning message at face value.  The user was still using an older version of Bazel.)
