### ISSUE TITLE
WORKSPACE files allow shadowing loads

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/bazel#17480]
### Description of the bug:

This is a valid WORKSPACE file:

```starlark
load("//:one.bzl", "fn")

fn()

load("//:two.bzl", "fn")

fn()
```

The second `fn` binding shadows the first one.

This is confusing, and error-prone. I would argue that this should be rejected by Bazel, requiring one of the loads to be renamed.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```console
% cat >WORKSPACE <<EOF
load("//:one.bzl", "fn")

fn()

load("//:two.bzl", "fn")

fn()
EOF
% cat >one.bzl <<EOF
def fn():
    print("Hello from one")
EOF
% cat >two.bzl <<EOF
def fn():
    print("Hello from two")
EOF
% touch BUILD.bazel
% bazel query ...            
Starting local Bazel server and connecting to it...
DEBUG: /tmp/bazelplay/one.bzl:2:10: Hello from one
DEBUG: /tmp/bazelplay/two.bzl:2:10: Hello from two
INFO: Empty results
Loading: 1 packages loaded
```

### What is the output of `bazel info release`?

release 6.0.0

**Comment by Wyverald** [comment]
At this point it's very unlikely that we'll spend any energy fixing WORKSPACE bugs; all cycles are devoted to Bzlmod instead. So I'll go ahead and close this, even though it's a very valid bug report.
