### ISSUE TITLE
inconsistent error with different accepted load syntaxes

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#1749]
If I use the following:

``` python
load("/local_tools/deploy_tools/deploy", "deploy_zip_impl")
```

inside a skylark bzl file (to load a this function for reuse), it works fine, and gives no errors or warnings.

If I then export the current rule as a remote repository, I get quite cryptically:

```
st-oscar1:hydra oscar$ bazel build src/...
ERROR: package contains errors: src/scala/com/stripe/hydra/job.
ERROR: error loading package 'src/scala/com/stripe/hydra/job': Every .bzl file must have a corresponding package, but 'lo
cal_tools/deploy_tools' does not have one. Please create a BUILD file in the same or any parent directory. Note that this
 BUILD file does not need to do anything except exist.
INFO: Elapsed time: 0.052s
```

Note, in this repo (hydra in the above example), we don't have any path like `local_tools/deploy_tools`. So, error number 1 is:

Error messages with files are not clearly localized to the correct remote repository.

I can fix all of this by in the remote repository using the syntax:

``` python
load("//local_tools/deploy_tools:deploy.bzl", "deploy_zip_impl")
```

So error number 2 is:

We should get warnings or errors on load syntax that is not compatible when used as a remote repository.

**Comment by laurentlb** [comment]
The old syntax has been removed. I believe this bug is obsolete.
Please reopen if not.
