### ISSUE TITLE
source filenames containing colons

### ISSUE THREAD

**Issue by nickbreen** [bazelbuild/bazel#17509]
### Description of the bug:

Bazel cannot process source files with filenames that contain colons.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
touch "foo:bar.baz"
touch WORKSPACE
tee BUILD <<EOF
genrule(
	name = "colons",
	srcs = glob(["*.bar"]) # or literally, which cannot be differentiated from a label ["foo:bar.baz"],
	outs = ["colons.txt"],
	cmd = """find > $@""",
)
EOF

bazel build //:colons
```

Error:
```
BUILD:1:8: //:colons: invalid label 'foo:bar.baz' in element 0 of attribute 'srcs' in 'genrule' rule: invalid label 'foo:bar.baz': absolute label must begin with '@' or '//'
ERROR: package contains errors: 
ERROR: package contains errors: : //:colons: invalid label 'foo:bar.baz' in element 0 of attribute 'srcs' in 'genrule' rule: invalid label 'foo:bar.baz': absolute label must begin with '@' or '//'
ERROR: Skipping '//...': Error evaluating '//...': error loading package '': Package '' contains errors
```

### Which operating system are you running Bazel on?

Fedora 36

### What is the output of `bazel info release`?

release 6.0.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
N/A
```

### Have you found anything relevant by searching the web?

Possibly a duplicate of this issue #374

**Comment by nickbreen** [comment]
There is apparently a work-around by [Using labels to reference directories](https://bazel.build/concepts/dependencies#data-dependencies).

E.g.

```
genrule(
    name = "foo",
    srcs = ["some/directory/."],   # note the slash-dot suffix.
)
```

**Comment by brandjon** [comment]
This is a limitation of label syntax (see [`LabelValidator.java`](https://github.com/bazelbuild/bazel/blob/22ae3a6d367239bcaad23d0d9eadf6ec7a3518b8/src/main/java/com/google/devtools/build/lib/cmdline/LabelValidator.java#L27-L31)). Extending Labels to support more characters or nearly arbitrary bytes is a long-standing issue; see #374.
