### ISSUE TITLE
[bazel.build] Problem with /docs/configurable-attributes

### ISSUE THREAD

**Issue by saimanohar1999** [bazelbuild/bazel#17510]
### Page link:

https://bazel.build/docs/configurable-attributes

### Problem description (include actual vs expected text, if applicable):

i am trying to build dependencies for arm9 32-bit architecture using bazel i am failed to do this.

### Where do you see this issue? (include link to specific section of the page, if applicable)

unable to give target architecture.

**Comment by sgowroji** [comment]
Hi @saimanohar1999, Could you please provide complete steps to reproduce the above issue with error logs. Thanks!

**Comment by saimanohar1999** [comment]
ERROR: Skipping 'CXX=/home/i63349-lnx/manohar/specegt/buildroot-at91/output/host/bin/arm-linux-gnueabi-g++': no such target '//:CXX=/home/i63349-lnx/manohar/specegt/buildroot-at91/output/host/bin/arm-linux-gnueabi-g++': target 'CXX=/home/i63349-lnx/manohar/specegt/buildroot-at91/output/host/bin/arm-linux-gnueabi-g++' not declared in package '' defined by /home/i63349-lnx/manohar/tensorflow_src/BUILD
ERROR: no such target '//:CXX=/home/i63349-lnx/manohar/especegt/buildroot-at91/output/host/bin/arm-linux-gnueabi-g++': target 'CXX=/home/i63349-lnx/manohar/specegt/buildroot-at91/output/host/bin/arm-linux-gnueabi-g++' not declared in package '' defined by /home/i63349-lnx/manohar/tensorflow_src/BUILD
INFO: Elapsed time: 12.604s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)

**Comment by saimanohar1999** [comment]
i am using a embedded system with ARM9 32-bi architecture, i am trying to work on AI application on top of this embedded system. but fortunately i couldnt find any tensorflow dependenies for this architecture. i am trying to build using Bazel tool.

my objective is to get this file "tflite_runtime-2.5.0-cp38-cp38-linux_armv7l.whl" . but i am unable to do that

**Comment by saimanohar1999** [comment]
this file  "tflite_runtime-2.5.0-cp38-cp38-linux_armv7l.whl" is for arm7 architecture i need similar one for ARM9 32-bit.

**Comment by gregestren** [comment]
@saimanohar1999 can you provide a more precise reproduction?
