### ISSUE TITLE
[bazel.build] Problem with /start/android-app

### ISSUE THREAD

**Issue by jbeta51** [bazelbuild/bazel#17516]
### Page link:

https://bazel.build/start/android-app

### Problem description (include actual vs expected text, if applicable):

In the Optional section under "Integrating the SDK" there are instructions for how to set up the NDK that have links that don't work with the instructions provided.

It says to download the latest NDK at this [link](https://developer.android.com/ndk/downloads/index.html) , then to add `android_ndk_repository(name = "androidndk")` to the WORKSPACE. However, this rule is not compatible with the NDK found at the link. This is specified in the documentation for the rule [here](https://bazel.build/reference/be/android#android_ndk_repository).

The solution is to either link to a [specific version](https://github.com/android/ndk/wiki/Unsupported-Downloads) of the Android NDK that is compatible with the native `android_ndk_repository` rule, and/or to include a note about the NDK versions similar to one found in the rule's documentation.

### Where do you see this issue? (include link to specific section of the page, if applicable)

https://bazel.build/start/android-app#integrate_with_the_android_sdk

**Comment by keertk** [comment]
Hi @jbeta51 thanks for reporting this! Are you open to submitting a PR with your proposed changes?
