### ISSUE TITLE
Bash Process Substitution is Broken

### ISSUE THREAD

**Issue by aryeh-looker** [bazelbuild/bazel#17532]
### Description of the bug:

[Process substitution](https://en.wikipedia.org/wiki/Process_substitution) is broken

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```bash
export __STARLARK_EXPR="
format(_):
  return ''
"

bazel cquery "deps(//:all)" \
  --output=starlark \
  --starlark:file=<(echo "$__STARLARK_EXPR")
```

Result:

```bash
INFO: Analyzed target //:all (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: Error doing post analysis query: invalid --starlark:file: failed to read /proc/self/fd/11
INFO: Elapsed time: 0.160s, Critical Path: 0.00s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

### Which operating system are you running Bazel on?

debian

### What is the output of `bazel info release`?

`release 6.0.0`

### Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

* an explanation of process substitution https://en.wikipedia.org/wiki/Process_substitution
* an example of using `--starlark:file=`https://bazel.build/query/cquery#output-format-definition-examples

**Comment by aryeh-looker** [comment]
Closing -- I am in error here.

**Comment by aryeh-looker** [comment]
Another example:

```
 % export __STARLARK_EXPR="
format(_):
  return ''
"

bazel cquery "deps(//:all)" \
  --output=starlark \
  --starlark:file=<(echo $__STARLARK_EXPR)  
INFO: Analyzed 0 targets (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
ERROR: Error doing post analysis query: invalid --starlark:file: file does not define 'format'
INFO: Elapsed time: 0.059s, Critical Path: 0.00s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by fmeum** [comment]
@aryeh-looker you are missing the `def` in front of `format`.

**Comment by aryeh-looker** [comment]
Thank you @fmeum! Closing.
