### ISSUE TITLE
java_tools not upgraded in rules_java cause Bazel with bzlmod failure

### ISSUE THREAD

**Issue by comius** [bazelbuild/bazel#17550]
### Description of the bug:

Downstream breakage:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2875#0186774e-9230-4242-98c3-13779fc6464e

Error:
```
singlejar_local: Bad command line argument --build_target
```

What happened:
1. The --build_target was introduced in singlejar_local in https://github.com/bazelbuild/bazel/commit/a1a5f3341f2e3052886fee79cffb5c6fcc80c1bd
2. java_tools was released in https://github.com/bazelbuild/bazel/commit/79fc488c26e974e384209ae9ffcd028075f01788
3. --built_target gets used in https://github.com/bazelbuild/bazel/commit/cc4af3e929eb37ad58c0437ed9ddcc3933171640

This broke downstream Bazel with bzlmod. (This is building bazel twice, once with old version and once with new one).

- bzlmod uses rules_java to obtain java_tools
- java_tools version wasn't updated in the rules_java
- rules_java wasn't released and updated in Bazel

**Comment by comius** [comment]
cc @cushon @hvadehra @meteorcloudy @Wyverald @kshyanashree

**Comment by meteorcloudy** [comment]
Sounds like we should 

- Update java_tools version in [rules_java](https://github.com/bazelbuild/rules_java/blob/f2c17c5cfcff5f0c2592e822d70cb09a97d8f32e/java/repositories.bzl#L22)
- Have a new rules_java release and submit it to the BCR.
- Update [MODULE.tools](https://github.com/bazelbuild/bazel/blob/d55029f6665a38a9972622f157e3d75a5b28f0f6/src/MODULE.tools#L4) and Bazel's [MODULE.bazel](https://github.com/bazelbuild/bazel/blob/master/MODULE.bazel#L19) file to use the new rules_java version.
