### ISSUE TITLE
Java Tutorial: Incorrect JAVA_HOME instructions?

### ISSUE THREAD

**Issue by Hanse00** [bazelbuild/bazel#17560]
### Page link:

https://bazel.build/start/java

### Problem description (include actual vs expected text, if applicable):

The tutorial for building a Java project includes instructions on setting the `JAVA_HOME` environment variable. For Linux/macOS those instructions say to execute: `export JAVA_HOME="$(dirname $(dirname $(realpath $(which javac))))"`, however unless I am missing something, those instructions are not accurate.

On my device (With javac located at `/usr/bin/javac`) the command evaluates to `/usr`:
```
> export JAVA_HOME="$(dirname $(dirname $(realpath $(which javac))))"
> echo $JAVA_HOME
/usr
```

I believe the appropriate command would be: `export JAVA_HOME="$(realpath $(which javac))"`, which would evaluate as follows:
```
> export JAVA_HOME="$(realpath $(which javac))"
> echo $JAVA_HOME
/usr/bin/javac
```

### Where do you see this issue? (include link to specific section of the page, if applicable)

https://bazel.build/start/java#install_the_jdk

**Comment by cushon** [comment]
The suggested replacement of `$(realpath $(which javac))` is not correct. `JAVA_HOME` needs to be the path to a directory containing a JDK, i.e. `./bin/javac` should be a valid relative path in that directory.

I agree the tutorial could be improved, and that the `$(dirname $(dirname $(realpath $(which javac))))` approach isn't correct if the `javac` on the path is in `/usr/bin/javac`.

**Comment by Hanse00** [comment]
My bad, you're totally right @cushon, for some reason I was thinking JAVA_HOME should be the path to the Java executable. 

Given that the requirement is for `$JAVA_HOME/bin/javac` to be a valid path, then if the executable is located at `/usr/bin/javac`, `/usr` is actually a valid value for `$JAVA_HOME`.

In which case, this change can be undone. My apologies.

**Comment by sgowroji** [comment]
Thanks for the update. I will revert the changes!
