### ISSUE TITLE
Stamping is broken in genrule.

### ISSUE THREAD

**Issue by AmandaCameron** [bazelbuild/bazel#1758]
According to https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/genrule/BazelGenRuleRule.java#L188 the stamping is currently broken in genrule, which is making it somewhat annoying to be able to generate reliable SCM info into my go binaries, which I'd like to be able to do via generation of a .go file using the genrule rule.

**Comment by laszlocsomor** [comment]
That comment may be outdated. Stamping works, though the information is just the timestamp:

```
$ cat foo/BUILD
genrule(
    name = 'x',
    stamp = 1,
    outs = ['hello'],
    cmd = 'cat bazel-out/volatile-status.txt > $@',
)

$ date +%s ; bazel build //foo:x >&/dev/null && cat bazel-genfiles/foo/hello
1474351681
BUILD_TIMESTAMP 1474351681532
```

**Comment by AmandaCameron** [comment]
@laszlocsomor In my case, I'm using it to try and stamp git repo info in, and it seems the new volitile-status is being generated properly, however it's not causing a rebuild of the genrule to generate the source code file, which would ultimately cause the go_library to be rebuilt. However, I guess this may be "Working as intended" since the .git stuff is out of scope of bazel?

**Comment by laszlocsomor** [comment]
@AmandaCameron I see, and I'm seeing the same results: the `volatile-status.txt` is updated in every build, yet the `genrule` isn't rebuilt.

Summoning @lberki : do you know how stamping ought to work? Is this case WIP?
I tried using `--workspace_status_command` (which is in Bazel, it's supported yet undocumented (TODO)), and while the output of the command is neatly written to `volatile-status.txt`, the genrule is only rebuilt (and picks up  the new volatile status) if its inputs or command change.

**Comment by lberki** [comment]
It's actually WAI. The reason why changes to the volatile status file doesn't trigger a rebuild is that then targets with build stamping would always be rebuilt, since at least the time stamp changes on every build (this is the difference between the volatile and the non-volatile status file)

**Comment by laszlocsomor** [comment]
Thanks! How could @AmandaCameron enforce rebuilding the genrule every time then, or at least when the client status changes?

**Comment by lberki** [comment]
That's a good question... I can't think of a way short of deleting the output of the genrule each time a rebuild is needed.

**Comment by laszlocsomor** [comment]
I can think of one sure, but hacky way: add a source file to the genrule that you manually update before each build, so the genrule is always rebuilt, and if its output stays the same, downstream actions will be cache hits. This is of course not an optimal solution, just a workaround.

**Comment by kchodorow** [comment]
You could add a dependency on .git/refs/heads/master (or whatever you need in the .git directory).

**Comment by hanwen** [comment]
@kchodorow - doesn't really work. First, refs are often compressed into another file for efficiency reasons. Second, for gerrit, we use

  git describe --dirty

which in turn depends on all files in the repo.

**Comment by hanwen** [comment]
@lberki  - this is not WAI. We stamp with 

$ git describe --dirty
v2.13-562-g86d94b8-dirty

this value only changes if someone runs a commit. So standard bazel caching would do the right thing for us. Maybe build status support could declare that the keys are stable, by prefixing their keys apprropriately, eg.

  STABLE_BUILD_SCM_STATUS v2.12-blabla

and then sticking the value into bazel-out/stable-status.txt (how are changes to stable-status handled?)

**Comment by hanwen** [comment]
for the latter, we'd basically have to run the action here,

 https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/BazelWorkspaceStatusModule.java#L141

and split the key/value pairs by the key names into stable/unstable, right? Seems like a straightforward change.

**Comment by davido** [comment]
The way we made it work in Buck with `genrule`,
is to execute `git describe` as a part of the command (in place):

```
genrule(
  name = 'gen_version',
  cmd = "v=" + git_describe(path) + ">$OUT",
  out = "version.txt",
)
```

Where git_describe is implemented here: [1]. While `git describe` would be executed each time (and in the right directory), `gen_version` and the ones depend on it, would only be rebuilt, if command has changed from pervious run. But there is no way to execute arbitrary Python code from BUILD file in Bazel.

* [1] https://gerrit.googlesource.com/gerrit/+/master/tools/git.defs

**Comment by lberki** [comment]
@davido : that's unfortunately not possible with Bazel, because you can't execute commands in our equivalent of `git_describe` (as you said).

I have the change out for external review that was proposed by @hanwen .

**Comment by hanwen** [comment]
wow, that was quick! thanks for first class customer service :)

**Comment by promiseofcake** [comment]
@hanwen, how does one take advantage of the patch? I am still seeing the reported behavior where genrules are not rebuild based upon changes in the volatile-status.txt file.

**Comment by laszlocsomor** [comment]
@promiseofcake : 
> I am still seeing the reported behavior where genrules are not rebuild based upon changes in the volatile-status.txt file.

*That* is working as intended -- see `volatile-status.txt` and `stable-status.txt` semantics here: https://stackoverflow.com/questions/47622645/how-to-run-a-shell-command-at-analysis-time-in-bazel/47630130#47630130
