### ISSUE TITLE
new java_tools release required to fix @remote_java_tools on Windows

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#17618]
Compiling `@remote_java_tools//:ijar_cc_binary` fails on Windows since 9f2c62aa489394ae882e07fb97eefb0556075944:
```
undeclared inclusion(s) in rule '@remote_java_tools//:ijar_cc_binary':
this rule is missing dependency declarations for the following files included by 'java_tools/ijar/classfile.cc':
  'external/bazel_tools/third_party/ijar/common.h'
```
9f2c62aa489394ae882e07fb97eefb0556075944 includes a workaround for this in `third_party/jdk/BUILD.java_tools` but there needs to be a new java_tools release to pick this `BUILD` file fix up.

**Comment by kshyanashree** [comment]
@benjaminp v11.12 is released: https://github.com/bazelbuild/java_tools/releases/tag/java_v11.12
