### ISSUE TITLE
Build warning spam on platforms with _FORTIFY_SOURCE enabled by default

### ISSUE THREAD

**Issue by pefoley2** [bazelbuild/bazel#1762]
When building bazel on a gentoo system, where the system compiler enables _FORTIFY_SOURCE by default, the screen is filled with the below warning for many files:
____From Compiling src/test/cpp/util/file_test.cc:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/x86_64-pc-linux-gnu/bits/os_defines.h:39:0,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/x86_64-pc-linux-gnu/bits/c++config.h:482,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/string:38,
                 from ./src/main/cpp/util/file.h:17,
                 from src/test/cpp/util/file_test.cc:14:
/usr/include/features.h:331:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^

It might make sense to either specify -U_FORTIFY_SOURCE or -O in the default c++ build flags.

**Comment by agl** [comment]
Additionally, if `-Werror` is enabled then this stops the build.

**Comment by maomaocode** [comment]
system information in the issue that jart referred is

OS:CentOS 7
GCC: gcc 4.8.5
Python: python3.5
Tensorflow version: TensorFlow 1.1.0-rc1
Bazel: version 0.4.5
CUDA: CUDA 8.0 with GTX 1080 GPU

**Comment by aiuto** [comment]
Closing this for staleness. If it is still a problem with current tensorflow and bazel, please start a new issue or ping to reopen this one.
