### ISSUE TITLE
[Mirror] zig sdk 0.11.0-dev.1796+c9e02d3e6

### ISSUE THREAD

**Issue by motiejus** [bazelbuild/bazel#17635]
### Please list the URLs of the archives you'd like to mirror:

https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.1796+c9e02d3e6.tar.xz
https://ziglang.org/builds/zig-linux-aarch64-0.11.0-dev.1796+c9e02d3e6.tar.xz
https://ziglang.org/builds/zig-macos-x86_64-0.11.0-dev.1796+c9e02d3e6.tar.xz
https://ziglang.org/builds/zig-macos-aarch64-0.11.0-dev.1796+c9e02d3e6.tar.xz
https://ziglang.org/builds/zig-windows-x86_64-0.11.0-dev.1796+c9e02d3e6.zip
https://ziglang.org/builds/zig-windows-aarch64-0.11.0-dev.1796+c9e02d3e6.zip

**Comment by motiejus** [comment]
This is for bazel-zig-cc, suggested by @linzhp .

**Comment by sgowroji** [comment]
Please find the below mirror artifacts
1. https://mirror.bazel.build/ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.1796+c9e02d3e6.tar.xz
2.https://mirror.bazel.build/ziglang.org/builds/zig-linux-aarch64-0.11.0-dev.1796+c9e02d3e6.tar.xz
3.https://mirror.bazel.build/ziglang.org/builds/zig-macos-x86_64-0.11.0-dev.1796+c9e02d3e6.tar.xz
4.https://mirror.bazel.build/ziglang.org/builds/zig-macos-aarch64-0.11.0-dev.1796+c9e02d3e6.tar.xz
5.https://mirror.bazel.build/ziglang.org/builds/zig-windows-x86_64-0.11.0-dev.1796+c9e02d3e6.zip
6. https://mirror.bazel.build/ziglang.org/builds/zig-windows-aarch64-0.11.0-dev.1796+c9e02d3e6.zip
