### ISSUE TITLE
bazel clean --partial: Unrecognized option: --partial

### ISSUE THREAD

**Issue by ahyangyi** [bazelbuild/bazel#1763]
Is this a new option which will be available in the new release? It's in the online documentation at https://www.bazel.io/versions/master/docs/output_directories.html but it's not available in Bazel 0.3.1.

**Comment by dslomov** [comment]
I don't think we have `--partial` anymore

**Comment by laszlocsomor** [comment]
Indeed, that's an ancient flag that is long gone. I'll update the docs.

**Comment by alvaromorales** [comment]
Has the feature been removed? Is there a new way to clean configuration-specific `outputDir`s?

**Comment by laszlocsomor** [comment]
You can simply delete the `bazel-*` symlink's target.
