### ISSUE TITLE
Allow `repository_rules` to be unconditionally run on every Bazel invocation.

### ISSUE THREAD

**Issue by blorente** [bazelbuild/bazel#17640]
### Description of the feature request:

Currently, one cannot configure a `repository_rule` to always run on every Bazel invocation.
The closest thing is the `local` flag, but as per [the documentation](https://bazel.build/extending/repo), that still does some dependency tracking.

Another alternative would be to use `stable_status.txt`, but as far as I know there is no way to consume it as an input of a repository rule.

### What underlying problem are you trying to solve with this feature?

We're trying to track the Xcode installation you're using, for internal reasons. Basically, the output of `xcode-select --print-path`.

We can define this as configuration that:
- Lives in the user's local machine, in an unknown location (the path is actually an indicator of whether the configuration has changed).
- Is quick and easy to read, or at least to check if we should read, from a repository rule.
- Can change between Bazel runs, for reasons unknown to Bazel (essentially, changing another config file somewhere else in the system that could also be in several locations).
- We (the team providing Bazel to users) have no control over.

We need to generate some targets depending on that configuration, and to do that correctly we need to track changes to that configuration.

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

Tested with `6.0.0` and the latest `7.0.0-pre.20230215.2`

### Have you found anything relevant by searching the web?

Only a couple of stackoverflow questions with workarounds for the issue:
- https://stackoverflow.com/questions/61955644/is-there-a-way-to-execute-a-repository-rule-with-local-true-on-every-bazel-invoc
- https://stackoverflow.com/questions/65188605/bazel-repository-rule-not-getting-executed

**Comment by benjaminp** [comment]
https://github.com/bazelbuild/bazel/issues/3041

**Comment by blorente** [comment]
Closed as duplicate of #3041
