### ISSUE TITLE
Add an `implementation_deps` field to `objc_library`

### ISSUE THREAD

**Issue by xiemotongye** [bazelbuild/bazel#17646]
### Description of the feature request:

`objc_library` treats all dependencies and transitive dependencies as public to its consumers. This results in include directories, headers exploding in volume when you have a complex dependency tree. When a header file of the downstream module changes, it break all of the cache of upstream modules.

`swift_library` has a `private_deps` field. `cc_library` has an `implementation_deps` field. Only `objc_library` doesn't have one. `objc_library` should behave as much like `cc_library` as possible. It could support an `implementation_deps` field. Any targets here would be considered the same as deps for compilation purposes, however when computing the final CcInfo provider, hdrs, textual_hdrs, and includes would not be included (obviously the linking context would still be included to properly pick up transitive .a/.so/etc). This would make it easy to control dependency explosion and better hide unfortunately-named files in dependencies.

### What underlying problem are you trying to solve with this feature?

We use bazel to organize & build our iOS project. This project have a complex dependency tree. When a header file of the downstream module changes, it break the cache of upstream modules. If implementation_deps is supported to objc_library, it make us easy to control dependency explosion and cut down lots of time for compilation.

### Which operating system are you running Bazel on?

macOS 12.6

### What is the output of `bazel info release`?

release 6.0.0

### Have you found anything relevant by searching the web?

similar feature request for `cc_library`: https://github.com/bazelbuild/bazel/issues/13000

**Comment by keith** [comment]
https://github.com/bazelbuild/bazel/pull/17962
