### ISSUE TITLE
Deprecate `runtime_deps` rule attribute from `objc_library`

### ISSUE THREAD

**Issue by stravinskii** [bazelbuild/bazel#17643]
### Description of the feature request:

Currently, the Objective-C library rule provides the [`runtime_deps`](https://bazel.build/reference/be/objective-c#objc_library.runtime_deps) rule attribute as means to propagate Apple frameworks (eg. [`ios_dynamic_framework`](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-ios.md#ios_dynamic_framework)) up the dependency graph, and include those framework bundles on top-level Apple rules (e.g. [`ios_application`](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-ios.md#ios_application)), but does not link against that framework (ie. framework will be loaded at runtime using [`NSBundle`](https://developer.apple.com/documentation/foundation/nsbundle)).

To move forward with a more agnostic Objective-C rule, the `runtime_deps` attribute will be deprecated from the `objc_library` rule, and usages of `runtime_deps` should migrate to use `data` instead to propagate Apple frameworks (support was added at [f711be0](https://github.com/bazelbuild/rules_apple/commit/f711be0) on the upstream branch).

**Comment by googlewalt** [comment]
@keith FYI.

**Comment by keith** [comment]
Question for you @stravinskii on https://github.com/bazelbuild/rules_apple/commit/7d0ec138654c7009ca3fb00705d130d60ae50ee4#diff-87d742fc0a4603b04747f3070c6070f4cf641ee55b6e1ab46761306e38c719d8

Shouldn't this commit have _added_ `data` to the `_FRAMEWORK_PROVIDERS_ASPECT_ATTRS`? As if you have a dep tree like `objc_library.data (previously runtime_deps) -> ios_framework.frameworks -> ios_framework` you will no longer collect the second ios_framework target, where previously you would? This might not affect you, but in the open source case we added support for watchos_frameworks which is bundled with watchos_extension targets, and in that case we need to pull those frameworks into the extension.
