### ISSUE TITLE
cquery --output=files is not useful for external dependencies

### ISSUE THREAD

**Issue by jscheid-ventana** [bazelbuild/bazel#17658]
### Description of the feature request:

With https://github.com/bazelbuild/bazel/pull/15979 `cquery --output=files` provides a relative path to the output or source file.  The feature request is to make the output as readily usable when the target is from an external dependency.

Bazel 6.0.0

```
% cat WORKSPACE
workspace(name = "com_example")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
% touch BUILD
% bazel cquery --output=files @bazel_tools//tools/build_defs/repo:git.bzl
Starting local Bazel server and connecting to it...
INFO: Analyzed target @bazel_tools//tools/build_defs/repo:git.bzl (1 packages loaded, 1 target configured).
INFO: Found 1 target...
external/bazel_tools/tools/build_defs/repo/git.bzl
INFO: Elapsed time: 3.607s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
```

There is no WORKSPACE-relative "external" directory.

I happen to know that I can currently use `$(bazel info output_path)/..` to get the parent directory to "external", but that's arcane knowledge and isn't directly provided by the cquery feature.

### What underlying problem are you trying to solve with this feature?

Have `cquery --output=files` behave consistently for all files known to bazel.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 6.0.0

### Have you found anything relevant by searching the web?

Linked issues and PRs associated with https://github.com/bazelbuild/bazel/pull/15979

**Comment by fmeum** [comment]
There are pros and cons to emitting relative paths: They are hermetic (don't differ between developer machines), but at the same slightly harder to use (require prefixing with `$(bazel info execution_root)` to be resolvable in general).

@jscheid-ventana What do you think, would prominently documenting the fact that the paths emitted by `--output=files` may have to be (and can always) be resolved relative to `$(bazel info execution_root)` resolve the issue for you?

**Comment by jscheid-ventana** [comment]
> would prominently documenting the fact that the paths emitted by --output=files may have to be (and can always) be resolved relative to $(bazel info execution_root) resolve the issue for you

Yes.  Documentation would help clarify context for usage of output (versus some assumption that the `bazel-out` prefixes are relative to the helper symlinks, etc.) and seems to solve my problem: scripts can use a consistent path base for source, external, and output files.
