### ISSUE TITLE
[bazel.build] Problem with /reference/be/general

### ISSUE THREAD

**Issue by amosStarkware** [bazelbuild/bazel#17653]
### Page link:

https://bazel.build/reference/be/general

### Problem description (include actual vs expected text, if applicable):

The following paragraphs kind of contradict each other:

`Do use $(location) extensively, for outputs, tools and sources. Due to the segregation of output files for different configurations, genrules cannot rely on hard-coded and/or absolute paths.`
(from [here](https://bazel.build/reference/be/general#:~:text=Do%20use%20%24(location)%20extensively%2C%20for%20outputs%2C%20tools%20and%20sources.%20Due%20to%20the%20segregation%20of%20output%20files%20for%20different%20configurations%2C%20genrules%20cannot%20rely%20on%20hard%2Dcoded%20and/or%20absolute%20paths.))

`location: A synonym for either execpath or rootpath, depending on the attribute being expanded. This is legacy pre-Starlark behavior and not recommended unless you really know what it does for a particular rule. See [#2475](https://github.com/bazelbuild/bazel/issues/2475#issuecomment-339318016) for details.`
(from [here](https://bazel.build/reference/be/make-variables#:~:text=location%3A%20A%20synonym%20for%20either%20execpath%20or%20rootpath%2C%20depending%20on%20the%20attribute%20being%20expanded.%20This%20is%20legacy%20pre%2DStarlark%20behavior%20and%20not%20recommended%20unless%20you%20really%20know%20what%20it%20does%20for%20a%20particular%20rule.%20See%20%232475%20for%20details.))

The first paragraph says `Do use $(location) extensively...` , while the second paragraph says `not recommended unless you really know what it does for a particular rule`. So should it be used or should it be avoided?

thanks

**Comment by comius** [comment]
I think the idea a while ago was to clean up use of `location`. However it never happened and `location` used everywhere.

@lberki Do you have more historical insights about this?

**Comment by lberki** [comment]
I don't have more than you do; my best understanding is that `$(location )` used to be exec path, but then some people wanted to also have a function that returns the root-relative path, but the addition of `$(rootpath )` made the name of `$(location )` ambiguous, so we added `$(execpath )` to disambiguate. Then, apparently, forgot to update the documentation.
