### ISSUE TITLE
Inconsistent encoding when running bazel --batch run //foo -- "$arg" on OS X

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1766]
From @aehlig's words:

"Open-sourcing //src/test/shell/integration:run_test showed that the encoding of arguments
for tests is inconsistent in batch mode (works in non batch mode, though).

`bazel run //foo -- "$arg"` and `bazel --batch run //foo -- "$arg"` use a different encoding.

internal ref: b/31448480

**Comment by jmmv** [comment]
Seems like a dup of https://github.com/bazelbuild/bazel/issues/1775, but if it isn't, I don't have enough information to reproduce.
