### ISSUE TITLE
System suspend events should be reported in the BEP

### ISSUE THREAD

**Issue by BalestraPatrick** [bazelbuild/bazel#17667]
### Description of the feature request:

Before Bazel 6 (I think), `build_event_stream.proto` contained a `was_suspended` field in `AnomalyReport` which signals whether or not a build was suspended (machine went to sleep while a build was ongoing). This property was deprecated in [this commit](https://github.com/bazelbuild/bazel/commit/286fb80081db0af43b1f86292ce417c6541d4ad4) and the replacement structure was never exposed in the BES.

### What underlying problem are you trying to solve with this feature?

It would be nice if this information was exposed again in the BES. We see quite often a BES for a build that took 3 hours, but when we inspect the profile, we can see that the build completed in less than 5 minutes. This is because somehow the timestamps used to compute how long a build where end up being a bit off due to the fact that the computer was put to sleep.

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

6.1.0rc3

**Comment by haxorz** [comment]
> This property was deprecated in [this commit](https://github.com/bazelbuild/bazel/commit/286fb80081db0af43b1f86292ce417c6541d4ad4) and the replacement structure was never exposed in the BES... It would be nice if this information was exposed again in the BES.

@dmaclach, did you already have a plan for reexposing this information, or a final decision on why you're not going to do so?

**Comment by haxorz** [comment]
I picked `P4` because `team-Core` has no plans to make any changes here. If @dmaclach has plans, I defer to those.

**Comment by dmaclach** [comment]
Apologies. Let me take a look.
