### ISSUE TITLE
Uninformative error message with invalid `select` key

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#17689]
### Description of the bug:

The error message Bazel displays when a target uses an invalid `select` key is very uninformative. In particular, it doesn't tell you *where* the offending usage occurs.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```sh
touch WORKSPACE
echo 'java_library(name="a", deps=["//b"])' > BUILD
mkdir b
echo 'java_library(name="b", deps=select({"//c": []}))' > b/BUILD
```

When you run `bazel build :a`, you get the following error message (and nothing else):

```
ERROR: Analysis of target '//:a' failed; build aborted: no such package 'c': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /Users/wyv/test/another-test/c
```

It doesn't tell you that `//c` is being referred to from the file `b/BUILD`. If `:a` has lots of deps, it's nigh impossible to figure out what's wrong.

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 6.1.0

**Comment by Wyverald** [comment]
cc @katre

**Comment by Wyverald** [comment]
For the record, to figure out what was wrong initially, I had to build my own Bazel and insert a line in `PackageValue#key` to crash immediately when the requested package identifier is `//c` o,o

**Comment by gregestren** [comment]
We have a long history of analysis errors not always propagating cleanly. I can't tell offhand if this is specifically about `select()` or the broader analysis error issue.

Either way, good point. Agreed on the bad messaging.
