### ISSUE TITLE
ASan link order error with Bazel 6.1.0 and non-Xcode toolchain

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#17686]
### Description of the bug:

Since https://github.com/bazelbuild/bazel/commit/0f9912ba8a6780a124478fd3ff4fb91b64dbae53, which is included in Bazel 6.1.0 but not 6.0.0, ASan builds that don't use the Xcode toolchain fail at runtime with:

```
==38681==ERROR: Interceptors are not working. This may be because AddressSanitizer is loaded too late (e.g. via dlopen). Please launch the executable with:
DYLD_INSERT_LIBRARIES=/opt/homebrew/Cellar/llvm/15.0.2/lib/clang/15.0.2/lib/darwin/libclang_rt.asan_osx_dynamic.dylib
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
git clone https://github.com/CodeIntelligenceTesting/cifuzz
cd cifuzz
git checkout 3dad1be36cfbd05a4b245e46cf8fe42cb6f3730e
cd examples/bazel
USE_BAZEL_VERSION=0f9912ba8a6780a124478fd3ff4fb91b64dbae53 bazelisk run --repo_env=CC=clang --repo_env=CXX=clang++ --repo_env=BAZEL_USE_CPP_ONLY_TOOLCHAIN=1 --copt -g --compilation_mode=opt --copt -Og --copt -UNDEBUG --copt -U_FORTIFY_SOURCE --@rules_fuzzing//fuzzing:cc_engine=@rules_fuzzing//fuzzing/engines:libfuzzer --@rules_fuzzing//fuzzing:cc_engine_instrumentation=libfuzzer --@rules_fuzzing//fuzzing:cc_engine_sanitizer=asan --@rules_fuzzing//fuzzing:cc_engine_sanitizer=ubsan --@cifuzz//:__internal_has_libfuzzer --verbose_failures //src:explore_me_fuzz_test_bin
```

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

6.1.0

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by meteorcloudy** [comment]
Looks like https://github.com/bazelbuild/bazel/commit/0f9912ba8a6780a124478fd3ff4fb91b64dbae53 is a regression, we probably should do a patch release. /cc @keith @brentleyjones @buildbreaker2021

**Comment by keith** [comment]
@meteorcloudy lets just revert out of 6.x (personally I didn't care if it was in there at all), and then try to do some fix at HEAD

**Comment by meteorcloudy** [comment]
Sounds fine, but 6.1.1 can definitely go out much faster than 6.2, so let's do a patch release.

**Comment by keith** [comment]
Also note I'm trusting the report here since I don't know off hand why this would cause this issue

**Comment by fmeum** [comment]
I also don't know why this flag would break us and definitely don't understand it well enough to even risk a guess. Our example is very simple and works as expected on Linux (clang) and Windows (MSVC and clang-cl), so I leaned towards "blaming" the change that added the toolchain flag.

**Comment by meteorcloudy** [comment]
@fmeum Can you confirm reverting that change in 6.1 fixes the regression?

**Comment by fmeum** [comment]
@meteorcloudy Yes, I can confirm that it does.

**Comment by keith** [comment]
after looking into this a bit with fabian i think it's on the consumer side, but we can revert for 6.x still and let folks fix in 7.x instead

**Comment by keertk** [comment]
Reverted in 6.1.1 - https://github.com/bazelbuild/bazel/pull/17696

**Comment by keertk** [comment]
@bazel-io fork 6.2.0
