### ISSUE TITLE
Release 6.2.0 - May 2023

### ISSUE THREAD

**Issue by kshyanashree** [bazelbuild/bazel#17695]
# Status of Bazel 6.2.0

-   First release candidate date: 2023-04-24
-   Expected release date: 2023-05-09
-   [List of release blockers](https://github.com/bazelbuild/bazel/milestone/48)

To report a release-blocking bug, please add a comment with the text `@bazel-io flag` to the issue. A release manager will triage it and add it to the milestone.

To cherry-pick a mainline commit into 6.2.0, simply send a PR against the `release-6.2.0` branch. 

Task list:
-   [x] [Create draft release announcement](https://docs.google.com/document/d/1pu2ARPweOCTxPsRR8snoDtkC9R51XWRyBXeiC6Ql5so/edit?usp=sharing)
-   [x] Send for review the release announcement
-   [ ] Push the release, notify package maintainers
-   [ ] Update the documentation
-   [ ] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by wondfor** [comment]
> # Status of Bazel 6.2.0
> * Expected release date: 2020-06-01

date is error

**Comment by keertk** [comment]
Thanks for calling this out, @wonfor. Fixed.

**Comment by meteorcloudy** [comment]
So far, we have already merged numerous cherry-picks for Bazel 6.2.0 release. In order to expedite the delivery of these new features and bug fixes to Bazel users, we have decided to reduce the minor release cycle from once every three months to once every two months. Consequently, the new expected release date for version 6.2.0 is now set for May 3, 2023.

**Comment by keertk** [comment]
6.2.0rc1 is now available.
You can download it from https://releases.bazel.build/6.2.0/rc1/index.html.

Please report regressions to https://github.com/bazelbuild/bazel/issues as soon as possible.

**Comment by keertk** [comment]
6.2.0rc2 is now available: https://releases.bazel.build/6.2.0/rc2/index.html.
Please report regressions as soon as possible.

**Comment by keertk** [comment]
6.2.0 is out:
- https://github.com/bazelbuild/bazel/releases/tag/6.2.0
- https://releases.bazel.build/6.2.0/release/index.html

cc @excitoon @vbatts for updating Scoop and Fedora packages. Thanks.
