### ISSUE TITLE
cc_library linkopts tries to expand absolute paths as labels

### ISSUE THREAD

**Issue by claridge** [bazelbuild/bazel#177]
If you try to pass an absolute path to a cc_library's linkopts, Bazel raises a "could not resolve label '<absolute path>'" error. This interferes with linking against a library installed at a fixed location for which "-l" can't be used.

As a temporary workaround, I'm setting up a make_variable in my CROSSTOOL file that stores the library path.

**Comment by hanwen** [comment]
can you import the .a into your repository either as a symlink or by copying?

**Comment by claridge** [comment]
I just tried using a symlink - that does work.

**Comment by damienmg** [comment]
Closing as this was resolved for the specific case. For future reference, the correct way of doing so is to use a local repository (http://bazel.io/docs/build-encyclopedia.html#new_local_repository) to include the .a

**Comment by damienmg** [comment]
Oops sorry misread the solution. We should make this possible using local repository.

**Comment by damienmg** [comment]
Assigning to myself as the autoconf mechanism should make that possible

**Comment by damienmg** [comment]
Hi @claridge, Have you seen: https://groups.google.com/d/msg/bazel-discuss/MSunz2ZUOq0/U5tE7uQLJQAJ?

**Comment by damienmg** [comment]
(Closing since I believe this is now doable correctly)

**Comment by claridge** [comment]
@damienmg, I hadn't, thanks!

A little while ago we started using a local_repository instead of a Make variable for this.
