### ISSUE TITLE
Add git_repository to bzlmod

### ISSUE THREAD

**Issue by lifengxiang1025** [bazelbuild/bazel#17704]
### Description of the feature request:

Add git_repository to bzlmod.

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

6.1.0

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/17473

**Comment by lifengxiang1025** [comment]
#https://github.com/lifengxiang1025/bazel/pull/new/lfx

**Comment by Wyverald** [comment]
You need to send the PR against the bazelbuild/bazel repo, not your own fork.

**Comment by Wyverald** [comment]
Dupe of https://github.com/bazelbuild/bazel/issues/17473
