### ISSUE TITLE
[Mirror] protobuf v22.1

### ISSUE THREAD

**Issue by malt3** [bazelbuild/bazel#17701]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/protocolbuffers/protobuf/archive/v22.1.tar.gz
https://github.com/protocolbuffers/protobuf/releases/download/v22.1/protoc-22.1-linux-aarch_64.zip
https://github.com/protocolbuffers/protobuf/releases/download/v22.1/protoc-22.1-linux-ppcle_64.zip
https://github.com/protocolbuffers/protobuf/releases/download/v22.1/protoc-22.1-linux-s390_64.zip
https://github.com/protocolbuffers/protobuf/releases/download/v22.1/protoc-22.1-linux-x86_32.zip
https://github.com/protocolbuffers/protobuf/releases/download/v22.1/protoc-22.1-linux-x86_64.zip
https://github.com/protocolbuffers/protobuf/releases/download/v22.1/protoc-22.1-osx-aarch_64.zip
https://github.com/protocolbuffers/protobuf/releases/download/v22.1/protoc-22.1-osx-x86_64.zip
https://github.com/protocolbuffers/protobuf/releases/download/v22.1/protoc-22.1-win32.zip
https://github.com/protocolbuffers/protobuf/releases/download/v22.1/protoc-22.1-win64.zip
https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.22.1/protobuf-java-3.22.1.jar
https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.22.1/protobuf-java-3.22.1-sources.jar
https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java-util/3.22.1/protobuf-java-util-3.22.1.jar
https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java-util/3.22.1/protobuf-java-util-3.22.1-sources.jar
https://repo1.maven.org/maven2/com/google/protobuf/protobuf-javalite/3.22.1/protobuf-javalite-3.22.1.jar
https://repo1.maven.org/maven2/com/google/protobuf/protobuf-javalite/3.22.1/protobuf-javalite-3.22.1-sources.jar

**Comment by sgowroji** [comment]
Please find the below mirror artifacts

1. https://mirror.bazel.build/github.com/protocolbuffers/protobuf/archive/v22.1.tar.gz
2. https://mirror.bazel.build/github.com/protocolbuffers/protobuf/releases/download/v22.1/protoc-22.1-linux-aarch_64.zip
3. https://mirror.bazel.build/github.com/protocolbuffers/protobuf/releases/download/v22.1/protoc-22.1-linux-ppcle_64.zip
4. https://mirror.bazel.build/github.com/protocolbuffers/protobuf/releases/download/v22.1/protoc-22.1-linux-s390_64.zip
5. https://mirror.bazel.build/github.com/protocolbuffers/protobuf/releases/download/v22.1/protoc-22.1-linux-x86_32.zip
6. https://mirror.bazel.build/github.com/protocolbuffers/protobuf/releases/download/v22.1/protoc-22.1-linux-x86_64.zip
7. https://mirror.bazel.build/github.com/protocolbuffers/protobuf/releases/download/v22.1/protoc-22.1-osx-aarch_64.zip
8. https://mirror.bazel.build/github.com/protocolbuffers/protobuf/releases/download/v22.1/protoc-22.1-osx-x86_64.zip
9. https://mirror.bazel.build/github.com/protocolbuffers/protobuf/releases/download/v22.1/protoc-22.1-win32.zip
10. https://mirror.bazel.build/github.com/protocolbuffers/protobuf/releases/download/v22.1/protoc-22.1-win64.zip
11. https://mirror.bazel.build/repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.22.1/protobuf-java-3.22.1.jar
12. https://mirror.bazel.build/repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.22.1/protobuf-java-3.22.1-sources.jar
13. https://mirror.bazel.build/repo1.maven.org/maven2/com/google/protobuf/protobuf-java-util/3.22.1/protobuf-java-util-3.22.1.jar
14. https://mirror.bazel.build/repo1.maven.org/maven2/com/google/protobuf/protobuf-java-util/3.22.1/protobuf-java-util-3.22.1-sources.jar
15. https://mirror.bazel.build/repo1.maven.org/maven2/com/google/protobuf/protobuf-javalite/3.22.1/protobuf-javalite-3.22.1.jar
16. https://mirror.bazel.build/repo1.maven.org/maven2/com/google/protobuf/protobuf-javalite/3.22.1/protobuf-javalite-3.22.1-sources.jar
