### ISSUE TITLE
bazel build //src/tools/generate_workspace failed

### ISSUE THREAD

**Issue by jeshjesh** [bazelbuild/bazel#1772]
I clone the master, and run bazel run //src/tools/generate_workspace failed.
bazel-master/tools/jdk/BUILD:117:1: //tools/jdk:toolchain: no such attribute 'javac_supports_workers' in 'java_toolchain' rule.
bazel-master/src/main/native/BUILD:1:1: Target '//tools/jdk:jni_md_header-darwin' contains an error and its package is in error and referenced by '//src/main/native:copy_link_jni_md_header'.
ERROR: Analysis of target '//src/tools/generate_workspace:generate_workspace' failed; build aborted.

**Comment by kchodorow** [comment]
It sounds like a version mismatch between the bazel you're running and master.  Could you try either checking out the version of bazel your binary is (e.g., `bazel version; git checkout 1.2.3`) or building & using the bazel at head (`./compile.sh; output/bazel run //src/tools/generate_workspace`)?

**Comment by damienmg** [comment]
No answer so closing, @jeshjesh please ping back if this is still an issue.

**Comment by jeshjesh** [comment]
It is a problem of version mismatch. Already fixed. Thanks.
