### ISSUE TITLE
Searching on bazel.io is down

### ISSUE THREAD

**Issue by hermione521** [bazelbuild/bazel#1773]
```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous users does not have storage.objects.get access to object www.bazel.io/search.html.
</Details>
</Error>
```

**Comment by dmishe** [comment]
Same with https://www.bazel.io/versions/master/docs/skylark/lib/skylark-builtin.html and other parts of Skylark docs.

**Comment by dslomov** [comment]
Back to normal now. Looks like we hit a builder publishing a site. Maybe that's longer now, therefore more noticable?

**Comment by damienmg** [comment]
When you update the site, for every changed page GCS reset the permission. If GCS is slow, then this change might take several minutes.
