### ISSUE TITLE
Infer bzlmod from BUILD.bzl

### ISSUE THREAD

**Issue by PandaBlueYellow** [bazelbuild/bazel#17730]
### Description of the feature request:

Hi,
Is it possible to let bazel analyze the BUILD.bazel in order to collect information about bzlmod? 
Thanks

### What underlying problem are you trying to solve with this feature?

Avoid the need to create a separate MODULE.bazel

**Comment by Wyverald** [comment]
The short answer is "no", and if you disagree, please provide more information.

**Comment by PandaBlueYellow** [comment]
Do you think it's technically impossible? Or it's just because no such tool is available currently?
