### ISSUE TITLE
Remove `--distinct_host_configuration`

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#17731]
The flag `--distinct_host_configuration` is a no-op since Bazel 6.0.0 (specifically, since 78d0fc9ff1d2f22005ddfce43384e35fbac338cb).

The flag should be entirely removed, which means also removing all uses.

**Comment by fmeum** [comment]
@katre Instead of removing the flag without replacement, would there be an option to replace it with a `--distinct_exec_configuration` flag?

**Comment by katre** [comment]
The flag is already a no-op: this is just to track deleting it. If the feature is actually useful (and I am not convinced that it is, it involved lying to Bazel about what you were building), a new feature request can be filed and discussed.
