### ISSUE TITLE
In Python 3.8. default format of tarfiles was changed from GNU_FORMAT to PAX_FORMAT. Building Debian packages using `pkg_tar` is broken.

### ISSUE THREAD

**Issue by ahryniv** [bazelbuild/bazel#17746]
### Description of the bug:

In Python 3.8. [default format](https://docs.python.org/3/library/tarfile.html#tarfile.DEFAULT_FORMAT) of tarfiles was changed from `GNU_FORMAT` to `PAX_FORMAT`.
Using `pkg_tar` with `python>=3.8` for building Debian packages breaks the `pkg_deb` rule because `dpkg` expects GNU format.

The proposed solution is to specify the tarfile format parameter explicitly. If nothing is specified default format will be used.
Please, check proposed implementation in the [PR](https://github.com/bazelbuild/bazel/pull/17679)

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build a Debian package using `pkg_tar` and `pkg_deb` rules with Python >= 3.8 and try to install it with `dpkg`.

**Comment by meteorcloudy** [comment]
@aiuto Can you take a look, we should no longer have pkg_tar, pkg_deb in Bazel repo, right?

**Comment by aiuto** [comment]
They ancient pkg_tar is still there because I have not figured out how to disentangle it from some repository rule tests.
No own should use it. They must migrate to rules_pkg.
