### ISSUE TITLE
`alias` targets should expose `FilesToRunProvider` if `actual` has one

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/bazel#17749]
### Description of the bug:

I have code which runs a `cquery` to gets the executable of a `FilesToRunProvider`:

`bazel cquery --output=starlark --starlark:expr="providers(target).get(\"FilesToRunProvider\").executable.path"`

This doesn't work for `alias` targets which point to binary targets. It probably should.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

BUILD file:
```starlark
py_binary(
    name = "bin",
    srcs = ["bin.py"],
)

alias(
    name = "alias",
    actual = ":bin",
)
```

Run: `bazel cquery --output=starlark --starlark:expr="providers(target).get(\"FilesToRunProvider\").executable.path" :alias`

expect to get an output path. Instead, get an error because `providers(target).get("FilesToRunProvider")` is `None`.

### What is the output of `bazel info release`?

release 6.1.0

**Comment by fmeum** [comment]
Seems to be a much more general issue:
```
$ bazel cquery --output=starlark --starlark:expr="providers(target)" :alias
None
```
