### ISSUE TITLE
Missing Bazel linux-arm64 build for NOJDK flavor

### ISSUE THREAD

**Issue by kevinxw** [bazelbuild/bazel#17742]
### Description of the bug:

Both GitHub release & Bazel mirror are missing the Linux ARM64 NOJDK flavor

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Check https://releases.bazel.build/6.1.0/release/
Only the JDK version for Linux ARM64 is provided, NOJDK version is missing.

### Which operating system are you running Bazel on?

Ubuntu ARM64

**Comment by meteorcloudy** [comment]
Fixing in https://github.com/bazelbuild/continuous-integration/pull/1575
