### ISSUE TITLE
osx_cc_wrapper.sh:get_realpath is buggy for relative uplevel symlinks

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#1776]
If we have the following directory tree:

```
./a/a.sym -> ../hello.txt
./a/b/b.sym -> ../a.sym
./a/b/c/c.sym -> ../b.sym
./hello.txt
```

Then all symlinks ultimately point to `hello.txt`, yet `get_realpath a/b/c/c.sym` will return `../b.sym`.

I have a fix for this as part of opensourceing some shell integration tests.

**Comment by laszlocsomor** [comment]
@damienmg : FYI

**Comment by mhlopko** [comment]
To clarify, does this issue say that osx_cc_wrapper should use get_real_path from cf773d2?

**Comment by laszlocsomor** [comment]
That'd be better, yes, though it wouldn't be perfect. The `get_real_path` in is not a real `realpath`: `get_real_path` just follows symlinks until it can't any further, resolving only the last segment of the path and may leave upper-level components as symlinks. The real `realpath` resolves all segments of a path so the result doesn't contain any symlinks.

**Comment by mhlopko** [comment]
I see. Thanks for clarification.

**Comment by laszlocsomor** [comment]
Status update: I'm not actively working on this issue.

**Comment by meisterT** [comment]
Is this still an issue?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
