### ISSUE TITLE
Intellij sync fails when importing Bazel

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#1777]
I am trying to use the latest Bazel (`467e716`) with the IntelliJ plugin to browse the Bazel source.

My _ProjectView_ looks like

    directories:
      .

    targets:
      //...:all

When attempting to partially sync output is

    Syncing project...
    Running Bazel info...
    Command: /Projects/bazel/output/bazel info --tool_tag=ijwb:IDEA:community --

    Sync failed

    ==== TIMING REPORT ====

    Sync: 21.7s
        BazelRoots: 21.7s

Executing the `info` command works fine and the error message `Sync failed` is not that great...

**Comment by dslomov** [comment]
Filed https://github.com/bazelbuild/intellij/issues/20
