### ISSUE TITLE
[bazel.build] Problem with /install

### ISSUE THREAD

**Issue by Kve-sudo-tech** [bazelbuild/bazel#17776]
### Page link:

https://bazel.build/install

### Problem description (include actual vs expected text, if applicable):

como instalo bazel

### Where do you see this issue? (include link to specific section of the page, if applicable)

en el comienzo de la apicacion

### Any other information you'd like to share?

pues  nomas queria comentar que  apenas estoy aprendiendo todo esto y hay muchas cosas que no entiendo pero me esfuerzo para entender , me encanta todo lo que hacen aqui, lo raro es por que me gusta si la mayoria de las cosas no las entiendo pero se y estoy seuro que existen muchas maravillosas no me cabe la menor duda,

**Comment by keertk** [comment]
Hi there! This seems like a support related question rather than a bug? Please feel free to ask on our support channels - [bazel-discuss@googlegroups.com](mailto:bazel-discuss@googlegroups.com) or [slack.bazel.build](https://slack.bazel.build/).
