### ISSUE TITLE
Export structured test output

### ISSUE THREAD

**Issue by mikedanese** [bazelbuild/bazel#1779]
Is it possible to export structured test output in xml/json/protobuf?

**Comment by damienmg** [comment]
Sorry, can you be more explicit about what you'd like to have?

**Comment by mikedanese** [comment]
@damienmg We are currently use junit xml test output (popular xml test output format) to generate dashboards like this https://k8s-testgrid.appspot.com/k8s#gce . We also load all test data in a BigQuery database. We can derive a structured output to use in tooling by parsing the output `--test_output=all`, but It would be nice to have a `--test_output=json`  or similar. cc @spxtr

**Comment by damienmg** [comment]
I still do not understand. Bazel generate ant junit XML files under bazel-testlogs, isn't that enough?

**Comment by mikedanese** [comment]
Thanks! I did not notice that but is exactly what I was looking fore
