### ISSUE TITLE
@bazel_tools//tools/cpp:compiler:gcc detection does not handle `gcc-10`

### ISSUE THREAD

**Issue by jbms** [bazelbuild/bazel#17794]
### Description of the bug:

Bazel's detection of GCC only works if the compiler executable name is exactly "gcc":

https://github.com/bazelbuild/bazel/blob/f06d00b8060b3b50f5dbc4a03b957c269ef62670/tools/cpp/unix_cc_configure.bzl#L273

Consequently, it fails to detect common variations like `gcc-10` as GCC.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

CC=gcc-10 bazel ...

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 6.1.0

**Comment by fmeum** [comment]
I simply didn't consider this case when I submitted https://github.com/bazelbuild/bazel/commit/ef3f05852b3bf542903f091184da96b96354a13d. Happy to (pre-)review a PR.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.1.0 RC1](https://releases.bazel.build/7.1.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!
