### ISSUE TITLE
 "missing dependency" error only when build as root

### ISSUE THREAD

**Issue by mikewei** [bazelbuild/bazel#178]
bazel version: commit f636cedabf07d3e1fa01f79478c711717dc0d990
## build FAILED as root

```
 [root@centos jemalloc-360]# pwd
 /root/work/third-party/jemalloc-360
 [root@centos jemalloc-360]# cat BUILD 
 package(default_visibility = ["//visibility:public"])
 cc_library(
    name = "jemalloc-360",
    includes = ["include"],
    hdrs = glob(["include/jemalloc/*.h"]),
    copts = [
        "-D_GNU_SOURCE",
        "-D_REENTRANT",
        "-std=gnu99",
        "-Wall",
        "-pipe",
        "-g3",
        "-fvisibility=hidden",
        "-O3",
        "-funroll-loops",
        "-Wno-unused-but-set-variable",
        "-Wno-unused-function",
        "-Wno-maybe-uninitialized",
        "-Wno-unused-variable",
    ],
    linkopts = ["-pthread"],
    linkstatic = 1,
    hdrs_check = "loose",
    srcs = glob(
        [
            "include/jemalloc/*.h",
            "include/jemalloc/internal/*.h",
            "src/*.c",
        ], 
        ["src/zone.c"],
    ),
    deps = [],
   )

 [root@centos jemalloc-360]# bazel build .
 INFO: Found 1 target...
 ERROR: /root/work/third-party/jemalloc-360/BUILD:3:1: undeclared inclusion(s) in rule '//third-party/jemalloc-360:jemalloc-360':
 this rule is missing dependency declarations for the following files included by 'third-party/jemalloc-360/src/tsd.c':
   '/root/work/third-party/jemalloc-360/include/jemalloc/jemalloc.h'.
 Target //third-party/jemalloc-360:jemalloc-360 failed to build
 Use --verbose_failures to see the command lines of failed build steps.
 INFO: Elapsed time: 0.609s, Critical Path: 0.32s
```
## build OK as USER(not root)

```
 [mikewei@centos jemalloc-360]$ pwd
 /home/mikewei/work/third-party/jemalloc-360
 [mikewei@centos jemalloc-360]$ bazel build .
 INFO: Found 1 target...
 Target //third-party/jemalloc-360:jemalloc-360 up-to-date:
   bazel-bin/third-party/jemalloc-360/libjemalloc-360.a
 INFO: Elapsed time: 0.293s, Critical Path: 0.00s
 [mikewei@centos jemalloc-360]$ diff -r /root/work/third-party/jemalloc-360/ .   (no difference)
 [mikewei@centos jemalloc-360]$ 
```

why? help please

**Comment by damienmg** [comment]
Note: I edited your report to use raw formatting for your snippet

diff -r /root/work ../../ (difference between workspaces) ?

Is the error consistent (what happens if you retry to build in /root/work?)?

The `hdrs = glob(["include/jemalloc/*.h"])` glob in root probably globing nothing.

**Comment by mikewei** [comment]
Is the error consistent (what happens if you retry to build in /root/work?)?
YES

diff -r /root/work ../../ (difference between workspaces) ?
I think the difference is irrelavent:
[mikewei@centos work]$ pwd
/home/mikewei/work
[mikewei@centos work]$ diff -r . /root/work
Binary files ./third-party/.git/index and /root/work/third-party/.git/index differ
diff -r ./third-party/.git/logs/HEAD /root/work/third-party/.git/logs/HEAD
1c1
< 0000000000000000000000000000000000000000 cdcbe2dab7af01bbcf88a000c289b8d4ce389fbb mikewei <mikewei@centos.(none)> 1430884000 +0800	clone: from git@git.n.xiaomi.com:messaging/third-party.git
---
> 0000000000000000000000000000000000000000 cdcbe2dab7af01bbcf88a000c289b8d4ce389fbb weibin1 <weibin1@xiamo.com> 1430884189 +0800	clone: from git@git.n.xiaomi.com:messaging/third-party.git
diff -r ./third-party/.git/logs/refs/heads/master /root/work/third-party/.git/logs/refs/heads/master
1c1
< 0000000000000000000000000000000000000000 cdcbe2dab7af01bbcf88a000c289b8d4ce389fbb mikewei <mikewei@centos.(none)> 1430884000 +0800	clone: from git@git.n.xiaomi.com:messaging/third-party.git
---
> 0000000000000000000000000000000000000000 cdcbe2dab7af01bbcf88a000c289b8d4ce389fbb weibin1 <weibin1@xiamo.com> 1430884189 +0800	clone: from git@git.n.xiaomi.com:messaging/third-party.git
Binary files ./third-party/.git/objects/pack/pack-b470528e9b1748f1c45d3c9fd4d1c34b584fa117.idx and /root/work/third-party/.git/objects/pack/pack-b470528e9b1748f1c45d3c9fd4d1c34b584fa117.idx differ
Binary files ./third-party/.git/objects/pack/pack-b470528e9b1748f1c45d3c9fd4d1c34b584fa117.pack and /root/work/third-party/.git/objects/pack/pack-b470528e9b1748f1c45d3c9fd4d1c34b584fa117.pack differ

**Comment by mikewei** [comment]
The hdrs = glob(["include/jemalloc/*.h"]) glob in root probably globing nothing.

I don't think so...
If I explictly add jemalloc.h to hdrs, I got this error:
    [root@centos jemalloc-360]# cat BUILD 
    package(default_visibility = ["//visibility:public"])
    
    cc_library(
	    name = "jemalloc-360",
	    includes = ["include"],
	    hdrs = glob(["include/jemalloc/*.h"]),
    	copts = [
	    	"-D_GNU_SOURCE",
		    "-D_REENTRANT",
		    "-std=gnu99",
		    "-Wall",
		    "-pipe",
		    "-g3",
		    "-fvisibility=hidden",
		    "-O3",
		    "-funroll-loops",
		    "-Wno-unused-but-set-variable",
		    "-Wno-unused-function",
		    "-Wno-maybe-uninitialized",
		    "-Wno-unused-variable",
	    ],
	    linkopts = ["-pthread"],
	    linkstatic = 1,
	    hdrs_check = "loose",
	    srcs = glob(
		    [
			    "include/jemalloc/*.h",
			    "include/jemalloc/internal/*.h",
			    "src/*.c",
		    ], 
		    ["src/zone.c"],
	    ) + ["include/jemalloc/jemalloc.h"],
	    deps = [],
    )

bazel build .
ERROR: /root/work/third-party/jemalloc-360/BUILD:3:1: Label '//third-party/jemalloc-360:include/jemalloc/jemalloc.h' is duplicated in the 'srcs' attribute of rule 'jemalloc-360'.
ERROR: error loading package 'third-party/jemalloc-360': Package 'third-party/jemalloc-360' contains errors.
INFO: Elapsed time: 0.187s

**Comment by damienmg** [comment]
right .git repository shouldn't matter.

The glob I am talking about is the one for the `hdrs` attribute. But that's probably don't make sense either. Can you, as root, cat include/jemalloc/jemalloc.h? What does `getenforce` returns?

Is jemalloc-360 an open-source stuff? Can I download it to try to reproduce the problem? If not, can you make an extracted version of it?

**Comment by mikewei** [comment]
I test it in another debian(jessie) system, and it is also reproducible (build as root fail)
jemalloc-360 is the open-source jemalloc official version 3.6.0 (https://github.com/jemalloc/jemalloc/releases)

I can reproduce it as follows:
    root@debain:~/work/third-party# tar jxvf jemalloc-3.6.0.tar.bz2
    root@debain:~/work/third-party# mv jemalloc-3.6.0 jemalloc-360
    root@debain:~/work/third-party# cd jemalloc-360
    root@debain:~/work/third-party/jemalloc-360# ./configure
    root@debain:~/work/third-party/jemalloc-360# cp THE_BUILD_FILE .
    root@debain:~/work/third-party/jemalloc-360# bazel build .

**Comment by mikewei** [comment]
Can you, as root, cat include/jemalloc/jemalloc.h? What does getenforce returns?

[root@centos jemalloc-360]# cat include/jemalloc/jemalloc.h |head 
#ifndef JEMALLOC_H_
#define	JEMALLOC_H_
#ifdef __cplusplus
extern "C" {
#endif

/* Defined if __attribute__((...)) syntax is supported. */
#define	JEMALLOC_HAVE_ATTR

/* Support the experimental API. */
[root@centos jemalloc-360]# getenforce 
Enforcing
[root@centos jemalloc-360]# pwd
/root/work/third-party/jemalloc-360

**Comment by damienmg** [comment]
Tested on my machine it worked.
ls -l ~root/work?
getenforce is set to enforced in debian too?
cat ~root/.bazelrc?

**Comment by mikewei** [comment]
(maclinux is debian)
root@maclinux:~/work/third-party/jemalloc-360# getenforce 
Disabled

root@maclinux:~/work/third-party/jemalloc-360# bazel build .
INFO: Found 1 target...
ERROR: /root/work/third-party/jemalloc-360/BUILD:3:1: undeclared inclusion(s) in rule '//third-party/jemalloc-360:jemalloc-360':
this rule is missing dependency declarations for the following files included by 'third-party/jemalloc-360/src/hash.c':
  '/root/work/third-party/jemalloc-360/include/jemalloc/jemalloc.h'.
Target //third-party/jemalloc-360:jemalloc-360 failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.574s, Critical Path: 0.39s
root@maclinux:~/work/third-party/jemalloc-360# cat ~/.bazelrc 
build --package_path %workspace%:/home/mikewei/mi/bazel-tools:/home/mikewei/mi/bazel-tools/bazel/base_workspace
root@maclinux:~/work/third-party/jemalloc-360# ll ~/work
total 24
lrwxrwxrwx 1 root root  104 May  6 19:25 bazel-bin -> /root/.cache/bazel/_bazel_root/e34b4c5077c3736f76750b467c603b48/work/bazel-out/local_linux-fastbuild/bin
lrwxrwxrwx 1 root root  109 May  6 19:25 bazel-genfiles -> /root/.cache/bazel/_bazel_root/e34b4c5077c3736f76750b467c603b48/work/bazel-out/local_linux-fastbuild/genfiles
lrwxrwxrwx 1 root root   78 May  6 19:25 bazel-out -> /root/.cache/bazel/_bazel_root/e34b4c5077c3736f76750b467c603b48/work/bazel-out
lrwxrwxrwx 1 root root  109 May  6 19:25 bazel-testlogs -> /root/.cache/bazel/_bazel_root/e34b4c5077c3736f76750b467c603b48/work/bazel-out/local_linux-fastbuild/testlogs
lrwxrwxrwx 1 root root   68 May  6 19:25 bazel-work -> /root/.cache/bazel/_bazel_root/e34b4c5077c3736f76750b467c603b48/work
drwxr-xr-x 3 root root 4096 May  7 19:54 third-party
-rw-r--r-- 1 root root    0 May  6 19:24 WORKSPACE

mikewei@maclinux:~/work/third-party/jemalloc-360$ bazel build .
Sending SIGTERM to previous Bazel server (pid=8246)... done.
.......
INFO: Found 1 target...
Target //third-party/jemalloc-360:jemalloc-360 up-to-date:
  bazel-bin/third-party/jemalloc-360/libjemalloc-360.a
INFO: Elapsed time: 1.564s, Critical Path: 0.21s
mikewei@maclinux:~/work/third-party/jemalloc-360$ cat ~/.bazelrc 
build --package_path %workspace%:/home/mikewei/mi/bazel-tools:/home/mikewei/mi/bazel-tools/bazel/base_workspace
mikewei@maclinux:~/work/third-party/jemalloc-360$ ll ~/work
total 24
lrwxrwxrwx 1 mikewei mikewei  115 May  7 20:08 bazel-bin -> /home/mikewei/.cache/bazel/_bazel_mikewei/0cb683f873f3eafb31470f76b21a2e1f/work/bazel-out/local_linux-fastbuild/bin
lrwxrwxrwx 1 mikewei mikewei  120 May  7 20:08 bazel-genfiles -> /home/mikewei/.cache/bazel/_bazel_mikewei/0cb683f873f3eafb31470f76b21a2e1f/work/bazel-out/local_linux-fastbuild/genfiles
lrwxrwxrwx 1 mikewei mikewei   89 May  7 20:08 bazel-out -> /home/mikewei/.cache/bazel/_bazel_mikewei/0cb683f873f3eafb31470f76b21a2e1f/work/bazel-out
lrwxrwxrwx 1 mikewei mikewei  120 May  7 20:08 bazel-testlogs -> /home/mikewei/.cache/bazel/_bazel_mikewei/0cb683f873f3eafb31470f76b21a2e1f/work/bazel-out/local_linux-fastbuild/testlogs
lrwxrwxrwx 1 mikewei mikewei   79 May  7 20:08 bazel-work -> /home/mikewei/.cache/bazel/_bazel_mikewei/0cb683f873f3eafb31470f76b21a2e1f/work
drwxr-xr-x 3 mikewei mikewei 4096 May  7 20:00 third-party
-rw-r--r-- 1 mikewei mikewei    0 May  7 19:59 WORKSPACE

**Comment by mikewei** [comment]
I  found something interesting, if I change the WORKSPACE path it works!

root@maclinux:~/work/third-party/jemalloc-360# ls ~/work/WORKSPACE 
/root/work/WORKSPACE
root@maclinux:~/work/third-party/jemalloc-360# touch ~/work/third-party/WORKSPACE
root@maclinux:~/work/third-party/jemalloc-360# bazel build .
.......
INFO: Found 1 target...
Target //jemalloc-360:jemalloc-360 up-to-date:
  bazel-bin/jemalloc-360/libjemalloc-360.a
INFO: Elapsed time: 7.211s, Critical Path: 5.88s
root@maclinux:~/work/third-party/jemalloc-360# rm ~/work/third-party/WORKSPACE
root@maclinux:~/work/third-party/jemalloc-360# bazel build .
INFO: Found 1 target...
ERROR: /root/work/third-party/jemalloc-360/BUILD:3:1: undeclared inclusion(s) in rule '//third-party/jemalloc-360:jemalloc-360':
this rule is missing dependency declarations for the following files included by 'third-party/jemalloc-360/src/atomic.c':
  '/root/work/third-party/jemalloc-360/include/jemalloc/jemalloc.h'.
Target //third-party/jemalloc-360:jemalloc-360 failed to build
Use --verbose_failures to see the command lines of failed build steps.

Or if I move /root/work to /root/somedir/work it also works.

**Comment by damienmg** [comment]
Ok I reproduced it by moving my workspace to /root/work. That's funny.

**Comment by ulfjack** [comment]
Do we have any idea what's going wrong here? ISTR something odd with short paths, but no details.

**Comment by meisterT** [comment]
This doesn't seem to be reproducible anymore.
