### ISSUE TITLE
Problem importing a project in IntelliJ - Invalid aspect

### ISSUE THREAD

**Issue by alessiocnit** [bazelbuild/bazel#17809]
### Page link:

https://bazel.build/help

### Problem description (include actual vs expected text, if applicable):

I'm trying to import onosproject with IntelliJ after installation of the bazel plugin. I did many times and every time I got some bazel problems... this time the problem is appearing during sync as follows:

Invalid aspect '@@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect': invalid repository name '@@intellij_aspect': repo names may contain only A-Z, a-z, 0-9, ... ... ... 

### Where do you see this issue? (include link to specific section of the page, if applicable)

During Sysc in the Bazel Problems window. It suggest to retry without the option "Expand Sync to Working Set' but this does not solve the problem.

### Any other information you'd like to share?

I'm running Intellij 2022.3.3 on Ubuntu 20.04

**Comment by Migo980226** [comment]
I had the same problem. Did you solve this problem?
