### ISSUE TITLE
Improve `--toolchain_resolution_debug`

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#17814]
The flag `--tolchain_resolution_debug` is helpful when there are problems with toolchain resolution, but is still far from perfect.

Known issues:
-  Platform mappings aren't made clear, causing confusion
-  The flag is overly verbose, while still not giving details
-  Exec groups aren't clearly grouped together

Probably more, this issue is for collecting issues and ideas.

**Comment by keith** [comment]
I think it would be nice if the platform being looked for was output more verbosely as well to help decipher _why_ things don't match

**Comment by xushaoxiao** [comment]
Type @bazel_tools//tools/python:toolchain_type: target platform @local_config_platform//:host: No toolchains found.

**Comment by katre** [comment]
Closed #12110, but the suggestion to fix the ordering is a useful one.

**Comment by konkers** [comment]
I found that knowing the value of the mismatched constraint to be useful in debugging toolchain resolution issues when a project has set up complicated constraints.  Here's a quite old patch that I used to debug resolution issues where it was unclear to me what values I needed to add to my platform/toolchain to get them to match: https://github.com/konkers/bazel/commit/f009c1931d83768047c714e39bb070ff345002af
