### ISSUE TITLE
generate_workspace should be able to use a configurable Maven Central URL

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1782]
Either:
- Picking it up from settings.xml
- Give it a path to settings.xml
- Or set a flag for Maven Central URL.

**Comment by is03wlei** [comment]
It's really needed!

**Comment by jylin** [comment]
I'm not sure whether it's worth opening a new issue for this, but generate_workspace does not pickup proxy settings from .m2/settings.xml either. Also, the tool doesn't seem to pickup http_proxy or https_proxy environment variables either. Is there a way to pass those to "bazel run"?

**Comment by laszlocsomor** [comment]
@jylin : Yes please open a separate issue for that.

**Comment by jylin** [comment]
Sure, filed https://github.com/bazelbuild/bazel/issues/1800

**Comment by jin** [comment]
Closing this as generate_workspace is no longer maintained. Please open Maven-related issues on [rules_jvm_external](https://github.com/bazelbuild/rules_jvm_external) instead.

rules_jvm_external supports custom Maven repository URLs through the `maven_install.repositories` attribute.
