### ISSUE TITLE
Provide tooling to import multiple versions of an artifact

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1783]
E.g., `generate_workspace --artifact=jetty:1,old_prod --artifact=jetty:2,prod` will create two maven_jars with the given suffixes and their dependencies, matching deps where possible and appending the suffix where not, e.g.,

```
jetty_prod -> foo_prod -> bar
jetty_old_prod -> foo_old_prod -> bar
```

jetty, foo, and bar are maven artifacts, dep on bar is the same version for both, dep on foo is not.

**Comment by jin** [comment]
Closing this as generate_workspace is no longer maintained. Please open Maven-related issues on [rules_jvm_external](https://github.com/bazelbuild/rules_jvm_external) instead.

rules_jvm_external supports declaring multiple `maven_install` instances, enabling multiple versions of an artifact namespaced by an external repository.
