### ISSUE TITLE
Build Bazel against libc++ instead of libstdc++

### ISSUE THREAD

**Issue by aaronmondal** [bazelbuild/bazel#17838]
### Description of the feature request:

At the moment a downloaded Bazel release binary for linux dynamically links against a GCC toolchain, i.e. libstdc++ and friends.

I wonder whether it would make sense to change this to an llvm-based toolchain.

Essentially, when I run `ldd bazel`, on a release binary, I'd want to get rid of

```
libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/13/libstdc++.so.6
```

And instead have something along the lines of

```
libc++.so.1 => /usr/lib64/libc++abi.so.1
```

Or no dynamic linking for these libraries at all.

### What underlying problem are you trying to solve with this feature?

At the moment users of pure llvm-project-based systems have two choices to run Bazel:

- Build it themselves against a libc++ toolchain
- Install a guest libstdc++/GCC toolchain so that the prebuilt Bazel binary works.

This also affects bazelisk usage.

Libc++ is licensed under Apache 2.0 with LLVM exceptions. Using libc++ might make it possible to statically link the c++ runtime dependencies into bazel release binaries.

With static linking the release binaries would be more portable and might benefit from a slight performance improvement.

### Which operating system are you running Bazel on?

- Gentoo X86_64 with clang profile
- Remote execution containers built with nix (i.e. no standard FHS layout).

**Comment by aaronmondal** [comment]
@GMNGeoffrey Did you also run into this? How are you dealing with it?

**Comment by GMNGeoffrey** [comment]
> @GMNGeoffrey Did you also run into this? How are you dealing with it?

I think I've just been using option 2 you list above. In practice there's usually been a libstdc++ install on the machine or I need it for other things. But I'm usually on Debian-based distributions.

Providing the option for statically-linked portable binaries seems nice.
