### ISSUE TITLE
Bazel spins up thousands of persisting `KQueueEventLoopGroup` threads during builds

### ISSUE THREAD

**Issue by holtherndon-stripe** [bazelbuild/bazel#17856]
### Description of the bug:

Internally we're using Bazel alongside BEP (bes) and a remote build cache server. When we have the `bes_backend` set (usually to localhost and some generated port number), Bazel spins up 800-1000 threads. All these threads name match `KQueueEventLoopGroup-(increasing number)-(number 1-20)`. According to YourKit, these threads are only active for a few milliseconds, but persist until the Bazel server restarts (or in our case, the laptop runs out of threads/memory and the OS kills the process).

<img width="1914" alt="image" src="https://user-images.githubusercontent.com/104039057/227044370-733e1ae4-f3f8-4971-8d21-2a1ec883ba2b.png">

I did some digging in the Bazel server source to attempt to find a culprit, but ran out of time. I set a few breakpoints and most of the threads were usually produced after a call on `RemoteCache#findMissingDigests()` which in turn caused more gRPC clients to spin up.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Locally, it seems to be running a build with a local `bes_backend` and a configured remote build cache. Commenting out the `bes_backend` flag on our script causes the issue to subside.

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 5.4.0

**Comment by benjaminp** [comment]
#16098

**Comment by meisterT** [comment]
@holtherndon-stripe can you try with a more recent Bazel version that includes the fix?

**Comment by holtherndon-stripe** [comment]
Following up - we upgraded to 6.1.1, and the issue appears to have been fixed! Thanks for the help!
