### ISSUE TITLE
bzlmod build occurred some resolution problem: No matching toolchains found for types @bazel_tools//tools/python:toolchain_type

### ISSUE THREAD

**Issue by xushaoxiao** [bazelbuild/bazel#17866]
### Description of the bug:

Hi Bazel teams, 

I am doing build monorepo via bazel mod, my example github repo is https://github.com/xushaoxiao/allinone-via-bazelmod.
it occurred a error when i build the source code that includes rules_java and rules_python and other bazel rules, the details is "While resolving toolchains for target @bazel_tools//tools/jdk:proguard_whitelister: No matching toolchains found for types @bazel_tools//tools/python:toolchain_type.", conflicts between rules_java and rules_python imports in MODULE.bazel.

run the build command `bazel build --enable_bzlmod ...`, output error log details is:

```
LCNC02GG727MD6R:allinone-via-bazelmod shaoxixu$ bazel build --enable_bzlmod ...
Starting local Bazel server and connecting to it...
DEBUG: rules_go@0.37.0/MODULE.bazel:8:6: WARNING: The rules_go Bazel module is still highly experimental and subject to change at any time. Only use it to try out bzlmod for now.
DEBUG: gazelle@0.27.0/MODULE.bazel:7:6: WARNING: The bazel_gazelle Bazel module is still highly experimental and subject to change at any time. Only use it to try out bzlmod for now.
DEBUG: rules_go@0.33.0/MODULE.bazel:7:6: WARNING: The rules_go Bazel module is still highly experimental and subject to change at any time. Only use it to try out bzlmod for now.
INFO: Repository rules_java~5.5.0~toolchains~remote_java_tools instantiated at:
  callstack not available
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_shaoxixu/4d55580d1e210b29889ae47b4f95eda7/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
INFO: repository @rules_java~5.5.0~toolchains~remote_java_tools' used the following cache hits instead of downloading the corresponding file.
 * Hash '6efab6ca6e16e02c90e62bbd08ca65f61527984ab78564ea7ad7a2692b2ffdbb' for https://mirror.bazel.build/bazel_java_tools/releases/java/v12.0/java_tools-v12.0.zip
If the definition of 'repository @rules_java~5.5.0~toolchains~remote_java_tools' was updated, verify that the hashes were also updated.
ERROR: /private/var/tmp/_bazel_shaoxixu/4d55580d1e210b29889ae47b4f95eda7/external/bazel_tools/tools/jdk/BUILD:393:10: While resolving toolchains for target @bazel_tools//tools/jdk:proguard_whitelister: No matching toolchains found for types @bazel_tools//tools/python:toolchain_type.
To debug, rerun with --toolchain_resolution_debug='@bazel_tools//tools/python:toolchain_type'
If platforms or toolchains are a new concept for you, we'd encourage reading https://bazel.build/concepts/platforms-intro.
ERROR: Analysis of target '//grpc_ecosystem/protobuf/support:pagination_java_proto' failed; build aborted: 
INFO: Elapsed time: 26.695s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (54 packages loaded, 1029 targets configured)
    Fetching repository @rules_go~0.38.1~go_sdk~go_default_sdk; Downloading and extracting Go toolchain 14s
    Fetching /private/var/tmp/_bazel_shaoxixu/4d55580d1e210b29889ae47b4f95eda7/external/rules_java~5.5.0~toolchains~remote_java_tools; Extracting java_tools-v12.0.zip
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. git clone https://github.com/xushaoxiao/allinone-via-bazelmod.git
2. bazel build --enable_bzlmod ...

### Which operating system are you running Bazel on?

Mac os

### What is the output of `bazel info release`?

6.1.1

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

LCNC02GG727MD6R:allinone-via-bazelmod shaoxixu$ bazel info release
release 6.1.1-homebrew

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
LCNC02GG727MD6R:allinone-via-bazelmod shaoxixu$ git remote get-url origin
git@github.com:xushaoxiao/allinone-via-bazelmod.git

LCNC02GG727MD6R:allinone-via-bazelmod shaoxixu$ git rev-parse HEAD
d6535bc02673aa0dea0bb96fb39dfa14a3fce5c5
```

### Have you found anything relevant by searching the web?

Not found any issues in internet.

**Comment by xushaoxiao** [comment]
> Same here -- could you please reduce the repro case to a minimal one? Looking through your "all-in-one" repro is quite time consuming.

Hi Xudong @Wyverald , thanks for reaching out this issue. the name is "all in one", but currently this repo is small, only includes simple code, a few bazel target exists.

**Comment by Wyverald** [comment]
Closing as inactionable.
