### ISSUE TITLE
C++ Tutorial Bugs

### ISSUE THREAD

**Issue by themiller** [bazelbuild/bazel#1786]
I found a few issues that prevented the [C++ version of the tutorial](https://www.bazel.io/versions/master/docs/tutorial/cpp.html) from working out of the box:
1) The url to gtest no longer works: https://googletest.googlecode.com/files/gtest-1.7.0.zip produces a 404
2) The tutorial suggests that after adding the new_http_archive rule you can depend on `//external:gtest/main`, but this produces an error. I was able to use `@gtest//:main` to depend on the target and `new_http_archive rule //external:gtest` exists when querying for targets under external.

Output of bazel version:
```
Build label: 0.3.1-homebrew
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Aug 4 09:58:27 2016 (1470304707)
Build timestamp: 1470304707
Build timestamp as int: 1470304707
```

**Comment by laszlocsomor** [comment]
Thanks for reporting this!

1) was fixed by https://github.com/bazelbuild/bazel/pull/1688 / https://github.com/bazelbuild/bazel/commit/68b4a2ddac29f7f65fa097691ef495bd79dff2e4

2) Good catch! I'm fixing this.
