### ISSUE TITLE
[Mirror] JDK8 for macosx_aarch64

### ISSUE THREAD

**Issue by deekim** [bazelbuild/bazel#17870]
### Please list the URLs of the archives you'd like to mirror:

https://cdn.azul.com/zulu/bin/zulu8.62.0.19-ca-jdk8.0.332-macosx_aarch64.tar.gz

**Comment by sgowroji** [comment]
Please find the below mirror artifact
https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu8.62.0.19-ca-jdk8.0.332-macosx_aarch64.tar.gz
