### ISSUE TITLE
[Mirror] bazel-zig-cc v1.0.1

### ISSUE THREAD

**Issue by motiejus** [bazelbuild/bazel#17878]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/uber/bazel-zig-cc/releases/download/v1.0.1/v1.0.1.tar.gz

**Comment by sgowroji** [comment]
Hi @motiejus, Please find the below mirror artifact.
https://mirror.bazel.build/github.com/uber/bazel-zig-cc/releases/download/v1.0.1/v1.0.1.tar.gz
