### ISSUE TITLE
--remote_download_toplevel --nozip_undeclared_test_outputs does not download any undeclared test outputs for passing tests

### ISSUE THREAD

**Issue by VarunKoyyalagunta** [bazelbuild/bazel#17884]
### Description of the bug:

Prior to upgrading to  bazel 6.0.0, on a setup with remote execution, with `bazel test --remote_download_toplevel --nozip_undeclared_test_outputs` I'd see `test.outputs` populated with files. 
On bazel 6.0.0, `test.outputs` is always empty on passing tests.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

With remote execution, run `bazel test --remote_download_toplevel --nozip_undeclared_test_outputs`. Observe that test.outputs is empty on passing tests.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 6.0.0

### Any other information, logs, or outputs that you want to share?

If I remove `--nozip_undeclared_test_outputs`, I see `test.outputs/outputs.zip` on passing tests too
If I remove `--remote_download_toplevel`, I see the desired files in `test.outputs/*` on passing tests too

Adding `--experimental_remote_download_regex=".*"` didn't help.

**Comment by tjgq** [comment]
Note to future self: the minimal repro for https://github.com/bazelbuild/bazel/issues/17911 is also applicable to this issue.

**Comment by brentleyjones** [comment]
@tjgq My usual question 😅 is this cherry-pickable?

**Comment by tjgq** [comment]
I don't think it's going to be possible, sorry :( there are way too many other changes that this one depends on.

**Comment by brentleyjones** [comment]
That is unfortunate, as it was working in 5.x, but broke in 6.x, and will only work again in 7.0 ☹️.

**Comment by coeuvre** [comment]
I will try to work out a dedicated fix for 6.3.

**Comment by coeuvre** [comment]
@bazel-io fork 6.3.0
