### ISSUE TITLE
Bazel internal tools not buildable with mingw

### ISSUE THREAD

**Issue by ozio85** [bazelbuild/bazel#17899]
### Description of the bug:

In the latest pre-release, is seems like the internal tools like:

* launcher
* zipper

are no longer shipped with the binary, and needs to be built from source.

However, this causes the Windows builds to break when MSVC is not used as host compiler. E.g. when mingw is used, it [correctly] complains on missing header includes, e.g. when compiling `strings.cc`:

```
In file included from external/bazel_tools/src/main/cpp/util/strings.cc:21:
external/bazel_tools/src/main/cpp/util/strings.h: In function 'std::__cxx11::string blaze_util::ToString(const T&)':
external/bazel_tools/src/main/cpp/util/strings.h:33:22: error: 'oss' has incomplete type
   std::ostringstream oss;
                      ^~~
In file included from external/mingw_windows/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/memory:72,
                 from external/bazel_tools/src/main/cpp/util/strings.h:17,
                 from external/bazel_tools/src/main/cpp/util/strings.cc:21:
external/mingw_windows/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/iosfwd:104:11: note: declaration of 'std::ostringstream' {aka 'class std::__cxx11::basic_ostringstream<char>'}
     class basic_ostringstream;
           ^~~~~~~~~~~~~~~~~~~
```

Since `<sstream>` is not included.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build anything on Windows and use mingw as default.

### Which operating system are you running Bazel on?

Windows

### What is the output of `bazel info release`?

7.0.0-pre.20230306.4

**Comment by sgowroji** [comment]
Hi @ozio85, Could you please provide complete steps to reproduce the above issue with sample code changes. Thanks !!
