### ISSUE TITLE
A shallow clone of our repository is 496Mb!!!

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1789]
A bare copy of our repository makes it to 360Mb, the extraneous space is due to the git cache. It makes a shallow clone impossible over poor network connectivity.

This is due to third_party which is 323Mb, 218 of those for the protobuf repository.
Next by size are java compiler (28Mb), grpc (15Mb) and hazelcast (14Mb)

A thing to start: there is 2 binary of each proto compiler checked in! one inside third_party/protobuf/3.0.0 and another directly in third_party/protobuf.

**Comment by ahumesky** [comment]
The extra proto compilers are temporary while we update to 3.0.0. I'm waiting on the windows dll to be added, then the ones in third_party/protobuf can be deleted.

**Comment by damienmg** [comment]
Normally we should do those change atomically and not have 2 versions sit for a long time. Even with that one set of compiler is 80Mb that's a lot on a git repository, we should figure something out.

**Comment by damienmg** [comment]
This is no longer under investigation:
  protoc is too big, we will kill it soon for the double one and we will kill the other binary with Klaus plan. Closing this investigation,
