### ISSUE TITLE
Documentation missing for protoc-linux-arm32.exe

### ISSUE THREAD

**Issue by jalajc** [bazelbuild/bazel#1790]
On bazel->third_party-> protobuf->readme.md
the line reads. 
> How to update the binaries other than protoc-linux-x86_64.exe and protoc-linux-arm32.exe
While `protoc-linux-x86_64.exe` steps are covered. I don't find what to do in case of `protoc-linux-arm32.exe`. Documentation seems to be missing.

**Comment by laszlocsomor** [comment]
@lberki: could you take a look please? You added the specific steps for x86_64, maybe you know for arm32 too?

**Comment by lberki** [comment]
Do we have `protoc-linux-arm32.exe`? It doesn't seem to be present at least under `third_party/protobuf`. In fact, there isn't any file in our source tree whose names contains `arm32`.

**Comment by laszlocsomor** [comment]
Indeed. An older version of the README mentioned that file, maybe it used to exist. Anyway, we can update the README. I'll send you a change.

**Comment by lberki** [comment]
Thanks :)

**Comment by laszlocsomor** [comment]
Done. Will be pushed to GH later today.
