### ISSUE TITLE
Syntax Error due to Version Mismatch between bazel and Python version

### ISSUE THREAD

**Issue by patty641** [bazelbuild/bazel#17900]
### Description of the bug:

Hi, 
I'm currently using Python 3.6.8 and bazel 4.2.1 on centOS 7 , And upon running the bazel test command on my Project, I encountered a few issues which were majorly regarding missing python modules or a syntax error in importing the said modules.
The Major issue is that the the module "typing-extensions", even though it is installed cannot be imported during compile time. The Error seems to be due to the version mismatch between bazel,python and centOS and I tried looking through the documentation on bazel but I couldn't find a proper mapping for bazel's releases to python releases. Is there such a list of requirements available for different bazel versions? 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

-centOS7
-Python 3.6.8 
- bazel 4.2.1

### Which operating system are you running Bazel on?

centOS 7

### What is the output of `bazel info release`?

4.2.1

### Have you found anything relevant by searching the web?

I tried looking through the documentation on bazel but I couldn't find a proper mapping for bazel's releases to python releases.

**Comment by sgowroji** [comment]
Hi @patty641, Can you provide minimal steps to reproduce the above issue with any Python sample code. Thanks!

**Comment by patty641** [comment]
I'm using python 3.6.8 on centOS7, 
->yum install bazel4
-> cd application
-> bazel test application

**Comment by meteorcloudy** [comment]
Can you try to upgrade Bazel to a more recent version?

**Comment by patty641** [comment]
on centOS7 bazel 4.x seems to be the latest version available in the yum repo.

**Comment by patty641** [comment]
Are you saying that bazel 6 or newer versions are compatible with centOS7, because if not then it's not feasible for me to upgrade bazel version over 4.2.1?
I've tried installing bazel 6 on centOS7 but it doesn't seem to install.
