### ISSUE TITLE
Bazel build and query invalidates cache

### ISSUE THREAD

**Issue by jakeleventhal** [bazelbuild/bazel#17914]
### Description of the bug:

The cache seems to be invalidated upon each run when running on an `aspect/rules_js` `js_run_devserver`. local reproduction can be done without ibazel by running
```sh
bazel build <js_run_devserver_target>
bazel query <js_run_devserver_target>
bazel build <js_run_devserver_target>
bazel query <js_run_devserver_target>
```

The cache is invalidated between each of these commands. However, if i replace `bazel query` with `bazel cquery`, it seems to work just fine.

The analysis cache should not be discarded when running bazel query in this case. `bazel cquery` considers select statements but `bazel query` does not. That seems to be the cause.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See above.

### Which operating system are you running Bazel on?

macOS 13.3

### What is the output of `bazel info release`?

release 6.1.0

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel-watcher/issues/594

**Comment by gregestren** [comment]
@sdtwigg for triage.

**Comment by sdtwigg** [comment]
What does your bazelrc look like?

In bazelrc semantics, query does not inherit from build. (cquery does and you not seeing this behavior for cquery tempts me to think this is a bazelrc issue.)
You would need to either include an equivalent line for query for build lines (when the options are relevant).

If your Bazel version is after the work in https://github.com/bazelbuild/bazel/issues/3054, you can now use `common` to enthusiastically apply options. (The old behavior of `common` was moved to `always`)

**Comment by jakeleventhal** [comment]
I've moved off bazel for my project. It's going to be pretty difficult to reproduce. Best to assign to someone else or close the issue altogether.
