### ISSUE TITLE
cc_shared_library causes c++ files to be compiled multiple times

### ISSUE THREAD

**Issue by cameron-martin** [bazelbuild/bazel#17927]
### Description of the bug:

If some cc_test or cc_binary targets consume a library by declaring a dependency on a cc_shared_library whereas some do not, this causes the C++ files in these libraries to be compiled multiple times. I would expect this mixed way of consuming the library to only cause extra linking, but reuse object files.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

A reproducer is here: https://github.com/cameron-martin/bazel-shared-library-redundant-compilation

Information is in the README on how to run it

### Which operating system are you running Bazel on?

Ubuntu 22.04

### What is the output of `bazel info release`?

I've tested this on both 6.1.0 and the latest 7.0.0 release, but more can be easily tested via the reproducer.

**Comment by fmeum** [comment]
If you build with `-s`, you can see that the two actions differ in the `-fPIC` flag: The library is built both in a PIC (for `cc_shared_library`) and a non-PIC (for `cc_binary`, presumably) version. You can use `--force_pic` to disable the generation of the non-PIC version, which also solves the rebuild for me.

**Comment by cameron-martin** [comment]
Thanks for investigating.

Turns out that simply building `//:lib causes this duplicate compilation, since this builds both a `.so` (with PIC) and a `.a` (without PIC). It makes sense why it's happening, but it does seem like a bit of a footgun.
