### ISSUE TITLE
method registerPostProcessAndSigningActions() is messy

### ISSUE THREAD

**Issue by hermione521** [bazelbuild/bazel#1792]
https://github.com/bazelbuild/bazel/blob/180d1b56b8aea8fab974cfa57e9182598990710c/src/main/java/com/google/devtools/build/lib/rules/objc/ReleaseBundlingSupport.java#L435
This action is too long and messy, and makes it hard to debug darwin sandbox. Please separate it into several actions.

**Comment by aragos** [comment]
It is a messy action but there is a reason for doing so many things in one place: If we split it then we'd have to zip/unzip the IPA multiple times which hurts build performance. I don't currently see a way to simplify the action without negative effects.
