### ISSUE TITLE
[Mirror] bazel-gazelle 0.30

### ISSUE THREAD

**Issue by tyler-french** [bazelbuild/bazel#17937]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.30.0/bazel-gazelle-v0.30.0.tar.gz

**Comment by sgowroji** [comment]
Please find the below mirror artifacts
1. https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.30.0/bazel-gazelle-v0.30.0.tar.gz
