### ISSUE TITLE
Bazel 5.3.0 `//tools/osx:xcode-locator-genrule` fails with Xcode 14.3

### ISSUE THREAD

**Issue by adamjstewart** [bazelbuild/bazel#17958]
### Description of the bug:

Bazel 5.3.0 fails to build with Xcode 14.3:
```
ERROR: /private/var/folders/jv/cgkfvslj6nq1l7cw0c8c_8gm0000gn/T/Adam/spack-stage/spack-stage-bazel-5.3.0-ltrek6pv3ubac62sal2ugrqkqx3azrnb/spack-src/tools/osx/BUILD:36:8: Executing genrule //tools/osx:xcode-locator-genrule failed: (Exit 1): bash failed: error executing command 
...
ld: file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_macosx.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try to build bazel 5.3.0 with Xcode 14.3. I'm using Spack, but it should be possible to reproduce from a source install.

### Which operating system are you running Bazel on?

macOS 13.3 (arm64)

### What is the output of `bazel info release`?

5.3.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

With Spack

### Have you found anything relevant by searching the web?

Found an ancient reference to this bug at https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/build-managers/bazel/bazel_4/default.nix#L212 (added in https://github.com/NixOS/nixpkgs/pull/106984). I'll try that patch and see if it solves my issue.

### Any other information, logs, or outputs that you want to share?

* [build log](https://github.com/bazelbuild/bazel/files/11141050/spack-build-out.txt)
* [build env](https://github.com/bazelbuild/bazel/files/11141054/spack-build-env-mods.txt)

This problem occurs with bazel 5.3.0 but not 6.1.1. The bug occurs with Apple Clang 14.0.3 but not 14.0.0. I need 5.3.0 to build TF.

**Comment by keith** [comment]
I think cherry picking https://github.com/bazelbuild/bazel/pull/17451 might fix this

**Comment by adamjstewart** [comment]
Worked like a charm, thanks for the quick fix!

**Comment by brentleyjones** [comment]
@meteorcloudy Should there be a 5.x patch release with that cherry-pick?

**Comment by keertk** [comment]
Sure, sounds good.

**Comment by keertk** [comment]
@bazel-io fork 5.4.1
