### ISSUE TITLE
Bazel crashes with bzlmod lockfile

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#17959]
### Description of the bug:

https://github.com/bazelbuild/bazel/issues/14554#issuecomment-1492218704

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In this project [lockfiletest.zip](https://github.com/bazelbuild/bazel/files/11141537/lockfiletest.zip) run `./repro.sh`

**Comment by keith** [comment]
cc @SalmaSamy

**Comment by SalmaSamy** [comment]
The fix is included in [this commit](https://github.com/bazelbuild/bazel/commit/23518b8df6bee3ca35202d942bfbd041ba7ca8f8)
