### ISSUE TITLE
bazel-__main__ symlink is created but not removed by bazel clean

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1795]
A recent change seems to have modified the name of the convenience symlink to the execroot (use to be `bazel-__dir__` but it is now `bazel-__workspace_name__`). This symlink is not deleted on `bazel clean`

repro (from bazel repo, using a bazel compiled at HEAD):
```
bazel build //tools:srcs
bazel clean
```

It was not present in 0.3.1

**Comment by kchodorow** [comment]
I still don't think this is a p1 (who cares, and if they do there's a workaround), but I've got a fix out for it.
