### ISSUE TITLE
deploy a specific binary

### ISSUE THREAD

**Issue by cnsgsz** [bazelbuild/bazel#1796]
I currently copy over the whole bazel-bin directory to another machine where one of the binary is run. The network is slow, so I prefer to just copy over the 1 binary and the so file it depends on. is there an easy way to do that? I guess I can use static linking or objdump the binary to find what so it depends on etc, but am curious if there is a better way.

**Comment by laszlocsomor** [comment]
What language is the binary written in?

For `java_binary` target `//foo/java/mypkg:bin`, you can build *targetname*_deploy.jar, i.e. `//foo/java/mypkg:bin_deploy.jar`

For any `xx_binary` target `//foo:mybin` you can copy just the `bazel-out/foo/mybin.runfiles` directory (only works on Linux and Mac, not yet Windows). Be aware that this library contains symlinks, so make sure you use `cp -LR`.

Please reopen if this doesn't work or you have more questions.

**Comment by cnsgsz** [comment]
it works. thanks!
