### ISSUE TITLE
Fedora 38: failed build

### ISSUE THREAD

**Issue by sergey-safarov** [bazelbuild/bazel#17967]
### Description of the bug:

failed build on Fedora 38 aarch

```
[root@sbc-stage-a0 SPECS]# cat /etc/os-release 
NAME="Fedora Linux"
VERSION="38 (Container Image Prerelease)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Container Image Prerelease)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Container Image"
VARIANT_ID=container
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I use RPM packaing and cannot provide minimal example.

### Which operating system are you running Bazel on?

Fedora 38

### What is the output of `bazel info release`?

building from scratch

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

NA

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
I compiling 6.1.1 release
```

### Any other information, logs, or outputs that you want to share?

Build error message attached
[build-error.txt](https://github.com/bazelbuild/bazel/files/11145430/build-error.txt)

**Comment by sgowroji** [comment]
Hi @sergey-safarov, Can you provide list of resources & minimal steps followed to reproduce the above error. Thanks!

**Comment by sergey-safarov** [comment]
I can create the docker container with the built environment and one command on how to reproduce it.
Is it works for you?

**Comment by sgowroji** [comment]
Hi @sergey-safarov, It would be good if we can reproduce the same error at our end. Thanks!

**Comment by sergey-safarov** [comment]
Could you try to execute two commands
1) start container with build environment
```
docker run -it --network host safarov/bazel6-build-error
```
2) start build process
```
cd /root/rpmbuild/SPECS/ && rpmbuild -ba bazel.spec
```

**Comment by sergey-safarov** [comment]
I have successfully build `7.0.0-pre.20230530.3` on Fedora 38
