### ISSUE TITLE
[6.2.0] cc_proto_aspect related cherry-picks

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#17971]
Please cherry pick https://github.com/bazelbuild/bazel/commit/70ce8378638290295e17fb62e735a239f22672e6 and https://github.com/bazelbuild/bazel/commit/2aa06cf227fe349195191107286167035f0c5431 into 6.2

**Comment by keertk** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/17979 and https://github.com/bazelbuild/bazel/pull/17980
