### ISSUE TITLE
Protoc failed (Segmentation Fault) during Build on centOS 8

### ISSUE THREAD

**Issue by patty641** [bazelbuild/bazel#17982]
### Description of the bug:

While running the bazel test command, Every test fails as there is a segmentation fault related to protoc. I've tried running the command with and without a locally installed protobuf library.

Found a similar issue #14273 and so I upgraded my bazel version to 4.2.2. II've installed bazel on my system manually in a similar method as described in this article : https://iq.opengenus.org/install-specific-version-of-bazel/

`(Segmentation fault): protoc failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc '--cpp_out=bazel-out/k8-fastbuild/bin'
`

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a VM operating on el8, Python 3.7.11 and using bazel version 4.2.2. 

### Which operating system are you running Bazel on?

centOS 8 

### What is the output of `bazel info release`?

release 4.2.2

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/14273
https://github.com/bazelbuild/bazel/issues/2353

**Comment by sgowroji** [comment]
Hi @patty641, Could you please provide complete steps to reproduce the above error. Thanks!

**Comment by patty641** [comment]
1. Create a VM with the operating system centOS 8.
2. make a directory for your application "hello".
3. Inside this directory "hello" , Install bazel using the following steps :
    wget https://github.com/bazelbuild/bazel/releases/download/4.2.2/bazel-4.2.2-installer-linux-x86_64.sh
    chmod +x bazel-4.2.2-installer-linux-x86_64.sh
    ./bazel-4.2.2-installer-linux-x86_64.sh --user
    cp -r  ~/bin/bazel* /usr/bin/
4. Inside "hello" directory :
`bazel test hello`

**Comment by meteorcloudy** [comment]
@patty641 Can you please upgrade to newer version of Bazel, e.g. Bazel 6? You can use [Bazelisk](https://github.com/bazelbuild/bazelisk/releases) to fetch the latest release easily. Also, centos 8 isn't an officially supported platfrom.

**Comment by patty641** [comment]
Is centos 8.5/ rhel 8.5 officially supported?
