### ISSUE TITLE
ci.bazel.io is very red

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#1799]
Likely due to https://github.com/bazelbuild/bazel/commit/82d43279f93d95e4c41b4bc598a3cc05ddd1ae1a

**Comment by meteorcloudy** [comment]
For tensorflow, the reason it fails is that this [genrule ](https://github.com/tensorflow/tensorflow/blob/master/jpeg.BUILD#L74)doesn't work anymore after the execution root change. //cc @kchodorow

**Comment by meteorcloudy** [comment]
I think it's going to take a long time to adapt this change in every broken repo, maybe rollback first?

**Comment by kchodorow** [comment]
On it.

**Comment by laszlocsomor** [comment]
Thanks! Rolling back in the internal depot now. I'll push to GH when it's submitted.

**Comment by laszlocsomor** [comment]
Pushed, waiting for CI to pick it up.

**Comment by damienmg** [comment]
Only android test are failing now closing this one.
