### ISSUE TITLE
generate_workspace does not pickup http_proxy or https_proxy settings

### ISSUE THREAD

**Issue by jylin** [bazelbuild/bazel#1800]
Thus, it fails to run/fetch anything if you are behind a proxy. Optionally or alternatively, it could use .m2/settings.xml's proxy settings to configure proxies if that's easier.

**Comment by jin** [comment]
Closing this as generate_workspace is no longer maintained. Please open Maven-related issues on [rules_jvm_external](https://github.com/bazelbuild/rules_jvm_external) instead. 

rules_jvm_external supports `http_proxy` and `https_proxy`.
