### ISSUE TITLE
Make --profile path unique by default

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/bazel#18006]
### Description of the feature request:

It is good to see that `--generate_json_trace_profile` is on by default for all build-like commands. What's unfortunate is that the JSON profiles are written, unconditionally, to a file named `command.profile.gz`. This means that a build will clobber the profile of a previous build.

The reason this is unfortunate is because when a user wants to report a "my build was slow!" situation, it is *very* likely that they have already run a second build and that the profile for the slow build is lost, nullifying all chances of troubleshooting the problem.

It'd be ideal if Bazel stamped the profiles under the output base, just like it does with the `java.log` files. This could be via a timestamp or via the invocation ID of the build or both. This should possibly also cap the number of log files stored to prevent uncontrolled disk growth.

### What underlying problem are you trying to solve with this feature?

Have the ability of obtaining profiles from users that report slow builds, without asking them to re-run the build. Rerunning a build is unlikely to showcase the same problems they previously experienced, so ensuring the profiles remain available is critical.

### Which operating system are you running Bazel on?

N/A

### What is the output of `bazel info release`?

6.1.1

**Comment by brentleyjones** [comment]
I would _love_ to see this changed, along with an easy way to collect the last `n` profiles.
