### ISSUE TITLE
[Mirror] rules_go and gazelle deps

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#18001]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/golang/tools/archive/refs/tags/v0.7.0.zip
https://github.com/golang/sys/archive/refs/tags/v0.6.0.zip
https://github.com/golang/xerrors/archive/04be3eba64a22a838cdb17b8dca15a52871c08b4.zip
https://github.com/protocolbuffers/protobuf-go/archive/refs/tags/v1.30.0.zip
https://github.com/golang/protobuf/archive/refs/tags/v1.5.3.zip
https://github.com/mwitkow/go-proto-validators/archive/refs/tags/v0.3.2.zip
https://github.com/gogo/protobuf/archive/refs/tags/v1.3.2.zip
https://github.com/googleapis/go-genproto/archive/6ac7f18bb9d5eeeb13a9f1ae4f21e4374a1952f8.zip
https://github.com/googleapis/googleapis/archive/83c3605afb5a39952bf0a0809875d41cf2a558ca.zip
https://github.com/golang/mock/archive/refs/tags/v1.7.0-rc.1.zip

**Comment by sgowroji** [comment]
Please find the below mirror artifacts

1. https://mirror.bazel.build/github.com/golang/tools/archive/refs/tags/v0.7.0.zip
2. https://mirror.bazel.build/github.com/golang/sys/archive/refs/tags/v0.6.0.zip
3. https://mirror.bazel.build/github.com/golang/xerrors/archive/04be3eba64a22a838cdb17b8dca15a52871c08b4.zip
4. https://mirror.bazel.build/github.com/protocolbuffers/protobuf-go/archive/refs/tags/v1.30.0.zip
5. https://mirror.bazel.build/github.com/golang/protobuf/archive/refs/tags/v1.5.3.zip
6. https://mirror.bazel.build/github.com/mwitkow/go-proto-validators/archive/refs/tags/v0.3.2.zip
7. https://mirror.bazel.build/github.com/gogo/protobuf/archive/refs/tags/v1.3.2.zip
8. https://mirror.bazel.build/github.com/googleapis/go-genproto/archive/6ac7f18bb9d5eeeb13a9f1ae4f21e4374a1952f8.zip
9. https://mirror.bazel.build/github.com/googleapis/googleapis/archive/83c3605afb5a39952bf0a0809875d41cf2a558ca.zip
10. https://mirror.bazel.build/github.com/golang/mock/archive/refs/tags/v1.7.0-rc.1.zip
