### ISSUE TITLE
[Mirror] bazelbuild/rules_nodejs 4.0.0 as dependency of bazelbuild/buildtools 6.1.0

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/bazel#18013]
### Please list the URLs of the archives you'd like to mirror:

* https://github.com/bazelbuild/rules_nodejs/releases/download/4.0.0/rules_nodejs-4.0.0.tar.gz
    * This is asset/artifact attached to https://github.com/bazelbuild/rules_nodejs/releases/tag/4.0.0 and so it should be stable.

**Comment by sgowroji** [comment]
Please find the below mirror artifact
https://mirror.bazel.build/github.com/bazelbuild/rules_nodejs/releases/download/4.0.0/rules_nodejs-4.0.0.tar.gz

**Comment by beasleyr-vmw** [comment]
Awesome, thanks! 🎉
