### ISSUE TITLE
Cannot do full build with iOS 10

### ISSUE THREAD

**Issue by eagleonhill** [bazelbuild/bazel#1801]
the sdk name should be iphoneos10.0 or iphonesimulator10.0 but .0 is stripped when parsing version.

xcrun cannot find iphoneos10 as the sdk.

blaze --ios_sdk_version=10.0 --xcode_version=8 ...

**Comment by c-parsons** [comment]
FWIW, in the interim, auto-detection for current system-default SDK version and xcode version should be working, so if you only have xcode 8 installed, you should be able to omit those flags and just have things work.

**Comment by c-parsons** [comment]
Fixed several weeks ago
