### ISSUE TITLE
Error in Building

### ISSUE THREAD

**Issue by shanjin2014** [bazelbuild/bazel#18037]
### Problem description (include actual vs expected text, if applicable):

every rule of type py_binary implicitly depends upon the target '//:package_license', but this target could not be found because of: error loading package '': Label '//tools/build_defs/license:license.bzl' is invalid because 'tools/build_defs/license' is not a package; perhaps you meant to put the colon here: '//:tools/build_defs/license/license.bzl'?

Any suggestion for how to resolve it?

**Comment by sgowroji** [comment]
Hi @shanjin2014, Could you please share the doc link,  which you are referring. Thanks!
