### ISSUE TITLE
Implement workspace status retrieval

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#1804]
Implement a way to stamp workspace status information into genrules.

This is the intention behind https://github.com/bazelbuild/bazel/issues/1758

**Comment by damienmg** [comment]
using stamp = 1 in the genrule should make the info file avaiable in the genrules. At least we do that in Bazel build for releases

**Comment by laszlocsomor** [comment]
That's not enough, unfortunately, see https://github.com/bazelbuild/bazel/issues/1758#issuecomment-248294048 and https://github.com/bazelbuild/bazel/issues/1758#issuecomment-248535743

**Comment by damienmg** [comment]
Well then the issue title is misleading. What is really needed is a genrule that can declare a dependencies on some stuff from the workspace status.

**Comment by laszlocsomor** [comment]
Could you be more specific? What would that look like, would the `genrule.srcs` list some file? That's not how it works internally.

I believe this FR is about noticing that your workspace status changed even when your files haven't, e.g. you build, then git commit, then build again. In the second build the stamped genrule should be rebuilt so it can read the new commit ID from the workspace status, for example.

**Comment by ulfjack** [comment]
We don't do that internally, though. If only the volatile workspace info changes, then we don't rebuild (unless some other input file also changes). That is WAI.

**Comment by laszlocsomor** [comment]
For the record, semantics of volatile vs. stable status are here: https://stackoverflow.com/questions/47622645/how-to-run-a-shell-command-at-analysis-time-in-bazel/47630130#47630130

**Comment by meisterT** [comment]
Closing as WAI.
