### ISSUE TITLE
Uncaught exception in CppLinkActionBuilder

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#1806]
See https://groups.google.com/forum/#!msg/bazel-discuss/YpGzj5e6J5A/WXWEOZwgAgAJ

**Comment by laszlocsomor** [comment]
@calpeyser - Are you the right assignee?

**Comment by mhlopko** [comment]
I guess I should fix this :)

**Comment by mhlopko** [comment]
(status update: asked Michiel for project sources so I can reproduce)

**Comment by mhlopko** [comment]
Closing due to the lack of information.
