### ISSUE TITLE
CC Toolchain Features Treated As Disabled When They Contain No Flags

### ISSUE THREAD

**Issue by t-rad679** [bazelbuild/bazel#18064]
If this is intended behavior or if I'm missing something forgive me, but this seemed pretty odd:

For patchset 4 of this [AOSP CL](https://android-review.git.corp.google.com/c/platform/prebuilts/clang/host/linux-x86/+/2523415), the test `test_cross_dso_not_added_when_static_binary` failed when building for Linux. In other words, the `with_features` clause of `android_cfi_cross_dso` did not appear to function as I expected. I looked more closely, and what I found was that, when building for host oses (in this case, Linux. Windows and Darwin are not supported by CFI at this time for Android), no flags are added to the `static_executable`  feature. This is the only difference I could find between building for linux vs building for Android (in which case the test passed), so I am inferring that this difference is what caused the `with_features` clause to not evaluate as expected.

Fortunately, I was able to work around the issue given some of the other constraints of my use case, but I still wanted to bring this to your attention in case it wasn't intended behavior.

**Comment by buildbreaker2021** [comment]
Thanks for the report, I think this is WAIT, but will take a closer look.
