### ISSUE TITLE
repository_rule.local undoc'd?

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#1807]
repository_rule() supports a local=True argument. I can't find what that means.

**Comment by laszlocsomor** [comment]
It's documented:
https://www.bazel.io/versions/master/docs/skylark/lib/globals.html#repository_rule.local

https://github.com/bazelbuild/bazel/blob/c9bc051f32b0d153110863e983749420200d000c/src/main/java/com/google/devtools/build/lib/bazel/repository/skylark/SkylarkRepositoryModule.java#L87

Where did you check?

**Comment by hanwen** [comment]
you're right.

i was looking around on https://www.bazel.io/versions/master/docs/skylark/repository_rules.html

there is an example

 local_repository = repository_rule(
    implementation=_impl,
    local=True,
    attrs={"path": attr.string(mandatory=True)})

but it doesn't mention what 'local' is about. Maybe remove that? Also, a link to 
https://www.bazel.io/versions/master/docs/skylark/lib/globals.html#repository_rule from 
the top of https://www.bazel.io/versions/master/docs/skylark/lib/repository_ctx.html would be nice.

**Comment by laszlocsomor** [comment]
> but it doesn't mention what 'local' is about. Maybe remove that?

Will do. It's indeed just confusing here.

> Also, a link to 
https://www.bazel.io/versions/master/docs/skylark/lib/globals.html#repository_rule from 
the top of https://www.bazel.io/versions/master/docs/skylark/lib/repository_ctx.html would be nice.

Will do that too.

**Comment by laszlocsomor** [comment]
repository_rule.local is now documented:
https://docs.bazel.build/versions/master/skylark/lib/globals.html#repository_rule
https://docs.bazel.build/versions/master/skylark/repository_rules.html#when-is-the-implementation-function-executed
