### ISSUE TITLE
linker_param_file only added to command line if it starts with "@"

### ISSUE THREAD

**Issue by Taldoras** [bazelbuild/bazel#18074]
### Description of the bug:

The tasking compiler for c/c++ requires a different format to pass a param file (--options-file=%{linker_param_file} or -f %{linker_param_file}.
When I add a custom linker_param_file_feature to a custom cc_toolchain_config, it will only be added to the command line if the flag starts with "@".

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a custom cc_toolchain_config and add a custom "linker_param_file" feature. 
Add a flag with `["--option-file=%{linker_param_file}"]`.
Build a c/cpp file with the custom toolchain configured. When the linker is being called, the flag wont be added. 
Now, add an @ at the beginning of the flag (e.g.  `["@ --option-file=%{linker_param_file}"]`.) and build again. The flag should now be shown in the command line.

### Which operating system are you running Bazel on?

Windows 11

### What is the output of `bazel info release`?

release 6.1.1

**Comment by brentleyjones** [comment]
@bazel-io flag

**Comment by iancha1992** [comment]
@bazel-io fork 6.5.0

**Comment by iancha1992** [comment]
@bazel-io fork 7.1.0

**Comment by meteorcloudy** [comment]
@comius Can you help backport the fixes?

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.1.0 RC1](https://releases.bazel.build/7.1.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!
