### ISSUE TITLE
repository_ctx missing methods. 

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#1808]
hanwen@hanwen:/tmp/rules_go$ git show HEAD|head

the repository_rule ctx doesn't work as documented

commit 4c73b9cb84c1f8e32e7df3c26e237439699d5d8c
Author: Yuki Yugui Sonoda yugui@yugui.jp
Date:   Wed Sep 21 13:38:37 2016 +0900

```
Bump version (#109)
```

diff --git a/README.md b/README.md
index 495bd5d..159a61a 100644
--- a/README.md
+++ b/README.md

hanwen@hanwen:/tmp/rules_go$ bazel build external:com_github_golang_glog
.
ERROR: /tmp/rules_go/WORKSPACE:7:1: in new_go_repository rule //external:com_github_golang_glog: 
Traceback (most recent call last):
    File "/tmp/rules_go/WORKSPACE", line 7
        new_go_repository(name = 'com_github_golang_glog')
    File "/tmp/rules_go/go/def.bzl", line 1028, in _new_go_repository_impl
        _go_repository_impl(ctx)
    File "/tmp/rules_go/go/def.bzl", line 1006, in _go_repository_impl
        ctx.path(ctx.attr._fetch_repo)
Type ctx has no function path(InputFileConfiguredTarget).
ERROR: Analysis of target '//external:com_github_golang_glog' failed; build aborted.
INFO: Elapsed time: 36.453s

hanwen@hanwen:/tmp/rules_go$ bazel version
Build label: 0.3.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 29 09:09:52 2016 (1469783392)
Build timestamp: 1469783392
Build timestamp as int: 1469783392

I'm seeing the same kind of problems with my own experiments.

When I print the type of the "ctx" argument, it prints "ctx". I can call ctx.action; does this get a RuleActionContext ?

**Comment by damienmg** [comment]
As discussed on Hangouts:
building //external: labels is not supported, the way to go should be bazel build @com_github_golang_glog//...

Downgrading to non release blocker as this is not a regression. Still a bug we need to fix for 0.4
