### ISSUE TITLE
Apple CC toolchain broken for objc

### ISSUE THREAD

**Issue by cpsauer** [bazelbuild/bazel#18091]
Howdy wonderful Bazelers 🤠,

I was just moving my team to the latest bazel rolling, and Objective-C compilation seems to be broken.

Attempts to build objc code yield:
```
Traceback (most recent call last):
        File "/virtual_builtins_bzl/common/objc/objc_library.bzl", line 59, column 52, in _objc_library_impl
        File "/virtual_builtins_bzl/common/objc/semantics.bzl", line 32, column 13, in _check_toolchain_supports_objc_compile
Error in fail: Compiling objc_library targets requires the Apple CC toolchain which can be found here: https://github.com/bazelbuild/apple_support
```

That's true with the latest rules_apple and apple_support commit and release. Things last worked with bazel rolling release `20230322.4` but not the latest rolling (`7.0.0-pre.20230405.2`) nor it's predecessor `7.0.0-pre.20230330.3` , so the issue is between `7.0.0-pre.20230322.4` and  `7.0.0-pre.20230330.3`. (Hence why I'm filing the issue here rather than rules_apple) 

Minimal example: grab [this](https://github.com/bazelbuild/bazel/files/11226607/apple-cc-toolchain.zip) with bazelisk and run `bazel build :example`.

I'm wondering if it might have something to do with [this stuff](https://github.com/bazelbuild/bazel/commit/a50cca561fe0a77c3750101e505171ddcc16db72).
Tagging, @keith, if that's ok, since he's magical 🧙🏻‍♂️.

Thanks so much for all you do!
Chris

**Comment by keith** [comment]
you need the configuration specified in the README as well https://github.com/bazelbuild/apple_support#toolchain-setup

**Comment by cpsauer** [comment]
Yup. Dead on. Thanks, @Keith--and sorry.

**Comment by keith** [comment]
no prob!

**Comment by keith** [comment]
once we can use automatic toolchain resolution that won't be the case which is nice!

**Comment by cpsauer** [comment]
Thanks, again. Really appreciate you, @Keith.

(While I hope I'm the last person to blindly upgrade and then make this dumb mistake, if auto toolchain resolution is a ways off, what do you think about adding that link to the warning message?)

**Comment by keith** [comment]
https://github.com/bazelbuild/bazel/pull/18092
