### ISSUE TITLE
How to exclusively use clang instead of gcc while running the "bazel test" command

### ISSUE THREAD

**Issue by patty641** [bazelbuild/bazel#18096]
### Description of the bug:

I'm compiling an application using bazel, on my system I have an old gcc (which the application doesn't support) and a newer version of clang (supported by the application), and I want to explicitly use clang but, while running the command "bazel test application" I get the error :
#error "GCC 9.2 or higher is required."

How can I configure the bazel test command in a way to make it explicitly use clang instead of gcc?

just for reference of versions being used :
`clang --version
clang version 14.0.6 (Red Hat 14.0.6-1.module+el8.7.0+15816+ec020e8f)`
`gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-3)`

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

-Create a VM with the operating system Rhel8.5
-make a directory for your application "hello".
-Inside this directory "hello" , Install bazel using the following steps :
wget https://github.com/bazelbuild/bazel/releases/download/4.2.2/bazel-4.2.2-installer-linux-x86_64.sh
chmod +x bazel-4.2.2-installer-linux-x86_64.sh
./bazel-4.2.2-installer-linux-x86_64.sh --user
cp -r ~/bin/bazel* /usr/bin/
-Inside "hello" directory :
bazel test hello

### Which operating system are you running Bazel on?

Rhel 8.5

### What is the output of `bazel info release`?

release 6.1.1

**Comment by Pavank1992** [comment]
Hi @patty641, I could see you are using bazel-4.2.2 `wget https://github.com/bazelbuild/bazel/releases/download/4.2.2/bazel-4.2.2-installer-linux-x86_64.sh`. Could you please use latest version of bazel as suggested [in this issue](https://github.com/bazelbuild/bazel/issues/17982#issuecomment-1503208853)?
