### ISSUE TITLE
[Mirror]  zig 0.11.0-dev.2619+bd3e248c7 (missed windows x86_64)

### ISSUE THREAD

**Issue by marler8997** [bazelbuild/bazel#18116]
### Please list the URLs of the archives you'd like to mirror:

https://ziglang.org/builds/zig-windows-x86_64-0.11.0-dev.2619+bd3e248c7.zip

**Comment by sgowroji** [comment]
Please find the below mirror artifact
1.https://mirror.bazel.build/ziglang.org/builds/zig-windows-x86_64-0.11.0-dev.2619+bd3e248c7.zip
