### ISSUE TITLE
repository_rule allows declaring name attribute 

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#1811]
repository_rule allows defining a "name" attribute, but apparently bazel already provides a name attribute, which leads to confusing error messages.

hanwen@hanwen:~/vc/rr$ bazel fetch @bower//...
ERROR: /home/hanwen/vc/rr/WORKSPACE:5:1: //external:bower: missing value for mandatory attribute 'name' in 'npm_binary' rule.
ERROR: error loading package 'external': Could not load //external package.

hanwen@hanwen:~/vc/rr$ cat WORKSPACE
load("//tools/bzl:js.bzl", "npm_binary")

npm_binary(
  name = "bower",
)

hanwen@hanwen:~/vc/rr$ cat tools/bzl/js.bzl
def _npm_binary_impl(ctx):
  print(ctx.attr.name)

npm_binary = repository_rule(
    implementation=_npm_binary_impl,
    local=True,
    attrs= {
        "name": attr.string(mandatory=True),
    })

**Comment by laszlocsomor** [comment]
That's not good. Routing to @vladmos as this looks like a Skylark bug.

**Comment by vladmos** [comment]
Should be fixed now. Providing a "name" attribute for a rule is not allowed anymore.
