### ISSUE TITLE
[Mirror] Boost 1.82.0

### ISSUE THREAD

**Issue by Vertexwahn** [bazelbuild/bazel#18122]
### Please list the URLs of the archives you'd like to mirror:

Please mirror `https://boostorg.jfrog.io/artifactory/main/release/1.82.0/source/boost_1_82_0.tar.gz`

Expected mirrored URL:

`https://mirror.bazel.build/boostorg.jfrog.io/artifactory/main/release/1.82.0/source/boost_1_82_0.tar.gz`

**Comment by sgowroji** [comment]
Please find the below mirror artifacts
1. https://mirror.bazel.build/boostorg.jfrog.io/artifactory/main/release/1.82.0/source/boost_1_82_0.tar.gz
