### ISSUE TITLE
Parsing JSON in Skylark

### ISSUE THREAD

**Issue by rockwotj** [bazelbuild/bazel#1813]
I'm trying to write a Skylark Extension and need to work with JSON data. Is there a way to load a JSON string into a struct or dict without implementing a json parser in my .bzl file?

**Comment by pcj** [comment]
I don't think so.  I would consider farming that task out to a helper python script.  Implementing a JSON parser would be pretty difficult without recursion.

**Comment by rockwotj** [comment]
Yeah but then I need to use certain values from that JSON to pass onto other build steps, as it gets very messy. So farming out to helpers would be non ideal as a bunch of work would get duplicated in each helper function. Would there be a chance this could get added to the built in functions for Skylark? I feel this could be a pretty common task.

**Comment by laszlocsomor** [comment]
@rockwotj : What's in the JSON data that you need to process in Skylark? How would the Skylark code use this data?

In principle the only way to process this data is creating Skylark structures from it using a tool pre-build that converts the data, as @pcj suggested, then `load`'ing that `.bzl` file.

I don't think we have JSON parsing on the roadmap, but I'm looping in @laurentlb to confirm.

**Comment by rockwotj** [comment]
Similar to `maven_jar` for java I want to add support for [Cocoapods](https://github.com/CocoaPods/Specs) on iOS. So I'm working on a bazel extension to convert `podspec.json` files into `BUILD` files.

**Comment by kchodorow** [comment]
cc @aj-michael, who's interested in Cocoapod support.

**Comment by aj-michael** [comment]
Haha, I had been asking around on behalf of @mcdonamp who I'm sure is already aware of this effort. Hi Tyler!

**Comment by rockwotj** [comment]
Haha great! Hey Michael, long time no talk. @mcdonamp has talked about it enough I figured it'd be a good side project.

**Comment by mcdonamp** [comment]
In case anyone else is curious, I think this can be accomplished manually in today's world by doing something like this: https://gist.github.com/mcdonamp/1f0799e38d1e96a993319da4645fa0b4 

I think @rockwotj has made it a little cleaner (autogening the `BUILD` file) and added support for pulling particular versions of a pod, more like `@cocoapod//sdwebimage:X.Y.Z`

As Tyler said, we need the ability to parse the `podspec.json` file, map specific properties to their `BUILD` equivalents, and autogenerate that `BUILD` file.

**Comment by pcj** [comment]
@rockwotj fyi you may already be aware of this tool in rules_go named "[gazelle](https://github.com/bazelbuild/rules_go/tree/master/go/tools/gazelle)" which autogenerates BUILD files for golang.  You may or may not be interested in using go but then you can use [buildifier](https://github.com/bazelbuild/buildifier) as well.

**Comment by rockwotj** [comment]
@pcj I was not. Thanks for the link! I'll probably look into that.

**Comment by damienmg** [comment]
Seems like this was resolved, closing :)

**Comment by jin** [comment]
For future readers: there doesn't yet exist a JSON parser in Starlark, the discussion is continuing here: https://github.com/bazelbuild/bazel/issues/3732

**Comment by jlaxson** [comment]
More explicitly: this now exists: https://docs.bazel.build/versions/master/skylark/lib/json.html
