### ISSUE TITLE
Documentation issue: Installing Bazel using Bazelisk

### ISSUE THREAD

**Issue by githubyumingsheng** [bazelbuild/bazel#18141]
Documentation URL: https://docs.bazel.build/versions/4.2.2/install-bazelisk.html

**Comment by Pavank1992** [comment]
Hi @githubyumingsheng, Could you please let us know what issue you are facing with the document so we can dive deep? If it is for Installing Bazel using Bazelisk, please follow the steps shared in [the official README](https://github.com/bazelbuild/bazelisk/blob/master/README.md) (mentioned in the doc).

**Comment by Pavank1992** [comment]
If you are facing any issue, please raise issue with issue [template](https://github.com/bazelbuild/bazel/issues/new/choose).
