### ISSUE TITLE
Test suites are being skipped when a filegroup is being built and the test suite is an element of the filegroup

### ISSUE THREAD

**Issue by limdor** [bazelbuild/bazel#18142]
### Description of the bug:

Imagine where you have a filegroup, and instead of files is refering to targets.
```
filegroup(
    name = "bla",
    src = [
        "//:my_library",
        "//:my_test_suite",
        "//:my_test_target",
    ]
)
```

Now when running `bazel build //:bla`, the target my_test_suite is not being built.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a target similar to what is described above.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

5.3.1

### Have you found anything relevant by searching the web?

I'm considering if this might be related to the fact of test_suite being different

See: https://github.com/bazelbuild/bazel/issues/14053

I was considering if could be related to https://github.com/bazelbuild/bazel/issues/10893

### Any other information, logs, or outputs that you want to share?

I would like to describe here what was the goal. I can understand that this might not be the way to achieve that but the result was unintuitively and the fact that is silently ignored I find it problematic.

In our case we just wanted to aggregate a set of targets that are "buildable" to check if they compile with a specific compiler.

**Comment by FaBrand** [comment]
A regular test target defines a output file, which causes bazel to produce the test binary when built through the filegroup (including its data)
```
$ bazel cquery test_a --output=files
INFO: Invocation ID: c494b662-6127-4014-89ca-232409bb77e4
INFO: Analyzed target //:test_a (37 packages loaded, 251 targets configured).
INFO: Found 1 target...
bazel-out/k8-fastbuild/bin/test_a
INFO: Elapsed time: 10.951s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
```

However for a test suite this does not seem to apply:
Cquery shows no declared files, which causes nothing to be built.
```
$ bazel cquery tests --output=files
INFO: Invocation ID: d7370ef1-58dd-47cb-9457-8b87b352c96d
INFO: Analyzed target //:tests (0 packages loaded, 3 targets configured).
INFO: Found 1 target...
INFO: Elapsed time: 0.267s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 0 total action
```

Declaring an output or an output_group (e.g. similar to how `build_test` does it) would solve the issue

Could not find any existing output groups that we could use:
```
$ bazel cquery //:tests \
  --output=starlark \
  --starlark:expr="target.output_groups"
INFO: Invocation ID: abe67cf7-58eb-4a70-a008-5485d752fe3b
INFO: Analyzed target //:tests (1 packages loaded, 11 targets configured).
INFO: Found 1 target...
struct(_hidden_top_level_INTERNAL_ = depset([]))
INFO: Elapsed time: 0.219s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
```

**Comment by gregestren** [comment]
@sdtwigg any initial thoughts?

**Comment by comius** [comment]
This is WAI. filegroups collect the `files` from targets (the ones returned in DefaultInfo). And `test_suite` doesn't return any files. You basically get the same result if you build the `test_suite` directly.
