### ISSUE TITLE
git_repository is not reproducible

### ISSUE THREAD

**Issue by cameron-martin** [bazelbuild/bazel#18152]
### Description of the bug:

The git_repository repository rule leaves the `.git` directory, either in [the root or in `.tmp_git_root`](https://github.com/bazelbuild/bazel/blob/0d672f3495036ca9e35a8fcd821fd4df6461b7dc/tools/build_defs/repo/git.bzl#L31-L36). This directory contains files that are not a function of the input attributes, for example `.git/logs` contains files that contain timestamps of when the remote branch was fetched.

This causes a real issue in rules_rust (https://github.com/bazelbuild/rules_rust/issues/1927), since it generates targets that glob the entire external repository.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a git_repository repository rule, inspect the `.git/logs` directory and see that it contains timestamps.

### Which operating system are you running Bazel on?

Ubuntu 22.04

### What is the output of `bazel info release`?

release 6.1.0

**Comment by sluongng** [comment]
Does it not remove it here https://github.com/bazelbuild/bazel/blob/0d672f3495036ca9e35a8fcd821fd4df6461b7dc/tools/build_defs/repo/git.bzl#L176 🤔

**Comment by cameron-martin** [comment]
I guess this bug only happens when `strip_prefix` is specified, and the git repository is in `.tmp_git_root`. I didn't observe the other case, and just assumed. I think the line above needs to be changed to:

```
if ctx.attr.strip_prefix:
    ctx.delete(ctx.path(".tmp_git_root"))
else:
    ctx.delete(ctx.path(".git"))
```

**Comment by fmeum** [comment]
@cameron-martin That looks very reasonable. Do you want to submit that as a PR?
