### ISSUE TITLE
Can't bootstrap with clang >= 15 and gcc >= 13

### ISSUE THREAD

**Issue by aaronmondal** [bazelbuild/bazel#18167]
### Description of the bug:

The abseil dependency used in upb is too old. Some symbols used by it no longer resolve.

Updating the gRPC dependencies would fix the issue.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Install Clang 15 or 16 (edit, thanks to @davido: or GCC 13)
2. Try to bootstrap Bazel

### Which operating system are you running Bazel on?

Gentoo X86_64 with clang profile

### What is the output of `bazel info release`?

Tried at HEAD.

**Comment by davido** [comment]
@aaronmondal I am seeing probably a different issue trying to build Bazel using gcc 13:

```bash
ERROR: /home/davido/.cache/bazel/_bazel_davido/0fa756dec521553dbe2dde6b6eac99b4/external/com_google_absl/absl/strings/BUILD.bazel:1078:11: Compiling absl/strings/internal/str_format/float_conversion.cc [for tool] failed: (Exit 1): gcc failed: error executing command (from target @com_google_absl//absl/strings:str_format_internal) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 38 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from external/com_google_absl/absl/strings/internal/str_format/float_conversion.h:18,
                 from external/com_google_absl/absl/strings/internal/str_format/float_conversion.cc:15:
external/com_google_absl/absl/strings/internal/str_format/extension.h:34:6: warning: elaborated-type-specifier for a scoped enum must not use the 'class' keyword
   34 | enum class FormatConversionChar : uint8_t;
      | ~~~~ ^~~~~
      |      -----
```

Ultimately, `stdint.h` was missing, in outdated `abseil-cpp` release, that was fixed upstream: [1] one year ago.

Not sure, if we need a separate issue for that?

[1] https://github.com/abseil/abseil-cpp/commit/36a4b073f1e7e02ed7d1ac140767e36f82f09b7c

**Comment by aaronmondal** [comment]
@davido This is probably related "closely enough" to be a merged issue. The gRPC dependency (and related deps like upb and abseil) is ancient from an upstream/living at head perspective. I'll update the issue to include GCC.

IMO it's an issue in general that some dependencies are not updated frequently enough and the Bazel build tends to fail with recent compiler versions.

**Comment by davido** [comment]
@aaronmondal thanks for the update.

I'm working on non intrusive `abseil-cpp` patch similar to https://github.com/bazelbuild/bazel/issues/15168 and https://github.com/bazelbuild/bazel/pull/15177, will upload PR in a moment.
