### ISSUE TITLE
[Mirror] abseil-cpp 20220623.1

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#18188]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/abseil/abseil-cpp/archive/refs/tags/20220623.1.tar.gz

**Comment by sgowroji** [comment]
Please find the below mirror artifact
1. https://mirror.bazel.build/github.com/abseil/abseil-cpp/archive/refs/tags/20220623.1.tar.gz

**Comment by davido** [comment]
Thanks, I've update the PR: https://github.com/bazelbuild/bazel/pull/18184
