### ISSUE TITLE
bazel 5.4.1 dist archive includes outdated .bazelversion file

### ISSUE THREAD

**Issue by dmivankov** [bazelbuild/bazel#18189]
### Description of the bug:

`.bazelversion` file is included in https://github.com/bazelbuild/bazel/releases/download/5.4.1/bazel-5.4.1-dist.zip and it 

prevents building examples/
---prevents bootstrap compilation if 5.4.0 isn't available as 2nd stage compilation pass wants to pick up 5.4.0 from outputs of 1st pass.---

Changing 5.4.0 to 5.4.1 should be enough to fix it

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build bazel 5.4.1, run `bazel test examples/cpp:hello-success_test` in unpacked dist archive
```
/build/bazel_src/tools/bazel: line 2: /nix/store/ilxn5dvj3yd3g670yd9n3cncrpd7ph3j-bazel-5.4.1/bin/bazel-5.4.0: No such file or directory
```

### Which operating system are you running Bazel on?

NixOS

**Comment by meteorcloudy** [comment]
Boostrapping Bazel shouldn't require any previously installed Bazel binary, it's probably something else require a specific version of Bazel? Can you share the build log?

**Comment by dmivankov** [comment]
Actually you're right, bootstrap compilation works, but building examples/ doesn't due to `.bazelversion` file requiring `5.4.0` (bootstrap scripts don't look into that file it seems).
  
Discovered while preparing a version update for nixpkgs https://github.com/NixOS/nixpkgs/pull/227432 (note: there are some other build errors that look transient)

Log exerpt
```
building
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
...
Build successful! Binary is here: /build/bazel_src/output/bazel
...
# here is tries to bazel test examples/
running install tests
/build/bazel_src/tools/bazel: line 2: /nix/store/ilxn5dvj3yd3g670yd9n3cncrpd7ph3j-bazel-5.4.1/bin/bazel-5.4.0: No such file or directory
```

I've updated issue description

**Comment by meteorcloudy** [comment]
I don't think there is anything we could do from Bazel side, basically we use `.bazelversion` file specify the version of Bazel you should use to build Bazel in the current repository state.
