### ISSUE TITLE
Error prone causing bazel build to fail

### ISSUE THREAD

**Issue by brendandouglas** [bazelbuild/bazel#1818]
Related to / dupe of https://github.com/google/error-prone/issues/461

Bazel fails at java compilation step, with error:

> ERROR: /path_to_project/base/BUILD:22:1: Couldn't build file base/libunit_test_utils.jar: Java compilation in rule '//base:unit_test_utils' failed: namespace-sandbox failed: error executing command ~/.cache/bazel/_bazel_brendandouglas/d5bec423b42e7dc25e25c2cc27988abf/execroot/temp-copybara/_bin/namespace-sandbox ... (remaining 8 argument(s) skipped).
> base/scope/ErrorCollector.java:44: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
>     assertThat(messages).containsExactly((Object[]) requiredMessages);
>                                         ^
>      Please report this at https://github.com/google/error-prone/issues/new and include the following:
>   
>      error-prone version: 2.0.9-SNAPSHOT
>      Stack Trace:
>      com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.google.errorprone.annotations.CanIgnoreReturnValue not found

Additional, possibly irrelevant details: the 'unit_test_utils' target contains deps:
- junit 4.11
- mockito 1.9.5
- truth 0.30

**Comment by brendandouglas** [comment]
Turning off error prone with --javacopt='-extra_checks:off' is a good workaround.

**Comment by laszlocsomor** [comment]
Trying to repro this but I'm not seeing any errors:

```
$ cat foo/java/com/example/BUILD 
java_test(
    name = "FooTest",
    srcs = ["FooTest.java"],
    deps = [
        "//third_party:guava",
        "//third_party:guava-testlib",
        "//third_party:junit4",
        "//third_party:truth",
    ],
)


$ cat foo/java/com/example/FooTest.java 
package com.example;

import static com.google.common.truth.Truth.assertThat;
import static org.junit.Assert.fail;

import com.google.common.collect.ImmutableSet;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

@RunWith(JUnit4.class)
public class FooTest {
  @Test public void foo() {
    assertThat(ImmutableSet.of("a", "b")).containsExactly("a", "b");
  }
}


$ bazel test foo/java/com/example:all --javacopt='-extra_checks:on'
INFO: Analysed target //foo/java/com/example:FooTest.
INFO: Found 1 test target...
Target //foo/java/com/example:FooTest up-to-date:
  bazel-bin/foo/java/com/example/FooTest.jar
  bazel-bin/foo/java/com/example/FooTest
INFO: Elapsed time: 0.162s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action
//foo/java/com/example:FooTest                                  (cached) PASSED in 0.4s
```

Is there any extra step necessary to turn on Error Prone?

**Comment by brendandouglas** [comment]
@cushon tracked this down -- it was user error (I was using an old version of bazel). Rebuilding bazel fixed it.

**Comment by brendandouglas** [comment]
(more specifically, I was using a bazel build with error-prone 2.0.9)
