### ISSUE TITLE
Installation on Linux Mint (Which is an Ubuntu Based Distro)

### ISSUE THREAD

**Issue by NickDeBeenAIE** [bazelbuild/bazel#18204]
### Description of the bug:

Bazel just refuses to install because it doesn't exist:

<pre>sudo apt update &amp;&amp; sudo apt install bazel
Hit:1 http://packages.microsoft.com/repos/code stable InRelease
Hit:2 https://dl.google.com/linux/chrome/deb stable InRelease                  
Ign:3 http://packages.linuxmint.com vera InRelease                             
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease               
Hit:5 http://packages.linuxmint.com vera Release                               
Hit:7 http://archive.ubuntu.com/ubuntu jammy InRelease                         
Hit:8 http://archive.ubuntu.com/ubuntu jammy-updates InRelease<font color="#C4A000">                 </font>
Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
<font color="#EF2929"><b>E: </b></font>Unable to locate package bazel
</pre>

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

``sudo apt update && sudo apt install bazel``

That's it, its really this simple.

### Which operating system are you running Bazel on?

I don't have Bazel because it won't install.

### What is the output of `bazel info release`?

Nothing, because again, I can't install Bazel.

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

I don't have this info as again for the 3rd time, I can't install it.

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
For the last time, I do not have this information as I cannot install Bazel.
```

### Have you found anything relevant by searching the web?

Nope. No search result is relevant to a program that refuses to install no matter how many times you correctly enter the command. Google is most definitely not my friend here.

### Any other information, logs, or outputs that you want to share?

Nope. That's about it.

**Comment by Pavank1992** [comment]
HI @NickDeBeenAIE, Could you please confirm you are following [Installing Bazel](https://bazel.build/install) documents for installation (select respective OS)?
If still facing the issue please share the steps followed and its respective outcomes. This will help us to dive deep.

**Comment by meteorcloudy** [comment]
Please follow https://bazel.build/install/ubuntu#add-dis-uri

**Comment by NickDeBeenAIE** [comment]
> HI @NickDeBeenAIE, Could you please confirm you are following [Installing Bazel](https://bazel.build/install) documents for installation (select respective OS)? If still facing the issue please share the steps followed and its respective outcomes. This will help us to dive deep.

Yes, I am on Linux Mint. This is an Ubuntu based distro.

**Comment by NickDeBeenAIE** [comment]
I could also follow the instructions for the Ubuntu operating system, but I don't believe this'll work.

**Comment by Wyverald** [comment]
This is not a bug because we didn't promise anywhere that you can install Bazel using apt on Ubuntu _or_ Mint. If you'd like to package it for Ubuntu or Mint, feel free to send a PR.

**Comment by NickDeBeenAIE** [comment]
What is a P.R.?

**Comment by NickDeBeenAIE** [comment]
> Please follow https://bazel.build/install/ubuntu#add-dis-uri

``E: Unable to locate package: Bazel``

**Comment by meisterT** [comment]
@NickDeBeenAIE did you run `apt-get update` before trying again?
