### ISSUE TITLE
Bazel Java test runner leaks classes into the classpath

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#18214]
### Description of the bug:

The Java test runner used by Bazel leaks classes into the classpath. 

This was discovered while investigating https://github.com/bazelbuild/rules_jvm_external/issues/839 (see [this comment](https://github.com/bazelbuild/rules_jvm_external/issues/839#issuecomment-1521810166))

Other test runners work around this issue by either only using classes in the JDK or known to be brought in by dependencies the user will require:

* `contrib_rules_jvm` uses a `jvm_import` to have the runner in a single jar file with no transitive deps: https://github.com/bazel-contrib/rules_jvm/blob/main/java/src/com/github/bazel_contrib/contrib_rules_jvm/junit5/BUILD.bazel#L9-L21
* Buck also avoids using dependencies outside the JDK: https://github.com/facebook/buck/blob/main/src/com/facebook/buck/testrunner/JUnitRunner.java#L54-L60

In theory, it should be possible to grab a pristine classloader and only run tests using that in the runner, but that's pretty challenging to get right.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```shell
git clone -v https://github.com/bazelbuild/rules_jvm_external.git
git reset d211f3b --hard
export USE_BAZEL_VERSION=bbf78a2cec27bf42bcbba59d3f84c857dff3aa15
bazel test //...
```

### Which operating system are you running Bazel on?

N/A

### What is the output of `bazel info release`?

N/A

**Comment by meteorcloudy** [comment]
To clarify a bit, this is an issue with Bazel@HEAD

**Comment by meteorcloudy** [comment]
@comius But 6.2.0rc1 is breaking rules_jvm_external which it shouldn't:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2979#0187b531-8780-4bff-9b1c-cbace4a9481f

**Comment by shs96c** [comment]
The problem of leaking on to the classpath exists in the current release, it's just that the new `java_tools` adds a dep on guava, and that tripped our test.

**Comment by meteorcloudy** [comment]
@shs96c is this something you can work around in rules_jvm_external?

**Comment by shs96c** [comment]
Nope. All `rules_jvm_external` is doing in this case is downloading some artifacts and exposing them as `jvm_import`. By the time we're running tests, those are just contributing to the classpath.

The problem is that the test runner depends on classes outside of the JRE and hasn't made an effort to prevent those additional dependencies being in the classloader used by the tests. The easiest way to do that is to do what Buck and the `contrib_rules_jvm` test runners did, and just limit yourself to the JDK or classes you can expect to be present in the test framework of choice (my preference is for the way that `contrib_rules_jvm` does it, which compiles the code, then exports a single jar with zero dependencies by indirecting through a `jvm_import`)

The more complicated way is for the test runner to "somehow" obtain a new classloader initialised with modules from the JRE, and then to augment that with the classpath provided by the tests (possibly by having the test classpath be a traditional `URLClassLoader` initialised with the test classpath, and having the parent of that classloader be the pristine classloader). We tried that with Buck for a while, and it wasn't easy to get right or stable, so we went with something simpler.

On the plus side, once rewritten, the test runner shouldn't be the cause of any breaking changes --- nothing should be relying on the classes it leaks into the classpath anyway....

**Comment by comius** [comment]
Findings:
- The leak of Guava was always present
- It became wider with https://github.com/bazelbuild/bazel/commit/205ba06a677fd1db428ca3cd154f4e585e8e45d4 (adding j2objc annotations to it)

Fix in https://github.com/bazelbuild/bazel/pull/18256, removes j2objc from guava, but keep guava on test-runner.

Proper (incompatible) fix before Bazel LTS release is to remove guava from test-runner.

**Comment by keertk** [comment]
https://buildkite.com/bazel/rules-jvm-external/builds/3384 passed. Closing this issue.

**Comment by keith** [comment]
even though this issue is closed I can't tell from this resolution if it's safe to apply this todo? https://github.com/bazelbuild/bazel/blob/b2cf9a59a3b0beb73e86fdd093c4c9787b1ac86c/third_party/BUILD#L353

**Comment by keith** [comment]
meaning can we revert https://github.com/bazelbuild/bazel/commit/413a8ba8471726a2515e0b771fdf7a0a3cd213a0 ? right now this change relies on a rules_jvm_external patch that leaks into other repos trying to build some parts of bazel

**Comment by hvadehra** [comment]
> can we revert https://github.com/bazelbuild/bazel/commit/413a8ba8471726a2515e0b771fdf7a0a3cd213a0 ?

Done in https://github.com/bazelbuild/bazel/commit/2493f2d278ea3144d1b43b638a9b5c5a1bb52c94

**Comment by shs96c** [comment]
Is there any appetite for rewriting the Bazel JUnit4 runner so that it only uses classes from the JDK? That would prevent the leaking of anything on to the command line, and is what we've done for [the JUnit5 runner in contrib_rules_jvm](https://github.com/bazel-contrib/rules_jvm/blob/main/java/src/com/github/bazel_contrib/contrib_rules_jvm/junit5/JUnit5Runner.java). I think it'd be easy enough to make that also support JUnit4, and I'm sure we can find a way to contribute it to Bazel itself.

**Comment by hvadehra** [comment]
> rewriting the Bazel JUnit4 runner so that it only uses classes from the JDK

AFAICT the set of dependencies is already pretty minimal (errorprone, jsr annot). Are there any other non-JDK classes you're thinking of?

**Comment by shs96c** [comment]
It also leaks junit4 onto the classpath. Ideally, there'd be nothing, other than what a user specifies in their test's `deps`. TBH, I thought the existing junit4 runner dragged in guava, but maybe that's not the case now.
