### ISSUE TITLE
cc_test does not accept cc_shared_library dependencies

### ISSUE THREAD

**Issue by mobileink** [bazelbuild/bazel#18222]
### Description of the bug:

Error msg:

in deps attribute of cc_test rule //test:test: cc_shared_library rule '//lib/static:c_s7_shared' is misplaced here (expected cc_library, objc_library, cc_proto_library or cc_import) and '//lib/static:c_s7_shared' does not have mandatory providers: 'CcInfo'. Since this rule was created by the macro 'cc_test_wrapper', the error might have been caused by the macro implementation

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Add a `cc_shared_library` dependency to `cc_test` target.

### Which operating system are you running Bazel on?

macos 13.3.1

### What is the output of `bazel info release`?

release 6.1.2

### Have you found anything relevant by searching the web?

Nothing

**Comment by Pavank1992** [comment]
Hi @mobileink, Could you please provide minimal steps to reproduce the issue with a sample code? That will make it easier to track down.

**Comment by calebzulawski** [comment]
I'm running into a similar problem. `cc_shared_library` doesn't provide `CcInfo` at all.

A simple example like this should illustrate it:
```bzl
cc_library(
    name = "broken",
    deps = [":shared"],
)

cc_shared_library(
    name = "shared",
    shared_lib_name = "libshared.so",
    deps = [":shared_impl"],
)

cc_library(
    name = "shared_impl",
    srcs = ["lib.cpp"],
)
```

**Comment by aminya** [comment]
This is the same for `cc_binary`. It is not just limited to `cc_test`. In short, what is generated using `cc_shared_library` is unusable.

**Comment by mobileink** [comment]
I believe this is fixed in version 7?

**Comment by aminya** [comment]
@mobileink The `7.0.0-pre.20231011.2` version from a week ago still has the bug. What version are you using?

**Comment by mobileink** [comment]
On Tue, Oct 31, 2023, 7:42 PM Amin Yahyaabadi ***@***.***>
wrote:

> @mobileink <https://github.com/mobileink> The 7.0.0-pre.20231011.2
> version from a week ago still has the bug. What version are you using?
>

Not using it, I just remember seeing a release note somewhere that said
cc_shared_library now produces CcInfo

**Comment by keith** [comment]
you want to put this in the `dynamic_deps` attribute of cc_binary/cc_test
