### ISSUE TITLE
Create build flow dependency

### ISSUE THREAD

**Issue by GinoHereIam** [bazelbuild/bazel#1822]
Hello!

I've got a project and I try to set up a build flow dependency, like I want to build my top - level BUILD (which should be in same like the WORKSPACE file, if it is possible). This is where I have my entry  point to build the project. 

Is there a way to define a rule to build this dependency chain?

`bazel build //PROJECT:ALL`

```Python
myrule(
    name = "ALL",
    deps = [":x", ":y", ":z"],
)
```

Thanks & regards
Gino

**Comment by ittaiz** [comment]
Hope I'm not interfering but did you try bazel build //:ALL? (Btw, sounds
more relevant for the google group of Bazel discuss)

**Comment by GinoHereIam** [comment]
No I didn't, because there is no rule ... my question was if it is possible. And honestly, I don't know how if it is possible. :(

**Comment by ittaiz** [comment]
AFK but you could probably synthesize a gen rule that you could use. Don't
know if that is an anti pattern or not.
In any case I think this discussion would be better placed in the google
group but those are my 2c

**Comment by GinoHereIam** [comment]
Thanks :) will ask in the google group.
