### ISSUE TITLE
py_test with `unittest.TestCase` doesn't work with sharding

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#18228]
### Description of the bug:

The `shard_count` attribute of `py_test` doesn't actually do any sharding if you just use `unittest.TestCase`, instead it just causes the test to run multiple tests.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In the Bazel repo:
- Add `shard_count = 5` to `//examples/py_native:test`
- Run `bazel test //examples/py_native:test`
- Check the test logs under `bazel-testlogs/examples/py_native/test/`

Every test log has:
```
Ran 2 tests in 0.000s

OK
```

### Which operating system are you running Bazel on?

all

### What is the output of `bazel info release`?

any

### Any other information, logs, or outputs that you want to share?

- [absltest](https://abseil.io/docs/python/guides/testing#testing) supports sharding, switching to this framework may make it work.
- https://bazel.build/reference/test-encyclopedia#test-sharding is not true, Bazel doesn't check [TEST_SHARD_STATUS_FILE](https://bazel.build/reference/test-encyclopedia#initial-conditions) to avoid launching additional test runners when sharding is not supported.

**Comment by fmeum** [comment]
@meteorcloudy I noticed the lack of an mtime check before while working in rules_jvm's JUnit 5 runner. This seems quite error-prone as we saw here. 

Do you think I could reasonably add that check for Bazel 7? As migrating only requires dropping `shard_count` and enjoying faster tests, that sounds like an acceptable "breaking" change to me.

**Comment by Wyverald** [comment]
If by "mtime check" you mean the TEST_SHARD_STATUS_FILE thing, then yeah I think adding it for Bazel 7 is very reasonable. If the runner doesn't touch that file, we can simply fail the test, and the fix is very easy -- just remove `shard_count`.

**Comment by meteorcloudy** [comment]
I'll recommend to add the check, but guard it behind an incompatible flag, then we can even cherry pick it back to 6.x (off by default) so that users can start migrate earlier.

**Comment by meteorcloudy** [comment]
The Bazel bug has been fixed by https://github.com/bazelbuild/bazel/pull/18236 and https://github.com/bazelbuild/bazel/pull/18469
