### ISSUE TITLE
Run compile.sh in Bazel directory.

### ISSUE THREAD

**Issue by vmeade** [bazelbuild/bazel#1823]
I am running 
INPUT:
compile.sh
OUTPUT:
bash: compile.sh: command not found

and then
INPUT 
./compile.sh
OUTPUT
bash: ./compile.sh: No such file or directory

How do I run compile.sh _in Bazel directory_?

**Comment by meteorcloudy** [comment]
Can you make sure `compile.sh` is under your current directory?

**Comment by vmeade** [comment]
I figured this out by running bazel/compile.sh

Also I was able to run the program from source.
