### ISSUE TITLE
Android resource shrinking is broken with R8

### ISSUE THREAD

**Issue by mauriciogg** [bazelbuild/bazel#18239]
### Description of the feature request:

Resource shrinking works by analyzing which resources are used in the code. Bazel relies on the proguarded class jar to do so. This is fine when using legacy proguard, but R8 does optimization and dexing in the same pass. Because of this, the shrinker logic is unable to find any usage for most resources and ends up incorrectly removing them. R8 supports class file output mode, but at least in my cases it crashes and it is not ideal to have this intermediate class file step if its possible to directly go to dex files.

### What underlying problem are you trying to solve with this feature?

Make resource shrinking work with R8

### Which operating system are you running Bazel on?

Mac OS

### What is the output of `bazel info release`?

release 7.0.0.9

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

Custom built based of prerelease 7.0.0

### Have you found anything relevant by searching the web?

For reference this is the Gradle implementation for dex files https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:build-system/shrinker/src/main/java/com/android/build/shrinker/usages/DexUsageRecorder.kt

**Comment by mauriciogg** [comment]
@ted-xie  @ahumesky

**Comment by ahumesky** [comment]
This is addressed with https://github.com/bazelbuild/rules_android/commit/b79878d71688baff303a9a2ee4218d5505ccf4e2
