### ISSUE TITLE
--remote_download_toplevel does not download symlink targets of runfiles

### ISSUE THREAD

**Issue by eric-skydio** [bazelbuild/bazel#18249]
### Description of the bug:

`--remote_download_toplevel` downloads the runfiles associated with any outputs explicitly listed on the command line, and (on Linux) constructs a runfiles tree of symlinks for them.
Unfortunately, if the runfiles is constructed with `symlinks=` or `root_symlinks=` that refer to File objects _not_ in the `files=` depset of the runfiles, this process fails and the target of the symlink is not downloaded, which results in a broken symlink in the resulting runfiles tree.

This is important for us because we use root_symlinks to relocate files to keep our PYTHONPATH smaller. This works file when not using --remote_download_toplevel.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`rules.bzl`
```starlark
def _symlink_rule_impl(ctx):
    file = ctx.actions.declare_file("file.txt")
    executable = ctx.actions.declare_file("executable")

    ctx.actions.run_shell(
        outputs = [file],
        command = "echo 'Hello World!' > " + file.path,
    )
    ctx.actions.write(executable, "cat symlink.txt")
    return [DefaultInfo(
        runfiles = ctx.runfiles(
            symlinks = {"symlink.txt": file},
        ),
        executable = executable,
    )]

symlink_rule = rule(
    implementation = _symlink_rule_impl,
    executable = True,
    attrs = {},
)
```

`BUILD`
```starlark
load(":rules.bzl", "symlink_rule")

symlink_rule(name = "symlink")
```

Reproduction steps:
1. `bazel run //:symlink --remote_download_toplevel --disk_cache /tmp/cache`
2. `bazel clean`
3. `bazel run //:symlink --remote_download_toplevel --disk_cache /tmp/cache`

### Which operating system are you running Bazel on?

Ubuntu 18.04

### What is the output of `bazel info release`?

release 6.1.2

### Any other information, logs, or outputs that you want to share?

This seems to reproduce both on Bazel 5.x and the latest 7.0.0-pre*

**Comment by william-smith-skydio** [comment]
We see a backport of the fix to this issue to 6.3.0 in #18446, but it doesn't look like that merged and as of 6.3.2 this is still broken. Is this fix expected to be backported to 6.x or do we need to wait for 7.x?

**Comment by fmeum** [comment]
@william-smith-skydio That's an unrelated change of mine that hasn't been merged yet.

**Comment by coeuvre** [comment]
The fix was not cherry-picked into 6.x due to conflicts.
