### ISSUE TITLE
Errors in the compile.sh ... can anyone help?

### ISSUE THREAD

**Issue by vmeade** [bazelbuild/bazel#1824]
INFO:    bazel/compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch.......
C:\tools\msys64\home\Vincent\bazel>call "C:/Program Files (x86)/Microsoft Visual Studio 9.0/           VC/VCVARSALL.BAT" amd64
'"C:/Program Files (x86)/Microsoft Visual Studio 9.0/VC/VCVARSALL.BAT"' is not recognized as            an internal or external command,
operable program or batch file.

C:\tools\msys64\home\Vincent\bazel>set TMP=C:\tools\msys64\tmp\tmp.gHpedail3X

C:\tools\msys64\home\Vincent\bazel>CL /LD /Fe:"C:\tools\msys64\tmp\bazel_ppIkAgqr\jni\window           s_jni.dll" /I "C:/Program Files/java/jdk1.8.0_20/include" /I "C:/Program Files/java/jdk1.8.0           _20/include/win32" /I . C:\tools\msys64\home\Vincent\bazel\src\main\native\windows_error_han           dling.cc C:\tools\msys64\home\Vincent\bazel\src\main\native\windows_file_operations.cc C:\to           ols\msys64\home\Vincent\bazel\src\main\native\windows_processes.cc
'CL' is not recognized as an internal or external command,
operable program or batch file.

**Comment by vmeade** [comment]
It might be that I needed to set up Visual studio before the compiler could access it...

**Comment by laszlocsomor** [comment]
What version of Bazel are you using? Which commit did you check out?

**Comment by vmeade** [comment]
I figured it out from the error message last night.

"C:/Program Files (x86)/Microsoft Visual Studio 9.0/VC/VCVARSALL.BAT" this was an older version of visual studio still operating on my computer and so when the installer went to look for Visual Studio it found this one, and the not the newly installed version which was 14.0   .

**Comment by OverratedGman** [comment]
Hey, I had this problem last night. I resolved it by copying the file VcDevCmd from Common7/tools and moved it to VC and then renamed it vcvarsall. For the second error I ran the auto repair that is built into MS Visual Studio. You can access it through remove or uninstall the program
