### ISSUE TITLE
Installation Time

### ISSUE THREAD

**Issue by ajeetksingh** [bazelbuild/bazel#1825]
Hi,

I am trying to dabble with tensorflow and Bazel is one of the packages required by it.
I am running the following command to compile the library on my CentOS system:
`./compile.sh compile`

And it's taking ages to compile. How much time does it take to install the library? Is there any flag in `compile.sh` which would help me see the compile output? For example,

`./compile.sh compile --verbose`

Thank you.

**Comment by meteorcloudy** [comment]
Bazel is the build tool of tensorflow, not actually a library tensorflow depends on, you can follow [this page](https://www.bazel.io/versions/master/docs/install.html) to install bazel on your machine. And `./compile.sh` shouldn't take too long (I believe less than 10 mins on Linux).

**Comment by ajeetksingh** [comment]
Thank you for the prompt reply.. 
I am following the instructions on the mentioned webpage, but still the compilation is taking eternity.

I have Oracle Java 1.8 installed on my system, and executing a simple java function takes around 45seconds. I don't know, if it's pertaining to the problem or not.

**Comment by damienmg** [comment]
If a javac action is taking 45s not surprising than bazel compilation is slow. The problem is coming from your OS or your JDK installation. Have you tried using a binary version of Bazel?

**Comment by damienmg** [comment]
Assigning to @meteorcloudy for more follow-up

**Comment by ajeetksingh** [comment]
Let's close this issue.. Upon fresh installation of OS and Java, bazel compiled successfully.. 
As @damienmg pointed out the problem was coming from my OS... 

Thanks for all the help....

**Comment by Namburger** [comment]
open the compile.sh and add 
```
set -x
``` 
at the beginning to see some output..
Also I feel you, it takes FOREVER
