### ISSUE TITLE
[Mirror] zig 0.11.0-dev.2892+fd6200eda

### ISSUE THREAD

**Issue by marler8997** [bazelbuild/bazel#18276]
### Please list the URLs of the archives you'd like to mirror:

https://ziglang.org/builds/zig-windows-x86_64-0.11.0-dev.2892+fd6200eda.zip
https://ziglang.org/builds/zig-windows-x86-0.11.0-dev.2892+fd6200eda.zip
https://ziglang.org/builds/zig-windows-aarch64-0.11.0-dev.2892+fd6200eda.zip
https://ziglang.org/builds/zig-macos-aarch64-0.11.0-dev.2892+fd6200eda.tar.xz
https://ziglang.org/builds/zig-macos-x86_64-0.11.0-dev.2892+fd6200eda.tar.xz
https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.2892+fd6200eda.tar.xz
https://ziglang.org/builds/zig-linux-x86-0.11.0-dev.2892+fd6200eda.tar.xz
https://ziglang.org/builds/zig-linux-aarch64-0.11.0-dev.2892+fd6200eda.tar.xz
https://ziglang.org/builds/zig-linux-riscv64-0.11.0-dev.2892+fd6200eda.tar.xz
https://ziglang.org/builds/zig-linux-powerpc64le-0.11.0-dev.2892+fd6200eda.tar.xz
https://ziglang.org/builds/zig-linux-powerpc-0.11.0-dev.2892+fd6200eda.tar.xz

**Comment by sgowroji** [comment]
Please find the below mirror artifacts
1. https://mirror.bazel.build/ziglang.org/builds/zig-windows-x86_64-0.11.0-dev.2892+fd6200eda.zip
2. https://mirror.bazel.build/ziglang.org/builds/zig-windows-x86-0.11.0-dev.2892+fd6200eda.zip
3. https://mirror.bazel.build/ziglang.org/builds/zig-windows-aarch64-0.11.0-dev.2892+fd6200eda.zip
4. https://mirror.bazel.build/ziglang.org/builds/zig-macos-aarch64-0.11.0-dev.2892+fd6200eda.tar.xz
5. https://mirror.bazel.build/ziglang.org/builds/zig-macos-x86_64-0.11.0-dev.2892+fd6200eda.tar.xz
6. https://mirror.bazel.build/ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.2892+fd6200eda.tar.xz
7. https://mirror.bazel.build/ziglang.org/builds/zig-linux-x86-0.11.0-dev.2892+fd6200eda.tar.xz
8. https://mirror.bazel.build/ziglang.org/builds/zig-linux-aarch64-0.11.0-dev.2892+fd6200eda.tar.xz
9. https://mirror.bazel.build/ziglang.org/builds/zig-linux-riscv64-0.11.0-dev.2892+fd6200eda.tar.xz
10. https://mirror.bazel.build/ziglang.org/builds/zig-linux-powerpc64le-0.11.0-dev.2892+fd6200eda.tar.xz
11. https://mirror.bazel.build/ziglang.org/builds/zig-linux-powerpc-0.11.0-dev.2892+fd6200eda.tar.xz
