### ISSUE TITLE
Starlarkify all repository rules

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#18285]
We originally wanted to allow native repo rule usage in module extensions (https://github.com/bazelbuild/bazel/issues/15412), but that turned out to be surprisingly hard to implement.

Instead, we could just go down the other route: Starlarkify all the repo rules!

- [x] `local_repository` (trivial) (added in https://github.com/bazelbuild/bazel/commit/6f254ce0f95d70e744b513a94d577036712befac)
- [x] `local_config_platform` (trivial; but also kind of unnecessary, since nobody should use it other than `@local_config_platform` itself) (done in https://github.com/bazelbuild/platforms/pull/86)
- [x] Add some sort of `repository_ctx` API to acquire a `DirectoryListingValue` (added in 7.1.0: [`path.readdir`](https://bazel.build/rules/lib/builtins/path#readdir)) This would unblock the following:
  - [x] `new_local_repository` (added in https://github.com/bazelbuild/bazel/commit/6f254ce0f95d70e744b513a94d577036712befac)
  - [x] `android_sdk_repository` (now in https://github.com/bazelbuild/rules_android)
  - [ ] `android_ndk_repository` (partially done: https://github.com/bazelbuild/rules_android_ndk)

**Comment by Wyverald** [comment]
cc @ted-xie @ahumesky @kotlaja

**Comment by fmeum** [comment]
@Wyverald Starlarkifying `local_config_platform` would get us halfway to https://github.com/bazelbuild/bazel/issues/8766#issuecomment-1207481712, so I think it's worth doing.

**Comment by ahumesky** [comment]
A starkark version of `android_ndk_repository` is mostly complete here: https://github.com/bazelbuild/rules_android_ndk

**Comment by Wyverald** [comment]
See https://docs.google.com/document/d/17RZKMuMjAIgNfFdrsLhqNsMTQDSS-BBA-S-fCSBPV7M/edit# for the design to address the missing API.

**Comment by iancha1992** [comment]
@bazel-io fork 7.1.0

**Comment by aaronmondal** [comment]
@Wyverald I tried to use the local repo rules in an extension with `8.0.0-pre.20240401.3` which contains https://github.com/bazelbuild/bazel/commit/6f254ce0f95d70e744b513a94d577036712befac, but it doesn't seem to work.

In `extension.bzl` I have something like this (same issue for `new_local_repository`):

```python
load("@bazel_tools//tools/build_defs/repo:local.bzl", "local_repository")

def _extension_impl(ctx):
    local_repository(name = "foo", path = "../../")
    
myext = module_extension(
    implementation = _extension_impl,
)
```

In `MODULE.bazel` something like this:

```python
ext = use_extension("//:extension.bzl", "myext")

use_repo(ext, "foo")
```

It raises this error telling me that the `local.bzl` file can't be found. Is this intended behavior because it's a prerelease or could it be a bug?

```
MODULE.bazel:xx:yy:
  at .../extensions.bzl:6:6: cannot load '@@bazel_tools//tools/build_defs/repo:local.bzl': no such file:
  at .../extensions.bzl:6:6: cannot load '@@bazel_tools//tools/build_defs/repo:local.bzl': no such file
```

**Comment by fmeum** [comment]
@aaronmondal I can't reproduce this with `USE_BAZEL_VERSION=8.0.0-pre.20240401.3`. Both in WORKSPACE and MODULE.bazel `load("@bazel_tools//tools/build_defs/repo:local.bzl", "local_repository")` works just fine.

**Comment by aaronmondal** [comment]
It looks like i messed something up. I don't know what it was but your right it works. Thanks for checking, I was about to defer this and now it looks like we can get LLVM working with bzlmod after all :heart:

**Comment by matts1** [comment]
Is this going to be cherry-picked into 7.2.0? We're stuck with using new_local_repository for a few local dependencies.
