### ISSUE TITLE
bazel query cannot find Skylark rules on a package_path directory

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel#183]
If a build rule loads a Skylark rule for an external tools directory, such as the one in the Bazel source tree pointed to by `~/.bazelrc`, then running `bazel query 'deps()'` on the rule would fail.

To reproduce:
1. Create an empty directory and touch `WORKSPACE`
2. Copy `bazel/src/main/protobuf` into the directory
3. Run `bazel build //protobuf:proto_crosstool_config` to confirm that the build rule runs successfully
4. Run `bazel query`:
   
   ``` bash
   $ bazel query 'deps(//protobuf:proto_crosstool_config)'
   ERROR: /Users/dzc/Sandbox/genproto-test/protobuf/BUILD:1: Extension file not found: 'tools/build_rules/genproto.bzl'.
   ERROR: error loading package 'proto': Extension file not found: 'tools/build_rules/genproto.bzl'.
   ```

**Comment by kchodorow** [comment]
I'm going to change the title, as this is actually referring to directories on the package_path, not //external. (Easily confused.)

**Comment by claridge** [comment]
I just ran into this bug, too. It looks like having a tools symlink, per the old installation method, provides a workaround.

**Comment by damienmg** [comment]
Assigning to John as this should fixed by using label instead of path.

**Comment by meisterT** [comment]
Is still this an issue?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
