### ISSUE TITLE
rules_kotlin fails with Bazel@head on ubuntu

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#18300]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2995#0187df5e-739d-4fa5-b106-11ef5af7e8d3

Platform : rules_kotlin (RBE (:ubuntu: 16.04, OpenJDK 8))

Logs:

```


==================== Test output for //src/test/kotlin/io/bazel/kotlin:KotlinJvmBasicAssertionTest:
--
  | java.lang.NoSuchMethodError: java.util.Set.of(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/Set;
  | at com.google.testing.junit.runner.junit4.JUnit4RunnerModule.setOfRunListeners(JUnit4RunnerModule.java:130)
  | at com.google.testing.junit.runner.junit4.JUnit4Bazel.initialize(JUnit4Bazel.java:75)
  | at com.google.testing.junit.runner.junit4.JUnit4Bazel.<init>(JUnit4Bazel.java:52)
  | at com.google.testing.junit.runner.junit4.JUnit4Bazel$Builder.build(JUnit4Bazel.java:102)
  | at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:144)
  | at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:76)
  |  


```
Steps followed:

1.  git clone -v https://github.com/bazelbuild/rules_kotlin.git
2. cd rules_kotlin
3. git reset 1d2a56d59c54c51d31cf0710d53ea9e43de03f63 --hard
4. export USE_BAZEL_VERSION=11d1ffecd4994e4d6fa72306174444a80f97793b
5. bazel test //src/test/kotlin/io/bazel/kotlin/builder:builder_tests //src/test/kotlin/io/bazel/kotlin:KotlinJvmAssociatesBasicVisibilityTest //src/test/kotlin/io/bazel/kotlin:KotlinJvmBasicAssertionTest

CC @meteorcloudy

**Comment by meteorcloudy** [comment]
@comius Do you have any idea on this?

**Comment by meteorcloudy** [comment]
https://buildkite.com/bazel/culprit-finder/builds/5466#0187e1f9-c27b-41bf-99fc-2863f41d6e7d points to https://github.com/bazelbuild/bazel/commit/99846b0eb600c4fdc6e684e7021f3ecfaa30b6da, which I guess update the default java_tools to the one containing the changes in https://github.com/bazelbuild/bazel/commit/d6ad383a269cac720bfd1a76af87dd312b9313a7
