### ISSUE TITLE
Is the best way to cache a locally generated file to use `repo_ctx.download` and a local http server?

### ISSUE THREAD

**Issue by aryeh-looker** [bazelbuild/bazel#18304]
Just trying to figure this one out. Have pored over documentation to no avail. I just rewrote a rule to use `repo_ctx.download` instead of `gsutil` due to caching semantics issues like this.

**Comment by Wyverald** [comment]
What @tjgq said. It's also not entirely clear to me what you meant by "locally generated file"; do you mean something built by Bazel? What does `gsutil` have to do with anything then?

In any case, this sounds like a discussion topic, not a bug. Please use GitHub discussions / Slack / bazel-discuss@googlegroups.com instead.
