### ISSUE TITLE
Still Cannot Install or Run Bazel

### ISSUE THREAD

**Issue by NickDeBeenSAE** [bazelbuild/bazel#18315]
Its not me.

Its the binary that continues to fail to install, because using the bazel command fail's:

<pre>./bazel-7.0.0-pre.20230426.1-installer-darwin-x86_64.sh
Bazel installer
---------------

Bazel is bundled with software licensed under the GPLv2 with Classpath exception.
You can find the sources next to the installer on our release page:
   https://github.com/bazelbuild/bazel/releases

# Binary package at HEAD (@cf30e4c4b95d)
   - [Commit](https://github.com/bazelbuild/bazel/commit/cf30e4c4b95d)

The Bazel installer must have write access to /usr/local/bin!
Consider using the --user flag to install Bazel under /home/dbts2023/bin instead.

Usage: ./bazel-7.0.0-pre.20230426.1-installer-darwin-x86_64.sh [options]
Options are:
  --prefix=/some/path set the prefix path (default=/usr/local).
  --bin= set the binary folder path (default=%prefix%/bin).
  --base= set the base install path (default=%prefix%/lib/bazel).
  --user configure for user install, expands to:
      --bin=$HOME/bin --base=$HOME/.bazel
  --skip-uncompress skip uncompressing the base image until the
      first bazel invocation<pre>

**Comment by meisterT** [comment]
(I transferred the issue from the bazelisk repository as you are talking about Bazel not Bazelisk).

Regarding the first comment:
> The Bazel installer must have write access to /usr/local/bin!
> Consider using the --user flag to install Bazel under /home/dbts2023/bin instead.

Did you read this? Did you either try the flag or using sudo?


Regarding the second comment:
> Err:1 file:/var/cudnn-local-repo-ubuntu2204-8.9.0.131  InRelease
> The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8182C797D7522631

This is unrelated to Bazel and Bazelisk. Fix or remove that `cudnn` repo?

**Comment by NickDeBeenAIE** [comment]
To your first question.

Yes, I read the entire page.

I used ``sudo`` to answer your second question.

That output was a result of attempting to use bazel to answer your third question.

There is no way for me to remove it.

**Comment by tjgq** [comment]
You're trying to follow the MacOS installation instructions on a Linux machine.

**Comment by NickDeBeenAIE** [comment]
I am trying to follow the Ubuntu installation on an Ubuntu machine.

**Comment by tjgq** [comment]
In the output you pasted above, the installer script you're running is called `bazel-7.0.0-pre.20230426.1-installer-darwin-x86_64.sh` (`darwin` means MacOS). You're getting an error because the script tried to execute a MacOS binary on Linux, which cannot work.

You didn't tell us exactly which instructions you were following when you got the error message, so I'm simply guessing that you were trying to follow https://bazel.build/install/os-x instead of https://bazel.build/install/ubuntu.

**Comment by NickDeBeenAIE** [comment]
No, I was following the installation guide for Ubuntu, which, for its binaries, also uses .sh.

**Comment by NickDeBeenAIE** [comment]
Lets be real here however, because fun fact, MacOS X is based on Debian if you go back to I think 2000.

I could be wrong, so a polite correction is appreciated.

**Comment by meisterT** [comment]
Please read what people write - in this case reread Tiago's comment on darwin. You downloaded the wrong file.

Perhaps it's good for you to start over, pick a single installation method from the page and follow *each* step from the beginning.

(Also please refrain from adding useless comments like the last one which doesn't add any value to the discussion.)

**Comment by NickDeBeenSAE** [comment]
I bet this is still going to be a problem, but on Fedora 40.

**Comment by meisterT** [comment]
Feel free to add something specific as pointed out above if still relevant. For the time being I am closing this issue.
