### ISSUE TITLE
Server terminated abruptly (error code: 2, error message: 'Stream removed' error occurred when bazel was built

### ISSUE THREAD

**Issue by ZSW001** [bazelbuild/bazel#18311]
Description of the problem / feature request / question:
Whole day "bazel build" command fails. From logs I see that it compares check sum '@protobuf//' and they do not match. I've tried it on several machines - had same error.
Environment info
Operating System: Windows 
Bazel version 5.1.0

**Comment by sgowroji** [comment]
Closing it as invalid. Please follow the issue templates to raise the valid issue. Thanks!

**Comment by sgowroji** [comment]
Hi @ZSW001, Can you please provide more details on the above request. Thanks!
