### ISSUE TITLE
use_param_file dumps quotes around

### ISSUE THREAD

**Issue by dentiny** [bazelbuild/bazel#18326]
### Page link:

https://bazel.build/rules/lib/builtins/Args#use_param_file

### Problem description (include actual vs expected text, if applicable):

I want to use "use_param_file" to avoid arguments being oversized, but I found it also dumps quotes around some string arguments, which leads to `protoc` fails to compile.

Eg:
```
proto_plugin = "--plugin=protoc-gen-picopb=bazel-out/host/bin/picopb/picopb_plugin" # No quotes around.

args = ctx.actions.args()
args.use_param_file("@%s", use_always = True)
args.set_param_file_format("shell")
args.add(cur_argument)
```

I found in the dumped param file, the proto plugin param is quoted with `'`.
Like
```
'--plugin=protoc-gen-picopb=bazel-out/host/bin/picopb/picopb_plugin'
```
which makes `protoc` fails to build.

I think it's poorly documented how to avoid this issue.

**Comment by tjgq** [comment]
Have you tried using `set_param_file_format("multiline")`?

**Comment by dentiny** [comment]
> Have you tried using set_param_file_format("multiline")?

Thanks for the reply! Yes, I have tried "multiline" and "flag_per_line", both doesn't seem to get parameters from files, since I still see the oversized argument issue.
And from the logging message, I don't see spilled file (I did see filename for "shell" file format).

**Comment by dentiny** [comment]
I'm wondering if there're any more documents I could read on this setting?

**Comment by tjgq** [comment]
Since you're setting `use_always = True`, I'd expect the params file to always be produced. I also wouldn't expect the `set_param_file_format` argument to affect whether the params file is produced, only its contents.

Do you have a minimal repro you can share?

**Comment by tjgq** [comment]
Does https://bazel.build/rules/lib/builtins/Args#set_param_file_format answer your question?

**Comment by dentiny** [comment]
I figured it out: 
- The quote problem could be fixed with `multiline`
- The real problem for my use case is: there're multiple arguments used, and I only apply file param in one of them.
