### ISSUE TITLE
"cannot relativize" crash

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#18321]
### Description of the bug:

Started seeing this crash @ HEAD https://buildkite.com/bazel/apple-support-darwin/builds/1941#0187e83e-ff89-407c-930e-5575275ed97f https://buildkite.com/bazel/rules-swift-swift/builds/4211#0187e846-a4d0-43e1-9f8e-2bf03a0f2e87

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Seems like it doesn't repro locally. I imagine it requires a remote cache?

### Which operating system are you running Bazel on?

macOS / Windows

### What is the output of `bazel info release`?

8b60d6dded0b8e30405f4327aa0135def1b4b880

**Comment by tjgq** [comment]
cc @coeuvre , from the stack trace I think this was introduced by https://github.com/bazelbuild/bazel/commit/3ef2e53ab65eab006b0d01c41ebc2265754b2007

**Comment by meteorcloudy** [comment]
This is breaking many downstream projects: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3000
