### ISSUE TITLE
rules_go & rules_python are failing in Downstream CI with Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#18346]
rules_go: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3007#0187f91d-2018-4dd0-b272-79d934978ac3
rules_python : https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3007#0187f91d-2990-4989-9b6e-68aaf097469e

Logs:
```
(04:08:41) ERROR: /Users/buildkite/builds/bk-imacpro-12/bazel-downstream-projects/rules_go/tests/bcr/proto/BUILD.bazel:30:8: no such package '@gazelle~0.30.0~go_deps~org_golang_google_grpc//': no such package '@gazelle~0.30.0~go_deps~bazel_gazelle_go_repository_config//': error loading package '': Bzlmod system contains .bzl load visibility violations and referenced by '//proto:foo_grpc_test'
(04:08:41) ERROR: Analysis of target '//proto:foo_grpc_test' failed; build aborted: Analysis failed
(04:08:41) INFO: Elapsed time: 10.960s
(04:08:41) INFO: 0 processes.
(04:08:41) ERROR: Build did NOT complete successfully
```

Caused by https://github.com/bazelbuild/bazel/commit/a6ebf07eb6c9856fcebbc151fc4412060a584e52 : 

CC @meteorcloudy

**Comment by meteorcloudy** [comment]
Should be reproducible with https://github.com/bazelbuild/rules_python/tree/main/examples/bzlmod_build_file_generation

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by iancha1992** [comment]
@bazel-io fork 6.3.0
