### ISSUE TITLE
[6.3.0] Actually check `TEST_SHARD_STATUS_FILE` has been touched

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#18353]
Forked from #18236

**Comment by iancha1992** [comment]
merge conflict while cherry-pick

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/18418

**Comment by iancha1992** [comment]
https://github.com/bazelbuild/bazel/pull/18418 was merged. Hence, closing this now.
