### ISSUE TITLE
BUILD file conflicts with Python's distutils build directory on case-insensitive filesystems

### ISSUE THREAD

**Issue by robertwb** [bazelbuild/bazel#1835]
Is there a way to support an alternative name for this build file? (I'm looking at making my project usable from https://www.bazel.io/versions/master/docs/be/workspace.html#git_repository specifically.)

**Comment by meteorcloudy** [comment]
//cc @damienmg  Is there a workaround for this problem?

**Comment by katre** [comment]
We are already working on this as #552. I'll close this, feel free to follow there.
