### ISSUE TITLE
How to convert repository rule in bzlmod

### ISSUE THREAD

**Issue by PandaBlueYellow** [bazelbuild/bazel#18351]
### Description of the feature request:

In tensorflow, there are some depended repositories implemented by repository rule: https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/cuda_configure.bzl#L1484

Is there any easy way to migrate those repository rules to bzlmod? (e.g., not needing to implement the logic in repository rules again in module_extension)

### What underlying problem are you trying to solve with this feature?

Use tensorflow together with bzlmod

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

release 6.1.2

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
https://github.com/tensorflow/tensorflow.git
6894a3f83d3548121e78bf94ac7d992fa406f7cd
4386a6640c9fb65503750c37714971031f3dc1fd
```

### Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

No repository visible as '@local_config_cuda' from repository "@tensorflow"

**Comment by PandaBlueYellow** [comment]
I found this: https://fuchsia.googlesource.com/third_party/github.com/bazelbuild/rules_cc/+/890aeb2860814104ae0bc66373fa11f754280434%5E%21/

**Comment by meteorcloudy** [comment]
Please read https://bazel.build/external/overview#bzlmod
