### ISSUE TITLE
[6.3.0] Pass version to java_runtimes created by local_java_repository

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#18364]
Forked from #18344

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/18404

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/18415

**Comment by iancha1992** [comment]
https://github.com/bazelbuild/bazel/pull/18415 was merged. Closing this
