### ISSUE TITLE
[6.3.0] Don't eagerly flatten a `NestedSet` in `RepoMappingManifestAction`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#18370]
Forked from #18349

**Comment by iancha1992** [comment]
merge conflict while cherry-pick

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/18419

**Comment by iancha1992** [comment]
https://github.com/bazelbuild/bazel/pull/18419 was merged. Hence, this is now closed.

**Comment by keertk** [comment]
Reopening this since we may need to revert the cherry-pick as per https://github.com/bazelbuild/bazel/pull/18419#issuecomment-1603297313.

**Comment by iancha1992** [comment]
Reverted in https://github.com/bazelbuild/bazel/pull/18886
