### ISSUE TITLE
request support difference compile flags for different dependency

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/bazel#18394]
### Description of the feature request:

my project import project A, B in WORKSPACE file, I need A use a set of compile flags, while B use another, my own project use a total different compile flag set

**Comment by xiedeacc** [comment]
like --copt=-g just work for my own code, not work for tensorflow

**Comment by sgowroji** [comment]
Hi @xiedeacc, Could you please elaborate your query with an example and complete steps used to reproduce it. Thanks !
