### ISSUE TITLE
Toolchain Resolution Implementation does not belong in the docs site

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#18424]
### Page link:

https://bazel.build/configure/toolchain-resolution

### Problem description (include actual vs expected text, if applicable):

This page, https://bazel.build/configure/toolchain-resolution, doesn't make sense in the only doc set.  We should removed it, or turn it into comments near the source code.

**Comment by aiuto** [comment]
@katre  WDYT?  Remove it or put in a README.md in the source.
Or maybe it belongs under "Understand the codebase"
https://bazel.build/contribute/codebase

**Comment by katre** [comment]
We should move it to a README. I'll take a look at this later this week.
