### ISSUE TITLE
cc_proto_library not linked properly into cc_shared_library

### ISSUE THREAD

**Issue by sogartar** [bazelbuild/bazel#18459]
### Description of the bug:

`cc_shared_library` that depends on a `cc_proto_library` does not include the `cc_proto_library` when it gets linked.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

WORKSPACE
```
workspace(name = "scratchpad")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_proto",
    sha256 = "dc3fb206a2cb3441b485eb1e423165b231235a1ea9b031b4433cf7bc1fa460dd",
    strip_prefix = "rules_proto-5.3.0-21.7",
    urls = [
        "https://github.com/bazelbuild/rules_proto/archive/refs/tags/5.3.0-21.7.tar.gz",
    ],
)
load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()
```

BUILD
```
proto_library(
    name = "scratchpad_proto_lib",
    srcs = ["scratchpad_proto_lib.proto"],
)

cc_proto_library(
    name = "scratchpad_cc_proto_lib",
    deps = [":scratchpad_proto_lib"],
)

cc_shared_library(
    name = "scratchpad_shared_lib",
    deps = [ ":scratchpad_cc_proto_lib" ],
)
```

scratchpad_proto_lib.proto
```
syntax = "proto3";
package scratchpad;

message ScratchpadMessage {
    string scratchpad_data = 1;
}

```

```
$ bazel build --experimental_cc_shared_library //:scratchpad_shared_lib
```

The resulting library `scratchpad_shared_lib` does not include the symbols related to the protobuf stuff.

You can see that the symbol `scratchpad::ScratchpadMessage::~ScratchpadMessage` is defined in `libscratchpad_proto_lib.a`.
```
$ nm --defined-only bazel-bin/libscratchpad_proto_lib.a | c++filt | grep ScratchpadMessage::~ScratchpadMessage
0000000000000250 T scratchpad::ScratchpadMessage::~ScratchpadMessage()
```

But it is not defined in `libscratchpad_shared_lib.so`.

Further more `bazel-bin/libscratchpad_shared_lib.so-2.params` show that it may be linking to `scratchpad_proto_lib.pb.pic.o`
```
-shared
-o
bazel-out/k8-fastbuild/bin/libscratchpad_shared_lib.so
-Wl,-S
-fuse-ld=lld
-Wl,-no-as-needed
-Wl,-z,relro,-z,now
-B/usr/bin
-pass-exit-codes
-Wl,--start-lib
bazel-out/k8-fastbuild/bin/_objs/scratchpad_proto_lib/scratchpad_proto_lib.pb.pic.o
-Wl,--end-lib
-lstdc++
-lm
```
`scratchpad_proto_lib.pb.pic.o` has the symbols defined.

### Which operating system are you running Bazel on?

Ubuntu 20.04

### What is the output of `bazel info release`?

release 6.2.0

**Comment by oquenchil** [comment]
Hello, thanks for reporting this. This should be fixed with the version at head and will be fixed with 6.3.

Please try with:
```
USE_BAZEL_VERSION=e0dcb24db172384318d194c38a724ce3f1c01d4a bazelisk build ...
```

That's the latest commit of the 6.3 branch at the time of writing.
