### ISSUE TITLE
cc_binary support #included .cc/.cpp files for template functions

### ISSUE THREAD

**Issue by skubica** [bazelbuild/bazel#1845]
The C++ FAQ recommends that template function code be written in a \*-impl.cpp file which in turn should be #included by an associated .h header file.  See [C++ FAQ: How can I avoid linker errors with my template classes?](https://isocpp.org/wiki/faq/templates#separate-template-fn-defn-from-decl).  (They acknowledge that this is "confusing").

In a **cc_binary** declaration, there is no way to distinguish normally compiled .cpp files from these "header" \*-impl.cpp files in the src file list.  The resulting behavior when compiling is that gcc fails to find the \*-impl.cpp file for the #include. (Presumably, the \*-impl.cpp file would also be erroneously compiled as another one of the src code files).

This distinction is actually handled fine in **cc_library**, where these \*-impl.cpp files can be included in the hdrs list of files and excluded from the src list.  I humbly suggest supporting hdrs for **cc_binary** would be one way to address this.

**Comment by shahms** [comment]
Name the included file `.inc` and put it in the `srcs` attribute.

**Comment by skubica** [comment]
Good idea. Much cleaner than the C++ FAQ suggested method. This works fine. Thanks!
