### ISSUE TITLE
command is not use

### ISSUE THREAD

**Issue by geeker-smallwhite** [bazelbuild/bazel#18463]
### Description of the bug:

when I use command 'bazel'，no response 
OS: macOS

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

2023/05/21 23:00:43 could not resolve the version 'latest' to an actual version number: unable to determine latest version: could not list Bazel versions in GCS bucket: could not list GCS objects at https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/: could not fetch https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/: Get "https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/": dial tcp 172.217.160.106:443: i/o timeout

**Comment by sgowroji** [comment]
Hi @geeker-smallwhite, Could you please provide minimal steps need to reproduce the above. Thanks!

**Comment by geeker-smallwhite** [comment]
now, This issue cannot be reproduced now.

**Comment by BTLDXX-x** [comment]
hi @sgowroji ,
i met this problem by followed steps:
1.git clone the version of 6.1.1
2.run `bazel build //src:bazel-dev` 


```
could not resolve the version 'latest' to an actual version number: unable to determine latest version: could not list Bazel versions in GCS bucket: could not list GCS objects at https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/: could not fetch https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/: Get "https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/": dial tcp 142.251.42.234:443: i/o timeout
```

thanks for your help!

**Comment by BTLDXX-x** [comment]
hi @geeker-smallwhite, how did you solve this issue?  i use different vpns, but all failed.

**Comment by BTLDXX-x** [comment]
i used the bazel6.1.1 to build mediapipe0.10.0. but i met [this issue](https://github.com/google/mediapipe/issues/4296). 
then, i followed [steps](https://github.com/google/mediapipe/issues/4296#issuecomment-1570491146), but it also failed.

**Comment by geeker-smallwhite** [comment]
> hi @geeker-smallwhite, how did you solve this issue? i use different vpns, but all failed.

bazelisk maybe not use vpn network, you should config http_proxy and https_proxy in ~/.bashrc env

**Comment by BTLDXX-x** [comment]
i set the version of bazel in .bazeliskrc, it worked. thanks!

**Comment by cancan101** [comment]
@BTLDXX-x , what steps did you take in order to get Mediapipe to build?
