### ISSUE TITLE
how to import external dependence that non-bazel project

### ISSUE THREAD

**Issue by damonChenzf07** [bazelbuild/bazel#18465]
### Description of the feature request:

I have a Project A that dependent on Project B. And the Project B is not build with the bazel, which uses  the cmake.
Also, the Project B outputs only header files, dont produces any libs or  binas. I have read the examples of the rules_foreign_cc, but I dont find the way to write rules for this scene. Could somebody help me?

**Comment by Wyverald** [comment]
![image](https://github.com/bazelbuild/bazel/assets/453203/44539c76-189d-474b-a76d-c727fd93d30a)

I would recommend going to https://slack.bazel.build and providing more concrete information.
