### ISSUE TITLE
bazel version doesn't work well after installation through apt-get

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#1846]
```
root@62f6b1c16dcb:/# bazel version
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=230
INFO: Reading options for 'version' from /etc/bazel.bazelrc:
  Inherited 'common' options: --action_env=PATH --action_env=LD_LIBRARY_PATH --action_env=TMPDIR
Unrecognized option: --action_env=PATH
root@62f6b1c16dcb:/# bazel info
The 'info' command is only supported from within a workspace.
root@62f6b1c16dcb:/# vim /etc/bazel.bazelrc 
root@62f6b1c16dcb:/# rm /etc/bazel.bazelrc
root@62f6b1c16dcb:/# bazel version
Build label: 0.3.2rc2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Sep 27 17:58:19 2016 (1474999099)
Build timestamp: 1474999099
Build timestamp as int: 1474999099
root@62f6b1c16dcb:/# 
```
I used a docker to test installing the latest bazel candidate and found this error.
After deleting `/etc/bazel.bazelrc`, the output is expected.

**Comment by damienmg** [comment]
Ok we have to rollback @aehlig change

**Comment by damienmg** [comment]
Rollback sent out for review. That's a P0, release blocker

**Comment by aehlig** [comment]
On Tue, Sep 27, 2016 at 11:45:25AM -0700, Yun Peng wrote:
> ```
> root@62f6b1c16dcb:/# bazel version
> INFO: Options provided by the client:
>   Inherited 'common' options: --isatty=1 --terminal_columns=230
> INFO: Reading options for 'version' from /etc/bazel.bazelrc:
>   Inherited 'common' options: --action_env=PATH --action_env=LD_LIBRARY_PATH --action_env=TMPDIR
> Unrecognized option: --action_env=PATH
> root@62f6b1c16dcb:/# bazel info
> The 'info' command is only supported from within a workspace.
> root@62f6b1c16dcb:/# vim /etc/bazel.bazelrc 
> root@62f6b1c16dcb:/# rm /etc/bazel.bazelrc
> root@62f6b1c16dcb:/# bazel version
> Build label: 0.3.2rc2
> Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
> Build time: Tue Sep 27 17:58:19 2016 (1474999099)
> Build timestamp: 1474999099
> Build timestamp as int: 1474999099
> root@62f6b1c16dcb:/# 
> ```
> I used a docker to test installing the latest bazel candidate and found this error.
> After deleting `/etc/bazel.bazelrc`, the output is expected.

Which commit does the label 0.3.2rc2 refer to? The error seems to indicate that your
debian package is combining the latest additional files (bazel.bazelrc) with a binary
based on an old source version (that does not yet know the --action_env option).

Note that not keeping packaging and sources in sync is usually a bad idea; so the
rollback only treats the symptoms and not the underlying cause that files intended
to be packaged with only a newer source version get packaged with an older source
version. Should we reopen this bug to address the actual issue that when packaging
an old version we don't use the packaging script from that source version (and
roll forward the rolled back commit)?

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by aehlig** [comment]
Ah, never mind. The rolled back change actually was wrong; it should have read
"build --action_env=PATH" instead of "common --action_env=PATH"; interestingly
enough, that was also wrong in the design.

Will prepare a roll forward with the corresponding fix.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle
