### ISSUE TITLE
[bazel.build] Problem with /versions

### ISSUE THREAD

**Issue by ericremoreynolds** [bazelbuild/bazel#18487]
### Page link:

https://bazel.build/versions/6.2.0/extending

### Problem description (include actual vs expected text, if applicable):

The "API" tab (see screenshot) links to https://bazel.build/rules/lib/overview, instead I think it should probably link to https://bazel.build/versions/6.2.0/rules/lib/starlark-overview. In any case, the current link takes the reader to the 7.0.0 docs, which is incorrect.

<img width="1019" alt="image" src="https://github.com/bazelbuild/bazel/assets/5197585/758ba684-d8c1-468f-9753-491af2f3747d">

### Any other information you'd like to share?

Would be nice if each doc page showed the version it refers to.

**Comment by fweikert** [comment]
Fixed (also the BE link)!
