### ISSUE TITLE
0.3.2 breaks some sh_tests() with: Device or resource busy

### ISSUE THREAD

**Issue by shahms** [bazelbuild/bazel#1848]
Kythe has a couple of sh_tests which appear to be broken by the upcoming 0.3.2 release:

    $ bazel test //kythe/cxx/extractor/testdata:index_pack
    FAIL: //kythe/cxx/extractor/testdata:index_pack (see .../execroot/kythe/bazel-out/local_linux-fastbuild/testlogs/kythe/cxx/extractor/testdata/index_pack/test.log)
    $ cat .../execroot/kythe/bazel-out/local_linux-fastbuild/testlogs/kythe/cxx/extractor/testdata/index_pack/test.log
    exec ${PAGER:-/usr/bin/less} "$0" || exit 1
    -----------------------------------------------------------------------------
    rm: cannot remove '.../execroot/kythe/_tmp/index_pack_1': Device or resource busy

The target in question is:

    sh_test(
        name = "index_pack",
        size = "small",
        srcs = [
            "test_index_pack.sh",
        ],
        data = [
            "test_common.sh",
            "transcript_a.h",
            "transcript_b.h",
            "transcript_main.cc",
            "//kythe/cxx/extractor:cxx_extractor",
            "//kythe/cxx/tools:kindex_tool",
        ],
    )

I suspect this is due to the sandbox attempting to clean up after itself before the processes in the test have exited; running the test with `--verbose_failures` and `--sandbox_debug` and then running the emitted command gives (eventually):

    src/main/tools/linux-sandbox-pid1.cc:369: remount rw: /home/shahms/.cache/bazel/_bazel_shahms/f0c8a49cbf1bfaa82de86be744427f4b/bazel-sandbox/4cc73291-ef8e-4dd8-9f9f-5979a47ecbe6-0/tmp/home/shahms/.cache/bazel/_bazel_shahms/f0c8a49cbf1bfaa82de86be744427f4b/bazel-sandbox/4cc73291-ef8e-4dd8-9f9f-5979a47ecbe6-0/execroot/kythe/_tmp/index_pack_1
    src/main/tools/linux-sandbox-pid1.cc:477: sigaction(32, &sa, NULL) failed
    src/main/tools/linux-sandbox-pid1.cc:477: sigaction(33, &sa, NULL) failed
    exec ${PAGER:-/usr/bin/less} "$0" || exit 1
    -----------------------------------------------------------------------------
    rm: cannot remove '/home/shahms/.cache/bazel/_bazel_shahms/f0c8a49cbf1bfaa82de86be744427f4b/bazel-sandbox/4cc73291-ef8e-4dd8-9f9f-5979a47ecbe6-0/execroot/kythe/_tmp/index_pack_1': Device or resource busy
    src/main/tools/linux-sandbox-pid1.cc:587: waitpid returned 2
    src/main/tools/linux-sandbox-pid1.cc:607: child exited with code 1
    src/main/tools/linux-sandbox.cc:223: child exited normally with exitcode 1

**Comment by damienmg** [comment]
Seems like a sandbox issue /cc @katre @philwo

**Comment by philwo** [comment]
> rm: cannot remove '/home/shahms/.cache/bazel/_bazel_shahms/f0c8a49cbf1bfaa82de86be744427f4b/bazel-sandbox/4cc73291-ef8e-4dd8-9f9f-5979a47ecbe6-0/execroot/kythe/_tmp/index_pack_1': Device or resource busy

This message comes from the test script, not from Bazel or the linux-sandbox.
Neither the sandbox nor Bazel do any cleanup before the process exits.

The cause for this problem is this line: https://github.com/google/kythe/blob/master/kythe/cxx/extractor/testdata/test_index_pack.sh#L20

It tries to delete the TEST_TMPDIR, which won't work, because it's a bind-mount.

If instead of directly using the TEST_TMPDIR as the OUT_DIR the tests use a sub-directory here: https://github.com/google/kythe/blob/master/kythe/cxx/extractor/testdata/test_common.sh#L17, everything should work fine :)

I sent you a pull-request - could you give it a try and see if that fixes the problem for you?
https://github.com/google/kythe/pull/5

**Comment by shahms** [comment]
Thanks, that's embarrassing! I'll take a look at the PR now.
