### ISSUE TITLE
[6.3.0] Let `common` ignore unsupported options

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#18505]
Forked from #18130

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/18566

**Comment by iancha1992** [comment]
Cherry-picked again with another required commit in https://github.com/bazelbuild/bazel/pull/18609 as per https://github.com/bazelbuild/bazel/pull/18566#issuecomment-1580191416

**Comment by iancha1992** [comment]
https://github.com/bazelbuild/bazel/pull/18609 is merged. Hence, this is now closed.
