### ISSUE TITLE
How to impliment a persistent worker by c++

### ISSUE THREAD

**Issue by SupSaiYaJin** [bazelbuild/bazel#18508]
### Description of the feature request:

There are many cc_binary toolchains not supporting persistent worker, how to support them.
are there any examples?

**Comment by Pavank1992** [comment]
Hi @SupSaiYaJin, Thanks for creating this feature request. From description, your request is not very clear. Could you please elaborate your query in details. Meanwhile, I am attaching [Persistent Workers](https://bazel.build/remote/persistent) doc.

**Comment by SupSaiYaJin** [comment]
> Hi @SupSaiYaJin, Thanks for creating this feature request. From description, your request is not very clear. Could you please elaborate your query in details. Meanwhile, I am attaching [Persistent Workers](https://bazel.build/remote/persistent) doc.

for example, AarFileExtractor and AarJarsMerger action is implemented by C++, they are not support persistent worker strategy. The work is very simple but there will be a lot of such actions executed for building a Android APK. As the image below, Extracting AndroidManifest.xml will cost 600ms+ is unreasonable.
![image](https://github.com/bazelbuild/bazel/assets/10076965/3f029283-33a7-4004-bc44-1f5885446985)
