### ISSUE TITLE
Should JavaInfo.transitive_compile_time_jars contain the ijar? 

### ISSUE THREAD

**Issue by crt-31** [bazelbuild/bazel#18519]
### Description of the bug:

JavaInfo.transitive_compile_time_jars contains the compileJar passed in in the JavaInfo constructor. This was unexpected as I interpreted the documentation to say that it contains the jars that were used to compile this particular jar. 
From documentation: 
> Returns the transitive set of Jars required to build the target.

This to me implies it was the set of Jars needed to build the target, but not the target itself.

Anyway, not sure if this is a bug or if it is working as expected. If it is working as expected, the docs should probably be updated to be more clear like "Returns transitive set of Jars needed when this target is used as a compile-time dependency" or similar.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a java target. Make an aspect that outputs the JavaInfo.transitive_compile_time_jars. Notice that it includes the ijar.

### Which operating system are you running Bazel on?

Windows

### What is the output of `bazel info release`?

release 6.0.0

### Any other information, logs, or outputs that you want to share?

somewhat related to #8124

**Comment by hvadehra** [comment]
I think this would be true if we were talking about a parameter in the JavaInfo constructor, and not a field on the provider. 

Providers and the data they contain are meant for consumption by downstream targets. In that context, the documentation, while terse, is accurate.
