### ISSUE TITLE
[Mirror] gazelle v0.31.0

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel#18522]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.31.0/bazel-gazelle-v0.31.0.tar.gz

**Comment by Pavank1992** [comment]
Please find the below mirror artifact-
https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.31.0/bazel-gazelle-v0.31.0.tar.gz
