### ISSUE TITLE
Windows, native: get rid of process-wrapper build dependency

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#1852]
`//src/main/tools:process-wrapper` is heavily dependent on the POSIX API. Implement it for Windows API too.

**Comment by dslomov** [comment]
We do not use process-wrapper on Windows, we use Win32 process control API directly, thanks to @lberki

**Comment by dslomov** [comment]
(reopen to track getting rid of build dependency)

**Comment by dslomov** [comment]
Oh actually I take that back, we are still using process-wrapper for `bazel run`

**Comment by benvanik** [comment]
I'm still unable to bazel run Windows executables. Is there an update on this?

**Comment by dslomov** [comment]
Any details? Which executables?

**Comment by benvanik** [comment]
Ah, sorry!
With bazel 0.5.2 on Windows 10: cc_test and cc_binary fail to run. cc_tests will execute through bazel test, though just not through bazel run.

Example cc_test: https://github.com/google/xrtl/blob/master/xrtl/base/BUILD#L38
```
λ bazel run //xrtl/base:array_view_test
INFO: Found 1 target...
Target //xrtl/base:array_view_test up-to-date:
  C:/users/ben/appdata/local/temp/_bazel_ben/4qe-y0h3/execroot/xrtl/bazel-out/msvc_x64-dbg/bin/xrtl/base/array_view_test.exe
INFO: Elapsed time: 6.229s, Critical Path: 4.53s

INFO: Running command line: C:/users/ben/appdata/local/temp/_bazel_ben/4qe-y0h3/execroot/xrtl/bazel-out/msvc_x64-dbg/bin/xrtl/base/array_view_test.exe
ERROR: process-wrapper is not yet implemented on Windows.
...
```

Example cc_binary: https://github.com/google/xrtl/blob/master/xrtl/gfx/spirv/BUILD#L31
```
λ bazel run //xrtl/gfx/spirv:shader_tool
INFO: Found 1 target...
Target //xrtl/gfx/spirv:shader_tool up-to-date:
  C:/users/ben/appdata/local/temp/_bazel_ben/4qe-y0h3/execroot/xrtl/bazel-out/msvc_x64-dbg/bin/xrtl/gfx/spirv/shader_tool.exe
INFO: Elapsed time: 31.764s, Critical Path: 8.34s

INFO: Running command line: C:/users/ben/appdata/local/temp/_bazel_ben/4qe-y0h3/execroot/xrtl/bazel-out/msvc_x64-dbg/bin/xrtl/gfx/spirv/shader_tool.exe
ERROR: process-wrapper is not yet implemented on Windows.
...
```

Manually executing either executable works.

**Comment by dslomov** [comment]
@philwo could you take a look?

**Comment by ocombe** [comment]
Same problem for me on windows 10 with bazel 0.5.2 --> https://github.com/bazelbuild/bazel/blob/master/src/main/tools/process-wrapper-windows.cc

```sh
bazel run @io_bazel_rules_typescript_node//:bin/npm install
INFO: Found 1 target...
INFO: Elapsed time: 1,515s, Critical Path: 0,01s

INFO: Running command line: C:/users/olivier/appdata/local/temp/_bazel_olivier/l40idi7t/external/io_bazel_rules_typescript_node/bin/npm install
ERROR: process-wrapper is not yet implemented on Windows.
Called with args:
argv[0]=(C:\users\olivier\appdata\local\temp\_bazel_olivier\l40idi7t\execroot\__main__\_bin\process-wrapper.exe)
argv[1]=(-1)
argv[2]=(15)
argv[3]=(-)
argv[4]=(-)
argv[5]=(C:/users/olivier/appdata/local/temp/_bazel_olivier/l40idi7t/external/io_bazel_rules_typescript_node/bin/npm)
argv[6]=(install)
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

**Comment by philwo** [comment]
If I read the code correctly, the "bazel run" command never worked on Windows, because it always uses the process-wrapper to run things: https://github.com/bazelbuild/bazel/blob/4ca8b8f98f043ef624b2d1605d658aa39c2c63dc/src/main/java/com/google/devtools/build/lib/runtime/commands/RunCommand.java#L261

This is pretty amazing considering that people added Windows-specific code to deal with runfiles (https://github.com/bazelbuild/bazel/commit/5206a67ff28f8479d4ce63ecf684f7e24404ac06#diff-e2f2bda74cebaff938dafb4555b9f144).

The fix is very simple, we just have to add a check for Windows and if that's true, don't add the process-wrapper prefix to the cmdline. I'll send a fix.

**Comment by dslomov** [comment]
It did work in glorious msys-ful days.

**Comment by philwo** [comment]
@dslomov Ahh! Of course! I totally forgot about that already.
