### ISSUE TITLE
Ability to build OSGi bundles with Bazel

### ISSUE THREAD

**Issue by OliverKaunds** [bazelbuild/bazel#18521]
I recently started exploring bazel. I am amazed at the build speed for Java projects. However, the final jar that I require is not an OSGi bundle. I need my final JAR to be built as an OSGi bundle with ability to specify every package that I want to expose as public and the packages that I want to import including the version.

This is possible in pom.xml using maven but not Bazel.
I am working on AEM a content management system, here all Jars are deployed as OSGi bundles. Therefore the need for Bazel to support OSGI bundles.

**Comment by hvadehra** [comment]
We are trying to move as much of language-specific code out of Bazel and into Starlark, so I don't think something like this will be shipped with Bazel.

You should be able to achieve this by writing your own `osgi_bundle` rule in Starlark. 

Maybe something like: https://github.com/google/guice/blob/master/osgi.bzl ?
