### ISSUE TITLE
[6.3.0] Use extension rather than local names in ModuleExtensionMetadata

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#18531]
Forked from #18528

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/18535

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/18536

**Comment by iancha1992** [comment]
Closing this issue as the PR has been merged.
