### ISSUE TITLE
Windows, native: implement build-runfiles

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#1853]
`//src/main/tools:build-runfiles` is dependent on the POSIX API. Implement it for Windows API too.

**Comment by dslomov** [comment]
Hmm do we still even call build-runfiles on Windows?

**Comment by laszlocsomor** [comment]
Good question, I don't know. It's a transitive dependency of //src:bazel, but maybe we don't need to pull it in for Windows/MSVC.

**Comment by dslomov** [comment]
We do not use build-runfiles on Windows, so the build dependency should be removed
