### ISSUE TITLE
3.2rc2 does not find msys-2.0.dll

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#1854]
Seems like there is some dependency or documentation missing when trying to get the Windows version of the rc2 to run on Windows. It complains:

    ---------------------------
    bazel-0.3.2rc2-windows-x86_64.exe - System Error
    ---------------------------
    The program can't start because msys-2.0.dll is missing from your computer. Try reinstalling the program to fix this problem. 
    ---------------------------
    OK   
    ---------------------------

`msys` is installed in `C:\msys`, though.

**Comment by meteorcloudy** [comment]
Try to add `C:\msys\usr\bin` in to `PATH` ? We will add this to the document soon.

**Comment by abergmeier-dsfishlabs** [comment]
Could you turn that search path into an option, please? I do not even want to know how many instances of _msys_ I have on my system and none is in `PATH` for obvious reasons.

**Comment by meteorcloudy** [comment]
Sorry, the msys path has to be added into PATH, because currently the bazel binary itself still depends on msys-2.0.dll. 
We are creating a chocolatey package for Windows, it will automatically set up the environment if you install Bazel via it.

**Comment by petemounce** [comment]
That DLL is added to the PATH via the work done in #1742 (discussion in #1453), so if bazel is installed to Windows via the chocolatey package (which will start to work as soon as I notice a 0.3.2-or-later release), this will work.

**Comment by damienmg** [comment]
Closing this one since there is a workaround and the chocolatey package will fix it once and for all :p
