### ISSUE TITLE
[7.0.0] declare_symlink: remove experimental warning

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#18554]
Forked from #18313

**Comment by iancha1992** [comment]
As per the comment, https://github.com/bazelbuild/bazel/pull/18313#issuecomment-1587821906, it is not necessary to add this change to 6.3.0. Hence, this is now closed.

cc: @keertk @Pavank1992 @sgowroji

**Comment by Wyverald** [comment]
This shouldn't be necessary, as major releases are cut from master. Issues should only be "forked" to the 7.0.0 milestone after the first RC is cut.
