### ISSUE TITLE
ERROR: No toolchain found for cpu 'aarch64'.

### ISSUE THREAD

**Issue by joshsuihn** [bazelbuild/bazel#1855]
I built bazel on Nvidia Jetson TX1,  tried to run TensorFlow with this command (to enable GPU support): 
$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer 

_WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: No toolchain found for cpu 'aarch64'. Valid cpus are: [
  k8,
  piii,
  arm,
  darwin,
].

I looked into the following bazel source codes 
1. tools/cpp/CROSSTOOL
2. src/main/java/com/google/devtools/build/lib/rules/cpp/CrosstoolConfigurationLoader.java
3. tools/cpp/cc_configure.bzl
4. src/main/java/com/google/devtools/build/lib/rules/cpp/CrosstoolConfigurationIdentifier.java
5. etc. 

That error messages is thrown by "CrosstoolConfigurationLoader.java"
344  if (selectedIdentifier == null) {
345       StringBuilder cpuBuilder = new StringBuilder();
346       for (CrosstoolConfig.DefaultCpuToolchain selector : release.getDefaultToolchainList()) {
347         cpuBuilder.append("  ").append(selector.getCpu()).append(",\n");
348       }
349       throw new InvalidConfigurationException(
350           "No toolchain found for cpu '" + desiredCpu
351           + "'. Valid cpus are: [\n" + cpuBuilder + "]");
352     }

It seems to me that 
"desiredCpu" comes from 'uname -m", and the list of selector (cpuBuilder) comes from "CROSSTOOL"

But, although I added 
"default_toolchain {
   cpu: "aarch64"
    toolchain_identifier: "local_linux"
 }" to CROSSTOLL 

It didn't work.  

Where does Default Toolchain List comes from?
Any suggestion or solutions to fix this problem? 

Thanks!

**Comment by meteorcloudy** [comment]
Not sure why it didn't work, did you rebuild bazel with the change?
Or try `bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer --cpu=k8` see if it helps?

**Comment by joshsuihn** [comment]
I'm getting the same error with "bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer --cpu=k8".
Interestingly, without "--config=cuda", it works well.

**Comment by meteorcloudy** [comment]
I guess it's TensorFlow doesn't have configuration for `aarch64 `, can you file this bug to them?

**Comment by joshsuihn** [comment]
Oh  yes, I think tensorflow doens't have it. Sure. I will

**Comment by damienmg** [comment]
Since it is on the cuda crosstool this is definetly on TF side. Closing

**Comment by alexryan** [comment]
@joshsuihn, I am having this exact same issue with the NVIDIA Jetson TX1.
Did you find a solution?
```
bazel build -c opt --verbose_failures --config=cuda //tensorflow/tools/pip_package:build_pip_package

ERROR: No toolchain found for cpu 'aarch64'. Valid cpus are: [
  k8,
  piii,
  arm,
  darwin,
].
INFO: Elapsed time: 3.013s
```

**Comment by joshsuihn** [comment]
It turned out the error was not caused by Bazel; it was a TensorFlow issue. 
But, I could build Bazel and TensorFlow on TX-1 only with v0.3.1 and 0.10.0RC, respectively. 
In particular, I could succeed in building TensorFlow only with a specific commit:  
( try "git reset a5f8f42cb29d890650c4ca5fac6654884856a8e1" after cloning TF master ) 

My impression is TensorFlow version was very sensitive to build on TX-1.
You may have several errors during the build because TX-1 has small resources(memory). Build took many hours.
