### ISSUE TITLE
undeclared inclusion(s) in rule when trying to build any isaac tutorial app

### ISSUE THREAD

**Issue by MichaelProvidia** [bazelbuild/bazel#18576]
### Description of the bug:

few errors of undeclared inclusion(s) in rule when trying to build any isaac tutorial app.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

try to launch bazel build //apps/tutorials/<issac-sdk-app> inside <issac-sdk-dir>/sdk

<issac-sdk-app> example : ping.

### Which operating system are you running Bazel on?

Ubuntu 20.04

### What is the output of `bazel info release`?

release 5.4.0- (@non-git)

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

accroding to the the guide here : 
(https://bazel.build/install/compile-source#bootstrap-unix-overview) following "Bootstrap Bazel on Ubuntu Linux, macOS, and other Unix-like systems" section
I'm trying to build isaac sdk apps in Jetson Agx Orin with ubuntu 20.04 and jetpack 5.1.1, I tried to build the app with bazel 5.4.0.

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
fatal: not a git repository (or any of the parent directories): .git
```

### Any other information, logs, or outputs that you want to share?

ERROR: /home/orin2/.cache/bazel/_bazel_orin2/53af14c2eca98f05d9cf0f64d89d1dc2/external/redis/BUILD.bazel:26:11: Compiling deps/lua/src/lapi.c failed: undeclared inclusion(s) in rule '@redis//:lua':
this rule is missing dependency declarations for the following files included by 'deps/lua/src/lapi.c':
  '/usr/include/stdc-predef.h'
  '/usr/include/assert.h'
  '/usr/include/features.h'
  '/usr/include/aarch64-linux-gnu/sys/cdefs.h'
  '/usr/include/aarch64-linux-gnu/bits/wordsize.h'
  '/usr/include/aarch64-linux-gnu/bits/long-double.h'
  '/usr/include/aarch64-linux-gnu/gnu/stubs.h'
  '/usr/include/aarch64-linux-gnu/gnu/stubs-lp64.h'
  '/usr/include/math.h'
  '/usr/include/aarch64-linux-gnu/bits/libc-header-start.h'
  '/usr/include/aarch64-linux-gnu/bits/types.h'
  '/usr/include/aarch64-linux-gnu/bits/timesize.h'
  '/usr/include/aarch64-linux-gnu/bits/typesizes.h'
  '/usr/include/aarch64-linux-gnu/bits/time64.h'
  '/usr/include/aarch64-linux-gnu/bits/math-vector.h'
  '/usr/include/aarch64-linux-gnu/bits/libm-simd-decl-stubs.h'
  '/usr/include/aarch64-linux-gnu/bits/floatn.h'
  '/usr/include/aarch64-linux-gnu/bits/floatn-common.h'
  '/usr/include/aarch64-linux-gnu/bits/flt-eval-method.h'
  '/usr/include/aarch64-linux-gnu/bits/fp-logb.h'
  '/usr/include/aarch64-linux-gnu/bits/fp-fast.h'
  '/usr/include/aarch64-linux-gnu/bits/mathcalls-helper-functions.h'
  '/usr/include/aarch64-linux-gnu/bits/mathcalls.h'
  '/usr/include/aarch64-linux-gnu/bits/mathinline.h'
  '/usr/lib/gcc/aarch64-linux-gnu/9/include/stdarg.h'
  '/usr/include/string.h'
  '/usr/lib/gcc/aarch64-linux-gnu/9/include/stddef.h'
  '/usr/include/aarch64-linux-gnu/bits/types/locale_t.h'
  '/usr/include/aarch64-linux-gnu/bits/types/__locale_t.h'
  '/usr/include/strings.h'
  '/usr/include/aarch64-linux-gnu/bits/strings_fortified.h'
  '/usr/include/aarch64-linux-gnu/bits/string_fortified.h'
  '/usr/lib/gcc/aarch64-linux-gnu/9/include/limits.h'
  '/usr/lib/gcc/aarch64-linux-gnu/9/include/syslimits.h'
  '/usr/include/limits.h'
  '/usr/include/aarch64-linux-gnu/bits/posix1_lim.h'
  '/usr/include/aarch64-linux-gnu/bits/local_lim.h'
  '/usr/include/linux/limits.h'
  '/usr/include/aarch64-linux-gnu/bits/posix2_lim.h'
ERROR: /home/orin2/.cache/bazel/_bazel_orin2/53af14c2eca98f05d9cf0f64d89d1dc2/external/redis/BUILD.bazel:26:11: Compiling deps/lua/src/lparser.c failed: undeclared inclusion(s) in rule '@redis//:lua':
this rule is missing dependency declarations for the following files included by 'deps/lua/src/lparser.c':
  '/usr/include/stdc-predef.h'
  '/usr/include/string.h'
  '/usr/include/aarch64-linux-gnu/bits/libc-header-start.h'
  '/usr/include/features.h'
  '/usr/include/aarch64-linux-gnu/sys/cdefs.h'
  '/usr/include/aarch64-linux-gnu/bits/wordsize.h'
  '/usr/include/aarch64-linux-gnu/bits/long-double.h'
  '/usr/include/aarch64-linux-gnu/gnu/stubs.h'
  '/usr/include/aarch64-linux-gnu/gnu/stubs-lp64.h'
  '/usr/lib/gcc/aarch64-linux-gnu/9/include/stddef.h'
  '/usr/include/aarch64-linux-gnu/bits/types/locale_t.h'
  '/usr/include/aarch64-linux-gnu/bits/types/__locale_t.h'
  '/usr/include/strings.h'
  '/usr/include/aarch64-linux-gnu/bits/strings_fortified.h'
  '/usr/include/aarch64-linux-gnu/bits/string_fortified.h'
  '/usr/lib/gcc/aarch64-linux-gnu/9/include/stdarg.h'
  '/usr/lib/gcc/aarch64-linux-gnu/9/include/limits.h'
  '/usr/lib/gcc/aarch64-linux-gnu/9/include/syslimits.h'
  '/usr/include/limits.h'
  '/usr/include/aarch64-linux-gnu/bits/posix1_lim.h'
  '/usr/include/aarch64-linux-gnu/bits/local_lim.h'
  '/usr/include/linux/limits.h'
  '/usr/include/aarch64-linux-gnu/bits/posix2_lim.h'
  '/usr/include/math.h'
  '/usr/include/aarch64-linux-gnu/bits/types.h'
  '/usr/include/aarch64-linux-gnu/bits/timesize.h'
  '/usr/include/aarch64-linux-gnu/bits/typesizes.h'
  '/usr/include/aarch64-linux-gnu/bits/time64.h'
  '/usr/include/aarch64-linux-gnu/bits/math-vector.h'
  '/usr/include/aarch64-linux-gnu/bits/libm-simd-decl-stubs.h'
  '/usr/include/aarch64-linux-gnu/bits/floatn.h'
  '/usr/include/aarch64-linux-gnu/bits/floatn-common.h'
  '/usr/include/aarch64-linux-gnu/bits/flt-eval-method.h'
  '/usr/include/aarch64-linux-gnu/bits/fp-logb.h'
  '/usr/include/aarch64-linux-gnu/bits/fp-fast.h'
  '/usr/include/aarch64-linux-gnu/bits/mathcalls-helper-functions.h'
  '/usr/include/aarch64-linux-gnu/bits/mathcalls.h'
  '/usr/include/aarch64-linux-gnu/bits/mathinline.h'
ERROR: /home/orin2/.cache/bazel/_bazel_orin2/53af14c2eca98f05d9cf0f64d89d1dc2/external/com_nvidia_isaac_engine/engine/alice/tools/BUILD:48:16: Compiling engine/alice/tools/main.cpp failed: undeclared inclusion(s) in rule '@com_nvidia_isaac_engine//engine/alice/tools:main':
this rule is missing dependency declarations for the following files included by 'engine/alice/tools/main.cpp':
  '/usr/include/stdc-predef.h'
  '/usr/include/c++/9/string'
  '/usr/include/aarch64-linux-gnu/c++/9/bits/c++config.h'
  '/usr/include/aarch64-linux-gnu/c++/9/bits/os_defines.h'
  '/usr/include/features.h'
  '/usr/include/aarch64-linux-gnu/sys/cdefs.h'
  '/usr/include/aarch64-linux-gnu/bits/wordsize.h'
  '/usr/include/aarch64-linux-gnu/bits/long-double.h'
  '/usr/include/aarch64-linux-gnu/gnu/stubs.h'
  '/usr/include/aarch64-linux-gnu/gnu/stubs-lp64.h'
  '/usr/include/aarch64-linux-gnu/c++/9/bits/cpu_defines.h'
  '/usr/include/c++/9/bits/stringfwd.h'
  '/usr/include/c++/9/bits/memoryfwd.h'
  '/usr/include/c++/9/bits/char_traits.h'
  '/usr/include/c++/9/bits/stl_algobase.h'
  '/usr/include/c++/9/bits/functexcept.h'
  '/usr/include/c++/9/bits/exception_defines.h'
  '/usr/include/c++/9/bits/cpp_type_traits.h'
  '/usr/include/c++/9/ext/type_traits.h'
  '/usr/include/c++/9/ext/numeric_traits.h'
  '/usr/include/c++/9/bits/stl_pair.h'
  '/usr/include/c++/9/bits/move.h'
  '/usr/include/c++/9/bits/concept_check.h'
  '/usr/include/c++/9/type_traits'
  '/usr/include/c++/9/bits/stl_iterator_base_types.h'
  '/usr/include/c++/9/bits/stl_iterator_base_funcs.h'
  '/usr/include/c++/9/debug/assertions.h'
  '/usr/include/c++/9/bits/stl_iterator.h'
  '/usr/include/c++/9/bits/ptr_traits.h'
  '/usr/include/c++/9/debug/debug.h'
  '/usr/include/c++/9/bits/predefined_ops.h'
  '/usr/include/c++/9/bits/postypes.h'
  '/usr/include/c++/9/cwchar'
  '/usr/include/wchar.h'
  '/usr/include/aarch64-linux-gnu/bits/libc-header-start.h'
  '/usr/include/aarch64-linux-gnu/bits/floatn.h'
  '/usr/include/aarch64-linux-gnu/bits/floatn-common.h'
  '/usr/lib/gcc/aarch64-linux-gnu/9/include/stddef.h'
  '/usr/lib/gcc/aarch64-linux-gnu/9/include/stdarg.h'
  '/usr/include/aarch64-linux-gnu/bits/wchar.h'
  '/usr/include/aarch64-linux-gnu/bits/types/wint_t.h'
  '/usr/include/aarch64-linux-gnu/bits/types/mbstate_t.h'
  '/usr/include/aarch64-linux-gnu/bits/types/__mbstate_t.h'
  '/usr/include/aarch64-linux-gnu/bits/types/__FILE.h'
  '/usr/include/aarch64-linux-gnu/bits/types/FILE.h'
  '/usr/include/aarch64-linux-gnu/bits/types/locale_t.h'
  '/usr/include/aarch64-linux-gnu/bits/types/__locale_t.h'
  '/usr/include/aarch64-linux-gnu/bits/wchar2.h'

**Comment by Pavank1992** [comment]
@MichaelProvidia, Could you please share the minimal steps to reproduce the issue with sample code?
