### ISSUE TITLE
[6.3.0] Conditionally set output_paths based on Remote Executor capabilities

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#18575]
Forked from #18270

**Comment by iancha1992** [comment]
There was a rollback from https://github.com/bazelbuild/bazel/pull/18270. So we cannot cherry-pick. There may be a new PR as per the comment: https://github.com/bazelbuild/bazel/pull/18270#issuecomment-1577012910. Closing this now as we'll get a new PR and we can cherry-pick that one

cc: @keertk, @Pavank1992, @sgowroji
