### ISSUE TITLE
Cherry-pick some commits for Bazel release

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#1857]
Please cherry-pick eb87208599cdb9ede31efe793485e9096ab4a773 c30432cc32886a2b50e2b902f7f572347a6886a4
They fix this important issue for Windows. https://github.com/bazelbuild/bazel/issues/1847

**Comment by damienmg** [comment]
Add this to the release bug :)

**Comment by meteorcloudy** [comment]
What's release bug? I don't see such a label, where is it?

**Comment by katre** [comment]
#1840 is the release tracking issue. The type is currently "process", maybe we need a more specific tag?

**Comment by meteorcloudy** [comment]
I see thanks!

**Comment by damienmg** [comment]
Process and release blocker seems enough to find it easily :)
