### ISSUE TITLE
Allow rewriting to a list of URLs with the bazel URL rewriter

### ISSUE THREAD

**Issue by matts1** [bazelbuild/bazel#18585]
### Description of the feature request:

http_file supports the URLs tag, which goes through the list and tries to find the first matching entry. We would want to use that mechanism to allow rewriting a URL to a list of URLs with the bazel URL rewriter. For example:

```
rewrite (.*) https://storage.cloud.google.com/bazel_cache/$1 $1
```
This example would allow you to use your mirror, but fall back to the real URL if the mirror isn't available. This is useful for local development, where any repo rules you write may not yet be in the mirror.

### What underlying problem are you trying to solve with this feature?

Our use case (which seems like a pretty common use case) is that we have a mirror of all the files required by bazel for repo rules.

This gives us the following bazel downloader config:
```
rewrite (.*) https://storage.cloud.google.com/bazel_cache/$1
```

This works great for release builds, but introduces friction for local development, as devs will need to manually upload things into the mirror themselves (which is also a security hazard).

What I would like is for CI builds to use the config above, and for local dev builds to use the following config:
```
rewrite (.*) https://storage.cloud.google.com/bazel_cache/$1 $1
```

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

6.2.0

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
N/A
```

**Comment by aiuto** [comment]
+1 to this.  No organization should pull things off the net repeatedly.
What I would actually like to see is download removed from the bazel process entirely. Requests to download should go to a distinct process, where bazel provides a reference implementation. An organization can replace that process with whatever kind of URL caching and rewriting they require.
One can even run a permissive downloader on developer machines, and have a caching only version for CI.

**Comment by matts1** [comment]
I do really like that idea. One idea we considered was adding a rewrite rule like `rewrite (.*) localhost:<port>/$1`, but we discarded it because of a few reasons, like having to ensure ourselves that it was running all the time, not being able to select the port, and having to create our own HTTPS certificates and whatnot. This provides a much cleaner way to do something like this.

My only concern is the time investment - it seems like a lot of work in comparison with my initial suggestion.

**Comment by aiuto** [comment]
Sure. It is a time investment. My question to myself would be when does it overall get cheaper to build that kind of thing than to have 1000 different security teams verify that Bazel's download code has no network security holes.

**Comment by matts1** [comment]
Just a bit of a feature suggestion if something like that was implemented - It'd be awesome if it was modular. I'd love to be able to write something like:

```python3
# Bazel could provide implementations of common handlers
from bazel import BaseHandler, DefaultHandler, RewriteHandler, MultiUrlHandler

class AutoMirrorHandler(BaseHandler):
  def handle(self, url):
    result = super().handle(url)
    f = tempfile()
    f.write(result.data)
    subprocess.run(f"gsutil cp {f} gs://bazel-mirror/{url}")
    return result

class AscHandler(BaseHandler):
  """Verifies that <url>/foo.asc matches <url>/foo and that the certificate is generated by someone trusted"""

mirror_handler = RewriteHandler(lambda url: "gs://bazel-mirror/" + url, GsHandler(auth = ...))
if cfg == "dev":
  return MultiUrlHandler([mirror_handler, AutoMirrorRequestHandler(AscHandler(DefaultHandler))])
else:
  return mirror_handler
```

**Comment by cameron-martin** [comment]
[The docs](https://bazel.build/reference/command-line-reference#flag--experimental_downloader_config) suggest this is possible already:

> It is possible for multiple `rewrite` directives for the same URL to be give, and in this case multiple URLs will be returned.

**Comment by matts1** [comment]
Ah, thanks, I didn't notice that. I've confirmed that this works.
