### ISSUE TITLE
No found coverage inside package "external"

### ISSUE THREAD

**Issue by RP-jefersonperito** [bazelbuild/bazel#18597]
### Description of the bug:

Executing a bazel coverage, java classes inside package "external" does not report code coverage, renaming this package coverage happens without problem at all.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Creating a package named "external", add a class and submit it to code coverage action

### Which operating system are you running Bazel on?

MacOS Ventura 13.4

### What is the output of `bazel info release`?

release 5.3.1

### Have you found anything relevant by searching the web?

Nothing

**Comment by Pavank1992** [comment]
Hi @RP-jefersonperito, Could you please update bazel version to latest and test this. Seems this issue is fixed [here](https://github.com/bazelbuild/bazel/issues/16208) in bazel version 6.0.0 onwords.

**Comment by RP-jefersonperito** [comment]
Thanks mate!
