### ISSUE TITLE
Bazel at head does not work with rules_jvm_external latest release

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#18596]
### Description of the bug:

Trying to update to rules_jvm_external 5.2.  The bazel build fails with messages like
```
DEBUG: /usr/local/google/home/aiuto/.cache/bazel/_bazel_aiuto/c42451a13f00e0b53b5ffe5391e00b77/external/rules_jvm_external/coursier.bzl:372:14: Lock file should be updated. Please run `REPIN=1 bazel run @unpinned_maven//:pin`
ERROR: /usr/local/google/home/aiuto/ws/bazel/third_party/BUILD:348:12: no such target '@maven//:com_google_guava_guava_file': target 'com_google_guava_guava_file' not declared in package '' defined by /usr/local/google/home/aiuto/.cache/bazel/_bazel_aiuto/c42451a13f00e0b53b5ffe5391e00b77/external/maven/BUILD (Tip: use `query "@maven//:*"` to see all the targets in that package) and referenced by '//third_party:guava'
ERROR: /usr/local/google/home/aiuto/ws/bazel/third_party/BUILD:348:12: no such target '@maven//:com_google_guava_failureaccess_file': target 'com_google_guava_failureaccess_file' not declared in package '' defined by /usr/local/google/home/aiuto/.cache/bazel/_bazel_aiuto/c42451a13f00e0b53b5ffe5391e00b77/external/maven/BUILD (Tip: use `query "@maven//:*"` to see all the targets in that package) and referenced by '//third_party:guava'
ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted:
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Patch https://github.com/bazelbuild/bazel/pull/18595

```
REPIN=1 bazel run @unpinned_maven//:pin
bazel build //src:bazel_nojdk
```

This is blocking SBOM work for Bazel.

cc: @shs96c, @radvani13 

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

Take bazel from head

### Any other information, logs, or outputs that you want to share?

I pounded on this for a few hours and learned a few things:
- We have some strange third party things which shadow maven, like
```
java_import(
    name = "guava",
    jars = [
        "@maven//:com_google_guava_guava_extension_file",
        "@maven//:com_google_guava_failureaccess_file",
    ],
    applicable_licenses = [":guava_license"],
    exports = [
        ":error_prone_annotations",
        ":jcip_annotations",
        ":jsr305",
    ],
)
```

- the '_file' targets (e.g. `@maven//:com_google_guava_failureaccess_file`) no longer exist in 5.2
- what you have to work with is like this:
```
jvm_import(
        name = "com_google_guava_failureaccess",
        jars = ["v1/https/repo1.maven.org/maven2/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar"],
        deps = [
        ],
        tags = [
                "maven_coordinates=com.google.guava:failureaccess:1.0.1",
                "maven_url=https://repo1.maven.org/maven2/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar",
        ],
        visibility = ["//visibility:public"],
)
alias(
        name = "com_google_guava_failureaccess_1_0_1",
        actual = "com_google_guava_failureaccess",
        visibility = ["//visibility:public"],
)
genrule(
     name = "com_google_guava_failureaccess_1_0_1_extension",
     srcs = ["@com_google_guava_failureaccess_1_0_1//file"],
     outs = ["v1/https/repo1.maven.org/maven2/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar"],
     cmd = "cp $< $@",
     visibility = ["@//visibility:private"]
)
```
- if you try to use the `jvm_import` target targets in a `java_import` rule you get errors like
```
in jars attribute of java_import rule //third_party:netty_checked_in: should not refer to Java rules. Since this rule was created by the macro 'distrib_java_import', the error might have been caused by the macro implementation
```
The sad part is that it is not a java rule, it's really an import. We could make java_import less strict here.
- using the `@com_google_guava_failureaccess_1_0_1//file` works sometimes, but I have not figure out the pattern
- using the "_extension" version does not work because it is private.

Hmmm... I wonder if we made the extension ones public, and changed s/_file/_extension/ in third_party/BUILD.  Maybe for tomorrow.

**Comment by aiuto** [comment]
FWIW. This should be at a P1 because it blocks compliance work. I spent some time diagnosing it today, but the guava thing is just such a mess I got lost. It's going to need an expert in why we have the dependencies we do.

**Comment by meteorcloudy** [comment]
This is because we do need the patch file you disabled here: https://github.com/bazelbuild/bazel/pull/18595/files#diff-a7b969a66e4cf15e076089c4b3ddca51a3e02750d07938fbb7607af2645fdb9eR359

I tried to upstream the change in https://github.com/bazelbuild/rules_jvm_external/pull/877, but got rejected since it's only needed for Bazel's bootstrap build.

**Comment by meteorcloudy** [comment]
Sent https://github.com/bazelbuild/bazel/pull/18603

**Comment by shs96c** [comment]
If this is the same issue as before, the underlying problem here is that the Bazel JUnit test runner leaks all its dependencies on to the classpath. To avoid these issues, the test runner should really only depend on classes in the JRE and a (non-linked) version of JUnit. Of course, rewriting the Bazel testrunner is quite a lot of work, but the advantage of not leaking dependencies is probably worth it.

FWIW, this is what we did with `contrib_rules_jvm`'s [JUnit 5 test runner](https://github.com/bazel-contrib/rules_jvm/tree/main/java/src/com/github/bazel_contrib/contrib_rules_jvm/junit5)

**Comment by meteorcloudy** [comment]
@shs96c I believe this is unrelated to https://github.com/bazelbuild/bazel/issues/18214

**Comment by aiuto** [comment]
Yes. I think this is a different problem. It is that third_party/BUILD has references into maven downloaded things and the labels all have to update.

**Comment by aiuto** [comment]
#18603 may avoid the problem for a while, but having to patch coursier.bzl is ugly.
The scheme in third_party/BUILD needs replacing.
This just occurred to me...

For all the rules in //third_party/BUILD which are now merely re-aggregate things downloaded from Maven, and not actual jars, we do not need the rule to be in //third_party.  Those collections are our own re-labeling of things, and the targets could be anywhere.  Removing them from third_party would make updates to them easier.
