### ISSUE TITLE
Ability to remove linker flag for build?

### ISSUE THREAD

**Issue by celskeggs** [bazelbuild/bazel#186]
I'm trying to build a package that is supposed to be built with absolutely no dependencies (no libc, no libstdc++, etc.) I have the following BUILD file:

```
cc_library(
    name = "linux-x86",
    srcs = ["core.c", "entry.S"],
    copts = ["-nostdlib", "-nostdinc", "-m32"],
    linkopts = ["-nostdlib", "-nostdinc", "-m32"],
)
```

My build is failing, and according to `--verbose_failures`, the command being executed is:

```
(cd /home/skeggsc/.cache/bazel/_bazel_skeggsc/36897e6dd9c785dc00c71df5dc0d0faa/bazel-workspace && \
  exec env - \
  /usr/bin/gcc -shared -o bazel-out/local_linux-fastbuild/bin/libsyscall/linux-x86/liblinux-x86.so bazel-out/local_linux-fastbuild/bin/libsyscall/linux-x86/_objs/linux-x86/libsyscall/linux-x86/core.pic.o bazel-out/local_linux-fastbuild/bin/libsyscall/linux-x86/_objs/linux-x86/libsyscall/linux-x86/entry.pic.o -nostdlib -nostdinc -m32 -lstdc++ -B/usr/bin/ -Wl,-S)
```

This includes `-lstdc++`, which is definitely not something that I want to include in the build. I tried using `nocopts` to eliminate this, but I couldn't get it to work - probably because this is part of the linking process, not the compilation process.

I can see that the option is being specified in `//tools/cpp:CROSSTOOL`:

```
linker_flag: "-lstdc++"
```

I could remove this - but then it would also affect all the other builds in the same workspace (assuming that I made a workspace-local copy of the systemwide tools directory.)

It appears that these toolchains are being referenced by the `cc_toolchain` rules in `//tools/cpp:BUILD`, but the only information available about `cc_toolchain` is that custom uses aren't supported, so I'm not sure how I could accomplish what I want by messing with this.

What's the proper way to override this linker flag?

**Comment by hanwen** [comment]
I had a short look, but there doesn't seem to be a good way right now.

Do you need this library to be dynamically linked? Then you can just add linkstatic=1 to the library. On link, since no symbol resolves to libstdc++, it should not make a difference.

**Comment by ulfjack** [comment]
We're moving all flags to the CROSSTOOL file and use features to enable / disable sets of flags. That should eventually allow disabling linking of libstdc++ or other things by disabling the corresponding features.

**Comment by PiotrSikora** [comment]
Related: it would be great if Bazel could link C (not C++) software without `-lstdc++`.

It can already differentiate between C and C++, because `cxx_flag` isn't added when compiling C sources, so hopefully this should be easier to implement than generic flag filtering.

**Comment by ulfjack** [comment]
My previous comment describes how that would work. It wouldn't be automatic, but you could enable (or disable) it per cc_binary. We could make it automatic if there's no C++ code in the transitive closure, but that's more work.

**Comment by UnaPlugin** [comment]
There are some **LD_FLAGS** automatically added in the final compiling. Just like ```-lm``` or ```-lz```. I'm now hitting a problem of the flag ```-lpthread```. From somewhere, I see people say it should be written as ```-pthread```, not ```-lpthread```. 
Do you know which file defines the ```LD_FLAGS``` in final gcc compiling of bazel?

**Comment by hlopko** [comment]
See the new revamped C++ toolchain configuration https://docs.bazel.build/versions/0.26.0/cc-toolchain-config-reference.html. This issue can be solved by writing a custom C++ toolchain, and providing a feature providing flags in question, and this feature can be enabled/disabled by individual targets. I'll close this issue now, feel free to complain if this is not enough. Thanks!
