### ISSUE TITLE
Experimental UI writes every character individually

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#1860]
Experimental UI writes every character individually. That results in a really bad experience under load, as you can see the output slowly build up character by character.

There are two reasons for this:
1. PositionAwareAnsiTerminalWriter splits up strings by char.
2. GrpcServerImpl.RpcOutputStream does not implement buffering (even though the old AfUnixSocket does).

There's even a todo in GrpcServerImpl to implement buffering.

**Comment by ulfjack** [comment]
I think this should block the release, because it results in a very bad user experience on Mac. I didn't try Linux or Windows.

**Comment by ulfjack** [comment]
I think this change should fix it:
https://github.com/ulfjack/bazel/tree/fix-single-byte-writes

**Comment by katre** [comment]
@ulfjack, Should this be cherrypicked into 0.3.2?

**Comment by ulfjack** [comment]
I think it should. Do you concur?

**Comment by ulfjack** [comment]
Lukacs has submitted one change, and another is still pending. My pull request needs to be abandoned.

**Comment by katre** [comment]
It does seem like a regression. I'll talk to Lukacs about what commits need to be cherrypicked.

**Comment by damienmg** [comment]
This is a regression on an experimental feature. The release is already
full of cherrypicks. That might be too much. We need to do a new release
candidate today so it still has 2 days to bake.

**Comment by katre** [comment]
Leaving this for the next release.
