### ISSUE TITLE
Extend "load" to allow loading bazel-agnostic files

### ISSUE THREAD

**Issue by eustas** [bazelbuild/bazel#18617]
### Description of the feature request:

Often, e.g. when project could be built with multiple build systems, it is necessary to read some variables (e.g. version) from a shared source.

Currently there is no way to populate file contents on load phase.

Solutions:
 - (easiest) allow loading skylark files without extension / with any extension; currently it is not possible to load file with name not ending with `.bzl`
 - (user-friendly) allow loading JSON/xml/properties/yaml files; one format would suffice; for all of those we should have the same import rules as with normal load - all imported names are directly listed in load function

I would work on this it if there is an agreement that we want to land this feature.

**Comment by pauldraper** [comment]
I feel like this has been requested before as well.

A workaround is a repository rule.

**workspace.bzl**

```bzl
_def _file_bzl_impl(ctx):
  content = ctx.read(ctx.attr.src)
  bzl = "CONTENT = %s" % json.encode(content)
  ctx.file("file.bzl", content = bzl, executable = False)

file_bzl = repository_rule(
  attrs = {
    "src": attr.label(mandatory = True),
  },
  implementation = _file_bzl_impl,
)
```

Example:

**BUILD.bazel**

```
load("@version//:file.bzl", VERSION = "CONTENT")

genrule(
  name = "version",
  cmd = "echo %s > $@" % VERSION,
  outputs = ["version2.txt"],
```

**WORKSPACE.bazel**

```bzl
load(":workspace.bzl", "file_bzl")

file_bzl(name = "version", src = "version.txt")
```

```sh
bazel build version
```

Or something like that

**Comment by brandjon** [comment]
It sounds like this is a request to have Bazel parse a myriad of other formats and deliver them to .bzl files via `load()` in a standard way.

Rather than commit to an API defining how we interpret those files, I'd strongly prefer that we instead require either a preprocessing step that converts them into .bzl, or a repo rule as @pauldraper suggested.

Note that .bzl files can express JSON-like content, just using Python-style syntax.

**Comment by eustas** [comment]
Thanks @pauldraper. Workaround looks good for me. But that means that Bazel workflow documentation is somewhat incomplete and should mention that workspace has its own parse-analyse-execute flow running before the the main BUILD parse-analyse-execute.

**Comment by pauldraper** [comment]
>  should mention that workspace has its own parse-analyse-execute flow running before the the main BUILD parse-analyse-execute

Look at ["repository rule"](https://bazel.build/extending/repo). Repository rules can interact with the environment in arbitrary ways, e.g. reading and writing files.

**Comment by pauldraper** [comment]
> Rather than commit to an API defining how we interpret those files, I'd strongly prefer that we instead require either a preprocessing step that converts them into .bzl, or a repo rule as @pauldraper suggested.

The problem with my workaround is that it's hella cumbersome.

I would suggest a very practical API to just read file content.

```
load_text(":version.txt", "VERSION", encoding = "utf-8")
```

Starlark already has `json.decode`, so JSON would already be supported by this.
