### ISSUE TITLE
When cc_binary is used for compilation, defines args does not take effect.

### ISSUE THREAD

**Issue by Distancess** [bazelbuild/bazel#18619]
### Description of the bug:

I use cc_binary to compile the published so (called A), which depends on the macro definition in another dynamic library (called B). I declare the macro in the defines parameter in the cc_binary of B. However, when compiling A, a message is displayed indicating that the macro cannot be found.

It seems that the defines macro in cc_binary of A can solve this problem. However, I understand that A depends on B. Bazel should build B first and then A. Therefore, this error should not be reported when A is being built.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

b.h
```c
#include <stdio.h>

#if (MARCO_DEFINE)
#define marco 23333
#endif
```
b.c
```c
#include "b.h"

void test(void);
```
a.c
```
#include "b.h"

void a_test(void)
{
    int b = marco;
    printf("%d", b);
}
```

BUILD.bazel
```
cc_import(
    name = "B_so",
    hdrs = ["b.h"],
    shared_library = ":B",
    visibility = ["//visibility:public"],
)
cc_binary(
    name = "B",
    srcs = ["b.h", "b.c"],
    defines = ["MARCO_DEFINE"],
    linkshared = 1
)

cc_binary(
    name = "A",
    srcs = ["a.c"],
    deps = [":B_so"],
    #defines = ["MARCO_DEFINE"],    
    #copts = ["-DMARCO_DEFINE"],
    linkshared = 1
)
```

### Which operating system are you running Bazel on?

Centos

### What is the output of `bazel info release`?

6.1.0

### Any other information, logs, or outputs that you want to share?

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
a.c: In function 'a_test':
a.c:5:13: error: 'marco' undeclared (first use in this function)
     int b = marco;
             ^~~~~
a.c:5:13: note: each undeclared identifier is reported only once for each function it appears in
Target //:A failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.874s, Critical Path: 0.21s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully

**Comment by fmeum** [comment]
`cc_import` is meant to import existing libraries, potentially built outside Bazel, into the build. It operates purely on the level of files and thus `B_so` neither sees nor forwards the `defines` on `B`. If you want to add such metadata, you can add a `cc_library` that depends on `B_so`.
