### ISSUE TITLE
Logo on homepage isn't showing up

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1862]
https://www.bazel.io/images/bazel-logo.png is giving permission denied!

**Comment by kchodorow** [comment]
```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous users does not have storage.objects.get access to object www.bazel.io/images/bazel-logo.png.
</Details>
</Error>
```

**Comment by damienmg** [comment]
For future reference, the fix is the following command line: `gsutil -m acl ch -R -u AllUsers:R gs://www.bazel.io`

**Comment by damienmg** [comment]
Ok this is now fixed, now looking at CI if I can figure out what when wrong

**Comment by damienmg** [comment]
Nothing. we have this line in the ACL update: `No changes to gs://www.bazel.io/images/bazel-logo.png`. I'll try to follow up with the GCS people.

**Comment by damienmg** [comment]
For future reference also the ci log: http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel-Publish-Site/221/console

**Comment by damienmg** [comment]
`gsutil defacl ch -u AllUsers:R gs://www.bazel.io` is setting the correct permission to the bucket so we should see it as intended :)
