### ISSUE TITLE
CLI flag to suppress INFO logging when building/running.

### ISSUE THREAD

**Issue by no-more-secrets** [bazelbuild/bazel#18636]
### Description of the feature request:

Currently `blaze build` (and friends) emit various INFO logging statements, e.g.:
```
INFO: Analyzed 3 targets (0 packages loaded, 0 targets configured).
INFO: Found 3 targets...
INFO: Elapsed time: 0.052s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```
Can we add a flag to suppress those?  I only want to see warnings and errors; if there are none, then I don't want any output at all preferably.

**Comment by keith** [comment]
https://bazel.build/reference/command-line-reference#flag--ui_event_filters
