### ISSUE TITLE
[Mirror] Gazelle v0.31.1

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel#18651]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.31.1/bazel-gazelle-v0.31.1.tar.gz

**Comment by sgowroji** [comment]
Please find the mirror artifact
1. https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.31.1/bazel-gazelle-v0.31.1.tar.gz
