### ISSUE TITLE
compiling tensorflow with bazel (master branch and 0.3.1)

### ISSUE THREAD

**Issue by shayanshams66** [bazelbuild/bazel#1867]
Hi 
I am trying to compile tensorflow when I am trying the bazel master I cant even configure the tensorflow,
./configure
I am getting this error:
ERROR: /var/scratch/_bazel_sshams2/3c79efdd14a80593173e3040c9712e33/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/BUILD:3:1: no such target '//external:android/dx_jar_import': target 'android/dx_jar_import' not declared in package 'external' defined by /var/scratch/tensorflow/WORKSPACE and referenced by '@bazel_tools//src/tools/android/java/com/google/devtools/build/android/dexer:dexer'.
ERROR: /var/scratch/_bazel_sshams2/3c79efdd14a80593173e3040c9712e33/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/BUILD:3:1: no such target '//external:android/dx_jar_import': target 'android/dx_jar_import' not declared in package 'external' defined by /var/scratch/tensorflow/WORKSPACE and referenced by '@bazel_tools//src/tools/android/java/com/google/devtools/build/android/dexer:dexer'.
ERROR: Evaluation of query "deps((//tensorflow/... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.
Configuration finished

when I am trying bazel 0.3.1
I can configure the tensorflow (master branch) but when I am trying to run 
$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
it picks up the wrong version of python although I have python compiled localy and point to the right python when configuring the tensorflow it uses global python on the cluster which is 2.6.6 and gives me this error:

 Linking of rule '@protobuf//:internal/_api_implementation.so' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -shared -o bazel-out/local_linux-opt/bin/external/protobuf/internal/_api_implementation.so -Wl,-whole-archive ... (remaining 10 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Traceback (most recent call last):
  File "external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc", line 41, in <module>
    from argparse import ArgumentParser
ImportError: No module named argparse
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.

environment:
tensorflow (master)
cuda 7.5
cudnn 4
python 2.7.12
GCC 4.9.4
jdk 1.8

thanks a lot in advance

**Comment by damienmg** [comment]
Hello, sorry for the delay, I have been crawling under the problems.

This seems like a breakage we rolled-back for the first issue.
The other error is definitely a tensorflow issue not ours. It seems to not find some python imports and it means that you are missing them on your OS.

Please refer to the TensorFlow issue tracker for more help.
