### ISSUE TITLE
[6.3.0] Teach ijar about dynamic constants.

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#18674]
Forked from #18406

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/18680

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/18711

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/18729

**Comment by fmeum** [comment]
@benjaminp I don't know for sure that it's needed, but just want to point out that this *may* require a java_tools release to become effective.

**Comment by iancha1992** [comment]
https://github.com/bazelbuild/bazel/pull/18729 is now merged. This is now closed.
