### ISSUE TITLE
Possibility to load generated Starlark files

### ISSUE THREAD

**Issue by mtribiere** [bazelbuild/bazel#18671]
### Description of the feature request:

In the embedded world we use a lot of code generators, and having the positibitly to load a generated `.bzl` file would be very useful. 
Example: 
`BUILD`: 
```
Code_Generation(                            <----- Let's imagine this target create a sources.bzl file
    name = "gen_srcs",
    Project_main_file = "MyCodeGenProject/main.qcg"
)

load(":gen_srcs","sourceList")     <------- Loading a list of file from the generated sources.bzl file

cc_library(
    name = "Generated_lib",
    scrs = sourceList
)
```
---
`sources.bzl`:
```
sourceList = [
 "gendir/srcA.c",
"gendir/srcB.c",
"gendir/srcC.c",
]
```

### What underlying problem are you trying to solve with this feature?

Code generation is rather hard with Bazel and requires a lot trickery at the moment 

### Which operating system are you running Bazel on?

Windows

### What is the output of `bazel info release`?

release 6.2.0

**Comment by brandjon** [comment]
This goes against some core design and implementation constraints about how .bzl files are handled. For instance, there's the possibility of cycles where the rule generating the .bzl lives in a BUILD file that loads the .bzl. And what if we want to just do a `bazel query` or a `bazel build --nobuild` on a package that loads such a file? Without running the execution phase we can't do it. I think this request amounts to condensing the loading, analysis, and execution phases into one big build step.

The alternative I'd suggest is running the code generators outside the bazel invocation (perhaps as another bazel invocation).

**Comment by mtribiere** [comment]
@brandjon Alright thanks, could you just elaborate a little on the alternatives?
The code generator we are using produces a certain number of sources files that we cannot know in advance. However it generates a text file that tell the build system what files it generated. Those files needs to be compiled in a library. 
How would go about this challenge?

**Comment by brandjon** [comment]
@comius Do you have any comments about this use case?

Off the top of my head: To me it sounds like the way you structured it, with the code generator producing a list of label strings in a .bzl file, is workable. The only difference is that instead of producing that .bzl as part of the build, you'd run it as a separate step before the build. Either you'd check in the generated file, or else you'd check in a stub file with an empty list and let the generation step overwrite the source file (but ignore that change in source control).

**Comment by tjgq** [comment]
Assuming the given example does not oversimplify what you want to achieve, I think it would suffice to generate your C++ source files as a tree artifact (`ctx.actions.declare_directory()`) whose contents are only determined at execution time. The limitation is that a single build action must be responsible for generating all of them.

**Comment by mtribiere** [comment]
@tjgq Thanks for your answers. I did not oversimplify what I want to achieve, and indeed it's possible to generate all the code with just one `ctx.action.run`. Below is the current is the current implementation of the rule that I tried. How would you modify it to get all the source files generated ?
```
def _my_Generation_impl(ctx):

    out = ctx.actions.declare_file("sources.bzl")

    args = ctx.actions.args()
    args.add(ctx.attr.Generator_Script)
    args.add(ctx.attr.QCG_main_file)
    args.add(out.dirname)
    args.add("--debug")   

    ctx.actions.run(
        executable = "python",
        outputs = [out],
        inputs = [ctx.files.Generator_Script],
        arguments = [args],
        mnemonic = "MyGen",
        env = myEnv
    )

    return [
            DefaultInfo(files = depset([out]))
        ]
```

**Comment by tjgq** [comment]
Modify your `ctx.actions.run` to produce a `ctx.actions.declare_directory` output and your `Generator_Script` binary to create the C++ files inside it. Then, put your rule (`my_Generation`) in the `srcs` of your `cc_library`.

**Comment by mtribiere** [comment]
Alright and just like that the rules should find all the sources in the directory ? If so thanks for your help

**Comment by tjgq** [comment]
Yes, there is special support for this in `cc_library` (it wouldn't work with `java_library`, for example; that's why I asked whether your problem was more general).

**Comment by tjgq** [comment]
Does your custom rule support a `declare_directory` in its `srcs`? If not, it shouldn't be too difficult to add support (assuming that you can modify the implementation easily).

**Comment by mtribiere** [comment]
It supports `filegroup`, not sure about `declare_directory`. I'm going to try

**Comment by mtribiere** [comment]
Okay there's a problem. The thing is, I can use the `declare_directory` like that:  
```
load("@build_tools_reloaded//toolchain/project:rules.bzl","my_Generation")

my_Generation(
    name = "my_gen_srcs",
    QCG_main_file = "TREATMENT.WRH/main.qcg"
)

load("@build_tools_reloaded//toolchain/project:rules.bzl","static_library")

static_library(
    name = "GEN_LIB",
    srcs= [":my_Generation"]
)
```

As I said, the generator creates a text file listing all generated source files. Therefore we have to compile **only** the sources listed in this text file. However in my understanding, using the `declare_directory` will result in a "glob-like" behavior (taking all the *.c files in the folder)

**Comment by tjgq** [comment]
This is fully under the control of the `static_library` implementation; if you wanted it to only consume a subset of the files in the `declare_directory`, you could still generate the list and have the `static_library` action use it to determine which files to read.

But I agree that the problem seems to be more complex than I initially assumed, so I'm no longer sure that this solution is preferable to what @brandjon was suggesting above.

**Comment by mtribiere** [comment]
Right, just to be sure, let's imagine we can have the list of files generated in any format (.bzl, BUILD,.txt,..).
Is there any ways I can read this generated file list ?
