### ISSUE TITLE
[6.3.0] Fix OOM in `describeNestedSetFingerprint`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#18676]
Forked from #18668

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/18678

**Comment by iancha1992** [comment]
> Cherry-picked in #18678

Need another commit before we can push this change. The PR is currently closed. Will create a new one when the necessary PR is pushed.

**Comment by keertk** [comment]
Requires https://github.com/bazelbuild/bazel/pull/18384, which won't be cherry-picked
