### ISSUE TITLE
[Mirror] Bellsoft JDK20.0.1 Windows aarch64 binary

### ISSUE THREAD

**Issue by zhengwei143** [bazelbuild/bazel#18689]
### Please list the URLs of the archives you'd like to mirror:

https://download.bell-sw.com/java/20.0.1+10/bellsoft-jdk20.0.1+10-windows-aarch64.zip

**Comment by Pavank1992** [comment]
Please find the mirror artifact:
https://mirror.bazel.build/download.bell-sw.com/java/20.0.1+10/bellsoft-jdk20.0.1+10-windows-aarch64.zip
