### ISSUE TITLE
cquery --output=files doesn't take --symlink_prefix into account

### ISSUE THREAD

**Issue by joca-bt** [bazelbuild/bazel#18690]
### Description of the bug:

I am trying to cquery the output files for my target

```
> bazel cquery --output=files ...:image
bazel-out/k8-fastbuild/bin/.../image/tarball.tar
```

but the output doesn't take my `--symlink_prefix` configuration into account (on my `.bazelrc` -> `build --symlink_prefix=.bazel/`).

The actual path is

```
.bazel/out/k8-fastbuild/bin/.../image/tarball.tar
```

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 6.2.1

**Comment by fmeum** [comment]
This is working as intended: The paths emitted with `--output=files` are relative to the execroot, not necessarily the project directory (for example, source files in external repositories aren't reachable via convenience symlinks). 

Please see https://bazel.build/query/cquery#files-output for the docs on this, including how to get the absolute path of the execroot.
