### ISSUE TITLE
cc_library alwayslink doesn't work when enable thinlto

### ISSUE THREAD

**Issue by lifengxiang1025** [bazelbuild/bazel#18704]
### Description of the bug:

for example:
`cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        ":lib",
    ],
)
cc_library(
    name = "lib",
    srcs = ["lib.cc","bar.cc"],
    alwayslink  = True,
)`
lib.cc has symbol 'foo'. main.cc doesn't use 'foo'. when use 'bazel build :main', main has 'foo'. when use 'bazel build :main --features=thin_lto', main doesn't have 'foo'.

### What is the output of `bazel info release`?

6.1.0

**Comment by lifengxiang1025** [comment]
> Hi @lifengxiang1025, Could you please help us to reproduce the issue with minimal steps and sample code?

https://github.com/lifengxiang1025/demo/tree/bazel.thinlto
when I build by 'bazel-dev build :main':
`nm bazel-out/k8-fastbuild/bin/main | grep foo
0000000000201720 T _Z3fooi`
when I build by 'bazel-dev build :main --features=thin_lto':
main doesn't have foo.

**Comment by lifengxiang1025** [comment]
complier version: `clang version 14.0.6 (https://github.com/llvm/llvm-project.git f28c006a5895fc0e329fe15fead81e37457cb1d1)`

**Comment by oquenchil** [comment]
[@teresajohnson](https://github.com/teresajohnson) can perhaps take a look.
