### ISSUE TITLE
Surprising behavior for attr.label_list accepting a dictionary

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#18702]
### Description of the bug:

I have a label_list attribute. It accepts a `dict`. I expected Bazel to error out during attribute typechecking.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
04:47:42 ~/code/repro/dict-as-label-list
$ cat BUILD
load(":myrule.bzl", "myrule")

filegroup(
    name = "fg",
    srcs = ["a.txt"],
)


myrule(
    name = "list",
    deps = [":fg"]
)


myrule(
    name = "dict",
    deps = { ":fg": True },
)

04:47:44 ~/code/repro/dict-as-label-list
$ cat myrule.bzl
def _myrule_impl(ctx):
    print(ctx.attr.name, ctx.attr.deps)
    pass

myrule = rule(
    implementation = _myrule_impl,
    attrs = {
        "deps": attr.label_list(),
    }
)
04:47:46 ~/code/repro/dict-as-label-list
$ bazelisk build :all
Starting local Bazel server and connecting to it...
DEBUG: /usr/local/google/home/jingwen/code/repro/dict-as-label-list/myrule.bzl:2:10: list [<target //:fg>]
DEBUG: /usr/local/google/home/jingwen/code/repro/dict-as-label-list/myrule.bzl:2:10: dict [<target //:fg>]
INFO: Analyzed 3 targets (4 packages loaded, 9 targets configured).
INFO: Found 3 targets...
INFO: Elapsed time: 3.139s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

I expected that `dict` to fail attribute typecheck.

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

release 6.2.1

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
n/a
```

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

unsure.

**Comment by jin** [comment]
cc @colecf

**Comment by brandjon** [comment]
This is an old Python gotcha, that dict iteration gives you back the keys, not the items. In this case it looks like label_list is accepting any iterable, not just lists (or lists + tuples).

We could restrict the allowed types down to lists [+ tuples?] as an incompatible change, to improve BUILD clarity.

**Comment by brandjon** [comment]
I'm not endorsing an API change just yet, but if wanted to proceed, [here's](https://github.com/bazelbuild/bazel/blob/9320a217779208aece2c8995ceb13d18be66f728/src/main/java/com/google/devtools/build/lib/packages/Type.java#L674-L680) the relevant code. Not sure how best to make it flag-guarded. Note that this affects all list-typed attributes.

Surprisingly, we accept depsets in these attributes as well. That must be a holdover from when depsets used to be implicitly iterable.
