### ISSUE TITLE
Can bazel build both go and c++in a single project, because I need go to call c++code for developmen

### ISSUE THREAD

**Issue by clearlove520** [bazelbuild/bazel#18706]
### Description of the feature request:

Can bazel build both go and c++in a single project, because I need go to call c++code for developmen

**Comment by iancha1992** [comment]
@clearlove520 bazel supports multiple languages for build including go and c++. We'll need more infos like what version of bazel you're using, logs/outputs (if any), what operating system you're running the Bazel on, and how you're building it.

**Comment by clearlove520** [comment]
Hello, currently the bazel version for calling C++is 5.4.1, and the operating system version is 20.04.1-Ubuntu. My idea is to add my go code to the C++library to call functions in C++(using cgo), and then bazel builds, compiles, and runs them. I would like to ask if this idea is feasible. If possible, I will provide you with a log output later. I know Bazel supports compiling in multiple languages, but I'm not sure if it's possible to mix and build two languages in the same project.
