### ISSUE TITLE
Issues with modulemaps and mixed types of headers

### ISSUE THREAD

**Issue by mikelikespie** [bazelbuild/bazel#1870]
Hi,

I'm attempting to convert some mixed objective-c/c++/swift projects to use bazel.

I've had some pretty good progress so far (see https://github.com/bazelbuild/bazel/pull/1784) but i am running into some issues.

I basically need a way to indicate to bazel that a header is C++ or should be explicitly imported (the latter would be a nice to have).

So here's the issue... say I have foo.h and foo_cxx.h (the latter with c++)... if the modulemap contains both of them and I import that module from an objective-c or swift file, it will try to parse everything as C/ObjC, not ObjC++. The right thing to do here is have 

```
requires cplusplus11
```

in the submodule for `foo_cxx.h`

One option I considered was adding a secondary `hdrs` attribute to the `objc_library` rule such as `cc_hdrs`, however not sure if this would scale... Another option would just be manually providing a modulemap.

Thanks!
Mike

**Comment by dmishe** [comment]
Mike, you could try moving C++ headers  into textual_hdrs as those are not exported to the module map currently (it should change to export with "textual" modifier in the future).

**Comment by jmmv** [comment]
Closing as a stale user support question that seems to have been answered.
