### ISSUE TITLE
Prebuilt osx dylib libraries not found during runtime

### ISSUE THREAD

**Issue by pjreiniger** [bazelbuild/bazel#18717]
### Description of the bug:

I'm trying to bazel-ify a project that uses prebuilt shared libraries for osx, windows, and linux. The osx versions have trouble finding the precompiled `*.dylib` file in several cases. It seems like the single library the is built with cmake works fine, but all of the other libraries that have a more bespoke build system cannot be found. Looking at the linker params it is appropriately adding the libraries in a similar way that it does for windows and linux, but at runtime when running a `bazel test`, `bazel run` or `./baze-bin/...` the shared object resolution is not happy. It seems like at some point the `rpath` / `loader_path` gets messed up.

I have tried pulling the libraries in with `cc_import` and `cc_library`, both download from an `http_archive` as well as living in the source tree, and they all exhibit the same problems. I've tried this against several bazel versions; `5.0.0`, `6.2.1`, `7.0.0-pre.20230530.3`

I do not personally have a mac to test on, so I've just been using [github actions](https://github.com/pjreiniger/BazelDylibExample/actions/runs/5301539517). 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/pjreiniger/BazelDylibExample

`bazel test //...`

This contains two attempts at pulling in the dll's, as well as the working (built with cmake) opencv example. I only put it linux and mac, but I know from my bigger repo that it works fine on windows as well, along with custom cross compilation toolchains.

### Which operating system are you running Bazel on?

Mac (`macos-latest` github actions runner)

### What is the output of `bazel info release`?

6.2.1

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
git@github.com:pjreiniger/BazelDylibExample.git
6eec6ecaa6671d48ce5b6da8cc3daee936035da2
6eec6ecaa6671d48ce5b6da8cc3daee936035da2
```

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/4794

**Comment by pcjanzen** [comment]
Try
```
install_name_tool -id @rpath/libwpiutil.dylib libwpiutil.dylib
```
in order to cause this library to be searched for on the rpath. (Or use the -install_name linker argument when creating the dylib in the first place.)

**Comment by oquenchil** [comment]
Please reopen if pcjanzen's recommendation didn't work.
