### ISSUE TITLE
Providers according to cquery inconsistent with providers according to aspect

### ISSUE THREAD

**Issue by nnmm** [bazelbuild/bazel#18721]
### Description of the bug:

`CcInfo` is listed as a provider of a `cc_binary`  in `bazel cquery <target> --output starlark --starlark:expr='providers(target).keys()'`, but `required_providers = [CcInfo]`  prevents an aspect from running on a `cc_binary`, at least when requested from a rule instead of the command line.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

**BUILD**

```python
load(":rule.bzl", "aspect_consumer")

cc_binary(
	name = "simple_binary",
	srcs = ["simple_main.cpp"]
)

aspect_consumer(
	name = "simple_binary_consumer",
	bin = ":simple_binary"
)
```

**rule.bzl**
```python
load(":aspect.bzl", "my_aspect", "MyInfo")

def _aspect_consumer_impl(ctx):
    print("MyInfo in bin: {}".format(MyInfo in ctx.attr.bin))
    return []

aspect_consumer = rule(
    implementation = _aspect_consumer_impl,
    attrs = {
        'bin' : attr.label(aspects = [my_aspect]),
    },
)
```

**aspect.bzl**
```python
MyInfo = provider()

def _my_aspect_impl(target, ctx):
    if ctx.rule.kind == "cc_binary":
        fail(target.label)
    return [MyInfo()]

my_aspect = aspect(
    implementation = _my_aspect_impl,
    attr_aspects = ["*"],
    required_providers = [CcInfo]
)
```

**simple_main.cpp**
```cpp
int main() {
}
```

Running `bazel build //:simple_binary_consumer`  gives
```
DEBUG: /home/user/example/rule.bzl:4:10: MyInfo in bin: False
INFO: Build completed successfully, 1 total action
```
so obviously the `cc_binary` was never visited by the aspect.

If you comment out the `required_providers = [CcInfo]`, the `cc_binary` _is_ visited:
```
ERROR: /home/user/example/BUILD:7:10: in //:aspect.bzl%my_aspect aspect on cc_binary rule //:simple_binary:
Traceback (most recent call last):
        File "/home/user/example/aspect.bzl", line 7, column 13, in _my_aspect_impl
                fail(target.label)
Error in fail: @//:simple_binary
ERROR: Analysis of target '//:simple_binary' failed
```

So the aspect behaves as if a `cc_binary` did not have `CcInfo`. This is inconsistent with the fact that `bazel build --aspects aspect.bzl%my_aspect //:simple_binary` does apply the aspect to the binary, and the fact that `bazel cquery --output starlark --starlark:expr='providers(target).keys()' //:simple_binary` lists `CcInfo` as well.

### Which operating system are you running Bazel on?

Ubuntu 20.04

### What is the output of `bazel info release`?

release 7.0.0-pre.20230420.2 (but it happens on 6.2.1 too)

**Comment by oquenchil** [comment]
The fact that `cc_binary` provides `CcInfo` is a legacy misfeature and it should be removed. Without knowing more details I don't know if until that happens the provider should be advertised with  `provides` or not.

I'd say that your aspect can safely skip the `cc_binary` targets since the `CcInfo` won't have any linking information and the information for compilation is very limited. If you are properly using the attribute `cc_library.hdrs` in your build to specify public headers and have the `layering_check` enabled, `cc_binary` doesn't really fit in that picture because it won't give you any public headers since it doesn't even have the `hdrs` attribute.

**Comment by pcjanzen** [comment]
My use case is slightly different: I want to write an aspect that peers into every C/C++ compilation action, regardless of whether it is generated by `cc_library`, `cc_binary`, or `cc_test`. Currently, I cannot use `required_providers` to filter-out every non-cc target, because `cc_binary` and `cc_test` do not advertise the CcInfo provider with `provides`.

**Comment by oquenchil** [comment]
For that you are going to have to propagate to every rule and check the target's actions for the `CppCompile` mnemonic. `required_providers` is not a guarantee that you caught every `CppCompile` action in the build. `cc_test` should definitely not advertise `CcInfo` and for the `cc_binary` case as I said earlier it's questionable whether it should be advertised until the code is cleaned up and the provider removed.

**Comment by oquenchil** [comment]
I will close now since it's pretty clear we won't be advertising `CcInfo` from `cc_binary` for now for this use case. Please feel free to continue the discussion though.

**Comment by nnmm** [comment]
@oquenchil This issue's original subject, that there are two subsystems with different views on whether `CcInfo` is in `cc_binary`, is still relevant I'd say. If it is a legacy misfeature to have `CcInfo` in `cc_binary`, that's fine with me, but then it should imo be removed from `cquery` too.

**Comment by fmeum** [comment]
@nnmm Ignoring the specifics of `cc_binary`, there is a general conceptual difference between a rule promising that it will always return a provider (what aspects care about) and a rule sometimes (depending on it's implementation logic) deciding to return a provider (which will be reported by `cquery` if present). Both are valuable concepts and I don't think that Bazel can get rid of one of them.

**Comment by nnmm** [comment]
@fmeum You're right, I knew that but I thought that an aspect propagates based on the actually returned providers, but in fact it propagates based on advertised providers. Then there is no discrepancy there.
