### ISSUE TITLE
it seems incompatible_avoid_conflict_dlls changed behaviour in bazel 6.x

### ISSUE THREAD

**Issue by tmasciar** [bazelbuild/bazel#18730]
### Description of the bug:

Hi

I have cc_library under windows generating name.dll when I run 
bazel build name --output_groups=dynamic library
from bazel version 4.0 to bazel 5.4 

my cc_library have the features=["windows_export_all_symbols"], set.

for the same cc_library setting, when using bazel 6.x
bazel build name --output_groups=dynamic library
return the library as name_{sha}.dll

bazel build name --output_groups=dynamic library --incompatible_avoid_conflict_dlls=false
return the library as name_{sha}.dll

bazel build name --output_groups=dynamic library --noincompatible_avoid_conflict_dlls
return the library as name_{sha}.dll

when I use the flag under bazel 5.4
bazel build name --output_groups=dynamic library --incompatible_avoid_conflict_dlls
return the library as name_{sha}.dll
when I use the flag under bazel 5.4
bazel build name --output_groups=dynamic library --noincompatible_avoid_conflict_dlls
or
bazel build name --output_groups=dynamic library --incompatible_avoid_conflict_dlls=false
return the library as name.dll

so, using incompatible_avoid_conflict_dlls has a consistent behavior when used under bazel 5.4
whatever the value of the flag set under bazel 6, I have the same behaviour => return the library as name_{sha}.dll

is the new behavior under bazel 6 expected?

Thanks

### Which operating system are you running Bazel on?

windows 10

### What is the output of `bazel info release`?

C:\usrs\thierryinteg\bb_test\bubazel info release Starting local Bazel server and connecting to it... release 5.4.0

### Have you found anything relevant by searching the web?

tried to ask question to google group but it does not pass the check of the moderator

**Comment by Pavank1992** [comment]
Hi @tmasciar, please refer https://github.com/bazelbuild/bazel/issues/11600 for rename DLL to avoids conflict on Windows. Let us know if you have other queries.

**Comment by tmasciar** [comment]
so, what you are saying is that the flag is had coded to true and cannot be changed now?
My understanding is that the https://github.com/bazelbuild/bazel/issues/11600 was set for bazel 4. and it was still possible to undo it.

**Comment by meteorcloudy** [comment]
@oquenchil @buildbreaker2021 It seems we cannot turn off the dll suffix anymore, maybe related to the starlarkification of cc rules?

@tmasciar On the other hand, this incompatible flag has been flipped a long time ago, theoretically we can just remove the flag and always adopt the new behaviour. So you should not depend on the old behaviour anyway.

**Comment by oquenchil** [comment]
I don't have the bandwidth to look into this now but incompatible_* flags are not a feature to control behavior that should be relied on long term. By definition they are a workaround to make migration possible for one release (or a few more).
