### ISSUE TITLE
clang module cache not being reused in darwin sandbox

### ISSUE THREAD

**Issue by mikelikespie** [bazelbuild/bazel#1873]
I noticed compiling to be significantly slower on versions of macOS where sandboxing is enabled (seems to not be enabled on macOS yet). The behavior described in `getCompileRuleCopts()` comments don't seem to be behaving.

If I understand how the sandboxing works, it sym/hardlinks all the input files to a temp directory. If the directory specified for the module cache is in the genfiles dir, it seems like each file it compiles will get an empty directory as input. This causes it to reparse imported modules each time.

**Comment by damienmg** [comment]
/cc @philwo for the general sandboxing things
/cc @hermione521 for the OS X sandbox but I think it is not specific to OSX
and pulling @klimek and @lberki for explaining how C++ clang module works

**Comment by r4nt** [comment]
Generally, the clang module cache feature is at odds with sandboxing (it creates a shared global module cache in /tmp, so it assume non-hermetic compilation), so the slow down is fully expected; you're essentially doing quadratic work here (recompile all transitive modules on every compile step).
You can imagine the clang module cache as it's own little C++ build system.

For C++ modules builds, we are using explicit module builds, and we are modeling the module outputs (pcm files) within bazel. For Obj-C this has (as far as I undersatnd) yet to be done; I guess the main work will be to actually figure out how to pass framework modules to the build correctly when implicit module builds are disabled.

**Comment by damienmg** [comment]
Ok so reassigning to Objc for Objc / C++ interop /cc @calpeyser

**Comment by jmmv** [comment]
Will make a dup of #7527 which has more information.
