### ISSUE TITLE
[Mirror] 

### ISSUE THREAD

**Issue by JamyDev** [bazelbuild/bazel#18744]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/rules_go/releases/download/v0.40.0/rules_go-v0.40.0.zip
https://github.com/golang/sys/archive/refs/tags/v0.8.0.zip
https://github.com/googleapis/go-genproto/archive/e85fd2cbaebc35e54b279b5e9b1057db87dacd57.zip
https://github.com/googleapis/googleapis/archive/77c99e43177c76ae1c1edacee7b6ac4e35a42f3d.zip

**Comment by sgowroji** [comment]
Attached mirror artifacts are:
======================
1. https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.40.0/rules_go-v0.40.0.zip
2. https://mirror.bazel.build/github.com/golang/sys/archive/refs/tags/v0.8.0.zip
3. https://mirror.bazel.build/github.com/googleapis/go-genproto/archive/e85fd2cbaebc35e54b279b5e9b1057db87dacd57.zip
4. https://mirror.bazel.build/github.com/googleapis/googleapis/archive/77c99e43177c76ae1c1edacee7b6ac4e35a42f3d.zip
