### ISSUE TITLE
.bazelrc not enforcing std

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#1874]
I have a `<WORKSPACE>/.bazelrc` with 

    build --cxxopt=-std=c++14

and in 0.3.1+ it does not apply the std argument.
Source code is compiled with `-std=c++0x`.

**Comment by abergmeier-dsfishlabs** [comment]
Should block #1840 IMO

**Comment by abergmeier-dsfishlabs** [comment]
This is not specific to 0.3.2. Still strange because this was working in 0.3.1!?

**Comment by abergmeier-dsfishlabs** [comment]
Setting `cfg` to host caused this. Superseded by https://github.com/bazelbuild/bazel/issues/1876

**Comment by breakds** [comment]
I am hitting this as well. Is there a work around already?
