### ISSUE TITLE
[6.3.0] Builtins exports.bzl file is called after the WORKSPACE

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#18767]
Forked from #17713

**Comment by meteorcloudy** [comment]
We'll need https://github.com/bazelbuild/bazel/commit/b1341bedcf55be1f5b46e0bb98ad3ed064bede70 and https://github.com/bazelbuild/bazel/commit/c2553cc6ccece9826895bd691c4981d1e790e9e6

**Comment by iancha1992** [comment]
@meteorcloudy As per the comment https://github.com/bazelbuild/bazel/issues/17713#issuecomment-1612631564, only https://github.com/bazelbuild/bazel/commit/b1341bedcf55be1f5b46e0bb98ad3ed064bede70 was cherry-picked in https://github.com/bazelbuild/bazel/pull/18819

**Comment by meteorcloudy** [comment]
Ack, thanks!

**Comment by iancha1992** [comment]
@meteorcloudy should I keep this open on the 6.3.0 milestone? since we only cherry-picked one of them?
