### ISSUE TITLE
Add a way to make arbitrary files available to C++ compilation targets

### ISSUE THREAD

**Issue by filmil** [bazelbuild/bazel#18766]
### Description of the feature request:

See discussion at https://groups.google.com/g/bazel-discuss/c/XE57LP4keoc

There currently seems to be no way to include an arbitrary file in a `cc_library` or a `cc_binary` or similar rule to be available at compilation time.

Sometimes it is necessary, such as when you want to have your options captured in a file, or if you want to use `.incbin` in assembly compilation.

**Comment by brentleyjones** [comment]
@oquenchil can we cherry-pick this into 6.3.0?

**Comment by oquenchil** [comment]
Yes, you can send a PR for 6.3.
