### ISSUE TITLE
Missing host_cxxopt

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#1876]
There currently is not way of setting `cxxopt` for host compilation. There should probably be a `host_cxxopt` but it is missing.

**Comment by abergmeier-dsfishlabs** [comment]
Is there any reason not to add `host_cxxopt`?

**Comment by abergmeier-dsfishlabs** [comment]
No objections? Here we go: #2543

**Comment by mhlopko** [comment]
I assume this can be closed now :) Thank you for the patch!
