### ISSUE TITLE
Remote exec connection should be established later

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/bazel#18760]
### Description of the feature request:

Right now, the RemoteModule tries to establish the connection to the remote execution service in `beforeCommand`. This is problematic:

1. If there are problems contacting the build farm and long retries are configured, a Bazel invocation will stall at startup, *before any message is printed*. This can be really confusing to users.
2. If a command does not really need to use the build farm, Bazel still tries to validate the credentials, which blocks execution of that command.
3. Error messages are poor due to the lack of context.

It seems to me that `beforeCommand` should be doing configuration validation only, and that the actual connection to the build farm should only be established in `executorInit`. The fact that everything currently happens in `beforeCommand` does not seem intentional to me, but just a consequence that it was "easier to do that way".

I have a pretty trivial change that does this and can send it as a PR, so let me know if it's something you'd consider reviewing/incorporating. cc @coeuvre

### What underlying problem are you trying to solve with this feature?

Not block commands (due to delays or failures) that don't need the build farm, and be able to provide more context-specific error messages for them.

E.g. change from this:

```
WARNING: Failed to query remote execution capabilities: null
INFO: Invocation ID: a1f225f9-9d84-4330-8b89-a37362cf4977
INFO: Analyzed target //foo:bar (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //foo:bar up-to-date:
  bazel-bin/foo/bar
INFO: Elapsed time: 0.386s, Critical Path: 0.04s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

To this:

```
INFO: Invocation ID: a1f225f9-9d84-4330-8b89-a37362cf4977
INFO: Analyzed target //foo:bar (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
WARNING: Failed to query remote execution capabilities: null
Target //foo:bar up-to-date:
  bazel-bin/foo/bar
INFO: Elapsed time: 0.386s, Critical Path: 0.04s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

### Which operating system are you running Bazel on?

N/A

### What is the output of `bazel info release`?

release 6.2.0

### Have you found anything relevant by searching the web?

There is https://github.com/bazelbuild/bazel/issues/18607 as well, which talks about establishing the connection in the background. That would be nice, but it's a separate issue to the one I'm describing.

**Comment by coeuvre** [comment]
Cool, please send us the PR!

**Comment by jmmv** [comment]
Alright, here it is: https://github.com/bazelbuild/bazel/pull/18794

**Comment by coeuvre** [comment]
Closing, in favor of https://github.com/bazelbuild/bazel/issues/18607.
