### ISSUE TITLE
Documentation for cfg missing

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#1877]
While there is this message

```
Argument `cfg = "host"` or `cfg = "data"` is required if `executable = True` is provided for a label.
```

in 0.3.2, the actual documentation about what `host` and `data` mean in detail is lacking.
Find it unpleasant to not be able to fix this due to lack of knowledge.

**Comment by laurentlb** [comment]
See https://bazel.build/versions/master/docs/skylark/rules.html#configurations

**Comment by abergmeier-dsfishlabs** [comment]
But what about things that need to be executed in both building and running (_host_ and _data_)? Can `cfg` be a list?

**Comment by fweikert** [comment]
Reopening for the discussion.

**Comment by dslomov** [comment]
This is a documentation issue. Let's close it and file a separate issue for functionality change
