### ISSUE TITLE
Update java_tools

### ISSUE THREAD

**Issue by cushon** [bazelbuild/bazel#18774]
There have been a couple of recent Java toolchain fixes that improve compatibility with JDK 21 that it would be nice to get into 6.3.0:

* https://github.com/bazelbuild/bazel/issues/18360
* https://github.com/bazelbuild/bazel/issues/18743

The first one has been merged into 6.3.0, the second one hasn't yet.

I think both changes will require a java_tools release to be visible, would it be possible to include both in 6.3.0 and then cut another java_tools release?

cc @kshyanashree @comius @hvadehra

**Comment by iancha1992** [comment]
@cushon hi, we can absolutely assist with cherry-picking the second one. But we'll need you to give us the commit ID or push to the master so that we can merge to the release-6.3.0 branch. We can communicate on the original issue: https://github.com/bazelbuild/bazel/issues/18743.

**Comment by cushon** [comment]
@iancha1992 to double-check, can you also do a `java_tools` release (similar to the example in #17427)?

Just cherry-picking the fixes into 6.3.0 isn't sufficient, the prebuilt tools also have to be updated and then then the `java_tools` release containing those fixes has to be cherry-picked

**Comment by iancha1992** [comment]
> @iancha1992 to double-check, can you also do a `java_tools` release (similar to the example in #17427)?
> 
> Just cherry-picking the fixes into 6.3.0 isn't sufficient, the prebuilt tools also have to be updated and then then the `java_tools` release containing those fixes has to be cherry-picked

Sure!

cc: @keertk, @sgowroji, @Pavank1992

**Comment by keertk** [comment]
@bazel-io fork 6.3.0

**Comment by keertk** [comment]
java_tools release: https://github.com/bazelbuild/java_tools/releases/tag/java_v12.4
rules_java release: https://github.com/bazelbuild/rules_java/releases/tag/6.2.1
PR to be merged: https://github.com/bazelbuild/bazel/pull/18810
cherry-pick into 6.3: https://github.com/bazelbuild/bazel/pull/18868
