### ISSUE TITLE
using python bin at custom location

### ISSUE THREAD

**Issue by cnsgsz** [bazelbuild/bazel#1878]
I want bazel to use /home/user_name/.conda/envs/py35/bin/python instead of the default /usr/bin/python. Do I have to disable sandboxing and put the former into PATH variable in some global config, or is there a better way? For example, it would be great if bazel can automatically get PATH from the shell it is running in, so that I don't have to duplicate the custom python location in both my bashrc and some bazel config.

**Comment by abergmeier-dsfishlabs** [comment]
Please search the issue tracker - there are other (similar?) issues for Python already.

**Comment by damienmg** [comment]
--action_env is working at HEAD.

/cc @aehlig to follow-up for user support.

**Comment by abergmeier-dsfishlabs** [comment]
@damienmg `HEAD` (to be known as _0.4_) or already _0.3.2_?

**Comment by damienmg** [comment]
0.3.2 includes it yes

**Comment by cnsgsz** [comment]
is there a way to add the python bin at custom location to the sandbox?

**Comment by cnsgsz** [comment]
> build --sandbox_add_path=/where/my/python/is

 seems to work.
