### ISSUE TITLE
Tutorial is broken on Darwin

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1879]
[Tutorial](http://ci.bazel.io/job/Tutorial/BAZEL_VERSION=latest,PLATFORM_NAME=darwin-x86_64/516/console) is broken on Darwin for both HEAD and latest, seems like it is a breakage we have for a [long time](http://ci.bazel.io/job/Tutorial/469/BAZEL_VERSION=latest,PLATFORM_NAME=darwin-x86_64/console) that was [hidden](http://ci.bazel.io/job/Tutorial/BAZEL_VERSION=latest,PLATFORM_NAME=darwin-x86_64/510/console)

The breakage is related to iOS, because it was already in the release it is definitely a release blocker, summoning @c-parsons to help me.

/cc @katre

**Comment by c-parsons** [comment]
We've run into this error in other places before -- the CoreSimulatorService gets into a bad state, which is a difficult and annoying problem for a CI machine.

Do we have a cleanup hook for this test suite?
I believe the general approach is to kill the CoreSimulatorService with `launchctl kill SIGKILL` of the appropriate service ID

E.g.
`launchctl kill SIGKILL user/12345/com.apple.CoreSimulator.CoreSimulatorService`

**Comment by damienmg** [comment]
Confirmed it is from the machine, still figuring out how to fix it.

**Comment by damienmg** [comment]
Rebooting the machines fixed it!
