### ISSUE TITLE
Document/update --check_licenses and its interaction with distribs() and licenses()

### ISSUE THREAD

**Issue by schroederc** [bazelbuild/bazel#188]
Source context: src/main/java/com/google/devtools/build/lib/packages/License.java

Since Bazel forces licenses to be set for //third_party/... targets, it would be very helpful to document what those declarations actual do and how --check_licenses works.

Likewise, I think that the current implementation is very Google-centric and could use some massaging to work better for the open-source community.  In particular, the distribs() doesn't make a lot of sense for completely open-source repositories.  It's often necessary to differentiate between executable and library distributions for some licenses, not just client vs web vs embedded.

Since the world of licenses is vast, it will also likely be necessary to provide some way to configure/extend this feature.  In my opinion, this feature could mostly boil down to a tagging mechanism that infects/affects all dependent targets coupled with asserts on which tags can/must exist for a particular target.

**Comment by gregestren** [comment]
There's been talk of overhauling this mechanism even within Google - I think this is due for a design refresh, and your points just add fuel to the argument. 

Depending on exactly what you want to do, you may also want to check out the (new and not yet documented) [constraints system](https://github.com/google/bazel/blob/master/src/main/java/com/google/devtools/build/lib/analysis/constraints/ConstraintSemantics.java#L45). The basic gist of it is that you can annotate any rule with tags of your choosing and enforce that if rule A supports "foo" and A depends on B, then B must also support "foo".

Feel free to ask for more details if you think that could help you.

**Comment by trainman419** [comment]
+1; this mechanism needs better documentation. This showed up again in #642 .

**Comment by michaelsafyan** [comment]
+1000. I think it is also reasonable in the opensource version to have --check_licenses default to false.

**Comment by aiuto** [comment]
I am in the process of looking at (and rebuilding) license checking for Google internally. I don't have a design ready for review but the important points are
- completely Starlark rule based and not built into the core code
- suggested taxonomy of license type labels (GPL, LGPL, Apache, MIT, ...). This is user extensible
- tooling to gather licenses used in a binary
- tooling to allow any organization to check license compatibility. 

The last point is a key one. Google has it's own view of what we can put in particular kinds of applications. Other organizations will rightly have other views. The implementation must allow someone to easily create their own check_licenses rule to reflect their needs.

In the short term, I don't want document what we do with license and distribs. I hope to have all that code removed and replaced with a new (and documented) implementation over the next quarter or two.

**Comment by aiuto** [comment]
Obsolete. --check_licenses is now a no-op in Bazel.
