### ISSUE TITLE
Not able to build from /tmp directory

### ISSUE THREAD

**Issue by zvh** [bazelbuild/bazel#1882]
This seems weird but I cannot build the attached workspace when it resides in /tmp, but I can build it when it resides in /usr/local.

The error I get when the workspace is in /tmp is:

test_workspace> bazel build :test
.
INFO: Found 1 target...
ERROR: /tmp/test_workspace/foo/BUILD:3:1: Extracting interface //foo:foo failed: linux-sandbox failed: error executing command /usr/local/google/home/zachh/.cache/bazel/_bazel_zachh/93ab1ca01a05c23ede3cf25cda21f0ce/execroot/test_workspace/_bin/linux-sandbox ... (remaining 5 argument(s) skipped).
open(): No such file or directory
Unable to open Zip file foo/foo.jar: No such file or directory
Target //:test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 5.594s, Critical Path: 0.21s
[test_workspace.zip](https://github.com/bazelbuild/bazel/files/509617/test_workspace.zip)

Is there some reason why I can't build from /tmp?

**Comment by ahumesky** [comment]
I believe this was fixed with https://github.com/bazelbuild/bazel/commit/52f4e8bbaf18ea489acd2db464f267757e8eb6d4
Can you check with a bazel on or after that commit?

**Comment by zvh** [comment]
Thanks, I pulled the latest bazel code and that seems to fix the problem

**Comment by philwo** [comment]
Yes, this was fixed in https://github.com/bazelbuild/bazel/commit/52f4e8bbaf18ea489acd2db464f267757e8eb6d4 :)
