### ISSUE TITLE
specifying the C++ standard via `--features`

### ISSUE THREAD

**Issue by junyer** [bazelbuild/bazel#18824]
### Description of the feature request:

Permit specifying the C++ standard via `--features` such that, for example, `--features=cxx_std_14` specifies C++14 as the C++ standard in the appropriate way for the compiler that gets selected during automatic configuration of the C++ toolchain.

### What underlying problem are you trying to solve with this feature?

Currently, specifying the C++ standard is problematic for multiple reasons. First and foremost, it requires specifying the C++ standard in a **_compiler-specific_** way (e.g. `-std=c++14` or `/std:c++14`). Second, it's unclear when the `--cxxopt` flag works and doesn't work, when the `BAZEL_CXXOPTS` environment variable works and doesn't work et cetera. Third, there's mounting evidence (documented by @Mizux) that **_none_** of the ways work consistently and effectively when using Abseil and Protobuf.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 6.2.1

**Comment by keith** [comment]
dup of https://github.com/bazelbuild/bazel/issues/16551
