### ISSUE TITLE
Allow `deps` attribute in `java_library` even without `srcs` attribute?

### ISSUE THREAD

**Issue by math4tots** [bazelbuild/bazel#1883]
Just a question, when I try to build a `java_library` with `deps` attribute but without a `srcs` attribute, I get:

`ERROR: /Users/kyuminkim/GitHub/source/protos/BUILD:5:10: in deps attribute of java_library rule //protos:protos: deps not allowed without srcs; move to runtime_deps?
`

Why is this the case? What should I do if I want to bundle a collection of `java_library` rules into one I can use as a dependency in a `java_binary` rule? Moving them to `runtime_deps` won't work because I want them available at compile time.

Thank you,

**Comment by ahumesky** [comment]
For this you'll want to use java_library.exports:
https://www.bazel.io/versions/master/docs/be/java.html#java_library.exports

**Comment by math4tots** [comment]
Exactly what was looking for, thank you!
