### ISSUE TITLE
Bazel build google mediapipe

### ISSUE THREAD

**Issue by schnitzlein** [bazelbuild/bazel#18842]
### Page link:

https://github.com/google/mediapipe/blob/master/docs/getting_started/python.md

### Problem description (include actual vs expected text, if applicable):

Under the Hood / behind the scence in Point 6. is bazel called.
And I add an issue at mediapipe, but still there is no big response.

Bazel try always to build for iOS, but it claims with mediapipe to be able to run under POSIX / Linux.
But it will not compile for Raspbian 11 (bullseye) with the 64 Bit on Architecture aarch64 with a ARM Cortex-A72.

I dont understand the complex build chain at all, try to understand it and go over with platform( ... and so on.
I manipulated in setup.py the platform checks to reconnaize the aarch64 or arm without iOS.

But still no sucess in building a simple Linux package with bazel, finally to retrieve my python package to work with.

I follow in the rabbit hole to understand what is going on.

But bazel seems to ignore my BUILD setup:

Here is no Linux, so I experiment and have no success: https://github.com/google/mediapipe/blob/master/mediapipe/BUILD

Here I added: 
https://github.com/google/mediapipe/blob/master/BUILD.bazel
```

platform(
    name = "linux_arm64",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:aarch64",
        ":glibc_10_2",
    ],
)

# FAIL
#platform(
#    name = "linux",
#    constraint_values = [
#        "@local_config_platform//:host"
#    ],
#)

platform(
    name = "myplatform",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:arm",
    ],
)


```
all of it is failing.

Dear bazel community please help me. ;)  

### Where do you see this issue? (include link to specific section of the page, if applicable)

https://github.com/google/mediapipe/blob/master/docs/getting_started/python.md

it is not ready to use

### Any other information you'd like to share?

https://github.com/google/mediapipe/issues/4591

I try to make it alive on raspibian 11 in 64 Bit or 32 Bit ... but no success only bazel errors

**Comment by sgowroji** [comment]
Hi @schnitzlein, Can you provide complete steps to reproduce the issue. Looking at description it looks like more a mediapipe support issue, not the bazel bug. Thanks!
