### ISSUE TITLE
Does Bazel support remote compilation and local linking

### ISSUE THREAD

**Issue by GITWHB** [bazelbuild/bazel#18856]
Does Bazel support remote compilation and local linking？

**Comment by GITWHB** [comment]
Recently, it has been found that remote links take a long time (30 minutes) and there may be instances of timeout and reconnection, but local links are fast (200 seconds)

**Comment by Pavank1992** [comment]
Yes, Bazel does support remote compilation and local linking. 
[Remote Execution documentation](https://docs.bazel.build/versions/main/remote-execution.html) explains how Bazel uses remote execution to distribute and parallelize builds.

Could you please share your use case with detailed explanation (with logs if possible) so we have dive deep into the issue?

**Comment by GITWHB** [comment]
> Yes, Bazel does support remote compilation and local linking. [Remote Execution documentation](https://docs.bazel.build/versions/main/remote-execution.html) explains how Bazel uses remote execution to distribute and parallelize builds.
> 
> Could you please share your use case with detailed explanation (with logs if possible) so we have dive deep into the issue?

log:

**Comment by GITWHB** [comment]
> Yes, Bazel does support remote compilation and local linking. [Remote Execution documentation](https://docs.bazel.build/versions/main/remote-execution.html) explains how Bazel uses remote execution to distribute and parallelize builds.
> 
> Could you please share your use case with detailed explanation (with logs if possible) so we have dive deep into the issue?
Log:
[6,874 / 6,875] Linking server; 29s remote
[6,874 / 6,875] Linking server; 80s remote
[6,874 / 6,875] Linking server; 128s remote
[6,874 / 6,875] Linking server; 209s remote
[6,874 / 6,875] Linking server; 305s remote
[6,874 / 6,875] Linking server; 386s remote
[6,874 / 6,875] Linking server; 509s remote
[6,874 / 6,875] Linking server; 629s remote
[6,874 / 6,875] Linking server; 809s remote
[6,874 / 6,875] Linking server; 972s remote
[6,874 / 6,875] Linking server; 1154s remote
[6,874 / 6,875] Linking server; 1409s remote
[6,874 / 6,875] Linking server; 186s remote
[6,874 / 6,875] Linking server; 486s remote
[6,874 / 6,875] Linking server; 846s remote
Target //:server up-to-date:
bazel-bin/server

INFO: Elapsed time: 2898.445s, Critical Path: 2817.89s

**Comment by GITWHB** [comment]
How can Bazel perform remote compilation and local linking? What compilation options or parameters do you need to add?
Currently, our compilation and linking processes are remote

Thank you.

**Comment by Pavank1992** [comment]
To configure Bazel to use remote execution, you need to set the --remote_executor flag with the appropriate value. [flag--remote_executor](https://bazel.build/reference/command-line-reference#flag--remote_executor) may help you.

Thanks for the log, Could you please share minimal steps with sample code to reproduce the issue. Also please help us to understand with bazel version, OS you are using.
