### ISSUE TITLE
bazel_toolchain_test is failing on darwin

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1885]
ERROR: /Users/ci/workspace/bazel-tests/BAZEL_VERSION/HEAD/PLATFORM_NAME/darwin-x86_64/src/test/shell/bazel/BUILD:162:12: in srcs attribute of sh_test rule //src/test/shell/bazel:bazel_toolchain_test: you must specify exactly one file in 'srcs'.
WARNING: errors encountered while analyzing target '//src/test/shell/bazel:bazel_toolchain_test': it will not be built.

http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/261/console

Not release blocker because the problem is on the test.

**Comment by damienmg** [comment]
what is this [select](https://github.com/bazelbuild/bazel/blob/master/src/test/shell/bazel/BUILD#L163)?

**Comment by meteorcloudy** [comment]
Looks like it's defined [here](https://github.com/bazelbuild/bazel/blame/master/src/test/shell/bazel/BUILD#L21)

**Comment by meteorcloudy** [comment]
This was meant to exclude this test on Darwin, but seems it's not the right way.
