### ISSUE TITLE
collect_cc_coverage.sh incorrectly assumes llvm-cov generates gcov.json files

### ISSUE THREAD

**Issue by carlosgalvezp** [bazelbuild/bazel#18874]
### Description of the bug:

Hi,

We are trying to migrate from our working GCC gcov solution for coverage in Bazel, to Clang-based coverage. Note: I do not mean ["source-based code coverage"](https://clang.llvm.org/docs/SourceBasedCodeCoverage.html) (which I believe only has experimental support in Bazel). I mean using the `--coverage` flag when building with Clang, which should produce identical results as GCC. In other words, using clang as a drop-in replacement for GCC.

Currently computing coverage fails because Bazel expects `*.gcov.json` files and it cannot find them:

```
mv: cannot stat '*.gcov.json.gz': No such file or directory
```

This comes from this line:
https://github.com/bazelbuild/bazel/blob/master/tools/test/collect_cc_coverage.sh#L163

So even though GCC 9+ does generate .gcov.json files, Clang 9+ does not do so. 

I am using the following relevant flags and settings:

```
coverage --instrument_test_targets
coverage --combined_report=lcov
```

```
        tool_path(
            name = "gcov",
            path = "wrapper/llvm-cov",
        ),
```

### Which operating system are you running Bazel on?

Ubuntu 20.04

### What is the output of `bazel info release`?

release 6.1.0

**Comment by carlosgalvezp** [comment]
It seems the generated files are "foo.pic.gcda.gcov".

I was thinking to go for LLVM source-based coverage but this comment here made me think it's unsupported for producing an lcov-compatible output. I see that the mentioned ticket is closed, is that comment still valid?

https://github.com/bazelbuild/bazel/blob/master/tools/test/collect_cc_coverage.sh#L178

```
  # If llvm code coverage is used, we output the raw code coverage report in
  # the $COVERAGE_OUTPUT_FILE. This report will not be converted to any other
  # format by LcovMerger.
  # TODO(#5881): Convert profdata reports to lcov.
```

**Comment by c-mita** [comment]
It's possible support for converting to LCOV is missing (although it should be implementable).

At the very least; I've opened https://github.com/bazelbuild/bazel/pull/18878 - can you check if that fixes the issue?

**Comment by carlosgalvezp** [comment]
Looks much more robust, thank you! I believe our infrastructure is setup to only be able to try out pre-built Bazel versions so I might need to wait until it's merged, but it sounds like it should work just fine :)
