### ISSUE TITLE
Understand and clean compiler flags in Windows CROSSTOOL

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#1887]
https://github.com/bazelbuild/bazel/blob/master/tools/cpp/CROSSTOOL#L617

When I was building TensorFlow on Windows, these legacy compiler flags are starting causing unexpected behaviors on Windows. So we need to know what they mean and clean the unnecessary ones.

**Comment by dslomov** [comment]
Anything more to do here @meteorcloudy ?

**Comment by meteorcloudy** [comment]
We did some work about this in https://github.com/bazelbuild/bazel/commit/193c9f88ed6df6e4444a6184c988ae8ae90a5f50 and https://github.com/bazelbuild/bazel/commit/87250d979d3622bc3fdb6095799a668841a2b152.

I think we can close it now, if users complain about other flags in CROSSTOOL, we'll then fix more.
