### ISSUE TITLE
Bazel coverage is not producing coverage reports for 6.1.2

### ISSUE THREAD

**Issue by darrenrabbs** [bazelbuild/bazel#18896]
### Description of the bug:

I am having issues running bazel coverage with  the 6.1.2 version of Bazel
This was working fine on 5.4.1 but for some reason now , the _coverage_report.dat files are appearing empty.

Is there anything broken with coverage between the two versions and has anyone discovered any workarounds to resolve?

Thanks

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I can see if the steps are reproducible with a simple repo 

### Which operating system are you running Bazel on?

ubuntu

### What is the output of `bazel info release`?

release 6.1.2

**Comment by sgowroji** [comment]
Hi @darrenrabbs, Can you provide complete steps to reproduce the above scenario. Thanks!

**Comment by darrenrabbs** [comment]
Hi guys, 
I am currently testing to see with Bazel 6.2.0 resolves my issues. If it does then I will happy to close the bug, will keep you posted and if I am still seeing issues , I'll give some more steps on how to reproduce.. ( however, it is a private repo but I will attempt on another sample repo if the issue persists)

**Comment by coeuvre** [comment]
Bazel 6.2 doesn't have the fix so it's likely you will still have the issue with it. Can you try with a custom binary with https://github.com/bazelbuild/bazel/pull/18791 patched, or wait for 6.3.0 RCs?

**Comment by sgowroji** [comment]
Hi @darrenrabbs, Can you please verify the above with latest [6.3.0](https://github.com/bazelbuild/bazel/releases/tag/6.3.0). release. Let us know if you still have any queries. Thanks!

**Comment by darrenrabbs** [comment]
Hi, we haven't upgraded to this version as of yet . However, coverage is working for us on 6.2.1 version so we are content for now. Happy to close this also
