### ISSUE TITLE
[6.3.0] More descriptive error messages for unexpected absolute includes

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#18893]
Cherry-pick https://github.com/bazelbuild/bazel/commit/f0361b4788ea690237c4d162c596b350b6da1518 into 6.3.0

fyi @iancha1992, thanks!

**Comment by iancha1992** [comment]
They cherry-pick has been called off as per the comment, https://github.com/bazelbuild/bazel/commit/f0361b4788ea690237c4d162c596b350b6da1518#r121320151

cc: @bazelbuild/triage
