### ISSUE TITLE
//src/test/shell/integration:stub_finds_runfiles_test is timing out on Darwin

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1889]
Seems like a genuine failure. The test takes only 50s on Linux.

See http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/265/console

**Comment by damienmg** [comment]
Maybe a consequence of the header compilation?

**Comment by damienmg** [comment]
On my machine they only takes 50s, machine's fatigue?

**Comment by damienmg** [comment]
Pulling in @meisterT because too much breakage and he opened sourced that test.

Tobias, feel free to find a better owner

**Comment by hermione521** [comment]
No more timeout! Yay!
