### ISSUE TITLE
[Mirror] rules_go 0.41.0 and Gazelle 0.32.0

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel#18900]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.32.0/bazel-gazelle-v0.32.0.tar.gz
https://github.com/bazelbuild/rules_go/releases/download/v0.41.0/rules_go-v0.41.0.zip

**Comment by Pavank1992** [comment]
Please find the mirror artifacts below:
https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.32.0/bazel-gazelle-v0.32.0.tar.gz
https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.41.0/rules_go-v0.41.0.zip
