### ISSUE TITLE
Coverage file is occasionally missing causing crash

### ISSUE THREAD

**Issue by iangudger** [bazelbuild/bazel#18915]
### Description of the bug:

We are running Bazel with the following command:
`bazel coverage --combined_report=lcov --test_output=errors --instrumentation_filter="^//" --build_tests_only --@io_bazel_rules_go//go/config:race //...`

Some percentage of the time, all tests pass, but the run fails with an error like this:

```
INFO: From Testing //path/to/package:package_test:
==================== Test output for //path/to/package:package_test:
PASS
coverage: 81.8% of statements
GCov does not exist at the given path: ''
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0x00007fbe7b6dea39, pid=12, tid=35
#
# JRE version:  (11.0.15+10) (build )
# Java VM: OpenJDK 64-Bit Server VM (11.0.15+10-LTS, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xc21a39]  PerfMemory::alloc(unsigned long)+0x59
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/runner/.cache/bazel/_bazel_runner/da152f49cc027ba7c8b301103a0d71b8/sandbox/linux-sandbox/3364/execroot/repo/core.12)
#
# An error report file with more information is saved as:
# /home/runner/.cache/bazel/_bazel_runner/da152f49cc027ba7c8b301103a0d71b8/sandbox/linux-sandbox/3364/execroot/repo/hs_err_pid12.log
#
#
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run `bazel coverage` on `go_test` targets from `rules_go`. The issue is intermittent.

### Which operating system are you running Bazel on?

Ubuntu 22.04 on GitHub Actions

### What is the output of `bazel info release`?

6.2.1

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
Private repo. I can't share this information.
```

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

This has been happening for a very long time. Versions old enough to not contain this bug won't run our code.

**Comment by meisterT** [comment]
cc @c-mita

**Comment by jfirebaugh** [comment]
We (Figma) experience this issue even on Bazel 7.4.0, where `--incompatible_sandbox_hermetic_tmp` is the default.

**Comment by jfirebaugh** [comment]
I am willing to try to debug further. Does anyone know where the mmapping is happening that is triggering this SIGBUS? I assume it is in [coverageoutputgenerator](https://github.com/bazelbuild/bazel/tree/master/tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator) somewhere but I can't find it.

**Comment by fmeum** [comment]
It's probably a JVM crash, I don't think the output generator uses `mmap`. Could you share the crash logs?

**Comment by jfirebaugh** [comment]
It's exactly the same SIGBUS output as in the OP.

**Comment by jfirebaugh** [comment]
Is it possible that the Java binary being executed here is not run in the sandbox, and thus not getting the effects of `--incompatible_sandbox_hermetic_tmp`, and hitting the hsperfdata conflict described in https://github.com/bazelbuild/bazel/issues/3236?

**Comment by jfirebaugh** [comment]
Ah, false alarm. Turns out we have `build --sandbox_add_mount_pair=/tmp` in .bazelrc, undoing the `--incompatible_sandbox_hermetic_tmp` default.

**Comment by fmeum** [comment]
Now that this also turned out to be an instance of #3236, let's close this issue as a dupe.
