### ISSUE TITLE
Some Hacker put this on my devices and I want it removed 

### ISSUE THREAD

**Issue by morgiemoemoney13** [bazelbuild/bazel#18917]
### Description of the bug:

Whatever this is, I didn’t download it and I want it off all my devices 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Trying to delete chromium from my iPhone and this was one of the steps 

### Which operating system are you running Bazel on?

iOS 

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

I didn’t but I pray to God that I find them

**Comment by Wyverald** [comment]
I highly doubt anyone could have managed to install Bazel on your iOS device.

**Comment by morgiemoemoney13** [comment]
Well, I didn’t put it on there and had no clue of its existence until I found a chromium bug page I was unaware of as well

**Comment by morgiemoemoney13** [comment]
I think it’s funny that the date I said a hacker put this on my phone it all of a sudden showed up on my page. I’ll add Github to my lawsuit because I’m about to expose everyone
