### ISSUE TITLE
'abs' function is not defined

### ISSUE THREAD

**Issue by mzapotoczny** [bazelbuild/bazel#18927]
### Description of the bug:

According to documentation https://bazel.build/rules/lib/globals/all#all user should have access to `abs()` function in all starlark files. Unfortunately, this function is not defined.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```bash
mkdir test
cd test
touch WORKSPACE
echo "print(abs(-1))" > BUILD
bazel build ...
```

Result:
```
(...)
ERROR: (...)/test/BUILD:1:7: name 'abs' is not defined
(...)
```

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 6.2.1

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

n/a

**Comment by c-mita** [comment]
This function was added recently: https://github.com/bazelbuild/bazel/commit/5e37989.
It doesn't exist, and isn't documented for, 6.2.

**Comment by mzapotoczny** [comment]
Oh, thanks. I didn't see that by default `bazel.build` shows documentation for nightly build (IMHO this is a little bit unintuitive). Nevertheless, this task can be closed. Thanks!
