### ISSUE TITLE
[bazel.build] Problem with /contribute/maintainers-guide

### ISSUE THREAD

**Issue by mzapotoczny** [bazelbuild/bazel#18926]
### Page link:

https://bazel.build/contribute/maintainers-guide

### Problem description (include actual vs expected text, if applicable):

When I click on "Issue Template" link I get "404 - page not found". 

### Where do you see this issue? (include link to specific section of the page, if applicable)

https://bazel.build/contribute/maintainers-guide#lifecycle-issue

Broken links are visible in section "Lifecycle of an Issue", point 1, and 2c.

**Comment by Snapstromegon** [comment]
I think this issue can be resolved fairly easily by linking to https://github.com/bazelbuild/bazel/issues/new/choose instead.

IMO the wording on the page could even stay the same.
