### ISSUE TITLE
MODULE.bazel.lock file contains user specific paths

### ISSUE THREAD

**Issue by jsharpe** [bazelbuild/bazel#18936]
### Description of the bug:

The lock file includes user specific paths in the location part of the extension usage sections.
This is a side effect of the change made to improve error messages by @fmeum.

### What is the output of `bazel info release`?

6.3.0rc1

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Yes this is a regression due to https://github.com/bazelbuild/bazel/pull/18612

**Comment by fmeum** [comment]
@Wyverald @SalmaSamy The absolute paths come from `Location`'s `file` field. Do you think we need to keep `Location` information in the JSON? If it is only used in error messages and the lockfile has been generated, maybe we can just drop that information?

If we want to preserve it, we would probably need to make the path relative to its root. But this doesn't look that easy since the root can vary (workspace root, external repo root, ...).

**Comment by SalmaSamy** [comment]
In some cases  the `location` is required in the error messages after reading the data from the lockfile. I am not sure if it's okay to drop it. @Wyverald what do you think?

**Comment by Wyverald** [comment]
@bazel-io fork 6.3.0

**Comment by fmeum** [comment]
> I was thinking that we should maybe just store a label-y thing for locations in MODULE.bazel files of modules with non-registry overrides. So `@@foo~override//:MODULE.bazel` instead of `$OUTPUT_BASE/external/foo~override/MODULE.bazel`. 

Sounds good! If we use `Label#getDisplayForm`, that label will be reasonably friendly in the likely case where a module with a non-registry override is a direct dependency of the root module.

> Then we could augment the `bazel mod show_repo` command a bit to show where the repo is actually located, and maybe also think about some sort of helper command that just straight up converts a label to a local file path. WDYT?

`bazel cquery --output=files` comes somewhat close, but doesn't quite get there: It only outputs paths relative to the output base and can't directly refer to `MODULE.bazel` unless its an exported file. So yes, something like this would be needed, but not urgently.

**Comment by fmeum** [comment]
Having thought about this some more, I like canonical labels more than the display form as they are closer to the actual location on disk.

We should probably also handle the root module specially as it is the one where errors are most likely to originate from. I am working on a PR for this aspect [here](https://github.com/bazelbuild/bazel/pull/18949).

**Comment by Wyverald** [comment]
I have a change in flight to fix non-registry overrides.
