### ISSUE TITLE
Bzlmod: offline mode

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#18934]
Offline mode: fetch all external repos needed for a certain build, so that the user could turn off internet and still successfully build.

New features to be added to the "fetch" command:
--all: fetch all external dependencies
--configure: only fetch the repos marked as configure
--repo={repo}: fetch this specific repo
--force: can be used with any of the previous options to force fetch the repos even if it was already downloaded

Note: these options **_only_** works with --bzlmod_enabled

Detailed designs to be worked on and published;

**Comment by goldencz** [comment]
Looking forward to read the design, it's important to enterprise scenes.

**Comment by SalmaSamy** [comment]
We are discussing some ideas [here](https://github.com/bazelbuild/bazel/discussions/19004)

**Comment by iancha1992** [comment]
@bazel-io fork 7.0.0

**Comment by SalmaSamy** [comment]
Done and will be included in our upcoming release, version 7.0.0

**Comment by SalmaSamy** [comment]
Done and will be included in our upcoming release, version 7.0.0
