### ISSUE TITLE
Bazel can't handle the Android values folders for some locales

### ISSUE THREAD

**Issue by mihnita** [bazelbuild/bazel#1895]
Bazel fails for locales with 3 characters in the language id (values-chr is valid)
And fails for locales that contain script ("the b+ syntax", which makes values-b+sr+Latn and values-b+zh+Hant valid)

Bazel also hard-codes a special case for es-419 (Spanish Latin America), but in general any 3 digit code is valid region.
Should support at least the ones listed under the IANA Language Subtag Registry
    http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
(search for Subtag: 0)

Android supports them for about two years (Android L)

**Comment by ahumesky** [comment]
For the b+ syntax, we've recently updated our resource processing libraries (today in fact), so this should work in the next few days (although I thought we already supported this independently of the resource processing library).

For the 3 character region, it's not clear from the documentation that this is supported:
https://developer.android.com/guide/topics/resources/providing-resources.html#AlternativeResources
`The language is defined by a two-letter ISO 639-1 language code, optionally followed by a two letter ISO 3166-1-alpha-2 region code (preceded by lowercase "r").`
Is the documentation out of date?

**Comment by mihnita** [comment]
Yes, the documentation is out of date.

A quick test: you can try values-chr, and the strings load fine (compiled with Android Studio)
(you would need Android N to be able to select Cherokee as a locale)

The change happened somewhere in Android L, but until N there was no way to select a 3 char locale.

The only locale that needed 3 char language ID would have been Filipino (fil).
But a "hackish" way was already in use ("tl", Tagalog, was used by Android when one selected the "Filipono" locale in UI)
The Android L fix also added a backward compat hack to consider fil == tl when loading resources.

I can find the code change that introduced 3 char support, if you want...
It is the same CL that added the b+ syntax.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
