### ISSUE TITLE
Clean up --strict_android_deps and --strict_java_deps

### ISSUE THREAD

**Issue by zvh** [bazelbuild/bazel#1896]
I tried disabling strict java deps but I still get a strict error:

> bazel build --strict_java_deps=off java/com/android/dialer/common/... 
INFO: Found 1 target...
ERROR: /tmp/tmpdXACj3/java/com/android/dialer/common/BUILD:7:1: Java compilation in rule '//java/com/android/dialer/common:common' failed: Worker process sent response with exit code: 1.
java/com/android/dialer/common/Assert.java:52: error: [strict] Using type android.support.annotation.NonNull from an indirect dependency (TOOL_INFO: "//libs:android-support-annotations"). See command below **
  @NonNull
   ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
** Please add the following dependencies:
  //libs:android-support-annotations  to //java/com/android/dialer/common

Target //java/com/android/dialer/common:common failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.322s, Critical Path: 0.13s

**Comment by cushon** [comment]
If that's an `android_library` you want `--strict_android_deps`.

The separate flags are a historical artifact, they should probably be combined.

**Comment by zvh** [comment]
Ah thanks, didn't know there was a separate flag and I confirmed the android one works properly.

**Comment by cushon** [comment]
I think it's worth keeping this open to clean up `--strict_android_deps` and `--strict_java_deps`.

They also aren't propagated into the host config, which has been confusing in the past.

**Comment by ittaiz** [comment]
@cushon any chance you'll be willing to consider cleaning it up to be `--strict_jvm_deps`? I'm currently piggybacking on the `--strict_java_deps` for scala compilation since skylark rules cant' have their own command line flags. Would be nice usability wise to be able to have a clearer name.
