### ISSUE TITLE
[6.3.0] Cherry-pick TF test fix into 6.3

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#18971]
https://github.com/bazelbuild/bazel/commit/ed4872a3fab99f9e51dcbf91418504795b533438

cc @iancha1992 @meteorcloudy

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/18973

**Comment by meteorcloudy** [comment]
https://github.com/bazelbuild/bazel/commit/ed4872a3fab99f9e51dcbf91418504795b533438 is getting rollbacked on the main branch, so we cannot cherry pick this for 6.3.0
