### ISSUE TITLE
Improve warning message on Windows with MSVC

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#1897]
It's kind of a mess right now. We are setting warning flags in [CROSSTOOL](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/CROSSTOOL.tpl#L165) while we are filtering warning messages in [msvc_tools.py](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/wrapper/bin/pydir/msvc_tools.py.tpl#L475)

When building TF on Windows, my screen is always flushed with warning messages.

**Comment by dslomov** [comment]
We no longer use python wrapper
