### ISSUE TITLE
cc_library should support copts and cxxopts both

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/bazel#18986]
### Description of the feature request:

some project contain both .c and .cc file， like jemalloc，.c need a set of compile flags, but .cc need another, can cc_library support cxxopts option?

**Comment by Pavank1992** [comment]
Hi @xiedeacc, Could you please elaborate the requested feature and its use case?

**Comment by thii** [comment]
If this is accepted, please consider adding `conlyopts` too.

**Comment by xiedeacc** [comment]
> Hi @xiedeacc, Could you please elaborate the requested feature and its use case?

what? I think request described clearly enough

**Comment by xiedeacc** [comment]
I cannot understand why need more data

**Comment by fmeum** [comment]
@xiedeacc This has been moved to the "untrusted" stage, which means that no more data is needed - instead, a team member will triage it at some point.

**Comment by snakethatlovesstaticlibs** [comment]
This is possibly a dupe of https://github.com/bazelbuild/bazel/issues/22041
