### ISSUE TITLE
While setting up Bazel from a docker terminal and running ./compile.sh results in error "No such package '@local_config_cc//'"

### ISSUE THREAD

**Issue by vasantivmahajan** [bazelbuild/bazel#1899]
I am running a docker terminal from a windows machine and I need to set up Bazel. I build Bazel from source by cloning the repository  git clone https://github.com/bazelbuild/bazel.git. While running the ./compile.sh command the following error is displayed.

![image](https://cloud.githubusercontent.com/assets/17990840/19197193/88d8e478-8c86-11e6-8502-ca46bd895960.png)

Any help is appreciated.

**Comment by damienmg** [comment]
One quick question: why is the docker part relevant? (the problem is just happening on Windows)

**Comment by vasantivmahajan** [comment]
@damienmg Just wanted to give all the information

**Comment by damienmg** [comment]
Oh ok :) @meteorcloudy should be able to help you further but I guess the issue is there is a space in the path to bash and setting `BAZEL_SH` to C:\Program~1\Git\usr\bin\bash.exe should be enough.

**Comment by vasantivmahajan** [comment]
@meteorcloudy

**Comment by meteorcloudy** [comment]
Did you set `BAZEL_SH`,  if so, can you show what's it like?

**Comment by meteorcloudy** [comment]
Where did you install msys? if it's `c:/tools/msys64`, try `export BAZEL_SH=c:/tools/msys64/usr/bin/bash.exe`

**Comment by meteorcloudy** [comment]
Also, looks like you are in MINGW64 console, it's better to switch to MSYS console. :)

**Comment by vasantivmahajan** [comment]
I have set the following paths:
BAZEL_SH=c:/msys64/usr/bin/bash.exe (as I have downloaded MSYS in C:/msys64)
JAVA_HOME="$(ls -d C:/Program\ Files/Java/jdk* | sort | tail -n 1)"
BAZEL_VS="C:/Program Files/Microsoft Visual Studio 12.0"
export BAZEL_PYTHON=C:/Python27/python.exe

After running the ./compile.sh command in the MSYS console, the following error is displayed:
![image](https://cloud.githubusercontent.com/assets/17990840/19275538/1a709bc4-8fa2-11e6-93aa-b47eaae062ea.png)

**Comment by meteorcloudy** [comment]
I believe `BAZEL_VS` should be `"C:/Program Files/Microsoft Visual Studio 14.0"`.
That's where the `VCVARSALL.BAT` script is, we need this to set up necessary environment for MSVC tools.

**Comment by meteorcloudy** [comment]
FYI, on my machine, Visual Studio is at `C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/VCVARSALL.BAT"`
If you are not sure, you don't have to set up BAZEL_VS, let bazel find it. :)

**Comment by vasantivmahajan** [comment]
@meteorcloudy : I changed the BAZEL_VS path to C:/Program Files/Microsoft Visual Studio 14.0.
However, the same error is displayed

![image](https://cloud.githubusercontent.com/assets/17990840/19276301/f075f114-8fa3-11e6-946c-b260c4642ef3.png)

**Comment by meteorcloudy** [comment]
So I guess it's `Program Files (x86)` instead of `Program Files`?
Please make sure `VCVARSALL.BAT` is under `${BAZEL_VS}/VC`

**Comment by vasantivmahajan** [comment]
On setting  the path as  export BAZEL_VS="C:/Program Files (x86)/Microsoft Visual Studio 14.0", the following error is displayed: 

![image](https://cloud.githubusercontent.com/assets/17990840/19276601/e3221a82-8fa4-11e6-8b5c-e7d8c64341f7.png)

**Comment by meteorcloudy** [comment]
Is the script under `C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/VCVARSALL.BAT`?
If not, you might didn't install Visual Studio with the Visual C++ components?

**Comment by vasantivmahajan** [comment]
@meteorcloudy: How do I check if the script is present in the path. I can see the following folders under "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"

![image](https://cloud.githubusercontent.com/assets/17990840/19277084/857f447a-8fa6-11e6-968d-49830297ffa7.png)

**Comment by meteorcloudy** [comment]
So, the script is missing, means you didn't install Visual Studio correctly, please make sure you have Visual C++ installed.
![image](https://cloud.githubusercontent.com/assets/4171702/19277215/4497d35e-8fd9-11e6-9263-c3edbfcb9a51.png)

**Comment by vasantivmahajan** [comment]
@meteorcloudy: I updated my Visual Studio and choose the above-mentioned features. The build was successful after that. Thank you very much for your help.
