### ISSUE TITLE
`--experimental_remote_cache_compression` causes 3-5x higher Bazel server heap usage

### ISSUE THREAD

**Issue by jfirebaugh** [bazelbuild/bazel#18997]
### Description of the bug:

Certain actions, possibly those that trigger a high number of remote cache CAS hits, lead to excessively high Bazel server memory use when using `--experimental_remote_cache_compression`. A build using `--experimental_remote_cache_compression` may result in 3-5x times higher JVM heap use compared to not using that flag.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I've minimized a repro here: https://github.com/jfirebaugh/bazel_remote_cache_compression

Checkout that repository, add .bazelrc with appropriate remote cache configuration, and then compare the output of:

1. `bazel clean && bazel shutdown && bazel build --memory_profile=memprof :binary && grep 'Build artifacts:heap:used' memprof`
2. `bazel clean && bazel shutdown && bazel build --experimental_remote_cache_compression --memory_profile=memprof :binary && grep 'Build artifacts:heap:used' memprof`

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 6.2.1

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
git@github.com:jfirebaugh/bazel_remote_cache_compression.git
master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fb76727c785f013541bb150120f2fecf14e79c58
```

### Have you found anything relevant by searching the web?

High memory use with `--experimental_remote_cache_compression` was reported by another user on Bazel slack: https://bazelbuild.slack.com/archives/CA31HN1T3/p1646921767090359?thread_ts=1646911448.469939&cid=CA31HN1T3

### Any other information, logs, or outputs that you want to share?

I have done some initial investigation using JFR memory profiling, and it looks like one possible cause is the following:

```
Stack Trace	Count	Percentage
void java.nio.HeapByteBuffer.<init>(int, int, MemorySegmentProxy)	504	34.4 %
   ByteBuffer java.nio.ByteBuffer.allocate(int)	504	34.4 %
   ByteBuffer com.github.luben.zstd.NoPool.get(int)	471	32.2 %
      void com.github.luben.zstd.ZstdInputStreamNoFinalizer.<init>(InputStream, BufferPool)	471	32.2 %
      void com.github.luben.zstd.ZstdInputStreamNoFinalizer.<init>(InputStream)	471	32.2 %
      void com.google.devtools.build.lib.remote.zstd.ZstdDecompressingOutputStream.<init>(OutputStream)	471	32.2 %
      ListenableFuture com.google.devtools.build.lib.remote.GrpcCacheClient.requestRead(RemoteActionExecutionContext, RemoteRetrier$ProgressiveBackoff, Digest, CountingOutputStream, Supplier, Channel)	471	32.2 %
```

[`requestRead` allocates `ZstdDecompressingOutputStream`](https://github.com/bazelbuild/bazel/blob/e81cdb9411fc45cab22d270ee374628fcaab82f8/src/main/java/com/google/devtools/build/lib/remote/GrpcCacheClient.java#L394), which allocates `ZstdInputStreamNoFinalizer`, which uses `NoPool` to allocate via `ByteBuffer.allocate`. It appears the size allocated here is:

https://github.com/luben/zstd-jni/blob/e07f8970be0c72ce02dcdf1877daa034208915d0/src/main/native/decompress/zstd_decompress.c#L1668

Which if I've calculated correctly is 131 kB. And I assume this will allocate once for every in-flight cache read.

**Comment by brentleyjones** [comment]
@coeuvre @tjgq

**Comment by coeuvre** [comment]
One thing we could do is to limit the number of inflight read requests. I don't have workload to work on it now. PR is welcome!

**Comment by sluongng** [comment]
I think the main problem here is that we were naively init `ZstdInputStreamNoFinalizer` so it would use `NoPool` underneath, which by default does not recycle the buffer pool (`release()` being a no-op).

The fix here is to use a buffer pool that would recycle the buffer for more efficient memory usage.

@jfirebaugh you could try changing the init of `ZstdInputStreamNoFinalizer` inside `ZstdDecompressingOutputStream` to make use of `RecyclingBufferPool.INSTANCE`.

```java
  public ZstdDecompressingOutputStream(OutputStream out) throws IOException {
    this.out = out;
    zis =
        new ZstdInputStreamNoFinalizer(
                new InputStream() {
                  @Override
                  public int read() {
                    return inner.read();
                  }

                  @Override
                  public int read(byte[] b, int off, int len) {
                    return inner.read(b, off, len);
                  }
                }, RecyclingBufferPool.INSTANCE)
            .setContinuous(true);
  }
```

This would probably require some careful benchmarking against your current setup to observe if the memory usage is any better.

**Comment by brentleyjones** [comment]
This bug is preventing some of our customers from using cache compression. Could this be bumped higher than a P3?

**Comment by jfirebaugh** [comment]
The patch suggested by @sluongng does not appear to help. I think because [`RecyclingBufferPool`](https://github.com/luben/zstd-jni/blob/e07f8970be0c72ce02dcdf1877daa034208915d0/src/main/java/com/github/luben/zstd/RecyclingBufferPool.java) does not impose any limit on the size of the pool. If concurrent use requires an additional buffer, the pool grows. So overall it does not meaningfully change the behavior when there are many concurrent decompression streams.

**Comment by meteorcloudy** [comment]
> This bug is preventing some of our customers from using cache compression. Could this be bumped higher than a P3?

@coeuvre @tjgq Do we have plan to rollout this experimental feature? If so, maybe P3 isn't appropriate?

**Comment by sluongng** [comment]
We discussed with @jfirebaugh a bit on this on the side. It seems like a contributing factor to this issue was remote actions with a large amount of small artifacts (<100B).

These artifacts don't compress well using vanilla ZSTD. In some cases, the ZSTD header of the file would be bigger than the file itself. So applying compression to these files would create a bigger file than the original and worsen the transfer speed.

A long-term fix for this could be https://github.com/bazelbuild/remote-apis/pull/276, in which, the client/server could agree on a Zstd dictionary to delta compressed against. This requires changes to the protocol, then adopted by clients (Bazel) and different server implementations.

A short-term solution could be as simple as adding a file size threshold limit to Bazel. Files under such a threshold will not be compressed when uploaded to the remote server.

**Comment by tjgq** [comment]
I concur that adding a minimum file size threshold for compression is the best short-term fix, but I don't have the time right now to run the experiments required to find an appropriate value.

If someone has already experimented or is willing to experiment and report here, I'm happy to do the rest of the work.

**Comment by sluongng** [comment]
I don't think there will be an appropriate value.

Here is a quick experiment

```
> echo -n '{}' > a

> zstd a
a                    :750.00%   (     2 B =>     15 B, a.zst)

> xxd a.zst
00000000: 28b5 2ffd 2402 1100 007b 7dd1 94f2 7a    (./.$....{}...z
```

So applying compression would inflate a 2-byte file by 750%, resulting in a 15-byte payload.

Reading through https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md, it seems like a zstd compressed file format would have a minimum cost of 4 bytes for the magic number, 2 bytes for the frame headers and 3 bytes for the block header. Realistically, it seems like the overhead is around 13 bytes minimum.

Beyond 13 bytes, it all depends on the data being compressed.

```
> echo -n 'bbbbbbbbbb' > a
> zstd a
a                    :230.00%   (    10 B =>     23 B, a.zst)

> echo -n 'bbbbbbbbbbaaaaaaaaaabbbbbbbbbb' > a
> zstd a
a                    : 83.33%   (    30 B =>     25 B, a.zst)
```

As an arbitrary value, I say we set the default value for skipping compression at "greater than, or equal to 100 Bytes". It should be a configurable flag so that folks can adjust it to their needs. It should also be "experimental" so that we could change it later if Zstd dictionary compression gets implemented in Bazel.

**Comment by sluongng** [comment]
In a "real world" build, I see that all compressed CAS entries up until 90B resulted in a size increase. Starting from 90B -> 105B, some entries show up as a size deflation. Beyond 105B the deflation is much more frequent.

I don't think that is representative of all builds out there, but I think it's a good case for us to pick a conservative starting point.

**Comment by jfirebaugh** [comment]
90-100 bytes is the break even point I see in our real-world builds as well.

**Comment by tjgq** [comment]
Let's start by adding a flag so that folks can experiment further. I'll prepare a PR.

**Comment by meteorcloudy** [comment]
@tjgq Should this one be backported to 7.1.0?

**Comment by sluongng** [comment]
I think the threshold being zero(0) by default makes it easier to backport. It makes the new behavior opt-in instead of opt-out.

**Comment by tjgq** [comment]
@bazel-io fork 7.1.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.1.0 RC1](https://releases.bazel.build/7.1.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!

**Comment by jfirebaugh** [comment]
I tried to test this in 7.1.0rc1 but hit https://github.com/bazelbuild/bazel/issues/21478 which prevents further progress.

**Comment by jfirebaugh** [comment]
I was able to test this on rc1/rc2 and confirm it works. I was able to re-enable `--experimental_remote_cache_compression` on some jobs that would OOM before.

**Comment by coeuvre** [comment]
We would like to change the default value of `--experimental_remote_cache_compression_threshold` in Bazel 8 (currently, it's `0`).

With your experiments, do you still think `100` is a good default value?

**Comment by brentleyjones** [comment]
cc: @fmeum @sluongng

**Comment by sluongng** [comment]
@brentleyjones thanks for the ping

@coeuvre we started recommending this flag with `100` value recently to all of our users. Here is the PR with some basic testing. https://github.com/buildbuddy-io/buildbuddy/pull/7009#discussion_r1676117359

**Comment by coeuvre** [comment]
@sluongng Thanks for the pointer! Please let me know if later you find out `100` should be adjusted.
