### ISSUE TITLE
bazel build C++ file failed in win10 version 21H2

### ISSUE THREAD

**Issue by blueskyscorpio** [bazelbuild/bazel#19014]
### Description of the bug:

It is failed when I build C++ file in win 10 version21H2. Below is information, how to solve it?

C:\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\\Python38\\python.exe" mediapipe/examples/desktop/hello_world
ERROR: C:/users/shaohg/_bazel_shaohg/3vmcl3ou/external/build_bazel_apple_support/crosstool/setup.bzl:69:32: name 'module_extension' is not defined
ERROR: error loading package '': in C:/users/shaohg/_bazel_shaohg/3vmcl3ou/external/build_bazel_rules_swift/swift/extras.bzl: in C:/users/shaohg/_bazel_shaohg/3vmcl3ou/external/build_bazel_apple_support/lib/repositories.bzl: Extension 'crosstool/setup.bzl' has errors
INFO: Elapsed time: 0.063s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

### Which operating system are you running Bazel on?

win 10

### What is the output of `bazel info release`?

bazel-3.7.2-windows-x86_64

**Comment by Pavank1992** [comment]
Hi @blueskyscorpio, Could you please update bazel to latest version? Please refer the [Bazel Doc](https://bazel.build/release#support-matrix).

**Note:** Bazel version older than Bazel 4 are no longer supported, Bazel users are recommended to upgrade to the latest LTS release or use rolling releases if you want to keep up with the latest changes at HEAD

**Comment by blueskyscorpio** [comment]
@Pavank1992  The ploblem has been solved after update bazel to latest version, thanks.
