### ISSUE TITLE
cc_library should support SO_CFLAGS

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/bazel#19028]
### Description of the feature request:

I want archive a so file like below command, but cc_library only has copts and linkopts, request support a soopts
```
gcc -fPIC -g -O3 -Wall -Wextra -fno-stack-protector -Wno-unused-parameter -DLIBURING_INTERNAL  -nostdlib -nodefaultlibs -ffreestanding -fno-builtin -fno-stack-protector -shared -Wl,--version-script=liburing.map -Wl,-soname=liburing.so.2 -o liburing.so.2.5 setup.os queue.os register.os syscall.os
```

**Comment by keith** [comment]
How would this differ from linkopts if you use linkshared=True on cc_binary or cc_shared_library
