### ISSUE TITLE
repo_mapping not work with bind

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/bazel#19023]
### Description of the bug:

my project import grpc, I use repo_mapping to substitute boringssl with openssl.  but not working, grpc still compile with boringssl. I guess repo_mapping not work with bind. beblow was code:

grpc imported in my project WORKSPACE:

```
http_archive(
    name = "com_github_grpc_grpc",
    repo_mapping = {
        "@boringssl": "@openssl",
        #"@openssl": "@boringssl",
    },
    sha256 = "7c861942ed0d8f41b5eb30bdb322719ade7c30791b4585338a500ef0facc662a",
    strip_prefix = "grpc-68a71aef9121d6647f3b054e82478c8596733dfc",
    urls = [
        "https://code.xxx.com/xxx/grpc/-/archive/68a71aef9121d6647f3b054e82478c8596733dfc/grpc-68a71aef9121d6647f3b054e82478c8596733dfc.tar.gz",
    ],
)
```

```
   native.bind(
        name = "libssl",
        actual = "@boringssl//:ssl",
    )
```

work if change to
```
   native.bind(
        name = "libssl",
        actual = "@openssl//:ssl",
    )
```

bazel 5.2.0

**Comment by Pavank1992** [comment]
Hi @xiedeacc, Could you please update bazel to [latest version](https://bazel.build/release#support-matrix). If issue still persist, could you help us to reproduce the issue with minimal steps?

**Comment by xiedeacc** [comment]
cc_library(
name = "openssl",
linkopts = ["-lssl", "-lcrypto",],
)
