### ISSUE TITLE
http_archive and git_repository should support target dependency alias

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/bazel#19022]
### Description of the feature request:

my project import A and B, and B depend @A//:foo,  but foo name in A is foo_alias, so when compile B, will meet no target foor in A. but A has that target, it just has another name

**Comment by meteorcloudy** [comment]
@xiedeacc I don't fully understand the problem, can you please give a concrete example?

**Comment by xiedeacc** [comment]
project A workspace file

```
workspace(name = "A")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository", "new_git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "B",
    ....
)

http_archive(
    name = "C",
    ....
)
```

B BUILD file
```

cc_library(
    name = "fooB",
    deps = [  
    ],
)
```

C BUILD file

```

cc_library(
    name = "fooC",
    deps = [  
      "@B//:fooB_anothername", #infact fooB_anothername is the same target fooB in B
    ],
)
```
so when compile C, C cannot find fooB_anothername in B, for fooB_anothername  in B named fooB, is there any rules can made C alias "@B//:fooB_anothername" to "@B//:fooB" ?

**Comment by meteorcloudy** [comment]
You can try the alias rule: https://bazel.build/reference/be/general#alias

**Comment by xiedeacc** [comment]
alias cannot fix this problem
