### ISSUE TITLE
bazel_toolchain_test is flaky

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1903]
http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=latest,PLATFORM_NAME=ubuntu_15.10-x86_64/274/console

This test tries to download stuff from the internet, this is a bit too flaky.

We maintain a mirror of Bazel stuff, if we want to maintain that test we should just vendor the toolchain on that mirror.

**Comment by katre** [comment]
After 50b4e8f62b57f2d13acc9b3538525a231dba704e, we can no longer execute "bazel test //src/test/shell/bazel/...", as it fails with the error:
ERROR: /usr/local/google/home/jcater/repos/bazel/src/test/shell/bazel/testdata/bazel_toolchain_test_data/tools/arm_compiler/BUILD:46:1: no such package 'tools/arm_compiler/linaro_linux_gcc': BUILD file not found on package path and referenced by '//src/test/shell/bazel/testdata/bazel_toolchain_test_data/tools/arm_compiler:linaro_linux_linker_files'.
ERROR: /usr/local/google/home/jcater/repos/bazel/src/test/shell/bazel/testdata/bazel_toolchain_test_data/tools/arm_compiler/BUILD:46:1: no such package 'tools/arm_compiler/linaro_linux_gcc': BUILD file not found on package path and referenced by '//src/test/shell/bazel/testdata/bazel_toolchain_test_data/tools/arm_compiler:linaro_linux_linker_files'.
ERROR: /usr/local/google/home/jcater/repos/bazel/src/test/shell/bazel/testdata/bazel_toolchain_test_data/tools/arm_compiler/BUILD:46:1: no such package 'tools/arm_compiler/linaro_linux_gcc': BUILD file not found on package path and referenced by '//src/test/shell/bazel/testdata/bazel_toolchain_test_data/tools/arm_compiler:linaro_linux_linker_files'.
ERROR: Analysis of target '//src/test/shell/bazel/testdata/bazel_toolchain_test_data/tools/arm_compiler:linaro_linux_linker_files' failed; build aborted.
INFO: Elapsed time: 0.193s
ERROR: Couldn't start the build. Unable to run tests.

**Comment by damienmg** [comment]
No more flake.
