### ISSUE TITLE
Improve configurable attributes for sh_test

### ISSUE THREAD

**Issue by salguarnieri** [bazelbuild/bazel#1904]
I tried using configurable attributes to specify different test behavior on different OSes but ran into a few problems.

1) args and tags appear to be non configurable but aren't listed as such in the documentation. (https://www.bazel.io/versions/master/docs/be/shell.html#sh_test)

2) Could either args or tags be made configurable? I got around the limitation by making the select statement in srcs, but I could be a lot more precise by sending different arguments on the different OSes.

The code I'm referring to is approximately here:
https://github.com/google/kythe/blob/master/kythe/cxx/indexer/cxx/testdata/cxx_indexer_test.bzl#L40

**Comment by ahumesky** [comment]
Tags is indeed non-configurable:
https://github.com/bazelbuild/bazel/blob/6aa2c274c1ca80e3f34bf02ef6d6c3e785a2ceaf/src/main/java/com/google/devtools/build/lib/analysis/BaseRuleClasses.java#L174-L175

however args appears to be configurable:
https://github.com/bazelbuild/bazel/blob/6aa2c274c1ca80e3f34bf02ef6d6c3e785a2ceaf/src/main/java/com/google/devtools/build/lib/analysis/BaseRuleClasses.java#L129

**Comment by salguarnieri** [comment]
Looks like this feature got added in 0.3.2. Sorry for the noise. I'll be looking forward to making use of it when we make the jump to require 0.3.2.
