### ISSUE TITLE
`bazel clean --expunge_async` silently orphans output dir on Mac (and fails on Win?)

### ISSUE THREAD

**Issue by mmdriley** [bazelbuild/bazel#1906]
`bazel clean --expunge_async` tries to run the same command, independent of OS:
`exec >&- 2>&- <&- && (/usr/bin/setsid /bin/rm -rf %s &)&`
(https://github.com/bazelbuild/bazel/blob/c484f19a2cf7427887d6e4c71c8534806e1ba83e/src/main/java/com/google/devtools/build/lib/runtime/commands/CleanCommand.java#L152)

`/usr/bin/setsid` doesn't exist on Mac OS X, so `blaze clean --expunge_async` effectively means: move the big cache somewhere else and leave it there forever. Even though the code claims to look at the error result, this fails _silently_ for me on OS X.

I can only imagine how this fails on Windows.

P0 should be to fail the `expunge_async` command on any non-Linux platforms. P2 would be to make it work.

**Comment by rokstrnisa** [comment]
The Win part is probably related to #1586.

**Comment by mmdriley** [comment]
I don't think so. #1586 is about `clean --expunge`, which seems to use a cross-platform delete: https://github.com/bazelbuild/bazel/blob/c484f19a2cf7427887d6e4c71c8534806e1ba83e/src/main/java/com/google/devtools/build/lib/runtime/commands/CleanCommand.java#L137

In this case, the command fails on Windows because Windows isn't Linux.

**Comment by damienmg** [comment]
To precise about priority: we should make expunge_async fails on darwin and windows for 0.4, and try to fix it in next release

**Comment by damienmg** [comment]
https://bazel-review.googlesource.com/c/6694 is in-flight for falling back to --expunge until we totally fix it (which is the blocker for 0.4).

**Comment by mmdriley** [comment]
Should I file a new issue to track the real fix?

**Comment by damienmg** [comment]
This should not have been marked as fixed.

**Comment by laszlocsomor** [comment]
Related bugs: #3043, #2480, #1586
