### ISSUE TITLE
The module lockfile doesn't contain hashes of files used in extension impl functions

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#19068]
```bzl
def _my_ext_impl(mctx):
  do_something(mctx.read(Label("//:abc.txt")))
my_ext = module_extension(_my_ext_impl)
```

If `//:abc.txt` changes, `my_ext` should be re-run.

**Comment by Wyverald** [comment]
@bazel-io fork 6.4.0

**Comment by brentleyjones** [comment]
Since the lockfile is enabled by default now in 6.3.0, is this high enough priority to fix in 6.3.1? How big of an impact is this bug (doesn't seem like a feature request)?

**Comment by Wyverald** [comment]
Hmm. I wonder if people consider this bad enough to warrant disabling lockfiles by default again. My gut feeling is that it's too big of a fix to go in 6.3.1, but am not 100% on that. @meteorcloudy WDYT?

**Comment by fmeum** [comment]
Does it rerun when a file referenced by label from a tag changes? If not, then `go_deps.from_file(go_mod = "//:go.mod")` would no longer see any changes to Go deps, which would be bad. I can test this tomorrow.

**Comment by Wyverald** [comment]
It wouldn't. Essentially any file read by the extension impl function wouldn't be noticed (unless the Bazel server process is alive, in which case Skyframe handles it).

I'm more and more leaning towards marking this a bug instead ... in fact I'll just go ahead and do it.

**Comment by meteorcloudy** [comment]
Yes, I'm inclined to also backport the fix to 6.3 as well. Trying to use the lockfile feature for Bazel itself with 6.3.0, this bug makes it quite awkward.

**Comment by Wyverald** [comment]
@bazel-io fork 6.3.0

**Comment by Wyverald** [comment]
@bazel-io fork 6.3.1

**Comment by iancha1992** [comment]
@Wyverald @SalmaSamy 
When cherry-picking this to release-6.4.0, There are some merge conflicts with some files.

1) src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileValue.java
Conflicts with the `getModuleExtensionDiff function`

2) src/main/java/com/google/devtools/build/lib/bazel/bzlmod/LockFileModuleExtension.java
`public abstract ImmutableMap<String, String> getEnvVariables()` should already have been part of the LockFileModuleExtension class in the release branch.
We also have conflicts with the `create` function

3) src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalFunction.java
Conflicts with the `singleExtensionEvalValue` variable

cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
thanks, Ian. @SalmaSamy could you send a cherry-pick PR later?

**Comment by SalmaSamy** [comment]
Sure!

**Comment by iancha1992** [comment]
@bazel-io fork 6.3.2
