### ISSUE TITLE
Spurious error message when concatenating selects

### ISSUE THREAD

**Issue by ahyangyi** [bazelbuild/bazel#1907]
```
srcs = select({
    ":foo": ["foo.c"],
    "//conditions:default": [],
    }) + select({
    ":foo_2": ["foo.c"],
    "//conditions:default": [],
    })
```

Assuming that `foo` and `foo_2` are two `config_settings` that are actually mutually exclusive, this expression would never contain duplicated elements. However, Bazel complains about that.

**Comment by gregestren** [comment]
The message: `Label '//testapp:foo.c' is duplicated in the 'srcs' attribute of rule 'cs'`

To support something like this we'd have to disable loading time duplicate label checking and move that to post-select time or just not do it.

Another conceptual problem is cases where `:foo` and `:foo_2` aren't *intrinsically* mutually exclusive. So the duplicate may or may not happen depending on how the build is invoked. Should that preemptively trigger an error or should Bazel just "wait and see" what the actual invocation looks like?

**Comment by aiuto** [comment]
I can not reproduce this and get an error. Since this is a very old issue that has not received much comment, I am going to close on the assumption that it was fixed and forgotten.
