### ISSUE TITLE
Wrong working directory for running external and/or host binaries.

### ISSUE THREAD

**Issue by ahyangyi** [bazelbuild/bazel#1908]
Generally, the working directory when running an `*_binary` would be `execroot/${WORKSPACE_DIR_NAME}/bazel-out/${TOOLCHAIN_NAME}/${PATH_TO_TARGET}.runfiles/${WORKSPACE_NAME}`. However, when running a binary which was built from an external repository and as a host binary as a tool of another `genrule`, the working directory becomes 
`execroot/${WORKSPACE_DIR_NAME}`.

Apparently, `File.short_path` does not take this into account. While the documentation at https://www.bazel.io/versions/master/docs/skylark/lib/File.html#path says `short_path` should work for binaries appearing in runfiles of other rules, it does not actually work in this particular case.

**Comment by ahyangyi** [comment]
Note that I am not sure if it's being external or being host causing this problem. I can only say that the issue happens when both conditions are satisfied.

**Comment by hermione521** [comment]
@kchodorow can you take a look? Thanks.

**Comment by ahyangyi** [comment]
I should mention that this happened in Bazel 0.3.1.

Due to the changes to the sandboxing I am not able to properly test in Bazel 0.3.2 for now. I'll report back when I finish my migration to 0.3.2.

**Comment by ulfjack** [comment]
Working as intended?
