### ISSUE TITLE
installing bazel with OS X 10.12 (Sierra) - SHA256 mistmatch

### ISSUE THREAD

**Issue by skgbanga** [bazelbuild/bazel#1909]
Hi,
I am trying to install bazel on MacOS Sierra, but getting the following error: 

> projects/Sandbox - [master●] » brew install bazel
> Warning: You are using OS X 10.12.
> We do not provide support for this pre-release version.
> You may encounter build failures or other breakages.
> ==> Downloading https://github.com/bazelbuild/bazel/archive/0.2.1.tar.gz
> ==> Downloading from https://codeload.github.com/bazelbuild/bazel/tar.gz/0.2.1
> ######################################################################## > 100.0%
> Error: SHA256 mismatch
> Expected: be964f98480ed258f249fc44c467a293e3a143aa750149b970da3d6719ba6ff1
> Actual: 9978505baa12de58b82cc04297fbcbfecc5b4f6c688b3a50ce985a5ad965da0b
> Archive: /Library/Caches/Homebrew/bazel-0.2.1.tar.gz
> To retry an incomplete download, remove the file above.

I get the same results on retrying.

**Comment by skgbanga** [comment]
Closing this. After upgrading to MacOS Sierra, I also had to update my brew installation, and it worked after that.

**Comment by ddofer** [comment]
Issue exists for me, 10.12.16, even after brew update, cleanup, upgrade. 
==> Downloading https://github.com/bazelbuild/bazel/archive/0.3.1.tar.gz
==> Downloading from https://codeload.github.com/bazelbuild/bazel/tar.gz/0.3.1
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 52beafc9d78fc315115226f31425e21df1714d96c7dfcdeeb02306e2fe028dd8
Actual: 218d0e28b4d1ee34585f2ac6b18d169c81404d93958815e73e60cc0368efcbb7
