### ISSUE TITLE
Use without CROSSTOOL configuration

### ISSUE THREAD

**Issue by schroederc** [bazelbuild/bazel#191]
Even if a build is only made up of java_library rules or Skylark rules, Bazel requires C++ configuration in //tools/cpp. 

This requirement should be removed for non-C++ builds.

**Comment by damienmg** [comment]
I don't think that's doable easily but we have a plan to ship automatically configuration for default tooling along with Bazel (//tools package would disappear). Would that be sufficient?

**Comment by schroederc** [comment]
The issue would still stand for those without need for the C++ rules.

The automatic configuration would help for Kythe, though.

**Comment by hanwen** [comment]
this is not happening any time soon. java_libraries can depend on cc_library through JNI, which is why the rules are tied to C++ too. There are some plans to fix this, but it will take a while.

**Comment by ulfjack** [comment]
We're closer now. All the rules are annotated with required fragments, and this is enforced. We'd need to add the additional notion of optional fragments, have the Java rules handle that correctly, and also provide a way to disable the cpp fragment.

**Comment by ulfjack** [comment]
We haven't made any progress since my last post.

**Comment by ulfjack** [comment]
We have made some progress. We're moving all the built-in rules to explicit *_toolchain rules, which should subsequently allow us to avoid loading those eagerly. That in turn should make it easier to avoid even having a toolchain rule if you don't have any rules that need it.

**Comment by hlopko** [comment]
This is fixed! :) Bazel 0.21 doesn't need C++ toolchain when no C++ is built. \o/
