### ISSUE TITLE
Can't find ObjC headers in external library.

### ISSUE THREAD

**Issue by rockwotj** [bazelbuild/bazel#1911]
Trying to add an external library to the `ios-app` example [here](https://github.com/bazelbuild/examples)

I added the following to the bottom of the `tutorial/WORKSPACE` file:

```
new_git_repository(
  name = "my_unirest",
  remote = "https://github.com/Mashape/unirest-obj-c.git",
  tag = "1.1.4",
  build_file_content = """
package(default_visibility = [ "//visibility:public" ])
objc_library(
  name="Unirest",
  srcs=glob(["Unirest/*.m", "Unirest/**/*.m"], exclude=[]),
  hdrs=glob(["Unirest/*.h", "Unirest/**/*.h"], exclude=[]),
  sdk_frameworks=[
    "Foundation",
  ],
  deps=[],
)
""",
)
```

Then modified `tutorial/ios-app/BUILD` and the `UrlGetClasses` rule to be:

```
objc_library(
    name = "UrlGetClasses",
    srcs = [
        "UrlGet/AppDelegate.m",
        "UrlGet/UrlGetViewController.m",
    ],
    hdrs = glob(["UrlGet/*.h"]),
    deps = [
      "@my_unirest//:Unirest"
    ],
    xibs = ["UrlGet/UrlGetViewController.xib"],
)
```

Then I tried to add `#import "UNIRest.h"` to `tutorial/ios-app/UrlGet/UrlGetViewController.h` and got the following error:

```
$ bazel build :UrlGetClasses --verbose_failures
INFO: Found 1 target...
ERROR: /Users/rockwood/Workspaces/tmp/examples/tutorial/ios-app/BUILD:18:1: null failed: xcrunwrapper failed: error executing command 
  (cd /private/var/tmp/_bazel_rockwood/c114bfd10e9798d5ba870a1d59fed286/execroot/tutorial && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneSimulator \
    APPLE_SDK_VERSION_OVERRIDE=9.3 \
    XCODE_VERSION_OVERRIDE=7.3.1 \
  bazel-out/host/bin/external/bazel_tools/tools/objc/xcrunwrapper clang -Wshorten-64-to-32 -Wbool-conversion -Wconstant-conversion -Wduplicate-method-match -Wempty-body -Wenum-conversion -Wint-conversion -Wunreachable-code -Wmismatched-return-types -Wundeclared-selector -Wuninitialized -Wunused-function -Wunused-variable -fexceptions -fasm-blocks '-fobjc-abi-version=2' -fobjc-legacy-dispatch -DOS_IOS '-mios-simulator-version-min=7.0' -arch x86_64 -isysroot __BAZEL_XCODE_SDKROOT__ -F __BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F __BAZEL_XCODE_DEVELOPER_DIR__/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -O0 '-DDEBUG=1' -iquote . -iquote bazel-out/local-fastbuild/genfiles -fobjc-arc -c ios-app/UrlGet/AppDelegate.m -o bazel-out/local-fastbuild/bin/ios-app/_objs/UrlGetClasses/ios-app/UrlGet/AppDelegate.o -MD -MF bazel-out/local-fastbuild/bin/ios-app/_objs/UrlGetClasses/ios-app/UrlGet/AppDelegate.d): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from ios-app/UrlGet/AppDelegate.m:17:
ios-app/UrlGet/UrlGetViewController.h:16:9: fatal error: 'UNIRest.h' file not found
#import "UNIRest.h"
        ^
1 error generated.
Target //ios-app:UrlGetClasses failed to build
INFO: Elapsed time: 0.353s, Critical Path: 0.25s
```

Any idea why this happened or what I did wrong?

**Comment by hermione521** [comment]
@c-parsons can you help? Thanks.

**Comment by c-parsons** [comment]
Is Unirest.h actually an available header under the repository?
To help track down the issue, you might consider explicitly enumerating the list of included headers in :Unirest (and sources, for that matter) instead of globbing them.

**Comment by rockwotj** [comment]
If I explicitly add `+ ["Unirest/UNIRest.h"]` to the glob I get a duplicate header exception.

`ERROR: /private/var/tmp/_bazel_rockwood/c114bfd10e9798d5ba870a1d59fed286/external/my_unirest/BUILD:3:1: Label '@my_unirest//:Unirest/UNIRest.h' is duplicated in the 'hdrs' attribute of rule 'Unirest'.
E`

**Comment by hochhaus** [comment]
I think that this issue is similar to (or maybe the same as) one I just ran into (https://github.com/bazelbuild/bazel/issues/2668).

In my case, I suspect that the underlying issue is that paths are built incorrectly when referring to headers in external repos. For example, I'm seeing file paths along the lines of:

```/Users/ahochhaus/Desktop/ll/external/[redacted]_webrtc_ios/WebRTC.framework/Headers/RTCSessionDescription.h```

while they should be

```/Users/ahochhaus/Desktop/ll/bazel-ll/external/[redacted]_webrtc_ios/WebRTC.framework/Headers/RTCSessionDescription.h```

(Note the missing `bazel-ll` in the middle of the path)

@c-parsons Can you help me debug further?

**Comment by lswith** [comment]
I'm getting this issue to but its related to https://github.com/bazelbuild/bazel/issues/306. This seems to occur in quite a few cocoapods.
