### ISSUE TITLE
`java_binary`'s `env` has no effect with Bazel@HEAD

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#19115]
### Description of the bug:

`java_binary`'s `env` attribute is ignored when the binary is run with `bazel run`.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
# Foo.java
public class Foo {
  public static void main(String[] args) {
    System.out.println("Hello, " + System.getenv("MY_NAME") + "!");
  }
}

# BUILD
java_binary(
    name = "Foo",
    srcs = ["Foo.java"],
    env = {"MY_NAME": "Bazel"},
    main_class = "Foo",
)
```

```
$ USE_BAZEL_VERSION=6.3.0 bazel run //:foo
...
Hello, Bazel!
$ USE_BAZEL_VERSION=1f0f6670088bcd7b6d6ded4b32c6eedc7a9027d9 bazel run //:Foo
...
Hello, null!
```

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

1f0f6670088bcd7b6d6ded4b32c6eedc7a9027d9

### Any other information, logs, or outputs that you want to share?

It looks like the Starlark implementation of `java_binary` doesn't return `RunEnvironmentInfo`.

**Comment by fmeum** [comment]
CC @hvadehra

**Comment by hvadehra** [comment]
I'll push out a fix soon.
