### ISSUE TITLE
Bazel CI flaky test failure com.google.devtools.build.lib.buildtool.OutputArtifactConflictTest testTwoConflictingTargets_keepGoing_behaviorDifferences

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#19112]
https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/01880a39-672a-75de-b7f4-e14060369f53?branch=master

Found in list of Postsubmit CI Builds : https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/01880a39-672a-75de-b7f4-e14060369f53?branch=master#failed

Platform : Linux 

Logs:

```

//src/test/java/com/google/devtools/build/lib/buildtool:OutputArtifactConflictTest FLAKY
```

CC Greenteam [@fweikert](https://github.com/fweikert)

**Comment by joeleba** [comment]
Should be fixed with https://github.com/bazelbuild/bazel/commit/ff83807a8e792c5d8608464d6a17127562165680.
