### ISSUE TITLE
Can't create Telegram IPA with bazel 4.0.0 (error - security: cert import failed: A default keychain could not be found)

### ISSUE THREAD

**Issue by sergiocasual** [bazelbuild/bazel#19118]
### Description of the bug:

I can't create Telegram IPA with instructions in readme. On build phase I get next error:
ERROR: /Users/s.teteryatnik/Downloads/Telegram-iOS/Telegram/BUILD:1546:14: Processing and signing IntentsExtension failed: (Exit 1): process-and-sign--389255329.sh failed: error executing command (from target //Telegram:IntentsExtension)
(cd /private/var/tmp/_bazel_root/887dba9f4a80f0175ab48c6032216a56/execroot/main && 
exec env - 
APPLE_SDK_PLATFORM=iPhoneOS 
APPLE_SDK_VERSION_OVERRIDE=16.2 
XCODE_VERSION_OVERRIDE=14.2.0.14C18 
bazel-out/applebin_ios-ios_armv7-opt-ST-2967bd56a867/bin/Telegram/IntentsExtension-intermediates/process-and-sign--389255329.sh should_sign should_compress)
Configuration: c6bb6bd296e25c168482670045b3949392953a77726ba5711b8379efb029e2e3
Execution platform: @local_config_platform//:host

security: cert import failed: A default keychain could not be found.
security: problem decoding

I have successfully created all Identifiers & Distribution Profiles

PLEASE, HELP! :)

Expected Behavior

IPA successfully created

Actual Behavior

IPA creation failed

Steps to Reproduce

Copy and edit build-system/appstore-configuration.json
Copy build-system/fake-codesigning. Create and download distribution provisioning profiles.
Generate an Xcode project:
python3 build-system/Make/Make.py 
--cacheDir="$HOME/telegram-bazel-cache" 
generateProject 
--configurationPath=configuration_from_step_1.json 
--codesigningInformationPath=directory_from_step_2
Run build:
python3 build-system/Make/Make.py 
--cacheDir="$HOME/telegram-bazel-cache" 
build 
--configurationPath=...see previous section... 
--codesigningInformationPath=...see previous section... 
--buildNumber=100001 
--configuration=release_arm64
Screenshots and Videos

Снимок экрана 2023-07-28 в 14 36 51
Environment

Device: MacBook Pro Apple M1 Pro

Xcode version: 14.2, 14.3

Mac OS version: 13.4

App version: 9.6.3, 9.6.5

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Follow instructions on https://github.com/TelegramMessenger/Telegram-iOS

### Which operating system are you running Bazel on?

Ventura 13.4 (22F66)

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

With Telegram

bazel version
Build label: 4.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:38:50 2021 (1611214730)
Build timestamp: 1611214730
Build timestamp as int: 1611214730

**Comment by keith** [comment]
this is likely an issue with your code signing configuration specific to how you set that up for the telegram app, you should try to debug that or otherwise report to the telegram repo
