### ISSUE TITLE
bazel cannot handle .include directive in assembly file

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/bazel#19127]
### Description of the bug:

my assembly file xxx.S 
```
#include "xxx.h"
.include "macro.inc"

... 

```
macro.inc has same .macro
bazel will meet error said cannot find macro.inc, infact that file exists, is just bazel cannot handle .include directive correct

### What is the output of `bazel info release`?

6.2.1

**Comment by Pavank1992** [comment]
Hi @xiedeacc, could you please explain the issue in details. Also, please help us how to reproduce the issue with additional information like minimal steps to reproduce the issue, which OS and environment you are using etc?
