### ISSUE TITLE
Cannot build with GPU support

### ISSUE THREAD

**Issue by AFAgarap** [bazelbuild/bazel#1912]
I am building TensorFlow from the source for days already. I'm stuck with `bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`. Everytime I am running it, it gives me the following errors:

``
.
ERROR: /home/darth/.cache/bazel/_bazel_darth/08554d152596e5a7df399506682a63f3/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
	File "/home/darth/.cache/bazel/_bazel_darth/08554d152596e5a7df399506682a63f3/external/local_config_cuda/crosstool/BUILD", line 4
		error_gpu_disabled()
	File "/home/darth/.cache/bazel/_bazel_darth/08554d152596e5a7df399506682a63f3/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
		fail("ERROR: Building with --config=c...")
ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
ERROR: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /home/darth/.cache/bazel/_bazel_darth/08554d152596e5a7df399506682a63f3/external/local_config_cuda/crosstool/BUILD.
INFO: Elapsed time: 1.079s
``

Help would be appreciated.

**Comment by hermione521** [comment]
Hi, it looks more like a tensorflow problem. Can you report this to tensorflow? Thanks.
