### ISSUE TITLE
Error no such attribute 'exec_tools' in 'genrule' rule  on Bazel@HEAD.

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#19130]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3202#0189aa1f-7d0d-42e1-8905-49d1986bd094

Platform : Ubuntu, Windows, MacOS

Logs: 
```
ERROR: /private/var/tmp/_bazel_buildkite/8c08c49ddb355665dd925b998661185f/external/desugar_jdk_libs/BUILD:13:8: @desugar_jdk_libs//:maven_release: no such attribute 'exec_tools' in 'genrule' rule (did you mean 'executable'?)
(06:10:28) ERROR: /private/var/tmp/_bazel_buildkite/8c08c49ddb355665dd925b998661185f/external/desugar_jdk_libs/BUILD:30:8: @desugar_jdk_libs//:maven_release_jdk11: no such attribute 'exec_tools' in 'genrule' rule (did you mean 'executable'?)

(06:10:29) ERROR: /Users/buildkite/builds/bk-macstudio-2/bazel-downstream-projects/bazel/tools/android/runtime_deps/BUILD.bazel:70:8: Target '@desugar_jdk_libs//:desugar_jdk_libs' contains an error and its package is in error and referenced by '//tools/android/runtime_deps:desugar_jdk_libs'
(06:10:29) ERROR: Analysis of target '//src/test/shell/bazel:bazel_android_tools_test' failed; build aborted: Analysis failed

```

Breaking commit : [c061e57a7004a88eeb2f84d094d9a88b56c146b6](https://github.com/bazelbuild/bazel/commit/c061e57a7004a88eeb2f84d094d9a88b56c146b6)

CC Greenteam @meteorcloudy

**Comment by sgowroji** [comment]
Protobuf is also failing with the same error https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3202#0189a9b6-1927-4b8c-8bfb-cf5b47ea3bd7

**Comment by meteorcloudy** [comment]
Breaking commit rollbacked at https://github.com/bazelbuild/bazel/commit/0c917255ca95b5c25ae6cf61ebe7a63c1061f73f

/cc @katre

**Comment by katre** [comment]
Migration issue: https://github.com/bazelbuild/bazel/issues/19132

**Comment by meteorcloudy** [comment]
Thanks, the breakage has been resolved.
