### ISSUE TITLE
debug_context should be a public API

### ISSUE THREAD

**Issue by anhlinh123** [bazelbuild/bazel#19147]
### Description of the feature request:

debug_context is one of the params of CcInfo, but currently it can't be used by public users.
There is a check that I believe to prevent users from using it
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/cpp/CcInfo.java#L73
This is problematic for custom cpp rules, as we have no ways to provide debug info to the dependants.

My naive request would be making debug_context public, so that custom rules can access and forward it downstream.
But I'm ignorant of why debug_context was hidden in the first place, so making it public is probably not feasible.
So any mechanism that helps custom cpp rules retrieve debug info (dwo files), and pass it downstream, is also appreciated.

### Which category does this issue belong to?

C++ Rules

### What underlying problem are you trying to solve with this feature?

Custom cpp rules can't access debug_context and create CcInfo with debug_context

### Which operating system are you running Bazel on?

Ubuntu

### What is the output of `bazel info release`?

release 6.1.1

**Comment by buildbreaker2021** [comment]
I think this is the same as: https://github.com/bazelbuild/bazel/issues/19149
