### ISSUE TITLE
When could bazel fetch transitive dependencies?

### ISSUE THREAD

**Issue by is03wlei** [bazelbuild/bazel#1914]
It's really a big pain to generate transitive dependencies even using generate_workspace.

**Comment by hermione521** [comment]
@kchodorow can you answer this? Thanks.

**Comment by dslomov** [comment]
We do not have a very good design for fetching transitive dependencies atm.  See the [thread](https://groups.google.com/d/msg/bazel-dev/YGV4_pMIMmA/z3o_64ewAQAJ)

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
