### ISSUE TITLE
cc_library doesn't collect debug_context(s) from implementation_deps

### ISSUE THREAD

**Issue by anhlinh123** [bazelbuild/bazel#19146]
### Description of the bug:

Currently, cc_library only merges debug_context(s) from `deps` and forward them to its dependents.
Consequently, cc_binary can't generate a dwp file containing sufficient debug info.

### Which category does this issue belong to?

C++ Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

cc_library(
    name = "lib",
    implementation_deps = ["impl_dep1, impl_dep2"],
)

\# the file ":bin.dwp" doesn't have all the debug info from "impl_dep1", "impl_dep2"
cc_binary(
    name = "bin",
    deps = ["lib"],
)

### Which operating system are you running Bazel on?

Ubuntu

### What is the output of `bazel info release`?

release 6.1.1

### Any other information, logs, or outputs that you want to share?

I believe this line https://github.com/bazelbuild/bazel/blob/master/src/main/starlark/builtins_bzl/common/cc/cc_library.bzl#L309C123-L309C123
should be changed to:
`debug_context = cc_helper.merge_cc_debug_contexts(compilation_outputs, cc_helper.get_providers(ctx.attr.deps + ctx.attr.implementation_deps, CcInfo))`

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 6.4.0 RC4](https://releases.bazel.build/6.4.0/rc4/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!
