### ISSUE TITLE
[shell rules] `sh_library` breaks on cross-repository dependencies

### ISSUE THREAD

**Issue by fughilli** [bazelbuild/bazel#19152]
### Description of the bug:

If one defines a `sh_library` in a repository, and then sources that `sh_library` in another repository, the target of the source statement cannot be resolved by bash.

Discussion on Bazel slack channel: https://bazelbuild.slack.com/archives/CA31HN1T3/p1690845438473009

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

./.bazelversion
```
5.3.1
```
./bar.sh
```
#!/bin/bash

source foo.sh
```
./dep_repo/foo.sh
```
#!/bin/bash

echo "Foo"
```
./WORKSPACE
```
workspace(name = "repo")

new_local_repository(
  name ="dep_repo",
  path = "dep_repo",
  workspace_file_content = "workspace(name = \"dep_repo\")",
  build_file_content = """
package(default_visibility=["//visibility:public"])

sh_library(
    name = "foo",
    srcs = [":foo.sh"],
)
  """,
)
```
./BUILD
```
sh_binary(
    name = "bar",
    srcs = [":bar.sh"],
    deps = [
        "@dep_repo//:foo",
    ],
)
```

### Which operating system are you running Bazel on?

MacOS

### What is the output of `bazel info release`?

release 5.3.1

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
N/A
```

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Not as far as I know.

### Have you found anything relevant by searching the web?

Nothing relevant AFAICT.

**Comment by fughilli** [comment]
Reproduction with the specified workspace setup above:

```
> bazelisk run //:bar
INFO: Analyzed target //:bar (41 packages loaded, 260 targets configured).
INFO: Found 1 target...
Target //:bar up-to-date:
  bazel-bin/bar
INFO: Elapsed time: 4.824s, Critical Path: 0.02s
INFO: 4 processes: 4 internal.
INFO: Build completed successfully, 4 total actions
INFO: Build completed successfully, 4 total actions
/private/var/tmp/_bazel_kbalke/a54d2e1472748e5bcfbd7649e499091e/execroot/repo/bazel-out/darwin_arm64-fastbuild/bin/bar: line 3: foo.sh: No such file or directory
>
```

**Comment by comius** [comment]
My focus isn't on sh rules ATM, however it would be really nice to fix this.

**Comment by fmeum** [comment]
You would need to prefix the path with `../<canonical repo name>/`. Since canonical repo names are considered an implementation detail with `--enable_bzlmod`, please use [the runfiles library](https://github.com/bazelbuild/bazel/blob/master/tools/bash/runfiles/runfiles.bash) to get the path to the other script.
