### ISSUE TITLE
same `module_extension` name in different bzl files could not be resolved while using bzlmod in bazel 6.3.1

### ISSUE THREAD

**Issue by xiemotongye** [bazelbuild/bazel#19155]
### Description of the bug:

We're using bzlmod.
This is a part of `MODULE.bazel`, which works fine in bazel 6.2.1.
```
a_ext = use_extension("//path/to/A:A.bzl", "my_ext")
use_repo(a_ext, "abc")
b_ext = use_extension("//path/to/B:B.bzl", "my_ext")
use_repo(b_ext, "xyz")
```
When I updated bazel to 6.3.1, there was an error in analysis phase.
```
ERROR: /my/workspace/library_path/BUILD:4:13: no such package '@_main~my_ext~2~xyz//':
The repository '@_main~my_ext~2~xyz' could not be resolved:
Repository '@_main~my_ext~2~xyz' is not defined and referenced by '//library_path:library_name'
ERROR: Analysis of target '//my_path:my_target' failed; build aborted:
```
It seems that in bazel 6.2.1, if there is a same `module_extension` name in different bzl files, the second one will be named as `@_main~my_ext2~xyz` in external directory. But in bazel 6.3.1, it seems that bazel is tring to find a module named as `@_main~my_ext~2~xyz` (adds a `~` after `ext`) which doesn't actually exist.

### Which operating system are you running Bazel on?

macOS 13.4.1

### What is the output of `bazel info release`?

release 6.3.1

### Have you found anything relevant by searching the web?

No

**Comment by fmeum** [comment]
Can confirm that this is a bug. The two extensions are assigned the prefixes `_main~my_ext~` and `_main~my_ext~2~` now, which is bad since the former is a prefix of the latter.

CC @Wyverald

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by iancha1992** [comment]
@bazel-io fork 6.4.0

**Comment by fmeum** [comment]
@iancha1992 This is a regression from Bazel 6.2.0, so unfortunately we may need a 6.3.2 release to cherry-pick this into.

**Comment by iancha1992** [comment]
> 

cc: @bazelbuild/triage
