### ISSUE TITLE
Warning uploading BEP files for symlinks

### ISSUE THREAD

**Issue by kjteske** [bazelbuild/bazel#19151]
### Description of the bug:

When using `--bes_backend` and `--remote_cache` with a symlink, a warning is printed, e.g.:

```
WARNING: Uploading BEP referenced local file /home/kteske/.cache/bazel/_bazel_kteske/020f4231a790243f1ddaeb9889e833df/execroot/__main__/bazel-out/k8-fastbuild/bin/the_symlink: /home/kteske/.cache/bazel/_bazel_kteske/020f4231a790243f1ddaeb9889e833df/execroot/__main__/bazel-out/k8-fastbuild/bin/the_symlink (No such file or directory)
java.io.FileNotFoundException: /home/kteske/.cache/bazel/_bazel_kteske/020f4231a790243f1ddaeb9889e833df/execroot/__main__/bazel-out/k8-fastbuild/bin/the_symlink (No such file or directory)
        at com.google.devtools.build.lib.unix.NativePosixFiles.stat(Native Method)
        ...
```

This warning is pretty harmless, but is very verbose and will cause users to ask questions and have to be taught to ignore this warning.

Using `--experimental_build_event_upload_strategy=local` avoids the warning, but then we lose the timing info, which is more important to us.

### Which category does this issue belong to?

Remote Execution

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Repro case at https://github.com/kjteske/bazel_bep_upload_warning_symlink

### Which operating system are you running Bazel on?

Linux (Ubuntu 20.04)

### What is the output of `bazel info release`?

release 6.3.1

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
N/A
```

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Unknown

### Have you found anything relevant by searching the web?

No

**Comment by coeuvre** [comment]
cc @tjgq

**Comment by tjgq** [comment]
I believe this was fixed in 5100d87, but it hasn't been backported to 6.x. (I haven't looked into how hard it would be to do that, there's probably other changes that would have to be backported first.)

**Comment by tjgq** [comment]
Thanks for checking! I will take a look when I can.

**Comment by tjgq** [comment]
@fmeum: yours seems to be a different problem, so I've filed a separate issue to investigate further: https://github.com/bazelbuild/bazel/issues/19847
