### ISSUE TITLE
Windows: Paths not relativized properly

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#1916]
Bazel always emits absolute paths in errors on Windows, which is clunky:

```
ERROR: C:/msys64/home/$USER/bazel/example_workspace/cpp/BUILD:3:1: undeclared inclusion(s) in rule '//cpp:hello-lib':
```

or

```
Target //proto:test_proto up-to-date:
  C:/msys64/var/tmp/_blaze_$USER/9b1eed1a423cf04373eb13e215b47824/example_workspace/bazel-out/local_windows_mingw-fastbuild/bin/proto/libtest_proto.jar
```

**Comment by laszlocsomor** [comment]
This is a feature request about aesthetics. P3 is accurate, maybe P4 would be fine too.

**Comment by laszlocsomor** [comment]
Related: https://github.com/bazelbuild/bazel/issues/7585

This bug and that one should be easy to fix while provide for a somewhat nicer user experience.

**Comment by meisterT** [comment]
Closing as it is not a bug, but cosmetics.
