### ISSUE TITLE
[6.4.0] same `module_extension` name in different bzl files could not be resolved while using bzlmod in bazel 6.3.1

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#19161]
Forked from #19155

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19164

**Comment by iancha1992** [comment]
Closing this as this is a duplicate as: https://github.com/bazelbuild/bazel/pull/19164
