### ISSUE TITLE
[6.4.0] `config_setting` incorrectly treated as implicit dependency by `--incompatible_visibility_private_attributes_at_definition`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#19178]
Forked from #19126

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts. Please resolve manually.

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts. Please resolve manually.

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts. Please resolve manually.

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19197
