### ISSUE TITLE
Is there any counterpart of "--sandbox_add_path" in Bazel 0.3.2?

### ISSUE THREAD

**Issue by ahyangyi** [bazelbuild/bazel#1917]
Hi,

I noticed that `--sandbox_add_path` was removed in Bazel 0.3.2, but an opposite option `--sandbox_block_path` was added. Is there any documentation that explains what happened to the sandbox and is there any replacement if I used to rely on `--sandbox_add_path`?

**Comment by ahyangyi** [comment]
Well, is http://www.bazel.io/docs/designs/2016/06/02/sandboxing.html relevant?

**Comment by hermione521** [comment]
I'm not sure if the design doc is updated enough.. @philwo 
But you can check this: https://github.com/bazelbuild/bazel/commit/e219a24a30960ab5c686dd09197b5e22626e1fe0

In short words, almost the whole system is readable by default now (not your workspace on Mac), so you just drop all the `--sandbox_add_path`. Feel free to reopen.

**Comment by philwo** [comment]
I updated that design doc + set the status to "launched" on 2016-09-13, but it seems that the website is still showing the old content. I don't know why...

@damienmg Do you know if we have to and if yes how can we update the website when we make changes to the static files? Can we automate this?

**Comment by damienmg** [comment]
It's automated, you modify the md files and when it gets pushed, ci.bazel.io
push it to GCS.

**Comment by philwo** [comment]
That's awesome, exactly how I wished it looks like :)
The puzzle remains though, then why does http://www.bazel.io/docs/designs/2016/06/02/sandboxing.html still show "Status: unimplemented", while the updated version I checked in internally ~4 weeks ago says "Status: launched"? (See cl/132971817).

**Comment by ahyangyi** [comment]
Is the "base image" thing implemented and documented, by the way?

**Comment by hermione521** [comment]
Not implemented yet

**Comment by rtsai** [comment]
Hello. After upgrading to bazel-0.3.2 and removing our use of "--sandbox_add_path=/dev/shm", our unit tests no longer work. We have some medium tests for a system that uses shared memory. We used --sandbox_add_path=/dev/shm with success in bazel-0.3.1, but bazel-0.3.2 does not seem to provide equivalent functionality.
