### ISSUE TITLE
Add more test for MSVC CROSSTOOL

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#1918]
The only test we have now is `bazel_windows_example_test`, since we added more features into MSVC CROSSTOOL, we need more tests in both java and shell to make sure it keep working.

**Comment by laszlocsomor** [comment]
@meteorcloudy : what's the state of this bug?

**Comment by meteorcloudy** [comment]
I think it's obsolete.
I created it when MSVC CROSSTOOL was still not default, now I think it's already well-tested since we're using it everywhere.
