### ISSUE TITLE
[6.4.0] Add toolchain type for Java bootstrap runtime

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#19201]
Forked from #18841

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts. Please resolve manually.
cc:@bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19216

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19220 by @fmeum
