### ISSUE TITLE
requestMetadata in grpc Header been filtered

### ISSUE THREAD

**Issue by Ruoye-W** [bazelbuild/bazel#19207]
### Description of the bug:

remote-apis defines requestMetadata key named "build.bazel.remote.execution.v2.requestmetadata-bin" in remote_execution.proto, and message requestMetadata will be encoded and set in each grpc request header when bazel 
 configures --remote_executor. It seems that the requestMetadata key contains "." seperator, which will be filtered if remote execution server using nginx as reverse proxy, nginx will filter "build.bazel.remote.execution.v2.requestmetadata-bin" field due to illegal syntax , so remote execution server could not get  invocation id, target id  from ExecuteRequest 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

build a simple example with --remote_executor configured,  use nginx as reverse proxy of remote execution server like buildfarm server. print all fields of ExecuteRequest header in buildfarm server, "build.bazel.remote.execution.v2.requestmetadata-bin" will be found miss in result.

### Which operating system are you running Bazel on?

6.3.1

### What is the output of `bazel info release`?

6.3.2

### Have you found anything relevant by searching the web?

not found

**Comment by coeuvre** [comment]
I think you should fire an issue to https://github.com/bazelbuild/remote-apis.

**Comment by sgowroji** [comment]
Hi @Ruoye-W, As mentioned above can you please raise issue at  [remote-apis](https://github.com/bazelbuild/remote-apis). We are closing this issue and reach us back if you have any queries. Thanks!
