### ISSUE TITLE
[Mirror] https://go.dev/dl/go1.20.7.linux-amd64.tar.gz

### ISSUE THREAD

**Issue by atetubou** [bazelbuild/bazel#19219]
### Please list the URLs of the archives you'd like to mirror:

https://go.dev/dl/go1.20.7.linux-amd64.tar.gz

This is to upgrade go toolchain in https://github.com/bazelbuild/remote-apis-sdks/pull/471.

**Comment by Pavank1992** [comment]
Hi @atetubou, Please find the requested mirror artifact below:
https://mirror.bazel.build/go.dev/dl/go1.20.7.linux-amd64.tar.gz
