### ISSUE TITLE
[6.4.0] Rename `cc_test_wrapper` to `cc_test`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#19227]
Forked from #18871

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts. Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19230

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19231 by @fmeum
