### ISSUE TITLE
[6.4.0] Cherry-pick commits to fix a Windows issue

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#19222]
Cherry-pick https://github.com/bazelbuild/bazel/commit/5647b26d7152f0a5ebd5d5fec2643d8e0b8dd661 and https://github.com/bazelbuild/bazel/commit/138f06fc90a5a238cc505ac075178889f7efb687 into 6.4

@bazelbuild/triage

**Comment by iancha1992** [comment]
@meteorcloudy 
There are conflicts when trying to cherry-pick both commits.

1) For https://github.com/bazelbuild/bazel/commit/5647b26d7152f0a5ebd5d5fec2643d8e0b8dd661,
In the ```.bazelrc``` file, below code is not in the release-6.4.0 branch. But it exists in the master branch.
```
# Fail if a glob doesn't match anything (https://github.com/bazelbuild/bazel/issues/8195)
build --incompatible_disallow_empty_glob
```

2) For https://github.com/bazelbuild/bazel/commit/138f06fc90a5a238cc505ac075178889f7efb687
In the ```.bazelrc``` file, below code is not in the release-6.4.0 branch. But it exists in the master branch.
```
# On Windows, we need pywin32 pip package, which doesn't work with the Python hermetic toolchain.
# See https://github.com/bazelbuild/rules_python/issues/1356
# Therefore, use the local detected Python toolchain on Windows.
build:windows --extra_toolchains=@bazel_tools//tools/python:autodetecting_toolchain
```
If another commit is not necessary, I can just accept the incoming change. Let us know please.

cc: @bazelbuild/triage

**Comment by meteorcloudy** [comment]
https://github.com/bazelbuild/bazel/commit/138f06fc90a5a238cc505ac075178889f7efb687 is still necessary, can you try to resolve the conflict, basically, we just need to add the following two lines to `.bazelrc`, we can ignore the rest.
```
build:windows_arm64 --platforms=//:windows_arm64
build:windows_arm64 --extra_toolchains=@local_config_cc//:cc-toolchain-arm64_windows
```

Thanks!

**Comment by meteorcloudy** [comment]
Oh, we also need https://github.com/bazelbuild/bazel/commit/d0de5e044c65fe7c5e414f860887be20087732da, sorry for missing this one!

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19232

@meteorcloudy I've cherry-picked https://github.com/bazelbuild/bazel/commit/d0de5e044c65fe7c5e414f860887be20087732da and https://github.com/bazelbuild/bazel/commit/138f06fc90a5a238cc505ac075178889f7efb687. I wasn't sure whether you wanted me to cherry-pick the https://github.com/bazelbuild/bazel/commit/5647b26d7152f0a5ebd5d5fec2643d8e0b8dd661. So I excluded it. Let me know if you want me to include it.

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19232

cc: @bazelbuild/triage
