### ISSUE TITLE
Allow @foo if @foo//:foo

### ISSUE THREAD

**Issue by jart** [bazelbuild/bazel#1924]
I'm allowed to say `//foo` when referencing `//foo:foo`. So it seems reasonable that I should be able to say `@foo` if I'm referencing `@foo//:foo`

**Comment by kchodorow** [comment]
Hmm, seems like it should be the shortening of `@foo//foo:foo`, but I guess that doesn't happen much with remote repos.  Also, maybe that's ridiculous (my example, not your request).

**Comment by jart** [comment]
If I'm not using repository_rule() then I'm only allowed to define a single BUILD file for the new_http_archive(), so it wouldn't be possible to have a foo/BUILD subpackage that defines foo.
