### ISSUE TITLE
RHEL9 images do not have us_US.UTF-8

### ISSUE THREAD

**Issue by spuliaiev-sfdc** [bazelbuild/bazel#19249]
### Description of the bug:

While running bazel build in the containers based on the RHEL9 with glibc-minimal - the build fails because it tries to set up locale to us_US.UTF-8 however this package provides on C.UTF-8

static final ImmutableMap<String, String> UTF8_ENVIRONMENT =
      ImmutableMap.of("LC_CTYPE", "en_US.UTF-8");

https://github.com/search?q=repo%3Abazelbuild%2Fbazel+UTF8_ENVIRONMENT&type=code

See the references:
https://bugzilla.redhat.com/show_bug.cgi?id=2000878

### Which category does this issue belong to?

External Dependency, Local Execution

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a docker image based on the registry.access.redhat.com/ubi9/ubi-minimal:9.1.0-1829
Add Bazel with some simple Java project and try to build.

### Which operating system are you running Bazel on?

ubi-minimal:9.1.0-1829

### What is the output of `bazel info release`?

release 6.1.0

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
private repository
```

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

not sure

### Have you found anything relevant by searching the web?

https://bugzilla.redhat.com/show_bug.cgi?id=2000878

https://github.com/osbuild/osbuild-composer/issues/2206
https://bugzilla.redhat.com/show_bug.cgi?id=1958876

**Comment by spuliaiev-sfdc** [comment]
Also: https://docs.ros.org/en/rolling/Installation/Alternatives/RHEL-Development-Setup.html#set-locale

**Comment by meteorcloudy** [comment]
@cushon Do you have any idea since this is from https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/java/JavaCompileActionBuilder.java;l=57?q=UTF8_ENVIRONMENT&ss=bazel

**Comment by cushon** [comment]
@meteorcloudy the original history for those Java tools explicitly configuring UTF-8 is in cl/120925801

**Comment by cushon** [comment]
Re-opening, the fix had to be rolled back: https://github.com/bazelbuild/bazel/pull/23470#issuecomment-2398255671

**Comment by fmeum** [comment]
@cushon Is that distribution internal to Google? Since only a single locale can be set and we don't have a way to determine it dynamically, I'm not sure what to do other than waiting for that distro to be updated.

**Comment by cushon** [comment]
It's internal. I'm looking in to whether it can be fixed, one alternative is to make this a Blaze/Bazel difference to avoid holding back the fix for Bazel.

**Comment by cushon** [comment]
I restored the fix for Bazel in https://github.com/bazelbuild/bazel/commit/ca5f6cf4604c0d28625dbbeed024276f17b653d7
