### ISSUE TITLE
Certain commands (query, mod, etc.) don't display fetch progress updates

### ISSUE THREAD

**Issue by BalestraPatrick** [bazelbuild/bazel#19252]
### Description of the bug:

Certain commands, such as `query` and `mod` don't display fetch progress updates. This provides a subpar experience because developers don't know what the progress of their commands is. 

In our project, we have an IDE integration that runs a Bazel `query` before generating an IDE project that developers can use. We run the query with `--noshow_progress` because the progress status isn't useful with commands such as `query` since it's only filled with statements like `Loading: X packages loaded`. When instead a `build` is ran, Bazel will properly display the progress along with the URL of the artifacts being downloaded.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Clean caches and run `bazel query //...` and see that it's not possible to see what workspace dependencies are being downloaded. If instead, you run `bazel build //...`, you'll see fetches being displayed along with their URLs.

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

6.3.2

### Have you found anything relevant by searching the web?

This was briefly discussed in the Bazel Slack: https://bazelbuild.slack.com/archives/CA31HN1T3/p1692105029206489

**Comment by fmeum** [comment]
@iancha1992 I think that this fits Team-ExternalDeps better.

**Comment by Wyverald** [comment]
It might just be because we don't have a proper UI event handler for query/mod/etc. I can take a look in a bit.

**Comment by Wyverald** [comment]
Hmm. I actually couldn't reproduce this. I made a WORKSPACE file with `http_archive(name="my_repo", url="https://speed.hetzner.de/1GB.bin")`, and when I do `bazel query @my_repo//:abc`, it does show the fetch progress of that huge file. (Similar with Bzlmod enabled.) Could you produce a minimal repro?

**Comment by fmeum** [comment]
When running `rm -f MODULE.bazel.lock && bazel shutdown && bazel <some command>` with Bazel from HEAD on https://github.com/bazelbuild/bazel-gazelle/tree/master/tests/bcr, I get:

* `build //...` and `cquery //...`: Everything works as expected.
* `query //...`: I see fetch progress, but the line above it says `checking cached actions` instead of `Computing main repo mapping...`.
* `mod graph`: No fetch progress events, only warnings/debug messages and then, eventually, the output.

**Comment by fmeum** [comment]
@Wyverald Did your commit also fix query?

**Comment by Wyverald** [comment]
It didn't, but that one is IMO at most a P4. I'd like to get the most salient bug fixed in 6.4.0 (the `mod` thing).

**Comment by Wyverald** [comment]
@bazel-io fork 6.4.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 6.4.0 RC1](https://releases.bazel.build/6.4.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!
