### ISSUE TITLE
support local retry when remote executor failed

### ISSUE THREAD

**Issue by csh2022** [bazelbuild/bazel#19255]
### Description of the feature request:

I hope the tasks to fallback and rerun locally if they fail on the remote_executor. However, after I added the --remote_local_fallback option, it only falls back to local re-execution when network issues occur. If there are any environmental issues causing errors, it just reports the error directly without falling back to local execution.

For example, a task relies on a specific dependency, but it is not installed in the environment of the remote executor, causing the task to fail when executed on the remote executor. However, this dependency has already installed locally, so instead of terminating with an error immediately, I hope the task can be rerun locally.

cc_library(
    name = "PocoFoundation",
    includes = ["."],
    linkopts = [
        "-L/opt/apollo/sysroot/lib",
        "-lPocoFoundation",
    ],

### Which category does this issue belong to?

Local Execution

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

release 7.0.0-pre.20230724.1

### Any other information, logs, or outputs that you want to share?

This task can be executed locally, but it hasn't been executed.

![image](https://github.com/bazelbuild/bazel/assets/24428215/70874e1f-09c0-4eb7-a348-f723dadbfc41)

**Comment by tjgq** [comment]
`--remote_local_fallback` is intended to work around transient failures, not permanent ones. I'm not sure it would be a good idea to unconditionally fall back (it would add latency to the edit/build/test cycle in the "permanent failure" case).

Why is it not possible to configure the remote execution environment correctly? In the case you describe, it looks like no C++ would compile remotely at all, so you'd be better off using `--strategy=CppCompile=standalone` (and likewise for other C++ mnemonics) and not even bother trying remotely.
