### ISSUE TITLE
Windows: referring to arguments of actions via "$arg" does not work

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#1926]
``` python
 ctx.action(
        mnemonic = "FixProtoSrcJar",
        inputs = outs,
        outputs = [srcjar],
        arguments = [srcjar.path + ".jar", srcjar.path],
        # weirdly fails
        command =  "cp $1 $2",
    )
```

the workaround is to expand manually:

```
command = " ".join(["cp", srcjar.path + ".jar", srcjar.path])
```

**Comment by ulfjack** [comment]
Uhm, what?

**Comment by dslomov** [comment]
Suspected reason: -we are not in Kansas anymore- this is not a bash command, but a Windows process. 
Will fix as part of clarifying genrules story.

**Comment by laszlocsomor** [comment]
As of now, `ctx.action` is deprecated: https://docs.bazel.build/versions/master/skylark/lib/ctx.html#action
