### ISSUE TITLE
--credentials_helper fails with exit code 37

### ISSUE THREAD

**Issue by ibolit** [bazelbuild/bazel#19277]
### Description of the bug:

I've been trying to use the --credentials_helper option in my build, but the build fails with exit code 37 and no output. My setup:

Apple Silicon MacBook 

credentials_helper.sh
```
sleep 10

echo "{\"headers\": {\"Authorization\": [\"Bearer my-secret-token\"]}}"
```

The `credentials_helper.sh` file lives at the root of the repo, the PATH env variable is set accordingly: 

`export PATH=.:$PATH`

When I run 
```
$ credentials_helper.sh
```
I do get a 10 second delay, and when I run `credentials_helper.sh | python -m json.tool` I get the formatted json (to check that the json is valid)

My .bazelrc:

```
test --build_tests_only
common --experimental_downloader_config=.bazel_downloader.cfg
build --credential_helper=credentials_helper.sh
```
(the build fails if I change `build` to `common` in the last line, too)

My bazel version: 6.3.2, but I also tried with 6.3.1 and 6.3.1 with the same result.

Here's how I run my build: 

```
 bazel run --subcommands --verbose_failures //an_experimental_lib_for_bazel:version
```

This is all the output I get: 

```
Starting local Bazel server and connecting to it...
```

Exit code:
```
echo $?                                                                           
37
```

### Which category does this issue belong to?

Core

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See description above

### Which operating system are you running Bazel on?

mac os 13.4.1 (Ventura)

### What is the output of `bazel info release`?

release 6.3.2

**Comment by ibolit** [comment]
After posting, I realised, the PATH variable doesn't get passed to Bazel

**Comment by tjgq** [comment]
You can also use `--credential_helper=%workspace%/credentials_helper.sh` to make it workspace-relative (and avoid PATH resolution).

**Comment by tjgq** [comment]
Nevertheless, this is a bug; Bazel should never crash instead of producing a human-readable error message.

I tried to repro this with a trivial java_binary and an empty `.bazel_downloader.cfg`, but instead of a crash, I get an error message saying the credential helper could not be found in the PATH.

What are you trying to build? What are the contents of your `.bazel_downloader.cfg` (feel free to replace any sensitive information with placeholders)?
