### ISSUE TITLE
Bazel coverage returns empty .dat files when running on Remote Execution

### ISSUE THREAD

**Issue by carlosgalvezp** [bazelbuild/bazel#19290]
### Description of the bug:

We are using Bazel for computing code coverage using LLVM-based coverage (.profraw, .profdata files). It works well when running locally, but it does not when running on Remote Execution (the output .dat file is empty).

Comparing the logs, I notice that the following line is never executed in RE:
https://github.com/bazelbuild/bazel/blob/master/tools/test/collect_cc_coverage.sh#L88

When running locally, the line is executed.

We use the following flags for coverage:

```
--experimental_split_coverage_postprocessing
--experimental_fetch_all_coverage_outputs
--remote_download_outputs=all
--instrument_test_targets
--combined_report=lcov
--experimental_generate_llvm_lcov
```

What could we be missing?

Thanks!

### Which category does this issue belong to?

C++/Objective-C Rules

### Which operating system are you running Bazel on?

Ubuntu 20.04

### What is the output of `bazel info release`?

release 6.1.0

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/13193

**Comment by fmeum** [comment]
Could you check whether this reproduces with `last_green`? I recently made a change to that logic.

**Comment by carlosgalvezp** [comment]
Unfortunately it's a bit hard for me to test a new version, will check with the team. Is it part of some recent release?

Another thing I notice is a change in directories:

Without RE:
```
COVERAGE_DIR=bazel-out/k8-fastbuild/testlogs/_coverage/path/to/test
```
With RE:
```
COVERAGE_DIR=bazel-out/k8-fastbuild/testlogs/path/to/test/_coverage
```
I.e the `_coverage` folder is put in different places. Could it be related?

**Comment by carlosgalvezp** [comment]
If I remove these 2 options:
```
--experimental_split_coverage_postprocessing
--experimental_fetch_all_coverage_outputs
```
things seems to work as expected, and the correct line that finds the executable files (https://github.com/bazelbuild/bazel/blob/master/tools/test/collect_cc_coverage.sh#L88) is hit. However it later fails due to this:
```
external/remote_coverage_tools/Main: Cannot locate runfiles directory. (Set $JAVA_RUNFILES to inhibit searching.)
```

**Comment by carlosgalvezp** [comment]
I just tested 6.3.2 which includes https://github.com/bazelbuild/bazel/commit/9d3b375fa6071fc7138d57f30cfcd91a3a2bfa7a and it seems to works perfectly :)
