### ISSUE TITLE
TensorFlow and TensorFlow_serving is broken on CI

### ISSUE THREAD

**Issue by hermione521** [bazelbuild/bazel#1929]
Breakage:
http://ci.bazel.io/job/TensorFlow/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/455/console

Relative commit:
https://github.com/bazelbuild/bazel/commit/e23b79c31ccaba176515e7032553d2816e5832cd

**Comment by meteorcloudy** [comment]
Do we have a fix for this? Or should we rollback it first, people are complaining about they cannot build TF with Bazel at HEAD.

**Comment by hermione521** [comment]
@damienmg Florian wants me to ask you if I can just rollback this change.

**Comment by meteorcloudy** [comment]
Wait, are we sure this is the culprit?

**Comment by hermione521** [comment]
OK, so we are going to update grpc for TensorFlow.
