### ISSUE TITLE
[6.4.0] FATAL: bazel crashed due to an internal error. Printing stack trace: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#19306]
Forked from #19250

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts. Please resolve manually.
cc: @bazelbuild/triage

**Comment by meteorcloudy** [comment]
This is probably not needed, since 6.4.0 branch is using the correct JDK: https://github.com/bazelbuild/bazel/blob/333e83f648795669695821c1c1ce77eb9e7b01c1/src/BUILD#L178
