### ISSUE TITLE
[6.4.0] Add `--incompatible_merge_fixed_and_default_shell_env`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#19312]
Forked from #18235

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts. Please resolve manually.
cc: @bazelbuild/triage

**Comment by fmeum** [comment]
@iancha1992 I submitted https://github.com/bazelbuild/bazel/pull/19319 with a manual cherry-pick.

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19319 by @fmeum
