### ISSUE TITLE
incompatible_merge_fixed_and_default_shell_env

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#19317]
With this flag enabled, when an action is registered with both `use_default_shell_env = True` and a non-empty `env` dict, the values of the `env` dict will override the values inherited from the shell environment. Previously, the `env` dict would be ignored in this case.

Since the default shell environment is user-controlled via `--action_env` and any values set via `env` on actions that also set `use_default_shell_env = True` have been ignored so far, this change should only break rules that have been setting invalid environment variables via `env` that are now becoming effective.

Users experiencing breakages due to this change can temporarily disable it via `--noincompatible_merge_fixed_and_default_shell_env`. Rule authors should verify that their actions with `use_default_shell_env = True` succeed even if the variables specified in `env` are applied and remove variables from that dict if needed.

**Comment by meteorcloudy** [comment]
Nope, an issue title with the flag name + `incompatible-change` and `migration-ready` labels are enough.

**Comment by brentleyjones** [comment]
@fmeum is there a way for rules to check for the flag being enabled, to conditionally do logic? Seems like it would be needed.

cc @keith

**Comment by fmeum** [comment]
I don't think there is. I can see how that would limit the usefulness of the cherry-pick, but I'm not sure how we could make this detectable with general purpose API.
