### ISSUE TITLE
[6.4.0] Retry on javax.net.ssl.SSLException ... BAD_DECRYPT

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#19326]
Forked from #19321

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts. Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19346 by @coeuvre
