### ISSUE TITLE
[Mirror] zig 0.11.0

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel#19344]
### Please list the URLs of the archives you'd like to mirror:

https://ziglang.org/download/0.11.0/zig-windows-x86_64-0.11.0.zip
https://ziglang.org/download/0.11.0/zig-macos-aarch64-0.11.0.tar.xz
https://ziglang.org/download/0.11.0/zig-macos-x86_64-0.11.0.tar.xz
https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz
https://ziglang.org/download/0.11.0/zig-linux-x86-0.11.0.tar.xz

**Comment by Pavank1992** [comment]
Please find the requested mirror artifacts below:

https://mirror.bazel.build/ziglang.org/download/0.11.0/zig-windows-x86_64-0.11.0.zip
https://mirror.bazel.build/ziglang.org/download/0.11.0/zig-macos-aarch64-0.11.0.tar.xz
https://mirror.bazel.build/ziglang.org/download/0.11.0/zig-macos-x86_64-0.11.0.tar.xz
https://mirror.bazel.build/ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz
https://mirror.bazel.build/ziglang.org/download/0.11.0/zig-linux-x86-0.11.0.tar.xz
