### ISSUE TITLE
Small incremental build are freakingly slow on OS X because stable build info

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1934]
Even though we do not have stamping activated, the build takes ~6-8 seconds for building a java_test where I just change an unused imports.

This is highly unexpected, especially with workers.

/cc @ulfjack @philwo 
$ bazel analyze-profile /tmp/profile\*  | grep Building
WARNING: This information is intended for consumption by Blaze developers only, and may change at any time.  Script against it at your own risk
INFO: Loading /tmp/profile
INFO: bazel profile for /private/var/tmp/_bazel_dmarting/fd98b88c9ddd01e9b99b057d5d085004 at Wed Oct 12 15:18:42 CEST 2016, build ID: 517bdcc1-c555-4cb0-ac46-3182d501f14b, 460 record(s)
INFO: Aggregating task statistics
   460    10.347 s   99.99%   Building src/test/java/com/google/devtools/build/lib/skyframe/SkyframeTests.jar (40 source files)
INFO: Loading /tmp/profile2
INFO: bazel profile for /private/var/tmp/_bazel_dmarting/fd98b88c9ddd01e9b99b057d5d085004 at Wed Oct 12 15:19:10 CEST 2016, build ID: 248a88a7-fd7e-47d8-be5b-da6f2ab989c3, 445 record(s)
INFO: Aggregating task statistics
   444     6.956 s   99.97%   Building src/test/java/com/google/devtools/build/lib/skyframe/SkyframeTests.jar (40 source files)
INFO: Loading /tmp/profile3
INFO: bazel profile for /private/var/tmp/_bazel_dmarting/fd98b88c9ddd01e9b99b057d5d085004 at Wed Oct 12 15:19:36 CEST 2016, build ID: e6b5a377-9bfc-4605-8273-ac0b4e677ec2, 306 record(s)
INFO: Aggregating task statistics
   306     6.411 s   99.98%   Building src/test/java/com/google/devtools/build/lib/skyframe/SkyframeTests.jar (40 source files)

**Comment by damienmg** [comment]
We see ~6s spent on building the action

**Comment by damienmg** [comment]
Also /cc @cushon @eaftan because that's a problem specifically in the java compile action (without worker the action takes 10s). Is the Java compiler just freaking slow on Darwin?

**Comment by meisterT** [comment]
I don't think this is an issue of Bazel, the tool. It's just a big compile action with 40 source files (or 73 nowadays).
