### ISSUE TITLE
Support internal jars in android support libs

### ISSUE THREAD

**Issue by zvh** [bazelbuild/bazel#1935]
The generated rules don't currently pull in the internal jars from the AAR libs/ directory which can cause compilation to fail due to missing classes. More context here:

https://github.com/bazelbuild/bazel/issues/1745#issuecomment-253282584

**Comment by zvh** [comment]
Please assign to @aj-michael

**Comment by aj-michael** [comment]
Thanks for filing this!

**Comment by aj-michael** [comment]
This was fixed in 97cc5be8787145bd0402406b67b2a28df5348788
