### ISSUE TITLE
create_cc_toolchain_config_info API is underdocumented

### ISSUE THREAD

**Issue by tpudlik** [bazelbuild/bazel#19353]
### Page link:

https://bazel.build/rules/lib/toplevel/cc_common#create_cc_toolchain_config_info

### Problem description (include actual vs expected text, if applicable):

The C++ toolchain configuration API exposes a number of string parameters (`toolchain_identifier`, `target_system_name`, `target_cpu`, `target_libc`, etc). These parameters are underdocumented. Specifically:

1. They have undocumented magic values. For example, if the `target_libc` string takes the magic value `macosx`, then the legacy features of the C++ toolchain [will assume](https://github.com/bazelbuild/bazel/blob/release-7.0.0-pre.20230816.3rc1/src/main/java/com/google/devtools/build/lib/rules/cpp/CcModule.java#L1301-L1304) the toolchain is running on MacOS.  This can only be discovered by diving into the Bazel source. The documentation doesn't even mention that there _are_ magic values, let alone what they might be.
2. These parameters are actually programmatically accessible, and some libraries make use of them, effectively treating them as enums. For example, the current compiler toolchain's `compiler` attribute is exposed as `@bazel_tools//tools/cpp:compiler`, and Abseil [uses it](https://github.com/abseil/abseil-cpp/blob/master/absl/BUILD.bazel#L23-L37) to select flags appropriate for clang vs gcc. AFAIK both that the parameters can be accessed, and the values they should conventionally take, is undocumented.

### Where do you see this issue? (include link to specific section of the page, if applicable)

https://bazel.build/rules/lib/toplevel/cc_common#create_cc_toolchain_config_info

**Comment by amansehgal0u2** [comment]
I was particularly stumped by `@bazel_tools//tools/cpp:compiler` and how setting the `compiler` attribute sets this flag which can be used to create config settings that are quite useful. Would really appreciate any such magic be documented.

**Comment by tpudlik** [comment]
Another aspect of the API that's underdocumented: it's not clear how to get a custom C++ toolchain to work with `bazel coverage`. I think maybe you need to define a `coverage` feature? But there's not even a hint about this, either on https://bazel.build/configure/coverage (the "Language-specific configuration" section doesn't mention C++) or on https://bazel.build/docs/cc-toolchain-config-reference.

**Comment by daivinhtran** [comment]
@tpudlik I created https://github.com/bazelbuild/bazel/issues/21911 to triage the documentation update for `bazel coverage` in c++ toolchain. Closing this issue now.
