### ISSUE TITLE
Adb installation is successful, but bazel shows an error

### ISSUE THREAD

**Issue by dvpermyakov** [bazelbuild/bazel#19362]
### Description of the bug:

Hello!
Sometimes when I do [mobile-install](https://bazel.build/docs/mobile-install) of my android application I see that incremental install fails, but streamed install succeeds. Despite the fact that my application is installed on device I see that bazel build is failed. As I see in [incremental_install.py](https://github.com/bazelbuild/bazel/blob/master/tools/android/incremental_install.py#L281) when adb returns code `0` and `failed` string is present in stdout then adb error is raised. My question is: can we prevent bazel to raise an error in the case when incremental installed fails and streamed install succeeds?
Here is log information from bazel output:
```
[incremental_install.py:445] Updating 3 dexes...
[incremental_install.py:506] Application resources up-to-date
[incremental_install.py:604] Updating 0 native libs...
Error:
adb command: ['external/androidsdk/platform-tools/adb', 'install', '-r', './bazel-out/darwin_arm64-fastbuild/*/*/*/app_incremental.apk']
return code: 0
stdout: Serving...
Performing Incremental Install
Failure [INSTALL_PARSE_FAILED_NOT_APK: Failed to parse /data/app/vmdl12345.tmp/app_incremental.apk: Failed to load asset path /data/app/vmdl12345.tmp/app_incremental.apk]
Performing Streamed Install
Success
stderr: All files should be loaded. Notifying the device.
Target //src/main/java/com/*/*/app:app failed to build
FAILED: Build did NOT complete successfully
```
Here is code that we can change `def Install(self, apk)` in [incremental_install.py](https://github.com/bazelbuild/bazel/blob/master/tools/android/incremental_install.py#L269):
```python
def Install(self, apk):
    """Invoke 'adb install'."""
    ret, stdout, stderr, args = self._Exec(["install", "-r", apk])
    
    # adb failed to install incrementally, but fallback streamed installation was successful
    pattern = "Performing Incremental Install\nFailure.*?\nPerforming Streamed Install\nSuccess"
    successful_fallback_installation = ret == 0 and re.search(pattern, stdout)

    # adb install could fail with a message on stdout like this:
    #
    #   pkg: /data/local/tmp/Gmail_dev_sharded_incremental.apk
    #   Failure [INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES]
    #
    # and yet it will still have a return code of 0. At least for the install
    # command, it will print "Success" if it succeeded, so check for that in
    # standard out instead of relying on the return code.
    if not successful_fallback_installation and ("FAILED" in stdout or "FAILED" in stderr):
      raise AdbError(args, ret, stdout, stderr)
```

### Which category does this issue belong to?

Android

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run `mobile-install` after some changes in android code base. It may not easy to reproduce.

### Which operating system are you running Bazel on?

MacOS 13.5

### What is the output of `bazel info release`?

release 6.3.1-bea46c3

**Comment by ahumesky** [comment]
The native version of mobile-install has been removed and the Starlark version in https://github.com/bazelbuild/rules_android/ does not rely on incremental_install.py or adb. If this is still and issue there, please feel free to open a new issue
