### ISSUE TITLE
Empty depsets should be optimized out of structs the same as they are optimized out of providers

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/bazel#19380]
### Description of the feature request:

Empty depsets are optimized out of providers, but not structs. This can lead to increased memory usage for some code patterns.

### Which category does this issue belong to?

Starlark Integration, Starlark Interpreter

### What underlying problem are you trying to solve with this feature?

In rules_xcodeproj we marshal a lot of data collected in aspects down the dependency tree. When doing Starlark memory profiling we noticed that creating new empty `depset` instances would drastically increase our memory usage. So instead we create frozen instances of empty values and use them when possible: https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/31a9e114dac0e20625fb7d9119fe5a117ecb3608/xcodeproj/internal/memory_efficiency.bzl, which helped us reduce our memory usage.

### Which operating system are you running Bazel on?

macOS 13.4.1 (c)

### What is the output of `bazel info release`?

release 6.3.2

### Any other information, logs, or outputs that you want to share?

https://bazelbuild.slack.com/archives/CA31HN1T3/p1693484609534579 where @fmeum requested I open this issue.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 6.4.0 RC1](https://releases.bazel.build/6.4.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!
