### ISSUE TITLE
"killall bazel" doesn't work

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#1939]
Current behavior:
When a user tries to run "killall bazel", it doesn't work, because killall can't find any running processes with that name.

Expected behavior:
"killall bazel" actually kills all running Bazel servers.

**Comment by aiuto** [comment]
Is there any possible way to make this work? I think not.
Closed: infeasible

**Comment by philwo** [comment]
I think it would be possible by setting the process name of Bazel's server via `prctl(PR_SET_NAME, "bazel")`, at least on Linux.

On FreeBSD and macOS, there seem to be similar mechanisms like `pthread_setname_np`. (Also, see https://stackoverflow.com/questions/4217947/setting-process-name-on-mac-os-x-at-runtime)

**Comment by meisterT** [comment]
In the meantime, you can use `pkill ^bazel` to kill all bazel processes on your machine.

**Comment by aehlig** [comment]
> I think it would be possible by setting the process name of Bazel's server via `prctl(PR_SET_NAME, "bazel")`, at least on Linux.

Or even simpler: since the `bazel` client starts the server, the call to `execv(3)` is actually under our control and we can set `argv[0]` to any name of our liking, right from the beginning.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
