### ISSUE TITLE
[Mirror] uber/hermetic_cc_toolchain v2.1.0

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel#19398]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/uber/hermetic_cc_toolchain/releases/download/v2.1.0/hermetic_cc_toolchain-v2.1.0.tar.gz

**Comment by Pavank1992** [comment]
Please find the mirror artifacts below:
https://mirror.bazel.build/github.com/uber/hermetic_cc_toolchain/releases/download/v2.1.0/hermetic_cc_toolchain-v2.1.0.tar.gz
