### ISSUE TITLE
Problem with Bazel while trying to build MediaPipe on Jetson Nano

### ISSUE THREAD

**Issue by VieiraJardel** [bazelbuild/bazel#19392]
Hi, I'm trying to build MediaPipe on Jetson Nano. I'm following these instructions, but I can't find the path with the folder 'external/com_github_glog_glog/' to remove two files (config.guess and config.sub).

I'm following this tutorial from [AndreV84](https://github.com/AndreV84): https://github.com/AndreV84/mediapipe/blob/master/README.md

When I try to use this step:
cd ~ && git clone https://github.com/google/mediapipe/
cd mediapipe
bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11  mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu
it will fail but will provide path that will need to be patched; In my case it is
/home/nvidia/.cache/bazel/_bazel_nvidia/ff4425722229fc486cc849b5677abe3f/external/com_github_glog_glog/

I received this message
jv@jv-desktop:~/mediapipe$ bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: ignoring LD_PRELOAD in environment.
ERROR: /home/jv/.cache/bazel/_bazel_jv/e1c4a6250c6ceb5a498b3a5ff767dd81/external/build_bazel_apple_support/crosstool/setup.bzl:69:32: name 'module_extension' is not defined
INFO: Repository rules_proto instantiated at:
  /home/jv/mediapipe/WORKSPACE:111:25: in <toplevel>
  /home/jv/.cache/bazel/_bazel_jv/e1c4a6250c6ceb5a498b3a5ff767dd81/external/build_bazel_rules_swift/swift/repositories.bzl:65:15: in swift_rules_dependencies
  /home/jv/.cache/bazel/_bazel_jv/e1c4a6250c6ceb5a498b3a5ff767dd81/external/build_bazel_rules_swift/swift/repositories.bzl:32:18: in _maybe
Repository rule http_archive defined at:
  /home/jv/.cache/bazel/_bazel_jv/e1c4a6250c6ceb5a498b3a5ff767dd81/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: error loading package '': in /home/jv/.cache/bazel/_bazel_jv/e1c4a6250c6ceb5a498b3a5ff767dd81/external/build_bazel_rules_swift/swift/extras.bzl: in /home/jv/.cache/bazel/_bazel_jv/e1c4a6250c6ceb5a498b3a5ff767dd81/external/build_bazel_apple_support/lib/repositories.bzl: Extension 'crosstool/setup.bzl' has errors
INFO: Elapsed time: 20,430s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
jv@jv-desktop:~/mediapipe$ 

I searched for some information on this topic:
https://github.com/google/mediapipe/issues/1733

**Comment by Pavank1992** [comment]
Hi @VieiraJardel, Could you please provide the OS and version of the Bazel that you were using? (What is the output of `bazel info release`?)

**Comment by VieiraJardel** [comment]
Hi @Pavank1992 !
After reading issues about MediaPipe in @AndreV84's repository, I noticed that "with more recent versions of the mediapipe/bazel, the specified patching step can be disregarded; just proceed to the next steps."

I'm using JetPack 4.6,
Bazel 4.2.1, 
and a Jetson Nano 4GB. 

However, I'm encountering a problem when I try to use this command: 
bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu

Result:
jv@jv-desktop:~/mediapipe$ bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: ignoring LD_PRELOAD in environment.
ERROR: /home/jv/.cache/bazel/_bazel_jv/e1c4a6250c6ceb5a498b3a5ff767dd81/external/build_bazel_apple_support/crosstool/setup.bzl:69:32: name 'module_extension' is not defined
ERROR: error loading package '': in /home/jv/.cache/bazel/_bazel_jv/e1c4a6250c6ceb5a498b3a5ff767dd81/external/build_bazel_rules_swift/swift/extras.bzl: in /home/jv/.cache/bazel/_bazel_jv/e1c4a6250c6ceb5a498b3a5ff767dd81/external/build_bazel_apple_support/lib/repositories.bzl: Extension 'crosstool/setup.bzl' has errors
INFO: Elapsed time: 29,234s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

Can you help-me?

**Comment by VieiraJardel** [comment]
Maybe the problem can be solved by updating Bazel to the latest version, but I might encounter compatibility issues with MediaPipe.

**Comment by Pavank1992** [comment]
@VieiraJardel,

It appears there is an issue related to the **Bazel version,** as documented in the [.bazelversion](https://github.com/google/mediapipe/blob/master/.bazelversion) file for MediaPipe. The officially supported **Bazel version** for MediaPipe is **6.1.1**. 

Furthermore, it is noteworthy that MediaPipe exclusively supports **Raspberry PI 64 Bit**, while it does not extend support to **Nvidia Jetson Nano**, as mentioned in the guide [here](https://developers.google.com/mediapipe/solutions/setup_python#supported_platforms_and_versions). Consequently, this limitation impedes the ability to build MediaPipe on the **Nvidia Jetson Nano Kit**. I recommend that you refer to the MediaPipe [thread](https://github.com/google/mediapipe/issues/4669) for additional insights and information.

Nevertheless, we kindly request that you consider submitting a feature request for the inclusion of support for the Jetson Kit with the MediaPipe team [here](https://github.com/google/mediapipe/issues/new/choose). Additionally, we recommend following up on this matter to explore potential workarounds or seek support for this specific edge device. We also advise initiating communication with the MediaPipe team for further guidance and collaboration on this matter.
