### ISSUE TITLE
github  download error

### ISSUE THREAD

**Issue by a7853z** [bazelbuild/bazel#19418]
### Description of the bug:

- when building secretflow from source, cann't download files from github.com using bazel to build.  But can telnet or wget wihout bazel.

- It shows **"connect time out"** or **"No subject alternative DNS name matching github.com found."**  error.

 

- Here is the log:

WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
INFO: Repository rules_foreign_cc instantiated at:
  /home/randy/local-gitlab/secretflow/secretflow/WORKSPACE:13:10: in <toplevel>
  /home/randy/.cache/bazel/_bazel_randy/083d6ac12f533e3f374ece45cc7df093/external/yacl/bazel/repositories.bzl:27:22: in yacl_deps
  /home/randy/.cache/bazel/_bazel_randy/083d6ac12f533e3f374ece45cc7df093/external/yacl/bazel/repositories.bzl:234:10: in _rules_foreign_cc
  /home/randy/.cache/bazel/_bazel_randy/083d6ac12f533e3f374ece45cc7df093/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /home/randy/.cache/bazel/_bazel_randy/083d6ac12f533e3f374ece45cc7df093/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
WARNING: Download from https://github.com/bazelbuild/rules_foreign_cc/archive/refs/tags/0.9.0.tar.gz failed: class java.io.IOException connect timed out
ERROR: An error occurred during the fetch of repository 'rules_foreign_cc':
   Traceback (most recent call last):
	File "/home/randy/.cache/bazel/_bazel_randy/083d6ac12f533e3f374ece45cc7df093/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_foreign_cc/archive/refs/tags/0.9.0.tar.gz] to /home/randy/.cache/bazel/_bazel_randy/083d6ac12f533e3f374ece45cc7df093/external/rules_foreign_cc/temp11010944972494380567/0.9.0.tar.gz: connect timed out
ERROR: /home/randy/local-gitlab/secretflow/secretflow/WORKSPACE:13:10: fetching http_archive rule //external:rules_foreign_cc: Traceback (most recent call last):
	File "/home/randy/.cache/bazel/_bazel_randy/083d6ac12f533e3f374ece45cc7df093/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_foreign_cc/archive/refs/tags/0.9.0.tar.gz] to /home/randy/.cache/bazel/_bazel_randy/083d6ac12f533e3f374ece45cc7df093/external/rules_foreign_cc/temp11010944972494380567/0.9.0.tar.gz: connect timed out
ERROR: no such package '@rules_foreign_cc//foreign_cc': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_foreign_cc/archive/refs/tags/0.9.0.tar.gz] to /home/randy/.cache/bazel/_bazel_randy/083d6ac12f533e3f374ece45cc7df093/external/rules_foreign_cc/temp11010944972494380567/0.9.0.tar.gz: connect timed out
INFO: Elapsed time: 36.182s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
error: command '/usr/local/bin/bazel' failed with exit code 1
(secretflow) [randy@federated-develop secretflow]$ ./proxychains4 -f /usr/local/etc/proxychains.conf telnet github.com 80
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.16-git-15-g0c79508
Trying 224.0.0.1...
[proxychains] Strict chain  ...  127.0.0.1:9060  ...  github.com:80  ...  OK

### Which category does this issue belong to?

External Dependency

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

build secretflow from source 

### Which operating system are you running Bazel on?

Centos 7

### What is the output of `bazel info release`?

WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE. release 5.4.1

### Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

(secretflow) [randy@federated-develop secretflow]$ echo $JAVA_HOME
/usr/lib/jvm/jre-openjdk
(secretflow) [randy@federated-develop secretflow]$ ls /usr/lib/jvm/jre-openjdk
ASSEMBLY_EXCEPTION  bin  lib  LICENSE  THIRD_PARTY_README

**Comment by Pavank1992** [comment]
@a7853z, Could you please provide sample code with minimal steps to reproduce this issue?

**Comment by a7853z** [comment]
> @a7853z, Could you please provide sample code with minimal steps to reproduce this issue?

- I am using following instructions to install secretflow: [https://github.com/secretflow/secretflow/blob/main/docs/getting_started/installation.md#option-3-from-source](url)

- In the above document, running

> python setup.py bdist_wheel

will run bazel: 

> bazel build //secretflow_lib/binding:_lib.so --symlink_prefix=build/temp.linux-x86_64-cpython-38/bazel- --compilation_mode=opt

 and it will download dependencies from github.

- My server can't connect to github, so I use proxychains [https://github.com/rofl0r/proxychains-ng](url) to setup a proxy, this proxy can telnet and wget github directly, No problem. 

- But if I use this proxy to run setup.py which will run bazel, errors occured:
> ./proxychains4 -f /usr/local/etc/proxychains.conf python setup.py bdist_wheel

errors like:

1. "ERROR: no such package '@rules_foreign_cc//foreign_cc': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_foreign_cc/archive/refs/tags/0.9.0.tar.gz] to /home/randy/.cache/bazel/_bazel_randy/083d6ac12f533e3f374ece45cc7df093/external/rules_foreign_cc/temp6777806408797802941/0.9.0.tar.gz: connect timed out"
2. "ERROR: no such package '@rules_foreign_cc//foreign_cc': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_foreign_cc/archive/refs/tags/0.9.0.tar.gz] to /home/randy/.cache/bazel/_bazel_randy/083d6ac12f533e3f374ece45cc7df093/external/rules_foreign_cc/temp8184421799046572597/0.9.0.tar.gz: No subject alternative DNS name matching github.com found."

**Comment by a7853z** [comment]
[https://github.com/rofl0r/proxychains-ng/issues/518#issuecomment-1708210094](url)       the author of proxychains indicates that bazel is written in java and it does not work well with proxychains

**Comment by Pavank1992** [comment]
Hi @a7853z, the shared link is broken, could you please share correct link please?

**Comment by a7853z** [comment]
> Hi @a7853z, the shared link is broken, could you please share correct link please?

https://github.com/rofl0r/proxychains-ng/issues/518

I setted up a new http proxy, problem is solved. Proxychains is a socks5 proxy.
