### ISSUE TITLE
[bzlmod]: add API for modules to discover their own version

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#19413]
### Description of the feature request:

The version of a ruleset appears in the `module()` declaration that Bazel reads, but the ruleset itself cannot read at runtime

This can be a problem in cases where you want to compare your own version against something, or use your own version in an error message you print to the user.
Ideally the bzlmod API could have a way for module code to "introspect" the version that was stamped into MODULE.bazel.
Note, @fmeum has already started some work on such an API.

Note: it's not okay to require a separate `version.bzl` file because rulesets should be able to use a very simple release automation that doesn't require commits or fancy rewrites on publish.

**Comment by fmeum** [comment]
This is the skylib PR which provides an extension that allows modules to learn the versions of other participating modules: https://github.com/bazelbuild/bazel-skylib/pull/421.

Please take a look and let me know whether this would satisfy your use case.

**Comment by alexeagle** [comment]
Oh, I think this issue is a dupe of  https://github.com/bazelbuild/bazel/issues/17114 then
