### ISSUE TITLE
On Windows: NullPointerException on fetching jars from repository defined with maven_server

### ISSUE THREAD

**Issue by Helcaraxan** [bazelbuild/bazel#1941]
Bazel manages to fetch all external jar dependencies defined with `maven_jar` from the standard repositories. However every single jar that uses a repository defined with `maven_server` results in a `NullPointerException` on transfer.

```
ERROR: C:/Projects/everything/third_party/flagz/BUILD:5:1: no such package '@flagz_core_artifact//jar': Failed to fetch Maven dependency: Could not transfer artifact org.flagz:flagz:jar:2.2.0 from/to flagz_core_artifact (https://<obfuscated-host>/content/repositories/releases/): NullPointerException and referenced by '//third_party/flagz:flagz'.
ERROR: C:/Projects/everything/third_party/flagz/BUILD:15:1: no such package '@flagz_core_artifact//jar': Failed to fetch Maven dependency: Could not transfer artifact org.flagz:flagz:jar:2.2.0 from/to flagz_core_artifact (https://<obfuscated-host>/content/repositories/releases/): NullPointerException and referenced by '//third_party/flagz:flagz_scala'.
ERROR: C:/Projects/everything/third_party/flagz/BUILD:15:1: no such package '@flagz_scala_artifact//jar': Failed to fetch Maven dependency: Could not transfer artifact org.flagz:flagz-scala_2.11:jar:2.2.0 from/to flagz_scala_artifact (https://<obfuscated-host>/content/repositories/releases/): NullPointerException and referenced by '//third_party/flagz:flagz_scala'.
[...]
```

**Comment by petemounce** [comment]
It's worth mentioning that our maven_server here has authentication enabled, which is present in `~/.m2/settings.xml`.

**Comment by dslomov** [comment]
@kchodorow could you help? What is the best way to debug this?

**Comment by petemounce** [comment]
This currently blocks me. Is there anything I can do to help diagnose, etc? Any workarounds?

**Comment by petemounce** [comment]
Might be able to work around this via #1960's workaround. I'll try it out.

**Comment by petemounce** [comment]
Wasn't able to work around.

@dinowernli provoked a great thought - on Windows, a user's home directory is `USERPROFILE`, not `HOME`. By default, Windows doesn't have the `HOME` environment variable (or understand `~/` come to that). Could that be the problem here...?

**Comment by petemounce** [comment]
@dslomov any update on this one?

**Comment by kchodorow** [comment]
One possible workaround is to use the new Skylark maven_jar rule, instead of the built-in one.  This rule doesn't take server= or repository= attributes, but it picks up on your system settings.xml file. You can try it out by specifying:

```
load('@bazel_tools//tools/build_defs/repo:maven_rules.bzl', 'maven_jar')
# Or continue to use some native, some skylark maven rules by giving the skylark version an alternative name:
load('@bazel_tools//tools/build_defs/repo:maven_rules.bzl', skylark_maven_jar = 'maven_jar')
```

@dslomov the error message is coming from https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/repository/MavenDownloader.java#L125.  Basically, Aether is throwing an NPE trying to resolve the artifact, and we're wrapping it.  I probably set something up wrong about how it resolves custom repositories+auth, but I don't know what it is.

**Comment by damienmg** [comment]
Friendly ping?

**Comment by Helcaraxan** [comment]
We have not been able to make much progress / tests here due to other things but we will be coming back to this soon. Will update as soon as I have more information.

**Comment by petemounce** [comment]
I have in my workspace:
```
git_repository(
  name = "io_bazel",
  remote = "https://github.com/bazelbuild/bazel.git",
  tag = "0.4.1",
)
load('@io_bazel//tools/build_defs/repo:maven_rules.bzl', skylark_maven_jar = 'maven_jar')
```

I have bazel 0.4.2-rc2 installed.

Initially, in msys2 shell, I got (targets obfuscated)
```
ERROR: C:/src/s/iw/everything/third_party/some_dep/BUILD:5:1: no such package '@some_dep_artifact//jar': Traceback (most recent call last):
        File "C:/tools/msys64/tmp/_bazel_Pete/fIsNmaZv/external/io_bazel/tools/build_defs/repo/maven_rules.bzl", line 252
                _check_dependencies(ctx)
        File "C:/tools/msys64/tmp/_bazel_Pete/fIsNmaZv/external/io_bazel/tools/build_defs/repo/maven_rules.bzl", line 50, in _check_dependencies
                fail("maven_jar requires %s as a depe...)
maven_jar requires mvn as a dependency. Please check your PATH. and referenced by '//third_party/some_dep:target'.
```

I installed maven via chocolatey and did `export PATH=$PATH:/c/tools/apache-maven-3.3.9/bin`.

Then, I get 
```
ERROR: C:/src/s/iw/everything/blah/BUILD:3:1: no such package '@some_dep_artifact//jar': Traceback (most recent call last):
        File "C:/tools/msys64/tmp/_bazel_Pete/fIsNmaZv/external/io_bazel/tools/build_defs/repo/maven_rules.bzl", line 252
                _check_dependencies(ctx)
        File "C:/tools/msys64/tmp/_bazel_Pete/fIsNmaZv/external/io_bazel/tools/build_defs/repo/maven_rules.bzl", line 50, in _check_dependencies
                fail("maven_jar requires %s as a depe...)
maven_jar requires openssl as a dependency. Please check your PATH. and referenced by '//blah'.
```

However - I appear to have _an_ openssl in my PATH - I believe from msys2's install, `/usr/bin/openssl.exe`:
```
MSYS /c/src/s/iw/everything
$ openssl version
OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by Helcaraxan** [comment]
Any news on this issue with the latest information provided by @petemounce?

**Comment by petemounce** [comment]
Friendly ping?

**Comment by damienmg** [comment]
pinging @dslomov and @kchodorow

**Comment by petemounce** [comment]
Friendly follow-up ping?

**Comment by meteorcloudy** [comment]
@dslomov Ping.

**Comment by dslomov** [comment]
Sorry, just go to this issue. I bet your openssl is in msys's PATH but not in Windows' PATH variable.

@kchodorow, what would be the easiest way to reproduce this?

**Comment by petemounce** [comment]
```
C:\Users\Pete>where openssl
C:\Program Files\OpenVPN\bin\openssl.exe
C:\Program Files\Git\mingw64\bin\openssl.exe
C:\Program Files\Git\usr\bin\openssl.exe
c:\tools\msys64\usr\bin\openssl.exe
```

**Comment by petemounce** [comment]
@dslomov @meteorcloudy @damienmg is there anything else I can provide to help?

**Comment by kchodorow** [comment]
Sorry about the delay, this got lost in my inbox!

The maven_jar skylark rule is failing at `ctx.which('openssl')`.  I'm not sure what implementation of `which` Skylark is using on Windows, but I'm guessing that if it can't find openssl, it's wrong.

**Comment by petemounce** [comment]
Ah. Which does not exist on Windows out of the box. `cmd` gives you `where`, PowerShell gives you `Get-Command`.

**Comment by damienmg** [comment]
According @meteorcloudy, `repository_ctx.which` is implemented the same way on windows that we do on Linux: we iterate over the PATH to find the environment variable.

Could that be a problem with casing of the environment?

**Comment by laszlocsomor** [comment]
About envvars: on Windows the Bazel client will [uppercase a few envvars](https://github.com/bazelbuild/bazel/blob/05e5b86e79c656da70cb049deb1b42447b153e8f/src/main/cpp/option_processor.cc#L464-L465), the rest of them are passed to the server as-is. Even if `$PATH` is defined as `Path`, as it is on Windows, we will pass it on as `PATH`.

**Comment by laszlocsomor** [comment]
This error could be related to https://stackoverflow.com/questions/42341374.

**Comment by jin** [comment]
maven_server has been removed from Bazel.
