### ISSUE TITLE
Documentation issue: Platforms

### ISSUE THREAD

**Issue by kaycebasques** [bazelbuild/bazel#19416]
Documentation URL: https://bazel.build/extending/platforms

The `constraint setting` anchor points to `https://bazel.build/reference/be/platform#constraint_setting` which seems to be a 404

**Comment by iancha1992** [comment]
@kaycebasques can you please create any documentation-related issue here?: https://github.com/bazelbuild/bazel/issues/new?assignees=pavank1992%2Csgowroji%2Ciancha1992&labels=type%3A+documentation+%28cleanup%29%2Cuntriaged%2Cteam-Documentation&projects=&template=doc_issue.yml

**Comment by keertk** [comment]
Thanks for reporting this issue! It's been fixed here https://github.com/bazelbuild/bazel/commit/f1c2e44182dd58717a5138641cfb450c48810b83. 
`constraint setting` now points to https://bazel.build/reference/be/platforms-and-toolchains#constraint_setting
