### ISSUE TITLE
Non-annotated classes bundled inside generated class jar

### ISSUE THREAD

**Issue by xuansontrinh** [bazelbuild/bazel#19410]
I have an annotation processor that targets a specific annotation `A`, I register this processor using `java_plugin` rule and build the target using `kt_jvm_library`.

**_What I expect_**: The generated class jar file should contain only classes annotated with `A`.
**_What I get_**: There are a lot of non-annotated classes bundled inside my generated class jar.

I attempted to convert one of the affected classes to Kotlin code, and the class disappeared from the bundle when rebuilding.
Is this the expected behaviour with Java annotation processing? And if possible, how can I unbundle the affected classes?

**Comment by comius** [comment]
cc @hvadehra @cushon

**Comment by hvadehra** [comment]
@xuansontrinh Could you please provide a minimal repro?

**Comment by xuansontrinh** [comment]
@hvadehra Sure.
Here is an example that I created to reproduce the problem:
[test-generated.zip](https://github.com/bazelbuild/bazel/files/12598538/test-generated.zip)
after building this project, you can try creating an aspect to retrieve info from `KtJvmInfo` provider of target `base`. The `provider.annotation_processing.class_jar` will point to `bazel-bin/base/base-java.jar`, which contains all 3 classes: `A`, `B`, and `AGenerated`.
In this example, `B` is not an annotated class.
Thank you for your time looking into this.

**Comment by hvadehra** [comment]
Extracting that zip just gives me an empty directory.

**Comment by xuansontrinh** [comment]
Sorry for that,
I will send you the corrected one tomorrow.

**Comment by hvadehra** [comment]
No, I had a look at the `rules_kotlin` code and I see what you mean. 

For what you're looking for, https://github.com/bazelbuild/rules_kotlin/blob/8d79e6a520df5a43c195bf92a31e7539fbb2faae/kotlin/internal/jvm/compile.bzl#L814
should be `jars.generated_class_jar` instead of `jars.class_jar`. But this is for the `@rules_kotlin` folks.

**Comment by hvadehra** [comment]
I can't seem to transfer this issue to https://github.com/bazelbuild/rules_kotlin, so I suggest you re-open this issue there.

**Comment by xuansontrinh** [comment]
Thank you for looking into it,
Yes, I digged into the code of `rules_kotlin` this afternoon and I also found out about that suspicious point, among other things.
I will create an issue there and maybe draft a suggested solution there.
Thank you once again.
