### ISSUE TITLE
No writable permission for /tmp if /tmp is symbolic link

### ISSUE THREAD

**Issue by harveydevloper** [bazelbuild/bazel#19438]
### Description of the bug:

Hi,

In some cases there is no enough space for /tmp to build big project, usually we will set /tmp as a symbolic link to local path (ex, /tmp -> /home/xxx/tmp)

For bazel build we will have no writable permission for /tmp 
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
clang-17: error: unable to make temporary file: Read-only file system

From the sandbox_debug log we can see the canonical path is remounted as read only.
src/main/tools/linux-sandbox-pid1.cc:311: writable: /tmp
src/main/tools/linux-sandbox-pid1.cc:405: remount ro: /home/xxx/tmp

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxedSpawnRunner.java
430 writableDirs.add(fs.getPath("/tmp"));
So it could be a bug for linux sandbox spaw runner. it can be changed as below
430 writableDirs.add(fs.getPath("/tmp").resolveSymbolicLinks());

Thanks

### Which category does this issue belong to?

Java Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

set /tmp as a symbolic link and build kernel modules with bazel which need to write files into /tmp directory

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

bazel 7.0.0  all pre release

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

bazel 7.0.0  all preversion dist

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

no

**Comment by harveydevloper** [comment]
how can i submit the changes?

**Comment by fmeum** [comment]
> how can i submit the changes?

If it's really just this line, you could use GitHub's web interface to edit the file and create a PR from that.
