### ISSUE TITLE
On Windows: Linking against standard libraries

### ISSUE THREAD

**Issue by Helcaraxan** [bazelbuild/bazel#1945]
For C++, `linkopts` allows one to specify [linker options](https://www.bazel.io/versions/master/docs/be/c-cpp.html#cc_binary.linkopts). However, it also states that:
> Each element of this list that does not start with `$` or `-` is assumed to be the label of a target in `deps`. The list of files generated by that target is appended to the linker options. An error is reported if the label is invalid, or is not declared in `deps`.

As far as I can see, this means that I cannot specify plain arguments to the linker, e.g. `User32.lib`, as required for some [system libraries](http://stackoverflow.com/a/21928624/974531).

I got it to link to the system library by copying it locally, specifying it as a `srcs` in a `cc_library`, and referring to the library's label in both `deps` and `linkopts`. However, copying a system library seems like a bad idea. The C++ system header files are already picked up automatically by Bazel, so maybe these libraries should be, too. I noticed that CMake automatically links against some libraries on Windows, i.e. it links against `user32.lib advapi32.lib gdi32.lib` when compiling openssl on Windows without explicitly specifying these anywhere.

**Comment by hermione521** [comment]
@meteorcloudy

**Comment by laszlocsomor** [comment]
You can use `linkopts = ["-Wl,user32.lib", "-Wl,advapi32.lib"]`.

```
$ cat foo/BUILD
cc_binary(
    name = 'foo',
    srcs = ['foo.cc'],
    linkopts = ['-Wl,user32.lib'],
)

$ cat foo/foo.cc
#include <Windows.h>

int main(int, char**) {
  MessageBoxA(0, "text", "caption", 0);
  return 0;
}

$ bazel run --cpu=x64_windows_msvc //foo
...
INFO: Running command line: C:/tools/msys64/var/tmp/Bazel/MGAgSgPx/execroot/bazel2/bazel-out/vc_14_0_x64-fastbuild/bin/foo/foo.exe

```

See the command line translation here: https://github.com/bazelbuild/bazel/blob/088bbc614c184822050dfa5768d8c1281458c275/tools/cpp/wrapper/bin/pydir/msvc_link.py#L40

**Comment by Helcaraxan** [comment]
Thanks for the solution!

**Comment by grandseiken** [comment]
Thanks laszlo! You walked out that elevator like a boss!

**Comment by laszlocsomor** [comment]
@grandseiken : hey Stuart, small world :)
