### ISSUE TITLE
//src/test/java/com/google/devtools/build/android/ideinfo:JarFilterTest failed on Windows

### ISSUE THREAD

**Issue by hermione521** [bazelbuild/bazel#1946]
Breakage:
http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=windows-x86_64/916/console

Related commit:
https://github.com/bazelbuild/bazel/commit/fe868010626115a9c6978c337f19549278965872

@ahumesky assigned to you because you reviewed this change. (Will also comment on the original change)

**Comment by ahumesky** [comment]
We decided to exclude the test for now from windows until we have a solution.

**Comment by dslomov** [comment]
@meteorcloudy on track for 0.5
