### ISSUE TITLE
[6.4.0] cc_proto_library doesn't get linked for binary with dynamic_deps

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#19468]
Forked from #17091

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts. Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19534 by @oquenchil
