### ISSUE TITLE
bazel execute submodules[mvn]' target differs with Maven

### ISSUE THREAD

**Issue by ddwolf** [bazelbuild/bazel#1947]
when I am integrating bazel into a exist maven project, which has to modules, I encountered a problem.
if I test maven's submodule , like :
```bash
 cd submod1; mvn test
```
the jvm's execution root will be this submod1 directory, in which I run the comand; while I test using bazel like: 
```bash
bazel test //submod1:alltests
```
 the jvm's execution root will be in the root directory of the bazel project.

is this a problem for bazel? or how can I fix this?

**Comment by hermione521** [comment]
@kchodorow can you help with this?

**Comment by kchodorow** [comment]
Generally that won't be an issue, Bazel will assume packages (in submod1) are relative to submod1/src/main/java and java generally doesn't care where things are on disk, so long as they're in the classpath.  If your tests are doing something funky with directories it's possible you could run into a dependency on directory structure... are you getting an error, or is this speculative?

**Comment by ddwolf** [comment]
@kchodorow yes I met a problem. 
I have a maven project that has two module.A/B
when I create a file like this:
```java :Test.java
   File file = new File("./target/repos/config.json")
```
in A's directory where there is a `target/repos/` directory, and the maven test goes well.

I setup WORKSPACE file a the root of the maven project, when I run bazel, because bazel run jvm in the different execution root, the file creation will cause an error. "Create File failed"

Now I seperate my WORKSPACE into two and everything goes well now
