### ISSUE TITLE
[6.4.0] --experimental_output_directory_naming_scheme=diff_against_baseline caused Bazel to rebuild whenever --run_under or --test_env change

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#19515]
Forked from #18480

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts. Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19514 by @fmeum
