### ISSUE TITLE
On Windows: porting cc_library to generate dll

### ISSUE THREAD

**Issue by t-vi** [bazelbuild/bazel#1954]
Hello,

thanks to your hard work, a lot of things seem to work in windows. However, one thing I am stuck with is what is the nicest way to get bazel to generate a .dll (or even .pyd) instead of .so.
(My use case is the _pywrap_tensorflow.)
The [example/windows/dll](https://github.com/bazelbuild/bazel/blob/master/examples/windows/dll/BUILD)  does not use cc_library but uses cc_binary for the lib. I am not sure what to do with porting then (duplicate the BUILD rule?). Maybe it would be nice to have a combination of the windows dll and linux library example...

Again, thanks for your work!

Thank you

Thomas

**Comment by philwo** [comment]
Assigning to @meteorcloudy, one of our Windows experts.

**Comment by laszlocsomor** [comment]
@meteorcloudy : Is this fixed together with https://github.com/bazelbuild/bazel/issues/3418?

**Comment by meteorcloudy** [comment]
Yes!
