### ISSUE TITLE
build bazel for a new platform--mips64el

### ISSUE THREAD

**Issue by vans88** [bazelbuild/bazel#1955]
I want to build bazel for tensorflow,bug I am getting the following error. Any suggestions?
/usr/local/bin/protoc -Isrc/main/protobuf/ -Isrc/main/java/com/google/devtools/build/lib/buildeventstream/proto/ --java_out=/tmp/bazel_2u7GJvhK/src --plugin=protoc-gen-grpc=/usr/local/bin/protoc-gen-grpc-java --grpc_out=/tmp/bazel_2u7GJvhK/src src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto
Missing input file.
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.

**Comment by philwo** [comment]
> /usr/local/bin/protoc
> --plugin=protoc-gen-grpc=/usr/local/bin/protoc-gen-grpc-java

It looks like you're using protoc from your local system for the Bazel bootstrap instead of one of the binaries we bundle, probably by settings the PROTOC and GRPC_JAVA_PLUGIN environment variables to /usr/local/bin/protoc and /usr/local/bin/protoc-gen-grpc-java. This will usually not work due to version differences.

I don't really know what "missing input file" protoc is complaining about here. Can you please share some information about the operating system you're using (which Linux version?) and the full command-line used that triggered this error?

**Comment by vans88** [comment]
Ok, many thanks. I built grpc-java and got the file "protoc-gen-grpc-java-1.1.0-SNAPSHOT-linux-mips64el.exe", so I copy it to /usr/local/bin/protoc-gen-grpc-java. but the protoc from local yum system. My platform information as follows:
Java version: 1.8.0_25
Java vendor: Oracle Corporation
Java vendor URL: http://java.oracle.com/
Java home: /usr/lib/jvm/j2sdk-image/jre
Java vm.specification.version: 1.8
Java vm.specification.vendor: Oracle Corporation
Java vm.specification.name: Java Virtual Machine Specification
Java vm.version: 25.25-b02
Java vm.vendor: Oracle Corporation
Java vm.name: OpenJDK 64-Bit Server VM
class.version: 52.0
class.path: .
library.path: /usr/java/packages/lib/mipsel:/usr/lib64:/lib64:/lib:/usr/lib
io.tmpdir: /tmp
java compiler: null
java ext dirs: /usr/lib/jvm/j2sdk-image/jre/lib/ext:/usr/java/packages/lib/ext
os.name: Linux
os.release: Fedora 21
os.arch: mips64el
kernel.version: 4.4.21+

**Comment by vans88** [comment]
[INFO] os.detected.name: linux
[INFO] os.detected.arch: mips64el
[INFO] os.detected.version: 4.4
[INFO] os.detected.version.major: 4
[INFO] os.detected.version.minor: 4
[INFO] os.detected.release: fedora
[INFO] os.detected.release.version: 21
[INFO] os.detected.release.like.fedora: true
[INFO] os.detected.classifier: linux-mips64el

**Comment by aehlig** [comment]
On Mon, Oct 17, 2016 at 06:26:39AM -0700, Philipp Wollermann wrote:
> It looks like you're using protoc from your local system for the Bazel bootstrap [...]

As Philipp mentioned, using the host protoc most likely will result in version conflicts.
so I would start by verifying that standard bootstrapping from the distribution artifact[1]
works; i.e., can you download https://github.com/bazelbuild/bazel/releases/download/0.5.0/bazel-0.5.0-dist.zip,
unpack, and run `bash compile.sh` there?

Also, in light of #3068, if you get an error mentioning workers, it is worth
trying javac in standalone strategy[2] first.

Thanks,
Klaus


[1] https://bazel.build/versions/master/docs/install-compile-source.html
[2] https://svnweb.freebsd.org/ports/head/devel/bazel/files/patch-scripts_bootstrap_bootstrap.sh?revision=436446&view=markup

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by xzy256** [comment]
@aehlig @laszlocsomor i change `scripts/bootstrap/bootstrap.sh` infer  [ https://svnweb.freebsd.org/ports/head/devel/bazel/files/patch-scripts_bootstrap_bootstrap.sh?revision=436446&view=markup](https://svnweb.freebsd.org/ports/head/devel/bazel/files/patch-scripts_bootstrap_bootstrap.sh?revision=436446&view=markup)
i get a new error,at the same time, JVM is broke down .
<pre class=code>
ERROR: /home/xzy/test/src/main/java/com/google/devtools/build/lib/BUILD:277:1: 
Building src/main/java/com/google/devtools/build/lib/libsingle-line-formatter.jar (1 source file) failed:
 java failed: error executing command 
  (cd /tmp/bazel_5yLwBSLV/out/execroot/test && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
  /opt/j2sdk-image/bin/java -Xbootclasspath/p:third_party/java/jdk/langtools/javac-9-dev-r4023-2.jar 
-XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -jar bazel-out/host/bin/src/java_tools/buildjar
/java/com/google/devtools/build/buildjar/bootstrap_deploy.jar @bazel-out/local-opt/bin/src/main
/java/com/google/devtools/build/lib/libsingle-line-formatter.jar-2.params): 
com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 11.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0xa) at pc=0x000000ffd92c8ad4, pid=17282, tid=1099237290480
#
# JRE version: OpenJDK Runtime Environment (8.0_25-b17) (build 1.8.0_25-rc22-b17)
# Java VM: OpenJDK 64-Bit Server VM (25.25-b02 mixed mode linux-mips64 compressed oops)
# Problematic frame:
# J 1 C1 java.lang.String.hashCode()I (55 bytes) @ 0x000000ffd92c8ad4 [0x000000ffd92c8a40+0x94]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, 
try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /tmp/bazel_5yLwBSLV/out/execroot/test/hs_err_pid17282.log
</pre>

**Comment by philwo** [comment]
Some ideas:
- A bug in your JVM? Version "1.8.0_25-rc22" sounds like a release candidate?
- The JVM often gets a [SIGBUS when your /tmp is almost full](https://confluence.atlassian.com/confkb/java-vm-dies-with-sigbus-0x7-when-temp-directory-is-full-on-linux-815584538.html). Can you send the output of "df -h", "df -i" and "mount" from your system where the build fails?

**Comment by laszlocsomor** [comment]
Try also if you can build a hello world with Java:
```
mkdir -p /tmp/foo
echo 'public class A { public static void main(String[] args) { System.out.println("hello world!"); } }' > /tmp/foo/A.java
javac /tmp/foo/A.java
java -cp /tmp/foo A
```

**Comment by laszlocsomor** [comment]
> (Hm, you probably can do that, since compile.sh can build Bazel for the first time.)

...which must leave behind a lot of build artifacts in /tmp, making it more likely that @philwo 's suspicion is correct.

Try this:
```
export TMPDIR=/usr/local/$USER/bazel_temp_xxx
bash -x compile.sh
```

**Comment by xzy256** [comment]
@philwo "df -h", "df -i" and "mount" output as follow. unpack bazel-0.4.5-rc9 at ` test` directory.
<pre>
[xzy@localhost test]$ df -h
file system       total  used   available used%  mount
/dev/root           50G   31G   16G     66%        /
devtmpfs          3.8G   0        3.8G    0%        /dev
tmpfs                3.8G  688K  3.8G    1%        /dev/shm
tmpfs                3.8G  4.2M  3.8G    1%         /run
tmpfs                3.8G     0     3.8G    0%         /sys/fs/cgroup
tmpfs           3.8G  8.0M  3.8G         1%         /tmp
tmpfs           778M   16K  778M        1%        /run/user/989
tmpfs           778M  112K  778M       1%        /run/user/1001
[xzy@localhost test]$ df -i
file system       total  used   available used%  mount
/dev/root      3276800  644113 2632687      20% /
devtmpfs        248839     500  248339       1% /dev
tmpfs           248849       6  248843       1% /dev/shm
tmpfs           248849     587  248262       1% /run
tmpfs           248849      11  248838       1% /sys/fs/cgroup
tmpfs           248849      45  248804       1% /tmp
tmpfs           248849       6  248843       1% /run/user/989
tmpfs           248849      15  248834       1% /run/user/1001
[xzy@localhost test]$ mount
/dev/sda3 on / type ext4 (rw,relatime,data=ordered)
devtmpfs on /dev type devtmpfs (rw,relatime,size=3981424k,nr_inodes=248839,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct,cpu)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=22,pgrp=1,timeout=300,minproto=5,maxproto=5,direct)
mqueue on /dev/mqueue type mqueue (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
tmpfs on /tmp type tmpfs (rw)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
configfs on /sys/kernel/config type configfs (rw,relatime)
tmpfs on /run/user/989 type tmpfs (rw,nosuid,nodev,relatime,size=796320k,mode=700,uid=989,gid=984)
tmpfs on /run/user/1001 type tmpfs (rw,nosuid,nodev,relatime,size=796320k,mode=700,uid=1001,gid=1001)
gvfsd-fuse on /run/user/1001/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1001,group_id=1001)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
</pre>

**Comment by xzy256** [comment]
@ laszlocsomor  i can run "hello word", this  #1955 (comment) page is always invilid
<pre>
[xzy@localhost ~]$ mkdir -p /tmp/foo
[xzy@localhost ~]$ echo 'public class A { public static void main(String[] args) { System.out.println("hello world!"); } }' > /tmp/foo/A.java
[xzy@localhost ~]$ javac /tmp/foo/A.java
[xzy@localhost ~]$ java -cp /tmp/foo A
hello world!
</pre>

**Comment by laszlocsomor** [comment]
> this #1955 (comment) page is always invilid

I don't understand, which page is always invalid?

**Comment by xzy256** [comment]
When i commit  comment, i get Unicorn page error. I guess multi operator edit comment lead to have opened page becoming old page. now, it is normal.

**Comment by xzy256** [comment]
i do infer next, but error is same.
> export TMPDIR=$HOME/bazel_temp_xxx
bash -x compile.sh
<pre>
[xzy@localhost test]$ echo $TMPDIR
/home/xzy/bazel_T9FeQm5j/
[xzy@localhost test]$bash -x compile.sh
... ...
ERROR: /home/xzy/test/src/main/java/com/google/devtools/build/lib/BUILD:277:1: Building src/main/java/com/google/devtools/build/lib/libsingle-line-formatter.jar (1 source file) failed: java failed: error executing command 
  (cd /home/xzy/bazel_T9FeQm5j/bazel_pLB449UD/out/execroot/test && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
  /opt/j2sdk-image/bin/java -Xbootclasspath/p:third_party/java/jdk/langtools/javac-9-dev-r4023-2.jar -XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -jar bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/bootstrap_deploy.jar @bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/libsingle-line-formatter.jar-2.params): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 11.

**Comment by laszlocsomor** [comment]
> When i commit comment, i get Unicorn page error.

I see. Yes, GitHub was down for me too about an hour ago.

> i do infer next, but error is same.
> (...)
> Process terminated by signal 11.

Signal 11 is SIGSEGV, so we have a segfault. Can you try a different JDK as @philwo suggested?

**Comment by xzy256** [comment]
Thank you very much @philwo @laszlocsomor @aehlig 
My JVM don't support `jvm_opts: -XX:+TieredCompilation   -XX:TieredStopAtLevel=1`.  Grepping and annotating it, then build successful. Last patch inferring [build-bazel-mips64.patch](https://github.com/xzy256/bazel-mips64/blob/master/build-bazel-mips.patch)
<pre>
[root@localhost bazel-0.5.0]# grep "TieredCompilation" . -r
./tools/jdk/BUILD:#        "-XX:+TieredCompilation",
./src/java_tools/buildjar/BUILD:#        "-XX:+TieredCompilation",
./src/java_tools/buildjar/BUILD:#        "-XX:+TieredCompilation",
</pre>

**Comment by laszlocsomor** [comment]
@xzy256 : Thanks for getting back to us! I'm glad you found the solution! How did you find it?

**Comment by xzy256** [comment]
Because my `JVM` is a release candidate, some params aren't supported. I hold the mind to try by error tips. Fortunately，it works.

**Comment by laszlocsomor** [comment]
Ha, cool :) Thanks!
