### ISSUE TITLE
[6.4.0] Add `--consistent_labels` flag to all query commands

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#19552]
Forked from #19508

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts. Please resolve manually.
cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
I'm preparing a manual cherry-pick for this.

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19567 by @Wyverald
