### ISSUE TITLE
[6.4.0] Use effective `StarlarkSemantics` with `cquery --output=starlark`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#19551]
Forked from #19334

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts. Please resolve manually.
cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
This is also being cherry-picked in https://github.com/bazelbuild/bazel/pull/19567
