### ISSUE TITLE
Bzlmod /external/migration page does not mention --enable_bzlmod

### ISSUE THREAD

**Issue by jlisee** [bazelbuild/bazel#19561]
### Page link:

https://bazel.build/external/migration

### Problem description (include actual vs expected text, if applicable):

The need for the `--enable_bzlmod` flag is mentioned only once in the [bzlmod overview page](https://bazel.build/external/overview).  It's easy to miss this which means you spend a while figuring out why none of the Bzlmod sample content is working for you. 

At a minimum tutorials like the migration guide should mention it, but in general the flag and how to use it need to much more prominent in the documentation and general examples.  For example [this external guide](https://blog.aspect.dev/bzlmod#heading-kicking-the-tires-yourself) mentions setting the flag in your RC file as the first step before doing anything else.

### Where do you see this issue? (include link to specific section of the page, if applicable)

The https://bazel.build/external/migration is missing information on using the flag.

### Any other information you'd like to share?

Here is a proposed documentation patch. I can make this a PR if desired:
https://github.com/bazelbuild/bazel/compare/master...jlisee:bazel:jlisee/bzlmod-flag-migration-guide

**Comment by keertk** [comment]
Thanks for the issue and proposed doc fix, @jlisee! 
cc @Wyverald to take a look and confirm

**Comment by meteorcloudy** [comment]
@jlisee Thanks for reporting, happy to review the PR!

**Comment by jlisee** [comment]
> @jlisee Thanks for reporting, happy to review the PR!

PR up at https://github.com/bazelbuild/bazel/pull/19574
