### ISSUE TITLE
On Windows `bazel clean --expunge` fails always

### ISSUE THREAD

**Issue by andreas-0815-qwertz** [bazelbuild/bazel#19562]
### Description of the bug:

Whenever I am running

`bazel clean --expunge`

bazel fails with the following error:

`ERROR: C:/_bazel/user_root/install/514d6bd1346ca30a25ef0dae1a54ba5f/A-server.jar (Permission denied)`

I have the following in my user-bazelrc,, which explains the path to `A-server.jar` in the error message above:

```
startup --noautodetect_server_javabase
startup --server_javabase=C:/Users/446158/java/jdk-17.0.8.1+1
startup --host_jvm_args=-Djavax.net.ssl.trustStore=NUL
startup --host_jvm_args=-Djavax.net.ssl.trustStoreType=Windows-ROOT
startup --output_base=C:/_bazel
startup --output_user_root=C:/_bazel/user_root
```

### Which category does this issue belong to?

Core

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build some target and run `bazel clean --expunge` afterwards.

### Which operating system are you running Bazel on?

Windows

### What is the output of `bazel info release`?

release 6.2.1

**Comment by iancha1992** [comment]
@andreas-0815-qwertz Could you please provide complete steps to reproduce this issue?

**Comment by andreas-0815-qwertz** [comment]
After a reboot, the issue has vanished. Sorry for the noise.
