### ISSUE TITLE
[Mirror] rules_cc & rules_java

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#19578]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/rules_cc/releases/download/0.0.9/rules_cc-0.0.9.tar.gz
https://github.com/bazelbuild/rules_java/releases/download/6.3.1/rules_java-6.3.1.tar.gz

**Comment by Pavank1992** [comment]
Please find the mirror artifacts below:

https://mirror.bazel.build/github.com/bazelbuild/rules_cc/releases/download/0.0.9/rules_cc-0.0.9.tar.gz
https://mirror.bazel.build/github.com/bazelbuild/rules_java/releases/download/6.3.1/rules_java-6.3.1.tar.gz
