### ISSUE TITLE
exclusive_if_local does not work as advertised

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#19570]
### Description of the bug:

`exclusive_if_local` is documented on https://bazel.build/reference/be/common-definitions as a tag on a test that makes it run serially only when local, but otherwise in parallel when remote.

However, as https://github.com/bazelbuild/bazel/pull/17854 demonstrates, it always defaults to false in Bazel.

This is necessary for projects like Android that have a significant number of device tests that need to run serially, but may have access to dedicated device pools remotely, which enables parallel testing.

### Which category does this issue belong to?

Remote Execution

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

For an RBE enabled test, tag it with `exclusive-if-local`, and run it with `--runs_per_test=100`. Observe that the tests run serially.

### Which operating system are you running Bazel on?

linux

**Comment by meisterT** [comment]
@jin is this a dupe of https://github.com/bazelbuild/bazel/issues/17834 or is there some additional nuance here?

**Comment by jin** [comment]
Correct, this is dupe of #17834.
