### ISSUE TITLE
feature request: local_jar workspace function

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/bazel#1960]
I'm trying to help debug my use of rules_closure, and it depends the closure-compiler jar file and uses a "@closure_compiler//jar" explicitly. Unfortunately, it's not clear how to get bazel to use a locally installed version of a jar without always looking it up in a remote Maven repository.

It would be nice to be able to use a local jar, so that we don't have to both hack up new BUILD files for the maven project as well as the targets of those other people's builds to not depend on '//jar'.

There seems to be some magic in `--maven_projects` that does this in GenerateWorkspace, but it seems unrelated to the code that does repository resolution.

Or maybe I've missed something obvious?

**Comment by jmhodges** [comment]
Okay! I figured out the magic incantation that will do this! I'll post it here, but it might be nice to call this out in the docs for when folks have to debug jars they fetch remotely. Should I make a new ticket for those docs?

The howto:

You'll need to create a `maven_server` with a `file:` scheme URL in it and then refer to it in your maven_jar. Like so:

    maven_server(
        name = "local_repo",
        url = "file:/Users/YOUR_USER_NAME/.m2/repository",
    )

    maven_jar(
        name = "closure_compiler",
        artifact = "com.google.javascript:closure-compiler-unshaded:1.0-weirdness",
        server = "local_repo"
    )

(Note the single '/' in `file:/`.)

(While I've not actually gotten a working build yet but that just seems to be because of some guava dep problems.)

**Comment by katre** [comment]
Would java_import (https://www.bazel.io/versions/master/docs/be/java.html#java_import) do what you want? You'd need to add the jar to your repo and commit it, but it can then directly be a dependency for other rules.

**Comment by jmhodges** [comment]
Oh yeah that would definitely do it. This request was for use in local debugging, so this is perfect. Didn't know this func was coming down the line!

**Comment by petemounce** [comment]
@jmhodges would you mind detailing how you mirrored remote maven dependencies into your local repository? I'm trying to use that technique to work around the issue I have in #1941. How did the remote structure look compared to the local? Very unfamiliar, so no detail too obvious!

**Comment by jmhodges** [comment]
Oh, I had used mvn to download the artifacts at some point. Probably did a build in the repo. Then set that stuff up as above.
