### ISSUE TITLE
[bazel.build] Problem with /remote/bep

### ISSUE THREAD

**Issue by keddad** [bazelbuild/bazel#19608]
### Page link:

https://bazel.build/remote/bep

### Problem description (include actual vs expected text, if applicable):

BES Service flags mention --project_id flag, saying that documentation on it would be on CLI reference page. However, from what I can see, there is no such flag - it was renamed to --bes_instance_name in 5.0, and CLI reference only mentions it under a new name. It should probably be renamed on BEP documentation as well.

### Where do you see this issue? (include link to specific section of the page, if applicable)

[Section link](https://bazel.build/remote/bep#bes-flags)

**Comment by keertk** [comment]
Thanks for raising this issue, @keddad. Would you be willing to submit a PR to fix this?

**Comment by keddad** [comment]
Sure! See #19778
