### ISSUE TITLE
[Mirror] hermetic_cc_toolchain@v2.1.2

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel#19618]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/uber/hermetic_cc_toolchain/releases/download/v2.1.2/hermetic_cc_toolchain-v2.1.2.tar.gz

**Comment by Pavank1992** [comment]
Please find the mirror artifact below-
https://mirror.bazel.build/github.com/uber/hermetic_cc_toolchain/releases/download/v2.1.2/hermetic_cc_toolchain-v2.1.2.tar.gz
