### ISSUE TITLE
feature request: support sha256 in maven_jar

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/bazel#1961]
Currently, sha1 is supported, but that's now a fairly insecure hash. Having sha256 would be nice.

**Comment by jin** [comment]
Also raised in #991, and umbrella issue is in #1410.

**Comment by ittaiz** [comment]
I'll just put it here :) https://arstechnica.com/security/2017/02/at-deaths-door-for-years-widely-used-sha1-function-is-now-dead/

**Comment by jin** [comment]
maven_jar has been removed.
