### ISSUE TITLE
Aspects: Merge validation output group

### ISSUE THREAD

**Issue by ismell** [bazelbuild/bazel#19624]
### Description of the feature request:

If I have a rule that returns the special [_validation](https://bazel.build/extending/rules#validation_actions) output group, it's not possible for an aspect also return the `_validation` output group. This results in a `Output group _validation provided twice` error.

According to the [aspect documentation](https://bazel.build/extending/aspects):
> It is an error if a target and an aspect that is applied to it each provide a provider with the same type, with the exceptions of [OutputGroupInfo](https://bazel.build/rules/lib/providers/OutputGroupInfo) (which is merged, so long as the rule and aspect specify different output groups)

It would be nice to extend this allow merging the `_validation` output group.

### Which category does this issue belong to?

Core

### What underlying problem are you trying to solve with this feature?

Allow multiple aspects to declare their own validations.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

6.2.0

### Have you found anything relevant by searching the web?

https://groups.google.com/g/bazel-discuss/c/TCo0msh1My4 was used as an inspiration to add validations via aspects.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 6.4.0 RC2](https://releases.bazel.build/6.4.0/rc2/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!
