### ISSUE TITLE
Tensorflow Serving error: no such package '@six_archive//'

### ISSUE THREAD

**Issue by robertcrowe** [bazelbuild/bazel#1963]
When trying to build a client under Tensorflow Serving I'm getting this error:

> bazel build //basic:client
> ERROR: /home/rcrowe/.cache/bazel/_bazel_rcrowe/b1867dd6bfd6249a885c91482eccde46/external/org_tensorflow/tensorflow/workspace.bzl:80:3: no such package '@six_archive//': In new_http_archive rule //external:six_archive the 'build_file' attribute does not specify an existing file (/home/rcrowe/serving/six.BUILD does not exist) and referenced by '//external:six'.
> ERROR: Analysis of target '//basic:client' failed; build aborted.
> INFO: Elapsed time: 0.219s

I haven't changed the WORKSPACE or the tensorflow_serving/workspace.bzl files, but I have recently upgraded Tensorflow from 10 to 11.  The WORKSPACE and workspace.bzl files are attached (added .txt in order to attach).

[WORKSPACE.txt](https://github.com/bazelbuild/bazel/files/537603/WORKSPACE.txt)

[workspace.bzl.txt](https://github.com/bazelbuild/bazel/files/537605/workspace.bzl.txt)

Copying @jart by request

**Comment by jart** [comment]
I'm surprised the TensorFlow serving repository has code using `local_repository()` checked in with relative paths to git submodules. https://github.com/tensorflow/serving/blob/master/tensorflow_serving/workspace.bzl

**Comment by robertcrowe** [comment]
I don't know enough about Bazel, but it sounds like having code using local_repository() with relative paths to git submodules is a bad thing.  Should we file an issue with Tensorflow Serving?  Could you recommend a fix for them?

**Comment by jart** [comment]
Yes it's definitely worth filing an issue with them. https://github.com/tensorflow/serving/issues/212

**Comment by ulfjack** [comment]
@meteorcloudy

**Comment by damienmg** [comment]
@jart this is a known issue and until python configuration is fixed on TensorFlow side, this cannot be fixed.

Anyway not a bazel bug so closing.
