### ISSUE TITLE
missing RunfileSupports doc

### ISSUE THREAD

**Issue by ddwolf** [bazelbuild/bazel#1964]
I saw a statement in the bazel document: 

> the *.runfiles directories is documented in more detail in the places pointed to by #RunfilesSupport#
> But I cant find RunfilesSupport any where.

**Comment by laszlocsomor** [comment]
Here it is: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/analysis/RunfilesSupport.java
