### ISSUE TITLE
[Q] How to see g++ warnings?

### ISSUE THREAD

**Issue by apivovarov** [bazelbuild/bazel#19644]
### Problem description (include actual vs expected text, if applicable):

I'm using bazel build to build my project. How to see g++ warnings?

**Comment by Pavank1992** [comment]
@user Could you please provide elaborate you issue or share sample code to reproduce this issue?

**Comment by apivovarov** [comment]
ok, I found it

Option 1 (TF specific):
```
bazel build --config=verbose_logs  

# TF default is --config=short_logs which is converted to --output_filter=DONT_MATCH_ANYTHING
# this is why TF build does not print any gcc warnings
```

Option 2:
```
bazel build --output_filter= ... 

# by default bazel uses empty output_filter - which will print gcc warnings.
```
