### ISSUE TITLE
//src/test/shell/bazel:bazel_windows_example_test is broken

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#1965]
Commit https://github.com/bazelbuild/bazel/commit/fa389066641ac7f92b220ef232f23e757704318d broke the //src/test/shell/bazel:bazel_windows_example_test test.

The test was disabled for now, but please fix the test and re-enable it.

**Comment by laszlocsomor** [comment]
Does https://github.com/bazelbuild/bazel/commit/3eef69dbef66371d0d3633a8e5fbbfe9971df961 fix this?

**Comment by meteorcloudy** [comment]
Yes, forgot to close this.
