### ISSUE TITLE
[Mirror] `bazelbuild/rules_go` version `v0.42.0`

### ISSUE THREAD

**Issue by tyler-french** [bazelbuild/bazel#19664]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/rules_go/releases/download/v0.42.0/rules_go-v0.42.0.zip

And transitives:
https://github.com/bazel-contrib/bazel_features/releases/download/v1.1.0/bazel_features-v1.1.0.tar.gz
https://github.com/golang/sys/archive/refs/tags/v0.12.0.zip
https://github.com/protocolbuffers/protobuf-go/archive/refs/tags/v1.31.0.zip
https://github.com/googleapis/go-genproto/archive/007df8e322eb3e384d36c0821e2337825c203ca6.zip

**Comment by Pavank1992** [comment]
Please find the requested mirror artifacts below:

https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.42.0/rules_go-v0.42.0.zip
https://mirror.bazel.build/github.com/bazel-contrib/bazel_features/releases/download/v1.1.0/bazel_features-v1.1.0.tar.gz
https://mirror.bazel.build/github.com/golang/sys/archive/refs/tags/v0.12.0.zip
https://mirror.bazel.build/github.com/protocolbuffers/protobuf-go/archive/refs/tags/v1.31.0.zip
https://mirror.bazel.build/github.com/googleapis/go-genproto/archive/007df8e322eb3e384d36c0821e2337825c203ca6.zip
