### ISSUE TITLE
[6.4.0] Remove stale extension entries from lockfile if module order changes

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#19669]
Forked from #19659

**Comment by iancha1992** [comment]
As per https://github.com/bazelbuild/bazel/pull/19659#issuecomment-1741265578, we'll merge this only after https://github.com/bazelbuild/bazel/pull/19658 is merged. FYI.

cc: @bazelbuild/triage

**Comment by bazel-io** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19730
