### ISSUE TITLE
actions.run `arguments` are not passed when executing a test rule

### ISSUE THREAD

**Issue by hashar** [bazelbuild/bazel#19661]
### Description of the bug:

I wrote a test rule to run an executable to which a list of files will be passed to act upon. I am using `ctx.actions.run` and pass the files to the `arguments` parameter.

Inspecting the action graph I see the parameters being passed (`one.json` and `two.json`):
```
action 'Action dump_test.output'
  Mnemonic: Action
  Target: //:dump_test
  ...
  Inputs: [bazel-out/k8-fastbuild/bin/dumparguments, one.json, two.json]
  Outputs: [bazel-out/k8-fastbuild/bin/dump_test.output]
  Command Line: (exec bazel-out/k8-fastbuild/bin/dumparguments \
    one.json \
    two.json)
```
But further below the testing action does not have them:
```
action 'Testing //:dump_test'
  Mnemonic: TestRunner
  Target: //:dump_test
  ...
  Inputs: [bazel-out/k8-fastbuild/internal/_middlemen/dumparguments-runfiles, external/bazel_tools/tools/test/generate-xml.sh, external/bazel_tools/tools/test/test-setup.sh]
  Outputs: [bazel-out/k8-fastbuild/testlogs/dump_test/test.cache_status, bazel-out/k8-fastbuild/testlogs/dump_test/test.log]
  Command Line: (exec external/bazel_tools/tools/test/test-setup.sh \
    ./dumparguments)
```

I am certainly missing something obvious, the arguments come from a `glob(["**/*.json"])` injected using the `ctx.files.inputs` and maybe those files are not available in the execution environment.

The files in my workspace:
```
BUILD
dumparguments (executable)
one.json
rules.bzl
two.json
WORKSPACE (empty)
```

**BUILD**
```
load("//:rules.bzl", "dumpargs_test")

dumpargs_test(
    name = "dump_test",
    # Python script dumping sys.argv
    binary = "//:dumparguments",
    # /one.json /two.json
    inputs = glob(["**/*.json"]),
)
```

**dumparguments**
```python
#!/usr/bin/python3

import pprint
import sys

print("# of args:", len(sys.argv))
pprint.pprint(sys.argv)
sys.exit(2)
```

**rules.bzl**
```python
def _dump_args_impl(ctx):
    output_file = ctx.actions.declare_file(ctx.label.name + ".output")

    # The rule MUST creates the executable, work around it by creating an
    # executable symbolic link pointing to the given target.
    executable = ctx.actions.declare_file(ctx.executable.binary.path)
    ctx.actions.symlink(
        output = executable,
        target_file = ctx.executable.binary,
        is_executable = True,
    )

    ctx.actions.run(
        executable = executable,
        inputs = ctx.files.inputs,
        outputs = [output_file],
        arguments = [i.path for i in ctx.files.inputs],
    )

    return [
        DefaultInfo(
            executable = executable,
        ),
    ]

dumpargs_test = rule(
    implementation = _dump_args_impl,
    test=True,
    attrs = {
        "binary": attr.label(
            mandatory=True,
            allow_single_file=True,
            executable=True,
            cfg="exec",
        ),
        "inputs": attr.label_list(allow_files=True),
    }
)
```

### Which category does this issue belong to?

Rules API

### Which operating system are you running Bazel on?

Debian 12 (bookworm)

### What is the output of `bazel info release`?

release 6.3.2

### Have you found anything relevant by searching the web?

I have search the Bazel issue tracker, Stackoverflow and have read the documentation for the run Action at https://bazel.build/rules/lib/builtins/actions#run .

### Any other information, logs, or outputs that you want to share?

**`bazel test ...`**
```
INFO: Analyzed target //:dump_test (1 packages loaded, 4 targets configured).
INFO: Found 1 test target...
FAIL: //:dump_test (see 053dce17be1d774b5aadfb2c9c6023d5/execroot/__main__/bazel-out/k8-fastbuild/testlogs/dump_test/test.log)
INFO: From Testing //:dump_test:
==================== Test output for //:dump_test:
# of args: 1
['053dce17be1d774b5aadfb2c9c6023d5/sandbox/linux-sandbox/23/execroot/__main__/bazel-out/k8-fastbuild/bin/dumparguments.runfiles/__main__/dumparguments']
================================================================================
Target //:dump_test up-to-date:
  bazel-bin/dumparguments
INFO: Elapsed time: 0.217s, Critical Path: 0.12s
INFO: 4 processes: 2 internal, 2 linux-sandbox.
INFO: Build completed, 1 test FAILED, 4 total actions
//:dump_test                                                             FAILED in 0.1s
  053dce17be1d774b5aadfb2c9c6023d5/execroot/__main__/bazel-out/k8-fastbuild/testlogs/dump_test/test.log

Executed 1 out of 1 test: 1 fails locally.
$
```
Note the command receives only one argument (the script) and is missing the input files (`one.json`, `two.json`).

The test failure is expected, the script exits 2.

**Comment by tjgq** [comment]
Test rules are special and a little awkward to write. You can't use `ctx.actions.run` to define the test runner action; instead, the test rule must return a self-contained executable (to be invoked with no command line arguments) and a set of runfiles (other files that must be available in the test environment). Something along these lines:

```
def _dump_args_impl(ctx):
  # Write the self-contained test runner script which calls your Python binary with the right arguments.
  script = ctx.actions.declare_file(ctx.label.name + ".script")
  ctx.actions.write(
    output = script,
    content = """#!bin/bash
{exe} {args}""".format(
      exe = exe.short_path,
      args = " ".join([f.short_path for f in ctx.files.inputs]))
    is_executable = True,
  )

  # Collect runfiles required by the test.
  # For a single-file binary, you could simply write ctx.runfiles([ctx.attr.executable] + ctx.files.inputs).
  # The version below is required for binaries that have their own support runfiles, like py_binary.
  runfiles = ctx.attr.executable[DefaultInfo].default_runfiles.merge(ctx.runfiles(ctx.files.inputs))

  return DefaultInfo(
    test = True,
    executable = script,
    runfiles = runfiles,
  )
```

**Comment by hashar** [comment]
Ouch, I guess that explains why in most rules I see people using `ctx.actions.run_shell` (which creates a script similar to how you propose to create one on the fly with `ctx.actions.write()`.

I also gave `runfiles` a try but I am afraid I will have to read the documentation and dig a bit more into that topic since when running the rule several times I ended up with input files being duplicates over and over I guess due to the recursive glob (first run has 2 files, second has 4 with nested sub directory, third run has 8 files etc). But that is a different topic.

I have also though the arguments might not be passed cause I am using files (`arguments = [i.path for i in ctx.files.inputs],`), but if I pass a list of strings such as (`arguments = ["--verbose", "--fail-fast"]`) they show up in the //Action dump_test.output// action but don't show in //action 'Testing //:dump_test'//.

More oddities, if I make the rule a binary one (with `executable = True` instead of `test = True`) then:
* `bazel run //:dump` executes the executable without any of the arguments provided in the rule
* `bazel run //:dump foo bar hello` does have the three arguments passed from the command line

It is going to be a long road ;)  I guess I will mimic others and go with `ctx.actions.run_shell()` or forging a script on the fly.  But I think those behavior should be documented, notably the doc for `actions.run` `arguments` should mention they are not passed to binary/test (I guess they are stripped at some point).

**Comment by tjgq** [comment]
In this context, `run` and `run_shell` are equivalent; neither can be used to define a test.

Have you read all of https://bazel.build/extending/rules? I realize that it's a lot of information to digest, but it will help you build a better mental model for how Bazel works. In particular, I suspect the following aren't yet clear to you:

1. Every call to `run`/`run_shell` creates a separate action, and a single rule can declare as many of them as it wants. In addition, every test rule has an implicit TestRunnerAction, which is entirely separate from actions created by calling `run`/`run_shell` in the rule implementation function. No arguments are "stripped"; you're just adding them to a different action.

1. An action does not run simply because it was declared; it runs when the output it produces is requested (either because you directly asked Bazel to build it, or because it's a transitive requirement of something you asked Bazel to build). The `aquery` output shows you the list of declared actions, which is a superset of the actions that will actually run. When you run `bazel test`, you're only asking for the TestRunnerAction to run; in turn, this will cause whatever actions are needed to produce the `executable` or `runfiles` to run (but the action you declared via `run` isn't one of them).

1. An executable rule is similar to a test rule in that `bazel run`ning an executable rule will just run its `executable` in an environment containing its `runfiles`. Any `run`/`run_shell` actions declared by the rule are irrelevant for `bazel run` unless they produce the `executable`, the `runfiles`, or anything else they transitively depend on.

I do agree that the documentation is lacking on how to write a complex test rule; an example where one calls a preexisting binary with arguments

**Comment by hashar** [comment]
Thank you very much @tjgq , I still have to digest your last comment :)

I have found another issue that looks closely related #11772.  When digging in Bazel code, it looks like `args` is being passed from the definition to the `TestAction`.  That is tentatively coming from:
```
// src/main/java/com/google/devtools/build/lib/analysis/RunfilesSupport.java
  private static CommandLine computeArgs(RuleContext ruleContext) throws InterruptedException {
    if (!ruleContext.getRule().isAttrDefined("args", Type.STRING_LIST)) {
      // Some non-_binary rules create RunfilesSupport instances; it is fine to not have an args
      // attribute here.
      return CommandLine.EMPTY;
    }
    ImmutableList<String> args = ruleContext.getExpander().withDataLocations().tokenized("args");
    return args.isEmpty() ? CommandLine.EMPTY : CommandLine.of(args);
  }
```

Interestingly I made a typo at some point in the `ctx.actions.symink` parameters and nothing was broken (indicating the test do not run those actions).  The `TestAction` is forged from the rule, and I guess this bug report would be about having `TestAction` to add to the test command line arguments the values from `ctx.actions.run( arguments = [...]`, but given that is not processed, I guess they are not accessible.

So it looks like I can repurpose my code to pass the extra options via `args`:
```
dumpargs_test(
    name = "dump_test",
    # Python script dumping sys.argv
    binary = "//:dumparguments",
    args = glob(["**/*.json"]),
)
```

(I still have to finish understanding your last comment).

**Comment by tjgq** [comment]
I stand corrected! It looks like the `args` attribute is indeed available by default on every test rule: https://bazel.build/reference/be/common-definitions#common-attributes-tests. So if you can live with the `args` name, you can avoid constructing a self-contained script in the rule implementation.

**Comment by comius** [comment]
Thanks @tjgq for support.

Closing this issue, because it's WAI.

**Comment by hashar** [comment]
+1 on closing and sorry for not having closed it myself.

Thank you very much @tjgq for giving me thorough explanations of the different between executable and test targets.
