### ISSUE TITLE
Projects broken by testonly enforcement on ci.bazel.io: re2, rules_scala, rules_web, TensorFlow, TensorFlow_Serving

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1967]
Creating that bug for tracking my progress toward fixing those projects. /cc @philwo fyi

**Comment by damienmg** [comment]
https://code-review.googlesource.com/8610 for re2

**Comment by damienmg** [comment]
bazelbuild/rules_scala#98 for rules_scala

**Comment by damienmg** [comment]
bazelbuild/rules_web#20 for rules_web
tensorflow/tensorflow#5093 for TensorFlow

TensorFlow serving needs tensorflow pr in.

**Comment by damienmg** [comment]
(fwiw it is not really blocking the release itself, we need to fix the project).

rules_webtesting have been fixed by upstream.

**Comment by petemounce** [comment]
I'm using bazel to compile some scala, and I think I'm affected by this issue. I have a target like

```python
scala_library(
    name = "testing_scala",
    testonly = 1,
    srcs = glob(["*.java"]),
    visibility = ["//visibility:private"],
    deps = [
        "//third_party/scalatest",
    ],
)
```

If I've understood the issue correctly, this is because of the `testonly = 1` attribute being set.

**Comment by damienmg** [comment]
I think your error is related to Sandboxing on OS X. It is definitely not related to testonly,

**Comment by petemounce** [comment]
@damienmg is https://github.com/bazelbuild/bazel/wiki/How-to-turn-off-sandboxing accurate? It seems to refer to options applicable for `bazel test`, not `bazel build`? Also, the snippet contains commas, so it looks not quite right?

**Comment by petemounce** [comment]
If I change my bazel invocation to `${BAZEL} build --spawn_strategy=standalone  --genrule_strategy=standalone --test_strategy=standalone //my_target` I get the same error.

**Comment by kchodorow** [comment]
Is this still a release blocker?

**Comment by damienmg** [comment]
@kchodorow: No sorry.
@petemounce: yes it should be

**Comment by petemounce** [comment]
@damienmg it's ok - I was able to repro my issue within rules_scala and have PR'd with that failing test bazelbuild/rules_scala#101. No capacity to actually fix right at the moment as I'm involved in our own release cycle.

**Comment by damienmg** [comment]
Ok only TensorFlow_Serving is left.

**Comment by damienmg** [comment]
And now TensorFlow_Serving is fixed! Breakage over \o/
