### ISSUE TITLE
ctx.actions.run inserts execroot into the command

### ISSUE THREAD

**Issue by lyuboasenov** [bazelbuild/bazel#19695]
### Description of the bug:

When running an action from a custom bazel rule on Windows. The execution root path is contained in the subcommand. This makes remote cache sharing impossible if the repository is not cloned at the same path.

### Which category does this issue belong to?

Rules API

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I've created a reproduction repository:

[https://github.com/lyuboasenov/bazel-windows-actions-run](https://github.com/lyuboasenov/bazel-windows-actions-run)

### Which operating system are you running Bazel on?

Microsoft Windows 11 Enterprise 1252

### What is the output of `bazel info release`?

release 6.1.2

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
PS C:\Users\lasenov\git\bazel-windows-actions-run> git remote get-url origin; git rev-parse main; git rev-parse HEAD
git@github.com:lyuboasenov/bazel-windows-actions-run.git
7adc84fc14db8dc52afb733df78893e834eeb070
7adc84fc14db8dc52afb733df78893e834eeb070
```

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

I don't think it is.

### Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

Here is what I get when I run the bazel build for the demo repo:

`PS C:\Users\lasenov\git\bazel-windows-actions-run> bazel build //package:run
INFO: Analyzed target //package:run (1 packages loaded, 2 targets configured).
INFO: Found 1 target...
SUBCOMMAND: # //package:run [action 'Action package/logs/package.log', configuration: f6d2379e6d32ace3209294617f515fb6db597da05c6fef8607024221c1b5f9b1, execution platform: @local_config_platform//:host]
cd /d C:/users/lasenov/_bazel_lasenov/uiggnarq/execroot/__main__
powershell.exe -ExecutionPolicy Bypass -NonInteractive -NoProfile -Command & ./package/build.ps1 *>&1 | tee bazel-out/x64_windows-fastbuild/bin/package/logs/package.log -append
# Configuration: f6d2379e6d32ace3209294617f515fb6db597da05c6fef8607024221c1b5f9b1
# Execution platform: @local_config_platform//:host
INFO: From Action package/logs/package.log:
Hello world
Target //package:run up-to-date:
  bazel-bin/package/logs/package.log
INFO: Elapsed time: 0.842s, Critical Path: 0.55s
INFO: 2 processes: 1 internal, 1 local.
INFO: Build completed successfully, 2 total actions`

**Comment by tjgq** [comment]
The output of `--subcommands` is not a representation of the cache key; it's just meant to be easily copy-pastable into something you can manually run. What does `bazel aquery` say about this action? That should be closer to what's actually included.

**Comment by lyuboasenov** [comment]
Thank you guys. I figured it out, thank to your help.

Of most help was aquery command, which showed I was excluding the wrong directory from the inputs (because of a typo).

Another thing that pointed me in the right direction was tracing the bazel-remote's output. Where a build that has to be the same as previously build one was looking for non-existing hash.

It is still a mistery to me how is the bazel-remote hash calculated, but at least the current issue is resolved.

Feel free to close the issue.

Best regards,
L
