### ISSUE TITLE
[6.4.0] Bzlmod lockfile: fix pretty printing for attributes

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#19690]
### Commit IDs

d3577c96bfa3619d87b68e28c1c7fb6980bc1424

### Category

team-ExternalDeps

### Reviewers

@SalmaSamy

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/19691: https://github.com/bazelbuild/bazel/commit/d3577c96bfa3619d87b68e28c1c7fb6980bc1424.
