### ISSUE TITLE
`no-cache` action outputs are downloaded locally

### ISSUE THREAD

**Issue by BalestraPatrick** [bazelbuild/bazel#19707]
### Description of the bug:

Hello! I have a question/bug report related to the use of `no-cache` in `--modify_execution_info`.

We use this flag to speed up our builds due to the fact that in certain cases, action outputs in our builds are very big (linked artifacts, etc.) which can slow down builds. For this reason, we prefer to never cache these outputs and always compute them locally because they change very often anyway. Some examples of actions that exhibit this behavior are `CppArchive`, `ObjcLink`, `AppleLipo`, `ApkBuilder` and `JavaDeployJar`. I have recently noticed that some of our builds keep downloading from our CAS the outputs for these actions instead of respecting `no-cache`.

One example usage of this flag is the following: 
```
build --modify_execution_info=^(BitcodeSymbolsCopy|BundleApp|BundleTreeApp|DsymLipo|GenerateAppleSymbolsFile|ObjcBinarySymbolStrip|ProcessAndSign|DsymDwarf|ProtoCompile|GetPlayPlay|ObjcCombiningArchitectures|CreateAar)$=+no-remote,^(ImportedDynamicFrameworkProcessor|TestRunner|SwiftStdlibCopy)$=+no-remote-exec,^(CreateAar|ObjcLink|CppLink|BundleApp|BundleTreeApp|ProcessAndSign|DsymDwarf|ObjcBinarySymbolStrip|ObjcCombiningArchitectures|AppleLipo|CppArchive)$=+no-cache
```

As you can see, `CppArchive` is set to `no-cache`. From my understanding, this means that it should never be written to any cache. When running a build from clean local caches (no disk cache and after running `bazelisk clean --expunge`), I see that Bazel 6.3.1 still pulls down these files from the remote cache. In the gRPC log I can see the following two calls (not sure why there are two for this particular action that have only a slightly different start time):
```
metadata {
  tool_details {
    tool_name: "bazel"
    tool_version: "6.3.1-b5e0f60"
  }
  action_id: "prefetcher"
  tool_invocation_id: "4984cfe8-6be8-40a9-902e-7fddde427236"
  correlated_invocations_id: "e33c1e24-8533-4c98-b9c0-bea59f7a7f9b"
  action_mnemonic: "CppArchive"
  target_id: "//path/to/package:target_name"
  configuration_id: "7b99a97337a09fc211da50296ef8028b77fee64d3253a13b0ec5529be89c43b0"
}
status {
}
method_name: "google.bytestream.ByteStream/Read"
details {
  read {
    request {
      resource_name: "cache4/compressed-blobs/zstd/8ce0566764cdc2a2f35e5a8640a853ta0cc074615c5cee3baeaf8ea6a63c0a57/336"
    }
    num_reads: 1
    bytes_read: 145
  }
}
start_time {
  seconds: 1696279012
  nanos: 674000000
}
end_time {
  seconds: 1696279012
  nanos: 753000000
}

---------------------------------------------------------
metadata {
  tool_details {
    tool_name: "bazel"
    tool_version: "6.3.1-b5e0f60"
  }
  action_id: "prefetcher"
  tool_invocation_id: "4984cfe8-6be8-40a9-902e-7fddde427236"
  correlated_invocations_id: "e33c1e24-8533-4c98-b9c0-bea59f7a7f9b"
  action_mnemonic: "CppArchive"
  target_id: "//path/to/package:target_name"
  configuration_id: "7b99a97337a09fc211da50296ef8028b77fee64d3253a13b0ec5529be89c43b0"
}
status {
}
method_name: "google.bytestream.ByteStream/Read"
details {
  read {
    request {
      resource_name: "cache/compressed-blobs/zstd/8ce0566764cdc2a2f35e5a8640a853ta0cc074615c5cee3baeaf8ea6a63c0a57/336"
    }
    num_reads: 1
    bytes_read: 145
  }
}
start_time {
  seconds: 1696279012
  nanos: 676000000
}
end_time {
  seconds: 1696279012
  nanos: 753000000
}
```

We use the following flags which might be relevant:
```
build --experimental_remote_build_event_upload=minimal
build --remote_retries=1
build --remote_timeout=30s
build --remote_local_fallback=true
build --experimental_remote_cache_compression
build --remote_upload_local_results=false
build --incompatible_remote_results_ignore_disk=true
build --remote_download_toplevel
build --experimental_remote_cache_eviction_retries=1
build --experimental_remote_merkle_tree_cache
build --experimental_remote_merkle_tree_cache_size=2000
```

My question is, is this the expected behavior? From my understanding, some other build uploaded this action output, but even if it was, should it be downloaded instead of being automatically ignore and computed locally? We use remote execution only on macOS, so maybe that could explain why the outputs are found in the remote cache even if they are marked as `no-cache`, but we see the same behavior in other builds and platforms (Linux and Windows) that don't use remote execution.

### Which category does this issue belong to?

Local Execution, Remote Execution

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

6.3.1

**Comment by coeuvre** [comment]
The `action_id` for these two calls are `prefetcher`, I think they are fetching their inputs to local filesystem to execute locally. If these actions can run remotely, can you disable dynamic execution to check whether these two calls are gone?

**Comment by BalestraPatrick** [comment]
@coeuvre Thanks for the answer! I don't have dynamic execution enabled yet. I can see how the inputs are being fetched locally because some subsequent actions might require them, but shouldn't all `no-cache` just be computed locally instead? I'm not even sure how they can be uploaded to the remote cache if they're always marked as `no-cache` via the `modify_execution_info` flag in the first place.

**Comment by BalestraPatrick** [comment]
I'm seeing this issue in projects that don't use remote execution at all (Windows builds for example in our case), and the mnemonic is added to both `no-cache` and `no-remote`, but we still see outputs of actions being downloaded from the remote cache.

**Comment by coeuvre** [comment]
Is it fetching its inputs or its outputs being fetched by downstream actions? From the grpc logs I suspect it's the former case.

**Comment by BalestraPatrick** [comment]
How did you find out exactly from the grpc log?

**Comment by BalestraPatrick** [comment]
In a particular situation I just investigated I see that yes, inputs are being downloaded. Before building a `.exe`, all the `CppLink` inputs required are downloaded from the remote cache, even though we have `no-cache` and `no-remote` set for `CppLink`.
<img width="314" alt="Screenshot 2023-10-10 at 10 26 57 AM" src="https://github.com/bazelbuild/bazel/assets/3658887/c9ca3177-fc36-4db9-a2ce-b020b98cc45d">

**Comment by coeuvre** [comment]
Thanks for the update! `no-cache` or `no-remote` doesn't apply to the transitive closures of the actions. I guess we can close this issue?

**Comment by BalestraPatrick** [comment]
So I assume that's the expected behavior. Is there any way today to prevent that, or should this be turned into a feature request (or a new issue opened as a FR)?

**Comment by coeuvre** [comment]
I am a little bit confused. In https://github.com/bazelbuild/bazel/issues/19707#issuecomment-1754691948, are you saying that the outputs of `CppLink` actions are downloaded to build `.exe`, or inputs for `CppLink` are downloaded to run it locally?

From our conversation above, I believe it's the latter case. Then I don't understand why you want to apply `no-cache` to all upstream actions to `CppLink`.

**Comment by BalestraPatrick** [comment]
No, it's the former case. Another example I just tested which might be easier to reproduce since it shouldn't be specific to our rules. 

I run `bazel build` for an `ios_application` target and all inputs required for linking are downloaded instead of being computed locally. From my understanding, the simplified dependencies between actions is something like this: `ObjcCompile` -> `ObjcLink` -> `BundleTreeApp`

In my situation, I can see big artifacts being downloaded due to CAS hits for `ObjcLink` and `BundleTreeApp` actions, but both `ObjcLink` and `BundleTreeApp` are set to `no-remote` and `no-cache`.

**Comment by coeuvre** [comment]
That's weird. Do you have a minimal repro?

**Comment by BalestraPatrick** [comment]
@brentleyjones explained a bit better what's happening and I now understand that this is working as expected. I believe one reason for my confusion was the way our BES UI shows a "prefetcher" CAS hit for action mnemonic which we have marked as `no-cache` making it seem like it's downloading an output of it, but instead it's a required input to run that action locally.
