### ISSUE TITLE
Expose BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN through a flag

### ISSUE THREAD

**Issue by tpudlik** [bazelbuild/bazel#19714]
### Description of the feature request:

To ensure Bazel uses only hermetic, vendored C++ toolchains, and does not attempt to configure a local toolchain, you need to set the environment variable `BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN`.

This is not very ergonomic: it would be better to expose this option through a flag, so it can be set via `.bazelrc` alongside other configuration options.

In general, is there some guidance on when Bazel configuration options should be set via flags vs via environment variables?

### Which category does this issue belong to?

C++/Objective-C Rules

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 6.3.2

**Comment by benjaminp** [comment]
You can do `--repo_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1`.

**Comment by tpudlik** [comment]
Ah, I didn't know about the `--repo_env` flag!

But per the [documentation](https://bazel.build/reference/command-line-reference#flag--repo_env), the variables specified by that flag are "available only for repository rules". So I don't think this will actually affect what [cc_configure.bzl does](https://bazel.googlesource.com/bazel/+/master/tools/cpp/cc_configure.bzl#33).

**Comment by benjaminp** [comment]
> But per the [documentation](https://bazel.build/reference/command-line-reference#flag--repo_env), the variables specified by that flag are "available only for repository rules". So I don't think this will actually affect what [cc_configure.bzl does](https://bazel.googlesource.com/bazel/+/master/tools/cpp/cc_configure.bzl#33).

The linked line is inside the `cc_autoconf_toolchains` repository rule.

**Comment by tpudlik** [comment]
D'uh, good point. Thank you for the explanation!
