### ISSUE TITLE
`repository_rule` implicit attributes are missing when using `bzlmod`

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#19731]
### Description of the bug:

The [documentation for repository_rules](https://bazel.build/extending/repo#attributes) state that there are two implicit attributes added to every `repository_rule`:

> All repository_rules have implicitly defined attributes (just like build rules). The two implicit attributes are name (just like for build rules) and repo_mapping. The name of a repository rule is accessible with repository_ctx.name. The meaning of repo_mapping is the same as for the native repository rules [local_repository](https://bazel.build/reference/be/workspace#local_repository.repo_mapping) and [new_local_repository](https://bazel.build/reference/be/workspace#new_local_repository.repo_mapping).

However, if a `repository_rule` is called from a `bzlmod` extension, the following error occurs:

`ERROR: <builtin>: //private/extensions:_main~non_module_deps~io_bazel_rules_kotlin: no such attribute 'repo_mapping' in 'http_archive' rule`

### Which category does this issue belong to?

Core

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In an extension, just try and use `repo_mapping`.

```starlark
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

def _non_module_deps_impl(mctx):
    http_archive(
        name = "io_bazel_rules_kotlin",
        sha256 = "946747acdbeae799b085d12b240ec346f775ac65236dfcf18aa0cd7300f6de78",
        urls = ["https://github.com/bazelbuild/rules_kotlin/releases/download/v1.7.0-RC-2/rules_kotlin_release.tgz"],
        repo_mapping = {
            "this_will": "fail",
        },
    )

non_module_deps = module_extension(
    _non_module_deps_impl,
)
```

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 6.3.2

**Comment by Wyverald** [comment]
This is working as intended. But we should update the documentation at the very least.

**Comment by Wyverald** [comment]
the documentation has been updated.
