### ISSUE TITLE
bazel test with /dev/shm broken in bazel-0.3.2

### ISSUE THREAD

**Issue by rtsai** [bazelbuild/bazel#1973]
See issue #1917 for some context.

We have some unit tests where the code under test does:

```
shm_open(path, O_CREAT | O_EXCL | O_RDWR, S_IRUSR | S_IWUSR)
```

In bazel-0.3.1 we used bazel test --sandbox_add_path=/dev/shm , and things worked.

In bazel-0.3.2 this option was removed, presumably because everything now readable (see #1917). However, this unit test fails on Linux, where shm_open fails with EROFS. Do we have another mechanism to do what we want?

**Comment by philwo** [comment]
Hi @rtsai,

would you expect /dev/shm to be a shared directory (e.g. two sandboxed actions can see/read/write each others files in /dev/shm) or an empty tmpfs for each running action?

If an empty writable tmpfs is fine, you could try --sandbox_tmpfs_path=/dev/shm.
If you need real shared memory (which could be considered a hole in the sandbox, basically), there's unfortunately no easy workaround for now, but I could probably add one (basically bring back a flag like --sandbox_writable_path=/dev/shm).

Cheers,
Philipp

**Comment by rtsai** [comment]
I think writable tmpfs should be fine, but I don't see any option for --sandbox_tmpfs_path. Can you please clarify? I am using bazel-0.3.2 for Linux.

I did try using --spawn_strategy=standalone , and that seemed to work, although I'm not sure I want to set that for the entire test run. Is there a way to tell bazel to turn on flags on a target-by-target basis within the BUILD file itself?

**Comment by ahyangyi** [comment]
@rtsai  is `local = True` (or alternatively setting `tags = ["local"]`) in a `cc_test` what you are looking for?

https://www.bazel.io/versions/master/docs/be/common-definitions.html#common-attributes-tests

**Comment by rtsai** [comment]
local = True works for narrowing the scope of non-sandboxing for a single test. Thanks!
