### ISSUE TITLE
Bazel release process: Fix push justification.

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#19767]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/8893f2ee0efbdeb0816b13e7cb57c69d70b941c6, https://github.com/bazelbuild/bazel/commit/46404353f8295fb6306e34b7138b622b083c8ec0

### Category

team-OSS

### Reviewers

@fweikert, @keertk

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/19768: https://github.com/bazelbuild/bazel/commit/8893f2ee0efbdeb0816b13e7cb57c69d70b941c6, https://github.com/bazelbuild/bazel/commit/46404353f8295fb6306e34b7138b622b083c8ec0.
