### ISSUE TITLE
Python runtime and DYLD_LIBRARY_PATH on OSx

### ISSUE THREAD

**Issue by binuscz** [bazelbuild/bazel#1977]
I am trying to run the Magenta project on OSx using a TensorFlow with GPU acceleration and I am getting following error when the Python tries to import TensorFlow:
`
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.7.5.dylib
`

Here is more analysis:
- I am able to run all the tests using CPU only version of Tensorflow.
- I am able to run Python scripts using GPU enabled Tesorflow outside of Bazel.
- The DYLD_LIBRARY_PATH does not seem to be preserved for the Python runtime within Bazel.

From the above I assume, that the Tensorflow/Python combination works fine, but I am missing some Bazel configuration. What is the preferred way to let the Python know where to find the dylib files?

I was trying to read the documentation, but didn't find anything relevant so far. I just found out how to declare a data files, but I would rather avoid copying the whole Cuda library.

I also found how to include dylib files in CC targets, but that does not help with running Python scripts.

I also tried to disable sandboxing, using the `--spawn_strategy=standalone --genrule_strategy=standalone` flags, but that didn't help either.

More details on the environment:
- Bazel 0.3.2 (brew)
- Python 2.7.12 (brew) 
- TensorFlow 0.11.0rc0 (GPU enabled OSx version)

**Comment by binuscz** [comment]
Was able to track the issue further. It actually seems to be caused by the "env" command which is part of the execution chain and which happens to clear up both the DYLD_LIBRARY_PATH and LD_LIBRARY_PATH variables.

I have found a similar related issues with OSx El Capitan elsewhere. Is there a different solution than disable the SIP protection?

**Comment by binuscz** [comment]
Adding symlinks for the CUDA library to a more standard location seems to do the trick without disabling the SIP protection. Is this the right approach?

`ln -s /usr/local/cuda/lib/* /usr/local/lib`

**Comment by ulfjack** [comment]
+meterocloudy

**Comment by damienmg** [comment]
/cc @aehlig,

Please try to use `--action_env DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}` to the bazel command line.

**Comment by jin** [comment]
Closing as a solution has been proposed. Please ping this thread if you're still running into this issue.
