### ISSUE TITLE
bazel needs to know when to ignore .DS_Store files on Mac when globbing

### ISSUE THREAD

**Issue by dmaclach** [bazelbuild/bazel#198]
on Mac OS X
 /Users/dmaclach/src/bazel_ext/bazel/output/bazel test src:bazel fails right now because some of my directories have .DS_Store files in them. .DS_Store files are created by the Finder when going through directories. 

ERROR: /Users/dmaclach/src/bazel_ext/bazel/src/main/java/BUILD:90:12: in srcs attribute of java_library rule //src/main/java:bazel-core: file '//src/main/java:com/google/devtools/build/lib/rules/.DS_Store' is misplaced here (expected .java, .jar, .srcjar or .properties).
ERROR: /Users/dmaclach/src/bazel_ext/bazel/src/main/java/BUILD:90:12: in srcs attribute of java_library rule //src/main/java:bazel-core: '//src/main/java:com/google/devtools/build/lib/rules/.DS_Store' does not produce any java_library srcs files (expected .java, .jar, .srcjar or .properties).
ERROR: Analysis of target '//src:bazel' failed; build aborted.
INFO: Elapsed time: 0.320s

**Comment by kchodorow** [comment]
For now, you can exclude file patterns from a glob (see http://bazel.io/docs/build-encyclopedia.html#glob).

**Comment by damienmg** [comment]
Globing files wasn't supposed to exclude dotted-files by default?

**Comment by dmaclach** [comment]
Globbing explicitly does not exclude dotted-files by default.

**Comment by hanwen** [comment]
to me, this is working as intended. The original problem is that the BUILD files for Java source should add the .java extension to the glob patterns explicitly.
