### ISSUE TITLE
[Mirror] rules_python 0.26.0

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/bazel#19813]
### Please list the URLs of the archives you'd like to mirror:

Would you please add the following rules_python release to mirror.bazel.build?  Thanks!

https://github.com/bazelbuild/rules_python/releases/download/0.26.0/rules_python-0.26.0.tar.gz

Release info: https://github.com/bazelbuild/rules_python/releases/tag/0.26.0

**Comment by Pavank1992** [comment]
Hi, Please find the requested mirror artifact below:
https://mirror.bazel.build/github.com/bazelbuild/rules_python/releases/download/0.26.0/rules_python-0.26.0.tar.gz
