### ISSUE TITLE
[6.4.0] Collect debug info context from implementation deps

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#19832]
Forked from #19725

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19834

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19836
