### ISSUE TITLE
[6.4.0] cquery's config function doesn't work with Bzlmod

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#19843]
Forked from #19823

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19848 by @fmeum
