### ISSUE TITLE
[c/c++] Linux creates shared/static libraries, but macOS only static

### ISSUE THREAD

**Issue by franramirez688** [bazelbuild/bazel#19840]
### Description of the bug:

Bazel is creating static and dynamic libraries for Linux, but not for macOS. I did not check the Windows platform.
I thought this behavior would be the same for all the platforms.
So the question is: is there any param coming from the CLI that is doing that? Any default param in the toolchain/platform? Is it even a bug?

I know it's a very basic question, but I got no answer in the Bazel slack channel or Stackoverflow (searching similar questions).

Even using the flag `--dynamic_mode=off|fully`, I cannot change that behavior building the binaries.

Any help would be great!
Thanks in advance!

### Which category does this issue belong to?

C++/Objective-C Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

First of all:
```bash
$ git clone https://github.com/bazelbuild/examples.git && cd examples/cpp-tutorial/stage3
```
Where the `lib/BUILD` file looks like:
```
$ cat lib/BUILD
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "hello-time",
    srcs = ["hello-time.cc"],
    hdrs = ["hello-time.h"],
    visibility = ["//main:__pkg__"],
)
```

For macOS:
```bash
$ bazel build  //lib:hello-time
Starting local Bazel server and connecting to it...
INFO: Analyzed target //lib:hello-time (37 packages loaded, 255 targets configured).
INFO: Found 1 target...
Target //lib:hello-time up-to-date:
  bazel-bin/lib/libhello-time.a
INFO: Elapsed time: 17.702s, Critical Path: 1.01s
INFO: 3 processes: 1 internal, 2 darwin-sandbox.
INFO: Build completed successfully, 3 total actions
```

For Linux:
```bash
$ bazel build  //lib:hello-time
Starting local Bazel server and connecting to it...
INFO: Analyzed target //lib:hello-time (36 packages loaded, 157 targets configured).
INFO: Found 1 target...
Target //lib:hello-time up-to-date:
  bazel-bin/lib/libhello-time.a
  bazel-bin/lib/libhello-time.so
INFO: Elapsed time: 4.210s, Critical Path: 0.27s
INFO: 6 processes: 3 internal, 3 processwrapper-sandbox.
INFO: Build completed successfully, 6 total actions
```

### Which operating system are you running Bazel on?

macOS Sonoma 14.0 | Ubuntu 20.04.6 LTS

### What is the output of `bazel info release`?

release 6.3.2-homebrew | release 6.3.2

**Comment by pcjanzen** [comment]
Support for "nodeps" shared libraries on macOS was removed in #4341 and https://github.com/bazelbuild/bazel/commit/ec5553352f2f661d39ac4cf665dd9b3c779e614c
