### ISSUE TITLE
[7.0.0] Automatically add function transition allow list when needed

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#19854]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/bb7fb2d32f055f2a70a5ab394cf5aef29bc74b2e

### Category

team-Rules-API

### Reviewers

@comius

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/19855: https://github.com/bazelbuild/bazel/commit/bb7fb2d32f055f2a70a5ab394cf5aef29bc74b2e.

**Comment by iancha1992** [comment]
This was created as per: https://github.com/bazelbuild/bazel/issues/19493#issuecomment-1767253262
