### ISSUE TITLE
[7.0.0] Incompatible: Remove legacy allowlist names 

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#19853]
Forked from #19493

**Comment by keertk** [comment]
As per https://github.com/bazelbuild/bazel/issues/19493#issuecomment-1767253262, looks like https://github.com/bazelbuild/bazel/commit/bb7fb2d32f055f2a70a5ab394cf5aef29bc74b2e needs to be cherry-picked. Tracked here: https://github.com/bazelbuild/bazel/pull/19855
