### ISSUE TITLE
BUILD file not found

### ISSUE THREAD

**Issue by koderbober** [bazelbuild/bazel#1985]
I trying build tensorflow_demo for android with Bazel, but I get this error:

```
ERROR: no such package 'tensorflow/tensorflow/examples/android': BUILD file not found on package path.
```

I have build file in directory (MacOS):

```
 /Users/pavelgosteev/tensorflow/tensorflow/examples/android
```

build command:

```
(tensorflow) MBP-Pavel:tensorflow pavelgosteev$ bazel build //tensorflow/tensorflow/examples/android:tensorflow_demo
```

What's wrong? Why can't Bazel see build file?

**Comment by aj-michael** [comment]
It looks like you have one too many "tensorflow"s. Try:

    bazel build //tensorflow/examples/android:tensorflow_demo

**Comment by koderbober** [comment]
I'm tried:

![2016-10-25 17 33 13](https://cloud.githubusercontent.com/assets/7825231/19690445/7e9ce034-9ad9-11e6-8fd1-29ea18d26816.png)

My contents of the directories:

![2016-10-25 17 37 08](https://cloud.githubusercontent.com/assets/7825231/19690520/b20745cc-9ad9-11e6-8f45-0ba15023eaa5.png)

Where else could be the problem?

**Comment by katre** [comment]
What directory are you running this from? The error looks like it's trying
to find a file names tensorflow/tensorflow/workspace.bzl, which I can see
exists from your directory screenshot.

**Comment by koderbober** [comment]
I tried running this from default user directory and from /Users/pavelgosteev/tensorflow/ directory. I get error "The 'build' command is only supported from within a workspace." in first case and I get error "no such package 'tensorflow/tensorflow/examples/android': BUILD file not found on package path." in second case.

**Comment by ulfjack** [comment]
All the paths are supposed to be relative to a directory containing a WORKSPACE file. The latest error says '//tensorflow/tensorflow/workspace.bzl', but if there's a WORKSPACE file in /Users/pavelgosteev/tensorflow/, then that won't resolve.
