### ISSUE TITLE
[7.0.0] Drop testing on ubuntu 1804 (JDK 11) and add testing on ubuntu 2204 (JDK 17)

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#19863]
### Commit IDs

6a7e9ba0c99a41bb99239425b4cbee48b78f734d
1b7e9bdd53234cf9838afdf0b86c2753591eecaa

### Category

team-OSS, team-Rules-Java

### Reviewers

@hvadehra

**Comment by bazel-io** [comment]
Failed commmits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/6a7e9ba0c99a41bb99239425b4cbee48b78f734d
1b7e9bdd53234cf9838afdf0b86c2753591eecaa.
Please resolve manually.
cc: @bazelbuild/triage

**Comment by meteorcloudy** [comment]
Backporting at https://github.com/bazelbuild/bazel/pull/19865
