### ISSUE TITLE
git_repository rule should error if a commit attribute is fed a non-sha

### ISSUE THREAD

**Issue by petemounce** [bazelbuild/bazel#1986]
I don't think it should be legal to be able to do this - https://github.com/bazelbuild/rules_scala/pull/100/files

```
git_repository(
      name = "io_bazel",
      remote = "git://github.com/bazelbuild/bazel.git",
      commit = "0.3.1",
)
```

and for bazel to allow it without either
- throwing an error about the value of `commit` not being a valid sha
- warning the user that the value of `commit` was resolved to a particular commit from that tag (in this case `0.3.1`) within the remote - but the user should consider using the `tag` attribute instead
  - I don't really like this, since if values can be arbitrary input, they could be branches, in which case those are mutable, and guarantees of the revision from the repository evaporate.

**Comment by philwo** [comment]
Yes, that looks broken. What does this actually do at the moment? Fail in some way? Or silently treat it as a tag?

I agree that adding validation here would be good.

**Comment by petemounce** [comment]
I _think_ it silently treats it as a tag. Whatever it does, it's certainly stealthy about it :)

**Comment by kchodorow** [comment]
Yeah, based on jGit's documentation, I'm guessing this will do the same thing as `tag = "0.3.1"`.

**Comment by dslomov** [comment]
git_repository is no more
