### ISSUE TITLE
[7.0.0] Java `--add-opens` should not be passed to javac; breaks with `-Werror`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#19877]
Forked from #19876

**Comment by timothyg-stripe** [comment]
Fix should be backported from 367994ab9f3bb8d06a39d6bd0c139f00dcf47f3e

**Comment by timothyg-stripe** [comment]
@bazel-io flag

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/20016
