### ISSUE TITLE
[7.0.0] Make C++ toolchain an optional dependency of `java_binary`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#19874]
Forked from #19793

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19875

cc: @keertk
