### ISSUE TITLE
Specifying environment variables for actions?

### ISSUE THREAD

**Issue by shuzhang1989** [bazelbuild/bazel#1988]
wondering if this feature (http://www.bazel.io/docs/designs/2016/06/21/environment.html#specifying-environment-variables-for-actions) is supported now?

**Comment by damienmg** [comment]
Yes it is at head. Should be in the next release

**Comment by damienmg** [comment]
Actually it should be even in 0.3.2

**Comment by shuzhang1989** [comment]
thanks, @damienmg. I saw 0.3.2 is already released so it's already available?

**Comment by damienmg** [comment]
Yes :)
