### ISSUE TITLE
Problems when using "bazel build" to download ImageNet data

### ISSUE THREAD

**Issue by yichengwang125** [bazelbuild/bazel#1989]
Hi all,
I tried to download the Imagenet data with the code provided in Inception model, but there was a problem when I used code:
 `bazel build inception/download_and_preprocess_imagenet`
The tensorflow was installed in a Singularity container. And the environment is a high-performance cluster.
### Running Code:

```
[yichengwang125@i21a-s2 ~]$ ml load tensorflow
[yichengwang125@i21a-s2 ~]$ cd ufrc/image/image/models-master/inception/
[yichengwang125@i21a-s2 inception]$ touch WORKSPACE
[yichengwang125@i21a-s2 inception]$ DATA_DIR=$HOME/image/
[yichengwang125@i21a-s2 inception]$ bazel build inception/download_and_preprocess_imagenet
WARNING: Output base /home/yichengwang125/.cache/bazel/_bazel_yichengwang125/bad337a79300dc0e5a9ba2ac2e22c48a' is on NFS. This may lead to surprising failures and undetermined behavior.
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target... 
Target //inception:download_and_preprocess_imagenet up-to-date:
bazel-bin/inception/download_and_preprocess_imagenet
INFO: Elapsed time: 2.952s, Critical Path: 0.02s
ERROR  : Could not remove session directory /tmp/.singularity-session-4308.2575366.144117625721484141: Device or resource busy
```
### Environment info

Operating System:
Red Hat Enterprise Linux Server release 6.7 (Santiago)
### I tried to

`lsof +D /tmp/.singularity-session-4308.2575366.144117625721484141`
but only shows
`COMMAND   PID     USER             FD   TYPE    DEVICE SIZE/OFF       NODE NAME`
`java         25707  yichengwang125  7r   DIR             8,3            4096 43779163 /tmp/.singularity-session-4308.2575366.144117625721484141`
### I also tried with basic hello world code,

```
$ touch WORKSPACE
$ cat > BUILD <<'EOF'
genrule (
  name = "hello",
  outs = ["hello_world.txt"],
  cmd = "echo Hello World > $@",
)
EOF
$ bazel build :hello
bazel build :hello
ERROR  : Could not obtain shared lock on /tmp/.singularity-session-4308.2575366.144117625721484141: Resource temporarily unavailable
ABORT  : Retval = 255
```

I wonder whether this is a problem for bazel on singularity

**Comment by philwo** [comment]
For our reference, "singularity" is this software: http://singularity.lbl.gov

"Singularity enables users to have full control of their environment. This means that a non-privileged user can “swap out” the operating system on the host for one they control. So if the host system is running RHEL6 but your application runs in Ubuntu, you can create an Ubuntu image, install your applications into that image, copy the image to another host, and run your application on that host in it’s native Ubuntu environment!"

I don't think we ever tried to run Bazel in a Singularity container. However we know that there are some issues with Bazel inside a Docker container when the sandbox is enabled.

Could you please try your build like this?

```
bazel build --spawn_strategy=standalone --genrule_strategy=standalone :hello
```

The error message doesn't look like a typical sandbox issue, but this might still give us a good hint.

**Comment by yichengwang125** [comment]
```
[yichengwang125@i21a-s1 ~]$ bazel build --spawn_strategy=standalone --genrule_strategy=standalone :hello
WARNING: Output base '/home/yichengwang125/.cache/bazel/_bazel_yichengwang125/ed5e58e49c03374f184c3728cdaddbbd' is on NFS. This may lead to surprising failures and undetermined behavior.
.
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
Target //:hello up-to-date:
  bazel-genfiles/hello_world.txt
INFO: Elapsed time: 6.677s, Critical Path: 0.02s
ERROR  : Could not remove session directory /tmp/.singularity-session-4308.2575366.144117625721484141: Device or resource busy
[yichengwang125@i21a-s1 ~]$ cat bazel-genfiles/hello_world.txt
Hello World
```
I found although there is an error, the command is built first. And the result is the same is `bazel build :hello`.
But when I want to try again, it did not work any more.
```
[yichengwang125@i21a-s1 ~]$ bazel build :hello
ERROR  : Could not obtain shared lock on /tmp/.singularity-session-4308.2575366.144117625721484141: Resource temporarily unavailable
ABORT  : Retval = 255
```
And if I kill the file, and use bazel build again, it works.
```
[yichengwang125@i21a-s1 ~]$ lsof +D /tmp/.singularity-session-4308.2575366.144117625721484141
lsof: WARNING: can't stat() fuse.basemount file system /ufrc/farmerie/tgu/projects/yanfei/fastqs
      Output information may be incomplete.
COMMAND   PID           USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
java    26412 yichengwang125    7r   DIR    8,3     4096 17301627 /tmp/.singularity-session-4308.2575366.144117625721484141
[yichengwang125@i21a-s1 ~]$ kill 26412
[yichengwang125@i21a-s1 ~]$ bazel build :hello
WARNING: Output base '/home/yichengwang125/.cache/bazel/_bazel_yichengwang125/ed5e58e49c03374f184c3728cdaddbbd' is on NFS. This may lead to surprising failures and undetermined behavior.
..................
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
Target //:hello up-to-date:
  bazel-genfiles/hello_world.txt
INFO: Elapsed time: 4.567s, Critical Path: 0.03s
ERROR  : Could not remove session directory /tmp/.singularity-session-4308.2575366.144117625721484141: Device or resource busy
[yichengwang125@i21a-s1 ~]$ ls
```

**Comment by philwo** [comment]
@damienmg This is not a sandboxing bug, as it also fails with the standalone strategy. As I'll be out in January, can you find a different engineer to assign this to?

FWIW, these "ERROR : ..." messages come from Singularity, not Bazel:

```
ERROR  : Could not obtain shared lock on /tmp/.singularity-session-4308.2575366.144117625721484141: Resource temporarily unavailable
ABORT  : Retval = 255
```

and

```
ERROR  : Could not remove session directory /tmp/.singularity-session-4308.2575366.144117625721484141: Device or resource busy
```

This might well be a bug in Singularity and not Bazel.

**Comment by damienmg** [comment]
Thanks @philwo for the investigation.

@yichengwang125 have you tried running out of singularity? What is that thing even doing?

**Comment by damienmg** [comment]
@yichengwang125 I will close this issue, feel free to ping it again if you cannot find a solution.
