### ISSUE TITLE
[7.0.0] update to platforms/0.0.8

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#19896]
### Commit IDs

29985cd45fb843338b312fe0b286553b178fc4c9

### Category

team-Configurability

### Reviewers

@aiuto

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/19897: https://github.com/bazelbuild/bazel/commit/29985cd45fb843338b312fe0b286553b178fc4c9.

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19906.
