### ISSUE TITLE
ld: warning: option -noall_load is obsolete and being ignored on Mac

### ISSUE THREAD

**Issue by dmaclach** [bazelbuild/bazel#199]
When attempting to run tests for bazel on Mac OS X we get a warning about -noall_load being ignored.

/Users/dmaclach/src/bazel_ext/bazel/output/bazel test src:bazel

....
INFO: From Linking src/main/native/libunix.so:
ld: warning: option -noall_load is obsolete and being ignored
INFO: From Building src/main/java/libbazel-core.jar (1047 files):
....

**Comment by helenalt** [comment]
@dmaclach The related issue is closed. Is this still a problem? Please close if obsolete. Tx.
