### ISSUE TITLE
no-cache tag does not disable caching of genrule

### ISSUE THREAD

**Issue by srdo** [bazelbuild/bazel#19909]
### Description of the bug:

According to https://bazel.build/reference/be/common-definitions#common-attributes, setting 

```
tags = ["no-cache"]
```

on a target should disable local and remote caching for that target. This does not seem to be the case, and Bazel will cache the build artifacts. 

### Which category does this issue belong to?

Local Execution

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

BUILD
```
genrule(
  name = "test-caching",
  tags = ["no-cache"],
  outs = ["file.txt"],
  cmd_bash = "echo $$RANDOM > $@"
)
```

I would expect every invocation of `bazel build test-caching` to put a new random number in the file. Instead, the file is cached.

### Which operating system are you running Bazel on?

Ubuntu

### What is the output of `bazel info release`?

7.0.0-pre.20230926.1

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

As far as I can tell, this is not a regression. It did not work on 5.0.0 or 6.0.0 either. 

### Any other information, logs, or outputs that you want to share?

This isn't specifically about `genrule`, and I get that what this reproducer code does is silly, but it's an easy way to demonstrate that `no-cache` appears broken.

I'm trying to disable caching for Scala rules from rules_scala, which has the same behavior of caching even when `no-cache` is set, so I'm hoping it's an issue with the feature in Bazel, and not a rule-specific issue that happens to affect both `genrule` and `scala_library`.

**Comment by tjgq** [comment]
I think this is the same as #15516. tl;dr the `no-cache` tag isn't respected for the action cache, only for the disk or remote cache.

**Comment by srdo** [comment]
I think you're right. 

Running `bazel build test-caching --nouse_action_cache` repeatedly will not generate a new file for every invocation though. I need to also do `bazel shutdown` between invocations, otherwise there's some cached in-memory state that is reused, despite the flag.

I assume this is expected, and the flag only disables the on-disk action cache, and not the in-memory version?

**Comment by tjgq** [comment]
Yes, your intution is correct. There are actually three caches involved:

- Skyframe, which is purely in-memory (i.e., it does not survive a shutdown nor a `bazel clean`)
- The persistent action cache (serialized to disk but private to the Bazel workspace, can survive a shutdown, gets cleared by a `bazel clean`)
- The disk and/or remote cache (external, can be shared by multiple Bazel workspaces)

The Skyframe cache will always be hit on incremental builds and there's afaik no way to disable it. The persistent action cache can be disabled by `--nouse_action_cache`. The disk and/or remote cache can be disabled by the `no-cache` tag.

This explains why `--nouse_action_cache` is not enough (you're still hitting the Skyframe cache) but it does the job in combination with a shutdown (or a clean).

For now, we're going to treat this as a documentation bug for `no-cache`, which should explicitly state that it only applies to the disk/remote cache (I'll send a PR shortly). We'll keep https://github.com/bazelbuild/bazel/issues/15516 open while we consider how to extend the no-caching behavior to the persistent action cache and/or Skyframe (either by redefining the semantics of the `no-cache` tag, or introducing some other mechanism; we're not sure yet).

**Comment by srdo** [comment]
Sounds great, thank you. Do you need me to close this issue, or can you do it?
