### ISSUE TITLE
Disabling bzlmod leads to Java toolchain errors

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#19907]
Discovered while testing [rules_android](https://github.com/bazelbuild/rules_android). From a clean checkout, using Bazel 7.0.0rc2:
```
$ USE_BAZEL_VERSION=7.0.0rc2 bazel   build   --enable_bzlmod=false   --incompatible_enable_android_toolchain_resolution=false   --java_runtime_version=remotejdk_17   -- //src/tools/ak/generatemanifest:generatemanifest

ERROR: /usr/local/google/home/jcater/repos/rules_android/src/tools/ak/generatemanifest/BUILD:21:11: While resolving toolchains for target //src/tools/ak/generatemanifest:generatemanifest (6312974): invalid registered toolchain '@local_jdk//:bootstrap_runtime_toolchain_definition': no such target '@local_jdk//:bootstrap_runtime_toolchain_definition': target 'bootstrap_runtime_toolchain_definition' not declared in package '' defined by /usr/local/google/home/jcater/.cache/bazel/_bazel_jcater/ddb4e20e0e2e6bca92f5deeef02ce168/external/local_jdk/BUILD.bazel (Tip: use `query "@local_jdk//:*"` to see all the targets in that package)
INFO: Analyzed target //src/tools/ak/generatemanifest:generatemanifest (43 packages loaded, 6 targets configured).
WARNING: errors encountered while analyzing target '//src/tools/ak/generatemanifest:generatemanifest': it will not be built
INFO: Found 0 targets...
ERROR: command succeeded, but not all targets were analyzed
INFO: Elapsed time: 5.220s, Critical Path: 0.04s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
```

Using Bazel 7.0.0rc1 succeeds, so I suspect f79ca0275e14d7c8fb478bd910ad7fb127440fd8.

Tracing the code, I see the following:

1. [`local_java_repository` always registers a toolchain called `//:bootstrap_runtime_toolchain_definition`](https://cs.opensource.google/bazel/bazel/+/master:tools/jdk/local_java_repository.bzl;drc=f79ca0275e14d7c8fb478bd910ad7fb127440fd8;l=22)
   1. Based on the error, the `local_java_repository` for `local_jdk` doesn't actually declare this target.
3. Tracing back where `local_jdk` is actually defined is tricky:
   1. It's defined in a built-in WORKSPACE template from the Java rules: https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/bazel/rules/java/jdk.WORKSPACE.tmpl;drc=b27ca73617c5319d4b15a9e5ba499cf476679a95;l=39
   2. But the actual BUILD file is from `@rules_java_builtin`
   3. Which, without bzlmod, is from [`distdir_deps.bzl:106`](https://cs.opensource.google/bazel/bazel/+/master:distdir_deps.bzl;drc=f79ca0275e14d7c8fb478bd910ad7fb127440fd8;l=106)
   4. Which is actually [rules_java@7.0.6](https://github.com/bazelbuild/rules_java/releases/tag/7.0.6)
   5. The BUILD_FILE_CONTENTS is, finally, from [toolchains/jdk_build_file.bzl](https://github.com/bazelbuild/rules_java/blob/7.0.6/toolchains/jdk_build_file.bzl)
   6. And, sure enough, no `bootstrap_runtime_toolchain_definition` is defined there.

I don't actually know why this works with bzlmod, but it looks like we need a release of rules_java that defines `bootstrap_runtime_toolchain_definition`, and then bundle that into Bazel.

**Comment by katre** [comment]
@fmeum @cushon @hvadehra

**Comment by fmeum** [comment]
rules_android loads rules_java 6.0.0 and then registers its toolchains here: https://github.com/bazelbuild/rules_android/blob/cab8634316d4ac24c6ee291b32f8839251aae537/defs.bzl#L94.

Could you check whether removing this fixes the failure?

**Comment by katre** [comment]
Thank you. I updated to rules_java 7.0.6 in the defs and it does in fact work. Sorry for the false alarm.
