### ISSUE TITLE
[7.0.0] Upgrade to rbe_ubuntu2004

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#19902]
### Commit IDs

553c2bc904865fa94a9e077ac34d7d7147fa928d

### Category

team-OSS

### Reviewers

@meteorcloudy @coeuvre

**Comment by bazel-io** [comment]
Failed commmits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/553c2bc904865fa94a9e077ac34d7d7147fa928d.
Please resolve manually.
cc: @bazelbuild/triage

**Comment by meteorcloudy** [comment]
Already done in https://github.com/bazelbuild/bazel/pull/19868
