### ISSUE TITLE
build '--nobuild_tests_only' option doesn't seem to have desired effect

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#1991]
/CC @hanwen 

Buck supports `buck test` or `buck test --all` command that would only execute tests, without specifying the target. This wouldn't rebuild the entire world, obviously!

Unless I'm missing something the way to achieve that in Bazel is:

```
  bazel test --nobuild_tests_only //...
```

However, it doesn't seem to have the desired effect, among other all `GWT` permutations are get rebuilt (4 times, as we have 2 modes: optimized and non-optimized, compiled in 2 different modes: strict:release and non strict:development):

* ui_dbg
* ui_opt
* ui_dbg_r
* ui_opt_r

All this have absolutely nothing to do with the test execution:

```
bazel test --nobuild_tests_only //...
[...]
INFO: From GWT compiling gerrit-gwtui/ui_dbg.zip:
Compiling module com.google.gerrit.GerritGwtUI
   Computing all possible rebind results for 'com.google.gerrit.client.ui.FancyFlexTableImpl'
      Rebinding com.google.gerrit.client.ui.FancyFlexTableImpl
         Could not find an exact match rule. Using 'closest' rule <replace-with class='com.google.gerrit.client.ui.FancyFlexTableImplIE8'/> based on fall back values. You may need to implement a specific binding in case the fall back behavior does not replace the missing binding
   Compiling 5 permutations
      Compiling permutation 0...
      Compiling permutation 1...
      Compiling permutation 2...
      Compiling permutation 3...
      Compiling permutation 4...
   Compile of permutations succeeded
   Compilation succeeded -- 100.270s
Linking into /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/bazel-sandbox/8dc48de1-3d83-4e24-91ba-1490a2e96a12-47/execroot/gerrit2/bazel-out/local-fastbuild/bin/gerrit-gwtui/ui_dbg.zip.gwt_output/gerrit_ui
   Link succeeded
   Linking succeeded -- 4.505s
```

Here is the whole truth: [1].

To reproduce, clone gerrit from here: [2] and issue:

```
  bazel test --nobuild_tests_only //...
```

* [1] http://paste.openstack.org/show/587033
* [2] https://gerrit.googlesource.com/gerrit

**Comment by damienmg** [comment]
You want to build only the test you run right? Then `--build_tests_only` is the flag you should be using. `--nobuild_tests_only` is the default and build everything under the target pattern.

**Comment by davido** [comment]
Oh, right, thanks. It was even documented: [1].

```
  $ bazel test --build_tests_only //...
```

Still just saying: `bazel test` or `bazel test --all` for the same thing would be syntactic sugar.

* [1] https://gerrit.googlesource.com/gerrit/+/master/Documentation/dev-bazel.txt#158
