### ISSUE TITLE
incompatible_sandbox_hermetic_tmp

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#19915]
Historically, on Linux, Bazel mounted the host machine's `/tmp` directory into each sandbox as `/tmp`. Since each sandbox maintains its own PID namespace, this [causes problems](https://github.com/bazelbuild/bazel/issues/3236) with actions that create files in `/tmp` using only the PID as a distinguishing element of the filename, e.g. well-known sockets.

With `--incompatible_sandbox_hermetic_tmp`, Bazel creates and later cleans up a dedicated, initially empty temporary directory for each sandboxed action on Linux.

**Migration:**  
If any actions in your build depend on access to the host's `/tmp` directory, for example to exchange data with non-hermetic daemons running on the host, you can either temporarily disable this new behavior via `--noincompatible_sandbox_hermetic_tmp` (not recommended as the flag will be removed in the future) or explicitly mount the host temporary directory via `--sandbox_add_mount_pair=/tmp`.

**Comment by fmeum** [comment]
CC @lberki I created this issue to get downstream coverage. Assuming CI is green, would you support flipping this for 7.0.0?

**Comment by tjgq** [comment]
Flipping this flag SGTM. It looks like the incompatible changes pipeline didn't find any incompatibilities.
