### ISSUE TITLE
Implement Symbolic Macros

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#19922]
This issue tracks the implementation of the Symbolic Macros feature (#19921).

Currently we have an unsubmitted, rough, partial prototype. When the code matures we'll begin submitting it, tagging this issue.

Targeting EoQ4 for the prototype.

**Comment by brandjon** [comment]
This feature is set to be released (by flipping the --experimental_enable_first_class_macros flag) in 8.0. There are some remaining issues concerning how visibility is introspected in `bazel query` / `native.existing_rules()`, but now seems like an excellent time to close this long standing bug and open smaller scoped ones for individual issues.

**Comment by fmeum** [comment]
Adopting symbolic macros in `with_cfg.bzl` helped me find [existing bugs without adding new tests](https://github.com/fmeum/with_cfg.bzl/pull/137). After the bugs were fixed, converting the legacy macros generated by `with_cfg` to symbolic macros [was straightforward](https://github.com/fmeum/with_cfg.bzl/pull/138). Thanks for the great feature! Lazy expansion will be particularly useful for this use case as the generated macros can end up declaring a large number of targets.
