### ISSUE TITLE
Allow access or generation of repo mapping files in Starlark

### ISSUE THREAD

**Issue by purkhusid** [bazelbuild/bazel#19937]
### Description of the feature request:

There is currently no way to access the repo mapping file in Starlark. This causes problems when you need to make an binary that uses a runfiles libraries runnable outside of Bazel e.g. in an container or if you just want to package the binary in some way.

To make the binary runnable outside of bazel the `.repo_mapping` file is required so that runfiles lookups don't fail. That means that there needs to be an way to either generate or copy the `.repo_mapping` file in starlark so that e.g. a tar rule can list the repo mapping file in it's inputs.

There is currently an workaround for this for Python zip that is not available to others: https://github.com/bazelbuild/bazel/commit/4e60992432a49dda255eb005544ae8c03b30e243#diff-06b3fa5571583c2c73ec269859f1b9194038c26cc6c0e9c8897f53b992731658R382

This API could be publicly exposed or if it's possible the repo mapping could be exposed on the `FilesToRunProvider` like the runfiles manifest is exposed today.

Tagging @fmeum and @Wyverald since there is some context in a couple of Slack threads that they were part of:
https://bazelbuild.slack.com/archives/C014RARENH0/p1698153613312699
https://bazelbuild.slack.com/archives/CA3NW13MH/p1697050350018059?thread_ts=1697034827.979009&cid=CA3NW13MH

### Which category does this issue belong to?

Rules API

**Comment by purkhusid** [comment]
I also think that this should be solved in 7.0 since this will make migrations to bzlmod more painful.

**Comment by fmeum** [comment]
Exposing the repo mapping on `FilesToRunProvider` seems very low risk to me, but only allows you to get the repo mapping for existing executable targets, not arbitrary collections of runfiles. When packaging multiple binary targets this would require some kind of merging logic.

@purkhusid Would this be sufficient for your use case?

**Comment by purkhusid** [comment]
My exact use case i only packaging a single executable with it's runfiles so that would be sufficient for me. It could be a first step if you want to think a bit better about an public API for generating mappings files for arbitrary runfiles.

**Comment by yx-altera** [comment]
The example below fails to locate test.txt file, what to do?

```
load("@rules_python//python:defs.bzl", "py_binary")
load("@rules_pkg//:pkg.bzl", "pkg_tar")
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_push", "oci_load")

filegroup(
    name = "test_txt",
    srcs = ["test.txt"],
)

py_binary(
    name = "hello",
    srcs = ["hello.py"],
    main = "hello.py",
    data = [":test_txt"],
    deps = [
        "@rules_python//python/runfiles",
    ],
)

pkg_tar(
    name = "hello_tar",
    srcs = [":hello"],
    include_runfiles = True,
)

# Create OCI image
# https://github.com/bazel-contrib/rules_oci/blob/main/docs/image.md
# bazel build :hello_image to create.
oci_image(
    name = "hello_image",
    base = "@python_3_12",
    entrypoint = ["./hello"],
    tars = [
        ":hello_tar",
    ],
)
```

```hello.py
import os
from python.runfiles import runfiles # type: ignore


def print_locations(r: runfiles.Runfiles, path: str):
    rlocation_path = r.Rlocation(path)
    exists = rlocation_path is not None and os.path.exists(rlocation_path)
    print(f"{path=} {rlocation_path=} {exists=}")


def main():
    print("Hello, Python & Bazel! 💚")
    r = runfiles.Create()

    # print_locations(r, 'altera-team-repo-canonical-sample/python/test.txt')
    print_locations(r, 'sample/python/test.txt')
    # print_locations(r, 'python/test.txt')
    # print_locations(r, 'test.txt')


if __name__ == "__main__":
    main()
```

**Comment by fmeum** [comment]
rules_pkg only gained support for repo mapping manifests in https://github.com/bazelbuild/rules_pkg/commit/447fb8e246cb437630b9ecd09f9bf9fe857d2c3f and hasn't had a release since then. 

Cc @aiuto
