### ISSUE TITLE
[Mirror] apple_rules_lint 0.3.2

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/bazel#19930]
### Please list the URLs of the archives you'd like to mirror:

Would the team kindly mirror apple_rules_lint's 0.3.2 source archive? 

Per <https://github.com/apple/apple_rules_lint/releases/tag/0.3.2>, the URL(s) to be mirrored are

* https://github.com/apple/apple_rules_lint/archive/refs/tags/0.3.2.tar.gz

(Unfortunately there is no stable `releases/download` URL.)

Thanks!

**Comment by Pavank1992** [comment]
Please find the requested mirror artifacts below:

https://mirror.bazel.build/github.com/apple/apple_rules_lint/archive/refs/tags/0.3.2.tar.gz
