### ISSUE TITLE
Comment change in a test re-run the test

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1993]
This looks like the exact thing we should not do. I guess the jar file change because the line code information change due to encoding of debugging info.

Filing this bug as a reminder that we might want to optimize that case too.

**Comment by ulfjack** [comment]
Java by default bakes in the line information into the class files, and we use the checksum to determine whether the test needs to be rerun. The line information can affect the outcome of the test (e.g., stack traces), so I don't think we should change that.

**Comment by philwo** [comment]
Closing as WAI due to the explanation given by @ulfjack.
