### ISSUE TITLE
[Mirror] bazel-contrib/rules_jvm v0.19.0

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/bazel#19932]
### Please list the URLs of the archives you'd like to mirror:

Per <https://github.com/bazel-contrib/rules_jvm/releases/tag/v0.19.0>, would you kindly mirror the following?

* https://github.com/bazel-contrib/rules_jvm/releases/download/v0.19.0/rules_jvm-v0.19.0.tar.gz

Thanks!

**Comment by Pavank1992** [comment]
Please find the requested mirror artifacts below:

https://mirror.bazel.build/github.com/bazel-contrib/rules_jvm/releases/download/v0.19.0/rules_jvm-v0.19.0.tar.gz
