### ISSUE TITLE
Precedence of --extra_toolchains toolchains is wrong

### ISSUE THREAD

**Issue by layus** [bazelbuild/bazel#19945]
### Description of the bug:

Multiple uses of --extra_toolchains are accumulated, but due to how toolchains work, the last use does not take precendence over the first use.
Toolchains are examined in the order of their registration by the flags, and the first one that matches gets used. This makes it impossible to override a previously registered toolchain. In particular, it is impossible to override a toolchain defined in a .bazelrc file, because these are always evaluated first.

Obviously, this is also how toolchains work in WORKSPACE files, where the first one to be registered is preferred.
I would argue that this is wrong too, but it causes less trouble, because the toolchains defined in the WORKSPACE are unlikely to conflict or compete for the same platforms, and the order can be altered to make it work.

The point of --extra_toolchains however is to provide hot fixes for the build, or to tune it. These use are more likely to add competing toolchains, and the one on the command line is probably a more important fix than the one in the .bazelrc file, which in turn is probably more important than toolchains defined in the WORKSPACE.

This precedence is partially implemented, as all --extra_toolchains options take precedence over the WORKSPACE file.

See also https://github.com/bazelbuild/bazel/pull/19942#issuecomment-1779378346 for the context where I discovered the issue, and the whole https://github.com/bazelbuild/bazel/pull/19942 for a fix.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

With two compatible toolchains, add them both on the command line, and observe that the first one is preferred. There is even a test enforcing it (this is the only trace that this may be an intentional behavior):

https://github.com/bazelbuild/bazel/blob/8630b0112f05577c5d5c07800ae88f38f0dcbb91/src/test/java/com/google/devtools/build/lib/skyframe/toolchains/RegisteredToolchainsFunctionTest.java#L144-L159

### Which operating system are you running Bazel on?

irrelevant, behavior is under test

### What is the output of `bazel info release`?

irrelevant, behavior is under test

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

all recent bazel versions.

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
6c02329b1e, current master.
```

**Comment by katre** [comment]
After discussing this with the team, we think that changing `--extra_toolchains` to not accumulate values is the right way to go: in this situation, the last flag on the command line overrides all others and there's less confusion. (In general, I lean towards only using `allow_multiple` with map-type flags, not list-type, for the reasons in this report).

I'm going to generate a change and run tests on that, and I'll report back.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.0.0 RC5](https://releases.bazel.build/7.0.0/rc5/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!
