### ISSUE TITLE
7.0.0rc2 does not fail when repositories are not declared in `MODULE.bazel`

### ISSUE THREAD

**Issue by cgrindel** [bazelbuild/bazel#19956]
### Description of the bug:

In Bazel 6.4.0 with bzlmod enabled, Bazel will fail when a client does not declare all of the repositories that it directly uses. Bazel 7.0.0rc2 does not do this.

### Which category does this issue belong to?

External Dependency

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

It is easy to reproduce this error by using a repository that I created for an unrelated issue.

1. Clone [this repository](https://github.com/cgrindel/apple-toolchain-resolution-repro).
2. Comment out or remove  [the line that declares `bazel_skylib`](https://github.com/cgrindel/apple-toolchain-resolution-repro/blob/main/MODULE.bazel#L8)  in the `MODULE.bazel` file.
3. (Optional) Remove the `MODULE.bazel.lock` file.
4. Execute `bazel test //...`

Notice that the build does not fail even though `bazel_skylib` is used [here](https://github.com/cgrindel/apple-toolchain-resolution-repro/blob/main/Sources/PrintSwiftVersion/BUILD.bazel#L1).

### Which operating system are you running Bazel on?

MacOS Sonoma 14.0

### What is the output of `bazel info release`?

release 7.0.0rc2

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Yes.

**Comment by fmeum** [comment]
The 6.4.0 build does not use Bzlmod and has an empty WORKSPACE, so `bazel_skylib` isn't found as it isn't part of the WORKSPACE suffix.

The 7.0.0rc2 build uses Bzlmod (since it is enabled by default in Bazel 7), but doesn't contain a `WORKSPACE.bzlmod` file. If a repository isn't defined in `MODULE.bazel`, it is thus looked up in the WORKSPACE suffix, which as of Bazel 7 does seem to contain `bazel_skylib`:

```shell
$ bazel query //external:bazel_skylib --output=build
# /DEFAULT.WORKSPACE.SUFFIX:29:6
http_archive(
  name = "bazel_skylib",
  generator_name = "",
  generator_function = "maybe",
  urls = ["https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.4.1/bazel-skylib-1.4.1.tar.gz", "https://github.com/bazelbuild/bazel-skylib/releases/download/1.4.1/bazel-skylib-1.4.1.tar.gz"],
  sha256 = "b8a1527901774180afc798aeb28c4634bdccf19c4d98e7bdd1ce79d1fe9aaad7",
)
# Rule bazel_skylib instantiated at (most recent call last):
#   /DEFAULT.WORKSPACE.SUFFIX:29:6                                                                                                           in <toplevel>
#   /home/fhenneke/.cache/bazel/_bazel_fhenneke/3a048073ab56995a6048e1331e8bd619/external/bazel_tools/tools/build_defs/repo/utils.bzl:240:18 in maybe
# Rule http_archive defined at (most recent call last):
#   /home/fhenneke/.cache/bazel/_bazel_fhenneke/3a048073ab56995a6048e1331e8bd619/external/bazel_tools/tools/build_defs/repo/http.bzl:379:31 in <toplevel>
```

Even though this behavior is confusing, it looks like it is working as intended. If you don't want this kind of behavior, you need to create an empty `WORKSPACE.bzlmod`.

**Comment by cgrindel** [comment]
@fmeum Sorry. I failed to include the `.bazelrc` that I was using for the 6.4.0 test. I just updated the repo.

I am not familiar with the WORKSPACE suffix. However, my understanding is that it is an error to not declare repositories that are explicitly used in your workspace.

With the updated reproduction repository, if I comment out the `bazel_dep(name = "bazel_skylib", version = "1.4.2")` in `MODULE.bazel`, here is what I see

### Bazel 6.4.0

```sh
❯ USE_BAZEL_VERSION=6.4.0 bazel test //...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: a2e7275e-1b60-4239-85fc-92237d772b2f
ERROR: error loading package under directory '': error loading package 'Sources/PrintObjcVersion': Unable to find package for @[unknown repo 'bazel_skylib' requested from @]//rules:build_test.bzl: The repository '@[unknown repo 'bazel_skylib' requested from @]' could not be resolved: No repository visible as '@bazel_skylib' from main repository.
INFO: Elapsed time: 3.907s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: SimpleObjc ... (4 packages)
ERROR: Couldn't start the build. Unable to run tests
```

### Bazel 7.0.0rc2

```sh
❯ USE_BAZEL_VERSION=7.0.0rc2 bazel test //...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: f91d057f-41ca-4e9e-b4a6-bb687056ac74
INFO: Analyzed 6 targets (84 packages loaded, 784 targets configured).
INFO: Found 4 targets and 2 test targets...
INFO: Elapsed time: 3.805s, Critical Path: 0.03s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action

Executed 0 out of 2 tests: 2 tests pass.
```

My understanding is that the Bazel 6.4.0 behavior is correct. Also, as another data point, one of the recent `rules_swift_package_manager` BCR presubmit errors was due to the fact that my local and CI tests were using 7.0.0rc2 and did not complain that I was legitimately missing an external dependency in my `MODULE.bazel`.

**Comment by fmeum** [comment]
Could you check whether this reproduces after `touch WORKSPACE.bzlmod`? Without that file, the root module will see certain repositories that aren't declared in `MODULE.bazel` and the set of these repos may change with Bazel versions.

**Comment by cgrindel** [comment]
After creating `WORKSPACE.bzlmod`, it does fail under 7.0.0rc2.

```sh
❯ USE_BAZEL_VERSION=7.0.0rc2 bazel test //...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 68e0a0b5-a500-4074-9dc5-e75fe6b9bb09
ERROR: Skipping '//...': error loading package under directory '': error loading package 'Sources/PrintSwiftVersion': Unable to find package for @[unknown repo 'bazel_skylib' requested from @]//rules:build_test.bzl: The repository '@[unknown repo 'bazel_skylib' requested from @]' could not be resolved: No repository visible as '@bazel_skylib' from main repository.
ERROR: error loading package under directory '': error loading package 'Sources/PrintSwiftVersion': Unable to find package for @[unknown repo 'bazel_skylib' requested from @]//rules:build_test.bzl: The repository '@[unknown repo 'bazel_skylib' requested from @]' could not be resolved: No repository visible as '@bazel_skylib' from main repository.
INFO: Elapsed time: 2.436s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
ERROR: Couldn't start the build. Unable to run tests
```

Is this a new/intended behavior for 7.x?

**Comment by cgrindel** [comment]
Something is not adding up for me. The [presubmit failed](https://buildkite.com/bazel/bcr-presubmit/builds/2308#018b68a0-d7fb-4c67-9208-90a1b2146581) because the [test workspace](https://github.com/cgrindel/rules_swift_package_manager/tree/main/bzlmod/workspace) was missing an external dependency declaration AND the test workspace has a `WORKSPACE.bzlmod`. In theory the CI tests that were using 7.0.0rc2 should have failed. Is that correct?

**Comment by fmeum** [comment]
In the workspace you linked, the repo is brought in via a use_repo tough (line 38). Does the CI failure you linked come from a different commit?

**Comment by cgrindel** [comment]
It is fixed at HEAD. [This is the 0.18.1 version of the file](https://github.com/cgrindel/rules_swift_package_manager/blob/3fd8e7857835c89abdc28a34342119e6918e7d5e/bzlmod/workspace/MODULE.bazel).
