### ISSUE TITLE
[Mirror] add mirror for golang/tools

### ISSUE THREAD

**Issue by hawkingrei** [bazelbuild/bazel#19964]
### Please list the URLs of the archives you'd like to mirror:

github.com/golang/tools/archive/refs/tags/v0.14.0.zip

**Comment by Pavank1992** [comment]
Hi @hawkingrei, Please find the requested mirror artifact below:
https://mirror.bazel.build/github.com/golang/tools/archive/refs/tags/v0.14.0.zip
