### ISSUE TITLE
[7.0.0] 'required_providers' for an aspect does not always work together with the 'aspects' requirement on rule attributes

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#19961]
Forked from #19609

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19986
