### ISSUE TITLE
ppc64le cpu type addition, please update platforms version

### ISSUE THREAD

**Issue by sumitd2** [bazelbuild/bazel#19974]
### Description of the feature request:

A new cpu type "ppc64le" has been added to bazelbuild/platforms here: https://github.com/bazelbuild/platforms/pull/64
Can you please update the bazelbuild/platforms version in your source to 0.0.8 or later, so the new bazel version has the update?

It will fix this: https://github.com/bazelbuild/rules_go/issues/3626

### Which category does this issue belong to?

External Dependency

**Comment by sumitd2** [comment]
cc: @seth-priya

**Comment by meteorcloudy** [comment]
You should be able to upgrade `platforms` version for your own project without changing Bazel. For Bazel itself, we are already using `0.0.8` https://github.com/bazelbuild/bazel/blob/master/MODULE.bazel#L20C49-L20C49
