### ISSUE TITLE
Incremental builds fail for package names starting with .

### ISSUE THREAD

**Issue by aj-michael** [bazelbuild/bazel#1998]
I'm not sure if package names that begin with "." are allowed, but after skimming https://www.bazel.io/versions/master/docs/build-ref.html#packages I do not see anything that prohibits this. And if they aren't allowed, the clean build probably should not succeed.

```
# .a/BUILD
java_library(
    name = "a",
    srcs = [],
)
```

```
ajmichael@ajmichael1:~/playground$ bazel build //.a:a
INFO: Found 1 target...
Target //.a:a up-to-date:
  bazel-bin/.a/liba.jar
INFO: Elapsed time: 3.396s, Critical Path: 0.02s

ajmichael@ajmichael1:~/playground$ bazel build //.a:a
INFO: Found 1 target...
ERROR: Source forest creation failed: /usr/local/google/home/ajmichael/.cache/bazel/_bazel_ajmichael/0c15bb6a56c9c860e4d322469d5b7237/execroot/playground/.a (File exists).
INFO: Elapsed time: 0.141s
```

**Comment by laszlocsomor** [comment]
Looks like a bug. Thanks for reporting!

**Comment by laszlocsomor** [comment]
@aj-michael : To work around the issue, can you avoid such package names until we fix it?

**Comment by janakdr** [comment]
Comes from https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/buildtool/SymlinkForest.java#L99 . That code was written by @kchodorow . No idea how safe it is to delete.

**Comment by kchodorow** [comment]
I didn't actually write it (I've just moved it around a lot). Looks like it wasn't updated when LabelValidator started allowing dots in package names.

**Comment by ulfjack** [comment]
That code in SymlinkForest looks odd. The symlink forest is created in the exec root, which is supposedly under Bazel's control. Why should we skip certain directories at all?

**Comment by katre** [comment]
Closed for lack of activity. Please ping the reviewers to reopen if this is still a problem.
