### ISSUE TITLE
[7.0.0] unflip --repository_cache_urls_as_default_canonical_id

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#19990]
Forked from #19749

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by fmeum** [comment]
I submitted https://github.com/bazelbuild/bazel/pull/20128

**Comment by keertk** [comment]
https://github.com/bazelbuild/bazel/pull/20147
