### ISSUE TITLE
[7.0.0rc2 regression] Can't load from `@bazel_tools//tools/jdk` `.bzl` files from module extension

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#20000]
### Description of the bug:

When a module extension used with `use_extension` transitively loads from a `.bzl` file in `@bazel_tools//tools/jdk`, the load fails since `@bazel_tools` forwards to `@rules_java`, but [uses an empty repo mapping for `load`s](https://github.com/bazelbuild/bazel/blob/835512a65e97f77101af5411897a3371ec6df3fe/src/main/java/com/google/devtools/build/lib/skyframe/BzlLoadFunction.java#L947-L953).

This wasn't an issue before https://github.com/bazelbuild/bazel/commit/3029a7db8a877e8a616b2ebe304573fae9ea9962, where `@bazel_tools` did not load from an external repo.

### Which category does this issue belong to?

External Dependency

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In a `.bzl` file containing a module extension, transitively `load` from e.g. `@bazel_tools//tools/jdk:toolchain_utils.bzl`. 

Concretely, I noticed this while working on Bzlmodifying the deps of `bazel_jar_jar` in https://github.com/bazeltools/bazel_jar_jar/blob/main/jar_jar.bzl, which transitively loads `find_java_toolchain`.

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

3029a7db8a877e8a616b2ebe304573fae9ea9962

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by fmeum** [comment]
CC @meteorcloudy @Wyverald

**Comment by fmeum** [comment]
I think I have a fix for this, will submit it soon.

**Comment by keertk** [comment]
@bazel-io fork 7.0.0

**Comment by meteorcloudy** [comment]
Congrats on winning the 20k issue/pr number! 🎉 😄

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.0.0 RC5](https://releases.bazel.build/7.0.0/rc5/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!
