### ISSUE TITLE
[Mirror] 

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#20019]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/sgammon/rules_graalvm/releases/download/v0.10.3/rules_graalvm-0.10.3.zip
https://github.com/bazelbuild/apple_support/releases/download/1.8.1/apple_support.1.8.1.tar.gz

**Comment by rakshitasingh05** [comment]
Please find the mirror URLs below:

https://mirror.bazel.build/github.com/sgammon/rules_graalvm/releases/download/v0.10.3/rules_graalvm-0.10.3.zip
https://mirror.bazel.build/github.com/bazelbuild/apple_support/releases/download/1.8.1/apple_support.1.8.1.tar.gz
