### ISSUE TITLE
OpenGlES in c++ library

### ISSUE THREAD

**Issue by vardan007** [bazelbuild/bazel#2001]
I want to build c++ library and use opengles in it. 
Is this possible with bazel build system and if yes, can you please provide an example.

**Comment by laszlocsomor** [comment]
Yes, it is certainly possible.

Bazel has built-in support for C++ rules, see examples here: https://github.com/bazelbuild/bazel/tree/master/examples/cpp

To create a package for the GLES files, you may need to create a local repository using the [`new_local_repository` workspace rule](http://bazel.build/versions/master/docs/be/workspace.html#new_local_repository), and write a `BUILD` file with `cc_library` rules that export the right header files ([`cc_library.hdrs`](http://bazel.build/versions/master/docs/be/c-cpp.html#cc_library.hdrs)) and link against the right system libraries (for example [this is how you'd do that on Windows](https://github.com/bazelbuild/bazel/issues/1945#issuecomment-255723827), but the approach is the same on other platforms). I don't know if there are any other examples about this.
