### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#20026]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/0a1dce27650a233d8acb1f09a1181279f510cae8

### Category

team-ExternalDeps

### Reviewers

@meteorcloudy, @Wyverald

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20027: https://github.com/bazelbuild/bazel/commit/0a1dce27650a233d8acb1f09a1181279f510cae8.
