### ISSUE TITLE
Please ignore. This is for testing.

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#20028]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/0a1dce27650a233d8acb1f09a1181279f510cae8

### Category

team-ExternalDeps

### Reviewers

@meteorcloudy, @Wyverald

**Comment by bazel-io** [comment]
Failed commmits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/0a1dce27650a233d8acb1f09a1181279f510cae8

.
Please resolve manually.
cc: @bazelbuild/triage
