### ISSUE TITLE
User-accessible JavaInfo constructor doesn't allow changing module_flags_info

### ISSUE THREAD

**Issue by timothyg-stripe** [bazelbuild/bazel#20033]
### Description of the feature request:

The user-accessible `JavaInfo` constructor runs `_javainfo_init`, which does not allow customizing `module_flags_info`. This means that it's impossible to replicate some of the semantics of `java_info_for_compilation` that would be useful for third party rulesets (like rules_scala), like:

1. It's impossible to make `add_exports` and `add_opens` attributes for a third-party rule
2. It's impossible to merge in `runtime_deps`' `add_exports` and `add_opens`, since `_javainfo_init` only merges the module flags for `deps` and `exports`.

A few ways to resolve this are:

1. The proper fix (IMO):
    1. Add some options to the `JavaInfo` constructor, like `add_exports` and `add_opens` (for "direct" rule attributes).
    2. Change the behavior of `JavaInfo` constructor so that `add_exports` and `add_opens` are merged for `runtime_deps` in addition to just `deps` & `exports`. This is IMO the right thing to do anyway, and reduces the delta between `JavaInfo` and `java_info_for_compilation`, though it changes some user-visible behavior and probably requires an `--[no]incompatible_` flag.
2. Provide a factory function for `JavaInfo` that simply wraps a `module_flags_info`. Then, users can call `java_common.merge([JavaInfo(…), java_common.wrap_module_flags_info(…)])`.
3. Loosen `java_common.merge` input validation to allow `JavaInfo`-lookalikes rather than strictly `JavaInfo` objects. Then we can create a fake `JavaInfo` with `module_flags_info` set correctly, and call `java_common.merge` to legitimize it.
4. Expose `_java_common_internal.wrap_java_info` to users so that they can legitimize their `JavaInfo` lookalikes.

I'm happy to provide a patch. Please let me know which approach seems the most reasonable.

cc @hvadehra @cushon 

### Which category does this issue belong to?

Java Rules, Rules API

**Comment by timothyg-stripe** [comment]
I've made two PRs that implement approach 1 above:

* https://github.com/bazelbuild/bazel/pull/20036. This solves _most_ of the issue.
* https://github.com/timothyg-stripe/bazel/pull/1 (rebased on top of [#20036](https://github.com/bazelbuild/bazel/pull/20036)), which changes the behavior of JavaInfo constructor to be more like `java_info_for_compilation`.

**Comment by iancha1992** [comment]
@timothyg-stripe awesome! can you actually resubmit this https://github.com/timothyg-stripe/bazel/pull/1 against the bazelbuild repo instead of your own, so that we can assign and review it?

**Comment by timothyg-stripe** [comment]
@iancha1992 Done – I refrained from doing that at first since there's a merge conflict between the two PRs, but I can fix up the conflict later when one of the two PRs gets merged.

**Comment by timothyg-stripe** [comment]
@iancha1992 Can we backport #20035 and #20037 to 7.0?

**Comment by keertk** [comment]
Hi @timothyg-stripe would you mind just sending a PR against the release-7.0.0 branch with all the changes you need? Since we're cutting it very close to the final RC, this would save us some back and forth.
Thanks!

**Comment by keertk** [comment]
@bazel-io fork 7.0.0

**Comment by timothyg-stripe** [comment]
@keertk Done: #20260
