### ISSUE TITLE
sh_binary documentation should call out that `args` is not suported

### ISSUE THREAD

**Issue by natebosch** [bazelbuild/bazel#2004]
The [documentation ](https://www.bazel.io/versions/master/docs/be/shell.html#sh_binary) for sh_binary does not mention that args doesn't work. It is listed in the attributes line, but not in the table of arguments

The [documentation](https://www.bazel.io/versions/master/docs/be/common-definitions.html#common-attributes-binaries) for attributes common to `*_binary` rules indicates that lack of support for `args` should be explicitly called out.

I verified lack of support by writing an sh_binary with a script that only prints it's args.

**Comment by davidzchen** [comment]
I can change the documentation to call this out, though, would having support for `args` be a useful feature to have for `sh_binary`? I have verified that the internal version of `sh_binary` supports `args`.

**Comment by natebosch** [comment]
Yes, support for args would be useful if it's feasible :)

**Comment by davidzchen** [comment]
I did some testing and it seems that `args` actually does work for `sh_binary` with Bazel at HEAD:

```
❯❯❯ cat BUILD
cc_binary(
    name = "foo",
    srcs = ["foo.cc"],
    args = ["foo", "bar", "baz"],
)

sh_binary(
    name = "foosh",
    srcs = ["foosh.sh"],
    args = ["foo", "bar", "baz"],
)
❯❯❯ cat foo.cc
#include <iostream>

int main(int argc, char** argv) {
  for (int i = 0; i < argc; ++i) {
    std::cout << argv[i] << std::endl;
  }
}
❯❯❯ cat foosh.sh
#!/bin/bash

echo $@
❯❯❯ bazel run :foosh
INFO: Analysed target //src/main/java/com/google/devtools/build/foo:foosh (0 packages loaded).
INFO: Found 1 target...
Target //src/main/java/com/google/devtools/build/foo:foosh up-to-date:
  bazel-bin/src/main/java/com/google/devtools/build/foo/foosh
INFO: Elapsed time: 0.094s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action

INFO: Running command line: bazel-bin/src/main/java/com/google/devtools/build/foo/foosh foo bar baz
foo bar baz
```

Did you observe something different?

**Comment by ulfjack** [comment]
Closing per the last update from David. Feel free to reopen if you have additional comments.
