### ISSUE TITLE
Unable to build targets in go 1.21 due to new workspace mode

### ISSUE THREAD

**Issue by klosmo** [bazelbuild/bazel#20048]
### Description of the bug:

upgraded to go 1.21, now when I run `bazel build //...`, all of the external go modules my program utilizes throws errors related to the new workspace mode introduced in 1.18 https://go.dev/doc/tutorial/workspaces:

<img width="1728" alt="Screenshot 2023-10-24 at 1 15 36 AM" src="https://github.com/bazelbuild/bazel/assets/112136720/6357e7ac-9daf-443d-8873-ab73fa76d250">

I suspect, because  Bazel symlinks packages to the `/private/var/tmp/_bazel_/external/ ` directory and builds all targets from there, with the advent of go workspaces, these are deemed as external modules to my project; Thus throwing the errors because I am not using a go.work file to reference these 'external' modules.

### Which category does this issue belong to?

External Dependency

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

update go version to 1.21 then run `bazel clean` followed by `bazel sync` then finally `bazel build //...`

### Which operating system are you running Bazel on?

MacOS Sonoma / Apple M2 Pro

### What is the output of `bazel info release`?

release 6.4.0

### Have you found anything relevant by searching the web?

- https://go.dev/doc/tutorial/workspaces
- https://stackoverflow.com/questions/76302573/how-can-i-import-a-workspace-as-a-dependency-in-another-go-repository
- https://github.com/golang/tools/blob/master/gopls/doc/workspace.md

### Any other information, logs, or outputs that you want to share?

I suspect, because  Bazel symlinks packages to the `/private/var/tmp/_bazel_/external/ ` directory and builds all targets from there, with the advent of go workspaces, these are deemed as external modules to my project; Thus throwing the errors because I am not using a go.work file to reference these 'external' modules.

**Comment by meteorcloudy** [comment]
This issue should probably be filed against https://github.com/bazelbuild/rules_go

/cc @fmeum
