### ISSUE TITLE
Bazel fails silently when the experimental_downloader_config path does not exist

### ISSUE THREAD

**Issue by dieortin** [bazelbuild/bazel#20058]
### Description of the bug:

When running bazel with `experimental_downloader_config` set to an invalid path, bazel fails and returns without printing any error message. Thus, it's harder to know what went wrong.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run a build command like this:
`bazel build //some:target --experimental_downloader_config=/etc/non_existing_file.cfg`

### Which operating system are you running Bazel on?

SUSE Linux RT SP4

### What is the output of `bazel info release`?

release 6.1.2

**Comment by meteorcloudy** [comment]
@bazel-io fork 7.0.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.0.0 RC5](https://releases.bazel.build/7.0.0/rc5/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!
