### ISSUE TITLE
how to fetch all dependents but ignore some of them?

### ISSUE THREAD

**Issue by landinggao** [bazelbuild/bazel#2008]
When build tensorflow there are many out dependents need to be download from online, for some reason some of them are always failed to be downloaded in fetch command. But I can download them by browser such as Chrome directly. So I want to use command "bazel fetch" to download all except those I downloaded by browser, 
Can you pls add option to  ignore some target in bazel fetch //... command?

**Comment by laszlocsomor** [comment]
Does `bazel fetch -- @foo//...:* -@foo//bar:"` work? If not, can you give an example of what you want to fetch and what to exclude?

**Comment by landinggao** [comment]
I don't know how to apply your suggestion. My question is, when I run bazel fetch //... in tensorflow root, always has such error:

ERROR: /home/hadoop/tensorflow/tensorflow/workspace.bzl:84:3: no such package '@gmock_archive//': Error downloading from https://archive.openswitch.net/gmock-1.7.0.zip to /home/hadoop/.cache/bazel/_bazel_hadoop/688bf433e3d98b943fba735d08e17b8c/external/gmock_archive: Error downloading https://archive.openswitch.net/gmock-1.7.0.zip to /home/hadoop/.cache/bazel/_bazel_hadoop/688bf433e3d98b943fba735d08e17b8c/external/gmock_archive/gmock-1.7.0.zip: Failed to connect to https://archive.openswitch.net/gmock-1.7.0.zip : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and referenced by '//external:gtest'.

The fact is that I can download the file correctly by browser. What I want is that bazel fetch tell me what it will download, and how I can exclude some of them by options.

For example, bazel fetch //... will list targets name it will download from internet, such as @gmock_achive//...., then if it failed and I can download it from browser, then I can use options tell bazel fetch skip it.

**Comment by laszlocsomor** [comment]
I tried the following:
```
$ git checkout a901819
$ bazel fetch @gmock_archive//...
INFO: All external dependencies fetched successfully.
```

So apparently I can't repro this problem. Let's collect some information:
* which commit have you checked out for tensorflow? (run `git rev-parse HEAD` to find out)
* does this happen in a custom branch with some modifications, or do you see the fetch failure on the master branch too?
* what version of bazel are you using? (run `bazel info release` to find out)
* if you run `bazel fetch @gmock_archive//...`, do you still see the error?

> Do you mean "-@foo//bar:*" will skip the download?

Yes, that's what I was hoping. This works for `bazel build`, e.g. `bazel build -- //foo/... -//foo/bar/...` will build everything under `//foo/...` except for targets under `//foo/bar/...`. I was hoping this filtering works for `bazel fetch` too.
