### ISSUE TITLE
Ensure all GitHub workflows run with read-only permissions

### ISSUE THREAD

**Issue by pnacht** [bazelbuild/bazel#20086]
### Description of the bug:

(Sorry for not following the issue template, couldn't find one that worked for this)

Currently, two of bazel's GitHub workflows (cherry-picker.yml and remove-labels.yml) run with write-all permissions. All the other workflows already declare top-level read-only permissions and grant extra permissions at the jobs that require them.

This issue can be solved in two ways:
- add top-level read-only permissions to both workflows; and/or
- set the default token permissions to read-only in the repo settings.

I'll be sending a PR along with this issue that sets the top-level permissions. If you instead (or also) wish to modify the default token permissions:

1. Open the repo settings
2. Go to [Actions > General](https://github.com/bazelbuild/bazel/settings/actions)
3. Under "Workflow permissions", set them to "Read repository contents and packages permissions"

### Any other information, logs, or outputs that you want to share?

**Disclosure:** My name is Pedro and I work with Google and the [Open Source Security Foundation (OpenSSF)](https://www.openssf.org/) to improve the supply-chain security of the open-source ecosystem.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.0.0 RC5](https://releases.bazel.build/7.0.0/rc5/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!

**Comment by varunsh-coder** [comment]
Hi @pnacht, I saw this issue mentioned in this blog post https://cycode.com/blog/cycode-discovers-a-supply-chain-vulnerability-in-bazel/

Wanted to mention that those jobs were already running the harden-runner GitHub Action. 
https://github.com/bazelbuild/bazel/actions/runs/7745839239/workflow#L20-L23
https://github.com/bazelbuild/bazel/blob/master/.github/workflows/remove-labels.yml#L16-L19

You can view outbound calls made by that workflow for past runs to confirm no unexpected calls/ exfiltration attempts happened. 
https://app.stepsecurity.io/github/bazelbuild/bazel/actions/runs/7741733879

I looked it up and only calls to these destinations have been observed in the last 240 odd runs. 
api.github.com:443
files.pythonhosted.org:443
github.com:443
pypi.org:443
