### ISSUE TITLE
new_git_repository fails to create symlink if git repo has a build folder

### ISSUE THREAD

**Issue by Lunarsong** [bazelbuild/bazel#2010]
I'm using new_git_repository to get an external repo and I am getting the following error:

```
ERROR: /Users/shanee/Projects/Game/engine/BUILD:1:1: no such package '@glew//': Error creating symbolic link from /private/var/tmp/_bazel_shanee/ff5870c5807ad12b64add05bad17357f/external/glew/BUILD to /Users/shanee/Projects/Game/glew.BUILD: /private/var/tmp/_bazel_shanee/ff5870c5807ad12b64add05bad17357f/external/glew/BUILD (Directory not empty) and referenced by '//engine:engine'.
ERROR: Analysis of target '//game:game' failed; build aborted.
```

My WORKSPACE rule:

```
new_git_repository(
    name = "glew",
    remote = "https://github.com/nigels-com/glew.git",
    commit = "013667e3e16b9b5bcad06913aaf9837dc487febb",
    init_submodules = 0,
    build_file = "glew.BUILD",
)

```

And build file:

```
cc_library(
    name = "glew",
    includes = ["include"],
    srcs = [
        "src/glew.c",
    ],
    hdrs = [
        "include/GL/glew.h",
        "include/GL/eglew.h",
        "include/GL/glxew.h",
        "include/GL/wglew.h",

    ],
    defines = [
        "GLEW_STATIC",
    ],
    visibility = ["//visibility:public"],
)
```

I assume it is because he repository https://github.com/nigels-com/glew already has a folder named "build".

**Comment by nigels-com** [comment]
It's been there since 2003.  Is there some other name that makes more sense? (Probably not!)

**Comment by Lunarsong** [comment]
buildfiles seems to work nicely. By the way, seems like glew.c and other files are missing on latest commit? The structure seems different from the .zip from sourceforge and documentation builds are failing.

**Comment by miuliano** [comment]
Kind bizarre, but I just ran into the exact same thing today trying to use Bazel to build GLEW. In my case it's due to macOS case-insensitivity. Not sure what the status is on a fix (#297, #301)?

**Comment by Lunarsong** [comment]
@miuliano if you need a quick fix, link against https://github.com/Lunarsong/glew.git for now.

```
new_git_repository(
    name = "glew",
    remote = "https://github.com/Lunarsong/glew.git",
    commit = "a38094b249974f219f9c23f54b5b60a620777a13",
    init_submodules = 0,
    build_file = "glew.BUILD",
)
```

However it's best to have a proper fix for this.

**Comment by nigels-com** [comment]
Concerning building GLEW from git repository.  The current advice is to build from the (tested) release snapshot, rather than the (work in progress) master branch.  It's old-school, I know, but GLEW is fairly old!

https://sourceforge.net/projects/glew/files/glew/2.0.0/glew-2.0.0.tgz/download

**Comment by laszlocsomor** [comment]
The problem isn't that there's a `build` directory, it's that the files referenced in the `BUILD` file do not exist in the repo (because they are Make targets), so Bazel cannot bind them. The solution is indeed linking again @Lunarsong's repo (described in https://github.com/bazelbuild/bazel/issues/2010#issuecomment-257132771).

**Comment by Lunarsong** [comment]
Can keep this closed, however there is an alternative solution which I plan on trying.

Using a generic build to run `make extensions `, which will return the relevant files as output, which will be used to build the actual library.
