### ISSUE TITLE
bazel_worker_test is failing at Bazel@HEAD in CI

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#20102]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3445#018bacb6-59f8-49b8-af10-8f283ad1c2fd

Platform : MacOS

Logs:
```
//src/test/shell/integration:bazel_worker_test                           FAILED
```

CC Greenteam @Wyverald

**Comment by meteorcloudy** [comment]
This is likely to be flaky, retrying at https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3445#018bb45e-811d-47b7-aa80-2e11527bdcb5

**Comment by Wyverald** [comment]
seems the retry succeeded. closing until this flares up again
