### ISSUE TITLE
[7.0.0] Update the .bazelversion and support matrix for 6.4.0

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#20119]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/ab0e7a133c37ac1055c6fba0fbb7a85a8970e5d9

### Category

team-OSS

### Reviewers

@meteorcloudy

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20120: https://github.com/bazelbuild/bazel/commit/ab0e7a133c37ac1055c6fba0fbb7a85a8970e5d9.
