### ISSUE TITLE
[Mirror] bazel-gazelle 0.34.0

### ISSUE THREAD

**Issue by tyler-french** [bazelbuild/bazel#20112]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.34.0/bazel-gazelle-v0.34.0.tar.gz

**Comment by keertk** [comment]
@tyler-french here it is - https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.34.0/bazel-gazelle-v0.34.0.tar.gz
