### ISSUE TITLE
move bazel cache

### ISSUE THREAD

**Issue by vladfi1** [bazelbuild/bazel#2012]
The bazel cache in `~/.cache/bazel` uses up a lot of space, which is a problem since my home dir quota is quite small. I'd like to put the cache in a different place (where I have more space), but this doesn't seem possible. If I use a symlink I get strange errors of the form `error: unexpected result from F_SETLK: Function not implemented` when trying to run bazel.

**Comment by laszlocsomor** [comment]
You can use the [`--output_user_root`](https://www.bazel.io/versions/master/docs/bazel-user-manual.html#flag--output_user_root) startup option to change the location of that directory.
