### ISSUE TITLE
ERROR Lock file is no longer up-to-date with Bazel@HEAD in Downstream 

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#20139]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3450#018bb763-b41d-439d-a82f-10a09269747a

Platform : MacOS, Ubuntu, Windows

Logs:
```
ERROR: Lock file is no longer up-to-date because: The implementation of the extension 'ModuleExtensionId{bzlFileLabel=@rules_python~0.26.0//python/extensions/private:internal_deps.bzl, extensionName=internal_deps, isolationKey=Optional.empty}' or one of its transitive .bzl files has changed. Please run `bazel mod deps --lockfile_mode=update` to update your lockfile.
```

CC Greenteam @Wyverald

**Comment by meisterT** [comment]
cc @SalmaSamy

**Comment by Wyverald** [comment]
@meteorcloudy this is due to us turning on `--lockfile_mode=error` in CI, and `rules_python`'s module extension being a platform-dependent one. A tricky problem to solve indeed.

**Comment by meteorcloudy** [comment]
I tried to turn off lockfile for downstream pipeline jobs in https://github.com/bazelbuild/continuous-integration/pull/1775, but apparently it didn't work. I'll take a look today.

**Comment by meteorcloudy** [comment]
Hopefully this should be fixed by https://github.com/bazelbuild/continuous-integration/pull/1781

**Comment by meteorcloudy** [comment]
Should be fixed now: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3458
