### ISSUE TITLE
More files are being compiled than necessary. Any tips?

### ISSUE THREAD

**Issue by ahyangyi** [bazelbuild/bazel#2014]
My users report that `bazel build` seems to be rebuilding files that's obviously unnecessary to rebuild. For example, modifying a C++ source file should not require rebuilding other C++ source files at all.

I am not sure if that's a known bug in Bazel 0.3.1, or it's my configuration of the C++ toolchain is inefficient (that is, I filled `False` for most boolean questions for my toolchain, even if some of them could actually be `True`). Do you have any hint or past experience in this issue?

Since we use CUDA, some files take really terribly long time to recompile, and as a result we really which to recompile as little as possible.

**Comment by laszlocsomor** [comment]
I'd look at the rules first, not the toolchain. What rules are you using, standard `cc_library` or some custom rules/macros? If the latter, it could be the case that the implementation is inefficient and it compiles the C++ files in a monolythic action rather than creating a separate compilation action for each. This typically happens if the macro expands to `native.genrule` with `srcs = <all C++ files>`.

**Comment by ahyangyi** [comment]
I always use `cc_library` when compiling C/C++/CUDA sources. There are indeed some custom rules, but they only use actions to do customized linking and/or stripping. All compiling work is delegated to `cc_library`s.

**Comment by ahyangyi** [comment]
I also noticed that I am using aspects to export headers of each `cc_library`. Regular fragments only provide recursive headers, while I needed unrecursive ones as a syntactic sugar for people to specify which headers to release. Maybe that's the issue?

The following is a simplified version of the rules I have:
```
def _direct_headers_aspect(target, ctx):
    hdrs = [f for hdrs in ctx.rule.attr.hdrs for f in hdrs.files]

    return struct(
        cc_library_extras = struct(
            direct_headers = hdrs,
            )   
        )   

direct_headers_aspect = aspect(
    implementation = _direct_headers_aspect,
)

def _cc_custom_library_impl(ctx):
    # Part 1: build a shared library using custom rules
    // initialize variables toolchain_files, output, libraries, gcc_command
    ctx.action(
        inputs=list(toolchain_files) + list(libraries),
        outputs=[output],
        progress_message="Linking %s..." % output.path,
        executable = gcc_command,
        arguments = ...,
        )
    # Part 2: build a tarball of all headers of dependended cc_libraryes, non-recursively
    build_tar = ctx.executable._build_tar
    header_tar = ctx.outputs.header_tar

    headers = [f for d in deps for f in d.megvii_lib.direct_headers]
   // some code to build arg_file here
   ctx.action(
       executable = build_tar,
       arguments = ["--flagfile=" + arg_file.path],
       inputs = [arg_file] + headers,
       outputs=[header_tar],
       mnemonic="PackageTar"
       )

_cc_custom_library = rule(
    implementation = _cc_custom_library_impl,
    attrs = {
        "deps": attr.label_list(aspects = [direct_headers_aspect]),
        "_toolchain": attr.label(default = ......)),
        "_build_tar": attr.label(
            default=Label("@bazel_tools//tools/build_defs/pkg:build_tar"),
            cfg=HOST_CFG,
            executable=True,
            allow_files=True),
        },
    outputs = {
        "out": "lib%{name}.so",
        "header_tar": "%{name}_headers.tar",
        },
    fragments = [
        "cpp",
        ],
)

def cc_custom_library(name, deps = [], .........):
   interna_cc_library_name = name + ".internal"
   native.cc_library(
       name = internal_cc_library_name,
       ........
       )
   _cc_custom_library(
       name = name,
       deps = deps + [internal_cc_library_name],
       ....
       )
```

**Comment by laszlocsomor** [comment]
@mhlopko : could you take a look please?

**Comment by mhlopko** [comment]
Hi Yi Yang!

hmmm nothing bad rings the bell when I'm reading this. I would be surprised if it was because of the toolchain configuration. Were you able to reproduce extra compilation actions yourself? Could you maybe assemble a small (but complete) project that will expose the issue?

Thanks!

**Comment by ahyangyi** [comment]
@mhlopko Yeah, that's my plan on this issue too. I'll try to create a minimal but complete project that exposes the problem on Github and then report back.

**Comment by mhlopko** [comment]
Wonderul! Thank you so much!

**Comment by ulfjack** [comment]
Please reopen if you have a smaller repro.

**Comment by ahyangyi** [comment]
Yeah, sorry for this long delay. I'll touch this problem after finishing other stuff at my hands.
