### ISSUE TITLE
File attributes like (executable bit) are not part of the cache digest

### ISSUE THREAD

**Issue by nikhilkalige** [bazelbuild/bazel#20148]
### Description of the bug:

The cache entry doesn't account for the executable bits of the file, causing the cache poisoning. 

Here's the scenario of what happened.
```
filegroup(scripts, srcs = ['a.sh'])
create_tarball(image, srcs = [scripts, more apps etc])
```
- User created `a.sh` without `+x`, `bazel build image`, copied the tar to the system, realized `a.sh` is not executable.
- User then `chmod +x a.sh; bazel build image`, copied the tar and saw that `a.sh` is still not an executable
- User did `bazel clean` no change, `bazel clean --expunge` and they complained it's still not working

Since the image was cached in the first step, the change to the executable bit was not recognized the build.

Bazel version: release 7.0.0-pre.20230123.5- (@non-git)

Slack conversation, with the same information as above https://bazelbuild.slack.com/archives/CA31HN1T3/p1699596635216589

**Comment by benjaminp** [comment]
#3400

**Comment by nikhilkalige** [comment]
@benjaminp Thank you.. Going to close this duplicate
