### ISSUE TITLE
[7.0.0] Do not do magic to achieve a hermetic /tmp when the sandbox is hermetic

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#20144]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/491284b0c782e0df25dd0a8bc921a9c2de0e6881

### Category

team-Local-Exec

### Reviewers

@keertk

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20145: https://github.com/bazelbuild/bazel/commit/491284b0c782e0df25dd0a8bc921a9c2de0e6881.

**Comment by keertk** [comment]
Context: https://github.com/bazelbuild/bazel/pull/20136#issuecomment-1806281035
