### ISSUE TITLE
incompatible_multi_release_deploy_jars

### ISSUE THREAD

**Issue by cushon** [bazelbuild/bazel#20159]
Multi-Release jar files were introduced in JDK 9 by [JEP-238](https://openjdk.java.net/jeps/238). The feature allows a library jar to provide different implementations for its interface for different Java major versions.

To enable the feature, a jar adds the following entry to its `META-INF/MANIFEST.MF`:

```
Multi-Release: true
```

And includes the version-specific implementation classes under a special `META-INF/versions` directory:

```
jar root
  - A.class
  - B.class
  - C.class
  - D.class
  - META-INF
     - versions
        - 9
           - A.class
           - B.class
```

Java applications can be deployed by packaging the application into a single `_deploy.jar`. Currently any `Multi-Release:` manifest entries in dependencies are ignored. The Bazel Java rules do not yet support creating multi-release jars directly, but when importing a third party multi-release jar using `java_import` and creating a deploy jar, the multi-release functionality is disabled and the default version is used.

Flipping `--incompatible_multi_release_deploy_jars` adds support for packaging prebuilt multi-release jars into `_deploy.jar`s, by unconditionally enabling setting `Multi-Release:` in the output manifest. This ensures that `_deploy.jar`s that transitively depend on a multi-release jar use the correct implementation of the library, and that multi-release behaviour is the same between tests and production.

Note that this enables multi-release functionality for more `_deploy.jar`s than actually need it. The number of `_deploy.jars` that will require this functionality is expected to increase over time: as soon as a widely used library starts using the feature, every `_deploy.jar` that transitively depends on that library will need to be a multi-release jar, so the benefit of only enabling the feature where necessary would decrease over time.

See also https://github.com/bazelbuild/bazel/issues/10507, https://github.com/bazelbuild/bazel/issues/10507.

**Comment by fmeum** [comment]
@cushon Are you aware of any realistic case in which this could be breaking? If not, maybe this could even be flipped for Bazel 7.

**Comment by cushon** [comment]
cc @hvadehra 

> @cushon Are you aware of any realistic case in which this could be breaking? If not, maybe this could even be flipped for Bazel 7.

We flipped this for Blaze last year and as far as I know didn't cause any problems, I think that considering it for Bazel 7 makes sense.

**Comment by davido** [comment]
> Flipping --incompatible_multi_release_deploy_jars adds support for packaging prebuilt multi-release jars into _deploy.jars, by unconditionally enabling setting Multi-Release: in the output manifest.

Why it's enabling "Multi-Release: true" unconditionally output manifest of `_deploy.jar`. ? Why not just look into the source jar and enable `Multi-Release` bit if and only if at least one of the source JAR has "Multi-Release:" bit set in its Manifest file?

**Comment by cushon** [comment]
> Why not just look into the source jar and enable `Multi-Release` bit if and only if at least one of the source JARs has "Multi-Release:" bit set in its manifest file?

There's a convention that the manifest file appears at the beginning of the jar, and singlejar processes its inputs once in a single pass for performance reasons. I considered writing the manifest and then back-patching it to set `Multi-Release` after reading the inputs, but it would have complicated the implementation. The current approach doesn't have any downsides that we ran into in practice.

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by keertk** [comment]
@bazel-io fork 7.0.0

**Comment by sgammon** [comment]
This was performed, right? Can this be closed?
