### ISSUE TITLE
[7.0.0] Make the BesUploadMode per transport instead of per invocation.

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#20169]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/353000ebc512e4f1654d123713b003011751e07e

### Category

team-Remote-Exec

### Reviewers

@coeuvre

**Comment by coeuvre** [comment]
I will manually create the cherrypick PR.

**Comment by keertk** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/20170
