### ISSUE TITLE
Declared providers don't work with aspects

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#2016]
Aspects still want structs:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/skyframe/SkylarkAspectFactory.java#L81

In contrast to configured targets, which can take lists:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/SkylarkRuleConfiguredTargetBuilder.java#L308

So for now, `java_lite_proto_library` will be implemented with string keys. It's easy to refactor, so it's not that big of a deal.

/cc @iirina

**Comment by lberki** [comment]
As a sidenote, returning declared providers from aspects in the `providers` field of the returned struct doesn't work either.

**Comment by dslomov** [comment]
Right, we already have an internal bug on this
