### ISSUE TITLE
[7.0.0] [Skymeld] Don't plant the symlinks to the paths specified in `.bazelignore`

### ISSUE THREAD

**Issue by joeleba** [bazelbuild/bazel#20167]
### Commit IDs

caf1702ce9fa060169548181afb9e19956826f0b

### Category

team-Performance

### Reviewers

@meisterT

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20168: https://github.com/bazelbuild/bazel/commit/caf1702ce9fa060169548181afb9e19956826f0b.
