### ISSUE TITLE
can not import tensorflow build from source

### ISSUE THREAD

**Issue by JunhongXu** [bazelbuild/bazel#2017]
When I import tensorflow, i get this error:

> 
ImportError: /home/jxu7/anaconda2/envs/tensorflow/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/jxu7/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so)

> 

Any suggestions to this issue??

**Comment by laszlocsomor** [comment]
Which version of bazel are you using? (`bazel info release`)
Which commit of tensorflow do you have checked out?
Which version of gcc do you have installed?

**Comment by JunhongXu** [comment]
Uh.. It occurs to me that I did not install libgcc in my conda environment. Just did a conda install libgcc solved problem. 

Thank you.

**Comment by laszlocsomor** [comment]
Cool, thanks for getting back to us! Glad it works.
