### ISSUE TITLE
7.0.0: Cannot build airgapped archives.tar

### ISSUE THREAD

**Issue by ldiamand42** [bazelbuild/bazel#20179]
### Description of the bug:

In 6.4.0 I can build the dist files needed for an airgapped build with this:

    bazel build @additional_distfiles//:archives.tar

https://bazel.build/run/build#running-bazel-airgapped

In 7.0.0 it fails:

    ERROR: Skipping '@additional_distfiles//:archives.tar': No repository visible as '@additional_distfiles' from main repository

The target is in the workspace file and has been deleted.

### Which category does this issue belong to?

Core

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build from source:

    bazel build @additional_distfiles//:archives.tar

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 6.4.0

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
https://github.com/bazelbuild/bazel
2482322fedb463e0bbecd29c5e8e6d0f087ed884
e3ab08195131b4b2db012ec7430a053f3c581213
```

### Have you found anything relevant by searching the web?

No.

**Comment by sluongng** [comment]
@meteorcloudy could this be related to https://github.com/bazelbuild/bazel/commit/c1f2afff305f5dec67f2a5bc0d8bccf7916c5e82?

**Comment by luked99** [comment]
Could it be that I should now be using `bootstrap_repo_cache` ?

**Comment by meteorcloudy** [comment]
We have removed `@additional_distfiles` since we migrated Bazel itself to be built with Bzlmod.

Now you need to build  `"@bazel_tools_repo_cache//:files"` (for bazel_tools builtin module with Bzlmod enabled) and `@workspace_repo_cache//:files` (for legacy WORKSPACE suffix) and it will populate your repository cache so that you don't have to access the internet. In addition, if you are using Bzlmod, you probably want a local copy of BCR so that Bazel won't try to access BCR during dependency resolution.

I'll update https://bazel.build/run/build#running-bazel-airgapped

**Comment by luked99** [comment]
Struggling to get this to work!

I built bazel as normal, and then built @bazel_tools_repo_cache//:files. Then I grabbed the repo-cache files and put them somewhere safe.

In a fresh copy of the bazel source tree I then did a second build, but this time with:

    --experimental_downloader_config=bazel_downloader.cfg
    build --repository_cache=/path/to/repo-cache

And `bazel_downloader.cfg` looks like:

    allow bcr.bazel.build
    block *

It fell over immediately trying to find `rules_python`. Strace seems to think that it never even looks at the repo cache.

**Comment by RoshithaB** [comment]
It'd be great if the page https://bazel.build/run/build#running-bazel-airgapped can be updated making it useful for Bazel 7.0.

**Comment by RoshithaB** [comment]
I'm still using WORKSPACE and I'm getting the following error when followed the steps provided in the above document link.
`ERROR: The repository's path is "/usr/local/kythe" (absolute: "/usr/local/kythe") but it does not exist or is not a directory.`

Can you please provide if there is something missing?
