### ISSUE TITLE
Add `--enable_workspace` flag (defaulting to true) to allow turning off WORKSPACE logic

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#20185]
Setting this flag to false should turn off all WORKSPACE related logic, including evaluating the WORKSPACE/WORKSPACE.bazel/WORKSPACE.bzlmod files at all, any WORKSPACE prefixes/suffixes, the `LocalRepositoryLookupFunction` (with some sort of replacement).

A blocker for this issue would be #18285; we currently still don't have a way to specify a `local_repository`/`new_local_repository` in a module extension.

**Comment by iancha1992** [comment]
@bazel-io fork 7.1.0
