### ISSUE TITLE
[7.0.0] Polish lockfile error message

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#20190]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/65f847a0103329f684e4313d49154583de15d164

### Category

team-ExternalDeps

### Reviewers

@SalmaSamy

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20191: https://github.com/bazelbuild/bazel/commit/65f847a0103329f684e4313d49154583de15d164.
