### ISSUE TITLE
[7.0.0] Fix read-only permissions on tree artifact subdirectories before moving them out of the sandbox

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel#20194]
### Commit IDs

547f0c6955942e6aafd279adbb2f5368a7a2347e

### Category

team-Performance

### Reviewers

@meisterT

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20195: https://github.com/bazelbuild/bazel/commit/547f0c6955942e6aafd279adbb2f5368a7a2347e.
