### ISSUE TITLE
[7.0.0] Flip --incompatible_multi_release_deploy_jars

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#20207]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/1d7af7ea70c2a08c90f7ebb34b24172fb1a44298

### Category

team-Rules-Java

### Reviewers

@hvadehra

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20208: https://github.com/bazelbuild/bazel/commit/1d7af7ea70c2a08c90f7ebb34b24172fb1a44298.
