### ISSUE TITLE
How to build with libraries like 'libmysqlclient' or 'openssl'?

### ISSUE THREAD

**Issue by ryancheung** [bazelbuild/bazel#2020]
I have a project which dependents on `libmysqclient` and `openssl`.  

If build with cmake, I can use functions like `find_library` to find system level `libmysqclient` or `openssl`.

But with bazel, I think I have to manually create a cross platform BUILD file for `mysql` or `openssl`. But this seems impossible for me since they have their own config/build script(configure/make). 

So I want to know, how `bazel` handle dependencies reside in operation system, or how `bazel` handle dependencies that their building process is written in another away that can not be converted to `bazel`'s BUILD file.

**Comment by laszlocsomor** [comment]
Currently Bazel doesn't understand makefiles or any other build system's build files. This means you need to create a BUILD file for the projects you need to depend on. I can think of the following solutions:

1. The easy way is to build binaries / shared libraries of `libmysqlclient` and `openssl` using their respective build pipeline (make, cmake, etc.), and create a minimal BUILD file that just wraps the build outputs as if they were source files, see [`cc_library.srcs`](https://bazel.build/versions/master/docs/be/c-cpp.html#cc_library.srcs). This is easy but every time you check out a new version of the dependencies, you need to rebuild the binary / shared library.

1. A variation of the (1) approach is to create a directory in your workspace with symlinks that point to the system-default libraries, and a BUILD file with a similar `cc_library` or whatever rule as in the previous approach. Alternatively you can create this directory anywhere on the filesystem, and add a [`local_repository`](https://bazel.build/versions/master/docs/be/workspace.html#local_repository) rule to your `WORKSPACE` file to import it.

1. The hard way is to create a complete BUILD file to build those projects from source. This is the perfect long-term solution, but it's usually non-trivial to do so it shouldn't be a burden of you who wants to use the library but the authors of those libraries.

**Comment by laszlocsomor** [comment]
For the record we are working on tools to make the 3rd approach drastically easier, but it's not done yet.

**Comment by laszlocsomor** [comment]
@jin to comment

**Comment by ryancheung** [comment]
@laszlocsomor Thanks for the help. And I'm excited that you're working on 3rd approach. Thanks very much!

**Comment by petroseskinder** [comment]
Expanding on @laszlocsomor's comment, the tool we are building is intended to automate writing a project's BUILD files. You provide it a binary (and some other pieces of information). It outputs the BUILD files in the appropriate directories. For the near future, we are restricting its input to java binaries (in the form of jars), but we will soon expand to other types of binaries.

**Comment by jin** [comment]
@ryancheung A concrete example of @laszlocsomor's 1st approach can be seen in the Rust rule implementations, where the Rust (precompiled) toolchain is downloaded and specified in a BUILD file. https://github.com/bazelbuild/rules_rust/blob/master/rust/rust.bzl#L690

**Comment by ryancheung** [comment]
@jin Very helpful, Many thanks!

**Comment by ryancheung** [comment]
Here's how I use @laszlocsomor's 1st approach to use system `openssl`:

WORKSPACE:
```
new_local_repository(
    name = "openssl",
    path = "./dep/openssl",
    build_file = "openssl.BUILD",
)
```

openssl.BUILD:
```
cc_library(
    name = "openssl",
    srcs = glob(["lib/*.so", "lib/*.dylib"]),
    hdrs = glob(["include/**/*.h"]) + ["include/dummy.h"],
    includes = ["./include"],
    visibility = ["//visibility:public"],
)

cmdStr = """
OPENSSL_ROOT=$$(dirname "$(location find_openssl.rb)")
pushd $${OPENSSL_ROOT}
ruby find_openssl.rb
popd
touch $(location include/dummy.h)
"""

genrule(
    name = "find_openssl",
    srcs = [],
    outs = ["include/dummy.h"],
    tools = ["find_openssl.rb"],
    cmd = cmdStr,
)
```

.dep/openssl/find_openssl.rb:
```ruby
#!/bin/bash ruby

include_paths = ["/usr/include", "/usr/local/include", "/usr/local/opt/openssl/include"]

found_include_path = nil
include_paths.each do |path|
  ret = Dir[File.join(path, "openssl")]
  if !ret.empty?
    found_include_path = ret[0]
  end
end

if found_include_path
  `mkdir -p include`
  `cp -r #{found_include_path} include/`

  puts "openssl include found."
end

lib_paths = ["/lib", "/lib/x86_64-linux-gnu", "/usr/lib", "/usr/lib/x86_64-linux-gnu", "/usr/local/opt/openssl/lib"]

found_lib_path = nil
lib_paths.each do |path|
  ret = Dir[File.join(path, "libssl.dylib"), File.join(path, "libssl.so")]
  if !ret.empty?
    found_include_path = ret[0]
  end
end

if found_include_path
  `mkdir -p lib`
  `cp -r $(dirname #{found_include_path})/libssl.dylib lib/`
  `cp -r $(dirname #{found_include_path})/libcrypto.dylib lib/`
  `cp -r $(dirname #{found_include_path})/libssl.so lib/`
  `cp -r $(dirname #{found_include_path})/libcrypto.so lib/`

  puts "openssl lib found."
end
```

This approach seems feasible. Basically I make a script to find system `openssl` and copy them to `bazel` using `genrule`, and then wrap them as a library.

Hope this would help if anyone have the same trouble as me.
