### ISSUE TITLE
Zipper produces archives that java compiler doesn't understand

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#2021]
`Zipper` seems to add '.\\' prefixes for each entry. This confuses the java compiler and putting such an artifact on the class path doesn't work, the resources are not found.

To reproduce, replace in this CL: [1] `zip` with `zipper here, the subsequent call to `javac` cannot find the resources any more.

* [1] https://gerrit-review.googlesource.com/#/c/90412/1/gerrit-gwtui/gwt.bzl@106

**Comment by laszlocsomor** [comment]
@damienmg commented on the review thread with a suggested fix, so I'm closing this. Please reopen if the fix doesn't work.
