### ISSUE TITLE
[7.0.0] Update registry invalid path error message

### ISSUE THREAD

**Issue by SalmaSamy** [bazelbuild/bazel#20213]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/52b5c8ccb80385b3eca071cfa353df9b94680852

### Category

team-ExternalDeps

### Reviewers

@meteorcloudy

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20214: https://github.com/bazelbuild/bazel/commit/52b5c8ccb80385b3eca071cfa353df9b94680852.
