### ISSUE TITLE
Suggestion - notify user that bazel is starting a daemon

### ISSUE THREAD

**Issue by edrozenberg** [bazelbuild/bazel#2022]
As I learned from https://github.com/tensorflow/tensorflow/issues/5317, and later from the manual, bazel starts a daemon to make subsequent bazel work faster.

Since this might be a surprise to many users (it was to me), it would be helpful if the bazel configure/bazel build output would display some message to indicate a daemon is being started, as suggested by @jart .

A possible downside is if any folks have automated processes to expect certain text in the bazel output, adding a new message to the bazel output might break their automation. But bazel will keep changing in other ways over time anyway so maybe it's not a problem.

**Comment by jart** [comment]
If people are parsing unstructured data from the stderr logs of a process, then they're probably aware of the risks that poses.

**Comment by laszlocsomor** [comment]
I guess we could print an INFO message like one of:

```
INFO: Starting bazel server daemon (PID 12345)
```

```
INFO: Using already-running bazel server daemon (PID 12345)
```

```
INFO: Running in batch mode, not starting a bazel server daemon
```

@damienmg , @aehlig : any objections?

**Comment by aehlig** [comment]
> @damienmg , @aehlig : any objections?

Sounds good to me. As already mentioned, stderr is not
meant to be parsed but for humans to read; so I don't
see a problem here adding more output. And this
information certainly is useful.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by laszlocsomor** [comment]
P4 to indicate that this is easy and up for grabs.

**Comment by damienmg** [comment]
SGTM as long as this is configurable (so we can shut the message off).

**Comment by laurentlb** [comment]
I don't think we should write a message each time user starts a Bazel command. Showing the pid is almost never useful, so I'll remove it (you can still see it with 'bazel info').
Maybe print a message only when the server starts?

**Comment by jin** [comment]
Bazel now prints this at startup, instead of the old `.......`:

```
→ bazel
Starting local Bazel server and connecting to it...
```

I think this satisfies the feature request.
