### ISSUE TITLE
[7.0] Cherrypick android_platforms flag docs

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#20229]
### Commit IDs

cc2fa9a74a1d09788189dd596ceffbf3f1037d0f

### Category

team-Android, team-Documentation

### Reviewers

@katre

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but failed to push. Please check if the branch, cp_ondemand_20229-7.0.0, already exists
cc: @bazelbuild/triage

**Comment by keertk** [comment]
Tracked here: https://github.com/bazelbuild/bazel/issues/20230
