### ISSUE TITLE
[7.0.0] Add --android_platforms to the user manual

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#20230]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/cc2fa9a74a1d09788189dd596ceffbf3f1037d0f

### Category

team-Documentation

### Reviewers

@keertk

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20231: https://github.com/bazelbuild/bazel/commit/cc2fa9a74a1d09788189dd596ceffbf3f1037d0f.
