### ISSUE TITLE
[7.1.0] Update java_tools v13.2 / rules_java 7.3

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20240]
Forked from #20216

**Comment by bazel-io** [comment]
Could not create and push the branch, release-7.1.0

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by keertk** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/20875

**Comment by Wyverald** [comment]
would work on https://github.com/bazelbuild/bazel/issues/21160 obviate this?

**Comment by keertk** [comment]
Yeah! This one won't be needed.
