### ISSUE TITLE
ERROR: Unrecognized option: --java_runtime_version=remotejdk_11

### ISSUE THREAD

**Issue by spz1st** [bazelbuild/bazel#20247]
I got the error when I tried to build a package with the command below on a redhat 8 system.

 bazel test -c opt --copt=-march=corei7 --copt=-Wno-sign-compare --copt=-Wno-write-strings --experimental_build_setting_api --java_runtime_version=remotejdk_11 deepvariant/...

The bazel version is 1.2.1.  I'm not sure if it has anything to do with java (openjdk 17.0.8 2023-07-18 LTS) on my machine.  Anyone has any ideas what might be the cause?  Thanks.

**Comment by iancha1992** [comment]
@spz1st What error message do you get? Also, do you want to try with the newer version of Bazel ([6.4.0](https://github.com/bazelbuild/bazel/releases/tag/6.4.0), [7.0.0rc4](https://releases.bazel.build/7.0.0/rc4/index.html))?

**Comment by spz1st** [comment]
Thanks for your reply.  The title is the error I got.

ERROR: Unrecognized option: --java_runtime_version=remotejdk_11.

I'm surely like to try the newer version if I'm able to install it.  I just installed bazel today with the command below and thought it would be the latest available to my system.

    dnf config-manager --add-repo https://copr.fedorainfracloud.org/coprs/vbatts/bazel/repo/epel-8/vbatts-bazel-epel-8.repo

    dnf install bazel

**Comment by Wyverald** [comment]
Please use a more up-to-date version of Bazel. 1.2.1 is about 4 years old and simply didn't support this flag. [Bazelisk](https://github.com/bazelbuild/bazelisk#installation) is the best way to keep up with latest Bazel releases.
