### ISSUE TITLE
sandbox paths are too long

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#2024]
from  our jenkins build:

14:18:19 Caused by: org.h2.jdbc.JdbcBatchUpdateException: Value too long for column "SITE_PATH VARCHAR(255)": "'/home/jenkins/.cache/bazel/_bazel_jenkins/d6587ecb0efd8ed00f5e4c3a1f8fde87/bazel-sandbox/18d3166a-a3f4-4d1f-a91b-3ddab1ad0c62-1... (269)"; SQL statement:
14:18:19 UPDATE system_config SET 

would it be possible to compress the path components? You could easily get shorter names without losing randomness by using base64. Also, do you really 128-bits of randomness? Can't you just use a 32-bit incremented counter?

**Comment by dslomov** [comment]
@philwo is this still under investigation?

**Comment by philwo** [comment]
It's probably easy to fix - just replace the UUID with something like mdktemp. We don't need the randomness, we just need a unique directory. That could indeed be made much shorter.

Will put it on my list of things to fix.

**Comment by philwo** [comment]
This was fixed some months ago by replacing the UUID with a counter.
