### ISSUE TITLE
[7.1.0] Also path map transitive header jar paths with direct classpath optimization

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20245]
Forked from #19872

**Comment by bazel-io** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21227

**Comment by Wyverald** [comment]
Since the original commit was rolled back, we should probably revert this for 7.1.0 as well.

**Comment by Wyverald** [comment]
revert PR: https://github.com/bazelbuild/bazel/pull/21281

**Comment by iancha1992** [comment]
Closing now that it's reverted.
