### ISSUE TITLE
Windows: SkylarkTests and bazel_windows_example_test are failing

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2025]
http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=windows-x86_64/949/consoleFull
```
FAIL: //src/test/java/com/google/devtools/build/lib/skylark:SkylarkTests (see C:/bazel_ci/temp/Bazel/073GEPhp/execroot/windows-x86_64/bazel-out/local-fastbuild/testlogs/src/test/java/com/google/devtools/build/lib/skylark/SkylarkTests/test.log)
____From Testing //src/test/java/com/google/devtools/build/lib/skylark:SkylarkTests:
==================== Test output for //src/test/java/com/google/devtools/build/lib/skylark:SkylarkTests:
JUnit4 Test Runner
ERROR: 'null' is not recognized as an internal or external command,
```

Culprit should be : 775dc683615d466b565a195abc30b09d90320eb7
//cc @laszlocsomor

**Comment by laszlocsomor** [comment]
Sadly, the culprit is indeed that commit :(  I'm looking into how to fix it.

**Comment by laszlocsomor** [comment]
The problem is that now we create the runfiles directory for `foo.cmd`, not just `foo`, e.g. in the [test output](http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=windows-x86_64/951/console) you can see this line:
```
____[44 / 51] Creating runfiles tree bazel-out/vc_14_0_x64-fastbuild/bin/examples/java-native/src/test/java/com/example/myproject/hello.cmd.runfiles
```

**Comment by laszlocsomor** [comment]
I have a bugfix for this, it's in the pipeline for submission. I'll push the changes to GitHub tomorrow.

**Comment by meteorcloudy** [comment]
```
================================================================================
FAIL: //src/test/java/com/google/devtools/build/lib/skylark:SkylarkTests (see C:/bazel_ci/temp/Bazel/073GEPhp/execroot/windows-x86_64/bazel-out/local-fastbuild/testlogs/src/test/java/com/google/devtools/build/lib/skylark/SkylarkTests/test.log)
____From Testing //src/test/java/com/google/devtools/build/lib/skylark:SkylarkTests:
==================== Test output for //src/test/java/com/google/devtools/build/lib/skylark:SkylarkTests:
JUnit4 Test Runner
ERROR: 'null' is not recognized as an internal or external command,
operable program or batch file.
```
Reopen this, since SkylarkTests is still failing

**Comment by laszlocsomor** [comment]
`//src/test/java/com/google/devtools/build/lib/buildeventstream/transports:BuildEventTransportTest` is also failing but I have a fix for it.

`//src/test/java/com/google/devtools/build/lib/skylark:SkylarkTests` seems to be flaky.
