### ISSUE TITLE
c-ares dependency of grpc is not disabled sufficiently forcefully

### ISSUE THREAD

**Issue by blackgnezdo** [bazelbuild/bazel#20265]
### Description of the bug:

Bazel uses gprc rules by disabling its dependency on c-ares in ` third_party/grpc/build_defs.bzl` with 
```
        defines = ["GRPC_ARES=0"],  # Our use case doesn't need ares.
```

Unfortunately, this still leaves the dependency in place, just somewhat disconnected. In particular, this has some negative effects:

1. The dependency is fetched and bundled into the bootstrap distribution bundle.
2. Bazel bootstrap process still wants to build `c-ares` in the second stage of bootstrap.
3. On some OSs this fails, because the fetched `c-ares` bundle is NOT buildable without patching or running `configure`.

### Which category does this issue belong to?

External Dependency

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try to build bazel-6.3.2 on OpenBSD.

### Which operating system are you running Bazel on?

OpenBSD-7.4

### What is the output of `bazel info release`?

`bazel 6.3.2`

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

Building it with `./compile.sh`

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
Using `bazel-6.3.2-dist.zip` with sha256 8cd7feac58193be2bcba451ba6688a46824d37ca6359ff58e0d44eb98f042948
```

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

No

### Have you found anything relevant by searching the web?

Nothing directly useful.

### Any other information, logs, or outputs that you want to share?

I excised the dependency with a little more force to get past this problem. This should not be a big problem as bazel already patches the rules from `grpc` for inclusion:
```patch
Index: third_party/grpc/grpc_1.47.0.patch
--- third_party/grpc/grpc_1.47.0.patch.orig
+++ third_party/grpc/grpc_1.47.0.patch
@@ -11,6 +11,26 @@ index 7bb6b8bdb9..7644107b70 100644
 
  # The set of pollers to test against if a test exercises polling
  POLLERS = ["epoll1", "poll"]
+@@ -60,8 +60,7 @@
+             ret.append("//third_party/xxhash")
+         elif dep == "cares":
+             ret += select({
+-                "//:grpc_no_ares": [],
+-                "//conditions:default": ["//external:cares"],
++                "//conditions:default": [],
+             })
+         elif dep == "cronet_c_for_grpc":
+             ret.append("//third_party/objective_c/Cronet:cronet_c_for_grpc")
+@@ -162,8 +162,7 @@
+         srcs = srcs,
+         defines = defines +
+                   select({
+-                      "//:grpc_no_ares": ["GRPC_ARES=0"],
+-                      "//conditions:default": [],
++                      "//conditions:default": ["GRPC_ARES=0"],
+                   }) +
+                   select({
+                       "//:remote_execution": ["GRPC_PORT_ISOLATED_RUNTIME=1"],
 @@ -237,10 +235,6 @@
      test_lib_ios = name + "_test_lib_ios"
      ios_tags = tags + ["manual", "ios_cc_test"]
@@ -57,6 +77,37 @@ index 09fcad95a2..9b737e5deb 100644
      )
 
      native.bind(
+@@ -106,11 +106,6 @@
+     )
+ 
+     native.bind(
+-        name = "cares",
+-        actual = "@com_github_cares_cares//:ares",
+-    )
+-
+-    native.bind(
+         name = "gtest",
+         actual = "@com_google_googletest//:gtest",
+     )
+@@ -276,18 +271,6 @@
+             urls = [
+                 "https://storage.googleapis.com/grpc-bazel-mirror/github.com/google/re2/archive/8e08f47b11b413302749c0d8b17a1c94777495d5.tar.gz",
+                 "https://github.com/google/re2/archive/8e08f47b11b413302749c0d8b17a1c94777495d5.tar.gz",
+-            ],
+-        )
+-
+-    if "com_github_cares_cares" not in native.existing_rules():
+-        http_archive(
+-            name = "com_github_cares_cares",
+-            build_file = "@com_github_grpc_grpc//third_party:cares/cares.BUILD",
+-            sha256 = "ec76c5e79db59762776bece58b69507d095856c37b81fd35bfb0958e74b61d93",
+-            strip_prefix = "c-ares-6654436a307a5a686b008c1d4c93b0085da6e6d8",
+-            urls = [
+-                "https://storage.googleapis.com/grpc-bazel-mirror/github.com/c-ares/c-ares/archive/6654436a307a5a686b008c1d4c93b0085da6e6d8.tar.gz",
+-                "https://github.com/c-ares/c-ares/archive/6654436a307a5a686b008c1d4c93b0085da6e6d8.tar.gz",
+             ],
+         )
+ 
 diff --git a/bazel/grpc_extra_deps.bzl b/bazel/grpc_extra_deps.bzl
 index 09fcad95a2..9b737e5deb 100644
 --- a/bazel/grpc_extra_deps.bzl

```

**Comment by blackgnezdo** [comment]
I confirmed that with this change cares is sufficiently disabled that bazel can be bootstrapped without `cares`.

**Comment by Wyverald** [comment]
could you please send a PR? thanks!
