### ISSUE TITLE
Remove the explicit inclusion of Darwin in the list of case-insensitive OSes

### ISSUE THREAD

**Issue by joeleba** [bazelbuild/bazel#20280]
### Commit IDs

c637041ec145e0964982a2cbf8d5693f0d1d4be0

### Category

team-Performance

### Reviewers

@meisterT

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20281: https://github.com/bazelbuild/bazel/commit/c637041ec145e0964982a2cbf8d5693f0d1d4be0.
