### ISSUE TITLE
[7.0.0] Limit labeler trigger so that it's triggered only when the PR creator is not bazel-io

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#20282]
### Commit IDs

d79119ff6e702f2b08ab91e05d0a8cfe69bc9c42

### Category

team-OSS

### Reviewers

@keertk

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20283: https://github.com/bazelbuild/bazel/commit/d79119ff6e702f2b08ab91e05d0a8cfe69bc9c42.
