### ISSUE TITLE
//src/test/shell/bazel:jdeps_test failing on RBE

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#20288]
The following error is only happening on RBE Linux platform.
```
--- /b/f/w/bazel-out/k8-fastbuild/bin/src/test/shell/bazel/jdeps_test.runfiles/_main/src/jdeps_modules.golden	2023-11-22 09:54:06.245590291 +0000
+++ jdeps-sorted	2023-11-22 09:55:22.346087882 +0000
@@ -2,7 +2,6 @@
 java.compiler
 java.instrument
 java.logging
-java.management
 java.naming
 java.sql
 java.xml
 ```

First broken RBE build in postsubmit: https://buildkite.com/bazel/bazel-bazel/builds/25696#018bf414-616b-4833-ba41-7b21d22f62ee

Suspected culprit: https://github.com/bazelbuild/bazel/commit/91ad91d5be3def4ffe4081174a87a307b63d03ad

This is currently blocking Bazel presubmit: https://buildkite.com/bazel/google-bazel-presubmit/builds/74116

**Comment by meteorcloudy** [comment]
I'm disabling this test on RBE to unblock presubmit.

**Comment by meteorcloudy** [comment]
@hvadehra @cushon Can you please help check what's going on?

**Comment by fmeum** [comment]
@bazel-io fork 7.2.1

**Comment by fmeum** [comment]
@bazel-io fork 7.3.0

**Comment by fmeum** [comment]
Nvm, this has already been cherry-picked. We may need to bump the limit again.
