### ISSUE TITLE
Hermetic sandbox / directory is writable by sandbox user

### ISSUE THREAD

**Issue by jkeljo** [bazelbuild/bazel#20285]
### Description of the bug:

Actions that run in the hermetic sandbox are allowed to create new files and directories in `/`. Outside of the sandbox, `/` is generally owned by root and not writable by other users.

### Which category does this issue belong to?

Local Execution

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Install bazelisk
2. Clone https://github.com/jkeljo/bazel_sandbox_readonly_output_directory_bug
3. Run `bazelisk test //:test_mkdir`

The test will succeed, but it should fail. Run `bazelisk test --spawn_strategy=local --nocache_test_results //:test_mkdir` to test outside the sandbox, where it will correctly fail with:
```
mkdir: cannot create directory '/foo': Permission denied
```

### Which operating system are you running Bazel on?

Ubuntu 12.04

### What is the output of `bazel info release`?

release 7.0.0-pre.20231018.3 (also reproes on 6.4.0)

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
https://github.com/jkeljo/bazel_sandbox_root_dir_permissions_bug.git
403362004e6eee744429926666ed6d687d7fdb37
403362004e6eee744429926666ed6d687d7fdb37
```

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

No

### Have you found anything relevant by searching the web?

No

**Comment by oquenchil** [comment]
The test is writing in the chrooted `/`, isn't it?

As long as the action can't mess/write on the system's `/` I'd say this is working as intended.
