### ISSUE TITLE
Update documentation for BES

### ISSUE THREAD

**Issue by joeleba** [bazelbuild/bazel#20301]
### Commit IDs

e40f5e9e784ce2df0c58b29bf943191ed0271e03

### Category

team-Performance

### Reviewers

@meteorcloudy

**Comment by bazel-io** [comment]
Failed commmits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/e40f5e9e784ce2df0c58b29bf943191ed0271e03.
Please resolve manually.
cc: @bazelbuild/triage

**Comment by joeleba** [comment]
https://github.com/bazelbuild/bazel/pull/20304
