### ISSUE TITLE
Skymeld crashes the build by overusing system resources.

### ISSUE THREAD

**Issue by layus** [bazelbuild/bazel#20302]
### Description of the bug:

Enabling skymeld (which happened while testing 7.0.0 because it is the new default) lead to many crashes because normal actions are now competing with repository actions for system resources. As our repository actions are resource-intensive (disk, cpu and network) a lot of these actions crash when the system starves.

This is mainly because there is no way to declare the amount of resources a repository action needs. We used to address that with `--loading_phase_threads=10` but skymeld makes this option is irrelevant.

Is there another way to configure expected resource usage for repository actions ? Right now we probably want to disable skymeld so failures in repository rules do not affect normal rules.

### Which category does this issue belong to?

Core, External Dependency

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Not trivial, you need repository rules that use a lot of resources, enough to decrease the available system resources below the amount needed to run normal actions.

### Which operating system are you running Bazel on?

Ubuntu

### What is the output of `bazel info release`?

7.0.0rc2

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

It's kind of a feature of skymeld.

### Have you found anything relevant by searching the web?

Skymeld discussion: https://github.com/bazelbuild/bazel/issues/14057

**Comment by layus** [comment]
I should probably mention that this issue arises from using rules_nixpkgs, where repository rules are (ab) used to build a whole tree of subpackages.

**Comment by GorshkovNikita** [comment]
Hi! We are experiencing the same issue (we also use `nixpkgs_rules`) after upgrading to bazel 7. Adding `--noexperimental_merged_skyframe_analysis_execution` doesn't seem to work in our case, because we have too many repository actions, which exhaust system resources by themselves. Is there a way to make `--loading_phase_threads` work in bazel 7.1.2?

**Comment by fmeum** [comment]
@GorshkovNikita This could be https://github.com/bazelbuild/bazel/issues/21803

**Comment by layus** [comment]
@GorshkovNikita  Is `--loading_phase_threads` somehow broken in 7.1.2 ? I cannot find any issue related to that.

--noexperimental_merged_skyframe_analysis_execution and --loading_phase_threads is the solution we are currently using.

**Comment by GorshkovNikita** [comment]
> @GorshkovNikita This could be #21803

Thanks! I can confirm, that the problem is gone, while using bazel 7.0.2.

**Comment by fmeum** [comment]
@GorshkovNikita Do you mean 7.2.0?
