### ISSUE TITLE
[7.1.0] Make Turbine x86_64 native image more compatible

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20308]
Forked from #20306

**Comment by bazel-io** [comment]
Could not create and push the branch, release-7.1.0

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
@hvadehra @fmeum any update on this?

**Comment by Wyverald** [comment]
@hvadehra is OOO until Feb 5. Guess we'll wait until then to decide.

**Comment by hvadehra** [comment]
In the past, we've just cherry picked the changes that update the `java_tools` versions. There could be some value in cherrypicking the actual changes as well if they introduce tests, but it looks like that's not the case here. So we just need https://github.com/bazelbuild/bazel/pull/20393 (or https://github.com/bazelbuild/bazel/pull/20713)

**Comment by Wyverald** [comment]
thanks for the confirmation. since it sounds like the java_tools code in the release branches isn't actually used, I'll go ahead and close the related PRs.
