### ISSUE TITLE
Enable (non-generated) filegroup resolution in repository_ctx.path

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2031]
### Description of the problem / feature request / question:
I want to execute a binary in a repository impl.
When using a `filegroup` with _non-generated_ file, it can not be resolved in `repository_ctx.path`.

### If possible, provide a minimal example to reproduce the problem:

in `@foo_binary//:`:

    filegroup(
      name = "mybinary",
      srcs = ["mybinary"],
    )

in `//third_party/bar.bzl`:

    binary = ctx.path(ctx.attr.foomybinary)

    ctx.execute([
      binary,
    ])
    

### Environment info
* Bazel version (output of `bazel info release`): 0.3.2

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
Nope

### Anything else, information or logs or outputs that would be helpful?
Error message is:

    Not a file: /home/user/.cache/bazel/_bazel_users/384827ac61ea21f490af4da32671de43/external/foo_binary/mybinary.

I hear people talking that the phases are not "important" anymore. So this limitation should be possible to lift!?

**Comment by laszlocsomor** [comment]
Could you please show more of the repository rule and how you're calling it? It's a bit too minimal right now :)

**Comment by damienmg** [comment]
```
filegroup(
  name = "mybinary",
  srcs = ["mybinary"],
)
```

This define 2 things for the same label that might pose problem, try removing the filegroup.

Normally we address file by label but we cannot refer to filegroup because we do not actually loads any package before executing the repository rule.

**Comment by damienmg** [comment]
friendly ping? Is removing the file group fixing your issue?

**Comment by damienmg** [comment]
Closing now
