### ISSUE TITLE
Bazel CI Flaky com.google.devtools.build.lib.bazel.rules.android.AndroidNdkRepositoryTest$WithPlatforms testUnsupportedNdkVersion

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#20312]
https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/01880a39-d753-7216-b63d-c10604d35361?branch=master

Platform  :  BAZELCI_TASK=ubuntu2004

Test details:
```
TEST_TARGET=//src/test/java/com/google/devtools/build/lib/bazel/rules/android:AndroidTests
TEST_NAME=testUnsupportedNdkVersion
bazel test //src/test/java/com/google/devtools/build/lib/bazel/rules/android:AndroidTests --test_filter=testUnsupportedNdkVersion
```

Logs:
```
java.lang.Exception: Test cancelled
	at com.google.testing.junit.runner.model.TestCaseNode.testInterrupted(TestCaseNode.java:89)
	at com.google.testing.junit.runner.model.TestSuiteNode.testInterrupted(TestSuiteNode.java:71)
	at com.google.testing.junit.runner.model.TestSuiteNode.testInterrupted(TestSuiteNode.java:71)
	at com.google.testing.junit.runner.model.TestSuiteNode.testInterrupted(TestSuiteNode.java:71)
	at com.google.testing.junit.runner.model.TestSuiteNode.testInterrupted(TestSuiteNode.java:71)
	at com.google.testing.junit.runner.model.TestSuiteModel.testRunInterrupted(TestSuiteModel.java:150)
	at com.google.testing.junit.runner.internal.junit4.JUnit4TestXmlListener$WriteXmlSignalHandler.handle(JUnit4TestXmlListener.java:118)
	at com.google.testing.junit.runner.internal.SignalHandlers$2.handle(SignalHandlers.java:62)
	at com.google.testing.junit.runner.internal.SignalHandlers$2.handle(SignalHandlers.java:65)
	at jdk.unsupported/sun.misc.Signal$InternalMiscHandler.handle(Signal.java:198)
	at java.base/jdk.internal.misc.Signal$1.run(Signal.java:220)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

CC Greenteam @fweikert

**Comment by sgowroji** [comment]
Similar flaky tests under AndroidNdkRepository are :

| Description | Instances | Most recent instance |
| --- | --- | --- |
| [com.google.devtools.build.lib.bazel.rules.android.AndroidNdkRepositoryTest$WithPlatforms testUnsupportedNdkVersion](https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/01880a39-d753-7216-b63d-c10604d35361) | 5 | Thu 23 Nov 2023 at 12:41 UTC |
| [com.google.devtools.build.lib.bazel.rules.android.AndroidNdkRepositoryTest$WithPlatforms testMissingPlatformsDirectory](https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/01880a39-d761-7e31-85d6-a90ad402c34e) | 5 | Thu 23 Nov 2023 at 12:41 UTC |
| [com.google.devtools.build.lib.bazel.rules.android.AndroidNdkRepositoryTest$WithPlatforms testApiLevelHighestVersionDetection](https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/01880a39-d767-7cb2-8570-9a55d9c16e12) | 5 | Thu 23 Nov 2023 at 12:41 UTC |
| [com.google.devtools.build.lib.bazel.rules.android.AndroidNdkRepositoryTest$WithoutPlatforms testInvalidNdkReleaseTxt](https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/01880a39-d75d-714e-9fc7-0e257e7b3d06) | 5 | Thu 23 Nov 2023 at 12:41 UTC |
| [com.google.devtools.build.lib.bazel.rules.android.AndroidNdkRepositoryTest$WithoutPlatforms testUnsupportedNdkVersion](https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/01880a39-d760-7645-b64a-a8c9e6cf9fe5) | 4 | Thu 23 Nov 2023 at 12:41 UTC |
| [com.google.devtools.build.lib.bazel.rules.android.AndroidNdkRepositoryTest$WithoutPlatforms testMiscLibraries](https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/01880a39-d757-7133-9a79-3805e91f378b) | 4 | Thu 23 Nov 2023 at 12:41 UTC |
| [com.google.devtools.build.lib.bazel.rules.android.AndroidNdkRepositoryTest$WithPlatforms testMiscLibraries](https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/01880a39-d758-75ad-be4a-c9a246022464) | 4 | Thu 23 Nov 2023 at 12:41 UTC |
| [com.google.devtools.build.lib.bazel.rules.android.AndroidNdkRepositoryTest$WithoutPlatforms testInvalidNdkSourceProperties](https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/01880a39-d757-741e-83f0-6c7af82de744) | 4 | Thu 23 Nov 2023 at 12:41 UTC |
| [com.google.devtools.build.lib.bazel.rules.android.AndroidNdkRepositoryTest$WithoutPlatforms testApiLevelHighestVersionDetection](https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/01880a39-d75c-7561-adb2-2128a9456cc9) | 4 | Thu 23 Nov 2023 at 12:41 UTC |
| [com.google.devtools.build.lib.bazel.rules.android.AndroidNdkRepositoryTest$WithPlatforms testInvalidNdkSourceProperties](https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/01880a39-d759-7dde-acaa-c0b6c904534b) | 4 | Thu 23 Nov 2023 at 12:41 UTC |
| [com.google.devtools.build.lib.bazel.rules.android.AndroidNdkRepositoryTest$WithoutPlatforms testMissingPlatformsDirectory](https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/01880a39-d753-71f9-bfd7-50b402917ed7) | 4 | Thu 23 Nov 2023 at 12:41 UTC |
| [com.google.devtools.build.lib.bazel.rules.android.AndroidNdkRepositoryTest$WithPlatforms testInvalidNdkReleaseTxt](https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/01880a39-d75a-7360-82fa-5a9d9ff5c333) | 4 | Thu 23 Nov 2023 at 12:41 UTC |

**Comment by ahumesky** [comment]
This test has been deleted.
