### ISSUE TITLE
[7.0.0] Pass `ct.sym` to direct version of Turbine

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20323]
Forked from #20294

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by meteorcloudy** [comment]
The relevant change this PR tries to fix is not in Bazel 7

**Comment by fmeum** [comment]
@meteorcloudy If we want to have a single java_tools/rules_java release flow for Bazel 7, I think that we should merge this. I can create a manual cherry-pick.
