### ISSUE TITLE
Windows, chocolatey: support drive letters other than C: in chocolatey package.

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#2032]
At least in `chocolateyinstall.ps1`, line 53, and maybe other places

**Comment by dslomov** [comment]
@petemounce @laszlocsomor

**Comment by petemounce** [comment]
Woah woah woah, regex find and replace in powershell? What have I let myself in for. Are different drives really necessary? :p

Yeah, sure. I'll get that done.

**Comment by laszlocsomor** [comment]
Help us Obi-Wan, you're the only PS expert! :)

**Comment by petemounce** [comment]
Done.
