### ISSUE TITLE
Bazel fails to clean when configuring Tensorflow

### ISSUE THREAD

**Issue by Randl** [bazelbuild/bazel#2033]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
When building Tensorflow, Bazel fails to clean with following message
```
WARNING: Output base '/home/username/.cache/bazel/_bazel_username/acf2af86672e1552dfd6edd47d54a950' is on NFS. This may lead to surprising failures and undetermined behavior.
.
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
ERROR: /home/username/.cache/bazel/_bazel_username/acf2af86672e1552dfd6edd47d54a950/server (Directory not empty).
```
Replacement of `bazel clean --expunge` with `bazel clean --expunge_async` [here](https://github.com/tensorflow/tensorflow/blob/master/configure#L25) fixes the issue.

### Environment info
* Operating System:
Ubuntu 16.04

* Bazel version (output of `bazel info release`):
```
$ bazel info release
WARNING: Output base '/home/chaimb/.cache/bazel/_bazel_chaimb/acf2af86672e1552dfd6edd47d54a950' is on NFS. This may lead to surprising failures and undetermined behavior.
................
release 0.3.2
```

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

No
### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).
https://github.com/tensorflow/tensorflow/issues/5357

**Comment by laszlocsomor** [comment]
Sounds like https://github.com/bazelbuild/bazel/issues/1586.
What happens if you move off NFS and use a local path? You can use [`--output_user_root`](https://bazel.build/versions/master/docs/bazel-user-manual.html#flag--output_user_root) for this.

**Comment by Randl** [comment]
```
$ bazel --output_user_root=/tmp/tens clean --expunge
Extracting Bazel installation...
.............
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
```

At the moment I move off NFS everything works OK.

**Comment by laszlocsomor** [comment]
Is that an acceptable long-term workaround for you?
