### ISSUE TITLE
Support using external repositories for builtin_sysroot in create_cc_toolchain_config_info

### ISSUE THREAD

**Issue by armandomontanez** [bazelbuild/bazel#20334]
### Description of the feature request:

[Pigweed](https://pigweed.googlesource.com/pigweed/pigweed/) doesn't have a checked in sysroot to reference in `create_cc_toolchain_config_info()`, and instead pulls down a sysroot hosted through CIPD. Right now, the only way I've found to reference the contents of this package is through `"external/linux_sysroot"`. For `cxx_builtin_include_directories`, we use strings like  `"%package(@llvm_toolchain//)%/include/c++/v1"` to reference include directories provided by external repositories, it would be nice for this syntax to be supported for `builtin_sysroot` as well.

### What underlying problem are you trying to solve with this feature?

Not relying on the exec-root-relative `external/*` path to reference contents of an external repository when specifying `builtin_sysroot` for a cc toolchain.

**Comment by t-rad679** [comment]
I'm now looking into this.

Is there any reason we couldn't extract the logic [here](https://github.com/bazelbuild/bazel/blob/935bd263ec5912469d7d0f0abe54efc071018a32/src/main/starlark/builtins_bzl/common/cc/cc_toolchain_provider_helper.bzl#L124-L139) and then call it [here](https://github.com/bazelbuild/bazel/blob/935bd263ec5912469d7d0f0abe54efc071018a32/src/main/starlark/builtins_bzl/common/cc/cc_toolchain_provider_helper.bzl#L215)?

Seems pretty straightforward.

**Comment by armandomontanez** [comment]
Yeah, I think it's that simple. Thanks for picking this up! :)

**Comment by t-rad679** [comment]
I was talking with @comius about this and he asked me to find out if it's possible for regular labels for your use case. He is hesitant to introduce more parsing and extra syntax in more cases. If it is not possible or preferable for some reason, he approved the solution I mentioned above.

**Comment by Wyverald** [comment]
Using a label would indeed be nicer as it would avoid the headache associated with parsing a label in Starlark (what is the current repo/package, where does the repo mapping come from, etc.) Essentially, avoid https://github.com/bazelbuild/bazel/issues/21801.

**Comment by t-rad679** [comment]
`builtin_sysroot_label` would be new

**Comment by armandomontanez** [comment]
I'd much prefer a label pointing to a package. I only mentioned the other syntax in the bug since there was precedence and the compatibility story was obvious.

Naming is always "fun," but perhaps `sysroot_package` would be more self-documenting? I'm not sure what the `builtin` in `builtin_sysroot` even refers to.

**Comment by tpudlik** [comment]
Does https://github.com/bazelbuild/rules_cc/commit/0069837ab5b631c2e4a45c7058223859f9b27dfa address this issue, or is there more to be done?

@armandomontanez @matts1

**Comment by matts1** [comment]
Should be addressed in the commit just before that. For an example, take a look at https://chromium-review.googlesource.com/c/chromiumos/bazel/+/5595076 (it got reverted due to a bug in Cq-Depend, but the code is correct).

**Comment by armandomontanez** [comment]
This is addressed in the new rules_cc toolchain ruleset:

https://github.com/bazelbuild/rules_cc/blob/main/cc/toolchains/args/sysroot.bzl
