### ISSUE TITLE
[7.0.0] Generalize memory and cpu tracking

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20344]
Forked from #19839

**Comment by bazel-io** [comment]
Could not create and push the branch, release-7.1.0

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/20396
