### ISSUE TITLE
In an air-gapped Environment bzlmod shouldn't fail if the first registry is not reachable & the second registry is reachable

### ISSUE THREAD

**Issue by brianantony456** [bazelbuild/bazel#20359]
### Description of the bug:

bzlmod supports providing multiple `--registry` parameters. However in an air-gapped environment if the first registry in the list is not reachable, bazel fails immidiately throwing error.

**Expected behavior:** Doesn't it make sense that bazel tries to find the module in the second defined registry, before giving up ? This is very important use case for us, as we do not want to modify the .bazelrc based on our network restrictions.

```
# .bazelrc
# Bazel's default registry
common --registry=https://bcr.bazel.build
# Our internal Registry
common --registry=https://internal-registry
```

We also thought of overcoming these problemms with `--download_config`, however this doesn't help as the failure is thrown when the first defined registry fails.
i.e. Rewrite url once with itself & once with our internal registry.
```
rewrite (bcr.bazel.build/.*) $1
rewrite (bcr.bazel.build)/(.*) <intenral_registry_url>/$2
```

Source code that throws the error seem to fail if the first registry is not reachable:
`https://github.com/bazelbuild/bazel/blob/7.0.0-pre.20231018.3/src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java#L413`

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

**Test workspace**
[Use bzlmod example 1 from turorial](https://github.com/bazelbuild/examples/tree/main/bzlmod/01-depend_on_bazel_module)

```
# .bazelrc file
# Invalid registry
common --registry=https://dummy-foo-registry
# Bazel's default registry
common --registry=https://bcr.bazel.build
# Our internal Registry
common --registry=https://internal-registry
```

`
.bazeliskrc file
7.0.0-pre.20231018.3
`

Error thrown:
```
examples/bzlmod/01-depend_on_bazel_module[main]$ bazelisk mod graph
2023/11/29 14:34:09 Downloading https://releases.bazel.build/7.0.0/rolling/7.0.0-pre.20231018.3/bazel-7.0.0-pre.20231018.3-linux-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: in module dependency chain <root> -> glog@0.5.0: Error accessing registry https://dummy-foo-registry: Unknown host: dummy-foo-registry. Type 'bazel help mod' for syntax and help.
```

### Which operating system are you running Bazel on?

Redhat OS 7.9

### What is the output of `bazel info release`?

release 7.0.0-pre.20231018.3

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
https://github.com/bazelbuild/examples.git

996a864ab8fb920fc5db7287d342fe16c090b481
```

**Comment by meteorcloudy** [comment]
> Doesn't it make sense that bazel tries to find the module in the second defined registry, before giving up ?

Theoretically, there is no guarantee that module "foo" in registry 1 is the same module "foo" in registry 2. If Bzlmod fetches the module from a different place based on if provided registries are reachable, that could actually mean different resolution results. 

Why do you need `https://dummy-foo-registry` in the first place? I hope we can find an alternative for your use case?

**Comment by brianantony456** [comment]
> Why do you need https://dummy-foo-registry in the first place?

https://dummy-foo-registry was to show that the build is always going to fail, if the first registry is not reachable.

Our setup:
- we have a mirror of bcr internally.
- we have machines that can access external network and also some machines in air-gapped environment without external network access.

Our use case:
- bazel hosted bcr (https://bcr.bazel.build) is our primary registry since it is faster on other sites across the world.
- our internal bcr mirror would just be a fallback for the air-gapped environment or in cases of external network connectivity issues.

**Comment by Wyverald** [comment]
Could you simply not specify the BCR for airgapped machines? That seems to be a very straightforward way to solve this problem.

As Yun said, doing what you suggested would mean a spurious failure to access a registry could suddenly turn into a correctness issue, so it's not likely to be feasible.

I'm going to close this for now, but please feel free to continue the discussion.
