### ISSUE TITLE
[7.2.0] Bzlmod: vendor mode

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20366]
Forked from #19563

**Comment by meteorcloudy** [comment]
Most of vendor mode functionalities have been backported in https://github.com/bazelbuild/bazel/pull/21366, waiting for vendoring targets to be implemented.

**Comment by Wyverald** [comment]
We've decided to punt this to 7.2.0 given that vendoring for a build target isn't fully ready yet (neither are docs). Better to let it bake a while more.

**Comment by Wyverald** [comment]
Punting to 7.3.0.
