### ISSUE TITLE
[7.1.0] Add `--enable_workspace` flag (defaulting to true) to allow turning off WORKSPACE logic

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20365]
Forked from #20185

**Comment by bazel-io** [comment]
The branch, release-7.1.0, may not exist. Please retry the cherry-pick after the branch is created.

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
cherry-pick in https://github.com/bazelbuild/bazel/pull/20855
