### ISSUE TITLE
Q: pex support?

### ISSUE THREAD

**Issue by trivigy** [bazelbuild/bazel#2038]
Not sure if this has been asked in the past but will bazel ever consider implementing pex file support build for python? I was able to find only two references to those and have been struggling getting them to work with the current version of bazel.

https://github.com/saileshmittal/bazel/tree/pex
https://github.com/benley/bazel_rules_pex

**Comment by pcj** [comment]
@trivigy You can also try https://github.com/google/subpar.

**Comment by meteorcloudy** [comment]
Just use `--build_python_zip` when you build a python binary, then you'll get an executable python zip file.
Please see the design doc: http://www.bazel.io/designs/2016/09/05/build-python-on-windows.html

**Comment by pcj** [comment]
@meteorcloudy Good to know!

**Comment by trivigy** [comment]
@pcj Thanks for the recommendation. Loved learning about a new cool think I didn't see online. Unfortunately this is quite similar to --build_python_zip which is simply a zipped executable python module. @meteorcloudy I definitely know about that one but unfortunately that feature is simply not enough for what I am looking. I want the ability to embed a venv inside the python executable archive. I have been messing around with creating my own rule for the past entire week and, now that I actually understand how the whole thing works, almost finished making my own pex rule.

The idea behind this is a two fold. Foremost, python programs have dependencies on other python modules. By using pex that dependency is resolved and makes it significantly easier to actually distribute python applications. On the other hand, python applications also have system dependencies and for that I think bazel is pretty well equipped. Hopefully I'll be able to wrap the python executable into a *.deb package that will contain all of the system dependencies. This way when the application is installed, all of the dependencies get resolved with it.

When I get it running I'll be happy to share the rule. And would love some advise if you think there are things I should be considering as I am building this.

**Comment by trivigy** [comment]
@meteorcloudy Maybe you could help. Is there a way to produce the zipped executable (`--build_python_zip`) using the python rule directly? Then I could potentially build another rule around it to wrap that zip with an venv and work similar to pex but not exactly.

**Comment by trivigy** [comment]
Okay never mind. I figured it out. :bulb:

**Comment by ulfjack** [comment]
Is there anything left here for us to do? Can we close this?

**Comment by trivigy** [comment]
I ended up writing a full rule for pex. You can find it here: #699. It would still be really nice if this rule was part of the bazel master and came in with the official distribution.
