### ISSUE TITLE
bazel fetch --repo=@@<repo_name>~<version> does not work for some repos

### ISSUE THREAD

**Issue by jacky8hyf** [bazelbuild/bazel#20397]
### Description of the bug:

For an empty repo, `bazel fetch --repo=@@platforms~0.0.7` does not work. I want a consistent way to pre-fetch my external repositories but without downloading too many things.

`bazel fetch --all` works but it pulls too many things (like some remote_jdk stuff). See below.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Set up the repo like this:

```
WORKSPACE: empty
BUILD.bazel: empty
MODULE.bazel: empty
```

```
# .bazelrc
common --enable_bzlmod
common --repository_cache=
common --distdir=
```

Then run:

```
$ bazel mod graph --include_builtin --verbose

<root> (kleaf@0.0.1)
├───bazel_tools@_ 
│   ├───local_config_platform@_ (*) 
│   ├───apple_support@1.5.0 
│   │   ├───local_config_platform@_ (*) 
│   │   ├───platforms@0.0.7 (*) (was 0.0.4, cause local_config_platform@_, zlib@1.3, bazel_tools@_, rules_cc@0.0.9)
│   │   └───bazel_skylib@1.3.0 
│   │       ├───local_config_platform@_ (*) 
│   │       └───platforms@0.0.7 (*) (was 0.0.4, cause local_config_platform@_, zlib@1.3, bazel_tools@_, rules_cc@0.0.9)
│   ├───platforms@0.0.7 
│   │   ├───local_config_platform@_ (*) 
│   │   └───rules_license@0.0.7 (*) 
│   ├───protobuf@3.19.6 
│   │   ├───bazel_skylib@1.3.0 (*) (was 1.0.3, cause apple_support@1.5.0)
│   │   ├───local_config_platform@_ (*) 
│   │   ├───rules_cc@0.0.9 (*) (was 0.0.1, cause bazel_tools@_)
│   │   ├───rules_java@6.3.1 (*) (was 4.0.0, cause bazel_tools@_)
│   │   ├───rules_proto@4.0.0 (*) 
│   │   ├───rules_python@0.4.0 (*) 
│   │   └───zlib@1.3 (*) (was 1.2.12, cause bazel_tools@_)
│   ├───rules_cc@0.0.9 
│   │   ├───local_config_platform@_ (*) 
│   │   └───platforms@0.0.7 (*) 
│   ├───rules_java@6.3.1 
│   │   ├───bazel_skylib@1.3.0 (*) (was 1.2.0, cause apple_support@1.5.0)
│   │   ├───local_config_platform@_ (*) 
│   │   ├───platforms@0.0.7 (*) (was 0.0.4, cause local_config_platform@_, zlib@1.3, bazel_tools@_, rules_cc@0.0.9)
│   │   ├───rules_cc@0.0.9 (*) (was 0.0.2, cause bazel_tools@_)
│   │   ├───rules_license@0.0.7 (*) (was 0.0.3, cause platforms@0.0.7)
│   │   └───rules_proto@4.0.0 (*) 
│   ├───rules_license@0.0.7 (was 0.0.3, cause platforms@0.0.7)
│   │   └───local_config_platform@_ (*) 
│   ├───rules_proto@4.0.0 
│   │   ├───bazel_skylib@1.3.0 (*) (was 1.0.3, cause apple_support@1.5.0)
│   │   ├───local_config_platform@_ (*) 
│   │   └───rules_cc@0.0.9 (*) (was 0.0.1, cause bazel_tools@_)
│   ├───rules_python@0.4.0 
│   │   └───local_config_platform@_ (*) 
│   └───zlib@1.3 
│       ├───local_config_platform@_ (*) 
│       ├───platforms@0.0.7 (*) 
│       └───rules_cc@0.0.9 (*) (was 0.0.8, cause bazel_tools@_)
└───local_config_platform@_ 
    ├───bazel_tools@_ (*) 
    └───platforms@0.0.7 (*) 
```

This can show that we have the following dependencies (others omitted)
```
apple_support@1.5.0
bazel_skylib@1.3.0
platforms@0.0.7
```

However, there is no consistent method to fetch these repos.

```
# NOTE: Run bazel clean --expunge between these commands
# NOTE: .bazelrc has --repository_cache= --distdir=

$ bazel clean --expunge && bazel fetch --repo=@@apple_support~1.5.0
# works

$ bazel clean --expunge && bazel fetch --repo=@@apple_support
ERROR: Fetching repos failed with errors: Repository '@apple_support' is not defined

$ bazel clean --expunge && bazel fetch --repo=@apple_support
ERROR: Fetching repos failed with errors: No repository visible as '@apple_support' from main repository

$ bazel clean --expunge && bazel fetch --repo=@@bazel_skylib
# works

$ bazel clean --expunge && bazel fetch --repo=@@bazel_skylib~1.3.0
# works

$ bazel clean --expunge && bazel fetch --repo=@bazel_skylib
# works

$ bazel clean --expunge && bazel fetch --repo=@@platforms
# works

$ bazel clean --expunge && bazel fetch --repo=@@platforms~0.0.4
ERROR: Fetching repos failed with errors: Repository '@platforms~0.0.4' is not defined

$ bazel clean --expunge && bazel fetch --repo=@@platforms~0.0.7
ERROR: Fetching repos failed with errors: Repository '@platforms~0.0.' is not defined

$ bazel clean --expunge && bazel fetch --repo=@platforms
# works

# This works but downloads a LOT of stuff
$ bazel clean --expunge && bazel fetch --all
```

The last command, `bazel fetch --all`, downloads too many stuff like:

```
$ ( cd $(bazel info output_base)/external; ls -d */ )
apple_support~1.5.0/
apple_support~1.5.0~apple_cc_configure_extension~local_config_apple_cc/
apple_support~1.5.0~apple_cc_configure_extension~local_config_apple_cc_toolchains/
bazel_skylib~1.3.0/
bazel_tools/
bazel_tools~cc_configure_extension~local_config_cc/
bazel_tools~cc_configure_extension~local_config_cc_toolchains/
bazel_tools~remote_android_tools_extensions~android_gmaven_r8/
bazel_tools~remote_android_tools_extensions~android_tools/
bazel_tools~remote_coverage_tools_extension~remote_coverage_tools/
bazel_tools~sh_configure_extension~local_config_sh/
bazel_tools~xcode_configure_extension~local_config_xcode/
local_config_platform/
platforms/
protobuf~3.19.6/
rules_cc~0.0.9/
rules_java~7.0.6/
rules_java~7.0.6~toolchains~local_jdk/
rules_java~7.0.6~toolchains~remote_java_tools/
rules_java~7.0.6~toolchains~remote_java_tools_darwin_arm64/
rules_java~7.0.6~toolchains~remote_java_tools_darwin_x86_64/
rules_java~7.0.6~toolchains~remote_java_tools_linux/
rules_java~7.0.6~toolchains~remote_java_tools_windows/
rules_java~7.0.6~toolchains~remotejdk11_linux/
rules_java~7.0.6~toolchains~remotejdk11_linux_aarch64/
rules_java~7.0.6~toolchains~remotejdk11_linux_aarch64_toolchain_config_repo/
rules_java~7.0.6~toolchains~remotejdk11_linux_ppc64le/
rules_java~7.0.6~toolchains~remotejdk11_linux_ppc64le_toolchain_config_repo/
rules_java~7.0.6~toolchains~remotejdk11_linux_s390x/
rules_java~7.0.6~toolchains~remotejdk11_linux_s390x_toolchain_config_repo/
rules_java~7.0.6~toolchains~remotejdk11_linux_toolchain_config_repo/
rules_java~7.0.6~toolchains~remotejdk11_macos/
rules_java~7.0.6~toolchains~remotejdk11_macos_aarch64/
rules_java~7.0.6~toolchains~remotejdk11_macos_aarch64_toolchain_config_repo/
rules_java~7.0.6~toolchains~remotejdk11_macos_toolchain_config_repo/
rules_java~7.0.6~toolchains~remotejdk11_win/
rules_java~7.0.6~toolchains~remotejdk11_win_arm64/
rules_java~7.0.6~toolchains~remotejdk11_win_arm64_toolchain_config_repo/
rules_java~7.0.6~toolchains~remotejdk11_win_toolchain_config_repo/
rules_java~7.0.6~toolchains~remotejdk17_linux/
rules_java~7.0.6~toolchains~remotejdk17_linux_aarch64/
rules_java~7.0.6~toolchains~remotejdk17_linux_aarch64_toolchain_config_repo/
rules_java~7.0.6~toolchains~remotejdk17_linux_ppc64le/
rules_java~7.0.6~toolchains~remotejdk17_linux_ppc64le_toolchain_config_repo/
rules_java~7.0.6~toolchains~remotejdk17_linux_s390x/
rules_java~7.0.6~toolchains~remotejdk17_linux_s390x_toolchain_config_repo/
rules_java~7.0.6~toolchains~remotejdk17_linux_toolchain_config_repo/
rules_java~7.0.6~toolchains~remotejdk17_macos/
rules_java~7.0.6~toolchains~remotejdk17_macos_aarch64/
rules_java~7.0.6~toolchains~remotejdk17_macos_aarch64_toolchain_config_repo/
rules_java~7.0.6~toolchains~remotejdk17_macos_toolchain_config_repo/
rules_java~7.0.6~toolchains~remotejdk17_win/
rules_java~7.0.6~toolchains~remotejdk17_win_arm64/
rules_java~7.0.6~toolchains~remotejdk17_win_arm64_toolchain_config_repo/
rules_java~7.0.6~toolchains~remotejdk17_win_toolchain_config_repo/
rules_java~7.0.6~toolchains~remotejdk21_linux/
rules_java~7.0.6~toolchains~remotejdk21_linux_aarch64/
rules_java~7.0.6~toolchains~remotejdk21_linux_aarch64_toolchain_config_repo/
rules_java~7.0.6~toolchains~remotejdk21_linux_toolchain_config_repo/
rules_java~7.0.6~toolchains~remotejdk21_macos/
rules_java~7.0.6~toolchains~remotejdk21_macos_aarch64/
rules_java~7.0.6~toolchains~remotejdk21_macos_aarch64_toolchain_config_repo/
rules_java~7.0.6~toolchains~remotejdk21_macos_toolchain_config_repo/
rules_java~7.0.6~toolchains~remotejdk21_win/
rules_java~7.0.6~toolchains~remotejdk21_win_toolchain_config_repo/
rules_license~0.0.7/
rules_proto~4.0.0/
rules_python~0.4.0/
rules_python~0.4.0~pip_install~pypi__click/
rules_python~0.4.0~pip_install~pypi__pip/
rules_python~0.4.0~pip_install~pypi__pip_tools/
rules_python~0.4.0~pip_install~pypi__pkginfo/
rules_python~0.4.0~pip_install~pypi__setuptools/
rules_python~0.4.0~pip_install~pypi__wheel/
zlib~1.3/
```

## Question:

* If `--repo=@@<name>~<version>` is the way to go, why does it not work on `@@platforms~0.0.4` (from bazel-skylib) or 0.0.7 (from bazel_tools)?
* If `--repo=@@<name>` is the way to go, why does it not work on apple_support (from bazel_tools)?
* If `--repo=@<name>` is the way to go, why does it not work on apple_support (from bazel_tools)?

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

development version

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

Downloaded from: http://r.android.com/2845760

I think this is 7.0.0-pre.20231018.3 but I am not sure.

**Comment by Wyverald** [comment]
> If `--repo=@@<name>~<version>` is the way to go, why does it not work on `@@platforms~0.0.4` (from bazel-skylib) or 0.0.7 (from bazel_tools)?
> If `--repo=@@<name>` is the way to go, why does it not work on apple_support (from bazel_tools)?
> If `--repo=@<name>` is the way to go, why does it not work on apple_support (from bazel_tools)?

All these questions can be answered together. `--repo=@@<canonical_repo_name>` and `--repo=@<apparent_repo_name_as_viewed_from_the_root_module>` are the way to go.

The canonical repo name for a module `foo@0.1.2` is almost always `foo~0.1.2`, but there are special cases known as "[well-known modules](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleKey.java;drc=ab016bec63d7afaf868b81ad7341fde5909dbffd;l=40)". As you can see, `platforms` is (unfortunately) one such special case, so the canonical repo name for `platforms@<any_version>` is just `platforms`. Hence `--repo=@@platforms` would work.

The apparent repo name for a given repo can be different based on where you're "viewing" it from. On the command line, you're "viewing" repos from the root module, or the "main repo". Here, only your direct dependencies are visible to you, so if your MODULE.bazel is empty, `--repo=@<something>` will almost never work. ("Almost" because there are always exceptions...) If you want to refer to `apple_support`, which is an indirect dependency, you'd either need to use `apple_support`'s canonical repo name (`--repo=@@apple_support~1.2.3`), or add it as a direct dependency in your MODULE.bazel file (`bazel_dep(name="apple_support",version="1.2.3")`). Read [the docs](https://bazel.build/external/module#repository_names_and_strict_deps) for more information.

**Comment by jacky8hyf** [comment]
Thanks for the quick response!

Are the list of well-known modules documented somewhere? Will the list grow or shrink in the future?

---

I think it is a bit confusing to me because the list of well-known modules are, as of today from the code you are linking to:

- bazel_tools
- local_config_platform
- platforms

The first two comes from Bazel itself (i.e. bazel generates them; it is a "built-in" module that are only shown when I run `bazel mod graph --include_builtin`). So, it makes sense they don't have a version (and bazel mod graph correctly shows `@_` to indicate no versioning.)

But platforms comes from the BCR and has a version. So it is confusing to me that only `@@platforms` works, but `@@platforms~0.0.7` doesn't.

**Comment by jacky8hyf** [comment]
It is also surprising to me that `@@bazel_skylib` without a version works, as well as `@@bazel_skylib~1.3.0`, though they seem to refer to different things (they are checked out to different directories under `output_base`).

bazel_skylib is not a well-known module.

**Comment by Wyverald** [comment]
> Are the list of well-known modules documented somewhere? Will the list grow or shrink in the future?

Ideally these would be implementation details, just like the exact format of canonical repo names, with due respect to Hyrum's law... So the surefire way to prefetch these would be to add them as direct dependencies and use the single-`@` syntax.

> But platforms comes from the BCR and has a version. So it is confusing to me that only `@@platforms` works, but `@@platforms~0.0.7` doesn't.

Indeed. We added `platforms` as a well-known module specifically to fix a weird interation with toolchain resolution (see code comment; also https://github.com/bazelbuild/bazel/issues/17289).

> It is also surprising to me that `@@bazel_skylib` without a version works, as well as `@@bazel_skylib~1.3.0`

This is because `@@bazel_skylib` is actually from the WORKSPACE world (from a WORKSPACE suffix). Similarly, the reason that `@platforms` (single `@`) works despite you not having declared `platforms` as a direct dependency is that it's from WORKSPACE.

**Comment by Wyverald** [comment]
That's no longer necessary -- we now parse flags twice, with the second pass taking repo mapping into account; also proto rules are starlarkified (or at least to a sufficient extent) that we don't have these hardcoded flag values in Bazel anymore.

**Comment by lberki** [comment]
What's the "bzlmod-certified" way of fetching whatever version of `@platforms` Bazel uses then? Just `@platforms`?
