### ISSUE TITLE
6.0.0-pre.20220517.1 release disappeared

### ISSUE THREAD

**Issue by erock2112** [bazelbuild/bazel#20410]
### Description of the bug:

My team is relying on the 6.0.0-pre.20220517.1 release, which became unavailable earlier today:

```
2023/12/01 15:46:16 Downloading https://github.com/bazelbuild/bazel/releases/download/6.0.0-pre.20220517.1/bazel-6.0.0-pre.20220517.1-linux-x86_64...
2023/12/01 15:46:16 could not download Bazel: HTTP GET https://github.com/bazelbuild/bazel/releases/download/6.0.0-pre.20220517.1/bazel-6.0.0-pre.20220517.1-linux-x86_64 failed with error 404
```

We're using this release because we use managed_directories support for VSCode auto-completion for node_modules.  We have workarounds in progress, but all of our continuous integration is blocked on this missing release so we would really like for it to re-appear.

**Comment by fweikert** [comment]
Hey Eric,

Sorry for breaking your CI! Please download rolling releases from GCS instead - https://releases.bazel.build/6.0.0/rolling/6.0.0-pre.20220517.1/index.html in your case. You can find a list of all rolling releases at https://bazel.build/release/rolling
