### ISSUE TITLE
How to install bazel on NFS

### ISSUE THREAD

**Issue by GaofengCheng** [bazelbuild/bazel#2042]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
I want to compile the tensorflow from source code, so I install the Bazel. My $HOME is on NFS, after install the Bazel using
    `$chmod +x bazel-version-installer-os.sh`
    `$ ./bazel-version-installer-os.sh --user`
when I type `bazel`, the warning show:
WARNING: Output base `'/home/usrname/.cache/bazel/_bazel_chenggaofeng/75c879a7665c1f6bb168362b3b0eb86b' is on NFS. This may lead to surprising failures and undetermined behavior.
                                                           [bazel release 0.4.0]`
 and the subsequent compile of tensroflow also failed.

### Environment info
* Operating System: `Linux gs07 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux`

* Bazel version (output of `bazel info release`): `bazel release 0.4.0`

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by laszlocsomor** [comment]
Please don't install Bazel on NFS, as the warning says it leads to undetermined behavior. Use the `--output_user_root` flag to change the location of Bazel's installation tree.
I'll add a FAQ entry about this on [bazel.build](bazel.build)

**Comment by laszlocsomor** [comment]
Here's the flag's documentation: [`--output_user_root`](https://bazel.build/versions/master/docs/bazel-user-manual.html#flag--output_user_root)

**Comment by fvisin** [comment]
In my case setting `TEST_TMPDIR` as suggested in https://github.com/bazelbuild/bazel/issues/1970#issuecomment-282177022 did the trick.
