### ISSUE TITLE
[7.1.0] Request API in repository_ctx to download multiple files simultaneously

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20457]
Forked from #19674

**Comment by bazel-io** [comment]
Could not create and push the branch, release-7.1.0

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/20856

**Comment by bazel-io** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/20857
