### ISSUE TITLE
Support incremental installation on Android 14

### ISSUE THREAD

**Issue by dvpermyakov** [bazelbuild/bazel#20456]
### Description of the feature request:

Right now if I run `mobile-install` command to install apk on Android 14 emulator then I receive the error: 
```
java.lang.SecurityException: Writable dex file '/data/local/tmp/incrementaldeployment/com.company.debug/dex/incremental_classes14.dex' is not allowed.
```
This happens because of [some restrictions](https://developer.android.com/about/versions/14/behavior-changes-14#safer-dynamic-code-loading) in Android 14.

### Which category does this issue belong to?

Android

### What underlying problem are you trying to solve with this feature?

Make `mobile-install` working for Android 14 emulator

### Which operating system are you running Bazel on?

macOS Sonoma 14.1.1

### What is the output of `bazel info release`?

release 6.2.1

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
https://github.com/bazelbuild/bazel.git
d84d852b2be3de8bcdbef5d05224e4a557ab6beb
2f3187963880da448f56879972f1167a99d51685
```

### Any other information, logs, or outputs that you want to share?

The feature can be implemented in [this file](https://github.com/bazelbuild/bazel/blob/master/tools/android/incremental_install.py#L449) by adding:
``` python
for local, _ in files_to_push:
    os.chmod(local, 0o440)
```

**Comment by meisterT** [comment]
cc @ted-xie

**Comment by ted-xie** [comment]
This is a pretty small change and should be OK to import. We are also in the middle of releasing the next version of mobile-install written in Starlark here: https://github.com/bazelbuild/rules_android/issues/12

**Comment by ted-xie** [comment]
Hi @dvpermyakov, I'm having a hard time reproducing this on my end. My setup: MacOS Sonoma 14.4.1, custom bazel built at 1c9986613a83ed9d8bd037bd9bcec3fc775bad9f (Apr 9 commit).

In a basic test app:
* ~/work/bazel/bazel-bin/src/bazel mobile-install java/com/basicapp:basic_app
* ~/work/bazel/bazel-bin/src/bazel mobile-install java/com/basicapp:basic_app --start_app

This correctly launches the app for me with no modifications required to the incremental install binary. Is this similar to what you're doing?

**Comment by ahumesky** [comment]
The native version of mobile-install has been removed in bazel 8 and replaced with the Starlark version in https://github.com/bazelbuild/rules_android/, if this is still an issue in that version, please feel free to open a new issue there.
