### ISSUE TITLE
[7.1.0] Read authentication information from .netrc

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20455]
Forked from #20417

**Comment by bazel-io** [comment]
The branch, release-7.1.0, may not exist. Please retry the cherry-pick after the branch is created.

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by keertk** [comment]
https://github.com/bazelbuild/bazel/pull/20915
