### ISSUE TITLE
Build strategy should be factored in to bazel's remote cache

### ISSUE THREAD

**Issue by SinOverCos** [bazelbuild/bazel#20460]
### Description of the bug:

If a target is built using one build strategy (e.g. `standalone`) and then it is later built (with the same inputs) with another build strategy (e.g. `sandboxed`), there shouldn't be a cache hit as the build strategy has changed and can produce a different output.

### Which category does this issue belong to?

Remote Execution

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a remote cache (empty). Build `//foo` with remote cache upload enabled and `--spawn_strategy=standalone`. Build again with `--spawn_strategy=sandboxed` and see cache hits.

### Which operating system are you running Bazel on?

Linux Ubutnu 18

### What is the output of `bazel info release`?

release 5.4.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

n/a

**Comment by tjgq** [comment]
It's a deliberate design decision that the strategy used to execute an action doesn't factor into its identity; an action that produces different results depending on the strategy used would be considered non-hermetic. This is very unlikely to change.

It would help to have a motivating use case for an action whose outputs are strategy-dependent, and that can't be achieved by leveraging one of the many factors that *do* affect the identity of an action, like its input, command line arguments or environment variables.

**Comment by SinOverCos** [comment]
Hey @tjgq , thanks for you quick response.

My motivation is that I'm trying to migrate my codebase from `standalone` to `sandboxed`. `standalone` is already not hermetic because it doesn't build inside a sandbox, and some of my build targets end up reaching into dependencies that were never explicitly passed to in the BUILD file.

By switching `spawn_strategy` to `sandboxed`, I was hoping a build-everything would show me where all my non-hermetic targets are.

**Comment by SinOverCos** [comment]
Yes, that works, and building without the cache is my plan now that I know that the build strategy isn't part of the cache key.

What I had in mind was having this done automatically (e.g. build strategy gets hashed for the cache key) so that each change in the gradual migration wouldn't need some hands-on tweaking of the CI pipeline's bazel configurations.
