### ISSUE TITLE
[6.5.0] Fix extraction of tar archives containing sparse files.

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20469]
Forked from #20110

**Comment by iancha1992** [comment]
I tried to cherry-pick this to release-6.5.0 branch, but `maven_install.json` and `MODULE.bazel.lock` were missing and `MODULE.bazel.lock` may need another commit(s) before we can cherry-pick. Can you please take a look? @meteorcloudy @tjgq @brentleyjones 

cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
Sent https://github.com/bazelbuild/bazel/pull/20531
