### ISSUE TITLE
`java_runtime_version_alias` removed in Bazel 7

### ISSUE THREAD

**Issue by Silic0nS0ldier** [bazelbuild/bazel#20462]
### Description of the bug:

The rule `java_runtime_version_alias ` was removed in https://github.com/bazelbuild/bazel/commit/3029a7db8a877e8a616b2ebe304573fae9ea9962#diff-1e7c4210fde93829697c4b9085dde7ecd924d798f203ba3ac9c5869d662cf996L82-L93.

This is not a documented breaking change and the rule is [available in Rules Java](https://github.com/bazelbuild/rules_java/blob/4732a6484548e5a524df8018966c3b38652be2dc/toolchains/java_toolchain_alias.bzl#L82-L93).

### Which category does this issue belong to?

Java Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Attempt to query a `BUILD` file containing;

```starlark
load("@bazel_tools//tools/jdk:java_toolchain_alias.bzl", "java_runtime_version_alias")
```

### Which operating system are you running Bazel on?

macOS Sonoma

### What is the output of `bazel info release`?

release 7.0.0rc6

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

3029a7db8a877e8a616b2ebe304573fae9ea9962

**Comment by meteorcloudy** [comment]
Added a breaking change note in Bazel 7 release note.

**Comment by meteorcloudy** [comment]
Thanks for pointing that out! I'll re-open this one to track the documentation update.

/cc @hvadehra

**Comment by hvadehra** [comment]
Docs have been updated in https://github.com/bazelbuild/bazel/commit/f001ef1a8a2af31abd879598a6def9eb22d3433f
