### ISSUE TITLE
Documentation: Some examples in workspace-rules contain invalid names

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#2047]
Consider this [documented local_repository example](https://www.bazel.io/versions/master/docs/be/workspace.html#local_repository)

```
local_repository(
    name = "my-ssl",
    path = "/home/user/ssl",
)
```

When used as is it's failing because `-` doesn't appear to be a valid char in wokspace rules:

```
ERROR: /home/davido/projects/bazel_test/WORKSPACE:1:1: local_repository rule //external:my-ssl's name field must be a legal workspace name.
ERROR: Error evaluating WORKSPACE file.
```

**Comment by aehlig** [comment]
Thanks for reporting; the documentation should be fixed indeed. Feel free to send a patch.
