### ISSUE TITLE
Flag to forcifully re-fetch bzlmod registry files

### ISSUE THREAD

**Issue by jacky8hyf** [bazelbuild/bazel#20477]
### Description of the feature request:

I want to request a flag to forcifully fetch bzlmod registry files instead of relying on a local cache.

### Which category does this issue belong to?

Configurability, External Dependency

### What underlying problem are you trying to solve with this feature?

For example, suppose you have the following set up (see 
[test.tar.gz](https://github.com/bazelbuild/bazel/files/13619870/test.tar.gz) )

```
# MODULE.bazel
bazel_dep(name = "mymod", version = "0.0.1")
```

and a local registry that vendors `@@mymod`:

```
# reg/modules/mymod/0.0.1/source.json
{
    "type": "local_path",
    "path": "mymod"
}
```

One may load files from `@@mymod` to let Bazel fetch the above `source.json`. However, after that, Bazel keeps this file in cache somewhere. So if I modify `source.json` locally, I cannot tell Bazel to forcifully fetch this `source.json` file again.

This is particularly important if I am relocating the source for a module.

I tried `bazel clean --expunge`, `rm -rf ~/.cache/bazel`, etc.; but none of them prevents Bazel from consulting this cache.

I request a flag to disable the underlying download cache.

Currently, the only workaround is to move the registry to somewhere else, then specify a different `--registry` flag to point to the new registry.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 7.0.0-pre.20231011.2

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
N/A
```

### Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

N/A

**Comment by Wyverald** [comment]
This is probably WAI; the module lockfile (`MODULE.bazel.lock`) stores the resolution result. There is no local cache for registry contents; Bazel assumes registries to be append-only. You could maybe disable the lockfile (`--lockfile_mode=off`), but maybe the better question is -- why do you need to change source.json to point somewhere else?

**Comment by jacky8hyf** [comment]
This is because I am incrementally working on the registry itself. To avoid reaching out to the internet when building, I am trying to checkout a sub-tree of the BCR locally, modify source.json's to point to locally checked out Git projects, then point `--registry` to it. However, I am still at the stage where the registry needs to be tuned so it only contains a minimal set of Bazel modules we use.

Sometimes, a module version (e.g. rules_cc@0.0.3) might be in the module dependency graph, but it is not used. That is, it is in `bazel mod graph --include_builtin --include_unused` but not in `bazel mod graph --include_builtin`. Or sometimes, a module version is in the module dependency graph (e.g. protobuf is in `bazel mod graph --include_builtin`), but no targets actually depend on it, so its sources does not need to be fetched. In these cases, I modify the source.json to an empty directory to make sure we aren't depending on it. Hence, during development, I need to change source.json arbitrarily.

Let me try disabling the lockfile and whether such caching still exist. Thanks for the reply!

**Comment by jacky8hyf** [comment]
I did try adding `--lockfile_mode=off` to my build. `MODULE.bazel` is no longer generated, but it still doesn't seem to re-fetch registry files when I modify them.

> why do you need to change source.json to point somewhere else?

Let me add more details to the answer to this question. The existance of the `--registry` flag indicates that it is valid for a user to use their own registry; the documentation [here](https://bazel.build/external/registry) has the full layout of the registry for a user to create their own. 

When the user creates their registry, it is very common that they do something wrong during development. For example, they may accidentally provide an incorrect path in `local_path` in `source.json`. Perhaps it is a typo. Perhaps they calculate the relative path against `module_base_path` incorrectly. Anyways, they hit the error `No such file or directory` as intended; the error message contains what path that Bazel is actually trying to read from, so the user noticed the bug.

Now, if the user corrects the path in `source.json`, the change is not immediately reflected. Bazel will still use the old path. It appears to me that Bazel caches the file from the registry somewhere. The only way the user can work around this is to perhaps symlink the registry to some other path, and point --registry to that symlinked path.

Hence, I am requesting this feature so the user can force bazel to always re-fetch any file from the registry.

**Comment by Wyverald** [comment]
> I did try adding `--lockfile_mode=off` to my build. `MODULE.bazel` is no longer generated, but it still doesn't seem to re-fetch registry files when I modify them.

You'd still need to shut down the Bazel server (`bazel shutdown`). I understand it's not great usability-wise, but it should achieve the same purpose.

**Comment by jacky8hyf** [comment]
Thanks.

In summary, one needs to run `bazel shutdown` then rebuild with `--lockfile_mode=off` to get the registry refreshed.

I'll put `--lockfile_mode=off` in Kleaf's bazelrc file to mitigate this issue.

**Comment by nachumg** [comment]
Ping, this is definitely required functionality, precisely because local registries will be used for development and testing.

If a local registry source changes, then bzlmod should (by default) see that and regenerate the dep tree.

**Comment by Wyverald** [comment]
Again, Bazel works on the assumption that registry contents are add-only. If that assumption doesn't hold for your case, you'll need to use `bazel shutdown` with `--lockfile_mode=off`.

**Comment by TzachiNoy** [comment]
It makes much sense to assume registry contents are add-only when public, but I agree with @jacky8hyf and @nachumg that for local registry it makes less.

This is very similar to source control, you should not `git commit --amend` to some commit that was already pushed to Github, but you should certainly want the ability to `git commit --amend` to a local commit on your machine.

**Comment by nachumg** [comment]
Referencing https://bazel.build/external/registry#selecting_registries

Can we add a flag like:

--volatile_local_registry=<absolute_path_to_local_registry>

As for --registry, except that if any files under <absolute_path_to_local_registry> are modified then the registry is rebuilt at the next bazel invocation, without regard to --localfile_mode.

**Comment by nachumg** [comment]
Update: I can force re-read of the registry in a wrapper script whenever I want to run bazel:

bazel shutdown

bazel build|run|query|sync \
      '--enable_bzlmod'  \
      '--lockfile_mode=off'  \
      "--registry=file://<absolute-path-to-localhost-registry-root" \
      '--registry=https://bcr.bazel.build'

**Comment by KoltesDigital** [comment]
@nachumg 2 cents, with `file:///` (three slashes) it's relative to the workspace root.

**Comment by tpudlik** [comment]
I think this issue should be reopened. Having to shutdown Bazel every time you modify the local registry is not a great workflow. Could we not do better?

**Comment by malkia** [comment]
Shutting down bazel, and adding --lockfile_mode=off and --batch (well this restarts it) did not solve it for me. 

I had to still manually delete the folder pointed by the `--repository_cache` before each build and then it worked.

This is on Windows with bazel 8.3.1 and this .bazelrc file:

```
common --enable_platform_specific_config
common:windows --shell_executable="c:\\program files\\git\\usr\\bin\\bash.exe"
build --experimental_convenience_symlinks=clean
common --registry=file:///%workspace%/bazel/registry
common --registry=https://bcr.bazel.build/
startup --batch
mod --lockfile_mode=off
try-import %workspace%/../top.bazelrc
```

where my `top.bazelrc` file is: (on my Windows machines)

```
build --disk_cache=q:/b/d
common --repository_cache=q:/b/r
startup --output_user_root=q:/b/u
```

**Comment by rdesgroppes** [comment]
Isn't the need covered by `--lockfile_mode=refresh`? (#22371, since Bazel [7.2.0](https://github.com/bazelbuild/bazel/releases/tag/7.2.0))
