### ISSUE TITLE
[7.1.0] Set minimum heap size for native Turbine to 512 MB

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20475]
Forked from #20360

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
@fmeum @brentleyjones @cushon can you please take a look with cherry-pick this to release-7.1.0?

**Comment by Wyverald** [comment]
closing (see https://github.com/bazelbuild/bazel/issues/20308#issuecomment-1927021148)
