### ISSUE TITLE
failed: missing input file '@@rules_jvm_external~5.2~maven~maven//:WORKSPACE' with Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#20498]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3521#018c5bcb-2afa-49cf-9acd-2e47e4ab118b
Platform : MacOS, Windows, Ubuntu
Logs:
```
(02:22:50) ERROR: /var/lib/buildkite-agent/builds/bk-docker-0hl8/bazel-org-repo-root/bazel/BUILD:177:8: Writing: bazel-out/k8-fastbuild/bin/maven-srcs.tar failed: missing input file '@@rules_jvm_external~5.2~maven~maven//:WORKSPACE'
(02:22:50) ERROR: /var/lib/buildkite-agent/builds/bk-docker-0hl8/bazel-org-repo-root/bazel/BUILD:177:8: Writing: bazel-out/k8-fastbuild/bin/maven-srcs.tar failed: 1 input file(s) do not exist
```
CC Greenteam @comius

**Comment by Wyverald** [comment]
This is likely due to my change that no longer generates a WORKSPACE file (but a REPO.bazel file instead). This is actually technically a breaking change so I'll guard this behavior behind `--noenable_workspace`.

**Comment by Wyverald** [comment]
@bazel-io fork 7.1.0
