### ISSUE TITLE
[bazel.build] Problem with /docs/android-ndk

### ISSUE THREAD

**Issue by AndyHuang1995** [bazelbuild/bazel#20495]
### Page link:

https://bazel.build/docs/android-ndk

### Problem description (include actual vs expected text, if applicable):

Some rules are changed in Bazel 7.0.0
https://blog.bazel.build/2023/11/15/android-platforms.html.

May need to update the document for compiling with NDK

**Comment by meisterT** [comment]
cc @katre

**Comment by katre** [comment]
Thanks, I'll update these.

**Comment by katre** [comment]
Ping @ahumesky and @ted-xie .
