### ISSUE TITLE
Support: bazel cquery --output=files --output_groups=validation

### ISSUE THREAD

**Issue by ismell** [bazelbuild/bazel#20490]
### Description of the feature request:

I have rule that returns runs validations via the `_validation` output group. I would like to be able to query the output group to get a list of files that were generated.

```
OutputGroupInfo(
            logs = depset([output_log_file]),
            traces = depset([output_profile_file]),
            _validation = depset(validation_files),
        ),
```

I'm running the following, but I don't get any outputs:

> bazel cquery --output=files --output_groups=validation,-logs,-traces 'kind("ebuild", deps(@portage//target/virtual/target-os))'

I also tried using `_validation`, but that didn't return anything.

### Which category does this issue belong to?

Core

### What underlying problem are you trying to solve with this feature?

Be able to query the validator outputs on a target.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 6.2.0

**Comment by jin** [comment]
This works for me:

```
bazel cquery //my:target --output=starlark --starlark:expr='providers(target)["OutputGroupInfo"]._validation'
```

Can you try it?

**Comment by ismell** [comment]
Yep, that works!
