### ISSUE TITLE
[bazel.build] Problem with /reference/be/c-cpp

### ISSUE THREAD

**Issue by tcm0116** [bazelbuild/bazel#20504]
### Page link:

https://bazel.build/reference/be/c-cpp

### Problem description (include actual vs expected text, if applicable):

The documentation is relevant for only the latest version of Bazel. However, many users of Bazel are not using the most recent version for various reasons. As such, it is impossible to know from the documentation what features are supported by the version of Bazel being used. For example, the `additional_linker_inputs` attribute was added to `cc_library` in version 6.4.0 (via [this PR](https://github.com/bazelbuild/bazel/pull/19264)), but a user with an older version of Bazel can only determine this by attempting to use the attribute and the receiving an error indicating that `no such attribute 'additional_linker_inputs' in 'cc_library' rule`.

It would be great if the various features could indicate the minimum required Bazel version. As an example, the description for the `additional_linker_inputs` attribute could be modified to be:

>List of [labels](https://bazel.build/concepts/labels); default is []
>
>Pass these files to the C++ linker command.
>For example, compiled Windows .res files can be provided here to be embedded in the binary target.
>
> Requires Bazel 6.4.0 or later.

### Where do you see this issue? (include link to specific section of the page, if applicable)

For the `additional_linker_inputs` example given, the issue is in the Attributes table within the [Arguments](https://bazel.build/reference/be/c-cpp#cc_binary_args) section.

### Any other information you'd like to share?

If implemented, this suggestion should be applied to all Bazel documentation.

**Comment by fmeum** [comment]
While hard to find, the docs are actually versioned (look for a `Version` drop-down in the top-level navigation bar). The default is the current state of the main branch, which isn't ideal but likely subject to change soon.
