### ISSUE TITLE
tools/bazel detection is broken with bzlmod repos

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/bazel#20509]
### Description of the bug:

Bazel's launcher script checks for only WORKSPACE and WORKSPACE.bazel files, and not MODULE.bazel, so the workspace is not detected as a workspace, and hence, a tools/bazel file is not picked up from the workspace.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In any bazel workspace with bzlmod enabled:
1. Delete WORKSPACE and WORKSPACE.bazel files if any.
2. Write a tools/bazel file that prints something before running bazel with all passed arguments.
3. Run any bazel command; notice that tools/bazel is not being run.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 7.0.0

**Comment by Wyverald** [comment]
@bazel-io fork 7.1.0

**Comment by Wyverald** [comment]
should probably also consider this for 7.0.1, should the need arise

**Comment by iancha1992** [comment]
@bazel-io fork 7.0.1

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.0.1 RC2](https://releases.bazel.build/7.0.1/rc2/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!
