### ISSUE TITLE
[7.1.0] Rewrite documentation on Labels

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20507]
Forked from #15821

**Comment by bazel-io** [comment]
The branch, release-7.1.0, may not exist. Please retry the cherry-pick after the branch is created.

**Comment by iancha1992** [comment]
Duplicate issue: https://github.com/bazelbuild/bazel/issues/20534

**Comment by Wyverald** [comment]
note: #20534 and this issue are branched from different original issues and need different commits to be cherry-picked

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
cherry-picked in  https://github.com/bazelbuild/bazel/pull/20978
