### ISSUE TITLE
[7.1.0] failed: missing input file '@@rules_jvm_external~5.2~maven~maven//:WORKSPACE' with Bazel@HEAD

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20512]
Forked from #20498

**Comment by bazel-io** [comment]
The branch, release-7.1.0, may not exist. Please retry the cherry-pick after the branch is created.

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by keertk** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/20914
