### ISSUE TITLE
[7.1.0] tools/bazel detection is broken with bzlmod repos

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20511]
Forked from #20509

**Comment by bazel-io** [comment]
The branch, release-7.1.0, may not exist. Please retry the cherry-pick after the branch is created.

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Already cherry-picked in https://github.com/bazelbuild/bazel/commit/b84528b0c716f4ea5a84c3b9ae15b2defa0a836c. The branch, release-7.1.0, was created after this cherry-pick into 7.0.1.
