### ISSUE TITLE
Cannot properly define prerequisite of py_binary

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2052]
### Description of the problem / feature request / question:

Arg dependency cannot be declared. With the below code I get error:

    in args attribute of py_binary rule //bar:foo: label '//otherstuff:myfile.txt' in $(location) expression is not a declared prerequisite of this rule.

Problem is that I could not yet figure out a way of working around this.

### If possible, provide a minimal example to reproduce the problem:

    py_binary(
      name = "foo",
      args = [
        "$(location //otherstuff:myfile.txt)",
      ],
      srcs = [
        "foo.py",
      ],
      data = [
        "//otherstuff:myfile.txt",
      ],
    )

### Environment info
* Bazel version (output of `bazel info release`): 0.3.2

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

Seems to be similar to #1566. It seems like prereq processing is not properly generalized.

**Comment by ulfjack** [comment]
It sounds like py_binary isn't adding data to the label resolver for $(location); the error message is a bit misleading.

**Comment by ulfjack** [comment]
Ok, looking at the code. py_binary doesn't do anything special AFAICT, and LocationExpander has a hard-coded list of attribute names (*facepalm*). But data is part of that, so it's odd if it's not working.

**Comment by ulfjack** [comment]
I can't reproduce this.

**Comment by abergmeier-dsfishlabs** [comment]
@ulfjack Which version did you check against?

**Comment by ulfjack** [comment]
I checked HEAD, but I also looked for changes since 0.3.2 and did not see anything relevant.

**Comment by abergmeier-dsfishlabs** [comment]
Ok, I will just file another bug should this not work in the future :)
