### ISSUE TITLE
[7.1.0] Workspace, repository, and label terms are still confusing, esp. w.r.t. repostiory_name

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20534]
Forked from #16210

**Comment by bazel-io** [comment]
The branch, release-7.1.0, may not exist. Please retry the cherry-pick after the branch is created.

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
cherry-picked in https://github.com/bazelbuild/bazel/pull/20977
