### ISSUE TITLE
Allow options to use ~ or $HOME

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#2054]
It would be nice for users to be able to specify user-specific paths.  We'd probably have to add support for both client & server path parsing.

See https://github.com/bazelbuild/bazel/issues/1752#issuecomment-258642717 for context.

**Comment by ittaiz** [comment]
this (in combination with #1752) sounds valuable since it lowers the entry costs of an organization. People can check out and best practices are laid out in the shared bazelrc

**Comment by nevion** [comment]
+1
