### ISSUE TITLE
Impossible-to-debug undefined config error

### ISSUE THREAD

**Issue by skye** [bazelbuild/bazel#20554]
### Description of the bug:

I work on the JAX team (https://github.com/google/jax) and am trying to run bazel locally to run JAX tests. However, I can't run anything due to the following error:
```
~/jax$ bazel test --//jax:build_jaxlib=false //tests:cpu_tests
ERROR: Config value 'tpu' is not defined in any .rc file
```
I'm fairly certain something is broken in my environment because we use bazel successfully in CI jobs, but I cannot figure for the life of me figure out how to debug it. There's nothing related to `tpu` in the `.bazelrc` of the current directory or my home directory.

If someone could help me figure this out that'd be great. It would also be good if there were some way to turn on more debug logging to figure out where the `tpu` config is coming from (or does this already exist? I couldn't find anything). Thanks in advance.

### Which category does this issue belong to?

Configurability

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

ERROR: Config value 'tpu' is not defined in any .rc file (I'm using bazelisk though, bazel version is 6.1.2)

**Comment by skye** [comment]
I figured this out actually: there was a stale file called `.jax_configure.bazelrc` generated as part of our build process that I needed to delete. It would still be great if bazel had a way to print all the .bazelrc's etc. it uses to generate its configuration. This should probably be classified as a feature request, sorry!

**Comment by benjaminp** [comment]
`--announce_rc`?

**Comment by skye** [comment]
Ah I missed this in https://bazel.build/reference/command-line-reference, thank you!
