### ISSUE TITLE
[6.5.0] Workspace, repository, and label terms are still confusing, esp. w.r.t. repostiory_name

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20553]
Forked from #16210

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
@Wyverald @fmeum @meteorcloudy
Looks like there are some conflicts when I try to cherry-pick https://github.com/bazelbuild/bazel/commit/1bcb68c6b7ce065ba884e6d6573bd87aebae4c3b to release-6.5.0. 

1) src/main/java/com/google/devtools/build/lib/packages/StarlarkNativeModule.java
We have `BazelStarlarkContext.from(thread).checkLoadingPhase("native.package_name");` in release-6.5.0 branch, but `BazelStarlarkContext.checkLoadingPhase(thread, "native.package_name");` in master branch

`BazelStarlarkContext.from(thread).checkLoadingPhase("native.repository_name");` in release-6.5.0 branch, but `BazelStarlarkContext.checkLoadingPhase(thread, "native.repository_name");` in master branch

`BazelStarlarkContext.from(thread).checkLoadingPhase("native.module_name");` in release-6.5.0 branch, but `BazelStarlarkContext.checkLoadingPhase(thread, "native.module_name");` in the master.

`BazelStarlarkContext.from(thread).checkLoadingPhase("native.module_version")` in release-6.5.0 branch, but `BazelStarlarkContext.checkLoadingPhase(thread, "native.module_version");` in the master.

If you want the changes from the release-6.5.0 branch, then I can continue with cherry-pick and create a PR. But if not then, I am unable to cherry-pick this one.

Thank you.

cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
cherry-pick in https://github.com/bazelbuild/bazel/pull/20590
