### ISSUE TITLE
`context.prefetchInputs` is slow on large set of inputs

### ISSUE THREAD

**Issue by coeuvre** [bazelbuild/bazel#20555]
### Description of the bug:

As shown in https://github.com/bazelbuild/bazel/issues/8230#issuecomment-1852246547, `context.prefetchInputs` takes a couple of seconds on large set of inputs even if all of the inputs are already on the disk. For a no-op prefetch, it should be fast.

**Comment by coeuvre** [comment]
The repro used for the screenshot in https://github.com/bazelbuild/bazel/issues/8230#issuecomment-1852246547 involves remote cache. The downloads may contribute to large portion of `context.prefetchInputs`.

When trying the repro locally with a clean disk cache, I only see ~400ms span of `context.prefetchInputs`.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.1.0 RC1](https://releases.bazel.build/7.1.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!
