### ISSUE TITLE
[6.5.0] Optimize prefetchInputs.

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20562]
Forked from #20557

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
@coeuvre @brentleyjones @tjgq There were two conflicting files when trying to cherry-pick this to 6.5.0 (7.1.0 was cherry-pickable just fyi)

1) src/test/java/com/google/devtools/build/lib/remote/ActionInputPrefetcherTestBase.java
2) src/main/java/com/google/devtools/build/lib/remote/AbstractActionInputPrefetcher.java

Could you please take a look?

cc: @bazelbuild/triage

**Comment by coeuvre** [comment]
I tried manually cherry-pick the commit but it required non-trivial code change to make the commit compatible with 6.5.0. Let's not take the risk of accidentally breaking Bazel 6.x.
