### ISSUE TITLE
[6.5.0] Ignore read-only errors when updating the `mtime` of the `install_base`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20567]
Forked from #20442

**Comment by iancha1992** [comment]
As per:  https://github.com/bazelbuild/bazel/pull/20442#issuecomment-1858349091

cc: @bazelbuild/triage

**Comment by bazel-io** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/20568
