### ISSUE TITLE
instrumentation_filter doesn't control what files will be instrumented

### ISSUE THREAD

**Issue by nlou9** [bazelbuild/bazel#20573]
### Description of the bug:

when I run 
`bazel coverage //ce-audit:all --instrumentation_filter="//ce-audit:ce-audit,-/test/java[/:]"`

But I still find all the test files are in the `_coverage_report.dat`
`SF:ce-audit/src/test/java/AuditLogRouterTest.java`

target `//ce-audit:ce-audit` includes all the files under `ce-audit/src/main/*.java` which are all the src files.

The instrumentation seems not working. My coverage options:

```
coverage --experimental_fetch_all_coverage_outputs 
coverage --experimental_split_coverage_postprocessing
coverage --combined_report=lcov
coverage --remote_download_minimal
```

### Which category does this issue belong to?

Java Rules

### What is the output of `bazel info release`?

6.4.0

**Comment by c-mita** [comment]
> target `//ce-audit:ce-audit` includes all the files under `ce-audit/src/main/*.java` which are all the src files.

`--instrumentation_filter` is a filter on _targets_, not _files_.

So if `//ce-audit:ce-audit` includes all Java source files and is marked as instrumented then you should expect to see all those files in the coverage report.
