### ISSUE TITLE
[Mirror] Go modules

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#20570]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/googleapis/go-genproto/archive/bbf56f31fb17579209f44dda2d2567d20ff21a20.zip
https://github.com/grpc/grpc-go/archive/refs/tags/cmd/protoc-gen-go-grpc/v1.3.0.zip

**Comment by sgowroji** [comment]
Here you go.
1. https://mirror.bazel.build/github.com/googleapis/go-genproto/archive/bbf56f31fb17579209f44dda2d2567d20ff21a20.zip
2.https://mirror.bazel.build/github.com/grpc/grpc-go/archive/refs/tags/cmd/protoc-gen-go-grpc/v1.3.0.zip
