### ISSUE TITLE
Sandboxing in 0.4.0 appears to break $(CC) genrule substitution on OSX

### ISSUE THREAD

**Issue by steven-johnson** [bazelbuild/bazel#2058]
I have a genrule that invokes a bash script, providing it with a value of $(CC) for the script's use:

```
genrule(
    name = "static_link",
    srcs = [...],
    outs = [...],
    cmd = " ".join([
        "bash",
        "$(location //tools:static_link.sh)",
        "\"$(locations :lib_halide_internal)\"", 
        "\"$(CC) $(CC_FLAGS)\"",
        "$@",
    ]),
    tools = [
        "//tools:static_link.sh",
    ],
)

```

This worked correctly in 0.3.2, but is failing in 0.4.0; $(CC) is being expanded to `external/local_config_cc/cc_wrapper.sh`, which doesn't appear to be a valid path during script execution.  Building with `--spawn_strategy=standalone --genrule_strategy=standalone` works fine, so presumably $CC isn't being added to the sandbox. 

Note that this rule works fine on Linux in both 0.3.2 and 0.4.0.

**Comment by steven-johnson** [comment]
Can anyone confirm whether this is an actual bug (vs. I'm doing something wrong that just happened to work before)?

**Comment by hermione521** [comment]
@mhlopko I guess you have an idea how CC works?

**Comment by mhlopko** [comment]
So the genrule will start working if you add //tools/defaults:crosstool to the tools section. I'll try to find out why this works with linux sandbox.

**Comment by ulfjack** [comment]
I think we're using a shell wrapper script on OSX, but not on Linux. The sandbox does not block access to system compilers, but the shell wrapper is somewhere in the workspace. Adding //tools/defaults:crosstool is the right fix for now. We're working on making it so you need to add the correct dependency to even get access to the $(CC) make variable, which makes it more difficult to get this wrong by accident.

**Comment by mhlopko** [comment]
That is indeed what happens. I think we can close this issue. Thanks Steven!

**Comment by steven-johnson** [comment]
> Adding //tools/defaults:crosstool is the right fix for now

Does this mean there is a different fix in the future? (I'm cleaning up old TODOs and trying to figure out if this is something I'll need to circle back to eventually)

**Comment by ulfjack** [comment]
Yes. The plan is to have a special target that provides the make variables
as well as the right files. All genrules that use $(CC) will need to be
updated for that (and similar for Java).

**Comment by steven-johnson** [comment]
Doing a quarterly circle-back on this -- any news on this front? Is it targeted for 0.5?

**Comment by mhlopko** [comment]
Hi Steven,
sorry, no progress, it's not coming in 0.5, and very probably not in this quarter either.
