### ISSUE TITLE
About the time "bazel test" spends

### ISSUE THREAD

**Issue by GinFungYJF** [bazelbuild/bazel#2060]
I get confused about the time "bazel test" spends, for example, I run bazel to test a test_suite:
`____Elapsed time: 8.153s, Critical Path: 7.95s
//s/a                         PASSED in 3.6s
//s/b                        PASSED in 0.9s
//s/c                         PASSED in 0.8s
//s/d                        PASSED in 5.6s
//s/e                        PASSED in 5.3s
//s/f                         PASSED in 1.9s`

Why the time Critical Path spends is not 5.6s? And how could the test of test_suite speed up? 

### Environment info
* Operating System:
`Ubuntu 14.04.5 LTS`

* Bazel version (output of `bazel info release`):
`0.3.1`

**Comment by aehlig** [comment]
> Why the time Critical Path spends is not 5.6s?

Were there any compile steps necessary before starting the first test?
Compiling tools required for the test also count towards the ciritical
path (but not to the time spent in the test).

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle
