### ISSUE TITLE
[Mirror] gazelle v0.34.0

### ISSUE THREAD

**Issue by tyler-french** [bazelbuild/bazel#20639]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.35.0/bazel-gazelle-v0.35.0.tar.gz

**Comment by sgowroji** [comment]
https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.35.0/bazel-gazelle-v0.35.0.tar.gz
