### ISSUE TITLE
test methods within a single test class paralled

### ISSUE THREAD

**Issue by ddwolf** [bazelbuild/bazel#2064]
is there a way to make bazel test running the methods in a single test class multi-threaded?

**Comment by benley** [comment]
What language are you working with?  What test framework?

**Comment by ddwolf** [comment]
@benley I just run test under bazel, using bazel's test command.
bazel test ...

oh, I am working with java, and spring framework.

**Comment by ddwolf** [comment]
@benley I just run test under bazel, using bazel's test command.
bazel test ...

oh, I am working with java, and spring framework.

**Comment by ddwolf** [comment]
@benley I just run test under bazel, using bazel's test command.
bazel test ...

oh, I am working with java, and spring framework.

**Comment by ddwolf** [comment]
@benley I just run test under bazel, using bazel's test command.
bazel test ...

oh, I am working with java, and spring framework.

**Comment by ddwolf** [comment]
@benley I just run test under bazel, using bazel's test command.
bazel test ...

oh, I am working with java, and spring framework.

**Comment by aehlig** [comment]
If you're using Bazel's [`java_test`](https://bazel.build/versions/master/docs/be/java.html#java_test), you might want to look at the [`shard_count`](https://bazel.build/versions/master/docs/be/common-definitions.html#test.shard_count). If this is not what you've been looking for, can you please describe in more detail what you need.

**Comment by GinFungYJF** [comment]
@aehlig I set shard_count in my java_test, but it seems to take more time.

**Comment by GinFungYJF** [comment]
@aehlig The log of one of the sharding:
`-----------------------------------------------------------------------------
JUnit4 Test Runner
CORE is running

 :: Spring Boot ::        (v1.3.5.RELEASE)


Time: 7.774

OK (1 test)


BazelTestRunner exiting with a return value of 0
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2016-11-14 03:53:59 --`

Does it shows that every sharding would start an JVM? Is it the reason why setting shard_count takes more time?

**Comment by GinFungYJF** [comment]
@aehlig The log of one of the sharding:
```
-----------------------------------------------------------------------------
JUnit4 Test Runner
CORE is running
.
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.3.5.RELEASE)


Time: 7.774

OK (1 test)


BazelTestRunner exiting with a return value of 0
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2016-11-14 03:53:59 --
```
Does it show that every sharding would start an JVM? Is it the reason why setting shard_count takes more time?

**Comment by ddwolf** [comment]
@aehlig GinFungYJF have provided the messages I have, after I use shard option, the test process takes more time, that's not what I want.

**Comment by ulfjack** [comment]
There's more discussion of sharding in #2113. I'm not sure there are any action items here for us. There may be a junit extension to do multi-threading within a single Jvm, if the Jvm startup overhead is too large for sharding...

**Comment by damienmg** [comment]
There is an on-going work to make junit test faster to avoid JVM startup time. I don't think we can do more than that.

Closing this issue since there is no specific action item for it.

**Comment by ddwolf** [comment]
@damienmg: have you considered using junit's `ParallelComputer` to make the test running faster?

**Comment by damienmg** [comment]
No I don't think so, our sharding tooling dates back from JUnit3 where there was no such thing as ParallelComputer. It also has some hermeticity issues.

**Comment by ulfjack** [comment]
We could potentially add support for parallel computer on an opt-in basis as well. Feel free to file a feature request for that. So far we have not looked at that, and it also hasn't been a good match for how our internal systems work.

**Comment by ddwolf** [comment]
@ulfjack I am working on that:) some problems...

**Comment by ddwolf** [comment]
@ulfjack I am working on that:) some problems...the spring initializing failed when I import ParallelComputer into bazel.
