### ISSUE TITLE
clang missing from sandbox

### ISSUE THREAD

**Issue by salguarnieri** [bazelbuild/bazel#2065]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

clang is sometimes not pushed into the sandbox. This seems to only happen on OS X.

Repo: https://github.com/google/kythe

build succeeds with:
bazel build //kythe/release --spawn_strategy=standalone

but fails with
bazel build //kythe/release

ERROR: .../kythe/third_party/zlib/BUILD:10:1: C++ compilation of rule '//third_party/zlib:zlib' failed: sandbox-exec failed: error executing command /usr/bin/sandbox-exec -f .../bazel-sandbox/e47e8ba2-ffbf-416a-9b90-b2231feb644e-0/sandbox.sb external/local_config_cc/clang -g0 -O2 ... (remaining 23 argument(s) skipped).
sandbox-exec: external/local_config_cc/clang: No such file or directory
Target //kythe/release:release failed to build

### Environment info
* Operating System:
OS X

* Bazel version (output of `bazel info release`):
release 0.4.0-homebrew

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

I found the spawn strategy workaround in https://github.com/bazelbuild/bazel/issues/698

I attached the output with --verbose_failures and --sandbox_debug
[bazel_output.txt](https://github.com/bazelbuild/bazel/files/581599/bazel_output.txt)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by aehlig** [comment]
@philwo, can you have a look at this issue? You're probably most knowledgable about the specification of what goes into the sandbox.

**Comment by hermione521** [comment]
According to the log, we are looking for `external/local_config_cc/clang` which is not there.
I believe it should be auto-configured? @lberki

**Comment by steven-johnson** [comment]
Looks like the same issue I reported in Issue #2058

**Comment by mhlopko** [comment]
Yeah it looks similar. Let me investigate.

**Comment by damienmg** [comment]
Ok debugging:
```
$ cat $(bazel info output_base)/external/local_config_cc/CROSSTOOL | grep clang
  compiler: "clang"
  tool_path { name: "gcc" path: "/usr/bin/clang" }
 cxx_builtin_include_directory: "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/include"
  compiler: "clang"
  tool_path { name: "gcc" path: "clang" }
 cxx_builtin_include_directory: "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/include"
```

So the compiler path for clang is wrong in the second instance

**Comment by damienmg** [comment]
Cannot find that entry on the Bazel repository, so it is not coming from cc_configure.bzl. Kythe is probably tweaking the c++ toolchain

**Comment by mhlopko** [comment]
Here? https://github.com/google/kythe/blob/dde5e72515513b3d4cb0b90855d7839d87733b12/tools/cpp/clang_configure.bzl

**Comment by damienmg** [comment]
Yes :) so that's a kythe bug

**Comment by damienmg** [comment]
So closing because the bug already exist on kythe side.

The clang_configure.bzl should write the full path to clang

**Comment by salguarnieri** [comment]
Thanks for the help!

**Comment by damienmg** [comment]
You're welcome :)
