### ISSUE TITLE
let cc_library's includes parameter can use $(location)

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/bazel#20670]
think about such a situation, a genrule generate a file named config.h, this config.h was included by a source file use
```
#include <config.h>
```
this means, directory that contains config.h must be add to search path by -isystem, I know bazel-7.0.0 cc_library has  additional_compiler_inputs parameter, then use 
```
$(location :config_h) 
```
to get config.h's path in copts,  can also  let includes parameter in cc_library use $ (location) or $ (directory)?

![image](https://github.com/bazelbuild/bazel/assets/8072296/dd67c074-3487-46b6-b8ed-55ea43754908)

![image](https://github.com/bazelbuild/bazel/assets/8072296/5459639e-4894-48de-bc74-9b41f6ebeae1)

here is a demo
https://github.com/xiedeacc/libdwarf.git

bazel 7.0.0

**Comment by comius** [comment]
It’s a rare use, where I think include path is good enough hardcoded. Supporting functions in include attribute would make implementation more complex than needed.

**Comment by xiedeacc** [comment]
your kown many project not support bazel，so it's hard to write build file for  such situation，and I find a lot of project include header file use system style， so a predefines variable can get label's directory is indeed needed

**Comment by xiedeacc** [comment]
see https://github.com/bazelbuild/bazel/issues/20669
