### ISSUE TITLE
Stale issue closer asks users to do something they literally cannot do.

### ISSUE THREAD

**Issue by chandlerc** [bazelbuild/bazel#20671]
### Description of the bug:

The bot closing stale issues gives instructions that users literally cannot follow:

> Please reach out to the triage team (`@bazelbuild/triage`) if you think this issue is still relevant or you are interested in getting the issue resolved.

Users cannot `@` that team in an issue. I have no idea as a user how to contact this team. Please change this to provide some steps, any steps, that I can do to keep the issues I have filed and continue to hit while using Bazel every day open.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

File an issue and wait for a year.

### Any other information, logs, or outputs that you want to share?

Sorry I can't fill out the rest of the issue form, this is a bug in the Bazel GitHub project, not in Bazel itself.

**Comment by sgowroji** [comment]
Hi @chandlerc, What is the problem are you seeing in tagging with @bazelbuild/triage ? Could you please take screenshot and share for a reference. The main Reason to tag that team, so who ever available can reach and ack on the issues immediately. So those important comments should not go stale.

**Comment by chandlerc** [comment]
> Hi @chandlerc, What is the problem are you seeing in tagging with @bazelbuild/triage ? Could you please take screenshot and share for a reference. The main Reason to tag that team, so who ever available can reach and ack on the issues immediately. So those important comments should not go stale.

So, I can't tab complete or do anything else that seems to confirm that I have actually `@`-ed a team when I type `@bazelbuild/triage` as I did in https://github.com/bazelbuild/bazel/issues/2537#issuecomment-1868650567

Maybe it actually does `@` that team, but there is *nothing* to indicate that happens, and everything about the UI indicates that I cannot `@` this team in this way.

In other organizations, teams can be easily `@`-ed, with tab completion and clear UI elements that indicate the team is CC-ed. So maybe there is a way to set things up that makes tagging the team work better? Not sure, I'm not a GitHub expert, but am maybe accurately reflecting how an average user will encounter these messages.

Another alternative is to set up some automation to CC the relevant teams on any comment after a staleness update? Or other ways to make it easier for users to figure out what they should do?

**Comment by fmeum** [comment]
Could we just make https://github.com/orgs/bazelbuild/teams/triage a public team?

**Comment by Wyverald** [comment]
> Could we just make https://github.com/orgs/bazelbuild/teams/triage a public team?

It's already public -- but GitHub has this to say:

> A visible team can be seen and [@mentioned](https://github.blog/2012-05-09-introducing-team-mentions/) by every member of this organization.

**Comment by Wyverald** [comment]
@chandlerc, thanks for flagging this -- it looks like the `@` mention does work, but if you're not part of the "bazelbuild" organization, the UI does nothing to suggest that it would work.

So we might need to rely on some bespoke automation. I'm thinking we could make a command like `@bazel-io not stale` or some such to remove the 'stale' label.

**Comment by chandlerc** [comment]
> @chandlerc, thanks for flagging this -- it looks like the `@` mention does work, but if you're not part of the "bazelbuild" organization, the UI does nothing to suggest that it would work.

Good to know that it was working I guess? The suggestion also talks about changing labels which doesn't seem to make sense outside the org...

> 
> So we might need to rely on some bespoke automation. I'm thinking we could make a command like `@bazel-io not stale` or some such to remove the 'stale' label.

Yeah, I'd suggest doing something that makes it much more clear to users what's going on. An action that they technically can take but that they'll never know if they typo or get wrong seems likely to both cause user frustration and also frequent accidental failures.

TBH, I would suggest something like *any* comment or a thumbs-down reaction to the stale-marking-comment as sufficient for whatever automation to flag it for the triage team.

When a robot marks an issue a user reported as stale due to *over a year without comment*, it's going to be a pretty rough experience for the reporter. I think that it's worthwhile to do everything you can in automation rather than exacerbating this with complex steps that the reporter must do to keep the issue open. So something super simple, both of which are trivially in their remit to do seems like a much better experience. For example, text like: "Add any comment indicating it is still relevant or react to this with a thumbs down and we'll put the issue in the queue for the Bazel triage team".

**Comment by keertk** [comment]
Thanks for the feedback, @chandlerc. We've addressed this in https://github.com/bazelbuild/bazel/commit/b4dc572b0dc357d7e9d3004f1e3641f20d23fd1d. Closing this issue.
