### ISSUE TITLE
Filter out shared resources and native libs from android instrumentation test apk

### ISSUE THREAD

**Issue by ThomasCJY** [bazelbuild/bazel#20682]
### Description of the bug:

Bazel build always includes redundant resources and native libs inside its instrumentation apk binary file. The `instruments = ":app_apk",` parameter in `android_binary` rule already strips the shared classes in test apk. But it doesn't strip the resources and native libraries. 

In a large android repository, this bug could introduce 100 Mb+ redundant test apk size for each build. It will be helpful if we can fix it and make test apk cleaner.

### Which category does this issue belong to?

Android

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I created this test repo https://github.com/ThomasCJY/testApp/tree/bazel-instrumentation-test-branch to easily reproduce this bug.

**Comment by ahumesky** [comment]
The native version of android_instrumentation_test has been removed from bazel 8 and migrated to Starlark in https://github.com/bazelbuild/rules_utp, if this is still an issue in the Starlark version please file an issue there.
