### ISSUE TITLE
//src/test/java/com/google/devtools/build/lib:foundations_test flaky

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/bazel#2068]
Running this test randomly times out in about 10% of all invocations. The underlying issue, however, is not a too short timeout; on my machine, a passing invocation takes about 25s whereas it still times out on my machine with timeout 300s.

The flaky timeouts can also be seen on ci, e.g., http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=latest-jdk7,PLATFORM_NAME=ubuntu_15.10-x86_64/318/console

**Comment by ulfjack** [comment]
There is a (non-deterministic) deadlock in one of our concurrency tests. Maybe that's the reason?

**Comment by damienmg** [comment]
Another instance: http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/383/console

**Comment by ulfjack** [comment]
This ones a failure, not a timeout. The deadlock I mentioned above is unrelated.

**Comment by damienmg** [comment]
Indeed but it does looks like a FS concurrency issue.

If this test is known to be flaky we should really fix our flaky support and mark it as flaky

**Comment by damienmg** [comment]
With `git bisect run bazel build //:protoc` the js culprit is 5a76e633ea9b5adb215e93fdc11e1c0c08b3fc74

**Comment by damienmg** [comment]
By sharding then deactivating the timeout is not from the same test. Culprit is  com.google.devtools.build.lib.concurrent.MultisetSemaphoreTest, removing the test until we can fix #540

**Comment by damienmg** [comment]
Assigning to Nathan who is the original writer of the test.

Repro `bazel test --runs_per_test 10 //src/test/java/com/google/devtools/build/lib:foundations_test`, selecting only MultisetSemaphoreTest does not trigger the flake so it might have some interaction issues with other tests.

Maybe the solution is to extract that test in a separate process.

**Comment by damienmg** [comment]
side-note: I fixed #540 should be here in a few hours but we still needs to wait for it to be released to actually supress the flake (because 0.4.3 will just run it once, so we would still see the flake on ci.bazel.io)

**Comment by meisterT** [comment]
Test doesn't exist anymore and this issue was not pinged since three years.
