### ISSUE TITLE
How to know when data is purgeable from repo cache?

### ISSUE THREAD

**Issue by Ryang20718** [bazelbuild/bazel#20685]
https://github.com/bazelbuild/bazel/commit/7a774ff7c5850e7bd57af840a0e097ad4ec25417

This modifies mtime for files accessed via remote cache. However, for external repos, it seems like there's not a surefire way to determine if something is stale...

I.e on bazel 7.0.0, 

if I have a file that leverages a bazel_skylib function, should I see the mtime refresh & update the next time I build a any target that leverages a bazel_skylib function?

I.e

Build, check atime, build, check atime. it seems to be the same even though I waited 5 minutes later to build
```
ls -lu ~/.cache/bazel/_bazel_ryang/d74806228f9a8a972e76dd6f55d51b26/external/ | grep bazel_skylib
drwxrwxr-x   5 ryang ryang  4096 Dec 28 00:29 bazel_skylib
-rw-rw-r--   1 ryang ryang   107 Dec 28 00:32 @bazel_skylib.marker
...
ls -lu ~/.cache/bazel/_bazel_ryang/d74806228f9a8a972e76dd6f55d51b26/external/ | grep bazel_skylib
drwxrwxr-x   5 ryang ryang  4096 Dec 28 00:29 bazel_skylib
-rw-rw-r--   1 ryang ryang   107 Dec 28 00:32 @bazel_skylib.marker
```

**Comment by tjgq** [comment]
The disk cache is only accessed if Bazel determines that an action must execute. If you run an incremental build with no changes (i.e., you didn't `bazel clean`, nor otherwise touch any source or output files), Bazel can tell that the output tree is up to date and won't execute anything. If you modify source or output files before incrementally rebuilding, Bazel will execute any affected actions (and only those), which will retrieve them from the disk cache if possible and update their mtime.

This applies regardless of which repository (main or external) the actions are defined in.

**Comment by Ryang20718** [comment]
What is the best way to identify "stale" or no longer used artifacts? 😓 we're running into disk cache issues constantly and would like to be able to prune only things we don't need.

I.e if I have the following
```
    s3_archive(
        name = "test-file-12-29",
        bucket = "fake",
        build_file_contents = _all_files(".txt"),
        file_path = "test-file-12-29.txt",
        sha256 = "5836ffe505ef3338b93744476e5a6a6586ae724273531393facb45208622bbbf",
    )
```

bazel build, and then later down the line want to replace this with another file more up to date, then `test-file-12-29` will still remain in the external bazel-out folder and eventually we'll have to purge the disk? 
```
    s3_archive(
        name = "test-file-12-30",
        bucket = "fake",
        build_file_contents = _all_files(".txt"),
        file_path = "test-file-12-30.txt",
        sha256 = "5836ffe505ef3338b93744476e5a6a6586ae724273531393facb45208622bbbf",
    )
```

**Comment by Ryang20718** [comment]
or is `bazel-out` the only directory we can clear from safely? (i.e if we clear from here, it won't prevent bazel from not building in subsequent build)

**Comment by coeuvre** [comment]
I think the question is more about repo cache, not disk cache.

**Comment by fmeum** [comment]
There are three separate locations you may want to clear:
* the disk cache, which is only used if you explicitly specify `--disk_cache`. See https://github.com/bazelbuild/bazel/issues/5139 for advice on how to clean it.
* the repo cache, which is used by default, should really be called "download cache" instead and lives in a directory such as `/home/user/.cache/bazel/_bazel_user/cache/repos`. In your use case, the different downloads will accumulate there over time. You can safely purge any of the hash-named subdirectories or the entire directory at any time. In the worst case, Bazel will redownload something it has downloaded before.
* the `external` directory under the output base. This is what you are referring to in the issue description. This is where Bazel fetches external repositories to. For example, this will contain the extracted contents of an `http_archive`. It's likely fine to purge this if you delete both a directory corresponding to a repository and the `.marker` file next to it at the same time, but that's not explicitly guaranteed as far as I know. You will see atime updates only if Bazel accesses the files, which it doesn't if they don't change and it keeps them in memory. Even mtime may change only rarely as Bazel usually doesn't refetch the repo unless you change the definition. `bazel clean --expunge` is a way to clean up all of these repos, but if you aren't using a disk cache, you will have to build from scratch afterwards.

**Comment by Wyverald** [comment]
If the above hasn't answered your question, please start a GitHub discussion instead. Thanks!
