### ISSUE TITLE
Bazel CI flaky src.test.shell.bazel.bazel_bootstrap_distfile_test test_bootstrap

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#20692]
[https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/01884406-8e1b-75f6-bd1a-7e06f2492152?branch=master](https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/01884406-8e1b-75f6-bd1a-7e06f2492152?branch=master)

Logs:

```
Generated bazel not working
[32mComputing main repo mapping:[0m 

[1A[K[32mLoading:[0m 

[1A[K[32mLoading:[0m 0 packages loaded

[1A[K[32mLoading:[0m 0 packages loaded
    currently loading: src
    Fetching repository @@rules_python~0.26.0; starting
```

CC Greenteam @SalmaSamy

**Comment by meteorcloudy** [comment]
No longer happening.
