### ISSUE TITLE
How to install bazel@7.0.0 on MacOS via homebrew or Bazelisk

### ISSUE THREAD

**Issue by xushaoxiao** [bazelbuild/bazel#20700]
### Description of the feature request:

Hi teams,

The version 6.4.0 is used on my MaxOS, i wanna to upgrade to 7.0.0, but it's failed.

- brew update && brew upgrade bazel
- brew uodate && brew upgrade bazelisk

### Which category does this issue belong to?

Starlark Integration

### What underlying problem are you trying to solve with this feature?

`➜  allinone-via-bazelmod git:(main) ✗ bazelisk build //... --enable_bzlmod
ERROR: Bazel version 6.4.0 is not compatible with module "rules_java@7.3.2" (bazel_compatibility: [>=7.0.0])
ERROR: Error computing the main repository mapping: Bazel compatibility check failed`

### Which operating system are you running Bazel on?

Mac os

### What is the output of `bazel info release`?

release 6.4.0

**Comment by fmeum** [comment]
What is the content of your `.bazelversion` file? `bazelisk` uses whatever version is specified there, regardless of which Bazel version you installed locally.

**Comment by xushaoxiao** [comment]
> bazelversion

it's empty, `.bazelversion` file not include any text.

**Comment by xushaoxiao** [comment]
<img width="778" alt="image" src="https://github.com/bazelbuild/bazel/assets/83151234/e0fb4ecc-a5e0-45fa-9d7c-e625c7de0fae">

refer to https://github.com/xushaoxiao/allinone-via-bazelmod , thank you.

**Comment by luangong** [comment]
@xushaoxiao On macOS with Homebrew, `bazel` conflicts with `bazelisk` (because both install the `bazel` binary to PATH). It’s recommended to uninstall `bazel` and install `bazelisk` and then specify the version of Bazel to download and use in the project-specific `.bazelversion` file.

**Comment by Wyverald** [comment]
Thank you @luangong for the suggestion -- that's likely what's happening here.

Also @xushaoxiao, for future reference, please refrain from asking us to debug using an "all-in-one" repo. It would save everyone time if you could produce a minimal reproduction case.
