### ISSUE TITLE
[bazel.build] Problem with /docs/user-manual

### ISSUE THREAD

**Issue by limdor** [bazelbuild/bazel#20707]
### Page link:

https://bazel.build/docs/user-manual

### Problem description (include actual vs expected text, if applicable):

dynamic_mode=auto does not exist

The auto option should be removed: https://github.com/bazelbuild/bazel/pull/20705

If you try to use auto, the following error appears:
`ERROR: While parsing option --dynamic_mode=auto: Not a valid dynamic mode: 'auto' (should be off, default or fully)`

### Where do you see this issue? (include link to specific section of the page, if applicable)

https://bazel.build/docs/user-manual#dynamic-mode

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.5.0 RC2](https://github.com/bazelbuild/bazel/releases/tag/7.5.0rc2). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.5.0rc2. Thanks!
