### ISSUE TITLE
sh_test text.xml format doesn't match JUnit format

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#2070]
This is making it difficult to use tools that consume test output.

**Comment by damienmg** [comment]
This is Junit ant XML format, Jenkins has no problem consuming it

**Comment by kchodorow** [comment]
It doesn't have some of the fields expected.

**Comment by ulfjack** [comment]
Which fields are missing?

**Comment by kchodorow** [comment]
It was missing failures= and errors= fields due to a bash typo, which was fixed by 8dc0810.
