### ISSUE TITLE
Bazel 7.0.0 & Lombok 1.18.30 issue

### ISSUE THREAD

**Issue by liam-kincaid** [bazelbuild/bazel#20702]
### Description of the bug:
[sample-1.0.0.tar.gz](https://github.com/bazelbuild/bazel/files/13800601/sample-1.0.0.tar.gz)

I create a Bzlmod 7.0.0 with lombok 1.18.30 and Java 17
Why i do this, to have a custom "build" method with hibernate validation for an immutable entity

Archive contains a demo of my issue
Here is the issue during JAVA 17 compilation:

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging

```
src/main/java/entity/User.java:60: error: could not resolve element onParam_() in lombok.With
		@With(onParam_={
        ^
src/main/java/entity/User.java:63: error: could not resolve element onMethod_() in lombok.With
		}, onMethod_={
     ^
src/main/java/entity/User.java:68: error: could not resolve element onParam_() in lombok.With
		@With(onParam_={
        ^
src/main/java/entity/User.java:72: error: could not resolve element onMethod_() in lombok.With
		}, onMethod_={
     ^
src/main/java/entity/User.java:77: error: could not resolve element onParam_() in lombok.With
		@With(onParam_={
        ^
src/main/java/entity/User.java:82: error: could not resolve element onMethod_() in lombok.With
		@With(onMethod_={
        ^
<>: error: Turbine is not currently supported by lombok.
```

It seem to appear only with "onMethod_" and "onParam_" attribut with Lombok.
A pom.xml is also join and compilation & test are successfull

### Which operating system are you running Bazel on?

Ubuntu 23.10

### What is the output of `bazel info release`?

release 7.0.0

**Comment by cushon** [comment]
Did this work for you with earlier Bazel versions? There are known pre-existing issues with Lombok: https://github.com/bazelbuild/bazel/issues/12837

**Comment by liam-kincaid** [comment]
I have made test also with 6.3.2 with the same consequences.
It seam to be a duplicate if I understand. Right ?

**Comment by cushon** [comment]
Thanks, yes, it sounds like a duplicate
