### ISSUE TITLE
[7.1.0] Fix two issues with --incompatible_sandbox_hermetic_tmp that manifested themselves when the output base was under /tmp

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#20717]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/fb6658c86164b81205a056a9a54975a62f2f957a

### Category

team-Local-Exec

### Reviewers

@lberki, @meteorcloudy, @fweikert

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20718: https://github.com/bazelbuild/bazel/commit/fb6658c86164b81205a056a9a54975a62f2f957a.

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20766: https://github.com/bazelbuild/bazel/commit/fb6658c86164b81205a056a9a54975a62f2f957a.
