### ISSUE TITLE
[7.0.1] Bzlmod lockfile does not track repository mappings of extension `.bzl` files

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20723]
Forked from #20721

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/20750

**Comment by Wyverald** [comment]
The mainline issue was reopened. We should cherry-pick #20830 when it's submitted.

**Comment by Wyverald** [comment]
cherry-picked in #20848
