### ISSUE TITLE
Disable PyTest.testSmoke on macOS

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#20728]
### Commit IDs

d9dc4fde4c8d06498f39b54a81d4e7fa1e5b5b30

### Category

team-Rules-Python

### Reviewers

meteorcloudy

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20729: https://github.com/bazelbuild/bazel/commit/d9dc4fde4c8d06498f39b54a81d4e7fa1e5b5b30.

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20730: https://github.com/bazelbuild/bazel/commit/d9dc4fde4c8d06498f39b54a81d4e7fa1e5b5b30.

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20731: https://github.com/bazelbuild/bazel/commit/d9dc4fde4c8d06498f39b54a81d4e7fa1e5b5b30.
