### ISSUE TITLE
[Mirror] rules go 0.44.1 and 0.44.2

### ISSUE THREAD

**Issue by tyler-french** [bazelbuild/bazel#20735]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/rules_go/releases/download/v0.44.2/rules_go-v0.44.2.zip
https://github.com/bazelbuild/rules_go/releases/download/v0.44.1/rules_go-v0.44.1.zip

**Comment by sgowroji** [comment]
Here you go

1.  [https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.44.2/rules_go-v0.44.2.zip](https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.44.2/rules_go-v0.44.2.zip)
2.  [https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.44.1/rules_go-v0.44.1.zip](https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.44.1/rules_go-v0.44.1.zip)
