### ISSUE TITLE
[Mirror] `pkgconfig-0.29.2` `gettext-runtime-0.18.1.1-2` `glic-2.26.1-1 + dev_2.26.1-1` `meson-0.63.0 + 1.1.1` `ninja 1.10.2 1.11.0 1.11.1`

### ISSUE THREAD

**Issue by mishazharov** [bazelbuild/bazel#20740]
### Please list the URLs of the archives you'd like to mirror:

https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
https://download.gnome.org/binaries/win64/dependencies/gettext-runtime_0.18.1.1-2_win64.zip
https://download.gnome.org/binaries/win64/glib/2.26/glib_2.26.1-1_win64.zip
https://download.gnome.org/sources/glib/2.26/glib-2.26.1.tar.gz
https://download.gnome.org/binaries/win64/glib/2.26/glib-dev_2.26.1-1_win64.zip
https://github.com/mesonbuild/meson/releases/download/0.63.0/meson-0.63.0.tar.gz
https://github.com/mesonbuild/meson/releases/download/1.1.1/meson-1.1.1.tar.gz
https://github.com/ninja-build/ninja/archive/v1.10.2.tar.gz
https://github.com/ninja-build/ninja/archive/v1.11.0.tar.gz
https://github.com/ninja-build/ninja/archive/v1.11.1.tar.gz

These URL are from https://github.com/bazelbuild/rules_foreign_cc/blob/ddda554d2a5d208c60ce00ccc83a2ca0b8ab5a9c/toolchains/built_toolchains.bzl#L1

**Comment by sgowroji** [comment]
Hi @mishazharov, Here they are 

1.   [https://mirror.bazel.build/pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz](https://mirror.bazel.build/pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz)
2.  [https://mirror.bazel.build/download.gnome.org/binaries/win64/dependencies/gettext-runtime_0.18.1.1-2_win64.zip](https://mirror.bazel.build/download.gnome.org/binaries/win64/dependencies/gettext-runtime_0.18.1.1-2_win64.zip)
3.  [https://mirror.bazel.build/download.gnome.org/binaries/win64/glib/2.26/glib_2.26.1-1_win64.zip](https://mirror.bazel.build/download.gnome.org/binaries/win64/glib/2.26/glib_2.26.1-1_win64.zip)
4.  [https://mirror.bazel.build/download.gnome.org/sources/glib/2.26/glib-2.26.1.tar.gz](https://mirror.bazel.build/download.gnome.org/sources/glib/2.26/glib-2.26.1.tar.gz)
5.  [https://mirror.bazel.build/download.gnome.org/binaries/win64/glib/2.26/glib-dev_2.26.1-1_win64.zip](https://mirror.bazel.build/download.gnome.org/binaries/win64/glib/2.26/glib-dev_2.26.1-1_win64.zip)
6.  [https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/0.63.0/meson-0.63.0.tar.gz](https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/0.63.0/meson-0.63.0.tar.gz)
7.  [https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/1.1.1/meson-1.1.1.tar.gz](https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/1.1.1/meson-1.1.1.tar.gz)
8.  [https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.10.2.tar.gz](https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.10.2.tar.gz)
9.  [https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.11.0.tar.gz](https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.11.0.tar.gz)
10.  https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.11.1.tar.gz

**Comment by mishazharov** [comment]
Awesome, thank you for the quick response!
