### ISSUE TITLE
[7.1.0] Bazel 7: `--sandbox_add_mount_pair` under `/tmp` fails

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20765]
Forked from #20527

**Comment by iancha1992** [comment]
Is this one needed? because we have https://github.com/bazelbuild/bazel/pull/20772.

cc: @bazelbuild/triage @lberki

**Comment by iancha1992** [comment]
Closing as there's nothing to commit/push

@bazelbuild/triage
