### ISSUE TITLE
[7.1.0] `java_binary` wrapper should forward `restricted_to`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20763]
Forked from #20600

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by meteorcloudy** [comment]
This was already cherry-picked https://github.com/bazelbuild/bazel/commit/b441ee5c6ed5d4643431add71c62bd977ac922ce
