### ISSUE TITLE
Refactor `bazel clean --expunge` in TF

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2077]
Fix https://github.com/bazelbuild/bazel/issues/1586  and remove the magic for cleaning output base directory in 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/windows/cpu/pip/build_tf_windows.sh#L58

And enable `bazel clean --expunge` in https://github.com/tensorflow/tensorflow/blob/master/configure#L25

**Comment by dslomov** [comment]
Close in favor of #2480. Workaround in TF is implemented.
