### ISSUE TITLE
[7.1.0] Bzlmod lockfile does not track repository mappings of extension `.bzl` files

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20770]
Forked from #20721

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
cherry-picked in https://github.com/bazelbuild/bazel/pull/21033
