### ISSUE TITLE
starlark_repository_test is failling with Bazel@HEAD


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#20790]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3577#018ce8de-917e-4943-82b5-5d4e4ba930e0

 Platform: Ubuntu

 Logs: 
```
//src/test/shell/bazel:starlark_repository_test                          FAILED in 3 out of 8 in 157.2s
```

 CC Greenteam @fweikert

**Comment by Wyverald** [comment]
This one has been flaky for a while, I think.

**Comment by Wyverald** [comment]
test analytics link: [`test_disable_download_should_prevent_downloading `](https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/01884414-6851-7896-b012-db2e42b937b7?branch=master) and [`test_starlark_headers_override_default_headers`](https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/018c4464-e9f7-7f8e-a6e6-29018c57827f?branch=master)

The two test cases above are by far the worst offenders. The failure has been observed on all Linux platforms (CentOS & the various Ubuntus), but never on macOS.

**Comment by Wyverald** [comment]
Found a failure on macOS too -- https://buildkite.com/bazel/bazel-bazel/builds/26163#018ceb78-abeb-4b5e-8420-7b4cd05ddee7
