### ISSUE TITLE
//src/test/cpp/util:file_platform_test fails to build

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/bazel#2079]
see http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/321/console

**Comment by kchodorow** [comment]
This was fixed by d92b684f9b90ce40c4f4662a382e3fe5bd2c353d, right?

**Comment by laszlocsomor** [comment]
Yes it was.
