### ISSUE TITLE
Support Android Robolectric test rules

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2080]
Child feature of #903 for robolectric test.

Assigning to @aj-michael who is currently submitting the work

**Comment by aj-michael** [comment]
Plans may have changed about submitting the robolectric test rule in its current state. @damienmg , I've posted a comment internally about some proposed design changes

**Comment by ronshapiro** [comment]
Is there any update on this?

**Comment by aj-michael** [comment]
I believe 2ef5d2170e0558468b0c0e989b910fbb52e95368 should have been tagged with this issue number

**Comment by ronshapiro** [comment]
Should it be documented in the [Build Encyclopedia](https://docs.bazel.build/versions/master/be/android.html)?

**Comment by jin** [comment]
I guess this can be closed now? @dkelmer
