### ISSUE TITLE
Refactor splitting of LinkerCommandLine

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#20817]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/b5cfea5f86830648dcecc55af6557fc7832ab11e

### Category

team-Rules-CPP

### Reviewers

@comiu

**Comment by bazel-io** [comment]
Failed commmits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/b5cfea5f86830648dcecc55af6557fc7832ab11e.
Please resolve manually.
cc: @bazelbuild/triage

**Comment by bazel-io** [comment]
Failed commmits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/b5cfea5f86830648dcecc55af6557fc7832ab11e.
Please resolve manually.
cc: @bazelbuild/triage
