### ISSUE TITLE
[7.2.0] `bazel build //X:all` records target completion events in the BEP stream with `file://` URIs, but sometimes doesn't write files to disk

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20816]
Forked from #20737

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/skyframe/AspectCompletor.java`
`src/main/java/com/google/devtools/build/lib/skyframe/BUILD`
`src/main/java/com/google/devtools/build/lib/skyframe/CompletionFunction.java`
`src/main/java/com/google/devtools/build/lib/skyframe/SkyframeExecutor.java`
`src/main/java/com/google/devtools/build/lib/skyframe/TargetCompletor.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/22318 by @coeuvre

**Comment by iancha1992** [comment]
https://github.com/bazelbuild/bazel/pull/22348
