### ISSUE TITLE
[7.1.0] Add tree artifact metadata for the coverage post-processing spawn.

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#20811]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/b0db044227d62178a7e578b8e03c452d8c17af33

### Category

team-Local-Exec

### Reviewers

@lberki

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20812: https://github.com/bazelbuild/bazel/commit/b0db044227d62178a7e578b8e03c452d8c17af33.

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20813: https://github.com/bazelbuild/bazel/commit/b0db044227d62178a7e578b8e03c452d8c17af33.
