### ISSUE TITLE
[7.1.0] Avoid emitting canonical labels into generated repos

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20826]
Forked from #20810

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/20840 by @fmeum

**Comment by keertk** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/20917
