### ISSUE TITLE
[7.0.1] After upgrading to bazel 7.0.0 gcc fails with: --push-state: unknown option

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20835]
Forked from #20834

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by fmeum** [comment]
Sent https://github.com/bazelbuild/bazel/pull/20901
