### ISSUE TITLE
After upgrading to bazel 7.0.0 gcc fails with: --push-state: unknown option

### ISSUE THREAD

**Issue by rsalvador** [bazelbuild/bazel#20834]
### Description of the bug:

After upgrading to bazel 7.0.0 the builds in our internal CIs that have an old gcc compiler are failing with:
```
(08:11:06) ERROR: /home/build/.cache/native_bazel_output_base/external/io_grpc_grpc_java/compiler/BUILD.bazel:5:10: Linking external/io_grpc_grpc_java/compiler/grpc_java_plugin [for tool] failed: (Exit 1): gcc failed: error executing CppLink command (from target @@io_grpc_grpc_java//compiler:grpc_java_plugin) 
  (cd /home/build/.cache/native_bazel_output_base/sandbox/processwrapper-sandbox/7179/execroot/core && \
  exec env - \
    PATH=/bin:/usr/bin:/usr/local/bin \
    PWD=/proc/self/cwd \
    ZERO_AR_DATE=1 \
  /usr/bin/gcc @bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/io_grpc_grpc_java/compiler/grpc_java_plugin-2.params)
# Configuration: 922915957e448184486ff0fb7f0ba0ee9f92dfb993e46799f9d5193882b93aa1
# Execution platform: @@local_config_platform//:host
```
seems that the check for is_push_state_supported in https://github.com/bazelbuild/bazel/commit/2482322fedb463e0bbecd29c5e8e6d0f087ed884 is not working well

### Which category does this issue belong to?

C++/Objective-C Rules

### Which operating system are you running Bazel on?

MacOS and Linux

### What is the output of `bazel info release`?

release 7.0.0

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

https://github.com/bazelbuild/bazel/commit/2482322fedb463e0bbecd29c5e8e6d0f087ed884

**Comment by fmeum** [comment]
@bazel-io fork 7.0.1

**Comment by meteorcloudy** [comment]
@fmeum Are you looking into a fix? This seems to be the only blocker for 7.0.1

**Comment by fmeum** [comment]
@meteorcloudy Yes, the speculative fix is https://github.com/bazelbuild/bazel/pull/20833. Unfortunately the reporter is unable to test this and it's also very challenging to cover in integration tests.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.0.1 RC2](https://releases.bazel.build/7.0.1/rc2/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!

**Comment by rsalvador** [comment]
Verified that 7.0.1 fixes this issue.

**Comment by iancha1992** [comment]
@bazel-io fork 7.1.0
