### ISSUE TITLE
py_binary and build_python_zip fails with data dependency

### ISSUE THREAD

**Issue by pames** [bazelbuild/bazel#2088]
Roughly, I am trying to do the following on an Ubuntu VM:

1) have one py_binary(), let's call this "launcher", which sets up an environment for some other code to run in (creating temporary directories, staging files, that sort of thing).  in this BUILD rule, I have added the targets in the next two steps to the "data" attribute of the py_binary() rule.

2) have a cc_binary() (nsjail-kafel: https://github.com/google/nsjail) invoked by the above binary with a set of arguments derived from that staging setup.  all that nsjail really does though is call the target I refer to in the next step

3) this is just a py_binary() that does some processing (sandboxed via the above nsjail/kafel) on data and then the binary in the first step then moves this along in a pipeline

If I run this with --build_python_zip, the build fails:
```
$ bazel build --build_python_zip --verbose_failures //foo:launcher
INFO: Found 1 target...
ERROR: /home/phil_ames/FOO/foo/BUILD:1:1: null failed: linux-sandbox failed: error executing command
  (cd /home/phil_ames/.cache/bazel/_bazel_phil_ames/974f36f26269382725c918aa24c9a8a3/bazel-sandbox/1811ae29-3b77-44b6-96c9-30710c662e2a-1/execroot/FOO && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/google-cloud-sdk/bin:/snap/bin \
  /home/phil_ames/.cache/bazel/_bazel_phil_ames/974f36f26269382725c918aa24c9a8a3/execroot/FOO/_bin/linux-sandbox @/home/phil_ames/.cache/bazel/_bazel_phil_ames/974f36f26269382725c918aa24c9a8a3/bazel-sandbox/1811ae29-3b77-44b6-96c9-30710c662e2a-1/linux-sandbox.params -- external/bazel_tools/tools/zip/zipper/zipper cC bazel-out/local-fastbuild/bin/foo/launcher.zip @bazel-out/local-fastbuild/bin/foo/launcher.zip-2.params).
File bazel-out/local-fastbuild/internal/_middlemen/foo_Sfoo-runfiles does not seem to exist.Target //foo:launcher failed to build
INFO: Elapsed time: 2.141s, Critical Path: 0.53s
```

Running without --build_python_zip works, though:
```
$ bazel build --verbose_failures //foo:launcher
INFO: Found 1 target...
Target //foo:launcher up-to-date:
  bazel-bin/foo/launcher
INFO: Elapsed time: 1.511s, Critical Path: 0.21s
```

**Comment by meteorcloudy** [comment]
Thanks for raising up this issue, I also noticed this problem before. It's because the middlemen file isn't really created, I'll figure out a solution for that.
