### ISSUE TITLE
How to build a shared library

### ISSUE THREAD

**Issue by fabiox77** [bazelbuild/bazel#20893]
I have cloned the `chromium` source code and now I'm trying to build a `shared object` for `brotli` using `bazel` but so far no luck.

My `BUILD` file is the following:

```
cc_library(
    name = "includes",
    srcs = glob(["inlude/brotli/*.c"]),
    hdrs = glob(["include/brotli/*.h"]),
)

cc_library(
    name = "decoder",
    srcs = glob(["dec/*.c"]),
    hdrs = glob(["dec/*.h"]),
    deps = [ ":common" ],
    copts = ["-Iinclude/"],
)

cc_library(
    name = "common",
    srcs = glob(["common/*.c"]),
    hdrs = glob(["common/*.h"]),
    deps = [ ":includes" ],
    copts = ["-Iinclude/"],
)

cc_shared_library(
    name = "brotli",
    deps = [ ":common", ":decoder" ],
    #visibility = ["//main:__pkg__"],
    #linkstatic = 1,
)
```

When I try to compile it using `bazel build :brotli` I have the following error

```
ERROR: /opt/chromium/src/third_party/brotli/BUILD:40:18: in cc_shared_library rule //:brotli: 
Traceback (most recent call last):
	File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 610, column 51, in _cc_shared_library_impl
	File "/virtual_builtins_bzl/common/cc/semantics.bzl", line 145, column 13, in _check_experimental_cc_shared_library
Error in fail: Pass --experimental_cc_shared_library to use cc_shared_library
ERROR: /opt/chromium/src/third_party/brotli/BUILD:40:18: Analysis of target '//:brotli' failed
ERROR: Analysis of target '//:brotli' failed; build aborted: 
INFO: Elapsed time: 0.038s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

I tried to understand the error using the [official](https://bazel.build/reference/be/c-cpp#cc_shared_library) documentation but I couldn't solve it.

Any suggestion?

Thanks

**Comment by fmeum** [comment]
Which version of Bazel are you using? With Bazel 7, you shouldn't need the flag. The docs are versioned, if you select the correct version under the `Version` section of the navigation bar, you should see the flag still mentioned in the `cc_shared_library` docs.

**Comment by fabiox77** [comment]
@fmeum I'm using version `6.4.0`. I'll update to a more recent version.

Thanks

**Comment by fabiox77** [comment]
Problem sorted after I have update to the version `7.0.0` as suggested.

Thanks
