### ISSUE TITLE
Please cherry-pick https://github.com/bazelbuild/bazel/commit/38918be4f665e4eca69c9f3f5d469be6d63a486b into 7.1

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel#20898]
### Commit IDs

38918be4f665e4eca69c9f3f5d469be6d63a486b

### Category

team-Performance

### Reviewers

meisterT

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20907: https://github.com/bazelbuild/bazel/commit/38918be4f665e4eca69c9f3f5d469be6d63a486b.

**Comment by iancha1992** [comment]
hi @meisterT. Looks like it just needs to be milestoned to trigger the cherry-pick. Please see above for the PR. Thanks!
