### ISSUE TITLE
Bazel call strip with unknown -p option under OS X

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#209]
$ bazel build //third_party/ijar:ijar.stripped
INFO: Found 1 target...
INFO: From Stripping third_party/ijar/ijar.stripped for //third_party/ijar:ijar:
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: unrecognized option: -p
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip [-AnuSXx] [-] [-d filename] [-s filename] [-R filename] [-o output] file [...] 
ERROR: /Users/dmarting/git/toto/bazel-review/third_party/ijar/BUILD:27:1: Stripping third_party/ijar/ijar.stripped for //third_party/ijar:ijar failed: strip failed: error executing command /usr/bin/strip -S -p -o bazel-out/local_darwin-dbg/bin/third_party/ijar/ijar.stripped -R .gnu.switches.text.quote_paths -R .gnu.switches.text.bracket_paths -R .gnu.switches.text.system_paths -R ... (remaining 10 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //third_party/ijar:ijar.stripped failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.095s, Critical Path: 0.01s

**Comment by ulfjack** [comment]
I can still reproduce this. I suppose moving more of the hard-coded flags into the crosstool may fix this?

**Comment by jart** [comment]
Just ran into this issue doing a `bazel build :*` of [gemmlowp](https://github.com/google/gemmlowp) on my Macbook.

**Comment by ulfjack** [comment]
I can still reproduce this. :-(

**Comment by zuercher** [comment]
We're working on OS X support in lyft/envoy and we hit this issue as well using bazel 0.5.2.

It's trivially reproducible in the bazelbuild/examples repo:

```
$ git clone https://github.com/bazelbuild/examples
$ cd examples/cpp-tutorial/stage1
$ bazel build //main:hello-world.stripped
INFO: Found 1 target...
ERROR: /Users/stephan/workspace/examples/cpp-tutorial/stage1/main/BUILD:1:1: Stripping main/hello-world.stripped for //main:hello-world failed: Process exited with status 1 [sandboxed].
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: unrecognized option: -p
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip [-AnuSXx] [-] [-d filename] [-s filename] [-R filename] [-o output] file [...] 
Use --strategy=CcStrip=standalone to disable sandboxing for the failing actions.
Target //main:hello-world.stripped failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.140s, Critical Path: 0.03s
```

**Comment by ulfjack** [comment]
Also still an issue with 0.5.3.
