### ISSUE TITLE
Loading Skylark git_repository fails on Windows

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2090]
### Description of the problem / feature request / question:

When trying to loading with Skylark `git_repository` it fails on Windows. On Linux it works fine.

### If possible, provide a minimal example to reproduce the problem:

`WORKSPACE` starts with:

    workspace(name = "foo")

    load(
	    "@bazel_tools//tools/build_defs/repo:git.bzl",
	    "git_repository",
	    "new_git_repository",
    )

    git_repository(
	    name = "com_dsfishlabs_rules_perforce",
	    remote = "https://github.com/abergmeier-dsfishlabs/bazel_rules_perforce.git",
	    commit = "bedfc6fa5d54f6694f38c2b8b0dd846b9f2e3fb7",
    )

### Environment info
* Operating System: Windows 8.1

* Bazel version (output of `bazel info release`): 0.4.0

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

Nope

### Anything else, information or logs or outputs that would be helpful?

The detailed error is:

    ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Encountered error while reading extension file 'perforce/def.bzl': no such package '@com_dsfishlabs_rules_perforce//perforce': C:/Users/A5336~1.BER/AppData/Local/Temp/Bazel/DY8I2EUN/external/com_dsfishlabs_rules_perforce/.git/objects/pack/pack-06e78c0fe79fdd2c24c0ed10b8e8a4916af496f6.pack (Permission denied).

**Comment by kchodorow** [comment]
I'd guess this is another platform-dependent bit of fun in the jGit library.  Does it work if you use the Skylark git rule? (`load('@bazel_tools//tools/build_defs/repo/git.bzl', 'git_repository')`.)

**Comment by abergmeier-dsfishlabs** [comment]
@kchodorow Ahem I think you missed the first `load` statement in my example 😉

**Comment by kchodorow** [comment]
Indeed I did!  Punting to the Windows people.

**Comment by dslomov** [comment]
Well, I couldn't repro this, sorry. Does it still occur? Do you have a repro case?

**Comment by dslomov** [comment]
Closing as non-repro.
