### ISSUE TITLE
Bazel crashes without PATH

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2091]
### Description of the problem / feature request / question:

When explicitly removing `PATH` from environment Bazel crashes on Windows.

### If possible, provide a minimal example to reproduce the problem:

In Python:

    env = os.environ.copy()
    del env["PATH"]
    subprocess.run(sys.argv, check = True, env = env)

### Environment info
* Operating System: Windows 8.1

* Bazel version (output of `bazel info release`): 0.4.0

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

No

### Anything else, information or logs or outputs that would be helpful?
It does work if at least have path to `bash.exe` in `PATH`.

**Comment by meteorcloudy** [comment]
I think the crash is expected. Because we still need msys.dll (and even many Windows system dlls) to be in PATH. But we are working actively on removing msys dependency. :)

**Comment by kchodorow** [comment]
Well, what does "crash" mean?  Erroring out is fine, stack trace is not.

**Comment by abergmeier-dsfishlabs** [comment]
`stack trace` it is.

**Comment by dslomov** [comment]
Yes empty PATH does not work until bazel.exe stops depending on msys-2.0.dll. So this will not be fixed until #2107 is. Closing this one.
