### ISSUE TITLE
[7.1.0] python: make incompatible_python_disallow_native_rules work for top-level external repo targets

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#20920]
### Commit IDs

1533cd123fa465480bbbcd4bdd2b438ebc5fb9eb

### Category

team-Rules-Python

### Reviewers

@rickeylev, @meteorcloudy

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20923: https://github.com/bazelbuild/bazel/commit/1533cd123fa465480bbbcd4bdd2b438ebc5fb9eb.
