### ISSUE TITLE
[bazel.build] Problem with /rules/lib/toplevel/cc_common

### ISSUE THREAD

**Issue by phst** [bazelbuild/bazel#20922]
### Page link:

https://bazel.build/rules/lib/toplevel/cc_common

### Problem description (include actual vs expected text, if applicable):

cc_common.compile is no longer documented

**Comment by tpudlik** [comment]
+1. This is causing confusion (e.g., https://github.com/google/emboss/issues/108#issuecomment-1936801890), because the function used to be documented in 6.4.0, so it looks like the function was removed.
