### ISSUE TITLE
[7.1.0] Remove flag guarding for the AndroidIdeInfo provider

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#20931]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/916c3f5a649926f07a8390893539b560646a192e

### Category

team-Android

### Reviewers

@iancha1992

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20932: https://github.com/bazelbuild/bazel/commit/916c3f5a649926f07a8390893539b560646a192e.

**Comment by iancha1992** [comment]
cc: @mai93 @keertk
