### ISSUE TITLE
--genrule_strategy=sandboxed breaks builds if --spawn_strategy=sandboxed is not also set

### ISSUE THREAD

**Issue by jart** [bazelbuild/bazel#2093]
This bug is minor. Maybe Bazel should make a slight modification so `--genrule_strategy=sandboxed` implies `--spawn_strategy=sandboxed`? I'm honestly not even sure why they're configured separately to begin with.

**Comment by hermione521** [comment]
@philwo I remember you had a CL for this?

**Comment by philwo** [comment]
The fact that --genrule_strategy exists is mostly historic - in the beginning, we didn't have the --strategy=Mnemonic=Strategy flag. In internal Blaze we have lots of these --whatever_strategy flags, so we just took the ones that we needed for Bazel and made them available (which happens to only be --genrule_strategy).

I think the general wisdom now is that --strategy=Mnemonic=Strategy (e.g. --strategy=Genrule=standalone) is better than individual strategy flags.

@jart - what exactly breaks when you use genrule_strategy=sandboxed but not spawn_strategy=sandboxed? I think that should work fine:

```
philwo@philwo:~/bazel-test (master)$ ./output/bazel build --spawn_strategy=standalone --genrule_strategy=sandboxed //examples/gen:all
INFO: Reading 'startup' options from /usr/local/google/home/philwo/.bazelrc: --command_port=0 --watchfs
.
INFO: Analysed 3 targets (8 packages loaded).
INFO: Found 3 targets...
INFO: Elapsed time: 2.673s, Critical Path: 0.07s
INFO: Build completed successfully, 3 total actions
```

**Comment by jart** [comment]
Let's make things simpler. What is the set of flags I can add to my `.bazelrc` which will make bazel as strict as possible, in every way imaginable? I want layering aka strict dependency checks. I want hermeticity guarantees. I want the works.

**Comment by philwo** [comment]
@jart This would be:

```
build --spawn_strategy=sandboxed
build --worker_sandboxing
```

Or go even further and disable workers (as they're not as strictly sandboxed as normal spawns):

```
build --spawn_strategy=sandboxed
build --strategy=Javac=sandboxed --strategy=Closure=sandboxed
```

I'm not aware of any other flags that can be enabled to increase hermeticity, as we usually default to strict checks. Pinging @damienmg and @lberki just in case they have any additional ideas.

**Comment by philwo** [comment]
I'm closing this, because I think there isn't much more to do here. Feel free to re-open, though.
