### ISSUE TITLE
[Mirror] rules_apple 3.1.1

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#20936]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/apple_support/releases/download/1.11.1/apple_support.1.11.1.tar.gz
https://github.com/bazelbuild/rules_apple/releases/download/3.1.1/rules_apple.3.1.1.tar.gz

**Comment by sgowroji** [comment]
Here they are.

1.  [https://mirror.bazel.build/github.com/bazelbuild/apple_support/releases/download/1.11.1/apple_support.1.11.1.tar.gz](https://mirror.bazel.build/github.com/bazelbuild/apple_support/releases/download/1.11.1/apple_support.1.11.1.tar.gz)
2.  [https://mirror.bazel.build/github.com/bazelbuild/rules_apple/releases/download/3.1.1/rules_apple.3.1.1.tar.gz](https://mirror.bazel.build/github.com/bazelbuild/rules_apple/releases/download/3.1.1/rules_apple.3.1.1.tar.gz)
