### ISSUE TITLE
`bazel version` fails with custom flags

### ISSUE THREAD

**Issue by SpencerC** [bazelbuild/bazel#20938]
### Description of the bug:

If a developer sets `common` settings in their `.bazelrc` file that include custom flags, `bazel version` comes back with "ERROR: Unrecognized arguments: ...".

### Which category does this issue belong to?

CLI

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Add a custom flag somewhere in your workspace: 
```
load("@bazel_skylib//rules:common_settings.bzl", "string_flag")

string_flag(
    name = "someflag",
    build_setting_default = "somevalue",
    visibility = ["//visibility:public"],
)
```
Add the following line to your `.bazelrc` file:
```
common --//backend:project_id=ggx-prototype
```
Run
```bazel version```

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 6.2.1

**Comment by Wyverald** [comment]
This is fixed in 6.4.0 (see https://github.com/bazelbuild/bazel/pull/18130#issuecomment-1728358014). Please upgrade.
