### ISSUE TITLE
[7.1.0] Cherry-pick the change to reduce repository invalidations to Bazel 7.1

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#20948]
### Commit IDs

80a4a1483e38353e9472ed8bfd5261efe1a6e23b

### Category

team-OSS

### Reviewers

@iancha1992

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20949: https://github.com/bazelbuild/bazel/commit/80a4a1483e38353e9472ed8bfd5261efe1a6e23b.
