### ISSUE TITLE
cc_binary: linkmap support

### ISSUE THREAD

**Issue by t-8ch** [bazelbuild/bazel#20966]
### Description of the feature request:

Our development process relies on linkmaps for binaries.
Currently `cc_binary` is not able to generate those.
While the necessary plumbing exists in `cc_common` with `addition_linker_outputs` this is not exposed as interface via `cc_binary`.

The `generate_linkmap` feature as used by the objc toolchain could be reused.

### Which category does this issue belong to?

C++/Objective-C Rules

### What underlying problem are you trying to solve with this feature?

Debugging of binaries.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 7.0.1

### Have you found anything relevant by searching the web?

* https://github.com/bazelbuild/bazel/issues/14189

**Comment by comius** [comment]
Unfortunately Bazel team is very short on C++ rules support, so we can't accept new features ATM.

**Comment by t-8ch** [comment]
That it unfortunate as there is no generic way to make `cc_binary` expose more linker artifacts.
(The same way `cc_common.link` does with `additional_linker_outputs`.

Do you have a *very rough* estimation on how long "ATM" could be?

**Comment by comius** [comment]
> That it unfortunate as there is no generic way to make `cc_binary` expose more linker artifacts. (The same way `cc_common.link` does with `additional_linker_outputs`.
> 
> Do you have a _very rough_ estimation on how long "ATM" could be? So we can determine if we should wait or try to come up with some different/hacky solution.

I don't know, I don't have any rough estimates.

**Comment by t-8ch** [comment]
Closing, as my PR got merged.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.2.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.2.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.2.0rc1. Thanks!
