### ISSUE TITLE
When disk cache and remote cache are both enabled, not all test logs are uploaded to the remote cache

### ISSUE THREAD

**Issue by DolceTriade** [bazelbuild/bazel#20962]
### Description of the bug:

This should be a pretty generic bug since I've reproduced this on at least 3 different bazel repos on bazel 6.4 and 7.0 and on 3 different remote cache implementations (bazel-remote, buildbuddy, and buildbarn).

Essentially, if you have disk cache enabled with `build --disk_cache=/some/path` and `--remote_cache=grpcs://myserver` not all test logs are uploaded to the remote cache `myserver`. However, if you run bazel test a second time (all tests should be cached, so this is actually a no-op), all the test logs get uploaded then. This assigns a new invocation, however, since the shas of the cached tests are the same, the old invocation's test logs get populated too.

By "not all logs are uploaded", I mean that some logs are uploaded successfully, but others are not even attempted to be uploaded (therefore the bazel timeout and retry options have no effect). I haven't been able to find a correlation between which logs are uploaded and which are not. 

If I remove the `--disk_cache=` arg, all the logs are uploaded on the first try.

### Which category does this issue belong to?

Remote caching

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`bazel test --disk_cache=~/.cache/bazel --remote_cache=grpc://localhost:9089 --bes_backend=<something> --noremote_upload_local_results --experimental_build_event_upload_max_retries=10 --remote_retries=10 --remote_timeout=1h //...`

I haven't tested without the bes backend, because I use the bes viewer to check whether the logs are there. For bes I used the OSS buildbuddy docker container.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

Bazelisk version: v1.15.0
Build label: 7.0.1
Build target: @@//src/main/java/com/google/devtools/build/lib/bazel:BazelServer
Build time: Thu Jan 18 18:04:46 2024 (1705601086)
Build timestamp: 1705601086
Build timestamp as int: 1705601086

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
https://github.com/bazelbuild/rules_go.git
54c12e5d6bc591137ca9127a7629a8fc68ab6094
54c12e5d6bc591137ca9127a7629a8fc68ab6094
```

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

don't know.

### Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

This could be nothing since I'm not very familiar with the bazel source code, but when I instrumented bazel to add logging for this bug, I could see the code path reached here: https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/remote/ByteStreamBuildEventArtifactUploader.java;l=355

but never go to the bytestream grpc uploader here: https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/remote/ByteStreamUploader.java;l=128;drc=aa6fa34f50b4fff74f9085fad76e34681dac3ecb?q=bytestreamgrpc&ss=bazel%2Fbazel

For some reason, [isRemoteFile](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/remote/ByteStreamBuildEventArtifactUploader.java;l=133-136) was returning true for the logs even though they are local files, which I suspect was causing bazel to not upload the logs.

On the second run, the uploads reach the bytestream grpc uploader and are successfully uploaded.

**Comment by tjgq** [comment]
You said that in a fully cached run, the logs always get uploaded. For partially cached runs, is there a correlation between a cache hit/miss and whether the log gets uploaded?

**Comment by DolceTriade** [comment]
On a cache hit, the logs do get uploaded.

**Comment by DolceTriade** [comment]
@tjgq I debugged this a little more and basically what seems to be happening is for some reason, RemoteCache calls uploadFile with writePolicy DISK_CACHE_ONLY through some code path (I haven't been able to trace which codepath makes this happen). Then, when the BES upload happens with REMOTE_CACHE_ONLY, since the digest is the key, the AsyncTaskExecutor doesn't execute it because `force` isn't set to true.

Unsure of where the DISK_CACHE_ONLY comes from.

**Comment by DolceTriade** [comment]
```
diff --git a/src/main/java/com/google/devtools/build/lib/remote/RemoteCache.java b/src/main/java/com/google/devtools/build/lib/remote/RemoteCache.java
index 2ad56b0239..ce2d32a7d4 100644
--- a/src/main/java/com/google/devtools/build/lib/remote/RemoteCache.java
+++ b/src/main/java/com/google/devtools/build/lib/remote/RemoteCache.java
@@ -82,7 +82,7 @@ public class RemoteCache extends AbstractReferenceCounted {
   private static final ListenableFuture<byte[]> EMPTY_BYTES = immediateFuture(new byte[0]);

   private final CountDownLatch closeCountDownLatch = new CountDownLatch(1);
-  protected final AsyncTaskCache.NoResult<Digest> casUploadCache = AsyncTaskCache.NoResult.create();
+  protected final AsyncTaskCache.NoResult<String> casUploadCache = AsyncTaskCache.NoResult.create();

   protected final CacheCapabilities cacheCapabilities;
   protected final RemoteCacheClient cacheProtocol;
@@ -162,7 +162,7 @@ public class RemoteCache extends AbstractReferenceCounted {

     Completable upload =
         casUploadCache.execute(
-            digest,
+            digest + context.getWriteCachePolicy().toString(),
             RxFutures.toCompletable(
                 () -> cacheProtocol.uploadFile(context, digest, file), directExecutor()),
             force);
@@ -193,7 +193,7 @@ public class RemoteCache extends AbstractReferenceCounted {

     Completable upload =
         casUploadCache.execute(
-            digest,
+            digest + context.getWriteCachePolicy().toString(),
             RxFutures.toCompletable(
                 () -> cacheProtocol.uploadBlob(context, digest, data), directExecutor()),
             force);
diff --git a/src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionCache.java b/src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionCache.java
index d614e52aac..7ab3d9f93d 100644
--- a/src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionCache.java
+++ b/src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionCache.java
@@ -194,7 +194,7 @@ public class RemoteExecutionCache extends RemoteCache {
           uploadTask.completion = Completable.fromObservable(completion);
           Completable upload =
               casUploadCache.execute(
-                  digest,
+                  digest.getHash() + context.getWriteCachePolicy().toString(),
                   Single.<Boolean>create(
                           continuation -> {
                             uploadTask.continuation = continuation;
```

This patch, albeit hacky, fixes the problem for me.

**Comment by DolceTriade** [comment]
Oddly, `--noremote_upload_local_results` seems to be why we initially try to upload with `DISK_CACHE_ONLY`, however, even if I change that flag to `--remote_upload_local_results`, it still doesn't work (however, it *does* work with my patch above), so maybe I traced the wrong code path...

**Comment by tjgq** [comment]
Thanks for the investigation. This makes the issue look a bit similar to https://github.com/bazelbuild/bazel/issues/20296. Perhaps the same fix will work for both cases.

**Comment by DolceTriade** [comment]
It does sound like the same underlying issue. Is there a workaround or a plan for a fix for this since it's quite annoying to not have all your assets uploaded to your remote cache (and the linked issue is a few months old)?

Happy to take a stab at a PR myself (hopefully pointing me in the right direction for a fix).
