### ISSUE TITLE
bazel 7.0.1 not backwards compatible with bazel 7.0.0 due to lockfile changes

### ISSUE THREAD

**Issue by zygoloid** [bazelbuild/bazel#20974]
### Description of the bug:

`bazel build --lockfile_mode=error` fails in bazel 7.0.1 for some repositories where the build succeeded in bazel 7.0.0.

For example, if you check out https://github.com/carbon-language/carbon-lang at revision 9be99cad4cc23710e2f96ed96215593cdba8b2cc, then building with bazel 7.0.0 succeeds, but with bazel 7.0.1:

```console
$ bazel build //toolchain/driver:carbon --lockfile_mode=error
INFO: Invocation ID: a955b73a-e1bb-4439-9f5e-9c5eb2a8b9a4
ERROR: Analysis of target '//toolchain/driver:carbon' failed; build aborted: MODULE.bazel.lock is no longer up-to-date because: The implementation of the extension 'ModuleExtensionId{bzlFileLabel=@@bazel_tools//tools/cpp:cc_configure.bzl, extensionName=cc_configure_extension, isolationKey=Optional.empty}' or one of its transitive .bzl files has changed. Please run `bazel mod deps --lockfile_mode=update` to update your lockfile.
```

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 7.0.1

### What's the output of `git remote get-url upstream; git rev-parse trunk; git rev-parse HEAD` ?

```text
git@github.com:carbon-language/carbon-lang.git
de2316bd0c38d1c5961bb038f76715f190495abf
de2316bd0c38d1c5961bb038f76715f190495abf
```

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Yes.

### Any other information, logs, or outputs that you want to share?

Per [the release notes](https://github.com/bazelbuild/bazel/releases/tag/7.0.1), version 7.0.1 is intended to be "fully backward compatible with Bazel 7.0".

**Comment by Wyverald** [comment]
This isn't something we can fix. Bazel version updates will almost always incur lockfile updates. Saying the update is backwards-incompatible when `--lockfile_mode=error` is akin to saying so because your assert `bazel_version == 7.0.0` no longer holds.

Please simply use `--lockfile_mode=update` instead.

**Comment by zygoloid** [comment]
Note that this also breaks our CI, and causes spurious changes on build for our developers when new versions of bazel happen to get installed on their systems.

How are we supposed to interact with lockfiles? Is it really expected that everyone working on a project upgrades their bazel *patch* version at the same time?

**Comment by Wyverald** [comment]
You can use a .bazelversion file with Bazelisk to manage the version of Bazel used to build your project: https://github.com/bazelbuild/bazelisk/tree/master?tab=readme-ov-file#how-does-bazelisk-know-which-bazel-version-to-run

This effectively makes sure that everyone working on it uses the same patch version.

**Comment by fmeum** [comment]
> Is it really expected that everyone working on a project upgrades their bazel patch version at the same time?

Just think about Bazel like any other of your dependencies: If you bump a version requirement for a regular dependency to the next patch release, wouldn't you also expect your lockfile to change?

**Comment by zygoloid** [comment]
Point taken, though note that problems arise here without any explicit "bump the version requirement" step, unlike for other deps. What happened in practice was that some of our development machines automatically updated their bazel version to the newest patch releases, and we started seeing lockfile issues -- a build that works one day doesn't do the same thing the next morning. That seems like a violation of the compatibility promise in the release notes, that ought to be called out somewhere.

Ultimately, Bazel isn't like any other dependency, precisely because it's not provided hermetically by Bazel. Using `bazelisk` certainly would address that, but if that's the stance going forward then the documentation for lockfiles should probably be changed to call that out prominently. Eg, perhaps in the [best practices](https://bazel.build/external/lockfile#best-practices) section ... you know what, I'll send a PR :)
