### ISSUE TITLE
OS X tests failing with xcrun error

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#2097]
See http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/325/console, for example:

```
apple_tests

** test_fat_apple_binary *******************************************************
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: unable to lookup item 'SDKVersion' in SDK 'iphoneos'
-- Test log: -----------------------------------------------------------
------------------------------------------------------------------------
test_fat_apple_binary FAILED: terminated because this command returned a non-zero status:
/private/var/tmp/_bazel_ci/663aef0b024d9552f81e09f650e1ea55/bazel-sandbox/21674329-8558-473a-93e4-d5248e7e35da-1454/execroot/darwin-x86_64/bazel-out/local-fastbuild/bin/src/test/shell/bazel/apple/bazel_apple_test.runfiles/io_bazel/src/test/shell/testenv.sh:370: in call to setup_objc_test_support
/private/var/tmp/_bazel_ci/663aef0b024d9552f81e09f650e1ea55/bazel-sandbox/21674329-8558-473a-93e4-d5248e7e35da-1454/execroot/darwin-x86_64/bazel-out/local-fastbuild/bin/src/test/shell/bazel/apple/bazel_apple_test.runfiles/io_bazel/src/test/shell/bazel/apple/bazel_apple_test:32: in call to set_up
FAILED: test_fat_apple_binary
```

**Comment by katre** [comment]
I saw a similar error when I was sheriff several weeks ago. Chris and I
looked into it and thought it should have been fixed in a recent change of
his.

The offending line of code is this:
https://github.com/bazelbuild/bazel/blob/5570bcca4e2d99570eeda688fb0ae8a52ada1659/src/test/shell/testenv.sh#L371

I tried connecting to one of the MacOS slaves and running the "xcrun --sdk
iphoneos --show-sdk-version" command and it ran successfully. Maybe check
on both slaves and see if it works properly?

**Comment by kchodorow** [comment]
The xcrun command does, indeed, error out with the same error message on the NYC Jenkins.

**Comment by c-parsons** [comment]
Looks due to xcode not being installed on the CI machine.
Command line tools are the only requirement for bazel in general, but, if we want to actually build objc / ios targets, as is done in these tests, we require xcode to be installed.

**Comment by kchodorow** [comment]
Thanks for the help, filed https://github.com/bazelbuild/continuous-integration/issues/37 to get a non-xcode Jenkins config set up.

**Comment by kchodorow** [comment]
Actually, reopening (but with lower priority).  Could the iOS rules give a clearer error if XCode isn't installed?

**Comment by jmmv** [comment]
Many things have changed in error reporting about Xcodes, so closing this.
