### ISSUE TITLE
[7.1.0] Bazel swallows credential helper standard error output instead to echoing it to the user

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#20983]
### Commit IDs

f052e79453afeefc46474641b3010226a3778700

### Category

team-ExternalDeps

### Reviewers

@iancha1992, @keertk

**Comment by bazel-io** [comment]
Failed commmits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/f052e7.
Please resolve manually.
cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
PR: https://github.com/bazelbuild/bazel/pull/20984

**Comment by Wyverald** [comment]
new PR: https://github.com/bazelbuild/bazel/pull/20992 (old one was owned by bazel-io and had merge conflicts)
