### ISSUE TITLE
Usage of bzlmod causes cache invalidations due to module version being in file path

### ISSUE THREAD

**Issue by v3n** [bazelbuild/bazel#20997]
### Description of the feature request:

Remove module version from the visible module path as it causes frequent cache invalidations when modules updates. This is particularly problematic in C++ where changes in include paths due to module versions can propagate a cache invalidation over most of the build graph; despite no actual dependent files changing.

### Which category does this issue belong to?

External Dependency

### Which operating system are you running Bazel on?

Mac OS

### What is the output of `bazel info release`?

release 6.4.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.1.0 RC1](https://releases.bazel.build/7.1.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!
