### ISSUE TITLE
[7.1.0] Remove `_allowlist_function_transition` requirement

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21008]
Forked from #19233

**Comment by meteorcloudy** [comment]
Probably need to cherry-pick https://github.com/bazelbuild/bazel/commit/bb7fb2d32f055f2a70a5ab394cf5aef29bc74b2e

**Comment by iancha1992** [comment]
> Probably need to cherry-pick [bb7fb2d](https://github.com/bazelbuild/bazel/commit/bb7fb2d32f055f2a70a5ab394cf5aef29bc74b2e)

@meteorcloudy
https://github.com/bazelbuild/bazel/commit/bb7fb2d32f055f2a70a5ab394cf5aef29bc74b2e was already cherry-picked in https://github.com/bazelbuild/bazel/commit/60f3319ebca47080b7af823c8aba52b391a8baa6.

**Comment by meteorcloudy** [comment]
Nice, then should we close this one?
