### ISSUE TITLE
Remove _allowlist_function_transition requirement

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#21011]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/bb7fb2d32f055f2a70a5ab394cf5aef29bc74b2e

### Category

team-Configurability

### Reviewers

@katre

**Comment by bazel-io** [comment]
Failed commmits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/bb7fb2d32f055f2a70a5ab394cf5aef29bc74b2e.
Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Already cherry-picked into 7.1.0
