### ISSUE TITLE
cquery with --transitions=lite fails if any targets are incompatible

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/bazel#21010]
### Description of the bug:

If any targets are incompatible with current target platform, and you perform a `cquery` which expands transitions, it fails (with a really obtuse error message).

I did some debugging and it looks like what's going on is:

* [This code](https://github.com/bazelbuild/bazel/blob/b22449f4a4ce713062636155adc48d5fb99a4a9e/src/main/java/com/google/devtools/build/lib/analysis/producers/DependencyContextProducerWithCompatibilityCheck.java#L159-L163) causes an `IncompatibleTargetException` to be thrown if any are encountered, even though we are fine with incompatible targets existing in a cquery context.
* [This code](https://github.com/bazelbuild/bazel/blob/b22449f4a4ce713062636155adc48d5fb99a4a9e/src/main/java/com/google/devtools/build/lib/query2/cquery/CqueryTransitionResolver.java#L158-L160) obfuscates the exception by converting it to an `EvaluationException` (and not setting a cause).
* [This code](https://github.com/bazelbuild/bazel/blob/b22449f4a4ce713062636155adc48d5fb99a4a9e/src/main/java/com/google/devtools/build/lib/query2/cquery/ProtoOutputFormatterCallback.java#L292-L295) obfuscates the exception by hiding it as an `InterruptedException`.

### Which category does this issue belong to?

Configurability

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
% touch WORKSPACE
% cat >BUILD.bazel <<EOF
genrule(
    name = "gr",
    cmd = "sleep 10",
    outs = ["out"],
    target_compatible_with = ["@platforms//os:linux"],
)
EOF
% USE_BAZEL_VERSION=7.0.0 bazel cquery --transitions=lite --output=proto ... 
INFO: Invocation ID: 3b1bb5f1-a496-4e3e-80b2-7bf2a8910b92
INFO: Analyzed 5 targets (0 packages loaded, 0 targets configured).
INFO: Found 5 targets...
ERROR: build interrupted
INFO: Elapsed time: 0.092s, Critical Path: 0.00s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
```

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Bisect blames https://github.com/bazelbuild/bazel/commit/9575c7fa86458717c154f08ff8a7f7aff000f6ae which seems relevant. cc @aoeui, @gregestren

**Comment by gregestren** [comment]
Snapshotting from the description: this may be a regression from https://github.com/bazelbuild/bazel/commit/9575c7fa86458717c154f08ff8a7f7aff000f6ae.

**Comment by keith** [comment]
Would def be nice to get a different error here at least. Hard to understand what's going wrong

**Comment by gregestren** [comment]
Is there anything left here after https://github.com/bazelbuild/bazel/pull/23210?

**Comment by illicitonion** [comment]
I think we're good - thanks!
