### ISSUE TITLE
.so names on Android shouldn't have to match the android_binary() rule name

### ISSUE THREAD

**Issue by steven-johnson** [bazelbuild/bazel#2105]
Say I have an Android app with a simple native component:

```
cc_library(
    name = "Foo",
    srcs = ["jni/foo.cpp"],
)

android_binary(
    name = "Hello",
    srcs = glob(["src/com/example/hello/*.java"]),
    custom_package = "com.example. hello",
    manifest = "AndroidManifest.xml",
    resource_files = glob(["res/**"]),
    deps = [":Foo"],
)
```

AFAICT, the native code is always put into a native .so that matches the android_binary() name -- i.e., "libHello.so" in this case -- rather than (say) "libFoo.so" or some other customized name. 

This is a reasonable and good default behavior.

But, if I have multiple Android app variants that share the same native code, this convention is suboptimal; the app needs to extract the embedded `nativedeps` file to  figure out how to call System.loadLibrary(). 

Could we add an optional way to tag a native library in this case to give it a custom name?

**Comment by aj-michael** [comment]
Could you expand on your example of having multiple Android app variants? What about the embedded `nativedeps` do you feel is suboptimal?

**Comment by steven-johnson** [comment]
> multiple Android app variants

```
# Simple app that uses the native "foo" library -- just enough UI to do simple experimentation
android_binary(
    name = "FooHarnessApp",
    srcs = ["src/Main.java", "src/FooWrapper.java"],
    deps = [":Foo"],
)

# Complex app that uses "foo" native library, along with many many other things
android_binary(
    name = "ComplicatedApp",
    srcs = ["src/FooWrapper.java"] + LOTS_MORE_SRCS,
    deps = [":Foo"] + LOTS_MORE_DEPS,
)
```

> What about the embedded nativedeps is suboptimal

I've never seen this file produced by any other build system -- either it's Bazel-specific, or my knowledge of Android native build practices is out of date -- is it documented anywhere? Are there specific guidelines on what it contains and how to use it? Will it be maintained in the future?

**Comment by ahumesky** [comment]
Yes, we need to update the documentation around this mechanism

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
