### ISSUE TITLE
Bazel bootstraping failure on gentoo x64

### ISSUE THREAD

**Issue by pefoley2** [bazelbuild/bazel#2106]
Trying to run ./compile.sh from head on my gentoo machine results in a whole host of the below errors:

/tmp/bazel_wBXYapGC/src/com/google/devtools/build/lib/query2/proto/proto2api/Build.java:10514: error: incompatible types: com.google.protobuf.GeneratedMessageV3.BuilderParent cannot be converted to com.google.protobuf.AbstractMessage.BuilderParent
                    getParentForChildren(),

Java version:
openjdk version "1.8.0_101"
OpenJDK Runtime Environment (IcedTea 3.1.0) (Gentoo icedtea-3.1.0)
OpenJDK 64-Bit Server VM (build 25.101-b13, mixed mode)

Full output from compile.sh:
http://termbin.com/6bbm

**Comment by kchodorow** [comment]
What commit is head? bac63f2ab7069eaf809a0af9539b2a7f727f16bd?

**Comment by pefoley2** [comment]
I just tried pulling again (now at  30ae806db34137c4ae7942ea5), and I no longer get this issue.
It's possible it was just some misconfiguration on my system.

**Comment by kchodorow** [comment]
There were actually some proto issues in the last couple days, so you may have been hitting that.
