### ISSUE TITLE
bazel.exe should not need msys-2.0.dll to run

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#2107]
Umbrella bug for removing msys usage from the launcher

**Comment by laszlocsomor** [comment]
Commits pertaining to this bug so far: https://github.com/bazelbuild/bazel/commit/b9d7767cc957d1cc6af0722c85858a5944df3d63, https://github.com/bazelbuild/bazel/commit/f926f3e1f43b008e034b4e8ecd16f5935ad35434, https://github.com/bazelbuild/bazel/commit/a85f52db9ddc126fabc46eab902745b183032c44, https://github.com/bazelbuild/bazel/commit/943d3cf92648f71c5aa6420aa275e674c82c6a4d, https://github.com/bazelbuild/bazel/commit/6c16765a010fccec9e3647e07d0c4b624e25445a, https://github.com/bazelbuild/bazel/commit/8a48f616bc1e6df70a30c416268f2c1323ffa9b0, https://github.com/bazelbuild/bazel/commit/6bf9576f73c34cbc7c807c13f4835861837ac4de, https://github.com/bazelbuild/bazel/commit/251bf035962bb84745436326982250678d25a7d1, https://github.com/bazelbuild/bazel/commit/9c95196bf21e42bf46df9436a84d263c26e972d2

**Comment by damienmg** [comment]
Is this going to happen by end of next month?

**Comment by laszlocsomor** [comment]
Yes, I think end of January is a realistic goal.

**Comment by petemounce** [comment]
By the way, 0.4.2 cleared the bazel moderation queue fine.

**Comment by petemounce** [comment]
Please let me know when this lands; I assume when it does, the chocolatey package can remove the dependency on msys2?

**Comment by laszlocsomor** [comment]
> Please let me know when this lands;
Sure.

> I assume when it does, the chocolatey package can remove the dependency on msys2?
Not yet. There are two parts of getting rid of msys:
1. getting rid of msys as a requirement to run bazel itself -- we will still need msys to run shell scripts (therefore e.g. java_binaries because we build a launcher (shell) script for those)
2. getting rid of msys completely, even for scenarios in (1)

We are now aiming for (1), the second one is further away but also on our radar.

**Comment by laszlocsomor** [comment]
It's my greatest pleasure to close this bug.

With 0.5.0 we'll start dogfooding the MSYS-less version, i.e. a Bazel binary built with MSVC and not depending on `msys-2.0.dll`. Bazel will still require an MSYS bash installation (we're also working on supporting other Bashes like Cygwin, see #2725) to build `genrule` and `sh_*` rules, but we will no longer require a particular version of it.

**Comment by dslomov** [comment]
Woo-hoo!

**Comment by damienmg** [comment]
Woohoo!
