### ISSUE TITLE
Android Data Binding rules

### ISSUE THREAD

**Issue by devilmac** [bazelbuild/bazel#2111]
### Description of the problem / feature request / question:

Hi Bazel team,

I'm trying to use this tool to build my project but I get the error below:

`ERROR: /Users/federico/DataBindingSample/app/BUILD:24:1: non-keyword arg after keyword arg.
ERROR: /Users/federico/DataBindingSample/app/BUILD:30:1: non-keyword arg after keyword arg.
ERROR: /Users/federico/DataBindingSample/app/BUILD:20:1: java_library(**kwargs) does not accept positional arguments, but got 1.
ERROR: /Users/federico/DataBindingSample/app/BUILD:26:1: java_library(**kwargs) does not accept positional arguments, but got 1.`

My app/BUILD file looks like the following:

android_binary(
    name = "app",
    srcs = glob(["src/main/java/com/colantoni/federico/databindingsample/*.java"]),
    custom_package = "com.colantoni.federico.databindingsample",
    manifest = "src/main/AndroidManifest.xml",
    resource_files = glob(["src/main/res/**"]),
    visibility = ["//visibility:public"],
    deps = [
            "@androidsdk//:appcompat_v7",
            "@androidsdk//:recyclerview_v7",
            ":databinding"
        ],
)

java_library(
    name = "databinding_adapters_import",
    srcs = ["@androidsdk//:extras/android/m2repository/com/android/databinding/adapters/1.3.1/adapters-1.3.1-sources.jar"],
    exports_files(["extras/android/m2repository/com/android/databinding/adapters/1.3.1/adapters-1.3.1-sources"]),
)

java_library(
    name = "databinding_library_import",
    srcs = ["@androidsdk//:extras/android/m2repository/com/android/databinding/library/1.3.1/library-1.3.1-sources.jar"],
    exports_files(["extras/android/m2repository/com/android/databinding/library/1.3.1/library-1.3.1-sources"]),
)

android_library(
    name = "databinding",
    custom_package = "android.databinding",
    deps = [":databinding_library_import",
            "_databinding_adapters_import"],
)

The WORKSPACE file is like this:

`android_sdk_repository(
    name = "androidsdk",
    # Replace with path to Android SDK on your system
    path = "/Volumes/HDD Mac/android-sdk-macosx",
    # Replace with the Android SDK API level
    api_level = 25,
    # Replace with the version in sdk/build-tools/
    build_tools_version="25.0.0"
)
`

Thanks for the help.

### Environment info
* Operating System:
Mac OS X 10.11.6

* Bazel version (output of `bazel info release`):
release 0.4.0

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

I tried to search for similar issues but I didn't find nothing.

**Comment by dslomov** [comment]
Well the error message says this I think: this line
`exports_files(["extras/android/m2repository/com/android/databinding/library/1.3.1/library-1.3.1-sources"]),`
is wrong. Not sure what you were trying to do.

**Comment by aj-michael** [comment]
For anyone who stumbles across this in the future, we are actively working to support Android databinding in Bazel in https://github.com/bazelbuild/bazel/issues/2694 although it is not ready yet.
