### ISSUE TITLE
[7.1.0] Publish RCs to GitHub

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#21125]
### Commit IDs

275000c430de7436a1dd09f0874f6151a7ca9162

### Category

team-OSS

### Reviewers

@iancha1992

**Comment by bazel-io** [comment]
Failed commmits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/275000c430de7436a1dd09f0874f6151a7ca9162.
Please resolve manually.
cc: @bazelbuild/triage

**Comment by keertk** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21127
