### ISSUE TITLE
--experimental_collect_resource_estimation crashes Bazel server

### ISSUE THREAD

**Issue by DavidANeil** [bazelbuild/bazel#21133]
### Description of the bug:

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "this.usedResources" is null
        at com.google.devtools.build.lib.actions.ResourceManager.getUsedCPU(ResourceManager.java:175)
        at com.google.devtools.build.lib.profiler.CollectLocalResourceUsage.run(CollectLocalResourceUsage.java:216)
```

CC @AlessandroPatti

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I can reproduce this in the bazel repo at HEAD currently with the following command:
```
bazel build --experimental_collect_resource_estimation //third_party/grpc/bazel:srcs
```
(The target isn't particularly important, the command fails immediately)

### What is the output of `bazel info release`?

release 7.0.2

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
git@github.com:bazelbuild/bazel.git
b4068180e6d86758aaee46650b1a7b4e041a3cd0
```

**Comment by meisterT** [comment]
cc @wilwell @zhengwei143

**Comment by zhengwei143** [comment]
Definitely https://github.com/bazelbuild/bazel/commit/0725711d76f8738be0f57cf210efaea0e0a32742, fix should be pretty simple by just ensuring `usedResources` is instantiated to an empty map and defaulting their return non-existent values.

**Comment by AlessandroPatti** [comment]
Uh-oh, sorry for missing that and thanks for fixing it @zhengwei143!

**Comment by brentleyjones** [comment]
@bazel-io flag

**Comment by keertk** [comment]
@bazel-io fork 7.1.0
