### ISSUE TITLE
bazel query is stricter on labels than http_archive

### ISSUE THREAD

**Issue by calebzulawski** [bazelbuild/bazel#21130]
### Description of the bug:

`http_archive` accepts `build_file`, `patches`, etc which are labels, but that label doesn't have to actually be exported if a source file.  This can cause `bazel query` to error in projects that otherwise build correctly.  I believe this error only occurs when the label points to a file outside of the repo.

### Which category does this issue belong to?

External Dependency

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
bazel query 'deps(//external:pkgconfig_src)'                             
ERROR: Evaluation of query "deps(//external:pkgconfig_src)" failed: preloading transitive closure failed: no such target '@@rules_foreign_cc//toolchains:pkgconfig-detectenv.patch': target 'pkgconfig-detectenv.patch' not declared in package 'toolchains' defined by /home/caleb/.cache/bazel/_bazel_caleb/5445fc14d1070af6d6f7f79afb7a0bd8/external/rules_foreign_cc/toolchains/BUILD.bazel; however, a source file of this name exists.  (Perhaps add 'exports_files(["pkgconfig-detectenv.patch"])' to toolchains/BUILD?)
```

Or more broadly, `bazel query 'deps(//external:*)'`

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 7.0.2

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
Company project, but should be reproducible in many projects.
```

**Comment by Wyverald** [comment]
Querying deps of a target under `//external` makes no sense anyway. Such targets are "pseudo-targets" that each represent a repo, and repos have no target-level deps.

Please use `bazel mod show_repo`, or if you haven't migrated to Bzlmod yet, just `bazel query //external:*` (without the `deps(...)` part).

**Comment by calebzulawski** [comment]
In my specific case, I am trying to find the source files that repository rules depend on, so querying just //external::* doesn't accomplish that.  I could read the attributes, but that doesn't necessarily cover all dependencies.  Maybe I'm missing something, but I'm not sure there's another way to query them.

**Comment by Wyverald** [comment]
There is unfortunately no reliable way to find this information. As you said, just reading the attributes doesn't cover all dependencies. And `bazel query` does nothing more than read the attributes.
