### ISSUE TITLE
Bazel cc does not work with truncated path on Windows

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2114]
### Description of the problem / feature request / question:

When trying to start Bazel from PowerShell (trying to start from MinGW crashes, probably due to msys dependency) it fails in `cc_configure.bzl`.
It seems like the `env` from `_find_env_vars(repository_ctx, vs_path)` is not returning a `PATH`. Since the `PATH` was truncated for running Bazel, of course there is no Visual Studio entries in there anymore.

I think there are the following options:

1. Explicitly check that VS entries are present in `PATH` and/or handle failure of `VCVARSALL.BAT`
2. Emulate `VCVARSALL.BAT` by using registry values
3. Set necessary `PATH` entries for `VCVARSALL.BAT` in `get_env.bat`
4. Somehow tell `VCVARSALL.BAT` not to search for `PATH` entries.

### If possible, provide a minimal example to reproduce the problem:

In PowerShell:

    $env:PATH="D:\msys64\usr\bin"; $env:JAVA_HOME="C:\Projects\tools\third_party\jre\win_x86_64"; $env:BAZEL_PYTHON="C:\Projects\tools\third_party\python3\win_x86_64"; $env:BAZEL_VS="C:\Program Files (x86)\Microsoft Visual Studio 14.0"; C:/Projects/tools/third_party/bazel/win_x86_64/bazel.exe info

When I do:

    $env:PATH="D:\msys64\usr\bin"; ./get_env.bat

it outputs:

    ERROR: Cannot determine the location of the VS Common Tools folder.
    PATH=D:\msys64\usr\bin,INCLUDE=,LIB=

So the key will probably be `ERROR: Cannot determine the location of the VS Common Tools folder.
PATH`.

### Environment info
* Operating System: Windows 10

* Bazel version (output of `bazel info release`): 0.4.0

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
Nope.

### Anything else, information or logs or outputs that would be helpful?

    ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
        File "D:/msys64/var/tmp/Bazel/DY8I2EUN/external/bazel_tools/tools/cpp/cc_configure.bzl", line 491
                _tpl(repository_ctx, "wrapper/bin/pydir...", ...})
        File "D:/msys64/var/tmp/Bazel/DY8I2EUN/external/bazel_tools/tools/cpp/cc_configure.bzl", line 493, in _tpl
                env["PATH"]
    Key "PATH" not found in dictionary.

**Comment by abergmeier-dsfishlabs** [comment]
When I change `$env:PATH="D:\msys64\usr\bin";` to

    $env:PATH="D:\msys64\usr\bin;" + $env:PATH;

it is complaining:

    ERROR: CreateFile(D:\msys64\var\tmp\Bazel\8QGNOs8Q\install): The system cannot find the file specified.
 (2)

When I do `ls D:\msys64\var\tmp\Bazel\8QGNOs8Q\install`:

    Directory: D:\msys64\var\tmp\Bazel\8QGNOs8Q\install


    Mode                LastWriteTime         Length Name
    ----                -------------         ------ ----
    d-----       21.11.2016     13:23                _embedded_binaries

**Comment by meteorcloudy** [comment]
@abergmeier-dsfishlabs  Thanks for raising up this issue and providing several options. I like option 3, because we are able to set the correct `PATH` by [`repository_ctx.execute`](https://www.bazel.io/versions/master/docs/skylark/lib/repository_ctx.html#execute). I'll fix it.

The second problem you mentioned looks like https://github.com/bazelbuild/bazel/issues/1744

Thanks again.

**Comment by 50417** [comment]
@abergmeier-dsfishlabs I am running into the same issue. Can you provide more elaborative solution to the problem? 
`ERROR: Analysis of target '//test:bin' failed; build aborted: no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/users/sls6964xx/_bazel_sls6964xx/am2y3e55/external/bazel_tools/tools/cpp/cc_configure.bzl", line 51
                configure_windows_toolchain(repository_ctx)
        File "C:/users/sls6964xx/_bazel_sls6964xx/am2y3e55/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 423, in configure_windows_toolchain
                escape_string(env["PATH"])
        File "C:/users/sls6964xx/_bazel_sls6964xx/am2y3e55/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 423, in escape_string
                env["PATH"]
key "PATH" not found in dictionary`

### Environment info
* Operating System: Windows 10
* Bazel version (output of `bazel info release`): 0.22.0

**Comment by meteorcloudy** [comment]
@50417 I think this issue should be fixed a long time ago. 

Can you provide more information about your environment? For example, what's the value of your `PATH` env.

**Comment by 50417** [comment]
Sure . My path currently has :` C:\msys64\usr\bin;
`BAZEL_SH = c:\msys64\usr\bin\bash.exe`
'BAZEL_VC =C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC '

**Comment by meteorcloudy** [comment]
Were you running under cmd.exe or msys?

**Comment by 50417** [comment]
@meteorcloudy  Its on cmd.exe
