### ISSUE TITLE
Support IPv6 on releases.bazel.build

### ISSUE THREAD

**Issue by vonschultz** [bazelbuild/bazel#21155]
### Description of the feature request:

`releases.bazel.build` should have an IPv6 address.

### What underlying problem are you trying to solve with this feature?

When building on an IPv6 only machine, `bazelisk` fails immediately on the step
```
Downloading https://releases.bazel.build/6.5.0/release/bazel-6.5.0-linux-x86_64...
```
because `releases.bazel.build` doesn't have an IPv6 address.

### Which operating system are you running Bazel on?

Ubuntu Linux

### Have you found anything relevant by searching the web?

https://bazelbuild.slack.com/archives/CRKPAB81Y/p1706699396121589

**Comment by alexeagle** [comment]
A bit more context from the slack thread,

> AWS has introduced an extra charge for IPv4 addresses

which means I think this is going to be frequently requested.

**Comment by meteorcloudy** [comment]
This should be fixed now. https://ready.chair6.net/?url=releases.bazel.build

@vonschultz Can you please help verify it?

**Comment by vonschultz** [comment]
I am able to download https://releases.bazel.build/6.5.0/release/bazel-6.5.0-linux-x86_64 over IPv6 now. I've verified with `curl -6 -v https://releases.bazel.build/6.5.0/release/bazel-6.5.0-linux-x86_64`; will try with Bazelisk on an IPv6-only host in the future, but since `curl` works, I think we can close this issue regardless.
