### ISSUE TITLE
bazel coverage hangs

### ISSUE THREAD

**Issue by Olsworn** [bazelbuild/bazel#21154]
### Description of the bug:

When running `bazel coverage` the bazel process occasionally hangs.
We first noticed the issue in our CI that runs with remote execution, but managed to reproduce the problem locally.
The process will hang until stopped manually.
The issue seems to stop happening when we remove the following flag: `--combined_report=lcov`
The last output in stdout seem to almost always be `checking cached actions`.

The issue was happening prior to version 7, but we did not attempt to make a reproduction until today.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Here is a minimal reproduction of the issue https://github.com/Olsworn/bazel-coverage-hang

### Which operating system are you running Bazel on?

Ubuntu 22.04

### What is the output of `bazel info release`?

release 7.0.2

**Comment by tjgq** [comment]
@bazel-io fork 7.1.0

**Comment by Olsworn** [comment]
@joeleba Thanks for having a look at it!

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.1.0 RC1](https://releases.bazel.build/7.1.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!
