### ISSUE TITLE
[7.1.0] Turbine error: unexpected input: when using Java 21 String Templates in java_library with javacopts = ["--enable-preview"],

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21159]
Forked from #21119

**Comment by Wyverald** [comment]
closing as we only need to update the java_tools version (see https://github.com/bazelbuild/bazel/issues/20308#issuecomment-1927021148)

(@fmeum / @hvadehra -- if we still need this, please reopen)
