### ISSUE TITLE
rules listed as data requirements not executed while gerules do

### ISSUE THREAD

**Issue by madmik3** [bazelbuild/bazel#2115]
### Missed data generated content

If you use an action to create a file, then list it as a data dependency of another rule, and build the rule with the data dependency then the needed file is not generated.  If you change this to use a genrule it works a I would expect and generate the needed content.

We have rules that depend on generated meta-content. We add them to the data section to ease upstream usage. 

### Example building my_test will not produce my_rule.txt:
```~/source/jnk$ more BUILD
load("//jnk:make.bzl", "rule_with_outputs")

rule_with_outputs(name = "my_rule")

cc_test(
    name="my_test",
    srcs=["a.cpp"],
    data=[":my_rule"]
)
~/source/jnk$ more make.bzl
def _impl(ctx):
  ctx.file_action(
      # Access the default outputs using ctx.outputs.<output name>.
      output=ctx.outputs.my_output,
      content="Hello World!"
  )
rule_with_outputs = rule(
    implementation=_impl,
    outputs = {
        # %{name} is substituted with the rule's name
        "my_output": "%{name}.txt"
    }
)
```
### Environment info
* Operating System:
Ubuntu 14.04

* Bazel version 0.3.1

**Comment by ulfjack** [comment]
I think the make.bzl _impl function is wrong.

**Comment by vladmos** [comment]
Hello. Sorry for the late answer.

You need to explicitly provide the generated file from the rule implementation function, for example:

    def _impl(ctx):
      ctx.file_action(
          # Access the default outputs using ctx.outputs.<output name>.
          output=ctx.outputs.my_output,
          content="Hello World!"
      )
      return struct(runfiles=ctx.runfiles(files=[ctx.outputs.my_output]))

Then Bazel will execute the action. See more about runfiles here: https://bazel.build/versions/master/docs/skylark/rules.html#runfiles
