### ISSUE TITLE
[7.1.0] java_tools v13.4.0 / rules_java v7.4.0

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#21160]
Cherry-pick rules_java and java_tools updates when ready - See https://github.com/bazelbuild/bazel/issues/21119#issuecomment-1919519065 and https://github.com/bazelbuild/java_tools/issues/87

**Comment by keertk** [comment]
Changes to be cherry-picked: https://github.com/bazelbuild/bazel/pull/21222/

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21359
