### ISSUE TITLE
'Exec failed due to IOException' error on tree artifact containing symlink to directory when --remote_download_outputs=toplevel

### ISSUE THREAD

**Issue by ljessendk** [bazelbuild/bazel#21171]
### Description of the bug:

When --remote_download_outputs=toplevel (default in Bazel 7) I get an IOException whenever I try to build a target that depends on a rule producing a tree artifact with a symlink to a directory when the outputs of the rule that produces the tree artifact is fetched from cache. 

The error I get looks like this:
`ERROR: /user/lsje/Lars/toplevel/project_a/BUILD:7:8: Executing genrule //:consume failed: Exec failed due to IOException: /user/lsje/.cache/bazel/_bazel_lsje/46fd854a93d2f0b0c14f3170daa62d94/execroot/_main/bazel-out/k8-fastbuild/bin/symlink_to_directory/symlink_to_dir (No such file or directory)`

I can get the above error to disappear if I either:
- Set --remote_download_outputs=all
- Build without cache
- Build when cache is not populated

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

tree_artifact_with_folder_symlink.bzl:

<pre>
def _tree_artifact_with_folder_symlink(ctx):

    args = ctx.actions.args()

    outdir = ctx.actions.declare_directory(ctx.attr.name)

    ctx.actions.run_shell(
        outputs = ([outdir]),
        use_default_shell_env = True,
        command = "\n".join([
            "mkdir -p {outdir}/dir",
            "touch {outdir}/dir/file",
            "ln -s dir {outdir}/symlink_to_dir",
        ]).format(outdir = outdir.path)
    )

    return [
        DefaultInfo(files = depset([outdir])),
    ]

tree_artifact_with_folder_symlink = rule(
    implementation = _tree_artifact_with_folder_symlink,
)
</pre>

BUILD:
<pre>
load(":tree_artifact_with_folder_symlink.bzl", "tree_artifact_with_folder_symlink")

tree_artifact_with_folder_symlink(
    name = "symlink_to_directory",
)

genrule(
    name = "consume",
    srcs = ["symlink_to_directory"],
    outs = ["dummy"],
    cmd = "touch $@",
)
</pre>

.bazelrc:
<pre>
build --disk_cache /tmp/cache
</pre>

Steps to reproduce (with Bazel 7.0.2):
<pre>
rm -rf /tmp/cache
bazel clean
bazel build :consume
bazel clean
bazel build :consume
</pre>

### Which operating system are you running Bazel on?

Fedora 37

### What is the output of `bazel info release`?

release 7.0.2

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/20415 seems to have a similar reproduction example except for the consuming rule.

**Comment by philsc** [comment]
Very different reproduction, but the error is identical: aspect-build/rules_js#1412.
Possibly same problem maybe?

**Comment by iancha1992** [comment]
@bazel-io fork 7.1.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.1.0 RC1](https://releases.bazel.build/7.1.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!

**Comment by matthewjh** [comment]
@iancha1992 possible to re-open this one? I see the same issue on 7.1.0.

**Comment by tjgq** [comment]
@matthewjh Can you provide a repro? There have been a few different issues with symptoms similar to this one. (For what it's worth, the repro provided by the initial post in this thread does *not* crash with 7.1.0.)
