### ISSUE TITLE
homebrew version out of date

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#2118]
according to 

  https://git.eclipse.org/r/#/c/84527/ 
 
(see last comment by Matthias Sohn)

the homebrew version which calls itself 0.4.0 doesn't include https://github.com/bazelbuild/bazel/commit/c1caffaabd028493188b7e3419bedf3a9506dfee, which is over a year old.

is the homebrew version tested on CI ?

**Comment by JakeWharton** [comment]
The homebrew version uses [the 0.4.0 archive](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bazel.rb#L4) which is created automatically by GitHub from the git tag which includes that commit.

**Comment by hanwen** [comment]
user deinstalled homebrew binary, so no further repro.
