### ISSUE TITLE
How to obtain remote system information? 

### ISSUE THREAD

**Issue by kekxv** [bazelbuild/bazel#21197]
local os : `macos`
remote os : `linux`

It's supposed to download for Linux, but instead it downloads for macos

![image](https://github.com/bazelbuild/bazel-buildfarm/assets/15551108/bdc4a351-ca47-4580-8a6b-ee68c04ff0ad)

https://github.com/uber/hermetic_cc_toolchain/issues/148

**Comment by sgowroji** [comment]
Hi @kekxv,  Could you please provide complete steps to reproduce the above issue. Thanks!

**Comment by fmeum** [comment]
This needs to be fixed in the linked project: Instead of relying on `repository_ctx.os`, the toolchain should be registered for all supported OS/arch combinations and then Bazel's toolchain resolution will be able to pick the correct one for your remote executor.

**Comment by kekxv** [comment]
> This needs to be fixed in the linked project: Instead of relying on `repository_ctx.os`, the toolchain should be registered for all supported OS/arch combinations and then Bazel's toolchain resolution will be able to pick the correct one for your remote executor.

the toolchain how registered OS/arch?

@fmeum

**Comment by fmeum** [comment]
For all supported combinations of those. Toolchain registrations are cheap (just `toolchain` targets), so it's not a problem to define as many as needed. Only the selected one will have its files downloaded. 

Let's follow up on the `hermetic_cc_toolchain` issue you linked.
