### ISSUE TITLE
Allow loading bazel via bzlmod

### ISSUE THREAD

**Issue by cameron-martin** [bazelbuild/bazel#21195]
### Description of the feature request:

I have often found myself loading bazel as an external repository (I _think_ it's mainly to access protos). However, this isn't as easy as it could be with bzlmod. The two main issues are:

* [remoteapis and googleapis](https://github.com/bazelbuild/bazel/blob/247e5e1ecd69afc908538c3354fa100872dfb381/MODULE.bazel#L35-L36) aren't in BCR
* Bazel itself isn't in BCR.

It would be nice if Bazel + all its dependencies were in BCR.

### Which category does this issue belong to?

External Dependency

**Comment by meteorcloudy** [comment]
@cameron-martin Can you file an issue against remote-apis and google-apis for BCR support? We should make sure the dependency you actually need is published in BCR instead of relying Bazel as a hub module. This isn't great for the health of your own external dependency graph.

**Comment by Wyverald** [comment]
> I _think_ it's mainly to access protos

The answer to that is we should move the protos to a separate module. I remember there being another GitHub issue about this, will link it here if I remember/find it.

**Comment by cameron-martin** [comment]
There's a comment here related to extracting the protos: https://github.com/bazelbuild/bazel/issues/3684#issuecomment-405554119

**Comment by Wyverald** [comment]
indeed -- let's follow up there instead. Publishing Bazel itself on BCR is not really what we should do as Bazel's codebase is not intended as an API.
