### ISSUE TITLE
Bazel compile java Error, 100 errors. 

### ISSUE THREAD

**Issue by ssword** [bazelbuild/bazel#2119]
I am trying to install hazel on a Centos 6.8 HPC, and I don't have admin privilege.
GCC version:
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)

But I have add gcc 4.8.2 to LD_LIBRARY_PATH.

JAVA version:
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

And I have also tried java version 1.8.0_66

I have tried some tweet from [rdipietro](https://github.com/tensorflow/tensorflow/issues/110).

But when I run ./compile.sh, I got the error messages as in the file: 
[result.txt](https://github.com/bazelbuild/bazel/files/606740/result.txt)

Saying that I have 100 errors. I am complete noob to JAVA, please help me solve this.

**Comment by philwo** [comment]
Hi @ssword,

I noticed this error today on my workstation, too. One of my colleagues could reproduce it on their machine, the others - using exactly the same Bazel source code - couldn't. We're still trying to figure out what happened here and either me or someone else from the team will get back to you on this bug as soon as we know how to solve this.

Sorry for the problems.

Philipp

**Comment by philwo** [comment]
@ssword I submitted a fix. If you update to the newest Bazel source code using "git pull", it should work on your machine now.

**Comment by ssword** [comment]
Great, thanks for the quick response and fix, I am able to compile right now, thanks a million!

**Comment by praveenece443** [comment]
i cannot compile bazel on odroid xu4 ox with ubuntu mate...It was throwing error while building bazel in third_parties/java..configuration.

**Comment by philwo** [comment]
@praveenece443 Please open a new issue with the exact error message and a more detailed description of your environment (e.g. which version of Ubuntu). Thanks!
