### ISSUE TITLE
Cannot use dynamic runtime (`/MD`) in Windows

### ISSUE THREAD

**Issue by javidcf** [bazelbuild/bazel#2120]
Looking at [`msvc_tools.py.tpl`](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/wrapper/bin/pydir/msvc_tools.py.tpl), it does not seem to be possible to compile on Windows using the dynamic runtime (that is, using `/MD` / `/MDd` and `LIBCMT`). Even if one adds `/MD` to the `copts` of some rule (because passing `--copt="/MD"` does not even get correctly processed, but that's a different issue), the Python wrapper will add `/MT` or `/MTd`, overriding the option. I am trying to compile TensorFlow + some additional code as static libraries to integrate in a bigger project that uses `/MD`, and with the current behavior it's not possible.

The obvious fix would be to add an additional check to the script before `self.AddOpt('/MT')`, but I don't really know if there are any other reasons behind this. It seems to me that, if anything, `/MD` should be favored as the default option (which is what Visual Studio does nowadays).

I am using Bazel 0.4.0 (installed through Chocolatey) in x64 machine with Win10. My build command line looks like:

    $ bazel build -c opt --cpu=x64_windows_msvc --host_cpu=x64_windows_msvc --verbose_failures --experimental_ui <target...>

**Comment by dslomov** [comment]
@meteorcloudy, wdyt?

**Comment by meteorcloudy** [comment]
I think only using `/MT` is just a legacy behavior after I created the wrapper script, I don't see anything special reason behind this. So, I think we can just add an additional check before adding `/MT`.

**Comment by javidcf** [comment]
Sorry I forgot to mention this before, but I also noted that [`msvc_cl.py`](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/wrapper/bin/pydir/msvc_cl.py) translates the copt `-g` to `/MTd`. I guess ideally it should translate to either `/MTd` or `/MDd` depending on the existing options, but that would require further changes I guess.

**Comment by javidcf** [comment]
I have sent a PR to better handle `/MT` and `/MD`, but I have just realized [`msvc_link.py`](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/wrapper/bin/pydir/msvc_link.py) also seems to link to `libcmt.lib` / `libcmtd.lib` by default. I'm not sure how important this is, though, because I am being able to create a DLL containing TensorFlow and use it in another application that uses `/MD` using my PR. However maybe the linker script should be adapted too somehow.

**Comment by javidcf** [comment]
@steven-johnson I have recently been able to make it work for TensorFlow building Bazel from source and then, when compiling TensorFlow, passing `--copt=/MD` to `bazel build`.

**Comment by steven-johnson** [comment]
javidcf@ That's good to know, but "building Bazel from source" should not be a prerequisite for being able to make this use case work :-)

**Comment by steven-johnson** [comment]
I think this should perhaps be reopened to fix the linker issue -- it's quite possible I'm doing something wrong, but I can't get a cc_binary to link reliably when specifying /MD and linking against another (non-Bazel) Windows library that is also compiled with /MD.

**Comment by fire** [comment]
USE_DYNAMIC_CRT=1 Is the way I worked around this, but I don't know how to encode it into the BUILD.

**Comment by wangjia184** [comment]
For bazel v5.3,  use `--features=static_link_msvcrt` parameter
