### ISSUE TITLE
[7.1.0] Mark gcc-<version> as `gcc` instead of `compiler` in Unix CC toolchain

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21214]
Forked from #20350

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21224
