### ISSUE TITLE
[7.2.0] `--incompatible_sandbox_hermetic_tmp` breaks outputs materialized as a symlinks to source artifacts

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21217]
Forked from #21215

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxedSpawnRunner.java`
`src/main/java/com/google/devtools/build/lib/sandbox/SandboxHelpers.java`
`src/main/java/com/google/devtools/build/lib/skyframe/ActionOutputMetadataStore.java`
`src/test/java/com/google/devtools/build/lib/worker/WorkerSpawnRunnerTest.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxedSpawnRunner.java` `src/main/java/com/google/devtools/build/lib/sandbox/SandboxHelpers.java` `src/main/java/com/google/devtools/build/lib/skyframe/ActionOutputMetadataStore.java` `src/test/java/com/google/devtools/build/lib/worker/WorkerSpawnRunnerTest.java`
> 
> cc: @bazelbuild/triage

cc: @tjgq @fmeum

**Comment by fmeum** [comment]
@iancha1992 This has been merged in https://github.com/bazelbuild/bazel/pull/22407
