### ISSUE TITLE
[7.1.0] Add `Label.to_display_form()`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21221]
Forked from #21179

**Comment by Wyverald** [comment]
cherry-pick: https://github.com/bazelbuild/bazel/pull/21312

**Comment by Wyverald** [comment]
For the record, the cherry-picker bot didn't run for the PR because we didn't actually approve the PR before importing it (https://github.com/bazelbuild/bazel/actions/runs/7877559830/job/21493965393#step:4:114).

**Comment by iancha1992** [comment]
Reverted in https://github.com/bazelbuild/bazel/pull/21454. May be included for 7.2.0.
