### ISSUE TITLE
ci.bazel.io JDK7 build includes JDK8-only targets

### ISSUE THREAD

**Issue by cushon** [bazelbuild/bazel#2123]
ae5d6497e01ebe08beaa31ccf0e10d8a98fddf4c was rolled back because it broke the JDK7 build:
http://ci.bazel.io/job/bazel-tests/325/BAZEL_VERSION=HEAD-jdk7,PLATFORM_NAME=darwin-x86_64/console

That code is only supported on JDK8, and all its tests have the `jdk8` tag. It should not be compiled as part of the JDK7 build.

**Comment by cushon** [comment]
This caused another breakage that @mhlopko fixed in aad9b44898cf1562765755d475463145466ea7ae and 2300f8a3e88d720f7eae90a80456142363850c5c.

**Comment by mhlopko** [comment]
Jenkins should by fixed now: https://bazel-review.googlesource.com/c/8215/
The issue Liam suffers from is now Bazel-only. If you don't agree Liam, feel free to reopen this issue.
Thanks for the patience!
