### ISSUE TITLE
[Mirror] hermetic_cc_toolchain v2.2.3

### ISSUE THREAD

**Issue by motiejus-wix** [bazelbuild/bazel#21234]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/uber/hermetic_cc_toolchain/releases/download/v2.2.3/hermetic_cc_toolchain-v2.2.3.tar.gz

**Comment by sgowroji** [comment]
https://mirror.bazel.build/github.com/uber/hermetic_cc_toolchain/releases/download/v2.2.3/hermetic_cc_toolchain-v2.2.3.tar.gz

**Comment by motiejus** [comment]
Thanks!
