### ISSUE TITLE
[Mirror] zig 0.12.0-dev.2631+3069669bc

### ISSUE THREAD

**Issue by motiejus-wix** [bazelbuild/bazel#21233]
### Please list the URLs of the archives you'd like to mirror:

     

https://ziglang.org/builds/zig-windows-x86_64-0.12.0-dev.2631+3069669bc.zip
https://ziglang.org/builds/zig-windows-aarch64-0.12.0-dev.2631+3069669bc.zip
https://ziglang.org/builds/zig-macos-aarch64-0.12.0-dev.2631+3069669bc.tar.xz
https://ziglang.org/builds/zig-macos-x86_64-0.12.0-dev.2631+3069669bc.tar.xz
https://ziglang.org/builds/zig-linux-x86_64-0.12.0-dev.2631+3069669bc.tar.xz
https://ziglang.org/builds/zig-linux-aarch64-0.12.0-dev.2631+3069669bc.tar.xz

**Comment by motiejus** [comment]
> ### Please list the URLs of the archives you'd like to mirror:

https://ziglang.org/builds/zig-windows-x86_64-0.12.0-dev.2631+3069669bc.zip
https://ziglang.org/builds/zig-windows-aarch64-0.12.0-dev.2631+3069669bc.zip
https://ziglang.org/builds/zig-macos-aarch64-0.12.0-dev.2631+3069669bc.tar.xz
https://ziglang.org/builds/zig-macos-x86_64-0.12.0-dev.2631+3069669bc.tar.xz
https://ziglang.org/builds/zig-linux-x86_64-0.12.0-dev.2631+3069669bc.tar.xz
https://ziglang.org/builds/zig-linux-aarch64-0.12.0-dev.2631+3069669bc.tar.xz

**Comment by motiejus-wix** [comment]
Thank you!
