### ISSUE TITLE
android_library aapt invocation doesn't handle public.xml

### ISSUE THREAD

**Issue by JakeWharton** [bazelbuild/bazel#2124]
### Description of the problem / feature request / question:

Android library projects can now [define a `public.xml`](https://developer.android.com/studio/projects/android-library.html#PrivateResources) file which turns all resources from being implicitly public to implicitly private with only the declared ones public.

The invocation of `aapt` needs to special case this file and pass it as an argument to the `-P` flag.

### If possible, provide a minimal example to reproduce the problem:

```
$ tree
.
├── AndroidManifest.xml
├── BUILD
├── WORKSPACE
├── res
│   └── values
│       ├── public.xml
│       └── strings.xml
└── src

$ cat WORKSPACE
android_sdk_repository(
    name = "android_sdk",
    path = "/Users/jw/android-sdk",
    api_level = 25,
    build_tools_version="25.0.0"
)

$ cat BUILD
android_library(
  name = "library",
  srcs = glob(["src/**"]),
  resource_files = glob(["res/**"]),
  custom_package = "com.example",
  manifest = "AndroidManifest.xml",
)

$ cat AndroidManifest.xml
<manifest package="com.example"/>

$ cat res/values/strings.xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <string name="hello">Hello</string>
  <string name="world">World</string>
</resources>

$ cat res/values/public.xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <public name="hello" type="string"/>
</resources>
```

### Environment info
* Operating System: Mac OS 10.11.6

* Bazel version (output of `bazel info release`): release HEAD-7585552-homebrew

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

Nope!

### Anything else, information or logs or outputs that would be helpful?

Here's the current output which attempts to process the `public.xml` as a normal resource which would otherwise require the `id` attribute. This is used by AOSP to create stable resource IDs across versions but isn't needed for library projects.

```
ERROR: /Users/jw/dev/square/cash/keypad/src/BUILD:1:1: Processing Android resources for //keypad/src:library failed: AndroidResourceProcessingAction failed: error executing command bazel-out/host/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/AndroidResourceProcessingAction --buildToolsVersion 25.0.0 --aapt ... (remaining 25 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Error: /var/folders/w0/hr1h_7h50f3_pwd_nrk9l808000195/T/android_resources_tmp5212054701171546315/merged_resources/values/values.xml:2472: error: No 'id' attribute supplied <public>, and no previous id defined in this file.
Error:
Error: /var/folders/w0/hr1h_7h50f3_pwd_nrk9l808000195/T/android_resources_tmp5212054701171546315/merged_resources/values/values.xml:2474: error: No 'id' attribute supplied <public>, and no previous id defined in this file.
Error:
Error: /var/folders/w0/hr1h_7h50f3_pwd_nrk9l808000195/T/android_resources_tmp5212054701171546315/merged_resources/values/values.xml:2476: error: No 'id' attribute supplied <public>, and no previous id defined in this file.
Error:
Error: /var/folders/w0/hr1h_7h50f3_pwd_nrk9l808000195/T/android_resources_tmp5212054701171546315/merged_resources/values/values.xml:2478: error: No 'id' attribute supplied <public>, and no previous id defined in this file.
Error:
Nov 22, 2016 6:03:59 PM com.google.devtools.build.android.AndroidResourceProcessingAction main
SEVERE: Error during processing resources
com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	bazel-out/host/bin/external/android_sdk/aapt_binary package -f --no-crunch --no-version-vectors -I external/android_sdk/platforms/android-25/android.jar -M /var/folders/w0/hr1h_7h50f3_pwd_nrk9l808000195/T/android_resources_tmp5212054701171546315/manifest-aapt-dummy/AndroidManifest.xml -S /var/folders/w0/hr1h_7h50f3_pwd_nrk9l808000195/T/android_resources_tmp5212054701171546315/merged_resources -m -J /var/folders/w0/hr1h_7h50f3_pwd_nrk9l808000195/T/android_resources_tmp5212054701171546315/generated_resources --output-text-symbols /var/folders/w0/hr1h_7h50f3_pwd_nrk9l808000195/T/android_resources_tmp5212054701171546315/generated_resources -P /var/folders/w0/hr1h_7h50f3_pwd_nrk9l808000195/T/android_resources_tmp5212054701171546315/merged_resources/values/public.xml --debug-mode --custom-package com.squareup.cash.keypad --non-constant-id -0 apk
Error Code:
	1
Output:

Error at 2472 : /var/folders/w0/hr1h_7h50f3_pwd_nrk9l808000195/T/android_resources_tmp5212054701171546315/merged_resources/values/values.xml:2472: error: No 'id' attribute supplied <public>, and no previous id defined in this file.
2467	:  </declare-styleable>
2468	:  <!-- keypad/src/main/res/values/public.xml -->
2469	:  <eat-comment/>
2470	:
2471	:  <public name="keypad_buttonGap" type="attr"/>
2472	:
2473	:  <public name="keypad_extraButton" type="attr"/>
2474	:
2475	:  <public name="keypad_lineColor" type="attr"/>
2476	:
```

The `aapt` invocation by Bazel looks like this:
```
 bazel-out/host/bin/external/android_sdk/aapt_binary package -f --no-crunch --no-version-vectors -I external/android_sdk/platforms/android-25/android.jar -M /var/folders/w0/hr1h_7h50f3_pwd_nrk9l808000195/T/android_resources_tmp5212054701171546315/manifest-aapt-dummy/AndroidManifest.xml -S /var/folders/w0/hr1h_7h50f3_pwd_nrk9l808000195/T/android_resources_tmp5212054701171546315/merged_resources -m -J /var/folders/w0/hr1h_7h50f3_pwd_nrk9l808000195/T/android_resources_tmp5212054701171546315/generated_resources -P /var/folders/w0/hr1h_7h50f3_pwd_nrk9l808000195/T/android_resources_tmp5212054701171546315/merged_resources/values/public.xml --output-text-symbols /var/folders/w0/hr1h_7h50f3_pwd_nrk9l808000195/T/android_resources_tmp5212054701171546315/generated_resources --custom-package com.squareup.cash.keypad --non-constant-id -0 apk
```
and the same project with Gradle would execute `aapt` like this:
```
 /Users/jw/android-sdk/build-tools/25.0.0/aapt package -f --no-crunch --no-version-vectors -I /Users/jw/android-sdk/platforms/android-25/android.jar -M /Users/jw/dev/square/cash/keypad/build/intermediates/manifests/aapt/release/AndroidManifest.xml -S /Users/jw/dev/square/cash/keypad/build/intermediates/res/merged/release -m -J /Users/jw/dev/square/cash/keypad/build/generated/source/r/release --output-text-symbols /Users/jw/dev/square/cash/keypad/build/intermediates/bundles/release --custom-package com.squareup.cash.keypad --non-constant-id -0 apk
```
The difference (with paths normalized) is the absence of this flag by Bazel:
```
-P /var/folders/w0/hr1h_7h50f3_pwd_nrk9l808000195/T/android_resources_tmp5212054701171546315/merged_resources/values/public.xml
```

**Comment by aj-michael** [comment]
Hmmm, I'm confused. From your two aapt command lines, it appears that Bazel *is* passing `-P` and Gradle *is not* passing `-P`.

**Comment by JakeWharton** [comment]
Eeep you're right. Let me try to confirm again.

**Comment by JakeWharton** [comment]
Yep, confirmed that Bazel is instead the one passing the additional `-P` flag compared to Gradle. I must have gotten my commands reversed when doing investigation.

The `aapt` help doesn't offer much here in terms of explanation:
```
   -P  specify where to output public resource definitions
```
but I'm guessing `-P` is for when you want to specify stable public resource IDs like the Android OS itself would want to do.

I can investigate further, but I don't have the time right now.

**Comment by JakeWharton** [comment]
So within the flags specifically for the `package` command it lists `-P` as:
```
[-P public-definitions-file]
```
whose description corresponds more to the behavior that's happening here. I'm going to try to take a look at the source tonight to see if I can learn more about why/when this behavior was added.

**Comment by JakeWharton** [comment]
The behavior was added in d8ffb712a8d4247c312c6f7df346d5c21e3246aa without much direct explanation.

Since the `-P` flag to `aapt` triggers a very specific, niche behavior and `public.xml` is now becoming a more common thing, I'm inclined to think it should be opt-in. Perhaps by specifying a `public_definitions` attribute to `android_library`?

**Comment by ldjhust** [comment]
Hi @aj-michael @JakeWharton , what's the solution here? I'm using `public.xml` on my android project too, but the bazel failed with the same error.

My bazel version:
```
Build label: 0.4.5-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 13:39:33 2017 (1489671573)
Build timestamp: 1489671573
Build timestamp as int: 1489671573
```

And my system is macOS Sierra 10.12.4.d

Thanks very much!

**Comment by aj-michael** [comment]
Unfortunately I don't think this is something Bazel supports at this time. Perhaps @apelle03 can comment on why Bazel does what it does.

And perhaps @ahumesky can comment on our prioritization of this issue for the future.

**Comment by apelle03** [comment]
The [ public/private resources ](https://developer.android.com/studio/projects/android-library.html#PrivateResources) functionality is provided directly by Gradle. Gradle processes the `public.xml` file and then passes only the appropriate resources to `aapt`, omitting the `public.xml`, meaning the command line difference is unrelated. This would need to be implemented in Bazel. @ahumesky for prioritization.

For context, the `-P` flag indicates to `aapt` to output the id assignments it has made. It can accept `<public>` resources with an `id` attribute to indicate what ids to assign to specific resources. This is why the `aapt` error mentions missing `id` attributes. Bazel uses the `-P` flag to maintain stable ids across the multiple `aapt` invocations involved in resource shrinking.

**Comment by ldjhust** [comment]
OK, thanks very much, guys, I get it. So, is it going to be implemented in the [**0.6**](https://github.com/bazelbuild/bazel/milestone/5) version? Cause I find that ahumesky has added it to the [**0.6**](https://github.com/bazelbuild/bazel/milestone/5) milestone.

**Comment by justhecuke** [comment]
I'm blocked on this since my codebase uses public.xml a lot. Since this hasn't had movement for years I'm going to assume that no one will be fixing this in the near future.

Is there someone who can point me in the right direction so I can get hacking at things? I'm not familiar with how bazel's native rules are implemented nor what actually needs to be done here.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
