### ISSUE TITLE
[7.1.0] Allow `@repo_name` labels in override attributes

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21248]
Forked from #21188

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
cherry-pick: https://github.com/bazelbuild/bazel/pull/21313

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21314
