### ISSUE TITLE
Missing documentation on incompatible_disallow_unsound_directory_outputs

### ISSUE THREAD

**Issue by tyler-french** [bazelbuild/bazel#21245]
### Page link:

https://bazel.build/reference/command-line-reference

### Problem description (include actual vs expected text, if applicable):

This was a breaking change in Bazel 7 that was very difficult to debug. It should be mentioned in the release notes and the documentation that this flag can be used to match previous behavior.
```
--incompatible_disallow_unsound_directory_outputs
```

### Where do you see this issue? (include link to specific section of the page, if applicable)

https://github.com/bazelbuild/bazel/releases/tag/7.0.0

### Any other information you'd like to share?

Relates to: https://github.com/bazelbuild/bazel/issues/18646

**Comment by fmeum** [comment]
Cc @tjgq

**Comment by iancha1992** [comment]
cc: @bazelbuild/triage @keertk

**Comment by tjgq** [comment]
The flag documentation has been fixed for 7.1.0 (for 8.x it doesn't make sense, since the flag has been no-op'ed). The release notes at https://github.com/bazelbuild/bazel/releases/tag/7.0.0 have been amended. Thanks for bringing this up!

**Comment by tyler-french** [comment]
> The flag documentation has been fixed for 7.1.0 (for 8.x it doesn't make sense, since the flag has been no-op'ed). The release notes at https://github.com/bazelbuild/bazel/releases/tag/7.0.0 have been amended. Thanks for bringing this up!

Thank you for doing this!

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.1.0 RC1](https://releases.bazel.build/7.1.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!
