### ISSUE TITLE
Sandbox reuse preserves test`_tmp` directory

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#21253]
### Description of the bug:

The `_tmp` directory created for tests is preserved in the sandbox stash.

While I haven't benchmarked the effect of this, it would at least waste disk space and may also negatively affect performance of sandbox reuse.

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by keertk** [comment]
@bazel-io fork 7.1.0

**Comment by oquenchil** [comment]
Hey Fabian, are you sure about this?

I see [here](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/sandbox/SandboxStash.java;drc=f799eb14e747ed95fe79fafedec7ccd0b2e50a1f;l=124) that we are only stashing the `execroot` from the `sandboxBase`. The `_hermetic_tmp` directory is a sibling of the `execroot`.

The testing code I wrote to repro this isn't giving me any hermetic tmp directory being copied into the stash. Under `sandboxBase/execroot/$TEST_WORKSPACE/`, I do see a  `_tmp` directory. It would be good not to copy that one too but it's not related to the hermetic tmp dir. Is that the one you meant? As far as I can see that would only be created for test rules though. Was this prompted by the test rules in rules_oci?

Thanks!

**Comment by fmeum** [comment]
Thanks for investigating and sorry for the false alarm - I saw the `_tmp` and thought that it was the hermetic tmp dir.

**Comment by oquenchil** [comment]
Oh I can still fix the _tmp one. I think it makes total sense not to stash that in tests.

**Comment by fmeum** [comment]
I updated title and description.
