### ISSUE TITLE
Output_groups are not documented.

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#2127]
`filegroup`'s documentation refers to `output_group` but there is no documentation on how one can write a rule that uses these. 

https://www.bazel.io/versions/master/docs/be/general.html#filegroup

https://bazel.build/search.html?cx=012346921571893344015%3Axv_nfgpzbu4&cof=FORID%3A10&ie=UTF-8&q=output_group

**Comment by pcj** [comment]
+1 to document this better.  The only use case I've discovered is to use the `--output_group` in conjunction with an aspect implementation to determine which files to produce. See https://github.com/pcj/bazel_aspects/blob/master/Makefile.

What is/are the main use-cases for output_groups within Google?

**Comment by mhlopko** [comment]
Hello Dmitry, is this still expected to be fixed in 0.5? It's still at least 2 weeks away, but we're getting there :)

**Comment by dslomov** [comment]
Yes certainly. As it is documentation, it's not really tied to a release

On Apr 10, 2017 12:51 PM, "Marcel Hlopko" <notifications@github.com> wrote:

Hello Dmitry, is this still expected to be fixed in 0.5? It's still at
least 2 weeks away, but we're getting there :)

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/bazelbuild/bazel/issues/2127#issuecomment-292915532>,
or mute the thread

**Comment by dslomov** [comment]
Now it is all documented: https://docs.bazel.build/versions/master/command-line-reference.html#flag--output_groups

**Comment by endobson** [comment]
The spacing seems off in that description.

>Specifies which output groups of the top-level targets to build. If omitted, a default set of output groups are built. When specified the default set is overridden.However you may use --output_groups=+<output_group> or -- output_groups=-<output_group> to instead modify the set of output groups.

Particularly a space is missing in  `overridden.However` and and extra one is in `-- output_groups=-<output_group>`.

A confusing part of that description is that it says it builds `the default set of output groups`, which seems like it is multiple output groups instead of just being the default output group (Which is what I thought it did). If so what is that set of groups, because knowing that seems like the only reason to need to use the negative output groups, because otherwise I could just avoid adding it in with positive output groups.

The prose documentation here, https://docs.bazel.build/versions/master/skylark/rules.html#output-groups should probably use the additive option to output groups instead of defining a new output group that implements that behavior in the rule.

**Comment by natansil** [comment]
It seems that documentation is still missing for output_groups of [aspects](https://docs.bazel.build/versions/master/skylark/aspects.html)

**Comment by htuch** [comment]
+1 to @natansil, aspects do not have any docs for output groups, please reopen.

**Comment by htuch** [comment]
Never mind, this looks to be documented at https://docs.bazel.build/versions/master/skylark/rules.html#output-groups. I still think it would be useful to link from https://docs.bazel.build/versions/master/skylark/aspects.html to here and explain the CLI requirement to specify `--output_groups` in the aspects docs.
