### ISSUE TITLE
[7.1.0] Omit unique module versions from canonical repo names

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21284]
Forked from #21035

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
I cannot cherry-pick this since `src/test/py/bazel/bzlmod/bazel_vendor_test.py` file is missing in the release-7.1.0 branch currently. 

cc: @fmeum @Wyverald @meteorcloudy

**Comment by fmeum** [comment]
The vendor command needs to be cherry-picked first. @SalmaSamy

**Comment by Wyverald** [comment]
cherry-pick: https://github.com/bazelbuild/bazel/pull/21316
