### ISSUE TITLE
[7.1.0] Bazel CI Flaky Test: //src/test/shell/bazel:starlark_repository_test (test_download_failure_message)

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21297]
Forked from #21238

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
cherry-pick: https://github.com/bazelbuild/bazel/pull/21305
