### ISSUE TITLE
[7.1.0] Use execution info instead of hard-coded mnemonics for Java path mapping

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21296]
Forked from #21093

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21461
