### ISSUE TITLE
[7.1.0] Fix flakiness in //src/test/shell/bazel:starlark_repository_test

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#21308]
### Commit IDs

83b825f79a0d255dea6b05a354d0ad343ef1bcfa

### Category

team-ExternalDeps

### Reviewers

@iancha1992

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/21309: https://github.com/bazelbuild/bazel/commit/83b825f79a0d255dea6b05a354d0ad343ef1bcfa.
