### ISSUE TITLE
Cannot use swift_library rule without providing alias to xcrunwrapper

### ISSUE THREAD

**Issue by zergtmn** [bazelbuild/bazel#2133]
When using swift_library rule outside of Bazel workspace the build fails due to missing target `//external:xcrunwrapper`:
```python
load("@bazel_tools//tools/build_defs/apple:swift.bzl", "swift_library")

swift_library(
    name = "lib",
    srcs = ["foo.swift"]
)
```

```
$ bazel build //:lib --ios_sdk_version=10.1
ERROR: /Users/sergey/dev/swift_library_test/BUILD:3:1: every rule of type swift_library implicitly depends upon the target '//external:
xcrunwrapper', but this target could not be found because of: no such target '//external:xcrunwrapper': target 'xcrunwrapper' not declared in pa
ckage 'external' defined by /Users/sergey/dev/swift_library_test/WORKSPACE.
ERROR: Analysis of target '//:lib' failed; build aborted.
```
The build succeedes if I provide an alias to xcrunwrapper:
```python
bind(
    name = "xcrunwrapper",
    actual = "@bazel_tools//tools/objc:xcrunwrapper"
)
```
Bazel version: 0.4.0

**Comment by zergtmn** [comment]
cc @dmishe

**Comment by dmishe** [comment]
@c-parsons, I thought this was automatic for bazel WORKSPACE, did something change? Could it affect other objc_ rules?

**Comment by c-parsons** [comment]
A clean pull seems to create a WORKSPACE file at the workspace level with that binding already set. 
Did you happen to wipe your own WORKSPACE file post-install? If not, how are you installing bazel? (using the installer or building from source?)

**Comment by zergtmn** [comment]
Sorry if my explanation wasn't clear enough. I use swift_library rule in my own project which is located in a different workspace than Bazel. I build it with pre-built binary 0.4.0 from Homebrew.
To load the rule I use:
```
load("@bazel_tools//tools/build_defs/apple:swift.bzl", "swift_library")
```
but when I use it the build fails with error from the first post.
If I add `xcrunwrapper` binding to my project's WORKSPACE file the build succeeds.
I'm not sure if it's the intended behaviour that user should provide the binding or just using `load` should be enough.

**Comment by c-parsons** [comment]
This is indeed intended -- certain things defined in the WORKSPACE are required. If you are going to create your own WORKSPACE file, you should base it off of the given WORKSPACE file and add whatever else you need.
