### ISSUE TITLE
Error No matching toolchains found for types @@bazel_tools//tools/python:toolchain_type in Downstream CI with 7.1


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#21348]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3657#018da594-7593-4e8f-850f-187a1a4cb063

Platform: Windows, MacOS, Ubuntu

Logs:

```
(03:07:01) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/dd5f1ab0fb45f70a5ca8f71a165f3850/external/bazel_tools/tools/jdk/BUILD:133:10: While resolving toolchains for target @@bazel_tools//tools/jdk:proguard_whitelister (102280f): No matching toolchains found for types @@bazel_tools//tools/python:toolchain_type.
To debug, rerun with --toolchain_resolution_debug='@@bazel_tools//tools/python:toolchain_type'
```

CC Greenteam @mai93 @meteorcloudy 

List of Downstream projects failing with above error logs

1.  [Stardoc](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3657#_)
2.  [rules\_apple](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3657#018da594-8614-405a-804f-5c31acc185ae)
3.  [rules\_dotnet](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3657#018da594-8ed8-47c2-9261-89f76b0e0547)
4.  [rules\_proto](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3657#018da594-71d7-4919-ab46-5e3c575c225f)
5.  [Bazel skylib](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3657#018da594-7593-4e8f-850f-187a1a4cb063)

**Comment by sgowroji** [comment]
I tried this '''
bazelisk --bisect=f9acae2b1f486c74f7b465b11e18d8d8d1ed410e..3e170287347a18836295178f170980a05a1de546 build //src:bazel //src:bazel_jdk_minimal //src:test_repos //src/main/java/...'''. It was succeeded,And didn't resulted any culprit.

**Comment by meteorcloudy** [comment]
@sgowroji You should bisect the broken downstream project, not building Bazel itself.
```
pcloudy@pcloudy-macbookpro3:~/workspace/bazel-skylib (main)
$ bazel --bisect=release-7.0.0..release-7.1.0 build //...
```

**Comment by meteorcloudy** [comment]
And the result is
```
--- Bisect Result

first bad commit is https://github.com/bazelbuild/bazel/commit/86a5f6b66dac4001c88fa00f938e0b482aede4a7
```

**Comment by sgowroji** [comment]
Yes 


--- Succeeded at 1821a88927d27f64cd4d9cd719d2899383e2f066



--- Bisect Result

first bad commit is https://github.com/bazelbuild/bazel/commit/86a5f6b66dac4001c88fa00f938e0b482aede4a7
sgowroji-macbookpro3:bazel-skylib sgowroji$

**Comment by iancha1992** [comment]
Fixed by https://github.com/bazelbuild/bazel/pull/21369
