### ISSUE TITLE
[Mirror]  vscode-shellcheck / shellcheck-binaries for rules_shellcheck

### ISSUE THREAD

**Issue by chenxiao0228** [bazelbuild/bazel#21340]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/vscode-shellcheck/shellcheck-binaries/releases/download/v0.9.0/shellcheck-v0.9.0.darwin.aarch64.tar.gz
https://github.com/vscode-shellcheck/shellcheck-binaries/releases/download/v0.9.0/shellcheck-v0.9.0.darwin.x86_64.tar.gz
https://github.com/vscode-shellcheck/shellcheck-binaries/releases/download/v0.9.0/shellcheck-v0.9.0.linux.aarch64.tar.gz
https://github.com/vscode-shellcheck/shellcheck-binaries/releases/download/v0.9.0/shellcheck-v0.9.0.linux.armv6hf.tar.gz
https://github.com/vscode-shellcheck/shellcheck-binaries/releases/download/v0.9.0/shellcheck-v0.9.0.linux.x86_64.tar.gz
https://github.com/vscode-shellcheck/shellcheck-binaries/releases/download/v0.9.0/shellcheck-v0.9.0.windows.x86_64.tar.gz

**Comment by sgowroji** [comment]
Here you go

1.  [https://mirror.bazel.build/github.com/vscode-shellcheck/shellcheck-binaries/releases/download/v0.9.0/shellcheck-v0.9.0.darwin.aarch64.tar.gz](https://mirror.bazel.build/github.com/vscode-shellcheck/shellcheck-binaries/releases/download/v0.9.0/shellcheck-v0.9.0.darwin.aarch64.tar.gz)
2.  [https://mirror.bazel.build/github.com/vscode-shellcheck/shellcheck-binaries/releases/download/v0.9.0/shellcheck-v0.9.0.darwin.x86_64.tar.gz](https://mirror.bazel.build/github.com/vscode-shellcheck/shellcheck-binaries/releases/download/v0.9.0/shellcheck-v0.9.0.darwin.x86_64.tar.gz)
3.  [https://mirror.bazel.build/github.com/vscode-shellcheck/shellcheck-binaries/releases/download/v0.9.0/shellcheck-v0.9.0.linux.aarch64.tar.gz](https://mirror.bazel.build/github.com/vscode-shellcheck/shellcheck-binaries/releases/download/v0.9.0/shellcheck-v0.9.0.linux.aarch64.tar.gz)
4.  [https://mirror.bazel.build/github.com/vscode-shellcheck/shellcheck-binaries/releases/download/v0.9.0/shellcheck-v0.9.0.linux.armv6hf.tar.gz](https://mirror.bazel.build/github.com/vscode-shellcheck/shellcheck-binaries/releases/download/v0.9.0/shellcheck-v0.9.0.linux.armv6hf.tar.gz)
5.  [https://mirror.bazel.build/github.com/vscode-shellcheck/shellcheck-binaries/releases/download/v0.9.0/shellcheck-v0.9.0.linux.x86_64.tar.gz](https://mirror.bazel.build/github.com/vscode-shellcheck/shellcheck-binaries/releases/download/v0.9.0/shellcheck-v0.9.0.linux.x86_64.tar.gz)
6.  https://mirror.bazel.build/github.com/vscode-shellcheck/shellcheck-binaries/releases/download/v0.9.0/shellcheck-v0.9.0.windows.x86_64.tar.gz
