### ISSUE TITLE
Label.repo_name no longer returns the canonical repo name 

### ISSUE THREAD

**Issue by hvadehra** [bazelbuild/bazel#21350]
### Description of the bug:

Likely culprit is a54a393d209ab9c8cf5e80b2a0ef092196c17df3

cc @c-mita 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

//src/test/shell/bazel/bazel_coverage_java_test.sh and friends no longer pick up changes to java_tools

Hardcoding RULES_JAVA_REPO_NAME to "rules_java~" gets the overrides working again.

**Comment by fmeum** [comment]
Sorry for the breakage. The scheme for canonical repo names will be different between `.bazelversion` Bazel and Bazel at HEAD until 7.1.0 is out. 

For now, hardcoding the name is totally fine.

**Comment by fmeum** [comment]
Cc @meteorcloudy

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.1.0 RC1](https://releases.bazel.build/7.1.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!
