### ISSUE TITLE
[7.1.0] bzlmod: module extension-invoked repository rules from `.bzl` files that (transitively) load from external repos yield cycle errors w/usage in WORKSPACE.bzlmod

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21373]
Forked from #21289

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
cc: @meteorcloudy @Wyverald

**Comment by Wyverald** [comment]
cherry-pick in https://github.com/bazelbuild/bazel/pull/21435
