### ISSUE TITLE
Introduce py3_binary

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2142]
Since for all Python scripts in our repo we have 3 set as standard, I have quite a lot of:

    py_binary(
        name = "foo",
        srcs = [
            "foo.py"
        ],
        default_python_version = "PY3", # all the time
        srcs_version = "PY3ONLY", # all the time
    )

Now I think for this scenario (and for Python 2) it would make sense to have shortcuts: `py3_binary`, `py3_library`, `py2_binary`, `py2_library` with the appropriate exclusive versions set.

**Comment by iirina** [comment]
Hi Andreas,

For your use-case I recommend creating a [Skylark macro](https://www.bazel.io/versions/master/docs/skylark/cookbook.html#macro_native) that simulates a `py3_library` etc like this:

```
def python3_binary(name, srcs):
  native.py_binary(
       name = name, 
       srcs = srcs, 
       default_python_version = "PY3",
       srcs_version = "PY3ONLY"
)
```

Cheers,
Irina

**Comment by abergmeier-dsfishlabs** [comment]
> For your use-case I recommend creating a Skylark macro that simulates a py3_library etc like this:

Do not worry, I have similar code already in use. Question is whether this would not be better upstreamed...

**Comment by iirina** [comment]
There are no plans for now to add these native rules, especially since they are such a good fit for using Skylark macros. What advantage would it bring to you using `python3_binary` as a native rule instead of a macro?
Adding @lberki to see if he has something to add.

**Comment by abergmeier-dsfishlabs** [comment]
To me not much - perhaps others would find it convenient.
