### ISSUE TITLE
[7.1.0] Add a native image of turbine to the prebuilt Java tools

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#21423]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/5f7968448f898b7d81986123b9fdd92945a134e5

### Category

team-Rules-Java

### Reviewers

@iancha1992

**Comment by bazel-io** [comment]
Failed commmits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/5f7968448f898b7d81986123b9fdd92945a134e5.
Please resolve manually.
cc: @bazelbuild/triage

**Comment by keertk** [comment]
https://github.com/bazelbuild/bazel/pull/21426
