### ISSUE TITLE
Order of include path entries on the command line is unspecified

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#2143]
Apparently, given a certain shape of the dependency graph, it's not specified in which order `-I` include path entries appear if there are `cc_inc_library` or `cc_library.includes=` rules in it.

This should be fixed, because undefined behavior is a bad thing, mmmkay?

**Comment by mhlopko** [comment]
Definitely needs to be fixed. Will look into that.

**Comment by lberki** [comment]
The simplest would be to figure out what we do now, and if it's sane enough, codify that. For extra points, refactor things so that it's obvious from the implementation. I spent ~10 minutes looking at it and it was very, very far from being obvious.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
