### ISSUE TITLE
Improve performance of --reuse_sandbox_directories

### ISSUE THREAD

**Issue by oquenchil** [bazelbuild/bazel#21431]
### Commit IDs

eac7c968f40066aef5b5bf9b6177dd6c1af543ee, a48aa0004a02fb16ca08da6454986d023dd00c4b, 0253bde3abbe2bd19508435362ed3e9ac91bdc92, e9022f6731b4f62d3a08bdc4eacce70ad28e3c78, 8a18dff5fe5eaaa89823ee26e0e20d2ec41e6683

### Category

team-Local-Exec

### Reviewers

wyverald

**Comment by Wyverald** [comment]
@iancha1992 hmm... the cherry-picker failed with `substring not found` (https://github.com/bazelbuild/bazel/actions/runs/7977695412/job/21781150278#step:5:153) with not much more to go on. any idea why?
