### ISSUE TITLE
AssertionError Cannot find .runfiles directory at Bazel@HEAD in CI


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#21445]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3670#018dc96a-07ad-4346-8284-07ab270033c1

 Platform: RBE Ubuntu

 Logs: 
```
 raise AssertionError('Cannot find .runfiles directory for %s' % sys.argv[0])
AssertionError: Cannot find .runfiles directory for bazel-out/k8-opt-exec-ST-0d13311fffe3/bin/external/rules_pkg~/pkg/private/tar/build_tar
(02:10:56) INFO: Elapsed time: 8.959s, Critical Path: 5.12s
(02:10:56) INFO: 1066 processes: 528 remote cache hit, 342 internal, 2 linux-sandbox, 1 local, 193 remote.
(02:10:56) ERROR: Build did NOT complete successfully
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/bazel
git reset fffa0affebbacf1961a97ef7cd248be64487d480  --hard
export USE_BAZEL_VERSION=5867dbf884cbe859e705c73264c5750ee3cb3ce2
bazel build //src:bazel //src:bazel_jdk_minimal //src/main/java/... 
 ``` 
 CC Greenteam @fweikert

**Comment by meteorcloudy** [comment]
https://buildkite.com/bazel/culprit-finder/builds/8764#018de910-a10f-4f09-8bbf-1a3468072561 shows the culprit is 404d8d97fafedb7c43a3c164a7446d2e1bf2e436

/cc @lberki

**Comment by meteorcloudy** [comment]
Also ccing @tjgq

**Comment by meteorcloudy** [comment]
Maybe the Windows failures are also related? 
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3670#018dcef9-0899-47f8-9c34-469760f58434

**Comment by sgowroji** [comment]
CI is Green now. We are closing this issue.
