### ISSUE TITLE
[7.1.0] Enable tests on macOS

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21455]
Forked from #21381

**Comment by iancha1992** [comment]
@Wyverald @meteorcloudy I tried cherry-picking this to release-7.1.0. But looks like I'll actually need your help. Thanks

cc: @bazelbuild/triage

**Comment by meteorcloudy** [comment]
Thanks! I'm doing it at https://github.com/bazelbuild/bazel/pull/21456!
