### ISSUE TITLE
Maybe git_repository should fetch tarballs from GitHub

### ISSUE THREAD

**Issue by jart** [bazelbuild/bazel#2147]
Services like GitHub that have well-known HTTP interfaces for grabbing snapshots at specific revisions and tags.

For example:

- https://github.com/bazelbuild/bazel/archive/0.4.0.tar.gz
- https://github.com/bazelbuild/bazel/archive/a1699bd77f1770670eac191d701757b98556b1c5.tar.gz

Maybe it would be better if, under the hood, `git_repository` was able to recognize when `remote` is pointing to one of those services, and then transparently turn itself into `{new_,}http_archive` under the hood.

This will make things go significantly faster and more reliable for many users, without requiring any action on their part.

CC: @nitnelave @pcj 
See also: #1194

**Comment by abergmeier-dsfishlabs** [comment]
I would prefer to have some logic, which keeps the git history around, even if a `git_repo` gets invalidated and afterwards fetches based on that history. THAT would be way faster.
Not to mention LFS support.

Currently we already use what you want by simply using `http_archive` and it is pretty straight forward.

**Comment by trainman419** [comment]
This seems more surprising than useful, and debugging this feature when the remote tarball isn't available will be more confusing than just having an http_archive directory in your WORKSPACE file.

**Comment by jart** [comment]
Yes but many users aren't aware that http_archive is a much better option than git_repository in 90% of cases. Most users think, "I want something from GitHub, therefore I should use git_repository" and end up with slow builds as a result. We want builds for them to go fast, without asking them to upgrade their code.

**Comment by jwnimmer-tri** [comment]
I like the motivation, but is it possible to do this invisibly while preserving integrity checking?  I would expect the `commit=` from git and `sha256=` checksum of the archive to be unrelated, so we'd only be relying on https for authenticity?

For me at least, a big fat warning on https://bazel.build/versions/master/docs/be/workspace.html#new_git_repository would have been enough.  I was content to write RobotLocomotion/drake#4975 myself having eventually found the advice here.

**Comment by jart** [comment]
That's actually a very wise insight I hadn't considered @jwnimmer-tri. I guess the only solution is to get rid of `git_repository`.

**Comment by ittaiz** [comment]
@kchodorow the opinions above are unclear if this won't be more of a deficit than a gain given the surprise factor. Do you still think it's better to have this feature as is?

**Comment by kchodorow** [comment]
The change should be mostly invisible to users, as it falls back to using jGit if anything goes wrong with downloading the tarball.  To the user, this should just make GitHub repos "feel faster" and will avoid jGit bugs.  For private repositories, it may feel slightly slower (since there will be an initial 403 before the clone) but compared to the time the "average" clone has, I don't think this will be particularly noticeable.  What do you think the surprise factor would be?

I think it's a good idea to add a warning to `git_repository`/`new_git_repository`.

**Comment by jwnimmer-tri** [comment]
I glanced at the patch but didn't immediately see anything special for integrity checking -- the approach is to rely solely on `https` for authenticity, relying on https github trust to turn a commit hash into a tarball?  Perhaps the `sha256` tarball checksum should be an optional kwargs, as it is with `http_archive` -- the rule works without it, but careful users should set it.

**Comment by ittaiz** [comment]
Mainly the fact that you get a shallow clone without asking it and only for public github repositories. Without reading the code or this thread it can be a bit daunting.
I'm really not an expert but I think maybe documenting in big capital letters in a few strategic places when to use git_repository and more importantly when not to use it might be the best approach.

**Comment by kchodorow** [comment]
Well, I'm not doing all-caps, but I have 2 changes in code review: one adds a big warning and one adds a sha256 attribute.

**Comment by steren** [comment]
Adding a sha256 attribute to the signature of git_repository that is supposed to be the sha256 of the downloaded archive does not seem the right API to me.

I think that if the performance improvement introduced cannot guarantee integrity, then we should revert it, or at least making it opt-in (via an attribute?)

I agree that we can recommend to users who prefer performances over convenience to use http_archive for GitHub archives.

**Comment by pcj** [comment]
I'm not in favor of faking `git_repository` to become `http_archive` under the hood.  I agree it's more an issue with educating users than surprising them.

I'd be OK with popping a warning/suggestion to "hey, use http_archive instead!" if a git_repository could be substituted out, and a flag to silence those warnings, something like `--experimental_suppress_http_archive_recommendation`.

Even then, not sure it's worth the effort...

**Comment by steren** [comment]
I don't think it is worth a warning in Bazel itself. At best, it is a recommendation in the doc for better first build performances.

**Comment by ittaiz** [comment]
And also perhaps some cleanups in docs of the ecosystem. At least
rules_scala advocates the usage of git_repository and maybe others do as
well.

**Comment by jart** [comment]
I only opened this issue under the assumption that deprecating and removing `git_repository` wasn't an option on the table. I think that might benefit Bazel users more.

**Comment by steren** [comment]
Depending on public or private git repositories is critical to Bazel use cases for our external users. We should not deprecate the `git_repository` API. Only offering an archive dependency solution is a big step back. 

Instead we should improve its internal performances and stability.

**Comment by ittaiz** [comment]
What are the use cases where one needs a git repository? Not saying there
isn't one but I'm not sure it's clear and I think that if that is cleared
up then maybe the documentation can be explicit about when to use the
archive and when to use git

**Comment by steren** [comment]
Projects might organize their codebase in various git repositories or depend on open-source libraries available in public git repositories.

**Comment by ittaiz** [comment]
I understand that but why is git better than http archive? Because we don't
want to assume their git providers front a shallow clone via http?
The reason I'm asking is because if this is the only reason then making it
clear in the documentation might help users make the better choice based on
their providers.
Since git doesn't offer a shallow clone I don't see it becoming a real
competition where one doesn't needs the history.

**Comment by steren** [comment]
In my opinion, for API semantic reasons: if the user's goal is to depend on a *git repository*, the API should be about giving the coordinates to a git repository, not to an archive.

**Comment by ittaiz** [comment]
I definitely agree. I also agree that this feature sounds problematic for
exactly this reason.
I think that in the bigger scope of what users should use and for which
use-cases then this discussion is important.
Do you want us to move it to the discussion group?

**Comment by steren** [comment]
Yes, the dev mailing list is a better for this. However, I will be unable to answer until Tuesday.

**Comment by MarkusTeufelberger** [comment]
https://git-scm.com/docs/git-archive could be a better solution...
