### ISSUE TITLE
[7.1.0] Set RC branch when creating GitHub releases

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#21476]
### Commit IDs

748e18a66e91b9344df00f2f017bba64a400b2c6

### Category

team-OSS

### Reviewers

@iancha1992

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/21477: https://github.com/bazelbuild/bazel/commit/748e18a66e91b9344df00f2f017bba64a400b2c6.
