### ISSUE TITLE
Upgrading `rules_java` from `6.5.2` to `7.4.0` seemed to resolve this issue for us

### ISSUE THREAD

**Issue by AxelValerio9** [bazelbuild/bazel#21489]
Upgrading `rules_java` from `6.5.2` to `7.4.0` seemed to resolve this issue for us

_Originally posted by @hjellek in https://github.com/bazelbuild/bazel/issues/21481#issuecomment-1961247080_

**Comment by sgowroji** [comment]
Hi @AxelValerio9, Could you please elaborate your query with complete details. Thanks!
