### ISSUE TITLE
refactor: `blaze::MakeDirectories` should return `std::error_condition`

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2149]
Instead of just a plain bool, this method (and maybe others in the `blaze` and `blaze_util` namespaces) could return a `std::error_condition`.

Filed on behalf of @abergmeier-dsfishlabs .

**Comment by abergmeier-dsfishlabs** [comment]
@laszlocsomor Nice, thx.

**Comment by laszlocsomor** [comment]
I don't think we'll every fix this, nor does it seem to bring any benefit.
