### ISSUE TITLE
[7.1.0] Fix stale trash dir not cleaned up on worker creation

### ISSUE THREAD

**Issue by oquenchil** [bazelbuild/bazel#21508]
### Commit IDs

e482e8b244c6d0d77045609f9f541a5abdac72be

### Category

team-Local-Exec

### Reviewers

wyv

**Comment by bazel-io** [comment]
Failed commmits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/e482e8b244c6d0d77045609f9f541a5abdac72be.
Please resolve manually.
cc: @bazelbuild/triage

**Comment by keertk** [comment]
https://github.com/bazelbuild/bazel/pull/21511
