### ISSUE TITLE
[7.1.0] Add multiplex sandboxing support to JavaBuilder

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21518]
Forked from #21370

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
@fmeum @wilwell @cushon I need help cherry-pick this to release-7.1.0. Could you please take a look? Thanks

cc: @bazelbuild/triage

**Comment by fmeum** [comment]
@iancha1992 I submitted https://github.com/bazelbuild/bazel/pull/21598
