### ISSUE TITLE
cc_shared_library can not IMPORTED_LOCATION

### ISSUE THREAD

**Issue by lyqaiym** [bazelbuild/bazel#21513]
### Description of the bug:

I use cc_shared_library in xnnpack.
"cc_shared_library(
    name = "xnnpack_so2",
    deps = [
        ":android_log",
        ":xnnpack_for_tflite",
        ":allocator",
        ":amalgam_microkernels",
        ":common",
        ":logging",
        ":math",
        ":microkernels_h",
        ":microparams",
        ":microparams_init",
        ":operators",
        ":params",
        ":subgraph",
    ]
)"
I copy external/XNNPACK/bazel-bin/libxnnpack_so2.so to android studio.
in CMakeLists.txt

add_library(xnnpack_so SHARED IMPORTED)
set_target_properties(xnnpack_so PROPERTIES IMPORTED_LOCATION ${CMAKE_SOURCE_DIR}/libs/xnnpack/${CMAKE_ANDROID_ARCH_ABI}/libxnnpack_so2.so)

target_link_libraries(mediapipe_tasks_vision_jni
        xnnpack_so

System.loadLibrary("mediapipe_tasks_vision_jni")

java.lang.UnsatisfiedLinkError: dlopen failed: library "/Users/xxxxx/AndroidStudioProjects/mediapipegesture/framework/src/main/cpp/libs/xnnpack/arm64-v8a/libxnnpack_so2.so" not found: needed by /data/app/~~6q8zu150Yo089WF3x3j7oQ==/com.google.mediapipe.examples.gesturerecognizer-qrGJwBuHDk6VTilU9nubcA==/lib/arm64/libmediapipe_tasks_vision_jni.so in namespace clns-4

Run "readelf -aW libmediapipe_tasks_vision_jni.so"

Dynamic section at offset 0x36069e0 contains 110 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libglogd.so]
 0x0000000000000001 (NEEDED)             Shared library: [libprotobufd.so]
 0x0000000000000001 (NEEDED)             Shared library: [libprotobuf-lited.so]
 0x0000000000000001 (NEEDED)             Shared library: [libopencv_java4.so]
 0x0000000000000001 (NEEDED)             Shared library: [libpthreadpool.so]
 0x0000000000000001 (NEEDED)             Shared library: [/Users/xxxxx/AndroidStudioProjects/mediapipegesture/framework/src/main/cpp/libs/xnnpack/arm64-v8a/libxnnpack_so2.so]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so]

**Comment by sgowroji** [comment]
Hi @lyqaiym, can you provide complete steps to reproduce the issue. Thanks!

**Comment by lyqaiym** [comment]
step 1:
`cc_shared_library(
name = "xnnpack_so2",
deps = [
":android_log",
":xnnpack_for_tflite",
":allocator",
":amalgam_microkernels",
":common",
":logging",
":math",
":microkernels_h",
":microparams",
":microparams_init",
":operators",
":params",
":subgraph",
]
)`
step 2:
`bazel build --verbose_failures --sandbox_debug -c opt --config=android_arm64 --experimental_cc_shared_library xnnpack_so2`

Use in CMakeLists.txt 
`add_library(xnnpack_so SHARED IMPORTED)
 set_target_properties(xnnpack_so PROPERTIES IMPORTED_LOCATION ${CMAKE_SOURCE_DIR}/libs/xnnpack/${CMAKE_ANDROID_ARCH_ABI}/libxnnpack_so2.so)
target_link_libraries(mediapipe_tasks_vision_jni
        xnnpack_so
        )`
has problem.
Now I change this,move add_library
`target_link_libraries(mediapipe_tasks_vision_jni
        ${CMAKE_SOURCE_DIR}/libs/xnnpack/${CMAKE_ANDROID_ARCH_ABI}/libxnnpack_so2.so
        )`
is ok.

**Comment by comius** [comment]
This looks like a problem loading the library in Java (`java.lang.UnsatisfiedLinkError: dlopen failed: library`), not Bazel or cc_shared_library.

**Comment by fmeum** [comment]
@lyqaiym You could give https://github.com/fmeum/rules_jni a try.
