### ISSUE TITLE
Bazel rebuilds all when $PATH changes

### ISSUE THREAD

**Issue by kayasoze** [bazelbuild/bazel#2153]
I have a workflow where I may bazel build from one or more SSH connections.  When I build from one SSH connection and then switch to the other, the bazel daemon restarts and rebuilds all dependencies, even though the bazel build options have not changed.

**Comment by damienmg** [comment]
Do you run in different directories? Different users?

**Comment by kayasoze** [comment]
Nope--same user same directory.

**Comment by damienmg** [comment]
Difference in the environment?

**Comment by kayasoze** [comment]
One is a login shell and one is not, thus picking up slightly different sets of environment variables, such as $PATH, $LANG, $VISUAL, $LS_COLORS etc.  However, they still end up executing the same Bazel binary, and bazel info shows the same server PID.   They're even multiplexed over the same SSH session.  The only major difference between sessions is that one is attached to a tty and the other is not.

**Comment by damienmg** [comment]
This is WAI. Set --action_env PATH=YourPath in your bazelrc to avoid this behaviour.

**Comment by kayasoze** [comment]
I can reproduce the bug with different $PATHs even with the following in my .bazelrc:

```
# Prevent PATH changes from invalidating builds when switching between
# interactive and non-interactive shells.
build --action_env=PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
test --action_env=PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
```

I can't use `common` because it interferes with `bazel query`.  So far, the only reliable way of preventing this issue is to make sure $PATH is identical across invocations, so perhaps this bug should be reopened.

**Comment by mariusgrigoriu** [comment]
Still happens with Bazel 1.2.0. Doesn't matter that you set the action_env in your .bazelrc file if the PATH changes you're getting a rebuild.
