### ISSUE TITLE
Inconsistent constraints handling of OutputFileConfiguredTargets

### ISSUE THREAD

**Issue by pcjanzen** [bazelbuild/bazel#21538]
### Description of the bug:

When a rule creates additional labels using output-typed attributes, and then those output-file labels are used inside a select(), Bazel checks the restricted_to constraints for that dependency "statically", as if they weren't in a select at all. This leads to the confounding behavior that the following construct passes analysis fine:

```
genrule(
    name = "foo",
    outs = ["foo.txt"],
    cmd = "echo foo > \"$@\"",
    restricted_to = [":a"],
)

filegroup(
    name = "uses_foo",
    srcs = select({
        ":some_condition": [":foo"],
        "//conditions:default": [],
    }),
    restricted_to = [":a", ":b"]
)
```

But if the label in the srcs select is changed to ":foo.txt" (which is the exact same thing) bazel will error with
```
ERROR: in filegroup rule //:uses_foo:
  dependency //:foo doesn't support expected environment: //:b
```

### Which category does this issue belong to?

Core

### Which operating system are you running Bazel on?

MacOS

### What is the output of `bazel info release`?

release 7.0.2

**Comment by pcjanzen** [comment]
A proposed fix is at https://github.com/bazelbuild/bazel/pull/21539

**Comment by gregestren** [comment]
Did that fix resolve this?

**Comment by pcjanzen** [comment]
Yep, done.
