### ISSUE TITLE
Claimed documentation on select/config_settings doesn't exist.

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#2154]
From: https://bazel.build/versions/master/docs/be/general.html#config_setting

The currently endorsed method for creating custom conditions that can't be expressed through dedicated build flags is through the --define flag. Use this flag with caution: it's not ideal and only endorsed for lack of a currently better workaround. See the Configurable attributes section for more discussion.

But the linked configurable attributes section (https://bazel.build/versions/master/docs/be/common-definitions.html#configurable-attributes) has no discussion on define or how to use it.

**Comment by gregestren** [comment]
`--define` is still missing from Bazel's [user manual](https://docs.bazel.build/versions/master/user-manual.html) for reasons I don't personally understand. It may be related to the upcoming effort to deprecate `--define` for proper custom-defined flags.

Anyway, more thorough walkthrough documentation for `config_setting` / `select` is coming down the pipeline - the review is already [underway](https://bazel-review.googlesource.com/c/bazel/+/58953), and includes specific references to `--define`.
