### ISSUE TITLE
[7.1.0] Unable to detect AndroidIdeInfo

### ISSUE THREAD

**Issue by comius** [bazelbuild/bazel#21544]
### Description of the bug:

With AndroidIdeInfo exposed on top-level, it's hard to detect it in IntelliJ plugin, considering the plugin works on different Bazel versions.

### Which category does this issue belong to?

Android

**Comment by keertk** [comment]
@bazel-io fork 7.1.0

**Comment by Wyverald** [comment]
Is work happening on this right now? Does it need to block the 7.1.0 release?

**Comment by comius** [comment]
> Is work happening on this right now? Does it need to block the 7.1.0 release?

Internal PR is in review. I'd prefer to have it in the release, so that legacy struct providers cleanup is not further blocked.

**Comment by meteorcloudy** [comment]
We expect to cut rc2 today, is this going to be fixed in time?

**Comment by iancha1992** [comment]
Fixed in https://github.com/bazelbuild/bazel/pull/21607

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.1.0 RC2](https://github.com/bazelbuild/bazel/releases/tag/7.1.0rc2). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.1.0rc2. Thanks!
