### ISSUE TITLE
Why does install require ~/.bazelrc to be backed up?

### ISSUE THREAD

**Issue by pcj** [bazelbuild/bazel#2155]
It's annoying that install.sh moves `~/.bazelrc` to `~/.bazelrc.bak` as a side-effect.  Is this really necessary?

**Comment by damienmg** [comment]
It's not necessary but that's to avoid overwriting it. We should do something more intelligent. PR are welcomed.

**Comment by meisterT** [comment]
This was fixed by 720561113bfa702acfc2ca24ce3cc3fd7ee9c115
