### ISSUE TITLE
Cherry-pick 5b4ba3e9b5a3d2532e96812ed7f1fd87c263a467 for 7.1.0

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#21554]
### Commit IDs

5b4ba3e9b5a3d2532e96812ed7f1fd87c263a467

### Category

team-ExternalDeps

### Reviewers

@Wyverald

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/21555: https://github.com/bazelbuild/bazel/commit/5b4ba3e9b5a3d2532e96812ed7f1fd87c263a467.
