### ISSUE TITLE
Downstream CI is failing with hanging jobs at Bazel@HEAD


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#21566]
Downstream CI pipelines
==================
1. https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3697
2. https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3695

 CC Greenteam @meteorcloudy

**Comment by meteorcloudy** [comment]
Hanging jobs are:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3697#018e0c5c-9fcd-462e-a55d-9f9256bf25d0
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3697#018e0c5c-9fdb-4a6a-890c-321b4078aff9
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3695#018e0cc5-98bc-40c2-a00b-9754b63ee32b

with
```
(11:26:17) Analyzing: 51 targets (64 packages loaded, 2910 targets configured)
[1 / 1] checking cached actions
```

might be related to https://github.com/bazelbuild/bazel/issues/21134

**Comment by meteorcloudy** [comment]
jstack log from the latest hang: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3701#018e16aa-d0d6-461e-a106-b369133a711f
[jstack.log](https://github.com/bazelbuild/bazel/files/14522853/result.log)
