### ISSUE TITLE
Windows: implement ijar for MSVC

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2157]
Goal:
```
bazel build //third_party/ijar/...:all --cpu=x64_windows_msvc
```
should succeed and have a working Windows implementation.

This is a prerequisite for https://github.com/bazelbuild/bazel/issues/2107.

**Comment by ulfjack** [comment]
Technically, you could disable ijar on Windows to achieve #2107 instead of blocking on this.

**Comment by laszlocsomor** [comment]
hmm :) well i already have the CLs lined up for it so meh
but thanks!
any ideas for porting or disabling build-runfiles / process-wrapper?

**Comment by ulfjack** [comment]
I think that we have a Java implementation of build-runfiles. process-wrapper is more complicated, but you could start with a minimal implementation that doesn't do the more advanced stuff we're doing in the Posix version.

**Comment by dslomov** [comment]
neither build-runfiles nor process-wrapper are used on Windows.

**Comment by laszlocsomor** [comment]
@dslomov , are you sure about process-wrapper? It is certainly a dependency of Bazel, do you think we can simply remove it?

**Comment by dslomov** [comment]
@laszlocsomor  oh sorry there is #1852: we still use it for `bazel run` but actually we shouldn't.

**Comment by laszlocsomor** [comment]
We can now build ijar but many functions say "isn't implemented for windows".
