### ISSUE TITLE
Mobile install command doesn't launch application with flag --start_app

### ISSUE THREAD

**Issue by dvpermyakov** [bazelbuild/bazel#21574]
### Description of the bug:

After successful installation of android apk next time bazel skips install action and show logs from previous action

### Which category does this issue belong to?

Android

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

bazel mobile-install {your android binary target}  --start_app

### Which operating system are you running Bazel on?

MacOS 13.5

### What is the output of `bazel info release`?

release 7.0.2

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
https://github.com/bazelbuild/bazel.git
ee89a53
```

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Yes, https://github.com/bazelbuild/bazel/commit/2b104c8fd5e54e31abbe1c84b04ba64530cd74ed

### Have you found anything relevant by searching the web?

No

**Comment by fmeum** [comment]
Cc @tjgq based on the regressing commit

**Comment by ahumesky** [comment]
mobile-install has been migrated to Starlark in https://github.com/bazelbuild/rules_android, so if this is still an issue with the Starlark version, please file a new issue there.
