### ISSUE TITLE
[7.1.0] Subrule respects the visibility of the parent rule itself, not the file used to refer to the rule

### ISSUE THREAD

**Issue by rockbruno** [bazelbuild/bazel#21572]
### Description of the bug:

I was eager to try out `subrules`, but I'm facing a problem where the subrule is respecting the visibility of the parent rule _itself_, when what I was expecting it to do was to respect the visibility of _the thing I'm using to refer to the rule_, similarly to how it works for load statements.

[See this for an example](https://github.com/bazelbuild/rules_apple/blob/f8fa4d9a32556ece0f7eee0ebdf997ca25bdc855/apple/apple.bzl#L51-L62). The actual rules these re-assignments are pointing to are private, but the `apple.bzl` file itself is public. This is enough for calling these rules via load commands, but when using subrules you get an error that the rule is private.

This seems to be what's mentioned as a known limitation/future improvement [in the subrules proposal](https://docs.google.com/document/d/1RbNC88QieKvBEwir7iV5zZU08AaMlOzxhVkPnmKDedQ) from last year. If so, I was wondering if there is someone actively working on those improvements, or if it's something that would be reasonable for a first-timer like me to contribute to if we agree that the example above should work.

### Which category does this issue belong to?

Rules API

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try to build a subrule whose's parent is a private rule that was "re-assigned" to be public, [such as in this example.](https://github.com/bazelbuild/rules_apple/blob/f8fa4d9a32556ece0f7eee0ebdf997ca25bdc855/apple/apple.bzl#L51-L62)

### Which operating system are you running Bazel on?

macOS 14.3.1 (23D60)

### What is the output of `bazel info release`?

7.1.0rc1

**Comment by rockbruno** [comment]
Looking at older issues, it's the same as https://github.com/bazelbuild/bazel/issues/19507#issuecomment-1933572248

**Comment by meteorcloudy** [comment]
Sounds like this is not a regression in 7.1.0rc1, right?

**Comment by rockbruno** [comment]
Probably not, but can't say for sure because subrules were already not working pre-7.1.0 due to a separate bug (that was fixed in 7.1.0).

**Comment by rockbruno** [comment]
This issue is invalid. The error message I was getting (cannot use private API) was misleading me into thinking the problem was related to visibility, when the issue was actually that I wasn't enabling the subrules feature correctly.
