### ISSUE TITLE
December release - ETA Dec 7

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2158]
Assigning to @iirina who's the current sheriff.

November release thread, to serve as an example: https://github.com/bazelbuild/bazel/issues/2027

**Comment by laszlocsomor** [comment]
Handover: we have 0.4.2rc1 out since yesterday, so if all goes well (no cherrypicks necessary so no new RC needs to be created) we can release it on Dec 7 evening.

**Comment by petemounce** [comment]
Hi @laszlocsomor & @iirina - these tickets are great to catch up with release activity, but they're quite hard to find or know about generally via github. Please could they be added to the milestone(s) which they will be releasing, so they're more discoverable?

**Comment by laszlocsomor** [comment]
@petemounce : Making these issues more discoverable is a good idea. Since we only have milestones for minor versions and not patch versions (as in [`MAJOR.MINOR.PATCH`](https://bazel.build/versions/master/docs/support.html#release-versioning)), I suggest adding a "Release" label to them. How does that sound?

**Comment by damienmg** [comment]
There is a release blocker label that should be added to those bug :)

**Comment by petemounce** [comment]
@laszlocsomor that would work if it were linked prominently from the website and docs? If people land on github, though, then less discoverable than milestones which are part of the ui as a first class thing.

**Comment by aehlig** [comment]
Can we please cherry-pick 7b835d97219e40ee92b109fbecd2dc3b37db024c
into the release? Currently, our release artefacts are build in
an environment with a changed WORKSPACE file; this results in a
distribution archive that is not usable (issue #2169).

Thanks,
Klaus

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by laszlocsomor** [comment]
@aehlig : yes.
@iirina : I can do the cherrypick Klaus requested and create the new RC because I started the 0.4.2 release.

@petemounce : Good point.

**Comment by laszlocsomor** [comment]
Created RC2:
```
$ scripts/release/release.sh create 0.4.2 6331a94bf74b936c7cbb2868267936f0981e10d9 7b835d97219e40ee92b109fbecd2dc3b37db024c
...
Created 0.4.2RC2 on branch release-0.4.2.

$ scripts/release/release.sh push
```

See https://github.com/bazelbuild/bazel/issues/2027#issuecomment-263866909 for RC1 creation.

**Comment by laszlocsomor** [comment]
@petemounce : Created https://github.com/bazelbuild/bazel/issues/2170

**Comment by laszlocsomor** [comment]
We have a release-blocking bug in the internal version; may be affecting Bazel too; we may need another cherry pick once that is fixed.

**Comment by petemounce** [comment]
Published https://chocolatey.org/packages/bazel/0.4.2-rc2 - it's in their automated validation queue.

**Comment by laszlocsomor** [comment]
The internal release-blocking bugs are either unrelated to Bazel or their culprit was submitted after the Bazel RC was cut, so I think we're good.

**Comment by laszlocsomor** [comment]
I pushed the release, but due to Jenkins and thus the "bazel release" job having issues, it's not yet announced. It also appears weird on our "Releases" page, though maybe I just need to wait until all binaries are uploaded.

**Comment by laszlocsomor** [comment]
No, the more likely culprit is https://github.com/bazelbuild/bazel/issues/2200. The release wasn't properly pushed, so for now it's just a tag.

**Comment by laszlocsomor** [comment]
Aw yiss! Yes, that was the culprit, and after https://github.com/bazelbuild/bazel/issues/2200#issuecomment-265536121, the windows slave finally came to life, and i could rerun the bazel job for 0.4.2, and it succeeded, and it's green, and i'm so happy now.

**Comment by meteorcloudy** [comment]
```
Uploading bazel-0.4.2-jdk7-dist.zip...
Error: Github returned an error:
 Code: 502 Bad Gateway. 
 Body: {"message":"Error uploading asset","request_id":"92943694:14B8B:160549FE:58485AFD"}
```
Looks like bazel-0.4.2-jdk7-dist.zip is not uploaded, we can do it manually.

**Comment by meteorcloudy** [comment]
But we have the release!!! \o/

**Comment by laszlocsomor** [comment]
Wow, thanks for checking that @meteorcloudy ! I'll upload the file.

**Comment by laszlocsomor** [comment]
The artifact was built by this run: http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.7,PLATFORM_NAME=linux-x86_64/1080/

**Comment by laszlocsomor** [comment]
Done. I verified that the SHA256 of the zip matches that in the .sha256 file.

**Comment by petemounce** [comment]
I published the chocolatey package - https://chocolatey.org/packages/bazel/0.4.2 - and it's waiting automated validation and human review, as usual.

**Comment by laszlocsomor** [comment]
Awesome, thank you @petemounce!
