### ISSUE TITLE
[7.1.0] Move compile StarlarkMethod back to CcModuleAPI

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#21589]
### Commit IDs

a4febaa8f947b750c137b51cbaa151fa1a1d630f

### Category

team-Rules-CPP

### Reviewers

@comius

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/21590: https://github.com/bazelbuild/bazel/commit/a4febaa8f947b750c137b51cbaa151fa1a1d630f.

**Comment by iancha1992** [comment]
cc: @fmeum

**Comment by keertk** [comment]
https://github.com/bazelbuild/bazel/pull/21605
