### ISSUE TITLE
[7.1.0] Expose the ApkInfo provider constructor to Starlark.

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#21586]
### Commit IDs

067b0ea5e3893fbd580aa8a76d6a78ad242e3dba

### Category

team-Android

### Reviewers

@ahumesky

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/21588: https://github.com/bazelbuild/bazel/commit/067b0ea5e3893fbd580aa8a76d6a78ad242e3dba.
