### ISSUE TITLE
f699b502ef6a57dc68570486191ad1c318e8fd1b breaks bazel-tests

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#2159]
f699b502ef6a57dc68570486191ad1c318e8fd1b broke `src/test/shell/bazel/android/android_integration_test#test_sdk_library_deps` (see [here](http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=ubuntu_15.10-x86_64/365/testReport/junit/%28root%29/%28empty%29/test_sdk_library_deps/))

**Comment by aj-michael** [comment]
I will roll forward this change with the appropriate test fixes early next week. Sorry for the breakage.
