### ISSUE TITLE
pdb_file not added to cc_shared_library output group

### ISSUE THREAD

**Issue by peakschris** [bazelbuild/bazel#21602]
### Description of the bug:

When generate_pdb_file feature is enabled, the pdb_file is built. However, it is not added to the output group of cc_shared_library. The cc_binary rule seems to be ok.

The code in cc_binary that is missing from cc_shared library is:

https://github.com/bazelbuild/bazel/blob/d738910e83427d394526cbdfc8ac665027dd9196/src/main/starlark/builtins_bzl/common/cc/cc_binary.bzl#L828-L832

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Trivial issue, but I can provide a git repo to reproduce this if it helps

### Which operating system are you running Bazel on?

Windows

### What is the output of `bazel info release`?

release 7.0.2

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

No

### Any other information, logs, or outputs that you want to share?

The code in cc_binary that is missing from cc_shared library is:

https://github.com/bazelbuild/bazel/blob/d738910e83427d394526cbdfc8ac665027dd9196/src/main/starlark/builtins_bzl/common/cc/cc_binary.bzl#L828-L832

**Comment by fmeum** [comment]
Would you be interested in submitting a PR? You could add test coverage here: https://github.com/bazelbuild/bazel/blob/bb3414cc0bb8e8d1536c38dc04df393530aa401c/src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/starlark_tests.bzl#L405

**Comment by peakschris** [comment]
fmeum, I would love to be able to contribute. Sadly my employer will not sign the google agreement, so I cannot contribute to this repo.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.2.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.2.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.2.0rc1. Thanks!
