### ISSUE TITLE
Cache for repository_rules???

### ISSUE THREAD

**Issue by trivigy** [bazelbuild/bazel#2161]
I am using an external build with a custom rule to package our python application into a pex build. The custom rule actually runs the Pex build using ctx.action(). Given that Pex actually also downloads additional dependencies and because execution of ctx.action() happens in sandbox I am not able to cache Pex downloading and the build is forced to redownload the dependencies every time again and again. Any way to use some sort of tmp folder that is shared with the host machine during sandboxed build?

**Comment by trivigy** [comment]
Would --sandbox_tmpfs_path qualify for my requirement?

**Comment by trivigy** [comment]
So it seems that this parameter does mount the directory to be writable but unfortunately whatever I end up writing in that directory during the action does not actually get exported out of ctx.action()

**Comment by damienmg** [comment]
Repository rules have a --experimental_repository_cache flag to cache shasumed downloaded artifact, see https://cr.bazel.build/6933/

**Comment by pcj** [comment]
On 0.4.1 `--experimental_repository_cache` is a no-op (IIRC something about breaking the jdk7 build), any idea when this change will make it back in?

**Comment by damienmg** [comment]
Huh? Giving the potato to @kchodorow who followed the roll out of that flag to comment.

**Comment by pcj** [comment]
@kchodorow Did I get that wrong?  Maybe that was 0.4.0 and not 0.4.1 (because now bazel seems to be using a repository cache again, which led me to #2185).

**Comment by trivigy** [comment]
@damienmg Thanks for introducing this flag to me but this is not what I am talking about. The issue I am running into is that I download pip,pex,etc. during analysis(workspace) stage. Those are fine. Then when I am actually building during a regular rule I use pex (that was downloaded prior.) However, pex has it's own solution for cache. (During pex file building, pex downloads dependencies internally based on setup.py file's configurations and packages them together with the rest of the code.) Because of this cache I have to point pex using environment variable PEX_ROOT to .pex (it is by default points to $HOME/.pex) which then downloads pex's cache into the sandbox. all that stuff disappears after the build is done. This forces that for each build pex has to re-download dependencies. One solution is to use local=1 but that means I loose the sandboxing abstraction.

**Comment by ulfjack** [comment]
You can make local paths available in the sandbox with --sandbox_add_path.

**Comment by trivigy** [comment]
@ulfjack Thanks. I'll try this one out right away.

**Comment by trivigy** [comment]
@ulfjack This flag doesn't seem to exist in the newer versions of bazel. Any alternatives?

**Comment by trivigy** [comment]
Would greatly appreciate it if someone has a workaround for me. I am running pex builds right now and they are taking forever because pex keeps re-downloading everything on every build. Thanks.

**Comment by kchodorow** [comment]
@pcj,  `--experimental_repository_cache` has never been a no-op.  

@trivigy, ctx.action happens during a different phase than the repository cache handles.  If you want Bazel to cache downloaded things, implement a [repository rule](https://bazel.build/versions/master/docs/skylark/repository_rules.html).  Do something like `ctx.execute(["pex", <your thing>])` and then depend on the target your generate.  Then Bazel will cache it without you even having to specify anything.  I can help you with writing the repository rule if you have any questions.

It's a very bad idea to download things in a "normal" skylark rule (using `ctx.action`).

**Comment by trivigy** [comment]
@kchodorow Thanks. Exactly what I did. Ended up doing `pip download <stuff>` and then pex depends on the downloads folder. This does solve my problem but leaves the WORKSPACE file to be enormous. This is something I can certainly live with.

**Comment by abhillman** [comment]
> @pcj, `--experimental_repository_cache` has never been a no-op.
> 
> @trivigy, ctx.action happens during a different phase than the repository cache handles. If you want Bazel to cache downloaded things, implement a [repository rule](https://bazel.build/versions/master/docs/skylark/repository_rules.html). Do something like `ctx.execute(["pex", <your thing>])` and then depend on the target your generate. Then Bazel will cache it without you even having to specify anything. I can help you with writing the repository rule if you have any questions.
> 
> It's a very bad idea to download things in a "normal" skylark rule (using `ctx.action`).

What is the suggested alternative? i.e. when writing a repository rule to fetch something from GCS or whatever.
