### ISSUE TITLE
[Mirror] rules_oci v1.7.4 (https://github.com/bazel-contrib/rules_oci/releases/tag/v1.7.4)

### ISSUE THREAD

**Issue by imankhadiv** [bazelbuild/bazel#21627]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazel-contrib/rules_oci/releases/tag/v1.7.4

**Comment by sgowroji** [comment]
Please find the mirror url 

https://mirror.bazel.build/github.com/bazel-contrib/rules_oci/releases/download/v1.7.4/rules_oci-v1.7.4.tar.gz
