### ISSUE TITLE
Implement Bazel Remote Output Service

### ISSUE THREAD

**Issue by coeuvre** [bazelbuild/bazel#21630]
### Description of the feature request:

The protocol is added with #21140. This is a tracking bug for implementing the client.

Working towards #20933.

**Comment by brentleyjones** [comment]
@coeuvre does this mean that Remote Output Service will be available in 7.2.0?

**Comment by coeuvre** [comment]
Yes. See https://github.com/bazelbuild/bazel/discussions/20933#discussioncomment-9443772.
