### ISSUE TITLE
cc provider digestable from Skylark rule implementation

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#2163]
### Description of the problem / feature request / question:

I have a rule implementation, which generates a C++ header. This header then needs to be includeable by its name alone. Naively looking at `CcSkylarkApiProvider` I would do the following:

    return struct(
        files = set([gen_file]),
        cc = struct(
            transitive_headers = set([gen_file]),
            include_directories = set([gen_dir]),
        ),
    )

Which leads to the error message:

    in deps attribute of cc_test rule //:flattests: cpp_schema rule '//:tests/monster_test_generated' is misplaced here (expected cc_inc_library, cc_library, objc_library or experimental_objc_library).

So it seems like there is no way of defining and digesting `cc` Provider in Skylark.

### Environment info
* Operating System: Ubuntu 16.04.1

* Bazel version (output of `bazel info release`): 0.4.1

### Anything else, information or logs or outputs that would be helpful?
Nope.

**Comment by mhlopko** [comment]
Hi Andreas,

what you describe is what we internally call "sandwich" ([design doc](https://bazel.build/designs/2016/08/04/extensibility-for-native-rules.html)). We have some rudimentary support for taking CcLinkParams from one native rule and passing it to another native rule, but not much more.

The good news is that we are going to work on this very soon, hopefully in January. The prerequisite cleanup and preparation work is already happening.

**Comment by mhlopko** [comment]
Just an update, still cleaning stuff up, actual work on C++ sandwich hasn't yet started.

**Comment by steeve** [comment]
@mhlopko hey, did the work start ? :)

**Comment by mhlopko** [comment]
Yes :) @ventrescadeatun is already investigating how the api should look like and doing the required cleanups. Design doc will be shared in Q1.

**Comment by steeve** [comment]
Awesome! Thank you for the quick response

**Comment by RNabel** [comment]
@mhlopko Has there been progress on this issue, and/or did the design doc get published yet?

**Comment by oquenchil** [comment]
I have a prototype and I am planning to send it for review to the Skylark people sometime in the next few weeks. I will update this issue: https://github.com/bazelbuild/bazel/issues/4570

**Comment by hlopko** [comment]
I'm closing this one, both CcToolchainInfo and CcInfo are fully released and exposed to Starlark.
