### ISSUE TITLE
[7.2.0] Bazel doesn't respect XDG_CACHE_HOME

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21635]
Forked from #16937

**Comment by bazel-io** [comment]
The branch, release-7.2.0, may not exist. Please retry the cherry-pick after the branch is created.

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by tetromino** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21817
