### ISSUE TITLE
[Mirror] aspect-build/bazel-lib https://github.com/aspect-build/bazel-lib/releases/tag/v1.39.0

### ISSUE THREAD

**Issue by imankhadiv** [bazelbuild/bazel#21634]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/aspect-build/bazel-lib/releases/tag/v1.39.0

Thank you team!

**Comment by keertk** [comment]
Here you go - https://mirror.bazel.build/github.com/aspect-build/bazel-lib/releases/tag/v1.39.0/bazel-lib-v1.39.0.tar.gz

**Comment by imankhadiv** [comment]
Hi Keertk,

Thanks for adding this. But, the above URL is not what we are looking for. This is the one that is missing

 https://mirror-bazel-build/github.com/aspect-build/bazel-lib/releases/download/v1.39.0/bazel-lib-v1.39.0.tar.gz] 
 
 instead of `/releases/tag/***` , it should be `/releases/download/v1.39.0/bazel-lib-v1.39.0.tar.gz `

**Comment by keertk** [comment]
Gotcha. It should work now - can you confirm?

**Comment by imankhadiv** [comment]
Yes, it works! Thanks Keertk!
