### ISSUE TITLE
Setting a `--disk_cache` means partial outputs don't get materialized

### ISSUE THREAD

**Issue by blorente** [bazelbuild/bazel#21645]
### Description of the bug:

When setting a `--disk_cache` to an existing directory, Bazel will not materialize partial outputs (in this case, Go source generated from Proto) into `bazel-out`.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Minimal repro is in: https://github.com/blorente/proto-repro
Instructions:
- Clone the repo
- Run `./repro.sh`
- Observe the output (I got [this](https://github.com/blorente/proto-repro/blob/main/output.txt)).

Roughly, the script does:
- Build some `go_proto_library` with the specified flags.
- Use `bazel aquery` to determine where the outputs would be.
- Assert that both the containing directory and the generated file exist.

Note that the containing directory existed in all cases.
I've tried to write the script so the only flag that changed was the disk cache, without regards for the global config. Please let me know if I have missed something.

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

This reproduces in Bazel 7.0.0 onwards, but not in Bazel 6.

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

A back-of-the-envelope bisect leads me to [this commit](https://github.com/bazelbuild/bazel/commit/8715e9ae6f5c2fd42607018b3adaad14bf601a1c), but I'm not sure it has anything to do with anything.

**Comment by tjgq** [comment]
Starting with 7.0.0, the default behavior when getting a remote or disk cache hit is to only "download" (i.e., copy to the output tree) the top-level outputs.

The top-level outputs are the ones reported by `bazel cquery --output=files //proto:proto_go_proto`. The `bazel aquery 'outputs(..., //proto:proto_go_proto)'` query answers a different question, namely "outputs of every build action declared by this target".

You can override which files are downloaded by setting `--remote_download_all` (download everything) or `--remote_download_regex` (download selectively by path).

**Comment by blorente** [comment]
Ahh, gotcha. I knew the default was different for the remote caches, but I didn't know it was so for the local disk caches.
Good to know, thanks!
