### ISSUE TITLE
Zipper fails under Windows due to incorrect parameters

### ISSUE THREAD

**Issue by zmeggyesi** [bazelbuild/bazel#2164]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

When building for AppEngine using the [AppEngine rules](https://github.com/bazelbuild/rules_appengine), the build under Windows fails on the `appengine_war` rule, apparently due a misconfigured Zipper. Attached is the [command.log](https://github.com/bazelbuild/bazel/files/626582/command.txt) for the run.

### If possible, provide a minimal example to reproduce the problem:
Theoretically, any AppEngine-targeted project under Windows should reproduce the problem. Using the `java_library` target works, but `java_war` and `appengine_war` fail with the same error output.

### Environment info
* Operating System: Windows 10 v1607 build 14393.447; java version "1.8.0_112"

* Bazel version (output of `bazel info release`): release 0.4.1

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`): N/A

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

I've raised the issue in the AppEngine ruleset GitHub repo, where others arrived at the conclusion that it's specific to Windows, leading me to believe that it's a core Bazel issue, not just one with the ruleset.

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by meteorcloudy** [comment]
`(root=$(pwd);cd bazel-out/local-fastbuild/bin/src/main/java/gae.war.build_output &&${root}/external/bazel_tools/tools/zip/zipper/zipper.exe Cc ${root}/bazel-out/local-fastbuild/bin/src/main/java/gae.war $(find .)): java.io.IOException: CreateProcess(): The parameter is incorrect.`

Based on the log, it looks more like an error happened when creating a process on Windows.

**Comment by laszlocsomor** [comment]
I just tried this with Bazel 0.5.3 rc2, cloning https://github.com/bazelbuild/rules_appengine/commit/14d860985c2a764fdb6a6072d5450d8360c4ce5b:
```
C:\work\rules_appengine>c:\work\bazel-0.5.3rc2\bazel.exe --output_user_root=c:\tmp1 build //examples --verbose_failures
INFO: Found 1 target...
ERROR: C:/work/rules_appengine/examples/BUILD:3:1: error executing shell command: 'set -e;rm -rf bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output
mkdir -p bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output
mkdir -p bazel-out/msvc_x64-fastbuild/...' failed (Exit 127): bash.exe failed: error executing command
(...)
  C:/tools/msys64/usr/bin/bash.exe -c set -e;rm -rf bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output
mkdir -p bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output
mkdir -p bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/WEB-INF/lib
mkdir -p $(dirname bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/WEB-INF/lib)
test -L bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/WEB-INF/lib || ln -s $(pwd)/bazel-out/msvc_x64-fastbuild/bin/examples/src/src_deploy.jar bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/WEB-INF/lib
mkdir -p $(dirname bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/WEB-INF/lib)
test -L bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/WEB-INF/lib || ln -s $(pwd)/external/com_google_appengine_java/lib/agent/appengine-agent.jar bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/WEB-INF/lib
mkdir -p $(dirname bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/WEB-INF/lib)
test -L bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/WEB-INF/lib || ln -s $(pwd)/external/com_google_appengine_java/lib/appengine-tools-api.jar bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/WEB-INF/lib
mkdir -p $(dirname bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/WEB-INF/lib)
test -L bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/WEB-INF/lib || ln -s $(pwd)/external/com_google_appengine_java/lib/impl/appengine-api.jar bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/WEB-INF/lib
mkdir -p $(dirname bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/BUILD)
test -L bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/BUILD || ln -s $(pwd)/examples/webapp/BUILD bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/BUILD
mkdir -p $(dirname bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/WEB-INF/appengine-web.xml)
test -L bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/WEB-INF/appengine-web.xml || ln -s $(pwd)/examples/webapp/WEB-INF/appengine-web.xml bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/WEB-INF/appengine-web.xml
mkdir -p $(dirname bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/WEB-INF/web.xml)
test -L bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/WEB-INF/web.xml || ln -s $(pwd)/examples/webapp/WEB-INF/web.xml bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output/WEB-INF/web.xml
(root=$(pwd);cd bazel-out/msvc_x64-fastbuild/bin/examples/examples.war.build_output &&${root}/external/bazel_tools/tools/zip/zipper/zipper.exe Cc ${root}/bazel-out/msvc_x64-fastbuild/bin/examples/examples.war $(find .)).
File . does not seem to exist.Target //examples:examples failed to build
INFO: Elapsed time: 1.897s, Critical Path: 0.91s
```

**Comment by laszlocsomor** [comment]
The problem lies is the way `appengine_war_base` is implemented: it's creating Skylark actions that are shell commands. Skylark actions run as native processes, so on Windows they attempt to run Bash commands as native Windows processes, which fails. The workaround is to move the logic to shell scripts and wrap those in `sh_binary` rules, and use those as the action's executable -- then Bazel knows that it must use Bash to run those commands.

**Comment by dslomov** [comment]
Well, this line https://github.com/bazelbuild/rules_appengine/blob/master/appengine/appengine.bzl#L156 runs the command with bash. However, it appears that `$(find .)` in that command finds nothing. My guess is that it has to do with absence of runfiles on Windows. Closing this since there is no Bazel issue.
