### ISSUE TITLE
Superfluous dependency on Visual Studio?

### ISSUE THREAD

**Issue by zmeggyesi** [bazelbuild/bazel#2165]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
Bazel requires a Visual Studio even when building a pure-Java project.  
The exact error output:  
```
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/tools/msys64/var/tmp/Bazel/qNrn0$Ug/external/bazel_tools/tools/cpp/cc_configure.bzl", line 481
                _find_env_vars(repository_ctx, vs_path)
        File "C:/tools/msys64/var/tmp/Bazel/qNrn0$Ug/external/bazel_tools/tools/cpp/cc_configure.bzl", line 423, in _find_env_vars
                _execute(repository_ctx, ["wrapper/get_env...."])
        File "C:/tools/msys64/var/tmp/Bazel/qNrn0$Ug/external/bazel_tools/tools/cpp/cc_configure.bzl", line 93, in _execute
                auto_configure_fail(result.stderr)
        File "C:/tools/msys64/var/tmp/Bazel/qNrn0$Ug/external/bazel_tools/tools/cpp/cc_configure.bzl", line 50, in auto_configure_fail
                fail("
%sAuto-Configuration Error:%s ...))

Auto-Configuration Error: The system cannot find the path specified.
```

At first, I thought the issue was the lack of a `BAZEL_VS` variable in the shell, so I suppressed it by setting an empty string. Since that didn't help, I first tried getting a GCC using MSYS `pacman`, to no avail. Finally, I installed MSVS Community Edition, and provided the path, which fixed the issue. 

However, the feeling still remains that a pure-Java project should not require me to install VS to run the `java_binary` or `java_library` rules.

### If possible, provide a minimal example to reproduce the problem:
The Java tutorial, or any Java project, without some version of Visual Studio installed will present the problem. The `BAZEL_VS` variable may need to be unset from the shell environment.

### Environment info
* Operating System: Windows 10 v1607 build 14393.447; java version "1.8.0_112"

* Bazel version (output of `bazel info release`): release 0.4.1

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`): N/A

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
I did raise the [question](https://groups.google.com/forum/#!topic/bazel-discuss/esKQVJYsKUE) in the Bazel Discussions group, and one user offered that the `java_binary` rule accidentally triggers the discovery of the C toolchain as well due to insufficient granularity.

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by mhlopko** [comment]
Hi Zalán,

well, that's complicated subject. Let me start with that we would like not to be dependent on C++ toolchain, or in general, on any "not needed" configuration fragment. The general solution is very complex to implement correctly and so it scales well under the requirements imposed on bazel. We are working on it, for quite some time already.

To make this less painful, we added local_config_cc remote repo and cc_configure.bzl which creates it. Let me ping @meteorcloudy if we can do anything better here...

**Comment by dslomov** [comment]
As a workaround, can we make it a warning instead of an error? (the tradeoff is that it might cause mysterious errors later) wdyt @meteorcloudy ?

**Comment by dslomov** [comment]
Leaving this in 0.5 milestone mostly for considering warning -> error change

**Comment by meteorcloudy** [comment]
@dslomov Do you think if it's better to use an environment variable to enable this change? like NO_CC_CONFIGURE_ERROR=1 ?

**Comment by laszlocsomor** [comment]
Closing this bug, as Bazel no longer requires VC++ (unless you build cc_* rules).
