### ISSUE TITLE
[bazel.build] Problem with /query/language

### ISSUE THREAD

**Issue by honnix** [bazelbuild/bazel#21672]
### Page link:

https://bazel.build/query/language

### Problem description (include actual vs expected text, if applicable):

It seems the following description does not match the observation:

> When this flag is deps, Bazel prints results in some topological order—that is, dependencies first. However, nodes that are unordered by the dependency order (because there is no path from either one to the other) may be printed in any order.

For a DAG like a -> b -> c, `--order_output=deps` outputs `a` first and then `b` and then `c`, which is a correct topological order. This code seems to confirm this observation as well: https://github.com/bazelbuild/bazel/blob/a4a73c526edcdbf675d34a25b1c397744d700e05/src/main/java/com/google/devtools/build/lib/graph/Digraph.java#L494-L508

### Where do you see this issue? (include link to specific section of the page, if applicable)

https://bazel.build/query/language#results-ordering

**Comment by keertk** [comment]
Hi @honnix thanks for the report. Would you be willing to submit a PR for this?

**Comment by honnix** [comment]
@keertk Sure I can do that. Just wanted to confirm my understand was correct.

**Comment by honnix** [comment]
Trying that in #21678. Please let me know whether you think the description should be more expanded. Thank you. @keertk
