### ISSUE TITLE
 Failed to load Skylark extension '//tensorflow/tensorflow:workspace.bzl'.

### ISSUE THREAD

**Issue by baditaflorin** [bazelbuild/bazel#2167]
### Description of the problem / feature request / question:

Trying to install this https://github.com/farazfazli/AI_Reader

`bazel test syntaxnet/...`
.
```
ERROR: Failed to load Skylark extension '//tensorflow/tensorflow:workspace.bzl'.
It usually happens when the repository is not defined prior to being used.
Maybe repository '' was defined later in your WORKSPACE file?
ERROR: cycles detected during target parsing.
INFO: Elapsed time: 0.753s
ERROR: Couldn't start the build. Unable to run tests.
```

### Environment info
* Operating System:

Ubuntu 16.04

* Bazel version (output of `bazel info release`):

0.4

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by iirina** [comment]
Hi,

I am not sure if this is an Bazel issue. Can you provide more information about the steps that you've taken to build the project?

Cheers,
Irina

**Comment by damienmg** [comment]
This is a syntaxnet issue. Please file an issue to the https://github.com/farazfazli/AI_Reader.
