### ISSUE TITLE
[7.2.0] Bazel@HEAD crashes if XDG_CACHE_HOME starts with `~/`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21685]
Forked from #21660

**Comment by bazel-io** [comment]
The branch, release-7.2.0, may not exist. Please retry the cherry-pick after the branch is created.

**Comment by bazel-io** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21796

**Comment by tetromino** [comment]
> Cherry-picked in #21796

Nope, #21796 is a separate cherry pick
