### ISSUE TITLE
Increased memory usage with Bazel 7 on macOS

### ISSUE THREAD

**Issue by Vertexwahn** [bazelbuild/bazel#21697]
### Description of the bug:

Bazel 7 on macOS is very RAM hungry. Had previously used Bazel 6.5. With Bazel 7 I get after a short time after executing bazel build a "Your computer is low on memory" popup and Bazel hangs in endless compling activity. For me it seems that a build in Bazel 7 (tested with Version 7.0.2 and 7.1.0) needs much more RAM than the same (similar) build using Bazel 6.4/6.5.

A similar issue has been reported here: https://bazelbuild.slack.com/archives/CA31HN1T3/p1709849903738179

**Comment by joeleba** [comment]
Might be relevant: https://github.com/bazelbuild/bazel/issues/21540

**Comment by joeleba** [comment]
Could you please take a heap dump when this popup occurs?

```
$ jmap -histo:live <bazel_server_pid> > /tmp/histo.txt
```

**Comment by meisterT** [comment]
@Vertexwahn I am closing this for now, when you see it again, feel free to re-open.
