### ISSUE TITLE
dist package does not compile

### ISSUE THREAD

**Issue by freswa** [bazelbuild/bazel#2169]
### Description of the problem / feature request / question:

Build fails with an error, that androidndk is not found. If I remove the regarding (last two) sections in WORKSPACE, Bazel builds fine. Installing android-ndk does not solve this issue. Since the two dummy targets at line 12 to 20 should allow building bazel without android-sdk and android-ndk this seems to be a bug.

### If possible, provide a minimal example to reproduce the problem:
1. download bazel-0.4.1-dist.zip and bazel-0.4.1-dist.zip.sig
2. check signature with gpg
3. unzip archive
4. ./compile.sh
5. get an error

### Environment info
* Operating System:
Arch Linux 4.8.11.201611271225-2-grsec

* Bazel version (output of `bazel info release`):
0.4.1

### Anything else, information or logs or outputs that would be helpful?
```
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch.......
🍃  Building Bazel with Bazel.
.WARNING: /tmp/bazel_hEMi7Wn5/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel_hEMi7Wn5/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.
ERROR: in target '//external:android/crosstool': no such package '@androidndk//': /home/ci/android/android-ndk-r10e (No such file or directory).
INFO: Elapsed time: 1,689s

ERROR: Could not build Bazel
```

**Comment by aehlig** [comment]
On Fri, Dec 02, 2016 at 02:48:03AM -0800, frederik wrote:
> ### Description of the problem / feature request / question:
> 
> Build fails with an error, that androidndk is not found. If I remove the regarding (last two) sections in WORKSPACE, Bazel builds fine. Installing android-ndk does not solve this issue. Since the two dummy targets at line 12 to 20 should allow building bazel without android-sdk and android-ndk this seems to be a bug.

This is indeed a bug. Thanks for reporting it and describing the work around.

We believe that https://bazel-review.googlesource.com/#/c/7592/ will fix it; this
change will be cherry-picked to the second rc for 0.4.2. Sorry for the inconvenience.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by aehlig** [comment]
I just verified that dist package for 0.4.2r2 (avaiable
from https://storage.googleapis.com/bazel/0.4.2/rc2/index.html)
works cleanly; so the cherry-picked patch fixed the problem
(and hence, also future releases should be clean).

Therefore, my suggestion is to ignore 0.4.1 and move on with
(0.4.2rc2 for the moment and then) 0.4.2.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by aehlig** [comment]
Closing, as 0.4.2rc2 provides a buildable dist package. The change is also upstream, so future dist packages should work as well.

**Comment by freswa** [comment]
Works, thx

**Comment by Zulfidin** [comment]
I have similar Error:

First, it showed WARNING:

🍃 Building Bazel from scratch.......
🍃 Building Bazel with Bazel.
.WARNING: /tmp/bazel_aa6GUqlR/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel_aa6GUqlR/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.
WARNING: /home/nvidia/bazel-0.5.2-dist/tools/build_defs/docker/docker.bzl:19:1: The docker_{build,bundle} rules bundled with Bazel are deprecated in favor of:
https://github.com/bazelbuild/rules_docker. Please change BUILD loads to reference: @io_bazel_rules_docker//docker:docker.bzl and add the following to your WORKSPACE:
git_repository(
name = "io_bazel_rules_docker",
remote = "https://github.com/bazelbuild/rules_docker.git",
commit = "...",
)
load("@io_bazel_rules_docker//docker:docker.bzl", "docker_repositories")
docker_repositories().
.
.
.


Then, it showed an Error:
ERROR: /home/nvidia/bazel-0.5.2-dist/src/main/protobuf/BUILD:27:2: Building src/main/protobuf/libextra_actions_base_proto-speed.jar (1 source jar) failed: Worker process sent response with exit code: 1.
java.lang.InternalError: Cannot find requested resource bundle for locale en_US
at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:128)
at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:147)
at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:140)
at com.sun.tools.javac.util.Log.localize(Log.java:788)
.
.
.
.
INFO: Elapsed time: 490.697s, Critical Path: 115.21s

ERROR: Could not build Bazel
cp: cannot stat 'output/bazel': No such file or directory



What could be the reason ?
