### ISSUE TITLE
[7.1.1] Disable //src/test/shell/bazel:srcs_test on Intel macOS

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#21706]
### Commit IDs

548bf4db56696557f2d1b732c56497e8098d3565

### Category

team-OSS

### Reviewers

@iancha1992

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/21707: https://github.com/bazelbuild/bazel/commit/548bf4db56696557f2d1b732c56497e8098d3565.
