### ISSUE TITLE
The following libraries were linked statically by different cc_shared_libraries but not exported

### ISSUE THREAD

**Issue by Ryang20718** [bazelbuild/bazel#21709]
### Description of the bug:

Building cc_shared_library targets with bazel 7.1.0 with --noenable_bzlmod results in errors of libraries not exported

### Which category does this issue belong to?

C++ Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I've created a small repro here: https://github.com/Ryang20718/repro-cpp-linker

if you clone it and run `bazelisk test //rust:rust_example_test` you'll hit a similar error 

```
Error in fail: The following libraries were linked statically by different cc_shared_libraries but not exported:
cc_shared_library @proj//:proj_so:
```

### Which operating system are you running Bazel on?

ubuntu 20.04

### What is the output of `bazel info release`?

7.1.0

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

yes. it was working on bazel 6.3.2. However ever since bazel 7.0.0, this has been broken

**Comment by Wyverald** [comment]
@bazel-io fork 7.1.1

**Comment by Wyverald** [comment]
likely fixed by https://github.com/bazelbuild/bazel/pull/21622; cc @comius

**Comment by fmeum** [comment]
I checked that this isn't fixed by #21622. Since it also relies on `--noenable_bzlmod`, it's unlikely to be related to repo names.

CC @oquenchil

**Comment by Wyverald** [comment]
ah, ok. Since this is not a 7.1.0 regression, I'll put it as a soft blocker for 7.1.1.

**Comment by oquenchil** [comment]
Just to clarify this was an intentional breaking change from 6.0 to 7.0.

I see that `@proj//:proj_so` is a `cc_shared_library`, the rest of the error should tell which `cc_libraries` should be declared exported. See here: https://cs.opensource.google/bazel/bazel/+/master:src/main/starlark/builtins_bzl/common/cc/cc_shared_library.bzl;drc=2abc982ca5a8d1e829613629c8e3b44cf61b58c5;l=543

The rest of the error message should tell you the solution.

**Comment by Ryang20718** [comment]
@oquenchil 

```
Are there two cc_shared_libraries linking @proj//:proj_soand the one that is a dependency is not exporting it? If so, then the error is intentional.
```

yeah,`proj_so`, a `cc_shared_library` is a dynamic dep of `gdal_so`, another cc shared library.
```
cc_shared_library(
    name = "gdal_so",
    shared_lib_name = "libgdal.so.31",
    deps = [
        ":alg",
        ":apps",
        ":cpl",
        ":gcore",
        ":geotiff",
        ":ogr",
    ],
    dynamic_deps = [
        "@proj//:proj_so",
    ],
    visibility = ["//visibility:public"],
)


cc_shared_library(
    name = "proj_so",
    shared_lib_name = "libproj-8d95adc6.so.25.9.2.0",
    deps = [":proj_lib"],
    visibility = ["//visibility:public"],
)
```

However, should we export the dependencies. i.e
```
cc_shared_library(
    name = "proj_so",
    shared_lib_name = "libproj-8d95adc6.so.25.9.2.0",
    deps = [":proj_lib"],
    # We need to export in 7.1.0 bazel version, but this causes linker errors
    exports_filter = [
        "@tiff//:tiff",
        "@jpeg//:jpeg",
        "@jpeg//:jpeg12",
        "@jpeg//:jpeg16",
        "@lerc//:lerc",
        "@zstd//:zstd",
        "@zlib//:z",
    ],
    visibility = ["//visibility:public"],
)
```

we have linker errors
```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
bazel-out/k8-fastbuild/bin/_solib_k8/_U@@gdal_S_S_Cgdal___Uexternal_Sgdal/libgdal.so.31: error: undefined reference to 'TIFFReadRGBATileExt'
bazel-out/k8-fastbuild/bin/_solib_k8/_U@@gdal_S_S_Cgdal___Uexternal_Sgdal/libgdal.so.31: error: undefined reference to 'TIFFReadRGBAStripExt'
bazel-out/k8-fastbuild/bin/_solib_k8/_U@@gdal_S_S_Cgdal___Uexternal_Sgdal/libgdal.so.31: error: undefined reference to 'TIFFRGBAImageOK'
```

**Comment by comius** [comment]
Assuming it's true this hit an intentional breakage, I'm triaging it down to P4.

cc @pzembrod

**Comment by Ryang20718** [comment]
@oquenchil I think we hit the intentional breakage, but wondering if you could provide insight as to what the proper fix should be?

With the exports_filter added, we have linker errors

**Comment by oquenchil** [comment]
Here on [the error](https://cs.opensource.google/bazel/bazel/+/master:src/main/starlark/builtins_bzl/common/cc/cc_shared_library.bzl;drc=2abc982ca5a8d1e829613629c8e3b44cf61b58c5;l=546) it says _If you are sure that the previous libraries are exported by the cc_shared_libraries_. Is this the case?

If you look at the symbols exported by the `*.so` produced by the `cc_shared_library` where you added the `exports_filter` attribute by using `nm` or similar, do you see the 3 symbols that appear on the error message?

The `cc_shared_library` rule can help at the Bazel level direct the build graph but it can't actually do the exporting at the linker level for you. You have to make sure that you are actually exporting the symbols that you claim to be exporting in the BUILD file.

**Comment by keertk** [comment]
Is this still on track for 7.2? We're aiming to create the first RC on 5/13.

**Comment by Wyverald** [comment]
Removing as 7.2.0 blocker given the P4 status.

**Comment by Ryang20718** [comment]
fixed
