### ISSUE TITLE
Bazel home page: make release tracking issues more discoverable

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2170]
See https://github.com/bazelbuild/bazel/issues/2158#issuecomment-264173521 and https://github.com/bazelbuild/bazel/issues/2158#issuecomment-264333874

**Comment by damienmg** [comment]
Can we do more than adding the "Release blocker" label and the next milestone for it?

**Comment by laszlocsomor** [comment]
Yes, I'd like to add the list of release issues somewhere on the Bazel site.

**Comment by laszlocsomor** [comment]
...or add a link that takes you to the right GitHub issue search result page.

**Comment by damienmg** [comment]
We can have a link to the open "release blocker" one. We can also reduce with "type: process" and only the release bug should appear.
