### ISSUE TITLE
Release notes include a Bazel bot account

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/bazel#21711]
### Description of the bug:

```
This release contains contributions from many people at Google, as well as bazel.build machine account
```

**Comment by keertk** [comment]
Hey @brentleyjones I'm gonna close this one -- we do a lot of manual clean up and I think you spotted this before we had a chance to edit the notes and send out any comms. :)
But thanks for flagging! There's room to be faster and improve the scripts, which we're tracking internally.
