### ISSUE TITLE
7.1.0: Fetch runs analysis on targets that do not require external dependencies

### ISSUE THREAD

**Issue by LINKIWI** [bazelbuild/bazel#21713]
### Description of the bug:

Below is a description of the symptom I am encountering. A minimally reproducible bug example is in the next section.

My build steps are, approximately:

1. `bazel fetch //...`
2. `bazel build --define FOO=bar //...`

I have a rule that runs `.format(**ctx.var)` against a string that contains `{FOO}`. This allows the rule to format the string according to the `--define` as it appears in the step 2 `bazel build` step.

After upgrading from Bazel 7.0.2 to 7.1.0, `bazel fetch` (as it appears in step 1) has started failing with (some text elided):

```
ERROR: .../BUILD:43:23: in unistore_upload_object rule //:deploy: 
Traceback (most recent call last):
	File "...", line 105, column 34, in ...
		quote(ctx.attr.key.format(**ctx.var)),
Error in format: Missing argument 'FOO'
ERROR: .../BUILD:43:23: Analysis of target '//:foo' failed
Analyzing: 19 targets (97 packages loaded, 10477 targets configured)
ERROR: Analysis of target '//:foo' failed; build aborted
```

This seems to suggest that `fetch` is now analyzing targets even if they do not have external dependencies.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`foo.bzl`:

```
def _foo_impl(ctx):
    print(ctx.var)

    return [
        DefaultInfo()
    ]

foo = rule(_foo_impl)
```

`BUILD`:

```
load("//:foo.bzl", "foo")

foo(name = "foo")
```

---

With Bazel 7.0.2, output is:

```
$ bazel fetch //...
INFO: Invocation ID: dd9b7a6a-9546-43a6-8040-f511eb65dfe1
INFO: Analyzed target //:foo (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
INFO: Elapsed time: 0.054s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
INFO: All external dependencies for these targets fetched successfully.
```

With Bazel 7.1.0, output is:

```
INFO: Invocation ID: 45aa4500-989f-4793-867f-24f55e6996c8
DEBUG: /mnt/ssd1/scratch/bazel/foo.bzl:2:10: {"TARGET_CPU": "k8", "COMPILATION_MODE": "fastbuild", "BINDIR": "bazel-out/k8-fastbuild/bin", "GENDIR": "bazel-out/k8-fastbuild/bin"}
INFO: Analyzed target //:foo (4 packages loaded, 6 targets configured).
INFO: Found 1 target...
INFO: Elapsed time: 1.146s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
INFO: All external dependencies for these targets fetched successfully.
```

This seems unexpected. I don't expect `fetch` to actually run the rule, i.e. print `ctx.var`.

### Which operating system are you running Bazel on?

`Linux 6.5.0-25-generic #25~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Feb 20 16:09:15 UTC 2 x86_64 x86_64 GNU/Linux`

### What is the output of `bazel info release`?

`release 7.1.0`

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Bisect indicates that the first bad commit is bbd608c3b6f96d25decce91eec742fbf4a3535c2.

**Comment by fmeum** [comment]
Cc @Wyverald @SalmaSamy

**Comment by Wyverald** [comment]
This is intended. We fixed `fetch` to use `cquery` semantics, which does run analysis (i.e. rule impl functions). This allows us to fetch repos that are more likely to be needed for your target.

> This seems to suggest that `fetch` is now analyzing targets even if they do not have external dependencies.

More accurately, `fetch` is analyzing _all_ targets. Technically, it's impossible to know whether a target actually has external dependencies without analyzing it, given the existence of toolchains and stuff.

Going to close this as WAI; if analyzing the target breaks your use case, please elaborate and we can re-open this issue.

**Comment by fmeum** [comment]
You could try adding  `fetch --define=FOO=some_placeholder_value` to your `.bazelrc`.
