### ISSUE TITLE
Merge of "META-INF/cxf /bus-extensions.txt" in deploy.jar

### ISSUE THREAD

**Issue by Xirponom** [bazelbuild/bazel#21722]
### Description of the bug:

When I create a fat jar of my application that depends on cxf, the "META-INF/cxf/bus-extensions.cxf" files are not merged and that causes problems. Is it possible to modify "DefaultJarEntryFilter.java" to add "META-INF/cxf/bus-extensions.cxf" ?

### Which category does this issue belong to?

Java Rules

### What is the output of `bazel info release`?

release 5.4.0

**Comment by hvadehra** [comment]
I think this is the same as https://github.com/bazelbuild/bazel/issues/7330
