### ISSUE TITLE
Remote falls back to local, not sandboxed

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/bazel#21725]
### Description of the bug:

We have a few actions that require either remote execution or sandboxed execution: they cannot be built with the local strategy.

We configure Bazel like this:

```
build --internal_spawn_scheduler
build --spawn_strategy=dynamic
build --remote_local_fallback
build --strategy=BootstrapGNUMake=remote,sandboxed
... some more strategy flags exactly like the previous one ...
```

But I've noticed that, when a remote action fails due to networking issues, Bazel reruns it *without* the sandbox and thus the action fails with the local strategy.

I found the `--remote_local_fallback_strategy` flag, which I thought would resolve our problems... but then this flag is deprecated and its docstring claims that it's a no-op. Then I went to https://github.com/bazelbuild/bazel/issues/7480 and, from my understanding of that bug, our strategy flags are already correctly configured. `--spawn_strategy` says `dynamic`, and the dynamic scheduler defaults to `worker,sandboxed` for the local path.

Is there a bug, or is something misconfigured?

### Which category does this issue belong to?

Local Execution

### Which operating system are you running Bazel on?

Linux but this is irrelevant

### What is the output of `bazel info release`?

release 6.5.0

**Comment by jmmv** [comment]
@tjgq I see you referenced this issue in #19904 but I'm not sure what that means for what I reported here. Is it possible to select "sandboxed" for the local fallback strategy? Or is this currently not doable given that the flag says it's a no-op?

**Comment by ulrfa** [comment]
Is this a duplicate of https://github.com/bazelbuild/bazel/issues/15519?

**Comment by jmmv** [comment]
Yeah, it looks like it.
