### ISSUE TITLE
[7.2.0] java_binary: superfluous dependency on MANIFEST from runfiles

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21723]
Forked from #21708

**Comment by keertk** [comment]
Need to cherry-pick https://github.com/bazelbuild/bazel/commit/6a4d61ebf2dc2214ffe6abc807e4f597175e1a6c and https://github.com/bazelbuild/bazel/commit/cff79d0aa6f2d470b8648f2b89beeefd0867e177

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21804

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21804
