### ISSUE TITLE
[7.2.0] bzlmod: “bazel mod” should fail if bzlmod is disabled

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21736]
Forked from #21303

**Comment by bazel-io** [comment]
The branch, release-7.2.0, may not exist. Please retry the cherry-pick after the branch is created.

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/test/py/bazel/bzlmod/mod_command_test.py`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Looks like this was already cherry-picked in https://github.com/bazelbuild/bazel/commit/08cc45b5812afd1c0b13bf6c36905b42d1469140
