### ISSUE TITLE
Windows: ignore trailing dots in file names

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2173]
### Description of the problem / feature request / question:

On Windows, trailing dots in path names are ignored. This is because the dot indicates where the extension would be, but if there's no extension, the dots are ignored, thus "C:/foo." is equal to "C:/foo".

**Comment by abergmeier** [comment]
@laszlocsomor Really? Is there any documentation for this?

**Comment by laszlocsomor** [comment]
@abergmeier : Yes, I did a little experiment yesterday to prove it, see below. I couldn't find any official-looking documentation (MSDN), only [on Wikipedia](https://en.wikipedia.org/wiki/8.3_filename#Overview):

> if a file name has no extension, the ., if present, has no significance (that is, myfile and myfile. are equivalent)"

Here's my experiment:
```
# start with empty directory c:\foo
c:\foo>dir /b

# create directory "hello."
c:\foo>md hello.

# the trailing "." was munched, because it indicates where
# the extension starts, but if there's no extension then the
# dot is ignored, so "hello." is equal to "hello"
c:\foo>dir /b
hello

# it even works with multiple trailing dots
c:\foo>md world..

c:\foo>md mundo...

c:\foo>dir /b
hello
mundo
world

# you can refer to files either through "hello.\name"
c:\foo>echo world > hello.\world.txt

# or through "hello\name"
c:\foo>echo mundo > hello\mundo.txt

# but not "hello..\name", so the multiple trailing dots are
# only swallowed for the last path segment
c:\foo>echo welt > hello..\welt.txt
The system cannot find the path specified.

# so far we have:
c:\foo>dir /b /s
c:\foo\hello
c:\foo\hello\mundo.txt
c:\foo\hello\world.txt

# and obviously cannot create "hello." again
c:\foo>md hello.
A subdirectory or file hello. already exists.

# nor "hello.."
c:\foo>md hello..
A subdirectory or file hello.. already exists.

# nor "hello", right?
c:\foo>md hello
A subdirectory or file hello already exists.

# but can we create the file "hello."?
c:\foo>echo really > hello.
Access is denied.

# OK, summon msys then; I haz "which"
c:\foo>which which
/usr/bin/which

# and I haz "touch"
c:\foo>which touch
/cygdrive/c/tools/msys64/usr/bin/touch

# mwahaha
c:\foo>touch hello.

# oh boy
c:\foo>dir /b /s
c:\foo\hello
c:\foo\hello.
c:\foo\mundo
c:\foo\world
c:\foo\hello\mundo.txt
c:\foo\hello\world.txt﻿
```

**Comment by laszlocsomor** [comment]
@abergmeier : After some digging (OK, scrolling down to the References section on the Wikipedia page) I found an [MSDN page](https://msdn.microsoft.com/en-us/library/aa365247.aspx#naming_conventions) dealing with this. It says:

> Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not. However, it is acceptable to specify a period as the first character of a name. For example, ".temp".

That's at least something.

**Comment by abergmeier** [comment]
Quite frankly just ignoring sounds too dangerous to me. Especially since there may be some logic working in *nix, that silently breaks on Windows.
I would issue a warning on Windows and make clear that the user is own its own when using this behavior.

**Comment by laszlocsomor** [comment]
Hm, I think you're right.

I'd rather not show a warning, IMO warnings tend to get ignored especially in large numbers (and we have a track record of showing way to many warnings in the internal version), and the only thing they achieve is user annoyance. So I'm for hard error or silence.

In this case silence seems like the better option, because if Bazel attempts to create "foo" and "foo.", the latter will fail with a user-visible error, and it's just as actionable from the user's side as if it would be with a warning.
