### ISSUE TITLE
[7.2.0] Implement StartBuild

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21738]
Forked from #21674

**Comment by iancha1992** [comment]
There was some conflicts when cherry-picking this to release-7.2.0. Can you please take a look?
cc: @bazelbuild/triage, @coeuvre, @tjgq

**Comment by iancha1992** [comment]
@coeuvre @tjgq can you please take a look at this one? There are several PR's that are dependent on this being merged. Thank you!

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21871 by @coeuvre
