### ISSUE TITLE
[7.2.0] Implement Clean

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21744]
Forked from #21743

**Comment by iancha1992** [comment]
There was a conflict when cherry-picking this to release-7.2.0 because `/src/main/java/com/google/devtools/build/lib/remote/BazelOutputService.java` does not exist in the branch currently

cc: @bazelbuild/triage, @tjgq , @coeuvre

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21927
