### ISSUE TITLE
[7.2.0] Implement FinalizeBuild

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21742]
Forked from #21739

**Comment by iancha1992** [comment]
I was not able to cherry-pick this to `release-7.2.0` branch because `src/main/java/com/google/devtools/build/lib/remote/BazelOutputService.java` does not exist yet in the branch. Could you please take a look? 

cc: @bazelbuild/triage, @coeuvre, @tjgq

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21926
