### ISSUE TITLE
Bazel error messages for custom rules in osx sandbox are near useless

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#2174]
I'm seeing error messages of the following form
```
ERROR: /Users/endobson/proj/racket/yaspl2/libraries/BUILD:216:1: Couldn't build file libraries/code-http-server_lib.o: null failed: sandbox-exec failed: error executing command /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_endobson/
f851d7f6c7010ae7d7a3db153bed36de/bazel-sandbox/af67bd96-e247-4e58-a4b6-115fd591353b-59/sandbox.sb ... (remaining 40 argument(s) skipped).
```
The first pieces of information are useful as they tell me the build rule's location and which output failed to produce. But from then on it is really bad and doesn't give me as the user any useful hints on what actually went wrong

### Environment info
* Operating System:
os x 10.11.2

* Bazel version (output of `bazel info release`):
release 0.4.0-2016-11-22 (@984d6d4)

**Comment by damienmg** [comment]
Indeed we should improve our error message (this is in sandboxing but we should improve it everywhere IMO)

**Comment by ulfjack** [comment]
Let's start with improving sandboxing errors.

**Comment by hermione521** [comment]
We used to have message like "add --verbose_failures and --sandbox_debug to debug sandbox" (first one for getting the skipped arguments, and second one for not deleting sandbox path). Do you think this is enough or what else do you like to have? Thanks

**Comment by endobson** [comment]
I do not think that just adding those are enough, but they may be helpful. If by default the command that is outputted doesn't tell me any new information then there is still more to be done. The two options that seem reasonable are not outputing the useless information until verbose output is asked for or by including enough to be useful. Where by useful I mean something that will help me debug my broken rule.

**Comment by hermione521** [comment]
I hope the last commit above gives better error message, although I still have no idea why you get "null failed".
We give instruction for flags now, so with proper flags you will get full debugging message. Feel free to reopen if the message is not enough.
