### ISSUE TITLE
Cannot load rules in external repository created by repository rule

### ISSUE THREAD

**Issue by atniomn** [bazelbuild/bazel#21753]
### Description of the bug:

I would like to load rules in an external repository.

I have the following:

WORKSPACE
```
http_archive(
    name = "my_bazel_tools",
    sha256 = "<sha>",
    url = "<url>",
)

load("@my_bazel_tools//tools/build_rules:my_shared_library.bzl", "my_shared_library")

new_git_repository(
    name =  "my_library",
    tag = "1.2.3",
    remote = "<my app remote>",
    build_file = "//bazel:my_library.BUILD"
)
```

First, I just try to use the rule:

bazel/my_library.BUILD
```
my_shared_library(
    name = "my_library",
    srcs = glob([
        "src/*.cpp"
     ]),
     visibility=["//visibility:public"],
 )
```

I expect that this should not work, because I am in different repository than the main repository, and I get this error:
```
ERROR: package contains errors: : name 'my_shared_library' is not defined (did you mean 'cc_shared_library'?)
```

makes sense.

Second, I try to load the rule:

bazel/my_library.BUILD
```
load("@my_bazel_tools//tools/build_rules:my_shared_library.bzl", "my_shared_library")

my_shared_library(
    name = "my_library",
    srcs = glob([
        "src/*.cpp"
     ]),
     visibility=["//visibility:public"],
 )
 ```
 
 I get this error:
 ```
 ERROR: Analysis of target '@my_library//:my_library' failed; build aborted: no such package '@my_library//tools/build_rules': BUILD file not found in directory 'tools/build_rules' of external repository @my_library. Add a BUILD file to a directory to mark it as a package.
 ```
 
 I don't understand this. The load statement clearly references "@my_bazel_tools", yet the error references "@my_library", why did the repository referenced by the label change? I don't understand this and suspect it's a bug.
 
Third, I tried to include an http_archive in the BUILD file, but obviously that's not permitted, because it's not a WORKSPACE.
 
Fourth, I tried to include a WORKSPACE file in the new_git_repository call:

WORKSPACE
```
new_git_repository(
    name =  "my_library",
    tag = "1.2.3",
    remote = "<my app remote>",
    build_file = "//bazel/my_library/:my_library.BUILD",
    workspace_file = "//bazel/my_library:WORKSPACE"
)
```

bazel/my_library/WORKSPACE
```
http_archive(
    name = "my_bazel_tools",
    sha256 = "<sha>",
    url = "<url>",
)

load("@my_bazel_tools//tools/build_rules:my_shared_library.bzl", "my_shared_library")
```

bazel/my_library/my_library.BUILD
```
load("@my_bazel_tools//tools/build_rules:my_shared_library.bzl", "my_shared_library")

my_shared_library(
    name = "my_library",
    srcs = glob ([
        "src/*.cpp"
    ]),
    visibility=["//visibility:public"],
)
```

This was super strange, because I believe the loading phase succeeded! The "my_shared_library" was recognized, but Bazel still complained about the missing build_rules package:

```
ERROR: Analysis of target '@my_library//:libmy_library.so_with_pic' failed; build aborted: no such package '@my_library//tools/build_rules': BUILD file not found in directory 'tools/build_rules' of external repository @my_library. Add a BUILD file to a directory to mark it as a package.
```

Like, obviously we were able to get to the analysis stage.

Fifth, with the same setup as the fourth attempt, if I comment out my load statement, "my_shared_library" is not found:

```
ERROR: <cache>/external/my_library/BUILD.bazel:3:1: name 'my_shared_library' is not defined (did you mean 'cc_shared_library'?)
ERROR: package contains errors: 
ERROR: package contains errors: : name 'my_shared_library' is not defined (did you mean 'cc_shared_library'?)
ERROR: Skipping '@my_library//...': Error evaluating '@my_library//...': error loading package '@my_library//': Package '' contains errors
```

### Which category does this issue belong to?

Loading API

### Which operating system are you running Bazel on?

RHEL 7.9

### What is the output of `bazel info release`?

release 6.4.0

### Have you found anything relevant by searching the web?

There are somewhat related issues, but they typically revolve around loading *.bzl files from the main repository within the external repository. I understand how to do this and get it to succeed. I want to load a rule from a third package in the external repository.

**Comment by meteorcloudy** [comment]
It seems you have some misunderstanding of repository rules (used in WORKSPACE) and build rules (used in BUILD). Since this isn't a bazel bug, can you please ask this question on StackOverflow to ask for help?
