### ISSUE TITLE
C++ Toolchain configuration on macOS does not allow cross compiling to another arch any more

### ISSUE THREAD

**Issue by redsun82** [bazelbuild/bazel#21768]
### Description of the bug:

Starting from bazel version 7 the autodetected C++ toolchain seems to have lost arch cross compiling capabilities (i.e. compile for `x86_64` when running on M1 `arm64`).

### Which category does this issue belong to?

C++ Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

As an example, the `//swift/extractor` target in https://github.com/github/codeql can only target `x86_64`. With bazel 6.4, I was able to compile that (and run it through rosetta) providing `--cpu=darwin_x86_64`. With bazel 7.0.1 and 7.1.0 that does not work any more, failing at linking, where `-arch arm64` is passed.

### Which operating system are you running Bazel on?

macOS 13.4.1 (arm64)

### What is the output of `bazel info release`?

release 7.1.0

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Yes, this is a regression. I tried `bazelisk --bisect=6.4.0..7.1.0` and it pointed at https://github.com/bazelbuild/bazel/commit/b5db37924fc204eff4ed6ebbccba18da972bf538, but I think it's a spurious result (the failures bisect were encountering seemed unrelated)

### Any other information, logs, or outputs that you want to share?

In bazel 6.4.0, `external/local_config_cc_toolchains/BUILD` is a symlink to `embedded_tools/tools/osx/crosstool/BUILD.toolchains` and contains toolchains for all sorts of macOS targets:
```bazel
load("@bazel_tools//tools/osx/crosstool:osx_archs.bzl", "OSX_TOOLS_ARCHS")

package(default_visibility = ["//visibility:public"])

exports_files(["osx_archs.bzl"])

# Target constraints for each arch.
# TODO(apple-rules): Rename osx constraint to macOS.
OSX_TOOLS_CONSTRAINTS = {
    "armeabi-v7a": [
        "@platforms//cpu:armv7",
        "@platforms//os:android",
    ],
    "darwin_arm64": [
        "@platforms//os:osx",
        "@platforms//cpu:arm64",
    ],
    "darwin_arm64e": [
        "@platforms//os:osx",
        "@platforms//cpu:arm64",
    ],
    "darwin_x86_64": [
        "@platforms//os:osx",
        "@platforms//cpu:x86_64",
    ],
    ...
}

OSX_DEVELOPER_PLATFORM_CPUS = [
    "arm64",
    "x86_64",
]

[
    toolchain(
        name = "cc-toolchain-" + arch + "-" + cpu,
        exec_compatible_with = [
            # These only execute on macOS.
            "@platforms//os:osx",
            "@platforms//cpu:" + cpu,
        ],
        target_compatible_with = OSX_TOOLS_CONSTRAINTS[arch],
        toolchain = "@local_config_cc//:cc-compiler-" + arch,
        toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
    )
    for arch in OSX_TOOLS_ARCHS + ["armeabi-v7a"]
    for cpu in OSX_DEVELOPER_PLATFORM_CPUS
]
```

In 7.1.0, I found this instead:
```bazel
toolchain(
    name = "cc-toolchain-darwin_arm64",
    exec_compatible_with = HOST_CONSTRAINTS,
    target_compatible_with = HOST_CONSTRAINTS,
    toolchain = "@local_config_cc//:cc-compiler-darwin_arm64",
    toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
)

toolchain(
    name = "cc-toolchain-armeabi-v7a",
    exec_compatible_with = HOST_CONSTRAINTS,
    target_compatible_with = [
        "@platforms//cpu:armv7",
        "@platforms//os:android",
    ],
    toolchain = "@local_config_cc//:cc-compiler-armeabi-v7a",
    toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
)
```

**Comment by fmeum** [comment]
The toolchain has been moved out to https://github.com/bazelbuild/apple_support in Bazel 7.

**Comment by redsun82** [comment]
ah, I see, thanks for the info!

**Comment by keith** [comment]
FWIW this change happened because now by default bazel's unix cc toolchain is used on macOS (where previously the one that's now in apple_support was used) and the default toolchain doesn't support any form of cross compiling

**Comment by redsun82** [comment]
Thank you, that makes sense!

For reference for anybody stumbling into this, [this is what I did](https://github.com/github/codeql/pull/16025/commits/5eaba48317b997d2f8b2163cfaed6215820a818c) to get things working again on our end. Notice I had to use `--platforms=@apple_support//platforms:macos_x86_64` rather than goofing around with `--cpu`.

**Comment by brentleyjones** [comment]
I'm surprised that `--cpu` didn't work.
