### ISSUE TITLE
[7.2.0] Implement RemoteActionFileSystem#statIfFound correctly when the path cannot be canonicalized (because one of the components is a non-directory or a dangling symlink).

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#21762]
### Commit IDs

b78d73fab1f01e2e8ae29bed667865a42800b626

### Category

team-Rules-API

### Reviewers

@tjgq

**Comment by iancha1992** [comment]
Will attempt to cherry-pick this once the branch is created.

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but failed to push. Please check if the branch, cp_ondemand_21762-7.2.0, already exists
cc: @bazelbuild/triage

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/21800: https://github.com/bazelbuild/bazel/commit/b78d73fab1f01e2e8ae29bed667865a42800b626.
