### ISSUE TITLE
DumpPlatformClassPath: include tools.jar when dumping JDK 8

### ISSUE THREAD

**Issue by rbeasley** [bazelbuild/bazel#21771]
### Description of the feature request:

To address asymmetry between JDK 8 and JDK 9+ w/r/t classes collected by `DumpPlatformClassPath`, I wonder if something like the following is desirable:

```diff
@@ -187,6 +187,10 @@ public class DumpPlatformClassPath {
         jars.add(path);
       }
     }
+    Path toolsJar = javaHome.resolve("lib/tools.jar");
+    if (Files.exists(toolsJar)) {
+      jars.add(toolsJar);
+    }
     return jars;
   }

```

### Which category does this issue belong to?

Java Rules

### What underlying problem are you trying to solve with this feature?

DumpPlatformClassPath (DPCP) is used by Bazel's / rules_java's `bootclasspath` rule to collect type information from the JDK's bootstrap or platform classes. On Java 9+, this includes the `jdk.compiler` module which provides classes like `com.sun.source.util.DocTreePath`. However, on Java 8 compiler classes are instead in a separate `tools.jar` and are ignored by DPCP.

Historically pure Java 8 workspaces would have to explicitly extract `tools.jar` from their JDK in order to use those classes w/ Bazel:

```python
genrule(
  name = "grab_tools",
  outs = ["tools.jar"],
  cmd = "cp $(JAVABASE)/lib/tools.jar $@",
  toolchains = ["@bazel_tools//tools/jdk:current_java_runtime"],
)
java_import(name = "tools", jars = [":grab_tools"])
java_library(name = "example", srcs = ["Example.java"], deps = [":tools"])

# Example.java is just
#
# import com.sun.source.util.DocTreePath
# class Example { public static void main(String[] args) {} }
```

Things get tricky when targeting Java 8 but using non-JDK 8 runtimes. This will fail when using `--java_runtime_version` of 9+, because `tools.jar` doesn't exist. I'd instead have to add a `select` to `deps` to conditionally include `tools.jar` as a dependency.

Since the `bootclasspath` for Java 9+ implicitly includes `jdk.compiler`, could the equivalent for Java 8 include `tools.jar`?

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 7.0.1

### Any other information, logs, or outputs that you want to share?

https://bazelbuild.slack.com/archives/CDCE4DFAP/p1710973678057699 Brief thread in bazelbuild Slack w/ fmeum.

**Comment by hvadehra** [comment]
(waiting for a rules_java release)
