### ISSUE TITLE
[7.2.0] Implement FinalizeArtifacts

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21784]
Forked from #21759

**Comment by iancha1992** [comment]
There was a conflict when cherry-picking this to release-7.2.0 because `src/main/java/com/google/devtools/build/lib/remote/BazelOutputService.java` does not exist yet in the branch currently. 

cc: @bazelbuild/triage, @coeuvre

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21930

**Comment by iancha1992** [comment]
Will cherry-pick this after https://github.com/bazelbuild/bazel/pull/21928 is merged.

**Comment by bazel-io** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21942
