### ISSUE TITLE
test summary reports incorrect cached ratio

### ISSUE THREAD

**Issue by haxorz** [bazelbuild/bazel#218]
repro:

nharmata-macbookair:base_workspace nharmata$ git log | head -n 1
commit 91430c71b44e92eb81af27522347b2dad7cf1084
nharmata-macbookair:base_workspace nharmata$ cat demo/pass.sh 
true
nharmata-macbookair:base_workspace nharmata$ ../output/bazel test //demo:demo_test 2> /dev/null
//demo:demo_test                                                         PASSED

Executed 1 out of 1 tests: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
nharmata-macbookair:base_workspace nharmata$ ../output/bazel test //demo:demo_test 2> /dev/null
//demo:demo_test                                            (1/0 cached) PASSED

Executed 0 out of 1 tests: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
nharmata-macbookair:base_workspace nharmata$

expected output would be either
  (1/1 cached) PASSED
or simply
  PASSED

fyi, this message comes from https://github.com/google/bazel/blob/4f08bef4cfc187392ef366d3dd2f35fcf8e5832d/src/main/java/com/google/devtools/build/lib/runtime/TestSummaryPrinter.java#L215-L219 and so i'm guessing TestSummary#totalRuns is plain wrong or is used inconsistently

**Comment by kchodorow** [comment]
It's `(cached) PASSED` internally, we should match that.
