### ISSUE TITLE
[7.2.0] Respect $XDG_CACHE_HOME if available for Bazel's output root on Linux and BSD

### ISSUE THREAD

**Issue by tetromino** [bazelbuild/bazel#21816]
### Commit IDs

05ae91f1a04b55af94aaa7b52ef34cb3a6ce7fa4

### Category

team-OSS

### Reviewers

@Wyverald

**Comment by bazel-io** [comment]
Failed commmits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/05ae91f1a04b55af94aaa7b52ef34cb3a6ce7fa4.
Please resolve manually.
cc: @bazelbuild/triage
