### ISSUE TITLE
[bazel.build] required JDK version on /install/compile-source

### ISSUE THREAD

**Issue by dws** [bazelbuild/bazel#21821]
### Page link:

https://bazel.build/install/compile-source

### Problem description (include actual vs expected text, if applicable):

Since this page currently states only that JDK 11 is required, it provides no guidance about newer versions of the JDK.
My understanding is that Bazel is starting to take advantage of features in newer JDKs if they are available.  If that is the case, then I suspect that this page should be updated to reflect that building with JDK 21 works and may be preferable, even if it may not yet be required.

Also, do we need to have a JDK installed if we are building Bazel with an existing Bazel binary?  Or is it only required when bootstrapping?

**Comment by fmeum** [comment]
Cc @zhengwei143

**Comment by zhengwei143** [comment]
> Also, do we need to have a JDK installed if we are building Bazel with an existing Bazel binary? Or is it only required when bootstrapping?

I think its needed for both.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.2.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.2.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.2.0rc1. Thanks!
