### ISSUE TITLE
`yes "" | bazel fetch ...` hangs on Windows

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2182]
### Description of the problem / feature request / question:

When running TF's configure script on Windows, `yes "" | ./configure` hangs after output `INFO: All external dependencies fetched successfully.`

### If possible, provide a minimal example to reproduce the problem:
```
pcloudy@PCLOUDY1-W MSYS ~/workspace
$ mkdir test_dir

pcloudy@PCLOUDY1-W MSYS ~/workspace
$ touch test_dir/WORKSPACE

pcloudy@PCLOUDY1-W MSYS ~/workspace
$ cd test_dir/

pcloudy@PCLOUDY1-W MSYS ~/workspace/test_dir
$ touch BUILD

pcloudy@PCLOUDY1-W MSYS ~/workspace/test_dir
$ yes "" | bazel fetch ...
......................
INFO: All external dependencies fetched successfully.
(Hangs here forever)
```
### Environment info
* Operating System:
Windows 7

* Bazel version (output of `bazel info release`):
```
Build label: 0.4.1
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 30 09:15:17 2016 (1480497317)
Build timestamp: 1480497317
Build timestamp as int: 1480497317
```

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
No

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).
This works fine on Linux

**Comment by meteorcloudy** [comment]
@lberki Can you take a look at this? I don't think I have enough knowledge to figure out the reason.. :(

**Comment by lberki** [comment]
Well, that not much data to draw conclusions from... looking at this:

https://github.com/tensorflow/tensorflow/blob/master/configure

it seems that the `bazel fetch` invocation is the last thing that script does, which is weird. Maybe msys is failing at stopping the `yes` command after the command on the other side of the pipe ends? Does this work without the `yes` part? 

I'd look at the set of running processes while it's hanging to figure out what's going on (and if the Bazel server is there, I'd attach a debugger to see what's going on). I'd also try adding debug statements to the Bazel client to see how far it gets (if it's still alive while the comand is hanging)

**Comment by meteorcloudy** [comment]
I believe this is a bug in Bazel itself, see the minimal example I gave, it doesn't involve any shell script. Thanks for the advice, I'll take another look.
