### ISSUE TITLE
[7.2.0] Stringify `Label`s in display form in `Args`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21826]
Forked from #21702

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/analysis/CachingAnalysisEnvironment.java`
`src/main/java/com/google/devtools/build/lib/analysis/starlark/Args.java`
`src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkActionFactory.java`
`src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkCustomCommandLine.java`
`src/test/java/com/google/devtools/build/lib/analysis/starlark/StarlarkCustomCommandLineTest.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21956
