### ISSUE TITLE
[7.2.0] fetch no longer works for targets ending in `...`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21831]
Forked from #21728

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by meteorcloudy** [comment]
We'll need to cherry-pick https://github.com/bazelbuild/bazel/commit/bbd608c3b6f96d25decce91eec742fbf4a3535c2 again

/cc @SalmaSamy @iancha1992

**Comment by meteorcloudy** [comment]
Yeah, I encountered the same issue, I had to disable the test case, see https://github.com/bazelbuild/bazel/pull/21567/commits/fb360250e03fb8856caf18b837d697032da25395
