### ISSUE TITLE
[7.2.0] Update release notes script

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#21843]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/9a333bc59e04e3c926121b11eb97547ba823c6ed

### Category

team-OSS

### Reviewers

@iancha1992

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/21844: https://github.com/bazelbuild/bazel/commit/9a333bc59e04e3c926121b11eb97547ba823c6ed.
