### ISSUE TITLE
[7.2.0] Use XattrProvider from OutputService to check filesystem values

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21842]
Forked from #21840

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21852

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/test/java/com/google/devtools/build/lib/skyframe/FilesystemValueCheckerTest.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21947
