### ISSUE TITLE
android_integration_test.sh does not work with NDK12

### ISSUE THREAD

**Issue by aj-michael** [bazelbuild/bazel#2184]
Support for Android NDK R12 was added in 722d03c2f6958ca942eb0efed85cb4fbcebdfb92. This removed ARM "hard" CPUs. //src/test/shell/bazel/android:android_integration_test tries to pass these CPU values to `--fat_apk_cpu` which causes the tests to fail.

We should probably just delete the relevant lines from the test.

**Comment by ahumesky** [comment]
For reference, this is where we set up the NDK:
https://github.com/bazelbuild/continuous-integration/blob/79de9267af8135532eab002e6d83d3e97bda96bd/gce/linux-android.sh#L19

**Comment by aj-michael** [comment]
Ok, I have a fix for the test. After it is submitted, I will update the continuous-integration setup script.
