### ISSUE TITLE
[bazel.build] Problem with /start/java

### ISSUE THREAD

**Issue by chris-yin** [bazelbuild/bazel#21848]
### Page link:

https://bazel.build/start/java

### Problem description (include actual vs expected text, if applicable):

I am new to bazel with java and would like to use JDK 17 to execute/test my code. The start/java docs indicate that the newest JDK version I can use is 15. Is this accurate or out of date?

Based on my understanding [here](https://bazel.build/docs/bazel-and-java), bazel compiles with an internal JDK, and the executes/tests using a user-provided JDK.

Parts of the [source code](https://github.com/bazelbuild/bazel/blob/46285cbe9c8307ead3c4ade4f16c39e1a414ff0f/src/BUILD#L584-L588) indicate that newer JDK versions have been used during the build.

Actual text:
> Install Java JDK (preferred version is 11, however versions between 8 and 15 are supported).

### Where do you see this issue? (include link to specific section of the page, if applicable)

https://bazel.build/start/java#install_the_jdk

**Comment by srdo** [comment]
My understanding is incomplete, but maybe this will be helpful to you, I'm sure people will offer corrections if this is wrong:

The documentation is out of date. You can build with any JDK version. I have a project building with Java 21 currently.

There are (I think) these JDK versions involved in a build: 

* The JDK that's used for running Bazel (unless you're downloading a `nojdk` version of Bazel, this is part of the bundle you download). I believe for current releases, the bundled JDK is Java 21.
* The JDK used for compiling sources, controlled via e.g. `--java_language_version=17`
* The JDK used for running binary targets or tests, controlled via e.g. `--java_runtime_version=remotejdk_17`
* The JDK used for compiling tool sources, controlled via e.g. `--tool_java_language_version=17`
* The JDK used for executing tools, controlled via e.g. `--tool_java_runtime_version=remotejdk_17`

If you just want to run and build with Java 17, and you don't have a special need to use a specific JDK distribution, then the easy solution is that you add this to your `.bazelrc` file:

```
build --java_language_version=17
build --java_runtime_version=remotejdk_17
build --tool_java_language_version=17
build --tool_java_runtime_version=remotejdk_17
```

That should make your build download a JDK 17 binary for your platform and use it for all the things I mentioned above.

**Comment by chris-yin** [comment]
thank you for the in-depth response! I’ve been using `java_language_version
=17` without any issues so far
