### ISSUE TITLE
experimental_repository_cache: should warn (error) if two repository rules claim the same content address

### ISSUE THREAD

**Issue by pcj** [bazelbuild/bazel#2185]
Consider the following `WORKSPACE` with 0.4.1 on osx and `build --experimental_repository_cache=/Users/pcj/bazel-cache` in  `~/.bazelrc`:

```python
maven_jar(
    name = "com_google_code_findbugs_jsr305",
    artifact = "com.google.code.findbugs:jsr305:jar:3.0.1",
    sha1 = "f7be08ec23c21485b9b5a1cf1654c2ec8c58168d",
)

maven_jar(
    name = "this_is_bogus",
    artifact = "any:bogus_maven:coordinate",
    sha1 = "f7be08ec23c21485b9b5a1cf1654c2ec8c58168d",
)
```

Will successfully install `external/this_is_bogus/...` having file contents equal to the findbugs jar, and the `@this_is_bogus//jar` label is perfectly valid.  

In this example, it's obvious that this_is_bogus is incorrect, but if the maven_jar rule is otherwise valid and contains an erroneous duplicate sha1 of another rule, it will be a very frustrating experience trying to track down why a perfectly fine looking rule otherwise does not work.

I suggest making it an error for two workspace names to resolve to the same hash (unless explicitly suppressed with another flag).

**Comment by damienmg** [comment]
I am not sure what is the best way to do it. Maybe make the warning not on by default for rules and activate it for maven_rules. As a side note, giving an empty sha also gives no warning.

Let's bring in @kchodorow for discussion.

**Comment by ulfjack** [comment]
I don't think that this should be an error - it's perfectly reasonable to have two identical files with different names. However, maven_jar should only use the cache after it has validated that the coordinates exist upstream. That probably requires having a cache for the performed lookup somewhere, not just for the contents.

**Comment by benley** [comment]
How hard would it be to write a WORKSPACE linter that could notice this sort of thing?  For just the WORKSPACE file it would be pretty easy, but I'm less certain about handling included skylark files, particularly from remote repositories.

**Comment by pcj** [comment]
@ulfjack Is there any support for this lookup cache you are thinking about?  How involved would this be?

**Comment by ulfjack** [comment]
@pcj I don't know. I am not familiar at all with the implementation of experimental_repository_cache. I'm just saying that, in my opinion, if the cache purely goes by sha1, there should be a check to ensure we only use the repository cache if we've previously checked that the coordinates exist. And we'd want to cache such a check to avoid having to connect to the internet on a non-fetch build.

**Comment by jin** [comment]
A way to solve this will be having a metadata file stored along each cache entry to keep track of the coordinates. Right now, the artifact files are stored in a folder (in the repository cache) named after the artifact's SHA1/256. It'll should be trivial to add a verification for metadata file contents. Folder structure should look something like this:

```
.../repository_cache/
    content_addressable/
        sha256/
             123456abcd..../
                  file
                  METADATA
```

**Comment by ulfjack** [comment]
Well, how do you handle the case where multiple coordinates resolve to the same sha? Add two entries to the METADATA file? In that case, how do you handle concurrent updates to the file? I think it would be better to have a separate tree that maps from coordinates to sha.

```
.../repository_cache/
    maven_coordinates/
        a:b:c -> ../content_addressable/sha256/123456abcd....
```

(This is a symlink. If we need more metadata, we could make it an actual file.)

**Comment by kchodorow** [comment]
Right now the cache doesn't handle concurrent access at all, so we can "lock" a metadata file the same way we (will) lock the cache itself.  

I bet there are duplicate jars out there with different coordinates and the same SHAs. I guess it's unlikely to have two in the same WS file, though, that might be worth making an error.

We've talked about adding a metadata file, probably just a .proto with a repeated field, with info about who was using the cache entry.  It seems reasonable to include rule-specific info, like maven coordinates (but at the very least WORKSPACE file locations). We've also gotten requests to expose where the cache entry was downloaded from, which could also be in the proto. Then the metadata proto could be parsed by some tool, if people wanted to check.

**Comment by ulfjack** [comment]
File system locking is notoriously unreliable, as far as I know. I'd go with an atomic move, which allows 'locking' for individual files, but still doesn't allow you to do concurrent access to a single file.

**Comment by sbalabanov** [comment]
We observed a related issue.
A user has changed some http_rule to download from a different URL but forgot to change SHA parameter of the rule to the checksum of a new object. Because repository cache on user machine and CI machine had old SHA, it did not detect the problem and the change got landed. The new dependency is compliant with the older version of the dependency, so CI build did not fail either, it just silently used the previous version of the dependency.
However, when CI machines got refreshed and lost repository cache, they tried to actually download the dependency and failed with SHA256 mismatch error for any build they tried to make.
Should the repository cache folder structure also include metadata (hash of it) of the rule definition as well?
