### ISSUE TITLE
bazel query doesn't like 'common' in .bazelrc

### ISSUE THREAD

**Issue by kayasoze** [bazelbuild/bazel#2186]
```
INFO: Reading options for 'query' from /home/.../.bazelrc:
  Inherited 'common' options: --action_env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Unrecognized option: --action_env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by damienmg** [comment]
--action_env is a build option not a common one (it does not work for query).

pinging @aehlig to see if there is common to replace by build somewhere. Also maybe that should be query command.

**Comment by kayasoze** [comment]
I tried 'common' because the documentation claims that Bazel creates defaults that way; from http://www.bazel.io/docs/designs/2016/06/21/environment.html:

```
Currently, some users of Bazel already make use of the fact that PATH, LD_LIBRARY_PATH, and TMPDIR are being passed to actions. To allow those projects a smooth transition to the new set up, the global Bazel rc-file provided by upstream will have the following content.

common --action_env=PATH
common --action_env=LD_LIBRARY_PATH
common --action_env=TMPDIR
```

For the most part, it works, but query does barf. 

I've been having issues preventing rebuilds on PATH change, even when PATH is defined via --action_env, so I tried common hoping that would fix the problem.

**Comment by aehlig** [comment]
> I tried 'common' because the documentation claims that Bazel creates
> defaults that way; from http://www.bazel.io/docs/designs/2016/06/21/environment.html:

Thanks for pointing this out. It seems that our documentation hasn't been pushed
to github for a while; the design document has been fixed quite a while ago
in our upstream repository, see https://github.com/bazelbuild/bazel/blob/master/site/designs/_posts/2016-06-21-environment.md

> I've been having issues preventing rebuilds on PATH change,
>  even when PATH is defined via --action_env [...]

Did you try specifying a fixed value here? I.e., using something like

```
build --action_env=PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
```

Note that just saying `--action_env=PATH` means it should be taken from the
invocation environment; and, of course, if an environment variable changes,
the action has to be redone.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by aehlig** [comment]
On Thu, Dec 08, 2016 at 05:16:57PM +0100, Klaus Aehlig wrote:
> > I tried 'common' because the documentation claims that Bazel creates
> > defaults that way; from http://www.bazel.io/docs/designs/2016/06/21/environment.html:
> 
> Thanks for pointing this out. It seems that our documentation hasn't been pushed
> to github for a while [...]

Actually no, the URL is outdated. When first adding design documents, we several
times changed the location where they reside, but apparently never removed them
on the outdated places. The correct URL for that design is
http://www.bazel.io/designs/2016/06/21/environment.html

How did you find the above link?

Thanks,
Klaus

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by kayasoze** [comment]
I've been testing with a full PATH defined, e.g. 

build --action_env=PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

Even with a fully defined path, different PATHs in the environment will cause spurious rebuilds.

**Comment by damienmg** [comment]
FYI I deleted the docs/designs directory all together.

I still think this option should applies for query but it's probably a not so important feature if we fix the documentation,

**Comment by aehlig** [comment]
So the documentation issue is solved; for the other issue mentioned, please file a new issue and also provide a minimal example where an environment change causes an unintended rebuild.
