### ISSUE TITLE
[Bazel CI] Error with Label '@@platforms//host:extension.bzl' is invalid because 'host' is not a package 


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#21877]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3769

Platform: Ubuntu, MacOs, Windows

 Logs: 
```
ERROR: [0merror loading package '': Label '@@platforms//host:extension.bzl' is invalid because 'host' is not a package; perhaps you meant to put the colon here: '@@platforms//:host/extension.bzl'?
``` 
 Culprit: https://github.com/bazelbuild/bazel/commit/74c8ca4886cfc188d60a18e796743e842f675842

 CC Greenteam @fweikert @meteorcloudy @Wyverald 

Few downstream projects are failing with below error 

1. [Gerrit](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3769#018ea222-6d7f-40ad-b7be-5968452be271)
2. [Kythe](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3769#018ea222-49c9-4cc7-9778-1b6ceed2c0cc)
3. [Stardoc](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3769#018ea222-1dd6-4b6f-bcfc-6dc7f3493da4)
4. [Protobuf](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3769#018ea222-4e75-4907-925f-fc6e3badc85d)
5. [rules_dotnet](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3769#018ea222-25dd-4fa3-9fb3-24e247c19ccc)
6. [rules_foreign_cc](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3769#018ea222-15fb-4940-90b1-a07ea9ca8285)
7. [rules_go](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3769#018ea222-19ab-45ce-a1d4-bb5755e808ca)
8. [rules_haskell](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3769#018ea222-1b84-48da-98a8-51bae2d4308a)

**Comment by brentleyjones** [comment]
They need to depend on the newer `@platforms`. We fixed this in apple_support here: https://github.com/bazelbuild/apple_support/commit/a1c4ec2b13b899a9eb52313881b78378c9516b58.

**Comment by Wyverald** [comment]
This is an unfortunate issue only with WORKSPACE -- Bazel itself already ships with the latest `@platforms` bundled, but there's no way to "force" that to be the version to be used. With Bzlmod, `bazel_tools` depends on the latest `platforms`, so there's no issue.

**Comment by Wyverald** [comment]
This also means that https://github.com/bazelbuild/bazel/commit/74c8ca4886cfc188d60a18e796743e842f675842 is not cherry-pickable back to 7.2.0. Hmm... I might need to come up with some halfway solution here.

**Comment by fmeum** [comment]
Could we just keep the default value of `--host_platform` as is for WORKSPACE (i.e., depending on the `--enable_bzlmod` flag)? Realistically speaking all WORKSPACE projects would otherwise have to manually bump platforms and also add the separate setup step for the generated repo. Since WORKSPACE users won't benefit from the future improvements to constraint registration, that pain won't pay off for them anyway.

**Comment by Wyverald** [comment]
Changing the flag default based on another flag sounds pretty error-prone. But I think I can safely change what `@bazel_tools//tools:host_platform` aliases to based on the value of `--enable_bzlmod`.

> also add the separate setup step for the generated repo.

This part is unnecessary; it's done in the WORKSPACE suffix. In fact it's what's causing the current breakage...

> Since WORKSPACE users won't benefit from the future improvements to constraint registration, that pain won't pay off for them anyway.

I mostly wanted to deprecate the native repo rule. I guess that's still doable, we just need to ship a copy of `@@platforms//host:extension.bzl` in Bazel 7.x. Which isn't the end of the world, but the setup is getting quite convoluted.

**Comment by meteorcloudy** [comment]
Downstream projects are still failing: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3783

**Comment by meteorcloudy** [comment]
Looks like there are still platforms related failures in https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3797

**Comment by meteorcloudy** [comment]
Oh, the fix was just submitted one hour ago, let's wait for another day.

**Comment by Wyverald** [comment]
I've sent a change internally to fix the `android_sdk_repository` issue.

Regarding Stardoc, there honestly isn't a good fix... We can upgrade `rules_dotnet` to use a newer Stardoc (which properly uses `starlark_doc_extract`), but that requires setting up a `bzl_library`/`filegroup` target for the `constraints.bzl` file in `local_config_platform`, which is very hard to do in a backwards-compatible manner. Will need to think about it more.

**Comment by brentleyjones** [comment]
I assume this inn't fully fixed yet? (@Wyverald feel free to re-close it if it is)

**Comment by Wyverald** [comment]
Indeed; GitHub apparently doesn't understand "partially" :)

**Comment by brentleyjones** [comment]
Does https://github.com/bazelbuild/stardoc/pull/213 help in this regard? Basically, newer Stardoc will be bzlmod only.

**Comment by Wyverald** [comment]
Not really -- Stardoc dropping WORKSPACE support doesn't help with this specific issue. Projects using old Stardoc (pre-`starlark_doc_extract`) will fail anyway with Bzlmod; projects using newer Stardoc will be broken because they need to update their `bzl_library` deps. This is very unsatisfactory but is an unfortunately consequence of `bzl_library` being in `bazel_skylib`. We need to move `bzl_library` into `bazel_tools` and then we could properly set up `bzl_library` targets for .bzl files in `@bazel_tools`, `@platforms`, etc.

**Comment by brentleyjones** [comment]
> We need to move `bzl_library` into `bazel_tools`

💯

**Comment by Wyverald** [comment]
We specifically didn't want to introduce a dependency on skylib from `@platforms`, which doesn't have any dependencies right now. It's not as easy as "just add skylib" because there's still WORKSPACE :)

**Comment by meteorcloudy** [comment]
Oh, I meant making the change of moving `bzl_library` from `bazel_skylib` to `bazel_tools` itself to be backwards compatible. I guess we need to add some redirects to bazel_skylib to make sure everyone is using the same `bzl_library`?

**Comment by Wyverald** [comment]
See also https://github.com/bazelbuild/bazel-skylib/pull/495 which would serve as a stop-gap in the meantime.

**Comment by meteorcloudy** [comment]
Nice! /cc @comius

**Comment by fmeum** [comment]
> ah, I see -- yes, that's the plan. `bzl_library` in `bazel_skylib` would just be an alias for its counterpart in `bazel_tools`.

Isn't that difficult to pull off since `load` are entirely static? For `bzl_library` in `bazel_skylib` to be an alias of the one in `bazel_tools`, we would either need to add a minimum Bazel version requirement to that version of skylib or introduce repo rules with generated loads. The latter would probably break with WORKSPACE though since many skylib users don't call its dependency macro (which so far only registers a toolchain for unit tests).

**Comment by meteorcloudy** [comment]
> we would either need to add a minimum Bazel version requirement to that version of skylib or introduce repo rules with generated loads.

I think this is also the concern Ivo raised to me. I don't have great answers, maybe we can backport the bzl_library to bazel_tools change in older Bazel LTS releases to make it easier for users to adapt? So basically, users have to migrate to the latest minor Bazel releases to use the latest bazel_skylib, which should be easy theoretically.

**Comment by Wyverald** [comment]
All green now!
