### ISSUE TITLE
`cc_shared_library.exports_filter` doesn't support apparent repo names

### ISSUE THREAD

**Issue by apronchenkov** [bazelbuild/bazel#21872]
It appears that cc_shared_library.exports_filter only supports canonical repository names, which (afaik) are not recommended for direct use.

Motivational example: https://github.com/google/arolla/blob/main/py/arolla/dynamic_deps/BUILD#L61-L62

**Comment by fmeum** [comment]
This will be fixed by https://github.com/bazelbuild/bazel/pull/21622.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.2.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.2.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.2.0rc1. Thanks!
