### ISSUE TITLE
`cc_binary` does not allow use of `select()` in `deps` when also using `dynamic_deps` 

### ISSUE THREAD

**Issue by ceyxiang** [bazelbuild/bazel#21875]
### Description of the bug:

I am using bazel 7.1.1 and if I create a cc_binary with

1. A dynamic_deps dependency
2. A select() in the deps attribute

I would get an error message

```
File "/virtual_builtins_bzl/common/cc/cc_shared_library.bzl", line 854, column 28, in cc_shared_library_initializer
Error in extend: type 'select' is not iterable
```

### Which category does this issue belong to?

C++ Rules, Core

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a `BUILD` file with this content

```
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_binary(
    name = "test",
    srcs = ["main.cpp"],
    dynamic_deps = [":anything"],
    deps = select({
        "//:my_config": [":any_cc_lib"],
        "//conditions:default": [],
    }),
)
```

The `config_setting`, `cc_library`, `cc_shared_library` do not need to exist. It fails immediately I believe in the analysis phase

### Which operating system are you running Bazel on?

Ubuntu 20.04

### What is the output of `bazel info release`?

release 7.1.1 and release 7.0.2

### Any other information, logs, or outputs that you want to share?

Example error message

```
christopher.eng:~/test_bazel_issue$ bazel run //:test
ERROR: Traceback (most recent call last):
        File "/home/christopher.eng/test_bazel_issue/BUILD", line 19, column 10, in <toplevel>
                cc_binary(
        File "/home/christopher.eng/.cache/bazel/_bazel_christopher.eng/5f68f153a1098415a7d48083ccf4c165/external/rules_cc/cc/defs.bzl", line 59, column 21, in cc_binary
                native.cc_binary(**_add_tags(attrs, True))
        File "<builtin>", in cc_binary
        File "/virtual_builtins_bzl/common/cc/cc_shared_library.bzl", line 854, column 28, in cc_shared_library_initializer
Error in extend: type 'select' is not iterable
WARNING: Target pattern parsing failed.
ERROR: Skipping '//:test': no such target '//:test': target 'test' not declared in package '' defined by /home/christopher.eng/test_bazel_issue/BUILD
ERROR: no such target '//:test': target 'test' not declared in package '' defined by /home/christopher.eng/test_bazel_issue/BUILD
INFO: Elapsed time: 0.045s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target
```

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.2.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.2.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.2.0rc1. Thanks!
