### ISSUE TITLE
[7.2.0] Use BatchStat for incremental build

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21879]
Forked from #21870

**Comment by iancha1992** [comment]
Waiting on https://github.com/bazelbuild/bazel/pull/21871 to merge first before cherry-picking it

cc: @bazelbuild/triage

**Comment by bazel-io** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21943

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but failed to push. Please check if the branch, cp21870-7.2.0, already exists
cc: @bazelbuild/triage

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but failed to push. Please check if the branch, cp21870-7.2.0, already exists
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21958
