### ISSUE TITLE
[7.1.2] Implement RemoteActionFileSystem#statIfFound correctly when the path cannot be canonicalized

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#21888]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/b78d73fab1f01e2e8ae29bed667865a42800b626

### Category

team-Rules-API

### Reviewers

@tjgq

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/21889: https://github.com/bazelbuild/bazel/commit/b78d73fab1f01e2e8ae29bed667865a42800b626.
