### ISSUE TITLE
[Mirror] Gazelle v0.36.0

### ISSUE THREAD

**Issue by tyler-french** [bazelbuild/bazel#21886]
### Please list the URLs of the archives you'd like to mirror:

github.com/bazelbuild/bazel-gazelle/releases/download/v0.36.0/bazel-gazelle-v0.36.0.tar.gz

**Comment by sgowroji** [comment]
Here it is

https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.36.0/bazel-gazelle-v0.36.0.tar.gz
