### ISSUE TITLE
[Mirror] go-genproto

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#21894]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/googleapis/go-genproto/archive/995d672761c0c5b9ac6127b488b48825f9a2e5fb.zip

**Comment by sgowroji** [comment]
Here you go 
https://mirror.bazel.build/github.com/googleapis/go-genproto/archive/995d672761c0c5b9ac6127b488b48825f9a2e5fb.zip
