### ISSUE TITLE
[bazel.build] Problem with /rules/lib/builtins/repository_ctx description of default working_directory for execute()

### ISSUE THREAD

**Issue by dws** [bazelbuild/bazel#21897]
### Page link:

https://bazel.build/rules/lib/builtins/repository_ctx

### Problem description (include actual vs expected text, if applicable):

The description of working_directory for repository_ctx.execute() says:

    default is ""
    Working directory for command execution. Can be relative to the repository root or absolute.

but this does not actually state what the default of "" _means_.  I'm _guessing_ that the default of "" means that the default working directory for command execution is the root of the repository since it does not begin with a "/" that would mark it as an absolute path.

### Where do you see this issue? (include link to specific section of the page, if applicable)

https://bazel.build/rules/lib/builtins/repository_ctx#parameters_3

**Comment by meteorcloudy** [comment]
Thanks for reporting!

That should mean default to the repository root, can you please send a PR to fix this issue?
https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java;l=1563

**Comment by dws** [comment]
@meteorcloudy Done; please see https://github.com/bazelbuild/bazel/pull/22669
