### ISSUE TITLE
[7.2.0] Show display form labels in `java_*` buildozer fixups

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21908]
Forked from #21827

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/test/shell/bazel/bazel_java_test.sh`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21948

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21956 by @fmeum
