### ISSUE TITLE
[7.2.0] Automatically map paths in `Args#map_each`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21903]
Forked from #19723

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/actions/BUILD`
`src/main/java/com/google/devtools/build/lib/actions/PathMapper.java`

cc: @bazelbuild/triage

**Comment by fmeum** [comment]
Has been rolled back.
