### ISSUE TITLE
Windows: don't shell out to `cmd.exe`

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2190]
### Description of the problem / feature request / question:

`cmd.exe` doesn't support UNC paths so we can't shell out to tools through it and use long paths.

Example where this occurs: [`WindowsFileSystem.createDirectoryJunction`](https://github.com/bazelbuild/bazel/blob/3fd5d398890f27cdfbb39eac063c1418fe6f1285/src/main/java/com/google/devtools/build/lib/vfs/WindowsFileSystem.java#L247)

Related issue: https://github.com/bazelbuild/bazel/issues/2181

### Environment info
* Operating System: Windows 10

**Comment by laszlocsomor** [comment]
This issue is actually blocking #2181 .

**Comment by laszlocsomor** [comment]
P2, because there is a workaround: use `--output_user_root=<something short>`.

You can even create a virtual drive:
```
subst d: c:\some\path\where\bazel\can\put\stuff
```
then just use `--output_user_root=/d/`.

**Comment by laszlocsomor** [comment]
Re: https://github.com/bazelbuild/bazel/issues/2190#issue-193718660 and  `WindowsFileSystem.createDirectoryJunction`, that's actually a bad example, because `mklink` is a built-in command of `cmd.exe`, so we'll have to implement the junction creation in JNI anyway.

The [`CommandBuilder`](https://github.com/bazelbuild/bazel/blob/3fd5d398890f27cdfbb39eac063c1418fe6f1285/src/main/java/com/google/devtools/build/lib/util/CommandBuilder.java#L161) however suffers from this limitation.

**Comment by abergmeier-dsfishlabs** [comment]
Isn't this rather a bug?

**Comment by petemounce** [comment]
Generally don't use cmd, because MS announced that they will (finally!!) be deprecating it (over some time): http://www.osnews.com/story/29502/Microsoft_replaces_cmd_with_PowerShell_in_new_Windows_10_build

**Comment by laszlocsomor** [comment]
@petemounce : AIUI they aren't deprecating cmd, just making it non-default. So cmd will be around... *in ghastly voice* foreveeeeeeer.

**Comment by petemounce** [comment]
Sure. Still don't use it. :p

**Comment by dslomov** [comment]
Powershell is very very slow to start (as in, >10x slower than cmd.exe as @philwo measured)
So we avoid using powershell as a shell.
See https://docs.google.com/document/d/1z6Xv95CJYNYNYylcRklA6xBeesNLc54dqXfri0z0e14/ for some plans

**Comment by davido** [comment]
Another reason to not shell out to `cmd.exe` is 8191 command line limit: #3579.

**Comment by laszlocsomor** [comment]
This is the only non-test place I found where Bazel shells out to `cmd.exe`: https://github.com/bazelbuild/bazel/blob/b8742540bd2aaad8e6de879c2d02f42f185f6f4f/src/main/java/com/google/devtools/build/lib/util/CommandBuilder.java#L163

I have a hunch (that I need to verify) that you can `CreateProcess` with other executables than `.exe` files, so automatically using cmd may be unnecessary: https://github.com/bazelbuild/bazel/blob/b8742540bd2aaad8e6de879c2d02f42f185f6f4f/src/main/java/com/google/devtools/build/lib/util/CommandBuilder.java#L146-L147

**Comment by laszlocsomor** [comment]
PR #5007 was rolled back in https://github.com/bazelbuild/bazel/commit/835814895fffef00fe88658f91e4550dc61546cf.

**Comment by laszlocsomor** [comment]
Apparently the `CommandBuilder.java` can still shell out to `cmd.exe`, so this bug is not fixed.

**Comment by laszlocsomor** [comment]
Other than `CommandBuilder.java`, the Android tools' junction helper (that I wrote) also uses cmd: https://github.com/bazelbuild/bazel/blob/acb1bd10fc8a25000fcebe5d53e2fdc28a2333f1/tools/android/junction.py#L89

These are the only two locations I'm aware of. (And some more in Bazel's own tests.)

**Comment by laszlocsomor** [comment]
I'm not sure if this bug is really that big of a deal:
- For the Android tools: `mklink` supports long paths, even when invoked from cmd. The limiting factor for the path length of the junction target is the 8K command line limit.
- Bazel shells out to cmd.exe only when:
  - the action sets `/bin/sh` or `/bin/bash` as its executable (I could not find any native rules doing so; I can't rule out Starlark rules doing it via the deprecated `ctx.action()`), or
  - when the argv0 does not end with ".exe", which should only happen on Windows if the extension is ".bat" or ".cmd" (very rare) which are fine to run under cmd.exe

**Comment by laszlocsomor** [comment]
Because of https://github.com/bazelbuild/bazel/issues/2190#issuecomment-468638563, I'm marking it as P4.

**Comment by meisterT** [comment]
Closing for the reasons mentioned above.
