### ISSUE TITLE
`java_binary` can no longer be used in `$(location)` expansions

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#21915]
### Description of the bug:

Prior to Bazel 7, it was possible to have a `java_binary` target be used with a `$(location)` expansion. This was very useful when (eg) passing the value to scripts or writing it to a file. With recent Bazel releases, this is no longer possible, because Bazel claims that there's more than one output of the rule. 

### Which category does this issue belong to?

Java Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```starlark
java_binary(
   name = "bin",
   ...
)

genrule(
    name = "foo",
    outs = "location.txt",
    cmd = "echo $(location :bin) >$@",
)
```

While this example uses `genrule` and there's a workaround for that, this issus is about the change in behaviour.

### Which operating system are you running Bazel on?

n/a

### What is the output of `bazel info release`?

7.1.1

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
n/a
```

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Yes. This worked in Bazel 6.5.0

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by hvadehra** [comment]
@shs96c I can't seem to repro the regression. With the example provided, it fails for both 6.5.0 & 7.1.1 is the java_binary is supplied in the genrule's `srcs`. It works for both Bazel versions if supplied in `tools`. It also works for both Bazel versions in `srcs` if the java_binary has `create_executable = False`. 

Could you please provide a more concrete repro?

**Comment by shs96c** [comment]
Sure. I’m on vacation right now but will provide a more complete example
when I return.

**Comment by iancha1992** [comment]
@bazel-io fork 7.2.0

**Comment by shs96c** [comment]
I've tried to create a reduced test case for this without success. Closing since I appear to have failed to understand my own build.
