### ISSUE TITLE
bazel refuses to start due to javac not being detected when it is

### ISSUE THREAD

**Issue by solomoncyj** [bazelbuild/bazel#21918]
### Description of the bug:

Bazel refuses to load, complaines 
`FATAL: Could not find system javabase. Ensure JAVA_HOME is set, or javac is on your PATH.` when i have java JDK

### Which category does this issue belong to?

External Dependency

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

![image](https://github.com/bazelbuild/bazel/assets/74647769/22cf8419-31c5-4072-8f3c-29826f92e1c2)

### Which operating system are you running Bazel on?

Windows 10

### What is the output of `bazel info release`?

7.1.1

**Comment by hvadehra** [comment]
Looks like the error message is misleading on Windows, where, unlike linux, we only check for `JAVA_HOME`: https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/blaze_util_windows.cc#L467-L479

@solomoncyj can you try setting the `JAVA_HOME` env variable?

**Comment by solomoncyj** [comment]
alright thanks
