### ISSUE TITLE
Dynamic *_test args attr calculation

### ISSUE THREAD

**Issue by trivigy** [bazelbuild/bazel#2193]
### Description of the problem / feature request / question:
Trying to figure out how to calculate *_test args attr dynamically. I have the need to actually calculate this parameter during transitive data passing within my custom rule and finally send the aggregated data into the test.

**Comment by damienmg** [comment]
Sorry, can you be a bit more precise, an example maybe?

**Comment by trivigy** [comment]
I am not entirely sure how to give an example but I will try. I built a rule that compute a binary file (python pex build). Right now I am writing a test rule for the same thing. The issue I am experiencing is that I can pass the `args` attr in my BUILD file for the particular test. However that means that the particular list(string) is going to be static and I have to define it ahead of time. Technically in my specific scenario, what should go into the `args` attr is the locations of all of my dependencies and all of their dependencies, etc. I could manually calculate them all out however, it would be significantly easier if I could actually just compute these while the actual build is happening and then assign ctx.attr.args before returning. Obviously writing to ctx.attr.args is an illegal operation and therefore I am trying to figure out an alternative method.

Thank you.

**Comment by damienmg** [comment]
Having something like:
"
my_rule(name = "myname",
   deps = MY_DEPS,
   args = ["$(location %s)" % dep for dep in MY_DEPS],
)
"
And use location expansion is not enough?

**Comment by trivigy** [comment]
Hmmmmmm.... thanks for the advice. I have never done this and will go ahead and mess around with this approach. I will reply with my findings shortly.
