### ISSUE TITLE
Add support for understanding Git submodules

### ISSUE THREAD

**Issue by vrishabmadduri** [bazelbuild/bazel#21950]
### Description of the feature request:

Bzlmod currently doesn't have a way for users to specify that they want a dependency to be in the form of a Git submodule. The ask is to add a way to configure or flag a dependency as a Git submodule.

Example of the proposed workflow:

1. Bazel Dependency B is added to the MODULE.bazel file of module A.
2. Dependency B is configured to be a Git submodule with a pointer to the local/remote Git repository that dependency B's source code is stored:

```
git_submodule(
    module_name = "B",
    remote = "https://google.com/foo/B",
    path = "local/path/to/B",
    branch = "dev", # Users could specify commit instead, which would check out the submodule to the specified commit
)
```
4. Upon a Bazel build of target A, a Git submodule of dependency B is added to the local Git repository and the path at which it is cloned to is recorded by Bazel and referenced by target A.

If a dependency module is configured as a Git submodule and it's parent target is not built in a Git repository, the build should fail. Git submodules can only be added to a Git repository.

### Which category does this issue belong to?

Configurability, External Dependency

### What underlying problem are you trying to solve with this feature?

There is currently not a tight integration between Bazel and Git, which results in users needing to develop extra tooling to automate the connection of the two.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 6.5.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
N/A
```

### Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

N/A

**Comment by nachumg** [comment]
Could this also be applied to support git subtree, or is that a different feature?

**Comment by vrishabmadduri** [comment]
I think we'll need a slightly different workflow for Git subtree, since technically the subtree paths/remote repos are not registered with Git like how Git submodules are. Let's leave subtrees for another FR since I think it won't be as straightforward as Git submodules (although there should be some overlap).

**Comment by vrishabmadduri** [comment]
P.S. I'm willing to implement this FR myself, but I would like some feedback from the Bazel team on whether this FR makes sense.

**Comment by meteorcloudy** [comment]
Do I understand correctly that `local/path/to/B` is located under the project's source tree and you want to Bazel to maintain its content via `git_submodule`? If so, that doesn't actually fit the view of Bazel. Because Bazel doesn't want to modify the source tree of a project and expect the external dependencies to be prepared at `<output_base>/external` where `<output_base>` is a path calculated for your workspace.

**Comment by meteorcloudy** [comment]
If the source content is completely managed by the user, can you just use `local_path_override` to introduce the dependency at that path? I don't quite understand why Bazel has to know it is a git submodule and what it should do.

**Comment by meteorcloudy** [comment]
Do I understand correctly, this is basically asking for the `git_override` to work transitively? The problem is if there are multiple `git_submodule`  for `B` in the dependency graph, Bzlmod won't know which one to pick.

**Comment by vrishabmadduri** [comment]
Not exactly, I'm looking for `git_submodule` (as defined in the FR) to be supported in the source.json file in a Bazel registry, similar to how git_repository was added recently: https://github.com/bazelbuild/bazel/issues/17473.

If multiple `git_repository` dependencies for `B` are found in the dependency graph, how does Bzlmod currently resolve this? It would be the same version resolution pattern for `git_submodule` as for `git_repository`.

**Comment by meteorcloudy** [comment]
I see, can you explain more about what the difference would be for `git_submodule` compared to `git_repository` in source.json?

> If a dependency module is configured as a Git submodule and it's parent target is not built in a Git repository, the build should fail.

What does parent target mean here?

**Comment by vrishabmadduri** [comment]
1. It's somewhat of a mix between `git_repository` and `local_repository`.  See the following example:

```
{
  "type": "git_submodule",
   "remote": "https://google.com/foo/B"
   "path": "local/path/to/b_repo"
   "commit": "123" # i.e could be -> "branch": "dev" or "tag": "v_01"
}
```
where:

`remote`: The URI of the remote Git repository.
`path`: The local path that the Git submodule will be added to.
`commit`: Specific commit to be checked out. Precisely one of branch, tag, or commit must be specified.

During the resolution of the `git_submodule` dependency, a Git submodule will be added to the git repository in the user's current directory (tracked via the Git repository's `.gitmodules/.gitconfig` files) and cloned to `local/path/to/b_repo`. The Git submodule will then be checked out to commit `123`.

`local/path/to/b_repo` is now effectively a `local_repository` that bzlmod refers to.


2. I meant the root module. This dependency only makes sense if the user is running Bazel within a Git repository.

**Comment by meteorcloudy** [comment]
> Not exactly - the source content will be completely managed by the user via the remote Git repository.

But this contradict the statement above, right? You do want Bazel to clone a repo under user's current source tree? Is there any reason you cannot just use `git_repository` and don't have the repo cloned to `local/path/to/b_repo`?

**Comment by vrishabmadduri** [comment]
I don't think it contradicts the previous statement - the source content is managed by the user, but Bazel manages where the dependency lives (just like the `local_repository` statement).

`local/path/to/b_repo` in this case would be within a Git repository. You cannot directly clone a Git repository inside another, you need to use submodules or subtrees. 

We are looking to "mark" specific dependencies as Git submodules, so that from the root module level, the Git submodules can be added to the root Git repository. Users can utilize all of the benefits of Git submodules without needing to worry about maintaining the connection between the build tool and Git.

**Comment by meteorcloudy** [comment]
> Bazel helps manage where the dependency lives.

This is what not Bazel is meant to do. In principle, Bazel shouldn't pull any additional sources under user's workspace. There was a previous similar use case in rules_nodejs, where it uses a repository rule to prepare the node_modules under the user's workspace, and it didn't work out well.

**Comment by vrishabmadduri** [comment]
If the user explicitly asks for this by defining a specific module in the registry, I don't understand why not?

I'm not familiar with the `rule_nodejs` repo rule, but I know that the operation that I am suggesting here is quite simple: it's just a `git submodule add` command run during dependency resolution.

**Comment by meteorcloudy** [comment]
Because this is a very unusual use case:
- There is no existing repository rules in `@bazel_tools` backing this `git submodule add`
- Bazel modifying user's source could lead to confusion in skyframe when tracking file changes.
- Dependency resolution relies on whether the root module is a git repo or not, which is very weird.
- What if the end user decides to do `git submodule add` manually? What is the source of the truth, how to many sure everything is up-to-date?

In general, I don't think we would want to support and maintain such a feature in Bazel.

**Comment by vrishabmadduri** [comment]
> What is the source of the truth, how do we make sure everything is up-to-date?

This is probably the bigger issue. I discussed this internally with my team and we think having a separate tool that contains a separate, single source of truth to automate this connection makes more sense. Having Bzlmod control which submodules are added and removed doesn't seem right.
