### ISSUE TITLE
Tutorial is broken on Linux because of the Android SDK version

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2195]
https://github.com/bazelbuild/bazel/commit/978c4a9f8ba0da990fa62a80570865be1d0d48b9 have increased the version needed for the Android SDK but some of our slave still use a older version. See http://ci.bazel.io/job/Tutorial/641/

**Comment by damienmg** [comment]
There is also a couple of failures on bazel-tests of course.

Identified slave to update:
ubuntu_14.04-x86_64-3
ubuntu_14.04-x86_64-2
ubuntu_14.04-x86_64-4
ubuntu_15.10-x86_64-4

It's probably better to just run an script on all the slave.

**Comment by damienmg** [comment]
Thanks great :)

**Comment by damienmg** [comment]
Version of the build tools on all the slaves:
ubuntu-15-10-slave-2: 24.0.2
ubuntu-15-10-slave-5: 24.0.3
ubuntu-15-10-slave-6: 24.0.3
ubuntu-14-04-slave-3: 24.0.1
ubuntu-14-04-slave-7: 24.0.3
ubuntu-15-10-slave-3: 24.0.3
ubuntu-15-10-slave-7: 24.0.3
ubuntu-14-04-slave-4: 24.0.2
ubuntu-14-04-slave-8: 24.0.3
ubuntu-14-04-slave-staging: 25.0.0
ubuntu-15-10-slave-4: 24.0.2
ubuntu-15-10-slave-8: 24.0.3
ubuntu-15-10-slave-staging: 25.0.0
ubuntu-14-04-slave-2: 24.0.1
ubuntu-14-04-slave-5: 24.0.3
ubuntu-14-04-slave-6: 24.0.3

So outdated slave are
ubuntu-15-10-slave-2: 24.0.2
ubuntu-14-04-slave-3: 24.0.1
ubuntu-14-04-slave-4: 24.0.2
ubuntu-15-10-slave-4: 24.0.2
ubuntu-14-04-slave-2: 24.0.1

**Comment by aj-michael** [comment]
We should probably keep them consistent with each other. It could be the case that a build-tools version release alters Blaze behavior by changing flags in a tool that we use.

**Comment by damienmg** [comment]
I propose that: I will shutdown those slave to do my run then once the run is finished you can go ahead and do a reimage of all the vms. WDYT?

**Comment by damienmg** [comment]
missing slave in the list: "ubuntu-14-04-slave" is also outdated

**Comment by aj-michael** [comment]
SGTM

**Comment by aj-michael** [comment]
Ok, I've kicked off a reimaging of only the outdated VMs.

**Comment by aj-michael** [comment]
Ok, the six outdated slaves have been reimaged.
