### ISSUE TITLE
When --remote_download_outputs=toplevel 'bazel run' may fail to run a transitioned binary

### ISSUE THREAD

**Issue by ljessendk** [bazelbuild/bazel#21955]
### Description of the bug:

When --remote_download_outputs=toplevel (default in Bazel 7) I am unable to run a transitioned C++ binary that depends on a shared library when outputs are fetched from cache.

Basically what I have is:
- A C++ shared library 'mylib'
- A C++ binary 'mybin'
- An 'exec' transition rule that creates a symlink 'mybin_transitioned' (in the target output folder) that points to 'mybin' (in the exec output folder)

When i execute 'bazel run mybin_transitioned' the error I get looks like this:
<pre>
... bazel-out/k8-fastbuild/bin/mybin_transitioned: error while loading shared libraries: libST-13d3ddad9198_libmylib.so: cannot open shared object file: No such file or directory
</pre>
It seems that this error occurs because the file bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/libmylib.so is not fetched from cache. Note that other files, including bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/libmylib.so-2.params and bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/mybin are fetched as expected.

I can get the above error to disappear if I either:
- Set --remote_download_outputs=all
- Build without cache
- Build when cache is not populated

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

transitions.bzl:

<pre>
def _symlink_transition_rule_impl(ctx):
    ctx.actions.symlink(output = ctx.outputs.output, target_file = ctx.file.target_file, is_executable = True)
    default_info = ctx.attr.target_file[DefaultInfo]
    return [
        DefaultInfo(
            files = depset(direct = [ctx.outputs.output], transitive = [default_info.files]),
            runfiles = default_info.default_runfiles.merge(ctx.runfiles([ctx.outputs.output])),
            executable = ctx.outputs.output,
        ),
    ]

def _attrs(cfg):
    return {
        "output": attr.output(mandatory = True),
        "target_file": attr.label(mandatory = True, allow_single_file = True, cfg = cfg),
    }

def _create_symlink_transition_rule(cfg):
    return rule(
        implementation = _symlink_transition_rule_impl,
        attrs = _attrs(cfg),
        executable = True,
    )

exec_symlink_transition = _create_symlink_transition_rule("exec")
</pre>

BUILD:
<pre>
load("transitions.bzl", "exec_symlink_transition")

cc_library(
    name = "mylib",
    srcs = [
        "mylib.cpp",
    ],
    tags = ["manual"],
)

cc_binary(
    name = "mybin",
    srcs = [
        "mybin.cpp",
    ],
    deps = ["mylib"],
    tags = ["manual"],
    linkstatic = False,
)

exec_symlink_transition(
   name = "mybin_transition",
   target_file = "mybin",
   output = "mybin_transitioned",
)
</pre>

.bazelrc:
<pre>
build --disk_cache /tmp/cache
</pre>

mylib.cpp:
<pre>
int get_nr() {
    return 0;
}
</pre>

mybin.cpp:
<pre>
#include <iostream>

int get_nr();

int main() {
    std::cout << "Result was: " << get_nr() << std::endl;
    return 0;
}
</pre>

Steps to reproduce (with Bazel 7.1.1):
<pre>
rm -rf /tmp/cache
bazel clean
bazel run :mybin_transitioned
bazel clean
bazel run :mybin_transitioned
</pre>

### Which operating system are you running Bazel on?

Fedora 37

### What is the output of `bazel info release`?

release 7.1.1

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/11920 is an issue that also seems to affect 'bazel run' depending on the setting of --remote_download_outputs. However this issue has been solved.

**Comment by tjgq** [comment]
I believe this is working as intended. The `--remote_download_toplevel` behavior for a binary rule is to download the rule's default outputs (in this case, just the executable itself) and its runfiles tree. Your `exec_symlink_transition` rule declares a runfiles tree with a single element (the binary itself) so that's the only file Bazel believes should be downloaded when you ask that target to be built. The shared library is expected to be found in the runfiles, so dynamic linking fails.

Can you explain which problem you want to solve by creating a symlink to the binary in a different location? Once I understand the requirements, I might be able to suggest a better way to achieve that goal.

**Comment by fmeum** [comment]
@tjgq Even though the use of `allow_single_file` makes this a bit confusing, doesn't the rule merge in default outputs and default runfiles from the target it wraps, in this case `mybin`?

**Comment by tjgq** [comment]
Actually, @fmeum has a point. The `exec_symlink_transition` rule is totally fine. The issue is that you're invoking `bazel run :mybin_transitioned` instead of `bazel run :mybin_transition`.

**Comment by ljessendk** [comment]
@tjgq, yes running `bazel run :mybin_transition` works. Thanks!

I'm not sure I fully understand why `bazel run :mybin_transitioned` doesn't work with --remote_download_outputs=toplevel, but the following rule does:
<pre>
genrule(
    name = "use_mybin",
    tools = ["mybin_transitioned"],
    outs = ["gen.txt"],
    cmd = "$(location mybin_transitioned) > $@",
)
</pre>

Also, isn't this a correctness issue (different behavior depending on whether the cache is populated)?

**Comment by tjgq** [comment]
> I'm not sure I fully understand why bazel run :mybin_transitioned doesn't work with --remote_download_outputs=toplevel, but the following rule does:

As far as I can tell, `bazel run :mybin_transitioned` and `bazel build :use_mybin` behave identically wrt the presence of runfiles, but I suspect you're getting a disk cache hit for the `genrule` the second time you build it (so the action doesn't actually run a second time). `bazel run`, on the other hand, always runs the binary unconditionally.

> Also, isn't this a correctness issue (different behavior depending on whether the cache is populated)?

It's how building without the bytes is supposed to work. If an action hits a disk or remote cache, only the outputs requested by the `--remote_download_*` flags are produced; if the action doesn't hit the cache and runs locally, all outputs are produced (they might be needed by subsequent actions, so we can't just throw them away). The difference is only observable if the build is doing non-hermetic things (using an input without explicitly declaring it); sandboxing cannot defend against every form of non-hermeticity, unfortunately.
