### ISSUE TITLE
Add test for bazel clean, incl. --async

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#2196]
Also update the documentation to use present tense consistently, and active voice.

**Comment by ulfjack** [comment]
See https://github.com/bazelbuild/bazel/pull/2053

**Comment by laszlocsomor** [comment]
Done for "clean" and "clean --expunge" in https://github.com/bazelbuild/bazel/blob/663df9d96f10a2dd0fa8a85b4aac39cd2cc368fb/src/test/py/bazel/bazel_clean_test.py

**Comment by laszlocsomor** [comment]
Someone else will have to do this for `--async` though.

**Comment by benjaminp** [comment]
2b21225ac3b7adf12b0066df2548a9725e504b54

**Comment by philwo** [comment]
Thanks @benjaminp! Closing this as fixed.
