### ISSUE TITLE
[Mirror] GraalVM

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#21977]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.2/graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz

**Comment by satyanandak** [comment]
here you go
https://mirror.bazel.build/github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.2/graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz
