### ISSUE TITLE
[7.2.0] Hang in 'checking cached actions'

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21970]
Forked from #21712

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/bazel/BazelRepositoryModule.java`
`src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryFunction.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/bazel/BazelRepositoryModule.java` `src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryFunction.java`
> 
> cc: @bazelbuild/triage

@fmeum @Wyverald

**Comment by Wyverald** [comment]
cherry-picked in https://github.com/bazelbuild/bazel/pull/22261

**Comment by xiemotongye** [comment]
This issue reappeared in version 7.3.2. Then I downgraded version to 7.2.0, it was gone.

**Comment by meteorcloudy** [comment]
@xiemotongye Can you file a new issue with details to reproduce this?
