### ISSUE TITLE
android_library/binary can't rasterize vector drawables

### ISSUE THREAD

**Issue by JakeWharton** [bazelbuild/bazel#2197]
### Description of the problem / feature request / question:

The Android Gradle plugin version 1.4.0 introduced the ability to rasterize vector drawables to PNGs at compile-time for backwards compatibility with pre-21 devices (on 21+ the vector drawables are supported natively): http://android-developers.blogspot.com/2015/09/android-studio-14.html

It doesn't not appear Bazel currently offers any such functionality.

While the support library team quickly followed this with a vector drawable support library, it has various limitations and runtime overhead which can make it unattractive to use in certain situations. Our apps and a few libraries currently rely on this functionality heavily since we still support pre-21 devices and will be doing so for some time.

### If possible, provide a minimal example to reproduce the problem:

```
$ tree
.
├── AndroidManifest.xml
├── BUILD
├── WORKSPACE
└── res
    └── drawable
        └── action_bar_back.xml

$ cat WORKSPACE
android_sdk_repository(
    name = "android_sdk",
    path = "/Users/jw/android-sdk",
    api_level = 25,
    build_tools_version="25.0.1"
)

$ cat BUILD
android_binary(
  name = "app",
  srcs = glob(["src/**"]),
  resource_files = glob(["res/**"]),
  custom_package = "com.example",
  manifest = "AndroidManifest.xml",
)

$ cat AndroidManifest.xml
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example"
    >
  <uses-sdk
      android:minSdkVersion="19"
      android:targetSdkVersion="25"
      />
</manifest>

$ cat res/drawable/action_bar_back.xml
<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:height="24dp"
    android:viewportHeight="24"
    android:viewportWidth="24"
    android:width="24dp">

  <path
      android:pathData="M11.5 4l-8 8 8 8M4.5 12h17 "
      android:strokeColor="#ffffffff"
      android:strokeWidth="2.33"/>
</vector>
```
Run `bazel build //...` and then `$(bazel info output_base)/external/android_sdk/build-tools/25.0.1/aapt d --values resources $(bazel info bazel-bin)/app.apk` to list the resources inside the APK.

Currently you see the `com.example:drawable/action_bar_back` XML in the default configuration. But I would expect it to be moved to `anydpi-v21` and six generated PNGs present in `ldpi`, `hdpi`, `xhdpi`, `xxhdpi`, and `xxxhdpi`.

### Environment info
* Operating System: Mac OS 10.12.1
* Bazel version (output of `bazel info release`): 0.4.1-homebrew

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

Nope.

### Anything else, information or logs or outputs that would be helpful?

The Android Gradle plugin implementation of this functionality is encapsulated in [`VectorDrawableRenderer`][1] which calls through to [`VdPreview`][2] for the actual rasterization. The behavior only happens when the library or binary's `minSdkVersion` is declared as being less than 21.

Additionally, you can customize and/or disable the behavior through [`VectorDrawableOptions`][3] of the plugin's Gradle DSL. Setting `useSupportLibrary = true` will disable the behavior when it otherwise would be enabled. The `generatedDensities` list allows you to pick which densities the rasterized PNGs are created for. By default it emits PNGs for ldpi, mdpi, hdpi, xhdpi, xxhdpi, and xxxhdpi.

 [1]: https://android.googlesource.com/platform/tools/base/+/master/build-system/builder/src/main/java/com/android/builder/png/VectorDrawableRenderer.java
 [2]: https://android.googlesource.com/platform/tools/base/+/master/sdk-common/src/main/java/com/android/ide/common/vectordrawable/VdPreview.java
 [3]: http://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.VectorDrawablesOptions.html

**Comment by laszlocsomor** [comment]
@calpeyser : Please feel free to reassign if you're not the right assignee!

**Comment by meisterT** [comment]
What is the status of this?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
