### ISSUE TITLE
bazel-complete fails due to ccache

### ISSUE THREAD

**Issue by waarmond** [bazelbuild/bazel#21978]
### Description of the bug:

The _bazel-complete.bash_ step at my 7.1.1 build (Python 3.10, Arch-derivative) fails due to a read-only ccache folder.
Disabling !ccache had no effect on the build:
```
INFO: Analyzed target //scripts:bazel-complete.bash (485 packages loaded, 10582 targets configured).
ERROR: ./bazel/src/src/main/tools/BUILD:3:10: Compiling src/main/tools/daemonize.c [for tool] failed: (Exit 1): gcc failed: error executing CppCompile command (from target //src/main/tools:daemonize) /usr/lib/ccache/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 23 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
ccache: error: Failed to create temporary file for ~/.ccache/tmp/daemonize.stdout: Read-only file system
```
Next build - strings.cc first:
`
Compiling src/main/cpp/util/strings.cc
[..]
ccache: error: Failed to create temporary file for ~/.ccache/tmp/strings.stdout: Read-only file system`

As far as I know ccache 4.0 has made stored and fetched object files read-only. When I override this with chmod -R 777 it is sadly getting changed back.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
./compile.sh
./output/bazel build scripts:bazel-complete.bash
```

### Which operating system are you running Bazel on?

ArchLinux

### What is the output of `bazel info release`?

N/A: build issue

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
using bazel-7.1.1-dist.zip
```

**Comment by tjgq** [comment]
There's nothing in Bazel that uses ccache. My guess is that you have ccache enabled through an environment variable, but it doesn't work because Bazel runs the C compiler in a sandboxed environment, where the location ccache wants to output to isn't writable.

Can you try building with ccache disabled?
