### ISSUE TITLE
`--incompatible_sandbox_hermetic_tmp` breaks gcc's dependency file outputs

### ISSUE THREAD

**Issue by thii** [bazelbuild/bazel#21981]
### Description of the bug:

Building with a custom hermetic gcc toolchain with Bazel 7 results in the following errors:

```
ERROR: /home/user/example/BUILD:106:11: Compiling hello.cpp failed: absolute path inclusion(s) found in rule '//:hello':
the source file 'hello.cpp' includes the following non-builtin files with absolute paths (if these are builtin files, make sure these paths are in your toolchain):
  '/tmp/bazel-source-roots/0/x86_64-unknown-linux-gnu/sysroot/usr/include/stdc-predef.h'
  '/tmp/bazel-source-roots/0/x86_64-unknown-linux-gnu/sysroot/usr/include/c++/v1/stdio.h'
<redacted>
```

Looking at the dependency file output, it contains absolute paths to files mounted in the hermetic tmp:

```
$ cat bazel-out/k8-fastbuild/bin/_objs/hello/hello.pic.d
bazel-out/k8-fastbuild/bin/_objs/hello/hello.pic.o: \
 hello.cpp \
 /tmp/bazel-source-roots/0/x86_64-unknown-linux-gnu/sysroot/usr/include/stdc-predef.h \
 /tmp/bazel-source-roots/0/x86_64-unknown-linux-gnu/sysroot/usr/include/c++/v1/stdio.h \
<redacted>
```

It works if I disable `--incompatible_sandbox_hermetic_tmp`, here are the contents of the dependency file in that case (`gcc-sysroot` is one of the repositories mounted in the hermetic tmp)

```
$ cat bazel-out/k8-fastbuild/bin/_objs/hello/hello.pic.d
bazel-out/k8-fastbuild/bin/_objs/hello/hello.pic.o: \
 hello.cpp \
 external/gcc-sysroot/x86_64-unknown-linux-gnu/sysroot/usr/include/stdc-predef.h \
 external/gcc-sysroot/x86_64-unknown-linux-gnu/sysroot/usr/include/c++/v1/stdio.h \
<redacted>
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I don't have a minimal example, but the same issue can also be reproduced with a public project (tested with Bazel 7.1.1):

```
git clone https://github.com/google/pigweed.git
bazel build --platforms=//pw_build/platforms:testonly_freertos //pw_sync/... --incompatible_sandbox_hermetic_tmp
```

### Which operating system are you running Bazel on?

Ubuntu

### What is the output of `bazel info release`?

release 7.1.1

### Any other information, logs, or outputs that you want to share?

Related: https://issues.pigweed.dev/issues/318850523

**Comment by fmeum** [comment]
While it's true that the sandbox layout changed with this flag flip, it shows that your compilation action isn't fully hermetic: gcc prints the resolved paths of symlinks, which could also become problematic in other cases. 

Are you passing `-fno-canonical-system-headers` or `-no-canonical-prefixes`? That's what Bazel's default toolchain does to fix this problem.

**Comment by fmeum** [comment]
> This still does seem like a regression, because when building with `--noincompatible_sandbox_hermetic_tmp` (and without `-fno-canonical-system-headers`), gcc doesn't print the resolved paths of symlinks.

I am working on making that flag less breaking, but it is an incompatible flag flipped in a major release and thus not necessarily considered a regression if something breaks with it. 

Without `-fno-canonical-system-headers`, gcc would be free to emit absolute paths into dependency files if they are shorter than the execroot path, which could very well happen with certain remote execution setups even without `--incompatible_sandbox_hermetic_tmp`.

**Comment by fmeum** [comment]
> @fmeum Sorry, I have a follow-up question. What would you suggest to do in a build where none of these flags are allowed?

You can use `--sandbox_add_mount_pair=/tmp` to disable the path remapping for now. I plan to have a better sandboxing layout ready for Bazel 7.2.0 which doesn't require as much bind mounting.

> From what I observed, if the mounted path contains the repository name (for instance, `/tmp/bazel-source-roots/0/external/repo_name` instead of `/tmp/bazel-source-roots/0`), then gcc won't print absolute paths into the .d files. And this seems like something can be fixed from Bazel.

I suspect that Bazel has very little to do with this, `external/repo_name` just happens to be long enough to make that path longer than the hermetic alternative. I'll try to find the relevant part of the gcc codebase to confirm this.
