### ISSUE TITLE
[7.2.0] Clean up `cc_shared_library` runfiles test

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21986]
Forked from #21880

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`MODULE.bazel`
`MODULE.bazel.lock`
`src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/BUILD.builtin_test`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `MODULE.bazel` `MODULE.bazel.lock` `src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/BUILD.builtin_test`
> 
> cc: @bazelbuild/triage

cc: @fmeum @pzembrod

**Comment by Wyverald** [comment]
#22321
