### ISSUE TITLE
BUILD.bazel in external repo doesn't work

### ISSUE THREAD

**Issue by lizan** [bazelbuild/bazel#2198]
in Bazel 0.4.1, packages are defined in BUILD.bazel as well as BUILD files. But it don't work if an external repository have BUILD.bazel.

### Description of the problem:

Here is the sample of using BUILD.bazel file.
https://github.com/lizan/bazel-build-external-samples

Building it with `bazel build //:all` in it works fine.

Create another directory, with WORKSPACE file as following:
```
git_repository(
    name = "examples_cpp",
    remote = "https://github.com/lizan/bazel-build-external-samples",
    commit = "577d40436c6c15aec17a4a9801ded28001805a2f",
)
```

And do `bazel build @examples_cpp//:all` will result:
```
ERROR: while parsing '@examples_cpp//:all': no such package '@examples_cpp//': BUILD file not found on package path.
```

It works just fine if the samples is using BUILD instead of BUILD.bazel, but BUILD.bazel should work too.

### Environment info
* Operating System:
Mac OS X 10.11

* Bazel version (output of `bazel info release`):
Build label: 0.4.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 30 09:13:20 2016 (1480497200)
Build timestamp: 1480497200
Build timestamp as int: 1480497200

**Comment by katre** [comment]
Hmm, that's annoying. I'll investigate and report back shortly.

**Comment by katre** [comment]
Ok, it was a simple oversight, I've sent https://bazel-review.googlesource.com/c/7691/ to fix this.
