### ISSUE TITLE
ci.bazel.io, "bazel" job completely broken

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2200]
http://ci.bazel.io/view/Dashboard/job/Bazel/1076/JAVA_VERSION=1.7,PLATFORM_NAME=darwin-x86_64/console

**Comment by laszlocsomor** [comment]
Suspected culprit:
```
ERROR: Failed to archive artifacts: output/ci/**
java.io.IOException: java.io.IOException: Failed to extract 
...
Caused by: java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
...
Caused by: java.io.IOException: This archives contains unclosed entries.
```

**Comment by laszlocsomor** [comment]
Now linux too.
http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/1077/JAVA_VERSION=1.8,PLATFORM_NAME=linux-x86_64/console

**Comment by laszlocsomor** [comment]
And broken on Windows too. 
http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=windows-x86_64/1077/console

Awesome.

**Comment by aj-michael** [comment]
I don't know if this is relevant, but I reimaged six of the ubuntu slaves last night due to #2195. I would hope that at least those six are not out of space.

**Comment by laszlocsomor** [comment]
Thanks for the info. Meanwhile another job fell over due to "No space left on device", I'm wondering what's going on.

**Comment by laszlocsomor** [comment]
`/volumes` was completely full, so jenkins fell over. I freed up about 50% by deleting old build outputs, which were taking up the vast majority of the disk. This may not have been the best idea because now those build results, including past release builds, are lost. But at least jenkins is back so we have that going for us which is good.

**Comment by laszlocsomor** [comment]
Linux and Darwin are fixed, Windows still failing with error:
```
ERROR: missing input file '@local_jdk//:bin/jar.exe'.
ERROR: C:/jenkins/workspace/Bazel/JAVA_VERSION/1.8/PLATFORM_NAME/windows-x86_64/src/main/protobuf/BUILD:25:2: //src/main/protobuf:build_java_proto_srcjar: missing input file '@local_jdk//:bin/jar.exe'.
____Building complete.
Target //src:bazel failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: C:/jenkins/workspace/Bazel/JAVA_VERSION/1.8/PLATFORM_NAME/windows-x86_64/src/main/java/com/google/devtools/build/lib/BUILD:1094:1 1 input file(s) do not exist.
____Elapsed time: 1.757s, Critical Path: 0.11s
Build step 'Conditional step (single)' marked build as failure
Archiving artifacts
Sending e-mails to: bazel-ci@googlegroups.com
Finished: FAILURE
```

**Comment by laszlocsomor** [comment]
After multiple attempts to reimage the machine, we found out it was hitting a bug in the [jenkins startup script](https://github.com/bazelbuild/continuous-integration/blob/79de9267af8135532eab002e6d83d3e97bda96bd/gce/jenkins-slave-windows.ps1#L86), which I've fixed, and it's good now.

**Comment by laszlocsomor** [comment]
Woohoo, the bazel job is green today! It's a good day so far. ;)
