### ISSUE TITLE
[Mirror] go-containerregistry

### ISSUE THREAD

**Issue by dvgbc** [bazelbuild/bazel#22006]
### Please list the URLs of the archives you'd like to mirror:

github.com/google/go-containerregistry/releases/download/v0.18.0/go-containerregistry_Darwin_x86_64.tar.gz

**Comment by satyanandak** [comment]
Here you go 

https://mirror.bazel.build/github.com/google/go-containerregistry/releases/download/v0.18.0/go-containerregistry_Darwin_x86_64.tar.gz
