### ISSUE TITLE
Building Android Support Libraries spams console with "Cannot stat file..."

### ISSUE THREAD

**Issue by aj-michael** [bazelbuild/bazel#2201]
As of 8d6da00ff0c84d623ccdde7232e0514690d95269, `//third_party/ijar:zipper` logs errors about stat_file failing.

```
$ cat WORKSPACE
android_sdk_repository(
    name = "androidsdk",
    path = "/home/ajmichael/Android/Sdk",
    build_tools_version = "25.0.0",
    api_level = 25,
)
$ cat java/com/foo/BUILD
android_binary(
    name = "foo",
    manifest = "AndroidManifest.xml",
    srcs = ["MainActivity.java"],
    deps = ["@androidsdk//com.android.support:mediarouter-v7-23.4.0"],
)
```

With Bazel built at 645dbc4e24f3c5b08cf4701906f4a1e54db3583b
```
$ devbazel build --spawn_strategy=standalone //java/com/foo
INFO: Found 1 target...
Target //java/com/foo:foo up-to-date:
  bazel-bin/java/com/foo/foo_deploy.jar
  bazel-bin/java/com/foo/foo_unsigned.apk
  bazel-bin/java/com/foo/foo.apk
$
```

With Bazel built at 8d6da00ff0c84d623ccdde7232e0514690d95269
```
$ devbazel build --spawn_strategy=standalone //java/com/foo
INFO: Found 1 target...
INFO: From AarManifestFileEntriesExtractor external/androidsdk/com.android.support/_aar/unzipped/resources/mediarouter-v7-23.4.0:
Cannot stat file /usr/local/google/home/ajmichael/.cache/bazel/_bazel_ajmichael/9edb8580cd9b915d33b825372a03920e/execroot/b/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/external/androidsdk/com.android.support/_aar/unzipped/resources/mediarouter-v7-23.4.0/res: No such file or directory
Cannot stat file /usr/local/google/home/ajmichael/.cache/bazel/_bazel_ajmichael/9edb8580cd9b915d33b825372a03920e/execroot/b/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/external/androidsdk/com.android.support/_aar/unzipped/resources/mediarouter-v7-23.4.0/res/values-el: No such file or directory
Cannot stat file /usr/local/google/home/ajmichael/.cache/bazel/_bazel_ajmichael/9edb8580cd9b915d33b825372a03920e/execroot/b/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/external/androidsdk/com.android.support/_aar/unzipped/resources/mediarouter-v7-23.4.0/res/values-ms-rMY: No such file or directory
Cannot stat file /usr/local/google/home/ajmichael/.cache/bazel/_bazel_ajmichael/9edb8580cd9b915d33b825372a03920e/execroot/b/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/external/androidsdk/com.android.support/_aar/unzipped/resources/mediarouter-v7-23.4.0/res/layout: No such file or directory
[lots more spam here]
Cannot stat file /usr/local/google/home/ajmichael/.cache/bazel/_bazel_ajmichael/9edb8580cd9b915d33b825372a03920e/execroot/b/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/external/androidsdk/com.android.support/_aar/unzipped/resources/appcompat-v7-23.4.0/res/color: No such file or directory
Target //java/com/foo:foo up-to-date:
  bazel-bin/java/com/foo/foo_deploy.jar
  bazel-bin/java/com/foo/foo_unsigned.apk
  bazel-bin/java/com/foo/foo.apk
INFO: Elapsed time: 19.622s, Critical Path: 16.50s
$
```

However, the APKs produced are the same (modulo a known determinism issue with DSA APK signing).

In 8d6da00ff0c84d623ccdde7232e0514690d95269, we started reporting logging this message when zipper stats a file that returns a negative value, instead of just ignoring it and moving to the next. `aar_import` uses zipper to extract the resources from the AAR. I'm not sure what the right course of action here is.

**Comment by laszlocsomor** [comment]
Oh, mea culpa.

https://github.com/bazelbuild/bazel/commit/8d6da00ff0c84d623ccdde7232e0514690d95269#diff-a5eb796bd8c9663be687d472a23b48b9R41 should not have been added. In later commits I started using the [`stat_file`](https://github.com/bazelbuild/bazel/commit/8d6da00ff0c84d623ccdde7232e0514690d95269#diff-a5eb796bd8c9663be687d472a23b48b9R32) method to simply check for file existence. The error message here is a false positive, it should silently return false and that'd be WAI. I'll send out a fix.

**Comment by laszlocsomor** [comment]
I think this is the actual culprit: https://github.com/bazelbuild/bazel/commit/645dbc4e24f3c5b08cf4701906f4a1e54db3583b#diff-69085d3849c04a65812896ac53704713R117

The problem is, I only added the error reporting to `stat_file` in a subsequent commit (8d6da00) but this call was never meant to report a failed `stat`.

**Comment by laszlocsomor** [comment]
@aj-michael: While trying to repro this, I'm hitting problems with my environment setup so I can't build your example, and given the simplicity of the original issue and my certainty in the fix, I won't spend more time on trying to figure out the reasons. Therefore can I ask you that once the fix is out for review or even submitted, to please try it out?

**Comment by aj-michael** [comment]
Thanks Laszlo! I will test the fix out now

**Comment by aj-michael** [comment]
I've confirmed that https://bazel-review.googlesource.com/#/c/7810/ fixes this issue.
