### ISSUE TITLE
[7.2.0] `bazel mod show_repo <canonical repo name>` doesn't work for module extension generated repos.

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22015]
Forked from #21621

**Comment by meteorcloudy** [comment]
https://github.com/bazelbuild/bazel/commit/2d54af169478a42d84d9551fab4b31852e0e85c3 should be cherry-picked

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/22027
