### ISSUE TITLE
commit b12e75767a3530b8bb595b497c61b8423ce35c49 broke compile.sh 

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/bazel#2202]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

commit b12e75767a3530b8bb595b497c61b8423ce35c49 broke running

compile.sh compile `which bazel`

### If possible, provide a minimal example to reproduce the problem:
git checkout HEAD # b12e75767a3530b8bb595b497c61b8423ce35c49
./compile.sh compile `which bazel`
🍃  Building Bazel with Bazel.
INFO: Found 1 target...
ERROR: missing input file '//third_party/java/apksig:apksigner_deploy.jar'.
ERROR: /Users/pbethe/Tools/bazel/src/main/cpp/util/BUILD:26:1: C++ compilation of rule '//src/main/cpp/util:file' failed: sandbox-exec failed: error executing command 
...
and lots more

### Environment info
* Operating System: Mac

* Bazel version (output of `bazel info release`): HEAD

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by aj-michael** [comment]
Sorry about this, I'm currently working on a fix.

**Comment by aj-michael** [comment]
Fixed in e26d26e81db26ab9e3e9d3b5d4602e23d9f50a60
