### ISSUE TITLE
[7.2.0] Fix action key staleness for Args due to type confusion

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22025]
Forked from #21999

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkCustomCommandLine.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkCustomCommandLine.java`
> 
> cc: @bazelbuild/triage

@fmeum @justinhorvitz

**Comment by fmeum** [comment]
Sent https://github.com/bazelbuild/bazel/pull/22088
