### ISSUE TITLE
[7.2.0] Clean up test setup for sandboxing tests

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22029]
Forked from #22002

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/test/shell/bazel/bazel_sandboxing_test.sh`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/22042
