### ISSUE TITLE
[7.2.0] Share Starlark env across module and repo files

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22033]
Forked from #21951

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java`
> 
> cc: @bazelbuild/triage

cc: @Wyverald, @fmeum

**Comment by bazel-io** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/22159
