### ISSUE TITLE
[Mirror] github.com/aspect-build/bazel-lib/releases/download/v1.39.0/copy_to_directory-darwin_amd64 

### ISSUE THREAD

**Issue by dvgbc** [bazelbuild/bazel#22037]
### Please list the URLs of the archives you'd like to mirror:

github.com/aspect-build/bazel-lib/releases/download/v1.39.0/copy_to_directory-darwin_amd64

**Comment by satyanandak** [comment]
Here you go :
https://mirror.bazel.build/github.com/aspect-build/bazel-lib/releases/download/v1.39.0/copy_to_directory-darwin_amd64
