### ISSUE TITLE
[7.2.0] Update blake3 to v1.5.1.bcr.1

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22048]
Forked from #22017

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`MODULE.bazel`
`MODULE.bazel.lock`
`maven_install.json`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `MODULE.bazel` `MODULE.bazel.lock` `maven_install.json`
> 
> cc: @bazelbuild/triage

cc: @fmeum @coeuvre

**Comment by Wyverald** [comment]
https://github.com/bazelbuild/bazel/pull/22300
