### ISSUE TITLE
Crash on startup with Bazel build

### ISSUE THREAD

**Issue by cwoodwar6** [bazelbuild/bazel#2204]
### Description of the problem / question:
I've build the same code base using Gradle, Buck, and now Bazel. Both Gradle and Buck produce a build that can install and run fine. However, the build from Bazel crashes on startup. I'm assuming because of this, it must be something in my Bazel configuration.

The stacktrace is as follows: 
```
12-07 15:56:28.628 3065-3511/system_process W/ActivityManager: Force removing ActivityRecord{4b4cc73 u0 com.example.test/com.example.ui.MainActivity t29}: app died, no saved state
12-07 15:56:28.631 3065-3090/system_process W/WindowManager: Failed looking up window
                                                             java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@2421ae1 does not exist
                                                                 at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8733)
                                                                 at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8724)
                                                                 at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2697)
                                                                 at com.android.server.wm.Session.remove(Session.java:187)
                                                                 at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3099)
                                                                 at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5606)
                                                                 at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3409)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                 at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

My Android binary looks like:
```
android_binary(
    name = 'bin_debug',
    custom_package = 'com.example',
    manifest = 'src/main/AndroidManifest.xml',
    incremental_dexing = 1,
    multidex = "native",
    dex_shards = 25,
    dexopts = [
        "--force-jumbo"
    ],
    manifest_values = {
        'applicationId': 'com.example.test',
        'defaultServerHost': 'example.com',
        'minSdkVersion': '23',
    },
    deps = [
        ':src_debug',
    ],
)
```

I also use the `--experimental_android_use_singlejar_for_multidex` flag when building because I ran into issue #1936.

I've tried modifying the configuration in many different ways. Particularly the dexing options, as I suspect it may be related to dexing because of the logs I've attached. I could be totally wrong, but at this point I'm not sure where to go.

### If possible, provide a minimal example to reproduce the problem:

Don't have a multi-dex application I can share to provide an example.

### Environment info
* Operating System:
MacOS Sierra 10.12.1

* Bazel version (output of `bazel info release`):
release 0.4.2- (@non-git)

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
ba94a7b

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
Nothing directly related to Bazel. Nothing else has proved successful. Searched the issue extensively with no luck.

### Anything else, information or logs or outputs that would be helpful?
Attached additional logcat information that leads me to believe this may be related to dexing.
[logcat.txt](https://github.com/bazelbuild/bazel/files/638075/logcat.txt)

Thank you for taking a look, appreciate any help. I'm stuck at this point and would love to be able to run the app.

**Comment by cwoodwar6** [comment]
Another note, as part of my trying different dex options, I tried manually specifing the main dex. That didn't get me any further.

**Comment by ahumesky** [comment]
So there are at least 3 things going on at the same time: incremental dexing, multidex, and mobile-install. Try turning off multidex if you can, incremental dexing, and build the app normally and install with adb. I suspect mobile-install might be the issue, so if installing with adb works, try mobile-install next.

**Comment by cwoodwar6** [comment]
@ahumesky By build normally I assume you just mean `bazel build app:bin_debug`. The result of doing that or using `mobile-install` without multidex and incremental dexing provides the result `trouble writing output: Too many method references: 219222; max is 65536.`. I definitely need multidex.

**Comment by cwoodwar6** [comment]
I ran `bazel build app:bin_debug` with `multidex = "native"` and no incremental dexing, same crash occurred when I installed with adb.

**Comment by ahumesky** [comment]
Correct, I meant using `bazel build`.

Actually, incremental dexing is not enabled yet in bazel (that the incremental_dexing attribute is documented is an unfortunate mistake). I'm surprised your binary built at all with that on.

I did some internet searching on that error, and it seems that it could be caused by several different things. It's not clear how building with bazel vs buck vs gradle could cause this. What would be most useful is if we had a minimal repro.

**Comment by ahumesky** [comment]
FYI incremental dexing should be fixed, see https://github.com/bazelbuild/bazel/issues/1819

**Comment by aj-michael** [comment]
Hmmm, I haven't seen this before and haven't been able to recreate this error.

@cwoodwar6 , could you `zipinfo` the APKs produced by Gradle and Bazel and either post the results here or let us know any differences you see?

**Comment by cwoodwar6** [comment]
Thanks for the update. I will give incremental dexing a try. If a minimal repro is possible, I will also try to provide that.

**Comment by cwoodwar6** [comment]
Sorry for the delay. I haven't looked at this in a while.

@aj-michael The differences between APKs produced by Gradle & Buck were so significantly different that it was hard to compare them to Bazel to comprehend what could be different.

I'm willing to bet that this may just simply be due to configuration problems. I used the first iteration of OkBazel to generate the configuration.

**Comment by cwoodwar6** [comment]
I'm willing to say this is no longer relevant. It has been a long time since I've tried Bazel and much has changed. Closing for now due to inactivity, will re-open if it ever comes up again.
