### ISSUE TITLE
[7.2.0] Add `pdb_file` and `def_file` output groups to `cc_shared_library`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22053]
Forked from #21900

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/starlark/builtins_bzl/common/cc/cc_shared_library.bzl` `src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/starlark_tests.bzl`
> 
> cc: @bazelbuild/triage

cc: @fmeum, @pzembrod

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/starlark/builtins_bzl/common/cc/cc_shared_library.bzl`
`src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/starlark_tests.bzl`

cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
#22321
