### ISSUE TITLE
[7.2.0] Extract Bazel registry creation into a SkyFunction

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22052]
Forked from #22040

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/bazel/BazelRepositoryModule.java`
`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BUILD`
`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java`
`src/main/java/com/google/devtools/build/lib/skyframe/packages/BazelPackageLoader.java`
`src/test/java/com/google/devtools/build/lib/analysis/util/AnalysisMock.java`
`src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BazelDepGraphFunctionTest.java`
`src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileFunctionTest.java`
`src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModuleResolutionFunctionTest.java`
`src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BzlmodRepoRuleFunctionTest.java`
`src/test/java/com/google/devtools/build/lib/bazel/bzlmod/DiscoveryTest.java`
`src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionResolutionTest.java`
`src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunctionTest.java`
`src/test/java/com/google/devtools/build/lib/rules/repository/RepositoryDelegatorTest.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/bazel/BazelRepositoryModule.java` `src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BUILD` `src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java` `src/main/java/com/google/devtools/build/lib/skyframe/packages/BazelPackageLoader.java` `src/test/java/com/google/devtools/build/lib/analysis/util/AnalysisMock.java` `src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BazelDepGraphFunctionTest.java` `src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileFunctionTest.java` `src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BazelModuleResolutionFunctionTest.java` `src/test/java/com/google/devtools/build/lib/bazel/bzlmod/BzlmodRepoRuleFunctionTest.java` `src/test/java/com/google/devtools/build/lib/bazel/bzlmod/DiscoveryTest.java` `src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionResolutionTest.java` `src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunctionTest.java` `src/test/java/com/google/devtools/build/lib/rules/repository/RepositoryDelegatorTest.java`
> 
> cc: @bazelbuild/triage

cc: @fmeum, @Wyverald

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/22138 by @Wyverald
