### ISSUE TITLE
CLI tooling for patching external dependencies

### ISSUE THREAD

**Issue by jgao54** [bazelbuild/bazel#22059]
### Description of the feature request:

Similar to PNPM’s built-in[ `pnpm patch` command](https://pnpm.io/cli/patch), it would be awesome to have the CLI tooling to support patching bazel's external dependencies.

API:
`bazel patch`: create a copy of the external dependency for edits
`bazel patch-commit`: apply the patch to the dependency
`bazel patch-remove`: remove the patch to the dependency

### Which category does this issue belong to?

External Dependency

### What underlying problem are you trying to solve with this feature?

Make a better user experience for patching external dependencies.

**Comment by meteorcloudy** [comment]
The MODULE.bazel file will be the source of truth for external dependencies in Bazel. It's highly unlikely we'll work on some features like this.

**Comment by fmeum** [comment]
I would say this would be very useful to have, but could very well be a separate tool built on buildozer and interacting with the BCR directly. There really isn't much benefit to building this into Bazel.

**Comment by meteorcloudy** [comment]
Yeah, it'll be nice to have some toolings to prepare patch files that can be used in BCR or MODULE.bazel, and I agree it shouldn't be part of Bazel.

@jgao54 Feel free to open an issue to https://github.com/bazelbuild/buildtools
