### ISSUE TITLE
Can we make aquery support --target_pattern_file parameters?

### ISSUE THREAD

**Issue by st0rm23** [bazelbuild/bazel#22062]
### Description of the feature request:

Currently, we are not able to execute `bazel aquery` with `--target_pattern_file` options. It is not very convenience when we have large number of target to query.

The current execution result is empty
```
bazel aquery --target_pattern_file=/tmp/targets
Loading:
```
 

### What underlying problem are you trying to solve with this feature?

we hope aquery can query a list of targets

### Which operating system are you running Bazel on?

Ubuntu 20.04

### What is the output of `bazel info release`?

6.4.0

### Have you found anything relevant by searching the web?

no

**Comment by st0rm23** [comment]
I found a workaround. use --query_file option to construct something like `deps(//target_a + //target_b + ...)`

But it is not very easy to use,  query_file does not support multiple lines and does not support - (exclude) operator

**Comment by joeleba** [comment]
Thanks for filing the feature request. Realistically speaking we're not planning to support this, since it does not fit very nicely with our existing query/filter syntax.
