### ISSUE TITLE
Hang on error in repo rule, regression in 7.1.0rc2

### ISSUE THREAD

**Issue by peakschris** [bazelbuild/bazel#22060]
### Description of the bug:

We are facing a hang (intermittent, approximately every 5 invocations of bazel) when it is run and there is an error in a repo rule, or an error in a build file referencing a non-existent repo. This occurs on both Windows and Linux. Control-C does not stop bazel - the output from infinitely fetching other repos continues to flood the command line. The only solution is to kill the bazel process using 'kill'

The issue first occurred for us in 7.1.0rc2, due to this flag default change: https://github.com/bazelbuild/bazel/pull/21082

- 7.1.0rc1 with --experimental_worker_for_repo_fetching=virtual - problem not seen
- 7.1.0rc2 with --experimental_worker_for_repo_fetching=virtual - problem occurs
- 7.1.0rc2 with --experimental_worker_for_repo_fetching=off - problem not seen

So it seems there are two separate changes in 7.1.0rc2 that are affecting us:
- the flag default was changed
- a bug appeared in the logic

Again, this issue *only* appears if there is a bug in one of the repo configurations that would cause an error to be displayed under normal conditions. The desired behaviour is that bazel shows this error and stops without hanging.

I don't have a minimal reproducer at this time, this is occurring in a very large repo with many repo rules.

Thanks! Chris

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Add a reference from rules_oci in a build file to a base image repo that does not exist. Have many other repos to fetch as well. Run bazel multiple times, most will show an error and stop, occasionally there will be a hang.

### Which operating system are you running Bazel on?

windows and redhat

### What is the output of `bazel info release`?

release 7.1.0rc2 and release 7.1.1

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

This issue occurs in:
7.1.0rc2
7.1.1
development version (.bazelversion=last_green)

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Yes, regressed from 7.1.0rc1 to 7.1.0rc2. Hard to bisect as it is intermittent

**Comment by peakschris** [comment]
Bazelisk isn't working by individual hash for me, am I doing it right?

```
2024/04/19 07:31:27 Using unreleased version at commit e7ad3748aca9553309d9eaf2e88dabf476a940af
2024/04/19 07:31:27 Downloading https://storage.googleapis.com/bazel-builds/artifacts/centos7/e7ad3748aca9553309d9eaf2e88dabf476a940af/bazel...
2024/04/19 07:31:27 could not download Bazel: failed to download bazel: failed to download bazel: HTTP GET https://storage.googleapis.com/bazel-builds/artifacts/centos7/e7ad3748aca9553309d9eaf2e88dabf476a940af/bazel failed with error 404
```

**Comment by peakschris** [comment]
It also isn't working by individual hash on windows

**Comment by fmeum** [comment]
I can't find that particular commit in the Bazel project, but `USE_BAZEL_VERSION=567e434101d60ef865aa55b1f6539a7c539ef872` works for me.

**Comment by peakschris** [comment]
Thanks for that,

https://github.com/bazelbuild/bazel/commit/c43ace2a9644c262be41c0d25c867161d7cfd903 doesn't have the issue
https://github.com/bazelbuild/bazel/commit/567e434101d60ef865aa55b1f6539a7c539ef872 has the issue

Chris

**Comment by fmeum** [comment]
cc @Wyverald

**Comment by Wyverald** [comment]
Thank you! Could you try and see if https://github.com/bazelbuild/bazel/commit/f93ef2d2725836f8a2ac89a0a7d7ba50e6611584 fixes your problem?

**Comment by peakschris** [comment]
Yes, this does seem to fix the problem! Good news!

**Comment by Wyverald** [comment]
Good to know! To help me understand better, do you set `--keep_going` anywhere in your .bazelrc? I was under the impression that such deadlocks can only happen with `--keep_going`, so it would be good to confirm that.

**Comment by peakschris** [comment]
No, I don't use --keep_going anywhere in .bazelrc or on command line.

**Comment by Wyverald** [comment]
I see, thanks. I'll go ahead and close this.

**Comment by peakschris** [comment]
Will the fix be picked into next release? Is some action needed to ensure that? Thanks!
