### ISSUE TITLE
ctx.action's command argument requires 3 strings in lists without good documentation why

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#2207]
I'm getting errors like:

```
ERROR: /Users/endobson/proj/racket/yaspl2/libraries/BUILD:734:1: in yaspl_library rule //libraries:true_lib:
Traceback (most recent call last):
        File "/Users/endobson/proj/racket/yaspl2/libraries/BUILD", line 734
                yaspl_library(name = 'true_lib')
        File "/Users/endobson/proj/racket/yaspl2/libraries/yaspl.bzl", line 31, in _lib_impl
                ctx.action(inputs = [ctx.outputs.object], out...], <2 more arguments>)
'command' list has to be of size at least 3.
```

This is coming from the check defined here:
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/SkylarkRuleImplementationFunctions.java#L273

But there doesn't seem to be good reason for the check. The underlying SpawnAction only requires there to be at least one argument for the executable.

**Comment by laurentlb** [comment]
This limitation has been removed.

The function is also deprecated, see the replacements:
 - `ctx.actions.run_shell`: https://docs.bazel.build/versions/master/skylark/lib/actions.html#run_shell
 - `ctx.actions.run`: https://docs.bazel.build/versions/master/skylark/lib/actions.html#run
