### ISSUE TITLE
[Skymeld] Symlink planting for external repos races against action execution

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#22073]
### Description of the bug:

When Skymeld is enabled, execroot symlinks for the root of external repositories are created when a `TopLevelTargetReadyForSymlinkPlanting` event is fired and received by `IncrementalPackageRoots#topLevelTargetReadyForSymlinkPlanting`. Notably, there is no happens-before relationship between the actual filesystem operation creating the symlink and the execution of dependent actions, which results in a race that can result in the symlink not being available during action execution, thus causing an `IOException`.

### Which category does this issue belong to?

Core

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Increase the likelihood of action execution winning the race by inserting `Thread.sleep(10000)` before line https://cs.opensource.google/bazel/bazel/+/d8613c222f233406165c623b1a92179faed142ba:src/main/java/com/google/devtools/build/lib/buildtool/SymlinkForest.java;l=474.
2. Run `bazel build //...` in https://github.com/bazelbuild/examples/tree/main/frontend.

This should reliably reproduce https://github.com/bazelbuild/examples/issues/421.

### Which operating system are you running Bazel on?

Any

### What is the output of `bazel info release`?

HEAD

**Comment by fmeum** [comment]
Cc @joeleba

**Comment by joeleba** [comment]
Thanks for filing the bug. I'll look into this.

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by iancha1992** [comment]
@bazel-io fork 7.2.0

**Comment by fmeum** [comment]
It's not unlikely that this is also the cause of https://github.com/bazelbuild/bazel/issues/20886.

**Comment by joeleba** [comment]
Update: I expect to have a fix submitted sometime this week.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.2.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.2.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.2.0rc1. Thanks!
