### ISSUE TITLE
[7.2.0] Bazel 7 crashes if coverage report is a tree artifact

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22091]
Forked from #22069

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/skyframe/SkyframeActionExecutor.java`

cc: @bazelbuild/triage

**Comment by tjgq** [comment]
The merge conflict was expected; I'll do a manual cherry-pick.
