### ISSUE TITLE
[7.2.0] Revert special handling of yanked module files

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22096]
Forked from #22083

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java`
> 
> cc: @bazelbuild/triage

cc: @fmeum @Wyverald @meteorcloudy

**Comment by bazel-io** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/22263
