### ISSUE TITLE
How to modify the default toolchain and important options  for building android native library .

### ISSUE THREAD

**Issue by nxty2011** [bazelbuild/bazel#2209]
### Description of the question:

Hi, I want to build a dynamic library with hard float abi for android platform on arm v7.  But I do not know how to modify the default toolchain from `external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9` to ` external/androidndk/ndk/toolchains/arm-linux-androideabi-4.8` and important options from `softfp` abi to `hard-float` abi  for building android native library .

### Simple example to reproduce the problem:
- Add `android_ndk_repository` in `WORKSPACE` file.

- Build the hello_world project in [android example,](https://github.com/bazelbuild/bazel/blob/master/examples/android/java/bazel/BUILD) it will succeed.

- Bazel always use the `external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9` toolchains and  `softfp` abi , even if I had added the option `--cpu=armeabi-v7a-hard` or set copts via `--copts="  D_NDK_MATH_NO_SOFTFP=1", --copts="-mhard-float"`. Because I built example with `-s` option, I always got the following building commands:

```
 exec env - \
  external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-
androideabi-gcc -fstack-protector-strong -fpic -ffunction-sections -funwind-tables -no-canonical-prefixes 
-fno-canonical-system-headers '-march=armv7-a' '-mfpu=vfpv3-d16' '-mfloat-abi=softfp' -MD -MF ...
```

### Environment info
* Operating System: Ubuntu 14.04

* Bazel version (output of `bazel info release`): release 0.4.0

I have checked this problem about two days, the most related description are

- https://github.com/tensorflow/tensorflow/issues/3444

- https://github.com/moul/bazel-examples/tree/master/android-prebuilts

Any suggestions would be appreciated. Thank you.

**Comment by ahumesky** [comment]
Support for the armeabi-v7a-hard ABI was removed in NDK r12:
https://developer.android.com/ndk/downloads/revision_history.html
They gave this link for more infomation:
https://android.googlesource.com/platform/ndk/+/ndk-r12-release/docs/HardFloatAbi.md

Bazel defaults to armeabi-v7a for building native code for android, is this enough?

**Comment by ahumesky** [comment]
Also, the reason that --copt didn't seem to be working may have been because cc rules use a different set of flags when they are built as dependencies of android_binary rules. This is so that base libraries can be built for both android targets and other targets in the same build. When a cc library is built normally, it's governed by --cpu, --crosstool_top, --compiler, and --copt (among others). When a cc library is built as a dependency of an android_binary, it's built using --fat_apk_cpu, --android_crosstool_top, and --android_compiler. There is unfortunately no equivalent for --copt, so the other option is to set the options using the copts attribute of the libraries themselves. This is all very subtle and we're working on better documentation for all this.

**Comment by nxty2011** [comment]
- In fact, after I modified the option `--fat_apk_cpu` to  target architecture, the toolchain changed indeed, and so did the compiling flag.

- What confused me is that it seems in no way could I modify the version of the toolchain and the flags of the compiling process.

- It is somewhat lack for documents of this part in bazel. Quit looking forward.

Thank you.

**Comment by ahumesky** [comment]
> Last, what confused me is that it seems in no way could I modify the version of the toolchain and the flags of the compiling process. Could I?

With NDK r12, you can select gcc-4.9 with `--android_compiler=gcc-4.9` and clang 3.8 with `--android_compiler=clang3.8`. To change the flags, you can use the [`copts`](https://bazel.build/versions/master/docs/be/c-cpp.html#cc_library.copts) and [`linkopts`](https://bazel.build/versions/master/docs/be/c-cpp.html#cc_library.linkopts) attributes of `cc_library`

**Comment by nxty2011** [comment]
Thank you so much, I guess it is enough to close this issue, right?

**Comment by ahumesky** [comment]
Yep, thanks, please feel free to reach out on the [mailing list](https://groups.google.com/forum/#!forum/bazel-discuss) for any other questions you may have.
