### ISSUE TITLE
[7.2.0] Replace most Bzlmod events with a Skyframe graph lookup

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22107]
Forked from #22058

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileModule.java`
`src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionResolutionTest.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileModule.java` `src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionResolutionTest.java`
> 
> cc: @bazelbuild/triage

cc: @fmeum @justinhorvitz @Wyverald

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileModule.java`

cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
https://github.com/bazelbuild/bazel/pull/22265
