### ISSUE TITLE
Java: overriding getter on a record results in "reference to <getter> is ambiguous

### ISSUE THREAD

**Issue by MorganRoff-UnlikelyAI** [bazelbuild/bazel#22105]
### Description of the bug:

This is similar to https://github.com/bazelbuild/bazel/issues/17181

According to [Oracle's docs](https://docs.oracle.com/en/java/javase/17/language/records.html#GUID-6699E26F-4A9B-4393-A08B-1E47D4B2D263) (see the section "Explicit Declaration of Record Class Members"), redefining a getter on a Java record should override the default implementation.

For example:

```java
public record Foo(int bar, List<String> baz) {
  /** This should override the default baz() getter. */
  public List<String> baz() {
    return baz == null ? new ArrayList<>() : baz;
  }
}
```

However, when I try to build this with Bazel, I get `error: reference to <getter> is ambiguous`. In contrast, the build succeeds as expected with Maven.

My .bazelrc options:
`common --java_language_version=17 --java_runtime_version=local_jdk_17 --tool_java_language_version=17 --tool_java_runtime_version=local_jdk_17`

I also tried importing the latest `java_tools` release into my WORKSPACE file to fix this, based on the resolution in
`https://github.com/bazelbuild/bazel/issues/17181`, but I'm still seeing this error.

### Which category does this issue belong to?

Java Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create one java_library with a record that overrides a getter, as demonstrated above.

Create another java_library with a source that tries to use that getter.

### Which operating system are you running Bazel on?

ubuntu 22.04.1

### What is the output of `bazel info release`?

release 7.1.1

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Uncertain, we have not used Bazel to build this code before.

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/17181

**Comment by fmeum** [comment]
cc @cushon

**Comment by cushon** [comment]
This will be resolved once there's a new java_tools and rules_java release (https://github.com/bazelbuild/bazel/pull/22310)
