### ISSUE TITLE
Repository rules should not re-fetch when .netrc changes

### ISSUE THREAD

**Issue by mortenmj** [bazelbuild/bazel#22118]
### Description of the feature request:

The http_archive/file/jar rules read the user's .netrc file in order to authenticate, as of 7.1.0. Presumably as a consequence of this, the netrc file appears in external repo marker files. This means that changes to the netrc file cause re-fetching of these dependencies.

### Which category does this issue belong to?

External Dependency

### What underlying problem are you trying to solve with this feature?

Changes to .netrc should not cause re-fetching of external dependencies that have been successfully fetched.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 7.1.1

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.1.2 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.1.2rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.1.2rc1. Thanks!
