### ISSUE TITLE
Poor error message when overriding BCR to invalid path

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#22111]
### Description of the bug:

If you pass `--registry=file:///bogus/dir`, the error you get is that some random dependency isn't found in the registry:

```
ERROR: Error computing the main repository mapping: in module dependency chain <root> -> googletest@1.14.0.bcr.1: module not found in registries: googletest@1.14.0.bcr.1
```

This makes it sound like you might just need to `git pull` or something in your registry. I think ideally it would be more clear that the root dir, or modules dir, or something similar just don't exist.

### What is the output of `bazel info release`?

release 7.1.1

**Comment by Wyverald** [comment]
Dupe of https://github.com/bazelbuild/bazel/issues/21541; I'm also not sure this is actionable at all.

**Comment by keith** [comment]
seems like for a file one just the dir existing should be a requirement? harder in the networking case
