### ISSUE TITLE
ActionOwner and aspects-on-aspects don't work well together

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#2211]
`ActionOwner` only contains the identifier of one aspect:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/actions/ActionOwner.java#L47

Which means that if the same aspect is computed twice (once for a configured target directly and once with another aspect in between), its `ActionOwner`s are going to be equal, which is bad.

This was introduced in https://github.com/bazelbuild/bazel/commit/ca9bfa433a549a0828d0c711786217983c82f455 (reviewed and the issue duly missed by Yours Truly :( )

**Comment by lberki** [comment]
@janakdr might also want to know about this.

**Comment by cgrushko** [comment]
@dslomov do you feel like taking a stab at this? :)

**Comment by damienmg** [comment]
@dslomov this seems a bit far-fetched for end of January, do you think this can be done by 0.5?

**Comment by dslomov** [comment]
Absolutely. It is quite an easy fix

**Comment by dslomov** [comment]
Fixed in https://github.com/bazelbuild/bazel/commit/1575652972d80f224fb3f7398eef3439e4f5a5dd
