### ISSUE TITLE
[7.2.0] Allow `native.package_relative_label` in initializers

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22113]
Forked from #21740

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/packages/StarlarkNativeModule.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/packages/StarlarkNativeModule.java`
> 
> cc: @bazelbuild/triage

cc: @fmeum @comius @brandjon

**Comment by Wyverald** [comment]
#22321
