### ISSUE TITLE
[7.2.0] Detect extension staleness due root module name/version change

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22124]
Forked from #22123

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `MODULE.bazel.lock` `src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileModule.java` `src/test/tools/bzlmod/MODULE.bazel.lock`
> 
> cc: @bazelbuild/triage

cc: @fmeum @Wyverald @meteorcloudy

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`MODULE.bazel.lock`
`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileModule.java`
`src/test/tools/bzlmod/MODULE.bazel.lock`

cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
https://github.com/bazelbuild/bazel/pull/22282
