### ISSUE TITLE
Module extension isn't rerun when root MODULE.bazel's `module` is changed

### ISSUE THREAD

**Issue by calebzulawski** [bazelbuild/bazel#22121]
### Description of the bug:

I have a module extension that reads the name and version of the root module.  When the `module` values are changed, the module extension is not rerun.  Adding `return ctx.extension_metadata(reproducible = True)` causes the extension to rerun.

cc @fmeum 

### Which category does this issue belong to?

External Dependency

### Which operating system are you running Bazel on?

Ubuntu

### What is the output of `bazel info release`?

release 7.1.1

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.2.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.2.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.2.0rc1. Thanks!
