### ISSUE TITLE
[7.2.0] Let `Label#debugPrint` emit label strings in display form

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22136]
Forked from #21963

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/analysis/BazelRuleAnalysisThreadContext.java`
`src/main/java/com/google/devtools/build/lib/analysis/config/StarlarkDefinedConfigTransition.java`
`src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryFunction.java`
`src/main/java/com/google/devtools/build/lib/cmdline/BazelStarlarkContext.java`
`src/main/java/com/google/devtools/build/lib/cmdline/Label.java`
`src/main/java/com/google/devtools/build/lib/cmdline/PackageIdentifier.java`
`src/main/java/com/google/devtools/build/lib/packages/BzlInitThreadContext.java`
`src/main/java/com/google/devtools/build/lib/packages/Package.java`
`src/main/java/com/google/devtools/build/lib/packages/PackageFactory.java`
`src/main/java/com/google/devtools/build/lib/packages/StarlarkCallbackHelper.java`
`src/main/java/com/google/devtools/build/lib/packages/TargetDefinitionContext.java`
`src/main/java/com/google/devtools/build/lib/skyframe/BzlLoadFunction.java`
`src/main/java/com/google/devtools/build/lib/skyframe/PackageFunction.java`
`src/test/java/com/google/devtools/build/lib/packages/PackageTest.java`
`src/test/java/com/google/devtools/build/lib/packages/RuleClassTest.java`
`src/test/java/com/google/devtools/build/lib/packages/RuleFactoryTest.java`
`src/test/java/com/google/devtools/build/lib/starlark/util/BazelEvaluationTestCase.java`

cc: @bazelbuild/triage

**Comment by keertk** [comment]
@Wyverald mind submitting a PR for this one?

**Comment by fmeum** [comment]
I sent https://github.com/bazelbuild/bazel/pull/22460.
