### ISSUE TITLE
[7.2.0] aquery: interpret "//foo:bar" as "all configured targets with label //foo:bar"

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#22134]
### Commit IDs

0662df0506507d872e1243c243719aeba72e6a3e

### Category

team-Configurability

### Reviewers

@Wyverald

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/22135: https://github.com/bazelbuild/bazel/commit/0662df0506507d872e1243c243719aeba72e6a3e.
