### ISSUE TITLE
Investigate seccomp-bpf for sandboxing

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#2213]
This might be an alternative to pid + mount namespaces.

**Comment by ulfjack** [comment]
If we've looked into it already, it would be good to document that somewhere (in the sandboxing design doc?).

**Comment by jmmv** [comment]
Closing as stale. Maybe we should do this, but currently have no plans. Any context would have to come from @philwo though as I have no idea if this was looked at in the past.
