### ISSUE TITLE
[Mirror] with_cfg v0.2.4

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#22144]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/fmeum/with_cfg.bzl/releases/download/v0.2.4/with_cfg.bzl-v0.2.4.tar.gz

**Comment by satyanandak** [comment]
Here you go
https://mirror.bazel.build/github.com/fmeum/with_cfg.bzl/releases/download/v0.2.4/with_cfg.bzl-v0.2.4.tar.gz
