### ISSUE TITLE
[7.2.0] Fix maven deps after 5e63f2d

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22146]
Forked from #22145

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`MODULE.bazel`
`MODULE.bazel.lock`
`maven_install.json`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `MODULE.bazel` `MODULE.bazel.lock` `maven_install.json`
> 
> cc: @bazelbuild/triage

cc: @fmeum @meteorcloudy

**Comment by Wyverald** [comment]
https://github.com/bazelbuild/bazel/pull/22266
