### ISSUE TITLE
[7.2.0] Windows: Inconsistent escaping for run --script_path

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22150]
Forked from #21940

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/runtime/commands/RunCommandLine.java`
`src/test/java/com/google/devtools/build/lib/runtime/commands/RunCommandLineTest.java`
`src/test/shell/integration/run_test.sh`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
cc: @fmeum

**Comment by iancha1992** [comment]
> cc: @fmeum



> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/runtime/commands/RunCommandLine.java` `src/test/java/com/google/devtools/build/lib/runtime/commands/RunCommandLineTest.java` `src/test/shell/integration/run_test.sh`
> 
> cc: @bazelbuild/triage

cc: @fmeum

**Comment by fmeum** [comment]
@iancha1992 Let's close this one, it does seem to need prerequisites I'm not familiar with.

**Comment by iancha1992** [comment]
Sure.

cc: @meisterT @tjgq
