### ISSUE TITLE
Release notes: missed a release note from 0.4.2 -- bug in script?

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2216]
### Description of the problem / feature request / question:

The release notes generator failed to include the relnotes of https://github.com/bazelbuild/bazel/commit/ed7ced0018dc5c5ebd6fc8afc7158037ac1df00d in the relnotes of [0.4.2](https://github.com/bazelbuild/bazel/releases/tag/0.4.2), I don't know why.

**Comment by damienmg** [comment]
0.4.2 had several issues with the relnotes. Let's follow-up closely 0.4.3. Also ed7ced0 was rolled-back and rolled-forward, maybe the rollback detection got messed-up.

**Comment by damienmg** [comment]
Marking as release blocker so we follow-up during the release.

**Comment by laszlocsomor** [comment]
@iirina: FYI @damienmg's first comment

**Comment by damienmg** [comment]
Closing as can't reproduce.
