### ISSUE TITLE
set |= set operator missing

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2217]
### Description of the problem / feature request / question:

Currently in Skylark I seem not to be able to extend a set in place with `|=`.

### If possible, provide a minimal example to reproduce the problem:

    foo = set()
    bar = set()

    foo |= bar

### Environment info
* Bazel version (output of `bazel info release`): 0.4.2

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
Nope

**Comment by iirina** [comment]
Hi Andreas,

The Skylark [sets](https://www.bazel.io/versions/master/docs/skylark/lib/set.html) are not the same as python `sets`, but a Skylark custom data type. This is why you can not do `foo |= bar`. You could use instead the `|` operator or the `union` method.

**Comment by abergmeier-dsfishlabs** [comment]
@iirina I know that and the implementation. Still I think it eventually should match feature wise 😄 .

**Comment by dslomov** [comment]
We will be removing binary operators on depsets (formerly sets) because they do not work very well.
@brandjon @laurentlb

**Comment by abergmeier-dsfishlabs** [comment]
@dslomov noticed that but did not follow that in depth - is there a "ordinary" set by now?

**Comment by dslomov** [comment]
Not yet,  you can use dict with None keys though.
