### ISSUE TITLE
Windows: implement java launcher

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2218]
The current java launcher is a shell script.
In order to implement https://github.com/bazelbuild/bazel/issues/2107, we need to come up with a different launcher -- native C++ launcher app, powershell script, batch file, something.

**Comment by abergmeier-dsfishlabs** [comment]
I vote for PowerShell unless startup times get too bad.

**Comment by damienmg** [comment]
I vote for C++ to have only one code to rule them all :) Python would be ok too but add a dependency to python for the Java rule so I'd rather not.

Also if C++ then we can use the JVM interface to launch the JVM in the same process.

**Comment by laszlocsomor** [comment]
@damienmg: That's a really interesting idea, launching the java_binary in-process. This would mean we save the cost of a JVM startup, but also the app or bazel crashing would crash the other -- not necessarily good.

**Comment by abergmeier-dsfishlabs** [comment]
> I vote for C++ to have only one code to rule them all :) Python would be ok too but add a dependency to python for the Java rule so I'd rather not.

Actually another reason to not use PowerShell is that there seems to be some policy that prevents Scripts from being executed by the user (the usual Windows policy hell). We currently wrap our PowerShell inside of batches to workaround that.

**Comment by petemounce** [comment]
Yes, for powershell one has to usually get the user to change their `ExecutionPolicy` to something more lenient than the default `Restricted`. But of course, I think one can just shell out to cmd to call powershell.exe to do that pretty silently 🙄 . https://technet.microsoft.com/en-us/library/ee176961.aspx

**Comment by laszlocsomor** [comment]
@meteorcloudy made great progress with this already, see https://github.com/bazelbuild/bazel/commit/09dd8c0330a3e18951d9481751ef99d3668115c0

**Comment by laszlocsomor** [comment]
Is there anything else to do with this bug? The native launcher is the default and working well.

**Comment by meteorcloudy** [comment]
54c5c5cf41bd47d11ea309f37697d83ae65fe9e7 should have closed this bug ;)
