### ISSUE TITLE
[Mirror] rules_graalvm & apple_support

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#22194]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/sgammon/rules_graalvm/releases/download/v0.11.2/rules_graalvm-0.11.2.zip
https://github.com/bazelbuild/apple_support/releases/download/1.15.1/apple_support.1.15.1.tar.gz

**Comment by satyanandak** [comment]
Here you go 
https://mirror.bazel.build/github.com/sgammon/rules_graalvm/releases/download/v0.11.2/rules_graalvm-0.11.2.zip
https://mirror.bazel.build/github.com/bazelbuild/apple_support/releases/download/1.15.1/apple_support.1.15.1.tar.gz
