### ISSUE TITLE
`bazel fetch` does not support target subtraction

### ISSUE THREAD

**Issue by aj-michael** [bazelbuild/bazel#2220]
```
$ bazel info release
release 0.4.2

$ tree
.
├── a
│   ├── b
│   │   └── BUILD
│   └── BUILD
└── WORKSPACE
2 directories, 3 files

$ cat a/BUILD
java_library(
    name = "a",
    srcs = [],
)

$ cat b/BUILD
cat: b/BUILD: No such file or directory

$ cat a/b/BUILD
java_library(
    name = "b",
    srcs = [],
)

$ bazel build -- //a/... -//a/b/...                                                                  
INFO: Found 1 target...
Target //a:a up-to-date:
  bazel-bin/a/liba.jar
INFO: Elapsed time: 0.132s, Critical Path: 0.00s

$ bazel fetch -- //a/... -//a/b/...
ERROR: Error while parsing 'deps(//a/... union -//a/b/... union @bazel_tools//tools/jdk:toolchain)': syntax error at '- //a/b/... union'.
```

Target subtraction is documented [here](https://www.bazel.io/docs/command-line-reference.html).
The relevant code is [here](https://github.com/bazelbuild/bazel/blob/873c259abc01b84524cc4280f0f8ddd5a4e90e62/src/main/java/com/google/devtools/build/lib/bazel/commands/FetchCommand.java#L101).

**Comment by aj-michael** [comment]
A hacky workaround at the moment is `bazel fetch "//a/... -//a/b/..."`.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
