### ISSUE TITLE
http.bzl : all_urls is given the remote_patch URL which is surely a mistake.

### ISSUE THREAD

**Issue by fzakaria** [bazelbuild/bazel#22201]
### Description of the bug:

_all_urls_ includes the _remote_patch_ URL key for http_archive.
This value is passed to downlolad_and_extract which is a bug.

This means that if the original URLs for the http_archive fail, it will treat the remote_patch as the URL for the archive itself.

Please see: https://github.com/bazelbuild/bazel/blob/0e7c0fb91eb6d6fd0f7a4e4bddf734569a9dd3b3/tools/build_defs/repo/http.bzl#L141

This came up during my writing of PR #22155 

CC @Wyverald

**Comment by Wyverald** [comment]
ah, indeed -- looks like this was accidentally introduced in https://github.com/bazelbuild/bazel/commit/445dfab8fdd7671fe6206ea938ef119c228019f0. We should take the remote patch URLs into account for auth, but not actually download the patches together with the main archive.

**Comment by meteorcloudy** [comment]
Sorry for the oversight! I'll work on a fix for this..
