### ISSUE TITLE
[swift] use -import-underlying-module flag

### ISSUE THREAD

**Issue by fkorotkov** [bazelbuild/bazel#2221]
### Description of the problem / feature request / question:

Xcode uses `-import-underlying-module` to avoid specifying explicit imports to frameworks like `Foundation`. It will be handy to pass it from bazel as well.

### If possible, provide a minimal example to reproduce the problem:

I've created a small project: https://github.com/fkorotkov/bazel-sandbox/tree/7c91c60bb0d789129e11bbcb1329c4dca196e253

When I run `bazel build //...` I see:

```
import-underlying-module/Foo.swift:4:13: error: use of undeclared type 'NSThread'
class Foo : NSThread {
            ^~~~~~~~
```

But Xcode can build a similar project by using `-import-underlying-module` flag.

Once I added `copts = ['-import-underlying-module']` I saw `error: underlying Objective-C module 'Foo' not found` because it seems a modulemap should be passed in order to use `-import-underlying-module` flag.

### Environment info
* Operating System: Mac OS X 10.12
* Bazel version (output of `bazel info release`): 0.4.2

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

https://github.com/bazelbuild/bazel/pull/1784

**Comment by iirina** [comment]
@c-parsons can you take a look?

**Comment by dmishe** [comment]
There can be no Objective-C half of the module in swift_library since we don't allow mixed sources, and currently there is no way to ship a mixed Objc/Swift framework from bazel. 
I guess that this option just triggers something else that happen to import Foundation?

In any case, importing everything (and that means Foundation and UIKit too :)) you use explicitly is a good thing and we strive to do that more and more.

**Comment by afking** [comment]
@dmishe any updates on support for mixed swift/objc libraries? When will it be possible for Bazel to build iOS apps with swift?

**Comment by dmishe** [comment]
It is possible, you just have Objective-C sources in an objc_library, and Swift sources in swift_library.

**Comment by keith** [comment]
This should be closed and be tracked here instead https://github.com/bazelbuild/rules_apple/issues/240
