### ISSUE TITLE
[7.2.0] Automatically map paths in `Args#map_each`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22221]
Forked from #21952

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/actions/PathMapper.java`
`src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkCustomCommandLine.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/actions/PathMapper.java` `src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkCustomCommandLine.java`
> 
> cc: @bazelbuild/triage

cc: @fmeum @aranguyen @lberki

**Comment by keertk** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/22322
