### ISSUE TITLE
[7.2.0] Avoid Windows short paths in Bzlmod

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22224]
Forked from #22219

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`MODULE.bazel.lock`
`src/test/java/com/google/devtools/build/lib/analysis/StarlarkRuleTransitionProviderTest.java`
`src/test/java/com/google/devtools/build/lib/skyframe/config/PlatformMappingFunctionParserTest.java`
`src/test/java/com/google/devtools/build/lib/skyframe/config/PlatformMappingValueTest.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `MODULE.bazel.lock` `src/test/java/com/google/devtools/build/lib/analysis/StarlarkRuleTransitionProviderTest.java` `src/test/java/com/google/devtools/build/lib/skyframe/config/PlatformMappingFunctionParserTest.java` `src/test/java/com/google/devtools/build/lib/skyframe/config/PlatformMappingValueTest.java`
> 
> cc: @bazelbuild/triage

cc: @fmeum @Wyverald

**Comment by Wyverald** [comment]
https://github.com/bazelbuild/bazel/pull/22326
