### ISSUE TITLE
[Mirror] ruff 0.1.6

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#22223]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/astral-sh/ruff/releases/download/v0.1.6/ruff-aarch64-apple-darwin.tar.gz

**Comment by satyanandak** [comment]
Here you go
https://mirror.bazel.build/github.com/astral-sh/ruff/releases/download/v0.1.6/ruff-aarch64-apple-darwin.tar.gz
