### ISSUE TITLE
JSON profile shows actions before the start of the build when there are long-running remote-executed builds

### ISSUE THREAD

**Issue by tbaing** [bazelbuild/bazel#22234]
### Description of the bug:

Our builds have long-running actions, often taking 10-30 minutes per action in a build that can take several hours total. We run builds every 30 minutes in our CI system, so when two successive builds execute, sometimes it turns out that build 1 is in the middle of executing a long-running action when build 2 starts. Because we execute these actions remotely, when build 2 reaches that action it will request that the action executes remotely in RBE, and RBE will deduplicate the actions and return the result to build 2 at the same time it's returned to build 1.

However, in this situation we've found that the JSON profile contains an `execute` span that corresponds to the amount of time that the full remote execution took, which means that we have an action that started before build 2 began. When this profile is loaded into Perfetto, the offsets for all actions are then computed relative to the start time of this already-started action instead of the time that the build actually started, which is confusing and requires us to do additional mental arithmetic to map the data in Perfetto to wall-clock times.

![Perfetto_span_before_build_start](https://github.com/bazelbuild/bazel/assets/117954304/162c298a-baf2-4587-abc5-dcdc1fc589c9)

### Which category does this issue belong to?

Remote Execution

### Which operating system are you running Bazel on?

gLinux

### What is the output of `bazel info release`?

release 7.1.0

**Comment by coeuvre** [comment]
It's probably because we log the task using timestamp from the RBE here: https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnRunner.java;l=361;drc=d8c27bfcd37a74dfbf1bdb9a1e3df13af8360a01.

We should clamp the start time in this case. cc @tjgq

**Comment by tjgq** [comment]
I will send a fix.
