### ISSUE TITLE
[Mirror] zig 0.12.0

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel#22236]
### Please list the URLs of the archives you'd like to mirror:

https://ziglang.org/download/0.12.0/zig-linux-aarch64-0.12.0.tar.xz
https://ziglang.org/download/0.12.0/zig-linux-x86_64-0.12.0.tar.xz
https://ziglang.org/download/0.12.0/zig-macos-aarch64-0.12.0.tar.xz
https://ziglang.org/download/0.12.0/zig-macos-x86_64-0.12.0.tar.xz
https://ziglang.org/download/0.12.0/zig-windows-aarch64-0.12.0.zip
https://ziglang.org/download/0.12.0/zig-windows-x86_64-0.12.0.zip

**Comment by satyanandak** [comment]
Hi @linzhp, 
Can you please share the non mirror link ?  as in   https://github.com/bazelbuild/bazel/issues/19344.

**Comment by linzhp** [comment]
Sorry, my bad. Updated.

**Comment by satyanandak** [comment]
Thanks @linzhp, here you go
https://mirror.bazel.build/ziglang.org/download/0.12.0/zig-linux-aarch64-0.12.0.tar.xz
https://mirror.bazel.build/ziglang.org/download/0.12.0/zig-linux-x86_64-0.12.0.tar.xz
https://mirror.bazel.build/ziglang.org/download/0.12.0/zig-macos-aarch64-0.12.0.tar.xz
https://mirror.bazel.build/ziglang.org/download/0.12.0/zig-macos-x86_64-0.12.0.tar.xz
https://mirror.bazel.build/ziglang.org/download/0.12.0/zig-windows-aarch64-0.12.0.zip
https://mirror.bazel.build/ziglang.org/download/0.12.0/zig-windows-x86_64-0.12.0.zip
