### ISSUE TITLE
ExtraActionInfo doesn't have let custom rules pass structured data to listeners

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#2223]
When running extra_action processing code for custom rules. I would like to know structured data from the rule definition such as which files are sources and which files are deps. As it stands I have to parse the command line or make assumptions about file names from the source files as specified in SpawnAction.

**Comment by iirina** [comment]
@ulfjack can you take a look at this?

**Comment by ulfjack** [comment]
As it stands you have to parse the command line. Consider that C++ rules create one compile action per source file, i.e., the mapping from cc_library.srcs to actions is highly non-obvious. If you want to know the rule structure, then you should use bazel query or the genquery rule, or an aspect.

What's the question here? Feel free to reopen if you have more data and / or a more specific request what you want us to do and why.

**Comment by endobson** [comment]
I want custom rules to be on the same playing field for extra actions as builtin rules. Currently those get special protos, where custom rules just get SpawnAction.

For example in my current linking action of my languages library rule I call the system linker with tons of flags that are appropriate for it. I'm working on an extra action that goes through a different linking process that I'm experimenting with. Currently I hackily parse the input files of SpawnAction, but that relies on the types of the input files all being the same which may change. Similarly I could try to parse the command line, but that could change as well if the system linker needs new flags. Neither of those are meant to be stable descriptions of the action being performed, while the proto passed to the extra action is, and I want the ability to attach a machine parseable format from my rule to downstream tools.

I don't know much about aspects and will investigate them. bazel query or genquery don't solve the issue that extra actions do of letting me run code per library rule that I have.


My linker code: https://github.com/endobson/yaspl2/blob/15bc4fc62a0e41efda89446f71f346e7fa928632/libraries/BUILD#L770

**Comment by endobson** [comment]
I don't have access to reopen it seems.

**Comment by ulfjack** [comment]
Reopening per request from @endobson .

We're actually considering dropping the special parts in the current proto. Since we introduced the proto, our internal users have changed to parsing the command-line instead of relying on the special protos or they're ok with doing so. Proto3 also doesn't support extensions any more, so if we want to keep something like this after all, we'll need to come up with a new mechanism to do so.

**Comment by dslomov** [comment]
@ulfjack  is this still under investigation?

**Comment by dslomov** [comment]
@ulfjack is this the right category?

**Comment by aiuto** [comment]
@endobson Is this still a request? Or, has enough changed to make it irrelevant?

**Comment by endobson** [comment]
I believe that aspects have allowed me to do similar processing without this.
