### ISSUE TITLE
[Mirror] abseil-cpp

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#22243]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/abseil/abseil-cpp/releases/download/20240116.2/abseil-cpp-20240116.2.tar.gz
https://github.com/abseil/abseil-cpp/archive/refs/tags/20240116.2.zip

**Comment by satyanandak** [comment]
Here you go
https://mirror.bazel.build/github.com/abseil/abseil-cpp/releases/download/20240116.2/abseil-cpp-20240116.2.tar.gz
https://mirror.bazel.build/github.com/abseil/abseil-cpp/archive/refs/tags/20240116.2.zip
