### ISSUE TITLE
Load external dependency for foreign project without control of WORKSPACE file content

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#2224]
Gerrit Code Review project exposes plugin API and hundreds of plugins exist in the wild. Two build modes are supported:

* Standalone plugin build mode
* In Gerrit tree plugin build mode

**Standalone plugin build mode:**

* reviewers plugin https://github.com/davido/gerrit-reviewers-plugin

Plugin project controls the content of `WORKSPACE` file and can add there plugin owns dependency. During build Gerrit Plugin API + plugin own dependency are downloaded from the Central and plugin artifact is created.

**In Gerrit tree plugin build mode:**

To short circuit the publishing of Gerrit plugin API to Central (or even to local Maven repository, in `~/.m2` directory) with this mode the plugin directory is linked to Gerrit tree under `plugins/<plugin-name>` and built with:

```
  bazel build plugins/<plugin-name>
```

Working example:

* reviewers plugin https://github.com/davido/gerrit-reviewers-plugin

This works unless plugins have their own dependencies, in which case, there is no way to load them, untill `WORKSPACE` in Gerrit project is patched.

Example:

* gerrit-oauth-provider https://github.com/davido/gerrit-oauth-provider

that depends on third party library `scribe`, that is loaded through plugin own `WORKSPACE` file:

```
maven_jar(
    name = "scribe_artifact",
    artifact = "org.scribe:scribe:1.3.7",
    sha1 = "583921bed46635d9f529ef5f14f7c9e83367bc6e",
)

bind(
    name = "scribe",
    actual = "@scribe_artifact//jar",
)
```

and added as a dependency to the plugin artifact:

```
gerrit_plugin(
    name = "gerrit-oauth-provider",
    srcs = glob(["src/main/java/**/*.java"]),
    manifest_entries = [
        "Gerrit-PluginName: gerrit-oauth-provider",
        "Gerrit-HttpModule: com.googlesource.gerrit.plugins.oauth.HttpModule",
        "Gerrit-InitStep: com.googlesource.gerrit.plugins.oauth.InitOAuth",
        "Implementation-Title: Gerrit OAuth authentication provider",
        "Implementation-URL: https://github.com/davido/gerrit-oauth-provider",
    ],
    resources = glob(["src/main/resources/**/*"]),
    deps = [
        "//external:scribe",
    ],
)
```

So in the Gerrit tree build mode, gerrit own `WORKSPACE` file doesn't contain this dependency and thus Gerrit tree build mode cannot be supported for all Gerrit plugins that require third party dependencies (without temporarily patching Gerrit `WORKSPACE` file).

FWIW: It worked as expected with Buck, by just adding the third party dependency in place (in `BUCK` file), see: https://github.com/davido/gerrit-oauth-provider/blob/stable-2.10/BUCK for the whole truth:

```
include_defs('//bucklets/gerrit_plugin.bucklet')
include_defs('//bucklets/maven_jar.bucklet')
[...]
maven_jar(
  name = 'scribe',
  id = 'org.scribe:scribe:1.3.7',
  sha1 = '583921bed46635d9f529ef5f14f7c9e83367bc6e',
  license = 'scribe',
  local_license = True,
)
[...]
gerrit_plugin(
  name = 'gerrit-oauth-provider',
  [...]
  deps = [
    ':scribe'
  ],
  [...]
```

**Comment by davido** [comment]
One workaround is to define `WORKSPACE.in_gerrit_tree` file in every gerrit plugin that has third party dependencies. Example for working `WORKSPACE.in_gerrit_tree`:

```python

maven_jar(
    name = "scribe",
    artifact = "org.scribe:scribe:1.3.7",
    sha1 = "583921bed46635d9f529ef5f14f7c9e83367bc6e",
)

```

Now, the building such plugin include extra patching step of gerrit's own `WORKSPACE` file:

```shell
  cd plugins/
  ln -s ../../gerrit-oauth-provider .
  cat ../gerrit-oauth-provider/WORKSPACE.in_gerrit_tree >> WORKSPACE
  $ bazel build plugins/gerrit-oauth-provider
INFO: Found 1 target...
Target //plugins/gerrit-oauth-provider:gerrit-oauth-provider up-to-date:
  bazel-genfiles/plugins/gerrit-oauth-provider/gerrit-oauth-provider.jar
INFO: Elapsed time: 0.652s, Critical Path: 0.52s
```

Checking the final artifact:

```shell
  unzip -t bazel-genfiles/plugins/gerrit-oauth-provider/gerrit-oauth-provider.jar | grep scribe | wc -l
112
```

**Comment by katre** [comment]
I think this will be addressed by @kchodorow's work on handling recursive workspaces, assigning to her.

**Comment by lucamilanesio** [comment]
Can we escalate the priority? We a hundred of plugins blocked ATM :-(

**Comment by hanwen** [comment]
maybe we can sit down together some time? I don't see an easy way to solve this, since skylark loads can't be parameterized.

**Comment by kchodorow** [comment]
Sure, although I'm actually working on recursive workspaces right now, so hopefully it'll be a moot point by next release.

**Comment by hanwen** [comment]
is there a doc I can look at?

**Comment by kchodorow** [comment]
https://bazel.build/designs/2016/09/19/recursive-ws-parsing.html

**Comment by hanwen** [comment]
Ah, so we would have a WORKSPACE in each plugin, and then in the main WORKSPACE, we would do something like 

  local_repository(name = "cookbook",
    path= "plugins/cookbook")

plugins/cookbook/WORKBOOK would contain the dependencies that just cookbook needs. I think that would work for us.

**Comment by kchodorow** [comment]
Exactly.

**Comment by davido** [comment]
Is there a recursive WORKSPACE resolution issue/feature request somewhere?
