### ISSUE TITLE
[Mirror] rules go patch release 0.47.1

### ISSUE THREAD

**Issue by tyler-french** [bazelbuild/bazel#22258]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/rules_go/releases/download/v0.47.1/rules_go-v0.47.1.zip

**Comment by satyanandak** [comment]
Here you go
https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.47.1/rules_go-v0.47.1.zip
