### ISSUE TITLE
[7.2.0] Update commons-compress to 1.26.1

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22256]
Forked from #22213

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`MODULE.bazel.lock`
`maven_install.json`

cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
https://github.com/bazelbuild/bazel/pull/22300
