### ISSUE TITLE
Error: couldn't connect to server after 60 seconds

### ISSUE THREAD

**Issue by ibudnikov** [bazelbuild/bazel#2225]
Hello, everybody!
I hope, you can help me with my problem. I'm trying to build Tensorflow v r0.12 with GPU support on Windows 8.1.
Every action i do (including even "bazel clean", "bazel fetch" and "bazel info release") leads to ~600 dots and error:
"Error: couldn't connect to server after 60 seconds"
Anybody have any ideas?

**Comment by iirina** [comment]
@dslomov can you take a look at this?

**Comment by dslomov** [comment]
Sorry for late reply.. Is it still an issue? Which bazel version are you using?

**Comment by ibudnikov** [comment]
I've already make tensorflow using CMake. It was latest version of Bazel (for Windows) on that time (11 Dec).

**Comment by dslomov** [comment]
Sorry, this is not actionable then I guess.
