### ISSUE TITLE
Docs - https://bazel.build/help slack invite is broken

### ISSUE THREAD

**Issue by kcon-stackav** [bazelbuild/bazel#22255]
### Page link:

https://bazel.build/help

### Problem description (include actual vs expected text, if applicable):

I can't join the Bazel Slack workspace as a new member because all of the links seem to be expired. When I click on the links to join the Bazel Slack workspace, I see a message that reads:

> This link is no longer active
> To join this workspace, you’ll need to ask the person who originally invited you for a new link.

### Where do you see this issue? (include link to specific section of the page, if applicable)

https://bazel.build/help#community for the "Chatting with other Bazel contributors on Slack" link, but also on most pages on the site in the footer for the "Slack" link under the "Support" section.

**Comment by Wyverald** [comment]
Thanks for the report! I'm trying to update the redirect. In the meantime, please use this link: https://join.slack.com/t/bazelbuild/shared_invite/zt-1kpv2308h-ZwFfFba8Enkotu7uhkLKdw

**Comment by Wyverald** [comment]
This is now fixed.
