### ISSUE TITLE
[7.2.0] Store remote registry file hashes in the lockfile

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22277]
Forked from #21901

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`MODULE.bazel.lock`
`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BUILD`
`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileModule.java`
`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java`
`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalValue.java`
`src/test/java/com/google/devtools/build/lib/analysis/util/BuildViewTestCase.java`
`src/test/py/bazel/bzlmod/bazel_lockfile_test.py`

cc: @bazelbuild/triage

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`MODULE.bazel.lock`
`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BUILD`
`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelLockFileModule.java`
`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunction.java`
`src/test/java/com/google/devtools/build/lib/analysis/util/BuildViewTestCase.java`

cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
https://github.com/bazelbuild/bazel/pull/22296
