### ISSUE TITLE
ci.bazel.io: //src/test/shell/bazel:bazel_coverage_test is failing on various architecture

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2227]
On latest run (403):
See http://ci.bazel.io/job/bazel-tests/403/BAZEL_VERSION=HEAD-jdk7,PLATFORM_NAME=ubuntu_15.10-x86_64/testReport/(root)/(empty)/test_java_test_coverage/

FTR http://ci.bazel.io/job/bazel-tests/403/testReport/ to see all test failures of a run (does not shows timeouts).

**Comment by hermione521** [comment]
Do you have any idea how to repro locally? Thanks

**Comment by damienmg** [comment]
It is fixed I sent a patch yesterday to reactivate the test and should
close that bug when the commit hit Github.

**Comment by hermione521** [comment]
Thank you so much!
