### ISSUE TITLE
[7.2.0] Apply repo mapping to `cc_shared_library`'s `exports_filter`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22283]
Forked from #21622

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/starlark/builtins_bzl/common/cc/cc_binary.bzl`
`src/main/starlark/builtins_bzl/common/cc/cc_shared_library.bzl`
`src/main/starlark/builtins_bzl/common/cc/cc_test.bzl`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/starlark/builtins_bzl/common/cc/cc_binary.bzl` `src/main/starlark/builtins_bzl/common/cc/cc_shared_library.bzl` `src/main/starlark/builtins_bzl/common/cc/cc_test.bzl`
> 
> cc: @bazelbuild/triage

cc: @Wyverald @fmeum @comius

**Comment by Wyverald** [comment]
https://github.com/bazelbuild/bazel/pull/22328
