### ISSUE TITLE
[bazel.build] Problem with /rules/language

### ISSUE THREAD

**Issue by jmanske** [bazelbuild/bazel#22286]
### Page link:

https://bazel.build/rules/language

### Problem description (include actual vs expected text, if applicable):

The links to the various data types no longer seem to work

### Where do you see this issue? (include link to specific section of the page, if applicable)

https://bazel.build/rules/language

**Comment by sgowroji** [comment]
Hi @jmanske, Could you please point me to the URL datatypes, which are no longer working?  Thanks!

**Comment by jmanske** [comment]
The links on that page to the data types were not working the day I wrote the issue. Today they are working. Maybe it was a browser problem? Unclear. I'll close the issue.
