### ISSUE TITLE
[7.2.0] Make --modify_execution_info additive

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22288]
Forked from #16262

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/analysis/config/BuildConfigurationValue.java`
`src/main/java/com/google/devtools/build/lib/analysis/config/CoreOptions.java`
`src/main/starlark/builtins_bzl/common/builtin_exec_platforms.bzl`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/analysis/config/BuildConfigurationValue.java` `src/main/java/com/google/devtools/build/lib/analysis/config/CoreOptions.java` `src/main/starlark/builtins_bzl/common/builtin_exec_platforms.bzl`
> 
> cc: @bazelbuild/triage

cc: @aranguyen @coeuvre

**Comment by coeuvre** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/22316.
