### ISSUE TITLE
[7.2.0] Cherry-pick  84861027d3f94ce6fc0bcf25ebbb787d6be8567a

### ISSUE THREAD

**Issue by ahumesky** [bazelbuild/bazel#22298]
### Commit IDs

84861027d3f94ce6fc0bcf25ebbb787d6be8567a

### Category

team-Android

### Reviewers

@iancha1992, @keertk

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/22299: https://github.com/bazelbuild/bazel/commit/84861027d3f94ce6fc0bcf25ebbb787d6be8567a.
