### ISSUE TITLE
[7.2.0] Preserve paths under hermetic `/tmp` in the sandbox

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22291]
Forked from #22001

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxedSpawnRunner.java`
`src/main/java/com/google/devtools/build/lib/sandbox/SandboxHelpers.java`
`src/main/java/com/google/devtools/build/lib/skyframe/ActionOutputMetadataStore.java`
`src/test/java/com/google/devtools/build/lib/worker/WorkerSpawnRunnerTest.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Duplicate: https://github.com/bazelbuild/bazel/issues/21217
