### ISSUE TITLE
Should --sandbox_debug imply --incompatible_sandbox_hermetic_tmp=false?

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#22290]
### Description of the feature request:

I often use --sandbox_debug to grab some paths from the output and inspect the execroot that an action failed with. I've noticed that with `--incompatible_sandbox_hermetic_tmp=true` (the default), that workflow doesn't work, so I have to flip it to false every time I want to do that. Should that be automatic with --sandbox_debug? Or should my workflow change since maybe we also don't want to keep both codepaths of `incompatible_sandbox_hermetic_tmp` around forever?

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

7.1.1

**Comment by fmeum** [comment]
The paths won't deviate for much longer: https://github.com/bazelbuild/bazel/pull/22001

Also, did you see the command that `--sandbox_debug` outputs? It drops you into an interactive shell in the sandbox environment in which you can explore the execroot.

**Comment by keith** [comment]
thanks for the link, so you're saying after that change the output paths will continue to exist? thanks for the command workaround, I'm just so used to the easy copy-paste when i don't need to change the whole context to match bazel

**Comment by fmeum** [comment]
> thanks for the link, so you're saying after that change the output paths will continue to exist?

Yes!

**Comment by keith** [comment]
awesome, thanks!

**Comment by fmeum** [comment]
Reopening as this should be closed by #22001 for posterity.
