### ISSUE TITLE
Upgrade to the latest release of Error Prone?

### ISSUE THREAD

**Issue by dpursehouse** [bazelbuild/bazel#2230]
Version 2.0.13 is used, but the latest version is 2.0.15.  Can it be upgraded?

**Comment by damienmg** [comment]
It's in-flight: https://bazel-review.googlesource.com/c/7110/

**Comment by dpursehouse** [comment]
@damienmg Ah, OK, thanks. I checked open PRs and issues here, but completely forgot to check open reviews in Gerrit :)

Will you close this issue when that change lands?

**Comment by damienmg** [comment]
Sure let me ask to add the needed info to the PR :)
