### ISSUE TITLE
Vendor mode does not remap cross-repo symlinks to vendor dir

### ISSUE THREAD

**Issue by peakschris** [bazelbuild/bazel#22303]
### Description of the bug:

When vendoring a repo such as rules_helm, which contains symlinks between its sub-repos, the symlinks are not remapped on vendoring. This means the resulting directories in the vendor_dir contains symlinks into the bazel user cache, and become dangling if the vendor_dir is copied to a different machine.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Module.bazel:
```bazel_dep(name = "rules_helm", version = "0.3.2")```

```
bazel vendor --vendor_dir=vendor
dir vendor\rules_helm~~helm~helm\helm.exe
<note resulting file is a symlink that points into user cache>
```

### Which operating system are you running Bazel on?

windows, but I suspect this is a general problem

### What is the output of `bazel info release`?

7.2.0 latest (8c6220a19b65dac3e675a97a59a146b8e294c404)

### Any other information, logs, or outputs that you want to share?

There is also an issue in rules_helm on Windows with the rules_helm symlink, but this is unrelated to this reported issue: https://github.com/abrisco/rules_helm/issues/78. I have validated this by fixing the rules_helm issue locally.

**Comment by fmeum** [comment]
This is the relevant line in rules_helm:
https://github.com/abrisco/rules_helm/blob/main/helm%2Frepositories.bzl#L130

**Comment by meteorcloudy** [comment]
@BoleynSu Can you please file a new issue for this with a more detailed bug report? Including what is the current behaviour and what is the expect behaviour?
