### ISSUE TITLE
exec_properties for action ObjcLink does not effect

### ISSUE THREAD

**Issue by Kila2** [bazelbuild/bazel#22314]
### Description of the bug:

```
ios_application(
  ...
  exec_properties = {
    'key': 'value',
  }
)
```
for this rule. when set exec_properties. the remote execution server receive ObjcLink Action platform properties is empty CppLink platform properties is name: key value:value.

### Which operating system are you running Bazel on?

macos 13.6.4

### What is the output of `bazel info release`?

bazel 7

**Comment by brentleyjones** [comment]
`ios_application` is defined in **rules_apple** (or **rules_ios** if you are using that), so this is probably best filed there.

**Comment by Kila2** [comment]
I'm sure this is a problem with Bazel. That's why I submitted it here.

**Comment by Kila2** [comment]
cc_common.link not getExecutionInfo from the exec_properties

**Comment by iancha1992** [comment]
@Kila2 
I think he meant here: https://github.com/bazelbuild/rules_apple/issues

**Comment by Kila2** [comment]
I had add an option to support this feature. https://github.com/bazelbuild/bazel/pull/22339

**Comment by katre** [comment]
I suspect you need to use the special `cpp_link` exec group name. Try this:

```
ios_application(
  ...
  exec_properties = {
    'cpp_link.key': 'value',
  }
)
```

See [the documentation on exec groups and execution properties](https://bazel.build/extending/exec-groups#platform-execution-properties) for more details.

**Comment by keith** [comment]
ObjcLink is gone as a separate action at this point anyways, so cpp_link should for sure be the right key
