### ISSUE TITLE
[7.2.0] Do not delay TargetCompleteEvents with coverage #22278

### ISSUE THREAD

**Issue by joeleba** [bazelbuild/bazel#22311]
### Commit IDs

84c15a00d4a756fb82af5079b4e71f5cf933fe94
fd2cc92ad7aa27878645b15c52474c9019233de9

### Category

team-Performance

### Reviewers

@keertk @meisterT

**Comment by bazel-io** [comment]
Failed commits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/84c15a00d4a756fb82af5079b4e71f5cf933fe94
fd2cc92ad7aa27878645b15c52474c9019233de9.
Please resolve manually.
cc: @bazelbuild/triage
