### ISSUE TITLE
actionListeners fully invalidate workspaces on query

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#2233]
If any --experimental_action_listener is specified, a subsequent query (without that option available for that module) causes bazel to perceive the build as being invoked with incompatible options.  A subsequent build of a target with the same --experimental_action_listener specified (and no other modifications) causes the target to be rebuilt with all actions executed, invariably.

* Operating System: linux
* Bazel version (output of `bazel info release`): master - 9bde9d09a83cdca2dc884d322ab50f7542c062cf

**Comment by iirina** [comment]
@ulfjack can you take a look?

**Comment by ulfjack** [comment]
How do you know that those are not cache hits?

**Comment by ulfjack** [comment]
Closing due to lack of updates.
