### ISSUE TITLE
[7.2.0] Mark bazel_tools extensions as reproducible

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22336]
Forked from #22335

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`MODULE.bazel.lock`
`src/test/tools/bzlmod/MODULE.bazel.lock`
`tools/android/android_extensions.bzl`

cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
https://github.com/bazelbuild/bazel/pull/22353
