### ISSUE TITLE
[FR]: support digest functions (SHA512, etc) for remote downloader

### ISSUE THREAD

**Issue by hunshcn** [bazelbuild/bazel#22338]
### Description of the feature request:

I observed that the resources of integrity except sha256/blake3 cannot is not working when using remote downloader.

bazel will always hash blob with sha256/blake3. And the digest won't be matched

```
WARNING: Remote Cache: Output null download failed: Expected digest '5de5a7e869ace4c69059d8fe0b87eec6ea3f21ccbc72487e0700088a3857d8b2911c7b753ae72d2cb2e507417810f8b9e66d885093539eff051fd912048ece83/1311' does not match received digest '9ade2f118703e4115bc1226fb366b06365130f3f04832cebe0d82ffd9008ff33/1311'.
``` 

(At present, neither bazel-remote nor buildbuddy supports sha512, but I have implemented a version myself. https://github.com/hunshcn/bazel-remote/tree/feat/cas-md5-sha1-sha512)

Since pnpm-lock.yaml only supports sha512, I have to use it.

### Which category does this issue belong to?

Remote Execution

### What underlying problem are you trying to solve with this feature?

support it

This should not be difficult, because we can easily confirm what kind of digest it is by the length of the Expected digest.

If this fr is approved, I am willing to provide pr. (it might take a while, I don't know java)

### Which operating system are you running Bazel on?

macos

### What is the output of `bazel info release`?

7.1.2

**Comment by coeuvre** [comment]
Implemented by https://github.com/bazelbuild/bazel/pull/21996 which will be shipped with 7.2.0.
