### ISSUE TITLE
collect-coverage.sh: exit trap: line 2: syntax error: unexpected end of file

### ISSUE THREAD

**Issue by GinFungYJF** [bazelbuild/bazel#2236]
After I run `bazel coverage`, the end of test.log complains
```
Post-processing coverage results:
Capturing coverage data from /tmp/tmp.NZsPXi1q6E
Found gcov version: 4.8.4
Scanning /tmp/tmp.NZsPXi1q6E for .gcda files ...
geninfo: ERROR: no .gcda files found in /tmp/tmp.NZsPXi1q6E!
external/bazel_tools/tools/coverage/collect-coverage.sh: exit trap: line 2: syntax error: unexpected end of file
```
How to solve it?
### Environment info
* Operating System: 
Ubuntu 14.04.5 LTS

* Bazel version (output of `bazel info release`):
0.4.2

**Comment by katre** [comment]
Coverage is a work in progress, assigning this to the person working on it.

**Comment by hermione521** [comment]
I haven't tried gcov yet. Add @ulfjack

**Comment by ulfjack** [comment]
Can you give us more info? Is this for C++? Do you get coverage results despite the test log output or does the coverage run fail? If so, can you post a larger chunk of the bazel output?
