### ISSUE TITLE
/Zc:inline should be set on by default in the MSVC Windows toolchain

### ISSUE THREAD

**Issue by matt-sm** [bazelbuild/bazel#22373]
### Description of the bug:

Since Visual Studio 14, `/Zc:inline` has been turned on by default:

https://devblogs.microsoft.com/cppblog/feedback-making-zcinline-default-for-debugrelease-configs-in-14/

But this flag seems to be missing from the default windows toolchain config:

https://github.com/bazelbuild/bazel/blob/master/tools/cpp/windows_cc_toolchain_config.bzl#L659

Migrating an existing VS project to cc_ toolchain can cause a regression.

### Which category does this issue belong to?

C++ Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a VS (2015 or greater) project and check Configuration Properties -> C/C++ -> Command Line.  `/Zc:inline` is set.
 
 or alternatively
 
 Use the VS generator with a CMake project and open the generated vcproj file in VS.  The same flag is set.
 
 Now create a cc_library and `bazel build -S //...`.  This flag is not set.

### Which operating system are you running Bazel on?

Windows 10

### What is the output of `bazel info release`?

release 7.1.1

**Comment by fmeum** [comment]
We could make this possibly breaking change for Bazel 8. Ideally, we would have a feature toggling this behavior so that users broken by it can easily disable it. 

Would you be interested in sending a PR?

**Comment by matt-sm** [comment]
Created https://github.com/bazelbuild/bazel/pull/22392
