### ISSUE TITLE
[Mirror] hermetic_cc_toolchain 3.1.0

### ISSUE THREAD

**Issue by tyler-french** [bazelbuild/bazel#22388]
### Please list the URLs of the archives you'd like to mirror:

github.com/uber/hermetic_cc_toolchain/releases/download/v3.1.0/hermetic_cc_toolchain-v3.1.0.tar.gz

**Comment by satyanandak** [comment]
Here you go
https://mirror.bazel.build/github.com/uber/hermetic_cc_toolchain/releases/download/v3.1.0/hermetic_cc_toolchain-v3.1.0.tar.gz
