### ISSUE TITLE
[7.2.0] Fix version detection logic in release branches

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel#22390]
### Commit IDs

31b522fc454f7b5ddf74b830c2c42fedc0d2db65

### Category

team-OSS

### Reviewers

@fweikert

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/22391: https://github.com/bazelbuild/bazel/commit/31b522fc454f7b5ddf74b830c2c42fedc0d2db65.
