### ISSUE TITLE
Please cherry-pick https://github.com/bazelbuild/bazel/pull/22100 into 7.2.0

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#22394]
### Commit IDs

`eb905bde4920954aefee0f018488d054cceaa772`

### Category

team-ExternalDeps

### Reviewers

@iancha1992 @Wyverald

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but failed to push. Please check if the branch, cp_ondemand_22394-Mainline issues targeted for 7.2.0, already exists
cc: @bazelbuild/triage

**Comment by bazel-io** [comment]
Failed commits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/`eb905bde4920954aefee0f018488d054cceaa772`
.
Please resolve manually.
cc: @bazelbuild/triage

**Comment by lberki** [comment]
Nevermind. This was manually cherry-picked as `f6618782df1521e674061d3b6a6bb973ed78f591`.
