### ISSUE TITLE
It should be possible to attach a `rules_license` license to arbitrary targets

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#22403]
### Description of the feature request:

Using `package(default_package_metadata = [])` it's possible to attach license information to every target in a build file, but in some cases it would be useful to add a specific license (or metadata) to a specific rule. The `licenses` attribute was previously used for this, but is now deprecated and only took a string

### Which category does this issue belong to?

Core, External Dependency

### What underlying problem are you trying to solve with this feature?

`rules_jvm_external` generates a single build file containing every third party dependency that a user can depend on. In order to integrate nicely with `rules_license`, it would be useful to be able to assign a specific license to each target, since each dependency may have its own license.

### Which operating system are you running Bazel on?

n/a

### What is the output of `bazel info release`?

n/a

**Comment by shs96c** [comment]
The presence of `default_package_metadata` in the `package` rule implies that there's a `package_metadata` attribute on rules. This doesn't appear to be the case with Bazel 7.1.0

**Comment by Wyverald** [comment]
> The presence of `default_package_metadata` in the `package` rule implies that there's a `package_metadata` attribute on rules. This doesn't appear to be the case with Bazel 7.1.0

just chatted to @aiuto -- he said that `package_metadata` is an implicit attribute on all rules. Probably undocumented though. Have you tried it?

**Comment by aiuto** [comment]
+1.  This is a doc bug.

**Comment by shs96c** [comment]
This attribute doesn't seem to be present in Bazel 7.1.1

**Comment by fmeum** [comment]
@aiuto It's not too late to cherry-pick this into 7.2.0.

**Comment by aiuto** [comment]
Huh?  It should have been available months ago.

**Comment by shs96c** [comment]
`applicable_licenses` does appear to be present.

**Comment by fmeum** [comment]
I sent https://github.com/bazelbuild/bazel/pull/22497 to encode the intended behavior in a test. Bazel 7 sets the `applicable_licenses` attribute, Bazel 8 will provide both to users while requiring rule authors to use `package_metadata`.
