### ISSUE TITLE
Sanitizer does not show colored output

### ISSUE THREAD

**Issue by carlosgalvezp** [bazelbuild/bazel#22418]
### Description of the bug:

When a cc_test fails due to sanitizer, the sanitizer output is shown without color. Executing the test directly instead of within Bazel does show color.

### Which category does this issue belong to?

C++ Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a simple `cc_test` with the following source code:

```
int main()
{
    int x[5];
    return x[5];
}
```

Run with:

```
bazel test --test_output=all --color=yes --features=asan :foo
```

The test fails and the ASAN output is printed, but without colors, which makes it harder to read.

### Which operating system are you running Bazel on?

Ubuntu 22.04

### What is the output of `bazel info release`?

release 7.1.2

**Comment by fmeum** [comment]
Could you try running with `--test_env=ASAN_OPTIONS=color=always`?

**Comment by carlosgalvezp** [comment]
It works, thanks a lot!

**Comment by fmeum** [comment]
Great! Since Bazel records all test output, sanitizer doesn't see a terminal and thus doesn't enable colors in auto mode. I don't think there is a way to change this, but since it works with an explicit sanitizer option, I'll close this issue.
