### ISSUE TITLE
Java: Support for long classpath on Windows

### ISSUE THREAD

**Issue by rpaquay** [bazelbuild/bazel#2242]
### Description of the problem / feature request / question:

On Windows, there is a hard limit on the total length of command lines. Depending on the context, it is either 8192 Bytes or 32KB. 

When running java actions through the src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt file, Bazel seem to hit the 8192 characters limit.

This is problematic for semi-complex java rules that have many .jar dependencies, as they are all added to the "-classpath" argument.

One solution to this problem is to use the "classpath jar" trick as explained here: http://stackoverflow.com/questions/201816/how-to-set-a-long-java-classpath-in-windows

(I am attaching a diff that partially implements this).

### If possible, provide a minimal example to reproduce the problem:

This is a little hard for me, as it would require sharing a semi-complex project, with many dependencies. But, in theory, the repro is simple: execute a java rule that has many .jar dependencies, and ensure the resulting command is longer than 8192 characters.

### Environment info
* Operating System:
Windows

* Bazel version (output of `bazel info release`):
All versions

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

This seems somewhat related to issue #1780, although the problem is more severe on Windows, as the limit is much lower than Linux/Mac.

### Anything else, information or logs or outputs that would be helpful?

I am attaching a patch I made to the "src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt" file. 

[0001-Fix-long-classpaths-windows.zip](https://github.com/bazelbuild/bazel/files/652706/0001-Fix-long-classpaths-windows.zip)

However, the patch is not perfect, as it has a hard-coded special treatment of the very first .jar file in the list to be explicitly left on the "-classpath" command line argument (as opposed to be referenced in the classpath.jar file). The reason is that the code in https://github.com/bazelbuild/bazel/blob/c484f19a2cf7427887d6e4c71c8534806e1ba83e/src/test/java/com/google/devtools/build/lib/testutil/Classpath.java#L127 does not take into account the "classpath jar" trick when looking for tests classes.

**Comment by dslomov** [comment]
@meteorcloudy could you take a look at this? This is a blocker for 0.5

**Comment by meteorcloudy** [comment]
No problem, I am on it!

**Comment by meteorcloudy** [comment]
I believe generating an extra `classpath.jar` when the limit is exceeded is the right solution for this. But java_stub_template.txt shouldn't be responsible for this, instead, we can create an action in [BazelJavaSemantics](https://github.com/bazelbuild/bazel/blob/2300f8a3e88d720f7eae90a80456142363850c5c/src/main/java/com/google/devtools/build/lib/bazel/rules/java/BazelJavaSemantics.java#L190) for this.

Also in Classpath.java, we look into classpath.jar to find the complete CLASSPATH.

How does this sound?
@dslomov @lberki

**Comment by lberki** [comment]
@iirina

**Comment by meteorcloudy** [comment]
@laszlocsomor Do you have some insight on this?

**Comment by laszlocsomor** [comment]
@meteorcloudy : Not more than what's already here. I had this exact issue in mind with the classpath.jar trick when I said I may know something :) Also, I agree this bug is related to https://github.com/bazelbuild/bazel/issues/1780, I they are in fact the same.

**Comment by laszlocsomor** [comment]
Correction: they aren't exactly the same, this bug is the Windows-specific case of https://github.com/bazelbuild/bazel/issues/1780.

**Comment by meteorcloudy** [comment]
@laszlocsomor Ah, thanks! I am implementing this, hopefully it could solve this issue on both Unix and Windows.

**Comment by meteorcloudy** [comment]
After discussion with @laszlocsomor and @damienmg, we realize it's a bad idea to create the classpath jar during build time. Because on Windows, the classpath is a list of absolute paths mapped from MANIFEST file at runtime, if it's a remote execution the length of classpath could change due to different workspace path. So the only solution is to do the trick in the java stub template file, create the classpath jar on the fly.

I'll rollback my changes and send new ones.

**Comment by meteorcloudy** [comment]
Had more discussion with @laszlocsomor, creating the classpath jar in stub template is also not good. From my observation, if the classpath is too long, it takes a long time to build the classpath jar file every time you run the script. (I built a java_binary target which depends on 1500 java_library targets, and it took half a minute to create the classpath jar.)

We think it's better to go with the original plan, and assume the worst case where every path is at MAX_PATH_LENGTH (4k on Linux, 260 on Windows). So the max number of entries in classpath is MAX_CMD_LENGTH / MAX_PATH_LENGTH. This might cause bazel to build the classpath jar very often, but maybe we can live with it?

**Comment by laszlocsomor** [comment]
Right, building the classpath jar during the build has the advantage that we build it only once (and it's always up-to-date). If we build it on-the-fly in the launcher stub script, then we build it every time we launch the script.

**Comment by rpaquay** [comment]
I am all for improving performance, but I should point out that is it a **misconception** that Windows is limited to 260 characters for paths. The actual limit is 32K characters, see https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx (look for "\\\\?\\" in the page)

In summary,

* Since Windows XP, Win32 applications can workaround the 260 character limit by ensuring they call Win32 file API using absolute paths with the "\\\\?\\" prefix.
  
  * For example, Java 7 (maybe 6?) introduced automatic support for 32K paths, so all Java applications
    automatically support 32K paths - see http://stackoverflow.com/questions/10094365/how-does-java-circumvent-the-windows-max-path-winapi-limitation)
	
  * Cygwin and msys also added automatic support for 32KB paths. It is easy to test in a bash prompt (create a very long and deep series of paths).

  * Git For Windows has a "core.config.longpaths" options to support 32KB paths. See http://pingec.si/blog/articles/msysgit-longpath/
  
* In addition, since Windows 10 anniversary edition, there is a new system wide setting to remove the 260 character limit even for apps that don't use the "\\\\?\\". What this means is that in a couple of years (Windows 10 usage is already higher than Windows 7 usage in the US), one can hope that most of the Windows ecosystem will have support for 32KB paths by default.

**Comment by rpaquay** [comment]
As for the 30 seconds you mention to create the JAR file, did you look at the following patch: https://github.com/rpaquay/bazel/commit/359fd3abd96797aac8dbc121afcbc80a8c1c5df4. It fixes an issue with "rlocation" performance on Windows. I am not sure why the patch I attached to this bug would have a 30 seconds overhead (even for 1500 files), because it is merely doing "echo yyy >xxx".

**Comment by laszlocsomor** [comment]
> I am all for improving performance, but I should point out that is it a **misconception** that Windows is limited to 260 characters for paths. The actual limit is 32K characters, see https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx (look for "\\\\?\\" in the page)
> 
The 32K limit is unfortunately the exception, not the general rule. Most functions still limit the path to 260 chars (including null-terminator). Some API functions support long paths with said prefix, but most don't:

> *These are the directory management functions that no longer have MAX_PATH restrictions if you opt-in to long path behavior: CreateDirectoryW, CreateDirectoryExW GetCurrentDirectoryW RemoveDirectoryW SetCurrentDirectoryW.*
>
> *These are the file management functions that no longer have MAX_PATH restrictions if you opt-in to long path behavior: CopyFileW, CopyFile2, CopyFileExW, CreateFileW, CreateFile2, CreateHardLinkW, CreateSymbolicLinkW, DeleteFileW, FindFirstFileW, FindFirstFileExW, FindNextFileW, GetFileAttributesW, GetFileAttributesExW, SetFileAttributesW, GetFullPathNameW, GetLongPathNameW, MoveFileW, MoveFileExW, MoveFileWithProgressW, ReplaceFileW, SearchPathW, FindFirstFileNameW, FindNextFileNameW, FindFirstStreamW, FindNextStreamW, GetCompressedFileSizeW, GetFinalPathNameByHandleW.*

(Source: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx)

Unfortunately, even though `SetCurrentDirectoryW` is mentioned above and moreover its documentation also says long paths are supported with the "\\\\?\\" prefix, that's simply false. I specifically tested this, hoping it'd help us work around the `MAX_PATH` limitation of `CreateProcess` (both `A` and `W`, with or without "\\\\?\\"), sadly to no avail.

> In summary,
> 
> * Since Windows XP, Win32 applications can workaround the 260 character limit by ensuring they call Win32 file API using absolute paths with the "\\\\?\\" prefix.
>   
>   * For example, Java 7 (maybe 6?) introduced automatic support for 32K paths, so all Java applications
>     automatically support 32K paths - see http://stackoverflow.com/questions/10094365/how-does-java-circumvent-the-windows-max-path-winapi-limitation)
> 	
>   * Cygwin and msys also added automatic support for 32KB paths. It is easy to test in a bash prompt (create a very long and deep series of paths).
> 
>   * Git For Windows has a "core.config.longpaths" options to support 32KB paths. See http://pingec.si/blog/articles/msysgit-longpath/
>   
I didn't know any of those, thanks for sharing!

> * In addition, since Windows 10 anniversary edition, there is a new system wide setting to remove the 260 character limit even for apps that don't use the "\\\\?\\".

Right, but that setting needs to be enabled (in the registry, perhaps?), potentially requiring Administrator intervention, which may be prohibitive for some users.

**Comment by rpaquay** [comment]
> The 32K limit is unfortunately the exception, not the general rule. Most functions still limit the path to 260 chars (including null-terminator)

I think there is some misunderstanding here. Most functions **do** support the "\\\\?\\" prefix. SetCurrentDirectoryW and CreateProcessW are the only 2 exceptions I know of. All the other API I have tried: CopyFileW, CreateDirectoryW, CreateSymbolicLink, etc. all support the "\\\\?\\" prefix (see https://github.com/rpaquay/mtsuite/blob/master/src/shared/Win32/Win32.cs for an example using these functions from C#).

The list you quote from the MSDN article is related to the new Windows 10 option to support long paths **without** having to use the prefix.

> Right, but that setting needs to be enabled (in the registry, perhaps?), potentially requiring Administrator intervention, which may be prohibitive for some users.

Sure. My guess is that this will change within a couple of years.

Anyways, my point is **please** think twice before making implementation decision in based on the MAX_PATH limit. For example, in this particular issue, there is no reason to limit anything based on MAX_PATH: jar files are data files that can be manipulated with functions that support "\\\\?\\", they can be loaded by the java runtime, etc. As long as there is no need to SetCurrentDirectory and/or CreateFile on such paths, the MAX_PATH limit does not apply.

**Comment by meteorcloudy** [comment]
I just realized a serious problem for the original solution (creating classpath jar at build time). It's impossible to have the correct jar paths before doing rlocation operation, but rlocation can only happen at runtime. So it's impossible to create the classpath jar file during build time anyway.

**Comment by rpaquay** [comment]
A little confused here: Why was the issue re-opened? Q CL was submitted with my (slightly modified) original patch that builds the classpath.jar file at runtime. (see https://github.com/bazelbuild/bazel/commit/752b61ee4d839b6b9680353c0d1d02de2ad13f14)

**Comment by meteorcloudy** [comment]
Yes, you are right. This is issue is fixed with 29e22949664b0c2a0a9cc8d48630f4712a89a067 and 752b61ee4d839b6b9680353c0d1d02de2ad13f14. But there might be some performance issue, feel free to reopen or create a new one if you think it's a problem. Closing this now.
