### ISSUE TITLE
Representation of repo rules in performance artifacts

### ISSUE THREAD

**Issue by emaxx-google** [bazelbuild/bazel#22439]
### Description of the feature request:

This feature request is about improving the representation of repo rules in Bazel's performance artifacts: trace profiles, exec logs, graph logs.

IIUC, currently the following limitations exist:
* repo rules aren't displayed in trace profiles as lying on the critical path even when they actually do;
* repo rules don't have the `out` field populated in trace profiles (`--experimental_profile_include_primary_output`);
* exec logs don't record invocations of the repo rules;
* graph logs have no nodes nor edges representing repo rules.

Having at least some of these fixed would be useful for projects like ChromeOS which have big repo rules (in our case, at the order of magnitude of 10 minutes). Currently we work it around by implementing the drag analysis ourselves after heuristically backfilling the missing edges to repo rules, but it'd be nice if these hacks weren't necessary in order to get unbiased performance analysis.

### Which category does this issue belong to?

Core

### What underlying problem are you trying to solve with this feature?

Better understanding of performance and bottlenecks in builds.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

7.1.0

**Comment by Wyverald** [comment]
We do have profile spans for repo fetches (see https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/repository/RepositoryDelegatorFunction.java;drc=e7635c5fcf984a38ce566214b101c6e31bc13f5f;l=140). Do you you mean something else with "trace profiles"?

Sorry I'm not too familiar with this area (e.g. how to make sure repo rules show up in the critical path). cc'ing some perf people for help. @meisterT @joeleba
