### ISSUE TITLE
[7.2.0] Provide "did you mean ...?" suggestions for unknown command-line options

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22459]
Forked from #22193

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/common/options/IsolatedOptionsData.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/22507
