### ISSUE TITLE
Aspects should be able to see ctx.rule.outputs

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2245]
I want to have a list of all (trans.) outputs of a `filegroup`.
For that I wrote an aspect and implementation to access `ctx.rule.outputs`. To my surprise `outputs` is not exposed for aspect implementation.
Is this an oversight or is there an actual reasoning?

**Comment by dslomov** [comment]
Oh, sorry for late reply. You should be able to examine outputs of a rule you apply aspect to, so it is a bug

**Comment by abergmeier-dsfishlabs** [comment]
Just hit that again. Makes aspects really unusable to me 😢

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
