### ISSUE TITLE
Linter Warning in src/main/cpp/blaze.cc for option_processor, passed by reference object

### ISSUE THREAD

**Issue by Sittiphat** [bazelbuild/bazel#22469]
### Description of the bug:

Discovered a Google C++ Linter Warning in src/main/cpp/blaze.cc at line 1092 (see image below)

The official Google C++ guideline say that the options are to either make the reference parameter const if the parameter is not meant to be modified, or use a pointer instead of a non-const reference if the parameter is intended to be modified. Since "option_processor" is modified in the function definition, the change I believe should be opted to pass by pointer.

![OptionProcessor_pass_by_ref](https://github.com/bazelbuild/bazel/assets/62792095/b5f088db-4cba-434d-9066-4fabcc62b371)

### Which category does this issue belong to?

C++ Rules

### Any other information, logs, or outputs that you want to share?

Is this a non-const reference? If so, make const or use a pointer: OptionProcessor &option_processor  cpplint(warning:runtime/references)
<error-type> &option_processor
![OptionProcessor_pass_by_ref](https://github.com/bazelbuild/bazel/assets/62792095/b4b87a08-1e4c-457f-bdee-e0db15254afb)

**Comment by Sittiphat** [comment]
My potential fix:
https://github.com/bazelbuild/bazel/pull/22470

**Comment by tjgq** [comment]
The Google C++ style guide changed a few years ago, and use of pointers for input/output parameters is no longer required; non-const references are fine if the parameter is never null. See https://google.github.io/styleguide/cppguide.html#Inputs_and_Outputs.
