### ISSUE TITLE
December release: 0.4.3

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2246]
Filing the release bug for this month since I haven't seen it yet.

**Comment by iirina** [comment]
Created RC:
`scripts/release/release.sh create 0.4.3 c645a45204b5ee4698387b0487b8a5136ba6d06f af878d04990d9eb12bda75b3571dff48d40fce1a 09b92a8fc9a6e4fcf451c71be098d9ba6ab379ac b11dd482eef2eb922686fb9ba96e39113cc1abd1`

and pushed to GitHub:
`scripts/release/release.sh push`

waiting for `ci.bazel.io `to finish.

**Comment by damienmg** [comment]
http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel-Release/95/console Release failed. Might be because of my last changes investigating

**Comment by damienmg** [comment]
Filed #2256

**Comment by petemounce** [comment]
Please ping me when rc is up and I'll publish to chocolatey.

**Comment by damienmg** [comment]
The RC is up but the mail wasn't send because of a bug in the debian
publishing :(. You can do the chocolatey package fron the 0.4.3rc2 URL at
https://storage.googleapis.com/bazel/0.4.3/rc2/index.html

On Sat, Dec 17, 2016, 12:31 AM Peter Mounce <notifications@github.com>
wrote:

Please ping me when rc is up and I'll publish to chocolatey.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bazelbuild/bazel/issues/2246#issuecomment-267721388>,
or mute the thread

**Comment by petemounce** [comment]
@damienmg ok - published and available at https://chocolatey.org/packages/bazel/0.4.3-rc2

**Comment by iirina** [comment]
Damien commited a fix for #2256 which I have cherry picked when creating and pushing RC2 on Friday evening:

```
$ scripts/release/release.sh create 0.4.3 c645a45204b5ee4698387b0487b8a5136ba6d06f af878d04990d9eb12bda75b3571dff48d40fce1a 09b92a8fc9a6e4fcf451c71be098d9ba6ab379ac b11dd482eef2eb922686fb9ba96e39113cc1abd1 9012bf1676bd6426229625e2567bfa399f89dabe

$ scripts/release/release.sh push
```

However the release still failed and @katre identified the commit as breaking the normal build process for non-releases, so the change got reverted.

**Comment by damienmg** [comment]
The reason for the breakage is because the manifest is empty. Easy enough
to fix and rollforward. I think the release is safe without it because it's
only breaking the CI pipeline on non release trigger.

However this did not fixed the underlying issue: the section is empty in
the DSC file. I need more investigation to fix it.

**Comment by damienmg** [comment]
To be cherry-picked: 4a753499d0685ce08c99c1da61eea4e100989d31

**Comment by damienmg** [comment]
More cherry-picks: 11b5725 deae044 deae044

**Comment by damienmg** [comment]
4a753499d0685ce08c99c1da61eea4e100989d31 55c97bcf9b99916a3fe59295be64c4aee860d823 are to be cherry-picked.

Still one change that is being submitted plus the fix for the distribution artifact

**Comment by damienmg** [comment]
Ok so far the remaining bug seems like just tests setup fixes. I think we can go forward with another RC with the following fixes: 4a75349 4a75349 55c97bc 39e5a46 4fb378c

**Comment by iirina** [comment]
I tried to create the new RC:

`$ scripts/release/release.sh create 0.4.3 c645a45204b5ee4698387b0487b8a5136ba6d06f af878d04990d9eb12bda75b3571dff48d40fce1a 09b92a8fc9a6e4fcf451c71be098d9ba6ab379ac b11dd482eef2eb922686fb9ba96e39113cc1abd1 9012bf1676bd6426229625e2567bfa399f89dabe 4a753499d0685ce08c99c1da61eea4e100989d31 55c97bcf9b99916a3fe59295be64c4aee860d823 39e5a46294de31baa0411f6a59119427c66305da 4fb378c0fa08131394dc5e815f6fe5597d007a66`

but it failed:

```
error: could not apply 4a75349... Avoids NullPointerException when running `bazel coverage //:xxx`, since PathFragment.getParentDirectory() may return null. Fixes #2212.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
Failed to cherry-pick 4a753499d0685ce08c99c1da61eea4e100989d31. please resolve the conflict and exit.
```

**Comment by iirina** [comment]
There was a conflict in `src/test/shell/bazel/bazel_coverage_test.sh`.

I merged the file and
```
$ git add src/test/shell/bazel/bazel_coverage_test.sh
$ git cherry-pick --continue
```

However the script exited before and the release didn't finish. The cherry-picks added after the one with the merge conflict were not added to the release.

**Comment by iirina** [comment]
Did
```
$ cherry-pick --continue; exit
```
after already cherry-picking and it accidentally deleted the release branch:

```
$ git cherry-pick --continue; exit
error: no cherry-pick or revert in progress
fatal: cherry-pick failed
exit
  Cherry-picking 55c97bcf9b99916a3fe59295be64c4aee860d823
  Cherry-picking 39e5a46294de31baa0411f6a59119427c66305da
  Cherry-picking 4fb378c0fa08131394dc5e815f6fe5597d007a66
Creating release notes
Release notes are empty, cancelling release creation...
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Deleted branch release-0.4.3 (was e59d226).
```

Re-did the whole RC creation and it worked, only now it is marked again as RC1 :(

$ scripts/release/release.sh create 0.4.3 c645a45204b5ee4698387b0487b8a5136ba6d06f af878d04990d9eb12bda75b3571dff48d40fce1a 09b92a8fc9a6e4fcf451c71be098d9ba6ab379ac b11dd482eef2eb922686fb9ba96e39113cc1abd1 9012bf1676bd6426229625e2567bfa399f89dabe 4a753499d0685ce08c99c1da61eea4e100989d31 55c97bcf9b99916a3fe59295be64c4aee860d823 39e5a46294de31baa0411f6a59119427c66305da 4fb378c0fa08131394dc5e815f6fe5597d007a66

```
$ vim src/test/shell/bazel/bazel_coverage_test.sh 
$ git add src/test/shell/bazel/bazel_coverage_test.sh 
$ git cherry-pick --continue; exit
[release-0.4.3 300e70d] Avoids NullPointerException when running `bazel coverage //:xxx`, since PathFragment.getParentDirectory() may return null. Fixes #2212.
 Author: Yue Gan <yueg@google.com>
 Date: Tue Dec 20 04:54:55 2016 +0000
 6 files changed, 80 insertions(+), 59 deletions(-)
exit
  Cherry-picking 55c97bcf9b99916a3fe59295be64c4aee860d823
  Cherry-picking 39e5a46294de31baa0411f6a59119427c66305da
  Cherry-picking 4fb378c0fa08131394dc5e815f6fe5597d007a66
Creating release notes
Created 0.4.3rc1 on branch release-0.4.3.
```

**Comment by iirina** [comment]
Fixed candidate name:
```
$ git notes --ref=release-candidate show
1
$ git notes --ref=release-candidate remove
$ git notes --ref=release-candidate append -m "3"
$ git notes --ref=release-candidate show
3
```

**Comment by iirina** [comment]
Pushing now

`$ scripts/release/release.sh push`

waiting for `ci.bazel.io` to finish.

**Comment by iirina** [comment]
Email was sent to bazel-discuss. The release notes in the email are wrong, they just include the commit message of the last cherry pick.

```
# Debian repository: override section and priority fields 

Those field are not added to the dsc file and reprepro has started 
failing. Reproducing the whole set-up is almost impossible so I 
am sending this and will trigger a test release. 

Also use release label instead of release name so we get the rc 
number (for some reason this was not included in previous release). 

Fixes #2256. 
To be cherry-picked for #2246 
```

The [web release notes](https://storage.googleapis.com/bazel/0.4.3/rc3/index.html) seem nicer, although the cherry picks are not nicely formatted and it still seems 2/6 cherry picks are missing.

**Comment by damienmg** [comment]
missing cherry-pick: acbcbc2 (forgot it)

**Comment by iirina** [comment]
Creating new candidate with additional cherry-pick acbcbc2ff7dab2e68801c714e57475d6d57be8f2

```
$ scripts/release/release.sh create 0.4.3 c645a45204b5ee4698387b0487b8a5136ba6d06f af878d04990d9eb12bda75b3571dff48d40fce1a 09b92a8fc9a6e4fcf451c71be098d9ba6ab379ac b11dd482eef2eb922686fb9ba96e39113cc1abd1 9012bf1676bd6426229625e2567bfa399f89dabe 4a753499d0685ce08c99c1da61eea4e100989d31 55c97bcf9b99916a3fe59295be64c4aee860d823 39e5a46294de31baa0411f6a59119427c66305da 4fb378c0fa08131394dc5e815f6fe5597d007a66 acbcbc2ff7dab2e68801c714e57475d6d57be8f2
$ vim src/test/shell/bazel/bazel_coverage_test.sh 
$ git add src/test/shell/bazel/bazel_coverage_test.sh 
$ git cherry-pick --continue; exit
```

Created 0.4.3rc4 on branch release-0.4.3.

Pushed:

`$ scripts/release/release.sh push`

**Comment by iirina** [comment]
New email was sent to bazel-discuss. The release notes look really good in the email, including almooost all (7/9) cherry-picks (except 4a753499d0685ce08c99c1da61eea4e100989d31 and 39e5a46294de31baa0411f6a59119427c66305da). The [web release notes](https://storage.googleapis.com/bazel/0.4.3/rc4/index.html) are still not nicely formatted.

**Comment by iirina** [comment]
Should we also cherry-pick 49757602c4ca9e48081f98850007b2ef17427b46? It fixes #2247 (someone accidentally added a usage of Java8-only code and some users can't built bazel on a Linux system with JDK7). The culprit is ca99bb71b8120e61a3bbde8e54f1a9488fa0478f which is included in the candidate, but the fix isn't. However we should actually release today since I'll be OOO starting tomorrow.

**Comment by damienmg** [comment]
We cannot release before Friday or at least before tomorrow. The JDK
breakage is on the test right? In which case is not really important.

**Comment by damienmg** [comment]
Oh it is not on the test so we should cherrypick it. Strange it was able to
bootstrap...

**Comment by iirina** [comment]
OK then I will cherry pick it now and will release Friday evening from home.

**Comment by damienmg** [comment]
Don't do the release from home. We'll find someone to take over.

**Comment by iirina** [comment]
Created and pushed RC5 including cherry-pick 49757602c4ca9e48081f98850007b2ef17427b46.

```
$ scripts/release/release.sh create 0.4.3 c645a45204b5ee4698387b0487b8a5136ba6d06f af878d04990d9eb12bda75b3571dff48d40fce1a 09b92a8fc9a6e4fcf451c71be098d9ba6ab379ac b11dd482eef2eb922686fb9ba96e39113cc1abd1 9012bf1676bd6426229625e2567bfa399f89dabe 4a753499d0685ce08c99c1da61eea4e100989d31 55c97bcf9b99916a3fe59295be64c4aee860d823 39e5a46294de31baa0411f6a59119427c66305da 4fb378c0fa08131394dc5e815f6fe5597d007a66 acbcbc2ff7dab2e68801c714e57475d6d57be8f2 49757602c4ca9e48081f98850007b2ef17427b46

$ scripts/release/release.sh push
```

**Comment by iirina** [comment]
Seems like bazel-install failed with Jenkins error:

http://ci.bazel.io/job/Bazel-Install/7659/console

will re-run.

**Comment by iirina** [comment]
The email was sent to bazel-discuss \o/ All is well except there are still 2/10 cherry picks missing (the same as before).

**Comment by iirina** [comment]
I re-run the build and got the same Jenkins errors:
http://ci.bazel.io/job/Bazel-Install/7690/console
platform is linux-x86_64

**Comment by damienmg** [comment]
Let finally cherry-pick 05fd076 today and do the release tomorrow evening so we still have one working day before christmas.

**Comment by iirina** [comment]
Created and pushed RC6 

```
$ scripts/release/release.sh create 0.4.3 c645a45204b5ee4698387b0487b8a5136ba6d06f af878d04990d9eb12bda75b3571dff48d40fce1a 09b92a8fc9a6e4fcf451c71be098d9ba6ab379ac b11dd482eef2eb922686fb9ba96e39113cc1abd1 9012bf1676bd6426229625e2567bfa399f89dabe 4a753499d0685ce08c99c1da61eea4e100989d31 55c97bcf9b99916a3fe59295be64c4aee860d823 39e5a46294de31baa0411f6a59119427c66305da 4fb378c0fa08131394dc5e815f6fe5597d007a66 acbcbc2ff7dab2e68801c714e57475d6d57be8f2 49757602c4ca9e48081f98850007b2ef17427b46 05fd076ba338b80ad4e650f3ea907544a9296c1c
$ vim src/test/shell/bazel/bazel_coverage_test.sh 
$ git add src/test/shell/bazel/bazel_coverage_test.sh 
$ git cherry-pick --continue; exit
$ scripts/release/release.sh push
```

**Comment by petemounce** [comment]
Pushed https://chocolatey.org/packages/bazel/0.4.3-rc6.

**Comment by damienmg** [comment]
Released, testing homebrew update. FreeBSD port update is being pushed too.

**Comment by damienmg** [comment]
Side-note:
We now have 3 packaging that needs separate update (homebrew, freebsd and chocolatey), maybe we should have automatic process to update them instead on relying on package maintainers

**Comment by damienmg** [comment]
homebrew/homebrew-core#8131 for Homebrew
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=215490 for FreeBSD

**Comment by petemounce** [comment]
@damieng I'm happy to write automation to automatically publish chocolatey. All it really needs is a Windows instance and for me too know how secrets are injected into your ci environment, so the chocolatey API key I have is not burned.

**Comment by damieng** [comment]
Wrong damien.

**Comment by petemounce** [comment]
Oh excuse me yes. @damienmg

**Comment by petemounce** [comment]
Merry Christmas; https://chocolatey.org/packages/bazel/0.4.3 is in the queue.

**Comment by damienmg** [comment]
@petemounce thanks but it seems like we will have to update the binaries: #2289 :(

**Comment by damienmg** [comment]
@petemounce I was not able to reproduce #2289 so I would say we are good to go.

Closing this bug, Merry Christmas!

**Comment by petemounce** [comment]
Could not reproduce == on the nice list ;)
