### ISSUE TITLE
Bazel doesn't detect dependencies between source code files and targets if the dependency on the sources comes from the local repository

### ISSUE THREAD

**Issue by Asdprom** [bazelbuild/bazel#22464]
### Description of the bug:

E.g.: there is a file `A.cc` located in the `@sample_repo` local repository, target `@sample_repo//:A` that depends on `A.cc` and there is a target `//:B` that depends on `@sample_repo//:A`.
If you execute the command `bazel query 'rdeps("//...", "@sample_repo//:A.cc")'`,
Output:
```
//:B
@sample_repo//:A
@sample_repo//:A.cc
```
 
However, if you execute the command `bazel query 'rdeps("//...", "sample_repo/A.cc")'`,
Output:
```
//sample_repo:A
//sample_repo:A.cc
```
 
As of my understanding, `//sample_repo:A.cc` and `@sample_repo//:A.cc` should be treated as labels for the same file. In both cases, we should receive the target `//:B`, as it depends on `sample_repo/A.cc` (and probably both kinds of labels, repo and not too). However, this is not what's happening. I would like to understand whether this is the expected behavior or if it's a rather strange bug.
 

### Which category does this issue belong to?

External Dependency

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Minimal sample to reproduce the issue is in attached archive.
[bazel_sample.zip](https://github.com/bazelbuild/bazel/files/15390901/bazel_sample.zip)

`bazel query 'rdeps("//...", "@sample_repo//:A.cc")'`
`bazel query 'rdeps("//...", "sample_repo/A.cc")'`

### Which operating system are you running Bazel on?

windows

### What is the output of `bazel info release`?

release 7.0.2-2

**Comment by Wyverald** [comment]
This is expected behavior. The labels `@sample_repo//:a.cc` and `//sample_repo:a.cc` ostensibly point to the same file, but they're treated as different files by Bazel. Technically, the former ends up being a symlink of the latter; the repo `@sample_repo` is really located at `$(bazel info output_base)/external/sample_repo`, which, due to your WORKSPACE setup, is a symlink to `$(bazel info workspace)/sample_repo`.

**Comment by Asdprom** [comment]
@Wyverald , understood, thank you!

If I need to find all possible targets that depend on a specific file, I currently have to resolve all repositories, mapping paths to repository names and forming repository labels manually. This is a very inefficient and sometimes incorrect solution. 
Maybe you can suggest a way to workaround this limitation?

**Comment by Wyverald** [comment]
well, to find out if there are things in `@whatever_repo` that depends on your file, it only makes sense that you have to fetch `@whatever_repo` first, no?

In any case, if you need help with your use case, please head over to https://slack.bazel.build to discuss it!
