### ISSUE TITLE
jdk7 installer on Linux does not work for me

### ISSUE THREAD

**Issue by kohlerm** [bazelbuild/bazel#2247]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
I used 
 bazel-0.4.2-jdk7-installer-linux-x86_64.sh 
to install bazel on RHEL 7.2 and Ubuntu 16.04

in both cases I get:

$ bazel build 
Warning: ignoring http_proxy in environment.
...
unexpected pipe read status: No such file or directory
Server presumed dead. Now printing '/home/D041705/.cache/bazel/_bazel_D041705/e1207fce5496ac41c73461b740d46bf3/server/jvm.out':
java.lang.NoSuchMethodError: java.lang.Boolean.hashCode(Z)I
	at com.google.devtools.build.lib.vfs.PathFragment.hashCode(PathFragment.java:740)
	at com.google.common.collect.ImmutableSet.construct(ImmutableSet.java:153)
	at com.google.common.collect.ImmutableSet.of(ImmutableSet.java:87)
	at com.google.devtools.build.lib.cmdline.Label.<clinit>(Label.java:62)
	at com.google.devtools.build.lib.analysis.ConfiguredRuleClassProvider$Builder.setPrelude(ConfiguredRuleClassProvider.java:240)
	at com.google.devtools.build.lib.bazel.rules.BazelRuleClassProvider$1.init(BazelRuleClassProvider.java:298)
	at com.google.devtools.build.lib.bazel.rules.BazelRuleClassProvider.setup(BazelRuleClassProvider.java:270)
	at com.google.devtools.build.lib.bazel.rules.BazelRulesModule.initializeRuleClasses(BazelRulesModule.java:106)
	at com.google.devtools.build.lib.runtime.BlazeRuntime$Builder.build(BlazeRuntime.java:1088)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:972)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.createBlazeRPCServer(BlazeRuntime.java:815)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:763)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:551)
	at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)

After installing with the jdk8  installer (which works) and reinstalling (with --user) even the jdk installation seems to work

### If possible, provide a minimal example to reproduce the problem:

I followed the Java introduction

### Environment info
* Operating System:
Red Hat Enterprise Linux 4.3
Ubuntu 16.06 LTS

* Bazel version (output of `bazel info release`):
release 0.4.2-jdk7

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

NO

### Anything else, information or logs or outputs that would be helpful?
strace bazel

(at the end)
fcntl(6, F_GETFL)                       = 0 (flags O_RDONLY)
fcntl(6, F_SETFL, O_RDONLY|O_NONBLOCK)  = 0
clock_gettime(CLOCK_REALTIME, {1481806269, 513222459}) = 0
clock_gettime(CLOCK_REALTIME, {1481806269, 513246300}) = 0
clock_gettime(CLOCK_REALTIME, {1481806269, 513262848}) = 0
open("/home/D041705/.cache/bazel/_bazel_D041705/e1207fce5496ac41c73461b740d46bf3/server/command_port", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, ".", 1.)                        = 1
clock_gettime(CLOCK_REALTIME, {1481806269, 513413577}) = 0
nanosleep({0, 99849271}, NULL)          = 0
read(6, 0x7ffcd50d00df, 1)              = -1 EAGAIN (Resource temporarily unavailable)
clock_gettime(CLOCK_REALTIME, {1481806269, 613566358}) = 0
clock_gettime(CLOCK_REALTIME, {1481806269, 613663057}) = 0
open("/home/D041705/.cache/bazel/_bazel_D041705/e1207fce5496ac41c73461b740d46bf3/server/command_port", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, ".", 1.)                        = 1
clock_gettime(CLOCK_REALTIME, {1481806269, 613774383}) = 0
nanosleep({0, 99888674}, NULL)          = 0
read(6, 0x7ffcd50d00df, 1)              = -1 EAGAIN (Resource temporarily unavailable)
clock_gettime(CLOCK_REALTIME, {1481806269, 713852447}) = 0
clock_gettime(CLOCK_REALTIME, {1481806269, 713877135}) = 0
open("/home/D041705/.cache/bazel/_bazel_D041705/e1207fce5496ac41c73461b740d46bf3/server/command_port", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, ".", 1.)                        = 1
clock_gettime(CLOCK_REALTIME, {1481806269, 713991201}) = 0
nanosleep({0, 99885934}, NULL)          = 0
read(6, "", 1)                          = 0
write(2, "\nunexpected pipe read status: No"..., 184
unexpected pipe read status: No such file or directory

**Comment by katre** [comment]
Looks like someone accidentally added a usage of the Java8-only static Boolean.hashCode method.

We need to remove it and figure out why tests didn't catch this.

**Comment by gibiansky** [comment]
This is a pretty frustrating showstopper. It would be really nice if there were a binary release with the fix in it, because right now software that depends on a new enough version of bazel can't be built on a Linux system with JDK7.

**Comment by katre** [comment]
The 0.4.3 release is in progress. have you tried the 0.4.3 release candidate 3 (available from https://storage.googleapis.com/bazel/0.4.3/rc3/index.html)? It is in good shape and we should have a full release shortly, but this might help you get moving until it's released.

**Comment by gibiansky** [comment]
I don't think that commit (4975760) is in RC3. The base of RC3 is https://github.com/bazelbuild/bazel/commit/c645a45 (15 days ago, before the fix) and it's not listed in the cherry picks.

**Comment by iirina** [comment]
You can now try 0.4.3r5 which also cherry-picks the fix for this issue. The link is [here](https://storage.googleapis.com/bazel/0.4.3/rc5/index.html). Let me know if it solved your problem.

**Comment by gibiansky** [comment]
@iirina That seems to have fixed the issues I had. Thank you!
