### ISSUE TITLE
[7.2.0] Add layering_check support for macOS

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22472]
Forked from #22259

**Comment by bazel-io** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/22474

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/22475 by @keith

**Comment by keith** [comment]
that one isn't targeting 7.2.0 yet, but have to re-merge into main since it was reverted, i will resubmit if we can land in time
