### ISSUE TITLE
[Mirror] Missing Bazel deps

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#22488]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazel-contrib/bazel_features/releases/download/v1.11.0/bazel_features-v1.11.0.tar.gz
https://github.com/bazelbuild/rules_java/releases/download/7.6.1/rules_java-7.6.1.tar.gz

**Comment by satyanandak** [comment]
Here you go 
https://mirror.bazel.build/github.com/bazel-contrib/bazel_features/releases/download/v1.11.0/bazel_features-v1.11.0.tar.gz
https://mirror.bazel.build/github.com/bazelbuild/rules_java/releases/download/7.6.1/rules_java-7.6.1.tar.gz
