### ISSUE TITLE
targets=$(bazel query "//...") hangs on Windows

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2248]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

http://ci.tensorflow.org/job/tf-master-win-bzl/186/console
TensorFlow Bazel builds are timeout after https://github.com/tensorflow/tensorflow/commit/dbe5e17e2ed307e86e1a6e79e558ec3e335d46fc

The reason is `bazel query` command hangs.

### If possible, provide a minimal example to reproduce the problem:
```
pcloudy@tensorflow-jenkins-win-gpu2-slave MSYS ~/workspace
$ mkdir test_dir

pcloudy@tensorflow-jenkins-win-gpu2-slave MSYS ~/workspace
$ touch test_dir/WORKSPACE

pcloudy@tensorflow-jenkins-win-gpu2-slave MSYS ~/workspace
$ touch test_dir/BUILD

pcloudy@tensorflow-jenkins-win-gpu2-slave MSYS ~/workspace
$ cd test_dir/

pcloudy@tensorflow-jenkins-win-gpu2-slave MSYS ~/workspace/test_dir
$ targets=$(bazel query "//...")
ERROR: CreateFile(C:\tmp\_bazel_pcloudy\cTsFhU5s\install): The system cannot find the file specified.
 (2)
............
____Loading package:
____Empty results
(Hangs here forever)
```

### Environment info
* Operating System: Windows 7

* Bazel version (output of `bazel info release`):

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`): 0.4.2

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
No

### Anything else, information or logs or outputs that would be helpful?
A similar bug https://github.com/bazelbuild/bazel/issues/2182

**Comment by meteorcloudy** [comment]
It only hangs when running in a new workspace or after the output base is cleaned.

**Comment by dslomov** [comment]
@meteorcloudy could you check whether 1324e83 fixed this?

**Comment by meteorcloudy** [comment]
No, we still have this problem.. :(

**Comment by laszlocsomor** [comment]
Shot in the dark: this may have been caused by Bash waiting for all child processes of the subshell to exit. Since the Bazel server was not exiting, though daemonizing, the subshell was duly waiting for it. See https://github.com/bazelbuild/bazel/issues/3148.
