### ISSUE TITLE
[7.2.0] Fail early on certain invalid labels in module files

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22491]
Forked from #22487

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunctionTest.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/22506
