### ISSUE TITLE
hang in analyzing for bazel-6.3.0 and other version

### ISSUE THREAD

**Issue by xmuchen** [bazelbuild/bazel#22490]
### Description of the bug:

I use qemu-docker to compile arm  target in my x86 device.
But when I start bazel compile,it always hang in analyzing.
![2024-05-21_18-30](https://github.com/bazelbuild/bazel/assets/122765896/4ca35a77-59d0-49c4-8327-b816b686a401)
and I find many threads was wating on condition,the log as below
[analyzing_hang.txt](https://github.com/bazelbuild/bazel/files/15400061/analyzing_hang.txt)

**Comment by meisterT** [comment]
Can you please provide a repro?

**Comment by tjgq** [comment]
Please reopen with reproduction instructions.

**Comment by briandbl** [comment]
i encounter the question. i use  the docker-qemu using the  bazel compile  the  baidu apollo project. it always hang in the build. but i found that  i use the command "kill -9 server-id", then the compile can continue.

**Comment by briandbl** [comment]
@xmuchen do you have a solution to  fix  it?

**Comment by lilejin322** [comment]
> i encounter the question. i use the docker-qemu using the bazel compile the baidu apollo project. it always hang in the build. but i found that i use the command "kill -9 server-id", then the compile can continue.

It seems that Baidu Apollo is not supported for compilation on an ARM machine, so I think cross-compilation is not feasible.
