### ISSUE TITLE
Repository rules get reevaluated too often, starting from 7.1.0

### ISSUE THREAD

**Issue by blorente** [bazelbuild/bazel#22494]
### Description of the bug:

Starting from Bazel 7.1.0, repository rules that used to be cached and not re-run have started being re-run. This might be a case of[ Hyrum's Law,](https://www.hyrumslaw.com) but we did rely on this behaviour for caching xcode resolutions internally.

### Which category does this issue belong to?

Rules API

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- Check out the repro: https://github.com/blorente/bazel-repo-rules-repro-may-2024
- Run it with Bazel 7.0.2. See how the repository rule doesn't get re-evaluated:
```
➜ USE_BAZEL_VERSION='7.0.2' bazel fetch @counter//...                                                                                                           
Starting local Bazel server and connecting to it...
DEBUG: /Volumes/code/scratch/scratch/repo-rules/rules.bzl:5:10: Running counter
DEBUG: /Volumes/code/scratch/scratch/repo-rules/rules.bzl:12:10: Writing counter value 23
INFO: All external dependencies fetched successfully.

➜ USE_BAZEL_VERSION='7.0.2' bazel fetch @counter//...
INFO: All external dependencies fetched successfully.
```
- Run it with Bazel 7.1.0. The repository rule got re-evaluated:
```
➜ USE_BAZEL_VERSION='7.1.0' bazel fetch @counter//...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: f7704521-eeda-44e8-b609-4c51d37851be
DEBUG: /Volumes/code/scratch/scratch/repo-rules/rules.bzl:5:10: Running counter
DEBUG: /Volumes/code/scratch/scratch/repo-rules/rules.bzl:12:10: Writing counter value 24
...

➜ USE_BAZEL_VERSION='7.1.0' bazel fetch @counter//...
INFO: Invocation ID: 62d9655c-ff33-4d49-9f22-a7a255d42136
DEBUG: /Volumes/code/scratch/scratch/repo-rules/rules.bzl:5:10: Running counter
DEBUG: /Volumes/code/scratch/scratch/repo-rules/rules.bzl:12:10: Writing counter value 25
...
```
- The same thing happens on the latest bazel:
```
➜ USE_BAZEL_VERSION='latest' bazel fetch @counter//...
Starting local Bazel server and connecting to it...
DEBUG: /Volumes/code/scratch/scratch/repo-rules/rules.bzl:5:10: Running counter
DEBUG: /Volumes/code/scratch/scratch/repo-rules/rules.bzl:12:10: Writing counter value 26
INFO: All external dependencies for these targets fetched successfully.

➜ USE_BAZEL_VERSION='latest' bazel fetch @counter//...
DEBUG: /Volumes/code/scratch/scratch/repo-rules/rules.bzl:5:10: Running counter
DEBUG: /Volumes/code/scratch/scratch/repo-rules/rules.bzl:12:10: Writing counter value 27
INFO: All external dependencies for these targets fetched successfully.
```

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

Release numbers are in the repro, but this reproduces on `latest`

### Have you found anything relevant by searching the web?

I haven't found anything searching through GH issues, and the documentation on repository rules seems to indicate that setting `local = True` and `configure = True` should prevent the rule from running.

**Comment by blorente** [comment]
Thanks @fmeum for the quick response!
If that is the case, I might be misreading t[he documentation on repository rule evaluation](https://bazel.build/extending/repo#when_is_the_implementation_function_executed). I think this is the relevant passage:

> The content of any file passed to the read(), execute() and similar methods of repository_ctx which is referred to by a label (for example, //mypkg:label.txt but not mypkg/label.txt)

In this case, the repository rule refers to it by a path ([link](https://github.com/blorente/bazel-repo-rules-repro-may-2024/blob/main/rules.bzl#L6)), so I would have expected the rule to not get invalidated. Am I misinterpreting the documentation?

**Comment by fmeum** [comment]
You aren't, the docs are wrong here (they weren't updated with the change).

Cc @Wyverald
