### ISSUE TITLE
[7.2.0] Fix a crash on `use_repo_rule` with no repos

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22496]
Forked from #22493

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunctionTest.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/22508
