### ISSUE TITLE
Building 0.4.2 for SDK7 from source: "BUILD file not found on package path." 

### ISSUE THREAD

**Issue by mindhog** [bazelbuild/bazel#2250]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

When building bazel from source from bazel-0.4.2-jdk7-dist.zip, the build fails with the following error:

    ERROR: no such package '@bazel_tools//tools/jdk': BUILD file not found on package path.

### If possible, provide a minimal example to reproduce the problem:

It should be possible to reproduce this by just running "./compile.sh" from the root of the distribution tree.

### Environment info
* Operating System: Debian 8.6 Linux

* Bazel version (output of `bazel info release`): 0.4.2

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

No.

### Anything else, information or logs or outputs that would be helpful?

my session:

    $ ./compile.sh
    INFO: You can skip this first step by providing a path to the bazel binary as second argument:
    INFO:    ./compile.sh compile /path/to/bazel
    Building Bazel from scratch.......
    Building Bazel with Bazel.
    .WARNING: /tmp/bazel_ayxCghhh/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel_ayxCghhh/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.
    ERROR: no such package '@bazel_tools//tools/jdk': BUILD file not found on package path.
    INFO: Elapsed time: 3.233s

The work-around:

    $ cp tools/jdk/BUILD.jdk7 tools/jdk/BUILD

It appears that tools/jdk/BUILD is being distributed with a jdk7 extension.  It looks like it should be renamed BUILD either during packaging or from compile.sh.

**Comment by damienmg** [comment]
No, it should use JAVA_VERSION=1.7

Either we should not distribute a -dist file for JDK7 or make sure they work out of the box
