### ISSUE TITLE
build rule ctx.action() without output

### ISSUE THREAD

**Issue by trivigy** [bazelbuild/bazel#2251]
In my use case I have some information generated during an action that I want to use in another action but is not a file but rather a file name. Is there a way to run something that is equivalent to `repository_ctx.execute()` inside of a regular rule?

**Comment by aehlig** [comment]
cc @dslomov @laurentlb as they know more about Skylark than I do.

**Comment by trivigy** [comment]
I kinda understand why this is not a part of the current stack. I think it's because with such feature people would be able to generate unpredictable `new_file()`. Either way, although for my specific problem I figured out a work around it would be nice to have a feature like that.

**Comment by laurentlb** [comment]
The analysis phase cannot depend on the result of a command (all dependencies are static).

We may allow more flexible use-cases in the future, but I'm closing this feature request for now.
