### ISSUE TITLE
[7.2.0] Add `NestedSet<PathFragment>`- and `Artifact`-typed compile build variables

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22533]
Forked from #22463

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/rules/cpp/CcCompilationHelper.java`
`src/main/java/com/google/devtools/build/lib/rules/cpp/CcToolchainVariables.java`
`src/main/java/com/google/devtools/build/lib/rules/cpp/CompileBuildVariables.java`
`src/main/java/com/google/devtools/build/lib/rules/cpp/CppLinkstampCompileHelper.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
cc: @comius @Wyverald @fmeum @lberki

**Comment by fmeum** [comment]
I sent https://github.com/bazelbuild/bazel/pull/22557
