### ISSUE TITLE
[7.2.0] Close the stdin pipe handle when the respective OutputStream is closed

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#22538]
### Commit IDs

b3f5c62d675ba9bf200e41cf755925b7242638d9

### Category

team-OSS

### Reviewers

@Wyverald, @iancha1992, @keertk

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/22539: https://github.com/bazelbuild/bazel/commit/b3f5c62d675ba9bf200e41cf755925b7242638d9.
