### ISSUE TITLE
[7.2.0] Wire up `oneversion` tool in `java_tools`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22576]
Forked from #22246

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`MODULE.bazel`
`MODULE.bazel.lock`
`src/tools/one_version/BUILD`

cc: @bazelbuild/triage

**Comment by fmeum** [comment]
https://github.com/bazelbuild/bazel/pull/22635
