### ISSUE TITLE
[7.2.0] Add layering_check support for macOS

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#22574]
### Commit IDs

de0a37c33c33bbb419f5003e382c96a25af81012

### Category

team-Rules-CPP

### Reviewers

@pzembrod, @Wyverald

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/22575: https://github.com/bazelbuild/bazel/commit/de0a37c33c33bbb419f5003e382c96a25af81012.
