### ISSUE TITLE
Skymeld deadlock in `registerAndPlantMissingSymlinks`

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/bazel#22586]
### Description of the bug:

In 7.2.0rc1 there is a deadlock in `registerAndPlantMissingSymlinks`. Probably caused by 52adf0b3d14d4af60ece33c95b94be058bafb41b. Turning off Skymeld fixes it for us (but brings with it other bugs that Skymeld fixed).

[jstack.txt](https://github.com/bazelbuild/bazel/files/15418655/jstack.txt)
[SIGINT.1.log](https://github.com/bazelbuild/bazel/files/15418756/SIGINT.1.log)
[SIGINT.2.log](https://github.com/bazelbuild/bazel/files/15418757/SIGINT.2.log)

### Which category does this issue belong to?

Performance

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 7.2.0rc1

**Comment by joeleba** [comment]
> Turning off Skymeld fixes it for us (but brings with it other bugs that Skymeld fixed).

@brentleyjones Could you please provide a list of these other bugs?

**Comment by brentleyjones** [comment]
I don't have a repro, sorry. It's based on an internal repo, and usually only happened in our indexing builds (frequent background builds that may get cancelled a lot).

The main other bug that Skymeld fixed and we are suffering from is the `.git` symlink planting (only Skymeld listens to `.bazelignore`).

**Comment by joeleba** [comment]
Brentley: I reached out to you on Slack. PTAL when you have time. Thanks!

**Comment by joeleba** [comment]
@bazel-io fork 7.2.0
