### ISSUE TITLE
[bazel.build] Problem with /rules/lib/providers/DefaultInfo

### ISSUE THREAD

**Issue by msiebuhr** [bazelbuild/bazel#22582]
### Page link:

https://bazel.build/rules/lib/providers/DefaultInfo

### Problem description (include actual vs expected text, if applicable):

> **Files**: A [depset](https://bazel.build/rules/lib/builtins/depset.html) of [File](https://bazel.build/rules/lib/builtins/File.html) objects representing the default outputs to build when this target is specified on the bazel command line. By default it is all predeclared outputs.

I read this as "files are the output _this rule will generate_", not "outputs that bazel will make sure is built before this rule is run".

### Where do you see this issue? (include link to specific section of the page, if applicable)

https://bazel.build/rules/lib/providers/DefaultInfo#files

**Comment by Wyverald** [comment]
> I read this as "files are the output _this rule will generate_", not "outputs that bazel will make sure is built before this rule is run".

I believe that's the correct reading? Providers are conceptually analogous to a rule's "outputs".
