### ISSUE TITLE
Exceptions 25% of builds - windows 7.2.0rc2

### ISSUE THREAD

**Issue by peakschris** [bazelbuild/bazel#22595]
### Description of the bug:

I'm seeing builds failing immediately with exceptions, around 25% of the time.

```
bazel build //...
Exception 0xc0000006 0x0 0x87790c 0x452ca0
PC=0x452ca0
```

```
bazel build //src/build/out:all
Exception 0xc0000006 0x0 0x78527b 0x4031ce
PC=0x4031ce
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

git clone https://github.com/peakschris/bazel7-conan-module-example
bazel build //...

### Which operating system are you running Bazel on?

windows

### What is the output of `bazel info release`?

release 7.2.0rc2

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Yes, am seeing it for the first time after switching to 7.2.0rc2

**Comment by Wyverald** [comment]
Could you try using [`bazelisk --bisect`](https://github.com/bazelbuild/bazelisk?tab=readme-ov-file#--bisect) to locate the culprit commit?

**Comment by peakschris** [comment]
I can't reproduce this now in my small workspace where I originally saw it. Can you give me any hints as to where this type of error can originate? I've never seen it before. I'll keep trying.

**Comment by peakschris** [comment]
I just saw this again with 7.2.0rc2, it's not 25% of builds, perhaps only 1-5%. I don't think it will be possible to bisect as it is so irregular, but I can try switching to a different commit for a while if you suspect something.

```
(.venv) D:\workdir\bazel7-conan-module-example>bazel --nosystem_rc --nohome_rc --windows_enable_symlinks build //...
Exception 0xc0000006 0x0 0x7895c5 0x4031ce
PC=0x4031ce
```

**Comment by malkia** [comment]
Is it possible, that you may have bad clusters on your drive?

**Comment by peakschris** [comment]
I'm not seeing this anymore in 7.3.x
