### ISSUE TITLE
Failure in `proto_lang_toolchain` with Bazel 7.2.0rc1

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#22607]
### Description of the bug:

Since https://github.com/bazelbuild/bazel/commit/d448e115eaa3acd12743c3077ab418f6eb2da3a0 (which is in 7.2.0rc1 but not 7.1.2), toolchain resolution with `--incompatible_enable_proto_toolchain_resolution` fails with an error in proto builtins.

### Which category does this issue belong to?

External Dependency

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```shell
$ git clone https://github.com/fmeum/with_cfg.bzl -b simplify-ci
$ cd with_cfg.bzl

$ USE_BAZEL_VERSION=e09b5369e4bca43eb7e007be6b7aea8713e88c33 bazel build //docs:all
...
INFO: Build completed successfully, 1 total action

$ USE_BAZEL_VERSION=d448e115eaa3acd12743c3077ab418f6eb2da3a0 bazel build //docs:all
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 78f076ac-d6d4-4933-8221-82c982a82ce5
ERROR: /Users/fmeum/git/with_cfg.bzl/docs/BUILD.bazel:14:21: in proto_lang_toolchain rule //docs:protoc_java_toolchain:
Traceback (most recent call last):
	File "/virtual_builtins_bzl/common/proto/proto_lang_toolchain.bzl", line 36, column 67, in _rule_impl
Error: 'NoneType' value has no field or method 'proto'
ERROR: /Users/fmeum/git/with_cfg.bzl/docs/BUILD.bazel:14:21: Analysis of target '//docs:protoc_java_toolchain' failed
Target //docs:protoc_java_toolchain failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: Analysis of target '//docs:defs' failed; build aborted: Analysis failed
INFO: Elapsed time: 4.919s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
```

### Which operating system are you running Bazel on?

Linux

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Yes, as indicated in the reproducer

**Comment by fmeum** [comment]
CC @Wyverald @comius

**Comment by fmeum** [comment]
After adding a few debug prints, it looks like the `ConfiguredTargetKey`s for the exec platforms aren't subject to consistent alias resolution, resulting in some lookups for `@@platforms//host:host` and some for `@@bazel_tools//tools:host_platform`. I haven't figured out where the difference comes from, but this ends up causing the mismatch due to which the toolchain ends up missing.

cc @katre

**Comment by fmeum** [comment]
@bazel-io fork 7.2.0

**Comment by katre** [comment]
I'll take a quick look, but here's my first question (probably for @comius based on the blame annotations):

Why is [`proto_common.bzl%_use_toolchain` claiming `mandatory = False`](https://cs.opensource.google/bazel/bazel/+/master:src/main/starlark/builtins_bzl/common/proto/proto_common.bzl;drc=e6167784b9e5381d4756bf7ec1b79092f1a3080b;l=371) when [the actual toolchain-using code](https://cs.opensource.google/bazel/bazel/+/master:src/main/starlark/builtins_bzl/common/proto/proto_lang_toolchain.bzl;drc=8b8c1302c6f21cea1af6ce21975d6882b06e0159;l=36) is not prepared to receive a `None`?

**Comment by katre** [comment]
And, as a matter of fact, setting `mandatory = True` causes your sample command to build, because now it can find a toolchain.

**Comment by katre** [comment]
More notes:

Setting a toolchain as optional means that it is not required that the toolchain is present to pick an execution platform. That means that, given execution platforms A and B (in that priority order), where A does not have a proto toolchain but B does, with the proto toolchain being optional, exec platform A will be chosen. (And, in the current `proto_lang_toolchain` code, the rule implementation that crashes trying to dereference a `None` value).

**Comment by fmeum** [comment]
@katre Thanks, that makes it pretty clear how to work around this problem. Since the build only involves a single (logical) exec platform, I would still not have expected optional vs. mandatory to make a difference here.

**Comment by katre** [comment]
I suspect the two exec platforms are due to the host aliasing issue. @Wyverald, were you able to debug that part?
