### ISSUE TITLE
[7.2.0] Failure in `proto_lang_toolchain` with Bazel 7.2.0rc1

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22608]
Forked from #22607

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/skyframe/toolchains/ToolchainResolutionFunction.java`
`src/test/shell/integration/toolchain_test.sh`

cc: @bazelbuild/triage

**Comment by keertk** [comment]
@katre would you mind submitting a PR against the release-7.2.0 branch for this please?

**Comment by katre** [comment]
Sure, doing that now, I'll send a PR shortly.

**Comment by keertk** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/22636
