### ISSUE TITLE
No ability to pass `copts` to `cc_proto_library`

### ISSUE THREAD

**Issue by chandlerc** [bazelbuild/bazel#22610]
### Description of the bug:

Currently, it is sometimes necessary to pass `copts` to `cc_library` rules to get the code to compile. This can even be true with the generated code compiled by `cc_proto_library`. Because there is a useful language-specific rule modeling the library for the generated code, it would make sense to expose similar C++ compilation options there as in `cc_library`.

### Which category does this issue belong to?

C++ Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Do a build with a C++ compiler that requires extra flags to correctly compile generated protobuf headers. There is no way to pass those flags to the compilation.

### Which operating system are you running Bazel on?

Linux

**Comment by cushon** [comment]
There's an existing FR for this in https://github.com/bazelbuild/bazel/issues/4446
