### ISSUE TITLE
About The local.bzl File

### ISSUE THREAD

**Issue by jiushun** [bazelbuild/bazel#22612]
hi, i want to know Which version contains the local.bzl functionality

in version 6.5.0, i can not find this file. and how can I use it

**Comment by fmeum** [comment]
It's in 7.2.0rc1 and later. The docs show the state of `master` by default.

**Comment by allsey87** [comment]
Quick side note. It is way too difficult at the moment if I am looking at, for example, https://bazel.build/rules/lib/repo/local and want to switch back to the 7.1.x version of the documentation.

**Comment by brentleyjones** [comment]
@meteorcloudy I agree with this. Where do we stand on having the better version selection (and `HEAD` _not_ being the default)?

**Comment by meteorcloudy** [comment]
Unfortunately this isn't much progress, I did some investigation into Google's DevSite doc this morning again, still couldn't find a nice way to either make the default the latest version or stay on the same page after switching version.. sorry..

/cc @fweikert
