### ISSUE TITLE
Clarification - Azul Zulu Vulnerability Within Bazel?

### ISSUE THREAD

**Issue by emilygaosalesforce** [bazelbuild/bazel#22625]
## Intro
Although this topic falls under Vulnerability Management, the security policy [here](https://github.com/bazelbuild/bazel/security/policy) doesn't allow us to request information on whether something is vulnerable as suggested by some third party. I hope I can create comms here through opening a Bug Issue.

## Description
After Tenable published [this](https://www.tenable.com/plugins/nessus/193814) plugin in April, we've noticed it detecting vulnerable versions of Azul Zulu Java JDK within Bazel. For instance, within Bazel v.7.1.2, Azul Zulu Java JDK v21.28.85 is embedded by default [here](https://github.com/bazelbuild/bazel/blob/7.1.2/repositories.bzl#L65), and versions 21 < 21.33.14 are claimed to be vulnerable by Azul Zulu.

What we're trying to figure out, instead of continuously upgrading Bazel & awaiting upstream patches, is whether the vulnerabilities (various Oracle Java vulnerabilities that impact Azul Zulu, because Azul Zulu uses Oracle Java, as indicated by Tenable and [this](https://docs.azul.com/core/release/april-2024/release-notes#fixed-common-vulnerabilities-and-exposures) security advisory) actually impact Bazel. 

From [this](https://www.tenable.com/plugins/nessus/193814) Tenable page, we can see quite a few of these CVEs only "applies to Java deployments, typically in clients running sandboxed Java Web Start applications or sandboxed Java applets, that load and run untrusted code (e.g., code that comes from the internet) and rely on the Java sandbox for security. This vulnerability does not apply to Java deployments, typically in servers, that load and run only trusted code (e.g., code installed by an administrator)."

We'd like to confirm with Bazel that the way in which Bazel uses Azul Zulu JDK exempts it from these vulnerabilities.
I deduced from [this](https://bazel.build/docs/bazel-and-java#config-jvm) and [this](https://bazel.build/docs/bazel-and-java#compile-using-jdk) that it's used for compilation, but I don't know if I'm missing some part of the scope of use. While it's highly likely that this way Bazel uses Azul Zulu to interact with code doesn't mean Bazel is vulnerable in the ways described by Tenable, it would be great to get this validated, or bring this to the attention of the team.

### Which category does this issue belong to?

External Dependency

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Download Bazel version 4.0.0, 6.5.0, or 7.0.0 (the only versions we've tested)
2. Inspect the default embedded jdk for its version (Inspect `*/embedded_tools/jdk`)
3. We can see that it's a vulnerable version (Azul Zulu Java JDK versions 6 < 6.63.0.14 / 7 < 7.69.0.14 / 8 < 8.77.0.14 / 11 < 11.71.14 / 17 < 17.49.16 / 21 < 21.33.14 / 22 < 22.30.14)

Or: check the most recent LTS version of Bazel, and observe [this](https://github.com/bazelbuild/bazel/blob/7.1.2/repositories.bzl#L65) `embedded_jdk_repositories` method to see what version of Zulu is embedded

### Which operating system are you running Bazel on?

Ubuntu

### What is the output of `bazel info release`?

N/A

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
N/A
```

**Comment by Wyverald** [comment]
As far as I know, Bazel does not run any untrusted code in the JVM itself (only as subprocesses), or rely on the Java sandbox (whatever that is) for security.

cc'ing some people who might know more, but it seems to me that there's no action to be taken here. @meisterT @tjgq @oquenchil

**Comment by meisterT** [comment]
* The embedded JDK is exclusively used as default JVM to run the Bazel server on, so this should be a non-issue. In case you want to use a different JVM to run the Bazel server on, you can select it with `--server_javabase`.
* `--tool_java_runtime_version` sets the JDK for tools in the exec configuration, such as compilers running on the JVM, e.g. `JavaBuilder`. I think the current default is `remotejdk11` which is in turn pointing to an affected JDK if I understand it correctly (see https://github.com/bazelbuild/rules_java/blob/master/java/repositories.bzl#L183).
* `--java_runtime_version` sets the JDK for tests and binaries that you run, e.g. through `bazel test`. The default value for this one is `local_jdk`, so it checks `JAVA_HOME` and your path.

cc @hvadehra to double check what I wrote is correct and potentially update the remote JDKs.

(Historically, the embedded JDK was exposed and could be selected as javabase or host javabase, but that was changed pre Bazel 1.0.)

**Comment by fmeum** [comment]
> `--tool_java_runtime_version` sets the JDK for tools in the exec configuration, such as compilers running on the JVM, e.g. `JavaBuilder`. I think the current default is `remotejdk11` which is in turn pointing to an affected JDK if I understand it correctly (see https://github.com/bazelbuild/rules_java/blob/master/java/repositories.bzl#L183).

This is not fully correct, `JavaBuilder` forcibly uses JDK 21 (see https://github.com/bazelbuild/rules_java/blob/3c72e8444e459ea6e094677722f5017c39a34c88/toolchains/default_java_toolchain.bzl#L96). But other exec tools such as `genrule` tools written in Java will use the runtime specified by `--tool_java_runtime_version`, which defaults to `remotejdk_11`.

**Comment by emilygaosalesforce** [comment]
If I understand this correctly:
- Since the Bazel server is not untrusted code, we don't need to worry about the embedded JDK being vulnerable in the way described -> this is what we wanted to confirm, thank you!! 🙏 
- There are ways to specify JDKs other than the embedded ones (`--tool_java_runtime_version` and `--java_runtime_version`)
- It is possible to update the remote JDKs throughout the different functions in `repositories.bzl`, and the team is looking into whether that can be done
- If the above is pursued, it would be good if the versions could be updated to at least: `6.63.0.14`, `7.69.0.14`, `8.77.0.14`, `11.71.14`, `17.49.16`, `21.33.14`, `22.30.14` as indicated by [this](https://docs.azul.com/core/release/april-2024/release-notes#fixed-common-vulnerabilities-and-exposures) security advisory

**Comment by meisterT** [comment]
> There are ways to specify JDKs other than the embedded ones (--tool_java_runtime_version and --java_runtime_version)

To be precise: you cannot use the embedded JDK for any of `--{,tool_}java_runtime_version`, not by default and not explicitly. But you can set it to a remotejdk that is vulnerable. Whether that is a concern depends on the user and usecase.

**Comment by meisterT** [comment]
@peakschris this is not the embedded JDK (also pointed out on the issue you reference: https://github.com/bazelbuild/rules_jvm_external/issues/445#issuecomment-673810702).

**Comment by peakschris** [comment]
Ah, I missed that reply to the issue. Thank you for clarifiying, it's good to know.

**Comment by Wyverald** [comment]
Given the discussion above, Bazel is most likely not affected. I'm going to go ahead and close this.

**Comment by hvadehra** [comment]
Status update: `rules_java` `v7.6.2` has been released (and published to the BCR). The default zulu remotejdk versions in use are now: `8.78.0.19-ca-jdk8.0.412`, `11.72.19-ca-jdk11.0.23`, `17.50.19-ca-jdk17.0.11`, `21.34.19-ca-jdk21.0.3`

Updating in Bazel@HEAD to follow.
