### ISSUE TITLE
Cleanup debian repository set-up

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2264]
After #2256 investigation:

  1. We are using format 1.0 and we should probably use format 3.0 (quilt) but that requires a better tuning for dpkg-source
  2. As a workaround #2256, we manually now tune the dsc file, we should find the correct way to fix it.
  3. version.txt and changelog does not returns the same version number, we should unite them (make the change to add the ~ to changelog and then use that version number to

**Comment by meisterT** [comment]
@meteorcloudy is this something the debian team could help us out with?

**Comment by meteorcloudy** [comment]
I think the 2 & 3 points are no problem anymore.

As for transform from format 1.0 to 3.0, I can check what we can upstream back to Bazel when we have the Debian package. But I don't think this is urgent.
