### ISSUE TITLE
`proto_library` can't build generated `srcs`.

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/bazel#2265]
Repro:

```
proto_library(name = "generated_proto", srcs = ["generated.proto"])
genrule(name = "generator", outs = ['generated.proto'], cmd = "echo 'syntax = \"proto2\";' > $@")
```

When building `:generated_proto`,

    generated.proto: No such file or directory

**Comment by cheister** [comment]
Are there any plans to look at this to unblock https://github.com/bazelbuild/bazel/issues/2763?

**Comment by buchgr** [comment]
Fix coming: https://bazel-review.googlesource.com/#/c/10473/

**Comment by buchgr** [comment]
This change was rolled back cause it broke builds inside google. Still investigating why.

**Comment by buchgr** [comment]
@cheister 

Unfortunately it will take a bit to resolve this problem. There is an inconsistency between the protobuf compiler inside and outside of google [1]. We are looking at a proper fix that works for both environments and will likely involve some changes by the protobuf team.

I am very sorry about that :-(.

[1] https://github.com/google/protobuf/issues/3022

**Comment by buchgr** [comment]
Update: We have resolved the issue internally. Will attempt to fix this asap.

**Comment by xfxyjwf** [comment]
@buchgr Did you get a chance to reattempt your fix in bazel?

**Comment by buchgr** [comment]
Not yet. Will within the next few weeks, when I can set aside some time.

**Comment by buchgr** [comment]
The fix is in again. I ll cherry-pick it into the 0.5.4 release.
