### ISSUE TITLE
java_tools v13.5 causes excessive warnings related to missing annotation jars

### ISSUE THREAD

**Issue by honnix** [bazelbuild/bazel#22661]
### Description of the bug:

After upgrading to rules_java 7.5.0, which I believe bumps java_tools from 13.4 to 13.5, we have been observing excessive warnings related to missing annotation jars, for example: `bazel-out/.../header-foo.jar(Foo.class): warning: Cannot find annotation method 'value()' in type 'JsonPropertyOrder': class file for com.fasterxml.jackson.annotation.JsonPropertyOrder not found`.

These are just warnings and don't fail the build even we have `-Werror` enabled.

### Which category does this issue belong to?

Java Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build any target that depends on a jar which contains a class with annotations.

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 7.2.0rc2

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Not sure whether this is a regression or not, but I managed to identify the commit that results in this behaviour change. I wrote down some details here https://github.com/bazelbuild/bazel/commit/8aedcc4b36f3b5d534263d33e15de6a5cff076d3#r142814732

**Comment by fmeum** [comment]
Cc @cushon

**Comment by cushon** [comment]
Interesting, thanks for the report and the investigation.

I think the interaction with fallback was unexpected here. If fallback was previously happening unnecessarily for these warnings and now isn't that's a good thing for performance, because the fallback is expensive.

But also the warnings are annoying and not actionable, so even if we don't want to fall back to avoid them, it would be nice to avoid them or possible just suppress them.

**Comment by honnix** [comment]
Indeed it is a good thing to avoid the fallback. This specific warning can be suppressed by `-Xlint:-classfile`, but that might also hide some real problems unfortunately. Another thing I don't fully understand is that why the fallback compilation does not result in those warnings. Does it mean the "reduced" classpath does not contain those jars while the fallback one does?

**Comment by cushon** [comment]
> Does it mean the "reduced" classpath does not contain those jars while the fallback one does?

Yes exactly, the 'reduced classpath' is a performance optimization that uses a heuristic to compile against a subset of the jars on the classpath. The heuristic isn't perfect, so it retries with the full classpath if it fails.

**Comment by honnix** [comment]
I see. Then it makes sense to "ignore" non-error warnings for sure. I will try to see what other problem could be caught by `-Xlint:classfile` to see whether it is totally safe to suppress.

Thank you for looking into this and explaining.

**Comment by honnix** [comment]
I couldn't find anything critical could be caught by `-Xlint:classfile`, so I will suppress this.

Please feel free to close this issue if you would like to keep this happy side effect :)
