### ISSUE TITLE
Crash when py_binary target's name clashes with dir of main src file

### ISSUE THREAD

**Issue by quittle** [bazelbuild/bazel#2267]
There is a bug where `py_binary` targets cannot have a `main` file whose folder matches the `name` of the target.

### If possible, provide a minimal example to reproduce the problem:
See https://gist.github.com/quittle/777a423f3de3e6037ceacf3927272c74 for a gist example

Essentially if you have a BUILD file like this and try doing `bazel run folder_name`, you will get a runtime error.
```
py_binary(
    name = "folder_name",
    srcs = [ "folder_name/main.py" ],
    main = "folder_name/main.py",
)
```
```
Traceback (most recent call last):
  File "/home/bazel-user/.cache/bazel/_bazel_bazel-user/4d8c2c628ef670120421904b22dfae5b/execroot/py_binary_test/bazel-out/local-fastbuild/bin/folder_name", line 140, in <module>
    Main()
  File "/home/bazel-user/.cache/bazel/_bazel_bazel-user/4d8c2c628ef670120421904b22dfae5b/execroot/py_binary_test/bazel-out/local-fastbuild/bin/folder_name", line 114, in Main
    'Cannot exec() %r: file not found.' % main_filename
AssertionError: Cannot exec() '/home/bazel-user/.cache/bazel/_bazel_bazel-user/4d8c2c628ef670120421904b22dfae5b/execroot/py_binary_test/bazel-out/local-fastbuild/bin/folder_name.runfiles/example_of_broken_py_binary/folder_name/main.py': file not found.
```

### Environment info
* Operating System:
Ubuntu 16.04
`Linux bazel-user-VirtualBox 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

* Bazel version (output of `bazel info release`):
`release 0.4.2`

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
N/A

**Comment by yuanzhedong** [comment]
Get the same error on Mac 10.12.1 and bazel 0.9.0

**Comment by brandjon** [comment]
This makes sense because `py_binary` is an executable rule, so it produces an executable artifact whose name is the same as the label, which would conflict with the directory name. But it should fail with a clean error at analysis time, not a stack trace while running the python artifact.

**Comment by jxramos** [comment]
still seeing this as of
```bash
$ bazel --version
bazel 4.2.1-1.3
```

**Comment by keith** [comment]
can we just make the rules error with a nice error message for this case? it's pretty inscrutable today
