### ISSUE TITLE
local_path_override doesn't get invalidated for MODULE.bazel file creation

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/bazel#22687]
### Description of the bug:

If you set a local_path_override to a directory which doesn't contain a MODULE.bazel, then create one, a subsequent build will continue to complain that the file didn't exist.

### Which category does this issue belong to?

External Dependency

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```console
% mkdir root_module 
% mkdir loaded_module
% cat >root_module/MODULE.bazel <<EOF     
bazel_dep(name = "loaded_module")

local_path_override(module_name = "loaded_module", path="$(pwd)/loaded_module")
EOF
% cat >root_module/BUILD.bazel <<EOF      
filegroup(name = "fg")           
EOF
% cd root_module
% bazel query ...
ERROR: <builtin>: fetching local_repository rule //:loaded_module~: java.io.IOException: No MODULE.bazel, REPO.bazel, or WORKSPACE file found in /Users/dwagnerhall/tmp/repro/loaded_module
ERROR: Error computing the main repository mapping: error during computation of main repo mapping: No MODULE.bazel, REPO.bazel, or WORKSPACE file found in /Users/dwagnerhall/tmp/repro/loaded_module
% cat >../loaded_module/MODULE.bazel <<EOF
module(name = "loaded_module")   
EOF
% bazel query ...
ERROR: <builtin>: fetching local_repository rule //:loaded_module~: java.io.IOException: No MODULE.bazel, REPO.bazel, or WORKSPACE file found in /Users/dwagnerhall/tmp/repro/loaded_module
ERROR: Error computing the main repository mapping: error during computation of main repo mapping: No MODULE.bazel, REPO.bazel, or WORKSPACE file found in /Users/dwagnerhall/tmp/repro/loaded_module
% bazel shutdown
% bazel query ...
Starting local Bazel server and connecting to it...
//:fg
```

The `query` _before_ the `shutdown` should have worked because the situation on disk was resolved and the repository fetch should have been invalidated by the filesystem changes.

Note that sometimes the first query only prints the second error not the first - when that happens, the first query after creating the MODULE.bazel file _will_ work.

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 7.2.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.3.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.3.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=7.3.0rc1`. Thanks!
