### ISSUE TITLE
Cherry-pick fix to make Protobuf work with sibling repository layout into Bazel 7.3

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#22682]
### Commit IDs

7048ef5eb5395679241f2321a8104b26ecee01c0

### Category

team-Rules-CPP

### Reviewers

@Wyverald

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/22683: https://github.com/bazelbuild/bazel/commit/7048ef5eb5395679241f2321a8104b26ecee01c0.
