### ISSUE TITLE
[7.3.0] Remove objc_library transition

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22686]
Forked from #20084

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/starlark/builtins_bzl/common/objc/j2objc_library.bzl`
`src/main/starlark/builtins_bzl/common/objc/transitions.bzl`
`src/test/java/com/google/devtools/build/lib/rules/objc/ObjcRuleTestCase.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/starlark/builtins_bzl/common/objc/j2objc_library.bzl` `src/main/starlark/builtins_bzl/common/objc/transitions.bzl` `src/test/java/com/google/devtools/build/lib/rules/objc/ObjcRuleTestCase.java`
> 
> cc: @bazelbuild/triage

cc: @keith @brentleyjones @comius @meteorcloudy

**Comment by meteorcloudy** [comment]
If this is too complicated we can drop this for 7.3.0, we found a workaround to remove the apple_support dependency (overriding apple_support to a dummy module with --override_module).

**Comment by keith** [comment]
I don't really have a preference but here's a manual cherry pick https://github.com/bazelbuild/bazel/pull/22880

**Comment by meteorcloudy** [comment]
I'll close this for now since it seems to require non-trivial effort to backport.
