### ISSUE TITLE
Allow specifying C++ only compiling options

### ISSUE THREAD

**Issue by zetachang** [bazelbuild/bazel#2268]
### Description of the problem / feature request / question:

Currently, `objc_library` allow C, C++, Objective-C, and Objective-C++ sources. But when I pass a C++ compiler only options to `copts`, it will fail on non C++ sources.

```py
objc_library(
    name="bar",
    srcs=["foo.mm", "foo.m"],
    copts=['-std=c++1y'],
)
```

The above snippet work if `srcs` contains only Objective-C++ sources, but fail with message `error: invalid argument '-std=c++1y' not allowed with 'C/ObjC'` if providing both Objective-C & Objective-C++ sources.

What I am looking for is something like `OTHER_CPLUSPLUSFLAGS` provided by Xcode.

### Environment info
* Operating System: OS X 10.11.6
* Bazel version (output of `bazel info release`): release 0.4.2-homebrew

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
