### ISSUE TITLE
[feature request] Is it possible to add extra build modes without modifying Bazel?

### ISSUE THREAD

**Issue by ahyangyi** [bazelbuild/bazel#2271]
OK, this is a feature request. I'd like to have more build modes than the built-in `fastbuild`, `dbg` and `opt`.

For example, our engineers want a build mode with lots of extra debug information (for example, without -DNDEBUG) but still built with -O2. Currently we do with `-c dbg -copt -O2` but that's clearly a hack that we don't want to maintain forever.

I suggested to re-interpret `fastbuild` since we do not really use it currently. However we recognized that's probably a poor decision, since that would make `fastbuild` a misnomer and waste everyone's time to understand the reason behind that.

So ideally, Bazel should provide a way to add extra compilation modes in configuration files like `CROSSTOOLS` or some `BUILD` file. I'd like to see this happening, and I'll be interested in knowing if other Bazel users also have similar needs.

Hopefully, I think this feature request aligns well with the general direction that Bazel is facing towards: moving hardcoded rules out of the Bazel core and allowing users to modify them in their workspaces.

Thanks a lot ;)

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
