### ISSUE TITLE
Conflict in cherry-pick lose the cherry-pick from the release notes

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2272]
Discovered in #2246, cherry-picking bce889840f91f14c05418d960984bcf1a5f59411 in plus actually adds the missing release note.

Fixing the problem is tricky. We do not store the original commit when cherry-picking and resort to the patch being the same. A solution might be to store as a git note for each commit the commit it was cherry-picked from and just resort to finding the original commit if the git note does not exists.

**Comment by iirina** [comment]
Actually it was commit 76c857b20d5ece4cdaf8c610d997fb2a93616787 that was cherry picked, not bce889840f91f14c05418d960984bcf1a5f59411.

**Comment by damienmg** [comment]
I know I meant if you take bce8898 before 76c857b then 76c857b appears in the history
