### ISSUE TITLE
Use worker threads for module extension eval

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#22729]
As `--experimental_worker_for_repo_fetching` gets more testing in the wild, we can start considering using worker threads for module extension eval too. That would open up the possibility of completely getting rid of restarts. This would potentially mitigate issues such as https://github.com/bazelbuild/bazel/issues/22710.

We'd ideally address some straggler issues like https://github.com/bazelbuild/bazel/issues/22680 first.

**Comment by DavidZbarsky-at** [comment]
@Wyverald does it make sense to fix this as part of the bzlmod push for Bazel 8? This is one of the remaining areas where bzlmod is a regression over WORKSPACE (for example `rules_js` needs to convert the pnpm lockfile from yaml to json and then parse it to discover all the patches, and then each patch it touches triggers the restart behavior, so it's quite slow)

**Comment by Wyverald** [comment]
Makes sense to me. I'll raise the priority of this.

**Comment by criemen** [comment]
Is this something you'd feel comfortable to pull into 7.4.0?

**Comment by Wyverald** [comment]
> Is this something you'd feel comfortable to pull into 7.4.0?

Sent https://github.com/bazelbuild/bazel/pull/23504
