### ISSUE TITLE
"select" can't be used for dictionary keys

### ISSUE THREAD

**Issue by trimbo** [bazelbuild/bazel#2273]
Example would be:

pkg_tar(
  symlinks = {select({"if_cond": "key1", "other_cond": "key2"}): "map to me"}

Gives error:

unhashable type: 'select'.

**Comment by gregestren** [comment]
It's pretty intrinsic to select that its values have to match the attribute's underlying type. So in this case the select would have to map conditions to dictionaries. This is unlikely to change.

I'd write a Skylark macro to get what you want. If it's as simple as the syntax above, you could write a macro that returns a select where `if_cond` produces `{"key1": "map to me"}` and `other_cond` produces `{"key2": "map to me"}`.

You should be able to encode more complicated combinations accordingly, but pipe in here if you have trouble.

**Comment by trimbo** [comment]
Thanks Greg, makes sense.
