### ISSUE TITLE
[Mirror]  python 

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#22735]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/indygreg/python-build-standalone/releases/download/20240415/cpython-3.8.19+20240415-x86_64-unknown-linux-gnu-install_only.tar.gz
https://github.com/indygreg/python-build-standalone/releases/download/20240415/cpython-3.8.19+20240415-x86_64-apple-darwin-install_only.tar.gz

**Comment by satyanandak** [comment]
Here you go
https://mirror.bazel.build/github.com/indygreg/python-build-standalone/releases/download/20240415/cpython-3.8.19+20240415-x86_64-unknown-linux-gnu-install_only.tar.gz
https://mirror.bazel.build/github.com/indygreg/python-build-standalone/releases/download/20240415/cpython-3.8.19+20240415-x86_64-apple-darwin-install_only.tar.gz
