### ISSUE TITLE
[7.3.0] NPE in `CompletionFunction`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22769]
Forked from #22741

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/skyframe/CompletionFunction.java`

cc: @bazelbuild/triage

**Comment by coeuvre** [comment]
Actually, the fix doesn't apply to 7.x branches because the code is different. Closing.

**Comment by Wyverald** [comment]
https://github.com/bazelbuild/bazel/pull/22827
