### ISSUE TITLE
[7.3.0] Enforce and await cleanup in `StarlarkBaseExternalContext`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22776]
Forked from #22772

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalFunction.java`
`src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryFunction.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalFunction.java` `src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryFunction.java`
> 
> cc: @bazelbuild/triage

cc: @fmeum @Wyverald @meteorcloudy

**Comment by fmeum** [comment]
@iancha1992 This needs https://github.com/bazelbuild/bazel/pull/22794, please retry the cherry-pick after that has been merged.

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalFunction.java`
`src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryFunction.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
@fmeum  I am still not able to cherry-pick this on my own :(

**Comment by fmeum** [comment]
I sent https://github.com/bazelbuild/bazel/pull/22883
