### ISSUE TITLE
Build 0.4.2 from source failed under ubuntu 16.04

### ISSUE THREAD

**Issue by zhengwx11** [bazelbuild/bazel#2277]
```
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch
ERROR: Must specify PROTOC if not bootstrapping from the distribution artifact; NOTE: development versions are built with 'bazel build //src:bazel'
```

This is what I got when I ran  `$ bash ./compile.sh`.

The [guide](https://bazel.build/versions/master/docs/install.html#compiling-from-source) did not provide any information about `PROTOC` or a pre-request list (I guesss it is a pre-request problem).

The java version is `openjdk-8-jdk`

**Comment by aehlig** [comment]
The error message indicates that you are trying to compile from a checkout rather than from a dsitribution archive as the instructions tell.

(In case you wonder why this is necessary, the design can be found at https://bazel.build/designs/2016/10/11/distribution-artifact.html)
