### ISSUE TITLE
Docs for using aspects don't obviously link to reference on the aspect function

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#2278]
I could not find a single link from https://bazel.build/versions/master/docs/skylark/aspects.html to https://www.bazel.io/versions/master/docs/skylark/lib/globals.html#aspect. Immediately after reading the first page, I wanted to go to the second page and read more details about how to use the feature I just read about.

**Comment by jin** [comment]
Documented in https://docs.bazel.build/versions/master/skylark/aspects.html#aspect-definition
