### ISSUE TITLE
bazel --version returns no_version when built from git

### ISSUE THREAD

**Issue by bhuntsman** [bazelbuild/bazel#22798]
### Description of the bug:

If I download the 7.2.1rc1-dist archive and perform a bootstrap build, the resulting binary returns the following:

```bazel 7.2.0- (@non-git)```

However, if I then want to bulid from git:

```
git clone https://github.com/bazelbuild/bazel.git
cd bazel
git checkout -b release-7.2.1rc1 origin/release-7.2.1rc1
../bazel-7.2.1rc1-dist/output/bazel build //src:bazel --compilation_mode=opt
```

The resulting build doesn't return a version:
```
$ bazel-bin/src/bazel --version
bazel no_version
```

Is this a bug, or am I doing something wrong?  Is there a documented procedure for how to build a specific release from the git repo directly, instead of downloading a zip archive at the specific release level?

Many thanks!

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

git clone https://github.com/bazelbuild/bazel.git
cd bazel
git checkout -b release-7.2.1rc1 origin/release-7.2.1rc1
bazel build //src:bazel --compilation_mode=opt
bazel-bin/src/bazel --version

### Which operating system are you running Bazel on?

Linux Ubuntu 20.04 ppc64le

**Comment by bhuntsman** [comment]
I can confirm that this occurs with 7.2.1rc2 as well, on both ppc64le and x86_64.
In both cases the host OS is Ubuntu 20.04.

**Comment by bhuntsman** [comment]
The bot just closed this without anyone putting any commentary on it.
So the implication is that this is not a bug?  Doesn't that at least mean that the documentation is wrong and should be updated referencing this issue?

**Comment by fmeum** [comment]
The bot closed it as completed due to this commit being merged that marks the issue as fixed: https://github.com/bazelbuild/bazel/commit/3f93d377d036d773fd505a18e084425a00fb94ea

**Comment by bhuntsman** [comment]
The merge clarifies the documentation to a degree, but still does not answer if this issue is a bug (ie, should a build from git automatically add a version string?), nor does it clarify why there is apparently some amount of logic in compile.sh to build using bazel and what that's for, nor does it document how to create an actual "release" build from git.

Thank you.
