### ISSUE TITLE
zsh completion prints bazels info about startup options 

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#2279]
When auto completing after bazel test I get the following output.

```
endobson@yggdrasil () ~/proj/racket/yaspl2 % bazel test INFO: Reading 'startup' options from /Users/endobson/.bazelrc: --watchfs                                                                                                       (1)
 azel            bazel-bin@       bazel-genfibazel test
```

My bazelrc uses the watchfs startup option which makes bazel output that line.

Versions:
```
endobson@yggdrasil () ~/proj/racket/yaspl2 % bazel version                                                                                                                                                                             (1)
INFO: Reading 'startup' options from /Users/endobson/.bazelrc: --watchfs
Build label: 0.4.0-2016-11-22 (@984d6d4)
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 23 05:22:12 2016 (1479878532)
Build timestamp: 1479878532
Build timestamp as int: 1479878532
endobson@yggdrasil () ~/proj/racket/yaspl2 % zsh --version                                                                                                                                                                             (0)
zsh 5.0.8 (x86_64-apple-darwin15.0)
```

**Comment by mmlac** [comment]
I see the issue as well but my prompt immediately jumps to the next and displays the autocomplete correctly. Is that happening for you as well and it's more of a cosmetic issue or are you stuck with the INFO.... in the prompt?

I'm using yadr / pretzo and it looks like that for me, [_] being the cursor:

```
$ bazel test [HIT TAB]
```
```
bazel test ...INFO: Reading 'startup' options from ...../.bazelrc: --watchfs
$ bazel test [_]
 -- BUILD package --
lib:          lib/          main:         main/         test:         test/         third_party/  tools/ 

```

and at this point I can just use it as normal, just have that weird echo line in the history.

**Comment by endobson** [comment]
The info line is not in the shells buffer just in the terminals view, so in that sense it is cosmetic. But I never have had this issue with blaze only bazel, so it seems like it should be solvable.

**Comment by aehlig** [comment]
The cosmetic issue is fixed by https://bazel-review.googlesource.com/c/12550/

What remains is the design question whether it is generally a good idea to
unconditionally print the startup options.

CC: @lfpino

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle
