### ISSUE TITLE
Docs for XML_OUTPUT_FILE are incomplete

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#2280]
The docs for `XML_OUTPUT_FILE` say that it expects an "`ANT` like XML output file". A quick google search turns up nothing related to test output for "ant xml output file".

I would expect bazel to document its expected format in enough detail for someone to implement a new test rule that can generate the output and have the test runner understand it.

**Comment by jin** [comment]
This XML schema is documented internally. Let me see if we can make it available publicly.

**Comment by ulfjack** [comment]
@jin you need to be careful here - I believe Google internally uses a different XML schema, even if the filenames are identical.

Here's a link with more discussion around the format (not Bazel-specific):
https://stackoverflow.com/questions/442556/spec-for-junit-xml-output

**Comment by jin** [comment]
@ulfjack thanks. I'm realized that it's based off the JUnit XML format, but I'm also wondering if we added any Blaze/Bazel specific extensions to that.

**Comment by ulfjack** [comment]
@jin not that I am aware of. @lberki or Eduardo (not sure if he's on GitHub) might know more. However, there isn't a clear spec to start with, so it may be that what Bazel is doing differs from what the others are doing.

**Comment by jin** [comment]
Thanks! I will ping them into the internal thread.
