### ISSUE TITLE
[Mirror] additional files referenced by rules_go v0.47.1

### ISSUE THREAD

**Issue by malt3** [bazelbuild/bazel#22800]
### Please list the URLs of the archives you'd like to mirror:

> (They are all referenced here: https://github.com/bazelbuild/rules_go/blob/v0.47.1/go/private/repositories.bzl)

- https://github.com/golang/sys/archive/refs/tags/v0.19.0.zip
          
- https://github.com/golang/xerrors/archive/104605ab7028f4af38a8aff92ac848a51bd53c5d.zip

- https://github.com/googleapis/go-genproto/archive/8c6c420018be7d99c6336d84554d856523d514bf.zip

**Comment by satyanandak** [comment]
Here you go
https://mirror.bazel.build/github.com/bazelbuild/rules_go/blob/v0.47.1/go/private/repositories.bzl
https://mirror.bazel.build/github.com/golang/sys/archive/refs/tags/v0.19.0.zip
https://mirror.bazel.build/github.com/golang/xerrors/archive/104605ab7028f4af38a8aff92ac848a51bd53c5d.zip
https://mirror.bazel.build/github.com/googleapis/go-genproto/archive/8c6c420018be7d99c6336d84554d856523d514bf.zip
