### ISSUE TITLE
MODULE.bazel git_override doesn't understand repo_name overrides?

### ISSUE THREAD

**Issue by 12wrigja** [bazelbuild/bazel#22807]
### Description of the bug:

Repro: https://github.com/12wrigja/bazel_git_override_demo

Context: I'm trying to use a version of rules_apko that hasn't been released yet, and from reading over https://bazel.build/rules/lib/globals/module#git_override my understanding was that I could override rules_apko with the repo and the content from that repo should be used as my dependency, instead of the upstream version.

When running acommand that uses that repository, it fails in two surprising ways:

Command: `bazel run @rules_apko//:apko -- lock ./ddclient_apko_image_config.yaml`

 - it complains that it find the name `bazel_gazelle`, but that is clearly documented as a repo_name override on the corresponding bazel_dep: https://github.com/chainguard-dev/rules_apko/blob/b097884460969fc5852d7f29c7c4c1a4d5651c29/MODULE.bazel#L22
  - it is complaining about a dependency that is marked as a dev_dependency, which seems weird to me as my intuition was that those should only matter if that repo was the root repository (though I could understand if that was incorrect given that I'm cloning a git repo as the source and maybe there are some pre-publish steps that would be missing in that state that would only be correctable via dev_dependencies).
  
  Is this the right way to go about overriding a single direct dependency, and if so why can't Bazel find that name when it is clearly marked in that module's MODULE.bazel?

### Which category does this issue belong to?

External Dependency

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Clone https://github.com/12wrigja/bazel_git_override_demo

run `bazel run @rules_apko//:apko -- lock ./ddclient_apko_image_config.yaml`

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 7.1.0

**Comment by fmeum** [comment]
I think that you should be running `@rules_apko//apko`, not `@rules_apko//:apko`. The latter doesn't seem to exist and loads the root package's `BUILD` file, which then attempts to load `@bazel_gazelle`. But Gazelle is only a dev dependency and thus not available since your own module is the root module, not rules_apko.

**Comment by 12wrigja** [comment]
Thanks - you are correct that I wasn't running the right target.
