### ISSUE TITLE
January release

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2282]
If we are on time this can be 0.5

**Comment by damienmg** [comment]
Volunteering @mhlopko :)

**Comment by mhlopko** [comment]
Yay! 👍 :)

**Comment by damienmg** [comment]
go/bazel-release for the how-to

**Comment by cgrushko** [comment]
When can we expect a release? I currently have to tell people to build Bazel from head to use `java_proto_library` 😄

**Comment by damienmg** [comment]
We have only one blocker and I got LGTM for all the code so I guess next
week if we can make the CI green. There are several important fixes in that
release (invalidation of repository, flaky tests, repository naming,
Windows output base) so we definitely want to have it soonish

**Comment by petemounce** [comment]
As ever, please ping me for RCs. Ta.

**Comment by Helcaraxan** [comment]
Question: I currently have some external dependency (protobuf actually) throwing warnings with Bazel 0.4.3 w.r.t `HOST_CFG` and `DATA_CFG` being deprecated in favor of the `host` and `data` variables. Is this going to be turned to errors soon or will it still be warnings for the new 0.5 release? Need to know if we need to schedule a protobuf upgrade ASAP or if we have a little bit more time.

Otherwise looks awesome with the bugfixes & features that are coming in 0.5. Great work Bazel team!

**Comment by vladmos** [comment]
The variables `HOST_CFG` and `DATA_CFG` will be removed in the next release, I suggest you replace them with the strings `"host"` and `"data"` asap.

In fact the change has already been committed: https://github.com/bazelbuild/bazel/commit/cd12f77b14883b61f215898063b4ac679e468553

**Comment by Helcaraxan** [comment]
Ok. Thanks for the information. :)

**Comment by meteorcloudy** [comment]
http://ci.bazel.io/job/bazel-tests/510/
I am going to create a RC based on 4bf8cc30a572018ac27101396d18686b75ad1ab5 , which is the only short period when ci is almost green. 
Also cherrypick a fix for TF Windows build ef1c6fd3379c80c66122f0b5fb2f5141ed0ba4a4

**Comment by meteorcloudy** [comment]
Just did
```
$ scripts/release/release.sh create 0.4.4 4bf8cc30a572018ac27101396d18686b75ad1ab5 ef1c6fd3379c80c66122f0b5fb2f5141ed0ba4a4
$ scripts/release/release.sh push
```
Waiting for ci

**Comment by meteorcloudy** [comment]
@petemounce A RC for 0.4.4 is out, can you please update the chocolatey package? Thanks!!

**Comment by petemounce** [comment]
@meteorcloudy sure, done; available at https://chocolatey.org/packages/bazel/0.4.4-rc1 . 

Is it correct for this to be 0.4.4-rc1? I thought this release would be in the 0.5x stream?

(There seem to be a lot of breaking changes for a patch release)

**Comment by meteorcloudy** [comment]
Thanks! Yes, that is correct.
We still have some features and bugs waiting to be implemented and fixed for 0.5. 
Probably it will be the next release.

**Comment by meteorcloudy** [comment]
0.4.4 has been released, @petemounce Can you update chocolatey again? Thanks!
Closing this one, and creating #2472 assigned to @hermione521

**Comment by petemounce** [comment]
@meteorcloudy sure, done - https://chocolatey.org/packages/bazel/0.4.4. The usual moderation queue to go through.
