### ISSUE TITLE
[7.3.0] Make `extract` available on `module_ctx`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22826]
Forked from #22825

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryContext.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryContext.java`
> 
> cc: @bazelbuild/triage

cc: @fmeum @Wyverald

**Comment by bazel-io** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/22981
