### ISSUE TITLE
[7.3.0] Do not eval WORKSPACE in LocalRepositoryLookupFunction when `--noenable_workspace`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22836]
Forked from #22774

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/test/py/bazel/bzlmod/bazel_module_test.py`

cc: @bazelbuild/triage

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/test/py/bazel/bzlmod/bazel_module_test.py`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/22855

**Comment by bazel-io** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/22911
