### ISSUE TITLE
//src/test/shell/bazel/android:android_integration_test failig

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/bazel#2283]
see, e.g., http://ci.bazel.io/job/bazel-tests/432/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/console

**Comment by ahumesky** [comment]
my guess is this:
https://github.com/bazelbuild/bazel/commit/e81ff0e156647ae680346ac833313319e7ea69d6

**Comment by aj-michael** [comment]
Yes, this was my fault. I forgot that `BUILD.oss` is copied into `BUILD.tools` if there is no `BUILD.tools` present. Sorry, rolling back.

**Comment by aj-michael** [comment]
I'm going to create a separate `tools/android/BUILD.tools` so that we don't run into this issue again.

**Comment by aj-michael** [comment]
Fixed by b1abe465731ca74393b28853338ac44d7a639f38
