### ISSUE TITLE
[7.3.0] Update `rules_java` `v7.6.5`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22833]
Forked from #22815

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`MODULE.bazel`
`MODULE.bazel.lock`
`src/MODULE.tools`
`src/test/tools/bzlmod/MODULE.bazel.lock`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/22834
