### ISSUE TITLE
[7.3.0] Mark more extensions as reproducible

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22841]
Forked from #22840

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`MODULE.bazel.lock`
`extensions.bzl`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/22846 by @fmeum
