### ISSUE TITLE
(Maybe) removing workspace_user.sh and making android_sdk_repository better.

### ISSUE THREAD

**Issue by aj-michael** [bazelbuild/bazel#2284]
I think the functionality of https://github.com/bazelbuild/bazel/blob/master/scripts/workspace_user.sh should be included in the `android_sdk_repository` and `android_ndk_repository` rules.

This script was created as a fix for https://github.com/bazelbuild/bazel/issues/746, but I don't think it really fixes that issue. See https://github.com/bazelbuild/bazel/issues/746#issuecomment-261347293 for some reasons why.

`android_sdk_repository` and `android_ndk_repository` should be able to be checked into a `WORKSPACE` file without needing to be commented out.

To make this work, all of the attributes should be figured out from the environment (to find the SDK) and by looking at the SDK. https://github.com/bazelbuild/bazel/commit/8e1cd5d9ff931d07f2724e1f08e2cd8f9442fdf4 was the first step in this direction, which made the `build_tools_version` optional. We could use the same logic to make the `api_level` attribute optional.

Making the `path` attribute optional requires reading the `$ANDROID_HOME` environment variable which will require https://bazel.build/designs/2016/10/18/repository-invalidation.html.

If all of that works, we could replace `android_sdk_repository` with a macro that sets the name for you as well, since you really can only use one of them at the moment.

The end goal is:

```
$ cat WORKSPACE
load("@bazel_tools//tools/build_defs/android:android_repositories.bzl", "android_sdk_repository")
load("@bazel_tools//tools/build_defs/android:android_repositories.bzl", "android_ndk_repository")
android_sdk_repository()
android_ndk_repository()
```

**Comment by kchodorow** [comment]
Yay!  I mean, it's not actually blocking on repository invalidation... you can get environment variables right now in repository rules (https://www.bazel.io/versions/master/docs/skylark/lib/repository_os.html).  It just isn't invalidated correctly.

**Comment by ahumesky** [comment]
Can we avoid doing the load() somehow? I thought there was a workspace prelude that can automatically load rules. Then it can just be those 2 lines

**Comment by aj-michael** [comment]
=

**Comment by aj-michael** [comment]
@ahumesky, what reason is there to avoid the load? My understanding is that we are working towards moving as many native rules to Skylark as possible, and all of those rules will require load(). Is there any reason why this one should be special?

**Comment by aj-michael** [comment]
I take my statement of "with a macro that sets the name for you as well, since you really can only use one of them at the moment." It is incorrect, there is in fact a use case for multiple android_sdk_repositories if they are at different paths. They can be selected via the --android_sdk flag.

As such, I do not plan to remove the name attribute.
