### ISSUE TITLE
[7.3.0] Optimize Profiler

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#22852]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/2810c4f874091b344c9f6dd6caeca428cce77ac9

### Category

team-Performance

### Reviewers

@coeuvre

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/22853: https://github.com/bazelbuild/bazel/commit/2810c4f874091b344c9f6dd6caeca428cce77ac9.

**Comment by iancha1992** [comment]
BTW, this was rolled back in the `master` (See https://github.com/bazelbuild/bazel/commit/3e7e5798aa1978aee3befb721e2fd52a469b1cd1)
cc: @fmeum

**Comment by coeuvre** [comment]
Let's not cherry-pick this commit because it was rolled back. I will figure out a roll forward with fix and cherry-pick that one instead.
