### ISSUE TITLE
Command line arguments to run scripts generated using --script_path are ignored when used with --run_under

### ISSUE THREAD

**Issue by ryancahoon-zoox** [bazelbuild/bazel#2287]
### Description of the problem / feature request / question:

1. A run-script is generated using the --script_path option, while a value for --run_under is also supplied
2. The run-script is invoked with additional arguments passed on the command line
3. Only the arguments supplied during build-time are passed to the executable, not those that are supplied at run-time (i.e. during step 2)
4. If the run-script is created without --run_under, step 3 works as expected, passing to the executable the arguments from both build-time and run-time.

This appears to be a problem caused by the executable being invoked using `bash -c` when --run_under is supplied.

### If possible, provide a minimal example to reproduce the problem:

https://github.com/ryancahoon-zoox/bazel-run-under-script

### Environment info
* Operating System: Ubuntu 14.04

* Bazel version (output of `bazel info release`): release 0.3.0-2016-09-27 (@ac731df)

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

No

### Anything else, information or logs or outputs that would be helpful?

I've done a sketch of a fix at https://github.com/ryancahoon-zoox/bazel/compare/master...ryancahoon-zoox:ryancahoon-run-under-script

**Comment by lberki** [comment]
I'm closing this as obsolete: `bazel run` now executes the binary in question with terminal I/O available and as a direct child of the shell running Bazel, so `--script_path` is obsolete now (the only reason it still exists is that some people at Google still depend on it, unfortunately)

**Comment by keith** [comment]
Note this is still an issue and there are actually still good uses for `--script_path` over `bazel run`.

1. If you want to exec bazel with different environment variables than you want to run with, say you want to use a restrictive `$PATH` for your build, but you want to run the tool with a more lenient one
2. It makes it easier to silence bazel output while building without losing the output from the tool, this is a common pattern we use with `--script_path` today:

```sh
if ! bazel run --script_path=foo TARGET > output.txt 2>&1; then
  cat output.txt
  exit 1
fi

./foo
```

While bazel does have some knobs for decreasing output, we found that none of them work to entirely silence the output like this (they're getting closer though https://github.com/bazelbuild/bazel/issues/12117)

Can we re-open this?

**Comment by lberki** [comment]
Sure thing, although I don't think we'll be able to get to this anytime soon; As discussed before, `--script_path` is only mostly kept in life support. Maybe you can work around this by using `--run_under <some script that dumps the command line to where you want>` instead of `--script_path`?
