### ISSUE TITLE
bazel 0.4.3 fails to load packages

### ISSUE THREAD

**Issue by StrangeTcy** [bazelbuild/bazel#2288]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I'm getting errors of the kind
```
ERROR: error loading package 'bazel-0.4.3-dist': Extension file not found. Unable to load package for '//tools/build_defs/pkg:pkg.bzl': .

```
and 
```
ERROR: package contains errors: bazel-0.4.3-dist/third_party/checker_framework_dataflow.
ERROR: error loading package 'bazel-0.4.3-dist/third_party/checker_framework_dataflow': Extension file not found. Unable to load package.

```

UPD: I've tried to `./configure` a lot of times, and most of them the error is
```
ERROR: error loading package 'bazel-0.4.3-dist/third_party/checker_framework_javacutil': Extension file not found. Unable to load package.

```
I don't really know what that package is supposed to do, but for some reason bazel seems unable to get it.

### If possible, provide a minimal example to reproduce the problem:

1. `cd` to `~/tensorflow` (freshly `git pull`ed)

2. run `./configure`; choosing /usr/bin/python2.7, GPU support, CUDA 8.0 and cudnn 5

3. press ENTER and wait
 
After the (usual) warnings about `Variables HOST_CFG and DATA_CFG` some error or other occurs

### Environment info
* Operating System:
     Ubuntu 17.04 x64

* Bazel version (output of `bazel info release`):
   0.4.3

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

 No
### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by aehlig** [comment]
I'm unsure about the status of this report. Do you only get those errors trying to build tensorflow, or also for other projects? Does it build with earlier versions of bazel?

**Comment by StrangeTcy** [comment]
> Do you only get those errors trying to build tensorflow, or also for other projects? 
Yes; it's currently the only thing I'm using bazel for.  I can try to build something else for debugging purposes, if it'd help.
> Does it build with earlier versions of bazel?
No, but that's due to another error.

**Comment by damienmg** [comment]
Are you unpacking bazel under the TF tree? Can you just move that directory elsewhere?

**Comment by StrangeTcy** [comment]
I guess; it isn't necessary for bazel to be in that tree for it to work, is it?

**Comment by damienmg** [comment]
I mean you have the Bazel sources underneath the TF source ?

**Comment by mhlopko** [comment]
Friendly ping @StrangeTcy

**Comment by mhlopko** [comment]
Closing due the lack of information, feel free to reopen if this is still a problem.
