### ISSUE TITLE
bazel 0.4.3 doesn't seem to be updating its release number

### ISSUE THREAD

**Issue by StrangeTcy** [bazelbuild/bazel#2289]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I've installed bazel 0.4.3 a lot of different ways, and yet `bazel info release` still shows `release 0.4.2`. I would expect it to show `0.4.3` (please say if it shouldn't)

### If possible, provide a minimal example to reproduce the problem:
Downloading the archive and running `./compile.sh`, installing the 0.4.3 `.deb` and running bazel-04.3-installer.sh have all apparently worked perfectly, but the release number still hasn't changed. 

### Environment info
* Operating System:
Ubuntu 17.04 x64

* Bazel version (output of `bazel info release`):
0.4.2 (but this might mean something else, see above)

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by damienmg** [comment]
Ok I have a version installed by the debian repository, the version number is correct but we do it differently, let me investigate.

**Comment by damienmg** [comment]
Just used the bazel-0.4.3-installer.sh and got version 0.4.3 as expected.

What does `which bazel` returns?

**Comment by damienmg** [comment]
deb package is also fine, I suspect an incorrect installation.

**Comment by StrangeTcy** [comment]
> What does which bazel return?
`/home/myname/bin/bazel`

**Comment by damienmg** [comment]
Can you ls in that folder (~bin) and returns me the sha256 of all the Bazel
related files?

**Comment by damienmg** [comment]
I meant in ~/bin

**Comment by StrangeTcy** [comment]
```
SHA256(btmakemetafile)= ea39064f8c2992219f8975761c03e373df1fde3ab99ba57eac9023d5d5017779

SHA256(btshowmetainfo)= 852d72eb2d4d63c61fdef6d4a7e272bb871976dbbb1c2444df06854c6ce99094

```

`~/bin/bazel` was a link to `~/.bazel/bin/bazel`, its sha256 is
`SHA256(bazel)= 3cc9a34dc6699dc9df002d82d937845895b53f904159dd537088e64e50e7de05
`

**Comment by damienmg** [comment]
Is there a ~/.bazel/bin/bazel-real? If so can we have it's sha256 too?

**Comment by damienmg** [comment]
Ok FTR, for 0.4.3, for the debian package:
```
SHA256(bazel) = 05e5f4b0206d4fa4140e249ae339eafa4fddcd9570bf71df09b8fb400e497081
SHA256(bazel-real) = a692eaf4da4abfa18bca63ff9d721be58a02703e7f4f93917ceb8e93b1fda683
```

They are the same from the installer.

I am closing this issue, your installed binary is not 0.4.3.

FTR 0.4.2 sha's:
```
$ shasum -a 256 bazel bazel-real
3cc9a34dc6699dc9df002d82d937845895b53f904159dd537088e64e50e7de05  bazel
8394150f2575fe4d9268a228740ae4a82c4c428f12dc1b9027542a5c21cb2806  bazel-real
```
So it matches 0.4.2. wrapper.
