### ISSUE TITLE
[7.3.0] Skymeld with `--notrack_incremental_state` throws `ArtifactPrefixConflictException` for TreeArtifact based cc_library

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#22893]
Forked from #22886

**Comment by iancha1992** [comment]
@fmeum @joeleba Could you please help cherry-pick https://github.com/bazelbuild/bazel/commit/12aa54e527eafb8db74fdf9a5eae69db97b21fa5?

cc: @bazelbuild/triage
