### ISSUE TITLE
Bazel test runs locally without giving errors when remote executor connection fails

### ISSUE THREAD

**Issue by Sowmya-Iyer** [bazelbuild/bazel#22917]
### Description of the bug:

Trying to run Bazel test using a grpc remote executor to test custom bazel-buildfarm server and worker deployed. But, bazel starts locally and runs locally without any explicit error message. First tried it with the original dns and port and the server logs showed no execution. Then tried chenaging the ip to dummy values and the bazel test still runs

```
siyer@siyer-ThinkPad-T15g-Gen-2i:~/workspace/bazel_training$ USE_BAZEL_VERSION=7.1.2 bazel test --verbose_failures --experimental_circuit_breaker_strategy="failure" --remote_executor=grpc://00.000.00.00:8980 //...
INFO: Invocation ID: 909464f3-f944-41ea-b4d8-4866b56ed84e
INFO: Analyzed 9 targets (0 packages loaded, 0 targets configured).
INFO: Found 8 targets and 1 test target...
INFO: Elapsed time: 0.049s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
PASSED: //src:base_test (see /home/siyer/.cache/bazel/_bazel_siyer/7d82a6405652796670e01aca9a02ed52/execroot/_main/bazel-out/k8-fastbuild/testlogs/src/base_test/test.log)
INFO: From Testing //src:base_test
==================== Test output for //src:base_test:
[==========] Running 3 tests from 3 test suites.
[----------] Global test environment set-up.
[----------] 1 test from SampleClass
[ RUN      ] SampleClass.Initialize
[       OK ] SampleClass.Initialize (0 ms)
[----------] 1 test from SampleClass (0 ms total)

[----------] 1 test from SampleSharedClass
[ RUN      ] SampleSharedClass.Initialize
[       OK ] SampleSharedClass.Initialize (0 ms)
[----------] 1 test from SampleSharedClass (0 ms total)

[----------] 1 test from Lambda
[ RUN      ] Lambda.Class
[       OK ] Lambda.Class (0 ms)
[----------] 1 test from Lambda (0 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 3 test suites ran. (1 ms total)
[  PASSED  ] 3 tests.
================================================================================
//src:base_test                                                 (cached) PASSED in 0.1s

Executed 0 out of 1 test: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
``` 

Would like to know if there is any config or a way to make sure it terminates when the --remote_executor connection cannot be established

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

 USE_BAZEL_VERSION=7.1.2 bazel test --verbose_failures --remote_executor=grpc://12.141.11.110:8980 //... (random ip)

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 7.1.2

**Comment by Sowmya-Iyer** [comment]
Sometimes running the same test while using my buildfarm worker as IP, I get: 
```
INFO: Found 1 test target...
Target //src:base_test up-to-date:
  bazel-bin/src/base_test
INFO: Elapsed time: 0.857s, Critical Path: 0.81s
INFO: 40 processes: 14 internal, 26 remote.
```

What is that 14 internal and 26 remote supposed to mean?

**Comment by iancha1992** [comment]
@Sowmya-Iyer Could you please provide sample code to reproduce this issue?

**Comment by tjgq** [comment]
In your initial message, it looks like you ran an incremental build where the output tree was determined to be already up to date, so nothing actually needed to run (neither locally nor remotely).

Nevertheless, if `--remote_executor` was set to a bad address, I'd still expect to see something like `ERROR: Failed to query remote execution capabilities: UNAVAILABLE: io exception` in the output. This is what I see when I try to reproduce it.

> What is that 14 internal and 26 remote supposed to mean?

`remote` means the action ran remotely (or you got a cache hit from the remote executor; we don't distinguish hits from misses for remote execution). `internal` means the action was run by Bazel itself (e.g. `ctx.actions.write` does this).

Please reopen with a self-contained repro. Make sure you include any other flags you might have in a bazelrc file, and include the complete list of steps to reproduce starting from a clean state.
