### ISSUE TITLE
protobuf dependencies for cc_proto_library not available upstream

### ISSUE THREAD

**Issue by dionescu** [bazelbuild/bazel#2291]
There are a couple of problems.

- The latest release of protobuf is too old and thus does not contain a cc_toolchain in its BUILD file.

- Building from head does net help either. Bazel tries to pass the flag direct_dependencies_violation_msg to protoc which is not present in the upstream compiler code (at head!):
https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/command_line_interface.cc

Some relevant discussion is here:
https://github.com/google/protobuf/issues/2426, cc_proto_library released with Bazel 0.4.3

**Comment by cgrushko** [comment]
It's unfortunately up to the protobuf team - I pinged https://github.com/google/protobuf/issues/2426#issuecomment-272220583.

**Comment by cgrushko** [comment]
Turns out the required change in protobuf are not yet in the master branch, they're in the 3.2.x branch. I'm told one of their team-members is actively working on merging it, and with some luck it'll be in master by next week.
