### ISSUE TITLE
Bazel hard-codes protoc location

### ISSUE THREAD

**Issue by dionescu** [bazelbuild/bazel#2292]
After hacking the protobuf code to ignore the unimplemented --direct_dependencies_violation_msg flag (https://github.com/bazelbuild/bazel/issues/2291), everything worked with protobuf checked into third_party/protobuf. However, moving the code to another directory (or using a git_repo rule) fails because protoc is expected at //third_party/protobuf:protoc.

Why is Bazel hard-coding this location? Can't this be com_google_protobuf_cc:protoc since the expected name of the repo is already hard-coded? If it's related to bootstrap, then that can probably be detected and the target can be controlled via a flag. I would really love to not have to keep protobuf at that location.

**Comment by rtsai** [comment]
We found something similar, and it was not a bazel problem.

In protobuf v3.0.2, the BUILD file assumes it lives in //third_party/protobuf (in our workspace, it lives in //third_party/google/protobuf). Fortunately, this can be solved by only patching the protobuf BUILD file, with no source patches necessary. We patched our :protobuf_test target:

```
diff --git a/BUILD b/BUILD
index 147b46ac..9ddc57d6 100644
--- a/BUILD
+++ b/BUILD
@@ -435,6 +435,7 @@ cc_binary(
 
 cc_test(
     name = "protobuf_test",
+    timeout = "short",
     srcs = COMMON_TEST_SRCS + [
         # AUTOGEN(test_srcs)
         "src/google/protobuf/any_test.cc",
@@ -505,7 +506,10 @@ cc_test(
         "src/google/protobuf/well_known_types_unittest.cc",
         "src/google/protobuf/wire_format_unittest.cc",
     ],
-    copts = COPTS,
+    copts = COPTS + [
+        "-DGOOGLE_PROTOBUF_TEST_PLUGIN_PATH=\\\"third_party/google/protobuf/test_plugin\\\"",
+        "-DGOOGLE_PROTOBUF_TEST_SOURCE_PATH=\\\"third_party/google/protobuf/src\\\"",
+    ],
     data = [
         ":test_plugin",
     ] + glob([

```

**Comment by dionescu** [comment]
Are you using the Bazel proto rules (e.g. cc_proto_library from latest release)? With third-party proto build rules  you can probably specify your proto toolchain as you desire. Bazel source code, however,   has the location //third_party/protobuf:protoc hard-coded for the proto rules.

**Comment by rtsai** [comment]
You are right. We have also created a Skylark extension to override cc_proto_library . It sets the "default_runtime" and "protoc" attributes to point at our path in //third_party/google/protobuf, then calls the protobuf cc_proto_library.

**Comment by cgrushko** [comment]
@dionescu agreed, it should be hardcoded to `@com_google_protobuf//:protoc`.
Until it does, can you use the `--proto_compiler` flag to point at any binary rule?

**Comment by cgrushko** [comment]
This is now `@com_google_protobuf//:protoc` by default, with `--proto_compiler` overriding it.
It's not in Bazel 0.4.4 though, so you'll have to build from sources (or wait for 0.4.5).

**Comment by cgrushko** [comment]
Ah, also see https://bazel.build/blog/index.html#protocol-buffers-in-bazel
