### ISSUE TITLE
Missing documentation for java_single_jar

### ISSUE THREAD

**Issue by peakschris** [bazelbuild/bazel#22924]
### Problem description (include actual vs expected text, if applicable):

I can't find any reference to documentation for java_single_jar, either here, or in the rules_java repo

There are two references to this rule that I can find:
* https://github.com/bazelbuild/bazel/issues/19720
* https://github.com/bazelbuild/bazel/issues/19687

It would be good to have this documented alongside all the other java rules.

**Comment by hvadehra** [comment]
We're looking to move the other java rules out of Bazel and into rules_java soon as well. Where the documentation will live for them then is still undecided. 

When that is settled, documentation for java_single_jar will be co-located.
