### ISSUE TITLE
allow multiple credential helpers for a single site

### ISSUE THREAD

**Issue by peakschris** [bazelbuild/bazel#22933]
### Description of the feature request:

I have two different sets of credentials for two different subdirectories of a site:

my.site.com/sub1 <- credentials A
my.site.com/sub2 <- credentials B

the credential helper works great for specifying one set of credentials, but is specified not to consider the subdirectory in the scope.

I would like to be able to do this:
```
common --credential_helper=my.site.com/sub1=sub1_credentials.bat
common --credential_helper=my.site.com/sub2=sub2_credentials.bat
```

But I get:
```
ERROR: While parsing option --credential_helper=my.site.com/sub1=sub1_credentials.bat: Credential helper scope 'my.site.com/sub1' must be a valid domain name with an optional leading '*.' wildcard
```

### Which category does this issue belong to?

Configurability

### What underlying problem are you trying to solve with this feature?

Connecting to websites such as github, typically different tokens can be assigned for different subdirectories on the main site.

### Which operating system are you running Bazel on?

windows

### What is the output of `bazel info release`?

bazel 7.2.1

**Comment by peakschris** [comment]
@Yannic this may interest you

**Comment by peakschris** [comment]
Another option would be to follow docker's protocol, https://github.com/docker/docker-credential-helpers?tab=readme-ov-file#development; the URL is supplied to the credential helper, which can then return the appropriate auth.

**Comment by tjgq** [comment]
> the URL is supplied to the credential helper, which can then return the appropriate auth

This is already the case. The standard input to a credential helper is a JSON object with a `uri` key.

**Comment by peakschris** [comment]
I missed this, thank you.
For others: this is documented here: https://github.com/bazelbuild/proposals/blob/main/designs/2022-06-07-bazel-credential-helpers.md
