### ISSUE TITLE
bazel  0.4.2 loading local rules does not work in new_git_repository

### ISSUE THREAD

**Issue by andrewmed** [bazelbuild/bazel#2293]
With this in WORKSPACE:
```
new_git_repository(
    name = "hiccup",
    commit = "53057de9799b27d5d0ddfe865fdac6e7a141d896",
    build_file_content = """
load("//build_tools/clojure:clojure.bzl", "clojure")
clojure(
    name = "src",
    namespace = "src.hiccup.core",
)""",
    remote = "https://github.com/weavejester/hiccup.git",
)
```

as it says, `bzl` rule should be loaded  from a local repository `//build_tools/clojure:clojure.bzl`

However, when called, the rule is looked upon in remote `new_git_repository` repository:

```
andy@laptop:~/repo/build_tools/clojure/tests$ bazel run :two
ERROR: /home/andy/repo/build_tools/clojure/tests/BUILD:9:1: error loading package '@hiccup//': Extension file not found. Unable to load package for '@hiccup//build_tools/clojure:clojure.bzl': BUILD file not found on package path and referenced by '//build_tools/clojure/tests:two'.
ERROR: Analysis of target '//build_tools/clojure/tests:two' failed; build aborted.
INFO: Elapsed time: 0.157s
ERROR: Build failed. Not running target.
```

here is `//build_tools/clojure/tests`
```
load("//build_tools/clojure:clojure.bzl", "clojure")

clojure(
    name = "one",
)
clojure(
    name = "two",
    deps = [
        "@hiccup//:src",
        ":one_library",
    ],
)
```
### Environment info
* Operating System:
Linux laptop 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

* Bazel version (output of `bazel info release`):
release 0.4.2

**Comment by damienmg** [comment]
This is a workaround until this get fixed but you actually access the main repository from a remote repository so you should use `@//build_tools/clojure:clojure.bzl`. Without the `@` prefix it resolve to a repository local label, from the `@hiccup` repository so it is like `@hiccup//build_tools/clouure:clojure.bzl`.

So your new workspace file should looks like:
```python
new_git_repository(
    name = "hiccup",
    commit = "53057de9799b27d5d0ddfe865fdac6e7a141d896",
    build_file_content = """
load("@//build_tools/clojure:clojure.bzl", "clojure")
clojure(
    name = "src",
    namespace = "src.hiccup.core",
)""",
    remote = "https://github.com/weavejester/hiccup.git",
)
```

**Comment by damienmg** [comment]
This does seems resolved, closing, please ping if you still have issues

**Comment by andrewmed** [comment]
Hello Damien
Yes with 'at' sign it works perfect

**Comment by damienmg** [comment]
Glad to hear :)
