### ISSUE TITLE
TestSummary compares strings extracted from protos against null

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#2295]
Proto accessors never return null (IIRC) thus this code is never run. I think the intention was to check against unset values which would require using field existence checks instead.

https://github.com/bazelbuild/bazel/blob/8d25362bcb49286feb546b306657b6453712f2b3/src/main/java/com/google/devtools/build/lib/runtime/TestSummary.java#L158

**Comment by damienmg** [comment]
Right, also the whole test_summary proto might need some clean-up to fix the flakyness running (so we can return multiple result).

**Comment by damienmg** [comment]
(btw, if you wish to remove those dead code example, feel free to send code reviews :))

**Comment by endobson** [comment]
The issue with just removing the dead code is that while in practice it is dead, it looks like the desired behavior was to do something different if the value wasn't set. In particular the current UI still adds a period if the class name isn't set. So you get things like "Passed .testCaseName" with a stray period. So I don't think the correct solution is to just remove the code, but instead figure out what the desired behavior is and add tests, and then fix the actual behavior to match.

**Comment by meisterT** [comment]
The code in question doesn't exist anymore.
