### ISSUE TITLE
C++ Coverage not working with --test_env="LCOV_MERGER=/bin/true"

### ISSUE THREAD

**Issue by Ryang20718** [bazelbuild/bazel#22969]
### Description of the bug:

C++ Code coverage doesn't work with this flag set

### Which category does this issue belong to?

C++ Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

add a cc_library and a cc_test, use bazel coverage <target> --combined_report=lcov --instrument_test_targets --instrumentation_filter="//" --test_env="LCOV_MERGER=/bin/true" 

To see that coverage isn't getting generated

### Which operating system are you running Bazel on?

20.04

### What is the output of `bazel info release`?

6.5.0

### Any other information, logs, or outputs that you want to share?

Removing --test_env="LCOV_MERGER=/bin/true" yields coverage results

**Comment by comius** [comment]
cc @c-mita for triage

**Comment by c-mita** [comment]
What's the expectation here?

That coverage works when you appear to be overriding the tool it needs to work?
