### ISSUE TITLE
[Documentation request?] How were official JDK7 binaries built?

### ISSUE THREAD

**Issue by ahyangyi** [bazelbuild/bazel#2297]
Hi, I noted that one cannot simply build Bazel itself with JDK7. In 0.3.x era, removing a few test cases and patching one or two lines were sufficient to make it buildable, but as time goes there are more and more lines that needs a patch to be able to build under JDK 7.

I am _not_ criticizing this. I understand that the Bazel team already decides to abandon JDK7 and you are only maintaining it as long as the effort it takes to build it doesn't become too huge.

However, I'd like to know if there is some documentation on how to build the source code under JDK7. Is there a non-open-sourced branch or a small patchset somewhere, or a custom build option?

Thanks a lot in advance.

**Comment by damienmg** [comment]
Hello, `export JAVA_VERSION=1.7; ./compile.sh` should do it.

Also we have a plan to totally switch to Java 8 (replacing the JDK7 build by a built with an OpenJRE bundled in our binary distribution), we would love to hear more about your use case.

/cc @philwo

**Comment by damienmg** [comment]
(side-note: we actually build them with an OpenJDK 8 with -source and -target to 7)

**Comment by ahyangyi** [comment]
Thanks a lot for both comments! I'll try them out. Being able to build both versions from a single machine with a single installation of JDK will certainly simplify things.

I have no real particular affinity to Java 7. We currently do not enforce a single Linux distribution across our developer's machines, servers & VMs however, so telling them to install JDK 8 takes some effort. And Ubuntu 14.04 LTS does not have an official Java 8 package, so I can't really blame them for using obsolete systems.

But if you decide the Java 7 port is no longer worth it, I'm fine.

**Comment by damienmg** [comment]
Ok thanks for your answer. I am closing this issue for now, ping back if you have further issues.
