### ISSUE TITLE
[bazel.build] Problem with /install/compile-source

### ISSUE THREAD

**Issue by ccw-li** [bazelbuild/bazel#22987]
### Page link:

https://bazel.build/install/compile-source

### Problem description (include actual vs expected text, if applicable):

I am running ubuntu-20.04 inside an arm64 virtual machine.
I am trying to build bazel from scratch.
I followed the instructions in the section "Build Bazel from scratch (bootstrapping)", but the command `env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" bash ./compile.sh` gave an error: 

> Unable to make java.lang.String(byte[],byte) accessible

It turns out that I should not use openjdk-21 in my environment. openjdk-11 works fine for me.

I suggest you change the following text
> JDK. Version 21 is required.

to 
> JDK. Version 11 is required.

### Where do you see this issue? (include link to specific section of the page, if applicable)

https://bazel.build/install/compile-source#bootstrap-unix-overview

**Comment by meteorcloudy** [comment]
@ccw-li Which version of Bazel are you trying to bootstrap?

@hvadehra I'm a bit surprised that Bazel doesn't bootstrap with JDK 21, do you know anything about this?

**Comment by hvadehra** [comment]
I can't think of any reason it wouldn't. I think an answer to your first question would help.

**Comment by ccw-li** [comment]
I am bootstrapping bazel-6.5.0.

**Comment by hvadehra** [comment]
> I am bootstrapping bazel-6.5.0.

Thanks, I'll see if I can repro.

fwiw, if you look at the docs for 6.5.0 here https://bazel.build/versions/6.5.0/install/compile-source#bootstrap-bazel , it does say jdk 11. The change to 21 became necessary only recently (the default docs are for Bazel@HEAD).
