### ISSUE TITLE
archive_override doesn't have a patch_args attribute

### ISSUE THREAD

**Issue by tpudlik** [bazelbuild/bazel#22982]
### Description of the feature request:

Unlike `http_archive`, the `archive_override` rule doesn't have a `patch_args` attribute. Per the documentation of that attribute, setting `patch_args = ["-p1"]` is generally necessary for applying patches generated by git.

@meteorcloudy 

### Which category does this issue belong to?

External Dependency

**Comment by Wyverald** [comment]
There is [`patch_strip`](https://bazel.build/rules/lib/globals/module#archive_override.patch_strip).
