### ISSUE TITLE
http_archive not using BUILD.bazel 

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#2299]
### Description of the problem / feature request / question:

`http_archive` does not recognize package when only `BUILD.bazel` is present.

### If possible, provide a minimal example to reproduce the problem:

Have the following content in `WORKSPACE`:

    http_archive(
      name = "range_v3",
      url = "https://github.com/abergmeier/range-v3/archive/e268a1ff761c65a4a47f4b395d2668461584c570.zip",
      sha256 = "0d74df4491f2e6f6fb57cc7ec3f305f30720979d89f743a46f4405c42bc08f5d",
      strip_prefix = "range-v3-e268a1ff761c65a4a47f4b395d2668461584c570",
    )

Execute `bazel fetch @range_v3//:all`. See it fail with:

    no such package '@range_v3//

### Environment info
* Operating System: Ubuntu 16.04.1

* Bazel version (output of `bazel info release`): 0.4.3

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

Nope.

**Comment by damienmg** [comment]
Hello,

This is a known issue that was fixed right after we cut version 0.4.3, it will be in the next release (or you can build a binary at HEAD).

Sorry for that.

/cc @katre fyi

**Comment by abergmeier-dsfishlabs** [comment]
I seem to be dumb and blind this morning. Can you please point me to the commit.

**Comment by katre** [comment]
https://github.com/bazelbuild/bazel/commit/b9c65d1ea5254b41238c23bdfbe3543f1dbd3a42

It's a revert of a revert of the original work, which does make it hard to
find, sorry.

**Comment by abergmeier-dsfishlabs** [comment]
Cherry-picking that onto 0.4.3 leads to:

    ERROR: in target '//external:jdk': no such package '@local_jdk//': BUILD file not found on package path.

**Comment by katre** [comment]
What are you building to test? I just built bazel from HEAD and it builds itself correctly.
I see the same error that you do when I checked out 0.4.3 and patched in that commit, so I'm not sure what the other differences are between 0.4.3 and HEAD that cause this.

Is working from HEAD acceptable to you, or should we keep investigating?

**Comment by abergmeier-dsfishlabs** [comment]
Am not too thrilled to use HEAD. If you can have another release of Bazel end of this month we should be ok, I think.

**Comment by katre** [comment]
https://github.com/bazelbuild/bazel/issues/2282 is already open for creating a release this month, so that should be workable. Thanks!
