### ISSUE TITLE
[bazel.build] Dict concatenation via | is not documented in the reference docs

### ISSUE THREAD

**Issue by tpudlik** [bazelbuild/bazel#22991]
### Page link:

https://bazel.build/rules/lib/core/dict

### Problem description (include actual vs expected text, if applicable):

Bazel dicts support concatenation via the `|` operator (https://github.com/bazelbuild/starlark/issues/14), but this is not documented in the reference documentation in https://bazel.build/rules/lib/core/dict.

**Comment by fmeum** [comment]
@tpudlik Isn't this explained as the 4th way to consttuct a dict on that page?

**Comment by tpudlik** [comment]
D'uh, search fail! Sorry guys.
