### ISSUE TITLE
Unable to build project due to @platforms//cpu and @platforms//os errors

### ISSUE THREAD

**Issue by khadflow** [bazelbuild/bazel#23000]
### Description of the bug:

I am migrating bazel dependencies from GitHub to my team’s local package management. I was able to get past the checksum by recalculating it and replacing it, but now I have this issue while building. I have no idea how to fix it. I’ve provided a picture. I’ve already tried a couple things on the internet. 

### Which category does this issue belong to?

External Dependency

### Which operating system are you running Bazel on?

Linux 

### What is the output of `bazel info release`?

Release 6.4.0

### Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

![image](https://github.com/user-attachments/assets/e9340880-bd54-4a2e-9024-bd5799f08dce)

**Comment by iancha1992** [comment]
@khadflow Do you have a repo, so we can reproduce this issue?

**Comment by khadflow** [comment]
No, this is a bug I'm experiencing with the source code at work.
