### ISSUE TITLE
[bazel.build] Problem with /versions/7.0.0/install

### ISSUE THREAD

**Issue by Dixusza** [bazelbuild/bazel#23011]
### Page link:

https://bazel.build/versions/7.0.0/install

### Problem description (include actual vs expected text, if applicable):

Service at your door step.

**Comment by satyanandak** [comment]
@Dixusza, Could you please provide more details?

**Comment by sgowroji** [comment]
@Dixusza  We are closing this issue since it doesn't have valid details. Please tag `@bazelbuild/triage` if you have any questions or want this reopened.
