### ISSUE TITLE
--module_override flag is undocumented

### ISSUE THREAD

**Issue by tpudlik** [bazelbuild/bazel#23025]
### Problem description (include actual vs expected text, if applicable):

https://github.com/bazelbuild/bazel/pull/16148/ added a `--module_override` flag, but as far as I can tell this flag is undocumented. The only way to learn of its existence and syntax is to find that PR and look at the modified files!

@Wyverald 

### Where do you see this issue? (include link to specific section of the page, if applicable)

Not exactly sure where this should be mentioned, maybe https://bazel.build/external/module?

**Comment by Wyverald** [comment]
You might have spelled it wrong :) https://bazel.build/reference/command-line-reference#flag--override_module

**Comment by tpudlik** [comment]
Indeed! Sorry about the noise.
