### ISSUE TITLE
[7.3.0] Document source of truth for `rctx.download*` cache key

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23044]
Forked from #22716

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23048
