### ISSUE TITLE
[7.3.0] Path map executable paths

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23040]
Forked from #22844

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/actions/CommandLines.java`
`src/main/java/com/google/devtools/build/lib/vfs/PathFragment.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23118 by @fmeum
