### ISSUE TITLE
[7.3.0] Deduplicate locally executed path mapped spawns 

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23060]
Forked from #22556

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/exec/SpawnCache.java`
`src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnCacheTest.java`

cc: @bazelbuild/triage

**Comment by fmeum** [comment]
Sent https://github.com/bazelbuild/bazel/pull/23069
