### ISSUE TITLE
Add `build_file` attribute to `git_override`, `archive_override`

### ISSUE THREAD

**Issue by tpudlik** [bazelbuild/bazel#23077]
### Description of the feature request:

It would be convenient if `git_override` and `archive_override` had a `build_file` attribute, analogous to that exposed by `git_repository` and `http_archive`.

### Which category does this issue belong to?

External Dependency

### What underlying problem are you trying to solve with this feature?

This would be particularly helpful during migrations to bzlmod of repositories that currently use `build_file`. The state of the art currently is that you need to convert the BUILD file into a patch, which adds friction to the migration and is less maintainable in the long run (especially in cases where the `build_file` was itself loaded from a dependency).

**Comment by Wyverald** [comment]
This is very easily to implement -- start by looking at ModuleFileGlobals.java. Contributions welcome!

**Comment by taimoorzaeem** [comment]
@Wyverald I would love to work on this issue. Could you please assign it to me?

**Comment by eliphazbouye** [comment]
@Wyverald  this issue is still relevant ?

**Comment by robinlinden** [comment]
Looks like this was done in #24443.
