### ISSUE TITLE
32-bit Windows build?

### ISSUE THREAD

**Issue by petemounce** [bazelbuild/bazel#2307]
There's a request for a 32-bit Windows build at the chocolatey package's disqus support board - http://disq.us/p/1es243i.

**Comment by charlesprogrammr** [comment]
I'd like to ask for this, I've been trying for a week or so to build enough of the toolchain to build a 32 bit windows version of tensorflow, but everything I try seems to result in some seemingly insurmountable hurdle. I've tried with CMake and Visual Studio, and I've tried with Msys2, but I run out of heap, I've built the protoc/protobuf stuff, and set all the environment variables and java parameters that somehow get left out of the "complete instructions" that are always short of complete. Long story short, Windows 7 32 bit, 2GB RAM, Intel N455 processor, (I know, lame, but hey, I'm poor.) This is the first time, I've run out of resources doing any development, so any help getting a leg up on this build would be appreciated. I see that Linux 32 bit has been done, and that 32 bit ARM processors have successfully been built, the only things left are windows and bsd.

**Comment by laszlocsomor** [comment]
I understand this is a pain (I also wanted to use Bazel on a 32-bit machine but couldn't), and I'm sorry about that, but we just don't have the capacity to work on supporting 32-bit builds nor is it a priority for us. I'm afraid we can't help here.

**Comment by excitoon** [comment]
Hi. As a second attempt to finally solve this I made almost seamless solution to this. Please check it out here:
https://github.com/excitoon/bazel-win32-toolchain
https://github.com/excitoon/bazel-win32-toolchain-test

It does not require merging anything into Bazel source tree and therefore any capacities to support it from Google.
