### ISSUE TITLE
Bazel downloader config: configure additional source (instead of rewrite)

### ISSUE THREAD

**Issue by malt3** [bazelbuild/bazel#23083]
### Description of the feature request:

Many organizations want to ensure that third party dependencies are highly available.
Currently, this can be achieved by setting:

- multiple alternative mirror URLs for `http_archive`, `rctx.download*`
- a `rewrite` rule in a downloader configuration

The former actually provides alternatives with fallback semantics, while the latter replaces the source URL.
What I would like to do is the following:
For any set (or subset) of URLs, add my own mirror as an alternative source. This should allow downloading from any of the alternative sources to maximize availability.

### What underlying problem are you trying to solve with this feature?

Provide high availability for HTTP downloads in Bazel

### Which operating system are you running Bazel on?

not applicable

### What is the output of `bazel info release`?

not applicable

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

-

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
-
```

### Have you found anything relevant by searching the web?

no

**Comment by meteorcloudy** [comment]
I believe this is already possible, for example for Bazel itself, we have 
https://github.com/bazelbuild/bazel/blob/1a61c84c2e44957fe1bf5ac29b05991d644a2c29/bazel_downloader.cfg#L1-L2

The first line adds the mirror URL and the latter adds the original URL.
