### ISSUE TITLE
[7.4.0] Fix deduping for `--extra_toolchains`.

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23095]
Forked from #23093

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/analysis/config/FragmentOptions.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/analysis/config/FragmentOptions.java`
> 
> cc: @bazelbuild/triage

cc: @katre @gregestren @rickeylev @aranguyen @fmeum

**Comment by iancha1992** [comment]
Just a friendly reminder, the 7.3.0RC1 is scheduled for next Monday, July 29th. Thanks!

**Comment by bazel-io** [comment]
The branch, release-7.4.0, may not exist. Please retry the cherry-pick after the branch is created.

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/analysis/config/FragmentOptions.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/analysis/config/FragmentOptions.java`
> 
> cc: @bazelbuild/triage

@gregestren @rickeylev @aranguyen @katre @fmeum

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23670
