### ISSUE TITLE
Label flag transitions are cached incorrectly

### ISSUE THREAD

**Issue by tpudlik** [bazelbuild/bazel#23097]
### Description of the bug:

If you modify which target a label flag points to in a transition, Bazel will fail to invalidate the cache.

I verified this bug is present in versions `8.0.0-pre.20240618.2` and https://github.com/bazelbuild/bazel/commit/0ddcfd327ffd012d348deeae08ec0836409706ad. But it _does not_ reproduce on 7.2.1.

@katre 

### Which category does this issue belong to?

Configurability

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/tpudlik/label_flag_transition_cache_bug

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 8.0.0-pre.20240618.2

### If this is a regression, please try to identify the Bazel commit where the bug was introduced with bazelisk --bisect.

Yes, it's a regression, but it's a little tricky to construct the `--bisect` for it because it's a caching issue. I decided to file it before figuring one out. Sorry!

### Have you found anything relevant by searching the web?

Seemed related to https://github.com/bazelbuild/bazel/issues/22995, but the fix for that issue doesn't fix this one.

**Comment by tpudlik** [comment]
Although the minimal example uses `bazel cquery` for simplicity, we observed the same bug in an actual project with `bazel build`.

**Comment by tpudlik** [comment]
Oh, also: I didn't verify what flags (other than label flags) are affected, the label flag is just the one we bumped into in the wild.

**Comment by katre** [comment]
Slightly cleaner repro command:

```
$ bazel-dev clean
$ bazel-dev cquery 'filter("^//:", deps(//:hello_with_flag_set))'
//:hello_with_flag_set (8985b25)
//:hello (c5ca09f)
//:main.cc (null)
//:label_flag (c5ca09f)
//:other_library (c5ca09f)

# Update file then re-run
$ bazel-dev cquery 'filter("^//:", deps(//:hello_with_flag_set))'
//:hello_with_flag_set (8985b25)
//:hello (c5ca09f)
//:main.cc (null)
//:label_flag (c5ca09f)
//:other_library (c5ca09f)
```

**Comment by katre** [comment]
I think the problem is actually transition caching, not anything specific to label flags. Investigating further, but this feels like it's related to 0ddcfd327ffd012d348deeae08ec0836409706ad
