### ISSUE TITLE
Debugging C++ on MacOS

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#23110]
### Description of the bug:

By default, debugging C++ doesn't seem to work on MacOS. Even with `bazel build -c dbg`, `lldb` is not able to show the locations.

The problem was discussed in https://github.com/bazelbuild/bazel/issues/6327, but the resolution doesn't seem satisfactory:

* `--spawn_strategy=local` is just a very rough workaround. Someone mentioned `--strategy_regexp=^Linking=local`, which seems somewhat better.
* This is not intuitive or discoverable at all. I didn't find it in the documentation. Finding the issue above is also not easy, since it's closed.
* Changing the strategy doesn't cause a rebuild, so users have to use `bazel clean` or do a spurious change in a source file in order to get a correct result.

### Which operating system are you running Bazel on?

MacOS

### What is the output of `bazel info release`?

7.2.0

**Comment by fmeum** [comment]
Have you tried using the https://github.com/bazelbuild/apple_support toolchain? It has some of the features mentioned in that issue enabled by default, so it might work out of the box (although `lldb` may still need to be configured to use the appropriate prefix).

To be fully honest, the default Unix toolchain that remains in Bazel core is not in a good state for macOS. I would highly recommend using the one in `apple_support` instead.

**Comment by keith** [comment]
In apple_support we more aggressively changed defaults to try to solve this for the common case for sure

**Comment by laurentlb** [comment]
Thanks, I confirm the debug information works with apple_support.

**Comment by burnpanck** [comment]
Huh, how is this completed? What is if you need a real compiler instead of Xcode? Say, a version of (upstream) clang that actually supports a recent C++ standard? `apple_support` explicitly caters to Xcode, but the issue above has nothing at all to do with Xcode. The original issue raised is equally valid for any other toolchain: The workarounds discussed in #6327 are years old (dating back to Bazel 0.x versions) and not documented in an accessible way anywhere.

**Comment by kpvo** [comment]
I am new to bazel and lldb on MacOS and need help.

I have not been able to set breakpoints and get source info in lldb for code compiled with "bazel build --config debug" on MacOS Sequoia 15.5. lldb indicates that my executable does not have debugging symbols.

Could someone tell me what need be done more than the below? Thanks.

Here's my "MODULE.bazel":
--------
bazel_dep(name = "apple_support", version = "1.22.0")
bazel_dep(name = "rules_apple", version = "3.22.0")
bazel_dep(name = "rules_cc", version = "0.1.1")
--------

And, my ".bazelrc":
--------
build:debug --spawn_strategy=local
build:debug --sandbox_debug
build:debug --strip=never
build:debug --features=oso_prefix_is_pwd
build:debug -c dbg

**Comment by keith** [comment]
For future reference, here is all the context and debugging tools to debug issues around this stuff https://www.smileykeith.com/2025/09/21/understanding-apple-debug-info/
