### ISSUE TITLE
[7.4.0] Fail on inapplicable flags on non-common commands expanded from configs

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23113]
Forked from #23105

**Comment by bazel-io** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23142

**Comment by iancha1992** [comment]
Let's include it in 7.4.0 (or 7.3.1 if needed) since we've already started the 7.3.0rc1 release.

**Comment by bazel-io** [comment]
The branch, release-7.4.0, may not exist. Please retry the cherry-pick after the branch is created.

**Comment by bazel-io** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23340
