### ISSUE TITLE
[7.4.0] Introduce `--http_max_parallel_downloads`.

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23119]
Forked from #23106

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/runtime/CommandEnvironment.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> /cc @criemen @fmeum

I can actually cherry-pick this one. I'll do it maybe after the `release-7.4.0` is cut. Thanks

**Comment by criemen** [comment]
Ah I just wanted to look at this one - is there still a chance to get this into 7.3.0 if I submit this today?

**Comment by iancha1992** [comment]
> Ah I just wanted to look at this one - is there still a chance to get this into 7.3.0 if I submit this today?

@Wyverald @meteorcloudy What do you think? We just got done with RC1

cc: @bazelbuild/triage

**Comment by criemen** [comment]
PR is at https://github.com/bazelbuild/bazel/pull/23143, merge or not depending on your rules.

I didn't see the ping here earlier, ideally this would've gone into rc1 😬

**Comment by fmeum** [comment]
Sorry, I also missed the ping.

**Comment by bazel-io** [comment]
The branch, release-7.4.0, may not exist. Please retry the cherry-pick after the branch is created.

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/runtime/CommandEnvironment.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23352
