### ISSUE TITLE
.bazelrc is not picked up when building rule dependency.

### ISSUE THREAD

**Issue by eugeneo** [bazelbuild/bazel#23117]
### Description of the bug:

I have a project that uses ABSL. It has the following `.bazelrc`:
```
build   --cxxopt=-std=c++20 --cxxopt=-Wall --cxxopt=-Werror --cxxopt=-fno-exceptions
```
I can build and run following target just fine:
```
cc_binary(
    name = "generator",
    srcs = ["main.cc"],
    copts = [
        "-std=c++20",
        "-fno-exceptions",
    ],
    deps = [
        "@abseil-cpp//absl/strings",
    ],
)
```
I have the following rule that is trying to run this executable:
```
generator = rule(
    implementation = _generator_rule_impl,
    attrs = {
        "_generator": attr.label(
            default = Label("//generator"),
            executable = True,
            allow_single_file = True,
            cfg = "exec",
        ),
    },
)
```
The executable that is built when this rule is built crashes because ABSL is broken

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Demo project: https://github.com/eugeneo/bazel-absl-bug

Run the executable (runs without issues): `bazel run //generator`
Build the rule: `bazel build //demo:test`

### Which operating system are you running Bazel on?

Ubuntu 22.04

### What is the output of `bazel info release`?

release 7.2.1

### Have you found anything relevant by searching the web?

No

**Comment by Wyverald** [comment]
This is not a bug; .bazelrc does not propagate to dependents. (In fact, it doesn't propagate anywhere.)

Wanting it to propagate is a reasonable feature request, though. That would be a duplicate of https://github.com/bazelbuild/bazel/issues/23028.

**Comment by eugeneo** [comment]
Note that rule and rule usage are in the same project.

Any other way to set global `cxxopts`?

**Comment by Wyverald** [comment]
Ah, sorry. I tried your repro, but the error I see when I run `bazel build //demo:test` is:

```
ERROR: /Users/wyv/test/23117/demo/BUILD:3:10: output 'demo/test-generated' was not created
ERROR: /Users/wyv/test/23117/demo/BUILD:3:10: Action demo/test-generated failed: not all outputs were created or valid
```

Looking at your `//generator` binary, it doesn't actually write any files, but only outputs to stdout (https://github.com/eugeneo/bazel-absl-bug/blob/main/generator/main.cc). This makes your rule unhappy because it wants a file output (https://github.com/eugeneo/bazel-absl-bug/blob/8ff351c1ab8c4da21d4e75c1adaf4211691a14b2/bazel/rules.bzl#L8).

That's what's causing the failure, not flags in .bazelrc.

**Comment by eugeneo** [comment]
On my system it crashes (see std::bad_alloc) but running the executable succeeds. Removing the `cxxopts` from bazelrc makes the binary crash too.
```
$ bazel build //demo:test 
INFO: Analyzed target //demo:test (1 packages loaded, 404 targets configured).
ERROR: /home/eostroukhov/code/oss/bazel-absl-bug/demo/BUILD:3:10: Action demo/test-generated failed: (Aborted): generator failed: error executing Action command (from target //demo:test) bazel-out/k8-opt-exec-ST-d57f47055a04/bin/generator/generator bazel-out/k8-fastbuild/bin/demo/test-generated

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Target //demo:test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.303s, Critical Path: 0.02s
INFO: 2 processes: 2 internal.
ERROR: Build did NOT complete successfully
```

**Comment by Wyverald** [comment]
ah, I can reproduce on Linux. This is probably because the `generator` binary is being built for the exec platform, while `--cxxopt` flags specified on the command line only apply to the target platform (if I understand correctly).

Routing to Configurability team for confirmation.

**Comment by eugeneo** [comment]
I also just setup a clean Ubuntu 24.04:
```
$ bazel run //generator
2024/07/25 20:41:53 Downloading https://releases.bazel.build/7.2.1/release/bazel-7.2.1-linux-x86_64...
Downloading: 68 MB out of 68 MB (100%) 
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //generator:generator (92 packages loaded, 544 targets configured).
INFO: Found 1 target...
Target //generator:generator up-to-date:
  bazel-bin/generator/generator
INFO: Elapsed time: 13.222s, Critical Path: 2.08s
INFO: 35 processes: 5 internal, 30 linux-sandbox.
INFO: Build completed successfully, 35 total actions
INFO: Running command line: bazel-bin/generator/generator
/home/eostroukhov/.cache/bazel/_bazel_eostroukhov/5e1914aa411d995e51a1ffa86e12e2e7/execroot/_main/bazel-out/k8-fastbuild/bin/generator/generator
eostroukhov@eugene-aurora:~/code/bazel-absl-bug$ bazel build //demo:test
INFO: Analyzed target //demo:test (1 packages loaded, 404 targets configured).
ERROR: /home/eostroukhov/code/bazel-absl-bug/demo/BUILD:3:10: Action demo/test-generated failed: (Aborted): generator failed: error executing Action command (from target //demo:test) bazel-out/k8-opt-exec-ST-d57f47055a04/bin/generator/generator bazel-out/k8-fastbuild/bin/demo/test-generated

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Target //demo:test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.891s, Critical Path: 1.30s
INFO: 36 processes: 6 internal, 30 linux-sandbox.
ERROR: Build did NOT complete successfully
```

**Comment by tjgq** [comment]
Try `--host_cxxopts` so that the flags also apply to the exec configuration?

**Comment by eugeneo** [comment]
Thanks. That works. Not sure this will work when I try to ship the module but this issue is resolved.
