### ISSUE TITLE
[7.3.0] Make Window launchers relocatable

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23121]
Forked from #23076

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/test/py/bazel/runfiles_test.py`
`src/test/shell/integration/run_test.sh`

cc: @bazelbuild/triage

**Comment by fmeum** [comment]
https://github.com/bazelbuild/bazel/pull/23135
