### ISSUE TITLE
[7.3.0] Preserve order between stdout and stderr in BES on a best-effort basis

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23130]
Forked from #22795

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/test/java/com/google/devtools/build/lib/runtime/BuildEventStreamerTest.java`

cc: @bazelbuild/triage

**Comment by fmeum** [comment]
Sent a manual cherry-pick at https://github.com/bazelbuild/bazel/pull/23151.

@iancha1992 What's the policy for cherry picks of bug fixes? There are a number of PRs with bug fixes that haven't made the cut for 7.3.0. Is a 7.3.1 release planned?

**Comment by Wyverald** [comment]
We can do a 7.3.1 release if we find a critical bug; otherwise this will need to wait until 7.4.0.

The good news is that, if 7.3.0 isn't delayed by a lot of cherry-picks/RCs, 7.4.0 will likely happen sooner.

**Comment by iancha1992** [comment]
Duplicate: https://github.com/bazelbuild/bazel/issues/23187
