### ISSUE TITLE
macos cc_shared_library dylib not linked to binary when libstatic=False

### ISSUE THREAD

**Issue by matt-sm** [bazelbuild/bazel#23149]
### Description of the bug:

When a cc_library with a cc_shared_library is linked to a cc_binary with libstatic=False, the solib symlink and dylib are not created and linked to the binary on macos.

### Which category does this issue belong to?

C++ Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See branch that extends cpp hello-world example: https://github.com/matt-sm/bazel/blob/share-library-example/examples/cpp/BUILD

```
cc_library(
    name = "hello-lib",
    srcs = ["hello-lib.cc"],
    hdrs = ["hello-lib.h"],
)

cc_shared_library(
    name = "hello-shared-lib",
    deps = [":hello-lib"],
)

cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
    deps = [":hello-lib"],
    linkstatic = False,
)
```
**On linux:**  :tada:

```
bazel build //examples/cpp:hello-world
objdump -p bazel-bin/examples/cpp/hello-world
```
solib folder created and output of objdump:
```
NEEDED               libexamples_Scpp_Slibhello-lib.so
```
and see the .so being linked in the params file:
```
-Lbazel-out/k8-fastbuild/bin/_solib_k8
```

**On macos:** :disappointed: 

```
bazel build //examples/cpp:hello-world
otool -L  bazel-bin/examples/cpp/hello-world
```

no solib symlink created and dylib not listed in otool output:
```
bazel-bin/examples/cpp/hello-world:
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 905.6.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
        /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1775.118.101)
        /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```
params file shows the `.a` is statically linked:

```
-o
bazel-out/darwin_x86_64-fastbuild/bin/examples/cpp/hello-world
bazel-out/darwin_x86_64-fastbuild/bin/examples/cpp/_objs/hello-world/hello-world.o
bazel-out/darwin_x86_64-fastbuild/bin/examples/cpp/libhello-lib.a
```

### Which operating system are you running Bazel on?

Ubuntu 22.04.4 LTS, macos 12.7.2

### What is the output of `bazel info release`?

release 7.2.1

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
git@github.com:matt-sm/bazel.git
a8e0d513704c5f2be44856a769dd9dd2ac04c738
```

**Comment by fmeum** [comment]
You aren't referencing the `cc_shared_library` anywhere. If you want the `cc_binary` to link against to provide the `deps` it contains, you need to add it to the `dynamic_deps` attribute of the `cc_binary` target.

**Comment by matt-sm** [comment]
How does that work on linux then?

**Comment by matt-sm** [comment]
But you are correct:
```
cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
    deps = [":hello-lib"],
    dynamic_deps = [":hello-shared-lib"],
    linkstatic = False,
)
```
Now I'm getting:

```
@loader_path/../../_solib_darwin_x86_64/_Uexamples_Scpp/libhello-shared-lib.dylib
```
And everything is as I'd expect on macos, but I'm still confused why I don't need to add the dynamic_dep on linux.

**Comment by matt-sm** [comment]
Actually it appears I don't need `linkstatic = False` when setting `dynamic_deps` on `cc_binary`?

**Comment by matt-sm** [comment]
It's almost like `linkstatic=False` does nothing on Darwin and `dynamic_deps` is key, but on linux I can get similar results interchanging `linkstatic=False` or `dynamic_deps` (or both).

**Comment by fmeum** [comment]
`linkstatic = False` only has an effect on Linux. It makes it so that *all* transitive `cc_library` deps of the binary are linked dynamically as individual shared libraries. 

With `dynamic_deps`, which works on all platforms, the provided `cc_shared_library`s are linked to replace entire subtrees of the transitive closure (the ones they mention in their `deps`).

To see the difference, you would need a more complicated example in which `hello-lib` itself has `deps`.

**Comment by matt-sm** [comment]
Thanks!

Another question: say I wanted to use static for `opt` and shared for `fastbuild`, the fact that `linkstatic` has no effect on macos makes me think the `dynamic_deps` would need to change across compilation modes?

**Comment by matt-sm** [comment]
There is another use case on macos that I have that I haven't tested but assume won't work: a rules_foreign_cc rule that has a dep on a `cc_shared_library`.  There is only support in that ruleset for `CcInfo`.

**Comment by fmeum** [comment]
> Thanks!
> 
> Another question: say I wanted to use static for `opt` and shared for `fastbuild`, the fact that `linkstatic` has no effect on macos makes me think the `dynamic_deps` would need to change across compilation modes?

Yes, but this can be achieved with `select` and a `config_setting` on `compilation_mode`.

**Comment by matt-sm** [comment]
It is annoying both the dep + dynamic_dep is required on the cc_binary even in this simple example.

I know it's because of the header in the compilation_context.
