### ISSUE TITLE
[Mirror] rules_go 0.49

### ISSUE THREAD

**Issue by tyler-french** [bazelbuild/bazel#23153]
### Please list the URLs of the archives you'd like to mirror:

github.com/bazelbuild/rules_go/releases/download/v0.49.0/rules_go-v0.49.0.zip

**Comment by satyanandak** [comment]
Here you go
https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.49.0/rules_go-v0.49.0.zip
