### ISSUE TITLE
Is there any plan to use support android opensource code build AOSP

### ISSUE THREAD

**Issue by eric0755** [bazelbuild/bazel#2315]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### Environment info
* Operating System:

* Bazel version (output of `bazel info release`):

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by aj-michael** [comment]
You can find Bazel's roadmap (including our Android-specific plans) here: https://bazel.build/roadmap.html

**Comment by eric0755** [comment]
0.7	2017 Q2	
P1. Android Studio interoperability

**Comment by yegle** [comment]
Not sure if anyone is following this bug but https://blog.bazel.build/2020/11/12/aosp_migrating_to_bazel.html
