### ISSUE TITLE
[bazel.build] Problem with /concepts/build-files

### ISSUE THREAD

**Issue by Yossarian0916** [bazelbuild/bazel#23163]
### Page link:

https://bazel.build/concepts/build-files

### Problem description (include actual vs expected text, if applicable):

```<ph type="x-smartling-placeholder>...</ph>``` tag incorrectly shown on web page after switching language to simplified-chinese.

### Where do you see this issue? (include link to specific section of the page, if applicable)

https://bazel.build/concepts/build-files?hl=zh-cn#:~:text=%3Cph%20type%3D%22x,%E5%AE%9A%E4%B9%89%E8%BD%AF%E4%BB%B6%E5%8C%85

**Comment by meteorcloudy** [comment]
Looks like this is fixed by https://github.com/bazelbuild/bazel/commit/572f8e5b25e8ca91998910bf61abdc4344e715dc
