### ISSUE TITLE
[7.4.0] Support `layering_check` with C++ path mapping

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23178]
Forked from #22957

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/rules/cpp/CcStarlarkInternal.java`
`src/main/java/com/google/devtools/build/lib/rules/cpp/CppModuleMapAction.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/rules/cpp/CcStarlarkInternal.java` `src/main/java/com/google/devtools/build/lib/rules/cpp/CppModuleMapAction.java`
> 
> cc: @bazelbuild/triage

@fmeum @comius

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23671
