### ISSUE TITLE
[7.4.0] Add path mapping support for C++ compile action templates

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23176]
Forked from #22890

**Comment by bazel-io** [comment]
The branch, release-7.4.0, may not exist. Please retry the cherry-pick after the branch is created.

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`tools/java/runfiles/BUILD`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23349
