### ISSUE TITLE
[7.4.0] Preserve order between stdout and stderr in BES on a best-effort basis

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23187]
Forked from #22795

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/test/java/com/google/devtools/build/lib/runtime/BuildEventStreamerTest.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/22795
