### ISSUE TITLE
[7.4.0] Add experimental `cc_static_library` rule

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23192]
Forked from #16954

**Comment by iancha1992** [comment]
I am not able to cherry-pick https://github.com/bazelbuild/bazel/commit/c945740bb8296e52a105fd5e4100368543d69bf9 on my own. @fmeum @comius could you please take a look? Thanks!

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23392
