### ISSUE TITLE
[bazel.build] Problem with /rules/lib/providers/ToolchainInfo

### ISSUE THREAD

**Issue by gnanasekarl** [bazelbuild/bazel#23193]
### Page link:

https://bazel.build/rules/lib/providers/ToolchainInfo

### Problem description (include actual vs expected text, if applicable):

Hi, 
![image](https://github.com/user-attachments/assets/a12412ef-4d55-40ae-b555-3b38005c5479)

It would be good the info starts like as new Paragraph.

Right one
![image](https://github.com/user-attachments/assets/b809b6e2-5a89-414b-a340-a49ebb0eea76)

Thanks,
Gnana

### Where do you see this issue? (include link to specific section of the page, if applicable)

https://bazel.build/rules/lib/providers/ToolchainInfo.html

After the heading. It would be really good if the content starts below View Source  or Report An issue button. 

### Any other information you'd like to share?

I can also fix if you share the steps to fix this.

**Comment by fmeum** [comment]
@fweikert I believe that this "regressed" in https://github.com/bazelbuild/bazel/commit/7cd4acd713c6ea786a7b6bc85f72e25ca337ab0e.

**Comment by gnanasekarl** [comment]
Thanks, 

also the below links are not reachable.
https://bazel.build/versions/6.4.0/extending/toolchains
https://bazel.build/versions/6.5.0/extending/toolchains

**Comment by fmeum** [comment]
@meteorcloudy Could we revert https://github.com/bazelbuild/bazel/commit/7cd4acd713c6ea786a7b6bc85f72e25ca337ab0e?

**Comment by fmeum** [comment]
Fixed by https://github.com/bazelbuild/bazel/commit/572f8e5b25e8ca91998910bf61abdc4344e715dc

**Comment by meteorcloudy** [comment]
Sorry for the breakage, we just realized and fixed it yesterday.

**Comment by gnanasekarl** [comment]
Thanks for taking care.
