### ISSUE TITLE
[7.4.0] Fix inconsistent virtual include paths

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23221]
Forked from #23071

**Comment by bazel-io** [comment]
The branch, release-7.4.0, may not exist. Please retry the cherry-pick after the branch is created.

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/rules/cpp/CcStarlarkInternal.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/rules/cpp/CcStarlarkInternal.java`
> 
> cc: @bazelbuild/triage

cc: @fmeum @lberki

**Comment by fmeum** [comment]
https://github.com/bazelbuild/bazel/pull/23361
