### ISSUE TITLE
[7.3.0] action cache inputs with old ~ external module naming poison fresh builds

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23228]
Forked from #23180

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/cmdline/PackageIdentifier.java`

cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
https://github.com/bazelbuild/bazel/pull/23230
