### ISSUE TITLE
Zlib link takedown breaks tensorflow

### ISSUE THREAD

**Issue by Whytehorse** [bazelbuild/bazel#2322]
zlib is now on version 1.2.9 but bazel install script tries to download 1.2.8 which is no longer available. I fixed it by changing the zlib version in /home/ben/git/bazel/tensorflow-cl/tensorflow/workspace.bzl

$ bazel fetch //tensorflow/...
.........
ERROR: /home/ben/git/bazel/tensorflow-cl/tensorflow/core/BUILD:956:1: no such package '@zlib_archive//': Error downloading from http://zlib.net/zlib-1.2.8.tar.gz to /home/ben/.cache/bazel/_bazel_ben/0c0c7c7442356b801bf0702296a71351/external/zlib_archive: Error downloading http://zlib.net/zlib-1.2.8.tar.gz to /home/ben/.cache/bazel/_bazel_ben/0c0c7c7442356b801bf0702296a71351/external/zlib_archive/zlib-1.2.8.tar.gz: 404 Not Found: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /zlib-1.2.8.tar.gz was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
 and referenced by '//tensorflow/core:lib_internal'.
ERROR: /home/ben/git/bazel/tensorflow-cl/tensorflow/core/BUILD:956:1: no such package '@zlib_archive//': Error downloading from http://zlib.net/zlib-1.2.8.tar.gz to /home/ben/.cache/bazel/_bazel_ben/0c0c7c7442356b801bf0702296a71351/external/zlib_archive: Error downloading http://zlib.net/zlib-1.2.8.tar.gz to /home/ben/.cache/bazel/_bazel_ben/0c0c7c7442356b801bf0702296a71351/external/zlib_archive/zlib-1.2.8.tar.gz: 404 Not Found: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /zlib-1.2.8.tar.gz was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
 and referenced by '//tensorflow/core:lib_internal'.
ERROR: Evaluation of query "deps((//tensorflow/... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.

**Comment by klimchuk** [comment]
Stuck with the same problem. Tried to switch it to 1.2.10 in workspace.bzl but of course it did not work.

**Comment by katre** [comment]
I just cloned tensorflow from head, and I see that they are now using the urls parameter for the new_http_archive that downloads zlib. They are now fetching from both zlib.net and from a public mirror, http://bazel-mirror.storage.googleapis.com/zlib.net/zlib-1.2.8.tar.gz.

Are you building from head or a branch? Can you change to use the same mirror? Failing that, it should be straightforward to update tensorflow to zlib 1.2.10, but that would be part of tensorflow.

I am closing this issue, please feel free to re-open if there are Bazel bugs but this needs to be addressed in Tensorflow itself.

**Comment by Whytehorse** [comment]
I also had to change the sha hash to match the 1.2.9 file.
