### ISSUE TITLE
[7.4.0] Remove unused code from Bzlmod package

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23232]
Forked from #23229

**Comment by bazel-io** [comment]
The branch, release-7.4.0, may not exist. Please retry the cherry-pick after the branch is created.

**Comment by bazel-io** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23346

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but failed to push. Please check if the branch, cp23229-7.4.0, already exists
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23359 by @fmeum
