### ISSUE TITLE
Slack link no longer works

### ISSUE THREAD

**Issue by nyurik** [bazelbuild/bazel#23235]
### Description of the bug:

The link to Slack on all docs pages shows an error message.

https://slack.bazel.build/

**Comment by iancha1992** [comment]
@nyurik
The link works for me. Does your error say something like, "This link is no longer active. To join this workspace, you’ll need to ask the person who originally invited you for a new link."?

**Comment by Wyverald** [comment]
Thanks for the report. I've just updated the invite link; please refresh your browser cache and then try again.
