### ISSUE TITLE
`bes_upload_mode=fully_async` can lead to incomplete profile uploads

### ISSUE THREAD

**Issue by iamricard** [bazelbuild/bazel#23267]
### Description of the bug:

When streaming BEP with `fully_async` as the upload mode, the uploaded profiles can sometimes be incomplete. This is more likely to happen if the profile upload is slow (for any reason). 

We think this happens because:

* In `BuildEventServiceModule#beforeCommand` we see a call to [waitForPreviousInvocation](https://github.com/bazelbuild/bazel/blob/4d6513b54fa07321115cac350553b29914d43a65/src/main/java/com/google/devtools/build/lib/buildeventservice/BuildEventServiceModule.java#L371).
* Waiting for the previous invocation includes waiting for BES and file uploads to finish.
* But the profiler starts [before the wait](https://github.com/bazelbuild/bazel/blob/4d6513b54fa07321115cac350553b29914d43a65/src/main/java/com/google/devtools/build/lib/runtime/BlazeCommandDispatcher.java#L383-L392) which leads to bazel to create an new output stream with append=false on `command.profile.gz`.
    * In fact, the waiting period is tracked as [`$module.beforeCommand` in the profile](https://github.com/bazelbuild/bazel/blob/4d6513b54fa07321115cac350553b29914d43a65/src/main/java/com/google/devtools/build/lib/runtime/BlazeCommandDispatcher.java#L429-L442).

### Which category does this issue belong to?

Core, Remote Execution

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Apologies ahead of time because the code is kind of a monster, but it was hard to write a test case for this. I wrote a test case for this bug in https://github.com/iamricard/bazel/commit/f16b0119f53296590d01cfe79038e6b615e789b7#diff-b9f568e8bd3518443c59fae8aae1ebdbeba1662bb8157f23dc70c77ffe16dd65R894-R937.

### Which operating system are you running Bazel on?

MacOS, Linux

### What is the output of `bazel info release`?

8.0.0-pre.20240730.1

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
git@github.com:iamricard/bazel.git
f16b0119f53296590d01cfe79038e6b615e789b7
```

### Any other information, logs, or outputs that you want to share?

* This can probably be mitigated by users who use bazelisk's `tools/bazel` if they generate a unique profile name for every invocation.
* It's probably not an issue for users using `--experimental_stream_log_file_uploads`.

**Comment by saraadams** [comment]
I dug through the code a bit and it looks to me like a `FileOutputStream` with `append=false` is created for the file `command.profile.gz` (assuming no specific profile file name is set via `--profile`). So indeed it looks like the existing file is used to overwrite existing data, without deleting the file before (or writing it to a "unique" path). I wonder whether the problem would at least be alleviated by first deleting the old file, and then creating it anew.

See https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/runtime/BlazeRuntime.java;l=334;drc=914db36648ef734b9b534d2a37907b9505534399 which ends up in https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/vfs/AbstractFileSystem.java;l=137;drc=914db36648ef734b9b534d2a37907b9505534399

**Comment by iamricard** [comment]
It seems like it _could_ be solved by https://github.com/bazelbuild/bazel/issues/18006.

**Comment by saraadams** [comment]
@meisterT Adding you for awareness - do one of the two options to potentially address this problem sound good to you?

**Comment by meisterT** [comment]
Unique profiles, keeping the last N of them (configurable), and symlinking the last one as `command.profile.gz` sounds reasonable to me.

Side note: should we flip the default of `--experimental_stream_log_file_uploads` to true?

**Comment by saraadams** [comment]
> Unique profiles, keeping the last N of them (configurable), and symlinking the last one as `command.profile.gz` sounds reasonable to me.

Do you think work on this might started/completed soon, or do you have a rough timeline?

**Comment by benjaminp** [comment]
> Side note: should we flip the default of `--experimental_stream_log_file_uploads` to true?

Unfortunately, there's no public protocol for streaming uploads and consequently no implementation of this flag in Bazel.
