### ISSUE TITLE
linux-sandbox didn't config /proc/sys/net/ipv4/ping_group_range, leads IPPROTO_ICMP not usable inside network namespace

### ISSUE THREAD

**Issue by comicfans** [bazelbuild/bazel#23275]
### Description of the bug:

I found my code which create socket with IPPROTO_ICMP 
```C
#include <netinet/in.h>
#include <stdio.h>
#include <sys/socket.h>
int main() {
  const int sock_fd = socket(AF_INET, SOCK_DGRAM, IPPROTO_ICMP);

  if (sock_fd == -1) {
    perror("create socket");
    return 1;
  } else {
    printf("success");
    return 0;
  }
}
```
can't run under linux-sandbox, without tags requires-network.
 if test has no requires-network tag, linux-sandbox will create network namespace,
but sys config /proc/sys/net/ipv4/ping_group_range which controls the usability of IPPROTO_ICMP,
will be reset to default "forbidden all" value (see https://forums.opensuse.org/t/network-namespace-does-not-work-for-non-root-user/143817/2 and https://lwn.net/Articles/422330/). so after enter linux-sandbox,
testcase won't be able to use IPPROTO_ICMP to create socket.
this can be resolved when fakeroot is used and write valid gid "0 0 " to /proc/sys/net/ipv4/ping_group_range.
podman also have similar process https://github.com/containers/common/blob/f34973f3d54cf4e7c7e14dac36f32fb6d46d9dd6/pkg/config/containers.conf#L66-L68
I have a branch , https://github.com/bazelbuild/bazel/compare/master...comicfans:bazel:make_ping_work shall I create a PR for this? 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

create a testcase shown in description , don't tag it with requires-network, then it will fail under linux-sandbox

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

I'm testing on master dacb794

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

I only build bazel linux-sandbox with
```bash
bazel build -c dbg //src/main/tools:linux-sandbox
```

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
https://github.com/bazelbuild/bazel.git
3a1e9b83f8a31d0cea308966f493e50ea643ad00
```

### Have you found anything relevant by searching the web?

https://forums.opensuse.org/t/network-namespace-does-not-work-for-non-root-user/143817
https://github.com/containers/common/blob/f34973f3d54cf4e7c7e14dac36f32fb6d46d9dd6/pkg/config/containers.conf#L66-L68
https://lwn.net/Articles/422330/

**Comment by zhengwei143** [comment]
A PR sounds reasonable to me, would it work if you used the `gid` set in `SetupUserNamespace` https://github.com/bazelbuild/bazel/blob/2bb4eb99fb012a9b628f2953ce149586456be18c/src/main/tools/linux-sandbox-pid1.cc#L231 and set `ping_group_range` to `0 <gid>`?

**Comment by comicfans** [comment]
I've tried it and it won't work (https://github.com/opencontainers/runc/discussions/4366)

both value of ping_group_range, must be valid gid in the namespace, if any one of them is not, then kernel will reject changes and write fail (https://discuss.linuxcontainers.org/t/setting-net-ipv4-ping-group-range-inside-an-lxd-container/2162/4), 
  bazel use unpriviledged namespace, it can only have 1 gid mapped, thus both values must be inner_gid.  write to this file requires root permission, so it's impossible to write values other than 0 0 .  so in conclusion, this can only works under fakeroot  (seems a bug of kernel to me, too restrict on IPPROTO_ICMP, or default config inconsistent between sysctl and unpriviledged namespace), 

I've created PR here https://github.com/bazelbuild/bazel/pull/23411
