### ISSUE TITLE
[7.4.0] remote_coverage_tools/Main cannot locate runfiles directory when building with `--nobuild_runfile_links`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23277]
Forked from #20577

**Comment by bazel-io** [comment]
The branch, release-7.4.0, may not exist. Please retry the cherry-pick after the branch is created.

**Comment by bazel-io** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23345

**Comment by Wyverald** [comment]
(see https://github.com/bazelbuild/bazel/pull/23345#issuecomment-2403431381)
