### ISSUE TITLE
[Mirror] rules_kotlin

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#23299]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/rules_kotlin/releases/download/v1.9.6/rules_kotlin-v1.9.6.tar.gz

**Comment by keertk** [comment]
https://mirror.bazel.build/github.com/bazelbuild/rules_kotlin/releases/download/v1.9.6/rules_kotlin-v1.9.6.tar.gz
