### ISSUE TITLE
[7.3.1] Add a version indicator and selector to all docs pages

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#23303]
### Commit IDs

2562707390fed314e2fb56eb6f92afa964117d25

### Category

team-Documentation

### Reviewers

@meteorcloudy, @Wyverald

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/23304: https://github.com/bazelbuild/bazel/commit/2562707390fed314e2fb56eb6f92afa964117d25.
