### ISSUE TITLE
Tutorial: cannot deploy to App Engine: JDK 8 not supported

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#2330]
The Installation instructions tell me to install JDK 8: https://bazel.build/versions/master/docs/install.html#1-install-jdk-8-1

However, when I want to [deploy my App Engine app](https://bazel.build/versions/master/docs/tutorial/backend-server.html#deploy-to-google-app-engine) and run `$WORKSPACE/bazel-bin/backend/backend.deploy test-gae-bazel` I get: `java.lang.IllegalArgumentException: Class file is Java 8 but max supported is Java 7`

Looking at the README of https://github.com/bazelbuild/rules_appengine, this seems to be a known problem and the way to solve it is to use this build commend: `bazel build --java_toolchain=@io_bazel_rules_appengine//appengine:jdk7 //backend:backend`
However, when I run it, it fails:  `no such target '@io_bazel_rules_appengine//appengine:jdk7': target 'jdk7' not declared in package 'appengine'`.

What's the best way to fix the tutorial?

**Comment by katre** [comment]
I see that the rules_appengine repository does define a java_toolchain named "jdk7" (see https://github.com/bazelbuild/rules_appengine/blob/master/appengine/BUILD#L28). So I am curious about why it's not resolving for you.

Do you have a repository I can clone and a sample bazel command I can run to try and reproduce this?

**Comment by steren** [comment]
I am following the Bazel tutorial, the code is at
https://github.com/bazelbuild/examples/tree/master/tutorial/backend

**Comment by katre** [comment]
The issue is that the current rules_appengine release used by the examples is 0.0.3, which doesn't include the :jdk7 target.

I've cut a new 0.0.5 release of rules_appengine, and I'll shortly push a commit to the examples to start using it. It looks like everything builds correctly, but once that's out I'd like you to cherry-pick it and verify that it solves your problem and doesn't need any further work.

**Comment by steren** [comment]
Sounds good, thanks. Count on me to verify the tutorial.

**Comment by katre** [comment]
Please take a look at https://github.com/bazelbuild/examples/pull/21

**Comment by mhlopko** [comment]
Hi Steren,
can I close this issue now? Is it working for you after the new rules_appengine release?

**Comment by steren** [comment]
Yes, this issue is fixed in https://github.com/steren/bazel/commit/cf6fdcdee203ea3e37f6340c8476020e4d090717
