### ISSUE TITLE
failure tests using the analysis test framework break `bazel cquery //...`

### ISSUE THREAD

**Issue by matt-sm** [bazelbuild/bazel#23318]
### Description of the bug:

I have copied the the code at https://bazel.build/rules/testing verbatim to https://github.com/matt-sm/failing-test-example

If I run `bazel test //mypkg:myrules_test` all works as expected.

If I run `cquery //...` I get

```
ERROR: /home/msmith/git/failing-test-example/mypkg/BUILD.bazel:11:19: in myrule rule //mypkg:this_should_fail: 
Traceback (most recent call last):
        File "/home/msmith/git/failing-test-example/mypkg/myrules.bzl", line 9, column 13, in _myrule_impl
                fail("This rule should never work")
Error in fail: This rule should never work
ERROR: /home/msmith/git/failing-test-example/mypkg/BUILD.bazel:11:19: Analysis of target '//mypkg:this_should_fail' failed
ERROR: Analysis of target '//mypkg:this_should_fail' failed; build aborted
``` 
I assume a failure test should not break cquery?

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

As per the description

### Which operating system are you running Bazel on?

Ubuntu 22.04.4 LTS

### What is the output of `bazel info release`?

release 7.3.0

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
https://github.com/matt-sm/failing-test-example.git
2e962a65565b7de8e57c186c90dcd76b64c080b2
```

### Any other information, logs, or outputs that you want to share?

works:
```
bazel cquery //mypkg:myrules_test
bazel cquery //mypkg:mytarget
```
fails:
```
bazel cquery //mypkg/... 
```

**Comment by katre** [comment]
In general, `cquery` is not robust in the face of failing builds, whether these are intentionally failing or not.  We've tried to work around this where possible but, fundamentally, if the target can't be analyzed then `cquery` can't do very much.

Closing this because it's not something we can fix.
