### ISSUE TITLE
Execution log + remote cache = very long build time

### ISSUE THREAD

**Issue by OparinE** [bazelbuild/bazel#23319]
### Description of the bug:

Official way of cache hit debugging is based on execution logs gathering [cache-remote](https://bazel.build/remote/cache-remote).
However if we build with execution_logs ON and remote_cache ON build time increases dramatically (x2-x5).

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have a target of 30 build actions (cpp code + packaging).
Build time average (sec):
no options:___________________________________28
disk cache in ON:_____________________________13
execution json log is ON:_____________________28
execuion json log is ON, disk cache is ON:___59

Disk cache is ON build shows repos fetching time. If bare in mind this, 
(execuion json log is ON + disk cache is ON) / execution json log is ON = 46 / 15 = 3 times

### Which operating system are you running Bazel on?

Windows

### What is the output of `bazel info release`?

7.0.2

**Comment by tjgq** [comment]
Consider using `--experimental_execution_log_compact_file` instead (see https://github.com/bazelbuild/bazel/issues/18643#issuecomment-1945078491). The `--execution_log_json_file` and `--execution_log_binary_file` formats are fundamentally inefficient; it's unlikely that they can be improved.

**Comment by OparinE** [comment]
@tjgq , I tries `--experimental_execution_log_compact_file` on bazel 7.2.0. General behavior is the same.

**Comment by tjgq** [comment]
Could you share two trace profiles (`--profile`) for your build, with and
without the compact execution log enabled, so I could better understand
where the time is going? Ideally for a build where actions are all hitting
the disk cache, which is the worst case for the execution log (very little
work happening elsewhere).

Also, how big is the execution log (in compact format)?

**Comment by OparinE** [comment]
[profile_with_cache_with_exe_logs.tar.gz](https://github.com/user-attachments/files/16659732/profile_with_cache_with_exe_logs.tar.gz)
[profile_without_cache_with_exe_logs.tar.gz](https://github.com/user-attachments/files/16659733/profile_without_cache_with_exe_logs.tar.gz)
[profile_without_exe_logs_with_cache.tar.gz](https://github.com/user-attachments/files/16659734/profile_without_exe_logs_with_cache.tar.gz)

@tjgq , profiles are added.

**Comment by tjgq** [comment]
It looks like these are for the json format. Can you also capture a profile for the compact format under the same conditions?

> in my opinion, --execution_log_json_file works faster than --experimental_execution_log_compact_file, because there is no zipping operation.

This shouldn't be the case for a typical build. The zstd compression is not the only difference between the two formats; the compact format avoids redundant work in other ways. (It's possible that your build is atypical, which is why I'd like to see both profiles).

**Comment by OparinE** [comment]
@tjgq , performance with `--experimental_execution_log_compact_file=` looks much better.
There is no build time big difference between  (exe_logs is ON + cache is ON) and (exe_logs is ON) as it was with json execution logs.
Seems like json and pure binary logs from bazel perspective are not critical tasks, am I right?
If so, please close the issue. I'll to switch to next bazel version.

**Comment by tjgq** [comment]
Thanks for checking that the compact format works for you!

I will close this issue, as I don't think it's possible to improve performance for the json/binary formats. The way forward is to point people to the compact format and deprecate them.
