### ISSUE TITLE
WORKSPACE rules can break on case-insensitive file systems (e.g. OSX)

### ISSUE THREAD

**Issue by GregBowyer** [bazelbuild/bazel#2331]
### Description of the problem / feature request / question:
This is related somewhat to #552

Lets say you have a `WORKSPACE` rule like so

```
new_git_repository(
    name = 'ck',
    remote = 'https://github.com/concurrencykit/ck.git',
    tag = '0.5.2',
    build_file = 'build_tools/externals/libck.BUILD',
)
```

And lets say that directory expands like so
```
gregbowyer@USSFRGBO-ML ~/work$ ls /private/var/tmp/_bazel_gregbowyer/ed2084cb983d1d34833966860868e551/external/ck
LICENSE  Makefile.in  README  WORKSPACE  build  configure  doc  include  regressions  src  tools
gregbowyer@USSFRGBO-ML ~/work$
```

That leads to the irritating situation where we try to copy `libck.BUILD` into that directory as `BUILD`.
This is different from #552 in that in `WORKSPACE` rules we dont seem to have the ability to state it should become `BUILD.bzl`. Maybe just defaulting to `BUILD.bzl` will work as a solution?

### Environment info
* Operating System: OSX (but I figure anything with a case-insensitive filesystem)
* Bazel version (output of `bazel info release`): 
```
gregbowyer@USSFRGBO-ML ~/work/pers $ bazel version
Build label: 0.4.3-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 22 15:20:22 2016 (1482420022)
Build timestamp: 1482420022
Build timestamp as int: 1482420022
```

**Comment by katre** [comment]
What version of Bazel are you using? I recently committed bazelbuild/bazel@b9c65d1 (after initially committing it, then reverting it), which does exactly this: external repositories will use BUILD.bazel instead of BUILD to fix this issue.

Can you try building Bazel from head and seeing if that has the same issue? This is pretty much a duplicate of #2226.

**Comment by GregBowyer** [comment]
Yes that fixed it
