### ISSUE TITLE
In-process symlink creation doesn't materialize unresolved symlinks as such

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#23327]
I would just like to point out this breaking issue with `rules_js` that I found when `--experimental_inprocess_symlink_creation` is turned on in Bazel 7.2.

Unsure if its Bazel, or the rules that aren't vibing with this in the way that is expected, but the rule set is popular enough you may want to see it resolved first.

I suspect I'm the first-mover to come across this.

Here is the ticket: https://github.com/aspect-build/rules_js/issues/1877

_Originally posted by @adamscybot in https://github.com/bazelbuild/bazel/issues/4327#issuecomment-2270135741_

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.4.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.4.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=7.4.0rc1`. Thanks!
