### ISSUE TITLE
"run" command used to start javac

### ISSUE THREAD

**Issue by charlesprogrammr** [bazelbuild/bazel#2332]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

I am trying to build bazel from scratch on a windows 7 32 bit machine.

### Description of the problem / feature request / question:
What I finally had running suddenly stopped, complaining about the line [  run "${JAVAC}" -J-Xms1228m -J-Xmx1228m -nowarn -classpath "${classpath}" -sourcepath "${sourcepath}" \
      -d "${output}/classes" -source "$JAVA_VERSION" -target "$JAVA_VERSION" \
      "@${paramfile}"] that it couldn't find the command run, I kept looking for why it wouldn't run javac, and found it in the correct place, thinking the problem was with the quoted path (I had the JDK in "Program Files",) but that wasn't the problem, it was the "run" command was missing.

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._
What is the missing file, is it a python file, shell script, an executable (.exe), java file, or what, I cannot tell, since it is now missing. Can you tell me where I can get it, is it part of a package in Msys2 (which one?,) part of the project from git? 

### Environment info
* Operating System:
Windows 7 32 bit

* Bazel version (output of `bazel info release`):
0.1.0 from scratch, eventually 0.4.2 once I have a working bazel 0.1.0

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by katre** [comment]
We are building on Windows in our CI server (https://ci.bazel.io) and not seeing this issue. Can you give more details about what you had running? Is the "run ${JAVAC} ..." you refer to the line in scripts/bootstrap/compile.sh? If so, run is defined in scripts/bootstrap/buildenv.sh (https://github.com/bazelbuild/bazel/blob/master/scripts/bootstrap/buildenv.sh#L148). Possibly it is being confused by the -J options you have added to javac? I'm not sure why it wouldn't be finding the run function unless you're made significant changes and aren't including buildenv.sh from the root compile.sh

**Comment by charlesprogrammr** [comment]
Katre,

Let me begin with a thank you for responding. I had msys2 and mingw64 running in a Windows 7 32-bit environment with 2GB RAM, and a couple of drives running ReadyBoost. I installed the 32-bit msys2 into a folder named "msys64" since the name is all that is really checked, as far as I know. Thus I eliminated that part of the 64-bit requirements. I downloaded and installed the prereqs like protoc/protobuf, etc and got them to compile and moved the required files as per the documentation for building bazel.
I had the following environment variables set in my .bashrc:

`export MAVEN_HOME=/c/tools/apache-maven-3.3.9

export M2_HOME=/c/tools/apache-maven-3.3.9

export PATH=/c/tools/apache-maven-3.3.9/bin:/c/Program\  Files/Java/jdk1.8.0_112/bin:$PATH

export BAZEL_SH=/c/tools/msys64/usr/bin/bash.exe

export BAZEL_WRKDIR=c:/temp/shrtpath

export TMPDIR=$BAZEL_WRKDIR/temp

mkdir -p $TMPDIR

export EXTRA_BAZEL_ARGS='--jobs 50'

export CC='/usr/lib/gcc/i686-pc-msys/5.3.0/cc1.exe'

export JAVA_HOME='/c/Progra~1/Java/jdk1.8.0_112'

export JAVAHOME=$JAVA_HOME
`
Yes, the that is the script in question, scripts/bootstrap/compile.sh. I just now checked, and the script got truncated at line 138, cleanly at the end of the function get_java_version(). This was the bazel0.1.0 version of the file, so of course I wouldn't notice it. I'm glad I asked.

I actually had a bazel built, but the script never told me about it, although I manually checked. When I tried running again, I ended up doing a control-c and lost that build, as well as the run command. I kept getting an error telling me about the line, but thought it was about the quoted (escaped) path for javac. I couldn't find anything related to the run command, so I figured I corrupted the filesystem, and tried to do a reinstall of msys2 and mingw64, but they wouldn't install over the existing and so uninstalled them and reinstalled.

BTW. The -J options allowed me to get as far as I did. I kept having to restart until I found a value that worked. I'll keep trying until I get a working build environment, then I'll try on the ultimate goal, to get a Windows 32-bit build of TensorFlow, hopefully a working one.

**Comment by katre** [comment]
Like I said, I'm very surprised that the out-of-the-box build isn't working for you, since we build continuously in our CI setup (visible at https://ci/bazel.io). If you're still using 0.1.0, however, that could be an issue.

Can you grab a copy of the latest release, 0.4.3 (available here: https://bazel.build/versions/master/docs/install.html#windows) and try that?

If you're not actually interested in building Bazel, but instead just want to use it, you could also try just installing the prebuilt binary from the Chocolatey link in the install.html page.

**Comment by charlesprogrammr** [comment]
I'd love to just use it, but unfortunately, this is 32-bit Windows 7.

**Comment by katre** [comment]
You can try building the latest source, but we aren't taking any steps to ensure operation on 32-bit systems so I am not sure what will or will not work.

If you run into specific problems feel free to open a new issue with full details and we will try to investigate.
