### ISSUE TITLE
[7.4.0] Fix in-process materialization of unresolved symlinks in runfiles

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23329]
Forked from #23328

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/starlark/builtins_bzl/common/builtin_exec_platforms.bzl`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/starlark/builtins_bzl/common/builtin_exec_platforms.bzl`
> 
> cc: @bazelbuild/triage

cc: @tjgq @fmeum

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23391
