### ISSUE TITLE
[Mirror] bazel-gazelle v0.38.0

### ISSUE THREAD

**Issue by tongke6** [bazelbuild/bazel#23330]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/bazel-gazelle/archive/refs/tags/v0.38.0.tar.gz

**Comment by satyanandak** [comment]
Here you go 
https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/archive/refs/tags/v0.38.0.tar.gz
