### ISSUE TITLE
[7.4.0] Cherrypick 638f293a0f608db0ea6de4e0b58cd61870086db6 into 7.4.0

### ISSUE THREAD

**Issue by ahumesky** [bazelbuild/bazel#23347]
### Commit IDs

638f293a0f608db0ea6de4e0b58cd61870086db6

### Category

team-Android

### Reviewers

@meteorcloudy

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/23348: https://github.com/bazelbuild/bazel/commit/638f293a0f608db0ea6de4e0b58cd61870086db6.
