### ISSUE TITLE
[7.4.0] Delay execution phase reporting in Skymeld.

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#23354]
### Commit IDs

5744abd7831fec791067ec8e182cd47f82aaaf3e

### Category

team-Remote-Exec

### Reviewers

@Wyverald, @meteorcloudy, @mei

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23353

**Comment by bazel-io** [comment]
Failed commits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/5744abd7831fec791067ec8e182cd47f82aaaf3e.
Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Looks like I cannot cherry-pick this. Could you please take a look?

cc: @fmeum @Wyverald @meteorcloudy @meisterT

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23362 by @fmeum
