### ISSUE TITLE
Bazel should error out if --output_user_root is in the workspace

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#2335]
Otherwise you get confusing error messages if you try to build `//...` and your bazel install is a subdirectory.

**Comment by helenalt** [comment]
@laszlocsomor, please classify to the appropriate component and update a priority. Thanks!

**Comment by laszlocsomor** [comment]
Update: I haven't done anything for this bug and likely won't do anything before end of Q2'18.

**Comment by laszlocsomor** [comment]
Bumping to P2. Easily triggered bug with Docker, see https://github.com/bazelbuild/bazel/issues/1787#issuecomment-396364911

**Comment by laszlocsomor** [comment]
Can't fix this before 1.0, removing tag.

**Comment by kshyanashree** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
