### ISSUE TITLE
[7.4.0] Replace "checking cached actions" message when no action is running.

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#23355]
### Commit IDs

b215cb804510bdc0ff357fd90c3c6fdf9aa77b4c

### Category

team-Remote-Exec

### Reviewers

@meisterT, @Wyverald, @meteorcloudy

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/23357: https://github.com/bazelbuild/bazel/commit/b215cb804510bdc0ff357fd90c3c6fdf9aa77b4c.
