### ISSUE TITLE
[7.4.0] Fix locations reported in repo rule instantiation errors for extensions

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23364]
Forked from #23363

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/test/py/bazel/bzlmod/bazel_module_test.py`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/test/py/bazel/bzlmod/bazel_module_test.py`
> 
> cc: @bazelbuild/triage

@fmeum @Wyverald @meteorcloudy

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23390
