### ISSUE TITLE
[7.4.0] Fix local execution deduplication to work with optional outputs

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23377]
Forked from #23296

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java`
> 
> cc: @bazelbuild/triage

@fmeum @tjgq

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23674
