### ISSUE TITLE
[7.4.0] No longer eagerly fetch labels in repo rule attributes

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23372]
Forked from #23371

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryContext.java`
`src/test/shell/bazel/starlark_prefetching_test.sh`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryContext.java` `src/test/shell/bazel/starlark_prefetching_test.sh`
> 
> cc: @bazelbuild/triage

cc: @fmeum @Wyverald @meteorcloudy

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23389
