### ISSUE TITLE
[7.4.0] Represent symlink actions in the compact execution log

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23380]
Forked from #23320

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/exec/SpawnLogReconstructor.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23403

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23398
