### ISSUE TITLE
Implement proper, language-agnostic handling of runfiles trees

### ISSUE THREAD

**Issue by cnsgsz** [bazelbuild/bazel#2339]
I have a python test named foo whose main is foo.py that depends on cpp binary. I have it set up as recommended in #703. It works when it is run in bazel test.

However, I sometimes want to run the python test manually by invoking foo (the executable python script that's generated by bazel that sits in the same bazel-bin directory as foo.runfiles). However it complains that the cpp binary cannot be found.

I tried something like #231, but sys.argv[0] points to foo.py and it does not seem straightforward to get the cpp binary path from there?

It is not just for python test. Sometime I have a python binary that depends on cpp binary too. But I assume they are similar.

Since bazel generates foo and put the specified data in foo.runfiles already, it seems natural that I should be able to just specify some relative path as in #703, call foo from any cwd, and foo does the work to make sure the cpp binary can be found based on the relative path? Or is it possible for foo to pass foo.py some environment variable RUNFILES_DIR that foo.py can use like os.path.join(RUNFILES_DIR, "relative/path/to/cpp/binary")?

**Comment by ulfjack** [comment]
We had to roll back the change. Why isn't that commit linked here?

**Comment by lberki** [comment]
So, after some consultation with @ulfjack , I realized that we can't solve this in a principled way without figuring out how runfiles trees should work in general. Therefore, I'm changing this bug to "we should really figure out how runfiles trees should work" in general.

**Comment by meisterT** [comment]
@lberki is this a P2?

**Comment by fmeum** [comment]
The recommended way to access runfiles is now to use the runfiles libraries (among others`@rules_python//python/runfiles`, `@bazel_tools//tools/java/runfiles`, `@bazel_tools//tools/cpp/runfiles`, `@bazel_tools//tools/bash/runfiles`).

**Comment by cnsgsz** [comment]
Will it suffice to use paths relative to a repo's root directory? When would these runfiles libraries be necessary?
Using the relative paths seems to work for `bazel run` and `bazel test`. It should also work in the deployment of the runfiles by setting CWD appropriately?

**Comment by fmeum** [comment]
@cnsgsz If you only ever reference files in your main repository, exclusively target a Unix variant and don't run your targets as part of build actions, then you don't need runfiles libraries. In all other cases you are likely better off with them.
