### ISSUE TITLE
Bazel does not honor `umask` anymore

### ISSUE THREAD

**Issue by doak** [bazelbuild/bazel#23405]
### Description of the bug:

Up to version `7.0.0` directories of the cache had been created and permissions had been only pruned by `umask` like it is usually done by Unix/Linux SW.
This had changed with `7.0.0` with 4da06426be298a350260879852db651da389c6c8 (and probably related commits).

This interferes with the use case to share the disk as well as repository cache on a single machine by giving mutual write access to the folders using a dedicated group. This may not be the preferred approach, but is simple enough and used to work quite well. For instance:
* Configure `umask` to `0002`.
* Assign relevant users to a group `bazel-cache`.
* Create the toplevel cache directory and `chmod g+ws <dir>` and `chown :bazel-cache <dir>`.
* Configure `--disk_cache` and `--repository_cache` accordingly.

Quote of the commit message
> Making all directories group and world writable seems excessive;

Imho the user, system configuration or whatever decides if it is wanted – Bazel ist not in charge for that.

### Which category does this issue belong to?

Core

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 7.0.1

### If this is a regression, please try to identify the Bazel commit where the bug was introduced with bazelisk --bisect.

4da06426be298a350260879852db651da389c6c8

**Comment by fmeum** [comment]
@tjgq

**Comment by tjgq** [comment]
Sorry for the breakage; it never occurred to me that users might be relying on `umask`. I will send a change to revert to the previous behavior.

**Comment by tjgq** [comment]
@bazel-io flag 7.4.0

**Comment by iancha1992** [comment]
@bazel-io fork 7.4.0

**Comment by doak** [comment]
> I will send a change to revert to the previous behavior.

Thanks a lot!

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.4.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.4.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=7.4.0rc1`. Thanks!

**Comment by doak** [comment]
> A fix for this issue has been included in [Bazel 7.4.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.4.0rc1). Please test out the release candidate and report any issues as soon as possible. If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=7.4.0rc1`. Thanks!

@iancha1992, I am very sorry, I apparently did not check.
Our project switched from 7.2.1 to 7.5.0 a few days ago and the same issue is still present.

Did you forget to adapt these two lines? It works for me™ if using `0777` for both.
* [UnixFileSystem.java:338](https://github.com/bazelbuild/bazel/pull/23525/files#diff-baf4ed47a585163a9e2f613bc6b1c8c2e20df9fe2689999f3a18c94ce9e8d712R338)
* [UnixFileSystem.java:358](https://github.com/bazelbuild/bazel/pull/23525/files#diff-baf4ed47a585163a9e2f613bc6b1c8c2e20df9fe2689999f3a18c94ce9e8d712R358)

**Comment by doak** [comment]
What about the other release branches, namely `8.x` and `9.x`? Do they already contain the correct fix?

**Comment by tjgq** [comment]
Yes, the fix was submitted before the 8.x and 9.x branches were cut.

**Comment by doak** [comment]
@iancha1992, @tjgq: Since there will be a `7.6.0` release, please consider to fix it there as well.

**Comment by tjgq** [comment]
Thanks for the reminder. I've sent https://github.com/bazelbuild/bazel/pull/25613.
