### ISSUE TITLE
Replacement of Unsafe code

### ISSUE THREAD

**Issue by RuixiangJiang** [bazelbuild/bazel#23409]
### Description of the feature request:

Greetings!

I notice that `sun.misc.Unsafe` appears in the 7.3.0 release version, and Unsafe accesses off-heap memory, which will be potentially deprecated in the future Java version. I wonder whether your team will replace Unsafe and ByteBuffer with FFM in Java 22, which is safer without losing high performance.

### Which category does this issue belong to?

Java Rules, Performance

### What underlying problem are you trying to solve with this feature?

Unsafety due to usage of `sun.misc.Unsafe`

### Which operating system are you running Bazel on?

Mac OS 14.6.1

### What is the output of `bazel info release`?

release 7.3.0- (@non-git)

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

`env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=22" bash ./compile.sh`

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
git@github.com:Software-Aurora-Lab/Benchmarks-for-LLM.git
08dd0ec8cb9b23ec32b1ae1b73be16b0e8c9d2b7

(That's my own public repo)
```

### Have you found anything relevant by searching the web?

JEP471 (https://openjdk.org/jeps/471) indicates the way to remove Unsafe.

**Comment by meisterT** [comment]
cc @greatfilter @jin

**Comment by jin** [comment]
cc @aoeui (I think this is the account Shahan uses), who has the most context here (for the serialization dependencies on Unsafe)

For Googlers: b/331765692 is the internal bug reference.

**Comment by fmeum** [comment]
There are some non-serialization usages of Unsafe for optimized String access, but those can easily be migrated to `VarHandle`.

**Comment by RuixiangJiang** [comment]
Thanks for your response!
