### ISSUE TITLE
[7.4.0] Let repo rule attributes reference extension apparent names

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23407]
Forked from #23369

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionEvalStarlarkThreadContext.java`
`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalFunction.java`
`src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionResolutionTest.java`
`src/test/java/com/google/devtools/build/lib/bazel/bzlmod/TypeCheckedTagTest.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionEvalStarlarkThreadContext.java` `src/main/java/com/google/devtools/build/lib/bazel/bzlmod/SingleExtensionEvalFunction.java` `src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionResolutionTest.java` `src/test/java/com/google/devtools/build/lib/bazel/bzlmod/TypeCheckedTagTest.java`
> 
> cc: @bazelbuild/triage

cc: @fmeum @Wyverald @meteorcloudy

**Comment by fmeum** [comment]
@Wyverald Could you help cherry-pick this? It looks like there are a number of refactoring commits missing (AutoValue -> record, module thread context extraction, ...) but I don't know which ones exactly.

**Comment by Wyverald** [comment]
uh, apparently I already did that last week... 😅 https://github.com/bazelbuild/bazel/pull/23585
