### ISSUE TITLE
bazel build failed for target name not equal link output name

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/bazel#23402]
### Description of the bug:

I setup mingw32-w64 to cross compiling for windows on a linux host, a cc_binary's name is brotli, but linker generate a brotli.exe finally, this cause error, how to fix this problem? 
```
output 'external/brotli/brotli' was not created
 Linking external/brotli/brotli failed: not all outputs were created or valid
Using built-in specs.
```

### Which category does this issue belong to?

C++ Rules

### Which operating system are you running Bazel on?

ubuntu 22.04

### What is the output of `bazel info release`?

7.2.0

**Comment by iancha1992** [comment]
@xiedeacc Could you please provide complete steps to reproduce this issue?

**Comment by xiedeacc** [comment]
here is demo: https://github.com/xiedeacc/bazel_template/tree/windows
```
git clone git@github.com:xiedeacc/bazel_template.git
cd bazel_template
git checkout windows
clear && bazel build --config=gcc_windows_x86_64 @brotli//:brotli -s
```

**Comment by fmeum** [comment]
Are you setting an `artifact_name_pattern` to tell Bazel that executables have an `.exe` extension? It looks like you aren't, see https://github.com/xiedeacc/cc_toolchains/blob/master/toolchain%2Funix_cc_toolchain_config.bzl#L1593 for an example.

**Comment by xiedeacc** [comment]
ok, thanks @fmeum

**Comment by xiedeacc** [comment]
it seems should use https://github.com/bazelbuild/bazel/blob/master/tools/cpp/windows_cc_toolchain_config.bzl
