### ISSUE TITLE
[7.4.0] Use retrieved nestedSet for symlink planting

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23408]
Forked from #23400

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/skyframe/BuildDriverFunction.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/skyframe/BuildDriverFunction.java`
> 
> cc: @bazelbuild/triage

@fmeum @joeleba

**Comment by joeleba** [comment]
https://github.com/bazelbuild/bazel/pull/23439
