### ISSUE TITLE
Windows: $ in output_base is breaking paths.

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#2342]
On Windows, trying to build Bazel from head, we are having repeated errors on Windows.

(See http://ci.bazel.io/view/Dashboard/job/Bazel/1151/JAVA_VERSION=1.8,PLATFORM_NAME=windows-x86_64/console for sample):
```
ERROR: C:/jenkins/workspace/Bazel/JAVA_VERSION/1.8/PLATFORM_NAME/windows-x86_64/src/java_tools/junitrunner/java/com/google/testing/coverage/BUILD:72:1: Executing genrule //src/java_tools/junitrunner/java/com/google/testing/coverage:Jacoco_jarjar failed: bash failed: error executing command C:/tools/msys64/usr/bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 127.
/usr/bin/bash: C:/bazel_ci/temp/_bazel_SYSTEM/enRRqR/execroot/windows-x86_64/bazel-out/host/bin/third_party/java/jarjar/jarjar_bin: No such file or directory
```

The actual output base for the SYSTEM user is:
```
C:\bazel_ci\temp\_bazel_SYSTEM\$7enRRqR
```

The output base shown in this command is:
```
C:/bazel_ci/temp/_bazel_SYSTEM/enRRqR
```

Looks like the $7 is being interpreted by msys2/bash as an environment variable and being removed.

**Comment by katre** [comment]
Not sure if it's directly involved, but the error mentions jarjar and git bisect points to 823091f7516abf7d854021edc765daf1467f1647 as the culprit, so assigning to @lberki

**Comment by katre** [comment]
Actually, that can't be the root cause, it's just where the symptom shows up. Sigh, continuing to search.

**Comment by katre** [comment]
Looks like the issue is here: https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/blaze_util_windows.cc#L1059

**Comment by abergmeier** [comment]
> // Builds a shorter output base dir name for Windows.

IMO having that special behavior _only_ for Windows is guaranteed to break thinks further down the line when devs are not using Windows as their primary platform.
