### ISSUE TITLE
[Mirror] gazelle 0.38.0

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#23432]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.38.0/bazel-gazelle-v0.38.0.tar.gz

**Comment by satyanandak** [comment]
Here you go
https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.38.0/bazel-gazelle-v0.38.0.tar.gz
