### ISSUE TITLE
[7.4.0] Force synchronous upload and reuse of possibly modified spawn outputs

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23444]
Forked from #23382

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java`
`src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnCache.java`
`src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnCacheTest.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java` `src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnCache.java` `src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnCacheTest.java`
> 
> cc: @bazelbuild/triage

@fmeum @tjgq

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23674
