### ISSUE TITLE
[7.4.0] Cherrypick b17552bfba80e69a4d86d5566c0237e6b8438fcf

### ISSUE THREAD

**Issue by ahumesky** [bazelbuild/bazel#23440]
### Commit IDs

b17552bfba80e69a4d86d5566c0237e6b8438fcf

### Category

team-Android

### Reviewers

@comius

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/23441: https://github.com/bazelbuild/bazel/commit/b17552bfba80e69a4d86d5566c0237e6b8438fcf.
