### ISSUE TITLE
[7.4.0] Bazel does not honor `umask` anymore

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23449]
Forked from #23405

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/unix/UnixFileSystem.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/unix/UnixFileSystem.java`
> 
> cc: @bazelbuild/triage

@fmeum @tjgq

**Comment by tjgq** [comment]
Manual cherry-pick in https://github.com/bazelbuild/bazel/pull/23525
