### ISSUE TITLE
[7.4.0] Use Bazel 7.3.1 and flip `--incompatible_use_plus_in_repo_names`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23451]
Forked from #23450

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`.bazelversion`
`BUILD`
`MODULE.bazel`
`MODULE.bazel.lock`
`src/test/tools/bzlmod/MODULE.bazel.lock`
`src/tools/bzlmod/blazel_utils.bzl`
`src/tools/bzlmod/utils.bzl`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `.bazelversion` `BUILD` `MODULE.bazel` `MODULE.bazel.lock` `src/test/tools/bzlmod/MODULE.bazel.lock` `src/tools/bzlmod/blazel_utils.bzl` `src/tools/bzlmod/utils.bzl`
> 
> cc: @bazelbuild/triage

cc: @fmeum @Wyverald @meteorcloudy

**Comment by Wyverald** [comment]
see https://github.com/bazelbuild/bazel/pull/23475 -- I ended up sending a much smaller change
