### ISSUE TITLE
[7.4.0] Add support for in-memory outputs to output reuse

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23457]
Forked from #23422

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/actions/SpawnResult.java`
`src/main/java/com/google/devtools/build/lib/includescanning/SpawnIncludeScanner.java`
`src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java`
`src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnCacheTest.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/actions/SpawnResult.java` `src/main/java/com/google/devtools/build/lib/includescanning/SpawnIncludeScanner.java` `src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java` `src/test/java/com/google/devtools/build/lib/remote/RemoteSpawnCacheTest.java`
> 
> cc: @bazelbuild/triage

cc: @tjgq @fmeum

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23674
