### ISSUE TITLE
[7.4.0] Add back path mapping test deleted in conflict resolution

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23455]
Forked from #23393

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/test/java/com/google/devtools/build/lib/analysis/actions/StrippingPathMapperTest.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/test/java/com/google/devtools/build/lib/analysis/actions/StrippingPathMapperTest.java`
> 
> cc: @bazelbuild/triage

cc: @fmeum @tjgq @katre
