### ISSUE TITLE
zlib 1.2.10 (2 Jan 2017) released

### ISSUE THREAD

**Issue by John-xiao** [bazelbuild/bazel#2345]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### Environment info
* Operating System:

* Bazel version (output of `bazel info release`):

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by katre** [comment]
What specifically is this bug requesting? Feel free to re-open it with more details.

**Comment by John-xiao** [comment]
sorry. should add this to syntaxnet which still use zlib 1.2.8

**Comment by katre** [comment]
Syntaxnet is part of Tensorflow. Please create an issue on Tensorflow's repository about upgrading their libraries.
