### ISSUE TITLE
'unknown repo' error when using bzlmod, multiple modules and 'platforms' transitions

### ISSUE THREAD

**Issue by ljessendk** [bazelbuild/bazel#23456]
### Description of the bug:

In attempting to migrate a project that uses 'platforms' transitions for multiarch builds to bzlmod I've run into a strange issue that I believe is a bug.

My project works fine when using the old WORKSPACE approach, but after migrating to bzlmod I get the following error:
`
com.google.devtools.build.lib.packages.BuildFileNotFoundException: no such package '@@[unknown repo 'program' requested from @@core~]//': The repository '@@[unknown repo 'program' requested from @@core~]' could not be resolved: No repository visible as '@program' from repository '@@core~'
`
This message makes no sense to me as 'core' does not depend on 'program' ('program' is not mentioned anywhere in 'core'). The dependency is the other way around, 'program' depends on 'core'

I've only been able to reproduce the problem for scenarios where all of the below are true:
- bzlmod is enabled
- Module 'A' depends on module 'B'
- Module 'A' has a rule that uses a transition for transitioning 'platforms' command line argument and this rule depends on output produced by cc_binary()
- Module 'A' loads the functions for performing the transitions from module 'B'
- Module 'A' is the module being build

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

core/MODULE.bzl:
<pre>
module(
    name = "core"
)
</pre>

core/BUILD (file is empty)

core/transitions.bzl:
<pre>
def _platforms_transition_impl(settings, attr):
    _ignore = settings

    res = {
        "//command_line_option:platforms": attr.platforms,
    }

    return res

_platforms_transition = transition(
    implementation = _platforms_transition_impl,
    inputs = [
    ],
    outputs = [
        "//command_line_option:platforms",
    ],
)

def _symlink_transition_rule_impl(ctx):
    ctx.actions.symlink(output = ctx.outputs.output, target_file = ctx.file.target_file)
    return [
        DefaultInfo(
            files = depset(direct = [ctx.outputs.output]),
        ),
    ]

def _symlink_transition_rule_executable_impl(ctx):
    ctx.actions.symlink(output = ctx.outputs.output, target_file = ctx.file.target_file)
    default_info = ctx.attr.target_file[DefaultInfo]
    return [
        DefaultInfo(
            files = depset(direct = [ctx.outputs.output]),
            runfiles = default_info.default_runfiles.merge(ctx.runfiles([ctx.outputs.output])),
            executable = ctx.outputs.output,
        ),
    ]

def _attrs(cfg):
    return {
        "output": attr.output(mandatory = True),
        "target_file": attr.label(mandatory = True, allow_single_file = True, cfg = cfg),
    }

_platforms_symlink_transition_attrs = _attrs(_platforms_transition)
_platforms_symlink_transition_attrs.update({
    "platforms": attr.string(),
    "_allowlist_function_transition": attr.label(
        default = "@bazel_tools//tools/allowlists/function_transition_allowlist",
    ),
})

platforms_symlink_transition = rule(
    implementation = _symlink_transition_rule_impl,
    attrs = _platforms_symlink_transition_attrs,
    executable = False,
)
</pre>

program/MODULE.bzl:
<pre>
module(
    name = "program",
)

bazel_dep(name = "core")
local_path_override(
    module_name = "core",
    path = "../core",
)
</pre>

program/WORKSPACE:
<pre>
workspace(name = "program")

local_repository(
    name = "core",
    path = "../core",
)
</pre>

program/BUILD:
<pre>
load(":cc_binary.bzl", "cc_binary_platforms")

cc_binary_platforms(
    name = "hello_world",
    srcs = ["hello_world.cpp"],
    platforms = "@program//:dummy"
)

platform(
    name = "dummy",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",        
    ],
)
</pre>

program/cc_binary.bzl:
<pre>
load("@core//:transitions.bzl", "platforms_symlink_transition")

def cc_binary_platforms(name, platforms, visibility = None, tags = [], **kwargs):
    orig_name = name + ".orig"
    internal_rule_tags = tags + (["manual"] if "manual" not in tags else [])
    native.cc_binary(name = orig_name, tags = internal_rule_tags, **kwargs)
    platforms_symlink_transition(
        name = name + "_transition_rule",
        platforms = platforms,
        visibility = visibility,
        tags = tags,
        target_file = orig_name,
        output = name,
    )
</pre>

program/hello_world.cpp:
<pre>
#include <iostream>

int main() {
    std::cout << "Hello, World!" << std::endl;
    return 0;
}
</pre>

Steps to reproduce the issue:
cd program;bazel build --enable_bzlmod=true ...

However executing the following works fine:
cd program;bazel build --enable_bzlmod=false ...

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 7.3.0

**Comment by fmeum** [comment]
`platforms` has to be an `attr.label()` for this to work. It's currently a string, which means that `@program//:dummy` ends up being interpreted relative to `core/transitions.bzl`, which results in the error you are seeing.

Label strings should always be turned into `Label` objects when they may cross repo boundaries.

**Comment by ljessendk** [comment]
Thank you for the explanation @fmeum. I'm not sure I completely understand your proposed workaround, the transition implementation method needs to return a string so at some point the label has to be converted to a string, right? How can I do this?

I've tried changing the transitions.bzl file like this:
<pre>
...
def _platforms_transition_impl(settings, attr):
    print(attr.platforms)
    print(attr.platforms.repo_name)

    _ignore = settings

    res = {
        "//command_line_option:platforms": attr.platforms.name,
    }

    return res
....
...
_platforms_symlink_transition_attrs = _attrs(_platforms_transition)
_platforms_symlink_transition_attrs.update({
    "platforms": attr.label(),
    "_allowlist_function_transition": attr.label(
        default = "@bazel_tools//tools/allowlists/function_transition_allowlist",
    ),
})
....
</pre>

The output I get is this (both with and without bzlmod enabled):
<pre>
ERROR: /user/lsje/bazel/bug_module_transitions/program/BUILD:3:20: com.google.devtools.build.lib.packages.NoSuchTargetException: no such target '@@core~//:dummy': target 'dummy' not declared in package '' defined by /user/lsje/.cache/bazel/_bazel_lsje/74c1c771396f6fee43f4671863231c8d/external/core~/BUILD
DEBUG: /user/lsje/.cache/bazel/_bazel_lsje/74c1c771396f6fee43f4671863231c8d/external/core~/transitions.bzl:2:10: //:dummy
DEBUG: /user/lsje/.cache/bazel/_bazel_lsje/74c1c771396f6fee43f4671863231c8d/external/core~/transitions.bzl:3:10: 
</pre>

Can you provide me with some more hints or pointers on how to get my example to work with bzlmod?

**Comment by fmeum** [comment]
@ljessendk Even though that's confusing, keep in mind that `--platforms` has type `list[Label]`, not `Label`. This patch works for me:

```patch
diff --git a/core/transitions.bzl b/core/transitions.bzl
index 027da98..5629d26 100644
--- a/core/transitions.bzl
+++ b/core/transitions.bzl
@@ -2,7 +2,7 @@ def _platforms_transition_impl(settings, attr):
     _ignore = settings
 
     res = {
-        "//command_line_option:platforms": attr.platforms,
+        "//command_line_option:platforms": [attr.platforms],
     }
 
     return res
@@ -43,7 +43,7 @@ def _attrs(cfg):
 
 _platforms_symlink_transition_attrs = _attrs(_platforms_transition)
 _platforms_symlink_transition_attrs.update({
-    "platforms": attr.string(),
+    "platforms": attr.label(),
     "_allowlist_function_transition": attr.label(
         default = "@bazel_tools//tools/allowlists/function_transition_allowlist",
     ),
```

I would recommend to consider label strings as distinct types and take them in as `Label` whenever possible.

**Comment by ljessendk** [comment]
Yes, works now. Thanks!
