### ISSUE TITLE
build bazel on armv7l: failed: process-wrapper failed: error executing command 

### ISSUE THREAD

**Issue by nydal91** [bazelbuild/bazel#2346]
Hi! im trying to build bazel on armv7l device it has a Allwinner a3 with 512mb ram. But it fails all the time..
`$uname -a
Linux DietPi 3.4.113-sun8i #2 SMP PREEMPT Thu Nov 24 13:45:59 GMT 2016 armv7l GNU/Linux`

`$which gcc
/usr/bin/gcc`

`which java
/usr/bin/java`

error messages:
`🍃  Building Bazel with Bazel.
.WARNING: /tmp/bazel_3YI1wv9s/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel_3YI1wv9s/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.
INFO: Found 1 target...
ERROR: /root/tf/bazel-0.4.0/src/main/tools/BUILD:14:1: C++ compilation of rule '//src/main/tools:build-runfiles' failed: process-wrapper failed: error executing command 
  (cd /tmp/bazel_3YI1wv9s/out/bazel-sandbox/068ced50-92ab-4b04-bbd2-7ed005633ddb-0/execroot/bazel-0.4.0 && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /tmp/bazel_3YI1wv9s/out/execroot/bazel-0.4.0/_bin/process-wrapper -1 5 - - /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-canonical-system-headers -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/local-opt/bin/src/main/tools/_objs/build-runfiles/src/main/tools/build-runfiles.d '-frandom-seed=bazel-out/local-opt/bin/src/main/tools/_objs/build-runfiles/src/main/tools/build-runfiles.o' -iquote . -iquote bazel-out/local-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/local-opt/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c src/main/tools/build-runfiles.cc -o bazel-out/local-opt/bin/src/main/tools/_objs/build-runfiles/src/main/tools/build-runfiles.o).
Target //src:bazel failed to build`

**Comment by nydal91** [comment]
I get this error sometimes to...

`.WARNING: /tmp/bazel_TGijuHtB/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel_TGijuHtB/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.
INFO: Found 1 target...
ERROR: /root/tf/bazel-0.4.0/src/BUILD:56:1: Executing genrule //src:java-version failed: process-wrapper failed: error executing command 
  (cd /tmp/bazel_TGijuHtB/out/bazel-sandbox/4172c49f-d354-4fd8-a08a-24917c5ed3f5-0/execroot/bazel-0.4.0 && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /tmp/bazel_TGijuHtB/out/execroot/bazel-0.4.0/_bin/process-wrapper -1 5 - - /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; 
          VERSION_LINE=$(cat bazel-out/local-opt/bin/src/java_toolchain_content | grep target_version);
          JAVA_VERSION=$(echo ${VERSION_LINE} | sed '\''s/.*value=\"\([^\"]\)\".*/\1/'\'');
          if [ -z "${JAVA_VERSION}" ]; then
            echo "1.8" >bazel-out/local-opt/genfiles/src/java.version  # Java 8 is the default
          elif [[ "${JAVA_VERSION}" =~ ^[0-9]+$ ]]; then
            echo "1.${JAVA_VERSION}" >bazel-out/local-opt/genfiles/src/java.version  # Add 1. before 7 or 8
          else
            echo "${JAVA_VERSION}" >bazel-out/local-opt/genfiles/src/java.version
          fi
          ').
Target //src:bazel failed to build
INFO: Elapsed time: 33.103s, Critical Path: 0.67s

ERROR: Could not build Bazel
`

**Comment by katre** [comment]
What command are you using to build? This is showing the subcommands being run but I don't see the actual errors those subcommands are reporting, so it's hard to diagnose anything.

With each of them, are you able to successfully run the commands given yourself? For example, in the first you could actually change to the /tmp/bazel_3YI1wv9s/out/bazel-sandbox/068ced50-92ab-4b04-bbd2-7ed005633ddb-0/execroot/bazel-0.4.0 directory and try running the given gcc command to see what the result is.

Also, it appears you are building 0.4.0. Have you tried with the most recent release, 0.4.3?

**Comment by nydal91** [comment]
I'm following this guide https://www.neotitans.net/install-tensorflow-on-odroid-c2.html and changed to arm those how are aarch64. I have tried to build with bazel 0.4.3 but that will not start even
. I'm running in terminal like this:
`sudo ./compile.sh`


what you mean about change `/tmp/bazel_3YI1wv9s/out/bazel-sandbox/068ced50-92ab-4b04-bbd2-7ed005633ddb-0/execroot/bazel-0.4.0`

**Comment by katre** [comment]
We don't currently support ARM directly, although there are people on the mailing list who are trying to make that work.

What errors do you get when running ./compile.sh from version 0.4.3? Are you building from the released dist package, or from a git checkout? See https://bazel.build/versions/master/docs/install.html#compiling-from-source for the latest directions on setting up and building from source.

In the original error message you posted, Bazel is trying to cd to the directory "/tmp/bazel_3YI1wv9s/out/bazel-sandbox/068ced50-92ab-4b04-bbd2-7ed005633ddb-0/execroot/bazel-0.4.0" and then run gcc inside process-wrapper. Are you able to run that gcc command from that directory yourself?

**Comment by nydal91** [comment]
this happen https://github.com/bazelbuild/bazel/issues/2140 when I try to build with bazel 4.3

**Comment by nydal91** [comment]
i gonne test out the cd to the directory

**Comment by katre** [comment]
Right, as that bug says, you need to run compile.sh from the dist archive, which you can find at the link I gave you.

**Comment by nydal91** [comment]
Trying to build with bazel 4.3 get this error:

`  🍃  Building Bazel with Bazel.
.WARNING: /tmp/bazel_tjQzdSGu/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel_tjQzdSGu/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.
INFO: Found 1 target...
ERROR: /root/tf/third_party/protobuf/3.0.0/BUILD:311:1: Creating runfiles tree bazel-out/host/bin/third_party/protobuf/3.0.0/protoc.runfiles [for host] failed: build-runfiles failed: error executing command
  (cd /tmp/bazel_tjQzdSGu/out/execroot/tf && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /tmp/bazel_tjQzdSGu/out/execroot/tf/_bin/build-runfiles bazel-out/host/bin/third_party/protobuf/3.0.0/protoc.runfiles_manifest bazel-out/host/bin/third_party/protobuf/3.0.0/protoc.runfiles): java.io.IOException: Cannot run program "/tmp/bazel_tjQzdSGu/out/execroot/tf/_bin/process-wrapper" (in directory "/tmp/bazel_tjQzdSGu/out/execroot/tf"): error=13, Permission denied.
Target //src:bazel failed to build
INFO: Elapsed time: 35.648s, Critical Path: 0.59s

ERROR: Could not build Bazel`


Have put this in  tools/cpp/cc_configure.bzl:

`result = repository_ctx.execute(["uname", "-m"])  
machine = result.stdout.strip()
  if machine in ["arm", "armv7l"]:
    return "arm"
  elif machine in ["amd64", "x86_64", "x64"]:
    return "k8"
  return "piii"`

**Comment by mhlopko** [comment]
So just to be sure I understand things correctly. You now have bazel 0.4.3 on your machine installed and working. With this bazel, you're trying to compile bazel from the github HEAD, with your changes needed to support arm. And you see the 'Permission denied' error message. Correct?

Can you check that process-wrapper is there and has +x permission?

**Comment by nydal91** [comment]
I have not install bazel 0.4.3 im trying to build it to work with arm machine from the arm machine.

**Comment by nydal91** [comment]
`chmod +x /tmp/bazel_tjQzdSGu/out/execroot/tf/_bin/process-wrapper` like that?

**Comment by mhlopko** [comment]
Just inspect if the file is there and that it has the flag.

**Comment by mhlopko** [comment]
Will close as it's probably obsolete. Feel free to comment and I'll reopen.
