### ISSUE TITLE
Performance issues on macos-14-arm with bazel prereleases

### ISSUE THREAD

**Issue by criemen** [bazelbuild/bazel#23468]
### Description of the bug:

I tried to pull in a 7.4.0 prerelease into our CI, as there's some features in it, and I didn't want to wait for an official release.
With bazelisk that's as easy as dropping a SHA into `.bazelversion`.

However, we're observing an approximately 2x slowdown on macos-14-arm if we do that.
In order to pin down the problem, I even used the SHA https://github.com/bazelbuild/bazel/commit/5caacf1130c95d93adf79cd947c307441c14504e of the 7.3.1 release, but that's ca. 2x slower than using 7.3.1 in bazelisk.

I'm mystified by this. For all measurements, I ran `bazel clean --expunge` on the new server to make sure there wasn't any leftover cache.
Disabling the sandbox didn't help either.
We're not observing this behavior on Ubuntu 22.04 or Windows Server 2022.

Are there some different compilation options used for release builds vs. pre-releases? Any way we can help debugging this further?
I clicked through a profile of the same build, and it just seems that everything takes longer, but it's quite hard to correlate individual actions the chrome profile UI.

**Comment by fmeum** [comment]
@meteorcloudy

**Comment by meteorcloudy** [comment]
Here is how the per commit binary was built:
https://github.com/bazelbuild/bazel/blob/c412b27a4fcb7a7736d8e214f2feace6b1274532/.bazelci/build_bazel_binaries.yml#L41-L47

Here is how the final release binary was built:
https://github.com/bazelbuild/continuous-integration/blob/master/pipelines/bazel-release.yml#L208-L221

Both are built with `-c opt`, and the only difference is the release binary was built with Bazel@HEAD. I'm not sure if that's the reason.

Let me see if I can reproduce on my apple silicon Mac.

**Comment by meteorcloudy** [comment]
Hmm, I'm not seeing such difference on my arm64 Mac when building `//src/main/cpp:client` in Bazel:
```
Bazel 7.3.1:

INFO: From Linking src/main/cpp/client:
ld: warning: ignoring duplicate libraries: '-lm', '-lpthread'
INFO: Found 1 target...
Target //src/main/cpp:client up-to-date:
  bazel-bin/src/main/cpp/client
INFO: Elapsed time: 79.639s, Critical Path: 8.62s
INFO: 1991 processes: 678 internal, 1313 darwin-sandbox.
INFO: Build completed successfully, 1991 total actions


5caacf1130c95d93adf79cd947c307441c14504e:

INFO: From Linking src/main/cpp/client:
ld: warning: ignoring duplicate libraries: '-lm', '-lpthread'
INFO: Found 1 target...
Target //src/main/cpp:client up-to-date:
  bazel-bin/src/main/cpp/client
INFO: Elapsed time: 82.173s, Critical Path: 8.45s
INFO: 1991 processes: 678 internal, 1313 darwin-sandbox.
INFO: Build completed successfully, 1991 total actions
```

Can you provide an example repo to reproduce this?

**Comment by criemen** [comment]
Turns out we were using bazelisk 1.11.0 (which is quite old), which works fine for released bazel versions, but on prereleases (presumably, I've not checked) forces the builds to x86 - or does something else funky that just slows _everything_ down.

Using bazelisk 1.20.0. does not reproduce this slowdown.

**Comment by meteorcloudy** [comment]
Ah, that explains, thanks for figuring it out.
