### ISSUE TITLE
Check for git repo in skylark rule in git.bzl doesn't work if bazel output_user_root is inside a git repo.

### ISSUE THREAD

**Issue by sethkoehler** [bazelbuild/bazel#2347]
I noticed (what I think is) an issue in the Skylark git.bzl rules that I figured I'd pass along...it may not come up much, but it bit me yesterday :)

### STEPS TO REPRODUCE ###

[outer_git_repo.tar.gz](https://github.com/bazelbuild/bazel/files/690747/outer_git_repo.tar.gz)

1. Extract the contents of the attached "outer_git_repo.tar.gz" example.
1. cd outer_git_repo
1. ./fetch.sh  (which just runs "git init", then goes into the hello folder and runs bazel clean and fetch using "--output_user_root ../_bazel_cache")

You should see the following error message (I've heavily truncated it):

```
java.lang.IllegalArgumentException: <ErrorInfo exception=com.google.devtools.build.lib.skyframe.PackageFunction$PackageFunctionException: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Encountered error while reading extension file 'go/def.bzl': no such package '@io_bazel_rules_go//go': Traceback (most recent call last):
...
		+ git reset --hard 6777d3455ad97e293e90d690d5fd9ba54be9ab55
		fatal: Could not parse object '6777d3455ad97e293e90d690d5fd9ba54be9ab55'.
		+ git fetch
		+ git reset --hard 6777d3455ad97e293e90d690d5fd9ba54be9ab55
		fatal: Could not parse object '6777d3455ad97e293e90d690d5fd9ba54be9ab55'.
```

### ISSUE ###

The full error message points at the right spot for the issue (let me know if you don't see it).  It's in the middle of trying to fetch the contents of https://github.com/bazelbuild/rules_go, and has a check in git.bzl:28 (in _clone_or_update) that seems to use "git rev-parse --git-dir" to determine if it's already fetched the repo in bazel's cache.  

The problem is that due to the output_user_root directive, the bazel cache is *inside* the outer_git_repo (which I just made with a git init command, nothing special), and thus this check detects the outer repo, thinks the go rules dependency has been cloned, and proceeds to try to get the specific commit hash listed at the end of the error message above, which naturally fails since the dependency repo hasn't actually been cloned.  Is there a way to tighten this check to make sure the dependency in question actually has been cloned?  I would have thought a check for the .git folder in the directory specifically, rather than relying on git rev-parse, which looks at parent folders, would be sufficient, but I'm quite far from a git expert.

Moving the bazel cache outside any git repo naturally fixes the issue (which is why you won't notice it without --output_user_root, I guess unless you git inited the default bazel output folder :) ).  I also don't believe the go rules have anything to do with it based on the code I saw (it's just a dependency that needs fetching).

Note that I searched for things like "bazel output user root inside git repo" and "_clone_or_update" in the issues here as well as in the bazel-discuss groups and didn't see anything relevant.

### ENV INFO ###

* Operating System: Ubuntu 14.04
* Bazel version (output of `bazel info release`): release 0.4.3

**Comment by katre** [comment]
@kchodorow, I think this is an error using output_user_root, but I'm assigning to you because you understand that better than I do.

**Comment by meisterT** [comment]
Is this still an issue?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
