### ISSUE TITLE
[Mirror] ninja v1.12.1

### ISSUE THREAD

**Issue by jmillikin** [bazelbuild/bazel#23486]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/ninja-build/ninja/archive/refs/tags/v1.12.1.tar.gz

**Comment by satyanandak** [comment]
Here you go
https://mirror.bazel.build/github.com/ninja-build/ninja/archive/refs/tags/v1.12.1.tar.gz

**Comment by jmillikin** [comment]
Thank you!
