### ISSUE TITLE
[bazel.build] Problem with /tutorials/ccp-toolchain-config

### ISSUE THREAD

**Issue by estoces** [bazelbuild/bazel#23482]
### Page link:

https://bazel.build/tutorials/ccp-toolchain-config

### Problem description (include actual vs expected text, if applicable):

There is no repo to work from.  The "Setup the Build Environment" section should have clone statement for example project.

### Where do you see this issue? (include link to specific section of the page, if applicable)

https://bazel.build/tutorials/ccp-toolchain-config#setup-build-environment

**Comment by Wyverald** [comment]
The example is already _very_ minimal -- it consists of all of 3 files: an empty file named MODULE.bazel, a BUILD file whose contents (4 lines) you can copy from the code block, and a C++ source file with arbitrary contents (presumably `int main(){}` would suffice). So I don't think this is really a problem.
