### ISSUE TITLE
Remote Downloader should support using custom credentials

### ISSUE THREAD

**Issue by sluongng** [bazelbuild/bazel#23499]
### Description of the feature request:

Currently, the HttpDownloader does support credentials from netrc or a custom credential helper.

However, the GrpcRemoteDownloader backed by Remote Asset API simply ignores the credentials https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/remote/downloader/GrpcRemoteDownloader.java;l=167;drc=0a0d877a6960db1f4054f9b6ac09b6c91c311548;bpv=0;bpt=1 which make it not possible to use `remote_downloader` against a URL that requires authentications.

Given that the credentials might be based on URL, we may want to extend the current `QUALIFIER_HTTP_HEADER_PREFIX` to also support different URLs, perhaps based on the order of the URLs added to the grpc request.,

### Which category does this issue belong to?

Remote Execution

**Comment by sluongng** [comment]
cc: @r2r-dev

**Comment by jmillikin** [comment]
Normally your remote downloader implementation would contain logic for loading appropriate credentials. For example, if you're using it to redirect download requests to an internal caching proxy then that proxy should be configured with `netrc` (or equivalent).

**Comment by sluongng** [comment]
@jmillikin It's one way to set it up. However, in some settings where the remote downloader is shared between different isolated + diverse tenants, it might be desirable to forward the credentials from the client side (Bazel side) instead of keeping the credentials in one centralized location. This way, tenant `foo` could be using a different set of credentials headers from tenant `bar`.
