### ISSUE TITLE
TMP: Cannot create temp files in Java binaries in actions

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#2349]
For one reason or other, `File#createTempFile()` tries to create the file in `C:\WINDOWS`, which of course fails with an access denied error.

This choice of default behavior in Java is questionable and it probably works because the `TEMP` environment variable is usually set. Except in Bazel actions.

**Comment by dslomov** [comment]
GetTempPath on WIndows looks at:

1. The path specified by the TMP environment variable.
2. The path specified by the TEMP environment variable.
3. The path specified by the USERPROFILE environment variable.
4. The Windows directory.

https://msdn.microsoft.com/en-us/library/windows/desktop/aa364992(v=vs.85).aspx

Looks like we need to provide one of those to actions

**Comment by laszlocsomor** [comment]
Closing because actions now always have a temp directory.
