### ISSUE TITLE
request support ar not libtool on macosx

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/bazel#23498]
### Description of the feature request:

because libtool has command line length problem, some repo cannot handle this well, like(current openssl),requst use ar on macosx

### Which category does this issue belong to?

C++ Rules

### Which operating system are you running Bazel on?

macosx Darwin Kernel Version 22.6.0

### What is the output of `bazel info release`?

7.2.0

**Comment by dzbarsky** [comment]
Can you try to build with '--features=-libtool'?

**Comment by xiedeacc** [comment]
> Can you try to build with '--features=-libtool'?

not working, always trigger libtool
![image](https://github.com/user-attachments/assets/05eedfde-734f-4cbb-b1ef-ea1567d3e643)
