### ISSUE TITLE
Fix an NPE with the SkymeldUiStateTracker.

### ISSUE THREAD

**Issue by joeleba** [bazelbuild/bazel#23493]
### Commit IDs

4972db8a5211c2efd7af3a3b77f24f7698e4bdfe

### Category

team-Performance

### Reviewers

@iancha1992

**Comment by bazel-io** [comment]
Failed commits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/4972db8a5211c2efd7af3a3b77f24f7698e4bdfe.
Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23495
