### ISSUE TITLE
Documentation issue: Bzlmod user guide

### ISSUE THREAD

**Issue by estoces** [bazelbuild/bazel#23501]
Documentation URL: https://docs.bazel.build/versions/5.1.0/bzlmod.html

Broken link in External links.

[Bazel External Dependencies Overhaul](https://docs.google.com/document/d/1moQfNcEIttsk6vYanNKIy3ZuK53hQUFq1b1r0rmsYVg/edit) (original Bzlmod design doc)

**Comment by Wyverald** [comment]
The link works for me, on two different machines and different browsers. Please check your internet connection.
