### ISSUE TITLE
[7.4.0] Wire up `internal-inline-outputs` requirement with RE API 

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23511]
Forked from #23428

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/remote/GrpcCacheClient.java` `src/main/java/com/google/devtools/build/lib/remote/RemoteCache.java` `src/main/java/com/google/devtools/build/lib/remote/common/RemoteCacheClient.java` `src/main/java/com/google/devtools/build/lib/remote/http/HttpCacheClient.java` `src/test/java/com/google/devtools/build/lib/remote/GrpcCacheClientTest.java` `src/test/java/com/google/devtools/build/lib/remote/RemoteCacheTest.java` `src/test/java/com/google/devtools/build/lib/remote/RemoteRepositoryRemoteExecutorTest.java` `src/test/java/com/google/devtools/build/lib/remote/http/HttpCacheClientTest.java` `src/test/java/com/google/devtools/build/lib/remote/util/InMemoryCacheClient.java` `src/test/shell/bazel/remote/remote_execution_test.sh` `src/tools/remote/src/main/java/com/google/devtools/build/remote/worker/ActionCacheServer.java`
> 
> cc: @bazelbuild/triage

@tjgq @fmeum @lawchingman

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23714
