### ISSUE TITLE
[Mirror] javacc 7.0.13 and javaparser 3.26.2

### ISSUE THREAD

**Issue by jmillikin** [bazelbuild/bazel#23517]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/javacc/javacc/archive/refs/tags/javacc-7.0.13.tar.gz
https://github.com/javaparser/javaparser/archive/refs/tags/javaparser-parent-3.26.2.tar.gz

**Comment by satyanandak** [comment]
Here you go
https://mirror.bazel.build/github.com/javacc/javacc/archive/refs/tags/javacc-7.0.13.tar.gz
https://mirror.bazel.build/github.com/javaparser/javaparser/archive/refs/tags/javaparser-parent-3.26.2.tar.gz

**Comment by jmillikin** [comment]
Thank you!
