### ISSUE TITLE
[7.4.0] Invalidate lockfile entry when the extension name prefix changes

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23529]
Forked from #23527

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/test/py/bazel/bzlmod/bazel_lockfile_test.py`
`src/test/tools/bzlmod/MODULE.bazel.lock`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23564
