### ISSUE TITLE
[Mirror] rules_go 0.50.1

### ISSUE THREAD

**Issue by hawkingrei** [bazelbuild/bazel#23531]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/rules_go/releases/download/v0.50.1/rules_go-v0.50.1.zip

**Comment by satyanandak** [comment]
Here you go
https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.50.1/rules_go-v0.50.1.zip
