### ISSUE TITLE
[Mirror] rules go 0.50 and 0.50.1

### ISSUE THREAD

**Issue by tyler-french** [bazelbuild/bazel#23539]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/rules_go/releases/download/v0.50.1/rules_go-v0.50.1.zip
https://github.com/bazelbuild/rules_go/releases/download/v0.50.0/rules_go-v0.50.0.zip

**Comment by satyanandak** [comment]
Here you go
https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.50.1/rules_go-v0.50.1.zip
https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.50.0/rules_go-v0.50.0.zip
