### ISSUE TITLE
[7.4.0] Undeclared outputs not uploaded to BES when --nozip_undeclared_test_outputs is set

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23542]
Forked from #17911

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/analysis/test/TestRunnerAction.java`

cc: @bazelbuild/triage

**Comment by tjgq** [comment]
Requires  ddc8a74b5916ac03e to be cherry-picked first, but even that one has a lot of merge conflicts due to divergence between 7.x and 8.x. At this time I'm not convinced it's worth the effort.
