### ISSUE TITLE
bazel test with opening a file in /var/tmp

### ISSUE THREAD

**Issue by KarimH22** [bazelbuild/bazel#23549]
### Description of the bug:

Running a test in which a file is opened in /var/tmp, `bazel test` command **failed** but `bazel run` **passed**

### Which category does this issue belong to?

Local Execution

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Clone the repository 
https://github.com/KarimH22/bazel_var_issue/tree/main
and run
`bazel test test1`

### Which operating system are you running Bazel on?

Linux debian/ubuntu

### What is the output of `bazel info release`?

release 6.2.1 

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

I tried also within bazel 
**release 7.0.1**

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
https://github.com/KarimH22/bazel_var_issue.git
b1bb6a0720afaa22d70f5b0380ec9997b2480815
```

### Have you found anything relevant by searching the web?

Nothing related to this issue among thoses 3 links

**Comment by tjgq** [comment]
`bazel test` runs the test in a sandboxed environment where `/var/tmp` isn't visible (see https://bazel.build/docs/sandboxing) to ensure hermeticity (see https://bazel.build/basics/hermeticity). `bazel run` doesn't.

If your test is intentionally non-hermetic with respect to `/var/tmp`, you can use `--test_strategy=standalone` to disable sandboxing entirely, or `--sandbox_add_mount_pair=/var/tmp` (Linux only) to make the host's `/var/tmp` visible in the sandbox.

**Comment by KarimH22** [comment]
Hello

> bazel test --sandbox_add_mount_pair=/var/tmp   test1

does'nt pass too 

same still failed with --test_strategy=standalone

**Comment by tjgq** [comment]
Sorry, try `--spawn_strategy=standalone` (it appears that `--test_strategy=standalone` doesn't work: https://github.com/bazelbuild/bazel/issues/5347)

For the other option, if you're writing files and not just reading them, you need to set `--sandbox_writable_path=/var/tmp` in addition to `--sandbox_add_mount_pair=/var/tmp`.

**Comment by KarimH22** [comment]
Yes it works with these options 
thank you!

**Comment by KarimH22** [comment]
in cc_test rule how can i add this strategy __--spawn_strategy=standalone__ please ?

**Comment by tjgq** [comment]
The command line flag affects the entire build. If you only want to disable sandboxing for a single test, add a `no-sandbox` tag:

```
cc_test(
  ...,
  tags = ["no-sandbox"],
)
```
