### ISSUE TITLE
bazel_sandbox_test wgets a tarball from a random storage bucket

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#2355]
See https://github.com/bazelbuild/bazel/commit/18e6b410a7f4e24b67740978d101cd665edea6cc#diff-a98105816a54206dd065943b75341ea2R487.

Please change this test to use Bazel's mechanism for external dependencies (add it to the WORKSPACE file, declare a dependency on it).

**Comment by xingao267** [comment]
Hi Kristina,

I did not use Bazel workspace rule because I would like to modify the CROSSTOOL file after I download (wget) the tarball and I thought Bazel workspace rule cannot achieve that. Is it possible to make modification to external repo after Bazel retrieves it?

Thanks,
Xin

**Comment by kchodorow** [comment]
This isn't an immediate problem (I found a workaround for the issue this was causing me) but yes.  You could use an http_file() rule to download the .tar.gz and then depend on the .tar.gz in your test and do exactly what you're doing, except extract it from $TEST_SRCDIR instead of where wget was putting it.

**Comment by xingao267** [comment]
Thanks! I'll fix that.

Xin

**Comment by philwo** [comment]
@xingao267 Friendly ping :)
