### ISSUE TITLE
[7.4.0] Cherrypick 384e381fa841537987691f170ed9408dcfeed2ea into 7.4.0

### ISSUE THREAD

**Issue by ahumesky** [bazelbuild/bazel#23557]
### Commit IDs

384e381fa841537987691f170ed9408dcfeed2ea

### Category

team-Android

### Reviewers

@comius

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/23558: https://github.com/bazelbuild/bazel/commit/384e381fa841537987691f170ed9408dcfeed2ea.
