### ISSUE TITLE
bazel.build website not rendered correctly. app.css code 503

### ISSUE THREAD

**Issue by apivovarov** [bazelbuild/bazel#23567]
### Page link:

bazel.build

### Problem description (include actual vs expected text, if applicable):

bazel.build website not rendered correctly . app.css code 503

### Where do you see this issue? (include link to specific section of the page, if applicable)

bazel.build website not rendered correctly . app.css code 503

### Any other information you'd like to share?

bazel.build website not rendered correctly . app.css code 503

**Comment by iancha1992** [comment]
https://bazel.build/ is working @apivovarov
