### ISSUE TITLE
CROSSTOOL bug on OSX for armeabi-v7a

### ISSUE THREAD

**Issue by Helcaraxan** [bazelbuild/bazel#2357]
### Description of the problem

When doing a cross-compile without a custom toolchain for arm on OSX Sierra compiling fails because the `/bin/false` executable, referenced in the `armeabi-v7a` toolchain definition [here](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/CROSSTOOL#L70) and in the lines below, has moved to `/usr/bin/false`.

Usually I would solve this, at least temporarily, with a symlink. However on the latest releases of OSX the `/bin` and `/usr/bin` folders have been locked down to prevent editing (even for `root`). This can only be circumvented by rebooting in "Recovery mode"... and that's not something I'm going to do on all our agents used in CI.

~Result: this is a **big** blocker for me at the moment and I don't have much in the form of a viable alternative or equivalent contingency plan.~
Edit: I was of course not defining my own toolchain so that part is at least understood and being solved now. But the bug still exists although its less of an immediate problem.

### Environment info
* Operating System: OSX Sierra (also verified on El Capitan)
* Bazel version: 0.4.3

###  Relevant link(s)

SO link about the "Recovery mode" and "rootless" folder lock down:
http://apple.stackexchange.com/questions/196224/unix-ln-s-command-not-permitted-in-osx-el-capitan-beta3

**Comment by Helcaraxan** [comment]
Just to make it clear after I edited the post above: this is not a blocker for me... Part of the solution was me learning better how CROSSTOOL & co works and what needs to be done to get cross-compiling working.

That said, the paths are wrong on OSX starting with El Capitan (or earlier but have not tested).

**Comment by kshyanashree** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
