### ISSUE TITLE
[7.4.0] cc_shared_library ignores linkopts from header only cc_library deps

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23588]
Forked from #21884

**Comment by Wyverald** [comment]
no fix available yet, closing.

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test/BUILD.builtin_test`
`src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test/starlark_tests.bzl`

cc: @bazelbuild/triage
