### ISSUE TITLE
need a way to affect the default timeout of repository_ctx.execute()

### ISSUE THREAD

**Issue by dws** [bazelbuild/bazel#23586]
### Description of the feature request:

It would be helpful if there were a way to affect the default timeout of `repository_ctx.execute()` without needing to patch Bazel itself.  While `repository_ctx.execute()` does accept a `timeout` parameter, the `git_repository()` and `http_archive()` rules provided with Bazel currently provide no way to specify an alternate timeout.  Even if they did, it could be quite cumbersome to provide a new parameter to all the calls to these rules in a given repo.  So, it would be helpful to have a way to adjust the default value, perhaps via a command line argument to Bazel.

If this is acceptable, then I'll be happy to provide a patch.

### Which category does this issue belong to?

Core

### What underlying problem are you trying to solve with this feature?

In order to cope with slow infrastructure, we need to be able to boost the timeout of _all_ uses of `repository_ctx.execute()`.

### Which operating system are you running Bazel on?

Ubuntu 20.04 LTS

### What is the output of `bazel info release`?

release 7.2.1

### Have you found anything relevant by searching the web?

No

**Comment by Wyverald** [comment]
You can use `--experimental_scale_timeouts` for this exact use case, I believe.
