### ISSUE TITLE
Please improve the documentation for protobuf support

### ISSUE THREAD

**Issue by mzhaom** [bazelbuild/bazel#2359]
- Please enhance the documentation on
https://bazel.build/versions/master/docs/be/protocol-buffer.html to
cover proto_library rule
- Please include some document describing how the workspace should be prepared, like
where the protobuf source should be put or prebuilt binary should be put
- Potentially please talk about how to work with grpc, or if some other feature is not supported
maybe put a road map and known limitation somewhere.

Thanks!

**Comment by cgrushko** [comment]
I posted 
https://bazel.build/blog/index.html#protocol-buffers-in-bazel

I also plan to update the docs in http://be.bazel.build .

**Comment by drigz** [comment]
The blog link is broken. I think it should point here: https://blog.bazel.build/2017/02/27/protocol-buffers.html

Additionally, the WORKSPACE rules in the blog post don't work for me. I need to add this line:

`strip_prefix = "protobuf-b4b0e304be5a68de3d0ee1af9b286f958750f5e4",`

or I get the error: `no such package '@com_google_protobuf//': BUILD file not found on package path`. The blog post also doesn't have an entry for `@com_google_protobuf_javalite`, so `java_lite_proto_library` doesn't work.

Is there a plan to document this somewhere other than a blog post? I would expect the docs for `*proto_library` to link to a document explaining the required rules in WORKSPACE. Currently the user journey is something like:
1. Read docs
1. Write rule
1. Try to build, get `no such package '@com_google_protobuf//': The repository could not be resolved`
1. Google the error message, find the blog post
1. Add the WORKSPACE rules
1. Try to build (currently requires fixing the WORKSPACE rules as described above)

**Comment by cgrushko** [comment]
Agreed. I'll put it on my queue.

**Comment by aiuto** [comment]
Closing as outdated - twice. The docs did get updated.
https://docs.bazel.build/versions/master/be/protocol-buffer.html#proto_library
And that page, in turn, now points to [rules_proto](https://github.com/bazelbuild/rules_proto)
