### ISSUE TITLE
[7.4.0] Apply `single_version_override` patches to module files

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23605]
Forked from #23536

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BUILD`
`src/main/java/com/google/devtools/build/lib/bazel/repository/PatchUtil.java`
`src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunctionTest.java`
`third_party/upb/BUILD`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BUILD` `src/main/java/com/google/devtools/build/lib/bazel/repository/PatchUtil.java` `src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunctionTest.java` `third_party/upb/BUILD`
> 
> cc: @bazelbuild/triage

cc: @fmeum @Wyverald @meteorcloudy

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23757
