### ISSUE TITLE
[7.4.0] Allow unquoted canonical repository names with `query`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23601]
Forked from #23600

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/query2/engine/Lexer.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/query2/engine/Lexer.java`
> 
> cc: @bazelbuild/triage

cc: @fmeum @Wyverald
