### ISSUE TITLE
Add an option to `container_push` rule that allows for pretty-print format of Docker image manifest

### ISSUE THREAD

**Issue by yawangwang** [bazelbuild/bazel#23613]
### Description of the feature request:

The Bazel `container_push` rule currently uses `json.Marshal` (see https://github.com/bazelbuild/rules_docker/blob/master/container/go/pkg/compat/image.go#L182) to format the image manifest before pushing it to an OCI repository, whereas the native Docker docker push command uses json.MarshalIndent to pretty-print the manifest. This discrepancy can lead to different image digests for the same manifest content when using different tools.

We are requesting a feature to add support for pretty-printing the Docker image manifest in the Bazel `container_push` rule to be compatible with Docker commands.

### Which category does this issue belong to?

Configurability

**Comment by srdo** [comment]
`rules_docker` is deprecated and no more work is going into it. You probably want `rules_oci` instead.

https://github.com/bazel-contrib/rules_oci

**Comment by gregestren** [comment]
Unless I'm missing something this should be a bug for the repo owning the rules. i.e https://github.com/bazel-contrib/rules_oci as suggested above.
