### ISSUE TITLE
[Bazel CI] Downstream project broken by rules_java upgrade

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#23619]
- rules_android: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4122#0191e992-eae4-42e8-9a83-2c25041a8537
- rules_android_ndk: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4122#0191e992-ef33-4327-b223-c143ed2eb0e9
- rules_testing: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4122#0191e992-f0c9-4795-9cad-20f0c60aa06e

```
(04:10:49) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/67c259e1fb9766950734b85418b03ced/external/rules_java_builtin/toolchains/BUILD:285:14: While resolving toolchains for target @@rules_java_builtin//toolchains:platformclasspath (4f6c53c): No matching toolchains found for types @@rules_java_builtin//toolchains:bootstrap_runtime_toolchain_type.
To debug, rerun with --toolchain_resolution_debug='@@rules_java_builtin//toolchains:bootstrap_runtime_toolchain_type'
```

Bisect points to https://github.com/bazelbuild/bazel/commit/f92124acf3d0eb99d06570ddc380aca7ab354b90

**Comment by meteorcloudy** [comment]
@hvadehra Looks like https://github.com/bazelbuild/bazel/pull/23571 is getting cherry-picked back to 7.4, you probably want to fix this one to make sure the upgrade is backwards compatible?

**Comment by hvadehra** [comment]
Looks like the failures are only when using WORKSPACE, and not with bzlmod. So presumably they're picking up an older version of `rules_java`?

**Comment by hvadehra** [comment]
I'v gone through the latest (https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/) failures and sent out fixes for the ones that look related to `@rules_java`. Hopefully things will look better once the're in.

**Comment by hvadehra** [comment]
Status update, looking at the latest nightly run (https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4308):

 - rules_testing : fixed
 - Google branch of Android Studio / Intellij / others  : unrelated compilation failures remain: `(04:09:37) ERROR: /var/lib/buildkite-agent/builds/bk-docker-n6v9/bazel-org-repo-root/intellij/proto/BUILD:88:14 Building proto/libartifact_tracker_data_proto-speed.jar (1 source jar) failed: (Exit 1): gcc failed: error executing CppCompile command (from target @@com_google_absl//absl/hash:hash)`

Only thing remaining is:
 - Main branch of Intellij / others: broken with the bzlmod + workspace hybrid mode issue
