### ISSUE TITLE
[7.4.0] Update rules_java 7.11.1 / java_tools 13.8

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23612]
Forked from #23571

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`MODULE.bazel`
`MODULE.bazel.lock`
`src/MODULE.tools`
`src/test/shell/bazel/bazel_bootstrap_distfile_test.sh`
`src/test/tools/bzlmod/MODULE.bazel.lock`
`workspace_deps.bzl`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `MODULE.bazel` `MODULE.bazel.lock` `src/MODULE.tools` `src/test/shell/bazel/bazel_bootstrap_distfile_test.sh` `src/test/tools/bzlmod/MODULE.bazel.lock` `workspace_deps.bzl`
> 
> cc: @bazelbuild/triage

@hvadehra @fmeum I cannot cherry-pick this due to many conflicts in `src/test/shell/bazel/bazel_bootstrap_distfile_test.sh`. Can you please take a look? Thanks

**Comment by iancha1992** [comment]
Wait till https://github.com/bazelbuild/bazel/issues/23619 and https://github.com/bazelbuild/bazel/pull/23571#issuecomment-2346958723 are resolved

**Comment by hvadehra** [comment]
Either would be fine I think.

**Comment by iancha1992** [comment]
Ok, then lets go with https://github.com/bazelbuild/bazel/pull/23811 since it's newer. Thanks. @hvadehra
