### ISSUE TITLE
Allow dynamic/query-based dependencies

### ISSUE THREAD

**Issue by shahms** [bazelbuild/bazel#2362]
Background:
  A number of tools use [`compile_commands.json`](http://clang.llvm.org/docs/JSONCompilationDatabase.html) to determine the necessary flags, etc for interpreting C++ source files.  Unfortunately, this file is an aggregate of all C++ source files in the repository and most tools don't support much more granularity than that (at least, not that I've found and it's often not well documented).

This highlights a bit of a deficiency in bazel: each target needs a (mostly) static list of dependencies. This makes targets which need to aggregate (for example) all of the C++ source files in a project either incredibly fragile and manual or dependent on being run as external scripts.

It would be great if there was a way for rules to have dependencies which were specified by a query, rather than just static target, e.g.
```
genrule(
  name = "compile_commands_json",
  deps = query("kind(cc_.*, @//...)"),
  out = "compile_commands.json",
  ...
)
```

**Comment by vladmos** [comment]
@ulfjack can we do this?

**Comment by ulfjack** [comment]
The short answer is no.

We don't currently have an incremental query 'engine', so we couldn't do incremental recomputation / invalidation of such a rule; rerunning such a query on every build would be counter to our performance targets. We looked into that, but it's not straightforward.

In addition, there's a dependency cycle here - in the example, the results of the query affect the structure of the BUILD file, which in turn can be an input to the query, and then affect query results. This argument doesn't apply for mechanisms simpler than query, e.g., plain target patterns, although the restriction would still be that it can't be used by BUILD macros.

Lastly, the example is clearly problematic. Having - in a BUILD file - a construct that can depend on all BUILD files in a tree is not going to scale to larger repositories, i.e., say, ~hundreds of BUILD files, not to mention those that contain _hundreds of thousands_ of BUILD files.

That said, we internally have a Bazel feature called print_action, which prints the right action for a specific source file, and we've successfully integrated that with tools, well, at least with some tools (like https://github.com/Valloric/YouCompleteMe). There've been requests for open sourcing that, but it hasn't happened yet.

**Comment by shahms** [comment]
Fair enough; thanks for addressing it!

FWIW, I wouldn't expect cyclical queries to work (just like cyclical dependencies don't work now).  I would expect that if the query would include the rule itself, such a rule would be invalid.  I can definitely sympathize with the scalability issues.

**Comment by ulfjack** [comment]
The computation of the query you posted "kind(cc_.*, @//...)" requires looking at all the rules, even if they are then filtered by the kind() filter. You're right, in this specific case we could probably make it work, but it's still worrying, and - as a generic mechanism - it's something that would need to be carefully considered in the design.

**Comment by rulatir** [comment]
Solution: abandon bazel. Dynamic dependencies are a reality, and build systems that find excuses not to natively support them are stuck in a correctness utopia.
