### ISSUE TITLE
[7.4.0] Conditionally set output_paths based on Remote Executor capabilities

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23629]
Forked from #18270

**Comment by iancha1992** [comment]
@sluongng @coeuvre @tjgq @fmeum I am not able to cherry-pick https://github.com/bazelbuild/bazel/commit/164705bf2507a97e584483b1ece3a590b84ae00a. Could you please take a look?

**Comment by coeuvre** [comment]
`7.4` branch has diverged too much from `master`. Since this PR doesn't introduce any user-visible features, maybe it's not worth the effort to cherry-pick?

**Comment by iancha1992** [comment]
> `7.4` branch has diverged too much from `master`. Since this PR doesn't introduce any user-visible features, maybe it's not worth the effort to cherry-pick?

WDYT? @Wyverald @meteorcloudy

**Comment by meteorcloudy** [comment]
FYI @fmeum, I'm closing this one for now.
