### ISSUE TITLE
`bazel vendor` ignores `--target_pattern_file`

### ISSUE THREAD

**Issue by lalten** [bazelbuild/bazel#23628]
### Description of the bug:

`bazel vendor` ignores `--target_pattern_file` and behaves as if no target pattern had been passed

### Which category does this issue belong to?

External Dependency

### What is the output of `bazel info release`?

release 7.3.1

**Comment by meteorcloudy** [comment]
@bazel-io fork 7.4.0

**Comment by meteorcloudy** [comment]
Thanks for reporting! I'm sending a fix and backport it to 7.4.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.4.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.4.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=7.4.0rc1`. Thanks!
