### ISSUE TITLE
[bazel.build] Problem with /external/vendor

### ISSUE THREAD

**Issue by Kadawe512** [bazelbuild/bazel#23624]
### Page link:

https://bazel.build/external/vendor

**Comment by Kadawe512** [comment]
Adb

**Comment by haxorz** [comment]
What's the problem with the doc you linked to?

I'm removing `team-Core` and not adding another label because at this point we don't know what the problem is, so it's hard to pick a category. I suppose `team-ExternalDeps` is the most plausible category though.
