### ISSUE TITLE
Incorrect handing of duplicated flag names in `bazel help flags-as-proto`

### ISSUE THREAD

**Issue by vogelsgesang** [bazelbuild/bazel#23632]
### Description of the bug:

There are two flags with the name `watchfs` (a deprecated `startup` flag and a `build` flag). However, the output of `bazel help flags-as-proto` only lists the deprecated `startup` flag, the build flag is missing from this dump.

This was reported in https://github.com/salesforce-misc/bazelrc-lsp/issues/2, where a user of the bazelrc language server realized that the language server is showing an incorrect deprecation warning for `common watchfs`.

The underlying root cause is that `emitFlagsAsProtoHelp` [uses a HashMap indexed by the flag-name](https://github.com/bazelbuild/bazel/blob/b4af015c1136213dc55e51df4167b95b43170969/src/main/java/com/google/devtools/build/lib/runtime/commands/HelpCommand.java#L242) to store information about all flags. This does not handle flags with colliding names correctly.

Not sure how to fix this. Either update `emitFlagsAsProtoHelp` or maybe just remove the deprecated `watchfs` startup flag for good?

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run `bazel help flags-as-proto`, base64-decode the result and interpret it as protobuf. You will see that the `watchfs` flag is listed only as a `startup` option, and the entry for the `build` option is missing.

### Which operating system are you running Bazel on?

not relevant

### What is the output of `bazel info release`?

not relevant

**Comment by haxorz** [comment]
> maybe just remove the deprecated watchfs startup flag for good?

Sure. I'll first work on migrating a few internal users to the command flag.

**Comment by haxorz** [comment]
After commit [`7409e6`](https://github.com/bazelbuild/bazel/commit/7409e68997c96b542cd8b619f7e9d6e4e037fc5c) we need to wait 6 months in order to delete the client-side handling of `--watchfs`.

But iiuc the change to `BlazeServerStartupOptions.java` obsoletes this issue here. @vogelsgesang do you agree?

**Comment by vogelsgesang** [comment]
yes, that solves the issue :)

**Comment by haxorz** [comment]
Thanks.

And thanks for reporting the underlying root cause. I'll keep that in mind for the future in case this sort of issue comes up again.
