### ISSUE TITLE
We shouldn't allow configured targets not to provide providers they advertise

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#2364]
This behavior was really conceived for the Google-internal `proto_library` rule which, depending on its attributes, may or may not support any language. 

However, this could be worked around by making `RuleClass#getAdvertisedProviders()` a function of the rule itself (not only its class) and it would make it harder to make mistakes by e.g. having a typo in the set of declared providers.

Also, this is the behavior we are aiming for with aspects and let's not be inconsistent between rule classes and aspects if we can help.

**Comment by brandjon** [comment]
I'm no aspects expert, but doesn't it seem pretty complicated to make advertised providers a function of the rule attrs? Why not require the provider but use an appropriately empty instance of it where there's no applicable data to pass along?

Or is the point here to allow aspects to propagate only to certain targets of a given rule type, based on those attributes? In which case, I'd question how much savings that kind of filtering gives us, vs the complexity of the request.

**Comment by lberki** [comment]
Since then, the internal `proto_library` rule doesn't have this behavior anymore because language-specific logic has been extracted from it. So I think doing this is now viable at least as far as native rules are concerned. I don't have any illusions, though, that all the Starlark rules we have conform to the "if you advertise it you must also provide it" rule...

**Comment by lberki** [comment]
I moved this to P3 because I would like this to happen, but realistically, we probably have better things to do, don't we?

**Comment by brandjon** [comment]
I set it to P4 because under current triage guidance P3 means "we'd welcome PRs that address this issue", and I wasn't sure we could guarantee bandwidth to review an incoming PR for this change. Ok if I set it back? I've been P4ing the overwhelming majority of issues as I work through our backlog.

**Comment by brandjon** [comment]
I think this issue is already solved?

```python
# pkg/test.bzl

FooInfo = provider()

def _foo_impl(ctx):
    pass  # No return [FooInfo(...)]

foo_rule = rule(
    implementation = _foo_impl,
    provides = [FooInfo],
)
```

```python
# pkg/BUILD

load(":test.bzl", "foo_rule")

foo_rule(
    name = "foo",
)
```

```sh
bazel build //pkg:foo
ERROR: [...] in foo_rule rule //pkg:foo: 
[...]: rule advertised the 'FooInfo' provider, but this provider was not among those returned
ERROR: Analysis of target '//pkg:foo' failed; build aborted: Analysis of target '//pkg:foo' failed
```

Was this issue about anything more than that?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
