### ISSUE TITLE
[7.4.0] Repeated invocations with `--noallow_analysis_cache_discard` don't fail as expected

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23643]
Forked from #23491

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/analysis/BuildView.java`
`src/main/java/com/google/devtools/build/lib/skyframe/SkyframeBuildView.java`
`src/test/java/com/google/devtools/build/lib/analysis/util/BuildViewForTesting.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/analysis/BuildView.java` `src/main/java/com/google/devtools/build/lib/skyframe/SkyframeBuildView.java` `src/test/java/com/google/devtools/build/lib/analysis/util/BuildViewForTesting.java`
> 
> cc: @bazelbuild/triage

cc: @fmeum @gregestren @lberki

**Comment by lberki** [comment]
Manually merged pull request is https://github.com/bazelbuild/bazel/pull/23653 .
