### ISSUE TITLE
Advanced examples (wrapping external builds).

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/bazel#2365]
I'm trying to setup a v8 build with depot_tools for use in a go project. I've got my head around bazel I think but there are too many concepts involved in getting such a custom build going. I'm trying to get bazel to do the build by following the human oriented steps -- i.e., use depot_tools in a script to checkout and build. At the end wrap the static artefacts and headers in a cc_library.

I was wondering if we could get this in an example, bonus would be a cross-compile (linux , darwin). I know this a bit of an ask but it's a very common use-case for 2 reasons:

1. Breaking the tie for a simple go build vs using Bazel. 
2. Wrapping complex external builds which cannot be driven by overlaying simple rules into external repositories.

**Comment by hsyed** [comment]
A list of projects demonstrating idiomatic ways us using bazel in a idiomatic way would be just as useful. --e.g., 

1. kubernetes/kubernetes (building docker layers, using some basic scripting in the build files)
2. tensorflow/tensorflow (??)

**Comment by laszlocsomor** [comment]
Hey,

Thanks for raising this request! I'm trying to triage it but I'm missing some context.
- Could you please clarify what is depot_tools?
- When you say "following the human oriented steps -- i.e., use depot_tools in a script to checkout and build", do you mean you try to do this using bazel build rules/macros or do you mean bazel is a part of this pipeline (supposedly the build step)?
- How much is this issue related to Go / to https://github.com/bazelbuild/rules_go -- is it a Go-specific example you're asking for, or does your use-case just happen to employ Go code / tools?
- "Wrapping complex external builds which cannot be driven by overlaying simple rules into external repositories." -- can you say more about this, or maybe give an example showing the problems? Is this a problem of bazel being unable to do something, or is it about inconvenience?

**Comment by hsyed** [comment]
Heya,

Sorry for the late response. 

[depot_tools](https://dev.chromium.org/developers/how-tos/install-depot-tools) is a collection of tools used by the Chromium / V8 project. It does various build related tasks, as far as an end-user building the code it is needed for checking out the repo and the third-party dependencies and for configuring the build.

An unfortunate side effect of this is that you cannot simply checkout out the v8 source code, if you do a manual check out you need to use a tool in depot_tools to "sync" the checkout.

What I mean by the human oriented steps is that I declared depot_tools and v8 as external repositories and I tried to use the various end-user oriented rules and concepts by reading the bazel documentation to try and orchestrate depot_tools into conducting the build. To me, at the of it all, it seemed that to build v8 I would have to learn skylark. 

It's not related to the go rules.

so refocusing:

* v8 is a C++ project there is more than one way to build it. 
* v8 cannot be declared as a simple external repository it needs to be synced by depot_tools before it can be built.

By wrapping I mean using the [new_git_repository](https://bazel.build/versions/master/docs/be/workspace.html#new_git_repository) mechanism and overlaying the build rules required to build  an external project. 

Perhaps builds like this are just outside the scope of idiomatic use of bazel ! But examples of this must exist. Are writing custom skylark rules the only way ?

**Comment by kchodorow** [comment]
Basically you want to download a thing and then run a script, right? 

You should be able to say something like:

```
# In, say, //:my_extractor.bzl
def _impl(ctx):
  for url in ctx.attr.urls:
    ctx.download_and_extract(url)
  result = ctx.execute(["./%s" % ctx.attr.script])
  if result.return_code != 0:
    print("Error executing %s: %s\n%s" % (ctx.attr.script, result.stdout, result.stderr))

download_and_exec = repository_rule(
    implementation = _impl,
    attrs = {
        'urls' : attr.string_list(mandatory = True),
        'script' : attr.string(),
    },
)
```

Then in your WORKSPACE file:

```
load('//:my_extractor.bzl', 'download_and_exec')
download_and_exec(
    name = 'v8',
    urls = ['https://gist.github.com/hsyed/b094299c27f89a029c816a1b281d61de/archive/100bfa24d63a0a8def7e4e25216b7f6d03070d2c.zip'],
    script = "b094299c27f89a029c816a1b281d61de-100bfa24d63a0a8def7e4e25216b7f6d03070d2c/build_v8.sh",
)
```

Then do `bazel build @v8//...; ls $(bazel info output_base)/external/v8` to see the results. 

You probably want to add fancier bells and whistles, but hopefully that will get you started.
