### ISSUE TITLE
Put all future "magic" labels in one location

### ISSUE THREAD

**Issue by adrianludwin** [bazelbuild/bazel#2366]
Bazel has a bunch of "magic" labels, like:

- //visibility:public
- //external
- //tools/defaults (but not //tools)
- //conditions:default
- @bazel_tools//...
- @local_host//... (this one might still be a proposal)

In addition, some of the toolchains create their own "magic" repos, like:

- @local_config_cc
- @local_jdk
- @local_config_xcode

However, experiments have shown that we don't do a good job of helping users with these labels - for example, there's nothing to stop you from creating a top-level package called "conditions," even though there probably should be! In addition, the fact that some built-in stuff appears in the "current" repo while other appear in external repos seems confusing.

My suggestion is that we pick one place for anything "builtin" and stick with it, and make it illegal for anyone else to create those names. For example, if we wanted to say that "//local/" is the the new "one place," then it should be illegal for a user to create a top-level package called "local." Or it could be a repo called @local, or it could be a prefix like @local_. This might yield names like:

- //local/conditions:default
- //local/visibility:public
- //local/external/...

or:

- @local//conditions:default
- @local//visibility:public
- @local//external/...

or:

- @local_conditions//default
- @local_visibility//public
- @local_repositories// (replacement for //external)

This last one is the closest to what we appear to have now, but it's a bit verbose IMO. Of course, actually moving _existing_ magic labels to the new format would be a lot harder than simply ensuring that all _new_ magic labels followed the new schema.

I would also suggest that only native rules/toolchains in Bazel were allowed to use these; Skylark toolchains would not. So if a Skylark toolchain wanted to create something like @local_jdk, we'd want to give them some convention instead like @toolchain_ and then let the individual users ensure there are no conflicts between the names chosen by their toolchains (which should be very rare).

**Comment by aiuto** [comment]
Adding to this:  The fundamental constraint values for platforms.
https://docs.google.com/document/d/1bqPF7CjHI03xHZmpy8gOE186uNjeU3dGYU8v2t-qiJ8/edit?disco=AAAAC1_NXUA&usp_dm=true&ts=5cc0dd23

**Comment by aiuto** [comment]
+1 to  @visibility and the pattern  @{name}... for all magic namespaces.

Proposal:
- rename `@visibilty` today, leaving `visibility` as an allowed synonym
- add the flag --enable_legacy_visibilty_name, defaulted to true.
   - users who want to enforce the new style for their builds can do that
- At an appropriate major release in the future flip the default for the flag
- At the next major release, drop the flag entirely.

**Comment by ulfjack** [comment]
If you're planning to change the "//visibility:public" labels, I had a proposal (a long time ago) to replace them with target patterns, which avoids magic names entirely.

**Comment by aiuto** [comment]
We are not really planning on that right now. I pinged this bug because I was venting steam.
I had just wasted an afternoon on a copybara import of a repo.  What you want is transforms that do
```
//:foo              -> //third_party/something:foo
@bazel_skylib:foo   -> //third_party/bazel_skylib:foo
//private:bar       -> //third_party/something/private:bar
//visibility:public -> //visibility:public
```

But how do a bunch of regex's know that visibility is very different from private?  If it were `@visibility//:private` it would be easy to handle on a site wide basis within a set of rules that remap all @<repo>// labels.

**Comment by ulfjack** [comment]
Private visibility is the default, so the empty list represents private. :-)

```
//foo/bar:__pkg__          -> //foo/bar:all
//foo/bar:__subpackages__  -> //foo/bar/....
//visibility:public        -> //...  (this isn't right, see below)
```

`//...` is all targets in the *current* workspace. We don't really have a concept for all targets in all workspaces right now, but you could come up with something like `@...` and also allow that in the CLI.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
