### ISSUE TITLE
[7.4.0] Fix upb build with Clang 16

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23668]
Forked from #23667

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`MODULE.bazel`
`third_party/upb/BUILD`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `MODULE.bazel` `third_party/upb/BUILD`
> 
> cc: @bazelbuild/triage

cc: @fmeum @meteorcloudy

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23700
