### ISSUE TITLE
[7.4.0] Optimize representation of runfiles in compact execution log

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23683]
Forked from #23321

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/actions/ActionExecutionContext.java`
`src/main/java/com/google/devtools/build/lib/actions/BUILD`
`src/main/java/com/google/devtools/build/lib/actions/RunfilesTree.java`
`src/main/java/com/google/devtools/build/lib/analysis/RunfilesSupport.java`
`src/main/java/com/google/devtools/build/lib/exec/BUILD`
`src/main/java/com/google/devtools/build/lib/exec/CompactSpawnLogContext.java`
`src/main/java/com/google/devtools/build/lib/exec/SpawnInputExpander.java`
`src/main/java/com/google/devtools/build/lib/exec/SpawnLogReconstructor.java`
`src/test/java/com/google/devtools/build/lib/analysis/util/FakeRunfilesTree.java`
`src/test/java/com/google/devtools/build/lib/exec/SpawnLogContextTestBase.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/actions/ActionExecutionContext.java` `src/main/java/com/google/devtools/build/lib/actions/BUILD` `src/main/java/com/google/devtools/build/lib/actions/RunfilesTree.java` `src/main/java/com/google/devtools/build/lib/analysis/RunfilesSupport.java` `src/main/java/com/google/devtools/build/lib/exec/BUILD` `src/main/java/com/google/devtools/build/lib/exec/CompactSpawnLogContext.java` `src/main/java/com/google/devtools/build/lib/exec/SpawnInputExpander.java` `src/main/java/com/google/devtools/build/lib/exec/SpawnLogReconstructor.java` `src/test/java/com/google/devtools/build/lib/analysis/util/FakeRunfilesTree.java` `src/test/java/com/google/devtools/build/lib/exec/SpawnLogContextTestBase.java`
> 
> cc: @bazelbuild/triage

cc: @tjgq @fmeum

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23713
