### ISSUE TITLE
[7.4.0] Intern `VectorArg`s more aggressively

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23684]
Forked from #23638

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkCustomCommandLine.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkCustomCommandLine.java`
> 
> cc: @bazelbuild/triage

@fmeum @justinhorvitz

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkCustomCommandLine.java`

cc: @bazelbuild/triage

**Comment by fmeum** [comment]
This cherry-pick isn't too important, let's close it.
