### ISSUE TITLE
//examples/j2objc:J2ObjCExample fails to build

### ISSUE THREAD

**Issue by matthewtodd** [bazelbuild/bazel#2368]
### Description of the problem / feature request / question:

It seems [`j2objc_library`](https://bazel.build/versions/master/docs/be/objective-c.html#j2objc_library) isn't ready for general out-of-the-box use, is that right?

I've been trying to get started with it this morning, and, FWICT,

1. The [workspace prefix for j2objc](https://github.com/bazelbuild/bazel/blob/1da429e943a4770161d63420b8ed0c7dcefba361/src/main/java/com/google/devtools/build/lib/bazel/rules/objc/j2objc.WORKSPACE) references a non-existent `BUILD` file.

2. Once I work around that as in #740, it seems the `//third_party/java/j2objc` package isn't included in `@bazel_tools`.

I'm willing to pitch in here. Would it be worthwhile for me to try to add the relevant j2objc bits to (I'm guessing) [create_embedded_tools.sh](https://github.com/bazelbuild/bazel/blob/1da429e943a4770161d63420b8ed0c7dcefba361/src/create_embedded_tools.sh)?

### If possible, provide a minimal example to reproduce the problem:

Building `//examples/j2objc:J2ObjcExample` seems like a good start:

```
~/Development/bazel (master u=) git rev-parse HEAD
1da429e943a4770161d63420b8ed0c7dcefba361

~/Development/bazel (master u=) ./bazel-bin/src/bazel build examples/j2objc:J2ObjcExample
ERROR: /Users/matthewtodd/Development/bazel/third_party/java/j2objc/BUILD:29:1: no such package '@bazel_j2objc//': In new_http_archive rule //external:bazel_j2objc the 'build_file' attribute does not specify an existing file (/var/tmp/_bazel_matthewtodd/install/db88fbe18280aa54e249a6f11b7b6698/_embedded_binaries/embedded_tools/third_party/java/j2objc/BUILD.remote does not exist) and referenced by '//third_party/java/j2objc:annotations'.
ERROR: Analysis of target '//examples/j2objc:J2ObjcExample' failed; build aborted.
INFO: Elapsed time: 3.811s
```

Then trying again, after manually providing bazel with a working `@bazel_j2objc` as in #740:

```diff
diff --git a/WORKSPACE b/WORKSPACE
index 666b8dfe9..ba199cf88 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -38,6 +38,13 @@ bind(
     actual = "//third_party:guava",
 )
 
+new_http_archive(
+    name = "bazel_j2objc",
+    url = "https://github.com/google/j2objc/releases/download/1.0.1/j2objc-1.0.1.zip",
+    sha256 = "25cd1da1c2ca2f446bcd9e663da1e1776316547f4b14785709d07ce888c34d67",
+    build_file = "third_party/java/j2objc/BUILD.remote"
+)
+
 # For tools/cpp/test/...
 load("//tools/cpp/test:docker_repository.bzl", "docker_repository")
 docker_repository()
```

```
~/Development/bazel (master * u=) ./bazel-bin/src/bazel build examples/j2objc:J2ObjcExample
ERROR: /Users/matthewtodd/Development/bazel/examples/j2objc/BUILD:15:1: every rule of type java_library implicitly depends upon the target '@bazel_tools//third_party/java/j2objc:proto_plugin', but this target could not be found because of: no such package '@bazel_tools//third_party/java/j2objc': BUILD file not found on package path.
ERROR: /Users/matthewtodd/Development/bazel/examples/j2objc/BUILD:15:1: every rule of type java_library implicitly depends upon the target '@bazel_tools//third_party/java/j2objc:jre_emul.jar', but this target could not be found because of: no such package '@bazel_tools//third_party/java/j2objc': BUILD file not found on package path.
ERROR: /Users/matthewtodd/Development/bazel/examples/j2objc/BUILD:15:1: every rule of type java_library implicitly depends upon the target '//third_party/java/j2objc:proto_runtime', but this target could not be found because of: no such target '//third_party/java/j2objc:proto_runtime': target 'proto_runtime' not declared in package 'third_party/java/j2objc' defined by /Users/matthewtodd/Development/bazel/third_party/java/j2objc/BUILD.
ERROR: Analysis of target '//examples/j2objc:J2ObjcExample' failed; build aborted.
INFO: Elapsed time: 184.003s
```

### Environment info
* Operating System: **macOS 10.12.2**

* Bazel version (output of `bazel info release`): **development version**

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`): **`1da429e943a4770161d63420b8ed0c7dcefba361`**

###  Have you found anything relevant by searching the web?

* [bazel-discuss](https://groups.google.com/forum/#!searchin/bazel-discuss/j2objc%7Csort:date) doesn't seem to have anything interesting.
* #1055 faintly suggests these rules might someday move out of bazel proper?

**Comment by c-parsons** [comment]
This is now fixed for me at current -- not sure what the affecting change was. 
Let me know if this is still broken for you.
