### ISSUE TITLE
[7.4.0] Precompute hashcode for `RepositoryName`.

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#23696]
### Commit IDs

5949aacc3a92e36e25293120c93d409f42e79b46

### Category

team-Configurability

### Reviewers

@justinhorvitz

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/23697: https://github.com/bazelbuild/bazel/commit/5949aacc3a92e36e25293120c93d409f42e79b46.
