### ISSUE TITLE
ElasticSearch not working with Bazel in windows

### ISSUE THREAD

**Issue by carolinasolfernandez** [bazelbuild/bazel#23698]
### Description of the bug:

When executing bazel with an elastic search dependency:

```
ERROR: C:/users/caros/_bazel_caros/5stqozjs/external/com_github_elastic_go_elasticsearch_v7/esapi/BUILD.bazel:3:11: GoCompilePkg external/com_github_elastic_go_elasticsearch_v7/esapi/esapi.a failed: (Exit 1): builder.exe failed: error executing command (from target @com_github_elastic_go_elasticsearch_v7//esapi:esapi) bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\external\go_sdk\builder.exe -param=bazel-out/x64_windows-fastbuild/bin/external/com_github_elastic_go_elasticsearch_v7/esapi/esapi.a-0.params
<unknown line number>: internal compiler error: panic: badly formatted input
```

### Which category does this issue belong to?

Local Execution

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

include in the build:
        "@com_github_elastic_go_elasticsearch_v7//:go_default_library",
run with bazel 

### Which operating system are you running Bazel on?

Windows 11

**Comment by tjgq** [comment]
That looks like a problem with the Go compiler or the Go rules, not with Bazel. Try filing an issue against https://github.com/bazelbuild/rules_go?
