### ISSUE TITLE
ctx.files linearizes nested sets

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#2370]
This code:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/SkylarkRuleContext.java#L330

linearizes nested sets and as such, unnecessarily increases memory use.

**Comment by laurentlb** [comment]
I'm tented to close as "working as intended". I don't expect us to change this.

**Comment by lberki** [comment]
Why?

**Comment by laurentlb** [comment]
Changing the behavior of `ctx.files` is a very disruptive change and would break a lot of code.
I think the cost of changing is higher than the benefits.

**Comment by lberki** [comment]
That's fair. I guess one can always say `ctx.attr.dep[FileProvider]`?

**Comment by laurentlb** [comment]
Yes. `ctx.files` is just for convenience.
