### ISSUE TITLE
[7.4.0] Strip unnecessary Bazel server jar contents

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23707]
Forked from #22787

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`MODULE.bazel.lock`
`maven_install.json`
`src/test/shell/integration/minimal_jdk_test.sh`
`third_party/BUILD`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23709
