### ISSUE TITLE
[7.4.0] Allow spaces in runfile source and target paths

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23715]
Forked from #23331

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`MODULE.bazel.lock`
`src/main/java/com/google/devtools/build/lib/analysis/SourceManifestAction.java`
`src/test/java/com/google/devtools/build/lib/analysis/SourceManifestActionTest.java`
`src/test/shell/integration/runfiles_test.sh`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `MODULE.bazel.lock` `src/main/java/com/google/devtools/build/lib/analysis/SourceManifestAction.java` `src/test/java/com/google/devtools/build/lib/analysis/SourceManifestActionTest.java` `src/test/shell/integration/runfiles_test.sh`
> 
> cc: @bazelbuild/triage

cc: @lberki @fmeum @meteorcloudy

**Comment by fmeum** [comment]
https://github.com/bazelbuild/bazel/pull/23912
