### ISSUE TITLE
[7.4.0] Fix naming inconsistency in `spawn.proto`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23710]
Forked from #23706

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/exec/CompactSpawnLogContext.java` `src/main/java/com/google/devtools/build/lib/exec/SpawnLogReconstructor.java` `src/main/protobuf/spawn.proto`
> 
> cc: @bazelbuild/triage

@tjgq @fmeum

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23713
