### ISSUE TITLE
request sandbox keep timezone with host

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/bazel#23717]
### Description of the feature request:

I found execute unit_test success manually, but bazel test //... will fail, for sandbox timezone UTC+0, my host timeze is UTC+8

### Which category does this issue belong to?

Core

### Which operating system are you running Bazel on?

ubuntu 22.04

### What is the output of `bazel info release`?

7.2.0

**Comment by tjgq** [comment]
I'd argue that normalizing the timezone is a *desirable* property of a sandbox, as it ensures people running the same build in environments configured for different timezones can still share a (remote) cache.
