### ISSUE TITLE
[7.4.0] Add `override_repo` and `inject_repo`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23724]
Forked from #23534

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelDepGraphFunction.java`
`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelDepGraphValue.java`
`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionEvalStarlarkThreadContext.java`
`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/RegularRunnableExtension.java`
`src/test/java/com/google/devtools/build/lib/starlark/StarlarkIntegrationTest.java`
`src/test/tools/bzlmod/MODULE.bazel.lock`

cc: @bazelbuild/triage

**Comment by fmeum** [comment]
@Wyverald Part of the conflict is due to https://github.com/bazelbuild/bazel/commit/e9aada57a4da30243c43f9e9372aa534a91bb017 missing from the release branch, could you cherry-pick it?

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23938
