### ISSUE TITLE
[7.4.0] Correct docs about allowed syntax of `exports_filter`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23725]
Forked from #22943

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/starlark/builtins_bzl/common/cc/cc_shared_library.bzl`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/starlark/builtins_bzl/common/cc/cc_shared_library.bzl`
> 
> cc: @bazelbuild/triage

cc: @fmeum @thii @comius

**Comment by thii** [comment]
There's no docs for `cc_shared_library` in the `release-7.4.0` branch yet, so there's no need to cherry-pick this. Or we could cherry-pick the changes adding the docs first.

**Comment by iancha1992** [comment]
Closing then @thii. Thank you! 
cc: @fmeum @comius

**Comment by fmeum** [comment]
@thii It does have docs: https://bazel.build/versions/7.3.0/reference/be/c-cpp#cc_shared_library

**Comment by thii** [comment]
Ah I mean docs in the bzl file. Looks like [this change](https://github.com/bazelbuild/bazel/commit/44c5a1bbb26d3c61b37529b38406f1f5b0832baf) move docs from the Java file to the bzl file, but it hasn't been cherry-picked.
