### ISSUE TITLE
[7.4.0] Mark tool runfiles as such in expanded execution log

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23734]
Forked from #23702

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/exec/BUILD`
`src/main/java/com/google/devtools/build/lib/exec/ExpandedSpawnLogContext.java`
`src/test/java/com/google/devtools/build/lib/exec/SpawnLogContextTestBase.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23713
