### ISSUE TITLE
prelude seems to only work with remote repos in bazel 0.4.2

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#2373]
Using homebrew osx bazel 0.4.2, I would like to put a rule in my prelude.

I have a file at `local_tools/scala/scala.bzl`

If I write this as:

`load("/local_tools/scala/scala", "scala_library")`

it seems to work. If I do:

`load("//local_tools/scala:scala.bzl", "scala_library")`

I get:
`ERROR: error loading package '@bazel_tools//tools/cpp': Extension file not found. Unable to load package for '@bazel_tools//local_tools/scala:scala.bzl': BUILD file not found on package path.`

if I use the full name of the repo (as declared in `workspace(name = "foo")`) I get:

`ERROR: error loading package 'decibel-summingbird/src/main/scala/com/stripe/decibel': Encountered error while reading extension file 'local_tools/scala/scala.bzl': no such package '@com_stripe_decibel//local_tools/scala': error loading package 'external': The repository named 'com_stripe_decibel' could not be resolved.`

I'm not sure why there are several ways to do the load rather than one. I'm not sure why doing the load with `/local_tools/scala/scala` works, but `//local_tools/scala:scala.bzl` does not, when I thought the former was the correct way.

**Comment by dslomov** [comment]
Is this still reproducible? If yes, we need to fix it.

**Comment by johnynek** [comment]
no, it is not.
