### ISSUE TITLE
linux-sandbox: "No such file or directory" error with `TMPDIR` under `/tmp`

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#23754]
I also see this inside of a nix-shell, where `TMP` and `TMPDIR` is set to a dedicated temp directory from `/tmp/nix-shell.XXXXXX`.

> Can you provide more detailed instructions for reproducing this? I'd need the exact command line.
> 
> I have been trying to reproduce with:
> 
> ```
> TMPDIR=/home/oquenchil/tmpdir USE_BAZEL_VERSION=7.1.0 bazelisk build --action_env=TMPDIR=/home/oquenchil/tmpdir --sandbox_debug :foo
> ```

I think you need to set TMPDIR to a directory inside `/tmp` to trigger the error. Since `/tmp` is mounted empty inside the sandbox, the given `TMPDIR` does not exist...

It works for me, when I use `--noincompatible_sandbox_hermetic_tmp`.

\edit: Oh, I came here from #5900. I don't see the permission denied error, but `No such file or directory`.

_Originally posted by @avdv in https://github.com/bazelbuild/bazel/issues/23217#issuecomment-2373083363_

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.4.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.4.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=7.4.0rc1`. Thanks!

**Comment by Flamefire** [comment]
For future reference:

I did run into this with this error:
`src/main/tools/linux-sandbox-pid1.cc:320: "mount(/tmp/eb-hx1aw_vl, /tmp/eb-hx1aw_vl, nullptr, MS_BIND | MS_REC, nullptr)": No such file or directory`

765d5e0a64926517d686ff567d280914df08e7dc fixes that.

**Comment by pcj** [comment]
@Flamefire to piggyback on your comment, it would appear that upgrading to bazel 8 is needed for that fix.
