### ISSUE TITLE
[7.4.0] Create writable dirs under hermetic tmp in the sandbox

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23756]
Forked from #23755

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxedSpawnRunner.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23796
