### ISSUE TITLE
[7.4.0] Add `--incompatible_no_implicit_watch_label`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23768]
Forked from #23750

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java`
`src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java`
`src/test/java/com/google/devtools/build/lib/bazel/repository/starlark/BUILD`
`src/test/shell/bazel/starlark_repository_test.sh`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23900
