### ISSUE TITLE
[7.4.0] Weakly cache runfiles mappings of tools

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23775]
Forked from #23774

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/analysis/RunfilesSupport.java`
`src/test/java/com/google/devtools/build/lib/skyframe/RemoteConfiguredTargetValueCodecTest.java`

cc: @bazelbuild/triage

**Comment by fmeum** [comment]
This is too difficult to cherry-pick.
