### ISSUE TITLE
[7.4.0] Automatically ignore vendor dir for finding packages

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23772]
Forked from #23771

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/test/java/com/google/devtools/build/lib/buildtool/BUILD`
`src/test/java/com/google/devtools/build/lib/buildtool/ProjectResolutionTest.java`
`src/test/java/com/google/devtools/build/lib/pkgcache/IncrementalLoadingTest.java`
`src/test/java/com/google/devtools/build/lib/skyframe/GlobTestBase.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/test/java/com/google/devtools/build/lib/buildtool/BUILD` `src/test/java/com/google/devtools/build/lib/buildtool/ProjectResolutionTest.java` `src/test/java/com/google/devtools/build/lib/pkgcache/IncrementalLoadingTest.java` `src/test/java/com/google/devtools/build/lib/skyframe/GlobTestBase.java`
> 
> cc: @bazelbuild/triage

cc: @meteorcloudy @Wyverald @gregestren

**Comment by meteorcloudy** [comment]
Manually backporting at https://github.com/bazelbuild/bazel/pull/23919
