### ISSUE TITLE
Document default value and possible values for --experimental_build_event_upload_strategy

### ISSUE THREAD

**Issue by mortenmj** [bazelbuild/bazel#23789]
### Page link:

https://bazel.build/reference/command-line-reference

### Problem description (include actual vs expected text, if applicable):

Currently the documentation for the default value says "default: see description", but the default is not explained in the description. There is also no list of legal values for this flag, which makes it hard to know what values can be set.
The description of the flag could also be expanded a bit, to better communicate what this is for.

### Where do you see this issue? (include link to specific section of the page, if applicable)

https://bazel.build/reference/command-line-reference#flag--experimental_build_event_upload_strategy

**Comment by jin** [comment]
@michaeledgar

**Comment by michaeledgar** [comment]
(Back from baby bonding leave) I've sent a CL to document this. While we wait for it to go through review, I can share my first draft of the new help string:

> "Selects how to upload artifacts referenced in the build event protocol. In Bazel the valid options include 'local' and 'remote'. The default value is 'local'."

(This option takes an additional value in Blaze. This is likely why the docstring was left so bare-bones before.)
