### ISSUE TITLE
SyntaxNet compilation broken

### ISSUE THREAD

**Issue by bogatyy** [bazelbuild/bazel#2378]
SyntaxNet (released as part of tensorflow/models) currently does not compile.

Installation instructions: https://github.com/tensorflow/models/tree/master/syntaxnet#installation
Used to work with bazel-0.3.0.

My guess is that it was broken by the following bazel-0.3.2 incompatible change:
_The main repository's execution root is under the main
repository's workspace name, not the source directory's basename.
This shouldn't
have any effect on most builds, but it's possible it could break
someone doing
weird things with paths in actions._

What should be done to fix the build? Seems that the reference @jpeg//:jpeg from the core tensorflow is broken when executed from tensorflow/models repository.

**Comment by katre** [comment]
Looking into this now.

**Comment by katre** [comment]
The basic problem is that jpeg.BUILD isn't referring to the correct third_party:configure.bzl path.

This seems to be fixed in tensorflow by https://github.com/tensorflow/tensorflow/commit/4f6e6eb285e0e925271d632cc688811ca4e8c5a2.

Can you update syntaxnet to use that version of tensorflow?

**Comment by bogatyy** [comment]
Thank you! Fixed.
