### ISSUE TITLE
[7.4.0] Disallow importing injected repos

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23799]
Forked from #23798

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleThreadContext.java`
`src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionResolutionTest.java`
`src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunctionTest.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleThreadContext.java` `src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleExtensionResolutionTest.java` `src/test/java/com/google/devtools/build/lib/bazel/bzlmod/ModuleFileFunctionTest.java`
> 
> cc: @bazelbuild/triage

@fmeum @Wyverald @meteorcloudy
