### ISSUE TITLE
Uses clang-16 instead clang++-16 and  

### ISSUE THREAD

**Issue by BhJaipal** [bazelbuild/bazel#23797]
### Description of the bug:

Sometimes when I try to run bazel build, it gives error 
ERROR: /home/jaipal001/Desktop/files/c-use/J7-language/main/BUILD:1:10: Linking main/j7 failed: (Exit 1): clang failed: error executing CppLink command (from target //main:j7) /usr/lib/llvm-16/bin/clang @bazel-out/k8-fastbuild/bin/main/j7-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
ld.lld: error: unable to find library -lstdc++ 

### Which category does this issue belong to?

C++ Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

bazel.bazelrc:
CC=/bin/clang++-16
CXX=/bin/clang++-16
-lstdc++=/usr/lib/x86_64-linux-gnu/libstdc++.so

main/BUILD
cc_library(
	name="lexer",
	srcs= ["lexer.cpp"],
	hdrs= ["lexer.hpp"],
	visibility = ["//main:__pkg__"],
	deps = ["//modules:mod", "//utils:utils"],
	copts = [ "-I/usr/include/c++/11", "-I/usr/include/x86_64-linux-gnu/c++/11"],
	includes = [ "/usr/include/c++/11", "/usr/include/x86_64-linux-gnu/c++/11"],
)

bazel build //main:j7

### Which operating system are you running Bazel on?

Pop os latest 22.04 or 24.04

### What is the output of `bazel info release`?

release 7.3.1

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

No,  
bazel info release
release 7.3.1
by apt install bazel

### Have you found anything relevant by searching the web?

I came yesterday and it got solved but now it is not working

**Comment by pzembrod** [comment]
I'm sorry, but from your description I can't really determine what might be going wrong in your setup.
Given that apparently building the main binary sometimes works and sometimes fails in the link invocation, could it be that your overall setup is unstable? Also, could it be that the link failures are legitimate link errors e.g. because of unresolved symbols in your code?
