### ISSUE TITLE
SVG logo missing in repo.

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2382]
Please add a SVG variant of the Bazel logo to the repo.
<sub>If that isn't P0, I don't know what is 😈 </sub>

**Comment by steren** [comment]
(being a former Inkscape contributor): +1 to open formats and vector files!
Wikipedia is also using a png: https://en.wikipedia.org/wiki/File:Bazel_logo.png we should fix this too.

Let me see what I can do.

Also note that the Bazel logo is a bit blurry on our landing page on my Retina screen. We will adress this last point at the same time of some other improvement to the website,

**Comment by steren** [comment]
I am putting this effort on hold until we receive confirmation we are able to add the source of the logo to the repo.
