### ISSUE TITLE
genrule Tagged as manual Still Builds during build (not test) When Used in py_test or sh_test

### ISSUE THREAD

**Issue by brianantony456** [bazelbuild/bazel#23822]
### Description of the bug:

When a genrule is tagged as manual, it's expected that the rule should not build unless explicitly invoked. However, when this rule is used in the data attribute of a py_test or sh_test, it still builds during the build invocation.

i.e. with `bazelisk build ...`

The underlying question is if you do a bazel build on a test rule, should Bazel really build all inputs of the test at this point ?
The alternative would be: delay building test dependencies until they are necessary, meaning: until bazel test.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```python
load("@rules_python//python:defs.bzl", "py_test")

genrule(
    name = "manual-test-only-rule",
    srcs = [],
    outs = ["dummy"],
    cmd = "echo xxx > $@",
    tags = ["manual"]
)

py_test(
    name = "test-me",
    srcs = ["test-me.py"],
    data = [":manual_test_only_rule"],
)
```

### Which operating system are you running Bazel on?

RHEL7

### What is the output of `bazel info release`?

7.3.1

**Comment by jin** [comment]
> The underlying question is if you do a bazel build on a test rule, should Bazel really build all inputs of the test at this point ? The alternative would be: delay building test dependencies until they are necessary, meaning: until bazel test.

`bazel test` is at its essence `bazel build` with extra test logic when the build completes. 

So I think it's by design and fully expected that building a test must also build its runfiles data dependencies- otherwise you'll just get an inconsistent and incomplete representation of the test runtime environment.

**Comment by haxorz** [comment]
What @jin said is correct.

> When a genrule is tagged as manual, it's expected that the rule should not build unless explicitly invoked.

Not quite. From https://bazel.build/reference/be/common-definitions#common-attributes:

```
manual keyword will exclude the target from expansion of target pattern wildcards ...
when computing the set of top-level targets to build/run for the build, test, and coverage commands`
```

So, the tagged target won't be in the set of top-level targets for your `bazelisk build ...` invocation. But the tagged target would still be built if its a transitive dependency of one of the top-level targets.
