### ISSUE TITLE
Option `--strip=always` has no effect for C++, possibly need to use `-s` instead of `-S` for linker

### ISSUE THREAD

**Issue by hauserx** [bazelbuild/bazel#23827]
### Description of the bug:

Documentation: https://bazel.build/reference/command-line-reference#flag--strip
`Specifies whether to strip binaries and shared libraries (using "-Wl,--strip-debug")`

But code uses `-S` option:
https://github.com/bazelbuild/bazel/blob/676ba6e38322d5890fe1a81609d2de93f3b739a4/tools/cpp/unix_cc_toolchain_config.bzl#L1076

But `-s` should be used, the `-S` when passed to linker seems to have no effect:
https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html#index-s

The `--strip-debug` seems to be strip command option and not the linker option? https://linux.die.net/man/1/strip

### Which category does this issue belong to?

C++ Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Using `--strip=never` or `--strip=always` seems to have no effect:

```bash
echo 'workspace(name = "bazel_simple")' > WORKSPACE
echo 'int main() {}' > main.c
echo 'cc_binary(name="main", srcs=["main.c"])' > BUILD

USE_BAZEL_VERSION=last_green bazel build --strip=never :main
file bazel-bin/main
bazel-bin/main: (...), not stripped
ls -la bazel-bin/main
size: 6112

USE_BAZEL_VERSION=last_green bazel build --strip=always :main
bazel-bin/main: (...), not stripped
size: 6112
```

Specifying `-s` manually works as expected:
```bash
USE_BAZEL_VERSION=last_green bazel build --strip=always :main --linkopt="-Wl,-s"
bazel-bin/main: (...) stripped
size: 4808
```

For reference, building .stripped version works somewhat differently:
```bash
USE_BAZEL_VERSION=last_green bazel build --strip=always :main.stripped
bazel-bin/main: (...), not stripped
size: 5968

USE_BAZEL_VERSION=last_green bazel build --strip=always :main.stripped --linkopt="-Wl,-s"
bazel-bin/main: (...) stripped
size: 4800
```

### Which operating system are you running Bazel on?

Ubuntu 20.04

### What is the output of `bazel info release`?

development version

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

Bazelisk option:
USE_BAZEL_VERSION=last_green

**Comment by pzembrod** [comment]
Stripping in the context of Bazel's C / C++ rules means stripping debug symbols, not all symbols: https://bazel.build/reference/be/c-cpp#implicit-output-targets

`-s` is an alias for `--strip-all` and `-S` is an alias for `--strip-debug` both for LLVM's ld.lld and for GCC's collect2:```
```
$ ld.lld-16 --help|grep strip
  --strip-all             Strip all symbols. Implies --strip-debug
  --strip-debug           Strip debugging information
  -S                      Alias for --strip-debug
  -s                      Alias for --strip-all

$ /usr/libexec/gcc/x86_64-linux-gnu/13/collect2 --help|grep strip
  -s, --strip-all             Strip all symbols
  -S, --strip-debug           Strip debugging symbols
```
So `--strip=` actually works as intended.

I'm guessing that the main.c in the example may not have any debug symbols?
