### ISSUE TITLE
[7.4.0] Add opt-in set_soname feature

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23842]
Forked from #23839

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`tools/cpp/unix_cc_toolchain_config.bzl`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `tools/cpp/unix_cc_toolchain_config.bzl`
> 
> cc: @bazelbuild/triage

cc: @keith @comius @fmeum

**Comment by keith** [comment]
@fmeum should we cherry pick https://github.com/bazelbuild/bazel/pull/23090/ w/o the default flip? that's the source of the conflict

**Comment by fmeum** [comment]
@keith Yes, sounds good!
