### ISSUE TITLE
[7.4.0] Add conlyopts and cxxopts attributes to cc rules

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23840]
Forked from #23792

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/starlark/builtins_bzl/common/cc/attrs.bzl`
`src/main/starlark/builtins_bzl/common/cc/cc_binary.bzl`
`src/main/starlark/builtins_bzl/common/cc/cc_library.bzl`

cc: @bazelbuild/triage

**Comment by fmeum** [comment]
@keith

**Comment by keith** [comment]
thanks! https://github.com/bazelbuild/bazel/pull/23904
