### ISSUE TITLE
[Mirror] Protobuf deps

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#23845]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/protocolbuffers/protobuf/archive/3b62052186d39775090fb074adcba078ea622f54.zip
https://github.com/bazel-contrib/bazel_features/releases/download/v1.17.0/bazel_features-v1.17.0.tar.gz
https://github.com/grpc/grpc/archive/refs/tags/v1.66.0.tar.gz
https://github.com/bazelbuild/rules_fuzzing/releases/download/v0.5.2/rules_fuzzing-0.5.2.zip 
https://github.com/bazelbuild/rules_foreign_cc/releases/download/0.10.1/rules_foreign_cc-0.10.1.tar.gz
https://github.com/bazelbuild/rules_apple/releases/download/3.5.1/rules_apple.3.5.1.tar.gz
https://github.com/googleapis/googleapis/archive/fe8ba054ad4f7eca946c2d14a63c3f07c0b586a0.tar.gz
https://github.com/grpc/grpc-java/archive/refs/tags/v1.66.0.tar.gz
https://github.com/bazelbuild/rules_swift/releases/download/1.18.0/rules_swift.1.18.0.tar.gz

**Comment by satyanandak** [comment]
Here you go
https://mirror.bazel.build/github.com/protocolbuffers/protobuf/archive/3b62052186d39775090fb074adcba078ea622f54.zip
https://mirror.bazel.build/github.com/bazel-contrib/bazel_features/releases/download/v1.17.0/bazel_features-v1.17.0.tar.gz
https://mirror.bazel.build/github.com/grpc/grpc/archive/refs/tags/v1.66.0.tar.gz
https://mirror.bazel.build/github.com/bazelbuild/rules_fuzzing/releases/download/v0.5.2/rules_fuzzing-0.5.2.zip
https://mirror.bazel.build/github.com/bazelbuild/rules_foreign_cc/releases/download/0.10.1/rules_foreign_cc-0.10.1.tar.gz
https://mirror.bazel.build/github.com/bazelbuild/rules_apple/releases/download/3.5.1/rules_apple.3.5.1.tar.gz
https://mirror.bazel.build
/github.com/googleapis/googleapis/archive/fe8ba054ad4f7eca946c2d14a63c3f07c0b586a0.tar.gz
https://mirror.bazel.build/github.com/grpc/grpc-java/archive/refs/tags/v1.66.0.tar.gz
https://mirror.bazel.build/github.com/bazelbuild/rules_swift/releases/download/1.18.0/rules_swift.1.18.0.tar.gz
