### ISSUE TITLE
Modification to remote (and disk) caches should invalidate persistent action cache remote metadata

### ISSUE THREAD

**Issue by layus** [bazelbuild/bazel#23841]
### Description of the bug:

When changing cache locations and/or cache options, the metadata stored in the persistent action cache becomes stale. Bazel starts erroring on missing remote blobs. Its easy to reproduce with remote execution and bwtb.

Just like when some flag changes invalidate the evaluation cache, I think changes to cache-related flags should invalidate the remote metadata in the persistent action cache.

This is a bit more tricky, because changes to these flags may or may not stem from a concrete change in the cache (like the cache secret key), but better safe than sorry. Invalidating that cache is not a huge loss, and cache changes are not supposed to happen frequently.

Then only way I know to discard that cache is `bazel clean`, which is more aggressive than needed because it also discards local data.

### Which operating system are you running Bazel on?

Ubuntu

### What is the output of `bazel info release`?

bazel 7.2

**Comment by layus** [comment]
See also https://github.com/bazelbuild/bazel/issues/8248

**Comment by coeuvre** [comment]
Duplicate of #23780?

**Comment by layus** [comment]
Yes, https://github.com/bazelbuild/bazel/issues/23780 seems close enough.
