### ISSUE TITLE
compile.sh broken at 88eca6e4f3951fe0ee1be3306bfb85f560bc046a

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/bazel#2384]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
........
ERROR: Illegal javabase value '', javabase must be an absolute path or label.
INFO: Elapsed time: 2.268s

ERROR: Could not build Bazel

### If possible, provide a minimal example to reproduce the problem:

on a system with bazel:

git pull && ./compile.sh compile `which bazel

### Environment info
* Operating System:

Linux and OSX

* Bazel version (output of `bazel info release`):
release 0.4.3-2017-01-18 (@dc61484cb)

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by laszlocsomor** [comment]
@lberki Do you think is P0 adequate? I think P1 would be fine. If you agree, please downgrade. Otherwise, do you have any updates?

**Comment by damienmg** [comment]
P0 it is blocking the release and we are already late.
