### ISSUE TITLE
Update documentation pages for Symbolic Macros, Finalizers, and Macro-Aware Visibility

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#23857]
Kinds of documentation to update:
- [x] Concept pages for macros
- [x] API docs (`macro()` callable, etc.)
- [x] Concept pages for visibility
- [x] Executable example in examples repo

**Comment by brandjon** [comment]
@bazel-io flag 8.0.0

**Comment by iancha1992** [comment]
@bazel-io fork 8.0.0

**Comment by iancha1992** [comment]
@bazel-io fork 8.0.0

**Comment by Wyverald** [comment]
What's the status of this? Can we get docs done by 25 Nov?

**Comment by tetromino** [comment]
@Wyverald - it's in progress; @brandjon is updating visibility docs, and I have in review updates for the `macro()` built-in and the macros introduction doc. We should be able to get it done by 25.

**Comment by brandjon** [comment]
@wyverald There's three CLs to be cherrypicked imminently that'll close off this issue.
