### ISSUE TITLE
Windows: ForEachDirectoryEntry implementation (e00a9ce) can break tests

### ISSUE THREAD

**Issue by vladmos** [bazelbuild/bazel#2386]
The windows-x86_64 @ HEAD configuration fails on Jenkins: http://ci.bazel.io/job/bazel-tests/ . This doesn't seem to be flaky.

@laszlocsomor: assigning to you because you are the author of the recent Windows-related changes.

**Comment by laszlocsomor** [comment]
Added logging (https://github.com/bazelbuild/continuous-integration/commit/e00a9ce713d53158ad15bf235ce666aaf0500e65) to catch this bug. Will reopen if this bug occurres again.

**Comment by laszlocsomor** [comment]
Update: I couldn't yet repro this issue.

**Comment by laszlocsomor** [comment]
@meteorcloudy found the culprit: d5527469ca629f806a7576783289cc0613bf418b, we're rolling it back. Thank you!

**Comment by laszlocsomor** [comment]
This was an example log:
http://ci.bazel.io/job/bazel-tests/491/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-x86_64/console
