### ISSUE TITLE
[7.4.0] Do no crash if a requested resource is not available

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23868]
Forked from #23541

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/actions/BUILD`
`src/main/java/com/google/devtools/build/lib/actions/ResourceManager.java`
`src/test/java/com/google/devtools/build/lib/actions/ResourceManagerTest.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/actions/BUILD` `src/main/java/com/google/devtools/build/lib/actions/ResourceManager.java` `src/test/java/com/google/devtools/build/lib/actions/ResourceManagerTest.java`
> 
> cc: @bazelbuild/triage

cc: @fmeum @meisterT

**Comment by fmeum** [comment]
https://github.com/bazelbuild/bazel/pull/23911
