### ISSUE TITLE
Add copybara to list of OSS projects using Bazel

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#2388]
Not sure if it should be an issue here or on [Copybara](https://github.com/google/copybara) but it uses Bazel for it's build.
cc @mikelalcon 
https://github.com/bazelbuild/bazel/blob/0b06ac45882d8c23f4f53817a0b6e7b3dffc8957/site/users.md

**Comment by laszlocsomor** [comment]
Thanks! It's good that you reported it here and not / not just on Copybara, we probably wouldn't have discovered the issue there.

**Comment by laszlocsomor** [comment]
@mhlopko , Could you please update the relevant page?

**Comment by mhlopko** [comment]
Fixed in cb174258b2c660f6df86436ac256d190e76c346a
