### ISSUE TITLE
Allow `$(location ...)` expansion in `cc_library.defines` for `additional_compiler_inputs`.

### ISSUE THREAD

**Issue by filmil** [bazelbuild/bazel#23886]
### Description of the feature request:

See title.

I wrote a way more detailed and reasoned explanation, but then something hiccuped and all my writing was just lost. Sorry, I'm not redoing all of that.

### What underlying problem are you trying to solve with this feature?

See title.

### Which operating system are you running Bazel on?

GNU/Linux :)

### What is the output of `bazel info release`?

release 7.3.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
N/A
```

**Comment by fmeum** [comment]
It's here: https://github.com/bazelbuild/bazel/issues/23885
