### ISSUE TITLE
Bazel 8.0.0rc1: 'cc/toolchains' is not a package error

### ISSUE THREAD

**Issue by gergelyfabian** [bazelbuild/bazel#23899]
### Description of the bug:

Testing Bazel 8.0.0rc1 I got such an error:

```
ERROR: Error computing the main repository mapping: at /home/user/.cache/bazel/_bazel_user/64527517dacf7170f7d914889f83481c/external/bazel_tools/tools/cpp/cc_configure.bzl:18:6: Label '@@rules_cc//cc/toolchains:toolchain_config_utils.bzl' is invalid because 'cc/toolchains' is not a package; perhaps you meant to put the colon here: '@@rules_cc//cc:toolchains/toolchain_config_utils.bzl'?
```

This worked with Bazel 7.3.2.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Reproduction: https://github.com/gergelyfabian/bazel-scala-example/tree/bazel-8.0.0rc1

Simply run `bazel build //...` in this repo at branch `bazel-8.0.0rc1`

### Which operating system are you running Bazel on?

Ubuntu 24.04

### What is the output of `bazel info release`?

release 8.0.0rc1

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
git@github.com:gergelyfabian/bazel-scala-example.git
0bbacfe5f35550db2da2ea5ba4f0edcba81ad46
```

### If this is a regression, please try to identify the Bazel commit where the bug was introduced with bazelisk --bisect.

$ bazelisk --bisect=7.3.2..8.0.0rc1

This finds another bug:

```
ERROR: Error computing the main repository mapping: Label '@@platforms//host:extension.bzl' is invalid because 'host' is not a package; perhaps you meant to put the colon here: '@@platforms//:host/extension.bzl'?
```

first bad commit is https://github.com/bazelbuild/bazel/commit/74c8ca4886cfc188d60a18e796743e842f675842

But this is incorrect I think.

**Comment by gergelyfabian** [comment]
Can be reproduced with 8.0.0rc2

**Comment by fmeum** [comment]
Could you check what happens if you manually add a recent version of `rules_cc` to the top of WORKSPACE?

**Comment by gergelyfabian** [comment]
Sure thing. I was just thinking about that in fact.

**Comment by gergelyfabian** [comment]
It seems rules_scala is including the following rules_cc version in my case:

```
$ bazel query --output=build //external:rules_cc
Starting local Bazel server and connecting to it...
# /home/user/Work/traveltime-platform/WORKSPACE:66:18
http_archive(
  name = "rules_cc",
  generator_name = "",
  generator_function = "rules_scala_setup",
  urls = ["https://github.com/bazelbuild/rules_cc/releases/download/0.0.6/rules_cc-0.0.6.tar.gz"],
  sha256 = "3d9e271e2876ba42e114c9b9bc51454e379cbf0ec9ef9d40e2ae4cec61a31b40",
  strip_prefix = "rules_cc-0.0.6",
)
# Rule rules_cc instantiated at (most recent call last):
#   /home/user/Work/my-projest/WORKSPACE:66:18                                                                                                  in <toplevel>
#   /home/user/.cache/bazel/_bazel_user/7f83a0b1f0940f88aec1f4530f927169/external/io_bazel_rules_scala/scala/private/macros/scala_repositories.bzl:96:21 in rules_scala_setup
# Rule http_archive defined at (most recent call last):
#   /home/user/.cache/bazel/_bazel_user/7f83a0b1f0940f88aec1f4530f927169/external/bazel_tools/tools/build_defs/repo/http.bzl:387:31 in <toplevel>
```

**Comment by fmeum** [comment]
That's too old. Without Bzlmod, it's next to impossible for Bazel to force newer versions of ruleset repos, so I would consider this (unfortunately) WAI and a reminder of what Bzlmod will get us.

**Comment by gergelyfabian** [comment]
Managed to make the issue go away with:

```
http_archive(
    name = "rules_cc",
    urls = ["https://github.com/bazelbuild/rules_cc/releases/download/0.0.12/rules_cc-0.0.12.tar.gz"],
    sha256 = "b26168b9a13f094794982b832975eaf53cefc5dced5b3be7df6b8b794dc2744b",
    strip_prefix = "rules_cc-0.0.12",
)
```

With `0.0.13` there is a different error though, missing `@@protobuf` , however I think using 0.0.12 could be a good workaround (I checked different versions, 0.0.10 doesn't work, 0.0.11 and 0.0.12 work).

**Comment by gergelyfabian** [comment]
Probably rules_scala would need a rules_cc upgrade to 0.0.12.

**Comment by gergelyfabian** [comment]
> That's too old. Without Bzlmod, it's next to impossible for Bazel to force newer versions of ruleset repos, so I would consider this (unfortunately) WAI and a reminder of what Bzlmod will give us.

Probably yes, in any case thanks a lot for your help on this one!

**Comment by gergelyfabian** [comment]
The above issue goes away with rules_cc 0.0.13 (starting from 0.0.11).

I have a different error then:

```
ERROR: /home/user/opt/bazel-scala-example/example-lib/BUILD:13:13: //example-lib:hello-world: no such attribute 'srcs' in 'java_library' rule
ERROR: /home/user/opt/bazel-scala-example/example-lib/BUILD:18:10: //example-lib:java_test: no such attribute 'test_class' in 'java_test' rule
ERROR: /home/user/opt/bazel-scala-example/example-lib/BUILD:18:10: //example-lib:java_test: no such attribute 'srcs' in 'java_test' rule
ERROR: /home/user/opt/bazel-scala-example/example-lib/BUILD:18:10: //example-lib:java_test: no such attribute 'deps' in 'java_test' rule
```

**Comment by gergelyfabian** [comment]
Updated my https://github.com/gergelyfabian/bazel-scala-example/tree/bazel-8.0.0rc1 branch.

**Comment by fmeum** [comment]
Does this go away if you add a dep on rules_java? Is there a warning about autoload failing?

**Comment by gergelyfabian** [comment]
There is a direct dependency on rules_java already:

```
http_archive(
    name = "rules_java",
    sha256 = "a9690bc00c538246880d5c83c233e4deb83fe885f54c21bb445eb8116a180b83",
    urls = [
        "https://github.com/bazelbuild/rules_java/releases/download/7.12.2/rules_java-7.12.2.tar.gz",
    ],
)
```

Upgrading to latest rules_java does not solve it.

But I have:

```
bazel build //...
INFO: Invocation ID: 1e7fce0e-ccc5-48b9-8da9-6964f6c21c5c
WARNING: WORKSPACE support will be removed in Bazel 9 (late 2025), please migrate to Bzlmod, see https://bazel.build/external/migration.
ERROR: /home/user/opt/bazel-scala-example/example-lib/BUILD:13:13: //example-lib:hello-world: no such attribute 'srcs' in 'java_library' rule
ERROR: /home/user/opt/bazel-scala-example/example-lib/BUILD:18:10: //example-lib:java_test: no such attribute 'test_class' in 'java_test' rule
ERROR: /home/user/opt/bazel-scala-example/example-lib/BUILD:18:10: //example-lib:java_test: no such attribute 'srcs' in 'java_test' rule
ERROR: /home/user/opt/bazel-scala-example/example-lib/BUILD:18:10: //example-lib:java_test: no such attribute 'deps' in 'java_test' rule
ERROR: package contains errors: example-lib
ERROR: package contains errors: example-lib: //example-lib:hello-world: no such attribute 'srcs' in 'java_library' rule
ERROR: Skipping '//...': Error evaluating '//...': error loading package 'example-lib': Package 'example-lib' contains errors
ERROR: Error evaluating '//...': error loading package 'example-lib': Package 'example-lib' contains errors
INFO: Elapsed time: 0.646s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
ERROR: Couldn't start the build. Unable to run tests
```

**Comment by fmeum** [comment]
@meteorcloudy @comius It looks like autoload may not work correctly without Bzlmod enabled.

**Comment by gergelyfabian** [comment]
Should we open a new issue for that?

**Comment by meteorcloudy** [comment]
Yes, that would be better. @comius is already looking into the WORKSPACE use case.

**Comment by gergelyfabian** [comment]
> Yes, that would be better. @comius is already looking into the WORKSPACE use case.

Sure, did just that. Opened #24235. Closing this issue.

Probably we need an issue for rules_scala to upgrade rules_cc there.
