### ISSUE TITLE
[7.4.0] rules_java `7.12.1` (w/ java_tools `v13.9`)

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23894]
Forked from #23811

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`MODULE.bazel`
`MODULE.bazel.lock`
`src/MODULE.tools`
`src/test/shell/integration/discard_graph_edges_test.sh`
`src/test/tools/bzlmod/MODULE.bazel.lock`
`workspace_deps.bzl`

cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
@hvadehra is this important for 7.4.0?

**Comment by hvadehra** [comment]
> @hvadehra is this important for 7.4.0?

Not critical afaict
