### ISSUE TITLE
Bazel build fails from within Xcode script

### ISSUE THREAD

**Issue by paramr** [bazelbuild/bazel#2390]
### Description of the problem / feature request / question:

I call bazel build to generate C++ grpc stubs from Xcode.  This is giving errors like:

____Loading package: third_party/rocksdb
____Loading...
____Loading package: @bazel_tools//tools/cpp
____Loading package: @local_jdk//
WARNING: /private/var/tmp/_bazel_param/ee4f61b0d859cceab50e7189568e55f2/external/bazel_tools/tools/osx/xcode_configure.bzl:98:5: Invoking xcode-locator failed, return code 256, stderr: java.io.IOException: Cannot run program "/private/var/tmp/_bazel_param/ee4f61b0d859cceab50e7189568e55f2/external/local_config_xcode/./xcode-locator-bin" (in directory "/private/var/tmp/_bazel_param/ee4f61b0d859cceab50e7189568e55f2/external/local_config_xcode"): error=2, No such file or directory.

Happens on and off with command line too.

bazel shutdown fixed running from command line.

### Environment info
* Operating System:
Mac: 10.12.2
Xcode:  8.2.1 (8C1002)

* Bazel version (output of `bazel info release`):
release 0.4.0-homebrew

**Comment by laszlocsomor** [comment]
Thanks for the report! Could you try a newer Bazel version (0.4.3) and tell us if the problem manifests with that too?

@c-parsons : FYI

**Comment by mhlopko** [comment]
Closing for the lack of info. Feel free to comment to reopen.
