### ISSUE TITLE
docker_build rules reports as `docker_build_` in `--output location`

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/bazel#2392]
In bazel 0.4.3, when `//path/to:some_docker_thing` is a `docker_build` rule,

    bazel query //path/to:some_docker_thing --output location

will report that the target is a `docker_build_ rule` (notice the trailing `_`).

This makes it a little bit of bummer for tooling around things. Would be nice to get that trailing `_` removed.

**Comment by laszlocsomor** [comment]
This is working as intended: `bazel_build` is a macro that wraps the `bazel_build_` rule [1].
Look for the `generator_function` in `bazel query`'s output to get at the unprocessed name.
```
$ bazel query tools/build_defs/docker/testdata:dummy_repository --output=build
...........
# (redacted)/gitroot/bazel/tools/build_defs/docker/testdata/BUILD:22:1
docker_build_(
  name = "dummy_repository",
  generator_name = "dummy_repository",
  generator_function = "docker_build",
  generator_location = "tools/build_defs/docker/testdata/BUILD:22",
  files = ["//tools/build_defs/docker/testdata:foo"],
  repository = "gcr.io/dummy",
)
```

[1] https://github.com/bazelbuild/bazel/blob/c484f19a2cf7427887d6e4c71c8534806e1ba83e/tools/build_defs/docker/docker.bzl#L533 and https://github.com/bazelbuild/bazel/blob/c484f19a2cf7427887d6e4c71c8534806e1ba83e/tools/build_defs/docker/docker.bzl#L569
