### ISSUE TITLE
[Mirror] Gazelle 0.39.1

### ISSUE THREAD

**Issue by mbarr-hrp** [bazelbuild/bazel#23948]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.39.1/bazel-gazelle-v0.39.1.tar.gz

**Comment by mbarr-hrp** [comment]
(Sorry, not actually part of the project, but a user.  Looks like this was a patch release, and the mirror request wasn't made.)

**Comment by satyanandak** [comment]
Here you go
https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.39.1/bazel-gazelle-v0.39.1.tar.gz
