### ISSUE TITLE
[bazel.build] Problem with /rules/lib/core/string

### ISSUE THREAD

**Issue by Javierxg15** [bazelbuild/bazel#23949]
### Page link:

https://bazel.build/rules/lib/core/string

### Where do you see this issue? (include link to specific section of the page, if applicable)

https://bazel.build/rules/lib/core/string.html?hl=es-419

**Comment by sgowroji** [comment]
@Javierxg15  We are closing this issue since it doesn't have valid details. Please tag `@bazelbuild/triage` if you have any questions or want this reopened.
