### ISSUE TITLE
sandbox should create regular empty files rather than symlinking to /dev/null

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#2394]
`Runfiles` may have an `EmptyFileSupplier` instance that can add empty files to the runfiles tree. `build-runfiles` creates regular empty files for paths added by the supplier. The sandbox code, however, creates symlinks to `/dev/null` for such paths. This means the empty files in the sandbox dereference to character devices not genuine files. For two reasons, I believe the sandbox code should create regular empty files, too:
1. It's an inconsistency between standalone and sandbox mode.
2. The only (public) use for `EmptyFilesSupplier` is adding `__init__.py` to make Python packages. (C)Python 2 is okay with `__init__.py` being a character device, but Python 3 is not. Moreover, other Python implementations and tools that do not exactly replicate CPython's arcane import behavior are generally confused by `__init__.py` being a character device.

**Comment by laszlocsomor** [comment]
@hermione521 : Could you please triage this, and assign a priority?

**Comment by hermione521** [comment]
This looks reasonable. Let's confirm with @philwo

**Comment by philwo** [comment]
Yes, this is in important issue. Sorry that it hasn't been fixed earlier!

I'm working on it now, fix should be in tomorrow.

**Comment by philwo** [comment]
A fix for this is now (finally) in code review. Sorry that it took so long.
