### ISSUE TITLE
[7.4.0] Fix version resolution in `AutoloadSymbols`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23950]
Forked from #23936

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/packages/AutoloadSymbols.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `src/main/java/com/google/devtools/build/lib/packages/AutoloadSymbols.java`
> 
> cc: @bazelbuild/triage

cc: @comius @fmeum @cushon @meteorcloudy
