### ISSUE TITLE
bazel cannot extract itself on Windows

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2396]
Earliest appearance:
http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-x86_64/490/
```
Extracting Bazel installation...
Error: install base directory 'c:\bazel_ci\temp/_bazel_SYSTEM/install/d3ae36cdaef1dde05263c26afe8c093f.tmp.6588' could not be renamed into place: Permission denied
```
/cc @laszlocsomor

**Comment by laszlocsomor** [comment]
:(
Duplicate of https://github.com/bazelbuild/bazel/issues/2386
Reopening that.
