### ISSUE TITLE
Extract blog and marketing pages to a different repo, move docs to docs.bazel.build

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#2397]
The entire content of the https://bazel.build website is store in the `bazelbuild/bazel` repo (see https://github.com/bazelbuild/bazel/tree/master/site).

Ideally things like blog posts or "marketing" landing page should be de-coupled from the main bazel code. Documentation should stay in the `bazelbuild/bazel` repo since we want it to be coupled to the current state of the code.

What we should do is:

* [x] Move everything related to the website (blog, landing page and other pages outside of the Docs section) in its own repo (probably `bazelbuild/bazel-website`)
* [ ] Serve https://bazel.build from the content of `bazelbuild/bazel-website`.
* [ ] Serve the Bazel documentation (tutorials, reference and concepts) at https://docs.bazel.build, from the documentation in `bazelbuild/bazel`
* [ ] Update instructions about how to runt he documentation

**Comment by steren** [comment]
FYI @davidzchen

**Comment by davidzchen** [comment]
SGTM. This would also make the setup for the site easier to understand, and would also simplify implementing versioned docs.

**Comment by steren** [comment]
We created https://github.com/bazelbuild/bazel-website and moved the marketing content to it.
We also created https://github.com/bazelbuild/bazel-blog and moved the blog content to it.

@davidzchen will now take care of the deployment pipeline.

In the end, we will have:

* bazel.build serving bazel-website
* docs.bazel.build serving the docs from the bazel repo
* blog.bazel.build serving bazel-blog

**Comment by steren** [comment]
We actually also need to explain how to serve the documentation locally. I could not find instructions.

**Comment by steren** [comment]
I think all of this is done
