### ISSUE TITLE
Leading '$' in docs command line snippets are interfering with copy/paste

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#2399]
When following the Bazel tutorial, it is very hard to copy paste the command line snippets due to the leading '$', which should not be pasted.

It should either not be selectable or not shown at all.

Google Cloud Platform docs decided to not display them. See [example](https://cloud.google.com/appengine/docs/go/quickstart). I would suggest to take the same approach.

**Comment by laszlocsomor** [comment]
@steren : If you have free cycles, could you maybe update the docs?

**Comment by steren** [comment]
Sure will do.

**Comment by royalharsh** [comment]
It would be great if anyone could review this: https://bazel-review.googlesource.com/#/c/9610/
