### ISSUE TITLE
Garbage in new_step output.

### ISSUE THREAD

**Issue by tfarina** [bazelbuild/bazel#240]
I'm seeing some garbage in the output messages of new_step. It is a square with 01F 343. Sorry, I could not copy that here.

**Comment by damienmg** [comment]
It's a UTF-8 Leaves for Bazel :)

**Comment by damienmg** [comment]
🍃  Building Bazel tools...
🍃  Determinism test...
🍃  Running tests.

**Comment by kchodorow** [comment]
We should disable for non-OS X builds, I think.  Or maybe do some terminal detection, if we want to be fancy.

**Comment by damienmg** [comment]
It works under last ubuntu. We should probably do some detection indeed.

**Comment by tfarina** [comment]
Does it make a difference if running under a ssh session?

**Comment by damienmg** [comment]
I have no problem in SSH session but it depends on wether your terminal
support displaying it and sometime SSH ttys are a bit messed up so it can

On Thu, Jun 11, 2015 at 5:32 PM Thiago Farina <notifications@github.com>
wrote:

> Does it make a difference if running under a ssh session?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/bazel/issues/240#issuecomment-111174579>.
>
-- 
Damien

**Comment by davidzchen** [comment]
It would be great to do some detection.

That said, I love the new_step output. :)

**Comment by hanwen** [comment]
I declare this 'working as intended'.

I don't think you can detect whether a remote system can display a certain unicode codepoint, since you cannot access the terminal's rendering output.

Perhaps you can file a bug with whatever terminal emulator you are using? Or with your distribution, because they don't supply a font with the right emoji's?

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/19247
