### ISSUE TITLE
Usage of input file in top-level macro does not cause it to be implicitly declared

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#24007]
When ":input.txt" appears as in a label-typed attribute of a symbolic macro at the top-level (not inside another symbolic macro), we should implicitly declare an `InputFile` for it the way we do for rules. That's not happening right now.

Fix is to iterate over macros in `Package.Builder#beforeBuild`. Working on that and adding test coverage now.

This should be cherrypicked into 8.0 to fix symbolic macro semantics before release. Otherwise users need to workaround by writing additional `exports_files` declarations.

**Comment by brandjon** [comment]
@bazel-io fork 8.0.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 8.0.0 RC2](https://github.com/bazelbuild/bazel/releases/tag/8.0.0rc2). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=8.0.0rc2`. Thanks!
