### ISSUE TITLE
Bazel client, Windows: store MSYS root as wstring

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2400]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

Store the MSYS root as a wstring, not as a string. This has the benefit that we can use `GetEnvironmentVariableW` and have a long path for `BAZEL_SH`, and we don't have to convert that part of the path from string to wstring every time we want to convert a path for widechar WinAPI functions.

Also, we should first normalize the input path, only then join it with the MSYS root, as we now do. Currently it's possible to pass a path like "/../../foo" and that joined with the MSYS root then normalized would lead out of the MSYS root.

**Comment by dslomov** [comment]
This is either fixed or not really relevant anymore, isn't it?

**Comment by laszlocsomor** [comment]
It is relevant, we'll still have `BAZEL_SH` for a while.
BTW this is a simple code cleanup.

**Comment by laszlocsomor** [comment]
We'll stop releasing MSYS-ful versions of Bazel with 0.5.4 / 0.6.0 (whichever comes first), and afterwards remove support for MSYS paths (because MSYS-less Bazel always receives Windows paths, even when ran from under MSYS), which will make this code cleanup unnecessary.
