### ISSUE TITLE
[8.0.0] Consider invalid entries in the marker file reason for refetch Beta

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#24015]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/d62e0a0f32188e1875bb8e62ef4377ea4dc1aab2

### Category

team-ExternalDeps

### Reviewers

@Wyverald

**Comment by bazel-io** [comment]
Failed commits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/d62e0a0f32188e1875bb8e62ef4377ea4dc1aab2.
Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picking https://github.com/bazelbuild/bazel/commit/d62e0a0f32188e1875bb8e62ef4377ea4dc1aab2 as per https://github.com/bazelbuild/bazel/pull/23941. No need to cherry-pick https://github.com/bazelbuild/bazel/commit/c3393dace76aa7761978d90613695b955ed39977 as it's already included

**Comment by iancha1992** [comment]
cc: @Wyverald

**Comment by iancha1992** [comment]
Sorry. Never mind.
