### ISSUE TITLE
[Mirror] rules_cc 0.0.13

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#24013]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/rules_cc/releases/download/0.0.13/rules_cc-0.0.13.tar.gz

**Comment by satyanandak** [comment]
Here you go 
https://mirror.bazel.build/github.com/bazelbuild/rules_cc/releases/download/0.0.13/rules_cc-0.0.13.tar.gz
