### ISSUE TITLE
[Mirror] `java.manifest`

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#24028]
### Please list the URLs of the archives you'd like to mirror:

https://raw.githubusercontent.com/openjdk/jdk/refs/tags/jdk-21%2B35/src/java.base/windows/native/launcher/java.manifest

**Comment by satyanandak** [comment]
Here you go
https://mirror.bazel.build/raw.githubusercontent.com/openjdk/jdk/refs/tags/jdk-21+35/src/java.base/windows/native/launcher/java.manifest
