### ISSUE TITLE
Inconsistent cquery configuration output

### ISSUE THREAD

**Issue by moroten** [bazelbuild/bazel#24037]
### Description of the bug:

I get the following inconsistent output from `cquery`:
```
$ bazel shutdown
$ bazel cquery :some_tool 2>/dev/null
//tmp:some_tool (23f2fe8)
$ bazel cquery :packager 2>/dev/null
//tmp:packager (23f2fe8)
$ bazel cquery :some_tool 2>/dev/null
//tmp:some_tool (23f2fe8)
//tmp:some_tool (b8845d7)  <- THIS ONE IS NEW
```

I seems like `bazel cquery` is looking for my targets in all loaded configurations, not just the command line configuration. The exec config below is only there after the `bazel cquery :package` command.
```
$ bazel config 2>/dev/null
Available configurations:
23f2fe887fea893bcf15f486f42279fc7b8af18589122f17444d7418474d3596 k8-fastbuild
ab8cba103302292a2b1ba4f5816adc45d4e4bc4d1f3a0e0ddbfd94da0f3bd83b fastbuild-noconfig
b8845d7af429907895a44f71777a587e8041bc42fe623c8b32dade48a988de15 k8-opt-exec-ST-034a0f31d80e (exec)
```

### Which category does this issue belong to?

Configurability

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```Starlark
# BUILD.bazel
genrule(
    name = "some_tool",
    srcs = [
        ":foo.txt",  # a filegroup with multiple files in it ==> $(locations)
    ],
    outs = ["foo_copy.txt"],
    cmd = "cat $< > $@",
)

genrule(
    name = "packager",
    srcs = [
        ":foo.txt"
    ],
    outs = ["foo_package.txt"],
    tools = [":some_tool"],
    cmd = "cat $< > $@",
)
```

```shell
bazel shutdown
bazel cquery :some_tool 2>/dev/null
bazel cquery :packager 2>/dev/null
bazel cquery :some_tool 2>/dev/null
```

### Which operating system are you running Bazel on?

Ubuntu 22.04

### What is the output of `bazel info release`?

release 7.4.0rc2

### Have you found anything relevant by searching the web?

Could not find any earlier reported cquery issue about this when searching for [cquery config](https://github.com/bazelbuild/bazel/issues?page=3&q=is%3Aissue+cquery+config).

**Comment by moroten** [comment]
For people finding this ticket: To print only the target configuration labels once, use either `bazel cquery 'config(:some_tool, target)'` or `bazel cquery :some_tool --output=starlark --starlark:expr='"" if build_options(target)["//command_line_option:is exec configuration"] else target.label'`.

The commands above don't work around the underlying cause though.

**Comment by gregestren** [comment]
This is intentional behavior: see https://bazel.build/query/cquery#target-pattern-evaluation.

This is a limitation in the query language: labels alone aren't enough to uniquely defined build graph nodes. This interpretation helps more complex queries like `deps` produce intuitive results, and not accidentally miss valid deps by implicitly excluding configurations. 

Best practice with cquery is to use the `config()` function when you need a specific configuration, as you note above.
