### ISSUE TITLE
Remove link to bazelcon 2024 registration (event has passed)

### ISSUE THREAD

**Issue by clintonsteiner** [bazelbuild/bazel#24049]
### Page link:

https://bazel.build/contribute/

### Problem description (include actual vs expected text, if applicable):

Bazelcon registration is live is still the banner in this doc

### Where do you see this issue? (include link to specific section of the page, if applicable)

In the heading

### Any other information you'd like to share?

Tried to find how to fix this, but think its hidden somewhere in the _button config?
Would love to have this explained if anyone is willing

**Comment by meisterT** [comment]
It's unfortunately in an internal configuration file. I will fix it. Thanks for flagging!

**Comment by clintonsteiner** [comment]
Looks like you fixed it. Thanks!
