### ISSUE TITLE
`zip: command not found` failing tests

### ISSUE THREAD

**Issue by freeform-andre** [bazelbuild/bazel#24056]
### Description of the bug:

Tests which use `TEST_UNDECLARED_OUTPUTS_DIR` are failing with the following after upgrading to Bazel 7.4.0
```
external/bazel_tools/tools/test/test-setup.sh: line 428: zip: command not found
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Uninstall the `zip` program from your linux worker and run a test which uses `TEST_UNDECLARED_OUTPUTS_DIR`.

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

release 7.4.0

### If this is a regression, please try to identify the Bazel commit where the bug was introduced with bazelisk --bisect.

Tests pass in `7.3.2`

**Comment by fmeum** [comment]
Did you upgrade from 7.3.2? The only change to the script since then seems to be https://github.com/bazelbuild/bazel/commit/7a183118187a8a799f2c23d935d3330e33527604, which can't really be the cause of the regression.

Since zipping up the outputs has always required `zip`, are you disabling zipping in your `.bazelrc`?

**Comment by freeform-andre** [comment]
> Did you upgrade from 7.3.2?

Yeah

> Since zipping up the outputs has always required `zip`, are you disabling zipping in your `.bazelrc`?

Users will occasionally use `--nozip_undeclared_test_outputs` but otherwise the the default is being used.

**Comment by tjgq** [comment]
I consider this WAI: it has always been the case that an external `zip` tool must be available in the `PATH` when using `--zip_undeclared_outputs`. I don't have a theory for why it started failing in 7.4.0; you could run a `bazelisk --bisect` if you're curious enough to track it down. The default is going to change to no zipping in 8.0.0.

**Comment by jwnimmer-tri** [comment]
> I don't have a theory for why it started failing in 7.4.0; ...

See #23479.  In recent bazel versions < 7.4, when zip was missing, bazel did not report a failure to user but instead just deleted all of the undeclared outputs.  (IIRC in 2023 and earlier, when zip was missing it just didn't zip, but kept them around.)

In any case, it sounds like this will be moot for >= 8.

**Comment by tjgq** [comment]
Thanks @jwnimmer-tri for identifying the cause! Somewhat embarrassingly, I was the one who fixed that issue, but had no memory of it :)
