### ISSUE TITLE
Symbolic macro attribute inheritance

### ISSUE THREAD

**Issue by tetromino** [bazelbuild/bazel#24066]
We want to allow symbolic macros to inherit attributes from a given rule, a given symbolic macro, or the set of [common](https://bazel.build/reference/be/common-definitions) attributes for Starlark rules, Starlark *_test rules, or Starlark *_binary rules. And we'd want the ability to remove or override inherited attributes.

Motivation:
* make it easier to wrap a rule (or macro) in another macro without needing to copy-paste the list of attributes
* if Bazel adds a new common Starlark rule attribute, many rule-wrapping macros would want to be able to use it immediately, without needing to be explicitly updated
* replicate the common **kwargs pattern seen in legacy macros, where the attributes that the macro doesn't explicitly care about are passed unchanged down to the macro's main target.

The last point, in particular, would make it *vastly* easier to migrate legacy macros to symbolic.

----

I'm thinking of syntax along the following lines:

```bzl
my_cc_library = macro(
    # inherit native.cc_library's attributes
    # alternatively: inherit_attrs = "common", "test", or "binary" to inherit the common attributes of
    # all Starlark rules, Starlark test rules, or Starlark binary rules respectively.
    inherit_attrs = native.cc_library,
    # remove cxxopts from inherited attrs list (so callers of my_cc_library cannot set it)
    no_inherit_attrs = ["cxxopts"],
    attrs = {
        # override/redefine the inherited copts attribute
        "copts": attr.string_list(...),
    },
    ...
)
```

`inherit_attrs` can take either a rule or macro symbol, or the special string constants `"common"`, `"test"`, or `"binary"` to indicate the set of attributes common to all Starlark rules, Starlark test rules, or Starlark binary rules respectively (see https://bazel.build/reference/be/common-definitions).

Specifically, the algorithm is as follows:
* remove the special `name` and `visibility` attributes from the inherited list, since symbolic macros auto-inject them
* remove private (prefixed with `"_"`) attributes, since the macro cannot pass them to the wrapped rule
* remove computed defaults and late-bound attributes, since macros cannot use them
* remove attributes whose names are listed in `no_inherit_attrs`
* combine with `attrs` dict, with `attrs` taking precedence

@brandjon @susinmotion FYI

**Comment by brandjon** [comment]
Note that `inherit_attrs` should also work for inheriting from other symbolic macros, not just rules. And with @comius's designs about parent rules, the name may also need to be applicable for rules inheriting from other rules for API consistency.

**Comment by tetromino** [comment]
@brandjon -

> Instead of `no_inherit_attrs = ["cxxopts"]`, how about `attrs = {"cxxopts": None}`? This would generalize the "shadow this attr with my own" use case to also support the "don't allow this attr at all" use case.

For consistency, I'd prefer to keep the shape of the `attrs` dict compatible between `macro()` and `rule()`.

> Alternatively, don't support that at all, and require the rule author to fail if "cxxopts" is a key of **kwargs. Honestly, that seems more minimalist and safer than adding a new None value type to attrs. Do we have evidence that this use case is common? Can we afford to punt on it?

An internal user explicitly requested a way to hide attributes.

Marking attributes as illegal via implementation `fail` is bad for readability (we want a macro to be described by the `macro()` declararation, not by the implementation function), IDE code completion, and Stardoc-generated docs introspection.

> What would the syntax be for inheriting common attrs (of all rules, test rules, or binary rules) without inheriting the specific attrs added by any particular rule?

Good question! My plan was to use special string constants - e.g. `"common"`, `"test"`, and `"binary"`. Will update the design above.

> I'm also worried that the idea of common attrs as documented in the Build Encyclopedia might be a fiction -- it's assembled from some seemingly manually curated template content, rather than extracted from a source of truth in code. So there may in fact be many more than three particular sets of predeclared rule attrs. Also the attrs for e.g. native binary rules and starlark binary rules may be subtly different. All of this is to say that perhaps we shouldn't yet support this use case, and instead require the user to name a particular rule.

Good question! And the answer, I think, is to explicitly state that  `"common"`, `"test"`, and `"binary"` refer to common attributes of *Starlark rules*. Starlark rule common attributes do have a common source of truth, while native rule common attributes more-or-less coincide with them by coincidence :)

**Comment by tetromino** [comment]
> Instead of `no_inherit_attrs = ["cxxopts"]`, how about `attrs = {"cxxopts": None}`? This would generalize the "shadow this attr with my own" use case to also support the "don't allow this attr at all" use case.

@brandjon - good idea, I agree (as discussed offline).

**Comment by tetromino** [comment]
@bazel-io fork 8.0.0

**Comment by tetromino** [comment]
@bazel-io fork 8.0.0

**Comment by brandjon** [comment]
@tetromino Any reason not to close this issue?
