### ISSUE TITLE
[bazel.build] Problem with /rules/lib/builtins/Subrule: Mention AEG specifically

### ISSUE THREAD

**Issue by jacky8hyf** [bazelbuild/bazel#24067]
### Page link:

https://bazel.build/rules/lib/builtins/Subrule

### Problem description (include actual vs expected text, if applicable):

Fuzzy error message when I try to use toolchains within a subrule:

"Error: subrules using toolchains must enable automatic exec-groups"

Presumably it is a requirement to enable AEG by setting `--incompatible_auto_exec_groups` or `_use_auto_exec_groups` in the rule(), but this requirement is not stated in the document.

**Comment by kotlaja** [comment]
Thanks for raising this issue! Fix is under way. In the meanwhile, for the migration to Automatic Exec Groups (AEGs), please check https://bazel.build/extending/auto-exec-groups#migration-aegs.

**Comment by meteorcloudy** [comment]
@bazel-io fork 8.0.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 8.0.0 RC2](https://github.com/bazelbuild/bazel/releases/tag/8.0.0rc2). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=8.0.0rc2`. Thanks!
