### ISSUE TITLE
bazel run doesn't respect the `--bazelrc` file contents

### ISSUE THREAD

**Issue by tjoneslo** [bazelbuild/bazel#24096]
### Description of the bug:

When running `bazel --bazelrc=./temprc run --config=tidy //:command` where the config (tidy) is in the `tmprc` file, bazel can't seem to find it and it fails with an error message. 

ERROR: Config value 'tidy' is not defined in any .rc file

### Which category does this issue belong to?

Core

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

echo "common:tidy -- show_progress" > tmprc
bazel --bazelrc=./tmprc run --config=tidy //:target

get the error message:
ERROR: Config value 'tidy' is not defined in any .rc file

### Which operating system are you running Bazel on?

MacOS

### What is the output of `bazel info release`?

release 7.3.1

### Have you found anything relevant by searching the web?

No

**Comment by soul-coder-heap** [comment]
The files tmprc and temprc are different. Are you sure there’s no mistake?

**Comment by soul-coder-heap** [comment]
![image](https://github.com/user-attachments/assets/de0bd1df-9da2-4c48-80c0-44feb484eb60)

**Comment by tjoneslo** [comment]
This is, as pointed out, a user error. Not a bazel bug. Sorry for the noise.
