### ISSUE TITLE
[8.0.0] Make bazel_tools work again

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#24116]
Forked from #24094

**Comment by Wyverald** [comment]
cherry-pick in https://github.com/bazelbuild/bazel/pull/24109

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/MODULE.tools`
`src/test/tools/bzlmod/MODULE.bazel.lock`
`src/test/tools/bzlmod/verify_default_lock_file.sh`

cc: @bazelbuild/triage
