### ISSUE TITLE
[Mirror] missing Bazel deps

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#24137]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/abseil/abseil-cpp/releases/download/20240116.1/abseil-cpp-20240116.1.tar.gz
https://github.com/bazel-contrib/bazel_features/releases/download/v1.18.0/bazel_features-v1.18.0.tar.gz
https://github.com/open-source-parsers/jsoncpp/archive/refs/tags/1.9.5.tar.gz
https://github.com/google/re2/releases/download/2023-09-01/re2-2023-09-01.zip
https://github.com/bazelbuild/rules_android/archive/refs/tags/v0.1.1.tar.gz 
https://github.com/bazelbuild/rules_jvm_external/releases/download/6.3/rules_jvm_external-6.3.tar.gz
https://github.com/indygreg/python-build-standalone/releases/download/20240726/cpython-3.11.9+20240726-aarch64-apple-darwin-install_only.tar.gz
https://github.com/protocolbuffers/protobuf/archive/refs/tags/v27.0.zip

**Comment by satyanandak** [comment]
Here you go
https://mirror.bazel.build/github.com/abseil/abseil-cpp/releases/download/20240116.1/abseil-cpp-20240116.1.tar.gz
https://mirror.bazel.build/github.com/bazel-contrib/bazel_features/releases/download/v1.18.0/bazel_features-v1.18.0.tar.gz
https://mirror.bazel.build/github.com/open-source-parsers/jsoncpp/archive/refs/tags/1.9.5.tar.gz
https://mirror.bazel.build/github.com/google/re2/releases/download/2023-09-01/re2-2023-09-01.zip
https://mirror.bazel.build/github.com/bazelbuild/rules_android/archive/refs/tags/v0.1.1.tar.gz
https://mirror.bazel.build/github.com/bazelbuild/rules_jvm_external/releases/download/6.3/rules_jvm_external-6.3.tar.gz
https://mirror.bazel.build/github.com/indygreg/python-build-standalone/releases/download/20240726/cpython-3.11.9+20240726-aarch64-apple-darwin-install_only.tar.gz
https://mirror.bazel.build/github.com/protocolbuffers/protobuf/archive/refs/tags/v27.0.zip
