### ISSUE TITLE
ijar / hjar producing incorrect Java 21 exhaustive switch statement errors

### ISSUE THREAD

**Issue by fzakaria** [bazelbuild/bazel#24138]
### Description of the bug:

I have a very weird bug which I've created a very small reproduction at [this repo](https://github.com/fzakaria/bazel-reproduction-playground/commit/16e1774e663c153a4854115f1d80ac60c1baf8de)

In essence, I have a library with a single class:
```java
public class Sealed {
    public sealed interface Error {
        record UserNotFound(String userName) implements Error { }
        record OtherError(Throwable cause) implements Error { }
    }
}
```

I have another library which uses it.
```java
public class Test {
    public static void handleError(Sealed.Error error) {
        switch (error) {
            case Sealed.Error.UserNotFound userNotFound ->
                    System.out.println("User not found: " + userNotFound.userName());
            case Sealed.Error.OtherError otherError ->
                    System.out.println("An error occurred: " + otherError.cause().getMessage());
        }
    }
}
```

Here is the minimal _BUILD_ file
```starlark
load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "sealed",
    srcs = [
        "src/Sealed.java",
    ],
)

java_library(
    name = "test",
    srcs = [
        "src/Test.java",
    ],
    deps = [
        ":sealed",
    ],
)
```

This produces the following error:

```console
> bazel build //:test
INFO: Invocation ID: 0ae940e9-a6ef-431e-b626-c57b3be9a722
INFO: Analyzed target //:test (0 packages loaded, 0 targets configured).
ERROR: /Users/fzakaria/code/playground/bazel/java-21-switch/BUILD.bazel:24:13: Building libtest.jar (1 source file) failed: (Exit 1): java failed: error executing Javac command (from target //:test) external/rules_java~~toolchains~remotejdk21_macos_aarch64/bin/java '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 19 arguments skipped)
src/Test.java:4: error: the switch statement does not cover all possible input values
        switch (error) {
```

If however I change `//:sealed` to be a `java_export` from [contrib_rules_jvm](https://github.com/bazel-contrib/rules_jvm)
```starlark
load("@contrib_rules_jvm//java:defs.bzl", "java_export")

java_export(
    name = "sealed",
    srcs = [
        "src/Sealed.java",
    ],
    maven_coordinates = "abc:abc:1.0.0",
    tags = [
        "no-javadocs",
    ],
)

java_library(
    name = "test",
    srcs = [
        "src/Test.java",
    ],
    deps = [
        ":sealed",
    ],
)
```

The build completes **successfully**
```console
> bazel build //:test
INFO: Invocation ID: deb880ca-396e-414f-98f9-fbdee97a0712
INFO: Analyzed target //:test (0 packages loaded, 6 targets configured).
INFO: Found 1 target...
Target //:test up-to-date:
  bazel-bin/libtest.jar
INFO: Elapsed time: 0.116s, Critical Path: 0.01s
INFO: 2 processes: 1 disk cache hit, 1 internal.
INFO: Build completed successfully, 2 total actions
```

We noticed that compiling ourselves against the `ijar` or `hjar` (unsure the distinction between the two causes the failure)
This leads me to believe that important information is being stripped out.

```
# succeeds
> bazel-java-21-switch/external/rules_java~~toolchains~remotejdk21_macos_aarch64/bin/javac src/Test.java -cp bazel-bin/libsealed.jar

# fails
> bazel-java-21-switch/external/rules_java~~toolchains~remotejdk21_macos_aarch64/bin/javac src/Test.java -cp bazel-bin/libsealed-hjar.jar
src/Test.java:4: error: the switch statement does not cover all possible input values
        switch (error) {
        ^
1 error
```

### Which category does this issue belong to?

Java Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Please see [this repo](https://github.com/fzakaria/bazel-reproduction-playground/commit/16e1774e663c153a4854115f1d80ac60c1baf8de)

### Which operating system are you running Bazel on?

MacOS

### What is the output of `bazel info release`?

release 7.4.0

### Have you found anything relevant by searching the web?

No.

**Comment by fmeum** [comment]
@cushon

**Comment by fzakaria** [comment]
@cushon or @fmeum looks like `java_export` ends up creating an `ijar` instead which does work.

```console
> bazel-java-21-switch/external/rules_java~~toolchains~remotejdk21_macos_aarch64/bin/javac src/Test.java -cp bazel-bin/sealed-project-ijar.jar
```

This is interesting since my understanding was `ijar` doesn't support "newer Java runtime bytecode".
Is there something I can read about this; and should contrib_rules_jvm use hjar instead?
(CC @shs96c )

**Comment by cushon** [comment]
> This is interesting since my understanding was `ijar` doesn't support "newer Java runtime bytecode"

ijar should support the latest bytecode features, do you remember where you saw that?

> should contrib_rules_jvm use hjar instead? (CC @shs96c )

It's probably worth considering, it should be faster.

**Comment by cushon** [comment]
This is fixed by 3ed6f3bf3a9fd8c4b07e53c43aaf2d68c3cbf1f4, but that needs to make it into a rules_java release.

@hvadehra do you want to leave this bug open to track that, or should I close it out?

**Comment by hvadehra** [comment]
`rules_java` `v8.3.0` has been released that includes this. I'm updating it in Bazel in https://github.com/bazelbuild/bazel/pull/24143.

**Comment by fzakaria** [comment]
Does that mean if we pin the newest `rules_java` we don't need to bump bazel ?

**Comment by hvadehra** [comment]
> Does that mean if we pin the newest rules_java we don't need to bump bazel ?

Yes
