### ISSUE TITLE
Unable to find Valid certification path to requested target

### ISSUE THREAD

**Issue by rishik1001** [bazelbuild/bazel#24140]
I have a personal system where this error is not produced, but when doing the same in my office system it's giving the certification error. How to resolve this ?

**Comment by iancha1992** [comment]
@rishik1001 Please file a bug report issue here: https://github.com/bazelbuild/bazel/issues/new?assignees=sgowroji%2Ciancha1992%2Csatyanandak&labels=type%3A+bug%2Cuntriaged&projects=&template=bug_report.yml

Thank you.
