### ISSUE TITLE
[7.4.1] downloader config from --experimental_downloader_config is cached in the server and requires shutdown to change

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#24167]
Forked from #24166

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistry.java`
`src/test/java/com/google/devtools/build/lib/bazel/bzlmod/FakeRegistry.java`

cc: @bazelbuild/triage

**Comment by meteorcloudy** [comment]
I'm taking a look

**Comment by meteorcloudy** [comment]
Cherry-picking at https://github.com/bazelbuild/bazel/pull/24228
