### ISSUE TITLE
[8.0.0] Remove JavaInfo and JavaPluginInfo providers

### ISSUE THREAD

**Issue by comius** [bazelbuild/bazel#24178]
### Description of the bug:

Having 2 copies of providers in Bazel and in rules_java repository is potentially problematic.

Version skew might make modifications to JavaInfo very difficult to impossible.

### Which category does this issue belong to?

Java Rules

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 8.0.0 RC3](https://github.com/bazelbuild/bazel/releases/tag/8.0.0rc3). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=8.0.0rc3. Thanks!
