### ISSUE TITLE
Bazel@HEAD on Darwin: //src/test/shell/bazel:bazel_java_test fails

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2417]
http://ci.bazel.io/view/Dashboard/job/bazel-tests/BAZEL_VERSION=HEAD-jdk7,PLATFORM_NAME=darwin-x86_64/512/consoleFull

Attempting to repro now.

**Comment by laszlocsomor** [comment]
Couldn't repro; we'll rerun on CI to see if it was a flake or not.

**Comment by laszlocsomor** [comment]
Could not repro manually.
Closing, assuming it was a flake.

**Comment by laszlocsomor** [comment]
This failed on Linux now: http://ci.bazel.io/view/Dashboard/job/bazel-tests/BAZEL_VERSION=HEAD-jdk7,PLATFORM_NAME=linux-x86_64/513/console

**Comment by laszlocsomor** [comment]
...and on http://ci.bazel.io/view/Dashboard/job/bazel-tests/BAZEL_VERSION=HEAD-jdk7,PLATFORM_NAME=darwin-x86_64/513/console again

**Comment by laszlocsomor** [comment]
@meteorcloudy : These tests are failing because BazelJavaBuilder doesn't recognize the `--manifest_file` flag. This seems to be related to https://github.com/bazelbuild/bazel/commit/d9a7d3a789be559bd6972208af21adae871d7a44 and AFAIU this shouldn't be happening. Any idea what's going on?

**Comment by meteorcloudy** [comment]
It should be fixed after this rollback 97e79cc5773835c199ff8eefd29379bc64ab59a4, let's watch the ci.
