### ISSUE TITLE
[Mirror] rules_python-0.34.0

### ISSUE THREAD

**Issue by hsharsha** [bazelbuild/bazel#24188]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/rules_python/releases/download/0.34.0/rules_python-0.34.0.tar.gz

**Comment by satyanandak** [comment]
Here you go
https://mirror.bazel.build/github.com/bazelbuild/rules_python/releases/download/0.34.0/rules_python-0.34.0.tar.gz
