### ISSUE TITLE
[8.0.0] Remove Python providers from Bazel

### ISSUE THREAD

**Issue by comius** [bazelbuild/bazel#24180]
### Description of the bug:

Having 2 copies of providers in Bazel and in rules_python repository is potentially problematic.

Version skew might make modifications difficult.

**Comment by iancha1992** [comment]
@bazel-io fork 8.0.0

**Comment by comius** [comment]
Blocked by https://github.com/bazelbuild/rules_python/issues/2414

**Comment by rickeylev** [comment]
rules_python 0.40.0 is released, which has the fix for https://github.com/bazelbuild/rules_python/issues/2414

**Comment by meteorcloudy** [comment]
Python providers removed in https://github.com/bazelbuild/bazel/pull/24408
