### ISSUE TITLE
bzlmod throws warning every build about importing extensions from direct dependency 

### ISSUE THREAD

**Issue by charleysaintNV** [bazelbuild/bazel#24191]
### Description of the bug:

I'm using bzlmod in a monorepo and trying to reduce duplication of code across many modules. I've created a shared module that uses rules_distroless to expose several debain packages to targets in these modules. To bring it into the module I call use repo on the apt repo's name. So in the shared module I have
```
apt = use_extension("@rules_distroless//apt:extensions.bzl", "apt")
apt.install(
    name = "bullseye",
    lock = ":bullseye.lock.json",
    manifest = ":bullseye.yaml",
)
```
then in the submodule I just have
```
bazel_dep(name="shared", version="0.0.0")
apt = use_extension("@rules_distroless//apt:extensions.bzl", "apt")
use_repo(apt, "bullseye")
```
This works fine but every time I run from the submodule I get a warning
```
The module extension apt defined in @rules_distroless//apt:extensions.bzl reported incorrect imports of repositories via use_repo():

Imported, but reported as indirect dependencies by the extension:
    bullseye

Fix the use_repo calls by running 'bazel mod tidy'.
```
If I run the bazel mod tidy it breaks my builds by deleting the use_repo from the MODULE.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Clone rules_distroless and add a module directive to and build the e2e/smoke module. Create another module that includes that creates the repos from e2e/smoke instead like so
```
module(name="shared", version="0.0.0")
bazel_dep(name = "rules_distroless", version = "0.0.0", dev_dependency = True)
local_path_override(
    module_name = "rules_distroless",
    path = "../..",
)

apt = use_extension("@rules_distroless//apt:extensions.bzl", "apt")
apt.install(
    name = "bullseye",
    lock = ":bullseye.lock.json",
    manifest = ":bullseye.yaml",
)
```
modify smoke module to remove the apt.install for bullseye and have a bazel_dep pointing to the new shared module. Should produce the warning when building targets in smoke.

**Comment by fmeum** [comment]
This warning is entirely controlled by the `@rules_distroless//apt:extensions.bzl` extensions use of `module_ctx.extension_metadata`, so I would suggest filing an issue with rules_distroless instead.

Generally speaking, modules are designed to be independent from each other and declare all their direct deps, so your use case doesn't quite fit the model that most extensions follow with respect to their usage of `extension_metadata`. You could try to share a module file segment via `include` instead of cutting out a separate module.
