### ISSUE TITLE
Docs do not mention Remote execution API, FAQ needs update.

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#2421]
A remote execution API is available in Bazel today.

Our FAQ question ["Does Bazel require a build cluster?"](https://bazel.build/faq.html#does-bazel-require-a-build-cluster) says "Bazel does have hooks in the code base to plug in [...] a remote execution system".
This should be updated to at least mention this API

The API design doc is supposed to be public, but we had troubles with sharing permissions. I'll update this issue when the doc is completely public.

A next step will be to document better this API.

**Comment by coeuvre** [comment]
We described the REAPI at https://bazel.build/remote/rbe.
