### ISSUE TITLE
[8.0.0] Cherry pick 764ba19ea5b935d7dd8b112a02dcbe05e4d9a5d5 to Bazel 8

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#24225]
### Commit IDs

764ba19ea5b935d7dd8b112a02dcbe05e4d9a5d5

### Category

team-Rules-API

### Reviewers

@comius

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/24226: https://github.com/bazelbuild/bazel/commit/764ba19ea5b935d7dd8b112a02dcbe05e4d9a5d5.
