### ISSUE TITLE
[7.4.1] Unable to execute `bazel info` without a module file

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#24254]
Forked from #24239

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/skyframe/SkyframeExecutor.java`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
@Wyverald @meteorcloudy do you want to do 7.4.1rc3 for this?

cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
It's not a regression, and not a high priority issue. Since the actual release is targeted for next Monday, I don't think we should include this.
