### ISSUE TITLE
Inconsistency in documentation: graph cycles

### ISSUE THREAD

**Issue by ivucica** [bazelbuild/bazel#2425]
### Description of the problem / feature request / question:

[`query` documentation](https://bazel.build/versions/master/docs/query.html) says dependency graphs "should" be acyclic.

> Build dependency graphs should be acyclic. The algorithms used by the query language are intended for use in acyclic graphs, but are robust against cycles. The details of how cycles are treated are not specified and should not be relied upon.

[Skylark rules documentation](https://bazel.build/versions/master/docs/skylark/rules.html) says it is an error to have cycles in the dependency graph:

> Dependencies are resolved by Bazel, which will decide which actions are executed. It is an error if there is a cycle in the dependency graph. Creating an action does not guarantee that it will be executed: It depends on whether its outputs are needed for the build.

Because there is an error thrown when there is a cycle, I would humbly suggest that the second quote is, in fact, correct, and the `query` documentation should be fixed.

I can submit a PR/CL if needed, but if someone can wordsmith this change better than me, that might be better.

**Comment by laszlocsomor** [comment]
IIRC there are some Google-internal rules that legitimately create a cyclic target graph by having [nodep_label-type attributes](https://github.com/bazelbuild/bazel/blob/96297ed7a9ab3df0f45e93bae9d71833f4195334/src/main/java/com/google/devtools/build/lib/packages/BuildType.java#L65), though it's translated to an acyclic configured-target-graph, so I'd say this information is simply confusing and irrelevant for public bazel.

Adding @vladmos for Skylark insight: can rules declare NODEP_LABEL-type attributes? Shall we document that target graph cycles are allowed under some specific circumstances?

**Comment by laszlocsomor** [comment]
Also, I'm not fully sure how such attributes are interpreted by the query engine. Let me try this quickly.

**Comment by laszlocsomor** [comment]
Forget what I said earlier, such attributes indeed not create a dependency edge, just tried with `query --output=graph`.

**Comment by alandonovan** [comment]
The `query` documentation is in fact correct. The explanation is that query builds a simple graph by blindly following dependency labels, treating each as a directed edge without regard to its quality. By contrast, `cquery` performs the analysis phase, which interprets each node (e.g. java_library) and edge (e.g. deps) according its particular semantics, and some of these semantics do not entail a true forward dependency.

For example, cc_public_library and cc_library rules may come in pairs in which each points to the other using a different kind of edge, one of which is logically a back edge. The graph constructed by the `query` command is not aware of such nuances.

As a benefit, the query tool can answer questions about graphs containing cycles that cause analysis to fail.
