### ISSUE TITLE
Windows: Poor performance when executing java rules that depend on many .jar (related: #2218)

### ISSUE THREAD

**Issue by rpaquay** [bazelbuild/bazel#2426]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

On Windows, executing external command from a bash script is much slower than on Linux.
Also on Windows, the default is to use RUNFILE_MANIFEST files.

These two things together make executing java rules much slower than necessary, because of the following code in java_stub_template.txt:

```
  function rlocation() {
    if [[ "$1" = /* ]]; then
      echo $1
    else
      echo $(grep "^$1 " $RUNFILES_MANIFEST_FILE | awk '{ print $2 }')
    fi
  }
```

For each invocation of "rlocation", which happen for each CLASSPATH entry, there are 3 (or 4 maybe?) processes executed: bash, grep and awk. It would be much better to do this in memory and avoid calling external processes.

### If possible, provide a minimal example to reproduce the problem:

I can't really share my project because it is big, but it is easy to reproduce with many java rules than all depend on many jar files. On my HP Z840 with 48 Cores, running bazel with such build files makes the machine totally unresponsive (even the mouse pointer is janky), even though there is plenty of memory available.

### Environment info
* Operating System:
Windows 10

* Bazel version (output of `bazel info release`):
0.4.3

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

No

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

I am about to upload a PR that will (mostly) address this issue.

**Comment by laszlocsomor** [comment]
Ouch, that's a really good catch. Thanks for reporting it!

In the long term we'd like to get rid of the shell script launcher in favor of a native c++ one instead, which would fix this problem Once And For All<sup>TM</sup>. See also https://github.com/bazelbuild/bazel/issues/2218.

**Comment by laszlocsomor** [comment]
@meteorcloudy : FYI

**Comment by meteorcloudy** [comment]
Thanks for @rpaquay , he already sent a PR to fix this! https://github.com/bazelbuild/bazel/pull/2427
And I am importing it!

**Comment by laszlocsomor** [comment]
Awesome, thanks both of you!

**Comment by dslomov** [comment]
Anything to fix after https://github.com/bazelbuild/bazel/commit/ae3ee253136fffe9767829694b45ec07e676b502?

**Comment by meteorcloudy** [comment]
No, this issue should be solved.
