### ISSUE TITLE
[Mirror] rules_shell 0.3.0

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#24274]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/rules_shell/releases/download/v0.3.0/rules_shell-v0.3.0.tar.gz

**Comment by sgowroji** [comment]
https://mirror.bazel.build/github.com/bazelbuild/rules_shell/releases/download/v0.3.0/rules_shell-v0.3.0.tar.gz
