### ISSUE TITLE
Cherrypick 3edda22913d1d42fb112c014fbb68f30993f5c18 into 8.0.0

### ISSUE THREAD

**Issue by ahumesky** [bazelbuild/bazel#24282]
### Commit IDs

3edda22913d1d42fb112c014fbb68f30993f5c18

### Category

team-Rules-Java

### Reviewers

@iancha1992 @keertk @comius

**Comment by Wyverald** [comment]
@iancha1992 the workflow failed, apparently because it tried to find a user called `iancha1992keertkcomius`: https://github.com/bazelbuild/bazel/actions/runs/11788618467/job/32836021079

I manually created the PR at https://github.com/bazelbuild/bazel/pull/24283.

**Comment by ahumesky** [comment]
Whoops, thanks for taking a look

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but failed to push. Please check if the branch, cp_ondemand_24282-8.0.0, already exists
cc: @bazelbuild/triage
