### ISSUE TITLE
Bazel@HEAD bazel-tests failing due to //scripts/release:release_test

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2429]
It's been broken at least since a676374f6988bee9c489588f95c0fa78c96d63d5. I haven't gone further into the past to find when it got broken.

**Comment by laszlocsomor** [comment]
@damienmg : Any ideas what could be going on?
Example log: http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/516/consoleFull

**Comment by damienmg** [comment]
grrr my fault

**Comment by laszlocsomor** [comment]
@damienmg : this isn't actually fixed yet, right?

**Comment by damienmg** [comment]
Yes well the ci failure is but I have to follow-up :)
