### ISSUE TITLE
Add option to write `bazel query` output directly to a file

### ISSUE THREAD

**Issue by keithl-stripe** [bazelbuild/bazel#24293]
### Description of the feature request:

Our repository contains about 700,000 targets. We use the output of `bazel query` to improve CI performance, by restricting the Bazel build to changed targets and their transitive dependencies (similar to [bazel-diff](https://github.com/Tinder/bazel-diff)).

Specifically, we run:

```
bazel query --output=streamed_proto //...
``` 

This produces a 6.8 GB file and takes (~cold):
- 16 seconds to download/unpack external repos
- 14 seconds to parse all the BUILD.bazel files
- 4 seconds to evaluate the query expression
- 1 minute, 35 seconds to render the protos to stdout

We'd like to speed up this last step, as it’s 74% of wall time.

Through Java profiling (via YourKit and Java Flight Recorder) we've noticed that Bazel spends a lot of CPU and wall time marshaling the query output to gRPC to send back to the Bazel client. This would be eliminated by writing directly to a file.

### Which category does this issue belong to?

Core, Performance

### What underlying problem are you trying to solve with this feature?

Improve `bazel query` performance when the output is destined for a file

### Which operating system are you running Bazel on?

Linux Ubuntu 24.04.1

### What is the output of `bazel info release`?

release 7.2.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 8.2.0 RC3](https://github.com/bazelbuild/bazel/releases/tag/8.2.0rc3). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=8.2.0rc3. Thanks!
