### ISSUE TITLE
bashunit tests are succeeding on OSX even in the presence of a syntax error

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#243]
bashunit use traps and apparently bash under OSX use the exit code of the commands in the trap as the error code of the shell script.

A simple case illustrating that is:

```
$ cat scripts/release/test.sh 
#!/bin/bash -eu
trap true EXIT
A=( () )
$  ./scripts/release/test.sh; echo $?
./scripts/release/test.sh: line 5: syntax error near unexpected token `('
0
```

It is probably a question of setting the good environment in Bash and we should at least have a workaround in bashunit.

**Comment by davidstanke** [comment]
@philwo Do you have a recommendation here?

**Comment by meisterT** [comment]
I don't have a Mac, is this still the case?
