### ISSUE TITLE
java_import_external generated //jar:jar target changed behavior in Bazel 7+

### ISSUE THREAD

**Issue by gkdn** [bazelbuild/bazel#24308]
### Description of the bug:

For given

```
java_import_external(name = "foo", generated_rule_name = "bar")
```

java_import_external used to create an alias for "foo". After https://github.com/bazelbuild/bazel/pull/19997, it started generating an alias for "bar".

As a result for java_import_external repositories that overrides default target by providing generated_rule_name (e.g. for annotation processors), the behavior for the jar target has changed.

### Which category does this issue belong to?

Core

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 7.4.0

### If this is a regression, please try to identify the Bazel commit where the bug was introduced with bazelisk --bisect.

https://github.com/bazelbuild/bazel/pull/19997/

**Comment by Wyverald** [comment]
Ideally, you should probably migrate off `java_import_external` onto [rules_jvm_external](https://github.com/bazel-contrib/rules_jvm_external). The JVM-related repo rules bundled with Bazel (`java_import_external`, `jvm_maven_import_external`, `jvm_import_external`, `maven_jar`, `maven_aar`) are essentially unmaintained and rules_jvm_external has a much more friendly API and an active community. The bundled rules will probably be removed in Bazel 9.

cc @jin

**Comment by jin** [comment]
+1 @Wyverald,  please let us know if rules_jvm_external doesn't work for you.

**Comment by gkdn** [comment]
I don't need this. I already worked around. I reported because it seemed like accidentally broken in Bazel 7+.
