### ISSUE TITLE
Have more C++ integration tests 

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#2430]
One option would be to port the relevant part of our internal C++ test battery.

Now that we have include pruning, there is a significantly higher chance of breakage so this'd be a good time. 

I'm not extremely worried (thus the P3 label) because our internal test battery is pretty extensive, but Bazel works a bit differently, so it's not a complete solution, even if we'd be okay with having a non-OSS test battery (which we are not)

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
