### ISSUE TITLE
Enable BUILD file auto-generation

### ISSUE THREAD

**Issue by dentiny** [bazelbuild/bazel#24323]
### Description of the feature request:

A lot of the projects I've seen doesn't use bazel & BUILD "correctly", for example C++, declaring all header files and impl files as dependency, and compile them all together.

The disadvantage for this approach is: when any header or impl files change, you need to rebuild everything.
I'm wondering if we could have a BUILD file auto-generation feature?

**Comment by Wyverald** [comment]
For discussion topics, please prefer to use either GitHub discussions (https://github.com/bazelbuild/bazel/discussions) or our Slack channel (https://slack.bazel.build/).

On this specific topic, there have been many, many successful cases of build file generation. Please see previous BazelCon talks (gogole "build file generation bazelcon") and the Gazelle project.
