### ISSUE TITLE
Depend only on Visual C++ Build Tools

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2432]
### Description of the problem / feature request / question:

According to @laszlocsomor, Bazel still requires a Visual Studio installation.
It is very probable that this is superfluous and could be replaced by using _Visual C++ Build Tools_, which is easier to bundle and install.

### Environment info
* Operating System: Windows

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
Nope

<sub>I see that I just produced the 666th Active Issue. Do I get a price or what.</sub>

**Comment by laszlocsomor** [comment]
@mhlopko : adding you because this is crosstool-related
@meteorcloudy : adding you because you authored cc_configure.bzl and the VS discovery logic

**Comment by laszlocsomor** [comment]
@dslomov : adding you to assign a milestone

**Comment by dslomov** [comment]
@meteorcloudy this is fixed right?

**Comment by meteorcloudy** [comment]
Yes, fixed by https://github.com/bazelbuild/bazel/commit/7a95e42ff3b0ed87a936dce50934640a58d25976
