### ISSUE TITLE
[8.0.0] Preserve analysis cache through `--run_under` command changes

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#24322]
Forked from #24303

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/analysis/BUILD`
`src/main/java/com/google/devtools/build/lib/analysis/config/RunUnder.java`
`src/test/shell/integration/run_test.sh`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/24352

**Comment by iancha1992** [comment]
This was rolled back. We no longer need this. See https://github.com/bazelbuild/bazel/pull/24303#issuecomment-2486531340
