### ISSUE TITLE
[8.0.0] Attribute inheritance causes analysis failures for certain built-in attributes

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#24320]
Forked from #24319

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/starlarkbuildapi/StarlarkRuleFunctionsApi.java`

cc: @bazelbuild/triage

**Comment by brandjon** [comment]
Merged in #24368.
