### ISSUE TITLE
MSVC output is very spammy with template instantiations

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2433]
When clean-building `//third_party/protobuf` for `--cpu=x64_windows_msvc`, the compiler spams stdout with hundreds of this and similar:
```
        with
        [
            T=google::protobuf::FileDescriptorProto
        ]
third_party/protobuf/3.0.0/src\google/protobuf/arena.h(623): note: see declaration of 'google::protobuf::Arena::CreateMaybeMessage'
```

Can we disable this somehow?

**Comment by laszlocsomor** [comment]
Example: http://ci.bazel.io/view/Dashboard/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-x86_64/517/console

**Comment by meteorcloudy** [comment]
Yes, I am also aware of this. A related issue #1897, I'll look into it.

**Comment by meteorcloudy** [comment]
Adding `--copt=/w` should suppress all the warning messages, but I found it's overridden by `/Wall` if `/Wall` appears later.
How about make `/w` superior than `/Wall`, like this:
https://github.com/bazelbuild/bazel/blob/master/tools/cpp/wrapper/bin/pydir/msvc_tools.py.tpl#L390

**Comment by laszlocsomor** [comment]
Would that have any drawbacks?

**Comment by meteorcloudy** [comment]
I guess not? Because people can always choose not to add /w, right?

**Comment by meteorcloudy** [comment]
Unless they want to use `/Wall` to force enable warnings, but /w is not under their control. That should be a rare situation.
