### ISSUE TITLE
Windows, cc_configure.bzl: Visual Studio discovery is flaky

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2434]
http://ci.bazel.io/view/Dashboard/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-x86_64/518/console

Sometimes we don't find the VS installation, even if it's there.
In this example, the machine has VS2015 installed under `C:\Program Files (x86)\Microsoft Visual Studio 14.0`.

**Comment by laszlocsomor** [comment]
Related issue: https://github.com/bazelbuild/bazel/issues/2448

**Comment by dslomov** [comment]
@meteorcloudy ping

**Comment by meteorcloudy** [comment]
This is fixed.
