### ISSUE TITLE
bazel.build, search widget: returns irrelevant results

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2435]
### Description of the problem / feature request / question:

On bazel.build, we have a Google Custom Search bar in the top. Search there returns irrelevant results, e.g. "cc_library" returns just one hit, bazel.io/docs/cpp.html (notice it's even bazel.io).

Don't know if there's anything to configure about this search bar, but if there is, maybe we misconfigured something.

**Comment by jin** [comment]
Just did a search on `cc_library`, the results look WAI. Closing this for now.
