### ISSUE TITLE
Build configurations conflict with `--experimental_platform_in_output_dir` usage

### ISSUE THREAD

**Issue by OparinE** [bazelbuild/bazel#24366]
### Description of the bug:

[--experimental_platform_in_output_dir](https://bazel.build/reference/command-line-reference#flag--experimental_platform_in_output_dir) may lead to configurations conflict if `bazel build` contains targets with transitions to platform aliases.

Example:
1) we have 2 platforms: origin and alias to origin. Both have the same name (its important), but are placed in different packages
2) we build 2 targets under these 2 platforms simultaneously (using transitions)
3) build fails with configuration conflict, however these 2 platforms are identical. Alias to platform is just renaming.

Expectations:
Build pass fine, there is one config subfolder in execroot.
Because alias to platform is just renaming, both platforms have matching basename.

If it's not a bug, but normal behavior of  `--experimental_platform_in_output_dir`, option description should be updated by this corner case.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/OparinE/bazel_issues

### Which operating system are you running Bazel on?

I get an error on Windows and Macos, however i guess it can be reproduced on Linux as well

### What is the output of `bazel info release`?

7.4

**Comment by katre** [comment]
This is the exact case that `--experimental_override_name_platform_in_output_dir` is designed to solve.

In your bazelrc, add the lines:
```
build --experimental_override_name_platform_in_output_dir=//package_a:platform=platform_a
build --experimental_override_name_platform_in_output_dir=//package_b:platform=platform_b
```

This will cause the output paths for each config to have either `platform_a` or `platform_b` instead of plain `platfform`.
