### ISSUE TITLE
Bazel installation failed  "package io.grpc.stub does not exist"

### ISSUE THREAD

**Issue by AndreiNikitin** [bazelbuild/bazel#2436]
### Description of the problem / feature request / question:
I try to compile bazel using MSYS2 64-bit
While executing command "bash compile.sh" in my bazel directory, it always fails to compile because of "error: package io.grpc.stub does not exist".
I set my enviroment according to requirements (https://bazel.build/versions/master/docs/windows.html#requirements).
Also, I checked   "/third_party/grpc" package in bazel folder. There are all classes, which need to compile bazel.
Log is attached.
Any idea of what it might be?

### Environment info
* Operating System:  Windows 7 Ultimate SP1 64-bit
* Bazel version (output of `bazel info release`): 0.4.3
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

###  Have you found anything relevant by searching the web?
No

### Anything else, information or logs or outputs that would be helpful?
[log.txt](https://github.com/bazelbuild/bazel/files/732869/log.txt)

**Comment by laszlocsomor** [comment]
Thanks for the bug report!

- Does https://github.com/bazelbuild/bazel/releases/download/0.4.3/bazel-0.4.3-windows-x86_64.exe work for you?
- As a workaround, can you use it with compile.sh like so?
    ```
    compile.sh compile path/to/bazel-0.4.3-windows-x86_64.exe
    ```

- Can you clone the bazel repository and use bazel to build bazel from source?
    ```
    export BAZEL_SH=c:/tools/msys64/usr/bin/bash.exe
    export JAVA_HOME=<path to your java home>
    git clone https://github.com/bazelbuild/bazel.git
    cd bazel
    path/to/bazel-0.4.3-windows-x86_64.exe --output_user_root=/c/tmp1 build src:bazel
    ```

**Comment by AndreiNikitin** [comment]
1. Got error after launching .exe "The entry point in procedure __locale_ctype_ptr not found in dll library msys-2.0.dll"
![bazel_error](https://cloud.githubusercontent.com/assets/18249799/22376929/a955b700-e4b8-11e6-8f35-df5316f43c84.png)
2. Got error ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//':

**Comment by laszlocsomor** [comment]
Bummer, that dialog box indicates the same error as https://github.com/bazelbuild/bazel/issues/2431#issuecomment-275391059

Could you translate the error message at the end of log2.txt please (this one):
```
Auto-Configuration Error: ""C:\Program Files (x86)\Microsoft Visual Studio 14.0/VC/VCVARSALL.BAT"" (the rest here)
```

**Comment by laszlocsomor** [comment]
Also, could you please run:
```
echo $PATH
du -b /usr/bin/msys-2.0.dll
md5sum /usr/bin/msys-2.0.dll
md5sum $(which md5sum)
```
and paste the output here?

**Comment by laszlocsomor** [comment]
Never mind, here's the solution!
https://github.com/bazelbuild/bazel/issues/2431#issuecomment-275699591

**Comment by AndreiNikitin** [comment]
I've got question marks right in the msys shell. So it seems there is no way to translate it

**Comment by AndreiNikitin** [comment]
Good, I'm going to try that one.

**Comment by laszlocsomor** [comment]
Ugh, maybe UTF8 rendering is broken so Cyrillic renders as question marks. Ouch. Thanks for bringing that to my attention! I'll open a separate bug for that.

**Comment by AndreiNikitin** [comment]
So, I reinstalled msys2 right from here https://msys2.github.io/

**Comment by AndreiNikitin** [comment]
ANDRE@▒▒▒▒▒▒-▒▒ MINGW64 /d/downloads/bazel
$ echo $PATH
/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/

ANDRE@▒▒▒▒▒▒-▒▒ MINGW64 /d/downloads/bazel
$ du -b /usr/bin/msys-2.0.dll
3293934 /usr/bin/msys-2.0.dll

ANDRE@▒▒▒▒▒▒-▒▒ MINGW64 /d/downloads/bazel
$ md5sum /usr/bin/msys-2.0.dll
8204f1e60a6babeeeebb48a830e223de */usr/bin/msys-2.0.dll

ANDRE@▒▒▒▒▒▒-▒▒ MINGW64 /d/downloads/bazel
$ md5sum $(which md5sum)
e599828a5d886626340f72c4cde77d5b */usr/bin/md5sum

**Comment by abergmeier-dsfishlabs** [comment]
@AndreiNikitin FYI: Installing https://sourceforge.net/projects/msys2/files/Base/x86_64/msys2-x86_64-20160205.exe/download and running `pacman -Syuu gcc git curl zip unzip zlib-devel` afterwards worked for me.

**Comment by AndreiNikitin** [comment]
So, the problem was in python absence in msys. After executing command `pacman -S python ` i could successfully compile bazel.

**Comment by AndreiNikitin** [comment]
Thank you all for help!

**Comment by abergmeier-dsfishlabs** [comment]
@laszlocsomor Does python need to be in msys or only in the System. I explicitly set `BAZEL_PYTON` in my installation.

**Comment by laszlocsomor** [comment]
@abergmeier-dsfishlabs : AFAIK only on the system. The auto-config (`cc_configure.bzl`) should be able to discover your python 2.7 installation, setting `BAZEL_PYTHON` should not be necessary. Does your experience contradict that?

**Comment by abergmeier-dsfishlabs** [comment]
> Does your experience contradict that?

Nope seems to work fine for me. Just sounded like it.
