### ISSUE TITLE
Cherry-pick a fix of race conditions while getting ps snapshots

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#24387]
### Commit IDs

b2664b1e4d60b5de8536242721f09841b30e6610

### Category

team-Performance

### Reviewers

@meisterT

**Comment by bazel-io** [comment]
Failed commits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/b2664b1e4d60b5de8536242721f09841b30e6610.
Please resolve manually.
cc: @bazelbuild/triage
