### ISSUE TITLE
bazel run ios_application doesn't update app in simulator

### ISSUE THREAD

**Issue by XperielIndigo** [bazelbuild/bazel#244]
Hi everyone,

When I use `bazel run --ios_sdk_version=8.3 --ios_simulator_version=8.3 //myfolder:myTarget` the first time it works fine. However, when I make changes to my app and then run the command again the simulator version does not update for the changes I made.

This issue was first discussed on the bazel forums: https://groups.google.com/forum/#!topic/bazel-discuss/h4Nd2uhKjso

Cheers
Indigo

**Comment by c-parsons** [comment]
Likely best handled by [Tulsi](https://github.com/bazelbuild/tulsi), now.
