### ISSUE TITLE
Bazel cannot detect Visual Studio 2017 on Windows

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2440]
The install directory for MSVC has completely changed.

`vcvarsall.bat` script is now located at 
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build`

And finding VS install directory through `reg.exe` doesn't work anymore, because key `InstallDir` no longer exists.

Need to figure out a new way to detect MSVC for Visual Studio 2017.

**Comment by davido** [comment]
Yeah, it's a known issue. May be my patch for LibreOffice for this compile detection would be helpful: [1].

* [1] https://gerrit.libreoffice.org/#/c/31279/12/configure.ac@3335

**Comment by meteorcloudy** [comment]
This is great, thanks!
