### ISSUE TITLE
[8.0.0] Update `rules_java v8.5.0`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#24405]
Forked from #24391

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/test/shell/bazel/bazel_proto_library_test.sh`

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/24414
