### ISSUE TITLE
Server crashed during startup. (maybe special-char related?)

### ISSUE THREAD

**Issue by stormsc1** [bazelbuild/bazel#24416]
### Description of the bug:

```
C:\Dev\KhaosSystems\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\\Python39\\python.exe" mediapipe/unreal:ump_shared
Starting local Bazel server and connecting to it...
Server crashed during startup. Now printing c:\users\storms∩┐╜ndergaard\_bazel_storms∩┐╜ndergaard\4jcgmw3g\server\jvm.out
Error: Unable to access jarfile C:\\Users\\StormS?ndergaard\\_bazel_StormS?ndergaard\\install\\29d8636b28175236152b75c823539a3c\\A-server.jar
```

### Which category does this issue belong to?

CLI

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I am not sure. It might be because of special characters in username, but not sure.

### Which operating system are you running Bazel on?

Windows 11

### What is the output of `bazel info release`?

C:\Dev\KhaosSystems\mediapipe>bazel info release Starting local Bazel server and connecting to it... Server crashed during startup. Now printing c:\users\storms∩┐╜ndergaard\_bazel_storms∩┐╜ndergaard\4jcgmw3g\server\jvm.out Error: Unable to access jarfile C:\\Users\\StormS?ndergaard\\_bazel_StormS?ndergaard\\install\\29d8636b28175236152b75c823539a3c\\A-server.jar

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
https://github.com/KhaosSystems/mediapipe
```

### Any other information, logs, or outputs that you want to share?

Tried to set BAZEL_USER_HOME=C:/Bazel and BAZEL_HOME=C:/Bazel, without luck.

**Comment by fmeum** [comment]
If you are using Bazelisk, could you check whether you can get past this error if you set the environment variable `USE_BAZEL_VERSION=083fc651d5c1b2076d08d82365ddf381e2ea4adb` ? That gives you a pre-release version of Bazel 8 with many Unicode fixes.

**Comment by stormsc1** [comment]
I was able to get a bit further, but the project I was trying to build did not build with the per-release version of Bazel (is it on 6.5). I ended up finding a second workstation.

> If you are using Bazelisk, could you check whether you can get past this error if you set the environment variable `USE_BAZEL_VERSION=083fc651d5c1b2076d08d82365ddf381e2ea4adb` ? That gives you a pre-release version of Bazel 8 with many Unicode fixes.

**Comment by meisterT** [comment]
@stormsc1 since this crashes during startup, you can test this independently from your project.

Just create temp dir in your home, an empty `WORKSPACE` file and test there first that it fails with Bazel 6.x and that it works with the Bazel version from Fabian.

**Comment by fmeum** [comment]
This may require additional fixes from https://github.com/bazelbuild/bazel/pull/24457 that won't make it into Bazel 8.0.0 (but will likely be in 8.1.0).

 You can specify an output base without special chars via `bazel --output_base=... build ...` to work around this in the meantime.
