### ISSUE TITLE
cc_configure_extension no longer available in @@bazel_tools//tools/cpp:cc_configure.bzl

### ISSUE THREAD

**Issue by weedless** [bazelbuild/bazel#24426]
### Description of the bug:

The module extension _cc_configure_extension_ has been removed from cc_configure.bzl. Many modules in bazel central registry (re2, abseil-cpp, blake3, ...) are referencing this, making the change non-backwards compatible.

### Which category does this issue belong to?

Loading API

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Use bazel revision 8.0.0rc2.
Setup a MODULE.bazel with dependencies to re2, abseil-cpp, or blake3.
Run "bazel mod graph"

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

release 8.0.0rc2

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

-

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
-
```

### If this is a regression, please try to identify the Bazel commit where the bug was introduced with bazelisk --bisect.

1c4e78a9ceab9794140324d64833c628e382a3da

### Have you found anything relevant by searching the web?

No

**Comment by fmeum** [comment]
@meteorcloudy It looks like these modules mostly rely on it for CI purposes and should have marked it a dev dependency. We could also add a forwarder and live with the extension being evaluated twice.

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by meteorcloudy** [comment]
Yeah, I also realized this and I'm sending an internal fix for abseil-cpp. 

I believe those are all needed for selecting toolchain on Windows, like `--extra_toolchains=@local_config_cc//:cc-toolchain-arm64_windows`. All of them should migrate to use `local_config_cc` from rules_cc instead.

https://github.com/bazelbuild/bazel/blob/572ff083d105c0fd05a025432318d3c102954cab/MODULE.bazel#L300-L302

And it's actually not easy to make it backwards compatible since there is no way to create an alias of cc_configure_extension from bazel_tools to rules_cc.

**Comment by fmeum** [comment]
> And it's actually not easy to make it backwards compatible since there is no way to create an alias of cc_configure_extension from bazel_tools to rules_cc.

While we can't create an alias, we could duplicate the extension by reexporting from a `.bzl` file in `bazel_tools`. It will be considered a distinct extension and thus duplicate work, but it could ensure backwards compatibility.

**Comment by meteorcloudy** [comment]
OK, maybe that's better. I'll send a change internal to speed this up. /cc @Wyverald

**Comment by meteorcloudy** [comment]
@bazel-io fork 8.0.0

**Comment by meteorcloudy** [comment]
This should be addressed by https://github.com/bazelbuild/bazel-central-registry/pull/3320

**Comment by meteorcloudy** [comment]
Abseil fixed at https://github.com/abseil/abseil-cpp/commit/9e3b68ac3b328212e4ad7baada1523a05f615dde

**Comment by phst** [comment]
At least for me this seems to be not fixed yet because there's another dependency chain abseil-cpp@20240722.0.bcr.2 -> googletest@1.15.2 -> re2@2024-07-02 with similar problems. re2 has a patched version but googletest doesn't use it yet. (Should googletest be a dev dependency for abseil-cpp?)

**Comment by meteorcloudy** [comment]
>  re2 has a patched version but googletest doesn't use it yet.

Yeah, this is a common problem with MVS resolution, https://github.com/phst/rules_elisp/commit/6b04053a924230c4e6db02e33c7f5d0fea8e5d71 is the correct workaround. A full fix will involve having a new release for every module on the dependency chain..

> Should googletest be a dev dependency for abseil-cpp?

Looks like no, https://github.com/abseil/abseil-cpp/blob/4e0956109640efa4b2ee68a2d6640fb13afa420e/MODULE.bazel#L41-L42

**Comment by vtsao-openai** [comment]
Oh I see there are already a bunch of CLs out for this for re2:
https://code-review.googlesource.com/c/re2/+/63510
https://code-review.googlesource.com/c/re2/+/63470

guess I should've checked first before adding yet another one...

**Comment by jmr** [comment]
> Oh I see there are already a bunch of CLs out for this for re2:
> https://code-review.googlesource.com/c/re2/+/63470

This has been merged as https://github.com/google/re2/commit/c84a140.
