### ISSUE TITLE
[Mirror] rules_shell

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#24425]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/bazelbuild/rules_shell/releases/download/v0.3.0/rules_shell-v0.3.0.tar.gz
https://github.com/bazelbuild/rules_shell/releases/download/v0.2.0/rules_shell-v0.2.0.tar.gz

**Comment by meteorcloudy** [comment]
Done: 
- https://mirror.bazel.build/github.com/bazelbuild/rules_shell/releases/download/v0.3.0/rules_shell-v0.3.0.tar.gz
- https://mirror.bazel.build/github.com/bazelbuild/rules_shell/releases/download/v0.2.0/rules_shell-v0.2.0.tar.gz
