### ISSUE TITLE
Flag to verify all WORKSPACE rules have a sha1/sha256

### ISSUE THREAD

**Issue by ronshapiro** [bazelbuild/bazel#2442]
I understand why the sha1/sha256 is an optional attribute for WORKSPACE rules to ease development, but I think it would be helpful to be able to have a presubmit that verifies that these are all in place.

* Bazel version (output of `bazel info release`):
0.4.3

Here's what we do in Dagger, but it's reliant on AST parsing and would not detect skylark macros which define WORKSPACE rules: https://github.com/google/dagger/blob/fcf2727b1c7996a99e1a50f9278f9e004ea29ce3/tools/maven_sha1_test.py

**Comment by dslomov** [comment]
This is a great idea, patches welcome

**Comment by ronshapiro** [comment]
Given the multitude of workspace rules since this was first filed, I'm not sure that this is still reasonable/possible. Happy to close it if you think it's out of scope.

**Comment by ronshapiro** [comment]
Actually, perhaps `repository_ctx.download{and_extract}()` is a good signal to measure.

**Comment by jmillikin-stripe** [comment]
I'm still interested in this feature. It's proposed implementation might be outside of Bazel itself (see https://docs.google.com/document/d/1aagKnM8kRmMvLqSXasShsI-NYOBZYtgNrbYWLPwBoBg/edit)

**Comment by fenollp** [comment]
A resolved.bzl file stores checksums regardless of whether they are set in WORKSPACE. See https://blog.bazel.build/2018/09/28/first-class-resolved-file.html

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
