### ISSUE TITLE
Windows, Skylark: cannot render Cyrillic (maybe?)

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2443]
This issue is split off https://github.com/bazelbuild/bazel/issues/2436#issuecomment-275697362 : apparently in log2.txt the question marks were rendered as such by MSYS. As can be seen on a screenshot earlier, the user has Windows installed in Russian. The question marks may be incorrectly rendered Cyrillic.

**Comment by laurentlb** [comment]
Skylark doesn't transform characters, so it shouldn't be an issue.
Maybe the input file and the terminal disagree on the encoding?

**Comment by laszlocsomor** [comment]
Assigning to Dmitry who actually speaks Russian :)

**Comment by laszlocsomor** [comment]
Acknowledging that this is a problem, I'm still keeping the priority as P3. Reason being that the rest of Bazel doesn't work well with non-ASCII paths anyway (labels for example don't support non-ASCII paths), and the Windows team doesn't have capacity to fix the rest of Bazel. I'm sad to say that I don't realistically see fixing this any time in the next few months.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
