### ISSUE TITLE
[8.0.0] archive_override() and git_override() should allow for same arguments as their repository rule counterparts

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#24442]
Forked from #24412

**Comment by Wyverald** [comment]
will probably need to cherry-pick a bunch of dependency CLs -- so don't block rc3 on this

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/ArchiveOverride.java`
`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/GitOverride.java`
`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/InterimModule.java`
`src/main/java/com/google/devtools/build/lib/bazel/bzlmod/LocalPathOverride.java`
`src/main/java/com/google/devtools/build/lib/skyframe/BzlmodRepoRuleFunction.java`

cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
https://github.com/bazelbuild/bazel/pull/24443
