### ISSUE TITLE
Compiler flags bleed into externals

### ISSUE THREAD

**Issue by david-german-tri** [bazelbuild/bazel#2444]
### Description of the problem / feature request / question:

On [RobotLocomotion/drake](https://github.com/RobotLocomotion/drake), our `CROSSTOOL` and `.bazelrc` upgrade various warnings to errors.  For instance, we [set -Werror=all](https://github.com/RobotLocomotion/drake/blob/master/tools/bazel.rc#L7).  These settings bleed into externals which may not actually be free of the upgraded warnings, resulting in problems like this:

```
ERROR: /home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/external/com_github_google_protobuf/BUILD:113:1: C++ compilation of rule '@com_github_google_protobuf//:protobuf' failed: linux-sandbox failed: error executing command /home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/_bin/linux-sandbox ... (remaining 54 argument(s) skipped).
external/com_github_google_protobuf/src/google/protobuf/util/time_util.cc:52:18: error: unused variable 'kMicrosPerMillisecond' [-Werror,-Wunused-const-variable]
static const int kMicrosPerMillisecond = 1000;
                 ^
external/com_github_google_protobuf/src/google/protobuf/util/time_util.cc:56:19: error: unused variable 'kTimestampFormat' [-Werror,-Wunused-const-variable]
static const char kTimestampFormat[] = "%E4Y-%m-%dT%H:%M:%S";
```

When we're handcrafting an external BUILD file (e.g. with `new_http_archive`), we just use `copts` to squash the offending warnings.  When an external comes with its own BUILD file, as protobuf does, I don't know how to proceed.  Is there a mechanism to inject our corrective `copts`, short of forking protobuf's BUILD?  Better yet, is there a mechanism to prevent our flags from leaking at all?

### Environment info
* Operating System: Ubuntu Trusty 14.04

* Bazel version (output of `bazel info release`): `release 0.4.3`

**Comment by meteorcloudy** [comment]
I think you can still use `new_http_archive` for an external repository which already has a BUILD. AFAIK, TensorFlow is using this way to override grpc's original BUILD file.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl#L294

If you don't want your flags applied to externals, I think the best way is to specify them in BUILD files instead of bazelrc file.

**Comment by david-german-tri** [comment]
Thanks for accepting the feature request!

> If you don't want your flags applied to externals, I think the best way is to specify them in BUILD files instead of bazelrc file.

OK.  If that's the recommended workaround, that's what we'll do.  Specifically, we'll replace `cc_binary` and `cc_library` with our own macros that specify platform-appropriate `copts`.  (See also #2358.)

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
