### ISSUE TITLE
[8.0.0] macOS support for Unicode in Java compilation actions regressed

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#24460]
Forked from #24459

**Comment by bazel-io** [comment]
Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.

`src/main/java/com/google/devtools/build/lib/bazel/rules/java/BazelJavaSemantics.java`
`src/main/java/com/google/devtools/build/lib/rules/java/JavaCompilationHelper.java`
`src/main/java/com/google/devtools/build/lib/rules/java/JavaSemantics.java`

cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
Hmm. It looks like the original change to use `C.UTF-8` isn't cherry-picked on release-8.0.0.

@fmeum how crucial is this? I'm reluctant to rock the boat at the eleventh hour (more like the thirteenth hour at this point...), but we can of course cherry-pick both this commit and the original one that switched to `C.UTF-8`, if absolutely necessary.
