### ISSUE TITLE
Bazel 8rc3 crashes even on an empty repository

### ISSUE THREAD

**Issue by tpasternak** [bazelbuild/bazel#24474]
### Description of the bug:

bazel depends on rules_shell 0.2.0 which depend on an outdated version of rules_features. The outdated version doesn't contain this patch, so it crashes with rc3 where these builtin providers have been removed 

https://github.com/bazel-contrib/bazel_features/commit/5aad6a345bb27d5db396b4b1aea46b36594cb65b

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
1. create a literally empty repository (just `touch MODULE.bazel`)
2. make sure you use bazel 8 rc 3
3. run `bazel mod deps`

_No response_

**Comment by meteorcloudy** [comment]
Relevant issue: https://github.com/bazel-contrib/bazel_features/issues/82

**Comment by tpasternak** [comment]
Yes, it's fixed. Thank you!
