### ISSUE TITLE
Windows: get rid of hardcoded `tools/msys64` paths

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2447]
"tools/msys64" is hardcoded in some locations.
Get rid of these and only use the `BAZEL_SH` envvar.

This is part of the larger effort known as https://github.com/bazelbuild/bazel/issues/2107

**Comment by laszlocsomor** [comment]
@mhlopko : FYI, CROSSTOOL is an example where this is hardcoded

**Comment by laszlocsomor** [comment]
This bug is related to https://github.com/bazelbuild/bazel/issues/2725

**Comment by dslomov** [comment]
The remaining occurrences are either in tests or in CROSSTOOL for gcc. Closing this (we do not see many requests for supporting gcc on Windows, and when we do, we will need to redesign it from scratch)
