### ISSUE TITLE
[8.0.0] Enforce a minimal required version of bazel_features in MODULE.tools

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#24480]
### Commit IDs

face2bea4a1371a9aece467fc6b8c977edfa95a6

### Category

team-OSS

### Reviewers

@comius

**Comment by bazel-io** [comment]
Failed commits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/face2bea4a1371a9aece467fc6b8c977edfa95a6.
Please resolve manually.
cc: @bazelbuild/triage
