### ISSUE TITLE
repository_disable_download fails with blzmod enabled

### ISSUE THREAD

**Issue by davexroth** [bazelbuild/bazel#24483]
### Description of the bug:

I have a workspace where all bazel dependencies are specified through `local_repositories`.  If I run bazel with `--experimental_repository_disable_download --enable_bzlmod=false` everything works.  However, if I enable bzlmod, the bazel fails with the following error message:

```
INFO: Repository platforms instantiated at:
  <builtin>: in <toplevel>
Repository rule http_archive defined at:
  /usr/local/google/home/davidroth/.cache/bazel/_bazel_davidroth/17b321a4c24be48339cbd5cfb60ee2e8/external/bazel_tools/tools/build_defs/repo/http.bzl:387:31: in <toplevel>
ERROR: /usr/local/google/home/davidroth/.cache/bazel/_bazel_davidroth/17b321a4c24be48339cbd5cfb60ee2e8/external/bazel_tools/tools/build_defs/repo/http.bzl:136:45: An error occurred during the fetch of repository 'platforms':
   Traceback (most recent call last):
	File "/usr/local/google/home/davidroth/.cache/bazel/_bazel_davidroth/17b321a4c24be48339cbd5cfb60ee2e8/external/bazel_tools/tools/build_defs/repo/http.bzl", line 136, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Failed to download repository @@platforms: download is disabled.
ERROR: no such package '@@platforms//host': java.io.IOException: Failed to download repository @@platforms: download is disabled.
ERROR: /usr/local/google/home/davidroth/.cache/bazel/_bazel_davidroth/17b321a4c24be48339cbd5cfb60ee2e8/external/bazel_tools/tools/BUILD:102:6: @@bazel_tools//tools:host_platform depends on @@platforms//host:host in repository @@platforms which failed to fetch. no such package '@@platforms//host': java.io.IOException: Failed to download repository @@platforms: download is disabled.
ERROR: /usr/local/google/home/davidroth/GitHub/davexroth/bazel_no_download_repro/BUILD:1:10: Target @@bazel_tools//tools:host_platform was referenced as a platform, but does not provide PlatformInfo
ERROR: Analysis of target '//:main' failed; build aborted
INFO: Elapsed time: 0.445s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
```

Please see the included minimal reproduction with full details.

### Which category does this issue belong to?

External Dependency

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/davexroth/bazel_no_download_repro

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

release 7.4.1

**Comment by davexroth** [comment]
cc @Wyverald @tpudlik

**Comment by Wyverald** [comment]
This is WAI -- the overrides you have in WORKSPACE don't affect the Bzlmod part of the build. You'll need to add `local_path_override` clauses to your MODULE.bazel file, similar to what you have in your WORKSPACE file.

So `local_path_override(module_name="platforms", path="external/platforms")` etc.

**Comment by davexroth** [comment]
This is a little un-intuitive for users upgrading from bazel 6 to 7, as by default in version 7 both `enable_workspace` and `enable_bzlmod` are true, which causes a working WORKSPACE to start failing on upgrade.  It's also not obvious to a user why these WORKSPACE overrides are ignored while other parts of the WORKSPACE are honored in this configuration.
