### ISSUE TITLE
[Bazel CI] Error failed executing CppLink command 


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#24486]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4292#019366a6-f024-4a45-8b91-3c9b11c1abef

 Platform: Ubuntu

 Logs: 
```
ERROR: [0m/workdir/src/main/cpp/BUILD:93:10: Linking src/main/cpp/client failed: (Exit 1): gcc failed: error executing CppLink command (from target //src/main/cpp:client) 
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/ttps://raw
git reset curl -sS htt --hard
export USE_BAZEL_VERSION=c22658697cbde128ad31e2f7ec8a351195ba91c9
bazel build //src:bazel  //src:bazel_nojdk 
 ``` 
 CC Greenteam @meteorcloudy @comius

**Comment by meteorcloudy** [comment]
Thanks! This should be fixed now.

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4292#019367c3-f065-4792-a892-ad4c6b39cd80
