### ISSUE TITLE
Add option to overlay local files into HTTP archives

### ISSUE THREAD

**Issue by ouillie** [bazelbuild/bazel#24499]
### Description of the feature request:

`http_archive` has `remote_file_urls` to insert files into a dependency archive. I propose adding something similar for local files relative to the repo root, so that I can insert files taken from the depending Bazel repo into the dependency archive. Something like this:

```python
http_archive(
  name = "foo",
  urls = ["http://foo.bar/dep.zip"],
  copy_files = {
    "path/in/dependency": "//file/in:depender",
  },
)
```

### Which category does this issue belong to?

External Dependency

### What underlying problem are you trying to solve with this feature?

There doesn't seem to be a reliable way to insert files that are hosted locally in the depending repo rather than remotely. You could use a local `file://` URL like [this test](https://github.com/bazelbuild/bazel/blob/7.4.1/src/test/shell/bazel/external_remote_file_test.sh#L130), but that only works for absolute paths, which would be unreliable in a cloneable Git repo. Up to now I was [abusing `cat` as a "patch" tool](https://github.com/vimana-cloud/rules_wasm/blob/v1.0.16/MODULE.bazel#L125), but that seems to be breaking now since https://github.com/bazelbuild/bazel/commit/27487cf11f61eb23108f8df129dc1a00ee1a4370 added the `patch_strip` rule to `http_archive`, which means my "patch" tool always gets passed `-p0` even when `patch_args` is empty (which doesn't work for `cat`).

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 8.0.0rc4

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
https://github.com/vimana-cloud/rules_wasm.git
cc13ad3ed22b8356ff60e0fa86b2ccd0530bb79d
```

**Comment by honnix** [comment]
I think `remote_file_urls` supports relative path (relative to the repository root), e.g. `file:foo/bar.txt`.

**Comment by Silic0nS0ldier** [comment]
Keep in mind that (confirmed in bzlmod, not sure about workspace) Bazel will not track changes to local files referenced with `file:` through `remote_file_urls`. If using this, also set `remote_file_integrity` and ensure they are updated when changes are made.

**Comment by Silic0nS0ldier** [comment]
Been after a way to do this for awhile so I've raised #26852.
