### ISSUE TITLE
Corrupt installation on Windows

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2450]
### Description of the problem / feature request / question:

A few times a day, Bazel seems to corrupt itself.

    bazel shutdown

Error is:

    Error: corrupt installation: file 'C:\Users\A5336~1.BER\AppData\Local\Temp\_bazel_a.bergmeier\install\ef18c8a0c4758f558e9141b77d899cfd\_embedded_binaries\build-runfiles.exe' missing. Please remove 'C:\Users\A5336~1.BER\AppData\Local\Temp\_bazel_a.bergmeier\install\ef18c8a0c4758f558e9141b77d899cfd' and try again.

Aside from any corruption, this is annoying because this means I have to manually kill the Server with Process Explorer.
So `shutdown` really should not depend on anything superfluous.
Still - should not corrupt itself.

### Environment info
* Operating System: Windows 10

* Bazel version (output of `bazel info release`): 855fbe9ee447b7b37fd8c73dbc047d69b7ceffcf

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
Seems to have happened in the past but fixed (for non-win): #471

### Anything else, information or logs or outputs that would be helpful?
Removing the install fixes it.

**Comment by meteorcloudy** [comment]
Did you somehow touched the bazel install directory?

**Comment by abergmeier-dsfishlabs** [comment]
> Did you somehow touched the bazel install directory?

Not willingly. That said - I have a custom repository and it behaves rather strange on Windows. Looking into it.

**Comment by abergmeier-dsfishlabs** [comment]
So even disabling the custom repository, it still fails.
The file in question in the error message seems different every time.

**Comment by abergmeier-dsfishlabs** [comment]
> Error: corrupt installation: file 'C:\Users\A5336~1.BER\AppData

And I am somewhat wondering why Bazel is still using that strange DOS path. Wasn't this a bug that has been fixed?

**Comment by meteorcloudy** [comment]
Hmm, I think you mean this issue? https://github.com/bazelbuild/bazel/issues/2342
It is fixed, and there is no `$` in the path anymore.
//cc @laszlocsomor Any idea on this?

**Comment by meteorcloudy** [comment]
Can you try setting `TMPDIR=c:/tmp`, see if it happens again?

**Comment by laszlocsomor** [comment]
Try also `--output_user_root=/c/tmp123`. Maybe your installation *did* become corrupt -- did you edit (or merely touch) any of the files in that directory? This corruption detection logic looks at file mtimes.

**Comment by abergmeier-dsfishlabs** [comment]
>  This corruption detection logic looks at file mtimes.

AFAIK this is **not** as safe thing to do on Windows. At least not without a large Epsilon value.

So I wait a few minutes and issue the same command that tells me about the corruption and voila works again. This really smells like your detection is broken.

**Comment by laszlocsomor** [comment]
> AFAIK this is not as safe thing to do on Windows. At least not without a large Epsilon value.

We set the timestamps years into the future. Why do you think this is unreliable on Windows?

**Comment by abergmeier-dsfishlabs** [comment]
> We set the timestamps years into the future.

Then you already have a reasonable Epsilon :)

> Why do you think this is unreliable on Windows?

We had problems in the past. We tested writing timestamps to files and reading them out again and often got an Epsilon in second range. Might be related to Windows FS cache.

**Comment by laszlocsomor** [comment]
> We had problems in the past. We tested writing timestamps to files and reading them out again and often got an Epsilon in second range. Might be related to Windows FS cache.

Epsilon has to be > 2sec.

**Comment by abergmeier-dsfishlabs** [comment]
Strange thing is - what often helps is executing `bazel fetch` and often afterwards the "corruption" is gone!?

**Comment by abergmeier-dsfishlabs** [comment]
Seems to be fixed when using 0.4.4.
