### ISSUE TITLE
[7.5.0] Cherry-pick "Add bazel query --output_file option, which writes query results directly to a file" onto 7.x

### ISSUE THREAD

**Issue by keithl-stripe** [bazelbuild/bazel#24511]
### Commit IDs

791e1f71876daf57b0ac8757eda037148f1470ea

### Category

team-Core, team-Performance

### Reviewers

@jin

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/24539

**Comment by keithl-stripe** [comment]
Thank you! But the cherry-pick request was not for 8.x; it was for 7.x. I'm not sure we'll be able to upgrade to 8.x soon at Stripe, so 7.x would allow us to use this change without having to maintain our own internal fork.

**Comment by iancha1992** [comment]
> Thank you! But the cherry-pick request was not for 8.x; it was for 7.x. I'm not sure we'll be able to upgrade to 8.x soon at Stripe, so 7.x would allow us to use this change without having to maintain our own internal fork.

cc: @meteorcloudy @Wyverald

**Comment by meteorcloudy** [comment]
We are not planning a Bazel 7.5 yet, but @iancha1992 please keep tracking on requests for a 7.5 release, maybe we should do it after the Bazel 8 release.

**Comment by iancha1992** [comment]
@keithl-stripe We are actually planning a Bazel 7.5. This is being cherry-picked into `release-7.5.0`.
