### ISSUE TITLE
Document the non-configurability of "tags"

### ISSUE THREAD

**Issue by david-german-tri** [bazelbuild/bazel#2451]
### Description of the problem / feature request / question:

`tags` appear to be `nonconfigurable`: https://github.com/bazelbuild/bazel/blob/227369a44a1061cfb26913cc2609c27801482368/src/main/java/com/google/devtools/build/lib/analysis/BaseRuleClasses.java#L173

But that doesn't show up in the [documentation for common attributes](https://bazel.build/versions/master/docs/be/common-definitions.html#common-attributes), and tags aren't explicitly documented on rules like [cc_library](https://bazel.build/versions/master/docs/be/c-cpp.html#cc_library).

**Comment by meteorcloudy** [comment]
Maybe we should make tags configurable? @damienmg WDYT?

**Comment by meteorcloudy** [comment]
AFAIK, TensorFlow has the same request before.
