### ISSUE TITLE
[7.4.1] Cannot read the array length because the return value of "jdk.internal.platform.Metrics.getCpuSetCpus()" is null

### ISSUE THREAD

**Issue by Ryang20718** [bazelbuild/bazel#24519]
### Description of the bug:

```
(01:49:08) FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.NullPointerException: Cannot read the array length because the return value of "jdk.internal.platform.Metrics.getCpuSetCpus()" is null
	at jdk.management/com.sun.management.internal.OperatingSystemImpl.isCpuSetSameAsHostCpuSet(Unknown Source)
	at jdk.management/com.sun.management.internal.OperatingSystemImpl$ContainerCpuTicks.getContainerCpuLoad(Unknown Source)
	at jdk.management/com.sun.management.internal.OperatingSystemImpl.getCpuLoad(Unknown Source)
	at jdk.management/com.sun.management.OperatingSystemMXBean.getSystemCpuLoad(Unknown Source)
	at com.google.devtools.build.lib.profiler.CollectLocalResourceUsage.run(CollectLocalResourceUsage.java:144)
```

### Which category does this issue belong to?

Local Execution

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

no reliable repro

### Which operating system are you running Bazel on?

ubuntu 20.04

### What is the output of `bazel info release`?

7.4.1

**Comment by fmeum** [comment]
This appears to be a time of check, time of use issue in the JDK. I'll see whether I can fix it there.

**Comment by fmeum** [comment]
@tjgq The JDK calls the method twice, once to check for `null`, once on the line that triggers the NPE. While I haven't been able to confirm that the method can return different return values, this looks like the likely source of the bug.

Since waiting for a JDK release with a fix will take a while anyway, should we catch the exception in Bazel?

**Comment by tjgq** [comment]
@Ryang20718 Have you seen this exact exception occur multiple times?

**Comment by Ryang20718** [comment]
@tjgq yes I’ve seen it occur multiple times

**Comment by tjgq** [comment]
I think it's reasonable to handle it gracefully on the Bazel side, then. It's just profiling logic, so occasionally swallowing an error shouldn't compromise correctness.
