### ISSUE TITLE
There is no (easy) way to retrieve py_binary script location from external repository

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#2452]
/CC @damienmg @dslomov 

From Gerrit Code Review project or other related project like Gitiles or more than 100 Gerrit plugins we consume Skylark rules from Bazlets repository, by including Gerrit's (or related projects) WORKSPACE file:

```
NAME = "com_googlesource_gerrit_bazlets"

def load_bazlets(
    commit,
    local_path = None
  ):
  if not local_path:
      native.git_repository(
          name = NAME,
          remote = "https://gerrit.googlesource.com/bazlets",
          commit = commit,
      )
  else:
      native.local_repository(
          name = NAME,
          path = local_path,
      )
```

Now, we define in Bazlets repository number of `py_binary` rules,
e.g. for Eclipse project generation, for Maven Central publishing,
etc, p.p.

For **reasons**, we cannot use `bazel run @bazlets//:foo` and would like
to access those python scripts from gerrit or other plugins. For that we
need to retrieve the script location from external repository. Now, we have
noticed, that there is no obvious way to achieve that.

Given this rule in bazlets repository:

```
package(
    default_visibility = ["//visibility:public"],
)

py_binary(
    name = "project",
    srcs = ["project.py"],
    main = "project.py",
)
```

We would like to call `project.py` from plugin project. One hacky
way to do it is to define this rule in bazlelts repository
`py_binary_path.bzl`:

```
def _py_binary_path_impl(ctx):
  """rule to retrieve python script location."""
  content = ""
  for f in ctx.attr.py_binary_label.py.transitive_sources:
    if ctx.attr.name in f.path:
      content += f.path
  ctx.file_action(output = ctx.outputs.output, content=content)

py_binary_path = rule(
    attrs = {
        "py_binary_label": attr.label(mandatory = True),
    },
    outputs = {
        "output": "%{name}.txt",
    },
    implementation = _py_binary_path_impl,
)
```

And call this rule from plugin with:

```
# TODO(davido): This is a hack. We know the py_binary rule,
# but for **reasons** we cannot use `bazel run <rule>.
# Unfortunately, a query to retrieve the path was removed
# in Bazel. So we are forced to do this dirty hack to access
# python script outside of the Bazel.
py_binary_path(
    name = "project.py",
    py_binary_label = "@com_googlesource_gerrit_bazlets//tools/eclipse:project",
)
```

Now, calling this rule from the plugin project would give us the result
we are looking for, dumped in the output file from this rule:

```
$ bazel build tools/eclipse:project.py
INFO: Found 1 target...
Target //tools/eclipse:project.py up-to-date:
  bazel-bin/tools/eclipse/project.py.txt
INFO: Elapsed time: 0.078s, Critical Path: 0.00s
```

Now investigating the resulting file content:

```
$ cat bazel-bin/tools/eclipse/project.py.txt
external/com_googlesource_gerrit_bazlets/tools/eclipse/project.py
```

reveals the location of `py_binary` utility from the external repository.
we are looking for. With a wrapper script we could call it in the end:

```
$ cat ./tools/eclipse/project.sh
#!/bin/bash

bazel build tools/eclipse:project.py
`bazel info output_base`/`cat bazel-bin/tools/eclipse/project.py.txt` -n gitiles -r . -x servlet_api_2_5
```

And the result is:

```
$ ./tools/eclipse/project.sh
INFO: Found 1 target...
Target //tools/eclipse:project.py up-to-date:
  bazel-bin/tools/eclipse/project.py.txt
INFO: Elapsed time: 0.084s, Critical Path: 0.00s
INFO: Found 1 target...
Target //tools/eclipse:main_classpath_collect up-to-date:
  bazel-bin/tools/eclipse/main_classpath_collect.runtime_classpath
INFO: Elapsed time: 1.951s, Critical Path: 0.00s
INFO: Found 1 target...
Target //tools/eclipse:classpath up-to-date:
  bazel-bin/tools/eclipse/libclasspath.jar
INFO: Elapsed time: 4.069s, Critical Path: 3.54s
```

Please, help us to avoid those ugly hacks.

**Comment by mgood** [comment]
I came across this looking for a way to work around `bazel run` holding the lock while the target is running (we want to build, then run some long-running tools).

You don't elaborate on your "reasons" but if you or anyone else is looking for a similar workaround to the lock with `bazel run`, #2337 is more specifically requesting a solution to that. It also pointed me at this example script that solved the problem for me:
https://github.com/bazelbuild/bazel/blob/master/scripts/bazel-run.sh

**Comment by davido** [comment]
It was reported, that the path can be retrieved using `bazel query` and replacing `BUILD` with the script name:

```
`bazel query @com_googlesource_gerrit_bazlets//tools/eclipse:project --output location | sed s/BUILD:.*//`project.py 
```

**Comment by davido** [comment]
Not sure if it's still relevant.
