### ISSUE TITLE
[bazel.build] Problem with /installفروشگاه گوگل  من  درست  کار نمیکنه    اون  قسمت   امنیتی    کلید سبز   ش خاموش هستش  .

### ISSUE THREAD

**Issue by Shahrkhyzdany** [bazelbuild/bazel#24533]
### Page link:

https://bazel.build/install

### Problem description (include actual vs expected text, if applicable):

فروشگاه  گوگل من درست کار نمیکنه

**Comment by sgowroji** [comment]
Hi @Shahrkhyzdany, We are closing this issue since it doesn't have valid details. Please tag `@bazelbuild/triage` if you have any questions or want this reopened.
