### ISSUE TITLE
Implement all repository rules in Skylark

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2453]
### Description of the problem / feature request / question:

TL;DR: Stop cheating with repository rules

Currently there is a lot of capabilities available to builtin repository rules that are very cumbersome to implement in Skylark (e.g. extending on `new_local_repository`). To really ensure that Skylark is up for the task of implementing sophisticated repository rules it would be good if all repository rules would be implemented in Skylark. This way we all have the same quality of weaponry.

### Anything else, information or logs or outputs that would be helpful?
IMO this is necessary for a 1.0

**Comment by meteorcloudy** [comment]
//cc @kchodorow

**Comment by meisterT** [comment]
@laurentlb do you know if this is done already?

**Comment by laurentlb** [comment]
I think this can be closed.
