### ISSUE TITLE
Running py_binary fails on Windows without Python in PATH

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2455]
### Description of the problem / feature request / question:

When trying to execute a `py_binary` named `collect` it complains:

    /usr/bin/env: ‘python’: No such file or directory
    ERROR: Non-zero return code '127' from command: Process exited with status 127.

Looking into `collect` and `collect.temp`, at least there they have that shebang entry.

### If possible, provide a minimal example to reproduce the problem:

`BAZEL_PYTHON` is set to `C:/My/Path/python3/python.exe`.

### Environment info
* Operating System: Windows 10

* Bazel version (output of `bazel info release`): 855fbe9

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
Nope

### Anything else, information or logs or outputs that would be helpful?
Since `C:/My/Path/python3` is not in path, `env` will not find `python.exe`. For Windows why not use `BAZEL_PYTHON` path directly?

**Comment by meteorcloudy** [comment]
Another way to run the python binary is `python ./bazel-bin/foo/bar/py_binary`, does it works for you as a workaround?

**Comment by abergmeier-dsfishlabs** [comment]
> Another way to run the python binary is python ./bazel-bin/foo/bar/py_binary, does it works for you as a workaround?

AssertionError: Could not find python binary: python3.exe

Looking into `__main__.py` it is hardcoded as `python3`.

**Comment by meteorcloudy** [comment]
Yes, thanks for spotting this, we should fix that!

**Comment by abergmeier-dsfishlabs** [comment]
Follow up is #2457

**Comment by dslomov** [comment]
Is this now fixed @meteorcloudy @philwo ?

**Comment by meteorcloudy** [comment]
No, we'll still need python in PATH during runtime, if building `py_bianry` without specifying `--python_path`. Besides, if we want to run the binary directly, `/usr/bin/env python` also needs python in PATH.
This is also the case on Linux.

**Comment by dslomov** [comment]
Ok i think it is reasonable to expect python in PATH on Windows too if that is the case on Linux
