### ISSUE TITLE
[8.0.0] Use the baseline exec config in BaselineOptionsFunction so that we don't discard the analysis cache for exec-configured nodes when non-exec flags change.

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#24554]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/559f6d1d51db60c1b2fa773d0df0256d5fc2ea58

### Category

team-Configurability

### Reviewers

@katre

**Comment by bazel-io** [comment]
Failed commits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/559f6d1d51db60c1b2fa773d0df0256d5fc2ea58.
Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
cc: @fmeum

**Comment by katre** [comment]
Why cherrypick this change? It depends on (at least) 37d733fe121a4e47c006493769310701f44fc8b2, but the feature isn't (I think) finished yet.

Bringing in @susinmotion to discuss.

**Comment by fmeum** [comment]
We can cherry pick it when all commits have landed.
