### ISSUE TITLE
`--zip_undeclared_test_outputs=false` crashes Bazel if tests create outputs in nested subdirectories

### ISSUE THREAD

**Issue by hvadehra** [bazelbuild/bazel#24578]
### Description of the bug:

Bazel crashes [here](https://github.com/bazelbuild/bazel/blob/863ba67296339b46bbd51a0f4eac0a05f77d229c/src/main/java/com/google/devtools/build/lib/exec/StandaloneTestStrategy.java#L185) while attempting to rewrite test outputs for non-last-attempts 

### Which category does this issue belong to?

Local Execution

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

 - Have a failing test that creates outputs under nested subdirs
 - Use Bazel that has https://github.com/bazelbuild/bazel/commit/489d08bf472f4568b3f7f478a8747a30cb956111
 - Execute with --flaky_test_attempts=2

### What is the output of `bazel info release`?
release 8.0.0rc7

_No response_

### If this is a regression, please try to identify the Bazel commit where the bug was introduced with bazelisk --bisect.

489d08bf472f4568b3f7f478a8747a30cb956111

### Any other information, logs, or outputs that you want to share?

First observed in https://buildkite.com/bazel/clion-plugin/builds/23996#01939224-067c-4206-a972-bac3d852299d

**Comment by iancha1992** [comment]
@bazel-io fork 8.0.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 8.0.0 RC8](https://github.com/bazelbuild/bazel/releases/tag/8.0.0rc8). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=8.0.0rc8. Thanks!
