### ISSUE TITLE
Running py_binary with standard Python3 for Windows fails to find python3.exe

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2457]
### Description of the problem / feature request / question:

When running a `py_binary` (inside or outside of Bazel) with `C:/My/Path/python3/python.exe` it fails with:

    AssertionError: Could not find python binary: python3.exe

Looking into `__main__.py` it is hardcoded as `python3`.

### If possible, provide a minimal example to reproduce the problem:
Download Python 3.6 from python.org and execute a `py_binary` for Python 3.

### Environment info
* Operating System: Windows 10

* Bazel version (output of `bazel info release`): 855fbe9

**Comment by meteorcloudy** [comment]
Thanks, I just found that adding `build --python3_path="C:/Program Files/Anaconda3/python"` during the build should fix this.

**Comment by meteorcloudy** [comment]
But it is a bit weird that you need to specify python twice for bazel.

**Comment by Carmezim** [comment]
had this issue when building TensorFlow from source on Windows

**Comment by dslomov** [comment]
@meteorcloudy is this fixed now?

**Comment by meteorcloudy** [comment]
Yes, it is.
