### ISSUE TITLE
Apply cxxopts to all cc_* on non-MSVC

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2458]
### Description of the problem / feature request / question:

We have the following entry in our `tools/bazel.rc`:

    build --cxxopts=-Werror=sequence-point

This leads to warnings when compiling with MSVC.
Now, is there any way of limiting that to non-MSVC?

### Environment info
* Operating System: Windows 10
* Bazel version (output of `bazel info release`): 855fbe9

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
Similar: https://groups.google.com/forum/#!topic/bazel-discuss/Jd14TyAXlTM

**Comment by meteorcloudy** [comment]
No, I don't think we can do this in bazelrc file, is using `select` in BUILD file an option?

**Comment by meteorcloudy** [comment]
Maybe you can write a macro for cc_* rules?

**Comment by abergmeier-dsfishlabs** [comment]
> Maybe you can write a macro for cc_* rules?

If this is the recommended way, I will.

**Comment by david-german-tri** [comment]
> > Maybe you can write a macro for cc_* rules?
> If this is the recommended way, I will.

FWIW, we will be doing this on [RobotLocomotion/drake](https://github.com/RobotLocomotion/drake) because of #2444.

**Comment by meteorcloudy** [comment]
Looks like we have a solution here, reopen or file a new one if you have any other problem. :)

**Comment by abergmeier-dsfishlabs** [comment]
> Looks like we have a solution here, reopen or file a new one if you have any other problem. :)

Thanks.
