### ISSUE TITLE
[8.0.0] Cherry-pick for "Add missing rules_apple allowlist alias"

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#24590]
### Commit IDs

dd02b9e52206499ede851a2113fd82a533ee4f67, 2e58ac01960c967b3b529ef086805a7e9191b041

### Category

team-Rules-API

### Reviewers

@pzembrod

**Comment by bazel-io** [comment]
Failed commits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/dd02b9e52206499ede851a2113fd82a533ee4f67, https://github.com/bazelbuild/bazel/commit/2e58ac01960c967b3b529ef086805a7e9191b041.
Please resolve manually.
cc: @bazelbuild/triage
