### ISSUE TITLE
Can't build grpc++ generated files with bazel.

### ISSUE THREAD

**Issue by ioctl0** [bazelbuild/bazel#2459]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

Building generated grpc.pb.cc files does not work since metadata_map.h and slice.h are not part of the "grpc++_codegen_base" target. Manually fixing the BUILD file works.

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### Environment info
* Operating System:
Debian

* Bazel version (output of `bazel info release`):
0.4.3

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
No.

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).
external/grpc_git/src/cpp/common/channel_filter.cc:39:10: fatal error: 'grpc++/impl/codegen/slice.h' file not found

external/grpc_git/include/grpc++/impl/codegen/client_context.h:60:10: fatal error: 'grpc++/impl/codegen/metadata_map.h' file not found

**Comment by ioctl0** [comment]
(This is at HEAD)

**Comment by meteorcloudy** [comment]
@ioctl0 Looks like an issue with grpc instead of Bazel? Can you file this bug to them?

**Comment by ioctl0** [comment]
Oh man. I thought I _had_. *shamecube*
