### ISSUE TITLE
Debug symbols path not resolving symlinks

### ISSUE THREAD

**Issue by dreisicht** [bazelbuild/bazel#24602]
### Description of the bug:

My built binary has a slightly different path compiled for the debug symbols. Expected is `/private/var/tmp/_bazel_username/a400ea441e3cbaea85fa60d80a42ac3a/execroot/_main/src/main/main.cc`. The path I'm getting is `/var/tmp/_bazel_username/a400ea441e3cbaea85fa60d80a42ac3a/execroot/_main/src/main/main.cc`. Note the missing `/private/`. Under MacOS `/var/tmp` is a symlink, that resolves to `/private/var/tmp`.

### Which category does this issue belong to?

C++ Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build a simple cc_binary target with `-c dbg` mode and debug the file with lldb.

### Which operating system are you running Bazel on?

MacOS 15.1.1

### What is the output of `bazel info release`?

release 7.4.1-homebrew

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
https://github.com/dreisicht/cpp_udemy2.git
5c652a6017d21fee94508941eb9caa1c48a47491
```

### Any other information, logs, or outputs that you want to share?

I'm using VS Code to launch the debugging session with the following `launch.json` config.
```
    {
      "name": "Bazel debug with lldb (MacOS)",
      "type": "cppdbg",
      "request": "launch",
      "targetArchitecture": "arm64",
      "program": "${workspaceFolder}/bazel-bin/${relativeFileDirname}/${fileBasenameNoExtension}",
      "args": [],
      "preLaunchTask": "Build current Bazel file (debug)",
      "stopAtEntry": true,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "externalConsole": false,
      "MIMode": "lldb",
      "sourceFileMap": {
        ".": "${workspaceFolder}"
      }
```

I have already disabled sandboxing since that generates ever changing paths with the different sandboxes. See my `.bazelrc`:
```
build --action_env=BAZEL_CXXOPTS="-std=c++20"

build --copt=-fdiagnostics-color=always
run --copt=-fdiagnostics-color=always

build --strip=never
build --spawn_strategy=standalone
build --sandbox_debug
build --features=oso_prefix_is_pwd

test --test_output=streamed
```

**Comment by keith** [comment]
The repo link is currently private

**Comment by dreisicht** [comment]
I made it public. I'm currently on the `section15` branch, using the `//src/section15:section15` target.

**Comment by keith** [comment]
when building on macOS you'll want to use the apple_support toolchain, found here https://github.com/bazelbuild/apple_support which solves this apple specific nuances. In this case that just means adding the most recent version to your MODULE.bazel, which automatically registers the toolchain. Doing that on your project resolves this issue. Please file any issues you find with it there!
