### ISSUE TITLE
Bazel does not properly handle nested workspaces from vendorized dependencies

### ISSUE THREAD

**Issue by chpatton013** [bazelbuild/bazel#2461]
### Description of the problem:

Bazel does not properly handle nested workspaces from vendorized dependencies.
* Bazel targets within dependencies are evaluated relative to the containing workspace. This causes commands to work correctly when run from within the vendorized dependency, but to fail when run in from the parent workspace.
* Dependencies have no way to describe their licensing at a workspace-level, so modifications must be made to BUILD files throughout the vendorized dependency to add license information.

### Minimal example:

https://github.com/chpatton013/bad_dependency
```
%> tree
.
├── BUILD
├── WORKSPACE
└── dependency
    ├── BUILD
    ├── WORKSPACE
    └── build.bzl
```

From `//dependency`, run `bazel build ...`. Build is successful.
```
%> bazel build ...
INFO: Found 0 targets...
INFO: Elapsed time: 0.151s, Critical Path: 0.00s
```

From `//`, run `bazel build ...`. Build is unsucessful.
```
%> bazel build ...
ERROR: package contains errors: dependency.
ERROR: error loading package 'dependency': Extension file not found. Unable to load file '//:build.bzl': file doesn't exist or isn't a file.
INFO: Elapsed time: 0.148s
```

### Environment info
* Operating System: Ubuntu
* Bazel version (output of `bazel info release`): 0.4.3
* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`): release 0.4.3-2017-01-23 (@065e9ef)

**Comment by meteorcloudy** [comment]
//cc @kchodorow Can you take a look at this?

**Comment by kchodorow** [comment]
I think this is the same as #2811.  What does your WORKSPACE file definition for the `dependency/` repo look like?

**Comment by katre** [comment]
I just re-tested this, it seems to be working now. Closing as obsolete.
