### ISSUE TITLE
[8.0.1] Make rlocation in test-setup.sh compatible with /bin/sh

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#24627]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/9ed06ad024bfc6633fb098ed57d2a8cbb

### Category

team-OSS

### Reviewers

@meteorcloudy

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/24628: https://github.com/bazelbuild/bazel/commit/9ed06ad024bfc6633fb098ed57d2a8cbb.

**Comment by iancha1992** [comment]
Cherry-picking as per: https://github.com/bazelbuild/bazel/commit/9ed06ad024bfc6633fb098ed57d2a8cbb0e532f0#commitcomment-150153422

cc: @fmeum
