### ISSUE TITLE
[8.1.0] Please cherry pick "Retry the cleanup of downloadAndExtract #24295" to 8.0 (if not also 7.4). 

### ISSUE THREAD

**Issue by sthornington** [bazelbuild/bazel#24622]
### Commit IDs

99a27f6

### Category

team-ExternalDeps

### Reviewers

@Wyverald

**Comment by bazel-io** [comment]
Cherry-pick was attempted, but failed to push. Please check if the branch, cp_ondemand_24622-8.1.0, already exists
cc: @bazelbuild/triage

**Comment by sthornington** [comment]
Thanks - I think separately this has been cherry-picked into 8.0.1 so maybe this is "done" ?  https://github.com/bazelbuild/bazel/pull/24630. I would still love to see it in a 7.4.2 so I can postpone the 8.0 migration until a more convenient time, but I don't see any signs of anyone making a patch release of 7.4 at the moment.

**Comment by iancha1992** [comment]
Yes, my bad. It's all good then. Thanks

**Comment by iancha1992** [comment]
Yes, this will be included in Bazel 8. I did not see that. But I am not sure if this will be included in Bazel 7. WDYT? @meteorcloudy

**Comment by iancha1992** [comment]
@sthornington We've decided to release 7.5 in January. Here's the PR: https://github.com/bazelbuild/bazel/pull/24665. Thank you!

**Comment by iancha1992** [comment]
Closing this now in favor of: https://github.com/bazelbuild/bazel/issues/24629
