### ISSUE TITLE
[8.0.1] 56329b904b8adc284adb3a06b36ef061521e60f0 --> 8.0.1

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel#24626]
### Commit IDs

56329b904b8adc284adb3a06b36ef061521e60f0

### Category

team-CLI

### Reviewers

@meisterT

**Comment by bazel-io** [comment]
Failed commits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/56329b904b8adc284adb3a06b36ef061521e60f0.
Please resolve manually.
cc: @bazelbuild/triage
