### ISSUE TITLE
Windows, cc_configure.bzl: do not use `cygpath`

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2463]
`cc_configure.bzl` performs a call to `cygpath -m /`, which only works if bazel runs under MSYS. This will not work when we cut the MSYS dependency (#2107).

**Comment by laszlocsomor** [comment]
@meteorcloudy : FYI.
I have a fix almost ready.

**Comment by meteorcloudy** [comment]
Ha, thanks!
