### ISSUE TITLE
`//src/main/native:windows_jni` build fails mysteriously

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2464]
### Description of the problem / feature request / question:

My `$PATH` doesn't normally contain MSYS's directory early enough, therefore running `find` actually runs `C:/Windows/System32/find.exe` instead of `/usr/bin/find`.

If I run `export PATH="/bin:/usr/bin"` then of course I can run `/usr/bin/find` with just `find`, but when I try to build `//src/main/native:windows_jni` the `PATH` of the action is my default `PATH`, not the one I just exported, so the shell script in that genrule is trying to locate Visual Studio with Windows' find, and fails mysteriously:

```
# export PATH="/bin:/usr/bin"

# bazel --output_user_root=/c/tmp3 build src/main/native:windows_jni --verbose_failures
(...)
WARNING: C:/tmp3/nYhaG828/external/bazel_tools/tools/cpp/cc_configure.bzl:57:3:
Auto-Configuration Warning: Visual Studio found at C:\Program Files (x86)\Microsoft Visual Studio 14.0
.
INFO: Found 1 target...
ERROR: C:/work/bazel/src/main/native/BUILD:75:1: Executing genrule //src/main/native:windows_jni failed: bash.exe failed: error executing command
  cd C:/tmp3/nYhaG828/execroot/bazel
  SET PATH=C:\Python27;(...);C:\tools\msys64\
  C:/tools/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; src/main/native/build_windows_jni.sh bazel-out/local-fastbuild/bin/src/main/native/windows_jni.dll src/main/native/windows_file_operations.cc src/main/native/windows_file_operations.h src/main/native/windows_processes.cc src/main/native/windows_util.cc src/main/native/windows_util.h: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Visual Studio not found
--version-sortThe system cannot find the file specified.
Target //src/main/native:windows_jni failed to build
INFO: Elapsed time: 1.210s, Critical Path: 0.43s
```

This is actually WAI, the genrule *should* use the default PATH to be deterministic, and our [installation guide](https://bazel.build/versions/master/docs/windows.html#requirements) even says you should have MSYS on the PATH. However:

-  maybe the documentation should say MSYS should be the first element on the PATH to avoid such mysterious errors, and
- the JNI compilation script shouldn't need to discover VS on its own, should receive it as some parameter instead

**Comment by laszlocsomor** [comment]
Related to #2107.

**Comment by meteorcloudy** [comment]
How about we get rid of this hack, and build windows jni dll using cc_binary in MSVC bazel build? Like: https://github.com/bazelbuild/bazel/blob/master/examples/windows/dll/BUILD#L8

Ideally, it should be a cc_library on Windows, but we use cc_binary to build `.so` file on Unix as well.

**Comment by laszlocsomor** [comment]
SGTM, but we need the hack when building for msys/gcc.
