### ISSUE TITLE
Windows: bazel server terminates every time I run a command

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2466]
Every time I run bazel command, it shows:
```
Cannot terminate server process with PID 9508
```

I bisected and found the culprit is 855fbe9ee447b7b37fd8c73dbc047d69b7ceffcf

Also noticed if `TMPDIR` is set, this doesn't happen anymore.

//cc @laszlocsomor Any idea?

**Comment by laszlocsomor** [comment]
Ah, so that's the culprit. Thanks for bisecting it.

I don't know why it's happening, please feel free to roll back that change. I can figure it out later.

**Comment by meteorcloudy** [comment]
No problem!
