### ISSUE TITLE
Does not match configuration in external repository properly

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2469]
Matching the configuration of the contained workspace fails:

`WORKSPACE`:

    workspace(name="root")
    new_http_archive(
        name = "foo",
        url = "http//uhu.com/glue.zip",
        build_file = "third_party/BUILD.foo",
    )

`BUILD`:

    config_setting(
        name = "windows_x86_64",
        values = {"cpu": "x64_windows_msvc"},
        visibility = ["//visibility:public"],
    )

`.bazelrc`:

    build --cpu=x64_windows_msvc

`third_party/BUILD.foo`

    cc_library(
        name = "foo",
        linkopts = select({
            "@root//:windows_x86_64": [],
        }),
    )

with:

    Configurable attribute "linkopts" doesn't match this configuration (would a default condition help?).
    Conditions checked:
     @root//:windows_x86_64

### Environment info
* Operating System: Windows 10
* Bazel version (output of `bazel info release`): 855fbe9

**Comment by abergmeier-dsfishlabs** [comment]
Replacing `@root//:windows_x86_64` by `@//:windows_x86_64` fails, too.

**Comment by meteorcloudy** [comment]
Yeah, this is not supported yet. I would suggest moving the definition of `config_setting` into `third_party/BUILD.foo` file as a workaround.

**Comment by meteorcloudy** [comment]
@damienmg Should we support referring config_setting from external repository?

**Comment by abergmeier-dsfishlabs** [comment]
> Yeah, this is not supported yet.

How come? We use this on Linux and Mac successfully AFAIR.?

**Comment by meteorcloudy** [comment]
Sorry, you are right! This is supported! And I tested it on Windows, it works!

I guess you specified the wrong cpu name in `.bazelrc` file? Should be `x64_windows_msvc` instead of `x86_windows_msvc`

**Comment by abergmeier-dsfishlabs** [comment]
> I guess you specified the wrong cpu name in .bazelrc file? Should be x64_windows_msvc instead of x86_windows_msvc

Sorry I wrote the `cpu` value in the issue. Corrected now.

**Comment by meteorcloudy** [comment]
Do you mean it still doesn't work with the correct CPU value?

**Comment by meteorcloudy** [comment]
Because it did work on my Windows machine.

**Comment by abergmeier-dsfishlabs** [comment]
> Because it did work on my Windows machine.

Doesn't seem to work on mine. We'll have to have a look at FOSDEM, then.

**Comment by meteorcloudy** [comment]
OK, see you then!

**Comment by abergmeier-dsfishlabs** [comment]
Same problem if I move the `config_setting` to the current package.

**Comment by meteorcloudy** [comment]
Ah, turns out it only works in 0.4.4. Can you try update bazel?

**Comment by abergmeier-dsfishlabs** [comment]
> Ah, turns out it only works in 0.4.4. Can you try update bazel?

Does that mean it should work since 0.4.3 + some change or until 0.4.4 and regressed after?

**Comment by meteorcloudy** [comment]
It should work since 0.4.4

**Comment by abergmeier-dsfishlabs** [comment]
> It should work since 0.4.4

Indeed. Seems to work with 0.4.4. Thanks.
