### ISSUE TITLE
Allow a $HOME variable in .bazelrc

### ISSUE THREAD

**Issue by pgr0ss** [bazelbuild/bazel#247]
I'd like to share my .bazelrc file between machines and even different developeres (and put it in source control). It would be nice if the paths could be relative to the home directory. Something like:

`build --package_path %workspace%:%home%/bazel/base_workspace`

Right now, it seems the best I can do is:

`build --package_path %workspace%:%workspace%/../../bazel/base_workspace`

But this relies on everyone cloning the repo in the same directory.

Thanks,
Paul

**Comment by damienmg** [comment]
Although as said on IRC I think that's a good idea but for your precise use case: could you have a globally installed directory (always at the same path on the machine)? Also for the bazelrc you can put it under tools/bazel.rc for sharing it on the depot. I think you still needs to have the bazel installed at the same place for every user.

**Comment by pgr0ss** [comment]
Yeah, for now I think we'll try use the same paths on every machine.

**Comment by hanwen** [comment]
you can now use %workspace% in bazelrc, does that help?

See e3681d1fb21efd7d0c597965c3642647649b417c

**Comment by pgr0ss** [comment]
That looks interesting. I'll have to check it out.

**Comment by damienmg** [comment]
Downgrading to P4 as there is an acceptable workaround. Contributions welcomed :)

**Comment by helenaut** [comment]
I am not sure %workspace% works for things outside of imports? I am trying to use it like:

`test --run_under=%workspace%/path/to/bash/file.sh`

**Comment by kchodorow** [comment]
Unfortunately, %workspace% is specially interpreted by --package_path, other options don't know how understand it.

**Comment by helenaut** [comment]
Thanks Kristina.

**Comment by ulfjack** [comment]
The tools used by the built-in rules are now bundled into Bazel, so --package_path should be unnecessary in the vast majority of use cases. I'm closing this. Let me know if there's still something to be done here.
