### ISSUE TITLE
iOS application fails to build with error "No toolchain found for cpu 'watchos_i386", only when invoked with option "--experimental_enable_objc_cc_deps"

### ISSUE THREAD

**Issue by adamhowardprice** [bazelbuild/bazel#2471]
When using [Tulsi](https://github.com/bazelbuild/tulsi) to generate an Xcodeproj for an `ios_application`, we ran into a problem in which that project would fail to build with the following error: `"No toolchain found for cpu 'watchos_i386'" `. This issue appears to be the same as is written up [here](https://groups.google.com/forum/#!topic/tulsi-discuss/An-de9qRXYo).

It appears this issue only occurs when the option `--experimental_enable_objc_cc_deps` is used. This is one of the default options when building with Tulsi. The project builds successfully when passing the option `--noexperimental_enable_objc_cc_deps` to override it.

I spoke with a Google engineer (@aragos) who mentioned that this was likely an unintended consequence of something else in Bazel.

I wasn't sure whether to file this issue against Bazel or Tulsi, so I filed both. The Tulsi issue is https://github.com/bazelbuild/tulsi/issues/3

**Comment by meteorcloudy** [comment]
//cc @lfpino @c-parsons Any idea here?

**Comment by aragos** [comment]
This is a Tulsi issue, not a Bazel issue as such. The flag should only be set if toolchains for all required Apple platforms are part of your --crosstool_top. Tulsi should avoid setting this flag for now, at least until #1279 is fixed.

**Comment by adamhowardprice** [comment]
@abaire Closing this in favor of https://github.com/bazelbuild/tulsi/issues/3
