### ISSUE TITLE
Bazel 8.0.0 omits repo mapping for __main__

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/bazel#24717]
### Description of the bug:

Before Bazel version 8.0.0 building a binary target in the main repo with a runfiles library dependency and a data dependency from the main repo would produce a repo mapping file that contains a mapping for `__main__` of the form
```
,__main__,_main
```
As of Bazel version 8.0.0 this is no longer the case and the repo mapping is instead empty.

This causes a runfiles lookup failure if the binary tries to look up the data file by runfiles path of the form `__main__/runfiles/data.txt`.

Using Bazelisk bisect I identified https://github.com/bazelbuild/bazel/commit/5881c38c54416add9faec35b7731954f4baf12d8 as the commit that changed this behavior. Indeed, if I pass `--enable_workspace`, then the repo mapping file again includes the entry for `__main__`.

I don't find any mention of `__main__` being a WORKSPACE specific feature in the [bzlmod runfiles proposal document](https://github.com/bazelbuild/proposals/blob/53c5691c3f08011f0abf1d840d5824a3bbe039e2/designs/2022-07-21-locating-runfiles-with-bzlmod.md#2-extend-the-runfiles-libraries-to-take-repository-mappings-into-account). So, this is unexpected behavior.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a binary target with runfiles dependencies, e.g.
```
load("@rules_zig//zig:defs.bzl", "zig_binary")

zig_binary(
    name = "binary",
    data = ["data.txt"],
    main = "main.zig",
    deps = ["@rules_zig//zig/runfiles"],
)
```

Build the target using `bazel build` and inspect the corresponding repo mapping file, e.g. `cat bazel-bin/runfiles/binary.repo_mapping`.

The example on which the issue was discovered [is here](https://github.com/aherrmann/rules_zig/blob/e03cb5cecbea8e7085aebeac686ca2f353b4ed75/zig/tests/integration_tests/workspace/runfiles/BUILD.bazel).

### Which operating system are you running Bazel on?

Ubuntu 22.04

### What is the output of `bazel info release`?

release 8.0.0

### If this is a regression, please try to identify the Bazel commit where the bug was introduced with bazelisk --bisect.

https://github.com/bazelbuild/bazel/commit/5881c38c54416add9faec35b7731954f4baf12d8

### Have you found anything relevant by searching the web?

The [bzlmod runfiles proposal](https://github.com/bazelbuild/proposals/blob/53c5691c3f08011f0abf1d840d5824a3bbe039e2/designs/2022-07-21-locating-runfiles-with-bzlmod.md#2-extend-the-runfiles-libraries-to-take-repository-mappings-into-account).

### Any other information, logs, or outputs that you want to share?

This was identified on https://github.com/aherrmann/rules_zig/pull/410 ([CI run](https://github.com/aherrmann/rules_zig/actions/runs/12346776416/job/34452847501#step:3:287)).
You can test locally by checking out that PR and executing
```
$ touch zig/tests/integration_tests/.bazelrc.meta
$ cd zig/tests/integration_tests/workspace
$ USE_BAZEL_VERSION=8.0.0 bazel run //runfiles:binary
$ cat bazel-bin/runfiles/binary.repo_mapping
```

**Comment by fmeum** [comment]
`__main__` is the (undocumented?) default WORKSPACE name if users don't set `workspace(name = "something")`. With `--enable_workspace --enable_bzlmod`, the repo mapping of the main repository contains an entry that maps the WORKSPACE name to the main repo. That's why with `--noenable_workspace` this line is no longer present.

You have a few options:
* Replace `__main__` with whatever you specified as `module(..., repo_name = "...")` (or `name` if `repo_name` isn't set).
* Replace `__main__` with `_main`, which is the fixed name of the runfiles directory of the main repository with Bzlmod.

**Comment by aherrmann** [comment]
> `__main__` is the (undocumented?) default WORKSPACE name if users don't set `workspace(name = "something")`.

`__main__` is explicitly mentioned in the [bzlmod runfiles proposal](https://github.com/bazelbuild/proposals/blob/53c5691c3f08011f0abf1d840d5824a3bbe039e2/designs/2022-07-21-locating-runfiles-with-bzlmod.md#2-extend-the-runfiles-libraries-to-take-repository-mappings-into-account). So, I wouldn't consider it undocumented. Yes, it's a proposal, but it is also the only documentation on how to create a runfiles library with bzlmod support that I'm aware of.

> Replace `__main__` with whatever you specified as `module(..., repo_name = "...")` (or `name` if `repo_name` isn't set).

In my case the `MODULE.bazel` file has no `module(name = ...)` line so far and the repo mapping file is empty for Bazel 8 and `--noenable_workspace`. I notice that when I specify different names in `MODULE.bazel`'s `module()` line and `WORKSPACE.bzlmod`'s `workspace` line then the repo mapping contains two entries, one for the module name and one for the workspace name. I wasn't aware that these two are treated completely separately.

> Replace `__main__` with `_main`, which is the fixed name of the runfiles directory of the main repository with Bzlmod.

The specific use-case is an integration test for the runfiles library of rules_zig that is supposed to test the repo-mapping functionality. So, using `_main` directly doesn't make sense in this case. For now the test is also used in both bzlmod and workspace modes and Bazel 7 and 8, so I need a solution that works for all combinations.

---

I'm addressing this issue by configuring a repo name in both `module(name = ...)` and `workspace(name = ...)` and adjusting the runfiles test to use that name instead of `__main__`.

**Comment by aherrmann** [comment]
That seems to have addressed the issue, thanks @fmeum for the quick help!

Is `_main` as a name for the main module runfiles directory meant to be stable and something that users should be able to directly reference? Or is it an implementation detail that users shouldn't directly reference and instead always go through `$(rlocationpath ...)` or repo mapping with the module's name/repo-name?

If users should not reference `_main` directly, then it seems that modules that do not specify a name via a `module` entry in their `MODULE.bazel` do not support runfiles lookups via repo mapping. Is that correct?

**Comment by fmeum** [comment]
`_main` is safe to rely on and even required to be "well-known" for runfiles libraries for dynamic languages.

That said, I would very much prefer users give a name to their module and use that instead. It's just much more descriptive.
