### ISSUE TITLE
February release

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2472]
@hermione521 will be our next release manager, hopefully this time it can be 0.5!

**Comment by damienmg** [comment]
As discussed in #2585, we should add a RELNOTES that points to #2585 about the regression on Java type inference.

**Comment by petemounce** [comment]
That ticket mentions a `0.4.5rc1` - please could I be pinged for RCs and releases (though I'm less likely to miss the latter) by automation? Or, perhaps if the announcements could go a to group where those are the only things that arrive there, in addition to the other lists it hits?

**Comment by damienmg** [comment]
bazel-discuss+release-candidate@googlegroups.com is the mail we are sending those announcement, would you need more?

Sorry for missing pinging you, the rc1 is at https://storage.googleapis.com/bazel/0.4.5/rc1/index.html

**Comment by petemounce** [comment]
That group is pretty high-traffic, so I don't monitor it closely. Is it possible to get a different group just for RCs/releases? Or to be included in the set of emails that the release script pings?

**Comment by petemounce** [comment]
The rc is published at https://chocolatey.org/packages/bazel/0.4.5-rc1

**Comment by damienmg** [comment]
Change we need to make sure are in the release:
88b20ae90bdeb77bdfd1c764805bd8ad5d55f3d7
a28b54033227d930672ec7f2714de52e5e0a67eb

**Comment by hermione521** [comment]
Pushed 0.4.5-rc2, cherry-picked:
https://github.com/bazelbuild/bazel/commit/a28b54033227d930672ec7f2714de52e5e0a67eb
https://github.com/bazelbuild/bazel/commit/6d1d424b4c0da724e20e14235de8012f05c470f8

This change is already in:
https://github.com/bazelbuild/bazel/commit/88b20ae90bdeb77bdfd1c764805bd8ad5d55f3d7

**Comment by petemounce** [comment]
Published 2nd RC to chocolatey.

**Comment by damienmg** [comment]
Thanks!

**Comment by damienmg** [comment]
More cherry-picks: 30490512eb0e48a3774cc4e4ef78680e77dd4e47 and more to come.

**Comment by meteorcloudy** [comment]
Added https://github.com/bazelbuild/bazel/issues/2613 as a release blocker, because TensorFlow is failing with Bazel at HEAD due to this bug.
@laszlocsomor already has a fix here: https://bazel-review.googlesource.com/#/c/9126/

**Comment by hermione521** [comment]
https://github.com/bazelbuild/bazel/commit/30490512eb0e48a3774cc4e4ef78680e77dd4e47
is cherry-picked

**Comment by damienmg** [comment]
0785cbb672357d950e0c045770c4567df9fbdc43 also needs cherry-pick. I have 2 in flight change to be cherry-picked and laszlo has one, maybe wait until those next change are pushed to emit a new canary?

**Comment by damienmg** [comment]
So more cherry-picks: 934c1d5e1340bbae9bd7b61a9f3aa3029c7c2c1c 7b295d34f3a4f42c13aafc1cc8afba3cb4aa2985 0768f3e444a121c5c8e8e0bd0bb98772fab0e0e2

Unfortunately there is another regression that came in... So we will need more cherry-picks

**Comment by damienmg** [comment]
So even more cherry-picks: fbad5f0 ed77952

**Comment by hermione521** [comment]
The first 4 commits are cherry-picked. The other 2 commits will be in the next round.

**Comment by damienmg** [comment]
So more cherry-picks yay!

For #2642: 81ae08b
For #2621: cl/149316508 and cl/149369076 when they hit the git repo

**Comment by hermione521** [comment]
the above one and 869d52f145c077e3499b88df752cebc60af51d66 are for #2621

**Comment by damienmg** [comment]
And last cherry-pick: https://github.com/bazelbuild/bazel/commit/d72bc57b60b26245e64f5ccafe023a5ede81cc7f for #2644

**Comment by hermione521** [comment]
All commits above are cherry-picked.
We reach rc5 with 12 cherry-picks :)

**Comment by petemounce** [comment]
Please note #2653; not a regression, but an installation failure that's quite painful.

**Comment by meteorcloudy** [comment]
Please cherry-pick https://github.com/bazelbuild/bazel/pull/2599 after it's submitted. It's needed by TensorFlow to build JNI library on Windows.

**Comment by meteorcloudy** [comment]
92ecbae is the commit from #2599 , please cherry-pick it.

**Comment by petemounce** [comment]
I've pushed RCs 4-6 inclusive.

**Comment by ulfjack** [comment]
I think the non-msys2 binary isn't ready yet.

**Comment by damienmg** [comment]
MSYS2 dependency should be dropped for 0.5 (still estimate, we technically have reached the 0.5 milestone already).

**Comment by kchodorow** [comment]
We haven't reached 0.5, which must include #1262.

**Comment by damienmg** [comment]
Indeed you are right!

**Comment by petemounce** [comment]
Would it be possible to get the cherry-picks section of the release notes to render like a list, like the `incompatible changes`, `new features`, and `important changes` sections?

When [there are many cherry-picks](https://storage.googleapis.com/bazel/0.4.5/rc6/index.html), it's quite hard to read.

**Comment by iirina** [comment]
Please also cherry-pick 36958806f2cd38dc51e64cd7bcc557bd143bbdb6, thanks!

**Comment by damienmg** [comment]
And also 8c00f398d7be863c4f502bde3f5d282b1e18f504 b6ea0d33d3ab72922c8fb3ec1ff0e437af09584d

**Comment by petemounce** [comment]
Pushed rc7: https://chocolatey.org/packages/bazel/0.4.5-rc7

**Comment by renning22** [comment]
Link for non-windows users: https://storage.googleapis.com/bazel/0.4.5/rc7/index.html

**Comment by damienmg** [comment]
Maybe we should post the release announcements to the bug number...

**Comment by damienmg** [comment]
https://github.com/bazelbuild/bazel/releases/tag/0.4.5 <-- release \o/

**Comment by petemounce** [comment]
https://chocolatey.org/packages/bazel/0.4.5 Pushed, in the queue. Thanks for the heads up :)

**Comment by hermione521** [comment]
Finally have a release! Closing this.
