### ISSUE TITLE
[7.5.0] Cherry-pick "Migrate imp to importlib in path_test.py"

### ISSUE THREAD

**Issue by sthornington** [bazelbuild/bazel#24728]
### Commit IDs

5b54c7412cfb251d9ab83e23b37f06504b893331

### Category

team-ExternalDeps

### Reviewers

@iancha1992

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/24732: https://github.com/bazelbuild/bazel/commit/5b54c7412cfb251d9ab83e23b37f06504b893331.
