### ISSUE TITLE
bazel-0.4.4: cannot bootstrap on Windows, latest MSYS

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2473]
Just downloaded the 0.4.4 dist zip, cannot bootstrap it on Windows with latest MSYS. It fails with Java compilation errors while compiling buildjar:

```
(...)
C:\Users\laszlocsomor\AppData\Local\Temp\bazel_O1pr7pGI\src\com\google\devtools\build\buildjar\proto\JavaCompilation.java:9: error: package com.google.protobuf does not exist
      com.google.protobuf.ExtensionRegistryLite registry) {
                         ^
C:\Users\laszlocsomor\AppData\Local\Temp\bazel_O1pr7pGI\src\com\google\devtools\build\buildjar\proto\JavaCompilation.java:13: error: package com.google.protobuf does not exist
      com.google.protobuf.ExtensionRegistry registry) {
                         ^
(...)
100 errors
9 warnings
````

**Comment by laszlocsomor** [comment]
Culprit: https://bazel-review.googlesource.com/c/8408/
This moved the `PATHSEP` reassignment on Windows into `buildenv.sh` which is sourced prior to `compile.sh`, the latter of which then sets `PATHSEP` to ":" unconditionally.

**Comment by laszlocsomor** [comment]
Fixing that is not enough though, there's another breakage, apparently `$JAVA_HOME` isn't quoted somewhere:
```
# ./compile.sh
(...)
🍃  Building Bazel with Bazel.
.ERROR: Bad target pattern 'Files\Java\jdk1.8.0_112': package names may contain only A-Z, a-z, 0-9, '/', '-', '.' and '_'.
INFO: Elapsed time: 0.561s

ERROR: Could not build Bazel
```

**Comment by abergmeier-dsfishlabs** [comment]
Can you fix this in a 0.4.4.1 or 0.4.5?

**Comment by laszlocsomor** [comment]
Yes, we'll fix this after FOSDEM in the next release, whatever version that is. Sorry about the breakage, we didn't have test coverage for from-source bootstrapping on Windows.

**Comment by abergmeier-dsfishlabs** [comment]
> For the time being, you can compile 0.4.3 from source (by applying a one-liner patch, see the known issues), then use that binary to build 0.4.4 or from HEAD.

No worries - I always keep working Bazel binaries around.
