### ISSUE TITLE
[bazel.build] Problem with /start/go

### ISSUE THREAD

**Issue by jishi-lyu** [bazelbuild/bazel#24750]
### Page link:

https://bazel.build/start/go

### Problem description (include actual vs expected text, if applicable):

 % bazel build //:hello 
INFO: Invocation ID: 636645c7-31e6-46cc-b974-7b649a15ab73
ERROR: Skipping '//:hello': no such package '': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /home/user/examples/go-tutorial
WARNING: Target pattern parsing failed.
ERROR: no such package '': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /home/user/examples/go-tutorial
INFO: Elapsed time: 0.078s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by iancha1992** [comment]
@jishi-lyu Could you please provide more details? What is wrong here?

**Comment by fmeum** [comment]
@jayconrod

**Comment by jayconrod** [comment]
Hi @jishi-lyu, it looks like you might be running `bazel build //:hello` from the `go-tutorial` directory instead of one of the subdirectories like `go-tutorial/stage1`.

From the repository root directory, try this:

```
$ cd go-tutorial/stage1/
$ bazel build //:hello
```

**Comment by jishi-lyu** [comment]
ohh nvm, i found the issue, issue was i didn't add workspace and BUILD file
to each workspace, after i manually added these files to each repo, and
also load rules, it works as expected. Thanks!!
