### ISSUE TITLE
documentation: eclipse instructions missing a target

### ISSUE THREAD

**Issue by monchalve** [bazelbuild/bazel#2477]
The docs here: https://bazel.build/contributing.html#creating-an-eclipse-project

Say to add `//src/main/java/...` and `//src/test/java/...` as targets, but it's missing `//src/main/protobuf/...` which is required if you want Eclipse to be aware of the protobuf objs.

Works great otherwise!

**Comment by jin** [comment]
The Eclipse docs are gone, please use IntelliJ for Bazel development instead.
