### ISSUE TITLE
Bazel 8.0.0: local_repository does not define repo name

### ISSUE THREAD

**Issue by neilconway** [bazelbuild/bazel#24787]
### Description of the bug:

In Bazel 8.0.0 (with modules disabled and workspaces enabled), if `repo2` is included as a `local_repository` of `repo1`, the label `//:xyz` in `repo2` can't be used.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/neilconway/bazel-local-repository-repro

### What is the output of `bazel info release`?

release 8.0.0

**Comment by Wyverald** [comment]
Your [.bazelrc file](https://github.com/neilconway/bazel-local-repository-repro/blob/main/.bazelrc) isn't actually taking effect. Each line needs to start with `common` (so `common --enable_workspace`, etc).

**Comment by neilconway** [comment]
@Wyverald ugh, whoops. Thanks!
