### ISSUE TITLE
//src/test/java:shell_test is flaky

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#248]
see https://travis-ci.org/google/bazel/builds/67043690.

It is from teardDown of testInterruptibleCommand(com.google.devtools.build.lib.shell.InterruptibleTest)

**Comment by hanwen** [comment]
we haven't seen this in a while.

**Comment by damienmg** [comment]
http://ci.bazel.io/job/Bazel/306/JAVA_VERSION=1.8,PLATFORM_NAME=ubuntu_15.10-x86_64/console

**Comment by damienmg** [comment]
It's happening every 3 days or so

**Comment by davidzchen** [comment]
The test is still flaky: http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.7,PLATFORM_NAME=ubuntu_15.10-x86_64/340/testReport/junit/com.google.devtools.build.lib.shell/InterruptibleTest/testInterruptibleCommand/

**Comment by davidzchen** [comment]
I'll go ahead and mark `//src/test/java/com/google/devtools/build/lib:shell_test` as flaky.

**Comment by damienmg** [comment]
Problem is that flaky doesn't do anything in bazel :(

**Comment by davidzchen** [comment]
Ah, right. #540
