### ISSUE TITLE
Windows: clean --expunge fails

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2480]
### Description of the problem / feature request / question:

Executing `bazel clean --expunge` leads to:

    INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
    ERROR: C:/tools/msys64/tmp/_bazel_a.bergmeier/dXgGrvqy/server/jvm.out (Permission denied).

### Environment info
* Operating System: Windows 10
* Bazel version (output of `bazel info release`): 0.4.4

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
Nope.

### Anything else, information or logs or outputs that would be helpful?

Searching for `server\jvm.out` in Process Explorer gives two `java.exe` instances keeping a file handle (both seem to be A-servers). One is using it via `C:\Users\a.bergmeier\AppData\Local\Temp` and the other via `C:\tools\msys64\tmp`.

Should `dXgGrvqy` not contain hashed information about the Bazel version and change with each different Bazel binary used?

Currently it seems to always use `dXgGrvqy`, no matter which Bazel binary I am using.

**Comment by meteorcloudy** [comment]
Yes, this is an known issue. Related issues:
https://github.com/bazelbuild/bazel/issues/1586#issuecomment-256290772
https://github.com/bazelbuild/bazel/issues/2077

**Comment by abergmeier-dsfishlabs** [comment]
> Yes, this is an known issue. Related issues:
#1586 (comment)
#2077 

Curious why issues were closed.

**Comment by abergmeier-dsfishlabs** [comment]
> Searching for server\jvm.out in Process Explorer gives two java.exe instances keeping a file handle (both seem to be A-servers). One is using it via C:\Users\a.bergmeier\AppData\Local\Temp and the other via C:\tools\msys64\tmp.

Not related because happens with 1 running java.exe, too.

**Comment by Helcaraxan** [comment]
We have also observed this issue while trying out Windows builds.

**Comment by laszlocsomor** [comment]
Related bugs: #3043, #1906, #1586

**Comment by laszlocsomor** [comment]
https://github.com/bazelbuild/bazel/commit/70ff798abb013ef66fca651e8cfa6c6aea96460b fixed this.
