### ISSUE TITLE
Refering to a missing config_setting from a remote repository give a totally unhelpful error message

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2481]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

This was discovered during review of tensorflow/tensorflow#7073. A build file in a remote repository was refering to a non existent config_settings (`@local_config_cuda//tensorflow:FreeBSD`) in a select. And the error message is:

```
ERROR: /usr/local/google/home/dmarting/.cache/bazel/_bazel_dmarting/e5cce820cc082410b4fcc604db349066/external/local_config_cuda/cuda/BUILD:48:1: no such package '@local_config_cuda//tensorflow': BUILD file not found on package path and referenced by '@local_config_cuda//cuda:cudart_static'
ERROR: /usr/local/google/home/dmarting/.cache/bazel/_bazel_dmarting/e5cce820cc082410b4fcc604db349066/external/local_config_cuda/cuda/BUILD:48:1: no such package '@local_config_cuda//tensorflow': BUILD file not found on package path and referenced by '@local_config_cuda//cuda:cudart_static'
ERROR: Evaluation of query "deps((//tensorflow/... - //tensorflow/examples/android/...))" failed: errors were encountered while computing transitive closure
```

### If possible, provide a minimal example to reproduce the problem:

Clone https://github.com/blodan/tensorflow at commit 1fe382095d590db50c2d0e9133b06802a7389fdc 
And `bazel fetch //...`

### Environment info
* Operating System: Ubuntu 14.04

* Bazel version (output of `bazel info release`):
0.4.4

**Comment by aehlig** [comment]
I just tried to reproduce this errror, but couldn't (the said pull request produced a lot of other errors with current bazel, but not the mentioned); probably bazel has evolved too much in the last two years. In any case, I would need more information to work on this issue.

**Comment by meisterT** [comment]
Closing as per last comment.
