### ISSUE TITLE
comple error [solved]

### ISSUE THREAD

**Issue by AntonyM55** [bazelbuild/bazel#2485]
---------------update----------------------------
build bazel-0.4.1 first, 

$git checkout 0.4.1
$./compile.sh
copy output/bazel to bin path
$git checkout 0.4.4
$bazel build //src:bazel   (use this,not use ./compile.sh)

----------old -----------------------------------------------------------------------------------------------------------------------
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

$ tar zxfv bazel-0.4.4.tar.gz
$ cd bazel-0.4.4/
$./compile.sh
### If possible, provide a minimal example to reproduce the problem:
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch
ERROR: Must specify PROTOC if not bootstrapping from the distribution artifact

### Environment info
* Operating System:
Distributor ID:	CentOS
Description:	CentOS Linux release 7.2.1511 (Core) 

* Bazel version (output of `bazel info release`):
0.4.4

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

Acrroding to this page 
https://bazel.build/designs/2016/10/11/distribution-artifact.html
I set PROTOC 
$export PROTOC=/usr/local/bin/protoc
$./compile.sh
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch
ERROR: Must specify GRPC_JAVA_PLUGIN if not bootstrapping from the distribution artifact

I don't know how to set "GRPC_JAVA_PLUGIN", and it not found @ distribution-artifact.html

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by kchodorow** [comment]
This should probably be documented.

**Comment by chemelnucfin** [comment]
worked for me, except after 0.4.1 I had to repeat with 0.4.2
(fedora 25)

**Comment by aehlig** [comment]
> This should probably be documented.

Our documentation[1] explicitly tells to download a distribution artefact; nowhere
it says to run compile.sh on a random checkout or sources-only tar archive. Also,
the error message has been significantly extended in 967a0a338e05fca60b437c36a52b31eaf706bea8.

So I fail to see the need for more documentation.

[1] https://bazel.build/versions/master/docs/install.html#compiling-from-source

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by qiaohaijun** [comment]
I met the same issue,

**Comment by ittaiz** [comment]
Klaus,
I agree it's documented but I think it might be somewhat hidden. Maybe this
should be highlighted better (not sure where) since it's very typical in
the OSS to checkout a project and try to build it intuitively (like using
compile.sh).
Wdyt about renaming compile.sh?
Also- Does the error message link to the above page in the site? If not
maybe it should

**Comment by asagjj** [comment]
So how can I set "GRPC_JAVA_PLUGIN"?...

**Comment by SanjunLiu** [comment]
ERROR: Must specify GRPC_JAVA_PLUGIN if not bootstrapping from the distribution artifact. How can i do?

**Comment by wangweiye** [comment]
go to download grpc-java https://github.com/grpc/grpc-java
then build it

**Comment by rihardsbar** [comment]
What does it say here ,that contradicts to what most people try to do to get it compiled from source ? 
https://docs.bazel.build/versions/master/install-compile-source.html

**Comment by DlisKeepOnGoing** [comment]
So how can I solve the problem? "ERROR: Must specify GRPC_JAVA_PLUGIN if not bootstrapping from the distribution artifact"

**Comment by wotchin** [comment]
For this error, you must install protocol buffer c++ first, you have finished.
Second, you must choose the bazel-xxx-dist.zip package to compile, this includes third-party dependencies.
such as  bazel-0.23.2-dist.zip, you can download it here:
>https://github.com/bazelbuild/bazel/releases

**Comment by loongson-zn** [comment]
@AntonyM55   how to set "GRPC_JAVA_PLUGIN"？

**Comment by sunmin89** [comment]
> @AntonyM55 how to set "GRPC_JAVA_PLUGIN"？

Hi, I came across the same problem.
My OS is Debian , the solution is to install  the grpc java plugin binary.
```
sudo apt-get update
sudo apt install protobuf-compiler-grpc-java-plugin
```
Find the binary location, and then export.
```
dpkg -L protobuf-compiler-grpc-java-plugin  | \grep bin
export GRPC_JAVA_PLUGIN=/usr/bin/grpc_java_plugin
```
Finally, compile it.
```
env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" bash ./compile.sh
```

I hope this could help others.
