### ISSUE TITLE
Windows: cannot open file foo.exp

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2488]
### Description of the problem / feature request / question:

When building a `foo.dll` with `cc_binary`, when linking everytime there is the error message, that it cannot access `foo.exp`.

### Environment info
* Operating System: Windows 10
* Bazel version (output of `bazel info release`): 0.4.4

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
Nope.

### Anything else, information or logs or outputs that would be helpful?
Example output is:

    C:/Projects/tools/pyabyss/BUILD:31:1: Linking of rule '//pyabyss:abyss.dll' failed: msvc_link.bat failed: error executing command
      cd B:/dXgGrvqy/execroot/tools
      SET PATH=external/local_config_cc/wrapper/bin
      external/local_config_cc/wrapper/bin/msvc_link.bat /DLL /OUT:bazel-out/vc_14_0_x64-py3-fastbuild/bin/pyabyss/abyss.dll -Wl,opengl32.lib -Lexternal/org_python/libs/ -Wl,python35.lib -m64 -Wl,-S -Xcompilation-mode=fastbuild -Wl,@bazel-out/vc_14_0_x64-py3-fastbuild/bin/pyabyss/abyss.dll-2.params: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1104.
       Creating library bazel-out/vc_14_0_x64-py3-fastbuild/bin/pyabyss/abyss.lib and object bazel-out/vc_14_0_x64-py3-fastbuild/bin/pyabyss/abyss.exp
    LINK : fatal error LNK1104: cannot open file 'bazel-out/vc_14_0_x64-py3-fastbuild/bin/pyabyss/abyss.exp'

**Comment by abergmeier-dsfishlabs** [comment]
Sometimes this works. Checking in Process Explorer no Process has a long-term handle on this one. So it probably is a short term handle stored somewhere.

**Comment by dslomov** [comment]
I *think* this is fixed in course of switching off python wrapper.
