### ISSUE TITLE
Show Visual Studio plugin

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2493]
### Description of the problem / feature request / question:

At FOSDEM there was bragging that there IS a Visual Studio plugin. In order to have bragging rights you should publish this on github.

### Environment info
* Operating System: Windows 10

**Comment by dslomov** [comment]
No there is no plugin. There is API for IDE integration: https://bazel.build/blog/2016/06/10/ide-support.html
