### ISSUE TITLE
Installing bazel-0.4.3 via 64-bit CentOS 6.8 causes GLIBCXX_3.4.{14,15,18,19} issues

### ISSUE THREAD

**Issue by icedwater** [bazelbuild/bazel#2495]
### Description of the problem / feature request / question:

I tried unzipping the distributed `bazel-0.4.3-dist.zip` and it couldn't run.

So instead I used the following install script (md5sum): 

    267c26037aea04c1b5df63f670646585  bazel-0.4.3-installer-linux-x86_64.sh

Then I tried to build tensorflow's pip package:

    bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

It doesn't work because there are dependencies on a particular version of libc6/libstdc++:

    /usr/local/bin/bazel: /usr/lib64/libc.so: version `GLIBC_2.12' not found (required by /usr/local/bin/bazel)
    /usr/local/bin/bazel: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /usr/local/bin/bazel)
    /usr/local/bin/bazel: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /usr/local/bin/bazel)
    /usr/local/bin/bazel: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /usr/local/bin/bazel)
    /usr/local/bin/bazel: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by /usr/local/bin/bazel)

### Environment info
* Operating System:
    $ lsb_release -a
    LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
    Distributor ID: CentOS
    Description:    CentOS release 6.8 (Final)
    Release:        6.8
    Codename:       Final

* Bazel version (output of `bazel info release`):
    The above error message was displayed, but I assume it's 0.4.3.

**Comment by icedwater** [comment]
This also applies for 0.3.2.

**Comment by damienmg** [comment]
Please use the distribution artifact and look at https://github.com/bazelbuild/bazel/wiki/FAQ#q2 on how to build on older CentOS. The distribution artifact are not made for old CentOS, we might build some in the future but right now we do not have the bandwidth to support older compiler

**Comment by damienmg** [comment]
Also I want to excuse ourselves for the late answer.
