### ISSUE TITLE
support cpufeatures in android ndk

### ISSUE THREAD

**Issue by ahumesky** [bazelbuild/bazel#2499]
cpufeatures is:
https://developer.android.com/ndk/guides/cpu-features.html

See discussion here:
https://groups.google.com/forum/#!msg/bazel-discuss/N62vXXXJRcw/EOLhEZDwCAAJ

**Comment by aj-michael** [comment]
Quoting the relevant part of the discussion for whoever ends up taking on this feature request:

>  cpufeatures is here (in NDK r12 which is what I happen to have on hand):
./sources/android/cpufeatures/cpu-features.c
./sources/android/cpufeatures/repo.prop
./sources/android/cpufeatures/Android.mk
./sources/android/cpufeatures/NOTICE
./sources/android/cpufeatures/cpu-features.h

**Comment by aj-michael** [comment]
This will eventually need to be documented in a better location, but for now, here is how to use cpufeatures:

    $ cat jni.cc
    #include "ndk/sources/android/cpufeatures/cpu-features.h"
    ...
    AndroidCpuFamily family = android_getCpuFamily();

    $ cat BUILD
    cc_library(
        name = "jni",
        srcs = ["jni.cc"],
        deps = ["@androidndk//:cpufeatures"],
    )
    android_binary(
        name = "app",
        manifest = 'AndroidManifest.xml',
        srcs = glob(["*.java"]),
        deps = [":jni"],
    )

    $ cat WORKSPACE
    android_sdk_repository(name = 'androidsdk')
    android_ndk_repository(name = 'androidndk')

Note that this was added in edcd915 which has not made it into a Bazel release. It might make it into 0.5.0, or else it will be in 0.5.1.
