### ISSUE TITLE
cannot create symbolic link bazel-out Executing Bazel from Docker Container

### ISSUE THREAD

**Issue by r351574nc3** [bazelbuild/bazel#2501]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I have bazel installed in a Debian/Jessie base image docker container. When I execute the following: 
`docker run --rm -v $PWD:/workspace -w /workspace --privileged bazel:0.4.4-debian bazel`

I get the following:
```
____Loading package: @io_bazel_rules_go_toolchain//
____Found 1 target...
WARNING: failed to create one or more convenience symlinks for prefix 'bazel-':
  cannot create symbolic link bazel-out -> /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/motocho/bazel-out:  /workspace/bazel-out (Operation not permitted)
  cannot create symbolic link bazel-workspace -> /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/motocho:  /workspace/bazel-workspace (Operation not permitted)
  cannot create symbolic link bazel-bin -> /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-fastbuild/bin:  /workspace/bazel-bin (Operation not permitted)
  cannot create symbolic link bazel-testlogs -> /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-fastbuild/testlogs:  /workspace/bazel-testlogs (Operation not permitted)
  cannot create symbolic link bazel-genfiles -> /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-fastbuild/genfiles:  /workspace/bazel-genfiles (Operation not permitted).
____Building...

```

### Environment info
* Operating System: Debian/Jessie in Docker container
`Linux be24d2dbdcca 4.4.14-boot2docker #1 SMP Fri Jul 1 21:46:36 UTC 2016 x86_64 GNU/Linux`

* Bazel version (output of `bazel info release`): ```...............
release 0.4.4```

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive) 

I am using a command from #134 that shows this is should work.

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by kchodorow** [comment]
I assume this has something to do with docker permissions, but I'm not very familiar with docker. Damien, could you take a look?

**Comment by damienmg** [comment]
Yes that is more a docker question than a Bazel issue. Basically /workspace is not writable from your docker container.

You should be able to repro with `docker run --rm -v $PWD:/workspace -w /workspace --privileged bazel:0.4.4-debian bash -c "mkdir -p /tmp/test; ln -s /tmp/test bazel-out"`

I don't remember the exact way to test but that's more a docker thing.

**Comment by r351574nc3** [comment]
@damienmg is correct. This works in regular docker. I was using xhyve on Mac OS X for my docker machine which is the real nature of the problem. I think this is resolved.

**Comment by damienmg** [comment]
Great! Thanks for telling us!
