### ISSUE TITLE
Preserve runfiles on Windows

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2503]
### Description of the problem / feature request / question:

I want to debug some `py_test` on Windows. The runfiles sadly get deleted even if with `--sandbox_debug`. @meteorcloudy, @dslomov Is there any way of preserving the runfiles?

### Environment info
* Operating System: Windows 10
* Bazel version (output of `bazel info release`): 0.4.4

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
Nope

**Comment by meteorcloudy** [comment]
Bazel needs symlink to create runfiles tree, but we cannot use it on Windows without admin privilege. So Bazel doesn't create runfiles tree anymore.

But for python, you can decompress the zip file to get the runfiles tree.

**Comment by abergmeier-dsfishlabs** [comment]
So is there only the zip content in the temp runfiles dir? What about data dependencies?

**Comment by meteorcloudy** [comment]
If it's declared in the `data` attribute of the `py_test`, it should also be zipped into the zip file.

**Comment by abergmeier-dsfishlabs** [comment]
> If it's declared in the data attribute of the py_test, it should also be zipped into the zip file.

Ok, so the `.pyd` is in the zip file. Now the question is, how do I add a path to `imports`, so that it finds the `.pyd`? Can I add paths relative to execroot?

**Comment by abergmeier-dsfishlabs** [comment]
If everything is in the zip, then indeed looking at the zip is ok. Still would be good to preserve these dirs. @kchodorow this then means you could decrease Priority to P3.

**Comment by laszlocsomor** [comment]
Closing this bug because 9 months later Bazel on Windows still doesn't create runfiles trees, and currently we don't plan to change that status quo.

We do plan to write language-specific libraries that help using runfiles. Until then, programs should read the contents of the runfiles manifest (its path is in the `RUNFILES_MANIFEST_FILE` envvar).
