### ISSUE TITLE
Bazel client, Windows: get rid of AsWindowsPath for MSVC code path

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2507]
Avoid using our UNIX to Windows path conversion methods (e.g. [`AsWindowsPathWithUncPrefix`](https://github.com/bazelbuild/bazel/blob/65fde000e1a31b569a43103fbb531e2b2cc30b18/src/main/cpp/util/file_platform.h#L142)) when building for `--cpu=x64_windows_msvc`.

If a binary is compiled with MSVC and thus not linked against msys-2.0.dll, then MSYS converts UNIX path arguments to Windows paths. So if Bazel is built with MSVC, we don't need the conversion methods.

We cannot completely get rid of these methods though because we use UNIX paths in places like the CROSSTOOL file. But we should get rid of calls when processing paths coming from command line arguments.

**Comment by laszlocsomor** [comment]
We can't remove this method, as we'll still have to normalize and absolutize paths, but we can remove all the logic dealing with MSYS path conversion (including the `bazel.windows_unix_root` JVM flag and its handling).

**Comment by laszlocsomor** [comment]
We'll stop releasing MSYS-ful versions of Bazel with 0.5.4 / 0.6.0 (whichever comes first), and then clean up all MSYS-related code. Thus marking this as milestone 0.7.

**Comment by laszlocsomor** [comment]
I was wrong in [my earlier comment](https://github.com/bazelbuild/bazel/issues/2507#issuecomment-317359742):

> We can't remove this method, as we'll still have to normalize and absolutize paths, but we can remove all the logic dealing with MSYS path conversion (including the `bazel.windows_unix_root` JVM flag and its handling).

I think we can remove the Unix path conversion logic from the Bazel client, and probably also from the JNI library. We cannot fully remove it from the Java code though, as @tomlu also discovered.

**Comment by meteorcloudy** [comment]
Closing because it's an obsolete issue
