### ISSUE TITLE
Bazel build fails in /tmp folder with v0.4.4

### ISSUE THREAD

**Issue by sethkoehler** [bazelbuild/bazel#2508]
### Description of the problem / feature request / question:
I'm trying to run bazel build in the /tmp folder (due to https://github.com/bazelbuild/bazel/issues/2347) and hit the following issue with 0.4.4 (I believe this was working in v0.4.3, but I can't seem to downgrade for the moment):

```
_src$ bazel build ...
................
INFO: Found 3 targets...
ERROR: /tmp/folder/_src/BUILD:10:1: null failed: Process exited with status 1 [sandboxed].
src/main/tools/linux-sandbox-pid1.cc:265: "mount(/tmp/folder/_src, tmp/folder/_src, NULL, MS_BIND, NULL)": No such file or directory
Use --strategy=GoCompile=standalone to disable sandboxing for the failing actions.
```

Using the GoCompile and GoLink standalone strategies indeed fixes the issue.  However, I don't hit this at all when I move the folder to my home directory.

When I run with --sandbox_debug, I get the following (not sure if that's helpful...note, I manually replaced my full home folder with ~ below):

```
INFO: Found 3 targets...
ERROR: /tmp/folder/_src/BUILD:5:1: null failed: Process exited with status 1 [sandboxed].
src/main/tools/linux-sandbox.cc:183: linux-sandbox-pid1 has PID 29418
src/main/tools/linux-sandbox-pid1.cc:241: tmpfs: /tmp
src/main/tools/linux-sandbox-pid1.cc:251: working dir: ~/.cache/bazel/_bazel_sethkoehler/159e7e722b034a64903a1b8e4b382e6e/bazel-sandbox/30b6019f-012a-467b-a5e9-0e8a218b081a-0/execroot/_src
src/main/tools/linux-sandbox-pid1.cc:252: sandbox root: ~/.cache/bazel/_bazel_sethkoehler/159e7e722b034a64903a1b8e4b382e6e/bazel-sandbox/30b6019f-012a-467b-a5e9-0e8a218b081a-0/tmp
src/main/tools/linux-sandbox-pid1.cc:181: CreateTarget(~/.cache/bazel/_bazel_sethkoehler/159e7e722b034a64903a1b8e4b382e6e/bazel-sandbox/30b6019f-012a-467b-a5e9-0e8a218b081a-0/execroot/_src, true)
src/main/tools/linux-sandbox-pid1.cc:263: bind mount: /tmp/folder/_src -> /tmp/folder/_src
src/main/tools/linux-sandbox-pid1.cc:265: "mount(/tmp/folder/_src, tmp/folder/_src, NULL, MS_BIND, NULL)": No such file or directory
src/main/tools/linux-sandbox.cc:223: child exited normally with exitcode 1
Use --strategy=GoCompile=standalone to disable sandboxing for the failing actions.
```

### If possible, provide a minimal example to reproduce the problem:
Download [helloworld.tar.gz](https://github.com/bazelbuild/bazel/files/760761/helloworld.tar.gz) program and build in a folder inside /tmp vs. somewhere outside of /tmp.

### Environment info
OS: Linux x86_64 (Ubuntu 14.04)
Bazel: release 0.4.4

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
I looked through the issues here and in the group discussion, but didn't see anything that looked related.

**Comment by frp** [comment]
+1, encountering the same problem.
