### ISSUE TITLE
Support embeddable Python

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2509]
### Description of the problem / feature request / question:

Starting with Python 3.5, on Windows there is an embeddable Python variant, which is as isolated as possible. It does not however allow modifying by environment variables (e.g. `PYTHONPATH`). There are alternating control files for that variant, which are currently not supported.

### Environment info
* Operating System: Windows

**Comment by abergmeier-dsfishlabs** [comment]
@meteorcloudy Not sure who other than you (for Windows) is invested in Python.

**Comment by abergmeier-dsfishlabs** [comment]
See this discussion about how to communicate with Python embeddable: https://bugs.python.org/issue29503

**Comment by abergmeier-dsfishlabs** [comment]
So the way to replace `PYTHONPATH` for embeddable would probably be to use:

    args = [python_program, "-c", """\
    import sys
    path=%s.rsplit(os.sep, 1)
    sys.path.append(path[0])
    sys.path.extend(python_path_list)
    import path[1] # This obviously does not work - but there should be a way to do it
    """ % main_filename] + args

Would you guys consider taking patches for that?

**Comment by abergmeier** [comment]
I think it would perhaps also be a good idea to set `-e` when calling Python.

**Comment by abergmeier-dsfishlabs** [comment]
Closing since I will close account.
