### ISSUE TITLE
Add GitHub topics

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel#2513]
GitHub just announced Topics, which lets you add tags to your repo to improve discoverability: https://github.com/blog/2309-introducing-topics

Let's add topics to all of the repos under bazelbuild.

**Comment by kchodorow** [comment]
Sounds good to me!

**Comment by steren** [comment]
Who has enough rights on the repo to do it? I don't but would gladly do it if rights granted.

**Comment by steren** [comment]
@damienmg you probably have enough rights for this. 

I suggest the following topics:

* `bazel` (it seems to be a topic we use on everything Bazel related)
* `build-tool`
* `build`
* `test`
* `fast`
* `correct`

And maybe `continuous-integration` ?

**Comment by damienmg** [comment]
@steren: I set you admin to the repo (we restrict number of admins to avoid human errors we seen in the past). Feel free to ask admin on any repo you'd like.

**Comment by damienmg** [comment]
(people with enough right: Kristina, Helen I and now yourself :))
