### ISSUE TITLE
Allow bootstrapping Bazel without protobuf-java-3.0.0.jar

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/bazel#2519]
Currently, the Java proto runtime (`protobuf-java-3.0.0.jar`) is checked into the Bazel source tree.

We can replace it with the protobuf distro, allowing Bazel to build itself without any binary artifacts related to protobuf. This will make upgrading protobuf much easier than currently.

However, the bootstrap script `./compile.sh` builds `//src/java_tools/buildjar/java/com/google/devtools/build/buildjar:skylark-deps`, which uses `protobuf-java-3.0.0.jar` to compile some generated protos.

Is it feasible to build `protobuf-java-3.0.0.jar` from head when building Bazel and its `-distr` file?

**Comment by damienmg** [comment]
dupe of #2578
