### ISSUE TITLE
Desugaring a method reference implicitly requires Java 7 APIs (Android API 19+).

### ISSUE THREAD

**Issue by JakeWharton** [bazelbuild/bazel#2522]
### Description of the problem / feature request / question:

When desugaring a method reference for Android, the lambda meta factory emits a call to `Objects.requireNonNull` before passing the captured instance to the generated class. This method was added in Java 7 which is Android API 19+ only.

I'm not sure what API level you're supporting with this feature, but all other emitted bytecode is certainly Java 6 compatible which would give you Android API 9+.

### If possible, provide a minimal example to reproduce the problem:

```java
public final class MainActivity extends Activity {
  @Override protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    Executor executor = Executors.newSingleThreadExecutor();
    Greeter greeter = new Greeter();
    executor.execute(greeter::sayHi);
  }

  static class Greeter {
    void sayHi() {
      System.out.println("Hi!");
    }
  }
}
```

### Environment info
* Operating System: OSX 10.12.3
* Bazel version (output of `bazel info release`): master @ 89512a7cb

### Anything else, information or logs or outputs that would be helpful?

Here's the bytecode output after desugaring:
```
      28: aload_3
      29: dup
      30: invokestatic  #41                 // Method java/util/Objects.requireNonNull:(Ljava/lang/Object;)Ljava/lang/Object;
      33: pop
      34: invokestatic  #44                 // Method com/google/bazel/example/android/activities/MainActivity$$Lambda$7.get$Lambda:(Lcom/google/bazel/example/android/activities/MainActivity$Greeter;)Ljava/lang/Runnable;
      37: invokeinterface #35,  2           // InterfaceMethod java/util/concurrent/Executor.execute:(Ljava/lang/Runnable;)V
```

**Comment by kevin1e100** [comment]
You should be able to avoid this by including -XDallowBetterNullChecks=false into the javacopts, either using bazel's --javacopts command line flag or your android_library target's javacopts attribute.  could you give that a try please?  we'll look into a fix that's more turnkey.

**Comment by aj-michael** [comment]
Thanks for the detailed report!

Some more background, (as provided by @kevin1e100), the bazel android desugarer is not actually writing out Objects.requireNonNull, but javac9 is synthetically adding it (see https://bugs.openjdk.java.net/browse/JDK-8074306). Bazel bundles javac9 in https://github.com/bazelbuild/bazel/blob/master/third_party/java/jdk/langtools, which is being used with javacopts -source 8 -target 8 if you use `--experimental_desugar_for_android`. So javac9 sees the target level and thinks its fine to write synthetic java7 methods, such as Objects.requireNonNull.

**Comment by JakeWharton** [comment]
A quick try of that flag didn't seem to affect the output. And thanks for the info around the compiler. I should have known because [the error-prone issue][1] has been getting some activity of late as well.

 [1]: https://github.com/google/error-prone/issues/375

**Comment by aj-michael** [comment]
The allowBetterNullChecks flag that @kevin1e100 mentioned is a fork that is not in Bazel's javac and is not in the javac we have at https://github.com/bazelbuild/bazel/blob/master/third_party/java/jdk/langtools.

One solution would be to have the desugaring tool remove this methods. @kevin1e100 do you think its worth patching Bazel's javac in the mean time to add that flag?

**Comment by kevin1e100** [comment]
Err sorry about that.  I'll see how we can work around this, stay tuned

**Comment by cushon** [comment]
> One solution would be to have the desugaring tool remove this methods

I think we need this even with the javac patch; we're going to want it to work with stock JDK 9's eventually.

> do you think its worth patching Bazel's javac in the mean time to add that flag?

I'm on it.

**Comment by cushon** [comment]
Support for `-XDallowBetterNullChecks=false` was added in 2e689c29d5fc8a747216563235e905b1b62d63b0.

**Comment by aj-michael** [comment]
b35a0c086152ac6e5e0e695b21cacfd61de68b51 updated the desugarer to desugar calls to `requireNonNull(Object o)` so I'm going to close this issue. Unfortunately, that commit won't be in the Bazel 0.4.5 release that is happening Monday, but it will be in the next one.
