### ISSUE TITLE
runs_per_test executes tests tagged exclusive in parallel

### ISSUE THREAD

**Issue by trainman419** [bazelbuild/bazel#2525]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I have a test that I've imported from an upstream project, which writes a file to an absolute path and then reads that file back through a separate API, to confirm that the API finds the file properly and reads back the entire contents.

When this test is executed in parallel with itself, it fails because one instance of the test is writing the file while another is reading it, and the reading process does not read the entire file contents.

To verify this, I've found that running `bazel test --runs_per_test 100 ...` fails, but `bazel test --runs_per_test 100 --jobs 1 ...` succeeds, so this is clearly a result of parallel execution and not some other form of flakiness in my test.

The test works fine if run by itself, so per [this documentation](https://bazel.build/versions/master/docs/be/common-definitions.html#common-attributes) I've added the `exclusive` tag to force it to run by itself. Unfortunately, this still results in parallel executions of my test when run with `--runs_per_test`

### Environment info
* Operating System: Ubuntu 14.04

* Bazel version (output of `bazel info release`): `release 0.4.3-2017-01-19 (@065e9ef)`

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

I haven't been able to find anything similar to this on the issue tracker.

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by dslomov** [comment]
@philwo, any quick ideas?

**Comment by philwo** [comment]
Mhm... I agree with @trainman419 that exclusive tests should not run in parallel for multiple runs and it actually sounds like a bug.

**Comment by brycecr** [comment]
Just encountered something that seems quite similar to this bug in symptom, so a mention that this still seems to be an issue.

**Comment by AdamSvetec** [comment]
This seems fixed as of version 0.23.2

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by Ryang20718** [comment]
Hi,  I'm currently on version 6.0.0, but I'm still hitting this issue. Wondering if we could reopen?
