### ISSUE TITLE
Automatically select the installed Xcode instead of requiring --ios_sdk_version

### ISSUE THREAD

**Issue by jcanizales** [bazelbuild/bazel#253]
`--verbose_failures` shows:

`clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk'`

Looking into that folder in my machine, there's an `iPhoneSimulator.sdk` directory, and a `iPhoneSimulator8.3.sdk` link. Duplicating the 8.3 link and renaming it 8.1 makes everything work. But is super hackish.

**Comment by jcanizales** [comment]
I see from another issue that there's a couple of flags that I guess would make it work: `--ios_sdk_version=8.3 --ios_simulator_version=8.3`. Bazel should assume them if those are the only versions of the SDKs it can find, instead of failing.

**Comment by Aragos** [comment]
We're working on a plan to automatically select the right SDK and Xcode as installed on your machine but as those plans are still fairly nebulous I won't go into details yet. Expect some updates here in the next few months.

**Comment by jcanizales** [comment]
If the fix is coming in months, I think we should have an immediate bandaid in the example app, like just mentioning the flags in its README.

**Comment by jcanizales** [comment]
(Also, FWIW, this command outputs the SDK version: `xcrun --sdk iphoneos --show-sdk-version`)

**Comment by dmaclach** [comment]
Thanks Jorge. We really are working on it :)

Cheers,
Dave

**Comment by damienmg** [comment]
This is done for several month now.
