### ISSUE TITLE
Can't suppress "Reading 'startup' options" print

### ISSUE THREAD

**Issue by Peaches491** [bazelbuild/bazel#2530]
The following line of code prints directly to `stderr`, completely circumventing the standard logger levels. 
Please replace this with the usual `BAZEL_LOG(INFO) << ` as used above in the same `Parse` function.

https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/option_processor.cc#L163

**Comment by dslomov** [comment]
Patch welcome!
