### ISSUE TITLE
Can I run cmake inside bazel ?

### ISSUE THREAD

**Issue by riless** [bazelbuild/bazel#2532]
I'd like to run `cmake` to prepare the build files of `OpenCV` and then use them inside `cc_library`.

I've tried using `genrule` for that, but it does not allow to set `outs` to a folder (aka `opencv_build/`)

How can I do this ?

**Comment by abergmeier-dsfishlabs** [comment]
This is a bit more complex problem. We kind of think about doing that, too.
@damienmg Can perhaps give an ETA when (extended) directory handling might be available!?

In general the easiest way is to, after running CMake, either:

- specify necessary built files in a custom rule
- put everything that was built into an archive (e.g. tar)

Next you may also need to pass all C/C++ flags into CMake. For that, though, I think there still is no good story how to do it!?

**Comment by damienmg** [comment]
I do not know about when this is going to be available for Skylark, /cc @aragos might know a bit more.

**Comment by riless** [comment]
@abergmeier-dsfishlabs Thank you for your answer.

I'm actually getting around this limitation by creating myself some files that are required for building OpenCV using genrules.

```
genrule(
    name = "opencv_core_kernels",
    outs = ["opencl_kernels_core.hpp"],
    cmd = """
      echo '
            #include "opencv2/core/ocl.hpp"             \
            #include "opencv2/core/ocl_genbase.hpp"     \
            #include "opencv2/core/opencl/ocl_defs.hpp" \
      ' > $@
    """,
)
```

I'm stucked in a step where I should run a python script (`modules/java/generator/gen_java.py`) that generates JNI exports in cpp file.

`$ python  modules/java/generator/gen_java.py ./modules/python/src2/hdr_parser.py imgproc modules/imgproc/include/opencv2/imgproc.hpp` generates `./imgproc.cpp` file

so I did this in bazel 

```
genrule(
    name = "imgproc_jni",
    outs = ["modules/java/gen/imgproc.cpp"],
    cmd = """ \
        python  $(location modules/java/generator/gen_java.py)              \
                $(location modules/python/src2/hdr_parser.py)               \
                imgproc                                                     \
                $(location modules/imgproc/include/opencv2/imgproc.hpp)     \
    """,
    srcs = [
        "modules/java/generator/gen_java.py",
        "modules/python/src2/hdr_parser.py",
        "modules/imgproc/include/opencv2/imgproc.hpp"
    ]
)
```

but I got this error: 

`declared output 'external/opencv/modules/java/gen/imgproc.cpp' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely).`

**Comment by kchodorow** [comment]
You're almost there!  Although it looks like `outs = ["imgproc.cpp"]` should refer to the `$PWD`, outputs are actually under a separate directory tree.  So it should work if you change your genrule cmd to:

```
    cmd = """                                                                                                                                                                                                                                                                                                                  
python  $(location modules/java/generator/gen_java.py)          \                                                                                                                                                                                                                                                              
    $(location modules/python/src2/hdr_parser.py)               \                                                                                                                                                                                                                                                              
    imgproc                                                     \                                                                                                                                                                                                                                                              
    $(location modules/imgproc/include/opencv2/imgproc.hpp)                                                                                                                                                                                                                                                                    
cp imgproc.cpp $@ 
"""
```

The last line copies imgproc.cpp to the output file location.

**Comment by riless** [comment]
Exactly what I needed. Thank you @kchodorow

I'm closing this issue as the original question about cmake was answered by @abergmeier-dsfishlabs as non supported yet by bazel.

**Comment by HuKeping** [comment]
> I'm closing this issue as the original question about cmake was answered by @abergmeier-dsfishlabs as non supported yet by bazel.

Seems like https://github.com/bazelbuild/rules_foreign_cc would support CMake in bazel? @riless

**Comment by raju249** [comment]
> You're almost there! Although it looks like `outs = ["imgproc.cpp"]` should refer to the `$PWD`, outputs are actually under a separate directory tree. So it should work if you change your genrule cmd to:
> 
> ```
>     cmd = """                                                                                                                                                                                                                                                                                                                  
> python  $(location modules/java/generator/gen_java.py)          \                                                                                                                                                                                                                                                              
>     $(location modules/python/src2/hdr_parser.py)               \                                                                                                                                                                                                                                                              
>     imgproc                                                     \                                                                                                                                                                                                                                                              
>     $(location modules/imgproc/include/opencv2/imgproc.hpp)                                                                                                                                                                                                                                                                    
> cp imgproc.cpp $@ 
> """
> ```
> 
> The last line copies imgproc.cpp to the output file location.

@kchodorow Can you please explain how can I use this if my file generates multiple files? 🤔  🙇
