### ISSUE TITLE
Error: expecting string instruction after `rep'

### ISSUE THREAD

**Issue by ysagon** [bazelbuild/bazel#2534]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I'm trying to compile Bazel dist 0.4.4 and I have the following error:

    ERROR: /home/sagon/easybuild/bazel/src/main/tools/BUILD:3:1: C++ compilation of rule '//src/main/tools:process-wrapper' failed: gcc failed: error executing command 
    (cd /tmp/bazel_bKWRSEkl/out/execroot/bazel && \
    exec env - \
    LD_LIBRARY_PATH=/opt/ebsofts/Core/Java/1.8.0_92/lib:/opt/ebsofts/MPI/GCC/6.3.0-2.27/OpenMPI/2.0.2/ScaLAPACK/2.0.2-OpenBLAS-0.2.19-LAPACK-3.7.0/lib:/opt/ebsofts/MPI/GCC/6.3.0-2.27/OpenMPI/2.0.2/FFTW/3.3.6/lib:/opt/ebsofts/Compiler/GCC/6.3.0-2.27/OpenBLAS/0.2.19-LAPACK-3.7.0/lib:/opt/ebsofts/Compiler/GCC/6.3.0-2.27/OpenMPI/2.0.2/lib:/opt/ebsofts/Compiler/GCC/6.3.0-2.27/hwloc/1.11.5/lib:/opt/ebsofts/Compiler/GCC/6.3.0-2.27/numactl/2.0.11/lib:/opt/ebsofts/Compiler/GCCcore/6.3.0/binutils/2.27/lib:/opt/ebsofts/Core/GCCcore/6.3.0/lib/gcc/x86_64-pc-linux-gnu/6.3.0:/opt/ebsofts/Core/GCCcore/6.3.0/lib64:/opt/ebsofts/Core/GCCcore/6.3.0/lib:/usr/mpi/gcc/openmpi-1.6.5/lib:/opt/intel/parallel_studio_xe_2016/compilers_and_libraries_2016.2.181/linux/compiler/lib/intel64:/opt/intel/parallel_studio_xe_2016/compilers_and_libraries_2016.2.181/linux/compiler/lib/intel64_lin:/opt/intel/parallel_studio_xe_2016/compilers_and_libraries_2016.2.181/linux/mpi/intel64/lib:/opt/intel/parallel_studio_xe_2016/compilers_and_libraries_2016.2.181/linux/mpi/mic/lib:/opt/intel/parallel_studio_xe_2016/compilers_and_libraries_2016.2.181/linux/ipp/lib/intel64:/opt/intel/parallel_studio_xe_2016/compilers_and_libraries_2016.2.181/linux/compiler/lib/intel64:/opt/intel/parallel_studio_xe_2016/compilers_and_libraries_2016.2.181/linux/mkl/lib/intel64:/opt/intel/parallel_studio_xe_2016/compilers_and_libraries_2016.2.181/linux/tbb/lib/intel64/gcc4.4:/opt/intel/parallel_studio_xe_2016/debugger_2016/libipt/intel64/lib:/opt/intel/parallel_studio_xe_2016/compilers_and_libraries_2016.2.181/linux/daal/lib/intel64_lin:/opt/intel/parallel_studio_xe_2016/compilers_and_libraries_2016.2.181/linux/tbb/lib/intel64_lin/gcc4.4:/opt/intel/parallel_studio_xe_2016/compilers_and_libraries_2016.2.181/linux/compiler/lib/intel64_lin \
    PATH=/opt/ebsofts/Core/Java/1.8.0_92:/opt/ebsofts/Core/Java/1.8.0_92/bin:/opt/ebsofts/Core/EasyBuild/3.1.0/bin:/opt/ebsofts/MPI/GCC/6.3.0-2.27/OpenMPI/2.0.2/FFTW/3.3.6/bin:/opt/ebsofts/Compiler/GCC/6.3.0-2.27/OpenBLAS/0.2.19-LAPACK-3.7.0/bin:/opt/ebsofts/Compiler/GCC/6.3.0-2.27/OpenMPI/2.0.2/bin:/opt/ebsofts/Compiler/GCC/6.3.0-2.27/hwloc/1.11.5/sbin:/opt/ebsofts/Compiler/GCC/6.3.0-2.27/hwloc/1.11.5/bin:/opt/ebsofts/Compiler/GCC/6.3.0-2.27/numactl/2.0.11/bin:/opt/ebsofts/Compiler/GCCcore/6.3.0/binutils/2.27/bin:/opt/ebsofts/Core/GCCcore/6.3.0/bin:/usr/lib64/qt-3.3/bin:/usr/mpi/gcc/openmpi-1.6.5/bin:/opt/intel/parallel_studio_xe_2016/compilers_and_libraries_2016.2.181/linux/bin/intel64:/opt/intel/parallel_studio_xe_2016/compilers_and_libraries_2016.2.181/linux/mpi/intel64/bin:/opt/intel/parallel_studio_xe_2016/debugger_2016/gdb/intel64_mic/bin:/opt/cluster/admin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/c3-4:/opt/ibutils/bin:/home/sagon/bin:/opt/nodejs/bin \
    /opt/ebsofts/Core/GCCcore/6.3.0/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/opt/ebsofts/Core/GCCcore/6.3.0/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/local-opt/bin/src/main/tools/_objs/process-wrapper/src/main/tools/process-tools.d -iquote . -iquote bazel-out/local-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/local-opt/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 '-std=c99' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c src/main/tools/process-tools.c -o bazel-out/local-opt/bin/src/main/tools/_objs/process-wrapper/src/main/tools/process-tools.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
    /tmp/ccMkyoTl.s: Assembler messages:
    /tmp/ccMkyoTl.s:645: Error: expecting string instruction after `rep'
    Target //src:bazel failed to build
    INFO: Elapsed time: 6.079s, Critical Path: 1.40s

### If possible, provide a minimal example to reproduce the problem:
./compile.sh

### Environment info
* Operating System:
Centos 6.8
Easybuild with toolchain foss/2017a (gcc 6.3.0, as 2.27)

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

I have found many threads saying that the error 
    
    Error: expecting string instruction after `rep'
Is due to a too old binutils.  The version that I have is the latest (2.27) but maybe it's not used? How should I enforce to use it?

**Comment by dslomov** [comment]
This looks like a gcc bug, sorry. Maybe @damienmg or @aehlig might have some ideas, but I do not know what we can do. Is trying a different gcc+binutils combination an option for you?

**Comment by damienmg** [comment]
Sounds like a C++ configuration issue. The CROSSTOOL generation might use a diferent binutils version than the bazel one. Have you set CC?

**Comment by ysagon** [comment]
I have tried like that:
    
    AS=$(which as) CCX=$(which g++) CC=$(which gcc) ./compile.sh
I have tried with another toolchain as well.

    AS=/opt/ebsofts/Compiler/GCCcore/5.4.0/binutils/2.26/bin/as 
    CCX=/opt/ebsofts/Core/GCCcore/5.4.0/bin/g++ 
    CC=/opt/ebsofts/Core/GCCcore/5.4.0/bin/gcc
Same error.

**Comment by ysagon** [comment]
Any clue?

**Comment by damienmg** [comment]
Try to export CC?

**Comment by ysagon** [comment]
Is it doing like this not enough?

    AS=$(which as) CCX=$(which g++) CC=$(which gcc) ./compile.sh

I tried like that:

    [sagon@master bazel]$ export CC=$(which gcc)
    [sagon@master bazel]$ export CCX=$(which g++)
    [sagon@master bazel]$ export AS=$(which as)
    [sagon@master bazel]$ echo $CC
    /opt/ebsofts/Core/GCCcore/5.4.0/bin/gcc
    [sagon@master bazel]$ echo $CCX
    /opt/ebsofts/Core/GCCcore/5.4.0/bin/g++
    [sagon@master bazel]$ echo $AS
    /opt/ebsofts/Compiler/GCCcore/5.4.0/binutils/2.26/bin/as

same error.

**Comment by damienmg** [comment]
pulling in @mhlopko because gcc 5.4 should definitely build bazel (maybe it is a too recent version of gcc?).

**Comment by mhlopko** [comment]
Well gcc 5.4 changed a [few things](https://gcc.gnu.org/gcc-5/changes.html) :) But nothing that immediately rings the bell. I will take a look.

**Comment by vanzod** [comment]
Identical problem here with `GCC 5.4.0` and `binutils 2.26`.
I had no problems building it with `GCC 4.9.2` and `binutils 2.25`.

Happy to provide any detail you may need.

**Comment by mhlopko** [comment]
Hmmm is it an option for you to test with binutils 2.28?

**Comment by mhlopko** [comment]
In general, I don't think Bazel does anything extreme with its C++ code, so I blame gcc/as :)

**Comment by ysagon** [comment]
In my case the problem was that gcc/as etc is hardcoded when compiling Bazel and setting CC etc in env variable seems to have no effects. 

Indeed, following the doc here [1] I was able to compile Bazel

The issue was that on Bazel the path to various tools are hardcoded!?

So I can compile Bazel after applying two patches.

cc_configure.bzl.patch [2]
CROSSTOOL.patch [3]




[1] http://biophysics.med.jhmi.edu/~yliu120/tensorflow.html

[2] https://gist.github.com/ysagon/8fb71312a31d58f62f7af2ccb7314bf8

[3] https://gist.github.com/ysagon/049e5dc01cd110b467586001dc802a93

**Comment by mhlopko** [comment]
Thanks @ysagon! I will improve the autogeneration.

**Comment by ysagon** [comment]
@mhlopko Today I tried to compile again bazel version 0.54 and I have again the same issue:( The hack with patching the CROSSTOL doesn't seems to work anymore.

**Comment by duganchen** [comment]
It's CXX, not CCX

**Comment by yrenier** [comment]
thanks @ysagon, I had the same problem (bazel 0.10.0) and your solution fixed it !

**Comment by meisterT** [comment]
Seems to be fixed.
