### ISSUE TITLE
generate_workspace does not work with spark artifact

### ISSUE THREAD

**Issue by jschenxiaoyu** [bazelbuild/bazel#2536]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
```
ERROR: Unable to resolve Maven model from https://repo1.maven.org/maven2/org/apache/spark/spark-core_2.11/2.1.0/spark-core_2.11-2.1.0.pom: 1 problem was encountered while building the effective model for org.apache.spark:spark-core_2.11:2.1.0
[ERROR] 'dependencyManagement.dependencies.dependency.groupId' for ${jline.groupid}:jline:jar with value '${jline.groupid}' does not match a valid id pattern. @
```

By the way, I have also tried other versions of spark and it also does not work.

### If possible, provide a minimal example to reproduce the problem:
bazel run //src/tools/generate_workspace -- --artifact=org.apache.spark:spark-core_2.11:2.1.0

### Environment info
* Operating System:
Ubuntu 14.04 LTS

* Bazel version (output of `bazel info release`):
0.4.3/0.4.4

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
Nope.

**Comment by jawsthegame** [comment]
I am also seeing this problem.

**Comment by jawsthegame** [comment]
any resolution on this problem?

**Comment by zrcahyx** [comment]
Anyone can help? This is troubling me.

**Comment by ittaiz** [comment]
Haven't read the issue but if I remember correctly the maintained generate
workspace is now in Bazelbuild/migration-tooling.
Maybe you should open an issue there.

**Comment by dslomov** [comment]
closing this in favor of https://github.com/bazelbuild/migration-tooling/issues/55
