### ISSUE TITLE
Add per-worker configuration for number of instances and lifespan

### ISSUE THREAD

**Issue by natebosch** [bazelbuild/bazel#2540]
We have global flags [`worker_quit_after_build`](https://github.com/bazelbuild/bazel/blob/bef19d10b1262e610569b4f604635eb0bea07e01/src/main/java/com/google/devtools/build/lib/worker/WorkerOptions.java#L66) and `worker_max_instances` for tuning behavior of workers. We should allow these per worker.

Ideally we should be able to set a default for each worker and allow them to be overridden by mnemonic.

The Dart build process has some particularly memory intensive workers, and having 4 copies of these live (potentially in multiple workspaces) across builds is too heavy, but limiting *all* workers to fewer copies and/or killing them after builds will negatively impact performance for other workers.

**Comment by natebosch** [comment]
The mailing list activity looks like a plan for being able to override this by mnemonic. Has any progress been made?
https://groups.google.com/d/msg/bazel-discuss/1SkiB8jw8rg/VOuQGqsBBgAJ

**Comment by philwo** [comment]
This was fixed in https://github.com/bazelbuild/bazel/commit/0c12603bedd4a270094137269b910a8587d3f93c.
