### ISSUE TITLE
Clarify support for Ubuntu 16.04 LTS in documentation

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#2542]
Reading the [documentation](https://bazel.build/versions/master/docs/install.html#ubuntu), the project seems to only officially support up to ubuntu 15.10 and 14.04. Ubuntu 16.04 is an LTS release. and has been released a year ago, we should make sure Bazel supports it and it's documented as such.

Please confirm me this is just a documentation issue. I will update it.

**Comment by damienmg** [comment]
What is the default JDK of Ubuntu 16.04? I believe we have issue with 16.10 that ship JDK 9 but not for 16.04. We could just add VMs for it to make it supported but we need to revise our testing strategy first.

As a temporary measure we should at least add a bootstrap test: like https://github.com/bazelbuild/bazel/tree/master/tools/cpp/test/Dockerfile.ubuntu-15.04

**Comment by steren** [comment]
It seems that 16.04 comes with JDK 8.

Also, should we remove from the doc the instructions for 14.04 LTS? Now that we have a new LTS release, it's probably safe to stop documenting 14.04. WDTY?

And yes, we need to provide a solution for people on 16.10.

**Comment by steren** [comment]
This should be clarified in an upcoming version of the install doc s

**Comment by damienmg** [comment]
Adding items for this bug since 1fbef39741cb5bb21dfb698cce94dca7a87ae335 has landed:

1. We still support 14.04 until its end of life, we just requires an extra step if you are not installing from the apt repository (installing openjdk8). We should add it back to the doc.

2. We do not test for ubuntu 16.04, I don't feel comfortable adding official support for it whereas we do not have test for it, adding tests.

**Comment by steren** [comment]
2: I created #2741

**Comment by michelleirvine** [comment]
Do you need to install OpenJDK 8 when compiling from source? We have one set of instructions for compiling on source which covers all platforms, and we don't currently mention OpenJDK 8. See: https://bazel.build/versions/master/docs/install-compile-source.html

In the doc for using binary installer for Ubuntu, the first step is to install OpenJDK 8. Is this needed for all three Ubuntu versions?

**Comment by michelleirvine** [comment]
Also - should I add this change (now supporting 16.04, will continue to support 14.04) to the release notes? Do I do that with the RELNOTES: tag in the change description?

**Comment by damienmg** [comment]
OpenJDK installation is not needed if you install from APT repositories. It's is needed when using the shell installer / compiling from source.

We do not need to add that to release notes, new support should be reflected on the documentation.

**Comment by michelleirvine** [comment]
Doc for installation on Ubuntu has been updated: https://bazel.build/versions/master/docs/install-ubuntu.html
