### ISSUE TITLE
How to access data runfiles from Python?

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#2545]
### Description of the problem / feature request / question:

Accessing data dependencies from Python is not straight-forward, see related user questions:

* http://stackoverflow.com/questions/41553609/what-is-the-right-way-to-refer-bazel-data-files-in-python/42307073#42307073
* https://groups.google.com/forum/#!searchin/bazel-discuss/data$20runfiles%7Csort:relevance/bazel-discuss/nLrZEhV7Ul0/3bOg_loUBgAJ
* https://groups.google.com/forum/#!searchin/bazel-discuss/data$20runfiles|sort:relevance/bazel-discuss/LPR8o1PYG2M/Cn4Bn3PYFAAJ

### Environment info
* Operating System: Linux
* Bazel version (output of `bazel info release`): release 0.4.2-jdk7

**Comment by ajayramesh23** [comment]
Hi , 
I am participating in GSoC-2017, getting drenched in Bazel ecosystem for contributions. Please, can someone assign this issue to me? 
Thank you
Ajay 👨🏻‍💻

**Comment by breakds** [comment]
I think it is a much needed feature to access the runfiles (probably the reason why we even have `data=` field in `py_library` and `py_binary`.

**Comment by brandjon** [comment]
Better semantics/documentation around runfiles is something I'd like to get to soonish. In any case it's not P4.

**Comment by donraj** [comment]
Is this really a documentation request? And why is it P3?

Has there been thought given to how to migrate python code which access files "in normal way" -> move to bazel -> access files via runfiles library?

Can we please get **the ultimate example** for a python project which access a bunch of runfiles?

**Comment by keith** [comment]
For others who find this I found the header document here useful https://github.com/bazelbuild/bazel/blob/a7a0d48fbeb059ee60e77580e5d05baeefdd5699/tools/python/runfiles/runfiles.py#L16-L58

**Comment by fmeum** [comment]
The runfiles library and documentation has moved to the rules_python repo: https://github.com/bazelbuild/rules_python/tree/main/python/runfiles
