### ISSUE TITLE
Generated Xcode project expects a file name that doesn't exist

### ISSUE THREAD

**Issue by jcanizales** [bazelbuild/bazel#255]
I created a minimal ios app with Bazel, and opened the project from `bazel-bin`. Trying to run it fails with:

> could not read data from '/Users/jcanizales/git/grpc/bazel-out/local_darwin-fastbuild/bin/src/objective-c/examples/BazelSample/**BazelSampleClasses**-MergedInfo.plist': The file “BazelSampleClasses-MergedInfo.plist” couldn’t be opened because there is no such file.`

That's almost the name of the file that does exist: **BazelSample**-MergedInfo.plist

This is my `BUILD` file:
```python
ios_application(
    name = "BazelSample",
    binary = ":BazelSampleClasses",
    infoplist = "Info.plist",
)

objc_binary(
    name = "BazelSampleClasses",
    srcs = [
        "main.m",
        "AppDelegate.m",
        "ViewController.m",
    ],
    hdrs = glob(["*.h"]),
    asset_catalogs = ["Images.xcassets/AppIcon.appiconset/Contents.json"],
    storyboards = ["Base.lproj/Main.storyboard"],
)
```

**Comment by jcanizales** [comment]
To reproduce: clone https://github.com/jcanizales/grpc and checkout the `bazel-ios-issue` branch. Then run, from the root of the cloned repo:
```sh
bazel build --ios_sdk_version=8.3 --ios_simulator_version=8.3 src/objective-c/examples/BazelSample
```

**Comment by jcanizales** [comment]
Also, this `BUILD` file, for the same set of sources, works without problem:
```python
objc_binary(
    name = "BazelSample",
    srcs = [
        "main.m",
        "AppDelegate.m",
        "ViewController.m",
    ],
    hdrs = glob(["*.h"]),
    asset_catalogs = ["Images.xcassets/AppIcon.appiconset/Contents.json"],
    infoplist = "Info.plist",
    storyboards = ["Base.lproj/Main.storyboard"],
)
```

**Comment by spierce7** [comment]
Is there any workaround for this? I'm seeing it on the ios tutorial project:
```
error: could not read data from '.../examples/tutorial/bazel-out/local_darwin-fastbuild/bin/ios-app/ios-app-MergedInfo.plist': The file “ios-app-MergedInfo.plist” couldn’t be opened because there is no such file.
```

**Comment by jcanizales** [comment]
@spierce7, @TimBurks has details about when it does happen and when not!

**Comment by c-parsons** [comment]
Thanks for updating this bug, it seems this completely fell off my radar. Is this issue still relevant, or is it obsolete? (this logic has changed a bit in the past few months)

As some extra info, we're in the process of deprecating (at low priority) bundling attributes on objc_binary, such as storyboards and asset_catalogs, if you specify these on the ios_application root target and *not* on objc_binary, this may resolve the issue you're running into.
