### ISSUE TITLE
C++ Basics failed redirect, broken link to googlecode

### ISSUE THREAD

**Issue by brunobowden** [bazelbuild/bazel#2551]
The **"C++ Basics"** and **"Build C++"** are two different pages in the docs. The **[C++ Basics](http://bazel.build/docs/cpp.html)** doc page has a broken link to googlecode for setting up Google Test. A similar fix was made for this to a different page, **[Build C++](https://bazel.build/versions/master/docs/tutorial/cpp.html)** tutorial, in #1688. Those changes should be copied from file site/versions/master/docs/tutorial/cpp.md to the **C++ Basics** docs. 

Broken link from docs: http://bazel.build/docs/cpp.html

```
new_http_archive(
    name = "gtest",
    url = "https://googletest.googlecode.com/files/gtest-1.7.0.zip",     <==================
    sha256 = "247ca18dd83f53deb1328be17e4b1be31514cedfc1e3424f672bf11fd7e0d60d",
    build_file = "gtest.BUILD",
    strip_prefix = "gtest-1.7.0",
)
```

I would send in a PR myself but I could not determined where the **C++ Basics** documentation page was located in the repository. Searching for text from that page in the GitHub repo was unsuccessful in finding it.

@pcj @laszlocsomor - since you both worked on #1688

**Comment by brunobowden** [comment]
It appears that the most doc pages redirect to a version under `versions/master/docs/...` but not the pages listed below. Perhaps this pages were removed in the new version of the website? Maybe they still appear in the old location by some transient effect?

There appear to be two issues:
1) When a page is removed from the repo it should disappear from the http://bazel.build website entirely.
2) The auto generated docs from Skylar and some other files are still pointing to the old website structure, e.g. https://github.com/bazelbuild/bazel/blob/5d8a44ccc3536f2327898e8671670ef9bafd6095/src/main/java/com/google/devtools/build/lib/rules/java/JavaRuleOutputJarsProvider.java#L40

http://bazel.build/docs/cpp.html => NO REDIRECT
http://bazel.build/docs/tutorial/index.html => NO REDIRECT
http://bazel.build/docs/be/docker.html => NO REDIRECT
http://bazel.build/docs/be/pkg.html => NO REDIRECT
http://bazel.build/docs/skyframe.html => NO REDIRECT
http://bazel.build/docs/skylark/lib/JavaAnnotationProcessing.html => NO REDIRECT
http://bazel.build/docs/skylark/lib/JavaCompilationInfo.html => NO REDIRECT
http://bazel.build/docs/skylark/lib/JavaOutput.html => NO REDIRECT
http://bazel.build/docs/skylark/lib/JavaOutputJars.html => NO REDIRECT

All the other doc pages I tested, did the redirect to **`versions/master/docs/...`** successfully. Examples include:

http://bazel.build/docs/external.html => https://bazel.build/versions/master/docs/external.html
http://bazel.build/docs/build-ref.html => https://bazel.build/versions/master/docs/build-ref.html

**Comment by steren** [comment]
The faulty behavior was indeed also reported to me this morning.

As you said, the fact that https://bazel.build/docs/cpp.html was still available is due to a problem in the way we deploy the website. It should not exist. I deleted the file behind it in our GCS bucket and sent in https://github.com/bazelbuild/bazel/pull/2553 a redirect to the correct page.

**Comment by brunobowden** [comment]
Thanks @steren. Please note the 9 other web pages listed in the previous comment that also appear to require deletion. I went through every link on the old website individually and these are the only ones that failed to redirect to something under `versions/master/docs/...`

**Comment by steren** [comment]
@brunobowden indeed, your original report pointed to more broken redirect that I tried to fix in PR #2553. 

I opened #2556 to work on a real fix, because today nothing prevents this to happen again.

**Comment by laszlocsomor** [comment]
Adding @davidzchen who knows best how our docs are deployed and how/why it's organized the way it is. As far as I'm concerned we intend(ed) to serve versioned docs (corresponding to each Bazel release), but never fully implemented the necessary pipeline changes.

**Comment by steren** [comment]
PR #2553 should fix the problems described earlier. Let me assign #2556 to @davidzchen.

**Comment by brunobowden** [comment]
I've verified this as fixed.

The Skylark pages are now 404s but that appears to be by design. All the other pages redirect correctly to versions/master/docs/...
