### ISSUE TITLE
Jenkins falsely reports test failures when testing the test runner

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#2554]
bazel-tests appear to fail on Jenkins due to testing the test runner:

http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/571/

> Test Result (2 failures / ±0)
> com.google.testing.junit.runner.testbed.JUnit4TestbridgeExercises.doNotRun
> com.google.testing.junit.runner.testbed.InternationalCharsTest.testThatAlwaysFails

[Some shell tests](https://github.com/bazelbuild/bazel/tree/master/src/java_tools/junitrunner/javatests/com/google/testing/junit/runner/junit4_testbridge_integration_tests.sh) verify that the test runner behaves appropriately  when a Junit test is failing. Even though the test passes, Jenkins sees it as a failure because there is a wrapped failing test.

**Comment by damienmg** [comment]
:) USA is down suggesting rollback.

The test is generating XML files that says the test is wrong: http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/ws/bazel-testlogs/src/java_tools/junitrunner/javatests/com/google/testing/junit/runner/junit4_testbridge_integration_test/test.xml

The shell test should make sure it does not overwrite its own log file...

**Comment by iirina** [comment]
Sorry Kush, I rolled back.

**Comment by kush-c** [comment]
damienmg@ I tried everything I could think of today, but not sure how I can stop these tests from generating the failure XML file. These tests did pass on Kokoro (and locally). What could Jenkins be doing differently than Kokoro?
Any hints would be super helpful.

**Comment by damienmg** [comment]
According to your run on CI the test does generate the boggus XML files: http://ci.bazel.io/job/Gerrit-bazel-tests/413/testReport/

The problem is not that there is failing test is that the test generate bogus XML files that overwrite the test log

**Comment by kush-c** [comment]
It seems the integration test's own XML results were not overwritten, but bogus XML were created by these  failing tests which were being picked up by Jenkins indicating failure.

After removing the failing XML of the tests in change: https://bazel-review.googlesource.com/c/9039/, I found previously failing tests (http://ci.bazel.io/job/Gerrit-bazel-tests/413) to pass (http://ci.bazel.io/job/Gerrit-bazel-tests/419/).

Submitted the change internally. Hope integrating with bazel/master does not require another rollback. (Fingers tightly crossed)!

**Comment by kush-c** [comment]
Since the immediate breakage was resolved the rollback, reducing priority.
