### ISSUE TITLE
Site search is searching bazel.io

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#2555]
Type "bazel" in the site Search.
All results are for bazel.io.

I guess Google Site Search has been configured on bazel.io, and not updated to bazel.build

@davidzchen or @damienmg would you know how to change this?
Our search widget seems to use an ID: https://github.com/bazelbuild/bazel/blob/master/site/search.html

**Comment by damienmg** [comment]
Iirc Kristina set that up.

**Comment by kchodorow** [comment]
I updated it to search bazel.build.  Not sure how long it'll take to reindex.

**Comment by steren** [comment]
great. since I guess this is based on Google search, it is already indexed. 
Spoiler alert: after a few tests search looks much better now. Thanks!
