### ISSUE TITLE
Website deploy mechanism should remove old files before pushing new site

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#2556]
We encountered #2551 because our deployment script seems to not remove old files in Google Cloud Storage before deploying a new version of the website. This means that if we delete a file and do not replace it by a redirect, the old file will still be served publicly (and indexed by search engines!).

This makes our deployment neither reproducible nor correct :)

**Comment by steren** [comment]
David, did you write our deployment scripts?

**Comment by davidzchen** [comment]
Steren - sorry for the delay.

I think @damienmg wrote the deployment script for pushing the site to GCS.

I agree, when we push a new version of the site, any files that have been deleted should be removed from the GCS bucket as well.

**Comment by steren** [comment]
I just discovered by chance a page that has been removed inhttps://github.com/bazelbuild/bazel/commit/9a9981e7c69276e61f998bc4c67525c1e45232f9 but that is still served: http://www.bazel.build/hard_to_write_rules.html

@damienmg: to be sure we are not keeping old stuff, could we delete the entire GCS buck content and re-trigger a new deployment?

**Comment by davidzchen** [comment]
We are using `gsutil rsync` for the push:

```
  The gsutil rsync command makes the contents under dst_url the same as the
  contents under src_url, by copying any missing files/objects (or those whose
  data has changed), and (if the -d option is specified) deleting any extra
  files/objects. src_url must specify a directory, bucket, or bucket
  subdirectory. For example, to make gs://mybucket/data match the contents of
  the local directory "data" you could do:

    gsutil rsync -d data gs://mybucket/data

  To recurse into directories use the -r option:

    gsutil rsync -d -r data gs://mybucket/data
```

Perhaps, we can run `gsutil rsync` with `-d` so that deleted files also get deleted from the bucket?

**Comment by damienmg** [comment]
Indeed but we should be careful because perf.bazel.build results are
actually not sync'd the same way, so we probably want to not use it for
perf.bazel.build or reorganize it a bit, Anyway this issue should be in
continuous-integration since the website sync tasks are moving there.

**Comment by davidzchen** [comment]
SGTM. Closing this. This is tracked by bazelbuild/continuous-integration#39
