### ISSUE TITLE
//src/test/shell/bazel:bazel_windows_example_test#test_java_test fails on Windows 

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2558]
```
-- Test log: -----------------------------------------------------------
INFO: Reading 'startup' options from /c/tmp/bazelrc: --output_user_root=/c/tmp/root --host_javabase=C:/tmp/_bazel_pcloudy/GYQDuV_U/external/local_jdk
INFO: $TEST_TMPDIR defined: output root default is '/c/tmp'.
____Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
ERROR: C:/tmp/root/iydsotdv/execroot/workspace/bazel-out/vc_14_0_x64-fastbuild/bin/examples/java-native/src/main/java/com/example/myproject (Directory not empty).
------------------------------------------------------------------------
test_java_test FAILED: terminated because this command returned a non-zero status:
/home/pcloudy/workspace/bazel/src/test/shell/testenv.sh:386: in call to cleanup_workspace
/home/pcloudy/workspace/bazel/src/test/shell/testenv.sh:411: in call to tear_down
```

The exact code producing this error is in [JavaIoFilesystem.java](https://github.com/bazelbuild/bazel/blob/e36a66cd6e35e5b4b276f2b6ce63e1c691bcb02c/src/main/java/com/google/devtools/build/lib/vfs/JavaIoFileSystem.java#L340), looks like a race condition to me, where Bazel trys to delete the parent directory before the child directories were deleted(but after calling delete function for the child directories)

Related issue: #2178

**Comment by laszlocsomor** [comment]
It's possible that `file.isDirectory()` returns true but `file` is actually a junction. In that case `file.list().length > 0` may rightfully be true but it's still safe to delete the junction. Does that sound plausible?

**Comment by laszlocsomor** [comment]
Oh no wait, that can't be, `file.delete()` a few lines above would succeed for that. Never mind.

**Comment by meteorcloudy** [comment]
This is no longer a failure, closing...
