### ISSUE TITLE
Testing local bazel doesn't work without android sdk

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#2559]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I'm trying to follow the instructions on [compiling bazel](https://bazel.build/contributing.html#compiling-bazel) but it seems that without android sdk this doesn't work

### If possible, provide a minimal example to reproduce the problem:
```
➜  bazel git:(master) bazel test //src/... //third_party/ijar/...
ERROR: /DEFAULT.WORKSPACE:81:1: in bind rule //external:android/sdk: The external label '//external:android/sdk' is not bound to anything.
ERROR: Analysis of target '//src/tools/android/java/com/google/devtools/build/android/incrementaldeployment:incremental_split_stub_application' failed; build aborted.
INFO: Elapsed time: 0.598s
ERROR: Couldn't start the build. Unable to run tests.
```

### Environment info
* Operating System:
OS X El-Capitan 10.11.6

* Bazel version (output of `bazel info release`):

development version

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
54b9d2c3d514c7023948930a86db88178309149a

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).
#509 is related but it just wants the error message to be better. I would rather drop android sdk as a requirement.

**Comment by iirina** [comment]
When running the tests under //src/..., the tests for Android are also started. I'm not sure it would be a good idea to disable these tests by default, but rather improve our documentation on what basic tests to run, depending on whether the user is interested or not in Android.

[Here](https://github.com/bazelbuild/bazel/blob/master/WORKSPACE#L45) are the instructions for running the Android tests.

**Comment by ittaiz** [comment]
@iirina thanks!
Don't the android instructions mandate something additional? What is `/WORKSPACE.user`?
Additionally the main problem is that the current documentation says to run `//src/...` while it doesn't work

**Comment by iirina** [comment]
`/WORKSPACE.user` is a file created by `scripts/workspace_user.sh` containing generated `android_ndk_repository` and `android_sdk_repository` rules. But yes you are right, you need to hame some environment variables set up (ANDROID_HOME, ANDROID_SDK, ANDROID_NDK) that also means you have to have Android set up.

I'm adding @aj-michael for Android support and @steren for the documentation part.

**Comment by ittaiz** [comment]
Exactly the android set up is the part I don't want to do.
Now, it might be totally valid to require it before making a contribution
but I'm not sure it's actually needed.

**Comment by steren** [comment]
adding @michelleirvine owner of our documentation

**Comment by aj-michael** [comment]
There is some confusion here, the error that you got is not due to an Android _test_, it is due to building an Android _tool_: 

    //src/tools/android/java/com/google/devtools/build/android/incrementaldeployment:incremental_split_stub_application

You want to use the `--build_tests_only` flag and everything should be ok. You can see the full list of flags for this step here:

https://github.com/bazelbuild/bazel/blob/master/compile.sh#L218

We should update the documentation to include this flag.

**Comment by ittaiz** [comment]
Fair enough.

**Comment by aj-michael** [comment]
While we're on the topic though, I should mention that //src/test/shell/bazel/android:android_integration_test will run and silently skip all the tests and return a pass if an android sdk and android ndk are not installed. I've been doing some work to make the process of  setting up android_sdk_repository and android_ndk_repository be less of a burden in #2284, but it's not quite done yet.

At some point, I would like to make android_integration_test fail if no Android SDK is installed, to prevent people from committing Android-related code while forgetting to run these tests. @ittaiz I would be curious to hear your perspective on how you think we could best handle the android tests for people who do not have an Android SDK on hand.

**Comment by ittaiz** [comment]
I think it really depends on how easy you want to make it for accidental
contributors (who I assume usually don't touch android related code) vs
regular maintainers and are you willing to defer some of the feedback loop
to CI.
If you want to optimize for accidental contributors and are willing to
defer to CI why not fail these only when a flag is turned on and turn it on
by default on CI.
Regular maintainers will also have it turned in via bazelrc or something

**Comment by aj-michael** [comment]
As of 65b49a2, `bazel test //src/...` no longer builds `//src/tools/android/java/com/google/devtools/build/android/incrementaldeployment:incremental_split_stub_application` so marking this as closed.
