### ISSUE TITLE
the cmd in the PrenotCalculatorInstruments example genrule assumes the existence of a TMPDIR variable

### ISSUE THREAD

**Issue by haxorz** [bazelbuild/bazel#256]
nharmata-macbookair2:base_workspace nharmata$ ../output/bazel build //examples/objc:PrenotCalculatorInstruments --ios_sdk_version=8.3 --verbose_failures
INFO: Found 1 target...
INFO: From Executing genrule //examples/objc:PrenotCalculatorInstruments:
/bin/bash: TMPDIR: unbound variable
ERROR: /Users/nharmata/bazel-github/bazel/examples/objc/BUILD:87:1: Executing genrule //examples/objc:PrenotCalculatorInstruments failed: bash failed: error executing command 
  (cd /private/var/tmp/_bazel_nharmata/5d0848a71b50b4a2f7fb3f96500f927e/bazel && \
  exec env - \
  /bin/bash -c 'source tools/genrule/genrule-setup.sh; unzip -q bazel-out/local_darwin-fastbuild/bin/examples/objc/PrenotCalculator.ipa -d ${TMPDIR} ; echo '\''UIATarget.localTarget().delay(5); UIATarget.localTarget().captureScreenWithName("hello_instruments");'\'' > ${TMPDIR}/hello_instruments.js && /usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -w '\''iPhone 5 (8.1 Simulator)'\'' ${TMPDIR}/Payload/PrenotCalculator.app -e UIASCRIPT ${TMPDIR}/hello_instruments.js -e UIARESULTSPATH ${TMPDIR} -v && cp ${TMPDIR}'\''/Run 1/hello_instruments.png'\'' bazel-out/local_darwin-fastbuild/genfiles/examples/objc/hello_instruments.png'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: bash failed: error executing command 
  (cd /private/var/tmp/_bazel_nharmata/5d0848a71b50b4a2f7fb3f96500f927e/bazel && \
  exec env - \
  /bin/bash -c 'source tools/genrule/genrule-setup.sh; unzip -q bazel-out/local_darwin-fastbuild/bin/examples/objc/PrenotCalculator.ipa -d ${TMPDIR} ; echo '\''UIATarget.localTarget().delay(5); UIATarget.localTarget().captureScreenWithName("hello_instruments");'\'' > ${TMPDIR}/hello_instruments.js && /usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -w '\''iPhone 5 (8.1 Simulator)'\'' ${TMPDIR}/Payload/PrenotCalculator.app -e UIASCRIPT ${TMPDIR}/hello_instruments.js -e UIARESULTSPATH ${TMPDIR} -v && cp ${TMPDIR}'\''/Run 1/hello_instruments.png'\'' bazel-out/local_darwin-fastbuild/genfiles/examples/objc/hello_instruments.png'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //examples/objc:PrenotCalculatorInstruments failed to build
INFO: Elapsed time: 0.138s, Critical Path: 0.02s
nharmata-macbookair2:base_workspace nharmata$

**Comment by haxorz** [comment]
maybe do something like

cmd = "TMPDIR=$$(mktemp -d -t PrenotCalculatorInstruments_genrule); ..."

**Comment by laszlocsomor** [comment]
I'm getting a compilation error at head:

    $ output/bazel version
    Build label: head (@8ca9131)
    Build target: bazel-out/local_linux-fastbuild/bin/src/main/java/bazel-main_deploy.jar
    Build time: Tue Jun 23 10:03:10 2015 (1435053790)
    Build timestamp: 1435053790
    Build timestamp as int: 1435053790

    $ output/bazel build //examples/objc:PrenotCalculatorInstruments --ios_sdk_version=8.3 --verbose_failures
    INFO: Found 1 target...
    ERROR: missing input file '//tools/objc:precomp_momczip_deploy.jar'.
    ERROR: /tmp/bzl/bazel/tools/objc/BUILD:24:1: //tools/objc:momczip: missing input file '//tools/objc:precomp_momczip_deploy.jar'.
    Target //examples/objc:PrenotCalculatorInstruments failed to build

**Comment by damienmg** [comment]
On a mac?

On Tue, Jun 23, 2015 at 12:25 PM László Csomor <notifications@github.com>
wrote:

> I'm getting a compilation error at head:
>
> $ output/bazel version
> Build label: head (@8ca9131)
> Build target: bazel-out/local_linux-fastbuild/bin/src/main/java/bazel-main_deploy.jar
> Build time: Tue Jun 23 10:03:10 2015 (1435053790)
> Build timestamp: 1435053790
> Build timestamp as int: 1435053790
>
> $ output/bazel build //examples/objc:PrenotCalculatorInstruments --ios_sdk_version=8.3 --verbose_failures
> INFO: Found 1 target...
> ERROR: missing input file '//tools/objc:precomp_momczip_deploy.jar'.
> ERROR: /tmp/bzl/bazel/tools/objc/BUILD:24:1: //tools/objc:momczip: missing input file '//tools/objc:precomp_momczip_deploy.jar'.
> Target //examples/objc:PrenotCalculatorInstruments failed to build
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/bazel/issues/256#issuecomment-114433355>.
>
-- 
Damien

**Comment by laszlocsomor** [comment]
*facepalm*
never mind, of course I tried on Linux

**Comment by laszlocsomor** [comment]
Damien, can you please triage this? I have no mac to play with.

**Comment by damienmg** [comment]
Assigning to Aragos as it is his field of expertise.

**Comment by haxorz** [comment]
Yes, this was on a new macbook air 11. I didn't personally do anything special (e.g. I didnt unset that environment variable).

**Comment by dmaclach** [comment]
If you launch terminal and type "export" is TMPDIR not listed?

What about if you run "getconf DARWIN_USER_TEMP_DIR"?

Cheers,
Dave

**Comment by haxorz** [comment]
well i added this after filing the bug

nharmata-macbookair2:~ nharmata$ tail -n 1 ~/.bashrc
export TMPDIR=/tmp

so now i get:

nharmata-macbookair2:~ nharmata$ export | grep TMPDIR
declare -x TMPDIR="/tmp"
nharmata-macbookair2:~ nharmata$ getconf DARWIN_USER_TEMP_DIR
/var/folders/85/vxc99k790z3clyfkz77dgpt00046dp/T/
nharmata-macbookair2:~ nharmata$

removing that from my ~/.bashrc, and opening a new terminal i get

nharmata-macbookair2:~ nharmata$ export | grep TMPDIR
declare -x TMPDIR="/var/folders/85/vxc99k790z3clyfkz77dgpt00046dp/T/"

but i may have modified other things between filing this bug and now.

**Comment by dmaclach** [comment]
nharmata-macbookair2:~ nharmata$ export | grep TMPDIR
declare -x TMPDIR="/var/folders/85/vxc99k790z3clyfkz77dgpt00046dp/T/"

Looks how I would expect things to look. Is it possible that you unset
TMPDIR somehow in the terminal you were working in?

Cheers,
Dave

**Comment by haxorz** [comment]
Perhaps some command I ran did so under the covers.

But in general, I don't see why a genrule should assume TMPDIR is set.

**Comment by damienmg** [comment]
Passing over P1 bug, this one was obsoleted by 946a2fb382e1d7792915de25648b27485598fc12
