### ISSUE TITLE
Site search not returning expected results

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#2562]
1. Open bazel.build
2. Search for "genrule"
Observed: No result
Expected: https://bazel.build/versions/master/docs/be/general.html to be returned as first result.

Would it be because our site is not correctly indexed? #2555?

**Comment by steren** [comment]
The problem is quite serious. Search results for most of my tests are almost irrelevant. Google Search does a very good job. I really wonder if this is not a bazel.io / bazel.build problem (#2555)

**Comment by ittaiz** [comment]
Also seeing the same...

**Comment by kchodorow** [comment]
Yeah, the complete uselessness of search has been driving me nuts, too.  Let me take a look, I definitely didn't update it from bazel.io to bazel.build, so that's a place to start.

**Comment by steren** [comment]
I get much better search results now that you fixed #2555.
Thanks!

**Comment by kchodorow** [comment]
Seriously, already?  Great!  I expected this to be much harder.
