### ISSUE TITLE
Document --spawn_strategy=standalone for test

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2571]
### Description of the problem / feature request / question:

`--spawn_strategy=standalone` actually disables sandboxing for tests. This is IMO not clear since the option  is documented under _BuildOptions_. Make it clear that it also applies for testing.

**Comment by iirina** [comment]
@philwo can you take a look at this?

**Comment by rutujasurve94** [comment]
I would like to take this bug up..

**Comment by aljabrr** [comment]
@philwo, @iirina any progress on this yet?

**Comment by philwo** [comment]
@aljabrr I don't think anyone of us is working on it. Please feel free to send a patch via Gerrit. :)

The help string for that option is here:

https://github.com/bazelbuild/bazel/blob/94fbad5b230ae0c02a88100f1978d40d17d57b71/src/main/java/com/google/devtools/build/lib/bazel/rules/BazelRulesModule.java#L51

It is used to automatically build the documentation on the website, so just changing that string to a better explanation should be enough.
