### ISSUE TITLE
do not leak PATH, LD_LIBRARY_PATH, and TMPDIR into the shell environment by default

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#2574]
`BazelConfiguration.setupShellEnvironement` makes the default shell environment inherit the `PATH`, `LD_LIBRARY_PATH`, and `TMPDIR` environmental variables from the server environment (i.e., what they are at server startup time). I can see why this might be useful, but I don't think it should be the default behavior. I observed that this behavior was a source of indeterminism when building the same code on different machines; the build products were the same, but as environment affects the action key, remote caching across the machines didn't work. Why not be hermetic by default and have users who need to change these variables pass, e.g., `--action_env=PATH`?

If the behavior can't be changed, I would at least like a way to unset those environmental variables in the shell environment from the command line. AFAICT, with `--action_env` currently, the best you can do is set them to an empty string.

**Comment by iirina** [comment]
@gregestren can you take a look at this? Thanks.

**Comment by ulfjack** [comment]
This is definitely on our todo list.

**Comment by AustinSchuh** [comment]
There's a pretty easy workaround.

Modify //tools/bazel in your repo to set the environment when it executes Bazel.  We do something like:

```
ENVIRONMENT_VARIABLES=()
ENVIRONMENT_VARIABLES+=(HOSTNAME="${HOSTNAME}")
ENVIRONMENT_VARIABLES+=(SHELL="${SHELL}")
ENVIRONMENT_VARIABLES+=(USER="${USER}")
ENVIRONMENT_VARIABLES+=(PATH="${PATH}")
ENVIRONMENT_VARIABLES+=(LANG="${LANG}")
ENVIRONMENT_VARIABLES+=(HOME="${HOME}")
ENVIRONMENT_VARIABLES+=(LOGNAME="${LOGNAME}")
ENVIRONMENT_VARIABLES+=(TERM="${TERM}")

if [[ ! -z "${DISPLAY+x}" ]]; then
  ENVIRONMENT_VARIABLES+=(DISPLAY="${DISPLAY}")
fi

exec -a "${VERSION_BAZEL}" env -i \
    "${ENVIRONMENT_VARIABLES[@]}" \
    "${VERSION_BAZEL}-real" "$@"
```

That lets us control which version of bazel is in use for each revision of the repository, and the environment.  That makes it easy to handle compatibility.

**Comment by ulfjack** [comment]
Ugh, this could be a problem...

**Comment by ittaiz** [comment]
@ulfjack Why would this be a problem?

**Comment by ulfjack** [comment]
We have some users who are very eager to use remote caching, and we've been trying to get all the necessary changes into 0.5.2, so this bug could be a problem for them.

**Comment by ulfjack** [comment]
I confirm that I see cache misses on changes to PATH in combination with bazel server restarts. :-(

**Comment by ulfjack** [comment]
I wonder if 716b527266f47f59a2b7fb2e5fc52cb45e1691b1 may have fixed this accidentally?

**Comment by ulfjack** [comment]
I saw non-zero exit twice:
```
ERROR: /.../Projects/os-bazel/src/main/java/com/google/devtools/build/lib/BUILD:1205:1: Building Java resource jar failed: singlejar failed: error executing command external/bazel_tools/tools/jdk/singlejar/singlejar --normalize --dont_change_compression --exclude_build_data --output ... (remaining 19 argument(s) skipped): Exit -1

**Comment by ulfjack** [comment]
I've started on adding a flag for migration. We can't just remove the env variables, since that is a breaking change.

**Comment by ulfjack** [comment]
I'd suggest setting --experimental_strict_action_env.

**Comment by benjaminp** [comment]
Yep, that option seems do precisely the right thing for me. Thanks.

Why does the option description mention `$LANG`, though? It doesn't actually seem to get set ever.

**Comment by ulfjack** [comment]
Sorry about that. That was from an earlier version of the change where I set LANG, which I decided not to do after all.

**Comment by ulfjack** [comment]
We need to set TMP or TEMP (or both) for local execution on Windows, but we probably don't want those in the cache key.

**Comment by jgavris** [comment]
Sorry to hijack, but I'm using `experimental_strict_action_env` right now to try this out, and I'm also seeing indeterminism. Does the working directory affect the cache key for action outputs?

**Comment by ulfjack** [comment]
Not generally, no. Need more information or maybe a reproduction case. What actions do you see being rerun? What rules are you using?

**Comment by jgavris** [comment]
Essentially, just re-running the build of the same commit on CI (all same build user, but different working directories due to hostname). I am watching the cache logs and I see basically all misses all the time, even after 3 runs. With `experimental_strict_action_env` enabled I wonder if there are other components of the cache key I'm missing.

**Comment by ulfjack** [comment]
The cache key consists of the env variables, the command line, and the (relative paths of the) input files. Any one of these can cause problems, either due to env variables that are host specific, command lines that contain absolute paths, or changes to the set of input files. Several of these can be affected by rules. Both the command-line and the env variables are easy to 'get wrong' in the sense that they accidentally are host-specific. We've tried to lock down our extension language to make it harder to do by accident, but it's still possible.

You need to figure out which one it is - try building with -s on different machines, and check whether the command lines or env variables are different.

**Comment by ulfjack** [comment]
(And the relative paths of the output files, but that's almost never a problem.)

**Comment by jgavris** [comment]
Thanks @ulfjack, the command line was the key piece of insight (sneaky absolute path to bazel binary built from HEAD). Seeing `HIT` across the board now.

**Comment by jgavris** [comment]
Just kidding, it works beautifully on linux (all cache hits), but on macOS I now seem to have the opposite problem, a full rebuild on *every* build (often before even consulting the remote cache).

**Comment by ulfjack** [comment]
Sorry, I haven't had time to reproduce your issue yet @jgavris (I also don't always have a Mac machine available). I may not be able to get to this before leaving for vacation on Saturday. Have you had any time to try to debug the issue?

**Comment by jgavris** [comment]
@ulfjack I owe you an investigation / repro first...I'm not 100% confident it's platform dependent. I probably need to hook bazel up to a debugger and step through the cache key generation on a few machines. I'll open a new issue when I can do that.

**Comment by ola-rozenfeld** [comment]
Hi! I'm using --experimental_strict_action_env and I still see the USER variable get passed to remote execution. From the code, I see https://github.com/bazelbuild/bazel/commit/9a444d4340563386b2141ab67a5bfdb14a62d311 did not purge that variable. Leaving it in means remote cache for test actions is not shared between users. Is that WAI?

**Comment by laszlocsomor** [comment]
@ola-rozenfeld : What value is `USER` set to, your actual username or some fixed value?

**Comment by ulfjack** [comment]
Where is USER set?

**Comment by ola-rozenfeld** [comment]
When I run bazel test on my workstation, the USER variable is set to my username. This value propagates to the test command:

environment_variables <
  name: "USER"
  value: "olaola"
>

I believe this might be set in StandaloneTestStrategy.java, line 67?

**Comment by benjaminp** [comment]
`--sandbox_fake_username` is useful for controlling that factor.

**Comment by ola-rozenfeld** [comment]
I tried it with the flag now, now, and it didn't work (still passed the USER variable) -- presumably because sandboxing and remote execution are different code paths. We should either enable the flag for remote execution or just always not pass USER to remote execution.

**Comment by ulfjack** [comment]
I see. Yes, it's set in StandaloneTestStrategy, and we'll need to fix that as well.

**Comment by ulfjack** [comment]
For now, you can override this behavior with --test_env=USER=<some_static_string>.

**Comment by ulfjack** [comment]
The easiest way to do it is probably to add USER=`whoami` to test-setup.sh and remove it from the StandaloneTestStrategy. It's technically a backwards-incompatible change, but I hope nobody is relying on the exact username. We could make it only set USER if it's not set by Bazel, which'd allow users to set --test_env=USER to get the old behavior back.

**Comment by benjaminp** [comment]
Is this issue completely done, or should it be left open until `--experimental_strict_action_env.` is the default?

**Comment by ola-rozenfeld** [comment]
Good point, I guess we should leave it open until `--experimental_strict_action_env` is the default.

**Comment by ulfjack** [comment]
It's still off by default.

**Comment by mboes** [comment]
@ulfjack 
> The cache key consists of the env variables, the command line, and the (relative paths of the) input files. 

Say I have two different two different projects, A and B, with two different WORKSPACE files (including different workspace names). Does this mean that if both projects happen to have targets (possibly differently named) where the inputs and actions are identical across both projects, then I'll get cache hits on project B after building project A?

**Comment by laszlocsomor** [comment]
@mboes : No, because Bazel uses different output directories for these workspaces, plus the workspace-relative file names (of the output files) are different.

**Comment by ulfjack** [comment]
There are multiple caches here. You can get a cache hit on the local or remote spawn cache, but not on the action cache, which is workspace-local, or on the in-memory cache, which is also workspace-local. If the two rules are in different locations (say //foo and //bar, then the names of the output files are likely different, in which case you can't get a cache hit either.

**Comment by mboes** [comment]
@ulfjack thanks. Is there any place you can point me to, to understand the difference between the spawn cache and the action cache? Does the (local or remote) spawn cache cache action outputs, or is that the action cache?

Being able to cache action outputs is pretty important for our use case. Haskell packages are notoriously slow to build. Many of them have source code (but not binary artifacts) published in a central location (called Hackage). We're considering running a remote cache that obviates the need for developers to have to rebuild these centrally published open source package every time they create a new project that uses them.

**Comment by ulfjack** [comment]
The spawn caches cache action outputs, the action cache works with outputs in the output tree (it doesn't cache files separately).

**Comment by mboes** [comment]
Gotcha. So IIUC, in the use case envisioned above, we should be able to avoid package rebuilds even across multiple (differently named) workspaces.

**Comment by ulfjack** [comment]
Yes, absolutely.

**Comment by ittaiz** [comment]
Ulf,
Any chance for a writeup (blog post?) about how and when the shell
environment and its paths effect the cache?

**Comment by ulfjack** [comment]
I've just fixed a number of cases where --action_env did not properly apply. I think we might want to wait for another release before we flip the default.

**Comment by danny-kuminov** [comment]
I see - makes sense, thank you!

**Comment by mboes** [comment]
> I think we might want to wait for another release before we flip the default.

Will it become the default after 0.16.0? I too am pretty keen on this. :)

**Comment by buchgr** [comment]
This has been enabled in Bazel 0.22
