### ISSUE TITLE
Android APK was rejected by Google Play because it's debuggable

### ISSUE THREAD

**Issue by fishy** [bazelbuild/bazel#2575]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I have an android_binary rule, and generated `app_unsigned.apk` file from the rule.

Then I signed it with my release key per instructions on https://github.com/bazelbuild/bazel/issues/1613, as:

```
bazel build java:app --strategy=AndroidAapt=standalone
zipalign -v -p 4 bazel-bin/java/app_unsigned.apk app-unsigned-aligned.apk
apksigner sign --ks release.jks --out app.apk app-unsigned-aligned.apk
rm app-unsigned-aligned.apk
```

When I try to publish the generated `app.apk` file on Google Play, it was rejected as "You uploaded a debuggable APK".

Bazel should provide a way to generate undebuggable APKs.

### Environment info
* Operating System:
macOS 10.12.3

* Bazel version (output of `bazel info release`):
release 0.4.4-homebrew

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by fishy** [comment]
Adding `android:debuggable="false"` into the `application` section in `AndroidManifest.xml` can workaround this issue, but that means I have to maintain two `AndroidManifest.xml` files, one for debug and one for release, which is error-prone. Bazel should provide a mechanism to generate release APK.

**Comment by iirina** [comment]
@ahumesky can you take a look please?

**Comment by ahumesky** [comment]
--compilation_mode=opt (or -copt for short) should set the debuggable flag to false, among other optimizations. We're revamping our android documentation and we'll be sure to mention this.

**Comment by fishy** [comment]
`--compilation_mode=opt` did the trick, but `-copt` doesn't work:

```
$ bazel build java:app --strategy=AndroidAapt=standalone -copt
Invalid options syntax: -copt
```

```
$ bazel build java:app --strategy=AndroidAapt=standalone --copt
Expected value after --copt
```

**Comment by ahumesky** [comment]
whoops, that's a typo, there should be a space between -c and opt ("-c opt") (i edited my comment above)

**Comment by fishy** [comment]
`-c opt` worked. Thanks!
