### ISSUE TITLE
Commit 71c72c15 breaks Bazel on Windows

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2582]
### Description of the problem / feature request / question:
See review comment on https://github.com/bazelbuild/bazel/commit/71c72c1515eb92730c28bebf65c925eadbe7b5a9

Bazel built at or after 71c72c151 doesn't work on Windows.
```
$ C:/tmp/Oh5NykPf/execroot/bazel2/bazel-out/local-fastbuild/bin/src/bazel.exe --output_user_root=/c/tmp5 build src:bazel --nobuild
Extracting Bazel installation...
Cannot terminate server process with PID 8428
.
ERROR: java.io.IOException: Could not read the crosstool configuration file 'CROSSTOOL file C:/tmp5/o6hbs7n0/external/local_config_cc/CROSSTOOL', because of a parser error (134:1: Expected identifier. Found '%').
```

### If possible, provide a minimal example to reproduce the problem:
Build bazel at 6b3b8d0ba073100bf9858fb65c2cc99dcd4d792e, it works on Windows.
Build it at 71c72c1515eb92730c28bebf65c925eadbe7b5a9, it gives the aforementioned error.

### Environment info
* Operating System: Windows 10

**Comment by iirina** [comment]
Thanks @laszlocsomor for signaling this and @mhlopko for fixing!

**Comment by EvilMudkip** [comment]
I'm having an extremely similar problem, wondering what was the fix? Thanks

**Comment by mhlopko** [comment]
Fix was in bazel, https://github.com/bazelbuild/bazel/commit/71c72c1515eb92730c28bebf65c925eadbe7b5a9. I'd suggest making sure your bazel is updated, and if the problem persists, opening a separate issue. Thanks!
