### ISSUE TITLE
Glob patterns does not accept parentheses

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2583]
```
[dmarting@trantor] /tmp/test$ cat BUILD 
filegroup(name = "test", srcs = glob(["**"], exclude = ["**/*(*"]))
[dmarting@trantor] /tmp/test$ cat WORKSPACE 
[dmarting@trantor] /tmp/test$ bazel build :test
ERROR: /tmp/test/BUILD:1:33: Traceback (most recent call last):
	File "/tmp/test/BUILD", line 1
		filegroup(name = "test", srcs = glob(["**"],..."]))
	File "/tmp/test/BUILD", line 1, in filegroup
		glob(["**"], exclude = ["**/*(*"])
illegal character '('
ERROR: no such target '//:test': target 'test' not declared in package '' defined by /tmp/test/BUILD
INFO: Elapsed time: 0.176s
FAILED: Build did NOT complete successfully
[dmarting@trantor] /tmp/test$ ls -R
.:
BUILD  WORKSPACE
```

**Comment by harmank** [comment]
@damienmg Should the exception be added in [this file](https://github.com/bazelbuild/bazel/blob/c484f19a2cf7427887d6e4c71c8534806e1ba83e/src/main/java/com/google/devtools/build/lib/syntax/GlobCriteria.java) ?

**Comment by damienmg** [comment]
I don't think so, if you [look for "illegal character"](http://cs.bazel.build/search?q=r%3Abazel+%22illegal+character%22&num=50), you find that [test](https://github.com/bazelbuild/bazel/blob/413415c6abe48153593deaa05487f40b9ce3df07/src/test/java/com/google/devtools/build/lib/packages/PackageFactoryTest.java#L790) which tends to means it was intentional to have '(' as an illegal character.

Looking at the other result, the problem is in [UnixGlob]( https://github.com/bazelbuild/bazel/blob/413415c6abe48153593deaa05487f40b9ce3df07/src/main/java/com/google/devtools/build/lib/vfs/UnixGlob.java#L140). Looking at the blame on the file and going through the history before it got open sourced it is not clear why those characters are disallowed.

**Comment by damienmg** [comment]
So this behavior dates back from the beginning of Blaze, there is no explanation whatsoever why those characters are not allowed in globs. I guess they wanted to reserve them to expand the glob pattern syntax. I would try to remove that restriction and run the test suite and see what it says :).

**Comment by harmank** [comment]
@damienmg I tried the changes (remove [illegal character declaration](https://github.com/bazelbuild/bazel/blob/413415c6abe48153593deaa05487f40b9ce3df07/src/main/java/com/google/devtools/build/lib/vfs/UnixGlob.java#L140) and its [assertion in the test](https://github.com/bazelbuild/bazel/blob/413415c6abe48153593deaa05487f40b9ce3df07/src/test/java/com/google/devtools/build/lib/packages/PackageFactoryTest.java#L790)).

It resulted in failing three tests: lib:foundations_test, lib:packages_test and skyframe:SkyframeTests. But I could not make much of the results. Here is the [log](https://gist.github.com/harmank/5ba4cfab651f394aa9b7932d5a3762d7). Thanks for all the help.

**Comment by damienmg** [comment]
@harmank the log is just telling me which test has failed. It output the test log file that you can look at to the see the actual test failure.

**Comment by raza15** [comment]
@damienmg i would like to take up this issue. Can i start working on it?

**Comment by jbduncan** [comment]
@damienmg Is this issue still open? I see that parentheses ("()") are now valid in glob patterns, but I wonder if there is a desire to allow ("{}") and ("[]") as well. If so, I'd be happy to have a go at this!

**Comment by damienmg** [comment]
Indeed that issue itself is resolved but other character might be missing, I will close this one and feel free to create separate issue for other characters.

**Comment by jbduncan** [comment]
Thank you @damienmg. I've raised a new issue at #3048. :)
