### ISSUE TITLE
Upgrade //third_party/protobuf to version >=3.2.0

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/bazel#2584]
The new version is required in order to remove `strict_proto_deps = 0` from Bazel's BUILD files.
The attribute is expected to be removed in a quarter, when an internal cleanup is complete.

I tried, but it broke freebsd. @iirina says -

> It breaks bazel build in freebsd[1]. The solution is to patch https://svnweb.freebsd.org/ports/head/devel/protobuf/files/. I rolled-back this since the other builds will not automatically start if Bazel is broken.
> 
> [1] http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=freebsd-11/1312/

**Comment by cgrushko** [comment]
This is blocked on https://github.com/google/protobuf/issues/2757, unless we're ok not build Bazel on FreeBSD.

**Comment by buchgr** [comment]
This is included in 0.5
