### ISSUE TITLE
Bazel 0.4.5rc1 javac type inference regression

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2585]
Reported by Liam upstream as https://bugs.openjdk.java.net/browse/JDK-8175794

Assigning to Liam for follow-up and updating javac.

/cc @hermione521

**Comment by cushon** [comment]
I split the InsecureCryptoUsage part into #2591.

As discussed, the type inference regression doesn't seem very severe and may not be something we want to block on.

**Comment by damienmg** [comment]
After mail discussion, let's not block the release on it. We depend too much on upstream and there is a good enough workaround.

Let's add a RELNOTEs to the release though.

**Comment by cushon** [comment]
This was fixed by 6e945ced1f3d61d2497626db9138127bcb302c77 (which included a backport of the javac fix: https://github.com/google/error-prone-javac/commit/67f328be53a1177743c0bf6477eb9911d9079e63).
