### ISSUE TITLE
generate_workspace unable to to process pinned versions

### ISSUE THREAD

**Issue by salrashid123** [bazelbuild/bazel#2588]
### Description of the problem / feature request / question:

Unable to generate a workspace with which includes a pinned dependency.

### If possible, provide a minimal example to reproduce the problem:

Attempt to generate a workspace with  io.grpc:grcp-all:1.1.2

```
bazel run //src/tools/generate_workspace -- --artifact=io.grpc:grpc-all:1.1.2
```
yields
```
 bazel run //src/tools/generate_workspace -- --artifact=io.grpc:grpc-all:1.1.2
INFO: Found 1 target...
Target //src/tools/generate_workspace:generate_workspace up-to-date:
  bazel-bin/src/tools/generate_workspace/generate_workspace.jar
  bazel-bin/src/tools/generate_workspace/generate_workspace
INFO: Elapsed time: 0.220s, Critical Path: 0.01s

INFO: Running command line: bazel-bin/src/tools/generate_workspace/generate_workspace '--artifact=io.grpc:grpc-all:1.1.2'
ERROR: Could not resolve dependency io.grpc:grpc-core:[1.1.2]: Could not find any repositories that knew how to resolve io.grpc:grpc-core:[1.1.2] (checked https://repo1.maven.org/maven2/)
ERROR: Could not resolve dependency io.netty:netty-codec-http2:[4.1.8.Final]: Could not find any repositories that knew how to resolve io.netty:netty-codec-http2:[4.1.8.Final] (checked https://oss.sonatype.org/content/repositories/snapshots, https://repo1.maven.org/maven2/)
Wrote:
/tmp/1487956563473-0/WORKSPACE
/tmp/1487956563473-0/BUILD

```

i suspect its because of version is pinned here:

[https://repo1.maven.org/maven2/io/grpc/grpc-all/1.1.2/grpc-all-1.1.2.pom](https://repo1.maven.org/maven2/io/grpc/grpc-all/1.1.2/grpc-all-1.1.2.pom)
```
<dependency>
<groupId>io.grpc</groupId>
<artifactId>grpc-core</artifactId>
<version>[1.1.2]</version>
<scope>compile</scope>
</dependency>
```

> note  --artifact=io.grpc:grpc-all:0.13.2  works but
>  --artifact=io.grpc:grpc-all:0.14.0  onwards does not

### Environment info
* Operating System:
14.04.1-Ubuntu x86_64 GNU/Linux

```
bazel info release
release 0.4.4- (@non-git)
```

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the 

[ https://maven.apache.org/pom.html#Dependency_Version_Requirement_Specification]( https://maven.apache.org/pom.html#Dependency_Version_Requirement_Specification)

**Comment by hermione521** [comment]
@kchodorow can you have a look? Thanks.

**Comment by petroseskinder** [comment]
Same issue as #3136

**Comment by kchodorow** [comment]
This was fixed in https://github.com/bazelbuild/migration-tooling.
