### ISSUE TITLE
Error: Build and run tests for Syntaxnet fail on Mac OS

### ISSUE THREAD

**Issue by coreych** [bazelbuild/bazel#2595]
### Description of the problem / feature request / question:

Couldn't start the build. Unable to run tests.

ERROR: /private/var/tmp/_bazel_/67774bec931188b8c444c9885d9c15ed/external/org_tensorflow/tensorflow/workspace.bzl:3:6: file '@io_bazel_rules_closure//closure:defs.bzl' does not contain symbol 'filegroup_external'.
ERROR: /private/var/tmp/_bazel_/67774bec931188b8c444c9885d9c15ed/external/org_tensorflow/tensorflow/workspace.bzl:4:6: file '@io_bazel_rules_closure//closure:defs.bzl' does not contain symbol 'webfiles_external'.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'tensorflow/workspace.bzl' has errors.
 
### If possible, provide a minimal example to reproduce the problem:

follow the installation instructions at https://github.com/tensorflow/models/tree/master/syntaxnet

>  bazel test --linkopt=-headerpad_max_install_names \
>    syntaxnet/... util/utf8/...

### Environment info
* Operating System:
Mac OS El Capitan ver 10.11.6

* Bazel version (output of `bazel info release`):
release 0.4.4-homebrew
 
### Anything else, information or logs or outputs that would be helpful?

file: WORKSPACE 

http_archive(
    name = "io_bazel_rules_closure",
    strip_prefix = "rules_closure-0.4.1",
    sha256 = "ba5e2e10cdc4027702f96e9bdc536c6595decafa94847d08ae28c6cb48225124",
    url = "http://bazel-mirror.storage.googleapis.com/github.com/bazelbuild/rules_closure/archive/0.4.1.tar.gz",
)

load("@io_bazel_rules_closure//closure:defs.bzl", "closure_repositories")

closure_repositories()

local_repository(
  name = "org_tensorflow",
  path = "tensorflow",
)
load("@org_tensorflow//tensorflow:workspace.bzl", "tf_workspace")
tf_workspace()

load("@org_tensorflow//tensorflow:tensorflow.bzl", "check_version")
check_version("0.4.3")

**Comment by hermione521** [comment]
If I didn't misunderstand, it looks like a problem in Tensorflow. So you failed to build tensorflow?

**Comment by coreych** [comment]
@hermione521 I couldn't build and run syntaxnet with given instructions https://github.com/tensorflow/models/tree/master/syntaxnet 

tried removing this code from WORKSPACE:

> http_archive(
name = "io_bazel_rules_closure",
strip_prefix = "rules_closure-0.4.1",
sha256 = "ba5e2e10cdc4027702f96e9bdc536c6595decafa94847d08ae28c6cb48225124",
url = "http://bazel-mirror.storage.googleapis.com/github.com/bazelbuild/rules_closure/archive/0.4.1.tar.gz",
)
> load("@io_bazel_rules_closure//closure:defs.bzl", "closure_repositories")
> closure_repositories()

and the following output from my machine:

>bazel test --linkopt=-headerpad_max_install_names \
>syntaxnet/... util/utf8/...
>ERROR: Failed to load Skylark extension >'@io_bazel_rules_closure//closure/private:java_import_external.bzl'.
>It usually happens when the repository is not defined prior to being used.
>Maybe repository 'io_bazel_rules_closure' was defined later in your WORKSPACE file?
>ERROR: cycles detected during target parsing.
>INFO: Elapsed time: 0.294s
>ERROR: Couldn't start the build. Unable to run tests.

**Comment by hermione521** [comment]
Sorry but I have no context about syntaxnet. Could you file a bug against tensorflow? Thanks.
