### ISSUE TITLE
documentation: build-ref rules outs is unclear and references non-existent figure

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/bazel#2596]
As a Bazel noob reading the build-ref document, I can't understand the section about Rules (https://bazel.build/versions/master/docs/build-ref.html#rules), the paragraph about the `outs`:

>  __***a rule***__ depends on its `srcs`, whereas __***a rule***__ is depended on by its `outs`. The two types of label attributes thus assign direction to the edges between targets, giving rise to a dependency graph.

Right after that there's a paragraph pointing to image that doesn't exist. Maybe with the image the paragraph bellow would have made more sense.
(I'm using mac OS X and Chrome 56)

> **The figure below** represents an example fragment of the build dependency graph, and illustrates: files (circles) and rules (boxes); dependencies from generated files to rules; dependencies from rules to files, and from rules to other rules. Conventionally, dependency arrows are represented as pointing from a target towards its prerequisites.

I wish I can suggest a fix but I'm not clear regarding what's supposed to be written there, yet.

**Comment by or-shachar** [comment]
Seems like [this commit](https://github.com/bazelbuild/bazel/commit/b7c00d8762d74fb54d0a6b0eb355abc6dc7a97c3) by   @kchodorow touched the figure area. I checked the previous svg code and got this image bellow. 
![image](https://cloud.githubusercontent.com/assets/2962963/23340261/d03495cc-fc3b-11e6-8bf0-f2eb720a862c.png)

**Comment by hermione521** [comment]
@kchodorow I'm not sure how it works. Can you have a look? Thanks.

**Comment by kchodorow** [comment]
Yeah, I removed them on purpose because it was annoying to get dot working as part of our CI, which was how we were generating the graphs.  We should add it back, though.

**Comment by or-shachar** [comment]
Seems to be fixed
