### ISSUE TITLE
Unnecessary rebuild of .cc file when non-included header is modified?

### ISSUE THREAD

**Issue by tomazos** [bazelbuild/bazel#2598]
If I modify a header in a `cc_library`, Bazel seems to recompile all the .cc files in the `cc_library`, even the ones they do not include the modified header?

Consider the following source files and rule:

    $ cat test1.cc
    #include "test1.h"

    $ cat test2.cc
    // empty

    $ cat test1.h
    // empty

    $ cat BUILD
    cc_library(
        name = "foo",
        hdrs = ["test1.h"],
        srcs = ["test1.cc", "test2.cc"]
    )

I fully build the `//:foo` rule.  It works as expected.

I then modify test1.h:

    $ cat > test1.h
    // empty 2

And when I rebuild `//:foo`, I observe that test2.o is rebuilt, even though it does not `#include` test1.h.

Is this expected?

If so, why doesn't bazel use the `-M` feature of gcc (or similar) like, say, cmake does, to determine which files need to be rebuilt?

**Comment by mhlopko** [comment]
:)) Did you try with bazel at HEAD? There was a (quite bad and involved) bug, but it got fixed already. But thanks for noticing!

**Comment by tomazos** [comment]
I thought I was using a build from head.  I'll try it again and get back to you.

**Comment by mhlopko** [comment]
Please do, in that case there might be a new bug. I tried with HEAD and it worked for my configuration.
