### ISSUE TITLE
iOS: Packaging happens every time a build is triggered

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#2600]
Packaging happens every time a build is triggered. In development phase, this is not needed. We should not wait for the packaging to be over to launch the simulator.

When you run `bazel build` for an ios_application, it seems like the executable should be the explicit output, and the IPA should not be packaged unless explicitly stated.

**Comment by steren** [comment]
@c-parsons we had this issue, please move it to https://github.com/bazelbuild/rules_apple if it belongs there

**Comment by sergiocampama** [comment]
Tree artifact outputs are available in rules_apple under the `--define=apple.experimental.tree_artifact_outputs=1` flag.
