### ISSUE TITLE
Bazel build doesn't kill subprocesses when it is sent control-c

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#2602]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

Sometimes I write buggy programs which run out of control and take up huge amounts of resources (e.g. infinite loops). And sometimes these programs are bazel genrules. Upon discovering that the genrules are using too many resources, I send bazel a SIGINT via Control-C. Bazel exits with an error message explaining that the build failed as expected. But the processes that were running out of control are not killed as I would expect, and I have to manually clean them up. I should not have to do this and bazel should reliably kill build rules.

### If possible, provide a minimal example to reproduce the problem:
https://gist.github.com/endobson/91bce60f7c50bfbab0324aef4e4da8c0

### Environment info
* Operating System:
OS X 10.11.2

* Bazel version (output of `bazel info release`):
dev version but same commit as 0.4.3

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
1d2fb1ffb09bb58a3a697ef730c5e41de3ed258a

**Comment by meisterT** [comment]
Seems to be fixed.

**Comment by TheKaur** [comment]
@meisterT What version is this fixed in?

**Comment by meisterT** [comment]
I don't know exactly. I just tried to repro at HEAD and could not. Does it still show up for you?

**Comment by TheKaur** [comment]
@meisterT I am on 1.0.0. I'll try a new version.
