### ISSUE TITLE
Windows: cd should use short windows path

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2604]
### Description of the problem / feature request / question:

When building ~~genrules~~ normal SpawnActions, we first `cd` into the execroot. This path should use shortened paths on Windows in order not to exceed 260 chars.

E.g.
```
ERROR: C:/work/bazel2/src/main/protobuf/BUILD:38:1: error executing shell command: 'JAR='external/local_jdk/bin/jar.exe' OUTPUT='bazel-out/vc_14_0_x64-fastbuild/bin/src/main/protobuf/libcommand_server_java_proto_srcjar.srcjar' PROTO_COMPILER='bazel-out/host/bin/third_party/protobu...' failed: bash.exe failed: error executing command
  cd C:/tmp/l90hcebl/execroot/bazel2
  SET PATH=...
```

In this case, the error was NOT due to the `cd` using forward slashes or anything, I just happened to notice this problem while looking at this log.

**Comment by abergmeier-dsfishlabs** [comment]
😕 Why are 260 characters a problem if you go through the cygwin layer?

**Comment by laszlocsomor** [comment]
Because this one isn't going through cygwin. I just realize this wasn't even a genrule, just a spawnaction, i.e. a native process we spawned with CreateProcess.

The main reason is, the current directory is always limited to MAX_PATH. Even though `SetCurrentDirectoryW`'s documentation claims you can pass long paths with the usual "\\\\?\\" prefix, in reality this doesn't work for me.

**Comment by abergmeier-dsfishlabs** [comment]
If it is P2 anyway, why not change it to use PowerShell?

**Comment by laszlocsomor** [comment]
Why would we change to PowerShell?

**Comment by abergmeier-dsfishlabs** [comment]
> Why would we change to PowerShell?

In PowerShell `\\?\` works.
And long term, `cmd` goes away, so switching must happen at some time.

**Comment by laszlocsomor** [comment]
> In PowerShell \\?\ works.

Can you show an example? It doesn't work for me:

```
PS C:\> cd \\?\C:\
cd : Cannot process argument because the value of argument "path" is not valid. Change the value of the "path"
argument and run the operation again.
At line:1 char:1
+ cd \\?\C:\
+ ~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Location], PSArgumentException
    + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.SetLocationCommand
```

Also, here's a demo about `SetCurrentDirectoryW`'s limitations:

```
#include <Windows.h>
#include <string>

int main(int, char**) {
  std::wstring path(L"\\\\?\\C:\\");
  while (::SetCurrentDirectoryW(path.c_str())) {
    path += L"aaaaaaaa.aaa\\";
    if (!::CreateDirectoryW(path.c_str(), NULL) &&
        GetLastError() != ERROR_ALREADY_EXISTS) {
      fprintf(
          stderr,
          "CreateDirectoryW failed for path %d chars long, error: %d\n",
          path.size(),
          GetLastError());
      return 1;
    }
  }
  fprintf(stderr, "Failed to `cd` into a path %d chars long\n", path.size());
  return 0;
}
```

This prints:
```
Failed to `cd` into a path 267 chars long
```

> And long term, cmd goes away, so switching must happen at some time.

Does it? Can you point me to the source? What I read was that they planned to make it non-default, not that it goes away.

**Comment by abergmeier-dsfishlabs** [comment]
>> In PowerShell \\?\ works.

> Can you show an example? It doesn't work for me:

    PS C:\Windows\System32\WindowsPowerShell\v1.0> cd \\?\C:\Projects
    PS Microsoft.PowerShell.Core\FileSystem::\\?\C:\Projects>

Can you do `$PSVersionTable.PSVersion`?
For me this prints:

    Major  Minor  Build  Revision
    -----  -----  -----  --------
    5      1      14393  693

Could this be a registry switch!?

> Does it? Can you point me to the source? What I read was that they planned to make it non-default, not that it goes away.

You might be right. Officially AFAIK there is no word from Microsoft for the latest changes.
Personally I expect it to be around for a long time but probably not get as much testing/maintenance after some time.

Nevertheless switching would be good just for the reason that error messages are a tad bit better and IMO PS insanity is not as horrible as batch insanity.

**Comment by abergmeier-dsfishlabs** [comment]
Oh, seems you are right - for me `cd \\?\C:` doesn't work either. Might be security!?

**Comment by laszlocsomor** [comment]
Yep, this looks like a registry and/or Windows version thing. I don't even have Anniversary Update.

```
PS C:\> cd C:\Users\laszlocsomor
PS C:\Users\laszlocsomor> cd \\?\C:\Users\laszlocsomor
cd : Cannot find path '\\?\C:\Users\laszlocsomor' because it does not exist.
At line:1 char:1
+ cd \\?\C:\Users\laszlocsomor
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (\\?\C:\Users\laszlocsomor:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS C:\Users\laszlocsomor> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10586  672
```

> Nevertheless switching would be good just for the reason that error messages are a tad bit better and IMO PS insanity is not as horrible as batch insanity.

I'd rather we didn't use any shell at all, if possible.

**Comment by laszlocsomor** [comment]
> Oh, seems you are right - for me cd \\?\C: doesn't work either. Might be security!?

I think that is actually an invalid path -- you need a trailing `\`.

**Comment by abergmeier-dsfishlabs** [comment]
> > Oh, seems you are right - for me cd \?\C: doesn't work either. Might be security!?

> I think that is actually an invalid path -- you need a trailing \.

Nope, that doesn't work either for me.

**Comment by abergmeier-dsfishlabs** [comment]
> I'd rather we didn't use any shell at all, if possible.

I do agree. Also important IMO is that you do not need a compiler to execute actions.

The easiest way IMO to do that is to have a binary blob, at which you concat the necessary arguments to the end of file:

    | binary | arg1len | arg1string | arg2len | arg2string |

The "correct" way would probably be to put the arguments into the const section of the Windows executable.

**Comment by laszlocsomor** [comment]
> > I'd rather we didn't use any shell at all, if possible.
> 
> I do agree. Also important IMO is that you do not need a compiler to execute actions.
> 

I'm missing context, do you mean we need a compiler to execute actions today?

For normal actions (SpawnActions) we create a native process using `CreateProcess`, with the executable we want to run. For genrules (which I'm only mentioning because I originally filed the bug talking about genrules but later corrected it) we do the same, and the executable is the MSYS bash.exe.

> The easiest way IMO to do that is to have a binary blob, at which you concat the necessary arguments to the end of file:
> ```
>     | binary | arg1len | arg1string | arg2len | arg2string |
> ```
> The "correct" way would probably be to put the arguments into the const section of the Windows executable.

Again, I'm missing context. What do you suggest this as a solution for?

**Comment by abergmeier-dsfishlabs** [comment]
> do you mean we need a compiler to execute actions today?

No, I mean we should keep the current behavior (of not needing a compiler).
Just mentioned this because you would "normally" compile a native Windows executable (needing a compiler). I would however rather advocate for building the Windows executable out of precompiled binary blobs (if possible).

Or maybe there is a better option?

**Comment by laszlocsomor** [comment]
I think we're talking about different things. I reckon you talk about the fact that, AFAIK, we currently require a C++ compiler installed, even if you don't build any C++ code. I agree that is not OK and we want to change that in the future, but we're not there yet.

There's also the matter of Bazel calling out to the shell, typically when we use `SpawnAction.Builder.setShellCommand` [1]. We also shell out on Windows in the CommandBuilder [2] -- we should stop doing so.

For SpawnActions that use simple binutils, like `cat`, `cp`, `echo`, I'd just implement them in native C++ and ship them as an embedded binary. So if the user downloads a precompiled Bazel binary, it would contain these tools already built in.

[1] https://github.com/bazelbuild/bazel/search?utf8=%E2%9C%93&q=setShellCommand&type=Code
[2] https://github.com/bazelbuild/bazel/blob/ee61191446829605b303bcfee3f2eddee437c8fc/src/main/java/com/google/devtools/build/lib/util/CommandBuilder.java#L161

**Comment by laszlocsomor** [comment]
373879d81e45a36c24322d725604e051f172d7b4 fixed this issue.
When building with `--verbose_failures` or with `-s`, we still report a long path, but that's purely cosmetic, see https://github.com/bazelbuild/bazel/blob/cb8a5e25382cb67a80449ac1fb78ae9680650b92/src/main/java/com/google/devtools/build/lib/util/CommandFailureUtils.java#L101.
