### ISSUE TITLE
Need a solution to replace Java -sourcepath in Bazel java support (use-case: Groovy stubs)

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2606]
This was reported while testing 0.4.5rc1 by a user that was not able to update to 0.4.4 due to the java bug.

```bash
$ ls -R
.:
bazel-bin  bazel-genfiles  bazel-out  bazel-test  bazel-testlogs  g  WORKSPACE

./g:
A.java  B.java  BUILD
[dmarting@trantor] /tmp/test$ cat WORKSPACE 
[dmarting@trantor] /tmp/test$ cat g/A.java
package g;
public class A {
   public A() {
      new B();
   }
}
[dmarting@trantor] /tmp/test$ cat g/B.java
package g;
public class B {
   public B() {
   }
}
[dmarting@trantor] /tmp/test$ cat g/BUILD 
genrule(
  name = "stub",
  srcs = ["B.java"],
  outs = ["B.jar"],
  cmd = "zip $@ $(SRCS)",
)

java_library(
  name = "test",
  srcs = ["A.java"],
  javacopts = ["-sourcepath $(GENDIR)/$(location :stub)", "-implicit:none"],
  deps = [":stub"]
)
```

**Comment by damienmg** [comment]
Bisecting in progress.

**Comment by damienmg** [comment]
Bisected to 3c5e55ff8e058b624ce26e803ff00434c70d4b91
/cc @cushon

**Comment by damienmg** [comment]
Working on a fix

**Comment by cushon** [comment]
Prefer:

```
genrule(
  name = "stub",
  srcs = ["B.java"],
  outs = ["B.srcjar"],
  cmd = "zip $@ $(SRCS)",
)

java_library(
  name = "test",
  srcs = ["A.java", ":stub"],
)
```

**Comment by damienmg** [comment]
As discussed offline this is WAI and we have found workaround to the user issues

**Comment by damienmg** [comment]
Workaround doesn't work, needs to find a better one or move forward with the fix.

**Comment by damienmg** [comment]
So more context for future reference:

The use case is groovy generate java stubs (interfaces) for groovy code to enable cyclic dependency between groovy code and java code. Those java stubs must be present at compile time but not in the final jar. As those stubs might be bogus, we also want to ignore them if they are not used (so java don't try to compile bogus stubs). -sourcepath + -implicit:none is the only workaround found.

We are going to move forward with that one by introducing back -sourcepath for 0.4.5 and then work on a good solution to add it to java_common.compile (as part of the work needed for #970).

**Comment by hermione521** [comment]
Is failures on darwin also related to this?
http://ci.bazel.io/job/bazel-tests/603/BAZEL_VERSION=HEAD-jdk7,PLATFORM_NAME=darwin-x86_64/

**Comment by damienmg** [comment]
Now that -sourcepath is added back we need to think of the long term solution, reassigning the issue to Lukacs for proper triaging.

**Comment by lberki** [comment]
@iirina: What do you think about having a `sourcepath` argument to `java_common.compile()`?

**Comment by iirina** [comment]
`java_common.compile` has a `javac_opts` argument, it should work to add `-sourcepath ...` there. I will try it out tomorrow.

**Comment by lberki** [comment]
@iirina : how about a `sourcepath` argument instead? In general, I prefer Bazel understanding what it does (as opposed to passing through random command line options)

**Comment by iirina** [comment]
Yes I also agree that this should be as transparent as possible. At the same time I would like to keep the API as simple as possible. Having an argument with the same name as the `javac` argument, doing the same thing, that can be also passed through `javac_opts` is repetitive and may be confusing to some users(?). I'm also afraid that if we introduce a `sourcepath` argument, users would want to add more and more arguments. I'm not sure if that's a good thing or not.
Also note that the `sourcepath` will end up in the same place, regardless of how it was specified (via a `sourcepath` argument or via the `javac_opts` argument). WDYT?

**Comment by damienmg** [comment]
The requirement is for having also "-implicit:none" for those source so changing the name might be a good idea. JavaBuilder support --sourcepath now.

**Comment by iirina** [comment]
Ah ok, sorry, I forgot about `-implicit:none`. So in this case it might be worth to add a new argument to `java_common.compile`, let's say `sourcepath_noclass` or something similar. 

If we add this, JavaBuilder will drop the support for `--sourcepath`?

**Comment by damienmg** [comment]
I don't think so (you still need that flag for resolving that bug), but it will drop support for `-sourcepath` in javacopts

**Comment by lberki** [comment]
As they say, the API should as simple as possible, but no simpler :) Since we do have a requirement to support `-sourcepath`, I think it's better to put it on the API. Even if `-implicit:none` wasn't an issue, we'd eventually end up parsing Java command lines so that we can figure out that value of `-sourcepath` and there lies madness.

**Comment by iirina** [comment]
Very well then. SGTM. Do we need to cherry pick the solution for the next RC?

**Comment by damienmg** [comment]
nope we have the temporary solution in the current RC (supporting `-sourcepath` in javacopts) so we can take the time to have a proper API for this use case.

**Comment by cushon** [comment]
> I'm also afraid that if we introduce a sourcepath argument, users would want to add more and more arguments. I'm not sure if that's a good thing or not.

I think that the javac options for files and search paths deserve arguments. (We're already doing that for `-source`, `-classpath`, `-bootclasspath`, ...). Setting `-sourcepath` via `javacopts` is clumsy because it still requires a way to express the dependency on the sources, and then doing manual `$(location ...)` expansion in `javacopts`.

And `-implicit:none` appears to be a javac-only feature (it's not supported by the eclipse compiler) so I'd vote for leaving implementation-specific details out the `java_common` API and letting people set it via `javacopts`.

**Comment by iirina** [comment]
I'm trying to reproduce the example in the first comment with bazel built @ HEAD, but it fails. I thought this should have been fixed? Also, the sourcepath test from bazel_java_test passes and I'm confused why.

**Comment by cushon** [comment]
What failure are you seeing? It works for me:

```
$ bazel build --javacopt=-verbose //g:all
...
[search path for source files: bazel-out/local-fastbuild/genfiles/g/B.jar]
...
[parsing started JarFileObject[bazel-out/local-fastbuild/genfiles/g/B.jar:/g/B.java]]
```

**Comment by iirina** [comment]
Damien helped me figure it out. It was because my files were under ` java/com/google/somename `and the expected location of `B.jar` was `com/google/somename/B.jar`. Thanks!
