### ISSUE TITLE
Accept label_string_dict for includes

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2611]
### Description of the problem / feature request / question:

Once we have `label_string_dict` (or whatever it will be called), it would be great if the reach of include statements could be controlled by labelled dicts. Something like:

    includes = {
      "//visibility:public": "include/",
      "//visibility:private": "src/",
    },

where `public` gets derived by dependants.

**Comment by laurentlb** [comment]
I need more context. Are you talking about the C++ rules?

**Comment by abergmeier-dsfishlabs** [comment]
> I need more context. Are you talking about the C++ rules?

Yes. I do think though, that this is not the best idea. Would rather have it accept a custom object, which wraps visibility similar to `select`.
