### ISSUE TITLE
Implement bazel Java sandwich

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#2614]
bazel Java sandwich allows Skylark rules to depend on Java rules and the other way around. It allows the users to do Java compilation inside a Skylark rule.

[This](https://bazel.build/designs/2016/08/04/extensibility-for-native-rules.html) is a document that explains in more details the purpose of the sandwich, but it is only informative and does NOT contain the latest API and implementation details. An updated documentation will be added soon.

The current status of the sandwich:
* Java compilation can be done in a Skylark rule
* compiling Java inside a Skylark rule will return a (black-box) declared provider that must be returned by the rule
* all native Java rules return this black-box, meaning that a Skylark rule can retrieve this black-box from all its Java dependencies and use them either as dependencies for a Java compilation, or just passing them further, for other rules to pick them up.

Some examples can be found in [these tests](https://github.com/bazelbuild/bazel/blob/10390f2dac277baeaaff48fbfd663ce687ec92e1/src/test/shell/bazel/bazel_java_test.sh) (look for tests ending in java_sandwich).

The purpose of this issue is to track progress on Java sandwich. Reporting of bugs/feature requests should be done in new issues. Questions are welcomed.

**Comment by tomlu** [comment]
Is this going to be powerful enough? If I'm reading the proposal right this will work for custom rules that transpile to Java, but it won't work for (say) Scala and similar because they will need a custom compilation action.

To implement that, it seems you'd have to be able to construct a java provider manually by feeding it the resulting jars from any compilation action. Is that part of this, or does that belong with another tracking issue?

**Comment by ittaiz** [comment]
It's mentioned in phase 2 of the doc. The second example also explicitly
gives scala as an example.

**Comment by buchgr** [comment]
can this be closed?

**Comment by sdtwigg** [comment]
I think there is a latent question on making sure native dependencies are propagated in the non-java part of  the sandwich (as exposed via https://docs.bazel.build/versions/master/be/java.html#java_binary.launcher).

However, that might be better as a separate issue?

**Comment by ittaiz** [comment]
I think we can close it.
There are still missing bits (strict deps for example) but they’re not
tracked here
