### ISSUE TITLE
Clicking on release candidate shell scripts opens them in browser

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#2615]
https://storage.googleapis.com/bazel/0.4.5/rc2/index.html

Click on one of the `.sh` links on that page.

Actual: The `.sh` script opens in the browser. It's a 164MB text file, so it kinda locks up a Chrome tab when that happens.

Expected: The script should download when you click on it.

### Environment info
* Operating System:
macOS 10.12.3, Google Chrome 56.0.2924.87

**Comment by dfabulich** [comment]
```
$ curl --silent --head https://storage.googleapis.com/bazel/0.4.5/rc2/bazel-0.4.5rc2-installer-darwin-x86_64.sh | grep Content-Type
Content-Type: text/x-sh
```

Chrome wants to open `text/x-sh` scripts in the browser. Ideally these would be sent with  `Content-Type: application/octet-stream` so the browser would just download them normally.

Barring that, another approach would be to add a `download` attribute to the `<a>` tag for those scripts.

**Comment by hermione521** [comment]
Hmm.. I checked it's generated from Markdown file and I don't see an easy way to do this.
@damienmg do you have an idea?

**Comment by damienmg** [comment]
I have manually updated the metadata on GCS for those shell script, we should do that from the release script.

**Comment by dfabulich** [comment]
Markdown supports embedded HTML. Use an `<a>` tag instead of brackets.

**Comment by damienmg** [comment]
I don't see why markdown is concerned here, the only problem is the metadata of the artifact on GCS

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
