### ISSUE TITLE
"bazel version" forces restart of server

### ISSUE THREAD

**Issue by yaroslavvb** [bazelbuild/bazel#2619]
I added `--max_idle_secs=100000000` to my `~/.bazelrc` to make sure my bazel never needs to restart, but it still restarts sometimes, for instance when running `bazel version` after a couple of days:

```
yaroslav@7:~$ bazel version
INFO: Reading 'startup' options from .bazelrc: --max_idle_secs=100000000 --output_base=/local_home/yaroslav/bazel
WARNING: Running Bazel server needs to be killed, because the startup options are different.
Build label: 0.4.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/bu
```

(PS, I'm using 0.4.2 rather than latest because 0.4.4 is broken with https://github.com/bazelbuild/bazel/issues/2526 but fixed at head)

**Comment by hermione521** [comment]
I think according to the [doc](https://bazel.build/versions/master/docs/command-line-reference.html), you should set it to 0.
