### ISSUE TITLE
unknown option: --start-lib while building bazel src

### ISSUE THREAD

**Issue by snehvyas** [bazelbuild/bazel#2620]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
Hello, I wanted to contribute to bazel and was following the steps [here](https://bazel.build/contributing.html). When I tried to build bazel it throws the following error attached as a screenshot
![screenshot](https://cloud.githubusercontent.com/assets/14810632/23485748/d2243d1e-ff02-11e6-9eb8-e209ba1ef126.png). I was looking at this [thread](https://github.com/bazelbuild/bazel/issues/2502) and felt that it deals with the same issue. I wanted to know whether there is a way around it with my Mac OS X with clang as the compiler or do we need to fix that issue first? 

### If possible, provide a minimal example to reproduce the problem:
Run `bazel build //src:build` after installing bazel using homebrew.

### Environment info
* Operating System:
Mac OS X Yosemite (10.10.5)
Clang Compiler 
![gcc version](https://cloud.githubusercontent.com/assets/14810632/23485923/b4a65848-ff03-11e6-9aa2-4c6e17442d77.png)

* Bazel version (output of `bazel info release`):
release 0.4.4-homebrew

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by hermione521** [comment]
Thanks for your (future) contribution! It looks like the same issue.
@mhlopko do you think there is a workaround?

**Comment by hermione521** [comment]
Add a link #2502

**Comment by mhlopko** [comment]
The workaround is to hardcode "false" in the cc_configure.bzl and rebuild :) What would be better instead is to investigate why cc_configure.bzl#_is_gold_supported returns true when it actually should return false. The logic is quite simple, it runs `clang -fuse-ld=gold -o /dev/null empty.cc` (empty.cc contains just `int main() {}`), and returns true when exit code is 0. Testing locally it returns 1 for me. Can you try to run the command and see what happens? And please let's continue on #2502.
