### ISSUE TITLE
running the command 'sudo apt-get install oracle-java8-installer' shows error

### ISSUE THREAD

**Issue by IvyGongoogle** [bazelbuild/bazel#2622]
hello,my system is ubuntu14.04. I run the command 'sudo apt-get install oracle-java8-installer' following (https://bazel.build/versions/master/docs/install.html#using-bazel-custom-apt-repository-recommended). but it shows error:
```
following packages have unmet dependencies:
 oracle-java8-installer : Depends: java-common (>= 0.24) but it is not going to be installed
                          Recommends: gsfonts-x11 but it is not going to be installed
                          Recommends: oracle-java8-set-default but it is not going to be installed
```
how to solve this problem.?
Thank you in advance!

**Comment by hermione521** [comment]
http://askubuntu.com/questions/563178/the-following-packages-have-unmet-dependencies

**Comment by coldestleon** [comment]
sudo apt-get install -f

**Comment by IvyGongoogle** [comment]
@hermione521 @coldestleon  thank you.

**Comment by JulyJohn** [comment]
sudo apt-get remove oracle-java8-installer

then,

sudo apt-get install oracle-java8-installer

may that help you:-0

**Comment by julianbueno** [comment]
I followed this one https://askubuntu.com/questions/336795/ubuntu-fix-dependency-problems
then 

`sudo apt-get remove oracle-java8-installer`

**Comment by asimonov-hitachi** [comment]
that oracle-java8-installer PPA is not supported anymore?

https://askubuntu.com/questions/790671/oracle-java8-installer-no-installation-candidate

shall bazel install instructions be updated with a working java install for Ubuntu?
