### ISSUE TITLE
bazel test can't be called on ios_test rules

### ISSUE THREAD

**Issue by shamanskyh** [bazelbuild/bazel#2624]
I notice that when I call `bazel test` on an `ios_test` rule, Bazel tries to invoke the iOS test runner, but fails (documented as [https://github.com/bazelbuild/bazel/issues/1387]()). It looks like the stubbed out code relies on `ios-sim`, a deprecated third-party utility for managing the iOS simulator. I’ve tried a few things to update this but haven’t had much success. Here’s what I’ve tried so far:

- Replace `ios-sim` usage with `xcrun simctl` and inject the test bundle into our dummy app. This seems like the most straightforward path — I even saw some example code in the comments of `bazel/src/tools/xcode/stdredirect/StdRedirect.c` — but the current version of xcrun wants an XCTestConfigurationFilePath. I’m pretty sure this is a binary file that only Xcode can generate without some pretty hacky code.
- Use `xcodebuild test`. This relies on an Xcode project, and I don’t think Bazel has generated the project file by the time `ios_test.sh` is called.
- Use `xcodebuild test-without-building`. I believe this requires our dummy app to have the `.xctest` files bundled within it. I could add an `ipa_post_processor` attribute to our `ios_application` rule that builds our dummy app, but I’d also need to generate an XCTestRun file. I may explore this route more, though it’s probably not the cleanest.

In the interim, our plan is to generate a single Xcode project for all our modular frameworks (using Tulsi) and run tests on CI by calling `xcodebuild test` on the generated project, but we'd really like to use `bazel test` in the long term. Do you have any suggestions on a workaround that allows us to run tests using `bazel test`?

**Comment by steren** [comment]
@c-parsons maybe you can provide guidance here?

**Comment by sergiocampama** [comment]
We know there is a gap in functionality for ios_test... we are actively working on a replacement for this and should be released in the near future.

We are also working on a replacement for ios_test in the new [Apple Rules](https://github.com/bazelbuild/rules_apple) for Bazel. Stay tuned.

**Comment by shamanskyh** [comment]
Looks like this was fixed by https://github.com/bazelbuild/rules_apple/pull/45 so I'm going to close this one out. Thanks again for all your help!

**Comment by sergiocampama** [comment]
keep in mind that the `rules_apple` test runner has limited functionality, so only `ios_unit_test`targets will work with `bazel test`. We are currently working on an open source test runner, but I can't yet give updates on when that might be released.

`ios_unit_test`  and `ios_ui_test` should be fully functional when using Tulsi, for simulators and devices.
