### ISSUE TITLE
Such problems arise when building TENSORFLOW projects on WINDOWS7: 

### ISSUE THREAD

**Issue by tiantianwei** [bazelbuild/bazel#2628]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

Such problems arise when building TENSORFLOW projects on WINDOWS7:

C:\tools\msys64\usr\tensorflow-master> bazel build //tensorflow/examples/androi
: tensorflow_demo
ERROR: in'//external:cc_toolchain'target: no such package'@local_config_cc//
Traceback (most recent call last):
How to solve

### Environment info
* Operating System:WIN7

* Bazel version (output of `bazel info release`):0.4.4

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by hermione521** [comment]
@meteorcloudy can you help with this? thanks.

**Comment by meteorcloudy** [comment]
@tiantianwei Do you have Visual Studio installed on Windows?

**Comment by tiantianwei** [comment]
Yeah, it's Visual Studio14 @ meteorcloudy

**Comment by tiantianwei** [comment]
具体问题如下：
C:\tools\msys64\usr\tensorflow-master>bazel build //tensorflow/examples/android:
tensorflow_demo
Extracting Bazel installation...
..............................
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//'
: Traceback (most recent call last):
File "C:/Users/Administrator/AppData/Local/Temp/_bazel_Administrator/SkY
7VH5k/external/bazel_tools/tools/cpp/cc_configure.bzl", line 543
_find_env_vars(repository_ctx, vs_path)
File "C:/Users/Administrator/AppData/Local/Temp/_bazel_Administrator/SkY
7VH5k/external/bazel_tools/tools/cpp/cc_configure.bzl", line 465, in _find_env_v
ars
_execute(repository_ctx, ["wrapper/get_env...."], ...)
File "C:/Users/Administrator/AppData/Local/Temp/_bazel_Administrator/SkY
7VH5k/external/bazel_tools/tools/cpp/cc_configure.bzl", line 96, in _execute
auto_configure_fail(result.stderr)
File "C:/Users/Administrator/AppData/Local/Temp/_bazel_Administrator/SkY
7VH5k/external/bazel_tools/tools/cpp/cc_configure.bzl", line 50, in auto_configu
re_fail
fail("
%sAuto-Configuration Error:%s ...))
具体问题如下：
C:\tools\msys64\usr\tensorflow-master>bazel build //tensorflow/examples/android:
tensorflow_demo
Extracting Bazel installation...
..............................
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//'
: Traceback (most recent call last):
        File "C:/Users/Administrator/AppData/Local/Temp/_bazel_Administrator/SkY
7VH5k/external/bazel_tools/tools/cpp/cc_configure.bzl", line 543
                _find_env_vars(repository_ctx, vs_path)
        File "C:/Users/Administrator/AppData/Local/Temp/_bazel_Administrator/SkY
7VH5k/external/bazel_tools/tools/cpp/cc_configure.bzl", line 465, in _find_env_v
ars
                _execute(repository_ctx, ["wrapper/get_env...."], ...)
        File "C:/Users/Administrator/AppData/Local/Temp/_bazel_Administrator/SkY
7VH5k/external/bazel_tools/tools/cpp/cc_configure.bzl", line 96, in _execute
                auto_configure_fail(result.stderr)
        File "C:/Users/Administrator/AppData/Local/Temp/_bazel_Administrator/SkY
7VH5k/external/bazel_tools/tools/cpp/cc_configure.bzl", line 50, in auto_configu
re_fail
                fail("
%sAuto-Configuration Error:%s ...))
Specific questions are as follows:
C:\tools\msys64\usr\tensorflow-master>bazel build //tensorflow/examples/android:
Tensorflow_demo
Extracting Bazel installation...
..............................
ERROR: in'//external:cc_toolchain'target: no such package'@local_config_cc//'
Traceback (most recent call last):
File "C:/Users/Administrator/AppData/Local/Temp/_bazel_Administrator/SkY
7VH5k/external/bazel_tools/tools/cpp/cc_configure.bzl ", line 543
_find_env_vars (repository_ctx, vs_path)
File "C:/Users/Administrator/AppData/Local/Temp/_bazel_Administrator/SkY
7VH5k/external/bazel_tools/tools/cpp/cc_configure.bzl ", line 465, in _find_env_v
ARS
_execute (repository_ctx, ["wrapper/get_env..."),...
File "C:/Users/Administrator/AppData/Local/Temp/_bazel_Administrator/SkY
7VH5k/external/bazel_tools/tools/cpp/cc_configure.bzl ", line 96, in _execute
Auto_configure_fail (result.stderr)
File "C:/Users/Administrator/AppData/Local/Temp/_bazel_Administrator/SkY
7VH5k/external/bazel_tools/tools/cpp/cc_configure.bzl ", line 50, in auto_configu
Re_fail
(fail"
%sAuto-Configuration Error:%s...)

**Comment by tiantianwei** [comment]
Specific questions are as follows:
C:\tools\msys64\usr\tensorflow-master>bazel build //tensorflow/examples/android:
Tensorflow_demo
Extracting Bazel installation...
..............................
ERROR: in'//external:cc_toolchain'target: no such package'@local_config_cc//'
Traceback (most recent call last):
File "C:/Users/Administrator/AppData/Local/Temp/_bazel_Administrator/SkY
7VH5k/external/bazel_tools/tools/cpp/cc_configure.bzl ", line 543
_find_env_vars (repository_ctx, vs_path)
File "C:/Users/Administrator/AppData/Local/Temp/_bazel_Administrator/SkY
7VH5k/external/bazel_tools/tools/cpp/cc_configure.bzl ", line 465, in _find_env_v
ARS
_execute (repository_ctx, ["wrapper/get_env..."),...
File "C:/Users/Administrator/AppData/Local/Temp/_bazel_Administrator/SkY
7VH5k/external/bazel_tools/tools/cpp/cc_configure.bzl ", line 96, in _execute
Auto_configure_fail (result.stderr)
File "C:/Users/Administrator/AppData/Local/Temp/_bazel_Administrator/SkY
7VH5k/external/bazel_tools/tools/cpp/cc_configure.bzl ", line 50, in auto_configu
Re_fail
(fail"
%sAuto-Configuration Error:%s...)

**Comment by tiantianwei** [comment]
I just want to know, "cc_toolchain" this package is specified in which file

**Comment by aj-michael** [comment]
@tiantianwei This does not address the error message that you are seeing, but Bazel does not yet support building Android targets on Windows. So you will not be able to build ` //tensorflow/examples/android:tensorflow_demo` on Windows 7.

**Comment by tiantianwei** [comment]
@aj-michae OK, I'll think of something else, and thank you very much for your answer

**Comment by jin** [comment]
Closing as issue is stale. @tiantianwei please reopen if you are still running into the error. Thanks.
