### ISSUE TITLE
Implement authentication for maven_jar

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#264]
Probably this would be a good time to add a maven_repository rule for specifying a default repo (maybe just point at a settings.xml file).

**Comment by ajorgensen** [comment]
+1 I have dependencies that come from a private artifactory where the username, password, and repo are all defined in the maven settings.xml file. It would be awesome if bazel could tap into this.

**Comment by damienmg** [comment]
@kchodorow: do you know when you can address this issue?

**Comment by kchodorow** [comment]
Currently working on it.  A new maven_server rule should be coming out in the next push.  It doesn't do anything yet, but will be used for authentication.

**Comment by kchodorow** [comment]
46d6dc54fc5352b7e463494de4a82bdf2c5168fe adds a maven_server rule and reads in a settings.xml file.  Basic auth is on the way.

**Comment by damienmg** [comment]
Marking this as closed now we have support for basic authentication. Please file more precise bug if needed.
