### ISSUE TITLE
Flush print() messages more quickly, in repo rules

### ISSUE THREAD

**Issue by rosun82** [bazelbuild/bazel#2641]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

It seems that the message printed from print(...) in skylark rules are only available at the end of the build execution. This makes it extremely hard for debugging if the build rule takes a long time to finish (retrieving big packages through the network, etc.)

print(...) in the skylark rules should be treated more like LOG(INFO) than printf(...)

### Environment info
* Operating System: Linux

* Bazel version (output of `bazel info release`): 0.4.4

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

No

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by dslomov** [comment]
Should inform future 'debugprint' design

**Comment by buchgr** [comment]
I also need this for debugging repository rules. @laurentlb does it sound reasonable to immediately flush print() statements?

**Comment by laurentlb** [comment]
The original bug was for Starlark rules, and it has been fixed a long time ago.

I wasn't aware there's still a problem for repository rules.

**Comment by buchgr** [comment]
In a repository_rule the print() statements are also only flushed once the rule finishes.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
