### ISSUE TITLE
'Reference' link in Extensions on Docs page is broken

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#2643]
'Extensions | Reference' in NavBar goes to https://bazel.build/versions/master/docs/skylark-overview.html which does not exist

**Comment by dslomov** [comment]
@fweikert could you take a look?

**Comment by fweikert** [comment]
David, any idea how to integrate the newly added skylark-overview.html into the Bazel documentation?

Context: I replaced the dropdown menu in our navigation with a single overview page, which is also being generated dynamically.

**Comment by fweikert** [comment]
The file exists at https://bazel.build/versions/master/docs/skylark/lib/skylark-overview.html

**Comment by davidzchen** [comment]
Looks like the link needs to be fixed. The overview page is in the `skylark/lib` directory under `docs/` but the link just points to `https://bazel.build/versions/master/docs/skylark-overview.html`.

**Comment by fweikert** [comment]
https://github.com/bazelbuild/bazel/commit/a1ea9963d33f87ed61739c72c495f73246119eea and https://github.com/bazelbuild/bazel/commit/3b99ad4144bc8530dc7454c539472ec5c7f415e8 fixed this problem:
https://bazel.build/versions/master/docs/skylark/lib/skylark-overview.html
