### ISSUE TITLE
VanillaJavaBuilder crash

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#2646]
I see a crash in VanillaJavaBuilder for code that isn't Java 7 compatible. The code in question was a method call that expected an ImmutableList<ActionInput> and the call passed ImmutableList.of() (no generic type arguments).

ERROR: /private/var/netboot/workspace/ddc67438cdfa06f96f3626c4c01ca16f_434048_19216/tmp/execution_root/src/main/java/com/google/devtools/build/lib/BUILD:511:1: Couldn't build file src/main/java/com/google/devtools/build/lib/libbuild-base.jar: Java compilation in rule '//src/main/java/com/google/devtools/build/lib:build-base' failed: java failed: error executing command external/local_jdk/bin/java -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac7.jar -XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -jar ... (remaining 2 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Exception in thread "main" java.lang.NullPointerException
	at com.google.devtools.build.buildjar.VanillaJavaBuilder.run(VanillaJavaBuilder.java:200)
	at com.google.devtools.build.buildjar.VanillaJavaBuilder.main(VanillaJavaBuilder.java:93)
ERROR: /private/var/netboot/workspace/ddc67438cdfa06f96f3626c4c01ca16f_434048_19216/tmp/execution_root/src/main/java/com/google/devtools/build/lib/BUILD:511:1: Couldn't build file src/main/java/com/google/devtools/build/lib/libbuild-base.jar: Java compilation in rule '//src/main/java/com/google/devtools/build/lib:build-base' failed: java failed: error executing command external/local_jdk/bin/java -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac7.jar -XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -jar ... (remaining 2 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Exception in thread "main" java.lang.NullPointerException
	at com.google.devtools.build.buildjar.VanillaJavaBuilder.run(VanillaJavaBuilder.java:200)
	at com.google.devtools.build.buildjar.VanillaJavaBuilder.main(VanillaJavaBuilder.java:93)

Expected output:
src/main/java/com/google/devtools/build/lib/exec/StandaloneTestStrategy.java:122: error: cannot find symbol
            /*tools=*/ImmutableList.<Artifact>of(),
                                     ^
  symbol:   class Artifact
  location: class StandaloneTestStrategy

The change on which this happened is cl/149290623 (internal). It's probably trivial to reproduce, though.

**Comment by cushon** [comment]
Thanks, I repro'd and mailed a fix.

**Comment by ulfjack** [comment]
I'm still seeing this issue (or an issue exactly like it) in a presubmit today:
```
ERROR: /private/var/netboot/workspace/9013cd9ab5f860a86b3c9dbdc42862b8_621769_105/tmp/execution_root/src/test/java/com/google/devtools/build/lib/BUILD:1054:1: Couldn't build file src/test/java/com/google/devtools/build/lib/remote-tests.jar: Java compilation in rule '//src/test/java/com/google/devtools/build/lib:remote-tests' failed: java failed: error executing command external/local_jdk/bin/java -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac7.jar -XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -jar ... (remaining 2 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Exception in thread "main" java.lang.NullPointerException
	at com.google.devtools.build.buildjar.VanillaJavaBuilder.run(VanillaJavaBuilder.java:200)
	at com.google.devtools.build.buildjar.VanillaJavaBuilder.main(VanillaJavaBuilder.java:93)
```

**Comment by ulfjack** [comment]
If we check in a jar, maybe we just haven't updated that yet?

**Comment by philwo** [comment]
This is blocking the merge of a contributed CL by Alpha. I'll have a look at whether we forgot to create / update a checked in JAR in Bazel tomorrow.

**Comment by ulfjack** [comment]
I think our CI is running with released Bazel, which doesn't contain the fix. I tried running at HEAD and that works.

**Comment by ulfjack** [comment]
Well, it works in the sense that it'll give a reasonable error message, not crash - you still need to fix the code to work properly. If you have a working Bazel binary, here's how to do a build with Java 7:

```
bazel build //third_party/protobuf:protoc //third_party/grpc:grpc-java-plugin
cp bazel-bin/third_party/protobuf/3.0.0/protoc bazel-bin/third_party/grpc/grpc-java-plugin /tmp
JAVA_VERSION=1.7 PROTOC=/tmp/protoc GRPC_JAVA_PLUGIN=/tmp/grpc-java-plugin ./compile.sh
cp output/bazel /tmp/bazel1.7
/tmp/bazel1.7 build --define=JAVA_VERSION=1.7 -k //src/test/...
```

**Comment by philwo** [comment]
Thanks @ulfjack for the easy to use reproduction steps!

I was able to find the compilation issue preventing the presubmit for Alpha's change from passing using that. It was then just a one-line fix to make that code Java 7 compatible.
