### ISSUE TITLE
Bazel installation on Windows 7

### ISSUE THREAD

**Issue by junyongyou** [bazelbuild/bazel#2648]
I tried to install the "bazel-0.4.4-windows-x86_64.exe". I have installed msys64 (version 20160205), msys-2.0.dll is in my PATH, and set BAZEL_SH=d:/msys64/usr/bin/bash.exe. But I don't know how to set JAVA_HOME="$(ls -d C:/Program\ Files/Java/jdk* | sort | tail -n 1)", because my JAVA_HOME is already set as the JDK directory (I have JDK8). I put d:/msys64/usr/bin in the first in my PATH. I also did "pacman -Syuu gcc git curl zip unzip zlib-devel". 

Then I tried to run "bazel-0.4.4-windows-x86_64.exe", but only got a message of "Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8", which is set in my Environment variables. Then nothing happened, and bazel was not installed.

Could anybody help me on how to install bazel (better to use a binary) on Windows7 64-bit? I don't care which bazel version will be used, I want to use TensorFlow which needs bazel. I already searched on other webs, including the Github issues, but didn't find an answer. Thanks a lot.

**Comment by meteorcloudy** [comment]
The simplest way to install Bazel on Windows is using chocolatey.
Can you follow https://bazel.build/versions/master/docs/install.html#install-on-windows-chocolatey ?
A simple `choco install bazel` should do.

**Comment by meteorcloudy** [comment]
BTW, if you don't need to built TensorFlow, you can just install their Python pip package.

**Comment by junyongyou** [comment]
Thanks a lot. I need to build TensorFlow, so I will try chocolatey.
