### ISSUE TITLE
Add a metric to track wasted build time.

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#2649]
One issue we have is that most engineers don't want to think much about build. So they add dependencies until things compile, but don't always remove them back down to get a minimal set.

An idea for a metric for bazel to track occured to me: build precision:

It is (out of date build time)/(total build time).

So, if I rebuild something, but then it was already up to date, this does not count towards out of date build time.  If we build a target and the hash of the outputs does not change from what it was previously, we can assume that was a wasted build effort.

Ideally, we want the above ratio to be 1. When it is less than one we may have overbroad dependencies or bugs in our skylark build rules.

One can even imagine bazel having something like a branch predictor that keeps statistics per target on how often a changed input still yields an up-to-date output to speculatively increase parallelism in the build, and to warn to highly "insensitive" targets (which may have overbroad dependencies).

https://groups.google.com/forum/#!topic/bazel-discuss/MmDaQ2nCLoE

**Comment by abergmeier-dsfishlabs** [comment]
IMO it would be better to have a way to mark an action as hermetic and path independent. This means if all inputs have the same "content" you could reason that building is not necessary.

**Comment by johnynek** [comment]
I *thought* all actions should have this property @abergmeier-dsfishlabs ?

I think this is already how bazel works, unless i'm confused. What I am talking about is the down-side of this: when we needlessly skip the cache because the user incorrectly claims to depend on something they don't really need.

**Comment by meisterT** [comment]
If we would want to go ahead, we could include this in the build event protocol.
But I am not convinced this is actionable in a lot of cases.

If you change just a comment, the action will show up there. If you change the public ABI of a java file but the new method is not used by the downstream library, the action will show up.
I'll close the bug because of these concerns. Feel free to comment/re-open if you have a concrete proposal.
