### ISSUE TITLE
Installer script broken on macOS / 0.4.3, 0.4.4, 0.4.5rc5: symlink is incorrect if the path to --prefix arg is relative

### ISSUE THREAD

**Issue by petemounce** [bazelbuild/bazel#2653]
### Description of the problem / feature request / question:

When I try to install bazel using the bash script, it fails when uncompressing the installation.

It looks like the `{prefix}/bin/bazel` symbolic link is broken (but I don't know why, and attempts to recreate it manually have yielded the same results. I wasn't able to find how the installer is created, either, to add debugging to it).

(I need to install a specific version, and homebrew doesn't allow me to do this easily since it doesn't have formulae for patch versions)

### If possible, provide a minimal example to reproduce the problem:

```
$ wget -q --no-clobber "https://github.com/bazelbuild/bazel/releases/download/0.4.3/bazel-0.4.3-installer-darwin-x86_64.sh"

$ ./bazel-0.4.3-installer-darwin-x86_64.sh --prefix=.local_bazel --bazelrc=.local_bazel/bazelrc
Bazel installer

... snipped ...

   - [Commit](https://github.com/bazelbuild/bazel/commit/1d2fb1f)
Uncompressing......./bazel-0.4.3-installer-darwin-x86_64.sh: line 224: .local_bazel/bin/bazel: No such file or directory
```

After having run, the filesystem tree is:
```
$ tree .local_bazel
.local_bazel
├── bazelrc
├── bin
│   └── bazel -> .local_bazel/lib/bazel/bin/bazel
└── lib
    └── bazel
        ├── bin
        │   ├── bazel
        │   ├── bazel-complete.bash
        │   └── bazel-real
        └── etc

$ ls -al .local_bazel/bin
total 8
drwxr-xr-x  3 peter  staff   102B  8 Mar 08:21 .
drwxr-xr-x  5 peter  staff   170B  8 Mar 08:21 ..
lrwxr-xr-x  1 peter  staff    32B  8 Mar 08:21 bazel -> .local_bazel/lib/bazel/bin/bazel
```

The symlink is broken but the binary is fine:
```
$ .local_bazel/bin/bazel version
zsh: command not found: .local_bazel/bin/bazel

$ .local_bazel/lib/bazel/bin/bazel version
.............
Build label: 0.4.3
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 22 12:31:39 2016 (1482409899)
Build timestamp: 1482409899
Build timestamp as int: 1482409899
```

*Note:* I've tried this in bash too, makes no difference.

### Environment info
* Operating System:
macOS 10.12.3

* Bazel version (output of `bazel info release`):
n/a - it doesn't get that far. I'm using the 0.4.3 install script

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by petemounce** [comment]
This happens with 0.4.4 too.

```
$ ./bazel-0.4.4-installer-darwin-x86_64.sh --prefix=.local_bazel --bazelrc=.local_bazel/bazelrc
Bazel installer
---------------

Bazel is bundled with software licensed under the GPLv2 with Classpath exception.
You can find the sources next to the installer on our release page:
   https://github.com/bazelbuild/bazel/releases

# Release 0.4.4 (2017-02-01)

Baseline: 4bf8cc30a

...snipped...

   - [Commit](https://github.com/bazelbuild/bazel/commit/80a07b5)
Uncompressing......./bazel-0.4.4-installer-darwin-x86_64.sh: line 272: .local_bazel/bin/bazel: No such file or directory
```

**Comment by petemounce** [comment]
0.4.5rc5 as well:
```
peter at petermounce-mbp-imp in ~/src/IW/everything (bugfix/bazel-pinning●●)
$ rm -rf .local_bazel

peter at petermounce-mbp-imp in ~/src/IW/everything (bugfix/bazel-pinning●●)
$ ./bazel-0.4.5rc5-installer-darwin-x86_64.sh --prefix=.local_bazel --bazelrc=.local_bazel/bazelrc

Bazel installer
---------------

Bazel is bundled with software licensed under the GPLv2 with Classpath exception.
You can find the sources next to the installer on our release page:
   https://github.com/bazelbuild/bazel/releases

# Release 0.4.5rc5 (2017-03-08)

Baseline: 2e689c29d5fc8a747216563235e905b1b62d63b0

...snipped...

   - [Commit](https://github.com/bazelbuild/bazel/commit/dcdd1c1)
Uncompressing......./bazel-0.4.5rc5-installer-darwin-x86_64.sh: line 265: .local_bazel/bin/bazel: No such file or directory
```

**Comment by damienmg** [comment]
The solution is to provide an absolute path to the installer:
`./bazel-0.4.5rc5-installer-darwin-x86_64.sh --prefix=$PWD/.local_bazel --bazelrc=$PWD/.local_bazel/bazelrc`

We should maybe try to get a complete path when creating the symlink

**Comment by petemounce** [comment]
@damienmg no; sorry, I should have said. I tried that via `$(pwd)/.local_bazel` and got the same result.

**Comment by damienmg** [comment]
Wait I just tried with $PWD/.local_bazel (the command I gave) and it worked without problem, withou $PWD I can repro. Can you give me the full command you run?

**Comment by petemounce** [comment]
Huh. When I tried `./bazel-0.4.3-installer-darwin-x86_64.sh --prefix=$(pwd)/.local_bazel --bazelrc=$(pwd)/.local_bazel/bazelrc` then it worked fine. Same if I used `$PWD` instead of `$(pwd)`.

**Comment by ajayramesh23** [comment]
Just a heads up - I am participating in GSoC, I am currently working on this issue.

**Comment by meisterT** [comment]
Is this still an issue?

**Comment by wondfor** [comment]
Is this still an issue?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
