### ISSUE TITLE
new_http_archive incorrectly reports a symlink pointing to a file outside of the zip archive

### ISSUE THREAD

**Issue by hazelnusse** [bazelbuild/bazel#2656]
When using new_http_archive to fetch a zip archive containing a symlink, bazel incorrectly reports that the symlink points outside of the directory.

Minimal working example can be found here:
https://github.com/hazelnusse/bazel-tests
https://github.com/hazelnusse/archive

the bazel-tests repo tries to fetch a very simple archive.zip file from the archive repository. This repository has a README.md at the top level, and a symlink at doc/README that points to README.md. It also a simple hello-world.cpp. The specific error I get is:

ERROR: no such package '@archive//': Error extracting /private/var/tmp/_bazel_luke.peterson/01b1e629b21d1dee999fd6ba57a48b02/external/archive/master.zip to /private/var/tmp/_bazel_luke.peterson/01b1e629b21d1dee999fd6ba57a48b02/external/archive: Zip entries cannot refer to files outside of their directory: master.zip has a symlink to ../README.md.
INFO: Elapsed time: 1.921s

I ran into this issue when trying to get bazel to build flatbuffers, which has a symlink at docs/source/CONTRIBUTING.md that points to ../../CONTRIBUTING.md. At first I thought it was because this was an invalid symlink but even after fixing the invalid symlink that the problem still persists:

https://github.com/google/flatbuffers/issues/4211

**Comment by hazelnusse** [comment]
Possible duplicate of:
https://github.com/bazelbuild/bazel/issues/1997

**Comment by kchodorow** [comment]
Yeah, https://github.com/bazelbuild/bazel/blob/b4060b6e53944a7c3bdc5e62b288e7293a87652a/src/main/java/com/google/devtools/build/lib/bazel/repository/ZipDecompressor.java#L129-L132 disallows all up-level references.  This is a bit harsh, we could allow symlinks that don't travel up past the root dir.

**Comment by thomaso-mirodin** [comment]
Just hit this bug as well because of test fixture (replicating `/proc`). 

If you are pulling from github you can quickly work around this by switching from grabbing a zip to grabbing a tarball:
```diff
- url = "https://github.com/<user>/<repo>/archive/<commit>.zip",
- type = "zip",
+ url = "https://github.com/<user>/<repo>/archive/<commit>.tar.gz",
+ type = "tar.gz",
```

**Comment by aehlig** [comment]
suggested fix: https://bazel-review.googlesource.com/c/bazel/+/34352

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by g-easy** [comment]
I'm running bazel 0.10.1 and this is still a problem.

**Comment by aherrmann** [comment]
This seems to be still an issue in Bazel 0.28.1, see https://github.com/digital-asset/daml/pull/2642#discussion_r316999137
cc @cocreature
