### ISSUE TITLE
new_http_archive sandboxing breaks build

### ISSUE THREAD

**Issue by hazelnusse** [bazelbuild/bazel#2657]
### Description of the problem / feature request / question:
I'm attempting to build flatbuffers with bazel using new_http_archive()

### If possible, provide a minimal example to reproduce the problem:
A standalone example of the problem can be seen by trying to build flatc with bazel here:
https://github.com/hazelnusse/flatbuffers-bazel/tree/master

The same BUILD file, when used without new_http_archive(), succeeds with no errors, as can be seen by running fetch_unzip_build.sh on this branch:

https://github.com/hazelnusse/flatbuffers-bazel/tree/works_without_using_new_http_archive

Or, if you enter the bazel-flatbuffers-bazel/external/flatbuffers/ directory that is symlinked, and run `bazel build //:flatc`, the build succeeds (I know I'm not supposed to run anything from here but I just wanted to see).  The only difference I can see is that the workspace file that is in that directory, rather than being empty has the line `workspace(name = "flatbuffers")`.

The way the build breaks is that an include path is not found, so there must be some difference in how bazel is invoked when new_http_archive that breaks the include paths.

### Environment info
* Operating System:
Mac OS X 10.11.6

* Bazel version (output of `bazel info release`):
release 0.4.4-homebrew

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by hazelnusse** [comment]
[all_output.txt](https://github.com/bazelbuild/bazel/files/829576/all_output.txt)

**Comment by hazelnusse** [comment]
[all_output_successful.txt](https://github.com/bazelbuild/bazel/files/829585/all_output_successful.txt)

**Comment by robbiexperiel** [comment]
I've ran into the same issue before (also with flatbuffers) and resolved it by adding `includes = ["include", "grpc"]` to the flatc cc_binary rule.

It definitely doesn't seem like the correct solution, but it got around the issue for now.

**Comment by hazelnusse** [comment]
@robbiexperiel Thanks for the workaround. Do you understand what the root cause is? I'm perplexed how the same build file works in isolation but not when used by new_http_archive()

**Comment by robbiexperiel** [comment]
I don't remember the details, but at a high level I believe it has to do with the fact that when flatbuffers is pulled in as an http_archive, it gets placed in bazel-master/external/<name> rather than living in the root directory, which messes with include paths.

I assume this is a bug, not intended behavior. Would someone from the bazel team be able to confirm?

**Comment by dslomov** [comment]
new_http_archive is no more
