### ISSUE TITLE
ExtraAction overexecution via CppCompileAction include pruning

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#2659]
### Description of the problem:

Races between ExtraActions/ExtraActionInfoFileWriteActions and their shadowedAction when that shadowedAction has unknown inputs cause overexecution of both.  Keys, generated by both ExtraAction-actions, are invalidated when the inputsKnown is eventually evaluated, and seen in large builds as a constant no-op build cost.  The change to CppCompileAction to make inputsKnown mostly-initially false has demonstrated this.

### If possible, provide a minimal example to reproduce the problem:

This is a race, and requires a large enough build with earlier/concurrent execution of extra actions with their shadowedAction.  Philosophically, create a workspace with a cc_* and srcs, specify an --experimental_action_listener which results in output, build once, and there is a possibility that the next build will exhibit the issue.  -s will be required to observe the action definitively.

### Environment info
* Operating System:

Linux

* Bazel version (output of `bazel info release`):

development version

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

master HEAD - 747c216887d35ce1e89ab0b0983088f8af90e8aa

### Other Notes

I have worked around this by, in the case of an inputsKnown() == false shadowed action at createInputs invocation time, switching the inputs of the action to the shadowedAction outputs.  If that is worthwhile, I will post a pull request.

**Comment by werkt** [comment]
This also applies to the new getExtraActionBuilder implementation returned by CppCompileAction - ExtraActionInfoFileWriteAction depends upon its representation to computeKey, and this changes from before to after building.  It should probably be using getInputsWhenSkippingDiscovery, instead of varying its behavior depending upon whether the inputs are known.

**Comment by lberki** [comment]
That's interesting. We have specific machinery in place to prevent this by special-casing actions that discover inputs in the action cache:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/actions/cache/ActionCache.java#L158

and updating the inputs of the action from the action cache on server startup:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/actions/ActionCacheChecker.java#L249

Does a server restart need to happen to trigger this bug? I'd be surprised if the bug could be tickled without a server restart, since then we don't actually hit `ActionCache` to verify that an action should not be re-executed.

`ExtraActionnfoFileWriteAction` also doesn't call `Action#getInputs()` so I don't see how it could be affected by the return value of that method having been changed.

**Comment by lberki** [comment]
@janakdr FYI

**Comment by werkt** [comment]
That the ActionCache specifically handles discoversInputs actions (including on server shutdown) is definitely not in question here - what's going on is simply that both the ExtraAction and the ExtraActionInfoFileWriteAction don't depend on the satisfaction of inputsKnown in their shadowedAction.  This results in a race between them and discoversInputs shadowedActions that require their action's execution to complete (as in CppCompileAction) in order to make the inputs known (but more specifically making their inputs up-to-date, since this can exhibit staleness in the case of a changed source file).  I would be very surprised to see discoversInputs Actions that don't rely on their own execution to actually fulfill inputsKnown.

A server restart is not required, but as I noted before in previous bug reports, there appears to be a special consideration for builds with interleaved queries and the evaluation through the ActionCache for at least the C++ compiles required for cc_test.  A server restart will likely exhibit the problem more broadly, as, as you've indicated, the ActionCache is evaluated for each target requested.

ExtraActionInfoFileWriteAction *does* call getInputs in the CppCompileAction case through getExtraActionInfo, which *conditionally* returns a set including getInputs() if the inputs are known, *or* a list including the declared include paths.  That in an of itself seems wrong - getExtraActionInfo() changing between execution states is the cause of differentiated output in the .xa file, as well as the computed key of the ExtraActionInfoFileWriteAction changing from pre/post updateInputs

**Comment by lberki** [comment]
Argh, my bad, I didn't notice the `#getInputs()` call in `CppCompileAction#getExtraActionInfo()`. Should maybe put my brain in gear... which makes it clear where the race condition lives :)

That said, I don't think there is a race condition between the extra action and the shadowed action because this line makes sure that the former is executed only after the latter:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/extra/ExtraActionSpec.java#L88

So it seems like the easiest fix is to do the same for `ExtraActionInfoFileWriteAction`. WDYT?

**Comment by werkt** [comment]
It appears my reproduction of this was mixed between 0.4.2 and my master copy - yes, that discoversInputs() addition in the spec looks like it should be satisfactory (0.4.2 didn't have such a distinction).

That fix should also cover the FileWriteAction, but here's some food for thought: we see a pretty hefty analysis overhead cost associated with adding extra actions (won't get into numbers, but let's say it takes 100% of our actions and makes it 150%), and I have some idea that the massive numbers of edges created between the ExtraAction{,InfoFileWriteAction} and their shadowedActions (in this case, CppCompileAction and swaths of inputs) is causing a proportionally large performance problem.  

That's the long way around saying I think the input list for those actions should be reduced to the shadowedAction outputs (either in the discoversInputs case or generally) - I don't believe I see evidence of them accessing anything but the in-memory action state to do their job.

**Comment by werkt** [comment]
Having tried to apply the same fix (adding actionToShadow.getOutputs() to the InfoFileWriteAction), I still ran into invalidations of the ExtraAction itself: validateArtifacts indicated differences during explain.

It is likely due to https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/extra/ExtraAction.java#L83, where it is relying on initially consistent values for getInputs().  Managed to get past this by rejecting shadowedActionInputs in favor of shadowedActionOutputs for discoversInputs.

**Comment by werkt** [comment]
And not to drive this into the ground, but I also had to prevent passthrough of the inputsKnown/discoversInput values from the shadowedAction, otherwise discoverInputs would be called and incorrectly update the now-always-known inputs.

**Comment by lberki** [comment]
@werkt : what do you mean by "initially consistent values for getInputs()"? CppCompileAction should return consistent values there in general. It changes, of course, but updateInputs() calls should take care of that.

**Comment by werkt** [comment]
Since the result of CppCompileAction#getInputs changes, the test performed in validateArtifacts fails, because the computed key based on the previous input set (pre-compilation, and evaluated at the time that the ExtraAction is created, not when it is executed) no longer matches the digest of the inputs that ActionCacheChecker computes on the next run.

This is actually very easy to replicate: observe, with an extra action, the inputs for the ExtraAction at instantiation time, then --explain a subsequent build.  Pretty sure it doesn't even require parallel execution.

**Comment by lberki** [comment]
I'm somewhat surprised at this, because we have code to handle this specific case. In fact, actions discovering inputs are special-cased in the action cache just for this reason...

(I'm currently spelunking in ExtraAction to debug an issue that may turn out to be this exact one...)

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
