### ISSUE TITLE
Support different deployment targets for ios_extension, etc.

### ISSUE THREAD

**Issue by dflems** [bazelbuild/bazel#2661]
There should be a way to set the iOS minimum deployment target on a per-rule level, at least for certain types of iOS rules.

For example, I have an iMessage app extension which requires a minimum deployment version of 10.0. The minimum iOS deployment target for our application is 8.0 (set with `--ios_minimum_os` on the command line). Setting this causes ALL targets to have that 8.0 minimum deployment version set. I have a storyboard file that uses classes that are only available in iOS 9.0 and up, so `ibtool` fails with an error. If I could set the deployment target on this extension to iOS 10, it would solve this issue as well as `-Wpartial-availability` compiler warnings (at least those can be suppressed).

This is perfectly doable with Xcode, which supports this use case via build settings on a per-target level. It is possible to have an application that supports iOS 8.0 and up which bundles extensions that support 9.0 or 10.0 and up.

I can work around this in the short-term by setting `--ios_minimum_os` to 10.0, but it would be nice to have the granularity.

@c-parsons?

**Comment by sergiocampama** [comment]
This should be obsolete with the new iOS rules that require minimum os versions for each of the targets.
