### ISSUE TITLE
Bazel binary installer contains empty file

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#2662]
$ unzip -l bazel-0.4.4-installer-linux-x86_64.sh
Archive:  bazel-0.4.4-installer-linux-x86_64.sh
  Length      Date    Time    Name
---------  ---------- -----   ----
     2714  1980-01-01 01:00   bazel
    84737  1980-01-01 01:00   bazel-complete.bash
146761588  1980-01-01 01:00   bazel-real
        0  1980-01-01 01:00   tools/
        0  1980-01-01 01:00   tools/defaults/
        0  1980-01-01 01:00   tools/defaults/BUILD
---------                     -------
146849039                     6 files

**Comment by damienmg** [comment]
wow also in 0.4.5rc

**Comment by damienmg** [comment]
https://github.com/bazelbuild/bazel/blob/master/scripts/packages/BUILD#L83 this is because of this line that wasn't removed when we packaged the bazel_tools repository inside bazel

**Comment by harmank** [comment]
@damienmg Should I just remove line #83 and open a pr ?

**Comment by royalharsh** [comment]
@harmank, I just sent a pull request for this issue.

**Comment by aljabrr** [comment]
@royalharsh @harmank Has the PR been merged? I could love totake on it.

**Comment by royalharsh** [comment]
PR hasn't been merged yet.
