### ISSUE TITLE
Output file availability - transitive dependency not building?

### ISSUE THREAD

**Issue by KGan** [bazelbuild/bazel#2665]
Edit: reformatting for the sections required:

### System/Bazel info

0.4.5-homebrew
Mac os Sierra

### Description of problem

Hey, pretty new to bazel. I am trying to get an electron build up and running through getting these two libraries, [rules_closure](https://github.com/bazelbuild/rules_closure) and [rules_node](https://github.com/pubref/rules_node) , to work with one another (let me know if this is better suited to ask either one of them instead). Basically, I want to create a closure_js_binary bundled js, and have it, an electron main file and a run-script all packaged together.

Bazel 0.4.5, rules_closure 0.2.3, rules_node @ my local fork's master, with a small tweak I added to build a transitive_data depset and make sure they end up in the runfiles.

Here's a quick excerpt from  the BUILD file I'm writing, will list what happens below:
```
closure_js_binary(
  name = "main.bundle",
  deps = ["..."],
)

filegroup(
 name = "html"
 srcs = ['a.html']
)

node_library(
  name = 'electron_main_app',
  main = "electron_main.js",
  srcs = ["electron_main.js"],
  data = [
     ":html", ":main.bundle"
  ]
)

// a node app that will start electron
node_binary(
  name = "start_electron_script",
  main = "start.js",
  deps = [":electron_main_app"],
  modules = ["@electron//:modules"]
)
```

There is a part of the node_library rule that copies files from its data dependencies into some staging area it creates [here](https://github.com/pubref/rules_node/blob/master/node/internal/node_library.bzl#L93). This part fails if I do a `bazel clean --expunge` and `bazel build ..:start_electron_script`, complaining that the file is not available (the binary bundle never builds). If I run `bazel build :electron_main_app` first and check the output directories it looks fine, and then the `bazel build :start_electron_script` works fine.

If I then run the js_binary build then upon finishing it will put itself into the runfiles folders if I run the start_electron script first.

### Find anything relevant online

no

**Comment by KGan** [comment]
Pinging this as it's still an issue I just haven't had it as a priority to figure out. How is it that a file necessary for building a rule A can be available when building it but not when building another rule B that depends on A...?

**Comment by kchodorow** [comment]
Sorry about the delay!  

That sounds like a bug in the node_binary rule, it looks like it's not actually taking start.js as an input to its action (https://github.com/pubref/rules_node/blob/master/node/internal/node_library.bzl#L112).  Does adding it there help?

**Comment by KGan** [comment]
This worked, thanks very much! To clarify the small typo, it seems the node_library rule wasn't adding its data dependencies (the `main.bundle` file) to its actions.

I added the data dependencies to that action in node_library and it worked like a charm.

**Comment by kchodorow** [comment]
Great!  Glad it worked out.
