### ISSUE TITLE
Bazel 0.4.4 for Windows can produce partial/inscrutable warnings with templates

### ISSUE THREAD

**Issue by steven-johnson** [bazelbuild/bazel#2666]
(1) Write a templated function that, when instantiated, can give an modest warning, most commonly, implicit integer conversion

```
template<typename T> inline T foo(T a, T b) { return  (int64_t)(a + b); }
uint32_t a = 0, b = 1;
uint64_t c = foo(a, b);
```

(2) Compile it using Bazel 0.4.4 with --cpu=x64_windows_msvc and MSVC 2017

Expected: at default settings, MSVC would produce something like

```
warning C4244: 'return': conversion from 'int64_t' to 'uint32_t', possible loss of data
note: see reference to function template instantiation 'T foo<uint32_t>(T,T)' being compiled
        with
        [
            T=uint32_t
        ]
```

Actual: msvc_tools.RunBinary() tries to eliminate all the warnings, but only manages to eliminate the first line, so you end up with the baffling and confusing message:

```
note: see reference to function template instantiation 'T foo<uint32_t>(T,T)' being compiled
        with
        [
            T=uint32_t
        ]
```

**Comment by meteorcloudy** [comment]
Sorry for that, I'll fix this
