### ISSUE TITLE
external repo with objc_framework generates incorrect include path

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/bazel#2668]
### Description of the problem / feature request / question:

I am using bazel to pull in an `objc_framework()` from a external repo. The external repo has the following `BUILD` file:

```
objc_framework(
    name = "rtc",
    framework_imports = glob(["WebRTC.framework/**"]),
    visibility = ["//visibility:public"],
)
```

In my repo's `WORKSPACE` file, I add the extrernal repo:

```
http_archive(
    name = "[redacted]_webrtc_ios",
    sha256 = "...",
    url = "[redacted]/webrtc-58-1-ios.tar.gz",
)
```

Then, in my relevant target's `BUILD` file I add:

```
objc_library(
    name = "...",
    srcs = glob(["*.m"]),
    hdrs = glob(["*.h"]),
    visibility = ["//visibility:public"],
    deps = [
        ...
        "@[redacted]_webrtc_ios//:rtc",
    ],
)
```

During build the compile fails due to an incorrect path:

```
ahochhauss-MacBook-Pro:ll ahochhaus$ bazel build //...
INFO: Found 44 targets...
ERROR: missing input file '/Users/ahochhaus/Desktop/ll/external/[redacted]_webrtc_ios/WebRTC.framework/Headers/RTCSessionDescription.h'.
ERROR: /Users/ahochhaus/Desktop/ll/workout/ios/BUILD:5:1 1 input file(s) do not exist.
INFO: Elapsed time: 0.250s, Critical Path: 0.00s
```

The reason is because the path to `RTCSessionDescription.h` should be `/Users/ahochhaus/Desktop/ll/bazel-ll/external/[redacted]_webrtc_ios/WebRTC.framework/Headers/RTCSessionDescription.h`

```
ahochhauss-MacBook-Pro:ll ahochhaus$ ls /Users/ahochhaus/Desktop/ll/bazel-ll/external/[redacted]_webrtc_ios/WebRTC.framework/Headers/RTCSessionDescription.h
/Users/ahochhaus/Desktop/ll/bazel-ll/external/[redacted]_webrtc_ios/WebRTC.framework/Headers/RTCSessionDescription.h
```

instead of `/Users/ahochhaus/Desktop/ll/external/[redacted]_webrtc_ios/WebRTC.framework/Headers/RTCSessionDescription.h`:

```
ahochhauss-MacBook-Pro:ll ahochhaus$ ls /Users/ahochhaus/Desktop/ll/external/[redacted]_webrtc_ios/WebRTC.framework/Headers/RTCSessionDescription.h
ls: /Users/ahochhaus/Desktop/ll/external/[redacted]_webrtc_ios/WebRTC.framework/Headers/RTCSessionDescription.h: No such file or directory
```

Can `objc_framework()` be fixed to work with external repositories?

### Environment info
* Operating System: Darwin (macOS 10.12.3)
* Bazel version (output of `bazel info release`): release 0.4.4

**Comment by hochhaus** [comment]
Playing a bit more, I found that if I hand modify `[target].xcodeproj/project.pbxproj` to insert the missing directory (`bazel-ll`) the build works in XCode and the app runs in the XCode simulator.

I modified all of the `FRAMEWORK_SEARCH_PATHS` sections of the xml file. For example:

```xml
<key>FRAMEWORK_SEARCH_PATHS</key>
<array>
  <string>$(WORKSPACE_ROOT)/bazel-ll/external/[redacted]_webrtc_ios</string>
  <string>$(SDKROOT)/Developer/Library/Frameworks</string>
  <string>$(PLATFORM_DIR)/Developer/Library/Frameworks</string>
</array>
```

**Comment by hochhaus** [comment]
@calpeyser  @c-parsons @sergiocampama - I see you are the major obcj contributors. Can you help me debug further?

**Comment by sergiocampama** [comment]
@kchodorow the path seems to be wrong for where it's trying to find the external WORKSPACE, wdyt?

**Comment by kchodorow** [comment]
Yeah, looks like a bug in how objc rules are handling external paths.

**Comment by meisterT** [comment]
@c-parsons is this still relevant?

**Comment by jmmv** [comment]
Considering obsolete. Also, given the dates of this bug, I'm assuming this was using the old Xcode project generation code (not Tulsi)... and things are probably different today.
