### ISSUE TITLE
Bazel client (Windows/MSVC) crashes in server mode

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2672]
The MSVC version (MSYS-less) bazel crashes if you run it in non-batch mode and the server isn't running.

The culprit is pretty complex and took days to debug. It consists of the following parts:

1. I narrowed down the problem to the Bazel client trying to connect to the non-running server, failing to do so, and trying to print an error. The printing code was segfaulting.

   The printing logic attempted to [translate the `WSAGetLastError()` result to a string](https://github.com/bazelbuild/bazel/blob/89f296f0d712e8a8ad2b545d72d00fbe63047fd8/third_party/grpc/src/core/iomgr/tcp_client_windows.c#L210). This was calling [`gpr_format_message`](https://github.com/bazelbuild/bazel/blob/89f296f0d712e8a8ad2b545d72d00fbe63047fd8/third_party/grpc/src/core/support/log_win32.c#L112) which crashed while calling [`gpr_tchar_to_char`](https://github.com/bazelbuild/bazel/blob/89f296f0d712e8a8ad2b545d72d00fbe63047fd8/third_party/grpc/src/core/support/log_win32.c#L121).  We built non-unicode, so [`gpr_tchar_to_char` is implemented here as just `gpr_strdup`](https://github.com/bazelbuild/bazel/blob/89f296f0d712e8a8ad2b545d72d00fbe63047fd8/third_party/grpc/src/core/support/string_win32.c#L104), which itself is [implemented here](https://github.com/bazelbuild/bazel/blob/89f296f0d712e8a8ad2b545d72d00fbe63047fd8/third_party/grpc/src/core/support/string.c#L45).

   On the surface, everything looks fine: `gpr_strdup` returns `char*`, `gpr_tchar_to_char` returns that, and `gpr_format_message` stores that also in a `char*`, however the two pointers -- [`dst` on the return site](https://github.com/bazelbuild/bazel/blob/89f296f0d712e8a8ad2b545d72d00fbe63047fd8/third_party/grpc/src/core/support/string.c#L58), [`message` on the call site](https://github.com/bazelbuild/bazel/blob/89f296f0d712e8a8ad2b545d72d00fbe63047fd8/third_party/grpc/src/core/support/log_win32.c#L121) -- were consistently different.

   Turns out `gpr_strdup` was not declared before using it, and thanks to the ancient C feature of implicit function declaration (which can be turned into an error with `/WE4013`), the compiler implicitly declared it with `int` return type, which is apparently 4 bytes long on MSVC, while `char*` is of course 8 bytes long.  So the upper 32 bits of [`message`](https://github.com/bazelbuild/bazel/blob/89f296f0d712e8a8ad2b545d72d00fbe63047fd8/third_party/grpc/src/core/support/log_win32.c#L121) were corrupt.

   So due to a missing header inclusion, we ended up implicitly declaring a function with the wrong yet compatible signature, causing a corruption of the return value which is a pointer, causing a segfault down the line.

2. We had no chance of catching it because the BUILD file of gRPC contains `-Wnoimplicit-function-declaration` line. Once @lberki [patched this](https://github.com/bazelbuild/bazel/blob/89f296f0d712e8a8ad2b545d72d00fbe63047fd8/third_party/grpc/grpc.patch) in d699a28f486efba71da9df0e278edd7193b2e465, but we overwrote that in the next commit 8b3b918ebd55911a3102f5ea6da60906fa63c866 and never noticed. All was working fine because gcc's int is 8 bytes long.

3. And even if we did notice, the MSVC wrapper script [ignores that warning](https://github.com/bazelbuild/bazel/blob/89f296f0d712e8a8ad2b545d72d00fbe63047fd8/tools/cpp/wrapper/bin/pydir/msvc_cl.py#L55).

**Comment by lberki** [comment]
Woahdude. That was one hell of a bug. Nice debugging! :)
