### ISSUE TITLE
tools/bazel doesn't handle nested WORKSPACE files

### ISSUE THREAD

**Issue by AustinSchuh** [bazelbuild/bazel#2681]
I have a repository with the following files:

//:WORKSPACE
//third_party/protobuf:WORKSPACE
//tools:bazel

When I call bazel from // or //third_party or anywhere but //third_party/protobuf, //tools:bazel gets called called.  If I call it from //third_party/protobuf/, it calls my host bazel.  The end result is that I get a different bazel version if I build third_party/protobuf as //third_party/protobuf/... outside the protobuf folder, or build ... inside the protobuf folder.  This was very surprising when I ran across it.

What is the right answer here?

**Comment by meteorcloudy** [comment]
@kchodorow Can you help with this? Thanks

**Comment by buchgr** [comment]
Ping @meteorcloudy @kchodorow

**Comment by kchodorow** [comment]
Sorry about the delay. 

`//third_party/protobuf` is a separate workspace, so it should only be built from the `//:WORKSPACE` directory as `@protobuf//whatever` (building `//third_party/protobuf/whatever` might work now, but it's weird and we might lock that down in the future). If you `cd third_party/protobuf`, then you are in a completely separate workspace as far as Bazel's concerned and can build relative to the protobuf repository (`//whatever`).

**Comment by dslomov** [comment]
Looks like there is no bug here
