### ISSUE TITLE
Bazel cannot use its own `java_proto_library` rules

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/bazel#2682]
The documentation seems to hint that using [`proto_library`](https://bazel.build/versions/master/docs/be/protocol-buffer.html#proto_library) and [`java_proto_library`](https://bazel.build/versions/master/docs/be/java.html#java_proto_library) seems to be the idiomatic way of building java proto libraries. (There is also a documentation issue here, as there is no indication about the difference between `java_proto_library` and `java_lite_proto_library`.) Trying to [use `java_proto_library`](https://github.com/aehlig/bazel/commit/ca1a2f576b45005bcc2601538f44d78372b7a788)  for the build_event_stream  protos however results in an error.
```
~/Projects/Bazel/bazel/src/main/java/com/google/devtools/build/lib/buildeventstream/proto>bazel build --verbose_failures :build_event_stream_java_proto
INFO: Analysed target //src/main/java/com/google/devtools/build/lib/buildeventstream/proto:build_event_stream_java_proto (0 packages loaded).
INFO: Found 1 target...
ERROR: /usr/home/aehlig/Projects/Bazel/bazel/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/BUILD:8:1: Generating Java (Immutable) proto_library //src/main/java/com/google/devtools/build/lib/buildeventstream/proto:build_event_stream_proto failed: protoc failed: error executing command 
  (cd /usr/home/aehlig/.cache/bazel/_bazel_aehlig/8dcdc1ce9be2430b2f4f1b52f2ec05e8/execroot/bazel && \
  exec env - \
    PATH=/home/aehlig/bin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/home/aehlig/bin:/sbin:/usr/sbin \
    TMPDIR=/memfs/tmp \
  bazel-out/host/bin/external/com_google_protobuf/protoc '--java_out=shared,immutable:bazel-out/local_freebsd-fastbuild/genfiles/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream_proto-speed-src.jar' '-Isrc/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto=src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto' '--direct_dependencies=src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto' '--direct_dependencies_violation_msg=%s is imported, but //src/main/java/com/google/devtools/build/lib/buildeventstream/proto:build_event_stream_proto doesn'\''t directly depend on a proto_library that '\''srcs'\'' it.' src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1
Unknown flag: --direct_dependencies
Target //src/main/java/com/google/devtools/build/lib/buildeventstream/proto:build_event_stream_java_proto failed to build
INFO: Elapsed time: 0.167s, Critical Path: 0.01s
FAILED: Build did NOT complete successfully
~/Projects/Bazel/bazel/src/main/java/com/google/devtools/build/lib/buildeventstream/proto>
```
This is true, both for bazel 0.4.5rc7 as well as bazel from head. The problem seems to be that the rule passes the option `--direct_dependencies` to the `protoc` invocation, despite the protoc shipped with bazel not knowing that option. This probably blocked on #2584, but still is a surprising experience.

There is another documentation issue with this rule. Trying to use it naively on a fresh repository results in the following error.
```
$ bazel build :simple_java_proto
ERROR: /crypto/general/aehlig/tmp/work/proto/BUILD:1:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf//:protoc', but this target could not be found because of: no such package '@com_google_protobuf//': error loading package 'external': The repository named 'com_google_protobuf' could not be resolved
ERROR: Analysis of target '//:simple_java_proto' failed; build aborted
INFO: Elapsed time: 0.134s
FAILED: Build did NOT complete successfully (0 packages loaded)
$
```
This could be documented in the rule, together with instructions on how to use it with `protoc` from host (as found in `PATH`). Note that it is common practice to use tools from the host system (and bazel happily does so for `cc` and `javac`), so doing the same for `protoc` should be easy.

**Comment by forumulator** [comment]
@aehlig About the main issue, I think the upgrading Bazel to include protobuf 3.2.0 is blocked on [this](https://github.com/google/protobuf/pull/2848) pull request which fixes the freeBSD build. 

As for the `java_proto_library` and `java_lite_proto_library`,  the latter also includes the transitive Proguard dependencies of it's deps. I'd love to help documenting this issue, but I'm a little confused as to how proguard spec files are used for proto_lib rules; as far as I can tell, Bazel native rules only use proguard specs for android_binary and android_library rules.

**Comment by jin** [comment]
I think we can close this as obsolete, since these are referring to very old versions of Bazel and Protoc. There's also significant development in the Proto rules in bazelbuild/rules_proto. Please ping this issue or reopen if you're still seeing the reported problem.
