### ISSUE TITLE
Coverage no longer creating coverage.dat

### ISSUE THREAD

**Issue by tomwickert** [bazelbuild/bazel#2685]
### Description of the problem / feature request / question:

I'm running the following command: bazel coverage ... 

In 0.4.2rc2, this worked well and produced coverage.dat files as expected. In the latest version 0.4.5rc7, this does not work. The coverage.dat files are not being produced. I receive the following errors:

ERROR: /home/tomw/dev/build_test_bazel/cpp/utils/policies/BUILD:19:1: output 'cpp/utils/policies/utils_policies-unittest/coverage.dat' was not created.
ERROR: /home/tomw/dev/build_test_bazel/cpp/utils/policies/BUILD:19:1: not all outputs were created or valid.

This also failed to work on 0.4.4 and 0.4.5rc2. 

### Environment info
* Operating System:
CentOS release 6.5 (Final)

* Bazel version (output of `bazel info release`):
release 0.4.4-2017-03-15 (@336f477)

### Anything else, information or logs or outputs that would be helpful?

[tomw@x cpp]$ /home/tomw/bazel/bazel coverage ...
INFO: Using default value for --instrumentation_filter: "//cpp".
INFO: Override the above default with --instrumentation_filter
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 8 targets and 6 test targets...
ERROR: /home/tomw/dev/build_test_bazel/cpp/utils/policies/BUILD:19:1: output 'cpp/utils/policies/utils_policies-unittest/coverage.dat' was not created.
ERROR: /home/tomw/dev/build_test_bazel/cpp/utils/policies/BUILD:19:1: not all outputs were created or valid.
INFO: Elapsed time: 4.455s, Critical Path: 2.85s
//cpp/utils/policies:utils_policies-unittest                             PASSED in 0.0s
//cpp/common:common-unittest                                          NO STATUS
//cpp/directory:directory-unittest                                    NO STATUS
//cpp/packet:packet-unittest                                          NO STATUS
//cpp/threading:threading-unittest                                    NO STATUS
//cpp/utils/detail:utils_detail-unittest                              NO STATUS

Executed 1 out of 6 tests: 1 test passes and 5 were skipped.

**Comment by meteorcloudy** [comment]
@hermione521 Any idea on this?

**Comment by ben-ward-hp** [comment]
Any progress on this regression?

**Comment by dslomov** [comment]
@lberki ping?

**Comment by lberki** [comment]
This is unsupported functionality, so I'd hesitate to call this a regression.

That said, I'll lift the old-style coverage collection code from `tools/coverage/collect-coverage.sh` and add it here.
