### ISSUE TITLE
Failed to compile by "bazel //src:bazel".

### ISSUE THREAD

**Issue by renning22** [bazelbuild/bazel#2688]
I tried to clone and build bazel from head by using different dist binary versions 0.4.3, 0.4,4, 0.4.5rc7. But got the same error message "ccache: failed to create /nonexistent/.ccache (No such file or directory)" essentially.

Full: 

ERROR: /usr/local/google/home/ningr/Downloads/bazel/src/main/tools/BUILD:20:1: C++ compilation of rule '//src/main/tools:build-runfiles' failed: linux-sandbox failed: error executing command 
  (exec env - \
    PATH=/usr/local/google/home/ningr/bin:/usr/local:/usr/lib/jvm/java-8-oracle/bin:/usr/local/google/opt/NVPACK/cuda-6.0-7ea902a/bin:/usr/local/google/opt/cmake/bin:/usr/lib/ccache:/usr/local/google/opt/llvm-3.7.0-iwyu/bin:/usr/share/clang/scan-build:/usr/local/google/opt/android-sdk-24.4.1/android-sdk-linux/tools:/usr/local/google/opt/android-sdk-24.4.1/android-sdk-linux/platform-tools:/usr/local/google/opt/android-ndk-linux-r13b:/usr/local/google/opt/google-cloud-sdk/bin:/usr/lib/google-golang/bin:/usr/local/buildtools/java/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/google/home/ningr/bin \
  /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/execroot/bazel/_bin/linux-sandbox @/usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/linux-sandbox.params -- /usr/lib/ccache/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/lib/ccache -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/local-fastbuild/bin/src/main/tools/_objs/build-runfiles/src/main/tools/build-runfiles.pic.d '-frandom-seed=bazel-out/local-fastbuild/bin/src/main/tools/_objs/build-runfiles/src/main/tools/build-runfiles.pic.o' -fPIC -iquote . -iquote bazel-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c src/main/tools/build-runfiles.cc -o bazel-out/local-fastbuild/bin/src/main/tools/_objs/build-runfiles/src/main/tools/build-runfiles.pic.o).
src/main/tools/linux-sandbox.cc:186: linux-sandbox-pid1 has PID 66756
src/main/tools/linux-sandbox-pid1.cc:233: tmpfs: /tmp
src/main/tools/linux-sandbox-pid1.cc:243: working dir: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/execroot/bazel
src/main/tools/linux-sandbox-pid1.cc:244: sandbox root: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp
src/main/tools/linux-sandbox-pid1.cc:173: CreateTarget(usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/execroot/bazel, true)
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/dev
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/dev/pts
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/run
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/run/lock
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/run/shm
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/run/user
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/run/user/269062/gvfs
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/run/rpc_pipefs
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/sys
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/sys/kernel/security
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/sys/fs/cgroup
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/sys/fs/cgroup/systemd
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/sys/fs/fuse/connections
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/sys/kernel/debug
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/sys/firmware/efi/efivars
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/sys/fs/pstore
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/proc
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/proc/sys/fs/binfmt_misc
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/boot
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/boot/efi
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/usr/local/google
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/auto
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/home
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/home/build
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/google/src
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/google/data
src/main/tools/linux-sandbox-pid1.cc:379: remount ro: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/google/obj
src/main/tools/linux-sandbox-pid1.cc:379: remount rw: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/tmp/usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/afba6a274fe634c48bbab12ffdf02438/bazel-sandbox/3b51cbfd-d68f-4012-a1d6-5758c12c07b5-2/execroot/bazel
src/main/tools/linux-sandbox-pid1.cc:491: sigaction(32, &sa, NULL) failed
src/main/tools/linux-sandbox-pid1.cc:491: sigaction(33, &sa, NULL) failed
ccache: failed to create /nonexistent/.ccache (No such file or directory)
src/main/tools/linux-sandbox-pid1.cc:601: waitpid returned 2
src/main/tools/linux-sandbox-pid1.cc:621: child exited with code 1
src/main/tools/linux-sandbox.cc:226: child exited normally with exitcode 1
Use --strategy=CppCompile=standalone to disable sandboxing for the failing actions.
Target //src:bazel failed to build
INFO: Elapsed time: 0.383s, Critical Path: 0.11s

**Comment by meteorcloudy** [comment]
@philwo Looks like some problem with sandbox?

**Comment by philwo** [comment]
Hi @renning22! Thanks for checking out Bazel. :)

The issue is that we currently don't support ccache together with sandboxing. As a workaround, you can either disable sandboxing for C++ (by adding "build --strategy=CppCompile=standalone" to your ~/.bazelrc) or not use ccache on your system.

I will explain in more detail what's happening:

You're trying to use ccache, ccache is trying to create a ".ccache" directory in the home directory of the user, but because in the sandbox you're running as the user "nobody", this would be the home directory of the user "nobody". This is usually set to "/nonexistent", which doesn't exist, so this error happens.

But even if this would work, ccache would then fail to write to that directory, because everything except the working directory of the command is read-only inside the sandbox. (We do this to prevent tools and especially tests from accidentally writing to arbitrary locations on your computer.)

Supporting this use case would mean we need to:
- Disable the switch to "nobody" user by default in the sandbox.
- Add a flag --sandbox_fake_user (similar to --sandbox_fake_hostname) that re-enables the user switch for those users who actually want that.
- Add a flag --sandbox_allow_path (similar to --sandbox_block_path) that mounts a certain path as read-write. You'd then need to pass this flag like: --sandbox_allow_path=$HOME/.ccache

This actually sounds pretty reasonable. I'll consider adding this.

**Comment by renning22** [comment]
Thanks Philipp for the complete explaination,

I tried that by adding "--strategy=CppCompile=standalone" is not enough to get rid of the error, but also need "--strategy=CppLink=standalone".

This command works for me!
bazel build --strategy=CppCompile=standalone --strategy=CppLink=standalone src:bazel
