### ISSUE TITLE
Make javac_opts of java_common.compile expandable

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#2689]
The `javac_opts` argument of `java_common.compile` doesn't accept expandable locations right now. Something like `$(GENDIR)/$(location :stub)` should be supported (the same as is supported in `javacopts` of `java_library`).

**Comment by lberki** [comment]
We have the `ctx.expand_location()` function which does the exact same thing. You can call it from anywhere you can call `java_common.compile()`.
