### ISSUE TITLE
Support for vendoring in nested Bazel workspaces

### ISSUE THREAD

**Issue by zombiezen** [bazelbuild/bazel#269]
@lberki Based on [this thread](https://groups.google.com/d/topic/bazel-discuss/tNz9HBe5lvY/discussion), there should be a way to nest Bazel or other roots with `WORKSPACE` files in one version-controlled repository.  Current support is lacking because `local_workspace` requires an absolute path, not one that is relative to the workspace.

**Comment by saileshmittal** [comment]
@kchodorow This change might be relevant to this issue.
https://bazel-review.googlesource.com/#/c/2601/

**Comment by lberki** [comment]
We have a syntax: `path = __workspace_dir__ + "../foo/bar"` which should allow you to reference directories relative to the workspace. Arguably, it should just be a relative path, but the `__workspace_dir__` thing would work here, wouldn't it?

**Comment by kchodorow** [comment]
This is now allowed.
