### ISSUE TITLE
genrule cannot use //external:mytool as a tool dependency

### ISSUE THREAD

**Issue by jcanizales** [bazelbuild/bazel#270]
I've got a Skylark macro defined, that expands into a `genrule`. I want to make the macro available to the users of my library, so I put it in a `.bzl` file in my repository. The genrule uses a tool that's distributed in my repo. The tool has a corresponding `cc_binary` target in my repo's `BUILD` file.

Because macros are expanded in place, the genrule it creates can't declare the tool using a relative path (the point of expansion will not be where my `.bzl` file is). It shouldn't declare it with an absolute path either, because that forces the user of my library to place my repo as a submodule in the specific path I decided:
```python
tools = ["//third_party/grpc:grpc_objective_c_plugin"],
```
So I tried:
```python
tools = ["//external:grpc_objective_c_plugin"],
```
(although asking the user to add a `bind` entry to their `WORKSPACE` file so that my stuff can work with itself is also a bad experience).

But that failed with:

> in cmd attribute of genrule rule //protos:auth_sample_codegen: label '//external:grpc_protoc_plugin_objc' in $(location) expression is not a declared prerequisite of this rule.

Maybe here: https://github.com/google/bazel/blob/master/src/main/java/com/google/devtools/build/lib/analysis/LocationExpander.java#L267 it can't tell the label represents an executable?

Is there a way I can make my genrule aware of the tool that's distributed with it? Trying to move my `cc_binary` from my `BUILD` file into my `.bzl` file (as `native.cc_binary`) didn't work either:

> The native module cannot be accessed from here. Wrap the function in a macro and call it from a BUILD file.

Maybe defining a Skylark rule instead of a macro can help me?

**Comment by jcanizales** [comment]
For reference, @mzhaom, facing the same problem, apparently worked around it by listing the tools in the `srcs` of the `genrule`: https://github.com/mzhaom/trunk/blob/master/third_party/grpc/grpc_proto.bzl#L45.

Still, ideally we won't have to tell our users to add that binding to their `WORKSPACE` file.

**Comment by jcanizales** [comment]
(The problem of how to refer to stuff that's in the same directory as the `.bzl` file applies to libraries too: My macro expansion creates an `objc_library` too, and has it depend on a runtime `objc_library` in my repo. Right now the only way I've found to do it is using `//external`, meaning I have to tell my users to add a `WORKSPACE` binding to teach my Skylark macro where to find its own stuff.)

**Comment by kchodorow** [comment]
I'm thinking it would make sense to add a function to the Skylark language that would allow .bzl files to include a WORKSPACE file that could be shipped (maybe something like workspace("relative/path/to/ws/file").  @laurentlb, does that sound okay to you?  (I can implement it.)

**Comment by damienmg** [comment]
What do you mean?

**Comment by kchodorow** [comment]
When you write a bazel rule (e.g., appengine.bzl) you'd have a line that said workspace("appengine.WORKSPACE") that would add that WORKSPACE file to the WS files to be used.

**Comment by damienmg** [comment]
I would prefer we think and implement a sound approach in which you use
remote repository that ship their own WORKSPACE file (transitive workspace
file) than adding yet another hack that would permit to create a WORKSPACE
file whereever you want in your workspace...

**Comment by jcanizales** [comment]
An alternative is to let a Skylark macro refer to targets defined in the same directory where the `.bzl` file is located, using `//internal:` or `//loaded-package:` or something like that.

**Comment by jcanizales** [comment]
Another alternative: Have a variable like `PACKAGE_NAME` for the package where the `.bzl` file is located. Then constructing references to libraries and binaries defined in that package is trivial.

**Comment by damienmg** [comment]
+Laurent Le Brun <laurentlb@google.com>

That's seems a reasonable approach to me, Laurent WDYT?

**Comment by laurentlb** [comment]
This is reasonable. It doesn't really fix the underlying bug, but it's a reasonable feature request.

**Comment by kayasoze** [comment]
I believe that listing a tool in srcs will break cross-compilation, so @mzhaom's workaround only works for native builds.

**Comment by jcanizales** [comment]
Thanks for the warning!

And sorry that I ended up mixing both things in this issue. There's on one hand the bug that `genrule` tools can't be `//external:`, with the semi-workaround of using `srcs`. And on the other hand the feature request to let `.bzl` files refer to targets defined in their same package, which is a much better solution to my problem.

**Comment by kayasoze** [comment]
The former appears to be fixed as of https://bazel-review.googlesource.com/#/c/1750/.
