### ISSUE TITLE
Provide an rpm package for CentOS/RHEL/Fedora

### ISSUE THREAD

**Issue by Rikorose** [bazelbuild/bazel#2701]
Ideally the installation process would be 
```
sudo dnf install bazel
```
or 
```
sudo yum install bazel
```
Alternatively an standalone rpm package or an external repository for Fedora would be great.

**Comment by damienmg** [comment]
FTR the package already exist we need to build it as part of our release pipeline now.

**Comment by katre** [comment]
There's three phases to this:

1) Build an RPM of Bazel - this is done (bazel build //scripts/packages/fedora:bazel)
2) Release the RPM with Bazel releases
3) Get Bazel into Fedora/RH/CentOS's package repository - haven't even started, we'll need to learn more about what they require from packages, but I suspect the current binary (which has a number of tools packed into it) will be a problem.

**Comment by rhofour** [comment]
Is there anything blocking 2? As a Fedora user that alone would make my life a bit easier.

**Comment by sjenning** [comment]
I've created a RPM for Fedora and opened a package review

https://bugzilla.redhat.com/show_bug.cgi?id=1470842

**Comment by katre** [comment]
Thanks! Hopefully we can get a RPM-based worker in our jenkins setup shortly for veirifcation.

**Comment by katre** [comment]
You may want to copy the install locations for bazel.bazelrc and the bash completion script, from https://github.com/bazelbuild/bazel/blob/5d453d93499e328d4c0ea9b8f0c6ff4bbba08b54/scripts/packages/fedora/bazel.spec

Also, I think releases.bazel.build will have faster downloads than github, but I'm not sure what the URL syntax is. @damienmg ?

**Comment by damienmg** [comment]
https://releases.bazel.build/<version>/release/index.html is the index,
e.g.: https://releases.bazel.build/0.5.2/release

**Comment by sjenning** [comment]
@katre ah, didn't know about the in-tree spec file.  Thanks for the heads-up :+1:  I'll update my spec file.

**Comment by katre** [comment]
@sjenning I added it to make a development package, but yours looks good for a releasable version. Thanks for working on it!

**Comment by sjenning** [comment]
@katre what is `bazel-real`?

**Comment by katre** [comment]
```
$ file /usr/bin/bazel /usr/bin/bazel-real
/usr/bin/bazel:      Bourne-Again shell script, ASCII text executable
/usr/bin/bazel-real: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2
```

The distributed `bazel` file is actually a shell script that checks whether there is a binary at tools/bazel, based on the current WORKSPACE. If that's not found, it executes `bazel-real`, which is the actual compiled binary.

**Comment by sdake** [comment]
@sjenning I am a provenpackager in Fedora.  Bundled dependencies are not permitted in Fedora/CentOS repositories and the lag time to unbundle the dependencies will be pretty high.  In the meantime, I've created a COPR and am shortly submitting a pull request to document using it for Bazel as well as a separate set of instructions for building from source.

I'm in need of this as a result of  https://github.com/istio/issues/issues/56

**Comment by sjenning** [comment]
@sdake that sounds like the only way forward at the moment, sadly.  I know @vbatts already has a COPR repo for bazel that includes EPEL https://copr.fedorainfracloud.org/coprs/vbatts/bazel/

**Comment by sdake** [comment]
@sjenning I did notice after I submitted https://github.com/bazelbuild/bazel/pull/3779 with a COPR build + documentation I did about a week ago, I was duplicating @vbatts work in https://github.com/bazelbuild/bazel/pull/3721, so I've asked @vbatts to include 0.5.3-1 for EPEL which at present is the recommended version of bazel for istio.  Version 0.5.3 is currently absent from @vbatt's COPR for EPEL.

I would encourage you to continue work on unbundling the dependencies for Fedora/EPEL so these can go into the main distribution of EPEL.  I'll be happy to provide reviews of the unbundled packages if you need.  I just noticed the reviewer who took on your initial review was not satisfied with the bundled dependencies.

**Comment by vbatts** [comment]
@sdake https://copr.fedorainfracloud.org/coprs/vbatts/bazel/build/606023/ if you'll double check it.

**Comment by sdake** [comment]
@vbatts 
```
[sdake@falkor-04 ~]$ sudo curl -o /etc/yum.repos.d/bazel.repo https://copr.fedorainfracloud.org/coprs/vbatts/bazel/repo/epel-7/vbatts-bazel-epel-7.repo
(correct output)
[sdake@falkor-04 ~]$ sudo yum install bazel-0.5.3
(correct output)
[sdake@falkor-04 istio.io]$ rpm -ql bazel
/usr/bin/bazel
/usr/share/bash-completion/completions/bazel
[sdake@falkor-04 istio.io]$ bazel help startup_options
Extracting Bazel installation...
 [bazel release 0.5.3- (@non-git)]
[sdake@falkor-04 mixer]$ make
INFO: Elapsed time: 166.209s, Critical Path: 59.34s
[sdake@falkor-04 mixer]$ cd ../pilot
[sdake@falkor-04 pilot]$ make
+ go install ./...
[sdake@falkor-04 pilot]$ 
```

LGTM

@vbatts - may I suggest adding a license file to the COPR rpm?  Although not strictly required from a COPR POV, it is helpful to understand what licenses are used in installed packages.

TIA!
-steve

**Comment by excavador** [comment]
I need it!

**Comment by vbatts** [comment]
It exists!

**Comment by excavador** [comment]
Thank you!
Yes, found description https://docs.bazel.build/versions/master/install-redhat.html
Why this ticket still opem?

**Comment by vbatts** [comment]
good question. I don't have perms to close it.
