### ISSUE TITLE
Code Quality Enhancement If-else instead of multiple if

### ISSUE THREAD

**Issue by nmpatsal** [bazelbuild/bazel#2702]
Dear Bazel Team,
I was reading the code to check the quality and I would like to suggest an enhancement, correct me please if I am wrong. We could use if-else statement instead of multiple if statements as they are used in options/Converter.java so the code would be more readable and maintainable for the future.

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/common/options/Converters.java
### Multiple if statements instead of if-else:
```
  public static class BooleanConverter implements Converter<Boolean> {
    @Override
    public Boolean convert(String input) throws OptionsParsingException {
      if (input == null) {
        return false;
      }
      input = input.toLowerCase();
      if (input.equals("true") || input.equals("1") || input.equals("yes") ||
          input.equals("t") || input.equals("y")) {
        return true;
      }
      if (input.equals("false") || input.equals("0") || input.equals("no") ||
          input.equals("f") || input.equals("n")) {
        return false;
      }
      throw new OptionsParsingException("'" + input + "' is not a boolean");
    }
```
_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### If possible, provide a minimal example to reproduce the problem:
```
  public static class BooleanConverter implements Converter<Boolean> {
    @Override
    public Boolean convert(String input) throws OptionsParsingException {
      input = input.toLowerCase();
      if (input == null) {
        return false;
      } else if (input.equals("true") || input.equals("1") || input.equals("yes") ||
          input.equals("t") || input.equals("y")) {
        return true;
      } else if (input.equals("false") || input.equals("0") || input.equals("no") ||
          input.equals("f") || input.equals("n")) {
        return false;
      } else {
       return false;
      }
      throw new OptionsParsingException("'" + input + "' is not a boolean");
    }
```

### Environment info
* Operating System: Windows 

* Bazel version (output of `bazel info release`): I read it online so I do not install any bazel version

### Anything else, information or logs or outputs that would be helpful?
No

**Comment by jin** [comment]
In your example, if `input` is `null`, calling `toLowerCase()` on it will cause a NullPointerException.

The conditional logic will also end in the `else` block, therefore never reaching the throwing of `OptionsParsingException`, which the original code is intended to do if the input doesn't match any of the specified conditions.

**Comment by nmpatsal** [comment]
Ok if I add the `OptionsParsingException` in the else condition does it change? 
If `toLowerCase()` is over if condition or under it, it will run anyway, am I wrong?

**Comment by hermione521** [comment]
Hi, we follow the code style to avoid multiple else statement (and also nested code blocks). It's clearer and less error-prone. Sorry I couldn't find a link now.
