### ISSUE TITLE
Randomly crashes with deletion of ~/.cache helping the problem

### ISSUE THREAD

**Issue by yurivict** [bazelbuild/bazel#2706]
On FreeBSD 11 bazel-0.4.4 randomly crashes while building tensorflow. It works immediately after deleting /root/.cache, and crashes during subsequent runs.

It looks like cache gets into the invalid state that causes crashes.

**Comment by hermione521** [comment]
Hi, the latest release is 0.4.5. Did you try if it works?
Also @aehlig for FreeBSD

**Comment by yurivict** [comment]
This is for 0.4.5,

**Comment by jin** [comment]
Hi, please try this with a later Bazel version (0.18.1, 0.19) and create a new issue if this problem still persists.
