### ISSUE TITLE
Windows: Bazel 0.4.5 has a regression in python stub template

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2708]
http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=latest,PLATFORM_NAME=windows-x86_64/651/console

```
ERROR: C:/jenkins/workspace/bazel-tests/bazel_version/latest/platform_name/windows-x86_64/BUILD:54:1: Couldn't build file bazel-srcs.tar: error executing shell command: 'bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/build_tar --flagfile=bazel-out/vc_14_0_x64-fastbuild/bin/bazel-srcs.args' failed: bash.exe failed: error executing command 
  cd C:/bazel_ci/temp/_bazel_system/bop-op4a/execroot/windows-x86_64
  SET PATH=c:\tools\msys64\usr\bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\Google\Compute Engine\sysprep\;C:\Program Files\Google\Compute Engine\metadata_scripts\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\ProgramData\chocolatey\bin;;;C:\ProgramData\chocolatey\bin;;c:\python_27_amd64\files;C:\Program Files\Java\jdk1.8.0_121\bin;;c:\tools\msys64\usr\bin
    SET TMPDIR=c:\bazel_ci\temp
  C:/tools/msys64/usr/bin/bash.exe -c bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/build_tar --flagfile=bazel-out/vc_14_0_x64-fastbuild/bin/bazel-srcs.args: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Traceback (most recent call last):
  File "C:\python_27_amd64\files\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\python_27_amd64\files\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "bazel-out\host\bin\external\bazel_tools\tools\build_defs\pkg\build_tar\__main__.py", line 168, in <module>
  File "bazel-out\host\bin\external\bazel_tools\tools\build_defs\pkg\build_tar\__main__.py", line 115, in Main
  File "bazel-out\host\bin\external\bazel_tools\tools\build_defs\pkg\build_tar\__main__.py", line 98, in CreateModuleSpace
  File "C:\python_27_amd64\files\lib\zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: '\\\\?\\bazel-out\\host\\bin\\external\\bazel_tools\\tools\\build_defs\\pkg\\build_tar'
```

This happens when build `bazel_bootstrap_distfile_test` on Windows.

The bug shouldn't happen with python2 due to 95dac7050d0d7f0cd2a4c7fad1859daceed556af, but unfortunately it's not cherry-picked into 0.4.5. And even with 95dac7050d0d7f0cd2a4c7fad1859daceed556af, it's still broken with python3, See https://github.com/tensorflow/tensorflow/issues/8482 (TensorFlow GPU build with Bazel is broken, we don't have test for this at all, neither TF CI nor Bazel CI)

I'm responsible for this because I changed the CI configuration after switching MSVC toolchain as default so that the release candidates were actually never tested on CI due to this error:
```
ERROR: No toolchain found for cpu 'x64_windows_msys'. Valid cpus are: [
  x64_windows,
  armeabi-v7a,
  x64_windows_msvc,
  s390x,
  ios_x86_64,
].
```
Terribly sorry for this, I'll fix the bug immediately and try to add tests for python3. But I wonder if we should have a fix release for this or wait until 0.5?

//cc @damienmg @dslomov @laszlocsomor

**Comment by damienmg** [comment]
Impact?

**Comment by meteorcloudy** [comment]
@damienmg 
1. bazel_bootstrap_distfile_test will keep failing on Window
2. py_binary built by 0.4.5 is not runnable with python2 on Windows
3. TensorFlow GPU build on Windows is broken (but not many people are using it, probably)

**Comment by damienmg** [comment]
Is it fixed at head? Why haven't we caught it on our test suite?

**Comment by meteorcloudy** [comment]
Yes, it is fixed at HEAD by 95dac70, but only for python2. python3 is still broken we don't have tests for python3.

**Comment by damienmg** [comment]
Ok, in which case I recommend we deactivate the test for Windows until it
is fixed and work on good testing for the feature and fixing the py3 case.

Track all that work on that issue and block 0.5 on it.

**Comment by meteorcloudy** [comment]
OK, Will do it, thanks!
