### ISSUE TITLE
Assigning to a list element fails with cryptic error

### ISSUE THREAD

**Issue by jcanizales** [bazelbuild/bazel#271]
I'm cool with list values being immutable, but the error message to discover it is cryptic. Trying `mylist[1] = 5` yields:

> unsupported operand type(s) for +: 'list' and 'dict'

And it'd be awesomest if Skylark automatically turned `mylist[i] = x` into `mylist = mylist[:i-1] + [x] + mylist[i+1:]`.

**Comment by damienmg** [comment]
Laurent: can you say wether should we make the list mutable or fix the message? (there is no way to CC people so I assigned you, feel free to unassign it).

**Comment by laurentlb** [comment]
The implementation of lists is going to change (current solution is very hacky), and we'll allow mutation in cases where it is thread-safe.

**Comment by dslomov** [comment]
lists are mutable and the error message is not cryptic anymore
