### ISSUE TITLE
bazel run of Tarball based images doesn't correctly load base.

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/bazel#2712]
### Description of the problem / feature request / question:

The incremental load logic doesn't load layers that aren't produced by `docker_build` into the Docker daemon cache, which breaks cases such as when folks check in a base image tarball, or download it in their workspace.

### If possible, provide a minimal example to reproduce the problem:

`bazel run` [this](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/docker/testdata/BUILD#L376) target.

### Environment info
* Operating System:

* Bazel version (output of `bazel info release`):

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

**Comment by mattmoor** [comment]
@damienmg Opening this to track, now that my test is in and released.

**Comment by damienmg** [comment]
Thanks Matt :)

**Comment by mattmoor** [comment]
This is fixed in `rules_docker`
