### ISSUE TITLE
Steps to evaluate model

### ISSUE THREAD

**Issue by drwael** [bazelbuild/bazel#2716]
I have installed Bazel,TensorFlow, NumPy, scikit-learn,Natural Language Toolkit (NLTK)and gensim.
then i downloaded: 
- skip_thoughts_uni_2017_02_02 and skip_thoughts_uni_2017_02_02.
- skip-thoughts GitHub repository 
- the CR (customer review) dataset 
then i executed the following commands:
CHECKPOINT_PATH="${HOME}/skip_thoughts/model/train"
VOCAB_FILE="${HOME}/skip_thoughts/exp_vocab/vocab.txt"
EMBEDDINGS_FILE="${HOME}/skip_thoughts/exp_vocab/embeddings.npy"
EVAL_DATA_DIR="${HOME}/skip_thoughts/eval_data"

when i executed the command : bazel build -c opt skip_thoughts/evaluate
i got the following error: The 'build' command is only supported from within a workspace.

i failed to follow the instructions in https://github.com/tensorflow/models/blob/master/skip_thoughts/README.md 

i want a detailed instructions to evaluate the models in   Ubuntu 16.04.2

thanks in advance

**Comment by hermione521** [comment]
The 'build' command is only supported from within a workspace. And the workspace is a directory with a file named `WORKSPACE`. You can run `bazel build` from any directory under workspace, for example [here](https://github.com/tensorflow/models/tree/master/skip_thoughts).

Thank you for using bazel! If you have any further question on a specific project (like tensorflow), please file an issue against the project. Thanks.
