### ISSUE TITLE
//src/test/shell/bazel:bazel_java_test is broken on CI with jdk7

### ISSUE THREAD

**Issue by hermione521** [bazelbuild/bazel#2717]
http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD-jdk7,PLATFORM_NAME=linux-x86_64/654/console

**Comment by cushon** [comment]
I think the issue is that `VanillaJavaBuilder` doesn't support `-sourcepath` yet: https://github.com/bazelbuild/bazel/blob/44c322b4e654930dfe8a7260843695289b9ecf39/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/VanillaJavaBuilder.java#L241
