### ISSUE TITLE
expand_location is missing example code

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#2719]
there is an example of https://bazel.build/versions/master/docs/skylark/lib/ctx.html#expand_location

but there is no live example (in tested .bzl code) by which I can verify how it is supposed to work:
 
  http://cs.bazel.build/search?q=r%3Abazel+expand_location&num=50

**Comment by laurentlb** [comment]
https://github.com/bazelbuild/examples/blob/e0ace801107f47b8343e354cf28d270d6e543f23/rules/runfiles/execute.bzl#L10
