### ISSUE TITLE
When is bazel going to be integrated into VS2017 for Mac, Eclipse, and Xcode for Mac?

### ISSUE THREAD

**Issue by shyamalschandra** [bazelbuild/bazel#2720]
When is bazel going to be integrated into VS2017 for Mac, Eclipse, and Xcode for Mac?

**Comment by hermione521** [comment]
Nice question for @steren ! Do we have a plan?

**Comment by shyamalschandra** [comment]
I just tried the Xcode and Eclipse plugins and it is not very clear by their documentation how to setup my bazel project.  Any ideas on a step-by-step instructions because there aren't any blogs or pages for tensorflow setup with bazel?

**Comment by steren** [comment]
The Xcode plugin is only to build iOS applications.
The Eclipse one is very experimental at the moment. 

The more mature plugin is the IntelliJ one: http://ij.bazel.build/docs/bazel-plugin.html

TensorFlow related questions should be asked to the TensorFlow team (either on Stackoverflow or on GitHub issue if something is missing, like build documentation)

**Comment by anton-matosov** [comment]
Are there any updates on the VS and Xcode plugins/generators?

**Comment by jin** [comment]
@anton-matosov there's a few now:

Visual Studio: https://github.com/tmandry/lavender
Visual Studio Code: https://github.com/dprogm/vscode-bazel-tools
XCode generator: https://github.com/pinterest/xchammer
XCode generator: https://github.com/bazelbuild/tulsi

**Comment by jin** [comment]
Closing this for now, as there now exist community projects for the mentioned IDEs.
