### ISSUE TITLE
multiple tests in bazel-tests failing on Windows

### ISSUE THREAD

**Issue by hermione521** [bazelbuild/bazel#2721]
http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-x86_64/656/console

culprit: https://github.com/bazelbuild/bazel/commit/dd142c93fd4939aaec30726f275644ca9446fea2

**Comment by philwo** [comment]
My guess is that this comes from me changing TEST_TMPDIR from an MSYS-style path to a Windows-forward-slashes-style PATH.

I will try to reproduce and fix it tomorrow on my Windows workstation.
