### ISSUE TITLE
Windows, msys-less: support other shells (cygwin, powershell)

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2725]
### Description of the problem / feature request / question:

The MSYS-less version should, by definition, work under other shells.

At https://github.com/bazelbuild/bazel/commit/c34320d27b5360e24c36b1bdca1d3081828a64fb it works under cmd.exe, Powershell 5.0.10586.672, MSYS2 20161025, and potentially other versions of these too, but these are the ones I tried.

It however doesn't work under Cygwin, especially if I do:
```
export BAZEL_SH=c:\\cygwin64\\bin\\bash.exe
```

Since the MSYS-less version should only require a valid BAZEL_SH for now (complete independence from MSYS is a bit further away), these scenarios should work.

**Comment by laszlocsomor** [comment]
Update: cygwin doesn't have `zip` installed and I haven't found it among the packages, and genrules need it (e.g. `//src:embedded_tools`). We should look for a `BAZEL_ZIP` envvar that specifies the path to a zip utility.

**Comment by laszlocsomor** [comment]
...or better yet, have a hermetic zip utility in `//third_party` and use that.

**Comment by davido** [comment]
> Update: cygwin doesn't have zip installed

Just define `zip` to be a Cygwin Bazel pre-requisite then? Here what we are requiring for LibreOffice cygwin based build tool chain on Windows: [1].

```
setup-x86_64.exe -P autoconf -P automake -P bison -P cabextract -P doxygen -P flex -P gcc-g++ ^
                -P git -P gnupg -P gperf -P make -P mintty ^
                -P nasm -P openssh -P openssl -P patch -P perl -P python -P python3 ^
                -P pkg-config -P rsync -P unzip -P vim -P wget -P zip -P perl-Archive-Zip
```

* [1] https://wiki.documentfoundation.org/Development/BuildingOnWindows#Install_Cygwin_Requirements

**Comment by laszlocsomor** [comment]
Neat! Thanks for the tip. I didn't find zip/unzip in the installer's package selector's search bar before, but the `-P <package>` approach works.

**Comment by laszlocsomor** [comment]
Thanks again @davido , now it works like a charm -- I can now build the previously failing genrule.

We still cannot build `//src:bazel.exe` because `//src/main/native:windows_jni` fails but we're now further than before having `zip` installed.

```
laszlocsomor@laszlocsomor0-w /cygdrive/c/work/bazel
$ export PATH="/usr/local/bin:/usr/bin"  # to avoid accidentally using MSYS binaries

laszlocsomor@laszlocsomor0-w /cygdrive/c/work/bazel
$ export BAZEL_SH="c:/cygwin64/bin/bash.exe"

laszlocsomor@laszlocsomor0-w /cygdrive/c/work/bazel
$ export BAZEL_PYTHON=c:/python27/python.exe

laszlocsomor@laszlocsomor0-w /cygdrive/c/work/bazel
$ c:/work/bazel-msvc.exe --output_user_root=c:/tmp-cyg build --{host_,}copt=-w --{host_,}cpu=x64_windows_msvc --verbose_failures //src:embedded_tools
...
Target //src:embedded_tools up-to-date:
  C:/tmp-cyg/o6hbs7n0/execroot/bazel/bazel-out/msvc_x64-fastbuild/genfiles/src/embedded_tools.zip
____Elapsed time: 66.175s, Critical Path: 65.27s
```

**Comment by davido** [comment]
@laszlocsomor Thank you for all your hard work to support Windows platform!

**Comment by laszlocsomor** [comment]
**Cool, it all works now.**

Turns out I made PATH too bare.

From cygwin:
```
laszlocsomor@laszlocsomor0-w /cygdrive/c/work/bazel
$ env | grep -i 'msys'
BAZEL_SH=C:\tools\msys64\usr\bin\bash.exe

laszlocsomor@laszlocsomor0-w /cygdrive/c/work/bazel
$ export BAZEL_SH=c:\\cygwin64\\bin\\bash.exe

laszlocsomor@laszlocsomor0-w /cygdrive/c/work/bazel
$ env | grep -i 'msys'

laszlocsomor@laszlocsomor0-w /cygdrive/c/work/bazel
$ env | grep -i 'cygwin'
BAZEL_SH=c:\cygwin64\bin\bash.exe

laszlocsomor@laszlocsomor0-w /cygdrive/c/work/bazel
$ c:/work/bazel-msvc.exe --output_user_root=c:/tmp-cyg build --{host_,}copt=-w --{host_,}cpu=x64_windows_msvc --verbose_failures //src:bazel.exe
...
Target //src:bazel.exe up-to-date:
  C:/tmp-cyg/o6hbs7n0/execroot/bazel/bazel-out/msvc_x64-fastbuild/bin/src/bazel.exe
____Elapsed time: 290.273s, Critical Path: 100.20s
```

From cmd.exe:
```
c:\work\bazel>set | c:\Windows\System32\find.exe /I "msys"
BAZEL_SH=C:\tools\msys64\usr\bin\bash.exe

c:\work\bazel>set BAZEL_SH=c:\cygwin64\bin\bash.exe

c:\work\bazel>set | c:\Windows\System32\find.exe /I "msys"

c:\work\bazel>c:/work/bazel-msvc.exe --output_user_root=c:/tmp-cmd build --host_copt=-w --copt=-w --host_cpu=x64_windows_msvc --cpu=x64_windows_msvc --verbose_failures //src:bazel.exe
...
Target //src:bazel.exe up-to-date:
  C:/tmp-cmd/o6hbs7n0/execroot/bazel/bazel-out/msvc_x64-fastbuild/bin/src/bazel.exe
INFO: Elapsed time: 175.676s, Critical Path: 91.36s
```

**Comment by laszlocsomor** [comment]
To be fair this bug isn't yet closed as I haven't tested with Windows bash (my work machine doesn't have it). 

@davido Do you have Windows bash installed and would you be interested in trying it?

**Comment by davido** [comment]
@laszlocsomor What exactly do you mean by Windows bash? [Windows Subsystem for Linux feature](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide)?

I thought this is tracked in different issue: https://github.com/bazelbuild/bazel/issues/1608. Yes, i can reproduce it, see my last comment there. Yes, i have that installed, but I'm not sure, how could I try bazel from master, if base cannot be run there? Right now I installed Bazel released version from Ubuntu  Bazel repository (0.4.5).

**Comment by laszlocsomor** [comment]
@davido : Yes, that's what I meant, and thanks for referencing the bug, I wasn't aware of it.
I made the assumption that installing the Anniversary Update along with this component meant there would be an actual bash.exe installed somewhere whose path we could set to `BAZEL_SH`. Is that not how it works?

**Comment by davido** [comment]
@laszlocsomor There are two tiny steps more. You enable developer feature on your machine and select that feature from zu GUI (that I wasn't able to find ;-) or per power shell. Then you rebooted voila, you run bash.exe, and Ubuntu Trusty is installed. See steps by steps installation guide is provided [here](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide).

Then I added Java8 PPA and installed Java 8 and added Bazel repository and installed bagel 0.4.5 and was bale to run `bazel version`. But trying to run `bazel build :foo` hangs.

**Comment by laszlocsomor** [comment]
Cool, thanks!

https://github.com/Microsoft/BashOnWindows/issues/620#issuecomment-238088556 goes further in suspecting Java as the culprit, but then in https://github.com/Microsoft/BashOnWindows/issues/620#issuecomment-250630759 someone shows a completed `bazel version` in bash.
I'll have to get a machine with recent enough Win10 to investigate.

**Comment by davido** [comment]
@laszlocsomor Thanks!

As I said in another issue, making Bazel work on "Windows bash" would be a huge step forward to support Windows platform for all bagel driven projects. I would be also able to help with investigation, but unfortunately I'm stuck and don't know how to proceed any further.

Do you have any hints for me?

**Comment by laszlocsomor** [comment]
Thanks, your help would be greatly appreciated!

1. What's the output of `java -version` in bash?
2. Do MSVC-built C++ binaries work in bash? A hello world would suffice.
3. Does bash translate UNIX paths to Windows paths? i.e. Can you pass `/tmp/foo.txt` to a MSVC-built .exe and call `CreateFile` on `argv[1]`?

**Comment by davido** [comment]
I don't think any MSVC related questions make any sense on "Windows Bash".

That's Linux Ubuntu trusty, that is ran without virtual machine. The whole MSVC topic is unrelated, in fact, you can't run any Windows binaries. At least that's how I understand it.

**Comment by laszlocsomor** [comment]
I see, thanks. So if anything we could only run the Linux version of bazel, right?
In that case, can you install OpenJDK 8 and see whether `java -version` works, whether you can run a pre-built Bazel 0.4.5 for Linux, and whether you can bootstrap Bazel from source (using `compile.sh`)?

**Comment by davido** [comment]
> I see, thanks. So if anything we could only run the Linux version of bazel, right?

Yes, that's correct.

> In that case, can you install OpenJDK 8 and see whether java -version works,

Yes, it works. `javac` worked too.

> whether you can run a pre-built Bazel 0.4.5 for Linux

Yes, I was able to install pre-built version 0.4.5 Bazel and run `bazel version`.

> and whether you can bootstrap Bazel from source (using compile.sh)

I haven't tried that yet.

**Comment by laszlocsomor** [comment]
>> whether you can run a pre-built Bazel 0.4.5 for Linux
>
> Yes, I was able to install pre-built version 0.4.5 Bazel and run bazel version.

And that's what hung for "bazel build foo", correct? I think I caught up to you now :)

**Comment by davido** [comment]
> And that's what hung for "bazel build foo", correct? I think I caught up to you now :)

Yeah, exactly! ;-)

**Comment by laszlocsomor** [comment]
In light of the latest comments here I'm closing this bug. Let's continue on https://github.com/bazelbuild/bazel/issues/1608.
