### ISSUE TITLE
Log spam from MSVC

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2726]
MSVC is **very** chatty, I see miles and miles of output for building C++ with `--cpu=x64_windows_msvc`, e.g.:
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\string(526): note: see declaration of 'std::_Integral_to_string'
        with
        [
            _Ty=unsigned int
        ]
(...same or similar things hundreds of times...)

third_party/protobuf/3.0.0/src\google/protobuf/arena.h(623): note: see declaration of 'google::protobuf::Arena::CreateMaybeMessage'
        with
        [
            T=google::protobuf::FieldDescriptorProto
        ]
(...same or similar things hundreds of times...)
```

**Comment by meteorcloudy** [comment]
The error message is incomplete, we should not filter them in msvc_tools.py, but that would only increase the size of output.
But try adding `--copt=/w --host_copt=/w`, the world will be quiet immediately.

**Comment by laszlocsomor** [comment]
cool, i'll try that tomorrow, thanks!
note that these messages are not errors but nots; for whatever reason msvc thinks it's important to make a note about each and every template instantiation, it seems

**Comment by dslomov** [comment]
@meteorcloudy isn't this fixed?

**Comment by dslomov** [comment]
(if not, moving to 0.7)

**Comment by meteorcloudy** [comment]
This is fixed, since we are not using wrapper-script, we are also not filtering any warning messages.
