### ISSUE TITLE
File permissions in bazel-bin are incorrect (all files are executable)

### ISSUE THREAD

**Issue by cuadue** [bazelbuild/bazel#2727]
### Description of the problem / feature request / question:

Every file in `bazel-bin/**/` is executable, including `*.runfiles_manifest`, `*.so`, `*.a` and `*.params`. It would be preferable if only files which can be executed have the executable permission bits set. This would make it easier to look through the produced files.

A quick comparison of files in `/usr/lib` shows that `*.so` and `*.a` files are not themselves executable, despite having executable contents. I'm certain the compilers on my system don't set the executable bit on generated `.o` or `.so` files, so I suspect Bazel must be setting them.

### Environment info
* Operating System:
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.7 (jessie)
Release:	8.7
Codename:	jessie

* Bazel version (output of `bazel info release`):
release 0.4.3

**Comment by hermione521** [comment]
Hmm I can only see we do this for runfiles, and I couldn't find how we do this for other files.
@damienmg what do you think?

**Comment by damienmg** [comment]
I think that's nice to have but a lot of small work to do everywhere. With little impact, let's mark it as P4

**Comment by jin** [comment]
Looks like this is WAI. Please see https://github.com/bazelbuild/bazel/issues/6530#issuecomment-435779225
