### ISSUE TITLE
genrules now implicitly depends on the current C/C++ toolchain. Is it intended?

### ISSUE THREAD

**Issue by ahyangyi** [bazelbuild/bazel#2729]
Hi,

I was using a workspace one file of my toolchain comes from a `genrule`.
I upgraded to Bazel-0.4.5 today. Building targets in this workspace no longer works. The error message says there is a cycle in the dependency graph:

//path/to/my:target
@bazel_tools//tools/cpp:stl
//path/to/my:toolchain
//path/to/my:toolchain_generated_files (host)
//path/to/my:genrule (host)
//path/to/my:toolchain (host)
//path/to/my:toolchain_generated_files (host)

which contains a cycle.
It puzzles me: my genrule only contains a `grep` command. Basically the toolchain needs some minor fixing before usage. That genrule should not depend on my toolchain at all. Even if it should, I need a way to explicitly tell Bazel to not think so.

Thanks a lot!

**Comment by aj-michael** [comment]
See #2691 for discussion of this change.

**Comment by gregestren** [comment]
Hi Yi,

I have a pending fix for this, about to go up for review. That'll make those dependencies only happen when the genrule has "$(CC)", etc. in its command line.

**Comment by ahyangyi** [comment]
Thank you!
