### ISSUE TITLE
Difference in design doc and real doc is confusing

### ISSUE THREAD

**Issue by zlalanne** [bazelbuild/bazel#2730]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

The documentation seems to be inconsistent when talking about the `use_default_shell_env` parameter of ctx.action

[Here](https://bazel.build/designs/2016/06/21/environment.html) it specifies that `use_default_shell_env` will have a default value of "True". Whereas [here](https://bazel.build/versions/master/docs/skylark/lib/ctx.html#action) it lists the default to be false, which seems to match the implementation.

### If possible, provide a minimal example to reproduce the problem:

Just docs

### Environment info
* Operating System:
Ubuntu 14.04

* Bazel version (output of `bazel info release`):

release 0.4.4

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by hermione521** [comment]
Well the first link is a design that published long time ago.. I'm not sure if we should modify the history design doc to match the current implementation.. @aehlig the author can decide.

**Comment by zlalanne** [comment]
Ahh, I understand. It is a bit confusing because you land on that page when searching for how to use environment variables in Bazel, but it doesn't actually match the implementation.

**Comment by hermione521** [comment]
Yes, I understand it's confusing. I would say we should make the pages of doc, design doc and blog more different. @steren

**Comment by ittaiz** [comment]
Maybe the design docs should be updated with a link to the implementation
docs after they've been implemented. Their status also needs to update so
just do it in the same go

**Comment by steren** [comment]
This is very good feedback.
Even internally at Google, design docs and actual implementation may differ a bit, and also diverge over time.

We will take this into account when we redesign the website: blog posts should look different than documentation, and design docs should clearly be identified as design docs. With "status: Implemented" and a link to the doc.

**Comment by steren** [comment]
Let me send a patch to the design doc to link to the doc.
