### ISSUE TITLE
Bazel-Publish-Site and Bazel-Push-Benchmark-Output is failing

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#2731]
My blog post
https://github.com/bazelbuild/bazel/blob/master/site/blog/_posts/2017-03-21-design-of-skylark.md
doesn't appear no the website (https://bazel.build/blog/).

Anyone knows why?

@davidzchen

**Comment by kchodorow** [comment]
I don't think pushing the site has succeeded in several days: http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel-Publish-Site/.

**Comment by hermione521** [comment]
Yes, the job is failing after jenkins update :(

**Comment by laurentlb** [comment]
Apparently, it has been fixed: https://bazel.build/blog/2017/03/21/design-of-skylark.html
