### ISSUE TITLE
Need "Using Bazel with Jenkins" documentation page

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#2733]
Bazel is used both for local development and in continuous integration systems.
Jenkins is a very popular tool to setup continuous integrations.

This is a feature request to add a dedicated page in our documentation explaining how to setup a Bazel build job with Jenkins. Even if it is easy, we should provide snippets of a Jenkins config to run Bazel build and tests.

**Comment by ittaiz** [comment]
+1

**Comment by steren** [comment]
@damienmg and @ittaiz: since both of you configured bazel on Jenkins (or plan to), feel free to share any snippet or content in this thread, we'll use it for a documentation page.

**Comment by ittaiz** [comment]
Haven't gotten to it yet...
If we'll get to it before the issue closes we'll update here

**Comment by damienmg** [comment]
There is that: https://bazel.build/blog/2016/01/27/continuous-integration.html

**Comment by damienmg** [comment]
Also the TF team has been doing that a lot

**Comment by bweston92** [comment]
Any update on using Jenkins with caching for Bazel?
