### ISSUE TITLE
Plan bazel to support  Android Studio in Windows?

### ISSUE THREAD

**Issue by butterl** [bazelbuild/bazel#2734]
Hi , 

 I'm new to bazel .Because of the build speed with Gradle in Android Studio , I want to change my build from Gradle to bazel , but from the offical web page  https://bazel.build/blog/2016/10/20/intellij-support.html 

> The plugins are currently Linux-only, with plans for Mac support in the future.

 Sadly I  use Android Studio as the IDE in windows.

And in the roadmap  https://bazel.build/roadmap.html  said:

> 2017‑02P0. Support for building and testing Java, C++ and Python on Windows

 Is there any plan for bazel to support  Android Studio in Windows ？

**Comment by aj-michael** [comment]
Hi @butterl , there is already an Android Studio plugin for Bazel (https://plugins.jetbrains.com/plugin/9185-android-studio-with-bazel). However, Bazel does not yet support Windows. The roadmap that you linked to has

> 2017-09 P1. Bazel can build Android application on Windows
