### ISSUE TITLE
bazel run routes stdin to /dev/null for C++ applications

### ISSUE THREAD

**Issue by thinlizzy** [bazelbuild/bazel#2737]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

When using bazel run to execute a C++ application that uses cin, it skips all cin reads.
If I manually execute the binary generated by bazel, it works as expected.

### If possible, provide a minimal example to reproduce the problem:

I have a cc_binary rule for a C++ application that reads from std::cin. When I use bazel run on this rule, it skips all cin reads, like the user was pressing enter all the time.
To reproduce, compile and run the snippet below with bazel. Input will be always empty.
```
#include <iostream>
#include <string>

int main()
{
	std::string input;
	std::cout << "enter input: " << std::flush;
	std::getline(std::cin,input);
	std::cout << "input is " << input << std::endl;
	std::cout << ":(" << std::endl;
}
```

### Environment info
* Operating System: Linux

* Bazel version (output of `bazel info release`): release 0.4.3- (@non-git)

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`): 
downloaded bazel-0.4.3-dist.zip and compiled it

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
https://groups.google.com/d/msgid/bazel-discuss/CAA5%3Di_EWj6cmZY-MOQZ_mO4Vwo9kF17neN-uTqgNBpeTA8%3DHPw%40mail.gmail.com?utm_medium=email&utm_source=footer

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by damienmg** [comment]
We are closing stdin when running from bazel. Because we cannot forward stdin to the background server.

What is the use case of such a feature?

**Comment by thinlizzy** [comment]
I'm kinda confused about this 'use case' question. You seem to imply that running applications that read from stdin is an uncommon / eccentric thing.

**Comment by damienmg** [comment]
Nope, I just wonder what is that you really need.

You can run a target by invoking directly the binary, which should just work.

In other word, there is a variety of reasons why you would like to run an application that read from stdin, but I know of none that requires you to do it inside Bazel. I guess you just want to use Bazel run as a convenience for running that binary, or is there more to it?

(If there is no more than that then we probably already have another issue for that feature request).

**Comment by thinlizzy** [comment]
oh I see now. thanks for the clarification!

no, there is no more than that. guess this is a duplicate bug, then

**Comment by damienmg** [comment]
Ok I am actually surprised but I could not find anything except #2337 which relate in the sense that the solution would fix this one too.

I am pretty sure we have that bug open somewhere (probably inside Google).

**Comment by jin** [comment]
The binary can now read from `stdin` from `bazel run`:

```
$ bazel run :main 
INFO: Analysed target //:main (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:main up-to-date:
  bazel-bin/main
INFO: Elapsed time: 0.197s, Critical Path: 0.01s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
enter input: working!
input is working!
:)
```
