### ISSUE TITLE
Something is wrong with the /... target wildcard and symlinks

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#274]
./compile.sh; cd base_workspace; touch WORKSPACE; ../output/bazel query //examples/... returns nothing. ../output/bazel query //examples/java-native/... returns some targets.

This is clearly wrong.

**Comment by haxorz** [comment]
nharmata@nharmata:~/bazel/base_workspace$ pwd
/usr/local/google/home/nharmata/bazel/base_workspace
nharmata@nharmata:~/bazel/base_workspace$ ls -l tools
lrwxrwxrwx 1 nharmata eng 43 Sep  1 12:54 tools -> /usr/local/google/home/nharmata/bazel/tools
nharmata@nharmata:~/bazel/base_workspace$

The current behavior (as of a very long time) is that recursive target patterns don't follow directory symlinks. I'm having trouble finding the documentation for this (perhaps it got deleted accidentally?) and I'm also having trouble remembering the motivation for this though.

**Comment by lberki** [comment]
`RecursiveDirectoryTraversalFunction#visitDirectory()` explicitly filters out symlinks. The rationale given in a comment is that then we don't have to deal with symlink loops.
