### ISSUE TITLE
Test for ubuntu 16.04

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#2741]
Ubuntu 16.04 is an LTS release. Bazel must support it, so we must test Bazel on this Ubuntu version.

**Comment by steren** [comment]
This seems like P0 to me.

**Comment by damienmg** [comment]
I send a Docker tests for now, we want to update all our 15.04 slaves to 16.10 so we run the full test suite on LTS but only bootstrapping on non LTS, sounds good?

**Comment by steren** [comment]
That sounds like a plan.
Thanks a lot

**Comment by damienmg** [comment]
(reducing to P1, please keep P0 for immediate emergency)

As @philwo is moving the VM around he will make the Ubuntu 15.10 migrate to 16.04.

I already added the docker tests and it will hit the repo at next export.

**Comment by philwo** [comment]
This is done. As of https://github.com/bazelbuild/continuous-integration/commit/977fedbafce889a1a798ae8947b2fde6d86beb32, Bazel's CI now uses Ubuntu 16.04 LTS VMs instead of Ubuntu 15.10.
