### ISSUE TITLE
Flag to export permissions in android_library() and android_resources() rules

### ISSUE THREAD

**Issue by hermione521** [bazelbuild/bazel#2743]
export reference id: 28599920
(sorry it's pretty old and I just noticed)

Sometimes users add information to manifests that include permissions required for the correct operation of the module.
The current behavior of Bazel strips permissions from android_library / android_resources rules that set exports_manifest=1 which means that users of a library need to explicitly list permissions by trawling through each module and duplicating the information from the manifest or they can attempt to maintain a android_manifest_merge() rule for their project which will likely break each time underlying modules and their dependencies change.

**Comment by aj-michael** [comment]
This bug contains references to a bunch of stuff that isn't in Bazel.

The relevant part of this issue is that the `exports_manifest` attribute of `android_library` defaults to 0 while it probably should default to 1.
