### ISSUE TITLE
Links to Ubntu and OSX installation documentation are broken

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#2745]
Go to https://bazel.build/versions/master/docs/install.html

Click on the left nav links 'Install on Ubuntu'.
Browser opens on https://bazel.build/versions/master/docs/install-ubuntu.html

Expected: installation doc
Observed: 404

it is the same for the following pages: https://bazel.build/versions/master/docs/install-os-x.html

Is this a problem with the website deployment mechanism?

**Comment by michelleirvine** [comment]
A third link is broken as well: **https://bazel.build/docs/windows-chocolatey-maintenance.html**

I'll look into this and fix asap

**Comment by steren** [comment]
Thanks. As I mentioned. Chances are that the problem lies within our deployment mechanism, and not in the documentation markdown. @damienmg can help you troubleshoot.

**Comment by softprops** [comment]
This is a dup of https://github.com/bazelbuild/bazel/issues/2746. It seems to be fixed now

**Comment by softprops** [comment]
well not for windows but osx and ubuntu are now fine

**Comment by michelleirvine** [comment]
These links are all fixed
