### ISSUE TITLE
@bazel_tools//tools/jdk:java|javac don't depend on a JDK

### ISSUE THREAD

**Issue by sdtwigg** [bazelbuild/bazel#2749]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

@bazel_tools//tools/jdk:java and @bazel_tools//tools/jdk:javac alias to
@local_jdk//:java and @bazel_tools//:javac, respectively. Both of which are merely filegroups. However, they are essentially prebuilt java binaries that require the JDK to be in the runfiles in order to run.

It then ends up seeming somewhat mysterious that in, https://github.com/bazelbuild/bazel/blob/master/tools/build_rules/java_rules_skylark.bzl#L160
"runfiles = ctx.runfiles(files = [deploy_jar, executable] + ctx.files._jdk, collect_data = True)"
that the runfiles have to be the whole jdk (which includes java) and not just java plus its runfiles (since the runfiles are actually empty).

### If possible, provide a minimal example to reproduce the problem:

In https://github.com/bazelbuild/bazel/blob/master/tools/build_rules/java_rules_skylark.bzl#L160, marking _java attribute as an executable that has runfiles attached (which 'seems' reasonable since the script tries to execute it) and replacing ctx.files._jdk in runfiles with
files = ... + [ctx.executable._java], transitive_files=ctx.attr._java.default_runfiles.files will lead to an issue

This was actually discovered in https://github.com/bazelbuild/rules_scala where we tried to remove the direct inclusion of _jdk in ctx.action inputs, thinking that ctx.executable._java would pull in the needed JDK.

### Environment info
* Operating System:
Any although this only occurred during CI in Darwin/macOS since only there was the sandboxing sufficient to hide the system JDK.

* Bazel version (output of `bazel info release`):
0.4.5

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)
Some workspaces seem to include a jdk as a runfile of java.

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by sdtwigg** [comment]
Suggestion is that instead of being filegroups, they should be some other rule that exposes the single files as executables with runfiles as the jdk.

**Comment by buchgr** [comment]
@damienmg can you please have a look and triage the bug?

**Comment by damienmg** [comment]
A short term fix was sent by @sdtwigg which should be good enough. See https://github.com/bazelbuild/bazel/commit/d119f969a30945a1fc29a24a293f6873ff73960d.

Is there anymore to do?

**Comment by buchgr** [comment]
I see. Closing this for now. Please re-open if there is more to do.

**Comment by buchgr** [comment]
Thanks @damienmg @sdtwigg

**Comment by sdtwigg** [comment]
I have a better grasp of the Bazel testing infrastructure now so I will (eventually) try to setup a PR that adds a test for this functionality.
