### ISSUE TITLE
End to end test for bazel rules are hard to write

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2751]
In Bazel we use //src/test/shell to do end to end tests, those tests are in shell so hard to maintain and we do not expose that framework for rules writer.

We could:
   - Clean-up our e2e support
   - Expose it in @bazel_tools
   - Expose the bazel binary as a dependency so we can write those tests.

/cc @steren @or-shachar

**Comment by damienmg** [comment]
Hopefully we can work on our integration testing framework this quarter.

/cc @aragos fyi

**Comment by ittaiz** [comment]
👏🏽

**Comment by mattmoor** [comment]
This is blocking my capacity to jettison `docker_build` into `rules_docker`...  What is the workaround?  Rewriting the tests to avoid this dependency?

**Comment by ittaiz** [comment]
Matt,
How do you think about rewriting the tests to avoid this dependency?

**Comment by mattmoor** [comment]
Doesn't look like I have a choice if I want to do this prior to 0.6 getting released...  :)

**Comment by ittaiz** [comment]
I understand.
My question was on how you're going to do this?
We tried a few different methods and couldn't find a way we think is actually good. rules_scala has a bash script which isn't part of Bazel and just calls out to Bazel. This isn't a good solution but it's the least worse we could see so we're using it

**Comment by damienmg** [comment]
Docker rules does not have failure mode tests so there test does not need to embed bazel integration testing support.

**Comment by mattmoor** [comment]
I ended up redefining the functions I needed, some essentially copied from the bashunit library: https://github.com/bazelbuild/rules_docker/blob/master/docker/testenv.sh#L25

**Comment by steren** [comment]
Note that this is not only a problem for language rules, but for any extension that user write, even internal.

**Comment by ittaiz** [comment]
@damienmg this seems like the generic relevant issue, right?
What we discussed is the desire to move the skylark rules introduced [here](https://bazel-review.googlesource.com/c/15432/1) to a separate repo which people can depend on directly.
Additionally we talked about having the rules extract Bazel itself and so save the (~17 seconds I saw when I tried something similar)

**Comment by damienmg** [comment]
https://github.com/bazelbuild/bazel-integration-testing not yet easy to use but launch approved :)

**Comment by ittaiz** [comment]
Well done! 🙇  👏

**Comment by aiuto** [comment]
cc/ @aiuto

**Comment by aiuto** [comment]
Moving to EngProd, as I think the logical conclusion of this thread is that bazel would take a dependency on bazel-integration-testing and use that. EngProd is the best team to make the call on the value of that.

**Comment by ittaiz** [comment]
I'll add that bazel-integration-testing is somewhat dormant mainly due to no capacity on my side so if EngProd will decide this is logically something they want to do then Wix will find capacity for this repo and/or EngProd can co-maintain (if you want to be sole maintainers we can discuss that to).

**Comment by aiuto** [comment]
Yes. Greenfield development of a tool is fun. Keeping the lights on is less so.

My recent interest comes from looking at a lot of Google's internal integration tests. They are a mess of different styles and techniques, and most are horribly linux specific in their use of bash-isms and tool assumptions.  We need some portable ways to write out a small workspace, run bazel and test that particular targets build, fail in specific ways, or produce specific output. 
 The worst are the failure tests, which are either brittle w.r.t. to the exact words expected in the output of a failure, or do suspect things with sed to normalize output.

I had started a very rough draft of some ideas. I just externalized it here.
[Better Blazel Integration Tests](https://docs.google.com/document/d/1WKQ-CQ64Y-xFUIN-tBjmjQl63OhL4vjOlkX5uEaGel8/edit#)

**Comment by ittaiz** [comment]
> Yes. Greenfield development of a tool is fun. Keeping the lights on is less so.

That’s a bit unfair given I’ve been maintaining rules_scala for about 3-4 years now and it’s far from being greenfield.

I think the main issue is that for us this is 2% of our overall concern while maintainers should probably be devs who can’t live without the project.

One use case that we care about and wasn’t mentioned (I think) was rulesets. I want to test negative or reproducibility functionality of rules_scala inside the bazel build.

I’ve read through your doc and it’s interesting at the very least. I’ll give it some more thought.
Thanks for sharing!

**Comment by aiuto** [comment]
On Thu, May 14, 2020 at 4:33 PM Ittai Zeidman <notifications@github.com>
wrote:

> Yes. Greenfield development of a tool is fun. Keeping the lights on is
> less so.
>
> That’s a bit unfair given I’ve been maintaining rules_scala for about 3-4
> years now and it’s far from being greenfield.
>
I'm sorry. I didn't mean it that way. I was trying to affirm that initial
development is only part of the cost. Someone still has to pay to keep it
alive. This is why we are often hesitant to take drive-by feature PRs,
because the Bazel team will own their upkeep.

> I think the main issue is that for us this is 2% of our overall concern
> while maintainers should probably be devs who can’t live without the
> project.
>
That's fair. And the Bazel team is one of those groups that can't live
without Bazel integration tests.

> One use case that we care about and wasn’t mentioned (I think) was
> rulesets. I want to test negative or reproducibility functionality of
> rules_scala inside the bazel build.
>
Exactly!   It is easy to write tests where my custom rules pass, I can just
have BUILD files and
bazel test //... works
But tests to make sure my rules error out in the right way need to generate
BUILD files or we break test ....
Those absolutely require an integration test framework.

> I’ve read through your doc and it’s interesting at the very least. I’ll
> give it some more thought.
> Thanks for sharing!
>
And I was pleased to discover the repo devoted to this. I would rather that
Bazel
use something that others can reuse, rather than have it's own built-in
integration test.
Any built-in rules we make become part of an API that is hard to change. A
separate
integration framework that we import in is more flexible.

**Comment by ittaiz** [comment]
👍🏽 it sounds like we have a lot in  agreement.

I’d love for Bazel team to help/co-maintain/maintain such an external framework.

I think it’s valuable to take a look at google’s internal needs, Bazel’s needs, community rules needs as well as other companies with internal extensions.

If you (Bazel people) find capacity and interest I think it could be super valuable in hosting an online round table to flush out needs and requirements. Probably start with a doc beforehand to make the discussion more effective.

Good luck!
