### ISSUE TITLE
bazel.exe Entry Point Not Found

### ISSUE THREAD

**Issue by YanYas** [bazelbuild/bazel#2756]
Hi,

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

I managed to build Bazel on Windows 8 okay using Chocclatey (it took a couple goes because of script permissions) but everything seemed to be okay.
Running the following command in CMD with administration privileges

`bazel help build`

 got me the following error window message:

> bazel.exe Entry Point Not Found

> The procedure entry point frexpl could not be located in the dynamic link library c\tools\msys-stdc++-6.dll

### If possible, provide a minimal example to reproduce the problem:
Install Bazel using the Chocolatey
Run a Bazel command. This brings up the error.

### Environment info
* Operating System: Windows 8 Pro (BootcampMac)

* Bazel version (output of `bazel info release`):
0.4.5

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

I have seen what might be a related error here: https://github.com/bazelbuild/bazel/issues/2431

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by laszlocsomor** [comment]
Which version of MSYS do you have installed?
Can you try and bootstrap 0.4.5 from source and see if it works? (Just download the [distribution archive](https://github.com/bazelbuild/bazel/releases/download/0.4.5/bazel-0.4.5-dist.zip) and run `./compile.sh` from an MSYS shell.)

**Comment by laszlocsomor** [comment]
Also, what's your `PATH`?

**Comment by YanYas** [comment]
Sorry, its been ages my Chocolatey Tools Path is : 
c\tools

User PATH is: 

> C:\Program Files (x86)\Parallels\Parallels Tools\Applications;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Arduino\hardware\tools\avr\bin;C:\Python27\;C:\Python27\Scripts\;C:\Users\H\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin;C:\ProgramData\chocolatey\lib\msys2;C:\tools\msys64;

System PATH:

> C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Parallels\Parallels Tools\Applications;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Anaconda3;C:\Program Files\Anaconda3\Scripts;C:\Program Files\Anaconda3\Library\bin;C:\Program Files (x86)\dotnet\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\dotnet\;C:\Program Files (x86)\Skype\Phone\;C:\ProgramData\chocolatey\bin;C:\Program Files\Java\jdk1.8.0_121\bin;c:\tools\msys64\usr\bin;

msys2 runs from my cmd just by typing in 'msys2' regardless of my current folder. Trying to do the bootstrap compile and I came across the follow show stopper: 

> "C:/tools/msys64/tmp/bazel_OXqksRCr/classes
> scripts/bootstrap/buildenv.sh: line 187: unzip: command not found"

**Comment by pcj** [comment]
I had similar issue of entry point error (though the message was slightly different).

I wrote up steps to get bazel.exe installed as a gist in case people find it useful:

https://gist.github.com/pcj/46553228eb782221a1bacd68b37b3d49

**Comment by jbduncan** [comment]
Unfortunately I experienced the same sort of issue as @YanYas and @pcj.

When run from both an admin _and_ non-admin cmd.exe, Bazel throws the following error message.

> The procedure entry point __locale_ctype_ptr could not be located in the dynamic link library msys-2.0.dll.

When run from admin and non-admin Powershells, it seems to immediately quit quietly, without giving any message at all.

FWIW I'm running Windows 7; I installed Bazel via chocolatey 0.10.5; and when I installed Bazel via chocolatey, it did throw a couple of error messages during installation. Can't seem to find what the error messages were anymore.

@petemounce

**Comment by laszlocsomor** [comment]
Hey folks, thanks for your error reports, and sorry about the long silence.

@YanYas : To rectify the missing unzip situation, run `pacman -Syu unzip` from MSYS

@pcj : Thanks for your document! It's very helpful to see all steps in one place.

@jbduncan : This looks like you have a bad version of MSYS installed, or the msys-2.0.dll that's found on your path or in the system directories is not the version that Bazel expects.  Try setting just `PATH=c:\tools\msys64;c:\tools\msys64\usr\bin` and see if it works.

**Comment by jbduncan** [comment]
@laszlocsomor Many thanks for taking the time to suggest a next step for my particular problem.

It looks like setting the path to `c:\tools\msys64;c:\tools\msys64\usr\bin` doesn't work, which I presume is because it removes Bazel from the path and prevents the command `bazel` from being recognised.

```
PS C:\Users\Jonathan> $env:PATH = "c:\tools\msys64;c:\tools\msys64\usr\bin";
PS C:\Users\Jonathan> bazel
The term 'bazel' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spell
ing of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:6
+ bazel <<<<
    + CategoryInfo          : ObjectNotFound: (bazel:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Setting the path to `c:\tools\msys64;c:\tools\msys64\usr\bin;$env:PATH` doesn't seem to resolve the underlying issue either; Bazel still finishes immediately and silently on PowerShell and throws the same error message as before on cmd.exe.

I could reinstall chocolatey and bazel and create a Gist with the log I get for doing so, if you'd find it helpful @laszlocsomor.

**Comment by petemounce** [comment]
@jbduncan please definitely gist the log; also please use the `--verbose` flag with the choco install command?

**Comment by jbduncan** [comment]
@petemounce Certainly!

A gist containing a command and installation log can be found at https://gist.github.com/jbduncan/6d14a54d79264454c562f9336bb260d6.

I did my best to remove chocolatey, bazel _and_ msys2 beforehand, so this should be pretty close to a log from an absolutely fresh install.

Let me know if you need anything else!

**Comment by greggaree** [comment]
@petemounce I have encountered the same issue as @jbduncan. I am also running Windows 7 and Chocolatey 0.10.5.

**Comment by petemounce** [comment]
So it looks like msys2 failed to install.

```
2017-05-05 16:26:31,750 [INFO ] - Starting 'C:\tools\msys64\msys2.exe'...
2017-05-05 16:26:31,766 [INFO ] - 
2017-05-05 16:26:31,797 [ERROR] - ERROR: Cannot process request because the process (5764) has exited.
```

Please would you run
```powershell
choco uninstall msys2 --force
choco uninstall bazel -f
choco install msys2 --version 20160719.1.1
choco install bazel --version 0.4.5
```
and again, gist the logs?

**Comment by greggaree** [comment]
While executing choco install bazel --version 0.4.5, Chocolatey reported a checksum mismatch after download.  The install failed. I tried choco install bazel... again, and it failed again with a checksum mismatch.

**Comment by petemounce** [comment]
Ah, nuts, sorry - I meant `0.4.5.20170331`. I forgot I'd published a fix for the package for 0.4.5.

**Comment by jbduncan** [comment]
@petemounce I'm sorry to say that msys2 failed to install on my computer. The installation log can be found at https://gist.github.com/jbduncan/4960614e51889faa43cb50091e5b1fcf.

**Comment by greggaree** [comment]
The checksums matched. Here is a gist of the log: 
https://gist.github.com/greggaree/b264387f6b5e0231cc1e8d514e3e8874

**Comment by laszlocsomor** [comment]
We'll stop releasing MSYS-ful versions of Bazel with 0.5.4 / 0.6.0 (whichever comes first), which will make this bug go away.
