### ISSUE TITLE
Error message in `_find_cc` (`cc_configure`) should use value in `$CC` rather than directly stating `gcc`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [bazelbuild/bazel#2761]
I had made a typo in my environment variables, accidentally setting `export CC=clang-4.9` (rather than `clang-3.9`); however, the error message returned was:
```Cannot find gcc, either correct your path or set the CC environment variable.```

It could be better stated as something like:
```Cannot find gcc or $CC (clang-4.9), either correct your path or set the CC environment variable.```

**Comment by mhlopko** [comment]
Thanks Eric for the fix in 6ac454a99672547a8d9709e326e573fd51b6bf8a :)
