### ISSUE TITLE
Ability to specify per_file_copt for external repositories

### ISSUE THREAD

**Issue by rohitsaboo** [bazelbuild/bazel#2762]
I want to be able to add the following to my .bazelrc in order to silence unused parameter warnings from protobufs. However, per_file_copt does not seem to work with the leading `@` to identify other repositories.
`--per_file_copt=@com_google_protobuf//.*,@com_google_protobuf//.*@-Wnounused-parameter`

(Of course other personally less appealing alternatives include setting `-Wnounused-parameter` for everything or going inside the protobuf repo and cleaning up the hundred or so warnings.)

**Comment by nicolov** [comment]
`--per_file_copt=external/reponame/.*\.cc@-myflag` seems to work for me.

**Comment by thymbahutymba** [comment]
I would like to apply the flag for everything except all external deps which are out of my control but it does not seems to work. I've inserted in the .bazelrc the following line:
`build --per_file_copt=-external/.*@-Werror=unused-variable`. If instead I use package specific name it works just for such dep `build --per_file_copt=-<package name>/.*@-Werror=unused-variable`. How can I solve this?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by vittorioromeo** [comment]
@sgowroji: I would like this to be re-opened, as I need this feature to suppress external dependency warnings.

**Comment by fmeum** [comment]
@vittorioromeo Bazel now has an `external_include_paths` feature that can silence these warnings. Do you need them to be silenced selectively?

**Comment by vittorioromeo** [comment]
> [@vittorioromeo](https://github.com/vittorioromeo) Bazel now has an `external_include_paths` feature that can silence these warnings. Do you need them to be silenced selectively?

That doesn't work for me.

For example, I just updated `abseil-cpp`:

```
bazel_dep(name = "abseil-cpp", version = "20260107.0")
```

And now some other `bazel_dep` dependencies that depend on Abseil end up creating a lot of deprecation warnings while they're getting compiled, even with `external_include_paths`. 

I would like to pass `-w` to the compilation of my `bazel_dep` dependencies, as I don't really care about those.
