### ISSUE TITLE
bazel test ... error

### ISSUE THREAD

**Issue by jingcangcang** [bazelbuild/bazel#2767]
question:
After bazel test ...
the terminal generate an error: there is one case failed
the error information is as follows:

//syntaxnet:parser_trainer_test                                          FAILED in 1 out of 2 in 41.9s

Executed 50 out of 50 tests: 49 tests pass and 1 fails locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.**

* Bazel version (output of `bazel info release`):
0.4.5

**Comment by bluecmd** [comment]
@jingcangcang It seems you're running TensorFlow tests. This is the issue tracker for Bazel (the build system). I suggest you report this issue in the TensorFlow repository instead (https://github.com/tensorflow/models/issues).

**Comment by buchgr** [comment]
Closing this issue for now. Please re-open if it's a bug in bazel.

**Comment by buchgr** [comment]
Also thanks @bluecmd for the guidance!
