### ISSUE TITLE
The use of 'select' is broken when used in a dependency of a cc_binary

### ISSUE THREAD

**Issue by jbasila** [bazelbuild/bazel#2771]
### Description

When creating a 'cc_binary' rule for creating a dynamic library which depends on a static library rule (cc_library) that has a 'select' for it's sources an error of 'Conflicting actions' occur:

**BUILD:**
```
config_setting(
    name = 'conf_a',
    values = {
        'define': 'CONF=A',
    },
)

cc_library(
    name = 'a',
    srcs = select({
        ':conf_a': [ 'a.c' ],
        '//conditions:default': [ 'dummy.c' ],
    }),
    linkstatic = True,
)

cc_binary(
    name = 'liba.so',
    deps = [ ':a' ],
    linkshared = True,
)
```
**a.c**
```
#include <stdio.h>

void a() {
    puts("a");
}
```
**dummy.c**
```
#include <stdio.h>

void a() {
    puts("dummy");
}
```
When trying to build the **liba.so** target, this is the output:
```
ERROR: file 'src/liba.so' is generated by these conflicting actions:
Label: //src:a, //src:liba.so
RuleClass: cc_library rule, cc_binary rule
Configuration: a533617dbcbc985e54cd30231d42f567
Mnemonic: Fail, CppLink
Action key: 626cb78a-810f-4af3-979c-ee194955f04c, 5f545f2646f6fc0089c5667245e1f934
Progress message: Building unsupported rule //src:a located at /home/jbasila/ckp/src/testing/if_flavor_cc_binary/src/BUILD:10:1, Linking src/liba.so
PrimaryInput: (null), Artifact:[[/bazel/jbasila/_bazel_jbasila/53c93f37d06a02c96f639f41b2bcfa27/execroot/if_flavor_cc_binary]bazel-out/host/internal]_middlemen/external_Slocal_Uconfig_Ucc_Cempty
PrimaryOutput: Artifact:[[/bazel/jbasila/_bazel_jbasila/53c93f37d06a02c96f639f41b2bcfa27/execroot/if_flavor_cc_binary]bazel-out/local-fastbuild/bin]src/liba.so
.
ERROR: Analysis of target '//src:a' failed; build aborted.
INFO: Elapsed time: 0.086s
```

**Comment by mhlopko** [comment]
Hi John, thanks for the report. Unfortunately the problem is that 'liba.so' name that is visible outside of Bazel is not what Bazel internally uses. Internally Bazel uses 'a' for it, so we have a name conflict. If you rename 'a' to 'b', everything will work. Feel free to reopen if there is something I missed here. Thanks!

**Comment by luorixiangyang** [comment]
> Hi John, thanks for the report. Unfortunately the problem is that 'liba.so' name that is visible outside of Bazel is not what Bazel internally uses. Internally Bazel uses 'a' for it, so we have a name conflict. If you rename 'a' to 'b', everything will work. Feel free to reopen if there is something I missed here. Thanks!

How to fix it? Could y give a detail solution by codes modification? 
Do y mean need to modify source of bazel?
