### ISSUE TITLE
Windows: Bazel shouldn't depend on msvcrt.dll

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2772]
The Bazel binary, no matter MSYS or MSVC version, depends on msvcrt.dll.
The reason is we link against [advapi32.lib, ,ole32.lib, shell32.lib](https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/BUILD#L54), and they depend on `msvcrt.dll`
```
C:\Windows\System32>dumpbin /dependents C:/tmp/_bazel_pcloudy/7uxoax_v/execroot/bazel/bazel-out/vc_14_0_x64-fastbuild/bin/src/bazel
Microsoft (R) COFF/PE Dumper Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:/tmp/_bazel_pcloudy/7uxoax_v/execroot/bazel/bazel-out/vc_14_0_x64-fastbuild/bin/src/bazel

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    KERNEL32.dll
    ADVAPI32.dll
    ole32.dll
    SHELL32.dll
    WS2_32.dll

C:\Windows\System32>dumpbin /dependents C:/windows/system32/advapi32.dll
Microsoft (R) COFF/PE Dumper Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:/windows/system32/advapi32.dll

File Type: DLL

  Image has the following dependencies:

    msvcrt.dll
    ntdll.dll
...
```

//cc @laszlocsomor Is it possible to avoid these dependencies?

@dslomov

**Comment by laszlocsomor** [comment]
`msvcrt.dll` is a very common system library, not depending on it (transitively) would be very difficult if not impossible. What's the motivation to break this dependency?

**Comment by meteorcloudy** [comment]
See discussion [here](https://groups.google.com/a/google.com/d/msgid/bazel-androidstudio/CAOZBPs6%3D0X0iA9SwhJycf1Wu483rUb2Z%2Br3xLTL%3DHXFH%3DDFSLA%40mail.gmail.com?utm_medium=email&utm_source=footer).
It would be nice to not have this dependency, but maybe it's not urgent.

**Comment by laszlocsomor** [comment]
I see, thanks! It's a very basic library, contains implementation for many POSIX API functions that we use, avoiding it seems to be rather difficult if at all possible. I see no problems with static linking though.

**Comment by meteorcloudy** [comment]
The problem is because Bazel depends on `msvcrt.dll` transitively, so even we [use `/MT`](https://msdn.microsoft.com/en-us/library/2kzt1wy3.aspx) to specify statically linking against `LIBCMT.lib`(and it is by default, see [msvc_tools.py.tpl](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/wrapper/bin/pydir/msvc_tools.py.tpl#L378)), the binary still depends on `msvcrt.dll` through advapi32.lib, ,ole32.lib, shell32.lib.

However, I didn't see any real problems it's causing.

**Comment by dslomov** [comment]
Dependencies on advapi32.dl, ole32.dll and shell32.dll should be fine (they all 100% present on all Windows versions we care about).

**Comment by meteorcloudy** [comment]
Great, since we are already using `/MT` to do static linking as default, Bazel won't depend on `msvcrt.dll` directly, no action needed here.
