### ISSUE TITLE
`bazel help` should accept all flags that can be specified in bazel.rc as `common`

### ISSUE THREAD

**Issue by kamalmarhubi** [bazelbuild/bazel#2777]
`bazel help` should accept any flag that can be put in a line beginning with `common` in `bazel.rc`. In my use case, I have marked some directories containing unrelated files named `build` with `--deleted_packages` in `tools/bazel.rc` using `common`. This works for all commands except `help`, which is a surprising outcome.

Example:

```
$ cd /tmp
$ cd $(mktemp --directory)
$ ls
$ touch WORKSPACE
$ mkdir tools
$ printf "common --deleted_packages somepkg\n" > tools/bazel.rc
$ bazel build //...
..............
ERROR: no targets found beneath ''.
INFO: Elapsed time: 0.561s
$ bazel help
INFO: Options provided by the client:                                                                                                                                                                              
  Inherited 'common' options: --isatty=1 --terminal_columns=211
INFO: Reading options for 'help' from /tmp/test/tools/bazel.rc:
  Inherited 'common' options: --deleted_packages somepkg
Unrecognized option: --deleted_packages
```

### Environment info
* Operating System: Linux (Debian Stretch)

* Bazel version (output of `bazel info release`): `release 0.4.5`

**Comment by kamalmarhubi** [comment]
This also applies to `bazel shutdown`.

**Comment by fmeum** [comment]
Fixed in https://github.com/bazelbuild/bazel/commit/44d395338ab9a27596b0796c14076641f4cb2093
