### ISSUE TITLE
We are not correctly attributing authors of changes

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#2778]
Example:

* https://bazel-review.googlesource.com/#/c/9610/ has been submitted by a community member
* But in the end, is attributed to a googler in the commit history: https://github.com/bazelbuild/bazel/commit/79251005cdb44781703e498045453efa1b1623a5#diff-bd6b18ec06d00ae0990444f4b6e5ed71

This is a problem. The original author must appear as the author of this commit on GitHub. Attribution of changes is very important.

This might have been introduced by our move to [Copybara](https://github.com/google/copybara).

We are very sorry about this. And will treat this with the highest priority.

**Comment by davido** [comment]
It worked in the past as expected: [1].

* [1] https://github.com/bazelbuild/bazel/commit/9d99bc45df4a6fcfb929cf6e641459f8b33077e3

**Comment by damienmg** [comment]
Change with gerrit are not affected AFAICT. Or maybe we just haven't had a non googler patch with gerrit yet

**Comment by damienmg** [comment]
As discussed offline P1 not P0 because we can work around it (simply not import change until this is fixed).

**Comment by damienmg** [comment]
(also /cc @petemounce who was affected, our only fix now is rollback and rollforward for those)

**Comment by damienmg** [comment]
I guess we are not using https://github.com/google/copybara/blob/master/docs/reference.md#metadatarestore_author

**Comment by fweikert** [comment]
I have found two changes by non-Googlers that were affected by this bug:

https://github.com/bazelbuild/bazel/commit/79251005cdb44781703e498045453efa1b1623a5 by Harsh Vardhan and https://github.com/bazelbuild/bazel/commit/83d07d6ba2d5471e7abe9f1828360b8d29697709 by Peter Mounce.

**Comment by damienmg** [comment]
Ok so a gerrit change and a github change. FTR we do use restore_author

**Comment by damienmg** [comment]
(side-note: since our export script are not open-source that's kind of hard to track work here)

**Comment by damienmg** [comment]
So update: we identified the issue, we have a workaround and the copybara team is working a correct fix. We will resume merge and push once we confirmed the workaround or the fix is in and actually fixes the issue.

**Comment by damienmg** [comment]
So we worked around the copybara bug and import can be done again. leaving this bug open for follow-up with @petemounce and @royalharsh about what to do of the 2 merged change whose attribution is wrong.

**Comment by royalharsh** [comment]
I don't have any problem with it. :smile:

**Comment by damienmg** [comment]
I added a comment on each change.

@petemounce, @royalharsh: please tell if you'd like us to do more (we can rollback and rollforward with the authoring fixed, or other idea you might think of).

@steren: I'll let that bug open for 24 hours. You can also chime in if you think we should do more.

**Comment by petemounce** [comment]
I'm content with the current state, no worries.

**Comment by steren** [comment]
Since @petemounce and @royalharsh confirmed they are OK with their commit not being attributed, let's not spend more time trying to rectify these commits.

I think we can close the issue.
