### ISSUE TITLE
Query language attr cannot filter on the name attribute.

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#278]
Repro:
  bazel query 'attr("name", ".*", //...)'

Result:
   an empty set.

Expected:
  All rule target

**Comment by buchgr** [comment]
@damienmg @laszlocsomor It seems to work for me with the current master branch.

Running the command on the "Getting Started" example project gives:
```
buchgr@buchgr0:~/code/build-java$ bazel query 'attr("name", ".*", //...)'
..........
//src/main/java/com/example/cmdline:runner
//:my-runner
//:my-other-runner
//:greeter
```

**Comment by laszlocsomor** [comment]
Filtering still doesn't work for me with 0.4.4:
```
$ ../bazel-0.4.4.exe query '//src:*' | grep "install"
//src:install_base_key_notools
//src:install_base_key-file_notools
//src:install_base_key
//src:install_base_key-file

$ ../bazel-0.4.4.exe query 'attr("name", ".*install.*", "//src:*")'
INFO: Empty results
```

**Comment by buchgr** [comment]
@laszlocsomor I can reproduce the bug.Will look...

Also, should `bazel query '//src:*'` and `bazel query 'attr("name", ".*", "//src:*")'` be equivalent? I get different result set with 0.4.4.

**Comment by laszlocsomor** [comment]
They should be different. The first one lists input and output file targets along with rules, the second one should only list rules.

**Comment by buchgr** [comment]
It seems like a problem accessing the attribute value - it's always the empty string.

While `query 'attr("name", ".*", "//src:*")'` works, `query 'attr("name", ".+", "//src:*")'` does not (`.*` vs `.+` in the pattern).
