### ISSUE TITLE
Support http caching for query

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2780]
### Description of the problem / feature request / question:

Trying to pass `experimental_repository_cache` to `bazel query` complains that the option is not supported. This means that offline querying is not possible.

### Environment info
* Operating System: Ubuntu 16.04.2
* Bazel version (output of `bazel info release`): 0.4.3

###  Have you found anything relevant by searching the web?
Nope

**Comment by abergmeier-dsfishlabs** [comment]
Maybe it would be good to have a meta-issue so all options of `build` get supported for `query`, too. AFAIR there are more options not working for `query`.

**Comment by kchodorow** [comment]
FWIW, `--experimental_repository_cache` only adds additional caching between bazel projects.  Bazel caches external repositories regardless, it just doesn't share them between various workspaces on your machine.

**Comment by abergmeier-dsfishlabs** [comment]
> --experimental_repository_cache only adds additional caching between bazel projects. Bazel caches external repositories regardless, it just doesn't share them between various workspaces on your machine.

When I build with `experimental_repository_cache` and then query without, it tries to download the `http_archive`. This then breaks working offline.

**Comment by kchodorow** [comment]
Hmm, that is a more serious bug.  Definitely not intended.

**Comment by laszlocsomor** [comment]
@abergmeier-dsfishlabs :

> Maybe it would be good to have a meta-issue so all options of `build` get supported for `query`, too. AFAIR there are more options not working for `query`.

See https://github.com/bazelbuild/bazel/issues/3054

**Comment by laszlocsomor** [comment]
@kchodorow, @damienmg : Is this really P1? If so, let's find an assignee and milestone. If not, let's demote to P2 or P3.

**Comment by damienmg** [comment]
Well I don't think this is a P1 until fixing repository caching becomes a P1 again... (IMO it should be but we have so many P1...)

**Comment by laszlocsomor** [comment]
Thanks! Dropped the priority.

> we have so many P1

Yes, and as this week's sheriff I feel uncomfortable with that :)

**Comment by aehlig** [comment]
First remark: `http_archive` does enough caching so that `bazel query` works also offline for every repository that was accessed while being online (see https://bazel-review.googlesource.com/c/bazel/+/33750/). So we can probably change the priority.

Second: In fact, a quick test with the release candidate of `0.10.0` shows that `--experimental_repository_chache` is supported for `bazel query` and does the caching one expects. So, it seems someone already implemented that feature request without closing the issue. Will add a test to ensure it stays that way.
