### ISSUE TITLE
Display that bazel is waiting for BEP upload in the UI.

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#2782]
A BEP upload might take longer than a build (i.e. for null builds) and thus bazel might be waiting for transports to finish uploading. If that's the case, we need to display this information in the UI.

**Comment by ittaiz** [comment]
May I ask what BEP upload is?

**Comment by buchgr** [comment]
It's short for build event protocol https://github.com/bazelbuild/bazel/blob/92f182bd1058ac05db8592d3f390826d2f94ed98/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto

**Comment by ittaiz** [comment]
I'm sorry, I wasn't clear.
I know what BEP is. I was asking about what does the upload event mean?

**Comment by pcj** [comment]
Well I'm glad you asked, 'cause I didn't know was BEP was... Now I know!

**Comment by buchgr** [comment]
@ittaiz So the protocol will typically be uploaded to a server and at times this upload may take longer then the build itself i.e. when the whole build is cached. In that case, bazel needs to wait for the upload to finish and we should display the reason for the wait time in the user interface.

**Comment by ittaiz** [comment]
When you say the *protocol* will be uploaded you mean notifying the server
about the event taking place? this is a meta event?

**Comment by buchgr** [comment]
Everything that goes on in a build is encoded in the BEP protobuf and may then be written to disk or uploaded to a server (i.e. for analysis, visualisation, ...).

**Comment by ittaiz** [comment]
Got you. Thanks!

**Comment by buchgr** [comment]
implemented.
