### ISSUE TITLE
Can't Link Shared Libraries Located in /usr/local/include Folder

### ISSUE THREAD

**Issue by RoboEvangelist** [bazelbuild/bazel#2785]
Folks,
I can't add any libraries in the /usr/local/include (or /lib) to the BUILD file. Bazel complains it cannot find the headers, nor the *.so files.
Are you planning on adding support for that?

Thanks,

**Comment by buchgr** [comment]
Hi @RoboEvangelist !

Can you please follow the issue template and explain exactly what's happening. Bonus point if you provide a smaller reproducer. Closing this for now.

Thanks so much!
