### ISSUE TITLE
no such package '@gmock_archive//': Error downloading in Tensorflow (on ubuntu_X86 14.04)

### ISSUE THREAD

**Issue by sandipmgiri** [bazelbuild/bazel#2788]
I'm getting the following error when trying to run the configure command (on ubuntu_X86:14.04):

ERROR: /root/tf/tensorflow/tensorflow/workspace.bzl:221:3: no such package '@gmock_archive//': Error downloading

Please find the attached log for more details.  [logfile.txt](https://github.com/bazelbuild/bazel/files/904981/logfile.txt)

Note- On ubuntu-ppc64le vm , configure command ran successfully.

Any suggestion/solution ?

**Comment by buchgr** [comment]
Hi @sandipmgiri. Thank you for your bug report, but this seems to be an issue with tensorflow. Please file an issue on their tracker: https://github.com/tensorflow/tensorflow

Closing this for now.
