### ISSUE TITLE
tensforflow build from source got an issue 

### ISSUE THREAD

**Issue by MilesZhao** [bazelbuild/bazel#2793]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

cannot find the python environment 

### Environment info
Ubuntu

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by MilesZhao** [comment]
ERROR: /home/yongzhao/tensorflow/tensorflow/core/BUILD:1346:1: Executing genrule //tensorflow/core:version_info_gen failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 127.
/usr/bin/env: 'python': No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.818s, Critical Path: 0.27s

**Comment by BKJackson** [comment]
I have a similar error in the bazel build for Mac OSX (darwin): 
```
$ bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
ERROR: Inconsistent crosstool configuration; no toolchain corresponding to 'local_darwin' found for cpu 'darwin'.
INFO: Elapsed time: 0.101s
```

Using bazel version: 0.4.5-homebrew.

**Comment by MilesZhao** [comment]
I find a solution by myself. 

change the python to python3 under  below files:

/Users/MilesZhao/Desktop/tensorflow/tensorflow/tools/ci_build/windows/bazel/common_env.sh:
   43  
   44  # Add python into PATH, it's needed because gen_git_source.py uses
   45: # '/usr/bin/env python' as a shebang
   46  export PATH="/c/Program Files/Anaconda3:$PATH"
   47  

/Users/MilesZhao/Desktop/tensorflow/tensorflow/tools/git/gen_git_source.py:
    1: #!/usr/bin/env python
    2  # Copyright 2016 The TensorFlow Authors. All Rights Reserved.
    3  #

/Users/MilesZhao/Desktop/tensorflow/third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl:
    1: #!/usr/bin/env python
    2  # Copyright 2015 The TensorFlow Authors. All Rights Reserved.
    3  #

/Users/MilesZhao/Desktop/tensorflow/third_party/sycl/crosstool/computecpp.tpl:
    1: #!/usr/bin/env python
    2  
    3  import os
