### ISSUE TITLE
Doubts regarding config_setting

### ISSUE THREAD

**Issue by RenatoUtsch** [bazelbuild/bazel#2795]
Hello,

I'm trying to understand `config_setting` for detecting the underlying platform and had some doubts. Could you help me clarify them?

1. What is the difference between `x64_windows` and `x64_windows_(msvc|msys)` cpus? If I create config_setting's for all of them, will only one of them trigger? Should I just ignore `x64_windows`?

2. To detect Windows, what is the recommended way? Currently I'm doing:
```python
config_setting(
    name = "windows",
    values = {"crosstool_top": "//crosstools/windows"},
)

config_setting(
    name = "windows_msvc",
    values = {
        "crosstool_top": "//crosstools/windows",
        "cpu": "x64_windows_msvc",
    },
)

config_setting(
    name = "windows_msys",
    values = {
        "crosstool_top": "//crosstools/windows",
        "cpu": "x64_windows_msys",
    },
)
```
By using this I want to use `:windows` to match *all* Windows versions and `:windows_msvc`, for example, to match only MSVC. Is this the best way to do it?

3. What is the difference between `darwin` and `darwin_x86_64` cpus? I know they match macOS, but do I need to always specify both when selecting something for macOS? If not, is there a better way to detect macOS with only one `config_setting`? Like using `//crosstools` with Windows?

4. How do detect Linux? I know you can detect the operating systems you care about first and then use `//conditions:default`, but it'd be nice to have a way to detect specifically Linux and not leave it as the default.

5. What are `k8`, `piii`, etc? Is there any documentation somewhere describing all the possible cpu values and what they mean?

6. If I wanted to use `//crosstools` to detect each platform, is there somewhere I can look up all available crosstools?

Thanks!

**Comment by buchgr** [comment]
Hi @RenatoUtsch! The issue tracker is for bug reports. Could you please ask this question on stackoverflow, so that other users can benefit from an answer. I ll find someone from the bazel team to answer your question on stackoverflow :-).

http://stackoverflow.com/questions/tagged/bazel

Closing this for now.

**Comment by RenatoUtsch** [comment]
Created the issue: http://stackoverflow.com/questions/43377370/doubts-regarding-config-setting-with-bazel

Sorry for taking so long, I forgot to create it. Thanks!
