### ISSUE TITLE
Bazel on Mac: @local_jdk//:bin/javadoc not invokable without @local_jdk//:jdk-default

### ISSUE THREAD

**Issue by ronshapiro** [bazelbuild/bazel#2796]
### Description of the problem / feature request / question:

Dagger uses `@local_jdk//:bin/javadoc` as an [input to a `genrule`](https://github.com/google/dagger/blob/bb2d3a9f142f91156cfa39d5d5894ade0e146c4c/tools/javadoc.bzl#L95) so that it can [run the javadoc binary](https://github.com/google/dagger/blob/bb2d3a9f142f91156cfa39d5d5894ade0e146c4c/tools/javadoc_library_impl.sh) in a genrule (#446). This works fine on Linux, but fails on Mac, unless `@local_jdk//:jdk-default` is also listed in the tools. Is that expected behavior? It definitely caught me by surprise. This was reported in https://github.com/google/dagger/issues/637 and manifested itself as errors like this:
```
Error: could not find libjava.dylib
Error: Could not find Java SE Runtime Environment.
```

### Environment info
* Operating System: Mac
* Bazel version (output of `bazel info release`): 0.4.4 and 0.4.5

**Comment by ittaiz** [comment]
I think this might be a dup of #2749
WDYT?

**Comment by buchgr** [comment]
Seems so. Thanks @ittaiz and thanks @ronshapiro for reporting. Closing this for now.

If it's not a duplicate, please re-open @ronshapiro.
