### ISSUE TITLE
Run any one of the bazel commands: corrupt installation: file LcovMerger.java modified

### ISSUE THREAD

**Issue by GinFungYJF** [bazelbuild/bazel#2798]
### Description of the problem / feature request / question:

Run any one of the bazel commands, complains:
```
~# bazel version
Error: corrupt installation: file '/root/.cache/bazel/_bazel_root/install/e4abe4ff56d8f229afa015dc729c5bd9/_embedded_binaries/embedded_tools/tools/test/LcovMerger/java/com/google/devtools/lcovmerger/LcovMerger.java' modified.  Please remove '/root/.cache/bazel/_bazel_root/install/e4abe4ff56d8f229afa015dc729c5bd9' and try again.
```

### If possible, provide a minimal example to reproduce the problem:
I can't reproduce it. It sometimes happens. Whether it is relevant that the build machine is used to build too many projects (40+) as a CI slave?

### Environment info
* Operating System:
Ubuntu 14.04 LTS

* Bazel version (output of `bazel info release`):
0.4.5

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
```
Build label: 0.4.5
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 12:19:38 2017 (1489666778)
Build timestamp: 1489666778
Build timestamp as int: 1489666778
```

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/2450  and  https://github.com/bazelbuild/bazel/issues/471 might be relevant

**Comment by buchgr** [comment]
@GinFungYJF thank you very much for your bug report!

Did you try removing `/root/.cache/bazel/_bazel_root/install/e4abe4ff56d8f229afa015dc729c5bd9` as suggested by the error message and did that help?

**Comment by GinFungYJF** [comment]
@buchgr After removing `/root/.cache/bazel/_bazel_root/install/e4abe4ff56d8f229afa015dc729c5bd9`, bazel can build my project successfully. But the error sometimes still happens and I have to do the same thing.

**Comment by damienmg** [comment]
I would suggest not running Bazel as root. It seems to be due to a  modification in a file of your set-up which would suggest a problem in you CI setup. Is it available somewhere?

**Comment by damienmg** [comment]
Closing issue after several months without activities.
