### ISSUE TITLE
Cannot build latest version   ON Centos6, while I can build version 0.4.0, 0.4.1.

### ISSUE THREAD

**Issue by bigvzhang** [bazelbuild/bazel#2800]
I can build version 0.4.0 & 0.4.1 without any problems, because compilor will download protobuf automatically and build successfully. But on version 0.4.5 & late, no lucky any more. I could build protobuf. and set protoc path, but it also ask me the java plugin. After git clone https://github.com/grpc/grpc-java, I couldn't link proto so requried. I'm sure I have set link path right. 

1) 
[vzhang@merry08 bazel]$ ./compile.sh compile
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
  Building Bazel from scratch
ERROR: Must specify PROTOC if not bootstrapping from the distribution artifact
2) After I set PROTOC, I got error
[vzhang@merry08 bazel]$ export PROTOC=$HOME/portobuf/bin
[vzhang@merry08 bazel]$ ./compile.sh compile
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
  Building Bazel from scratch
ERROR: Must specify GRPC_JAVA_PLUGIN if not bootstrapping from the distribution artifact
3) when I build grpc, I got such informations.
[vzhang@merry08 ~]$ cd $OLDPWD
[vzhang@merry08 grpc-java]$ ls
1                        buildscripts        COMPILING.md     gradle                  interop-testing  protobuf            run-test-server.sh  testing-proto
all                      CHANGES.md          context          gradle.properties       LICENSE          protobuf-lite       SECURITY.md         thrift
android-interop-testing  checkstyle.license  CONTRIBUTING.md  gradle.properties.save  netty            protobuf-nano       services
auth                     checkstyle.xml      core             gradlew                 NOTICE.txt       README.md           settings.gradle
benchmarks               codecov.yml         documentation    gradlew.bat             okhttp           RELEASING.md        stub
build.gradle             compiler            examples         grpclb                  PATENTS          run-test-client.sh  testing
[vzhang@merry08 grpc-java]$ ./compile.sh compile
-bash: ./compile.sh: No such file or directory
[vzhang@merry08 grpc-java]$ set -o vi
[vzhang@merry08 grpc-java]$ ldconfig -p | grep vzhang
        libprotoc.so.12 (libc6,x86-64) => /home/vzhang/protobuf/lib/libprotoc.so.12
        libprotoc.so (libc6,x86-64) => /home/vzhang/protobuf/lib/libprotoc.so
        libprotobuf.so.12 (libc6,x86-64) => /home/vzhang/protobuf/lib/libprotobuf.so.12
        libprotobuf.so (libc6,x86-64) => /home/vzhang/protobuf/lib/libprotobuf.so
        libprotobuf-lite.so.12 (libc6,x86-64) => /home/vzhang/protobuf/lib/libprotobuf-lite.so.12
        libprotobuf-lite.so (libc6,x86-64) => /home/vzhang/protobuf/lib/libprotobuf-lite.so
[vzhang@merry08 grpc-java]$ ./gradlew build
*** Building codegen requires Protobuf version 3.2.0
*** Please refer to https://github.com/grpc/grpc-java/blob/master/COMPILING.md#how-to-build-code-generation-plugin
:grpc-context:compileJava UP-TO-DATE
:grpc-context:processResources NO-SOURCE
:grpc-context:classes UP-TO-DATE
:grpc-context:jar UP-TO-DATE
:grpc-core:compileJava UP-TO-DATE
:grpc-core:processResources UP-TO-DATE
:grpc-core:classes UP-TO-DATE
:grpc-core:jar UP-TO-DATE
:grpc-auth:compileJava UP-TO-DATE
:grpc-auth:processResources NO-SOURCE
:grpc-auth:classes UP-TO-DATE
:grpc-auth:jar UP-TO-DATE
:grpc-netty:compileJava UP-TO-DATE
:grpc-netty:processResources UP-TO-DATE
:grpc-netty:classes UP-TO-DATE
:grpc-netty:jar UP-TO-DATE
:grpc-okhttp:compileJava UP-TO-DATE
:grpc-okhttp:processResources UP-TO-DATE
:grpc-okhttp:classes UP-TO-DATE
:grpc-okhttp:jar UP-TO-DATE
:grpc-compiler:compileJava_pluginExecutableJava_pluginCpp UP-TO-DATE
:grpc-compiler:linkJava_pluginExecutable
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -lprotoc
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -lprotobuf
collect2: error: ld returned 1 exit status

:grpc-compiler:linkJava_pluginExecutable FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grpc-compiler:linkJava_pluginExecutable'.
> A build operation failed.
      Linker failed while linking protoc-gen-grpc-java.
  See the complete log at: file:///home/vzhang/Src/grpc-java/compiler/build/tmp/linkJava_pluginExecutable/output.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.204 secs

Can I avoid grpc java building? If not, how can I link the protoc so?

Best Regards,
Vic

**Comment by damienmg** [comment]
From which source do you build Bazel? You should use the distribution artifact at https://github.com/bazelbuild/bazel/releases/download/0.4.5/bazel-0.4.5-dist.zip

**Comment by buchgr** [comment]
Hey @bigvzhang . Please re-open this bug if the problem persists when building from the source that @damienmg suggested. Thanks!
