### ISSUE TITLE
[Python] How generate BUILD files for Python project

### ISSUE THREAD

**Issue by nlamirault** [bazelbuild/bazel#2801]
Hi,
i would like to test Bazel for a current Python application (Flask). Do you know if it possible to manage BUILD files automatically ? Like the [gazel](https://github.com/mikedanese/gazel) tool for golang projects.
Thanks.

**Comment by buchgr** [comment]
Hey @nlamirault ! We are using GitHub for bug reports. It would be great if you could ask this question on stackoverflow using the bazel tag. We will be happy to answer it there (so that other users can also benefit).

**Comment by nlamirault** [comment]
Thanks. Done: http://stackoverflow.com/questions/43364826/how-generate-build-files-for-python-project

**Comment by buchgr** [comment]
@vladmos might know?

**Comment by ZikangXiong** [comment]
[pazel](https://github.com/tuomasr/pazel)
