### ISSUE TITLE
Remove dependency on jGit

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#2802]

**Comment by ittaiz** [comment]
May I ask why?

**Comment by kchodorow** [comment]
We've run into several bugs with it that do not inspire confidence, like throwing RuntimeExceptions that are not documented (see https://github.com/bazelbuild/bazel/blob/3fa1e883acd14a208e7c70c6e9b627981fd86dd9/src/main/java/com/google/devtools/build/lib/bazel/repository/GitCloner.java#L198-L200) and failing to set file permissions correctly on OS X in some cases (can't find the bug for that at the moment).

I'm not sure what we'd replace it with, though, and possibly we'd just deprecate these rule in favor of https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/git.bzl.

**Comment by jbduncan** [comment]
@kchodorow Have these bugs been reported to the JGit team?

**Comment by kchodorow** [comment]
The file permissions one: yes, I found it in the jGit bugtracker. 

The runtime exceptions are a bigger issue which I think indicates a different philosophy of development.

**Comment by dslomov** [comment]
This is fixed.
