### ISSUE TITLE
Update C++ gRPC from 0.13.0

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#2804]
0.13.0 is truly ancient and unsupported, so it should be updated to something more recent. It'd also probably help us get rid of the Windows patch. Furthermore, it might also help with the issue whereupon a gRPC thread is still alive when we fork the server and prevents the fork from succeeding.

This probably also requires an update to protobuf.

The Java gRPC library should also be given a closer look.

**Comment by buchgr** [comment]
gRPC Java has been updated to 1.3.0. We considered this more important, as with BEP and Remote Execution gRPC Java talks over real networks while gRPC C++ only talks over loopback.

**Comment by buchgr** [comment]
@tetromino feel free to take this bug!
