### ISSUE TITLE
Bazel compile problem on Orange Pi+ (plus) 2e

### ISSUE THREAD

**Issue by pczekalski** [bazelbuild/bazel#2808]
I'm trying to compile bazel from source on Raspberry Pi clone - Orange Pi+ (plus) 2e osing Oracle JDK (Open JDK also fails with Internal Error, that is currently acknowledged to be JDK problem on ARM, so I had to switch to Oracle).
### Description of the problem / feature request / question:

Compilation seem to be working quite well but finally I'm stuck with the following error:

```
Note: Recompile with -Xlint:deprecation for details.
ERROR: /home/pczekalski/Downloads/bazel/src/BUILD:205:2: Executing genrule //src:bazel-bin failed: process-wrapper failed: error executing command 
  (cd /tmp/bazel_HPfSTSQQ/out/bazel-sandbox/225db975-fe8d-416f-ba14-647190542e8f-849/execroot/bazel && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
  /tmp/bazel_HPfSTSQQ/out/execroot/bazel/_bin/process-wrapper -1 5 - - /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; rm -f bazel-out/local-opt/bin/src/bazel; cat bazel-out/local-opt/bin/src/main/cpp/client bazel-out/local-opt/genfiles/src/package.zip > bazel-out/local-opt/bin/src/bazel && zip -qA bazel-out/local-opt/bin/src/bazel').

zip error: Output file write failure (write error on zip file)
Target //src:bazel failed to build
INFO: Elapsed time: 1778.275s, Critical Path: 1725.94s
```
### Environment info
* Operating System:

Hardware is Orange Pi+ 2e with OS installed into the eMMC (16GB) 
```
Linux orangepiplus2e 3.4.113-sun8i #10 SMP PREEMPT Thu Feb 23 19:55:00 CET 2017 armv7l armv7l armv7l GNU/Linux
```

###  Have you found anything relevant by searching the web?
I've been browsing web for similar errors most of them seem to be due to the limited storage that is not a case here:
`Filesystem     1K-blocks    Used Available Use% Mounted on
sysfs                  0       0         0    - /sys
proc                   0       0         0    - /proc
udev              897544       0    897544   0% /dev
devpts                 0       0         0    - /dev/pts
tmpfs             206264    5864    200400   3% /run
/dev/mmcblk0p1  14876944 3647104  10474136  26% /
securityfs             0       0         0    - /sys/kernel/security
tmpfs            1031304   22260   1009044   3% /dev/shm
tmpfs               5120       4      5116   1% /run/lock
tmpfs            1031304       0   1031304   0% /sys/fs/cgroup
cgroup                 0       0         0    - /sys/fs/cgroup/systemd
cgroup                 0       0         0    - /sys/fs/cgroup/blkio
cgroup                 0       0         0    - /sys/fs/cgroup/memory
cgroup                 0       0         0    - /sys/fs/cgroup/perf_event
cgroup                 0       0         0    - /sys/fs/cgroup/cpu,cpuacct
cgroup                 0       0         0    - /sys/fs/cgroup/cpuset
cgroup                 0       0         0    - /sys/fs/cgroup/devices
cgroup                 0       0         0    - /sys/fs/cgroup/freezer
systemd-1              -       -         -    - /proc/sys/fs/binfmt_misc
mqueue                 0       0         0    - /dev/mqueue
debugfs                0       0         0    - /sys/kernel/debug
fusectl                0       0         0    - /sys/fs/fuse/connections
tmpfs            1031304      36   1031268   1% /tmp
/dev/mmcblk0p1  14876944 3647104  10474136  26% /var/log.hdd
log2ram            51200    3348     47852   7% /var/log
tmpfs             206264       8    206256   1% /run/user/1000
gvfsd-fuse             0       0         0    - /run/user/1000/gvfs
binfmt_misc            0       0         0    - /proc/sys/fs/binfmt_misc
`

Any help is appreciated as I'm hoping finally to move to building Tensorflow library to test it.

Thank you in advance,

P.

**Comment by damienmg** [comment]
Tmp has 1G free so it is possible that we fill it up  during the build, although that seems a lot for Bazel output base.

Have you tried increasing the size of /tmp?

**Comment by pczekalski** [comment]
Thank you for the reply. Answering question - no - I didn't. 1GB seemed to be quite enough, but will give it a try with bigger one. Anyway error seemed more like permission or invalid path than out of space. Will give it a try and report next week.

**Comment by pczekalski** [comment]
I can acknowledge that increasing tmp to 4GB + chmod 777 on all source files/folders solved the problem.

**Comment by damienmg** [comment]
This was fixed forgot to close, my travels made me forgot about that bug.

**Comment by shmilyhh** [comment]
@damienmg I meet the same problem, but I don't have the permission to change the size of the /tmp. Do you have other solution? Thanks.

**Comment by shmilyhh** [comment]
@damienmg I found the solution in #2738.
