### ISSUE TITLE
Bazel query sees and resolve target in a local_repository

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2811]
While investigating removing protobuf weirdness, @buchgr fall under a very strange situation.

According to a change by @katre, any local_repository defined under the workspace should not be seen as a package in the main repository. So `bazel query //third_party/protobuf/...` should not see anything under 3.0.0: https://github.com/bazelbuild/bazel/blob/master/WORKSPACE#L53 (we actually change this line with a local_repository to test):

```
[dmarting@trantor git bazel (master)] $ bazel query third_party/protobuf/...
...................
//third_party/protobuf/3.0.0:protobuf_python_genproto
//third_party/protobuf:srcs
//third_party/protobuf/3.0.0:srcs
//third_party/protobuf:protoc_lib
//third_party/protobuf:protoc
//third_party/protobuf/3.0.0:protoc
//third_party/protobuf/3.0.0:protoc_lib
//third_party/protobuf:protobuf_python
//third_party/protobuf/3.0.0:protobuf_python
//third_party/protobuf/3.0.0:protobuf_python_srcs
//third_party/protobuf:protobuf_java_util
//third_party/protobuf/3.0.0:protobuf_java_util
//third_party/protobuf:protobuf_java
//third_party/protobuf/3.0.0:protobuf_java
//third_party/protobuf:protobuf-jars
//third_party/protobuf/3.0.0:protobuf-jars
//third_party/protobuf:protobuf
//third_party/protobuf:java_toolchain
//third_party/protobuf/3.0.0:java_toolchain
//third_party/protobuf/3.0.0:protobuf
//third_party/protobuf/3.0.0:protobuf_lite
//third_party/protobuf/3.0.0:freebsd
[dmarting@trantor git bazel (master)] $ git diff
diff --git a/WORKSPACE b/WORKSPACE
index 0f215c8a3..49c164ae6 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -50,10 +50,9 @@ docker_repository()
 # This allows rules written in skylark to locate apple build tools.
 bind(name = "xcrunwrapper", actual = "@bazel_tools//tools/objc:xcrunwrapper")
 
-new_local_repository(
+local_repository(
     name = "com_google_protobuf",
     path = "./third_party/protobuf/3.0.0/",
-    build_file = "./third_party/protobuf/3.0.0/BUILD",
 )
 
 new_local_repository(
```

@katre: any idea why we see those in query?

**Comment by katre** [comment]
Hmm, I'm not sure without digging into the source. I'm on vacation til next
week, go ahead and file an issue and assign it to me.

**Comment by damienmg** [comment]
This was actually an issue :) assigned :)

**Comment by katre** [comment]
The problem in the stock bazel source, with new_local_repository, is that there is no WORKSPACE file, which is what [LocalRepositoryLookupFunction](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/skyframe/LocalRepositoryLookupFunction.java) is using to check for the presence of a local repository. The WORKSPACE file generated by [NewLocalRepositoryRule](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/repository/NewLocalRepositoryRule.java) is located at:
```
[output_base]/external/com_google_protobuf/WORKSPACE
```
but the actual query is looking at the directory path
```
[bazel_dir]/third_party/protobuf/3.0.0/WORKSPACE
```
so there is no match.

There's not an easy way to solve this that I know of.

If we change com_google_protobuf to a local_repository, as the 'git diff' seems to indicate, there is still no WORKSPACE present in [bazel_dir]/third_party/protobuf/3.0.0/, so it is not detected as a local repository.

Also, the way LocalRepositoryLookupFunction tests for local_repositories is brittle, specifically it's relying on [PathFragment](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/vfs/PathFragment.java).equals() to check if paths match, and that is confused by the leading "./" in the path of com_google_protobuf.

If I fix the path, and also add an empty WORKSPACE, then LocalRepositoryLookupFunction detects the repository and filters out the references to //third_party/protobuf/3.0.0.

Clone https://github.com/katre/bazel/tree/i2811-query-oddness to see the changes I made.

Action items:
1. File an issue on [LocalRepositoryRule](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/repository/LocalRepositoryRule.java) to give an error if there is no WORKSPACE file.
2. File an issue on PathFragment.equals to properly handle relative paths starting with "./" or "../". OR forbid those in the path attribute of repositories.
3. Why do we have two repositories, com_google_protobuf and com_google_protobuf_java, pointing to the same directory? If we need both names, can

**Comment by damienmg** [comment]
Action item 3 is under investigation by carmi FTR

**Comment by katre** [comment]
This issue is fixed, closing now,
