### ISSUE TITLE
document docker_build `debs` caveats

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/bazel#2812]
I spent a good long while last night figuring out that in bazel 0.4.5, the `debs` parameter on `docker_build` doesn't work with packages that use post-install and other bits to do main work of the package.

Packages that do so use the full debian package install process include `ca-certificates` which uses it to create the `/etc/ss/certs/ca-certificates.crt`. Bazel, instead, only copies files out of the deb file. 

Unfortunately, the documentation for `docker_build` doesn't seem to mention that behavior and, oof, actually mentions a `ca_certificates` package in a way that seems like it'd be easy to make work. It probably should mention the installation behavior and also maybe not mention `ca_certificates`. As a bonus, it'd be really nice if the `docker_build` examples included a way to get ca-certificates installed because doing verified TLS is super important to systems in 2017.

Of course, it'd be nice if `docker_build`'s `debs` _did_ work with Debian's `ca-certificates` and similar packages, and if y'all have a plan or an idea of how easy that would be, I'd be willing to make a ticket for that work, too. Would be cool to not have to check in a `docker save`'d image just to get one more package beyond the base install.

(For the extra curious: even with those copies it doesn't seem that the ca-certificates installation is easily correctable after the fact with a command at runtime. Plus, ick to doing that in every final images command's, you know?)

**Comment by mattmoor** [comment]
See the discussion in [this](https://github.com/GoogleCloudPlatform/distroless/pull/11) PR, but IMO `build_tar.py` (part of `pkg_tar`) should error when the `deb` contains any more than data.

**Comment by shs96c** [comment]
It would be nicer if the docker image could have those files installed by running apt-get (or dpkg) in the docker image. It would be slower, and require the presence of the docker binaries on the host system, but it wouldn't break the requirement that all inputs are known before running the build step.

**Comment by damienmg** [comment]
FTR I moved this to bazelbuild/rules_docker#133
