### ISSUE TITLE
Extensions examples might be wrong

### ISSUE THREAD

**Issue by tanin47** [bazelbuild/bazel#2813]
In the first example, I think `empty.bzl` and `extension.bzl` must be in the `pkg` dir, and the `pkg` dir must have an empty `BUILD`.

Here: https://bazel.build/versions/master/docs/skylark/cookbook.html

**Comment by laurentlb** [comment]
Sorry for the confusion. I've just moved some examples to github, so that it's clearer (and you can directly try the examples).
https://github.com/laurentlb/examples/tree/master/rules/empty

**Comment by laurentlb** [comment]
Examples are here: https://github.com/bazelbuild/examples
