### ISSUE TITLE
Document best practices for consuming autoconf/make C++ external dependencies

### ISSUE THREAD

**Issue by htuch** [bazelbuild/bazel#2814]
Currently, at https://bazel.build/versions/master/docs/external.html, there's a variety of guidance for consuming external deps, but none that is suitable for handling existing C++ deps. It's certainly not scalable and even valid advice in many cases to suggest that the consuming projects of a dependency just write a BUILD file that they keep up to date on a best effort basis that parallels the existing autoconf/make based build system.

As I discovered in https://github.com/bazelbuild/bazel/issues/2792, https://github.com/lyft/envoy/pull/716 and https://github.com/lyft/envoy/pull/747, there are a variety of approaches to encapsulating the autoconf/make process, with a `repository_rule` the cleanest way to do this. This should be a recommendation on https://bazel.build/versions/master/docs/external.html. In addition, we should have a simpler example, similar to https://github.com/lyft/envoy/pull/747 of how this is used. Currently, the only example in this vain is https://github.com/bazelbuild/bazel/blob/ac29b78000afdb95afc7e97efd2b1299ebea4dac/tools/cpp/cc_configure.bzl#L288, linked to from https://bazel.build/versions/master/docs/skylark/repository_rules.html, which is crazy complicated.

**Comment by steven-johnson** [comment]
I eagerly await progress on this front :-)

**Comment by buchgr** [comment]
@htuch thanks for the bug report and we love contributions :-).

**Comment by htuch** [comment]
@buchgr I've added to https://github.com/bazelbuild/bazel/issues/2792 the limitation of the `repository_rule` approach. I'll take an action item to do a PR to link to https://github.com/lyft/envoy/pull/747, but it's not exactly a clean example as a result of the issues described in #2792.

**Comment by buchgr** [comment]
cc: @mhlopko @lberki

**Comment by dslomov** [comment]
We need to work on a better autoconf approaches in the near future.

**Comment by prestonvanloon** [comment]
+1 

I am having a hard time understanding this rule and how it is used. I'm trying to import [gmplib](https://gmplib.org) which generates some headers as part of running `./configure`. Does `cc_configure()` achieve this? I was unable to get it to work after a brief attempt.

**Comment by mhlopko** [comment]
Preston: nope, `cc_configure` is a workspace rule that configures C++ toolchain (compiler, linker, flags...).

Try https://github.com/bazelbuild/rules_foreign_cc, they sound like what you need.

**Comment by dslomov** [comment]
See https://github.com/bazelbuild/rules_foreign_cc
