### ISSUE TITLE
Bazel Tests timeout on RHEL 7.3

### ISSUE THREAD

**Issue by YugandhaD** [bazelbuild/bazel#2818]
Hi,
Many Bazel Tests are timing out on RHEL 7.3.

Platform: x86
OS: RHEL 7.3
JDK : 8
Bazel Version: 0.4.4

'bazel info' command showed following version:
release: release 0.4.4-2017-04-12 (@80a07b5)

I could successfully build bazel 0.4.4 on RHEL 7.3, but when I tried to run tests with following command, many failed with timeout:
         `./compile.sh test /bazel/output/bazel`
Out of 154, 65 tests are failing with timeout issue.
I have attached the detailed log, and also a file which has list of all those tests.

[Bazel_0.4.4_x86_RHEL.docx](https://github.com/bazelbuild/bazel/files/919120/Bazel_0.4.4_x86_RHEL.docx)

[Bazel list of timing out tests.docx](https://github.com/bazelbuild/bazel/files/919123/Bazel.list.of.timing.out.tests.docx)

These tests fail similarly even if we run those tests individually with bazel command as shown in following example.
           `bazel  test //src/test/shell/bazel:bazel_coverage_test`
I tried increasing the timeout values but that also didn’t help.
There is no issue of insufficient memory or resources, as I am already working on high end VM, and all these tests have passed for me on Ubuntu VM, which had relatively lower configuration. 
Has anyone else faced this issue?  
Please let me know if there is some solution. 

Thanks & Regards
YugandhaD

**Comment by buchgr** [comment]
Could you try with bazel 0.4.5 please? The issue might have been fixed already. Please re-open this issue if the issue persists on 0.4.5

Thank you so much!

**Comment by YugandhaD** [comment]
Hi,

As per your suggestion, I tried to build and test Bazel 0.4.5 on RHEL 7.3.
However I am observing similar TIEMOUT errors. 
I don’t seem to have permissions to re-open the issue, could you please re-open and let me know your comments? 

Thanks & Regards,
YugandhaD
