### ISSUE TITLE
new_git_repository/git_repository should accept a commit hash and sha256 sum just like new_http_archive

### ISSUE THREAD

**Issue by bkase** [bazelbuild/bazel#2824]
Hi! I have a feature request: I believe {new_}git_repository as currently implemented is unsafe to use when you want to ensure reproducible builds. I would like to propose the following: `{new_}git_repository` should accept a `sha256` hash when a `tag` is provided OR it should also accept a commit hash.

### Description of the problem / feature request / question:

Problem: `new_git_repository` in WORKSPACE files only allows a `tag` to refer to a version in a git repo.
1. Without an associated sha256 hash, like `http_archive` this is unsafe because locations tags can be changed on a remote.
2. Sometimes you want to point to a specific commit and (assuming we don't care about SHA-1 collisions) this _is_ itself an immutable reference (unlike a version tag)

### If possible, provide a minimal example to reproduce the problem:

Let's say I depended on bazel at commit hash eecd7128f420b2d404ed2f42d549dea3bd198d9d

I would like to do:

```
new_git_repository(
  name = "bazel",
  remote = "https://github.com/bazelbuild/bazel.git",
  commit = "eecd7128f420b2d404ed2f42d549dea3bd198d9d",
  build_file = "BUILD.bazel"
)
```

instead I need to do:

```
new_http_archive(
  name = 'bazel',
  url = 'https://github.com/bazelbuild/bazel/archive/eecd7128f420b2d404ed2f42d549dea3bd198d9d.zip',
  sha256 = '<whatever the hash of this is>',
  strip_prefix = "bazel-eecd7128f420b2d404ed2f42d549dea3bd198d9d",
  build_file = "BUILD.bazel"
)
```

**Comment by pcj** [comment]
Not really seeing this as a problem... Why not just always use the commit?

**Comment by bkase** [comment]
Hmm I misunderstood the docs -- didn't realize you could pass a commit to `new_git_repository` (from https://bazel.build/versions/master/docs/be/workspace.html#new_git_repository).

Sorry, this seems fine! (but maybe it would be worth adding the commit as a parameter to `new_git_repository` docs)

**Comment by dslomov** [comment]
Relevant to WORKSPACE.lock proposal

**Comment by dslomov** [comment]
new_git_repositiory is no more
