### ISSUE TITLE
piping bazel query causes it to lose newlines

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/bazel#2826]
When piping the results of `bazel query` to another process (maybe `xargs bazel run`), the output of `bazel query` loses its newlines.

This is with bazel 0.4.5-homebrew.

Example:

```
$  bazel query 'kind(docker_build, //go/...)' 
//go/svc/hodgepodge:hodgepodge_prod
//go/svc/hodgepodge:hodgepodge_dev
//go/svc/convolabeler:convolabeler_prod
//go/cmd/https-sidecar:https-sidecar-prod
```

versus:

```
$  bazel query 'kind(docker_build, //go/...)' | xargs echo
//go/svc/hodgepodge:hodgepodge_prod //go/svc/hodgepodge:hodgepodge_dev //go/svc/convolabeler:convolabeler_prod //go/cmd/https-sidecar:https-sidecar-prod
```

**Comment by buchgr** [comment]
This is not a bug with bazel. 

xargs splits stdin by spaces by default. What you want is to split by newline instead.

```
bazel query 'kind(docker_build, //go/...)' | xargs -0
```

(echo is redundant since that's xargs default program. See `man xargs`).

**Comment by jmhodges** [comment]
🤦🏼‍♂️
