### ISSUE TITLE
java_proto_library not indexed by IntelliJ Bazel plugin

### ISSUE THREAD

**Issue by Ubehebe** [bazelbuild/bazel#2827]
Before Bazel released its own proto rules, I was using the third-party [rules_protobuf](https://github.com/pubref/rules_protobuf) proto rules. When I switched to the native proto rules, I discovered that my IDE (IntelliJ CE 2017.1 with Bazel plugin 2017.03.15.3) does not index the native java_proto_library targets, causing a lot of red squigglies, inability to navigate to proto gencode, etc.

Minimal repro: https://github.com/Ubehebe/java_proto_library_intellij_bug

I'm not sure if this is a bug in Bazel or the Bazel IntelliJ plugin, but either way, this will hinder adoption of the native java_proto_library rules.

**Comment by buchgr** [comment]
Thank you for your bug report @Ubehebe. This sounds like a bug in the intellij plugin. Mind opening an issue there? https://github.com/bazelbuild/intellij

Thanks!

**Comment by Ubehebe** [comment]
The reason I opened an issue here first is that it's likely caused by a missing action in the java_proto_library implementation. The rules_protobuf implementation of java_proto_library emits a regular java_library ([here](https://github.com/pubref/rules_protobuf/blob/master/java/rules.bzl#L126)), which is presumably why IntelliJ can index it. It's harder for me to understand the [Bazel implementation](https://github.com/bazelbuild/bazel/blob/59d2a6a8cdfcae1935a9e91ec329a6ff68fa7d5b/src/main/java/com/google/devtools/build/lib/rules/java/proto/JavaProtoLibrary.java) of java_proto_library.

@cgrushko, WDYT?

**Comment by cgrushko** [comment]
Internally, the native `java_proto_library` is supported by IntelliJ, so it should be easy to make it work in the external plugin as well.

Can you file a bug in https://github.com/bazelbuild/intellij and CC me? I'll try to find the right people for this.
