### ISSUE TITLE
How can I link a system library statically?

### ISSUE THREAD

**Issue by wjywbs** [bazelbuild/bazel#2828]
### Description of the problem / feature request / question:

How can I link a system library statically in mostly static mode (linkstatic=1)? I tried to use "-Wl,-Bstatic -lboost_thread -Wl,-Bdynamic" or "-Wl,-Bstatic", "-lboost_thread", "-Wl,-Bdynamic", but none of them worked. I don't want to hard code the path of libboost_thread.a in the system.

### If possible, provide a minimal example to reproduce the problem:

```
cc_binary(
    name = "main",
    srcs = [
        "main.cpp",
    ],
    linkopts = [
        "-lboost_thread",
    ],
)
```

```
ldd bazel-bin/main
linux-vdso.so.1
libboost_thread.so.1.54.0 => /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
...
```

### Environment info
* Operating System: Linux
* Bazel version (output of `bazel info release`): 0.4.5

###  Have you found anything relevant by searching the web?
http://stackoverflow.com/questions/6578484/telling-gcc-directly-to-link-a-library-statically

**Comment by buchgr** [comment]
The github issue tracker is for bugs, your's seems more like a usage question. Could you please ask this question on stackoverflow? We'll be happy to answer it there.

Please re-open if it's a bug indeed.

cc: @mhlopko
