### ISSUE TITLE
pls respect something like "make -j1"

### ISSUE THREAD

**Issue by toralf** [bazelbuild/bazel#2834]
At my Gentoo Linux build bot I do build N independend software package in parallel, each occupying usually 1 cpu. Bazel however spawns tons of java processes.
Is there any chance to let only 1 file at a time being built ?

**Comment by kchodorow** [comment]
You can specify `-j 1` as an argument to Bazel:

```
bazel build -j 1 //whatever
```

See `bazel help build`:

```
--jobs [-j] (an integer; default: "200")
```

**Comment by toralf** [comment]
ok, thx

**Comment by buchgr** [comment]
hey @toralf ... I think it would be valuable if you asked this question stackoverflow, so that other users can benefit as well. Thanks!
