### ISSUE TITLE
python/stub_template.txt doesn't work with virtualenv

### ISSUE THREAD

**Issue by kersson** [bazelbuild/bazel#2836]
### Description of the problem / feature request / question:

The change in 1cd2096284959ead26687d1d58b695d2abffb8e2 prevents `python/stub_template.txt` from working with virtualenvs because they rely on the python executable being launched from a particular place (the virtualenv location), and the python executable is simply a symlink back to the real executable, but it won't work if the symlink is followed back to the real executable.

Why do the symlinks need to be ignored anyway? Until it's possible to specify what python packages to install into a sandbox (which is basically just doing what virtualenv does) for running python tests, etc. I think this change should be reverted.

###  Have you found anything relevant by searching the web?
Related discussion: https://groups.google.com/d/msg/bazel-discuss/oRDudISQXjQ/MYKADEIvAQAJ

**Comment by aehlig** [comment]
Indeed, python's `os.path.isfile` is also true for symbolic links. So just returning a symlink should be fine. I also verifed that event with 1cd2096284959ead26687d1d58b695d2abffb8e2 reverted, bazel works fine on FreeBSD, despite `python` on path just being a symlink.

This whole part, however, will be reworked soon anyway, as the current approach of finding the interpreter locally (and hard-coding a #!-lines anyway) does not fit with remote execution.

/cc @philwo

**Comment by kersson** [comment]
>This whole part, however, will be reworked soon anyway, as the current approach ...  does not fit with remote execution.

Okay, cool.  In the meantime would you consider reverting the commit? 😇
