### ISSUE TITLE
How to load glob function in bzl file?

### ISSUE THREAD

**Issue by ldjhust** [bazelbuild/bazel#2837]
Hi, I want to use the `glob` function in `bzl` file, but it seems like that I can't use it directly. So how can I use it in `bzl` file? Or how can I use regular expression in `bzl` file?

Thanks very much for any help!

**Comment by kersson** [comment]
Use [`native.glob()`](https://bazel.build/versions/master/docs/skylark/lib/native.html#glob).

**Comment by ldjhust** [comment]
Thank you @kersson , I tried, but seems like that `native.glob()` also can't be accessed in `bzl` file. The error message is below:
```
ERROR: /Users/lency/Downloads/work/bazel_test/bazel_zc/assist_compile.bzl:4:20: Traceback (most recent call last):
	File "/Users/leodjli/Downloads/work/bazel_test/bazel_zc/assist_compile.bzl", line 7
		get_local_jar()
	File "/Users/leodjli/Downloads/work/bazel_test/bazel_zc/assist_compile.bzl", line 4, in get_local_jar
		native.glob(["libs/*.jar"])
The native module cannot be accessed from here. Wrap the function in a macro and call it from a BUILD file.
```

And my `bzl` file content:
```
local_jars = []

def get_local_jar():
    for jarfile in native.glob(["libs/*.jar"]):
        local_jars.append(jarfile)

get_local_jar()
```

**Comment by buchgr** [comment]
Hi @ldjhust ! Please ask this question and stackoverflow using the bazel tag and we'll be happy to answer it there, so that other users can also benefit. The github issue tracker is primarily used for bug reports. Thanks!
