### ISSUE TITLE
documentation layout breaks for some windows sizes

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#2839]
Open https://bazel.build/versions/master/docs/install.html

Resize the window to be 1050px wide.

Observed:
<img width="1147" alt="screen shot 2017-04-18 at 2 50 39 pm" src="https://cloud.githubusercontent.com/assets/360895/25131537/691ea192-2446-11e7-9d49-7b6e093ee9f1.png">

This is probably due to 2 media queries that are not using the same value (the one that collapses the nav, and the one that changes from a 2 column layout to a 1 column layout)

**Comment by jin** [comment]
This seems to be fixed.
