### ISSUE TITLE
PathFragment.equals should properly handle paths that are different but refer to the same directory

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#2842]
Currently, [PathFragment.equals](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/vfs/PathFragment.java#L762) simply checks that the paths are identical, but does not handle paths containing "./" or "../" segments. PathFragment should either handle this case, or explicitly not support such a case and provide an alternative that does.

Expected behavior:
```java
PathFragment frag1 = PathFragment.create("foo");
PathFragment frag2 = PathFragment.create("./foo");
frag1.equals(frag2) == false; // Should be true
```

Related to #2811.

**Comment by ulfjack** [comment]
You can call .normalize() on both fragments before comparing them.

**Comment by katre** [comment]
The problem isn't that we can't do that, it's that there are many places where we don't.

**Comment by ulfjack** [comment]
We have a lot of already-normalized PathFragments, and we certainly don't
want to call normalize on them again. Is there any particular issue you're
seeing?

**Comment by katre** [comment]
I originally filed this based on #2811, where LocalRepositoryLookupFunction is checking for path equivalence. Based on this discussion, I will close this issue and just fix the one call.
