### ISSUE TITLE
"local" tag suppresses remote caching

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#2844]
I think based on reading the code that setting "local" on a test prevents it from being cached remotely. Is this a bug or do we want this?

**Comment by damienmg** [comment]
I think that is working as intended, since we use to not have no-sandbox, we should probably mark the local tag to not deactivate sandboxing instead.

**Comment by ulfjack** [comment]
Anyone hitting this, I recommend against setting "local", and instead using some subset of the more specific tags "no-remote", "no-sandbox", "no-cache".
