### ISSUE TITLE
DashModule prints errors even when disabled

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#2847]
The DashModule is doing work and printing errors even when it's completely disabled, see e.g., DashModule.java line 217.

Damien tells me that we should delete it instead.

**Comment by ulfjack** [comment]
If we don't delete it, then we should make it so it doesn't register itself with the EventBus if the dash is disabled.

**Comment by damienmg** [comment]
I just deleted that code so closing this bug.
