### ISSUE TITLE
Adding a dependency to a spawnaction does not transitively add sub dependencies

### ISSUE THREAD

**Issue by dmaclach** [bazelbuild/bazel#285]
I was creating a spawnaction using and calling setExecutable(FilesToRunProvider executableProvider)

https://github.com/google/bazel/blob/5fe79331f9160ae8b37f907ddbaa5f080dfc8185/src/main/java/com/google/devtools/build/lib/analysis/actions/SpawnAction.java#L681

The executableProvider was a sh_binary that depended on some data something like

sh_binary {
name="foo",
srcs = [ "foo.sh" ],
data = [ ":foodata" ],
}

genrule {
name = "foodata",
outs = [ "somedata" ],
...
}

when my spawn action was actually created it did not end up collecting up somedata as part of its inputs. I had to 
.addInput(":foodata") directly. 

This seems very fragile and unexpected to me. Shouldn't the spawnaction be collecting sub-dependencies?

**Comment by hanwen** [comment]
the expllicit addInput() is not the right fix: you can't do this transitively. Imagine that you have a couple of levels of genrules/sh_binary stacked together, then you won't be able to delve down into the dependencies. I imagine somehting else is amiss.

If you show us (internally or externally) a bit of code, we can give more specific advice.

**Comment by hanwen** [comment]
closing for lack of feedback.

**Comment by dmaclach** [comment]
Hey hanwen. Sorry for the delay on this.

Take a look at 
https://github.com/bazelbuild/bazel/blob/master/tools/objc/BUILD#L34. 
Note that it depends on realpath. For my spawnaction that was created at 
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/objc/BundleSupport.java#L303
I had to add a explicit dependency, or the spawnaction never seemed to pick up realpath.

**Comment by hanwen** [comment]
you mena ? https://github.com/bazelbuild/bazel/blob/master/tools/objc/BUILD#L49

I don't see where realpath is defined? It's also not a file in the directory. How does this work?

**Comment by dmaclach** [comment]
realpath gets copied in there as part of compile.sh

https://github.com/bazelbuild/bazel/blob/master/compile.sh#L116

**Comment by dmaclach** [comment]
hanwen@ any thoughts?

**Comment by hanwen** [comment]
Sorry for the delay.

Is there a repro scenario that I could run?

when running ibtoolwrapper, the shell-script should be able to find its
dependencies under the runfiles, ie.

  $0.runfiles/{WORKSPACE_NAME}/tools/objc/ibtoolwrapper.sh



On Thu, Oct 22, 2015 at 5:44 PM, dmaclach <notifications@github.com> wrote:

> hanwen@ any thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bazelbuild/bazel/issues/285#issuecomment-150267086>.
>



-- 
Han-Wen Nienhuys
Google Munich
hanwen@google.com

**Comment by damienmg** [comment]
Ping?

**Comment by hanwen** [comment]
the misunderstanding was clarified in my last comment.

Dave, what about the shell script code? Did you get that fixed?

**Comment by hanwen** [comment]
I'm closing this issue, as it's WAI. Let's have any discussion of refactoring the OSX scripts on another bug.
