### ISSUE TITLE
bazel build failing with missing dependency declarations

### ISSUE THREAD

**Issue by PranavSathy** [bazelbuild/bazel#2852]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I am attempting to build a go_binary after switching from fish shell to zsh on my machine. The command I am running is:

`bazel build //core/archon`

The output is:

`
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_sathyp/5c3f987840c2e4c7bdb38ead7742430b/external/com_github_google_protobuf/BUILD:334:1: undeclared inclusion(s) in rule '@com_github_google_protobuf//:protoc':
this rule is missing dependency declarations for the following files included by 'external/com_github_google_protobuf/src/google/protobuf/compiler/main.cc':
  '/Library/Developer/CommandLineTools/usr/lib/clang/8.1.0/include/stdarg.h'
  '/Library/Developer/CommandLineTools/usr/lib/clang/8.1.0/include/stddef.h'
  '/Library/Developer/CommandLineTools/usr/lib/clang/8.1.0/include/__stddef_max_align_t.h'
  '/Library/Developer/CommandLineTools/usr/lib/clang/8.1.0/include/stdint.h'
  '/Library/Developer/CommandLineTools/usr/lib/clang/8.1.0/include/limits.h'.
Target //core/archon:archon failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.582s, Critical Path: 4.35s
`

### If possible, provide a minimal example to reproduce the problem:

N/A

### Environment info
* Operating System:
macOS 10.12.4

* Bazel version (output of `bazel info release`):
release 0.4.5-homebrew

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
N/A

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

No, only old articles about CROSSTOOL from 2015/2016.

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

This used to work when I ran the command on fish shell, I recently uninstalled fish shell and switched to utilizing zsh installed via homebrew.

**Comment by aehlig** [comment]
Do you have any other shells do you have installed on your system, in particular, which shell is `/bin/sh` now (and `/bin/bash` if that file exists)? While it is a known issue that a lot of the bazel code assumes that every shell is a Bourne Again Shell, I am a bit surprised that we pick up the default shell, if it is not named `bash` or `sh` (actually, the name `/bin/bash` is even hard-coded at many places), especially as it worked with the fish shell, which also differs from bash, as far as I know.

If you have bash installed on your system, does setting `BAZEL_SH` to the absolute path to the bash binary help?

**Comment by PranavSathy** [comment]
I have all the default shells that come on macOS (including zsh) and then I installed zsh again via Homebrew.

Setting `BAZEL_SH=/bin/bash` solved the problem for me! Before I did that, I ran

`echo $BAZEL_SH` and the result was empty. Shouldn't installing bazel via Homebrew set the `BAZEL_SH`?
