### ISSUE TITLE
bazel doesn't support build a signed release apk

### ISSUE THREAD

**Issue by ldjhust** [bazelbuild/bazel#2854]
Hi guys, I want to build a release apk that signed with my release keys. Howevey, I can't find any rule about `keystore` in bazel's doc or any parameter about signature in `android_binary`'s parameters. So does bazel doesn't support build a release apk that signed with release keys?

**Comment by ldjhust** [comment]
already solved

**Comment by aj-michael** [comment]
@ldjhust, for future people who encounter this, what is your solution?

**Comment by ldjhust** [comment]
OK @aj-michael , the [bazel-discuss mailing list](https://groups.google.com/forum/#!topic/bazel-discuss/2BPWVRnsiGc) has already discussed this question and provided a solution with some background.
