### ISSUE TITLE
Bazel's error messages are sometimes ridiculously useless

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#2855]
I was just trying to test some of my changes via "bazel test", when Bazel stopped working and suddenly couldn't build anything at all. I know the bug is probably in my new code, but the uselessness of error messages makes it nearly impossible to debug this:

```
philwo-macbookpro:bazel-test philwo$ bazel build -s --verbose_failures //src:bazel
INFO: Reading 'startup' options from /Users/philwo/.bazelrc: --watchfs
INFO: Analysed target //src:bazel (0 packages loaded).
INFO: Found 1 target...
ERROR: Process exited with status 127
Target //src:bazel failed to build
INFO: Elapsed time: 0.252s, Critical Path: 0.01s
FAILED: Build did NOT complete successfully
```

It prints 7 lines, none of which are remotely helpful here.

Some open questions:
- Which "process" that supposedly exited with status 127 is Bazel referring to here?
- If Bazel tried to launch a process, why isn't it printing any command-line even though I use "-s"?

I understand that we don't want to annoy users with stack traces when the build failed due to a syntax error in their own code. But after another hour of debugging Bazel failing with "Failure due to failure in a failing component that is totally not Bazel, haha, oh wait, I have another hint for you: Somewhere some code threw an IOException! But I won't print any more info, because stack traces are ugly and UX!" I'm slightly annoyed.

As a Bazel developer, this terseness of error messages has killed my productivity often enough that I'll try to improve this now...

![trace_all_the_stacks](https://cloud.githubusercontent.com/assets/504652/25238072/a7df7f12-25ec-11e7-8a77-52c87a61c330.png)

**Comment by philwo** [comment]
FWIW, this particular issue turned out to be the line "build --workspace_status_command=/bin/true" in my ~/.bazelrc, but macOS has no /bin/true, instead it is in /usr/bin/true.

**Comment by keir** [comment]
I concur. I am currently fighting Bazel errors and have no way to debug. For example, I am trying to create a BUILD for an external dependency, and a file is not compiling due to being unable to find an include. When I run with -s, it looks like everything should work, but it doesn't. Sigh.
