### ISSUE TITLE
Default to including debug information in all Java binaries

### ISSUE THREAD

**Issue by brendandouglas** [bazelbuild/bazel#2859]
See https://github.com/bazelbuild/intellij/issues/78.

Seems that Bazel should be doing this by default (e.g. adding --javacopt=-g to default build flags).

**Comment by cushon** [comment]
The internal [`java_toolchain.misc`](https://bazel.build/versions/master/docs/be/java.html#java_toolchain.misc) includes `-g`; updating Bazel's to match sounds good to me: https://github.com/bazelbuild/bazel/blob/2ce304aebe95b9e377fc9d1e0d9f1dd5ebfdd60d/tools/jdk/BUILD#L152

**Comment by ittaiz** [comment]
Is this a big/complex task?

**Comment by ittaiz** [comment]
Friendly ping. Is this big?

**Comment by ittaiz** [comment]
thanks!
