### ISSUE TITLE
c++ compilation not linking correctly

### ISSUE THREAD

**Issue by ajorgensen** [bazelbuild/bazel#286]
I am trying to setup a build for a c++ library on osx but am running into an issue. The source bundled up into a tarball and I have a genrule that looks something like this:

```
genrule(
  name = "library-source",
  srcs = [ lib.tar.gz ],
  outs = [ "include/header-file.h" ],
  cmd = "\n".join([
        "export TMPDIR=$$(mktemp -d -t glog.XXXXX)",
    "export INSTALLDIR=$$(pwd)/$(@D)",
    "mkdir -p $$TMPDIR",
    "cp -R $(SRCS) $$TMPDIR",
    "cd $$TMPDIR",
    "tar xvfz " + package_file,
    "cd " + package_dir,
    "./configure --prefix=$$INSTALLDIR --enable-shared=no",
    "make install",
    "rm -rf $$TMPDIR
  ])
```

The results of this looks something like:

```
Undefined symbols for architecture x86_64:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::find(char const*, unsigned long, unsigned long) const", referenced from:
      google::XMLText(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libgflags.a(gflags_reporting.cc.o)
      google::HandleCommandLineCompletions()      in libgflags.a(gflags_completions.cc.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::find(char, unsigned long) const", referenced from:
      google::HandleCommandLineCompletions()      in libgflags.a(gflags_completions.cc.o)
 ```

It looks like the standard library is not getting linked. I have tried setting CXX="/usr/local/bin/g++". I have also installed gcc and related libraries that are installed by xcode are not in my path.

```
g++ --version
    g++ (Homebrew gcc48 4.8.4) 4.8.4
```

The build configuration works on some colleagues machines and I cant figure out what the difference in our environments are. I am able to run the steps in the genrule manually and the project will compile just fine. It seems to be something bazel is doing to either my environment or the arguments that are being passed to g++ that are causing the standard library not to be linked in.

Has anyone seen this before?

**Comment by hanwen** [comment]
you can run your compile with 

  bazel build -s my:target

this will print the exact commands issued, which may help you diagnose things.

FWIW, running configure/make from within a genrule is highly unusual; isn't the .h file directly in the tarball anyway?

**Comment by ajorgensen** [comment]
I believe this is the commands thats being run when the error occurs:

```
/bin/sh ./libtool --tag=CXX   --mode=link g++ -D_THREAD_SAFE     -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare  -DNO_FRAME_POINTER  -g -O2 -D_THREAD_SAFE   -o logging_unittest  logging_unittest-logging_unittest.o  libglog.la  -lgflags    -lgflags -lpthread
libtool: link: g++ -D_THREAD_SAFE -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -DNO_FRAME_POINTER -g -O2 -D_THREAD_SAFE -o logging_unittest logging_unittest-logging_unittest.o -Wl,-bind_at_load  ./.libs/libglog.a -lgflags -lpthread
```

I'm still understanding how bazel works so its highly likely I did something that is unconventional. Would the more conventional case here be to extract the tarball in the genrule, add the src and hearder in `cc_library` and have that take care of building?

I guess a more general question would be is there a process for taking a tarball and building from the stuff inside of it or is it recommended that its extracted first and then the build run?

**Comment by hanwen** [comment]
normally, you would either install the library outside of your tree manually, or and include as if it were a library from your system (using -I flags in the cflags and "-llib" as linkopts) or extract it into your source tree and write BUILD files.

**Comment by ajorgensen** [comment]
Ok I can try that. Is there anything I can do to figure out why the ./configure and make steps wouldn't work in the genrule? As mentioned it worked on a co-workers machine which tells me its an environment thing but I can get it to build fine when I isolate my path to just /usr/local/bin and run configure and make outside of bazel. I'm at a bit of a loss at how to diagnose what exactly is going on. Printing out the versions of g++ etc in the genrule seems to indicate that the environments inside and outside bazel are the same but clearly I am missing some piece.

**Comment by hanwen** [comment]
if you run with -s , you 'll notice that the command is run as 

(cd /..something../ && \
  exec env - \


the 'env' command strips the environment. This is done so commands are reproducible.

**Comment by kayasoze** [comment]
I've found that on some machines env /bin is missing from the env supplied PATH.  This may cause some autotool based genrules to fail.  You could add "export PATH=$$PATH:/bin &&" to the beginning of your cmd.  I'd at least echo $PATH to compare them across environments.

**Comment by damienmg** [comment]
Obsolete
