### ISSUE TITLE
Extract legacy features from CppConfiguration to CROSSTOOLs

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#2868]
Currently we patch in missing features and action_configs into toolchains ([CppActionConfigs](https://github.com/bazelbuild/bazel/blob/50d62ee7888856f935d09e5fd60ee23d24d02b44/src/main/java/com/google/devtools/build/lib/rules/cpp/CppLinkActionConfigs.java), [CppConfiguration](https://github.com/bazelbuild/bazel/blob/0d3d5ae35650b23cb6c1a232342ec51dc88728c2/src/main/java/com/google/devtools/build/lib/rules/cpp/CppConfiguration.java#L826)). All these should be in crosstools, Bazel shouldn't need to know about Linux C++ specifics. And for example windows crosstool has to contain empty feature just to prevent patching.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
