### ISSUE TITLE
Cannot compile bazel from head using bazel release 0.4.5

### ISSUE THREAD

**Issue by erain** [bazelbuild/bazel#2869]
### Description of the problem / feature request / question:

I cannot use the release version of Bazel (0.4.5) to compile Bazel source code from head in Ubuntu 16.04. 

### If possible, provide a minimal example to reproduce the problem:

``` shell
git clone https://github.com/bazelbuild/bazel.git
cd bazel
./compile.sh compile /usr/bin/bazel
...
ERROR: /home/yiyu/opt/bazel/src/java_tools/junitrunner/java/com/google/testing/coverage/BUILD:61:1: Java compilation in rule '//src/java_tools/junitrunner/java/com/google/testing/coverage:bitfield' failed: Worker process sent response with exit code: 1.
Fatal Error: Unable to find package java.lang in classpath or bootclasspath
```

### Environment info
* Operating System:
Ubuntu 16.04

* Bazel version (output of `bazel info release`):
release 0.4.5

**Comment by damienmg** [comment]
Does `bazel build //src:bazel` works? Which version of java is installed?

**Comment by erain** [comment]
I just realized (by [this](https://bazel.build/designs/2016/10/11/distribution-artifact.html)) that `./compile.sh compile <bazel-binary-path>` is no longer supported for dev version of Bazel. I tried `bazel build //src:bazel` and it worked. 

I will close this issue, and thanks Damien for helping!
