### ISSUE TITLE
Need standard way to propagate data from targets

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/bazel#2878]
When defining a rule, I wish we had an extra field to _"**tag**"_* it (add some kind of property that other rules may read) so that custom rules may read it and use it to identify rules that require special care.

In general - a [common attribute to all rules](https://bazel.build/versions/master/docs/be/common-definitions.html) that its value will be readable to other rules that depends on this target.

### minimal example of need
Consider the following simplified use case:
```python
java_library(
  name = "foo",
  srcs = ["MyFoo.java"],
)

java_library(
  name = "bar",
  resources = ["db.xml.erb"],
  tags = ["config"]
)

my_packager(
   name = "pack",
   deps = [":foo",":bar"],
)
```
In my implementation of `my_packager` I want to iterate over all deps and find deps with tag `"config"` so I'll put the config files somewhere else within the package.

### reference
I've asked this question in SO:
http://stackoverflow.com/questions/43169201/in-skylark-given-label-how-to-read-the-tags-of-the-original-rule

Seems like `rules_scala` does something very close:
https://github.com/bazelbuild/rules_scala/blob/master/scala/scala.bzl#L414
(even though `extra_information` is not a valid input.

---
\* I know that `tags` is already reserved for[ other uses,](https://bazel.build/versions/master/docs/be/common-definitions.html#common.tags) but I couldn't find a better name for this use case.

**Comment by dslomov** [comment]
You can use aspects to achieve what you want:  add an aspect on `deps` attribute of `my_packager` that will read `tags` and provide the information you need in a provider.

See https://bazel.build/versions/master/docs/skylark/aspects.html
