### ISSUE TITLE
--aspects flag isn't documented

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#2880]
`bazel help build` doesn't document the `--aspects` flag but it is accepted and used here:

https://bazel.build/versions/master/docs/skylark/aspects.html#applying-aspects-from-command-line

**Comment by endobson** [comment]
In addition the `--output_groups` flag which is more or less necessary to use in conjunction is also not documented.

**Comment by dslomov** [comment]
Now it is: https://docs.bazel.build/versions/master/command-line-reference.html#flag--aspects
