### ISSUE TITLE
skylark: rule.output function patterns that expand to >1 file cause an error

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#2881]
Implicit output patterns defined in Skylark are artificially restricted to expand to at most one file.  No such restriction exists for native rules such as proto_library.  Consider:

```
$ cat t/BUILD 
proto_library(
    name = "a_proto",
    srcs = [
        "a.proto",
        "b.proto",
    ],
    cc_api_version = 2,
)

load(":inc.bzl", "my_proto_library")

my_proto_library(
    name = "my_proto_library",
    srcs = [
        "a.proto",
        "b.proto",
    ],
)

$ cat t/inc.bzl 

def _implicit_outputs(srcs):
  return {"": "%{srcs}.pb.go"}

def _implementation():
  pass

my_proto_library = rule(
    outputs = _implicit_outputs,
    implementation = _implementation,
    attrs = {
        "srcs": attr.label_list(),
    },
)

$ blaze query -k 'kind(generated, t:*)'
ERROR: google3/t/BUILD:12:1: google3/t/inc.bzl:8:20: expected one element but was: <a.pb.go, b.pb.go>
//t:b.proto.h
//t:b.pb.h
//t:b.pb.cc
//t:a.proto.h
//t:a.pb.h
//t:a.pb.cc
```

Notice that the native proto_library's outputs expand to [a.pb.h b.pb.h], but Blaze reports an error when my_proto_library tries to do the same thing using the "%{srcs}.pb.go" rule.  I don't know why this restriction exists, but clearly it is an obstacle to Skylark rules achieving parity with native rules.

Changing my_proto_library to use a dict {"": "%{srcs}.pb.go"} instead of a function causes Blaze to emit the same error (and crash while doing so).

**Comment by dslomov** [comment]
(this issue originally reported by @alandonovan

**Comment by c-parsons** [comment]
Lets close this, as I believe it's covered under https://github.com/bazelbuild/bazel/issues/6241
In short, we're going to remove the `output` parameter of `rule()` altogether.
