### ISSUE TITLE
 skylark: existing_rule is underspecified 

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#2884]
(originally reported by @alandonovan)
The documentation for the existing_rule function doesn't specify what its result contains.  It should answer the following questions:

Does it contain only explicitly specified attributes, or does it also include defaults for missing ones?  (Seems to be the latter.)

Are the values for explicitly specified attributes identical to the ones passed to the rule constructor function, or are they new data structures converted back from some canonicalized internal representation?  (Seems to be the latter.)

If the latter, what exact form does each rule attribute take?  For example, are labels represented by  Labels or by strings, and if by strings, are they in absolute (//x:y or //x) or relative (:y or y) form?  Are attribute lists represented by Skylark lists or tuples?  What about Tristates?  And so on.

**Comment by alandonovan** [comment]
Fixed by CL 279390031 (see b/36532401).
