### ISSUE TITLE
Windows: bootstrapping doesn't work under Cygwin

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2885]
Related to https://github.com/bazelbuild/bazel/issues/2725

Bootstrapping doesn't work under Cygwin.

I already discovered the following problems and fixed them in a pending change (https://bazel-review.googlesource.com/c/10470/):
- the bootstrap scripts don't expect `uname` to return "cygwin*"
- `JAVA_HOME` default value in `scripts/bootstrap/buildenv.sh` is computed using msys path (`/c/...`) instead of cygwin path (`/cygdrive/c/...`)
- we pass `${PWD}` as `--client_cwd` and `--workspace_directory` in `scripts/bootstrap/compile.sh:run_bazel_jar` but `WindowsFileSystem.java` doesn't understand `/cygdrive/c/...` and attempts to make it relative to the MSYS root (`c:/cygwin64/`) but this doesn't exist

**Comment by dslomov** [comment]
Lowering the prio as it is just bootstrapping

**Comment by laszlocsomor** [comment]
Lowering the prio because we don't support Cygwin because of #2810.
