### ISSUE TITLE
Aspect example isn't doing what is reasonably expected when generating output file names

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#2886]
https://bazel.build/versions/master/docs/skylark/aspects.html#implementation-functions

The code in question:
```
 outputs = [ctx.new_file(f.short_path + ".metal")
               for f in proto_sources]
```

Reading this I would expect this to generate files in the same directory as the proto sources but with a longer suffix. Instead since `short_path` is `The path of this file relative to its root.` but `ctx.new_file` says it `Creates a file object with the given filename, in the current package.`, this results in the package path getting duplicated in the resulting output.

https://bazel.build/versions/master/docs/skylark/lib/File.html#short_path
https://bazel.build/versions/master/docs/skylark/lib/ctx.html#new_file(filename)

**Comment by abergmeier-dsfishlabs** [comment]
Can we please rewrite the aspect docs from scratch? I may be not the brightest but I feel like there is a lot of information that is either not in the docs or with the current "structure" I am missing.

**Comment by dslomov** [comment]
I am working on making docs better (hopefully; this also involves making API better), but I am not planning any major structure changes.
Any concrete ideas on what I could change?

**Comment by abergmeier-dsfishlabs** [comment]
From the top of my head:

- Go through the different steps the aspects are applied to the graph.
- Explicitly state in which order they will be executed
- More structured information - less prose writing.
- All references to **A(...)** need to stand out.
- Display information passing/providers in graphic
- Actually consume `metal_proto` somewhere
- Document how information is passed. I think it relies on the attrs of the rules and can only be passed through them and not directly in the aspect arcs.

**Comment by dslomov** [comment]
Thanks, I understand what you want a bit better now. I have a couple of things I still don't follow in what you suggest:
> * Go through the different steps the aspects are applied to the graph. There have to be at least 3 more substeps to show.

I am not sure what you mean by "3 substeps". For all intents and purposes [this build graph](https://bazel.build/versions/master/docs/skylark/build-graph-aspects.png) appears instantaneously  when you apply aspect A to target X...
> * Explicitly state in which order they will be executed
... and the build graph is then reduced in the same way build graphs are reduced in [analysis phase](https://bazel.build/versions/master/docs/skylark/concepts.html#evaluation-model)

Maybe evaluation model just need more pictures? :)

**Comment by abergmeier-dsfishlabs** [comment]
> I am not sure what you mean by "3 substeps". For all intents and purposes this build graph appears instantaneously when you apply aspect A to target X...

The shadow-graph may be instantaneously, if you apply. Since you do not get any feedback, I think it would be good to explicitly describe that e.g. **A(W)** aspect gets instantiated before **A(Y)**.

Especially passing information between aspects could be more explicitly described IMO.

> Maybe evaluation model just need more pictures? :)

Yes, more pictures, arcs and better labels would help a lot :)

**Comment by pcj** [comment]
@abergmeier-dsfishlabs Not sure if it will augment your understanding of aspects but I wrote up my experience at https://github.com/pcj/bazel_aspects.

@dslomov If you can swing it, an animated visualization of how the aspect graph is created and then reduced, showing how information is propagated would be awesome.

**Comment by abergmeier-dsfishlabs** [comment]
> Not sure if it will augment your understanding of aspects but I wrote up my experience at https://github.com/pcj/bazel_aspects.

Won't anymore, but it helped understanding aspects. Thanks.

**Comment by dslomov** [comment]
Re original request, on second thought I actually think it is fine as is.
The output files of the metal_proto_aspect should reflect to source proto structure and that is what happens here.
