### ISSUE TITLE
Bazel recompiles Everthing from scratch

### ISSUE THREAD

**Issue by karanaggarwal1994** [bazelbuild/bazel#2889]
Whenever I build tensorflow it again recompile everything which takes a lot of time. Is there a way to prevent this??

**Comment by vladmos** [comment]
Hi. Could you please provide a bit more details? Do you change anything between consequent builds?

**Comment by jin** [comment]
Closing this as issue is stale. @karanaggarwal1994 please reopen the issue if you have an reproducible example for us to investigate. Thanks.
