### ISSUE TITLE
Windows: TensorFlow is failing due to local_python_config

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2892]
http://ci.bazel.io/job/TensorFlow/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-msvc-x86_64/795/console

In https://github.com/tensorflow/tensorflow/commit/7933420df6700e8037da7f06c9cd8e0121fb769a, TensorFlow started to use python_config.bzl to replace python_config.sh

Unfortunately, it didn't work well on Windows.

At https://github.com/tensorflow/tensorflow/blob/master/third_party/py/python_configure.bzl#L65 , `dir` is used to list all the headers under the python include directory.

But Bazel found `C:\tools\msys64\usr\bin\dir.exe` instead of the default `dir` in cmd.exe, which doesn't accept `/b /s` options.

I tried to set a PATH not containing MSYS (even an empty path) when invoking `repository_ctx.execute`, but still it found the wrong `dir`.

More bugs I found in `python_config.bzl`
1. Trys to create junction to a file : https://github.com/tensorflow/tensorflow/blob/master/third_party/py/python_configure.bzl#L85
2. Using `&&` to concatenate all the commands for `cmd.exe`: https://github.com/tensorflow/tensorflow/blob/master/third_party/py/python_configure.bzl#L93

Since I will be on vacation starting tomorrow, I probably don't have enough time to solve this.

//cc @laszlocsomor @damienmg @vladmos Can you help with this issue?

**Comment by laszlocsomor** [comment]
For the record, getting around the `dir` problem is:

    $WINDIR/system32/cmd.exe /C dir /b /s

**Comment by laszlocsomor** [comment]
I'll take a look tomorrow.

**Comment by laszlocsomor** [comment]
FYI, sent PR: https://github.com/tensorflow/tensorflow/pull/9510

**Comment by laszlocsomor** [comment]
PR was merged, this bug should now be fixed.

**Comment by damienmg** [comment]
Ok rerunning the job on CI

**Comment by damienmg** [comment]
Still failing

**Comment by laszlocsomor** [comment]
I could repro locally, taking a look now.

**Comment by damienmg** [comment]
:) Not submitted to tensorflow yet :)

**Comment by damienmg** [comment]
Github you are crazy, should only mark bug as fixed when merged to upstream...

**Comment by laszlocsomor** [comment]
I marked it closed... :)

**Comment by laszlocsomor** [comment]
Oops, I see what you meant...

**Comment by damienmg** [comment]
It is not your fault, Github mark bug as closed as soon as it is in any branch anywhere :(

**Comment by damienmg** [comment]
So off line discussion with @laszlocsomor: he found the issue, and will fix it on monday. Downgrading to P2 since it is not on bazel side.

**Comment by laszlocsomor** [comment]
Reopening, not merged to upstream yet.
