### ISSUE TITLE
Support for Ubuntu 17.04

### ISSUE THREAD

**Issue by chaitanya9186** [bazelbuild/bazel#2896]
After upgrading my ubuntu from 16.04 to 17.04, bazel builds are not working as before.

Distributor ID: Ubuntu                                                                                                                                
Description:    Ubuntu 17.04                                                                                                                          
Release:        17.04                                                                                                                                 
Codename:       zesty

**Comment by vladmos** [comment]
Hi. Could you please describe how exactly is the new behavior different?

**Comment by jin** [comment]
Closing due to lack of information.
