### ISSUE TITLE
There is no documentation in the User Manual for --workspace_status_command

### ISSUE THREAD

**Issue by jayeye** [bazelbuild/bazel#2898]
The [Command Line Reference](https://bazel.build/versions/master/docs/command-line-reference.html) has:
--workspace_status_command=<path> default: ""
A command invoked at the beginning of the build to provide status information about the workspace in the form of key/value pairs. See the User's Manual for the full specification.

However, the [User Manual](https://bazel.build/versions/master/docs/bazel-user-manual.html) has no mention of the workspace_status_command. Indeed, searching for --workspace_status_command from the bazel site searchbox returns only the command line reference entry.

**Comment by htuch** [comment]
https://github.com/bazelbuild/bazel/issues/2893 also is related.

**Comment by ixdy** [comment]
This seems to be a continuing source of confusion, especially regarding the `stable-status.txt` vs. `volatile-status.txt` split for custom values, which is basically tribal knowledge.

How to actually stamp artifacts varies by language, though `rules_go` and `rules_docker` have started to standardize around replacing `{FOO}` in certain names/identifiers with the appropriate workspace status value.

**Comment by htuch** [comment]
Is this now resolved in https://docs.bazel.build/versions/master/user-manual.html#workspace_status?

**Comment by mhlopko** [comment]
@laszlocsomor is the best!
