### ISSUE TITLE
No toolchain found for cpu 'armeabi'

### ISSUE THREAD

**Issue by ldjhust** [bazelbuild/bazel#2900]
Hi guys, When I building my android project with bazel, it failed with the following error:
```
ERROR: No toolchain found for cpu 'armeabi'. Valid cpus are: [
  darwin,
  armeabi-v7a,
  x64_windows_msvc,
  s390x,
  ios_x86_64,
].
```

What's the problem here?

I'm using this build command:
```
bazel build --jvmopt="Server 4G" --cpu=armeabi //:apk --strategy=AndroidAapt=standalone
```

My bazel version is:
```
Build label: 0.4.5-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 13:39:33 2017 (1489671573)
Build timestamp: 1489671573
Build timestamp as int: 1489671573
```

And my system is macOS Sierra 10.12.4.
Thanks very much for any help!

**Comment by ldjhust** [comment]
Hi @aj-michael , do you have any idea about what's going on here?

Thanks very much!

**Comment by aj-michael** [comment]
Hi @ldjhust , unfortunately our documentation for building android_binary with JNI is lacking. @ahumesky is working on fixing that.

Two things that I hope will help you out:

1. The flag that you want to use to determine which architectures we build the JNI code for in your apk is `--fat_apk_cpu`. It takes a comma-separated list of architectures. E.g. `blaze build --fat_apk_cpu=x86,armeabi-v7a` will build an APK with native libraries for both x86 and arm 32 bit devices.

2. The default architecture that we build for if you don't specify any flags is armeabi-v7a. So if you build with no flags and the use `zipinfo` on your APK, you should see `libs/armeabi-v7a/apk.so`.

**Comment by ldjhust** [comment]
Thanks @aj-michael , but the error shows that there are only: `darwin,
  armeabi-v7a,
  x64_windows_msvc,
  s390x,
  ios_x86_64` cpus, and doesn't has `x86` or `armeabi`, does this is my system's problem?

**Comment by ldjhust** [comment]
bazel build --jvmopt="Server 4G" --fat_apk_cpu=x86 //:qzone_apk --strategy=AndroidAapt=standalone
....................
ERROR: No toolchain found for cpu 'x86'. Valid cpus are: [
  darwin,
  armeabi-v7a,
  x64_windows_msvc,
  s390x,
  ios_x86_64,
].

**Comment by aj-michael** [comment]
Hmm, are you sure that `//:qzone_apk` is an `android_binary` rule? Also, do you have an `android_ndk_repository` rule in your WORKSPACE? those CPUs are the options for non-android rules.

**Comment by ldjhust** [comment]
Yes, the `//:qzone_apk` is an `android_binary`:
```
android_binary(
    name="qzone_apk",
    custom_package = "com.xtbc",
    manifest = "AndroidManifest.xml",
    resource_files = glob(["res/**"], exclude=["res/.DS_Store"]),
    assets = glob(["assets/**"], exclude=["assets/.DS_Store"]),
    assets_dir = "assets",
    deps = [
        ":lib",
        ":jni"
    ]
)
```

And the `:jni` rule is:
```
cc_library(
    name = "jni",
    srcs = glob(["libs/armeabi/*.so"])
)
```

Cause they are prebuilt `.so` file, so I didn't have the `android_ndk_repository` rule in my WORKSPACE. Am I wrong?

**Comment by aj-michael** [comment]
Hmmm, I'll have to let @ahumesky answer that. He is more knowledgable about JNI. Bazel's typical use case is to build the cc_library from source files.

**Comment by ldjhust** [comment]
OK, thanks very much!

**Comment by ahumesky** [comment]
This is similar to the issues discussed here: https://github.com/bazelbuild/bazel/issues/2851#issuecomment-296025329

Try passing `--android_cpu=armeabi --fat_apk_cpu=""`

If you want to be able to use `.so` files for multiple architectures, see the discussion in the comment linked above.

**Comment by ldjhust** [comment]
```
bazel build --jvmopt="Server 4G" //:qzone_apk --strategy=AndroidAapt=standalone --android_cpu=armeabi --fat_apk_cpu=""
.............
ERROR: No toolchain found for cpu 'armeabi'. Valid cpus are: [
  darwin,
  armeabi-v7a,
  x64_windows_msvc,
  s390x,
  ios_x86_64,
].
```

@ahumesky looks like it not works for me, I also refered to the issue and changed my `cc_library` to this:
```
config_setting(
  name = "android_x86",
  values = {
    "android_cpu": "x86",
  }
)

cc_library(
    name = "jni",
    srcs = select({
    ":android_x86": glob(["libs/armeabi/*.so"])
  }),
)
```

But it still failed with the same error.

**Comment by ldjhust** [comment]
Thanks guys, I found the reason. Though, I'm using the prebuilt `.so` file, I still need to have the `android_ndk_repository` rule in my WORKSPACE file, or bazel will fail with the above error.

Thanks very much for the help again!
