### ISSUE TITLE
Filegroup lead to unexpected data_runfiles

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2901]
### Description of the problem / feature request / question:
Filegroups `srcs` are exposed as `data_runfiles` in an aspect. This is unexpected IMO because I did not specify the explicit `data` attribute. 

### If possible, provide a minimal example to reproduce the problem:

    filegroup(
        name = "foo",
        srcs = [
            "foo1.cpp", # This will be a file in `data_runfiles`
        ],
    )

### Environment info
* Operating System: Ubuntu 16.04
* Bazel version (output of `bazel info release`): 0.4.5

###  Have you found anything relevant by searching the web?
Original question here: https://stackoverflow.com/questions/43654278/unexpected-data-runfiles-of-filegroup-appearing-in-aspect

**Comment by dslomov** [comment]
It's unclear why is this a problem - `filegroup` only has data runfiles indeed.
