### ISSUE TITLE
Provide control over PIC generation on C++ opt builds

### ISSUE THREAD

**Issue by htuch** [bazelbuild/bazel#2903]
With Bazel 0.4.5 and `-c opt`, I've observed that both PIC and non-PIC C++ libraries are generated during the build, effectively doubling the build time. In the Envoy project (https://github.com/lyft/envoy/), we only statically link our binaries (including tests). As a result, we have no need for PIC objects.

We had to resort to a toolchain hack via a forked `cc_configure.bzl` in https://github.com/lyft/envoy/pull/837 to disabled PIC (see https://github.com/lyft/envoy/pull/837/commits/396ecf8f0a10d2f2397badce713d5f8ed45a4157). 

Can we make this a command-line option? There exists `--force_pic` (and corresponding `'--noforce_pic`) but not `--force_no_pic` AFAICT.

CC: @MattKlein123 https://github.com/lyft/envoy/issues/415

**Comment by mhsmith** [comment]
Related: #1740.

**Comment by hlopko** [comment]
With bazel 0.23 (February 2019 release) you will be able to pass `--features=-supports_pic`, which will tell bazel that the toolchain doesn't need PIC for dynamic libraries ([docs](https://docs.bazel.build/versions/master/crosstool-reference.html#well-known-features). The result will be that PIC actions won't be registered.

I will close this issue, please reopen if this isn't what you needed. Thanks!

**Comment by solsjo** [comment]
Related to this but for cc_binary, in some gcc versions, gcc requires the linkerflag -no-pie. Otherwise the target will position independent. Regardless if needsPic is set to false . Is this resolved by this issue aswell? Or should I add a new issue?

**Comment by hlopko** [comment]
Nope, supports_pic will not address that, we would have to have a separate feature for that. I'm thinking if this is better expressed using linkopts, or if it should be part of the autoconfigured toolchain, what do you think? If latter, feel free to open a feature request and assign me.
