### ISSUE TITLE
Cannot impl aspect_group in Skylark

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2905]
### Description of the problem / feature request / question:

I tried creating a group for delegating aspects to `srcs`. Sadly my first attempt does not work:

    Invalid rule class hasn't been exported by a Skylark file.

Is there any other way (aside Java) to do it?

### If possible, provide a minimal example to reproduce the problem:

    def _aspect_group_impl(ctx):
        return struct(
            files=ctx.files.srcs,
        )

    def aspect_group(name, *args, aspects, **kwargs):

        aspect_group_rule = rule(
            implementation = _aspect_group_impl,
            attrs = {
                "srcs": attr.label_list(aspects = aspects),
            },
        )

        return aspect_group_rule(
            name = name,
            *args,
            **kwargs
        )

### Environment info
* Operating System: Ubuntu 16.04
* Bazel version (output of `bazel info release`): 0.4.5

###  Have you found anything relevant by searching the web?
Nope

**Comment by dslomov** [comment]
Creating rules in macros is not supported.

**Comment by dslomov** [comment]
What are you trying to do? Maybe there is another solution?

**Comment by abergmeier-dsfishlabs** [comment]
I am trying to apply a rule on a portion of my graph. For that I want to apply an aspect to every src of a `filegroup`. So I created a `aspect_group`, that should handle like a `filegroup` but also apply aspects. 
I solved that now by (moving the rule declaration to the parent context and) writing a specific aspect list.

**Comment by abergmeier-dsfishlabs** [comment]
Not needed for recursion - only for data handling. Found another way of handling that.
