### ISSUE TITLE
Software Engineer

### ISSUE THREAD

**Issue by rajsarany** [bazelbuild/bazel#2907]
Hi Everyone,
Hope all are doing great!
We are currently looking for candidates with good expertise on Bazel Build System and good programming skills on C or C++. This is for one of our Top notch IT Firm located in Santa Clara,CA.

Best,
pia saranya
pia@zenaide.com
408-564-7176/408-564-0254

**Comment by vladmos** [comment]
Hi! Sorry, we use this issue tracker only to track bugs, our mailing list would be a better place for such announcements.
