### ISSUE TITLE
Aspect kind attr is not uniquely identifying

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2908]
### Description of the problem / feature request / question:

When accessing `kind` in an aspect, the name is local only. So there is a chance that it collides in huge repos and one cannot differentiate. Maybe introduce a way to retrieve a global (full path) `kind`.

### Environment info
* Operating System: Ubuntu 16.04
* Bazel version (output of `bazel info release`): 0.4.5

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
