### ISSUE TITLE
Create new category for aspects

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2911]
### Description of the problem / feature request / question:

Perhaps it would make sense to create a GitHub category for aspects.

**Comment by abergmeier-dsfishlabs** [comment]
Was feeling bold and created one on stackoverflow already: https://stackoverflow.com/questions/tagged/bazel-aspect

**Comment by dslomov** [comment]
Closing as obsolete. team-Starlark owns aspects.
