### ISSUE TITLE
"pivot_root(., tmp/....)": Invalid argument

### ISSUE THREAD

**Issue by costinm** [bazelbuild/bazel#2913]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

Sandbox failing on some linux machines.

### If possible, provide a minimal example to reproduce the problem:

I suspect it's due to 'shared' mounts not compatible with pivot_root, however 
not sure how to work around, and which directories are mounted by bazel.
My system seems to have a lot of directories mounted this way - I haven't
found who is causing this, I'm running docker, but it may be another 
'benefit' of systemd.

At least the bazel error message should be more clear - and if it happens
it should point to 'spawn_strategy=standalone' flag, right now it only recommends
--stragegy=foo=standalone, with all the build steps, which is pretty frustrating.

### Environment info
* Operating System:

Ubuntu Xenial. 

* Bazel version (output of `bazel info release`):

release 0.4.5

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

Found various pages linking pivot_root failures to shared mounts.
I tried "mount --make-private /", also the workspace dir - still fails.

Also tried to run bazel in a docker container (using gcr.io bazel image) - same
error inside docker. 

It happens both on my home machine and on goobuntu desktop at work. 

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by susinmotion** [comment]
cc @jmmv

**Comment by jmmv** [comment]
Looks like this fell through the cracks years ago...

I have no easy means to confirm this right now, so I'll close the bug as obsolete. But please reply if you think this issue still exists.
