### ISSUE TITLE
Governance page implies there is a full list of core contributors but it isn't there.

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#2915]
https://bazel.build/governance.html#core-contributors

> At this time, all core contributors work for Google (see below for the full list), but this will hopefully change over time.

But there is no list below, just a mailing list.

**Comment by damienmg** [comment]
/cc @michelleirvine 

The list of core contributors ended-up changing so we ended-up replacing it by a mailing list, we should probably reword the sentence before.
