### ISSUE TITLE
Failure to build external proto_libraries with dependencies

### ISSUE THREAD

**Issue by kgreenek** [bazelbuild/bazel#2916]
Bazel fails to build an external project that contains protos, where one proto_library depends on another proto_library.

Example WORKSPACE:

```python
http_archive(
    name = "com_google_protobuf",
    urls = ["https://github.com/google/protobuf/archive/v3.3.0.tar.gz"],
    sha256 = "94c414775f275d876e5e0e4a276527d155ab2d0da45eed6b7734301c330be36e",
    strip_prefix = "protobuf-3.3.0",
)

new_http_archive(
    name = "ign_msgs_archive",
    urls = ["https://bitbucket.org/ignitionrobotics/ign-msgs/get/ignition-msgs_0.7.0.tar.gz"],
    sha256 = "a3bd439c15df1dbde7f9e8c6fb272c7bfb2dcd34059d6b672f6805918e455e72",
    strip_prefix = "ignitionrobotics-ign-msgs-b5ed20ac644a",
    build_file = "//third_party:ign_msgs.BUILD",
)
```

Example //third_party/ign_msgs.BUILD:

```python
proto_library(
    name = "header_proto",
    srcs = ["ignition/msgs/header.proto"],
    deps = [":time_proto"],
)

proto_library(
    name = "time_proto",
    srcs = ["ignition/msgs/time.proto"],
)
```

Bazel build output:

```bash
$ bazel build @ign_msgs_archive//:header_proto --verbose_failures
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
ERROR: /home/kevin/.cache/bazel/_bazel_kevin/743181dda8049f3d71a9ad4eab06b9c6/external/ign_msgs_archive/BUILD.bazel:484:1: Generating Descriptor Set proto_library @ign_msgs_archive//:header_proto failed: protoc failed: error executing command 
  (exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl \
  bazel-out/host/bin/external/com_google_protobuf/protoc '--descriptor_set_out=bazel-out/local-fastbuild/genfiles/external/ign_msgs_archive/header_proto-descriptor-set.proto.bin' '-Iignition/msgs/header.proto=external/ign_msgs_archive/ignition/msgs/header.proto' '-Iignition/msgs/time.proto=external/ign_msgs_archive/ignition/msgs/time.proto' '--direct_dependencies=external/ign_msgs_archive/ignition/msgs/time.proto:external/ign_msgs_archive/ignition/msgs/header.proto' '--direct_dependencies_violation_msg=%s is imported, but @ign_msgs_archive//:header_proto doesn'\''t directly depend on a proto_library that '\''srcs'\'' it.' external/ign_msgs_archive/ignition/msgs/header.proto)

Use --sandbox_debug to see verbose messages from the sandbox.
[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: ignition/msgs/header.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: ignition/msgs/time.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
ignition/msgs/header.proto: ignition/msgs/time.proto is imported, but @ign_msgs_archive//:header_proto doesn't directly depend on a proto_library that 'srcs' it.
Use --strategy=GenProtoDescriptorSet=standalone to disable sandboxing for the failing actions.
Target @ign_msgs_archive//:header_proto failed to build
INFO: Elapsed time: 1.148s, Critical Path: 0.05s
```

It looks like the wrong values are being passed to protoc to the --direct_dependencies flag. If instead of passing this:
```bash
--direct_dependencies=external/ign_msgs_archive/ignition/msgs/time.proto:external/ign_msgs_archive/ignition/msgs/header.proto
```

...you pass this:

```bash
--direct_dependencies=ignition/msgs/time.proto:ignition/msgs/header.proto
```

...then the protoc command succeeds.

### Environment info
* Operating System:
Arch Linux

* Bazel version (output of `bazel info release`):
release 0.4.5- (@non-git)
Latest bazel version from AUR

**Comment by buchgr** [comment]
Thanks for the bug report @kgreenek.  This has already been fixed by commit 98571f36260fa70043ea07820d6b19a8f9219500 and will be part of the next release.

It would be great if you could reconfirm that this works for you too by using bazel from HEAD.

**Comment by kgreenek** [comment]
Excellent! Thank you! I guess I didn't search hard enough.
Is there a rough timeline for when the next release will be available?

**Comment by buchgr** [comment]
This or next week I believe. It would still be great if you could verify that it works for you too, so that we don't release something broken! Thanks @kgreenek

**Comment by kgreenek** [comment]
Confirmed! I can build my example without any issues using bazel built from HEAD. I greatly appreciate the prompt turn-around! Cheers to you guys

**Comment by kgreenek** [comment]
On a semi-related, I wrote a python script that generates a BUILD file automatically for a directory full of protos according to Bazel's guidlines (if you look at that ign_msgs repo, you'll see why I needed to do that). It may help others migrate existing repos with a lot of protobuf files to Bazel. Do you think a tool like that would be worth distributing (similar to wtool)? I plan to throw it up on my github when I get home. Happy to develop it further if you guys think it'd be helpful.

**Comment by buchgr** [comment]
@kgreenek yep totally! Else, I would have written one in a few weeks for https://github.com/googleapis/googleapis :-). So please do and send an announcement to https://groups.google.com/forum/#!forum/bazel-discuss. Also please put me in cc if you don't forget - I sometimes miss messages from bazel-discuss. Thanks!

**Comment by buchgr** [comment]
I could actually use such a script asap :-). So I am looking forward to it!

**Comment by junghoahnsc** [comment]
Is there any ETA of the next release?

**Comment by buchgr** [comment]
@junghoahnsc if things go well tomorrow or monday.
