### ISSUE TITLE
PackagePathLocator doesn't handle BUILD.bazel

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#2917]
Not sure if this is causing any problems, but it seems like a bug: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/pkgcache/PathPackageLocator.java#L104

**Comment by kchodorow** [comment]
Also CppCompileAction is looking for "BUILD".

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
