### ISSUE TITLE
Bazel breaks on system includes with newest macOS command line tools

### ISSUE THREAD

**Issue by sayrer** [bazelbuild/bazel#2918]
### Description of the problem / feature request / question:

A previously working build broke when the command line tools were upgraded on OS X.
### Environment info
* Operating System:

macOS 10.12.4

* Bazel version (output of `bazel info release`):

> bazel info release
release 0.4.5-homebrew

###  Have you found anything relevant by searching the web?

No.

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

```
ERROR: /private/var/tmp/_bazel_sayre/4de71d28335d84ef3a9372b4f1cd1773/external/gtest/BUILD.bazel:1:1: undeclared inclusion(s) in rule '@gtest//:main':
this rule is missing dependency declarations for the following files included by 'external/gtest/src/gtest-death-test.cc':
  '/usr/include/ctype.h'
  '/usr/include/sys/cdefs.h'
  '/usr/include/sys/_symbol_aliasing.h'
  '/usr/include/sys/_posix_availability.h'
  '/usr/include/runetype.h'
  '/usr/include/_types.h'
  '/usr/include/sys/_types.h'
  '/usr/include/machine/_types.h'
  '/usr/include/i386/_types.h'
  '/usr/include/sys/_pthread/_pthread_types.h'
 ...
```

**Comment by luberg** [comment]
Seems related to: https://github.com/bazelbuild/bazel/issues/715
@sayrer Can you try updating your CROSSTOOL file and add a cxx_builtin_include_path for /usr/include ?

Use bazel build with -s to discover which toolchain needs the path included.

**Comment by damienmg** [comment]
Marcel: can you have a look, probably an error in auto configuration on OS X.

**Comment by pcj** [comment]
We're seeing a possibly related issue with the newer command line tools as well...  

https://github.com/pubref/rules_node/issues/16

Perhaps like the behavior of osx sandbox has had some change?

**Comment by mhlopko** [comment]
Can you also share the output of (with the compiler that Bazel detects, or the compiler that you have in $CC):

```clang -E -xc++ -v -v```

This is what Bazel uses to get the list of include directories and sets that into generated CROSSTOOL. Other solution would be what @luberg suggests. Maybe Bazel uses a different compiler that you assume (use -s flag to see the invocations). Or maybe you need to teach your compiler about the `/usr/include`?

**Comment by mhlopko** [comment]
Friendly ping.
