### ISSUE TITLE
CcToolchainInfo has fields that say 'do not use', but don't explain why.

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#2920]
https://bazel.build/versions/master/docs/skylark/lib/CcToolchainInfo.html

There are two fields `link_options_do_not_use`and `unfiltered_compiler_options_do_not_use`. These fields do not say why they shouldn't be used. If they are deprecated then the documentation should say so.

**Comment by lberki** [comment]
/cc @mhlopko 

It's because we needed these for Google-internal purposes until we can come up with a more reasonable API, but we didn't want to make them "official" so that people don't start depending on the functionality. So we did not document them and gave them an appropriately scary name.
