### ISSUE TITLE
new_file does not check for other package path

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2923]
### Description of the problem / feature request / question:

In a rule implementation I create a

    bar = ctx.new_file("%sdeps.id" % ctx.file.src.path)

    ctx.action(
        ...
        arguments = [
            bar.path,

Now in `ctx.action` I get the error message:

    expected type 'string' for 'arguments' element but got type 'root' instead

This is probably because `src` comes from another package and must not be used. IMO `new_file` should check for path "locality" already because the later error message of `arguments` is not that helpful.

### Environment info
* Operating System: Ubuntu 16.04
* Bazel version (output of `bazel info release`): 0.4.5

**Comment by brandjon** [comment]
`ctx.actions.declare_file()` creates the file relative to the current package, so I'm not sure how you're getting that behavior (unless something's changed, aside from the rename of this method). When I try it, I get the package path of the src target appended to the package path of the current target.

If there's a modern repro, feel free to reopen.
