### ISSUE TITLE
Fragments need better examples

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#2932]
https://bazel.build/versions/master/docs/skylark/rules.html#configuration-fragments
This does not show how to use the values provided by a fragment. It does not explain what adding a fragment does other than making it available to the rule's implementation (maybe it doesn't do anything, but then why do they need to be requested up front).

https://bazel.build/blog/2017/03/07/java-sandwich.html
This uses fragments for `java` but doesn't actually access the fragment values, and so doesn't answer what a user would use fragments for.

**Comment by juliexxia** [comment]
(Context: I'm moving on from Bazel on friday and spending some time triaging all bugs assigned to me before unassigning myself)

Agree this should happen. Also probably good to mention in any ctx.fragments documentation the existence of starlark build settings and link to them. An important thing to note for this documentation is that specific options are exposed to starlark on an ad-hoc basis so folks can't expect every option in a given fragment to be available.
