### ISSUE TITLE
java_common docs use unknown syntax and have bad names for first argument 

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#2933]
https://bazel.build/versions/master/docs/skylark/lib/java_common.html

The docs for compile use a syntax I haven't seen in other files: `*`. It isn't explained here either.
```
struct java_common.compile(arg0:ctx, *, source_jars=[], source_files=[], output, javac_opts=[], deps=[], strict_deps='ERROR', java_toolchain, host_javabase, sourcepath=[])
```

Also multiple functions in this file have the first argument named `arg0` instead of something semantic. This looks like this is generated from the mandatory positional argument annotation.

**Comment by laurentlb** [comment]
It means that arguments after "*" are keyword-only.

`java_common.compile(ctx, [])  # error`
`java_common.compile(ctx, source_jars=[]) # correct`

This is the same syntax as in Python 3 (https://www.python.org/dev/peps/pep-3102/). Please don't use it in your code, though.

We'll clarify it in the documentation.

**Comment by brandjon** [comment]
The `arg0` thing appears to have been fixed.

Keyword-only params were at one point going to be removed (I believe for syntactic compatibility with Python 2), but we ended up deciding against it. It's ok to use keyword-only params.
