### ISSUE TITLE
Test on HDD

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2934]
### Description of the problem / feature request / question:

Due to #2921, #1836 I personally would recommend for Bazel to have a Jenkins slave running on HDDs. The reason is that, this will show problems very early when some part of Bazel is relying on too much IO throughput and/or latency (which Sandboxing seems so do).

Bonus points if you downgrade devs to HDDs.

### Environment info
* Operating System: Ubuntu 16.04
* Bazel version (output of `bazel info release`): 0.4.5

**Comment by damienmg** [comment]
Moving to continuous-integration

**Comment by damienmg** [comment]
Closing in favor of bazelbuild/continuous-integration#66
