### ISSUE TITLE
Windows, Bazel client: always prefix paths with "\\?\"

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2935]
The C++ code of the Bazel client should always use the Unicode WinAPI functions and always add the "\\\\?\\" prefix, even if the path is shorter than MAX_PATH.

The purpose is to avoid the Win32 API's path processing which tries to be helpful but in fact does things like stripping trailing dots from paths, so e.g. `CreateDirectory("c:\\foo.")` will actually be translated to `CreateDirectory("c:\\foo")` (mind the missing dot after foo).

### Environment info
* Operating System: Windows, all versions

**Comment by petemounce** [comment]
"fix all remaining bugs." - strong! :D

**Comment by laszlocsomor** [comment]
Shooting for the starts, no less ;)

**Comment by laszlocsomor** [comment]
Not yet fixed.
