### ISSUE TITLE
Convenience symlink are inconsistent

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2936]
See http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD-jdk7,PLATFORM_NAME=darwin-x86_64/737/console

Notably SubincludePreprocessorTest is run was deleted a long time ago.

Looking in the runfiles we can find it in the package_test lib:
```
$ jar tvf ./bazel-bin/src/test/java/com/google/devtools/build/lib/packages_test.runfiles/io_bazel/src/test/java/com/google/devtools/build/lib/packages_test.jar  | grep Subinclude
  6113 Tue Jan 01 09:00:02 CET 1980 com/google/devtools/build/lib/packages/SubincludePreprocessorTest.class
```

**Comment by damienmg** [comment]
Some more weirdness

```
$ ~/.bazel/HEAD-jdk7/bin/bazel --bazelrc=bazel.bazelrc build --test_output=summary --test_summary=none -s --explain build.explain //src/test/java/com/google/devtools/build/lib:packages_test &>build.log
$ ~/.bazel/HEAD-jdk7/bin/bazel --bazelrc=bazel.bazelrc test --test_output=summary --test_summary=none -s --explain test.explain //src/test/java/com/google/devtools/build/lib:packages_test &>test.log
```

Build a lot of stuff in build.log but nothing in test.log. Actually fails the build when using build, fail the test but no rebuild during test.

Files content are there: https://gist.github.com/damienmg/bbe5ce14a97fc181425cbc529ac90152

**Comment by damienmg** [comment]
Ok the difference is in the command line from the rc file: we are running in --keep_going in the second case, so I think we execute the test even though the build failed.

**Comment by damienmg** [comment]
Although this should be a build error then...

**Comment by damienmg** [comment]
Same behavior without keep going...

**Comment by buchgr** [comment]
On Linux we are also occasionally running tests that don't exist. `InvocationPolicyEnforcerTest` doesn't exist.
![dont exist](https://cloud.githubusercontent.com/assets/1388179/25697382/0c05b834-30bb-11e7-97c4-3937d07dedaf.png)

**Comment by buchgr** [comment]
`InvocationPolicyEnforcerTest` is also run on OSX. The machine was ` darwin-x86_64-2`
![dont exist mac](https://cloud.githubusercontent.com/assets/1388179/25697733/6993df52-30bc-11e7-8444-341c2a2b8c03.png)

**Comment by buchgr** [comment]
Same thing with `AndroidBinaryTest`. The return type of `JavaRuleOutputJarsProvider.getOutputJars()` changed from `Iterable` to `ImmutableList` and thus it can't find the method
![android no exist](https://cloud.githubusercontent.com/assets/1388179/25697863/e594f1b8-30bc-11e7-902a-1e96c529e04c.png)

**Comment by buchgr** [comment]
Also `ConfigSettingsTest`. These error messages were introduced in commit 5d1042629e94e278 two weeks ago, so we must be using a cached jar from even longer ago... 
![config fails](https://cloud.githubusercontent.com/assets/1388179/25698722/4547f724-30c0-11e7-8274-d7ee0087075d.png)

**Comment by ulfjack** [comment]
The other issue here is that the symlinks are incorrect, which is _really_ confusing. Here's the symlinks from our Mac CI machine:

```
bazel-bin -> /private/var/tmp/_bazel_ci/14bf93ceb0c9200fc39d844714861a53/execroot/darwin-x86_64/bazel-out/local-fastbuild/bin
bazel-darwin-x86_64 -> /private/var/tmp/_bazel_ci/14bf93ceb0c9200fc39d844714861a53/execroot/io_bazel
bazel-genfiles -> /private/var/tmp/_bazel_ci/14bf93ceb0c9200fc39d844714861a53/execroot/darwin-x86_64/bazel-out/local-fastbuild/genfiles
bazel-out -> /private/var/tmp/_bazel_ci/14bf93ceb0c9200fc39d844714861a53/execroot/io_bazel/bazel-out
bazel-testlogs -> /private/var/tmp/_bazel_ci/14bf93ceb0c9200fc39d844714861a53/execroot/darwin-x86_64/bazel-out/local-fastbuild/testlogs
```

bazel-bin, bazel-genfiles, and bazel-testlogs use the directory name, while bazel-out and bazel-darwin-x86_64 use the project name.

**Comment by ulfjack** [comment]
The VanillaJavaBuilder issue explains all the bugs above except the AndroidBinaryTest failure.

**Comment by buchgr** [comment]
The CI link to the bugs I experienced is: http://ci.bazel.io/job/Gerrit-bazel-tests/639/BAZEL_VERSION=latest-jdk7,PLATFORM_NAME=darwin-x86_64/testReport/

**Comment by damienmg** [comment]
This is fixed and cherry-picked in the release candidate
