### ISSUE TITLE
Windows: envvars may reference other envvars

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2940]
On Windows you can define System and User environment variables.
User envvars are expanded eagerly.
System envvars are expanded lazily... or not at all:
```
C:\>set foo
foo_system=foo_system
foo_user=foo_user

C:\>set bar
bar_system=bar1;foo_system;%foo_user%;bar2
bar_user=bar1;foo_system;foo_user;bar2

C:\>echo %bar_system%
bar1;foo_system;%foo_user%;bar2
```
(I set both "bar_user" and "bar_system" to "bar1:%foo_system%;%foo_user%;bar2".)

So if `Path` is a system envvar, as it is, and it contains other envvars, it will not be expanded. I don't know if this is intentional in Windows, but even `GetEnvironmentVariableA` returns the non-expanded value of `bar_system`.

The problem however is that as bazel is installing (extracting its embedded files) we create the CROSSTOOL file by substituting values into the crosstool template. As part of that we process (or embed, I don't know) the value of PATH in the crosstool file. If the PATH contains a reference to another envvar then the template instantiation logic believes the "%" references a (non-existent) placeholder, and reports an ugly error:
```
Extracting Bazel installation...
........................
____Loading package: src
____Loading package: @bazel_tools//tools/cpp
____Loading package: @local_config_xcode//
ERROR: Invalid toolchain configuration: expected '{' at position 1776 while pars
ing a flag containing 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Commo
n7\IDE\CommonExtensions\Microsoft\TestWindow;(...many more entries...);%foo%'.
```

We should either try to resolve the embedded `%foo%` there or ignore it straight away.

**Comment by laszlocsomor** [comment]
@mhlopko , @dslomov

**Comment by dslomov** [comment]
We have fixed CROSSTOOL generation to handle % signs (they are passed verbatim).
