### ISSUE TITLE
Porting bazel to run on  an embedded system where JDK is not available.

### ISSUE THREAD

**Issue by udnaan** [bazelbuild/bazel#2945]
Just a general query to figure out whether it's even a reasonable question to ask or a hopeless quest with no chance of success.

**Comment by damienmg** [comment]
Can you provide example of such system?

**Comment by udnaan** [comment]
aarch64 (arm64) with sfp

**Comment by dmitry-xnor** [comment]
Do such systems actually exist? IIRC aarch64 mandates that the CPU has VFP and NEON.

**Comment by dmitry-xnor** [comment]
Just to be clear: I'm not a part of the "Bazel team". I do work quite extensively with aarch64 though, and have a build of Bazel that works there. We run it on NVIDIA TX1, Pine-A64 and Nanopi-A64 at the moment.

**Comment by dmitry-xnor** [comment]
ARM seems to concur: there's no soft float ABI for aarch64

http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.faqs/ka16242.html

Hence the question

**Comment by udnaan** [comment]
I'm only looking for the answer to the original question. Don't take offense but as informative as all this is, it is just adding noise to a legitimate question.

**Comment by damienmg** [comment]
So you mean that there is no build of a JDK whatsoever on that platform?

**Comment by udnaan** [comment]
That is correct.

**Comment by damienmg** [comment]
So supporting those platform means for us to rewrite Bazel outside of JVM :(, unless you would be ok with cross-compilation (that is not having Bazel on the machine you target)?

**Comment by udnaan** [comment]
That is a reasonable answer event though not quite the one that I hoped. Thank you.

**Comment by jainrahul1** [comment]
@dmitry-xnor I am facing problem in building bazel for PINE A64 board.  
Error:
Building Bazel from scratch..scripts/bootstrap/buildenv.sh: line 186:  9352 Killed
