### ISSUE TITLE
Open source internal version of BlazeJavacMainTest

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#2950]
After https://bazel-review.git.corp.google.com/c/10751/ is submitted there will be 2 versions of this test (internal + external), which is not desirable. Open sourcing the internal version also improves contributions test coverage.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
