### ISSUE TITLE
Consider allowing '.def' files in cc_library's 'srcs'

### ISSUE THREAD

**Issue by ilya-biryukov** [bazelbuild/bazel#2955]
### Description of the feature request:

Since `.inc` and `.h` files are allowed in `cc_library`'s `srcs`, could bazel allow `.def` files to be there as well?
 Note they are already allowed in `hdrs`.

I stumbled upon this limitation while trying to fix BUILD file for llvm inside tensorflow repository. I tried adding `.def` file into cc_library's `srcs` and it failed with an error. I managed to workaround it by adding a new cc_library that has this `.def` file in `hdrs` and including it as a dependency, but that's certainly redundant.

### If possible, provide a minimal example to reproduce the problem:
```
// File: values.def
HANDLE_VALUE(Foo1)
HANDLE_VALUE(Foo2)

// File: foo.h
#define HANDLE_VALUE(NAME) struct NAME { };
#include "values.def"
#undef HANDLE_VALUE

// File: foo.cpp
#include "foo.h"

// File: BUILD
cc_library(
    name = "foo",
    srcs = ["foo.cpp", "foo.def", "foo.h"],
    hdrs = ["foo.h"]
)
   
```
### Environment info
* Bazel version (output of `bazel info release`):
release 0.4.5

**Comment by kchodorow** [comment]
Given that there is a (kludgy) workaround, I'm marking this p3, but it shouldn't be too hard to fix.

**Comment by mhlopko** [comment]
@meteorcloudy

Is .def file mentioned here the same as 'module definition' file for MSVC? Yun has been working on it here: https://bazel-review.googlesource.com/c/bazel/+/17552 and we decided to create a special attribute for it.

If it's not the same thing, and your def file represents just a normal C++ header file, then I'd be against adding support for it in srcs. That would be confusing. Unless you persuade me otherwise :)

**Comment by meteorcloudy** [comment]
This is the same thing, I am trying to submit https://bazel-review.googlesource.com/c/bazel/+/17552 now.

**Comment by ilya-biryukov** [comment]
Actually, my original issue was about usual header files that have a `.def` extension.
LLVM source code uses this extension extensively for a special kind of headers (e.g, see [this file](https://reviews.llvm.org/diffusion/L/browse/cfe/trunk/include/clang/Basic/Builtins.def))

Given that MSVC's `.def` files should be handled very differently, I don't see how both fit into the current design.
In general it seems weird that there are restrictions on file extensions in the build system, which is not present in the underlying compilers and other build systems.
