### ISSUE TITLE
buildifier and rules_dotnet are broken

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2956]
Due to upstream rules_go not including PR https://github.com/bazelbuild/rules_go/pull/428 in the release. Filing this bug for hand off mostly, the fix is no longer on our side.

/cc @c-parsons fyi

**Comment by kchodorow** [comment]
It looks like rules_dotnet are passing (e.g., http://ci.bazel.io/job/rules_dotnet/652/) and I can't figure out why they'd be depending on the rules_go release.

Sent https://github.com/bazelbuild/buildtools/pull/95 to update buildifier.

**Comment by damienmg** [comment]
Oops sorry I should have written rules_web

**Comment by kchodorow** [comment]
Ah, got it.  Sent https://github.com/bazelbuild/rules_webtesting/pull/115.
