### ISSUE TITLE
pkg_tar failed to detect the file content change of the undelying folders

### ISSUE THREAD

**Issue by yuekui2** [bazelbuild/bazel#2957]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
pkg_tar failed to detect the file content change of the undelying folders

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### If possible, provide a minimal example to reproduce the problem:
The following is the build file, which intends to tar the folder naming master

```
package(default_visibility = ["//visibility:public"])

load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar")

pkg_tar(
    name = "vexconfig",
    package_dir = "/vexconfig",
    files = [
        "master",
    ],
)

```
say the following folder structure:
```
master
  \a\aa.txt
  \b\bb.txt
  \c\cc.txt

```
after tar, even if, say, cc.txt changes, the tar build failed to detect the change, and no new tar will build

### Environment info
* Operating System:
ubuntu 16.04

* Bazel version (output of `bazel info release`):
0.4.5

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by damienmg** [comment]
`cc.txt` is not an input of the rule, why do you expect it to influence pkg_tar

**Comment by yuekui2** [comment]
The intention is to tar files and the folder structure of `master`. In this regard, the cc.txt  is somewhere under master and should be part of the rule. What is the correct way to achieve this?

**Comment by damienmg** [comment]
You should glob all the files in that case:

```
package(default_visibility = ["//visibility:public"])

load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar")

pkg_tar(
    name = "vexconfig",
    package_dir = "/vexconfig",
    files = glob(["master/**"]),
)
```

**Comment by yuekui2** [comment]
`files = glob(["master/**"]), `will flatten the folder structure, while we want to keep it.

**Comment by damienmg** [comment]
Try to set strip_prefix to ".", it should not flatten the structure this way.

**Comment by yuekui2** [comment]
works. Thanks a lot.
