### ISSUE TITLE
Unable to compile ios_application under XCode (unable to find tools/objc/dummy.c file)

### ISSUE THREAD

**Issue by wentao** [bazelbuild/bazel#296]
My workspace is setup as follows

project_home/
  WORKSPACE
  third_party/leveldb/BUILD   <--- has a objc_library(name = "leveldb_objc"...
  ios/apps/test/BUILD   <--- has a ios_application, and objc_library that depends on leveldb_objc

When I use bazel build on the ios_application target, everything works fine, and it generates XCode project file and a ipa binary.

But after I switch to XCode and compile the project, it complains about

clang: error: no such file or directory: 'project_home/tools/objc/dummy.c'
clang: error: no input files

This didn't happen before I added the third_party folder in the project root.

**Comment by damienmg** [comment]
Closing request as obsolete. How comes nobody answered that bug?

**Comment by damienmg** [comment]
Just an update this was fixed in August but the author of the change forgot to add the fixes line :)
