### ISSUE TITLE
Unable to download ubuntu-rootfs as new_http_archive

### ISSUE THREAD

**Issue by lazutkin** [bazelbuild/bazel#2960]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

Trying to download ubuntu rootfs ends up with an error:

```
ERROR: no such package '@docker_brew_ubuntu//image': /private/var/tmp/_bazel_dimka/410c032606a1e3f8de1a8d68a1ef052a/external/docker_brew_ubuntu/usr/share/man/man7/pam.7.gz (File exists).
```

My config is:

`WORKSPACE`
```
new_http_archive(
    name = "docker_brew_ubuntu",
    url = "http://cdimage.ubuntu.com/ubuntu-base/releases/16.04/release/ubuntu-base-16.04-core-amd64.tar.gz",
    build_file = "docker/ubuntu.BUILD",
    sha256 = "c66c6cd71270bc5191afeff79ed22e4b29ec8c6aa35431505b12f7d5fd5782e5",
)
```

`docker/ubuntu.BUILD`
```
load("@bazel_tools//tools/build_defs/docker:docker.bzl", "docker_build")
docker_build(
    name = "image",
    tars = ["ubuntu-base-16.04-core-amd64.tar.gz"],
    visibility = ["//visibility:public"],
)

```

### Environment info
* Operating System:
16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

* Bazel version (output of `bazel info release`):
release 0.4.5-homebrew

**Comment by kchodorow** [comment]
Well, one problem is that it would be `@docker_brew_ubuntu//:image`, (note the colon: `//:image` vs `//image`).  If you try that, do you still get an error?  (I wasn't able to reproduce the error you're seeing.)

**Comment by lazutkin** [comment]
Hmm. I don't think that it is a problem since `docker/ubuntu.BUILD` becomes a `BUILD` inside a `docker_brew_ubuntu` directory (sibling to WORKSPACE file) . I'm sure that problem still exists but not in my case since `new_http_archive` was changed to `http_file` (why I should unpack a content of rootfs if I need to use it as base layer of docker image).

Later I'll try to make demo bazel-project to reproduce an error

**Comment by lazutkin** [comment]
@kchodorow here is a test case https://gist.github.com/lazutkin/31bdc8fea9945031ed7be54c652424a2 to reproduce an error

**Comment by kchodorow** [comment]
Thanks, reproduced!  Looks like it's an Mac-only bug, which is why I couldn't get it to error out before.  Looking into it...

**Comment by kchodorow** [comment]
Aha! There is both a PAM.7.gz and a pam.7.gz file, and since OS X has a case-insensitive filesystem, it thinks those are the same and doesn't want to overwrite one with the other.  Hmm. AFAICT, native tar just happily overwrites the file, so I guess that's what Bazel should do, too.
