### ISSUE TITLE
Clarify required Bazel "dump" for correctness issues

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#2962]
### Description of the problem / feature request / question:
I just tried to build copybara on my machine and stumbled on to a correctness issue.
I realized I don't know what I should have done before running "bazel clean --expunge" so I went to the website and searched for the instructions for next time but couldn't find any.

### If possible, provide a minimal example to reproduce the problem:
go to bazel.build
search for "bug" or "correctness bug"
expect to find a result which explains what info will be useful for bazel team to debug a correctness problem.

P.S.
What I did with copybara in more detail:
Built an old version I had lying around (it passed)
Git pulled
Tried to build and some tests failed (same tests several times)
Ran "bazel clean --expunge"
Ran "bazel test //..." and it passes

**Comment by ittaiz** [comment]
@kchodorow I just had a different problem ("Too many open files in system") and again wasn't sure what (if any) diagnostics info I should take before rebuilding so a report can be helpful. 
Do you think we should expand this issue to be general diagnostics gathering guidelines or only about correctness?

**Comment by kchodorow** [comment]
Probably we should eventually cover tips on filing bugs against bazel (how to dump the Java thread stack & what we need to diagnose correctness issues) and stuff that's more oriented towards debugging user issues (running out of memory, threads, CPU, inodes, etc.).

**Comment by ittaiz** [comment]
Definitely agree. I'd even say that this should happen sooner rather than
later since currently people encounter more rough edges and need this in
order to not lose faith
