### ISSUE TITLE
Locale not set for python programs in bazel test

### ISSUE THREAD

**Issue by RenatoUtsch** [bazelbuild/bazel#2963]
`bazel test` doesn't set the locale for python tests. Because of that, trying to run the following program fails with errors:

main.py:
```python
print('solução')
```

Python 2 error:
```
SyntaxError: Non-ASCII character '\xc3' in file /private/var/tmp/_bazel_renatoutsch/ef55f89aac8185d59261068c1a20b42b/bazel-sandbox/a84ee798-eb50-4ec9-8e64-596872088c83-0/execroot/tp1/bazel-out/local-fastbuild/bin/test.runfiles/__main__/test.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

Python 3 error:
 ```
UnicodeEncodeError: 'ascii' codec can't encode characters in position 4-5: ordinal not in range(128)
```

This is making it impossible to test my python programs, because I can't test functions that try to print anything that is non-ascii.

bazel needs to set `LANG` to either something like `en_US.UTF-8` or to at least the current system default.

Looks like `bazel run` also doesn't set the locale for python 2, although it sets it for python 3, because printing works on it.

Is there a workaround I can use to test my software while this is not working?

### Environment info
* Operating System: macOS Sierra
* Bazel version (output of `bazel info release`): `release 0.4.5-homebrew`

**Comment by RenatoUtsch** [comment]
Ok, looks like I might have confused locale with encoding.

My encoding when running python3 with `bazel run` is `UTF-8`, as expected. However, with `bazel test`, the locale is set to `US-ASCII`.

**Comment by kchodorow** [comment]
I actually get that `sys.stdout.encoding` is `None` for both `run` and `test`. How are you running them now that this works? Just running `python whatever.py` with that line barfs for me.

It looks like the way you're supposed to indicate this in source files is adding a line [`# coding: utf-8`](https://www.python.org/dev/peps/pep-0263/), would it be possible to add that to tests?

**Comment by RenatoUtsch** [comment]
Python3 is *always* UTF-8, you aren't supposed to add any comments specifying utf-8 sources.

I'm running with the following BUILD rule:
```python
py_test(
    name = "main_test",
    size = "small",
    srcs = ["main_test.py"],
    default_python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        ":main",
    ],
)
```

And the following command:
```shell
$ bazel test --test_output=errors --force_python=PY3 --host_force_python=PY3 :main_test

**Comment by RenatoUtsch** [comment]
In Python 2 you might actually be right, but in Python 3 you're not supposed to do that.

**Comment by kchodorow** [comment]
Indeed!  Sorry, not terribly up on Python (obviously).  I did find a workaround: you can use `--action_env` to pass in the correct encoding:

```
bazel test --action_env=PYTHONIOENCODING=utf8 --force_python=PY3 --host_force_python=PY3 //:thing
```

Clearing the locale seems reasonable (to make builds from different areas produce the same output) but I'm guessing that clearing Python's default encoding was unintentional. Assigning to someone who can verify that.

**Comment by RenatoUtsch** [comment]
Oh, I didn't know about that flag! Thanks!

Yeah, I agree it is reasonable to clear the locale. It should only be the language's default instead of a random encoding.

**Comment by marczych** [comment]
A quick warning for anybody are adding `test --action_env=PYTHONIOENCODING=utf8` to your bazelrc: doing so doubled our test time in CI because we built everything without that action env in the build phase and then we ran the test command which results in rebuilding everything with the extra action_env. I'm still working on a proper fix for this. =)

**Comment by brandjon** [comment]
Can this issue be closed, or is it now a feature request to add something to `py_test` that would enable setting an env var for the locale / encoding?

**Comment by RenatoUtsch** [comment]
This was a bug where tests would run in a different configuration than
python 3 runs by default and because of that the tests would fail even
though the code was correct. This is not a feature request but a bugfix.

I haven't used python 3 with bazel since I opened this bug. So much has
changed, so I don't know if this is fixed already.

**Comment by brandjon** [comment]
I see. If I clear the LANG env var and open a Python 3 REPL, I can repro the failure to print a non-ASCII string. (It doesn't repro that way for Python 2.) So if simple python programs are behaving differently over non-ASCII data just because they're run within bazel, I can see how that's an issue.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
