### ISSUE TITLE
py_test passing file with paths

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2965]
### Description of the problem / feature request / question:

I have a `py_test`, to which I pass in a generated file `testfiles.txt` (containing a huge amount of files to load).

I generate the `testfiles.txt` like:

    # in a macro
    ref_locations = ["$(location %s)" % ref for ref in testfiles]

    native.genrule( # Don't judge
        name = "testfiles.txt",
        outs = [param_file],
        srcs = refs,
        cmd = "echo '{}' > $(location {})".format("\n".join(ref_locations ), param_file),

    )

Then `testfiles.txt` is passed to the test like:

    py_test(
        ...
        args = ["$(location %s)" % param_file],
        data = testfiles + [
            param_file,
        ],

In the `py_test`:
1. The _cwd_ is `<...>/384827ac61ea21f490af9da32681de43/execroot/tools/bazel-out/local-py3-fastbuild/bin/external/<...>/resource_ref_tests.runfiles/<...>`
2. `param_file` gets loaded just fine.
3. but the locations inside the `param_file` begin with `bazel-out`, which of course is totally wrong for that _cwd_.

Question now is - is there a way of generating a file with paths relative to the py_test?

### Environment info
* Operating System: Ubuntu 16.04
* Bazel version (output of `bazel info release`): 0.4.5

###  Have you found anything relevant by searching the web?
Another strange behavior is, that `testfiles` are not mapped into the runfiles directory (both sandboxed and standalone)!?

**Comment by abergmeier-dsfishlabs** [comment]
So the workaround we use now is to use the regex `(.*/execroot/.*)/bazel-out/.*` to find the root and then prefix that to the files.

**Comment by kchodorow** [comment]
If you use a skylark rule, you could use `short_path`: it's the path under the runfiles tree.  

(`path` is what you get from `$(location ...)`.)

Would converting it to a skylark rule work for you?

**Comment by abergmeier-dsfishlabs** [comment]
Thanks for the suggestion @kchodorow.
Now tried:

    def _list_paths_impl(ctx):

        ctx.file_action(
            ctx.outputs.lst,
            "\n".join([src.short_path for src in ctx.files.srcs]),
        )

    list_paths = rule(
        implementation = _list_paths_impl,
        attrs = {
            "srcs": attr.label_list(),
        },
        outputs = {
            "lst": "%{name}.txt"
        }
    )

and then:

    param_file = "testfiles"

    list_paths(
        name = param_file,
        srcs = refs,
    )

but strangely then `param_file` can no longer be opened inside Python.
AFAIS the `testfiles.txt` is not added to the sandbox.

**Comment by kchodorow** [comment]
Are you adding testfiles.txt as a data dependency? E.g.,

```
list_paths(
    name = "testfiles",
    srcs = ["whatever"],
)

py_test(
    name = "thing",
    srcs = ["thing.py"],
    data = ["testfiles.txt"],
)
```

(Works for me...)

**Comment by abergmeier-dsfishlabs** [comment]
> data = testfiles + [
            param_file,
    ],

Via this. Could it be, that it only works if you explicitly reference the file and not the rule!?

**Comment by kchodorow** [comment]
You have to add testfiles.txt to the runfiles provider if you want it to be picked up as something relevant to `data`.  With the latest Bazel, this looks like:

```
return [DefaultInfo(runfiles = ctx.runfiles(files = [ctx.outputs.lst]))]
```

at the end of your Skylark function.

**Comment by abergmeier-dsfishlabs** [comment]
> You have to add testfiles.txt to the runfiles provider if you want it to be picked up as something relevant to data

Indeed. Sorry, that slipped my mind. While `testfiles.txt` can now be read, the containing paths cannot (are not linked into runfiles).
Actually I think my whole problem is that multiple layers are generating the necessary runfiles and this somewhere breaks. Is there ANY way of debugging runfiles? This is very annoying currently.

**Comment by kchodorow** [comment]
You mean figuring out what runfiles are provided by each rule?

**Comment by abergmeier-dsfishlabs** [comment]
> You mean figuring out what runfiles are provided by each rule?

Would be a start.

**Comment by kchodorow** [comment]
Yeah, I guess what I'd really want is a debugger, so I could put a breakpoint in this action (or maybe the rule in the BUILD file?) and then step through and see what's being provided... I think that's a bit outside the scope of this issue, though :)
