### ISSUE TITLE
Failure on protobuf compilation on Windows on one slave (ci)

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2966]
http://ci.bazel.io/job/bazel-tests/747/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-x86_64/console

The slave have been turned off for @laszlocsomor to investigate. It is failing consistently on that slave. 

Filed the bug for tracking.

**Comment by laszlocsomor** [comment]
Status update: unfortunately i couldn't repro this yet, and i was busy fixing https://github.com/bazelbuild/bazel/issues/2892 today. I'll take a look tomorrow again.

**Comment by laszlocsomor** [comment]
I managed to log on to the machine but so far couldn't repro the error there either.

**Comment by laszlocsomor** [comment]
This error in the CI log:
```
  C:/tools/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/third_party/protobuf/3.2.0/protoc.exe\
    --plugin=protoc-gen-grpc=bazel-out/host/bin/third_party/grpc/cpp_plugin.exe\
    --cpp_out=bazel-out/msvc_x64-fastbuild/genfiles\
    --grpc_out=bazel-out/msvc_x64-fastbuild/genfiles\
    src/main/protobuf/command_server.proto: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
--grpc_out: protoc-gen-grpc: Plugin failed with status code 3221225477.
```

3221225477 = 0xc0000005 = `STATUS_ACCESS_VIOLATION`

I'm looking for possible cause for this.

**Comment by laszlocsomor** [comment]
@damienmg , Build 748 that you started at the same revision as 747, has passed, even though 747 failed, so the most I can say is this problem was intermittent. My attempts to repro it, either on the machine or locally, failed. I suggest turning on the machine again and react sooner the next time it fails like this, to rule out the possibility of overwriting potentially corrupt files with a rerun.

**Comment by damienmg** [comment]
Sounds good, let's put this bug as P2 waiting for information

**Comment by laszlocsomor** [comment]
And also, let's not rerun the build again before looking. I don't know if that played a role here, maybe did, maybe not.

**Comment by laszlocsomor** [comment]
Closing this as WAI for now.
