### ISSUE TITLE
Document the Build Event Protocol API

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#2968]
Add documentation related to the Build Event Protocol API (see [protos](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto))

Ulf has a change in flight: https://bazel-review.googlesource.com/#/c/3967/

**Comment by steren** [comment]
We agreed to add proper documentation when we release 0.5.1, which should contain a more stable Build Event Protocol

**Comment by buchgr** [comment]
In the design session I started to write something up about BEP and BES that could be published as a blog post and link to the design doc for more details.

**Comment by steren** [comment]
The top priority should be to have user documentation. Blog posts and design docs are less important.

**Comment by helenalt** [comment]
@michelleirvine and @buchgr  Can this be completed within the next few weeks, so we could complete the 0.6 Milestone "BEP API is stable", aimed for mid-end August.

**Comment by michelleirvine** [comment]
@buchgr I'll send you some edits for this file today - sorry for the delay.

**Comment by buchgr** [comment]
Thank you. Please comment on the pull request and not the google docs.

**Comment by buchgr** [comment]
Fixed by b4011da70a9c0b49a43109c7e2ad56a4874ab28e
