### ISSUE TITLE
"Compile Bazel from source" page is out-of-date

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#2970]
https://bazel.build/versions/master/docs/install-compile-source.html talks about running ./compile.sh.  This incorrect and should be updated or removed (if we have more up-to-date instructions elsewhere).

@brian-peloton noticed this on https://groups.google.com/d/msgid/bazel-discuss/CAP01z6KofAv_pi7bWgn3JONT87b-vE6c751LuGV0ezOYidbPiQ%40mail.gmail.com.

**Comment by tfarina** [comment]
@aehlig 

Klaus may be fixing this in https://bazel-review.googlesource.com/#/c/11351/.
