### ISSUE TITLE
Add "exclusive:<id>" tag that runs tests serially when they have the same <id>.

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#2972]
Reported by @gorset in https://github.com/bazelbuild/bazel/issues/2669#issuecomment-299619719:

> An alternative approach that would have worked well for us is to have a version of exclusive that only require running exclusively in relation to other tests with the same tag. Then such tests will only run one at a time, but still let other tests run concurrently, making the build faster.

**Comment by jmmv** [comment]
This might be a good idea, but given the age of this request, the lack of activity, and the efforts to tidy up our bug backlog... I'll close this as stale. Let me know if you still would have a valid use case for this though.
