### ISSUE TITLE
Within Bazel, java_proto_library hack prevents proto-to-proto dependencies

### ISSUE THREAD

**Issue by cvcal** [bazelbuild/bazel#2974]
src/main/protobuf uses tools/build_rules:genproto.bzl, to support grpc, but that prevents adding import statements to protobuf files. (see TODO in tools/build_rules/genproto.bzl) 

I would like to add invocation policy to the BEP, but cannot import the invocation_policy.proto definitions with the current hack. I could add it as a string, since BEP is currently for logging, but that feels like another hack-around.

Could we get rid of the hack and use the native protobuf rule?
@cgrushko

**Comment by cgrushko** [comment]
@damienmg how do you feel about copying `java_grpc_library` from  https://github.com/grpc/grpc-java/issues/2756#issuecomment-283195820 into the Bazel tree, so we can get rid of the `java_proto_library` macro?

**Comment by damienmg** [comment]
/cc @buchgr who has deep interest in making that story better.

I would be more into vendoring directly the repo, is there a problem with that? If we vendor the repository directly as a local repository it is easier to unbundle it if/when we decide to do it.

**Comment by buchgr** [comment]
@cgrushko https://bazel-review.googlesource.com/c/10711/ and https://github.com/grpc/grpc-java/pull/2975

@cvcal https://bazel-review.googlesource.com/c/10690/ 

Those are blocked by the bazel 0.5 release. So once that is released, we can merge those CLs.

**Comment by buchgr** [comment]
This was fixed a while back by commit `6073f1d41a102b70007356d1445c57b7f7533d78`.
