### ISSUE TITLE
"Failed to extract install_base_key" running bazel built on another system

### ISSUE THREAD

**Issue by qualiaa** [bazelbuild/bazel#2978]
### Description of the problem / feature request / question:

Attempting to build Bazel on an HPC cluster in the process of building TensorFlow, I ran into the problem described here: https://github.com/bazelbuild/bazel/issues/2534

My attempt to work around it was to build Bazel on a separate system, run the binary once to perform the self-extraction, and then upload the binary to the server I was working on (I also had to compile my own glibc and set the dynamic linker and rpath using [NixOS/patchelf](https://github.com/NixOS/patchelf)).

The binary runs fine locally, but on the cluster it immediately exits with error:

    $ ./bazel
    
    Failed to extract install_base_key: local file header signature for file A-server.jar not found
    

### Environment info
* Operating System:

CentOS 6.9

    $ uname -r
    2.6.32-696.el6.x86_64
    $ cat /proc/version 
    Linux version 2.6.32-696.el6.x86_64 (mockbuild@c1bm.rdu2.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) ) #1 SMP Tue Mar 21 19:29:05 UTC 2017
    $ cat /etc/issue
    CentOS release 6.9 (Final)
    Kernel \r on an \m
    

* Bazel version (output of `bazel info release`):
`[bazel release 0.4.5- (@non-git)]`

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
https://github.com/bazelbuild/bazel/releases/tag/0.4.5

###  Have you found anything relevant by searching the web?
[Possible point of error](https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/blaze.cc#L308)

**Comment by kchodorow** [comment]
> run the binary once to perform the self-extraction, and then upload the binary to the server I was working on 

Why are you running the binary once locally?  

One thing that might work is to upload the extracted install base (`bazel info install_base`) and then point bazel to it on the cluster (`bazel --install_base=/path/to/wherever/you/put/it build //...`).

**Comment by qualiaa** [comment]
Ah, that makes sense - I ran once because, failing to find `.cache/bazel` I incorrectly inferred that it was performing self-extraction and then swapping the binary/modifying in-place.

Your suggestion to use `--install_base` sounded hopeful, but unfortunately it exits with the same error:

    $ ./bazel-new --install_base=$HOME/bazel_install_data
    
    Failed to extract install_base_key: local file header signature for file A-server.jar not found
    
    $ ls $HOME/bazel_install_data/
    _embedded_binaries
    $ ls $HOME/bazel_install_data/_embedded_binaries
    A-server.jar	client		install_base_key  jdk.BUILD   linux-sandbox    xcode-locator
    build-runfiles	embedded_tools	java.version	  libunix.so  process-wrapper


I'm currently building an isolated tool-chain at the glibc/libstdc++ versions available on the cluster to double-check everything works locally.

**Comment by kchodorow** [comment]
Hmm, sounds like a bug in our zip extraction, then.  Assigning to @damienmg, who made the client use ijar for extraction.

Random idea: your cluster isn't big-endian by any chance, is it?

**Comment by damienmg** [comment]
Visibly the extraction happens successfully but an error code is returned. Can we get a lot more details about the running infrastructure (especially hardware) and how Bazel was compiled (gcc version, why not use devtoolset?, see http://stackoverflow.com/questions/42982735/how-to-compile-bazel-on-centos-6-x).

**Comment by qualiaa** [comment]
To be clear, I manually uploaded `$HOME/bazel_install_data/` from my local `.cache/bazel/...`. I've edited my code snippet to clarify.

I compiled Bazel locally with gcc-5.4.0. On the cluster, the same gcc version is available, and I've set the rpath of `bazel` to point at glibc-2.14, which is the latest version given by `cat bazel | strings | grep GLIBC`.

Dynamic linking:

    [phulgm@login1 ~]$ ldd bazel
    	linux-vdso.so.1 =>  (0x00007fff215fc000)
    	librt.so.1 => /home/dcs/phulgm/glibc2.14/lib/librt.so.1 (0x00007f4c8eaa7000)
    	libdl.so.2 => /home/dcs/phulgm/glibc2.14/lib/libdl.so.2 (0x00007f4c8e8a3000)
    	libpthread.so.0 => /home/dcs/phulgm/glibc2.14/lib/libpthread.so.0 (0x00007f4c8e686000)
    	libstdc++.so.6 => /csc/tinis/software/Core/GCCcore/5.4.0/lib64/libstdc++.so.6 (0x00007f4c8e4ff000)
    	libm.so.6 => /home/dcs/phulgm/glibc2.14/lib/libm.so.6 (0x00007f4c8e27b000)
    	libgcc_s.so.1 => /csc/tinis/software/Core/GCCcore/5.4.0/lib64/libgcc_s.so.1 (0x00007f4c8e264000)
    	libc.so.6 => /home/dcs/phulgm/glibc2.14/lib/libc.so.6 (0x00007f4c8ded8000)
    	/home/dcs/phulgm/glibc2.14/lib/ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2 (0x0000003f28800000)

Java version:

    [phulgm@login1 ~]$ echo $JAVA_HOME
    /csc/tinis/software/Core/Java/1.8.0_92

What kind of hardware information would you like? The CPU is an Intel(R) Xeon(R) E5-2630 v3 @ 2.40GHz. Here's the output of (`lscpu`)[https://pastebin.com/kQ1Zv5Vb] (little-endian).

**Comment by damienmg** [comment]
Thanks all the information I need is there.

The problem is the binary is edited after by setting the rpath, right? Which might mess up with zip data, you might want to run zip -A on Bazel. It stills needs to extract the install key to verify it does not need to extract all the remaining parts. Also Bazel contains other C++ binary and you are going to run in the rpath problem all the time.

Side-note: You shouldn't need root access to build bazel nor to bootstrap it.

**Comment by qualiaa** [comment]
Ah, of course, that makes sense. Running `zip -A bazel` has fixed the reported error. Thanks for your help!

I still run into problems (Bazel now hangs after extraction) but I think this is to do with my less-than-sane environment (different ld.so.2s, different rpaths) - when I get time I'll install an isolated binutils/gcc/glibc/libstdc++ on the cluster and use it to build Bazel properly. 

In case it's of interest, here's the last few lines of `strace` when it hangs

    rename("/home/dcs/phulgm/.cache/bazel/_bazel_phulgm/install/24ea1251e1e561edf41a36b2892891d2.tmp.21849", "/home/dcs/phulgm/.cache/bazel/_bazel_phulgm/install/24ea1251e1e561edf41a36b2892891d2") = 0
    stat("/csc/tinis/software/Core/Java/1.8.0_92/bin/java", {st_mode=S_IFREG|0755, st_size=7734, ...}) = 0
    access("/csc/tinis/software/Core/Java/1.8.0_92/bin/java", X_OK) = 0
    stat("/csc/tinis/software/Core/Java/1.8.0_92/jre/lib/rt.jar", {st_mode=S_IFREG|0755, st_size=66044468, ...}) = 0
    access("/csc/tinis/software/Core/Java/1.8.0_92/jre/lib/rt.jar", R_OK) = 0
    open("/home/dcs/phulgm/.cache/bazel/_bazel_phulgm/install/24ea1251e1e561edf41a36b2892891d2/_embedded_binaries/java.version", O_RDONLY) = 6
    read(6, "1.8\n", 4096)                  = 4
    read(6, "", 4096)                       = 0
    close(6)                                = 0
    pipe([6, 7])                            = 0
    clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f9efce4ca10) = 22406
    close(7)                                = 0
    read(6,
