### ISSUE TITLE
Document how to setup remote caching and its API

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#2980]
As seen in #904, remote caching is now fixed.
Bazel has REST and gRPC APIs that can be used to implement remote caching. This should be documented in the Bazel documentation, not only visible in the source code.

**Comment by steren** [comment]
Documentation exists buried in the source code: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/remote/README.md

We should move this in the regular docs/ folder

**Comment by steren** [comment]
The implementation of the feature is being tracked in https://github.com/bazelbuild/bazel/issues/904

**Comment by buchgr** [comment]
This can be closed: https://docs.bazel.build/versions/master/remote-caching.html
