### ISSUE TITLE
aws cli (python) cannot read files with non-English text under genrule

### ISSUE THREAD

**Issue by lazdmx** [bazelbuild/bazel#2986]
### Description of the problem 

aws cli (genrule) cannot process files containing non-ascii (Cyrillic) chars because of clean (`env -`) environment. So script like

```
aws apigateway update-model --cli-input-json file://$< > /dev/null && touch $@
```

cannot be done, if `$<` file has non-ascii symbols and the only way to make it work is to set category explicitly like

```
LC_CTYPE=UTF-8 aws apigateway update-model --cli-input-json file://$< > /dev/null && touch $@
```

### Environment info
* Operating System:
Darwin Dmitrys-iMac.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

* Bazel version (output of `bazel info release`):
release 0.4.5-homebrew

**Comment by brandjon** [comment]
I'm migrating the category python label to team-Rules-Python so we can delete it. Since this is a genrule / action\_env issue and not a python rules issue, I'll just remove the label without replacing it here.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
