### ISSUE TITLE
Feature Request: Objc Library Module Name

### ISSUE THREAD

**Issue by lswith** [bazelbuild/bazel#2988]
I'd like the ability to control the module name created by the objc_library rule. For more details refer to https://github.com/bazelbuild/rules_apple/issues/51.

**Comment by lswith** [comment]
any updates on this?

**Comment by c-parsons** [comment]
No updates yet -- we'll be chatting about this over the next few business days to prioritize.

**Comment by steeve** [comment]
Is there a hint so that we could fix it and perhaps submit a PR ?

**Comment by c-parsons** [comment]
We're not likely to get to this ourselves; we deemed this low priority internally.
If you'd like to go ahead and create a PR, you'll need to trace through ObjcLibrary.java and understand where the module name gets set; you can then hook through an attribute value to optionally change the default. 

(I don't know off the top of my head what decides the default module name in terms of the end command line.. You might start there? You can build an example with `-s` to see the command lines invoked in your build)

**Comment by steeve** [comment]
Makes total sense that's it's low priority.

That's exactly what I needed, we'll see how bad we want it and if so we'll submit a PR. Thanks!
