### ISSUE TITLE
experimental_ui: should respect `--show_timestamps` for actions

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2989]
Building with `--noexperimental_ui --show_timestamps --curses=no`:
```
INFO: (05-11 10:46:22.504) Loading complete.  Analyzing...
INFO: (05-11 10:46:22.506) Found 1 target...
INFO: (05-11 10:46:22.955) Building...
[2 / 138] (05-11 10:46:24.682) Writing file third_party/protobuf/3.2.0/libprotobuf_lite.a-2.params [for host]
[3 / 140] (05-11 10:46:24.725) Compiling third_party/protobuf/3.2.0/src/google/protobuf/io/zero_copy_stream.cc [for host]
[3 / 140] (05-11 10:46:24.756) Compiling third_party/protobuf/3.2.0/src/google/protobuf/stubs/atomicops_internals_x86_msvc.cc [for host]
```

Building with `--experimental_ui --show_timestamps --curses=no`:
```
INFO: (10:45:46.513) Analysed target //src/main/cpp:client.
INFO: (10:45:46.513) Found 1 target...
[0 / 41] BazelWorkspaceStatusAction stable-status.txt
[2 / 50] no action running
[3 / 178] no action running
[3 / 178] Compiling third_party/grpc/src/core/support/slice_buffer.c; 1s standalone ... (12 actions running)
[4 / 178] Compiling third_party/grpc/src/core/support/slice_buffer.c; 4s standalone ... (11 actions running)
```

EDIT: I got the logs mixed up first

**Comment by aehlig** [comment]
I believe that issue is already fixed upstream, with 598c90d0a24140ef81042efd3fd4aac9d48ec5ed (May 5, 2017). That change also changed the position of the timestamp so that timestamps are always at the beginning of line, reduces to second granualrity, and adds it to the progress messages (regardless if curses are used or not).

Please try with bazel at or after the mentioned commit and feel free to reopen, if the problem persists at head.

**Comment by laszlocsomor** [comment]
Thanks, confirmed that it's fixed now!
I however liked the old format (MM-DD HH:MM:SS.mmm), both the month/day and milliseconds were useful IMO. Can you say more about why the new format was simplified?

**Comment by aehlig** [comment]
> I however liked the old format (MM-DD HH:MM:SS.mmm), both the month/day and milliseconds were useful IMO.
> Can you say more about why the new format was simplified?

Month and Date were never included in the experimental_ui to reduce redundant
information; even at google, builds usually finish within a single day.

The milliseconds were removed as the accuracy was never that good anyway: we
could only report the time when event was printed, not when it was generated
(and there are synchronized blocks flushing to the terminal, etc). Moreover,
progress updates are rate limited (configurable, but something in the order
of 200ms makes sense), with nocurses even to at least a whole second; so there,
a higher precission would rarely help, so it seems good to save another
4 characters from the terminal width.

Do you have a concrete use case, where sub-second timestamps would help?

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by laszlocsomor** [comment]
Thanks, that's a compelling argument you presented :) As for use case, I thought about analyzing CI build logs, but come to think of it if an operation is abnormally slow then that that'll show up on the second-precision too.
