### ISSUE TITLE
Use "git archive" for (new_)git_repository rule

### ISSUE THREAD

**Issue by MarkusTeufelberger** [bazelbuild/bazel#2990]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

As discussed in https://github.com/bazelbuild/bazel/issues/2147, cloning a full repository might rarely be what you actually want to happen, in the end all you need is the state of the repository at a certain commit/tag, not the full history or capabilities to get random states.

The current solution with a sha256 field that reacts differently on github.com than on any other platform seems rather arbitrary to me...

I propose to use the "git archive" (https://git-scm.com/docs/git-archive) command with the --remote switch first and only fall back to current behaviour in case it is not supported by the remote and/or local git installation. The contents of that archive then could also be checked using e.g. sha256.

###  Have you found anything relevant by searching the web?

(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

Issue https://github.com/bazelbuild/bazel/issues/2147 and discussions about it seem to be related.

### Anything else, information or logs or outputs that would be helpful?
Github doesn't seem to offer a remote endpoint for git-archive, so a per-service list of popular services might still be useful. git archive still seems useful for non-github repositories though, perhaps also implicitly activated by the "sha256" parameter to not change current "clone" behaviour?

**Comment by kchodorow** [comment]
That seems like a good idea to make sha256 more widely useful (and, perhaps, speed up git_repository in some cases).

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
