### ISSUE TITLE
Windows MSYS2 - Bazel fails to run with exit code 127.

### ISSUE THREAD

**Issue by Helcaraxan** [bazelbuild/bazel#2994]
Though I am aware that this is likely to not be an issue with the Bazel code itself I am posting this to see whether somebody else has encountered the following problem and found the solution to it. It has been causing me signficant headaches the last two weeks while trying to switch our Windows builds to use Bazel.

### Description of the problem / feature request / question:

I am working on multiple Windows environments on which I have been able to use Bazel in the past without any trouble (desktop & VMs).

At some point a given environment becomes unable to even run a simple `bazel version` command and gives the following behaviour in an MSYS2 shell:
```
$> bazel version  # returns immediately
$> echo $?
127
```
This behaviour remains even if you replace `bazel` with the absolute path to the binary (even if it is already in the `PATH`).

There have not been any significant events between the moment where I can build and where I cannot run Bazel anymore although it is very likely that the enviroments settings (environment variables & co) have evolved because of our automatic system configuration management updates.

### If possible, provide a minimal example to reproduce the problem:

I have not yet found a way (despite trying hard) to find a reliable way to trigger the behaviour.

### Environment info

* Operating System: Windows 10 Pro - up-to-date
* Bazel version (output of `bazel info release`): 0.4.5 (before it stops working)

###  Have you found anything relevant by searching the web?

Nothing unfortunately.

**Comment by laszlocsomor** [comment]
1. Could it be that the disk is filling up, particularly `$TMP`?
2. What other symptoms do you observe, does it just no longer start after a while?
3. Is everything OK with the file permissions? See https://github.com/bazelbuild/bazel/issues/2810#issuecomment-300795901 for what I mean.

As workarounds:
1. kill all running Bazel servers (java processes in Task Manager)
2. add the `--client_debug` startup flag to Bazel, that'll print a bit of debugging info if the Bazel client manages to start up: `bazel --client_debug build (...)`
3. try using the msys-less version [1] (look for "bazel-msvc")

[1] https://storage.googleapis.com/bazel/0.5.0/rc6/index.html

**Comment by Helcaraxan** [comment]
Thank you for the quick points @laszlocsomor:

Conclusion as far as the diagnose with 0.4.5:
1. Disk is not filling up (over 150Gb left).
2. No other particular symptoms. Just Bazel that does not want to run by any means. It indeed no longer starts after while, and that while is not coming right after some other specific event.
3. File permissions are OK. To be sure I even ran `bazel version` as admin which had (as expected) all possible permissions set correctly but that did not help either.

For the work-arounds:
1. No bazel servers were running anyway.
2. The `--client_debug` option did not add any output. It looks like the client fails somewhere in the pre-`main()` initialisations / routines.
3. :tada:  Success :tada: Worked like a charm. I have my `bazel build` running again.

Bazel 0.5.0 just made me a very happy engineer. :smile:

**Comment by laszlocsomor** [comment]
Woohoo, great! I'm glad it helped :) Thanks for getting back with the good news.

FYI, 0.5.0 release is coming soon! This is still the release candidate.

**Comment by Helcaraxan** [comment]
Yes. I'm aware. Am following the release issue actively.
