### ISSUE TITLE
excessive 'ijar: skipping unknown attribute: "org.aspectj.weaver.MethodDeclarationLineNumber".' output

### ISSUE THREAD

**Issue by znull** [bazelbuild/bazel#2995]
as mentioned at https://groups.google.com/forum/#!topic/bazel-discuss/DmfErzHeBjI, use of bazel with aspectj can cause extremely verbose output, mostly consisting of hundreds or thousands of lines like:

`ijar: skipping unknown attribute: "org.aspectj.weaver.MethodDeclarationLineNumber".`

**Comment by kchodorow** [comment]
As a workaround, you could use [`--output_filter`](https://bazel.build/versions/master/docs/bazel-user-manual.html#flag--output_filter) to suppress that output.

However, as a larger issue, we probably shouldn't warn (or do it at a more verbose log level).

**Comment by guw** [comment]
Was this completed or just closed? Still seeing the excessive output with 6.3.2.

**Comment by fmeum** [comment]
Cc @cushon
