### ISSUE TITLE
CppCompileAction's extra action info is nondeterministic

### ISSUE THREAD

**Issue by brian-peloton** [bazelbuild/bazel#2996]
### Description of the problem / feature request / question:
The sources_and_headers in the cpp_compile_info is nondeterministic because it depends on whether the action's inputs have been discovered or not at the time it's emitted. This leads to overexecution and nondeterminism. I think the specific cause of my nondeterminism is .d-pruning. Specifically, `CppCompileAction#getExtraActionInfo()` relies in `#inputsDiscovered()` to decide how to fill out that field of the extra action info, and that can be true or false depending on how it races with the inputs being discovered on its shadowed action.

### If possible, provide a minimal example to reproduce the problem:
Any use of CppCompileAction's extra action info could be affected I think. My particular (private) repository and a combination of interleaved `bazel build <with the extra action>` and `bazel run --script_path=tempfile <with the extra action>` seems to trigger this very often. I can spend more time in a week or two on a more minimal way to reproduce if somebody wants.

### Environment info
* Operating System:
Linux (Debian jessie amd64)

* Bazel version (output of `bazel info release`):
0.5.0-rc2

I never saw problems with a version based on 088bbc614c184822050dfa5768d8c1281458c275, but I wasn't looking too hard so I may have not noticed. It definitely wasn't as bad.

###  Have you found anything relevant by searching the web?
#2659 sounds related. 5ea2b14a also touched this code, but I think it was broken before then. @lberki and @werkt sound like good people to look at this.

I think this patch might solve the problem, but I'm not sure if it causes other problems (I'm happy to submit this if it's the right approach):
```patch
diff --git a/src/main/java/com/google/devtools/build/lib/rules/cpp/CppCompileAction.java b/src/main/java/com/google/devtools/build/lib/rules/cpp/CppCompileAction.java
index 1b1884c..21a2ad7 100644
--- a/src/main/java/com/google/devtools/build/lib/rules/cpp/CppCompileAction.java
+++ b/src/main/java/com/google/devtools/build/lib/rules/cpp/CppCompileAction.java
@@ -764,7 +764,7 @@ public class CppCompileAction extends AbstractAction
     }
     info.setOutputFile(outputFile.getExecPathString());
     info.setSourceFile(getSourceFile().getExecPathString());
-    if (inputsDiscovered()) {
+    if (!discoversInputs) {
       info.addAllSourcesAndHeaders(Artifact.toExecPaths(getInputs()));
     } else {
       info.addSourcesAndHeaders(getSourceFile().getExecPathString());
```

**Comment by lberki** [comment]
I know :( It's kind of a hobby project of mine to clean this up, unfortunately, it's not working very well for two reasons: 1. it's fiddly and requires large chunks of make time which is not in abundance nowadays and various internal systems at Google rely on the broken semantics of extra actions. This was verified by way of trying to fix it and getting yelled at :)

So we'll have to live with this for a while...

**Comment by lberki** [comment]
At @AustinSchuh 's prodding on BazelCon, I realized that this got fixed in https://github.com/bazelbuild/bazel/commit/7af14dfdbd6addb779226c0a103b2a8dc72c16b1 : since we now execute the `CppCompileAction` before the `ExtraAction`, the race condition disappears.

We even take care to set `discoversInputs()` to true if there is only .d file pruning but no include scanning (as is usually the case for Bazel):

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/cpp/CppCompileAction.java#L341

So it's definitely correct (but please do verify that this is true -- I have only proved it correct, not tried it!)
