### ISSUE TITLE
Push Java built artifacts into Maven

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/bazel#30]
Allow Bazel to automatically push compiled jars into Maven.

**Comment by lberki** [comment]
I agree that this would be nice, but realistically, we have a bunch of other burning issues that we should take care of before. For now, Bazel's world ends with output files.

**Comment by davidzchen** [comment]
I think the best way to implement this would be to add rules for pushing to Maven similar to the [Gradle Maven Plugin](http://gradle.org/docs/current/userguide/maven_plugin.html).

**Comment by damienmg** [comment]
We have a whole install story we need to take care of and pushing to a maven repository is probably not going to be soon (especially because we have nothing to comply with maven version scheme)

**Comment by jin** [comment]
Please see https://github.com/graknlabs/bazel-distribution - these are now implemented as Starlark rules.
