### ISSUE TITLE
Compile Bazel on Power8

### ISSUE THREAD

**Issue by davideleoni90** [bazelbuild/bazel#3000]
Hi!

I am trying to compile Bazel from source on a Power 8 machine.

Here's the error I get when launching "bash compile.sh"

🍃  Building Bazel from scratch.......
🍃  Building Bazel with Bazel.
ERROR: No toolchain found for cpu 'ppc'. Valid cpus are: [
  piii,
  armeabi-v7a,
  x64_windows_msvc,
  x64_windows_msys,
  s390x,
  ios_x86_64,
].
INFO: Elapsed time: 2.181s

ERROR: Could not build Bazel

The output from uname -a:

4.7.4-200.fc24.ppc64 #1 SMP Thu Sep 22 17:40:37 UTC 2016 ppc64 ppc64 ppc64 GNU/Linux

Do you have any idea of why I get this error?

Thank you

**Comment by kchodorow** [comment]
I'm actually not sure why it doesn't pick this up automatically, but it seems to only be looking for crosstools in `@local_config_cc`, which doesn't contain a ppc crosstool (?).  You have to give the `--crosstool_top=//tools/cpp:default-toolchain` argument to make it look at //tools/cpp, which _does_ contain a ppc toolchain.

However, I'm not actually sure how to give extra arguments to the ./compile.sh script, so assigning to @damienmg for clarification on:

1. How to pass `--crosstool_top` into `./compile.sh`.
2. Why `@local_config_cc` doesn't contain the same toolchain as `@bazel_tools`.
3. Why they aren't both used to find toolchains.

**Comment by davideleoni90** [comment]
I solved it by myself making two small modifications:

1- added 
       default_toolchain {
  	  cpu: "ppc64"
  	  toolchain_identifier: "local_linux"
	}

   to tools/cpp/CROSSTOOL

2- in the file "tools/cpp/cc_configure.bzl" changed 

    "if result.stdout.strip() in ["power", "ppc64le", "ppc"]:"

    into "if result.stdout.strip() in ["power", "ppc64le", "ppc", "ppc64"]:"

I am not sure if both the modifications are actually necessary, but that's what I did and I successfully built bazel

**Comment by damienmg** [comment]
@davideleoni90: would you be willing to send a PR with those modification? They looks reasonable to me.

**Comment by damienmg** [comment]
(re-opened the bug because the code is not fixed)
