### ISSUE TITLE
How to replace http_jar in workspace.bzl on a Internet-limited machine?

### ISSUE THREAD

**Issue by kaituoxu** [bazelbuild/bazel#3005]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

My RHEL 6 server can not access Internet, I can only download .jar file in advance and put it in RHEL server.
But I don't know how to replace http_jar in the workspace.bzl, just like the way new_local_repository replace new_http_archive.
(Actually, I'm installing tensorflow from source on a Internet-limited server. The process is so complicated, I need to download tons of dependency files and solve tons of problems!)

### Environment info
* Operating System: RHEL 6.6

* Bazel version (output of `bazel info release`):0.4.5

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by dslomov** [comment]
@kchodorow any ideas?

**Comment by kchodorow** [comment]
There are a couple of options.  If you can run bazel once on another machine with `--experimental_repository_cache=/path/to/a/dir`, then move the cache to your RHEL server, you can use that option and cache directory. Bazel will check it first before downloading.  That way you don't have to even modify the workspace.bzl file.

Alternatively, `http_jar` creates a directory, so you could, again, run Bazel once on an internet-capable machine and then copy `$(bazel info output_base)/external/your_http_jar_name` to the RHEL server and use it as a `local_repository`.  In 0.5.0, there will be a new flag `--override_repository=path`, which would let you point to this directory without changing workspace.bzl.

**Comment by kaituoxu** [comment]
@kchodorow @dslomov Thanks a lot!
