### ISSUE TITLE
Have chocolatey package support different flavours of bazel?

### ISSUE THREAD

**Issue by petemounce** [bazelbuild/bazel#3006]
(Forked from #2692)

@damienmg @laszlocsomor et al - what, if anything, would you like me to do to the chocolatey package to represent the fact that there are now 3 flavours of bazel possible to get as I can see:
* current one
* one that doesn't have jdk7 bundled
* one that is msysless
?

I could add a flag to the installer to specify which zip to download, and therefore which checksum to use, but that would be a bit of work. Fine to do it, but thought I'd check first. At work, we'll be trying out the msysless one, I think, so will want to make that easy to install.

What is the lifetime of the different flavours expected to be? Is this kind of scenario one that would be beneficial to support now and/or in future?

Caveat: the package should only end up providing one bazel.exe - any other exes should be named for the flavour, so that they can coexist on a system and not have the user juggle the PATH to choose which one to use, I think.

(Making more than one package would, I think, not be the best approach - for the caveat above, for the maintenance overhead, and for the chocolatey package name dilution/confusion)

**Comment by laszlocsomor** [comment]
Hey Peter,

Thanks for raising this issue.

Timeline and plans: we'll phase out the msys-ful version by 0.6, but I don't know about plans with the JDK-ful vs. JDK-less version -- @philwo?

Choosing between versions: for now I think a dispatcher script would be the easiest way forward -- "bazel.bat" chooses between "bazel-{msys,msvc}-{with,without}-jdk.exe". WDYT?

Installer: I agree the script could take a parameter, or it could prompt the user to choose between downloading all binaries or just the default (still msys-ful for now). The installer script could also write "bazel.bat", which really only has to do `@bazel-<version>.exe %*`

**Comment by petemounce** [comment]
I'm not fond of the idea of a `bat` dispatcher, writing it or supporting it - very unfamiliar with shell programming with that beyond executing commands in sequence.

Also - how would `bazel.bat` choose between the `exe`s? An environment variable?

I'll scribble something that won't be good into a PR, and iterate...

**Comment by laszlocsomor** [comment]
Do you have specific concerns about the dispatcher? As for writing and maintaining it, I think it could be created by the installer, and would contain literally just one line:

```
@c:\path\to\bazel-msvc-0.5.0.exe
```

or whichever version the user selected during installation. So the version (path) would be hardcoded in the dispatcher, and the installer would re-create the dispatcher every time a new version is downloaded (or the user can update it manually if they wish). How does that sound?

**Comment by philwo** [comment]
IMHO it's not very useful for end users to install multiple flavors of Bazel in parallel and I'm also a bit scared of the dispatcher script. I think we should just decide on a default flavor and distribute that as bazel.exe. For 0.5.0 that might be MSYS + bundled JDK, later versions might be MSVC + bundled JDK.

Seems like Chocolatey supports a "params" flag that can be used to tune the package installation? https://chocolatey.org/docs/how-to-parse-package-parameters-argument - maybe that is an option for further customization if that is required?

**Comment by petemounce** [comment]
The issue is that the user would be running 
* `choco install bazel --params '/flavour:regular' #default
* `choco install bazel --params '/flavour:msvc'
* `choco install bazel --params '/flavour:no-jdk7'
to install in that case. 

That means
* the user has to reinstall if they want to try a different flavour - that means friction on testing out the different features
* the user has to use `--force` to do that
* the user has to discover the flag in the first place

I think it will be a better UX to instead to install all the `exe`s and provide an on-machine way of dispatching.

[This SO](https://stackoverflow.com/questions/357315/get-list-of-passed-arguments-in-windows-batch-script-bat) suggests that
```batch
c:\tools\bazel\bazel-%BAZEL_FEATURE_NAME%.exe %*
```
will do the trick - `%*` is apparently the equivalent of bash's `$@` to send all the arguments onward.

I was then thinking that the chocolatey package would download and install all the available bazel features by default, and then set the environment variable according to which one the user wants to use initially.

I don't particularly want to create one chocolatey package per build flavour, since
* the flavours are transient - they'll come and go, so the maintenance will be increased
* the approval process for chocolatey packages adds another overhead until the packages become trusted (except they might never be since they're, as above, transient)

**Comment by laszlocsomor** [comment]
@petemounce : SGTM for the envvar-based approach too. I forgot to add `%*` to my code snippet (updated).

**Comment by philwo** [comment]
FYI, there's no "JDK7" thing on Windows. JDK7 is the old deprecated version that we still keep around for people who cannot upgrade their system JDK to JDK8. It will go away with 0.5.1.

The flavours for Windows are:
bazel-0.5.0rc6-windows-x86_64.exe = MSYS, bundled OpenJDK8
bazel-0.5.0rc6-without-jdk-windows-x86_64.exe = MSYS
bazel-msvc-0.5.0rc6-windows-msvc-x86_64.exe = MSVC, bundled OpenJDK8
bazel-msvc-0.5.0rc6-without-jdk-windows-msvc-x86_64.exe = MSVC

What's the difference?
"MSYS" is using the default MSYS-built launcher, that will be going away with Bazel 0.6.0.
"MSVC" is using the new MSVC-built launcher, that is great, but not ready to be the default yet. It will become the default and only launcher option (AFAIK) with Bazel 0.6.0.

The "bundled OpenJDK8" versions do not require an installed JDK on the machine. We made these because many people seem to think that installing a JDK is annoying and they just want to use the software. The versions without a bundled OpenJDK8 require an installed JDK8. Functionally they should be identical.

**Comment by petemounce** [comment]
Also, could the inconsistency with package naming please be addressed?
```
https://storage.googleapis.com/bazel/0.5.0/rc6/bazel-0.5.0rc6-windows-x86_64.zip 
https://storage.googleapis.com/bazel/0.5.0/rc6/bazel-0.5.0rc6-without-jdk-windows-x86_64.zip 
https://storage.googleapis.com/bazel/0.5.0/rc6/bazel-msvc-0.5.0rc6-windows-msvc-x86_64.zip 
```

Could it become standardised on `bazel-<version>-<platform>-<arch>-<build flavour>.zip`? 

If not that, then a consistent order to the tokens, and no repetition?

**Comment by philwo** [comment]
The file names are indeed a bit embarrassing. 😊

Would these look OK?
bazel-0.5.0rc6-windows-x86_64.exe
bazel-0.5.0rc6-windows-x86_64-without-jdk.exe
bazel-0.5.0rc6-windows-x86_64-msvc.exe
bazel-0.5.0rc6-windows-x86_64-without-jdk-msvc.exe

**Comment by petemounce** [comment]
That would be fine, though it would make the automation slightly easier if the `bazel-0.5.0rc6-windows-x86_64.exe` "regular" one _also_ had a flavour (like "standard", "regular", etc) so that the dispatcher and so on don't have to do string manipulations, and so the environment variable posited earlier in the thread doesn't have to have a `-` prefix, and hacks like that.

Since what's going to be in the PATH is `bazel.bat`, invokable via `bazel` the name of the underlying exe can be descriptive, I think.

**Comment by philwo** [comment]
@petemounce Sounds good! I'll have a look at our scripts to see how I can tweak them to give better names and will report back.

**Comment by laszlocsomor** [comment]
Thanks to both of you! I agree with Peter that a structured name would be a lot easier; it also clarifies which version is which without having to know that the default is msys-ful.

**Comment by damienmg** [comment]
Adding some questions:

- Why would flavour be after the platform?
- Why still ship the without jdk version? If you don't ship it, the msysless is the only flavour you want to maintain and in the long term you can just plan for one variation: the not yet ready.

I also dislike encoding a flavour on the default flavour, if we can avoid it (the simpler the default name is the better).

Also the reason msvc flavour is after the platform name is that because when it was introduced it was as a platform name. This is not fixable easily but I have a series of patch to our CI where it should be easy to fix after.

In the time being we can probably rename using some shell magic in the time being and the new names would appear on the next rc that include it.

**Comment by damienmg** [comment]
I agree if we already encode the version in the .exe, but I actually wonder why it is done that way? Why don't we zip a bazel.exe? Anyway if it only touch the .exe file installed by chocolatey the user won't see it that's fine, but if we special case in everything we will see it also on the shell installer (also breaking some people in the process). If we do it only for chocolatey, we special case it anyway (wether it is on the dispatcher/installer or on our CI).

**Comment by laszlocsomor** [comment]
@petemounce : Another approach is to download the different variants into separate directories, and rename all of them "bazel.exe", and create a junction that points to the one the user needs, e.g. "c:/bazel/current/bazel.exe" and "current" points to, say, "c:/bazel/releases/0.5.0-msvc-without-jdk".

@damienmg : 
> Why don't we zip a bazel.exe?

Sorry I don't understand this, can you explain?

> if we special case in everything we will see it also on the shell installer

I don't think that's necessary, we don't have to use the same naming convention on all platforms.

**Comment by damienmg** [comment]
On Mon, May 15, 2017, 6:53 AM László Csomor <notifications@github.com>
wrote:

> @petemounce <https://github.com/petemounce> : Another approach is to
> download the different variants into separate directories, and rename all
> of them "bazel.exe", and create a junction that points to the one the user
> needs, e.g. "c:/bazel/current/bazel.exe" and "current" points to, say,
> "c:/bazel/releases/0.5.0-msvc-without-jdk".
>

+1 that is consistent with Linux distribution approaches (e.g.
update-alternative)

@damienmg <https://github.com/damienmg> :
>
> Why don't we zip a bazel.exe?
>
> Sorry I don't understand this, can you explain?
>

I mean we create a bazel-0.5.0-windows-x86_64.zip that contains
bazel-0.5.0-windows-x86_64.exe, why don't we store directly a bazel.exe in
that zip?

if we special case in everything we will see it also on the shell installer
>
> I don't think that's necessary, we don't have to use the same naming
> convention on all platforms.
>

(Assuming you meant that we do not have to have the same flavours on all
platform) So we are special casing the default version on windows to be of
flavour "standard", that is to be compared to special casing in the wrapper
script.

**Comment by dslomov** [comment]
@petemounce do you have any numbers on how many people install bazel via chocolatey?
Frankly, I would be open to chocolatey package only containing oine version of Bazel, that version being msys-less (msvc) with bundled JDK. What say you?

**Comment by philwo** [comment]
@dslomov Download numbers are here, broken down by version if you scroll down: https://chocolatey.org/packages/bazel

0.4.5 had ~2000 downloads in total.

I would also prefer a simple package that just ships one default version (MSVC + bundled JDK sounds good).

**Comment by petemounce** [comment]
A different approach would be to include several binaries in the single zip file for Windows? Or at least, one zip file with whatever the default flavour is, and one zip with all of them, then a parameter to the package to tell it which zip to get.

UX for regular users is unaffected, UX for people with appetite to test is only affected by size of download, which is a one time hit per install. Both sets of users get a dispatcher ahead of the binary.

Maintenance is also reduced because there's still only one package, whose name isn't diluted by there being several variants that are transient over time.

**Comment by petemounce** [comment]
What are the download stats for non chocolatey Windows binaries by the way?

**Comment by laszlocsomor** [comment]
Re: @damienmg 

> I mean we create a bazel-0.5.0-windows-x86_64.zip that contains
> bazel-0.5.0-windows-x86_64.exe, why don't we store directly a bazel.exe in
> that zip?

Sure, that'd work too.

----
Re: @petemounce 

> A different approach would be to include several binaries in the single zip file for Windows? Or at least, one zip file with whatever the default flavour is, and one zip with all of them, then a parameter to the package to tell it which zip to get.

I'm fine either way.
Do we agree to go for the junction-based approach I proposed earlier?

> What are the download stats for non chocolatey Windows binaries by the way?

@steren Do we have stats about this?

**Comment by steren** [comment]
`https://api.github.com/repos/bazelbuild/bazel/releases` returns overall stats of Bazel downloads from GitHub release (used by install scripts I suppose)
For 0.4.4, we had:
bazel-0.4.4-windows-x86_64.zip : 3922
bazel-0.4.4-windows-x86_64.exe : 2697

**Comment by petemounce** [comment]
So bazel 0.4.4 is about 25% of those zip downloads, and 17% of total? Cool :)

**Comment by petemounce** [comment]
It would be the least amount of package-change if the zip file could contain more `exe`s, but that would also make the download universally larger, so people that weren't interested in the trial flavours would be impacted. One zip with the regular build (as now), and one for a new zip that contains the regular build and all current other flavours?

**Comment by petemounce** [comment]
I'm still not totally clear on what solution is desired?

If it's "make the package install bazel-msvc-0.5.0rc9-windows-msvc-x86_64.exe instead of bazel-0.5.0rc9-windows-x86_64.exe" then that's trivial; say the word and I'll issue the PR.

If it's some form of "make the package install all the flavours then allow the user to pick which one to dispatch through" that's possible too, but:
* I don't want to do that unnecessarily - are you likely to want to pilot builds like this regularly?
* it would become easier if each of the `exe` builds were available within a single `zip`.

**Comment by dslomov** [comment]
I would go with "make the package install bazel-msvc-0.5.0rc9-windows-msvc-x86_64.exe instead of bazel-0.5.0rc9-windows-x86_64.exe"

**Comment by philwo** [comment]
+1

**Comment by petemounce** [comment]
Ok, I can do that. Will the `exe` names be consistentised before then? re: https://github.com/bazelbuild/bazel/issues/3006#issuecomment-301433472

**Comment by petemounce** [comment]
@laszlocsomor @dslomov @philwo - shall I create a fix-package release for bazel 0.5.0 so that it contains the msysless version, or wait for 0.5.1?

Doing so would mean that if people do `choco install bazel` they'll get bazel 0.5.0-msysless. It'll be possible to install 
* msysful via `choco install bazel --version 0.5.0`
* msysless version via `choco install --version 0.5.0.whateverthedateis`

**Comment by laszlocsomor** [comment]
@petemounce : I suggest that it to still install the msysful version, because that's the default for 0.5.0, and the msysless will only be the default with 0.6.0. If you do that (choco install bazel still installs 0.5.0-msysful), can users install choco install 0.5.0-msysless somehow?

**Comment by petemounce** [comment]
@laszlocsomor at the present time, since this has been merged, msysless will be the default for the _next release_. If that's 0.6.0, then that fits. If instead it's 0.5.1, then 0.5.1 will be msysless. Unless there's intervention.

No, it's not possible to make `choco install 0.5.0` msysless without some of the other work described above in this thread. If you think that bazel will have several release flavours reasonably often (like, 1 or more non-standard flavours per 2 releases, say), then I think that work is worth doing.

To recap in a single place, options:
0. make one choco package per flavour (in addition to existing `bazel`)
  * -ive - package approval per flavour, so lag time to introduce
  * -ive - maintenance overhead of both package code and release activity
  * -ive - dilute the initial user experience, since now the user has to know which `bazel-*` to install
  * +ive - simple
0. don't do anything, keep existing `bazel` as "standard"
  * -ive - friction to get for-test flavours, so less take-up, & later feedback
  * +ive - simple, no overhead
0. introduce `bazel-experimental` additional choco package whose payload changes depending on flavours available, but always also includes "standard". Introduce dispatcher to invoke chosen bazel, probably based on an environment variable. Keep existing package for "standard"
  * -ive - maintenance per release to make sure flavours are correct
  * -ive - longer install process for users
  * -ive - environment variable for users to know / manage (don't think that's much of a -ive)
  * -ive - dilutes `bazel-*` name - but not much, and clearly `-experimental` is for people willing to live on the bleeding wrist
  * -ive - batch file + environment variable dispatcher might end up requiring support from both me and the bazel team members. It shouldn't be allowed to grow beyond roughly `c:\tools\bazel\bazel-%BAZEL_FLAVOUR%-0.5.1.exe %*`
    * This would **require**  that the names of the `exe` binaries produced by your release process are regular, and that the "standard" one also has a flavour name, to avoid special casing anything or, basically, logic in the batch file.
    * It would also be _convenient_ for the release process to produce a `zip` containing _all_ of the flavours (including "standard"), to minimise the number of remote calls the choco package must make
  * +ive - able to introduce and remove flavours easily
  * +ive - once the choco package becomes trusted, fast publishes
0. Keep existing package, introduce a package parameter to choose which flavour it installs
  * -ive - horrible user experience - user has to know which flavour to install, then remember which one they installed, then uninstall / reinstall to change versions. Too much friction to get users who want to test to use, in my opinion

If you think it's worth doing, then option 3 would be my choice.

**Comment by laszlocsomor** [comment]
Hey, sorry about the long silence. I'll look at this thread now.

**Comment by laszlocsomor** [comment]
Ok caught up.

@petemounce :
> @laszlocsomor at the present time, since this has been merged, msysless will be the default for the next release. If that's 0.6.0, then that fits. If instead it's 0.5.1, then 0.5.1 will be msysless. Unless there's intervention.

SGTM. So from 0.5.1 on, choco will install msys-less. I'm fine with that -- although msys-less will be the default only in 0.6.0, that goal also implies (as I understand it) that we stop releasing msys-ful binaries altogether, meaning until 0.6.0 we keep releasing them. Therefore if choco already installs msys-less by default, that's fine, users who really need msys-ful will be able to download that.

As for the future, now I'm leaning towards choco installing just one flavour instead of all of them (with some dispatching mechanism), as @philwo said earlier:

> I would also prefer a simple package that just ships one default version (MSVC + bundled JDK sounds good). Considering that advanced users who have a need for a specific flavour can just download the .exe files they want, that seems like a reasonable way.

As for these options:

> 1. make one choco package per flavour (in addition to existing bazel)
> 2. don't do anything, keep existing bazel as "standard"
> 3. introduce bazel-experimental
> 4. Keep existing package, introduce a package parameter to choose which flavour it installs

I agree (3) offers the most for our users, but I'm not convinced about the need for it. Again as Philipp said, power users who are likely to be interested in dogfooding experimental versions can download them from the Releases page on GitHub, and users who just want a simple way to install Bazel (which is presumably the reason they use Choco in the first place) likely don't care about experimental verisons. Therefore I say let's do (2).

**Comment by petemounce** [comment]
I'd class myself as a power user; over here we manage our build machines with configuration management.

It's a lot more simple and convenient to depend on a package to install something than write a script to fetch that thing, especially if that script will change over time. That's indeed why I contributed the package in the first place.

I'll go for (2) at present (but only because you agreed that 0.5.1 can install msysless, since that's necessary for me at present and I'm not willing to wait a full release cycle for 0.6.0), and let's revisit if there are multiple build flavours in the future. That ok?

**Comment by laszlocsomor** [comment]
Sure, that sounds good!

Right, configuration management is a use-case I didn't think of. I hope my comment didn't come across harsh, I didn't mean to pass judgment in any way.

**Comment by petemounce** [comment]
> Right, configuration management is a use-case I didn't think of. I hope my comment didn't come across harsh, I didn't mean to pass judgment in any way.

You're fine :)
