### ISSUE TITLE
Java: productionize auto test suite

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#3007]
A number of test suites use runtime collection of test classes, which can be very slow on large classpaths. Instead, I (Ulf) have prototyped using an annotation processor to collect the test classes at compile time. For some of our own unit tests, the test runs more than 2x faster.

```
Test                    Before      After    % faster
CmdLineTests             9.966      2.676      73.15%
ActionsTests            13.588      9.765      28.14%
AnalysisTests Shard 1   73.1       69.088       5.49%
AnalysisTests Shard 2   70.201     72.822      -3.73%
CollectTests             6.794      2.757      59.42%
```

On larger integration tests, the benefit is smaller, but I'm not sure why I measured a slowdown in that one case - maybe eager class loading is beneficial in some cases?

In any case, we should make it easy to use this approach in Bazel, and also migrate our own tests. It doesn't work in all cases - it generally requires Junit 4, so it needs to be done in a way that's backwards compatible.

**Comment by ulfjack** [comment]
My code is here, but it needs to be cleaned up and ported to head:
https://github.com/ulfjack/bazel/tree/auto-java-test

**Comment by meisterT** [comment]
@ulfjack do you still plan to work on this?

cc @alandonovan

**Comment by alandonovan** [comment]
We should also not be afraid to list *Test.java source files in the BUILD file and *Test.class files in the test, and skip the vastly overcomplicated machinery of test setup.

Pretty much any time we reach for ClassPath.scan we are doing something wrong.

**Comment by ulfjack** [comment]
The current situation with Bazel is this:
```
java_test(name = "FooTest", srcs = ["FooTest.java"]) # Runs FooTest (if FooTest.java defines a class FooTest)
java_test(name = "FooTest", srcs = ["FooTest.java", "BarTest.java"]) # Runs FooTest, silently ignores BarTest
```

It is possible to explicitly list all the tests using a `@SuiteClasses` annotation, but that'll also silently ignore tests that are not listed there.

I think the reason for the classpath scan is to avoid accidentally not running tests, and also to avoid merge conflicts on the `@SuiteClasses` listing.

The code I wrote here uses a compile-time annotation processor to automatically generate the list of tests. It's also prone to accidentally missing tests if they're declared in a `java_library` rule that doesn't have the annotation processor.

That said, I'm not currently using this approach, though maybe I should fix that because it's annoying to have to update the suite declaration every time I add a test.

Note that this approach can be implemented fully outside of Bazel, except that it's nicer (and simpler) if the test runner supports it out of the box.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
