### ISSUE TITLE
fetch and query are broken on OS X with files or directories named any other capitalization of "BUILD"

### ISSUE THREAD

**Issue by mrdomino** [bazelbuild/bazel#301]
It's not uncommon for 3rd-party repos to have directories called e.g. "build". Just like with #297, OS X's case-insensitivity creates all kinds of hilarity around this.

Unlike in #297, it's probably enough in this case to just canonicalize the "BUILD"s we find and ignore any that wind up other than all-caps.

**Comment by kchodorow** [comment]
Oof, fun.  Thanks for the report.

**Comment by mrdomino** [comment]
FYI this also breaks query. As a concrete example, any subtree that contains [dropbox/djinni](https://github.com/dropbox/djinni) suffers from this. In particular, I can't ask for rdeps(..., //mylib:mylib) at the moment, since my 3rdparty/djinni/src/build is getting interpreted as a BUILD file.

This isn't too urgent for me; it's not breaking any functionality that I depend on at the moment. Just mentioning the broader scope and concrete example.

**Comment by vigilancer** [comment]
Same here.
On non-case-sensitive HFS you can't have BUILD file and ./build folder together in one place.
It makes hard to run gradle and bazel side by side out of the box.

**Comment by r351574nc3** [comment]
Is there a workaround for me? I am trying to build `golang.org/x/text`, but there's a `build` package there as well https://github.com/golang/text/tree/master/collate/build

**Comment by r351574nc3** [comment]
Looks like my problem is bazelbuild/rules_go#144

**Comment by jmmv** [comment]
The issues here have most likely been resolved or usability has improved significantly, given that we now run on macOS and Windows and people don't report this routinely.
