### ISSUE TITLE
How bazel deal with fat jar and relocating issue?

### ISSUE THREAD

**Issue by zhexuany** [bazelbuild/bazel#3011]
I am working on a java project. We were use maven for building until we cann't bear with the slowness. We decide to move to `bazel`. We figures almost everything out but two things we can not find any docs about these. First one is `fat jar`. Second one is `shading`.  I hope someone from the community could give us some hits about how to do these. 

We already googled everywhere but did not find satisfied solution. We noticed that there are some open issue across GitHub similar with our situation. But these issues have not been done yet. Maybe it is time to collect some thoughts and give an introduction about how to do these things. 

Thanks in advance. :)

**Comment by zhexuany** [comment]
https://github.com/pingcap/tikv-client-java/issues/30

**Comment by ittaiz** [comment]
Have you tried deploy_jar? It's a fat jar

**Comment by zhexuany** [comment]
@ittaiz I could not find any docs related with `deploy_jar`.

**Comment by ittaiz** [comment]
https://bazel.build/versions/master/docs/be/java.html#java_binary_implicit_outputs
Specifically:

> name_deploy.jar: A Java archive suitable for deployment (only built if explicitly requested).
Building the <name>_deploy.jar target for your rule creates a self-contained jar file with a manifest that allows it to be run with the java -jar command or with the wrapper script's --singlejar option. Using the wrapper script is preferred to java -jar because it also passes the JVM flags and the options to load native libraries.

> The deploy jar contains all the classes that would be found by a classloader that searched the classpath from the binary's wrapper script from beginning to end. It also contains the native libraries needed for dependencies. These are automatically loaded into the JVM at runtime.
> 
> If your target specifies a launcher attribute, then instead of being a normal JAR file, the _deploy.jar will be a native binary. This will contain the launcher plus any native (C++) dependencies of your rule, all linked into a static binary. The actual jar file's bytes will be appended to that native binary, creating a single binary blob containing both the executable and the Java code. You can execute the resulting jar file directly like you would execute any native binary.

**Comment by zhexuany** [comment]
We actually tried that. But we could figure out how to trigger this implicit output. Could you please tell me how to?

**Comment by ittaiz** [comment]
Sure thing-
Given a target named `baz` in package `//java/com/example/foo` you should call `bazel build //java/com/example/foo:baz_deploy.jar`. Note the `_deploy.jar` suffix.
In general btw I think you should really try to use SO and tag your question with Bazel since this doesn't sound like an issue with Bazel itself.

**Comment by zhexuany** [comment]
@ittaiz That works. 

How about another issue? The relocating issue? We used `maven-shade` plugin to do this. Is there any thing in bazel can do the same thing as we did before with maven?

**Comment by ittaiz** [comment]
There is a solution but unfortunately I don't remember it off the top of my
head.
I suggest you ask that on SO.
Bazel team members (as well as community members) monitor the tag and help
out.

**Comment by zhexuany** [comment]
Thanks. I did not find any useful info from SO. I leaves this issue open in case of any others people run into same situation.

**Comment by ittaiz** [comment]
Did you ask in SO a question about how to do shading?

**Comment by zhexuany** [comment]
I did. But no one gives me answer about this particular issue.

**Comment by ittaiz** [comment]
That's strange. I try to monitor the tag bazel and don't remember seeing
it. Link? I'll try to see (though I'm really really not sure I know the
answer)

**Comment by promiseofcake** [comment]
This is still an issue when attempting to bundle applications for the Spark runtime and it's provided Hadoop transitive dependencies (protobuf) being out of date (2.x, need 3.x).

**Comment by ittaiz** [comment]
I think @johnynek has a jarjar rule which might be what you're looking for.
@damienmg where would you put such a rule? java_rules? Standalone repo?

**Comment by promiseofcake** [comment]
@ittaiz that would be great! I tried playing with jarjar but it seemed to get caught up in the generated protobuf code. Is it already a Bazel rule, that would be wonderful.

**Comment by ittaiz** [comment]
I don't have such a rule but like I mentioned I've heard others who have it.
Sounds like something we need in the ecosystem.
I've mentioned the two people I know who might be able to help

**Comment by johnynek** [comment]
we use it in a few places. Works so far for us.

**Comment by hmemcpy** [comment]
Yes! Turns out that in our particular case, a combination of using SingleJar (via the deployable.jar implicit target) + applying jar_jar solves our needs pretty well!
The only thing that's missing is the ability to exclude things from the final deployable. I've just opened an issue, requesting an additional parameter be added to `scala_library` to support that (https://github.com/bazelbuild/rules_scala/issues/560)

**Comment by thundergolfer** [comment]
@ittaiz, @hmemcpy 

If you could publish code/writing on getting feature parity with Maven's shade plugin and Gradle's [shadow](https://github.com/johnrengelman/shadow) plugin that would be great. I know there's [`bazel_jar_jar`](https://github.com/johnynek/bazel_jar_jar), but haven't found it straightforward to use, and it seems that it requires having the shaded name in your source code, as in  

`import com.google.common` must become `import com.myorg.google.common` in source. This is something that isn't necessary with the Gradle plugin.

**Comment by smparkes** [comment]
>  it seems that it requires having the shaded name in your source code

FWIW, we're starting to use `bazel_jar_jar` and instead of changing source code, we run `bazel_jar_jar` on the client jars as well as the implementation jars. This avoids having to change source code at the cost of having to add an additional shading step and factor our dependences a bit more ...

**Comment by thundergolfer** [comment]
@smparkes Can you expand on this, it sounds interesting but I don't quite know your terminology in this: 

>  on the client jars as well as the implementation jars.

**Comment by sid374** [comment]
@hmemcpy @smparkes Could you please describe your build process/give some examples of how you got bazel jar_jar working. The documentation isn't very clear for someone who's new to bazel.

The problem I'm trying to solve is this: My project imports 2 external libraries (azure-sdk and cassandra-driver) that depend on different versions of guava (19 and 20). These versions of guava are not backwards compatible. I can not upgrade the cassandra-driver to a newer version, so I'm looking to shade azure-sdk with the version of guava that this requires. 

I'm using bazel-deps to download and include the external libraries. Any help/pointers are much appreciated. This is the most active discussion I've found on this topic yet.

**Comment by thundergolfer** [comment]
Hey @sid374, 

I did further work in this area, so can try help out. 

Say you want to shade `guava` inside `azure-sdk`. First you want to pull the `azure-sdk` and it's dependencies into your `WORKSPACE`:

```
maven_install(
    name = "maven_deps_with_guava_conflicts",
    artifacts = [
        "com.azure-sdk:1.23.0",
    ],
    fetch_sources = True,
    repositories = [
        "https://jcenter.bintray.com/",
    ],
```

Then you want to gather up the `azure-sdk` jar and all it's dependencies by using the `_deploy.jar` implicit target. Like this:

```
# This is only to generate a fat jar for further shading
java_binary(
    name = "azure-sdk",
    main_class = "none",
    runtime_deps = [
        "@maven_deps_with_guava_conflicts//:com_azure_sdk",
    ],
)
```

then you shade the fat jar. 

`shade_rules` is a files with something like this -> `rule com.google.common.** shaded.guava.@1`.

```
jar_jar(
    name = "shaded-fat-azure-sdk",
    # Fat jar
    input_jar = ":google-cloud-storage_deploy.jar",
    rules = "shade_rules",
)
```

Now you have a shaded library, `:shaded-fat-azure-sdk` , that you can put in your deps list.

**Comment by thundergolfer** [comment]
The above strategy has been used to solve the kind of problem you describe. Let me know if anything is unclear or if you need further details. There really should be a blog post about this...

**Comment by jwilliams-ocient** [comment]
Hi @joca-bt, I'm actually running into the issue you've brought up here. I have a resource `META-INF/foo/bar.baz` being added by two deps, A & B, in a fat-jar.

Are you aware of a workaround allowing me to "zap" `foo/bar.baz` from A?
