### ISSUE TITLE
Label documentation out of date.

### ISSUE THREAD

**Issue by AustinSchuh** [bazelbuild/bazel#3013]
https://bazel.build/versions/master/docs/build-ref.html#labels

The label section doesn't mention @reporitory//:target in the description of the syntax.  I would have expected either a description there or a link to a description.  (I was looking for a link to use in answering a question.)

Edit: https://bazel.build/versions/master/docs/external.html hints at the syntax, but isn't very clear.

**Comment by iirina** [comment]
Hi. You are right, the documentation could have been clearer. We are welcoming any contributions, so feel free to click the "Edit" button on [the Labels page](https://bazel.build/versions/master/docs/build-ref.html#labels) and send a patch.

**Comment by keertk** [comment]
Hi there! This page has [moved](https://bazel.build/concepts/labels) and has been updated. Please reopen or submit a PR if anything is still unclear. Thanks!
