### ISSUE TITLE
Comment in examples of runfiles provider is out of date.

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3014]
https://bazel.build/versions/master/docs/skylark/cookbook.html

The comments here talk about setting the fields on the struct returned, yet this is using the newer api of directly returning providers.

**Comment by iirina** [comment]
Do you mean to replace the word "struct" in "Remember, that the struct returned by the implementation function needs" with "provider DefaultInfo"?

**Comment by endobson** [comment]
I wasn't proposing any specific fix, so the direct answer to your question is no.

I don't think just that substitution is correct because you aren't constructing the fields directly of the provider. And the provider doesn't have a field called 'runfiles' even if it is constructed correctly.

Removing the last 3 lines seems like enough to me, since they seem to just add confusion. It seems obvious that you have to set runfiles somewhere, and the example shows where.

**Comment by iirina** [comment]
OK then. You are also welcome to contribute with a fix. :)

**Comment by brandjon** [comment]
The cookbook has long since been removed; I believe it's been migrated to bazelbuild/examples, under the rules directory. If there's anything out-of-date there, feel free to send a PR in that repository.
