### ISSUE TITLE
How to make bazel to be available for mips64el arch 

### ISSUE THREAD

**Issue by xzy256** [bazelbuild/bazel#3017]
I build the bazel source code at mips arch, i get error
<pre>
[root@localhost bazel]# ./compile.sh
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch
ERROR: Must specify PROTOC if not bootstrapping from the distribution artifact

--------------------------------------------------------------------------------
NOTE: This failure is likely occuring if you are trying to bootstrap bazel from
a developer checkout. Those checkouts do not include the generated output of
the protoc compiler (as we prefer not to version generated files).

* To build a developer version of bazel, do

    bazel build //src:bazel

* To bootstrap your first bazel binary, please download a dist archive from our
  release page at https://github.com/bazelbuild/bazel/releases and run
  compile.sh on the unpacked archive.

The full install instructions to install a release version of bazel can be found
at https://bazel.build/versions/master/docs/install.html#compiling-from-source
For a rationale, why the bootstrap process is organized in this way, see
https://bazel.build/designs/2016/10/11/distribution-artifact.html
--------------------------------------------------------------------------------
</pre>
our environments as follow,
arch: mips64el
os : fedora 21
gcc version: 4.9.3-5
<pre>
[root@localhost cares]# uname -a
Linux localhost.localdomain 3.10.84 #1 SMP PREEMPT Wed Feb 8 16:03:10 CST 2017 mips64 mips64 mips64 GNU/Linux

[root@localhost cares]# protoc --version
libprotoc 2.5.0

[root@localhost cares]# java -version
openjdk version "1.8.0_25"
OpenJDK Runtime Environment (build 1.8.0_25-rc21-b17)
OpenJDK 64-Bit Server VM (build 25.25-b02, mixed mode)
</pre>

How to build bazel for mips arch, could anybody give me some ideas?

**Comment by xzy256** [comment]
**i build relational protobuf and set env available PROTOC in /etc/profile, i get another error.**
<pre>
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
Building Bazel from scratch
ERROR: Must specify GRPC_JAVA_PLUGIN if not bootstrapping from the distribution artifact
</pre>
**as if, locking of grpc-java-plugin, When i build grpc-java github source code, getting error**  
<pre>
... ...
FAILURE: Build failed with an exception.
20:34:20.430 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
20:34:20.430 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Where:
20:34:20.431 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Build file '/home/loongson/下载/grpc-java/all/build.gradle' line: 31
20:34:20.431 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
20:34:20.431 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
20:34:20.432 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] A problem occurred evaluating project ':grpc-all'.
20:34:20.432 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > A problem occurred configuring project ':grpc-protobuf-lite'.
20:34:20.432 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > unknown os.arch: mips64el
20:34:20.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
20:34:20.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
20:34:20.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
20:34:20.433 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
20:34:20.434 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED
</pre>

**could anybody give me some ideas?**

**Comment by iirina** [comment]
Hi,
`compile.sh` is not meant to be used like this, you need to get a bazel release and if you want to build a custom bazel, do it using `bazel build //src:bazel`. Have you tried this?

**Comment by xzy256** [comment]
thanks @iirina. I have a try. By the way, i should download zip source code, as if lacking something by using `git clone`.

**Comment by xzy256** [comment]
I download zip source code [bazel-0.4.5-dist.zip](https://github.com/bazelbuild/bazel/archive/0.4.5.zip) .Then unziping it and executing `bash ./compile.sh`, i get the next error.
<pre>
[root@localhost bazel-0.4.5]# bash ./compile.sh
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch.......
🍃  Building Bazel with Bazel.
.WARNING: /tmp/bazel_qadO1W8B/out/external/bazel_tools/WORKSPACE:1: Workspace name 
in /tmp/bazel_qadO1W8B/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name  given in the repository's definition (@bazel_tools); 
this will cause a build error in future versions.
ERROR: No toolchain found for cpu 'unknown'. Valid cpus are: [
  piii,
  armeabi-v7a,
  x64_windows_msvc,
  s390x,
  mips64el,
  ios_x86_64,
].
INFO: Elapsed time: 8.248s
ERROR: Could not build Bazel
</pre>
I upload change log at github, see [1.patch](https://github.com/xzy256/bazel-mips64el/blob/master/1.patch) ,but why does occur **ERROR: No toolchain found for cpu 'unknown'**? I have added mips64el arch, could you give me some tips?

**Comment by xzy256** [comment]
I trace the source of causing error, it is `String desiredCpu = cpuTransformer.apply(config.getCpu());`. The` desiredCpu=='unknown'`, my tracing log as follow,` vim src/main/java/com/google/devtools/build/lib/rules/cpp/CrosstoolConfigurationLoader.java`. 
<pre>
330     String selectedIdentifier = null;
331     // We use fake CPU values to allow cross-platform builds for other languages that use the
332     // C++ toolchain. Translate to the actual target architecture.
333     String desiredCpu = cpuTransformer.apply(config.getCpu());
334     System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"); 
335     System.out.println("desiredCpu="+desiredCpu);
336     System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
337     for (CrosstoolConfig.DefaultCpuToolchain selector : release.getDefaultToolchainList()) {
338       System.out.println("##########################selector.getCpu()="+selector.getCpu());
339       if (selector.getCpu().equals(desiredCpu)) {
340         selectedIdentifier = selector.getToolchainIdentifier();
341         break;
342       }
343     }
344 System.out.println("------------------------------------------------");
345 System.out.println("selectedIdentifier="+selectedIdentifier);
346 System.out.println("------------------------------------------------");
</pre>
then, executing `bash -x ./compile.sh` ,geting output log as follow.
<pre>
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
desiredCpu=unknown
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
##########################selector.getCpu()=piii
##########################selector.getCpu()=armeabi-v7a
##########################selector.getCpu()=x64_windows_msvc
##########################selector.getCpu()=s390x
##########################selector.getCpu()=ios_x86_64
##########################selector.getCpu()=mips64
------------------------------------------------
selectedIdentifier=null
------------------------------------------------
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
desiredCpu=unknown
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
##########################selector.getCpu()=piii
##########################selector.getCpu()=armeabi-v7a
##########################selector.getCpu()=x64_windows_msvc
##########################selector.getCpu()=s390x
##########################selector.getCpu()=ios_x86_64
##########################selector.getCpu()=mips64
------------------------------------------------
selectedIdentifier=null
------------------------------------------------
ERROR: No toolchain found for cpu 'unknown'. Valid cpus are: [
  piii,
  armeabi-v7a,
  x64_windows_msvc,
  s390x,
  ios_x86_64,
  mips64,
].
</pre>

How should i do fix this error?

**Comment by xzy256** [comment]
The latest patch see https://github.com/xzy256/bazel-mips64el/blob/master/1.patch. Adding mips arch suport and configuring toolchain can fix `ERROR: No toolchain found for cpu 'unknown'`. After fixing above error,  i get a new error.
<pre>
INFO: From Compiling third_party/ijar/ijar.cc:
third_party/ijar/ijar.cc: In member function 'virtual bool devtools_ijar::JarStripperProcessor::Accept(const char*, devtools_ijar::u4)':
third_party/ijar/ijar.cc:66:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (filename_len >= CLASS_EXTENSION_LENGTH) {
                    ^
ERROR: /home/loongson/??/bazel-0.4.5/src/main/tools/BUILD:3:1: Linking of rule '//src/main/tools:process-wrapper' failed: gcc failed: error executing command 
  (cd /tmp/bazel_LEiC5RX6/out/execroot/bazel-0.4.5 && \
  exec env - \
    PATH=/lib/jvm/java-1.8.0-openjdk-1.8.0.25-6.b17.rc21.fc21.loongson.mips64el/bin:/usr/local/bin/:/lib/jvm/java-1.8.0-openjdk-1.8.0.25-6.b17.rc21.fc21.loongson.mips64el/bin:/usr/local/bin/:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/loongson/.local/bin:/home/loongson/bin \
  /usr/lib64/ccache/gcc -o bazel-out/local-opt/bin/src/main/tools/process-wrapper -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/lib64/ccache -B/usr/bin '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -pass-exit-codes -Wl,--gc-sections -Wl,@bazel-out/local-opt/bin/src/main/tools/process-wrapper-2.params): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/usr/bin/ld: .gnu.hash is incompatible with the MIPS ABI
collect2: error: ld returned 1 exit status
Target //src:bazel failed to build
INFO: Elapsed time: 812.944s, Critical Path: 771.14s
+ fail 'Could not build Bazel'
+ local exitCode=1
+ [[ 1 = \0 ]]
+ echo

+ echo 'ERROR: Could not build Bazel'
ERROR: Could not build Bazel
+ exit 1
</pre>

**Comment by iirina** [comment]
Seems there is an incompatibility between gnu hash and MIPS, but I cannot figure out where it is coming from. @philwo do you have any idea?
@xzy256 There seems to be a couple of fixes for this incompatibility on some forums, but they don't look very pretty.

**Comment by iirina** [comment]
I have investigated a bit and the use of the flag `--hash-style=gnu` is causing this error. @mhlopko informs me that the flag will be gone in bazel 0.5. You can try our latest RC for 0.5 and download the dist zip from [here](https://storage.googleapis.com/bazel/0.5.0/rc9/index.html).
I hope this helps.

**Comment by xzy256** [comment]
@iirina It is from` ./tools/cpp/CROSSTOOL`. You can change `-Wl,--hash-style=gnu` into `-Wl,--hash-style=sysv` for fixing it. By the way, the ld version must be 2.17 or higher.

After fixing above error, i get new error.
<pre>
ERROR: /home/loongson/bazel-0.4.5/src/java_tools/singlejar/BUILD:77:1: error executing shell command: 'set -e;rm -rf bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output;mkdir -p bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
unzip -qn bazel-ou...' failed: bash failed: error executing command 
  (cd /tmp/bazel_Y3I17siq/out/execroot/bazel-0.4.5 && \
  exec env - \
    PATH=/lib/jvm/java-1.8.0-openjdk-1.8.0.25-6.b17.rc21.fc21.loongson.mips64el/bin:/usr/local/bin/:/lib/jvm/java-1.8.0-openjdk-1.8.0.25-6.b17.rc21.fc21.loongson.mips64el/bin:/usr/local/bin/:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/loongson/.local/bin:/home/loongson/bin \
  /bin/bash -c 'set -e;rm -rf bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output;mkdir -p bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
unzip -qn bazel-out/host/bin/src/java_tools/singlejar/libbootstrap.jar -d bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
unzip -qn bazel-out/host/bin/src/java_tools/singlejar/libskylark-deps.jar -d bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
unzip -qn third_party/auto/auto-common-0.3.jar -d bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
</pre>
<pre>
[/home/loongson/bazel-0.4.5/src/java_tools/singlejar/BUILD]
76 
 77 bootstrap_java_binary(
 78     name = "bootstrap",
 79     srcs = glob(
 80         ["java/**/*.java"],
 81         exclude = ["java/**/SingleJarWorker.java"],
 82     ) + [
 83         "//src/java_tools/singlejar/java/com/google/devtools/build/zip:java-srcs",
 84     ],
 85     main_class = "com.google.devtools.build.singlejar.SingleJar",
 86     visibility = ["//visibility:public"],
 87     deps = [
 88         ":skylark-deps",
 89         "//src/main/java/com/google/devtools/build/lib:shell-skylark",
 90     ],
 91 )
</pre>

**Comment by xzy256** [comment]
@iirina  i have a try `bazel-0.5-rc9`, but error is same.Could you please give me same tips ?
<pre>
INFO: From JavacBootstrap src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libbootstrap_JarOwner.jar [for host]:
warning: Implicitly compiled files were not subject to annotation processing.
  Use -proc:none to disable annotation processing or -implicit to specify a policy for implicit compilation.
1 warning
ERROR: /home/loongson/bazel-0.5.0rc9/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/BUILD:151:1: error executing shell command: 'set -e;rm -rf bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/bootstrap_deploy.jar.build_output;mkdir bazel-out/host/bin/src/java_tools/buildjar/java/com/google/d...' failed: bash failed: error executing command 
  (cd /tmp/bazel_XapT5DY6/out/execroot/bazel-0.5.0rc9 && \
  exec env - \
    PATH=/lib/jvm/java-1.8.0-openjdk-1.8.0.25-6.b17.rc21.fc21.loongson.mips64el/bin:/usr/local/bin/:/lib/jvm/java-1.8.0-openjdk-1.8.0.25-6.b17.rc21.fc21.loongson.mips64el/bin:/usr/local/bin/:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/loongson/.local/bin:/home/loongson/bin \
  /bin/bash -c 'set -e;rm -rf bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/bootstrap_deploy.jar.build_output;mkdir bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/bootstrap_deploy.jar.build_output
unzip -qn bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libbootstrap.jar -d bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/bootstrap_deploy.jar.build_output
</pre>

**Comment by xzy256** [comment]
@iirina bazel-0.4.5 build failed on mips, because the `io-bazel` can't match build workspace. Bazel-0.5.0 fixes this bug, i create a new question see #3068 .Please close this question, thanks.
