### ISSUE TITLE
Bazel test cases timing out on CentOS 7.

### ISSUE THREAD

**Issue by sowani** [bazelbuild/bazel#3019]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I have observed that certain Bazel test cases from the test suite are timing out on CentOS 7 (kernel version 3.10.0-123.el7.x86_64). For example, I tried bazel_coverage_test (using command bazel test //src/test/shell/bazel:bazel_coverage_test) and observed that it just hangs. I tried tracing it using strace (log attached).

This seems to be CentOS specific behavior as I did not observe this on Ubuntu 16.04. Has anybody observed this? Is this a regression as far as CentOS is concerned?

### If possible, provide a minimal example to reproduce the problem:
bazel test //src/test/shell/bazel:bazel_coverage_test

### Environment info
* Operating System:
CentOS 7 on x86_64
kernel version 3.10.0-123.el7.x86_64

* Bazel version (output of `bazel info release`):
release 0.4.5-2017-05-17 (@7184b6f)

### Anything else, information or logs or outputs that would be helpful?
log file 
[log.txt](https://github.com/bazelbuild/bazel/files/1007554/log.txt)

attached.

**Comment by sowani** [comment]
I upgraded CentOS kernel version to the latest available (4.11.1-1.el7.elrepo.x86_64 #1 SMP Sun May 14 11:54:29 EDT 2017). However the issue is still there.

**Comment by truatpasteurdotfr** [comment]
timeout also on 3.10.0-514.16.1.el7.x86_64 ref thread at https://lists.centos.org/pipermail/centos-devel/2017-May/015877.html

**Comment by sowani** [comment]
I have observed this same issue with the same set of test cases on RHEL 7.3 as well.

**Comment by sowani** [comment]
Here is a snippet from strace output on CentOS:

poll([{fd=7, events=POLLIN}, {fd=8, events=POLLIN}, {fd=9, events=POLLIN|POLLOUT}], 3, 1000) = 1 ([{fd=9, revents=POLLOUT}])
getsockopt(9, SOL_SOCKET, SO_ERROR, [0], [4]) = 0

So as I understand it, fd (7, 8, 9) are being polled. Any idea what these FDs are used for by bazel?

Next, a message is sent to fd 9:
sendmsg(9, {msg_name(0)=NULL, msg_iov(3)=[{"PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n", 24}, {"\0\0\22\4\0\0\0\0\0\0\2\0\0\0\0\0\3\0\0\0\0\0\4\0\0\377\377", 27}, {"\0\0\4\10\0\0
clock_gettime(CLOCK_MONOTONIC, {8489674, 379142208}) = 0

3 more messages are sent to fd 9 following above message. FDs 7,8,9 are again polled. This time there is a message on FD 9:

poll([{fd=7, events=POLLIN}, {fd=8, events=POLLIN}, {fd=9, events=POLLIN}], 3, 999) = 1 ([{fd=9, revents=POLLIN}])

A message is received on fd 9:
recvmsg(9, {msg_name(0)=NULL, msg_iov(1)=[{"\0\0\f\4\0\0\0\0\0\0\3\177\377\377\377\0\4\0\20\0\0\0\0\4\10\0\0\0\0\0\0\17"..., 8192}], msg_controllen=0, msg_flags=0}, 0) = 34

Trouble appears to begin after this:
sendmsg(9, {msg_name(0)=NULL, msg_iov(1)=[{"\0\0\0\4\1\0\0\0\0", 9}], msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 9
recvmsg(9, 0x3ffffb2ae998, 0)           = -1 EAGAIN (Resource temporarily unavailable)

The same behavior is also observed on RHEL as well. Any idea what could be going on?

Thanks,
Atul.

**Comment by philwo** [comment]
If this is still happening, please re-open this bug.
