### ISSUE TITLE
Bazel fails during analysis phase - "Server terminated abruptly"

### ISSUE THREAD

**Issue by ains** [bazelbuild/bazel#3020]
### Description of the problem / feature request / question:

When running Bazel in CI and building targets with rules_go the build will infrequently fail with the message

```
Server terminated abruptly (error code: 14, error message: '', log file: '...')
```

The "jvm.out" file given as the log file is empty. The last message in the bazel java.log file is
"INFO: Starting analysis"

### If possible, provide a minimal example to reproduce the problem:

N/A

### Environment info
* Operating System: Ubuntu 16.04, build inside docker container.

* Bazel version (output of `bazel info release`):

Bazel 0.4.5

###  Have you found anything relevant by searching the web?

Same issue is seen here, but no resolution in sight
https://github.com/bazelbuild/bazel/issues/2939

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by ains** [comment]
Turns out this was the OOM killer, the CI machines were running out of memory during the Bazel run.

**Comment by iirina** [comment]
I will close this since it wasn't a bazel issue.

**Comment by ry** [comment]
Is there no way for bazel to print OOM? This is very difficult to debug.

**Comment by michaeljs1990** [comment]
When the OOM killer comes into play all bets are off. OOM just sends a SIGKILL nothing special that would be possible for bazel to determine why it's process is getting killed vs some random person killing one off. Possibly you could use some heuristic to say a process was killed and I see that I'm using X% of allocated memory so maybe OOM?

**Comment by mirh** [comment]
Checking if dmesg has an oom-killer entry with <your-process-name> on the second of the SIGKILL would be as effective as it is dirty, also, imo.

**Comment by ZLonnie** [comment]
I also have same problem, but  solved by setting swap memory. more detail see http://www.jishuyiliu.com/archives/209.html

**Comment by orioli** [comment]
same issue here when running on 800MB ram

**Comment by andreamlin** [comment]
My bazel target had been running fine on my local desktop, but failing with the aforementioned `error 14...`. Solved this by constraining bazel's memory usage (https://stackoverflow.com/questions/34382360/decrease-bazel-memory-usage).

**Comment by eduamf** [comment]
> same issue here when running on 800MB ram

But with 22G of RAM seems to be difficult.
Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/home/cosev/.cache/bazel/_bazel_cosev/86567ccce8de0c1bf6e7f43fe83a5013/server/jvm.out')

Maybe the jvm configuration?

**Comment by cse19922021** [comment]
@eduamf use --jobs=1. Please note that you have to place this argument after "build" not before it.

**Comment by jxramos** [comment]
Can anyone shed any insight into the file `jvm.out`. Does this file always get rendered by the bazel server and is kept empty until some error messages need to populate into it? I'm finding an empty file on my local system, but in the remote server where the bazel command is operating I've yet to cat the file to see what's in there.

```
Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/home/org_x/.cache/bazel/_bazel_org_x/073241073e47b03b6e3590c37cd049f8/server/jvm.out
```

What exactly does an empty file designate, does it imply that the server ran out of memory? Is the file normally empty and populated per server shutdown or something? What are the persistence, rolling behavior, and lifetime for this file?

**Comment by hsl89** [comment]
@cse19922021 I encountered the same build issue, why setting `--jobs=1` would fix it? It seems to be a very inefficient way of using cpu cores. Plus, building large project like tensorflow would probably take forever if `--jobs=1`

**Comment by mirh** [comment]
Because fewer jobs = less used RAM too?
