### ISSUE TITLE
Project's .bazelrc should inherit ~/.bazelrc

### ISSUE THREAD

**Issue by jart** [bazelbuild/bazel#3022]
TensorFlow `./configure` outputs a `tensorflow/.bazelrc` file. But this causes Bazel to ignore what's in `~/.bazelrc`. It would be nice if the project-level one inherited and overrode the home directory one.

**Comment by ittaiz** [comment]
Isn't there some sort of inheritance already?
I was really sure I read there is

**Comment by ittaiz** [comment]
@iirina according to this [blog post](https://blog.bazel.build/2015/07/01/Configuration-File.html) it sounds like one can currently circumvent this issue by having a `~/.bazelrc` file and a `my-proj/tools/bazel.rc` file where `~/.bazelrc` will inherit from the `tools/bazel.rc` one. Is that correct?
cc @damienmg

**Comment by damienmg** [comment]
Yes this is correct. however .bazelrc will take precedence over ~/.bazelrc (so if you have a .bazelrc in your workspace, it will ignore ~/.bazelrc). There is a long standing issue in fixing our .bazelrc order.

**Comment by ittaiz** [comment]
@cvcal should this be closed in favor of #4502?

**Comment by cvcal** [comment]
Probably, there are a bunch of these old bugs, I haven't looked through all of them. The proposal in #4502 leaves these both to be read independently, so that should address the problem.

**Comment by gregestren** [comment]
On account of the last comment, I'm going to mark this closed du to #4502. 

Feel free to re-open if something is still missing.
