### ISSUE TITLE
--explain doesn't give actionable feedback

### ISSUE THREAD

**Issue by AustinSchuh** [bazelbuild/bazel#3026]
### Description of the problem / feature request / question:

I've got build --explain=/tmp/log.txt in my ~/.bazelrc file.  I'll see spurious re-builds, generally after the bazel server restarts.  Most of the time, I don't see anything actionable in the log.  An example is:

'''
Build options: --watchfs --workspace_status_command=scripts/bazel_workspace_status.sh --experimental_multi_threaded_digest --test_tag_filters=-nightly_only,-hercules_only --host_crosstool_top=//tools/cpp:toolchain --stamp --features=use_libstdcxx --test_env='ASAN_OPTIONS=allow_user_segv_handler=1' --strip=never --crosstool_top=//tools/cpp:toolchain --custom_malloc=//tools/cpp:malloc --show_result=15 --experimental_sandbox_base=/dev/shm/ --stripopt=--strip-all --sandbox_fake_hostname --sandbox_fake_username --sandbox_tmpfs_path=/tmp/ --local_resources=60000,20,5000 --explain=/tmp/bazel_explain.log --verbose_explanations --experimental_ui --experimental_ui_actions_shown=32 --compilation_mode=opt
Executing action 'BazelWorkspaceStatusAction stable-status.txt': unconditional execution is requested.
Executing action 'Compiling third_party/protobuf/src/google/protobuf/extension_set.cc [for host]': action command has changed.
New action: Compiling third_party/protobuf/src/google/protobuf/extension_set.cc [for host] 
  Command: tools/cpp/debian_amd64_compilers/clang
  Argument: '--sysroot=external/amd64_compilers_repo'
  Argument: -nostdinc
  Argument: -isystem
  Argument: external/clang_3_7_repo/lib/clang/3.7.1/include
  Argument: -isystem
  Argument: external/amd64_compilers_repo/usr/include/x86_64-linux-gnu
  Argument: -isystem
  Argument: external/amd64_compilers_repo/usr/include
  Argument: -Werror
  Argument: -Wall 
  Argument: -Wextra
  Argument: '-Werror=vla'
  Argument: -pipe 
  Argument: -ggdb3
  Argument: -pthread
  Argument: -U_FORTIFY_SOURCE
  Argument: '-D_FORTIFY_SOURCE=1'
  Argument: -fstack-protector
  Argument: -fPIE 
  Argument: -fcolor-diagnostics
  Argument: -fno-omit-frame-pointer
  Argument: -fno-strict-aliasing
  Argument: -DNDEBUG
  Argument: -ffunction-sections
  Argument: -fdata-sections
  Argument: -g0
  Argument: -g0
  Argument: -MD
  Argument: -MF
  Argument: bazel-out/host/bin/third_party/protobuf/_objs/protobuf_lite/third_party/protobuf/src/google/protobuf/extension_set.d
  Argument: '-frandom-seed=bazel-out/host/bin/third_party/protobuf/_objs/protobuf_lite/third_party/protobuf/src/google/protobuf/extension_set.o'
  Argument: -DGOOGLE_PROTOBUF_NO_RTTI
  Argument: -iquote
  Argument: .
  Argument: -iquote
  Argument: bazel-out/host/genfiles
  Argument: -iquote
  Argument: external/bazel_tools
  Argument: -iquote
  Argument: bazel-out/host/genfiles/external/bazel_tools
  Argument: -isystem
  Argument: third_party/protobuf/src
  Argument: -isystem
  Argument: bazel-out/host/genfiles/third_party/protobuf/src
  Argument: -isystem
  Argument: external/bazel_tools/tools/cpp/gcc3
  Argument: '-std=c++11'
  Argument: -isystem
  Argument: external/amd64_compilers_repo/usr/include/c++/4.9
  Argument: -isystem
  Argument: external/amd64_compilers_repo/usr/include/x86_64-linux-gnu/c++/4.9
  Argument: -isystem
  Argument: external/amd64_compilers_repo/usr/include/c++/4.9/backward
  Argument: -O2
  Argument: -fno-rtti
  Argument: -fno-exceptions
  Argument: -DHAVE_PTHREAD
  Argument: -Wall
  Argument: -Wwrite-strings
  Argument: -Woverloaded-virtual
  Argument: -Wno-sign-compare
  Argument: -Wno-unused-function
  Argument: -Wno-unused-parameter
  Argument: -Wno-deprecated-declarations
  Argument: -DGOOGLE_THIRD_PARTY_PROTOBUF
  Argument: -Wno-ignored-qualifiers
  Argument: -Wno-type-limits
  Argument: -Wno-unused-const-variable
  Argument: -Wno-unused-private-field
  Argument: -no-canonical-prefixes
  Argument: -Wno-builtin-macro-redefined
  Argument: '-D__DATE__="redacted"'
  Argument: '-D__TIMESTAMP__="redacted"'
  Argument: '-D__TIME__="redacted"'
  Argument: -c
  Argument: third_party/protobuf/src/google/protobuf/extension_set.cc
  Argument: -o
  Argument: bazel-out/host/bin/third_party/protobuf/_objs/protobuf_lite/third_party/protobuf/src/google/protobuf/extension_set.o
  Declared include source: third_party/protobuf/src/google/protobuf/any.h
  Declared include source: third_party/protobuf/src/google/protobuf/any.pb.h
  Declared include source: third_party/protobuf/src/google/protobuf/api.pb.h
  Declared include source: third_party/protobuf/src/google/protobuf/arena.h
  Declared include source: third_party/protobuf/src/google/protobuf/arena_test_util.h
  Declared include source: third_party/protobuf/src/google/protobuf/arenastring.h
...
'''

(and more)  From reading that, I don't see anything which changed, looks like it could have changed, or is machine specific.

### If possible, provide a minimal example to reproduce the problem:

I'm suspecting that if the environment changes, I'd trigger this.

### Environment info
* Operating System: Debian Jessie

* Bazel version (output of `bazel info release`):
0.5.0-rc2

I'd like bazel to maybe print what the action was before hand, and/or a diff showing what changed.  As is, there's nothing actionable in that print.

**Comment by softprops** [comment]
If would also be nice to have info about remote cache misses in this output. We're using remote caching for our outputs. We tried using explain to indicate when that cache is utilized but it didn't seem to surface in this log. It only reports on the action cache, not the cas cache.

**Comment by laszlocsomor** [comment]
@ericfelly : Do you have any thoughts on this?

**Comment by ericfelly** [comment]
both the "new action" and "command has changed" were incorrect? or just one of them? do you have a way to repro reliably?

in general, the explain file has only coarse grained information after action cache checking (whether the action is new, changed, or one of its files have changed).

**Comment by AustinSchuh** [comment]
@ericfelly For a simple reproduction case:

bazel build //...
export PATH="${PATH}:${PATH}"
bazel shutdown
bazel build //...

That should trigger a rebuild and a similar set of messages.  You might need a small variation on that.  In theory, the shutdown shouldn't be required, but in practice, it seemed to be.

I discovered that my path was different when logging in remotely and when using a terminal directly on my machine.  When switching, I would inconsistently trigger full rebuilds.

I would say that the "new action" statement is wrong in this case.  "command has changed" is right, but needs to include *everything* that could have changed, which in this case includes the environmental variables.  If there is anything else that could change but isn't printed, that needs to be added too.  Ideally, I'd see a diff too showing what's different rather than just a huge text dump, but that's less important than having all the information available.

**Comment by kush-c** [comment]
Hi Austin,
I wasn't able to reproduce this issue by changing the PATH while rebuilding a java_library target, even after the bazel shutdown. Can you point to some Github targets which I can access? The change in behavior due to the shutdown may be a bug in itself.

**Comment by AustinSchuh** [comment]
Hi Kush,

Using bazel 0.5.0-rc2 to build bazel-0.4.5 (as a random target which you should have access to).  I wasn't the most careful in the following test with which exact git revisions I'm using of everything.  I can re-run it again being more careful if reproduction is still eluding you and document exactly what I did.

My watching of the build output when it re-built seemed to suggest that it was only re-building C++, but I could have easily missed some java targets.  I wasn't being very scientific.

`
austin[97993] aschuh-debian-z620 ~
$ cat .bazelrc 
build --local_resources 100000,16,5000
build --jobs=18
build --explain=/tmp/bazel_explain.log
build --verbose_explanations
--watchfs
build --experimental_ui
build --experimental_ui_actions_shown=32
`

`
austin[98015] aschuh-debian-z620 (bazel-0.4.5-peloton-austin) ~/local/bazel
$ bazel build //src:bazel
INFO: Analysed target //src:bazel.
INFO: Found 1 target...
INFO: Writing explanation of rebuilds to '/tmp/bazel_explain.log'
INFO: From Executing genrule //src/java_tools/junitrunner/java/com/google/testing/coverage:Jacoco_jarjar:
Jun 21, 2017 4:14:12 PM com.tonicsystems.jarjar.transform.JarTransformer transform
INFO: Transforming archive ZipArchive(/home/austin/.cache/bazel/_bazel_austin/33b1fb5fd89e324f3381d636742e6218/bazel-sandbox/1968535439830931474/execroot/bazel/bazel-out/local-fastbuild/bin/src/java_tools/junitrunner/java/com/google/testing/coverage/JacocoCoverage_deploy.jar)
Target //src:bazel up-to-date:
  bazel-bin/src/bazel
INFO: Elapsed time: 131.553s, Critical Path: 54.51s
INFO: Build completed successfully, 1562 total actions
austin[98016] aschuh-debian-z620 (bazel-0.4.5-peloton-austin) ~/local/bazel
$ bazel build //src:bazel
INFO: Analysed target //src:bazel.
INFO: Found 1 target...
INFO: Writing explanation of rebuilds to '/tmp/bazel_explain.log'
Target //src:bazel up-to-date:
  bazel-bin/src/bazel
INFO: Elapsed time: 0.431s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action
austin[98016] aschuh-debian-z620 (bazel-0.4.5-peloton-austin) ~/local/bazel
$ export PATH=$PATH:/home/austin/bin
austin[98017] aschuh-debian-z620 (bazel-0.4.5-peloton-austin) ~/local/bazel
$ bazel build //src:bazel
INFO: Analysed target //src:bazel.
INFO: Found 1 target...
INFO: Writing explanation of rebuilds to '/tmp/bazel_explain.log'
Target //src:bazel up-to-date:
  bazel-bin/src/bazel
INFO: Elapsed time: 0.212s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
austin[98018] aschuh-debian-z620 (bazel-0.4.5-peloton-austin) ~/local/bazel
$ bazel shutdown
austin[98019] aschuh-debian-z620 (bazel-0.4.5-peloton-austin) ~/local/bazel
$ bazel build //src:bazel
.........
INFO: Analysed target //src:bazel.
INFO: Found 1 target...
INFO: Writing explanation of rebuilds to '/tmp/bazel_explain.log'
INFO: From Executing genrule //src/java_tools/junitrunner/java/com/google/testing/coverage:Jacoco_jarjar:
Jun 21, 2017 4:17:03 PM com.tonicsystems.jarjar.transform.JarTransformer transform
INFO: Transforming archive ZipArchive(/home/austin/.cache/bazel/_bazel_austin/33b1fb5fd89e324f3381d636742e6218/bazel-sandbox/3040815097905034358/execroot/bazel/bazel-out/local-fastbuild/bin/src/java_tools/junitrunner/java/com/google/testing/coverage/JacocoCoverage_deploy.jar)
Target //src:bazel up-to-date:
  bazel-bin/src/bazel
INFO: Elapsed time: 111.144s, Critical Path: 51.35s
INFO: Build completed successfully, 825 total actions
austin[98020] aschuh-debian-z620 (bazel-0.4.5-peloton-austin) ~/local/bazel
$ bazel shutdown
austin[98021] aschuh-debian-z620 (bazel-0.4.5-peloton-austin) ~/local/bazel
$ bazel build //src:bazel
..........
INFO: Analysed target //src:bazel.
INFO: Found 1 target...
INFO: Writing explanation of rebuilds to '/tmp/bazel_explain.log'
Target //src:bazel up-to-date:
  bazel-bin/src/bazel
INFO: Elapsed time: 7.301s, Critical Path: 1.77s
INFO: Build completed successfully, 1 total action
austin[98022] aschuh-debian-z620 (bazel-0.4.5-peloton-austin) ~/local/bazel
$ 
`

What I see is that after the path change, the build before shutdown is fast, and does no work.

The next build after shutdown is slow.

Subsequent shutdowns and builds are fast (re-scanning bazel-output, but that's expected).

**Comment by kush-c** [comment]
Thanks for the repro steps Austin. I filed #3259 since the shutdown should not trigger re-executions and as you correctly point out these re-executions only occur if the environment was changed before the shutdown.

As about your original concerns:
1. Changing the environment itself will trigger some re-executions and that seems very [intentional](https://github.com/bazelbuild/bazel/blob/a81264e1043dd90e984d9fcef5ce9962dce90d1d/src/main/java/com/google/devtools/build/lib/actions/ActionCacheChecker.java#L286)
2. --explain coupled with --verbose_explanations actually helped me  understand what bazel was doing (which was incorrect hence #3259). So in the absence of the bug won't the flag be Working as Intended?

**Comment by AustinSchuh** [comment]
Hi Kush,

I didn't try changing the environment after shutdown, which would be another fascinating test to see if it does the same thing.

1) Agreed, changing the environment should trigger re-executions.  Those should happen immediately, and not require a shutdown to take effect (or not happen, but not happen randomly.)  I think we agree on that, and that's likely a second bug here.

2) I would have expected a line saying something that the environment changed, and what changed.  "Action Changed" isn't actionable feedback for me.  Adding the environment to the printout (and everything else that could have changed) would have given me actionable feedback.  I'd like to see *everything* that could possibly have changed, or, in an ideal world, a diff showing me exactly what changed.  As is, it took me about 2 months off and on to figure out what was happening once I noticed that I was getting random large re-builds which didn't seem correlated with the changes I was making.

On my system, I was triggering this by having a /etc/profile.d/add_path.sh file which was adding /home/austin/bin to the path.  That file was only being run over SSH.  So, my path was different when remotely logged in or logged in locally.  I would only get rebuilds when I waited long enough after switching, which was hard to debug.  I ended up finding it by random luck by wondering if an environmental variable had changed and running some experiments.

**Comment by kush-c** [comment]
Reg 1: So for me changing the environment *always* triggered re-executions (irrespective of restarts). Did you observe a different result?
Reg 2: --verbose_explanations did give me the full path being used while choosing to perform re-executions. However I agree we can try to figure out the *exact* diff in the environment rather than dumping the new environment.

**Comment by AustinSchuh** [comment]
1) I observed a different result...  I didn't get a re-build until shutdown.

2) I didn't get the new environment printed out at all.  What I got is in the first post in this issue (different code base, but I can't see how that would matter)  Is that a new feature in 0.5.1 or master or something?

I'm going to go try reproducing what you observed.  I'm a bit weirded out by us getting different results for the same test.  I'm going to be more rigorous, which will take a couple days to block out enough time for.

**Comment by kush-c** [comment]
Hmmm... 
1. Could you add this observation to #3259? Changing the path should just trigger re-executions.
2. The dump of the PATH contents (when using the --verbose_explanations flag) seem to be added at the same time bazel decided to trigger re-executions with client changes. https://github.com/bazelbuild/bazel/commit/6f33a1c54e517d7343c36d0479713655a19f3224, and it's been in bazel releases much prior to 5.0

**Comment by AustinSchuh** [comment]
Hi Kush,

I re-tried the experiment from master today to make sure I'm not reporting an issue with old code.

```
austin[100738] aschuh-debian-z620 (master) ~/local/bazel
$ git show --summary HEAD
commit 1e0628d18c2e3defaddd935ffb41edbf3ef40339
Author: aehlig <aehlig@google.com>
Date:   Wed Jun 28 15:11:46 2017 +0200

    Writing build events to a file is no longer experimental
    
    Reflect this by renaming the options appropriately. While
    there, also add categories to those options.
    
    RELNOTES: writing build events to a file is no longer experimental
    PiperOrigin-RevId: 160400332
```

Pretty new

```
austin[100730] aschuh-debian-z620 (master) ~/local/bazel
$ /tmp/bazel build //third_party/protobuf:protobuf
.................
INFO: Analysed target //third_party/protobuf:protobuf.
INFO: Found 1 target...
INFO: Writing explanation of rebuilds to '/tmp/bazel_explain.log'
Target //third_party/protobuf/3.2.0:protobuf up-to-date:
  bazel-bin/third_party/protobuf/3.2.0/libprotobuf.a
  bazel-bin/third_party/protobuf/3.2.0/libprotobuf.so
INFO: Elapsed time: 33.283s, Critical Path: 12.08s
INFO: Build completed successfully, 84 total actions
austin[100731] aschuh-debian-z620 (master) ~/local/bazel
$ export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/peloton-tech/
austin[100732] aschuh-debian-z620 (master) ~/local/bazel
$ /tmp/bazel build //third_party/protobuf:protobuf -s
INFO: Analysed target //third_party/protobuf:protobuf.
INFO: Found 1 target...
INFO: Writing explanation of rebuilds to '/tmp/bazel_explain.log'
SUBCOMMAND: # //third_party/protobuf/3.2.0:protobuf [action 'Linking third_party/protobuf/3.2.0/libprotobuf.a']
(cd /home/austin/.cache/bazel/_bazel_austin/33b1fb5fd89e324f3381d636742e6218/execroot/io_bazel && \
  exec env - \
    PWD=/proc/self/cwd \
  /usr/bin/ar @bazel-out/local-fastbuild/bin/third_party/protobuf/3.2.0/libprotobuf.a-2.params)
SUBCOMMAND: # //third_party/protobuf/3.2.0:protobuf [action 'Linking third_party/protobuf/3.2.0/libprotobuf.so']
(cd /home/austin/.cache/bazel/_bazel_austin/33b1fb5fd89e324f3381d636742e6218/execroot/io_bazel && \
  exec env - \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -shared -o bazel-out/local-fastbuild/bin/third_party/protobuf/3.2.0/libprotobuf.so -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -Wl,-S -Wl,@bazel-out/local-fastbuild/bin/third_party/protobuf/3.2.0/libprotobuf.so-2.params)
Target //third_party/protobuf/3.2.0:protobuf up-to-date:
  bazel-bin/third_party/protobuf/3.2.0/libprotobuf.a
  bazel-bin/third_party/protobuf/3.2.0/libprotobuf.so
INFO: Elapsed time: 1.620s, Critical Path: 0.93s
INFO: Build completed successfully, 3 total actions
austin[100733] aschuh-debian-z620 (master) ~/local/bazel
$ /tmp/bazel shutdown
austin[100734] aschuh-debian-z620 (master) ~/local/bazel
$ /tmp/bazel build //third_party/protobuf:protobuf -s
.....................
INFO: Analysed target //third_party/protobuf:protobuf.
INFO: Found 1 target...
INFO: Writing explanation of rebuilds to '/tmp/bazel_explain.log'
Target //third_party/protobuf/3.2.0:protobuf up-to-date:
  bazel-bin/third_party/protobuf/3.2.0/libprotobuf.a
  bazel-bin/third_party/protobuf/3.2.0/libprotobuf.so
INFO: Elapsed time: 10.937s, Critical Path: 0.20s
INFO: Build completed successfully, 1 total action
```

So, looks like I'm not seeing 1) on master, at least in the same form.  I'm seeing less code re-build on an environment variable change than I would expect.  I would have expected the .cc files to be re-built, not just the link step.

```
$ cat /tmp/explain
Build options: --action_env=PATH --action_env=LD_LIBRARY_PATH --action_env=TMPDIR --test_env=PATH --test_env=LD_LIBRARY_PATH --local_resources=100000,16,5000 --jobs=18 --explain=/tmp/bazel_explain.log --verbose_explanations --experimental_ui --experimental_ui_actions_shown=32 --test_env='HERCULES_CAN_INTERFACE=can2' --subcommands --verbose_explanations --explain=/tmp/b2
Executing action 'BazelWorkspaceStatusAction stable-status.txt': unconditional execution is requested.
Executing action 'Linking third_party/protobuf/3.2.0/libprotobuf.so': Effective client environment has changed. Now using
  PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/peloton-tech/:/home/austin/bin
.
Executing action 'Linking third_party/protobuf/3.2.0/libprotobuf.a': Effective client environment has changed. Now using
  PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/peloton-tech/:/home/austin/bin
.
```

So, yea, looks like the original bug is fixed.

**Comment by janakdr** [comment]
Sounds like this has been fixed?
