### ISSUE TITLE
Style not correctly applied to docs Edit button

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#3028]
In https://github.com/bazelbuild/bazel/commit/8dd69b609304bf3f89048dd9446076698c092e1b, I added an Edit button to the docs.

It contains [CSS style](https://github.com/bazelbuild/bazel/blob/8dd69b609304bf3f89048dd9446076698c092e1b/site/styles/main.css#L103)
But these do not seem to have been deployed, see https://bazel.build/css/main.css

Any idea what's wrong?

This is urgent to solve, as the edit button is not supposed to be visible on every pages.

**Comment by damienmg** [comment]
So investigation so far:
http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel-Publish-Site/682/console push styles/main.css but you are looking at css/main.css

**Comment by damienmg** [comment]
https://bazel.build/styles/main.css does reflect that change. So either the jekyll build is broken or we refer to the wrong path at some place

**Comment by damienmg** [comment]
From source code, we do refer to css/main.css. So that means the problem is on the jekyll part.

**Comment by steren** [comment]
Something related to SCSS not running?

To be honest, I am not sure of the value of using SCSS for something as simple as our website, but this is a different story

**Comment by damienmg** [comment]
I don't think so, the jekyll command works on my machine and generates the correct files.

**Comment by damienmg** [comment]
Sorry I was wrong, the jekyll command did generate a main.css in css that is not containing the input from styles/main.css, styles/main.css still exists. I don't know about the jekyll stuff so much so I cannot investigate further, handing off to @davidzchen

**Comment by steren** [comment]
It is because we have scss files AND css files versioned?
https://github.com/bazelbuild/bazel/blob/master/site/_sass/style.scss
https://github.com/bazelbuild/bazel/blob/master/site/styles/main.css

Jekyll has nothing to do with transforming SCSS to CSS as far as I know.

If css is derived from scss, then it should not be versionned

**Comment by steren** [comment]
Changing the .scss file fixes it. I am sending a fix.
