### ISSUE TITLE
XcodeprojGeneration should only be adding $(SDKROOT)/Developer/Library/Frameworks to tests

### ISSUE THREAD

**Issue by dmaclach** [bazelbuild/bazel#303]
Right now we are adding unnecessary framework paths to all targets. We should only add them if needed.

**Comment by dmaclach** [comment]
Specifically in XcodeprojGeneration.java:frameworkSearchPaths()

**Comment by aragos** [comment]
We're about to remove this functionality so I'm closing this issue as obsolete.
