### ISSUE TITLE
build error when building android tensorflow_demo

### ISSUE THREAD

**Issue by naveenkumarmarri** [bazelbuild/bazel#3031]
I'm trying to build android app from custom model build in tensor flow.

I've installed all the required SDK and NDK for the app and modified the WORKSPACE file to point to the location in docker container.
 
It is throwing the following error.

`bazel build //tensorflow/examples/android:tensorflow_demo                                           
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: /tensorflow/WORKSPACE:19:1: no such package '@androidsdk//': android_sdk_repository requires that at least one Android SDK Platform is installed in the Android SDK. Please install an Android SDK Platform through the Android SDK manager. and referenced by '//external:android/sdk'.
ERROR: Analysis of target '//tensorflow/examples/android:tensorflow_demo' failed; build aborted.
INFO: Elapsed time: 2.185s
`

### Environment info
* Operating System:
Mac OS:Sierra

* Bazel version (output of `bazel info release`):
0.45

**Comment by aj-michael** [comment]
Hi @naveenkumarmarri, the problem is in the error message

> android_sdk_repository requires that at least one Android SDK Platform is installed in the Android SDK. Please install an Android SDK Platform through the Android SDK manager.

This means that the contents of `$ANDROID_HOME/platforms` is empty. You need to run `$ANDROID_HOME/tools/android` and download an SDK Platform.

**Comment by aj-michael** [comment]
I just noticed that you said that this is in a docker container. In that case, you can use something like this command in your dockerfile to download the needed parts of the Android SDK.

    tools/bin/sdkmanager "platforms;android-24" "platform-tools" "build-tools;24.0.3"

The "platform" is the jar of class files that we compile the app against, the platform-tools are tools like aapt that are used to process resources, and the build-tools are things like the apksigner and zipalign which manipulate the APK that bazel builds.

**Comment by guruprasaad123** [comment]
`bazel build //tensorflow/examples/android:tensorflow_demo
............................................................................
____Loading package: tensorflow/examples/android
____Loading package: @bazel_tools//tools/cpp
____Loading package: @bazel_tools//tools/jdk
____Loading package: @local_config_xcode//
____Loading package: @local_config_cc//
____Loading package: @local_jdk//
____Loading complete.  Analyzing...
____Loading package: tensorflow/examples/android/assets
____Loading package: @bazel_tools//tools/android
____Loading package: tensorflow/contrib/android
ERROR: Analysis of target '//tensorflow/examples/android:tensorflow_demo' failed; build aborted.
____Elapsed time: 39.150s
`
am getting this error and cant find the cause of this ? any idea what that might be ?

**Comment by jin** [comment]
@guruprasaad123 can you please paste your android_sdk_repository() and android_ndk_repository() rules from your Tensorflow WORKSPACE file here?

**Comment by guruprasaad123** [comment]
`Here's the content in the `WORKSPACE` File in the root directory 
`workspace(name = "org_tensorflow")

http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "bc41b80486413aaa551860fc37471dbc0666e1dbb5236fb6177cb83b0c105846",
    strip_prefix = "rules_closure-dec425a4ff3faf09a56c85d082e4eed05d8ce38f",
    urls = [
        "http://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/dec425a4ff3faf09a56c85d082e4eed05d8ce38f.tar.gz",  # 2017-06-02
        "https://github.com/bazelbuild/rules_closure/archive/dec425a4ff3faf09a56c85d082e4eed05d8ce38f.tar.gz",
    ],
)

load("@io_bazel_rules_closure//closure:defs.bzl", "closure_repositories")

closure_repositories()

load("//tensorflow:workspace.bzl", "tf_workspace")

# Uncomment and update the paths in these entries to build the Android demo.
android_sdk_repository(
    name = "androidsdk",
    api_level = 23,
    build_tools_version = "25.0.1",
    # Replace with path to Android SDK on your system
    path = "D:/sdk/",
)
#
# Android NDK r12b is recommended (higher may cause issues with Bazel)
android_ndk_repository(
    name="androidndk",
    path="D:/android-ndk-r12b/",
    api_level=14)

# Please add all new TensorFlow dependencies in workspace.bzl.
tf_workspace()

new_http_archive(
    name = "inception5h",
    build_file = "models.BUILD",
    sha256 = "d13569f6a98159de37e92e9c8ec4dae8f674fbf475f69fe6199b514f756d4364",
    urls = [
        "http://storage.googleapis.com/download.tensorflow.org/models/inception5h.zip",
        "http://download.tensorflow.org/models/inception5h.zip",
    ],
)

new_http_archive(
    name = "mobile_ssd",
    build_file = "models.BUILD",
    sha256 = "bddd81ea5c80a97adfac1c9f770e6f55cbafd7cce4d3bbe15fbeb041e6b8f3e8",
    urls = [
        "http://storage.googleapis.com/download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_android_export.zip",
        "http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_android_export.zip",
    ],
)

new_http_archive(
    name = "mobile_multibox",
    build_file = "models.BUILD",
    sha256 = "859edcddf84dddb974c36c36cfc1f74555148e9c9213dedacf1d6b613ad52b96",
    urls = [
        "http://storage.googleapis.com/download.tensorflow.org/models/mobile_multibox_v1a.zip",
        "http://download.tensorflow.org/models/mobile_multibox_v1a.zip",
    ],
)

new_http_archive(
    name = "stylize",
    build_file = "models.BUILD",
    sha256 = "3d374a730aef330424a356a8d4f04d8a54277c425e274ecb7d9c83aa912c6bfa",
    urls = [
        "http://storage.googleapis.com/download.tensorflow.org/models/stylize_v1.zip",
        "http://download.tensorflow.org/models/stylize_v1.zip",
    ],
)
`

**Comment by aj-michael** [comment]
Hi @guruprasaad123, can you open a separate GitHub Issue? We can help you there.

**Comment by guruprasaad123** [comment]
i just opened a new Issue @aj-michael [ Issue #3829 ](https://github.com/bazelbuild/bazel/issues/3829 )
