### ISSUE TITLE
Memory/Resources best practices/troubleshooting documentation page

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#3032]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

If I run bazel clean my machine runs out of memory, pauses all other apps and takes tens of minutes to finish.
When I tried googling for help I found several resources (mainly an SO question and two github issues) which gave some value (--jobs) but also added confusion due to the long discussions.
I think a doc on the bazel.build site which talks about best practices and/or troubleshooting of resources in general and memory in particular could be very helpful.

### If possible, provide a minimal example to reproduce the problem:
go into bazel.build
type memory into the search bar
expect to find memory guidelines for working with bazel

###  Have you found anything relevant by searching the web?
https://www.google.co.il/search?q=bazel+memory+usage

**Comment by iirina** [comment]
cc @michelleirvine

**Comment by steren** [comment]
@ittaiz confirmed me he is using Bazel head (so >0.5)

And we know that the # of jobs is in v0.5+ capped by default at the # of cores on the machine

**Comment by tuananhckpt90** [comment]
có

**Comment by meisterT** [comment]
I think we have added some documentation so that we can close this: https://docs.bazel.build/versions/master/memory-saving-mode.html
