### ISSUE TITLE
Bazel complains about --watchfs every other call

### ISSUE THREAD

**Issue by nordlow** [bazelbuild/bazel#3034]
I've bumped Inotify limits as

```
sysctl fs.inotify.max_user_watches=1000000
sysctl fs.inotify.max_queued_events=1000000 # originally 16384
sysctl fs.inotify.max_user_instances=4096 # originally 128
```

but when I try to build my Bazel stress test at 

https://github.com/nordlow/build-system-benchmark/blob/master/test_bazel.sh

it complains every other time as 

``` 
WARNING: Overflow when watching local filesystem for changes... temporarily falling back to manually checking files for changes.
INFO: Found 1 target...
``` 

Is this fixed on master?

**Update:** Problem happens on master aswell.

**Comment by philwo** [comment]
Reassigning to @ulfjack, as I think he knows more about --watchfs than me.

**Comment by ulfjack** [comment]
Java 7 maxes out at 512 events, regardless of how the kernel is configured, according to this [answer](https://stackoverflow.com/questions/18586091/in-jdk7-watch-service-api-when-will-the-overflow-event-be-thrown).

We currently poll in the main thread, not in a separate thread, so it's guaranteed to overflow with the example benchmark provided. When it overflows, it'll fall back to stat for both the current and the subsequent build, which explains why it only shows the warning on every other invocation.

**Comment by nordlow** [comment]
And Java 8?

**Comment by ulfjack** [comment]
I can reproduce the problem on my machine, where I'm using Java 8. I conclude that Java 8 has the same problem. There are possible workaround, but I don't think there's any immediate pressure to do something here. Bazel will be slightly slower on your benchmark, but I'm not convinced that this is a common scenario for our users.

**Comment by ulfjack** [comment]
I think the obvious fix is to move polling to a separate thread, but I won't be able to personally work on this.

**Comment by meisterT** [comment]
I agree with Ulf, we have not seen any other reports of this behavior showing that it's an uncommon behavior.

**Comment by orborde** [comment]
I see the `Overflow when watching local filesystem for changes... temporarily falling back to manually checking files for changes.` error routinely on my company's quite large monorepo.

**Comment by meisterT** [comment]
@orborde If you want to work on this issue and send a Pull Request, we are happy to accept a contribution but we don't have the bandwidth to look into this ourselves.

**Comment by jschaf** [comment]
Likely not the original cause, but posting for future searchers:

If calling `bazel mod *` causes this warning, the fix is to use common for the `--watchfs` flag in .bazelrc.

```diff
-build --watchfs
+common --watchfs
```
