### ISSUE TITLE
Should be able to use @SkylarkSignature on Provider constructors

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#3035]
In order to make a declared native provider creatable from Skylark, the [NativeClassObjectConstructor.createInstanceFromSkylark](https://github.com/bazelbuild/bazel/blob/b36774ac955c5af15d59df36c66dc69f89674a49/src/main/java/com/google/devtools/build/lib/packages/NativeClassObjectConstructor.java#L132) method must be overloaded for the new provider type. This method has the signature:
```java
protected SkylarkClassObject createInstanceFromSkylark(Object[] args, Location loc)
      throws EvalException
```

This requires the implementor to handle all argument checking manually, like:
```java
  public static final ClassObjectConstructor SKYLARK_CONSTRUCTOR =
      new NativeClassObjectConstructor(SKYLARK_NAME) {
        @Override
        protected PlatformInfo createInstanceFromSkylark(Object[] argsUnchecked, Location loc)
            throws EvalException {
          SkylarkDict<String, Object> args =
              SkylarkDict.castSkylarkDictOrNoneToDict(
                  argsUnchecked[0], String.class, Object.class, "args");
          // Check arguments exist and types.
          // Use arguments.
          // Return new object
        }
      };
```

It would instead be convenient to use the existing @SkylarkSignature annotation and processor to do something like the following:
```java
  @SkylarkSignature(
    parameters = [
      @Param(name = "label", type = Label.class),
      @Param(name = "values", type = SkylarkList.class, generic1 = PlatformInfo.class),
    ]
  )
  public static final ClassObjectConstructor SKYLARK_CONSTRUCTOR =
      new NativeClassObjectConstructor(SKYLARK_NAME) {
        public NewTypeInfo invoke(Label label, SkylarkList<PLatformInfo> values) {
          // Use arguments.
          // Return new object
        }
      };
```

**Comment by katre** [comment]
This can be worked around currently by passing the correct FunctionSignature.WithValues object through to the BaseFunction constructor. See https://bazel-review.googlesource.com/11390 for an example.

**Comment by katre** [comment]
(Previous comment was not correct and was deleted).

**Comment by brandjon** [comment]
@c-parsons is solving this with the new BuiltinProvider class design. It's based on specifying signatures in `@SkylarkCallable` annotations. I'll leave it to him to close.

**Comment by laurentlb** [comment]
@c-parsons to triage

**Comment by c-parsons** [comment]
Oof. This issue is very out of date and we can almost certainly close it.
For new providers, use BuiltinProvider, and have the Info object extend Info.
You can use @SkylarkCallable for object construction, and that should be everything you need.

Here's a canonical example:
https://github.com/bazelbuild/bazel/blob/e8d450c4cbae8b733470eee6d816baaaa0162318/src/main/java/com/google/devtools/build/lib/analysis/test/AnalysisFailureInfo.java

Let me know if there are any issues using this.
