### ISSUE TITLE
Bazel triggers full builds to run Extra Actions and Aspects

### ISSUE THREAD

**Issue by jerrymarino** [bazelbuild/bazel#3036]
### Description of the problem / feature request / question:

I'm using aspects and extra actions in an Objective-C / C++ / C  iOS bazel project:
- Aspects to generate Xcode projects with tulsi.
- Extra actions to generate CompilationDatabases.

These take a lot longer than they should. That is because Bazel wants to do an actual build: i.e. the full compilation of a `.m`, linking, and more.

It seems like the object files and static libraries aren't needed these 2 scenarios and possibly more. Clang has the ability to do a noop build by passing `-###`. Is it possible to leverage this in Bazel some how?

I understand that currently, Bazel's `objc_libray` rules need the `.d` files. These can be generated without object file compilation using `clang -MD -MF foo.d -E` (`-E` says only run the preprocessor + the `foo.d` side-effect). This seems to work with a heavily customized rules and is fast.

### If possible, provide a minimal example to reproduce the problem:

Run an extra action or aspect.

### Environment info
* Operating System:
OSX 10.12.2 (16C67)

* Bazel version (output of `bazel info release`):
```
$ bazel info release
........
release 0.4.3-jdk7
```

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

Yes, [people are requesting this for features like running `extra_actions` for a CompilationDatabase and more](https://groups.google.com/forum/#!searchin/bazel-discuss/dry$20build%7Csort:relevance).

**Comment by iirina** [comment]
@mhlopko, @c-parsons can you take a look at this?

**Comment by lberki** [comment]
Yes, this is a known limitation... I think the eventual solution to this issue is that we get a reasonable Skylark API for C++ that allows you to write an aspect that runs the C++ compilation with the extra "do nothing" argument. 

Unfortunately, we haven't even started with that API so it'll take a while :(

**Comment by benvanik** [comment]
Any easy known workaround? Perhaps overriding PATH to dummy clang/cl.exe instances that return 0 (though then bazel would likely complain about missing outputs)...

I'm also using extra actions (to generate a Visual Studio project) and not only does it take awhile but the full build has to be able to succeed in order for me to get any of the extra actions outputs.

**Comment by lberki** [comment]
I can't think of any :(

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
