### ISSUE TITLE
Toolchain error when building from source on Redhat linux

### ISSUE THREAD

**Issue by joydeep-mitra** [bazelbuild/bazel#3038]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question: Cannot build bazel from source. Getting the following error when running compile.sh:
ERROR: No toolchain found for cpu 'piii'. Valid cpus are: [
  k8,
  armeabi-v7a,
  x64_windows_msvc,
  s390x,
  ios_x86_64,
].

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### Environment info
* Operating System:Redhat 6.6 (x86_64)

* Bazel version (output of `bazel info release`): Trying to build from source. Used the distribution https://github.com/bazelbuild/bazel/releases/download/0.4.5/bazel-0.4.5-dist.zip

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)
This issue was reported to be fixed inside tools/cpp/cc_autoconfigure.bzl but I verified the above distribution has the fix. So the above error is coming from a different source. I have attached the output of: bash -x compile.sh >& compile.txt

[compile.txt](https://github.com/bazelbuild/bazel/files/1020438/compile.txt)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by mhlopko** [comment]
Is this still valid issue? Should be long fixed. Please comment if not. Thanks!
