### ISSUE TITLE
debug information and -c opt

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#3039]
In the default Bazel crosstool, fastbuild and opt mode inhibit debug information generation by the compiler (either by explicitly passing `-g0` or simply not passing `-g`). On the other hand, the default behavior of `--strip` is to drop debug sections at the link time only in fastbuild mode. It seem to me that either opt builds should enable stripping and pass `-g0` OR disable stripping and pass `-g`, but not generating debug information and not stripping it is somewhat weird. The Bazel opt mode flags appear to come largely come from #99, but it doesn't seem this particular aspect was discussed there. Maybe there's a good reason for this that I'm missing.

**Comment by mhlopko** [comment]
You are totally right! This logic comes from the times when Bazel wasn't a thing yet, I'm guessing just to make binaries built in fastbuild smaller so we had less bits to send over the wire. Compilation mode should not affect stripping, and ideally Bazel wouldn't have to know about stripping at all, as it can be made a crosstool feature and enable it on a per rule/package/build basis. I'll look into it (eventually).

**Comment by mirsking** [comment]
Hi, is there any progress on this issue?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
