### ISSUE TITLE
Dexing fails with unsupported class file version 52.0 in android_binary

### ISSUE THREAD

**Issue by aaronj1335** [bazelbuild/bazel#3044]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

[aaronj1335/bazel-kotlin-android](https://github.com/aaronj1335/bazel-kotlin-android) fails to `bazel build --strategy=KotlinCompile=standalone :app` when it tries to dex with the error:

```
aaronstacy∂oɹdʞooqɔɐɯ-ʎɔɐʇsuoɹɐɐ ☠ ~/Downloads/test  09:17:06 May24
§ bazel build --strategy=KotlinCompile=standalone :app
.........
INFO: Found 1 target...
ERROR: /Users/aaronstacy/Downloads/test/BUILD:3:1: Converting bazel-out/darwin_x86_64-fastbuild/bin/app_deploy.jar to dex format failed: Process exited with status 1 [sandboxed].

PARSE ERROR:
unsupported class file version 52.0
...while parsing android/Manifest.class
1 error; aborting
Use --strategy=AndroidDexer=standalone to disable sandboxing for the failing actions.
Target //:app failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 20.542s, Critical Path: 6.47s
```

I'm trying to build an Android app with Kotlin as the source code. The `kotlin_library` rule works fine, but it can't find the Android SDK, so I include it explicitly as a `java_import` dependency. 
It seems like I if I could specify a dependency on the Android SDK that doesn't actually include any of the code, the `kotlin_library` would compile and everything would work.

### If possible, provide a minimal example to reproduce the problem:

```
git clone https://github.com/aaronj1335/bazel-kotlin-android.git
cd bazel-kotlin-android
bazel build --strategy=KotlinCompile=standalone :app
```

### Environment info
* Operating System: OS X 10.2.4

* Bazel version (output of `bazel info release`): release 0.4.5-homebrew

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

No.

* The top SO answer when I Google the issue is for Gradle
* I've also filed the issue on the `kotlin_library` at repo pubref/rules_kotlin#14
* The only ["kotlin android app" mailing list discussion](https://groups.google.com/d/msg/bazel-discuss/qNwXiJoV1kE/kDRsEU3wBwAJ) I can find does not have relevant info

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

I've also tried setting my JAVA_HOME to Java 7, but bazel doesn't work at all unless it's using Java 8.

**Comment by aaronj1335** [comment]
I needed `neverlink = 1` for the Android SDK `java_import`: https://github.com/aaronj1335/bazel-kotlin-android/commit/4cc76907921fb8fbedbee03a172effb9227ce807

**Comment by aj-michael** [comment]
I'm glad you found the answer 😄 

One suggestion that I would make to your project is to depend on `//tools/defaults:android_jar` instead of `@androidsdk//:platforms/android-25/android.jar`. `//tools/defaults:android_jar` is a special build rule that will give you the android.jar for the API level specified by `--android_sdk`.

For example, `bazel build --android_sdk=@androidsdk//:sdk-19 //:app` will build your app against api level 19, but if you hardcode android-25 for your kotlin dependency, then it will be out of sync with the rest of your app.
