### ISSUE TITLE
cache symlinks not owned by user should be removed rather than fail due to permissions issue

### ISSUE THREAD

**Issue by brunobowden** [bazelbuild/bazel#3046]
In order to do a more hermetic build isolated from local system packages, I'm running a bazel build inside Docker. Running bazel in docker works just fine and builds successfully. The problem comes afterwards when running a non docker build:

    WARNING: Failed to get information about path, for bazel-src, skipping: /root/.cache (Permission denied).
    ERROR: /root/.cache (Permission denied).

It appears that bazel in docker runs with root permissions and is therefore changing owner of the bazel symlinks to root (docker using root permissions is a concern but ignored for this issue). The result is that a subsequent non docker build no longer works as it doesn't have root permissions. A simple workaround is for the non-root user to delete the bazel-* symlinks and then the non docker build works just fine.

    rm bazel-*

Given that this is a simple workaround, my request is to consider making it an automatic part of bazel. Specifically, if current bazel-* symlinks are not owned by the current user, bazel should delete the symlinks itself and then proceed as normal. Swapping between docker and non-docker builds may never be an officially supported usecase but this change would remove the only current obstacle to doing it seamlessly.

### Hermetic Docker Builds

The motivation here is to make bazel builds more hermetic such that they're done independently of the local installed system packages. Building in docker means that the build only depends on what's in the docker image.

### Reproduction Steps:

Here's a minimal set of files to reproduce the problem:

Start by [installing docker](https://docs.docker.com/engine/installation/linux/ubuntu/#install-docker) and configure sudo less docker: https://askubuntu.com/a/477554 (I'm unclear if this causes any change in behaviour).

Next create a local directory with this Dockerfile:

```
# Dockerfile
FROM ubuntu:16.04
RUN apt-get -y update && apt install -y apt-transport-https
RUN echo 'deb [arch=amd64] "https://storage.googleapis.com/bazel-apt" stable jdk1.8' \
    > /etc/apt/sources.list.d/bazel.list
RUN apt-get -y update && apt install -y --allow-unauthenticated \
    bazel && rm -rf /var/lib/apt/lists/*
```
Build the image:

    docker build -t hermetic /PATH_TO_DOCKERFILE_FOLDER

Build cache must be disabled as it breaks the build in docker. From the src root directory where you'd normally run bazel commands, run the the bazel build in docker instead. This mounts `$PWD` as `/src` in the docker image and then runs the build command in that directory:

    docker run -v $PWD:/src deleteme /bin/bash -c "cd /src; bazel build -- //..."

The build should complete successfully for you. It's worked many times for me.

After the build is done and the docker image exited. Note how permissions for the `bazel-*` folders have changed:

```
$ ls | xargs stat --printf "%U %G %A %n \n"
bruno bruno lrwxrwxrwx bazel-XXXX 
root root lrwxrwxrwx bazel-bin 
root root lrwxrwxrwx bazel-genfiles 
root root lrwxrwxrwx bazel-out 
root root lrwxrwxrwx bazel-src 
root root lrwxrwxrwx bazel-testlogs 
bruno bruno drwxrwxr-x build
....
```

FAILURE: note how the local bazel build now fails:

```
$ bazel build //...
INFO: Reading 'startup' options from /XXXX/tools/bazel.rc: --host_jvm_args=-Dbazel.DigestFunction=SHA1
WARNING: Failed to get information about path, for bazel-src, skipping: /root/.cache (Permission denied).
ERROR: /root/.cache (Permission denied).
INFO: Elapsed time: 0.222s
```

WORKAROUND: delete the `bazel-*` directories (doesn't require root access) and re-run the non docker bazel build to confirm that it's working:

```
$ rm bazel*
$ bazel build //...
... build should SUCCEED
```

### Environment

* OS: Ubuntu 16.04 LTS (same os on machine and within docker image)
* Bazel: release 0.4.5
* Docker: 17.03.1-ce

###  Have you found anything relevant by searching the web?

Google reports zero results for this error, so maybe only a few people have tried this before.

### Anything else, information or logs or outputs that would be helpful?

I recognize that this may not be an official use case for bazel but it's helpful to make the tool as useful as possible. There are certain users that care greatly about hermetic builds and this is a good way to improve it without needing to make other more extensive changes in bazel.

**Comment by laszlocsomor** [comment]
Thanks for the detailed bug report!

After the build inside docker, where do the symlinks point to? I'm looking for the source of that `/root/.cache` path in the build. Also, what's the output of `bazel info install_base ; bazel info output_base` output?

**Comment by brunobowden** [comment]
@laszlocsomor - thanks for taking a look. Here's what you asked for:

```
$ bazel $ ls -al bazel*
lrwxrwxrwx 1 bruno bruno  88 May 28 18:59 bazel-XXXX -> /home/bruno/.cache/bazel/_bazel_bruno/080af39086b7862c7cf8e1c994f7ea27/execroot/__main__
lrwxrwxrwx 1 root  root  112 May 30 10:14 bazel-bin -> /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/execroot/src/bazel-out/local_linux-fastbuild/bin
lrwxrwxrwx 1 root  root  117 May 30 10:14 bazel-genfiles -> /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/execroot/src/bazel-out/local_linux-fastbuild/genfiles
lrwxrwxrwx 1 root  root   86 May 30 10:14 bazel-out -> /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/execroot/src/bazel-out
lrwxrwxrwx 1 root  root   76 May 30 10:14 bazel-src -> /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/execroot/src
lrwxrwxrwx 1 root  root  117 May 30 10:14 bazel-testlogs -> /root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/execroot/src/bazel-out/local_linux-fastbuild/testlogs
```

```
$ info install_base ; bazel info output_base
INFO: Reading 'startup' options from /home/bruno/src/XXXX/bazel.rc: --host_jvm_args=-Dbazel.DigestFunction=SHA1
/home/bruno/.cache/bazel/_bazel_bruno/install/e4abe4ff56d8f229afa015dc729c5bd9
INFO: Reading 'startup' options from /home/bruno/src/XXXX/bazel.rc: --host_jvm_args=-Dbazel.DigestFunction=SHA1
/home/bruno/.cache/bazel/_bazel_bruno/080af39086b7862c7cf8e1c994f7ea27
```

```
$ bazel version
INFO: Reading 'startup' options from /home/bruno/src/XXXX/bazel.rc: --host_jvm_args=-Dbazel.DigestFunction=SHA1
Build label: 0.4.5
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 12:19:38 2017 (1489666778)
Build timestamp: 1489666778
Build timestamp as int: 1489666778
```

**Comment by laszlocsomor** [comment]
@brunobowden : Thanks!

@philwo : Any ideas?

**Comment by philwo** [comment]
I think instead of (or in addition to?) checking that the symlinks are owned by the current user, we should verify their target and if it doesn't point to the right one, delete and recreate them. It's surprising that we don't do this? Or maybe it's exactly this check that fails? Then we should fix the check to delete the symlinks when it can't access the target, I guess.

**Comment by laszlocsomor** [comment]
Philipp, thanks for the diagnosis! Are you also volunteering to fix this?

**Comment by philwo** [comment]
Yes, but can't promise when.

**Comment by laszlocsomor** [comment]
Thanks! Marking this as P3 then to indicate that we could use some help and are unlikely to work on it soon.

**Comment by brunobowden** [comment]
@philwo - my machine was was just updated to 0.5.2 and this no longer seems to be a problem. I didn't notice anything in the 0.5.2 release notes that would suggest a fix. Any reason this might work now?

With 0.5.2, it seems to happily overwrite the root owned symlinks without any complaint.

**Comment by philwo** [comment]
@brunobowden Great to hear! I don't know if anyone actively worked on it to fix it or if it was a side-effect of general improvements. Unfortunately it means that we probably also don't have a regression test for it, but feel free to ping this bug if it ever happens again. Do you mind if I close it for now?

**Comment by brunobowden** [comment]
let me confirm that it regresses and gets fixed as I alternate between
0.5.1 and 0.5.2. I want to make sure it's down to bazel and not something
else that changed.

**Comment by brunobowden** [comment]
I never did verify this issue regressed between 0.5.1 and 0.5.2 but thought I should close the bug anyway. Looks like it's been working fine with 0.5.2. I'll reopen it if it regresses in the future.

**Comment by odisseus** [comment]
I'm having this exact issue with Bazel 5.1.0.
