### ISSUE TITLE
Glob patterns do not accept "{", "}", "[", "]" characters

### ISSUE THREAD

**Issue by jbduncan** [bazelbuild/bazel#3048]
Continuation of #2583.

In #2583, the logic for dealing with glob patterns in BUILD files was enhanced to allow parentheses ("(", ")") as valid characters. This issue asks whether other sorts of bracket characters (like "{", "}", "[", and "]") should be allowed as valid characters as well.

**Comment by jbduncan** [comment]
If these other bracket characters are desired, then I'd be happy to have a go at this issue to start my journey into the world on Bazel development!

**Comment by laszlocsomor** [comment]
@laurentlb : What do you think?

**Comment by laurentlb** [comment]
Sure.

**Comment by jbduncan** [comment]
@laurentlb Is that a confirmation that I can start on this issue when I'm ready?

**Comment by laurentlb** [comment]
Yes. There's no reason to have this restriction in glob, as far as I know.
(there might be a restriction for labels, though)

So feel free to assign the issue to yourself when you want.

**Comment by jbduncan** [comment]
@laurentlb I'm ready to start on this issue, so would you kindly assign it to me? It seems that I lack permissions to do so myself.

**Comment by jbduncan** [comment]
or @laszlocsomor for that matter? :)

**Comment by katre** [comment]
I'm not either of them, but there you go.

**Comment by jbduncan** [comment]
Many thanks @katre. :+1:
