### ISSUE TITLE
io-bazel workspace isn't created

### ISSUE THREAD

**Issue by xzy256** [bazelbuild/bazel#3049]
When i build bazel from source zip, i get error
<pre>
ERROR: /home/loongson/bazel-0.4.5/src/java_tools/singlejar/BUILD:77:1: error executing shell command: 'set -e;rm -rf bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output||:;mkdir bazel-out/host/bin/src/java_tools/singlejar/bootstrap_deploy.jar.build_output
unzip -qn bazel-ou...' failed: bash failed: error executing command 
</pre>
I find the `bazel-out` links a non existing dictionary. As if the `/tmp/bazel_igpiwDIH/out/execroot/io_bazel` is not created,  How should i do?
<pre>
[root@localhost bazel-0.4.5]# ll
总用量 420
lrwxrwxrwx  1 root root     41 5月  25 10:37 bazel-bazel-0.4.5 -> /tmp/bazel_igpiwDIH/out/execroot/io_bazel
lrwxrwxrwx  1 root root     68 5月  25 10:37 bazel-bin -> /tmp/bazel_igpiwDIH/out/execroot/bazel-0.4.5/bazel-out/local-opt/bin
lrwxrwxrwx  1 root root     73 5月  25 10:37 bazel-genfiles -> /tmp/bazel_igpiwDIH/out/execroot/bazel-0.4.5/bazel-out/local-opt/genfiles
lrwxrwxrwx  1 root root     51 5月  25 10:37 bazel-out -> /tmp/bazel_igpiwDIH/out/execroot/io_bazel/bazel-out
lrwxrwxrwx  1 root root     73 5月  25 10:37 bazel-testlogs -> /tmp/bazel_igpiwDIH/out/execroot/bazel-0.4.5/bazel-out/local-opt/testlogs

[root@localhost bazel-0.4.5]#cd bazel-out 
bash: cd: bazel-out : There is no file or directory

[root@localhost bazel-0.4.5]#cd /tmp/bazel_igpiwDIH/out/execroot
[root@localhost execroot]# pwd
/tmp/bazel_igpiwDIH/out/execroot
[root@localhost execroot]# ll
总用量 0
drwxr-xr-x 3 root root 60 5月  25 10:39 bazel-0.4.5

[root@localhost execroot]# uname -a
Linux localhost.localdomain 3.10.84 #1 SMP PREEMPT Wed Feb 8 16:03:10 CST 2017 mips64 mips64 mips64 GNU/Linux
</pre>

**Comment by kchodorow** [comment]
This is a known bug in 0.4.5, related to #1681. As a workaround, you can change the directory name to io_bazel.

**Comment by xzy256** [comment]
ok, thanks.
