### ISSUE TITLE
Allow relative paths with bazelrc's "import" command

### ISSUE THREAD

**Issue by mmorearty** [bazelbuild/bazel#3050]
### Description of the problem / feature request / question:

Feature request: It would be helpful if bazelrc's `import` command allowed relative paths.

If it allowed relative paths, I could put these three files side by side:

    dev.bazelrc     # what I use on my local machine
    ci.bazelrc      # what our CI system uses
    common.bazelrc  # common to both of the above

Then, `dev.bazelrc` and `ci.bazelrc` could just start with this line:

    import common.bazelrc

But currently, that is not possible.

### Environment info
* Operating System:

OSX

* Bazel version (output of `bazel info release`):

0.4.5

**Comment by mmorearty** [comment]
By the way, to be clear, it should be relative to the file that has the `import` statement, _not_ relative to the current working directory.

**Comment by laszlocsomor** [comment]
@lfpino : What do you think?

> By the way, to be clear, it should be relative to the file that has the import statement, not relative to the current working directory.

I strongly agree with that.

**Comment by lfpino** [comment]
I agree this is a reasonable request but I don't have the bandwidth to do this at the moment.

**Comment by laszlocsomor** [comment]
Thanks Luis, I'll leave it as P3 for now and add a "help wanted" tag.

**Comment by cgbystrom** [comment]
FWIW, a workaround is to use `%workspace%`.
For example `import %workspace%/common.bazelrc`

**Comment by dslomov** [comment]
Given that we have `%workspace%`, I am going to close this. `%workspace%` is superior to relative paths, because it is unclear realtive to what: workspace? current directory? bazel binary directory? Only the first choice makes sense, and it is already implemented.
