### ISSUE TITLE
Unable to build .so file with tensorflow

### ISSUE THREAD

**Issue by Zumbalamambo** [bazelbuild/bazel#3053]
Im trying to build so file from tensorflow. Im getting the following error. I have put up both command and error as follows,

```
Zumbala-MacBook-Pro:tensorflow Zumbala$ bazel build -c opt //tensorflow:libtensorflow.so
Unexpected error reading .blazerc file '/Users/Zumbala/Documents/tensorflow/.tf_configure.bazelrc'
```

**Comment by iirina** [comment]
Have you written the `.tf_configure.bazelrc` file or was it generated? Can you paste its content?

**Comment by laszlocsomor** [comment]
@Zumbalamambo : the error means that there was an I/O error reading `/Users/Zumbala/Documents/tensorflow/.tf_configure.bazelrc`. Possible reasons: it's not a file, you don't have permission to read it, it contains bad entries, maybe more than that.

As @iirina asked, was that file auto-generated? Did you edit it? Can you show us its contents?

**Comment by laszlocsomor** [comment]
Also, what's the output of `bazel version`?

**Comment by aqeeliqbal** [comment]
any update on this one?
on running `Configure` i get this error:

`sudo ./configure 
Please specify the location of python. [Default is /Library/Frameworks/Python.framework/Versions/2.7/bin/python]: 
Please specify optimization flags to use during compilation [Default is -march=native]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] n
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] n
No XLA JIT support will be enabled for TensorFlow
Found possible Python library paths:
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Please input the desired Python library path to use.  Default is [/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages]

Using python library path: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] n
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] n
No CUDA support will be enabled for TensorFlow
Configuration finished
Unexpected error reading .blazerc file '/Volumes/DATA/tensorflow/.tf_configure.bazelrc'
`
bazel version is latest one.

**Comment by laszlocsomor** [comment]
@aqeeliqbal : No updates, we haven't heard from @Zumbalamambo . But since you saw the same error, could you help us please by pasting here the output of:
```
echo "user=($(whoami))"
ls -l /Volumes/DATA/tensorflow
stat /Volumes/DATA/tensorflow/.tf_configure.bazelrc
cat /Volumes/DATA/tensorflow/.bazelrc
```

**Comment by austingg** [comment]
@aqeeliqbal you may have remove the file `.tf_configure_bazelrc`, just touch one. then run `./configure`

**Comment by laszlocsomor** [comment]
I'm guessing this bug is obsolete. Please reopen if you think otherwise.
