### ISSUE TITLE
'bazel info' gives invalid exection_root, output_path for projects with WORKSPACE name not equal to the root directory name

### ISSUE THREAD

**Issue by brendandouglas** [bazelbuild/bazel#3055]
Happens when building bazel from HEAD.

Steps to reproduce:
1. find a bazel project
2. remove the `workspace(name = x)` line from the WORKSPACE file
3. `bazel clean`
4. `bazel info`

Output artifacts now appear under `[output_base]/execroot/__main__`, and `bazel info` shows the correct corresponding paths for `bazel-bin`, `bazel-genfiles`, etc.

However bazel info lists `execution_root` as `[output_base]/execroot/[project_root_dir_name]`, and `output_path` as `[output_base]/execroot/[project_root_dir_name]/bazel-out`, neither of which exist.

`execution_root` and `output_path` use the root directory name, but should instead use the WORKSPACE name.

**Comment by laszlocsomor** [comment]
Found the culprit: 85ae1905d4abfcd214bd53d6cd3d032ff246daf6, which is a rollback of c4134802dd15d6ef5cca6521f6bf6aac395ee2ad, which itself is a rollback of 1d9e1ac90197b1d3d7b137ba3c1ada67bb9ba31b.

I have an empty WORKSPACE file in a directory.

Pre-culprit:
```
  $ ../../gitroot/bazel/bazel-bin/src/bazel --batch info bazel-bin
Extracting Bazel installation...
(14:44:19) INFO: Current date is 2017-05-31
(...)/execroot/github3055/bazel-out/local-fastbuild/bin
```

At culprit:
```
  $ ../../gitroot/bazel/bazel-bin/src/bazel --batch info bazel-bin
Extracting Bazel installation...
(14:46:45) INFO: Current date is 2017-05-31
(...)/execroot/__main__/bazel-out/local-fastbuild/bin
```

**Comment by laszlocsomor** [comment]
So as I understand it, this is now working as intended. @kchodorow , can you confirm?

**Comment by laszlocsomor** [comment]
@brendandouglas : "__main__" is the default workspace name: https://github.com/bazelbuild/bazel/blob/c5d1d55a7fc27d72b58f14859429019b012f6a17/src/main/java/com/google/devtools/build/lib/cmdline/Label.java#L58

**Comment by brendandouglas** [comment]
The problem does now seem to be specific to workspaces without an explicitly-specified name.

Just built bazel from HEAD, and in the case where it falls back to the default workspace name, no symlink directory is set up in execroot/, which contains only '__main__' (however `execution_root` in `bazel info` still points to execroot/[root_dir_name], which doesn't exist).

**Comment by kchodorow** [comment]
Unfortunately `bazel info` it not able to pick up the "correct" workspace name yet (the workspace name is discovered during the build's loading phase and `info` never gets there).  I think this is a bug, we shouldn't be returning a non-existent dir, it might actually be better just to make this return `<output_base>/execroot` (with no directory suffix), as I think that's the directory we're moving (@lberki has proposed making actions cd to execroot, not `execroot/ws`, before running).

**Comment by brendandouglas** [comment]
If I build bazel from HEAD now, this appears to have regressed a little since the initial report -- for workspaces with non-default names, the 'execution_root' shown by bazel info exists, but is empty (it's no longer a symlink to the actual exec root).

bazel-bin, bazel-genfiles, etc. point to directories which actually exist, underneath the actual exec root.

This is breaking IntelliJ support, because we rely on knowing the execution root (e.g. to decode execution root relative paths).

**Comment by ulfjack** [comment]
Marking as a release blocker unless someone says otherwise.

**Comment by ulfjack** [comment]
@kchodorow Did you see this? Are you working on it?

**Comment by kchodorow** [comment]
Yes, I think I have a way to thread the name back to execution_root but it's not done yet.

**Comment by ulfjack** [comment]
Is that something we can cherrypick into 0.5.2? Do we need a shorter-term fix? Also, is the plan to load the WORKSPACE file for info? - I'm a bit concerned about the performance implication.

**Comment by kchodorow** [comment]
AFAICT, it already is loading the workspace name, it just isn't exposed to anything `info` sees.  `info` does some sort of skyframe sync that looks up `PACKAGE://external`.  I don't think this will be a great cherry pick but I don't know, I haven't coded it yet.

**Comment by brendandouglas** [comment]
I'm hitting this again in 0.5.3 -- this time, `bazel-bin`, `bazel-genfiles`, `bazel-testlogs` all point to a directory under `output_base` named from the WORKSPACE name.

But `output_path` points to a directory (empty in practice) named from the workspace root dir.

This is currently breaking IntelliJ support, though I can put in a workaround for the next plugin build (i.e. avoid using `output_path`).

**Comment by softprops** [comment]
I just hit this after upgrading to 0.5.4.

**Comment by softprops** [comment]
a bit more info 

```bash
$ ~/bin/bazel version
INFO: Reading 'startup' options from /usr/local/git_repo/meetup/modules/tools/bazel.rc: --host_jvm_args=-Dbazel.DigestFunction=SHA1 --watchfs
Build label: 0.5.4
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Aug 25 10:00:00 2017 (1503655200)
Build timestamp: 1503655200
Build timestamp as int: 1503655200

$ ~/bin/bazel info output_path
INFO: Reading 'startup' options from /usr/local/git_repo/meetup/modules/tools/bazel.rc: --host_jvm_args=-Dbazel.DigestFunction=SHA1 --watchfs
/home/doug/.cache/bazel/_bazel_doug/9b83aa90a589949dfeac2b73a9d75602/execroot/modules/bazel-out

$ ls /home/doug/.cache/bazel/_bazel_doug/9b83aa90a589949dfeac2b73a9d75602/execroot
__main__
```

note that `output_path`  is not an actual directory

This broke a CI script we use to collect test reports under `$(~/bin/bazel info output_path)/local-fastbuild/testlogs`

**Comment by softprops** [comment]
This is a workspace without an explicit name declared
