### ISSUE TITLE
--action_env not passing env to repository_ctx

### ISSUE THREAD

**Issue by jart** [bazelbuild/bazel#3057]
I want to bring to the Bazel team's attention https://github.com/tensorflow/tensorflow/issues/9436 where Bazel doesn't seem to be propogating environment variable information to our Python configuration repository rule. We're not sure what's going on, but I'm working around the issue in https://github.com/tensorflow/tensorflow/pull/10176.

**Comment by ulfjack** [comment]
Indeed. Bazel does _not_ forward --action_env=NAME, but it does forward --action_env=NAME=VALUE.

I recently looked at that code and was wondering why, but I'm not sure, and it may not be easy to fix.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
