### ISSUE TITLE
failed to use bazel, even for bazel info.

### ISSUE THREAD

**Issue by zhexuany** [bazelbuild/bazel#3060]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### If possible, provide a minimal example to reproduce the problem:
```
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_zhexuany/6bfb8836d8a7c642713005d68a02df63/external/bazel_tools/tools/cpp/cc_configure.bzl", line 829
		_get_escaped_darwin_cxx_inc_directories(repository_ctx, cc)
	File "/private/var/tmp/_bazel_zhexuany/6bfb8836d8a7c642713005d68a02df63/external/bazel_tools/tools/cpp/cc_configure.bzl", line 726, in _get_escaped_darwin_cxx_inc_directories
		for toolchain in toolchains: ...
type 'NoneType' is not iterable.
```
### Environment info
* Operating System:
macOs
* Bazel version (output of `bazel info release`):
0.50

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

release 0.5.0-homebrew

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)
No.
### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by zhexuany** [comment]
```
rm -rf /private/var/tmp/_bazel_zhexuany
```
did the trick.  Closing issue.

**Comment by zhexuany** [comment]
That operation does not work.

**Comment by damienmg** [comment]
Please follow #3063, this is duplicate.
