### ISSUE TITLE
How to get local repository_rule to rerun?

### ISSUE THREAD

**Issue by aj-michael** [bazelbuild/bazel#3062]
The docs for local repository_rules at https://bazel.build/versions/master/docs/skylark/repository_rules.html#when-is-the-implementation-function-executed only says

> If the repository is declared as local then change in a dependency in the dependency graph (including the WORKSPACE file itself) will cause an execution of the implementation function.

but it does not explain what the "dependency graph" is referring to in this context. AFAIK, the dependency graph usually refers to the configured target graph and repository rules are not a part of that.

My use case is this: I would like to rewrite AndroidSdkRepositoryFunction as a skylark repository rule. AndroidSdkRepositoryFunction uses DirectoryListingValues so that it is rerun whenever the contents of a certain directory changes (e.g. when a user installs a new API level). Is there a way to accomplish this with a Skylark repository rule?

**Comment by damienmg** [comment]
This should be a feature request, we do not support 
DirectoryListingFunction in skylark.

We probably need a proper design and API review for it, I am all for it especially that would enable tracking compiler that we were talking about with @ulfjack some time ago.

**Comment by ulfjack** [comment]
I think we need to allow local repositories to declare what changes need to trigger reruns. Directory listing for sure, as well as env variables; maybe other triggers as well?

**Comment by damienmg** [comment]
So far we have env variables, file dependency (label, so needs to be in the
workspace), and of course source of the repository function itself.

**Comment by aj-michael** [comment]
Other than directorylistingvalue and env variables, the Android repository rules also need filevalues, because we read some properties file to determine the the version of some things.
