### ISSUE TITLE
common JDKs don't support params files

### ISSUE THREAD

**Issue by chaoren** [bazelbuild/bazel#3069]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

The [scala rules](https://github.com/bazelbuild/rules_scala) is borrowing the [java_stub_template](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt) from the java rules, and it seems like [this line](https://github.com/bazelbuild/bazel/blob/8598824a26434167108a5a4925a971b498af109f/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt#L308) doesn't actually work.

### If possible, provide a minimal example to reproduce the problem:

```
$ ./bazel-bin/foo.runfiles/local_jdk/bin/java -classpath ./bazel-bin/foo.runfiles/__main__/foo.jar Foo
Hello world!
$ ./bazel-bin/foo.runfiles/local_jdk/bin/java -classpath @<(echo ./bazel-bin/foo.runfiles/__main__/foo.jar) Foo
Error: Could not find or load main class Foo
```

**Comment by laszlocsomor** [comment]
@chaoren : What platform did you try on?

**Comment by ittaiz** [comment]
OS X at least

**Comment by laszlocsomor** [comment]
I managed to repro this. Apparently neither OpenJDK for MacOS nor Zulu JRE (that we bundle Bazel 0.5.0 with) support parameter file syntax (i.e. `java -cp @paramfile classname`).

Repro:
```
cd /tmp

echo > Foo.java <<EOF
public class Foo { public static void main(String[] args) { System.out.println("Hello world!"); } }
EOF

javac Foo.java
```

Then this works:
```
$ java -cp /tmp Foo
Hello world!
```

But this doesn't:
```
$ echo /tmp > /tmp/cp.txt && java -cp @/tmp/cp.txt Foo
Error: Could not find or load main class Foo
```

Here's my Java:
```
$ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

**Comment by laszlocsomor** [comment]
This only affects users with very long classpaths (>120K) so I'm prioritizing it as P2.
We already work around this issue on Windows, so I'll just use that code path.

**Comment by laszlocsomor** [comment]
Just to clarify: process substitution (the `@<(echo $CLASSPATH)`) works fine on MacOS (it creates a named pipe as `/dev/fd/63`).

**Comment by ittaiz** [comment]
Do you know if oracle jdk works?

**Comment by laszlocsomor** [comment]
@ittaiz : It doesn't, I just tried.

**Comment by laszlocsomor** [comment]
Unfortunately Bazel doesn't pick up the fixed java_stub_template from the workspace, it's compiled into Bazel instead. So to see the effects of the bugfix, you must rebuild Bazel from head and use that binary, or wait for the next release.

**Comment by chaoren** [comment]
Won't this line cause a problem outside of cygwin?
https://github.com/bazelbuild/bazel/blob/102ce6ddc04063d26165c6a2167059f2348026bf/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt#L303
Can we please have a test for this?

**Comment by laszlocsomor** [comment]
Oops, you're right, good catch! I forgot to remove that line. Yes, this needs a test, I'll add one.
