### ISSUE TITLE
Bazel CI, bazel-tests: //src/test/shell/integration:skylark_flag_test times out on Linux/JDK7

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3072]
http://ci.bazel.io/view/Dashboard/job/bazel-tests/BAZEL_VERSION=HEAD-jdk7,PLATFORM_NAME=linux-x86_64/786/console

Relevant log lines:
```
//src/test/shell/integration:skylark_flag_test                          TIMEOUT in 61.7s
  /home/ci/.cache/bazel/_bazel_ci/29502e488c6c26e35c2694f6f4eb1ffe/execroot/io_bazel/bazel-out/local-fastbuild/testlogs/src/test/shell/integration/skylark_flag_test/test.log
```

**Comment by laszlocsomor** [comment]
I'm marking this test manual as a workaround until @brandjon can take a look.

**Comment by kchodorow** [comment]
Probably a dup of #2985.

**Comment by brandjon** [comment]
I can't account for how this test could be at fault. If #2985 means we can't run bazel in integration tests, then so be it until that's fixed.
