### ISSUE TITLE
{name}_nativedeps.so is not built

### ISSUE THREAD

**Issue by eustas** [bazelbuild/bazel#3079]
`{name}_nativedeps.so` is not built for `java_binary` / `java_test` targets, whether `launcher` attribute is set or not.

### Description of the problem / feature request / question:

Without nativedeps library it becomes difficult to load all the (transitively) required libraries at once.

### If possible, provide a minimal example to reproduce the problem:

BUILD
```
package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # MIT

genrule(
    name = "copy_link_jni_header",
    srcs = ["@openjdk_linux//:jni_h"],
    outs = ["jni/jni.h"],
    cmd = "cp -f $< $@",
)

genrule(
    name = "copy_link_jni_md_header",
    srcs = ["@openjdk_linux//:jni_md_h"],
    outs = ["jni/jni_md.h"],
    cmd = "cp -f $< $@",
)

cc_library(
    name = "jni_inc",
    hdrs = [":jni/jni.h", ":jni/jni_md.h"],
    includes = ["jni"],
)

cc_library(
    name = "jni",
    srcs = ["xxx_jni.cc"],
    deps = ["//:jni_inc"],
    alwayslink = 1,
)

java_library(
    name = "xxx",
    srcs = ["Xxx.java"],
    deps = [":jni"],
)

java_library(
    name = "xxx_tests",
    srcs = ["XxxTest.java"],
    deps = [
        ":xxx",
        "@junit_junit//jar",
    ],
    testonly = 1,
)

java_test(
    name = "XxxTest",
    test_class = "org.xxx.XxxTest",
    runtime_deps = [":xxx_tests"],
)
```

WORKSPACE
```
# Description:
#   Bazel workspace file for xxx.

workspace(name = "org_xxx")

maven_jar(
    name = "junit_junit",
    artifact = "junit:junit:4.12",
)

new_http_archive(
    name = "openjdk_linux",
    url = "https://bazel-mirror.storage.googleapis.com/openjdk/azul-zulu-8.20.0.5-jdk8.0.121/zulu8.20.0.5-jdk8.0.121-linux_x64.tar.gz",
    sha256 = "7fdfb17d890406470b2303d749d3138e7f353749e67a0a22f542e1ab3e482745",
    build_file_content = """
package(
    default_visibility = ["//visibility:public"],
)
filegroup(
    name = "jni_h",
    srcs = ["zulu8.20.0.5-jdk8.0.121-linux_x64/include/jni.h"],
)
filegroup(
    name = "jni_md_h",
    srcs = ["zulu8.20.0.5-jdk8.0.121-linux_x64/include/linux/jni_md.h"],
)""",
)
```

Xxx.java
```
package org.xxx;

class Xxx {
  static native int doXxx();
}
```

XxxTest.java
```
package org.xxx;

import static org.junit.Assert.fail;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

@RunWith(JUnit4.class)
public class XxxTest {

  static {
    System.loadLibrary("XxxTest_nativedeps");
  }

  @Test
  public void testXxx() {
    if (Xxx.doXxx() != 42) {
      fail("Nevermind");
    }
  }
}
```

xxx_jni.cc
```
#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL
Java_org_xxx_Xxx_doXxx(JNIEnv* env, jobject /*jobj*/) {
  return 42;
}

#ifdef __cplusplus
}
#endif
```

### Environment info
* Operating System:
Ubuntu

* Bazel version (output of `bazel info release`):
release 0.5.0

**Comment by laszlocsomor** [comment]
Thanks for the simple and clear repro!

Either the documentation is wrong (it leaks a Google-internal Java rule feature) or there's a bug (Bazel java rules don't generate the nativedeps.so even though they should). @cushon : Do you know anything about this?

The Android rules seem to support native deps though. @ahumesky : Do you know if that's the case?

**Comment by eustas** [comment]
Digging into implementation.
Currently I see that somewhat suspicious happening in navite deps collection (in JavaBinary.java):
`liblibjni.so` is added info list, whereas I'd expect to see `libjni.so`

**Comment by eustas** [comment]
`liblibjni.so` is OK, extra `lib` is carelessly added in `SolibSymlinkAction.getDynamicLibrarySoname`.
Going to investigate further.

**Comment by laszlocsomor** [comment]
Thanks for investigating!

**Comment by eustas** [comment]
What I see:
 * JavaBinary has no intention to create 'combined' library; so documentation should be fixed (or, better, implementation should be upgraded)
 * `java.library.path` is set to a directory that should contain symlinks to native dependency libraries; unfortunately this directory is not created

Going to take a look at android targets implementation, to see how native dependencies are processed there...

**Comment by eustas** [comment]
Now I have a working hack: https://github.com/eustas/bazel/commit/4b99a583af7fbe166aa414cc95d3b69ba48c72bc
With this hack it is possible to load native (JNI) libraries, however:
 * additional `lib` prefix is required
 * (not sure) multiple libraries might end-up to a single link (if they have the same name) -> will not work as expected

So, the only reasonable solution is to upgrade JavaBinary to match its description =)

**Comment by laszlocsomor** [comment]
Nice! Thank you for investigating and coming up with a fix.
I'm no expert on the Java rules, maybe @cushon can say more.
The safest and easiest way forward is to update the docs :)

**Comment by eustas** [comment]
Workaround: to force library being copied, reference it again in `data` attribute of executable target.

**Comment by dmitry-xnor** [comment]
It'd be good to fix this, this bug sabotages JNI builds for everything other than Android.

**Comment by eustas** [comment]
With some voodoo-rituals and a grain of luck I've managed to have working JNI builds for windows...
(see https://github.com/google/brotli/pull/612/files)

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
