### ISSUE TITLE
Bazel 0.5.0 doesn't set SDKROOT for cc_library dependencies

### ISSUE THREAD

**Issue by erikmchut** [bazelbuild/bazel#3080]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

Bazel 0.5.0 no longer sets the APPLE_* environment variables for dependent cc_library rules with a custom cc and objc CROSSTOOL

### If possible, provide a minimal example to reproduce the problem:

Minimal repro example provided here:
https://github.com/8thwall/bazel-issue-3080

Requires:
XCode and Mac OS X

Steps to reproduce:
git clone https://github.com/8thwall/bazel-issue-3080 
cd bazel-issue-3080
bazel build //example:example

Expected Result:
Build succeeds

Actual Result:
Build fails with error "tools/objc/cc-xcwrapper.sh: line 32: SDKROOT: parameter null or not set"

### Environment info
* Operating System:

Mc OS 10.12.1

* Bazel version (output of `bazel info release`):

bazel 0.5.0

###  Have you found anything relevant by searching the web?

Not yet.

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by erikmchut** [comment]
Minimal repro example provided here:
https://github.com/8thwall/bazel-issue-3080

**Comment by c-parsons** [comment]
In your example it looks like you have written your own crosstool and are not relying on the bazel default -- this is why the apple environment variables are not being set properly. Is there a reason you are not using the default?

The crosstool is what sets these environment variables. (Well, sort of.. It writes the environment variables that end up getting turned into SDKROOT.)
It is done so here:
https://github.com/bazelbuild/bazel/blob/master/tools/osx/crosstool/CROSSTOOL.tpl#L758

...And it depends on expanded values that are only available if the BUILD target is of type apple_cc_toolchain instead of cc_toolchain

I would recommend looking at the contents of:

```$(bazel info execution_root)/external/local_config_cc```

in recent bazel (0.5.0). After attempting a CC build with default crosstool flags, this directory will be a generated crosstool suite which sets these variables correctly.

**Comment by erikmchut** [comment]
> In your example it looks like you have written your own crosstool and are not relying on the bazel default -- this is why the apple environment variables are not being set properly. Is there a reason you are not using the default?

Our software stack shares native code across Android, iOS, and Desktop builds and many architecture variants. Each of these targets requires a full-dependency tree to be recompiled with the correct toolchain and the the only way to achieve this in bazel is to rely on the built-in ability of apple_* rules and android_* rules to compile their dependency trees.  The default CROSSTOOL and compile scripts have never fully supported our use case for cc dependencies.

> The crosstool is what sets these environment variables. (Well, sort of.. It writes the environment variables that end up getting turned into SDKROOT.)
> It is done so here:
> https://github.com/bazelbuild/bazel/blob/master/tools/osx/crosstool/CROSSTOOL.tpl#L758

Something changed with Bazel 0.5.0.  cc_dependencies of apple_rules are no longer being compiled with these environment variables although they have in all previous versions.  

> 
...And it depends on expanded values that are only available if the BUILD target is of type apple_cc_toolchain instead of cc_toolchain

Understood, but cc_dependencies of apple_rules _are_ compiled using apple_cc_toolchain rules, and this appears to still work properly in 0.5.0

> I would recommend looking at the contents of:
> $(bazel info execution_root)/external/local_config_cc in recent bazel (0.5.0). After attempting a CC build with default crosstool flags, this directory will be a generated crosstool suite which sets these variables correctly.

We don't rely on the local_config_cc for the reasons provided above. Our CROSSTOOL is also locally-generated, but from custom scripts that differ from the crosstool_configure that ships with bazel.

**Comment by mhlopko** [comment]
Friendly ping @c-parsons

**Comment by c-parsons** [comment]
Apologies for not following up on this thread, but we sorted things out in a private thread weeks ago.

In short, a custom apple crosstool needs to set the environment variables XCODE_VERSION_OVERRIDE, APPLE_SDK_VERSION_OVERRIDE, and APPLE_SDK_PLATFORM, as is shown here by example: https://github.com/bazelbuild/bazel/blob/master/tools/osx/crosstool/CROSSTOOL.tpl#L758

**Comment by erikmchut** [comment]
Yes, the resolution was the following:

Beginning with Bazel 0.5.0, custom crosstools for apple/ios must explicitly
define the env variables XCODE_VERSION_OVERRIDE,
APPLE_SDK_VERSION_OVERRIDE, and APPLE_SDK_PLATFORM.  Prior versions of
Basel have automatically populated these.

The following is an example that can be added to a CROSSTOOL to fix
compilation, along with 'implies: "apple_env"' added to any action configs.

feature {
name: "apple_env"
env_set {
action: "c-compile"
action: "c++-compile"
action: "c++-module-compile"
action: "c++-header-parsing"
action: "c++-header-preprocessing"
action: "assemble"
action: "preprocess-assemble"
action: "objc-compile"
action: "objc++-compile"
action: "objc-archive"
action: "c++-link-executable"
action: "c++-link-dynamic-library"
action: "c++-link-static-library"
action: "c++-link-alwayslink-static-library"
action: "c++-link-pic-static-library"
action: "c++-link-alwayslink-pic-static-library"
action: "objc-executable"
action: "objc++-executable"
env_entry {
key: "XCODE_VERSION_OVERRIDE"
value: "%{xcode_version_override_value}"
}
env_entry {
key: "APPLE_SDK_VERSION_OVERRIDE"
value: "%{apple_sdk_version_override_value}"
}
env_entry {
key: "APPLE_SDK_PLATFORM"
value: "%{apple_sdk_platform_value}"
}
}
}

Thanks to cparsons for help with debugging and resolving.
