### ISSUE TITLE
git workflow suggestion for Bazel repo: avoid cherry-pick when prepping a new release

### ISSUE THREAD

**Issue by mmorearty** [bazelbuild/bazel#3081]
### Description of the problem / feature request / question:

It seems that that Bazel team's current git workflow is: When a new release is almost ready, make a branch for that release; then, as necessary, cherry-pick last-minute fixes from `master` into that branch, until the release is done.

My org has a fork of Bazel with some changes of our own, and the cherry-picking makes it very hard for us to move from one version of Bazel to the next, because we can't `git merge`. (At least, I _think_ it's the cherry-picks that are causing all the conflicts.)

I think that it might work better to turn your workflow around: When you have a change that needs to be in the upcoming release, first commit it to the release branch, and then merge (not cherry-pick) the release branch into `master`.

**Comment by mmorearty** [comment]
(Or perhaps you are currently cherry-picking from the release branch into master, instead of the other way around. If that's the case, then this workflow change is even easier to do)

**Comment by damienmg** [comment]
In which way would that make it easier? I meant the cherry-picked commit would be the same as the master one. Also we do follow a develop @ HEAD model so we cannot just merge change from a release branch.

**Comment by mmorearty** [comment]
Here's a concrete example of the sort of merge conflicts that I've been getting. Try this — start at version 0.4.5 and then try to "merge" to get up to version 0.5.0, with no custom changes at all:

    $ git checkout 0.4.5
    $ git checkout -b mybranch
    $ git merge 0.5.0

That's a pretty simple series of commands, and I would think it would work; yet it results in merge conflicts in 36 files.

If you take a look at the conflict in CHANGELOG.md, you'll see that git can't resolve the "conflict", because the 0.4.5 version has the description of 0.4.5; the 0.5.0 version has that plus the description of 0.5.0; and the merge-base has neither. If `git merge` was being used instead of cherry-picking, git would have been able to figure out what to do.

I did eventually figure out a workaround: I `git merge` twice. First, I `git merge` only up to the commit on `master` that corresponds directly to the corresponding head of 0.4.5; then I `git merge` again the rest of the way. That way, most of the changes that git sees in the first `git merge` are identical on both sides. Like this:

    $ git checkout 0.4.5
    $ git checkout -b mybranch
    # merge only up to the master commit that corresponds to the head of 0.4.5:
    $ git merge 8d635fc57
    # resolve just one conflict. then:
    $ git merge 0.5.0

**Comment by juhalindfors** [comment]
I was noticing something similar when attempting to merge from upstream to a personal repository. I think cherry-picking might be an issue as @mmorearty points out.

[This article](http://www.draconianoverlord.com/2013/09/07/no-cherry-picking.html) was clarifying some things for me, as I am used to cherry picking in subversion where it flows nicely, but things seem to work differently in git. In short, assuming the article is correct, git does not store any metadata about the origins when cherry-picking (equivalent of svn:mergeinfo). That could explain the odd merge conflicts if the merge implementation cannot identify equal patch sets.

Copying here in case its helpful:

> Git vs. Subversion’s cherry pick. Even though it’s the same conceptual operation, the details are different between the two systems. Specifically:
>
> In git, git cherry-pick copy/pastes a commit from one branch to another.
> 
> In doing so, when the commit is “pasted” onto the new branch, it now has a new parent commit (which would be whatever the tip of that branch was when the “paste” happened).
> 
> And since parent ids are part of the new commit’s SHA1 id, the pasted commit now has a new commit id.
> 
> So you now have two physically distinct commits in your repository for the same logical change. And no metadata tying them together.
> 
>The DAG does not give any hints that these two separate commits are the same conceptual change.
>
>My friend’s assertion was that that’s pretty ugly. And it is.

>  In contrast, in Subversion, it also pastes the diff onto the new branch (which technically makes a new Subversion version number), but it records in the metadata (svn:mergeinfo) where the commit came from.

**Comment by damienmg** [comment]
Why not use rebasing instead of merging?

**Comment by juhalindfors** [comment]
I'll try that next time. Thanks for the tip.

**Comment by mmorearty** [comment]
@damienmg was your suggestion about rebasing intended for @juhalindfors, or for me?

If it was for me: I'm unclear on how rebasing instead of merging would help.

**Comment by damienmg** [comment]
@mmorearty   Rebasing would try to find out cherry-picks instead of merging them, it should just work fine to do `git rebase 0.5.0`

**Comment by mhlopko** [comment]
I guess we can close this issue now, feel free to shout at me otherwise :)
