### ISSUE TITLE
v0.5.0 No such attribute forcibly_disable_header_compilation in java_toolchain on Fedora 25

### ISSUE THREAD

**Issue by chemelnucfin** [bazelbuild/bazel#3083]
### Description of the problem / feature request / question:

Trying to build version 0.5.0

### If possible, provide a minimal example to reproduce the problem:

bazel build //src:bazel

### Environment info
* Operating System:

Fedora 25

* Bazel version (output of `bazel info release`):

development version - tag 0.5.0 -
1cc2041ed3f9f4eaf16e606e2c61e59d35fd597d

###  Have you found anything relevant by searching the web?

Seems related to this:
https://github.com/bazelbuild/bazel/issues/2603

### Anything else, information or logs or outputs that would be helpful?

ERROR: (project_root)/bazel/tools/jdk/BUILD:136:1: //tools/jdk:toolchain: no such attribute 'forcibly_disable_header_compilation' in 'java_toolchain' rule.
ERROR: (project_root)/bazel/src/BUILD:126:2: Target '//tools/jdk:jdk7' contains an error and its package is in error and referenced by '//src:embedded_tools'.
ERROR: Analysis of target '//src:bazel' failed; build aborted.

**Comment by laszlocsomor** [comment]
That looks like a custom-built bazel -- how did you build it? Did you have any local modifications in the source tree?

**Comment by chemelnucfin** [comment]
I used ./compile.sh after checkout 0.5.0
then it tells me to use 
bazel build //src:bazel

I don't have any local modifications.
It has built before in previous 0.4.? version.

**Comment by xzy256** [comment]
@chemelnucfin How do you get source?
got source is incomplete by `git clone` , lacking of  the generated files needed
for bootstrapping. Please download [bazel-0.5.0-dist.zip](https://github.com/bazelbuild/bazel/releases/download/0.5.0/bazel-0.5.0-dist.zip), unpack it, then execute compile.sh for building source.

**Comment by chemelnucfin** [comment]
I did use git clone.  What would I need to boostrap from git clone?  (It'd
be easier to update bazel version in the future)

**Comment by xzy256** [comment]
> I did use git clone. What would I need to boostrap from git clone? (It'd be easier to update bazel version in the future)

I have no idea. @laszlocsomor Could  you give some ideas? As if  you only download and build relevant bazel-xxx-dist.zip  for updating bazel version

**Comment by laszlocsomor** [comment]
@chemelnucfin : You cannot bootstrap from the code at HEAD (`git clone`); you can only bootstrap from the [distribution archive](https://github.com/bazelbuild/bazel/releases/download/0.5.0/bazel-0.5.0-dist.zip).
If you have a bazel binary already, then you can build from HEAD: `bazel build //src:bazel`

**Comment by laszlocsomor** [comment]
I just re-read this thread.

@chemelnucfin : 
> It has built before in previous 0.4.? version.

Yes, bootstrapping from `git clone`'d code used to work until 0.4.2'ish, can't remember anymore in which version we stopped supporting that, since then you can only bootstrap from the distribution archive.

**Comment by chemelnucfin** [comment]
got it.  I will close the issue now.
