### ISSUE TITLE
CI tests for jdk7 Windows seem to not do anything.

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#3084]
My change fails on every platform, but not jdk7 on Windows. Looking at the Windows jdk7 test log it took 7.5 seconds. So it doesn't seem to test anything.

![screenshot from 2017-05-31 09 49 12](https://cloud.githubusercontent.com/assets/1388179/26621303/a717365a-45e6-11e7-9283-c18a749bbe24.png)

http://ci.bazel.io/job/CR/job/bazel-tests/15/

Is that expected as we just stopped testing with JDK7?

**Comment by laszlocsomor** [comment]
I don't know for sure, but I believe this is a known issue.
@meteorcloudy ?

**Comment by meteorcloudy** [comment]
Yes, this is an intended behavior on Windows. 
See https://github.com/bazelbuild/continuous-integration/search?p=2&q=jdk7&type=&utf8=%E2%9C%93

**Comment by laszlocsomor** [comment]
Thanks Yun!
