### ISSUE TITLE
Override args in alias [enhancement]

### ISSUE THREAD

**Issue by cpenner-va** [bazelbuild/bazel#3091]
### Description of the problem / feature request / question:

We're attempting to add a `generate_workspace` command to your build file; this is what we have:

```
#WORKSPACE
http_archive(
    name = "io_bazel",
    url = "https://github.com/bazelbuild/bazel/releases/download/0.4.5/bazel-0.4.5-dist.zip",
    sha256 = "2b737be42678900470ae9e48c975ac5b2296d9ae23c007bf118350dbe7c0552b",
)

#BUILD

alias(
    name = "generate_workspace",
    actual = "@io_bazel//src/tools/generate_workspace:generate_workspace",
)
```

This is pretty much a stop-gap to allow us to call generate_workspace reliably until the story for that is better; the problem is that I'd like to add an `args` override to the alias which includes all of our java artifacts which we depend on, something like:

```
alias(
    name = "generate_workspace",
    actual = "@io_bazel//src/tools/generate_workspace:generate_workspace",
    args = [
        "-a junit:junit:4.12",
        "-a org.hamcrest:hamcrest-all:1.3",
        "-a org.mockito:mockito-all:1.9.5",
    ]
)
```

As is, there doesn't appear to be a way to alias a build rule and and override some parameters (not strictly an alias I suppose).

Granted the workflow we're using for generating workspaces is less than idea, if anyone has better ideas I'm open to them 😋 

Thanks!

**Comment by damienmg** [comment]
Reassigning to Kristina for reevaluation, it should probably be moved to bazelbuild/migration-tools

**Comment by kchodorow** [comment]
This was reported as https://github.com/bazelbuild/migration-tooling/issues/24 and fixed.
