### ISSUE TITLE
Building with --output_groups=intellij-compile doesn't do anything

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#3095]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

When building Bazel itself using "Bazel > Build > Compile Project" in the IntelliJ plug-in, it runs a build with a command-line roughly like this:

`bazel build --output_groups=intellij-compile //src:bazel //src/test/...`

This doesn't actually build anything, though:

```
philwo-macbookpro2:bazel philwo$ bazel build --output_groups=intellij-compile //src:bazel //src/test/...
.........
INFO: Analysed 243 targets (239 packages loaded).
INFO: Found 243 targets...
INFO: Elapsed time: 10.954s, Critical Path: 0.02s
INFO: Build completed successfully, 1 total action
```

Introducing a simple error into WorkerSpawnStrategy.java still gives you a successful build using that command-line. Leaving out "--output_groups=intellij-compile" correctly lets the build fail and shows the compiler error about the error you introduced.

### If possible, provide a minimal example to reproduce the problem:

```
git clone https://github.com/bazelbuild/bazel.git &&
cd bazel &&
sed 's/UserExecException/NopeNopeNope/g' src/main/java/com/google/devtools/build/lib/worker/WorkerSpawnStrategy.java > tmp &&
mv tmp src/main/java/com/google/devtools/build/lib/worker/WorkerSpawnStrategy.java &&
bazel build --output_groups=intellij-compile //src:bazel //src/test/...
```

Expected:
```
src/main/java/com/google/devtools/build/lib/worker/WorkerSpawnStrategy.java:197: error: cannot find symbol
      throw new NopeNopeNope(
                ^
  symbol:   class NopeNopeNope
  location: class WorkerSpawnStrategy
Target //src:bazel failed to build
```

Actual:
```
INFO: Build completed successfully, 1 total action
```

### Environment info
* Operating System:
macOS 10.12.5

* Bazel version (output of `bazel info release`):
release 0.5.0

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by philwo** [comment]
Pinging @brendandouglas, in case he noticed this, too or knows what might cause this.

**Comment by brendandouglas** [comment]
This is an intellij bazel plugin bug -- I fixed it for the next release (https://github.com/bazelbuild/bazel/commit/74d19e62de915ccdb871503558e48fdaacce56e8).

However you'll have to wait for either the next bazel release (our aspect is currently shipped with bazel) or the next plugin release (I'm just in the process of bundling the aspect with the plugin).

**Comment by brendandouglas** [comment]
I'm not able to close bugs here -- can someone else close this? (it's not a Bazel bug, and is also fixed)
