### ISSUE TITLE
Passing empty filegroup fails due to extension enforcement

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3099]
### Description of the problem / feature request / question:

I have the following attribute:

    "data": attr.label_list(allow_files = [".myext"], cfg = "data"),

Now in 0.4.5 it was ok, to assign an empty `filegroup` to `data`, while in 0.5.0 I get the error, that:

    does not produce any _myrule data files (expected .myext)

Which behavior is correct!?

### Environment info
* Operating System: Ubuntu 16.04
* Bazel version (output of `bazel info release`): 0.5.0

**Comment by laszlocsomor** [comment]
@vladmos , @laurentlb : Do you know if anything here changed?

**Comment by laurentlb** [comment]
I have tried with Bazel 0.4.2 and it fails in the same way.
Do you have reproduction steps?

**Comment by abergmeier-dsfishlabs** [comment]
> I have tried with Bazel 0.4.2 and it fails in the same way.

You are right, actually it is a patch we have in our fork, where we only error if the attribute `isNonEmpty`.
Who is the Bazel lawyer, who can tell whether e.g. a empty filegroup should produce this error.

I am torn.

**Comment by laurentlb** [comment]
Current behavior is intended. We can keep this feature request to allow this use-case.

**Comment by abergmeier-dsfishlabs** [comment]
> We can keep this feature request to allow this use-case.

Looked at our use cases and changing the way Macros and Rules were implemented made more sense. So currently I have no good use-case for it.
