### ISSUE TITLE
Support a tooling API for tooling suitable for IDE integrations by third-parties

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/bazel#31]
Whether or not Bazel supports Eclipse or Intellij or other tools directly, there are a lot of useful hooks that would permit third-parties to write their own APIs.  This especially includes:

  * Exposing an annotated dependency graph
  * Exposing hooks around build-steps for given rules, or in a general way
  * Allowing hooks for alternate builders, so that incremental compilers like Eclipse's can provide the compilation, and using the produced information in Bazel's computations of what has been completed (in effect, allowing integration of incremental compilation information between the tools).
  * hooks/entry-points for partial invocations within tooled contexts, to reduce the work needed to be done by bazel, where such work is already done by the tool. 

That's all I can think of just now, but I wanted this tracking bug in place, more focused on the tooling api.

**Comment by davidzchen** [comment]
Having YouCompleteMe integration would be awesome as well. :)

**Comment by byzhang** [comment]
+1 for YCM

**Comment by jcanizales** [comment]
This would be so sweet to have.

**Comment by jdc2172** [comment]
just wondering if this is still planned, or if it's been shelved for a later release - I really like bazel, but ide support is quite important for me

**Comment by damienmg** [comment]
It is still planned for the end of the week (the interface  exists and is
in the 0.3.0rc1).

**Comment by dslomov** [comment]
For the impatient, take a look at https://github.com/bazelbuild/e4b and http://tulsi.bazel.io/
