### ISSUE TITLE
Bazel builds occasionally able to crash OS X Terminal in which they were launched

### ISSUE THREAD

**Issue by BrendanDrewZippy** [bazelbuild/bazel#3101]
### Description of the problem / feature request / question:

I've seen this a few times with our code base but I have not been able to isolate the exact problem. It is a fairly modest code base; however, it does pull in a lot of 3rd party dependencies. 

At some point when running bazel build, something will happen that causes the entire terminal to crash (not just one tab, the whole OS X terminal app). If I am building something that takes a long time, I am able to avoid this by minimizing the terminal shortly after launching the build.

### If possible, provide a minimal example to reproduce the problem:
N/A

FWIW, I have sent the crash reports to Apple

### Environment info
* Operating System:
Configuration:
Hardware Overview (current gen MBP with touch bar):
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro13,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.7 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB
  Boot ROM Version:	MBP133.0226.B23
  SMC Version (system):	2.38f7

OS: macOS Sierra 10.12.5
  System Version:	macOS 10.12.5 (16F73)
  Kernel Version:	Darwin 16.6.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	5:12

* Bazel version (output of `bazel info release`):
bazel info release
INFO: Reading 'startup' options from /Users/bdrew/devel/zippy/.bazelrc: --host_jvm_args=-Xmx2500m --host_jvm_args=-Xms2500m --batch
release 0.4.5-homebrew

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

N/A

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)
Nothing obvious on github or stackoverflow

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by laszlocsomor** [comment]
Next time this happens, can you show us the of the java.log and jvm.out of Bazel? You can find them under `$(bazel info output_base)/java.log` and `$(bazel info output_base)/server/jvm.out`.

**Comment by ittaiz** [comment]
@laszlocsomor is this info written in any troubleshooting doc?

**Comment by laszlocsomor** [comment]
@ittaiz : Do you mean the log files? Not that I know of. Can you think of a good location to mention them? Where would you look for them?

I know about https://docs.bazel.build/versions/master/output_directories.html#bazel-internals-directory-layout, but AFIAK it's outdated and I wouldn't think to look at it while troubleshooting.

**Comment by ittaiz** [comment]
Yes.
I guess I'll go to bazel.build and search for "troubleshooting" or
"reporting issues"

**Comment by jin** [comment]
Closing this as not reproducible and obsolete, please ping this issue if you are running into this issue again.
