### ISSUE TITLE
HtmlChart is uncolored

### ISSUE THREAD

**Issue by ahippler** [bazelbuild/bazel#3102]
### Description of the problem / feature request / question:

Legend and Chart are completely white.

![bildschirmfoto 2017-06-02 um 11 51 27](https://cloud.githubusercontent.com/assets/28805183/26720825/e64d9e32-4789-11e7-929a-f32b1a79a39c.png)

### Environment info

* Operating System: MacOSX
* Bazel version: release 0.4.5-homebrew

### Reason

css color values `background-color:rgba(102,153,204,1,000000)` are not valid . This should be a result of german decimal separator ','. 

### Solution

force '.' as decimal separator.

**Comment by laszlocsomor** [comment]
Thanks for the bug report! Unfortunately we have no capacity to fix it now, so I'm marking it P4 to indicate that we need external help to fix it. Would you be interested in fixing it?
