### ISSUE TITLE
Checkers Support

### ISSUE THREAD

**Issue by nordlow** [bazelbuild/bazel#3103]
How do I extend Bazel with targets that process C/C++-code via checkers such as 

- qac
- cppcheck
- iwyu

?

Do I need to use a `genrule` or is there some other target rule for that?

**Comment by laszlocsomor** [comment]
I think you're looking for https://bazel.build/versions/master/docs/be/extra-actions.html

Please ask questions on [StackOverflow (tag #bazel)](https://stackoverflow.com/questions/tagged/bazel), there's a bigger community monitoring that and it's also more easily searchable.

**Comment by nordlow** [comment]
Done: https://stackoverflow.com/questions/44342503/bazel-checkers-support

Thanks.
