### ISSUE TITLE
Placeholders $1, $2, ... in ctx.action are not replaced on Windows.

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#3104]
In a Skylark rule I tried to create an action that copies a file from a to b:

```
ctx.action(
  command = "cp $1 $2",
  arguments = [foo, bar],
  ...
)
```

That works on Linux and Mac, but not on Windows. On Windows `$1` and `$2` are not replaced by the values of `foo` and `bar`. According to our documentation [1], using `$1` and `$2` should work.

[1] https://bazel.build/versions/master/docs/skylark/lib/ctx.html#action

**Comment by laszlocsomor** [comment]
`ctx.action` starts an OS-native subprocess, and on Windows `$1` doesn't make sense. You need to use `%1` and `%2`.

Could you update the docs to say that?
