### ISSUE TITLE
Bazel shows wrong action / test duration when waiting for resources

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#3106]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

Imagine four tests sleep0, sleep1, sleep2 and sleep3. The only thing they do is to sleep 15 seconds and then succeed. sleep2 and sleep3 use the "cpu:200000" tag to tell Bazel that they need 200,000 CPU cores to run. This causes the following behavior:

sleep0 and sleep1 run in parallel. then sleep2 runs. then sleep3 runs.

The whole run should take roughly 45 seconds, with each individual test taking 15 seconds.

```
philwo@philwo:~/bazel-test$ bazel --blazerc=/dev/null test --nocache_test_results //examples/java-native/src/test/java/com/example/myproject:sleep{0,1,2,3}
INFO: Found 4 test targets...
INFO: Elapsed time: 46.067s, Critical Path: 45.92s
//examples/java-native/src/test/java/com/example/myproject:sleep0        PASSED in 30.6s
//examples/java-native/src/test/java/com/example/myproject:sleep1        PASSED in 30.6s
//examples/java-native/src/test/java/com/example/myproject:sleep2        PASSED in 15.3s
//examples/java-native/src/test/java/com/example/myproject:sleep3        PASSED in 45.9s
```

Expected:
- PASSED in 15s for each test

Observed:
- The time waiting for resource acquisition is counted towards the test run time, which is wrong.
- This happens with the old and the new, experimental UI, so it's not a UI bug.

### If possible, provide a minimal example to reproduce the problem:

See above, but will also add code to the Bazel repo to illustrate this.

### Environment info
* Operating System: Linux
* Bazel version (output of `bazel info release`): 0.5.0

**Comment by ulfjack** [comment]
The bug is in StandaloneTestStrategy - it shouldn't measure wall time, but take the time from the SpawnResult.

**Comment by ulfjack** [comment]
We don't currently pass back the SpawnResult, so this will have to wait until we've refactored the strategies to all use SpawnRunner and all return SpawnResult.

**Comment by ulfjack** [comment]
I think we now always pass back the SpawnResult. Unfortunately, we pass back a list now. :-/

**Comment by mrdaulet** [comment]
This is still the case for Bazel 0.18.0, any plans to fix it? It causes frequent timeouts for unit tests, currently working around by setting higher test timeout.

**Comment by ulfjack** [comment]
This is related to #4808 I think, which has cccd7185384764a9ad4cd22ff18212602e765c22 attached to it. It seems that there is a code path not collecting wall time - sandboxing perhaps?

**Comment by philwo** [comment]
Amazingly, this still seems to be broken, but in a different way. Repro:

```bash
cat > BUILD <<'EOF'
sh_test(
    name = "test1",
    srcs = ["test.sh"],
    tags = ["cpu:200000"],
)

sh_test(
    name = "test2",
    srcs = ["test.sh"],
    tags = ["cpu:200000"],
)

sh_test(
    name = "test3",
    srcs = ["test.sh"],
    tags = ["cpu:200000"],
)

sh_test(
    name = "test4",
    srcs = ["test.sh"],
    tags = ["cpu:200000"],
)
EOF

cat > test.sh <<'EOF'
#!/bin/bash

sleep 5
EOF

chmod +x test.sh
```

results in output like this:

```
philwo@philwo-imacpro ~/src/repro bazel --nohome_rc test --nocache_test_results :all
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/Users/philwo/.bazelrc
INFO: Analyzed 4 targets (0 packages loaded, 0 targets configured).
INFO: Found 4 test targets...
[1 / 5] 4 actions, 3 running
    Testing //:test3; 13s darwin-sandbox
    Testing //:test2; 8s darwin-sandbox
    Testing //:test4; 3s darwin-sandbox
    [Sched] Testing //:test1; 13s
```

I have no idea why the time for test3 and test2 keeps counting up, even though the test is already finished.

The end result is shown correctly though:

```
//:test1                                                                 PASSED in 5.1s
//:test2                                                                 PASSED in 5.1s
//:test3                                                                 PASSED in 5.1s
//:test4                                                                 PASSED in 5.1s
```

I can repro this no matter whether I use the darwin-sandbox or local strategy.

**Comment by ulfjack** [comment]
There was a fix to the status lines a couple weeks ago. Which bazel version did you use?

**Comment by meisterT** [comment]
This still reproduces with current Bazel.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
