### ISSUE TITLE
Bazel calls VS 2010's cl with /DEBUG:FASTLINK

### ISSUE THREAD

**Issue by haferburg** [bazelbuild/bazel#3109]
```
G:\src\test_projects\bazel_tutorial>bazel info release
release 0.5.0

G:\src\test_projects\bazel_tutorial>set bazel_vs
BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio 10.0

G:\src\test_projects\bazel_tutorial>bazel build main:hello-world --verbose_failures
...
  external/local_config_cc/wrapper/bin/msvc_cl.bat /nologo -Wl,-S /OUT:bazel-out/msvc_x64-fastbuild/bin/main/hello-world.exe /MACH
INE:X64 /SUBSYSTEM:CONSOLE -Xcompilation-mode=fastbuild -Wl,@bazel-out/msvc_x64-fastbuild/bin/main/hello-world.exe-2.params /DEFAU
LTLIB:libcmt.lib /DEBUG:FASTLINK /INCREMENTAL:NO: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with
status 1117.
LINK : fatal error LNK1117: syntax error in option 'DEBUG:FASTLINK'
```

As far as I can tell, cl.exe supports `/DEBUG:FASTLINK` only in versions 2015 or later. In the earlier versions, it's only `/DEBUG`. I didn't see a list of supported VS versions, e. g. on the [Using Bazel on Windows](https://bazel.build/versions/master/docs/windows.html) page.

**Comment by sbilkoloft** [comment]
@laszlocsomor any update on this? I'm hitting this as well. I have VS 2010 professional and I can't create any binaries because of this. Please advise on a possible workaround. Thanks.

**Comment by laszlocsomor** [comment]
@sbilkoloft : Here's a workaround:

1. Clone the Bazel repository
2. Patch the CROSSTOOL template: https://github.com/bazelbuild/bazel/blob/aeb863a9bfa94ea366c8cb5d1c64042fdf42d782/tools/cpp/CROSSTOOL.tpl#L834
3. Build Bazel: `bazel build //src:bazel`
4. Use the resulting Bazel binary to build your code.

**Comment by sbilkoloft** [comment]
Thanks for the help @laszlocsomor. I tried the solution and seems like it's beyond redemption:

C:\msys64\tmp\_bazel_sbilkoloft\qagro95y\execroot\io_bazel\src/main/cpp/util/port.h(19) : fatal error C1083: Cannot open include file: 'cinttypes': No such file or directory
Target //src:bazel.exe failed to build

I found this:
https://connect.microsoft.com/visualstudio/feedback/details/748766/c-11-header-cinttypes-is-missing-microsoft-visual-studio-ultimate-2012-rc-11-0-50522-1

Seems like they just didn't fix it.

**Comment by laszlocsomor** [comment]
@sbilkoloft : You're welcome! I'm sorry to hear it didn't work. Can you install a newer version? Bazel supports the VC++ Build Tools 2017, see our ["Getting started" guide](https://docs.bazel.build/versions/master/windows.html#build-c).

Meanwhile I realized that my step (3) would require you have a patched Bazel already. But I think you could avoid that by building Bazel from source:

1. download Bazel's distribution archive
2. patch the CROSSTOOL.tpl *and* CROSSTOOL files (we use the latter just for bootstrapping Bazel)
3. bootstrap bazel ([build it from source](https://docs.bazel.build/versions/master/install-compile-source.html))

Although if the compiler is buggy, there's not much left to do.

**Comment by meteorcloudy** [comment]
@sbilkoloft I suspect `cinttypes` might doesn't exist in older version of MSVC, since `port.h` depends on it, it's unlikely we can build Bazel with it.

But, what you can do is using an existing Bazel binary with a custom CROSSTOOL,
Here's one you can use easily, https://github.com/meteorcloudy/windows-crosstool
Download the repo, and use the `local_repository` rule to use this CROSSTOOL.
Then you can modify the CROSSTOOL without rebuild Bazel itself.

**Comment by sbilkoloft** [comment]
@laszlocsomor @meteorcloudy thanks for the help. I went  with VS 2017 community.  Seems like my original 2017 installation had problems so I thought to give my 2010 a try.

**Comment by sbilkoloft** [comment]
And things work with 2017 now btw.

**Comment by laszlocsomor** [comment]
I'll update the docs to say we need VS 2013 or older.

VS 2012 might work too, I don't know and can't test.

**Comment by meteorcloudy** [comment]
@laszlocsomor The error you got from your local machine in https://github.com/bazelbuild/bazel/issues/4240  is caused by this bug.
We should fix the CROSSTOOL and auto configuration to make it work with older version of VC
