### ISSUE TITLE
Warning in C++ code

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#311]
This is after the CROSSTOOL change to enable -Wall, on a mac (no -Werror yet):

third_party/ijar/zip.cc:251:8: warning: private field 'zipdata_out_mapped_' is not used [-Wunused-private-field]
  u1 \* zipdata_out_mapped_;       // start of still mapped region
       ^
1 warning generated.

**Comment by ulfjack** [comment]
More warnings on Ubuntu 14.04:

INFO: From Compiling third_party/ijar/zip.cc:
third_party/ijar/zip.cc: In member function 'int devtools_ijar::InputZipFile::ProcessLocalFileEntry(size_t, size_t)':
third_party/ijar/zip.cc:414:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (p - zipdata_in_mapped_ > MAX_MAPPED_REGION) {
                                ^
third_party/ijar/zip.cc: In member function 'void devtools_ijar::OutputZipFile::WriteCentralDirectory()':
third_party/ijar/zip.cc:788:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int ii = 0; ii < entries_.size(); ++ii) {
                                       ^
INFO: From Compiling third_party/ijar/zip.cc [for host]:
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined [enabled by default]
<built-in>:0:0: note: this is the location of the previous definition
third_party/ijar/zip.cc: In member function 'int devtools_ijar::InputZipFile::ProcessLocalFileEntry(size_t, size_t)':
third_party/ijar/zip.cc:414:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (p - zipdata_in_mapped_ > MAX_MAPPED_REGION) {
                                ^
third_party/ijar/zip.cc: In member function 'void devtools_ijar::OutputZipFile::WriteCentralDirectory()':
third_party/ijar/zip.cc:788:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int ii = 0; ii < entries_.size(); ++ii) {
                                       ^
INFO: From Compiling src/main/cpp/blaze_util.cc:
src/main/cpp/blaze_util.cc: In function 'std::string blaze::GetJvmVersion(const string&)':
src/main/cpp/blaze_util.cc:354:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
INFO: From Compiling third_party/ijar/ijar.cc [for host]:
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined [enabled by default]
<built-in>:0:0: note: this is the location of the previous definition
INFO: From Compiling src/main/native/unix_jni.cc:
src/main/native/unix_jni.cc: In function '_jobject* Java_com_google_devtools_build_lib_unix_FilesystemUtils_readdir(JNIEnv*, jclass, jstring, jchar)':
src/main/native/unix_jni.cc:635:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int ii = 0; ii < len; ++ii) {
                         ^
INFO: From Compiling src/main/cpp/blaze.cc:
src/main/cpp/blaze.cc: In function 'int blaze::StartServer(int)':
src/main/cpp/blaze.cc:520:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/main/cpp/blaze.cc: In function 'int blaze::Connect(int, const string&)':
src/main/cpp/blaze.cc:593:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/main/cpp/blaze.cc: In function 'int blaze::ConnectToServer(bool)':
src/main/cpp/blaze.cc:676:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
INFO: From Javac src/main/java/libshell-skylark.jar [for host]:
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
INFO: From Compiling third_party/ijar/classfile.cc [for host]:
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined [enabled by default]
<built-in>:0:0: note: this is the location of the previous definition
third_party/ijar/classfile.cc: In function 'devtools_ijar::Constant* devtools_ijar::constant(int)':
third_party/ijar/classfile.cc:107:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (idx < 0 || idx >= const_pool_in.size()) {
                                            ^
third_party/ijar/classfile.cc: In member function 'virtual void devtools_ijar::ExceptionsAttribute::Write(devtools_ijar::u1*&)':
third_party/ijar/classfile.cc:425:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int ii = 0; ii < exceptions_.size(); ++ii) {
                                            ^
third_party/ijar/classfile.cc: In destructor 'virtual devtools_ijar::InnerClassesAttribute::~InnerClassesAttribute()':
third_party/ijar/classfile.cc:444:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < entries_.size(); i++) {
                                       ^
third_party/ijar/classfile.cc: In member function 'virtual void devtools_ijar::InnerClassesAttribute::Write(devtools_ijar::u1*&)':
third_party/ijar/classfile.cc:469:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int ii = 0; ii < entries_.size(); ++ii) {
                                         ^
third_party/ijar/classfile.cc: In destructor 'virtual devtools_ijar::ArrayTypeElementValue::~ArrayTypeElementValue()':
third_party/ijar/classfile.cc:568:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < values_.size(); i++) {
                                      ^
third_party/ijar/classfile.cc: In member function 'virtual void devtools_ijar::ArrayTypeElementValue::Write(devtools_ijar::u1*&)':
third_party/ijar/classfile.cc:576:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int ii = 0; ii < values_.size(); ++ii) {
                                        ^
third_party/ijar/classfile.cc: In destructor 'virtual devtools_ijar::Annotation::~Annotation()':
third_party/ijar/classfile.cc:594:51: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < element_value_pairs_.size(); i++) {
                                                   ^
third_party/ijar/classfile.cc: In member function 'void devtools_ijar::Annotation::Write(devtools_ijar::u1*&)':
third_party/ijar/classfile.cc:603:53: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int ii = 0; ii < element_value_pairs_.size(); ++ii) {
                                                     ^
third_party/ijar/classfile.cc: In destructor 'virtual devtools_ijar::AnnotationsAttribute::~AnnotationsAttribute()':
third_party/ijar/classfile.cc:941:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < annotations_.size(); i++) {
                                           ^
third_party/ijar/classfile.cc: In member function 'virtual void devtools_ijar::AnnotationsAttribute::Write(devtools_ijar::u1*&)':
third_party/ijar/classfile.cc:961:45: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int ii = 0; ii < annotations_.size(); ++ii) {
                                             ^
third_party/ijar/classfile.cc: In member function 'virtual void devtools_ijar::ParameterAnnotationsAttribute::Write(devtools_ijar::u1*&)':
third_party/ijar/classfile.cc:997:55: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int ii = 0; ii < parameter_annotations_.size(); ++ii) {
                                                       ^
third_party/ijar/classfile.cc:1000:46: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int jj = 0; jj < annotations.size(); ++jj) {
                                              ^
third_party/ijar/classfile.cc: In destructor 'virtual devtools_ijar::HasAttrs::~HasAttrs()':
third_party/ijar/classfile.cc:1071:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < attributes.size(); i++) {
                                         ^
third_party/ijar/classfile.cc: In destructor 'virtual devtools_ijar::ClassFile::~ClassFile()':
third_party/ijar/classfile.cc:1120:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < fields.size(); i++) {
                                     ^
third_party/ijar/classfile.cc:1124:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < methods.size(); i++) {
                                      ^
third_party/ijar/classfile.cc: In member function 'void devtools_ijar::ClassFile::WriteBody(devtools_ijar::u1*&)':
third_party/ijar/classfile.cc:1155:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int ii = 0; ii < interfaces.size(); ++ii) {
                                           ^
third_party/ijar/classfile.cc:1159:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int ii = 0; ii < fields.size(); ++ii) {
                                       ^
third_party/ijar/classfile.cc:1163:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int ii = 0; ii < methods.size(); ++ii) {
                                        ^
third_party/ijar/classfile.cc: In member function 'void devtools_ijar::HasAttrs::WriteAttrs(devtools_ijar::u1*&)':
third_party/ijar/classfile.cc:1231:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int ii = 0; ii < attributes.size(); ii++) {
                                         ^
third_party/ijar/classfile.cc: In member function 'void devtools_ijar::ClassFile::StripIfAnonymous()':
third_party/ijar/classfile.cc:1342:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int ii = 0; ii < attributes.size(); ++ii) {
                                         ^
third_party/ijar/classfile.cc:1358:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int ii = 0; ii < fields.size(); ++ii) {
                                       ^
third_party/ijar/classfile.cc:1364:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int ii = 0; ii < methods.size(); ++ii) {
                                        ^
third_party/ijar/classfile.cc:1371:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int ii = 0; ii < attributes.size(); ++ii) {
                                           ^
third_party/ijar/classfile.cc: In function 'void devtools_ijar::StripClass(devtools_ijar::u1*&, const u1*, size_t)':
third_party/ijar/classfile.cc:1479:42: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < const_pool_in.size(); i++) {
                                          ^

**Comment by hanwen** [comment]
as of today, 

 bazel build third_party/ijar/... src/main/cpp/ src/test/cpp/...

only generates signed comparison errors for ijar in classfile.cc.

**Comment by tfarina** [comment]
@hanwen, @ulfjack: which compiler, which version and which os?

With g++ 4.8.1 on Ubuntu 12.04, I don't get any warnings anymore with:
$ ./output/bazel version
Build label: head (@af69e7a)
Build target: bazel-out/local_linux-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sun Jan 17 20:40:02 2016 (1453063202)
Build timestamp: 1453063202
Build timestamp as int: 1453063202

$ output/bazel build third_party/ijar/... src/main/cpp/... //src/test/cpp/...

**Comment by forumulator** [comment]
Hi. I see that commit @75dd495 fixes most of the warnings above, and as of today, `bazel build third_party/ijar/... src/main/cpp/... //src/test/cpp/...` does not generate any warnings in third_party/ijar (though there are quite a few `-Wunused-function` and `-Wmisleading-indentation`s in thirdparty/protobuf) . Is there anything remaining for this issue?

**Comment by mhlopko** [comment]
I'll take the liberty to close this issue, since no more action items are known.
