### ISSUE TITLE
Update protobuf and build bazel: no such attribute 'jars' in 'java_library' rule

### ISSUE THREAD

**Issue by Spenhouet** [bazelbuild/bazel#3110]
Because of having this issue with building tensorflow i try to update protobuf: https://stackoverflow.com/questions/44264801/build-protobuf-with-bazel-msvc-error-protobuf-pyext-message-so-failed

I'm doing it as described here: https://github.com/bazelbuild/bazel/tree/master/third_party/protobuf

1.  I cloned the current git head of protobuf (version 3.3.0).

1.  Followed the rest of the instruction

1.  Tried to build bazel (current git head) with `bazel build //src:bazel`
 
I'm getting this error:

```
ERROR: C:/tools/bazel/third_party/protobuf/3.3.0/BUILD:28:1: //third_party/protobuf/3.3.0:protobuf_java_util: no such attribute 'jars' in 'java_library' rule.
ERROR: C:/tools/bazel/third_party/protobuf/3.3.0/BUILD:37:1: //third_party/protobuf/3.3.0:protobuf_java: no such attribute 'jars' in 'java_library' rule.
ERROR: C:/tools/bazel/third_party/protobuf/BUILD:19:1: Target '//third_party/protobuf/3.3.0:protobuf_java' contains an error and its package is in error and referenced by '//third_party/protobuf:protobuf_java'.
```

The java rules in the BUILD file look like this:
```
java_library(
    name = "protobuf_java_util",
    jars = ["libprotobuf_java_util.jar"],
    visibility = ["//visibility:public"],
    exports = [
        "//third_party:gson",
    ],
)

java_library(
    name = "protobuf_java",
    jars = ["libprotobuf_java.jar"],
    visibility = ["//visibility:public"],
)
```
and the .jar files are in the `\third_party\protobuf\3.3.0` folder.

What could be wrong here? I don't understand why this error is happening.

**Comment by Spenhouet** [comment]
To update the protobuf version this instruction [here](https://github.com/bazelbuild/bazel/tree/master/third_party/protobuf) didn't work for me.

I got it to work with the following steps:

1. Copy the `third_party/protobuf/<old_proto_version>/BUILD` file to `third_party/protobuf/<new_proto_version>/BUILD` (replacing the existing one)

2. Change the line `//third_party/protobuf/<old_proto_version>/util/python:srcs` to `//third_party/protobuf/<new_proto_version>/util/python:srcs` in the `third_party/protobuf/<new_proto_version>/BUILD` file

3. Add the lines

```
licenses(["notice"])

filegroup(
    name = "srcs",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)
```
to the beginning of the `third_party/protobuf/<new_proto_version>/util/python/BUILD` file

4. Copy the files `io_win32.cc`, `io_win32.h` and `io_win32_unittest.cc` from `third_party/protobuf/<old_proto_version>/src/google/protobuf/stubs` to `third_party/protobuf/<new_proto_version>/src/google/protobuf/stubs`

5. Change the `PROTOBUF_VERSION` in the `third_party/protobuf/BUILD` file to <new_proto_version>.

6. Run `bazel build //src:bazel`

<old_proto_version> and <new_proto_version> are just placeholders for the actual version numbers in your situation.

**Comment by meisterT** [comment]
This is probably outdated, closing.
