### ISSUE TITLE
Bazel 0.5.0 server's `cmdline` output is broken

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3112]
Seeing this on Windows and Linux, didn't try on Mac.

`$(bazel info output_base)/server/cmdline` contains the command line of the Bazel server, as launched by the Bazel client. Mine contains a repetitive `-Djava.library.path` value and null-terminators instead of spaces between flags:

```
> bazel info release
(...)
release 0.5.0

> bazel info output_base
(...)
C:/tmp2/o6hbs7n0

> hexdump.exe -C c:\tmp2\o6Hbs7N0\server\cmdline
00000000  62 61 7a 65 6c 28 77 6f  72 6b 29 00 2d 58 58 3a  |bazel(work).-XX:|
00000010  2b 48 65 61 70 44 75 6d  70 4f 6e 4f 75 74 4f 66  |+HeapDumpOnOutOf|
00000020  4d 65 6d 6f 72 79 45 72  72 6f 72 00 2d 58 58 3a  |MemoryError.-XX:|
(...)
```

On Linux:
```
  $ hd /tmp/tmp1/02b3cf8f4df57525f8ffcd79c2928896/server/cmdline  | head -n10
00000000  62 61 7a 65 6c 28 67 69  74 72 6f 6f 74 29 00 2d  |bazel(gitroot).-|
00000010  58 58 3a 2b 48 65 61 70  44 75 6d 70 4f 6e 4f 75  |XX:+HeapDumpOnOu|
00000020  74 4f 66 4d 65 6d 6f 72  79 45 72 72 6f 72 00 2d  |tOfMemoryError.-|
(...)
```

**Comment by laszlocsomor** [comment]
@vladmos : Sorry to pick you, could you take a look when you have some time?

**Comment by aiuto** [comment]
I am not seeing the repeated -Djava.library.path. But it is still nulls rather than spaces.
But, in nearly 2 years, no one has re-raised this as an issue. Lowering priority.
