### ISSUE TITLE
Bazel doesn't find cl when using Visual C++ 2015 Build Tools

### ISSUE THREAD

**Issue by haferburg** [bazelbuild/bazel#3113]
Running `bazel-msvc-0.5.0-windows-msvc-x86_64.exe` on Windows 7.

I saw in #2448 that I can use the Visual C++ 2015 Build Tools from http://landinghub.visualstudio.com/visual-cpp-build-tools. I installed them, and now I have the environment variable
```
VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\Common7\Tools\
```
set. With
```
set bazel_vs=C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0
```
Bazel says:
```
ERROR: G:/src/test_projects/bazel_tutorial/lib/BUILD:1:1: C++ compilation of rule '//lib:hello-greet' failed: msvc_cl.bat failed: error executing command
...
'cl' is not recognized as an internal or external command, operable program or batch file.
Target //main:hello-world failed to build
```

**Comment by laszlocsomor** [comment]
Weird, that should work too.
Shot in the dark: maybe you have to set "BAZEL_VS" (uppercase)?

**Comment by haferburg** [comment]
Thing is, it does find something. At first, I thought that the path was wrong. So I tried something else like `C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\VC` (I think), but then bazel said that it couldn't find the `vcvars.bat` file.

**Comment by meteorcloudy** [comment]
@haferburg Usually, the BAZEL_VS path should be `C:\Program Files (x86)\Microsoft Visual Studio 14.0`, do you have this folder on your system?

**Comment by haferburg** [comment]
@meteorcloudy I do, but it doesn't contain anything useful:

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0>dir /b /s
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7
C:\Program Files (x86)\Microsoft Visual Studio 14.0\SDK
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\1033
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\Rules2BuildRules.xslt
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\Rules2Props.xslt
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\Rules2Targets.xslt
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\1033\errlookui.dll
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\1033\guidgenui.dll
C:\Program Files (x86)\Microsoft Visual Studio 14.0\SDK\Bootstrapper
C:\Program Files (x86)\Microsoft Visual Studio 14.0\SDK\Bootstrapper\Packages
C:\Program Files (x86)\Microsoft Visual Studio 14.0\SDK\Bootstrapper\Packages\SqlClrTypes_x64
C:\Program Files (x86)\Microsoft Visual Studio 14.0\SDK\Bootstrapper\Packages\SqlClrTypes_x86
C:\Program Files (x86)\Microsoft Visual Studio 14.0\SDK\Bootstrapper\Packages\SqlClrTypes_x64\de
C:\Program Files (x86)\Microsoft Visual Studio 14.0\SDK\Bootstrapper\Packages\SqlClrTypes_x64\en
C:\Program Files (x86)\Microsoft Visual Studio 14.0\SDK\Bootstrapper\Packages\SqlClrTypes_x64\es
...
```

To me it looks like the Visual C++ 2015 Build Tools were installed here:

```
C:\Program Files (x86)\Microsoft Visual C++ Build Tools>dir /b
vcbuildtools.bat
vcbuildtools_msbuild.bat
Visual C++ 2015 MSBuild Command Prompt.lnk
Visual C++ 2015 x64 arm cross Build Tools Command Prompt.lnk
Visual C++ 2015 x64 Native Build Tools Command Prompt.lnk
Visual C++ 2015 x64 x86  cross Build Tools Command Prompt.lnk
Visual C++ 2015 x86 arm cross Build Tools Command Prompt.lnk
Visual C++ 2015 x86 Native Build Tools Command Prompt.lnk
Visual C++ 2015 x86 x64 Cross Build Tools Command Prompt.lnk
```

```
G:\build\bazeltest>"C:\Program Files (x86)\Microsoft Visual C++ Build Tools\vcbuildtools.bat" x64

C:\Program Files (x86)\Microsoft Visual C++ Build Tools>where cl
C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\VC\bin\amd64\cl.exe

C:\Program Files (x86)\Microsoft Visual C++ Build Tools>where msbuild
C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe
```

**Comment by meteorcloudy** [comment]
Hmm,, I've never seen this kind of layout before. Can you show me what's under `C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\VC`. 

Did you install VC++ by default? I just installed [Visual C++ Build Tools 2015](http://go.microsoft.com/fwlink/?LinkId=691126&__hstc=268264337.c73c4f1e8c45b505253c80abd4ee345d.1485769751065.1496752451504.1496755768047.8&__hssc=268264337.1.1496755768047&__hsfp=2780251651&fixForIE=.exe) and the layout is like:
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0>dir /b
Common7
SDK
Team Tools
VC

C:\Program Files (x86)\Microsoft Visual Studio 14.0>dir VC /b
atlmfc
bin
crt
include
lib
redist
vcvarsall.bat

C:\Program Files (x86)\Microsoft Visual Studio 14.0>.\VC\vcvarsall.bat amd64

C:\Program Files (x86)\Microsoft Visual Studio 14.0>where cl.exe
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe
```

Bazel needs to find `vcvarsall.bat` to setup all the environment for MSVC compiler, can you find where it is?

**Comment by haferburg** [comment]
I do have that layout, but at `C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0`. I just tried running `vcvarsall.bat`, and it failed. I'll reinstall and report back.

Are you sure you don't have a regular Visual Studio 2015 installed?

**Comment by haferburg** [comment]
To me it looks like even Microsoft doesn't know where they install their tools.

I uninstalled the Visual C++ Build Tools 2015, restarted, reinstalled with default options, restarted. Still the same. At `C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\VC` there is a `vcvarsall.bat`. When I run it it always fails. So I took a look:

```
if exist "%~dp0..\common7\IDE\devenv.exe" goto setup_VS
if not exist "%~dp0..\common7\IDE\wdexpress.exe" goto setup_buildsku
```

Now, I have neither the `devenv.exe` nor the `wdexpress.exe`. Maybe you could check if your uninstall really removed that file. Maybe you have wdexpress? Anyways, the next part is interesting:

```
if not exist "%~dp0..\..\Microsoft Visual C++ Build Tools\vcbuildtools.bat" goto usage
set CurrentDir=%CD%
call "%~dp0..\..\Microsoft Visual C++ Build Tools\vcbuildtools.bat" %1 %2
cd /d %CurrentDir%
goto :eof
```

The script is in `C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\VC`, so the path evaluates to `C:\Program Files (x86)\Microsoft Visual Studio\Shared\Microsoft Visual C++ Build Tools\vcbuildtools.bat`, which is bogus. It should be `C:\Program Files (x86)\Microsoft Visual C++ Build Tools\vcbuildtools.bat`, at least that's where this file is on my machine.

Not sure what to make of it.

**Comment by meteorcloudy** [comment]
In https://github.com/bazelbuild/bazel/commit/cec624e756d0090cda440937dd00da542d3932bd, I changed the MSVC detection logic, can you try [this binary](http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/1591/JAVA_VERSION=1.8,PLATFORM_NAME=windows-msvc-x86_64/artifact/output/ci/bazel-msvc-.exe) built by our ci?  See http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/1591/JAVA_VERSION=1.8,PLATFORM_NAME=windows-msvc-x86_64/

**Comment by guruprasaad123** [comment]
bro , this link is expired can you update the link?

**Comment by meteorcloudy** [comment]
@guruprasaad123 Can you try the latest release version Bazel?
https://github.com/bazelbuild/bazel/releases/download/0.5.3/bazel-0.5.3-windows-x86_64.exe
