### ISSUE TITLE
First build fails due to missing inputs created by repository_rule

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#3114]
The first build fails, but immediately building again succeeds.
The setup is unusual: npm installation creates a directory in the user's project, which we want to use as inputs to later actions.

Repro:

`WORKSPACE`
```python
workspace(name = "repro")
load("//:defs.bzl", "repo")
repo(file_in_project = "//:BUILD")
```

`defs.bzl`
```python
def _repo_rule_impl(ctx):
  # Grab a reference to the root of the users project
  project_dir = ctx.path(ctx.attr.file_in_project).dirname
  # Emulate installing npm dependencies there
  ctx.file("install.sh", """#!/bin/bash
  cd $(dirname $1)
  mkdir node_modules
  echo "hello" > node_modules/some-file.txt
  ls -R
  """)
  result = ctx.execute(["./install.sh", ctx.path(ctx.attr.file_in_project)])
  print(result.stdout)
  if result.return_code > 0:
    print(result.stderr)
  # Create a symlink so external repo can reference the installed node packages
  ctx.symlink(project_dir, "installed")

_repo_rule = repository_rule(_repo_rule_impl,
  attrs = {"file_in_project": attr.label()})

def repo(file_in_project):
  _repo_rule(name = "foo", file_in_project=file_in_project)
```

`BUILD`
```python
filegroup(
    name = "generated",
    srcs=glob(["node_modules/**"]),
    visibility=["//visibility:public"]
)

genrule(
  name = "test",
  outs = ["out"],
  cmd = "echo works > $@",
  # This points through the symlink to the filegroup above
  srcs = ["@foo//installed:generated"]
)
```

On the initial build (or after `rm -rf node_modules/; bazel clean --expunge`) the build fails. Note that the `node_modules` directory doesn't exist in the project at the start of the build, but does exist before the actions execute:

```shell
$ bazel build :test
...........
WARNING: /home/alexeagle/repro6/defs.bzl:13:3: .:
BUILD
defs.bzl
node_modules
WORKSPACE

./node_modules:
some-file.txt
.
INFO: Found 1 target...
ERROR: missing input file '@foo//installed:node_modules/some-file.txt'.
ERROR: /home/alexeagle/repro6/BUILD:2:1: //:test: missing input file '@foo//installed:node_modules/some-file.txt'.
Target //:test failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/alexeagle/repro6/BUILD:2:1 1 input file(s) do not exist.
INFO: Elapsed time: 2.505s, Critical Path: 0.01s
```

Now the `node_modules` directory exists before the build starts, and simply building again succeeds:

```
$ bazel build :test
WARNING: /home/alexeagle/repro6/defs.bzl:12:3: .:
BUILD
defs.bzl
node_modules
WORKSPACE

./node_modules:
some-file.txt
.
INFO: Found 1 target...
Target //:test up-to-date:
  bazel-genfiles/out
INFO: Elapsed time: 0.213s, Critical Path: 0.00s
```

**Comment by katre** [comment]
Bazel shouldn't be changing the actual project directory. If npm needs to download something, it should download that into a directory defined by the repository rule, and further dependencies can refer to that directory.

**Comment by alexeagle** [comment]
@katre The reasoning here is that in the Node ecosystem, the user needs to download packages to a folder in their project. The bazel rules could download another copy of these files into the /external directory, but then there is the risk that the two are not in sync, so then a bazel build gives different results than running eg. a compiler directly in the project dir.

**Comment by alexeagle** [comment]
It also means downloading all the packages again, which can take minutes. Bazel would be the only tooling that has such a penalty, in a project where the packages were already installed in the standard `node_modules` location.

**Comment by katre** [comment]
A GitHub issue isn't really the best forum for discussing this. I'd recommend sending an email to the https://groups.google.com/forum/#!forum/bazel-discuss mailing list to discuss your design.

In general, Bazel's principle is to not modify the code at all, but instead download to the working directory and then do builds from there. If Bazel (and your node rules) are managing the node packaging, does the user need a copy of the packages in their source code?

**Comment by alexeagle** [comment]
Discussed with my teammate @evmar and with @mattmoor - here's my plan:

- We think it's paramount that we don't install dependencies twice, and that there is no version skew between the `node_modules` directory the user uses (eg. for tools like a linter) and the one bazel uses for builds. So we'll continue to have the symlink from `$(bazel info output_base)/external/npm/installed` back to your project dir.
- It's surprising that a build tool installs dependencies. So I'll change the behavior to instead verify the `node_modules` directory is in sync with some lock file the user supplies (`yarn.lock` or `npm_shrinkwrap.json`)
- If that check fails, it could be because the user has a locally installed `yarn` or `npm` that isn't the right version. so the error message can direct them to run our version, eg. `bazel run @yarn_pkg//:bin/yarn`

It's still annoying because before you run the first bazel build, the repository_rule hasn't been run so there is no `yarn` executable for you. You might go download and install one, just for us to tell you it's the wrong one. But developer documentation can suggest running `bazel run @yarn...` instead of `yarn install`.

**Comment by alexeagle** [comment]
FYI angular/typescript rules have worked around this by requiring that the directory with the filegroup is populated before the initial build.

**Comment by archanaara** [comment]
Hi I am facing the following issue. can someone please help

ERROR: missing input file '@nlohmann_json_lib//:license.txt'

ERROR: missing input file '@nlohmann_json_lib//:license.txt'
ERROR: C:/users/archana/documents/tensorflow/tensorflow/tools/pip_package/BUILD:216:1: //tensorflow/tools/pip_package:build_pip_package: missing input file '@nlohmann_json_lib//:license.txt'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: C:/users/archana/documents/tensorflow/tensorflow/tools/pip_package/BUILD:216:1 1 input file(s) do not exist
INFO: Elapsed time: 27.493s, Critical Path: 2.73s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

C:\Users\Archana\Documents\tensorflow>

**Comment by archanaara** [comment]
Anyone know about @nlohmann_json_lib//:license.txt' I am not finding any results for that. Please help

**Comment by janakdr** [comment]
@archanaara your issue looks unrelated. Please open a new issue if you need it. The npm issue has been fixed by extending Bazel, I think.
