### ISSUE TITLE
bazel's dependency suggestion is wrong with proto_library.

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#3117]
I wrongly added a `proto_library` dependency, while I really should have added a `java_proto_library` dependency to a `java_test_library`. Bazel then suggests that I should depend on that `proto_library` that I am already depending on (`:build_data_proto`), while it should really suggest to depend on (`build_data_java_proto`).

```
src/tools/benchmark/javatests/com/google/devtools/build/benchmark/BazelBuilderTest.java:44: error: [strict] Using type com.google.devtools.build.benchmark.BuildTargetConfig from an indirect dependency (TOOL_INFO: "//src/tools/benchmark/java/com/google/devtools/build/benchmark:build_data_proto wrapped in java_proto_library"). See command below **
    BuildTargetConfig targetConfig = BuildTargetConfig.newBuilder().setBuildTarget("foo").build();
    ^
** Please add the following dependencies:
  //src/tools/benchmark/java/com/google/devtools/build/benchmark:build_data_proto  to //src/tools/benchmark/javatests/com/google/devtools/build/benchmark:BazelBuilderTest
```

cc: @cgrushko

**Comment by cgrushko** [comment]
There's a similar bug internally, but my explanation there doesn't fit here.
How come you already depend on :build_data_proto?
How do I repro this?

**Comment by buchgr** [comment]
@cgrushko 

> How come you already depend on :build_data_proto?

I wrongly depended on this.

> How do I repro this?

Create a `proto_library` and a `java_proto_library`. Create a `java_test_library` target and have it (wrongly) depend on the `proto_library` target instead of the `java_proto_library` target.

**Comment by aiuto** [comment]
Closing for staleness.  All proto rules were updated and moved around in the last year.
