### ISSUE TITLE
False positive results with remote_executor and java_test

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/bazel#3121]
### Description of the problem / feature request / question:
I am running java_test (junit) using locally started remote executor and I get that the test has passed way too soon. I noticed that even with a simplest junit test that just throws exception I get that the test has passed.

### STRP
1. with latest bazel
2. clone this repo: https://github.com/or-shachar/bazel-sample-repo
3. run the test locally to notice that it fails:
```
$ bazel test //src/main/java/com/example/...
```
4. start remote worker
```sh
$ cd ${bazel_git_repo}
$ bazel build //src/tools/remote_worker
$ bazel-bin/src/tools/remote_worker/remote_worker \
      --work_path=/tmp/test \
      --listen_port=3030
```
5. change one character in `/src/main/java/com/example/MyTest.java` to avoid using cache.
6. Run the test with the remote worker:
```sh
$ cd ${bazel-sample-repo}
$ bazel --host_jvm_args=-Dbazel.DigestFunction=SHA1 test \
      --spawn_strategy=remote \
      --remote_executor=localhost:3030 \
      --remote_cache=localhost:3030 \
      --strategy=Javac=remote \
      --remote_local_fallback=false \
      --remote_timeout=600 \
      //src/main/java/com/example/...
```
7. notice how the test suddenly PASS.

### Environment info
* Operating System: **mac os x sierra**
* Bazel version: **development version** (`956810b6ee24289e457a4b8d0a84ff56eb32c264`)

###  Have you found anything relevant by searching the web?
There seems to be some changes in the remote executor area. issue #2887 and fixed in here -
 https://github.com/bazelbuild/bazel/commit/8c67e3e50f58780ed261289b1418e734a20bbb5a  by @ulfjack

**Comment by ulfjack** [comment]
I can reproduce the problem.

**Comment by ulfjack** [comment]
I think I broke this in 7f6e27f1354db41fbf986fd2e3abcb770988323e, and we didn't have tests for the failure case.
