### ISSUE TITLE
Genrule sandbox behaves strangely

### ISSUE THREAD

**Issue by MarkusTeufelberger** [bazelbuild/bazel#3128]
### Description of the problem:
When running a certain BUILD file containing a genrule (to handle autoconf header generation) against a locally checked out repository, it builds fine, when using the same BUILD file in a new_http_archive rule later, it seems to have issues with sandboxing and paths.

### If possible, provide a minimal example to reproduce the problem:

While getting everything to build, I used the following BUILD file:
````
$ git clone https://github.com/google/snappy/
$ cd snappy
$ git checkout 1.1.4
# copy in BUILD file
$ cat BUILD
genrule(
    name = "generated_headers",
    srcs = glob([
        "autogen.sh",
        "configure.ac",
        "Makefile.am",
        "AUTHORS",
        "ChangeLog",
        "COPYING",
        "NEWS",
        "README",
        "m4/*",
        "*.in",
    ]),
    outs = [
        "config.h",
        "snappy-stubs-public.h",
    ],
    cmd = "./autogen.sh && ./configure && mv config.h $(location config.h) && mv snappy-stubs-public.h $(location snappy-stubs-public.h)",
)

cc_library(
    name = "snappy",
    srcs = glob(
        ["*.cc"],
        exclude = [
            "snappy-test.cc",
            "snappy_unittest.cc",
        ],
    ),
    hdrs = [":generated_headers"] + glob(["*.h"]),
)
# empty WORKSPACE
$ cat WORKSPACE
$ bazel build ...
# Everything builds fine
````
Now with new_http_repository and a dummy rule (to get bazel to build the output):
````
$ cat snappy.1.1.4.BUILD
genrule(
    name = "generated_headers",
    srcs = glob([
        "autogen.sh",
        "configure.ac",
        "Makefile.am",
        "AUTHORS",
        "ChangeLog",
        "COPYING",
        "NEWS",
        "README",
        "m4/*",
        "*.in",
    ]),
    outs = [
        "config.h",
        "snappy-stubs-public.h",
    ],
    cmd = "./autogen.sh && ./configure && mv config.h $(location config.h) && mv snappy-stubs-public.h $(location snappy-stubs-public.h)",
)

cc_library(
    name = "snappy",
    srcs = glob(
        ["*.cc"],
        exclude = [
            "snappy-test.cc",
            "snappy_unittest.cc",
        ],
    ),
    hdrs = [":generated_headers"] + glob(["*.h"]),
)
$ cat WORKSPACE
new_http_archive(
    name = "snappy_1_1_4",
    build_file = "snappy.1.1.4.BUILD",
    sha256 = "9ff0ca3e1417135bde5add9a60b6a98a7ed0aabea255c426d83423be522b358a",
    strip_prefix = "snappy-2d99bd14d471664758e4dfdf81b44f413a7353fd",
    url = "https://github.com/google/snappy/archive/2d99bd14d471664758e4dfdf81b44f413a7353fd.zip",
)
$ cat BUILD
# Dummy rule
filegroup(
    name = "dummy_rule",
    srcs = [
        "@snappy_1_1_4//:snappy",
    ],
)
$ bazel build ...
...........
INFO: Found 1 target...
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/adda498f781708cde2d8e46c475e9593/external/snappy_1_1_4/BUILD.bazel:2:1: Executing genrule @snappy_1_1_4//:generated_headers failed: Process exited with status 1 [sandboxed].
/bin/bash: ./autogen.sh: No such file or directory
Use --strategy=Genrule=standalone to disable sandboxing for the failing actions.
Target //:dummy_rule failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.909s, Critical Path: 0.05s
````
Defining `$(location autogen.sh)` leads to:

````
INFO: Found 1 target...
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/adda498f781708cde2d8e46c475e9593/external/snappy_1_1_4/BUILD.bazel:2:1: Executing genrule @snappy_1_1_4//:generated_headers failed: Process exited with status 1 [sandboxed].
aclocal: error: 'configure.ac' is required
Use --strategy=Genrule=standalone to disable sandboxing for the failing actions.
Target //:dummy_rule failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.171s, Critical Path: 0.09s
````

I mean, I know that configure.ac is required, that's why it is explicitly listed in "srcs"!

### Environment info
* Operating System:
Ubuntu 16.04 in a (Vagrant) VM

* Bazel version (output of `bazel info release`):
release 0.5.0

###  Have you found anything relevant by searching the web?
I found a few issues here on github related to genrules and/or autotools, but I'm not 100% sure if what I'm doing is even wrong or not...

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

I am still confused why the genrule doesn't detect that the output files are already created in the very folder it is running and that they need to be moved to a different location via `mv`. It would be nice to be able to do something like `cd $(GENRULEWORKDIR)`, even better if it would actually already happen automatically. This seems to be the case in the initial example but not work at all in the WORKSPACE reference. My intuition about genrules was that all "srcs" files get copied to a sandbox folder, a shell is opened there and after the script ran, Bazel checks if the "outs" files are present to move them to their cache location. Apparently this is wrong. :-(

**Comment by MarkusTeufelberger** [comment]
Oh, any I also took a look at https://raw.githubusercontent.com/nikhedonia/snappy/f63f34aedc9d490db4f1d6927614873c7e849231/BUCK (the buck version for this repo), however I also find it weird that there is a lot of copying files... they at least seem to have a $SRCDIR variable, but apparently chose to return a folder, not a list of files from their genrule.

**Comment by MarkusTeufelberger** [comment]
After lots of trial and error, the following cmd seems to work:
````
cmd = "pushd $$(dirname $(location autogen.sh)) && \
    ./autogen.sh &&\
    ./configure &&\
    popd &&\
    mv $$(dirname $(location autogen.sh))/config.h $(location config.h) && \
    mv $$(dirname $(location autogen.sh))/snappy-stubs-public.h $(location snappy-stubs-public.h)",
````

The issue seems to be that autogen.sh will only work if the work directory is in the same directory as the script itself, but there is no way that I could find to get the current directory of a sandbox (other than the awkward "dirname" workaround.

**Comment by ramtej** [comment]
Similar issue here, just with a Java (.jar) file:
 
genrule(
    name = "build",
    srcs = [],
    # cmd = "java -jar $(location @gradle_distribution//:lib/gradle-launcher-3.2.1.jar) build > $@",
    # cmd = "pwd",
    cmd = "java -jar $(location @gradle_distribution//:lib/gradle-launcher-3.2.1.jar) --project-dir " + PROJECT_DIR +
          " build > $@",
    outs = ["jar-output"],
    tools = ["@gradle_distribution//:lib/gradle-launcher-3.2.1.jar"],
    local = 1,  # run with the standalone strategy
)

Error: 

What went wrong:
A problem occurred configuring root project 'simple'.
> java.io.FileNotFoundException: /home/jj/.cache/bazel/_bazel_jj/**9f49585d627dc8c3ff9af18b5a8da101**/external/gradle_distribution/lib/plugins/gradle-diagnostics-3.2.1.jar (No such file or directory)

$ find $HOME/.cache/bazel/ | grep gradle-diagnostics-3.2.1.jar

$HOME/.cache/bazel/_bazel_jj/**c78dceb1c373becb1e6f3c4084ea0b55**/external/gradle_distribution/lib/plugins/gradle-diagnostics-3.2.1.jar

**Comment by philwo** [comment]
@Nickersoft Sorry, no idea. :( I don't think there's any better way than the above mentioned workaround.

**Comment by MarkusTeufelberger** [comment]
The ones in the original report - the same command behaves differently in a BUILD file invoked from `new_http_archive` vs. a local BUILD file.
