### ISSUE TITLE
Could not write domain /env.plist; exiting

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/bazel#313]
Noob trouble: I'm trying to build the PrenotCalculator, but the build fails.
I must be missing something iOS-specific on my MacBook, but it would be nice to get a readable error.

    $ ~/bazel/output/bazel build --verbose_failures examples/objc:PrenotCalculator
    INFO: Found 1 target...
    INFO: From EnvironmentPlist examples/objc/plists/PrenotCalculator-environment.plist:
    2015-07-20 12:48:07.538 defaults[86340:1045226] Could not write domain /env.plist; exiting
    ERROR: /Users/carmi/bazel/examples/objc/BUILD:15:1: error executing shell command: 'PLATFORM_PLIST=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Info.plist && PLIST=${TMPDIR}/env.plist && os_build=$(/usr/bin/defaults read ${PLATFORM_PLIST} BuildMach...' failed: bash failed: error executing command
      (cd /private/var/tmp/_bazel_carmi/ae9e85330f48c811168cd2c82a8cab2f/bazel && \
      exec env - \
      /bin/bash -c 'PLATFORM_PLIST=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Info.plist && PLIST=${TMPDIR}/env.plist && os_build=$(/usr/bin/defaults read ${PLATFORM_PLIST} BuildMachineOSBuild) && compiler=$(/usr/bin/defaults read ${PLATFORM_PLIST} DTCompiler) && platform_version=$(/usr/bin/defaults read ${PLATFORM_PLIST} Version) && sdk_build=$(/usr/bin/defaults read ${PLATFORM_PLIST} DTSDKBuild) && platform_build=$(/usr/bin/defaults read ${PLATFORM_PLIST} DTPlatformBuild) && xcode_build=$(/usr/bin/defaults read ${PLATFORM_PLIST} DTXcodeBuild) && xcode_version=$(/usr/bin/defaults read ${PLATFORM_PLIST} DTXcode) && /usr/bin/defaults write ${PLIST} DTPlatformBuild -string ${platform_build} && /usr/bin/defaults write ${PLIST} DTSDKBuild -string ${sdk_build} && /usr/bin/defaults write ${PLIST} DTPlatformVersion -string ${platform_version} && /usr/bin/defaults write ${PLIST} DTXcode -string ${xcode_version} && /usr/bin/defaults write ${PLIST} DTXCodeBuild -string ${xcode_build} && /usr/bin/defaults write ${PLIST} DTCompiler -string ${compiler} && /usr/bin/defaults write ${PLIST} BuildMachineOSBuild -string ${os_build} && cat ${PLIST} > bazel-out/local_darwin-fastbuild/bin/examples/objc/plists/PrenotCalculator-environment.plist'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: bash failed: error executing command
      (cd /private/var/tmp/_bazel_carmi/ae9e85330f48c811168cd2c82a8cab2f/bazel && \
      exec env - \
      /bin/bash -c 'PLATFORM_PLIST=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Info.plist && PLIST=${TMPDIR}/env.plist && os_build=$(/usr/bin/defaults read ${PLATFORM_PLIST} BuildMachineOSBuild) && compiler=$(/usr/bin/defaults read ${PLATFORM_PLIST} DTCompiler) && platform_version=$(/usr/bin/defaults read ${PLATFORM_PLIST} Version) && sdk_build=$(/usr/bin/defaults read ${PLATFORM_PLIST} DTSDKBuild) && platform_build=$(/usr/bin/defaults read ${PLATFORM_PLIST} DTPlatformBuild) && xcode_build=$(/usr/bin/defaults read ${PLATFORM_PLIST} DTXcodeBuild) && xcode_version=$(/usr/bin/defaults read ${PLATFORM_PLIST} DTXcode) && /usr/bin/defaults write ${PLIST} DTPlatformBuild -string ${platform_build} && /usr/bin/defaults write ${PLIST} DTSDKBuild -string ${sdk_build} && /usr/bin/defaults write ${PLIST} DTPlatformVersion -string ${platform_version} && /usr/bin/defaults write ${PLIST} DTXcode -string ${xcode_version} && /usr/bin/defaults write ${PLIST} DTXCodeBuild -string ${xcode_build} && /usr/bin/defaults write ${PLIST} DTCompiler -string ${compiler} && /usr/bin/defaults write ${PLIST} BuildMachineOSBuild -string ${os_build} && cat ${PLIST} > bazel-out/local_darwin-fastbuild/bin/examples/objc/plists/PrenotCalculator-environment.plist'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
    Target //examples/objc:PrenotCalculator failed to build
    INFO: Elapsed time: 1.113s, Critical Path: 0.90s

**Comment by dmaclach** [comment]
We've got a fix for this ready, and it should be rolling out soon.

Cheers,
Dave

**Comment by c-parsons** [comment]
I belieeve this issue is obsolete and was never closed.
