### ISSUE TITLE
Docs describe nonexistent --local_genrule_timeout_seconds option

### ISSUE THREAD

**Issue by mmorearty** [bazelbuild/bazel#3131]
### Description of the problem / feature request / question:

https://bazel.build/versions/master/docs/bazel-user-manual.html describes an option called `--local_genrule_timeout_seconds`, but I can't find any such option, or anything similar. Should this be removed from the docs?

**Comment by katre** [comment]
You're right, that's a holdover from the internal docs, and should be removed. Would you like to send a patch to remove it?
