### ISSUE TITLE
Add documentation for Buildifier Tool

### ISSUE THREAD

**Issue by axgillies** [bazelbuild/bazel#3135]
Some sort of documentation coverage for the Buildifier tool might be good in the Bazel documentation. It's mentioned here or there, but does not seem to have an easily findable location in the docs.

**Comment by katre** [comment]
Buildifier is located in this repository: https://github.com/bazelbuild/buildtools
Are the docs you are looking for there?

**Comment by axgillies** [comment]
This looks like a good start to me. It would be great if there was a
findable place in the docs that referred to the tool and pointed to the
repo location.

**Comment by laurentlb** [comment]
Obsolete. Buildifier is now mentioned.
