### ISSUE TITLE
generate_workspace does not support maven dependencies with version ranges

### ISSUE THREAD

**Issue by petroseskinder** [bazelbuild/bazel#3136]
### Description of the problem:

The generate_workspace tool is unable to handle maven coordinates with dependencies on a range of versions. Instead, it requires that all dependencies (explicit and transitive) are anchored to a specific version. Dart's package manager's [docs](https://www.dartlang.org/tools/pub/versioning#version-constraints) provide reasonable justification why version ranges are useful. 

### Minimal example

```bash
bazel run //src/tools/generate_workspace -- --artifact=com.github.stefanbirkner:system-rules:1.4.0
```
According to maven central, this specific artifact depends on two artifacts. Both artifacts' versions are specified by a range of valid versions rather than as a specific version. This is a feature supported by [Maven](https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN402)
```xml
<dependencies>
     <dependency>
          <groupId>junit</groupId>
          <artifactId>junit-dep</artifactId>
          <version>[4.9,)</version> 
          <scope>compile</scope>
     </dependency>
     <dependency>
          <groupId>commons-io</groupId>
          <artifactId>commons-io</artifactId>
          <version>[2,3)</version>
          <scope>compile</scope>
     </dependency>
</dependencies>

```
Bazel outputs
```
ERROR: Could not resolve dependency junit:junit-dep:[4.9,): Could not find any repositories that knew how to resolve junit:junit-dep:[4.9,) (checked https://oss.sonatype.org/content/repositories/snapshots, https://repo1.maven.org/maven2/)

ERROR: Could not resolve dependency commons-io:commons-io:[2.0,): Could not find any repositories that knew how to resolve commons-io:commons-io:[2.0,) (checked https://oss.sonatype.org/content/repositories/snapshots, https://repo1.maven.org/maven2/)
```

### Environment info
* Bazel version (output of `bazel info release`):
   * release 0.4.5-homebrew
   * development version: commit no 037b9b93f33deaf8f33db2197b93a3e784c72fac

###  Have you found anything relevant by searching the web?

Reading through the source code for DefaultModelResolver, it seems that the dependency on commons-io:commons-io artifact versions [2,3) is being directly translated to `commons-io:commons-io:[2,3)` Then it's querying for a pom file versioned [2,3), which obviously won't exist.

Here is the relevant [code block](https://github.com/bazelbuild/bazel/blob/master/src/tools/generate_workspace/src/main/java/com/google/devtools/build/workspace/maven/DefaultModelResolver.java#L112)
```java
@Override
public ModelSource resolveModel(String groupId, String artifactId, String version)
      throws UnresolvableModelException {
    String ruleName = Rule.name(groupId, artifactId);
    ...    
    for (Repository repository : repositories) {
      UrlModelSource modelSource = getModelSource(
          repository.getUrl(), groupId, artifactId, version);
      if (modelSource != null) {
        return modelSource;
      }
      // COMMENT: getModelSource will always throw null for the above example.
    }
    ...
}

private UrlModelSource getModelSource(
      String url, String groupId, String artifactId, String version)
      throws UnresolvableModelException {
    try {
      if (!url.endsWith("/")) {
        url += "/";
      }
      // COMMENT: One simple change could be to add a check here if the version is a range.
      URL urlUrl = new URL(url
          + groupId.replaceAll("\\.", "/") + "/" + artifactId + "/" + version + "/" + artifactId
          + "-" + version + ".pom");
      if (pomFileExists(urlUrl)) {
        ... 
      }
    } catch (MalformedURLException e) {
      throw new UnresolvableModelException("Bad URL " + url + ": " + e.getMessage(), groupId,
          artifactId, version, e);
    }
    return null;
  }
```

To support versioning constraints, generate_workspace could either use a simple heuristic of some kind or it could implement a SAT solver.

Based off of related issues, I presume @kchodorow and @ahumesky would know how best to handle this.

**Comment by petroseskinder** [comment]
Maven does not seem to handle version ranges particularly well either. [This jira](https://issues.apache.org/jira/browse/MNG-3092) has been open for roughly 10 years now.

**Comment by talios** [comment]
@petroseskinder we've gone so far as to write our own external aether based range-resolver tool, with much greater control over ranges/dependencies ( [] ranges, global transitive exclusions etc ). Builds can be a pain at times, but SO much more stable and reproducible now. Hopefully I can open source it, I did have an experimental WORKSPACE file generator but hit snags. Can a WORKSPACE include/load another WORKSPACE file?

**Comment by petroseskinder** [comment]
> Can a WORKSPACE include/load another WORKSPACE file?

I believe no. There are [design documents](https://bazel.build/designs/2016/09/19/recursive-ws-parsing.html) for allowing multiple WORKSPACE files in a project space. 

An alternative approach would be to have your WORKSPACE file load a bzl file. Here is a [relevant example](https://github.com/johnynek/bazel-deps). Take a look at `3rdparty/workspace.bzl` and `3rdparty/load.bzl`

That said, it would be great if you open source it. Currently development of `generate_workspace` has been externalized to [migration_tooling](https://github.com/bazelbuild/migration-tooling).

What other snags did you face with the WORKSPACE file generator?

**Comment by kchodorow** [comment]
I actually just added support yesterday for generate_workspace to create generate_workspace.bzl instead of WORKSPACE and BUILD (there's still a command line option if you want the old behavior).  Then, as @petroseskinder mentions, you can load that generate_workspace.bzl from you WS file.  See the README at github.com/bazelbuild/migration-tooling for details.

**Comment by jin** [comment]
Closing this as generate_workspace is no longer maintained. Please open Maven-related issues on [rules_jvm_external](https://github.com/bazelbuild/rules_jvm_external) instead.

rules_jvm_external uses Coursier as its resolver, which works well with version ranges.
