### ISSUE TITLE
Feature request: access Bazel version in Skylark

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel#3138]
It would be useful for Bazel extensions written in Skylark to be able to determine the current version of Bazel. The version could be accessed through a global function or variable, similar to `REPOSITORY_NAME` and `PACKAGE_NAME`.

This would help Skylark extensions determine what Bazel features are available. Rules could degrade gracefully or provide meaningful error messages when a feature is not available.

A few upcoming and recently added features where this could be used.

* Upcoming support for platforms and toolchains.
* Named providers
* `environ` in `repository_rule`.

**Comment by benjaminp** [comment]
This doesn't seem to be documented, but repository rules can use `native.bazel_version`.
