### ISSUE TITLE
Windows CI tests are passing but Jenkins still sets the test as unstable

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#3139]
Two recent cases, one MSVC, one MSYS:

http://ci.bazel.io/view/Dashboard/job/bazel-tests/805/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-msvc-x86_64/console
http://ci.bazel.io/view/Dashboard/job/bazel-tests/805/BAZEL_VERSION=latest,PLATFORM_NAME=windows-x86_64/console

Sample from logs:
```
Executed 1 out of 1 test: 1 test passes.

c:\jenkins\workspace\bazel-tests\BAZEL_VERSION\latest\PLATFORM_NAME\windows-x86_64>set retCode=0 

c:\jenkins\workspace\bazel-tests\BAZEL_VERSION\latest\PLATFORM_NAME\windows-x86_64>if 0 == 3 (
 
 echo 1  1>c:\jenkins\workspace\bazel-tests\BAZEL_VERSION\latest\PLATFORM_NAME\windows-x86_64\.unstable 
)  else (if not 0 == 0 (exit 0 ) ) 

...

[File exists] check if file exists [.unstable]
Run condition [File exists] enabling perform for step [Set the build result]
Setting result to [Unstable]
```

**Comment by meteorcloudy** [comment]
There is also a MSVC run there, which has the following failure:
```
//src/test/shell/bazel:bazel_bootstrap_distfile_test                     FAILED in 502.5s
  C:/bazel_ci/temp/_bazel_system/bop-op4a/execroot/windows-x86_64/bazel-out/msvc_x64-fastbuild/testlogs/src/test/shell/bazel/bazel_bootstrap_distfile_test/test.log
```

bazel_bootstrap_distfile_test is flaky on Windows, @laszlocsomor is working on a solution, see https://github.com/bazelbuild/bazel/issues/3129

**Comment by laszlocsomor** [comment]
The MSYS CI is now empty, and I fixed https://github.com/bazelbuild/bazel/issues/3129 and https://github.com/bazelbuild/bazel/issues/3618 (not yet pushed to GitHub), so I think this issue is obsolete.
