### ISSUE TITLE
Error messages when changing repository_rule arguments

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3143]
### Description of the problem / feature request / question:

In `WORKSPACE`, I changed:

    my_repo(
        name = "foo",
        build_files_path = __workspace_dir__ + "/third_party/abyss",

to 

    my_repo(
        name = "foo",
        build_files_path = select({
            "//conditions:default": __workspace_dir__ + "/third_party/abyss",
        }),

As a result, I then get the error:

    no such package '@foo//' <...> (Directory not empty) and referenced by <...>

Changing it back, it still remains broken.

### Environment info
* Operating System: Windows 10
* Bazel version (output of `bazel info release`): 0.5.1

###  Have you found anything relevant by searching the web?
Nope

**Comment by abergmeier-dsfishlabs** [comment]
BTW: I am pretty sure that repository invalidation does not currently work with 0.5.1 on Windows.

**Comment by laszlocsomor** [comment]
With Bazel 0.23.1, I get:

```
ERROR: no such package '@A//': select() cannot be used in WORKSPACE files
```
