### ISSUE TITLE
Bazel test cases time out on RHEL 7.3/x86.

### ISSUE THREAD

**Issue by sowani** [bazelbuild/bazel#3144]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

Bazel test cases (which are part of the source cloned from github) are timing out on RHEL 7.3/x86.

### If possible, provide a minimal example to reproduce the problem:

bazel test //src/test/shell/bazel:bazel_coverage_test

### Environment info
* Operating System:
RHEL 7.3 running on x86

[pts00449-vm15 bazel]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"

* Bazel version (output of `bazel info release`):

release 0.4.5-2017-05-23 (@69d2ea2)

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

N/A

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).
Log file created using strace attached. Command used:

strace output/bazel test --discard_analysis_cache --nocache_test_results --java_debug --show_loading_progress --show_package_location --subcommands --show_task_finish --show_timestamps --test_verbose_timeout_warnings --verbose_explanations --verbose_failures --verbose_test_summary --logging 6 --strategy=TestRunner=standalone //src/test/shell/bazel:bazel_java_test
[log_rhel.txt](https://github.com/bazelbuild/bazel/files/1060438/log_rhel.txt)

**Comment by katre** [comment]
You're passing java_debug. Are you connecting a debugger? Why do you have all of these flags specified?

**Comment by sowani** [comment]
I am passing all these flags with a hope to get more debugable output from
bazel. I am not connecting any debugger.

**Comment by sowani** [comment]
The test cases time out even if I don't use any of these flags.

**Comment by katre** [comment]
If you don't connect a debugger and pass the --java_debug flag, bazel will hang waiting for the debugger to connect, to that makes sense.

Can you run the test without all of the flags, and include the command output that you do get?

**Comment by sowani** [comment]
@katre Thanks for clarification. I executed plain command (i.e. without any of those options). Here is the output I got in console. strace output of the same is attached.
[latest-log.txt](https://github.com/bazelbuild/bazel/files/1071266/latest-log.txt)

$ output/bazel test //src/test/shell/bazel:bazel_java_test
WARNING: /root/Atul/bazel/tools/build_defs/docker/docker.bzl:19:1: The docker_{build,bundle} rules bundled with Bazel are deprecated in favor of:
https://github.com/bazelbuild/rules_docker. Please change BUILD loads to reference: @io_bazel_rules_docker//docker:docker.bzl and add the following to your WORKSPACE:
git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    commit = "...",
)
load("@io_bazel_rules_docker//docker:docker.bzl", "docker_repositories")
docker_repositories().
INFO: Found 1 test target...
TIMEOUT: //src/test/shell/bazel:bazel_java_test (see /root/.cache/bazel/_bazel_root/8a5a0552338b407bf08ad70f788e12bf/execroot/bazel/bazel-out/local-fastbuild/testlogs/src/test/shell/bazel/bazel_java_test/test.log).
Target //src/test/shell/bazel:bazel_java_test up-to-date:
  bazel-bin/src/test/shell/bazel/bazel_java_test
INFO: Elapsed time: 906.211s, Critical Path: 905.75s
//src/test/shell/bazel:bazel_java_test                                  TIMEOUT in 905.7s
  /root/.cache/bazel/_bazel_root/8a5a0552338b407bf08ad70f788e12bf/execroot/bazel/bazel-out/local-fastbuild/testlogs/src/test/shell/bazel/bazel_java_test/test.log

Executed 1 out of 1 test: 1 fails locally.

**Comment by katre** [comment]
Did you examine the log file in the error message? /root/.cache/bazel/_bazel_root/8a5a0552338b407bf08ad70f788e12bf/execroot/bazel/bazel-out/local-fastbuild/testlogs/src/test/shell/bazel/bazel_java_test/test.log should have more details.

**Comment by sowani** [comment]
Here is the test log created by bazel_java_test under /root/.cache/.... - I renamed it from "test.log" to "test_log.txt" to get it uploaded here.  I couldn't find anything specific there, but may be I missed it altogether... 
[test_log.txt](https://github.com/bazelbuild/bazel/files/1073515/test_log.txt)

**Comment by katre** [comment]
You're right, there's not much information there. If you look at the code of the test (https://github.com/bazelbuild/bazel/blob/624c706e49076912350277db746f5d43c484e591/src/test/shell/bazel/bazel_java_test.sh), you'll see that this test just sets up various source code paths and then calls bazel and checks the output. You could try reproducing these manually to see if you can find the problem.

You might also try asking this question on StackOverflow, where we have a fairly active community. Someone there may also be using RHEL 7.3 and have some insight.

**Comment by sowani** [comment]
Sure, I will raise this question on StackOverflow. Thanks!

**Comment by mhlopko** [comment]
So I guess I can close this issue right?
