### ISSUE TITLE
Bazel should allow openjdk-9-jdk to be installed as long as Java 8 is the system default

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#3147]
Reported by @tbroyer:

> Last week, the oracle-java9-installer debian package from webupd8 was updated [1] and now provides openjdk-9-jdk (you can see it in the diff linked from [1]).
This conflicts with Bazel.
I understand that Bazel won't work with Java 9, but I also have Java 8 (both OpenJDK from Ubuntu, and Oracle JDK from webupd8) and Java 7, and Java 8 is my default JDK; so why would I be blocked from installing both Bazel and Oracle JDK 9 at the same time?
Could the "Conflicts: openjdk-9-jdk" be removed from the Debian package info? I feel like it's too strong just to make an "apt-get install bazel" not result in openjdk-9-jdk being automatically selected if no java8-sdk package is already installed [2,3].
> 
> [1] https://launchpad.net/~webupd8team/+archive/ubuntu/java/+sourcepub/7841749/+listing-archive-extra
> [2] https://github.com/bazelbuild/bazel/commit/fdb5a8c06985d78c55981a981a72bd4f0766ddb8
> [3] https://github.com/bazelbuild/bazel/issues/1456

**Comment by tbroyer** [comment]
Patch removing the "Conflicts:" line and updating the documentation to explicitly install JDK 8: https://bazel-review.googlesource.com/11991 (as I suggested in https://groups.google.com/d/topic/bazel-discuss/GNt7DRtBdPg/discussion)
