### ISSUE TITLE
single status line is quite busy/flickers when lots of things are going on

### ISSUE THREAD

**Issue by MarkusTeufelberger** [bazelbuild/bazel#3149]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the feature request:

While e.g. downloading a dozen dependency files, the single status line of bazel really isn't very informative at all.

### If possible, provide a minimal example to reproduce the problem:

https://github.com/MarkusTeufelberger/BBW

Run `python3 workspacegen.py snappy.yml sqlite.yml`, then run `vagrant up`, `vagrant ssh`, `cd /vagrant_data` and run `bazel build ...`

Some steps are quite spammy anyways, what I mean more specifically is the phase where dependencies are downloaded at the beginning. Also later it is not clear which tasks are currently running, since only one is displayed (but probably several tasks are running at the same time).

### Environment info
* Operating System:
Linux

* Bazel version (output of `bazel info release`):
````
$ bazel version
Build label: 0.5.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 6 10:34:11 2017 (1496745251)
Build timestamp: 1496745251
Build timestamp as int: 1496745251
````

###  Have you found anything relevant by searching the web?
Buck's status is so pretty ✨ , I'd love to see something similar in Bazel:
![Build status gif from buckbuild.com](https://buckbuild.com/static/buck-build-15fps.gif)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by aehlig** [comment]
Have you tried tihe "experimental UI"? I.e., if you add the following to your `.bazelrc`, are you still missing information, if so, which ones?

```
common --experimental_ui
common --experimental_ui_actions_shown 8
build --show_progress_rate_limit=0.25
build --experimental_skyframe_target_pattern_evaluator
```

**Comment by MarkusTeufelberger** [comment]
Oh, that's nearly exactly what I had in mind, Hopefully this becomes the default in the future!

**Comment by steren** [comment]
Yes, the goal is to have --experimental_ui be the default. I created https://github.com/bazelbuild/bazel/issues/3187 to track it
