### ISSUE TITLE
bazel run and build failed to run after executing bazel test 

### ISSUE THREAD

**Issue by zhexuany** [bazelbuild/bazel#3150]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### If possible, provide a minimal example to reproduce the problem:
My repo: tikv-java-client.
`bazel test //src/test/java/com/pingcap/tikv:tikv-client-java-test`
### Environment info
* Operating System:
macOs.

* Bazel version (output of `bazel info release`):
0.50

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)
No. 

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).
ERROR: /Users/zhexuany/repo/java/tikv-client-java/BUILD:9:12: Label '//:bazel-tikv-client-java/external/local_jdk/lib/missioncontrol/plugins/com.jrockit.mc.console.ui.notification_5.5.1.172852/icons/alert_obj.png' crosses boundary of subpackage 'bazel-tikv-client-java/external/local_jdk' (perhaps you meant to put the colon here: '//bazel-tikv-client-java/external/local_jdk:lib/missioncontrol/plugins/com.jrockit.mc.console.ui.notification_5.5.1.172852/icons/alert_obj.png'?).
ERROR: /Users/zhexuany/repo/java/tikv-client-java/BUILD:9:12: Label '//:bazel-tikv-client-java/external/local_jdk/lib/visualvm/visualvm/modules/com-sun-tools-visualvm-modules-appui.jar' crosses boundary of subpackage 'bazel-tikv-client-java/external/local_jdk' (perhaps you meant to put the colon here: '//bazel-tikv-client-java/external/local_jdk:lib/visualvm/visualvm/modules/com-sun-tools-visualvm-modules-appui.jar'?).
ERROR: /Users/zhexuany/repo/java/tikv-client-java/BUILD:9:12: Label '//:bazel-tikv-client-java/external/local_jdk/man/ja_JP.UTF-8/man1/rmic.1' crosses boundary of subpackage 'bazel-tikv-client-java/external/local_jdk' (perhaps you meant to put the colon here: '//bazel-tikv-client-java/external/local_jdk:man/ja_JP.UTF-8/man1/rmic.1'?).
ERROR: /Users/zhexuany/repo/java/tikv-client-java/BUILD:9:12: Label '//:bazel-tikv-client-java/external/local_jdk/lib/missioncontrol/plugins/com.jrockit.mc.rjmx.ja_5.5.1.172852.jar' crosses boundary of subpackage 'bazel-tikv-client-java/external/local_jdk' (perhaps you meant to put the colon here: '//bazel-tikv-client-java/external/local_jdk:lib/missioncontrol/plugins/com.jrockit.mc.rjmx.ja_5.5.1.172852.jar'?).
ERROR: /Users/zhexuany/repo/java/tikv-client-java/BUILD:9:12: Label '//:bazel-tikv-client-java/external/local_jdk/lib/missioncontrol/plugins/org.eclipse.e4.core.commands_0.10.2.v20140424-2344.jar' crosses boundary of subpackage 'bazel-tikv-client-java/external/local_jdk' (perhaps you meant to put the colon here: '//bazel-tikv-client-java/external/local_jdk:lib/missioncontrol/plugins/org.eclipse.e4.core.commands_0.10.2.v20140424-2344.jar'?).
ERROR: /Users/zhexuany/repo/java/tikv-client-java/BUILD:9:12: Label '//:bazel-tikv-client-java/external/local_jdk/lib/missioncontrol/plugins/com.jrockit.mc.rjmx.ui.zh_CN_5.5.1.172852.jar' crosses boundary of subpackage 'bazel-tikv-client-java/external/local_jdk' (perhaps you meant to put the colon here: '//bazel-tikv-client-java/external/local_jdk:lib/missioncontrol/plugins/com.jrockit.mc.rjmx.ui.zh_CN_5.5.1.172852.jar'?).
ERROR: /Users/zhexuany/repo/java/tikv-client-java/BUILD:9:12: Label '//:bazel-tikv-client-java/external/local_jdk/lib/missioncontrol/plugins/org.eclipse.equinox.util_1.0.500.v20130404-1337.jar' crosses boundary of subpackage 'bazel-tikv-client-java/external/local_jdk' (perhaps you meant to put the colon here: '//bazel-tikv-client-java/external/local_jdk:lib/missioncontrol/plugins/org.eclipse.equinox.util_1.0.500.v20130404-1337.jar'?).
ERROR: /Users/zhexuany/repo/java/tikv-client-java/BUILD:9:12: Label '//:bazel-tikv-client-java/external/local_jdk/lib/visualvm/platform/modules/locale/org-netbeans-core-windows_zh_CN.jar' crosses boundary of subpackage 'bazel-tikv-client-java/external/local_jdk' (perhaps you meant to put the colon here: '//bazel-tikv-client-java/external/local_jdk:lib/visualvm/platform/modules/locale/org-netbeans-core-windows_zh_CN.jar'?).
ERROR: /Users/zhexuany/repo/java/tikv-client-java/BUILD:9:12: Label '//:bazel-tikv-client-java/external/local_jdk/lib/visualvm/visualvm/modules/locale/com-sun-tools-visualvm-jmx_zh_CN.jar' crosses boundary of subpackage 'bazel-tikv-client-java/external/local_jdk' (perhaps you meant to put the colon here: '//bazel-tikv-client-java/external/local_jdk:lib/visualvm/visualvm/modules/locale/com-sun-tools-visualvm-jmx_zh_CN.jar'?).
ERROR: /Users/zhexuany/repo/java/tikv-client-java/BUILD:9:12: Label '//:bazel-tikv-client-java/external/local_jdk/lib/visualvm/platform/update_tracking/org-netbeans-modules-applemenu.xml' crosses boundary of subpackage 'bazel-tikv-client-java/external/local_jdk' (perhaps you meant to put the colon here: '//bazel-tikv-client-java/external/local_jdk:lib/visualvm/platform/update_tracking/org-netbeans-modules-applemenu.xml'?).
ERROR: /Users/zhexuany/repo/java/tikv-client-java/BUILD:9:12: Label '//:bazel-tikv-client-java/external/local_jdk/lib/missioncontrol/features/org.eclipse.equinox.p2.core.feature_1.3.0.v20140523-0116/feature.properties' crosses boundary of subpackage 'bazel-tikv-client-java/external/local_jdk' (perhaps you meant to put the colon here: '//bazel-tikv-client-java/external/local_jdk:lib/missioncontrol/features/org.eclipse.equinox.p2.core.feature_1.3.0.v20140523-0116/feature.properties'?).
ERROR: /Users/zhexuany/repo/java/tikv-client-java/BUILD:9:12: Label '//:bazel-tikv-client-java/external/local_jdk/man/ja_JP.UTF-8/man1/jdeps.1' crosses boundary of subpackage 'bazel-tikv-client-java/external/local_jdk' (perhaps you meant to put the colon here: '//bazel-tikv-client-java/external/local_jdk:man/ja_JP.UTF-8/man1/jdeps.1'?).
ERROR: /Users/zhexuany/repo/java/tikv-client-java/BUILD:9:12: Label '//:bazel-tikv-client-java/external/local_jdk/man/man1/jmap.1' crosses boundary of subpackage 'bazel-tikv-client-java/external/local_jdk' (perhaps you meant to put the colon here: '//bazel-tikv-client-java/external/local_jdk:man/man1/jmap.1'?).
ERROR: /Users/zhexuany/repo/java/tikv-client-java/BUILD:9:12: Label '//:bazel-tikv-client-java/external/local_jdk/lib/missioncontrol/features/org.eclipse.ecf.filetransfer.httpclient4.ssl.feature_1.0.0.v20140827-1444/META-INF/MANIFEST.MF' crosses boundary of subpackage 'bazel-tikv-client-java/external/local_jdk' (perhaps you meant to put the colon here: '//bazel-tikv-client-java/external/local_jdk:lib/missioncontrol/features/org.eclipse.ecf.filetransfer.httpclient4.ssl.feature_1.0.0.v20140827-1444/META-INF/MANIFEST.MF'?).
ERROR: /Users/zhexuany/repo/java/tikv-client-java/BUILD:9:12: Label '//:bazel-tikv-client-java/external/local_jdk/lib/missioncontrol/plugins/com.jrockit.mc.console.ui.notification_5.5.1.172852/html/dcommon/gifs/bookicon.gif' crosses boundary of subpackage 'bazel-tikv-client-java/external/local_jdk' (perhaps you meant to put the colon here: '//bazel-tikv-client-java/external/local_jdk:lib/missioncontrol/plugins/com.jrockit.mc.console.ui.notification_5.5.1.172852/html/dcommon/gifs/bookicon.gif'?).
ERROR: /Users/zhexuany/repo/java/tikv-client-java/BUILD:9:12: Label '//:bazel-tikv-client-java/external/local_jdk/lib/visualvm/visualvm/modules/locale/com-sun-tools-visualvm-api-caching_ja.jar' crosses boundary of subpackage 'bazel-tikv-client-java/external/local_jdk' (perhaps you meant to put the colon here: '//bazel-tikv-client-java/external/local_jdk:lib/visualvm/visualvm/modules/locale/com-sun-tools-visualvm-api-caching_ja.jar'?).
ERROR: /Users/zhexuany/repo/java/tikv-client-java/BUILD:9:12: Label '//:bazel-tikv-client-java/external/local_jdk/lib/missioncontrol/plugins/com.jrockit.mc.console.ui.notification_5.5.1.172852/icons/file_obj.gif' crosses boundary of subpackage 'bazel-tikv-client-java/external/local_jdk' (perhaps you meant to put the colon here: '//bazel-tikv-client-java/external/local_jdk:lib/missioncontrol/plugins/com.jrockit.mc.console.ui.notification_5.5.1.172852/icons/file_obj.gif'?).
ERROR: /Users/zhexuany/repo/java/tikv-client-java/BUILD:9:12: Label '//:bazel-tikv-client-java/external/local_jdk/jre/lib/deploy.jar' crosses boundary of subpackage 'bazel-tikv-client-java/external/local_jdk' (perhaps you meant to put the colon here: '//bazel-tikv-client-java/external/local_jdk:jre/lib/deploy.jar'?).
ERROR: /Users/zhexuany/repo/java/tikv-client-java/BUILD:9:12: Label '//:bazel-tikv-client-java/external/local_jdk/lib/visualvm/visualvm/modules/locale/com-sun-tools-visualvm-host_ja.jar' crosses boundary of subpackage 'bazel-tikv-client-java/external/local_jdk' (perhaps you meant to put the colon here: '//bazel-tikv-client-java/external/local_jdk:lib/visualvm/visualvm/modules/locale/com-sun-tools-visualvm-host_ja.jar'?).

**Comment by katre** [comment]
It looks like your dependency labels are incorrect, did you try the corrections from the error message?
```
ERROR: /Users/zhexuany/repo/java/tikv-client-java/BUILD:9:12: Label '//:bazel-tikv-client-java/external/local_jdk/lib/missioncontrol/plugins/com.jrockit.mc.console.ui.notification_5.5.1.172852/icons/alert_obj.png' crosses boundary of subpackage 'bazel-tikv-client-java/external/local_jdk' (perhaps you meant to put the colon here: '//bazel-tikv-client-java/external/local_jdk:lib/missioncontrol/plugins/com.jrockit.mc.console.ui.notification_5.5.1.172852/icons/alert_obj.png'?).
```

If you provide a link to the repo I can take a look and provide further suggestions.

**Comment by zhexuany** [comment]
@katre 
My repo is https://github.com/pingcap/tikv-client-java 
Not sure why this happened. This only happened when I executed `bazel build` after I had been executed `bazel test`.

**Comment by katre** [comment]
I cloned your repo, and ran the command you gave:
```
$ bazel test //src/test/java/com/pingcap/tikv:tikv-client-java-test
```

However, src/test/java/com/pingcap/tikv/BUILD does not define a target named "tikv-client-java-test" so it failed.

I think you need to go back and check your BUILD files that all of the targets and dependencies are correct.

**Comment by katre** [comment]
However, running
```
$ bazel test //src/test/java/com/pingcap/tikv:AllTests
```
does work, and all the tests pass.

**Comment by zhexuany** [comment]
My bad. I change it in the branch I am currently working on. Did you try `bazel build //src/...`  or what else target specify in the `BUILD` file. This is where come from.

**Comment by katre** [comment]
I also have sucess when running "bazel build //src/..." on master.

At this point I suspect the problem is with the changes you've made in your branch. If you're still having problems, I suggest asking on StackOverflow, where we have a very active community, as this does not appear to be a bug in Bazel itself.
