### ISSUE TITLE
Non-determinism of .a file on Darwin OS

### ISSUE THREAD

**Issue by xingao267** [bazelbuild/bazel#3156]
### Description of the problem / feature request / question:
.a files on Darwin OS are not deterministic.

This issue is unveiled by [java_integration_test.test_deterministic_nostamp_build](https://github.com/bazelbuild/bazel/blob/master/src/test/shell/integration/java_integration_test.sh#L299) on Darwin OS when I was working on [change 11590](https://bazel-review.googlesource.com/#/c/11590/), which make source code of singlejar and ijar available from @bazel_tools.

To test that everything would still work with singlejar and ijar compiled on the fly (instead of the pre-compiled one). I changed the default java_toolchain in //tools/jdk/BUILD to use the new singlejar and ijar cc_binary targets like the following:

ijar = ["@bazel_tools//third_party/ijar:ijar"],
singlejar = ["@bazel_tools//src/tools/singlejar:singlejar"],

and run tests locally and on Jenkins. This determinism test failed as some artifacts generated during two singlejar compilation do not have the same md5 digest.

These include:

- stderr-* on all Darwin and Linux: these are fine as the warning files produced are not deterministic due to parallelism
- _xcodelocatorcache and __xcruncache on Darwin: information pertaining to Apple host machines required for using Apple toolkits in local action execution. I guess the non-determinism is also fine for them. And these files are only there when the test is run on Jenkins.
- *.a on Darwin only: they are static library archive file.  Non-determinism shouldn't happen like that, and is likely to be a Bazel bug.

For now, I skip checking the determinism for these files, as [here](https://bazel-review.googlesource.com/#/c/11590/15/src/test/shell/integration/java_integration_test.sh). 

These non-determinism were not discovered before because with the precompiled singlejar, only a very simple java target is compiled in this determinism test (no *.a files are generated before), but with compiling singlejar on the fly, a lot more c targets are built.

### If possible, provide a minimal example to reproduce the problem:
To reproduce the error, once [change 11590](https://bazel-review.googlesource.com/#/c/11590/) is in,

1. checkout Bazel dev version including this change
2. modify https://github.com/bazelbuild/bazel/blob/master/tools/jdk/BUILD#L161 to be: singlejar = ["@bazel_tools//src/tools/singlejar:singlejar"].
3. Enable checking determinism for *.a files in https://bazel-review.googlesource.com/#/c/11590/15/src/test/shell/integration/java_integration_test.sh.
4. Then run command  /path/to/bazel test //src/test/shell/integration:java_integration_test

You might want to also print out the file names in [test_deterministic_nostamp_build](https://github.com/bazelbuild/bazel/blob/master/src/test/shell/integration/java_integration_test.sh#L299) to see which files are different.

### Environment info
* Operating System:
Darwin OS

* Bazel version:
https://bazel-review.googlesource.com/#/c/11590/

###  Have you found anything relevant by searching the web?
https://stackoverflow.com/questions/5965171/what-is-a-file-with-extension-a
https://www.reviversoft.com/file-extensions/a

### Anything else, information or logs or outputs that would be helpful?
See discussion with Lukacs here: https://bazel-review.googlesource.com/#/c/11590/11/src/test/shell/integration/java_integration_test.sh

Test log for [patch set 5](https://bazel-review.googlesource.com/#/c/11590/5) where *.a files are not skipped: http://ci.bazel.io/job/CR/job/bazel-tests/27/BAZEL_VERSION=latest,PLATFORM_NAME=darwin-x86_64/console
The log only shows the md5, which is hard to debug. You might want to print out the file name for the corresponding mdb5.

**Comment by jmmv** [comment]
I recently had to deal with non-determinism in Apple tooling and I do not recall archives being a problem. That said, we know that many of the tools in Xcode are _not_ deterministic, and we have to use them, in which case there may be nothing we can do here.

Do you know if this is still an issue? Thanks.
