### ISSUE TITLE
nocopt .bazelrc

### ISSUE THREAD

**Issue by tomazos** [bazelbuild/bazel#3158]
Suppose I have a compiler option (a "--copt") that I want to be passed by default, but not for some non-default config (say config "foo").  How can I express this in the .bazelrc or otherwise?

    build --copt="-mfma"
    build:foo --nocopt="-mfma"

Doesn't work.  No such thing as "--nocopt"?  Any ideas?

**Comment by meteorcloudy** [comment]
How about just put
```
--config=default
build:default --copt="-mfma"
```
in your .bazelrc file? So --copt="-mfma" is gonna be passed by "default", if you don't want it, just remove `--config=default`

**Comment by mhlopko** [comment]
Friendly ping @tomazos, does Yun's advice help?

**Comment by tomazos** [comment]
I ended up doing it a slightly different way, using "-mno-fma" - but thanks, I'm sure this way works too.
