### ISSUE TITLE
Documentation- Add "local", "checked-in", "prebuilt" and "binary" keywords to `java_import` docs

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#3167]
### Description of the problem / feature request / question:
I was looking for the `java_import` feature but couldn't for the life of me remember how to do it.
Searching the site and google didn't retries java_import.
I tried to search for "bazel local jar", "bazel check in binaries" and "bazel prebuilt_jar".

### If possible, provide a minimal example to reproduce the problem:
Perform one of the above searches and get java_import as one of the results

**Comment by meteorcloudy** [comment]
Are you looking for `https://bazel.build/versions/master/docs/be/java.html#java_import`?
Using the search bar at https://bazel.build/ should help.

**Comment by iirina** [comment]
I agree that this should be easier to find, but FWIW you can always check the list of [Java rules](https://bazel.build/versions/master/docs/be/java.html) when in doubt.

**Comment by meisterT** [comment]
Searching for "bazel local jar" ends up on the Java rules page.
