### ISSUE TITLE
making aspects reachable across repos

### ISSUE THREAD

**Issue by natansil** [bazelbuild/bazel#3168]
### Description of the feature request / question:

in order to run builds with aspects the syntax is:
```
bazel build //java/com/company/example:main \
      --aspects path/to/extension.bzl%metal_proto_aspect
```

I would like to request a feature where if the aspect is found on a **different repo**, it could still be reached.

Something like adding to WORKSPACE:
```
load("@external_repo//:extension.bzl", "metal_proto_aspect")
```

and then the execution will be something like:
```
bazel build //java/com/company/example:main \
      --aspects @external_repo//:extension.bzl%metal_proto_aspect
```

This way aspects can be shared across repos without duplicating them.

**Comment by meteorcloudy** [comment]
@dslomov @laurentlb

**Comment by natansil** [comment]
I've tried recreating this issue and got:
```
ERROR: /Users/.../WORKSPACE:2416:6: file '@ external_repo//: extension.bzl' does not contain symbol 'metal_proto_aspect'.
ERROR: Error evaluating WORKSPACE file.
```
@damienmg @ittaiz

**Comment by damienmg** [comment]
Can you share your definition of external_repo? Also the spaces in the
label are dubious, is that a verbatim copy?

**Comment by damienmg** [comment]
Can you also try to quote the command line argument?

**Comment by natansil** [comment]
@damienmg you are correct, In my test I confused the `output_group` for the `aspect_name`.
This feature exists and works. closing the issue...
