### ISSUE TITLE
Bazel tutorial producing error?

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3169]
(From https://stackoverflow.com/questions/44494235/bazel-tutorial-producing-error)

Hello,

When I run the program my-runner in the “Introduction to Bazel: Build Java” tutorial page at https://bazel.build/versions/master/docs/tutorial/java.html I get an error.

More specifically, when I enter: bazel-bin/my-runner I don’t get the expected result, “Hi!”, rather I get the java console help output. I’ve tried to run this project on Debian 8.8 and Ubuntu 16.04 LTS and get the same result.

Any suggestions are welcome. My java installation is working and I was able to complete https://bazel.build/versions/master/docs/getting-started.html with the expected results.

Thanks.

**Comment by laszlocsomor** [comment]
I filed this as a bug following @steren's suggestion (https://groups.google.com/d/msg/bazel-discuss/50Hk9Qp3-wM/UX-S7ouOCwAJ).

**Comment by spomorski** [comment]
Can you try prefixing the command with ./  ? That is:

./bazel-bin/my-runner

**Comment by griffmcc** [comment]
Thanks for your suggestion, but it leads to the same outcome.

$ bazel clean
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.

$ bazel build //:my-runner
INFO: Found 1 target...
Target //:my-runner up-to-date:
  bazel-bin/my-runner.jar
  bazel-bin/my-runner
INFO: Elapsed time: 0.684s, Critical Path: 0.22s
 
$ ./bazel-bin/my-runner
Usage: java [-options] class [args...]
...

$ bazel-bin/my-runner
Usage: java [-options] class [args...]
...

**Comment by laszlocsomor** [comment]
@griffmcc : try this:
```
set -x  # will print all commands that are executed
./bazel-bin/my-runner
```

**Comment by laszlocsomor** [comment]
I went through the tutorial now and everything worked as expected and as described there.
@griffmcc : Which commit of Bazel did you check out, and what's the output of `bazel info release`?

**Comment by spomorski** [comment]
Did you installl Bazel using Homebrew or the binary installer? JDK 8 is
required for Bazel to function and only the binary installers include it.
If you install via Homebrew or on Debian, you have to manually install the
JDK:

https://bazel.build/versions/master/docs/install.html

**Comment by griffmcc** [comment]
Laszlocsomor and spomorski, thank you for your attention.

$ bazel info release
release 0.5.1

$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)


Previously, I installed bazel on both Debian 8.8 and Ubuntu 16.04 LTS following the “Using Bazel custom APT repository (recommended)” section at https://bazel.build/versions/master/docs/install-ubuntu.html.  I reported the errors that resulted, which was ./bazel-bin/my-runner displaying the java help screen.

Today, I installed bazel on Debian and Ubuntu following the “Install using binary installer” section and got the same errors as before.

I am getting these errors on both Debian and Ubuntu.


Here is the “Install using binary installer” install I did today:

$ sudo apt-get install pkg-config zip g++ zlib1g-dev unzip
Reading package lists... Done
...
Setting up pkg-config (0.28-1) ...

$ chmod +x bazel-0.5.1-installer-linux-x86_64.sh

$ ./bazel-0.5.1-installer-linux-x86_64.sh --user
Bazel installer
...
Bazel is now installed!
...

**Comment by laszlocsomor** [comment]
@griffmcc : Do I understand correctly that you successfully installed Bazel but the Java example still doesn't work? If so, could you please [build the target](https://bazel.build/versions/master/docs/tutorial/java.html#build-with-bazel-1) and attach to the thread `bazel-bin/my-runner`? It's actually a shell script. I want to compare it with my own `bazel-bin/my-runner` in hopes of finding something.

**Comment by griffmcc** [comment]
I have attached bazel-bin/my-runner.

[my-runner.zip](https://github.com/bazelbuild/bazel/files/1083442/my-runner.zip)

Below is information about my environment.

Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 6 10:34:11 2017 (1496745251)
Build timestamp: 1496745251
Build timestamp as int: 1496745251

$ java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)

$ sudo apt-get install openjdk-8-jre-headless
...
openjdk-8-jre-headless is already the newest version (8u131-b11-0ubuntu1.16.04.2).
...

$ sudo apt-get install default-jre
...
default-jre is already the newest version (2:1.8-56ubuntu2).
...

$ sudo apt-get install openjdk-8-jre
...
openjdk-8-jre is already the newest version (8u131-b11-0ubuntu1.16.04.2).
...

$ sudo apt-get install default-java-plugin
...
Setting up default-java-plugin (2:1.8-56ubuntu2) ...

$ sudo apt-get install default-jdk
...
Setting up default-jdk (2:1.8-56ubuntu2) ...

**Comment by griffmcc** [comment]
My earlier post had two lines omitted.  The line beginning with "Build target: bazel-out/local-" should be preceded by:

$bazel version
Build label: 0.5.1

**Comment by griffmcc** [comment]
I have traced the xecution of bazel-bin/my-runner and it makes it to line 310 before the java usage page is displayed.  The $CLASSPATH variable is empty.  I have tried adding things at line 309 like:

CLASSPATH="/usr/lib/jvm/java-8-openjdk-amd64:/home/thomas/.cache/bazel/_bazel_thomas/4b9a34882725e03aae1b969f4156284d/execroot/java/bazel-out/local-fastbuild/bin:/home/thomas/Documents/bazel/java"

but have gotten errors like:

Error: Could not find or load main class com.example.ProjectRunner

**Comment by jin** [comment]
Closing as obsolete.
