### ISSUE TITLE
Allow filegroup in exports attribute of java_library

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#3171]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
I'm trying to work around an issue mentioned in #632 and https://github.com/bazelbuild/rules_scala/issues/118 where I need to depend on the `//jar:file` target of a maven_jar and not the `jar` target. What I've done so far was just to depend explicitly on `@workspace//jar:file` in all of my BUILD files but now I need to add `runtime_deps` for some of them and I faced a problem where trying the following:
```
java_library(
    name = "me_chrons_boopickle_2_11",
    visibility = ["//visibility:public"],
    exports = [
        "@me_chrons_boopickle_2_11//jar:file",
    ],
)
```  
fails because of:
```
ERROR: .../third_party/BUILD:4:15: in exports attribute of java_library rule //third_party:me_chrons_boopickle_2_11: filegroup rule '@me_chrons_boopickle_2_11//jar:file' is misplaced here (expected cc_binary, cc_library, genrule, genproto, java_import, java_library, java_proto_library, java_lite_proto_library, proto_library, sh_binary or sh_library).
```
I've worked around the issue for now by using `scala_library` which doesn't forbid the above but this limitation should probably be lifted.

### If possible, provide a minimal example to reproduce the problem:

just try to use the above in a BUILD file when the WORKSPACE file has
```
maven_jar(
    name = "me_chrons_boopickle_2_11",
    artifact = "me.chrons:boopickle_2.11:1.2.4",
)
```

### Environment info
* Operating System:
Mac OS X 10.11.6

* Bazel version (output of `bazel info release`):
development version

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
55f40c8ea4f1e7bf81552bfe4377e26768e85f2c

**Comment by sdtwigg** [comment]
I'm presuming java_import or jar import can't be used due to the issue where both call ijar and this interferes with scala macros?

In theory, when this is actually released, https://github.com/bazelbuild/bazel/commit/7e91ad631a660ae12a2b8dcfb8ba42574a7a76d3
you should be able to work around the issue. 

You won't be able to use a filegroup directly, however, you can just have a simple rule that forges a JavaProvider with your jar in it (via java_common.create_provider) and use that as the export. You would effectively be creating your own custom java_import rule that doesn't call ijar.

**Comment by ittaiz** [comment]
Thanks!
That sounds like more work than one should do IMHO to get this done. I can
workaround this via using scala_library as is so I won't be creating a new
custom type just for this one.
I still think it should be considered.

**Comment by cushon** [comment]
@lberki @iirina

The support for e.g. `.jar` files in `java_library.deps` is a historical accident that will eventually be fixed. Additional addition support for using files (or `filegroups`) is not a goal.

This use-case is handled by `java_common.create_provider` or (when #632 is addressed) by `java_import`.

**Comment by ittaiz** [comment]
We can close as far as I’m concerned (don’t remember if I authored this
issue)

**Comment by lberki** [comment]
So be it then!
