### ISSUE TITLE
javac -Werror flag doesn't work with Bazel 0.5.1

### ISSUE THREAD

**Issue by cushon** [bazelbuild/bazel#3172]
-Werror can't be used with Bazel 0.5.1 because JavaBuilder emits an unsuppressible warning. The warning needs to be fixed.

Also, the Java integration tests should exercise -Werror to prevent regressions.

context: https://groups.google.com/d/topic/bazel-discuss/J8smhzzSuPY/discussion

**Comment by ulfjack** [comment]
Ping?

**Comment by pgr0ss** [comment]
Seems fixed in 0.5.2, and we were able to upgrade and keep our warnings turned on.
