### ISSUE TITLE
compile broken from 6073f1d41a102b70007356d1445c57b7f7533d78

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/bazel#3174]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
with a recent bazel binary in output
git pull && ./compile.sh compile $PWD/output/bazel

src/java_tools/buildjar/java/com/google/devtools/build/buildjar/BUILD:131:12: in srcs attribute of bootstrap_java_library rule //src/java_tools/buildjar/java/com/google/devtools/build/buildjar:skylark-deps: '//:bootstrap-derived-java-srcs' does not produce any bootstrap_java_library srcs files (expected .java).
ERROR: Analysis of target '//src:bazel' failed; build aborted.
INFO: Elapsed time: 9.423s

### If possible, provide a minimal example to reproduce the problem:
see above

### Environment info
* Operating System: OSX 10.12.5

* Bazel version (output of `bazel info release`):
release 0.5.1-2017-06-12 (@d9223e00c)

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by meteorcloudy** [comment]
@aehlig I think `compile.sh` doesn't work at HEAD, instead it only work in our released source tree? Like https://github.com/bazelbuild/bazel/archive/0.5.1.zip

@pmbethe09 If you already have a bazel installed, you can build bazel@HEAD with `bazel build //src:bazel`

**Comment by pmbethe09** [comment]
Ah -- I hadn't realized about `bazel build //src:bazel`, I have been using compile.sh for the last year.

So WAI.
