### ISSUE TITLE
Bazel loads deprecated docker rules, prints warning

### ISSUE THREAD

**Issue by jgavris** [bazelbuild/bazel#3175]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

Our project has chosen to build our workspace with a bazel that has been bootstrapped from source from a submodule, so we can update it easily and with minimal overhead to our developers. Our bazel wrapper script builds bazel itself on every build, and then invokes the bazel command passed to it, so we see the following deprecation warning on every build.

```shell
WARNING: /Users/jgavris/code/software/bazel/tools/build_defs/docker/docker.bzl:19:1: The docker_{build,bundle} rules bundled with Bazel are deprecated in favor of:
https://github.com/bazelbuild/rules_docker. Please change BUILD loads to reference: @io_bazel_rules_docker//docker:docker.bzl and add the following to your WORKSPACE:
git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    commit = "...",
)
load("@io_bazel_rules_docker//docker:docker.bzl", "docker_repositories")
docker_repositories().
```

### If possible, provide a minimal example to reproduce the problem:

Build bazel from source:

```shell
$ bazel build //src:bazel-bin
```

### Environment info
* Operating System:
macOS 10.12.5

* Bazel version (output of `bazel info release`):
release 0.5.1-homebrew

### Anything else, information or logs or outputs that would be helpful?

I may try to tackle this later this week. I was wondering if anyone is aware of it and / or planning to resolve it in the near future.

**Comment by mattmoor** [comment]
@damienmg @steren FYI.  I deprecated these as a first step towards unbundling them from the Bazel core.  It is still not completely clear to me if/how long to leave the bundled version of the rules?

**Comment by steren** [comment]
Now that we have the warning in place in 0.5, we can remove them in the next release.
@mattmoor do you want to take care of this?

**Comment by mattmoor** [comment]
If I can just remove them at head and that'll do the right thing, then I'm happy to do this in the next few days.

**Comment by mattmoor** [comment]
@steren I was thinking about this a bit yesterday, and while I'm happy to remove them, I'm not sure Bazel has fully migrated to the new rules (e.g. [in the CI repo](https://github.com/bazelbuild/continuous-integration/blob/7c9704038b29445809e3966c4506312e3e5301ec/jenkins/base/BUILD#L1)).  So I'm inclined to say @damienmg should own this cleanup since that repo also needs to use our official `docker_pull`, `docker_push` rules.

**Comment by jgavris** [comment]
It would be nice to provide an API to dismiss / silence deprecation warnings ... perhaps indicate the version of bazel the deprecation was added in, and a command-line flag to bazel to ignore deprecation warnings that are less than or equal to that version?

**Comment by damienmg** [comment]
That seems fair but for the record I won't have time to work on that before
at least the end of the summer.

**Comment by mattmoor** [comment]
Sent a PR to migrate `docker_build`: https://github.com/bazelbuild/continuous-integration/pull/79

**Comment by mattmoor** [comment]
Damien adapted my CI PR, and got it merged.  I put together an internal CL that should remove these rules, and if all go smoothly it'll be out in the next few days.

That said, there are a variety of ways I can see it not going smoothly :)

**Comment by jgavris** [comment]
Any update on this?

**Comment by mattmoor** [comment]
Ball's in @damienmg's court, Bazel core uses these rules for testing, but the current testing setup can't properly import the new rules.

**Comment by jgavris** [comment]
Just wondering if we're close on this one?

**Comment by damienmg** [comment]
Unfortunately no :(

**Comment by mattmoor** [comment]
@damienmg Given that this is complicated mostly for internal reasons, can we at least get a change into 0.6 that removes the deprecation notice and changes the visibility?

**Comment by jgavris** [comment]
This was resolved a while ago, thanks!
