### ISSUE TITLE
bazel won't build external maven jar dependencies??

### ISSUE THREAD

**Issue by lucianspec** [bazelbuild/bazel#3176]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

i am trying to add elastic search client Jest to my WORKSPACE file

```
maven_jar(
  name = "io_searchbox_jest",
  artifact = "io.searchbox:jest:5.3.2",
)
```

and i found seems bazel won't build jest dependencies? 

### Environment info
* Operating System:

macOS 10.12.1 (16B2657)

* Bazel version (output of `bazel info release`):

release 0.2.3

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?

i also found a project **bazel-deps**
https://github.com/pgr0ss/bazel-deps
and it's tell me had to add dependency manually.

```
--------- Add these lines to your WORKSPACE file ---------

maven_jar(name = "commons_codec_commons_codec_1_9", artifact = "commons-codec:commons-codec:jar:1.9")
maven_jar(name = "commons_logging_commons_logging_1_2", artifact = "commons-logging:commons-logging:jar:1.2")
maven_jar(name = "com_google_code_gson_gson_2_8_0", artifact = "com.google.code.gson:gson:jar:2.8.0")
maven_jar(name = "com_google_guava_guava_21_0", artifact = "com.google.guava:guava:jar:21.0")
maven_jar(name = "org_apache_httpcomponents_httpasyncclient_4_1_3", artifact = "org.apache.httpcomponents:httpasyncclient:jar:4.1.3")
maven_jar(name = "org_apache_httpcomponents_httpclient_4_5_3", artifact = "org.apache.httpcomponents:httpclient:jar:4.5.3")
maven_jar(name = "org_apache_httpcomponents_httpcore_4_4_6", artifact = "org.apache.httpcomponents:httpcore:jar:4.4.6")
maven_jar(name = "org_apache_httpcomponents_httpcore_nio_4_4_6", artifact = "org.apache.httpcomponents:httpcore-nio:jar:4.4.6")
maven_jar(name = "io_searchbox_jest_5_3_2", artifact = "io.searchbox:jest:jar:5.3.2")
maven_jar(name = "io_searchbox_jest_common_5_3_2", artifact = "io.searchbox:jest-common:jar:5.3.2")
maven_jar(name = "org_slf4j_slf4j_api_1_7_25", artifact = "org.slf4j:slf4j-api:jar:1.7.25")


--------- Add these lines to your BUILD file ---------

java_library(
  name="jest",
  visibility = ["//visibility:public"],
  exports = [
    "@com_google_code_gson_gson_2_8_0//jar",
    "@com_google_guava_guava_21_0//jar",
    "@commons_codec_commons_codec_1_9//jar",
    "@commons_logging_commons_logging_1_2//jar",
    "@io_searchbox_jest_5_3_2//jar",
    "@io_searchbox_jest_common_5_3_2//jar",
    "@org_apache_httpcomponents_httpasyncclient_4_1_3//jar",
    "@org_apache_httpcomponents_httpclient_4_5_3//jar",
    "@org_apache_httpcomponents_httpcore_4_4_6//jar",
    "@org_apache_httpcomponents_httpcore_nio_4_4_6//jar",
    "@org_slf4j_slf4j_api_1_7_25//jar",
  ],
)
```

so this is the best practice to add a external maven jar???

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by meteorcloudy** [comment]
@kchodorow Can you take a look at this?

**Comment by petroseskinder** [comment]
Are you also including `io_searchbox_jest`'s transitive dependencies in your WORKSPACE file? 

Bazel requires that all external dependencies be explicitly declared within the WORKSPACE file [source](https://bazel.build/versions/master/docs/external.html#generate-a-workspace-file). When you depend on `io_searchbox_jest`, you also implicitly depend on all of its dependencies and their dependencies (i.e. its transitive dependencies). According to its [pom.xml](https://search.maven.org/remotecontent?filepath=io/searchbox/jest/5.3.2/jest-5.3.2.pom), `io_searchbox_jest` depends on the following maven artifacts
```
org.apache.lucene:lucene-test-framework
org.elasticsearch.test:framework
net.java.dev.jna:jna
org.hamcrest:hamcrest-all
com.carrotsearch.randomizedtesting:randomizedtesting-runner
org.apache.lucene:lucene-codecs
io.searchbox:jest-common
org.apache.httpcomponents:httpcore-nio
org.apache.httpcomponents:httpclient
org.apache.httpcomponents:httpasyncclient
...
```
Currently, the `maven_jar` rule only fetches the jar for `io_searchbox_jest`. It does _not_ fetch its transitive dependencies, i.e. the jars for each of above artifacts. 

For Bazel to successfully build your project, it will need to know where to find these jars. Consequently, you will need to explicitly declare these dependencies within your WORKSPACE file. 

There are a two general approaches you can take. One is to directly write the maven_jar in your WORKSPACE file, creating an expansive WORKSPACE file. (This is the suggestion you found). Another is to create a separate bzl file and load your maven jar from there. [Here is an example from a fork of that project.](https://github.com/johnynek/bazel-deps)

```python
load("//3rdparty:workspace.bzl", "maven_dependencies")
load("//3rdparty:load.bzl", "declare_maven")
maven_dependencies(declare_maven)
#note: these are two macros defined by the tool
```

The biggest challenge you will face is with actually generating the transitive dependencies, i.e. identifying all of the dependencies of your jar, their dependencies, the dependencies of their dependencies, and so on. There are numerous tools for generating these transitive dependencies. The one officially supported by the Bazel team is the generate_workspace tool. Documentation can be found [here](https://bazel.build/versions/master/docs/external.html#generate-a-workspace-file). It is currently housed in the [migration-tooling repository](https://github.com/bazelbuild/migration-tooling)

**Comment by lucianspec** [comment]
thanks for your detailed explanation, it solved.
