### ISSUE TITLE
Tests: //src/test/cpp/{startup_options,workspace_layout}_test.cc are unused

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3177]
We have no open-source BUILD rules for these.

**Comment by ulfjack** [comment]
@tfarina Unfortunately, we have two sets of BUILD files right now.

**Comment by ulfjack** [comment]
I think this should be a P2, and possibly be categorized as a bug.

**Comment by tfarina** [comment]
@ulfjack, workspace_layout_test.cc also needs code changes, it is using google3 apis.

**Comment by aiuto** [comment]
Believe fixed in 58acb7b85c6e06ac0142a8c8d53e4aa9000ccfd0
