### ISSUE TITLE
65 test cases timing out on RHEL 7.3/x86.

### ISSUE THREAD

**Issue by sowani** [bazelbuild/bazel#3180]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
When bazel test suite is run on x86 running RHEL 7.3, 65 test cases are timing out. List of test cases attached. 
[bazel_timeouts_rhel.txt](https://github.com/bazelbuild/bazel/files/1071283/bazel_timeouts_rhel.txt)

### If possible, provide a minimal example to reproduce the problem:
After building bazel source (cloned from GitHub):
output/bazel test

### Environment info
* Operating System:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.0 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.0"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.0:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.0
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION=7.0

* Bazel version (output of `bazel info release`):
release 0.4.5-2017-05-23 (@69d2ea2)

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).
https://github.com/bazelbuild/bazel/issues/3019

**Comment by philwo** [comment]
Closing, please re-open if it's still happening.
