### ISSUE TITLE
Bazel cache throwing errors after external dependency removal

### ISSUE THREAD

**Issue by Helcaraxan** [bazelbuild/bazel#3181]
### Description of the problem:

While eliminating some tech debt from our project I have encountered a strange caching error in Bazel.

I have taken the following steps:
 
1. Removed all references in our codebase to the external dependency.
2. Removed all references to the external dependency in `BUILD` files.
3. Removed the external dependency from the `WORKSPACE`.

When running this on a hot Bazel cache that has already build the codebase without these changes I get the following errors:
```
 ERROR: /home/teamcity/BuildAgent/work/ee9378522cbb9fd1/Proto/improbable/protocol/BUILD:150:1: Couldn't build file Proto/improbable/protocol/system_command.pb.cc: Executing genrule //Proto/improbable/protocol:system_command_proto_cc_codegen failed: Process terminated by signal 15 [sandboxed].
Use --strategy=Genrule=standalone to disable sandboxing for the failing actions.
 ____Building complete.
 ERROR: /home/teamcity/BuildAgent/work/ee9378522cbb9fd1/cpp/core_sdk/BUILD:91:1 Failed to get cached inputs: Could not determine containing package for external/nlohmann_json/src/json.hpp.
 ____Elapsed time: 1.924s, Critical Path: 0.22s
Process exited with code 1
```

These errors do not appear on a cold cache and reverting step 3. solves the errors on the hot cache.

I've `grep`ed for the removed dependency in the `bazel-bin` folder and it appears in the `.d` files (these are `cc_library` rules) associated with the source files that previously referenced the external dependency.

### If possible, provide a minimal example to reproduce the problem:
I have wriggled around for a few hours with a small Bazel test project but was unable to reproduce the issue directly.

### Environment info
* Operating System: Linux & macOS
* Bazel version (output of `bazel info release`): 0.4.5

###  Have you found anything relevant by searching the web?
Nope

**Comment by meteorcloudy** [comment]
@kchodorow Can you take a look at this?

**Comment by dslomov** [comment]
I'll have to close this as this is not really actionable
