### ISSUE TITLE
Commit a4697fd ("Make C++ archiving use action_configs instead of hardcoded flags") broke cgo builds in MacOS

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel#3184]
Starting with commit a4697fdc1372adc6189abda0990e9ffd7ed00d63, Bazel invokes `/usr/bin/libtool` with flags that aren't recognized in the MacOS version.

Old invocation (succeeds):
```
$ bazel build -s //vendor/gopkg.in/mgo.v2/...
[...]
/usr/bin/libtool -static -s -o bazel-out/local-fastbuild/bin/vendor/gopkg.in/mgo.v2/internal/sasl/cgo_default_library.cgo.dir/gen/lib_cgo_lib.lo [...]
```

New invocation (fails):
```
$ bazel build -s //vendor/gopkg.in/mgo.v2/...
[...]
/usr/bin/libtool rcsD bazel-out/local-fastbuild/bin/vendor/gopkg.in/mgo.v2/internal/sasl/cgo_default_library.cgo.dir/gen/lib_cgo_lib.lo [...]
ERROR: /private/var/tmp/_bazel_jmillikin/7703c98cd5e24ec5d319151bffe9e906/vendor/gopkg.in/mgo.v2/internal/sasl/BUILD:3:1: Linking of rule '//vendor/gopkg.in/mgo.v2/internal/sasl:cgo_default_library.cgo.dir/gen/_cgo_lib' failed: Process exited with status 1 [sandboxed].
error: /Library/Developer/CommandLineTools/usr/bin/libtool: no output file specified (specify with -o output)
Usage: /Library/Developer/CommandLineTools/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
Usage: /Library/Developer/CommandLineTools/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]
Use --strategy=CppLink=standalone to disable sandboxing for the failing actions.
```

cc @mhlopko @laszlocsomor

**Comment by mhlopko** [comment]
That's bad, I'll fix it right away. Thanks for reporting!

**Comment by mhlopko** [comment]
Hmm. Do you use custom crosstool? Does this also persist when you run `bazel clean --expunge`?

**Comment by mhlopko** [comment]
Can you also reproduce this by calling `bazel test //examples/cgo:cgo_lib_test` from [rules_go](https://github.com/bazelbuild/rules_go) workspace?

**Comment by jmillikin-stripe** [comment]
`bazel test //examples/cgo:cgo_lib_test` fails with the same error message.

```diff
diff --git a/WORKSPACE b/WORKSPACE
index 94ba2be..8153dc6 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -1,3 +1,9 @@
+http_archive(
+    name = "bazel_tools",
+    strip_prefix = "bazel-a4697fdc1372adc6189abda0990e9ffd7ed00d63",
+    url = "https://github.com/bazelbuild/bazel/archive/a4697fdc1372adc6189abda0990e9ffd7ed00d63.tar.gz",
+)
+
 workspace(name = "io_bazel_rules_go")
 
 load("@io_bazel_rules_go//go:def.bzl", "go_repositories", "go_repository")

```
```
[~/src/rules_go] $ bazel clean --expunge
[~/src/rules_go] bazel test //examples/cgo:cgo_lib_test
[...]
INFO: Found 1 test target...
ERROR: /Users/jmillikin/src/rules_go/examples/cgo/cc_dependency/BUILD:6:1: Linking of rule '//examples/cgo/cc_dependency:version' failed: Process exited with status 1 [sandboxed].
error: /Library/Developer/CommandLineTools/usr/bin/libtool: no output file specified (specify with -o output)
```

I'm not using a custom crosstool, at least not intentionally. `CC` is the standard Apple-distributed LLVM:
```
$ clang --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by mhlopko** [comment]
I still cannot reproduce but by following the code path I think I found it and have a fix in flight.

**Comment by jmillikin-stripe** [comment]
That commit hasn't changed the behavior. I updated `WORKSPACE` to use that commit ID for `@bazel_tools`, ran `bazel clean --expunge`, and libtool is still being called as `/usr/bin/libtool rcsD bazel-out/...`.

**Comment by mhlopko** [comment]
Hmm. Do you have xcode installed? Can you try with Bazel@HEAD?

**Comment by jmillikin-stripe** [comment]
> Hmm. Do you have xcode installed? Can you try with Bazel@HEAD?

I don't have XCode, nor the Java dev environment to build Bazel. I'm using Bazel build 0.5.1, so it's pretty close to HEAD.

What's the logic Bazel is using to decide how to structure the libtool options? I'd be happy to run detection scripts or whatever would be useful for inspecting my libtool setup.

**Comment by mhlopko** [comment]
So we released 0.5.2 in the meantime, you can try your luck with it. If it persists, I'm clueless, so I'll try to explain the path hoping that you might find something suspicious :)

* It all starts with [cc_configure.bzl](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/cc_configure.bzl#L34). 
* In your case the [xcode check](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/osx_cc_configure.bzl#L59) should return empty collection and delegate to [unix_cc_toolchain.bzl](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/unix_cc_configure.bzl#L354)
* [Here](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/unix_cc_configure.bzl#L170) we set target libc to "macosx"
* [And here is what we patch the crosstool with at loading time](https://github.com/bazelbuild/bazel/blob/3759d00356e7bf1dcf42e34cb83ad7bf3153a9c2/src/main/java/com/google/devtools/build/lib/rules/cpp/CppActionConfigs.java#L332). Platform is taken from [here](https://github.com/bazelbuild/bazel/blob/90ccaa583828aa4e9bf8b7b0507ab518121ef90c/src/main/java/com/google/devtools/build/lib/rules/cpp/CppConfiguration.java#L653).

Any ideas?

**Comment by jmillikin-stripe** [comment]
Upgrading to Bazel 0.5.2 fixed it -- at least, I'm not able to reproduce the build failure on `cgo_lib_test`. Surprisingly I can't even get it to fail by manually pinning `@bazel_tools` back to an old version, which makes me suspect this whole issue was caused by version skew between Bazel and `@bazel_tools` rather than bad logic in the toolchain detection.

 ¯\\\_(ツ)\_/¯

**Comment by mhlopko** [comment]
Pfew, at least it's gone. Glad you can be productive again :)
