### ISSUE TITLE
Name Spawned Bazel processes (server and workers) as Bazel and not Java

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#3185]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I'm trying to debug an issue where I **think** Bazel is spawning tens (~70) of worker processes for some obscure reason. When I look in "Activity Monitor" (OS X) I see a lot of `java` processes.
That makes it hard for me to know in a glance what are they. Are they related to Bazel? Are they workers? Are they orphan server instances? Additionally maybe naming it after the worker type would bring even more value.
If I were to see "Bazel server", "Bazel JavaC worker", "Bazel ScalaC worker" that would have helped me tremendously.

### If possible, provide a minimal example to reproduce the problem:
start a worker heavy build and open activity monitor (or `ps aux`)

### Environment info
* Operating System:
OS X 10.11.6

* Bazel version (output of `bazel info release`):
development

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
55f40c8ea4f1e7bf81552bfe4377e26768e85f2c

**Comment by meteorcloudy** [comment]
@philwo Is this doable to name the processes?

**Comment by ittaiz** [comment]
@philwo any thoughts?

**Comment by philwo** [comment]
@ittaiz Sounds like a nice feature. Not sure if it's actually possible to implement this (some OS have an API like this: https://www.freebsd.org/cgi/man.cgi?query=setproctitle&sektion=3 - I guess there might be something similar for Linux and Windows, too.

I'd be happy to review a patch for this. I won't get to it myself in the next time.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
