### ISSUE TITLE
Make "experimental UI" the default Bazel UI (console output)

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#3187]
Bazel is a command line tool. The output of a command line action should be digestible by a human and provide real time feedback. 

Machines should not rely on the command line output but rather use the dedicated Build Event Protocol to access build events.

Today, Bazel outputs way too much information. We need a clean output, that describes what are the actions in progress and errors encountered.

And this is what `--experimental_ui`  is doing. Let's make it the default UI for Bazel

**Comment by meisterT** [comment]
Already done in 784bb52613feb484221c3aa6756de45012163088
