### ISSUE TITLE
java_test attempting to load incorrect classes when BUILD is inside a folder named "java"

### ISSUE THREAD

**Issue by dgavedissian** [bazelbuild/bazel#3191]
### Description of the problem / feature request / question:

In our project, we have workspace with a BUILD file inside `worker_sdk/java`. This file contains a `java_test` target which looks roughly like the following:

```
java_test(
    name = "java_sdk_tests",
    size = "small",
    srcs = glob([
        "src/test/java/improbable/worker/*.java",
    ]),
    deps = [
        ":java_sdk",
        "//third_party/junit",
    ]
)
```

This used to work fine in the past when this BUILD file was located in a folder called `java_sdk`, but after it was moved to `worker_sdk/java`, the following errors began to happen:

```
INFO: From Testing //worker_sdk/java:java_sdk_tests:
==================== Test output for //worker_sdk/java:java_sdk_tests:
JUnit version 4.11
Could not find class: src.test.java.improbable.worker.CallbacksTest
Could not find class: src.test.java.improbable.worker.ClientErrorTest
Could not find class: src.test.java.improbable.worker.ComponentCallbacksTest
Could not find class: src.test.java.improbable.worker.PackageScannerTest

Time: 0.001

OK (0 tests)
```

Looks like a heuristic is used by finding the first occurrence of "java" in the source file path, and using that to build a fully qualified class name, but it ignores the fact the build file is located in a path containing a directory called "java".

### Environment info
* Operating System: Ubuntu 16.04

* Bazel version (output of `bazel info release`): release 0.4.5, but also happens in 0.5.1

###  Have you found anything relevant by searching the web?
We can use this as a workaround, but it is not ideal: https://github.com/bazelbuild/bazel/issues/354#issuecomment-140153326

**Comment by meisterT** [comment]
This doesn't seem to be a problem with modern Bazel anymore.
