### ISSUE TITLE
new_local_repository: validate `build_file` attribute (esp. on Windows)

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3192]
### Description of the problem / feature request / question:

Trying  to build `//:main` in https://github.com/abergmeier-dsfishlabs/bazel/commit/51d024e12123a45dd6bc38bfb1fe5811867c9176 - `third_party\python\test_win` makes the Skylark parser throw an exception from `sun.nio.fs.WindowsPathParser.normalize`.

### Environment info
* Operating System: Windows 10
* Bazel version (output of `bazel info release`): 0.5.1

**Comment by meteorcloudy** [comment]
Here: https://github.com/abergmeier-dsfishlabs/bazel/commit/51d024e12123a45dd6bc38bfb1fe5811867c9176#diff-12d915cac6de6a779d777547b149656eR5

You should use `build_file_content` instead of `build_file`, otherwise bazel would consider it as a file path.

**Comment by abergmeier-dsfishlabs** [comment]
Oh, I know. Still it should IMO not throw an exception ;)

**Comment by meteorcloudy** [comment]
Yeah, a more clear error message would be better. Anyway, closing this now.

**Comment by abergmeier-dsfishlabs** [comment]
> Anyway, closing this now.

Why? Shouldn't that at least get a P4 or something?

**Comment by meteorcloudy** [comment]
Fine, making it a P4 now. ;)
