### ISSUE TITLE
Switch Bazel to a more secure hash by default (SHA256?)

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#3193]
Switch Bazel to a more secure hash by default (SHA256?).

**Comment by ulfjack** [comment]
SHA1 is a bit outdated now, as is MD5. We should probably add support for - at least - SHA256.

**Comment by benjaminp** [comment]
A good option might be `blake2`, which is secure and fast in software.

**Comment by MarkusTeufelberger** [comment]
SHA256 isn't exactly slow either and recent CPUs might even already have native instructions: https://en.wikipedia.org/wiki/Intel_SHA_extensions
