### ISSUE TITLE
What is the possible op substitute for set of OPerations on CPU to DSP Hexagon

### ISSUE THREAD

**Issue by kzos** [bazelbuild/bazel#3199]
OS: Ubuntu 16.04 64bits
Android Version: 7.1 (Nougat)
NDK Version: android-ndk-r12b
HEXAGON SDK: 3.1
nnlib source: https://source.codeaurora.org/quic/hexagon_nn/nnlib 

I am trying to build a graph to run on hexagon,
it uses few op's which hexagon doesn't support.

`native : graph_transferer.cc:109 Failed to transfer graph Invalid argument: Mean has not been implemented yet.`

OP's details are as below:-

     {"Mean", SupportedOpType::**??**},
     {"RealDiv", SupportedOpType::**??**},
     {"Pow", SupportedOpType::**??**},
     {"Conv2DBackpropInput", SupportedOpType::**??**},
     {"Square", SupportedOpType::**??**},
     {"SquaredDifference", SupportedOpType::**??**},
     {"StopGradient", SupportedOpType::**??**},
     {"Reciprocal", SupportedOpType::**??**},

Is there any possible substitute for the operation types Mean, Pow, Conv2DBackpropInput etc.. for hexagon.

thanks in advance.

**Comment by kzos** [comment]
@satok16, could you please suggest possible substitute , thanks

**Comment by meteorcloudy** [comment]
Looks like a TensorFlow issue, please file at https://github.com/tensorflow/tensorflow/issues

**Comment by kzos** [comment]
Oops, I didn't notice, sorry about that.!
