### ISSUE TITLE
cross-package generated symlinks can cause unnecessary intra-build skyframe invalidation

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#3200]
This is Bazel 0.5.1 on Ubuntu 16.04.

Here's how to set up a workspace to reproduce the bug:
```
mkdir symlink-bug;
cd symlink-bug;
mkdir a b;
touch WORKSPACE b/link-target a/boring-source-file;
cat > a/BUILD <<'EOF'
genrule(
    name = 'do-link',
    outs = ['a-link'],
    srcs = ['//b:link-target'],
    cmd = 'ln -s $$(realpath .)/$< $@',
)

exports_files(['boring-source-file'])
EOF
echo "exports_files(['link-target'])" > b/BUILD;
```
These commands demonstrate the bug:
```
$ bazel build --genrule_strategy=standalone a:a-link
...
$ ls bazel-symlink-bug
a  b  bazel-out  _bin  external
$ bazel build a:boring-source-file
...
$ ls bazel-symlink-bug
a  bazel-out  _bin
$ readlink -f bazel-genfiles/a/a-link
$ echo $?
1
$ grep informAboutNumberOfModifiedFiles $(bazel info output_base)/java.log | tail -1
170615 18:22:35.370:I 25 [com.google.devtools.build.lib.skyframe.SkyframeExecutor.informAboutNumberOfModifiedFiles] Found 1 modified files from last build
$ bazel build --genrule_strategy=standalone a:a-link --profile=prof
...
$ bazel analyze-profile prof --task_set=Executing --task_tree_threshold=0
INFO: Aggregating task statistics
    14 ACTION_CHECK (0.537 ms) Executing genrule //a:do-link []
```

As `java.log` shows, the second `build` command finds a modified file somewhere in the output tree even though nothing has been changed by the user. It appears the "modified file" is actually a failure to resolve the target of `bazel-genfiles/a/a-link`. The target has disappeared because executing the build of `a:boring-source-file` deleted the `b` package root symlink from the execroot. From the profile of the second time we build `a:a-link`, we see the build now has to go through an action cache check for `a:do-link`.

You might say that creating symlinks into the execroot with a genrule is bad, and I would agree. However, my example is merely a simplified version of a problem I saw when "legitimately" using cc virtual includes (i.e., `strip_include_prefix`) and external repositories. For example, something like
```
new_http_archive(
    name = 'some-thirdparty-dep',
    build_file_content = '''
cc_library(
    name = 'a-lib',
    strip_include_prefix = '',
)
''',
)
```
will result in symlinks from genfiles into `execroot/external/some-thirdparty-dep`.

One way to fix this would be make `SymlinkForest` work incrementally rather than blowing away and recreating the execroot in every build.

**Comment by ulfjack** [comment]
Marking as P3, since it's not a correctness issue, and I don't think it's very common. Certainly, it would be nice to fix, so if we can do that without otherwise reducing performance, by all means. The SymlinkForrest class is written under the assumption that it's common to have multiple package_path entries, but that's actually uncommon in Bazel, so it's not unlikely that we can improve how it works in that case.

**Comment by cgrushko** [comment]
@ulfjack since this is used in `new_http_archive` with `strip_include_prefix`, does it mean it happens frequently in Bazel?

**Comment by dslomov** [comment]
Please do not assign more than one team to an issue.

**Comment by janakdr** [comment]
We don't really like the execroot at all, but we're not planning to work on removing those symlinks anytime soon. I don't think we'd want to leave stale symlinks lying around in the execroot, so even if SymlinkForest did work incrementally, we probably wouldn't leave the one to b/ if we built something that didn't depend on b.

A solution to this specific problem might be to do output file checking without resolving symlinks. However, that might be a pretty big change (I think we would have to change how we calculate [output metadata for symlinks](https://github.com/bazelbuild/bazel/blob/7a11752a8ae7689d2bd482e23d466cb44a3261a1/src/main/java/com/google/devtools/build/lib/skyframe/ActionMetadataHandler.java#L583)).

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
