### ISSUE TITLE
Modifying headers does not trigger a rebuild of dependent source files (Windows).

### ISSUE THREAD

**Issue by pbos** [bazelbuild/bazel#3202]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

Modifying headers do not trigger a rebuild of dependent source files (at least not by default / on Windows). This has caused me size mismatches between structs and resulting heap and stack corruption and crashes. If I change a header to just contain #error, the program doesn't recompile anything. As a routine I always do a full rebuild whenever my app crashes, and most of the time (so far) that has fixed the root cause.

I have a simple repro below, but in essence updates to header files will only be observed by files that are otherwise rebuilt. If there's some kind of header-check setting that need to go in here, please let me know, but if so, this seems like a crazy dangerous default to me. Not even the cc_library target that declares the header will be rebuilt if only the header is changed.

### If possible, provide a minimal example to reproduce the problem:

A minimal repro would be main.cc including main.h. If you change the contents of main.h to be #error and build again, the .exe is already built and files depending on the header won't be recompiled.

A slightly more complicated (but interesting) example contain a main target and a library. They both depend on the same header and are already built. After they are built we change the header (modifying the size of a struct), and then change something inside the library source files. This library will then be compiled with the updated struct size, while the main target will use the old struct size and layout.

C:\Users\msft\bazel_rebuild_repro>bazel build project
[32mINFO: [0mLoading complete.  Analyzing...
[1A[K[32mINFO: [0mFound 1 target...
[32mINFO: [0mBuilding...
[1A[KTarget //project:project up-to-date:
  C:/users/msft/appdata/local/temp/_bazel_msft/nlkmo67r/execroot/bazel_rebuild_repro/bazel-out/msvc_x64-fastbuild/bin/project/project.exe
[32mINFO: [0mElapsed time: 1.064s, Critical Path: 0.65s

C:\Users\msft\bazel_rebuild_repro>.\bazel-bin\project\project.exe
C:\users\msft\appdata\local\temp\_bazel_msft\nlkmo67r\execroot\bazel_rebuild_repro\project\main.cc: struct size: 4
C:\users\msft\appdata\local\temp\_bazel_msft\nlkmo67r\execroot\bazel_rebuild_repro\project\lib.cc: struct size: 4

///// Update the struct inside lib.h to contain 10 more ints. Then add a comment (or otherwise update) lib.cc, so it gets rebuilt.
///// main.cc however does not get rebuilt, even though both files directly include lib.h:

C:\Users\msft\bazel_rebuild_repro>bazel build project
[32mINFO: [0mLoading complete.  Analyzing...
[1A[K[32mINFO: [0mFound 1 target...
[32mINFO: [0mBuilding...
[1A[KTarget //project:project up-to-date:
  C:/users/msft/appdata/local/temp/_bazel_msft/nlkmo67r/execroot/bazel_rebuild_repro/bazel-out/msvc_x64-fastbuild/bin/project/project.exe
[32mINFO: [0mElapsed time: 1.088s, Critical Path: 0.65s

C:\Users\msft\bazel_rebuild_repro>.\bazel-bin\project\project.exe
C:\users\msft\appdata\local\temp\_bazel_msft\nlkmo67r\execroot\bazel_rebuild_repro\project\main.cc: struct size: 4
C:\users\msft\appdata\local\temp\_bazel_msft\nlkmo67r\execroot\bazel_rebuild_repro\project\lib.cc: struct size: 44

C:\Users\msft\bazel_rebuild_repro>bazel info release
release 0.5.0

### Environment info
* Operating System: Windows 10
Using: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\

* Bazel version (output of `bazel info release`):
release 0.5.0

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
Potential duplicate issues:

https://github.com/bazelbuild/bazel/issues/473 sounds like this issue but was closed, perhaps this is platform dependent?
https://github.com/bazelbuild/bazel/issues/1162 seems to mention includes included from other includes. This is direct inclusion, so I'm not sure if this is a duplicate or not, I think I have the easiest possible version of this (source file directly includes header, libraries even list header in list).

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

=== WORKSPACE ===
<empty>
=== project/BUILD ===
cc_binary(
    name = "project",
    srcs = [
      "main.cc",
    ],
    deps = [
      ":lib",
    ],
)

cc_library(
    name = "lib",
    srcs = [
      "lib.cc"
    ],
    hdrs = [
      "lib.h"
    ],
)
=== project/main.cc ===
#include "project/lib.h" 

#include <stdio.h>

int main() {
  printf("%s: struct size: %zu\n", __FILE__, sizeof(StructInHeader));
  lib_printsize();
  return 0;
}
=== project/lib.h ===
#ifndef PROJECT_LIB_H_
#define PROJECT_LIB_H_

void lib_printsize();

struct StructInHeader {
  int field;
  // Uncomment the below when re-building lib.cc, main.cc will not be rebuilt
  // so the size will mismatch.
  //int fields[10];
};

#endif  // PROJECT_LIB_H_
=== project/lib.cc ===
#include "project/lib.h"
#include <stdio.h>

void lib_printsize() {
  printf("%s: struct size: %zu\n", __FILE__, sizeof(StructInHeader));
}
=== End of files. ===

**Comment by pbos** [comment]
Attaching .zip of minimal repro (sorry for the bad Markdown formatting). Build -> run -> change lib.h's struct size -> add comment to lib.cc -> rebuild -> run.
[bazel_rebuild_repro.zip](https://github.com/bazelbuild/bazel/files/1079806/bazel_rebuild_repro.zip)

**Comment by meteorcloudy** [comment]
Trying to reproduce the problem, but after modifying `lib.h`, `main.cpp` did get rebuilt, the struct size is correct. Am I missing anything? @laszlocsomor Can you also try to reproduce this?

```
pcloudy@pcloudy0-w MSYS ~/workspace/my_tests/bazel_rebuild_repro
$ bazel version
Build label: 0.5.0
Build target: bazel-out/msys_x64-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri May 26 12:12:09 2017 (1495800729)
Build timestamp: 1495800729
Build timestamp as int: 1495800729

pcloudy@pcloudy0-w MSYS ~/workspace/my_tests/bazel_rebuild_repro                                                                       
$ bazel clean                                                                                                                          
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.                     
                                                                                                                                       
pcloudy@pcloudy0-w MSYS ~/workspace/my_tests/bazel_rebuild_repro                                                                       
$ bazel build //project                                                                                                                
INFO: Analysed target //project:project.                                                                                               
INFO: Found 1 target...                                                                                                                
Target //project:project up-to-date:                                                                                                   
  C:/tmp/_bazel_pcloudy/wcw0--l1/execroot/bazel_rebuild_repro/bazel-out/msvc_x64-fastbuild/bin/project/project.exe                     
INFO: Elapsed time: 2.550s, Critical Path: 1.59s                                                                                       
INFO: Build completed successfully, 9 total actions                                                                                    
                                                                                                                                       
pcloudy@pcloudy0-w MSYS ~/workspace/my_tests/bazel_rebuild_repro                                                                       
$ /c/tmp/_bazel_pcloudy/wcw0--l1/execroot/bazel_rebuild_repro/bazel-out/msvc_x64-fastbuild/bin/project/project.exe                     
C:\tmp\_bazel_pcloudy\wcw0--l1\execroot\bazel_rebuild_repro\project\main.cc: struct size: 4                                            
C:\tmp\_bazel_pcloudy\wcw0--l1\execroot\bazel_rebuild_repro\project\lib.cc: struct size: 4                                             
                                                                                                                                     
pcloudy@pcloudy0-w MSYS ~/workspace/my_tests/bazel_rebuild_repro                                                                       
$ vim project/lib.h                                                                                                                    
                                                                                                                                       
pcloudy@pcloudy0-w MSYS ~/workspace/my_tests/bazel_rebuild_repro                                                                       
$ cat project/lib.h                                                                                                                    
#ifndef PROJECT_LIB_H_                                                                                                                 
#define PROJECT_LIB_H_                                                                                                                 
                                                                                                                                       
void lib_printsize();                                                                                                                  
                                                                                                                                       
struct StructInHeader {                                                                                                                
  int field;                                                                                                                           
  // Uncomment the below when re-building lib.cc, main.cc will not be rebuilt                                                          
  // so the size will mismatch.                                                                                                        
  int fields[10];                                                                                                                      
};                                                                                                                                     
                                                                                                                                       
#endif  // PROJECT_LIB_H_                                                                                                              
                                                                                                                                       
pcloudy@pcloudy0-w MSYS ~/workspace/my_tests/bazel_rebuild_repro                                                                       
$ bazel build //project                                                                                                                
INFO: Analysed target //project:project.                                                                                               
INFO: Found 1 target...                                                                                                                
Target //project:project up-to-date:                                                                                                   
  C:/tmp/_bazel_pcloudy/wcw0--l1/execroot/bazel_rebuild_repro/bazel-out/msvc_x64-fastbuild/bin/project/project.exe                     
INFO: Elapsed time: 2.019s, Critical Path: 1.58s                                                                                       
INFO: Build completed successfully, 6 total actions                                                                                    
                                                                                                                                       
pcloudy@pcloudy0-w MSYS ~/workspace/my_tests/bazel_rebuild_repro                                                                       
$ /c/tmp/_bazel_pcloudy/wcw0--l1/execroot/bazel_rebuild_repro/bazel-out/msvc_x64-fastbuild/bin/project/project.exe                     
C:\tmp\_bazel_pcloudy\wcw0--l1\execroot\bazel_rebuild_repro\project\main.cc: struct size: 44                                           
C:\tmp\_bazel_pcloudy\wcw0--l1\execroot\bazel_rebuild_repro\project\lib.cc: struct size: 44                                            
```

**Comment by laszlocsomor** [comment]
Hm, I also fail to repro this, so I'm assuming it's something with @pbos 's setup or system. I didn't even have to update lib.cc:
```
C:\tempdir\gh3202>c:\work\bazel\bazel-msvc-0.5.0-without-jdk-windows-msvc\bazel.exe --nomaster_bazelrc --bazelrc=NUL --output_user_root=c:\tmp5 bui
ld --cpu=x64_windows_msvc --host_cpu=x64_windows_msvc -- //project:project
(...)
Target //project:project up-to-date:
  C:/tmp5/ebfrun7d/execroot/gh3202/bazel-out/msvc_x64-fastbuild/bin/project/project.exe
INFO: Elapsed time: 17.271s, Critical Path: 1.34s

C:\tempdir\gh3202>"C:/tmp5/ebfrun7d/execroot/gh3202/bazel-out/msvc_x64-fastbuild/bin/project/project.exe"
C:\tmp5\ebfrun7d\execroot\gh3202\project\main.cc: struct size: 4
C:\tmp5\ebfrun7d\execroot\gh3202\project\lib.cc: struct size: 4

C:\tempdir\gh3202>vim project\lib.h

C:\tempdir\gh3202>c:\work\bazel\bazel-msvc-0.5.0-without-jdk-windows-msvc\bazel.exe --nomaster_bazelrc --bazelrc=NUL --output_user_root=c:\tmp5 build --cpu=x64_windows_msvc --host_cpu=x64_windows_msvc -- //project:project
(...)
Target //project:project up-to-date:
  C:/tmp5/ebfrun7d/execroot/gh3202/bazel-out/msvc_x64-fastbuild/bin/project/project.exe
INFO: Elapsed time: 1.717s, Critical Path: 1.24s

C:\tempdir\gh3202>"C:/tmp5/ebfrun7d/execroot/gh3202/bazel-out/msvc_x64-fastbuild/bin/project/project.exe"
C:\tmp5\ebfrun7d\execroot\gh3202\project\main.cc: struct size: 44
C:\tmp5\ebfrun7d\execroot\gh3202\project\lib.cc: struct size: 44
```

**Comment by meteorcloudy** [comment]
@laszlocsomor Thanks! Same situation on my workstation, @pbos Can you double check this issue?

**Comment by pbos** [comment]
I'm using:

>bazel version
Build label: 0.5.0
Build target: bazel-out/msys_x64-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri May 26 12:12:09 2017 (1495800729)
Build timestamp: 1495800729
Build timestamp as int: 1495800729

Which I pulled off of choco (`choco install bazel`), per doc. I build using 

I update lib.h using Sublime, the corresponding date stamp is updated when I save this file, and then call `bazel build project` again. Running `blaze --nomaster_bazelrc --bazelrc=NUL --output_user_root=c:\tmp5 build --cpu=x64_windows_msvc --host_cpu=x64_windows_msvc -- //project:project` seems to make no difference (bug still present). I run this directly under `cmd.exe` as user, in case that's a hint, but I just entered bash, and bazel build doesn't trigger a rebuild there directly for me either.

Is there anything else I can dump to help debug? Dump a build config, etc.?

**Comment by pbos** [comment]
Which parts of this should matter btw? Are dependencies figured out entirely inside `bazel` or does the MSVC version matter?

**Comment by laszlocsomor** [comment]
It should make no difference whether you use the MSVC or the MSYS bazel, but just to make sure, could you please try building with [the 0.5.1 msvc version](https://github.com/bazelbuild/bazel/releases/download/0.5.1/bazel-msvc-0.5.1-windows-msvc-x86_64.exe), and do so from cmd.exe (not msys)?

**Comment by pbos** [comment]
Does this replace my existing choco installation or do I run this binary directly?

Env if it's useful:

C:\Users\msft\bazel_rebuild_repro>env
!::=::\
!C:=C:\Users\msft\bazel_rebuild_repro
!ExitCode=00000000
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\msft\AppData\Roaming
BAZEL_PYTHON=C:/python27/python.exe
BAZEL_SH=c:/tools/msys64/usr/bin/bash.exe
ChocolateyInstall=C:\ProgramData\chocolatey
ChocolateyLastPathUpdate=Sun Jun  4 20:53:13 2017
ChocolateyToolsLocation=C:\tools
CLASSPATH=.;
COMMONPROGRAMFILES=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-609PPCQ
COMSPEC=C:\WINDOWS\system32\cmd.exe
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\msft
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_131
LOCALAPPDATA=C:\Users\msft\AppData\Local
LOGONSERVER=\\DESKTOP-609PPCQ
NUMBER_OF_PROCESSORS=4
OneDrive=C:\Users\msft\OneDrive
OS=Windows_NT
PATH=/c/Python27:/c/Python27/Scripts:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/ProgramData/chocolatey/bin:/c/Program Files/Java/jdk1.8.0_131/bin:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/usr/bin:/c/Program Files/Git/cmd:/c/Users/msft/AppData/Local/Microsoft/WindowsApps:/c/ProgramData/chocolatey/lib/msys2:/
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=4e03
ProgramData=C:\ProgramData
PROGRAMFILES=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SYSTEMDRIVE=C:
SYSTEMROOT=C:\WINDOWS
TEMP=/c/Users/msft/AppData/Local/Temp
TMP=/c/Users/msft/AppData/Local/Temp
USERDOMAIN=DESKTOP-609PPCQ
USERDOMAIN_ROAMINGPROFILE=DESKTOP-609PPCQ
USERNAME=msft
USERPROFILE=C:\Users\msft
VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
WINDIR=C:\WINDOWS
TERM=cygwin
HOME=/home/msft

**Comment by pbos** [comment]
Not the issue (but this binary has correct command-line colors, neat):

C:\Users\msft\bazel_rebuild_repro>C:\Users\msft\Desktop\bazel-msvc-0.5.1-windows-msvc-x86_64.exe build project
.
WARNING: C:/users/msft/appdata/local/temp/_bazel_msft/nlkmo67r/external/bazel_tools/tools/cpp/cc_configure.bzl:67:3:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
.
WARNING: C:/users/msft/appdata/local/temp/_bazel_msft/nlkmo67r/external/bazel_tools/tools/cpp/cc_configure.bzl:67:3:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables,eg. VS140COMNTOOLS
.
WARNING: C:/users/msft/appdata/local/temp/_bazel_msft/nlkmo67r/external/bazel_tools/tools/cpp/cc_configure.bzl:67:3:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
.
INFO: Found 1 target...
Target //project:project up-to-date:
  C:/users/msft/appdata/local/temp/_bazel_msft/nlkmo67r/execroot/bazel_rebuild_repro/bazel-out/msvc_x64-fastbuild/bin/project/project.exe
INFO: Elapsed time: 33.053s, Critical Path: 2.53s

C:\Users\msft\bazel_rebuild_repro>C:\Users\msft\Desktop\bazel-msvc-0.5.1-windows-msvc-x86_64.exe build project
WARNING: C:/users/msft/appdata/local/temp/_bazel_msft/nlkmo67r/external/bazel_tools/tools/cpp/cc_configure.bzl:67:3:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
.
WARNING: C:/users/msft/appdata/local/temp/_bazel_msft/nlkmo67r/external/bazel_tools/tools/cpp/cc_configure.bzl:67:3:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables,eg. VS140COMNTOOLS
.
WARNING: C:/users/msft/appdata/local/temp/_bazel_msft/nlkmo67r/external/bazel_tools/tools/cpp/cc_configure.bzl:67:3:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
.
INFO: Found 1 target...
Target //project:project up-to-date:
  C:/users/msft/appdata/local/temp/_bazel_msft/nlkmo67r/execroot/bazel_rebuild_repro/bazel-out/msvc_x64-fastbuild/bin/project/project.exe
INFO: Elapsed time: 0.995s, Critical Path: 0.04s

C:\Users\msft\bazel_rebuild_repro>.\bazel-bin\project\project.exe
C:\users\msft\appdata\local\temp\_bazel_msft\nlkmo67r\execroot\bazel_rebuild_repro\project\main.cc: struct size: 4
C:\users\msft\appdata\local\temp\_bazel_msft\nlkmo67r\execroot\bazel_rebuild_repro\project\lib.cc: struct size: 4

//// Modify lib.h to resize struct, add comment in lib.cc.

C:\Users\msft\bazel_rebuild_repro>C:\Users\msft\Desktop\bazel-msvc-0.5.1-windows-msvc-x86_64.exe build project
WARNING: C:/users/msft/appdata/local/temp/_bazel_msft/nlkmo67r/external/bazel_tools/tools/cpp/cc_configure.bzl:67:3:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
.
WARNING: C:/users/msft/appdata/local/temp/_bazel_msft/nlkmo67r/external/bazel_tools/tools/cpp/cc_configure.bzl:67:3:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables,eg. VS140COMNTOOLS
.
WARNING: C:/users/msft/appdata/local/temp/_bazel_msft/nlkmo67r/external/bazel_tools/tools/cpp/cc_configure.bzl:67:3:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
.
INFO: Found 1 target...
Target //project:project up-to-date:
  C:/users/msft/appdata/local/temp/_bazel_msft/nlkmo67r/execroot/bazel_rebuild_repro/bazel-out/msvc_x64-fastbuild/bin/project/project.exe
INFO: Elapsed time: 2.101s, Critical Path: 1.10s

C:\Users\msft\bazel_rebuild_repro>.\bazel-bin\project\project.exe
C:\users\msft\appdata\local\temp\_bazel_msft\nlkmo67r\execroot\bazel_rebuild_repro\project\main.cc: struct size: 4
C:\users\msft\appdata\local\temp\_bazel_msft\nlkmo67r\execroot\bazel_rebuild_repro\project\lib.cc: struct size: 44

**Comment by laszlocsomor** [comment]
> Not the issue (but this binary has correct command-line colors, neat):

Yes, sorry about that :) see https://github.com/bazelbuild/bazel/issues/3108

> Does this replace my existing choco installation or do I run this binary directly?

No, the link leads to a downloadable bazel binary. No need to install anything; you can run it directly from cmd.exe

> //// Modify lib.h to resize struct, add comment in lib.cc.

Hm, let's try something: could you please do the experiment again, but do *not* modify lib.cc, only edit lib.h, and then exit the editor before running the second build. I want to make absolutely sure that your changes are saved to disk.

Also, not that I think it matters, but let's check: what filesystem are you using? Do you have multiple drives? 

Finally, this:
> ```
> TEMP=/c/Users/msft/AppData/Local/Temp
> TMP=/c/Users/msft/AppData/Local/Temp
> ```

Try doing this please (in cmd.exe):
```
set TEMP=c:\tmp1
set TMP=c:\tmp1
set TMPDIR=c:\tmp1
```

**Comment by pbos** [comment]
I set the env vars, then rebuild. Then editing `lib.h` (insert `#error`) , save (updates file timestamp) and close the editor completely. rebuild still succeeds (no files are rebuilt, so `#error` doesn't trigger).

`.cc` changes are detected, so unless paths are weirdly resolved by the "include-dependency generator" (not actual name), I think the filesystem part is fine.

NTFS, one partition (C:\), this is a Surface Pro 4 that I installed without changing any settings (at least FS settings).

**Comment by pbos** [comment]
Can we debug which include paths bazel think are actually affected by each target?

**Comment by meteorcloudy** [comment]
Oh, the problem is not running under cmd.exe or not, it's setting `TMPDIR` or not. I can also reproduce under MSYS after `unset TMPDIR`. Also adding `--output_user_root=C:/tmp1` will prevent this problem.

**Comment by pbos** [comment]
Oh, maybe my env resetting didn't kick in because it didn't actually restart the bazel master for me. Could it be that `TMPDIR` defaults to something with spaces, and some var expansion struggles with spaces in the TMPDIR name?

I left home so I can't try, but what if you set `"--output_user_root=C:/tmp dir"`?

**Comment by meteorcloudy** [comment]
Nope, adding "--output_user_root=C:/tmp dir" won't trigger the problem. I think @laszlocsomor might know more about this, we'll look into this next week. :)

**Comment by pbos** [comment]
Thanks, let me know if there's something I can do to help debug/verify. Glad to hear this wasn't by design. :)

**Comment by pbos** [comment]
Additional info which might help find the root cause: Not setting `--output_user_root` (or possibly tmpdir, not tested) causes the header dependency check to not trigger at all.

I got home and set `--output_user_root` and for my project (let's call it `foo`) the same build fails with:

```
>bazel --output_user_root=C:\tmp build foo
...
ERROR: C:/users/msft/dev/foo/foo/BUILD:1:1: undeclared inclusion(s) in rule '//foo:foo':
this rule is missing dependency declarations for the following files included by 'foo/foo.cc':
  'C:/users/msft/dev/foo/foo/foo.h'.
```

While the same command without `--output_user_root=C:\tmp` succeeds. I've now fixed my buildfile. :)

**Comment by meteorcloudy** [comment]
I have found the reason of this issue.
On Windows, we set `$TMP` as a `cxx_builtin_include_directory` to ignore files under it during dependency check.
See https://github.com/bazelbuild/bazel/blob/master/tools/cpp/windows_cc_configure.bzl#L361
This is for cuda compilation with nvcc, because nvcc compiler generated intermediate source files under `TMP`, and of course they are not declared in BUILD files.

After unset `TMPDIR`, Bazel would choose `TMP` to be  it's output directory root.
See [here](https://github.com/bazelbuild/bazel/blob/5b8045836fc64a783fa527fd7c4e274ccf14d6ff/src/main/cpp/blaze_util_windows.cc#L317).

The solution could be tell nvcc to generate files under `$TMP/nvcc`, then adding `$TMP/nvcc` as `cxx_builtin_include_directory` instead of `$TMP`

**Comment by pbos** [comment]
Thanks. Make sure that `#include "nvcc/..."` is not excluded from the check (maybe `nvcc` above needs to be `nvcc-bazel-out` or something, unless bazel is putting build intermediates in another subdirectory).

**Comment by meteorcloudy** [comment]
@pbos Yeah, we have a change here: https://bazel-review.googlesource.com/#/c/12174/
