### ISSUE TITLE
Missing/hard to find instructions on how to work with external DLLs.

### ISSUE THREAD

**Issue by pbos** [bazelbuild/bazel#3205]
I can't find instructions on how to work with external binary distributions (pre-built SDKs/binary DLLs). This is a very common usecase especially on Windows, so it should possibly be mentioned inside https://bazel.build/versions/master/docs/windows.html.

I made a `//third_party/foo` `cc_library` for that pre-built library and set `hdrs = glob("foo/*.h")` and `srcs = ["foo/lib/foo.lib"],` which "made it work" (compile), no idea if it's correct. In runtime it now complains that it can't find the dlls, but this doesn't seem to work if I set `--output_user_root` (nor was it probably the right place to begin with).

I tried putting the dlls in the `data` section of `//third_party/foo`, but that doesn't seem to change anything (still not found by project.exe, which depends on `//third_party/foo`) when running the binary from command-line. When doing bazel run I get `ERROR: process-wrapper is not yet implemented on Windows.`.

**Comment by laszlocsomor** [comment]
@meteorcloudy recently updated the [Windows example to show DLL usage](https://github.com/bazelbuild/bazel/tree/c893bf4c39d02bcd881b579d949960ab61567e35/examples/windows/dll). Does that help?

**Comment by pbos** [comment]
It does help, but it would also be nice if the Windows doc above linked to it. Searching for the text string "dll" on the Windows page yields nothing.

**Comment by oquenchil** [comment]
Closing issue since it was documented by @meteorcloudy in [Windows example to show DLL usage](https://github.com/bazelbuild/bazel/tree/c893bf4c39d02bcd881b579d949960ab61567e35/examples/windows/dll).
