### ISSUE TITLE
C++ Missing dependency declarations for C standard library

### ISSUE THREAD

**Issue by durandj** [bazelbuild/bazel#3208]
### Description of the problem / feature request / question:

I installed GCC 7.0.1 on my system and after doing so Bazel is no longer able to build C/C++ libraries that depend on the C standard library. Doing so results in the following error message:

    this rule is missing dependency declarations for the following files included by <rule_name>
        '/usr/lib/gcc/x86_64-linux-gnu/7/include/stdint.h'
        '/usr/lib/gcc/x86_64-linux-gnu/7/include/stddef.h'
        ...

I installed GCC 7.0.1 so that I could compile C++ 14 code however it doesn't seem to matter if I use the C++11, C++14, or any other flag for the compiler.

### If possible, provide a minimal example to reproduce the problem:

The C/C++ code doesn't seem to matter. I made a minimum application that only includes a C header from the standard library and returns 0 in main and the issue continued.

Install GCC 7.0.1 from the test ubuntu-toolchain PPA on Ubuntu 17.0.4 with Bazel 0.5.1 and the issue should manifest.

### Environment info
* Operating System: Ubuntu 17.0.4

* Bazel version (output of `bazel info release`): 0.5.1

###  Have you found anything relevant by searching the web?
I wasn't able to find anything that seemed relevant. Usually this type of issue is from a user defined library. The standard library would be covered already I would think.

**Comment by durandj** [comment]
I updated to Bazel 0.5.2 and the issue seems to have been resolved.

**Comment by mhlopko** [comment]
I like these kinds of bugs :)) Thanks!
