### ISSUE TITLE
Bazel process remains after build complete

### ISSUE THREAD

**Issue by 3ygun** [bazelbuild/bazel#3209]
### Description of the problem / feature request / question:

Originally thought I was having issue #1160 however it may stem in part to Bazel seemly not deallocating/removing the process after the build is complete. Basically, this is what my `htop` looks like long after I believe my build command has/is completed: (e.g. ~1GB of still held memory)

![bazelstuff](https://user-images.githubusercontent.com/5482320/27258007-b0ed8bba-53bb-11e7-8b81-e55706e71cdd.png)

The [ps_mem](https://github.com/pixelb/ps_mem) program lists it as RAM held by java not bazel directly. (e.g. `963.7 MiB + 270.5 KiB = 963.9 MiB	java`)

### If possible, provide a minimal example to reproduce the problem:

I really don't know what is causing this however here is the details/process I'm using.

I'm using bazel to build TensorFlow from source to use in a Android app. The specific build command I'm using can be found [here](https://github.com/jihunhamm/Crowd-ML/blob/master/client/android/Crowd-ML/app/build.gradle#L115) and is executed by Android studio. I also independently built TensorFlow from source following the directions found [here on the TensorFlow Android example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android#building-the-demo-with-tensorflow-from-source)

The above pictured output was remains after running our app with the equivalent of:
```text
bazel build -c opt tensorflow/examples/android:tensorflow_native_libs --crosstool_top=//external:android/crosstool --cpu=<MY_CPU_TYPE> --jobs=1 --host_crosstool_top=@bazel_tools//tools/cpp:toolchain'
```

#### Why do I know the build has/is complete?

The gradle build command has finished and the app has loaded onto my phone with the app working 🌵. The screen shot and output was taken after closing Android Studio and disconnecting the phone.

### Environment info
* Operating System:

Type | Info
--- | ---
System Information | Lenovo y510p running Fedora 25 (8GB RAM, 8 cores)
Using with | open JDK 1.8.0.131

* Bazel version:

```bash
$ bazel version
Build label: 0.5.1- (@non-git)
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jun 12 22:43:46 2017 (1497307426)
Build timestamp: 1497307426
Build timestamp as int: 1497307426
```

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
    - I downloaded the bazel source from the [releases page tag 5.1](https://github.com/bazelbuild/bazel/releases/tag/0.5.1) using `bazel-0.5.1-dist.zip` and followed the instructions on the [bazel.build site](https://bazel.build/versions/master/docs/install-compile-source.html)

**Comment by benjaminp** [comment]
That's [by design](https://bazel.build/versions/master/docs/bazel-user-manual.html#client/server). You can use `--batch` if you don't want the server to stick around.

**Comment by 3ygun** [comment]
@benjaminp Thanks didn't know about that but that makes a lot of sense. Closing as that answers why bazel is still running.
