### ISSUE TITLE
Can not install bazel 0.5.1 on windows

### ISSUE THREAD

**Issue by RastislavKiss** [bazelbuild/bazel#3211]
Hello all,
I'm trying to run im2txt Tensorflow model on my computer, and in descryption I saw I need bazel as a dependency. I am windows user and because I hate compiling from sources, I searched for Bazel binary installer. I installed msys2 required version by instructions on Bazel's windows website, I have also set up variables to bash and msys2 /usr/bin/ directory. To this point okay, for example bash in cmd is normally working, so it looks all is fine. Next, because I have JDK 8 already installed (64bit version), I downloaded
bazel-0.5.1-without-jdk-windows-x86_64.exe
from a releases page, and here is the problem. When I run it, it shows me following error:
bazel-0.5.1-without-jdk-windows-x86_64.exe - Entry Point Not Found
The procedure entry point __locale_ctype_ptr could not be 
located in the dynamic link library msys-2.0.dll. 
OK 

I had similar situation onetime, in that case it was because of more libraryes in system, so I looked now if there is not another msys-2.0.dll, but it isn't. Do you have please some idea how to fix it? Because I no. I searched the net and nothing, also tryed to redownload and reinstall msys2, but it did not work too.

I'm using Windows 7 64 bit.

Thank you in advance.

Best regards

Rastislav

**Comment by laszlocsomor** [comment]
Hey,

Sounds like https://github.com/bazelbuild/bazel/issues/2756.
Could you try downloading the msys-less version of Bazel? It is [bazel-msvc-0.5.1-without-jdk-windows-msvc-x86_64.exe](https://github.com/bazelbuild/bazel/releases/download/0.5.1/bazel-msvc-0.5.1-without-jdk-windows-msvc-x86_64.exe).

**Comment by RastislavKiss** [comment]
Hello,
thank you too much, it works now, there was problem only with Visual studio compiler, where bazel wanted to use amd64 compiler, which my vc++ does not include, but there must probably be only some Bazel configuration, I must learn syntax first. :)

Regards

Rastislav

**Comment by laszlocsomor** [comment]
Cool, I'm glad it works now! Thanks for coming back to let us know :)
