### ISSUE TITLE
cc_library rule should also be able to strip_srcs_prefix

### ISSUE THREAD

**Issue by MarkusTeufelberger** [bazelbuild/bazel#3212]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I automatically generate WORKSPACE rules from github commit hashes and repository links (that way it is not that easily possible to strip extra directories by default from the received tarball). Some libraries (an example is lz4) however put their code into sub-folders.

In general that is nor much of an issue, but https://github.com/lz4/lz4/blob/7bb64ff2b69a9f8367de9ab483cdadf42b4c1b65/lib/lz4hc.c#L74 includes a .c file that I don't really want to expose to users of a BUILD file for lz4. My current solution is to create an additional private "header" to be able to remove the unwanted prefix (https://github.com/MarkusTeufelberger/BBW/blob/c6d0ea14bb039d55f368864a5bb83bcbc112576c/packages/github.com/lz4/lz4/lz4_1_7_5%2B.BUILD#L17).

I would prefer to be able to remove the prefix from files in srcs[...] too, so I could add "lib/lz4.c" in the lz4_hc rule.

### If possible, provide a minimal example to reproduce the problem:

See my BBW repo for lz4. (https://github.com/MarkusTeufelberger/BBW/blob/c6d0ea14bb039d55f368864a5bb83bcbc112576c/packages/github.com/lz4/lz4/lz4_1_7_5%2B.BUILD)

### Environment info
* Operating System:
Linux

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

https://bazel.build/versions/master/docs/be/c-cpp.html#cc_library.strip_include_prefix already exists, I'd like to see strip_srcs_prefix added.

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

Maybe this is a bad idea and how I solved it is actually the correct way (after all, the file is included, similar to a header file in this case) - in that case, please feel free to close this feature request. It just felt really awkward to do it that way.

**Comment by lberki** [comment]
This is another instance of the "I want an include path for my rule only" issue. We should have an attribute for that, but until we do, the best thing I can recommend is `copts=["-I..."]`.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
