### ISSUE TITLE
Error while installing bazel using choco on windows machine

### ISSUE THREAD

**Issue by ajaysaini-sgvu** [bazelbuild/bazel#3221]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I am trying to install bazel using choco on windows machine which in turn tries to install some more dependencies - msys2 and bazel. It throws some error messages for which I am not sure.

> choco install bazel

I executed above command using administrative rights on windows machine. Here are the logs:

> D:\>choco install bazel  --force
> Chocolatey v0.10.7
> [Pending] Removing incomplete install for 'bazel'
> Installing the following packages:
> bazel
> By installing you accept licenses for the packages.
> 
> msys2 v20160719.1.1 (forced) [Approved]
> msys2 package files install completed. Performing other installation steps.
> The package msys2 wants to run 'chocolateyinstall.ps1'.
> Note: If you don't run this script, the installation will fail.
> Note: To confirm automatically next time, use '-y' or consider:
> choco feature enable -n allowGlobalConfirmation
> Do you want to run the script?([Y]es/[N]o/[P]rint): y
> 
> Adding 'C:\ProgramData\chocolatey\lib\msys2' to PATH...
> Installing to 'C:\tools\msys64'
> File appears to be downloaded already. Verifying with package checksum to determ
> ine if it needs to be redownloaded.
> Error - hashes do not match. Actual value was '0E14E2E707629D140EC5BE4889BF14C08
> BB446BD'.
> Downloading msys2 64 bit
>   from 'http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20160719.tar.xz'
> Progress: 100% - Completed download of C:\Users\ajaysaini\AppData\Local\Temp\msy
> s2\20160719.1.1\msys2-base-x86_64-20160719.tar.xz (3.82 MB).
> Download of msys2-base-x86_64-20160719.tar.xz (3.82 MB) completed.
> Error - hashes do not match. Actual value was '8FEAF6EBFEF6612F5D38E3357BFD536A3
> 2708B79'.
> ERROR: Checksum for 'C:\Users\ajaysaini\AppData\Local\Temp\msys2\20160719.1.1\ms
> ys2-base-x86_64-20160719.tar.xz' did not meet '4FF1090B143DEAEDED088146E04503B9A
> 3C15FDB' for checksum type 'SHA1'. Consider passing the actual checksums through
>  with --checksum --checksum64 once you validate the checksums are appropriate. A
>  less secure option is to pass --ignore-checksums if necessary.
> The install of msys2 was NOT successful.
> Error while running 'C:\ProgramData\chocolatey\lib\msys2\tools\chocolateyinstall
> .ps1'.
>  See log for details.
> 
> bazel v0.5.1 (forced) [Approved]
> bazel package files install completed. Performing other installation steps.
> The package bazel wants to run 'chocolateyinstall.ps1'.
> Note: If you don't run this script, the installation will fail.
> Note: To confirm automatically next time, use '-y' or consider:
> choco feature enable -n allowGlobalConfirmation
> Do you want to run the script?([Y]es/[N]o/[P]rint): y
> 
> Content of C:\ProgramData\chocolatey\lib\bazel\tools\params.txt:
> https://github.com/bazelbuild/bazel/releases/download/0.5.1/bazel-msvc-0.5.1-win
> dows-msvc-x86_64.zip
> ce2936c6115ac940ef75cdc780d63cc7558b7e8d486821806c9e057075ace5cb
> 
> url:  https://github.com/bazelbuild/bazel/releases/download/0.5.1/bazel-msvc-0.5
> .1-windows-msvc-x86_64.zip
> hash: ce2936c6115ac940ef75cdc780d63cc7558b7e8d486821806c9e057075ace5cb
> File appears to be downloaded already. Verifying with package checksum to determ
> ine if it needs to be redownloaded.
> Error - hashes do not match. Actual value was 'FA126CC2338E38CE09E080925EA106B36
> 7212AB7A2A2A73DB3D8783187DB1305'.
> Downloading bazel 64 bit
>   from 'https://github.com/bazelbuild/bazel/releases/download/0.5.1/bazel-msvc-0
> .5.1-windows-msvc-x86_64.zip'
> Progress: 70% - Saving 139.37 MB of 198.33 MB                                  E
> RROR: The remote file either doesn't exist, is unauthorized, or is forbidden for
>  url 'https://github.com/bazelbuild/bazel/releases/download/0.5.1/bazel-msvc-0.5
> .1-windows-msvc-x86_64.zip'. Exception calling "Read" with "3" argument(s): "Rec
> eived an unexpected EOF or 0 bytes from the transport stream."
> The install of bazel was NOT successful.
> Error while running 'C:\ProgramData\chocolatey\lib\bazel\tools\chocolateyinstall
> .ps1'.
>  See log for details.
> 
> Chocolatey installed 0/2 packages. 2 packages failed.
>  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
> 
> Failures
>  - msys2 (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\msys2\
> tools\chocolateyinstall.ps1'.
>  See log for details.
>  - bazel (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\bazel
> \tools\chocolateyinstall.ps1'.
>  See log for details.
> 
> D:\>

### Environment info
* Operating System: Windows 64 bit 

###  Have you found anything relevant by searching the web?
Nope

**Comment by laszlocsomor** [comment]
@petemounce

**Comment by petemounce** [comment]
It looks like you suffered network issues during the downloads. Does this happen if you retry, and/or try a different network?

Log bits that make me think this:
```
Progress: 70% - Saving 139.37 MB of 198.33 MB E
RROR: The remote file either doesn't exist, is unauthorized, or is forbidden for
url 'https://github.com/bazelbuild/bazel/releases/download/0.5.1/bazel-msvc-0.5
.1-windows-msvc-x86_64.zip'. Exception calling "Read" with "3" argument(s): "Rec
eived an unexpected EOF or 0 bytes from the transport stream."
```

**Comment by ajaysaini-sgvu** [comment]
Yep, it was network issue. Thanks a lot :-)
