### ISSUE TITLE
Provide original path of artifact

### ISSUE THREAD

**Issue by mwoehlke-kitware** [bazelbuild/bazel#3227]
Since Bazel can't install things by itself, I have been working on bolting on a kludge to do it. One of the issues I run into is:

```
install_files(
    ...
    files = [
        "src/foo/example.h",
        "src/bar/example.h",
    ]
)
```

Now, I need to install these to `foo/example.h` and `bar/example.h`. Breaking up the list into multiple `install` directives would be superfluous repetition at best; in some cases, the headers may be coming from elsewhere (`transitive_headers` being a worst case).

The problem is, while Bazel knows at the point that it first sees a path that ultimately creates the artifact object that a file is named like e.g. `src/foo/example.h`, this information is lost to Skylark.

I can generally figure out what this "partial path" should be, but *only* if the artifact originates in the same context as the rule that needs to know; otherwise, the user has to manually specify a context, which leads to DRY violations.

Please make the original partial path available in Skylark.

See the argument at robotlocomotion/drake#6347 for additional context.

**Comment by brandjon** [comment]
I'm not clear on what is meant by "original path" and "context" here.

At analysis time, you can get the path to a file with the `File.path` field. At loading time (i.e. in a macro), you don't have full path information, though `native.package_name()` gets you a piece of it.

If you're trying to get a source file's directory during rule analysis, you could conceivably take the path of a source file's `File` object, but that will break if the source file is a generated file.

If you're trying to modify the source directory, that's not really a supported use case, but you might be able to do it with a repository rule.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
