### ISSUE TITLE
bazel compile problem 'linux/magic.h: No such file or directory

### ISSUE THREAD

**Issue by yuhow** [bazelbuild/bazel#3230]
### Description of the problem / feature request / question:
ERROR: /ban/yohchang/practice/tensorflow/bazel-0.5.1-dist/src/main/cpp/BUILD:7:1: C++ compilation of rule '//src/main/cpp:blaze_util' failed: gcc failed: error executing command 
  (cd /tmp/bazel_tC149834/out/execroot/bazel-0.5.1-dist && \
  exec env - \
    LD_LIBRARY_PATH=:/volp1/quota_ctrl/yohchang/practice/tensorflow/local_install/gcc-4.8.1/lib:/volp1/quota_ctrl/yohchang/practice/tensorflow/local_install/gcc-4.8.1/lib64/:/volp1/quota_ctrl/yohchang/practice/tensorflow/local_install/mpc-0.8.1/lib:/volp1/quota_ctrl/yohchang/practice/tensorflow/local_install/gmp-4.3.2/lib:/volp1/quota_ctrl/yohchang/practice/tensorflow/local_install/mpfr-2.4.2/lib:/volp1/quota_ctrl/yohchang/practice/tensorflow/local_install/isl-0.11/lib:/volp1/quota_ctrl/yohchang/practice/tensorflow/local_install/cloog-0.18.0/lib \
    PATH=/volp1/quota_ctrl/yohchang/practice/tensorflow/local_install/binutils-2.28:/sc10/ap/sivl/2005.09-SP1-1/bin:/vol0/sys/myPrint/print_execd-6.2u4/bin/lx24-amd64:/sc10/ap/linux/bin:/ban/yohchang/:.:/bin:/usr/ucb:/usr/ccs/bin:/usr/dt/bin:/usr/openwin/bin:/usr/local/bin:/usr/ucb/bin:/usr/bin:/usr/sbin:/bin/X11:/usr/X11R6/bin:/sc10/ap/xv/sun:/ban/wchuang/tool:/sc10/ap/tool:/vol0/sys/tool:/usr/bin:/volp1/quota_ctrl/yohchang/practice/tensorflow/local_install/gcc-4.8.1/bin \
    PWD=/proc/self/cwd \
  /volp1/quota_ctrl/yohchang/practice/tensorflow/local_install/gcc-4.8.1/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/volp1/quota_ctrl/yohchang/practice/tensorflow/local_install/gcc-4.8.1/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/local-opt/bin/src/main/cpp/_objs/blaze_util/src/main/cpp/blaze_util_linux.d '-frandom-seed=bazel-out/local-opt/bin/src/main/cpp/_objs/blaze_util/src/main/cpp/blaze_util_linux.o' -DBLAZE_OPENSOURCE -iquote . -iquote bazel-out/local-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/local-opt/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c src/main/cpp/blaze_util_linux.cc -o bazel-out/local-opt/bin/src/main/cpp/_objs/blaze_util/src/main/cpp/blaze_util_linux.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
src/main/cpp/blaze_util_linux.cc:18:25: fatal error: linux/magic.h: No such file or directory
 #include "linux/magic.h"
                         ^
compilation terminated.

Don't really know how to solve this...
I try to use google to find some information. It tells me that maybe this problem is caused by my old kernel. But I don't really know what I can do next.

### Environment info
* Operating System:
Red Hat Enterprise Linux Server release 5.7 (Tikanga)
ldd (GNU libc) 2.5
gcc-4.8.1 (I install this compiler additionally.)

other information: 
I can't use yum or any other on-line update to install package...
So I download source code and compile them on my redhat computer.

* Bazel version (output of `bazel info release`):
0.5.1-dist

If you need any other information, please let me know!
Thanks for help!

**Comment by philwo** [comment]
I don't think this is a Bazel bug, but more like a usage question (and possibly an issue in our documentation, which could be improved in this regard).

Could you please ask your question just as you wrote it here on StackOverflow? I'll also try to find someone on the team who is more experienced with this kind of setup to answer it then.

I'm closing this issue here, but please post the link to your question as a comment here when you created it. Thanks!

**Comment by yuhow** [comment]
my post on stackoverflow:
https://stackoverflow.com/questions/44687949/bazel-compile-error-linux-magic-h-no-such-file-or-directory
