### ISSUE TITLE
Add a bazel info key that prints auto-detected local resources

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#3231]
That makes it easier to debug issues.

**Comment by neel-desh** [comment]
Hello, I would love to pick it up, but i would need some help with the issue, would love if someone could fill in the description

**Comment by ayushanand308** [comment]
@ulfjack is this still up for grab?

**Comment by meisterT** [comment]
@ayushanand308 feel free to submit a PR for this

cc @wilwell

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by meisterT** [comment]
I think this is still helpful - and up for grabs.

**Comment by Stoozy** [comment]
I'll take it. I'm new here so I'll need a brief description on what to do.

**Comment by Stoozy** [comment]
To be more specific, I need to know what is meant by 'auto-detected local resources'

**Comment by meisterT** [comment]
See https://cs.opensource.google/bazel/bazel/+/refs/heads/master:src/main/java/com/google/devtools/build/lib/actions/LocalHostCapacity.java;l=58;drc=e715e34d1b09261be364427dbb1cb82e92a1420f where we detect the local CPU and RAM resources.

This is where I last added an InfoItem: https://github.com/bazelbuild/bazel/commit/a1651871510e2df25851a4bd1ce4980800545e53

**Comment by Stoozy** [comment]
do we want this to be hidden or visible to `bazel info` ?

**Comment by Stoozy** [comment]
Ok I opened a PR, I also signed the CLA so the checks need to be run again. #18287

**Comment by HimanshuKhatarkar** [comment]
This Still shows open in the Status. If this really is the case please let me help on this.

**Comment by meisterT** [comment]
This was fixed in https://github.com/bazelbuild/bazel/commit/f09ee6546c95072c05a77da09a6ed07179206e3b
