### ISSUE TITLE
bazel fetch with --keep_going doesn't correctly report overall fetch error (via exit code or final message)

### ISSUE THREAD

**Issue by sethkoehler** [bazelbuild/bazel#3234]
### Description of the problem / feature request / question:

When running bazel fetch with --keep_going (to see all errors), errors are printed, but the final message printed is:

"INFO: All external dependencies fetched successfully."

and the exit code (e.g., via "echo $?") is 0, indicating no error.  This makes it difficult to use in a script to both see all errors but stop further actions.

Note that running bazel build, I see these two final messages:

ERROR: command succeeded, but there were loading phase errors.
INFO: Elapsed time: 0.667s, Critical Path: 0.01s

And the exit code is nonzero (as desired).

### If possible, provide a minimal example to reproduce the problem:
Attached is a hello-world example with a fake dependency that is intentionally not present in the WORKSPACE file.  Running "bazel fetch --keep_going ... && echo 'hi'" should exhibit the issue.

[helloworld_keep_going.tar.gz](https://github.com/bazelbuild/bazel/files/1092016/helloworld_keep_going.tar.gz)

### Environment info
* Operating System:
Ubuntu 14.04

* Bazel version (output of `bazel info release`):
release 0.5.1

###  Have you found anything relevant by searching the web?
Sadly nope.

**Comment by ghasemloo** [comment]
Also the exit codes for bazel fetch should probably be added to Bazel documentation:
https://bazel.build/versions/master/docs/bazel-user-manual.html#what-exit-code-will-i-get

It seems that the exit code should be 3 for this case as 3 is used for partial success. 

(or should it be a separate exit code to make it easier to interpret it?)

**Comment by dslomov** [comment]
Being fixed here: https://bazel-review.googlesource.com/c/bazel/+/32114
