### ISSUE TITLE
Misleading "The include path '[...]' references a path outside of the execution root." when compiler is not available

### ISSUE THREAD

**Issue by tomasz-wiszkowski** [bazelbuild/bazel#3239]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

Bazel throws misleading error messages about include path being outside of execution root if custom compiler is specified, but not present in the system.

### If possible, provide a minimal example to reproduce the problem:

1) create a cc_library with option copts = [ "-I/usr/include" ]
2) specify in bazel.rc: build --client_env=CC=/bin/false (or a path to inexisting binary)
3) execute bazel build //path/to:rule

this will give results such as:

in cc_library rule @workspace//path/to:rule: The include path '/usr/include' references a path outside of the execution root.

### Environment info
* Operating System:
linux / goobuntu Ubuntu 14.04.5 LTS, x86_64

* Bazel version (output of `bazel info release`):
release 0.5.1

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

no info, just people struggling with similar problems

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

@ender

**Comment by yiakwy** [comment]
a bug

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
