### ISSUE TITLE
Migrate binary ints to booleans

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3240]
### Description of the problem / feature request / question:

Triggered by https://groups.google.com/forum/#!topic/bazel-discuss/M_LCQuLk-BQ, this shall be the central part to collect all parts where ints are used in binary form only. Then we can discuss how to fix these.

- [ ] cc_binary: `linkshared`
- [ ] cc_binary: `linkstatic`
- [ ] cc_binary: `stamp`
- [ ] genrule: `executable`
- [ ] genrule: `local`
- [ ] genrule: `output_to_bindir`

**Comment by abergmeier-dsfishlabs** [comment]
IMO `linkshared` and `linkstatic` should be deprecated and replaced by a `linking` list attr. The values could be something more descriptive - possibly a rule name (e.g. `//linking:for_shared`).

**Comment by laurentlb** [comment]
`linkstatic` and `linkstared` are marked as boolean in the code. We should have to tell Bazel that `True` and `False` are allowed for boolean values.
`stamp` has type tristate. Maybe we could use `True`, `False`, `None`.

**Comment by abergmeier-dsfishlabs** [comment]
> linkstatic and linkstared

Does it make sense to have both? Aren't they mutually exclusive?

**Comment by laurentlb** [comment]
That's a separate discussion (design of C++ rules). I think this bug should be for allowing booleans where it makes sense, not specific to any rule.

**Comment by lberki** [comment]
They are mostly orthogonal `linkshared` controls whether you get a shared library or a binary and `linkstatic` controls whether dependencies are linked dynamically or statically.

**Comment by abergmeier-dsfishlabs** [comment]
Merged `genrule`

**Comment by aiuto** [comment]
@laurentlb @lberki Does this belong in Team:starlark or Team:cpp?
I'm untriaging for now and whomever picks it up can decide.

**Comment by laurentlb** [comment]
We can leave it in the Starlark label if you prefer, but I actually expect the rules teams to work on this (e.g. as part of a documentation fixit).

**Comment by lberki** [comment]
Is this a documentation issue? I thought what's called for is actual migration of rules in BUILD files and then in rule definitions.

**Comment by laurentlb** [comment]
https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary.linkshared
`linkshared`, `linkstatic`, `executable`, `local`, and `output_to_bindir` are all marked as booleans, but with default value 0 or 1. I think that's just a documentation issue.

(stamp cannot be converted to boolean, because it allows -1)

**Comment by mhlopko** [comment]
We're approaching a state when ping ponging it around costs more than fixing it. Let me create a change for this.

**Comment by lberki** [comment]
Ok, I misunderstood it then. Nm.
