### ISSUE TITLE
Android: android_sdk_repository should not allow incompatible api_level and build_tools_version

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3241]
### Description of the problem / feature request / question:

If you mix the wrong version of aapt and android.jar, you'll sometimes get access violation errors on Windows. There's nothing preventing the user from doing that. `android_sdk_repository` should disallow incompatible `api_level` and `build_tools_version` values.

### If possible, provide a minimal example to reproduce the problem:

The culprit was a bad `android_sdk_repository` rule in my workspace:
```
android_sdk_repository(
    name = "androidsdk",
    path = "c:\\Users\\laszlocsomor\\AppData\\Local\\Android\\sdk",
    api_level = 26,
    build_tools_version = "24.0.3",
)
```

What this resulted in was Bazel symlinking (actually copying, since I'm on Windows) the 24.0.3 aapt.exe into `bazel-out\host\bin\external\androidsdk\aapt_binary.exe`, but using it with `external\androidsdk\platforms\android-26\android.jar`, which sometimes resulted in either a crash with a Windows popup saying "aapt.exe stopped working: [close] or [debug]", or just an exit code -1073741819 (which is 0xc0000005 = `ACCESS_VIOLATION`).

With trial and error I found some nasty non-deterministic behavior: sometimes aapt would crash if I added the "-v" flag, sometimes it would crash without and wouldn't with the flag.

Repro:

I have a dummy manifest file `c:\tempdir\aapt-cmd\AndroidManifest.xml`:
```
<?xml version="1.0" encoding="utf-8"?><manifest xmlns:android="http://schemas.android.com/apk/res/android" package="null"></manifest>
```

24.0.3 aapt with 26 android.jar:
```
c:\tempdir\aapt-cmd>c:\Users\laszlocsomor\AppData\Local\Android\sdk\build-tools\24.0.3\aapt.exe package -f -I c:\Users\laszlocsomor\AppData\Local\Android\sdk\platforms\android-26\android.jar -M AndroidManifest.xml --non-constant-id -0 apk
(crash)

c:\tempdir\aapt-cmd>c:\Users\laszlocsomor\AppData\Local\Android\sdk\build-tools\24.0.3\aapt.exe package -v -f -I c:\Users\laszlocsomor\AppData\Local\Android\sdk\platforms\android-26\android.jar -M AndroidManifest.xml --non-constant-id -0 apk
(success)
```

But sometimes it was the opposite: crash with "-v", fine without.

Other combinations (24.0.3 aapt with jar 25, 26.0.0 aapt with jar 25, 26.0.0 aapt with jar 26) work fine in both cases.

### Environment info
* Operating System: Windows 10

* Bazel version (output of `bazel info release`): heavily hacked custom bazel, but you can repro this without it

**Comment by laszlocsomor** [comment]
Actually, this is pretty nasty, so i'm going to put P1 back on it. Feel free to overrule ;)

**Comment by laszlocsomor** [comment]
@dslomov FYI

**Comment by laszlocsomor** [comment]
@ahumesky : Do you know whom we could contact from the Android Platforms Team? I'm wondering if aapt could detect that the user (or the build tool) passed a wrong .jar file to it and report a meaningful error.

**Comment by ahumesky** [comment]
If it works with the latest version of the build tools, then I'm not sure there's anything for the Android folks to do (it already works). In general, users should use the latest version of the build tools, and `build_tools_version` is now optional: `android_sdk_repository` will auto detect the latest version of the build tools installed in the SDK, so all you have to do is update the tools in the SDK manager. (`build_tools_version` is still provided for hermeticism)

**Comment by aj-michael** [comment]
@corbinrsmith-work are you aware of when AAPT chokes like this? I've never seen this before.

**Comment by aj-michael** [comment]
I tried building //examples/android/java/bazel:hello_world on linux with build tools 24.0.3 with both android 25 and android 26

```
$ bazel build --android_sdk=@androidsdk//:sdk-25 //examples/android/java/bazel:hello_world
INFO: Found 1 target...
Target //examples/android/java/bazel:hello_world up-to-date:
  bazel-bin/examples/android/java/bazel/hello_world_deploy.jar
  bazel-bin/examples/android/java/bazel/hello_world_unsigned.apk
  bazel-bin/examples/android/java/bazel/hello_world.apk
INFO: Elapsed time: 27.906s, Critical Path: 27.31s

$ bazel build --android_sdk=@androidsdk//:sdk-26 //examples/android/java/bazel:hello_world
INFO: Found 1 target...
ERROR: /usr/local/google/home/ajmichael/.cache/bazel/_bazel_ajmichael/0867dbc2acf946964ff0690cf8249ab9/external/androidsdk/com.android.support/BUILD:4411:1: Validating Android resources for @androidsdk//com.android.support:support-core-utils-25.0.0 failed: Process exited with status 1 [sandboxed].
Jun 22, 2017 11:17:34 AM com.google.devtools.build.android.AndroidResourceValidatorAction main
SEVERE: Unexpected
com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        bazel-out/host/bin/external/androidsdk/aapt_binary package -f --no-crunch --no-version-vectors -I external/androidsdk/platforms/android-26/android.jar -M /tmp/resource_validator_tmp3083361962531526151/manifest-aapt-dummy/AndroidManifest.xml -m -J /tmp/resource_validator_tmp3083361962531526151/generated_resources --output-text-symbols /tmp/resource_validator_tmp3083361962531526151/generated_resources --debug-mode --non-constant-id -0 apk
Error Code:
        139

        at com.google.devtools.build.android.AndroidResourceProcessor.runAapt(AndroidResourceProcessor.java:379)
        at com.google.devtools.build.android.AndroidResourceValidatorAction.main(AndroidResourceValidatorAction.java:128)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$2.call(ResourceProcessorBusyBox.java:59)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:143)

Exception in thread "main" com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        bazel-out/host/bin/external/androidsdk/aapt_binary package -f --no-crunch --no-version-vectors -I external/androidsdk/platforms/android-26/android.jar -M /tmp/resource_validator_tmp3083361962531526151/manifest-aapt-dummy/AndroidManifest.xml -m -J /tmp/resource_validator_tmp3083361962531526151/generated_resources --output-text-symbols /tmp/resource_validator_tmp3083361962531526151/generated_resources --debug-mode --non-constant-id -0 apk
Error Code:
        139

        at com.google.devtools.build.android.AndroidResourceProcessor.runAapt(AndroidResourceProcessor.java:379)
        at com.google.devtools.build.android.AndroidResourceValidatorAction.main(AndroidResourceValidatorAction.java:128)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$2.call(ResourceProcessorBusyBox.java:59)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:143)
Use --strategy=AndroidResourceValidator=standalone to disable sandboxing for the failing actions.
Target //examples/android/java/bazel:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.363s, Critical Path: 1.78s
```

The error is in the processing of the 25.0.0 support libraries.

**Comment by aj-michael** [comment]
It appears this was a change between aapt 24.0.3 and 25.0.0

**Comment by aj-michael** [comment]
I've thought about this for a bit, and I think that the general problem here is not something that Bazel can solve. We don't know when an api level requires newer build tools, and even if we did and we baked that information into the Bazel binary, when a new Android api level comes out we wouldn't be able to update the old Bazel release with the minimum build tools version needed for the new SDK level.

Feel free to reopen if you have an idea of how Bazel would be able to detect this.
