### ISSUE TITLE
Skylark Library filenames conflict on macOS

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#3244]
The problem is that when we generate the Skylark Library, there is both a [`provider.html`](https://bazel.build/versions/master/docs/skylark/lib/provider.html) and a [`Provider.html`](https://bazel.build/versions/master/docs/skylark/lib/Provider.html). Because HFS+ (and presumably the upcoming APFS) is by default case-insensitive, we get an error on macOS when generating redirects.

The ideal fix for this is to either improve the directory structure of the Skylark Library to separate modules and types or have a single page for both the provider module and the Provider type.

Because of this problem, the Bazel website cannot le built on macOS https://github.com/bazelbuild/bazel-website/issues/28

**Comment by steren** [comment]
cc @michelleirvine

**Comment by steren** [comment]
Note that a workaround to serve the site on a mac is to delete the line `"skylark/lib/provider.html"` in `redirects.bzl`. Just do not forget to revert this change before pushing to the repo.

**Comment by meisterT** [comment]
This is no longer a problem.
