### ISSUE TITLE
Split our mobile app tutorial into Android and iOS getting started, remove backend part

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#3245]
Our [mobile app tutorial](https://bazel.build/versions/master/docs/tutorial/app.html) is both building an Android and an iOS app, in addition to a backend.

We should take a different approach and do per-language getting started guides.

this tutorial should thus be split into two, in order to create "Bazel for Android" and "Bazel for iOS" guides.

Each guide should: 
* link to the installation pages (install on macOS in case of the iOS gudie)
* link to the relevant existing IDE plugins: Our IntelliJ plugin in case of Android, and Tulsi project generator in case of iOS.
* document as much as possible the migration process (From a Gradle Android Studio project for Android, from a regular xCode project with cocoapod dependencies for iOS)

We should remove the backend part because backend languages are better covered in otehr getting started (Java, and later Python). Also "deploy to App Engine" is not something we want to push forward as Bazel is not a continuous deployment tool.

**Comment by steren** [comment]
Also, the iOS tutorial should not use the Objective C rules but https://github.com/bazelbuild/rules_apple instead, as these are the new recommended rules for iOS development.

**Comment by spomorski** [comment]
The iOS tutorial has already been updated to use the new rules in
cl/158296117. We're waiting for the site to unfreeze so the updated version
can be published.

**Comment by steren** [comment]
I see this had been done:

- https://docs.bazel.build/versions/master/tutorial/android-app.html
- https://docs.bazel.build/versions/master/tutorial/ios-app.html

I suppose we can close the issue
