### ISSUE TITLE
Toolchains support for Bazel fetch

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#3246]
As part of the toolchains work (ref #2219), it should be possible to use "bazel fetch" to fetch all toolchain-related repositories as well as other fetched repositories.

One option is to unconditionally fetch all toolchains, another is to add platform configuration to fetch and only fetch the required toolchains.

**Comment by katre** [comment]
There are two ways to handle this:

1. Special case FetchCommand to check a flag and include all registered toolchains in the query used to fetch targets. This is pretty easy to implement but is a bit of a hack on how FetchCommand works
2. Add a flag that causes targets to depend on all toolchains they could possibly use, ignoring constraints, rather than just one. This is much cleaner (since it only pulls in toolchains that could be used by the targets being fetched), but would have impact on rebuilds (since we're changing the actual configured target graph, and would need to invalidate it twice: once before the query, and once after).

What do you think, @kchodorow?

**Comment by beasleyr-vmw** [comment]
> One option is to unconditionally fetch all toolchains, another is to add platform configuration to fetch and only fetch the required toolchains.

Could this be extended beyond toolchains to build configuration and remote repository rules? 

Context: I would very much like for `fetch` to support build configuration. My products consume binary artifacts, and we use build configuration (`--define=buildtype=x` atm) to download binary artifacts corresponding to the product's configuration. (Ex: If I'm compiling with aggressive optimization flags, I want to download/use artifacts that were built with similarly aggressive opt flags.) Today, I cannot prefetch _just_ the aggressively optimized artifacts (or, conversely, no optimization+extra debugging artifacts) for my product.

**Comment by aiuto** [comment]
@katre  Is this still a request, or is it obsolete now?

**Comment by katre** [comment]
I haven't heard of any further requests, but I don't know what the actual use-case of `bazel fetch` is these days.

Let's close this and if someone still needs it, they can comment to explain why and what the use case is.

**Comment by guw** [comment]
What is the recommended way to fetch all repositories for toolchains regardless of the platforms? I am looking for a way to ensure all repository download URLs are correct/working.

**Comment by fmeum** [comment]
> What is the recommended way to fetch all repositories for toolchains regardless of the platforms? I am looking for a way to ensure all repository download URLs are correct/working.

With Bzlmod, you can use `bazel fetch --all` to do this.
