### ISSUE TITLE
Implement chunking for the HTTP rest remote cache

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#3250]
This is split off from #2680.

**Comment by brunobowden** [comment]
Fixing this should allow building TensorFlow with a remote cache. Right now, it tries to transfer a blob which is just over the 512MB limit, generating this error:

```Caused by: java.lang.IllegalArgumentException: Upload: maximum blob size exceeded: 553666K > 524288K.```

thanks to @ola-rozenfeld for helping me find this

**Comment by ola-rozenfeld** [comment]
Ulf, if you haven't started on this, I can take it. Should be straightforward.

**Comment by ulfjack** [comment]
I haven't. I'm still fully loaded with other stuff.

**Comment by ulfjack** [comment]
On that note - I think we need to also change the layout of the files; right now we dump everything in a single directory, which is going to be a performance problem at some point. We should mirror what git is doing for its CAS. I think we should also put the action key -> action result mapping into a different directory.

**Comment by ola-rozenfeld** [comment]
Wait, we create a different directory for each action, isn't that enough? Or you meant splitting the input files between directories?
> I think we should also put the action key -> action result mapping into a different directory.
Currently we don't put this mapping on disk at all, it only exists in memory.

**Comment by ulfjack** [comment]
Uhm, what? Are you talking about this bug or the other one?

**Comment by ola-rozenfeld** [comment]
This one. I guess I did not understand which files are you referring to. Same for action key -> action result mapping. Can you please clarify?

**Comment by ulfjack** [comment]
The HTTP Rest cache uses /[hashsum] for all the files, while Git uses /[first_two_chars_of_hashsum]/[rest_of_hashsum] (or something like that). By default, a normal WebDAV webserver (both NGINX and Apache2 with normal configuration) puts all the files into a single directory, which can grow very large.

As far as I can tell, it uses /[hashsum] for the action mapping, except the action mapping isn't a content addressed file.

**Comment by ola-rozenfeld** [comment]
Oh, OK. Yes, you're right, we just use the digest for everything --
commands, action keys, tree nodes, etc. It will create a lot of files.

**Comment by benjaminp** [comment]
Now that there's a been a release of Hazelcast containing the fix for hazelcast/hazelcast#10878, would it make sense to enable chunked encoding and streaming for the rest cache interface?

**Comment by ulfjack** [comment]
Works for me.

**Comment by benjaminp** [comment]
https://bazel-review.googlesource.com/c/bazel/+/17030 implements streaming uploads.
