### ISSUE TITLE
Clarify situation: ObjectiveC rules or rules_apple?

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#3252]
[rules_apple](https://github.com/bazelbuild/) seems to be what we recommend to iOS users today, however, Bazel still contains and documents the [ObjectiveC rules](https://bazel.build/versions/master/docs/be/objective-c.html)

Let's use this GH issue to track the status of this situation and fix it.

We should make sure users looking for iOS Bazel support easily end up finding the best option.
Also, we should deprecate (or at least hide) things when there is duplication.

Are rules_apple entirely covering the same features as the Objective C rules?
What is the plan?

**Comment by steren** [comment]
We will update the iOS tutorial to use rules_apple, this is tracked in https://github.com/bazelbuild/bazel/issues/3245

**Comment by DmytroLapshyn** [comment]
But on the other hand, the apple_rules docs sometimes explicitly advise on using the native Objective C rules, e.g.:

https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-ios.md
> A static framework is bundled like a dynamic framework except that the embedded binary is a static library rather than a dynamic library. It is intended to create distributable static SDKs or artifacts that can be easily imported into other Xcode projects; it is specifically not intended to be used as a dependency of other Bazel targets. **For that use case, use the corresponding objc_library targets directly.**

**Comment by jmmv** [comment]
Closing due to staleness and because a lot of things have changed in this area since this was originally filed.
