### ISSUE TITLE
Create a "Bazel for Java" guide

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#3253]
We decided to have ecosystem specific intro pages: 

For Java, we should have one page that contains:

1. a link to the install page 
2. introduction material:
  - presenting the main Java rules
  - explaining how to handle package dependencies from artifact repositories
  - link to our IntelliJ plugin
3. an hello world Java tutorial (that can be our existing Java tutorial)
4. a Maven migration guide

**Comment by jin** [comment]
Available at https://docs.bazel.build/versions/master/bazel-and-java.html
