### ISSUE TITLE
Create a "Bazel for C++" guide

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#3254]
We decided to have ecosystem specific intro pages:

For C++, we should have one page that contains:

1. a link to the install page 
2. introduction material:
 - presenting the main C++ rules
 - explaining how to handle package dependencies from artifact repositories
 - link to our CLion plugin
3. an hello world C++ tutorial (that can be our existing Java tutorial)
4. a [CMake](https://cmake.org/) migration guide

**Comment by spomorski** [comment]
We now have these pages:

https://docs.bazel.build/versions/master/bazel-and-cpp.html

https://docs.bazel.build/versions/master/cpp-use-cases.html

Closing this issue.
