### ISSUE TITLE
Document Bazel IDE support

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#3257]
Create a documentation page that lists the IDEs supported by Bazel, this includes:
* IntelliJ, Clion and Android Studio
* XCode
* Eclipse (experimental)
* Visual Studio Code
* Atom
* Vim

For each of them, sow:
* its status (stable, experimental...), 
* a link to install page
* a link to the dedicated plugin doc (if it exists)
* a short list of features to expect

The page should list Google-authored IDE plugins, but also others if they are relevant.

**Comment by abergmeier-dsfishlabs** [comment]
Sublime should also come soonish.

**Comment by steren** [comment]
I see we now have a 'IDE integration' page: https://docs.bazel.build/versions/master/ide.html

However, it could contain more info and in particular links. I'll see if I can submit a PR

**Comment by jin** [comment]
Closing this as we have an IDE page now.
