### ISSUE TITLE
android support is broken with build tools 26.0.0

### ISSUE THREAD

**Issue by aj-michael** [bazelbuild/bazel#3258]
build-tools/26.0.0/apksigner does not exist, which completely breaks android_binary.

**Comment by aj-michael** [comment]
it appears that this was a bug in the build-tools 26.0.0 release, and should be fixed in the next release.

**Comment by aj-michael** [comment]
The android public tracking issue is https://issuetracker.google.com/issues/62696222

**Comment by klyubin** [comment]
A workaround until a fixed Android SDK Build Tools 26.x build is available is to copy build-tools/25.0.3/apksigner* and build-tools/25.0.3/lib/apksigner.jar to build-tools/26.0.0/.

**Comment by klyubin** [comment]
Android SDK Build Tools 26.0.1 has been published. It contains apksigner.

**Comment by aj-michael** [comment]
Due to another breaking change, a future Bazel release will drop support for build-tools versions prior to 26.0.1. See #3469 for context.
