### ISSUE TITLE
bazel re-executing actions after restart if the environment was changed before the restart

### ISSUE THREAD

**Issue by kush-c** [bazelbuild/bazel#3259]
### Description of the problem
Changing the environment (such as the PATH) causes bazel to re-execute some actions which seems to be by [design](https://github.com/bazelbuild/bazel/blob/a81264e1043dd90e984d9fcef5ce9962dce90d1d/src/main/java/com/google/devtools/build/lib/actions/ActionCacheChecker.java#L286) .
Subsequent builds after the env change don't cause a re-execution, **however** if bazel restarts it triggers unnecessary re-executions (supposedly due to "action command has changed").

A bazel restart without a previous env change **does not** trigger these re-executions.

### If possible, provide a minimal example to reproduce the problem:
$bazel build --explain=/tmp/explain.txt --verbose_explanations src:bazel 
$export PATH=$PATH:/bin
// Following rebuilds as expected
$bazel build --explain=/tmp/explain.txt --verbose_explanations src:bazel 
$bazel shutdown
// The next action triggers unnecessary re-executions.
$bazel build --explain=/tmp/explain.txt --verbose_explanations src:bazel 

### Environment info
* Operating System: Goobuntu

* Bazel version (output of `bazel info release`): 0.5.1

**Comment by benjaminp** [comment]
This is very likely #2574. Several environmental variables including `PATH` are fixed at server startup.

**Comment by meisterT** [comment]
Close as duplicate.
