### ISSUE TITLE
Is there a reason why `rbuildfiles` is not documented?

### ISSUE THREAD

**Issue by Utsav2** [bazelbuild/bazel#3260]
`bazel query rbuildfiles` would help us in CI to determine which tests to run when a skylark file changes.

Currently, we run every test if there's a skylark file change, which is not that infrequent anymore.

It would be nice to know if `rbuildfiles` is considered supported/unsupported/buggy to decide if we want to use it.

**Comment by Utsav2** [comment]
ping?

**Comment by janakdr** [comment]
Sorry for the lack of response! rbuildfiles is supported, though it's currently only used internally. We depend on it, though, so it is fully supported. We will try to add documentation!

**Comment by Utsav2** [comment]
@janakdr thanks! Could you remind me the strategy you suggested regarding diffs of query outputs to better determine which tests to run? I don't think I understood it properly, and we ran out of time discussing it today.

**Comment by meisterT** [comment]
Seems to fixed at HEAD https://docs.bazel.build/versions/master/query.html#rbuildfiles
