### ISSUE TITLE
bazel fails to compile tensorflow when gcc points to /etc/alternatives on Ubuntu

### ISSUE THREAD

**Issue by esafak** [bazelbuild/bazel#3261]
# System information

TensorFlow 1.2, Ubuntu 17.04 on GCE, CUDA 8.0, gcc 4.9.4

# Describe the problem

bazel fails to compile tensorflow when multiple versions of gcc are installed through `update-alternatives` and the default points to /etc/alternatives/gcc. Specifically, it fails to find the C and C++ header files. However, all works well when configure is set to use /usr/bin/gcc

**Comment by mhlopko** [comment]
Workaround: set `CC` environment variable to point to the concrete gcc to be used. Will investigate a real fix soon-ish.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
