### ISSUE TITLE
Add an integration test for files_to_run

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#3266]
Based on https://stackoverflow.com/questions/44398080/cc-grpc-library-for-bazel-0-5-1-fails-due-to-mandatory-files-to-run-provider-m, it seems like this is somewhat fragile.  `grep -r files_to_run src/test/shell/*` returning nothing, so I'm guessing we don't have any integration test for this.

See also https://groups.google.com/d/msg/bazel-discuss/4Vu_uv9nZaI/_fk9BoPXAQAJ for more discussion.

**Comment by mhlopko** [comment]
Test was already added in 36da18a6c8f4e9281eca1c9643a59fe16ab03c7c. Vlad verified that it fails with the issue from the StackOverflow and passes with the fix.
