### ISSUE TITLE
Error while upgrading Bazel with Bazel

### ISSUE THREAD

**Issue by AkritiRao** [bazelbuild/bazel#3267]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
I built bazel-0.4.0 successfully.
Then I tried upgrading it to the latest version **bazel-0.5.1** using 

$ ./compile.sh compile ../bazel-0.4.0/output/bazel.exe command
It's giving me an error

I even tried downgrading it to the older versions,
**bazel-0.5.0**, **bazel-0.4.5** gave me same error i.e.,
ERROR: Illegal javabase value 'C:/Program Files/Java/jdk', javabase must be an absolute path or label.
INFO: Elapsed time: 1.231s

**bazel-0.4.4** gave me different error i.e.,
🍃  Building Bazel with Bazel.
.ERROR: no such target '//:Files/Java/jdk': target 'Files/Java/jdk' not declared in package '' defined by C:/Users/potlapel/Downloads/bazel-0.4.4/BUILD.
INFO: Elapsed time: 0.182s

ERROR: Could not build Bazel

### Environment info
* Operating System: Windows 10

* Bazel version (output of `bazel info release`): bazel-0.5.1

###  Have you found anything relevant by searching the web?
No

### Anything else, information or logs or outputs that would be helpful?

$ ./compile.sh compile ../bazel-0.4.0/output/bazel.exe
🍃  Building Bazel with Bazel.
ERROR: Illegal javabase value 'C:/Program Files/Java/jdk', javabase must be an absolute path or label.
INFO: Elapsed time: 0.246s
---------------------
$ ./compile.sh compile ../bazel-0.4.0/output/bazel.exe
🍃  Building Bazel with Bazel.
.ERROR: no such target '//:Files/Java/jdk': target 'Files/Java/jdk' not declared in package '' defined by C:/path/to/bazel-0.4.4/BUILD.
INFO: Elapsed time: 0.182s
-------------------------

**Comment by mhlopko** [comment]
Answered on [StackOverflow](https://stackoverflow.com/questions/44775709/how-to-upgrade-bazel/44778377#44778377). Please do not double post, in this case I think StackOverflow question was sufficient. Thanks!
