### ISSUE TITLE
dsym support on MacOS

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#327]
We support fission on Linux, we should also support dsym on MacOS. I was hoping that we could use the same code path as fission, but it looks like it's a bit more tricky.

**Comment by ulfjack** [comment]
Someone was working on this internally, but he doesn't seem to be on github, so I can't easily assign it to him.

**Comment by dmaclach** [comment]
try adding --objc_generate_debug_symbols=true to your build options

**Comment by RNabel** [comment]
There is a flag `--apple_generate_dsym` -- since this flag exists, does it work, and if so, why is this issue still open?

**Comment by sergiocampama** [comment]
I believe this is for blaze dsym symbols.`--apple_generate_dsym` is for Apple builds using bazel, not for building bazel itself.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by thesayyn** [comment]
@sgowroji Can we reopen this issue please? this isn't anywhere near being fixed.

**Comment by hugooole** [comment]
I use the flag --apple_generate_dsym, but the dir xxx.dSYM generted by bazel is empty , why?
If manully use cmd  `dsymutil path/to/target  -o path/to/target.dSYM` , it not empty, and it work for me

**Comment by keith** [comment]
make sure you're using the toolchain from apple_support instead of from rules_cc

I don't follow the purpose of this ticket, @thesayyn can you clarify the ask here?

**Comment by hugooole** [comment]
```
load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "unittest",
```
@keith  Thanks for your attention! Is there a method to generate dSYM files for `cc_test` not by manully run `dsymutils xxx -o xxx`?

**Comment by hugooole** [comment]
I get the flag `--apple_generate_dsym` work when I add `bazel_dep(name = "apple_support", version = "1.24.3", repo_name = "build_bazel_apple_support")` in my MODULE.bazel @keith  THANK YOU VERY MUCH!!!

**Comment by keith** [comment]
yea that example should work with the latest bazel, generating dsyms for cc_binary was added very recently
