### ISSUE TITLE
'Get started' button should land on an index of Getting started pages

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#3276]
The primary action from the Bazel homepage is 'Get started', which opens https://bazel.build/versions/master/docs/getting-started.html

We decided to provide per-language getting started guides, this is why we are building [Java guide](https://github.com/bazelbuild/bazel/issues/3253), [C++ guide](https://github.com/bazelbuild/bazel/issues/3254), [Android and iOS guides](https://github.com/bazelbuild/bazel/issues/3245)

Today, the getting-started.html is a very strange tutorial that uses Bazel genrules to manipulate txt files.
Instead, this page should just ask users to pick a language to getting started. Basically, the same content as what is present at the bottom of our homepage: https://github.com/bazelbuild/bazel-website/blob/master/index.html#L160

**Comment by spomorski** [comment]
"Get Started" button now links to here: https://docs.bazel.build/versions/master/getting-started.html
