### ISSUE TITLE
Sanity Check Option

### ISSUE THREAD

**Issue by ncteisen** [bazelbuild/bazel#3277]
### Description of the problem / feature request / question:
It would be nice to have a sanity check feature, either on by default or flag enabled, that does a quick check for common case stupid errors.

I spend a frustrated hour trying to pick apart a linker error, only to find that I had listed a .h file under both srcs and hdrs. A check that there are no header files under srcs seems simple, and I am sure there are a lot more cases when a few lines of code could save a lot of debugging down the line.

### If possible, provide a minimal example to reproduce the problem:
Be me, coding too late to be smart.

###  Have you found anything relevant by searching the web?
A quick google search did not show any such functionality

**Comment by aiuto** [comment]
Won't fix. This is too open ended to address.
