### ISSUE TITLE
Bazel 0.5.2 doesn't build on Yosemite (therefore cannot update homebrew recipe)

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/bazel#3279]
Discovered by @ilovezfs when he created a pull request to update homebrew bazel to 0.5.2 (https://github.com/Homebrew/homebrew-core/pull/15003#issuecomment-311401027)

Failure: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/3726/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_bazel/

**Comment by mhlopko** [comment]
@damienmg @ulfjack Dejavu 0.5.0. Let's fix this and publish 0.5.4 with only this additional cherry pick?

**Comment by ulfjack** [comment]
You mean 0.5.3? How's this a dejavu?

**Comment by philwo** [comment]
Do we still support Yosemite? If yes, why?

And if yes, we need a CI cluster for this, otherwise these breakages will continue. No one is testing whether Bazel works correctly or even builds on anything but the latest macOS release at the moment.

I can try to prepare a one-time patch for this issue, but the lack of automated and manual testing makes it hard to maintain support.

@ulfjack Do you think it is worth it to buy 8 additional MacPros (we can also do with less, but AFAIK this will slow down the entire CI run then, @damienmg can probably confirm this) to support OS X 10.10 and 10.11?

**Comment by ilovezfs** [comment]
Note that when Apple releases High Sierra in three months, Homebrew will drop Yosemite support. At that point we will support 10.11, 10.12, and 10.13. Do you have enough CI capacity currently to support those three versions?

**Comment by mhlopko** [comment]
Reg dejavu: we had to do 0.5.1 just for osx, it was 0.5.0 with 1 (maybe 2) cherry picks.

If yosemite will be dropped in 3 months, we can also ignore 3% of homebrew users (unclear how many if any are using bazel) and publish homebrew recipe only for el capitan and further (https://github.com/Homebrew/homebrew-core/pull/15003#issuecomment-311401027)

**Comment by ilovezfs** [comment]
@mhlopko the 3% number was specific to Bazel :)

**Comment by ulfjack** [comment]
@ilovezfs I wish. We have hardly enough to support one, and we're currently running with 5 (?) Mac Pros.

**Comment by mhlopko** [comment]
Ah ok, sorry for the confusion.

**Comment by ulfjack** [comment]
Maybe we can run two macs with 10.11 and 10.12 and only do pre-release test runs with them, rather than running presubmit?

**Comment by ulfjack** [comment]
Well, let's fix it and push a patch release. Is there any other choice? I'll see what I can do to get us more capacity.

**Comment by ilovezfs** [comment]
@ulfjack I don't mind dropping 10.10 support immediately if it helps you guys out. But you have to promise me you'll test on 10.13 with APFS sooner rather than later :)

**Comment by ulfjack** [comment]
Yosemite is still 20% of OSX users or so: https://www.gosquared.com/global/mac/sierra/#beta

Probably lower wrt. software developers. In any case, we need to come up with a strategy of testing different platforms, and also clarify what versions we support.

**Comment by ulfjack** [comment]
@philwo is working on testing with 10.13...

**Comment by ilovezfs** [comment]
I'm testing this patch
```
diff --git a/src/java_tools/junitrunner/java/com/google/testing/coverage/BUILD b/src/java_tools/junitrunner/java/com/google/testing/coverage/BUILD
index 36b4aef..509f3b0 100755
--- a/src/java_tools/junitrunner/java/com/google/testing/coverage/BUILD
+++ b/src/java_tools/junitrunner/java/com/google/testing/coverage/BUILD
@@ -77,7 +77,7 @@ genrule(
     ],
     outs = ["JacocoCoverage_jarjar_deploy.jar"],
     cmd = "\n".join([
-        "JARJAR=\"$$(mktemp)\"",
+        "JARJAR=\"$$(mktemp -t bazel)\"",
         "\"$(JAVA)\" -jar \"$(location //third_party/java/jarjar:jarjar_bin_deploy.jar)\" --rules \"$(location :JacocoCoverage.jarjar)\" --output \"$${JARJAR}\" \"$(location :JacocoCoverage_deploy.jar)\"",
         "\"$(JAVA)\" -jar \"$(location //src/java_tools/singlejar:SingleJar_deploy.jar)\" --normalize --sources \"$${JARJAR}\" --output \"$@\"",
         "rm -fr \"$${JARJAR}\"",
```

**Comment by ilovezfs** [comment]
Yes that worked: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/3728/version=yosemite/console

**Comment by philwo** [comment]
@ilovezfs Thanks a lot for coming up with the patch and testing it! Do you want to send this as a GitHub pull request?

**Comment by ilovezfs** [comment]
@philwo https://github.com/bazelbuild/bazel/pull/3281.

**Comment by damienmg** [comment]
@ilovezfs: Can we have the patch in the homebrew recipe for now?

**Comment by ilovezfs** [comment]
@damienmg yes, that's fine. I've shipped https://github.com/Homebrew/homebrew-core/pull/15003 with the patch from #3281.

**Comment by damienmg** [comment]
Thanks!

**Comment by mhlopko** [comment]
Marking as a release blocker for 0.6.0.

**Comment by ulfjack** [comment]
Removing "Release blocker" since there seems to be a workaround. Do we have a fix for this?

**Comment by ulfjack** [comment]
Damien tells me we should merge the pull request.

**Comment by ulfjack** [comment]
Can't merge the pull request, it's broken on Linux (and seems overly complicated).

**Comment by ilovezfs** [comment]
@ulfjack I don't see how it's "broken" on Linux if it never gets to the `mktemp -t bazel` part on Linux. Regardless, I've pushed the change you requested, though.

**Comment by ulfjack** [comment]
@ilovezfs sorry, you're right - I should have been clearer. Thanks for the change.

**Comment by buchgr** [comment]
Fixed by https://github.com/bazelbuild/bazel/commit/9dd30c92cee7e74cc307d941e3f1d77a232be340
