### ISSUE TITLE
Requirements for WORKSPACE rules not documented

### ISSUE THREAD

**Issue by macrael** [bazelbuild/bazel#3287]
When attempting to create a workspace http_file rule called "getssl-file" I got the following error:

ERROR: /Gyroscope/WORKSPACE:3:1: http_file rule //external:getssl-file's name field must be a legal workspace name.

`getssl_file` did work, but I this was not documented anywhere near its definition in the docs here: https://docs.bazel.build/versions/master/be/workspace.html#http_file

Moreover, in order to refer to this in a project, I had to use the string: `@getssl_file//file` which I also do not see documented anywhere.

**Comment by dslomov** [comment]
http_file is no more
