### ISSUE TITLE
Bazel with remote execution reports everything as 'local'

### ISSUE THREAD

**Issue by EricBurnett** [bazelbuild/bazel#3288]
### Description of the problem / feature request / question:

When used with remote execution, bazel still reports everything as 'local'. This is confusing.

E.g.
"Executed 745 out of 745 tests: 552 tests pass and 193 fail locally."

(--spawn_strategy and its counterparts are set to 'remote'; execution in fact did not occur locally).

### Environment info
* Operating System:
Linux

* Bazel version (output of `bazel info release`):
development version

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
Built from head on 2017/06/23 (sorry, not sure exact commit hash).

###  Have you found anything relevant by searching the web?
Could be related to https://github.com/bazelbuild/bazel/commit/acd291a520d392977a2efff17949b75c2fa80eef ?

### Anything else, information or logs or outputs that would be helpful?
I'll note that the logs in java.log are also misleading, e.g. log messages like:
170628 22:54:00.970:I 4727 [com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.start] starting local subprocess #1443, argv: external/bazel_tools/tools/test/test-setup.sh \<target\>
170628 22:54:00.970:I 4727 [com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.stepLog] prefetching inputs for local execution (#1443 Testing \<target\>)
170628 22:54:00.970:I 4727 [com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.setState] Step #1443 time: 0.000 delta: 0.000 state: PARSING --> PREFETCHING_LOCAL_INPUTS
170628 22:54:00.970:I 4727 [com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.stepLog] running locally (#1443 Testing \<target\>)

I realize that java.log is internal-only and under no obligation to be non-misleading, but possibly worth correcting anyways.

**Comment by ulfjack** [comment]
If java.log says com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.start, then it is, in fact, executing locally. Maybe you have tests marked as "local"?

bazel query 'attr(tags, local, //...)' (or something like that)

**Comment by EricBurnett** [comment]
Ahh, hmm - you are correct, those tests are in fact marked local. Whoops! This can probably be closed non-actionable then.

Though as an interesting side note, nothing that _isn't_ local ends up in java.log, which I think is what mislead me. Are other execution strategies supposed to generate log lines as well?

**Comment by ulfjack** [comment]
Only the local one has logging implemented. It's on my todo list, though.
