### ISSUE TITLE
Android studio cannot find all aar librarys!

### ISSUE THREAD

**Issue by luoyushouchai** [bazelbuild/bazel#3290]
When i use Android studio open my project, all jars can be found but the aars ?
For example:
```
android_binary(
   ...
   deps = [
      "a",
      "b",
   ]
   ...
)
java_import(
    name = "a",
    jars = [
       "libs/a.jar",
    ]
)

aar_import(
   name = "b",
   aar = "libs/b.aar",
)
```
The a.jar can be found but the b.aar!
**bazel build //my:app** run well,  However, It can not found by android studio!

----------------------------------------------------------------------------------------------------
The generated project has files: `.bazel/modules/.project-data-dir.iml`!
All deps third jar is in it like this:
```
...
<orderEntry type="library" name="gson-2.7-ijar_243ebdc5" level="project" />
...
```
But no reference to aar. 

My Android studio version is 2.2.2 !
How should I do to set it?

**Comment by aj-michael** [comment]
This is a known bug in aar_import right now. It was implemented without proper IDE support. The first step to fix that was in a7be6f6df4d3cc5f0f8107b8ffc15f0496e001c6, but it will also require a change to the Android Studio IDE plugin in https://github.com/bazelbuild/intellij.

**Comment by aj-michael** [comment]
This was reported to the android studio plugin plugin in https://github.com/bazelbuild/intellij/issues/103.

**Comment by luoyushouchai** [comment]
Thanks! I see! How long will this change take?

**Comment by luoyushouchai** [comment]
@aj-michael This bug remain unsolved !

**Comment by aj-michael** [comment]
Thanks Jan!
