### ISSUE TITLE
remote worker fails to run java tests (local mac osx / remote docker container)

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/bazel#3294]
Trying to run tests with remote worker running on local docker container, I get a new failure: It suddenly complains about my SHA1 function (as warning) and then fails 
This failure did not occur on `0.5.1` (we just didn't have a way to run in in sandbox).

This is what I get when I run the test: (more details below)
```sh
$ bazel test  \
        --javabase=/usr/lib/jvm/java-8-openjdk-amd64 \
        --remote_executor=localhost:3030 \
        --remote_cache=localhost:3030 \
        --strategy=TestRunner=remote \
        --remote_local_fallback=false \
        --remote_timeout=600 \
           //...

INFO: Found 1 test target...
WARNING: TestRunner remote work failed (io.grpc.StatusRuntimeException: INVALID_ARGUMENT: invalid argument(s): content_digest: Upload digest hash: "bc432edfd77a62a04690d0dc6af4ebf8"
size_bytes: 101
 did not match data digest: hash: "ece0c0812394a0df9e6d9c2097ed2f026d4b9c33"
size_bytes: 101
).
FAIL: //src/main/java/com/example:my_test (see /private/var/tmp/_bazel_ors/719f891d5db9fd5e73ade25b0c847fd1/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/testlogs/src/main/java/com/example/my_test/test.log).
ERROR: /Users/ors/workspace/workshops/bazel-remote-test/src/main/java/com/example/BUILD:2:1: output 'src/main/java/com/example/my_test/test.log' was not created.
ERROR: /Users/ors/workspace/workshops/bazel-remote-test/src/main/java/com/example/BUILD:2:1: not all outputs were created or valid.
Target //src/main/java/com/example:my_test up-to-date:
  bazel-bin/src/main/java/com/example/my_test.jar
  bazel-bin/src/main/java/com/example/my_test
INFO: Elapsed time: 2.999s, Critical Path: 1.01s
//src/main/java/com/example:my_test                                      FAILED in 0.0s

Executed 1 out of 1 test: 1 fails locally.
```

At first I thought that's because I started the remote worker with sandboxing but it didn't work without the sandboxing as well. 

### Steps to reproduce:
1. clone this repo: https://github.com/or-shachar/bazel-sample-repo
2. build bazel worker image `docker build -t bazel-worker remote-worker-docker`
3. start the remote worker (script is in `remote-worker-docker/` folder)
4. Run the tests: (notice the local `.bazelrc` file)
```sh
bazel test  \
        --javabase=/usr/lib/jvm/java-8-openjdk-amd64 \
        --remote_executor=localhost:3030 \
        --remote_cache=localhost:3030 \
        --strategy=TestRunner=remote \
        --remote_local_fallback=false \
        --remote_timeout=600 \
           //...
```

### Environment info
* Operating System: mac os x sierra
* Bazel version - HEAD (d698367067c1ca52c8e23eae58232d0d5a4861cd)
* local java : oracle jdk 1.8.0_111
* worker java: openjdk 1.8.0_111

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
Maybe related to https://github.com/bazelbuild/bazel/issues/3188 by @philwo  and @ulfjack

**Comment by ulfjack** [comment]
Bazel and the remote worker need to agree on the hash function, and Bazel still uses MD5 by default, while the remote worker uses SHA1. We can't auto-detect this right now - we can't even detect that they differ. Are you setting --host_jvm_args=-Dbazel.DigestFunction=SHA1?

**Comment by ulfjack** [comment]
See here:
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/remote/README.md

**Comment by or-shachar** [comment]
@ulfjack thanks for the clarification! With the startup option it worked!
I created a pull request to fix the docs on the remote worker page as well.
