### ISSUE TITLE
Expose java_strict_deps option to Skylark

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#3295]
`java_common.compile` actually takes `strict_deps` as an option, but AFAICT Skylark can't see what the user passed in.  Given that [we'd like people to use it](https://blog.bazel.build/2017/06/28/sjd-unused_deps.html) and [people are trying to use it](https://stackoverflow.com/q/44827704/4243), we should expose it.

**Comment by iirina** [comment]
This should work, what do you mean by Skylark can't see what the user passed in?

**Comment by ittaiz** [comment]
How can one see the contents of the flag from a skylark rule?

**Comment by iirina** [comment]
Sorry, I'm not sure if we are talking about `java_common.compile#strict_deps` or the `java_strict_deps` flag.

**Comment by ittaiz** [comment]
The java_strict_dep command line flag

**Comment by iirina** [comment]
OK, now I see. How would you want to use this flag from Skylark?

**Comment by ittaiz** [comment]
I'm developing something very similar in rules_scala.
I'd like to be able to toggle the way it works from our bzl file.
Additionally we are going to call java_common.compile (for java sources)
and we'll need to pass the contents of the flag to it

**Comment by ittaiz** [comment]
Thanks!
