### ISSUE TITLE
Bazel passes through TMPDIR by default, but sandbox doesn't

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#3296]
We are forwarding TMPDIR to the actions, but aren't making it writable in the sandbox. We shouldn't be inconsistent like that.

We're actually likely going to stop forwarding TMPDIR to the actions due to hermeticity / caching concerns (see https://github.com/bazelbuild/bazel/issues/2574). Although I suppose we might honor it for locally executed actions, but it must not be part of the cache key.

**Comment by ulfjack** [comment]
Workaround is to set --sandbox_tmpfs_path=$TMPDIR or similar.

**Comment by Androbin** [comment]
@ulfjack Any updates on this since #2574 was closed in release 0.8.0?

**Comment by ulfjack** [comment]
@laszlocsomor has made some progress in 294c074fcd42ffb1154101f5156f5e9e121ab615, and also has a pending change to make TMPDIR writable in the sandbox.

**Comment by ulfjack** [comment]
I'll close this in favor of #4376, which has all the changes attached.
