### ISSUE TITLE
Bazel run not making sure process has exited

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#3299]
I just had a case where my machine ran out of memory, and the Bazel process got killed, but the process started with bazel run was still alive. That was pretty confusing.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
