### ISSUE TITLE
Use a variable for latest Bazel version number in docs

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#3303]
Our install docs are often displaying the latest version number to download: http://docs.bazel.build/versions/master/install-ubuntu.html

Today, this is hardcoded in the text.
We should introduce a variable that is defined in one place and that we update when performing the release.
https://github.com/bazelbuild/bazel/blob/master/site/_config.yml is probably the place to put this variable.

**Comment by jin** [comment]
The install docs are now versioned, and I also don't see hardcoded Bazel version numbers in the installation instructions anymore.

https://docs.bazel.build/versions/0.20.0/install-windows.html
https://docs.bazel.build/versions/0.20.0/install-ubuntu.html
