### ISSUE TITLE
Expose ld_executable to cpp fragment

### ISSUE THREAD

**Issue by mjs-sx** [bazelbuild/bazel#3306]
### Description of the problem / feature request / question:

CppConfiguration doesn't expose the linker executable to Skylark's cpp fragment, the way it does with the compiler, ar, nm, objcopy, etc. Reading the code, it isn't obvious why. Is there a reason why it isn't exposed?

It would be nice to have access to the linker executable from skylark rules.

###  Have you found anything relevant by searching the web?
I searched GitHub and StackOverflow and didn't find much related to the C++ fragment, mostly documentation requests (#2932, #2930, #2929). #1487 suggests customizing fragments, but doesn't seem related.

### Anything else, information or logs or outputs that would be helpful?

C++ fragment docs:
https://docs.bazel.build/versions/master/skylark/lib/cpp.html

The relevant source:
https://github.com/bazelbuild/bazel/blob/95aa487c02e20c6e0e137fca1670fc72ec9bd588/src/main/java/com/google/devtools/build/lib/rules/cpp/CppConfiguration.java#L1554

**Comment by mhlopko** [comment]
Done in https://github.com/bazelbuild/bazel/commit/cdda23f5f83bb6e8c85a200ab98b9fff6789a62b
