### ISSUE TITLE
Skylark implementation of `new_git_repository` looks for BUILD files in external/

### ISSUE THREAD

**Issue by minorhacks** [bazelbuild/bazel#3308]
### Description of the problem / feature request / question:

The documentation of `//tools/build_defs/repo/git.bzl` for `new_git_repository` reads:

>   build_file: The file to use as the BUILD file for this repository.
>   Either build_file or build_file_content must be specified.
>   This attribute is a label relative to the main workspace.

However, this appears to be incorrect - this implementation of `new_git_repository` appears to look for BUILD files within the workspace's `external` directory.

### If possible, provide a minimal example to reproduce the problem:

```
mkdir /tmp/bazel_workspace
cd /tmp/bazel_workspace
touch WORKSPACE
touch tinyformat.BUILD
```

`WORKSPACE`:

```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository", "git_repository")

new_git_repository(
    name = "tinyformat",
    build_file = "tinyformat.BUILD",
    remote = "https://github.com/c42f/tinyformat",
    tag = "v2.1.0",
)
```

`tinyformat.BUILD`:

```
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "tinyformat",
    hdrs = ["tinyformat.h"],
)

cc_test(
    name = "tinyformat_test",
    srcs = ["tinyformat_test.cpp"],
    deps = [":tinyformat"],
)
```

Run: `bazel build @tinyformat//:all`
Which prints:

```
ERROR: no such package '@tinyformat//': Not a file: /tmp/bazel_workspace/external/tinyformat.BUILD.
ERROR: no such package '@tinyformat//': Not a file: /tmp/bazel_workspace/external/tinyformat.BUILD.
____Elapsed time: 0.894s
```

Moving `tinyformat.BUILD` to `external/tinyformat.BUILD` will allow the aforementioned build command to succeed.

Which is correct - the documentation or the implementation? (Note that having files in an `external` directory causes other issues - see #3307 )

### Environment info
* Operating System:
Ubuntu 16.04

* Bazel version (output of `bazel info release`):
release 0.5.2

**Comment by dhalperi** [comment]
Still happening on bazel 0.13.0

**Comment by rkallal** [comment]
Still happening in 0.19.2

**Comment by dslomov** [comment]
Working as intended, the syntax is `@//tinyformat.BUILD`
