### ISSUE TITLE
FR: Support implicit linking with DLLs

### ISSUE THREAD

**Issue by benvanik** [bazelbuild/bazel#3311]
### Description of the problem / feature request / question:

Requesting the ability to access the .lib files for DLLs produced by link.exe from cc_binary rules and pass them to other cc_library/cc_binaries as dependencies.

Discussion here: https://groups.google.com/forum/#!topic/bazel-discuss/aLExoG4m5Us

### If possible, provide a minimal example to reproduce the problem:

Extending https://github.com/bazelbuild/bazel/tree/master/examples/windows/dll:

Add `hello-world-implicit.cpp`:
```
#include <stdio.h>
#include <windows.h>
__declspec(dllimport) char *get_time();
__declspec(dllimport) void say_hello(char *message);

int main() {
  char *now = get_time();
  say_hello(now);
  return 0;
}
```

And a build rule like:
```
cc_binary(
    name = "hello-implicit",
    srcs = [
        "hello-world-implicit.cpp",
    ],
    deps = [":hellolib.dll"],
)
```

Expect the following the link without unresolved symbols:
```
bazel build --cpu=x64_windows_msvc :hello_implicit
```

Currently since the lib is not passed on to the exe the linking will fail with unresolved symbols. Adding the dll as a dep also causes issues as it is passed to cl.exe as such:
```
external/local_config_cc/wrapper/bin/msvc_cl.bat ... -Lbazel-out/msvc_x64-dbg/bin/_solib_x64_windows/ hellolib.dll ...
```
This causes the msvc_tools.py ArgParser to emit the following warning:
```
Warning: Unmatched arguments: hellolib.dll
```

**Comment by mhlopko** [comment]
Related to #1920

**Comment by dslomov** [comment]
@mhlopko @meteorcloudy feasible for 0.6? Is there any workaround?

**Comment by meteorcloudy** [comment]
I've wrote a doc about building dynamic library on Windows, please check out here:
https://docs.google.com/document/d/1ZK4f84wype5NsZ7ltOUqvyFr7eKOIf4Wd-DrU6HCBkA/edit
