### ISSUE TITLE
0.5.2 have C++ compilation error on macOS Sierra without Xcode, maybe on more version of macOS

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3315]
@philipposslicher @varming have pinged #3063 saying that they encountered it again. Opening this bug for tracking since it is probably a different issue.

@philipposslicher @varming: can you explain your set-up (macOS version, xcode installed or not, if it use to work or not)?

Also please send the error message you are getting.

**Comment by philipposslicher** [comment]
macOS: 10.13 Build 17A291M
xcode is installed but not in the applications folder (external hard drive), I prefer to have CLT installed to a path on my computer, not on an external drive, so the computer wouldn't necessarily see if xcode is installed. I just use xcode for ios app development (specifically unity). I had to manually set the CLT path to xcode to make bazel build, but this means that things like git and CLT don't work unless I have my external drive plugged all the time.

**Comment by mhlopko** [comment]
Hi Philippos,
so what exactly was the problem? Bazel didn't find CLT that was installed in the computer, or it didn't find Xcode installed on the external drive? Or it didn't reconfiger when you plugged the drive? How did you 'manually set the CLT path'? I also didn't understand why git and CLT don't work unless you have your drive plugged out? I guess I just need more elaborate problem description :)

Thank you for investigating and reporting!

**Comment by philipposslicher** [comment]
The problem is that git resides in CLT, which by default with an xcode installation is inside of the xcode app bundle. Without the drive plugged in, I would have to always switch my CLT path depending on if the drive was plugged in or not. 
I switched my CLT path with xcode-select. Right now, without my external drive, commands like git don't work (blah blah xcode command line tools missing please install or reconfigure blah blah)
The problem is that bazel is still reliant on xcode (and strangely didn't find xcode when it was installed).

**Comment by varming** [comment]
I didn't have Xcode installed, but installed it to address #3063. After installing Xcode the problem went away. I just tried to delete Xcode and run bazel, but everything works now. FYI: I got bazel 0.5.2 by upgrading the brew installation from 0.4.5. I should have recorded the error, but I didn't.

**Comment by ulfjack** [comment]
I don't see anything actionable here. We need at least a description of what happened, possibly including terminal output, or a full reproduction workspace.

**Comment by ulfjack** [comment]
Removing the "Release blocker" label, since I have no idea what we need to do here.

**Comment by obeattie** [comment]
I'm encountering the same issue with Bazel 0.5.2 installed from Homebrew. What information can I provide to help?

**Comment by ulfjack** [comment]
Apparently the last comment didn't make it to GitHub. How about all of the
information you have?

**Comment by damienmg** [comment]
I think this should be a release blocker: this is a un planned regression that prevent some user from using Bazel, namely people that does not have Xcode clt installed.

The repro is clear but since it requires a special setup that we do not have, it would help if we get console output of an execution of Bazel.

/cc @buchgr for the release

**Comment by ulfjack** [comment]
I don't see how we can support it if we don't have tests for it, or if those tests requires special setup that we can't reproduce.

**Comment by damienmg** [comment]
I would have been more than happy to add the corresponding platform if only
we had enough people...

**Comment by ulfjack** [comment]
We can't get more people, so we need to carefully decide what we support, and not support stuff that we don't have enough people for.

**Comment by c-parsons** [comment]
From what I understand this is a kind of bizarre setup that I'm not sure we want to spend resources to make sure we support. (i.e. have a test setup to prevent regressions for)
It sounds like the user has Xcode available in an external drive *sometimes* but then unmounts that drive between builds. Thus, bazel will sometimes detect an xcode available but will require a `blaze clean --expunge` if suddenly xcode is no longer available.

Ultimately we want to *sort of* fix this by invalidating the xcode_config repository when xcode versions change; but that is currently unsupported in a repository rule.

**Comment by damienmg** [comment]
IIUC @varming did not had Xcode installed and we should be able to support that use-case. I agree that we don't want to address @philipposslicher use-case right now, though we want to have it supported in the long run and we have some ideas around it.

We need to test for @varming use case and make sure it does not happen again, the previous case generated 3 user report in the 15minutes after the upgrade of homebrew...

**Comment by Gurbo86** [comment]
Hi,

I'm having a problem related to this Issue and [3063](https://github.com/bazelbuild/bazel/issues/3063).

I've been following the steps detailed in this [article](https://medium.com/jim-fleming/loading-a-tensorflow-graph-with-the-c-api-4caaff88463f). Downloaded Bazel as it's specified [here](https://docs.bazel.build/versions/master/install-os-x.html#install-on-mac-os-x-homebrew) and followed the rest of the steps in the article.

The error that is showing me while compiling is this one:
```
Leonels-MacBook-Pro:MeCagoEnTodo Gurbo$ bazel build :loader --verbose_failures
.............................................................
ERROR: /private/var/tmp/_bazel_Gurbo/9edb2ddb8d65829e041fd83f16a07397/external/local_config_cc/BUILD:49:5: in apple_cc_toolchain rule @local_config_cc//:cc-compiler-darwin_x86_64: Xcode version must be specified to use an Apple CROSSTOOL.
ERROR: Analysis of target '//tensorflow/MeCagoEnTodo:loader' failed; build aborted.
```

I've tried everything you have mention in the previous issue, and I'm already stuck with the same place. Can you please help me?

Regards

**Comment by mhlopko** [comment]
Do you have Xcode installed? In the Applications folder? Does `bazel clean --expunge` help? I assume you're using bazel 0.5.4, correct? I also assume you tried `xcode-config` commands mentioned above?

**Comment by Gurbo86** [comment]
@mhlopko I have skipped this command in the thread 3063:
`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

I've made all the steps except this one. After running it, everything started running

Thanks and sorry for bothering.

Regards.

**Comment by mhlopko** [comment]
Glad it got resolved :)

**Comment by mhlopko** [comment]
I believe this is fixed. Please complain if I'm wrong.
