### ISSUE TITLE
experimental_sandbox_base not working for test

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3321]
### Description of the problem / feature request / question:

I have Go and Python tests. For both, once I enable `--experimental_sandbox_base=/run/shm`, they no longer find their respective input files.

### Environment info
* Operating System: Ubuntu 16.04.2
* Bazel version (output of `bazel info release`): 0.5.2

###  Have you found anything relevant by searching the web?
Nope

**Comment by philwo** [comment]
I'll try to reproduce this on Monday, but if you have a minimal example and command-line to reproduce the error you see, that would be helpful.

**Comment by abergmeier-dsfishlabs** [comment]
I _think_ the problem was me passing `args` wrapped in `location` subst. Let me double check that first.
