### ISSUE TITLE
test and sandbox_debug and test_output=errors

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3322]
### Description of the problem / feature request / question:

When I use `test` with `--sandbox_debug` and `test_output=errors`, it no longer prints the errors.

### Environment info
* Operating System: Ubuntu 16.04.2
* Bazel version (output of `bazel info release`): 0.5.2

###  Have you found anything relevant by searching the web?
Nope

**Comment by ulfjack** [comment]
Marked as release blocker since it looks like a regression in 0.5.2.

**Comment by ulfjack** [comment]
@philwo Can you work on this today or do I need to find someone else?

**Comment by philwo** [comment]
In pretty sure I know why this happens. I'll have a look.

**Comment by ulfjack** [comment]
Talked with @philwo about this and decided that I'd take a shot at fixing it.
