### ISSUE TITLE
Can't depend on prebuilt extensionless dynamic library on macOS

### ISSUE THREAD

**Issue by vmsp** [bazelbuild/bazel#3323]
### Problem

I'm trying to build a `cc_binary()` which uses Qt 5.9.

When you install Qt through Homebrew on a macOS it compiles the code to *.framework files. The content of these files are the headers and a dynamic library without extension (e.g. QtCore instead of QtCore.dylib).

So in `WORKSPACE` I have
```python
new_local_repository(
    name = "qt",
    path = "/usr/local/opt/qt/lib/",
    build_file = "BUILD.qt"
)
```

Then I have an Hello World application
```python
cc_binary(
    name = "desktop",
    srcs = ["main.cc"],
    deps = ["@qt//:core", "@qt//:widgets", "@qt//:gui"]
)
```

In `BUILD.qt` I tried two different methods. First:
```python
cc_library(
    name = "core",
    srcs = ["QtCore.framework/QtCore"],
    includes = ["QtCore.framework/Headers/*"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "widgets",
    srcs = ["QtWidgets.framework/QtWidgets"],
    includes = ["QtWidgets.framework/Headers/*"],
    deps = [":core"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "gui",
    srcs = ["QtGui.framework/QtGui"],
    includes = ["QtGui.framework/Headers/*"],
    deps = [":core"],
    visibility = ["//visibility:public"],
)
```

Gives an error when I `bazel build desktop` telling me I need to use files with the appropriate extensions:
```
ERROR: /private/var/tmp/_bazel_vitor/18b2d5f5da948f20554e381cd9e6605a/external/qt/BUILD.bazel:4:12: in srcs attribute of cc_library rule @qt//:core: file '@qt//:QtCore.framework/QtCore' is misplaced here (expected .cc, .cpp, .cxx, .c++, .C, .c, .h, .hh, .hpp, .hxx, .inc, .S, .s, .asm, .a, .lib, .pic.a, .lo, .pic.lo, .so, .dylib, .dll, .o or .pic.o).
```

The second method I tried used `objc_framework`:
```python
objc_framework(
    name = "core",
    framework_imports = ["QtCore.framework"]
)

objc_framework(
    name = "widgets",
    framework_imports = ["QtWidgets.framework"]
)

objc_framework(
    name = "gui",
    framework_imports = ["QtGui.framework"]
)
```

But it tells me I can't use an `objc_framework` in `cc_binary`'s deps
```
ERROR: /Users/vitor/code/aceso_repo/desktop/BUILD:4:12: in deps attribute of cc_binary rule //desktop:desktop: objc_framework rule '@qt//:core' is misplaced here (expected cc_inc_library, cc_library, objc_library, experimental_objc_library or cc_proto_library).
```

So, how can what else can I try?

Thanks!

### Environment info
* Operating System: macOS 10.12
* Qt 5.9.1
* Bazel version: release 0.5.2-homebrew

**Comment by mhlopko** [comment]
@lberki Another reason to work on cc_import-like rule...

**Comment by mhlopko** [comment]
CC @calpeyser

**Comment by evanmoran** [comment]
I just wanted to add that I'm also running into this. QT releases are built with framework libraries by default so supporting frameworks easily would be super helpful to combine QT + Bazel!

**Comment by hlopko** [comment]
This should be doable with [cc_import](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_import), please open a new issue if it is not. Thanks!

**Comment by shriramiyer** [comment]
Does anyone have a working solution handy for using Qt with Bazel on MacOS? I'm using Qt version 5.12 (installed using brew), in case it matters.

**Comment by shantanugoel** [comment]
Just add `-F` (for the path where the frameworks are) and `-f` for the framework that you want to link to in linkopts. e.g.
```
cc_library(
    name = "qt_test",
    hdrs = glob(["include/**/**"]),
    includes = ["include"],
    linkopts = [
        "-Flib/",
        "-framework QtTest",
    ],
)
```
