### ISSUE TITLE
android_integration_test failing on CI

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#3326]
//src/test/shell/bazel/android:android_integration_test is failing on CI with the following error:
```
____[13 / 19] Creating manifest for test.aar matching res/.*
ERROR: /home/ci/.cache/bazel/_bazel_ci/fd6504bb53134b06c1d2dd463af2cc34/bazel-sandbox/9217689767576555005/execroot/io_bazel/_tmp/3da2c920435451c498a79854252eca5c/workspace.avZL6EzQ/BUILD:1:1: Creating manifest for test.aar matching res/.* failed: Process exited with status 1 [sandboxed].
ERROR: zip_manifest_creator: could not find zipper executable
Use --strategy=ZipManifestCreator=standalone to disable sandboxing for the failing actions.
____Building complete.
Target //:test failed to build
Use --verbose_failures to see the command lines of failed build steps.
____Elapsed time: 9.809s, Critical Path: 0.61s
-- Test log: -----------------------------------------------------------
------------------------------------------------------------------------
test_empty_tree_artifact_action_inputs_mount_empty_directories FAILED: terminated because this command returned a non-zero status:
/home/ci/.cache/bazel/_bazel_ci/fd6504bb53134b06c1d2dd463af2cc34/bazel-sandbox/9217689767576555005/execroot/io_bazel/bazel-out/local-fastbuild/bin/src/test/shell/bazel/android/android_integration_test.runfiles/io_bazel/src/test/shell/bazel/android/android_integration_test:295: in call to test_empty_tree_artifact_action_inputs_mount_empty_directories
FAILED: test_empty_tree_artifact_action_inputs_mount_empty_directories
```

**Comment by katre** [comment]
Looks like the same error in test_nonempty_aar_resources_tree_artifact:
```
____[11 / 17] Creating manifest for test.aar matching res/.*
ERROR: /home/ci/.cache/bazel/_bazel_ci/fd6504bb53134b06c1d2dd463af2cc34/bazel-sandbox/9217689767576555005/execroot/io_bazel/_tmp/3da2c920435451c498a79854252eca5c/workspace.iHOtt4Vo/BUILD:1:1: Creating manifest for test.aar matching res/.* failed: Process exited with status 1 [sandboxed].
ERROR: zip_manifest_creator: could not find zipper executable
Use --strategy=ZipManifestCreator=standalone to disable sandboxing for the failing actions.
____Building complete.
Target //:test failed to build
Use --verbose_failures to see the command lines of failed build steps.
____Elapsed time: 11.021s, Critical Path: 1.32s
-- Test log: -----------------------------------------------------------
------------------------------------------------------------------------
test_nonempty_aar_resources_tree_artifact FAILED: terminated because this command returned a non-zero status:
/home/ci/.cache/bazel/_bazel_ci/fd6504bb53134b06c1d2dd463af2cc34/bazel-sandbox/9217689767576555005/execroot/io_bazel/bazel-out/local-fastbuild/bin/src/test/shell/bazel/android/android_integration_test.runfiles/io_bazel/src/test/shell/bazel/android/android_integration_test:317: in call to test_nonempty_aar_resources_tree_artifact
FAILED: test_nonempty_aar_resources_tree_artifact
```

**Comment by dkelmer** [comment]
hey @laszlocsomor, I think this commit might be breaking the test: https://github.com/bazelbuild/bazel/commit/e212c0514df05c5df8da097ff9ce443e0dde43e9

I can't reproduce the failure locally at all so I can't fully confirm, but the timeline seems to match up:
test was passing at build #859 which was before you submitted (http://ci.bazel.io/job/bazel-tests/859/testReport/)
test was failing at build #861 which was the first build to include your change (http://ci.bazel.io/job/bazel-tests/861/testReport/)

Could you take a look?

**Comment by laszlocsomor** [comment]
@dkelmer : I couldn't repro the failure locally, so I added more logging: https://bazel-review.googlesource.com/c/12891/

**Comment by katre** [comment]
Output with extra debugging:
ERROR: /home/ci/.cache/bazel/_bazel_ci/6e647099a05461e78b1d704c36fb3217/bazel-sandbox/8263209054496238925/execroot/io_bazel/_tmp/3da2c920435451c498a79854252eca5c/workspace.5a8uTWKx/BUILD:1:1: Creating manifest for test.aar matching res/.* failed: Process exited with status 1 [sandboxed].
ERROR: zip_manifest_creator: could not find zipper executable. Additional info:
  $0=(bazel-out/host/bin/external/bazel_tools/tools/android/zip_manifest_creator)
  $RUNFILES=(bazel-out/host/bin/external/bazel_tools/tools/android/zip_manifest_creator.runfiles)
  $RUNFILES_MANIFEST_FILE=(bazel-out/host/bin/external/bazel_tools/tools/android/zip_manifest_creator.runfiles/MANIFEST)
  $IS_WINDOWS=(false)
  find=(bazel-out/host/bin/external/bazel_tools/tools/android/zip_manifest_creator.runfiles/bazel_tools/tools/zip/zipper
bazel-out/host/bin/external/bazel_tools/tools/android/zip_manifest_creator.runfiles/bazel_tools/tools/zip/zipper/zipper
bazel-out/host/bin/external/bazel_tools/tools/android/zip_manifest_creator.runfiles/__main__/external/bazel_tools/tools/zip/zipper
bazel-out/host/bin/external/bazel_tools/tools/android/zip_manifest_creator.runfiles/__main__/external/bazel_tools/tools/zip/zipper/zipper)
Use --strategy=ZipManifestCreator=standalone to disable sandboxing for the failing actions.
____Building complete.

**Comment by katre** [comment]
The find command finds four different copies of zipper, and so the ZIPPER variable is all of them concatenated together, with spaces between. We need to fix the find call to only find the first executable.

**Comment by aj-michael** [comment]
To give some context, we use `find` here because the paths are different in internal and external Bazel. Perhaps there is a better way?

Have we verified that 93dc21f fixed the issue? And do we know why we couldn't repro it locally? I'm a little worried because if I am reading the debug output correctly, the first result is a directory, not the executable.

**Comment by laszlocsomor** [comment]
> Have we verified that 93dc21f fixed the issue?

Yes, it's passing on CI post-push.

> the first result is a directory, not the executable.

That's because the "find" that prints the debug info uses different flags than the "find" that actually tries to find zipper. Namely the debugging one was just looking for anything called "zipper" (so it matched the "zipper" binary and its parent directory too, also called "zipper"), while the actual ones match the path "*/tools/android/zipper/zipper", so it couldn't possibly match the parent directory. (The four matches were the two parent directories and two files.)
