### ISSUE TITLE
Add --auto_output_filter flag

### ISSUE THREAD

**Issue by cushon** [bazelbuild/bazel#3330]
Bazel should have an `--auto_output_filter=(none|all|packages|subpackages)` flag to help prevent build log spam when compiler warnings are enabled.

If no [`--output_filter`](https://docs.bazel.build/versions/master/bazel-user-manual.html#flag--output_filter) option is given, `--auto_output_filter` would cause a filter to be created from the targets listed on the command line:

* `none` does no filtering and shows all output.
* `all` filters everything and shows no output.
* `packages` shows only the output for the packages of targets requested on the command line. 

    For example, the Blaze invocation

    ```
      % blaze build //foo:bar //baz/...
    ```

    will show the output for all targets in the package foo or any package under baz. Warnings for dependencies in other packages will be hidden. Corresponding packages under `//java` and `//javatests` will be treated as a single package. For example

    ```
      % blaze test //javatests/com/google/foo:bar
    ```
    will also show the output for the `java/com/example/foo` package.
* `subpackages` (the default) works similar to packages but also includes output from subpackages.

**Comment by meisterT** [comment]
The option exists now: https://cs.opensource.google/bazel/bazel/+/f17c403b2365ff0268b0ecae2e00e95fcad9d36b:src/main/java/com/google/devtools/build/lib/outputfilter/OutputFilteringModule.java;l=41;drc=62dd17438bcde06ccbed361f6594a6cf96fb3a07

https://docs.bazel.build/versions/master/command-line-reference.html#flag--auto_output_filter
