### ISSUE TITLE
persistent JavaBuilder may have incremental correctness problems due to caching in ServiceLoader

### ISSUE THREAD

**Issue by cushon** [bazelbuild/bazel#3332]
A related issue was discovered with Buck and Error Prone (which uses ServiceLoader for plugins). See discussion https://github.com/google/error-prone/issues/588#issuecomment-290876037. We should make sure that the javac worker doesn't have the same problem, and maybe have it disable caching (see google/error-prone#604).

**Comment by cushon** [comment]
@philwo FYI

**Comment by ulfjack** [comment]
This isn't a regression, right?

**Comment by cushon** [comment]
Not a regression. I wasn't planning to work on this, but I thought someone might want to investigate whether it could be causing incorrect incremental builds for Bazel users.

**Comment by cushon** [comment]
Downgrading priority based on (in)activity, but I still think it's worth investigating.
I'm also not sure why this was assigned to me.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
