### ISSUE TITLE
Generated doc pages have edit link that 404s

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3335]
https://docs.bazel.build/versions/master/skylark/lib/ctx.html has a link to edit that goes to https://github.com/bazelbuild/bazel/tree/master/site/docs/skylark/lib/ctx.md. Since this documentation page is generated it doesn't actually have a page to go to to edit, which is a poor experience. Either linking to the code which the documentation is extracted from or not having the edit link would be better.

**Comment by laszlocsomor** [comment]
@steren : let me know if you can work on this, otherwise i'll find a different assignee

**Comment by steren** [comment]
Indeed everything under https://docs.bazel.build/versions/master/skylark/lib/ should not have an edit button.
Let me send a change (code here: https://github.com/bazelbuild/bazel/blob/master/site/_layouts/documentation.html#L118)

**Comment by steren** [comment]
Note that our docs do not auto-deploy (anymore). So the change should be released at the next documentation push.

@davidzchen could you trigger it?

**Comment by davidzchen** [comment]
The push job was broken for some period of time, but @damienmg has fixed it, and the push is working again.
