### ISSUE TITLE
Remote Execution Action output_files are not sorted

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#3337]
### output_files members of Actions in ExecuteRequests are not guaranteed to be sorted:

From the remote_execution.proto inline documentation:

_// In order to ensure consistent hashing of the same Action, the output paths_
_// MUST be sorted lexicographically by code point (or, equivalently, by UTF-8_
_// bytes)._

### To reproduce:

Attempt to compile any C/C++ file.c[c] via remote execution, observe `file.pic.o` preceding `file.pic.d` in the output_files list of google.devtools.remoteexecution.v1test.Action to be sent via ExecuteRequest to Execution#Execute

### Environment info
* Operating System: Linux

* Bazel version (output of `bazel info release`):

development version

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

master - 4ca8b8f98f043ef624b2d1605d658aa39c2c63dc

**Comment by ulfjack** [comment]
Do we need this in 0.5.3?

**Comment by ola-rozenfeld** [comment]
No, but I will send a fix right away! Can't believe I added a comment "// Somewhat ugly: we rely on the stable order of outputs here for remote action caching." instead of just sorting them :-/
