### ISSUE TITLE
Ensure that Bazel releases are built with "-c opt".

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#3340]
In #3280 we noticed that (some parts of?) Bazel releases are not build with "-c opt" which might result in decreased performance.

@cushon thinks we should make sure that releases are built with "-c opt".

IMHO this is a good idea, but we have to ensure that stack traces etc. still work fine at least for the Java part, as otherwise bug reports from users will be most useless. (I think this is the case and all will be fine, but we should just make sure.)

**Comment by cushon** [comment]
For singlejar this is specifically about host tools that are packaged with Bazel. Using opt builds would be consistent with how they would be built from source with `--distinct_host_configuration=true` enabled.

`--compilation_mode` has no effect on Java code, including stack traces, it expands to c++ compiler flags.

**Comment by damienmg** [comment]
I think this can wait until the new pipeline is rolled-out since this will be just the matter of adding a flag in configuration file.

**Comment by damienmg** [comment]
Sent https://bazel-review.googlesource.com/c/bazel/+/15930
