### ISSUE TITLE
Support prefixing include paths for new_http_archive

### ISSUE THREAD

**Issue by pbos** [bazelbuild/bazel#3342]
See example with `sign_in.cc` using `openssl` as an external library here: https://docs.bazel.build/versions/master/be/workspace.html

In this example, OpenSSL contains `src/openssl.h` which is then used by `sign_in.cc` as `#include "src/openssl.h"`. This gets very awkward for C++ targets that use more generic names such as `image.h` for their headers and risks colliding with other libraries (what library provides `src/image.h`?). Internal header files included by `src/openssl.h` probably also risk collisions in turn?

For C++ targets it'd be useful to be able to rewrite these paths and not just strip archive prefixes, so `src` -> `third_party/openssl` for this archive, or possibly set up a symlink to the pseudo-path `external/openssl`, so that source files depending on external libraries can use a more reasonable include path without importing them into the workspace (`#include "external/openssl/src/openssl.h`). How should workspaces be dealing with many external library dependencies?

Also, what happens now if two new_http_archive libraries contain say `src/string.h`, and a target depends on both of them?

**Comment by pbos** [comment]
Sorry, the latter (`external/openssl/foo`) actually appears to work. I updated my include paths to not be in third_party, and use `new_http_archive` now. In my case this becomes `#include "external/sfml/include/SFML/Graphics.hpp"`.

If this is the recommended way to work with `new_http_archive`-imported C++ dependencies, could the documentation be updated to reflect that this is the preferred include path, or list it as a supported include path, rather than the `src/include.h` in the example?

**Comment by laszlocsomor** [comment]
Thanks for filing the bug and for the follow-up.
Do you want to update the docs? If you have a good idea for wording, I'd be happy to review the change.

**Comment by pbos** [comment]
Sure, I can do that. Can you confirm that `#include "external/<archive-name>/path/to/hdr.h"` is the preferred/supported way to do this? I've only tested it on Windows and it happens to work.

**Comment by laszlocsomor** [comment]
Thanks!

> Can you confirm that #include "external/<archive-name>/path/to/hdr.h" is the preferred/supported way to do this?

No, I can't, although I've found this to be a working solution too. @ulfjack : do you know who could confirm this with authority?

**Comment by aiuto** [comment]
This is a feature request for http_archive. It is essentially code rewriting while importing. Like  having integrated [Copybara](https://github.com/google/copybara) rewrites. Interesting idea, and probably can be done as an add on tool rather than in the bazel source itself.
