### ISSUE TITLE
new_http_archive doesn't support HTTP 303 redirects

### ISSUE THREAD

**Issue by pbos** [bazelbuild/bazel#3343]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

A library I'm using uses a http redirects to distribute downloading over several mirrors.

`BUILD:1:1: no such package '@sfml//': Error downloading [https://www.sfml-dev.org/files/SFML-2.4.2-windows-vc14-32-bit.zip] to C:/users/msft/appdata/local/temp/_bazel_msft/iy6bww2k/external/sfml/SFML-2.4.2-windows-vc14-32-bit.zip: GET returned 303 See Other and referenced by '//foo:foo'.`

This HTTP 303 should've taken bazel to `http://mirror0.sfml-dev.org/files/SFML-2.4.2-windows-vc14-64-bit.zip` (for example). Bypassing the load balancing here seems like bad karma, so `bazel` should probably be OK with `HTTP 303` and just redirect (but avoid redirect cycles or have a N jump limit)?

### If possible, provide a minimal example to reproduce the problem:

WORKSPACE:
new_http_archive(
    name = "sfml",
    url = "https://www.sfml-dev.org/files/SFML-2.4.2-windows-vc14-64-bit.zip",
    sha256 = "93f372582f7216a7f41c18b8f46cd1c6f26881c695b05747aa08b1fd06072dd7",
    build_file = "third_party/sfml.BUILD",
)

Create a target that depends on `@sfml`, and then `bazel build` it.

### Environment info
* Operating System:
Windows 10

* Bazel version (output of `bazel info release`):
release 0.5.2

**Comment by laszlocsomor** [comment]
Please paste or attach `third_party/sfml.BUILD` -- I followed the repro instructions and Bazel is missing this file.

**Comment by laszlocsomor** [comment]
Eh, never mind, I wrote a dummy build file and see the same error:
```
(13:17:25) ERROR: C:/tempdir/scratch/BUILD:1:1: no such package '@sfml//': Error downloading [https://www.sfml-dev.org/files/SFML-2.4.2-windows-vc14-64-bit.zip] to C:/users/laszlocsomor/appdata/local/temp/_bazel_laszlocsomor/fehkyibx/external/sfml/SFML-2.4.2-windows-vc14-64-bit.zip: GET returned 303 See Other and referenced by '//:foo'
(13:17:25) ERROR: Analysis of target '//:foo' failed; build aborted
(13:17:25) INFO: Elapsed time: 1.185s
(13:17:25) FAILED: Build did NOT complete successfully
```

**Comment by laszlocsomor** [comment]
For the record, this is the workaround:

1. download the file to e.g. `c:/foo/SFML-2.4.2-windows-vc14-32-bit.zip`
2. `cd c:\foo` then `python -m SimpleHTTPServer`
3. update the `new_http_archive.url` value to `http://localhost:8000/SFML-2.4.2-windows-vc14-64-bit.zip`

**Comment by laszlocsomor** [comment]
Bazel built at head also cannot handle http response 303.

**Comment by pbos** [comment]
My workaround was to manually follow the HTTP303 in Chrome and use mirrorX.foo.bar url instead, but I'm hesitant to publish that. :)

**Comment by laszlocsomor** [comment]
That's even easier than downloading and running a local webserver.

**Comment by damienmg** [comment]
Is there anything left to do here? If not please close :)

**Comment by laszlocsomor** [comment]
Yes there is: the repo rules don't handle HTTP 303, but they should.
We have a manual workaround so this isn't blocking builds.

**Comment by damienmg** [comment]
Ok sorry I did not read correctly your comment, I though it was fixed at head, also the rules is no assignee before someone is actually selected to do the job :)
