### ISSUE TITLE
aspect function doesn't document all of its arguments

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3346]
https://docs.bazel.build/versions/master/skylark/lib/globals.html#aspect

The arguments of `required_aspect_providers` and `provides` are undocumented beyond that they are supposed to be `sequences`. This is not useful enough to actually know how to use them.

**Comment by endobson** [comment]
It looks like the current documentation is the string `<not available>`, which gets treated as markup and thus not even visibly shown in the generated html.

**Comment by c-parsons** [comment]
This issue seems obsolete -- the documentation for these fields is now present and plentiful.
(Please feel free to reopen if the documentation is unsatisfactory, with specific feedback!)
