### ISSUE TITLE
Output looks similar for rebuilds and new builds

### ISSUE THREAD

**Issue by pbos** [bazelbuild/bazel#3350]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

The [17/17] compiling foo.cc is not present after compilation finishes (maybe a newline should be posted before Target). If I don't look at the output while it's building it looks like `bazel` didn't correctly rebuild anything. 

### If possible, provide a minimal example to reproduce the problem:
C:\Users\msft\Dev\highfive>bazel clean
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.

C:\Users\msft\Dev\highfive>bazel build ace
INFO: Found 1 target...
Target //ace:ace up-to-date:
  C:/users/msft/appdata/local/temp/_bazel_msft/iy6bww2k/execroot/__main__/bazel-out/msvc_x64-fastbuild/bin/ace/ace.exe
INFO: Elapsed time: 11.399s, Critical Path: 2.46s

C:\Users\msft\Dev\highfive>bazel build ace
INFO: Found 1 target...
Target //ace:ace up-to-date:
  C:/users/msft/appdata/local/temp/_bazel_msft/iy6bww2k/execroot/__main__/bazel-out/msvc_x64-fastbuild/bin/ace/ace.exe
INFO: Elapsed time: 0.519s, Critical Path: 0.01s

While building the first one, I saw X/17 files compiling, but when done it looked like this didn't even have to build the program. Note the big difference in Elapsed time, and the latter command doesn't say something like "is already up-to-date".

### Environment info
* Operating System:

Windows 10

* Bazel version (output of `bazel info release`):

release 0.5.2 

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by laszlocsomor** [comment]
The log says:
> ```
> Target //ace:ace up-to-date:
> ```
in both cases. The much lower completion time also indicates that this was a null build. Bazel doesn't count how many actions it would've executed had it been a clean build, because that'd take extra time for the benefit of a number that doesn't even say much; in a normal edit-rebuild cycle you normally run incremental builds, not clean ones.

> If I don't look at the output while it's building it looks like bazel didn't correctly rebuild anything.

Why do you think it didn't correctly rebuild anything?

**Comment by pbos** [comment]
I think I'm used to `ninja`'s output which will keep the `[foo/X] linking Y` as the last line when you're building, and spit out everything up to date when it's not rebuilding anything, so it explicitly distinguishing between a build where it has to do something and one where it hasn't.

But it could also be that I'm more vigilant because I'm actively being bitten by #3202 because it's still in the latest binary release, so take this with a grain of salt (feel free to close it).

**Comment by laszlocsomor** [comment]
I sounds like a matter of taste. I don't feel like taking sides here, but for what it's worth, changing the UI would involve some work, and if everything is working fine, I don't see the value.

> But it could also be that I'm more vigilant because I'm actively being bitten by #3202 because it's still in the latest binary release, so take this with a grain of salt (feel free to close it).

Fair enough. Perhaps you'd find `--show_task_finish` and `--curses=no` useful?

**Comment by laszlocsomor** [comment]
Closing as WAI.

**Comment by pbos** [comment]
I think I can just live with uncertainty until 0.5.3. Thanks!
