### ISSUE TITLE
iOS Extension targets fail to generate dSYMs

### ISSUE THREAD

**Issue by bkase** [bazelbuild/bazel#3351]
Hi, I've found a bug in generating dsyms on ios extensions. Is this a known issue? Is there some flag I'm missing?

### Description of the problem / feature request / question:

When ` --apple_generate_dsym` is passed as a flag for an ios extension target (tested with a ShareExtension and SiriExtension). The following error occurs:

```
ERROR: iOS/BUILD:51:1: output 'iOS/ShareExtension.apple_binary.app.dSYM.temp.zip' was not created.
ERROR: iOS/BUILD:51:1: not all outputs were created or valid.
```

### Environment info
* Operating System:
macOS 10.12.5

* Bazel version (output of `bazel info release`):
`release 0.5.2`

###  Have you found anything relevant by searching the web?

I haven't

**Comment by laszlocsomor** [comment]
We need more data. Please provide simple repro instructions.

**Comment by laszlocsomor** [comment]
By "more data" and "repro instructions" I mean:
- what is a minimal set of BUILD and source files (and WORKSPACE file, if relevant) that I need to create to repro the problem you were seeing
- what target did you build
- what flags exactly you used

**Comment by bkase** [comment]
Sorry about that! This was misdiagnosed (realized when trying to get more data). It's a combination of crosstool and dsyms (not just extensions). I or one of my coworkers will open up another issue when we narrow it down.
