### ISSUE TITLE
Headers not propagated from objc_library to cc_library.

### ISSUE THREAD

**Issue by chetgnegy** [bazelbuild/bazel#3352]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
I have lots of purely C++ libraries that depend on a library that internally uses Objective C (when built on OSX). The Objective C is not exposed through any header in this library. 

### If possible, provide a minimal example to reproduce the problem:
TestFolder/my_header.h
```
int k = 0;
```

TestFolder/test.cc
```
#include "TestFolder/my_header.h"
#include <stdio.h>
int main(void) { printf("%d\n", k); }  // k is defined in the header.
```

TestFolder/BUILD
```
objc_library(
    name = "ObjcLib",
    hdrs = ["my_header.h"],
)

cc_binary(
  name = "Test",
  srcs = ["test.cc"],
  deps = [":ObjcLib"],
)
```

If I make both libraries cc_* targets this works. If I make both libraries objc_* targets this works. I don't want a single objc_library to infect all of my C++ code. This code needs to compile on both OSX and on Linux, where objc_library presumably doesn't work.

I actually care about this example below, but the above is a simplified version of what is likely the same issue:

TestFolder/BUILD
```
cc_library(   # I don't really care if this is a cc or objc library.
    name = "TextualHeaderTarget",
    textual_hdrs = ["my_header.h"],
)

objc_library(
    name = "ObjcLib",
    srcs = [":TextualHeaderTarget"],
)

cc_binary(
  name = "Test",
  srcs = ["test.cc"],
  deps = [":ObjcLib"],
)
```
### Environment info
* Operating System:
OSX 10.11.6

* Bazel version (output of `bazel info release`):
release 0.5.2-homebrew

Related:
https://groups.google.com/forum/#!msg/bazel-discuss/IAtDeYJ4Mi8/HWhQ_K9TryMJ
I didn't see any issues that were obviously related. This looks like a way to perhaps hack around the issue:
https://github.com/bazelbuild/bazel/issues/2420

**Comment by chetgnegy** [comment]
Please let me know if you have any suggestions for workarounds. I am blocked on this at the moment. Thanks!

**Comment by chetgnegy** [comment]
Has there been any progress here? An ETA?

**Comment by calpeyser** [comment]
https://github.com/bazelbuild/bazel/commit/db61b316458685344d3aa4b6a784f09001a90892 should have addressed this, please let us know if your problem continues.

**Comment by chetgnegy** [comment]
Thanks, Cal. I'm still finding that I can't build the example above at version 0.11.0.

**Comment by calpeyser** [comment]
It doesn't look like db61b31 is in Bazel 0.11.0: https://github.com/bazelbuild/bazel/commits/0.11.0

**Comment by chetgnegy** [comment]
How does whoever prepares releases decide what commits will make the cut? It looks like it's not in 0.12.0 either, even though newer changes are included and this one is many months old. I'm fumbling around with building it from source now.

**Comment by chetgnegy** [comment]
It builds my test examples now. Thanks!

**Comment by calpeyser** [comment]
Glad it works! For posterity, this was 968f87900dce45a7af749a965b72dbac51b176b3.
