### ISSUE TITLE
Provider generated documentation seems to incorrectly describe old style providers

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3353]
I'm trying to figure out what baked in providers are available and how to access their data.

The prose documentation for providers talks both about the new way of access and the old way of access. (https://docs.bazel.build/versions/master/skylark/rules.html#providers).

The generated documentation (https://docs.bazel.build/versions/master/skylark/lib/skylark-provider.html) says:
> Rule implementation functions can access them via target.[provider name]

I'm trying to access the `FilesToRunProvider`. So following that documentation I substitute in `FilesToRunProvider`.
I tried all the following because the color/font choice makes it hard to determine what is the meta variable.
* `target.[FilesToRunProvider]` 
* `target.FilesToRunProvider` 
* `target[FilesToRunProvider]` 

None of these work, but what does is `target.files_to_run`, which is a non trivial transformation of FilesToRunProvider.

I think until all the default providers are available in the new way, that this line be removed from the docs and each provider on its individual page explain if it is accessible in the new way or what string it is available at in the old way.

Using bazel from c6bd5166d1c558fb8f619b53eb4c56fa7cee8b93.

**Comment by laszlocsomor** [comment]
Asking @laurentlb and @vladmos to comment.

**Comment by laurentlb** [comment]
I believe the documentation has been updated since this bug was filed. Please reopen if it's still not clear.

We are actively removing old-style providers, they should disappear soon.
