### ISSUE TITLE
How to use custom providers as an abstraction is unclear

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3354]
From the documentation on providers it seems that providers are both meant to be a namespacing mechanism (same textual names but different bindings don't clash) and an trust mechanism (some core providers can only be created by core libraries, only inspected by others).

Yet I cannot see how the second feature can be achieved with new style providers. Because the key to access a provider instance on an existing target is the same value as the constructor used to construct new values. Thus a bzl file cannot export the first without exporting the second.

If providers are supposed to allow only trusted creation as currently the core providers are, then I would like this to be a feature request for the ability to do that with new style custom providers.

If this is not a desired feature then it should be removed from the documentation. In particular I couldn't find a single exposed Provider that didn't allow instance creation. Most were not actually exposed and I could only get provider instances through the old style interface.

**Comment by laszlocsomor** [comment]
Asking @laurentlb and @vladmos to comment. The new-style providers are a relatively new feature as far as I could trace their origin, the docs were added in April 2017 (https://github.com/bazelbuild/bazel/commit/3b5f9bd49d4e891aa3ca07e30a28158f1184c3db). So I'm asking @dslomov too to comment.

**Comment by dslomov** [comment]
We do not intend new providers to be a trust mechanism.
The intention is actually opposite, as per [Bazel sandwich](https://bazel.build/designs/2016/08/04/extensibility-for-native-rules.html): providers are used to interface between rules, and any rule should be able to communicate needed information to another rule, e.g. `scala_library` should be able to provide needed information to a `java_library` etc.

What would make sense though is more validation for declared providers at creation time. Some ideas for that are in [Declared Providers design doc](https://bazel.build/designs/skylark/declared-providers.html), see "Stage 2". I am planning to implement that very soon, but we also have some ideas for adding even more validation.

**Comment by endobson** [comment]
Then is the documentation incorrect then, or are there examples of exposed Providers that don't allow instance creation (and not just instances of providers that cannot be created)? I don't understand what that line is trying to tell the reader about providers. Being italicized seems like it is trying to convey something important, but unless there is an overarching point for providers that cannot be constructed then it seems like that is a minor point, because all it is saying is that the only way to construct provider instances is through the Provider which is impossible if the provider isn't exposed.

**Comment by dslomov** [comment]
Sorry, which line are you referring to?

**Comment by endobson** [comment]
Sorry thought I had included that before:
https://docs.bazel.build/versions/master/skylark/lib/Provider.html
> Some providers, defined internally, do not allow instance creation
