### ISSUE TITLE
genrule ignores executable attribute

### ISSUE THREAD

**Issue by twpayne** [bazelbuild/bazel#3359]
### Description of the problem:

When using `genrule` on macOS, the output file always has permissions `-r-xr-xr-x`, even if `executable = 0` is specified.

### Minimal example to reproduce the problem:

`BUILD.bazel`:
```python
genrule(
    name = "gen-foo",
    outs = ["foo"],
    cmd = "echo > $@",
    executable = 0,
)
```

Example run:

```
$ bazel build :gen-foo
...
$ ls -l bazel-genfiles/foo
-r-xr-xr-x  1 user  group  1 Jul 11 16:10 bazel-genfiles/foo
```

`foo` has executable permissions, but it should not.

Note that the [documentation for the `genrule` `executable` attribute](https://docs.bazel.build/versions/master/be/general.html#genrule.executable) states that default value for `executable` is `0`. So, by default, it seems that all `genrule`s are generating files with executable permissions.

### Environment info
* Operating System: macOS Sierra 10.12.5
* Bazel version: `release 0.5.2-homebrew`

Nothing relevant by searching the web. Checked StackOverflow and `bazel-discuss` with the search term "bazel genrule executable".

https://github.com/bazelbuild/bazel/issues/918 is possibly relevant.

**Comment by EricCousineau-TRI** [comment]
This seems to also be a problem on Linux (and Mac). Example downstream issue:
https://github.com/robotlocomotion/drake/pull/13143#pullrequestreview-400912629

Any chance this issue can be renamed to be more general?

Needed to update the repro stuff, wrapped it in a bash script:
```sh
#!/bin/bash
set -eux

cd $(mktemp -d)

cat > WORKSPACE.bazel <<'EOF'
workspace(name = "repro")
EOF

cat > BUILD.bazel <<'EOF'
genrule(
    name = "gen-foo",
    outs = ["foo"],
    cmd = "echo > $@",
    executable = 0,
)
EOF

bazel build :gen-foo
ls -l bazel-bin/foo | sed "s#${USER}#user#g"

# Output:
# -r-xr-xr-x 1 user user 1 Apr 28 18:08 bazel-bin/foo
```

Environment info:
* Operation System: Ubuntu 18.04
* Bazel version:
```
$ bazel version
Build label: 2.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Feb 7 13:01:04 2020 (1581080464)
Build timestamp: 1581080464
Build timestamp as int: 1581080464
```

**Comment by philwo** [comment]
I was able to reproduce this on Linux. The output file is indeed always marked as executable, the `executable` attribute is ignored.

**Comment by twpayne** [comment]
I'm not currently using Bazel so I don't have skin in the game at the moment, so feel free to ignore this, but I think this should be fixed. Reasoning:

The genrule needs to set `executable = 0` to manifest the bug. This is an explicit statement of intent by the user, so I think it's unlikely to break existing genrules.

If existing genrules are impacted by the bug, then I suspect that the users already have extra rules to work to strip the executable permissions. These extra rules will be unaffected by fixing the bug: the stripping of executable permissions will just become a no-op.

And kinda relevant, kinda not, in the past the Bazel project has not been shy about making large changes that affect existing genrules. The current behavior does not match either the documentation or what is expressed in the genrule itself, so I think it is a clear bugfix.

If the bug is not fixed then the documentation should be updated to reflect the current behavior instead.

**Comment by aiuto** [comment]
@twpayne has a point.  This is worth considering. 
Of course, it is not trivial. We really need a notion of what the modes of a file should be (device independent, of course) and carry that through to runfiles so that when we package them they show up with the right modes. For example, if a pkg_tar rule depends on the output of a rule that says executable=0, the file should be r--r--r-- in the tarball - even if the underlying bazel-bin blob store has no respect for permissions.

**Comment by mwoehlke-kitware** [comment]
So, I just ran into this... *Why is this even a thing*? Why is Bazel altering the permissions of the output file *at all*? Maybe that makes sense as a convenience if you're using some unusual mechanism to produce an executable (i.e. `executable = 1`), but it's just plain wrong for anything producing data files, which I suspect is a more common use case of `genrule`.

A simple, backwards-compatible fix would be to add a `permissions` or similar argument to `genrule` that defaults to the historic value. Preferably with a magic string (probably just the *empty* string) that says "don't change them". Personally, though, I would argue that "don't change them" should be the default.
