### ISSUE TITLE
Bazel fails to respect 'external' tag on tests when remote caching is enabled

### ISSUE THREAD

**Issue by jgavris** [bazelbuild/bazel#3362]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

Some of our tests are tagged with `external` and should not be cached. We've observed that when remote caching is enabled, a test that normally takes 60 seconds reports as taking 0 seconds (and is not run at all). 

### If possible, provide a minimal example to reproduce the problem:

I've put together a minimal workspace [here](https://github.com/ButterflyNetwork/bazel-external-caching) with two scripts that can demonstrate the issue. The only requirement is a remote REST cache server. 

Running `time ./test_local.sh` should take longer than 5 seconds (due to the sleep in the test). 
Running `time ./test_remote.sh` should take longer than 5 seconds (also due to the sleep in the test, and the `external` tag). This test passes in 0.0s.

### Environment info
* Operating System:
macOS 10.12.5

* Bazel version (output of `bazel info release`):
release 0.5.2-homebrew

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by laszlocsomor** [comment]
@ulfjack : You are (or have recently been) looking at cleaning up test strategies, does this ring a bell?

**Comment by ulfjack** [comment]
Sounds like a bug. I'm not really surprised, except maybe that people are actually using remote caching.

**Comment by jgavris** [comment]
@ulfjack We'd certainly like to!

**Comment by buchgr** [comment]
Fix coming ...

**Comment by jgavris** [comment]
Tested, looks great! Thanks.
