### ISSUE TITLE
OS_WINDOWS redefined

### ISSUE THREAD

**Issue by snnn** [bazelbuild/bazel#3366]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

OS_WINDOWS is already defined in C:\Program Files (x86)\Windows Kits\10\Include\xxxx\um\Shlwapi.h, which is a part of Windows SDK.

	#ifndef NO_SHLWAPI_ISOS

	// Returns TRUE/FALSE depending on question
	#define OS_WINDOWS                  0           // Windows 9x vs. NT
	#define OS_NT                       1           // Windows 9x vs. NT
	#define OS_WIN95ORGREATER           2           // Win95 or greater
	#define OS_NT4ORGREATER             3           // NT4 or greater
	#define OS_WIN98ORGREATER           5           // Win98 or greater
	#define OS_WIN98_GOLD               6           // Win98 Gold (Version 4.10 build 1998)
	#define OS_WIN2000ORGREATER         7           // Some derivative of Win2000
	//...
	#endif

### Environment info
* Operating System:
Windows 10

* Bazel version (output of `bazel info release`):
development version

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
937350211dcd55a4714ec32ebbf33fffcc42cdf2

**Comment by laszlocsomor** [comment]
I need more context: is this causing any problems, and what?

The only place I see `OS_WINDOWS` in the source is in https://github.com/bazelbuild/bazel/blob/master/tools/cpp/CROSSTOOL and https://github.com/bazelbuild/bazel/blob/master/tools/cpp/CROSSTOOL.tpl

**Comment by snnn** [comment]
If bazel is used to compile any file who includes 'Shlwapi.h', vc will generate a warning for that. e.g.

2017-07-12T08:08:39.7826155Z INFO: From Compiling tensorflow/core/platform/windows/env.cc [for host]:
2017-07-12T08:08:39.7826155Z C:\Program Files (x86)\Windows Kits\8.1\include\\um\Shlwapi.h(2024): warning C4005: 'OS_WINDOWS': macro redefinition
2017-07-12T08:08:39.7826155Z C:\Program Files (x86)\Windows Kits\8.1\include\\um\Shlwapi.h(2024): note: command-line arguments:  see previous definition of 'OS_WINDOWS'

Not a real problem. I am just curious why do you need this macro? If it is really needed, maybe you can also define NO_SHLWAPI_ISOS to get rid of this conflict.

**Comment by laszlocsomor** [comment]
I see, thanks for explaining that! @meteorcloudy : WDYT?

**Comment by meteorcloudy** [comment]
I think we should just remove `/DOS_WINDOWS` from our CROSSTOOL, no one is or should be depending on this in CROSSTOOL.
