### ISSUE TITLE
Allow JavaProvider(java_common.provider) to expose transitive_compile_time_jars (for scala strict deps)

### ISSUE THREAD

**Issue by natansil** [bazelbuild/bazel#3367]
We are in the process of adding a `strict deps` feature for `rules_scala` ([issue](https://github.com/bazelbuild/rules_scala/issues/235)).

In order to complete this feature we would like for javaProvider (java_common.provider) to expose [transitive_compile_time_jars](https://github.com/bazelbuild/bazel/blob/937350211dcd55a4714ec32ebbf33fffcc42cdf2/src/main/java/com/google/devtools/build/lib/rules/java/JavaSkylarkCommon.java#L95).
(Currently JavaProvider only exposes [transitive_runtime_jars](https://github.com/bazelbuild/bazel/blob/77baa4c372ae014db8e17f6d3c60bd88597853d9/src/main/java/com/google/devtools/build/lib/rules/java/JavaProvider.java#L179) and [compile_jars](https://github.com/bazelbuild/bazel/blob/77baa4c372ae014db8e17f6d3c60bd88597853d9/src/main/java/com/google/devtools/build/lib/rules/java/JavaProvider.java#L183))

This will allow us to alert the build user that there transitive dependencies that should be added to direct dependencies.

**Comment by laszlocsomor** [comment]
Asking @laurentlb to help triage this: is this a Skylark feature request, or a Java rule one?

**Comment by dslomov** [comment]
Java rules /cc @iirina

**Comment by natansil** [comment]
Thanks @iirina!
Do you know when is the next scheduled release of bazel?

**Comment by buchgr** [comment]
We are trying to cut the first release candidate of 0.5.3 as we speak.
