### ISSUE TITLE
Print a warning to UI when remote execution / caching fails and local fallback enabled.

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#3368]
I noticed that remote execution / caching fails silently and bazel falls back to local execution. It seems completely transparent to a user whether a build was executed remotely or locally. We should print a warning to the UI saying that the whole or parts of the build were executed locally due to remote execution / caching failures.

cc: @ulfjack @ola-rozenfeld

**Comment by jgavris** [comment]
+1 ... other interesting stats could be the overall cache hit rate for the build, overall cache product size etc

**Comment by ulfjack** [comment]
I think there was code to print a warning, but I removed it as there was no good place for it. Maybe I left a todo? That said, warnings are generally ignored, and we also don't want to spam a warning for every single action (that could be thousands of them). If we add stats (for which there's a separate issue), maybe we should say how often we fell back to local execution?

**Comment by buchgr** [comment]
That's happening. Can be closed.
