### ISSUE TITLE
load() does not work in WORKSPACE file

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#337]
Assigning to Damien because he was planning to work on Skylark support for WORKSPACE files.

**Comment by damienmg** [comment]
Ok as talked offline, will be resolved by the skylark remote repository. I will pass over all the bug related to it and consolidate them when I have a bit more time

**Comment by mrdomino** [comment]
Any updates on this? It'd be helpful for my purposes.

**Comment by damienmg** [comment]
I will start working on that this week or next week. The prototype is
already out there at
https://github.com/damienmg/bazel/tree/skylark-remote-repository?files=1

**Comment by damienmg** [comment]
Ok I haven't finished my first change and I am going to be out for 4 weeks so this will be delayed. Sorry for that.

**Comment by chin33z** [comment]
Any updates? Really need this feature! Thanks.

**Comment by damienmg** [comment]
Sorry I am back from a 4 weeks leave and I had to work on some emergency
stuff I should restart working on that tomorrow. The problem is that since
I did my initial prototype a lot have change in the Skylark environment and
I have to handle the change.

**Comment by lberki** [comment]
@damienmg: let me know if I can help -- this is quite an important feature and I'm willing to spend time on it :)

**Comment by damienmg** [comment]
Sure :) I am starting again to work on it right now.

**Comment by chin33z** [comment]
Just curious, will this feature come independently before "P1. Custom remote repositories using Skylark" finish? I think the two were relative but still independent from user aspect.
Thanks.

**Comment by damienmg** [comment]
Yes this feature is the first step of the custom remote repositories so it will be available first. I am still having issues with making it work with the environment change but that shouldn't be too long until this is rolled-out.

**Comment by benley** [comment]
yessssssssss thank you

**Comment by davidzchen** [comment]
Woohoo! \o/

**Comment by chin33z** [comment]
THANKS!!
