### ISSUE TITLE
Expose Bazel binary itself under bazel_tools 

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#3371]
### Description of the problem / feature request / question:

I'd like to be able to write end to end tests for bazel rules which:
1. Create a scratch workspace
2. Run bazel build/test
3. Do all kinds of assertions

For step 2 I need to be able to use Bazel much like e2e inside this repo are doing.
For various reasons we were unable to use the targets the current internal tests are using.

A workaround I was able to build entails downloading the installer and installing bazel per test target but that takes 17.5 seconds (!) without fetching the installer.

`WORKSPACE`
```
http_file(
    name = "bazel_for_test",
    url = "https://github.com/bazelbuild/bazel/releases/download/0.5.2/bazel-0.5.2-installer-darwin-x86_64.sh",
    sha256 = "c31a38761b7b21eadccc757774198bc307353cab07c3c496b386f249de2a33dc",
 )
```
`BUILD`
```
sh_test(
    name = "bazel_integration_test",
    srcs = ["bazel_integration_test.sh"],
    data = ["@bazel_for_test//file"],
    args = ["$(location @bazel_for_test//file)"],
)
```
`bazel_integration_test.sh`
```
#!/bin/bash

touch WORKSPACE
#make installer executable
chmod u+x $@
mkdir bazel_install
#install bazel to dir which test can access
./$@ --prefix=bazel_install
./bazel_install/lib/bazel/bin/bazel info
```

This idea to expose Bazel binary itself via a synthetic target was suggested by @dslomov

**Comment by laszlocsomor** [comment]
A more efficient workaround is to create a local repository with the bazel binary in it.

`WORKSPACE`
```
workspace(name = "bazel_on_bazel")

new_local_repository(
    name = "bazel_itself",
    path = "/usr/local/google/home/laszlocsomor/bazel-0.5.2/bin",
    build_file_content = """
exports_files(["bazel"])
"""
)
```

`BUILD`
```
sh_test(
    name = "test_using_bazel",
    srcs = ["test_using_bazel.sh"],
    data = ["@bazel_itself//:bazel"],
)
```

`test_using_bazel.sh`
```
#!/bin/bash
echo "hello from test"
echo "=== find . -not -type d ==="
find . -not -type d
echo "=== done ==="
```

Test output:
```
hello from test
=== find . -not -type d ===
./external/bazel_itself/bazel
./test_using_bazel
./test_using_bazel.sh
=== done ===
```

**Comment by ittaiz** [comment]
Thanks!
Two questions:
1. Is there a generic way to have the path? Because this current path
obviously changes between machines.
2. Does this mean you think this request isn't valid?

**Comment by laszlocsomor** [comment]
> 1. Is there a generic way to have the path? Because this current path obviously changes between machines.

Right. I don't know of any generic way.

> 2. Does this mean you think this request isn't valid?

No! I agree it is valid. I just presented a more efficient workaround for the meantime.

**Comment by ittaiz** [comment]
Great, thanks!
Waiting for more thoughts...

**Comment by ittaiz** [comment]
@damienmg WDYT?

**Comment by damienmg** [comment]
I think this is a correct FR but @ulfjack and @dslomov had some point against it IIRC.

You can also depends on the shell installer from our release, it is a zip file so it can be downloaded and unzipped for integration test.

**Comment by ittaiz** [comment]
@damienmg Did you see my first message? IIUC that's the workaround I published but it takes 17.5 seconds per target. Did you mean something else? The only zip I could find was windows or the sources.
@dslomov / @ulfjack what are the reservations?
I really feel the current testing story of skylark in Bazel is awful.
I'm sorry to be blunt but I just feel that the current situation in Bazel pushes me to either have no tests for bzl files, have E2Es which don't run in bazel (see rules_scala) or pay 20 seconds overhead per target.

**Comment by ulfjack** [comment]
Running Bazel inside Bazel is brittle and slow, making it a very bad user experience. I don't think we should consider it as a long-term solution, but instead have excellent Skylark testing support.

I also don't like it as a short-term solution, because it'll turn into a long-term solution. :-P There's no way we can possibly remove it once it's there, and it's yet another API that we can break when we make changes. Think of every implicit dependency of every built-in rule - we're already struggling with that more than enough. Our ongoing support costs are already high, and I'd rather not add yet another large API surface to the existing set of problems.

**Comment by ittaiz** [comment]
I think the discussion should differentiate between users who develop
extensions (OSS and internal) which need more abilities and so I think are
willing to "pay" more in terms of test time. Effectively what I saw people
do is- Keep the build in maven (2 of our internal plugins), keep the e2e
out of bazel and depend on travis and bash for project correctness
(rules_scala) or just not have e2es.
I think that's a big problem.

Re excellent skylark testing support- I try not to use such tools since
they often give you less feedback and couple you to the assumptions of the
fw. One of the values of having an e2e is to validate the functional need
without coupling it to the specific fw and it's testing utilities.

**Comment by ulfjack** [comment]
Well, if you're an expert, you might want to have hermetic tests, so you'd check in Bazel anyway - why use the host Bazel binary?

What does "fw" mean?

**Comment by ittaiz** [comment]
I agree I want to have hermetic tests.
Checking in Bazel is costly (VCS wise) and depending on a specific version
(like I showed above) is hermetic but costly time wise (17 seconds for the
installation).

:) Sorry. Framework.

**Comment by laszlocsomor** [comment]
@ittaiz : Can you standardize on where people install Bazel on their machine? Or at least have a standardized location where they'd have a directory with a symlink to their own bazel? Then you could use the workaround I suggested.

**Comment by ittaiz** [comment]
I think that will be hard to do.
Also if we think about the other use-case of OSS rules then this adds
another bit of knowledge people need to have before contributing.
Additionally I think that's even less hermetic than exposing the host
binary.

**Comment by petroseskinder** [comment]
+1 on exposing a synthetic Bazel target. On the OSS side, it's undesirable that I have to either (1) download the Bazel installer and install Bazel for each target or (2) manually point to a bazel binary. I can understand concerns that exposing the host binary is not hermitic.

**Comment by ittaiz** [comment]
Thought about another pro for the OSS use-case (or basically anytime you
want to support multiple OS/bazel versions) and that is that when you use
the host binary you easily see in the failed matrix which version/os your
skylark rules fails in.

**Comment by ulfjack** [comment]
I don't see why you need the host binary for getting a test matrix. I also don't see why you couldn't get reliable test results from inside Bazel without running bazel as a subprocess. I'm still unconvinced that this is a good idea.

That said, there aren't a lot of good alternatives for rule testing right now, and I could potentially see us add an interim solution. I'd defer to @dslomov on that, who's 'owning' Skylark.

**Comment by ittaiz** [comment]
Test matrix is just a plus.
Not sure what you mean by reliable. The code that integrates with skylark
can be tested in two ways:
1. By an E2E that uses Bazel and doesn't care exactly how you use skylark,
just what are the inputs and outputs. This requires using Bazel as a sub
process (like many tests in bazel do).
2. By using a testing infrastructure of skylark to validate the
integration. The con with this approach is that the tests are often very
coupled to the testing infrastructure.

**Comment by ulfjack** [comment]
For 2 - I'm not sure why that's a problem. The Skylark rules are very coupled to Bazel, so I don't see a big difference between being coupled to Bazel and being coupled to Bazel Skylark test infrastructure (which is part of Bazel).

**Comment by ittaiz** [comment]
From my experience such tests are usually harder to understand since they
have some assumptions on the world (for example you populate the ctx with
all kinds of stuff for a test case) where in the e2e the tests speak in the
problem domain

**Comment by ittaiz** [comment]
see https://github.com/bazelbuild/bazel-integration-testing

**Comment by laszlocsomor** [comment]
Oh, nice!
