### ISSUE TITLE
DSYM fails to generate with ObjC Crosstool

### ISSUE THREAD

**Issue by jerrymarino** [bazelbuild/bazel#3372]
### Description of the problem / feature request / question:

The DSYM fails to generate with the presence of a crosstool:

Build options:
```
build  --apple_generate_dsym=true  --crosstool_top=//tools/local_config_cc:toolchain --apple_crosstool_top=//tools/local_config_cc:toolchain --apple_crosstool_transition --experimental_objc_crosstool=all
```

Output:

```
INFO: From Linking ios-app/ios-app.apple_binary_bin:
ld: warning: -undefined dynamic_lookup is deprecated on iOS
ERROR: /Users/jerry/Projects/bazel-crosstool-dsym-failure/ios-app/BUILD:3:1: output 'ios-app/ios-app.apple_binary.app.dSYM.temp.zip' was not created.
ERROR: /Users/jerry/Projects/bazel-crosstool-dsym-failure/ios-app/BUILD:3:1: not all outputs were created or valid.
Target //ios-app:ios-app failed to build
```

### If possible, provide a minimal example to reproduce the problem:

I've attached an example project and iOS app that reproduces this.

### Environment info
* Operating System:
`10.12.2 (16C67)`

* Bazel version (output of `bazel info release`):
`release 0.5.2`

###  Have you found anything relevant by searching the web?
https://github.com/bazelbuild/bazel/issues/3228

### Anything else, information or logs or outputs that would be helpful?
The `.bazelrc` in the attached sample project sets `generate_dsym_file` through `--apple_generate_dsym`. It looks like this issue happens in both `rules_apple` and native bazel iOS rules

Here is a test project including a basic iOS app:
[bazel-crosstool-dsym-failure-submit.zip](https://github.com/bazelbuild/bazel/files/1143017/bazel-crosstool-dsym-failure-submit.zip)

The `README` has more info, but simply run `bazel build ios-app`

**Comment by jerrymarino** [comment]
cc @calpeyser do you have any suggestions around this one? It looks like the DSYM is generated during the build, but the `.temp` zip archive isn't working

**Comment by dmishe** [comment]
Hm not sure what I can do here. As a start, Jerry, can you dump your build log with `-s` flag so it's clear what the link action is doing?

**Comment by calpeyser** [comment]
We're working on a solution in the CROSSTOOL to add DYSM generation, hopefully it will go out next week. 

@c-parsons

**Comment by c-parsons** [comment]
Cal, is this done? (See #3940)

**Comment by sergiocampama** [comment]
This should be fixed at head, probably will take a while to get rolled out to a release binary.
