### ISSUE TITLE
Channel failure should not cause the build to fail.

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#3377]
Our remote execution retry strategy is flawed. If an RPC call fails, we retry the RPC call but if the underlying channel fails we don't try to open a new channel. We need to fix this.

**Comment by ola-rozenfeld** [comment]
What is a channel failure? How do we diagnose one? Is that the proper response -- open a new channel? I'm a bit worried with the synchronization on this (multiple threads getting the error at the same time, trying to reopen the same channel multiple times).

**Comment by buchgr** [comment]
Can be closed now that we are using dns load balancing.
