### ISSUE TITLE
remote execution no longer outputs stack trace with --verbose_failures

### ISSUE THREAD

**Issue by ola-rozenfeld** [bazelbuild/bazel#3380]
### Description of the problem / feature request / question:

This was regressed in a recent refactoring, and needs to be brought back, because the stack traces are extremely helpful in debugging most any problems related to remote caching/execution.

**Comment by ola-rozenfeld** [comment]
And it's now broken again by commit bcbd2da340ed24a026729104dc0ba2a71cf70463, which changes the expectations of which exceptions are raised by the Runner.

**Comment by buchgr** [comment]
For anything that you want to be supported, you need to add tests :-). It was technically not broken, because it wasn't clear that it was there in the first place.

**Comment by ola-rozenfeld** [comment]
You're right. Yeah, it didn't occur to me to add a test for messages printouts. Speaking of which, I see you didn't add any tests on bcbd2da either :-)
Will fix.
