### ISSUE TITLE
update aspects docs to not use ctx.action

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/bazel#3390]
The docs at https://docs.bazel.build/versions/master/skylark/aspects.html uses `ctx.action` in its code, but that is deprecated (per https://docs.bazel.build/versions/master/skylark/lib/ctx.html#action).

**Comment by jmhodges** [comment]
Oh, hm, maybe this should be generalized because https://docs.bazel.build/versions/master/skylark/rules.html#actions also uses the deprecreated action style functions.

**Comment by dslomov** [comment]
https://github.com/bazelbuild/bazel/commit/67f42c318f824566e358f705a320f82484bc0540 fixes this.

**Comment by jmhodges** [comment]
Thanks!
