### ISSUE TITLE
How to use well-known types for protobuf in Bazel

### ISSUE THREAD

**Issue by Azure-Vani** [bazelbuild/bazel#3391]
I'd like to use `any.proto` or `descriptor.proto` in my protobuf file and use bazle to build it. The rule I used is proto_library().

But to both `any.proto` and `descriptor.proto` are not exported by protobuf official upstream, and I found **third_part** folder in bazel forks a new version of protobuf and export them by :well_known_types_protos targets. 

But how to set my project to use the protobuf in bazel instead of the official one. The WORKSPACE example shown [here](https://blog.bazel.build/2017/02/27/protocol-buffers.html) seems doesn't work.

**Comment by buchgr** [comment]
There is an open-bug for this https://github.com/bazelbuild/bazel/issues/2265 ... I haven't had time to fix this yet.

What we did in bazel was move the well known protos from `src/com/google/protobuf` to `com/google/protobuf`. So you can add protobuf to your dependencies and fix that yourself.
