### ISSUE TITLE
[feature request] Add 'patches' and 'patch_cmds' fields to 'http_archive' in WORKSPACE

### ISSUE THREAD

**Issue by yurivict** [bazelbuild/bazel#3395]
In case the tarball contents need to be patched after download, http_archive should have the fields 'patches' and 'patch_cmds':
```
http_archive(
    name = "my_ssl",
    url = "http://example.com/openssl.zip",
    sha256 = "03a58ac630e59778f328af4bcc4acb4f80208ed4",
    patches = ("patch1.diff", "patch2.diff"),
    patch_cmds = ("cmd-patch1.sh", "cmd-patch2.sh"),
)
```

Otherwise, it appears that currently it isn't easy to add such patches.

**Comment by aehlig** [comment]
Over to @kchodorow, who is our expert on remote resources.

**Comment by aehlig** [comment]
The background is handling external resources when packaging projects with bazel. For a related discussion see the [thread](https://lists.freebsd.org/pipermail/freebsd-ports/2017-July/thread.html#109466) starting at [this mail](https://lists.freebsd.org/pipermail/freebsd-ports/2017-July/109466.html) on the `freebsd-ports` mailing list.

/cc @mhlopko @dslomov as the discussion there also touches including libraries already installed on the system.

**Comment by aehlig** [comment]
The related question of importing already installed libraries is now handled in issue #3402

**Comment by yurivict** [comment]
This blocks certain projects using Bazel from having FreeBSD ports.
On one hand, the projects bundle dependencies.
On the other hand, there is no way to patch those dependencies.

**Comment by yurivict** [comment]
@aehlig 
This blocks certain projects using Bazel from having FreeBSD ports.
On one hand, the projects bundle dependencies.
On the other hand, there is no way to patch those dependencies.

Google uses bazel on some projects. On the other hand, bazel is subpar compared to cmake: it doesn't support an important feature (patching), that cmake easily supports.

Is there an ETA for patching?

**Comment by aehlig** [comment]
> @aehlig 
> This blocks certain projects using Bazel from having FreeBSD ports.

I'm surprised to here this, as I would have expected to do the respective
patching in the extract/patch phase, which sets up `WRKDIR`.

Anyway, I finally have the time now to start working on supporting
patches and patch commands in http-archives.

> Is there an ETA for patching?

However, I do not have an ETA now, as I'm quite new to that part of the
bazel code base.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by yurivict** [comment]
> I'm surprised to here this, as I would have expected to do the respective patching in the extract/patch phase, which sets up `WRKDIR`.

It is of course possible to take a tarball, extract it, patch it, and repackage it with a different name, as a workaround. But this is an obvious workaround. No other port does it this way. This will cause more than a few questions, I know this for sure. And it comes down to Bazel, and its inability to patch tarballs.

**Comment by aehlig** [comment]
> It is of course possible to take a tarball, extract it, patch it, and repackage it with a different name, as a workaround. But this is an obvious workaround. No other port does it this way. This will cause more than a few questions, I know this for sure. And it comes down to Bazel, and its inability to patch tarballs.

I was more thinking of extracting and patching all sources needed in
`WRKDIR` during the extract and patch phases and, while there changing
the reference form `new_http_archive` to `new_local_repsoitory` so
that the ready-made patched sources of the dependencies are used. In
that way, one could also benefit from standard patch procedures such
as `USES=shebangfixes`.

**Comment by yurivict** [comment]
Thanks! I will try it.
