### ISSUE TITLE
Repository Tar functions are using java.io FileInputStreams with 1-byte reads

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#3397]
### Performance of compressed tar archive content extraction is extremely poor due to non-buffered IO:

_fetched content can be observed reading from the raw compressed archive one byte at a time, as with the default InputStream read() behavior.  Apache commons interface uses only InputStream basics with no buffering_

### If possible, provide a minimal example to reproduce the problem:

Add a new_http_archive to a WORKSPACE, with a large (100+MiB .tar.bz2) compressed archive, depend on its contents in any rule, run an initial bazel query (or any other repository fetching command), and strace the running bazel daemon to observe huge numbers of single byte read syscalls against a file descriptor that matches the archive's external download location.

### Environment info
* Operating System:

linux

* Bazel version (output of `bazel info release`):

development version

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

688dbf7a71d2c2c2a092ab77ddaa2e2bfdebef8a

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

Using a BufferedInputStream to wrap the default FileInputStream being used in the TarBz2/Gz/Xz functions, with a BUFFER_SIZE of 32k (the going rate for buffers in sha256 validation for skylark repositories), I brought the time for numerous repository extractions (with a simplistic query command to trigger the download/extracts) from 2m19s without buffering to 1m1s.  Mileage will vary, but I think we can mostly agree that the cost of 1-byte reads is undesirable.

With this input buffering in place, execution becomes write dominated with a default BufferedOutputStream-style 8k size set of writes, of what appears to be uncompressed content of the archives.

**Comment by aehlig** [comment]
Over to @kchodorow who probably knows best the context of `new_http_archive` to further triage this performance issue.

**Comment by drigz** [comment]
To quantify this, it can take three minutes to extract an 80MB boost release:

```
➜  cat WORKSPACE 
new_http_archive(
    name = "boost",
    build_file_content = """
filegroup(
    name = "install",
    srcs = ["index.htm"],
)
""",
    sha256 = "beae2529f759f6b3bf3f4969a19c2e9d6f0c503edcb2de4a61d1428519fcb3b0",
    strip_prefix = "boost_1_63_0/",
    url = "https://dl.bintray.com/boostorg/release/1.63.0/source/boost_1_63_0.tar.bz2",
)
➜  bazel build @boost//:installINFO: Analysed target @boost//:install (2 packages loaded).
INFO: Found 1 target...
Target @boost//:install up-to-date (nothing to build)
INFO: Elapsed time: 240.105s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
```

Of those 240s, about 60s were spent downloading the archive. The user gets no feedback when the archive is being extracted - I originally thought Bazel was deadlocked.

Switching to a .tar.gz reduces the extraction time to around 15s.
