### ISSUE TITLE
execroot/source/external/<repo>/* symlinks race with input cache population

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#3398]
### Evaluation of input artifacts during ActionExecutionFunction#compute can precede external source-path availability of inputs:

_The net effect of this race is to produce null inputs which can never cache-hit with created action cache key entries, and can result in precondition failures for null results on PerActionFileCache fetches_

### If possible, provide a minimal example to reproduce the problem:

Like many races, this is difficult to reproduce.  Originally we encountered this problem when performing static-only input ExtraActions, but have discovered it again when performing large builds.  Our unreliable reproducer involves building a small target with no (or few) external depedencies, then building a larger-scoped set of targets with numerous external dependencies.  When the larger scoped build runs, the stock bazel behavior results in ActionCache misses (for results) based on now-unreproducible key selection due to the null inputs, and the action is re-executed. This can also trigger an ActionExecutionException in ActionExecutionFunction#checkInputs (but does not have to, given the race), which will fail the build for the cryptic indication of missing inputs, which can actually end up being created by the time the non-catastrophically errored build returns to the prompt. This also has ramifications for other uses of the PerActionFileCache (like remote execution/remote ActionCache), resulting in the more undesirable precondition failure for a null input cache entry - this would be discovered closer to the source of the error if null value containing-maps were preconditioned out of PerActionFileCache's construction.

### Environment info
* Operating System:

linux

* Bazel version (output of `bazel info release`):

development version

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

4594b7fd6c2516341cdd6e57f9eaaf22cf691f95

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

We've been investigating this over the course of the last 8 months at least, and have seen it drop in and out of view through the use of various features, but believe it is a genuine race, and is impacted by build size (requested and execute-required) and external repo population.

**Comment by aehlig** [comment]
Assigning to @ulfjack who recently did a lot of changes on action execution and might have best knowledge of that part of the code.

**Comment by ulfjack** [comment]
I'm not even sure where to start. In principle, the idea of Skyframe is that dependencies are declared such that there can't be any races, which suggests that some dependency declaration is missing; not necessarily in a BUILD file, it could be that the Skyfunctions don't declare their dependencies correctly. I don't think we've tried too hard to enforce functional behavior, and there are limits to what we can do in Java anyway.

**Comment by ulfjack** [comment]
More data? At least a stack trace from the precondition failure?

**Comment by benjaminp** [comment]
Maybe has to do with #3200?

**Comment by werkt** [comment]
I definitely believe it does, but perhaps for slightly different reasons, and for this I at least have a reproducer of null metadata breaking actioncache validation through a shutdown:

1. Apply the following to most any bazel version:

```
diff --git a/src/main/java/com/google/devtools/build/lib/actions/ActionCacheChecker.java b/src/main/java/com/google/devtools/build/lib/actions/ActionCacheChecker.java
index 1a6c4c8..af5c83b 100644
--- a/src/main/java/com/google/devtools/build/lib/actions/ActionCacheChecker.java
+++ b/src/main/java/com/google/devtools/build/lib/actions/ActionCacheChecker.java
@@ -161,7 +161,11 @@ public class ActionCacheChecker {
         : actionInputs;
     Map<String, Metadata> mdMap = new HashMap<>();
     for (Artifact artifact : artifacts) {
-      mdMap.put(artifact.getExecPathString(), getMetadataMaybe(metadataHandler, artifact));
+      Metadata metadata = getMetadataMaybe(metadataHandler, artifact);
+      if (metadata == null) {
+        System.out.println("Artifact " + artifact.toString() + " HAS NULL METADATA");
+      }
+      mdMap.put(artifact.getExecPathString(), metadata);
     }
     return !DigestUtils.fromMetadata(mdMap).equals(entry.getFileDigest());
   }
```

2. Build a target in daemon mode with external dependencies (I've attached a sample workspace which uses icu as installed by libicu-dev:amd64 on my ubuntu machine, but most anything will do)
3. Shut down the daemon
4. Build the same target, observe the external inputs expected to be available under the workspace root/external/icu_repo/... as having null metadata.

We've actually been creating a symlink to the external directory matching the execroot/__main__/external under our workspace root to satisfy this, but the race appears to be independent of the key inconsistencies (the null values create all kinds of problems, but only appear when the daemon restarts, for somewhat complicated reasons).

As to some more data, we did happen to instrument our output so that we could capture the stack trace of the creation of the ValueOrException member for inputDeps in checkInputs:

```
	at com.google.devtools.build.lib.skyframe.ArtifactFunction.makeMissingInputFileExn(ArtifactFunction.java:218)
	at com.google.devtools.build.lib.skyframe.ArtifactFunction.missingInputFile(ArtifactFunction.java:211)
	at com.google.devtools.build.lib.skyframe.ArtifactFunction.createSourceValue(ArtifactFunction.java:188)
	at com.google.devtools.build.lib.skyframe.ArtifactFunction.compute(ArtifactFunction.java:63)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:370)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Pay... little attention to the line numbers (old version, modifications, etc), and that is the point at which we *expected* to see those external dirs populated for a file, and they were not.  Hope that helps.

I think this is probably going to be more useful than the precondition failures, since they're on the consuming side of a collection of metadata, not the producing.

**Comment by dslomov** [comment]
@ulfjack what is the right category for this bug?

**Comment by ulfjack** [comment]
I probably won't be able to look at this issue this week, and I'm out on vacation for two weeks after this week. Assigning to @buchgr to take a look - if you can't track it down in a day or two, it'll have to wait until I'm back.

**Comment by werkt** [comment]
This was caused by (at least as old as 0.4) resolution issues with Paths under external repositories, and does not appear once the non-default-repo-external path is not in use - with the real repository rooted files backing up the Paths, the outputs no longer race. Closing
