### ISSUE TITLE
Enable repository dependency on non-source labels

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3403]
### Description of the problem / feature request / question:

When wanting to import external data for us the only sane way is to pull that data in as an external repo and have executables rework data to comply to Bazels structure and concepts.
This approach is crippled by the inability to depend on non-source Labels (from Skylark repository implementations).
It would be really great to be able to depend on non-source Labels.

**Comment by abergmeier-dsfishlabs** [comment]
The workaround we use for this currently is to build the executable (e.g. `go_binary`) and then copy it into the source tree 👎 .

**Comment by ittaiz** [comment]
Sorry for barging in but what are non-source labels?

**Comment by abergmeier-dsfishlabs** [comment]
> Sorry for barging in but what are non-source labels?

A Label pointing to a `go_binary` for example. So loosely anything, that has to be built.

**Comment by ittaiz** [comment]
Thanks!

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
