### ISSUE TITLE
Java 9: Can't set java source and target to 9

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#3404]
### Description of the problem / feature request / question:

https://github.com/bazelbuild/bazel/blob/36ce4b433e19498a78c34540d5a166d4e0006b22/third_party/java/jdk/README.md says that Bazel's built-in compiler is a Java 9 compiler, so I tried setting the source and target to "9" for the compiler, but it's not working.

### If possible, provide a minimal example to reproduce the problem:

Consider this repository: https://github.com/dfabulich/java9-source-target

It has a blank `WORKSPACE` and a trivial "hello world" `X.java` file. The `BUILD` file says:

```python
java_binary(
	name='x',
	srcs=['X.java'],
	javacopts = ["-source","9","-target","9"],
	main_class='X',
)
```

Expected: Compile with Java 9 source/target, or fail with an error saying that Java 9 isn't supported
Actual: A bogus error message
> Fatal Error: Unable to find package java.lang in classpath or bootclasspath

### Environment info
* Operating System: macOS 10.12.5

* Bazel version (output of `bazel info release`):
0.5.2-homebrew

**Comment by dfabulich** [comment]
See also issue #3410; there's no way to configure a `java_toolchain` for Java 9 either.

**Comment by lberki** [comment]
Let's close this and track Java 9 on https://github.com/bazelbuild/bazel/issues/3410 .
