### ISSUE TITLE
Add ability to act as another service account when constructing gRPC credentials

### ISSUE THREAD

**Issue by pmcalpine** [bazelbuild/bazel#3406]
Currently, the credentials used to make gRPC calls can use the Google Application Default Credentials or a service account JSON file passed on the command line. Could Bazel please be updated so that it optionally accepts the ID of a service account and to act as that service account?

The resulting process would be:
1a. if passed --auth_credentials: authenticate with them, OR
1b. authenticate with Google Application Default Credentials
then
2. if passed --auth_act_as_service_account: act as the service account.

This would enable the caller to be granted the [iam.serviceAccountActor role](https://cloud.google.com/iam/docs/service-accounts#the_service_account_actor_role) on a service accounts which has the permissions to perform the gRPC call.

The process to assume act as a service account is (broadly):
* grant the base identity the iam.serviceAccountActor role on the service account they are permitted to act as
* authenticate with the base identity, ensuring it has the auth/iam or auth/cloud-platform
* construct a JWT, setting the "sub" field to the identity being assumed
* call the projects/serviceAccounts/signJwt to sign the JWT
* use the JWT to acquire an OAuth token for the assumed identity

The access token granted with the OAuth token does not typically include a refresh token. When the access token is expired the process should be performed again with a new JWT in order to acquire a new access token.

**Comment by ulfjack** [comment]
How urgent is this? I also have no idea how to go about doing that.

**Comment by buchgr** [comment]
Just to test my vague understanding of this:
> grant the base identity the iam.serviceAccountActor role on the service account they are permitted to act as

base identity = user account? Also, this has to be done by an owner of a cloud project (i.e. remote execution)? Nothing for bazel to do here?

> authenticate with the base identity, ensuring it has the auth/iam or auth/cloud-platform

So the user who wants to act as a service account first needs to authenticate himself ... where would the user specify his credentials?

> construct a JWT, setting the "sub" field to the identity being assumed

Ok.

> call the projects/serviceAccounts/signJwt to sign the JWT

Just make a gRPC call to that API, using the user's auth token we got two steps up?

> use the JWT to acquire an OAuth token for the assumed identity

Ok.

It seems that besides specifying the service account that a user wants to act as, we also need to authenticate the user. How would that be done? Would we use application default credentials or the JSON credentials file provided for this?

**Comment by buchgr** [comment]
So one would invoke:
```
bazel build ... --auth_credentials=/path/to/user/creds.json --auth_service_account_actor=my_service_account
```

Then bazel would:
1. Create a JWT token with the `sub` field being set to `my_service_account`.
2. Make an RPC call to `projects/serviceAccounts/signJwt` with the JWT token as the payload and receive a signed JWT token back.
3. Using the signed JWT token, construct gRPC call credentials which to use for i.e. remote execution calls.

When along the way the auth credentials expire, repeat the above steps.

In retrospect, I am also thinking we should have prefixed all of the auth flags with `glcoud` or so, as all our auth is google cloud specific tech.

**Comment by buchgr** [comment]
@pmcalpine Marking this as `P2` for now. Do we need this for the `0.5.3` release?

**Comment by pmcalpine** [comment]
Thanks for the fast replies!

> base identity = user account?

base identity = the identity of whatever is actually executing bazel (user or robot).

> > grant the base identity the iam.serviceAccountActor role on the service account they are permitted to act as

> Also, this has to be done by an owner of a cloud project (i.e. remote execution)?

Correct.

> Nothing for bazel to do here?

Correct: nothing for Bazel to do here. This is just context into the use-case.

> So the user who wants to act as a service account first needs to authenticate himself ... where would the user specify his credentials?

The user would specify their credentials via the existing process: either relying on Google Default Application Credentials or by specifying "--auth_credentials" with the path to a credentials JSON file.

> Just make a gRPC call to that API, using the user's auth token we got two steps up?

Correct. The entire flow can be seen in Go code here:
https://github.com/luci/luci-go/blob/master/common/gcloud/googleoauth/token.go#L78
https://github.com/luci/luci-go/blob/master/common/gcloud/iam/client.go#L103

> So one would invoke:
> 
> `bazel build ... --auth_credentials=/path/to/user/creds.json --auth_service_account_actor=my_service_account`

Pretty much. Although in this case the actor is the user, so I think --act_as_service_account or --auth_service_account_act_as makes more sense.

> Then bazel would:
>
> 1. Create a JWT token with the sub field being set to my_service_account.
> 1. Make an RPC call to projects/serviceAccounts/signJwt with the JWT token as the payload and receive a signed JWT token back.
> 1. Using the signed JWT token, construct gRPC call credentials which to use for i.e. remote execution calls.

I would add:
0. Authenticate as the user, and
4. Renew the gRPC credentials as required by following steps 1-3.

> @pmcalpine Marking this as P2 for now. Do we need this for the 0.5.3 release?

Not needed for the 0.5.3 release, but I'll be dusting off my Java textbook if it's not something that could land before September. :)

**Comment by buchgr** [comment]
@pmcalpine thanks! I added it to the 0.6 milestone. should be ready before september :)

**Comment by pmcalpine** [comment]
That's great to hear. Thank you!

**Comment by pmcalpine** [comment]
Hi. I'd like to temporarily "pause" this request. We are re-evaluating whether or not we'll use this authn/authz flow.

**Comment by pmcalpine** [comment]
Update, we don't have a need for this in the short-term.
