### ISSUE TITLE
javabase accepts a java_runtime_suite but not a java_runtime

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#3407]
Consider this BUILD file:

```python
java_runtime_suite(name="jdk9", default=":jdk9-jdk")
java_runtime(
  name="jdk9-jdk",
  srcs=[],
  java_home="/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home"
)
```

When I `bazel run --javabase=jdk9` it works just fine, but when I `bazel run --javabase=java_runtime` I get this error message:

> ERROR: Unexpected javabase rule kind 'java_runtime'.

I would expect javabase to accept a java_runtime, or at the very least something in the documentation should suggest a java_runtime_suite instead.

### Environment info
* Operating System: macOS 10.12.5

* Bazel version (output of `bazel info release`):
0.5.2-homebrew

**Comment by lberki** [comment]
Even though this is P4, this is going to fix itself once I plumb information about the Javabase through a dependency instead of the `Jvm` class. Hopefully I won't forget closing this then.

**Comment by dfabulich** [comment]
Filed a PR documenting this behavior. https://bazel-review.googlesource.com/c/13550/
