### ISSUE TITLE
java_runtime requires an empty srcs when specifying an absolute java_home

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#3408]
https://docs.bazel.build/versions/master/be/java.html#java_runtime

`java_runtime` has a `java_home` attribute.

> The path to the root of the runtime. Subject to "Make" variable substitution. If this path is absolute, the rule denotes a non-hermetic Java runtime with a well-known path. In that case, the `srcs` attribute must be empty.

But the `srcs` is listed as "required," so we have to include an empty "srcs" attribute, `[]`. That's a bit silly; `srcs` should just be marked optional.

**Comment by lberki** [comment]
Hm, I would never have thought that someone will run into this :) Will fix.
