### ISSUE TITLE
java_runtime_suite demands an armeabi-v7a or default architecture

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#3409]
Consider this repository https://github.com/dfabulich/java-runtime-suite

It has a blank workspace and a "hello world" `X.java` that prints the current Java version.

```java
public class X {
	public static void main(String[] args) {
		System.out.println("hello java " + System.getProperty("java.specification.version"));
	}
}
```

Here's its `BUILD` file.

```python
java_binary(
	name='x',
	srcs=['X.java'],
	main_class='X',
)

java_runtime(
	name='jdk-darwin',
	srcs=[],
	java_home='/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home',
)

java_runtime_suite(
	name='jdk',
	runtimes = {
		'darwin': ':jdk-darwin',
	}
)
```

(To reproduce, you'll probably need to change this `java_home` to your exact installed `JAVA_HOME` value on your Mac.)

Run `bazel run --javabase=//:jdk x`.

Expected: "hello java 1.8"
Actual:
> ERROR: No JVM target found under java_runtime_suite rule //:jdk that would work for armeabi-v7a.

If you add a junk `java_runtime` for `armeabi-v7a`, or add a junk `default`, like this, it works.

```python
java_runtime_suite(
	name='jdk',
	runtimes = {
		'armeabi-v7a': ':empty',
		'darwin': ':jdk-darwin',
	}
)

java_runtime(
	name='empty',
	srcs=[],
	java_home='/dne',
)
```

### Environment info
* Operating System: macOS 10.12.5
I'm running on an 2.9 GHz Intel Core i7. (Not an ARM CPU, of course.)

* Bazel version (output of `bazel info release`):
0.5.2-homebrew

**Comment by lberki** [comment]
This is working as intended (unfortunately, until we can stop creating the Android configurations if we don't build Android /cc @gregestren)

For now, add a `default=` attribute to the `java_runtime_suite` rule and it should work.

**Comment by dfabulich** [comment]
IMO, the point of this bug is to stop creating the Android configurations if we're not building Android. Should I re-file this bug with a different title, or can it be reopened?

**Comment by lberki** [comment]
@gregestren will know how to handle the paperwork on that and how much ahead in the future that is. Work is in progress, but will take time.
