### ISSUE TITLE
Bazel 0.5.2 custom toolchain, incorrectly invoking archive program (gcc “ar”) when building tensorflow?

### ISSUE THREAD

**Issue by marcoal** [bazelbuild/bazel#3412]
### Description of the problem:
I may be missing something but it seems like there is a bug when using bazel with a custom toolchain and called gnu archive utility 'ar'

### Environment info
* Operating System:
Ubuntu 14.04.5 LTS

* Bazel version:
release 0.5.2

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)
Nope

### Anything else, information or logs or outputs that would be helpful?
Trying to use a custom toolchain to build a target that depends on tensorflow, my CROSSTOOL and toolchain BUILD files seem fine. However when building a target (that depends on tensorflow) bazel errors in the following:
    
    >>>>>> #@org_tensorflow//tensorflow/core:version_lib [action 'Linking external/org_tensorflow/tensorflow/core/libversion_lib.a']
    cd blah/blach && \ exec env - \ PWD=/proc/self/cwd \ 
    path/to/linux-gnu-gcc-ar @bazel-out/local_linux-opt/bin/external/external/org_tensorflow/tensorflow/core/libversion_lib.a-2.params

The error is in the calling of "ar" itself, it should be called with the _contents_ of the file, not the file itself.

    ERROR: path/to/tensorflow/core/BUILD:1033:1:1 Linking of rule 
    '@org_tensorflow//tensorflow/core:version_lib' failed: x86_64-unknown-linux-
    gnu-gcc-ar failed: error executing command 
    (cd blah/blach && \ exec env - \ PWD=/proc/self/cwd \ 
    path/to/linux-gnu-gcc-ar @bazel-out/local_linux-
    opt/bin/external/external/org_tensorflow/tensorflow/core/libversion_lib.a-
    2.params) : com.google.devtools.build.lib.shell.BadExitStatusException: 
    Process exited with status 1.
    path/to/ar: invalid option --'@'
    Usage: ar [emulation options] [-]{dmpqrstx}[abcDfilMNoPsSTuvV] [--plugin 
    <name>] [member-name] [count] archive-file file... etc.

Now cat'ing 

    bazel-out/local_linux/opt/bin/external/external/org_tensorflow/tensorflow/core/libversion_lib.a-2.params

I get exactly what should be the argumets to 'ar', that is I get:
    
     rcsD bazel-out/local_linux-opt/bin/external/org_tensorflow/tensorflow/core/libversion_lib.a bazel-out/local_linux-opt/bin/external/org_tensorflow/tensorflow/core/_objs/version_lib/external/org_tensorflow/tensorflow/core/util/version_info.o

The command that should be run is something like:
  
    path/to/custom/toolchain/ar $(cat bazel-out/local_linux/opt/bin/external/external/org_tensorflow/tensorflow/core/libversion_lib.a-2.params)

Seems like a bug in bazel? What am I missing?

**Comment by benjaminp** [comment]
Bazel expects `ar` to support parameter files as documented in the GNU `ar` manpage:
```
@file
    Read command-line options from file. The options read are inserted in place of the original @file option. If file does not exist, or cannot be read, then the option will be treated literally, and not removed. 
```

**Comment by aehlig** [comment]
As mentioned, we need options from parameter files. Maybe the documentation can be improved here.

**Comment by mhlopko** [comment]
Answered on the bazel-discuss (please do not double post). If your ar doesn't support param files, set 'supports_param_files' argument to 0/false in your cc_toolchain rule.
