### ISSUE TITLE
py_test xml reports are too terse

### ISSUE THREAD

**Issue by azymnis** [bazelbuild/bazel#3413]
Not sure if this has been reported before but the xml reports that py_test targets generate are a bit too terse. Instead of generating an xml report that lists results for individual unit tests, the result of `bazel run` on a `py_test` target will generate a test report that treats the whole target as a single test. This makes it harder to figure what tests are failing for a test suite with many tests. I tried seeing if this is configurable via test args but i could not find a way to do this. This does not seem to be an issue with unittest itself as far as i can tell.

**Comment by azymnis** [comment]
Let me know if you need a more specific example

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
