### ISSUE TITLE
non-native maven_jar rule does not support maven_server

### ISSUE THREAD

**Issue by petroseskinder** [bazelbuild/bazel#3414]
### Context
This is primarily a documentation issue. The `maven_jar` repository rule, according to its [documentation](https://docs.bazel.build/versions/master/be/workspace.html#maven_jar), accepts a repository argument as well as a server argument. 

```
maven_jar(name, artifact, repository, server, sha1)
     repository (String; optional): 
               A URL for a Maven repository to fetch the jar from.
               Either this or server can be specified. 
               Defaults to Maven Central ("central.maven.org").
     server (String; optional): 
               A maven_server to use for this artifact. 
          
maven_server(name, settings_file, url)
     settings (String; optional):
               A path to a settings.xml file. 
     url (String; optional):
               A URL for accessing the server.
```
Note, this issue is raised for the skylark maven_jar rule. Not the native.maven_jar rule. 

### Specific Issue
Currently, the maven_jar rule errors out if a server argument is passed, [see line 61](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/maven_rules.bzl#L61). 

The repository argument, however, is supported and used, [see line 197](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/maven_rules.bzl#L197).

It would be nice if either (1) the documentation was updated accordingly, or (2) support is added for maven_servers.

### Potential Fix
Beyond actually adding support for the argument, one simple fix would be to redesign maven_jar so it includes the settings argument. For example:
```
maven_jar(name, artifact, remote_repository, settings_file, sha1)
```
This would alleviate the need for the separate maven_server repository rule. However, it would introduce inconsistency between the native and skylark maven_jar rules.

In the bazel code base, the non-native maven_server is only used within the [java-maven](https://github.com/bazelbuild/examples/blob/029745078fb7795b58ae2c5b0793aefe2e8f4313/java-maven/WORKSPACE#L7) example.

**Comment by dslomov** [comment]
@dkelmer what is the right resolution here? I believe it is all fixed with https://github.com/bazelbuild/rules_jvm_external

**Comment by meisterT** [comment]
Closing under the assumption that this is fixed by rules_jvm_external.
