### ISSUE TITLE
Update documentation on deprecating/removing --android_cpu

### ISSUE THREAD

**Issue by chaoren** [bazelbuild/bazel#3415]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

`--android_cpu` appears to have no effect, while `--fat_apk_cpu` seems to do the job.

### If possible, provide a minimal example to reproduce the problem:

```
$ bazel mobile-install :binary
stderr: Failed to install ./bazel-out/local-fastbuild/bin/binary_incremental.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
# fails as expected

$ bazel mobile-install :binary --fat_apk_cpu=x86
# success

$ bazel mobile-install :binary --android_cpu=x86
stderr: Failed to install ./bazel-out/local-fastbuild/bin/binary_incremental.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
# still fails, not expected

$ bazel mobile-install :binary --android_cpu=foo
stderr: Failed to install ./bazel-out/local-fastbuild/bin/binary_incremental.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
# bogus cpu name not detected

$ bazel mobile-install :binary --android_cpu=x86 --android_compiler=foo
ERROR: No toolchain found for --cpu='armeabi-v7a' --compiler='foo'. Valid toolchains are: [
# cpu value is still armeabi-v7a for some reason

$ bazel mobile-install :binary --fat_apk_cpu=x86 --android_compiler=foo
ERROR: No toolchain found for --cpu='x86' --compiler='foo'. Valid toolchains are: [
# doesn't happen with fat_apk_cpu
```

### Environment info
* Operating System: Ubuntu 14.04.5 LTS

* Bazel version (output of `bazel info release`): release 0.5.2

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by aj-michael** [comment]
Hi @chaoren, the behavior that you are seeing is because the default value of --fat_apk_cpu is armeabi-v7a. If --fat_apk_cpu is set (including the default), then it overrides --android_cpu. If you run `bazel mobile-install :binary --fat_apk_cpu= --android_cpu=x86`, you should see success.

I would suggest forgetting that --android_cpu exists. It is a historical artifact that at some point will hopefully be removed. Instead use --fat_apk_cpu.

Leaving this bug open as we should update the documentation.

**Comment by meisterT** [comment]
See https://blog.bazel.build/2023/11/15/android-platforms.html
