### ISSUE TITLE
Android builds of cc_binary targets on Windows produce executable files with '.exe' extensions

### ISSUE THREAD

**Issue by benvanik** [bazelbuild/bazel#3418]
I'm trying to build a cc_binary for Android and on Windows with Bazel 0.5.2 this results in an executable output that has the '.exe' extension. I'd expect that since I'm using the Android crosstool the executable would have no extension, as it would on other platforms producing Android executables.

```
λ bazel build --cpu=arm64-v8a --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain :my_test
INFO: Found 1 target...
Target //:my_test up-to-date:
  C:/users/ben/appdata/local/temp/_bazel_ben/4qe-y0h3/execroot/__main__/bazel-out/aarch64-linux-android-clang3.8-gnu-libstdcpp-fastbuild/bin/my_test.exe
```

Looking at the command bazel is actually calling for the link it shows it choosing this:
```
  external/androidndk/ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/clang -o bazel-out/aarch64-linux-android-clang3.8-gnu-libstdcpp-fastbuild/bin/my_test.exe .......
```

The exe is indeed an elf that can run on Android, it just breaks all my adb scripts expecting it to not have an exe extension :(

**Comment by laszlocsomor** [comment]
I'm surprised this works at all -- we don't yet support building for Android on Windows, see https://github.com/bazelbuild/bazel/issues/3264 .

**Comment by laszlocsomor** [comment]
As for crosstool-dependent output names of `cc_binary`, let me ask @mhlopko and @meteorcloudy  -- Marcel and Yun, can a `cc_binary` change its outputs names depending on the crosstool? E.g. produce `%{name}.exe` with MSVC crosstool but produce `%{name}` with other crosstools, all on Windows?

**Comment by meteorcloudy** [comment]
No, it's currently hard-coded in CcBinary.java.
See https://github.com/bazelbuild/bazel/blob/c6bd5166d1c558fb8f619b53eb4c56fa7cee8b93/src/main/java/com/google/devtools/build/lib/rules/cpp/CcBinary.java#L226

**Comment by mhlopko** [comment]
But you could use a genrule to rename the file as a workaround.

**Comment by benvanik** [comment]
I too was delightfully surprised it worked first try :) Very cool!

I'll use a genrule to rename things for now. I haven't tried it yet but I'm guessing that cc_libraries may end up as .dll instead of .so too. Having the crosstool specify that kind of stuff seems like a good idea!

**Comment by meteorcloudy** [comment]
This issue should already be fixed by https://github.com/bazelbuild/bazel/commit/5c4f3b59fb4aa06da2c368c764cf0d9056ab287a
