### ISSUE TITLE
Builds with `--experimental_action_listener` are approximately twice as slow

### ISSUE THREAD

**Issue by gkelly** [bazelbuild/bazel#3420]
### Description of the problem / feature request / question:

Building targets with `--experimental_action_listener`, even one that invokes an `extra_action` that simply executes `true`, almost doubles total build time.

### If possible, provide a minimal example to reproduce the problem:

The `cloud/...` target set contains a bunch of `C++` targets, and the `tools/BUILD.bazel` looks like:

```
action_listener(
    name = "emit_cpp_extra_actions",
    extra_actions = [":empty_extra_action"],
    mnemonics = ["CppCompile"],
    visibility = ["//visibility:public"],
)

extra_action(
    name = "empty_extra_action",
    cmd = "true",
)
```

And a build without an action listener:

```
$ bazel clean
$ time bazel build cloud/...
<snip>
bazel build cloud/...  0.14s user 0.06s system 0% cpu 24:15.73 total
```

And a build _with_ an action listener:

```
$ bazel clean
$ time bazel build --experimental_action_listener=//tools:emit_cpp_extra_actions cloud/...
<snip>
bazel build  cloud/...  0.28s user 0.17s system 0% cpu 46:57.17 total
```

### Environment info
* Operating System:
Ubuntu 14.04.5 LTS, running on an HP Z620.

* Bazel version (output of `bazel info release`):
```
Build label: 0.5.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 27 13:27:03 2017 (1498570023)
Build timestamp: 1498570023
Build timestamp as int: 1498570023
```

###  Have you found anything relevant by searching the web?
No.

**Comment by meisterT** [comment]
Depending on your build, any additional action may slow things down. I have not been able to repro such a dramatic slowdown, but it really depends on the number of `--jobs` and the parallelism of your build.
