### ISSUE TITLE
//src/test/shell//bazel:remote_execution_test is flaky

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/bazel#3421]
Running `//src/test/shell//bazel:remote_execution_test` occasionally fails with a bind error ("Address already in use"), see, e.g., http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=latest,PLATFORM_NAME=linux-x86_64/902/testReport/junit/(root)/(empty)/test_genrule_large_output_chunking/

This doesn't happen very often (about 1 in a 50 times), but still is reproducible.

**Comment by ola-rozenfeld** [comment]
Hmm, that is surprising. I would expect a $(pick_random_unused_tcp_port) to pick, I don't know, a random *unused* tcp port? :-/
I think I'll switch it to use a reserve_random_unused_tcp_port instead, and see how that goes.

**Comment by ola-rozenfeld** [comment]
OK, I now understand how a race between the tests is possible with pick_random_unused_tcp_port. Indeed, we should use a reserve_random_unused_tcp_port, because that's what actually marks the port as used for the given duration.
