### ISSUE TITLE
Bazel tries to exec WORKSPACE_DIR/tools/bazel even if it's a directory

### ISSUE THREAD

**Issue by BooneJS** [bazelbuild/bazel#3422]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

/usr/bin/bazel tries to `exec -a $WORKSPACE_DIR/tools/bazel $@` if `$WORKSPACE_DIR/tools/bazel` exists and is executable. This path may not be what bazel thinks it is.

I came across an interesting issue when writing skylark rules for my repository. I put the rules in `$workspace_dir/tools/bazel/*.bzl`, and I was rewarded with a cryptic bash error from line 79 about a failed exec. I can understand why someone would want to make building bazel a part of their build flow (especially with remote caching!), and as such would reference bazel internal to their repo.

### If possible, provide a minimal example to reproduce the problem:

```
cd $workspace_dir
mkdir -p tools/bazel
touch tools/bazel/myrules.bzl
bazel build
```

### Environment info
* Operating System: 
Ubuntu 16.04,

* Bazel version (output of `bazel info release`):
release 0.5.2

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
No, but I found this blurb in the bazel shell script (https://github.com/bazelbuild/bazel/blob/7be6ec66422e23705a8d8345675ee4c15bad3882/scripts/packages/bazel.sh#L19)

```# This is a script which is installed instead of the real Bazel binary.
# It looks for a tools/bazel executable next to the containing WORKSPACE
# file and runs that. If that's not found, it runs the real Bazel binary which
# is installed next to this script as bazel-real.
```

It would be neat if portions of this 4 line comment could be displayed to the user if `$WORKSPACE_DIR/tools/bazel` is a directory.

### Anything else, information or logs or outputs that would be helpful?

https://github.com/bazelbuild/bazel/blob/7be6ec66422e23705a8d8345675ee4c15bad3882/scripts/packages/bazel.sh#L79

The shell script currently looks for `$WORKSPACE_DIR/tools/bazel` to be executable, which directories will be if users are to enter them. An additional check, like presenting an error message if `$WORKSPACE_DIR/tools/bazel` is a directory, would help the user understand their conflict with bazel's assumptions better than a cryptic bash error message will.

```
if [[ -e "${WORKSPACE_DIR}/WORKSPACE" ]]; then
  readonly WRAPPER="${WORKSPACE_DIR}/tools/bazel"
  if [[ -x "${WRAPPER}" ]]; then
    if [[ -d "${WRAPPER}" ]]; then
      echo "CONFLICT: Bazel expects "${WRAPPER}" to be a wrapper around bazel-real, not a directory. Please rename."
    fi
    exec -a "$0" "${WRAPPER}" "$@"
  fi
fi
```

Thank you.

**Comment by aehlig** [comment]
While technically one might argue that it is only missing documentation, I classify it as a bug; the large number of unsystematic "magic paths" make bazel indeed hard to use. We probably need a general design on a more systematic way of which names and places to treat specially.

**Comment by damienmg** [comment]
I agree that we should be a bit more careful about those magic paths but we must choose our fights :/

**Comment by damienmg** [comment]
Klaus also told me offline that for this one particular issue we could test that the realpath of tools/bazel is indeed a file not a directory.

**Comment by meisterT** [comment]
We now check whether it's a file and executable.
