### ISSUE TITLE
Error : failed to load skylark extension

### ISSUE THREAD

**Issue by aurorelaurent** [bazelbuild/bazel#3426]
### Environment info
* Operating System: Ubuntu
* Bazel version : 0.5.2

Hello,

When I try this command :

`bazel build tensorflow/examples/label_image:label_image && bazel-bin/tensorflow/examples/label_image/label_image --graph=/tmp/output_graph.pb --labels=/tmp/output_labels.txt --output_layer=final_result --image=$HOME/piscine/nvxpool/cad_image_182022_259650_1987_3303.jpg --input_layer=Mul --output_layer='final_result'
`
I have this error : 

`ERROR: Failed to load Skylark extension '//tensorflow:workspace.bzl'.
It usually happens when the repository is not defined prior to being used.
Maybe repository '' was defined later in your WORKSPACE file?
ERROR: cycles detected during target parsing.`

I do not understand because before restarting my computer this command worked. Do you have any ideas ? 

(For information before restarting my computer I try this tutorial https://github.com/DigitalGlobe/mltools/tree/master/examples/polygon_classify_cnn [The section Getting Started]. Do you think the problem comes from there?)

Thanks

**Comment by fdchiu** [comment]
I had this problem when I built the whole tensor flow from source. I found that in my case I had another workspace under tensor flow subdirectories (I might accidentally built from this sub dir before). Once I deleted it the problem went away.
