### ISSUE TITLE
Full project rebuilds when switching between IntelliJ and Terminal

### ISSUE THREAD

**Issue by cpenner-va** [bazelbuild/bazel#3433]
### Description of the problem / feature request / question:

Problem:
- Bazel rebuilds the entire project from scratch every time I switch between the IntelliJ 'sync' and cmdline commands like `bazel build mytarget`

### If possible, provide a minimal example to reproduce the problem:

In any bazel project run a build using the IntelliJ plugin, then run a build from the command line.

Seems like they're not sharing the same Bazel server.

This gets pretty annoying over time, we're using the pubref protobuf rules and they rebuild protoc from source everytime I switch from cmdline to intelliJ and vice versa 😢 

Thanks!

**Comment by ittaiz** [comment]
Are you sure this is a bug?
I might be wrong but it sounds like a SO question where can someone can
help you troubleshoot your problem (for example match 'which bazel' in the
cmd and the Bazel binary settings in IntelliJ)

**Comment by buchgr** [comment]
cc: @damienmg

Bazel IntelliJ might be using different startup options?

**Comment by brendandouglas** [comment]
> I thought this was fixed

It's not the kind of problem which is ever '[fixed](http://www.codesimplicity.com/post/make-it-never-come-back/)', without some fundamental design change to Bazel.

Can you include the full command line invocations in both cases (including any flags, etc.)?

For the IntelliJ Bazel plugin, this is printed to the 'Bazel Console' tool window during sync.

In particular, please check that:
- the same Bazel executable (and .bazelrc file) is used in both cases
- there are no .bazelproject `build_flags` not also used when running in the command line -- if there are, please include the exact list

**Comment by dslomov** [comment]
Bug, if any, should be filed in IntelliJ plugin: https://github.com/bazelbuild/intellij

**Comment by welshm** [comment]
Was there another issue filed? Or a SO article? This is where I ended up searching for a resolution to the same issue
