### ISSUE TITLE
Is it possible to add `numCached` and `numUncached` to the build event stream proto?

### ISSUE THREAD

**Issue by Utsav2** [bazelbuild/bazel#3435]
**Feature Request**

We have a distributed cache set up, but it's tricky to monitor whether test result caching works, and what the cache hit rate is. Ideally, we would like to monitor that for regressions and see if the numbers can be improved.

From what it looks like, that information is present in [TestSummary.java](https://github.com/bazelbuild/bazel/blob/8970b43c42197378e93339584d27063d082a512d/src/main/java/com/google/devtools/build/lib/runtime/TestSummary.java#L365), but it seems like it's not exposed externally anywhere. 

So I was wondering if it could be added to the build event stream, through which we can track it? I would be happy to supply a patch if requested.

**Comment by buchgr** [comment]
@Utsav2 we also have an issue for adding this to bazel's UI: https://github.com/bazelbuild/bazel/issues/2846

**Comment by Utsav2** [comment]
Even adding it to the UI would be ok for now. Right now, we're guessing based on the time the test took to execute, which isn't ideal.

**Comment by buchgr** [comment]
@Utsav2 that is definitely planned! However, please don't parse the UI output ... we will break you eventually :-).

@aehlig can talk about whether adding this to the BEP is possible.

**Comment by aehlig** [comment]
Note that `TestSummary`'s `numCached` also counts local cache hits, but it is certainly possible to expose that value in the build event stream proto.

https://bazel-review.googlesource.com/c/14493/

**Comment by Utsav2** [comment]
Thank you!

**Comment by Utsav2** [comment]
FYI, `num_cached` does not seem to work for remotely cached actions (non worker, haven't tried with worker) at all.

**Comment by buchgr** [comment]
@Utsav2 you are correct. there is a bug somewhere about this.
