### ISSUE TITLE
Can't (cleanly) depend on maven_jar from a repository rule

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#3438]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I'm writing a repository rule which essentially calls a runnable jar to download an external dependency. The runnable jar contains logic which shouldn't be duplicated into skylark on where to find the needed file.
The current problem is that `repository_ctx.path` fails when it gets a `label` and not a `file`.

### If possible, provide a minimal example to reproduce the problem:
`WORKSPACE`
```
maven_jar(
    name = "com_wix_wix_embedded_mysql_download_and_extract_jar_with_dependencies",
    artifact = "com.wix:wix-embedded-mysql-download-and-extract:jar:jar-with-dependencies:2.2.9",
)
load(":mysql_installer.bzl", "mysql_installer")
mysql_installer(name = "mysql")
```
`mysql_installer.bzl`
```python
def _impl_mysql_installer(repository_ctx):
  build = """filegroup(
          name = "5.6_36" ,
          srcs = ["downloaded_mysql"],
          visibility = ['//visibility:public']
        )""")
  repository_ctx.file("BUILD", build)
  path_to_download_to = repository_ctx.path("downloaded_mysql")

  args = ["java",
          "-jar",
          repository_ctx.path(repository_ctx.attr._mysql_downloader_and_extractor),
          path_to_download_to,
          "5.6",
          "36"
  ]
  repository_ctx.execute(args)


mysql_installer = repository_rule(
    implementation=_impl_mysql_installer,
	attrs = {
      "_mysql_downloader_and_extractor": attr.label(default=Label("@com_wix_wix_embedded_mysql_download_and_extract_jar_with_dependencies//jar")),
			})
```
`BUILD`
```python
sh_test(
    name = "foo_integration_test",
    srcs = ["foo.sh"],
    data = ["@mysql//:5.6_36"],
    args = ["$(location @mysql//:5.6_36)"],
)
```
`foo.sh`
```sh
#!/bin/bash
echo "Executing: " $@
```

This gives the following error:
```
ERROR: ... no such package '@mysql//': Not a file: .../external/com_wix_wix_embedded_mysql_download_and_extract_jar_with_dependencies/jar/jar and referenced by ...
```

### Anything else, information or logs or outputs that would be helpful?
I've tried:
`@com_wix_wix_embedded_mysql_download_and_extract_jar_with_dependencies//jar:jar`
`@com_wix_wix_embedded_mysql_download_and_extract_jar_with_dependencies//jar:file`
but that didn't work either.
The current workaround is `@com_wix_wix_embedded_mysql_download_and_extract_jar_with_dependencies//jar:wix-embedded-mysql-download-and-extract-2.2.9-jar-with-dependencies.jar` which means I have the version encoded in two places (the `maven_jar` in the `WORKSPACE` and in the repository rule)

**Comment by ittaiz** [comment]
I'd also like to replace "java" with `repository_ctx.path(repository_ctx.executable._java.path)` or something similar where `_java` is roughly `"_java": attr.label(executable=True, cfg="host", default=Label("@bazel_tools//tools/jdk:java"), allow_files=True),`.
Nor sure if it's the same problem or different one so I'm adding it here and I'll open a new issue if you think it's better

**Comment by davido** [comment]
In Gerrit Code Review build tool chain, we are doing something similar, providing downloaded Maven artefacts as a parameter to a python script to produce a third artefact. I believe, you are missing `$(location :foo)` macro invocation. Here what we are doing

```
load("//tools/bzl:maven.bzl", "merge_maven_jars")

# core and backward-codecs both provide
# META-INF/services/org.apache.lucene.codecs.Codec, so they must be merged.
merge_maven_jars(
    name = "lucene-core-and-backward-codecs",
    srcs = [
        "@backward_codecs//jar",
        "@lucene_core//jar",
    ],
    data = ["//lib:LICENSE-Apache2.0"],
    visibility = ["//visibility:public"],
)
```

and further, in maven_bzl:

```
# Merge maven files

def cmd(jars):
  return ('$(location //tools:merge_jars) $@ '
          + ' '.join(['$(location %s)' % j for j in jars]))

def merge_maven_jars(name, srcs, **kwargs):
  native.genrule(
    name = '%s__merged_bin' % name,
    cmd = cmd(srcs),
    tools = srcs + ['//tools:merge_jars'],
    outs = ['%s__merged.jar' % name],
  )
  native.java_import(
    name = name,
    jars = [':%s__merged_bin' % name],
    **kwargs
  )
```

**Comment by ittaiz** [comment]
Thanks @davido! I actually started with `$(location)` but forgot to report about it.
I think that the above works for you because `genrule` uses under the hood `ctx.expand_location`. I'm not sure how this will work in the example I gave above?
1. Would you use `$(location //tools:merge_jars)` in the label? I tried in the call to `repository_ctx.path` and as an arg to execute (without calling repo_ctx.path in hopes that maybe `execute` calls `expand_location` on args but that didn't work)
2. `repository_ctx` doesn't have an `expand_location` method

**Comment by ittaiz** [comment]
Any other thoughts?

**Comment by helenalt** [comment]
@kchodorow would you be able to check this issue in Ittai's original post and see if you have a recommendation?

**Comment by ittaiz** [comment]
Hey,
Any update?

**Comment by kchodorow** [comment]
Yeah, we should expose some facility for getting the path more easily.  Could you do something like `"%s/%s/%s" % (label.workspace_root, label.package, label.name)` in the meantime?

**Comment by ittaiz** [comment]
Right now I just use the explicit label since it's an external label which changes rarely.
It's just not very stable.
Do you think your suggestion will solve the "java" problem I had above?
Should I open a separate ticket about it?

**Comment by ittaiz** [comment]
@kchodorow friendly ping

**Comment by ittaiz** [comment]
Hey,
Any update on this?
Additionally is the `java` issue I raised in the second comment a separate issue? If so I'll open one

**Comment by ittaiz** [comment]
Ping

**Comment by ittaiz** [comment]
ok, this duplication of versions hit us pretty bad.
Any chance for this to happen?
cc @helenalt

**Comment by dslomov** [comment]
What about @kchodorow suggestion: `%s/%s/%s" % (label.workspace_root, label.package, label.name)`?

**Comment by dslomov** [comment]
Ok, I spoke too soon. The label `@com_wix_wix_embedded_mysql_download_and_extract_jar_with_dependencies//jar` actually denotes a `java_import` rule. So during the workspace loading we do not know what its path is.

Currently, we have a phase separation such that workspace processing precedes loading (BUILD file parsing) precedes analysis precedes execution. Accessing paths for arbitrary labels during workspace processing violates phase separation (workspace processing starts to depend on results of execution) which we cannot do.

Workspace rules have access to "pseudo-labels" that denote _files_ from other repositories. But they cannot access build results, and  `@com_wix_wix_embedded_mysql_download_and_extract_jar_with_dependencies//jar` is a build result.

One possible solution here is for maven_jar rule to create symlink with a version-independent name for  the jar it downloaded and other rules to refer to that, but maybe that's infeasible?
