### ISSUE TITLE
Bazel client, Windows, regression: can't create top-level directories

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3454]
https://github.com/bazelbuild/bazel/commit/b69acfaa1c281ac2e8fd7450f07bb3735d24ae23 introduced a regression: `blaze_util::MakeDirectoryW` computes the parent of "\\\\?\\C:\\foo" to be "\\\\?\\C:" (no trailing backslash) and `blaze_util::IsRootDirectory` doesn't recognize this as a root directory, so we attempt to create its parent, which is computed to be "\\\\?".

**Comment by laszlocsomor** [comment]
@buchgr : FYI

**Comment by buchgr** [comment]
Thanks :-) Let me know once you have a fix.

**Comment by damienmg** [comment]
The commit is not in the release branch so it is not blocking 0.5.3
