### ISSUE TITLE
Bootstrapping on CentOS 6.x is broken

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3455]
commit a96369c1c66df624bbee0d9e1c7ad38fea55cd26 broke bootstrapping on CentOS, to get the test:

bazel test src/test/docker:test_cc_configure-centos6.7-fastbuild

(requires docker, found by bisecting)

The error message is:

ERROR: /opt/workspace/src/main/cpp/BUILD:14:1: C++ compilation of rule '//src/main/cpp:blaze_util' failed (Exit 1): gcc failed: error executing command 
  (exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
  /opt/rh/devtoolset-2/root/usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/opt/rh/devtoolset-2/root/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/local-fastbuild/bin/src/main/cpp/_objs/blaze_util/src/main/cpp/blaze_util_posix.pic.d '-frandom-seed=bazel-out/local-fastbuild/bin/src/main/cpp/_objs/blaze_util/src/main/cpp/blaze_util_posix.pic.o' -fPIC -DBLAZE_OPENSOURCE -iquote . -iquote bazel-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c src/main/cpp/blaze_util_posix.cc -o bazel-out/local-fastbuild/bin/src/main/cpp/_objs/blaze_util/src/main/cpp/blaze_util_posix.pic.o).
src/main/cpp/blaze_util_posix.cc: In function 'bool blaze::UnlimitResource(int)':
src/main/cpp/blaze_util_posix.cc:749:71: error: expected ')' before 'PRIdMAX'
     fprintf(stderr, "Warning: failed to raise resource limit %d to %" PRIdMAX
                                                                       ^
src/main/cpp/blaze_util_posix.cc:751:28: warning: spurious trailing '%' in format [-Wformat=]
             strerror(errno));
                            ^
src/main/cpp/blaze_util_posix.cc:751:28: warning: too many arguments for format [-Wformat-extra-args]
INFO: Building complete.

(probably missing an include). Log from CI: http://ci.bazel.io/job/bazel-docker-tests/BAZEL_VERSION=latest,PLATFORM_NAME=docker/674/console

Unfortunately the docker tests have been deactivated by error and did not run for a long time, that's why we only found out now.

**Comment by damienmg** [comment]
${CC} -o /tmp/test.o src/main/cpp/blaze_util_posix.cc -I . -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -fPIC -DBLAZE_OPENSOURCE -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c

Is working fine inside the container...

**Comment by damienmg** [comment]
```
(exec env - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /opt/rh/devtoolset-2/root/usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/opt/rh/devtoolset-2/root/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -fPIC -DBLAZE_OPENSOURCE -iquote . -iquote bazel-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c src/main/cpp/blaze_util_posix.cc -o /tmp/test.o)
```

Pass on the container

```
[root@d64536f65aab workspace]# grep PRIu32 /usr/include/inttypes.h 
# define PRIu32         "u"
[root@d64536f65aab workspace]# ${CC} '-std=c++0x' -iquote . -c src/tools/singlejar/combiners.cc -o /tmp/combiners.o
In file included from ./src/tools/singlejar/transient_bytes.h:21:0,
                 from ./src/tools/singlejar/combiners.h:21,
                 from src/tools/singlejar/combiners.cc:15:
./src/tools/singlejar/transient_bytes.h: In member function ‘void TransientBytes::DecompressEntryContents(const CDH*, const LH*, Inflater*)’:
./src/tools/singlejar/transient_bytes.h:111:52: error: expected ‘)’ before ‘PRIu32’
                       "Z_OK but there are still %" PRIu32
                                                    ^
./src/tools/singlejar/diag.h:25:29: note: in definition of macro ‘diag_errx’
 #define diag_errx(...) errx(__VA_ARGS__)
                             ^
./src/tools/singlejar/transient_bytes.h:132:74: error: expected ‘)’ before ‘PRIu64’
                 "%s:%d: Internal error inflating %.*s: inflater wrote %" PRIu64
                                                                          ^
./src/tools/singlejar/diag.h:25:29: note: in definition of macro ‘diag_errx’
 #define diag_errx(...) errx(__VA_ARGS__)
                             ^
./src/tools/singlejar/transient_bytes.h: In member function ‘uint8_t* TransientBytes::advance(size_t)’:
./src/tools/singlejar/transient_bytes.h:278:63: error: expected ‘)’ before ‘PRIu64’
       diag_errx(2, "%s: %d: Cannot advance %ld bytes, only %" PRIu64
                                                               ^
./src/tools/singlejar/diag.h:25:29: note: in definition of macro ‘diag_errx’
 #define diag_errx(...) errx(__VA_ARGS__)
                             ^
[root@d64536f65aab workspace]# echo | ${CC} -E -std=c++0x - -v
Using built-in specs.
COLLECT_GCC=/opt/rh/devtoolset-2/root/usr/bin/gcc
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/opt/rh/devtoolset-2/root/usr --mandir=/opt/rh/devtoolset-2/root/usr/share/man --infodir=/opt/rh/devtoolset-2/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-languages=c,c++,fortran,lto --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --disable-libgcj --with-isl=/dev/shm/home/centos/rpm/BUILD/gcc-4.8.2-20140120/obj-x86_64-redhat-linux/isl-install --with-cloog=/dev/shm/home/centos/rpm/BUILD/gcc-4.8.2-20140120/obj-x86_64-redhat-linux/cloog-install --with-mpc=/dev/shm/home/centos/rpm/BUILD/gcc-4.8.2-20140120/obj-x86_64-redhat-linux/mpc-install --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC) 
COLLECT_GCC_OPTIONS='-E' '-std=c++11' '-v' '-mtune=generic' '-march=x86-64'
 /opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/cc1 -E -quiet -v - -mtune=generic -march=x86-64 -std=c++11
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
ignoring nonexistent directory "/opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-redhat-linux/4.8.2/include-fixed"
ignoring nonexistent directory "/opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-redhat-linux/4.8.2/../../../../x86_64-redhat-linux/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-redhat-linux/4.8.2/include
 /usr/local/include
 /opt/rh/devtoolset-2/root/usr/include
 /usr/include
End of search list.
# 1 "<stdin>"
# 1 "<command-line>"
# 1 "<stdin>"
COMPILER_PATH=/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/:/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/:/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/:/opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-redhat-linux/4.8.2/:/opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-redhat-linux/4.8.2/:/opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-redhat-linux/4.8.2/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-redhat-linux/4.8.2/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-E' '-std=c++11' '-v' '-mtune=generic' '-march=x86-64'
```

So I get another failing action now. And not understandable

Haha found out:

```
/* The ISO C99 standard specifies that these macros must only be
   defined if explicitly requested.  */
#if !defined __cplusplus || defined __STDC_FORMAT_MACROS
```

So -D__STDC_FORMAT_MACROS should fix the issue

**Comment by damienmg** [comment]
Bingo!
```
[root@d64536f65aab workspace]# ${CC} '-std=c++0x' -iquote . -c src/tools/singlejar/combiners.cc -o /tmp/combiners.o -D__STDC_FORMAT_MACROS
[root@d64536f65aab workspace]# 
```

**Comment by philwo** [comment]
Can you check if alternatively using

```
#include <cinttypes>
```

also works (without defining __STDC_FORMAT_MACROS)?

The __STDC_FORMAT_MACROS define and "inttypes.h" header are C stuff, but this is C++ code, so we should be using cinttypes, which - if I understand what I just found on the web correctly - doesn't require the define: http://lists.llvm.org/pipermail/cfe-commits/Week-of-Mon-20160926/171617.html

**Comment by damienmg** [comment]
Indeed that works fine!
