### ISSUE TITLE
Bazel thrashes caches between branches

### ISSUE THREAD

**Issue by bkase** [bazelbuild/bazel#3457]
### Description of the problem / feature request / question:

Problem: If I build my project on one branch then switch to another and build and switch back, it seems like there should be a cache hit here. Is there a way to configure bazel's cache so this sort of workflow works?
Do shared build caches also thrash between different versions of the files? Wouldn't this make them not very useful? Given that everything is hashed is there some setting I could change to make the input hashes be the key to the data in the cache not the names of the files?

Please advise. Thanks!

### If possible, provide a minimal example to reproduce the problem:

Here is a simple iOS app:

```
git clone https://github.com/bkase/debugging-tulsi-broken.git project
cd project
bazel build '//:FullBazelSample'
git checkout feature-branch
bazel build '//:FullBazelSample'
git checkout master
bazel build -s '//:FullBazelSample'
```

I expect no clang commands to run in the output of `build -s` because an older version of the file would be cached.

### Environment info
* Operating System:

macOS Sierra 10.12.5

* Bazel version (output of `bazel info release`):

`release 0.5.2`

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

I see that the output directories mirror the rule names so I see why the cache is busted: https://docs.bazel.build/versions/master/output_directories.html , but I'd be interested in ways to workaround this.

**Comment by buchgr** [comment]
@ulfjack maybe knows?

**Comment by jgavris** [comment]
I believe the way bazel is designed now you'd want to run a 'remote cache', and that cache would be responsible for defining a size limit / eviction policy for action outputs.

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/remote/README.md

**Comment by jgavris** [comment]
I made a very simple one in Swift that can connect to redis, there's no reason you couldn't run this service locally.

https://github.com/ButterflyNetwork/bazel-rest-cache

**Comment by buchgr** [comment]
@jgavris cool cache! ;-) FYI we are also adding one based on nginx to our continuous integration: https://bazel-review.googlesource.com/c/14370/

**Comment by ulfjack** [comment]
We don't currently cache files outside the workspace. That means that if you do a build on another branch, then if that overwrites files in the output tree, they'll have to be re-generated when you switch back.

It's unlikely that we'll enable cross-workspace caching by default, since that will significantly increase the amount of disk space needed (at least by a factor of 2) since we'll need to keep another copy of the same files. That said, there is actually code in Bazel [1] to implement a cross-workspace cache, but it's not hooked up yet - though it should be easy to add.

[1] https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/remote/blobstore/OnDiskBlobStore.java

**Comment by bkase** [comment]
Great, thanks for all the advice!

**Comment by jgavris** [comment]
@buchgr Cool cache! Redis 4.0 has a new LFU eviction policy which is pretty rad ;)

**Comment by derekargueta** [comment]
Wanted to poke this thread to see if there've been any developments in this space in the last 2.5 years?

**Comment by buchgr** [comment]
@derekargueta --disk_cache is what you want.

**Comment by padresmurfa** [comment]
Can confirm. --disk_cache works very nicely for this type of scenario.

**Comment by tuananhlai** [comment]
@padresmurfa Since `disk_cache` and `remote_cache` are both external cache, can I understand that you could share a single GCS bucket as remote cache between multiple git branches?
