### ISSUE TITLE
0.5.3 release: Windows package does not include the version number

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3459]
I was looking at the release and seems like the new pipeline did not included the release version on the windows artifact.

Proposed remediation:
  - Fix the CI configuration, delete the release from github and re-run the pipeline. It will resend a mail but we can probably deactivate the mail for one run.

**Comment by damienmg** [comment]
The error can be found in the [Jenkins log](http://ci.bazel.io/blue/rest/organizations/jenkins/pipelines/Global/pipeline/runs/156/nodes/27/log/?start=0):
``` 
[c:\jenkins\workspace\Global\pipeline] Running shell script
+ bash -c 'source scripts/release/common.sh; get_full_release_name'
xargs: environment is too large for exec
xargs: environment is too large for exec
```

**Comment by damienmg** [comment]
Recalling the same action on msys works...

**Comment by damienmg** [comment]
From https://www.gnu.org/software/findutils/manual/html_node/find_html/Error-Messages-From-xargs.html:

> 
> ‘environment is too large for exec’
> This message means that you have so many environment variables set (or such large values for them) that there is no room within the system-imposed limits on program command line argument length to invoke any program. This is an unlikely situation and is more likely result of an attempt to test the limits of xargs, or break it. Please try unsetting some environment variables, or exiting the current shell. You can also use ‘xargs --show-limits’ to understand the relevant sizes.

**Comment by damienmg** [comment]
I don't think those `| xargs echo` are even needed (used to replace all whitespace characters by simple space), since the git notes return only one word.

**Comment by damienmg** [comment]
Sent out a change to remove those xargs echo, trying to figure out a way to fix 0.5.3 release now.

**Comment by damienmg** [comment]
So the generated binaries does not have the version label either.

**Comment by damienmg** [comment]
(normal because it is set from the command before). So let's try to simply patch on the fly in the pipeline itself.

**Comment by damienmg** [comment]
Ok re-running the release pipeline without sending mail.

**Comment by damienmg** [comment]
So the re-run worked the new release is on release.bazel.build. I deleted the release on github and will do yet another run that should publish good artifacts everywhere :)

**Comment by damienmg** [comment]
http://ci.bazel.io/blue/organizations/jenkins/Global%2Fpipeline/detail/pipeline/162/pipeline <-- the pipeline is running, now in less than 30 minute we should get a clean release

**Comment by damienmg** [comment]
The release is done now correctly, the fix is published as fc6c3cb, so I am closing this bug.

Follow-up on bazelbuild/continuous-integration#112

**Comment by petemounce** [comment]
Published https://chocolatey.org/packages/bazel/0.5.3 - thanks. PR incoming for the URL changes that the package needed.

**Comment by petemounce** [comment]
I've adjusted the package build scripts in #3466 to cope with the rename.
