### ISSUE TITLE
Bazel doesn't get Google Application Default Credentials correctly

### ISSUE THREAD

**Issue by huangw5** [bazelbuild/bazel#3460]
When getting the application default credentials, google-auth-library-java searches from five different sources in order (see [doc](http://google.github.io/google-auth-library-java/releases/0.6.0/apidocs/com/google/auth/oauth2/GoogleCredentials.html#getApplicationDefault()) and [code](https://github.com/google/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java#L124)) :

1. Credentials file pointed to by the GOOGLE_APPLICATION_CREDENTIALS environment variable
2. Credentials provided by the Google Cloud SDK gcloud auth application-default login command
3. Google App Engine built-in credentials
4. Google Cloud Shell built-in credentials
5. Google Compute Engine built-in credentials

However, currently Bazel [checks](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/buildeventservice/client/BuildEventServiceGrpcClient.java#L201) the first source only: If environment variable "GOOGLE_APPLICATION_CREDENTIALS" is empty, it simply returns null. This means we have to always provide the json credential file in order to upload build events to BES.

I did the following experiment:

1. Built bazel from HEAD and ran bazel with --bes_backend set and --auth_credential unset: I always got UNAUTHENTICATED error:

```
ERROR: Build Event Protocol upload failed: UNAUTHENTICATED: UNAUTHENTICATED: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication crede
ntial. See https://developers.google.com/identity/sign-in/web/devconsole-project.

```

2. Built bazel by removing the check against the environment variable `!isNullOrEmpty(getenv(DEFAULT_APP_CREDENTIALS_ENV_VAR)` and ran the above the same command.

```
INFO: Waiting for Build Event Protocol upload to finish.
INFO: Build Event Protocol upload finished successfully.
```

**Comment by buchgr** [comment]
Thanks @huangw5! Will fix asap!

**Comment by buchgr** [comment]
@huahang if you would like to fix this ... we love contributions :-)! Let me know!

**Comment by pmcalpine** [comment]
@buchgr Is there a reason that Bazel has any custom handling of the GOOGLE_APPLICATION_CREDENTIALS environment variable at all? I would have expected it to depend on GoogleCredentials.getApplicationDefault(...) to select the appropriate credentials source?

https://github.com/google/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java#L100

**Comment by buchgr** [comment]
@pmcalpine I don't think so. AFAIK it's been there since before I joined, so I can't say for sure, but we might not have been using google's auth library initially.

Anyway, I think it's safe to remove and we will include this in the next release.

**Comment by huangw5** [comment]
Great to hear that. Thanks a lot @buchgr!

**Comment by pmcalpine** [comment]
@buchgr: @huangw5 has created a pull request for this:
https://github.com/bazelbuild/bazel/pull/3468
