### ISSUE TITLE
i have a svn path, http://xxx.com/xxx/tag/xxx.1.0.1 for example. new_http_archive need a compress file, how can i do?

### ISSUE THREAD

**Issue by cnhjq** [bazelbuild/bazel#3463]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### Environment info
* Operating System:

* Bazel version (output of `bazel info release`):

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by dslomov** [comment]
Pleas provide more details of what you were trying to do and what failed. If you have a specific feature request, please formulate it in a form of feature request :)

if you need help setting up you project, ask on [bazel-discuss](https://groups.google.com/forum/#!forum/bazel-discuss) or 
[StackOverflow](http://stackoverflow.com/questions/tagged/bazel)
