### ISSUE TITLE
Can I use path in repository to another repository?

### ISSUE THREAD

**Issue by w4-taehyeong** [bazelbuild/bazel#3464]
I try to make a new local repository the following but it fails. 

git_repository(
  name = "io_bazel",
  commit = "88518522a18df5788736be6151fc67992efe2aad",
  remote = "https://github.com/bazelbuild/bazel.git",
)

new_local_repository(
  name = "com_google_protobuf",
  path = "@io_bazel//third_party/protobuf/3.2.0",
  build_file = "@io_bazel//third_party/protobuf/3.2.0/BUILD",
)

I want to use well known types in protobuf but I can't use fixed protobuf source in bazel.
Is there any good way?

**Comment by dslomov** [comment]
This syntax is not supported. You cannot define a local repository within another repository.
Depend on protobuf directly.
