### ISSUE TITLE
Update jacoco to 0.7.9 or later

### ISSUE THREAD

**Issue by aj-michael** [bazelbuild/bazel#3471]
A combination of `blaze coverage`, `--experimental_desugar_for_android`, the current jacoco 0.7.5 and the upcoming android test rules do not work well together.

See https://issuetracker.google.com/issues/62623509 for the gradle report. The solution is to update jacoco 0.7.8 or later.

**Comment by jin** [comment]
JaCoCo is at 0.8.3 now. https://github.com/bazelbuild/bazel/blob/master/third_party/java/jacoco/org.jacoco.core-0.8.3.jar
