### ISSUE TITLE
Bazel on Windows logs tons of warnings on -c dbg due to bad crosstool flag

### ISSUE THREAD

**Issue by benvanik** [bazelbuild/bazel#3473]
Using 0.5.3. Trying to build a cc_binary with -c dbg. Getting tons of these warnings (one per file):
```
1>cl : Command line warning D9002: ignoring unknown option '-g'
```

Did a bazel clean --expunge in case some old pre-0.5.3 stuff was around, but it looks like the CROSSTOOL for Windows does in fact still define -g for the wrapper, even though the wrapper is no longer used by default:
https://github.com/bazelbuild/bazel/blob/master/tools/cpp/CROSSTOOL#L793

**Comment by meteorcloudy** [comment]
I'll fix this.
