### ISSUE TITLE
Portable python script invocation in build rules

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#3477]
Currently, there is no portable python script invocation machinery from build rules.

### Skylark repository rule

Repository rule context exposes `context.which()` method. However, this doesn't work on Winows:

```
python = ctx.which("python")
```
In Bazel, there is a place: `tools/cpp/windows_cc_configure.bzl`, where a command is searched on the path:

```
def which_cmd(repository_ctx, cmd, default = None):
  """Find cmd in PATH using repository_ctx.which() and fail if cannot find it. Doesn't %-escape the cmd!"""
  result = repository_ctx.which(cmd)
  if result != None:
    return str(result)
  path = get_env_var(repository_ctx, "PATH")
  if default != None:
    auto_configure_warning("Cannot find %s in PATH, using '%s' as default.\nPATH=%s" % (cmd, default, path))
    return default
  auto_configure_fail("Cannot find %s in PATH, please make sure %s is installed and add its directory in PATH.\nPATH=%s" % (cmd, cmd, path))
  return str(result)
```

IOW, the question is what is a portable way to determine python binary in repository rule.

### Skylark rule

From regular Skylark rule, python can be invoked directly:

```
  native.genrule(
    name = "gen_license_txt_" + name,
    cmd = "python $(location //tools/bzl:license-map.py) %s %s > $@" % (" ".join(opts), " ".join(xmls)),
    outs = [ name + ".txt" ],
    tools = tools,
    **kwargs
  )
```

or, even, with previously defining `python_binary` rule, like:

```
py_binary(
    name = "merge_jars",
    srcs = ["merge_jars.py"],
    main = "merge_jars.py",
    visibility = ["//visibility:public"],
)
```

where the first line in: `merge_jars.py`:

```
#!/usr/bin/env python
```

and the script is invoked like this:

```
def cmd(jars):
  return ('$(location //tools:merge_jars) $@ '
          + ' '.join(['$(location %s)' % j for j in jars]))
```

All these invocation versions don't work on Windows.

**Comment by dslomov** [comment]
py_binary should work for Skylark rule starting with 0.5.4.
`repository_ctx.which(''python.exe")` should give you python if it is on the PATH.

**Comment by davido** [comment]
This issue is a follow-up from #2040. 

> py_binary should work for Skylark rule starting with 0.5.4.

I tried with 0.5.3 and it didn't work. Is the fix for that already landed? I could try to build from the HEAD an re-test it. In last comment in #2040 detailed message how it's failing.

> repository_ctx.which("python.exe") should give you python if it is on the PATH.

Gerrit Code Review currently supports Mac OS X and all flavours of Linux. We want to support Windows. Currently we have this:

```
  python = ctx.which("python")
  script = ctx.path(ctx.attr._download_script)
  args = [python, script, "-o", binjar_path, "-u", binurl]
  out = ctx.execute(args)
```

This is failing on Windows. Question: what is the suggested way to make this part portable?

**Comment by davido** [comment]
> py_binary should work for Skylark rule starting with 0.5.4.

Given the commit message in 7e4fbbe4a looks like it wasn't implemented yet.

**Comment by davido** [comment]
> repository_ctx.which("python.exe") should give you python if it is on the PATH.

I would expect that `repository_ctx.which("python")` should work on all supported platforms. Or there should be another version of `which`, may be call it `which_portable` that gets it right on all platforms.

**Comment by davido** [comment]
> I would expect that repository_ctx.which("python") should work on all supported platforms.

Untested: http://paste.openstack.org/show/617633. I wonder if this would be a sane approach?

**Comment by meteorcloudy** [comment]
That looks right, but you can also implement `which_protable` in skylark?

**Comment by davido** [comment]
> That looks right, but you can also implement which_protable in skylark?

Right, but I would rather avoid doing it in gerrit, as we need it already twice, in the same project in core and bazlets to build hundreds of gerrit plugins. What i can imaging if `which_portable` is going to be a part of Bazel distribution.

**Comment by meteorcloudy** [comment]
I see, do you mind sending the change as a PR?

**Comment by davido** [comment]
> I see, do you mind sending the change as a PR?

https://bazel-review.googlesource.com/c/14890

**Comment by davido** [comment]
Works as expected now, thanks!

**Comment by davido** [comment]
@meteorcloudy thanks again for your help! Gerrit Code Review can beo almost compiled on Windows now ;-) Running into another crazy problem, though and writing next issue right now.

**Comment by davido** [comment]
@meteorcloudy #3542.
