### ISSUE TITLE
TensorFlow broken on CI

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#3478]
See http://ci.bazel.io/blue/organizations/jenkins/TensorFlow/detail/TensorFlow/1000/pipeline
RepositoryDelegatorFunction complains that it does not know what to do with 'bind'.

`@protobuf` target in tensorflow is
```
  native.bind(
      name = "protobuf",
      actual = "@protobuf_archive//:protobuf",
  )
```
Not sure what the underlying issue is - maybe it cannot resolve the actual target and then fails with this error message?

**Comment by kchodorow** [comment]
I haven't been able to reproduce yet which suggests a caching issue, but it looks like https://github.com/tensorflow/tensorflow/commit/d09304fca478b8db5c651eec6fb2559844a73373 broke it and has some issues. The paths in tensorflow/tools/pip_package/setup.py were incorrectly changed.  That should be reverted (although that should break at runtime, not compile time).

Error message could definitely be better, too.

**Comment by dslomov** [comment]
So what is the action we should take? The build is still broken. 
tensorflow/tensorflow@d09304f added 
```
 +  native.bind(
 +      name = "protobuf",
 +      actual = "@protobuf_archive//:protobuf",
 +  )
```
My understanding is that repository resolution cannot handle 'bind' -  shall we revert TF change? But how got it landed in the first place?

**Comment by mhlopko** [comment]
Is this still an open issue? I don't see it on the ci anymore?

**Comment by dslomov** [comment]
Seems to be fixed, I assume by a change in TF (there is a different issue now on Windows)

**Comment by mhlopko** [comment]
(yup, that what I'm investigating and came across this one)
