### ISSUE TITLE
Stripped msvc binaries not working - examples/cpp:* fails

### ISSUE THREAD

**Issue by moroten** [bazelbuild/bazel#3482]
`bazel build examples/cpp:*` fails for msvc on Windows because stripping the binary is not implemented. `bazel build examples/cpp:hello_world` works fine.

Error message: `Stripping examples/cpp/hello-world.stripped for //examples/cpp:hello-world failed`

### Description of the problem / feature request / question:

In CI systems, and also as a user, I often want to test a lot of targets by using `//my/package:*`. That is not possible as, for example, `examples/cpp:*` includes `examples/cpp:hello-world.stripped` which fails for msvc.

### If possible, provide a minimal example to reproduce the problem:

> $ export BAZEL_SH="C:/Program\ Files/Git/bin/bash.exe"
> $ export BAZEL_VC="C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC"
> $ PATH="" bazel-0.5.3-windows-x86_64.exe build examples/cpp:* --verbose_failures
> ____Loading complete.  Analyzing...
> ____Found 15 targets...
> ____Building...
> ERROR: C:/git/bazel/examples/cpp/BUILD:9:1: Stripping examples/cpp/hello-world.stripped for //examples/cpp:hello-world failed (Exit -1). Note: Remote connection/protocol failed with: execution failed: msvc_nop.bat failed: error executing command
>     SET PATH=C:\Program Files\Git\bin;C:\Program Files\Git\usr\bin;.
>     SET TMPDIR=C:\Temp
>   external/local_config_cc/wrapper/bin/msvc_nop.bat -S -p -o bazel-out/msvc_x64-fastbuild/bin/examples/cpp/hello-world.stripped -R .gnu.switches.text.quote_paths -R .gnu.switches.text.bracket_paths -R .gnu.switches.text.system_paths -R .gnu.switches.text.cpp_defines -R .gnu.switches.text.cpp_includes -R .gnu.switches.text.cl_args -R .gnu.switches.text.lipo_info -R .gnu.switches.text.annotation bazel-out/msvc_x64-fastbuild/bin/examples/cpp/hello-world.exe.
> Action failed to execute: java.io.IOException: CreateProcess(): The system cannot find the file specified.

### Environment info

* Operating System:
Windows 8
Using Microsoft Visual C++ Build Tools 2015

* Bazel version (output of `bazel info release`):
From git-bash:
> $ bazel-0.5.3-windows-x86_64.exe info release
> release 0.5.3

Also tried bazel 0.5.3 from `cmd.exe` and bazel 0.4.5 from `C:\tools\msys64`, but all three setups are failing the same way.

###  Have you found anything relevant by searching the web?
Nothing relevant found on https://github.com/bazelbuild/bazel/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20stripped or https://github.com/bazelbuild/bazel/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20strip.

### Problem analysis and suggestions

At first, not that `bazel build examples/cpp:*` includes `examples/cpp:hello-world.stripped`. It seems like `external/local_config_cc/wrapper/bin/msvc_nop.bat` is a fake command which should just echo the command line and produce nothing. Nowadays, when using non-wrapped msvc, `wrapper/bin/msvc_nop.bat` is not created, but manually copying it there does not help as the expected output `hello-world.stripped` is not produced by `msvc_nop.bat`. Should `createStripAction` be called at 
 all in `src/main/java/com/google/devtools/build/lib/rules/cpp/CcBinary.java` in the msvc case?

I see three options to solve the problem:

1. Implement some kind of stripping for msvc. Is it even possible to strip a msvc binary?

2. Add `CppRuleClasses.NO_STRIPPING`, compare with `CppRuleClasses.GENERATE_PDB_FILE` in `src/main/java/com/google/devtools/build/lib/rules/cpp/CcBinary.java`.

3. Reuse `CppRuleClasses.GENERATE_PDB_FILE` by saying it also means that stripping should not be done.

I think number 2 looks most sensible.

**Comment by dslomov** [comment]
Seems pretty serious, let's fix this for 0.6 @meteorcloudy

**Comment by meteorcloudy** [comment]
Sure, we can fix it.
It's just <binary>.stripped is an implicit output of cc_binary rule, when users try to build stripped binary with MSVC CRSSOTOOL, do you think it's better to throw an error or just copy the original executable?

**Comment by meteorcloudy** [comment]
Related change: https://github.com/bazelbuild/bazel/commit/b3be32e7135895737b64e3ad8ddb09176bfc8dd5

Now strip action can be configured in CROSSTOOL, but what it should be on Windows, a copy or just thrown an error? @dslomov

**Comment by moroten** [comment]
Will throwing an error solve the problem of `bazel build examples/cpp:*` failing? Does a .stripped executable have to be produced if it is just a copy? What I understand, the PDB file contains all symbols so the original .exe file is already stripped from debug symbols.

**Comment by meteorcloudy** [comment]
@moroten That's why I sent https://bazel-review.googlesource.com/#/c/bazel/+/14731/ ;)

**Comment by dslomov** [comment]
right, we discussed offline but I didn't reply here: the resolution we agreed on is to not do stripping on Windows (it is not needed as symbols are not in the .exe as you rightly say)
