### ISSUE TITLE
0.5.3 rule-function return value change breaks Kythe

### ISSUE THREAD

**Issue by shahms** [bazelbuild/bazel#3483]
### Description of the problem / feature request / question:

I'm sure there's a trivial workaround, but some change between 0.5.2 and 0.5.3 caused rule functions when called from a macro to go from returning an object with `.package()` and `.label()` accessors to returning None.

This broke ~all of the Kythe tests, which were written using a combination of rules and macros, combined such as:

```
def cc_verifier_test(name, srcs, deps=[], size="small",
                     indexer_opts=["--ignore_unimplemented=true"],
                     verifier_opts=["--ignore_dups"], tags=[]):
  args = ["-std=c++11", "-c"]
  kindexes = [extract_kindex(
        name = name + "_" + src + "_kindex",
        srcs = [src],
        tags = tags,
        extractor = "//kythe/cxx/extractor:cxx_extractor",
        testonly = True,
        opts = select({
            "//conditions:default": args,
            "//:darwin": args + [
                # TODO(zarko): This needs to be autodetected (or does doing so even make sense?)
                "-I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",
                # TODO(salguarnieri): This could be made more generic with:
                # $(xcrun --show-sdk-path)/usr/include
                "-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include",
            ],
        }),
  ).label() for src in srcs]
  entries = [index_compilation(
      name = name + "_entries",
      deps = kindexes,
      opts = indexer_opts,
      indexer = "//kythe/cxx/indexer/cxx:indexer",
      tags = tags,
      testonly = True,
  ).label()]
  return verifier_test(
      name = name,
      size = size,
      deps = entries + deps,
      opts = verifier_opts,
      tags = tags,
  )
```

I'm sure this change was well intentioned, but it causes a lot of work fixing these macros (unnecessarily, IMO) and substantially reduces the readability thereof.

**Comment by buchgr** [comment]
@dslomov @laurentlb can you take a look?

**Comment by laurentlb** [comment]
Was changed in https://github.com/bazelbuild/bazel/commit/2f32e38826db0325f44f5a385dd958299fb8461d
cc @vladmos 

Sorry, we should have announced this change. The return value was undocumented and unintentional. I didn't expect anyone to try and use it. If I remember correctly, this was also inconsistent with native rules (`cc_library` will return `None`).

We can keep this open as a feature request. We'll have to think of the design first (maybe it's better to directly return the label as a string?). I the mean time, I'm afraid you have to update your code.

**Comment by shahms** [comment]
That's fair, I found the return value through a liberal application of introspection :-)
I think the label string would be sufficient.  It's incredibly useful, particularly when creating a rules in a list comprehension.

**Comment by dslomov** [comment]
Short-term resolution is to fix the code.

**Comment by laurentlb** [comment]
obsolete
