### ISSUE TITLE
cc_proto_library needs a way to define protobuf

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3485]
### Description of the problem / feature request / question:

Currently `cc_proto_library` cannot be used since there is no way to tell it which protobuf library (version/(non-)lite) to use. This leads to command lines like:

```
(exec env - \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' '-std=c++14' '-Werror=sequence-point' -MD -MF bazel-out/local-py3-fastbuild/bin/resource/_objs/texture_extract_proto/resource/src/proto/texture_extract.pb.pic.d '-frandom-seed=bazel-out/local-py3-fastbuild/bin/resource/_objs/texture_extract_proto/resource/src/proto/texture_extract.pb.pic.o' -fPIC -iquote . -iquote bazel-out/local-py3-fastbuild/genfiles -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c bazel-out/local-py3-fastbuild/genfiles/resource/src/proto/texture_extract.pb.cc -o bazel-out/local-py3-fastbuild/bin/resource/_objs/texture_extract_proto/resource/src/proto/texture_extract.pb.pic.o)
```

and fails since it a, either finds non-matching Protobuf headers in system or b, finds no Protobuf headers at all.
Seems like `cc_proto_library` is completely broken due to this currently.

### Environment info
* Operating System: Ubuntu 16.04
* Bazel version (output of `bazel info release`): 0.5.2

**Comment by cgrushko** [comment]
You can configure `cc_proto_library` by configuring the `@com_google_protobuf_cc` external repository, as described in http://blog.bazel.build/2017/02/27/protocol-buffers.html

The remote repository contains a `proto_lang_toolchain` rule that uses the proto runtime from that same remote repo.

I'm not exactly sure what you're trying to do and what's not working. What's wrong with the command line you mentioned?

**Comment by abergmeier-dsfishlabs** [comment]
> You can configure cc_proto_library by configuring the @com_google_protobuf_cc external repository, as described in http://blog.bazel.build/2017/02/27/protocol-buffers.html

You might be wrong there. AFAIK, `@com_google_protobuf_cc` only exposes `protoc`. I will read through that again, though.

> I'm not exactly sure what you're trying to do and what's not working. What's wrong with the command line you mentioned?

The commandline has no include path to the `@com_google_protobuf//:protobuf` library. So where should it find the includes from?

**Comment by cgrushko** [comment]
Does https://github.com/cgrushko/proto_library build for you?

**Comment by abergmeier-dsfishlabs** [comment]
I switched to 0.5.3 and the problem seems gone there.

**Comment by abergmeier-dsfishlabs** [comment]
Replacing `com_google_protobuf` and `com_google_protobuf_cc` used in Bazel with the ones from https://github.com/cgrushko/proto_library made it work.
