### ISSUE TITLE
Rename bazel/third_party/protobuf/3.2.0

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3486]
### Description of the problem / feature request / question:

At least as of 0.5.2, protobuf is >= 3.3.0 so please rename the directory.

### Environment info
* Bazel version (output of `bazel info release`): 0.5.2

**Comment by buchgr** [comment]
It's true that we don't use 3.2.0. We use protobuf at a random commit + a custom patch. This patch has been merged into protobuf mainline a week ago and we can upgrade protobuf to the next release as soon as there is one.

**Comment by abergmeier-dsfishlabs** [comment]
Seems like this was fixed in master.
