### ISSUE TITLE
current version has not support "define_values" in "config_setting"

### ISSUE THREAD

**Issue by tigerxiao** [bazelbuild/bazel#3487]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

when I read the website: https://docs.bazel.build/versions/master/be/general.html#config_setting
I got that i can use "define_values" in "config_setting" to satisfy my goal.
but I got an error when run the sample listed in the website.

"no such attribute 'define_values' in 'config_setting' rule"

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### If possible, provide a minimal example to reproduce the problem:
config_setting(
                name = "a_and_b",
                define_values = {
                    "a": "1",
                    "b": "2",
                })
        
### Environment info
* Operating System:
ubuntu

* Bazel version (output of `bazel info release`):
Build label: 0.5.3
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 28 08:34:59 2017 (1501230899)
Build timestamp: 1501230899
Build timestamp as int: 1501230899

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
no

### Anything else, information or logs or outputs that would be helpful?
no such attribute 'define_values' in 'config_setting' rule

**Comment by dslomov** [comment]
@serynth either the documentation or the code needs to be updated

**Comment by dslomov** [comment]
Sorry mis-assigned, reassigning to to @gregestren

**Comment by gregestren** [comment]
Both the documentation and supporting code were part of the same commit:

https://github.com/bazelbuild/bazel/commit/28ad27e5ef060174adf3a425ba63cd7e87ceb5a2

The documentation reflects the master branch, which 0.5.3 isn't up to yet. I think the only resolution here is to wait until the next Bazel release gets the supporting code. Apologies for the confusion.
