### ISSUE TITLE
Flag --auth_enabled is not respected for build event service (BES)

### ISSUE THREAD

**Issue by huangw5** [bazelbuild/bazel#3489]
According to the document:

> --[no]auth_enabled default: "false"
> Whether to enable authentication for remote execution/caching and the build event service (BES)

I found Bazel still does the authentication even when this flag is set to false. Further looking into BuildEventServiceGrpcClient.java, I found no check was performed against the above flag.

But I did see the flag was checked in ChannelOptions.java for remote execution.

**Comment by buchgr** [comment]
@huangw5 I have a change coming that fixes this! Thanks!

**Comment by buchgr** [comment]
Fixed by fe9ba893c0ebec19228086356af5fa8d81f2809b
