### ISSUE TITLE
bind() is documented as taking visibility (etc) but doesn't

### ISSUE THREAD

**Issue by steven-johnson** [bazelbuild/bazel#349]
http://bazel.io/docs/build-encyclopedia.html#bind documents bind() as accepting visibility (and other common BUILD arguments) but that doesn't appear to be the case. Either bind() or documentation should be fixed.

**Comment by damienmg** [comment]
The documentation should be fixed. Obviously you cannot change the visibility of a declared target (which bind would allow).
