### ISSUE TITLE
Consider refactoring Digraph to use com.google.common.graph

### ISSUE THREAD

**Issue by jbduncan** [bazelbuild/bazel#3490]
At the time of me writing this, `com/google/devtools/build/lib/graph/Digraph.java` is implemented using `Node`s and an internal `HashMap<T, Node<T>> nodes`.

However, a number of graph ADTs were introduced in Guava not too long ago, comprising of `com.google.common.graph.{Graph,ValueGraph,Network}`, which are arguably more pleasant to write with and to read. So there may be worthwhile benefits in refactoring `Digraph`'s API and internals to use these classes, such as maintainability, memory savings and performance improvements.

Thus, I propose the idea of investigating this in the medium to long term, to see if any such benefits could be obtained.

Understandably, this would be a _huge_ project, as `Digraph` and `Node` are apparently used a lot just in the open source version of Bazel, and I would hazard that they're used at just as extensively if not more in the Google-internal version of Bazel.

**Comment by dslomov** [comment]
Unless there is a specific perf problem that can fix, it is unlikely anyone on the team will work on this soon. But patches welcome.

**Comment by abergmeier-dsfishlabs** [comment]
@jbduncan Due to https://github.com/bazelbuild/bazel/issues/3549 I would be more interested in memory consumption and whether common enables some sort of packing.

**Comment by abergmeier-dsfishlabs** [comment]
To quote the docs:

> Does it support very large graphs (i.e., MapReduce scale)?
> Not at this time. Graphs in the low millions of nodes should be workable, but you should think of this library as analogous to the Java Collections Framework types (Map, List, Set, and so on).

Due to this I would _currently_ close this Issue. We, Google and others have multi-million of nodes.

**Comment by jbduncan** [comment]
> We, Google and others have multi-million of nodes.

Ah okay, that's a shame.

I'm on the edge about leaving this issue open or not, as the idea of using `common.graph` from a readability perspective still tempts me greatly.

I'm going to leave it open in the hope that, in the future, `common.graph`'s structures become as memory-efficient or even more so than **Digraph**. But if the Bazel team decide to close this issue in the meantime, then I won't press further.

**Comment by dslomov** [comment]
Per https://github.com/bazelbuild/bazel/issues/3490#issuecomment-322158570, switch to other implementation might be actually harmful
