### ISSUE TITLE
Windows, *_binary launcher: should work when rule is in an external repo

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3491]
If a {sh,py,java}_binary rule is in an external repository (e.g. `@bazel_tools//tools/android:zip_manifest_creator`), its exe launcher doesn't work because, in the case of sh_binary for example, the `bash_main_path` variable's value is computed from runfiles-relative path, which is "../build_tools/android/tools/zip_manifest_creator.sh" (relative to the execroot), which is not a valid entry in the manifest file.

Instead the rule should substitute the main file's exec path into `bash_main_file`, because that's the path in the manifest.

**Comment by laszlocsomor** [comment]
Release-critical for 0.5.4 / 0.6.0.

**Comment by dslomov** [comment]
We only use the launcher for sh_binary, right? 
Consider rolling back the use of launcher for 0.5.4

**Comment by laszlocsomor** [comment]
@meteorcloudy already fixed this with a oneliner

**Comment by laszlocsomor** [comment]
Yet you have a good point; the launcher may have other bugs we don't know about.
@meteorcloudy : How hard would be restoring the old launcher script mechanism, and adding a new command line flag (e.g. `--windows_exe_launcher`) that enables the exe launcher? That way we can roll out the feature as an rc file push, not as a release.

**Comment by meteorcloudy** [comment]
@laszlocsomor That's a good idea, and it shouldn't be too hard to do this.
