### ISSUE TITLE
presence of embedded jvm should not influence --javabase

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#3496]
The distribution of Bazel with an embedded JVM is great for hermetically distributing Bazel across diverse platforms. Unfortunately, by default, the embedded JVM leaks into builds. Specifically, Bazel uses the embedded JVM java base as `@local_jdk` and thus, by alias, the default value of `--javabase`. I think Bazel should use the same `--javabase` by default regardless of the presence of an embedded JVM.

**Comment by dslomov** [comment]
@philwo @iirina thoughts?

**Comment by cushon** [comment]
I agree it is not a good default for `--javabase`. It might be a good default for the right hand side `--host_javabase`, though.

**Comment by cushon** [comment]
Many of the tools that run in the host configuration are distributed with Bazel (e.g. JavaBuilder), and may not be compatible with the system JDK.

**Comment by benjaminp** [comment]
I see. How do you decide what bytecode version to compile to then? The system jdk may be older than the embedded Bazel JDK.

**Comment by cushon** [comment]
> How do you decide what bytecode version to compile to then?

Currently we default to Java 8, but it's an open question going forward. If you are targeting a specific version of Java it's probably a good idea to configure the desired `-source`/`-target` explicitly.

The current behaviour is still to use the embedded JDK as the default `--javabase`, but only if there is no locally installed JDK available.
