### ISSUE TITLE
query: support --relative_locations with --output=location

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#3497]
The `--relative_locations` flag makes the output of `query` with `--output=proto` and `--output=xml` more succinct, readable, and machine independent. However, `--relative_locations` does nothing for `--output=location`, whose output could also benefit from analogous abbreviation.

Technically, making `--relative_locations` have effect for `--output=location` would be a breaking change, since it currently silently does nothing. I'm not sure how serious that is, though.

**Comment by gregestren** [comment]
@meisterT - do you / we have an agreed on triage process for `query` bugs now? Note we have a `query bugs` label.
