### ISSUE TITLE
bazel-watcher is broken

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#3499]
http://ci.bazel.io/blue/organizations/jenkins/Global%2Fbazel-watcher/detail/bazel-watcher/62/pipeline

Seems that the reference to go rules should be updated

**Comment by vladmos** [comment]
There is already a pull request that fixes bazel-watcher: https://github.com/bazelbuild/bazel-watcher/pull/19

**Comment by vladmos** [comment]
The pull request has been merged.
