### ISSUE TITLE
Windows: running `bazel version` causes ERROR: Unrecognized option: --action_env=TEMP

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#3501]
http://ci.bazel.io/blue/organizations/jenkins/Global%2Fbazel-tests/detail/bazel-tests/136/pipeline/32

@laszlocsomor @dslomov 

Possibly caused by 0abf5fa

**Comment by meteorcloudy** [comment]
Solution might be only passing `--action_env=<tmp vars>` for build, test command?

**Comment by laszlocsomor** [comment]
Yes.

**Comment by laszlocsomor** [comment]
Let me fix it real quick.

**Comment by laszlocsomor** [comment]
p1 -> p3 because this was rolled back
