### ISSUE TITLE
Expected action_config for 'strip' to be configured

### ISSUE THREAD

**Issue by snnn** [bazelbuild/bazel#3505]
### Description of the problem / feature request / question:

Cannot build the latest bazel source code.

### If possible, provide a minimal example to reproduce the problem:

bazel build --config opt --color=no --compilation_mode opt --verbose_failures --experimental_ui src:bazel.exe

### Environment info
* Operating System:
Windows 10

* Bazel version (output of `bazel info release`):
development version

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
f7f1a8f756f33f86b1bdc5023d5052117b62523e

###  Have you found anything relevant by searching the web?
no

### Anything else, information or logs or outputs that would be helpful?
bazel build --color=no --compilation_mode opt --verbose_failures --experimental_ui src:bazel.exe
Loading:
ERROR: D:/os/bazel/src/main/tools/BUILD:50:1: in cc_binary rule //src/main/tools:linux-sandbox: Expected action_config for 'strip' to be configured.
Analyzing: target //src:bazel.exe
ERROR: Analysis of target '//src:bazel.exe' failed; build aborted
Analyzing: target //src:bazel.exe
INFO: Elapsed time: 0.394s
Analyzing: target //src:bazel.exe
FAILED: Build did NOT complete successfully

**Comment by meteorcloudy** [comment]
Already sent https://bazel-review.googlesource.com/#/c/bazel/+/14731/ to fix this ;)

**Comment by damienmg** [comment]
Is this still on? Why is there the breakage tag there?

**Comment by meteorcloudy** [comment]
This is fixed, it was breaking CI as well.
