### ISSUE TITLE
Bazel 0.5.3 does not build on CentOS 6.8 with GCC 4.8.2 in non standard location

### ISSUE THREAD

**Issue by samfux84** [bazelbuild/bazel#3506]
### local setup:

* CentOS 6.8
* GCC 4.8.2 installed in /cluster/apps/gcc/4.8.2
* Oracle JDK 1.8.0_91

### workflow:

1.) Download bazel-0.5.3-dist.zip
2.) build standalone bazel binary by running "bash ./compile.sh"
3.) Download 0.5.3.tar.gz from github release page
4.) Copy bazel standalone binary to 0.5.3 installation directory
5.) Edit tools/cpp/CROSSTOOL in the 0.5.3 installation directory

Replace all occurrences of /usr/bin/gcc with /cluster/apps/gcc/4.8.2/bin/gcc
Replace all occurrences of /usr/bin/cpp with /cluster/apps/gcc/4.8.2/bin/cpp
After the toolpath containing correct gcc path, add the lines

  linker_flag: "-L/cluster/apps/gcc/4.8.2/lib64"
  linker_flag: "-lstdc++"
  linker_flag: "-B/cluster/apps/gcc/4.8.2/bin/"
  linker_flag: "-Wl, -rpath, /cluster/apps/gcc/4.8.2/lib64"

  cxx_builtin_include_directory: "/cluster/apps/gcc/4.8.2/lib64"
  cxx_builtin_include_directory: "/cluster/apps/gcc/4.8.2/include/c++/4.8.2"
  cxx_builtin_include_directory: "/cluster/apps/gcc/4.8.2/include"

6.) Try to compile bazel with the bootstrapped bazel binary from bazel-0.5.3-dist.zip

### problem:

```
[sfux@develop01 x86_64]$ ./bazel build //src:bazel                                 
WARNING: ignoring http_proxy in environment.
WARNING: ignoring _JAVA_OPTIONS in environment.
WARNING: Output base '/cluster/home/sfux/.cache/bazel/_bazel_sfux/a47e9eb472ab0ee33f1212146187c5b6' is on NFS. This may lead to surprising failures and undetermined behavior.
..................
WARNING: /cluster/apps/bazel/0.5.3/x86_64/tools/build_defs/docker/docker.bzl:19:1: The docker_{build,bundle} rules bundled with Bazel are deprecated in favor of:
https://github.com/bazelbuild/rules_docker. Please change BUILD loads to reference: @io_bazel_rules_docker//docker:docker.bzl and add the following to your WORKSPACE:
git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    commit = "...",
)
load("@io_bazel_rules_docker//docker:docker.bzl", "docker_repositories")
docker_repositories().
WARNING: /cluster/apps/bazel/0.5.3/x86_64/tools/build_defs/pkg/pkg.bzl:196:9: pkg_tar: renaming non-dict `files` attribute to `srcs`.
INFO: Found 1 target...
INFO: From Compiling src/main/tools/process-wrapper-options.cc:
src/main/tools/process-wrapper-options.cc:53:13: warning: 'void ValidateIsAbsolutePath(char*, char*, char)' defined but not used [-Wunused-function]
 static void ValidateIsAbsolutePath(char *path, char *program_name, char flag) {
             ^
ERROR: /cluster/apps/bazel/0.5.3/x86_64/third_party/java/jarjar/BUILD:31:1: Building deploy jar third_party/java/jarjar/jarjar_command_deploy.jar failed (Exit 1).
external/bazel_tools/tools/jdk/singlejar/singlejar: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by external/bazel_tools/tools/jdk/singlejar/singlejar)
external/bazel_tools/tools/jdk/singlejar/singlejar: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by external/bazel_tools/tools/jdk/singlejar/singlejar)
Target //src:bazel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 35.918s, Critical Path: 7.99s
[sfux@develop01 x86_64]$
```

Any idea ?

**Comment by buchgr** [comment]
cc @mhlopko

**Comment by hlopko** [comment]
Closing this issue, there were many improvements in autoconfiguration of C++ toolchain in the last year, pls file a new issue if there are bugs there for centos. Thanks!
