### ISSUE TITLE
Bazel unconditionally adds -isystem external/bazel_tools/tools/cpp/gcc3 to the compile command line

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/bazel#3507]
And more importantly, hlopko@ has no idea why this behavior was ever introduced. Figure out if it's still needed and don't add it when it's not.

**Comment by indrgun** [comment]
What is external/bazel_tools/tools/cpp/gcc3?   Does it cause "/usr/include/libio.h:307:3: error: unknown type name 'size_t'"?

**Comment by indrgun** [comment]
I am getting this error with macro calling cc_binary:

/nobackup/ingunawa/bazel_output_user_root/437be82108db050e294afe7481920630/execroot/ios_xr/_bin/process-wrapper '--timeout=0' '--kill_delay=15' /router/bin/gcc.c4.7.0-p3.x86_64 -g0 -MD -MF bazel-out/host/bin/sysdb/_objs/bgen.cc_binary/sysdb/bgen/src/bgen_lex.d -iquote . -iquote bazel-out/host/genfiles -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -I bazel-out/host/bin/sysdb/_virtual_includes/backend_headers -I bazel-out/host/bin/linux/os/_virtual_includes/headers -I bazel-out/host/bin/thirdparty/opensource/sdk/_virtual_includes/x86_64_headers -I bazel-out/host/bin/thirdparty/opensource/sdk/_virtual_includes/x86_64_headers_bits_headers -I bazel-out/host/bin/thirdparty/opensource/sdk/_virtual_includes/x86_64_linux_headers -isystem external/bazel_tools/tools/cpp/gcc3 -c -fno-builtin -g '-DCPP_CMD=gcc.c4.7.0-p1 -D DISABLE_API_VERSION_MACRO -D__BASE_OS_LINUX__ -D__x86_64__ -E %s -x c %s -o %s' -DSIGNAL_H_MISSING_SIGEVENT_STRUCT -Ibgen/src -O2 -fno-inline-functions-called-once -fno-strict-aliasing -fno-omit-frame-pointer -fno-reorder-functions -c bazel-out/host/bin/sysdb/bgen/src/bgen_lex.c -o bazel-out/host/bin/sysdb/_objs/bgen.cc_binary/sysdb/bgen/src/bgen_lex.o).
In file included from bazel-out/host/bin/thirdparty/opensource/sdk/_virtual_includes/x86_64_headers/lnx/stdio.h:74:0,
                 from bazel-out/host/bin/linux/os/_virtual_includes/headers/xros_wrapper.h:40,
                 from bazel-out/host/bin/linux/os/_virtual_includes/headers/stdio.h:14,
                 from bazel-out/host/bin/sysdb/bgen/src/bgen_lex.c.temp:12:
/usr/include/libio.h:307:3: error: unknown type name 'size_t'
/usr/include/libio.h:311:67: error: 'size_t' undeclared here (not in a function)
/usr/include/libio.h:339:62: error: expected declaration specifiers or '...' before 'size_t'
/usr/include/libio.h:348:6: error: expected declaration specifiers or '...' before 'size_t'
/usr/include/libio.h:470:19: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_IO_sgetn'

My question:
1. Why there is "-g0"?  It is commented out in the host tool's CROSSTOOL file and where is "-g0 -MD -MF" coming from? why it is building *.d?

The /usr/include in "cxx_builtin_include_directory" in the host CROSSTOOL has "size_t" defined.  

2. Why the error is traced back to bazel-out/host/bin/sysdb/bgen/src/bgen_lex.c.temp?  This is intermediary output of a target that produces bgen_lex.c.  I don't include it in the struct's depset of that target's rule skylark implementation output.

**Comment by mhlopko** [comment]
Uff too many questions to respond to without inline responses. I'll try.

I don't know what external/bazel_tools/tools/cpp/gcc3 is but without it google breaks. I didn't have time to investigate more.

I don't know if it causes unknown type name 'size_t'.

Bazel patches legacy crosstools by https://github.com/bazelbuild/bazel/blob/275ae45b1228bdd0f912c4fbd634b29ba4180383/src/main/java/com/google/devtools/build/lib/rules/cpp/CppActionConfigs.java I think that's where the flags come from. Unless you have a custom crosstool that defines feature named 'no_legacy_features'. Let me know if you do.

C++ rules unconditionally generate .d file (last time I checked it was not trivial to turn it off) and use the information to speed up the build (by not rebuilding targets that don't really use the changed dependency).

I've no idea why the error is tracked back to bazel-out/host/bin/sysdb/bgen/src/bgen_lex.c.temp, you can investigate by running bazel with `--subcommands`, then observing the commands bazel generates, `cd`-ing into the sandbox, and running the command manually. That's how I debug similar issues.

**Comment by mhlopko** [comment]
Anecdata, the addition of this gcc3 into blaze happened 12 years ago, and since 9 years ago it was considered a hack that should go away :)
