### ISSUE TITLE
bazel 0.5.3 checksum mismatch

### ISSUE THREAD

**Issue by ilovezfs** [bazelbuild/bazel#3509]
URL:
https://github.com/bazelbuild/bazel/releases/download/0.5.3/bazel-0.5.3-dist.zip

Expected SHA-256: d6d27e87bb3ccc6f70f885d51b70c4a9924f0b198dec8ccb82baceb912075212

Actual SHA-256:
76b5c5880a0b15f5b91f7d626c5bc3b76ce7e5d21456963c117ab711bf1c5333

The expected checksum is what we had in Homebrew for the SHA-256 when the formula was upgraded to version 0.5.3 on Thu Jul 27 12:22:06 2017 -0700. See https://github.com/Homebrew/homebrew-core/pull/16132.

But currently downloading the file gives a different checksum.

I wanted to make sure you weren't hacked, and ask what the reason(s) for the changes were.

CC @mhlopko @damienmg

**Comment by buchgr** [comment]
There was a bug in the release procedure for windows and so we had to re-create the release the next day [1]. Now, the contents, file timestamps, ... and so must be the same. However, I suspect that zip adds some metadata (timestamp?) to the zip file or maybe the compression algo is not deterministic.

Testing this theory on my MBP:
```
$ echo "hello world" > test.txt
$ shasum test.txt 
22596363b3de40b06f981fb85d82312e8c0ed511  test.txt
$ zip test1.zip test.txt 
  adding: test.txt (stored 0%)
$ zip test2.zip test.txt
  adding: test.txt (stored 0%)
$ shasum test1.zip test2.zip 
57554e52c9f2d95b4e72d6458eba99b06730b9f3  test1.zip
a7c33e9d91ad634e33c78aa6c2c43e579e575051  test2.zip
```

I ll look into this in detail on Monday, but I think that's the likely explanation.

[1] https://groups.google.com/forum/#!topic/bazel-discuss/np39cH-nvTY

**Comment by chocol4te** [comment]
Is it OK to just change the hash for the 0.5.3 release?

**Comment by buchgr** [comment]
Hmm, I inspected our `-dist` file using `zipinfo -v` and we don't seem to have any metadata encoded in the zip formats "extra header", while my local zip program does that.

**Comment by buchgr** [comment]
@ilovezfs @chocol4te do you guys have the zip file with the hash `d6d27e87bb` somewhere? So then I could compare them and see the difference.

**Comment by chocol4te** [comment]
I might do, give me a second :)

**Comment by chocol4te** [comment]
Sorry, the only one in my cache folder has the 76b5c5880a hash, same as the release in the Bazel repo.

**Comment by buchgr** [comment]
I found it. It's still cached on our jenkins release pipeline: http://ci.bazel.build/view/Bazel%20bootstrap%20and%20maintenance/job/Global/job/pipeline/156/

**Comment by buchgr** [comment]
Ok we are all good. @ilovezfs @chocol4te it's safe to update to the new hash.

Here's how I verified:
```
$ shasum -a 256 bazel_27.zip bazel_28.zip 
d6d27e87bb3ccc6f70f885d51b70c4a9924f0b198dec8ccb82baceb912075212  bazel_27.zip
76b5c5880a0b15f5b91f7d626c5bc3b76ce7e5d21456963c117ab711bf1c5333  bazel_28.zip
$ unzip bazel_27.zip -d bazel_27 > /dev/null
$ unzip bazel_28.zip -d bazel_28 > /dev/null
$ diff -r bazel_27 bazel_28
diff -r bazel_27/scripts/release/common.sh bazel_28/scripts/release/common.sh
44c44
<   git notes --ref=release-candidate show "$@" 2>/dev/null | xargs echo || true
---
>   git notes --ref=release-candidate show "$@" 2>/dev/null  || true
49c49
<   git notes --ref=release show "$@" 2>/dev/null | xargs echo || true
---
>   git notes --ref=release show "$@" 2>/dev/null  || true
Only in bazel_28/scripts/release: common.sh.bak
```

So these two releases are different, in that the release script `common.sh` is different (notice the `xargs echo`).  I have to follow up with @damienmg why this was not mentioned in the cherry-picks.

Thanks for reporting guys @ilovezfs @chocol4te!

**Comment by ilovezfs** [comment]
Thanks! https://github.com/Homebrew/homebrew-core/pull/16461

**Comment by damienmg** [comment]
As a side note: in the future, you might want to verify the signature of
the artifact. We don't plan to do those kind of binary updates but we can
never predict failure mode if the release fails to produce some binaries,
so we are not free from those kind of change.

We should also remove the timestamp from the zip file...

**Comment by buchgr** [comment]
> We should also remove the timestamp from the zip file...

Timestamp wise we are good I believe. The bazel release .zip does not contain a timestamp.

**Comment by ilovezfs** [comment]
@damienmg it is a matter of policy for Homebrew that an issue be filed upstream whenever a checksum changes without the version changing (i.e. whenever a "stealth update" occurs). Ideally this should never happen, and the patch level version should be bumped instead.

**Comment by damienmg** [comment]
We should be able to replay a build then forcing the SOURCE_DATE_EPOCH so
we regenerate binary with exactly the same timestamp when the problem is
not on the binary.
