### ISSUE TITLE
Relative path construction not possible

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3515]
### Description of the problem / feature request / question:

I have the following in an aspect:

```
# output = "../foo_repo/bar.deps.id"
runfile_ids = ctx.new_file("%s.runfile_ids" % output.short_path)
```

Which gives me an error:
```
external/foo_repo/../foo_repo/bar.deps.id.runfile_ids
```

Would have expected it to be able to process the filepath.

### Environment info
* Operating System: Ubuntu 16.04.2
* Bazel version (output of `bazel info release`): 0.5.2

**Comment by abergmeier-dsfishlabs** [comment]
Workaround currently is to use
```
runfile_ids = ctx.new_file(output, "%s.runfile_ids" % output.basename)
```

**Comment by laurentlb** [comment]
See https://github.com/bazelbuild/bazel-skylib for extra functions on paths.
