### ISSUE TITLE
verbose_failures no longer works in 0.5.3

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3521]
### Description of the problem / feature request / question:

Previously, when e.g. `gcc` failed it printed all the arguments when built with `--verbose_failures`. In 0.5.3, it only prints a few and then `... (remaining 173 argument(s) skipped)`.

### Environment info
* Operating System: Ubuntu 16.04.2
* Bazel version (output of `bazel info release`): 0.5.3

**Comment by mhlopko** [comment]
cc @philwo

**Comment by mhlopko** [comment]
So I confirmed it works in bazel 0.5.2, and it does work internally. It's only Bazel that's affected. I tracked it down to [AbstractSandboxSpawnStrategy](https://github.com/bazelbuild/bazel/blob/05f563a97581959db5da0cb02daf87cfa20c6b88/src/main/java/com/google/devtools/build/lib/sandbox/AbstractSandboxSpawnRunner.java#L102) where we don't query verbose_failures but sandbox_debug when deciding whether to log the full command.

**Comment by mhlopko** [comment]
Passing over to @ulfjack :)

**Comment by ulfjack** [comment]
You mean AbstractSandboxSpawnRunner, not *Strategy, and you link to the right file. I was only briefly confused.

**Comment by ulfjack** [comment]
If it's a release blocker than it should be P1. :-P

**Comment by mhlopko** [comment]
Sorry for the confusion :)
