### ISSUE TITLE
bazel_bootstrap_distfile_test.sh failing on windows

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/bazel#3529]
Ci won't show you nice test failure (http://ci.bazel.io/blue/organizations/jenkins/Global%2Fbazel-tests/detail/bazel-tests/150/tests) because it cannot parse the xml because of unrelated problem.

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="1" failures="0" errors="1"><testsuite name="bazel_bootstrap_distfile_test.sh" tests="1" failures="0" errors="1">
<testcase name="test_bootstrap" status="run" time="189.408" classname="">
<error message="Expected to be able to bootstrap bazel">
<![CDATA[ [32mINFO [0m: You can skip this first step by providing a path to the bazel binary as second argument:
[32mINFO [0m:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch......scripts/bootstrap/compile.sh: line 256: src/main/native/windows/build_windows_jni.sh: No such file or directory
-- Test log: -----------------------------------------------------------
------------------------------------------------------------------------
test_bootstrap FAILED: Expected to be able to bootstrap bazel .
C:/jenkins/workspace/global/bazel-tests-toolchain=msvc,node=windows-x86_64,variation=/src/test/shell/bazel/bazel_bootstrap_distfile_test.sh:41: in call to test_bootstrap]]>
</error>
</testcase>
</testsuite>
</testsuites>
```

**Comment by laszlocsomor** [comment]
I'm afraid this was cauesed by https://github.com/bazelbuild/bazel/commit/c28e2e0e0433f03cab8dcac964436ba6617be54a which removed that file.

**Comment by laszlocsomor** [comment]
@meteorcloudy : FYI

**Comment by meteorcloudy** [comment]
Sorry for the breakage, I'm fixing it!

**Comment by meteorcloudy** [comment]
However, It's strange this failing test doesn't show up at http://ci.bazel.io/blue/organizations/jenkins/bazel-tests/detail/bazel-tests/948/tests

**Comment by mhlopko** [comment]
It does, it's just hidden behind test.xml failure :)

**Comment by meteorcloudy** [comment]
Ah... 😂

**Comment by meteorcloudy** [comment]
@laszlocsomor Do we need to build JNI separately during bootstrap? I mean, why we don't need to build it on Linux?

**Comment by laszlocsomor** [comment]
@meteorcloudy : We do. On Linux we use a pure Java implementation of the Filesystem class (JavaIoFileSystem) while bootstrapping, which is fully functional just less efficient than the UnixFileSystem. On Windows however we must use the WindowsFileSystem which needs JNI, because JavaIoFileSystem doesn't support all operations (namely creating or identifying junctions). See [BlazeRuntime.fileSystemImplementation](https://github.com/bazelbuild/bazel/blob/5a661c793f54b092c5bfc2f4f0049c9f2e317843/src/main/java/com/google/devtools/build/lib/runtime/BlazeRuntime.java#L798-L805).

**Comment by meteorcloudy** [comment]
@laszlocsomor Thanks for the explanation!
Reopening this.. (Closed by accident)

**Comment by meteorcloudy** [comment]
Since c28e2e0e0433f03cab8dcac964436ba6617be54a is in 0.5.4, this should be a release blocker.

**Comment by mhlopko** [comment]
Does it mean  4a2e17f needs to be cherry picked?

**Comment by laszlocsomor** [comment]
Ah yes it does.
