### ISSUE TITLE
Make py_binary have zipped binary as implicit output

### ISSUE THREAD

**Issue by kamalmarhubi** [bazelbuild/bazel#3530]
I'd like to be able to depend on the zipped python binary for distribution, but not build the zipped binary usually. To do this, I'd like to specify `//path/to/my/py_binary_target.zip` as a dependency of my distribution artifact.

At the moment, it's possible to build with `--build_python_zip`, but I'd rather not have to use different flags for ordinary builds and distribution builds.

### Environment info
* Operating System:

        $ lsb_release --description 
        Description:    Debian GNU/Linux testing (buster)

* Bazel version (output of `bazel info release`): `release 0.5.3`

###  Have you found anything relevant by searching the web?

Found some info in https://bazel.build/designs/2016/09/05/build-python-on-windows.html

**Comment by duggelz** [comment]
An alternative would be to add an explicit attribute to `py_binary`/`py_test` rules that changes the behavior for that single target, from the current behavior (generated "py_binary_target" is a shell script that invokes the "py_binary_target.runfiles/" tree on Linux), to the "--build_python_zip" behavior ("py_binary_target" is a zip file with '#!" line).

**Comment by shs96c** [comment]
The implicit output seems a lot more predictable: if you want the zip, ask for the zip. It also allows for faster iteration as `bazel run` won't require the building of a zip.

As a final point, if anyone ever lands PEX support (#2038) then that could also be implemented as an implicit output, rather than Yet Another Parameter.

**Comment by brandjon** [comment]
In considering the native rules' zip files vs subpar, I'm thinking we should aim to implement this and deprecate subpar. See google/subpar#44 for more discussion.

It may also be worth renaming the `.zip` extension to `.pyz` after [PEP 441](https://www.python.org/dev/peps/pep-0441/).

**Comment by meteorcloudy** [comment]
Sounds good. But I guess our `.zip` file doesn't work exactly the way `.pyz` file work?

**Comment by brandjon** [comment]
My understanding is that Python itself shouldn't care about the file extension, but using a different extension may affect file associations in the OS shell. While not all versions of Python would recognize `.pyz` under windows, you'd think it'd be no worse than leaving it as `.zip` where the default association would be some extractor tool.

Pep 441 explicitly mentions that the zip format may be used with shebang lines and self-extracting archives, so I don't see a conflict.

**Comment by groodt** [comment]
Is there any update or movement here? 

It would be great to be able to reference:
`//path/to/my/py_binary_target.zip`

and have the executable zip consumed in other targets, such as rules_docker.

**Comment by meteorcloudy** [comment]
I think it's preferred to not have implicit output. How about we add it to a output group called `python_zip_file`, then you can access it by
```
filegroup(
  name = "foo_zip",
  srcs=  ["//bar:foo"],
  output_group = "python_zip_file",
)
```

**Comment by groodt** [comment]
This would be wonderful @meteorcloudy 

I'd be keen to try help implement this as well if necessary. Or is this something that you are already wishing to take on? I imagine this would need to be added to rules_python and not Bazel itself, however, I have no current knowledge of what `--build_python_zip` is doing behind the covers in the Bazel code.

**Comment by meteorcloudy** [comment]
@groodt I think this should be implemented in the native python rule, because that's what `--build_python_zip` applies to.
I sent https://github.com/bazelbuild/bazel/pull/9453, please take a look.

**Comment by brandjon** [comment]
Thanks @meteorcloudy for the implementation!
