### ISSUE TITLE
0.5.3 brought UI regression of repository rules

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#3534]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I have a repository rule which takes some time to complete.
It calls `repository_ctx.execute(args, quiet = False)` to do the actual action and the executed process prints its progress.
In 0.5.2 the rule printed its progress as it worked.
In 0.5.3 the output is printed after the rule finishes so effectively there is no output and when it finishes I get ~30 lines in one batch.  

### If possible, provide a minimal example to reproduce the problem:
given this [repo](https://github.com/ittaiz/bazel-block-network-issue)
run `bazel build //...` with bazel 0.5.2 and see the progress.
Do `bazel clean --expunge` and run the build again with bazel 0.5.3 to see the progress is only flushed at the end.

### Environment info
* Operating System:
Mac OS 10.12

**Comment by ittaiz** [comment]
@kchodorow any thoughts?

**Comment by kchodorow** [comment]
For reasons I don't entirely understand, adding `/bin/bash -c` makes it print, e.g.,

```
# Prints nothing
ctx.execute(['echo "hi"''], quiet = False)
# Prints 'hi'
ctx.execute(["/bin/bash", "-c", 'echo "hi"'], quiet = False)
```

Adding @ulfjack, who last changed the output handling.

**Comment by ittaiz** [comment]
Hi,
Any news?

**Comment by ulfjack** [comment]
Klaus, I wonder if this is related to changes you made?

**Comment by aehlig** [comment]
> Klaus, I wonder if this is related to changes you made?

I don't think so. Bisecting shows that it was your change 70f84252a0 that caused the new behavior. Reverting it on master (it is in fact a clean revert) gives the old behavior.

**Comment by ittaiz** [comment]
@ulfjack ping?

**Comment by ulfjack** [comment]
Sorry, I've been OOO. Hopefully I'll get to it this week.

**Comment by ulfjack** [comment]
I'll revert the change. I don't think anything depends on it yet, and I don't have time right now to investigate in more detail.

**Comment by ittaiz** [comment]
Thanks!
