### ISSUE TITLE
Windows: some Java tests (`src/test/**/*.java`) are disabled on Windows (they test `OS.getCurrent()`)

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#3536]
See the .java files for TODOs.

**Comment by ulfjack** [comment]
The tests are currently not running due to us missing java_test rules.

**Comment by ulfjack** [comment]
The paths we get in the LocalSpawnRunnerTest are particularly odd - File should treat files with "/foo/bar" as absolute, shouldn't it?

**Comment by laszlocsomor** [comment]
Dropping priority to P3. I'd like to eventually fix these tests, but it doesn't seem to be critical right now.

**Comment by meteorcloudy** [comment]
Closing because it's an obsolete issue
