### ISSUE TITLE
consider accepting SkylarkSemanticsOptions for all commands

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#3538]
To properly use the skylark semantics options, all commands that can load skylark must receive them. In Bazel, these commands are currently `build` and its descendants, `query`, and `fetch`. This means a forward-looking bazelrc must keep 3 copies of the skylark semantic options in sync. It would nicer to be to just put these in the `common` section.

Alternatively, maybe the rc format should have a nice way to specify options for several commands at once. E.g.
```build,query,fetch --some_option```

**Comment by dslomov** [comment]
@brandjon wdyt?

**Comment by brandjon** [comment]
Spoke with @cvcal, looks like making it a common option is the easiest thing to do.

**Comment by brandjon** [comment]
Fix inbound in an upcoming commit.
