### ISSUE TITLE
Add strip_prefix_slashes to *http_archive

### ISSUE THREAD

**Issue by drigz** [bazelbuild/bazel#3539]
**Feature request**

Writing a WORKSPACE file involves lots of boilerplate like this:

```
native.new_http_archive(
name = "eigen_archive",
url = "https://bitbucket.org/eigen/eigen/get/" + eigen_version + ".tar.gz",
sha256 = eigen_sha256,
strip_prefix = "eigen-eigen-" + eigen_version,
build_file = str(Label("//:eigen.BUILD")),
)
```

This could be simplified by adding an alternative to `strip_prefix` called `strip_prefix_slashes` taking an integer, eg:

`strip_prefix_slashes = 1,`

This avoids repeating the repo name & tag/sha, and would be more robust (see [rules_go](https://github.com/bazelbuild/rules_go), which says "the strip_prefix part can break if the repository is renamed"). It follows the precedent of [patch(1)](https://linux.die.net/man/1/patch).

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
