### ISSUE TITLE
java_test target doesn't run any test when running directly

### ISSUE THREAD

**Issue by mzhaom** [bazelbuild/bazel#354]
I have a java_test target that runs the tests when running with bazel test foo
But if I run bazel-bin/java/foo, it says 0 test cases has run, does the generated wrapper script miss any arg?

**Comment by damienmg** [comment]
The test runner we use is the JUnit one and it's expect to be given the testsuite to run as argument (which bazel test/run does add ). We have a work of open-sourcing our own test runner which should make those stuff a bit more easy.

I will close as working as intended but improvements are to come.

**Comment by mzhaom** [comment]
Can the document be updated? The discrepancy between bazel test and running bazel-bin/... is slightly unexpected for java_test. Also, what is testsuite argument passed by bazel test?

**Comment by damienmg** [comment]
The arguments are passed to [JUnitCore](http://junit.org/apidocs/org/junit/runner/JUnitCore.html) (see https://github.com/google/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/java/BazelJavaTestRule.java#L50). The code to pass the good argument is there: https://github.com/google/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/java/BazelJavaSemantics.java#L343 

I think it's more likely we fix the underlying problem (there is no correct test launcher so we call directly the JUnitCore launcher).

**Comment by mzhaom** [comment]
Please do fix the underlying problem. I don't think even the argument builder is doing the right thing at the moment, sometimes it just can't figure out the right class name to run.

**Comment by xavigonzalvo** [comment]
Tests are only going to work if they are under a java/ folder.

**Comment by damienmg** [comment]
or javatests. We want to lift that enforcement

**Comment by kchodorow** [comment]
Just a note: tests should also work from src/*/java directories.

**Comment by ulfjack** [comment]
Tests work just find outside of java/ or javatests/ directories, they just need a little bit more configuration. Bazel tries to automatically determine the name of the test class from the source file names, which doesn't always work. You can help it along by explicitly passing the name of the test class in the args attribute, like so:

$ cat foo/Foo.java
package foo;
import org.junit.Test;
public class Foo {
  @Test
  public void doNothing() {
    // Does nothing.
  }
}
$ cat foo/BUILD
java_test(
  name = "foo",
  srcs = ["Foo.java"],
  deps = ["//third_party:junit4"],
  args = ["foo.Foo"],
)
$ bazel test //foo --test_output=all
INFO: Found 1 test target...
INFO: From Testing //foo:foo:
==================== Test output for //foo:foo:
JUnit version 4.11
.
Time: 0,007

OK (1 test)

================================================================================
Target //foo:foo up-to-date:
  bazel-bin/foo/foo.jar
  bazel-bin/foo/foo
INFO: Elapsed time: 0,600s, Critical Path: 0,40s
//foo:foo                                                                PASSED

Executed 1 out of 1 tests: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.

**Comment by damienmg** [comment]
This was shiped a long time ago so this bug is fixed.

**Comment by ittaiz** [comment]
The runner that was shipped was BazelTestRunner?

**Comment by ulfjack** [comment]
The documentation isn't very good. But yes, we shipped BazelTestRunner, and we recommend using it, but you don't have to, and can override by setting main_class. java_test should also try to guess the main class name, but you can override by setting test_class.

At least I think that's how it should work right now.

**Comment by SalzzZ** [comment]
I'm trying to use JUnit5's TestRunner, and set
`main_class = "org.junit.platform.console.ConsoleLauncher"`
but it fails as the class need argument (particularly [-a](http://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher) to run all tests). How to define arguments to be passed to java_test / java_binary?

**Comment by ulfjack** [comment]
Like so?

java_test(
  name = "mytests',
  main_class = "org.junit.platform.console.ConsoleLauncher",
  args = ["-a"],
)

**Comment by SalzzZ** [comment]
thanks @ulfjack , how about adding classpath?
I used jvm_flags, but the classpath got overriden
can I do something like:
jvm_flags {
 "-classpath = /new/classpath:$(OLD_CLASSPATH)"
}

**Comment by ulfjack** [comment]
Why do you need to override the classpath? Can't you just add the library to deps?

**Comment by SalzzZ** [comment]
So here's the case:
java_* library only add jars to the classpath;
JUnit 5 M1 doesn't support [classpath scanning within Jar Files](https://github.com/junit-team/junit5/issues/399), so it can't find my test classes within the jar
I think this is JUnit5 issue but maybe I can workaround it by overriding classpath

**Comment by marcphilipp** [comment]
@SalzzZ The latest snapshot of JUnit 5 now supports classpath scanning within JAR files if you select a base package to be run. The `-a` has been renamed to `--scan-class-path` for M3 and does still only scans _directory_ classpath entries. If you need it to scan JARs, too, please open an issue for JUnit 5.
