### ISSUE TITLE
Cannot compile with copts containing space on mac

### ISSUE THREAD

**Issue by sulume** [bazelbuild/bazel#3541]
### Description of the problem / feature request / question:

It fails to compile cc target with copts containing spaces (or maybe any character needed to escape on shell) on mac. I defined a macro `-D_START_GOOGLE_NAMESPACE_="namespace google {"` to build glog like https://github.com/google/glog/issues/61.
```
clang: error: no such file or directory: 'google'
clang: error: no such file or directory: '{'
```

This is likely caused by [wrapped_clang](https://github.com/bazelbuild/bazel/blob/master/tools/osx/crosstool/wrapped_clang.tpl) incorrectly passing arguments. I'd think it could succeed by just replacing `clang $@` with `clang "$@"`. I could make a change if that's considered reasonable but the wrapper script has been rolled back and forward twice maybe due to a regression (missing details though.) I don't know how it's designed and wonder the validity of that way.

### If possible, provide a minimal example to reproduce the problem:

BUILD (for arbitrary a.cc):
```python
cc_binary(name="a",srcs=["a.cc"],copts=["-DM='a b'"])
```
bazel 0.5.3
```bash
$ bazel build :a
INFO: Found 1 target...
ERROR: (workspace)/BUILD:1:1: C++ compilation of rule '//:a' failed (Exit 1).
clang: error: no such file or directory: 'b'
Target //:a failed to build
```
bazel 0.4.5
```bash
$ bazel build :a
INFO: Found 1 target...
Target //:a up-to-date:
  bazel-bin/a
```

### Environment info
* Operating System: macOS 10.12.6

* Bazel version (output of `bazel info release`): release 0.5.3-homebrew

**Comment by iirina** [comment]
you can send us a change to review with your suggested change. The lack of details for the rollbacks/rollforwards is probably due to some internal factors. Marcel can tell you more about the validity of your suggestion.

**Comment by vthuongt** [comment]
I facing the same problem on Ubuntu 18.04 as well. I tried to use `gcc` with the following flags:

    --copt=-mmmx --copt=-mno-3dnow --copt=-msse --copt=-msse2 --copt=-msse3 --copt=-mssse3 --copt=-mno-sse4a --copt=-mcx16 --copt=-msahf --copt=-mno-movbe --copt=-mno-aes --copt=-mno-sha --copt=-mno-pclmul --copt=-mno-popcnt --copt=-mno-abm --copt=-mno-lwp --copt=-mno-fma --copt=-mno-fma4 --copt=-mno-xop --copt=-mno-bmi --copt=-mno-bmi2 --copt=-mno-tbm --copt=-mno-avx --copt=-mno-avx2 --copt=-mno-sse4.2 --copt=-mno-sse4.1 --copt=-mno-lzcnt --copt=-mno-rtm --copt=-mno-hle --copt=-mno-rdrnd --copt=-mno-f16c --copt=-mno-fsgsbase --copt=-mno-rdseed --copt=-mno-prfchw --copt=-mno-adx --copt=-mfxsr --copt=-mno-xsave --copt=-mno-xsaveopt --copt=-mno-avx512f --copt=-mno-avx512er --copt=-mno-avx512cd --copt=-mno-avx512pf --copt=-mno-prefetchwt1 --copt=-mno-clflushopt --copt=-mno-xsavec --copt=-mno-xsaves --copt=-mno-avx512dq --copt=-mno-avx512bw --copt=-mno-avx512vl --copt=-mno-avx512ifma --copt=-mno-avx512vbmi --copt=-mno-clwb --copt=-mno-mwaitx --copt=-mno-clzero --copt=--param l1-cache-size=32 --copt=--param l1-cache-line-size=64 --copt=--param l2-cache-size=2048 --copt=-mtune=core2

The problem comes from the last 3 arguments `--copt=--param ....` which contain spaces. When I compile without those flags, the compilation works.

How can I fix this problem?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
