### ISSUE TITLE
Search field doesn't work from blog

### ISSUE THREAD

**Issue by drigz** [bazelbuild/bazel#3543]
1. Go to https://blog.bazel.build/
1. Perform a search with the search at the top
1. Get redirected to https://blog.bazel.build/search.html?q=search which is a 404

It works fine from https://bazel.build/, which includes blog results, so I guess you just need to include the host in the URL.

**Comment by DirtyF** [comment]
Like many popular documentation websites, Bazel could benefit from [Algolia's docsearch](https://community.algolia.com/docsearch/).

**Comment by drigz** [comment]
Looks like this issue has now been resolved.
