### ISSUE TITLE
Feature request: link to source on Build Encyclopedia docs

### ISSUE THREAD

**Issue by drigz** [bazelbuild/bazel#3545]
Some documentation pages have an edit button, eg the [Overview](https://docs.bazel.build/versions/master/bazel-overview.html):

![image](https://user-images.githubusercontent.com/632207/29215935-3da52e5c-7ead-11e7-8270-e4be28ba3998.png)

But it's not in the Build Encyclopedia, eg:
https://docs.bazel.build/versions/master/be/overview.html (could link to src/main/java/com/google/devtools/build/docgen/templates/be/overview.vm)

This is presumably because the Build Encyclopedia is generated from comments in the code. However, this complexity means it would be even more helpful. For example, to create [this PR](https://github.com/bazelbuild/bazel/pull/3544) I had to:
1. Notice the typo
1. Look for the edit button, fail to find it
1. Clone bazelbuild/bazel
1. Grep for "beforethis"
1. Go to the [source file on GitHub](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/cpp/BazelCppRuleClasses.java)
1. Make the edit

Maybe the rule docs could link to the source files? eg

![image](https://user-images.githubusercontent.com/632207/29217478-3346bc28-7eb2-11e7-9488-8078c40ca3a5.png)

**Comment by meisterT** [comment]
They do now.
