### ISSUE TITLE
startup_options_test fail on windows on ci.bazel.io

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/bazel#3546]
e.g. http://ci.bazel.io/job/bazel-tests/954/testReport/junit/src_test_cpp_startup_options_test/exe/src_test_cpp_startup_options_test_exe/

**Comment by mhlopko** [comment]
It passes on global pipeline.

**Comment by mhlopko** [comment]
Hmm stopped failing?

**Comment by meteorcloudy** [comment]
Eh... No idea why..

**Comment by damienmg** [comment]
no new instance --> closing
