### ISSUE TITLE
building bazel from scratch failed...

### ISSUE THREAD

**Issue by ddwolf** [bazelbuild/bazel#3547]
I found that you don't support building bazel from scratch, because:
1. the document describes the standard way of install bazel is to download a bazel binary and then compile using this binary;
2. and I found that building from scratch is a totally disaster

Is the conclusion correct?

**Comment by jbduncan** [comment]
Hi @ddwolf, it's not terribly clear from your description (for me, at least) what exact problem you're experiencing. Please can you try specifying as much information as you can that the [issue template](https://github.com/bazelbuild/bazel/blob/master/ISSUE_TEMPLATE.md) asks for. I think that the Bazel team would be more likely to respond and be able to help you that way.

**Comment by ddwolf** [comment]
@jbduncan yeah you are right, I 'll start a new issue describe problems I encountered, or just follow the Instructions on the official website.

**Comment by siyangy** [comment]
@ddwolf I am hitting the same issue when compiling bazel from source. Have you found a solution to it?

**Comment by ddwolf** [comment]
@siyangy well, I didn't find a way, you can install a prebuild version or standalone installer, the install it on you system, and use it to compile bazel source code.
