### ISSUE TITLE
Failing actions lead to java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3549]
### Description of the problem / feature request / question:

I upgraded several machines to 0.5.3 and on every one of them I now get (with admittedly big build graphs):

```
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:261)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
	at java.util.ArrayList.addAll(ArrayList.java:579)
	at com.google.devtools.build.skyframe.ReverseDepsUtility.addReverseDeps(ReverseDepsUtility.java:155)
	at com.google.devtools.build.skyframe.InMemoryNodeEntry.addReverseDepAndCheckIfDone(InMemoryNodeEntry.java:302)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.enqueueChild(ParallelEvaluator.java:208)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:579)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Java heap space

ERROR: bazel ran out of memory and crashed.
```
What worries me is that it even runs out of heap when I only built a fraction of the build graph.

### Environment info
* Operating System: Ubuntu 16.04.2
* Bazel version (output of `bazel info release`): 0.5.3

### Anything else, information or logs or outputs that would be helpful?

Sizes are (`java -XX:+PrintFlagsFinal -version | grep HeapSize`):

```
    uintx ErgoHeapSizeLimit                         = 0                                   {product}
    uintx HeapSizePerGCThread                       = 87241520                            {product}
    uintx InitialHeapSize                          := 2113929216                          {product}
    uintx LargePageHeapSizeThreshold                = 134217728                           {product}
    uintx MaxHeapSize                              := 32210157568                         {product}
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

Seems like all machines are capping MaxHeapSize at 32G.

~~I have a 12G hprof if anyone is interested...~~

**Comment by abergmeier-dsfishlabs** [comment]
Just curious - are you tracking the memory usage version to version?

**Comment by janakdr** [comment]
If the hprof is actually available, that would be great. Otherwise, are there any other details you can give about your build? We do track memory usage internally and haven't seen any big increases recently.

**Comment by abergmeier-dsfishlabs** [comment]
> If the hprof is actually available, that would be great.

I have one but am not sure whether it is directly related. I will try to generate a current one.

> Otherwise, are there any other details you can give about your build?

By now I tried running it with `MaxHeapSize` of 50G and it still reports out of memory. The one actual change we did in switching to 0.5.3 is using a hermetic `py_runtime` instead of the system Python.

**Comment by janakdr** [comment]
It's hard for me to see an internal change to Bazel causing a multi-gig regression in memory like this. Ideally, heap dumps from both 0.5.2 and 0.5.3 would be great, so they could be diffed. Command lines would also be useful.

**Comment by abergmeier-dsfishlabs** [comment]
What I find weird is that it usually does *not* die in Analysis or Loading but when actually executing Actions.

I may need a little hand with Java. How do I get a hprof? I tried adding

    startup --host_jvm_args=-XX:-HeapDumpOnOutOfMemoryError

to `.bazelrc` but that did nothing when dying.

**Comment by janakdr** [comment]
Bazel should dump an hprof automatically. It should be in the output base.
But host_jvm_args=-XX:+HeapDumpOnOutOfMemoryError would be the right
argument (note the +). Bazel uses its maximum memory during execution, so
that's expected.

On Aug 15, 2017 8:27 AM, "Andreas Bergmeier" <notifications@github.com>
wrote:

What I find weird is that it usually does *not* die in Analysis or Loading
but when actually executing Actions.

I may need a little hand with Java. How do I get a hprof? I tried adding

startup --host_jvm_args=-XX:-HeapDumpOnOutOfMemoryError

to .bazelrc but that did nothing when dying.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/bazelbuild/bazel/issues/3549#issuecomment-322452800>,
or mute the thread

**Comment by abergmeier-dsfishlabs** [comment]
> But host_jvm_args=-XX:+HeapDumpOnOutOfMemoryError would be the right
argument (note the +)

Thanks, good catch. How can I get these > 10GB of dump to you?

**Comment by janakdr** [comment]
Retrieving now. Is the 0.5.2 dump taken at the end of the build?

**Comment by janakdr** [comment]
Also, is there any chance of getting a successful 0.5.3 build, so that the heap dump can be taken at the end, similar to the 0.5.2 heap dump? Would make for a better apples-to-apples comparison.

**Comment by abergmeier-dsfishlabs** [comment]
> Is the 0.5.2 dump taken at the end of the build?

Nope. But probably at a different stage than whatever 0.5.3 was doing.

> Also, is there any chance of getting a successful 0.5.3 build

So far I can only successfully build with 0.5.3 with non-problematic build graphs. I will try to narrow it down a bit today, though.

Another problem is that 0.5.3 does barely report the current action anymore.
In general very curious how you analyze the problem (as someone who took a quick look with Eclipse Memory Analyzer but has not been in Java land for more than a decade).

**Comment by abergmeier-dsfishlabs** [comment]
Reduced a reproduction now to a smaller target. What is particular is that this one heavily uses aspects and takes way longer than it used to on 0.5.2. Uploaded another dump.

**Comment by abergmeier-dsfishlabs** [comment]
So I think I found the problem behavior. It is related to #3568. Due to this bug, every dependency (> 400 000) of the target is failing.
My theory why this leads to VM memory running full is:
Bazel seems to produce all dependencies in parallel. Since these fail (all use `py_runtime`) it keeps some data of the failed action(s) alive (probably for error reporting). For some reason on certain code paths Bazel is not aborting say, after the first N errors but waits until all errors were produced (even without `--keep_going` switch). This eventually then leads to the VM not having any memory left.

So it is not really related to 0.5.3 and could somehow probably also be reproduced with 0.5.2.
When I work around #3568, 0.5.3 seems to work fine.

**Comment by janakdr** [comment]
Thanks for the diagnosis! Would you mind sharing your command line? It's
unexpected that Bazel wouldn't shut down after the first error. It's also
unexpected that error reporting would use so much memory.

**Comment by abergmeier-dsfishlabs** [comment]
> Would you mind sharing your command line?

    bazel build --verbose_failures //my_target --experimental_repository_cache /foo --python_path /python/bin/python3.6 --watchfs

`.bazelrc` is:

```
build --experimental_sandbox_base=/run/shm
test --experimental_sandbox_base=/run/shm
run --experimental_sandbox_base=/run/shm

build --cxxopt=-Werror=sequence-point
build --host_cxxopt=-Werror=sequence-point
```

`tools/bazel.rc` is:

```
build --cxxopt=-std=c++14
build --host_cxxopt=-std=c++14

build --strategy=ExtractResourceReferences=worker
```

> It's
unexpected that Bazel wouldn't shut down after the first error

Not at all. Happens all the time when Loading/Analysis (quite annoying). Though more rarely after that.

> It's also
unexpected that error reporting would use so much memory.

Well its at least half a mil of file references (Hash entries!?). So these may sum up.

**Comment by janakdr** [comment]
It's
unexpected that Bazel wouldn't shut down after the first error

Not at all. Happens all the time when Loading/Analysis (quite annoying).
Though more rarely after that.

Perhaps I should have said, unexpected to me. There may be some delay as
the error propagates, but the build should shut down as soon as possible.
How long are the delays you're seeing?

If you can share a toy repro for the increased memory usage with errors,
that would be great.

**Comment by meisterT** [comment]
If this is still worth investigating, please reopen.
