### ISSUE TITLE
Better documentation of "alongside" bazelrc location

### ISSUE THREAD

**Issue by philandstuff** [bazelbuild/bazel#355]
I'm trying to package bazel for nixpkgs (see nixos/nixpkgs#9008 if you're interested).  One issue I'm encountering is how set up a base_workspace and make it available for all users.

As described [on the blog](http://bazel.io/blog/2015/04/06/Simplified-Workspace-Creation.html), the compile.sh script will create a .bazelrc in $HOME to link to the base_workspace it provides.  I want to do something similar, but the package should work even when deployed to another machine so `$HOME/.bazelrc` won't work for me.  This feels like a use-case for a master bazelrc, of which there are [three possibilities](http://bazel.io/docs/bazel-user-manual.html#bazelrc): "next to the binary, in the workspace at tools/bazel.rc or system-wide at /etc/bazel.bazelrc".  For my purposes, the "next to the binary" option seems the best fit, to keep it with the other packaged files in the nix store.

However, the documentation leaves out some information about how to do this.  What should the file be called?  `.bazelrc`, `bazel.bazelrc`, or `bazel.rc`, which are all options used elsewhere?  And which directory should it be in?  To me, "next to the binary" might mean any of these:
- `/path/to/bazel-pkg/bin` - literally the same directory as the `bazel` binary, unusually for a config file
- `/path/to/bazel-pkg` - in the bazel package, though not in the `bin` directory as config doesn't normally go in there
- `/path/to/bazel-pkg/etc` - in the bazel package, in the directory where config files normally go

(I'm sure I'm doing something wrong because I couldn't get any of these options to work.)

If the documentation gave a specific example, saying where the bazel binary is and where the "alongside" rc file is in relation to it, that would answer all of my questions.

**Comment by damienmg** [comment]
FYI it's /path/to/bazel/binary.bazelrc
So if bazel binary is at /usr/local/bin/bazel then the bazel rc file will be /usr/local/bin/bazel.bazelrc

**Comment by philandstuff** [comment]
>FYI it's /path/to/bazel/binary.bazelrc
>So if bazel binary is at /usr/local/bin/bazel then the bazel rc file will be /usr/local/bin/bazel.bazelrc

Thanks! :)

**Comment by davidstanke** [comment]
Assigning to @michelleirvine -- input on the .bazelrc documentation need.

**Comment by meisterT** [comment]
I think this is fixed: https://docs.bazel.build/versions/master/guide.html#bazelrc
