### ISSUE TITLE
Nondeterministic behavior with glob

### ISSUE THREAD

**Issue by chaoren** [bazelbuild/bazel#3553]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

1. Include a nested workspace as a `local_repository`.
2. `glob` files within the nested workspace.
3. The glob will sometimes be empty under identical circumstances and sometimes not.

### If possible, provide a minimal example to reproduce the problem:
```
$ find
.
./WORKSPACE
./BUILD
./nested
./nested/foo.txt
./nested/WORKSPACE
./nested/BUILD
$ cat nested/*
$ cat WORKSPACE
local_repository(
    name = "nested",
    path = "nested",
)
$ cat BUILD
filegroup(
    name = "foo",
    srcs = ["nested/foo.txt"],
)

filegroup(
    name = "glob",
    srcs = glob(["nested/foo.txt"]),
)
```
```
$ bazel query :all --output=build
```
will sometimes produce:
```
# /path/to/BUILD:6:1
filegroup(
  name = "glob",
  srcs = [],
)

# /path/to/BUILD:1:1
filegroup(
  name = "foo",
  srcs = ["//:nested/foo.txt"],
)
```
and sometimes:
```
# /path/to/BUILD:6:1
filegroup(
  name = "glob",
  srcs = ["//:nested/foo.txt"],
)

# /path/to/BUILD:1:1
filegroup(
  name = "foo",
  srcs = ["//:nested/foo.txt"],
)
```
with no discernable difference in environment.
Though one result will persist for some time.

### Environment info
* Operating System: Ubuntu 14.04.5 LTS

* Bazel version (output of `bazel info release`): release 0.5.3

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by chaoren** [comment]
The difference in behavior seems to be based on timestamp on the BUILD file. If I `touch` the `./BUILD` I always get the nonempty glob afterwards. But after some combination of building, cleaning, and touching files, I'll get the empty glob again.

**Comment by chaoren** [comment]
Okay, I can reliably reproduce this now:
```
$ touch ./BUILD
$ bazel query :all --output=build
# /path/to/BUILD:6:1
filegroup(
  name = "glob",
  srcs = ["//:nested/foo.txt"],
)

# /path/to/BUILD:1:1
filegroup(
  name = "foo",
  srcs = ["//:nested/foo.txt"],
)

$ bazel clean
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
$ bazel query :all --output=build
# /path/to/BUILD:6:1
filegroup(
  name = "glob",
  srcs = [],
)

# /path/to/BUILD:1:1
filegroup(
  name = "foo",
  srcs = ["//:nested/foo.txt"],
)

$ touch ./BUILD
$ bazel query :all --output=build
# /path/to/BUILD:6:1
filegroup(
  name = "glob",
  srcs = ["//:nested/foo.txt"],
)

# /path/to/BUILD:1:1
filegroup(
  name = "foo",
  srcs = ["//:nested/foo.txt"],
)
```
It seems `./nested/BUILD` is required for this to happen.

**Comment by damienmg** [comment]
To be precise the globs should ALWAYS be empty

So I used that script:

```
$ cat create_ws.sh 
#!/bin/bash

echo "local_repository(name='nested',path='nested')" > WORKSPACE
cat > BUILD <<'EOF'
filegroup(name='foo', srcs=['nested/foo.txt'])
filegroup(name='glob', srcs=glob(['nested/foo.txt']))
EOF
mkdir nested
touch nested/foo.txt
```

And run the following line several time always got the issue:
`touch ./BUILD; bazel query :all --output=build; bazel clean; bazel query :all --output=build; bazel query :all --output=build`

Even after creating a nested/workspace
I highly suspect a problem with evaluation of nested workspace. Reassigning to @katre.

**Comment by katre** [comment]
Once nested is a local repository, the filegroup in the main repository shouldn't be able to reach into it. I'll investigate and see where the error is.

**Comment by katre** [comment]
To be more clear, even without the glob, the filegroup that reaches into the local repository should give an error like this:
```
BUILD:15:18: Label '//:nested/foo.txt' crosses boundary of subpackage 'nested' (perhaps you meant to put the colon here: '//nested:foo.txt'?)
ERROR: error loading package '': Package '' contains errors
```

Although possibly it should say "local repository" instead of "subpackage".
