### ISSUE TITLE
--incompatible_load_argument_is_label fails on external labels starting with "@"

### ISSUE THREAD

**Issue by kevingessner** [bazelbuild/bazel#3560]
### Description of the problem:

The --incompatible_load_argument_is_label disallows load statements like `load('foo.bzl', 'foo')` and `load('/path/to/foo.bzl', 'foo')`, in favor of labels like `load('//path/to:foo.bzl', 'foo')`.  That check inadvertently disallows external labels like `load('@other//foo.bzl', 'foo')`.

### Repro

1. In a new directory, `touch WORKSPACE`
2. Run `bazel build --incompatible_load_argument_is_label`.

Expected: success

Actual: an error, `ERROR: /home/kgessner/.cache/bazel/_bazel_kgessner/07d908670fc42f8a290a374abf92bb5e/external/bazel_tools/tools/cpp/unix_cc_configure.bzl:18:1: First argument of 'load' must be a label and start with either '//' or ':'. Use --incompatible_load_argument_is_label=false to temporarily disable this check.`

That is, it fails with an empty WORKSPACE because bazel's internal imports fail this validation. 

### Environment info

* Bazel version (output of `bazel info release`): release 0.5.3

**Comment by kevingessner** [comment]
I have a fix for this incoming shortly.

**Comment by abergmeier-dsfishlabs** [comment]
@dslomov Is this a bug or feature? Have you guys decided whether you want to support @ loading with proper aliasing (`@//` == `@<workspace_name>//`)?
