### ISSUE TITLE
"Socket closed" I/O Error when using remote REST cache

### ISSUE THREAD

**Issue by jonwallg** [bazelbuild/bazel#3561]
When I try to build using remote REST cache, my build fails with the error message:
"&lt;target&gt; failed: I/O Error in remote cache/executor: Socket closed."

This appears to happen when executing a large number of actions in a short amount of time. I cannot reproduce when trying to build bazel itself using remote REST cache, but I can see from the http logs that it is executing actions at a slower rate than my project.

### Steps to reproduce:

1. Setup bazel to use [remote caching](https://github.com/bazelbuild/bazel/tree/master/src/main/java/com/google/devtools/build/lib/remote) via HTTP REST. I'm using an nginx server running on the same machine.
2. Apply this patch: https://github.com/jonwallg/bazel/commit/033fcb68e697316becdae7bf67282c2dca9e63e1
3. build:
`$ bazel build //src/test/java/com/google/devtools/build/lib:remote_cache_socket_failure`

### Environment info
* Operating System:
macOS Sierra 10.12.6

* Bazel version (output of `bazel info release`):
release 0.5.3

**Comment by buchgr** [comment]
this has been fixed in the meantime.

**Comment by liujiwei777** [comment]
root@52751d2608d1:/apollo# ./apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you nee                                                                                        d ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_schedul                                                                                        ing
[INFO] Building on aarch64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_schedul                                                                                        ing
INFO: Found 1637 targets...
ERROR: /root/.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32/external/                                                                                        com_google_protobuf/BUILD:113:1: C++ compilation of rule '@com_google_protobuf//                                                                                        :protobuf' failed: I/O Error in remote cache/executor: io.grpc.StatusRuntimeExce                                                                                        ption: INTERNAL.
INFO: Elapsed time: 11.637s, Critical Path: 3.14s
============================
[ERROR] Build failed!
[INFO] Took 13 seconds
============================
