### ISSUE TITLE
Update local_repository docs to reflect support for relative paths

### ISSUE THREAD

**Issue by davidstanke** [bazelbuild/bazel#3563]
See: https://groups.google.com/forum/#!topic/bazel-discuss/Pgv9soFhPv8

... local_repository supports absolute or relative paths, but [its documentation](http://docs.bazel.build/versions/master/be/workspace.html#local_repository) says only absolute paths are supported.

The same may be true of [new_local_repository](http://docs.bazel.build/versions/master/be/workspace.html#new_local_repository) -- @kchodorow to confirm.

Thanks!

**Comment by kchodorow** [comment]
Confirmed, relative paths also work for `new_local_repository`.

**Comment by keertk** [comment]
Hi there! This is [fixed](https://bazel.build/reference/be/workspace#local_repository) and mentions both absolute and relative paths.
Closing.
