### ISSUE TITLE
Options/flags should be documented only by doc generated from code.

### ISSUE THREAD

**Issue by michelleirvine** [bazelbuild/bazel#3564]
Currently, flags are documented twice. They should only be documented once, and should not be documented manually. 

Current examples:

(1) Manual doc (will go out of date):
https://github.com/bazelbuild/bazel/blob/master/site/docs/bazel-user-manual.html
https://docs.bazel.build/versions/master/bazel-user-manual.html

(2) By doc generated from the code (will be as accurate as the code): 
https://docs.bazel.build/versions/master/command-line-reference.html

related to #2898
related to ##3502

**Comment by keertk** [comment]
Hi there! This doesn't appear to be a problem anymore -- closing this issue.
