### ISSUE TITLE
py_binary not executed sandboxless

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3569]
### Description of the problem / feature request / question:

When specifying:

    py_binary(
        ...
        tags = ["local"],
    )

the binary still gets executed in a sandbox e.g. `/dev/shm/bazel-sandbox.6db27142db1a9dda6ab345b217b92239/1101892232480956201`

### Environment info
* Operating System: Ubuntu 16.04.2
* Bazel version (output of `bazel info release`): 0.5.3

**Comment by iirina** [comment]
@philwo @lberki can you take a look?

**Comment by philwo** [comment]
Trying to repro this now.

**Comment by philwo** [comment]
Actually, this is working as intended: The "local" tag always concerns the rule itself, not when its output is used as a tool later when building a different action.

With the provided example, the actions that build the py_binary will run without a sandbox (which is probably not what you wanted). If you later use the py_binary in e.g. a genrule to do something, that genrule will run in a sandbox, unless you also put "tags = ["local"]" there.
