### ISSUE TITLE
bootstrap.sh other distro scripts..

### ISSUE THREAD

**Issue by necrose99** [bazelbuild/bazel#3572]
debian i have at the moment on board , 

need to fix my gentoo rpi-3 build...  and or get a Ban-64-pi...  

anycase I grabbed the source... ,  overlay-ed distribution into from zip 

fired up ./compile.sh
it growned.. 
I figured a bootstrap script to just git-clone & pull a bin-dist ie zip... for any linux 
./bootstrapme.sh  (get files needed)  install bazel for other arches.. 

debian-build.sh also a nice touch if not using x86/x64  ie arm or arm64 etc.... 
at the moment I'm using ARM64...  on IOT ,   when I can i'll snag a amr server...

**Comment by iirina** [comment]
Hi,

I did not understand what your issue is. What steps have you taken and which failed?

Thanks

**Comment by necrose99** [comment]
just saying source build is kinda a pain in the @......  
./compile....  groans about bootstrapping , thus requiring to yank a prior compiled ... in... 
--- might have a script to do this for alt platforms go yank deps... etc.. (just a bit more user friendly)

i was building a few things for Debian currently no debs , so I have to use src. 
it builds eventually RPI3 @ 64bit arm ist the fastest..  
and 2ndly a deb packer script to build bazel-$VERSION-$MYARCH.deb   , for those on ALT platforms.. 
in mycase been tinkering in arm64. or arm... 
some go code with bazel ... would be good to have built... 

if thier were an Ebuild once for other RPI3/BPI-64 , I'd care not as Gentoo dose this rather well.

**Comment by mhlopko** [comment]
cc @aehlig 

(I'm not a native speaker, sorry if I don't understand your message correctly)

Can you share the exact error that you encountered when running ./compile? It seems to me that you correctly used the distribution archive, so that's not the problem.

We don't have a debian package yet (mainly because we package many third party dependencies into bazel, and that goes against the debian rules). But last time I checked we still plan to have a debian package by bazel 1.0. Of course one can create a .deb package that will work on debian, but it won't be accepted into debian repos. If you want to make it anyway, check https://github.com/bazelbuild/bazel/tree/master/scripts/packages/debian that's what we use for making our debs for ubuntu.

**Comment by laszlocsomor** [comment]
IIUC the issue is that bootstrapping Bazel on alternative platforms than Linux, MacOS, Windows/MSYS -- particularly on ARM/ARM64 -- is a pain in the ass, and it'd be nice if it weren't :)

@necrose99 : I second what @mhlopko asked, can you please provide additional info: which versikon of Bazel's distribution archive you downloaded, what was ./compile.sh's output? Did you try fixing it and if so, how far did you get, what modifications did you do and what was the output of the script?

**Comment by laszlocsomor** [comment]
Please note that we currently can't bootstrap on 32-bit platforms; we just run out of memory while compiling  java code, because Bazel's bootstrapper script isn't exactly smart, it just compiles all .java files in one `javac` call and that eats memory for breakfast.

**Comment by laszlocsomor** [comment]
@necrose99 : Did you first `git clone` Bazel's source then unzip the distribution archive on top of that? Right, that doesn't work (@aehlig knows the details better than I do). The right way is to unzip the dist archive to a separate directory and run `./compile.sh` there. You can't bootstrap in the git cloned tree; you need an existing Bazel binary to build Bazel there.

Anyway, @aehlig tells me you *can* bootstrap on 32-bit but you'll need lots of RAM (I guess 3 GB should be enough). I agree a smarter bootstrapper would be nicer but I don't think it's a priority right now.

**Comment by aehlig** [comment]
> if thier were an Ebuild once for other RPI3/BPI-64 , I'd care not as Gentoo dose this rather well. 

FYI, there is an ebuild for bazel, https://packages.gentoo.org/packages/dev-util/bazel
But not using gentoo myself, I don't know how well it works.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment]
> @necrose99 : Did you first `git clone` Bazel's source then unzip the distribution
> archive on top of that? Right, that doesn't work (@aehlig knows the details better than I do).

The long story can be found at https://www.bazel.build/designs/2016/10/11/distribution-artifact.html

In short, we have a cyclic dependency there: bazel needs protoc, and
protoc is built using bazel (and, to make things worse, we cannot use
the latest released protoc). To break this dependency, the distribution
archive also contains the (architecture-independent!) output of protoc,
so you compile a bootstrap version of bazel and use it, to build
everything from source. For this to work, of course the output of protoc
(generated files, after all) must fit to the remaining sources (e.g.,
if we change a proto definition, the remaining classes expect the new
fields to be present in the generated classes). So, to bootstrap you
need to download a distribution archive (there is nothing unual with
that approach, it's basically what is `make distfile` in the autotools
world).

Once you have a working bazel on any architecture, you can `git checkout`
whatever version you need and `bazel build //:bazel-distfile` a
distribution archive for that version which then, beeing architecture
independent, can be used on whatever architecture you want. If you
already have a working bazel for the correct architecure, you can `git
checkout` your favourite commit and `bazel build //src:bazel` there.

> Anyway, @aehlig tells me you *can* bootstrap on 32-bit but you'll need lots
> of RAM (I guess 3 GB should be enough).

You will indeed need lots of memory. You will also need an extra patch
for 32-bit systems, https://svnweb.freebsd.org/ports/head/devel/bazel/files/extra-i386_src_BUILD?view=markup
(the nanosleep part is already upstream as
https://github.com/bazelbuild/bazel/commit/91a4d98ec7ed723fdbfd6f35b85bedafee907884
but didn't make it into the current release).

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by necrose99** [comment]
noted for the moment , I was using debian  for arm64 , could use to get another pi3 ... or a better dev board..  need a new file server as is .. 
a few things are ahead on debian for rust etc.. so for Distcc etc.. will do as a slave. 

tried swapping to systemd on [gentoo pi3](https://github.com/sakaki-/gentoo-on-rpi3-64bit) ...   broke the boot..  matter of scrapping the fs... taring from Gentoo/Sabayon VM or HDD.... however I've set a mini Chroot on deb-arm64 pi3 should be enough to run the catalyst build toy ... repack gentoo stage3 for systemd... 
 dev-util/bazel/bazel-0.5.2.ebuild isnt keyed for arm64 but I'll try n force it anyhow..  give it a go..  while on vacation over dataplicity-ssh 

my point was could get a script to make the  **build process from scratch a touch simpler**..  @ more novice's 
./bootstrap-me.sh  (./compile) and w'get the bootstrap-pkg  or unpack it for jars etc.. 
but its not a critical feature but a @future feature request for less building nags.. 

also a rpm/deb pack scripts etc would again be a nice touch if you need a custom compile.  and care to distribute..

**Comment by laszlocsomor** [comment]
Thanks for the details.

@necrose99, as I understand the situation, what you're really looking for is not a simpler bootstrapping process (I think it's simple enough on the platforms we support: 64-bit Ubuntu / Mac OS / Windows), but an easier way to port the bootstrapper.

I agree that would be nice to have and I think this feature request in general is reasonable, however I also think that for now this is a low priority request, so I'm marking it P4.

**Comment by vielmetti** [comment]
It's been a few months since this issue was opened and commented on, and I find myself here planning to get `bazel` built for arm64 so that I can build `envoy`.

**Comment by meisterT** [comment]
We don't plan any work on this right now.
