### ISSUE TITLE
Add support for generating mapfiles

### ISSUE THREAD

**Issue by charlesnicholson** [bazelbuild/bazel#3576]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

According to this mailing list thread:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bazel-discuss/A00d7Ui1f8s/FhD2jfucCAAJ

There doesn't appear to be a way to command Bazel to emit mapfiles. These are really important when using Bazel as a cross-compiler for embedded systems work.

### If possible, provide a minimal example to reproduce the problem:

The first email in the thread linked above describes my attempts (adding flags via cc_binary and via CROSSTOOL).

### Environment info
* Operating System:

Linux x64, Win10

* Bazel version (output of `bazel info release`):

C:\Users\nicholsonc\dev\src\bazel-test> .\bazel.exe info release
.
release 0.5.3

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
