### ISSUE TITLE
Compile from source docs don't list bazel's dependencies.

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/bazel#3578]
https://docs.bazel.build/versions/master/install-compile-source.html should enumerate all the dependencies bazel has. Good source of that information are our dockerfiles.

**Comment by aehlig** [comment]
> https://docs.bazel.build/versions/master/install-compile-source.html should
> enumerate all the dependencies bazel has. Good source of that information are
> our dockerfiles.

...or the port (updated to the latest release candidate), after verifying the
build in an insolated environment.

```
[root@freebsd-12-slave-staging /usr/local/poudriere/ports/default/devel/bazel]# make -V BUILD_DEPENDS
bash:shells/bash  zip:archivers/zip /usr/local/openjdk8/bin/java:java/openjdk8 /usr/local/bin/python2.7:lang/python27
[root@freebsd-12-slave-staging /usr/local/poudriere/ports/default/devel/bazel]# 
```

Note that "all dependencies" is not such a clear notion as it sounds,
as every system has its own idea of what is "always there". Will update
the documentation nevertheless.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by mhlopko** [comment]
Yeah I understand. Thanks for working on it!
