### ISSUE TITLE
--package_path ignored when in repository_rule in 0.5.3

### ISSUE THREAD

**Issue by htuch** [bazelbuild/bazel#3580]
The Envoy project hit an issue where, when executing from a workspace directory and using `--package_path`, one of our `repository_rule`s started to fail in 0.5.3. Specifically (somewhat simplified):

1. We have our source root at `/source`. We have some file `/source/foo/bar.bzl`.
2. We have a `WORKSPACE` in `/source/ci/WORKSPACE`.
3. We run `bazel build --package_path %workspace%:/source //...`.
4. In the `WORKSPACE`, we refer to a macro that sets up `@bar_bzl` via a `repository_rule`. This includes the line `ctxt.symlink(Label("//foo:bar.bzl"), "bar.bzl")`. 

With 0.5.2, this seemed to work fine, but in 0.5.3, we get an error like:
```
no such package '@bar_bzl//': Unable to load package for //foo:bar.bzl: not found.
```

This issue doesn't show up when building from `/source` with a `WORKSPACE` there, it only occurs when using `--package_path`.

One workaround is to map `/source` into the `WORKSPACE` as a `local_repository`, but it doesn't seem great.

**Comment by iirina** [comment]
@cvcal can you take a look? I saw you did some changes to `PackageCacheOptions`.

**Comment by cvcal** [comment]
My recent changes to `PackageCacheOptions`were changes that went through to all options, so unfortunately it doesn't mean I know much about this. 
I think @dslomov might know who to pass this to.

**Comment by dslomov** [comment]
sorry, I do not completely understand this report. Can I have a small repro?
you have a `WORKSPACE` in `/source/ci`, and another `WORKSPACE` in `/source`:
```
/source
   WORKSPACE
   /foo
      bar.bzl
  /ci
     WORKSPACE     
```

You run `bazel build --package_path %workspace%:/source //....` in `/source/ci`.
This should give you package `//foo` and `//foo:bar.bzl`.

So far so good. What I do not understand is this bit
> In the WORKSPACE, we refer to a macro that sets up @bar_bzl via a repository_rule. This includes the line `ctxt.symlink(Label("//foo:bar.bzl"), "bar.bzl")`.

what are you trying to achieve? What is the complete definition of `@bar_bzl` repository?

**Comment by htuch** [comment]
TBH, I've lost context on this one. We have a TODO for this workaround in https://github.com/envoyproxy/envoy/blob/c66c113776f8251a0b66d5dd32e671ba62b05624/ci/WORKSPACE#L6. We're transitioning ownership of Envoy's Bazel to @jmillikin-stripe, so I'll leave it for him to triage as appropriate.
