### ISSUE TITLE
bazel test and bazel build clears each other's targets

### ISSUE THREAD

**Issue by startcode** [bazelbuild/bazel#3581]
I found that whenver I run
```
bazel test ...
```
All the targets I built by command
```
bazel build ...
```
will be removed.
Is there any way to reserve the files generated by `bazel build ...` when testing? 
Thanks

**Comment by iirina** [comment]
Do you mean that all the targets that were built with `bazel build` before and were not used by `bazel test` are removed? What are you trying to accomplish?

**Comment by iirina** [comment]
Can you also provide an example easy to reproduce or describe the targets that you're trying to build/test? What you previously built shouldn't be removed, how did you notice they were?

**Comment by startcode** [comment]
Here is a live example: https://github.com/ApolloAuto/apollo/blob/master/apollo.sh
If you run ```bash apollo.sh test```, all targets generated by ```bash apollo.sh build``` will be cleared.

**Comment by iirina** [comment]
Oh I see. There are some options that affect the startup of the bazel server (search for them [here](https://docs.bazel.build/versions/master/command-line-reference.html)). Among those I can identify `--batch` and` --batch_cpu_scheduling` in your `build` command line. When you run `bazel test` with different startup options than the previous bazel command, the server will restart with a clean state, therefore removing the previous built targets. I recommend you use the same startup options.

**Comment by startcode** [comment]
Problem solved. Thanks.
