### ISSUE TITLE
Bazel fails to build on Debian Wheezy

### ISSUE THREAD

**Issue by cflewis** [bazelbuild/bazel#359]
When running inside of a Docker container which is based on Debian Wheezy (which is used for Managed VMs images), Bazel can't build:

```
INFO     2015-08-04 05:34:46,408 containers.py:282] /usr/bin/ld: bazel-out/local_linux-fastbuild/bin/src/main/native/_objs/libunix.so/src/main/native/unix_jni.pic.o: relocation R_X86_64_PC32 against symbol `_Z13PostExceptionP7JNIEnv_iRKSs' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status

INFO     2015-08-04 05:34:46,408 containers.py:282] ERROR: /home/vmagent/appengine-java-vmruntime/webapps/root/bazel/src/main/native/BUILD:26:1: Linking of rule '//src/main/native:libunix.so' failed: gcc failed: error executing command /usr/bin/gcc -shared -o bazel-out/local_linux-fastbuild/bin/src/main/native/libunix.so -Wl,-whole-archive ... (remaining 14 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
```

**Comment by damienmg** [comment]
Ulf: do you know what's happening here?

**Comment by cflewis** [comment]
Note that I rolled back to ecd4ec41e5b2d2520bcab1e00a4acc982f18d64b , which is the last known good Linux build on Travis, which does build.

**Comment by bsilver8192** [comment]
This looks like the same issue discussed at <https://groups.google.com/forum/#!msg/bazel-discuss/f8oHMtKzZfE/SYKSJvwWX-cJ>. <https://bazel-review.googlesource.com/#/c/1690/> is one fix and deleting -fPIE from tools/cpp/CROSSTOOL is another.

**Comment by PeterBeukelman** [comment]
I have deleted that option, but I still have the problem. (I changed option to -fPIC after the error log urged me)

>(tensorflow)peter@peter-linux:~/tensorflow/tensorflow$  sudo bazel build -c opt --config=cuda //google/protobuf:protoc --verbose_failures
INFO: Found 1 target...
INFO: From Linking google/protobuf/protoc:
/usr/bin/ld: bazel-out/local_linux-opt/bin/google/protobuf/libprotoc_lib.a(command_line_interface.o): undefined reference to symbol 'ceil@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ERROR: /home/peter/tensorflow/tensorflow/google/protobuf/BUILD:270:1: Linking of rule '//google/protobuf:protoc' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/afabb577f502c71974321e5c9c6e13dc/tensorflow && \
  exec env - \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -o bazel-out/local_linux-opt/bin/google/protobuf/protoc bazel-out/local_linux-opt/bin/google/protobuf/_objs/protoc/google/protobuf/src/google/protobuf/compiler/main.o bazel-out/local_linux-opt/bin/google/protobuf/libprotoc_lib.a bazel-out/local_linux-opt/bin/google/protobuf/libprotobuf.a bazel-out/local_linux-opt/bin/google/protobuf/libprotobuf_lite.a -lpthread -lstdc++ -B/usr/bin/ -pie -Wl,-z,relro,-z,now -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,--gc-sections): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/afabb577f502c71974321e5c9c6e13dc/tensorflow && \
  exec env - \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -o bazel-out/local_linux-opt/bin/google/protobuf/protoc bazel-out/local_linux-opt/bin/google/protobuf/_objs/protoc/google/protobuf/src/google/protobuf/compiler/main.o bazel-out/local_linux-opt/bin/google/protobuf/libprotoc_lib.a bazel-out/local_linux-opt/bin/google/protobuf/libprotobuf.a bazel-out/local_linux-opt/bin/google/protobuf/libprotobuf_lite.a -lpthread -lstdc++ -B/usr/bin/ -pie -Wl,-z,relro,-z,now -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,--gc-sections): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //google/protobuf:protoc failed to build
INFO: Elapsed time: 43.005s, Critical Path: 41.38s
>
>
> (tensorflow)peter@peter-linux:~/tensorflow/tensorflow$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
INFO: Found 1 target...
INFO: From Linking google/protobuf/protoc [for host]:
/usr/bin/ld: bazel-out/host/bin/google/protobuf/libprotoc_lib.a(command_line_interface.o): undefined reference to symbol 'ceil@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ERROR: /home/peter/tensorflow/tensorflow/google/protobuf/BUILD:270:1: Linking of rule '//google/protobuf:protoc' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -o bazel-out/host/bin/google/protobuf/protoc ... (remaining 15 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.789s, Critical Path: 0.12s

**Comment by bsilver8192** [comment]
This bug was fixed by 4e7ed50345f3a3037549f7c41f852b5d9db4a08d.

@PeterBeukelman: That's a different problem. I think you should open another bug with the output from running the build with `--verbose_failures`.

**Comment by XingxingZhang** [comment]
@bsilver8192 

<< This looks like the same issue discussed at https://groups.google.com/forum/#!msg/bazel-discuss/f8oHMtKzZfE/SYKSJvwWX-cJ. https://bazel-review.googlesource.com/#/c/1690/ is one fix and deleting -fPIE from tools/cpp/CROSSTOOL is another.

Where is -fPIE? I didn't find it in tools/cpp/CROSSTOOL

**Comment by bsilver8192** [comment]
> Where is -fPIE? I didn't find it in tools/cpp/CROSSTOOL

It's not there any more. 4e7ed50345f3a3037549f7c41f852b5d9db4a08d removed it completely.

**Comment by XingxingZhang** [comment]
@bsilver8192  thanks
