### ISSUE TITLE
"The handle is invalid" errors on Windows

### ISSUE THREAD

**Issue by grandseiken** [bazelbuild/bazel#3594]
### Description of the problem / feature request / question:

We are in the process of porting our CMake-based build to Bazel. With Bazel 0.5.3, almost all Windows-specific issues we've seen before seem to have been resolved (thank you so much!).

We still have one occasional flake with the Bazel build on Windows. Very rarely, Bazel fails with a "The handle is invalid" error. This seems to happen randomly and in a few different contexts. I've provided a couple of sample flakes below:

```
ERROR: missing input file '//cpp/external:boost-thread/boost/preprocessor/iteration/detail/iter/reverse1.hpp':The handle is invalid.
ERROR: C:/w/ee9378522cbb9fd1/cpp/external/BUILD:33:1: //cpp/external:boost_thread: missing input file '//cpp/external:boost-thread/boost/preprocessor/iteration/detail/iter/reverse1.hpp'.
```

```
[19:02:43] ERROR: C:/t/buildtmp/_bazel_system/aig5ghsl/external/protobuf/BUILD.bazel:361:1: Couldn't build file external/protobuf/_objs/protoc/external/protobuf/src/google/protobuf/compiler/main.o: C++ compilation of rule '@protobuf//:protoc' failed (Exit -1). Note: Remote connection/protocol failed with: execution failed: cl.exe failed: error executing command 
     SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\\shared;C:\Program Files (x86)\Windows Kits\8.1\include\\um;C:\Program Files (x86)\Windows Kits\8.1\include\\winrt;
     SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64;
     SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\8.1\bin\x64;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\Python27;C:\Python27\Scripts;C:\ProgramData\chocolatey\bin;C:\tools\msys64\usr\bin;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\Google\Compute Engine\sysprep;C:\Program Files\Google\Compute Engine\metadata_scripts;C:\improbable\it\bin;C:\Program Files\Java\jdk1.8.0_102\bin;C:\Program Files\7-Zip;C:\improbable\tools\latest\windows;C:\tools\go\bin;C:\Program Files\Unity\Editor;C:\Program Files (x86)\MSBuild\14.0\Bin;C:\Program Files (x86)\NUnit.org\nunit-console;C:\Program Files (x86)\CMake\bin;C:\Program Files (x86)\sbt\bin;C:\Program Files (x86)\sbt\bin;C:\tools\spatial;C:\tools\protoc;C:\windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\tools\python2;C:\tools\python2\Scripts;C:\Program Files\Perforce;C:\Program Files\Perforce\DVCS;C:\tools\apache-maven-3.3.9\bin;C:\Program Files\Mono\bin;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\bin;C:\Program Files\LLVM\bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\ProgramData\nvm;C:\Program Files\nodejs;C:\Program Files\nodejs;C:\ProgramData\osquery;C:\python27;C:\Program Files\Puppet Labs\Puppet\bin;C:\ProgramData\chocolatey\lib\msys2;C:\tools\msys64\;$($env;SystemDrive)\Program Files\LLVM\bin;C:\windows\system32\config\systemprofile\AppData\Roaming\npm;C:\windows\system32
     SET PWD=/proc/self/cwd
     SET TEMP=C:\t\buildTmp
     SET TMP=C:\t\buildTmp
     SET TMPDIR=C:\t\buildTmp
   C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /nologo /Iexternal/protobuf /Ibazel-out/msvc_x64-fastbuild/genfiles/external/protobuf /Iexternal/bazel_tools /Ibazel-out/msvc_x64-fastbuild/genfiles/external/bazel_tools /Iexternal/zlib_repo /Ibazel-out/msvc_x64-fastbuild/genfiles/external/zlib_repo /Iexternal/protobuf/src /Ibazel-out/msvc_x64-fastbuild/genfiles/external/protobuf/src /Iexternal/bazel_tools/tools/cpp/gcc3 /showIncludes /MT /Od /Z7 /c external/protobuf/src/google/protobuf/compiler/main.cc /Fobazel-out/msvc_x64-fastbuild/bin/external/protobuf/_objs/protoc/external/protobuf/src/google/protobuf/compiler/main.o.
 Action failed to execute: java.io.IOException: ResumeThread(): The handle is invalid.
```

This error does not occur on Linux, or when building with an equivalent CMake-based build on Windows.  We've seen it on several different machines. I appreciate that this is fairly vague, and that the root cause may well be some problem with our configuration rather than Bazel doing something wrong, but I'm hoping someone might have seen this before or have some insight on what it might be caused by.

### Environment info
* Operating System: Windows 10
* Bazel version (output of `bazel info release`): 0.5.3

###  Have you found anything relevant by searching the web?
Unfortunately this error message is fairly generic and seems to crop up a lot in various unrelated contexts, so I haven't been able to pin down any root cause.

### Anything else, information or logs or outputs that would be helpful?
Since the error happens very rarely, I haven't yet been able to reproduce it in a context in which I'd be able to get more detailed output.

**Comment by dslomov** [comment]
I saw similar error but I do not know how to reliably reproduce. Any repro or details will be appreciated!

**Comment by dslomov** [comment]
The error (invalid handle) comes from here: https://github.com/bazelbuild/bazel/blob/master/src/main/native/windows/processes-jni.cc#L327
indicating that the thread handle passed to `ResumeThread` is invalid. 
The thread handle comes from process info (https://github.com/bazelbuild/bazel/blob/master/src/main/native/windows/processes-jni.cc#L307), it is the main thread of the process that is created suspended here:
 https://github.com/bazelbuild/bazel/blob/master/src/main/native/windows/processes-jni.cc#L294.

No idea why this happens sometimes. The symptoms indicate a typical race condition: the thread has already terminated before ResumeThread executed. But in this case we very explicitly create the process suspended. Could it be that AssignProcessToJobObject resumes the process somehow?

**Comment by dslomov** [comment]
I've spent some time looking at this code an reading things, but no clue yet :(

Also, the other instance of invalid handles that you report (`ERROR: missing input file '//cpp/external:boost-thread/boost/preprocessor/iteration/detail/iter/reverse1.hpp':The handle is invalid.`) is a different bug I guess

**Comment by petemounce** [comment]
@meteorcloudy this is the issue I'm stood talking to you about :)

**Comment by sgreenstein** [comment]
I've also seen this. It happens about 5% of the time in our CI system

**Comment by laszlocsomor** [comment]
Has anyone seen this bug recently?
I believe it's obsolete. We improved process management a lot since 2017.
