### ISSUE TITLE
Tool to edit elf RUNPATH

### ISSUE THREAD

**Issue by jfroy** [bazelbuild/bazel#3595]
Bazel-built shared libraries and programs can have a complex RUNPATH synthesized by bazel. This is almost always not what should be shipped in the packaged version of the software. There should be a bundled tool and rule to set the final RUNPATH value.

This issues comes up when using the pkg_tar or pkg_deb rules to ship build artifacts.

### Environment info
* Operating System:
debian unstable

* Bazel version (output of `bazel info release`):
release 0.5.3

**Comment by ajbouh** [comment]
There's a handy tool called [PatchELF](https://nixos.org/patchelf.html) built by the NixOS team that might help here.

```
PatchELF is a small utility to modify the dynamic linker and RPATH of ELF executables.
```

**Comment by damienmg** [comment]
Since PatchELF exists I would recommend using that...

/cc @mhlopko to further evaluate this request because it is linked to deployment of C++ binaries but I think we can close this one since I doubt we want to bundle PatchELF by default (no real need for). However there might be a more general mechanism to think of about writing runpath...

**Comment by mhlopko** [comment]
Yeah controlling the RPATH for deployment is one of the main problems we want to solve by the 'Bazel for Open-Source C++ Development' effort (that is very early in the design stage and have not yet been shared with the world :) So I think we can close this issue as it doesn't add anything we're not addressing already.

**Comment by wesleyw72** [comment]
Hi @hlopko is there any update on the above since your last post. I'd like to do something very similar to the author and change the RUNPATH of a deployed binary built with Bazel

**Comment by hlopko** [comment]
Hmm it's quite depressing, but nope, no progress on this since 2017.

**Comment by hawkeyese** [comment]
I have ran into the need to change RUNPATH in a binary when rpm packaging it. Have this problem been solved or am I left to my own tinkering?
