### ISSUE TITLE
Add -v, --version flag

### ISSUE THREAD

**Issue by drigz** [bazelbuild/bazel#3599]
Working out that `bazel version` is the right command is (for me at least) quite slow. It would be better to support the more common `-v` and `--version` flags.

```
> bazel -v
Unknown startup option: '-v'.
  For more info, run 'bazel help startup_options'.
> bazel --version
Unknown startup option: '--version'.
  For more info, run 'bazel help startup_options'.
> bazel help startup_options | grep version
> bazel help | grep version
  version             Prints version information for bazel.
> bazel version
Build label: 0.5.3
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 28 08:34:59 2017 (1501230899)
Build timestamp: 1501230899
Build timestamp as int: 1501230899
```

### Environment info
* Operating System: Ubuntu 14.04
* Bazel version: 0.5.3

**Comment by werkt** [comment]
`bazel info release` suffices for this, recommend it be closed.

**Comment by jbduncan** [comment]
@werkt Sure, but it doesn't solve the problem that it's non-intuitive to people who are so used to the GNU convention of -v and --version, which in my experience is by far the most common way of allowing people to query version information in other command-line tools.

So I vote to keep this open until https://github.com/bazelbuild/bazel/pull/3671 is closed.

**Comment by ulfjack** [comment]
I added a --gnu_format flag to version in 938a53d3d54ede8132109df3c492c47afc63f5a6.

**Comment by ulfjack** [comment]
However, changing the default is tricky and will require more work.

**Comment by rathovarun** [comment]
#6857

**Comment by drigz** [comment]
`--version` works as of 371a2e343199ee799404fd2bb8319d990a2ad572, and without starting a server!  :tada:
