### ISSUE TITLE
Error: couldn't connect to server after 120 seconds. Killed non-responsive server process (xxx)

### ISSUE THREAD

**Issue by oswcab** [bazelbuild/bazel#3602]
Using bazel to build gerrit and other related projects. Just upgraded to a new laptop so I had to install bazel again; it was running fine in old machine.

Now when I try to build any project it takes a long time (several minutes) to show the dots and finally gives error message:
   Error: couldn't connect to server after 120 seconds.

If after that, if try in another project, get "Killed non-responsive server process" followed by the aforementioned timeout error.

Only difference between the old laptop and the new one (besides upgraded OS) is the presence of Pulse Secure [1], a Java application to connect to the company internal network.

Further troubleshooting showed that if I stop Pulse connection, bazel starts to work again. Given Pulse Secure is a 32-bit application, my suspicion was some kind of conflict or version mismatch. So I installed the beta 64-bit version, but unfortunately the problem is still the same.

Any idea how to further troubleshoot this? I have opened a ticket with the IT department at my company asking them also for some advice but wanted to have your impressions on this.

Thanks

[1] https://www.pulsesecure.net

### Steps to reproduce:
Start Pulse Secure and establish connection to remote network
Run bazel info release
bazel fails with "Error: couldn't connect to server after 120 seconds."
Interrupt Pulse Secure connection (no need to exit the application)
Run bazel info release
bazel gives (instantaneous) response

### Environment info
* Operating System:
Ubuntu 16.04.1
Linux hostname# 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* Bazel version (output of `bazel info release`):
release 0.5.3

###  Have you found anything relevant by searching the web?
Similar error messages here:
[Issue  #3097](https://github.com/bazelbuild/bazel/issues/3097), 
[Issue  #1754](https://github.com/bazelbuild/bazel/issues/1754),
[Issue #1767](https://github.com/bazelbuild/bazel/issues/1767)

but issues seem unrelated.

### Anything else, information or logs or outputs that would be helpful?
Looking at how to troubleshoot this in the user manual, did not find where to look for the bazel logs.

**Comment by damienmg** [comment]
This looks like Pulse Secure is preventing bazel front-end to talk to bazel server. Does it work with the --batch option? (e.g. `bazel --batch info`)

If so, then it is probably a security policy enforced by Pulse secure.

**Comment by oswcab** [comment]
I'll test this option this evening as now at the office I cannot connect using Pulse and I let you know.
Thanks

**Comment by oswcab** [comment]
bazel --batch build gerrit works just fine.
Thanks!

**Comment by damienmg** [comment]
Ok that's what I guessed. Thanks.

So confirmed that the problem is on the security config, not our Bazel side.

**Comment by hugares** [comment]
Even if --batch workaround is working, it would be nice to not have to use --batch.

I know this is a Pulse Secure issue because it prevents bazel client from connecting to server but I found out that if I patch bazel to use IPv4 to start server instead of IPv6, it works. IPv4 is already supported and used in case IPv6 is not supported. Would it be possible to add an option to make bazel use IPv4?

https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/server/GrpcServerImpl.java;l=695

**Comment by oswcab** [comment]
Another workaround (when possible) is to disable IPv6.

**Comment by pmoncadaisla** [comment]
In my case I was using Forticlient for VPN connection, and it was blocking IPv6 over SSL. Setting this flag to off allows me to use Bazel connected to the VPN.

in MacOS, `/Library/Application\ Support/Fortinet/FortiClient/conf/vpn.plist` and set:

```
<key>SslShouldBlockIpv6</key>
<integer>0</integer>
```

Hope someone finds this useful!

**Disclaimer**, I don't know the implications of setting this off, do it on your own risk.
