### ISSUE TITLE
sandboxing test broken

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3610]
Logs:
http://ci.bazel.io/job/bazel-tests/978/artifact/tests-node=linux-x86_64-variation=/src/test/shell/bazel/bazel_sandboxing_test/test.log/*view*/

I don't know why we don't get XML file
it is failing on Linux and ubuntu
http://ci.bazel.io/job/bazel-tests/978/artifact/tests-node=ubuntu_16.04-x86_64-variation=/src/test/shell/bazel/bazel_sandboxing_test/test.log/*view*/

**Comment by philwo** [comment]
Fix incoming.

**Comment by damienmg** [comment]
This is fixed, thanks @philwo !
