### ISSUE TITLE
Windows regression on 0.5.4 rc4 and rc5 [flake]

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3615]
It got on rc5: http://ci.bazel.io/blue/rest/organizations/jenkins/pipelines/Global/pipelines/bazel-tests/runs/187/nodes/31/log/?start=0 on windows-x86_64-3

and on rc4: http://ci.bazel.io/blue/rest/organizations/jenkins/pipelines/Global/pipelines/bazel-tests/runs/182/nodes/31/log/?start=0 on windows-x86_64-2

windows-x86_64-3 had the test passed

RC3 passed: http://ci.bazel.io/blue/rest/organizations/jenkins/pipelines/Global/pipelines/bazel-tests/runs/158/nodes/31/log/?start=0

I haven't saw the failure with bazel HEAD so far.

**Comment by damienmg** [comment]
So grepping all the log gives only those two failures since we switched to pipeline 3 weeks ago

**Comment by damienmg** [comment]
Assigning to the RM to assess.

/cc @laszlocsomor @meteorcloudy

**Comment by meteorcloudy** [comment]
I'm looking into it

**Comment by meteorcloudy** [comment]
I can reproduce this locally.

**Comment by meteorcloudy** [comment]
`bazel clean` can fix this issue, but the underlying problem is not clear.

**Comment by meteorcloudy** [comment]
Remove release block since we have a workaround.

**Comment by damienmg** [comment]
We might need to clean up our machines when the release is out. Once 0.5.4 is out I might just go and reimage all windows slave to avoid the problem

**Comment by meteorcloudy** [comment]
Sounds good to me.

**Comment by buchgr** [comment]
Should we add a message about this to the release notes i.e. "Windows users need to bazel clean once after upgrading to 0.5.4"?

**Comment by damienmg** [comment]
No new issue, a clean will fix if that ever happens, removing the breakage from it

**Comment by laszlocsomor** [comment]
@meteorcloudy : Is this issue resolved? Is P1 appropriate?

**Comment by meteorcloudy** [comment]
This only happens when upgrading Bazel from an old version to 0.5.4. We haven't seen this for a long time, so it's likely the actual bug is in a very old version of Bazel.
I believe this is resolved.
