### ISSUE TITLE
test_toolchain flaky on FreeBSD [flake]

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3619]
This is not the only instance I have seen but this is the last: http://ci.bazel.io/job/bazel-tests/982/testReport/junit/(root)/(empty)/test_register_toolchain_error_target_not_a_toolchain/

**Comment by aehlig** [comment]
Just tried to reproduce on `freebsd-12-slave-staging`, but couldn't in 50 runs.

```
INFO: Analysed target //src/test/shell/bazel:bazel_toolchain_test.
INFO: Found 1 test target...
Target //src/test/shell/bazel:bazel_toolchain_test up-to-date:
  bazel-bin/src/test/shell/bazel/bazel_toolchain_test
INFO: Elapsed time: 176.004s, Critical Path: 70.49s
INFO: Build completed successfully, 51 total actions
//src/test/shell/bazel:bazel_toolchain_test                              PASSED in 69.1s
  Stats over 50 runs: max = 69.1s, min = 33.0s, avg = 48.1s, dev = 10.1s

Executed 1 out of 1 test: 1 test passes.
```

Will try on freebsd-11 next.

**Comment by damienmg** [comment]
Related: #3629

**Comment by damienmg** [comment]
Note: this is `toolchain_test` not `bazel_toolchain_test` (yes we have both)

**Comment by aehlig** [comment]
OK, could reproduce it, but only failure mode was timeout. Moreover, the average time of the tests that didn't timeout was pretty close to the timeout. Currently testing with increased timeout and number of shards.
