### ISSUE TITLE
Support "watch" command?

### ISSUE THREAD

**Issue by pspeter3** [bazelbuild/bazel#362]
Is it possible for bazel to watch the inputs to a target and rebuild/test when inputs change?

**Comment by damienmg** [comment]
We have this tool internally and we are discussing open-sourcing it. It's a wrapper around bazel that calls it when notified of a file change by inotify.

It's not going to be support by Bazel itself though.

**Comment by hanwen** [comment]
for context, you would just do 

  while true; do blaze MYTARGET ; done

if you want to be fancy, you could use inotify rather than 'true' to trigger more conservatively.

**Comment by damienmg** [comment]
Also you can use --watchfs option to avoid bazel stating the file system and use inotify for change.

**Comment by pspeter3** [comment]
Would there be any danger in a script executed by `bazel run` invoking bazel? Eg, I may write a simple script that gets the files to watch from Bazel itself.

**Comment by damienmg** [comment]
Humm if it is on the same workspace it won't work as bazel execution lock
the workspace for themselves. Can you be more precise on what you want to
do?

**Comment by pspeter3** [comment]
That's what I anticipated but I wanted to make sure. I was hoping to have
bazel give me the input files for a target so I could explicitly watch
them. Running the script out of bazel is also totally fine

**Comment by damienmg** [comment]
bazel query 'kind(file, deps(//src:bazel))' should give you the list of
file target. With a bit of conversion you can make it a file list.

**Comment by pspeter3** [comment]
Thanks!

**Comment by softprops** [comment]
wanted to share here a tool we open sourced for this. https://github.com/meetup/rebazel. Its a tiny rustlang binary that you can swap in place of where you'd typically call bazel

```bash
brew install rebazel
rebazel test --test_filter com.foo.* --test_output streamed //pkg:foo
```

**Comment by damienmg** [comment]
https://github.com/bazelbuild/bazel-watcher

**Comment by softprops** [comment]
Ibazel was our original inspiration. Our engineers complained that it was too awkward to install and didn't really support flags well. Rebazel makes a improvements in both those areas as well adds a few things that were essential for us.
