### ISSUE TITLE
launcher_test is failing on windows

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3620]
http://ci.bazel.io/job/bazel-tests/982/testReport/junit/src_test_py_bazel_launcher_test/cmd/src_test_py_bazel_launcher_test_cmd/

**Comment by damienmg** [comment]
Not flaky sorry

**Comment by damienmg** [comment]
It actually make tests fail on windows with bazel @ HEAD too

**Comment by laszlocsomor** [comment]
Looking.

**Comment by damienmg** [comment]
Suspecting https://github.com/bazelbuild/bazel/commit/54c5c5cf41bd47d11ea309f37697d83ae65fe9e7 sorry I though native launcher was your work. /cc @meteorcloudy

**Comment by laszlocsomor** [comment]
I can repro locally with 0.5.4, at f6291af.

**Comment by laszlocsomor** [comment]
I confirmed that 54c5c5c is the culprit.

**Comment by meteorcloudy** [comment]
I have a simple fix for this

**Comment by meteorcloudy** [comment]
Sorry for the breakage, I didn't run the test after changing in internal review.
Maybe add launcher_test in Kokoro as well?
