### ISSUE TITLE
Skylark tests is timeout flaky [flake]

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3628]
3 instances, all on ubuntu 16.04:

http://ci.bazel.io/job/bazel-tests/984/artifact/tests-node=ubuntu_16.04-x86_64-variation=/src/test/java/com/google/devtools/build/lib/skylark/SkylarkTests/test.log

http://ci.bazel.io/job/Global/job/bazel-tests/200/artifact/tests-node=ubuntu_16.04-x86_64-variation=/src/test/java/com/google/devtools/build/lib/skylark/SkylarkTests/test.log

http://ci.bazel.io/job/Global/job/bazel-tests/198/artifact/tests-node=ubuntu_16.04-x86_64-variation=/src/test/java/com/google/devtools/build/lib/skylark/SkylarkTests/test.log

Laurent, please triage further

**Comment by damienmg** [comment]
Ping? This bug is stalled for 25 days...

**Comment by vladmos** [comment]
Duplicate of #3774.
