### ISSUE TITLE
//src/test/shell/bazel:toolchain_test is time out flaky on darwin [flake]

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3629]
2 instances:
http://ci.bazel.io/job/bazel-tests/985/artifact/tests-node=darwin-x86_64-variation=/src/test/shell/bazel/toolchain_test/test.log/*view*/
http://ci.bazel.io/job/Global/job/bazel-tests/200/artifact/tests-node=darwin-x86_64-variation=/src/test/shell/bazel/toolchain_test/test.log/*view*/

**Comment by damienmg** [comment]
(to be clear this is bazel_toolchain_test not toolchain_test)

**Comment by damienmg** [comment]
Arf ok I misread, so the failing test is toolchain_test but I c/p the log of bazel_toolchain_test, let me fix that.

**Comment by damienmg** [comment]
Ok now it makes sense, reassigning to the test author.

**Comment by katre** [comment]
Is this still being flaky? Please re-open if it's happening again.
