### ISSUE TITLE
--build_tests_only removes external dependencies

### ISSUE THREAD

**Issue by siyangy** [bazelbuild/bazel#3634]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

We have a custom rule to do some C++ lint test (wrapped in a py_test, similar as 
 https://github.com/RobotLocomotion/drake/blob/master/tools/cpplint.bzl). We certainly don't want to actually compile the code as it takes very long so we added build_tests_only in bazel.rc for that particular test config. The lint check then finishes instantly without compiling the code. However, every time after running it, we found that the previously built targets are lost (notably some third party dependencies under bazel-<project>/external). They are not actually been deleted though, as they come back after a bazel build without much time. My best guess is that the symlink were unlinked during lint, and recovered somehow during build again. I am wondering if there's a way to get around this.

### Environment info
* Operating System:
Ubuntu 14.04

* Bazel version (output of `bazel info release`):
0.5.1

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)
Not yet.

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
