### ISSUE TITLE
Bazel cannot build genrules with long chain of commands

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3636]
### Description of the problem / feature request / question:

If a genrule's command line is longer than some limit, Bazel writes it a shell script and runs Bash with that script.
If the command contains too many subcommands on one line (i.e. `command1 ; command2 ; ... ; commandN`), Bazel on Windows cannot build it.

The reason is MSYS segfaults when its argument is a script with such a long line.

## Repro 1

```
genrule(
  name = 'x',
  outs = ['x.out'],
  cmd = "( " + " ; ".join(["echo yyy%d" % i for i in range(0, 4973)]) + " ) > $@",  # segfault
)
```

Output:
```
ERROR: C:/work/bazel/foo/BUILD:8:1: Executing genrule //foo:x failed (Segmentation fault): bash.exe failed: error executing command C:/tools/msys64/usr/bin/bash.exe bazel-out/msvc_x64-fastbuild/genfiles/foo/x.genrule_script.sh.
bazel-out/msvc_x64-fastbuild/genfiles/foo/x.genrule_script.sh: line 2:  6012 Segmentation fault      (core dumped) ( echo yyy0; echo yyy1; echo yyy2; [...] ; echo yyy4972 ) > bazel-out/msvc_x64-fastbuild/genfiles/foo/x.out
Target //foo:x failed to build
```

## Repro 2

I can create the same script as the genrule_script.sh and run it as the genrule's tool, and it still fails:

In MSYS:
```
$ ( echo '#!/bin/bash' ; echo -n "(" ; for i in {0..4972}; do echo -n " echo yyy$i;" ; done ; echo " ) > \$1" ; ) > /c/work/bazel/foo/bar.sh
```

BUILD rule:
```
genrule(
  name = 'x',
  outs = ['x.out'],
  tools = ['bar.sh'],
  cmd = '$(location bar.sh) $@',
)
```

Again, MSYS segfaults:
```
ERROR: C:/work/bazel/foo/BUILD:8:1: Executing genrule //foo:x failed (Segmentation fault): bash.exe failed: error executing command C:/tools/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; foo/bar.sh bazel-out/msvc_x64-fastbuild/genfiles/foo/x.out.
foo/bar.sh: line 2:  4072 Segmentation fault      (core dumped) ( echo yyy0; echo yyy1; echo yyy2; [...]; echo yyy4971; echo yyy4972 ) > $1
Target //foo:x failed to build
```

I can show the segfault just from the command line:
```
C:\work\bazel>c:\tools\msys64\usr\bin\bash.exe foo\bar.sh foo\bar-out.txt
foo\bar.sh: line 2:  8804 Segmentation fault      (core dumped) ( echo yyy0; echo yyy1; [...]; echo yyy4971; echo yyy4972 ) > $1
```

And it's not the length of the line, because if I change "yyy%d" to just "y%d", it still fails.

But if I break up the long line to multiple lines, everything works:
```
$ ( echo '#!/bin/bash' ; for i in {0..4972}; do echo "echo yyy$i" ; done ) > /c/work/bazel/foo/bar.sh
```

BUILD rule:
```
genrule(
  name = 'x',
  outs = ['x.out'],
  tools = ['bar.sh'],
  cmd = '$(location bar.sh) > $@',
)
```

### Environment info
* Operating System: Windows 10 Anniversary Update with MSYS 20160205.

    ```
    $ bash --version
    GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)
    ```

* Bazel version (output of `bazel info release`):
0.5.4

**Comment by laszlocsomor** [comment]
Git-on-Windows (also MSYS)  and Cygwin exhibit the same behavior: they both segfault if you run a script with too many commands chained on one line.

**Comment by davido** [comment]
But this is not the same, as I was observing in #3589, i guess? `pck_war.bzl` in gerrit is generating 25K script size, but with single single command per line. Passing these lines separated with new line char, was failing simply because in the code path `ctx.action()`, the too long lines are passed as is, without writing the script and calling `bash` with this script instead.

**Comment by laszlocsomor** [comment]
I don't think it's the same.
This issue is about scripts that look like this:
```
command1 ; command2 ; ... ; commandN
```
If N is large enough, MSYS can't run the script.

If all of these commands were on separate lines then MSYS could run the script.

Could you take a look at the script that the `run_shell` command created? If the war-generating rule is `//foo:bar`, then Bazel writes `bazel-genfiles/foo/bar.run_shell.sh`. Take a look at that file: are the commands on new lines or separated by semicolons?

**Comment by laszlocsomor** [comment]
Ah, and I just realized there's a bug in my WIP CL (https://bazel-review.googlesource.com/c/bazel/+/15850): I create a `%{rulename}.run_shell.sh` file, meaning that every `actions.run_shell` in the same Skylark rule will try to create the file with that name. I'll fix that.

**Comment by davido** [comment]
> Could you take a look at the script that the run_shell function created?

Yes, I will have a look later today and report back. I will re-apply the new version of your patch from #3589.

**Comment by laszlocsomor** [comment]
Thanks! There's no new version yet, I'm in the middle of fixing the bug.

**Comment by laszlocsomor** [comment]
I figured out more about the bug:

*   The limit for chain length is 4964 elements. If the chain is longer, Bash won't execute any of its commands.
*   Replacing ";" with "||" or "&&" reduces the limit to 4963 elements.
*   Wrapping the chain in a Bash function does not work around the problem.
*   In some cases the chain ostensibly (but not actually) succeeds, in other cases it produces a segfault. For example, if the chain is in a function's body, the script seems to succeed. If the chain is in the main script body, Bash segfaults.

For the following script:
```
#!/bin/bash
function foo() { echo $1 ; }
foo yyy0 ; foo yyy1 ; ... ; foo yyy4963 ; foo yyy4964
```

Bash's core dump is:
```
Exception: STATUS_STACK_OVERFLOW at rip=00100410DB4
rax=00000000FFE04058 rbx=00000001004E6741 rcx=00000001004E6741
rdx=00000006002FF6F0 rsi=00000001004E6741 rdi=00000000FFE03FF0
r8 =00000001004E675E r9 =0000000000000000 r10=0000000000000000
r11=0000000100000000 r12=0000000000000000 r13=0000000000000000
r14=00000006002FF800 r15=00000001005EB0F4
rbp=00000001004E675E rsp=00000000FFE03FD0
program=C:\tools\msys64\usr\bin\bash.exe, pid 5224, thread unknown (0x24A0)
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
001004E675E  00100410DB4 (006002FF6F0, 001004E675E, 00000000000, 00000000000)
001004E675E  00100410FBB (00000000000, 00000000000, 00000000000, 00000000000)
006002FF5F0  001004125C8 (00000000000, 00000000000, 00000000000, 00000000000)
006002FF5F0  001004154BC (000FFFFFFFF, 000FFFFFFFF, 00100000000, 006002FF4B0)
001004DB7B8  0010041794C (00600044F30, 006002FF7B0, 00000000005, 006002FF4B0)
00600044F00  001004176A3 (001800B9FDC, 001004E675E, 001004132F0, 006002FF4B0)
00600044F30  0010041B235 (006002FF750, 00000000000, 006002FF4B0, 00000000000)
00000000000  00100416993 (000FFFFFFFF, 000FFFFFFFF, 00100000000, 006002FF4B0)
001004DB7B8  0010041794C (00000000000, 000FFFFFFFF, 000FFFFFFFF, 006002FF4B0)
00000000000  00100419BF4 (00000000000, 00000000000, 001005EDD38, 006002FF480)
00000000000  001004175FA (00000000000, 000FFFFFFFF, 000FFFFFFFF, 006002FF400)
00000000000  00100419BF4 (00000000000, 00000000000, 001005EDD38, 006002FF3D0)
00000000000  001004175FA (00000000000, 000FFFFFFFF, 000FFFFFFFF, 006002FF350)
00000000000  00100419BF4 (00000000000, 00000000000, 001005EDD38, 006002FF320)
00000000000  001004175FA (00000000000, 000FFFFFFFF, 000FFFFFFFF, 006002FF2A0)
00000000000  00100419BF4 (00000000000, 00000000000, 001005EDD38, 006002FF270)
End of stack trace (more stack frames may be present)
```

**Comment by laszlocsomor** [comment]
Bash in Mac OS X has a limit for the same scenario too, and it's 7937.
Bash version is: GNU bash, 3.2.57(1)-release (x86_64-apple-darwin16).

I didn't find a limit on my corp Linux machine, though it could be using a custom kernel with higher limits.

**Comment by laszlocsomor** [comment]
Given that:
*   this is not a Bazel bug
*   there are limits on at least Mac and Windows/MSYS

I think there's nothing to fix in Bazel.

I considered detecting long command chains and warning the user or rewriting the script, but realized that:
*   rewriting the script is not Bazel's job to do
*   detection would require reimplementing parts of Bash

I conclude that Bazel is working as intended.
