### ISSUE TITLE
Compilation error on 32 bit machine

### ISSUE THREAD

**Issue by shodow** [bazelbuild/bazel#3643]
When i run ./compile.sh in Ubuntu 16.04 32bit i got this error("./src/tools/singlejar/mapped_file.h:40:2: error: #error This code for 64 bit Unix"),how can i do?
i follow #3382 to modify src/main/java/com/google/devtools/build/lib/util/CPU.java (line 23-29)and
tools/cpp/lib_cc_configure.bzl (line 106)like this

```
# Use uname to figure out whether we are on x86_32 or x86_64
  result = repository_ctx.execute(["uname", "-m"])
  if result.stdout.strip() in ["power", "ppc64le", "ppc", "ppc64"]:
    return "ppc"
  if result.stdout.strip() in ["arm", "armv7l", "aarch64"]:
    return "arm"
  if result.stdout.strip() in ["i386", "i486", "i586", "i686", "i786", "x86"]:
    return "piii"
```

```
public enum CPU {
  X86_32("piii", ImmutableSet.of("i386", "i486", "i586", "i686", "i786", "x86")),
  X86_64("x86_64", ImmutableSet.of("amd64", "x86_64", "x64")),
  PPC("ppc", ImmutableSet.of("ppc", "ppc64", "ppc64le")),
  ARM("arm", ImmutableSet.of("aarch64", "arm", "armv7l")),
  S390X("s390x", ImmutableSet.of("s390x", "s390")),
  UNKNOWN("unknown", ImmutableSet.<String>of());
```
but it's not work...

Bazel version : 0.5.4
my machine information is :
```
$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK Server VM (build 25.131-b11, mixed mode)
$ uname -a
Linux ubuntu 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:18:53 UTC 2017 i686 i686 i686 GNU/Linux
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by shodow** [comment]
I seem to have solved this problem，
I just delete this line (./src/tools/singlejar/mapped_file.h:40: error: #error This code for 64 bit Unix)
i don't konw why and whether it is affected,but at present it's no error.

**Comment by shodow** [comment]
@aehlig  thank you very much ,I'll have a try :)

**Comment by vladmos** [comment]
I'm closing the issue as you've solved the problem and the proper fix has been submitted already, feel free to reopen if you have any questions.

**Comment by likan999** [comment]
The fix of deleting the line `#error This code for 64 bit Unix` doesn't work. It makes the ./compile.sh succeeds, but the resulting bazel can't be used to build scripts/packages:with-jdk/install.sh.

```
[xyz@xyz-mac-fc-x86 bazel]$ output/bazel build scripts/packages:with-jdk/install.sh                                                                               
Extracting Bazel installation...         
...........                              
ERROR: /home/xyz/.cache/bazel/_bazel_xyz/97cdd804d556cb3de47debcf86f945f6/external/bazel_tools/tools/jdk/BUILD:187:17: in singlejar attribute of java_toolchain rule @bazel_tools//tools/jdk:toolchain: '@bazel_tools//tools/jdk:singlejar' must produce a single file.                                                                 
ERROR: Analysis of target '//scripts/packages:with-jdk/install.sh' failed; build aborted.                                                                             
INFO: Elapsed time: 2.894s    
```

**Comment by IT-Wangzi** [comment]
I hava  the same issue, my os is also ubuntu 16.04 32bit LTS . but the bazel version is 0.21.0， 
i follow https://github.com/bazelbuild/bazel/pull/3382 to modify src/main/java/com/google/devtools/build/lib/util/CPU.java (line 23-29)and
tools/cpp/lib_cc_configure.bzl like this
_# Use uname to figure out whether we are on x86_32 or x86_64
  result = repository_ctx.execute(["uname", "-m"])
  if result.stdout.strip() in ["power", "ppc64le", "ppc", "ppc64"]:
    return "ppc"
  if result.stdout.strip() in ["arm", "armv7l", "aarch64"]:
    return "arm"
  if result.stdout.strip() in ["i386", "i486", "i586", "i686", "i786", "x86"]:
    return "piii"
public enum CPU {
  X86_32("piii", ImmutableSet.of("i386", "i486", "i586", "i686", "i786", "x86")),
  X86_64("x86_64", ImmutableSet.of("amd64", "x86_64", "x64")),
  PPC("ppc", ImmutableSet.of("ppc", "ppc64", "ppc64le")),
  ARM("arm", ImmutableSet.of("aarch64", "arm", "armv7l")),
  S390X("s390x", ImmutableSet.of("s390x", "s390")),
  UNKNOWN("unknown", ImmutableSet.<String>of());_

and #https://github.com/bazelbuild/bazel/pull/3382/commits/38c52418d34b0e1af4753324ad94366016cf89cc to edit the file src/BUILD (line 173-174) into        
            _"//conditions:default": [
            "//src/java_tools/singlejar:SingleJar_deploy.jar",_ it's not the same changing compared with the author, but it works. Then use the commod env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh  to run and it succeed. 
Hope to help others.
