### ISSUE TITLE
"bazel --batch clean --expunge" returns non-zero

### ISSUE THREAD

**Issue by snnn** [bazelbuild/bazel#3644]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### If possible, provide a minimal example to reproduce the problem:

"bazel --batch clean --expunge" always returns 36.

$ touch WORKSPACE

$ echo $?
0

$ bazel --batch clean --expunge
____Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.

$ echo $?
36

$ bazel clean --expunge
...........
____Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.

$ echo $?
0

$ bazel --batch clean --expunge
____Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.

$ echo $?
36

### Environment info
* Operating System:
Windows 10

* Bazel version (output of `bazel info release`):
* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
687d6c449a336cd5f9667cf0b15b0f7a26d6c103

###  Have you found anything relevant by searching the web?
No

**Comment by sgreenstein** [comment]
I recently hit this in bazel 0.8.0 on Windows. It works correctly on Linux:
```
sgreens@sgreens0:test$ bazel --batch clean --expunge
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
sgreens@sgreens0:test$ echo $?
0
```

**Comment by meisterT** [comment]
Seems to be fixed at head.
