### ISSUE TITLE
Bazel consumes too much memory and hangs in docker container

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#3645]
### Description of the problem / feature request / question:

I have a sass_binary rule from https://github.com/bazelbuild/rules_sass
And build in this docker image on CircleCI 
https://github.com/alexeagle/ngcontainer/blob/master/Dockerfile

Most of the time the build hangs while compiling C++, but sometimes it succeeds.

### If possible, provide a minimal example to reproduce the problem:

https://circleci.com/gh/alexeagle/angular-bazel-example/1
is a (somewhat) minimal example.
Source: https://github.com/alexeagle/angular-bazel-example

### Environment info
* Operating System:
Debian linux (jessie) (in docker)

* Bazel version (output of `bazel info release`):
Build label: 0.5.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 6 10:34:11 2017 (1496745251)
Build timestamp: 1496745251
Build timestamp as int: 1496745251

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by alexeagle** [comment]
Confirmed this also happens on release 0.5.4

**Comment by alexeagle** [comment]
Another sample, got a different behavior, instead of hanging it fails with an error:

```
ERROR: /root/.cache/bazel/_bazel_root/049ed6f058a98cba95753eee774cab7a/external/sassc/BUILD.bazel:4:1: C++ compilation of rule '@sassc//:sassc' failed (Exit 1)

external/libsass/src/sass.cpp:41:1: fatal error: error writing to /tmp/ccLTBo6L.s: Cannot allocate memory
 }
 ^
compilation terminated.
The bug is not reproducible, so it is likely a hardware or OS problem.
```

**Comment by alexeagle** [comment]
Hi, this prevents Angular bazel apps from using CircleCI, which is our recommendation.
It also means the canonical demo app
https://github.com/alexeagle/angular-bazel-example
has a flaky build status, which looks bad.

Can someone triage this? I might be able to fix it if I could tell what is wrong.
/cc @davidstanke

**Comment by alexeagle** [comment]
@gregmagolan tracked it down (thanks!)

Under the docker container, the amount of memory available to a process is limited
https://docs.docker.com/engine/admin/resource_constraints/

Bazel should determine the amount of available RAM (you hint at this in https://docs.bazel.build/versions/master/bazel-user-manual.html#flag--ram_utilization_factor )
but that doesn't account for the `cgroup` limitation.
https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt

**Comment by djudd-stripe** [comment]
Underlying issues might be #3886 plus #2946?

**Comment by laszlocsomor** [comment]
/cc: @jhfield @ulfjack @ericfelly 

Summary: https://github.com/bazelbuild/bazel/issues/3645#issuecomment-331672268

Who should work on this?

**Comment by ulfjack** [comment]
We have no idea what's going on there, and I don't think we can debug this without seeing jvm.out. In order to get better debug information in the future, we will also need to add code to bazel client to cat jvm.out.

**Comment by ulfjack** [comment]
This isn't the first time that not having jvm.out is preventing us from making progress.

**Comment by ittaiz** [comment]
I think I opened an issue a while back to add documentation on “what should
you report” when seeing serious bazel issues (I think I was talking about
reproducibility).

**Comment by Globegitter** [comment]
I have run into similar issues and the `jvm.out` has nothing relevant, just the some warnings that I believe are always there.

**Comment by meteorcloudy** [comment]
@ulfjack This issue is still bothering Angular. Is it possible to make Bazel auto-tune the memory usage (eg. adjusting the parallel job number) according to the RAM size?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by fmeum** [comment]
@sgowroji Not stale, has a Bazel team assignee.

**Comment by larsrc-google** [comment]
I think https://github.com/bazelbuild/bazel/pull/16512 does fix this.

**Comment by fmeum** [comment]
@larsrc-google Please reopen, my fix only applied to CPU shares, not RAM.

**Comment by larsrc-google** [comment]
The memory usage in general is hard to control - Bazel needs to hold your build graph in memory. The amount of parallel actions can be controlled with `--jobs`, e.g. `--jobs=HOST_RAM*0.01`, together with `--local_ram_resources`.
