### ISSUE TITLE
Action_config for 'assemble' missing from Windows crosstool

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/bazel#3648]
Reported on [bazel-discuss](https://groups.google.com/d/msgid/bazel-discuss/f0bcc3e2-2e19-4d30-86ab-4eb37a923e1b%40googlegroups.com).

Yun, can cl.exe compile assembly?

**Comment by meteorcloudy** [comment]
Yes, I am sure it can, will looking into this.
