### ISSUE TITLE
Targets for iOS static frameworks

### ISSUE THREAD

**Issue by mrdomino** [bazelbuild/bazel#365]
This is roughly the iOS equivalent of #348 (aar targets). It'd be great to be able to build a self-contained framework containing a static library and headers in an appropriate directory structure to hand to third-party developers.

I could swear I've seen this come up before on either bazel-discuss or in another issue, but I can't find any reference to it at the moment, so I'm creating this tracking bug.

**Comment by dslomov** [comment]
Damien, could you help direct this to the right person?

**Comment by mrdomino** [comment]
Any ETA on this? It would make my life way better.

My current hacky way of doing this is to step outside of bazel to build `kind(.*_library, deps(my_objc_library) - deps(libraries_shipped_separately))` on each arch I need, then use ar to stitch the libraries together into one single .a. This living outside of bazel means my CI setup is more complex than it needs to be (I need a build for each release, since I can't rely on ci.sh just doing the right thing.) Also it's slow as crap due to #370.

I'm not sure what would make the most sense for this, but I'm imagining something like this:

```
ios_framework(
  name="Foo",
  hdrs=[":foo_hdrs"],
  deps=[":foo_lib"],
  external=["//third_party/..."],  # things to leave out of the framework lib.
)
```

And have ios_frameworks respect --ios_multi_cpus.

Thoughts?

**Comment by c-parsons** [comment]
Update here -- we are internally testing and verifying an ios_static_framework rule written in skylark, and are working to open source this. We anticipate this should be available in a couple of weeks.

**Comment by mhlopko** [comment]
Hello Chris, also on this one, is this still expected to be fixed in 0.5? Is this a release blocker?

**Comment by c-parsons** [comment]
This is actually complete as of a week ago (sorry for not updating the issue)
We have new rules written in skylark to handle framework generation.
Please try the framework rules here: https://github.com/bazelbuild/rules_apple
(In particular, ios_static_framework.)

If there are issues with these rules, please file a separate issue.

**Comment by mhlopko** [comment]
Thanks Chris for the info and closing this issue! :)

**Comment by zetachang** [comment]
Hi @c-parsons , I couldn't find rule for `ios_static_framework` in the **rules_apple** repo, did I miss anything?
