### ISSUE TITLE
java_import has many jars and one srcjar

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#3651]
The `java_import` rule allows grouping of several jars together into a single import (which is good), but only allows a single source jar (which is less good). For the case where someone is bundling together multiple binary jars into a single import, it would be useful to also be able to specify multiple source jars too. Perhaps a `srcjars` attribute is needed.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
