### ISSUE TITLE
Docs for git_repository have confusing security section on sha256

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3655]
https://docs.bazel.build/versions/master/be/workspace.html#git_repository

```
git_repository has several issues:

Security - http_archive allows a sha256 to be specified, which ensures that the downloaded code is exactly what was expected.
...
```

This sentence implies that git_repository doesn't allow the sha256 to be specified, yet it can be in certain scenarios. So it seem wrong to omit that, but then document how to provide the sha256 a page lower.

**Comment by dslomov** [comment]
git_repository is no more
