### ISSUE TITLE
Windows: Android compilation broken at head

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3659]
### Description of the problem / feature request / question:

I built bazel at 82f71f56c221f81dcb08dadde831f98ad663b7d2 and used that to build `//examples/android/java/bazel:hello_world`. This used to work a couple weeks ago but now it's broken.

**Comment by aj-michael** [comment]
Shoot, what's the error message? Unfortunately I have no access to a windows machine 

I was hoping to get internal presubmit testing of the sample app on windows before something like this happened

**Comment by laszlocsomor** [comment]
There were 3 different errors.
@dslomov advised me to set up CI for Android on Windows but I neglected to, and now I pay hard for it.
Anyway, I have the fixes ready, I'm about to send them out.

**Comment by laszlocsomor** [comment]
Android compilation works again, but until we fix https://github.com/bazelbuild/bazel/issues/3663 I have to verify this manually periodically.
