### ISSUE TITLE
git_repository + sha256 fails with "Could not download tarball, but sha256 specified"

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3661]
### Description of the problem / feature request / question:

Error are swallowed when using git_repository + sha256 on a github repository. It is supposed to download the tarball archive from github but it can fails and the error is non understandable.

### If possible, provide a minimal example to reproduce the problem:

```
[dmarting@trantor] /tmp/w$ bazel build @git_repo//...
...........
ERROR: Could not download tarball, but sha256 specified (f7b26ab6f9c1c938766c4fc523f48cdf8108f2a16fa1a001c7c97ec39f7595ca)
INFO: Elapsed time: 1.173s
FAILED: Build did NOT complete successfully (0 packages loaded)
[dmarting@trantor] /tmp/w$ bazel build @http_repo//...
WARNING: /usr/local/google/home/dmarting/.cache/bazel/_bazel_dmarting/c06a12bbe2b47cf6ffc2589a847c1ccd/external/http_repo/WORKSPACE:1: Workspace name in /usr/local/google/home/dmarting/.cache/bazel/_bazel_dmarting/c06a12bbe2b47cf6ffc2589a847c1ccd/external/http_repo/WORKSPACE (@com_google_googletest) does not match the name given in the repository's definition (@http_repo); this will cause a build error in future versions
INFO: Analysed 11 targets (11 packages loaded).
INFO: Found 11 targets...
INFO: Elapsed time: 35.452s, Critical Path: 24.31s
INFO: Build completed successfully, 102 total actions
[dmarting@trantor] /tmp/w$ bazel build @git_repo//...
WARNING: /usr/local/google/home/dmarting/.cache/bazel/_bazel_dmarting/c06a12bbe2b47cf6ffc2589a847c1ccd/external/git_repo/WORKSPACE:1: Workspace name in /usr/local/google/home/dmarting/.cache/bazel/_bazel_dmarting/c06a12bbe2b47cf6ffc2589a847c1ccd/external/git_repo/WORKSPACE (@com_google_googletest) does not match the name given in the repository's definition (@git_repo); this will cause a build error in future versions
INFO: Analysed 11 targets (3 packages loaded).
INFO: Found 11 targets...
INFO: Elapsed time: 32.369s, Critical Path: 24.03s
INFO: Build completed successfully, 102 total actions
[dmarting@trantor] /tmp/w$ cat WORKSPACE 
git_repository(
    name = "git_repo",
    commit = "e3bd4cbeaeef3cee65a68a8bd3c535cb779e9b6d",
    remote = "https://github.com/google/googletest.git",
    sha256 = "f7b26ab6f9c1c938766c4fc523f48cdf8108f2a16fa1a001c7c97ec39f7595ca",
)

http_archive(
    name = "http_repo",
    sha256 = "f7b26ab6f9c1c938766c4fc523f48cdf8108f2a16fa1a001c7c97ec39f7595ca",
    strip_prefix = "googletest-e3bd4cbeaeef3cee

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):


65a68a8bd3c535cb779e9b6d",
    url = "https://github.com/google/googletest/archive/e3bd4cbeaeef3cee65a68a8bd3c535cb779e9b6d.tar.gz",
)
```

### Environment info
* Operating System: Linux Ubuntu 14.04
* Bazel version (output of `bazel info release`): 0.5.4

###  See also

[Thread on bazel-discuss](https://groups.google.com/d/msgid/bazel-discuss/b524d964-728e-4d18-a4d0-e2c43422857f%40googlegroups.com)

**Comment by akira-baruah** [comment]
It seems like [this call](https://github.com/bazelbuild/bazel/blob/27443bf16ecadf5ba16fd3cd4305e49930dec8e8/src/main/java/com/google/devtools/build/lib/bazel/repository/GitCloner.java#L294) to [urlPathSegmentEscaper()](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/net/UrlEscapers.html#urlPathSegmentEscaper()) escapes `/` as `%2F`, causing the generated archive URL to become
`https://github.com/user%2Frepo%2Farchive%2Ftag.tar.gz` (returns an HTTP 404 error) instead of
`https://github.com/user/repo/archive/tag.tar.gz` (expected)

**Comment by akira-baruah** [comment]
I [updated](https://github.com/akira-baruah/bazel/commit/448117adaa32f39c0639182e263eed54f49531ac) `GitClonerTest` to verify the download URL, and sure enough, the `/` characters are improperly escaped:
```
There was 1 failure:
1) testSha256TarballOkay(com.google.devtools.build.lib.bazel.repository.GitClonerTest)
Argument(s) are different! Wanted:
httpDownloader.download(
    [https://github.com/foo/bar/archive/1.2.3.tar.gz],
    <any>,
    Optional.of(tar.gz),
    /home/akira/.cache/bazel/_bazel_akira/e36bf307e80952c206a5da49e956330b/bazel-sandbox/3032536169757988015/execroot/io_bazel/_tmp/84a104db675a04ee2341dbc170478a33/output-dir,s
    <any>,
    <any>
);
-> at com.google.devtools.build.lib.bazel.repository.GitClonerTest.testSha256TarballOkay(GitClonerTest.java:87)
Actual invocation has different arguments:
httpDownloader.download(
    [https://github.com/foo%2Fbar%2Farchive%2F1.2.3.tar.gz],
    "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9826",
    Optional.of(tar.gz),
    /home/akira/.cache/bazel/_bazel_akira/e36bf307e80952c206a5da49e956330b/bazel-sandbox/3032536169757988015/execroot/io_bazel/_tmp/84a104db675a04ee2341dbc170478a33/output-dir,
    com.google.devtools.build.lib.events.StoredEventHandler@241d1052,
    {}
);
```
Compare:
1) `https://github.com/foo/bar/archive/1.2.3.tar.gz` (expected)
2) `https://github.com/foo%2Fbar%2Farchive%2F1.2.3.tar.gz` (actual)

**Comment by akira-baruah** [comment]
`bazel build @git_repo//...` now works for the example provided above. NOTE that the GitHub checksum has changed to `c18f281fd6621bb264570b99860a0241939b4a251c9b1af709b811d33bc63af8`:

```
# WORKSPACE

git_repository(
    name = "git_repo",
    commit = "e3bd4cbeaeef3cee65a68a8bd3c535cb779e9b6d",
    remote = "https://github.com/google/googletest.git",
    sha256 = "c18f281fd6621bb264570b99860a0241939b4a251c9b1af709b811d33bc63af8",
)

http_archive(
    name = "http_repo",
    sha256 = "c18f281fd6621bb264570b99860a0241939b4a251c9b1af709b811d33bc63af8",
    strip_prefix = "googletest-e3bd4cbeaeef3cee65a68a8bd3c535cb779e9b6d",
    url = "https://github.com/google/googletest/archive/e3bd4cbeaeef3cee65a68a8bd3c535cb779e9b6d.tar.gz",
)
```

**Comment by akira-baruah** [comment]
There's a bug that [breaks downstream projects](https://github.com/bazelbuild/bazel/commit/cf52ebad2f794b0c9c7fb6b77e57937bb76f53da). Here's what I think causes it:

GitHub usually prefixes archive contents with a directory named `<repo>-<reference>` where `<repo>` is the repository name and `<reference>` is a commit, branch, or tag.

However, there's an exception to this rule when a tag is formatted as a version like `v1.2.3`. In this case, GitHub omits the initial "v" producing a prefix like `<repo>-1.2.3`. For example running

    `curl -L https://github.com/bazelbuild/rules_docker/archive/v0.3.0.tar.gz | tar xvz`

yields `rules_docker-0.3.0/` instead of `rules_docker-v0.3.0`.

**Comment by Androbin** [comment]
Not only does the CI server reference
[`https://ci.bazel.io/blue/organizations/jenkins/PR%2Fbazel-tests/activity`](https://ci.bazel.io/blue/organizations/jenkins/PR%2Fbazel-tests/activity)
which has only this single slash escaped but also
[`https://ci.bazel.io/blue/organizations/jenkins/PR/bazel-tests/activity`](https://ci.bazel.io/blue/organizations/jenkins/PR/bazel-tests/activity)
gives HTTP 404 error.

1) Why does this error still persist?
2) Why is only this single slash escaped?
3) Why does the un-escaped URL not work?

**Comment by akira-baruah** [comment]
@Androbin I think that Jenkins constructs its URL as `https://{address}/blue/organizations/<org_name>/<pipeline_name>/activity` and in this case, the pipeline is named `PR/bazel-tests`. Since the `/` in the pipeline name isn't acting as a URL delimiter, it is properly escaped as part of the pipeline name field. Hope that makes sense!

**Comment by akira-baruah** [comment]
@damienmg should we close this issue?

**Comment by damienmg** [comment]
Right I don't know why this issue was still open.

**Comment by akira-baruah** [comment]
I think the original PR message only said "addresses #3661" (which is not a [GitHub closing keyword](https://help.github.com/articles/closing-issues-using-keywords/)).
