### ISSUE TITLE
Windows, Android, sh_binary launcher: missing --python_path leads to cryptic error

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3679]
### Description of the problem / feature request / question:

If I build the Android hello world example without the `--python_path` flag, I get a strange "LAUNCHER ERROR" message.
The reason is that `--python_path` is "python" be default, which is not a valid Windows program ("python.exe" or the full path "c:\python27\python.exe" would be better I guess).

### If possible, provide a minimal example to reproduce the problem:

1. Check out HEAD (663df9d) + cherry-picked https://bazel-review.googlesource.com/c/bazel/+/16273.
2. Build Bazel.
3. Add Android SDK/NDK rules to WORKSPACE
4. Build Android example without `--python_path` flag.

WORKSPACE:
```
...

android_sdk_repository(
  name = "androidsdk",
  path = "<path to SDK>",
)

android_ndk_repository(
  name = "androidndk",
  path = "<path to NDK>",
)
```

Build without `--python_path`:
```
C:\work\bazel>C:/users/laszlocsomor/appdata/local/temp/_bazel_laszlocsomor/o6hbs7n0/execroot/io_bazel/bazel-out/msvc_x64-fastbuild/bin/src/bazel.exe --output_user_root=c:\tmp2 build //examples/android/java/bazel:hello_world
...
ERROR: C:/work/bazel/examples/android/java/bazel/BUILD:12:1: Extracting Java resources from deploy jar for split Java resource apk failed (Exit 2).
LAUNCHER ERROR: Cannot launch process:
(error: 2): The system cannot find the file specified.

Target //examples/android/java/bazel:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 95.879s, Critical Path: 49.17s
```

Build with `--python_path` succeeds:
```
C:\work\bazel>C:/users/laszlocsomor/appdata/local/temp/_bazel_laszlocsomor/o6hbs7n0/execroot/io_bazel/bazel-out/msvc_x64-fastbuild/bin/src/bazel.exe --output_user_root=c:\tmp2 build //examples/android/java/bazel:hello_world --python_path=c:\python27\python.exe
...
INFO: Found 1 target...
Target //examples/android/java/bazel:hello_world up-to-date:
  C:/tmp2/o6hbs7n0/execroot/io_bazel/bazel-out/msvc_x64-fastbuild/bin/examples/android/java/bazel/hello_world_deploy.jar
  C:/tmp2/o6hbs7n0/execroot/io_bazel/bazel-out/msvc_x64-fastbuild/bin/examples/android/java/bazel/hello_world_unsigned.apk
  C:/tmp2/o6hbs7n0/execroot/io_bazel/bazel-out/msvc_x64-fastbuild/bin/examples/android/java/bazel/hello_world.apk
INFO: Elapsed time: 37.734s, Critical Path: 35.84s
```

### Environment info
* Operating System: Windows 10

* git commit hash:
HEAD (663df9d) + cherry-pick https://bazel-review.googlesource.com/c/bazel/+/16273.

**Comment by laszlocsomor** [comment]
@meteorcloudy : FYI

**Comment by meteorcloudy** [comment]
I think it's fine to just use `python` as python_bin_path, it works on my machine.
Maybe it's because `python` is not in your PATH environment variable?

**Comment by laszlocsomor** [comment]
/me is silly, I forgot I filed this bug a week ago... anyway, duplicate of https://github.com/bazelbuild/bazel/issues/3717
