### ISSUE TITLE
Support C++ opts for objc_* targets

### ISSUE THREAD

**Issue by mrdomino** [bazelbuild/bazel#368]
Needed by #366.

**Comment by ulfjack** [comment]
#366 says: Support C++11 Objective-C++ in objc_.* targets.

**Comment by c-parsons** [comment]
Consider separating out objc_library targets into srcs of different types, if their copts need to differ? These can be later recombined as a single objc_library which depends on both...

Per-language per-target copts strikes me as scaling poorly.

Feel free to reopen and explain if this doesn't work for you.
