### ISSUE TITLE
Error surfaced when using fail exception in repository_rule is hard to read/locate

### ISSUE THREAD

**Issue by htuch** [bazelbuild/bazel#3683]
In the Envoy build, we `fail` when a `repository_rule` goes bad (https://github.com/lyft/envoy/blob/b0d8095d0cd3c63667997124b9e8cee70d52f743/bazel/repositories.bzl#L28). However, while this ends the execution of the `repository_rule`, the build continues and we get a confusing message later in execution, e.g. https://groups.google.com/forum/#!topic/envoy-users/MPLgCsj0zrQ, where the build relies on an outcome of the `repository_rule` that is missing. The message in the `fail` is not output to the user.

I think the correct behavior would be for Bazel to hard fail the build and print the error.

**Comment by damienmg** [comment]
Are you sure this the error that is triggered? Using with --nokeep_going should fail the build as soon as we hit the error. If not we definitely needs to investigate more.

**Comment by htuch** [comment]
I just checked, and even with `--nokeep_going` I get:

```
make: *** [/usr/local/google/home/htuch/.cache/bazel/_bazel_htuch/d994dfb436942cc737a6ac7e679f7c24/external/envoy_deps_cache_b3779303a90cb6b7115db282060da854/boringssl.dep] Error 1
make: Leaving directory `/usr/local/google/home/htuch/.cache/bazel/_bazel_htuch/d994dfb436942cc737a6ac7e679f7c24/external/envoy_deps'
WARNING: /usr/local/google/home/htuch/src/envoy-2/bazel/repositories.bzl:26:5: External dep build exited with return code: 1
WARNING: /usr/local/google/home/htuch/src/envoy-2/bazel/repositories.bzl:28:9:  External dependency build failed, check above log for errors and ensure all prerequisites at https://github.com/lyft/envoy/blob/master/bazel/README.md#quick-start-bazel-build-for-developers are met.
ERROR: error loading package 'source/exe': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf_bzl//': no such package '@envoy_deps//thirdparty/protobuf': External dep build failed
ERROR: error loading package 'source/exe': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf_bzl//': no such package '@envoy_deps//thirdparty/protobuf': External dep build failed
INFO: Elapsed time: 0.104s
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: source/exe
[2]    19637 exit 1     bazel build --nokeep_going //source/exe/...
```

If you look at https://github.com/lyft/envoy/blob/ec0591e9e6132c95b01f43b3bd9681db582b0e7d/bazel/repositories.bzl#L32, the build should have terminated after the second WARNING above. I do see the `fail` message, appended to a confusing ERROR message. This might be "working as intended", since it's probably catching the error while searching for the `protobuf_bzl` dependency and evaluating the rule, but I think a `fail` should be more prominent, indicating to the user the desired failure message (and then secondarily, have some stack information).

**Comment by damienmg** [comment]
The build finish after the second warning but indeed the error are not really good, we should fix them.

**Comment by damienmg** [comment]
(Amended the topic so it's clearer that we have to ameliorate the error message)
