### ISSUE TITLE
BuildEventProtocol is not publically visible 

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3684]
The BuildEventProtocol is a publically documented part of bazel's api (https://docs.bazel.build/versions/master/build-event-protocol.html), yet the build rule that defines the proto_library rule is not publically visible.

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/BUILD

This makes it hard to depend on it without copying and maintaining another copy, especially since it isn't self contained.

**Comment by meteorcloudy** [comment]
//cc @buchgr

**Comment by buchgr** [comment]
You are totally right @endobson

**Comment by jmillikin-stripe** [comment]
Gentle ping -- any progress on this?

I think it might make sense to move the BEP protos out of `bazelbuild/bazel` into a separate repo (perhaps by a Kubernetes-style automirror). Fetching Bazel sources can be a huge dependency for small tools that want to consume BEP events, and it'd be nice if we could fetch just the protos.

**Comment by buchgr** [comment]
I think it makes sense to contribute the protobuf to https://github.com/bazelbuild/remote-apis, which contains also the remote execution API.

**Comment by tsawada** [comment]
Is there any update? It'd be great if the protos move to https://github.com/bazelbuild/remote-apis so that I don't have to depend on the whole 70MB of the entire bazel tar.gz just to use a few messages.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by brentleyjones** [comment]
Not stale

**Comment by ZSmallX** [comment]
Is there any update? It would be helpful if build_event_stream_proto is public visible.

I want to consume BEP in my golang program, but I'm unable to reuse the protocol definition unless copy them.

Hope this would work to generate go code.
```
load("@io_bazel_rules_go//proto:compiler.bzl", "go_proto_compiler")

go_proto_compiler(
    name = "build_event_stream_go_proto",
    deps = ["@io_bazel//:build_event_stream_proto"],
)
```

**Comment by cameron-martin** [comment]
Related: https://github.com/bazelbuild/bazel/issues/20315#issuecomment-1831845550

**Comment by Wyverald** [comment]
@meisterT, could you ask someone on the performance team to take a look at this? It's a very long standing request and I think completely reasonable.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.2.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.2.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.2.0rc1. Thanks!

**Comment by Jonpez2** [comment]
Hello! This is a good change but how does one depend on this in bzlmod land please? Also I think one needs //src/main/protobuf:spawn_java_proto in order to parse an execution_log_binary_file. 

Thanks!

**Comment by iancha1992** [comment]
> Hello! This is a good change but how does one depend on this in bzlmod land please? Also I think one needs //src/main/protobuf:spawn_java_proto in order to parse an execution_log_binary_file.
> 
> Thanks!

cc: @comius

**Comment by Jonpez2** [comment]
Ping please? Thank you!
