### ISSUE TITLE
Missing dependencies of Aspects cause confusing error messages

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3685]
When building a java_proto_library the output says that 'proto_library' rules have an implicit dependency on the java toolchain, which is incorrect. Instead it is likely the aspect version of the proto_library rule which has that implicit dependency.

Workspace file (probably will work with other version of bazel as well).
```
http_archive(
  name = "io_bazel",
  sha256 = "4193fa72356d62eb648d470f73d8bc4ae910fbf29eb3ad77274ec7ff9346849b",
  strip_prefix = "bazel-visibility",
  urls = ["https://github.com/endobson/bazel/archive/visibility.tar.gz"],
)
```

```
endobson@yggdrasil () ~/proj/bes-example % bazel build @io_bazel//src/main/java/com/google/devtools/build/lib/buildeventstream/proto:build_event_stream_proto                                                                             (1)
INFO: Reading 'startup' options from /Users/endobson/.bazelrc: --watchfs
INFO: Found 1 target...
Target @io_bazel//src/main/java/com/google/devtools/build/lib/buildeventstream/proto:build_event_stream_proto up-to-date:
  bazel-genfiles/external/io_bazel/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream_proto-descriptor-set.proto.bin
INFO: Elapsed time: 0.510s, Critical Path: 0.00s
endobson@yggdrasil () ~/proj/bes-example % bazel build @io_bazel//src/main/java/com/google/devtools/build/lib/buildeventstream/proto:build_event_stream_java_proto                                                                        (0)
INFO: Reading 'startup' options from /Users/endobson/.bazelrc: --watchfs
ERROR: /private/var/tmp/_bazel_endobson/c56b77af296477cd0f319aa9d4ce1d19/external/io_bazel/src/main/protobuf/BUILD:25:2: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf_java//:java_toolchain', but this target could not be found because of: no such package '@com_google_protobuf_java//': The repository could not be resolved.
ERROR: /private/var/tmp/_bazel_endobson/c56b77af296477cd0f319aa9d4ce1d19/external/io_bazel/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/BUILD:20:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf_java//:java_toolchain', but this target could not be found because of: no such package '@com_google_protobuf_java//': The repository could not be resolved.
WARNING: errors encountered while analyzing target '@io_bazel//src/main/java/com/google/devtools/build/lib/buildeventstream/proto:build_event_stream_java_proto': it will not be built.
INFO: Found 0 targets...
ERROR: command succeeded, but not all targets were analyzed.
INFO: Elapsed time: 0.530s, Critical Path: 0.00s
```

**Comment by meteorcloudy** [comment]
//cc @buchgr Can you also take a look at this as well? ;)

**Comment by buchgr** [comment]
I think @cgrushko will know more.

**Comment by cgrushko** [comment]
You're missing the `com_google_protobuf_java` external repo; see example in https://github.com/cgrushko/proto_library/blob/master/WORKSPACE

(yep, docs are lacking, it's on our queue to improve them)

**Comment by endobson** [comment]
The issue is not that I was in a situation which caused an error message. The issue is that the error message says confusing things:

> ERROR: /private/var/tmp/_bazel_endobson/c56b77af296477cd0f319aa9d4ce1d19/external/io_bazel/src/main/protobuf/BUILD:25:2: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf_java//:java_toolchain', but this target could not be found because of: no such package '@com_google_protobuf_java//': The repository could not be resolved.

This is not true. No rules of proto_library implicitly depend on '@com_google_protobuf_java//:java_toolchain'. The java_proto_library adds an aspect version of proto_library that has that implicit dependency (or at least I believe thats how it works). Thus this looks like an issue with aspects where they report issues in the context of the original rule instead of the aspected copy.

I cannot reopen as I'm not in the ACLs.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
