### ISSUE TITLE
discard_graph_edges_test fails but XML says the test passed

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3687]
So we had several breakage on CI without useful XML output. Investigated the discard_graph_edges_test on one of the PR and I found the following output

http://ci.bazel.io/job/PR/job/bazel-tests/105/execution/node/97/ws/bazel-testlogs/src/test/shell/integration/discard_graph_edges_test/shard_1_of_5/test.xml/*view*/:
```
<?xml version="1.0" encoding="UTF-8"?><testsuites><testsuite><testcase name="test_info" status="run" time="10.149" classname=""></testcase></testsuite></testsuites>
```

[http://ci.bazel.io/job/PR/job/bazel-tests/105/execution/node/97/ws/bazel-testlogs/src/test/shell/integration/discard_graph_edges_test/shard_1_of_5/test.log/*view*/](https://gist.github.com/damienmg/fead657109acb4ff2290305d3ab86228)

**Comment by damienmg** [comment]
And the interesting part is "/private/var/tmp/_bazel_ci/282a174d82e4200497ceb8612808f3ab/bazel-sandbox/823694128990615721/execroot/io_bazel/bazel-out/darwin_x86_64-fastbuild/bin/src/test/shell/integration/discard_graph_edges_test.runfiles/io_bazel/src/test/shell/unittest.bash: line 654: /usr/bin/perl: Argument list too long"

So we are hitting the command line limit

**Comment by damienmg** [comment]
In the spirit of who touch it last who owns it I summon @michajlo :)

**Comment by aiuto** [comment]
Possibly still a bug. Since there is no easy repo, and it has not had activity for a long time I am lowering priority, but keeping test tag.

**Comment by jin** [comment]
Closing as we haven't seen this in a long time.
