### ISSUE TITLE
toolchain_type rule is not documented

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3691]
There exists a rule `toolchain_type` referenced by the `toolchain` rule that does not exist in documentation.

https://docs.bazel.build/versions/master/be/platform.html#toolchain

https://docs.bazel.build/search.html?cx=012346921571893344015%3Axv_nfgpzbu4&cof=FORID%3A10&ie=UTF-8&q=toolchain_type

**Comment by meteorcloudy** [comment]
//cc @katre
