### ISSUE TITLE
Is there a way to get the targets that would be reevaluated?

### ISSUE THREAD

**Issue by ddwolf** [bazelbuild/bazel#3694]
I have modified some files and want to konw which targets will be reevaluated, is there a way to get this?

**Comment by meteorcloudy** [comment]
Hi @ddwolf, I think https://docs.bazel.build/versions/master/query-how-to.html#reverse-dependencies might be what you are looking for.

**Comment by meteorcloudy** [comment]
You can do `bazel query 'rdeps(//..., <path to changed file>)'`, but be careful if your repo is very large, Bazel may run out of memory.

**Comment by philwo** [comment]
Closing this as the question has been answered.

**Comment by ddwolf** [comment]
@meteorcloudy  if I don't know what files have been modified, then how to achieve this?

**Comment by meteorcloudy** [comment]
@damienmg Is it possible to make Bazel return all targets that would be re-evaluated without knowing exactly which files are modified?

**Comment by damienmg** [comment]
I don't think so...
