### ISSUE TITLE
_clone_or_update using bash instead of BAZEL_SH

### ISSUE THREAD

**Issue by filipesilva** [bazelbuild/bazel#3699]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

On Windows, the `_clone_or_update` function in `git.bzl` is using `bash` instead of `BAZEL_SH`: https://github.com/bazelbuild/bazel/blob/8c8633610a948846244494e2e3dad91eb0536a58/tools/build_defs/repo/git.bzl#L25

This is problematic because `bash` can be other shells, such as Linux Subsystem for Windows, instead of the required MSYS2 shell.

### If possible, provide a minimal example to reproduce the problem:
- 

### Environment info
* Operating System: Windows 10

* Bazel version (output of `bazel info release`):
```
release 0.5.4
```

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
- 

### Anything else, information or logs or outputs that would be helpful?

/cc @dslomov @alexeagle

**Comment by dslomov** [comment]
cc @laszlocsomor

**Comment by alexeagle** [comment]
FYI I believe the workaround is just to use the native `git_repository` rule rather than loading the one from `@bazel_tools`.
In my case I didn't need the features from the native git client; the jgit used by the native rule works.
You can drop the priority/severity here.

**Comment by bimmlerd** [comment]
@alexeagle unfortunatelz the native rule is broken in interesting ways, thus not really a viable option:

> Library issues - This implementation uses jGit, which we've discovered several issues with. It also lacks support for some authentication types you might use with your system git. 

from https://docs.bazel.build/versions/master/be/workspace.html#git_repository

**Comment by alexeagle** [comment]
Fair enough - internally we have an "sso" scheme which requires jgit, so I guess we just have to flip this back and forth depending on the environment.

**Comment by davido** [comment]
I still think, that general purpose rules, and this what I would expect rules_nodejs to be, should just work on both git and jgit and all three major platforms. Gerrit Code Review is currently using custom JS tool chain but in the long run, its Polymer stack should be migrated to use standard JS/NodeJS rules.

**Comment by alexeagle** [comment]
rules_nodejs itself works fine, it's up to the user to put the right
git_repository rule in their WORKSPACE file.

**Comment by bimmlerd** [comment]
Any update on this? 0.7 is out and still seems to have this bug.

**Comment by laszlocsomor** [comment]
ping @dslomov

**Comment by laszlocsomor** [comment]
I think this can be fixed simply by using [`actions.run_shell`](https://docs.bazel.build/versions/master/skylark/lib/actions.html#run_shell). Bazel supports that on Windows already.

**Comment by laszlocsomor** [comment]
I'm removing the Windows label because this is a bug in the `git` rule implementation, not in Bazel's Windows-specific logic.
