### ISSUE TITLE
Incremental builds across different ios_cpu

### ISSUE THREAD

**Issue by mrdomino** [bazelbuild/bazel#370]
When I script bazel to build a fat objc_library, I appear to lose all build incrementality, probably because it gets reset per ios_cpu. This causes nothing-changed builds to take upwards of a minute where they'd ortherwise take less than a second.

Maybe this overlaps with some other issue or some work on the roadmap that will render this obsolete -- if so, then please close this issue and don't let it distract. :)

**Comment by laszlocsomor** [comment]
Peter, could you comment?

**Comment by kchodorow** [comment]
Assigning to Chris, since Peter's on vacation.

**Comment by jmmv** [comment]
The current theory here is that we lose the in-memory metadata for all files in the action cache, and thus the incremental build has to recompute their digests, which is costly. There may be other things at play here. The plan is to get this fixed by next quarter.

**Comment by mhlopko** [comment]
Hello Julio, is this still expected to be fixed in 0.5? We're still at least 2 weeks away from the release but we should be getting ready.

**Comment by damienmg** [comment]
Julio is on holiday, moving to 0.6

**Comment by aiuto** [comment]
The entire Apple tool chain changed int he last 7 years. This is obsolete.
