### ISSUE TITLE
windows: bazel clean --expunge fails when switching from git_repository to local_repository

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#3700]
### Description of the problem / feature request / question:

Switched a repository from git_repository to local_repository (to allow editing its files locally).

### If possible, provide a minimal example to reproduce the problem:
```
$ bazel clean --expunge
____Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than sever
ERROR: C:/msys64/tmp/_bazel_angular/buoukos3/external/build_bazel_rules_nodejs/.git/objects/pack/pack-714426c75826180e9651993d.pack (Permission denied).
```
### Environment info
* Operating System:
Windows 10

* Bazel version (output of `bazel info release`):
0.5.4

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by alexeagle** [comment]
Windows file explorer also reports it cannot remove the files because they are open by another program, even after killing the shell where bazel was running.

**Comment by meteorcloudy** [comment]
Hi @alexeagle , I think Bazel is unlikely to open git's object files, can you check which program the file is opened in?

**Comment by alexeagle** [comment]
I don't know how to check that on windows, is there an equivalent of linux `lsof` or `/proc/xxx/fd` on windows?

**Comment by meteorcloudy** [comment]
I am using a software called [Process-Explorer](http://www.chip.de/downloads/Process-Explorer_12996492.html)

**Comment by filipesilva** [comment]
In my case it happened with https://github.com/bazelbuild/rules_typescript while updating the commit hash in https://github.com/bazelbuild/rules_typescript/blob/master/WORKSPACE#L20. Permissions only cleared after a restart.

```
kamik@T460p MINGW64 /d/sandbox/rules_typescript (master)
$ bazel clean --expunge
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
ERROR: C:/users/kamik/appdata/local/temp/_bazel_kamik/y9xg3tkg/external/build_bazel_rules_nodejs/.git/objects/pack/pack-81f5c50edfae70559ba382ba58fb1b69a24e3b9a.pack (Permission denied)
```

Using process explorer I can see it is being used by Java:
![image](https://user-images.githubusercontent.com/4172079/33897332-0b58657a-df5d-11e7-8a71-70ef4ce3de45.png)

This instance of java seems to be the one embedded in bazel
![image](https://user-images.githubusercontent.com/4172079/33897407-437a3d66-df5d-11e7-8112-3b42389ab576.png)

**Comment by meteorcloudy** [comment]
Let me try to reproduce this.

**Comment by meteorcloudy** [comment]
I can reproduce this, I believe https://stackoverflow.com/questions/31764311/how-do-i-release-file-system-locks-after-cloning-repo-via-jgit is causing this problem.

We should also call `git.getRepository().close();` before https://github.com/bazelbuild/bazel/blob/9135b7bfc4245e16bd6599e22dce0ba077e0d10a/src/main/java/com/google/devtools/build/lib/bazel/repository/GitCloner.java#L259

I'll send a fix.
