### ISSUE TITLE
ProtoSourcesProvider is not available as a Provider

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3701]
I want to write a lang_proto_library rule, and as such enforce that all the labels in the `deps` attribute export the right provider. I currently can only enforce that they export the old style provider "proto", instead of a new style provider.

Bazel release = 0.5.4

**Comment by meteorcloudy** [comment]
//cc @vladmos

**Comment by oscar-stripe** [comment]
what's the story here? This has become import for us. Any news?

@dslomov @cgrushko ?

**Comment by oscar-stripe** [comment]
PS: it seems like we can consume the provider via skylark: https://docs.bazel.build/versions/master/skylark/lib/ProtoSourcesProvider.html but I don't see how we can create a provider.

Context: we would like to download some protobuf descriptors in a repository rule and consume them in the current repo. We can download the providers, but we have no way to get them back as consumable by proto_library currently. This is causing us pain and suffering.

**Comment by cgrushko** [comment]
@iirina

**Comment by perezd** [comment]
Any update here? How does one produce proto genfiles that can use the proto provider?
