### ISSUE TITLE
required_aspect_providers and provides arguments of aspect are not documented well

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3702]
These two arguments are documented in the code with the string `<not available>`. This string is treated as the markup tag `not` and so doesn't actually render in the generated documentation.

https://docs.bazel.build/versions/master/skylark/lib/globals.html#aspect
https://github.com/bazelbuild/bazel/blob/8d6fc64b18c7e35b93f5c43dae1dbd2f8cae2147/src/main/java/com/google/devtools/build/lib/analysis/skylark/SkylarkRuleClassFunctions.java#L645-L658

@dslomov

**Comment by laurentlb** [comment]
This is fixed
