### ISSUE TITLE
native compilation bazel fails with "pure virtual method called " error

### ISSUE THREAD

**Issue by Kalindee** [bazelbuild/bazel#3706]
Hi,
I am building bazel on armv7 board to compile tensorflow and followed the bazel build instruction for armv7 from :https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/GUIDE.md#3-build-bazel.
 Bazel build successfully completed . To make sure that Bazel build is working proper when I have issued bazel commad but got the following error:
     bazel
	 pure virtual method called
	 terminate called without an active exception
	 Aborted can help.

Could anyone has any input on this?

**Comment by philwo** [comment]
Mhmm... not sure who would be a good person on the team to look into this?

@aehlig Any idea?

**Comment by jin** [comment]
Closing this as dupe of https://github.com/bazelbuild/bazel/issues/8882
