### ISSUE TITLE
Bazel query //... downloads 1.1 GB zip file and then hangs

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#3707]
The hang might be due to #3534. But having Bazel query download a 1 GB zip file _on every single run_ with no caching seems like a pretty bad user experience.

```
$ bazel query //...
...
INFO: Downloading https://github.com/google/j2objc/releases/download/2.0.3/j2o\
bjc-2.0.3.zip via github-production-release-asset-2e65be.s3.amazonaws.com: 101\
,159,424 bytes
```

**Comment by ulfjack** [comment]
When I interrupt it when it hangs, it outputs:
```
^C
Bazel caught interrupt signal; shutting down.
DEBUG: /usr/local/google/home/ulfjack/Projects/bazel/src/test/docker/docker_pull.bzl:47:5: Running `docker build`.
ERROR: query interrupted.
```

**Comment by damienmg** [comment]
Download j2objc at each runs is not normal, this should be cached.

**Comment by damienmg** [comment]
I just had a complementary though: at some point docker build were also
cancelled in repository function. Do we interrupt long SkyFunction at some
point?

**Comment by ulfjack** [comment]
No, we don't enforce any timeouts on sky functions.
