### ISSUE TITLE
Bazel decompresses new_http_archive whenever BUILD file changes

### ISSUE THREAD

**Issue by drigz** [bazelbuild/bazel#3708]
When using new_http_archive and editing the BUILD file, Bazel will decompress the archive each time, even if it has been drawn from the experimental_repository_cache. This can be slow for large repos (#3397).

This is quite annoying when working on a difficult BUILD file for a large external repo, eg [rules_boost](https://github.com/nelhage/rules_boost).

### If possible, provide a minimal example to reproduce the problem:

```
➜  echo "build --experimental_repository_cache=$PWD/.cache" > .bazelrc
➜  cat WORKSPACE 
new_http_archive(
    name = "boost",
    build_file_content = """
filegroup(
    name = "install",
    srcs = ["index.htm"],
)
""",
    sha256 = "beae2529f759f6b3bf3f4969a19c2e9d6f0c503edcb2de4a61d1428519fcb3b0",
    strip_prefix = "boost_1_63_0/",
    url = "https://dl.bintray.com/boostorg/release/1.63.0/source/boost_1_63_0.tar.bz2",
)
➜  bazel build @boost//:install
INFO: Analysed target @boost//:install (2 packages loaded).
INFO: Found 1 target...
Target @boost//:install up-to-date (nothing to build)
INFO: Elapsed time: 240.105s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
➜  sed -i "s/htm/html/" WORKSPACE 
➜  bazel build @boost//:install
INFO: Analysed target @boost//:install (2 packages loaded).
INFO: Found 1 target...
Target @boost//:install up-to-date (nothing to build)
INFO: Elapsed time: 205.076s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
```

### Environment info
* Operating System: Ubuntu 14.04
* Bazel version: 0.5.4

**Comment by philwo** [comment]
Assigning to @damienmg according to triage owners and because Kristina is no longer here :(

**Comment by damienmg** [comment]
We could cache the uncompressed step but since you are not supposed to rewrite the BUILD file a lot that seems like a corner case optimisation.

**Comment by drigz** [comment]
I've realised in the mean time that I could use `--override_repository` to avoid repeated decompression on this use case.

**Comment by philwo** [comment]
Thanks for the feedback. Let's close this then.
