### ISSUE TITLE
Better Invalid SHA256 checksum message

### ISSUE THREAD

**Issue by ianthehat** [bazelbuild/bazel#3709]
When you specify an incorrect checksum, the message you get is
```
Invalid SHA256 checksum.
```
It would be nice if it told you what the correct checksum was. This would be an easy way of updating a repository version. Update the reference, set the sha to an invalid value, try to build, cut'n'paste in the correct checksum, profit.

**Comment by dungeonmaster18** [comment]
Hi, Can someone help me to get started with this issue. I am new here.

**Comment by keir** [comment]
The error message is not clear, especially if you are new to Bazel and are gluing together pieces of other Bazel WORKSPACE files to get a project going. Here's a suggested alternate message that would make it more clear:

```
The SHA256 checksum specified in the WORKSPACE file does not match the SHA256
checksum of the downloaded file. The checksum exists to ensure a secure build,
since remote files can change. If the file is correct, update the SHA256 checksum.
("sha256 = ") in your WORKSPACE file. Otherwise, this could be a security compromise.

File:
/home/keir/foo/bazel-build/..../foo.tar.gz"

Expected SHA256 (from WORKSPACE):
1ee310e5d0a19b9d584a855000434bb724aa744745d5b8ab1855c85bff8a8e21

Actual SHA256 from file:
6e16c8bc91b1310a44f3965e616383dbda48f83e8c1eaa2370a215057b00cabe
```

**Comment by deepaknalore** [comment]
Hi! I would like to pick this up.

**Comment by jin** [comment]
@deepaknalore go for it!

**Comment by mig35** [comment]
This should be closed because it is already implemented and merged in https://github.com/bazelbuild/bazel/pull/5991

**Comment by jin** [comment]
#5991 isn't merged. It's still open here: https://github.com/bazelbuild/bazel/pull/5996

**Comment by pscheid2** [comment]
I'm not sure this issue is still relevant. The error message to be improved ("Invalid SHA256 checksum.") is no longer anywhere in the repo and files touched in the old PRs on this issue don't have any special checksum validation logic.

**Comment by redone9211** [comment]
i would like to contribute to this issue , can you let me know how i can solve it.
