### ISSUE TITLE
How to get resolved runfiles path from a skylark rule

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#3720]
On Windows, it's necessary to resolve runtime dependencies through the runfiles.manifest file.

I have a `template_action` that writes a wrapper script, it needs to know the path to a binary and an entry point file.
https://github.com/bazelbuild/rules_nodejs/blob/defc6449af919b7388e64467df27ceba95b4a33b/internal/node.bzl#L73
Rather than some mechanics to look this up in the manifest, eg. 
https://github.com/bazelbuild/rules_nodejs/pull/12/files#diff-8ff781f26faf09b017356acd453b0bdcR96
it would be better to just write the resolved path into the file when the template is interpolated.

It seems possible only by hacking around the https://docs.bazel.build/versions/master/skylark/lib/root.html object to get the path on disk:

`print(str(ctx.file._node.root)[:-len("[source]")])`
->
`C:/msys64/tmp/_bazel_angular/hsol5eiq`

To which I can append `ctx.file._node.path` to get the real path on disk
`C:/msys64/tmp/_bazel_angular/hsol5eiq/external/nodejs/node.exe`

However this is pretty gross. Is there a public API to get the real path on disk to the file's root?

**Comment by dslomov** [comment]
> it would be better to just write the resolved path into the file when the template is interpolated.
This is non-hermetic. Do not do that. Outputs of a build should not contain local paths

> `print(str(ctx.file._node.root)[:-len("[source]")])`
The fact that this works is is a bug, fixed at HEAD.

**Comment by dslomov** [comment]
Actually not sure that `str(root)` is fixed. Do not use it anyway!

**Comment by vladmos** [comment]
This feature (actually a bug) will be disabled in the upcoming Bazel 0.6, `str(root)` will return either `"<source root>"` or `"<derived root>"` (for source and generated files correspondingly).
