### ISSUE TITLE
objc_library documentation doesn't mention `.S` assembler files can be passed to srcs

### ISSUE THREAD

**Issue by bkase** [bazelbuild/bazel#3724]
### Description of the problem / feature request / question:

`objc_library` documentation doesn't mention `.S` assembler files can be passed to srcs. We have a tool that generates BUILD files and it was filtering out `.S` source files since it wasn't mentioned in the documentation. Could you update the docs?

**Comment by meisterT** [comment]
@c-parsons is this still relevant?
