### ISSUE TITLE
Cleanup of MoreAsserts#assertThrows

### ISSUE THREAD

**Issue by aj-michael** [bazelbuild/bazel#3729]
JUnit 4.13 will add a very helpful method called assertThrows. Until that is released, we can add this method to com.google.devtools.build.lib.testutil.MoreAsserts. After JUnit 4.13 is released, we should go back and change all of the callsites.

**Comment by andyscott** [comment]
JUnit 4.13 has been released!

**Comment by ulfjack** [comment]
I already added the new junit into third_party.

**Comment by jin** [comment]
Cleaned up by @michajlo in https://github.com/bazelbuild/bazel/commit/660d17feaff82b34ac895b280ebe90a688465c0f (and other CLs)
