### ISSUE TITLE
On Windows, the path to build directories is not correct

### ISSUE THREAD

**Issue by gregbown** [bazelbuild/bazel#3734]
### Description of the problem:

On windows, it appears that the paths areincorrect in bazel and thus the error **Not a file**  or **file(s) do not exist** occurs on both install and build as documented below.

`bazel run @yarn//:yarn
ERROR: no such package '@yarn//': Traceback (most recent call last):
        File "C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/build_bazel_rules_nodejs/internal/node_install.bzl", line 89
                ctx.file("yarn.sh", ("#!/bin/bash" + "".joi...])), ...)
        File "C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/build_bazel_rules_nodejs/internal/node_install.bzl", line 89, in ctx.file
                "".join(["\nROOT=\"$(dirname \"{}\")\"\n...])
        File "C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/build_bazel_rules_nodejs/internal/node_install.bzl", line 89, in "".join
                "\nROOT=\"$(dirname \"{}\")\"\nNODE=\"{}\"\nSCRIPT=\"{}\"\n(cd \"$ROOT\"; \"$NODE\" \"$SCRIPT\" \"$@\")\n".format(ctx.path(package_json), ctx.path(c...), ..."))
        File "C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/build_bazel_rules_nodejs/internal/node_install.bzl", line 96, in "\nROOT=\"$
                ctx.path(ctx.attr._node)
Not a file: C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/nodejs/bin/node.`

**The closest actual path below, correct segment letters in bold**
**C:/Users/gbown/AppData/Local/Temp/_bazel_gbown/aFPn2GXi/external/nodejs**/node_modules/npm/bin

This may be a symptom of the prior error if I work around Basel by running install manually
`C:\Users\gbown\Documents\bazel-angular\angular-bazel-example>bazel build src
INFO: Found 1 target...
ERROR: missing input file '@nodejs//:bin/node'.
ERROR: C:/users/gbown/documents/bazel-angular/angular-bazel-example/src/BUILD.bazel:5:1: //src:src: missing input file '@nodejs//:bin/node'.
Target //src:src failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: C:/users/gbown/documents/bazel-angular/angular-bazel-example/src/BUILD.bazel:5:1 1 input file(s) do not exist.`

**This path is correct**
C:\Users\gbown\Documents\bazel-angular\angular-bazel-example\src\BUILD.bazel

### If possible, provide a minimal example to reproduce the problem:
I am trying to build [angular with bazel](https://github.com/alexeagle/angular-bazel-example)

### Environment info
**System Info**
Windows 10 Pro, Version 1703, OS Build 15063.540
Yarn 1.0.1
Node 6.10.2
npm 4.0.2
Python 3.6.2
Java version "1.8.0_144"
Java SE Runtime Environment (build 1.8.0_144-b01)
Visual Studio 2017 15.3.4
WebStorm 2017.2.4
**Bazel version**
Build label: 0.5.4 Build target: bazel-out/msvc_x64-fastbuild/bin/src... Build time: Fri Aug 25 09:59:45 2017 (1503655185) Build timestamp: 1503655185 Build timestamp as int: 1503655185

###  Have you found anything relevant by searching the web?
I have not found any working Angular, TypeScript or Closure Bazel examples

### Anything else, information or logs or outputs that would be helpful?
Bazel was installed with the binary download version without jdk as jdk is already set up on my system.
I was able to run the hello world examples in the bazel repo; Java, Python and C++ without any issues.
I set up an environment paths so I can access Bazel, Java and Python in cmd or power shell in any directory.

**Comment by meteorcloudy** [comment]
Hi, @gregbown . File path on Windows is usually case insensitive. See https://stackoverflow.com/questions/7199039/file-paths-in-windows-environment-not-case-sensitive

Can you check if the file `C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/nodejs/bin/node` really exists?

FYI @laszlocsomor

**Comment by gregbown** [comment]
My apologies for wrongly jumping to a conclusion, perhaps working too late into the evening.
I adjusted post accordingly.

The correct segment is in bold:
**C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/nodejs**/bin/node.

There is no bin folder in the nodejs folder. The BUILD.bazel file in the nodejs folder may be indicating otherwise?
C:\Users\gbown\AppData\Local\Temp\_bazel_gbown\aFPn2GXi\external\nodejs\BUILD.bazel
`package(default_visibility = ["//visibility:public"])
exports_files([
  "bin/node",
  "bin/npm",
])
alias(name = "npm", actual = "bin/npm")`

**Comment by gregbown** [comment]
After updating to the latest upgrade rules_nodejs to [0.1.1](https://github.com/bazelbuild/rules_nodejs/commit/defc6449af919b7388e64467df27ceba95b4a33b) as per Alex's recommendations, it made it a little farther this time.  This may be a yarn - bazel integration issue?

I cant tell why it barks that yarn.sh is not a recognized command?
`C:\Users\gbown\Documents\bazel-angular\angular-bazel-example>bazel run @yarn//:yarn
INFO: Found 1 target...
Target @yarn//:yarn.sh up-to-date (nothing to build)
INFO: Elapsed time: 55.942s, Critical Path: 0.02s

INFO: Running command line: C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/yarn/yarn.sh
'\"C:/users/gbown/appdata/local/temp/_bazel_gbown/afpn2gxi/external/yarn/yarn.sh\"' is not recognized as an internal or external command,
operable program or batch file.
ERROR: Non-zero return code '1' from command: Process exited with status 1.`

Double checked my yarn install.  Note I have both the msi installer version and a global nodejs version and they are both 1.0.2
`C:\Windows\System32>yarn --version
1.0.2`

Also checked my environment path for windows:
C:\Program Files (x86)\Yarn\bin
Also tried:
C:\Program Files (x86)\Yarn\bin\
[This  post recommends an extra slash](https://github.com/yarnpkg/yarn/issues/1648)
Either way my system obviously can access it as shown by yarn --version

**Comment by gregbown** [comment]
Working through this with [Alex](https://github.com/alexeagle/angular-bazel-example/issues/4) seemed to arrive at an issue with [sass rules](https://github.com/bazelbuild/rules_sass) so I will take it up on that repo.

I appreciate all the sincere assistance from everyone at Google, thank you.
