### ISSUE TITLE
Support make substitution in repository_ctx

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3736]
Context: https://github.com/bazelbuild/rules_docker/issues/141

**Comment by ensonic** [comment]
What is missing here? The container rules such as container_push use ctx.template_action()
https://github.com/bazelbuild/rules_docker/blob/master/container/push.bzl#L59
Is the idea to add ctx.vars to the substitutions?

My use case is to be able to put this into my `.bazelrc`
```
build --action_env="GCP_REGISTRY=eu.gcr.io" --action_env="GCP_PROJECT=foo-123456"
```
and this in my `BUILD.bazel`:
```
container_push(
   name = "push-x",
   format = "Docker",
   image = ":x",
   registry = "$(GCP_REGISTRY)",
   repository = "$(GCP_PROJECT)/x",
)
```

**Comment by rltvty** [comment]
this works on `registry`, `repository` and `tag`.  Is there a way to do it on `image` as well?

```
docker_push(
    name = "docker_push",
    image = ":$(image)",
    registry = "$(registry)",
    repository = "$(repository)",
    tag = "$(tag)",
)
```

yields error: 
```
ERROR: /location/BUILD.bazel:42:1: in image attribute of container_push rule tool:docker_push: target 'tool:$(image)' does not exist. Since this rule was created by the macro 'docker_push', the error might have been caused by the macro implementation in /location/BUILD.bazel:42:1
```

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
