### ISSUE TITLE
In docs for FileType (which is deprecated), provide guidance on what to do instead

### ISSUE THREAD

**Issue by davidstanke** [bazelbuild/bazel#3738]
See: https://groups.google.com/forum/#!topic/bazel-discuss/hWPW1Vo4uCc

The docs for "[FileType](https://docs.bazel.build/versions/master/skylark/lib/FileType.html)" correctly list it as deprecated, but don't describe an alternative. Can we offer some guidance?

Here's the solution as written in that thread: 
"For allow_files, you should use plain lists of extensions. For filtering lists of files yourself, instead of FileType#filter the new way is with normal Skylark string methods (split/endswith/list comprehensions etc). I think those were the only use cases for FileType.
tools/build_defs/pkg/pkg.bzl in the main repository has some updated examples with tar_filetype.and deb_filetype."

**Comment by laurentlb** [comment]
Obsolete, I think
