### ISSUE TITLE
proto_library doesn't expose dependency information between source files

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3743]
I'm trying to write an aspect that generates code for protocol buffers in a language which requires that all source files form a DAG. That is not an issue when normally writing libraries as I can ensure that each library rule has one source file, and bazel enforces the DAG between rules. But proto_libraries can have multiple source files and there is no way in the analysis phase to determine the a topological ordering as it depends on the file content. This is forcing pushing down the determination of the ordering into my compilation logic and making it hard to reuse the standard compilation logic as the ordering is encoded in the FileDescriptorSet and not the generated source files (or at least in an easily parseable form).

I believe this is an issue for every language that wants to compile the generated sources of `.proto` files in a dag on a per `.proto` basis. There is no easy way I can see to fix this besides forcing `proto _library` rules to explicitly list the source files in topological order.

The primitives that I'm currently assuming for the language's compilation are:
```
# Generates the source files for all protos listed in the contents of the descriptor file.
generate_source_files(ctx, proto_provider, descriptor_file)

# Compiles 'source_file' with access to the files in deps
compile_file(ctx, source_file, deps)
```

**Comment by dslomov** [comment]
Interesting problem. Is the language is OCaml or F#? 

In any case, it the knowledge of how to generate code from .proto files for a specific language needs to be encapsulated in a proto compiler *targeting that language*. So the hypothetical ocaml_protoc should take in *all* .protos in one library and output *all* .ml files *along with* their correct ordering. 

Source file ordering is just not a part of proto language spec.

Closing this, but cc @cgrushko  for opinion as well.

**Comment by endobson** [comment]
The language that I'm using is Racket.

Having the action that generates the source files output the ordering is the workaround I came up with. But that doesn't solve the issue. The issue is that bazel handles every other part of the DAG, and cannot handle this part because the ordering constraints are only in the proto file and not the BUILD file. I believe other build systems can handle this because they do not have the strict phase ordering that bazel does and information can flow from outputs to the DAG.

In particular I now need a single action which can compile multiple output files. The language's bazel tool chain now needs to expose utilities for compiling multiple files in an 'execution phase' determined order. This is weird because I haven't seen another use case where conceptually separate actions are combined into one because of ordering/phasing issues.

**Comment by cgrushko** [comment]
Can you enforce one `.proto` file per `proto_library` rule? 
That's the best-practice inside Google too, if that helps.

**Comment by endobson** [comment]
No I cannot enforce it, as the aspect needs to work with all `proto_library` rules that it could encounter which includes ones in remote repos. Best practice isn't good enough, it needs to be actually enforced.
