### ISSUE TITLE
Visibility rule for workspace that imports me (//visible:external ?)

### ISSUE THREAD

**Issue by achew22** [bazelbuild/bazel#3744]
### Description of the problem / feature request / question:

When you attempt to depend on a binary produced in another repo it may have a visibility rule that prevents people in the project from depending on it but there doesn't appear to be a class of visibility where it is public to someone who loads the repo. For example [kubectl](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubectl/BUILD#L8).

### Minimal example:

`WORKSPACE`
```BUILD
git_repository(
    name = "io_bazel_rules_go",
    # https://github.com/kubernetes/kubernetes/blob/master/build/root/WORKSPACE#L5
    commit = "82483596ec203eb9c1849937636f4cbed83733eb",
    remote = "https://github.com/bazelbuild/rules_go.git",
)

load(
    "@io_bazel_rules_go//go:def.bzl",
    "go_repositories",
)

go_repositories()

git_repository(
    name = "com_github_kubernetes_kubernetes",
    remote = "https://github.com/kubernetes/kubernetes.git",
    tag = "v1.7.6",
)

http_archive(
    name = "io_kubernetes_build",
    sha256 = "ca8fa1ee0928220d77fcaa6bcf40a26c57800c024e21b08c8dd9cc8fbf910236",
    strip_prefix = "repo-infra-0aafaab9e158d3628804242c6a9c4dd3eb8bce1f",
    urls = ["https://github.com/kubernetes/repo-infra/archive/0aafaab9e158d3628804242c6a9c4dd3eb8bce1f.tar.gz"],
)
```

`BUILD`
```BUILD
sh_binary(
    name = "demo",
    srcs = ["demo.sh"],
    # This target is clearly intended for public consumption but there doesn't exist a visibility rule that allows that.
    data = ["@com_github_kubernetes_kubernetes//cmd/kubectl"],
)
```

### Environment info
* Operating System: Linux
* Bazel version (output of `bazel info release`):
release 0.5.4

###  Have you found anything relevant by searching the web?

Not really. The docs on [bazel.build](https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes) say this:

>There are five forms (and one temporary form) a visibility label can take:
>
>["//visibility:public"]: Anyone can use this rule.
>["//visibility:private"]: Only rules in this package can use this rule. Rules in javatests/foo/bar can always use rules in java/foo/bar.
>["//some/package:__pkg__", "//other/package:__pkg__"]: Only rules in some/package and other/package (defined in some/package/BUILD and other/package/BUILD) have access to this rule. Note that sub-packages do not have access to the rule; for example, //some/package/foo:bar or >//other/package/testing:bla wouldn't have access. __pkg__ is a special target and must be used verbatim. It represents all of the rules in the package.
>["//project:__subpackages__", "//other:__subpackages__"]: Only rules in packages project or other or in >one of their sub-packages have access to this rule. For example, //project:rule, //project/library:lib or >//other/testing/internal:munge are allowed to depend on this rule (but not //independent:evil)
>["//some/package:my_package_group"]: A package group is a named set of package names. Package groups can also grant access rights to entire subtrees, e.g.//myproj/....
>The visibility specifications of //visibility:public and //visibility:private can not be combined with any other visibility specifications. A visibility specification may contain a combination of package labels (i.e. //foo:__pkg__) and package_groups.
>
>If a rule does not specify the visibility attribute, the default_visibility attribute of the package statement in the BUILD file containing the rule is used (except exports_files).
>
>If the default visibility for the package is not specified, the rule is private.

Which makes me think it isn't possible. Maybe this is a documentation bug.

**Comment by mattmoor** [comment]
This sounds like `//visibility:public` to me.  I'm not sure why you'd only make something visible to folks outside of your repo?

@ixdy FYI

**Comment by ixdy** [comment]
yeah, this is a weird artifact of some of the work we're doing in the kubernetes repo to break up dependency chains. that discussion probably belongs in the kubernetes repo proper.

**Comment by mhlopko** [comment]
@damienmg for qualified decision, but my humble opinion is that this will be used very little, so I'd just close this issue as won't fix. Damien?

**Comment by damienmg** [comment]
Agree.

Sorry that is not something we want to have in Bazel.

**Comment by damienmg** [comment]
to be more precise: `//visibility:public` is the way to expose a target for other repository. We do not intend to have a visilibility that expose a target only for external repositories (and not for the main one).

**Comment by ixdy** [comment]
and to further close the loop: `//cmd/kubectl` in kubernetes is now marked `//visibility:public`.
