### ISSUE TITLE
Proto Descriptor Set file extension incompatible with gCloud

### ISSUE THREAD

**Issue by jackwootton** [bazelbuild/bazel#3748]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

[Proto Buffers in Bazel](https://blog.bazel.build/2017/02/27/protocol-buffers.html) states that when compiled on the command-line, a `proto_library` creates a descriptor set for the messages it srcs. I'm actually using a thin wrapper, `py_proto_library`, around `proto_library` - [the recommended approach when [Building gRPC services with bazel and rules_protobuf](https://grpc.io/blog/bazel_rules_protobuf).

However, the resulting descriptor has the file extension `.descriptor_set` - which is incompatible with Google Cloud command line interface. Google's documentation for [Deploying a GRPC API configuration](
https://cloud.google.com/endpoints/docs/grpc/deploy_grpc_api#deploy_configuration) uses a proto descriptor:

`gcloud service-management deploy out.pb api_config.yaml`

Using the descriptor generated using py_proto_library, the same command would be

`gcloud service-management deploy out.descriptor_set api_config.yaml`

...which fails wth:

`Could not determine the content type of file [bazel-genfiles/proto/out.descriptor_set]. Supported extensions are .json .yaml .yml .pb. and .descriptor`

### If possible, provide a minimal example to reproduce the problem:

```
py_proto_compile(
    name = "out",
    with_grpc = True,
    protos = ["my_api.proto"],
)

bazel build :out
```

### Environment info
* Operating System: Mac OS 10.12

* Bazel version (output of `bazel info release`): 0.5.2

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
