### ISSUE TITLE
Justification for Disallowing Tabs

### ISSUE THREAD

**Issue by EddieRingle** [bazelbuild/bazel#3749]
It seems that https://github.com/bazelbuild/bazel/commit/7a6ec8e9ab2a0f9c60c9394831619335d9ed5760 removed the ability to use the tab character in `.bzl` files, but I'm unable to find any sort of justification for this change.

On the surface it seems rather silly considering the commit still counts it after marking it as an error. Why not disallow files that mix the use of tabs and spaces for indentation, instead?

**Comment by laurentlb** [comment]
There are multiple ways to support tabs:

1. In Python 2 (and previously in Skylark), tabs are converted to spaces. 1 tab = 8 spaces (or less, if there are spaces in front). This behavior is error-prone and we wanted to remove it.

2. Allow tabs and spaces in the same file, as long as they are in different blocks. This is what Python 3 does.

3. Forbid files that contain both spaces and tabs.

The vast majority of Bazel users was using spaces for indentation. We thought it was easier to just forbid tabulations. It's easier to be stricter at the beginning (we can always relax the constraints later if needed). I also think it's good to have consistency. In the future, we expect everyone to use the same code formatter (we'll work on it) and not worry about spaces and indentation anymore.

We can leave this issue open as a feature request, but it's not clear to me what's the benefit of implementing it.
