### ISSUE TITLE
Bazel CI: wrong android version is preventing Unix tests being green

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#3755]
http://ci.bazel.io/blue/rest/organizations/jenkins/pipelines/bazel-tests/runs/1033/nodes/27/steps/287/log/?start=0
All tests passed, but still has an error:
```
ERROR: /home/ci/workspace/bazel-tests-node=ubuntu_16.04-x86_64/src/test/java/com/google/devtools/build/android/desugar/BUILD:19:1: no such target '@androidsdk//:platforms/android-25/android.jar': target 'platforms/android-25/android.jar' not declared in package '' (did you mean 'platforms/android-24/android.jar'?) defined by /home/ci/.cache/bazel/_bazel_ci/f576cbcb4b5fe364bb084077db8fda2f/external/androidsdk/BUILD.bazel and referenced by '//src/test/java/com/google/devtools/build/android/desugar:android_jar_for_testing'.
```
Introduced in https://github.com/bazelbuild/bazel/commit/d60e0d02eb56e27f98086d764c6d9f88898d920d

@aj-michael Should we just change `@androidsdk//:platforms/android-25/android.jar` to `@androidsdk//:platforms/android-24/android.jar` ?

**Comment by meteorcloudy** [comment]
Oh, duplicated with #3754

**Comment by aj-michael** [comment]
Yes, we should just change that path. Preparing a CL now.
