### ISSUE TITLE
Custom java_toolchain conflicting with protobuf's :java_toolchain

### ISSUE THREAD

**Issue by ejona86** [bazelbuild/bazel#3757]
We (gRPC) have a user that is using a custom java_toolchain that fails the build on warnings. The Bazel protobuf integration compiles google/protobuf from source, which currently triggers some warnings. So the user is unable to use their java_toolchain with gRPC/protobuf and was wanting gRPC/protobuf to use pre-built JARs instead of from-source compilation.

How should first-class Java dependencies be handled in Bazel?

More information can be found at https://github.com/grpc/grpc-java/issues/3412

CC @pgr0ss @buchgr @cgrushko

**Comment by cgrushko** [comment]
> Bazel protobuf integration compiles google/protobuf from source

Not exactly - it takes whatever label you give it in `--proto_compiler` and "builds" it. If it's a precompiled binary there won't be any compilation. 

So a trivial solution is to build the proto compiler (either with Bazel or whatever) and check-in the binary.
The harder solution is to complain to github.com/google/protobuf.

I'm unaware of a mechanism to suppress warnings from external repositories, though there might be; perhaps file a separate issue about that?

**Comment by mhlopko** [comment]
Did anybody talk to the protobuf people?

**Comment by rockwotj** [comment]
@cgrushko `--proto_compiler` doesn't actually fix the problem due to https://github.com/bazelbuild/bazel/issues/8485

**Comment by comius** [comment]
I created a reproduction described in grpc/grpc-java#3412, here: https://github.com/comius/bazel_issue_3757.

It compiles without any warnings on bazel 3.7.2.
