### ISSUE TITLE
Bazel docs are recommending unsupported use of github .tar.gz files

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3762]
Github provides archive .tar.gz files for commits but makes no promises to checksum stability. This broke a bunch of bazel users recently.

https://github.com/libgit2/libgit2/issues/4343#issuecomment-328631745
https://github.com/tensorflow/tensorflow/issues/12984

The docs for git_archive recommend using http_archive with paths to these .tar.gz files.
https://docs.bazel.build/versions/master/be/workspace.html#git_repository

**Comment by laszlocsomor** [comment]
Thanks for reporting this bug! Do you know what's the correct approach?

**Comment by endobson** [comment]
Nope. I just had to deal with the issue yesterday and I used the workaround of changing all my sha256s in all my repositories, which works if github doesn't change their code again.

**Comment by laszlocsomor** [comment]
Thanks for pointing it out anyway!

I just looked at the Bazel docs and they say:

>  ## http_archive
>
> (...)
> It supports Zip-formatted archives (with the .zip extension) and tarballs (.tar.gz and .tgz extensions).

(https://docs.bazel.build/versions/master/be/workspace.html#http_archive)

Is this what you were referring to? I don't read this as recommending to use GitHub tarballs specifically.

**Comment by endobson** [comment]
No I'm referring to the section I linked about git_repository and moving off of it to http_archive.


> Many git repository hosts serve tarballs of the repository, so depend on those if possible. For GitHub, this takes the form:
> ```
> http_archive(
>     name = "",
>     urls = ["https://github.com/<user>/<repo>/archive/<commit or tag>.tar.gz"],
> )
> ```

While this example doesn't use a sha256, the section is saying that one of the reasons that http_archive should be used is that it supports sha256.

> * Security - http_archive allows a sha256 to be specified, which ensures that the downloaded code is exactly what was expected.

(I also don't think this is a useful bullet and filed https://github.com/bazelbuild/bazel/issues/3655 for that).

**Comment by jin** [comment]
This snippet doesn't seem to be on the docs anymore, since git_repository has been rewritten in Starlark. 

https://docs.bazel.build/versions/master/repo/git.html
