### ISSUE TITLE
Add support to read http headers from settings.xml for native/skylark maven_rules in bazel.

### ISSUE THREAD

**Issue by yadav** [bazelbuild/bazel#3764]
### Description of the problem / feature request / question:
Add support to read http headers from settings.xml for native/skylark maven_rules in bazel.

### If possible, provide a minimal example to reproduce the problem:
Here is the settings.xml we are using:

```
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                          https://maven.apache.org/xsd/settings-1.0.0.xsd">
    <localRepository/>
    <interactiveMode/>
    <usePluginRegistry/>
    <offline/>
    <pluginGroups/>
    <servers>
        <server>
            <id>gateway</id>
            <configuration>
                <httpHeaders>
                    <property>
                        <name>Authorization</name>
                        <value>Basic abc*****</value>
                    </property>
                </httpHeaders>
            </configuration>
        </server>
    </servers>
    <mirrors/>
    <proxies/>
    <profiles/>
    <activeProfiles/>
</settings>

```
### Environment info
* Operating System:
 Mac/Ubuntu

* Bazel version (output of `bazel info release`):
release 0.5.4-homebrew

**Comment by jin** [comment]
Hi @yadav, I'm trying to reproduce this error locally. The Skylark Maven rules should be able to read and apply the user provided settings.xml file, since it uses mvn directly. Will follow up when I have updates.

**Comment by jin** [comment]
Related #1410

**Comment by dslomov** [comment]
AFAIU, skylark maven rules are using settings.xml, so they should be used if that behavior is desired. lmk if I am wrong.
