### ISSUE TITLE
Please let repository_ctx.execute accept a string for subprocess stdin

### ISSUE THREAD

**Issue by jmillikin** [bazelbuild/bazel#3767]
[`repository_ctx.execute`](https://docs.bazel.build/versions/master/skylark/lib/repository_ctx.html#execute) doesn't have any way to pass input data to its subprocess. This can be worked around using `sh -c` to construct a pipe, but that approach has all sorts of awful issues related to quoting.

Please add a `stdin` parameter to `repository_ctx.execute`, defaulting to the empty string, which can be used to supply the process with input.

**Comment by damienmg** [comment]
Reasonable request.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
