### ISSUE TITLE
docs.bazel.build fails to show docs on Chrome on Ubuntu

### ISSUE THREAD

**Issue by pboothe** [bazelbuild/bazel#3776]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

https://docs.bazel.build renders without text on Chrome on Ubuntu

### Environment info
* Operating System:

`chrome:version` shows: `61.0.3163.91 (Official Build) (64-bit)`

`uname -a` returns:
`Linux deletedhostname 4.4.0-89-generic #112~14.04.1-Ubuntu SMP Tue Aug 1 22:08:32 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).
https://docs.bazel.build/versions/master/install-ubuntu.html renders as 
https://photos.app.goo.gl/3BSjV6pMGw4Vppca2
(and yes, I did restart my browser to make sure it wasn't that :P)

**Comment by pboothe** [comment]
Whoops! It turns out I can't read the docs and the header wasn't all that was on the page.  Actual bug is: all content renders below the fold on smaller screen widths.

**Comment by damienmg** [comment]
/cc @davidzchen @michelleirvine @spomorski fyi

Indeed at some screen width before it goes into mobile layout where the content moves below the menu but the menu is still big. We should probably just have 2 layout.

Repro: reduce the size of your browser up to the weird point.

**Comment by damienmg** [comment]
(workaround: reduce the size of the browser or the font size)

**Comment by jin** [comment]
I can't seem to repro this anymore. Please reopen if you're running into the same issue.
