### ISSUE TITLE
aar_import should propagate proguard specs

### ISSUE THREAD

**Issue by aj-michael** [bazelbuild/bazel#3778]
AAR files may contain a file called `proguard.txt` at the top level. These should be propagated up to the android_binary level and concatenated if a proguarded build is requested. This is especially important for the Android Support Libraries.

**Comment by cpsauer** [comment]
Should this have been closed by #12749? 

(Happened across these while searching after running into the bug--fix still unreleased, I think, right?)

**Comment by cpsauer** [comment]
^ tagging also @benjaminRomano and @philwo

**Comment by benjaminRomano** [comment]
Yes, this should be resolved by https://github.com/bazelbuild/bazel/pull/12749. @cpsauer maybe try asking in https://github.com/bazelbuild/bazel/issues/13558 to get this cherrypicked in. My change is self-contained so it should be straightforward.

**Comment by cpsauer** [comment]
Done. Thanks again, guys.

I don't have the power to close the issue either--could I ask someone who can to do so? @philwo?
