### ISSUE TITLE
Gerrit Code Review cannot be built from HEAD

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#3782]
I am seeing this breakage in rules_closure when trying to build
Gerrit master (0fb1572ce77314fc9117e51fcbfb8f8884409b97) from this Bazel commit: 486206012a664ecb20bdb196a681efc9a9825049:

```
$ bazel build gerrit
ERROR: /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/io_bazel_rules_closure/java/io/bazel/rules/closure/BUILD:62:1: every rule of type _gensrcjar implicitly depends upon the target '@com_google_protobuf_protoc//:com_google_protobuf_protoc', but this target could not be found because of: no such package '@com_google_protobuf_protoc//': Cannot convert parameter 'url' to type string or sequence of strings, in method download_and_extract(List, string, string, string, string) of 'repository_ctx'.
ERROR: Analysis of target '//:gerrit' failed; build aborted: Loading failed.
INFO: Elapsed time: 9.314s
```

We are using the last released `rules_closure` version:

```
http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "25f5399f18d8bf9ce435f85c6bbf671ec4820bc4396b3022cc5dc4bc66303609",
    strip_prefix = "rules_closure-0.4.2",
    url = "https://bazel-mirror.storage.googleapis.com/github.com/bazelbuild/rules_closure/archive/0.4.2.tar.gz",  # 2017-08-29
)
```

**Comment by davido** [comment]
//CC @damienmg @dslomov 

Bisecting the breakage and the first bad commit is:

  17214ac78 Check parameter types for methods when multiple types are allowed.

**Comment by damienmg** [comment]
Yes we have a bunch of breakage due to that change, I think we'll roll it
back tomorrow morning. See

/cc @laszlocsomor

**Comment by davido** [comment]
@damienmg 

Thanks. This is the very first time, since migration from Buck to Bazel, that Gerrit Code Review (better to say rules_closire, that Gerrit depends upon) can't be built form HEAD.

**Question**: How comes, that Bazel CI hasn't catched this regression? It's green: http://ci.bazel.io/job/gerrit.

In the end it was the reason to set it up, to ensure, that something like that can't ever happen: Gerrit can't be bult from the head?

**Comment by damienmg** [comment]
This was caught, the build from nightly is there:
http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/nightly/Downstream_projects/

Gerrit is red on last nightly. The job you are looking is the build with
Bazel latest. I actually commented earlier on the corresponding commit.

**Comment by davido** [comment]
@damienmg Cool, so why  this change wasn't rollbacked already, after you have noticed, that Gerrit isbroken? How come, that I have spent ca. 30 min. investigation to bisect the breakage?

**Comment by damienmg** [comment]
Because I found out right before leaving work, as I was investigating
another breakage. Generally those things happen pretty regularly, it is
just the first time it touch Gerrit I believe.

We do not guarantee that head is always green but we try to keep it as
green as possible (so we can easily cut a new release).

**Comment by dslomov** [comment]
The commit went in yesterday, and breakage was discovered in the nightly run.
It takes some time to analyze the nightly runs and bisect.
I am sorry @davido that we are not working fast enough for your high standards, but this is Bazel at HEAD (not a released version at Bazel). Literally direct off the bleeding edge. Expect breakages.
