### ISSUE TITLE
The behavior of `--flaky_test_attempts` is surprising and suboptimal

### ISSUE THREAD

**Issue by jasharpe** [bazelbuild/bazel#3783]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

The behavior of `--flaky_test_attempts` is surprising and suboptimal.

How it actually behaves, I believe:

- If you use `--flaky_test_attempts=N`, then Bazel will run the test *up to* N times.
- If the test fails every time, then the test is marked `FAILED`.
- If the test passes the first time, then the test is marked `PASSED` and remaining attempts are skipped.
- If the test passes, but not the first time, then the test is marked `FLAKY` and remaining attempts are skipped.

I illustrate why this is surprising and bad with an example. This test will pass ~50% of the time:

    NUMBER="$(grep -m1 -ao '[0-1]' /dev/urandom | head -n1)"
    if [[ "$NUMBER" -eq 1 ]]; then
      echo "fail"
      exit 1
    else
      exit 0
    fi

Use this BUILD file:

    sh_test(
        name = "flaky_test",
        srcs = ["flaky_test.sh"],
    )

Using this command `bazel test :flaky_test --flaky_test_attempts=10`, I would *expect* that the test should only pass with probability (1/2)^10 (so, essentially never), should fail with the same probability, and should be marked flaky for the vast majority of runs. However, in practice, this test is marked `PASSED` with ~50% probability (because of the behavior described above)!

How I expect it to work:

- If you use `--flaky_test_attempts=N`, then Bazel will run the test *up to* N times.
- If all the runs are passed, the test is marked `PASSED`.
- If all the runs are failed, the test is marked `FAILED`.
- If at any point there has been a passed *and* a failing run, the test is marked `FLAKY` and the remaining runs may be skipped.

Importantly, if a test has probability P(flaky) of failing when it should be passing, then the probability that I detect a flake should be P(flaky)^flaky_test_attempts, which it currently is not.

Note that afaik `--runs_per_test` has behavior similar to what I describe, but `--flaky_test_attempts` should still be fixed because:

- `--flaky_test_attempts` is what I found when looking for a strategy for dealing with flaky tests and was not as effective as I'd hoped.
- The `--flaky_test_attempts` strategy I describe is how the `flaky = True` test property works, but isn't as effective as it could be at its job.

### If possible, provide a minimal example to reproduce the problem:

See the example above.

### Environment info
* Operating System: Ubuntu

* Bazel version (output of `bazel info release`): 0.5.4

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by damienmg** [comment]
> How it actually behaves, I believe:
> 
> If you use --flaky_test_attempts=N, then Bazel will run the test up to N times.
> If the test fails every time, then the test is marked FAILED.
> If the test passes the first time, then the test is marked PASSED and remaining attempts are skipped.
> If the test passes, but not the first time, then the test is marked FLAKY and remaining attempts are skipped.

And later

> How I expect it to work:
> 
> If you use --flaky_test_attempts=N, then Bazel will run the test up to N times.
> If all the runs are passed, the test is marked PASSED.
> If all the runs are failed, the test is marked FAILED.
> If at any point there has been a passed and a failing run, the test is marked FLAKY and the remaining runs may be skipped.

So let's summarize you expect it to work with some more general constraint it has now? 

Because point 1 in both is the same, point 2 in the first is point 3 in the second, point 3 in the first is a specialization of point 2 in the second. point 4 is the same except the part about skipping is optional in your expected behavior.

You expect that your test only pass with a probability of 2^-10 but the goal of flaky test is to do exactly the contrary: you want a test to pass even though sometime it might fail because of race condition or whatever (so here you want a probably of 2^10 that it fails). Generally it is a very bad idea to rely on flaky tests but it might reduce the pain while investigating the source of flakiness.

**Comment by jasharpe** [comment]
Yeah, after thinking about it, I'm just wrong about what `--flaky_test_attempts` is for. It's trying as hard as possible to get at least 1 pass in a minimal number of attempts. This makes sense if your goal is papering over failures.

My mistake was in trying to use it to detect flakes. For that, `--runs_per_test` is much better. (There's also a `--runs_per_test_detects_flakes` flag that I'm unsure of the behavior of.)

I guess the actual issue is just the confusion about the scenarios in which its appropriate to use each flag. It's unfortunate that `bazel help test` just gives a list of flags, but usually no descriptions.

**Comment by damienmg** [comment]
Thanks! For your information, `bazel help --long test` should gives the
description of each flags.
