### ISSUE TITLE
ERROR: java.io.IOException: Could not read the crosstool configuration file

### ISSUE THREAD

**Issue by EvilMudkip** [bazelbuild/bazel#3784]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

Hi guys,

so I've been installing Magenta and Bazel and when I type:
bazel test //magenta/...
I get an ERROR message:

ERROR: java.io.IOException: Could not read the crosstool configuration file 'CROSSTOOL file C:/users/fei/appdata/local/temp/_bazel_fei/uyk23a1f/external/local_config_cc/CROSSTOOL', because of a parser error (289:987: Expected identifier. Found '%').

and then followed by:

ERROR: Couldn't start the build. Unable to run tests.

Can anyone help? :'(

### If possible, provide a minimal example to reproduce the problem:

Any build code.
`bazel test //magenta/...` or

`bazel run //magenta/models/melody_rnn:melody_rnn_generate -- --config=...`

### Environment info
* Operating System:
Windows 10

* Bazel version (output of `bazel info release`):
release 0.5.4

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by damienmg** [comment]
@meteorcloudy: can you TAL, C++ error on windows.

**Comment by meteorcloudy** [comment]
> ERROR: java.io.IOException: Could not read the crosstool configuration file 'CROSSTOOL file C:/users/fei/appdata/local/temp/_bazel_fei/uyk23a1f/external/local_config_cc/CROSSTOOL', because of a parser error (289:987: Expected identifier. Found '%').
@EvilMudkip 
Looks like the CROSSTOOL file content is wrong, are you using a custom CROSSTOOL?
Can you show me your bazelrc file?

**Comment by EvilMudkip** [comment]
@meteorcloudy

I'm not using a custom CROSSTOOL file. I will attach the bazelrc file here on Monday.

Maybe I should try reinstall Bazel? I installed using the chocolatey, will try using binary.

**Comment by meteorcloudy** [comment]
@EvilMudkip Just a reminder, TensorFlow is still lack of some functionalities on Windows, it's very possible that some tests are going to fail.

If you are not using a custom CROSSTOOL, can you also attach `C:/users/fei/appdata/local/temp/_bazel_fei/uyk23a1f/external/local_config_cc/CROSSTOOL`?

**Comment by EvilMudkip** [comment]
[CROSSTOOL.zip](https://github.com/bazelbuild/bazel/files/1327280/CROSSTOOL.zip)

**Comment by EvilMudkip** [comment]
[bazel.zip](https://github.com/bazelbuild/bazel/files/1327282/bazel.zip)

**Comment by EvilMudkip** [comment]
I've uploaded CROSSTOOL file and bazel.rc file as ZIP files. Please help, I'm still getting the same errors after uninstalling and reinstalling Bazel. Thanks!

**Comment by EvilMudkip** [comment]
@meteorcloudy Thanks.

**Comment by meteorcloudy** [comment]
@EvilMudkip From the CROSSTOOL file, it looks like you have a `"%%IFORT_COMPILER15%%\\redist\\ia32\\mkl;%%IFORT_COMPILER15%%\\redist\\intel64\\mkl"` in your PATH. 
The `"` corrupted `PATH`  environment variable, like 
`PATH="...;"%%IFORT_COMPILER15%%\\redist\\ia32\\mkl;%%IFORT_COMPILER15%%\\redist\\intel64\\mkl";..."`

Bazel should have escaped the quotes, I'll send a fix for it.
In the mean time, you can remove the directory from your PATH as a workaround.

**Comment by EvilMudkip** [comment]
@meteorcloudy I have removed the path from the environment variables, but the same error still comes up... I've attached a screenshot:

![capture](https://user-images.githubusercontent.com/31815007/30797515-ec906566-a208-11e7-969c-06b8cc2f18e1.PNG)

**Comment by meteorcloudy** [comment]
@EvilMudkip Can you run `bazel clean` first?

**Comment by EvilMudkip** [comment]
@meteorcloudy Yes, I ran it but the same error still comes up...

![capture](https://user-images.githubusercontent.com/31815007/30797638-4ba94d38-a209-11e7-9087-fe61470c0316.PNG)

**Comment by meteorcloudy** [comment]
@EvilMudkip Oh, sorry, please try `bazel clean --expunge`?

**Comment by meteorcloudy** [comment]
And this problem is not going to happen with Bazel 0.6, because it sanitized the `PATH`  environment variable.

**Comment by EvilMudkip** [comment]
@meteorcloudy I see... However the same problem still shows up after I used `bazel clean --expunge`

![capture](https://user-images.githubusercontent.com/31815007/30798210-4c3ac482-a20b-11e7-9a49-be8132d5d59c.PNG)

**Comment by meteorcloudy** [comment]
@EvilMudkip , well, that's strange. Can you show me your `PATH`?
And, if it keeps failing, can you try our release candidate of 0.6? 
https://storage.googleapis.com/bazel/0.6.0/rc3/bazel-0.6.0rc3-windows-x86_64.exe

**Comment by EvilMudkip** [comment]
@meteorcloudy I've attached an image for my paths... And I'll also try install Bazel 0.6.

![capture](https://user-images.githubusercontent.com/31815007/30799092-451ffca0-a20e-11e7-85c0-2d119d083265.PNG)

**Comment by meteorcloudy** [comment]
The PATH looks good, did you restart your console after updating it?

**Comment by EvilMudkip** [comment]
@meteorcloudy Yes I did restart. I have installed Bazel 0.6, and the error no longer shows up. Although, there are new problems that prevent the test from running smoothly. I will close this thread. Thanks @meteorcloudy , really appreciate it.

Link to the new problem: [https://github.com/bazelbuild/bazel/issues/3803](url)
