### ISSUE TITLE
A configured XCode should not be required for a pure java project

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#3790]
Steps to reproduce:

* Create a pure Java project that can be built with bazel
* Upgrade or freshly install XCode. Do not run it.
* `bazel build //...:all`

Expected result:

* Java project builds incredibly quickly

Actual result:

```
bazel build //...:all
...............
ERROR: /private/var/tmp/_bazel_shs/829cb35a81208dafe6c911f381579e04/external/local_config_cc/BUILD:49:5: in apple_cc_toolchain rule @local_config_cc//:cc-compiler-darwin_x86_64: Xcode version must be specified to use an Apple CROSSTOOL.
ERROR: Analysis of target '//javatests/org/infalible/selenium/remote/session:AllTests' failed; build aborted.
INFO: Elapsed time: 1.582s
ERROR: Couldn't start the build. Unable to run tests.
``

**Comment by shs96c** [comment]
`bazel clean --expunge` appears to "fix" the problem.

**Comment by mhlopko** [comment]
Also reported at https://stackoverflow.com/questions/46327893/bazel-xcode-version-must-be-specified

**Comment by c-parsons** [comment]
Before you installed the pure Java project -- did you have Xcode installed on your system?

**Comment by shs96c** [comment]
I had an old version of Xcode, did java builds with bazel, upgraded Xcode (without running it), and started to see this error.

**Comment by c-parsons** [comment]
ack -- thanks.
Indeed, right now updating / reinstalling xcode typically requires a `blaze clean --expunge` -- this is terrible, but a known issue. We'll be looking into better solutions over the next few weeks.

**Comment by hlopko** [comment]
As far as I know, C++ toolchain is no longer needed as implicit dependency of anything that Bazel builds.

There are still tools written in C++ that are used to build code in other languages (for example is protobuf compiler, which is written in C++ and is used to generate Java protos).

If you see that a C++ toolchain is required and you believe it shouldn't be, it's a bug. Please file a separate issue for that.

Thank you all!
