### ISSUE TITLE
<nightly:bazel-tests> //src/test/shell/bazel:remote_{sandboxing_}execution_test is failing with Bazel @ HEAD

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3793]
From http://ci.bazel.io/blue/organizations/jenkins/Global%2Fbazel-tests/detail/bazel-tests/263/tests/

All the test are failing with the following error:
```
Error
Timed out waiting for remote worker to start.
Stacktrace
-- Test log: -----------------------------------------------------------
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: io/grpc/BindableService
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: io.grpc.BindableService
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
------------------------------------------------------------------------
test_cc_test FAILED: Timed out waiting for remote worker to start. .
/home/ci/.cache/bazel/_bazel_ci/a662063314b9ed68d0536f44c93482c1/bazel-sandbox/5779205525017255812/execroot/io_bazel/bazel-out/local-fastbuild/bin/src/test/shell/bazel/remote_execution_test.runfiles/io_bazel/src/test/shell/bazel/remote_execution_test:48: in call to set_up
```

**Comment by ulfjack** [comment]
I can't find the error message in Jenkin's UI, which also isn't loading for me right now.

**Comment by damienmg** [comment]
The full error message for each failing test is above (the link shows plenty of those failure), do you need more?

**Comment by ulfjack** [comment]
I need all the help I can get, because that error message is impossible to happen. I don't see how we can not find a class that was present during the build, since without the class, the test couldn't have been built.

I may actually need to ssh into the machine and reproduce the problem manually, because there's no way this reproduces in a clean client on my machine (full disclosure: I haven't even tried, but I can't imagine that it will reproduce).

**Comment by damienmg** [comment]
So it definitely not happens all the time, latest occurence: http://ci.bazel.io/job/Global/job/bazel-tests/282/

On the pipeline view, we can find the log of the linux worker, for the occurence I found: http://ci.bazel.io/blue/rest/organizations/jenkins/pipelines/Global/pipelines/bazel-tests/runs/282/nodes/26/log/?start=0

**Comment by damienmg** [comment]
(sorry I hit enter too fast, I still looking for other logs)

**Comment by damienmg** [comment]
Actually that was all the log, all happen on the same machine: ubuntu_14.04-x86_64-3

**Comment by ulfjack** [comment]
My hypothesis is that there's a bad file in the output tree and bazel thinks it's up to date so it doesn't get regenerated.

**Comment by damienmg** [comment]
Sounds reasonable, maybe we should just zip the output base and the
workspace and then run a Bazel clean?

**Comment by damienmg** [comment]
FWIW it is happening again with latest this time: https://ci.bazel.io/blue/rest/organizations/jenkins/pipelines/bazel-tests/runs/1123/nodes/30/steps/348/log/?start=0

**Comment by damienmg** [comment]
This is happening on all mac worker. I suspect it was trigger by the update to bazel 0.7

**Comment by damienmg** [comment]
I zipped the output base before and after a clean, it is on darwin 8 slave. And now I am doing a clean on all slaves.

**Comment by tomlu** [comment]
Here's another failure from the presubmit: https://ci.bazel.io/blue/organizations/jenkins/CR%2Fbazel-tests-remote/detail/bazel-tests-remote/194/pipeline/

**Comment by hchauvin** [comment]
What is the status on this?  I stumbled upon this developing locally.

**Comment by ulfjack** [comment]
No progress. I still have no idea what could be wrong - maybe it's related to the runfiles issue we had a few weeks ago?

**Comment by jin** [comment]
Is this still happening? Jenkins is no more so the links do not point to the runs anymore. Please reopen with a Buildkite link and/or repro setup if this is still happening.
