### ISSUE TITLE
<nightly:bazel-tests> desugar test are failing on Windows

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3794]
From http://ci.bazel.io/blue/organizations/jenkins/Global%2Fbazel-tests/detail/bazel-tests/263/tests/

Classical error:
```
Error
exited with error code 1
Standard Output
Error: Could not find or load main class '-Dexpected.strategy=com.google.devtools.build.android.desugar.runtime.ThrowableExtension$MimicDesugaringStrategy'
```

Failing tests:
src/test/java/com/google/devtools/build/android/desugar/TryWithResourcesRewriterUnitTestWithMimicStrategy.exe
src/test/java/com/google/devtools/build/android/desugar/TryWithResourcesRewriterUnitTestWithReuseStrategy.exe
src/test/java/com/google/devtools/build/android/desugar/runtime/ThrowableExtensionTestWithMimicDesugaringStrategy.exe
src/test/java/com/google/devtools/build/android/desugar/runtime/ThrowableExtensionTestWithNullDesugaringStrategy.exe
src/test/java/com/google/devtools/build/android/desugar/runtime/ThrowableExtensionTestWithReuseDesugaringStrategy.exe

**Comment by aj-michael** [comment]
this is strange. the test targets set something like this:

```
jvm_flags = [
    "-Dfortest.simulated.android.sdk_int=18",
    "'-Dexpected.strategy=com.google.devtools.build.android.desugar.runtime.ThrowableExtension$$MimicDesugaringStrategy'",
],
test_class = "com.google.devtools.build.android.desugar.TryWithResourcesRewriterTest",
```

note the extra single quote around -Dexpected_strategy=...

So, Windows is interpreting that as the main class instead of a flag

**Comment by aj-michael** [comment]
This code hasn't changed recently, and it is passing in our internal CI environment on Windows. We can't just get rid of the single quote, because there is a "$" inside of it.

The only change to this since the test was open sourced was 088f6113007d1a341893d915a87b93a4aed9898e. Laszlo, do you know if using test_suite is changing how jvm_flags are being parsed?
