### ISSUE TITLE
experimental_ui does not display streaming curses test output while runing tests

### ISSUE THREAD

**Issue by ddouglas87** [bazelbuild/bazel#3799]
### Description of the problem / feature request / question:

When running a command like:  `bazel test ... --test_output=streamed --experimental_ui=yes --curses=yes`

Output is only printed at the end of the test.  While the test is running it displays `6s processwrapper-sandbox` or `2s linux-sandbox` depending on the system.

But: `bazel test ... --test_output=streamed --experimental_ui=no` and curses output is printed while tests are running.

### If possible, provide a minimal example to reproduce the problem:

An example line of code might look like: `std::cout << "\r" << "Progress: " << progress << "%" << std::flush;`

And with `--experiemental_ui=no` tests successfully print something like `Progress: 67%`.

### Environment info
* Operating System:
One Mint 18.2 /w kernel `4.10.0-33-generic`
Another Debian Unstable, kernel: `4.12.0-1-amd64`

* gcc version `7.2.0`.
* Google Test `release-1.8.0`.

* Bazel version (output of `bazel info release`):
Both version 0.5.4.

### Anything else, information or logs or outputs that would be helpful?

~/.bazelrc
`test --test_output=all --verbose_test_summary --test_verbose_timeout_warnings --show_progress_rate_limit=-1 --action_env="GTEST_COLOR=1" --copt="-fdiagnostics-color" --copt="-fmessage-length=110" --test_output=streamed --experimental_ui=no`

**Comment by aehlig** [comment]
I can't reproduce the report. If I take a simple example,

```
#include <stdio.h>
#include <unistd.h>

int main(int argc, char **argv) {
    printf("Hello world.\n");
    fflush(stdout); sleep(3);
    printf("Second line.\n");
    fflush(stdout); sleep(3);
    printf("Third line.\n");
    fflush(stdout); sleep(3);
}
```

with empty `WORKSPACE` and `BUILD`

```
cc_test(
  name="stream",
  srcs=["stream.c"],
)
```

I do see the streamed output, even with the experimental UI; see the [`script(1)` of the invocation](http://www.linta.de/~aehlig/download/uucp/20170926-stream.script). I used the `--show_timestamps` (implicitly from my `.bazelrc`), so you can see when a status line was updated and which output was present at that time.

Note, however, that below the streamed output, there still is the status bar. Hence, in the middle of the invocation, it looks like

```
(09:08:59) INFO: Current date is 2017-09-26
(09:08:59) INFO: Analysed target //:stream (0 packages loaded).
(09:08:59) INFO: Found 1 test target...
Hello world.
Second line.
(09:09:02) [1 / 2] Testing //:stream; 3s processwrapper-sandbox
```

and new streamed output sill be added between the end of the output so far ("Second line.") and the status bar ("(09:09:02)[1/2] Testing //:stream; ...").

I might consider changing that layout (even though I think it's useful) as it already caused confusion, see #1359, but the streaming is definitely working.

**Comment by ddouglas87** [comment]
I've played around with aehlig's example above, and it does work.  It works because it is using a `printf()` statement.  `std::endl` works as well as an `'\n'` too.

What doesn't work is `std::flush` without a newline character, regardless if it is coupled with `'\r'` or not. Also, `fflush(stdout);` doesn't work by itself as well.  (I might be using the word curses in a slang or unofficial way.  Thanks for dealing with my lack of explicit description above.)

So eg while, `std::cout << "Hello world!\n";` works `std::cout << "Hello world!" << std::flush;` does not. Also, `std::cout << "Hello world."; fflush(stdout);` doesn't work.

**Comment by aehlig** [comment]
I see. The experimental UI deliberately only shows during `build` and `test` (not during run) only completed lines to avoid messing up with the curses control for the UI (which only uses line-based curses). While for `stderr` we could to show the output and redraw once it is updated, for `stdout` we have to assume it is redirected, so can only send the octets actually received.

I see that there is room for improvement, but I think it is low priority, as tests can end a line if they want the user to know about that information immediately.

**Comment by meisterT** [comment]
There is no plan to work on this issue.
