### ISSUE TITLE
How to specify PROTOC when build bazel

### ISSUE THREAD

**Issue by gyliu513** [bazelbuild/bazel#3801]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### If possible, provide a minimal example to reproduce the problem:
```
root@cit1046:~/gyliu/bazel-0.5.3# ./compile.sh
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch
ERROR: Must specify PROTOC if not bootstrapping from the distribution artifact

--------------------------------------------------------------------------------
NOTE: This failure is likely occuring if you are trying to bootstrap bazel from
a developer checkout. Those checkouts do not include the generated output of
the protoc compiler (as we prefer not to version generated files).

* To build a developer version of bazel, do

    bazel build //src:bazel

* To bootstrap your first bazel binary, please download a dist archive from our
  release page at https://github.com/bazelbuild/bazel/releases and run
  compile.sh on the unpacked archive.

The full install instructions to install a release version of bazel can be found
at https://docs.bazel.build/install-compile-source.html
For a rationale, why the bootstrap process is organized in this way, see
https://bazel.build/designs/2016/10/11/distribution-artifact.html
--------------------------------------------------------------------------------
```

### Environment info
* Operating System:
```
root@cit1046:~/gyliu/bazel-0.5.3# uname -a
Linux cit1046.rtp.raleigh.ibm.com 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:56:58 UTC 2017 ppc64le ppc64le ppc64le GNU/Linux
```

* Bazel version (output of `bazel info release`):

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by katre** [comment]
The critical error here is this one:
```
ERROR: Must specify PROTOC if not bootstrapping from the distribution artifact
```

Since you are bootstrapping Bazel on a system that does not have Bazel installed, you need to download the distribution artifact from https://github.com/bazelbuild/bazel/releases/download/0.5.4/bazel-0.5.4-dist.zip

This contains all of the code required to bootstrap Bazel.

**Comment by gyliu513** [comment]
Thanks @katre , it works

**Comment by gyliu513** [comment]
Related with https://github.com/bazelbuild/bazel/issues/3812

**Comment by Pokharaa** [comment]
I did as told by you @katre .I downloaded the bazel-0.5.4-dist.zip file and installed bazel.
But at the end, I got an error "Couldn't build bazel" :(.
Not able to create bazel.exe file in output folder.

 My error is:
Executing genrule //src:embedded_tools failed (Exit 1): bash.exe failed: error executing command
  cd C:/tempdir/shrtpath/tmp/bazel_snP6uY1x/out/execroot/io_bazel......

Please suggest me.

**Comment by Pokharaa** [comment]
Sorry for the trouble @katre .
I solved it by installing the latest version of bazel0.9.0dist. :) :)

**Comment by invegat** [comment]
Downloaded and extracted Tag 0.15.0, exact same error as using checkout.  "Must specify PROTOC if not bootstrapping from the distribution artifact"

**Comment by wafabouzid** [comment]
Hi I downloaded the last release of bazel 0.24.1 for windows  and I did the same instructions But, when I run  
./compile.sh
It shows the same error zs mentionned in this post  and I tried  bazel build //src:bazel but sadly it didn't work it shows me -bash: bazel: command not found
Ps: I run it from msys64 any suggestions please thanks a lot for reacting

**Comment by katre** [comment]
@wafabouzid Please open a new issue, and be sure that you are using the directions at [Building Bazel from scratch](https://docs.bazel.build/versions/master/install-compile-source.html#bootstrap-bazel).

**Comment by wafabouzid** [comment]
@katre  thank you here's my new issue https://github.com/bazelbuild/bazel/issues/8186

**Comment by jxramos** [comment]
What does the distribution archive provide that the bare source does not? Apparently the generated code is not checked into source control, if I download a corresponding distribution archive matching in version to a developer fork of bazel what artifacts must I merge from the unzipped archive over to my source folder?
