### ISSUE TITLE
No such attribute 'srcs' in 'pkg_tar' rule.

### ISSUE THREAD

**Issue by jsonschema** [bazelbuild/bazel#3804]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

`pkg_tar` fails with

`no such attribute 'srcs' in 'pkg_tar' rule.`

### If possible, provide a minimal example to reproduce the problem:
My BUILD file:

```
load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar")

filegroup(
    name = "bin_files",
    srcs = glob(["bazel-bin/*"]),
)

pkg_tar(
  name = "bin_tar",
  srcs = [":bin_files"]
)
```

### Environment info
* Operating System:
ProductName:    Mac OS X
ProductVersion: 10.12.6
BuildVersion:   16G29

* Bazel version (output of `bazel info release`): 0.5.2

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by katre** [comment]
In older versions, pkg_tar had a "deps" attribute, not "srcs". You can try renaming the attribute, but a better course would be to upgrade to a more recent Bazel release.
