### ISSUE TITLE
Mac installer output contains line noise

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#3805]
Unfortunately, I just closed the terminal so I can no longer copy paste it, but it looked something like this:
```
-n .
-n .
-n .
```

**Comment by katre** [comment]
I just re-installed 0.5.4 with the installer https://github.com/bazelbuild/bazel/releases/download/0.5.4/bazel-0.5.4-installer-darwin-x86_64.sh) and didn't see any issues. Log attached.
[installer.log](https://github.com/bazelbuild/bazel/files/1330276/installer.log)

**Comment by ulfjack** [comment]
I'll consider this unable to reproduce.
