### ISSUE TITLE
bazel does NOT follow `~/.m2/settings.xml` maven repos

### ISSUE THREAD

**Issue by fyears** [bazelbuild/bazel#3806]
### Description of the problem / feature request / question:

I am using bazel in a restricted network environment where `maven.org` couldn't be accessed BUT an internal maven mirror/repo is provided. My `~/.m2/settings.xml` is correctly configured, and all of `gradle`, `mvn`, intellij can download artifacts from internal mirror/repo read from `settings.xml` without problems.

- Expectation: bazel can also automatically download artifacts using configurations in `~/.m2/settings.xml`.
- Actual behaviour: bazel still downloads things from `https://repo1.maven.org/maven2`.

### If possible, provide a minimal example to reproduce the problem:

Use a modified version of official https://github.com/bazelbuild/examples/tree/master/java-maven by removing `maven_server()`.

```bash
$ git clone https://github.com/bazelbuild/examples/
$ cd examples/java-maven
$ cat > WORKSPACE << EOF
maven_jar(
    name = "com_google_guava_guava",
    artifact = "com.google.guava:guava:18.0",
)
EOF

$ bazel info release
WARNING: ignoring http_proxy in environment.
release 0.6.0rc3
$ bazel build :java-maven
WARNING: ignoring http_proxy in environment.
ERROR: ~/examples/java-maven/BUILD:3:1: no such package '@com_google_guava_guava//jar': Failed to fetch Maven dependency: Could not transfer artifact com.google.guava:guava:jar:18.0 from/to com_google_guava_guava (https://repo1.maven.org/maven2/): connect timed out and referenced by '//:java-maven-lib'
ERROR: Analysis of target '//:java-maven' failed; build aborted
INFO: Elapsed time: 10.749s
FAILED: Build did NOT complete successfully (9 packages loaded)
```

```bash
$ cat ~/.m2/settings.xml # internal repo working for gradle and mvn
<settings>
  <mirrors>
    <mirror>
      <id>internal mirror</id>
      <url>http://maven_internal.example.com/</url>
      <mirrorOf>*</mirrorOf>
    </mirror>
  </mirrors>
  ...
</settings>
```

if I manually add lines below to `WORKSPACE`, bazel works. **But I don't want to do this workaround because it should not be checked into version control.**

```
maven_server(
    name = "default",
    url = "http://maven_internal.example.com/",
)
```

### Environment info
* Operating System:

    Ubuntu 16.04 LTS

* Bazel version (output of `bazel info release`):
 
    ```bash
    $ sudo apt-get install bazel # using official testing repo as of 20170924
    $ bazel info release
    WARNING: ignoring http_proxy in environment.
    release 0.6.0rc3
    ```

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

According to [official doc](https://docs.bazel.build/versions/master/be/workspace.html#specifying-a-default-server), shouldn't bazel follow `~/.m2/settings.xml`??

They seem to be relevant,  however I still don't know how to "fix" the problem:

- https://stackoverflow.com/questions/43404421/how-to-specify-a-maven-repository-for-the-maven-aar-rule
- https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/maven_rules.bzl

**Comment by jin** [comment]
+@cgrushko +@damienmg related #3764

**Comment by fyears** [comment]
So, after a lot of try and error, I finally understood what's going on here.

bazel provides built-in `maven_jar` **as well as** the alternative extension-skylark-based `maven_jar`. The former one does things faster but not follow maven settings, and the later one directly calls system maven thus as a side effect it reads maven's `~/.m2/settings.xml` as expected.

The solution to my problem is quite simple: load the extension-based `maven_jar`:

```
$ cat > WORKSPACE << EOF
load("@bazel_tools//tools/build_defs/repo:maven_rules.bzl",
  "maven_jar", "maven_dependency_plugin")

maven_jar(
    name = "com_google_guava_guava",
    artifact = "com.google.guava:guava:18.0",
)
EOF
```

Though I found a workaround, I'd like to keep this issue open, as the default behavior is extremely confusing and no any available/useful doc found. At least, I could not find any "global settings" to define maven mirror/repo (and/or, for example, python pip mirror, etc), and the [doc here](https://docs.bazel.build/versions/master/be/workspace.html#specifying-a-default-server) ("A path to a settings.xml file. Used for testing. If unspecified, this defaults to using `$M2_HOME/conf/settings.xml` for the global settings and `$HOME/.m2/settings.xml` for the user settings.") is very confusing -- it works only(?) for testing!

**Comment by ittaiz** [comment]
Did you try just adding a maven_server with the name "default"? If your
private repo doesn't require authentication this just works.
I have a workspace with thousands of maven jars (the native rules) and they
all point to the private repo just by adding the above

**Comment by fyears** [comment]
@ittaiz 

Hi , I tried it, but it doesn't work...

```
maven_server(
    name = "default",
)
```

I have to explicitly declare the server, and after that bazel works:

```
maven_server(
    name = "default",
    url = "http://maven.example.com"
)
```

Maybe you using the newer version? I am using the one from offical ubuntu repo.

**Comment by ittaiz** [comment]
I was indeed referring to the latter form of:
```
maven_server(
    name = "default",
    url = "http://maven.example.com"
)
```
What is the problem with it?

**Comment by fyears** [comment]
@ittaiz 

The problems are, for example:

- I don't want to check in the url into version control
- plugins like https://github.com/bazelbuild/rules_scala doesn't work

**Comment by ittaiz** [comment]
The first point is valid though I don't consider the URL to be a secret so
I'm ok with it. One might even say it's better it's checked in since it
makes yet another implicit assumption into an explicit one.
Re rules_scala I happen to use them (and am a co-maintainer) and don't have
any problem. Can you please elaborate?

**Comment by jin** [comment]
@fyears if you have a `settings.xml` file with your server configuration in your WORKSPACE root, can you please try the following?

```
load("@bazel_tools//tools/build_defs/repo:maven_rules.bzl", "maven_jar")

maven_jar(
    name = "com_google_guava_guava",
    artifact = "com.google.guava:guava:18.0",
    settings = "//:settings.xml",
)
```

**Comment by ittaiz** [comment]
Is the git maven_jar really recommended?
It adds so much volatility in that it uses a local non versioned maven
version which seems to me very problematic

**Comment by jin** [comment]
I don't think we've come to a conclusion on which is the right way forward yet, but it's a solution that (should) work for now.

**Comment by cgrushko** [comment]
@jin there's https://github.com/bazelbuild/bazel/issues/1410#issuecomment-320761024 , where Kristina believed `java_import_external` was the way to go.

**Comment by fyears** [comment]
@ittaiz `rules_scala` hard-codes many `maven_server`s, thus unfortunately I cannot install/import/use the rules and run the tests properly under my limited network conditions. And the problem couldn't be fixed by trivially manually removing all the `maven_server`s.

**Comment by ittaiz** [comment]
@fyears we use `bind` so you should be able to just declare all of your maven jars yourself and bind them to the ones you declare. Instead of calling `scala_repositories` and its various counterparts just define them yourselves.

**Comment by damienmg** [comment]
Bind had lots of drawbacks, please use alias instead :)

**Comment by ittaiz** [comment]
@damienmg please please don't open this flame war here. We have enough of it over at #1952
The important point is that rules_scala uses an abstraction (maybe the wrong one) to allow its users to define the dependencies themselves.

**Comment by damienmg** [comment]
:( Sorry that wasn't for starting a flame war, I just want to avoid spreading the usage of bind whereas we are thinking of removing it. (as @ittaiz said there is a long discussion on the pros and cons on #1952 to not start another one here).

**Comment by dslomov** [comment]
Looks like there is no actual bug here, isn't it?

**Comment by pemgithub** [comment]
bazel with external dependency using maven... proxy does not seem to work

I tried adding this to my WORKSPACE (for gapid) but no luck:
```
load("@bazel_tools//tools/build_defs/repo:maven_rules.bzl", "maven_jar", "maven_dependency_plugin")
maven_jar(
    name = "com_google_guava_guava",
    artifact = "com.google.guava:guava:18.0",
    settings = "//:settings.xml",
)
```
