### ISSUE TITLE
[Problem] the generated shell script in windows cannot recognize the space among the file names

### ISSUE THREAD

**Issue by Sherler** [bazelbuild/bazel#3807]
### Description of the  Bug:
I came across a bug (shown below) when following the tutorial of [building java program with bazel](https://docs.bazel.build/versions/master/tutorial/java.html)
![image](https://user-images.githubusercontent.com/11971198/30809814-aa56f912-a235-11e7-97b9-efd7645e7568.png)

  I noticed that my username "George Liang" contains a space character, which I believed should be the main reason of the error.
  I''m new to bazel, and I'm not sure about that. Hope someone can help.

The environment is:
Windows 10
bazel 0.5.4
java 1.8

**Comment by laszlocsomor** [comment]
Yes, that's very likely the bug indeed.
Routing to @meteorcloudy -- does the native launcher handle this?

**Comment by meteorcloudy** [comment]
Yes, this is hitting a bug of parsing manifest file in [java_stub_template.txt](https://github.com/bazelbuild/bazel/blob/3ba3dfc4ed0cbccfc77e3a21dcaf19438a6c415c/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt#L202)
And the native launcher handles it nicely. 

I'll send a fix for the java stub.

**Comment by meteorcloudy** [comment]
@Sherler Can you try our latest release candidates? 
https://storage.googleapis.com/bazel/0.6.0/rc4/bazel-0.6.0rc4-windows-x86_64.exe, it should fix the problem. ;)

**Comment by Sherler** [comment]
@meteorcloudy  yeah, It works as expected now！Thank you very much！
