### ISSUE TITLE
repository_rule not hermetic to other repos

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3809]
### Description of the problem / feature request / question:

In `repository_rules`, there seems to be currently not way of ensuring hermetic operations.
You can:

1. Pass any (non-exported) path as parameter to a `repository_ctx`
2. Modify any file from another repository in your repository implementation.

### Environment info
* Operating System: Ubuntu 16.04.03
* Bazel version (output of `bazel info release`): 0.6rc1

**Comment by katre** [comment]
Can you provide an example of a non-hermetic repository rule that is causing problems?

**Comment by abergmeier-dsfishlabs** [comment]
Problems are 2 fold:

1. There we violate the interface with being able to access even private files. This in turn means you cannot be sure, that when you change your internal structure, that other repos don't depend on it.
2. In the best case, this leads to hard to debug error cases.

I could construct 2 tests for these if you want.

**Comment by abergmeier-dsfishlabs** [comment]
There you go: https://github.com/abergmeier-dsfishlabs/bazel_repo_visibility

It demonstrates both problems with `bazel build @violating_repo//:all`

**Comment by dslomov** [comment]
Well, repository rules are not intended to be "hermetic": they need to be able to access your file system, Internet and so on. However you raise very valid points w.r.t protecting repo rules from each other.
I do not think we have a good solution.

**Comment by abergmeier-dsfishlabs** [comment]
> I do not think we have a good solution.

Wouldn't the solution be to:

1. Enable sandboxing for all actions of `repository_ctx`.
2. Disable access on `external/*`
2. Selectively allow read access to public targets under `external` of repos which appear in repository_rule's attrs.
3. Allow write access to `external/<current_repo>`

Or am I missing something (aside from that nobody currently will find time to do this).

**Comment by dslomov** [comment]
Repositiory rules need (read) access to the local disk, the environment and the network.
I guess we can think of sandboxing them, but I am not sure how to allow reading local disk at the same time disallowing reads of `external` @philwo, any thoughts?

**Comment by abergmeier-dsfishlabs** [comment]
>  but I am not sure how to allow reading local disk at the same time disallowing reads of external

Isn't that what _sandboxfs_ should easily enable!?

**Comment by dslomov** [comment]
> Isn't that what sandboxfs should easily enable!?

Right, that should work.

**Comment by jmmv** [comment]
No, sandboxfs has nothing to do with allowing or disallowing file accesses. sandboxfs is an optimization for sandboxing but doesn't actually do the sandboxing itself. (We chose a poor name for the file system...)

Having sandboxing for repository actions seems good though.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
