### ISSUE TITLE
Update Windows status on FAQ

### ISSUE THREAD

**Issue by davidstanke** [bazelbuild/bazel#3810]
On https://bazel.build/faq.html, the description of Windows support is not consistent with its current maturity.

**Comment by mmorearty** [comment]
The new description of Windows support is confusing to me when you read it in context. If you look at https://bazel.build/faq.html, you will see this:

> ### Where can I run Bazel?
> 
> Currently, Linux and macOS (OS X). Porting to other UNIX platforms should be straightforward, as long as a JDK is available for the platform.
> 
> ### What about Windows?
> 
> Bazel runs natively on Windows and we are committed to improving it with every new release.
> 
> For more information, see the list of open bugs.

The recently-rewritten answer to that "What about Windows" question seems to indicate that Bazel on Windows basically just works (although there are issues). If that's the case, wouldn't it make sense to eliminate the "What about Windows" question altogether, and just update the "Where can I run Bazel?" answer to include Windows in its list of supported platforms?

**Comment by laszlocsomor** [comment]
Good point, thanks! I'll update it.
