### ISSUE TITLE
rpaths of linkshared cc_binary rules don't pick up their dependencies

### ISSUE THREAD

**Issue by allenlavoie** [bazelbuild/bazel#3811]
### Description of the problem / feature request / question:

TensorFlow recently started building with a dependence on a cc_binary with linkshared=1 (for custom op registration). This mostly works, but there's an issue when this cc_binary rule itself depends on some shared objects (in this case CUDA libraries). The rpaths seem to assume that each cc_binary is going to be root-level, while in reality they get shuffled off into a sub-directory and can't find their dependencies.

For the moment I'm going to suggest that people use --action_env=LD_LIBRARY_PATH, which is a reasonable workaround (i.e. will pick up external CUDA libraries), but it'd be nice to add a few extra rpaths to these cc_binary rules so it's not necessary.

### If possible, provide a minimal example to reproduce the problem:

```
cc_binary(
    name = "libsecond_dep.so",
    linkshared = 1,
)

cc_binary(
    name = "libfirst_dep.so",
    srcs = ["libsecond_dep.so"],
    linkshared = 1,
)

genrule(
    name = "make_main",
    outs = ["main.cc"],
    cmd = "echo 'int main() {return 0;}' > $@",
)

cc_binary(
    name = "main",
    srcs = [
        "main.cc",
        ":libfirst_dep.so",
    ],
)

genrule(
    name = "use_main",
    outs = ["foo.txt"],
    cmd = "./$(location main) > $@",
    tools = [
        ":libfirst_dep.so",
        ":libsecond_dep.so",
        ":main",
    ],
)
```

If I run "bazel build :use_main", I get an error like:

> ERROR: /usr/local/google/home/allenl/bazelrepro3/BUILD:26:1: Executing genrule //:use_main failed (Exit 127)
> ./bazel-out/host/bin/main: error while loading shared libraries: libsecond_dep.so: cannot open shared object file: No such file or directory
> Target //:use_main failed to build

Oddly "bazel run :main" does not throw an error.

See https://github.com/tensorflow/tensorflow/issues/13243 for a more complicated reproduction of what I think is the same issue. This also seems to affect //tensorflow/contrib/factorization/kernels:clustering_ops_test when building with CUDA,  so I don't think it's just genrules.

### Environment info
* Operating System:
Ubuntu 14.04.5 LTS

* Bazel version (output of `bazel info release`):
release 0.5.4

**Comment by mhlopko** [comment]
Hi Allen,
sorry this took so long, have too few free evenings. I tried to build `bazel build :use_main` with bazel build@HEAD (to make sure https://github.com/bazelbuild/bazel/commit/f98a7a2fedb3e714cef1038dcb85f83731150246 is included) and it passed. Can you verify it works for you and ideally also if https://github.com/tensorflow/tensorflow/issues/13243 is fixed as well?

Thank you so much!

**Comment by allenlavoie** [comment]
Huh. I just built at https://github.com/bazelbuild/bazel/commit/06e1781a95f16bb4b1840fc50ae705b9cdb98b34 and I'm seeing the same issue. Are you running the repro on a Mac (https://github.com/bazelbuild/bazel/commit/f98a7a2fedb3e714cef1038dcb85f83731150246 looks Mac-specific)? Possibly it's working there but not on Linux (FWIW I'm on Debian).

**Comment by allenlavoie** [comment]
Now that I look at my repro again, "main" has an undeclared dependence on "libsecond_dep.so" even though it is declared as a tool dependence. Adding that explicitly fixes things. So probably the repro has the correct behavior wrt Bazel not doing transitive binary deps? With the more recent Bazel version, "bazel run :main" fails, which makes things a bit more clear.

It looks like we've essentially given up on collecting CUDA libraries ourselves, and have the action_env=LD_LIBRARY_PATH=... in our default bazelrc. So probably https://github.com/tensorflow/tensorflow/issues/13243 is set too (or at least, nobody is going to complain). Possibly it's the same issue as was in the repro (deps added to the tool but not to an intermediate binary?); I'll circle back if I find anything Bazel-related that isn't just an undercover feature request for transitive dependencies.

Thanks for taking a look! I'll close this, since I don't see anything actionable on your end.

**Comment by mhlopko** [comment]
I just confused this issue with one of many we have open for linking on darwin. I think this issue is still valid, and boils down to cc_binary cannot depend on cc_binary. And the solution for that are transitive libraries, that are currently on hold but hopefully eventually going to be implemented. If you can wait until then, let's keep this issue closed, if not, feel free to reopen.

**Comment by allenlavoie** [comment]
Taking another look at the original https://github.com/tensorflow/tensorflow/issues/13243, I do think this is a real issue with rpaths regardless of the transitive libs issue. Probably my repro just fails to capture some nuance of the situation.

I don't think it's necessary to reproduce this yourself (feel free to skip this bit), but just for completeness the command I'm running is:

```
bazel build --config=cuda //tensorflow/contrib/factorization:gen_gen_clustering_ops_py_wrappers_cc
```
With CUDA 9 / CuDNN 7 configured and the following patch applied to TensorFlow (https://github.com/tensorflow/tensorflow/commit/4e108ef30d7cd7ae5e1c550ec5ae27e79b8c6e39, Bazel at https://github.com/bazelbuild/bazel/commit/06e1781a95f16bb4b1840fc50ae705b9cdb98b34) to explicitly reference the necessary shared objects:

```
diff --git a/tensorflow/BUILD b/tensorflow/BUILD
index 9932e56076..1f0a02991c 100644
--- a/tensorflow/BUILD
+++ b/tensorflow/BUILD
@@ -754,6 +754,16 @@ filegroup(
 # depend on libtensorflow_framework.so unless they opt in.
 tf_cc_shared_object(
     name = "libtensorflow_framework.so",
+    srcs = [
+        "@local_config_cuda//cuda:cuda/lib/libcublas.so.9.0",
+        "@local_config_cuda//cuda:cuda/lib/libcuda.so",
+        "@local_config_cuda//cuda:cuda/lib/libcudart.so.9.0",
+        "@local_config_cuda//cuda:cuda/lib/libcudnn.so.7",
+        "@local_config_cuda//cuda:cuda/lib/libcufft.so.9.0",
+        "@local_config_cuda//cuda:cuda/lib/libcupti.so.9.0",
+        "@local_config_cuda//cuda:cuda/lib/libcurand.so.9.0",
+        "@local_config_cuda//cuda:cuda/lib/libcusolver.so.9.0",
+    ],
     framework_so = [],
     linkstatic = 1,
     visibility = ["//visibility:public"],
```

Note that to reproduce you also need to comment out the --action_env=LD_LIBRARY_PATH in TensorFlow's bazelrc. And the error is (undefined symbol errors omitted):

```
/usr/bin/ld: warning: libcublas.so.9.0, needed by bazel-out/k8-py3-opt/bin/_solib_local/_U_S_Stensorflow_Scontrib_Sfactorization_Cgen_Ugen_Uclustering_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcudnn.so.7, needed by bazel-out/k8-py3-opt/bin/_solib_local/_U_S_Stensorflow_Scontrib_Sfactorization_Cgen_Ugen_Uclustering_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcufft.so.9.0, needed by bazel-out/k8-py3-opt/bin/_solib_local/_U_S_Stensorflow_Scontrib_Sfactorization_Cgen_Ugen_Uclustering_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcupti.so.9.0, needed by bazel-out/k8-py3-opt/bin/_solib_local/_U_S_Stensorflow_Scontrib_Sfactorization_Cgen_Ugen_Uclustering_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcurand.so.9.0, needed by bazel-out/k8-py3-opt/bin/_solib_local/_U_S_Stensorflow_Scontrib_Sfactorization_Cgen_Ugen_Uclustering_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcusolver.so.9.0, needed by bazel-out/k8-py3-opt/bin/_solib_local/_U_S_Stensorflow_Scontrib_Sfactorization_Cgen_Ugen_Uclustering_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so, not found (try using -rpath or -rpath-link)
```
The directory structure looks like:

```
~/tensorflow/tensorflow$ tree bazel-out/k8-py3-opt/bin/_solib_local/
bazel-out/k8-py3-opt/bin/_solib_local/
├── _U@local_Uconfig_Ucuda_S_Scuda_Ccublas___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib
│   └── libcublas.so.9.0
├── _U@local_Uconfig_Ucuda_S_Scuda_Ccudart___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib
│   └── libcudart.so.9.0
├── _U@local_Uconfig_Ucuda_S_Scuda_Ccuda_Udriver___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib
│   └── libcuda.so
├── _U@local_Uconfig_Ucuda_S_Scuda_Ccudnn___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib
│   └── libcudnn.so.7
├── _U@local_Uconfig_Ucuda_S_Scuda_Ccufft___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib
│   └── libcufft.so.9.0
├── _U@local_Uconfig_Ucuda_S_Scuda_Ccurand___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib
│   └── libcurand.so.9.0
├── _U_S_Stensorflow_Clibtensorflow_Uframework.so___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib
│   ├── libcublas.so.9.0
│   ├── libcudart.so.9.0
│   ├── libcuda.so
│   ├── libcudnn.so.7
│   ├── libcufft.so.9.0
│   ├── libcupti.so.9.0
│   ├── libcurand.so.9.0
│   └── libcusolver.so.9.0
└── _U_S_Stensorflow_Scontrib_Sfactorization_Cgen_Ugen_Uclustering_Uops_Upy_Uwrappers_Ucc___Utensorflow
    └── libtensorflow_framework.so
```

And the rpaths are (reformatted slightly):

```
~/tensorflow/tensorflow$ objdump -a -x bazel-out/k8-py3-opt/bin/_solib_local/_U_S_Stensorflow_Scontrib_Sfactorization_Cgen_Ugen_Uclustering_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so | grep PATH

RUNPATH
  $ORIGIN/../_solib_local/_U_S_Stensorflow_Clibtensorflow_Uframework.so___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib:
  $ORIGIN/../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccublas___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib:
  $ORIGIN/../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccuda_Udriver___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib:
  $ORIGIN/../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudnn___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib:
  $ORIGIN/../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccufft___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib:
  $ORIGIN/../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccurand___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib:
  $ORIGIN/../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudart___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib:
  $ORIGIN/:../local_config_cuda/cuda/lib64:../local_config_cuda/cuda/extras/CUPTI/lib64
```

None of which point to the declared dependencies, since there's an extra "_solib_local" in there.

**Comment by meteorcloudy** [comment]
I'm debugging today and found out the reason there is an extra "_solib_local" is this:

The original `libtensorflow_framework.so` is located at:
`bazel-out/k8-py3-opt/bin/tensorflow/libtensorflow_framework.so`
If you use `$ORIGIN=bazel-out/k8-py3-opt/bin/tensorflow` in rpath, it should be able to load its dependencies.

But because `libtensorflow_framework.so` itself is also a shared library, it's symlinked to a folder under _solib_local, so the relative rpath is not correct anymore.

I think the solution would be that, when building shared library from cc_binary, we add extra rpaths calculated relatively to its symlink under _solib_local

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
