### ISSUE TITLE
Allow installing older Bazel versions from the custom Bazel APT repository

### ISSUE THREAD

**Issue by mishas** [bazelbuild/bazel#3813]
When using the Bazel custom APT repository (recommended) method for installing Bazel on Debian/Ubuntu, it's only possible to install the latest version:

```
> apt-get install bazel=0.5.3
[...]
E: Version '0.5.3' for 'bazel' was not found
> apt-get install bazel=0.5.4
[...]
The following additional packages will be installed:
[...]
```

Looking at the Packages file (http://storage.googleapis.com/bazel-apt/dists/stable/jdk1.8/binary-amd64/Packages), it indeed only contains one package with Version 0.5.4.

Since there're many breaking changes (most of them are welcome :) ) in every new version, we must have a way to install a specific, older, version.

**Comment by katre** [comment]
It is actually our CI system that handles the APT repository, could you please re-open this issue there? https://github.com/bazelbuild/continuous-integration/issues

**Comment by rickwierenga** [comment]
Any news on this issue? I'm looking to install version 0.25.2 to build Swift.

**Comment by jin** [comment]
@rickwierenga check out https://github.com/bazelbuild/bazelisk, or download the binary from https://github.com/bazelbuild/bazel/releases/tag/0.25.2

**Comment by rickwierenga** [comment]
I was able to download the installer script using `wget`:

```sh
wget bazel-0.25.2-installer-linux-x86_64.sh
```

Then installing:
```sh
chmod +x bazel-0.25.2-installer-linux-x86_64.sh
sudo ./bazel-0.25.2-installer-linux-x86_64.sh
```
