### ISSUE TITLE
Bazel --jobs=auto might benefit from a larger default

### ISSUE THREAD

**Issue by depristo** [bazelbuild/bazel#3814]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

Hello fellow Googlers and open source contributors,

### Description of the problem / feature request / question:

Bazel controls the number of parallel jobs to run with --jobs, which defaults to the value 'auto' in the latest build. This resolves via the series of source files:

Here's the actual code in bazel:

https://github.com/bazelbuild/bazel/blob/bf96c50e0c9afd3da8d937948c3636f09a0e80d7/src/main/java/com/google/devtools/build/lib/buildtool/BuildRequest.java#L74

and associated value getting for 'auto'

https://github.com/bazelbuild/bazel/blob/bf96c50e0c9afd3da8d937948c3636f09a0e80d7/src/main/java/com/google/devtools/build/lib/buildtool/BuildRequest.java#L435

which ultimately goes to:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/actions/ResourceManager.java#L45

which ultimately calls:

https://github.com/bazelbuild/bazel/blob/5e60e3868b4bafacc138f786b304589dbd687016/src/main/java/com/google/devtools/build/lib/actions/LocalHostResourceManagerLinux.java#L50

which produces 32 * 0.6 = 19.2 cores to use, along with the ceil calls gives us 20. This is the value I see when using bazel to build a large project (TensorFlow + other sources) on a 32 vCPU GCE instance:

(02:33:06) [975 / 1,044] 1 / 50 tests; 20 actions running

However, we've noticed that this isn't taking advantage of all of the resources on the instance, and started experimenting with different values of --jobs to speed up our build:

--jobs value | build time
auto & 20 | 9m26.597s
32 | 7m26.728s
64 | 7m11.939s
128 | 7m14.128s

We have resorted to setting --jobs=128 in our bazel.rc but this isn't ideal as presumably the best option depends on the actual number of CPUs on the machine. I'd recommend increasing the multiplier (currently 0.6) to a larger number. At least according to our calculations, a value >= 1.0 may be optimal.

### If possible, provide a minimal example to reproduce the problem:

You should be able to reproduce by cloning TensorFlow (or any other large project) and running with a variety of --job values.

### Environment info
* Operating System: ubuntu 14.06 LTS on 32 core high-cpu GCE instance.

* Bazel version (output of `bazel info release`):

release 0.5.4

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

**Comment by susinmotion** [comment]
We're doing some testing to find a good cpu multiplier for the auto value of --jobs, and you can expect to see this changed soon. 

But, in the meantime, --jobs now takes HOST_CPUS*<float>, so you can specify resource-relative configurations.

**Comment by dslomov** [comment]
Please do not assign more than one team to an issue.

**Comment by jmmv** [comment]
`auto` was changed a while ago to default to the number of cores and remove the 0.6 cap, so I think the original issue reported here was fixed.

**Comment by acecilia** [comment]
@jmmv 

> auto was changed a while ago to default to the number of cores

Seems like documentation still uses `auto` as default 🤔 https://bazel.build/reference/command-line-reference#flag--jobs

<img width="866" alt="Screenshot 2023-07-20 at 11 35 58" src="https://github.com/bazelbuild/bazel/assets/7938671/3cfdbe42-da7c-477a-bf64-b73587849d5e">

**Comment by jmmv** [comment]
@acecilia I don't understand your comment. The default is `auto`, which in turn translates to an automatically-computed value. This automatic computation was changed to be the number of cores, but it's not explicitly stated in the description to avoid committing to this implementation detail.

**Comment by acecilia** [comment]
Got it, understood. Thanks!

**Comment by mohamedelkony** [comment]
Hi, just a dummy question what does --job in bazel refer to? the number of worker processes that actions are distributed? or is it more subtle?
