### ISSUE TITLE
Support for C# code?

### ISSUE THREAD

**Issue by arekbulski** [bazelbuild/bazel#382]
Is there a possibility that Bazel will support building C# code? I am particularly interested in Mono.Fuse dependency.

**Comment by davidzchen** [comment]
Supporting building C# projects would definitely be great to have, especially now that Microsoft has open-sourced Roslyn and much of its .NET frameworks.

Writing build rules for building Mono projects is on my list of things that I want to do, but I have not had time to work on it yet. If someone is interested in picking this up, that would be awesome.

**Comment by bowlofstew** [comment]
I agree that it would be a nice to have!

**Comment by damienmg** [comment]
It has been in now. http://bazel.io/docs/be/dotnet.html

File more speicific issue if you have ones.

**Comment by KashMoneyMillionaire** [comment]
The above link no longer points to a valid page. Is there any more news out of this?

**Comment by ajrepp** [comment]
@KashMoneyMillionaire I believe you're looking for https://github.com/bazelbuild/rules_dotnet?

**Comment by samuela** [comment]
Are there any docs for rules_dotnet though?

**Comment by laurentlb** [comment]
https://github.com/bazelbuild/rules_dotnet has some documentation.
If it's not enough or if you have any problem with it, please file an issue on that repository.
