### ISSUE TITLE
Is the "experimental" directory skipped when running "bazel test ..." from workspace root?

### ISSUE THREAD

**Issue by claveld** [bazelbuild/bazel#3822]
Assuming we have the following workspace:
```
my_workspace/
 a_dir/
  experimental/
  some_dir/
  WORKSPACE
```

where tests (eg cc_test, py_test) can be found in each of these directories.

Then running from within my_workspace:
```
  bazel test ...
```
will only run tests in a_dir and some_dir.

Then:
```
  cd experimental
  bazel test ...
```
will successfully run the tests from experimental.

Why is the "experimental" directory skipped where running from the workspace root?
Is there a flag controlling this?
 
### Environment info
* Operating System:
macOs 10.12.6

* Bazel version (output of `bazel info release`):
$ bazel info release
release 0.5.4- (@non-git)

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
$ git rev-parse HEAD
02dceebed167d308869943977ba1a1411dd3ff3b

**Comment by ulfjack** [comment]
The "experimental" string is currently hard-coded in Bazel, I believe (like a few other strings, like "third_party", which requires license declarations in any BUILD files underneath).

**Comment by haxorz** [comment]
i plan to get rid of this (hardcoded) behavior. i came across it today and didn't like it.

i imagine it's completely undesirable for external bazel users.

**Comment by Kernald** [comment]
Is there any way to reproduce that kind of behaviour?
