### ISSUE TITLE
A better "executable" mechanism

### ISSUE THREAD

**Issue by ianthehat** [bazelbuild/bazel#3826]
This is a feature request for a better mechanism than setting "executable = True" on a rule.

There are a few issues with the current mechanism. 

1. Name transformations (.exe, .sh, .bat etc) are not under the control of the rule
    This is a problem for things like cross compiling to windows, which is one of the major drivers for this issue. The Kubernetes team need linux to windows cross compile and there is no way for me to make it work right now.

1. Multiple binary flavours
    You can easily build multiple flavours (static, asan, etc) of an output rule using various controls (output groups, features etc) but you cannot easily control which of them is the default output used by `bazel run` or (even worse) `bazel test`. What you have to do right now is build them with flavour specific names and then have an extra rule to copy the flavour version over the pre-determined output path.

1. Your rule name is forced by your desired binary name
    This leads to weirdness where you don't really want a rule to be called the same as the binary, for instance if the default rule for a package should be to build and package an executable, but you really want the executable named the same as the folder.

1. It's weird extra magic
    You can do everything else about selecting your outputs in a standard way except this one thing and I don't think it deserves or needs the conceptual overhead.

Instead of this I propose we add a new provider, either an extra one or a well understood field of the DefaultOutputProvider.

For example, currently we would write:

``` bzl
def _my_binary_impl(ctx):
  normal_executable = ctx.outputs.executable
  ...
  return [
      DefaultInfo(
          files = depset([normal_executable]),
      ),
      OutputGroupInfo(
          normal = depset([normal_executable]),
          static = depset([static_executable]),
          asan = depset([asan_executable]),
      ),
  ]

my_binary = rule(
    _my_binary_impl,
    attrs = {
        "srcs": attr.label_list(allow_files = True),
        "deps": attr.label_list(),
    },
    executable = True,
)
```

And instead this would become:

``` bzl
def _my_binary_impl(ctx):
  normal_executable = ctx.actions.declare_file(ctx.label.name)
  ...
  return [
      DefaultInfo(
          files = depset([normal_executable]),
          executable = normal_executable,
      ),
      OutputGroupInfo(
          normal = depset([normal_executable]),
          static = depset([static_executable]),
          asan = depset([asan_executable]),
      ),
  ]

my_binary = rule(
    _my_binary_impl,
    attrs = {
        "srcs": attr.label_list(allow_files = True),
        "deps": attr.label_list(),
    },
)
```

There is probably a cost in that the rule type alone is no longer sufficient to tell you if it is executable and if so what file you are going to execute?

**Comment by dslomov** [comment]
This is a reasonable request. It is a non-trivial change.

Why is is a P1? What does this block? Is there a workaround for whatever it blocks?

**Comment by ianthehat** [comment]
It blocks the ability to cross compile go code from linux to windows (the .exe extension) which in turn blocks the ability for kubernetes to switch to using Bazel for their release builds in Q4.
There may be other ways around that in the shorter term though?

**Comment by dslomov** [comment]
I see. I *think* we can implement this for 0.8 which is scheduled be cut (not released) for Nov 6th (https://github.com/bazelbuild/bazel/issues/3772). 

If you just need to port a specific build, you can always second target "whatever.exe", that is a genrule copying whatever to whatever.exe. If you just need to port one specific build, that would be a workaround.

**Comment by ianthehat** [comment]
I don't think I could do that inside the rules_go, its too invasive to all the other users, so it would have to be up to Kubernetes to add the extra rules for all the binaries they care about.
You would also want the copying rules to only exist on windows. 
You also need rules that depend on the binaries to pick the right ones using select, which means what you really need is 3 rules:
``` bzl
  # the actual binary compiler
  go_binary(visiblitiy=private)

  # genrule that copies the binary output to add .exe
  go_windows_binary(visiblitiy=private, tags=manual)

  #filegroup that picks between the two above rules using select
  go_select_binary
```
where only the last one is a visible name to the rest of the world
I guess the last two could be merged by writing a custom rule instead, and the whole thing could be wrapped in a macro...
Doing the select is also non trivial because there is no single thing you can test for that matches a target os of windows (there are quite a few cpu values that mean windows)

I think if we really really need to do this we can, but it won't be pretty, it should be a last resort if it's the only thing left to be able to switch Kubernetes on time and the clean fix is still a long way out.

**Comment by dslomov** [comment]
I was thinking Kubernetes can add it for specific targets they need (if
there is a small number of  .exes they need to build)
 Definitely not go rules in general.

**Comment by dslomov** [comment]
Here is a prototype (that I do not quite like): https://bazel-review.googlesource.com/c/bazel/+/18850

That patch allows `executable` argument to `rule` function to be a string `"custom"` and then `ctx.output.executable` is not created and the rule must create the executable artifact itself and pass it
through `DefaultInfo(executable = xxx)` (see the test)

This is not a great API but it works: @ianthehat if you want to play with it, feel free to patch it in and try it, let me know if there are any issues.

The deal though is that we want to mark rules as `executable` (for validation) but currently `executable = True` forces the creation of `ctx.outputs.executable` which in turn forces the rule to create an action that output it (because we do not allow orphan artifacts). In my patch `executable = "custom"` marks the rule as executable but does not create `ctx.outputs.executable`.

The best way forward that occurs to me is: keep `executable` arg of `rule` boolean, but create `ctx.outputs.executable` on demand: 
 - the rule marked with `executable = True` must either
   - access `ctx.output.executable` and create an action generating it; or
   - create an output file with `ctx.actions.declare_file` and return it via `DefaultInfo(executable = ...)`
Longer-term we want to get rid of all implicit outputs (`ctx.output`) so the second method is preferable.

I'll prototype that next, but WDYT @laurentlb @ianthehat ?

**Comment by ianthehat** [comment]
I looked at the change, and I agree with you, executable should stay a bool and the implicit output should be built on demand (but you might need to add an extra check to complain if you do neither?)

I will try to find time to try it out tomorrow, currently stuck deep in a massive change to the way we build the standard library (for cross compilation)

For what it's worth, *all* outputs in rules_go except those mandated by the executable flag are generated with `ctx.new_file` (we have not migrated to `ctx.actions` yet), it will make me very happy to remove this last one.

**Comment by dslomov** [comment]
> I will try to find time to try it out tomorrow, currently stuck deep in a massive change to the way we build the standard library (for cross compilation)

No rush.

> For what it's worth, all outputs in rules_go except those mandated by the executable flag are generated with ctx.new_file (we have not migrated to ctx.actions yet), it will make me very happy to remove this last one.

Yeah I do not like the magical `ctx.outputs` too, but we need to dance the dance so that we stay compatible with current API (and it has a _lot_ of usages).

Anyhow the change is much simpler than I feared, so I am more confident that it can make 0.8. I'll prototype lazy creation of `ctx.outputs.executable` and bring this to Skylark Design Cabal soon. I'll keep this bug posted on my progress.

**Comment by dslomov** [comment]
The API per https://github.com/bazelbuild/bazel/issues/3826#issuecomment-336220897 is approved.

**Comment by dslomov** [comment]
This implementation is in internal review (sorry about the non-transparency, it is a bit hard right now to do both internal and gerrit reviews; work is underway to fix that)

**Comment by dslomov** [comment]
Overeager GitHub bot.

**Comment by dslomov** [comment]
This is now implemented for real; @ianthehat please try it out soonish - if this does not work for you and you need something changed before 0,8, we'll have to act quickly.

**Comment by ianthehat** [comment]
Thanks Dmitry
Is there a build with it in or do I need to build bazel from source?

**Comment by dslomov** [comment]
There will be a nightly tonight, but building from source is the quickest

**Comment by ianthehat** [comment]
Tested this today, worked perfectly for this and a few other use cases, thanks!

**Comment by dslomov** [comment]
Great, let me know it you hit any issues, and thanks for bringing this problem to our attention and also suggesting a design for solution. This will be helpful to everyone developing rules for Windows.
