### ISSUE TITLE
FULLY STATIC mode with error "get crtbeginT.o: relocation R_X86_64_32 against `__TMC_END__' can not be used when making a shared object; recompile with -fPIC'` "

### ISSUE THREAD

**Issue by channingxiao** [bazelbuild/bazel#3831]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
I was using Bazel 0.5.4 to compile tensorflow (1.3.1) C++ shared libs, and for some reasons  I want to link libstdc++ statically.  According to [Bazel C/C++ Rules](https://docs.bazel.build/versions/master/be/c-cpp.html), I have to set " linkstatic=["-static"] " in the cc_binary config file. Then I compiled tensorflow with this settings and I encounted with an error " gcc/x86_64-unknown-linux-gnu/4.8.2/crtbeginT.o: relocation R_X86_64_32 against `__TMC_END__' can not be used when making a shared object; recompile with -fPIC
/home/xiaochunlin/3rdparty/gcc4/lib/gcc/x86_64-unknown-linux-gnu/4.8.2/crtbeginT.o: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
".

Then I tried to recompile gcc , and add parameter CFLAGS="-fPIC" when running configure.  The same error still exited when recompile tensorflow with Bazel.

Can anybody providing some guide line to work this around ? 

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### Environment info
* Operating System:
Redhat 6.5 with kernel 2.6.32-431.el6.x86_64. And I compiled Bazel with a self compiled GCC 4.8.2 installed locally on my own home directory,  and i didn't update the binutils, i.e. the linker ld and asembler as are systems default version "2.20.51.0.2-5.36.el6 20100205". 

* Bazel version (output of `bazel info release`):
0.5.4

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by aiuto** [comment]
Closing because this is for an obsolete Bazel and has gone stale.
