### ISSUE TITLE
Windows: Android tools should use the prebuilt windows_jni.dll from embedded tools

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3832]
https://github.com/bazelbuild/bazel/blob/c6122b6ad35ebbed61036b0a2bcfea92b10adb8f/src/tools/android/java/com/google/devtools/build/android/BUILD.tools#L12

Since the Android tools themselves are embedded binaries, and users will most likely not have Bazel's repo checked out when building Android rules, the tools should not depend on targets in Bazel's own repo.

**Comment by aj-michael** [comment]
Can we bundle the windows_jni.dll inside the busybox deploy jar that we embed in bazel? e.g. put it here:

**Comment by laszlocsomor** [comment]
I don't see how we could.

If we added it as a resource, then the BusyBox would need to unpack it at runtime, and delete it after it's done running to avoid polluting the disk.

If we added it as a data-dependency, then it wouldn't be added to the runfiles of `@src/tools/android/java/com/google/devtools/build/android:ResourceProcessorBusyBox`.

**Comment by aj-michael** [comment]
Hmm, I was thinking that deploy jars worked with runfiles somehow, although now that I think about it, I don't know how it would work. For posterity, I was assuming something like this:

```
# BUILD
java_binary(
    name = "foo",
    data = ["foo_data"],
)
java_import(
    name = "foo_import",
    jars = [":foo_deploy.jar"],
)
java_binary(
    name = "bar",
    runtime_deps = [":foo_import"],
)
```

but I tried it, and bar does not have access to foo_data

**Comment by laszlocsomor** [comment]
Yes, I remember having tried the same and reaching the same conclusion.

**Comment by laszlocsomor** [comment]
Update: I haven't done anything for this bug and likely won't do anything before end of Q2'18.

**Comment by laszlocsomor** [comment]
Dropping priority. This doesn't seem to cause trouble.

**Comment by jin** [comment]
Closing as wontfix, let's revisit if it's an issue.
