### ISSUE TITLE
Bazel calls strip with invalid -R option under OS X

### ISSUE THREAD

**Issue by zuercher** [bazelbuild/bazel#3838]
Tested with bazel-0.6.0. This is basically a variation on #209, but with a different flag.

This issue continues to cause problems for https://github.com/envoyproxy/envoy. We currently have a workaround for #209 that works with 0.5.4 but not 0.6.0.

The bug is trivially reproducible with the bazelbuild examples repository:

```
$ git clone https://github.com/bazelbuild/examples
$ cd examples/cpp-tutorial/stage1
$ bazel build //main:hello-world.stripped
INFO: Found 1 target...
ERROR: /Users/stephan/workspace/examples/cpp-tutorial/stage1/main/BUILD:1:1: Stripping main/hello-world.stripped for //main:hello-world failed (Exit 1).
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: only one -R option allowed
Target //main:hello-world.stripped failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.078s, Critical Path: 0.40s
```

Using `--verbose_failures` shows that strip command is

```
/usr/bin/strip -S -o bazel-out/darwin_x86_64-fastbuild/bin/main/hello-world.stripped -R .gnu.switches.text.quote_paths -R .gnu.switches.text.bracket_paths -R .gnu.switches.text.system_paths -R .gnu.switches.text.cpp_defines -R .gnu.switches.text.cpp_includes -R .gnu.switches.text.cl_args -R .gnu.switches.text.lipo_info -R .gnu.switches.text.annotation bazel-out/darwin_x86_64-fastbuild/bin/main/hello-world
```

Xcode's strip command does not accept section names for the `-R` flag. It's a flag for specifying a file containing symbol names to be stripped.

### Environment info
* Operating System:
macOS Sierra 10.12.6, XCode 8.3.3

* Bazel version (output of `bazel info release`):
release 0.6.0- (@non-git)

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
Compiled from the distribution at https://github.com/bazelbuild/bazel/releases/download/0.6.0/bazel-0.6.0-dist.zip

**Comment by zuercher** [comment]
I can submit a PR to fix this, modifying `rc/main/java/com/google/devtools/build/lib/rules/cpp/CppActionConfigs.java`.  However, it seems that I would also need to regenerate `tools/osx/crosstool/CROSSTOOL.tpl` which has a comment indicating it's generated by an internal Google tool.

Is it sufficient to patch CppActionConfigs.java and assume that regeneration of CROSSTOOL.tpl will happen as needed?

**Comment by jmillikin-stripe** [comment]
Should be fixed by https://github.com/bazelbuild/bazel/pull/4029
See also: https://github.com/bazelbuild/bazel/issues/4028

**Comment by mhlopko** [comment]
Importing the fix, pending internal review.

**Comment by jmillikin-stripe** [comment]
This is fixed now, right?

**Comment by mhlopko** [comment]
Yes :) Thanks for patience and thanks @jmillikin-stripe for contributing! :)
