### ISSUE TITLE
environment variables reduce remote cache effectiveness

### ISSUE THREAD

**Issue by ola-rozenfeld** [bazelbuild/bazel#3847]
When remote execution and caching are enabled, Bazel commands often include environment variables such as PATH, USER, and TMPDIR. These variables contain values specific to the local execution, and cannot be helpful to remote execution. Moreover, they make remote cache not effective, because environment variables are part of the resulting action key.
So a user executing compilation of hello-world.cc into hello-world.o will not get a remote cache hit, because their PATH contained /usr/local/alice instead of /usr/local/bob.

We need to sanitize spawn environment before it gets sent to remote caching/execution.
See also b/67045247 internally.

**Comment by ola-rozenfeld** [comment]
@ulfjack @buchgr

**Comment by benjaminp** [comment]
I think this supposed to be (partially?) addressed by the work on #2574.

**Comment by ola-rozenfeld** [comment]
Oh, thank you, I missed these earlier reports! I will use --experimental_strict_action_env in our runs for now. This is really a duplicate of https://github.com/bazelbuild/bazel/issues/2574, then.

**Comment by aehlig** [comment]
closing, as it is a duplicate.
