### ISSUE TITLE
No such package bazel windows

### ISSUE THREAD

**Issue by atkawa7** [bazelbuild/bazel#3848]
### Description of the problem / feature request / question:

 ```
git clone https://gerrit.googlesource.com/gitiles
bazel build //...
bazel test //...
```
![image](https://user-images.githubusercontent.com/5673828/31052280-29faaa94-a635-11e7-8c5a-b2aef8a06079.png)

**Comment by aehlig** [comment]
To make the report more self-contained, here the relvant excerpts of the mentioned repoistory `https://gerrit.googlesource.com/gitiles`.

The `WORKSPACE` file contains

```
maven_jar(
    name = "servlet_api_2_5",
    artifact = "org.eclipse.jetty.orbit:javax.servlet:2.5.0.v201103041518",
    sha1 = "9c16011c06bc6fe5e9dba080fcb40ddb4b75dc85",
)
```
And `lib/BUILD` contains

```

[java_library(
    name = n,
    exports = ["@%s//jar" % n.replace("-", "_")],
) for n in [
    "autolink",
    "commonmark",
    "commons-lang3",
    "cm-autolink",
    "gfm-strikethrough",
    "gfm-tables",
    "html-types",
    "jsr305",
    "joda-time",
    "servlet-api_2_5",
    "servlet-api_3_0",
    "truth",
    "gson",
    "guava",
    "prettify",
]]
```

**Comment by laszlocsomor** [comment]
I see different errors with 0.5.4 and 0.6.0:

```
C:\work\gerrit-gitiles>c:\work\bazel-0.5.4\bazel.exe --nomaster_bazelrc --bazelrc=nul build //...
.............
ERROR: C:/work/gerrit-gitiles/lib/guice/BUILD:16:2: no such package '@guice_assistedinject//jar': Argument 0 of execute is neither a path nor a string. and referenced by '//lib/guice:guice-assistedinject'.
ERROR: Analysis of target '//tools/maven:gen_api_deploy' failed; build aborted.
INFO: Elapsed time: 9.981s

C:\work\gerrit-gitiles>c:\work\bazel-0.6.0\bazel.exe --nomaster_bazelrc --bazelrc=nul build //...
.............
ERROR: C:/work/gerrit-gitiles/lib/jetty/BUILD:44:1: no such package '@io//jar': failed C:/Python27/python.exe C:/users/laszlocsomor/appdata/local/temp/_bazel_laszlocsomor/xsc8h-xb/external/com_googlesource_gerrit_bazlets/tools/download_file.py -o C:/users/laszlocsomor/appdata/local/temp/_bazel_laszlocsomor/xsc8h-xb/external/io/jar/jetty-io-9.3.18.v20170406.jar -u MAVEN_CENTRAL:/org/eclipse/jetty/jetty-io/9.3.18.v20170406/jetty-io-9.3.18.v20170406.jar -v 36cb411ee89be1b527b0c10747aa3153267fc3ec: Traceback (most recent call last):
  File "C:/users/laszlocsomor/appdata/local/temp/_bazel_laszlocsomor/xsc8h-xb/external/com_googlesource_gerrit_bazlets/tools/download_file.py", line 20, in <module>
    from os import link, makedirs, path, remove
ImportError: cannot import name link
 and referenced by '//lib/jetty:io'.
ERROR: Analysis of target '//tools/eclipse:main_classpath_collect' failed; build aborted.
INFO: Elapsed time: 11.100s
```

**Comment by laszlocsomor** [comment]
IIUC this is the offending line: https://gerrit.googlesource.com/bazlets/+/a615d69786a965e9622761ff2229446115732cca/tools/download_file.py#20

**Comment by laszlocsomor** [comment]
This could be a Python2 vs. Python3 issue. Using Python3 I got past the point where this error would come, but I killed the process after 10 minutes because it was eating up all my CPU with python.exe subprocesses, while Bazel was still loading.

**Comment by atkawa7** [comment]
@laszlocsomor @aehlig  Still the same problem
![image](https://user-images.githubusercontent.com/5673828/31079061-41ff3470-a739-11e7-91db-7b783d9a8460.png)

**Comment by laszlocsomor** [comment]
@atkawa7 : Did you try with Bazel 0.6.0? I believe there's a bug in 0.5.4, see [my earlier comment](https://github.com/bazelbuild/bazel/issues/3848#issuecomment-333453721).

**Comment by atkawa7** [comment]
@laszlocsomor Thanks. I have upgraded bazel. But now its hogging CPU. Hopeful its going to complete without hiccups

**Comment by atkawa7** [comment]
@laszlocsomor @aehlig Still fails 
![image](https://user-images.githubusercontent.com/5673828/31080497-b120bc8a-a73d-11e7-9b87-894b7613bde1.png)

**Comment by atkawa7** [comment]
@aehlig @laszlocsomor  On my windows machine. These lines in `download.py` never completes
```python
root_dir = args.o
while root_dir and root_dir != "/":
  root_dir, n = path.split(root_dir)
  if n == 'buck-out':
    break
```

**Comment by atkawa7** [comment]
@aehlig @laszlocsomor I change the line to 

```python
while root_dir and root_dir != "/" and root_dir != "C:\\" and root_dir != "C:/":
```
And now I get the following error
```
ERROR: C:/users/allen/downloads/gitiles/java/com/google/gitiles/blame/cache/BUILD:13:1: every rule of type java_doc implicitly depends upon the target '@local_jdk//:bin/javadoc', but this target could not be found because of: no such target '@local_jdk//:bin/javadoc': target 'bin/javadoc' not declared in package '' (did you mean 'bin/javac'?) defined by C:/users/allen/appdata/local/temp/_bazel_allen/avyowy2q/external/local_jdk/BUILD.bazel.
ERROR: Analysis of target '//tools/maven:gen_api_install' failed; build aborted.
INFO: Elapsed time: 2.380s
```

**Comment by atkawa7** [comment]
@aehlig @laszlocsomor changed it to bin/javadoc.exe and it worked. The war file is failing to build. That's because of they are using a none crossplatform script from this #2009. But the `dev.exe` builds fine. Thank you all for your help.

**Comment by laszlocsomor** [comment]
@atkawa7 : Nice catch with that bug! Cool that it's working now.

I recommend checking for any drive on Windows:
```
import os
import path

(...)

def _IsRootDir(s):
  if os.name == "nt":
    return os.path.isabs(root_dir) and len(os.path.normpath(root_dir)) == 3
  else:
    return s == "/"

(...)

while root_dir and not _IsRootDir(root_dir):
```

**Comment by joegana** [comment]
@atkawa7 
![default](https://user-images.githubusercontent.com/7437859/36705541-ac60e418-1ba0-11e8-9f27-9de216f07e8d.png)
Try edit this file with path on this picture to add javadoc target
