### ISSUE TITLE
HttpDownloader connection timeout causes "build interrupted" error.

### ISSUE THREAD

**Issue by ondrasej** [bazelbuild/bazel#3851]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem:

User perspective: When HTTP connection times out when downloading a dependency via new_http_archive(), bazel build ends with error message "build interrupted" and no additional details. This error message is wrong, as it points to a wrong direction, and does not provide any additional pointers for debugging the problem.

Technically: When there is a new_http_archive() that times out, the com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorMultiplexer#connect call in 
com.google.devtools.build.lib.bazel.repository.downloader.HttpDownloader#download, line 201, throws InterruptedIoException. This causes the HttpDownloader to throw InterruptedException, which is then 
caught in com.google.devtools.build.lib.buildtool.BuildTool#processRequest, line 353, and interpreted as user interrupt.

I've debugged this on/line numbers come from: https://github.com/bazelbuild/bazel/releases/download/0.6.0/bazel-0.6.0-dist.zip.

### If possible, provide a minimal example to reproduce the problem:

In the WORKSPACE file, have a new_http_archive() rule with an URL that causes connection timeouts.
Run "bazel build ...".

A not so minimal example:
```bash
git clone https://github.com/google/EXEgesis.git
cd EXEgesis
git checkout a7f455bbeb8be7bf16b188986996d6ab2542961e
bazel build ...
```

### Environment info
* Operating System: Linux (Ubuntu, Arch), OS X
* Bazel version (output of `bazel info release`): release 0.6.0

###  Have you found anything relevant by searching the web?
I didn't find any posts or threads referring to this problem.

**Comment by aehlig** [comment]
Thanks for the detailed bug report. This is indeed a misleading way of error handling.

**Comment by TravisWhitaker** [comment]
Just hit this myself; surprised there's not more activity on this.

**Comment by ctiller** [comment]
I think I'm seeing this also.

**Comment by ccl0326** [comment]
I'm seeing this too, and this error is a little obscure.
