### ISSUE TITLE
Please add --proto_toolchain_for_objectivec option

### ISSUE THREAD

**Issue by thaidn** [bazelbuild/bazel#3854]
Similar to --proto_toolchain_for_cc, this option should tell Bazel how to compile ObjC protos. I need it so that I can configure a different toolchain, rather than the default "@com_google_protobuf_objc//:objectivec".

Thanks!

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
