### ISSUE TITLE
Cache invalidation based on binary timestamp for genrule

### ISSUE THREAD

**Issue by viveksjain** [bazelbuild/bazel#3856]
### Description of the problem / feature request / question:

Suppose I have genrule which calls out to `mybinary`. I do a build, then change/upgrade `mybinary`, which modifies its behavior. It seems bazel does not pick up this change and will happily use the old output.

Of course, in the general case, to truly ensure correctness bazel would have to check that nothing inside its sandbox changed, which is infeasible. But what do you think about just checking the timestamp of any binary that is called directly? Seems like a more reasonable middle ground. Alternatively, is there an easy way to define cache invalidation rules for a genrule?

Also, does this affect other build rules, e.g. cc_* if the version of gcc changes?

### Environment info
* Operating System: Linux
* Bazel version (output of `bazel info release`): release 0.5.3

###  Have you found anything relevant by searching the web?
Nada

**Comment by aehlig** [comment]
It is a known issue that bazel does not track dependencies on the ambient system environment. Arguably we should do so in some way (maybe have something like declared external tools that get checksummed in the same way as dependencies from within the `WOKRSPACE`?). In any case, I think that requires a larger design discussion.

@dslomov @laurentlb FYI as this is related to Skylark interfaces.

**Comment by dslomov** [comment]
I do not think we have any clear path for implementation here. The only consistent implememtation idea I have is a sandbox implementation that tracks file acccesses. I am re-categorizing this for team-LocalExec (because sandboxing), but unless someone has a clever idea for implementation, this will be wishful thinking

**Comment by jmmv** [comment]
I think this is unfeasible for any tools not specified as inputs to a rule. There are, of course, ways to do this (with kernel support) but they are too expensive. So... I don't think we can do this.
