### ISSUE TITLE
We need a way to build modes in toolchain construction

### ISSUE THREAD

**Issue by ianthehat** [bazelbuild/bazel#3858]
The specific examples at the moment are we need access to the `--compilation_mode` and `--strip` command line arguments in order to configure the go toolchain correctly.
Because the toolchain is constructed in a place where only the host configuration is available, they always appear as `opt` and `always` if you just use config_setting and select.
The only way round this right now is to have the toolchain functions read a hidden attribute of the rule they are being invoked for, and have the select in or below that parameter. This means that to use a toolchain you have to add a special hidden attribute as well as declaring that you want the toolchain, which is not an ideal solution.

It is also not unreasonable that you should be able to use then to control toolchain selection as well (for instance picking a gcc toolchain for opt and an llvm one for dbg).

To meet these goals I propose we expose the values directly as constraints, and add a system to toolchains to let them read the values of constraints that did not directly affect their selection. This would allow them to either pick a toolchain (in which case the know the value), register the same underlying toolchain against mutiple constraint sets and detect which one was selected, or just configure themselves based on the value of a constraint.

**Comment by katre** [comment]
This is now possible with custom transitions.
