### ISSUE TITLE
/usr/local/include is not a standard cpp include path on OS X

### ISSUE THREAD

**Issue by onponomarev** [bazelbuild/bazel#3860]
### Description of the problem / feature request / question:

subj. I needed it to link with glog and gflags.I tried to add /usr/local/include to different environment variables but it resulted into nothing.
Also, I tired to create a workaround by creating a custom toolchain but it resulted into #3859 

### Environment info
* Operating System:

MaxOS Sierra 10.12.6

```
$ xcode-select -v
xcode-select version 2347.
```

```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

```
* Bazel version (output of `bazel info release`):

release 0.6.0-homebrew

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?

Not really.

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by c-parsons** [comment]
I don't understand the issue you are having at all based on your description here. I'm sorry.
Can you restate?

Are you trying to add additional link options to your cpp builds on OSX?

**Comment by onponomarev** [comment]
Thanks for you reply.

It's a very minor issue and it might be fixed with additional flags.
Still, the //tools/cpp/CROSSTOOL file looks inconsistent:
- on linux ("local_linux") and freebsd you have the following:
   cxx_builtin_include_directory: "/usr/lib/gcc/"
   cxx_builtin_include_directory: "/usr/local/include"
   cxx_builtin_include_directory: "/usr/include"
- for mac ("darwin") it's just:
   cxx_builtin_include_directory: "/";

This looks strange because /usr/local/include is typically used for custom dev libraries installations both on linux and on osx.

This wouldn't be a problem at all because on osx, there is a custom logic implemented in //tools/cpp/osx_cc_wrapper.sh, but somehow it doesn't import the default include search path from Xcode setup.

Hope, I clarified the issue:)

**Comment by c-parsons** [comment]
As far as I know,`cxx_builtin_include_directory: "/"` is strictly more relaxed than the other options.. I believe anything recursively under `/` is thus treated as an acceptable include directory.

What is the actual error you are encountering? I wouldn't recommend simply trying to make the OSX crosstool entry look more like the linux crosstool entry.

To help me address your specific issue, it would help if you showed the error you are seeing, as well as what you are specifically trying to do and what steps you have currently taken.
For example, "I am trying to build a cc_library target on OSX with additional link options, and I am seeing <bazel error here>" would help me to help you. :)
