### ISSUE TITLE
Some Python imports unavailable in cmd of genrule

### ISSUE THREAD

**Issue by LyraSolomon** [bazelbuild/bazel#3861]
I am trying to use a genrule written in Python to process c++ structs and output functions to log those structs. In the process I found I was unable to import libclang when the script was called as a genrule, although I was able to run the script by calling `bazel run` directly.

I am using Bazel (201603050101~+5dff9cd) on Ubuntu 16.04 LTS.

I have created a minimal example that replicates the issue.

`test/BUILD`:
```Python
py_binary(
    name = "sample_script",
    srcs = ["sample_script.py"],
)
genrule(
    name = "sample_genrule",
    tools = [":sample_script"],
    cmd = "$(location :sample_script)",
    outs = ["output.h"],
)
cc_library(
    name = "sample_genrule_user",
    hdrs = ["output.h"],
    srcs = ["genrule_user.cpp"]
)
```

`test/sample_script.py`:
```Python
import clang
print ("got here")
```

`WORKSPACE` and `test/genrule_user.cpp` are empty.

`bazel build test:sample_genrule_user` yields `ImportError: No module named clang`,
however, `bazel run test:sample_script` yields `got here`.

I tested a few other imports to check whether this was only an issue with libclang. Numpy and sys are able to be imported in genrules, while tkinter cannot be imported either.

Any help would be greatly appreciated.

**Comment by LyraSolomon** [comment]
Update: I found that downgrading to 0.6.1 fixes the issue on my end, but the most recent version is still not working.

**Comment by aehlig** [comment]
@lberki can you have a look? To me it looks like a bug, that a `py_binary` behaves differently in `run` and as a `tool` in a genrule, but you know the intended semantics of the python rules better.

**Comment by ocurr** [comment]
Has there been any movement on this issue? I'm seeing the same problem on 0.9.0.

**Comment by lberki** [comment]
Erm, this somehow escaped my notice -- I'm not *entirely* surprised that `py_binary` rules behave differently under `run` and under `test`; not that they should, but the environment they run in are slightly different and it's entirely possible that that throws off the Python interpreter.

The Python rules are revamped at the moment. The discussions happen on https://groups.google.com/forum/#!forum/bazel-sig-python, and the consensus seems to be that it's a bad idea to depend on packages installed on the system "just like that" and if you want to import something, there should always be a dependency on it. See this thread:

https://groups.google.com/d/msg/bazel-sig-python/ibYbTuF-KpI/xEfYSLK2BQAJ

With that in mind, I'll close this bug as obsolete; please do participate in the discussion there if you want your voice heard!
