### ISSUE TITLE
skylark - add attr.string_dict_dict

### ISSUE THREAD

**Issue by MarkusTeufelberger** [bazelbuild/bazel#3862]
### Description of the problem / feature request / question:

I'd like to create a build rule as follows:

```
rule_name(
  name = "foo",
  files = {
    "foo1": {"URL": "http://example.com/foo1", "SHA256": "1234..."},
    "foo2": {"URL": "http://example.com/foo2", "SHA256": "2345..."},
    ...
  }
)
```

Currently I'm circumventing this issue by having 2 https://docs.bazel.build/versions/master/skylark/lib/attr.html#string_dict that have to have the same keys. Not ideal, but ok for just 2 parameters.

I'd like to have 1-2 parameters more though, and now it gets really into "DRY" territory and keeping information that belongs together also visually in the same place.

A workaround would be to use a https://docs.bazel.build/versions/master/skylark/lib/attr.html#string_list_dict and force users to have the elements of the list in a certain order (first URL, then hash...). This is far from ideal though and seems quite arbitrary.

Having a dict of string keys map to an inner dict with string keys and values would be ideal.

### If possible, provide a minimal example to reproduce the problem:

see above

###  Have you found anything relevant by searching the web?

Apparently the mostly Google-internal `Fileset` rules allow handing over a function with parameters according to mattmoor's comments on https://github.com/GoogleCloudPlatform/distroless/pull/94 but according to https://www.bazel.build/support.html#unstable concerning `Fileset` rules: "we do not intend to support them in Bazel, ever".

**Comment by Globegitter** [comment]
There is also an interesting comment on bazel-watcher on supporting a multi-binary target that also allows to set args and environment variables in code. See: https://github.com/bazelbuild/bazel-watcher/pull/133#issuecomment-426425064 for an example.

**Comment by brandjon** [comment]
While the current set of attribute types might not be ideal, we're generally against adding new ones. See [this comment](https://github.com/bazelbuild/bazel/blob/e2c91cc330179b638e3b88b2fd5ba4db63e0e1ce/src/main/java/com/google/devtools/build/lib/packages/Type.java#L58-L80) for an explanation.
