### ISSUE TITLE
Windows: bootstrapping broken with Bazel 0.6.0

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3863]
Boostrapping from the 0.6.0 dist archive is broken on Windows, because `//src/main/native:jni.h` is a generated file, included from `//src/main/native/windows/*`, but not part of the dist archive.

```
laszlocsomor@laszlocsomor0-w MSYS /c/tempdir/bazel-0.6.0-bootstrap
$ ./compile.sh
🍃  Building Bazel from scratch......**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Microsoft (R) C/C++ Optimizing Compiler Version 19.10.25019 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

file-jni.cc
C:\tempdir\bazel-0.6.0-bootstrap\src\main\native\windows\file-jni.cc(24): fatal error C1083: Cannot open include file: 'src/main/native/jni.h': No such file or directory
file.cc
jni-util.cc
.\src/main/native/windows/jni-util.h(19): fatal error C1083: Cannot open include file: 'src/main/native/jni.h': No such file or directory
processes-jni.cc
C:\tempdir\bazel-0.6.0-bootstrap\src\main\native\windows\processes-jni.cc(25): fatal error C1083: Cannot open include file: 'src/main/native/jni.h': No such file or directory
util.cc
Generating Code...
```

**Comment by laszlocsomor** [comment]
I'm wondering why we didn't see this on CI o_O

**Comment by laszlocsomor** [comment]
`src/main/native/windows/build_windows_jni.sh` is supposed to mimic the `//src/main/native:jni.h` genrule: https://github.com/bazelbuild/bazel/blob/b4ebfd724d33223ac78190be88c6f8704c249651/src/main/native/windows/build_windows_jni.sh#L88-L92.

The culprit is that VSTEMP is an MSYS path under `/tmp`, so cl.exe in windows_jni.bat cannot use it.

**Comment by damienmg** [comment]
Humm should we do another patch release?

Is the bootstrap test running on windows? I remember we had to turn it down waiting for a release but maybe we forgot to readd it.

**Comment by katre** [comment]
Do we know what the fix for this is? If it's still under investigation, I'd like to release 0.6.1 to improve mac users' experience, and then we can do 0.6.2 with the fix for this when we have it.

**Comment by laszlocsomor** [comment]
I'm working on a fix. There are multiple problems, I already fixed two, there's at least one more.

**Comment by laszlocsomor** [comment]
https://bazel-review.googlesource.com/c/bazel/+/18030
