### ISSUE TITLE
Windows, native launcher: sh_binary doesn't have `rlocation`

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3865]
When using the native launcher, the .exe launcher created from sh_binary rules doesn't define `rlocation` for the shell script.

Normally `rlocation` is defined for shell tests because they all run https://github.com/bazelbuild/bazel/blob/master/tools/test/test-setup.sh which defines and exports this function.

**Comment by laszlocsomor** [comment]
Fixing this bug makes fixing https://github.com/bazelbuild/bazel/issues/3839 trivial.

**Comment by meteorcloudy** [comment]
Not actually, because when you run the binary alone, `test-setup.sh` won't be executed at all, right?

I am thinking about adding a library under @bazel_tools, which provides rlocation function for Java/Python/Bash/C++, so that users can just depend on it and don't have to write their own. WDYT?

**Comment by laszlocsomor** [comment]
That's similar to what I did in my pending change that fixes this issue. I'll send it to you for review soon.

**Comment by meteorcloudy** [comment]
Great, thanks!

**Comment by laszlocsomor** [comment]
Actually, I like your idea more than my own! Let me accommodate that in my CL.

**Comment by laszlocsomor** [comment]
For the record, this was my approach: https://bazel-review.googlesource.com/c/bazel/+/18250 .

**Comment by laszlocsomor** [comment]
I'm making this P3 with the same justification as I gave on https://github.com/bazelbuild/bazel/issues/3839:

> This bug directly influences the usability of `sh_*` rules on Windows.
>
> I'd like Bazel to treat shell scripts as just another language like Python, and to require Bash only if the targets depend on `sh_*` rules.
>
> I'm making this P3 for now, because I believe other languages are more important on Windows and the practical limitation with a sub-par support for `sh_*` rules is that we can't use them to implement build-aiding tools as easily as we can on Linux.

**Comment by laszlocsomor** [comment]
I'm closing this bug as obsolete.

The sh_binary on non-Windows uses no launcher, so there's nothing to load whatever defines `rlocation`. If users want to write platform-independent sh_* rules, they'll need to source the rlocation-defining library manually (copy-pasting the code to do so from the runfiles library itself).

Automatically sourcing the file on Windows encourages writing non-portable Bash scripts, and is unnecessary if the scripts will have the copy-pasted initializer code anyway.
