### ISSUE TITLE
How do I use an input binary as the test executable in Skylark?

### ISSUE THREAD

**Issue by pspeter3** [bazelbuild/bazel#387]
It seems like that tests need to generate an executable. I want to execute my input binary but cannot find a good way of making that work. My leading theory right now is to set the `dirname` to the `$PATH` and run the `basename`

**Comment by pspeter3** [comment]
I named the binary test which is being overridden by the bash command named test when I do that.

**Comment by hanwen** [comment]
the binary should have the same name as the test rule, eeg.

  foo_test(name = "bla_test"  .. )

should generate a bla_test binary.  Normally, you do this by reusing the xx_binary rule, eg. 

  https://github.com/google/bazel/blob/master/tools/build_rules/java_rules_skylark.bzl#L245

if you want more detailed help, it would help a lot if you could show a snippet of the faulty code.

**Comment by kchodorow** [comment]
Do you mean something like this?

def impl(ctx):
    ctx.action(
        inputs = [],
        command = "%s -and -some -args" % ctx.file.my_bin.path,
        outputs = [ctx.outputs.executable]
    )

scala_binary = rule(
    attrs = {
        'my_bin': attr.label("//my-prereq",
            executable=True,
            allow_files=True,
            single_file=True),
...
)

Or similar if you want the output from one action to be used in the command
for the next.

**Comment by pspeter3** [comment]
Yeah, exactly. It seems to work in other cases. I think this may be because we're running an outdated version of bazel but it seems like the cwd for binaries and tests are not the same so binaries do not have their runfiles in consistent places.

**Comment by kchodorow** [comment]
Do you have an example you should show us?  The runfiles should be in a consistent place.

**Comment by damienmg** [comment]
Closing as obsolete, ping if you have update.

**Comment by jianxingliu** [comment]
now, native_test maybe the solution.
https://github.com/bazelbuild/bazel-skylib/blob/main/docs/native_binary_doc.md
