### ISSUE TITLE
Support Python 2 and 3 in the same build

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel#3871]
Context: https://groups.google.com/d/msg/bazel-discuss/nVQ48R94S_8/xbMi3_RWBwAJ

Active work is going on for this (code in review inside Google). Follow this bug to track.

**Comment by gregestren** [comment]
https://github.com/bazelbuild/bazel/commit/8b5bf1f440ef8d140eb3843861fbce65709438ea puts in core support for building with both Python 2 and 3 in the same invocation. 

I think we'll have to do some more tweaks to properly integrate the Python top, etc. But keep an eye out for this functionality, which alone might go a long way.

**Comment by brandjon** [comment]
Closing this as dup: Let's use #4815 to track being able to at least run the "python3" command when the mode is set to PY3, and #3517 to track the broader problem of specifying/overriding the particular py2/py3 runtimes used.
