### ISSUE TITLE
bazel, distcc and remote execution?

### ISSUE THREAD

**Issue by tomazos** [bazelbuild/bazel#3875]
We are currently using bazel with distcc on a 300 package, 900 target (mostly C++), 35000 action WORKSPACE - and a full build takes 10 mins (profile included below).  (If we switch off distcc and compile locally, a full build takes 60 mins) We have achieved this by writing a CROSSTOOL file that references a gcc wrapper script that forwards the arguments to distcc gcc, and then placed the following:

```
build --jobs=600
build --local_resources="15000,30,10"
```

in our bazelrc.  The problem is that, at this level of parallelism, while great for the C++ compilation steps, is bad for the other non C++ compilation steps, like for example C++ linking, test execution and so on - because they run locally.  Frankly, it feels like a bit of a hack.

Is it the intention that the remote execution feature of bazel will eventually replace distcc and be as performant as it?

Currently we have a set of dedicated machines running distcc servers, and then these are listed in the DISTCC_HOSTS environment variable - so when bazel calls distcc gcc it will connect to a random one of the available servers to farm out the compile.  We have many developers simulatenously using bazel to build on their workstations, all sharing this distcc server farm.

Is it currently possible to replace that setup with `remote_worker`?  Is the idea that instead of the distcc servers we will run `remote_worker` instances on the dedicated servers?

Is it possible to get this setup working currently?  If so, what command do I execute to start the remote workers running on the servers?  How do I configure the bazelrc to specify those available remote workers and tell it to use them?

Also, given the description of what we are doing, does the below profile look healthy?

Thanks for your help.

```
=== PHASE SUMMARY INFORMATION ===

Total launch phase time          550 ms    0.09%
Total init phase time           98.1 ms    0.02%
Total loading phase time        1.340 s    0.22%
Total analysis phase time       3.772 s    0.61%
Total preparation phase time    15.3 ms    0.00%
Total execution phase time    611.332 s   99.06%
Total finish phase time         40.8 ms    0.01%
Total run time                617.148 s  100.00%

=== INIT PHASE INFORMATION ===

Total init phase time                    98.1 ms

Total time (across all threads) spent on:
              Type    Total    Count     Average

=== LOADING PHASE INFORMATION ===

Total loading phase time                 1.340 s

Total time (across all threads) spent on:
              Type    Total    Count     Average
    CREATE_PACKAGE    8.30%      339     2.66 ms
          VFS_STAT    0.55%      912     0.07 ms
           VFS_DIR    2.47%      886     0.30 ms
          VFS_OPEN    0.11%      331     0.04 ms
          VFS_READ    0.01%      330     0.00 ms
         VFS_WRITE    0.00%        1     0.01 ms
          VFS_GLOB   21.17%     1839     1.25 ms
     SKYFRAME_EVAL   11.97%        3      433 ms
       SKYFUNCTION   42.57%    94382     0.05 ms
     SKYLARK_LEXER    0.26%      360     0.08 ms
    SKYLARK_PARSER    1.52%      360     0.46 ms
   SKYLARK_USER_FN    1.17%      429     0.30 ms
SKYLARK_BUILTIN_FN    9.52%     2179     0.47 ms

=== ANALYSIS PHASE INFORMATION ===

Total analysis phase time                3.772 s

Total time (across all threads) spent on:
              Type    Total    Count     Average
    CREATE_PACKAGE    0.04%       16     2.30 ms
          VFS_STAT    0.19%     2631     0.07 ms
           VFS_DIR    3.48%     2278     1.57 ms
          VFS_OPEN    0.00%       14     0.04 ms
          VFS_READ    0.00%       14     0.01 ms
          VFS_GLOB    2.39%     4942     0.50 ms
     SKYFRAME_EVAL    3.09%        1     3.193 s
       SKYFUNCTION   89.66%    85650     1.08 ms
     SKYLARK_LEXER    0.00%       23     0.04 ms
    SKYLARK_PARSER    0.01%       23     0.37 ms
   SKYLARK_USER_FN    0.00%        2     0.44 ms
SKYLARK_BUILTIN_FN    0.59%      295     2.07 ms

=== EXECUTION PHASE INFORMATION ===

Total preparation time                   15.3 ms
Total execution phase time             611.332 s
Total time finalizing build              40.8 ms

Action dependency map creation           0.00 ms
Actual execution time                  611.332 s

Total time (across all threads) spent on:
              Type    Total    Count     Average
            ACTION    0.06%    36219     8.79 ms
      ACTION_CHECK    0.00%        4     30.7 ms
    ACTION_EXECUTE    5.42%    36219      762 ms
       ACTION_LOCK   43.35%     6829    32.330 s
    ACTION_RELEASE    0.00%     6846     0.20 ms
     ACTION_UPDATE    0.00%     5051     0.00 ms
   ACTION_COMPLETE    0.03%    36219     3.60 ms
              INFO    0.00%        1     0.00 ms
          VFS_STAT    0.00%  2864398     0.01 ms
           VFS_DIR    0.00%    68094     0.02 ms
      VFS_READLINK    0.00%   136758     0.01 ms
           VFS_MD5    0.01%    41612     0.68 ms
        VFS_DELETE    0.19%   531371     1.80 ms
          VFS_OPEN    0.00%     7128     0.95 ms
          VFS_READ    0.00%    38453     0.00 ms
         VFS_WRITE    0.00%     2707     0.01 ms
              WAIT    0.80%    28548      143 ms
     SKYFRAME_EVAL    0.12%        1   611.230 s
       SKYFUNCTION   50.03%   317700      802 ms

```

**Comment by mhlopko** [comment]
@philwo @ulfjack @buchgr

**Comment by ulfjack** [comment]
We have no intention to support distcc, as it's a C++-only 'solution', and our experience with it has not been good. It might be possible to convince me to put in a workaround to make Bazel work better with distcc. For example, we could mark such actions in some way that tells Bazel that these are actually remote actions so it doesn't count them as local (allowing you to run many without --local_resources).

Our intent is that remote execution will cover your use case. There is currently one open source project to implement a remote execution system here:
https://github.com/bazelbuild/bazel-buildfarm

I have not personally tried running this, so I don't know how well it works, but it might be worth a try.

**Comment by buchgr** [comment]
I believe this issue can be closed. @tomazos remote execution has made huge leaps in the past year and a half and should be ready for you to try as a replacement of distcc.

**Comment by liujiwei777** [comment]
Now, bazel can only use remote cache. I suggest combine distcc and remote cache, such can reduce the first time compile time.

**Comment by buchgr** [comment]
@liujiwei777 that's not correct. See e.g. https://github.com/EdSchouten/bazel-buildbarn

**Comment by liujiwei777** [comment]
@buchgr Thank you!
