### ISSUE TITLE
.deb packaging uses Unix epoch for file mod time. Ubuntu Software Center complains about this

### ISSUE THREAD

**Issue by jsonsystems** [bazelbuild/bazel#3876]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

When installing latest  release `bazel_0.6.1-linux-x86_64.deb`, Ubuntu Software Center reports

> The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.

```
**Lintian check results for /usr/local/google/home/jackwootton/Downloads/bazel_0.6.1-linux-x86_64.deb:
E: bazel: package-contains-ancient-file etc/ 1970-01-01
E: bazel: package-contains-ancient-file etc/bash_completion.d/ 1970-01-01
E: bazel: package-contains-ancient-file etc/bash_completion.d/bazel 1970-01-01
E: bazel: package-contains-ancient-file etc/bazel.bazelrc 1970-01-01
E: bazel: package-contains-ancient-file usr/ 1970-01-01
E: bazel: package-contains-ancient-file usr/bin/ 1970-01-01
E: bazel: package-contains-ancient-file usr/bin/bazel 1970-01-01
E: bazel: package-contains-ancient-file usr/bin/bazel-real 1970-01-01**
_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._
```

### Environment info
* Operating System: Ubuntu 14.04 Trust (x86-64)
* Linux Kernel: 4.4.0-96-generic

* Bazel version (output of `bazel info release`):
`release 0.5.2`

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by aiuto** [comment]
There is no easy win here. We want packaging to use epoch a default time stamp so builds are reproducible. For package creation, we should have --stamp create files with current time as the stamp. We'll need the release build chain to use --stamp.

**Comment by aehlig** [comment]
> There is no easy win here. We want packaging to use epoch a default time stamp so builds are reproducible.

We can also be reproducible with meaningful timestamps, e.g., honoring [`SOURCE_DATE_EPOCH`](https://reproducible-builds.org/specs/source-date-epoch/) and setting it to the commit date of the commit we build for (something planned for our release pipeline anyway, cc @philwo).

**Comment by aiuto** [comment]
I was talking more about other user of pkg_deb, not bazel's own packaging. (Which is not really EngProd's problem).
But yes, we should have a valid build time on the packages in our distribution.

**Comment by meisterT** [comment]
This is fixed at HEAD.
