### ISSUE TITLE
Windows: "data" dependencies does not link to ".runfiles"

### ISSUE THREAD

**Issue by eustas** [bazelbuild/bazel#3881]
### If possible, provide a minimal example to reproduce the problem:
`BUILD` file:
```
filegroup(
    name = "some_data",
    srcs = ["some_data.txt"],
)
java_test(
    name = "SomeDataTest",
    srcs = ["SomeDataTest.java"],
    data = [":some_data"],
    jvm_flags = ["-DSOME_DATA=$(location :some_data)"],
    deps = ["@junit_junit//jar"],
)
```

Result: `SomeDataTest` can't read file at `System.getProperty("SOME_DATA")`
Path looks OK, but there is no corresponding file in `.runfiles`.

### Environment info
* Operating System:
Fails on Windows
Works fine on OSX, Linux

* Bazel version (output of `bazel info release`):
0.6.1 windows binary distro

**Comment by eustas** [comment]
Correct entry appears in `.runfiles_manifest`. But this doesn't help at all, as there is no API to use it.

**Comment by dslomov** [comment]
We do not have an API to read `.runfiles_manifest` but it is fairly trivial: https://github.com/bazelbuild/bazel/blob/259c9e8014ad960985c0ed99db2a879cdd2ac301/src/main/java/com/google/devtools/build/lib/windows/runfiles/WindowsRunfiles.java#L27

**Comment by eustas** [comment]
Thanks.
Unfortunately this solution does not align nicely with "multiple-build-system" concept: use different build systems should use the same source code.

**Comment by dslomov** [comment]
We are open to suggestions on how to fix it.
Creating symlinks on Windows is not really an option as it requires admin privileges.

**Comment by eustas** [comment]
Perhaps, least intrusive way is to update `$location` behavior, or make an alternative to it.
Since reading files pointed in manifest already breaks the concept of sandboxing, it won't make the things worse, if `$location` would point to absolute file path.
Such change would instantly fix my [project](https://github.com/google/brotli/blob/master/java/org/brotli/wrapper/enc/BUILD#L81) build on Windows (without touching neither BUILD files, nor sources)

**Comment by dslomov** [comment]
> Since reading files pointed in manifest already breaks the concept of sandboxing,

No, it does not. In the same way, under Linux inside sandbox the application can use `readlink` to discover where symlink points - that does not "break the concept of sandboxing".

>  it won't make the things worse, if `$location` would point to absolute file path.

No it would. The result of `$location` is a part of a command line generated during analysis. That command line should be "relocatable", so no absolute paths.

However one possible way to allow automatic translation might be within the API of (just added) [Args object](https://docs.bazel.build/versions/master/skylark/lib/Args.html)

**Comment by eustas** [comment]
It seems that Args object should fit my requirements. Thanks.

**Comment by eustas** [comment]
How about optional copying of data deps when symlinking is not available (windows)?

It seems that there is no way to hack this around using just Skylark. The only way to alter build graph using the information form the outer world is exec_result, but it is available only for repository rules...

Other solution could be creating resource file with environment info, but it touches project sources too much (almost the same way as reading manifest) =(

**Comment by eustas** [comment]
Another tiny problem with runfiles resolving is that "workspace" path part should be either guessed or ignored. Two lines of code, but also a potential bug, as there could be name collisions.

**Comment by eustas** [comment]
My current workaround:
```
import fnmatch
import os
import os.path
from shutil import copyfile

matches = []
# replace with your project path
for root, dirnames, filenames in os.walk('bazel-bin\\java\\org\\brotli'):
  for filename in fnmatch.filter(filenames, '*.runfiles_manifest'):
    matches.append(os.path.join(root, filename))

for match in matches:
  runfiles = match[:-len('_manifest')]
  with open(match) as manifest:
    for entry in manifest:
      entry = entry.strip()
      if not entry.startswith("org_brotli"): # workspace id
        continue
      if entry.startswith('org_brotli/external'): #workspace id
        continue
      (alias, space, link) = entry.partition(' ')
      if alias.endswith('.jar') or alias.endswith('.exe'):
        continue
      link = link.replace('/', '\\')
      alias = alias.replace('/', '\\')
      dst = os.path.join(runfiles, alias)
      if not os.path.exists(dst):
        print(link + ' -> ' + dst)
        parent = os.path.dirname(dst)
        if not os.path.exists(parent):
          os.makedirs(parent)
        copyfile(link, dst)
```
Just run it between build and test.

**Comment by laszlocsomor** [comment]
I'm closing this issue, because Bazel is working fine.
`$(location)` returns the runfiles path of the target. You have to pass that to the runfiles library's `rlocation` function. Here's more info: https://github.com/bazelbuild/bazel/blob/e5735fd27d7ab72ef1793a10977316b4bdf52020/tools/python/runfiles/runfiles.py#L16-L59
