### ISSUE TITLE
Support WORKSPACE.bazel as alias for WORKSPACE

### ISSUE THREAD

**Issue by davidstanke** [bazelbuild/bazel#3885]
We support naming the BUILD file "BUILD.bazel"... for consistency, let's add support for WORKSPACE.bazel, too.

**Comment by katre** [comment]
It'll be a decent amount of work, there are a lot of bare references to "WORKSPACE" that will need to expand to accept WORKSPACE or WORKSPACE.bazel.

Also, any code that generates an internal WORKSPACE file should update to create WORKSPACE.bazel.

**Comment by damienmg** [comment]
I'd rather not as @katre said, it is a fair amount of work. We can have WORKSPACE.bazel be parsed easily but since we use WORKSPACE to get the root of the workspace directory everywhere, I'd rather just not do it before 1.0

**Comment by cgrushko** [comment]
`BUILD.bazel` became supported because of Windows not distinguishing between `BUILD` and `build`, which was often the name of a directory.
`WORKSPACE` doesn't probably have this problem?

**Comment by damienmg** [comment]
That was because of macOS actually but yes we do not have a collision issue
on WORKSPACE.

**Comment by cgrushko** [comment]
FWIW, supporting WORKSPACE.bazel makes it slightly easier to export code to open-source.

**Comment by jin** [comment]
+1, one less Copybara step.

**Comment by mikest** [comment]
+1, Also useful to disambiguate the mime type in code editors for Syntax highlighting.

**Comment by alexeagle** [comment]
Raising to P2 per discussion with @dslomov and @meteorcloudy - this will also make Bazel more palatable in Angular CLI since users won't wonder "What is this strange WORKSPACE file that's ignored by git". And the `.gitignore` can just be `*.bazel`
