### ISSUE TITLE
Windows,Android: Bazel should work with Android Studio on Windows

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3888]
Now that Bazel on Windows can build `android_*` rules, let's make it also work with Android Studio on Windows.

**Comment by laszlocsomor** [comment]
I'll definitely not get to this bug this year. Dropping to P3 and waiting @ahumesky 's input -- some other team may take ownership of this bug.

**Comment by jin** [comment]
Bazel works with Android Studio on Windows now. Tested with Bazel 0.21.0 and the Android tutorial app.

![windows-as](https://user-images.githubusercontent.com/347918/50366041-61034f80-0545-11e9-9026-83dd6680019a.PNG)

The tiny blip of bad news is that mobile-install is stuttering on its use of singlejar.exe. I've filed an issue for that here: https://github.com/bazelbuild/bazel/issues/6990

Thanks all for working on this!
