### ISSUE TITLE
Building @repo//:all or @repo//:... don't work

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#389]
Working on #352, I noticed that @foo//:all doesn't work (individual targets do).  I was attempting to fix this in TargetPattern, but the change just kept getting bigger so I figured I'd file a bug and get back to it later.  Basically:

* TargetPatternResolver should probably take PackageIdentifiers instead of Strings
* So PackageIdentifier should be moved to cmdline (and its dependencies on ExternalPackage and Label.SyntaxException severed). 
* All implementations of TargetPatternResolver should be modified to expect PIs.

**Comment by lberki** [comment]
This was fixed in c7106d4f6c0f550ad401ef8d8b3df2a5ec7eeea0 .
