### ISSUE TITLE
[skylark] add repository_ctx.tar

### ISSUE THREAD

**Issue by MarkusTeufelberger** [bazelbuild/bazel#3890]
### Description of the problem / feature request / question:

Repository_ctx:
https://docs.bazel.build/versions/master/skylark/lib/repository_ctx.html

I'd like to create a tarball of one or several files in a repository_ctx context when writing a custom function in skylark. Probably using similar syntax to the native pkg_tar rule (https://docs.bazel.build/versions/master/be/pkg.html#pkg_tar). Currently it would be possible to run an `repository_ctx.execute` function with `tar` in it somehow, but then it would rely on tar being available on the host, might have issues with reproducibility and so on.

### Environment info
* Operating System:
Any

* Bazel version (output of `bazel info release`):
0.6.1

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

Not really, https://github.com/bazelbuild/bazel/issues/893 seems to be the meta-issue that introduced repository_ctx and its features.

**Comment by mattmoor** [comment]
@damienmg owns `pkg_tar`

**Comment by damienmg** [comment]
we have a triaging policy, no need to assign :)

pkg_tar is not native, it is a skylark rule.

I wonder about the use case of doing tar in a repository rule?

**Comment by MarkusTeufelberger** [comment]
My current use case is creating the tar file that contains the `os-release` file here: https://github.com/GoogleCloudPlatform/distroless/blob/master/package_manager/util.py#L32

The docker rules that should consume this usually also need some metadata next to file contents (e.g. permissions) and thus only allow tar files as input. I can create the deb files at fetch time (by just downloading them), but the os-release file is not really available somewhere online and might also need some custom modifications (distroless for example puts their own issue tracker in there and I guess that's also the main reason they create/add this file in the first place)

**Comment by aiuto** [comment]
Related: https://github.com/bazelbuild/bazel/issues/11183.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
