### ISSUE TITLE
Confusing error message when a custom repository_rule fails

### ISSUE THREAD

**Issue by yilei** [bazelbuild/bazel#3892]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

When a custom repository_rule fails, bazel displays something like:

`ERROR: /path/to/BUILD:1:1: no such package '@my_custom_repository//':`

The `no such package` part is very confusing, because there *is* such package, just it *fails*.

Something like `error loading package` will be much more clear?

I spent an afternoon trying to figure out why my custom repository rule implementation function isn't executed because I thought `no such package` means it cannot find the package that is supposed to be provided by the custom repository rule. Then I finally realized that the function is indeed executed, it just fails.

### If possible, provide a minimal example to reproduce the problem:

./WORKSPACE:

```
load("//:custom_repository.bzl", "custom_repository")

custom_repository(name="my_custom_repository")
```

./custom_repository.bzl:

```
def _custom_repository_impl(repository_ctx):
  fail("...")

custom_repository = repository_rule(
    implementation = _custom_repository_impl,
)
```

./BUILD:

```
cc_library(
    name = "shim",
    deps = ["@my_custom_repository//:lib"],
)
```

Run `bazel build :shim`, it produces something like:

`ERROR: /path/to/BUILD:1:1: no such package '@my_custom_repository//': ... and referenced by '//:shim'.`

### Environment info
* Operating System:
macOS 10.12.6

* Bazel version (output of `bazel info release`):
release 0.6.1-homebrew

**Comment by buchgr** [comment]
@laurentlb please take a look:)

**Comment by damienmg** [comment]
I am pretty sure we already have that bug somewhere but I would need to dig.

**Comment by aehlig** [comment]
> The `no such package` part is very confusing, because there _is_ such package, just it _fails_.

Technically, there is no package. We only have a _definition_ or a _repository_ which, however, failed to produce a repository with the needed package.

Anyway, with current `bazel` at HEAD, the message reads as follows.

```
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
(15:38:17) INFO: Invocation ID: 53efbb2c-4af9-48ac-a4e0-a200518f2264
(15:38:17) INFO: Current date is 2019-05-02
(15:38:19) INFO: Call stack for the definition of repository 'my_custom_repository' which is a custom_repository (rule definition at /tmp/work2/custom_repository.bzl:4:21):
 - /tmp/work2/WORKSPACE:3:1
(15:38:19) ERROR: An error occurred during the fetch of repository 'my_custom_repository':
   ...
(15:38:19) ERROR: /tmp/work2/BUILD:1:1: no such package '@my_custom_repository//': ... and referenced by '//:shim'
(15:38:19) ERROR: Analysis of target '//:shim' failed; build aborted: no such package '@my_custom_repository//': ...
(15:38:19) INFO: Elapsed time: 7.234s
(15:38:19) INFO: 0 processes.
(15:38:19) FAILED: Build did NOT complete successfully (9 packages loaded, 28 targets configured)
```

The first error message states that an error occurred during the fetch of the repository, which should be enough information to find out what is going on.
