### ISSUE TITLE
Proxy in gitconfig NOT work in bazel

### ISSUE THREAD

**Issue by gwtony** [bazelbuild/bazel#3893]
There is socks5 proxy config in global .gitconfig
[https]
	proxy = socks5://10.x.x.x:1080
	
It do works with git clone command.
But when i build with bazel, it seems ignore proxy in gitconfig and requests to destination directly.
Is this a bug? If not could anyone tell me how to use git socks5 proxy in bazel.
Thank you

**Comment by buchgr** [comment]
Do you mean it doesn't work for `git_repository`? I don't think we support this @damienmg?

**Comment by katre** [comment]
This should be supported by the Skylark-based git_repository, but not by the native version.

Please make sure you are using the Skylark version by adding this to your WORKSPACE before git_repository:
```
load('@bazel_tools//tools/build_defs/repo:git.bzl', 'git_repository')
```

**Comment by gwtony** [comment]
Thank you, It might help me, let me try it later

**Comment by katre** [comment]
I am closing this issue as there have been no further updates.
