### ISSUE TITLE
Publish Skylark tools: Buildifier, Buildozer, Skylint

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/bazel#3895]
For Buildifier, I think we should distribute it with Bazel itself, similarly to how Go includes `go fmt`. The more teams use Bazel, and the more teams generate BUILD files, the more important it gets.

@damienmg proposes we have multiple packages that users choose from:

1. `bazel` or `bazel-core` - includes Bazel only, for automated use-cases like CI.
2. `bazel-dev` - includes everything a Bazel developer needs, such as Skylark tools.
3. Possible: Bazel for Java, which includes https://github.com/johnynek/bazel-deps for Maven jar management.

We can also bundle the tools into the command-line installers (e.g., in the list in https://github.com/bazelbuild/bazel/releases/tag/0.6.1)

CC @laurentlb @dslomov @davidstanke

**Comment by damienmg** [comment]
This is blocked by bazel/continuous-integration#137

**Comment by cgrushko** [comment]
@damienmg can you linkify the blocking issue? 
did you meant https://github.com/bazelbuild/continuous-integration/issues/137? I don't see how it's related, it's talking about Jenkins.

**Comment by dslomov** [comment]
https://github.com/bazelbuild/buildtools exists; closing
