### ISSUE TITLE
[I think that] repository_ctx.path(Label) should be able to resolve directories too

### ISSUE THREAD

**Issue by Reflexe** [bazelbuild/bazel#3901]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
1. The `repository_ctx.path` function throws error when it gets a directory `Label`. However, it has no problem with other `Label`-s.

    The source of the problem is in [this](https://github.com/bazelbuild/bazel/blob/0204bccf95dfaa01d15c21ffe9a64d04c5a6bf61/src/main/java/com/google/devtools/build/lib/bazel/repository/skylark/SkylarkRepositoryContext.java#L734) condition that makes sure `path` is a regular file.

    To bypass this restriction I ended up giving it a `BUILD` file inside of the required directory and then calling `path.dirname` to resolve the requested `path` (ugly hack).

     If it was intentional, I would be happy to learn way (except if the reason is to restrict the overpowered `repository_rule`).

2. The problem also occur when I tried to give a `repository_rule` an `attr.Label` with a directory.

### If possible, provide a minimal example to reproduce the problem:
```python
def _impl(repository_ctx):
     # Problem #1
    repository_ctx.path(Label("//:directory"))

repo_rule = repository_rule(_impl, 
    attrs = {  
        # Problem #2
        'label': attr.label(default=Label("//:directory")) ,
    },
)
```

### Environment info
* Operating System: Linux, ArchLinux.

* Bazel version (output of `bazel info release`): 0.6.1

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`): The archlinux official package.

###  Have you found anything relevant by searching the web?
Unfortunately, not.

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by buchgr** [comment]
@laurentlb can you take a look please?

**Comment by johnmarkwayve** [comment]
I realise this is very late, but I thought I'd put this here for anybody else who comes across it

I'm using this as a workaround. I've not tested it thoroughly, but it works for my usecases:

```
def directory_path(repository_ctx, label):
    """Return the absolute path to a directory referred to by an absolute label"""
    label = str(label)

    # Get the prefix (before the "//", if any)
    split = label.split("/", 1)
    prefix = split[0]

    # Get the path (after the "//")
    split = split[1].split(":", 1)
    dir_path = split[0]
    dir_name = split[1]
    if dir_path == "/":
        path = "/" + dir_name
    else:
        path = dir_path + "/" + dir_name

    return repository_ctx.path(
        str(repository_ctx.path(Label(prefix + "//:WORKSPACE"))).rsplit("/", 1)[0] +
        path,
    )
```

**Comment by chrisdunelm** [comment]
Any progress on this issue? It's been open for some time, and is difficult to work around.
Thanks.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
