### ISSUE TITLE
`attr.string_list_dict` doesn't resolve `select()` calls to values before type checking.

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel#3902]
Given a rule with an attribute defined by `attr.string_list_dict()`, I'd expect the following two stanzas to be equivalent:

```python
foo(my_attr = {"hello": ["world"]})

foo(
  my_attr = {"hello": select({
    "//conditions:default": ["world"],
  })},
)
```

However, Bazel rejects the second with a type error:

```
expected value of type 'list(string)' for dict value element, but got select({"//conditions:default": []}) (select)
```

**Comment by buchgr** [comment]
@laurentlb can you take a look please?

**Comment by gregestren** [comment]
Hi,

Unfortunately `select` doesn't support this kind of composition.

At core, `select` is designed to let you custom-choose the value an attribute takes. This means the `select`'s type has to match the attribute's type: in this case a dictionary of string lists. 

In your example, the `select` is bound to a string list, which is not the same type. Hence the error.

While your request makes sense as a user, it requires decomposing Bazel's type system more deeply than that system supports. So we'd basically have to refactor the type system to make this work. 

We could theoretically add ad hoc support for dictionary values to make this work (similar to how `+` works), or apply a filter that propagates `select`s to the top-level, e.g. auto-translates your example to:

```python
foo(
  my_attr = select({
    "//conditions:default": {"hello": ["world"]}
  }),
)
```
In this modified example, the `select` is now bound to a string list dict, so it now matches `my_attr`'s type.

So these are potential paths forward but I suspect it'd be messy.

**Comment by gregestren** [comment]
Most importantly, do you have workarounds with the status quo?

**Comment by jmillikin-stripe** [comment]
The workaround is to copy-paste the non-selected part of the dict into multiple select cases. It's not pretty, but is tolerable at our config sizes.

Given that the `attr` module has a fixed set of allowed container types, is it practical to special-case `select()` when used as a key or value of those containers? For example, `string_list_dict` attrs must be of type `Dict<String, List String>>` so there's only so many ways a select could get in there.

**Comment by gregestren** [comment]
I think the challenge is that the part of the type system in the `List String` subtype would have to be aware of selects and know how to "pass them up" to the final attribute assignment. So code paths crossing multiple classes would have to synchronize more tightly.

Another concern is nesting selects across multiple types, i.e.:

```python
foo(
  my_attr = select({
    "//conditions:default": {
      "hello": select({
        "//conditions:default": ["world"]}}
  }),
)
```
So resolving this attribute would require evaluating two selects over different types. This would effectively defer type resolution to a far later phase in Blaze's build process - a phase that's not equipped for that kind of thing now.  But I'm not sure how strong the call is for mixing selects this way, so maybe we can ignore this concern.

**Comment by kastiglione** [comment]
We ran into this, wanted to have a `string_dict` attr whose values could be configurable. For example:

```
my_attr = {
    "key": "A",
    "configurable_key": select({
        ":config": "B",
        "//conditions:default": "C",
    }),
}
```

I ended up on a solution that does provide this interface, but complicates the implementation. The approach is to add a macro layer above the rule (which generally wouldn't be used directly). The macro destructures the dictionary into static and configurable pieces. The configurable part is restructured and wrapped in a `select()`. 

The restructuring is the messy part. It converts:

```
"A": {
    ":X", "AX",
    ":Y", "AY,
},
"B": {
    ":X": "BX",
    ":Y": "BY",
}
``` 

into

```
keys = ["A", "B"]
values = select({
    ":X": ["AX, "BX"],
    ":Y": ["AY", "BY"],
})
```

The macro then calls the rule whose interface has an attr for both the static half and an attr for the keys and values of the configurable parts. The rules's implementation can then recompose the dictionary from the resolved values.

**Comment by gregestren** [comment]
I think the most practical solution remains https://github.com/bazelbuild/bazel-skylib/blob/master/lib/selects.bzl, since it doesn't deeply mess with Starlark's type system.

Also see https://docs.bazel.build/versions/master/configurable-attributes.html#or-chaining and the following section.

Going forward, I suggest criteria for opening new bugs includes demonstrating how the skylib approach is insufficient and really evaluating what kind of organization with existing mechanisms is possible before considering enhancements. We really want to lean away from direct support for syntax like described here, even though I get the intuition from the user side (enough that I even prototyped it!).
