### ISSUE TITLE
[Document Issue] What does "//:target-name" stand for?

### ISSUE THREAD

**Issue by tianzhi0549** [bazelbuild/bazel#3905]
### Description of the problem / feature request / question:
Hi, in the official document, it is said //:target-name means `referencing targets within the same package`. You could find it at https://docs.bazel.build/versions/master/tutorial/cpp.html#use-labels-to-reference-targets. However, according to my tries, it should refer to the targets in the root directory of a WORKSPACE. Therefore, I think it's wrong in the official document. Additionally, the another part of the official document, it is said it refers to the targets in the root directory. https://docs.bazel.build/versions/master/build-ref.html#package-names-package-name.

Hope you can fix it if I'm right:-). Thank you.

### Environment info
* Operating System:
Ubuntu 14.04

* Bazel version (output of `bazel info release`):
bazel release 0.6.1

**Comment by jin** [comment]
Fixed in https://github.com/bazelbuild/bazel/commit/d22331df583738029a43b310e825d1da9985d743
