### ISSUE TITLE
Build fails on circular reference between two repos (target graph is DAG)

### ISSUE THREAD

**Issue by natansil** [bazelbuild/bazel#3907]
### Description of the problem / feature request / question:

We are examining using bazel in an environment of many-repos.
The scenario below of circular reference between two repos (target graph is DAG) fails to build.

### A minimal example to reproduce the problem:
We have two repos, [A](https://github.com/natansil/bazel-repo-a) and [B](https://github.com/natansil/bazel-repo-b)

repo `A` has two [defined](https://github.com/natansil/bazel-repo-a/blob/master/BUILD) targets `a1` and `a2`
repo `B` [has](https://github.com/natansil/bazel-repo-b/blob/master/BUILD#L6) a target called `b1`

The targets graph is `a1->b2->a2` (no circles here)

Build of `A`'s targets fails:
```
bazel build //...
ERROR: /private/var/tmp/_bazel_natans/4424a3bd55dd7410870d8adef5c5f370/external/repo_b/BUILD:5:1: no such package '@repo_a//': The repository could not be resolved and referenced by '@repo_b//:b1'.
ERROR: Analysis of target '//:a1' failed; build aborted.
INFO: Elapsed time: 0.106s
```

### Environment info
* Operating System:
macOS Sierra 10.12.6

* Bazel version (output of `bazel info release`):
0.6.1-homebrew

**Comment by buchgr** [comment]
I believe dependency resolution might work on the package level? @damienmg ?

**Comment by jmillikin-stripe** [comment]
You'll need to define `@repo_a` by setting a workspace name.

**Comment by damienmg** [comment]
Hi as @jmillikin-stripe said, you need to set the workspace name so Bazel know which name the main workspace has.

**Comment by natansil** [comment]
did the trick!
Thanks @jmillikin-stripe, @damienmg
