### ISSUE TITLE
Repository redefinition using skylark rules are ok but should error out.

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3908]
Update by @laszlocsomor: Damien no longer works on Bazel, but this bug is still not fixed with Bazel 0.21.

---

With latest bazel (0.6.1):

Recreation of the repo:
```bash
$ cat >test.bzl <<'EOF'
def _impl(ctx):
  print("Bleh")

my_repo = repository_rule(_impl)
EOF
$ cat >WORKSPACE <<'EOF'
local_repository(name = 'local_repo', path = 'local_repo')
load('//:test.bzl', 'my_repo')
local_repository(name = 'local_repo', path = 'local_repo')
EOF
$ touch BUILD
$ mkdir local_repo
$ touch local_repo/WORKSPACE
$ echo "filegroup(name = 'test', srcs = [], visibility = ['//visibility:public'])" >local_repo/BUILD
```

This creates an error as expected:
```bash
$ bazel clean --expunge
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
$ bazel fetch //...
..............
ERROR: /private/tmp/bug/WORKSPACE:3:1: Cannot redefine repository after any load statement in the WORKSPACE file (for repository 'local_repo')
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package 'external': Package 'external' contains errors
ERROR: error loading package 'external': Package 'external' contains errors
Building: no action running
```

Now let's use a skylark repository:

```bash
$ cat >WORKSPACE <<'EOF'
local_repository(name = 'local_repo', path = 'local_repo')
load('//:test.bzl', 'my_repo')
my_repo(name = 'local_repo')
EOF
```

Bazel accept it no issue:
```bash
$ bazel clean --expunge
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
$ bazel fetch //...
...
$ bazel query //external:local_repo --output=label_kind
my_repo rule //external:local_repo
```

**Comment by damienmg** [comment]
Note that I found the bug while looking at external repo code:

https://github.com/bazelbuild/bazel/blob/b4a2034b77703b764304acb352325b06912ec279/src/main/java/com/google/devtools/build/lib/packages/WorkspaceFactory.java#L455 is throwing the error but Skylark repositories call directly [createAndAddRepositoryRule](https://github.com/bazelbuild/bazel/blob/b4a2034b77703b764304acb352325b06912ec279/src/main/java/com/google/devtools/build/lib/bazel/repository/skylark/SkylarkRepositoryModule.java#L179) which does not have that check.

**Comment by laszlocsomor** [comment]
The fix (https://github.com/bazelbuild/bazel/commit/337f19cc54e77c45daa1d5f61bf0a8d3daf8268f) was apparently rolled back (https://github.com/bazelbuild/bazel/commit/766ba8adc4487f17ebfc081aeba6f34b18b53d6c) so I've reopened the bug.

**Comment by laszlocsomor** [comment]
I confirmed that the bug is still present in Bazel 0.21.0 -- it was never fixed.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
