### ISSUE TITLE
Build error with NDK-r10e

### ISSUE THREAD

**Issue by zagannath** [bazelbuild/bazel#391]
I believe Path specified in CROSSTOOL is misleading in android-ndk-r10e-darwin-x86_64 thus causing build errors, I didn't find any  "linux-x86_64" folder inside prebuilt but there is "darwin-x86_64" ,am I doing something wrong here ?

 target_cpu: "armeabi-v7a"
  target_system_name: "arm-linux-androideabi-4.8"
  toolchain_identifier: "arm-linux-androideabi-4.8"

  tool_path { name: "ar"
    path: "toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar"
  }
  tool_path { name: "compat-ld"
    path: "toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ld"
  }
  tool_path { name: "cpp"
    path: "toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-cpp"
  }
  tool_path { name: "dwp"
    path: "toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-dwp"
  }

Here is the full build fail
-----------------
Vinays-MacBook-Pro:cpp Symbioun$ bazel build --dynamic_mode=off --package_path=%workspace%:$HOME/tmp/android:$HOME/bazel-src --crosstool_top=//android-ndk:toolchain --host_crosstool_top=//tools/cpp:toolchain --cpu=armeabi-v7a --verbose_failures --custom_malloc=//android-ndk:malloc :hello-world
INFO: Found 1 target...
INFO: From Compiling examples/cpp/hello-lib.cc:
execvpe android-ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc failed --- No such file or directory

ERROR: /Users/Pankajbafna/Downloads/bazel-master/examples/cpp/BUILD:3:1: C++ compilation of rule '//examples/cpp:hello-lib' failed: arm-linux-androideabi-gcc failed: error executing command
  (cd /private/var/tmp/_bazel_Symbioun/8de0ed97260158704607eb66baa1d395/bazel-master && \
  exec env - \
    INTERCEPT_LOCALLY_EXECUTABLE=1 \
    PATH=/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Users/Pankajbafna/Library/Android/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/opt/local/bin:/Users/Pankajbafna/Library/Android/ndk/android-ndk-r10e \
    TMPDIR=/var/folders/zl/n90v2ywd1ws2k_sw1tg0hkth0000gp/T/ \
  android-ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -fPIE -DANDROID -g '-std=c++0x' '-std=gnu++11' -iquote . -iquote bazel-out/arm-linux-androideabi-4.8-fastbuild/genfiles -isystem tools/cpp/gcc3 '--sysroot=android-ndk/platforms/android-19/arch-arm' -isystem%sysroot%/usr/include -isystemandroid-ndk/sources/cxx-stl/gnu-libstdc++/4.8/include -isystemandroid-ndk/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi/include -isystem android-ndk/sources/cxx-stl/stlport/stlport -isystem android-ndk/sources/cxx-stl/gabi++/include -fno-canonical-system-headers -no-canonical-prefixes '-frandom-seed=bazel-out/arm-linux-androideabi-4.8-fastbuild/bin/examples/cpp/_objs/hello-lib/examples/cpp/hello-lib.pic.o' -MD -MF bazel-out/arm-linux-androideabi-4.8-fastbuild/bin/examples/cpp/_objs/hello-lib/examples/cpp/hello-lib.pic.d -fPIC -c examples/cpp/hello-lib.cc -o bazel-out/arm-linux-androideabi-4.8-fastbuild/bin/examples/cpp/_objs/hello-lib/examples/cpp/hello-lib.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: arm-linux-androideabi-gcc failed: error executing command
  (cd /private/var/tmp/_bazel_Symbioun/8de0ed97260158704607eb66baa1d395/bazel-master && \
  exec env - \
    INTERCEPT_LOCALLY_EXECUTABLE=1 \
    PATH=/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Users/Pankajbafna/Library/Android/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/opt/local/bin:/Users/Pankajbafna/Library/Android/ndk/android-ndk-r10e \
    TMPDIR=/var/folders/zl/n90v2ywd1ws2k_sw1tg0hkth0000gp/T/ \
  android-ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -fPIE -DANDROID -g '-std=c++0x' '-std=gnu++11' -iquote . -iquote bazel-out/arm-linux-androideabi-4.8-fastbuild/genfiles -isystem tools/cpp/gcc3 '--sysroot=android-ndk/platforms/android-19/arch-arm' -isystem%sysroot%/usr/include -isystemandroid-ndk/sources/cxx-stl/gnu-libstdc++/4.8/include -isystemandroid-ndk/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi/include -isystem android-ndk/sources/cxx-stl/stlport/stlport -isystem android-ndk/sources/cxx-stl/gabi++/include -fno-canonical-system-headers -no-canonical-prefixes '-frandom-seed=bazel-out/arm-linux-androideabi-4.8-fastbuild/bin/examples/cpp/_objs/hello-lib/examples/cpp/hello-lib.pic.o' -MD -MF bazel-out/arm-linux-androideabi-4.8-fastbuild/bin/examples/cpp/_objs/hello-lib/examples/cpp/hello-lib.pic.d -fPIC -c examples/cpp/hello-lib.cc -o bazel-out/arm-linux-androideabi-4.8-fastbuild/bin/examples/cpp/_objs/hello-lib/examples/cpp/hello-lib.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //examples/cpp:hello-world failed to build
INFO: Elapsed time: 7.246s, Critical Path: 0.23s
---------------------

**Comment by ahumesky** [comment]
Have you recently updated your bazel repo? I recently updated our NDK handling which may fix the problem that you're seeing.

**Comment by lberki** [comment]
Assigning to Alex -- it's the end of day here and he is the one who put together these CROSSTOOL files.

**Comment by zagannath** [comment]
@ahumesky did you had any chance to look into this issue ?

**Comment by damienmg** [comment]
Are you running on Linux? If there's a -darwin folder it means you have downloaded a Darwin NDK on Linux.

**Comment by damienmg** [comment]
Did you tried with yesterday update? We fix a lot of stuff around those repository.

**Comment by ahumesky** [comment]
The android_ndk_repository rule should work for both linux and darwin. Can you try from head?

**Comment by damienmg** [comment]
Closing as obsolete
