### ISSUE TITLE
Cannot see debug print statements in rules when executing `bazel run @{external}:{target}`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [bazelbuild/bazel#3920]
### Description of the problem:

I am attempting to debug some install rules in an external, and ran into an issue where I was not seeing `print(...)` statements.

I was able to see the `print(...)` statements when running a rule that is not prefixed with `@`.

**Workaround**: See temporary debug statements using `fail(...)`.

### If possible, provide a minimal example to reproduce the problem:

I encountered it in `drake` ([source tree](https://github.com/EricCousineau-TRI/drake/tree/9ae3fe6) of my fork), when attempting to debug installation of an external library while following a workaround of #492.

Steps:
* Wanted to debug an executable rule implementation: `bazel run @fmt//:install -- ~+/build_install`
* Added debug statements in `//tools:install.bzl` for things like `dir(target.cc)` to inspect available fields
* Executed command, got a syntax error, but no debug statement.
* Fixed syntax error, but still no output.
* Add `fail(...)` statement, and could see the output.

I could see output previously when running something like `bazel run //:install -- ~+/build_install`

### Environment info
* Operating System: Ubuntu 16.04.2

* Bazel version (output of `bazel info release`): `release 0.6.1`

###  Have you found anything relevant by searching the web?
Nope, searching in these issues and on the web didn't turn anything up.

**Comment by jwnimmer-tri** [comment]
I think this is because Drake is turning them off: https://github.com/RobotLocomotion/drake/blob/f825eb3566b998890e37a539233abeb7afe031d8/tools/bazel.rc#L12-L13.

**Comment by EricCousineau-TRI** [comment]
Ah, that makes sense! Thank you for pointing that out!
