### ISSUE TITLE
Bazel lets me redefine a workspace rule, and then ignores the second definition

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/bazel#3922]
From CcProtoLibraryTest, I wrote the following WORKSPACE:

```
local_repository(name = 'com_google_protobuf', path = 'protobuf/')
local_repository(name = 'bazel_tools', path = '/bazel_tools_workspace')
local_repository(name = 'local_config_xcode', path = '/local_config_xcode')
local_repository(name = 'com_google_protobuf', path = '/protobuf')
bind(name = 'android/sdk', actual='@bazel_tools//tools/android:sdk')
bind(name = 'tools/python', actual='//tools/python')
```

Notice the two conflicting definitions of `com_google_protobuf` - one takes `/protobuf/`, the other just `protobuf/`. 
Incredulously, I neither got an error, nor the second definition took precedence over the first.

**Comment by petroseskinder** [comment]
This is still an issue for us. Is there plans of fixing this?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
