### ISSUE TITLE
Android NDK libc++ include paths incorrect

### ISSUE THREAD

**Issue by spinorx** [bazelbuild/bazel#3923]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I am using bazel with ndk android-ndk-r14b.  The libc++ includes are at cxx-stl/llvm-libc++/include directly:
```
[param@param-mac:~/android-ndk-r14b/sources/cxx-stl]$ ls
gabi++/         gnu-libstdc++/  llvm-libc++/    llvm-libc++abi/ stlport/        system/
[param@param-mac:~/android-ndk-r14b/sources/cxx-stl]$ ls llvm-libc++
Android.bp               CREDITS.TXT              README.version           docs/                    lit.site.cfg             src/                     www/
Android.mk               LICENSE.TXT              TODO.TXT                 include/                 ndk-test.sh*             test/
Application.mk           MODULE_LICENSE_BSD_LIKE  buildcmds/               lib/                     repo.prop                test.mk
CMakeLists.txt           NOTICE                   cmake/                   libs/                    run-tests.py             utils/
[param@param-mac:~/android-ndk-r14b/sources/cxx-stl]$ ls llvm-libc++abi/
Android.bp               CMakeLists.txt           MODULE_LICENSE_BSD_LIKE  cmake/                   repo.prop                www/
Android.mk               CREDITS.TXT              NOTICE                   include/                 src/
Application.mk           LICENSE.TXT              README.version           lib/                     test/
[param@param-mac:~/android-ndk-r14b/sources/cxx-stl]$
```

However bazel adds extra libcxx (from external/android_ndk/BUILD.bazel):
```
  unfiltered_cxx_flag: "-isystem"
  unfiltered_cxx_flag: "external/android_ndk/ndk/sources/cxx-stl/llvm-libc++/libcxx/include"
  unfiltered_cxx_flag: "-isystem"
  unfiltered_cxx_flag: "external/android_ndk/ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/include"
```

### Environment info
* Operating System:
Mac OSX

* Bazel version (output of `bazel info release`):
```
[param@param-mac:~/vircorX]$ bazel info release
release 0.6.1-homebrew
```

###  Have you found anything relevant by searching the web?

See also:  https://github.com/android-ndk/ndk/issues/252

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by spinorx** [comment]
Dug a bit more.  There used to be libcxx in ndk 12 and got removed in 13.  13 was released like an year ago and I am surprised this has gone undetected for an year??

**Comment by spinorx** [comment]
@aj-michael who is doing most android changes.

**Comment by aj-michael** [comment]
@ahumesky , do you have time to look at this? I have an internal change (167013945) that I started to fix this a bit ago, but was never able to fix all the edge cases.

See also #3641

**Comment by spinorx** [comment]
I am using android-ndk-r14b .  Yup it is dup of the issue you pointed out.  Feel free to close this.

Workarounds:
Change the include to be under llvm-libc++/libcxx/ and llvm-libc++abi/libcxxabi/.

After changing the include paths in ndk to work around I hit another snag with linker not finding -lc++_static etc.

The work around for that was to add --linkopt=-Lexternal/android_ndk/ndk/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a manually.

The rest of issues I hit are captured in https://github.com/bazelbuild/bazel/issues/3924

**Comment by spinorx** [comment]
And thanks for being responsive!

**Comment by jin** [comment]
@spinorx Sorry for the long wait, but the fix is now in master. Feel free to try it out and let me know if it's working for you.

**Comment by steeve** [comment]
Hum, it seems `libc++_static.a`, `libandroid_support.a` are not part of the generated CROSSTOOL, which creates linking issues when the sandbox is enabled. Test on today's `master`.

cc @jin

**Comment by steeve** [comment]
But actually I do see them in the `deps` graph of the toolchain, which is weird. But when listing the files via `@bazel_tools//tools/cpp:current_cc_toolchain` or `//tools/defaults:crosstool` I don't see them listed.

I think basically all the files in `<NDKROOT>/sources/cxx-stl/llvm-libc++/libs/<ARCH>/`:
```
libandroid_support.a
libc++.a
libc++.so
libc++_shared.so
libc++_static.a
libc++abi.a
```

**Comment by jin** [comment]
Are you building the `cc_library` dep by itself, or through an `android_library` transition? Building the `cc_library` by itself defaults to using the host CROSSTOOL that doesn't include the NDK libraries.

**Comment by steeve** [comment]
@jin I'm running a custom link rule that calls the native `ld_executable` with its args. It seems the STATIC and DYNAMIC filegroups are not declared as outputs to the toolchain by itself. Should I declare that filegroup too?

**Comment by steeve** [comment]
My rules is declaring this as an implicit dependency:
```
        "_crosstool": attr.label(default = Label("//tools/defaults:crosstool")),
```

The uses it as input for a `ctx.actions.run` command.

**Comment by jin** [comment]
Can you please try 

        "_crosstool": attr.label(default = Label("//external:android/crosstool")),

instead? `//tools/defaults:crosstool` is not the NDK CROSSTOOL.

**Comment by steeve** [comment]
@jin i'm starting bazel with:
```
build:android_arm64 --crosstool_top=@androidndk//:toolchain-libcpp
build:android_arm64 --android_crosstool_top=@androidndk//:toolchain-libcpp
build:android_arm64 --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
build:android_arm64 --cpu=arm64-v8a
```

**Comment by jin** [comment]
@steeve do you mind creating a new issue with a minimal repro example, please? It'll help me to understand how you're writing the custom rule.

**Comment by steeve** [comment]
@jin there you go: https://github.com/steeve/bazel_libcpp_android_issue
Just do:
```
$ bazel build //...
```

**Comment by steeve** [comment]
If I add `//external:android/crosstool` as a `src`, then somehow I see `gnu-libstdc++` files too.

**Comment by steeve** [comment]
@jin did you get a chance to look into the repo ?

**Comment by jin** [comment]
I just got some time to look at the repo: a quick workaround is to include the relevant `filegroup` in `srcs`:

```
$ cat BUILD.bazel
genrule(
    name = "libcpp_static",
    srcs = [
        "//tools/defaults:crosstool",
        "@androidndk//:libcpp-x86_64-static-runtime-libraries",
    ],
    outs = [
        "files.txt",
    ],
    cmd = """\
find external/androidndk/ndk/sources/cxx-stl/llvm-libc++/libs/ > $(@)
    """,
)
```

```
$ cat bazel-genfiles/files.txt
external/androidndk/ndk/sources/cxx-stl/llvm-libc++/libs/
external/androidndk/ndk/sources/cxx-stl/llvm-libc++/libs/x86_64
external/androidndk/ndk/sources/cxx-stl/llvm-libc++/libs/x86_64/libc++_static.a
external/androidndk/ndk/sources/cxx-stl/llvm-libc++/libs/x86_64/libc++abi.a
external/androidndk/ndk/sources/cxx-stl/llvm-libc++/libs/x86_64/libandroid_support.a
external/androidndk/ndk/sources/cxx-stl/llvm-libc++/libs/x86_64/libc++.a
```

Next: figure out why the `libs` directory isn't part of the implicit outputs.

**Comment by steeve** [comment]
Indeed, the issue however is that the name platform dependent... But it can be worked around it via select maybe.

Thank you for looking into that.

**Comment by jin** [comment]
@steeve I found the root cause, filed #4864

**Comment by steeve** [comment]
Thank you that was fast
