### ISSUE TITLE
bazel crash

### ISSUE THREAD

**Issue by excavador** [bazelbuild/bazel#3928]
### Description of the problem / feature request / question:

Wrong rules can crash bazel
See https://github.com/bazelbuild/rules_go/issues/941

### If possible, provide a minimal example to reproduce the problem:

See https://github.com/bazelbuild/rules_go/issues/941

### Environment info
```
➜ bazel version
.................................................
Build label: 0.7.0-homebrew
Build target: bazel-out/darwin_x86_64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Oct 19 09:12:48 2017 (1508404368)
Build timestamp: 1508404368
Build timestamp as int: 1508404368
```

###  Have you found anything relevant by searching the web?
No

### Anything else, information or logs or outputs that would be helpful?
See https://github.com/bazelbuild/rules_go/issues/941

**Comment by katre** [comment]
The core issue here is that if a toolchain isn't registered, toolchain resolution's exception doesn't validate in SkyframeBuildView.assertSaneAnalysisError, and a crash happens instead of just reporting the error.

**Comment by katre** [comment]
@excavador Can you help me reproduce this by telling me exactly what git repo you have cloned, and what commands you are running?

**Comment by excavador** [comment]
Give me some time, I will prepare minimal repo for reproduce.
It also another bug there 
https://github.com/bazelbuild/rules_go/issues/943

**Comment by excavador** [comment]
Interesting. I can not reproduce problem in clean repo.

Trying to find dependency combination for reproduce the problem

**Comment by excavador** [comment]
I have the repo with the problem
https://github.com/excavador/bazel_vendor_bug

**Comment by katre** [comment]
Thanks! Looking now.

**Comment by excavador** [comment]
@katre please get second commit, I updated README.md

**Comment by katre** [comment]
Okay, I can only reproduce this on a Mac, which is pretty interesting to start with. Debugging now.

**Comment by excavador** [comment]
Keep me informed! :)

I little surprised, because I just tried switch our make-based build system to bazel (before this I two months time-to-time learn bazel & skylark).

Pretty interesting fact, the problem reproduced only on full vendor directory with current versions.
If try to create repo with latest dependencies version, particullary openzipkin, no problem.
So, this problem does not block me, but definitely we have some problems in bazel and rules_go, and this case and good point to improve their :)

**Comment by katre** [comment]
Looks like the problem is specifically with the case where a rule asks for more than one toolchain, and one of them is missing.

Occurs here:
https://github.com/bazelbuild/rules_go/blob/ad076c97335c03319280fa438c9f958e7c81597a/proto/def.bzl#L56

Note: I don't think the go rules are wrong, I think Bazel is wrong.

**Comment by katre** [comment]
And the reason it only expresses as an error on Macs is because of non-determinism in how Skyframe handles getValues() calls

**Comment by katre** [comment]
I have a fix, trying to write a test now.

**Comment by excavador** [comment]
Great! It would be in next bazel release, right?

**Comment by katre** [comment]
Yes, it should be in the November release.

**Comment by excavador** [comment]
Thank you!
Can't wait :)

**Comment by katre** [comment]
I'll have a change out for review shortly , once I've tested and cleaned up the code :)
I'll link it from here.

**Comment by katre** [comment]
https://bazel-review.googlesource.com/c/bazel/+/19310 is sent for review. I tested it with your repro git repository and I get the expected error.
