### ISSUE TITLE
No tests run when using --java_debug

### ISSUE THREAD

**Issue by ekuefler** [bazelbuild/bazel#393]
When I pass `--java_debug` on the command line when running a java test, Bazel waits for a connection from a debugger, but when I connect IntelliJ the test immediately passes and reports that zero tests were run.

I see from https://github.com/google/bazel/blob/4fa83ac8380330e6f1d88e77030c248bb501ab29/src/main/java/com/google/devtools/build/lib/rules/java/JavaOptions.java#L188 that `--java_debug` expands to several other command-line args. `--test_arg=--wrapper_script_flag=--debug` is the one that causes problems - if I manually pass all of the other args things are fine (though it obviously doesn't wait for the debugger), and if I add that flag it goes back to not running anything after the connection.

However, it does work fine if I run the generated test script under bazel-bin directly and pass the `--debug` flag. So there must be some problem in how flags get passed to the test script by Bazel.

Another workaround is to remove the `--java_debug` flag and modify the test's BUILD file to include `jvm_flags = ["-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"]` on the `java_test` target.

**Comment by damienmg** [comment]
It is another consequence of the same root cause: our java test runner isn't the one we use internally. Adding Philip (well assigning as there is no CC on github issue tracker) who did work on that some time ago to comment (how far are we to ship the actual version?).

**Comment by philwo** [comment]
Now that the sandboxing stuff is done, I will get back to these things and will have a look at the JUnit test runner tomorrow. I hope integrating it into Bazel and releasing it is a 1 - 2 day thing, as most preparations on the code side have already been done. :)

**Comment by Aragos** [comment]
I ran into this recently and did some investigation. As far as I can tell the script is passing the correct JVM arguments: https://github.com/bazelbuild/bazel/blob/15e9a506118b4067655e5e7f72ff852be5b797ca/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt#L166

But for some reason the JVM is suspended as a result but the port (usually 5005) not opened for listening. If you pass `--test_env DEFAULT_JVM_DEBUG_SUSPEND=n` to the test, the tests are started properly and a debugger can be successfully attached. However, this only works if the tests are quite complex - if they are short they are likely already complete (and the JVM shut down) by the time the debugger attempts to attach. And the port appears to close with the actual tests running, at least if I add a Thread.sleep(30000) to my test `lsof -i | grep 5005` doesn't list any open ports.

**Comment by Aragos** [comment]
https://bugs.openjdk.java.net/browse/JDK-8042704 is the only thing I've been able to find even remotely describing this issue and I've managed to replicate the issue with multiple JDK versions (`--host_javabase`) so I suspect this isn't the JVMs fault but rather something we do in the test runner. Not sure what that would be though since I'd have expected the JVM to suspend before ever interacting with our code.

**Comment by damienmg** [comment]
@Aragos: the current test runner is dumb. I am doing the last plumbing for shipping our own version and should be here in the following weeks. I hope this will fix that issue.

**Comment by ekuefler** [comment]
Another note for anyone who comes across this - it looks like you now also need to pass `--spawn_strategy=standalone` to bazel when you're trying to run a debugger against recent versions of Bazel. I'm guessing the sandbox started blocking access to the debugger port at some point.

**Comment by damienmg** [comment]
I haven't tested but with the new Junit runner it should work. That is with `--nolegacy_bazel_java_test`

**Comment by ekuefler** [comment]
Just tried this out. This works now:

```
bazel test //src/test/java/com/ekuefler:MyTest --nolegacy_bazel_java_test --java_debug --spawn_strategy=standalone
```

However, it doesn't work when I drop the `spawn_strategy=standalone` flag. Bazel blocks waiting for a connection on port 5005, but IntelliJ is unable to connect to that port. This would be consistent with the sandbox blocking access to the port. Does Bazel know to open up port 5005 when run with `--java_debug`?

**Comment by hermione521** [comment]
@ekuefler please add `tags = ["requires-network"],` to your test, then it should work in sandbox.

**Comment by ekuefler** [comment]
Adding the tag works, but having to modify the BUILD file removes much of the convenience of the flag. I guess I can also just pass the standalone flag when passing debug, but it would be nice if the flag just worked out of the box.
