### ISSUE TITLE
intermittent Bazel crash: bus error

### ISSUE THREAD

**Issue by ola-rozenfeld** [bazelbuild/bazel#3933]
This happened to us twice, once with 0.6 and once with 0.7rc1. The error message is:

____Building complete.
Target //:protoc up-to-date:
  bazel-bin/protoc
____Elapsed time: 665.904s, Critical Path: 535.13s
____Waiting for build event protocol upload: 0s
____Waiting for Build Event Protocol upload to finish.
____Build Event Protocol upload finished successfully.
Error: error running command: signal: bus error (core dumped)

This was encountered on a build of protoc with remote execution.
Note that the error message itself is from the Golang wrapper script we use in order to run Bazel -- there is no Bazel-originating message that suggests anything went wrong, so this looks like the bus error happened after the execution finished successfully.
At first, we thought that this was a signal of system overload (memory, for instance), but this time we don't see any obvious problems with the machine. Any ideas?

**Comment by dslomov** [comment]
@ulfjack @buchgr any suggestions?

**Comment by buchgr** [comment]
Do you have the JVM log from Bazel? HotSpot is known to surface any kind of error as a bus error.

**Comment by ola-rozenfeld** [comment]
Sorry, no, we wipe these directories after execution. I will try to get a log if this ever happens in a different environment. What's HotSpot?

**Comment by philwo** [comment]
> What's HotSpot?
The name of the "usual" JVM used :) See https://en.wikipedia.org/wiki/HotSpot

Have you seen this issue again?

**Comment by ola-rozenfeld** [comment]
No, this hasn't happened again since. If it ever does, I'll try to copy the JVM logs. Let's close for now. Thank you!
