### ISSUE TITLE
experimental_remote_spawn_cache: missing runfiles

### ISSUE THREAD

**Issue by nicolov** [bazelbuild/bazel#3934]
Sandboxed local workers with the remote caching is great, thanks.

Unfortunately, it seems that the runfiles tree is not created when the results are downloaded from the (REST) cache. The first build with a cold cache works as expected (the runfiles are there). I've tried both today's master and 0.7.0.

**Comment by nicolov** [comment]
It seems that https://github.com/bazelbuild/bazel/commit/ba8b0b3273ace313d35e9917c8116bab6386c6cc fixes this.

**Comment by buchgr** [comment]
So it seems like this is fixed then? Please re-open if still an issue.
