### ISSUE TITLE
apple_binary.app.dSYM.temp.zip was not created

### ISSUE THREAD

**Issue by thassss** [bazelbuild/bazel#3940]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

Hi I am exploring hazel to possibly use at my company.  I am unable to build simple Swift iOS app. I have an ios_application target that depends on a swift_library, which contains my AppDelegate and RootViewController. I tried to set this up similar to the tutorial, but haven't been able to get it working. It seems that it's breaking on zipping the dSYM.

### If possible, provide a minimal example to reproduce the problem:

My small workspace directory is attached.

this works: `bazel build //app:bztest`

this doesn't: `bazel build --apple_generate_dsym=true //app:bztest`

log:
```
INFO: Found 1 target...
ERROR: /bztest/app/BUILD:13:1: output 'app/bztest.apple_binary.app.dSYM.temp.zip' was not created.
ERROR: /bztest/app/BUILD:13:1: not all outputs were created or valid.
Target //app:bztest failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 5.175s, Critical Path: 3.07s
```

### Environment info
* Operating System: macOS 10.13
• Xcode: 9.0 

* Bazel version (output of `bazel info release`): release 0.7.0-homebrew

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss
[bztest.zip](https://github.com/bazelbuild/bazel/files/1403008/bztest.zip)
) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by dmishe** [comment]
@c-parsons this looks familiar, have you seen this error before?

**Comment by jbeder** [comment]
Is this similar to #3372?

(I'm running into this too.)

**Comment by mikelikespie** [comment]
Seeing this too (with master and 0.9.0)

**Comment by sergiocampama** [comment]
#4312 has more info on what's missing in the CROSSTOOL

**Comment by sergiocampama** [comment]
This should be fixed at head, probably will take a while to get rolled out to a release binary.

**Comment by DmytroLapshyn** [comment]
0.11 still seems to have it not fixed

**Comment by jmmv** [comment]
Considering fixed per the last updates and because a lot of things have changed in the Apple rules. Please let us know if this is still a problem or relevant.
