### ISSUE TITLE
remote caching/execution README is out of date for 0.7.0

### ISSUE THREAD

**Issue by nicolov** [bazelbuild/bazel#3945]
The [remote execution readme](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/remote/README.md) is out of date now that 0.7.0 has been released with the `RemoteSpawnCache`. The `remote` spawn strategy is not even available anymore.

**Comment by buchgr** [comment]
`--spawn_strategy=remote` is still available.
