### ISSUE TITLE
Handle grandparent poms

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#395]
https://github.com/google/bazel/commit/d34488544835edce8fa15abd07e00be472b959b9 made references to the parent pom work, but the resolver really needs to recurse in both directions (up the parent tree as well as down the submodules).

**Comment by petroseskinder** [comment]
@kchodorow is this still an issue? 

With the current implementation, the resolver recurses up the parent tree, so presumably, it will handle grandparent poms. Why would it also need to recurse down the submodules, and what are you referring to by submodules?

**Comment by kchodorow** [comment]
I don't think it recurses up the parent tree.  It just looks at the parent.

**Comment by jin** [comment]
Closing as generate_workspace is no longer being maintained in favor of https://github.com/bazelbuild/rules_jvm_external.
