### ISSUE TITLE
SkylarkDocumentationGenerator generate incorrect documentation for is_executable

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3951]
https://docs.bazel.build/versions/master/skylark/lib/actions.html#expand_template says that the last argument is `executable` but the code https://github.com/bazelbuild/bazel/blob/e222ba362c4c8c0cc0c76b308ee899e75098746a/src/main/java/com/google/devtools/build/lib/analysis/skylark/SkylarkActionFactory.java#L798 shows that it should be `is_executable`. This is actually verified by writing a skylark action.

Found out the same issue with the `write` action

/cc @dslomov

**Comment by akira-baruah** [comment]
@damienmg @dslomov The docs for `expand_template` appear to correctly reference `is_executable` now. Has this bug been resolved?

**Comment by laurentlb** [comment]
Yes
