### ISSUE TITLE
Android, Windows: Android hello world won't build with Bazel 0.7.0

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3955]
This is again a long path issue, this time in `tools/android/aar_embedded_jars_extractor.py`. I have a fix for it.

I think it's time I update all `tools/android/*.py` files to support long paths, because we keep running into this issue.

**Comment by meteorcloudy** [comment]
Do we have a test for building the Android hello world?

**Comment by laszlocsomor** [comment]
No, but we have an open bug for it: https://github.com/bazelbuild/bazel/issues/3663

**Comment by aj-michael** [comment]
re test: it's coming in https://bazel-review.googlesource.com/#/c/bazel/+/18511, but i got unexpectedly busy in the last two weeks

**Comment by aj-michael** [comment]
Was this a new issue? The aar code has not been changed recently

**Comment by laszlocsomor** [comment]
We may not have triggered the bug before. Maybe the way we use the aar tool has changed? Anyway, I'm planning to fix these bugs once and for all by updating the Python tools under `//tools/android`.

**Comment by laszlocsomor** [comment]
#3963 subsumes this
