### ISSUE TITLE
Allow the `no-cache` execution requirement to be set via a tag on built-in rules

### ISSUE THREAD

**Issue by tybook** [bazelbuild/bazel#3960]
### Description of the problem / feature request / question:

I am using remote caching (Apache WebDAV with the `--experimental_remote_spawn_cache` option) and some of my build artifacts created by `genrule`s are very large (1-3GB). These artifacts don't take very long to build locally, so they would be unnecessarily taking up cache space and network bandwidth. It appears that Skylark actions can be excluded from remote caching by specifying `execution_requirements = { 'no-cache': '1' }` in their implementations. Setting this execution requirement as a tag on built-in rules (at least `genrule`s) does not work, however. It would seem that I would have to wrap my `genrule`s in a new build rule to exclude them from remote caching.

For the 0.8.0 release, could setting `tags = ['no-cache']`, or equivalent, on built-in rules be made to work?

### Environment info
* Operating System:
Ubuntu 16.04

* Bazel version (output of `bazel info release`):
0.7.0

* Relevant `.bazelrc`
```
<snip>
startup --host_jvm_args=-Dbazel.DigestFunction=SHA1
build --experimental_remote_spawn_cache
build --remote_rest_cache=http://REMOTE.CACHE.IP
build --experimental_strict_action_env
test --test_env=USER=dummytestuser  # see https://github.com/bazelbuild/bazel/issues/2574
```

**Comment by nicolov** [comment]
It's a one-line diff to `RemoteSpawnCache.java`, if you're willing to do it yourself.

**Comment by tybook** [comment]
Can you be more specific? I'm willing to do it myself but it isn't obvious to me what the one-line diff would be.

**Comment by nicolov** [comment]
AFAICT, this works fine:

```
-    if (options.remoteUploadLocalResults) {
+    if (options.remoteUploadLocalResults && !spawn.getExecutionInfo().containsKey("nospawncache")) {
```

**Comment by tybook** [comment]
That isn't working for me. The map `spawn.getExecutionInfo()` returns does not contain `"nospawncache"` or any other tag value I set in the `BUILD` file. Are you sure it's working for you?

**Comment by nicolov** [comment]
Now that I think about it, I may only have tested it on skylark actions,
not built-in rules.

**Comment by tybook** [comment]
It looks like your change is unnecessary now. As of at least release 0.7.0, you can specify
`execution_requirements = { 'no-cache': '1' },` in a Skylark action and the same effect as your change is achieved. See `mayBeCached()` in `src/main/java/com/google/devtools/build/lib/actions/Spawns.java` and its uses. 

This functionality is still not exposed via tags on built-in rules (at least not `genrule`s), though. I'm editing this issue to target that.

**Comment by nicolov** [comment]
Great catch, thanks!

**Comment by katre** [comment]
If this is not needed I will go ahead and close the issue. Please re-open or re-file it if there is still missing functionality.

**Comment by tybook** [comment]
Like my last comment says, there is still missing functionality:

> This functionality is still not exposed via tags on built-in rules (at least not genrules), though. I'm editing this issue to target that.

**Comment by katre** [comment]
My mistake, re-opening now.

**Comment by ulfjack** [comment]
It's probably just a one-line change to TargetUtils.java line 215 (or thereabouts, plus adding a corresponding test). I should've done that in the change where I added the new spawn cache code path. The change itself is trivial, but adding a test isn't. I'm traveling right now, and won't be back home in time for 0.8.0.

**Comment by tybook** [comment]
Related to https://github.com/bazelbuild/bazel/issues/4343
