### ISSUE TITLE
bazel sandboxing is too narrow for compiler-selecting conditionally-compiled code

### ISSUE THREAD

**Issue by rtsai** [bazelbuild/bazel#3961]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

We use gcc to compile our project, and use an experimental_action_listener to implement clang-tidy checking of the code as it compiles.

Part of our project uses boost (in source form, in our //third_party). Boost includes a "[select_compiler_config.hpp](https://github.com/boostorg/config/blob/boost-1.60.0/include/boost/config/select_compiler_config.hpp)" that checks for the compiler in use, and includes a compiler-specific header file (gcc.hpp, clang.hpp, etc.).

* In 0.4.3, things were working
* In 0.4.5, we needed to use strategy=standalone (see #2790)
* In 0.7.0, we can remove strategy-standalone for builds that do not depend on boost

For the boost-dependent builds, I observe the following differences in behavior:

* In 0.4.3, 5c346b5e4b6390e1d6c311b5361d6719/bazel-sandbox/3678643609906101330/execroot/foo/third_party/boost/libs/config is fully-populated with all header files.
* In 0.7.0, the same directory contains only the files needed to build with gcc, and the clang-tidy check fails because clang.hpp is not present.

I suspect the sandboxing code since 0.4.3 is improved to be more narrow and dependent only on files identified by some variant of gcc -M, which for a compiler-selecting header like Boost config.hpp would eliminate the files required for clang-tidy, causing things to fail.

The high-level feature request is a mechanism to enable clang-tidy as an action listener for compiler-dependent code when gcc is the compiler

### If possible, provide a minimal example to reproduce the problem:

I will try to create one and update later.

### Environment info
* Operating System: Ubuntu 16.04.3 LTS
* Bazel version (output of `bazel info release`): 0.7.0

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by rtsai** [comment]
Attached a sample workspace demonstrating the issue
[clang_gcc.tar.gz](https://github.com/bazelbuild/bazel/files/1809020/clang_gcc.tar.gz)

**Comment by philwo** [comment]
@mhlopko Any idea? The sandboxing code doesn't have any language specific knowledge - it simply includes all input files. Could it be that some are missing?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
