### ISSUE TITLE
Android, Windows: update //tools/android/*.py to support long paths on Windows

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3963]
Update `//tools/android/*.py` to support long paths on Windows.

**Comment by laszlocsomor** [comment]
Update: I haven't done anything for this bug and likely won't do anything before end of Q2'18.

**Comment by philwo** [comment]
@laszlocsomor If you still remember, what does it mean to update these scripts to support long paths on Windows? What kind of changes are required to the code?

(Or feel free to just close this issue, if it's no longer relevant.)

**Comment by laszlocsomor** [comment]
To use `tools/android/junction.py` in every script that deals with long-path inputs/outputs. Example: `tools/android/aar_resources_extractor.py`

Junction targets can be ~32K long even while the junction itself is shorter than MAX_PATH. This trick lets the script work with inputs / outputs under long paths.

**Comment by laszlocsomor** [comment]
> Example: `tools/android/aar_resources_extractor.py`

^ this is an example of a migrated script, i.e. one that can deal with long paths using `TempJunction` from `junction.py`.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
