### ISSUE TITLE
Aspects not returning correct paths for local_repositories

### ISSUE THREAD

**Issue by dmaclach** [bazelbuild/bazel#3970]
### Description of the problem / feature request / question:
Aspects do not appear to be given the correct paths for deps that are referenced via local_repositories in WORKSPACES.

WORKSPACE has:
local_repository(
    name = 'df_bzl_local',
    path = 'local',
)

The aspect prints the paths for all of the files

DEBUG: local_repo_issue/app/print.bzl:7:11: ../df_bzl_local/mylib/MyLib.cc.
DEBUG: local_repo_issue/app/print.bzl:7:11: app/App.h.
DEBUG: local_repo_issue/app/print.bzl:7:11: app/App.cc.
DEBUG: local_repo_issue/app/print.bzl:7:11: app/main.cc.

I would expect the first path to be ../local/mylib/MyLib.cc

The attached zip contains a full example.

I think this is blocking https://github.com/bazelbuild/tulsi/issues/9

### If possible, provide a minimal example to reproduce the problem:
[local_repo_issue.zip](https://github.com/bazelbuild/bazel/files/1416632/local_repo_issue.zip)
bazel build app --aspects app/print.bzl%print_aspect

### Environment info
* Operating System:
macOS 10.12

* Bazel version (output of `bazel info release`):
release 0.7.0-homebrew

**Comment by dslomov** [comment]
The aspect code is:
```
PrintProvider = provider()

def _print_aspect_impl(target, ctx):
    if hasattr(ctx.rule.attr, "srcs"):
        sources = [f for src in ctx.rule.attr.srcs for f in src.files]
        for e in sources:
          print(e.short_path)
    return [_PrintProvider()]

print_aspect = aspect(implementation = _print_aspect_impl,
    attr_aspects = ["deps"],
)
```

File's `short_path` (see `e.short_path`) is documented [here](https://docs.bazel.build/versions/master/skylark/lib/File.html#short_path). It is a path of this file related to _its_ root. Its root is in the "local" workspace, so this is WAI. 
What you want instead is `e.path`, which is a path related to execution root. 
Or am I missing something?

**Comment by dmaclach** [comment]
So if it is changed to `e.path` I get:

```DEBUG: local_repo_issue/app/print.bzl:7:11: external/df_bzl_local/mylib/MyLib.cc.
DEBUG: local_repo_issue/app/print.bzl:7:11: app/App.h.
DEBUG: local_repo_issue/app/print.bzl:7:11: app/App.cc.
DEBUG: local_repo_issue/app/print.bzl:7:11: app/main.cc.
```
I would expect the first path to be `local/mylib/MyLib.cc`

**Comment by dslomov** [comment]
Local repositories are "mounted" (symlinked) into an execroot (in this case, under `external/df_bzl_local`). `path = "local"` in `local_repository` is the local path on your machine - it is never visible to rules or aspects. The path where the external repo is mounted is all rules or aspects will ever get to see.

**Comment by dslomov** [comment]
Closing this, as there seems to be no bug here, but I'll be happy to help with figuring out what problem Tulsi runs into and what is the right solution.
