### ISSUE TITLE
wrapped_clang does not correctly pass arguments to xcrunwrapper.sh

### ISSUE THREAD

**Issue by didzis** [bazelbuild/bazel#3979]
### Description of the bug:

The wrapped_clang scripts do not correctly pass arguments to xcrunwrapper.sh, i.e., the argument list `$@` must be quoted: `"$@"`.

The following two files have this issue present
[tools/osx/crosstool/wrapped_clang.tpl](https://github.com/bazelbuild/bazel/blob/master/tools/osx/crosstool/wrapped_clang.tpl#L10)
[tools/osx/crosstool/wrapped_clang_pp.tpl](https://github.com/bazelbuild/bazel/blob/master/tools/osx/crosstool/wrapped_clang_pp.tpl#L10)
whereas this file has the quoting in place
[tools/osx/crosstool/wrapped_ar.tpl](https://github.com/bazelbuild/bazel/blob/master/tools/osx/crosstool/wrapped_ar.tpl#L18)

This does matter on some situations when there is a complicated command line option defined in `copts` for `cc_binary` rule that includes spaces, e.g., a define like `-DMESSAGE="Hello World!"` will be split into two command line arguments no matter how the string is quoted.

This generally applies to macOS platform where clang is the default toolchain.

### Environment info
* Operating System: macOS

* Bazel version: _master_ branch

**Comment by c-parsons** [comment]
Acknowledged, thanks for the catch. I'll make a PR.

**Comment by c-parsons** [comment]
Well, this is actually more complicated than I thought.

We're pretty sloppy about the way we pass arguments in the crosstool. For example, we pass '-framework Foundation' to all ios builds. When we "correctly" treat this as a single argument, of course the build fails because these should actually be defined as two arguments.

This is going to require we clean up the crosstool as well as maybe a few other locations, and thus will be a larger undertaking.

**Comment by darrengarvey** [comment]
I just hit this too. Isn't a simple fix for this to modify `wrapped_clang{,_pp}.tpl` like so:

```diff --git a/tools/osx/crosstool/wrapped_clang.tpl b/tools/osx/crosstool/wrapped_clang.tpl
index 3a523d228..192d61605 100644
--- a/tools/osx/crosstool/wrapped_clang.tpl
+++ b/tools/osx/crosstool/wrapped_clang.tpl
@@ -7,4 +7,4 @@ if [ -z ${MY_LOCATION+x} ]; then
   fi
 fi

-"${MY_LOCATION}"/xcrunwrapper.sh clang $@
+"${MY_LOCATION}"/xcrunwrapper.sh clang "$@"
diff --git a/tools/osx/crosstool/wrapped_clang_pp.tpl b/tools/osx/crosstool/wrapped_clang_pp.tpl
index 4afc7b056..01e94c52d 100644
--- a/tools/osx/crosstool/wrapped_clang_pp.tpl
+++ b/tools/osx/crosstool/wrapped_clang_pp.tpl
@@ -7,4 +7,4 @@ if [ -z ${MY_LOCATION+x} ]; then
   fi
 fi

-"${MY_LOCATION}"/xcrunwrapper.sh clang++ $@
+"${MY_LOCATION}"/xcrunwrapper.sh clang++ "$@"```

I'm trying to test this locally but hitting an issue with compiling bazel for OSX.

**Comment by darrengarvey** [comment]
Ah, no I see that won't work now. It was also tried in #3559.

This is quite a nasty one that I don't see an easy way for a user to work around.

**Comment by toulouse** [comment]
I'm on 10.12.6. Getting the same error; the temporary hack doesn't appear to work, either.

**Comment by toulouse** [comment]
The hack is editing config.h.in instead of config.h.cmake.in, which I realized after staring at it for a bit. The workaround works if you add it to that.

**Comment by meisterT** [comment]
Is this still an issue?

**Comment by jmmv** [comment]
wrapped_clang was rewritten in C++ so this problem should be gone.
