### ISSUE TITLE
Running with --experimental_remote_spawn_cache=true is susceptible to intermittent network / server errors

### ISSUE THREAD

**Issue by hhclam** [bazelbuild/bazel#3987]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem:

I'm trying to run Bazel with --experimental_remote_spawn_cache=true --remote_rest_cache=http://localhost:5701/hazelcast/rest/maps which works fine. 

However when used on a network with a real REST cache the RemoteSpawnCache is susceptible to intermittent network or server errors. For example a server timeout can fail the entire build. It should be more resilient to these errors and continue to build with a warning.

### If possible, provide a minimal example to reproduce the problem:

Run bazel with:
bazel build --experimental_remote_spawn_cache=true --remote_rest_cache=http://localhost:5701/hazelcast/rest/maps

Then shutdown the local hazelcast REST server. The build should continue with a warning. However I'm seeing and error such as:
[for host] failed: Unexpected IO error.: Connect to localhost:5701 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused).

### Environment info
* Operating System: Does not matter

* Bazel version (output of `bazel info release`): 0.7.0

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

**Comment by hhclam** [comment]
I updated a fix here for review: https://bazel-review.googlesource.com/c/bazel/+/19671

**Comment by buchgr** [comment]
This was merged. CAn be closed.
