### ISSUE TITLE
[Windows] build failed with: "must produce a single file"

### ISSUE THREAD

**Issue by ddwolf** [bazelbuild/bazel#3988]
### Description of the problem / feature request / question:
     I am building a project in windows, it failed with:
    /c/msys64/tmp/_bazel_usera/9l56y845/external/bazel_tools/tools/jdk/BUILD:187:17: in singlejar attribute of java_toolchain rule @bazel_tools//tools/jdk:toolchain: '@bazel_tools//tools/jdk:singlejar' must produce a single file.

while I can successfully build it in a linux VM, 

### Environment info
* Operating System: Windows 7 Professional Service Pack 1

* Bazel version (output of `bazel info release`): 

Build label: 0.7.0- (@non-git)
Build target: bazel-out/msvc_x64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 30 02:52:43 2017 (1509331963)
Build timestamp: 1509331963
Build timestamp as int: 1509331963

* Source code are downloaded from bazel release 0.7 dist.zip file: [here](https://github.com/bazelbuild/bazel/releases/download/0.7.0/bazel-0.7.0-dist.zip)

**Comment by katre** [comment]
Can you share the project being built so we can try to reproduce it? It sounds like your java_toolchain is misconfigured on Windows, but without your BUILD files we can't check that easily.

**Comment by ddwolf** [comment]
@katre the most simple case is this:
```bash
cat BUILD
>java_binary(
>name = "main",
>srcs = glob(["*.java"]),
>main_class = "Main",
>)
```

```bash
cat Main.java
>public class Main{
>public static void main(String[] args){
>  System.out.println("HelloWorld!");
>}
}
```

and WORKSPACE file is empty.

**Comment by dslomov** [comment]
@meteorcloudy  could you take a quick look? this is a potential 0.8 blocker

**Comment by ddwolf** [comment]
@dslomov @meteorcloudy any updates?

**Comment by meteorcloudy** [comment]
@ddwolf Sorry for the delay, I'll take a look immediately.

**Comment by meteorcloudy** [comment]
@ddwolf I don't see this error with both Bazel 0.7.0 and 0.8.0, can you give more details about reproducing this bug? Or try our latest 0.8.0 release, see if it works for you.

**Comment by YanzheL** [comment]
@asimshankar 
Same error when compiling example from bazel website

Steps to reproduce:
```
git clone https://github.com/bazelbuild/examples/
cd examples/java-tutorial
bazel build //:ProjectRunner
```

Output:

```
root@tegra-ubuntu:~/examples/java-tutorial# bazel build //:ProjectRunner
.................................
ERROR: /root/.cache/bazel/_bazel_root/9318dfd54d71a6b918f8033146aeac2a/external/bazel_tools/tools/jdk/BUILD:193:17: in singlejar attribute of java_toolchain rule @bazel_tools//tools/jdk:toolchain: '@bazel_tools//tools/jdk:singlejar' must produce a single file
ERROR: Analysis of target '//:ProjectRunner' failed; build aborted: Analysis of target '@bazel_tools//tools/jdk:toolchain' failed; build aborted
INFO: Elapsed time: 5.553s
FAILED: Build did NOT complete successfully (10 packages loaded)
```

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04 aarch64
- **Bazel version (if compiling from source)**:
0.9.0 and 0.10.0 (both tried with clean installation)
- **GCC/Compiler version (if compiling from source)**:
gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609
- **Device Info**:
Nvidia Jetson TX2
```
root@tegra-ubuntu:/usr/src# java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

root@tegra-ubuntu:/usr/src# javac -version
javac 1.8.0_151
```

**Comment by YanzheL** [comment]
I tried a fresh installation of bazel 0.9.0 (and 0.10.0) on amd64 architecture, no error produced.
It should be a bazel bug on aarch64 architecture CPUs. 
Can anyone have a look at this? Our production environment depend on this, so please fix it as soon as possible.

**Comment by pterjan** [comment]
I see the same error on linux/armv7

So far the only thing I noticed is https://github.com/bazelbuild/bazel/blob/master/src/BUILD#L182
The java version is used on windows and arm:

    }) + select({
        # TODO(bazel-team): Once https://github.com/bazelbuild/bazel/issues/2241
        # is resolved, use cc implementation of singlejar on windows
        "//src/conditions:windows": [
            "//src/java_tools/singlejar:SingleJar_deploy.jar",
            "//src/tools/launcher:launcher",
            "//third_party/def_parser:def_parser",
        ],
        "//src/conditions:arm": [
            "//src/java_tools/singlejar:SingleJar_deploy.jar",
        ],
        "//conditions:default": [
            "//src/tools/singlejar:singlejar",
        ],

The filegroup in https://github.com/bazelbuild/bazel/blob/master/tools/jdk/BUILD#L105 expects `singlejar/*` which doesn't get created here

When reading https://github.com/bazelbuild/bazel/blob/master/src/create_embedded_tools.py#L39 I see that output path for 'singlejar' is 'tools/jdk/singlejar/singlejar' and the one for '*SingleJar_deploy.jar' is 'tools/jdk/singlejar/SingleJar_deploy.jar' so tools/jdk/singlejar/ should still be there.

**Comment by pterjan** [comment]
on amd64, embedded_tools.zip contains `tools/jdk/singlejar/singlejar`, but if I switch the default to use the java version instead in `src/BUILD`, it now contains `src/java_tools/singlejar/java/com/google/devtools/build/singlejar/bazel-singlejar_deploy.jar` instead and no `tools/jdk/singlejar`.

I guess the name of the jar could be the problem as it doesn't match the rules for output files in create_embedded_tools.py.

I guess it was broken by commit 6705b508fe069147c853ca9669363342f3527689 as it seems to have renamed the java_binary and created an alias with the old name

**Comment by pterjan** [comment]
Fixing the name in create_embedded_tools.py seems to work, but I will not be able to properly test on arm soon as it takes > 1 day to build on my arm machine

**Comment by pterjan** [comment]
I can confirm that bazel built with this patch on arm now works properly
