### ISSUE TITLE
C++ rules link again when $PATH changes

### ISSUE THREAD

**Issue by nicolov** [bazelbuild/bazel#3989]
Changing `$PATH` or `$LD_LIBRARY_PATH` in the client environment cause re-linking of all cc binaries. This also happens when `--experimental_strict_action_env=true`. The explain log says: *Effective client environment has changed, using..*. In any case, compilation does _not_ run again. Forcing `--action_env=PATH=...` does not seem to work either.

Minimal reproduction case:

```
#/bin/bash

# ./make_wkspace.sh
# bazel build --experimental_strict_action_env=true //...
# export PATH=$PATH:hello
# bazel build --experimental_strict_action_env=true --explain=explain.log --verbose_explanations //...

cat << EOF > WORKSPACE
EOF

cat << EOF > BUILD
cc_binary(
    name = "my_test",
    srcs = ["main.cpp"],
)
EOF

cat << EOF > main.cpp
#include <iostream>

int main() {
    std::cout << "Hello world!\n";
}
EOF
```

Bazel 0.7.0 on Ubuntu 14.04

**Comment by nicolov** [comment]
I ended up tracing this down to the `/etc/bazel.rc` file shipped in the debian package, that sets `--action_env=LD_LIBRARY_PATH` and `--action_env=PATH=` (i.e. letting bazel inherit their values from the client environment).

AFAICT, overriding those settings does not work because of the order in which inherited and fixed environment variables are handled in [here](https://github.com/bazelbuild/bazel/blob/77baa4c372ae014db8e17f6d3c60bd88597853d9/src/main/java/com/google/devtools/build/lib/actions/ActionEnvironment.java#L53).

Changing `/etc/bazel.rc` fixed the problem for me, but I believe those defaults should be removed.

**Comment by aehlig** [comment]
Options in later rc-files can override those in earlier ones; so a user-specified `action_env` setting `PATH` to a fixed good value will render the actions independent of the value of `PATH` in the environment of the bazel client.

**Comment by aehlig** [comment]
Unassigning myself as I don't want to be involved in yet another bikeshedding discussion about what default values should be. The fact that different users have different needs was the very reason that those values are put into user-configurable files.

**Comment by drigz** [comment]
Looks like this was fixed by https://github.com/bazelbuild/bazel/commit/f482d9e74e93c1cb13ca8eec026b0e7f62f8d224.

**Comment by jin** [comment]
Reported fixed, closing. Please create a new issue if you run into this again.
