### ISSUE TITLE
Non-existent files in default_runfiles

### ISSUE THREAD

**Issue by drigz** [bazelbuild/bazel#3994]
rules_docker uses `default_runfiles` to get a list of runfiles to put into a docker image. It is running into an issue bazelbuild/rules_docker#207 (repro is there) where `default_runfiles` contains a non-existent "middleman" path, leading to:

`IOError: [Errno 2] No such file or directory: 'bazel-out/local-fastbuild/internal/_middlemen/foo-runfiles'`

It's not clear to me if this is a problem with `default_runfiles` or if consumers should filter out these non-existent files (eg [this workaround](https://github.com/drigz/rules_docker/commit/39ced16812f288120fa495d7cc033f2b4bc8f102)).

Is this expected behaviour for `default_runfiles`? It's hard to tell because of #3015.

### Environment info
* Operating System: Ubuntu 14.04
* Bazel version: 0.7.0

###  Relevant info
This appears to be analogous to to bazelbuild/bazel#2088, which was fixed in [a5294e6a](https://github.com/bazelbuild/bazel/commit/a5294e6a48a0c6ff6ef5eec918489f8564b40824) by replacing `getRunfiles().getArtifacts()` with `getRunfilesArtifactsWithoutMiddlemen()`.

**Comment by benjaminp** [comment]
dbbcbcb8d227b0f35000f2a07b75524bfe1b681b fixed this for the Python rules. https://bazel-review.googlesource.com/c/bazel/+/19550 should prevent this kind of issue from happening in the general case.

**Comment by drigz** [comment]
Fixed in bazel 0.8.0.
