### ISSUE TITLE
//src/test/shell/integration:progress_reporting_test consistently times out in bazel-remote-tests

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#3995]
In many runs of bazel-remote-tests, we see timeout errors for //src/test/shell/integration:progress_reporting_test.

See https://ci.bazel.io/blue/rest/organizations/jenkins/pipelines/Global/pipelines/bazel-tests-remote/runs/43/log/?start=0 for log

**Comment by katre** [comment]
This is reproducible locally.

**Comment by aehlig** [comment]
Since e974328478011a05b90a326b88987e1d62321d35 disabled the test, there is no ongoing breakage. As bazel-remote-tests are still experimental anyway, we can reduce the priority, as it is mainly a feature request to have this test being run on remote execution.
