### ISSUE TITLE
Tensorflow failures in Bazel CI

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#3996]
Tensorflow_Serving and tf_models_syntaxnet are both failing on CI, with errors like this:
```
[variation=,node=ubuntu_16.04-x86_64] ERROR: /home/ci/workspace/Global/tf_models_syntaxnet-variation=,node=ubuntu_16.04-x86_64/research/syntaxnet/syntaxnet/BUILD:646:1: Couldn't build file syntaxnet/binary_segment_transitions_test: Linking of rule '//syntaxnet:binary_segment_transitions_test' failed (Exit 1): gcc failed: error executing command 
[variation=,node=ubuntu_16.04-x86_64]   (cd /home/ci/.cache/bazel/_bazel_ci/e2a5aaf888eb50a1ece44dc2d11a4367/execroot/__main__ && \
[variation=,node=ubuntu_16.04-x86_64]   exec env - \
[variation=,node=ubuntu_16.04-x86_64]     PATH=/home/ci/node/node-v6.9.1-linux-x64/bin:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin \
[variation=,node=ubuntu_16.04-x86_64]     PWD=/proc/self/cwd \
[variation=,node=ubuntu_16.04-x86_64]     PYTHON_BIN_PATH=/usr/bin/python \
[variation=,node=ubuntu_16.04-x86_64]     PYTHON_LIB_PATH=/usr/local/lib/python2.7/dist-packages \
[variation=,node=ubuntu_16.04-x86_64]     TF_NEED_CUDA=0 \
[variation=,node=ubuntu_16.04-x86_64]     TF_NEED_OPENCL=0 \
[variation=,node=ubuntu_16.04-x86_64]   /usr/bin/gcc -o bazel-out/k8-opt/bin/syntaxnet/binary_segment_transitions_test '-Wl,-rpath,$ORIGIN/../_solib_k8/' -Lbazel-out/k8-opt/bin/_solib_k8 -pthread -pthread '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -Wl,--gc-sections -Wl,@bazel-out/k8-opt/bin/syntaxnet/binary_segment_transitions_test-2.params)
[variation=,node=ubuntu_16.04-x86_64] bazel-out/k8-opt/bin/_solib_k8/libsyntaxnet_Slibparser_Utransitions.so: error: undefined reference to 'tensorflow::strings::StrAppend(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, tensorflow::strings::AlphaNum const&, tensorflow::strings::AlphaNum const&)'
```

This does not seem to be reproducible locally.

**Comment by katre** [comment]
Problem appeared in tensorflow/serving at commit https://github.com/tensorflow/serving/commit/169c28d3349b4c874ee2a022f2c32a7c269ceaa7#diff-2c39bc19b761ac36dc046245d1d47fe6, so presumably it's something that changed between https://github.com/tensorflow/tensorflow/commit/0b0d3c12ace80381f4a44365d30275a9a262609b and https://github.com/tensorflow/tensorflow/commit/4270c4a00bb90d97418df5b0e9b6b3e148a72a1e

**Comment by allenlavoie** [comment]
Just a guess, but the undefined NodeDef seems to point to https://github.com/tensorflow/tensorflow/commit/5c7f9e316d8c7735308a217310350d416d7498cc. Are you (accidentally?) building with TensorFlow's bazelrc? Does adding `--config=monolithic` fix things?

**Comment by katre** [comment]
Yes, we are adding the .tf_configure.bazelrc to the bazelrc. Is this incorrect?

**Comment by allenlavoie** [comment]
Not incorrect necessarily, just not what I was expecting. TensorFlow is now building with an explicit shared object dependence (cc_binary with linkshared=1), and projects which build with TensorFlow as a submodule have not been updated to explicitly include that shared object (since Bazel does not have transitive shared objects yet). The plan was that they'd use their own bazelrcs and so wouldn't get the lines which enable it (set here https://github.com/tensorflow/tensorflow/blob/e6faa845c51bb69465146d93646947fd2ba53efa/configure.py#L953). But if you've picked up those lines, you'll need to build with `--config=monolithic` (or get @mhlopko to work on transitive shared objects :p).

**Comment by katre** [comment]
Both removing the .tf_configure.bazelrc and adding "--config=monolithic" makes my local tests pass.
I will look into adding the monolithic config to our runs.

Thanks for the advice.
