### ISSUE TITLE
Windows: backslashes passed to subprocess are unnecessarily unescaped.

### ISSUE THREAD

**Issue by yilei** [bazelbuild/bazel#4001]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I am running the generated .exe file of a py_binary, which is a data deps of another py_test. The backslashes in the arguments passed to the .exe file end up unnecessarily unescaped in the py_binary.

### If possible, provide a minimal example to reproduce the problem:

BUILD:
```python
py_binary(
    name = "sub",
    srcs = ["sub.py"],
)
py_test(
    name = "main",
    srcs = ["main.py"],
    data = [":sub"],
)
```

main.py:
```python
import os
import subprocess
import unittest
class MainTest(unittest.TestCase):
  def testMain(self):
    test_srcdir = os.getenv('TEST_SRCDIR')
    with open(os.path.join(test_srcdir, 'MANIFEST'), 'r') as f:
      for line in f:
        tokens = line.strip().split(' ')
        if len(tokens) == 2 and tokens[0] == '__main__/sub.exe':
          sub_path = tokens[1]
          break
    subprocess.check_call([sub_path, r'path\to\dir'])
if __name__ == '__main__':
  unittest.main()
```

sub.py:
```python
import sys
if sys.argv[1] != r'path\to\dir':
  raise RuntimeError('Unexpected sys.argv[1]: {}\n'.format(sys.argv[1]))
```

`bazel test :main` fails, because `sys.argv[1]` is actually `r'path\\to\\dir'` instead of `r'path\to\dir'`.

### Environment info
* Operating System:
Windows Server 2016

* Bazel version (output of `bazel info release`):
release 0.7.0

**Comment by yilei** [comment]
Any word on this?

**Comment by laszlocsomor** [comment]
I can take a look.

**Comment by meteorcloudy** [comment]
I think the problem is we always escape `\` in this function:
https://github.com/bazelbuild/bazel/blob/a5833a8cde9d9d3398f64edae134370f06784cf6/src/tools/launcher/util/launcher_util.cc#L111-L142

But `GetEscapedArgument` is not only used in python launcher, but also the Java and Bash launcher. I remember at least in Bash launcher, we have to always escape `\` for passing identical arguments.

**Comment by meteorcloudy** [comment]
We need a similar test for Python and Java
https://github.com/bazelbuild/bazel/blob/a5833a8cde9d9d3398f64edae134370f06784cf6/src/test/py/bazel/launcher_test.py#L276-L316

**Comment by laszlocsomor** [comment]
@meteorcloudy , I think we always have to follow Command Prompt escaping rules, not Bash escaping, because we pass the escaped arguments to CreateProcess.

I have a pending change that fixes this.

**Comment by meteorcloudy** [comment]
Right, but when we launch the exact binary
Bash: `bash.exe -c "foo/bin.sh arg1 arg2"`
Python: `python.exe foo/bin.zip arg1 arg2`(an executable python zip file)
So we have to escape arguments for bash.exe but not python.exe

Let's see if your change will break `testShBinaryArgumentPassing` or not.

**Comment by laszlocsomor** [comment]
You're right, my change did break `testShBinaryArgumentPassing`, among others.
I think we have to escape differently in the Bash and in the Java/Python launchers.

**Comment by laszlocsomor** [comment]
> So we have to escape arguments for bash.exe but not python.exe

Ah, now I understand what you meant by this ;)

**Comment by meteorcloudy** [comment]
> I think we have to escape differently in the Bash and in the Java/Python launchers.

I agree :)

**Comment by yilei** [comment]
Kindly ping?

**Comment by laszlocsomor** [comment]
I haven't been able to work on this lately.
@meteorcloudy , do you want to take over?

**Comment by meteorcloudy** [comment]
@yilei Sorry for the delay.
@laszlocsomor Sure, I can take over. ;)

**Comment by meteorcloudy** [comment]
Just sent a fix to review:
https://bazel-review.googlesource.com/#/c/bazel/+/26710/
