### ISSUE TITLE
Building a DLL that contains no sources complains about the lack of an '.ifso' file.

### ISSUE THREAD

**Issue by brianretford** [bazelbuild/bazel#4003]
### Description of the problem / feature request / question:
Building a DLL that has only deps and no sources no longer works. (Say you want to bundle the same library into an .so and a .dll and have separate build rules). 
Specifically it fails like this:
```
INFO: From Linking plaidml/plaidml.dll:
LINK : warning LNK4044: unrecognized option '/lpthread'; ignored
LINK : warning LNK4044: unrecognized option '/lpthread'; ignored
ERROR: C:/users/brian/plaidml/plaidml/BUILD:67:1: output 'plaidml/plaidml.ifso' was not created.
```
### If possible, provide a minimal example to reproduce the problem:

For a build rule that looks like this:
```
cc_binary(
    name = "plaidml.dll",
    linkshared = 1,
    deps = [
        ":api",
    ],
)
```

Adding a dummy source file that has at least one exported function solves the problem:
```
cc_binary(
    name = "plaidml.dll",
    linkshared = 1,
    srcs = [
        "dummy.cc"
    ],
    deps = [
        ":api",
    ],
)
```
dummy.cc:
```
extern "C" {
__declspec(dllexport)void i_love_bazel_most_of_the_time(char *message) {}
}
```

### Environment info
* Operating System:
Winders10

* Bazel version (output of `bazel info release`):
0.7.0

###  Have you found anything relevant by searching the web?
Nope (tried though). I built the example dll and figured out what was different.

### Anything else, information or logs or outputs that would be helpful?
Seems pretty straightforward.

**Comment by meteorcloudy** [comment]
Hi, @brandjon Why do you want to build a dll that expose no symbols at all?
Generally, Bazel expects users to expose symbols they need, so that the import library gets generated(sorry, it's still using the .ifso extension)

If you do need to generate such a dll and don't want to add a dummy.cc, Bazel can help you export symbols. Just use "windows_export_all_symbols" feature.
```
cc_binary(
    name = "plaidml.dll",
    linkshared = 1,
    deps = [
        ":api",
    ],
   features = ["windows_export_all_symbols"],
)
```
This way, all symbols from it's dependencies will be exported.

**Comment by brandjon** [comment]
(I think you meant @brianretford and got autocompleted to me. :) )

**Comment by meteorcloudy** [comment]
Opps,, Sorry for that...

**Comment by laszlocsomor** [comment]
@meteorcloudy : do you intend to work on this bug?

**Comment by meteorcloudy** [comment]
I think it's WAI, @brianretford is this still a problem for you?

**Comment by meteorcloudy** [comment]
So I'm closing it, please reopen if having any question.
