### ISSUE TITLE
native.repository_name() in the main repository returns "@" when it is documented as returning ""

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#4006]
Docs here:
https://docs.bazel.build/versions/master/skylark/lib/native.html#repository_name

When I run it in the main repostory and print it: `print(native.repository_name())`. I get the following output: 
```
DEBUG: /private/var/tmp/_bazel_endobson/e36ff165f90c34e5ec103dfa2b4ef8e1/external/minimal_racket/racket.bzl:402:3: @
```

It is unclear whether the current behavior or the documented behavior is what is desired.

bazel version 0.6.1

**Comment by meisterT** [comment]
Documentation has been fixed.
