### ISSUE TITLE
--action_env not forwarded through "tools" dependency

### ISSUE THREAD

**Issue by didzis** [bazelbuild/bazel#4008]
### Description of the problem:

Variables set by `--action_env` are not forwarded through `tools` dependency of a rule. To generate test example, paste following lines into terminal:

```shell
mkdir test
cd test
touch WORKSPACE
touch tool.sh
chmod +x tool.sh
cat > BUILD << EOF
genrule(
    name = "rule1",
    srcs = [],
    outs = ["out1.c"],
    cmd = "bash -c 'echo RULE1:TESTVAR=\$\$TESTVAR'; exit 1",
)

sh_binary(
    name = "tool",
    srcs = ["tool.sh"],
    # srcs = [":rule1"],
    data = [":rule1"],
)

genrule(
    name = "rule2",
    srcs = [],
    outs = ["out2.c"],
    cmd = "",
    tools = [":tool"],
)

genrule(
    name = "rule3",
    srcs = [],
    outs = ["out3.c"],
    cmd = "",
    tools = [":rule1"],
)

genrule(
    name = "rule4",
    srcs = [":rule1"],
    outs = ["out4.c"],
    cmd = "",
)

cc_binary(
    name = "main",
    srcs = [
        # ":rule1",
        # ":rule2",
        # ":rule3",
        # ":rule4",
    ],
    data = [
        # ":rule1",
        ":rule2",
        # ":rule3",
        # ":rule4",
        # ":tool",
    ],
)
EOF
bazel build :main --action_env TESTVAR=hello
```
outputs
```
RULE1:TESTVAR=
```
however depending on what is uncommented, i.e., `":rule1",`, `":rule2",`, `":rule3",`, `":rule4",`, `":tool",` at the end of BUILD, bazel may output also
```
RULE1:TESTVAR=hello
```
`rule1` gives `RULE1:TESTVAR=hello` - rule1 is directly referenced
`rule2` and `rule3` gives `RULE1:TESTVAR=` - rule1 is referenced via tools option
`rule4` and `tool` again gives `RULE1:TESTVAR=hello` - rule1 is referenced via middleman

If the `rule1` is referenced from the "_tool_" and from another rule as a dependency, it may be randomly executed with different environment set for each run. Is this the expected behaviour?

A consistent behaviour is obtained when exporting the environment variable into bazel environment, i.e.,
```
export TESTVAR="hello world!"
bazel shutdown
bazel build :main
```

_NOTE:_ in case there is a linking error, execute the last command (`bazel build ...`) once more.
_NOTE2:_ if more than one rule dependency is uncommented, it may randomly output both results, execute multiple times to verify, e.g.,
```shell
for i in 1 2 3 4 5; do bazel build :main --action_env TESTVAR=hello 2> /dev/null | grep TESTVAR ; done
```

### Environment info
* Operating System: macOS, Linux

* Bazel version: release 0.7.0, release 0.5.4

**Comment by r4nt** [comment]
Encountered the same problem trying to compile TensorFLow with CUDA and LD_LIBRARY_PATH: Nvidia's docs say using LD_LIBRARY_PATH is a way to set up compilation with cuda. This mostly works with the bazel/TensorFlow build, until we hit a host-compiled tool that links into cuda - the link then fails.

**Comment by RNabel** [comment]
There is a workaround:
You write your own custom bazel rule which uses `ctx.actions.run` to execute the shell script, and make sure to set the `use_default_shell_env` parameter to `True` - this parameter controls whether to forward the `--action_env` env vars to the shell script. 
If you need to access the environment variables within the custom rule itself you can use [`ctx.configuration`](https://docs.bazel.build/versions/master/skylark/lib/configuration.html).
See docs: https://docs.bazel.build/versions/master/skylark/lib/actions.html#run

**Comment by meteorcloudy** [comment]
As proposed by @ulfjack at https://github.com/bazelbuild/bazel/issues/6473#issuecomment-441230398, I think we should add `--host_action_env` (maybe `--host_test_env` as well). Is there any progress on this?
This has been a problem for many TensorFlow users. (eg. tensorflow/tensorflow#22395)

@lberki @aehlig

**Comment by endobson** [comment]
I believe I'm running into this in relation to #7899 on macOS. The default path that bazel uses does not find my installation of python3 (macports, `/opt/local/bin`), and I cannot use action_env to make it find it for the actions that run without `use_default_shell_env` which I cannot fix as they are in dependencies.

I currently have a 'workaround' with `--extra_toolchains=@bazel_tools//tools/python:autodetecting_toolchain_nonstrict` but that is just putting off migrating to the correct path.

**Comment by crorvick** [comment]
What is the status of adding `--host_action_env` to Bazel?

**Comment by Flamefire** [comment]
I currently experienced something very similar in TensorFlow. But there it was due to use of `exec_tools` while `tools` works.
