### ISSUE TITLE
Illegal instruction: 4 on macOS 10.11.6 El Capitan

### ISSUE THREAD

**Issue by aacirino** [bazelbuild/bazel#4014]
Either installing with homebrew or downloading the binary I am not able to run bazel. My info:

macOS 10.11.6
bazel 0.7.0

**Comment by katre** [comment]
Please include more details, including a log of the errors.

**Comment by aacirino** [comment]
Hi, there are no details, invoking bazel yields the error:

`Hackintosh:~ aacirino$ bazel`
`Illegal instruction: 4`

I've attached the crash report file.
[bazel-real_2017-11-03-125145_Hackintosh.crash.zip](https://github.com/bazelbuild/bazel/files/1441429/bazel-real_2017-11-03-125145_Hackintosh.crash.zip)

**Comment by katre** [comment]
Thanks!

**Comment by c-parsons** [comment]
@cvcal  looks like a launcher error? If you're not the correct person to look at this, feel free to add whomever else :)

**Comment by cvcal** [comment]
No, this does not look like a launcher error. Does the following question on stack-overflow help? https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10. It seems that this is a problem with the versioning of mac and its interface protobuf. @jmmv does this sound similar?

**Comment by meisterT** [comment]
This is probably no longer relevant.
