### ISSUE TITLE
Invalid name for external dependency

### ISSUE THREAD

**Issue by vmax** [bazelbuild/bazel#4018]
### Description of the problem / feature request / question:

On the [docs](https://docs.bazel.build/versions/master/external.html) specify valid names for external dependencies. Dash (as in the example, `coworkers-project`) raises an error:

```
ERROR: …/WORKSPACE:61:1: local_repository rule //external:coworkers-project's name field must be a legal workspace name.
```

### If possible, provide a minimal example to reproduce the problem:
Try specifying an external dependency with the same name as in docs.

### Environment info
* Operating System: macOS 10.13 
* Bazel version (output of `bazel info release`): `release 0.7.0-homebrew`

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
Installed via [Homebrew](brew.sh)

**Comment by akira-baruah** [comment]
@spomorski I think you can close this issue since #4020 has been merged. The [docs](https://docs.bazel.build/versions/master/external.html#bazel-projects) have also been updated to reflect the fix.
