### ISSUE TITLE
git_repository should support Google Cloud Source Repositories

### ISSUE THREAD

**Issue by michaelsafyan** [bazelbuild/bazel#4025]
### Description of the problem / feature request / question:

The git_repository() rule doesn't work when authentication is involved. This is problematic for development using private repositories as hosted on Google Cloud. For example, if you develop purely within Google Cloud Shell and have multiple repositories within the same Google Cloud project, you cannot have one repository reference another via the git_repository() rule.

Ideally, git_repository() would support Git's "credential helper" mechanism (as set via git config --global credential.helper) and would be able to work with Google Cloud Source Repositories via the credential helper supplied when installing the Google Cloud SDK (and would similarly work with any other repository provider that supplies a valid credential helper). Failing that, it would be ideal if the version of Bazel installed on Google Cloud Shell were to specially include some logic that would enable authorization with the Cloud Source repositories in the git_repository() rule.

### If possible, provide a minimal example to reproduce the problem:

1. Create a throw-away Google Cloud project.
2. At "console.cloud.google.com", create a Cloud Source repository.
3. In this repository, create a WORKSPACE, BUILD, and trivial rule (e.g. a cc_library
    that exports some very simple C++ function that returns "Hello, World").
4. Create another Cloud Source repository.
5. In the second respository, create a WORKSPACE, BUILD, etc. rules. Create a
    cc_binary that includes the functionality from the first library.
6. In the "WORKSPACE" file of the second repository, try to create a "git_repository"
    rule that references the URL of the first repository. That URL should look something
    like "https://source.developers.google.com/p/$PROJECT_ID/r/$REPOSITORY_NAME"

Observed:
Fails, because Cloud Source Repositories require authorization.

Expected:
Should succeed (at least while authenticated in this project).

### Environment info
* Operating System:
Google Cloud Shell [custom debian-based VM]

* Bazel version (output of `bazel info release`):
release 0.7.0

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

N/A

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by ittaiz** [comment]
I'm pretty certain "git@proj.git" format works with authentication.
Is that format not supported by GCSR?

**Comment by michaelsafyan** [comment]
@ittaiz I'm not sure what you are proposing/saying. According to the [git_repository](https://docs.bazel.build/versions/master/be/workspace.html#git_repository) rule documentation, there is "currently no support for authentication" in the `remote` field that indicates the Git repository (and even if there were, I'm not sure that it would be ideal to encode the username in the `WORKSPACE` as the user is something that would reasonably vary depending on who is invoking the build).

I'm not sure what kind of authentication Cloud Source Repositories uses, though it would surprise me if it were not the typical OAuth2 credentials that most other Google services use. The Google Cloud SDK includes a "git-credential-gcloud.sh" script that is invoked by Git to resolve the credential for Git (this script is configured to be invoked via `git config credential.helper gcloud.sh`).

**Comment by katre** [comment]
Have you tried using the Skylark-based git_repository rule, rather than the native one? The Skylark-based rule uses the native git binary, and thus uses the same configuration setup you already have.

To try it, add this before your first git_repository rule in WORKSPACE:
```
load('@bazel_tools//tools/build_defs/repo:git.bzl', 'git_repository')
```

The rule is intended to be a drop-in replacement for the native rule, which we plan to deprecate at some point.

**Comment by ittaiz** [comment]
@damienmg is @katre correct in saying that native git repository will be deprecated in favor of the skylark one? Since the skylark one depends on whatever git is installed this adds somewhat of a non-reproducibility to the build. it might be small but I don't like it that much.

@michaelsafyan We have the following declaration with then native rule
```
git_repository(
             name = "foo",
             remote = "git@github.com:some-org/some-private-repository.git",
             commit = ...
)
```
 and that utilizes the ssh keys. I don't think we needed to do anything for it but I might have forgotten already. 
In any case the above allows me to clone a private git repository from github.

**Comment by michaelsafyan** [comment]
Thanks, @ittaiz. That's perfect. In the case of Cloud Source Repositories, I just used the HTTPS URL (there was no need to specify a user at all). I was simply missing the use of this new definition.

I note that the documentation here:
https://docs.bazel.build/versions/master/be/workspace.html#git_repository

... now links to the new Skylark rule, but the formatting makes this a little subtle...

Would it be possible to draw a big warning or note box to use the other definition? And would it be possible to show the code:

     load('@bazel_tools//tools/build_defs/repo:git.bzl', 'git_repository')

... inline so that it is not necessary to go digging for it on another page? Thanks!

**Comment by ittaiz** [comment]
@michaelsafyan I'm glad it's working for you but just so it's clear I'm not using the skylark one and the load isn't needed. I'm using the native one the way I showed above.
Like I said I'd rather not use the skylark one until I understand better how I can have it using a reproducible git.

**Comment by dslomov** [comment]
git_repositories are no more
