### ISSUE TITLE
GLIBC_2.14 not found 

### ISSUE THREAD

**Issue by zjh-nudger** [bazelbuild/bazel#4032]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
GLIBC_2.14' not found 

### If possible, provide a minimal example to reproduce the problem:
when I compile bazel use *.sh shell file.

### Environment info
* Operating System:
uname -a 
Linux x86_64 #1 SMP Tue Nov 29 17:56:13 CST 2016 x86_64 x86_64 x86_64 GNU/Linux

* Bazel version (output of `bazel info release`):
0.1.0 and 0.7.0

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).
the follow info occurs when I run bazel commond.
bazel: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by bazel)
bazel: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by bazel)
bazel: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by bazel)

**Comment by damienmg** [comment]
Wheredid you get your bazel binary? Which distribution are you using?

**Comment by zjh-nudger** [comment]
I got it from 'https://github.com/bazelbuild/bazel/releases'. I tried the version of 'bazel-0.7.0-installer-linux-x86_64.sh' and 'bazel-0.1.0-installer-linux-x86_64.sh'.

**Comment by damienmg** [comment]
And your Linux distribution is?

**Comment by zjh-nudger** [comment]
Linux version 2.6.18-128.el5xen (mockbuild@hs20-bc1-7.build.redhat.com) (gcc version 4.1.2 20080704 (Red Hat 4.1.2-44)) #1 SMP Wed Dec 17 12:01:40 EST 2008

**Comment by jin** [comment]
Closing this as obsolete. Please create a new issue if you're running into this problem with the latest Bazel versions.
