### ISSUE TITLE
Please allow Crosstool features to be defined without redefining all of CROSSTOOL.tpl

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel#4044]
Projects like Envoy want to have a broader range of build modes than just opt/fastbuild/dbg. Currently Envoy has a custom bazelrc defining flag sets as configs:

```
# Allow --config=asan builds
build:asan --define ENVOY_CONFIG_ASAN=1
build:asan --copt -fsanitize=address,undefined
build:asan --linkopt -fsanitize=address,undefined
# ...
```

It would be nice if these additional flags could be represented as Crosstool features -- then they could be enabled per-target, or excluded from certain targets that are known to be problematic for certain flags.

**Comment by jin** [comment]
cc @hlopko, please triage if this is still relevant.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
