### ISSUE TITLE
link  shared library which compiled by myself failed 

### ISSUE THREAD

**Issue by xxlest** [bazelbuild/bazel#4046]
bazel version is 0.5.4,  system is ubuntu 16.04, I'm trying to use so file which i build ,but failed 

build file:
cc_library(
    name = "hello-time",
    srcs = ["hello-time.cc"],
    hdrs = ["//main:hello-time.h","//main:hello-greet.h"],
)

cc_library(
    name = "hello-shared",
    srcs = ["hello.so"],
    hdrs = ["hello-greet.h"],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
    deps = [
        ":hello-time",
        "//main:hello-shared",
    ],
)

and i got error:   /usr/bin/ld.gold: error: cannot find -lhello
actually  i have hello.so file in main folder, i confused for whole day. since i'm trying to modifed tesorflow serving for support  mxnet model, and want to load mxnet .so file.

**Comment by damienmg** [comment]
@mhlopko to triage

**Comment by mhlopko** [comment]
I'd be surprised if this was broken in bazel. Linking of which target fails? Why do you have //main:hello-greet.h header twice? It should be owned only by one target, and other targets should depend on it via `deps`. That's not related though. You can run the build with `--subcommands` to see the generated commands. Then you can `cd` into the sandbox and see if the hello.so is in the sandbox, and also see if the command (and params file) are correct.

**Comment by mhlopko** [comment]
Also feel free to upgrade to bazel 0.7, a lot has changed since 0.5.4

**Comment by jin** [comment]
I'm gonna close this as obsolete. If you're running into this bug at newer Bazel version, please create a new issue.
