### ISSUE TITLE
Document SkylarkLateBoundDefault

### ISSUE THREAD

**Issue by tvolkert** [bazelbuild/bazel#4050]
https://docs.bazel.build/versions/master/skylark/lib/attr.html#parameters-3

Can you please document `SkylarkLateBoundDefault`?

**Comment by c-parsons** [comment]
Sorry about the stale bug.

I believe this was done some time in 2018-2019:

https://docs.bazel.build/versions/master/skylark/lib/LateBoundDefault.html

Please feel free to reopen if you have any questions about the new documentation.
