### ISSUE TITLE
Bazel reports an non-existant BUILD file when .bzl file is present

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/bazel#4056]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

Bazel 0.7.0 reports a non-existent `BUILD` in the same folder as a dependent .bzl file.

### If possible, provide a minimal example to reproduce the problem:

Minimum example repo is here: https://github.com/gregmagolan/bazel-buildfiles-bug

Run `bazel query "buildfiles(deps(set(:sometarget)))"` with Bazel 0.7.0 and you'll see

```
//:somerule.bzl
//:BUILD.bazel
//:BUILD
```

instead of the expected

```
//:somerule.bzl
//:BUILD.bazel
```

since there is no BUILD file present

### Environment info
* Operating System: OSX & Linux

* Bazel version (output of `bazel info release`): 0.7.0

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by katre** [comment]
Hmm, that's pretty odd. I'll investigate.

**Comment by katre** [comment]
Sent https://bazel-review.googlesource.com/#/c/bazel/+/20530
