### ISSUE TITLE
document "build -c <...>" option: have a short to long list correspondence somewhere

### ISSUE THREAD

**Issue by excavador** [bazelbuild/bazel#4062]
documentation about "-c" option missed:
https://docs.bazel.build/versions/master/command-line-reference.html#build

Option was mentointed here https://github.com/bazelbuild/rules_go/issues/993

**Comment by ianthehat** [comment]
This is actually documented, the easiest way to find the short form documentation at the moment is to search for [-c] (for any of the single letter options), but that is something you kind of have to just know. Maybe a table of short to long forms somewhere would be helpful?

**Comment by excavador** [comment]
> Maybe a table of short to long forms somewhere would be helpful?

Definitely! It would be awesome.
Just imagine how to user search information - find link to command line reference and make search on the page.
