### ISSUE TITLE
pkg_tar fails when src file name contains the '=' character

### ISSUE THREAD

**Issue by sghiaus** [bazelbuild/bazel#4063]
### Description of the problem / feature request / question:

Cannot build simple `pkg_tar` target when a file contains the `=` character, e.g. if the file is named `a=b`.

### If possible, provide a minimal example to reproduce the problem:
```
mkdir mydir
touch mydir/a=b

pkg_tar(
    name = "test-tar",
    extension = "tar.gz",
    strip_prefix = "/",
    package_dir = "/home/user",
    srcs = glob(["mydir/**/*"]),
    mode = "0777",
)
```

### Environment info
* Operating System:
Linux x64, Ubuntu 14.04

* Bazel version (output of `bazel info release`):
release 0.7.0

### Anything else, information or logs or outputs that would be helpful?
```
    with open(file_content, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'mydir/a'
Target //prebuilt:test-tar failed to build
```

The `=` character is used as delimiter in `bazel-out/..../test-tar.args` which conflicts with the file name.

**Comment by joshfischer1108** [comment]
Is this still an issue that needs to be corrected?

**Comment by fajran** [comment]
I run into the same problem. I did check the pkg_tar rule and I see the `pkg_tar` rule uses [`build_tar.py`](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/pkg/build_tar.py) script underneath. As @sghiaus mentioned, the script uses `=` as delimiter which conflicts with the file name.

**Comment by fajran** [comment]
it's interesting to see that the rule/script uses `=` as delimiter for [files](https://github.com/bazelbuild/bazel/blame/master/tools/build_defs/pkg/pkg.bzl#L47), [modes](https://github.com/bazelbuild/bazel/blame/master/tools/build_defs/pkg/pkg.bzl#L57), [owners](https://github.com/bazelbuild/bazel/blame/master/tools/build_defs/pkg/pkg.bzl#L59), and [owner names](https://github.com/bazelbuild/bazel/blame/master/tools/build_defs/pkg/pkg.bzl#L62), but uses colon `:` for [symlinks](https://github.com/bazelbuild/bazel/blame/master/tools/build_defs/pkg/pkg.bzl#L76).
