### ISSUE TITLE
REST cache: uploads broken after change to streaming

### ISSUE THREAD

**Issue by nicolov** [bazelbuild/bazel#4066]
After, https://github.com/bazelbuild/bazel/commit/5de01e5ed348a0b9d9eea88502fcca4b8c4133ed, which enabled streaming uploads to the remote REST cache, ~10% of PUT requests are rejected by nginx with status code 400:

```
10.64.1.111 - - [09/Nov/2017:17:09:03 -0800] "PUT /cache/cas/ff81135233341d671607a1ee7d57a11934c2b57051bede45b47b35f0f169f71d HTTP/1.1" 400 0 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_141)"
2017/11/09 17:09:03 [info] 62558#0: *153 client prematurely closed connection, client: 10.64.1.111, server: , request: "PUT /cache/cas/4cad70f6be1d25a3513684ed980771718db221bc48b95dfbd97cab9ac45b5cd9 HTTP/1.1", host: "10.64.1.111:7979"
```

I've also tried [caddy](https://caddyserver.com/docs/http.webdav) and have the same unexpected EOF issues.

@benjaminp You mentioned that you were using your own custom backend, right?

**Comment by benjaminp** [comment]
Is what you're building public? I just ran a clean build of `//src:bazel` using 9135b7bfc4245e16bd6599e22dce0ba077e0d10a with the REST cache backed by nginx and didn't see a single PUT error.

**Comment by nicolov** [comment]
I tested again and it seems to actually work fine, I don't what was up with my network configuration. Sorry for the trouble.
