### ISSUE TITLE
Toolchains with deps in target mode

### ISSUE THREAD

**Issue by ianthehat** [bazelbuild/bazel#4067]
At the moment all the deps of a toolchain are evaluated in host mode.
It would be nice if toolchains could "inject" deps on target (for instance, the library that goes along with the generated source file produced by the toolchain) but there is no way to achieve this at the moment that works for cross compilation.

**Comment by damienmg** [comment]
@katre: I don't really understand, can you tal and triage?

**Comment by katre** [comment]
@ianthehat and I discussed this issue, I know what is required.

**Comment by katre** [comment]
This will be implemented by #11128.
