### ISSUE TITLE
Provide command line option to enable network sandbox by default

### ISSUE THREAD

**Issue by philsc** [bazelbuild/bazel#4071]
I am not exactly sure in what release of the official repo this happened, but for at least two internal bazel upgrades we've partially reverted c5af2f3f2d974f7d0d84cecab6c57444b3413b01.

We understand that this was done because of performance concerns, but we're finding too much value in the sandbox to give up. This is on Linux.

Would it be reasonable to provide a command line option that enables/disables the network sandbox?

I believe @philwo agreed that that'd be useful.

/cc @AustinSchuh

**Comment by philwo** [comment]
Happy to add this. As always, please ping me regularly to ensure it stays on my list, until the feature is there. ;)

**Comment by Globegitter** [comment]
ping @philwo Would love to see this as a flag to be able enforce this for globally.

**Comment by philwo** [comment]
@Globegitter I can look at this after my vacation (I'll be back on April 2nd). If I forget, please feel free to ping again.

**Comment by AustinSchuh** [comment]
I added a flag ~6 months ago and this is in master.  I'm home sick or I'd go look it up for you.

**Comment by AustinSchuh** [comment]
```--experimental_sandbox_default_allow_network=false``` should do the trick.

**Comment by Globegitter** [comment]
Ah yes thanks for providing this and mention it here - will give it at try.
