### ISSUE TITLE
android ndk builds use wrong headers

### ISSUE THREAD

**Issue by mobileink** [bazelbuild/bazel#4072]
### Description of the problem / feature request / question:

Android builds that build native code pull system headers from $NDK/platforms/... rather than $NDK/sysroot.

### If possible, provide a minimal example to reproduce the problem:

In a C11 source file:
#include <assert.h>
static_assert( 1 == 0, "static assert failed successfully - comment me out and recompile");

(While you're at it, add #include <asm/types>, to validate that platform-specific headers are correctly included.)

Build with copt -std=c11. It should fail; if the compile succeeds with a warning about "implicit declaration of function 'static_assert' is invalid in C99", then the wrong assert.h header is being used. The ones in $NDK/platforms do not define static_assert; the one in $NDK/sysroot does.

I cannot provide a patch, but I have a working custom CROSSTOOL.
The fix is to point build_sysroot to $NDK/platforms/android-<api level>/arch-<arch>.  This is for lib searches.
Then use unfiltered_cxx_flag: "-isysroot ....." tell bazel to use $NDK/sysroot for header searches.
Use cxx_builtin_include_directory to point to $NDK/sysroot.
Use unfiltered_cxx_flag to explicitly add both $NDK/sysroot/usr/include and $NDK/sysroot/usr/include/<TRIPLE> to the search paths using -I or -isystem.

With clang you need to pass the -I stuff to the preprocessor as well, using -Wp,-I

### Environment info
* Operating System:

macOS 10.12.6

* Bazel version (output of `bazel info release`):

release 0.7.0-homebrew

**Comment by jin** [comment]
Sorry for the delay, this is fixed with the release of NDK 15/16 support:

```
jingwen@jingwen:~/code/crosstool
$ cat foo.c
#include <assert.h>
#include <asm/types.h>

static_assert( 1 == 0, "static assert failed successfully - comment me out and recompile");

int main() {}

jingwen@jingwen:~/code/crosstool
$ cat BUILD
cc_library(
    name = "foo_c",
    srcs = ["foo.c"],
)

android_binary(
    name = "a",
    custom_package = "a.a",
    manifest = "AndroidManifest.xml",
    deps = [":foo_c"],
)

jingwen@jingwen:~/code/crosstool
$ gbazel build --fat_apk_cpu=armeabi-v7a,mips,x86,arm64-v8a --android_crosstool_top=@androidndk//:toolchain-libcpp :a --copt='-std=c11'
WARNING: API level 27 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 26
INFO: Analysed target //:a (1 packages loaded).
INFO: Found 1 target...
ERROR: /usr/local/google/home/jingwen/code/crosstool/BUILD:1:1: C++ compilation of rule '//:foo_c' failed (Exit 1)
foo.c:4:1: error: static_assert failed "static assert failed successfully - comment me out and recompile"
static_assert( 1 == 0, "static assert failed successfully - comment me out and recompile");
^              ~~~~~~
external/androidndk/ndk/sysroot/usr/include/assert.h:59:24: note: expanded from macro 'static_assert'
# define static_assert _Static_assert
                       ^
1 error generated.
Target //:a failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.210s, Critical Path: 0.63s
FAILED: Build did NOT complete successfully

jingwen@jingwen:~/code/crosstool
$ zipinfo -1 bazel-bin/a.apk
nativedeps
lib/arm64-v8a/liba.so
lib/armeabi-v7a/liba.so
lib/mips/liba.so
lib/x86/liba.so
AndroidManifest.xml
META-INF/CERT.SF
META-INF/CERT.RSA
META-INF/MANIFEST.MF
```

Do you mind trying out Bazel on master and let me know if it still doesn't work for you?

**Comment by jin** [comment]
Closing this issue for now, please reopen if you are still facing related issues. Thanks!

**Comment by mobileink** [comment]
Will do, but it may be a few days before I can get to it.

Thanks!
