### ISSUE TITLE
Closure rules fail to build

### ISSUE THREAD

**Issue by schroederc** [bazelbuild/bazel#408]
Following the instructions in https://github.com/bazelbuild/bazel/tree/6db6eba6b2e1a0368e79da47a8cafd5dd9b6d63e/tools/build_rules/closure results in the following error during a build/fetch:

```
ERROR: /home/schroederc/.cache/bazel/_bazel_schroederc/ddace01a1ad38df359eb57115be59fad/external/closure_library/BUILD:1: Extension file not found: 'tools/build_rules/closure/closure_js_library.bzl'.
ERROR: /home/schroederc/kythe/kythe/javascript/util/BUILD:5:1: error loading package '@closure_library//': Extension file not found: 'tools/build_rules/closure/closure_js_library.bzl' and referenced by '//kythe/javascript/util:uri_lib'.
WARNING: errors encountered while analyzing target '//kythe/javascript:kythe': it will not be built.
WARNING: errors encountered while analyzing target '//kythe/javascript/util:uri_lib': it will not be built.
```

BUILD source:
```
load("/tools/build_rules/closure/closure_js_library", "closure_js_library")
load("/tools/build_rules/closure/closure_js_binary", "closure_js_binary")

closure_js_library(
    name = "uri_lib",
    srcs = ["uri.js"],
    deps = [
        "@closure_library//:closure_library",
    ],
)

closure_js_binary(
    name = "uri",
    compilation_level = "simple",
    main = "kythe.util.uri",
    deps = [":uri_lib"],
)
```

Removing the `@closure_library//:closure_library` bypasses this error but then the library obviously can't find the closure library during compilation and fails with `namespace never provided` errors.

It seems like Bazel can't find the `//tools/build_rules/closure:closure_js_library.bzl` file in the context of https://github.com/bazelbuild/bazel/blob/6db6eba6b2e1a0368e79da47a8cafd5dd9b6d63e/tools/build_rules/closure/closure_library.BUILD (even though it surely exists).

My WORKSPACE file is exactly copied from https://github.com/bazelbuild/bazel/blob/6db6eba6b2e1a0368e79da47a8cafd5dd9b6d63e/tools/build_rules/closure/closure.WORKSPACE.

**Comment by kjiwa** [comment]
Was the file ```tools/build_rules/closure/closure_js_library.bzl``` part of your workspace or were you trying to reference it from Bazel's base workspace?

**Comment by damienmg** [comment]
Hello,

What's the output of :
`bazel info package_path`
`ls tools/build_rules`
`ls tools`
`ls tools/build_rules/closure`
?

**Comment by schroederc** [comment]
It definitely exists.  That's why I filed an issue.

```
$ bazel info package_path
INFO: Writing profile data to '/tmp/bazel.prof'
%workspace%:/usr/local/google/home/schroederc/bazel/base_workspace

$ ls tools/build_rules
cc_resources.bzl  closure  doc.bzl  docker.bzl  go.bzl  kythe.bzl  lexyacc.bzl  proto.bzl

$ ls tools
arc  bazel.rc  BUILD  build_rules  cpp  defaults  docker  genrule  go  jdk  modules  test  test_sharding_compliant

$ ls tools/build_rules/closure
BUILD                   closure_js_binary.bzl   closure_library.BUILD           closure_template_library.bzl  closure.WORKSPACE
closure_compiler.BUILD  closure_js_library.bzl  closure_stylesheet_library.bzl  closure_templates.BUILD       README.md
```

**Comment by kjiwa** [comment]
I can repro this with both your BUILD file and with the example file listed in the rules documentation.

```
ERROR: /home/kjiwa/.cache/bazel/_bazel_kjiwa/7dd834ca79225cd88bd5bdc844663400/external/closure_library/BUILD:1: Extension file not found: 'tools/build_rules/closure/closure_js_library.bzl'.
ERROR: /home/kjiwa/src/hello/test/BUILD:12:1: error loading package '@closure_library//': Extension file not found: 'tools/build_rules/closure/closure_js_library.bzl' and referenced by '//test:hello_lib'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 0.806s
```

Not sure why it doesn't work, though. It seems like the problem comes from the ```closure_library``` build target. @damienmg Could it be an issue with how files are loaded out of external workspaces?

**Comment by damienmg** [comment]
Arf this a long standing bug. You cannot refer to skylark extension in the package path from remote repository. The fix is not easy and we have several work going in // for fixing it.

The workaround is to copy the extension to the current workspace.

PS: Sorry for the delay, beta and all that, you know :)

**Comment by schroederc** [comment]
I'm not sure what you mean by "current" workspace.  The extension is already in the Kythe workspace, and I don't have control over the closure http/git workspaces.

**Comment by kjiwa** [comment]
This has to be a regression -- the ```closure_library``` rule used to work in the past. I was able to create a standalone repro. I have a workspace (```my_workspace```) and another folder representing a external repository (```my_library```).

```
$ find . -type f | sort
./my_library/u.txt
./my_library/v.txt
./my_library/w.txt
./my_workspace/hello/a.txt
./my_workspace/hello/BUILD
./my_workspace/tools/build_rules/my_library.BUILD
./my_workspace/tools/build_rules/zip_archive.bzl
./my_workspace/WORKSPACE
```

Note: the text files are randomly generated using ```base64 /dev/urandom | head -c 1000000 > u.txt```.

`my_workspace/hello/BUILD`

```
load("/tools/build_rules/zip_archive", "zip_archive")

zip_archive(
    name = "a",
    srcs = ["a.txt"],
)
```

`my_workspace/tools/build_rules/my_library.BUILD`

```
load("/tools/build_rules/zip_archive", "zip_archive")

zip_archive(
    name = "my_library_archive",
    srcs = glob(["*.txt"]),
)
```

`my_workspace/tools/build_rules/zip_archive.bzl`

```python
def _impl(ctx):
  ctx.action(
      inputs=list(ctx.files.srcs),
      outputs=[ctx.outputs.out],
      command="/usr/bin/zip %s %s" % (
          ctx.outputs.out.path, " ".join([src.path for src in ctx.files.srcs]))
  )


zip_archive = rule(
    implementation=_impl,
    attrs={"srcs": attr.label_list(allow_files=True)},
    outputs={"out": "%{name}.zip"}
)
```

`my_workspace/WORKSPACE`

```
new_local_repository(
    name = "my_library",
    build_file = "tools/build_rules/my_library.BUILD",
    path = "/home/kjiwa/tmp/bazel/my_library"
)
```

The ```zip_archive``` rule works fine for ```hello:a``` but fails for ```@my_library//:my_library```:

```
$ bazel build hello:a 
......
INFO: Found 1 target...
INFO: From Unknown hello/a.zip:
  adding: hello/a.txt (deflated 24%)
Target //hello:a up-to-date:
  bazel-bin/hello/a.zip
INFO: Elapsed time: 2.076s, Critical Path: 0.51s

$ bazel build @my_library//:my_library 
ERROR: /home/kjiwa/.cache/bazel/_bazel_kjiwa/e9c0682d06e3f6e523d9dd9eece75843/external/my_library/BUILD:1: Extension file not found: 'tools/build_rules/zip_archive.bzl'.
ERROR: error loading package '@my_library//': Extension file not found: 'tools/build_rules/zip_archive.bzl'.
INFO: Elapsed time: 0.224s
```

**Comment by damienmg** [comment]
I think that's coming from a change lberki@ did. I remember something about path and remote repositories.

**Comment by kchodorow** [comment]
Yes, lberki made a change so that Skylark rules are repository-local (`load(x)` looks for x.bzl in the current repository).  @jhfield is working on a change that will allow specifying Skylark extensions by label, which will make loading from other repositories possible.

**Comment by lberki** [comment]
Yep, until we get labels in load() statements there isn't a good solution. If I fixed this so that this refers to the main repository, other things will break, so I think it's best to leave this untouched until John's changes land. But then this should be instantaneously fixed, so I'm assigning this bug to him.

**Comment by kjiwa** [comment]
What kind of effort is required to fix this?

**Comment by damienmg** [comment]
For your side: to waiting for 0.2. Hopefully next week.

**Comment by kchodorow** [comment]
Closure rules have now been moved to https://github.com/bazelbuild/rule_closure, please open an issue there if this is still a problem.
