### ISSUE TITLE
Document the interaction of virtualenv with Python interpreter autodetection

### ISSUE THREAD

**Issue by ben-ng** [bazelbuild/bazel#4080]
### Description of the problem / feature request / question:

If the bazel server is started when a python virtualenv is activated, actions are run in that virtualenv until the server restarts. `bazel clean` does not clear this state.

### If possible, provide a minimal example to reproduce the problem:

1. Create a python virtualenv
2. Create a python script that `import`s a dependency in that virtualenv
3. Activate the virtualenv
4. Build & run the script with bazel. It should exit normally.
5. Deactivate the virtualenv. Build & run the script with bazel again. It passes, unexpectedly.
6. `bazel shutdown` (in practice this happens automatically, which is even more surprising)
7. Build & run the script with bazel. It now fails because the dependency couldn't be found.

It looks like it's because activating the virtualenv changes `PATH`, and the deactivation of the virtualenv doesn't propagate to the bazel server.

### Environment info
* Operating System:

CentOS Linux release 7.0.1406

* Bazel version (output of `bazel info release`):

release 0.7.0

**Comment by brandjon** [comment]
Correct me if I'm wrong, but this seems like a natural consequence of how virtualenv works by manipulating the shell env. I suppose we could have the Bazel CLI client check the current shell environment and compare it with the server's state...

I'd consider this a feature request but we can certainly document this behavior regardless.

**Comment by brandjon** [comment]
FWIW, this issue can be avoided by specifying a py_runtime to refer to an interpreter by a fixed absolute path instead of relying on a command lookup in `PATH`. This will be more mainstream when #7375 is implemented, though it sounds like the default toolchain (which will look up a runtime from `PATH`) will still be affected by this issue.
