### ISSUE TITLE
Build is completed without errors, but SO file is not generated

### ISSUE THREAD

**Issue by lucasharada** [bazelbuild/bazel#4081]
I found this [tutorial](https://blog.mindorks.com/android-tensorflow-machine-learning-example-ff0e9b2654cc) and am trying to follow it to test TensorFlow. This way, I managed to build using 
```
bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so \
   --crosstool_top=//external:android/crosstool \
   --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
   --cpu=armeabi-v7a
```
but it didn't generate any SO file in `bazel-bin/tensorflow/contrib/android/libtensorflow_inference.so`. Looking for a SO file in all generated folders, I found one in `bazel-out/arm-linux-androideabi-clang3.8-v7a-gnu-libstdcpp-opt/bin/tensorflow/contrib/android/libtensorflow_inference.so`.

Is the SO file I found the correct one or I need to rebuild?

IMPORTANT INFORMATION:
```
$ bazel version
Build label: 0.7.0-homebrew
Build target: bazel-out/darwin_x86_64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sun Nov 12 03:11:20 2017 (1510456280)
Build timestamp: 1510456280
Build timestamp as int: 1510456280
$ 
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by aj-michael** [comment]
Yea, those should both be symlinks to the same file. The bazel-bin symlink probably just failed to get created. If you rebuild, it should be cached and will try again to create the symlink.
