### ISSUE TITLE
Expose Skylint in @bazel_tools

### ISSUE THREAD

**Issue by greggdonovan** [bazelbuild/bazel#4086]
### Description of the problem / feature request / question:

We would like to run Skylint in CI without a source checkout of Bazel. Skylint's [README](https://github.com/bazelbuild/bazel/blob/master/site/docs/skylark/skylint.md#building-the-linter) does not provide a way to use it other than via a full source checkout of Bazel.

### If possible, provide a minimal example to reproduce the problem:

Skylint cannot be found in `$(bazel info execution_root)/external/bazel_tools/tools/`.

Skylint cannot be accessed in its current location:
```
$ cd rules_scala
$ bazel run '@bazel_tools//src/tools/skylark/java/com/google/devtools/skylark/skylint:Skylint' ./scala/scala.bzl
ERROR: no such package '@bazel_tools//src/tools/skylark/java/com/google/devtools/skylark/skylint': BUILD file not found on package path.
```

### Environment info
* Operating System:
OSX Sierra 10.12.6

* Bazel version (output of `bazel info release`):

release 0.7.0-homebrew

###  Have you found anything relevant by searching the web?

No. There is no [Skylint discussion on SO](https://stackoverflow.com/search?q=%5Bbazel%5D+skylint) or [`bazel-discuss`](https://groups.google.com/forum/#!searchin/bazel-discuss/skylint%7Csort:date).

#3895 mentions publishing Skylint separately. But, Skylint is built into Bazel so it seems easier to "publish" it via `@bazel_tools`.

**Comment by ittaiz** [comment]
Any update about this?

**Comment by philwo** [comment]
FYI @vladmos

**Comment by laurentlb** [comment]
We're working on a replacement of Skylint, so it's unlikely we work on this issue.

**Comment by laurentlb** [comment]
See Buildifier (https://github.com/bazelbuild/buildtools).
