### ISSUE TITLE
compile fail on redhat5

### ISSUE THREAD

**Issue by zjh-nudger** [bazelbuild/bazel#4087]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
ERROR: /root/files/bazel-0.5.0-dist/third_party/grpc/BUILD:55:1: C++ compilation of rule '//third_party/grpc:grpc_unsecure' failed: gcc failed: error executing command
  (cd /tmp/bazel_CiYG5779/out/execroot/bazel-0.5.0-dist && \
  exec env - \
    LD_LIBRARY_PATH=:/usr/local/bin/protoc/lib \
    PATH=/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/jdk1.8/bin:/usr/local/gcc4.8.4/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin \
    PWD=/proc/self/cwd \
  /usr/local/gcc4.8.4/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/local/gcc4.8.4/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/local-opt/bin/third_party/grpc/_objs/grpc_unsecure/third_party/grpc/src/core/iomgr/pollset_multipoller_with_epoll.d -iquote . -iquote bazel-out/local-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/local-opt/genfiles/external/bazel_tools -isystem third_party/grpc -isystem bazel-out/local-opt/genfiles/third_party/grpc -isystem third_party/grpc/include -isystem bazel-out/local-opt/genfiles/third_party/grpc/include -isystem third_party/zlib -isystem bazel-out/local-opt/genfiles/third_party/zlib -isystem external/bazel_tools/tools/cpp/gcc3 '-std=gnu99' -Wimplicit-function-declaration -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c third_party/grpc/src/core/iomgr/pollset_multipoller_with_epoll.c -o bazel-out/local-opt/bin/third_party/grpc/_objs/grpc_unsecure/third_party/grpc/src/core/iomgr/pollset_multipoller_with_epoll.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
third_party/grpc/src/core/iomgr/pollset_multipoller_with_epoll.c: In function 'epoll_become_multipoller':
third_party/grpc/src/core/iomgr/pollset_multipoller_with_epoll.c:293:3: warning: implicit declaration of function 'epoll_create1' [-Wimplicit-function-declaration]
   h->epoll_fd = epoll_create1(EPOLL_CLOEXEC);
   ^
third_party/grpc/src/core/iomgr/pollset_multipoller_with_epoll.c:293:31: error: 'EPOLL_CLOEXEC' undeclared (first use in this function)
   h->epoll_fd = epoll_create1(EPOLL_CLOEXEC);
                               ^
third_party/grpc/src/core/iomgr/pollset_multipoller_with_epoll.c:293:31: note: each undeclared identifier is reported only once for each function it appears in
Target //src:bazel failed to build
INFO: Elapsed time: 39.923s, Critical Path: 0.64s

ERROR: Could not build Bazel

### If possible, provide a minimal example to reproduce the problem:
when I compile bazel from source on redhat5

### Environment info
* Operating System:
os:Linux redhat5 2.6.18-128.el5xen
gcc:4.8.4

* Bazel version (output of `bazel info release`):
0.5.0

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by katre** [comment]
Looks like some of the epoll headers are missing/old on these systems. I'll do a little more investigation, but beware that the end result may be "we can't support this configuration".

**Comment by katre** [comment]
Looks like epoll_create1 was added to the kernel in version 2.6.27 (see the "Versions" section of https://linux.die.net/man/2/epoll_create1).

You are running 2.6.18.

If you cannot upgrade your kernel to a version that supports gRPC, I'm afraid we cannot provide support to you in getting it to build.

**Comment by zjh-nudger** [comment]
Thank you very much. I update my kernel to 2.6.33. However the same error occured agin. I know from the page that "epoll_create1() was added to the kernel in version 2.6.27 and Library support is provided in glibc starting with version 2.9. That means that the function epoll_create1 can not be invoked on machine with lower glibc version(under 2.9). That is to say, I can not compile bazel on redhat5 with GLIBC version of 2.5?

**Comment by katre** [comment]
If your system does not support the minimum glibc and kernel versions, we cannot support it, I am sorry to say. If you are able to add shims that define the needed epoll_create1 API it might work, but we won't be able to help with any bugs that arise.
