### ISSUE TITLE
experimental ui could handle blocked actions better

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#4089]
Unlike the old UI, the experimental UI doesn't track whether a "running" action is actually executing or is just blocked waiting for resources. Since the experimental UI shows actions in descending order of "running" time, the UI may not indicate what's actually running if there are many older actions blocked on resource acquisition. (I often see C++ link actions piling up at the top of the UI because their high hardcoded resource requirements are hard to schedule locally.)

The lack of scheduling tracking of can cause confusion when blocking occurs while switching execution strategies. For example, if an action starts with the remote strategy but needs to fallback to local execution, the experimental ui will show the action as running remotely until it actually starts executing locally.

**Comment by aehlig** [comment]
This is indeed true that the UI should better distinguish between actually running and blocked actions, at the very least in the startegy part of the status line (which is easy to achieve), probably also counting/grouping differently, which is a bit more work. I'll try to find time to do that as well, but that might take a bit longer.
