### ISSUE TITLE
IllegalStateException when a bind conflicts with a maven_jar

### ISSUE THREAD

**Issue by ekuefler** [bazelbuild/bazel#409]
My WORKSPACE has a `bind` rule and a `maven_jar` rule with the same name (where "//:junit" is defined in a top-level build file to group junit with its transitive deps):

```python
bind(name = "junit", actual = "//:junit")
maven_jar(
  name = "junit",
  group_id = "junit",
  artifact_id = "junit",
  version = "4.12",
)
```

This leads to the following error:
```
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'WORKSPACE_FILE:[/Users/erik/github/Master]/[WORKSPACE]' (requested by nodes 'PACKAGE:external')
INFO: Elapsed time: 0.567s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'WORKSPACE_FILE:[/Users/erik/github/Master]/[WORKSPACE]' (requested by nodes 'PACKAGE:external')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:762)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$2.run(AbstractQueueVisitor.java:436)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Got a name conflict for maven_jar rule //external:junit, which can't happen: maven_jar rule 'junit' in package 'external' conflicts with existing bind rule
	at com.google.devtools.build.lib.packages.ExternalPackage$Builder.build(ExternalPackage.java:79)
	at com.google.devtools.build.lib.skyframe.WorkspaceFileFunction.compute(WorkspaceFileFunction.java:78)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:726)
	... 4 more
```

Aside from the ugly error, it would be really nice if this were allowed. In theory there shouldn't be a conflict since they're referenced in different ways (`@junit//jar` vs. `//external:junit`). Not allowing this will make it difficult to work with build rules shipped with Bazel - for example, the groovy rules require `@junit` to be defined, which prevents them being used in any repository that defines a bind rule for junit.

Other options include ensuring rules like groovy.bzl use uniquish names such as `@junit-groovy`, but this leads to annoying artifact duplication. A better solution might be for groovy.bzl to rely on `//external` targets, which would give users some flexibility in how they're bound. I'm happy to make these changes to the groovy rules.

**Comment by kchodorow** [comment]
We should certainly get rid of the ugly error.  That they aren't duplicate symbols is an interesting idea, I'm not sure whether that would be confusing or convenient.

> Other options include ensuring rules like groovy.bzl use uniquish names such as @junit-groovy, but this leads to annoying artifact duplication. A better solution might be for groovy.bzl to rely on //external targets, which would give users some flexibility in how they're bound. I'm happy to make these changes to the groovy rules.

groovy.bzl should rely on //external targets for exactly the reasons you mention.  We'd be happy to accept patches for that.

**Comment by ekuefler** [comment]
I sent https://bazel-review.googlesource.com/#/c/1940/ to do the groovy rules.

With my current approach to workspaces I think it would be convenient if I could re-use names between artifacts and bindings, but I'm not certain my current approach is the best one, and I keep making tweaks to how I do it. It might be useful for the Bazel team to provide more documentation/guidance around best practices here. My current approach has the following properties:

  * Every external dependency is defined via a `bind` rule in WORKSPACE. Normal code only ever references these bindings via the `external` package, it never refers directly to `@` targets.
  * External artifacts (`maven_jar`, `http_repository`, etc.) are all named like `mydep-raw`. In the simple case where the artifact has no transitive deps, it's bound as `bind(name = "mydep", actual = "@mydep-raw//jar")` or similar.
  * For artifacts with transitive dependencies, I have a top-level BUILD file that defines `java_libraries` containing only `exports` and `runtime_deps`. These are the only libraries allowed to refer to to `@` raw targets, which go in either `exports` or `runtime_deps` depending on whether the artifact defines the library's API or it's a transitive dependency.

This is working okay but there are still a few things I don't like about it:

  * `-raw` suffix required on all the artifacts is annoying and feels unnecessary (the part this bug is about).
  * Have to split the definition of a single library across three places (the binding in WORKSPACE, artifacts in WORKSPACE, and then the dependency declarations in a BUILD). It feels like I should be able to configure the transitive deps right in WORKSPACE.
  * Transitive dep warnings instruct developers to add the raw `@` targets to their BUILD files, which have to be mapped back to external bindings manually.
  * The `java_libraries` used to define the deps mean I wind up with a bunch of empty jars in the top level of bazel-bin/

I kind of drifted from the scope of this bug there, but hopefully it's useful for understanding how I'm currently interacting with bindings and external artifacts.

**Comment by ekuefler** [comment]
> I was thinking that it would be good to add deps (and runtime_deps) fields to the maven_jar rule. That might alleviate some of this pain.

+1, that would be excellent. I'd think `http_jar` would need it also.

> Not sure if it'd help, but you don't have to bind all of the maven_jars, if you don't want to. It makes your code a bit less portable (users might not be able to import it as an external repository), but if it's not an open source library, you should be okay.

For the time being I want to avoid the inconsistency of using `//external` for targets with transitive deps and `@` for targets without them. But if the artifact rules supported dependencies this would become a much less compelling argument.

**Comment by kchodorow** [comment]
Created #438 to track the maven_jar change.
