### ISSUE TITLE
Expose tools from toolchain in CROSSTOOL

### ISSUE THREAD

**Issue by vrobertbaruch** [bazelbuild/bazel#4098]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

https://docs.bazel.build/versions/master/be/make-variables.html shows that these are exposed as Make variables:

CC
STRIP
AR
NM
OBJCOPY

However, objdump gives useful information that nm does not, so I wanted to use objdump. However, bazel does not expose OBJDUMP.

### If possible, provide a minimal example to reproduce the problem:

https://github.com/bazelbuild/bazel/wiki/Building-with-a-custom-toolchain

And then write a definition such as:

elf_rule = ":%s.out" % (name,)
genrule(
        name = name + "_map",
        srcs = [elf_rule],
        outs = [name + ".map"],
        cmd = "$(OBJDUMP) -C --all-headers $< > $@")

### Environment info
* Operating System:
Linux 4.4.0-96-generic #119~14.04.1-Ubuntu SMP Wed Sep 13 08:40:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* Bazel version (output of `bazel info release`):
release 0.7.0

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

[Discussion on getting a map file during the compilation step](https://groups.google.com/forum/#!topic/bazel-discuss/A00d7Ui1f8s)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by indrgun** [comment]
@vrobertbaruch

I also would like to know how to get READELF if it can be exposed as MAKE variable.
I am interested in the workaround.   Do you know how to get CROSSTOOL toolchain's tool_path information from skylark's ctx inside a rule?

**Comment by hlopko** [comment]
Objdump path is exposed Starlark in CcToolchainInfo: https://docs.bazel.build/versions/master/skylark/lib/CcToolchainInfo.html#objdump_executable

So you can write a custom rule (https://docs.bazel.build/versions/master/integrating-with-rules-cc.html) that uses it.

@indrgun custom make variables can be defined in custom C++ toolchains by passing make_variables to https://docs.bazel.build/versions/master/skylark/lib/cc_common.html#create_cc_toolchain_config_info.
