### ISSUE TITLE
Extra warnings of "The lower priority option does not override the previous value".

### ISSUE THREAD

**Issue by wjywbs** [bazelbuild/bazel#4099]
### Description of the problem / feature request / question:

Should bazel disable this kind of warnings? If there is "build -c dbg" in bazel.rc and run "bazel build -c opt", it will report this warning. Older bazel versions before 0.6 do not have this issue.

WARNING: The lower priority option '-c dbg' does not override the previous value '-c opt'.

### Environment info
* Operating System: linux
* Bazel version (output of `bazel info release`): 0.7.0

###  Have you found anything relevant by searching the web?
See similar warnings in building tensorflow: #3948

WARNING: The lower priority option '-c opt' does not override the previous value '-c opt'.

**Comment by cushon** [comment]
I think this was fixed in 2553875c285dcca454ee830182d238296ce70aa2.

**Comment by wjywbs** [comment]
I will reopen if this warning persists in the next bazel release, thanks.

**Comment by cvcal** [comment]
Thanks for identifying the fix, @cushon ! Yes, 0.8 should include this change, apologies for the log spam!
