### ISSUE TITLE
load('ing a file that doesn't exist in WORKSPACE should tell you what file it errored in

### ISSUE THREAD

**Issue by achew22** [bazelbuild/bazel#4100]
### Description of the problem / feature request / question:

If you attempt to `load` a `.bzl` file in the `WORKSPACE` that doesn't exist you get the following error:

`ERROR: error loading package '': Extension file not found. Unable to load file '//path/to:import.bzl': file doesn't exist or isn't a file`

Since this is an error new users are likely to experience it might be worth prioritizing since it may drive people away before they experience the awesome.

### If possible, provide a minimal example to reproduce the problem:

WORKSPACE:

```
load("//path/to:import.bzl", "doesnt_exit")
```

### Environment info
* Operating System: Linux
* Bazel version (output of `bazel info release`): release 0.8.0rc2

**Comment by ayad81** [comment]
![screenshot_20170902-011700](https://user-images.githubusercontent.com/33680914/32873466-4e7c35fe-ca9d-11e7-9b79-0e01acd2f46f.png)
![screenshot_20170902-011733](https://user-images.githubusercontent.com/33680914/32873468-4f0967ee-ca9d-11e7-9d12-c88f33416e78.png)
![screenshot_20170902-011758](https://user-images.githubusercontent.com/33680914/32873469-4f9bc648-ca9d-11e7-9263-3541603b9a37.png)
![screenshot_20170902-011809](https://user-images.githubusercontent.com/33680914/32873470-5027fc26-ca9d-11e7-820b-4a94494714f5.png)
![screenshot_20170902-011902](https://user-images.githubusercontent.com/33680914/32873472-50bd767a-ca9d-11e7-9b99-33a168cbd293.png)
![screenshot_20170902-012000](https://user-images.githubusercontent.com/33680914/32873474-51696b74-ca9d-11e7-8ad4-53e9917b0dad.png)
![screenshot_20170902-012022](https://user-images.githubusercontent.com/33680914/32873475-5248d624-ca9d-11e7-81e7-87c4459d345f.png)
![screenshot_20170912-040130](https://user-images.githubusercontent.com/33680914/32873477-52decb20-ca9d-11e7-8f4e-17a8c55f1b92.png)
![screenshot_20170912-040337](https://user-images.githubusercontent.com/33680914/32873478-536ce16c-ca9d-11e7-8a88-5e60e32a88b3.png)
![screenshot_20170912-040503](https://user-images.githubusercontent.com/33680914/32873479-5449dbda-ca9d-11e7-8dbf-4ebafe5d2e8e.png)

**Comment by laurentlb** [comment]
I think I fixed this a few months ago.
