### ISSUE TITLE
repository_rule local=True not executed every time on mac

### ISSUE THREAD

**Issue by ahippler** [bazelbuild/bazel#4101]
### Description of the problem / feature request / question:

repository_rule with local=True is only executed on changes, not every time.
I use repository_ctx.execute() to validate local cached artefacts.
This should be done every time bazel starts to build.

### Environment info
* Operating System:
macOS 10.12.6

* Bazel version (output of `bazel info release`):
0.7.0-homebrew

**Comment by dslomov** [comment]
This is working as intended: https://docs.bazel.build/versions/master/skylark/repository_rules.html#when-is-the-implementation-function-executed. It will be *very* costly to rerun repository rules on every build.

If you share more details on what you are trying to do, we can try to suggest a solution.

**Comment by daicoden** [comment]
Found this issue while looking for solutions.

Came up with a solution where I create a timestamp file on every bazel execution, but I think bazel should have a flag like unmanaged_resource=True which works in conjunction with local to indicate the rule has a non hermetic dependency which needs to be evaluated on every execution.

https://stackoverflow.com/questions/61955644/is-there-a-way-to-execute-a-repository-rule-with-local-true-on-every-bazel-invoc/61965711#61965711
