### ISSUE TITLE
Enable aapt2 by default

### ISSUE THREAD

**Issue by aj-michael** [bazelbuild/bazel#4103]
It works internally and is now the default in gradle:

https://developer.android.com/studio/build/gradle-plugin-3-0-0.html

**Comment by jin** [comment]
aapt2 will be fully functional in the next release (0.17.0), and we can schedule to enable it by default for 0.18.0.

**Comment by jin** [comment]
To take note: mobile-install v1 doesn't yet work with aapt2 https://github.com/bazelbuild/bazel/issues/5799
