### ISSUE TITLE
some broken doc pages

### ISSUE THREAD

**Issue by cauthu** [bazelbuild/bazel#4104]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

https://docs.bazel.build/versions/master/skylark/ is showing:
```
404 - Page not found
$ bazel build :what-you-were-looking-for
...............
ERROR: no such page ':what-you-were-looking-for': BUILD file not found on package path.
INFO: Elapsed time: 0.567s
```

child pages, e.g., https://docs.bazel.build/versions/master/skylark/concepts.html, work fine.

UPDATE: others that are failing similarly:
https://docs.bazel.build/versions/master/tutorial/workspace.html
https://docs.bazel.build/versions/master/bazel-user-manual.html

**Comment by dungeonmaster18** [comment]
hey @cauthu from where exactly you are trying to access these links. It's happening because someone has changed the name of those files and didn't corrected that. So if you can tell me which pages these links belong then I can fix these.

**Comment by cauthu** [comment]
ah ok

* https://docs.bazel.build/versions/master/skylark/ i got to this from google results for "bazel skylark," the first linked result "Extensions - Bazel"

* https://docs.bazel.build/versions/master/tutorial/workspace.html from https://docs.bazel.build/versions/master/bazel-overview.html#how-do-i-use-bazel, the second item "2. Set up a project workspace"

* https://docs.bazel.build/versions/master/bazel-user-manual.html sorry i don't remember from which page i got this link.

**Comment by laurentlb** [comment]
I think this can be closed now
