### ISSUE TITLE
Android support library now requires maven.google.com

### ISSUE THREAD

**Issue by gregghz** [bazelbuild/bazel#4106]
### Description of the problem / feature request / question:

In the [Android Rules documentation for support libraries](https://docs.bazel.build/versions/master/be/android.html#android_sdk_repository_support_libraries) it says to use `@androidsdk//com.android.support:appcompat-v7-25.0.0` in `deps`. This approach uses the local maven repo provided by the android sdk. However as of (I think) 26.0.0 of the support libraries these artifacts are no longer managed by the sdk and are instead published to https://maven.google.com. The [Android documentation for using support libraries](https://developer.android.com/topic/libraries/support-library/setup.html) also reflects this change.

Ideally androidsdk would be changed to (perhaps as a fallback?) look for artifacts at maven.google.com. At the very least, documentation should be updated to show how to use support libraries with versions 26+ (I still haven't fully figured that out, but I guess that's a different issue).

### If possible, provide a minimal example to reproduce the problem:

```
android_binary(
    name = "app",
    custom_package = "com.gregghz.android.sample",
    srcs = glob(["src/main/java/**/*.java"]),
    resource_files = glob(["src/main/res/**"]),
    manifest = "src/main/AndroidManifest.xml",
    deps = [
        "@androidsdk//com.android.support:appcompat-v7-26.1.0",
    ]
)
```

This fails with:

    ERROR: /home/gregg/workspace/android-scala-bazel/app/BUILD:10:1: no such target '@androidsdk//com.android.support:appcompat-v7-26.1.0': target 'appcompat-v7-26.1.0' not declared in package 'com.android.support' (did you mean 'appcompat-v7-22.1.0'?) defined by /home/gregg/.cache/bazel/_bazel_gregg/29f69d95c66f549f861c961ce50dbe9f/external/androidsdk/com.android.support/BUILD and referenced by '//app:app'

### Environment info
* Operating System:
Ubuntu 16.04

* Bazel version (output of `bazel info release`):

```
$ bazel info releaserelease 0.7.0
```

###  Have you found anything relevant by searching the web?

All of what I found uses the `@androiddsk//` deps.

**Comment by gregghz** [comment]
I should also mention that I have updated/installed the support libraries and this all does work with my sdk as-is with gradle and sbt.

**Comment by jin** [comment]
Hey @gregghz, this is a known issue and we’re working on it. For now, @aj-michael has created a set of WORKSPACE rules for Google Maven here: https://github.com/aj-michael/gmaven_rules

**Comment by jin** [comment]
cc @aj-michael @dkelmer @ahumesky

**Comment by gregghz** [comment]
@jin Thanks for the quick reply. @aj-michael's rules works great. I really appreciate this :+1:

**Comment by marup** [comment]
I'm running 0.9.0 and still using aj-michael's workaround. I see this is targeted to 0.9. Can we expect support for this to be part of bazel soon?

**Comment by aj-michael** [comment]
@marup, I'm not sure if we will ever see this as part of bazel. The current trend in other languages is to offload transitive external dependency resolution into other tools. I think the right path forward will be adding support for .aar files into something like https://github.com/johnynek/bazel-deps, which generates a WORKSPACE file for you.

**Comment by marup** [comment]
It's too bad Google's Android team doesn't support Google's open source build tool, but for now I'll be patient for Bazel's next release. Thank you for creating the gmaven-rules.

**Comment by ahumesky** [comment]
We're moving off milestones (see https://blog.bazel.build/2017/09/27/release-cadence.html) so I'll remove 0.9 here.

**Comment by jin** [comment]
These are now supported with https://github.com/bazelbuild/gmaven_rules and you can find regular releases here: https://github.com/bazelbuild/gmaven_rules/releases
