### ISSUE TITLE
Put source code into TEST_SRCDIR

### ISSUE THREAD

**Issue by TeBoring** [bazelbuild/bazel#411]
My test depends on my source code as data.
How can I put my source code into TEST_SRCDIR so that my test can find them when running?

**Comment by kchodorow** [comment]
You should be able to add them in the `data` attribute.   For example, https://github.com/bazelbuild/bazel/blob/master/src/test/shell/bazel/BUILD#L36-L60 is used by most of the tests in that build file. https://github.com/bazelbuild/bazel/blob/master/src/test/shell/bazel/testenv.sh is probably the simplest example of those files being referenced.
