### ISSUE TITLE
BEP: ActionExecuted event never delivered

### ISSUE THREAD

**Issue by pcj** [bazelbuild/bazel#4112]
In my experiments with the BEP via `--build_event_binary_file` (and friends), I've never seen an `ActionExecuted` event come through. Is that expected?  How to trigger one?  Seems like that's a pretty core one in order to visualize the execution graph.

Also, what sort of events should one expect during the loading phase?  Particularly regarding external dependency fetching, repository_ctx events?

**Comment by aehlig** [comment]
> In my experiments with the BEP via `--build_event_binary_file` (and friends), I've never
> seen an `ActionExecuted` event come through. Is that expected?

Yes.

Quoting the proto specification.

```
// Payload of the event indicating the completion of an action. The main purpose
// of posting those events is to provide details on the root cause for a target
// failing; however, consumers of the build-event protocol must not assume
// that only failed actions are posted.
```

>  How to trigger one?

Just create an action that fails.

> Seems like that's a pretty core one in order to visualize the execution graph.

It was a deliberate decission to not report on every executed actions, only "important"
Ones; those are all failed actions (for sure), as well as currently (that might change)
also actions generated by top-level aspects (as the output of those are needed for
IDE use). Showing all actions would generate a far too large sequence of build events,
even for moderately-sized builds.

> Also, what sort of events should one expect during the loading phase? [...]

Currently only the PatternExpanded event. We might add more events regarding
access to externel repositories, once things there stabilize more. But don't
hold your breath.

Regards,
  Klaus


-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by shahms** [comment]
top-level "extra actions" are also present
