### ISSUE TITLE
Provide an option to write skylint warnings in a structured format.

### ISSUE THREAD

**Issue by ttsugriy** [bazelbuild/bazel#4119]
When using Skylint with any automation, it's very useful to be able to parse every message for either visualization or storage purposes. In particular, we are using Skylint with arcanist tool to run all linters for our project and in order for it to be useful, we need to parse all message parts.

### Description of the feature request:

Unfortunately, messages that describe missing `Args` or other parts of a docstring span multiple lines:
```
    /some_path/foo.bzl:8:3-11:5:
    incomplete docstring: the function parameters are not documented (no
    'Args:' section found)
    The parameter documentation should look like this:

    Args:
      name: ...
      srcs: ...
      deps: ...
      visibility: ...

     [inconsistent-docstring]
```
and even though it's possible to match an entire message with a regular expression like:
```
    $re = '/
      ^
        (?<path>[^:]+):                         # java_rules.bzl:
        (?<s_line>[0-9]+):(?<s_char>[0-9]+)-    # 1:1-
        (?<e_line>[0-9]+):(?<e_char>[0-9]+):    # 2:1:
        \s*(?<msg>.*)\s*\[(?<category>[\w-]+)\] # file has no module docstring [missing-docstring]
      $
    /mxs';
```
it gets much trickier when multiple messages are written. It's still possible, but very fragile.

Instead I would like to have an option (`--json` flag) to produce a structured format like json. So the message above would be written as:
```
[{"path": "/some_path/foo.bzl", "range": {"start": {"line": 8", "column": 3}, "end": {"line": 11, "column": 5}}, "message": "...", "category": "inconsistent-docstring"}
```

This would greatly simplify automation around Skylint.

### Simple repro:

To reproduce you can run linter on something like:
```
"""Some module."""

def some_test(
    name,
    srcs,
    deps = [],
    visibility = []):
  """Define a new caliper microbenchmark test."""
  pass
```

**Comment by ttsugriy** [comment]
for now I'm using
```
    $re = '/
      ^
        (?<path>[^:]+):                       # java_rules.bzl:
        (?<s_line>[0-9]+):(?<s_char>[0-9]+)-  # 1:1-
        (?<e_line>[0-9]+):(?<e_char>[0-9]+):  # 2:1:
        \s*(?<msg>[\s\S]*?)\s*                # file has no module docstring
        \[(?<category>[\w-]+)\]               # [missing-docstring]
      $
    /mx';
```
and iterate over matches like this:
```
$matches = array();
preg_match_all($re, $stdout, $matches, PREG_SET_ORDER);
foreach ($matches as $match) {
    ...
}
```
so I have a temporary work-around but having a structured format would certainly be much more convenient :)

**Comment by laurentlb** [comment]
We plan to retire Skylint in favor of Buildifier.

Adding json output to Buildifier would be a good feature!
