### ISSUE TITLE
Test methods that contain non-regex safe characters should be escaped

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/bazel#4120]
(I've encountered this when implementing support for bazelbuild/intellij#155)

If a test method contains one of the symbols `.^$*+?()[{\|`, if passed verbatim as a JUnit test, will fail regex validation (e.g. a test named "2+2 = 4", which is a valid method name in scala.)

Given a filter: `"--test-filter=MyTest#calculator should::prove 2+2 = 4"`, `RegExTestCaseFilter` will fail to match the junit test description with the filter.

As a workaround, the string could be escaped at the source (e.g. rules_scala or the IntelliJ plugin), by escaping the string using `Pattern.quote`, which surrounds the string with `\Q...\E`, thus making the regex engine treat it as an escaped regex string.

However, this should probably be done inside the `RegExTestCaseFilter` handling itself, so no special formatting required when passing the filter.

**Comment by ittaiz** [comment]
Hi,
@laszlocsomor I'm guessing you're the sheriff this week (hope I'm not wrong).
WDYT can we do with this issue?

**Comment by laszlocsomor** [comment]
Hi Ittai,

@philwo is the sheriff week.

@hmemcpy : could you please provide repro instructions? I'm not familiar with the Scala rules' syntax or with Scala in general, so figuring out how to write a test would take me longer than it would for you. Thanks!

**Comment by hmemcpy** [comment]
@laszlocsomor of course! Thanks for looking into this.

It's unrelated to Scala, directly, this is more of a JUnit "limitation".
In Scala (in particular, the specs2 framework), you can create test names using arbitrary strings, e.g. `"this is a valid test name (in specs2)"`.
If I pass this verbatim to the test filter, it will fail early in Bazel, because it (probably) considers the `(in specs2)` bit to be a valid regex. So when running:
```
bazel test //:my_test "--test_filter=com.example.MyTest#this is a valid test name (in specs2)$"
```
It will fail with the following message:
```
1) initializationError(org.junit.runner.manipulation.Filter)
java.lang.Exception: No tests found matching RegEx[com.example.MyTest#this is a valid test name (in specs2)$]
	at com.google.testing.junit.runner.junit4.JUnit4Runner.createErrorReportingRequestForFilterError(JUnit4Runner.java:241)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.applyFilters(JUnit4Runner.java:209)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:95)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:144)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:82)
```

If I escape the test filter string like this:
```
\Qcom.example.MyTest#this is a valid test name (in specs2)$\E
```
Then it passes, but this requires additional handling (unescaping) inside rules_scala.

So I was hoping that bazel could escape the regex string itself, so no additional escaping need to be done externally.

**Comment by laszlocsomor** [comment]
Thanks!

Bazel and the JUnit test runner are separate entities. I think Bazel itself is doing the right thing, because it forwards the test filter to the test runner (via an envvar) and it's up to the test runner how it interprets the filter:

```
  $ cat BUILD
sh_test(
    name = 'foo_test',
    srcs = ['foo_test.sh'],
)

  $ cat foo_test.sh 
#!/bin/bash
echo "hello from $(basename $0)"
env | sort

  $ bazel test //:foo_test "--test_filter=com.example.MyTest#this is a valid test name (in specs2)$" >&/dev/null && cat bazel-testlogs/foo_test/test.log | grep "hello\|example"
hello from foo_test
TESTBRIDGE_TEST_ONLY=com.example.MyTest#this is a valid test name (in specs2)$
```

@iirina : Since you work on Java rules (AFAIK), I'm asking you. Do you have any thoughts about what Bazel or the JUnit test runner should do here?

**Comment by ittaiz** [comment]
Thanks László for your help, sorry for the misidentification

**Comment by iirina** [comment]
It would be nice to do this in the test runner, but I don't see how it can know what to escape from the filter. If it escapes the whole filter, than it won't work for regex characters.

@hmemcpy Why would you need to unescape in rules_scala?

**Comment by laszlocsomor** [comment]
@ittaiz : No worries, I don't think we publish anywhere who's sheriff on a given week. Thanks for trusting it was me! ;)

**Comment by hmemcpy** [comment]
@iirina for specs2, I will have to extract the test name (just the name), to pass it to the specs2 runner. For this I need to split the final matched `Description` by the `::` string, in order to get the test name part.

However, now that I think about it, I can probably do this without unescaping, by operating on the `Description` object directly... I'll look into this!

However, the question remains: whose responsibility it is to escape the test filter string?

**Comment by hmemcpy** [comment]
After discussing this further with @ittaiz, we decided the best course of action would be to escape it in the plugin, and handle it in rules_scala.
The plugin will always Pattern.quote the test name filters.

For now, this should probably be a Note in the rules_scala/specs2 documentation.

Thanks! Closing.

**Comment by ittaiz** [comment]
Mainly since the other alternative we had in mind meant disabling the usage
of regex from the command line.
Maybe there is a place to add another parameter that says if the test
filter is a regex or not
