### ISSUE TITLE
Better docs for authors of new rules

### ISSUE THREAD

**Issue by ghemawat** [bazelbuild/bazel#4129]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I find myself doing a lot of searches and cut and paste to figure out how to add new rules.  I suspect it would be helpful to a lot of people if there was some kind of a tutorial with examples for how to add new rules. 

My suggestion would be sketch out everything needed for somebody to add Yacc or Bison support since it should be fairly straightforward, yet a realistic example.

The reference manual is useful for details, but doesn't provide much guidance for how to put things together.

Similarly, the "Packaging Rules" section seems like overkill for somebody first experience with Skylark and new rules. 

### Environment info

Applies to all environments.

**Comment by meteorcloudy** [comment]
@laurentlb Any ideas on this?

**Comment by laurentlb** [comment]
I definitely agree that's a major issue. Please continue to give feedback, and point at specific issues, we'll address them.

Also, when you need help, please ask on stackoverflow. Over time, there will be a collection of examples and tips.

**Comment by c-parsons** [comment]
@laurentlb  would you like to keep this open? Otherwise I recommend we close this and track more-specific issues separately (also, this was filed several years ago, and I *do* think we've improved our guides since 2017)

Closing, but feel free to reopen and assign to me if you have better ideas with what to do with this issue
