### ISSUE TITLE
ChaiScript is real

### ISSUE THREAD

**Issue by jonathandturner** [bazelbuild/bazel#4133]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

In your page at https://docs.bazel.build/versions/master/skylark/deploying.html, you say "suppose we are writing new Skylark rules for the (make-believe) chaiscript language"

ChaiScript is a real language that's been around since 2009.  May want to use a different example 😅 

More info:

http://chaiscript.com/

https://github.com/chaiscript/chaiscript

cc @lefticus who runs ChaiScript these days

**Comment by jin** [comment]
Already in a PR: https://github.com/bazelbuild/bazel/pull/4125
