### ISSUE TITLE
Could I compile bazel from source on redhat5 successfully?

### ISSUE THREAD

**Issue by zjh-nudger** [bazelbuild/bazel#4139]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
Could I compile bazel on redhat5 successfully? 
I have tried some method to compile bazel from source on redhat5(We deploy our applications on redhat5). However, I failed.
Many utilities , such as htole16, sandbox, needed by compiling, are not supported on redhat5.
Consequently, I want to know if I can compile successfully on redhat5.

I need some help. Thank you very much!

### Environment info
* Operating System:
1.cat /etc/redhat-release:
Red Hat Enterprise Linux Server release 5.8 (Tikanga)
2.GLIBC version: 2.5
3.uname -a:
Linux localhost.localdomain 2.6.33 #1 SMP Fri Nov 17 03:22:34 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
4.GCC version:
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)

* Bazel version (output of `bazel info release`):

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by meteorcloudy** [comment]
What exactly problems did you encounter?
@damienmg Do you know any known blocker on Rethat5?

**Comment by damienmg** [comment]
Redhat 5 is pretty old, so might be useful to follow https://stackoverflow.com/questions/42982735/how-to-compile-bazel-on-centos-6-x

**Comment by zjh-nudger** [comment]
@meteorcloudy https://groups.google.com/forum/#!topic/bazel-discuss/2B-W_jRehhc. I record the problem I encountered on the page. In brief, MS_REC, EPOLL_CLOEXEC, le16toh, UTIME_NOW,etc.. are not found.

**Comment by zjh-nudger** [comment]
@damienmg In other way, I can not compile on redhat5? As I know, many company deploy their applications on redhat5. So, would you support for redhat5?

**Comment by damienmg** [comment]
As said in the CentOS thread, your c++ toolchain is too old and you get around it by installing a newer one. I have no access to rhel 5 so I cannot say how to do it.

We don't have plan to support older c++ toolchain.

**Comment by zjh-nudger** [comment]
Got it. Thank you very much any way.

**Comment by jin** [comment]
Closing as
