### ISSUE TITLE
Unable to find directories in external repositories in sandboxed execution on Linux

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel#414]
For example, when building one of the Rust examples:

```
❯❯❯ bazel build //examples/rust/hello_world
INFO: Found 1 target...
ERROR: Sandboxed execution failed: //examples/rust/hello_lib:hello_lib..
INFO: From Compiling Rust library hello_lib:
/bin/bash: line 1: external/rust-linux-x86_64/rust-1.2.0-x86_64-unknown-linux-gnu/rustc/bin/rustc: No such file or directory
...snipped
```

The error goes away with `--spawn_strategy=standalone --genrule_strategy=standalone`.

**Comment by philwo** [comment]
This is caused by the Rust Skylark rules not declaring the inputs to the compile action correctly (they're missing the compiler and its deps) and the sandboxed execution just uncovered this bug.

I will send a patch tomorrow that fixes this issue and another small one I just found.

**Comment by davidzchen** [comment]
Understood. Thanks!
