### ISSUE TITLE
Bazel CI: bazel-tests-remote broken

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#4142]
https://ci.bazel.io/view/Dashboard/job/bazel-tests-remote/151/console
Many tests are failing with 
`ERROR: Caught I/O exception: java.io.FileNotFoundException: /home/ci/.cache/bazel/_bazel_ci/8611dd7c3b25e5904a345d6a0e712ca1/execroot/io_bazel/bazel-out/linux_gnu_x86-fastbuild/testlogs/src/test/shell/integration/outputs_test/test.log (No such file or directory).`
```
[node=ubuntu_16.04-x86_64] //src/test/shell/integration:bazel_command_log_test                      FAILED in 1 out of 4 in 733.9s
[node=ubuntu_16.04-x86_64]   Stats over 4 runs: max = 733.9s, min = 57.0s, avg = 268.6s, dev = 276.3s
[node=ubuntu_16.04-x86_64] //src/test/shell/integration:experimental_ui_test                        FAILED in 1 out of 11 in 903.5s
[node=ubuntu_16.04-x86_64]   Stats over 11 runs: max = 903.5s, min = 62.0s, avg = 229.1s, dev = 239.4s
[node=ubuntu_16.04-x86_64] //src/test/shell/integration:loading_phase_tests                         FAILED in 1 out of 4 in 859.8s
[node=ubuntu_16.04-x86_64]   Stats over 4 runs: max = 859.8s, min = 59.0s, avg = 435.4s, dev = 337.7s
[node=ubuntu_16.04-x86_64] //src/test/shell/integration:outputs_test                                FAILED in 790.4s
[node=ubuntu_16.04-x86_64] //src/test/shell/integration:run_test                                    FAILED in 1 out of 3 in 831.0s
[node=ubuntu_16.04-x86_64]   Stats over 3 runs: max = 831.0s, min = 192.1s, avg = 438.1s, dev = 280.8s
[node=ubuntu_16.04-x86_64] 
[node=ubuntu_16.04-x86_64] Executed 103 out of 104 tests: 99 tests pass and 5 fail locally.
```

**Comment by meteorcloudy** [comment]
@damienmg Have you seem this error before?
It failed at this change https://github.com/bazelbuild/bazel/commit/4d09a1de6a60c6f90cc88978151bcde83c8000d4, but I'm not sure it's related.

**Comment by ola-rozenfeld** [comment]
Hmm, I thought I fixed this when I fixed https://github.com/bazelbuild/bazel/issues/3834, but I guess I didn't. These are duplicates.

**Comment by ola-rozenfeld** [comment]
Sorry, I just noticed this run was using Bazel 0.7.0, which does not include my fix. So this is, unfortunately, expected. Please use a later version of Bazel.

**Comment by meteorcloudy** [comment]
I see, it means it will be fixed with the next Bazel release.
Thanks!

**Comment by philwo** [comment]
@meteorcloudy Can we close this now?

**Comment by meteorcloudy** [comment]
Yes!
