### ISSUE TITLE
NDEBUG not defined in default Windows CROSSTOOL with -c opt

### ISSUE THREAD

**Issue by sgreenstein** [bazelbuild/bazel#4144]
### Description of the problem / feature request / question:

- Build on Windows using the default CROSSTOOL with `--compilation_mode=opt`
- Expected: `NDEBUG` is defined (see #139)
- Actual: It is not defined.

### If possible, provide a minimal example to reproduce the problem:
Empty WORKSPACE file

BUILD
```
cc_library(
    name = "lib",
    srcs = ["lib.cc"],
)
```

lib.cc
```
#ifdef NDEBUG
symbol defined
#else
symbol undefined
#endif
```

```
C:\Users\sgreens\test>bazel build :lib -c opt
INFO: Found 1 target...
ERROR: C:/users/sgreens/test/BUILD:11:1: C++ compilation of rule '//:lib' failed (Exit 2).
lib.cc(6): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
lib.cc(6): error C2146: syntax error: missing ';' before identifier 'undefined'
```

### Environment info
* Operating System: Windows 10

* Bazel version (output of `bazel info release`): 0.6.1

###  Have you found anything relevant by searching the web?
#139

**Comment by laszlocsomor** [comment]
Confirmed that this is indeed broken on Windows with Bazel 0.7.0, but working on macOS.

**Comment by meteorcloudy** [comment]
Right, I'll add it to CROSSTOOL definition

**Comment by mhlopko** [comment]
Thanks Yun!
