### ISSUE TITLE
stubify_manifest.py breakage when running mobile-install

### ISSUE THREAD

**Issue by XperielIndigo** [bazelbuild/bazel#415]
Hi,

I just updated to https://github.com/bazelbuild/bazel/commit/8a61174af91802262b682e51eae10dabf2fe491f and when I run `mobile-install` on an `android_binary` now I get the following error.

```
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_indigo/8965add7011578a5d33385a234e6a985/Master/bazel-out/local_darwin-fastbuild/bin/external/android_tools/tools/android/stubify_manifest.runfiles/external/android_tools/tools/android/stubify_manifest.py", line 29, in <module>
    from third_party.py import gflags
ImportError: No module named third_party.py
```

**Comment by XperielIndigo** [comment]
Seems to be caused by https://github.com/bazelbuild/bazel/commit/4ac3c22a43cd1a6d5dccb84f7a43776c75ba6869. Before that commit there is still the issue in https://github.com/bazelbuild/bazel/issues/413

**Comment by ahumesky** [comment]
https://github.com/bazelbuild/bazel/commit/4ac3c22a43cd1a6d5dccb84f7a43776c75ba6869 was probably only masking the issue, since it never got to invoking stubify_manifest

Do you have the right base workspace specified in your .bazelrc? Can you confirm that <workspace>/bazel-<workspace>/third_party/py/gflags exists?

**Comment by XperielIndigo** [comment]
Base is correct, gflags is there.

**Comment by ahumesky** [comment]
Sorry, github ate part of my comment, should have been "\<workspace>/bazel-\<workspace>/third_party/py/gflags"

**Comment by XperielIndigo** [comment]
No problem, that's where I checked.

**Comment by ahumesky** [comment]
Can you try running compile.sh again so it rebuilds the base workspace?

**Comment by XperielIndigo** [comment]
Tried that. I have git pulled, removed the output directory and then done a compile.sh. Still fails.

**Comment by ahumesky** [comment]
Hmm yes I can reproduce the issue now, let me take a look.

**Comment by ahumesky** [comment]
Do you also see

ERROR: Sandboxed execution failed: @android_tools//src/tools/android/java/com/google/devtools/build/android/incrementaldeployment:stub_application..
?

**Comment by XperielIndigo** [comment]
Nope, this is my full output:

```
INFO: Results are being streamed to [DASH_BOARD_URL]
INFO: Found 1 target...
INFO: From Injecting stub application:
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_indigo/8965add7011578a5d33385a234e6a985/Master/bazel-out/local_darwin-fastbuild/bin/external/android_tools/tools/android/stubify_manifest.runfiles/external/android_tools/tools/android/stubify_manifest.py", line 29, in <module>
    from third_party.py import gflags
ImportError: No module named third_party.py
ERROR: /Users/indigo/development/Master/src/main/java/com/xperiel/android/api/BUILD:1:1: Injecting stub application failed: stubify_manifest failed: error executing command bazel-out/local_darwin-fastbuild/bin/external/android_tools/tools/android/stubify_manifest --input_manifest src/main/java/com/xperiel/android/api/AndroidManifest.xml --output_manifest ... (remaining 3 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //src/main/java/com/xperiel/android/api:wrapper failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.897s, Critical Path: 0.86s
```

**Comment by ahumesky** [comment]
It looks like the newly-added android_local_tools_repository rule is causing this. gflags is ending up in stubify_manifest.runfiles/external/\<android_local_tools_repository name>/third_party/py/gflags

**Comment by ahumesky** [comment]
The only workaround I can think of right now is to change the import paths in the py files to include "external.android_tools" (or whatever the name of the android_local_tools_repository is). These are the relevant files:

third_party/py/concurrent/futures/__init__.py
third_party/py/concurrent/futures/_base.py
third_party/py/concurrent/futures/process.py
third_party/py/concurrent/futures/thread.py
tools/android/incremental_install.py
tools/android/stubify_manifest.py

**Comment by lberki** [comment]
I have a change out. I hope it lands before the next push to Github by @davidzchen .
