### ISSUE TITLE
Allow specifying http(s)_proxy per http_archive

### ISSUE THREAD

**Issue by djudd-stripe** [bazelbuild/bazel#4155]
### Feature request:
We have an internal corporate HTTP egress proxy that disallows queries to internal resources, for security reasons. Requests to the internet from some of our servers are required to go through this proxy. Meanwhile, I have a Bazel workspace that depends on some artifacts hosted on internal servers, and some artifacts hosted externally. Whether or not I set HTTP_PROXY & HTTPS_PROXY, some artifacts will be broken.

Specifying the http_proxy & https_proxy (for my use case, they're the same) per http_archive rule would let me make this work with Bazel. I suggest adding one or two attributes, whose values override the environment variables if present (but the environment variables could take precedence and my use case would still be ok).

I could work around this by modifying our egress proxy in theory, or by mirroring all artifacts internally, but both have downsides, and it seems simple to solve this on the client side.

**Comment by zlalanne** [comment]
What might work for you is setting a NO_PROXY environment variable, so that bazel knows not to use the proxy when URLs are within a certain domain (mycompany.com)

Unfortunately NO_PROXY support doesn't exist, but I just filed a bug about that
https://github.com/bazelbuild/bazel/issues/4299

**Comment by djudd-stripe** [comment]
Yes, that sounds like it would work very well for my use case if it was implemented, thanks!

**Comment by zlalanne** [comment]
I'm going to try and resurrect an older patch that did this and get it working over the weekend.
