### ISSUE TITLE
[Documentation] maven_jar: add section explaining that transitive dependencies need to be dealt with manually

### ISSUE THREAD

**Issue by sk-** [bazelbuild/bazel#4156]
Please add to the `maven_jar` documentation (https://docs.bazel.build/versions/master/be/workspace.html#maven_jar) that any transitive dependencies need to be deal with manually and that some tools exist to automatically populate the workspace and maybe wrapper rules.

For example:
When depending on Google Truth (http://google.github.io/truth/), you need to also depend on Guava, or otherwise you get a compilation error like the following 

http://central.maven.org/maven2/com/google/guava/guava/23.4-jre/guava-23.4-jre.pom
```
ERROR: /project/javatests/com/sample/BUILD:13:1: Building javatests/com/sample/SampleTest.jar (1 source file) failed (Exit 1).
javatests/com/sample/SampleTest.java:49: error: cannot access Optional
    assertThat(pairs)
    ^
  class file for com.google.common.base.Optional not found
javatests/com/sample/SampleTest.java:81: error: cannot access Multimap
    assertThat(pairs)
    ^
  class file for com.google.common.collect.Multimap not found
Target //javatests/com/sample:SampleTest failed to build
```
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### Environment info
* Operating System:
MacOs X

* Bazel version (output of `bazel info release`):
release 0.7.0-homebrew

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)
Found some open issues here: https://github.com/bazelbuild/bazel/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20maven_jar%20transitive

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by dslomov** [comment]
cc @cgrushko

**Comment by cgrushko** [comment]
Sounds reasonable. Can you send a PR, also mentioning the solution (GitHub.com/johnynek/bazel-deps) and the template project https://github.com/cgrushko/bazel-with-maven-template ?

@dslomov which file should be modified for this?

**Comment by dslomov** [comment]
Closing this as maven_jar is deprecated.
