### ISSUE TITLE
Provide a way to make //java/foo/bar implicitly visible to //javatests/foo/bar

### ISSUE THREAD

**Issue by sk-** [bazelbuild/bazel#4157]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
The documentation on https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes says that "Rules in javatests/foo/bar can always use rules in java/foo/bar" when the visibility is private, which is the default.

However in practice I see that this is not the case, and that both with the default visibility and with `package(default_visibility = ["//visibility:private"])` and with `visibility = ["//visibility:private"],` I get the following error:

```
$ bazel test javatests/com/sample:SampleTest
ERROR: /project/javatests/com/sample/BUILD:13:1: Target '//java/com/sample:Sample' is not visible from target '//javatests/com/sample:SampleTest'. Check the visibility declaration of the former target if you think the dependency is legitimate.
ERROR: Analysis of target '//javatests/com/sample:SampleTest' failed; build aborted: Analysis of target '//javatests/com/sample:SampleTest' failed; build aborted.
INFO: Elapsed time: 0.093s
ERROR: Couldn't start the build. Unable to run tests.
```

The file structure of my project is as following:
```
WORKSPACE
java/com/sample
  BUILD
  Sample.java
javatests/com/sample
  BUILD
  SampleTest.java
```

where the `BUILD` files are:

```
java_library(
    name = "Sample",
    srcs = ["Sample.java"],
)
```

```
java_test(
    name = "SampleTest",
    srcs = ["SampleTest.java"],
    deps = [
        "//java/com/sample:Sample",
        "@junit//jar",
        "@com_google_truth//jar",
        "@com_google_guava//jar",
     ],
)
```

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### Environment info
* Operating System:
MacOS X

* Bazel version (output of `bazel info release`):
release 0.7.0-homebrew

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by meteorcloudy** [comment]
I can confirm this is true, @damienmg is the documentation wrong?

**Comment by damienmg** [comment]
I believe it is. I don't know where that is coming from. I traced back the documentation change from a very old change that @lberki reviewed. I am pretty sure the documentation out of sync.

**Comment by meteorcloudy** [comment]
Then let's fix the documentation.

**Comment by sk-** [comment]
Well, not 100% a documentation issue, because that's how it works internally at Google.

Is there any other way one could configure the project so that `java` packages are automatically visible in the corresponding `javatests` package, without having to manually add a default visibility for every package.

**Comment by benjaminp** [comment]
Google's Java source code layout leaks haphazardly all over Bazel semantics. (Among the ways are the default heuristic of `--instrumentation_filter` and the fact that any package under `javatests/...` is automatically `default_testonly = True`.) I expect the only reason the documented behavior doesn't hold here is that Blaze and Bazel do not share visibility validation code. Perhaps there should be a way to configure when two different packages are logically the same. Or maybe Bazel should simply support the [standard Maven layout](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) and remove all Googlely heuristics.

**Comment by mtsgrd** [comment]
Googled for this issue and found this thread. It seems for right now I'll have to set visibility manually, but does anyone know what direction this is heading? I currently use the Maven standard layout, but am keen on dropping it in favor of something more shallow.

**Comment by brandjon** [comment]
Just stumbled across this -- I'll fix the documentation but let's leave this issue open as a FR.

**Comment by pete-gillin-privitar** [comment]
Given that the [best practices doc](https://docs.bazel.build/versions/master/bazel-and-java.html#directory-structure) says to prefer Maven directory structure, I think the FR should include making anything with `src/main/java` in its path visible to the corresponding `src/test/java` package.

(In the meantime, if there's a way to make this easier with a starlark macro, I'd love to know...)
