### ISSUE TITLE
Can't easily import googleapis into my WORKSPACE

### ISSUE THREAD

**Issue by nictuku** [bazelbuild/bazel#4161]
The [github.com/googleapis/googleapis][1] repository has several `.proto` files for Google APIs, including for example the Google Assistant one.

Unfortunately, though unsurprisingly, they are missing BUILD files so it's not possible to build them from Bazel by purely importing the remote repository.

I can vendor it as a stop-gap solution, no big deal, but this seems sub-optimal at scale.

1. Could the googleapis repo have BUILD.bazel files? OR
1. Could Bazel somehow live without explicitly checked in BUILD files for protos? 

I would suggest that you consider the 2nd option. Imagine a world where a lot of people write gRPC services and want to publish them for the world to use. There needs to be an easy way for folks to share .protos and Bazel is *almost* the perfect solution, except that demanding that all upstream services have BUILD files makes it hard to even get started.

Would it be possible to improve this? Thanks!

  [1]: https://github.com/googleapis/googleapis

**Comment by meteorcloudy** [comment]
I don't think we should provide BUILD files for other repository, I believe the first option is the correct way to go. As for `.proto` files, maybe you also need to import https://github.com/google/protobuf ?
@damienmg What do you think?

**Comment by damienmg** [comment]
We have https://github.com/bazelbuild/bazel-packages about making BUILD for other repository.

What I think we should have is BUILD files in googleapis. I don't know who to speak to get that though, maybe @ola-rozenfeld knows?

**Comment by nictuku** [comment]
FYI I am currently avoiding this problem by using the genproto repository that has pre-generated protos for Go:

https://godoc.org/github.com/google/go-genproto/googleapis/assistant/embedded/v1alpha1

This isn't ideal because it's better to use the same proto and grpc generation tools for the whole codebase. Also I'll later need this for other languages but this is a Go-specific workaround. Just saying this to make it clear to others that it's an option.

**Comment by ola-rozenfeld** [comment]
I would speak to hong@ or cbao@.

**Comment by nictuku** [comment]
For Go projects at least, Gazelle has been implicitly creating BUILD files quite well. So I wonder if the same approach could be used in general.

**Comment by jin** [comment]
Assigning to product excellence team as this is an issue dealing with user experience.

**Comment by philwo** [comment]
Closing, as the mentioned repo has BUILD files now.
