### ISSUE TITLE
Standardized config_settings

### ISSUE THREAD

**Issue by mfarrugi** [bazelbuild/bazel#4167]
Platform `config_settings` are very common and often duplicated, like [this](https://github.com/google/brotli/blob/master/BUILD#L14). 

It would be useful to provide these in a standardized or built-in way.

**Comment by philwo** [comment]
Totally agree with this idea. I don't know a good owner for this FR, but I'll assign it to Dmitry to see if he knows someone.

**Comment by gregestren** [comment]
This should be handled by https://github.com/bazelbuild/bazel/issues/7445. While it doesn't say so explicitly, the current plan is to let you `select` directly on the `constraint_values` defined there, with no need for a separate `config_setting`.

**Comment by gregestren** [comment]
But let's keep this issue open for this specific use case.

**Comment by gregestren** [comment]
Also note https://github.com/bazelbuild/bazel/issues/7668.

**Comment by gregestren** [comment]
https://github.com/bazelbuild/platforms is the home for this, and should get some more attention (from me) over the next few weeks.
