### ISSUE TITLE
Build Bazel on LXC ARM take very very long time

### ISSUE THREAD

**Issue by 123AWS7** [bazelbuild/bazel#4169]
Processor : Intel® Core™ i5-3320M CPU @ 2.60GHz × 4 
Memory : 8 GiB
Main OS : 64-bit ubuntu xenial 
----------------------------------------------------------------------

I am using LXC ARM7l Architecture ubuntu xenial and tried to build bazel onto it but it takes 50 hrs and still building at that moment !! I think that is very long time and it still printing some lines like those 
![bp43n](https://user-images.githubusercontent.com/34027840/33264537-a84d6ea4-d376-11e7-815d-7fd8a3b63071.png)

There is something not right, isn't it ? what is it ??

**Comment by philwo** [comment]
Hi @MYasin93, I need some more data to help you on this issue.

Could you please, when your build gets stuck like this, send the output of "ps axuf" (just the sub-tree of Bazel is fine), "uptime" (to get an idea of system load) and please check the output of "dmesg" for any kernel errors (Oops or BUG messages). If you find any, please paste them.

**Comment by mhlopko** [comment]
Hi @MYasin93, did you manage to get some more debug info?
