### ISSUE TITLE
`--nobuild_runfile_manifests` breaks running tests

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4177]
### Description of the problem / feature request / question:

The [`--nobuild_runfile_manifests`](https://docs.bazel.build/versions/master/user-manual.html#flag--build_runfile_manifests) flag breaks running tests.

### If possible, provide a minimal example to reproduce the problem:

```
  $ cat BUILD
sh_test(
    name = 'foo_test',
    srcs = ['foo_test.sh'],
)

  $ cat foo_test.sh 
#!/bin/bash
echo "hello from $(basename $0)"

  $ bazel test //:foo_test --nobuild_runfile_manifests
INFO: Analysed target //:foo_test (1 packages loaded).
INFO: Found 1 test target...
ERROR: /tmp/foo/BUILD:1:1:  failed (Exit 1): build-runfiles failed: error executing command _bin/build-runfiles bazel-out/k8-fastbuild/internal/_middlemen/foo_Utest-runfiles_artifacts bazel-out/k8-fastbuild/internal/_middlemen/foo_Utest-runfiles_artifacts.runfiles
_bin/build-runfiles (args bazel-out/k8-fastbuild/internal/_middlemen/foo_Utest-runfiles_artifacts bazel-out/k8-fastbuild/internal/_middlemen/foo_Utest-runfiles_artifacts.runfiles): creating directory 'bazel-out/k8-fastbuild/internal/_middlemen/foo_Utest-runfiles_artifacts.runfiles': No such file or directory [2]
Target //:foo_test up-to-date:
  bazel-bin/foo_test
INFO: Elapsed time: 0.177s, Critical Path: 0.01s
FAILED: Build did NOT complete successfully
//:foo_test                                                           NO STATUS

Executed 0 out of 1 test: 1 was skipped.

  $ bazel test //:foo_test --build_runfile_manifests
INFO: Analysed target //:foo_test (0 packages loaded).
INFO: Found 1 test target...
Target //:foo_test up-to-date:
  bazel-bin/foo_test
INFO: Elapsed time: 0.425s, Critical Path: 0.10s
INFO: Build completed successfully, 4 total actions
//:foo_test                                                              PASSED in 0.1s

Executed 1 out of 1 test: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
```

### Environment info
* Operating System:
Ubuntu 14.04

* Bazel version (output of `bazel info release`):
0.8.0

**Comment by benjaminp** [comment]
I think local testing is incompatible with `--nobuild_runfile_manifests` because you're denying the test action an input (the runfiles tree) it requires to work. Similarly with `bazel run`. (I suppose it would be technically possible for test the strategy to reify the runfiles tree from the associated `RunfilesSupplier`. But my supposition is that anyone using `--nobuild_runfile_manifests` is trying to run everything remotely anyway?)

I have a change which improves the error message when local tests try to run with `--nobuild_runfile_manifests`, but I haven't put it up for review because it depends on https://cr.bazel.build/21873.

**Comment by laszlocsomor** [comment]
I agree this flag hardly makes sense when testing/running locally. I think a clear error message is the easiest and best solution here.

**Comment by philwo** [comment]
@benjaminp https://cr.bazel.build/21873 has been merged yesterday. Sorry for the delay.

I see that you sent the fix for this, too: https://bazel-review.googlesource.com/c/bazel/+/25010
Thanks!

**Comment by benjaminp** [comment]
Thanks for merging. I suppose we may close this now?

**Comment by laszlocsomor** [comment]
Yup. Thanks for pushing through!
