### ISSUE TITLE
Error depending on google.golang.org packages via `go_repository`

### ISSUE THREAD

**Issue by tiziano88** [bazelbuild/bazel#4184]
### Description of the problem / feature request / question:

In a Go project, most of the dependencies are handled correctly by `go_repository`, but those from `google.golang.org` always fail to compile when depended upon.

### If possible, provide a minimal example to reproduce the problem:

WORKSPACE:

```
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    commit = "a390e7f7eac912f6e67dc54acf67aa974d05f9c3",
)

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains", "go_repository")
go_rules_dependencies()
go_register_toolchains()

load("@io_bazel_rules_go//proto:def.bzl", "proto_register_toolchains")
proto_register_toolchains()

go_repository(
    name = "org_golang_google_grpc",
    commit = "7db1564ba1229bc42919bb1f6d9c4186f3aa8678",
    importpath = "google.golang.org/grpc",
)
```

BUILD.bazel:

```
load("@io_bazel_rules_go//go:def.bzl", "gazelle")

gazelle(
    name = "gazelle",
    prefix = "deepmindhealth.com",
)

sh_binary(
    name = "xxx",
    srcs = ["test.sh"],
    deps = [
        "@org_golang_google_grpc//status",
    ],
)
```

Then run

`bazel build :xxx`

Result:

```
ERROR: [...]/BUILD.bazel:8:1: no such package '@org_golang_google_grpc//status': BUILD file not found on package path and referenced by '//:xxx'                                    
ERROR: Analysis of target '//:xxx' failed; build aborted: no such package '@org_golang_google_grpc//status': BUILD file not found on package path                                                    
INFO: Elapsed time: 0.957s                       
FAILED: Build did NOT complete successfully (6 packages loaded)                                   
```

### Environment info
* Operating System:

`Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux`

* Bazel version (output of `bazel info release`):

`release 0.8.0`

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

- https://groups.google.com/forum/#!searchin/bazel-discuss/google.golang.org|sort:date/bazel-discuss/vA504VqSiCw/fDxWm1QkCAAJ

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by tiziano88** [comment]
Interestingly, using v. `0.7.1` of `rules_go` I get a different error message:

```
ERROR: [...]/BUILD.bazel:8:1: no such target '@org_golang_google_grpc//status:status': target 'status' not declared in package 'status' defined by [...]/external/org_golang_google_grpc/status/BUILD.bazel and referenced by '//:xxx'
ERROR: Analysis of target '//:xxx' failed; build aborted: Loading failed
INFO: Elapsed time: 21.211s
FAILED: Build did NOT complete successfully (15 packages loaded)
```

**Comment by philwo** [comment]
I think the right place to report this issue would be here: https://github.com/bazelbuild/rules_go/issues
But I'll try to find an owner for this :)

**Comment by philwo** [comment]
FYI @ianthehat - are you the right person to assign this bug to? If not, please unassign. Thanks :)

**Comment by ianthehat** [comment]
@org_golang_google_grpc//status really isn't a valid target, no such folder or sources exist in that repository, what were you hoping it would be?
