### ISSUE TITLE
OSX: Changing file contents without changing its size doesn't trigger a rebuild of cc_binary

### ISSUE THREAD

**Issue by ambrusc** [bazelbuild/bazel#4189]
### Description of the problem:
Changing file contents without changing the file size should probably trigger a rebuild, but it doesn't on my OSX machine. I can test on Linux and Windows tomorrow.

### To repro:
1 . download [osx_no_rebuild.zip](https://github.com/bazelbuild/bazel/files/1512649/osx_no_rebuild.zip) (or do this in any other workspace -- there is nothing special about this one)
2. Run `bazel build //osx_no_rebuild:main && ./bazel-bin/osx_no_rebuild/main`: observe one target rebuilt.
3. Make any change (including a syntax-breaking change) in main.cpp _without changing the file size_.
2. Run `bazel build //osx_no_rebuild:main && ./bazel-bin/osx_no_rebuild/main`: observe no targets built; the cached binary from step 2. is executed instead.

### Environment info
* Operating System: OSX 10.12.5, bash on iterm 3.1.beta.6, bazel 0.7.0-homebrew, and Sublime Text 2
* Bazel version (output of `bazel info release`): release 0.7.0-homebrew
* Output of `bazel version`
Build label: 0.7.0-homebrew
Build target: bazel-out/darwin_x86_64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sun Nov 12 03:11:31 2017 (1510456291)
Build timestamp: 1510456291
Build timestamp as int: 1510456291

### Relevant or similar issues:
Issue #1525 seems somewhat similar, but didn't yield an answer. #2674 may be mildly relevant.

https://github.com/bazelbuild/bazel/issues/1525#issuecomment-266976638 about DigestUtils may be relevant, or https://github.com/bazelbuild/bazel/issues/1525#issuecomment-273709447 about FSEvents on OSX.

**Comment by philwo** [comment]
That sounds like a pretty bad bug! However, I can't reproduce it on my machine:

macOS 10.12.6, Bazel 0.8.0 (from our GitHub releases), Sublime Text 3 (but also tested with "sed -i")

I tried like this:

```bash
bazel --bazelrc=/dev/null build //osx_no_rebuild:main && ./bazel-bin/osx_no_rebuild/main
sed -i '' 's/1337/1338/' osx_no_rebuild/main.cpp
bazel --bazelrc=/dev/null build //osx_no_rebuild:main && ./bazel-bin/osx_no_rebuild/main
```

I get the correct output: 1337 and 1338. I also tried with `--watchfs`, but it didn't change anything.

Can you still repro this?
