### ISSUE TITLE
Building Android fails missing target

### ISSUE THREAD

**Issue by XperielIndigo** [bazelbuild/bazel#419]
Hi,

I just updated to https://github.com/bazelbuild/bazel/commit/828126145fb1f8182c3667a0046b85296cb40691 and now when I run `build` or `mobile-install` on an `android_binary` target I get the following error:

```
ERROR: /private/var/tmp/_bazel_indigo/8965add7011578a5d33385a234e6a985/external/android_tools/tools/android/BUILD:5:1: no such target '@android_tools//src/tools/android/java/com/google/devtools/build/android/incrementaldeployment:stub_application': target 'stub_application' not declared in package 'src/tools/android/java/com/google/devtools/build/android/incrementaldeployment' defined by /private/var/tmp/_bazel_indigo/8965add7011578a5d33385a234e6a985/external/android_tools/src/tools/android/java/com/google/devtools/build/android/incrementaldeployment/BUILD and referenced by '@android_tools//tools/android:incremental_stub_application'.
```

**Comment by damienmg** [comment]
Hello I am on it.

In the time being you can simply add
android_local_tools_repository(name = "android_tools", path = "/path/to/the/bazel/workspace")

**Comment by XperielIndigo** [comment]
Hi,

I have that already. When I emacs into the BUILD file at `src/tools/android/java/com/google/devtools/build/android/incrementaldeployment` it doesn't have the target.

**Comment by damienmg** [comment]
Oh sorry I misread the message.

**Comment by damienmg** [comment]
I am working on a slightly related matter, you can fix it by editing the deps (adding the incremental_ prefix) of the first two targets of tools/android/BUILD

**Comment by ulfjack** [comment]
With every bug we squash a new one comes up. :-(
