### ISSUE TITLE
Protobuf sample workspace file is missing required fields

### ISSUE THREAD

**Issue by monkeynova** [bazelbuild/bazel#4191]
The documentation at https://blog.bazel.build/2017/02/27/protocol-buffers.html provides a sample WORKSPACE file to get started with the proto libraries. It includes a shortened form of the workspace found at https://github.com/cgrushko/proto_library/blob/master/WORKSPACE for brevity.

Unfortunately the inline documentation doesn't include the strip_prefix field which is required to get the build working, and it was non-intuitive from the error what exactly when wrong (see below for the specific error I got).

Can the documentation be updated to include the strip_prefix (and maybe the sha256 too since that would be good practice) to make sure that it's easy for a user to get up and running quickly?

keith-mbp:logic-solver keith$ bazel run -c opt :swimming_pool -- --brute_force
ERROR: /Users/keith/github/logic-solver/BUILD:25:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf//:protoc', but this target could not be found because of: no such package '@com_google_protobuf//': BUILD file not found on package path.
ERROR: Analysis of target '//:swimming_pool' failed; build aborted: Loading failed.
INFO: Elapsed time: 2.171s
ERROR: Build failed. Not running target.

**Comment by j3parker** [comment]
You could submit a PR to https://github.com/bazelbuild/bazel-blog/blob/master/_posts/2017-02-27-protocol-buffers.md

**Comment by monkeynova** [comment]
Thanks for the link. Sent: https://github.com/bazelbuild/bazel-blog/pull/48
