### ISSUE TITLE
RPM for openSUSE / SUSE Enterprise Linux  / Need for dependency listing. 

### ISSUE THREAD

**Issue by plinnell** [bazelbuild/bazel#4195]
* Operating System:  Linux

* Bazel version (output of `bazel info release`):
0.8.0

#2701 is related

I'm developing an rpm for openSUSE / SUSE which will be built on https://build.opensuse.org and hosted in a repo with a pretty permanent address on download.opensuse.org

Before getting it officially in the distro, we need to be able to build bazel without the bundled third party bits. To do so, I would need a full list of the dependencies either as jars or libraries. Is there a way to get bazel to use the distro version of protobuf ? That is already in the distro and I suspect most of the bundled jars.

**Comment by iirina** [comment]
cc: @aehlig

**Comment by plinnell** [comment]
Related: https://github.com/bazelbuild/bazel/issues/4394

**Comment by meisterT** [comment]
closing in favor of https://github.com/bazelbuild/bazel/issues/9408
