### ISSUE TITLE
Patch release 0.8.1

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#4196]
Apparently #4173 is a regression in 0.8.0 (#3772).
This issue tracks the progress of 0.8.1 patch release to address it.

**Comment by dslomov** [comment]
0.8.1rc1: `scripts/release/release.sh create 0.8.1 cff0dc9 8a49b15 275ae45 d0bf589 9738f35 0d6ff47 49008a3`

49008a3 is the fix for #4173

**Comment by dslomov** [comment]
I had to patch 49008a3 to add missing imports, trying again.

**Comment by dslomov** [comment]
rc1 is created with a moral equivalent of `scripts/release/release.sh create 0.8.1 cff0dc9 8a49b15 275ae45 d0bf589 9738f35 0d6ff47 49008a3 f499ddc `

**Comment by dslomov** [comment]
Pushed rc3, fixing some merges

**Comment by mattmoor** [comment]
Any update on when this will land?  Our CI is still on the floor :(

**Comment by dslomov** [comment]
Ok, I am fast-tracking rc3 to release.

**Comment by dslomov** [comment]
Pinging @petemounce for chocolatey

**Comment by dslomov** [comment]
0.8.1 is out, I am updating the CI & related things

**Comment by dslomov** [comment]
All done

**Comment by petemounce** [comment]
https://chocolatey.org/packages/bazel/0.8.1
