### ISSUE TITLE
[Feature Request] Please document how to use a static analyzer with bazel

### ISSUE THREAD

**Issue by snnn** [bazelbuild/bazel#4203]
We often need to run static analyze on our code, but most static analyze tools (e.g. clang scan-build, HP Fortify SCA) do not  have a document of how to use it with bazel.  For most users, it's not a easy to find a way to do that. (see #1622).

**Comment by zoidbergwill** [comment]
There are some examples in this repo: https://github.com/google/startup-os/tree/master/tools

**Comment by snnn** [comment]
Thanks!
