### ISSUE TITLE
consider moving to preemptive auth for remove cache interactions

### ISSUE THREAD

**Issue by softprops** [bazelbuild/bazel#4209]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

The implementation of remote caches http blob store results in two requests for every logical single request when the remote_rest_cache value contains basic authentication credentials

```bash
--remote_rest_cache=https://user:pass@myhost.com
```

This can be observed by monitoring the responses a remote cache server returns, typically a 401, before the client sends a second request containing the credentials. This is the default behavior of apache httpclient but results doubling the network chatter between a bazel build and a cache server

The potential improvement to be made is to opt into [preemptive auth](http://hc.apache.org/httpclient-3.x/authentication.html#Preemptive_Authentication). I think this could probably happen with a small change to the RestBlobStore [here](https://github.com/bazelbuild/bazel/blob/062da5cbb5848dbfa1cf8bae028b06313a84ef0d/src/main/java/com/google/devtools/build/lib/remote/blobstore/RestBlobStore.java#L60).

### If possible, provide a minimal example to reproduce the problem:

set up a remote build cache with basic auth authentication and configure a bazel build with a remote_rest_cache parameter

```bash
--remote_rest_cache=https://user:pass@myhost.com
```

Observe two requests for every http interaction with the remote cache server.

### Environment info
* Operating System:

* Bazel version (output of `bazel info release`):

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by pspeter3** [comment]
In one of my projects, Bazel does not seem to be sending the second request with the authorization headers.

**Comment by softprops** [comment]
I discovered this issue with some server response code metrics I started recoding to set up cache server alerting. For every 401 I got  a 200 immediately after.

**Comment by iirina** [comment]
CC: @ulfjack

**Comment by buchgr** [comment]
@softprops Apologies that I have missed this issue. Your request sounds reasonable. Admittedly, the fact that http authorization is working is more by accident than by design. We have so far mostly had to authenticate against Google Cloud Services and thus this was not a priority.

I ll make sure to work on this after the christmas break.

**Comment by mikelikespie** [comment]
I'm interested in this working as well. I think having credentials in the URL used to work, but probably just by accident as mentioned. I don't think our security team is OK having a WebDAV server without any authentication, so having support for basic auth would be a big win

**Comment by buchgr** [comment]
This has been fixed.
