### ISSUE TITLE
when bazel running a cc_binary in Windows, the C++ app can't find its data dependencies 

### ISSUE THREAD

**Issue by thinlizzy** [bazelbuild/bazel#4215]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I have a cc_binary rule with a single .cpp file and one data dependency. I have no means to tell the application where to find the data.

### If possible, provide a minimal example to reproduce the problem:

# BUILD file in engine_test/demos directory relative to the WORKSPACE directory
```
cc_binary(
	name = "test",
	srcs = [
		"Test.cpp",
	],
	data = ["//engine_test/images"],
)
```

# BUILD file in engine_test/images directory. same deal
```
filegroup(
    name = "images",
    srcs = glob([
        "*.png",
    ]),
)

```
# Test.cpp
```
#include <fstream>

int main()
{
  std::fstream fs("engine_test/images/test.png");  // can't find the file
  // fs.fail() == true   :(
}

```
### Environment info
* Operating System: Windows
* Bazel version (output of `bazel info release`): release 0.5.4

###  Have you found anything relevant by searching the web?
https://github.com/bazelbuild/bazel/issues/3881 seems to be related, but I also tried to use ($location //engine_test/images) without success.

### Anything else, information or logs or outputs that would be helpful?
my current workaround to open the files is:
`std::fstream fs("../../../../../../engine_test/images/test.png"); `

**Comment by iirina** [comment]
CC: @laszlocsomor Do you know why this doesn't work on Windows?

**Comment by laszlocsomor** [comment]
See https://groups.google.com/d/msg/bazel-discuss/Po8xN8dhWkI/sWPUYV9YBAAJ
