### ISSUE TITLE
CC Variable is ignored on OSX

### ISSUE THREAD

**Issue by rnburn** [bazelbuild/bazel#4217]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

CC won't set the compiler on OSX, as it does on linux.

### If possible, provide a minimal example to reproduce the problem:

```
touch WORKSPACE
echo "int main() { return 0; }" > main.cpp
echo "cc_binary(name = 't', srcs = ['main.cpp'], copts = ['-std=c++1z', '-fconcepts'])" > BUILD
bazel build -s --action_env CC=/usr/local/bin/g++-7 //:t
```
gives the error
```
...........................................................
INFO: Analysed target //:t (9 packages loaded).
INFO: Found 1 target...
SUBCOMMAND: # //:t [action 'Creating runfiles tree bazel-out/darwin-fastbuild/bin/t.runfiles']
(cd /private/var/tmp/_bazel_ryanburn/c86ea362b0f6ec05e4e55b0eda264fd0/execroot/__main__ && \
  exec env - \
    CC=/usr/local/bin/g++-7 \
    PATH=/opt/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/ryanburn/bin \
    TMPDIR=/var/folders/xs/q7s6hkh549n29x625fbjg26h0000gn/T/ \
  _bin/build-runfiles bazel-out/darwin-fastbuild/bin/t.runfiles_manifest bazel-out/darwin-fastbuild/bin/t.runfiles)
SUBCOMMAND: # //:t [action 'Compiling main.cpp']
(cd /private/var/tmp/_bazel_ryanburn/c86ea362b0f6ec05e4e55b0eda264fd0/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.12 \
    CC=/usr/local/bin/g++-7 \
    PATH=/opt/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/ryanburn/bin \
    TMPDIR=/var/folders/xs/q7s6hkh549n29x625fbjg26h0000gn/T/ \
    XCODE_VERSION_OVERRIDE=8.3.3 \
  external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' -iquote . -iquote bazel-out/darwin-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/darwin-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -MD -MF bazel-out/darwin-fastbuild/bin/_objs/t/main.d '-frandom-seed=bazel-out/darwin-fastbuild/bin/_objs/t/main.o' '-isysroot __BAZEL_XCODE_SDKROOT__' '-std=c++1z' -fconcepts -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c main.cpp -o bazel-out/darwin-fastbuild/bin/_objs/t/main.o)
ERROR: /private/tmp/bazel/BUILD:1:1: C++ compilation of rule '//:t' failed (Exit 1)
clang: error: unknown argument: '-fconcepts'
Target //:t failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 14.191s, Critical Path: 0.10s
FAILED: Build did NOT complete successfully
```
showing that it's running clang and not the gcc compiler I pointed to

### Environment info
* Operating System: 
OS X Sierra

* Bazel version (output of `bazel info release`): 
release 0.8.0-homebrew

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?

[StackOverflow Question](https://stackoverflow.com/questions/47624689/how-to-set-c-compiler-on-os-x-with-bazel)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by abergmeier** [comment]
Did you validate that `CC='/usr/local/bin/g++-7' bazel build //:t` works?

**Comment by rnburn** [comment]
Doesn't make any difference. From this part of the output,
```
exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.12 \
    CC=/usr/local/bin/g++-7 \
    PATH=/opt/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/ryanburn/bin \
    TMPDIR=/var/folders/xs/q7s6hkh549n29x625fbjg26h0000gn/T/ \
    XCODE_VERSION_OVERRIDE=8.3.3 \
  external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' -iquote . -iquote bazel-out/darwin-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/darwin-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -MD -MF bazel-out/darwin-fastbuild/bin/_objs/t/main.d '-frandom-seed=bazel-out/darwin-fastbuild/bin/_objs/t/main.o' '-isysroot __BAZEL_XCODE_SDKROOT__' '-std=c++1z' -fconcepts -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c main.cpp -o bazel-out/darwin-fastbuild/bin/_objs/t/main.o)
```
you can see it prints out `CC=/usr/local/bin/g++-7 `, so it's picking up the environmental variable; it's doing nothing with it.

**Comment by abergmeier** [comment]
So the good news is, from looking at the code, it seems like configure (in Skylark) is correct.
Your problem is probably coming from somewhere in Java. Maybe @mhlopko knows more details, when clang vs gcc is chosen on macOS.

**Comment by mhlopko** [comment]
Pasting the answer from https://stackoverflow.com/questions/47624689/how-to-set-c-compiler-on-os-x-with-bazel:

`CC` correctly works only when you use the C++-only toolchain. If you have Xcode installed, bazel will detect this and automatically pick a different toolchain, the one that supports both C++ and ObjC. This toolchain can only use Xcode-provided clang.

This is unfortunate and I propose two solutions:

1) File a feature request for bazel to make it possible to select which toolchain is used. This will allow you to tell bazel that even though you have Xcode installed, you want to use C++ only toolchain with a custom compiler. This is quite simple and doable in a short time.
2) File a feature request for bazel to make it possible to select which compiler is used with C++/ObjC toolchain. I cannot comment on viability of this, I know next to nothing about osx, and I have no idea if it makes any sense to compile ObjC with a compiler that is not provided with Xcode...

**Comment by iirina** [comment]
I will close this as @mhlopko answered and provided 2 solutions.
