### ISSUE TITLE
Build Encyclopedia: document `genrule.stamp`

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4219]
Even though `genrule.stamp` is supported in Bazel, not just Blaze, it's not documented publicly.

**Comment by meisterT** [comment]
dupe of #4942

**Comment by alokpr** [comment]
This should be reopened. Both issue 4219 and issue 4942 have been closed as dups of each other.

**Comment by meisterT** [comment]
@alokpr #4942 is still open.
