### ISSUE TITLE
Failed to find underlying Bazel executable from bazel-real file

### ISSUE THREAD

**Issue by airmak** [bazelbuild/bazel#4225]
When I tried to run the **bazel build** command on Git Bash, I encountered the error:

**Failed to find underlying Bazel executable at /usr/local/bin/bazel-real**

When I looked, there wasn't a folder at /usr/local/bin/ named "bazel-real," even though I have already downloaded Bazel from its binary.

**Comment by sri123098** [comment]
Could you please let me know how you have fixed this?
