### ISSUE TITLE
Wrong name for bazel process

### ISSUE THREAD

**Issue by chaoren** [bazelbuild/bazel#4227]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

Bazel process name is
```
bazel(<parent of workspace directory>)
```
instead of
```
bazel(<workspace name>)
```
This is probably because there's only one workspace with blaze, and we use the client name instead. This is wrong for bazel, however.

### If possible, provide a minimal example to reproduce the problem:
1. Run long bazel command
2. 
```
$ pgrep -fa bazel
<pid> bazel(<parent of workspace directory>) -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=...
```
### Environment info
* Operating System: Debian
* Bazel version (output of `bazel info release`): release 0.8.0rc2

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by akira-baruah** [comment]
@chaoren if https://github.com/akira-baruah/bazel/commit/81d8d1270a0bff17c1bcfab6251c57783473d669  makes sense, please let me know and I'll make a pull request.

**Comment by chaoren** [comment]
I think it should first try to use the workspace name. If the workspace doesn't have a name, then use the workspace directory name.

I.e., if the `WORKSPACE` contains this
```
workspace(name = "foo")
```
then it should be `bazel(foo)`.

**Comment by akira-baruah** [comment]
I could be wrong, but it seems that `WORKSPACE` is parsed by the server, so setting the server process name to the value of `workspace(name = "foo")` at start up might be a circular dependency. Any ideas?

**Comment by iirina** [comment]
cc: @philwo

**Comment by philwo** [comment]
I agree very much that this would be a nice improvement for Bazel users.

FYI, the current behavior of using the parent directory name of the workspace is due to some legacy directory structure in use inside Google, where the parent directory actually makes more sense. But I'd be happy to take a patch here and will make sure that we can get it in. :)

**Comment by akira-baruah** [comment]
Thanks for the feedback @philwo! Do you know of any way to incorporate the `workspace(name = ...)` functionality that @chaoren suggested above? It would probably help support the internal legacy directory structure that you mentioned.

I made #4253 to address this issue. Please let me know what you think - thanks!
