### ISSUE TITLE
The same empty file written to the remote cache multiple times

### ISSUE THREAD

**Issue by mmorearty** [bazelbuild/bazel#4228]
### Description of the problem / feature request / question:

I think that the same zero-byte file is written to the remote cache (content-addressable storage, CAS) twice each time a genrule is run.

I don't think this breaks any functionality; but it probably slows Bazel down a little.

### If possible, provide a minimal example to reproduce the problem:

Set up a remote cache, e.g. nginx. In this example, I set up a remote cache on localhost port 8080.

BUILD file:

```python
genrule(
    name = "gen1",
    srcs = ["gen1.in"],
    outs = ["gen1.out"],
    cmd = "cp $< $@"
)
```

Then make a `gen1.in` file with any text in it.

Run:

```bash
bazel build --spawn_strategy=remote --remote_rest_cache=http://localhost:8080 :gen1
```

Then look at the log file of your remote cache. In my case, I see a `GET` request (this is an attempt to see if the final output is in the cache); then, after that returns a 404, I see four `PUT` requests. Note that two of them are identical. If you download /cas/d41d8cd98f00b204e9800998ecf8427e (with `curl http://localhost:8000/cas/d41d8cd98f00b204e9800998ecf8427e`), you will see that it's an empty file.

```
GET /ac/785858acef65db774c552415c8f4299b 404
PUT /cas/eac67abc9f8774df064db9e5868633b0 200
PUT /cas/d41d8cd98f00b204e9800998ecf8427e 200
PUT /cas/d41d8cd98f00b204e9800998ecf8427e 200
PUT /ac/785858acef65db774c552415c8f4299b 200
```

### Environment info
* Operating System:

Mac and Linux.

* Bazel version (output of `bazel info release`):

0.8.0

**Comment by buchgr** [comment]
Agreed. W should probably filter out duplicates on upload. Seems like an easy fix.

**Comment by buchgr** [comment]
This has been fixed a while ago. We de-duplicate uploads during a build for both the gRPC and HTTP protocol
