### ISSUE TITLE
Error locating GNU coreutils on MSYS2 shell

### ISSUE THREAD

**Issue by airmak** [bazelbuild/bazel#4229]
Trying to run **./compile.sh** to compile Bazel from its source, I run into the following error:
**cannot locate GNU coreutils; check your PATH.
       (You may need to run 'export PATH=/bin:/usr/bin:$PATH)'**

Even when the suggested command is run, the following error pops up: 
**-bash: export: `/bin:/usr/bin:': not a valid identifier**

**Comment by iirina** [comment]
cc: @laszlocsomor

**Comment by laszlocsomor** [comment]
Please note that there's a typo in that error message: the closing parenthesis and the apostrophe should be swapped.

@airmak , what's the output of `echo $PATH`?

**Comment by airmak** [comment]
The output of **echo $PATH** is 
/C:/Users/cogneuro/bin:/C:/Windows/System32/Python36

Then when I try to run **export PATH=/bin:/usr/bin:$PATH**, it gives me the output 

**-bash: export: `/bin:/usr/bin:/C:/Users/cogneuro/bin:/C:/Windows/System32/Python36': not a valid identifier**

Thanks for your help @laszlocsomor

**Comment by laszlocsomor** [comment]
The paths in your `$PATH` envvar are not all valid for MSYS.
Run this command:
```
export PATH=/bin:/usr/bin:/c/Users/cogneuro/bin:/c/Windows/System32/Python36
```

**Comment by airmak** [comment]
Worked! Thank you
