### ISSUE TITLE
Add a tag for tests that only pass on Windows

### ISSUE THREAD

**Issue by aj-michael** [bazelbuild/bazel#4230]
I noticed that //third_party/def_parser:def_parser_test only works on Windows. In fact, it does not build on mac or linux. We use the "no_windows" tag to mark tests that dont work on Windows. Perhaps we should have a corresponding tag to indicate tests that only work on Windows?

This is an issue for our internal CI system which uses bazel query to determine which tests to run on mac, but currently there is no way to filter out Windows-only tests.

**Comment by laszlocsomor** [comment]
We already have such tests, and what I usually do is using a `select` and running an empty test on non-Windows. This has the advantage that it does not require `tags`-based filtering (and that the tags are consistent across the code base), with the (in my opinion negligible) drawback that Bazel will complain that the test ran too fast for its size.

Example: https://github.com/bazelbuild/bazel/blob/9ac1f287eab0ce2fa0e3c685cd218832091f19e9/src/test/py/bazel/BUILD#L59-L64

**Comment by aj-michael** [comment]
Thanks for the tip, that sounds good. I'll close this issue since we don't intend to add the tags as I described them.

I mailed https://bazel-review.googlesource.com/c/bazel/+/25250 to add selects to def_parser_test.
