### ISSUE TITLE
Support selecting C++ Only toolchain.

### ISSUE THREAD

**Issue by rnburn** [bazelbuild/bazel#4231]
### Description of the problem / feature request / question:

Setting bazel up to use GCC on OSX is currently a difficult task.

This follows on from [suggestion (1)](https://github.com/bazelbuild/bazel/issues/4217#issuecomment-348960808) in #4217 and proposes adding an option to select the C++ only toolchain so that you can easily specify the compiler with CC.

###  Have you found anything relevant by searching the web?

See also [StackOverflow question](https://stackoverflow.com/q/47624689/4447365).

**Comment by mhlopko** [comment]
By specifying `BAZEL_USE_CPP_ONLY_TOOLCHAIN=1` you can force using the C++-only toolchain.

**Comment by fbriggs** [comment]
@mhlopko thanks! do you have a guess of when this will be in the version of bazel which is installed by homebrew?

**Comment by mhlopko** [comment]
Bazel 0.10.0 should have the cl.

**Comment by 745198699** [comment]
Hello,
Is there any way to select my clang as compiler? 
By specifying BAZEL_USE_CPP_ONLY_TOOLCHAIN=1 and I set CC/CXX as my clang, but I got a error: 
clang-6.0: unknown arguments "-fno-canonical-system-headers". 
Thanks! :)

**Comment by mhlopko** [comment]
That should work, if you're trying with the latest bazel version, and it's passing that flag, please file a new issue. Thanks!
