### ISSUE TITLE
Unzip command not found even though I had already downloaded the package

### ISSUE THREAD

**Issue by airmak** [bazelbuild/bazel#4234]
When compiling Bazel (**./compile.sh**) on the msys2 shell, the following comes up:

**line 194: unzip: command not found**

However, I thought I had already installed the zip and unzip packages using **pacman -Syu** and **pacman -Su**. When I tried to download these packages again just to make sure, the shell's output said that the files already existed. Did I download the wrong packages?

**Comment by airmak** [comment]
@laszlocsomor

**Comment by laszlocsomor** [comment]
What's the output of `which unzip` and `unzip`?
