### ISSUE TITLE
Cannot use cc_libary as dep to py_binary or py_test

### ISSUE THREAD

**Issue by skye** [bazelbuild/bazel#4237]
### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

According to https://docs.bazel.build/versions/master/be/python.html, the deps of py_binary and py_test rules "can be py_binary rules, py_library rules or cc_library rules." However, adding a cc_library dep produces an error like `'target' does not have mandatory providers: 'py'`.

FWIW this works in blaze.

### If possible, provide a minimal example to reproduce the problem:
```
touch WORKSPACE
touch foo.py
touch bar.cc

cat > BUILD << EOF
py_binary(
    name = "foo",
    srcs = ["foo.py"],
    deps = [":bar"],
)

cc_library(
    name = "bar",
    srcs = ["bar.h"],
)
EOF

bazel build :foo
```
This yields:
```
ERROR: /.../BUILD:4:12: in deps attribute of py_binary rule //:foo: '//:bar' does not have mandatory providers: 'py'.
ERROR: Analysis of target '//:foo' failed; build aborted: Analysis of target '//:foo' failed; build aborted.
```
### Environment info
* Operating System: Ubuntu 14.04

* Bazel version (output of `bazel info release`): release 0.7.0

**Comment by iirina** [comment]
Unfortunately the Bazel documentation is wrong in this case, `cc_library` dependencies are not allowed. I will update the documentation.

**Comment by learyg** [comment]
It might also be good for us to document the rationale for why this doesn't work / doesn't need to work -- my understanding is there's some assumption of how linkage works in Bazel that precludes fully statically linked py_binaries? So all SWIG modules must be shared objects and it doesn't make sense for a cc_library to link into a py_binary without it being explicitly SWIG wrapped?

**Comment by jaebaek** [comment]
I have the same issue. Why other deps are not allowed?
My `py_binary` has a dependency with `pkg_tar`. If I put the `pkg_tar` dependency to `py_binary` as `data=[..]`, the `py_binary` exeuction does not trigger updating `pkg_tar` correctly.

**Comment by yaadhavraajagility** [comment]
What is the workaround for this?

**Comment by sberney** [comment]
Indeed: it's not useful to have a polyglot builder if the components being built can call each other.
