### ISSUE TITLE
BuildConfiguration.Options.collectCodeCoverage should be propagated to the host configuration

### ISSUE THREAD

**Issue by tvolkert** [bazelbuild/bazel#4238]
### Summary

[`BuildConfiguration.Options.collectCodeCoverage`](https://github.com/bazelbuild/bazel/blob/3d362fb9a122ceee6d781be127dfedbbff8051f8/src/main/java/com/google/devtools/build/lib/analysis/config/BuildConfiguration.java#L665) should be propagated to the host configuration in [`BuildConfiguration.Options.getHost()`](https://github.com/bazelbuild/bazel/blob/3d362fb9a122ceee6d781be127dfedbbff8051f8/src/main/java/com/google/devtools/build/lib/analysis/config/BuildConfiguration.java#L1035)

### Use case

Consider the following targets:

* `//foo/toolkit:android` -- an Android app that must be built in an Android configuration.
* `//foo/toolkit:ios` -- an iOS app that must be built in an iOS configuration
* `//mobile/toolkit:tool` -- A host-based executable target capable of installing and launching both apps defined in the previous targets (on either Android or iOS devices/emulators, respectively), then establishing a communication channel between the host and the running app, allowing for things like hot code reload, etc.  This executable target must be built in the host configuration.

Now consider that `//mobile/toolkit:tool` represents a large chunk of code, and as such, it has many tests.  The tests are set up using a newly defined Skylark rule, like so:

* The rule defines an attribute that is used to specify the app that the test will build.  This attribute specifies the target configuration.
* The rule defines an attribute that is used to specify the host-based tool.  This attribute specifies the host configuration.
* The test executable will:
  * Provision an Android or iOS emulator.
  * Invoke the host-based tool as a spawned process, pointing it at the app via flags passed to the process.
  * Write to the process' `stdin` (as a user would) and read from the process' `stdout` -- thus verifying the behavior that they wish to test.

Once the tests are all written and running properly, the next step is to track code coverage of the host-based tool.  However, when a coverage run is attempted, even with an instrumentation filter of `//mobile/toolkit`, Bazel thinks that the list of instrumented files is empty.  **It turns out this is because the switch to the host configuration turned off `collectCodeCoverage` in the build configuration's options.**

Bottom line: the coverage instrumentation filter is the hook that the user has to specify which files should be instrumented and which shouldn't -- so there's no reason to not propagate the coverage bit to the host configuration.

### Complication

I tried enabling this internally in Google, and I get the following exception during a coverage run:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/jacoco/agent/rt/internal_e5875b2/Offline
	at support.ImplicitForRemover.$jacocoInit(ImplicitForRemover.java)
	at support.ImplicitForRemover.main(ImplicitForRemover.java)
Caused by: java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_e5875b2.Offline
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 2 more
```

Again, there's no inherent reason (that I can see) why propagating the coverage bit to the host configuration would be wrong, so my guess is that something just needs to check `ctx.coverage_instrumented` and is not.

### Misc info

* Bazel version (output of `bazel info release`): Google internal release 2017.11.27-2

**Comment by iirina** [comment]
> I tried enabling this internally in Google, and I get the following exception during a coverage run

How did you try to enable this? From the error, it seems like not everything needed for coverage was loaded.

> there's no inherent reason (that I can see) why propagating the coverage bit to the host configuration would be wrong

The tests should be run in the target configuration. In the host configuration you have the tools you need for the build, and in target configuration the targets you want to run. You should have separate tests for the tools in the target configuration.

**Comment by tvolkert** [comment]
Thanks for the help!

> How did you try to enable this?

cl/178046334

> The tests should be run in the target configuration.

Yes, and they are, but alas, they need to launch the built Android or iOS app on the provisioned simulator, and the app needs to be built with the corresponding Android of iOS configuration -- thus the target configuration in the case of these tests is `--config=android_x86` or `--config-ios_x86_64`.  The test then launches the host-based tools executable, which is built in the host configuration.  If there were a way for Bazel to say "the target configuration is for the host CPU, and there's this *other* custom configuration (e.g. "device" config) that I need my app built in... then that would work too, but there's no way to express that in Bazel.

Alternatively, I know I could run the tests without a real app and fake out the app.  Unfortunately, doing so would mean providing a fake Android SDK, iOS SDK, and Dart VM (since once the app is started, the communication channel is over a protocol that's built into the Dart VM).  That amount of fakes would turn a 100 LOC test into a 10,000 LOC test ☹️  (and also make it *significantly* more fragile, given the API surface that would need to be faked).

**Comment by aj-michael** [comment]
At least for the Android case, I think you can get what you want if you build with --fat_apk_cpu and --android_crosstool_top instead of --config=android_x86 (which sets --cpu and --crosstool_top). The android target has a configuration transition when it goes into its deps attribute, that should not affect whatever implicit attribute the coverage tool is coming from. (although I admit I know very little about how the coverage tool is hooked up)

**Comment by tvolkert** [comment]
@aj-michael after having wrestled with getting coverage to work in host config for about a week, I think I'm gonna go with your suggestion instead. 😄 

FTR, the problem I was running into with enabling coverage in the host configuration was that it really messed with any Java host configuration tools.  Java coverage uses Jacoco, and the way it's currently wired up, Bazel will implicitly add Jacoco's JAR file to the classpath for any `java_binary` target when code coverage is enabled (the assumption being that Java code running in target config all goes through `java_binary`).  This seems a little dodgy, and when we propagate coverage to host config, it gets worse, because when we do that, it's not just `java_binary` targets that need Jacoco now, but also `java_plugin` targets (annotation processors) and some random other `java_library` targets that get manually invoked via `java -jar` (e.g. `ImplicitForRemover`).  If any of those tools don't have Jacoco added to their classpath, we get the `NoClassDefFoundError` in the OP.

What I've since realized I'm *really* looking for is multi-target configuration transitions.  My use case calls for:

* Host config: tools needed during build.
* Target config "A": My binary that is capable of deploying apps to iOS or Android emulators.
* Target config "B": Android or iOS, depending on the specific target.

In that world, I want to make sure that `bazel coverage` enables code coverage for "A", which should be no problem since "A" is not host config.  Alas, Bazel doesn't have the ability to express this setup (yet?), but the split configuration transitions afforded by `--fat_apk_cpu` (and `--ios_multi_cpus`?) kinda sorta get me there.
