### ISSUE TITLE
PATH passed through to genrule despite --experimental_strict_action_env

### ISSUE THREAD

**Issue by drigz** [bazelbuild/bazel#4239]
If I build a genrule with --experimental_strict_action_env, the genrule is executed with the same PATH as my shell. According to [the docs for --experimental_strict_action_env](https://docs.bazel.build/versions/master/command-line-reference.html#flag--experimental_strict_action_env):

> If true, Bazel uses an environment with a static value for PATH and does not inherit LD_LIBRARY_PATH or TMPDIR. Use --action_env=ENV_VARIABLE if you want to inherit specific environment variables from the client, but note that doing so can prevent cross-user caching if a shared cache is used.

Additionally, the docs for [Predefined "Make" Variables](https://docs.bazel.build/versions/master/be/make-variables.html#predefined_variables) say:

> The build system also provides a consistent PATH environment variable for genrules and tests which need to execute shell commands.

which suggests to me that Bazel is choosing the value of PATH, rather than just passing it through from the calling shell. 

### Expected behaviour

Either:
- actions get a static PATH when using --experimental_strict_action_env
- the documentation explains when --experimental_strict_action_env does not use a static PATH unless you pass --action_env=PATH=/bin:/usr/bin or similar 

### Repro

```
> echo > WORKSPACE
> echo > src.msg
> cat BUILD.bazel
genrule(
    name = "link",
    srcs = ["src.msg"],
    outs = ["out/src.msg"],
    cmd = "cp $< $@",
)
```

```
> bazel build --experimental_strict_action_env :link
...
INFO: Build completed successfully, 2 total actions
> bazel build --experimental_strict_action_env :link
...
INFO: Build completed successfully, 1 total actions   # ie successfully cached
> PATH=/asdfsadf:$PATH bazel build --experimental_strict_action_env :link 
...
INFO: Build completed successfully, 2 total actions   # ie not cached
```

If I run with -s I can see that the PATH is passed through to the genrule:

```
> PATH=/asdfadf:$PATH bazel build -s --experimental_strict_action_env :link                                                                                                                         
INFO: Analysed target //:link (0 packages loaded).
INFO: Found 1 target...
SUBCOMMAND: # //:link [action 'Executing genrule //:link']
(cd /usr/local/google/home/rodrigoq/.cache/bazel/_bazel_rodrigoq/7e37c45dd6a3d6ff2f057f9d44fb304b/execroot/__main__ && \
  exec env - \
    PATH=/asdfadf:/usr/local/google/home/rodrigoq/google-cloud-sdk/bin:/usr/local/google/home/rodrigoq/.nvm/versions/node/v7.7.4/bin:/usr/local/google/home/rodrigoq/bin:/usr/lib/google-golang/bin:/usr/local/buildtools/java/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/google/users/joeuser/aswb-sdk/tools:/usr/local/google/users/joeuser/aswb-sdk/platform-tools:/google/data/ro/users/mp/mpn/git-stuff:/usr/local/google/home/rodrigoq/.tmuxifier/bin:/opt/gradle/gradle-3.5/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; cp src.msg bazel-out/k8-fastbuild/genfiles/out/src.msg')
Target //:link up-to-date:
  bazel-genfiles/out/src.msg
INFO: Elapsed time: 0.317s, Critical Path: 0.09s
INFO: Build completed successfully, 2 total actions
```

I can work around this by commenting out `build --action_env=PATH` in /etc/bazel.bazelrc, or by overriding it with `--action_env=PATH=/bin:/usr/bin` on the command line.

### Environment info
* Operating System: Ubuntu 14.04
* Bazel version: 0.8.1

###  Possible duplicates
#577 - but this predates --experimental_strict_action_env
#3989 - but this is about C++ linking

**Comment by ulfjack** [comment]
The Debian package includes a bazelrc file that gets installed to /etc/ which sets --action_env=PATH, IIRC.

**Comment by ulfjack** [comment]
Ah, I see you found the bazelrc file.

**Comment by tybook** [comment]
I have found that this bug is _not_ present on macOS with versions `0.8.0` and `0.9.0`. Specific to Linux?

**Comment by drigz** [comment]
@tybook It occurs if /etc/bazel.bazelrc contains `--action_env=PATH` - does the macOS package have this?

In my opinion, `--experimental_strict_action_env` on the CLI should override `--action_env=PATH` in /etc/bazel.bazelrc, or if it doesn't its documentation should be changed.

**Comment by tybook** [comment]
Good call, the macOS package does not create that file. And I agree with you.
