### ISSUE TITLE
Clarify best practices for third-party dependencies

### ISSUE THREAD

**Issue by NicholasGorski** [bazelbuild/bazel#4241]
Currently the documentation for third-party dependencies suggests the best practice is to declare an external dependency, rather than vendor the code into the repository.

What is the justification for this preference? Google does not do this internally, and it makes the build dependent on the availability of things outside my own repository. I could see this being justified with a preference to simplicity or ease of use, but not justified with a preference to better hermeticity or availability (or if I need to apply patches).

Can this documentation or this issue be updated to clarify this decision? Or perhaps make the better practice conditional on the goal of the user. Thanks!

**Comment by shahms** [comment]
Bazel supports augmenting or changing external dependencies from the command line, making it relatively straightforward (although not easy) to build against local or system copies of those dependencies.  Vendoring dependencies into the source tree makes that much, much more difficult.  It similarly makes it much harder for dependent projects to to build against a common version of a shared dependency that isn't the one the vendored project chose.

**Comment by ittaiz** [comment]
Why? Can't you just vendor it two different versions and have the odd one
encode the version to the path?
You have to do it in a similar way even if it's an external repository

**Comment by ulfjack** [comment]
You can vendor it and declare it as a local_repository. That allows you to override it to somewhere else but still have all the code checked in.
