### ISSUE TITLE
Skylark API page is not available.

### ISSUE THREAD

**Issue by ttsugriy** [bazelbuild/bazel#4244]
### Description of the problem / feature request / question:

[Skylark language](https://docs.bazel.build/versions/master/skylark/language.html) page points at a [Skylark API page](https://docs.bazel.build/versions/master/skylark/skylark-overview.html) but it's not available.

**Comment by spomorski** [comment]
Fixed broken link. Fix will be up in 24 hours when the Bazel site is rebuilt.

**Comment by ttsugriy** [comment]
woohoo, thank you for such a quick fix!

**Comment by spomorski** [comment]
My pleasure :)
