### ISSUE TITLE
Undocumented change to remote_rest_cache HTTP API.

### ISSUE THREAD

**Issue by jacobstr** [bazelbuild/bazel#4246]
### New Remote Cache Prefixes (AC/CAS) are not Documented

The new prefixes in the HTTP API mandated by the remote_rest_cache have not been documented.
They were introduced in: c291726428a7caaa6024fdb06af285fbc68f63cb

I suppose the existing specification isn't well documented either. We've implemented our own backend that uses s3 to store artifacts via a thin golang wrapper that interacts with the s3 API. I'm somewhat able to reverse engineer the "modern" API by observing our access logs on the existing deployment of this thin wrapper.

Specifically: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/remote/README.md

### Environment info
* Ubuntu 16.04
* Bazel 0.8.1

**Comment by jacobstr** [comment]
It also feels unclear if this change was addressing a fundamental issue with the CAS of the cache ("we need to namespace actions separately because, due to <blah> they tend to evaluate to the same hash, when indeed they're different). 

Were there collisions prior to the change? Why was it necessary to distinguish between the "ac" and "cas"? 

As of now, my solution is to simply to reroute /og/route/prefix/<cas|ac>/ to the route handlers at /og/route/prefix which handled all of the GET/POST/PUT requests prior to this change.

**Comment by buchgr** [comment]
> The new prefixes in the HTTP API mandated by the remote_rest_cache have not been documented.

This change was mentioned in the 0.7.0 release notes. I agree we should update remote/README.md.

> Why was it necessary to distinguish between the "ac" and "cas"?

CAS stands for content addressable storage, meaning that an object is referenced by its content i.e. `hash(object)`. AC stands for action cache. In the action cache the metadata of a successfully executed action is referenced by the hash of the action definition.

A server being able to distinguish between what's what has a few advantages:
1. For the CAS, it can verify that contents and hash match to avoid poisoning the cache.
2. The bytes uploaded to the action cache refer to the `ActionResult` protobuf message of the remote execution API. A server can read the message and understand the relations between the uploaded blobs and implement garbage collection strategies on top of that. The server can also easily provide hit / miss statistics and so on.

I am sorry that this change caused you problems. I figured adding it to the release notes was good enough. I think this change is for the better though.
