### ISSUE TITLE
CI, bazel-watcher: failing with bazel 0.9.0 rc2

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4249]
**Blocking: https://github.com/bazelbuild/bazel/issues/3773**

Log: https://ci.bazel.io/job/Global/job/bazel-watcher/311/console

Ran as part of Bazel 0.9.0 rc2 test: https://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/release/533/Downstream_projects/

Binaries: https://releases.bazel.build/0.9.0/rc2/index.html

Example log:
```
[node=darwin-x86_64] ERROR: /Users/ci/workspace/Global/bazel-watcher-node=darwin-x86_64/WORKSPACE:69:1: Cannot redefine repository after any load statement in the WORKSPACE file (for repository 'com_github_golang_protobuf')
[node=darwin-x86_64] ERROR: Error evaluating WORKSPACE file
[node=darwin-x86_64] ERROR: error loading package 'external': Package 'external' contains errors
[node=darwin-x86_64] INFO: Elapsed time: 0.961s
[node=darwin-x86_64] FAILED: Build did NOT complete successfully (0 packages loaded)
[node=darwin-x86_64] FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by laszlocsomor** [comment]
TODO:
- repro the failure with Bazel 0.9.0 rc2
- try to repro with Bazel 0.8.1, see if it's failing with that too
  - if failing, then mark as non-blocker for #3773 
  - if not failing, bisect commits to find culprit

**Comment by buchgr** [comment]
I can confirm that it works with 0.8.1 and fails with 0.9.0 rc2. Bisecting.

**Comment by buchgr** [comment]
git bisect tells me that 337f19cc54e77c45daa1d5f61bf0a8d3daf8268f is the offending commit.

**Comment by buchgr** [comment]
I reverted the commit on my local branch and can confirm that bazel-watcher works without the commit.

**Comment by laszlocsomor** [comment]
See https://github.com/bazelbuild/bazel/issues/3773#issuecomment-348932061
Damien apparently already expected that change to cause problems. As I understand it, he planned to revert it anyway.

Jakob, can you revert that commit please?

**Comment by buchgr** [comment]
Yes sir!
