### ISSUE TITLE
Drop the JDK dependency

### ISSUE THREAD

**Issue by bjacob** [bazelbuild/bazel#425]
I believe that the vast majority of prospective Bazel users must be writing it off as soon as they see the JDK requirement. I'd like for Bazel to be successful and widely adopted and I can't see that happening with the JDK dependency.

**Comment by bjacob** [comment]
(That might imply switching implementation languages away from Java, which I understand is a huge task. It's just the reality that Java isn't a popular platform at the moment for open source projects in the wider world i.e. outside of big corporate infrastructures).

**Comment by damienmg** [comment]
Sorry but what is that myth about Java being a blocker for a "vast majority" of prospective Bazel users.

Switching more than 300Kloc is a big no-way.

**Comment by kchodorow** [comment]
We know that requiring a JDK is a heavy dependency, but as Damien mentioned, Bazel's codebase is large and mature and we don't want to [rewrite it](http://www.joelonsoftware.com/articles/fog0000000069.html).  It's possible in the future that we could only require the JRE, but honestly that's pretty far off.
