### ISSUE TITLE
bazel --client_debug should print server.pid location

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#4254]
We got a workspace into a strange state: the server process had been killed, but the client kept trying to connect to it. Don't know how to repro.

However, recovering from this was difficult, because
- we didn't know where bazel keeps the server pid
- when we did figure out that it's in the output_base, we couldn't run `bazel info` to find out the location of the output_base

We did discover `bazel --client_debug` from the documentation, but it didn't tell us how it finds the server. If it printed the absolute path to the server-pid.txt file it would have saved a lot of trouble.

**Comment by dahlstrom-g** [comment]
Incidentally maybe you can find it this way:
```
$ ls ~/.cache/bazel/*/*/server/server.pid.txt
```
