### ISSUE TITLE
ERROR: No toolchain found for cpu 'unknown'

### ISSUE THREAD

**Issue by qduan163** [bazelbuild/bazel#4258]
I build bazel-0.4.5, have the issue:(./compile.sh)
reference: https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/GUIDE.md

ERROR: No toolchain found for cpu 'unknown'. Valid cpus are: [
  arm,
  armeabi-v7a,
  x64_windows_msvc,
  s390x,
  ios_x86_64,

I had modify tools/cpp/cc_configure.bzl Line133,  _get_cpu_value
...
#"""Compute the cpu_value based on the OS name."""
return "arm"
...

more Log :
//------------------------------
+ /usr/lib/jvm/java-8-openjdk-arm64/bin/java -XX:+HeapDumpOnOutOfMemoryError -Xverify:none -Dfile.encoding=ISO-8859-1 -XX:HeapDumpPath=/tmp/bazel_k8Op9Tup -Djava.util.logging.config.file=/tmp/bazel_k8Op9Tup/javalog.properties -Dio.bazel.EnableJni=0 -jar /tmp/bazel_k8Op9Tup/archive/libblaze.jar --batch --install_base=/tmp/bazel_k8Op9Tup/archive --output_base=/tmp/bazel_k8Op9Tup/out --install_md5= --workspace_directory=/root/tf/bazel --nofatal_event_bus_exceptions build --ignore_unsupported_sandboxing --startup_time=329 --extract_data_time=523 --rc_source=/dev/null --isatty=1 --ignore_client_env --client_cwd=/root/tf/bazel --java_toolchain=//src/java_tools/buildjar:bootstrap_toolchain --host_java_toolchain=//src/java_tools/buildjar:bootstrap_toolchain --spawn_strategy=standalone --nojava_header_compilation --strategy=Javac=worker --worker_quit_after_build --ignore_unsupported_sandboxing --compilation_mode=opt --verbose_failures --javabase=/usr/lib/jvm/java-8-openjdk-arm64 --host_javabase=/usr/lib/jvm/java-8-openjdk-arm64 '--javacopt=-g -source 1.8 -target 1.8' --stamp --embed_label '0.4.5- (@non-git)' src:bazel
WARNING: /tmp/bazel_k8Op9Tup/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel_k8Op9Tup/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.
INFO: Loading package: src
INFO: Loading package: @bazel_tools//tools/cpp
INFO: Loading package: @local_config_xcode//
INFO: Loading package: @local_config_cc//
ERROR: No toolchain found for cpu 'unknown'. Valid cpus are: [
  arm,
  armeabi-v7a,
  x64_windows_msvc,
  s390x,
  ios_x86_64,
].
INFO: Elapsed time: 15.203s
+ fail 'Could not build Bazel'
+ local exitCode=2
+ [[ 2 = \0 ]]
+ echo

+ echo 'ERROR: Could not build Bazel'
ERROR: Could not build Bazel
+ exit 2
+ run_atexit_handlers 2
+ local exit_code=2
+ local failed=no
+ for handler in '${ATEXIT_HANDLERS}'
+ eval cleanup_tempdir_bazel_k8Op9Tup
++ cleanup_tempdir_bazel_k8Op9Tup
++ rm -rf /tmp/bazel_k8Op9Tup
+ for handler in '${ATEXIT_HANDLERS}'
+ eval cleanup_phasefile
++ cleanup_phasefile
++ '[' -f /tmp/bazel_k8Op9Tup/phase ']'
+ for handler in '${ATEXIT_HANDLERS}'
+ eval restore_saved_path
++ restore_saved_path
++ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ export BAZEL_OLD_PATH=
++ BAZEL_OLD_PATH=
+ for handler in '${ATEXIT_HANDLERS}'
+ eval cleanup_tempdir_bazel_aMwILhG5
++ cleanup_tempdir_bazel_aMwILhG5
++ rm -rf /tmp/bazel_aMwILhG5
+ trap - EXIT
+ '[' 2 -ne 0 ']'
+ exit 2

//-------------------------------
### Environment info
platform info: ARM -A53 , 2G DDR , 
Debian GNU/Linux 8 \n \l
Linux version 3.10.52 (huangjunmin@srv-pad-compile5) (gcc version 4.9.3 20150113 (prerelease) (Linaro GCC 4.9-2015.01-3) ) #1 SMP PREEMPT Thu Nov 16 09:34:08 CST 2017

* Bazel version (output of `bazel info release`):
0.4.5

question:
How can get the cpu info and set to bazel build ? 
What need modify to slove the issue?

**Comment by iirina** [comment]
> I had modify tools/cpp/cc_configure.bzl Line133, _get_cpu_value

Did you get the same error after this change?

> How can get the cpu info and set to bazel build ?

Bazel will try to automatically detec your CPU info, there is no way to specify it.

**Comment by qduan163** [comment]
uname -m
aarch64

**Comment by qduan163** [comment]
I had modified tools/cpp/cc_configure.bzl Line133, _get_cpu_value, 
yes, I got same error .

**Comment by qduan163** [comment]
reference: http://zhiyisun.github.io/2017/02/15/Running-Google-Machine-Learning-Library-Tensorflow-On-ARM-64-bit-Platform.html
I modified bazel source file to compatible with "aarch64" and build bazel pass. 
This issue can close.
