### ISSUE TITLE
android_resources rule type referenced in documentation, not documented

### ISSUE THREAD

**Issue by XperielIndigo** [bazelbuild/bazel#426]
In the android_binary and android_library documentation in bazel.io there are references to an `android_resources` rule. I can't find any documentation for this rule type in bazel.io.

Where do I find documentation on usage?

**Comment by damienmg** [comment]
Ok android_resources is I believe deprecated and should not be referenced in the documentation.

Assigning to Lukacs for triaging

**Comment by lberki** [comment]
Correct, android_resources is a legacy rule only in use within Google. Let me send out a change to remove it from the documentation.

(Thanks for noticing it with your sharp eye! :) )
