### ISSUE TITLE
Bazel 0.8.0 migration issue

### ISSUE THREAD

**Issue by aahmed-se** [bazelbuild/bazel#4260]
We are currently trying to move from bazel 0.7.0 to 0.8.0 for heron and having a error with shell script execution which works fine on 0.7.0

### Description of the problem / feature request / question:
The issue is during the execution of this rule
https://github.com/twitter/heron/blob/master/tools/rules/pex/BUILD

It seems the way we handle long terminal lines in linux is not longer working in 0.8.0 the problem does not appear in darwin , so it something specific to linux, and is related to bazel changes.

```
ERROR: /home/jenkins/test/heron/tools/rules/pex/BUILD:4:1: Bootstrapping pex //tools/rules/pex:pex_wrapper failed (Exit 126): bash failed: error executing command 
  (cd /home/jenkins/.cache/bazel/_bazel_jenkins/4aee62fbf194cfd9f33e35137c9b5465/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; 
        OUTDIR=$(cd bazel-out/host/bin/tools/rules/pex && pwd)
        # Workaround really long shebang lines breaking on linux:
        # Use a /tmp path, but keep the actual venv inside the bazel outdir.
        # Avoids having to worry about cleanup, even if sandboxing is off.
        TMPF=$(mktemp -d -t pex.XXXXX)
        ln -sf "$OUTDIR" "$TMPF"
        VENV="${TMPF}/venv"

        bazel-out/host/bin/external/virtualenv/virtualenv --no-download --quiet --clear "$VENV"
        PYTHON="$VENV/bin/python"

        $VENV/bin/pip install pex             --quiet --no-cache-dir --no-index --build bazel-out/host/bin/tools/rules/pex/pexbuild             --find-links $(dirname external/pex_src/file/pex-1.2.11.tar.gz)             --find-links $(dirname external/wheel_src/file/wheel-0.29.0.tar.gz)             --find-links $(dirname external/setuptools_src/file/setuptools-31.0.0.tar.gz)

        # Work around setuptools insistance on writing to the source directory,
        # which is discouraged by Bazel (and annoying)
        cp -r $(dirname tools/rules/pex/wrapper/setup.py) bazel-out/host/bin/tools/rules/pex/.pex_wrapper

        # Use the bootstrapped pex to build pex_wrapper.pex
        $VENV/bin/pex bazel-out/host/bin/tools/rules/pex/.pex_wrapper             --disable-cache --no-index -m pex_wrapper -o bazel-out/host/bin/tools/rules/pex/pex_wrapper.pex             --find-links $(dirname external/pex_src/file/pex-1.2.11.tar.gz)             --find-links $(dirname external/setuptools_src/file/setuptools-31.0.0.tar.gz)             --find-links $(dirname external/requests_src/file/requests-2.12.3.tar.gz)             --find-links $(dirname external/wheel_src/file/wheel-0.29.0.tar.gz)
    ')
/bin/bash: /home/jenkins/.cache/bazel/_bazel_jenkins/4aee62fbf194cfd9f33e35137c9b5465/execroot/__main__/tmp52e_d7d65d35d0518793/pex.LIWGE/venv/bin/pip: /home/jenkins/.cache/bazel/_bazel_jenkins/4aee62fbf194cfd9f33e35137c9b5465/ex: bad interpreter: No such file or directory
Target //scripts/packages:binpkgs failed to build
```

### If possible, provide a minimal example to reproduce the problem:
clone twitter heron repo and execute on an ubuntu machine with bazel 0.8.0
bazel build -c opt --config=ubuntu scripts/packages:binpkgs

### Environment info
* Operating System: ubuntu 16.04

* Bazel version (output of `bazel info release`): 0.8.0

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by benjaminp** [comment]
Probably a result of cfccdf1f6e93125d894ff40e0ccecaf20cc20ef5, which adds a TMPDIR to the default action environment. The sandbox tmpdir ends up being within the sandbox, so has a long path. If you actually want to use `/tmp` you should probably explicitly pass `-p /tmp` to `mktemp`.

**Comment by jmmv** [comment]
Given the age of this bug and the mentions to 0.7.0... is this still a problem?

**Comment by aahmed-se** [comment]
I implement a workaround so no sure if still an issue

**Comment by jmmv** [comment]
Considering fixed then. Please get back to this if you ever happen to try without your workaround.
