### ISSUE TITLE
Support portrait mode for documentation

### ISSUE THREAD

**Issue by marcohu** [bazelbuild/bazel#4262]
I'm using my monitors in portrait mode. Each provides 1200px horizontally. Unfortunately the Bazel online documentation [(https:docs.bazel.build)](https:docs.bazel.build) does not play nice with this setup.

The actual content is displayed below the vertical navigation bar which makes navigation so much harder (see attached screenshot).

If I make the window only a few pixels wider, the page displays as expected, but this defeats the purpose of the tiling window manager I use.

It's possible to fix the issue on the client side with tools like Stylish, but I would appreciate if such action wouldn't be necessary.

![1200px](https://user-images.githubusercontent.com/487062/33804828-65287b6e-ddad-11e7-98f3-5ebe5a0dcab3.png)

**Comment by marcohu** [comment]
If I increase the window width by 11px, the content does not reflow. Given that there are very generous white space margins, I would suggest that these are simply made smaller if the horizontal space is limited.

**Comment by jin** [comment]
Sent out a fix in #4263

**Comment by marcohu** [comment]
That will do. Thanks very much for your very quick action!
