### ISSUE TITLE
Skylark Java methods should use a JavaToolchainProvider, not a ConfiguredTarget

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#4269]
Currently, several methods available in the SkyLark Java API require a JavaToolchainProvider, but access it by requiring users to pass a ConfiguredTarget that provides the JavaToolchainProvider.

These methods need to be reworked to accept either form, so that these methods can continue to work when JavaToolchainProvider is accessed via the toolchain resolution process.

Possible the JavaRuntimeInfo also need to be handled similarly.

**Comment by katre** [comment]
Methods to fix for JavaToolchainProvider:

- [java_common.create_provider](https://github.com/bazelbuild/bazel/blob/30f6d44ff99cc60446e6ae1f7d4c9818351b918d/src/main/java/com/google/devtools/build/lib/rules/java/JavaSkylarkCommon.java#L52)
- [java_common.compile](https://github.com/bazelbuild/bazel/blob/30f6d44ff99cc60446e6ae1f7d4c9818351b918d/src/main/java/com/google/devtools/build/lib/rules/java/JavaSkylarkCommon.java#L268)
- [java_common.default_javac_opts](https://github.com/bazelbuild/bazel/blob/30f6d44ff99cc60446e6ae1f7d4c9818351b918d/src/main/java/com/google/devtools/build/lib/rules/java/JavaSkylarkCommon.java#L520)
- [JavaToolchainSkylarkApiProvider](https://github.com/bazelbuild/bazel/blob/30f6d44ff99cc60446e6ae1f7d4c9818351b918d/src/main/java/com/google/devtools/build/lib/rules/java/JavaToolchainSkylarkApiProvider.java#L26)

**Comment by meisterT** [comment]
@katre what's the status of this work?

**Comment by katre** [comment]
Nothing concrete has happened. Unassigning myself because I will not be able to pick this up. Feel free to close it if this doesn't seem like useful work, although I think it makes sense as an API surface.

**Comment by comius** [comment]
It seems that all the listed methods already accept JavaToolchainProvider:
- java_common.create_provider - now [JavaInfo constructor](https://cs.opensource.google/bazel/bazel/+/389e0da1fedc7543e243267a1052f9209b4dd395:src/main/java/com/google/devtools/build/lib/starlarkbuildapi/java/JavaInfoApi.java;l=240)  doesn't need toolchains
- [java_common.compile](https://cs.opensource.google/bazel/bazel/+/389e0da1fedc7543e243267a1052f9209b4dd395:src/main/java/com/google/devtools/build/lib/starlarkbuildapi/java/JavaCommonApi.java;l=217) uses `JavaToolchainT` and `JavaRuntimeT`
- [java_common.default_javac_opts](https://cs.opensource.google/bazel/bazel/+/389e0da1fedc7543e243267a1052f9209b4dd395:src/main/java/com/google/devtools/build/lib/starlarkbuildapi/java/JavaCommonApi.java;l=420) uses `JavaToolchainT`
