### ISSUE TITLE
Dead installer link in install.html

### ISSUE THREAD

**Issue by bjacob** [bazelbuild/bazel#427]
This page,
http://bazel.io/docs/install.html

tells the user to download a Bazel installer from
https://github.com/bazelbuild/bazel/releases

but that link says there's nothing there.

**Comment by damienmg** [comment]
This is a duplicate of #403 

You can use the release candidate until we do the full release (hopefully tomorrow), here the link to current candidate:

https://storage.googleapis.com/bazel/0.1.0/rc2/index.html
