### ISSUE TITLE
Error encountered while dealing with WORKSPACE file after executing bazel build command

### ISSUE THREAD

**Issue by airmak** [bazelbuild/bazel#4273]
I am trying to build a Tensorflow Model using bazel. When I type the command 
`bazel build -c opt lm_1b/...`, the following error pops up:
```
ERROR: no such package 'external': Error encountered while dealing with the WORKSPACE file: C:\users\cogneuro\desktop\lm_1b\WORKSPACE (Access is denied)
ERROR: no such package 'external': Error encountered while dealing with the WORKSPACE file: C:\users\cogneuro\desktop\lm_1b\WORKSPACE (Access is denied)
INFO: Elapsed time: 1.744s
FAILED: Build did NOT complete successfully (0 packages loaded)
```

I have already checked the permissions on the file, and there are no constraints. Any help would be appreciated.

**Comment by airmak** [comment]
@damienmg

**Comment by laszlocsomor** [comment]
- Which Bazel version are you using?
- Which Windows version?
- What's in the `WORKSPACE` file?

**Comment by airmak** [comment]
@laszlocsomor 
I am using Bazel 0.8.1, and the `WORKSPACE` file is just an empty directory, even when I delete the `WORKSPACE` file, the same error outputs

**Comment by laszlocsomor** [comment]
@airmak :
> `WORKSPACE` file is just an empty directory

It should be an empty text file, not an empty directory.

**Comment by laszlocsomor** [comment]
In other words, try this in a Windows Command Prompt:
```
md c:\tmp\hello
cd c:\tmp\hello
echo. > WORKSPACE
c:\path\to\bazel.exe build
```

This should produce similar output:
```
c:\tmp\hello>c:\work\bazel-releases\0.8.1\bazel.exe build
..............
DEBUG: C:/users/laszlocsomor/appdata/local/temp/_bazel_laszlocsomor/bddkywhn/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/laszlocsomor/appdata/local/temp/_bazel_laszlocsomor/bddkywhn/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables,eg. VS140COMNTOOLS
DEBUG: C:/users/laszlocsomor/appdata/local/temp/_bazel_laszlocsomor/bddkywhn/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
INFO: Analysed 0 targets (4 packages loaded).
INFO: Found 0 targets...
INFO: Elapsed time: 13.628s, Critical Path: 0.02s
INFO: Build completed successfully, 1 total action
```

**Comment by airmak** [comment]
Turns out the only problem was that I did not have file extensions turned on, so it was fetching for a WORKSPACE file when it was actually called WORKSPACE.txt. Thanks for your help

**Comment by hack-r** [comment]
How does one replicate this solution? What exactly do you by turning on file extensions?

**Comment by kryan225** [comment]
@airmak could you please show how you turned on file extensions?
