### ISSUE TITLE
Loading a declared provider from a remote workspace does not work

### ISSUE THREAD

**Issue by sergiocampama** [bazelbuild/bazel#4283]
### Description of the problem / feature request / question:

When applying an aspect from an external workspace, which reads a declared provider defined in the main workspace, bazel will not detect the provider as being present on the target. More info on the repro case.

### If possible, provide a minimal example to reproduce the problem:

https://github.com/sergiocampama/bazel_provider_bug

### Environment info
* Operating System:

macOS High Sierra 10.13

* Bazel version (output of `bazel info release`):

release 0.8.1-homebrew

###  Have you found anything relevant by searching the web?

No.

### Anything else, information or logs or outputs that would be helpful?

More info on the repro case.

**Comment by sergiocampama** [comment]
@dslomov FYI

**Comment by dslomov** [comment]
This must be the same as https://github.com/bazelbuild/bazel/issues/3493
