### ISSUE TITLE
JavaInfo should expose `transitive_full_compile_jars`

### ISSUE THREAD

**Issue by pcj** [bazelbuild/bazel#4297]
For some JVM languages (kotlin), we need access to the transitive set of original "full" (non-ABI) jars.  For example consider this code snippet that attempts to build a classpath:

```python
    jars = depset()
    # Populate from (transitive, pretty please) java dependencies.  
    for dep in ctx.attr.java_deps:
        if java_common.provider in dep:
            info = dep[java_common.provider]
            # Here's what we have currently
            jars += info.full_compile_jars
            # Here's what we'd like to do
            jars += info.transitive_full_compile_jars
```

cc @iirina Thanks in advance for considering this!

https://github.com/pubref/rules_kotlin/issues/47

https://github.com/pubref/rules_kotlin/pull/41

**Comment by cushon** [comment]
> For some JVM languages (kotlin), we need access to the transitive set of original "full" (non-ABI) jars. 

Why is this needed? Is it related to bazelbuild/bazel#4549?

**Comment by iirina** [comment]
Please reopen if you still consider this is needed.
