### ISSUE TITLE
Mention changed file with `--verbose_explanations`

### ISSUE THREAD

**Issue by nelhage** [bazelbuild/bazel#4302]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I have a mid-sized C++ codebase. I'd like to understand which header files are commonly being changed that require rebuilds of the ~entire codebase. I added `build --explain=bazel.log --verbose_explanations` to my `.bazelrc`, in the hopes of consulting `bazel.log` after rebuilds to determine which header change(s) necessitated the full rebuild.

However, the log file is just full of information like
```
Executing action 'Compiling common/counters.cc': One of the files has changed.
```
which doesn't tell me the information I actually want -- *which* dependency file changed?

Would it be possible (probably only under `--verbose_explanations`) for bazel to log *which* file has changed, or maybe a subset of them, if an exact list is too verbose or expensive somehow?

### Environment info
* Operating System:
Linux Ubuntu 16.04

* Bazel version (output of `bazel info release`):
```
release 0.8.0
```

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by benjaminp** [comment]
In general, this isn't possible because the code that emits this explanation is simply comparing the saved aggregated hash of all the inputs the last time the action was built with the aggregated hash of the current inputs. `--verbose_explanations` would have to enable some extra tracking.

**Comment by ulfjack** [comment]
That's right. We dropped this feature a couple years ago when we moved to a more condensed action cache on-disk representation.

In the rare cases where I've had to debug such issues I've been using a patched Bazel binary, see [1]. That change is technically more powerful than --explain, but it's somewhat difficult to read the output it generates. I think --explain is basically dead, but maybe we can put something like this in instead.

[1] https://github.com/ulfjack/bazel/tree/ulfjack-debug-skyframe

**Comment by Globegitter** [comment]
Just running into this scenario also and while it would be very useful to have some way of getting this information directly it is at least possible with the `experimental_execution_log_file` flag combined with the quite new parser: https://github.com/bazelbuild/bazel/tree/master/src/tools/execlog, making it possible to diff what exactly has changed between two builds.

**Comment by meisterT** [comment]
We currently have no way to add this information to `--explain` which doesn't add too much costs to the builds. Given that there is a way with the execution log to get the information across multiple builds, I am closing this issue.
