### ISSUE TITLE
Skylark: cfg="data" is deprecated, but you're forced to use it for attributes named "data"

### ISSUE THREAD

**Issue by tvolkert** [bazelbuild/bazel#4316]
https://github.com/bazelbuild/bazel/blob/076977e019ebcb8b822e7727d292636fadcafcca/src/main/java/com/google/devtools/build/lib/analysis/Runfiles.java#L1012

That check means that any attributes named data but configured for either the `target` or `host` configurations will cause the build to fail:

```
Caused by: java.lang.IllegalStateException: /.../BUILD:<line>:<column>: <rule> attribute data is not configured for the data configuration
	at com.google.devtools.build.lib.analysis.RuleContext.checkAttribute(RuleContext.java:1028)
	at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisites(RuleContext.java:718)
	at com.google.devtools.build.lib.analysis.Runfiles$Builder.getPrerequisites(Runfiles.java:1165)
	at com.google.devtools.build.lib.analysis.Runfiles$Builder.addDataDeps(Runfiles.java:1012)
```

I'm told that new Skylark rules should not be using the `data` configuration, as it's deprecated and exists merely for legacy reasons.  If that's the case, we shouldn't be forcing users to use it for attributes that happened to be named "data".

@laurentlb

**Comment by ittaiz** [comment]
@laurentlb is this true that it's needed? because now there is a failure if you run with all incompatible flags

**Comment by c-parsons** [comment]
@ittaiz : is it true that **what's** needed?  (What is the "it" in your sentence?) I would love to help but don't understand :)

FWIW this bug looks out of date. I believe the requirement of the "data" attribute being cfg="data" was removed in 475d91a2b9314e6803aba5da83156712af63f837.

**Comment by ittaiz** [comment]
Sorry for the confusion. I was referring exactly to the requirement. If it’s removed then probably a good idea to close it. Thanks for the quick response!

**Comment by laurentlb** [comment]
`cfg = "data"` is going away (cc @gregestren).
I think it's now a no-op and it shouldn't be used at all.
