### ISSUE TITLE
Please open source //tools/build_rules:build_test.bzl

### ISSUE THREAD

**Issue by bcsgh** [bazelbuild/bazel#4321]
The docs include a reference to `//tools/build_rules:build_test.bzl`, which is not publicly available, in one of the examples.

The reference:
https://github.com/bazelbuild/bazel/blob/7cc8efe44a167d818deb77e53f12cecc15b4e4aa/src/main/java/com/google/devtools/build/docgen/templates/be/functions.vm#L42

Where that file would be:
https://github.com/bazelbuild/bazel/tree/7cc8efe44a167d818deb77e53f12cecc15b4e4aa/tools/build_rules

Ideally, this build extension should be open sourced. Or, failing that, the example in the docs should be updated to use something that is publicly available.

* Operating System: n/a
* Bazel version: docs at head

**Comment by aehlig** [comment]
That part of the documentation indeed refers to a `.bzl` that exists only google-internally. So we should either open-source the file or change the example in the documentation. As it only serves as example for the load statement, low priority though.

**Comment by davidstanke** [comment]
Let's change the example. Assigning to docs.

**Comment by spomorski** [comment]
Addressed in pull request [4694](https://github.com/bazelbuild/bazel/pull/4694).

**Comment by laurentlb** [comment]
I thought using a realistic-looking example would work better. But maybe not.

**Comment by spomorski** [comment]
Since this is only an example of a load statement, I think a generic one is
pretty self-explanatory. It's not code that users would copy-and-paste
verbatim into their BUILD files.

What would you rather change it to if not a generic example?

**Comment by laurentlb** [comment]
Go ahead with your change.

I didn't expect the example to confuse users, but apparently I was wrong.
