### ISSUE TITLE
ctx.actions.write does not write the last line

### ISSUE THREAD

**Issue by lightyang** [bazelbuild/bazel#4324]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
`ctx.actions.write` seems to always drop the last line in the file content

### If possible, provide a minimal example to reproduce the problem:
Using this [example](https://github.com/bazelbuild/examples/blob/master/rules/executable/executable.bzl). Only `#!/bin/bash` shows up in the output.

### Environment info
* Operating System:
Ubuntu 16.04

* Bazel version (output of `bazel info release`):
`c0aa1b7a6fd694b167b2feb6f31b9ad084df4481`

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by aehlig** [comment]
Took a stock `Ubuntu 16.04.3 LTS`, built bazel at c0aa1b7a6fd. And tested the example. It worked as expectd: `bazel build :my_rule` produced a file with the expected content and `bazel run :my_rule` did output `Hello!`.

Closing as non-reproducible.
