### ISSUE TITLE
Release - January 2018 - Target RC date: 2017-01-02 - name: 0.10.0

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4325]
Release tracking bug for January 2018:

- Target date for RC1 cut should be 2nd of January (first business day of January 2018)
- Name: 0.10.0

Previous release was 0.9.0:
- https://github.com/bazelbuild/bazel/issues/3773
- release manager was @laszlocsomor

**Comment by laszlocsomor** [comment]
Assigning to @iirina , I think you've been Release Manager the longest time ago.

**Comment by aehlig** [comment]
Isn't this a duplicate of #3958?

**Comment by laszlocsomor** [comment]
You're right, it is. Closing this one.
