### ISSUE TITLE
Bazel pulling corrupt jar from Google Maven on 0.9.0

### ISSUE THREAD

**Issue by izzyleung** [bazelbuild/bazel#4328]
### Description of the problem / feature request / question:
When bazel is trying to pull the jar with the following artifactId: `com.android.support:support-annotations:27.0.2`, which supposed to have the sha1: `0b9ef4342c934a1a8b107506273dc8061662a322`, it will pull a corrupt jar, with the sha1: `5cde4b7a94e85a7f5da362c84b4ff10be7c5c8cd`, __every single time__ this morning after downloading the `0.9.0` release from Homebrew on macOS Sierra 10.12.6.

There was no such problem last night while using bazel 0.8.1.

Could it be a network issue, since I have not tested this on other network environment.
Or could it be the download logic?

### If possible, provide a minimal example to reproduce the problem:
https://gist.github.com/izzyleung/0e887ae56fbaf630e6a393ffff183436

Just run: `bazel build //:android`

### Environment info
* Operating System:
macOS Sierra 10.12.6

* Bazel version (output of `bazel info release`):
`release 0.9.0-homebrew`

**Comment by aj-michael** [comment]
Hi @izzyleung , what was the solution here?

**Comment by izzyleung** [comment]
It was possibly due to a wield network issue, I cannot reproduce this anymore.

The solution was just switch to another network environment.
