### ISSUE TITLE
Sandboxing isn't supported on Google Container Engine

### ISSUE THREAD

**Issue by ekuefler** [bazelbuild/bazel#433]
When trying to run Bazel builds in a container running on [Google Container Engine](https://cloud.google.com/container-engine/docs/), I get the "sandbox not supported" message:

```
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
```

As far as I can tell, the node running the container meets the [criteria](http://bazel.io/docs/bazel-user-manual.html#sandboxing) to support sandboxing:

```
root@gke-corp-849e9a2e-node-biid:~# uname -r
3.16.0-0.bpo.4-amd64
root@gke-corp-849e9a2e-node-biid:~# grep CONFIG_USER_NS /boot/config-3.16.0-0.bpo.4-amd64 
CONFIG_USER_NS=y
```

The fact that it's running inside a container on the node complicates things, but I don't think that's the issue since sandboxing works OK when I run the same container on my workstation.

**Comment by philwo** [comment]
Is this Debian Linux? You might be hitting the "user namespace are disallowed for regular users by default" restriction they built in:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=712870
   * namespaces: Enable USER_NS (Closes: #712870)
     - Restrict creation of user namespaces to root (CAP_SYS_ADMIN) by
       default (sysctl: kernel.unprivileged_userns_clone)

You can enable user namespace for normal users on Debian systems via the following command:
sudo sysctl kernel.unprivileged_userns_clone=1

If it works, you can make it persistent via:
echo 'kernel.unprivileged_userns_clone = 1' | sudo tee /etc/sysctl.d/99-enable-user-namespaces.conf

If it still doesn't work, it may be a restriction that Google Container Engine imposes on its users due to security concerns about the feature.

You can check whether the basic feature works using the command: unshare -U
(The unshare tool comes with recent versions of util-linux).

The output would look similar to this:
philwo@philwo-bazel-debian81:/etc/sysctl.d$ unshare -U
nobody@philwo-bazel-debian81:/etc/sysctl.d$

If that fails with an "Operation not permitted" error, next step would be to ask the Container Engine people about it.

**Comment by ekuefler** [comment]
Yeah, looks like it's based on Debian Wheezy. `unshare` seems to work but it's using a much older version - the man page is dated Oct 2008 (my local machine's is July 2014), and it doesn't support the -U flag or a way to unshare the user namespace. `unshare ls` runs without reporting any problems though.

Does Bazel invoke `unshare` directly or is it just using the same mechanism (in which case util-linux being out of date isn't necessarily the root problem).

**Comment by philwo** [comment]
Bazel does not depend on the "unshare" tool provided by util-linux - it just uses the same mechanism, calling the unshare function provided by glibc.

As a quick test whether it works or not, you can use this C program:

```c
#define _GNU_SOURCE
#include <sched.h>
#include <stdio.h>
int main(int argc, char *argv[]) {
  if (unshare(CLONE_NEWUSER) != 0) {
    perror("unshare");
    return 1;
  }
  printf("OK\n");
  return 0;
}
```

Save it as "unshare.c", compile via "gcc -o unshare unshare.c" and run it.

One of the following should happen:

philwo@philwo-bazel-debian81:~$ ./unshare 
OK

Or:

philwo@philwo-bazel-debian81:~$ ./unshare 
unshare: Operation not permitted

If it fails, it would be interesting if it works when run via "sudo", or if it still fails.

**Comment by ekuefler** [comment]
OK, so it is related to running inside of a container somehow. Your program prints "OK" on the node host, but gives "Operation not permitted" inside of the container. I can also do "unshare -U" inside of the container and get operation not permitted. I can't run it under sudo since sudo isn't installed on the Debian image, but it shouldn't matter since I'm root in the container anyways.

But there is still something weird about the GKE environment, because when I run the same container on my desktop unshare works inside of it, even if the container isn't privileged. So to summarize:

```
# On GKE:
root@gke-corp-849e9a2e-node-9g7m:~/erik# docker run -it --entrypoint /bin/bash mycontainer
root@b096897cf6d6:/# unshare -U
unshare: unshare failed: Operation not permitted

# On Local ubuntu:
erik@erik$ docker run -it --entrypoint /bin/bash mycontainer
root@c7704e917af6:/# unshare -U
$ 

```

Any idea why unshare would fail in a container on one host but not another when both hosts support unshare and I have root on both?

**Comment by bsilver8192** [comment]
It sounds to me like it's the Debian patch that disables user namespaces for unprivileged users by default @philwo mentioned. What does `cat /proc/sys/kernel/unprivileged_userns_clone` say on both machines?

**Comment by ekuefler** [comment]
Aha, looks promising:

```
# Local Ubuntu
erik@erik:~ $ cat /proc/sys/kernel/unprivileged_userns_clone
cat: /proc/sys/kernel/unprivileged_userns_clone: No such file or directory
# GKE
root@gke-corp-849e9a2e-node-fhp8:~# cat /proc/sys/kernel/unprivileged_userns_clone 
0
```

And it does look like it works after I run `sudo sysctl kernel.unprivileged_userns_clone=1` on the host and shutdown the bazel server in the container. I'll check with the GKE team about enabling this by default or at least allowing me to customize the images in some way. Thanks!

**Comment by ekuefler** [comment]
To follow up on this one, I checked in with GKE support and they had security concerns about enabling that kernel flag by default. They don't yet have a mechanism for configuring cluster nodes automatically (it's being worked on), so the best option is a script that's run manually whenever nodes are created to twiddle the flag. Mine looks like this:

```
for node in $(kubectl get no | grep <my-cluster> | sed "s/ .*//"); do
  gcloud compute ssh $node --command="sudo sysctl kernel.unprivileged_userns_clone=1"
done
```

So I don't think there's anything left here on the Bazel side.

**Comment by prattmic** [comment]
It would be helpful to mention the kernel.unprivileged_userns_clone sysctl somewhere in the documentation, such as [here](http://bazel.io/docs/bazel-user-manual.html#sandboxing). It took me quite a while to find this bug.

**Comment by damienmg** [comment]
Sorry catching up.

@mattmoor can we get more background on the GKE side about the security concerns? It would be nice if we could provide image in GKE that "Just Work" for build with bazel

**Comment by damienmg** [comment]
(Also reopening as a documentation issue)

**Comment by mattmoor** [comment]
@damienmg One question is: what are the docker/kernel versions on the workstation/node?  Container Engine just switched from 1.6.2 to 1.8.3

If it isn't a Docker client thing, then I certainly don't know enough about Kubernetes manipulation of user namespaces to help.

**Comment by damienmg** [comment]
It's a kernel setup thing (of the GCE instance I guess), do you know who to ask?

Who could probably come up with some nicer thing with remote execution though (in which all action are sandboxing in a docker image).
