### ISSUE TITLE
java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by bcsgh** [bazelbuild/bazel#4332]
With the following in my WORKSAPCE 

    new_http_archive(
        name = "eigen",
        strip_prefix = "eigen-eigen-5a0156e40feb",
        urls = [
          "https://bitbucket.org/eigen/eigen/get/3.3.4.tar.gz",  # current as of 2017/12/19
          # "file:///home/${USER}/Downloads/eigen-3.3.4.tar.gz",  ## NOTE this on the other hand works.
        ],
        sha256 = "4286e8f1fabbd74f7ec6ef8ef31c9dbc6102b9248a8f8327b04f5b68da5b05e1",
        build_file = "BUILD.eigen",
    )

I get the following error:

    $ bazel test ...
    ERROR: ${ROOT}/src/BUILD:51:1: no such package '@eigen//': Error downloading [https://bitbucket.org/eigen/eigen/get/3.3.4.tar.gz] to ${HOME}/.cache/bazel/_bazel_bcsgh/bfebe506d6f9460c8b8d877b99f90bfa/external/eigen/3.3.4.tar.gz: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty and referenced by '//my:code'
    ERROR: Analysis of target '//my:test' failed; build aborted: no such package '@eigen//': Error downloading [https://bitbucket.org/eigen/eigen/get/3.3.4.tar.gz] to ${HOME}/.cache/bazel/_bazel_bcsgh/bfebe506d6f9460c8b8d877b99f90bfa/external/eigen/3.3.4.tar.gz: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

### Environment info
* Operating System:
4.13.0-17-generic #20-Ubuntu SMP

* Bazel version (output of `bazel info release`):
$ bazel info release
release 0.9.0

###  Have you found anything relevant by searching the web?
https://github.com/bazelbuild/rules_docker/issues/183
https://groups.google.com/forum/#!searchin/bazel-discuss/trustAnchors%7Csort:date/bazel-discuss/VudWovEKU_4/zNwKTaHpAgAJ

**Comment by aehlig** [comment]
I couldn't reproduce the issue with bazel 0.9.0 release on Ubuntu 16.0.4. But your example seems to be part of a bigger project; can you find a (preferrably minimal) reproduction example that you can share completely? Thanks.

**Comment by bcsgh** [comment]
https://github.com/bcsgh/stl-to-ps/blob/master/WORKSPACE#L45

**Comment by aehlig** [comment]
I still cannot reproduce the issue. The error message, however, indicates an error in the setup of your ca certificates for java (no single root certificate declared as trusted).

So closing for now. Feel free to reopen with precise reproducition instructions if the error persists in a setting where the jvm you're using can connect to the respective site via https.

It is a different question whether we should check for ssl certificates at all, if we already have a precise hash as base of our trust; but this is a different feature request and a new issue should be filed, if this is need.

**Comment by bcsgh** [comment]
I can reproduce this consistently in the only environment I have available to test it in. In fact I can't make it not happen. Unfortunately I have zero experience debugging Java so I don't know how to check if "the jvm [I'm] using can connect to the respective site via https." What I do know is that I haven't seen this sort of error from anything else (and I would assume at least something I'm using uses Java and https).

Do you have any suggestions for steps I could do that would give you more information to work from?

As to your "different question", I know what most of those words are and that sounds plausibly useful, but I don't know enough about what you are suggesting to file an FR.

**Comment by schlueter** [comment]
```
$ sudo apt-get install ca-certificates-java
$ sudo update-ca-certificates -f
$ bazel shutdown
```
Fixed this issue for me.

**Comment by bcsgh** [comment]
FWIW: this because Eigen is now available via a git mirror, I now have a viable workaround in my specific case.

https://github.com/bcsgh/stl-to-ps/commit/30d138f752831de4d3a3b20b6b15af8a6561cda1#diff-09498dbadf45966909850dc8a47ebb13
