### ISSUE TITLE
runfiles library: support enumerating runfiles under a directory [blocking: #3865]

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4334]
Feature request: some function that allows enumerating all runfiles under a directory.

Idea: support maybe a glob-like syntax?

**Comment by laszlocsomor** [comment]
This is a sub-task of https://github.com/bazelbuild/bazel/issues/3865.

**Comment by laszlocsomor** [comment]
Update: this issue is still on my radar, but P2 is appropriate and plenty of P1s are also on my plate. I don't expect to fix this issue before end of Q2, and it may have to wait even more.

**Comment by laszlocsomor** [comment]
Dropping to P4 for now. I haven't seen any demand for this feature. It would be nice to have, but there are more important things to work on.

**Comment by deannagarcia** [comment]
I see this issue was closed as complete, did it ever get implemented?

I have a use case where my `sh_binary` depends on files generated by another rule. The filenames are known before runtime so I can list them out, but I will have to manually keep the list of files in sync when we want to make changes.

**Comment by fmeum** [comment]
This hasn't been implemented yet. In languages with real filesystem abstractions (Java's `FileSystem`, Go's `fs.FS`), I would see value in adding e.g. glob support to the runfiles libraries that works across platforms.

With Shell, it's hard so come up with an abstraction that works well for every use case.

@deannagarcia Do you also have to support Windows? If not, I would recommend looking up a single runfile, walking up to a common parent directory and just applying `find` to that.
