### ISSUE TITLE
CROSSTOOL is not found if the build file is called BUILD.bazel

### ISSUE THREAD

**Issue by pmuetschard** [bazelbuild/bazel#4339]
### Description of the problem / feature request / question:

Follow along with the following tutorial: https://github.com/bazelbuild/bazel/wiki/Yet-Another-CROSSTOOL-Writing-Tutorial
**but** create `BUILD.bazel` files instead of `BUILD` files. 

Even after creating the empty CROSSTOOL file, you will still get the following error:
```
The crosstool_top you specified was resolved to '//toolchain:emscripten',
which does not contain a CROSSTOOL file.
```

### Environment info
* Operating System:
Only tried Windows

* Bazel version (output of `bazel info release`):
Only tried 0.8.1

**Comment by rongjiecomputer** [comment]
@pmuetschard I hit that bug as well. This is because "BUILD" string is hard-coded at https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/cpp/CrosstoolConfigurationLoader.java;l=206?q=%5C(%5C%22BUILD%5C%22%5C)

**Comment by mhlopko** [comment]
Nice catch. But since there's a workaround (to rename the BUILD.bazel to BUILD) and toolchain selection will be rewritten in 2018, only assigning P3.
Thanks!
