### ISSUE TITLE
Android multi-arch support

### ISSUE THREAD

**Issue by mrdomino** [bazelbuild/bazel#434]
At least it'd be useful to have i386 (for device emulators and those rumoured x86 Android devices), probably also armeabi for super-old pre-v7a devices, and at that point it seems like you might as well do it the fully general way but there's nothing else I can think of needing.

One idea that comes to mind is using `make-standalone-toolchain.sh` to dump a toolchain into bazel-genfiles or something. Or if that's too hard/slow/annoying/whatever, setting up a link to a pre-generated toolchain rather than an `android_ndk_repository`.

**Comment by ahumesky** [comment]
There are still things to clean up, but multi-arch is supported today:

~/bazel$ bazel build examples/android/java/bazel:hello_world --fat_apk_cpu=armeabi-v7a,armeabi,arm64-v8a,x86,x86_64,mips,mips64

A crosstool for the NDK is generated and placed in \<workspace>/bazel-\<workspace>/external/\<android_ndk_repository name>/BUILD

**Comment by mrdomino** [comment]
It'd also be good to have support for the other parameters make-standalone-toolchain.sh -- most significantly STL version.

**Comment by ahumesky** [comment]
We're working to enable selecting the STL version to use, it should be available in a few days.

**Comment by mrdomino** [comment]
Yay, thanks!

**Comment by ahumesky** [comment]
In the meantime, you can manually change the STL implementation files by changing these filegroups:
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/android/android_ndk_cc_toolchain_template.txt#L34-L42
