### ISSUE TITLE
Skylark support for proto3

### ISSUE THREAD

**Issue by nclinger** [bazelbuild/bazel#4342]
Are there any plans to support proto3 in either the python based Skylark or the Go implementation?

**Comment by mhlopko** [comment]
I'd advice you to ask this question on bazel-discuss, we try to keep github issues only for bugs and feature requests. Thank you for your understanding.

**Comment by nclinger** [comment]
Well, let me change this to a feature request then since I haven't seen anybody else request this yet. :)

**Comment by mhlopko** [comment]
What exactly are you requesting? :) What do you want to do with protos and Skylark?

**Comment by nclinger** [comment]
I have services that are configured via text proto files that live by the service. Some of the fields in the proto are required at build time (e.g. the service name). It would be great to either have native support for duck typing from proto to Skylark structs or to enable consuming a proto by a Skylark function.

**Comment by meisterT** [comment]
This not being worked on, closing.
