### ISSUE TITLE
--all_incompatible_changes causes failures in bazel internal skylark code

### ISSUE THREAD

**Issue by ianthehat** [bazelbuild/bazel#4346]
I tried to turn it on --all_incompatible_changes for rules_go and it broke both travis and jenkins with the same error as shown below.

```
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):

	File "/home/ci/.cache/bazel/_bazel_ci/1aec92f0c99138e5307d9cfdfd559ea8/external/bazel_tools/tools/cpp/cc_configure.bzl", line 38

		configure_unix_toolchain(repository_ctx, cpu_value)

	File "/home/ci/.cache/bazel/_bazel_ci/1aec92f0c99138e5307d9cfdfd559ea8/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 359, in configure_unix_toolchain

		_get_tool_paths(repository_ctx, darwin, "cc_wrapper....))

	File "/home/ci/.cache/bazel/_bazel_ci/1aec92f0c99138e5307d9cfdfd559ea8/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 59, in _get_tool_paths

		{k: which(repository_ctx, k, ("/usr/bin/" + k)) for k in ["ld", "cpp", "dwp", "gcov", "nm", "objcopy", "objdump", "strip"]} + {"gcc": cc, "ar": "/usr/bin/libtool" if darwin else which(repository_ctx, "ar", "/usr/bin/ar")}

The `+` operator for dicts is deprecated and no longer supported. Please use the `update` method instead. You can temporarily enable the `+` operator by passing the flag --incompatible_disallow_dict_plus=false
```

**Comment by davido** [comment]
//CC @vladmos who added https://github.com/bazelbuild/bazel/commit/ee0a8bb7f4a9b8edc3fdb30b4e255cf461415382.

**Comment by davido** [comment]
I added another fix to Bazel test rules, to make it forward compatible: [1].

* [1] https://bazel-review.googlesource.com/#/c/bazel/+/30030/

**Comment by mboes** [comment]
@davido more fixes will be needed: this particular error shows up in `tools/cpp/unix_cc_configure.bzl`.

**Comment by mboes** [comment]
`--all_incompatible_changes` currently always triggers on the above file, at least on Linux, AFAICT. Thus making the flag essentially unusable. @ianthehat though for my particular project, `bazel build //...` before `bazel test //... --all_incompatible_changes` is a workaround.

**Comment by vladmos** [comment]
I've removed all usages of + on dicts I could find manually. I'll test whether Bazel works with --all_incompatible_changes tomorrow and will fix the rest if anything is missing. Feel free to reopen the issue if you find anything.
