### ISSUE TITLE
--sandbox_debug output gets uploaded to remote cache

### ISSUE THREAD

**Issue by mmorearty** [bazelbuild/bazel#4348]
### Description of the problem / feature request / question:

I could see how this could be quite hard to avoid, and might even be considered WAI, but it's probably not optimal behavior from the perspective of users:

If `--sandbox_debug` is used, and the remote cache is also used, then the full output of `--sandbox_debug` is uploaded to the remote cache for every command that is run. This means that future downloads from the cache by other users will clutter the screen with a lot of the `--sandbox_debug` output.

In my case, I had `--sandbox_debug` on while doing some debugging of our Bazel config. I left it on for a little while, so thousands of my build artifacts got uploaded. Later, after a `bazel clean` and then a new build *without* `--sandbox_debug`, there was a long stream of sandbox-debug output.

### If possible, provide a minimal example to reproduce the problem:

```bash
bazel build --sandbox_debug --experimental_remote_spawn_cache --remote_rest_cache=http://localhost:13000 :main

bazel clean

bazel build --experimental_remote_spawn_cache --remote_rest_cache=http://localhost:13000 :main
```

Change `http://localhost:13000` to the location of your remote cache, and change `:main` to any target you have.

The second `bazel build` will display the `--sandbox_debug` outpu even though it was not on the command line.

### Environment info
* Operating System: Linux
* Bazel version (output of `bazel info release`): 0.9.0

**Comment by buchgr** [comment]
I think this is a wider issue of remote caching / execution that we need to take flags that influence the outputs of an action as inputs to that action.

We have the basic mechanism in place in our options library where one can specify the effect of an option (i.e. influences outputs). In the remote execution we would need to include all these flags in the cache key computation. However, as usual, it's not all that straightforward and we also need to think about how to remain debuggable.

**Comment by fmeum** [comment]
@bazelbuild/triage Not stale.

**Comment by coeuvre** [comment]
Duplicate of https://github.com/bazelbuild/bazel/issues/16689.
