### ISSUE TITLE
Please support javac plugins

### ISSUE THREAD

**Issue by denis-zhdanov** [bazelbuild/bazel#4349]
*Bazel* supports annotations processors only at the moment - [java_plugin](https://docs.bazel.build/versions/master/be/java.html#java_plugin):   

```
java_plugin defines plugins for the Java compiler run by Bazel. At the moment, the only supported kind of plugins are annotation processors.
```
A sample javac plugin is [Traute](http://traute.oss.harmonysoft.tech/)

**Comment by iirina** [comment]
I think you should be able to write a `java_plugin` for that. @cushon knows more about plugins

**Comment by cushon** [comment]
Yeah, this is possible with `java_plugin`. `com.sun.source.util.Plugin`s need to be on the processor class path (which `java_plugin` takes care of) and available for service-loading (which I recommend https://github.com/google/auto/tree/master/service for), and then they can be enabed with `-Xplugin` javacopts.

Demo: https://gist.github.com/cushon/53857e654f8bb1cd126074368aeb4c71

```
bazel build :hello
...
Hello.java:1: Note: hello plugins
class Hello {}
^
```

**Comment by jin** [comment]
Closing this as the feature is already supported.

**Comment by cushon** [comment]
We should consider better support for this. Having to set `javacopts=["-Xplugin:..."]` on all upstream targets is kind of limiting. We could add a `java_plugin.plugin_name` attribute (similar to `processor_class`) that caused the plugin to run on targets that the plugin is applied to.
