### ISSUE TITLE
Bazel for Solaris

### ISSUE THREAD

**Issue by FrostSrg** [bazelbuild/bazel#4350]
Unable to collect Bazel 0.8.1 from source on the Solaris operating system version 11.3

����  Building Bazel from scratch......sed: illegal option -- E
fgrep: illegal option -- m
usage: fgrep [ -bchilnsvx ] [ -e exp ] [ -f file ] [ strings ] [ file ] ...
����  Building Bazel with Bazel.
.Building output/bazel!
awk: ENVIRON is not an array
WARNING: /tmp/bazel_XXL.aagd/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel_XXL.aagd/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
	File "/tmp/bazel_XXL.aagd/out/external/bazel_tools/tools/cpp/cc_configure.bzl", line 38
		configure_unix_toolchain(repository_ctx, cpu_value)
	File "/tmp/bazel_XXL.aagd/out/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 358, in configure_unix_toolchain
		find_cc(repository_ctx)
	File "/tmp/bazel_XXL.aagd/out/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 348, in find_cc
		fail(("Cannot find gcc or CC%s, eithe...))
Cannot find gcc or CC, either correct your path or set the CC environment variable
INFO: Elapsed time: 2.583s
FAILED: Build did NOT complete successfully (3 packages loaded)
    currently loading: @local_jdk//
ERROR: Could not build Bazel!!!

**Comment by buchgr** [comment]
Hi @FrostSrg, unfortunately Solaris is not one of our supported platforms :(.

**Comment by SheldonE** [comment]
You can fix the sed error by installing GNU sed, the awk error can be solved by replacing this line:
local env_vars="$(awk 'END { for (name in ENVIRON) { if(name != "_" && name ~ /^[A-Za-z0-9_]*$/) print name; } }' </dev/null)"
in scripts/bootstrap/compile.sh to:
local env_vars=`env | sed 's/=.*$//' | grep -v '^_$'`
Also make sure the CXX environmental variable is defined to your c++ compiler.

After all that, you end up with the following error:

ERROR: No default_toolchain found for cpu 'unknown'. Valid cpus are: [
  piii,
  armeabi-v7a,
  x64_windows,
  x64_windows_msvc,
  x64_windows_msys,
  s390x,
  ios_x86_64,
]
INFO: Elapsed time: 10.664s
FAILED: Build did NOT complete successfully (3 packages loaded)

This is what's stopping us right now.

**Comment by siepkes** [comment]
In case anyone Google's this / ends up here; I have a port for SmartOS (Illumos) which should also work with Solaris with some effort here: https://github.com/siepkes/bazel-smartos
