### ISSUE TITLE
Bazel 0.9 stop working on Windows10

### ISSUE THREAD

**Issue by susiwen8** [bazelbuild/bazel#4353]
I installed Bazel 0.9 on Windows10 by Chocolatey, but when I run bazel, there is pop out window to tell me "bazel.exe has stopped working".  Does this occur to anyone else?

**Comment by mhlopko** [comment]
Assigning to Laszlo, he will know how to obtain more debug information :)

**Comment by laszlocsomor** [comment]
@susiwen8 : Is there more information, like an error code? I've seen similar errors when the `PATH` environment variable was set up incorrectly.

Try this workaround:

1. open `cmd.exe`
2. call `set PATH=c:\tools\msys64\bin;c:\tools\msys64\usr\bin;c:\python27;c:\windows\system32`

  Adjust the paths as needed for your platform.

3. Try running Bazel from this command prompt.

**Comment by jeness** [comment]
Already set system path as above. But Bazel still stops working when run `bazel version` or `bazel`.

**Comment by laszlocsomor** [comment]
@jeness :  Is there more information, like an error code?

**Comment by buchgr** [comment]
Can this be closed @laszlocsomor?

**Comment by laszlocsomor** [comment]
I don't know what was the original issue or if it got resolved. Since there were no more updates, I can only assume a transient failure and as such declare this bug non-reproducible.
