### ISSUE TITLE
Tensorflow bazel issue

### ISSUE THREAD

**Issue by rish321** [bazelbuild/bazel#4357]

**Comment by mhlopko** [comment]
:)

TF people are investigating the issue, and unfortunately I don't have a bandwidth to help at this stage of investigation. Please open an issue if you discover that it's a bazel problem and please follow the issue template to provide more information that will speed up fixing it. Thanks!

**Comment by rish321** [comment]
Sure, if they are investigating, its fine. I thought that because python scripts are working fine, it would be a bazel issue.
