### ISSUE TITLE
Support for shallow clones with git_repository skylark rules

### ISSUE THREAD

**Issue by edbaunton** [bazelbuild/bazel#4359]
As discussed in https://github.com/bazelbuild/bazel/issues/1408 by @davidzchen, this issue tracks adding support for shallow clones to the `git_repository` skylark rules.

Also https://github.com/bazelbuild/bazel/issues/1246 and https://github.com/bazelbuild/bazel/issues/2696 related.

**Comment by edbaunton** [comment]
Can someone with the requisite superpowers reopen this so that we don't lose track of the outstanding work discussed in #4537

**Comment by ittaiz** [comment]
I think it's a good idea to try and think of the use-cases (one dimension is how far is the commit from the tip)

**Comment by aehlig** [comment]
Reopend  by 40c757f4ab90214f95935672532a495c4551490a.

**Comment by aehlig** [comment]
With shallow clones for tag and `shallow_since` for fixed commits we have a good enough work around to reduce priority.

**Comment by edbaunton** [comment]
It's a bit of a shame this was done without any community discussion as I would like to have contributed. There appears to be no documentation on the expected date format, nor does there seem to be any tests for the above changeset.

**Comment by ittaiz** [comment]
is there still point in this issue given git itself doesn't support full shallow clones?

**Comment by aehlig** [comment]
> is there still point in this issue given git itself doesn't support full shallow clones?

Well, that's why we went the `shallow_since` path as truely shallow clones are usually not supported by git servers. And in theory, it would still be desirable&mdash;but you're right, given that git doesn't support it, there's not much bazel can do.
