### ISSUE TITLE
ijar zipper compression corrupts some files

### ISSUE THREAD

**Issue by ekuefler** [bazelbuild/bazel#436]
For some files, it's not possible to deflate the zip file created by the ijar zipper:

```
$ bazel-bin/third_party/ijar/zipper Cc test.zip test
$ bazel-bin/third_party/ijar/zipper x test.zip     
zlib returned error code -3 during inflate.
.
$ unzip test.zip
Archive:  test.zip
replace test? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: test                    
  error:  invalid compressed data to inflate
```

I'm not sure what sorts of files cause this failure, but the following is a small example that fails reliably for me:

```
one
two
three
four
five
six
seven
eight
nine
ten
eleven
```

It works with only ten lines, so it seems somehow related to file size, but in further experiments it doesn't seem like there's an exact byte count that it breaks after.

@damienmg

**Comment by damienmg** [comment]
Thanks for the reproduction case, I told you I had corner case I did not caught. I'll work on that later today.

**Comment by damienmg** [comment]
It's not related to the size of the input. As if we replace newlines with space then no errors happen

**Comment by damienmg** [comment]
After fixing the CRC32 I have an interesting repro scenario:
 for i in $(seq 1 24); do rm test; for j in $(seq 1 $i); do echo -n "$j">>test; done; ./bazel-bin/third_party/ijar/zipper Cc $i.zip test; rm test; unzip $i.zip >/dev/null || echo $i; done
 bad CRC c2a609e9  (should be 37730268)
23

  error:  invalid compressed data to inflate
24


So at 23 the file is corrupted but uncompressed, at 24 the decompression fails

**Comment by damienmg** [comment]
Smaller repro case I could come up with is "aaaaaaaaaaa" in a file

**Comment by damienmg** [comment]
Wait seems like it happens all the time when compression actually does compress.

**Comment by damienmg** [comment]
Ok I have a fix for that, it relies on a undocumented feature of zlib!
