### ISSUE TITLE
Linkopts substitution breaks compiling against windows sdk libraries

### ISSUE THREAD

**Issue by gimo** [bazelbuild/bazel#4367]
MSVC requires that sdk libraries are passed by name directly to the linker (https://docs.microsoft.com/en-gb/cpp/build/reference/link-input-files) this means that we need to set linkopts to "ws2_32.lib" to link to winsock. It then gets detected by bazel as a target which doesn't exist. Note: MSVC doesn't support "-Lws2_32.lib" for passing libraries.

Example:

cc_binary(
    name = "winsock_test",
    src="dummy.cpp",
    linkopts = [
        "ws2_32.lib"
    ]
)

Windows 10
Bazel 0.9.0
Visual Studio 2015 (But I think all versions will have the same problem)

**Comment by meteorcloudy** [comment]
@gimo You can use `-DEFAULTLIB:ws2_32.lib`
