### ISSUE TITLE
cc_import should return CcSkylarkApiProvider

### ISSUE THREAD

**Issue by mboes** [bazelbuild/bazel#4369]
### Description of the problem

cc_import does not return any additional provider. This means that e.g. header files supplied via `hdrs` are not available for inspection by Skylark rules. Say I'm implementing a Skylark rule to compile Foolang native libraries, that can depend on cc libraries and can include cc header files. I can easily enough depend on a `cc_library`, since I can get at the header files for that library via the `cc` provider. But for some reason I can't do the same with `cc_import`.

### Environment info

* Bazel version (output of `bazel info release`): 0.9.0

###  Have you found anything relevant by searching the web?
Nothing in [GitHub issues](https://github.com/bazelbuild/bazel/issues) nor Google.

**Comment by meteorcloudy** [comment]
@mboes cc_import does has CcSkylarkApiProvider, but the actual implementation of cc_import is not included in 0.9.0
https://github.com/bazelbuild/bazel/commit/40bc935f033412f8564c57a2bd7ec99f493538c3#diff-f636451e668d549f65db71c2d7ec923fR161

It'll be available from 0.10.0
