### ISSUE TITLE
Support for Dart?

### ISSUE THREAD

**Issue by perezd** [bazelbuild/bazel#437]
It'd be nice to be able to build Dart projects using Bazel. WDYT?

**Comment by damienmg** [comment]
Hi,

I am great fan of Dart but we don't have enough bandwidth to add it. However, Bazel as its own (extension mechanism)[http://bazel.io/docs/skylark/concepts.html] and it should be straigthforward to add dart support for it. However, if you want full integration then pub might be a bit harder (we also have a plan to enable those kind of thing easily using skylark extensions).

**Comment by perezd** [comment]
Yes, I think its doable as well, I'm not entirely sure what it'd look like, especially if I want it to support protocol buffers and be pub friendly.

**Comment by cbracken** [comment]
Working on extracting everything we've got to Skylark right now. I'm happy to contribute these.

**Comment by damienmg** [comment]
As announced today during the Dart summit this is possible. See https://github.com/dart-lang/rules_dart

**Comment by perezd** [comment]
That's great news!
