### ISSUE TITLE
Expose CcSkylarkApiProvider as a first-class provider in Skylark

### ISSUE THREAD

**Issue by mboes** [bazelbuild/bazel#4370]
### Description of the feature request

It's possible to write Skylark rules that have `cc_*` rules as dependencies. Via the `CcSkylarkApiProvider`, it's possible for these Skylark rules to e.g. collect the list of transitive header files from these dependencies. But,

1. it's not possible to write a Skylark rule that itself provides `CcSkylarkApiProvider`,
2. it's not possible to test whether a dependency provides `CcSkylarkApiProvider`.

A workaround for (2) is:

```bzl
[dep for dep in ctx.attr.deps if hasattr(dep, "cc")]
```

where one would expect to be able to use:

```bzl
[dep for dep in ctx.attr.deps if CcSkylarkApiProvider in dep]
```

Underlying both (1) and (2) is the fact that unlike say `DefaultInfo` and `OutputGroupInfo`, `CcSkylarkApiProvider`, along with many other native providers, are not exported to Skylark as a global.

My use case for (1) is writing a replacement for `cc_import` in Skylark, since that rule does not currently provide `CcSkylarkApiProvider`.

### Environment info
* Bazel version (output of `bazel info release`): 0.9.0

###  Have you found anything relevant by searching the web?

I've seen mention of "Bazel <X> sandwiches" where <X> is some language. e.g. https://blog.bazel.build/2017/03/07/java-sandwich.html. It looks like for Java at least, the equivalent of (2) above is possible. Though the blog post mentions that the equivalent of (1) is still not possible. The Java functionality is provided via the `java_common` struct. For C/C++, the corresponding struct [`cc_common`](https://docs.bazel.build/versions/master/skylark/lib/cc_common.html) does not expose the corresponding methods.

Also related: https://github.com/bazelbuild/bazel/issues/2163

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by mhlopko** [comment]
We are currently working on a C++ sandwich. CcSkylarkApiProvider will very likely be replaced by some other thing and we'll also include corresponding cc_common functionality. We will provide a design doc for public review in Q1. Assigning to Pedro since he leads this effort.

**Comment by oquenchil** [comment]
Sandwich is ready to be used. Closing this bug:
https://docs.bazel.build/versions/master/skylark/lib/CcInfo.html
