### ISSUE TITLE
toolchains flag --experimental_extra_toolchains is not supported 

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/bazel#4372]
According to [docs](https://docs.bazel.build/versions/master/toolchains.html) all you need to do to override toolchain is to provide flag `--experimental_extra_toolchains` but unfortunately that does not work on `0.9.0`, and I can't find the right flag that replaces it.

What is the current way to override toolchain?

**Comment by katre** [comment]
What is the problem you are seeing? The `--extra_toolchains` flag (the older experimental version should still be recognized but is deprecated) does not override toolchain selection, it simply adds new toolchains that are available. If the execution and target constraints on the extra toolchains do not match the execution and target platforms in the build, the extra toolchains won't be used. (The target platform is set with `--platforms`, execution platform should be intelligently autodetected.)

Try using the `--toolchain_resolution_debug` flag to cause Bazel to emit extra information during toolchain resolution. This will include each toolchain considered, and any reasons why it does not match the execution and target platforms.

Assigning this back to you for further information gathering.

**Comment by or-shachar** [comment]
@katre - thanks for clarification! Maybe it's worth to add this also to [bazel command line reference](https://docs.bazel.build/versions/master/command-line-reference.html).

Still - I don't understand where have I mistaken. I get this:
```
ERROR: Unrecognized option: --experimental_extra_toolchains=@io_bazel_rules_scala//scala:scala_toolchain
```
The command I'm running is:
```
bazel test --test_output=errors --override_repository io_bazel_rules_scala="${rules_scala_dir}"  --experimental_extra_toolchains=@io_bazel_rules_scala//scala:scala_toolchain //aspect/testing/tests/src/com/google/idea/blaze/aspect/scala/...
```

Please kindly take a look at travis logs here https://travis-ci.org/bazelbuild/rules_scala/jobs/323554656

**Comment by katre** [comment]
Okay, this is my fault, and I definitely need to go check the documentation and update it. Checking the history, there was never a flag named `--experimental_extra_toolchains`, it has always been `--extra_toolchains`. I don't have access to the repository you're testing, but checking out the https://github.com/bazelbuild/rules_scala/pull/364 PR I can run this command successfully:

```
$ bazel test --test_output=errors  --extra_toolchains=@io_bazel_rules_scala//scala:scala_toolchain //test/...
```

Try using the flag name without the "experimental" and let me know how that goes, I'll look into extending the documentation as you suggest.

**Comment by katre** [comment]
Sending https://bazel-review.googlesource.com/c/bazel/+/30310 for review to update the docs.

**Comment by or-shachar** [comment]
Thanks @katre !
