### ISSUE TITLE
Temp directories: respect TMPDIR/TEMP/TMP for local actions

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4376]
## Request

Respect the user's TMPDIR envvar (or TMP and TEMP on Windows) if set, fall back on `/tmp` on Linux/macOS and to temp-in-execroot on Windows.

## Summary

Unexpected effect of https://github.com/bazelbuild/bazel/commit/cfccdf1f6e93125d894ff40e0ccecaf20cc20ef5 was that it breaks socket creation because the paths are longer than 106 characters.

From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=847206:

> I can confirm that this is the case -- the GNUPGHOME needs to fit within
> sockaddr_un.sun_path (see unix(7)).  In other test suites that use
> GnuPG, i've seen deliberately short paths used.

/cc @jianglai, @jmhodges 

## Context

- comments leading up to https://github.com/bazelbuild/bazel/issues/4303#issuecomment-353571193
- https://github.com/bazelbuild/bazel/issues/3215#issuecomment-348994701 points out gpg-agent's limitation of paths length

**Comment by dapirian** [comment]
I believe this has had the side effect that `--test_env=TMPDIR=/tmp` is not respected, which is problematic
