### ISSUE TITLE
Update freebsd port to 0.9.0 to fix bazel nightly

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/bazel#4377]
Since https://github.com/bazelbuild/bazel/commit/caceacd984a3f86b623ea726f4df36bd81998d25 bazel nightly on freebsd has been failing as "configuration_field" is not available in bazel 0.7.0. Now that configuration_field is available on bazel 0.9.0 now, can we update bazel version in freebsd? Or change freebsd ci scripts to use latest released bazel + bazel from HEAD like we do on other distributions?

Thanks!

**Comment by aehlig** [comment]
The FreeBSD port is already at version 0.9.0, see https://svnweb.freebsd.org/ports?view=revision&revision=456716

Will reimage the machines to get a clean latest version later today.
