### ISSUE TITLE
Windows: Error: corrupt installation

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#4378]
I noticed this error in many places, my local machine, [Bazel CI](https://ci.bazel.io/blue/organizations/jenkins/bazel-tests/detail/bazel-tests/1606/pipeline), [Tensorflow CI](http://ci.tensorflow.org/job/tf-master-win-bzl/2189/console), 
```
Error: corrupt installation: file 'C:\tmp/_bazel_pcloudy/install/6f94f50e4679b4d40059370500e5cb9c/_embedded_binaries/A-server.jar' modified.  Please remove 'C:\tmp/_bazel_pcloudy/install/6f94f50e4679b4d40059370500e5cb9c' and try again.
```

The interesting part is that, it happens with every old Bazel versions **in the new year**!

The file timestamps are all set to `Jan  1  2027`. 
```
pcloudy@tensorflow-jenkins-win-gpu2-slave MSYS ~/workspace/tensorflow
$ ll /c/tmp/_bazel_pcloudy/install/6f94f50e4679b4d40059370500e5cb9c/_embedded_binaries
total 44894
-rw-r--r-- 1 pcloudy None 45074399 Jan  1  2027 A-server.jar
-rwxr-xr-x 1 pcloudy None   257536 Jan  1  2027 build-runfiles.exe
drwxr-xr-x 1 pcloudy None        0 Oct 19 16:13 embedded_tools
-rw-r--r-- 1 pcloudy None       33 Jan  1  2027 install_base_key
-rw-r--r-- 1 pcloudy None        4 Jan  1  2027 java.version
-rw-r--r-- 1 pcloudy None     3849 Jan  1  2027 jdk.BUILD
-rwxr-xr-x 1 pcloudy None    90112 Jan  1  2027 linux-sandbox.exe
-rwxr-xr-x 1 pcloudy None   257536 Jan  1  2027 process-wrapper.exe
-rwxr-xr-x 1 pcloudy None   272896 Jan  1  2027 windows_jni.dll
-rwxr-xr-x 1 pcloudy None      698 Jan  1  2027 xcode-locator
```

@laszlocsomor Do you have any idea about this? Is there anything wrong with our file invalid mechanism?
FYI @mhlopko

**Comment by wyan-nestlabs** [comment]
We ran into the same problem in all our own windows builder machines. Removing C:\tmp/_bazel_pcloudy/install/* fixed it. But it is not addressing the reason for the failure.

**Comment by laszlocsomor** [comment]
@meteorcloudy : This is Windows only, right? Then it's likely a bug in this class: https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/util/file_windows.cc#L156 . Yesterday was Jan 2, did you see this yesterday too, or only on Jan 1, or with Bazel installations from last year?

**Comment by meteorcloudy** [comment]
I saw it on Jan 2 and also today Jan 3, and yes, with every bazel installations from last year.

**Comment by laszlocsomor** [comment]
Yeah the code looks really suspicious. Let me take a closer look.

**Comment by meteorcloudy** [comment]
@mhlopko To fix the Windows CI build, we'll have to delete the installation directories.

**Comment by meteorcloudy** [comment]
@laszlocsomor Thanks!

**Comment by laszlocsomor** [comment]
One workaround is to delete the install directory (dirname of "A-server.jar" in the error message).
Another workaround is to run `touch -m -t 202801010101 $(find path/to/install/dir -type f)`.

**Comment by laszlocsomor** [comment]
Another workaround: rename the install directory.
This is the easiest approach. It's useful if deleting fails due to long file names. (Delete those directories from MSYS or using Total Commander.)

**Comment by rongjiecomputer** [comment]
I hit this bug in my local Windows 10 machine as well on Jan 3. Some Bazel files have the "01/01/202**8**" timestamp.

Reinstalling Bazel fixes the issue, but new Bazel files still have the timestamp of 01/01/2028. See screenshots.

![capture](https://user-images.githubusercontent.com/13115060/34549727-ec3c18f8-f145-11e7-9c33-78dc37be4d38.JPG)

**Comment by laszlocsomor** [comment]
> Reinstalling Bazel fixes the issue, but new Bazel files still have the timestamp of 01/01/2028. See screenshots.

That is working as intended.

When you install Bazel, Bazel unpacks embedded binaries and sets their timestamp to Jan 1, 10+$current_year. It's 2018 now, so the timestamps are 2028/01/01.

**Comment by buchgr** [comment]
Can this be closed?

**Comment by laszlocsomor** [comment]
No, this bug is not yet fixed.

**Comment by flaub** [comment]
Just ran into this issue here.
