### ISSUE TITLE
bazel build build: command not found

### ISSUE THREAD

**Issue by DavidBrayford** [bazelbuild/bazel#4379]
When trying to build TensorFlow I get an error from bazel not finding the command build with the following command:

bazel build --config=mkl -c opt //tensorflow/tools/pip_package:build_pip_package
build: command not found

Any suggestions on what might be causing this issue?

David

**Comment by laszlocsomor** [comment]
Sorry but I'm going to close this, it's a question not a bug report.
Please ask usability questions on StackOverflow: https://stackoverflow.com/questions/tagged/bazel
Thanks!

**Comment by laszlocsomor** [comment]
Ah, I just noticed the bug template still says this may be a question.  Let me update the template. :)

As for the issue, you may have to run `./configure` from the TF directory.
What OS are you using and what's the output of "bazel version"?

**Comment by mhlopko** [comment]
If what Laszlo suggests doesn't help, what version of bazel do you have installed? What is your OS?

**Comment by DavidBrayford** [comment]
I am using version 0.7.0 on SLES12

**Comment by mhlopko** [comment]
Can you run `bazel version`?

**Comment by DavidBrayford** [comment]
I can successfully execute bazel version, but not bazel build

**Comment by mhlopko** [comment]
This is super weird. Can you reinstall bazel? 0.9.0 is the latest released version.

**Comment by DavidBrayford** [comment]
Thanks updating to version 0.9.0 fixed the problem.

**Comment by laszlocsomor** [comment]
Thanks!
