### ISSUE TITLE
bazel test ignores tags=["manual"]

### ISSUE THREAD

**Issue by excavador** [bazelbuild/bazel#4380]
### Description of the problem / feature request / question:

bazel test ignores ```tags = ["manual"]``` on test rule

### Environment info
* Operating System: maxOS High Sierra 10.13.2

* Bazel version (output of `bazel info release`):
```
➜ bazel version
Build label: 0.9.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sun Jul 12 12:24:01 +49936 (1513677414241)
Build timestamp: 1513677414241
Build timestamp as int: 1513677414241
➜ bazel info release
release 0.9.0-homebrew
```

**Comment by benjaminp** [comment]
Could you be more specific about what you're expecting to happen? As documented in https://docs.bazel.build/versions/master/user-manual.html#target-patterns, `manual` causes tests to be ignored in target expansions but not if they're explicitly listed on the command line.

**Comment by excavador** [comment]
I am sorry.

I meant, 
```
bazel test //...
```
executes test, marked as "manual".

If it is important, it is my own rule, implemented in skylark
```
my_test = rule(
    test=True,
    executable=True,
)
```

I use it in my BUILD file in following way
```
my_test(name = "my_concrete_test", tags = ["manual"])
```

command
```
bazel test //...
```
run this test

**Comment by excavador** [comment]
I am sorry.
Just found the problem in macros.
