### ISSUE TITLE
Android: support font in XML

### ISSUE THREAD

**Issue by vmax** [bazelbuild/bazel#4381]
### Description of the problem / feature request / question:

Bazel does not support newly-added Android feature [Fonts in XML](https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml.html)

### Environment info
* Operating System:
macOS 10.13.2

* Bazel version (output of `bazel info release`):
release 0.9.0-homebrew

### Log
```
$ bazel build --verbose_failures :android
ERROR: app/BUILD:11:22: in resource_files attribute of android_binary rule //app:android: 'app/src/main/res/font/heebo_black.ttf' is not in the expected resource directory structure of <resource directory>/{anim,animator,color,drawable,interpolator,layout,menu,mipmap,raw,transition,values,xml}/<file>
ERROR: Analysis of target '//app:android' failed; build aborted: Analysis of target '//app:android' failed; build aborted
INFO: Elapsed time: 0.296s
FAILED: Build did NOT complete successfully (1 packages loaded)
```

**Comment by dkelmer** [comment]
The android_common jars need to be updated for this to work. I'll take a look.

**Comment by oferb** [comment]
Adding some more info to help repro:

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Working app on master:
https://github.com/hasadna/hasadna
To run:
bazel build //projects/noloan/app

Non-compiling app, after adding fonts to `res/font`:
https://github.com/hasadna/hasadna/tree/xml_fonts_issue
This branch has just one commit to add the fonts:
https://github.com/hasadna/hasadna/commit/642e82725f0eb868692c5d534b0025fcb878d0df
Same command to run:
bazel build //projects/noloan/app

### What's the output of `bazel info release`?
I've checked this on both versions:
release 0.10.0-2018-03-25 (@b4fcdc3)
development version (based on https://github.com/bazelbuild/bazel/tree/release-0.12.0 from March 29th)

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
This is odd, I agree. I can try to clone & rebuild bazel if you want.

###  Have you found anything relevant by searching the web?
Nope.

### Any other information, logs, or outputs that you want to share?
This is the full bazel error:
```
oferb@oferb:~/devel/hasadna$ bazel build //projects/noloan/app
ERROR: /home/oferb/devel/hasadna/projects/noloan/app/BUILD:6:22: in resource_files attribute of android_binary rule //projects/noloan/app:app: 'projects/noloan/app/res/font/heebo_black.ttf' is not in the expected resource directory structure of <resource directory>/{anim,animator,color,drawable,interpolator,layout,menu,mipmap,raw,transition,values,xml}/<file>
ERROR: Analysis of target '//projects/noloan/app:app' failed; build aborted: Analysis of target '//projects/noloan/app:app' failed; build aborted
INFO: Elapsed time: 0.212s
FAILED: Build did NOT complete successfully (0 packages loaded)
```
###  Anything else?
Let me know how best to help you reproduce the problem. I want to make it as easy as possible for you. You can reach me at oferb@ ;)

**Comment by jin** [comment]
Bumping to P2.

**Comment by jin** [comment]
Update: spent some time upgrading the vendored Android commons dependencies to 26, but that broke a bunch of other stuff and Bazel wouldn't build. Still looking..

**Comment by asiri-uber** [comment]
Locally I just updated com.android.tools.layoutlib_layoutlib-api to 26 which seems to work.  Not sure what the ramifications are of only updating one lib is.

**Comment by oferb** [comment]
@asiri-uber how did you do that?

**Comment by oferb** [comment]
@jin any update so far?

**Comment by jin** [comment]
Sorry, I haven't had the chance to work on this since the last time I ran into blockers. I think what @asiri-uber meant was that they switched https://github.com/bazelbuild/bazel/blob/master/third_party/android_common/com.android.tools.layoutlib_layoutlib_25.0.0.jar to 26.0.0 and it worked for them. Do you mind trying that out and seeing if it works for you too?

**Comment by oferb** [comment]
That works, although I do want to work out of a Bazel release or head.
So I'll wait for it :)

**Comment by jin** [comment]
@oferb https://github.com/bazelbuild/bazel/issues/4381
