### ISSUE TITLE
ctx.action.expand_template not executing

### ISSUE THREAD

**Issue by tagarwal** [bazelbuild/bazel#4382]
[charts.zip](https://github.com/bazelbuild/bazel/files/1601412/charts.zip)
In writing a rule, have a call to ctx.actions.run_shell, but the commands inside it are never executed

### If possible, provide a minimal example to reproduce the problem:
`_VERSION = "0.0.1"
def _chgver(ctx):
  for f in ctx.files.srcs:
    output_file = ctx.actions.declare_file(f.path.replace('/charts','/tmp/charts'))
    ctx.actions.expand_template(
      template=f,
      output=output_file,
      substitutions={
          "{VERSION}": _VERSION
      })

change_version = rule(
    implementation=_chgver,
    attrs={
        "srcs": attr.label_list(allow_files=True),
    }
)`

BUILD FILE
`change_version(
    name="changeversion",
    srcs=glob(["charts/**"])
)`

charts directory in the package contains text files with "{VERSION}" literal, Attached is the zip

### Environment info
* Operating System: Darwin Kernel Version 15.5.0

* Bazel version (output of `bazel info release`): release 0.7.0-homebrew

`bazel build --verbose_failures :changeversion
INFO: Found 1 target...
Target //expand_template:changeversion up-to-date (nothing to build)
INFO: Elapsed time: 0.163s, Critical Path: 0.01s`

Why do I always get nothing to build. I am expecting the directory tmp/charts to contain the substituted files post the execution of ctx.actions.expand_template

**Comment by ahumesky** [comment]
The outputs of the template actions need to be added to the default outputs of the rule.
See https://docs.bazel.build/versions/master/skylark/rules.html#default-outputs

Something like this should work:

```python
_VERSION = "0.0.1"
def _chgver(ctx):
  outs = []
  for f in ctx.files.srcs:
    output_file_path = "processed/" + f.basename
    output_file = ctx.actions.declare_file(output_file_path)
    outs.append(output_file)
    ctx.actions.expand_template(
      template=f,
      output=output_file,
      substitutions={
          "{VERSION}": _VERSION
      })
  return [DefaultInfo(files=depset(outs))]

change_version = rule(
    implementation=_chgver,
    attrs={
        "srcs": attr.label_list(allow_files=True),
    }
)
```

Note also that you don't necessarily need to create a new skylark rule for this. It's possible to use a `genrule`, though that requires some bash or some other program to do the substitution, e.g.

```python
_VERSION = "0.0.1"

genrule(
  name = "gen_charts",
  srcs = glob(["*.chart"]),
  outs = ["processed/" + f for f in glob(["*.chart"])],
  cmd = """
srcs=($(SRCS))
outs=($(OUTS))
for ((i=0; i < $${#srcs[@]}; i++)); do
  sed "s/{VERSION}/%s/g" "$${srcs[i]}"> "$${outs[i]}"
done
""" % _VERSION,
)
```

**Comment by tagarwal** [comment]
Thank you Alex, I was under the impression, ctx.actions.expandTemplate would generate the Default Provider to return, But your suggestion works. We wanted to write the skylark rule to make it platform independent (we started with genrule though)
