### ISSUE TITLE
Bazel crashes with NPE when trying to access transitive_compile_time_jars of some java_binary dependency

### ISSUE THREAD

**Issue by Fuuzetsu** [bazelbuild/bazel#4384]
### Description of the problem / feature request / question:

We're writing bazel rules and one of the things we'd like to do is obtain information about Java dependencies, notably `dep[JavaInfo].transitive_compile_time_jars`. Sadly when I try to with what's a rather simple dependency, bazel throws NullPointerException and crashes.

As far as I remember, a couple of other fields in the same provider have the same issue but I focus on this field in my repro.

### If possible, provide a minimal example to reproduce the problem:
You can find a prepared repository which exhibits the problem at https://github.com/Fuuzetsu/bazel-trans-classpath-repro/tree/185dac522019f15918b46cea7a9c1576e951e70e . There are instructions in the README along with all information about bazel version &c.. Briefly:

* Clones repository with one of our products which contains some Java files.
* Specifies a couple of `maven_jar`s in WORKSPACE which are needed to build.
* Specifies `java_binary` which depends on those maven jars and uses files from the repository.
* Defines a small helper rule `get_classpath` which has only a single purpose: output `transitive_compile_time_jars` of the aforementioned `java_binary` into a file.
* Tries to build an instance of `get_classpath`: bazel crashes.

### Environment info
* Operating System:

[NixOS](https://nixos.org/). Built from [nixpkgs](https://github.com/NixOS/nixpkgs) `4026ea9c8afd09b60896b861a04cc5748fdcdfb4`.

* Bazel version (output of `bazel info release`):

```
$ bazel info release
release 0.8.0- (@non-git)

$ bazel version
Build label: 0.8.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800
```

Build timestamps are irrelevant here due to `nix` package manager.

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

https://github.com/bazelbuild/bazel/releases/download/0.8.0/bazel-0.8.0-dist.zip

###  Have you found anything relevant by searching the web?
I have not.

### Anything else, information or logs or outputs that would be helpful?
See README in aforementioned repository for part of the bazel stack trace.

**Comment by Fuuzetsu** [comment]
Possibly was fixed in https://github.com/bazelbuild/bazel/commit/49008a3c90e65bc4abf5292af823a931b8f4e096 , needs testing.

**Comment by iirina** [comment]
Please reopen if this still happens.
