### ISSUE TITLE
@wkspc shorthand label syntax works as a dependency but not on command line

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#4385]
Bazel 0.8.1
The current treatment of a label expressed as just `@wkspc` is inconsistent.

I can have `deps=["@rxjs"]` as a shorthand for `deps=["@rxjs//:rxjs"]`

But if I `bazel build @rxjs` I get 
```
INFO: Analysed 0 targets (4 packages loaded).
INFO: Found 0 targets...
```

and if I try to abbreviate `bazel run @yarn//:yarn` as `bazel run @yarn` I get `ERROR: No targets found to run`

Reproduction in this repo:
https://github.com/alexeagle/angular-bazel-example

**Comment by alexeagle** [comment]
fyi @dslomov we might want to take a different solution to this as part of allowing `@` in package names

**Comment by baskus** [comment]
I'd love for this to be resolved. :)

**Comment by Wyverald** [comment]
@bazel-io fork 6.2.0

**Comment by hvadehra** [comment]
https://github.com/bazelbuild/bazel/commit/24f6fe802ebb68da71e1e071c9e84c89b4aa0772 is being reverted due to internal breakages.

**Comment by Wyverald** [comment]
Re-submitted.
