### ISSUE TITLE
bazel_test_test invalid undeclared output test

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#4389]
### Description of the problem / feature request:

`test_no_zip_annotation_manifest_when_no_undeclared_outputs` in `src/test/shell/bazel/bazel_test_test.sh` has a check for the existence of the values of `TEST_UNDECLARED_OUTPUTS_DIR` and `TEST_UNDECLARED_OUTPUTS_ANNOTATIONS_DIR`, but the associated change to add this test only ensures that the undeclared outputs MANIFEST is removed if there are no undeclared outputs. Further, the name of this test seems to indicate that it should be testing for the absence of the annotations *zip* file rather than these two directories.
This test only succeeds because the directories *cannot* exist after the test is run, because the default spawn_strategy of `sandboxed` prevents *any* undeclared outputs from being copied from the action's execution, including those of the test output directories...

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Add `--spawn_strategy=standalone` to the invocation at https://github.com/bazelbuild/bazel/blob/f05a59f68563b48a30abc55dbe927048df011fe2/src/test/shell/bazel/bazel_test_test.sh#L630

### What operating system are you running Bazel on?

linux

### What's the output of `bazel info release`?

0.9.0

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Output of the test log after only adding the standalone strategy specification is attached.

[test_no_zip_annotation_manifest_when_no_undeclared_outputs.log](https://github.com/bazelbuild/bazel/files/1606977/test_no_zip_annotation_manifest_when_no_undeclared_outputs.log)

**Comment by jin** [comment]
@aehlig, I saw that you last reviewed this - can you please take a look? Thanks!

**Comment by werkt** [comment]
Why is this tagged as feature request? The test does not cover the relevant behavior...
