### ISSUE TITLE
cc_library depending on genrule in remote repository: file not found

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel#439]
I have added a BUILD file to [Jsonnet](https://github.com/google/jsonnet). Running `bazel build :jsonnet` in the root of the Jsonnet repo works fine. However, if I include the repository as a remote repository and build the target, I get an error.

## Repro scenario

`WORKSPACE`:

```python
git_repository(
    name = "jsonnet",
    remote = "https://github.com/google/jsonnet",
    commit = "b396545e98150545b75f25abe9464ba8171d668a",
)
```

Result:

```
❯❯❯ bazel build @jsonnet//:jsonnet
.......
INFO: Found 1 target...
INFO: From Compiling external/jsonnet/parser.cpp:
external/jsonnet/parser.cpp:833:29: fatal error: std.jsonnet.h: No such file or directory
     #include "std.jsonnet.h"
                             ^
compilation terminated.
ERROR: /usr/local/google/home/dzc/.cache/bazel/_bazel_dzc/a77de5c83588ca94e232b1cee2f9c3f3/external/jsonnet/BUILD:17:1: C++ compilation of rule '@jsonnet//:jsonnet-common' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -iquote . -iquote ... (remaining 17 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target @jsonnet//:jsonnet failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 8.099s, Critical Path: 0.45s
```

I am wondering whether this is caused by the compiler looking for the header files in the wrong directories. Perhaps it is looking for `"external/jsonnet/std.jsonnet.h"`?

**Comment by kchodorow** [comment]
Yeah, you'll need to specify `includes = ["."]` (see the "Including external libraries" section of http://bazel.io/docs/cpp.html).

**Comment by davidzchen** [comment]
I see. I'm guessing it would be non-trivial to implicitly set the default `includes` path this way for targets in remote repositories?

**Comment by davidzchen** [comment]
On a similar note, if the remote repository had the following directory structure:

```
[workspace]/
    foo/
        BUILD
        foo.cc
````

Then, would the `foo/BUILD` file need to specify `includes = [".."]`?

**Comment by davidzchen** [comment]
Anyway, I added `includes = ["."]` to the `cc_library` rules, but I am still getting the same error when trying to build `@jsonnet//:jsonnet`. Here is the BUILD file: https://github.com/davidzchen/bazel/blob/jsonnet/tools/build_defs/jsonnet/jsonnet.BUILD

In this case, I am using a `new_http_archive` rule that downloads the 0.8.0 release of Jsonnet, which does not contain the BUILD file: https://github.com/davidzchen/bazel/blob/jsonnet/WORKSPACE

Could this be a separate issue?

**Comment by davidzchen** [comment]
It turns out this might have been an issue in my BUILD file. I am not longer getting the error.

I think it would still be good if setting `includes = ["."]` were not required in remote repositories. That way, the same set of BUILD files can be used if compiling a repository directory as well as using it as a remote repository. I will open a separate issue for that.
