### ISSUE TITLE
remote_rest_cache inaccessible error message is unclear

### ISSUE THREAD

**Issue by brunobowden** [bazelbuild/bazel#4395]
### Description of the problem / feature request:

An inaccessible `remote_rest_cache` for a build will produce unclear errors that doesn't clearly explain the cause (i.e. remote rest cache couldn't be contacted):

`C++ compilation of rule '//xxxx:status' failed (Exit 34). Note: Remote connection/protocol failed with: execution failed`

### Improved Error Message
Ideally bazel would identify a higher level error that more directly points to the cause. In this case it's not that the build cache failed internally but that it was inaccessible at all. Something like this would be much more helpful:

`C++ compilation of rule '//xxxx:status' failed (Exit 34). Note: Remote rest cache couldn't be reached: http://my-build-cache-path:8081/cache`

`C++ compilation of rule '//xxxx:status' failed (Exit 34). Note: Remote rest cache internal failure: http://my-build-cache-path:8081/cache - further explanation of internal error`

### Bugs: what's the simplest, easiest way to reproduce this bug?
Configure `bazel.rc` with non-existent build cache:
```
build --spawn_strategy=remote --remote_rest_cache=http://non-existent:8081/cache
```
### What operating system are you running Bazel on?
Ubuntu 16.04

### What's the output of `bazel info release`?
```release 0.8.1```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a

###  Have you found anything relevant by searching the web?

@ulfjack and @buchgr both created tests that verify the existing message

### Any other information, logs, or outputs that you want to share?

n/a

@BillZito for tracking this issue

**Comment by brunobowden** [comment]
Better still, this error shouldn't be seen when there's automatic failover to local build if the remote_rest_cache isn't available. That would be a much preferred fix. #2964

**Comment by drigz** [comment]
This has also caused a flake in our continuous build that runs on GCP and uses GCS as a remote cache.

**Comment by buchgr** [comment]
@drigz which version of bazel are you running?

**Comment by drigz** [comment]
@buchgr This was with 0.12.0. We've since upgraded our CI job to 0.15.0; I'll comment here if we see it again.

**Comment by buchgr** [comment]
AFAIK this has been fixed in the meantime.
