### ISSUE TITLE
Bazel nightly fails due to Jenkins error

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#4397]
The most recent Bazel nightly: [181](https://ci.bazel.build/view/Dashboard/job/bazel/job/nightly/181/console) ([blue ocean](https://ci.bazel.build/blue/organizations/jenkins/bazel%2Fnightly/detail/nightly/181/pipeline))

Sample error output:

`remote file operation failed: c:\jenkins\workspace\bazel\nightly\output at hudson.remoting.Channel@60136487:JNLP4-connect connection from windows-slave-2.c.bazel-public.internal/192.168.59.9:49618: hudson.remoting.ChannelClosedException: Remote call on JNLP4-connect connection from windows-slave-2.c.bazel-public.internal/192.168.59.9:49618 failed. The channel is closing down or has closed down`

**Comment by philwo** [comment]
This was fixed today via https://github.com/bazelbuild/continuous-integration/commit/3fe97baa26d8a0cfd1f854e519478336c1ae52f1.
