### ISSUE TITLE
Bazel's CI is broken

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#4399]
Bazel's CI is broken, we're working on fixing it.

This is just used to track progress and block the release on it.

**Comment by philwo** [comment]
@iirina FYI

**Comment by ivucica** [comment]
Does this issue also cover the fact that artifacts are lacking version?

I wanted to try a nightly build to try out remote caching with directory support, but not only do the filenames lack version, so does the Debian package, making it uninstallable.

Happy to open a new issue if this issue doesn't cover this.

**Comment by philwo** [comment]
I think the nightly artifacts have always lacked a version.

Not sure about the Debian package - could be that that never worked, or that is was recently broken. Please feel free to file an issue for that.

**Comment by ivucica** [comment]
Filed #4417

**Comment by jin** [comment]
CI is revived. Closing this now.
