### ISSUE TITLE
sha256 checksum files for the binary installer can't be used with `sha256sum -c`

### ISSUE THREAD

**Issue by korfuri** [bazelbuild/bazel#440]
The sha256 file for the Linux installer contains the following:

````
c6055c48c39fb044599a53d56431f0af33f7d8c913951f60615e26e0ce4ae1d2
````

The usual way of providing sha256 checksums would be:

````
c6055c48c39fb044599a53d56431f0af33f7d8c913951f60615e26e0ce4ae1d2  bazel-0.1.0-installer-linux-x86_64.sh
````

This way the file can easily be checked with `sha256sum -c bazel-0.1.0-installer-linux-x86_64.sh.sha256`.

**Comment by damienmg** [comment]
Ok I cannot seems to be able to upload the file in the current release. I will fix the release script and might try to go back fix the file themselves later.

**Comment by damienmg** [comment]
Ok I updated the release. This bug will be closed when we do the next export.
