### ISSUE TITLE
Deploy jar cannot execute on Debian: "bad magic number"

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#4400]
Repro is in a docker container that we use for CI.
```
$ docker run --rm -it angular/ngcontainer:0.1.0
circleci@e1d10f36103e:~/repro$ echo "" > WORKSPACE
circleci@e1d10f36103e:~/repro$ cat > BUILD
java_binary(
  name = "main",
  srcs = ["Main.java"],
  main_class = "Main",
)
circleci@e1d10f36103e:~/repro$ cat > Main.java
public class Main {

    public static void main(String[] args) {
        // Prints "Hello, World" to the terminal window.
        System.out.println("Hello, World");
    }

}
circleci@e1d10f36103e:~/repro$ bazel build :main_deploy.jar
Extracting Bazel installation...
...............
INFO: Analysed target //:main_deploy.jar (13 packages loaded).
INFO: Found 1 target...
Target //:main_deploy.jar up-to-date:
  bazel-bin/main_deploy.jar
INFO: Elapsed time: 6.358s, Critical Path: 1.09s
INFO: Build completed successfully, 9 total actions
circleci@e1d10f36103e:~/repro$ bazel-bin/main_deploy.jar
invalid file (bad magic number): Exec format error
circleci@e1d10f36103e:~/repro$ bazel info release
release 0.9.0
```

Context: discussion on https://github.com/bazelbuild/bazel/commit/ba1f83c2c32159dab2640c844e73cbc6cb02ddc4 where I'm trying to run Skylint

**Comment by jin** [comment]
Does `java -jar bazel-bin/main_deploy.jar` work?

**Comment by alexeagle** [comment]
yes

**Comment by jin** [comment]
I'm not sure if calling `bazel-bin/main_deploy.jar` like a native executable is the intended design. The wrapper script `bazel-bin/main` is essentially https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt, which sets up the OS specific mechanisms for the `java_binary` to be run "natively". 

@iirina do you have any suggestions?

**Comment by jin** [comment]
Perhaps it will make sense to have a rule to package a binary along with its runfiles to some single file output, like mentioned in this comment: https://github.com/bazelbuild/bazel/issues/4383#issuecomment-355920899

**Comment by alexeagle** [comment]
I think this is exactly what `*_deploy.jar` is meant to provide, and it works this way on other platforms.

**Comment by meisterT** [comment]
Is this still an issue?
