### ISSUE TITLE
HOME missing from the action env (despite mentioned in the docs)

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/bazel#4401]
### Description of the problem

https://docs.bazel.build/versions/master/test-encyclopedia.html#initial-conditions
says HOME is set to $TEST_TMPDIR. When running the sh_test with -s HOME is not printed.

I have a shell test (that runs node-js web-component-tester) and that relies on HOME being set. I can work-around in the driver script.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

BUILD:
```
sh_test(
    name = "repro",
    srcs = ["repro.sh"],
)
```
repro.sh:
```shell
#!/bin/bash
test -z ${HOME+x} && exit 1
exit 0
```

### What operating system are you running Bazel on?

debian testing

### What's the output of `bazel info release`?

release 0.9.0

**Comment by jin** [comment]
I can repro this on macOS 10.12.6 with release 0.9.0. 

https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/exec/StandaloneTestStrategy.java;l=74?q=StandaloneTestStrategy.java sets TEST_TMPDIR, but not HOME. I'm not sure where HOME is set, if it was set in the first place.

@ulfjack is $HOME == $TEST_TMPDIR or should the docs be updated to reflect this?

**Comment by ulfjack** [comment]
If we want to set HOME, we should do it in test-setup.sh. I don't have a strong preference either way - I vaguely remember that some tools will use HOME, and maybe require it being set. Internally, we always set HOME to TEST_TMPDIR. Technically, the test encyclopedia says "recommended", whatever that means (and I'm also not sure who wrote that or why - it predates my involvement with Bazel).

**Comment by jin** [comment]
Related: #422 

I think we should set HOME, since we're doing it internally and it should be consistent with the TE.

**Comment by jin** [comment]
Low hanging fruit for first time contributors :-)

**Comment by grswk** [comment]
@jin Do we need any changes in TE?

**Comment by jin** [comment]
No, since this syncs up to TE. I see that your commit adds it in StandaloneTestStrategy.java, but by @ulfjack's suggestions can you please add it to https://source.bazel.build/bazel/+/master:tools/test/test-setup.sh instead?

**Comment by grswk** [comment]
@jin Thanks for the review. PR created.
