### ISSUE TITLE
When is `target.runfiles` directory properly set up?

### ISSUE THREAD

**Issue by yiming9** [bazelbuild/bazel#4406]
### Description of the problem / feature request:

It's not a feature request or a bug. It's just a question: for a cc_binary (or py_binary, sh_binary), when does bazel create its runfiles directory and have all symlinks correctly set up? 

* Is it created right after the cc_binary is built, and before any rule that takes this cc_binary as input, OR
* Is it created after the whole build process of all targets is finished?

I'm trying to write a custom rule to pack the contents in the runfiles directory of a cc_binary into a tarball. This custom rule takes the cc_binary and all targets in its runfiles as input. If the runfiles directory is properly set up right after the cc_binary is built, then I just need to directly pack this directory. If not, I probably need to set up a tmp runfiles directory by myself in my custom rule.

Also, is this behavior guaranteed to keep in the future releases?

Thanks a lot!

### What operating system are you running Bazel on?

Ubuntu Linux 16.04.

### What's the output of `bazel info release`?

Release 0.9.0

###  Have you found anything relevant by searching the web?

I tried searching online. Did not find anything relevant.

**Comment by jin** [comment]
Hello @yiming9, do you mind posting this question on [StackOverflow](https://stackoverflow.com/questions/tagged/bazel) with the [bazel] tag? I'll be closing this issue since it's neither a bug or feature request.
