### ISSUE TITLE
The scala_library build def mandates main_class

### ISSUE THREAD

**Issue by orrsella** [bazelbuild/bazel#441]
The `scala_library` build def requires the `main_class` attribute, which doesn't make a lot of sense for a `*_library`. Would expect it to behave similarly to `java_library`. Setting `main_class` to an empty string (or some class, for that matter) makes this error go away. Tested with latest version built from source 8fa0ddcc9165b77f989e5c7be04fbff21189c085.

```bash
├── BUILD
└── Foo.scala
```

```python
load("/tools/build_defs/scala/scala", "scala_library")

scala_library(
    name = "my-scala-lib",
    srcs = glob(["*.scala"]),
)
```

```scala
package com.example

class Foo {
  def main(args: Array[String]): Unit = {
    println("Hello world")
  }
}
```

```bash
$ ./bazel build //my-scala-lib
ERROR: /Users/orr/projects/bazel-example/my-scala-lib/BUILD:3:1: //my-scala-lib:my-scala-lib: missing value for mandatory attribute 'main_class' in 'scala_library' rule.
ERROR: error loading package 'my-scala-lib': Package 'my-scala-lib' contains errors.
INFO: Elapsed time: 0.066s
```

**Comment by laurentlb** [comment]
Thanks, fixed by (36bc3285b751be366a84f113ff0eda0e8bfe61a2).
main_class attribute now exists only for scala_binary rules.
