### ISSUE TITLE
--test_filter flag not implemented for cc_test test runner

### ISSUE THREAD

**Issue by brendandouglas** [bazelbuild/bazel#4411]
Action: "bazel test --test_filter=x -- //cc_test_target", with a test class using the gtest framework.

Expected result:
--test_filter gives equivalent results to --test_arg="--gtest_filter=x"

Actual result:
--test_filter flag has no effect.

Manually replacing '--test_filter=x' with '--test_arg=gtest_filter=x' is the current workaround.

Possibly WAI, if there's no expectation that the test runner implements 'test_filter' for gtest?

**Comment by rohanjoyce** [comment]
This should be fixed since https://github.com/google/googletest/commit/ba96d0b1161f540656efdaed035b3c062b60e006

**Comment by jin** [comment]
Closing this issue based on the previous comment, please reopen if it's still a problem.
