### ISSUE TITLE
cc_import rule fails cc_binary dependency check

### ISSUE THREAD

**Issue by thezha** [bazelbuild/bazel#4412]
### Description of the problem:

Following the instructions on [cc_import](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_import) doesn't give expected result when importing an external pre-compiled library. Error message seems to say that "cc_import" doesn't belong to the cc_library dependency list. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Set up a new_local_repository in WORKSPACE which points to a directory containing a pre-compiled library
```
new_local_repository(
    name = "hello_world",
    path = "/Users/kainanc/projects/vsi/sandbox/libhello_world",
    build_file = "hello_world.BUILD",
)
```
2. Write local BUILD rule hello_world.BUILD with rule **cc_import**
```
cc_import(
    name = "libhello_world",
    shared_library = "libhello_world.so",
    hdrs = ["hello_world.h"],
    visibility = ["//visibility:public"],
)
```
3. In BUILD, create cc_binary rule to include the import rule
```
cc_binary(
    name = "hi",
    srcs = ["hi.c"],
    deps = ["@hello_world//:libhello_world"]
)
```
4. Run build and fails
> bazel build hi
> ERROR: /Users/kainanc/projects/vsi/sandbox/hello_world/BUILD:22:12: in deps attribute of cc_binary rule //:hi: cc_import rule '@hello_world//:libhello_world' is misplaced here (expected cc_inc_library, cc_library, objc_library or cc_proto_library)
> ERROR: Analysis of target '//:hi' failed; build aborted: Analysis of target '//:hi' failed; build aborted
> INFO: Elapsed time: 0.119s
> FAILED: Build did NOT complete successfully (1 packages loaded)
> 

### What operating system are you running Bazel on?
Tested this on both Ubuntu 16.04 and MacOS High Sierra with bazel 0.9.0 release

### What's the output of `bazel info release`?
release 0.9.0-homebrew

###  Have you found anything relevant by searching the web?
No

### Any other information, logs, or outputs that you want to share?
cc_library() way works just fine

**Comment by mhlopko** [comment]
Can you try with bazel 0.10.0? cc_import was fully implemented only in 0.10.

**Comment by alexanderlobov** [comment]
I have tested `cc_import` from master branch on [this toy project](https://github.com/alexanderlobov/try-bazel/tree/master/cc-import).

It stopped to fail with `cc_import rule '//lib:lib' is misplaced here (expected cc_inc_library, cc_library, objc_library or cc_proto_library)` error. But it still has the same issue with wrong rpath as `cc_library` has: #4480.

**Comment by mhlopko** [comment]
Great, so I'll close this issue now and will take a look on #4480. Thanks!
