### ISSUE TITLE
CI: rules_typescript: Broken on Linux

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#4415]
```
[rules_typescript-node=linux-x86_64] Running shell script
+ /home/ci/.bazel/latest/binary/bazel --bazelrc=/home/ci/workspace/rules_typescript-node=linux-x86_64/bazel.bazelrc build //...
Loading: 
Loading: 0 packages loaded
ERROR: /home/ci/workspace/rules_typescript-node=linux-x86_64/internal/karma/BUILD.bazel:15:1: no such package '@build_bazel_rules_typescript_karma_deps//': npm_install failed:  (/usr/bin/env: node: No such file or directory
) and referenced by '//internal/karma:karma_bin_bin'
ERROR: Analysis of target '//internal/karma:karma_bin' failed; build aborted: no such package '@build_bazel_rules_typescript_karma_deps//': npm_install failed:  (/usr/bin/env: node: No such file or directory
)
INFO: Elapsed time: 0.803s
FAILED: Build did NOT complete successfully (33 packages loaded)
FAILED: Build did NOT complete successfully (33 packages loaded)
script returned exit code 1
```

https://ci.bazel.build/blue/organizations/jenkins/rules_typescript/detail/rules_typescript/104/pipeline/21

Doesn't look like it's Bazel specific, but an issue with an external `node` dep.

cc @alexeagle

**Comment by alexeagle** [comment]
the root cause is 
https://github.com/bazelbuild/rules_nodejs/issues/77

I'm surprised you just started running into this - it seems that node used to be installed on the CI worker machines and now it isn't?

**Comment by jin** [comment]
This might be due to the recent reimaging. @philwo do you know if node has to be installed manually?

**Comment by alexeagle** [comment]
It's probably better to fix it in rules_nodejs, I'll work on that tomorrow morning.

**Comment by jin** [comment]
Green: https://ci.bazel.build/job/rules_typescript/107/

root cause: missing `node`, fixed by @philwo
