### ISSUE TITLE
Please include version in the Debian nightly-built package

### ISSUE THREAD

**Issue by ivucica** [bazelbuild/bazel#4417]
### Description of the problem / feature request:

https://ci.bazel.build/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/nightly/182/

I tried installing the .deb to try out a new feature, but dpkg refuses to do so as the `Version` field is empty.

`Version` field should probably have the next-release's version, plus `~git$BUILD_TIMESTAMP` or `~nightly$JENKINS_ID`. See [what tilde means](https://unix.stackexchange.com/questions/230911/what-is-the-meaning-of-the-tilde-in-some-debian-openjdk-package-version-string).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
wget https://ci.bazel.build/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/nightly/lastSuccessfulBuild/artifact/node=linux-x86_64/variation=/bazel_-linux-x86_64.deb
dpkg -i bazel_-linux-x86_64.deb
```

### What operating system are you running Bazel on?

Debian stretch + some buster

### What's the output of `bazel info release`?

n/a

**Comment by aiuto** [comment]
@meteorcloudy   Does this make sense? Is our current plan to do the debian builds, or have them come from debian? If we will not be the packager, than we probably don't want to do this, as it will create confusion as to which is authoratative.

**Comment by meteorcloudy** [comment]
Yes, we already have [a .deb package](https://github.com/bazelbuild/bazel/blob/master/scripts/packages/debian/BUILD#L80
) for Bazel. But we are hosting that package through our own APT repo because it doesn't meet the standards of getting into Debian distribution. And we no longer offer the nightly build for that artifact since we move from Jenkins to Buildkite. 

@ivucica Is this still an issue for you? Can you try install Bazel by [some other way](https://docs.bazel.build/versions/3.1.0/install-ubuntu.html#install-with-installer-ubuntu)?

**Comment by ivucica** [comment]
I have not installed from a **nightly** build in a *really* long time.

This was really only filed about installing the CI build to try out some at-that-time fresh feature, not about installing from a release .deb or from any properly managed apt repos.

I have no current need to install a CI build, so I have not tried to see if it's still broken. Only if its `Version:` field is still empty, then it's still not installable and the `.deb` is useless as an artifact as `dpkg` rejects it. If the `Version:` field is nowadays populated, then all is good.

**Comment by meteorcloudy** [comment]
@ivucica Thanks for the explanation! Since we no longer provide the nightly Debian package and there seems to be no real need for this, I'll close this issue.
