### ISSUE TITLE
Incorrectly converting git_repository to http_archive

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/bazel#4419]
### Description of the problem / feature request:

bazel 0.9 failed to fetch git_repository rule pin to a tag with `/` in the tag name. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
git_repository(
        name = "io_bazel_rules_jsonnet",
        remote = "https://github.com/xreception/rules_jsonnet.git",
        tag = "patched/6f425a8482ceac19d122944a38d250ae4758de53",  # latest, as of 2017-12-26
)
```

The root cause is that the new git fetcher assumes the tag name is always safe to use for stripping prefixes.

For the above example, the directory in the archive will be named as `rules_jsonnet-patched-6f425a8482ceac19d122944a38d250ae4758de53` instead of `rules_jsonnet-patched/6f425a8482ceac19d122944a38d250ae4758de53`.

**Comment by edbaunton** [comment]
@ashi009 do you have a full example of a repository that can be cloned to reproduce this issue? i.e. has a `WORKSPACE` and `BUILD` since the actual error message is not included in the original report it would be useful to be able to reproduce easily.

**Comment by edbaunton** [comment]
Can you paste the error output? Or link to an example project? I don't understand what you mean by `assumes the tag name is always safe to use for stripping prefixes`.

Do you have the same problem with the `git_repository` skylark rules?

**Comment by ashi009** [comment]
@edbaunton FYR https://github.com/bazelbuild/bazel/blob/ac0d354437c15003e79ec0fec168762cc9b676de/src/main/java/com/google/devtools/build/lib/bazel/repository/GitCloner.java#L311

**Comment by jin** [comment]
Is this still an issue with the new Starlark `git_repository` rule?

**Comment by ashi009** [comment]
> Is this still an issue with the new Starlark `git_repository` rule?

Given the implementation at https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/git.bzl, it seems to me that the new rule no longer performs such conversion for github.com repos.

Feel free to close this issue as obsolete.
