### ISSUE TITLE
Windows, Java launcher: remove '../' in classpath jar

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#4420]
"The Java platform team advised that we shouldn't rely on the JVM supporting "../" in the class path, because it's possible that the JVM won't support that in the future." -- László

We can use junctions to avoid using ../ in classpath jar.

**Comment by laszlocsomor** [comment]
@meteorcloudy : was this bug fixed?

**Comment by meteorcloudy** [comment]
Nope

**Comment by laszlocsomor** [comment]
Thanks. I think P4 would be more appropriate: there's no current problem.
