### ISSUE TITLE
CI rules_go is failing with bazel 0.10.0 RC1 

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#4426]
rules_go fails to build with the RC: `Current Bazel version is 0.10.0rc1, expected at least 0.8.0`
The console output is [here](https://ci.bazel.build/job/Global/job/rules_go/344/console).

This is blocking the 0.10.0 release (#3958).

**Comment by jayconrod** [comment]
I'm looking into this. Feel free to assign to me.

Our version checking code is fairly new, but it's the same as what Kubernetes and TensorFlow are using, so others may be affected.

**Comment by iirina** [comment]
Yes actually I found more similar issues in #4425. I forgot to include rules_go there. Thanks for looking into it.

**Comment by iirina** [comment]
It seems I cannot assign this to you, I don't understand why.

**Comment by jayconrod** [comment]
This should be fixed now. It looks like rules_go is passing in Jenkins, so this can be closed.

**Comment by jin** [comment]
Yes, passing - thanks @jayconrod.

https://ci.bazel.build/blue/organizations/jenkins/Global%2Frules_go/detail/rules_go/348/pipeline

 Closing.

**Comment by thaidn** [comment]
This is failing if Bazel was installed via Homebrew.

bazel version
Build label: 0.10.1-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Oct 11 20:06:37 +50095 (1518702897997)
Build timestamp: 1518702897997
Build timestamp as int: 1518702897997

I'm getting this stack trace:

Traceback (most recent call last):
	File "/Users/thaidn/tink/cloudcryptosdk/WORKSPACE", line 518
		go_rules_dependencies()
	File "/private/var/tmp/_bazel_thaidn/df2e59bf257c59e48735734d799e3be1/external/io_bazel_rules_go/go/private/repositories.bzl", line 28, in go_rules_dependencies
		check_version(MINIMUM_BAZEL_VERSION)
	File "/private/var/tmp/_bazel_thaidn/df2e59bf257c59e48735734d799e3be1/external/io_bazel_rules_go/go/private/common.bzl", line 160, in check_version
		fail("\nCurrent Bazel version is {}, ...))

Current Bazel version is 0.10.1-homebrew, expected at least 0.8.0
ERROR: Error evaluating WORKSPACE file

Same error observed by other people: https://github.com/tensorflow/tensorflow/issues/16654 and https://github.com/bazelbuild/bazel-skylib/issues/17.

**Comment by jayconrod** [comment]
@thaidn Based on the stack trace, it looks like you may be using an older version of rules_go that still has a broken version check. Do you still see this after upgrading to a newer version?
