### ISSUE TITLE
CI rules_k8s fails with bazel 0.10.0 RC1

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#4427]
On linux the following error is reported:
```
ERROR: /home/ci/workspace/Global/rules_k8s-variation=,node=linux-x86_64/examples/hellohttp/nodejs/BUILD:20:1: no such package '@examples_hellohttp_npm//': npm_install failed:  (/usr/bin/env: node: No such file or directory) and referenced by '//examples/hellohttp/nodejs:server'

ERROR: Analysis of target '//examples/hellohttp/nodejs:staging' failed; build aborted: no such package '@examples_hellohttp_npm//': npm_install failed:  (/usr/bin/env: node: No such file or directory)
```

Full console output is [here](https://ci.bazel.build/job/Global/job/rules_k8s/198/console).
This is blocking the 0.10.0 release (#3958).

**Comment by iirina** [comment]
The same error occurs for rules_typescript (see [pipeline](https://ci.bazel.build/blue/organizations/jenkins/Global%2Frules_typescript/detail/rules_typescript/310/pipeline/)).

**Comment by jin** [comment]
Green from https://ci.bazel.build/blue/organizations/jenkins/Global%2Frules_k8s/detail/rules_k8s/199/pipeline

Closing..
