### ISSUE TITLE
Can't use scala_library target in java_test

### ISSUE THREAD

**Issue by orrsella** [bazelbuild/bazel#443]
One of the core strengths of Scala is its inteop with Java, in both directions. Therefore it should probably be possible to use Scala code from Java tests. At Wix we have a large mixed Scala/Java code base. It's very common for classes to be in Java and have their tests written in Scala.

```bash
$ ./bazel test //...:
ERROR: /Users/orr/Dev/Projects/bazel-test/my-java-lib/src/test/java/com/example/BUILD:5:12: in deps attribute of java_test rule //my-java-lib/src/test/java/com/example:test: scala_library rule '//my-java-lib/src/main/scala/com/example:scala' is misplaced here (expected cc_binary, cc_library, genrule, genproto, java_import, java_library, sh_binary or sh_library).
ERROR: Analysis of target '//my-java-lib/src/test/java/com/example:test' failed; build aborted.
INFO: Elapsed time: 0.080s
ERROR: Couldn't start the build. Unable to run tests.
```

**Comment by damienmg** [comment]
laurentlb@ isn't yesterday modifications fixing that?

**Comment by laurentlb** [comment]
As shown in the example, the current workaround is to use a java_import (https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/scala/test/BUILD).
Of course, we'll remove this limitation in the future.

**Comment by orrsella** [comment]
@laurentlb Yup, workaround works as expected – thanks. Do you want to keep this issue until it's no longer needed, or to close for now?
