### ISSUE TITLE
Support supplying jdeps data via java_common.create_provider

### ISSUE THREAD

**Issue by brendandouglas** [bazelbuild/bazel#4432]
Jdeps data is required by IDEs. It's available in the old `java` provider, but there's no way to expose it via `java_common.provider`, when created via `java_common.create_provider`

See https://github.com/bazelbuild/intellij/issues/207

**Comment by iirina** [comment]
@dbabkin FYI

**Comment by johnynek** [comment]
Any update on this?

@ittaiz isn’t this an alternative the jars2labels map scala rules is maintaining at analysis time? I think this is at build time instead.

**Comment by ittaiz** [comment]
The way I understand it (and @tomlu / @cushon  can easily correct me if I'm wrong) the direction java-bazel people are aiming at is moving (or have moved) from jdeps and into having each jar have its own originating label and then the jdeps output can be dropped.
The enforcing tool (I think turbine in the case of java rules and scala compiler plugin in the case of rules_scala) can output a message saying what is the offending target and what is the offended target.

**Comment by ittaiz** [comment]
@brendandouglas can you please explain why the IDE needs jdeps? from @cushon's explanation I understand why the rules need them (turbine? JavaBuilder?) but I don't understand why the IDE needs it in addition to what JavaInfo has.
Main reason I ask is because we (rules_scala) currently don't generate jdeps and want to understand what IDE functionality we're missing.
Thanks!

**Comment by ittaiz** [comment]
I think there’s something I’m missing.
Is the optimization only about “filtering out those that are derived from
the project sources” or is it something else which I’m missing?
Does jdeps contain additional information about the transitive dependencies
that allows more optimization?

Thank you for taking the time to answer!

**Comment by brendandouglas** [comment]
Filtering out jars from project sources is separate.

Without jdeps we're forced to include the entire transitive closure of deps to guarantee that source files will completely resolve. With jdeps we can greatly limit what gets added to the project libraries (only jars needed to resolve sources will be added).
