### ISSUE TITLE
Provide a canonical way to assert minimum and maximum bazel_versions in bzl files

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#4433]
External repositories are implementing their own copy of Bazel version checks as seen in #4425 and causes fragmentation in implementations.

Bazel already provides this function in https://github.com/bazelbuild/bazel-integration-testing/blob/master/bazel_version.bzl, but that is still an external dependency. This is something that we can move into `@bazel_tools`, and set that as the canonical way to check and parse versions. The caveat is that older Bazel versions do not have it in their `@bazel_tools`, and therefore have to depend on bazelbuild/bazel-integration-testing for the function.

**Comment by fahhem** [comment]
Another implementation of this check: https://github.com/google/protobuf/pull/3968

**Comment by jin** [comment]
On second thought, it seems that https://github.com/bazelbuild/bazel-skylib will be a good home for  `check_bazel_version`.

**Comment by jin** [comment]
This was just merged into Skylib. Copy and paste this into your WORKSPACE and it should just work:

```py
git_repository(
    name = "bazel_skylib",
    remote = "https://github.com/bazelbuild/bazel-skylib",
    commit = "34d62c4490826f7642843e0617d7fa614994ef79",
)

load("@bazel_skylib//:lib.bzl", "versions")
versions.check("0.5.0")
```
