### ISSUE TITLE
java targets can't be built without disabling sandbox?

### ISSUE THREAD

**Issue by mzhaom** [bazelbuild/bazel#444]
```
INFO: From GenProtoSrcJar lwms/acs/proto/libapconfig_srcjar.srcjar:
external/local-jdk/bin/jar: error while loading shared libraries: libjli.so: cannot open shared object file: No such file or directory
ERROR: /usr/local/home/mzhao/s/m3/main/tools/build_rules/proto_library.bzl:110:3: error executing shell command: 'rm -rf bazel-out/crosstool_v5_gcc-fastbuild/bin/lwms/acs/proto/libapconfig_srcjar.srcjar.proto_output && mkdir bazel-out/crosstool_v5_gcc-fastbuild/bin/lwms/acs/proto/libapconfig_srcjar.srcjar.prot...' failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped).
```

Building with --spawn_strategy=standalone solves the issue

**Comment by mzhaom** [comment]
I wonder whether "//external:jar" needs more precise definition since it's not just a single binary but it also needs some .so files to run, I guess these .so files are not declared so that sandbox doesn't set them up.

**Comment by philwo** [comment]
Looks like in the proto_library.bzl rules, your GenProtoSrcJar action is missing the JDK as an input to the action. Take a look at my commit https://github.com/bazelbuild/bazel/commit/c8db70c7bc8f9cf916daac42010a4886b825fc63, where I fixed this for our https://github.com/bazelbuild/bazel/blob/master/tools/build_rules/java_rules_skylark.bzl or https://github.com/bazelbuild/bazel/blob/master/tools/build_rules/genproto.bzl. :)

If you can point me to the proto_library.bzl file that you're using, I can have a look too.

**Comment by philwo** [comment]
Please re-open if this is still an issue.
