### ISSUE TITLE
`cc_*` rules in remote repositories should not require setting `includes`

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel#445]
Following up from the discussion in #439.

Currently, `cc_*` targets in the BUILD files for remote repositories must set the `includes` attribute (see the "Including external libraries" section of http://bazel.io/docs/cpp.html).

I think it would be better if this requirement can be lifted. This requirement would be particularly troublesome if the remote repository had separate BUILD files in subdirectories, for example:

```
[workspace]/
    WORKSPACE
    foo/
        BUILD
        foo.cc
        foo.h
    bar/
        BUILD
        bar.cc
        bar.h
        baz/
            BUILD
            baz.cc
            baz.h
```

In this case, all `cc_*` targets in `bar/baz/BUILD` would need `includes = ["../.."]`, etc. if this project were to be used as a remote repository.

Ideally, the default include path for `cc_*` targets inside a remote repository should be the root of the remote repository itself, though the include path `cc_*` targets in the outer workspace that is importing the remote repository would be the root of the workspace as usual.

I am not sure how difficult it would be to remove this restriction, but it would be better to be able to use a single set of BUILD files regardless of whether a project is being built by itself or used as a remote repository.

**Comment by kchodorow** [comment]
Agreed that this is the desired functionality, but I don't think it'll be trivial to implement.

**Comment by ulfjack** [comment]
I think it's a one line change in CcLibraryHelper. Will take a look Monday
if noone else does.

**Comment by ulfjack** [comment]
I think this should work:
https://github.com/bazelbuild/bazel/compare/master...ulfjack:cpp-include-path

This will always first search for an include in the same repository as the
rule is in, and then check the repositories of any rules in deps (including
transitively). If everything is in the same repository, it should just work.

Tested:
$ cat WORKSPACE
local_repository(
    name = "bazel",
    path = "/Users/ulfjack/Google/bazel",
)

$ bazel build @bazel//examples/cpp:all
INFO: Reading 'startup' options from /Users/ulfjack/.bazelrc: --watchfs
........
INFO: Found 5 targets...
INFO: Elapsed time: 3,244s, Critical Path: 0,82s



Errm, this is odd:
$ bazel test @xyz//examples/cpp:all
INFO: Reading 'startup' options from /Users/ulfjack/.bazelrc: --watchfs
........
INFO: Found 3 targets and 2 test targets...
FAIL: //examples/cpp:hello-fail_test (see
/private/var/tmp/_bazel_ulfjack/3f0275ccb9d6b5d2d674a0bdedafc265/example/bazel-out/local_darwin-fastbuild/testlogs/examples/cpp/hello-fail_test/test.log).
INFO: Elapsed time: 2,720s, Critical Path: 0,65s
//examples/cpp:hello-success_test
 PASSED
//examples/cpp:hello-fail_test
FAILED

Executed 2 out of 2 tests: 1 test passes and 1 fails locally.
There were tests whose specified size is too big. Use the
--test_verbose_timeout_warnings command line option to see which ones these
are.


How is it finding a remote repository named xyz?

Ok, maybe it's not working. When I remove examples from the base_workspace
over in the bazel repo, it fails saying it can't find the target.

**Comment by ulfjack** [comment]
I think that's #389.
