### ISSUE TITLE
Loading bazel through PATH does not work when having a bazel.bazelrc file next to it

### ISSUE THREAD

**Issue by sergiocampama** [bazelbuild/bazel#4452]
### Description of the problem / feature request:

Imagine for example that we have the following folder structure:

```
~/bin/bazel
~/bin/bazel.bazelrc
```

We then also have the following configuration for PATH, making it easy to call bazel from any folder.

```
PATH="~/bin:$PATH"
```

Now we find ourselves in `~/Dev/SecretProject`. If I call `bazel` from this folder, it will be found because of the `PATH` configuration. But the `bazel.bazelrc` will not be loaded. This is because [this code](https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/workspace_layout.cc#L73) assumes that `bazel` resides in `$CWD`, so it prepends `$CWD` to the invocation name (or `$0` in bash) and appends `basename($0) + "rc"`. So it will effectively load `~/Dev/SecretProject/bazel.bazelrc`. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

From within the bazel github repository:

```
$ bazel build //src:bazel
$ mkdir -p ~/bin
$ cp bazel-bin/src/bazel ~/bin/bazel
$ # Add a broken bazel.bazelrc file next to bazel.
$ echo "build --nonexistantflag" > ~/bin/bazel.bazelrc 
# This command should fail, as bazel should load ~/bin/bazel.bazelrc
$ PATH="$HOME/bin:$PATH" bazel build //src:bazel
# This command does fail, as we're invoking bazel directly through a relative link.
$ ~/bin/bazel build //src:bazel
```

### What operating system are you running Bazel on?

macOS High Sierra 10.13.2

### What's the output of `bazel info release`?

This is at HEAD

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Bootstrapped with bazel 0.9.0 homebrew

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

07c4e3648e3b7a521b6706ffc5cbcdeca1ebf4e1
455f005ed742ded601065d8db80e24a1d8d247d8

###  Have you found anything relevant by searching the web?

Nope

### Any other information, logs, or outputs that you want to share?

Nope

**Comment by philwo** [comment]
I might be missing something, but Bazel should definitely not load a bazel.bazelrc file placed next to its binary, whether you call it via PATH nor via its absolute path.

The locations for bazelrc files are documented here: https://docs.bazel.build/versions/master/guide.html#where-are-the-bazelrc-files

It seems like this has been fixed in the meantime, because when I try to repro it, it works as expected now:

```
philwo@philwo-imacpro ~/src/bazel (master) cp bazel-bin/src/bazel ~/bin2/
philwo@philwo-imacpro ~/src/bazel (master) echo "build --nonexistantflag" > ~/bin2/bazel.bazelrc

philwo@philwo-imacpro ~/src/bazel (master) PATH="$HOME/bin2:$PATH" bazel build //src:bazel
[...]
Success.

philwo@philwo-imacpro ~/src/bazel (master) ~/bin2/bazel build //src:bazel
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/Users/philwo/bin2/bazel.bazelrc
[...]
Success.
```
