### ISSUE TITLE
bazel-slow-tests are failing with bazel 0.10.0rc2

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#4454]
The log is [here](https://ci.bazel.build/job/Global/job/bazel-slow-tests/189/console). The problems are related to docker. It seems it cannot fetch some files.

@philwo can you take a look? Do you know what the issue is?

Blocks #3958.

**Comment by philwo** [comment]
Fixed with https://github.com/bazelbuild/bazel/commit/96c654d43eb2906177325cbc2fc2b1e90dbcc792

Can you please cherry-pick it? Thanks!

**Comment by philwo** [comment]
It's just a test failure due to our CI config, though! Nothing to do with the actual Bazel binary, so it's not blocking the release.

**Comment by iirina** [comment]
Thanks! Since I cannot see the actual result of bazel-slow-tests, I considered it a release blocker. Stands in the way of finding other release blockers. :smiley:
