### ISSUE TITLE
Can't query packages where ignoring conditions creates cycles.

### ISSUE THREAD

**Issue by devnev** [bazelbuild/bazel#4457]
### Description of the problem / feature request:

A vendored dependency has two packages `A` and `B` which use `select()`s in their dependencies. Depending on the target platform, they produce either an A->B dependency or a B->A dependency. Querying for deps breaks on this package.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Hopefully description is enough as actually creating platform-dependend builds seems quite complicated...

### What operating system are you running Bazel on?

Ubuntu 16.04.3

### What's the output of `bazel info release`?

release 0.9.0

###  Have you found anything relevant by searching the web?

Issue #967 is a discussion of the same cause but with a different use-case. 

### Any other information, logs, or outputs that you want to share?

The dependency that orignially caused this was https://github.com/shirou/gopsutil, where subpackages "process" and "host" have the quasi-cycle.

**Comment by gregestren** [comment]
Just as in https://github.com/bazelbuild/bazel/issues/967, [bazel cquery](https://docs.bazel.build/versions/master/cquery.html) should resolve this.

Feel free to re-open if anything remains amiss.
