### ISSUE TITLE
runfiles: provide language-specific runfiles libraries

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4460]
**Update(2018/04/17)**: [link to design doc](https://docs.google.com/document/d/e/2PACX-1vSDIrFnFvEYhKsCMdGdD40wZRBX3m3aZ5HhVj4CtHPmiXKDCxioTUbYsDydjKtFDAzER5eg7OjJWs3V/pub).

### Blockers

Blocking:
- "Windows, testing: make //src/test/shell/... run on Windows" (https://github.com/bazelbuild/bazel/issues/4930)

### Feature requests: what underlying problem are you trying to solve with this feature?

FR: provide language-specific runfiles libraries, with implementations of platform-independent `rlocation`, for the main languages: Bash, Java, C++, Python.

Motivation:
- easier for users: they don't need to worry about runfiles semantics, just include a library and use runfiles the same way on every platform
- easier for Bazel developers: we can change runfiles semantics if we need to, and only need to change the libraries and release Bazel for people to get the new semantics

**Comment by laszlocsomor** [comment]
related: https://github.com/bazelbuild/bazel/issues/3839

**Comment by alexeagle** [comment]
The release notes for 0.8.0 include
> New features:
> runfiles, sh: Shell scripts may now depend on
> //src/tools/runfiles:runfiles_sh_lib and source runfiles.sh. The
> script defines the rlocation function which returns runfile
> paths on every platform.

Is this actually usable today? Maybe it works under Windows but not other platforms?

**Comment by laszlocsomor** [comment]
No, that one is not usable. But the 0.14.0rc1 has this announcement:

> New features:
>
>  - Bash,runfiles: use the new platform-independent library in
>    `@bazel_tools//tools/bash/runfiles` to access runfiles
>    (data-dependencies). See
>    https://github.com/bazelbuild/bazel/blob/master/tools/bash/runfiles/runfiles.bash for usage information.

and that one is good on all platforms!

There's a caveat though: the initialization code is long and complex (20 lines):

https://github.com/bazelbuild/bazel/blob/eb35e41242e1f9fb0ae1061623272c891237c8a8/tools/bash/runfiles/runfiles.bash#L38-L58

I haven't found a way to automatically source this file without the highlighted init code.

**Comment by laszlocsomor** [comment]
Done -- Bazel 0.15.0 contains the runfiles library for Python, Bash, C++, and Java, and they all support `rlocation()`. None of them supports `rfind()` yet (see #4334).

**Comment by alexeagle** [comment]
FYI, on my Windows machine the `grep` and `cut` dependencies in the runfiles.bash initializer block don't work. In cmd.exe and cmder.exe I get a version mismatch on a cygwin1.dll, in PowerShell grep and cut aren't found.
Does this feature require new installation instructions on Windows?

**Comment by laszlocsomor** [comment]
Thanks for reporting that! How do you run the binary -- directly from bazel-bin, using "bazel run", or as part of another rule (e.g. genrule)?

**Comment by laszlocsomor** [comment]
Meanwhile I ran into the same problem. @meteorcloudy knows how to fix it -- we just need to use `bash -l` in the sh_binary's launcher.

**Comment by alexeagle** [comment]
Would you like a separate issue to track that? Or maybe re-open this one?

**Comment by alexeagle** [comment]
Opened a separate issue since this is still broken in Bazel 0.16
