### ISSUE TITLE
Bazel support for full proto on Android (for json and prototxt)

### ISSUE THREAD

**Issue by vmax** [bazelbuild/bazel#4461]
## Android: allow java_proto_library as dependency for android_binary
It's impossible to utilize full protobuf library on Android device if build is done by `bazel`

### Feature requests: what underlying problem are you trying to solve with this feature?

I need to include full runtime library together with `protobuf-java-util` unless there's a way to parse `json` in `lite` version of which I don't know.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create proto file, add it as `java_proto_library`, add that library as dependency to `android_binary`

### What operating system are you running Bazel on?

macOS 10.13.2

### What's the output of `bazel info release`?

release 0.9.0-homebrew

### Any other information, logs, or outputs that you want to share?

To allow this, `"java_proto_library"` should be added [here](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/android/AndroidRuleClasses.java#L318).

**Comment by jin** [comment]
cc @ahumesky

**Comment by codesuki** [comment]
@jin  Hi is there any progress on this?

We definitely want to have this, too.
According to this issue protobuf-java will scrap lite support. 
https://github.com/google/protobuf/issues/4314

Also we are using any which doesn't seem to work with lite.

**Comment by oferb** [comment]
See internal draft cl/189732367
Thanks!
