### ISSUE TITLE
Make private headers for cc_library "just work" for external and generated files

### ISSUE THREAD

**Issue by drigz** [bazelbuild/bazel#4463]
Add a way of including private headers (ie, headers included by files in `srcs` that should *not* be available to targets that depend on this `cc_library`) that works the same when the `cc_library` is in an external repo and when the headers are generated files.

### Feature requests: what underlying problem are you trying to solve with this feature?

Currently, the only way I'm aware of including a private header is with `copts = ["-Ipath/to/hdr/dir"]`. However, this needs a different path when the target is used from an external repository, resulting in code like this (from [ceres](https://github.com/ceres-solver/ceres-solver/blob/c1075cd313e1e68af21c714d55488255f04dcb69/bazel/ceres.bzl#L173)):

```
    # The path to internal/ depends on whether Ceres is the main workspace or
    # an external repository.
    if native.repository_name() != '@':
        internal = 'external/%s/internal' % native.repository_name().lstrip('@')
    else:
        internal = 'internal'
    copts = ["-I" + internal],
```

or if the header is generated, like this (from [glog](https://github.com/google/glog/blob/028d37889a1e80e8a07da1b8945ac706259e5fd8/bazel/glog.bzl#L11)):

```
    if native.repository_name() != '@':
        gendir = '$(GENDIR)/external/' + native.repository_name().lstrip('@')
    else:
        gendir = '$(GENDIR)'
    copts = ["-I%s/glog_internal" % gendir],
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Download and extract [private_headers.tar.gz](https://github.com/bazelbuild/bazel/files/1634393/private_headers.tar.gz)
1. `cd private_headers/ws1`
1. `bazel build :lib` (works)
1. `cd ../ws2`
1. `bazel build :exthdr_lib` (fails)
1. `bazel build :genhdr_lib` (also fails)

### What operating system are you running Bazel on?

Ubuntu 14.04

### What's the output of `bazel info release`?

release 0.9.0

###  Have you found anything relevant by searching the web?

It is related to #2172, but that is specifically about platform independence.
#1950 concerns the difficulty of using private generated headers, but (a) is closed due to inactivity and (b) doesn't mention the complexity of use from external repos.
#2476 might also have been avoided, since it appears to stem from the use of `includes = ["$(GENDIR)"]` ([source](https://github.com/gflags/gflags/blob/v2.2.0/bazel/gflags.bzl#L88)).

**Comment by mhlopko** [comment]
I'd say this issue has very little to do with C++, it's more about how we layout execroot and repositories. C++ is only a victim with its include directories. Luckily @aehlig is going to save us all from this suffering :)

**Comment by sffc** [comment]
I just hit this issue in the context of a header file created by a genrule.

**Comment by mhlopko** [comment]
Header created by a genrule should be fixed by https://github.com/bazelbuild/bazel/commit/dc986d290bad8a76d3429f73c8244376b4c59494 (not yet in released bazel).

**Comment by schroederc** [comment]
I just hit this in the context of trying to get https://github.com/google/kythe/tree/80edc69ef3165427ea8159d53f207888629ff75b/third_party/llvm/src/BUILD#L45 to build as an external repository.  It's not possible to build `@io_kythe//third_party/llvm/src:clang_builtin_headers` while it *is* possible to build `//third_party/llvm/src:clang_builtin_headers` (even if `io_kythe` is the primary workspace).

**Comment by mhlopko** [comment]
Cody, can you try building with bazel > 0.16, and with that `GENDIR` line removed? `//third_party/llvm` seems to already set the includes, so the headers should be available to the target. If not, I'd recommend fixing it on the `//thid_party/llvm` side.
