### ISSUE TITLE
[Feature][Android] Support for consumer proguard files in AARs

### ISSUE THREAD

**Issue by jcayzac** [bazelbuild/bazel#4467]
Following [this comment](https://github.com/bazelbuild/bazel/issues/348#issuecomment-358003363) I'd like to request support for adding consumer proguard files when creating AARs.

Currently there's no obvious way for packaging a consumer proguard file, something that's standard when using gradle and AGP to build a library.

[Anatomy of an AAR file](https://developer.android.com/studio/projects/android-library.html#aar-contents) shows the `proguard.txt` packaged inside the AAR, to be eventually merged with the proguard configuration of the consuming application.

**Comment by ronshapiro** [comment]
Is this on the horizon? Is there a pointer to where this should be implemented?

**Comment by aj-michael** [comment]
Fix pending in https://bazel-review.googlesource.com/c/48690/
