### ISSUE TITLE
nightly debs aren't installable

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/bazel#4468]
If you install from a nightly build's deb ([like this one](https://ci.bazel.build/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/nightly/195/artifact/node=linux-x86_64/variation=/bazel_-linux-x86_64.deb)), you'll get this error:

```
dpkg: error processing archive bazel_195-linux-x86_64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'bazel':
 error in 'Version' field string '': version string is empty
```

(which is a bummer because a blocker I've got was recently fixed)

**Comment by jmhodges** [comment]
(The bazel--without-jdk-installer-linux-x86_64.sh does, though, for others trying to make nightlys work!)

**Comment by meisterT** [comment]
We don't build nightly debian packages anymore.
We recommend https://github.com/bazelbuild/bazelisk as a way to use the latest builds.
