### ISSUE TITLE
Can't copy-paste from http://bazel.io/docs/external.html

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#447]
The example on http://bazel.io/docs/external.html has '>' at the beginning, preventing copy-pasting it into a terminal.

**Comment by kchodorow** [comment]
...the example with /path/to/skunkworks and /path/to/teleporter/project?  It's not exactly meant to be copy-pasted as-is.

**Comment by ulfjack** [comment]
Sure, but people will still do it. What else are they supposed to do?

**Comment by kchodorow** [comment]
Copy the first line and then actually type in the path to their project.  But I guess we could add a copy-pastable template.

**Comment by kchodorow** [comment]
After consideration, this WAI.
