### ISSUE TITLE
"build --action_env=PATH" in /etc/bazel.bazelrc removes PATH from build actions

### ISSUE THREAD

**Issue by dws-uber** [bazelbuild/bazel#4475]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

When `/etc/bazel.bazelrc` is present and contains `build --action_env=PATH`, bazel _removes_ `PATH` from the environment, at least when building C++.

### Feature requests: what underlying problem are you trying to solve with this feature?

There is a discrepancy between the docs for --action_env and what it actually does. The docs say that it should _add_ variables to the environment, but it seems that there are cases where it _removes_ variables from the environment.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ cat WORKSPACE
$ cat BUILD
cc_binary(
    name = "hello",
    srcs = ["hello.cc"]
)
$ cat hello.cc
#include <stdio.h>
int main(void) { printf("%s", "hello world\n"); return 0; }
```

Verify that you have no `/etc/bazel.bazelrc` file.  Then do `bazel build -s //:hello` and observe that the printed actions include PATH=<path>.

Verify that you have `/etc/bazel.bazelrc` and that it contains `build --action_env=PATH`.  Then do `bazel build -s //:hello` and observe that the printed actions do NOT include PATH=<path>

### What operating system are you running Bazel on?

Ubuntu 14.04.5 LTS

### What's the output of `bazel info release`?

release 0.9.0- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

./compile.sh

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

An example output with no `/etc/bazel.bazelrc`:

```
........
Loading:
Loading: 0 packages loaded
Analyzing: target //:hello (5 packages loaded)
INFO: Analysed target //:hello (8 packages loaded).
INFO: Found 1 target...
[0 / 6] no action
SUBCOMMAND: # //:hello [action 'Compiling hello.cc']
(cd /home/dws/.cache/bazel/_bazel_dws/976b33b611d60f37e083b7bf0feab613/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/_objs/hello/hello.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/_objs/hello/hello.pic.o' -fPIC -iquote . -iquote bazel-out/k8-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/k8-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c hello.cc -o bazel-out/k8-fastbuild/bin/_objs/hello/hello.pic.o)
SUBCOMMAND: # //:hello [action 'Creating runfiles tree bazel-out/k8-fastbuild/bin/hello.runfiles']
(cd /home/dws/.cache/bazel/_bazel_dws/976b33b611d60f37e083b7bf0feab613/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
  _bin/build-runfiles bazel-out/k8-fastbuild/bin/hello.runfiles_manifest bazel-out/k8-fastbuild/bin/hello.runfiles)
SUBCOMMAND: # //:hello [action 'Linking hello']
(cd /home/dws/.cache/bazel/_bazel_dws/976b33b611d60f37e083b7bf0feab613/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -o bazel-out/k8-fastbuild/bin/hello '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -Wl,-S -Wl,@bazel-out/k8-fastbuild/bin/hello-2.params)
Target //:hello up-to-date:
  bazel-bin/hello
INFO: Elapsed time: 1.644s, Critical Path: 0.15s
INFO: Build completed successfully, 6 total actions
```

An example output when `/etc/bazel.bazelrc` contains `build --action_env=PATH`:

```
........
Loading:
Loading: 0 packages loaded
Analyzing: target //:hello (5 packages loaded)
INFO: Analysed target //:hello (8 packages loaded).
INFO: Found 1 target...
[0 / 6] [-----] Writing file hello-2.params
SUBCOMMAND: # //:hello [action 'Creating runfiles tree bazel-out/k8-fastbuild/bin/hello.runfiles']
(cd /home/dws/.cache/bazel/_bazel_dws/976b33b611d60f37e083b7bf0feab613/execroot/__main__ && \
  exec env - \
  _bin/build-runfiles bazel-out/k8-fastbuild/bin/hello.runfiles_manifest bazel-out/k8-fastbuild/bin/hello.runfiles)
SUBCOMMAND: # //:hello [action 'Compiling hello.cc']
(cd /home/dws/.cache/bazel/_bazel_dws/976b33b611d60f37e083b7bf0feab613/execroot/__main__ && \
  exec env - \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/_objs/hello/hello.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/_objs/hello/hello.pic.o' -fPIC -iquote . -iquote bazel-out/k8-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/k8-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c hello.cc -o bazel-out/k8-fastbuild/bin/_objs/hello/hello.pic.o)
SUBCOMMAND: # //:hello [action 'Linking hello']
(cd /home/dws/.cache/bazel/_bazel_dws/976b33b611d60f37e083b7bf0feab613/execroot/__main__ && \
  exec env - \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -o bazel-out/k8-fastbuild/bin/hello '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -Wl,-S -Wl,@bazel-out/k8-fastbuild/bin/hello-2.params)
Target //:hello up-to-date:
  bazel-bin/hello
INFO: Elapsed time: 1.682s, Critical Path: 0.16s
INFO: Build completed successfully, 6 total actions
```

I'll note that I first noticed this problem in the context of a much larger build system using a different compiler toolchain where program links would actually _fail_ if `PATH` was absent.  We knew that this happened on systems where people had installed a bazel package -- but we didn't know why simply installing this bazel package would make all our builds fail. Once I tracked down the source of the problem, I was able to work around it in our build system by invoking its bazel with `--nomaster_bazelrc` in order to avoid being affected by the `/etc/bazel.bazelrc` that comes with the install of a bazel package.

**Comment by katre** [comment]
This should be fixed by #4850.
