### ISSUE TITLE
Symlinks to directories starting with ../.. confuse the sandboxing code

### ISSUE THREAD

**Issue by bsilver8192** [bazelbuild/bazel#448]
If an action takes a symlink to a directory which starts with ../.. as an input, the sandboxing code fails with a very un-helpful error message:
```
src/main/tools/namespace-sandbox.c:341: mkdir(path, 0755): File exists
```

I think the right solution is to detect this situation and print some kind of friendly error message. Currently, if the directory is an input to a skylark action, no error or warning whatsoever is printed out.

I looked into why, and it's really complicated, so I'm not particularly confident in the rest of this paragraph. I think the problem is that the sandboxing code starts by bind-mounting the directory containing the symlink. This also brings in the "source" (not-bind-mounted) symlink, which is broken because there's an intermediate symlink in the paths to source files which means the target of the symlink isn't present in that file tree. This means that stat returns ENOENT but mkdir complains that EEXIST, which leads to the current error. That one's trivial to solve, but the kernel also tries to dereference that broken symlink when the sandboxing code goes to bind-mount the symlink, which doesn't work. To actually support this, I think the sandboxing code needs to (correctly) resolve 1 level of symlink and use that when calculating the set of paths to mount, but that's hard... I worked around it by globbing files instead of taking directories as inputs, which is probably a better idea anyways.

Here's a patch which adds a (failing) test for this:
```patch
diff --git a/src/test/shell/bazel/bazel_sandboxing_test.sh b/src/test/shell/bazel/bazel_sandboxing_test.sh
index 4403b07..77b59a2 100755
--- a/src/test/shell/bazel/bazel_sandboxing_test.sh
+++ b/src/test/shell/bazel/bazel_sandboxing_test.sh
@@ -79,6 +79,10 @@ EOF
   ln -s $PWD/examples/genrule/symlinks/ok/sub examples/genrule/symlinks/a/b
   ln -s ../x.txt examples/genrule/symlinks/a/b/x.txt
 
+  # Create a symlink to a directory up two levels.
+  mkdir -p examples/genrule/symlinks/{dir_with_link/dir,dir_target}
+  ln -s ../../dir_target examples/genrule/symlinks/dir_with_link/dir/link
+
   cat << 'EOF' > examples/genrule/BUILD
 genrule(
   name = "works",
@@ -116,6 +120,13 @@ genrule(
 )
 
 genrule(
+  name = "dir_symlink",
+  srcs = [ "symlinks/dir_with_link" ],
+  outs = [ "dir_symlink.txt" ],
+  cmd = "touch $@",
+)
+
+genrule(
   name = "breaks1",
   srcs = [ "a.txt" ],
   outs = [ "breaks1.txt" ],
@@ -199,6 +210,16 @@ function test_sandbox_relative_symlink_in_inputs() {
     || fail "Genrule didn't produce output: examples/genrule:relative_symlinks"
 }
 
+# Test for symlinks to directories up at least two levels.
+#
+# If the code doesn't properly resolve symlinks when doing the bind mounting,
+# this will fail because the directory the symlink points to doesn't exist in the
+# sandbox.
+function test_sandbox_dir_symlink() {
+  bazel build --genrule_strategy=sandboxed examples/genrule:dir_symlink \
+    || fail "Sandbox didn't work with symlink to directory"
+}
+
 function test_sandbox_undeclared_deps() {
   bazel build --genrule_strategy=sandboxed \
     examples/genrule:breaks1 \
```

**Comment by hanwen** [comment]
can you see if this https://github.com/bazelbuild/bazel/commit/76c0e498deb29beeeeaa19595f50d2524c16c0aa fixes it?

**Comment by bsilver8192** [comment]
I tried it on top of aff46bc2f0e59cb9b59f6db982ddd490cf1d2b3c and it still fails. Also, I think my proposed test from above is flaky in some way...

**Comment by philwo** [comment]
I think this is obsolete due to the new sandbox, but please re-open if it becomes a problem again.
