### ISSUE TITLE
Document Improve: example to build standalone jar package for sayhi

### ISSUE THREAD

**Issue by netroby** [bazelbuild/bazel#449]
At the first example , the document just show how to build and run , but not tell how to build standalone jar package.

the command was like this:

```
bazel build //:my-runner_deploy.jar
INFO: Found 1 target...
Target //:my-runner_deploy.jar up-to-date:
  bazel-bin/my-runner_deploy.jar
INFO: Elapsed time: 0.549s, Critical Path: 0.16s

```
to run standalone jar which just built by bazel

```
java -jar bazel-bin/my-runner_deploy.jar
```

If we just put these document after 

```
$ bazel build //:my-runner
INFO: Found 1 target...
Target //:my-runner up-to-date:
  bazel-bin/my-runner.jar
  bazel-bin/my-runner
INFO: Elapsed time: 1.021s, Critical Path: 0.83s
$ bazel-bin/my-runner
Hi!
```

seems easily to let us getting started

**Comment by netroby** [comment]
http://bazel.io/docs/getting-started.html

**Comment by kchodorow** [comment]
I think that `java -jar bazel-bin/my-runner_deploy.jar` is general Java knowledge, not specific to Bazel, and it won't add much to add it to the documentation (especially since how to run is covered directly above that section).

**Comment by netroby** [comment]
Oh, my point it to show how to built for standalone jar file

```
bazel build //:my-runner_deploy.jar
```

**Comment by damienmg** [comment]
could make sense.

**Comment by kchodorow** [comment]
It does:

> To build a self-contained jar that can be deployed, build runner_deploy.jar (or, more generally, <target-name>_deploy.jar):
>    `$ bazel build //src/main/java/com/example/cmdline:runner_deploy.jar`

Am I missing something?

**Comment by damienmg** [comment]
You are totally right, sorry, my bad.

**Comment by netroby** [comment]
The document i had see, but if we want to show new user a quick hello world jar package, the documentation should be adjusted.
Anyway, thanks for you time.

**Comment by damienmg** [comment]
Oh I see you meant in example/java/README.md
Sorry we understood in the tutorial.

**Comment by damienmg** [comment]
Well no sorry I shouldn't answer so fast. Let's keep this one closed.
