### ISSUE TITLE
deb with pre-extracted bazel

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel#4492]
### Description of the problem / feature request:

I was trying to build a docker image with bazel using `rules_docker`. See https://github.com/bazelbuild/rules_docker/issues/285. Turns out the thing that makes it very inconvenient and the resulting image very unfitting for ci jobs is that bazel has to be extracted on first run in the container.

### Feature requests: what underlying problem are you trying to solve with this feature?

I want to be able to build a docker image that includes a bazel that is ready to be used.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a `http_file` dependency on https://github.com/bazelbuild/bazel/releases/download/0.9.0/bazel_0.9.0-linux-x86_64.deb. Create a package bundle in your `WORKSPACE` file that specifies `openjdk-8-jdk-headless` in the same way as specified here: https://github.com/GoogleCloudPlatform/distroless/blob/master/WORKSPACE#L49

Then create a `container_image` rule as specified in the link to the rule_docker issue above. Also happy to provide an exampel repo if necessary.

**Comment by philwo** [comment]
Hi @Globegitter,

I totally agree with you that the startup delay is annoying!

Here's a suggestion how you can make this work:

```python
# Generate a bazel.tar that contains the extracted install base for Bazel.
genrule(
    name = "bazel_tar",
    # This is the bazel binary you'd like to use inside your Docker container.
    srcs = ["bazel"],
    outs = ["bazel.tar"],
    cmd = "mkdir -p opt && $(location :bazel) --batch --install_base=opt/bazel --output_base=outputbase version && tar cvf \"$@\" opt/bazel"
)

container_image(
    name = "bazel_image",
    base = "@java_debug_image_base//image",
    workdir = "/home",
    symlinks = {
        "/usr/bin/javac": "/usr/lib/jvm/java-8-openjdk-amd64/bin/javac",
        "/usr/bin/jar": "/usr/lib/jvm/java-8-openjdk-amd64/bin/jar",
    },
    debs = [
        "@bazel_deb//file",
        packages["openjdk-8-jdk-headless"],
    ],
    tars = [
        ":bazel_tar"
    ],
)
```

Inside your Docker container, you'd have to call Bazel like this:

```bash
bazel --install_base=/opt/bazel build ...
```

Would that work for you?

**Comment by Globegitter** [comment]
@philwo That almost works, just that now bazel is complaining `Error: corrupt installation: file '/opt/bazel/_embedded_binaries/A-server.jar' modified.  Please remove '/opt/bazel' and try again. And checking, the timestamps are `Jan  1  1970`. Seems to be related to https://github.com/bazelbuild/rules_docker/issues/52

**Comment by meisterT** [comment]
cc @meteorcloudy

**Comment by aiuto** [comment]
Having this available could speed up a lot of the integration tests where we need to run bazel as part of the test. Instead of spending time unpacking, we could directly run the C++ main and the server.

**Comment by meteorcloudy** [comment]
https://github.com/bazelbuild/bazel/pull/11905 could probably help this, but I still need find some time to resolve the concerns on rc file parsing
