### ISSUE TITLE
Recommended protobuf integration triggers bazel warning: external/com_google_protobuf_java/WORKSPACE (@com_google_protobuf) does not match

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#4495]
//CC @ejona86 @cgrushko as author of [Protobuf integration recommendation](https://blog.bazel.build/2017/02/27/protocol-buffers.html) and maintainer of https://github.com/cgrushko/proto_library.

In https://github.com/bazelbuild/rules_closure/pull/231, https://github.com/bazelbuild/rules_closure/pull/232 `rules_closure` [recently](https://github.com/bazelbuild/rules_closure/commit/d3e0437b6964db0719d71f075833614df3348fa7) moved from depending on protobuf release binaries to depending on the protobuf directly.

Gerrit Code Review updated [recently](https://github.com/GerritCodeReview/gerrit/commit/2b61903d85d182cd941a1db4bf4d890b4c48afe8) to `rules_closure`@HEAD and now Gerrit build started to issue this [warning](https://bugs.chromium.org/p/gerrit/issues/detail?id=8182):

```
WARNING: /private/var/tmp/_bazel_xxx/4e4bb427cd475349ab3944ff29048468/external/com_google_protobuf_java/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_xxx/4e4bb427cd475349ab3944ff29048468/external/com_google_protobuf_java/WORKSPACE (@com_google_protobuf)
does not match the name given in the repository's definition (@com_google_protobuf_java);
this will cause a build error in future versions
```

To reproduce, [clone](https://gerrit.googlesource.com/gerrit) gerrit code review and issue `bazel build gerrit`.

I reported [this issue](https://github.com/bazelbuild/rules_closure/issues/248) in `rules_closure` repository, but I was recommended to ask for feedback here.

The alternative way to repro is to clone [`rules_closure`](https://github.com/bazelbuild/rules_closure) and run the tests there:

```
davido@wizball:~/projects/rules_closure (master=)$ bazel test javatests/...
WARNING: /home/davido/.cache/bazel/_bazel_davido/2a0702ea37a9bc7e0f689212ecb3673c/external/com_google_protobuf_java/WORKSPACE:1: Workspace name in /home/davido/.cache/bazel/_bazel_davido/2a0702ea37a9bc7e0f689212ecb3673c/external/com_google_protobuf_java/WORKSPACE (@com_google_protobuf) does not match the name given in the repository's definition (@com_google_protobuf_java); this will cause a build error in future versions
```

The [Protobuf integration recommendation](https://blog.bazel.build/2017/02/27/protocol-buffers.html) is telling us to fetch the same repository multiple times under different names:

```
# proto_library rules implicitly depend on @com_google_protobuf//:protoc,
# which is the proto-compiler.
# This statement defines the @com_google_protobuf repo.
http_archive(
    name = "com_google_protobuf",
    urls = ["https://github.com/google/protobuf/archive/b4b0e304be5a68de3d0ee1af9b286f958750f5e4.zip"],
)

# cc_proto_library rules implicitly depend on @com_google_protobuf_cc//:cc_toolchain,
# which is the C++ proto runtime (base classes and common utilities).
http_archive(
    name = "com_google_protobuf_cc",
    urls = ["https://github.com/google/protobuf/archive/b4b0e304be5a68de3d0ee1af9b286f958750f5e4.zip"],
)

# java_proto_library rules implicitly depend on @com_google_protobuf_java//:java_toolchain,
# which is the Java proto runtime (base classes and common utilities).
http_archive(
    name = "com_google_protobuf_java",
    urls = ["https://github.com/google/protobuf/archive/b4b0e304be5a68de3d0ee1af9b286f958750f5e4.zip"],
)
```

What is the recommended way to avoid the warning? Or should Bazel accept such mismatch:
 `external/com_google_protobuf_java/WORKSPACE (@com_google_protobuf) does not match` without warning, not to mention "cause a build error in future versions"?

**Comment by cgrushko** [comment]
Seems like a bug in the gh.com/google/protobuf repo? If so, please reassign
/ move there.

**Comment by davido** [comment]
> Seems like a bug in the gh.com/google/protobuf repo?

That's indeed the question here, whether or not is this a bug or a feature? In case it's as feature, then Bazel should accepts the mismatch and remove the warning. Can you (or someone else) shed some light on what is the right next step here?

**Comment by drigz** [comment]
The warning will be resolved in grpc-java v1.10.0, which will include https://github.com/grpc/grpc-java/pull/3881. The warning is caused by grpc-java, not the recommendations (although these are indeed out-of-date - maybe worth another issue?)

**Comment by ejona86** [comment]
The warning will be common for any project using the previous set up with `@com_google_protobuf_java` and similar. They should migrate to using `@com_google_protobuf`. This will be handled by each project individually. File a bug against the repo if it hasn't yet updated. In this case, bazelbuild/rules_closure.

@drigz, the warning will not be resolved by the grpc update, since @davido is having trouble with rules_closure because [it still uses the old style](https://github.com/bazelbuild/rules_closure/blob/master/closure/repositories.bzl#L632).

**Comment by ejona86** [comment]
https://github.com/cgrushko/proto_library/pull/5 can be referenced to show projects how to update.

**Comment by drigz** [comment]
Ah, thanks for the correction, @ejona86.

**Comment by davido** [comment]
On the second thought, I will let the fix for consumption of `com_google_protobuf_js` to `rules_closure` maintainers. I fixed the warning in gerrit build with this PR: [1] and here I forked `rules_clsoure` in gerrit: [2] to use this custom release: [3] until my PR is merged. Thanks again for the help.

[1] https://github.com/bazelbuild/rules_closure/pull/249
[2] https://gerrit-review.googlesource.com/#/c/gerrit/+/153870
[3] https://github.com/davido/rules_closure/releases/tag/0.8.0

**Comment by davido** [comment]
FWIW: both CIs are now red with my CLs:

- `rules_closure`: https://travis-ci.org/bazelbuild/rules_closure/jobs/332180567
* gerrit: https://gerrit-ci.gerritforge.com/job/Gerrit-verifier-bazel/40429/consoleText

with the same message:

```
ERROR: /home/travis/build/bazelbuild/rules_closure/java/io/bazel/rules/closure/BUILD:60:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf_java//:java_toolchain', but this target could not be found because of: no such package '@com_google_protobuf_java//': The repository could not be resolved.
ERROR: Analysis of target '//javatests/com/google/javascript/jscomp:JsCompilerTest' failed; build aborted.
INFO: Elapsed time: 8.570s
ERROR: Couldn't start the build. Unable to run tests.
```

That's because on both environments Bazel is tool old:

- rules_closure: 0.5.3: https://github.com/bazelbuild/rules_closure/blob/master/.travis.yml#L14
- gerrit 0.7.0

I guess Bazel must be at least 0.8.0 to support that, yet, rules_closure removed recently Bazel version check, ...
