### ISSUE TITLE
Generate a download list and design tooling to add mirror entries

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/bazel#4499]
Having failing build because of a network issues is annoying and harms bazels reputation as a reliable build system.
Rules will use `ctx.download(url, ...)`. Could bazel track the urls that rules tried to download from and output them together with the rule that triggered the download.

What about some tooling that helps to add mirror urls to improve reliability or generate a list of unmirrored urls + licenses to setup mirroring?

**Comment by guw** [comment]
Alternatively, I'd like to have a capability which allows to rewrite outgoing URLs.

For example:
* `http[s]://*.maven.org/maven2/` --> `https://my.internal.mirror/some/path

**Comment by ozio85** [comment]
I'm looking for this option as well.

I am currently surviving with [--distdir](https://docs.bazel.build/versions/master/command-line-reference.html#flag--distdir).. but the bazel internal dependencies are getting a headache to update when bazel versions change.

**Comment by yoonjesung** [comment]
Is there any workaround to this at the moment? This makes maintaining internal bazel dependencies difficult as each dep has to either be maintained locally or the WORKSPACE has to be littered with http_archive rules that point to the internal mirror.
