### ISSUE TITLE
Toolchain wrapper scripts don't have execution permission

### ISSUE THREAD

**Issue by chenkan0104** [bazelbuild/bazel#4500]
### Description of the problem / feature request:

I am using an external repository as toolchain to cross compile my project, and a docker image based on Ubuntu 16.04 to run the builds, but seems my wrapper script of gcc don't have execution permission.

I'm pretty sure that I've ```chmod +x``` on those files before commit and push them.
And seems that I can't make them executable before build as the external project hasn't been downloaded before any build.
Think that bazel should make them executable automatically?

```
ERROR: /root/.cache/bazel/_bazel_root/4734a5a1c2901fe989e5b6a11965b4d1/external/boringssl/BUILD:132:1: C++ compilation of rule '@boringssl//:crypto' failed (Exit 1)
src/main/tools/process-wrapper-legacy.cc:58: "execvp(external/toolchains/tools/arm_compiler/gcc-4.8.5-aarch64/aarch64-unknown-linux-gnu-gcc, ...)": Permission denied
```

### Feature requests: what underlying problem are you trying to solve with this feature?

Make wrapper of gcc etc. executable automatically when using external project as toolchain.

### What operating system are you running Bazel on?

Ubuntu 16.04, docker image: chenkan1994/bazel-build

### What's the output of `bazel info release`?
This is ```bazel version```

```
Build label: 0.9.0
Build target: bazel-out/k8-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Dec 19 09:31:58 2017 (1513675918)
Build timestamp: 1513675918
Build timestamp as int: 1513675918
```

###  Have you found anything relevant by searching the web?
Seems No.

**Comment by iirina** [comment]
Could you point us to the repositories/BUILD files that you described? A link or a BUILD snippet would be nice.

> I'm pretty sure that I've chmod +x on those files before commit and push them.
> And seems that I can't make them executable before build as the external project hasn't been downloaded before any build.

I think I'm missing something here. What files are you chmod-ing? In your own repo? As I understand, the files in case are from an external project that you cannot control, so how can you chmod +x them? Thanks!

**Comment by chenkan1994** [comment]
@iirina I'm sorry that the repository is a private project that I can't share with you.

But the toolchain was specifically made based on ```@bazel//:src/test/shell/bazel/testdata/bazel_toolchain_test_data```, and the script for testing this project uses the same trick as mine: https://github.com/bazelbuild/bazel/blob/master/src/test/shell/bazel/bazel_toolchain_test.sh#L50:56

So basically:
1. I have a project like ```bazel_toolchain_test_data```, and I've ```chmod +x``` on those wrapper scripts before commit and push them.
2. I put this project into my target project's WORKSPACE like this:
```
# set up toolchain
git_repository(
  name = "toolchains",
  remote = "http://git.***.com/***/toolchains.git",
  commit = "***",
)
load("@toolchains//:toolchain_deps.bzl", "toolchain_deps")
toolchain_deps()
```
3. I compile my target project using this command:
```
bazel build --crosstool_top=//external:toolchain --cpu=aarch64 --host_cpu=k8 -c opt //:main
```
4. And I got this error: 
```
ERROR: /root/.cache/bazel/_bazel_root/4734a5a1c2901fe989e5b6a11965b4d1/external/boringssl/BUILD:132:1: C++ compilation of rule '@boringssl//:crypto' failed (Exit 1)
src/main/tools/process-wrapper-legacy.cc:58: "execvp(external/toolchains/tools/arm_compiler/gcc-4.8.5-aarch64/aarch64-unknown-linux-gnu-gcc, ...)": Permission denied
```
5. So I presume that I should do the same trick as in: https://github.com/bazelbuild/bazel/blob/master/src/test/shell/bazel/bazel_toolchain_test.sh#L50:56
6. But actually I can't as I would have to
```chmod +x bazel-project/external/toolchains/***/tools/arm-compiler/gcc-4.8.5-aarch64/aarch64-unknown-linux-gnu-*```
but those external files won't be exsiting before any real build command like
```bazel build --crosstool_top=//external:toolchain --cpu=aarch64 --host_cpu=k8 -c opt //:main```.

Hope you understand me...

Thanks a lot.

**Comment by chenkan1994** [comment]
Hello @iirina , any update?

**Comment by dslomov** [comment]
The Starlark git_repository rules preserve file premissions
