### ISSUE TITLE
windows,testing: bazel_bootstrap_distfile_test is slow

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4503]
### Description of the problem / feature request:

`//src/test/shell/bazel:bazel_bootstrap_distfile_test` is very slow on Windows.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I added logging between most operations in the test, after it took 48 minutes to run.

With the logging, it took 53 min, but I kept using the machine the whole time so some variance is to be expected. Still, these numbers are noteworthy:

- startup until running the test method: 54s
- [`unzip`](https://github.com/bazelbuild/bazel/blob/28c20f79e3d265f897e8c644a4c31bd2b3d6ac67/src/test/shell/bazel/bazel_bootstrap_distfile_test.sh#L40): 1m 51s
- [`find` and `chmod`](https://github.com/bazelbuild/bazel/blob/28c20f79e3d265f897e8c644a4c31bd2b3d6ac67/src/test/shell/bazel/bazel_bootstrap_distfile_test.sh#L41): 20m 31s
- [bootstrap & bazel version & bazel shutdown](https://github.com/bazelbuild/bazel/blob/28c20f79e3d265f897e8c644a4c31bd2b3d6ac67/src/test/shell/bazel/bazel_bootstrap_distfile_test.sh#L42-L45): 29m 25s
- [`rm -rf` in `trap`](https://github.com/bazelbuild/bazel/blob/28c20f79e3d265f897e8c644a4c31bd2b3d6ac67/src/test/shell/bazel/bazel_bootstrap_distfile_test.sh#L37): ? (I messed up the logging here)

Log:
```
INFO: Found 1 test target...
DEBUG[Mon Jan 22 18:02:46 WEST 2018]  10 Test start
(...)
DEBUG[Mon Jan 22 18:03:39 WEST 2018]  20 setup complete
DEBUG[Mon Jan 22 18:03:39 WEST 2018]  30 run suite
(...)

** test_bootstrap **************************************************************
DEBUG[Mon Jan 22 18:03:40 WEST 2018]  40 start test
DEBUG[Mon Jan 22 18:03:40 WEST 2018]  50 start unzip
DEBUG[Mon Jan 22 18:05:31 WEST 2018]  60 start find
DEBUG[Mon Jan 22 18:26:02 WEST 2018]  70 start compile.sh
(...)
DEBUG[Mon Jan 22 18:55:27 WEST 2018]  80 done test
(...)
DEBUG[Mon Jan 22 18:03:40 WEST 2018] 90 done rm
PASSED: test_bootstrap
```

### What operating system are you running Bazel on?

Windows 10.

### What's the output of `bazel info release`?

0.10.0 rc4

**Comment by meteorcloudy** [comment]
Latest status of this test
```
//src/test/shell/bazel:bazel_bootstrap_distfile_test                     PASSED in 912.1s
```
It should be fine now.
