### ISSUE TITLE
Allow providing an external test.xml producer

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/bazel#4507]
One of the tasks of our internal migration from maven to bazel is to compare the existing test results produced by maven (via surefire/failsafe plugins) to the test.xml files produced by bazel. It turned out to be a not-so-easy task, as bazel writes the test.xml differently from maven.

In addition, we're using specs2 junit tests in scala, which further complicates things (issues like bazelbuild/rules_scala#339, bazelbuild/rules_scala#231, bazelbuild/rules_scala#391)

Since currently the Scala test runner delegates to the Java one, instead of trying to fix the xml reporter, perhaps it would be better to have a custom reporter provided externally? This way I could delegate the job of creating the test xml to the actual test runner, which could help solve some of these issues?
(in particular, Specs2 has the ability to create own junit xml report, which has a higher-accuracy test times)

WDYT?

**Comment by hmemcpy** [comment]
@ulfjack sorry, I missed your comment.
Not sure what you meant: the current test.xml is generated by bazel's JUnit test runner, and it works by listening to test events (started, finished, failed, etc). It also calculates execution times manually (which is sometimes off by an order of magnitude from the actual run times).

My suggestion was to expose API/hooks in the test runner to allow supplying a test.xml (or similar) produced by the actual test library (for example, Scala's specs2 is capable of producing its own junit-compatible test.xml, which has much more detailed results)

Or perhaps you meant something else?

**Comment by ChrisCummins** [comment]
Any update on this? [pytest](http://doc.pytest.org/en/latest/usage.html#creating-junitxml-format-files) can also generate detailed xml reports, it would be nice to get bazel to read them.

**Comment by ulfjack** [comment]
If you write it to the location indicated by the TEST_XML variable, Bazel should pick up the report automatically. Java is a bit special, because we use a test runner that ships with Bazel.

**Comment by ulfjack** [comment]
Note that Bazel will only read the file if it uses the maven XML format.

**Comment by ChrisCummins** [comment]
> If you write it to the location indicated by the TEST_XML variable, Bazel should pick up the report automatically. Java is a bit special, because we use a test runner that ships with Bazel.

I can't find any reference to this elsewhere, and on bazel 2.0.0 this variable doesn't appear to be set. Could you provide an example?

**Comment by ulfjack** [comment]
Sorry, I meant the XML_OUTPUT_FILE variable. You can see all variables if you run bazel test -s //my/test, which looks like this:
```
SUBCOMMAND: # //cpp:cpp [action 'Testing //cpp:cpp', configuration: 419a3f9c03a725a237290b10359c9923007948fc3772740ed08cd228e37927c7]
(cd /usr/local/google/home/ulfjack/.cache/bazel/_bazel_ulfjack/e63b5512da07d9a249b9546238576adf/execroot/mybazel && \
  exec env - \
    EXPERIMENTAL_SPLIT_XML_GENERATION=1 \
    JAVA_RUNFILES=bazel-out/k8-fastbuild/bin/cpp/cpp.runfiles \
    PATH=/usr/local/google/home/ulfjack/Software/:/usr/local/jprofiler5/bin/:/usr/lib/google-golang/bin:/usr/local/buildtools/java/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PYTHON_RUNFILES=bazel-out/k8-fastbuild/bin/cpp/cpp.runfiles \
    RUNFILES_DIR=bazel-out/k8-fastbuild/bin/cpp/cpp.runfiles \
    RUN_UNDER_RUNFILES=1 \
    TEST_BINARY=cpp/cpp \
    TEST_INFRASTRUCTURE_FAILURE_FILE=bazel-out/k8-fastbuild/testlogs/cpp/cpp/test.infrastructure_failure \
    TEST_LOGSPLITTER_OUTPUT_FILE=bazel-out/k8-fastbuild/testlogs/cpp/cpp/test.raw_splitlogs/test.splitlogs \
    TEST_PREMATURE_EXIT_FILE=bazel-out/k8-fastbuild/testlogs/cpp/cpp/test.exited_prematurely \
    TEST_SIZE=medium \
    TEST_SRCDIR=bazel-out/k8-fastbuild/bin/cpp/cpp.runfiles \
    TEST_TARGET=//cpp:cpp \
    TEST_TIMEOUT=300 \
    TEST_TMPDIR=_tmp/31ea6f4e967aebf5ef87cd77931f1803 \
    TEST_UNDECLARED_OUTPUTS_ANNOTATIONS=bazel-out/k8-fastbuild/testlogs/cpp/cpp/test.outputs_manifest/ANNOTATIONS \
    TEST_UNDECLARED_OUTPUTS_ANNOTATIONS_DIR=bazel-out/k8-fastbuild/testlogs/cpp/cpp/test.outputs_manifest \
    TEST_UNDECLARED_OUTPUTS_DIR=bazel-out/k8-fastbuild/testlogs/cpp/cpp/test.outputs \
    TEST_UNDECLARED_OUTPUTS_MANIFEST=bazel-out/k8-fastbuild/testlogs/cpp/cpp/test.outputs_manifest/MANIFEST \
    TEST_UNDECLARED_OUTPUTS_ZIP=bazel-out/k8-fastbuild/testlogs/cpp/cpp/test.outputs/outputs.zip \
    TEST_UNUSED_RUNFILES_LOG_FILE=bazel-out/k8-fastbuild/testlogs/cpp/cpp/test.unused_runfiles_log \
    TEST_WARNINGS_OUTPUT_FILE=bazel-out/k8-fastbuild/testlogs/cpp/cpp/test.warnings \
    TEST_WORKSPACE=mybazel \
    TZ=UTC \
    XML_OUTPUT_FILE=bazel-out/k8-fastbuild/testlogs/cpp/cpp/test.xml \
  external/bazel_tools/tools/test/test-setup.sh cpp/cpp)
```

**Comment by ChrisCummins** [comment]
Thanks @ulfjack! I had missed that it is referenced in the [test encyclopedia](https://docs.bazel.build/versions/master/test-encyclopedia.html#initial-conditions) but not fully explained.

For pytest uses, you can just add `--junitxml=$XML_OUTPUT_FILE` arg to get nice XML reporting 👍 
See [here](https://github.com/ChrisCummins/phd/blob/02dffda32b7aa7414d3910ebe554f11f74b7948d/labm8/py/test.py#L231-L256) for a full example, as there's a couple of other options you may want to set such as `junit_suite_name = $TEST_TARGET`.
