### ISSUE TITLE
Create a native distribution for OSX

### ISSUE THREAD

**Issue by arun-gupta** [bazelbuild/bazel#451]
Downloads at https://github.com/bazelbuild/bazel/releases/tag/0.1.0 has `.sh` for Bazel. `.dmg` installer is the expected format for Mac and should be provided.

**Comment by damienmg** [comment]
We are going to ship brew recipe so dmg is not a priority

**Comment by air720boarder** [comment]
Updating this as brew recipe is out of date***

**Comment by damienmg** [comment]
Homebrew had an issue with 0.2.2 but 0.2.3 fixes the issue.

**Comment by davidstanke** [comment]
Closing this because brew has kept up-to-date with past several releases.

**Comment by ittaiz** [comment]
Dave,
I saw Helen say in a recent issue that Brew is no longer the recommended
way for Mac OS so I think either issue should stick
