### ISSUE TITLE
Feature request: expose bazel shell integration testing targets

### ISSUE THREAD

**Issue by brendandouglas** [bazelbuild/bazel#4515]
The IntelliJ plugin has java integration tests which actually run blaze (using testenv.sh, etc.).

We'd like to include these in our Bazel plugin repo as well, but realistically that's going to require using //src/test/shell/bazel:test_deps, which has restricted visibility.

Are there any plans to open up visibility of the shell integration testing targets, so other repos can include bazel-invoking integration tests?

**Comment by ittaiz** [comment]
Brendan,
Are you familiar with Bazel integration testing repo? It's very immature
but with demand I promise to allocate more time.
Last I asked @ulfjack to expose the shell the answer was that it's not an
API they want to support

**Comment by brendandouglas** [comment]
I wasn't aware of that, thanks.

For now, I'd like to keep the integration testing code consistent internally and externally (which currently means no external integration tests running Bazel).

I'm not exactly fond of Bazel's integration testing code though, so at some point it may be worth upstreaming a different version which is exposed externally, and using that instead.

**Comment by jin** [comment]
I've added bazel-invoking integration tests to the intellij repo using https://github.com/bazelbuild/bazel-integration-testing here: https://github.com/bazelbuild/intellij/blob/master/aspect/testing/tests/src/com/google/idea/blaze/aspect/integration/BazelInvokingIntegrationTest.java
