### ISSUE TITLE
actool is too verbose

### ISSUE THREAD

**Issue by Arcank** [bazelbuild/bazel#4518]
### Description of the problem / feature request:

actool output is too verbose:

/* com.apple.actool.compilation-results */
/var/tmp/Foo.resources/actool-output/AppIcon20x20@2x.png
/var/tmp/Foo.resources/actool-output/AppIcon20x20@3x.png
/var/tmp/Foo.resources/actool-output/AppIcon29x29@2x.png
/var/tmp/Foo.resources/actool-output/AppIcon29x29@3x.png
/var/tmp/Foo.resources/actool-output/AppIcon40x40@2x.png
/var/tmp/Foo.resources/actool-output/AppIcon40x40@3x.png
/var/tmp/Foo.resources/actool-output/AppIcon60x60@2x.png
/var/tmp/Foo.resources/actool-output/AppIcon60x60@3x.png
/var/tmp/Foo.resources/actool-output/Assets.car
/var/tmp/Foo.resources/actool-PartialInfo.plist

### Feature requests: what underlying problem are you trying to solve with this feature?

It would be nice to ignore actool's output when there is no warning or error. This is how Chromium does it for example:
https://chromium.googlesource.com/chromium/src/+/5b150b0a5a28f95f651767f901819390fc065676/build/toolchain/mac/compile_xcassets.py

Tracking issue: https://bugs.chromium.org/p/chromium/issues/detail?id=635306

### What operating system are you running Bazel on?

Mac, to build iOS apps.

**Comment by susinmotion** [comment]
I'm going to close this since it's been gathering dust for a couple of years. @Arcank, please feel free to reopen if it's still relevant.
