### ISSUE TITLE
--workspace_status_command is executed only when in tools/bazel.rc

### ISSUE THREAD

**Issue by astratto** [bazelbuild/bazel#4523]
### Description of the problem / feature request:

I'm not quite sure what I'm doing wrong, but it looks like `--workspace_status_command` is ignored from command line, but works only in `tools/bazel.rc`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have a simple script in `tools/expose_stamping_attributes.sh` that exposes some attributes that I need for stamping binaries.

```
#!/bin/bash
echo "STABLE_MY_ATTRIBUTE 100"
```

If I run `bazel --workspace_status_command=./tools/expose_stamping_attributes.sh`, the script is ignored:

```$ cat bazel-out/stable-status.txt
BUILD_EMBED_LABEL
BUILD_HOST xxx
BUILD_USER yyy
```

If I put that in `tools/bazel.rc` it works just fine:

```
$ cat bazel-out/stable-status.txt
BUILD_EMBED_LABEL
BUILD_HOST xxx
BUILD_USER yyy
STABLE_MY_ATTRIBUTE 111
```

### What operating system are you running Bazel on?

Ubuntu running on Vagrant.

### What's the output of `bazel info release`?

release 0.9.0

###  Have you found anything relevant by searching the web?

According to the documentation and other answers on StackOverflow, this should work fine.

i.e., https://stackoverflow.com/questions/47622645/how-to-run-a-shell-command-at-analysis-time-in-bazel?rq=1

**Comment by meteorcloudy** [comment]
Hmm, it worked for me. Can you provide more details on how to reproduce this?

**Comment by astratto** [comment]
This is weird... I've just tried with a pet project and it worked.

```
> bazel build --workspace_status_command=./tools/expose_stamping_attributes.sh ...
INFO: Analysed 2 targets (0 packages loaded).
INFO: Found 2 targets...
INFO: Elapsed time: 0.955s, Critical Path: 0.02s
INFO: Build completed successfully, 1 total action

> cat bazel-out/stable-status.txt
BUILD_EMBED_LABEL
BUILD_HOST StefanosMacBook
BUILD_USER stefanotortarolo
STABLE_MY_ATTRIBUTE 100
```

I'll try again tomorrow in the other project.
Is there a way to troubleshoot why it doesn't touch that file in the other one?

I guess I could try with `--explain ./bazel.log --verbose_explanations`?
