### ISSUE TITLE
libc++ support for Clang + Linux

### ISSUE THREAD

**Issue by htuch** [bazelbuild/bazel#4524]
In the Envoy project, we would like to use a combination of our Bazel build and oss-fuzz (https://github.com/google/oss-fuzz), tracked at https://github.com/envoyproxy/envoy/issues/508.

oss-fuzz requires that we are able to build with a Clang toolchain in a Linux Docker container, and link against libc++ rather than libstdc++, see https://github.com/google/oss-fuzz/issues/1114.

I don't see direct support for this in `cc_configure.bzl` toolchain autoconfigure today, there's direct references to `libstdc++` in https://github.com/bazelbuild/bazel/blob/12471a77bdd4439f17cc1a665454601c867e1286/tools/cpp/unix_cc_configure.bzl#L49 for example. Ideally we would have some flag or detection of `-stdlib=libc++` as a `--linkopt` that would correctly configure for linking against `libc++`. 

We'd find it helpful to hear from Bazel team on the ideal way of structuring this and hopefully suggestions for how we can work around this in the interim to avoid blocking our full oss-fuzz integration. I'm guessing we could do a manually crafted CROSSTOOL file (possibly generated on-the-fly prior to Bazel invocation), or continue with Envoy's fork of `cc_configure.bzl` and build in the support there. The situation is complicated by the fact that oss-fuzz may invoke our build with arbitrary CFLAGS/CXXFLAGS/CC that we need to map into the Bazel world. Thanks!

@jmillikin-stripe @mattklein123 @kcc

**Comment by meteorcloudy** [comment]
Using a custom CROSSTOOL sounds like the right way to me, but //cc @mhlopko for more insight.

**Comment by htuch** [comment]
@jmillikin-stripe if we have https://github.com/bazelbuild/bazel/pull/4031 in the next release, it seems this won't allow us to drop the cc_configure.bzl fork still, since we need to be able to override this for OSS-Fuzz as described above. Thoughts?

**Comment by jmillikin-stripe** [comment]
If we can use the C++ toolchain support to define a custom `envoy_cc_binary` rule, then we can use it to do all the flag editing we want without having to worry about the crosstool. It should also be easier to keep up-to-date as the Bazel API changes, since we'll be poking at far fewer internal surfaces.

**Comment by mhlopko** [comment]
@htuch @jmillikin-stripe pls verify that 19c6428 is good enough, and let me know if not and I'll reopen. Thanks!

**Comment by jmillikin-stripe** [comment]
@mhlopko The functionality looks good to me. Can you document somewhere what `BAZEL_LINKOPTS` is, its expected format, and how it's different from the `--linkopt` flag?

**Comment by mhlopko** [comment]
Let me come back to that next Monday, I'm planning a present for the world later this week.

**Comment by mhlopko** [comment]
Still working on (fully documented :) present.

**Comment by mihaimaruseac** [comment]
Hi. Any update on the document? I'm thinking we'll need this for OSSFuzz-tensorflow integration

**Comment by htuch** [comment]
@mihaimaruseac you can see what we did for Envoy + Bazel + oss-fuzz at https://github.com/google/oss-fuzz/blob/master/projects/envoy/build.sh.

**Comment by mihaimaruseac** [comment]
I'm following that, but I thought it might be easier/more readable with `BAZEL_LINKOPT` (which is not present there).

I got it to work just now, so it should be ok, thanks
