### ISSUE TITLE
Add Envoy to Bazel CI

### ISSUE THREAD

**Issue by htuch** [bazelbuild/bazel#4525]
Envoy (https://github.com/envoyproxy/envoy) is a significant Google contributed project that makes use exclusively of Bazel. We break frequently as Bazel releases roll out. I learnt from recent issues (https://github.com/bazelbuild/bazel/issues/4474) that TensorFlow is built under Bazel CI.

Would it be feasible to add Envoy to Bazel CI to avoid breakages when qualifying the next point release?

@jmillikin-stripe @alyssawilk @mattklein123 @jmarantz

**Comment by davido** [comment]
Wrong issue tracker? Bazel CI requests are handled [here](https://github.com/bazelbuild/continuous-integration).

**Comment by iirina** [comment]
CC: @philwo

**Comment by htuch** [comment]
Great, didn't realize this was self-service. Will track this in the Envoy issues at https://github.com/envoyproxy/envoy/issues/2461, closing this one out.
