### ISSUE TITLE
Special variable for `tools`

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#4527]
### Description of feature request:

https://docs.bazel.build/versions/master/be/make-variables.html#predefined_variables
We have '<' and '@' special variables for input and output. Can you introduce similar functionality for tools (if it is a list of one tool)?

### Feature requests: what underlying problem are you trying to solve with this feature?

That will simplify writing and readability of custom rules.

**Comment by excitoon** [comment]
@meteorcloudy Is it worth merging? If so I'll be glad to make a PR for this. I would suggest `@0` for a tool (as a reference to bash `!:0`).

**Comment by meteorcloudy** [comment]
@lberki Do you know we could support such syntax in genrule?

**Comment by lberki** [comment]
Meh. I'd much rather not introduce one more special case. `$<` and `$@` are really there for Make compatibility (the great grandfather of Bazel was a script that emitted Makefiles), and I'd much rather not have those, either. 

Is `$(location <label>)` that onerous to write?

**Comment by excitoon** [comment]
Okay, feel free to close this then. I just wanted to reduce duplicity when specifying the tool twice, in `tools` and in the command.
