### ISSUE TITLE
Bazel 0.10.0rc6: bazel-tests fail on Ubuntu

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#4529]
Error snippet:
```
mktemp: failed to create file via template '/home/ci/.cache/bazel/_bazel_ci/a662063314b9ed68d0536f44c93482c1/bazel-sandbox/5691265306661215494/execroot/io_bazel/_tmp/6fdf25c615e59962ba0e653de8344b89/tests_root/tmp8gPt3f/sandboxed-temp-1/tmp.XXXXXXXX': Read-only file system
```

Console log is [here](https://ci.bazel.build/view/Global%20Dashboard/job/Global/job/bazel-tests/464/consoleFull).

@philwo bisected and found the culprit to be bfc738dbbd03600bec78d7cc6e1de668372fd947 (the last cherry pick).

I added the last two cherry picks (bfc738dbbd03600bec78d7cc6e1de668372fd947 and 9d0d8119d4b4a18cd399fc5fd5a276830a9a6461) in order to fix #4303, which was a regression issue from 0.7.0.

@laszlocsomor you are the author of those commits. Can you please asses what should we do in this case? If there is no easy fix that could be cherry picked early next week, I think we should revert the last 2 cherry picks and aim for a patch release to fix #4303.

**Comment by iirina** [comment]
@philwo identified a missing cherry pick that was related to those 2 I mentioned before: 6cc2ad8676d1ae0542b351a07a05ddbe5efac165. Seems like the tests are passing with the new cherry pick. I'll create a new RC and leave this open until I can confirm it's fixed in the CI.

**Comment by meteorcloudy** [comment]
This is fixed in rc7
