### ISSUE TITLE
BazelJavaSemantics.getExtraArguments is wrong

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#453]
It checks:
ruleContext.getConfiguration().getTestArguments().isEmpty()

Which means that java_test rules basically never work if someone passes --test_args on the command line. And why don't we have a test_class attribute?

**Comment by ulfjack** [comment]
We have a test_class attribute now. Is there anything left to do here?

**Comment by damienmg** [comment]
I still need to remove the legacy java test flag but this issue is indeed fixed
