### ISSUE TITLE
Unable to build using 'bazel build //src:bazel' - errors about osx tools version

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/bazel#4534]
When I try building bazel locally, I get the following error:
```
$ bazel build //src:bazel
ERROR: ~/git/bazel/tools/osx/xcode_version_flag.bzl:90:45: name 'configuration_field' is not defined
ERROR: ~/git/bazel/src/BUILD:249:2: error loading package 'tools/osx': Extension 'tools/osx/xcode_version_flag.bzl' has errors and referenced by '//src:package-zip'
ERROR: Analysis of target '//src:bazel' failed; build aborted: error loading package 'tools/osx': Extension 'tools/osx/xcode_version_flag.bzl' has errors
```

It was building previously, so I used `git bisect` to track down when stopped working: the culprit commit is db319f8eca064475d5092a756c75f2c3f6526b7e made by @c-parsons.

Is there anything I can do to fix?

**Comment by meteorcloudy** [comment]
Hi @hmemcpy, which bazel version are you using? I believe `configuration_field` is only supported from 0.9.0.
@c-parsons Correct me if I'm wrong.

**Comment by hmemcpy** [comment]
Ooh, thanks for the heads up! I checked, I was indeed on 0.8.1, just upgraded to 0.9.0 via brew - I can build again! :)
Thanks a lot, closing!
