### ISSUE TITLE
kotlin rules and android.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/bazel#4535]
I'm working on new bazel rules for Kotlin and an extension to the intellij plugin. The android rules in 0.8.1 are not accepting jars built from the Kotlin rules. The `kotlin_library` rule return a `JavaInfo` provider, and I was expecting the android rules to just accept `JavaInfo`.

These rules might be upstreamed into the bazelbuild org soon (@davidstanke).  I don't do any android development myself so it would be good if someone can take charge of the android facet of the rules. 

There is more info here hsyed/rules_kotlin#8.

**Comment by aj-michael** [comment]
Hi @hsyed. Regarding "I was expecting the android rules to just accept JavaInfo" - unfortunately that is not the case. I believe it should be the case, but noone has done the work to make it so.

As a workaround, you can just wrap your jar in one of the rules that Android does accept. In particular, you could create a java_library with no sources that exports your kotlin_library. And then depend on that from the android_* rules.

If someone were to take charge of the android facet of the kotlin rules, I would be happy to advise. However, I don't think I currently have the bandwidth to do it myself.

**Comment by hsyed** [comment]
@aj-michael that pattern would work as a work around for now -- `pubref/rules_kotlin` uses this pattern in a macro layer. 

I don't think such a macro layer should be introduced in the new rules. If we added such macros they would need to be integration tested in the Kotlin rules repo and it will also make developing new features more complicated (--e.g., Kapt).  

Until `JavaInfo` is recognised by the Android rules some examples could be added to the Kotlin rules repo illustrating the workaround.
