### ISSUE TITLE
CI: bazel_bootstrap_distfile_test failing on Windows due to long object file path

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#4536]
https://ci.bazel.build/blue/organizations/jenkins/bazel-tests/detail/bazel-tests/1856/pipeline/31

```
C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe /c external/io_bazel/third_party/protobuf/3.4.0/src/google/protobuf/stubs/atomicops_internals_x86_gcc.cc /Fobazel-out/host/bin/external/io_bazel/third_party/protobuf/3.4.0/_objs/protobuf_lite/external/io_bazel/third_party/protobuf/3.4.0/src/google/protobuf/stubs/atomicops_internals_x86_gcc.o /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/io_bazel /Ibazel-out/host/genfiles/external/io_bazel /Iexternal/bazel_tools /Ibazel-out/host/genfiles/external/bazel_tools /Iexternal/io_bazel/third_party/protobuf/3.4.0/src /Ibazel-out/host/genfiles/external/io_bazel/third_party/protobuf/3.4.0/src /Iexternal/bazel_tools/tools/cpp/gcc3 /showIncludes /MD /O2 /DNDEBUG /DHAVE_PTHREAD /wd4018 /wd4514

C:\temp\eabe42fa62db9997c05f08353752736f\bazel_oZlJBkQv\out\execroot\io_bazel\external\io_bazel\third_party\protobuf\3.4.0\src\google\protobuf\stubs\atomicops_internals_x86_gcc.cc : fatal error C1083: Cannot open compiler generated file: '': Invalid argument
```

The absolute object file path is `C:/temp/eabe42fa62db9997c05f08353752736f/bazel_oZlJBkQv/out/execroot/io_bazel
/bazel-out/host/bin/external/io_bazel/third_party/protobuf/3.4.0/_objs/protobuf_lite/external/io_bazel/third_party/protobuf/3.4.0/src/google/protobuf/stubs/atomicops_internals_x86_gcc.o` (263) characters

**Comment by meteorcloudy** [comment]
A proper solution for this is under discussion, let's find a workaround first.

**Comment by meteorcloudy** [comment]
Culprit is https://github.com/bazelbuild/bazel/commit/a59e60e4fba191b8793254c38485f781f790a607

It makes the object file path longer by repeating "external/io_bazel/" twice.
//cc @dslomov @laszlocsomor

**Comment by meteorcloudy** [comment]
@laszlocsomor Can we use a shorter output base for the bootstrap test? `c:/temp/eabe42fa62db9997c05f08353752736f` seems a bit too long.

**Comment by laszlocsomor** [comment]
Yes, I was thinking the same.

**Comment by laszlocsomor** [comment]
Yun, do you have any update on this?

**Comment by meteorcloudy** [comment]
Not yet, how about we set `TMPDIR` to a shorter path in the shell test?

**Comment by laszlocsomor** [comment]
Do you want to do it or shall I?

**Comment by meteorcloudy** [comment]
It would be great if you can do it!

**Comment by laszlocsomor** [comment]
Sure!

**Comment by meteorcloudy** [comment]
Hmm,, it's still happening
https://ci.bazel.build/blue/organizations/jenkins/CR%2Fbazel-tests/detail/bazel-tests/814/pipeline/36

**Comment by meteorcloudy** [comment]
The output_base is created here when bootstrap:
https://github.com/bazelbuild/bazel/blob/ef381e54b124a7bb71dcb883fdc999f3bd37d4ed/scripts/bootstrap/buildenv.sh#L158-L169
Seems like TMPDIR is already set to `c:/temp/eabe42fa62db9997c05f08353752736f
`?
Is that possible?

**Comment by laszlocsomor** [comment]
Was this fixed?

**Comment by meteorcloudy** [comment]
It is fixed by your change, I believe it's this one https://github.com/bazelbuild/bazel/commit/46cd4fd2e120fe3c5f08f44422bc5d3ddaecde42
