### ISSUE TITLE
Predictable build sequence

### ISSUE THREAD

**Issue by cuadue** [bazelbuild/bazel#4538]
### Description of the problem / feature request:

Flag which permits a developer to build files in a predictable sequence. Specifically, if I change no files, and invoke the same build command twice, I would see the same file and its error messages.

### Feature requests: what underlying problem are you trying to solve with this feature?

Reduce mental context reorientation required to randomly switch between source files at the whim of my build system. More generally, I expect the build system to be subservient to the developer (I tell the computer what to do), rather than (respectfully) the other way around (the computer tells me what to do).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

    cc_binary(name='foo', srcs=['bar.cc', 'baz.cc'])
    $ echo syntax error one > bar.cc
    $ echo syntax error two > baz.cc
    $ bazel build :foo
    Maybe error messages for bar.cc
    $ bazel build :foo
    Maybe error messages for baz.cc, or maybe bar.cc

### What operating system are you running Bazel on?

Ubuntu 16.04.3 LTS

### What's the output of `bazel info release`?

release 0.7.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Confidential

###  Have you found anything relevant by searching the web?

Unfortunately no: terms such as "bazel build order" or "bazel build fix" or "bazel build sequence" are too generic.

**Comment by benjaminp** [comment]
I think `--jobs 1` will get you pretty close.

**Comment by mjansche** [comment]
``bazel build -k --jobs=1`` will build everything and tell you about all of the syntax errors. It doesn't strike me as reasonable to expect more. There is nothing in the build language that would indicate any kind of ordering of the smaller units of a ``cc_binary`` target. The only ordering you get is a topological ordering on the build graph, but whether ``bar.cc`` or ``baz.cc`` gets compiled first is not expressed anywhere, so no ordering is defined. If you're running a distributed build, it would be wasteful to try to schedule one of them first and wait for its compilation to complete before compiling the other file. This is not substantially different from ``make -j``.

**Comment by mhlopko** [comment]
Closing, we don't plan to introduce deterministic execution order.
