### ISSUE TITLE
./scripts/setup-intellij.sh downloads j2objc zip

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#454]
$ ./scripts/setup-intellij.sh 
INFO: Reading 'startup' options from /Users/ulfjack/.bazelrc: --watchfs
...........................
INFO: Downloading from https://github.com/google/j2objc/releases/download/0.9.8.1/j2objc-0.9.8.1.zip: 13MB

(Didn't get any further yet, but is this really necessary?)

**Comment by ulfjack** [comment]
My home internet connection is really bad, in case you're wondering.

**Comment by damienmg** [comment]
I looked at the source code and this is only necessary if you need to execute j2objc. The setup-intellij.sh shouldn't try to fetch things in //tools/... and in third_party/java{,src}/...

We also have the problem with the AppEngine SDK

**Comment by damienmg** [comment]
Closing this bug as we now have a native IDE support for IntelliJ. This script will go away.
