### ISSUE TITLE
 git push origin may push to unintended remote URL after unsuccessful bazel's git fetch - very critical security issue

### ISSUE THREAD

**Issue by excavador** [bazelbuild/bazel#4545]
### Description of the problem / feature request:

Very critical bug for users of close-source private repositories.

My case: 
1. My private repository A/.git/config
```
[remote "origin"]
	url = git@bitbucket.org:MY/PRIVATE/REPO
	fetch = +refs/heads/*:refs/remotes/origin/*
```
2. A/WORKSPACE
```
load('@bazel_tools//tools/build_defs/repo:git.bzl', system_git_repository = 'git_repository')
system_git_repository(
    name = "bazel_gazelle",
    remote = "https://github.com/bazelbuild/bazel-gazelle.git",
    commit = "734db0c7a082ffc38cc19f7c9a6f8a20dd0441a1",
)
```
3. bazel-gazelle
```

  _maybe(native.git_repository,
      name = "bazel_skylib",
      remote = "https://github.com/bazelbuild/bazel-skylib",
      commit = "f3dd8fd95a7d078cb10fd7fb475b22c3cdbcb307", # 0.2.0 as of 2017-12-04
  )
```
https://github.com/bazelbuild/bazel-gazelle/blob/7585a43dbca7efcb5647f8c9000cd68926daaa9a/deps.bzl#L18
4. During fetch according to network failure bazel failed to fetch bazel-skylib
5. A/.git/config now is following:
```
[remote "origin"]
	url = git@bitbucket.org:MY/PRIVATE/REPO
        url = https://github.com/bazelbuild/bazel-skylib
	fetch = +refs/heads/*:refs/remotes/origin/*
```
6. git push trying to push my private repo data to bazel-skylib

### Operation system

OSX High Sierra

### What's the output of `bazel info release`?
0.9.0-homebrew

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Create git repository and add BUILD/WORKSPACE files
2. Add external native.git_repository "foo" to WORKSPACE
3. In "foo" add external native.git_repository "bar" with incorrect commit.
4. Try to fetch "foo" / build something which uses "foo"

Expected behavior: just error
Actual behavior: error AND modification of .git/config of your first repository

**Comment by excavador** [comment]
As result, you ".git/config" has following form:

```
[remote "origin"]
	url = YOUR_PRIVATE_REPO
        url = URL_OF_PUBLIC_REPO_FOO
	fetch = +refs/heads/*:refs/remotes/origin/*
```
and push goes to BOTH repositories

**Comment by excavador** [comment]
Problem somewhere around https://github.com/bazelbuild/bazel/blob/ac0d354437c15003e79ec0fec168762cc9b676de/src/main/java/com/google/devtools/build/lib/bazel/repository/GitCloner.java#L190

Seems like it processing correctly incorrect commit of first dependency, but broken on incorrect commit of dependency of dependency (but I don't sure).

I tried to find the root of cause, but seems like it's some unexpected behavior of jgit...

**Comment by aehlig** [comment]
> Assigned #4545 to @aehlig.

I'll have a look. But please note that this issue is talking about a use
case that is *explicitly* not supported. Quoting
https://docs.bazel.build/versions/master/be/workspace.html#git_repository

  If you are using a private repository, prefer the Skylark git repository rules,

Also, the native git_repository rules are deprecated and will be removed eventually
anyway; so this issue might just result in the deprecation being made faster.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by excavador** [comment]
@aehlig you missed the point.

I am using PUBIC git_repository INSIDE private git repository.
Usage of PUBLIC git_repository affects my private workspace's git repository

**Comment by excavador** [comment]
> Also, the native git_repository rules are deprecated and will be removed eventually
anyway; so this issue might just result in the deprecation being made faster.

@aehlig yeah, but a lot of rules (rules_go, gazelle, etcetera) still using native.git_repository for bazel-skylib, for instance

My case: 
1. My private repository A
2. Inside workspace
```
load('@bazel_tools//tools/build_defs/repo:git.bzl', system_git_repository = 'git_repository')
  system_git_repository(
      name = "bazel_gazelle",
      remote = "https://github.com/bazelbuild/bazel-gazelle.git",
      commit = "734db0c7a082ffc38cc19f7c9a6f8a20dd0441a1",
  )
```
3. Inside bazel-gazelle
```

  _maybe(native.git_repository,
      name = "bazel_skylib",
      remote = "https://github.com/bazelbuild/bazel-skylib",
      commit = "f3dd8fd95a7d078cb10fd7fb475b22c3cdbcb307", # 0.2.0 as of 2017-12-04
  )
```
https://github.com/bazelbuild/bazel-gazelle/blob/7585a43dbca7efcb5647f8c9000cd68926daaa9a/deps.bzl#L18
4. During fetch according to network failure bazel failed to fetch bazel-skylib
5. .git/config inside A now has following:
```
[remote "origin"]
	url = git@bitbucket.org:MY/PRIVATE/REPO
       url = https://github.com/bazelbuild/bazel-skylib
	fetch = +refs/heads/*:refs/remotes/origin/*
```
6. git push trying to push my private repo data to bazel-skylib

**Comment by excavador** [comment]
@aehlig I hope, now is clear, what's happens. I am using bazel according to documentation, native.git_repository used only for public repositories, but according to some bazel bug network failure on git operations introduce url to public repo to .git/config of my private repo

**Comment by excavador** [comment]
Major pittfals for me - I am bazel contributor and have access to push to some repos

**Comment by aalexand** [comment]
Maybe a better title for the issue would be "`git push origin` may push to unintended remote URL after unsuccessful bazel's git fetch", or something like that.

**Comment by excavador** [comment]
@aehlig @meteorcloudy hello, guys!
I am so sorry for my pure english.
Can you please provide some feedback?
1.  How clear problem has described now? 
2. Can you reproduce this behavior?
3. Can you confirm the severity of this problem?
Thank you!

**Comment by dslomov** [comment]
Is it critical that the repo is private repo? (I cannot repro with public repos)

**Comment by dslomov** [comment]
I cannot repro witth a private repro either. The repo is https://bitbucket.org/dslomov/repro-4545, I can invite you to it to have a look.
```
$ bazel version
Build label: 0.9.0
Build target: bazel-out/k8-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Dec 19 09:31:58 2017 (1513675918)
Build timestamp: 1513675918
Build timestamp as int: 1513675918
```

**Comment by excavador** [comment]
@dslomov you have three reports:
1. First one (which affected) - it's private in my case, I think it's not important
2. Second one - public bazelbuild repo - which I define by ```load('@bazel_tools//tools/build_defs/repo:git.bzl', system_git_repository = 'git_repository')```
3. Third one - public bazelbuild repo - dependency of second.

During external repo fetch second one fetched, while it's dependency - third one - can not be fetched.
First repository after that has .git/config modification -it's definitely unexpected for user.

It's reproduced just time-to-time, typically - when you have some outdated versions of dependency in bazel private directory (/var/private/_bazel_username/blablabla).
After update your first repo you receive updated versions for second, which has updated versions of dependencies, and SOMETIME problem reproduced.

It's seems like to some problem in jgit or native.git_repository

**Comment by excavador** [comment]
@dslomov other words - I do not have stable reproduction case.

First time we saw problem two weeks ago, I decided what developer misclicked something in IDEA.
Second time was few days ago on my eyes - developer updated our repo (first repo in my description), execute bazel build, bazel_skylib failed to fetch (dependency of bazel_gazelle) and after that first what I made - checked .git/config, it was modified by bazel (I am 100% sure the problem on bazel side).

I do not know how to reproduce this flaky bug

**Comment by excavador** [comment]
@dslomov I highlight what repo is private, because this private repo can be published by accident to public.

**Comment by dslomov** [comment]
well, that's obviously not great, but since we do not have a repro case, I do not really know what to do here :(

Long term solution is to deprecate and remove native.git_repository and jgit in general, we should prioritize that. 
I took a look at jgit bug tracker, but I have not found anything relevant. 

Any good suggestions on how to proceed? All I have is:
- if that repeats, try to idenify the repro scenario
- build custom bazel with the latest jgit (4.10.0) and give it a run for a couple of weeks. If the problem disappears, we can upgrade jgit in Bazel.

**Comment by excavador** [comment]
@dslomov It's repeat, but is can not be reproduced repeatedly.

For repro you need some network failure on fetch third-dependency.
Seems like it reproduced in following cases:

1. You already have some external repo fetched
2. You updated version of this external repo
3. You run something which force to re-load this repo
4. You receive network failure on this fetch.

**Comment by excavador** [comment]
@dslomov other words - I'm 90% sure the problem on errors processing from jgit.
jgit raise some exception on network failure and bazel does not process it correctly - and add remote url to wrong git checkout

**Comment by dslomov** [comment]
One thing I do not understand is where the https://github.com/bazelbuild/bazel-skylib comes from.
If your WORKSPACE file does not mention it, bazel should not find it - we do not read WORKSPACEs from external repos.

**Comment by dslomov** [comment]
Oh I see, it is because you are using a pseudo-recursive workspace trick, with loading a `def.bzl` file.
A workaround (not ideal): redefine the offending repos in your own WORKSPACE using non-native `git_repositiory`

**Comment by excavador** [comment]
@dslomov 

```

  _maybe(native.git_repository,
      name = "bazel_skylib",
      remote = "https://github.com/bazelbuild/bazel-skylib",
      commit = "f3dd8fd95a7d078cb10fd7fb475b22c3cdbcb307", # 0.2.0 as of 2017-12-04
  )
```
https://github.com/bazelbuild/bazel-gazelle/blob/7585a43dbca7efcb5647f8c9000cd68926daaa9a/deps.bzl#L18

gazelle_dependencies() function

**Comment by excavador** [comment]
> 
A workaround (not ideal): redefine the offending repos in your own WORKSPACE using non-native git_repositiory

Good workaround, thank you. But we can not override all repositories from all pseudo-recursive tricks...

**Comment by excavador** [comment]
So, I guess it's combination of update bazel-gazelle (which requires new, unknown in my bazel external repository checkout commit) and network failure of git clone.

Somewhere bazel make "git remote set-url" on this case, and if dependency checkout removed already, this update go to your workspace repository

**Comment by dslomov** [comment]
I tried to repro this, also emulating network failures, but couldn't.
As @excavaodor points out in the privite mail, the problem is most likely here: https://github.com/bazelbuild/bazel/blob/ac0d354437c15003e79ec0fec168762cc9b676de/src/main/java/com/google/devtools/build/lib/bazel/repository/GitCloner.java#L189, which suggests jgit issue (all the cloning and `git remote set-url` equivalents happen inside `Git.cloneRepository().....call()`).

Do you want to try building your own bazel and upgrading to the latest jgit?

**Comment by excavador** [comment]
@dslomov I made it already:
https://github.com/bazelbuild/bazel/pull/3823

The problem is following: I can not stable reproduce it, as result, I never can be sure helped it or not.
From other hands, when problem reproduced - I can not switch to own version of bazel and check for the reason...

**Comment by dslomov** [comment]
>  I can not stable reproduce it, as result, I never can be sure helped it or not.
of course. What I was suggesting was that you distribute the modified version of Bazel in your team and observe if the problem occurs over time.

**Comment by excavador** [comment]
@dslomov got it, thank you.
On next reproduction I will contact you with request to debug assistant.

I read the document "Future of external repositories".
When we can wait to remove of "native.git_repository", how do you estimate?

**Comment by excavador** [comment]
Problem is not actual anymore, because native.git_repository replaced by load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository") in bazel completely
