### ISSUE TITLE
syntaxError in File "bazel-out/host/bin/src/create_embedded_tools"

### ISSUE THREAD

**Issue by shmilyhh** [bazelbuild/bazel#4552]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> Target //src:bazel failed to build. And there is syntaxError in File "bazel-out/host/bin/src/create_embedded_tools".
> ERROR: /local/data/haoxu/Library/bazel-0.9.0-dist/src/BUILD:245:1: Executing genrule //src:embedded_tools failed (Exit 1): bash failed: error
 executing command
  (cd /tmp/bazel_ywcCVYL0/out/execroot/io_bazel && \
  exec env - \
    PATH=/usa/haoxu/Library/Full-JDK-Linux-x64-jdk1.8.0_152/bin:/usa/haoxu/bin:/usa/haoxu/byobu/bin:/usa/haoxu/homebrew/bin:/usa/haoxu/bin:/u
sa/haoxu/byobu/bin:/usa/haoxu/homebrew/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/src/create_embedded_tools "bazel-out/k8-opt/ge
nfiles/src/embedded_tools.zip" bazel-out/k8-opt/bin/src/embedded_tools.params')
  File "bazel-out/host/bin/src/create_embedded_tools", line 2
    PK
      ^
SyntaxError: invalid syntax
Target //src:bazel failed to build
INFO: Elapsed time: 231.628s, Critical Path: 67.71s

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> I download the bazel 0.9.0, and jdk1.8.0_152 is from https://github.com/magiclen/Full-JDK-Linux-x64/releases/tag/jdk1.8.0_152, then just run the ./compile.sh

### What operating system are you running Bazel on?

> CentOs

### What's the output of `bazel info release`?

> /usa/haoxu/bin/bazel: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usa/haoxu/bin/bazel)

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

>fatal: Not a git repository (or any parent up to mount parent /local)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount parent /local)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount parent /local)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

###  Have you found anything relevant by searching the web?

> No

**Comment by meteorcloudy** [comment]
@shmilyhh Can you tell me which python version are you using?

**Comment by shmilyhh** [comment]
@meteorcloudy Python 2.5.1

**Comment by meteorcloudy** [comment]
Can you upgrade it to 2.7 or higher?

**Comment by shmilyhh** [comment]
@meteorcloudy Thank you. I use the python 2.7. But I meet a new problem, it is same as #2808. Do you know how to change the size of the /tmp folder? Thanks.

**Comment by meteorcloudy** [comment]
Sorry, I'm not familiar with that...

**Comment by shmilyhh** [comment]
@meteorcloudy Thank you. I appreciate your help.
