### ISSUE TITLE
zip error: Output file write failure (write error on zip file)

### ISSUE THREAD

**Issue by shmilyhh** [bazelbuild/bazel#4553]
### Description of the problem / feature request:

> zip error: Output file write failure (write error on zip file)
> it is same as #2808

### Feature requests: what underlying problem are you trying to solve with this feature?

> the problem is the size of /tmp is too small. But I don't have the permission to increase the it. Are there any other ways to solve this problem? Thanks.
> Can I let the bazel store the temporary files into another folder instead of /tmp?

**Comment by shmilyhh** [comment]
I found what I want in #2738.

**Comment by huma-cloud** [comment]
Hello I'm trying to do bed2tped through plink, but every time I'm getting : "File write Failure"
Although I've enough space/storage in my linux account. I'm stucking over here since last 10 days.
Please tell me what's the problem
