### ISSUE TITLE
install tensorflow on BeagleBone Black

### ISSUE THREAD

**Issue by yuanbuckingham** [bazelbuild/bazel#4554]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> I have managed to compile tensorflow from source and install it on BeagleBone Black according to https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/GUIDE.md,
and I can import tensorflow in Python 2.7.13. However, when  I want to test the simple 'Hello, tensorflow', I got the 'Bus error' and directly quit from python as follows:

root@beaglebone:/tmp# python
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
>>> sess.run(hello)
Bus error

### Feature requests: what underlying problem are you trying to solve with this feature?

>use tensorflow on BeagleBone Black

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

> Debian 9

### What's the output of `bazel info release`?

Build label: 0.9.0- (@non-git)
Build target: bazel-out/arm-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 15 06:27:50 +50016 (1516202260070)
Build timestamp: 1516202260070
Build timestamp as int: 1516202260070

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

I built bazel acoording to https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/GUIDE.md

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

fatal: Not a git repository (or any of the parent directories): .git

###  Have you found anything relevant by searching the web?

> https://github.com/tensorflow/tensorflow/issues/15062
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by jin** [comment]
This seems like a Tensorflow issue instead of a Bazel one, since it looks like you have managed to build and import TF successfully. Do you have information on why you think this is a Bazel issue?

**Comment by yuanbuckingham** [comment]
Sorry, putted in a wrong place.
