### ISSUE TITLE
Linking against system libraries on Windows

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#4556]
### Description of the problem / feature request:

As specified [here](https://github.com/bazelbuild/bazel/issues/1945#issuecomment-255723827) I tried to link my binary against system library using `linkopts = ["-Wl,advapi32.lib"]` but it looks like it does no longer work:
```
C:\Users\Chebotarev_V\Documents\bazel-issues\windows-link-against-system-libraries>bazel build ...
INFO: Analysed target //:hello-world (1 packages loaded).
INFO: Found 1 target...
ERROR: C:/users/chebotarev_v/documents/bazel-issues/windows-link-against-system-libraries/BUILD:3:1: Linking of rule '//:hello-world' failed (Exit 1120)
LINK : warning LNK4044: unrecognized option '/Wl,advapi32.lib'; ignored
hello-world.o : error LNK2019: unresolved external symbol __imp_LogonUserA referenced in function main
bazel-out/x64_windows-fastbuild/bin/hello-world.exe : fatal error LNK1120: 1 unresolved externals
Target //:hello-world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.312s, Critical Path: 0.15s
FAILED: Build did NOT complete successfully
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Please find an example here: https://github.com/excitoon/bazel-issues/tree/master/windows-link-against-system-libraries

### What operating system are you running Bazel on?

Windows 10 x64

### What's the output of `bazel info release`?

```
Build label: 0.9.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Dec 19 09:32:04 2017 (1513675924)
Build timestamp: 1513675924
Build timestamp as int: 1513675924
```

###  Have you found anything relevant by searching the web?

Something, but not enough: #1945, #1980.

**Comment by meteorcloudy** [comment]
That's because we no long have the wrapper script to do the translation. 
Try `linkopts = ["-DEFAULTLIB:advapi32.lib"]`

**Comment by excitoon** [comment]
Thank you very much.
