### ISSUE TITLE
scala compile 'too many arguments'

### ISSUE THREAD

**Issue by JackSullivan** [bazelbuild/bazel#456]
I'm using the scala rules script and I noticed that on my mac I get a 'too many arguments' failure at `touch -t 198001010000 $(find .)` in the compile method. I've replaced this in my version with 
```bash
touch -t 198001010000 $(find {out}_tmp)
touch -t 198001010000 {manifest}
```

which works for me an I suspect would have the same effect, but I'm not sure if this is the best approach.

**Comment by damienmg** [comment]
@laurentlb : I let you finish this one as you are commenting the pull request.
