### ISSUE TITLE
Building Windows DLL without exports fails

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#4561]
### Description of the problem / feature request:

In order to produce import library for a DLL bazel uses `/IMPLIB` flag of the linker and expect that it will force creating import library in the place specified:
https://msdn.microsoft.com/en-us/library/67wc07b9.aspx

Unfortunately, this flag is not managing the fact of creating or not creating import library but only sets the name for it. If DLL does not export anything, linker do not create it by design. Unluckily, we actively use DLLs without imports for a reason.

The output of bazel is as follows:
```
C:\Users\Chebotarev_V\Documents\bazel-issues\windows-dll-without-exports>bazel build ...
INFO: Analysed target //:hellolib.dll (8 packages loaded).
INFO: Found 1 target...
ERROR: C:/users/chebotarev_v/documents/bazel-issues/windows-dll-without-exports/BUILD:3:1: output 'hellolib.ifso' was not created
ERROR: C:/users/chebotarev_v/documents/bazel-issues/windows-dll-without-exports/BUILD:3:1: not all outputs were created or valid
Target //:hellolib.dll failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 49.652s, Critical Path: 1.14s
FAILED: Build did NOT complete successfully
```

Please find an example in my repository:
https://github.com/excitoon/bazel-issues/tree/master/windows-dll-without-exports

### Feature requests: what underlying problem are you trying to solve with this feature?

We need building DLLs without exports.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/excitoon/bazel-issues/tree/master/windows-dll-without-exports

### What operating system are you running Bazel on?

Windows 10 x64

### What's the output of `bazel info release`?

```
Build label: 0.10.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Nov 9 22:42:19 +50056 (1517474731339)
Build timestamp: 1517474731339
Build timestamp as int: 1517474731339
```

###  Have you found anything relevant by searching the web?

Nothing expect mentioned.

**Comment by excitoon** [comment]
The same error in tensorflow:
```
ERROR: C:/users/chebotarev_v/documents/src/tensorflow/tensorflow/contrib/lite/BUILD:62:1: output 'tensorflow/contrib/lite/libcontext.ifso' was not created
ERROR: C:/users/chebotarev_v/documents/src/tensorflow/tensorflow/contrib/lite/BUILD:62:1: Couldn't build file tensorflow/contrib/lite/libcontext.so: not all outputs were created or valid
```

**Comment by meteorcloudy** [comment]
@excitoon I noticed this problem when I was implementing dynamic linking on Windows. The thing is you can not tell Bazel "this action may or may not generate this file". There's no way we can know if any symbols will be exported before the linking action. So the interface library (.ifso) has to be a mandatory output of the action. 

However, I think it's meaningless if you build a DLL that expose no symbol, right?

And to help with this issue, I implemented the `windows_export_all_symbols` feature.
You can use it like this:
```
cc_binary(
  name = "A",
  srcs = ["dummy.cc"],
  features = ["windows_export_all_symbols"],
)
```
Then Bazel will parse the object file of //:A to generate a DEF file, then use it during linking time to export all symbols found.

**Comment by excitoon** [comment]
> However, I think it's meaningless if you build a DLL that expose no symbol, right?

Not always. DLL is always exposing `DllMain()` and this is more than enough to make interaction with invoking process. I worked around that by specifying trivial `DEF` file. That forces compiler to generate `ifso` in any case.

**Comment by excitoon** [comment]
@meteorcloudy Did you make this feature to address #4561 ? If so it seems to be a huge overkill, according to https://docs.microsoft.com/en-us/cpp/build/reference/implib-name-import-library?view=vs-2017 :
> A program contains exports if one **or more** of the following are specified:
>     The __declspec(dllexport) keyword in the source code
>     EXPORTS statement in a .def file
>     An /EXPORT specification in a LINK command

The solution of this issue should be as follows - if we have no `win_def_file` and `windows_export_all_symbols`, we should generate a def file containing only `LIBRARY <LIBNAME>` and pass it to the linker. In this case linker will always generate IMPLIB and add all symbols which are exported in the code.

I wonder if `windows_export_all_symbols` is used by somebody?

**Comment by meteorcloudy** [comment]
@excitoon No, I didn't make that feature just to address #4561, it is a part of https://docs.google.com/document/d/1ZK4f84wype5NsZ7ltOUqvyFr7eKOIf4Wd-DrU6HCBkA/edit#heading=h.atngtzdodour

There is a similar feature in CMake as well, https://cmake.org/cmake/help/v3.4/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html

**Comment by meteorcloudy** [comment]
It is used in TensorFlow, https://github.com/tensorflow/tensorflow/blob/dc34ddc6ddcc0581050322a98abbfc19203484e4/tensorflow/tensorflow.bzl#L1635

**Comment by excitoon** [comment]
@meteorcloudy I understand, but the original problem is still not fixed (`windows_export_all_symbols` can greatly increase the size of a library). May I proceed with the solution I proposed?

**Comment by meteorcloudy** [comment]
Oh, I see. You actually don't want anything to be exported by still want the DLL file. If this is the case, your solution sounds good to me. Please proceed, I'm happy to review the change.

**Comment by excitoon** [comment]
Exactly my case. But I have to add that this is not only our case. For example, Microsoft uses that: https://stackoverflow.com/questions/6588249/dll-without-exported-functions . Even without exporting anything, `DllMain` is getting called, and also DLL can be used as a resource storage.

**Comment by maximyurchuk** [comment]
Hello @meteorcloudy, I've just found another repro case of this issue, it seems more legitimate: 
repro is [here](https://github.com/maximyurchuk/bazel-issues/tree/master/use_runfiles_from_cc_library). 

This example is more real-world, because `use_runfiles` (from link above) rule can pack targets with all runfiles dependencies as an example (and actually this case not working for me). In this sample there is no strange .dll files without exports: I just want build cc_library and put all it outputs somethere.
