### ISSUE TITLE
repeating any test with same invocation id gives NO STATUS

### ISSUE THREAD

**Issue by ola-rozenfeld** [bazelbuild/bazel#4565]
To reproduce:

export BAZEL_INTERNAL_INVOCATION_ID=d6d3f134-70ae-4e25-a4ca-53fd35c5e63e
bazel test  hello-world_test
bazel test  hello-world_test

It doesn't matter whether the test passes or fails -- on the second run, Bazel returns:

//:hello-world_test                                                   NO STATUS
Executed 0 out of 1 test: 1 was skipped.

This is not a new bug, I see it as far back as 0.5.3. It also fails regardless of whether the invocation id is passed by environment variable or the new --invocation_id flag.

**Comment by ulfjack** [comment]
Working as intended. You aren't supposed to set BAZEL_INTERNAL_INVOCATION_ID at all unless you're running a cloud build service and you need to post BES streams with the same invocation id as Bazel, but you need to start posting streams before actually invoking Bazel. That's the only supported use case for this env variable.

Assuming you are running a cloud build service, you must set different values for BAZEL_INTERNAL_INVOCATION_ID for different bazel invocations. Not doing so can cause a lot of problems, including causing data corruption in the build event service.

That said, the explanation for the observed behavior is thus: we're creating a Skyframe node with the invocation id and use that to trigger test re-execution (among other things). If the invocation id doesn't change, then it's the same invocation, so we don't need to re-trigger. Technically, we could have a separate (internal internal) id to trigger test re-execution, but the contract is that you are not supposed to do that anyway.

**Comment by ola-rozenfeld** [comment]
Go it. We ran into it because we now pass the invocation_id as a flag to Bazel in our Guitar tests, and we need to remember to remove it from the command if we want to manually trigger the same command again. But I guess it's fine. Thank you!
