### ISSUE TITLE
native.bazel_version does not exist in the Homebrew distribution

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#4566]
Is this working as intended? Homebrew compiles using `compile.sh` and sets its own version name, but somehow the `bazel_version` attribute is not set in the `native` module.

Location where the version name is generated in Homebrew: https://github.com/Homebrew/homebrew-core/blob/master/Formula/bazel.rb#L18

This is causing issues for version checks like in https://github.com/bazelbuild/bazel-skylib/issues/17

**Comment by neogia** [comment]
I'm having the exact same issue. Is there a workaround in the meantime?

**Comment by jin** [comment]
@neogia The easiest workaround for now will be to install Bazel from https://github.com/bazelbuild/bazel/releases/tag/0.10.0

**Comment by jin** [comment]
I've made a mistake debugging this - the version checking is working as intended. @neogia do you mind describing what your project set up is?
