### ISSUE TITLE
Tutorial is broken with rules_apple 0.2.0

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#4567]
The ios tutorial on CI is broken due to incompatibility between Bazel at HEAD and rules_apple 0.2.0. Tracking in that repository as https://github.com/bazelbuild/examples/issues/54.

This is not a release blocker, but shows up as a failed test in CI.

**Comment by sergiocampama** [comment]
Should the examples be updated to the HEAD version of rules_apple as well? both bazel and rules_apple are in constant evolution, paired together, so they should both be advanced in tandem.

**Comment by katre** [comment]
The intent of the examples is to be a google base for people to copy for new projects, so we should demonstrate correct use of the latest release.

That said, rules_apple needs a new release to be compatible with Bazel 0.10.0, and then the examples should be updated as well.

**Comment by sergiocampama** [comment]
I'm looking into that
