### ISSUE TITLE
Implement C++ Starlark API

### ISSUE THREAD

**Issue by oquenchil** [bazelbuild/bazel#4570]
### Description of the problem / feature request:
The API should expose to Skylark from Java the logic for the creation of compilation and linking actions.

### Feature requests: what underlying problem are you trying to solve with this feature?

The main problem to solve is inter-operability between different rules/languages that have dependencies on C++ code.

Design doc:https://docs.google.com/document/d/1cRRdHOPTTUXBbq9Cj9hk_WLnPqsGtAoQynYd7TKBQI8/edit?disco=AAAACkgMw7E

**Comment by mhlopko** [comment]
Bazel@HEAD now accepts `--experimental_enable_cc_skylark_api` that will enable the current WIP version of the API. It's only for experimenting at this point, we break it daily, and we will not support users using it yet. But feedback is more than welcome.

**Comment by mfarrugi** [comment]
Is there a better way to traverse the API than `print(dir(ctx.attr.cc_lib.cc))`?

Would like to see if it better fits https://github.com/bazelbuild/rules_rust/pull/108

**Comment by oquenchil** [comment]
Sandwich is ready:
https://docs.bazel.build/versions/master/skylark/lib/cc_common.html#compile

**Comment by excitoon** [comment]
Hey @oquenchil . How to pass data to `LinkBuildVariables` of `cc_common.link`? For example, `interface_library` name?

CcModule.java:290
```
        /* interfaceLibraryBuilder= */ null,
        /* interfaceLibraryOutput= */ null,
```

Repro case is here:
https://groups.google.com/forum/#!topic/bazel-discuss/I-yvg7xbbG0

**Comment by excitoon** [comment]
Also, dynamic libraries in `create_linking_context_from_compilation_outputs` are not being generated on Windows:
CcModule.java:1435
```
            .setShouldCreateDynamicLibrary(
                !disallowDynamicLibraries
                    && !featureConfiguration
                        .getFeatureConfiguration()
                        .isEnabled(CppRuleClasses.TARGETS_WINDOWS))
```
