### ISSUE TITLE
Inclusion checking is broken in 0.10.0

### ISSUE THREAD

**Issue by iphydf** [bazelbuild/bazel#4572]
```
external/yasm/BUILD.bazel:115:1: undeclared inclusion(s) in rule '@yasm//:genperf':
this rule is missing dependency declarations for the following files included by 'external/yasm/libyasm/xstrdup.c':
  '/usr/lib/clang/3.8.1/include/stddef.h'
  '/usr/lib/clang/3.8.1/include/stdarg.h'
  '/usr/lib/clang/3.8.1/include/__stddef_max_align_t.h'
  '/usr/lib/clang/3.8.1/include/stdint.h'
INFO: Elapsed time: 3.690s, Critical Path: 0.18s
FAILED: Build did NOT complete successfully
```

https://github.com/iphydf/toktok-stack/blob/build-yasm/third_party/BUILD.yasm
https://github.com/iphydf/toktok-stack/blob/build-yasm/WORKSPACE

**Comment by nicolasnoble** [comment]
Blocking issue for the gRPC team - this happens if you specify `build --client_env=CC=clang` in the `tools/bazel.rc` file.

**Comment by adelez** [comment]
Friendly ping? Is there any update on this?

**Comment by jin** [comment]
@mhlopko can you take a look at this please?

**Comment by g-easy** [comment]
I ran into this also.

```
export CC=clang
bazel clean --expunge
bazel build $some_thing
```

Looking at `$(bazel info output_base)/external/local_config_cc/CROSSTOOL`, it has:

```
  cxx_builtin_include_directory: "/usr/include/c++/6.3.0"
  cxx_builtin_include_directory: "/usr/include/x86_64-linux-gnu/c++/6.3.0"
  cxx_builtin_include_directory: "/usr/include/c++/6.3.0/backward"
  cxx_builtin_include_directory: "/usr/local/include"
  cxx_builtin_include_directory: "/usr/lib/llvm-3.8/lib/clang/3.8.1/include"
  cxx_builtin_include_directory: "/usr/include/x86_64-linux-gnu"
  cxx_builtin_include_directory: "/usr/include"
```

but no `/usr/lib/clang/3.8.1/include`

**Comment by benjaminp** [comment]
If you're building on a Debian derivative, it's likely due to a Debian patch as described in https://github.com/bazelbuild/bazel/issues/3977#issuecomment-339894732.

**Comment by philwo** [comment]
@ulfjack @mhlopko This seems like a huge regression. Can you help figuring out what's going on here?

**Comment by mhlopko** [comment]
Looking into it. The culprit is https://source.bazel.build/bazel/+/e99279bcce475249e58543a5330fa35e59acd7e8:tools/cpp/unix_cc_configure.bzl;dlc=a3fd5e76be71988035388c7e09c3257c8cbb2dd3, since then we're adding `-no-canonical-prefixes` if compiler supports it and this apparently makes clang to return different include paths in .d files than what it reportins in `clang -E -xc++ - -v`.

**Comment by mhlopko** [comment]
Filed https://github.com/bazelbuild/continuous-integration/issues/186

**Comment by mhlopko** [comment]
And uploaded https://bazel-review.googlesource.com/c/bazel/+/39872 with the fix.

**Comment by mhlopko** [comment]
Could you test that the patch fixes the problem for you?

**Comment by ulfjack** [comment]
Does this also fix #3977?

**Comment by mhlopko** [comment]
Ok the exported cl I linked to is a merge of multiple changes, I'll link to a proper patch soon :)

**Comment by mhlopko** [comment]
Correct patch: https://bazel-review.googlesource.com/c/bazel/+/39951
