### ISSUE TITLE
rule is missing dependency declarations for the following files included by 'tensorflow/core/lib/hash/crc32c_accelerate.cc'

### ISSUE THREAD

**Issue by sxhmilyoyo** [bazelbuild/bazel#4573]
### Description of the problem / feature request:

> ERROR: /infolab/infolab5/haoxu/Library/tensorflow/tensorflow/core/BUILD:1559:1: undeclared inclusion(s) in rule '//tensorflow/core:l[19/9672]
rc32c_accelerate_internal':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/lib/hash/crc32c_accelerate.cc':
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/include/stddef.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/include/stdint.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/stdint.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/features.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/sys/cdefs.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/bits/wordsize.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/gnu/stubs.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/gnu/stubs-64.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/bits/wchar.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/include/nmmintrin.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/include/smmintrin.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/include/tmmintrin.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/include/pmmintrin.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/include/emmintrin.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/include/xmmintrin.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/include/mmintrin.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/include/mm_malloc.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/include/c++/7.2.0/stdlib.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/include/c++/7.2.0/cstdlib'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/include/c++/7.2.0/x86_64-conda_cos6-linux-gnu/bits/c++co
nfig.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/include/c++/7.2.0/x86_64-conda_cos6-linux-gnu/bits/os_de
fines.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/include/c++/7.2.0/x86_64-conda_cos6-linux-gnu/bits/cpu_d
efines.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/stdlib.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/bits/waitflags.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/bits/waitstatus.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/endian.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/bits/endian.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/bits/byteswap.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/xlocale.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/sys/types.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/bits/types.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/bits/typesizes.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/time.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/sys/select.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/include/mm_malloc.h'              [0/9672]
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/include/c++/7.2.0/stdlib.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/include/c++/7.2.0/cstdlib'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/include/c++/7.2.0/x86_64-conda_cos6-linux-gnu/bits/c++co
nfig.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/include/c++/7.2.0/x86_64-conda_cos6-linux-gnu/bits/os_de
fines.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/include/c++/7.2.0/x86_64-conda_cos6-linux-gnu/bits/cpu_d
efines.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/stdlib.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/bits/waitflags.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/bits/waitstatus.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/endian.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/bits/endian.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/bits/byteswap.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/xlocale.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/sys/types.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/bits/types.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/bits/typesizes.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/time.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/sys/select.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/bits/select.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/bits/sigset.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/bits/time.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/sys/sysmacros.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/bits/pthreadtypes.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/alloca.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/bits/stdlib.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/x86_64-conda_cos6-linux-gnu/include/c++/7.2.0/bits/std_abs.h'
  '/infolab/infolab5/haoxu/Library/anaconda/envs/anapy27/lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/include/popcntintrin.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 26.247s, Critical Path: 3.67s
FAILED: Build did NOT complete successfully

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> conda install -c anaconda gxx_linux-64
> conda install -c anaconda gcc_linux-64
> bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

### What operating system are you running Bazel on?

> CentOs

### What's the output of `bazel info release`?

>INFO: $TEST_TMPDIR defined: output root default is '/infolab/infolab5/haoxu/Library/.cache/bazel' and max_idle_secs default is '15'.
WARNING: Output base '/infolab/infolab5/haoxu/Library/.cache/bazel/_bazel_haoxu/95196ed5087168c723729aeb7fc160d9' is on NFS. This may lead to surprising failures and undetermined behavior.
.................................
release 0.9.0- (@non-git)

**Comment by owainkenwayucl** [comment]
FWIW I'm fairly certain this is due to the GCC you have installed being in your home directory and some part of `/infolab/infolab5` is a sym-link (presumably to a filesystem mount).  The `configure` script is quite bad at dealing with sym-links, particularly when referring to the C compiler used by `nvcc` and so if you can work out the real path and put that in it should resolve the issue (see the issue I've referenced to this one above for an example).
