### ISSUE TITLE
remote/performance: add gzip compression to HTTP remote cache

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#4575]
The Apache client supported gzip, but the new Netty client doesn't.

cc: @jgavris

**Comment by jgavris** [comment]
Let's also add `Content-Type: 'application/octet-stream`. I noticed the newer objects in my GCS bucket do not have this set either.

https://cloud.google.com/storage/docs/transcoding

**Comment by excitoon** [comment]
I'd like to make little patches to implement this as it blocks me now.

**Comment by excitoon** [comment]
It seems like it is pretty easy  :)
@buchgr

**Comment by jgavris** [comment]
@excitoon That might help for some cache backends, but for people on say, Google Cloud Storage as their cache backend, it does not do [compressive transcoding](https://cloud.google.com/storage/docs/transcoding) (this would be *very* expensive with respect to CPU time). What Jakob and I were discussing offline was a scheme to store compressed blobs in GCS, and then detect and decompress them in the bazel client.

**Comment by excitoon** [comment]
Yep, I know about buchgr/bazel-remote#12 , this is just a client-side thing. Anyway, it is at least a progress on this task!
