### ISSUE TITLE
[Feature] Special filegroup variant matching all files including subpackages

### ISSUE THREAD

**Issue by Androbin** [bazelbuild/bazel#4577]
### Description of the feature request:

Provide a special variant of `glob(["**/*"])` matching files in subpackages as well.

### What underlying problem are you trying to solve with this feature?

Getting rid of bloated `all_files` target hierarchies.
See tensorflow/tensorflow#15758 and tensorflow/tensorflow#16491 for reference.

###  Have you found anything relevant by searching the web?

The [documentation for `glob`](https://docs.bazel.build/versions/master/be/functions.html#glob) currently says the following:
> Labels are not allowed to cross the package boundary and glob does not match files in subpackages. For example, the `glob` expression `**/*.cc` in package `x` does not include `x/y/z.cc` if `x/y` exists as a package (either as `x/y/BUILD`, or somewhere else on the package-path). This means that the result of the `glob` expression actually depends on the existence of `BUILD` files — that is, the same `glob` expression would include `x/y/z.cc` if there was no package called `x/y` or it was marked as deleted using the `--deleted_packages` flag.

**Comment by Androbin** [comment]
@jart What exactly do you think are the tradeoffs here?

**Comment by ittaiz** [comment]
I don’t know why tensorflow needs this but I can say skylark rules could
also use this for easier e2es which need to import their own code into the
test workspace

**Comment by Androbin** [comment]
@ittaiz TensorFlow needs this mostly for sanity checks.
Plus, a `Makefile` build not fully determined in advance.

**Comment by Androbin** [comment]
Actually, this might as well just be a special value for `data` attributes.

**Comment by Androbin** [comment]
@yifeif Do you think this would work for TensorFlow?

**Comment by jart** [comment]
For cases when one wishes to glob across packages, Bazel might not be the right tool for the job. What we generally do is write a separate tool, like Copybara, or pylint, which we run independently of Bazel, in our `.travis.yml` or whatever. For example: https://github.com/tensorflow/tensorboard/blob/master/.travis.yml

**Comment by laszlocsomor** [comment]
This is infeasible with Bazel's current design. `glob` doesn't cross package boundaries on purpose: Bazel relies on packages being independent of each other. @laurentlb knows the exact details.

I second everything @jart said in her [comment](https://github.com/bazelbuild/bazel/issues/4577#issuecomment-363849176).
