### ISSUE TITLE
RUNFILES_MANIFEST_FILE is set to a nonexistent path on Linux

### ISSUE THREAD

**Issue by rjogrady** [bazelbuild/bazel#4586]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:
RUNFILES_MANIFEST_FILE is set to a nonexistent place on Linux

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

const char* manifest_file_path = std::getenv("RUNFILES_MANIFEST_FILE");
FILE* f = fopen(manifest_file_path, "r");
// fails

### What operating system are you running Bazel on?
Linux

### What's the output of `bazel info release`?
release 0.10.0

###  Have you found anything relevant by searching the web?
It seems like this env variable intended only for use on Windows, but the environment variable is still being set in the environment. There is a manifest file, but the path to it is wrong.

### Any other information, logs, or outputs that you want to share?
The variable seems to point to a nonexistent bazel-sandbox directory under bazel-out.

**Comment by philwo** [comment]
@laszlocsomor This bug seems relevant to your interests.

**Comment by laszlocsomor** [comment]
> @laszlocsomor This bug seems relevant to your interests.

Indeed it is.

@rjogrady : Is this a `cc_binary` or a `cc_test` we are talking about? How exactly do you run the binary, using `bazel run`, `bazel test`, or build and then run from the output directory?

**Comment by rjogrady** [comment]
This was a cc_test and run via bazel test.

**Comment by laszlocsomor** [comment]
Thanks! Was the path something like `(...).runfiles/MANIFEST`? Does its parent directory exist? (Check this inside of the test.) Does that directory exist under `bazel-bin`?

I suspect this line to be the culprit: https://github.com/bazelbuild/bazel/blob/2a2aa7ab31367da47f8449059fdfcddfba3a20f1/tools/test/test-setup.sh#L106

It doesn't seem to check the existence of the file, just assumes it's there.

**Comment by rjogrady** [comment]
Ah, yeah, I think you nailed it.
The path is like:
/usr/local/.../.cache/bazel/_bazel_rjogrady/e4fe7294a547790a857197a33ce79b06/bazel-sandbo
x/1475856093921078659/execroot/proj/bazel-out/k8-fastbuild/bin/a_test.runfiles/MANIFEST
The parent directory does indeed exist inside the test.

**Comment by laszlocsomor** [comment]
FYI, I'm working on a runfiles library for C++ that'll make it easy to look up runfiles, without the client code needing to know about RUNIFILES_* envvars.

**Comment by laszlocsomor** [comment]
FYI: here's the commit stack, which is still under review and won't be released until Bazel 0.13.0 or so: https://bazel-review.googlesource.com/c/bazel/+/39570

**Comment by rjogrady** [comment]
Nice, that'll be super helpful.

**Comment by laszlocsomor** [comment]
Update: I'm still slowly working on the runfiles libraries (#4460), but the C++ one is not ready yet. I'm planning to make it so that the runfiles library follows the same strategy on all platforms: that it checks if `$RUNFILES_DIR/path/to/runfile` exists and if so, returns its path, otherwise tries to look it up from `$RUNFILES_MANIFEST_FILE`. This way runfiles lookup will work even with an incorrect manifest path value but an available runfiles tree.

**Comment by hsyed** [comment]
FYI I added this (adapted it from java test class in the repo) just to pick up a local jar that Is colocated with the Kotlin compiler. 

https://github.com/bazelbuild/rules_kotlin/blob/windows/kotlin/builder/src/io/bazel/kotlin/builder/utils/BazelUtils.kt

Had to add [this bit of trickery](https://github.com/bazelbuild/rules_kotlin/blob/6e76e73b5b2016adc581a4ce5a9328cef502dfe4/kotlin/builder/src/io/bazel/kotlin/builder/utils/BazelUtils.kt#L28-L34) to ensure the env var is only processed on windows. So this issue might apply to the Mac as well. I didn't verify if the env var was null, the file was non-existant or if the file was empty.

**Comment by janakdr** [comment]
This looks like a rules issue to me.
