### ISSUE TITLE
The Android rules require python to be on the PATH

### ISSUE THREAD

**Issue by pmuetschard** [bazelbuild/bazel#4591]
### Description of the problem / feature request:

Part of the Android rules for bazel don't look for Python correctly and require it to be on the `PATH`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Remove python from the `PATH`, but keep it in the standard place or set `BAZEL_PYTHON` to the location of python as instructed by the install [script](https://github.com/bazelbuild/bazel/blob/95aa487c02e20c6e0e137fca1670fc72ec9bd588/scripts/packages/chocolatey/tools/chocolateyinstall.ps1#L25).
Build something Android-y. While the rest of bazel will find python, the Android rules will fail with:

```
INFO: From Extracting Java resources from deploy jar for split Java resource apk:
LAUNCHER ERROR: Cannot launch process: "python.exe" C:\tmp\_bazel_xxx\xxxxxxxx\execroot\xxx\bazel-out\host\bin\external\bazel_tools\tools\android\resource_extractor.zip bazel-out/android-x86-fastbuild/bin/xxx/apk/xxx_deploy.jar bazel-out/android-x86-fastbuild/bin/xxx/apk/_dx/xxx/extracted_xxx_deploy.jar
Reason: (error: 2): The system cannot find the file specified.

ERROR: BUILD.bazel:29:1: output 'xxx/apk/_dx/xxx/extracted_xxx_deploy.jar' was not created
ERROR: BUILD.bazel:29:1: not all outputs were created or valid
```

However, with python on the `PATH`, this error does not happen.

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

0.10.0

**Comment by ahumesky** [comment]
Laszlo, could you take a look? None of us have a windows machine to verify this on.

**Comment by laszlocsomor** [comment]
I'll take a look.

**Comment by aj-michael** [comment]
I believe this is working as intended. The Android rules require the Python rules. The python rules on Windows require that either --python_path is specified, or python.exe is on the PATH. That is documented here:

https://docs.bazel.build/versions/master/windows.html#build-python

The code that looks for this is in the native python launcher. @meteorcloudy may have more details.

https://source.bazel.build/bazel/+/master:src/tools/launcher/python_launcher.cc;l=34?q=python_launcher.cc

**Comment by ahumesky** [comment]
Also, could you say what you mean with "the rest of bazel will find python"? The resource extractor is itself a py_binary, so if other py_binary rules work without having python on the path, then something seems strange.

**Comment by pmuetschard** [comment]
Looking at https://github.com/bazelbuild/bazel/search?q=BAZEL_PYTHON, apparently only `cc_configure` respects the `BAZEL_PYTHON` env variable as instructed by the install script. I suppose this is more of a feature request, then, to have the `py_*` rules respect that variable as well for consistency. Also, `cc_configure` should respect `--python_path`. Truly, everything that needs python should "find it" the same way.

**Comment by laszlocsomor** [comment]
There may be a deeper problem here: bazel on windows (also) appears to ignore `--python_path` if python is already on the `PATH`. I'm still investigating.

**Comment by laszlocsomor** [comment]
Update about my latest comment: this seems to work fine in Bazel 0.11.0rc2, it picks up `--python_path` even if there is already another python on the `PATH`. (I haven't looked at `BAZEL_PYTHON`.)

**Comment by meteorcloudy** [comment]
@pmuetschard `BAZEL_PYTHON` is deprecated. It was introduced specifically for **C++ toolchain** when it  needs python wrapper scripts for the MSVC compiler. It has nothing to do with any python rules.
Sorry for the confusing..

To specify python binary for python rules, you should either ensure `python.exe` is in PATH or pass `--python_path` flag.

**Comment by meisterT** [comment]
This is probably stale.

**Comment by jin** [comment]
No, the Android rules still use Python tools, and AFAIK doesn't use any hermetic python toolchains.
