### ISSUE TITLE
Change in recommended installer for Bazel on MacOS

### ISSUE THREAD

**Issue by helenalt** [bazelbuild/bazel#4593]
Homebrew is no longer a recommended way to install Bazel on macOS.
Until that's changed, please remove the word "(recommended)" and place "(recommended)" next to "Use the binary installer in this doc https://docs.bazel.build/versions/master/install-os-x.html:

### What operating system are you running Bazel on?
MacOS

**Comment by helenalt** [comment]
Confirmed that Homebrew on ios works well, so this issue is obsolete

**Comment by ittaiz** [comment]
Why is it no longer the recommended way?
