### ISSUE TITLE
C++ shared libraries under `.runfiles` not linked with RPATH when built as an external, @repo//:target; affects Python libraries

### ISSUE THREAD

**Issue by EricCousineau-TRI** [bazelbuild/bazel#4594]
### Description of the problem / feature request:

I ran into RobotLocomotion/drake#7972, and dug into it. After stripping out our project-specific stuff and looking a bit deeper, it looks like Bazel uses different RPATH logic for linking a shared library depending on whether the (a) artifacts were built as a local target or an external target and (b) if the artifact is under `.runfiles` or not.

### Feature requests: what underlying problem are you trying to solve with this feature?

I would like to allow consumption of Python targets which rely on a C++ shared library from downstream Bazel projects.
RobotLocomotion/drake#7972 shows a binary workflow; however, I'd like to declare `py_library` and `py_binary` targets which depend on these upstream Python / C++ libraries.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```bash
cat > WORKSPACE <<EOF
workspace(name = "example")
EOF

cat > BUILD.bazel <<EOF
cc_binary(
    name = "libexample_lib.so",
    srcs = [
        "example_shared.cc",
        "example_shared.h",
    ],
    linkshared = 1,
    linkstatic = 1,
)

cc_test(
    name = "example_cc",
    srcs = [
        "example.cc",
        "example_shared.h",
        "libexample_lib.so",
    ],
)
EOF

cat > example_shared.h <<EOF
#pragma once

int func();
EOF

cat > example_shared.cc <<EOF
#include "example_shared.h"

int func() {
  return 10;
}
EOF

cat > example.cc <<EOF
#include "example_shared.h"

int main() {
  if (func() == 10)
    return 0;
  else
    return 1;
}
EOF

bazel run //:example_cc
ldd bazel-bin/example_cc | grep 'not found'  # Good.
ldd bazel-bin/example_cc.runfiles/example/example_cc | grep 'not found'  # Good.

bazel run @example//:example_cc
ldd bazel-bin/external/example/example_cc | grep 'not found'  # Good.
ldd bazel-bin/external/example/example_cc.runfiles/example/example_cc | grep 'not found'  # BAD
```

Old:
https://github.com/EricCousineau-TRI/repro/tree/444a315b9638c17e202a05a1c94f880dfa541ac9/bug/bazel_external_py_shared_lib

### What operating system are you running Bazel on?

Ubuntu 16.04.

### What's the output of `bazel info release`?

`release 0.10.0`

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

This is from the old example; the new reproduction code is self-contained:
```
git@github.com:EricCousineau-TRI/repro.git
444a315b9638c17e202a05a1c94f880dfa541ac9
444a315b9638c17e202a05a1c94f880dfa541ac9
```
Relative directory is `bug/bazel_external_py_shared_lib`.

###  Have you found anything relevant by searching the web?

I saw #3788, which seemed relevant, but upon looking further seemed like it was sensitive to 

### Any other information, logs, or outputs that you want to share?

Nope. See above example.

UPDATE: If this isn't something that's a high priority for the Bazel team as a whole, can I get a suggestion on where this can be fixed, and what tests to inspect / modify? This hurts our library as an upstream dependency providing Python.

**Comment by EricCousineau-TRI** [comment]
Simplified reproduction steps:

```
cat > WORKSPACE <<EOF
workspace(name = "example")
EOF

cat > BUILD.bazel <<EOF
cc_binary(
    name = "libexample_lib.so",
    srcs = [
        "example_shared.cc",
        "example_shared.h",
    ],
    linkshared = 1,
    linkstatic = 1,
)

cc_test(
    name = "example_cc",
    srcs = [
        "example.cc",
        "example_shared.h",
        "libexample_lib.so",
    ],
)
EOF

cat > example_shared.h <<EOF
#pragma once

int func();
EOF

cat > example_shared.cc <<EOF
#include "example_shared.h"

int func() {
  return 10;
}
EOF

cat > example.cc <<EOF
#include <cassert>

#include "example_shared.h"

int main() {
  if (func() == 10)
    return 0;
  else
    return 1;
}
EOF

bazel run @example//:example_cc
ldd bazel-bin/external/example/example_cc  # Should work
ldd bazel-bin/external/example/example_cc.runfiles/example/example_cc  # Should fail
```

**Comment by philwo** [comment]
Marcel, any idea?

**Comment by EricCousineau-TRI** [comment]
I've just tried using `cc_import` (on version `0.10.1`) to see if that does any new magic to fix this, but alas, it seems the issue is still the same. A patch for the above repro steps (from this [commit](https://github.com/EricCousineau-TRI/repro/commit/c6252ff)):
```diff
@@ -19,13 +19,18 @@ cc_binary(
     linkstatic = 1,
 )
 
+cc_import(
+    name = "example_lib",
+    hdrs = ["example_shared.h"],
+    shared_library = "libexample_lib.so",
+)
+
 cc_test(
     name = "example_cc",
     srcs = [
         "example.cc",
-        "example_shared.h",
-        "libexample_lib.so",
     ],
+    deps = [":example_lib"],
 )
 EOF
```

@mhlopko Can I ask if you have any advice on how this could possibly be fixed? If you can point me to a place where I can tinker with patching the code, I'm willing to see if I can contribute a patch.

If not, is there a decent workaround that you can think of?
At present, one workaround is the following ugliness:
https://github.com/EricCousineau-TRI/drake/blob/5ad7335d62705b7c1c557b414b099f466fac7088/bindings/_bazel_workaround_4594.py#L12-L47

An alternative that @jwnimmer-tri suggested is to use a secondary process to produce solib artifacts (we have an `//:install` rule), and then consume those, which is much less hacky than the above workaround, but quite a bit of build overhead.

**Comment by EricCousineau-TRI** [comment]
As an update for external Python libraries in Bazel, @jwnimmer-tri found a workaround, which is shown in the following PR: https://github.com/RobotLocomotion/drake/pull/8240

The workaround is to import the library from an alternative path as means to import the correctly-linked shared library dependencies; then you can import your original library, which will the use the properly loaded libraries.

The incorrectly-linked libraries are under `{runfiles}/{workspace}/{target_path}` (I assume due to how the relative RPATHs are formed);
the correctly-linked libraries are under `{runfiles}/external/{workspace}/{target_path}`.
This does import a duplicate, but there shouldn't be too many averse side effects.

Example, making `@drake//bindings/pydrake` work in downstream projects:
```
import external.drake.bindings.pydrake
import pydrake  # Now works

# Print module names, and paths.
import sys
print("\n".join(sorted([k for k in sys.modules.keys() if "pydrake" in k])))
print(sys.modules["pydrake"].__file__)
print(sys.modules["external.drake.bindings.pydrake"].__file__)
```
Output of the above script: https://gist.github.com/EricCousineau-TRI/0e34cb046450bb4fc8a0a2403b1733aa

**Comment by brandjon** [comment]
It sounds like this issue doesn't directly involve Python? CPython extension support is something we'd like eventually, but we're prioritizing other Python issues right now. Removing the Python label as this seems to fall under the cpp rules team.

**Comment by EricCousineau-TRI** [comment]
Just checked and confirmed that the above repro steps still fail in Bazel:

```
Build label: 0.19.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Nov 19 16:25:09 2018 (1542644709)
Build timestamp: 1542644709
Build timestamp as int: 1542644709
```

**Comment by EricCousineau-TRI** [comment]
Any chance this may receive some love in the future? Still hurting on this have and having to find workarounds :(

**Comment by EricCousineau-TRI** [comment]
FWIW, looks like this is no longer an issue for the project we are using:
https://github.com/RobotLocomotion/drake/pull/21748
