### ISSUE TITLE
Doc error for transitive proto_libraries in https://blog.bazel.build/2017/02/27/protocol-buffers.html

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/bazel#4599]
The article https://blog.bazel.build/2017/02/27/protocol-buffers.html says "Notice how the proto_library provide structure for both Java and C++ code generators, and how there's only one java_proto_library even though there multiple .proto files." but this action does not work.

If you then depend on e.g. a java_proto_library in a java_library, the build fails with
```
Building src/java/libframework.jar (21 source files) and running annotation processors (ComponentProcessor) failed (Exit 1)
src/java/com/cloudrobotics/framework/configuration/ConfigurationModule.java:27: error: [strict] Using type com.example.configuration.Config from an indirect dependency (TOOL_INFO: "//src/proto:config_proto wrapped in java_proto_library"). See command below **
      GeneratedMessage.GeneratedExtension<Config, M> extension, Path filepath) {
```

The only way I found to fix this is to have a java_proto_library for each proto and to include all of the java_proto_libraries in the deps of the proto_library.

```
bazel version
Build label: 0.10.0
Build target: bazel-out/k8-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Nov 9 04:43:10 +50056 (1517474666590)
```

**Comment by cgrushko** [comment]
@ensonic what's the Java file?

**Comment by ensonic** [comment]
This is the core part (line 27 is the 2nd line below).
```
  public static <M extends Message> ConfigurationModule createForExtension(
      GeneratedMessage.GeneratedExtension<Config, M> extension, Path filepath) {
    return new ConfigurationModule(new ConfigurationServiceForProto<>(extension, filepath));
  }
```
What I wonder is that usually in bazel you add direct dependencies for what you use. So for that doc I wonder why it would be different for a `<lang>_proto_library`.

**Comment by cgrushko** [comment]
Seems like a strict java deps violation?
The statement in the blog refers to the fact that you don't have to define JPLs all over the place to be able to build a top-level JPL. It doesn't say that if you use protos deep in the proto tree, you don't have to depend on them directly.

**Comment by ensonic** [comment]
Feel free to close it then. I understood the statement differently.
