### ISSUE TITLE
Building //external:whatever prints that it fails

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#460]
...even though it succeeds because Bazel is looking for actual output of bazel-bin/external/whatever.  See https://groups.google.com/d/msgid/bazel-discuss/6dc3aa3d-6686-4d0b-803a-418eb62613c6%40googlegroups.com.

**Comment by lberki** [comment]
I'm closing this as a dupe. #1290 is already fixed at internal HEAD, so all we need is a push to make it work in the GitHub tree, too.
