### ISSUE TITLE
--invocation_policy gets set to inappropriate values on Windows

### ISSUE THREAD

**Issue by sgreenstein** [bazelbuild/bazel#4601]
### Description of the problem / feature request:

Passing `--invocation_policy` on Windows results in the flag being set to random values

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm trying to pass `--invocation_policy` as in this question: https://stackoverflow.com/questions/48652798/how-do-i-unset-flags-set-in-bazelrc/

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In a Windows command prompt in any directory, run `bazel --invocation_policy=`. It will print things like `Malformed value of --invocation_policy: ystem32\cmd.exe`

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

0.10.0

###  Have you found anything relevant by searching the web?

No

**Comment by meteorcloudy** [comment]
I tested on Windows with Bazel 4.2.2, this doesn't seem to be a problem anymore.
```
# bazel --invocation_policy
[FATAL 13:46:06.715 src/main/cpp/blaze.cc:1293] Startup option '--invocation_policy' expects a value.
Usage: '--invocation_policy=somevalue' or '--invocation_policy somevalue'.
  For more info, run 'bazel help startup_options'.
```

**Comment by yslking** [comment]
C++ 格式化字符串
