### ISSUE TITLE
fail to build gerrit version 2.14.5 with bazel

### ISSUE THREAD

**Issue by lilyandchih** [bazelbuild/bazel#4606]
Hi, I clone gerrit code and checked with version 2.14.5, When i build gerrit with bazel some error occurred. can you help me? here is the error log:
./bazel build devtools/gerrit:gerrit
ERROR: /Users/.../devtools/gerrit/lib/js/BUILD:25:1: no such package '@iron-form-element-behavior//': failed /usr/bin/python /Users/.../devtools/gerrit/tools/js/download_bower.py -b /usr/bin/python /Users/......./devtools/gerrit/tools/js/run_npm_binary.py /private/var/tmp/_bazel_chen/3f86623f4ae9da13ec21323716812429/external/bower/bower@1.8.0.npm_binary.tgz -n iron-form-element-behavior -p iron-form-element-behavior -v 1.0.6 -s 8d9e6530edc1b99bec1a5c34853911fba3701220 -o iron-form-element-behavior__download_bower.zip: env: node: No such file or directory
Traceback (most recent call last):
  File "/Users/........./devtools/gerrit/tools/js/run_npm_binary.py", line 91, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/......../devtools/gerrit/tools/js/run_npm_binary.py", line 87, in main
    subprocess.check_call([bin] + args[1:])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/private/var/tmp/_bazel_chen/3f86623f4ae9da13ec21323716812429/external/bower/bower@1.8.0-55dbebef0ad9155382d9e9d3e497c1372345b44a/package/bin/bower', '-l=error', '-j', 'info', 'iron-form-element-behavior#1.0.6']' returned non-zero exit status 127
Traceback (most recent call last):
  File "/Users/.........../devtools/gerrit/tools/js/download_bower.py", line 128, in <module>
    sys.exit(main(sys.argv[1:]))
  File ........"/Users/........./devtools/gerrit/tools/js/download_bower.py", line 99, in main
    info = bower_info(opts.b, opts.n, opts.p, opts.v)
  File "/Users/......../devtools/gerrit/tools/js/download_bower.py", line 49, in bower_info
    raise OSError('Command failed: %s' % ' '.join(cmd))
OSError: Command failed: /usr/bin/python /Users/./devtools/gerrit/tools/js/run_npm_binary.py /private/var/tmp/_bazel_chen/3f86623f4ae9da13ec21323716812429/external/bower/bower@1.8.0.npm_binary.tgz -l=error -j info iron-form-element-behavior#1.0.6
 and referenced by '//devtools/gerrit/lib/js:iron-form-element-behavior'.

**Comment by davido** [comment]
Just guessing: Pre-Requisites are not there: nodejs. Follow these steps: 

https://github.com/GerritCodeReview/gerrit/blob/master/Documentation/dev-bazel.txt#L10

**Comment by philwo** [comment]
> `env: node: No such file or directory`

Yes, nodejs is missing on your system. It looks like you're on a Mac. If you have Homebrew installed, you can install nodejs like this: `brew install node`.
