### ISSUE TITLE
System Hang post running "bash apollo.sh build" or ./apollo.sh build_no_perception dbg

### ISSUE THREAD

**Issue by jarviscrypter** [bazelbuild/bazel#4607]
### Description of the problem / feature request:

> Hello, i have executed all the required commands for launching the Dreamview and i am in last step. My PC runs on Nvidia GPU and on ubuntu the drivers are setup. Then also, when  i try to run the commands in' title' the system loads few packages and later hangs up. I have healthy HDD, RAM, GPU.

### Feature requests: what underlying problem are you trying to solve with this feature?

> Smooth system run.

### What operating system are you running Bazel on?
 

>Ubuntu

###  Have you found anything relevant by searching the web?

> No

The image in the below link is the point at which system hangs, is it normal and does it take hours of time or its a problem that needs to be addressed?
[https://drive.google.com/open?id=1MELuSFFS5qua_cEsseWr91trgr-IABvH](url)

**Comment by philwo** [comment]
Hi @jarviscrypter - I'm sorry that Bazel crashes your system! This surely should not happen.

I wonder if your computer is running out of RAM? Bazel can use a lot of RAM and if it then runs many compilers in parallel, it can be a bit much. Can you share some details about your computer system, like which CPU and how much RAM do you have?

You can try to create a file called ".bazelrc" in your home directory with the contents `build --jobs=1`. This would limit Bazel to only run one compiler in parallel. You could e.g. create it like this:

`echo 'build --jobs=1' > ~/.bazelrc`

**Comment by jarviscrypter** [comment]
Dear Sir,

Sorry about the late response.
yes AM utility might be an issue.
My system configuration is
i5-6600
8gb RAM
gtx 1050 ti GPU
1tb HDD


I shall surely try with the suggested steps and let you know the further
results

Thank You
Rajath C S

**Comment by jarviscrypter** [comment]
Dear @philwo ,

I'd like to say that Apollo build is successful on my laptop where as it hangs on my desktop, on a comparitive basis my Desktop is at higher configurations than laptop. The below are my laptop configuration details, previous comment details are my desktop details.

amd a10 processor
1gb dedicated graphics radeon
processor and gpu are crossfired
8gb RAM

**Comment by philwo** [comment]
@jarviscrypter Sorry for the late response and that I can't be of much help!

I think this might be an issue with your hardware. Your system surely looks strong enough to run the build successfully. Maybe something is overheating?
