### ISSUE TITLE
test stdout is sometimes missing

### ISSUE THREAD

**Issue by ola-rozenfeld** [bazelbuild/bazel#4608]
There is a race condition in test-setup.sh which will cause the test output to occasionally be (partially or fully) missing, from either the test log or from the test.xml, or both.

Sample Tensorflow tests revealed the stdout missing from xml in as much as 40% of the cases, although usual incidence for small tests is ~1%. Internal issue: b/65977241.

**Comment by ulfjack** [comment]
After a lot of offline discussion, we think that the principled fix is to split test execution and test.xml generation (only to be executed if the test did not generate a test.xml file). I have a patch for that, but unfortunately, it's causing problems elsewhere. I have a patch for that, except it's causing problems in yet another place.

As a short-term solution, we're going to put in a Linux-specific fix, which is the most critical case right now.

**Comment by katre** [comment]
Is the remaining work on this a release blocker for 0.11.0?

**Comment by ola-rozenfeld** [comment]
No, as long as https://github.com/bazelbuild/bazel/commit/9fe02aa9c7081f5cb6b48a949a054f64f693ae22 is in 0.11.0, we're good. the remaining work will take a few more weeks.

**Comment by katre** [comment]
That's fine, I am removing the release blocker label.

**Comment by ulfjack** [comment]
Assigning to myself for the long-term fix.

**Comment by Reflexe** [comment]
I looked into the issue a bit with `strace`. Looked like `bash` is not reliable at catching `SIGINT` at all - it just keeps blocking it on some occasions with `rt_sigprocmask(2)`. 

I'm not very familiar with Bazel internals but is there a good reason for using bash for this task?  (Sometimes the short way is actually the long way).

**Comment by agoulti** [comment]
Thanks for looking into it!

The "short way" implementation is in the works.
The long-term fix that Ulf is working on is exactly about removing this functionality from the Bash script and moving it into Bazel itself.

Unfortunately, some non-trivial refactoring is involved so it's not coming as fast as we'd like - that's the main reason for the stop-gap fix in 9fe02aa

**Comment by ulfjack** [comment]
Change is here: https://bazel-review.googlesource.com/c/bazel/+/66174

With the recent-ish refactorings (before my ~one month of leave), it's possible that this might just work now. I'm running the tests right now.

**Comment by ulfjack** [comment]
Progress: a6255612e4892729d3758775c76085b26b9bc584 removes one of the metadata caches, which should allow the split to move forward now.

**Comment by dapirian** [comment]
I can see this bug simply by doing `bazel test //some/target --test_output=all --nocache_test_results` a bunch of times in a row. The standard output in about 25% of the cases is randomly some section from the end of the actual stdout. This bug makes `bazel test` unusable for development and should be extremely high priority.

**Comment by bergsieker** [comment]
@ulfjack can you confirm if you're still working on this, or can you find a new owner? Thanks!

**Comment by buchgr** [comment]
Do you have a CL number of the change that needs to be rolled forward? Will you take care of this or should I?

**Comment by ulfjack** [comment]
cl/207084179 needs to be rolled back (i.e., the original change is cl/205629237 and needs to be rolled forward). I already have a rollback of the rollback, but we were unable to determine how the change could have caused the problems that led to the rollback. @meisterT was pretty confident that the original change caused a problem. We later found another change that caused a similar problem, but it's unclear if that was the same problem.

**Comment by ulfjack** [comment]
There was an intermediate change by Janak which may have resolved the underlying problem - cl/210731120.

**Comment by ulfjack** [comment]
It's unlikely that I'll have any time this week to work on it.

**Comment by ulfjack** [comment]
So, the rollback of the rollback is in, guarded with a flag: https://github.com/bazelbuild/bazel/commit/f2b260cc416fba01a8bd3309d352eb8b823ff708

Unfortunately, @meisterT was completely correct that the change was broken. Fortunately, we managed to track it down and I just submitted a fix: https://github.com/bazelbuild/bazel/commit/9de2ea51187bf11a06cc7089b5c6fddcfda555f6

(See the description for a long explanation of what was going wrong.)

If that second change sticks, then we can move forward with flipping the flag introduced in the first change and backing out the temporary code. That should happen some time next week. Assuming that that also sticks, i.e., we didn't overlook something else, we're done with the second-level Yak shaving.

That means we can go up one level and flip --experimental_split_xml_generation to true. If next week looks good, then we can tackle that the week after. If that also sticks, then we can clean up the temporary code for that, and finally close this bug.

**Comment by ulfjack** [comment]
Well, it took me a bit longer but I have a patch to flip the flag, as well as a patch to back out the temporary code. They should get submitted this week.

**Comment by ulfjack** [comment]
To clarify: I already flipped the flag for all Google builds and we have not observed any problems. My patch is to flip the flag in Bazel as well, and then to back out the temporary code.

**Comment by ulfjack** [comment]
Temporary code removed in b7ae7b06a6a602f2eaf3ab386e7afbffd120fae1. Next up is to flip the --experimental_split_xml_generation flag.

**Comment by ulfjack** [comment]
This got delayed due to me being on vacation for all of December. Unfortunately, I just found yet another issue. As far as I can tell, our code to replace invalid xml characters doesn't actually work right now (at least with some versions of perl). On the plus side, I can now confirm that the upcoming replacement is equivalent to what we're doing right now.

**Comment by ulfjack** [comment]
Make that two issues - there's still a bug in the code for which I have a fix, and the current XML character replacement function doesn't work, which I want to replace anyway.

Ok, make that three issues - the test doesn't actually test whether XML character replacement works because it's broken.

**Comment by ulfjack** [comment]
The good news is that I fixed most of the issues mentioned above, at least those that are critical for rolling this out.

However, I found yet another issue with signal handling, which apparently isn't working correctly.

**Comment by ulfjack** [comment]
It looks like there may still be an issue with remote execution.

**Comment by ulfjack** [comment]
It's in! It's amazing! (But don't celebrate yet, it could still be rolled back...)
