### ISSUE TITLE
Breaking with XCode 9.0

### ISSUE THREAD

**Issue by XperielIndigo** [bazelbuild/bazel#461]
Hi everyone,

XCode has just updated on my system and now my bazel iOS apps are broken.

Issues when running on Simulator I get the following error:
```
INFO: Running command line: bazel-bin/src/main/objc/com/xperiel/sandbox/Xperiel_runner.sh

2015-09-17 09:26:18.254 iossim[3197:45102] +[SimDeviceType supportedDeviceTypesByName]: unrecognized selector sent to class 0x105dd8430

2015-09-17 09:26:18.255 iossim[3197:45102] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[SimDeviceType supportedDeviceTypesByName]: unrecognized selector sent to class 0x105dd8430'

*** First throw call stack:

(

0   CoreFoundation                      0x00007fff9034903c __exceptionPreprocess + 172

1   libobjc.A.dylib                     0x00007fff97e3476e objc_exception_throw + 43

2   CoreFoundation                      0x00007fff9034bfad +[NSObject(NSObject) doesNotRecognizeSelector:] + 205

3   CoreFoundation                      0x00007fff90291e24 ___forwarding___ + 1028

4   CoreFoundation                      0x00007fff90291998 _CF_forwarding_prep_0 + 120

5   iossim                              0x0000000100003821 main + 1809

6   iossim                              0x0000000100001344 start + 52

)

libc++abi.dylib: terminating with uncaught exception of type NSException

/private/var/tmp/_bazel_przemeklach/2f4d7cf61411af5af1cd4207b2fa3553/Master/bazel-out/local_darwin-fastbuild/bin/src/main/objc/com/xperiel/sandbox/Xperiel_runner.sh: line 44:  3197 Abort trap: 6           third_party/iossim/iossim -d "${SIM_DEVICE}" -s "${SDK_VERSION}" "${args[@]}" "${APP_DIR}/Payload/Xperiel.app" "$@"
```
Issues when generating XCode:

1. Enable bitcode is defaulting to true, all third-party frameworks that were built before 9.0 (i.e. almost all) now fail as they don't have bitcode enabled.
2. Reference iPhoneOS9.0.sdk/Developer/Library/Frameworks, this is now at iPhoneOS9.0.sdk/System/Library/Frameworks, though iPhoneOS.sdk is still with iPhoneOS.sdk/Developer/Library/Frameworks

**Comment by XperielIndigo** [comment]
I'm getting this error as well when performing a bazel build.

```

2015-09-17 11:47:10.169 defaults[64286:10271498] 
The domain/default pair of (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Info.plist, BuildMachineOSBuild) does not exist
```

**Comment by damienmg** [comment]
Peter: can you tell a bit more about your plan for supporting the breaking change from X-Code in the future?

**Comment by c-parsons** [comment]
This bug is pretty stale, and we have new versions of xcode supported nowadays.
If this resurfaces with new xcode versions, feel free to file new issues.

Our policy is no more specific than we address new GA versions of Xcode ASAP (we don't have a specific timed SLO)
Beta xcode versions we don't spend too much time addressing, except in preparation for them to GA.
