### ISSUE TITLE
--symlink_prefix doesn't affect the bazel-out symlink

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#4613]
Followup from https://github.com/bazelbuild/bazel/issues/4603#issuecomment-364269706

I've always been surprised that setting symlink_prefix to a directory, eg.
`--symlink_prefix=dist/`

does the lovely thing of creating `dist/bin`, `dist/genfiles`, etc. and printing such paths in the build output, however it still always puts a `bazel-out` symlink in the workspace root.

Is this intended behavior? It's annoying because users must configure editors to ignore both directories.

**Comment by aj-michael** [comment]
see also https://github.com/bazelbuild/bazel/issues/3796

**Comment by alexeagle** [comment]
Thanks @aj-michael looks like a dupe to me
