### ISSUE TITLE
java_library output depends on system timezone

### ISSUE THREAD

**Issue by aj-michael** [bazelbuild/bazel#4614]
Repro using bazel 0.10.0 from homebrew on MacOS 10.13.3. I don't think this is specific to mac, nor do I think it's new in 0.10.0.

```
$ cat BUILD
java_library(name = "lib")

$ date
Fri Feb  9 11:41:52 EST 2018

$ bazel build //:lib
INFO: Analysed target //:lib (0 packages loaded).
INFO: Found 1 target...
Target //:lib up-to-date:
  bazel-bin/liblib.jar
INFO: Elapsed time: 0.169s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action

$ md5 -q bazel-bin/liblib.jar
7b0dbb93e2fc9cd8c103c9fb108cfe60

$ sudo unlink /etc/localtime

$ sudo ln -s /var/db/timezone/zoneinfo/America/Chicago /etc/localtime

$ date
Fri Feb  9 10:44:20 CST 2018

$ bazel clean
INFO: Starting clean.

$ bazel build //:lib
INFO: Analysed target //:lib (9 packages loaded).
INFO: Found 1 target...
INFO: From Executing genrule @bazel_tools//tools/jdk:gen_platformclasspath [for host]:
Note: external/bazel_tools/tools/jdk/DumpPlatformClassPath.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Target //:lib up-to-date:
  bazel-bin/liblib.jar
INFO: Elapsed time: 4.537s, Critical Path: 4.11s
INFO: Build completed successfully, 5 total actions

$ md5 -q bazel-bin/liblib.jar
6b2fb913b4d33bbd0dc80c3432fc6355
```

**Comment by aj-michael** [comment]
the difference comes from the timestamps of the zip file entries in the jar

**Comment by cushon** [comment]
It normalizes using a fixed timestamp

https://github.com/bazelbuild/bazel/blob/f13a7ef7c9eb7ce400ffbbaca0bdc7945172a332/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/jarhelper/JarHelper.java#L41

and [`ZipEntry#setTime`](https://docs.oracle.com/javase/8/docs/api/java/util/zip/ZipEntry.html#setTime-long-) uses the default time zone to convert to a DOS timestamp when writing out the archive.

I have a change in progress (cl/185015644) that will help with this by considering the default time zone when creating the normalized timestamp.

[JDK-8075526](https://bugs.openjdk.java.net/browse/JDK-8075526) would also be helpful here.
