### ISSUE TITLE
Better error message for XCode locator problems

### ISSUE THREAD

**Issue by davidstanke** [bazelbuild/bazel#4615]
### Description of the problem / feature request:
Various situations on macOS can cause problems when Bazel attempts to interoperate with XCode. See: #4603, and similar behavior if the XCode license has not been accepted. The user gets an error that's not often helpful: `Xcode version must be specified to use an Apple CROSSTOOL`. Please replace this with a message that will help users take action. (Strawperson: `Unable to run xcode-locator-bin -- another process may be interfering with execution`)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
This is actually really hard to reproduce, but some users have reported that it happens on macOS High Sierra, if both Santa and VSCode are running when Bazel is called.

### Versions
Experienced on Bazel 0.10 on macOS High Sierra. (Other versions possibly affected)

**Comment by c-parsons** [comment]
The problem is that xcode-locator-bin has no meaning outside of bazel. I posit that your "strawperson" proposal does not help understand the issue, nor provide any actionable information to the user at all.

I'm open to other proposals -- this is easy enough to change, I just don't have any good ideas what information we can provide the user, given that we don't even really have any idea how to reliably reproduce this issue, nor what process may be establishing an arbitrary lock on xcode-locator-bin right after its creation.

**Comment by buchgr** [comment]
I find that this problem happens every single time after installing a macOS update and when there's a xcode related update outstanding. The issue goes away after installing the update, reboot,

```
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
sudo xcodebuild -license
bazel clean --expunge
```

The issue happens to me every two weeks or so :\.

**Comment by jmmv** [comment]
One extra case to handle: when we get `/Library/Developer/CommandLineTools` as a path, we should probably tell the user that things won't work and that they must use `xcode-select` to point to an Xcode directory.

**Comment by jmmv** [comment]
We also must ensure that all `xcode-locator` output ends up in the Bazel log unconditionally so that we have something to base our debugging on.

**Comment by c-parsons** [comment]
Ping for visibility, with priority (I will likely take this on myself)

Received some recent feedback that this error message ("run `xcode-select -p`") is horribly unhelpful in terms of path forward, as that doesn't actually resolve any issues.
Some ideas for extra steps, of "less precise" things to try:

"Manually run xcode and accept any terms and conditions"
"Run `xcode-select -s <Xcode_installation_path>` if the path does not match"

**Comment by jmmv** [comment]
There are so many things that can go wrong in Xcode selection, and given the little visibility we have when running `xcode-locator-bin`, I'm afraid an error message isn't gonna cut it.

I think we should have an FAQ entry or something with detailed information on this, with multiple troubleshooting steps, and then make the error message point at that page. (I even think we do have some documentation on that topic already, written recently by @susinmotion.)
