### ISSUE TITLE
sh_binary cannot depend on java_import

### ISSUE THREAD

**Issue by vmax** [bazelbuild/bazel#4620]
### Description of the problem / feature request:

```
ERROR: devtools/formatter/BUILD:5:12: in deps attribute of sh_binary rule //devtools/formatter:formatter: java_import rule '@google_java_format//:formatter_binary' is misplaced here (expected sh_library)
ERROR: Analysis of target '//devtools/formatter:formatter' failed; build aborted: Analysis of target '//devtools/formatter:formatter' failed; build aborted
INFO: Elapsed time: 0.174s
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
```

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm trying to write shell script, which would utilize run a jar which is downloaded and exported by `new_http_archive` and `java_import` rules, specifically [google-java-format](https://github.com/google/google-java-format)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`WORKSPACE`:

```
new_http_archive(
    name = "google_java_format",
    urls = ["https://github.com/google/google-java-format/releases/download/google-java-format-1.5/google-java-format-1.5-all-deps.jar"],
    build_file = "BUILD.google_java_format"
)
```

`BUILD.google_java_format`:

```
package(default_visibility = ["//visibility:public"])

java_import(
    name = "formatter_binary",
    jars = ["google-java-format-1.5-all-deps.jar"],
)
```

`devtools/formatter/BUILD`:
```
sh_binary(
    name = "formatter",
    srcs = ["formatter.sh"],
    deps = ["@google_java_format//:formatter_binary"]
)
```

`devtools/formatter/formatter.sh`

```
#!/usr/bin/env bash
# Run java -jar google-java-format-1.5-all-deps.jar here
```

### What operating system are you running Bazel on?

`macOS 10.13.3`

### What's the output of `bazel info release`?

```
bazel version
Build label: 0.10.0-2018-02-05 (@565672c)
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 27 18:00:01 +50068 (1517857552801)
Build timestamp: 1517857552801
Build timestamp as int: 1517857552801
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Built from `bazel v0.10` with inclusion of some patches to android rules (shouldn't affect other rules)

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Not really helpful, but I created repo with `git init` starting from [bazel dist v0.10](https://github.com/bazelbuild/bazel/releases/download/0.10.0/bazel-0.10.0-dist.zip)

**Comment by cushon** [comment]
`sh_binary.deps` is for `sh_library` dependencies. You can use `sh_binary.data` to pull in other files (like `.jar` files). However using `java_binary` here is probably a better option:

```
java_binary(
    name = "formatter",
    main_class = "com.google.googlejavaformat.java.Main",
    runtime_deps = ["@google_java_format//:formatter_binary"]
)
```

**Comment by philwo** [comment]
Thank you for answering this, @cushon!
