### ISSUE TITLE
support reading multiple rc files

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/bazel#4629]
Currently, the user-specific rc-file and the rc-file committed into the project are conflicting, in the sense that only one rc-file is used. Instead it would be desirable, that the effects of both are accumulated (as described in https://bazel.build/designs/2016/06/21/environment.html), see, e.g., the discussion in #3516.

**Comment by cvcal** [comment]
I agree, but this is part of the suggested fix in #4502, can we make that the canonical one? I can change the title to be more inclusive, but it already has the discussion on it, so I'd rather keep it active.

**Comment by aehlig** [comment]
> I agree, but this is part of the suggested fix in #4502, can we make that the canonical one?
> I can change the title to be more inclusive, but it already has the discussion on it, so I'd rather keep it active.

Sure. Feel free to change the title of #4502 and close this issue as a duplicate.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado
