### ISSUE TITLE
clarify the docs for proto_lang_toolchain

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/bazel#4631]
It would be nice to improe the docs for
https://docs.bazel.build/versions/master/be/protocol-buffer.html#proto_lang_toolchain
and clarify that this won't magically give a new xyz_proto_library(), but only lets you configure the existing ones. 

I wanted to run a proto compiler plugin and this can simply be done with a macro that uses 'proto_gen' from  com_google_protobuf//:protobuf.bzl. This could also be a useful addition to the docs.

**Comment by communikit** [comment]
https://docs.bazel.build/versions/master/be/protocol-buffer.html#proto_lang_toolchain is currently marked as Deprecated and directs users to refer to https://github.com/bazelbuild/rules_proto instead.

Closing; feel free to reopen if there is still a strong preference for updating that block of documentation.
