### ISSUE TITLE
Allow setting the target platform directly on targets

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#4638]
It would be useful to directly specify the target platform on some types of targets (typically, "top level" or binary targets). This will enable us to support builds for multiple target platforms in the same build, as well as hard-coding some types of configuration information.

Example syntax:
```
cc_binary(name = "my_binary",
  srcs = [...],
  deps = [...],
  platforms = [ "//platforms:linux", "//platforms:osx"])
```

**Comment by katre** [comment]
Note that this is being added for tracking purposes, this feature will not be worked on for some time.

**Comment by ztl8702** [comment]
+1 for this: I have a use case where I need to compile both x64 and x86 binaries, pack them into a single file, then perform subsequent build steps on the file.

**Comment by katre** [comment]
Closing this as a dupe of #6519 (this is older, that has more activity.)
