### ISSUE TITLE
CROSSTOOL file parse error on msys_x64_mingw_content

### ISSUE THREAD

**Issue by jnb** [bazelbuild/bazel#4645]
### Description of the problem / feature request:

I'm observing a parse error on a `CROSSTOOL` file when using Bazel 0.10.1 to build [envoy](https://www.envoyproxy.io/).

I believe that the build succeeds when using Bazel 0.9.0

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

    $ git clone -b v1.5.0 --single-branch --depth 1 https://github.com/envoyproxy/envoy.git
    $ cd envoy
    $ bazel fetch //source/...
    $ bazel build //source/exe:envoy-static
    $ ERROR: java.io.IOException: Could not read the crosstool configuration file 'CROSSTOOL file /work/.cache/bazel/_bazel_root/[...]/external/local_config_cc/CROSSTOOL', because of a parser error (251:1: Expected identifier. Found '%')
    INFO: Elapsed time: 0.497s
    FAILED: Build did NOT complete successfully (0 packages loaded)

When I examine the referenced `CROSSTOOL` file, I see the following:

    toolchain {
      toolchain_identifier: "msys_x64_mingw"
      abi_version: "local"
      abi_libc_version: "local"
      builtin_sysroot: ""
      compiler: "mingw-gcc"
      host_system_name: "local"
      needsPic: false
      target_libc: "mingw"
      target_cpu: "x64_windows"
      target_system_name: "local"

    %{msys_x64_mingw_content}

      linking_mode_flags { mode: DYNAMIC }
    }

Removing the `%{msys_x64_mingw_content}` line allows the build to successfully complete.

### What operating system are you running Bazel on?

Ubuntu 14.04.3 LTS

### What's the output of `bazel info release`?

    $ bazel info release
    release 0.10.1

### Any other information, logs, or outputs that you want to share?

Could this problem be related to [this commit](https://github.com/bazelbuild/bazel/commit/e9f4090c67a89247166b7c9607394b350a7c4ef6#diff-e07426bee11837e49252adc9c0a21190R163)?

**Comment by aehlig** [comment]
Apparently the issue is in the cited upstream project, not in bazel.
