### ISSUE TITLE
Mac: Warning about /dev/null having been modified

### ISSUE THREAD

**Issue by mmorearty** [bazelbuild/bazel#4647]
### Description of the problem / feature request:

cc @ola-rozenfeld 

I'm using 0.10.1 plus cherry-picks of fixes for #3360 — I cherry-picked 8896d2e211c57453359566c4520615c1c1f75b66 and 9e344ec089f3f46ac6d4cdf2638b671242f87631 onto the top of 0.10.1.

When compiling a large project on Mac (sorry, I don't have a small repro case for you), I saw this warning about ten times:

    WARNING: /dev/null was modified during execution

If you do `ls -l /dev/null` on a Mac, you'll see that its timestamp is continually changing.

I wouldn't be surprised if this is related to 3e28868f63692b3a57a3d22a2dabc18395f24ceb, which added this line:

    static final ActionInput EMPTY_FILE = new EmptyActionInput("/dev/null");

### Feature requests: what underlying problem are you trying to solve with this feature?

Just fixing a spurious warning.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Sorry, I don't have a small repro case. I compiled a large project on Mac.

If you do `ls -l /dev/null` on any Mac, you'll see that its timestamp is continually changing. That does not seem to be the case on the one Linux system that I tried.

### What operating system are you running Bazel on?

macOS 10.13.3

### What's the output of `bazel info release`?

As described above, I am running 0.10.1 plus several cherry-picks.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/Asana/bazel.git
1c7e5815c8a5af38f7c8bf3b764cfa51158f7247
a9c02b030a1ad6cb7fd824d92d5fbb1ea1563fad

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

No.

**Comment by ola-rozenfeld** [comment]
cc @ulfjack

**Comment by ulfjack** [comment]
This is probably as simple as adding "if (input instanceof VirtualActionInput) continue;" to RemoteSpawnCache.java, around line 195.

**Comment by jgavris** [comment]
I'm seeing this again on Bazel 0.13.1 (macOS) with the experimental remote spawn cache

**Comment by jgavris** [comment]
It just looks like this patch was lost in later refactoring https://github.com/bazelbuild/bazel/commit/d8ac06a4cfba7fe820cf61c9b865cf670cc936a9

**Comment by jin** [comment]
The patch should be in 0.14.0, since 0.13.0 was cut before the patch d8ac06a and 0.14.0 was cut in early this month.

https://releases.bazel.build/0.14.0/rc5/index.html
