### ISSUE TITLE
remote/usability: upload to remote cache failed: PUT failed with status code 429

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#4664]
Google Cloud Storage allows to mutate the same object at most once per second. If that limit is exceeded it gives a "429 Too Many Requests" error. The error is mostly harmless for Google Cloud Storage, since it means that someone else uploaded this file already.

We should still not print dozens of these warnings and improve the user experience.

**Comment by RNabel** [comment]
@buchgr Does the caching code `PUT` new targets regardless of whether they already exist?

I'm hitting a similar error (`DEBUG: Upload to remote cache failed: Download failed with Status: 403 Forbidden`) on all but the builds working with a clean cache, and am investigating which limits could be hit.

**Comment by RNabel** [comment]
Thank you for the quick reply - `gsutil cp` illustrated the problem. The service account was lacking `storage.objects.delete`, but had read and write permissions. I'm happy to do a PR to add an additional `HEAD` request. Feel free to shoot me an email if you have initial pointers / thoughts on how this could be done.

**Comment by buchgr** [comment]
@RNabel sent you an e-mail the ucdavis.edu address (from your profile).

I don't know whether HEAD requests would help with e.g. performance in that I don't know how frequent this happens and for which artifacts. I ll open a separate issue.

**Comment by jgavris** [comment]
I've got a patch that solves this at least for the workflow I'm using https://github.com/bazelbuild/bazel/pull/6040.
