### ISSUE TITLE
Update BEP documentation to include available metrics

### ISSUE THREAD

**Issue by helenalt** [bazelbuild/bazel#4667]
Currently BEP documentation lives in the code comments and has limited information. It would be helpful for users to have a doc with more details, including what metrics are available.

**Comment by buchgr** [comment]
I did write documentation on it back in summer: https://docs.bazel.build/versions/master/build-event-protocol.html

**Comment by helenalt** [comment]
Thanks, Jakob. Looks like we missed this doc when looking for answers to a question about what types of metrics are published. Specific question was about whether we publish long running tests, long running builds, flaky tests/flags,  total runtime, totalk # of targets

**Comment by buchgr** [comment]
> publish long running tests

We don't distinguish between longrunning tests and tests - it's just a test. We publish detailed metrics/results for every test specified in the target patterns of `bazel test`.

> long running builds

Same as for tests.

> flaky tests/flags,

Yes, `FLAKY` is a test result just as `PASSED` and `FAILED` is.

> total runtime

Yes

> total # of targets

Yes

A good way to find out what's included in the BEP is to look at its proto definition [1]. The BEP contains essentially one protobuf message per "metric". You can also try it out yourself. Just run a test with Bazel and specify `--build_event_json_file=/path/to/build_event.json`. The `/path/to/build_event.json` will then contain the BEP as JSON which is well suited to be read through manually.

I think this can be closed. Please re-open if I misunderstood.

[1] https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto#L621
