### ISSUE TITLE
Bazel bash completion script takes hours to build on macOS via MacPorts

### ISSUE THREAD

**Issue by missa-prime** [bazelbuild/bazel#4670]
### Description of the problem / feature request:

Essentially, it takes hours to build the Bazel bash completion script on macOS when attempting to install Bazel via MacPorts. Building Bazel itself from source takes only several minutes, but somehow the bash completion script takes hours. There seems to be a hang that ends up resolving itself if you wait long enough. 

### Feature requests: what underlying problem are you trying to solve with this feature?

N/A

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Make sure JDK 8 or newer is installed
2. Ensure that ``/etc/gitconfig`` file exists and `user.name` and `user.email` fields are populated
3. Install MacPorts from [here](https://www.macports.org/install.php)
4. `sudo port install bazel` at a terminal prompt to install bazel

### What operating system are you running Bazel on?

macOS 10.12.6

### What's the output of `bazel info release`?

ERROR: The 'info' command is only supported from within a workspace.

Since I don't have a workspace handy, I'll provide the output of `bazel version`:
```
Build label: 0.9.0- (@non-git)
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Aug 1 19:08:22 +50104 (1518980756902)
Build timestamp: 1518980756902
Build timestamp as int: 1518980756902
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Bazel was built from source while being installed with MacPorts.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

Here are traces captured by @kencu:

[Sample.of.cfprefsd.txt](https://github.com/bazelbuild/bazel/files/1742739/Sample.of.cfprefsd.txt)
[Sample.of.distnoted.txt](https://github.com/bazelbuild/bazel/files/1742741/Sample.of.distnoted.txt)
[Sample.of.tclsh8.5.txt](https://github.com/bazelbuild/bazel/files/1742742/Sample.of.tclsh8.5.txt)
[Sample.of.lsd.txt](https://github.com/bazelbuild/bazel/files/1742743/Sample.of.lsd.txt)
[Sample.of.java4.txt](https://github.com/bazelbuild/bazel/files/1742744/Sample.of.java4.txt)
[Sample.of.java3.txt](https://github.com/bazelbuild/bazel/files/1742745/Sample.of.java3.txt)
[Sample.of.java2.txt](https://github.com/bazelbuild/bazel/files/1742746/Sample.of.java2.txt)
[Sample.of.java1.txt](https://github.com/bazelbuild/bazel/files/1742747/Sample.of.java1.txt)

**Comment by RootFunction** [comment]
Why is this tagged as a feature request rather than a bug?

**Comment by meisterT** [comment]
I assume this issue is stale.
