### ISSUE TITLE
C compiler option in Bazel CROSSTOOL file

### ISSUE THREAD

**Issue by AndersSundmanTobii** [bazelbuild/bazel#4672]
### Description of the problem / feature request:

`compiler_flag` can be used for both C and C++, `cxx_flag` for C++ code. But there doesn't seem to be any way to set C only options.

### Feature requests: what underlying problem are you trying to solve with this feature?

In particular I need to specify `-std=c99` as an option. The only way I know of doing this right now is by passing `copts = ["-std=c99"]` to every target. This is messy and error prone. Specifying `-std=c99` as a `compiler_flag` doesn't work since the option is not recognized (or desired) when building .cpp files that might be present in the same project.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Just create one .c and one .cpp file and compile it with a CROSSTOOL file

Bazel Build label: 0.10.1

###  Have you found anything relevant by searching the web?

https://stackoverflow.com/questions/48881886/c-compiler-option-in-bazel-crosstool-file

**Comment by lberki** [comment]
Looks like a simple thing to do, isn't it, @mhlopko ? It's one more feature to support, but it doesn't look like it would require a lot of care and feeding.

**Comment by lberki** [comment]
Moving this to P3 since there is a clear workaround; if you think it's more important, tell us how the lack of a resolution on this bug makes your life harder.

**Comment by hlopko** [comment]
With crosstool in starlark this is trivially doable by using 'c-compile' action name.

**Comment by juugcatm** [comment]
@hlopko It may be trivially doable but not at all trivially understandable. Can you provide a demonstration for specifying a copt project-wide for the native CPU using CROSSTOOL since it's so easy? I cannot synthesize such an example using existing documentation as the examples used are far too complex.
