### ISSUE TITLE
Windows-only py_test failure

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#4673]
This happens in Bazel CI with the nightly build: https://ci.bazel.build/blue/organizations/jenkins/Global%2Fbazel-tests/detail/bazel-tests/511/tests

Looks like the test is assuming the existence of the runfiles tree, which doesn't exist on windows.

**Comment by laszlocsomor** [comment]
Yeah, I already noticed yesterday, will fix it now.
The culprit is that the test assumes the presence of a runfiles tree, but on Windows we create a zip file (with the runfiles tree inside), so on Windows the test should look at the zip's contents.
