### ISSUE TITLE
Provide a fragment with paths to standard utilities like ln, grep, etc.

### ISSUE THREAD

**Issue by mrkkrp** [bazelbuild/bazel#4681]
### Description of the feature request

If we had a fragment, e.g. `ctx.fragments.binutils` that allowed us to get locations (full paths) to various utilities like `ln` and `grep`, we could perform some actions (such as symlink creation) without resorting to `ctx.actions.run_shell` or `use_default_shell_env = True` (for `ctx.actions.run`) and that in turn would allow for better hermeticity and control over build environment.

### What underlying problem are you trying to solve with this feature?

When we call e.g. `grep`, some users report errors because although it is on their `PATH`, it's not in standard location, and so we have to enable `use_default_shell_env` for our `run` actions or equivalently resort to `ctx.actions.run_shell` which brings too much in scope and hurts hermeticity.

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

No.

**Comment by jin** [comment]
@gregestren assigning this to configurability, please re-prioritize if it's not a P1. Thanks!

**Comment by gregestren** [comment]
@laszlocsomor  - would https://github.com/bazelbuild/bazel/issues/5265 cover this need?

**Comment by laszlocsomor** [comment]
@gregestren -- Even though they are closely related, I don't think so. #5265 provides the foundation, this issue asks for the "frontend".

**Comment by gregestren** [comment]
My hope is that if binutils can be expressed as a toolchain, this request can be fulfilled by the toolchain API instead of a new `ctx.fragments`, which we're trying to move away from.

**Comment by aiuto** [comment]
Closing. We don't want to add to fragments, and a shell toolchain would solve the problems.
