### ISSUE TITLE
Bazel Slow Tests on macOS

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#4684]
The below tests take longer than 5 minutes on macOS on Buildkite. The `bazel_determinism_test` takes longer than 15min, the `remote_execution_test` takes around 10min and all the other tests take between 5-7 minutes.
```
//src/test/shell/bazel:bazel_determinism_test
//src/test/shell/bazel:remote_execution_test
//src/test/shell/bazel:bazel_java_test
//src/test/shell/bazel:bazel_bootstrap_distfile_test
//src/test/shell/bazel:remote_execution_http_test
//src/test/shell/bazel:skylark_git_repository_test
//src/test/shell/bazel:external_path_test
//src/test/py/bazel:runfiles_test
//src/test/shell/bazel:git_repository_test
//src/test/shell/bazel/android:aar_integration_test
//src/test/shell/bazel/android:android_integration_test
```

cc: @ulfjack @philwo

**Comment by buchgr** [comment]
Please note that this are the tests times when the mac is under full load, with other tests running concurrently.

**Comment by leesandy** [comment]
int64 msgrcv = 15

**Comment by jin** [comment]
cc @ahumesky 

I didn't realize the {aar, android}_integration_tests were not running in presubmit on the Mac until today. @buchgr, it'll be great if you can cc the owners of disabled tests in the future - thanks!

**Comment by aiuto** [comment]
@philwo @jin   It might be worth looking at this to see if tests are still disabled and if the machines are still slow. Please close if appropriate.

**Comment by philwo** [comment]
I fixed this some time ago - macOS has the same test coverage now as other platforms. No more disabled slow tests. 🎉
