### ISSUE TITLE
bazel test --go_debug

### ISSUE THREAD

**Issue by nate-meta** [bazelbuild/bazel#4687]
### Description of the problem / feature request:
Please add a flag to allow attaching a go debugger similar to --java_debug

### Feature requests: what underlying problem are you trying to solve with this feature?
Making it possible to attach a debugger to go tests.

**Comment by jayconrod** [comment]
I'm not directly familiar with `--java_debug`, but from the help text, it sounds like this expands a few flags: `--test_arg=--wrapper_script_flag=--debug --test_output=streamed --test_strategy=exclusive --test_timeout=9999 --nocache_test_results`. The Java test runner must know what to do with `--wrapper_script_flag=--debug`. That would be pretty simple to setup in the Go test runner.

In general, I think Bazel should avoid introducing more language-specific functionality though. Maybe there could be a general `--debug` flag that expands to everything above and sets an environment variable `TEST_DEBUG=1`?

**Comment by jin** [comment]
Please open an issue on the rules_go repository for Go specific features.
