### ISSUE TITLE
https://bazel.io not responding while http://bazel.io works

### ISSUE THREAD

**Issue by VikramTiwari** [bazelbuild/bazel#47]
Maybe cause of some wrong ssl files configuration. But this is causing issue in resolution of links in [readme] (https://github.com/google/bazel/blob/master/README.md).

**Comment by damienmg** [comment]
Closing this one as we cannot do anything about https://bazel.io github pages does not support https on custom domain :(

**Comment by pgr0ss** [comment]
What about fronting with something like Cloudflare?

**Comment by kchodorow** [comment]
Hmm, looks possible: https://www.benburwell.com/posts/configuring-cloudflare-universal-ssl/

**Comment by damienmg** [comment]
We did the effort needed for 0.3, serving over SSL is now under way (we needs some approvals for SSL certificates from Google and then it should be there).

It can take another 2-3 weeks to get completed. Won't be ready for 0.3

**Comment by damienmg** [comment]
https://bazel.io is now live :)
