### ISSUE TITLE
Clarify what "Xcode version must be specified to use an Apple CROSSTOOL" means

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/bazel#4706]
I'm getting the aforementioned error regardless of what I do with Xcode, `xcode-select` or `bazel clean --expunge`, and the various StackOverflow questions about it don't explain what's actually wrong, which make it difficult for me to figure this out.

`bazel build //src/main/java/com/google/devtools/build/lib/skyframe/packages`

This issue is about changing the error message and/or providing a KB link that explains what's up.

**Comment by cgrushko** [comment]
Suggestion: add 

    To see some debug information, execute cat $(bazel info output_base)/external/local_config_xcode/BUILD

to the error message.

In my case, I get

```
# Error: Invoking xcode-locator failed, return code 256, stderr: java.io.IOException: Cannot run program "/private/var/tmp/_bazel_carmi/9bae3bfe96e0ac1bcb7f541f8c8aaf93/external/local_config_xcode/./xcode-locator-bin" (in directory "/private/var/tmp/_bazel_carmi/9bae3bfe96e0ac1bcb7f541f8c8aaf93/external/local_config_xcode"): error=1, Operation not permitted, stdout:
```

But, running `/private/var/tmp/_bazel_carmi/9bae3bfe96e0ac1bcb7f541f8c8aaf93/external/local_config_xcode/./xcode-locator-bin` on the command-line gives me a valid JSON string, so not sure what's going on.

**Comment by cgrushko** [comment]
Ah, https://github.com/bazelbuild/bazel/issues/4603#issuecomment-364266652 is probably the solution - VSCode must've been holding a file handle to `xcode-locator-bin`. I fixed the problem by deleting the repo and re-cloning it, which probably freed the handle.

I suggest including some sort of KB that mentions this possibility.
Thanks!

**Comment by jmmv** [comment]
Closing given that #4603 was addressed.
