### ISSUE TITLE
Building Bazel with JAVA_HOME set to OpenJDK 9 fails.

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#4709]
I'm trying to build Bazel using Bazel itself when JAVA_HOME is set to the official OpenJDK 9 binaries downloaded from http://jdk.java.net/9/.

I get this error:
```
ERROR: /private/var/tmp/_bazel_philwo/7a01905b4627ca044e5e3f5ad5b14d26/external/local_jdk/BUILD.bazel:165:1: @local_jdk//:langtools-neverlink: missing input file '@local_jdk//:lib/tools.jar'
```

It seems like `langtools-neverlink` is only used by `//third_party/checker_framework_dataflow` and `//third_party/checker_framework_javacutil`, both of which are only depended on by errorprone.

@cushon How would I fix this? Is there a replacement for `tools.jar` in JDK9 that `checker_framework_dataflow` should use?

**Comment by cushon** [comment]
That should probably be using `//third_party/java/jdk/langtools:javac` instead of the host JDK's `tools.jar` anyways. There isn't a direct `tools.jar` replacement in 9.

Also, those versions of the Checker Framework libraries are out of date. They should be updated to 2.2.2 to match the current version of Error Prone. And I'm not sure why they're being built from source? If they were prebuilts we wouldn't need the neverlink javac dep at all. I recommend updating them to these versions:

* http://repo1.maven.org/maven2/org/checkerframework/javacutil/2.2.2/
* http://repo1.maven.org/maven2/org/checkerframework/dataflow/2.2.2/

**Comment by davido** [comment]
> And I'm not sure why they're being built from source?

+1. I have never understood why Bazel building Checker Framework from source?

**Comment by davido** [comment]
I fixed Checker Framework fork mess, but Bazel build with Java 9 is still broken: [1], that's on:

```
davido@wizball:~/projects/bazel (master %>)$ java -version
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+12-suse-4.2-x8664)
OpenJDK 64-Bit Server VM (build 9.0.4+12-suse-4.2-x8664, mixed mode)
```

[1] http://paste.openstack.org/show/694663

**Comment by davido** [comment]
I added another CL to pass `--add-modules=jdk.unsupported` to the compiler,
and now it is failing later:

```
  $ bazel --host_javabase=/usr/lib64/jvm/java-9-openjdk build
  \--javacopt='--release 9' \
  \--java_toolchain=@bazel_tools//tools/jdk:toolchain_jdk9 \
  src:bazel
[...]
ARNING: All illegal access operations will be denied in a future release
INFO: From Building src/main/java/com/google/devtools/build/lib/libkeep-going-option.jar (1 source file) and running annotation processors (OptionProcessor):
warning: Supported source version 'RELEASE_8' from annotation processor 'com.google.devtools.common.options.processor.OptionProcessor' less than -source '1.9'
ERROR: /home/davido/projects/bazel/src/main/protobuf/BUILD:102:1: Building src/main/protobuf/libcommand_server_java_grpc.jar (1 source jar) failed (Exit 1)
/com/google/devtools/build/lib/server/CommandServerGrpc.java:20: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
Target //src:bazel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 106.315s, Critical Path: 28.19s
FAILED: Build did NOT complete successfully
```

**Comment by davido** [comment]
@cushon I added a workaround to use Java 9 `@Geberated` annotation and add the patch to the PR linked to this issue. Now I'm, able to build bazel with Java 9.

Trying to use it Bazel built that way with Java 9, I'm seeing something strange, the transitive dependency is not correctly detected, and build is aborted. SUT is my bazel_printy repository:

```
 $ java -version
  openjdk version "9.0.4"
  $ b9 build :printy_lib
INFO: Analysed target //:printy_lib (0 packages loaded).
INFO: Found 1 target and 0 test targets...
ERROR: /home/davido/projects/bazel_printy/BUILD:9:1: Building libprinty_lib.jar (1 source file) failed (Exit 1)
src/main/java/org/gerritcon/mv2016/Printy.java:22: error: [strict] Using type com.google.common.base.Joiner from an indirect dependency (TOOL_INFO: "@guava//jar"). See command below **
    System.out.println(Joiner.on(' ').join(argv));
                       ^
 ** Please add the following dependencies: 
  @guava//jar  to //:printy_lib 
 ** You can use the following buildozer command: 
buildozer 'add deps @guava//jar ' //:printy_lib 

Target //:printy_lib failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.481s, Critical Path: 0.32s
FAILED: Build did NOT complete successfully
```

But, the `guava` dependency is already there, of [course](https://github.com/davido/bazel_printy/blob/master/BUILD#L12).

Any clue, what is going on here?

If I build Bazel from the same tree with Java 8, basically, most recent master with the PR linked to this issue, but revert gRpc change as `javax.annotation.processing.Generated` does not exist on Java 8, then all is fine:

```
$ bazel build :printy_lib
Extracting Bazel installation...
...........
INFO: Analysed target //:printy_lib (10 packages loaded).
INFO: Found 1 target...
Target //:printy_lib up-to-date:
  bazel-bin/libprinty_lib.jar
INFO: Elapsed time: 7.662s, Critical Path: 3.84s
INFO: Build completed successfully, 4 total actions
```

**Comment by cushon** [comment]
The checker framework changes happened in 88a007244f51ed66a62d442e28de483e13a68576.
