### ISSUE TITLE
Unknown language warning from --test_lang_filters option

### ISSUE THREAD

**Issue by soonho-tri** [bazelbuild/bazel#4711]
### Description of the problem / feature request:

When `--test_lang_filter=-sh` is passed, `bazel-0.11.0` generates "Unknown language" warning. While [the documentation](https://docs.bazel.build/versions/master/user-manual.html#flag--test_lang_filters) uses it as an example. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`bazel test --test_lang_filters=-sh //...`

### What operating system are you running Bazel on?

macOS-10.13.3

### What's the output of `bazel info release`?

release 0.11.0-homebrew

**Comment by ulfjack** [comment]
What kind of client are you running bazel test in?

**Comment by soonho-tri** [comment]
You mean a specific project that I'm building/testing? It's https://github.com/RobotLocomotion/drake .

**Comment by soonho-tri** [comment]
I guess it's because `0.11.0-homebrew` and `0.11.1-homebrew` did not pick up this commit: https://github.com/bazelbuild/bazel/commit/bc09735be8868f345a25f9013e7c995d0871a8b4

**Comment by ulfjack** [comment]
Yeah, that sounds about right (GitHub says the commit was not picked up by any release). I'll close this as fixed then.
