### ISSUE TITLE
Bazel's release build timestamp injected as milliseconds but parsed as seconds

### ISSUE THREAD

**Issue by ixdy** [bazelbuild/bazel#4713]
### Description of the problem / feature request:
Starting with Bazel 0.10.0, it appears the bazel releases are stamped with their build timestamps in milliseconds, rather than seconds, but `bazel version` is still parsing these values as seconds:

Bazel 0.9.0:
```console
$ bazel version
Build label: 0.9.0
Build target: bazel-out/k8-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Dec 19 09:31:58 2017 (1513675918)
Build timestamp: 1513675918
Build timestamp as int: 1513675918
```

Bazel 0.10.0:
```console
$ bazel version
Build label: 0.10.0
Build target: bazel-out/k8-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Nov 9 04:43:10 +50056 (1517474666590)
Build timestamp: 1517474666590
Build timestamp as int: 1517474666590
```

Bazel 0.11.0:
```console
$ bazel version
Build label: 0.11.0
Build target: bazel-out/k8-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 9 15:39:59 +50117 (1519402203599)
Build timestamp: 1519402203599
Build timestamp as int: 1519402203599
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run `bazel version`,  notice the weird date in the output, compare the Build timestamp to second since unix epoch and milliseconds since unix epoch

### What operating system are you running Bazel on?
Linux.

### What's the output of `bazel info release`?

```console
$ bazel info release
release 0.11.0
```

**Comment by aehlig** [comment]
This is a known issue, fixed in https://github.com/bazelbuild/bazel/commit/dbf748c1a0bc7f5e3f2d6b67286d99ec88795f36, regression test added in https://github.com/bazelbuild/bazel/commit/c0e52bce8278243e8fd43f8307b413114d3ebbba
