### ISSUE TITLE
NetBSD port request

### ISSUE THREAD

**Issue by krytarowski** [bazelbuild/bazel#4719]
### Description of the problem / feature request:

There is no bazel available for NetBSD users, through pkgsrc. Certainly the same applies for other users of pkgsrc such as Illumos (SmartOS), Minix and others.

### Feature requests: what underlying problem are you trying to solve with this feature?

Get bazel aboard in NetBSD through pkgsrc.
Reuse bazel to build TensorFlow for NetBSD.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ pkg_add bazel
pkg_add: no pkg found for 'bazel', sorry.
pkg_add: 1 package addition failed
```

### What operating system are you running Bazel on?

So far none. Requested: NetBSD/amd64.

### What's the output of `bazel info release`?

None.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

No build.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

None.

###  Have you found anything relevant by searching the web?

FreeBSD package: https://www.freshports.org/devel/bazel/

### Any other information, logs, or outputs that you want to share?

Please ship it to NetBSD users! I cannot port it myself, I have tried to do so, but I've failed miserably with almost no Java knowledge.

**Comment by aehlig** [comment]
It would probably help more to ask in the NetBSD community. I'm not sure how many bazel developers are active in NetBSD. You already found the FreeBSD port (https://svnweb.freebsd.org/ports/head/devel/bazel/) which might act as a starting point, but that's all we have at the moment.

CC @jmmv who might be able to help.

**Comment by jmmv** [comment]
But there *is* a Bazel port in pkgsrc; it's just incredibly stale... and it doesn't build for NetBSD, hence why `pkg_add` fails.

I don't think there is anything for us to do here, sorry. The only person in the team able to do this is probably myself, and I have no time nor interest to do this. As @aehlig says, someone from the NetBSD community should work on this: first, make Bazel portable to NetBSD, then add a port, and then request us to add CI build nodes to ensure the port remains functional.

I'd suggest approaching the `pkgsrc-wip` project and asking if anybody has interest in doing this work.

**Comment by krytarowski** [comment]
There is no such package. Please reopen.

**Comment by jmmv** [comment]
Oh, it was removed over a year ago because it was broken.

Still, my point remains: we do not have the ability to provide this port. It's up to the NetBSD community to step up and do so at this point . Once Bazel works on NetBSD, we can consider setting up a CI build node for it.

**Comment by krytarowski** [comment]
I consider this as a fatal bug of bazel because it does not work on NetBSD and I'm looking here for volunteers with Java knowledge to help to port it.

**Comment by siepkes** [comment]
@krytarowski I'm actually working on a SmartOS (aka Illumos, aka Solaris) port. I'm (mostly) a Java dev so I don't have much worries about the Java part. I've created a couple of PR's (#4967 and #4969) which probably also help with NetBSD support. If (emphasis on if) I get the SmartOS port working I don't think adding NetBSD will be that much more work.

**Comment by krytarowski** [comment]
Great! I was trying to package it myself, but I've failed with gradle dependency.. nowadays gradle packaged by Joyent people in pkgsrc so it's a step forward.

Please try to package Bazel in the pkgsrc context and I will add NetBSD specific patches... leaving the build machinery for people familiar with Java.

**Comment by miwarin** [comment]
Please wait. I will try it once.
I saw FreeBSD ports, uhhh.... too many patches :-(

**Comment by siepkes** [comment]
@krytarowski @miwarin Just a quick FYI for you guys. This is the patch I created to get Bazel (0.11.1) running on SmartOS: https://gist.github.com/siepkes/989ac0267082b1a2df6aafa222964358 . I'm currently cleaning it up and tweaking it but the whole thing bootstraps (compile.sh) Bazel. 2 POSIX compatibility fixes in it are already upstreamed. There is only one other in it for which I will create a separate PR. From there I will try and get it in pkgsrc and upstream as much as possible.

Solaris is really strict and FreeBSD support is already in Bazel so I would think that porting it to NetBSD should be relatively easy?

**Comment by krytarowski** [comment]
This looks good. Yes, adding ifdefs (in Java terminology) seems relatively simple. Just the tooling is all Greek to me. Instead of setting JAVA_HOME and fiddling with that, I prefer to use it through well defined and reproducible pkgsrc framework.

**Comment by krytarowski** [comment]
Moreover, without bazel in pkgsrc, there is no option to get there tensorflow.. It's not a regular tool like sed or awk.

**Comment by siepkes** [comment]
@krytarowski There is a fundamental difference (IMHO) between Bazel and the more "standard" *nix build systems like autoconf; Bazel defines the tool chain (compiler, linker, flags, etc.) where as other *nix build systems usually detect the environment they are running in and adept to that. This makes is somewhat harder to integrate into pkgsrc. So as porter you must define that toolchain. For example the toolchain in the patch uses GCC from pkgsrc and the SmartOS linker.

**Comment by krytarowski** [comment]
I'm aware of that there is probably need to rewrite its internals and/or write custom scripts and preprocess for a package management. There was need to do the same for gradle.

I'm just a able to add ifdefs for NetBSD.
