### ISSUE TITLE
bootstrap_dist_file_test fails on Windows

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#4722]
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
ls: cannot access 'C:/Program Files/Java/jdk*': No such file or directory
INFO[bazel_bootstrap_distfile_test 2018-02-27 09:36:22 (+0000)] bazel binary is at /d/build/buildkite-windows-bp8r/bazel/bazel-bazel-postsubmit/src/test/shell/bin
INFO[bazel_bootstrap_distfile_test 2018-02-27 09:36:22 (+0000)] setting up client in D:/temp/_bazel_buildkite/hv3ry7qg/execroot/io_bazel/_tmp/eabe42fa62db9997c05f08353752736f/workspace
INFO[bazel_bootstrap_distfile_test 2018-02-27 09:36:31 (+0000)] setting up client in D:/temp/_bazel_buildkite/hv3ry7qg/execroot/io_bazel/_tmp/eabe42fa62db9997c05f08353752736f/workspace
rm: cannot remove 'D:/temp/_bazel_buildkite/hv3ry7qg/execroot/io_bazel/_tmp/eabe42fa62db9997c05f08353752736f/workspace': Device or resource busy
rm: cannot remove 'D:/temp/_bazel_buildkite/hv3ry7qg/execroot/io_bazel/_tmp/eabe42fa62db9997c05f08353752736f/workspace': Device or resource busy

bootstrap test

** test_bootstrap **************************************************************
INFO[bazel_bootstrap_distfile_test 2018-02-27 09:36:39 (+0000)] test_bootstrap: start
INFO[bazel_bootstrap_distfile_test 2018-02-27 09:36:39 (+0000)] test_bootstrap: unzip
INFO[bazel_bootstrap_distfile_test 2018-02-27 09:36:48 (+0000)] test_bootstrap: bootstrap
ls: cannot access 'C:/Program Files/Java/jdk*': No such file or directory
Building Bazel from scratch
ERROR: JDK not found, please set $JAVA_HOME.
-- Test log: -----------------------------------------------------------
------------------------------------------------------------------------
test_bootstrap FAILED: Expected to be able to bootstrap bazel .
D:\temp\_bazel_buildkite\hv3ry7qg\execroot\io_bazel\bazel-out\x64_windows-fastbuild\bin\src\test\shell\bazel\bazel_bootstrap_distfile_test:51: in call to test_bootstrap
INFO[bazel_bootstrap_distfile_test 2018-02-27 09:36:49 (+0000)] Cleaning up workspace
FAILED: test_bootstrap

** 0 / 1 tests passed. *********************************************************
** There were errors. **********************************************************
INFO[bazel_bootstrap_distfile_test 2018-02-27 09:36:51 (+0000)] Cleaning up BAZEL_INSTALL_BASE under D:/temp/_bazel_buildkite/hv3ry7qg/execroot/io_bazel/_tmp/eabe42fa62db9997c05f08353752736f/root/install/ab36f2d8d3d2f45b343a8b60fe500400
INFO[bazel_bootstrap_distfile_test 2018-02-27 09:37:01 (+0000)] Test cleanup: couldn't delete D:/temp/_bazel_buildkite/hv3ry7qg/execroot/io_bazel/_tmp/eabe42fa62db9997c05f08353752736f/root/install/ab36f2d8d3d2f45b343a8b60fe500400 after 10 seconds (Timeout in 110 seconds.)
```

**Comment by buchgr** [comment]
cc: @laszlocsomor

**Comment by meteorcloudy** [comment]
Looks like the JDK is installed under `C:/openjdk`, right? We should set JAVA_HOME to the correct place.

**Comment by meteorcloudy** [comment]
https://github.com/bazelbuild/bazel/blob/43fd34062f3e1a4eae57209e80aefadf00c1ade6/scripts/bootstrap/buildenv.sh#L98
The problem is, during bootstrap we assume jdk is installed under `C:/Program Files/Java/jdk` if `JAVA_HOME` is not set.
And when running tests, we clean up all environment variables, so `JAVA_HOME` is always missing.

If `JAVA_HOME` is set on the Windows slaves, I think we can fix it by adding `--test_env=JAVA_HOME` in [test_flags](https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/pipelines/bazel-postsubmit.yml#L73)

**Comment by philwo** [comment]
Hi Yun,

Indeed, the used JDK on all machines is Azul Zulu 8 (instead of Oracle JDK). It is installed in C:\openjdk and JAVA_HOME is set to it! :)

If that’s a big problem I can try to move the JDK to Program Files. But maybe setting —test_env is better?

**Comment by meteorcloudy** [comment]
Yeah, I agree, I think setting `--test_env` is more robust. Can you do that? :) 
I don't know how to deploy to buildkite yet.

**Comment by meteorcloudy** [comment]
Hmmm,, from https://buildkite.com/bazel/bazel-bazel/builds/396#b08da688-2348-4606-932e-45392f4eeab3
It's still failing with the same error with `--test_env=JAVA_HOME`

I found the reason is in testenv.sh, it doesn't respect JAVA_HOME first.
https://github.com/bazelbuild/bazel/blob/38a36ccd369e66a8a9bca8e6753d342a1cec05a1/src/test/shell/testenv.sh#L58

Will send a fix.

**Comment by meteorcloudy** [comment]
Now I see:
```
** test_bootstrap **************************************************************
INFO[bazel_bootstrap_distfile_test 2018-03-01 09:06:41 (+0000)] test_bootstrap: start
INFO[bazel_bootstrap_distfile_test 2018-03-01 09:06:41 (+0000)] test_bootstrap: unzip
INFO[bazel_bootstrap_distfile_test 2018-03-01 09:06:51 (+0000)] test_bootstrap: bootstrap
Building Bazel from scratch......ERROR: Visual Studio not found
```

Where is Visual Studio installed?

**Comment by philwo** [comment]
Visual Studio 2017 Build Tools are installed in the standard location. You can login to the testing-windows VM and check it out :)

**Comment by meteorcloudy** [comment]
Looks like we are using VC 2017 build tools?
https://github.com/bazelbuild/bazel/blob/a07419c8ace66ce3926466b1d53982286bb9bdba/src/main/native/windows/build_windows_jni.sh#L53-L58
This script (used only during bootstrap) doesn't work with VC 2017.

Besides, we still have this [open bug](https://github.com/bazelbuild/bazel/issues/3949) preventing us from completely supporting VC 2017.

So, I would recommend we still use VC 2015 build tools on our Windows slaves.

**Comment by meteorcloudy** [comment]
Unfortunately I was blocked from accessing any VM because I'm in China. :(

**Comment by philwo** [comment]
Hi Yun,

ohh.. I didn't know. I checked with Laszlo and he said VC 2017 build tools should be fine, also our documentation says it's OK to use 2017 tools: https://docs.bazel.build/versions/master/windows.html#build-c - but no problem, we can just downgrade to 2015 tools on CI for now! I have already prepared it, it's just a matter of uncommenting that code in the script ;)

Should we change the docs and say that 2017 tools are not fully supported yet and link to that open bug?

**Comment by laszlocsomor** [comment]
Philipp, sorry for giving you the wrong information, I was also under the impression that VC/VCBT 2017 was fine.

Yes, I think we should change the docs. Philipp, would you do that?

**Comment by philwo** [comment]
No worries at all! I was the one pushing for 2017, because I like newer versions 😄

I'll send you a change for the docs later.

**Comment by meteorcloudy** [comment]
@philwo Thank you so much!
