### ISSUE TITLE
experimental_skyframe_target_pattern_evaluator causes Bazel to no longer emit "patternSkipped" events in  BEP

### ISSUE THREAD

**Issue by alexmv** [bazelbuild/bazel#4731]
### Description of the problem / feature request:

784bb52613feb484221c3aa6756de45012163088 switched to the "new UI"; however, this change appears to have had a material change on the BEP output.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

./bazel-bin/src/bazel test --keep_going --build_event_json_file foo.json //not/actually/present

Expected that the `foo.json` file would contain a `patternSkipped` event for the `//not/actually/present` pattern.  It does not.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

```
development version
```

(I bisected to 784bb52613feb484221c3aa6756de45012163088; it replicates on current `master` as well)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
git@github.com:dropbox/bazel
d926bc40260549b997a6a5a1e82d9e7999dbb65e
784bb52613feb484221c3aa6756de45012163088
```

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

Nope.

**Comment by alexmv** [comment]
Whoops, forgot to fill in the buidl instructions.  Bazel was built via installing bazel 0.7.0 from pacakges (to let it build itself in the area of the relevant commits) and then built via `~/bazel-0.7.0/bin/bazel build //src:bazel`

**Comment by benjaminp** [comment]
More specifically, the omission is caused by `--experimental_skyframe_target_pattern_evaluator`.

**Comment by aehlig** [comment]
@ulfjack can you have a look, as you probably know the Skyframe target pattern evaluator best. Thanks.

**Comment by benjaminp** [comment]
https://cr.bazel.build/42690
