### ISSUE TITLE
Bazel 0.11.0 cant be built from source on Linux because of missing execute bits

### ISSUE THREAD

**Issue by s-m-e** [bazelbuild/bazel#4733]
### Description of the problem:

Bazel fails to build from source on openSUSE Leap 42.3 x86_64. Root cause: Two scripts lack an execute bit, bash throws `permission denied` error, built is aborted.

### Bugs: what's the simplest, easiest way to reproduce this bug?

Download the latest [dist zip file, version 0.11.0](https://github.com/bazelbuild/bazel/releases/download/0.11.0/bazel-0.11.0-dist.zip), unpack it (with KDE's Ark), `cd` into it, run `bash ./compile.sh`.

### What operating system are you BUILDING Bazel on?

openSUSE Leap 42.3 x86_64 (Linux)

### WORKAROUND

This can be worked (solved) around by `chmod +x` on the following two files: 

* `src/package-bazel.sh`
* `src/main/java/com/google/devtools/build/lib/merge_licenses.sh`

**Comment by katre** [comment]
I'll take a look, thanks for bringing this to our attention.

**Comment by katre** [comment]
I just downloaded and unpacked the dist file with the built-in "unzip" program from Debian, and I see the +x bits as expected:
```
$ ls -l src/package-bazel.sh src/main/java/com/google/devtools/build/lib/merge_licenses.sh
-rwxr-xr-x 1 jcater eng  864 Jan  1  1980 src/main/java/com/google/devtools/build/lib/merge_licenses.sh
-rwxr-xr-x 1 jcater eng 1662 Jan  1  1980 src/package-bazel.sh
```

Is Ark doing something unusual with other zip files?

**Comment by s-m-e** [comment]
@katre Possibly ... Let me check. What tool / command have you used for unpacking?

**Comment by katre** [comment]
Just the command line `unzip` utility provided by my Debian install:
```
Package: unzip
Version: 6.0-21
Installed-Size: 534
Maintainer: Santiago Vila <sanvila@debian.org>
Architecture: amd64
Depends: libbz2-1.0, libc6 (>= 2.14)
Suggests: zip
Description: De-archiver for .zip files
 InfoZIP's unzip program. With the exception of multi-volume archives
 (ie, .ZIP files that are split across several disks using PKZIP's /& option),
 this can handle any file produced either by PKZIP, or the corresponding
 InfoZIP zip program.
 .
 This version supports encryption.
Description-md5: b83e2b495da5d292f3fe6ab67b088c47
Multi-Arch: foreign
Homepage: http://www.info-zip.org/UnZip.html
Filename: pool/unzip_6.0-21_amd64_d0d8d9ab3e55b139a207c43b7a15faec17faf7b0da77f9b844ffd2d2c03b68e6.deb
Priority: optional
SHA256: d0d8d9ab3e55b139a207c43b7a15faec17faf7b0da77f9b844ffd2d2c03b68e6
Section: utils
Size: 169776
```

**Comment by s-m-e** [comment]
Yep, I can confirm it. This is an issue with Ark. Sry for the confusion, I'll file another bug somewhere else ...

**Comment by katre** [comment]
No problem, thanks for helping me debug!

**Comment by wmark** [comment]
I can confirm this for Ubuntu 16.04 and 18.04 if *minizip* is providing `unzip`. As a workaround, and because any *alternative* won't be changed if `apt` is not run connected to a *terminal*:

```bash
# just in case
apt-get install zip unzip minizip-

# the actual workaround
find -name '*.sh' -exec chmod a+x '{}' \;
```
