### ISSUE TITLE
Changes in a generated AndroidManifest.xml don't propagate to the final APK on Windows

### ISSUE THREAD

**Issue by pmuetschard** [bazelbuild/bazel#4734]
### Description of the problem:

On Windows, a `android_binary` rule, which uses a `manifest` attribute that is a label to a rule which generates the XML, fails to propagate changes to the final APK if the generated manifest changes.

We want to "stamp" our APKs by putting a hash of the source files into the Android manifest. To do this, we have a rule, which depends on the sources and a template. It computes the hash of the sources and then replaces a token in the template and writes the resulting XML to its output. This output is then uses as the `manifest` attribute in the `android_binary` rule.

Making a change to the source file, while causing the hash to change, even in the merged manifest, does not cause the manifest of the final APK to change. It appears that the `Processing Android resources for <target>` action does not get run, even if the input manifest (the output of the merger) changes. This only happens on Windows.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

On Windows

1) `git clone https://github.com/pmuetschard/android-bazel-bug`
2) `cd android-bazel-bug`
3) `bazel build :test`
4) `aapt l -a bazel-bin\test.apk` and note down the application label
5) `type bazel-genfiles\AndroidManifest.xml` - notice how the checksum matches what `aapt` printed.
6) Modify `MainActivity.java` by adding/removing some whitespace
7) `bazel build -s :test`
8) Notice that the `Processing Android resources for :test` action was not run.
9) `aapt l -a bazel-bin\test.apk` and notice how the label did not change from step 4 or 5.
10) `type bazel-genfiles\AndroidManifest.xml` - notice how the checksum has changed and does not match what `aapt` printed in step 9.

Optional: do the above steps on Linux and notice how the label in the APK gets updated as expected.

### What operating system are you running Bazel on?

Windows 10.

### What's the output of `bazel info release`?

0.10.0

**Comment by reforgetYZ** [comment]
Windows 10 系统 在GitHub 已经下载bazelbuild/bazel  之后不知道怎么用 ,并且tensorflow 运行Android 
一直在报这个问题
Error:Execution failed for task ':buildNativeBazel'.
> A problem occurred starting process 'command '/usr/bin/bazel''
已经把build.gradle 中的bazelLocation 改过了 def bazelLocation = '/usr/bin/bazel'

**Comment by aj-michael** [comment]
Huh. This is weird. I can reproduce (on Windows, and not on Linux, per the OP).

**Comment by aj-michael** [comment]
On Windows, these are the actions that get run when the input to the manifest generator changes:


```
SUBCOMMAND: # //:manifest [action 'SkylarkAction AndroidManifest.xml']
cd C:/users/ajmichael/appdata/local/temp/6/_bazel_ajmichael/ty3skwh5/execroot/__main__
  SET PATH=C:\tools\msys64\usr\bin;C:\tools\msys64\bin;C:\python3\Scripts\;C:\python3\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\GooGet;C:\Program Files\Google\Compute Engine\metadata_scripts;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\Google\Compute Engine\sysprep;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;c:\openjdk\bin;c:\bazel;c:\buildkite;C:\Users\ajmichael\AppData\Local\Microsoft\WindowsApps;
  bazel-out/host/bin/hash.exe AndroidManifest.xml.in bazel-out/x64_windows-fastbuild/genfiles/AndroidManifest.xml MainActivity.java
SUBCOMMAND: # //:test [action 'Merging manifest for //:test']
cd C:/users/ajmichael/appdata/local/temp/6/_bazel_ajmichael/ty3skwh5/execroot/__main__
  SET PATH=C:\tools\msys64\usr\bin;C:\tools\msys64\bin;C:\python3\Scripts\;C:\python3\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\GooGet;C:\Program Files\Google\Compute Engine\metadata_scripts;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\Google\Compute Engine\sysprep;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;c:\openjdk\bin;c:\bazel;c:\buildkite;C:\Users\ajmichael\AppData\Local\Microsoft\WindowsApps;
  bazel-out/host/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox.exe @bazel-out/x64_windows-fastbuild/bin/test_merged/test/AndroidManifest.xml-2.params
SUBCOMMAND: # //:test [action 'Building libtest.jar (1 source file)']
cd C:/users/ajmichael/appdata/local/temp/6/_bazel_ajmichael/ty3skwh5/execroot/__main__
  SET LC_CTYPE=en_US.UTF-8
  external/local_jdk/bin/java.exe -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac-9+181-r4173-1.jar -jar external/bazel_tools/tools/jdk/JavaBuilder_deploy.jar @bazel-out/x64_windows-fastbuild/bin/libtest.jar-2.params
```

**Comment by aj-michael** [comment]
The next action should be

```
SUBCOMMAND: # //:test [action 'Processing Android resources for //:test']
cd C:/users/ajmichael/appdata/local/temp/6/_bazel_ajmichael/ty3skwh5/execroot/__main__
  SET PATH=C:\tools\msys64\usr\bin;C:\tools\msys64\bin;C:\python3\Scripts\;C:\python3\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\GooGet;C:\Program Files\Google\Compute Engine\metadata_scripts;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\Google\Compute Engine\sysprep;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;c:\openjdk\bin;c:\bazel;c:\buildkite;C:\Users\ajmichael\AppData\Local\Microsoft\WindowsApps;
  bazel-out/host/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox.exe @bazel-out/x64_windows-fastbuild/bin/test_symbols/R.txt-2.params
```

which has params file:

```
C:\Users\ajmichael\android-bazel-bug>type bazel-out\x64_windows-fastbuild\bin\test_symbols\R.txt-2.params
--tool
PACKAGE
--
--aapt
external/androidsdk/build-tools/27.0.3/aapt.exe
--primaryData
::bazel-out/x64_windows-fastbuild/bin/test_merged/test/AndroidManifest.xml
--buildToolsVersion
27.0.3
--androidJar
external/androidsdk/platforms/android-25/android.jar
--rOutput
bazel-out/x64_windows-fastbuild/bin/test_symbols/R.txt
--srcJarOutput
bazel-out/x64_windows-fastbuild/bin/test.srcjar
--proguardOutput
bazel-out/x64_windows-fastbuild/bin/proguard/test/_test_proguard.cfg
--mainDexProguardOutput
bazel-out/x64_windows-fastbuild/bin/proguard/test/main_dex_test_proguard.cfg
--manifestOutput
bazel-out/x64_windows-fastbuild/bin/test_processed_manifest/AndroidManifest.xml
--resourcesOutput
bazel-out/x64_windows-fastbuild/bin/test_files/resource_files.zip
--packagePath
bazel-out/x64_windows-fastbuild/bin/test.ap_
--debug
--packageForR
test
```

**Comment by aj-michael** [comment]
If we don't use manifest_values, we do trigger the resource processing action, but then we go no further...

**Comment by aj-michael** [comment]
I attached a debugger and confirmed that the resource processing action is created with two inputs:

```
File:[[C:/users/ajmichael/appdata/local/temp/6/_bazel_ajmichael/ty3skwh5/execroot/__main__]bazel-out/x64_windows-fastbuild/bin]test_merged/test/AndroidManifest.xml
File:[[C:/users/ajmichael/appdata/local/temp/6/_bazel_ajmichael/ty3skwh5[source]]external/androidsdk/platforms/android-25/android.jar
```

AFAICT, the only difference between the actions created on Linux and Windows is whether we unconditionally use param files.

Laszlo, I'm thinking there is an underlying Windows issue here

**Comment by laszlocsomor** [comment]
Adam, thanks for figuring that out!

> Laszlo, I'm thinking there is an underlying Windows issue here

I wouldn't rule that out either :)

What's the set of inputs for the same action on Linux, do you know?

**Comment by aj-michael** [comment]
I have not debugged it on Linux - however, from reading the code it should be the same. I can verify if you'd like. But since we create the action on Windows to have `test_merged/test/AndroidManifest.xml` as an input - and we've verified that `test_merged/test/AndroidManifest.xml` is changing during the build, the fact that the resource processing action is not being rerun seems to be an incrementality bug

**Comment by aj-michael** [comment]
Also, I think I've ruled out the param file usage as the culprit. I built a Bazel on Linux that unconditionally uses param files for the resource processing action - and it did not have this bug.

**Comment by laszlocsomor** [comment]
Ok, thanks!

Hmm, I've been debugging an issue last week (issue #4755) that looked similar to this one: on Windows we didn't detect that a file changed. I didn't manage to continue debugging today because of distractions, but I'm eager to continue tomorrow.

**Comment by aj-michael** [comment]
Possibly relevant observation from debugging: I think that we are always creating RegularFileStateValues for test_merged/test/AndroidManifest.xml with a FileContentsProxy object with ctime 0.

**Comment by aj-michael** [comment]
debugging on Linux I got a ctime 1520273202 (Monday, March 5, 2018 6:06:42 PM) when creating the RegularFileStateValue for that file. I see in WindowsFileSystem.java:

```
          @Override
          public long getLastChangeTime() {
            // This is the best we can do with Java NIO...
            return attributes.lastModifiedTime().toMillis();
          }
```

So I guess this is intentional?

**Comment by haxorz** [comment]
> [aj-michael] So I guess this is intentional?

https://github.com/bazelbuild/bazel/commit/4f647e859203dc3a2f26ab088b95ef1a58c2e3ea is relevant, not for this bug but for the history of the code. before this commit, FileContentsProxy was using FileStatus#getLastModifiedTime, the WindowsFileSystem implementation of which is the same as the one you gave, just without the comment.

so what's the deal here? ignoring this issue and only thinking about #4755, i would wonder whether there's something particular about the buildkite windows CI environment such that ava.nio.file.attribute.BasicFileAttributes#lastModifiedTime always returns a FileTime whose #toMillis is 0. but this issue here has nothing to do with buildkite. so i agree there's something more fundamentally bad going on; if bazel-on-windows is unable to reliably get correct FileStateValues, then it has a major correctness problem.

**Comment by laszlocsomor** [comment]
found the culprit for https://github.com/bazelbuild/bazel/issues/4755, see https://github.com/bazelbuild/bazel/issues/4755#issuecomment-370835018

**Comment by laszlocsomor** [comment]
@haxorz : 

> i would wonder whether there's something particular about the buildkite windows CI environment such that ava.nio.file.attribute.BasicFileAttributes#lastModifiedTime always returns a FileTime whose #toMillis is 0

It doesn't! On the testing Windows VM (which has the same image as the CI VMs), I see that the mtime is correct. The atime is wrong though.

Demo:
```
C:\Users\laszlocsomor\tmp>type Mtime.java
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.BasicFileAttributes;

public class Mtime {
  public static void main(String[] args) throws IOException {
    File f = new File("c:\\users\\laszlocsomor\\stuff\\bazel\\a");
    System.out.println("file=(" + f + ")");
    System.out.println("nexists=" + (f.exists() ? "1" : "0"));
    BasicFileAttributes bfa = Files.readAttributes(f.toPath(), BasicFileAttributes.class);
    System.out.println("mtime=" + Long.toString(bfa.lastModifiedTime().toMillis()));
    System.out.println("atime=" + Long.toString(bfa.lastAccessTime().toMillis()));
  }
}
```

The run this:
```
C:\Users\laszlocsomor\tmp>javac Mtime.java & java Mtime
file=(c:\users\laszlocsomor\stuff\bazel\a)
exists=1
mtime=1520429580644
atime=1520429580644
```

Modify the file contents, see the `mtime` updated but not the `atime`:
```
C:\Users\laszlocsomor\tmp>echo foo > ..\stuff\bazel\a

C:\Users\laszlocsomor\tmp>javac Mtime.java & java Mtime
file=(c:\users\laszlocsomor\stuff\bazel\a)
exists=1
mtime=1520429633390
atime=1520429580644
```

In fact nothing that I tried changes the `atime`, neither changing file attributes nor dumping the file's contents. So I don't know what's the deal with that, perhaps it's showing the file's creation time.

**Comment by ben-clayton** [comment]
Hi folks.

Are there any updates on this bug?

It's a bit of a scary one that's putting [us](https://github.com/google/gapid) off developing on Windows as we're uncertain whether our builds are taking changes. If there's anything we can do to help move this along, please let me know.

Cheers,
Ben

**Comment by laszlocsomor** [comment]
I'll take a look at this right now. It sounds like a correctness bug.

**Comment by laszlocsomor** [comment]
> In fact nothing that I tried changes the `atime`, neither changing file attributes nor dumping the file's contents.

I found the reason for this on https://msdn.microsoft.com/en-us/library/windows/desktop/ms724284(v=vs.85).aspx:

> On NTFS, access time has a resolution of 1 hour.

**Comment by laszlocsomor** [comment]
[@aj-michael 's comment](https://github.com/bazelbuild/bazel/issues/4734#issuecomment-370509886) is relevant: apparently on both Windows and Linux, Bazel creates `bazel-bin/test_merged/test/AndroidManifest.xml` with mtime=0, but while on Linux the file has a nonzero ctime, the WindowsFileSystem returns the mtime as the ctime, so the file seems to never change, and that's why Bazel doesn't reexecute downstream actions.

Unfortunately NTFS doesn't track ctime the same way Unix filesystems do, instead we have creation time (resultion unknown), access time (resolution: 1 hour), and write time (similar to mtime, resolution: 2 seconds).

I'm still thinking about a good way to solve this problem.

One solution is if WindowsFileSystem's stat returns `max(write time, creation time)`, but that's just wrong. And returning the access time is equally wrong because of its coarse resolution.

I'll try to find out why Bazel zeroes out the mtime of this file, and see if that's a bug or not.

**Comment by laszlocsomor** [comment]
Apparently the Android rules set the mtime to 0 on purpose:
https://github.com/bazelbuild/bazel/blob/d6a98282e229b311dd56e65b72003197120f299a/src/tools/android/java/com/google/devtools/build/android/AndroidResourceOutputs.java#L302-L303

There are 4 more occurrences of `setLastModifiedTime`.

**Comment by aj-michael** [comment]
Cc @corbinrsmith-work

**Comment by laszlocsomor** [comment]
Unfortunately commenting out those lines doesn't solve the problem. Let me keep looking for the culprit.

**Comment by laszlocsomor** [comment]
Ok, this *was* the culprit after all, I just didn't comment out occurrences of `setLastModifiedTime` in other files. :) I'll send a PR shortly.

**Comment by laszlocsomor** [comment]
@philwo, heads-up that we'll need to cherrypick this into 0.12.0 too (https://github.com/bazelbuild/bazel/issues/4582).
