### ISSUE TITLE
XML test report uses the wrong attribute name for duration

### ISSUE THREAD

**Issue by guoshimin** [bazelbuild/bazel#4738]
### Description of the problem / feature request:

XML test report uses the wrong attribute name for duration. According to https://www.ibm.com/support/knowledgecenter/en/SSQ2R2_9.5.0/com.ibm.rsar.analysis.codereview.cobol.doc/topics/cac_useresults_junit.html (and a few other sources,) the attribute name for test duration should be "time", but the reports generated by Bazel uses attribute name "duration". I believe this is the reason the Jenkins JUnit report UI shows all durations as 0.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`bazel test` any target. On my system the xml report can be found at `bazel-out/k8-fastbuild/testlogs/<path_to_target>/test.xml`

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

`release 0.10.1`

###  Have you found anything relevant by searching the web?

Searched all these places. Didn't find anything relevant.

### Any other information, logs, or outputs that you want to share?

Offending line: https://github.com/bazelbuild/bazel/blob/77c4f30b333106ff15de5b5dd42076db01fd22b4/tools/test/test-setup.sh#L187

First introduced here: https://github.com/bazelbuild/bazel/commit/4bb4b3d7553f74d68b38743dd6500ece1b1be2e7

**Comment by guoshimin** [comment]
@aehlig Why is this marked as feature request?

**Comment by laszlocsomor** [comment]
Adding "Under investigation" because I'm not sure this bug is still relevant, see my comment: https://github.com/bazelbuild/bazel/pull/4764#issuecomment-370355271
