### ISSUE TITLE
Bazel CI failing

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#474]
"Bazel" is failing on http://ci.bazel.io/

It has been failing for the past few builds. It's always one of the `Bazel » 1.x,darwin-x86_64` steps failing, but it's non-deterministic which one.

Per our policy, I'm filing a P0 bug. Assigning to Kristina, because it's still daytime in NY.

**Comment by damienmg** [comment]
I fixed the osx build earlier today.

**Comment by damienmg** [comment]
It was a problem with the xcode machine. The other test is a flake and on
next push ci should be blue again.

**Comment by laszlocsomor** [comment]
Thank you. Please clarify, is the CI push the same as the Bazel push?
I currently cannot push the sources because some checks are failing.

**Comment by damienmg** [comment]
I mean on the next bazel push. The ci rerun on every push to github.

**Comment by kchodorow** [comment]
It looks like this is now failing due to a missing third_party jar (http://mvnrepository.com/artifact/commons-codec/commons-codec/1.9, containing the Base64 class).  I'll put it in third_party and try again, if you want to go home, @laszlocsomor.

**Comment by laszlocsomor** [comment]
Thanks Kristina!

I'm actually still in the US :) so no going home just yet.

**Comment by kchodorow** [comment]
Oh that's true, I'll send you the CR :)

**Comment by damienmg** [comment]
maven_test is still failing, is the change in? Do we need to do a push?

**Comment by kchodorow** [comment]
The build needed the Apache jar added as a dep, looks like it's fixed now.

**Comment by damienmg** [comment]
Unfortunately we have some tests that are still flaky :( Re-running the
test suite.

It will be easier to track once we connect the dashboard or Junit tests.
will look at that tomorrow.
