### ISSUE TITLE
Support NDK 17

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#4742]
r17 is expected to land [in May 2018.](https://github.com/android-ndk/ndk/wiki#release-schedule)

Betas 1 and 2 will be released this month (March) and next month (April) respectively.

 https://android.googlesource.com/platform/ndk/+/ndk-release-r17/CHANGELOG.md

[Relevant changes:](https://android.googlesource.com/platform/ndk/+/master/docs/Roadmap.md#ndk-r17)
- `libc++`/`@androidndk//:toolchain-libcpp` will become the default STL. The other STLs will be removed in r18, or moved to another project.
- GCC will no longer be supported.
- Removed support for building against `armeabi`, `mips`, and `mips64`.
- ~Removed support for API levels 14 and 15. New minimum is 16.~
- [clang is updated to v6.0.2, build 4691093](https://android.googlesource.com/platform/prebuilts/clang/host/darwin-x86/+/refs/heads/ndk-release-r17/clang-4691093/AndroidVersion.txt)

**Comment by steeve** [comment]
NDK17 is was released. I haven't tested with bazel 0.14rc, but I don't see this being in the changelog.

**Comment by jin** [comment]
I haven't had free cycles to work on this yet. Bumping to P1 for re-prioritization.

**Comment by steeve** [comment]
That's great thank you!

**Comment by jin** [comment]
@steeve WIP: https://github.com/bazelbuild/bazel/pull/5371

**Comment by Nimitz14** [comment]
When calling `./configure` in tensorflow I get
```
WARNING: The API level of the NDK in /home/seni/Android/Sdk/ndk-bundle is 17, which is not supported by Bazel (officially supported versions: [10, 11, 12, 13, 14, 15, 16]). Please use another version.
```
Can someone please confirm I can ignore this warning?

**Comment by jin** [comment]
Yes, you can ignore it. Bazel supports up to r18 now.
