### ISSUE TITLE
Bazel performance regression since 0.9

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#4749]
### Description of the problem / feature request:

0.10 doubled the build time for 100% remote cache hit builds

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Populate a cache with results of a build under 0.9 and 0.10.x, observe the 100% hit rate builds compared between the two.

I happen to have a large number of C++ targets, and I am beginning to suspect more post-action activity (header inclusion rule) as the source of this. I am attempting to bisect the problem out.

### What operating system are you running Bazel on?

Ubuntu 14.04

### What's the output of `bazel info release`?

0.9, 0.10.1, 0.11

**Comment by werkt** [comment]
This was caused by 3d0a04ddc6b0f4d660256f274ceb3e5c7f654c90

I am attempting to narrow it down.

+@ola-rozenfeld

**Comment by buchgr** [comment]
3d0a04d does cause additional `stat` calls. Could it be that?

**Comment by ola-rozenfeld** [comment]
So far George and I located two culprits: the extra digest check after download, and the isDirectory check on each output file. Do you know of any other calls added?

**Comment by buchgr** [comment]
@ola-rozenfeld no I don't. With `stat` calls I was referring to the `isDirectory` check.

**Comment by ola-rozenfeld** [comment]
That isDirectory check does nothing anyway, btw. Since the output file doesn't exist at that point, it will always return false. I noticed this a few days ago and I think I even filed a bug, but can't find it now. Anyway, I was going to fix it. It just happens wo work with our tests, because our RemoteWorker doesn't care that we get the output as OutputFile rather than OutputDirectory.

**Comment by werkt** [comment]
This is the source of the majority of the time lost. I am amazed that this stat did not completely cripple others' builds immediately - the only thing that made it tenable on my side was the use of a ramdisk output fs.

https://github.com/bazelbuild/bazel/blob/46f7106d0b20ae0ba245c3609545600ae379cea4/src/main/java/com/google/devtools/build/lib/remote/TreeNodeRepository.java#L315-L318

Of the total time change (4.55x observed)  the leaf path construction represented 7% of the overhead, with the stat resulting from the isDirectory check being 93%

I've removed this section locally (since output directories are neither used nor do they work) and gotten my full cache hit performance back up to 0.9 levels.

@ola-rozenfeld has indicated that we could cache the existence as a directory here to do the right thing without the cost. This (and many other instances I can think of) is begging for a "IO ist verboten" annotation that could be identified through static analysis.

**Comment by ola-rozenfeld** [comment]
I have a patch in review that removes all three I/O instances thus far. Should be in soon.
