### ISSUE TITLE
Architecture dependent http_archive

### ISSUE THREAD

**Issue by pspeter3** [bazelbuild/bazel#475]
I would like to be able to download the version of node, for building TypeScript, dependent on the architecture of the machine that is being used. Is this possible? Replicating Node's build scripts in Bazel seems not worth the effort to make it an git archive.

**Comment by pspeter3** [comment]
My belief is that this would be done with `select`

**Comment by kchodorow** [comment]
Not sure if you worked this out on your own or not, but select is the best mechanism for this at the moment.  Note that select can only be used in BUILD files (not the WORKSPACE file).

**Comment by pspeter3** [comment]
Oh interesting! So can I not add a `new_http_archive` with select then? That seems to imply that I would need to download every possible binary

**Comment by kchodorow** [comment]
You shouldn't have to.  If you select one of them, Bazel should only need to download that one.

**Comment by pspeter3** [comment]
An I can put that in a BUILD file? Cool.

**Comment by kchodorow** [comment]
So you'd have a WORKSPACE file like:

```
new_http_archive(name = "node-x86-64", ...)
new_http_archive(name = "node-32", ...)
new_http_archive(name = "node-ppc", ...)
...
```

The a BUILD file something like:

```
genrule(
    ...
    tools = select(
        ":intel64" : ["@node-x86-64//:node-bin"],
        ":intel32" : ["@node-x32//:node-bin"],
        ":ppc32" : ["@node-ppc//:node-bin"],
    )
)
```

**Comment by pspeter3** [comment]
Ok, that example makes a tremendous amount of sense. Thank you
