### ISSUE TITLE
build-runfiles does not use environment variables set with --action_env

### ISSUE THREAD

**Issue by burkpojken** [bazelbuild/bazel#4750]
### Description of the problem / feature request:
We have to set LD_LIBRARY_PATH in our environment for bazel to work since it will not find GLIBCXX otherwize.
We would like to use --experimental_strict_action_env together with --action_env to make sure we have control of the environment and possibility to use the remote cache in the best way.

When  --experimental_strict_action_env is set the command build-runfiles fails because GLIBCXX is not found even if LD_LIBRARY_PATH is set with --action_env

Output from command
 exec env - \
    PATH=/bin:/usr/bin \
  _bin/build-runfiles

build-runfiles failed: error executing command

**Comment by laszlocsomor** [comment]
@burkpojken : FYI, a workaround for the glibcxx problem is to install OpenJDK 8 and export `JAVA_HOME` to point at it, e.g.:

```
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
```

Re: build-runfiles: do you see with with `bazel run` by any chance? It seems that in that case Bazel won't use the normal action execution machinery to run "build-runfiles", see:
- https://github.com/bazelbuild/bazel/blob/96145511b34a2d7be834e3eb05927674e875c813/src/main/java/com/google/devtools/build/lib/runtime/commands/RunCommand.java#L546
- https://github.com/bazelbuild/bazel/blob/96145511b34a2d7be834e3eb05927674e875c813/src/main/java/com/google/devtools/build/lib/exec/SymlinkTreeHelper.java#L83-L84

I think it's a bug that Bazel even supports running build-runfiles in a plain mode like this. Normally (during a build) Bazel would use the proper execution mechanism that creates a Spawn object and respects `--action_env`. I think the RunCommand should use this method instead: https://github.com/bazelbuild/bazel/blob/96145511b34a2d7be834e3eb05927674e875c813/src/main/java/com/google/devtools/build/lib/exec/SymlinkTreeHelper.java#L108

**Comment by laszlocsomor** [comment]
Assigning to @ulfjack who authored the relevant lines.

**Comment by burkpojken** [comment]
Hmm, not sure it is the reducing the env that made the build time so much shorter, I will have to investigate that more, so ignore that for now.
Sorry

**Comment by laszlocsomor** [comment]
The reduced build time was likely due to caching. Bazel reuses build outputs from previous builds as much as it can.

**Comment by burkpojken** [comment]
Hi! 
From bazel 0.13 and above it is not possible to make build-runfiles use neither the LD_LIBRARY_PATH from the environment or from --action_env=LD_LIBRARY_PATH=/app/vbuild/RHEL6-x86_64/gcc/5.2.0/lib

We cannot use the later versions of bazel now in our environment :(

Preferable for us the environment variables for LD_LIBRARY_PATH and PATH should be used in all actions if --experimental_strict_action_env is not set.

**Comment by ulfjack** [comment]
Sorry about that. I'll send out a fix.

**Comment by burkpojken** [comment]
Working fine in 0.14.0rc4 
Thanks!
