### ISSUE TITLE
clean short circuit actioncache load since 0.9

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#4758]
### Description of the problem / feature request:

clean on new daemon loads actioncache (prior to immediately deleting it)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Under both 0.9 and anything later:

build (has to be significant enough size that startup after shutdown would be noticeable)
shutdown
clean (0.9 will return immediately.  0.10 and later will hang, with no output, while loading the action cache and existing outputs)

### What operating system are you running Bazel on?

Ubuntu 14.04

### What's the output of `bazel info release`?

0.9.0, 0.10.1, 0.11.0...

**Comment by laszlocsomor** [comment]
Are we talking about the local action cache or a remote one?

**Comment by werkt** [comment]
The local action cache.

**Comment by meisterT** [comment]
Doesn't happen with Bazel 3.1 anymore.
