### ISSUE TITLE
Feature request: remote cache: Download only / asymmetric caching

### ISSUE THREAD

**Issue by jgavris** [bazelbuild/bazel#4759]
Feature requests: what underlying problem are you trying to solve with this feature?

Piggybacking on https://github.com/bazelbuild/bazel/issues/4757, when I'm away from the office, I often have very asymmetric bandwidth (residential broadband or 4G tethering). It would be great if I could build with a configuration that only pulls artifacts from the remote cache, and does not push them back up. 

What's the output of bazel info release?
0.11.0

**Comment by buchgr** [comment]
Wouldn't `--remote_upload_local_results=false` work?

**Comment by jgavris** [comment]
🤔Forgot about that one. Thanks!
