### ISSUE TITLE
new_http_archive should doc format of build_file format

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#476]
is it a basename? A directory? A label?

I guess it's basename; in that case, how do we deal with a project with 100 external dependencies; will it have 100 BUILD.foo files in the root of the project?

I tried a label, and it doesn't seem to work (looks like the value is normalized to a path).

hanwen@nienhuys:~/vc/gobaz$ bazel build go/pkg:hello
..........
ERROR: /home/hanwen/vc/gobaz/tools/build_rules/BUILD:2:1: no such package '@go-linux-amd64-toolchain//': In new_http_archive rule //external:go-linux-amd64-toolchain the 'build_file' attribute does not specify an existing file (/tools/build_rules/BUILD.go-toolchain does not exist) and referenced by '//tools/build_rules:toolchain'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 5.757s
hanwen@nienhuys:~/vc/gobaz$ ls tools/build_rules/BUILD.go-toolchain
tools/build_rules/BUILD.go-toolchain
hanwen@nienhuys:~/vc/gobaz$ cp tools/build_rules/BUILD.go-toolchain .

[edit WORKSPACE]

hanwen@nienhuys:~/vc/gobaz$ bazel build go/pkg:hello
ERROR: /home/hanwen/vc/gobaz/go/pkg/BUILD:14:1: Target '//tools/build_rules:toolchain' is not visible from target '//go/pkg:lib'. Check the visibility declaration of the former target if you think the dependency is legitimate.
ERROR: Analysis of target '//go/pkg:hello' failed; build aborted.
INFO: Elapsed time: 2.638s

**Comment by kchodorow** [comment]
This is now documented.
