### ISSUE TITLE
[Feature] `all_files` hierarchy macro

### ISSUE THREAD

**Issue by Androbin** [bazelbuild/bazel#4761]
### Description of the feature request:

Provide an macro `filegroup` target, e.g. `all_files(...)`, which also includes such targets in all sub-modules.

### What underlying problem are you trying to solve with this feature?

Getting rid of `all_files` target hierarchy boilerplate code.
See tensorflow/tensorflow#15758 and tensorflow/tensorflow#16491 for reference.

### Any other information, logs, or outputs that you want to share?

This is thought of as an alternative to #4577.

### Example

```
all_files(
    name = 'all_files' # implied?
    srcs = glob(["**/*"]) # default?
    # data = <computed by macro>
)
```

Shall there be packages `foo`, `foo/bar`, `foo/bar/fizz`, `foo/fizz`, each with such target.
The macro in `foo` would resolve `data` to `foo/bar:all_files` and `foo/fizz:all_files`.
The macro in `foo/bar` would resolve `data` to `foo/bar/fizz:all_files`.

**Comment by Androbin** [comment]
@jart Do you think such macro could be used instead of a separate tool?

**Comment by Androbin** [comment]
@ittaiz Could the Skylark rules use this?

**Comment by ittaiz** [comment]
Yes. It still means we need to annotate all packages but at least not tie them together

**Comment by laszlocsomor** [comment]
@Androbin -- sorry to say this but this feature request is infeasible for the same reason as https://github.com/bazelbuild/bazel/issues/4577 is, see my [comment](https://github.com/bazelbuild/bazel/issues/4577#issuecomment-370419822). Bazel assumes packages are independent of each other.

But you can achieve this outside of Bazel! There's an excellent tool called [Buildozer](https://github.com/bazelbuild/buildtools/tree/master/buildozer) which allows you to bulk-edit BUILD files. You can script against this tool, and it can both create and update rules in BUILD files. So you could write a tool that looks at the source tree, finds the BUILD files, thus determines the package hierarchy, then drives Buildozer to update the BUILD files to have the "all_files" build rules.
