### ISSUE TITLE
Make objc_library copy public headers to a subfolder named after the target name

### ISSUE THREAD

**Issue by dmytrol** [bazelbuild/bazel#4763]
### Description of the problem / feature request:

It would be nice to have the obj_library rule copy the public headers specified in the `hdrs` attribute to a subfolder in genfiles named after the objc_library rule name (or even better, to have a dedicated `library_name` attribute for that purpose)

### Feature requests: what underlying problem are you trying to solve with this feature?

This would make migrating existing xcode projects much easier, because xcode copies public headers of a static library target to a subfolder named after the target name inside the product folder (e.g. release-iphoneos/LibraryName), and source files from other targets in the same project can very well assume this location (e.g. `#import <LibraryName/LibraryName.h>`

### What operating system are you running Bazel on?

MacOS Sierra

### What's the output of `bazel info release`?

0.11.0-homebrew

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Not sure if I can answer this one; as this is a private GtiHub repo.

###  Have you found anything relevant by searching the web?

This is somewhat related to https://github.com/bazelbuild/bazel/issues/306 but I believe is much simpler to implement

### Any other information, logs, or outputs that you want to share?

Specifying public headers in the `hdr` attribute makes Bazel copy them to the package's folder inside genfiles (and this location does get added to the include paths for the dependents), but so far we need to copy the public headers into an appropriate subfolder with the help of a `genrule`.

Probably another possible workaround would be to introduce a dedicated package for the library, but that would complicate things for us because this is a 3rd party library added as a git submodule, and we would like to avoid the hassle related to forking and tracking updates to the submodule.

**Comment by laszlocsomor** [comment]
I think the `genrule`-based approach you are applying is the right way to solve this problem.

For sake of convenience you could introduce a [Skylark macro](https://docs.bazel.build/versions/master/skylark/macros.html) that creates the `objc_library` rule together with the `genrule`, so you could just write `my_objc_library` and the macro would create the right rules.

**Comment by laszlocsomor** [comment]
@aragos please triage this

**Comment by aragos** [comment]
I agree with @laszlocsomor that this is best solved using the genrule + macro approach. 

`objc_library` is complex enough and I'd prefer removing functionality rather than adding more, unless there is no other way to solve a problem. As there is a workaround here I don't think a change to the rule is warranted. 

@sergiocampama in case he has an opinion.
