### ISSUE TITLE
"error: invalid 'asm': invalid operand for code 'w' "  while cross compiling tensorflow for Raspberry Pi 3 using Bazel

### ISSUE THREAD

**Issue by AnchoretBaladev** [bazelbuild/bazel#4765]
### Description of the problem / feature request:

> Trying to Cross Compile Tensorflow using Bazel and getting the below error in the middle of Compilation,
****from /home/baladev/.cache/bazel/_bazel_baladev/da0e175f87e998fe3d550279550cec2c/external/arm_compiler/bin/../lib/gcc/arm-linux-gnueabihf/4.9.3/../../../../arm-linux-gnueabihf/include/c++/4.9.3/cstdlib:72,
                 from tensorflow/core/platform/posix/net.cc:19:
tensorflow/core/platform/posix/net.cc: In function 'bool tensorflow::internal::{anonymous}::IsPortAvailable(int*, bool)':
tensorflow/core/platform/posix/net.cc:60:19: error: invalid 'asm': invalid operand for code 'w'
   addr.sin_port = htons(static_cast<uint16_t>(*port));
                   ^
tensorflow/core/platform/posix/net.cc:75:17: error: invalid 'asm': invalid operand for code 'w'
   actual_port = ntohs(addr.sin_port);**
                 ^
INFO: Elapsed time: 1351.383s, Critical Path: 74.54s
FAILED: Build did NOT complete successfully**

The above error usually occurs, when you were cross-compiling, probably from an x86 or x86_64 host to an ARM target. The error most likely occurred when you used, directly or indirectly, a network byte order translation function from the C library like htons(), or ntohl(), **It means Bazel is not picking up the perfect Compiler Or may be including wrong header files**

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Simply clone Tensorflow and Install Bazel and then run "./tensorflow/tools/ci_build/pi/build_raspberry_pi.sh" from Inside tensorflow directory.

### What operating system are you running Bazel on?

> Ubuntu 16.04LTS

### What's the output of `bazel info release`?

> release 0.8.0

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Its a compiler issue u guess!!! Please help , M stopped here from last 15 days.

**Comment by laszlocsomor** [comment]
You are using Bazel 0.8.0, that is a rather old version. Could you try with the latest release (version 0.11.0)?

**Comment by AnchoretBaladev** [comment]
@laszlocsomor i have tried with Bazel 0.11.0 but the output is still same

**Comment by laszlocsomor** [comment]
@AnchoretBaladev : when you wrote the following:

> The above error usually occurs, when you were cross-compiling, probably from an x86 or x86_64 host to an ARM target. The error most likely occurred when you used, directly or indirectly, a network byte order translation function from the C library like htons(), or ntohl(), It means Bazel is not picking up the perfect Compiler Or may be including wrong header files

...did you copy-paste this from somewhere or are these your own words? If the former, where's the source? I don't know if the compiler Bazel is using is indeed right or wrong, but the person who wrote the text (whether it was you or someone else) may know better than me.

**Comment by mhlopko** [comment]
I'm sorry I don't think this is really a bazel issue.
