### ISSUE TITLE
localjdk's digest includes machine-dependent bits

### ISSUE THREAD

**Issue by gkossakowski** [bazelbuild/bazel#4769]
### Description of the problem / feature request:

Bazel's localjdk target includes files that are machine-dependent and have non-reproducible content. The files that I found problematic are: `classes.jsa` and `cacerts`. Both seem to be a JVM-internal storages that should be excluded from the digest computation.

The non-reproducible content of `classes.jsa` came up with me testing the same bazel build in two Docker container instances: the contents of that file differed and the digest of `localjdk` differs as a result.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

You can see what's included in localjdk with `bazel query 'kind("source file", deps(@local_jdk//:jdk-default))'`. You can read on `classes.jsa` and cacerts in JDK's docs to see these are most likely machine-dependent files.

### What operating system are you running Bazel on?

Linux, MacOS (tested on both)

### What's the output of `bazel info release`?

`release 0.9.0- (@non-git)`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

download the distribution tarball and call `./compile`.

###  Have you found anything relevant by searching the web?

This issue is a spinoff from this issue: https://github.com/bazelbuild/bazel/issues/4714
Earlier discussion of me debugging java rules reproducibility: https://groups.google.com/d/msg/bazel-discuss/5M-QoZ4gPq8/d_y1dEWnAAAJ

### Any other information, logs, or outputs that you want to share?

A comment: tracking down this issue was difficult because bazel doesn't offer logging into what goes into digest computation.

**Comment by gkossakowski** [comment]
Yeah, I'm referring to the computation of the digestKey for the action that point at the local jdk. `bazel dump --action_cache` prints:

```
2, bazel-out/host/internal/_middlemen/external_Slocal_Ujdk_Cjdk-default:
      actionKey =
      usedClientEnvKey = 00000000000000000000000000000000
      digestKey = 2df4b787734c4ed41f36d8181688a1ac
```

The digestKey is different between docker instances due to files I mentioned earlier.

**Comment by gregestren** [comment]
@philwo (who was involved with the current definition of jdk-default): do we have room for more granularity here? (also see the discussion #4714)

**Comment by philwo** [comment]
@cushon is probably the right person to ask here. :)

**Comment by philwo** [comment]
For Bazel, the two are equivalent: "ignore those files when it computes the hash" == "excluding them from the JDK definition".

If they're in the definition and show up using the given `bazel query`, they're part of the input files. There's no mechanism to exclude some of the inputs when computing action cache digests.

Excluding the `classes.jsa` file from the definition should be fine, as it seems to be an optional file that is present on some systems (it's not on my MacBook) just to speed up the startup. If it doesn't exist, the JVM will just not use that particular optimization (according to the docs I read).

@gkossakowski If you use the Bazel version with an embedded JDK, this shouldn't be an issue, right? The embedded JDK doesn't contain a `classes.jsa` file and the `cacerts` file would be the same on each machine.

**Comment by ittaiz** [comment]
could this be causing cache misses on the creation of the **large** platformclasspath target?

**Comment by ckolli5** [comment]
Hey @gkossakowski, could you please confirm if this issue is still existing? Thanks!

**Comment by gkossakowski** [comment]
Sadly, I no longer work with Bazel so can't weight in.

**Comment by ckolli5** [comment]
@gkossakowski - Thanks for the reply.
