### ISSUE TITLE
fetch command should doc how to reboot state

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#477]
I was trying to fiddle with new_http_archive and now got myself in a state where I get 

$ bazel fetch //go/...
..........
ERROR: no such package 'tools/jdk': BUILD file not found on package path.

where does new_http_archive and fetch store state, and how to blow it away cleanly? I saw "clean --expunge" mentioned somewhere. If it is, it should be doc'd on all the repository rules that create state.

**Comment by kchodorow** [comment]
`clean --expunge` is a workaround and should unstick you for now.  I'll add it to the docs until the underlying issue is fixed.

**Comment by kchodorow** [comment]
Closing as obsolete due to f9fdc8dfced8b2b14561720623126a91e04b22cb.
