### ISSUE TITLE
Measure the remote cache hit tracked per rule

### ISSUE THREAD

**Issue by gkossakowski** [bazelbuild/bazel#4776]
### Description of the problem / feature request:

An _easy_ way to measure the remote cache hit tracked per rule. The output should look like:

```
rule name     number of targets     remote cache hit
java_library   1200                           821
...
```

### Feature requests: what underlying problem are you trying to solve with this feature?

Have a global caching health check for bazel builds. This would be used for alerting: if suddenly the cache hits rate drops (e.g. after a bazel upgrade), it most likely means some kind of reproducibility/hermeticitiy problem that needs to be investigated. The health check would be the trigger.

### What operating system are you running Bazel on?

Linux/Mac.

### What's the output of `bazel info release`?

`release 0.9.0- (@non-git)`

###  Have you found anything relevant by searching the web?

No. I think bazel doesn't emit that information in any way.

**Comment by ulfjack** [comment]
I think we have an open bug for basic stats already. I don't think that we were planning to show a breakdown by rule type, but it's something that'd fit into the profile at least.

**Comment by gkossakowski** [comment]
Great to hear it's planned. Do you have a sense when you'll get down to implementing it?

Re: per-rule breakdown: it's very useful for forming a quick guess whether an issue is with home-grown rules or the ones that ship with bazel. These two categories have distinct profiles in terms of risk and how you approach debugging them.

**Comment by gkossakowski** [comment]
And on profiling: the problem is that often cache hit misses will be non-deterministic (in case of a bug) and non-continuous monitoring might have a hard time catching these problems.

**Comment by agoulti** [comment]
I am aimingto implement the basic stats by the end of the month. Current approach would break executions down by type: e.g., show how many were remote, local sandboxed, local non-sandboxed etc. One of those types would be for remote cache hits. From that you should be able to infer cache rate.
The plan is to include this brief summary at the end of every run.

It is not planned to be per-target though.

**Comment by ulfjack** [comment]
It should be pretty easy to do a breakdown by action mnemonic once we have a place where we collect the data.

**Comment by buchgr** [comment]
looking forward to this! cc: @alexeagle

**Comment by buchgr** [comment]
This information is available via --experimental_execution_log_file
