### ISSUE TITLE
NDK r16 missing standard library functions

### ISSUE THREAD

**Issue by etnu** [bazelbuild/bazel#4777]
### Description of the problem / feature request:

When compiling with NDK 16, certain C++ standard library headers fail to locate their C counterparts. For instance:

external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/cmath:321:9: error: no member named 'isless' in the global namespace
using ::isless;
      ~~^
external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/cmath:322:9: error: no member named 'islessequal' in the global namespace
using ::islessequal;
      ~~^
external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/cmath:323:9: error: no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/cmath:324:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/cmath:325:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

file: test.cc

  #include <cmath>

  int main(){}

bazel build  <target> --android_crosstool_top=@androidndk//:toolchain-libcpp --cxxopt='-std=c++14'

### What operating system are you running Bazel on?

linux

### What's the output of `bazel info release`?

development version

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

bazel build //src:bazel

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://bazel.googlesource.com/bazel
babbfdc6cb98a23fe0dadf02d7dc407504e9cac5
babbfdc6cb98a23fe0dadf02d7dc407504e9cac5

###  Have you found anything relevant by searching the web?

nope

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by etnu** [comment]
@jin

**Comment by jin** [comment]
I'm only able to reproduce this with `cmath` so far. Have you stumbled upon this with other headers too?

**Comment by jin** [comment]
Rroot cause: the same sysroot is being used for both compile and link time. The compile time sysroot should be `$ndk/sysroot/usr/include` and link time sysroot `$ndk/platforms/android-$api/arch-$arch`.

**Comment by etnu** [comment]
Not sure, I hit it with cmath as well (I guess markdown ate my example)

**Comment by jin** [comment]
This should be fixed with ebdd92d now.
