### ISSUE TITLE
cc_proto_library does not provide list of built lib files

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/bazel#4779]
### Description of the problem / feature request:

CcSkylarkApiProvider from cc_proto_library always contains an empty list for libs. This prevents us from using the provider to ascertain which libraries need to be linked. An example of how we use the provider is [here](https://github.com/grailbio/rules_r/blob/fe60ad3630cfb56b5166dafea36c5c83f8a38806/R/defs.bzl#L210). The provider does contain expected entries for headers and include directories.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

A simple workspace can be created to demonstrate the bug:

cc_proto_dep.bzl:
```
def _impl(ctx):
    print(ctx.attr.cc_proto_dep.cc.libs)

cc_proto_lib = rule(
    attrs = {
        "cc_proto_dep": attr.label(),
    },
    implementation = _impl,
)
```
BUILD:
```
proto_library(
    name = "a_proto",
    srcs = [":a.proto"],
)

cc_proto_library(
    name = "a_cc_proto",
    deps = [":a_proto"],
)

load(":cc_proto_dep.bzl", "cc_proto_lib")

cc_proto_lib(
    name = "a_cc_lib",
    cc_proto_dep = ":a_cc_proto",
)
```
WORKSPACE:
```
workspace(name = "test")

http_archive(
    name = "com_google_protobuf",
    sha256 = "826425182ee43990731217b917c5c3ea7190cfda141af4869e6d4ad9085a740f",
    strip_prefix = "protobuf-3.5.1",
    urls = [
        "https://github.com/google/protobuf/archive/v3.5.1.tar.gz",
    ],
)
```
a.proto:
```
syntax = "proto3";

message Msg {
  string name = 1;
}
```

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 0.10.1-homebrew

###  Have you found anything relevant by searching the web?

No

**Comment by cgrushko** [comment]
I'll defer to iirina.
