### ISSUE TITLE
Regression in external cc_proto_library after f43df1e29765f75e02838e4139417e914b3ee812

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/bazel#4780]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

After f43df1e29765f75e02838e4139417e914b3ee812
building a cc_proto_library from a remote repo results in an error.

ERROR: /private/var/tmp/_bazel_pmbethe/d03eb8f816153c36c4229eeab3f690b4/external/com_github_pmbethe09_dtac/cards_proto/BUILD:8:1: Generating C++ proto_library @com_github_pmbethe09_dtac//cards_proto:cards_proto failed (Exit 1)
bazel-out/darwin-fastbuild/genfiles/external/com_github_pmbethe09_dtac/: No such file or directory

### Feature requests: what underlying problem are you trying to solve with this feature?

n/a

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

to your WORKSPACE:
git_repository(
    name = "com_github_pmbethe09_dtac",
    commit = "43b2658ce4bfdd22bd8a0845a10d9b86b33e0385",
    remote = "https://github.com/pmbethe09/DTAC.git",
)

bazel build  @com_github_pmbethe09_dtac//cards_proto:cards_proto_cc

### What operating system are you running Bazel on?

OSX

### What's the output of `bazel info release`?

development version

I ran git bisect from HEAD back a few days and it selected
f43df1e29765f75e02838e4139417e914b3ee812
which I confirmed manually

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

bazel build -c opt --stamp //src:bazel

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git@github.com:bazelbuild/bazel.git
3e687ff5988aa6b3fb1582ade1362c80698a86ff
f43df1e29765f75e02838e4139417e914b3ee812

###  Have you found anything relevant by searching the web?

f43df1e29765f75e02838e4139417e914b3ee812
fixed an issue with objc protos, but introduced this new one.

**Comment by pmbethe09** [comment]
Ah, and you will also need protobuf, say 3.5.1. in your WORKSPACE

PROTO_VERS = "3.5.1"
http_archive(
    name = "com_google_protobuf",
    sha256 = "1f8b9b202e9a4e467ff0b0f25facb1642727cdf5e69092038f15b37c75b99e45",
    strip_prefix = "protobuf-" + PROTO_VERS,
    urls = ["https://github.com/google/protobuf/archive/v" + PROTO_VERS + ".zip"],
)

**Comment by c-parsons** [comment]
I'll issue a rollback.

**Comment by mikelikespie** [comment]
I should have a fix for this in the next day or so that makes my change work for both cc_proto_library as well as j2objc's proto library.

I think there's a difference in the codegen plugins where the j2objc one will output.

for protoc ```-Icards_proto/cards.proto=external/com_github_pmbethe09_dtac/cards_proto/cards.proto```

j2objc will output
```
cards_proto/cars.j2objc.pb.h 
```

and the c++ will output
```
external/com_github_pmbethe09_dtac/cards_proto/cards.h
```

**Comment by pmbethe09** [comment]
SGTM.  I am working on an integration test to catch this sort of thing for cc_proto_library

**Comment by meisterT** [comment]
@c-parsons is this still relevant?

**Comment by c-mita** [comment]
Closing for now. If this is still a problem then please reopen.
