### ISSUE TITLE
remote ex builds print error when interrupted

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#4783]
### Description of the problem / feature request:

When interrupted (with Ctrl-C) bazel builds with remote ex print an extra ERROR message before indicating 'build interrupted'

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Interrupt (with Ctrl-C on linux) a build running with active operations in remote execution:

You could see, if compiling C++ for that action, something like the following:

```
ERROR: /my/package/BUILD:18:1: C++ compilation of rule '//my/package:target' failed (Exit 34). Note: Remote connection/protocol failed with: execution failed
ERROR: build interrupted
```

### What operating system are you running Bazel on?

Ubuntu 14.04

### What's the output of `bazel info release`?

release 0.11.0

**Comment by ola-rozenfeld** [comment]
I know what caused this, fixing.
