### ISSUE TITLE
remote/performance: check if blob exists before uploading.

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#4789]
In issue https://github.com/bazelbuild/bazel/issues/4664 @RNabel noticed that Bazel was trying to upload a file to the remote cache that was already there.

Bazel currently doesn't check whether a blob already exists before uploading but maybe it should. I am aware that some files (like the empty file) or java manifest files are uploaded multiple times as many actions produce these artifacts. These files are small however and it might not be worth checking whether a file exists first. We need to investigate (1) how often this happens for different builds (2) how much bandwidth can be saved.

cc: @jgavris @nicolov @RNabel @mmorearty @BenTheElder @alexeagle

**Comment by ola-rozenfeld** [comment]
Note: this only applies to non-grpc remote cache. In gRPC cache, we always check if a blob exists before uploading, in more than one way (GetMissingBlobs, in particular).

**Comment by buchgr** [comment]
@ola-rozenfeld you only do that for inputs though, no? This particular issue is about action outputs.

**Comment by ola-rozenfeld** [comment]
No, I always do it. https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/remote/GrpcRemoteCache.java#L281

**Comment by mpictor** [comment]
> ... I am aware that some files (like the empty file) or java manifest files are uploaded multiple times ...

If a file is zero-length, does it ever make sense to cache it? Seems like the cases where it took considerable time to generate a zero-length file would be few and far between.

Another solution, though a bit more complicated: don't cache things that take less time to generate than  `t`, where `t` is one of the following, user-configurable:
* `t` is calculated as the average cache request-response cycle time seen by bazel, multiplied by a user-configured constant, or
* `t` is specified by the user as some small amount of time (us/ms/s)

**Comment by j3parker** [comment]
RE: my concern about an S3 cache's ability to implement this if there was a stock S3 cache: S3 has since improved their consistency: https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/
