### ISSUE TITLE
changing build_file in new_http_archive yields EEXIST

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#479]
I tried moving around the build_file. Since this touches the WORKSPACE, I thought that might work.

$ bazel fetch go/...
ERROR: /home/hanwen/vc/gobaz/tools/go/toolchain/BUILD:7:1: no such package '@golang-linux-amd64//': Error creating symbolic link from /home/hanwen/.cache/bazel/_bazel_hanwen/932b22c08805e7ceb2fd2b1cd530e147/external/golang-linux-amd64/BUILD to /home/hanwen/vc/gobaz/tools/go/toolchain/BUILD.go-toolchain: /home/hanwen/.cache/bazel/_bazel_hanwen/932b22c08805e7ceb2fd2b1cd530e147/external/golang-linux-amd64/BUILD (File exists) and referenced by '//tools/go/toolchain:go_tool'.

**Comment by hanwen** [comment]
trying to delete things manually under the output root also fails, 

ERROR: /home/hanwen/vc/gobaz/tools/go/toolchain/BUILD:2:1: no such package '@golang-linux-amd64//': Error downloading from https://storage.googleapis.com/golang/go1.5.1.linux-amd64.tar.gz to /home/hanwen/.cache/bazel/_bazel_hanwen/932b22c08805e7ceb2fd2b1cd530e147/external/golang-linux-amd64: Error downloading https://storage.googleapis.com/golang/go1.5.1.linux-amd64.tar.gz to /home/hanwen/.cache/bazel/_bazel_hanwen/932b22c08805e7ceb2fd2b1cd530e147/external/golang-linux-amd64/go1.5.1.linux-amd64.tar.gz: /home/hanwen/.cache/bazel/_bazel_hanwen/932b22c08805e7ceb2fd2b1cd530e147/external/golang-linux-amd64/go1.5.1.linux-amd64.tar.gz (No such file or directory) and referenced by '//tools/go/toolchain:toolchain'.

**Comment by kchodorow** [comment]
This was been fixed by the external repo correctness change a few months ago.
