### ISSUE TITLE
Rule documentation should consistently prefer True/False over 1/0

### ISSUE THREAD

**Issue by defunctzombie** [bazelbuild/bazel#4792]
### Description of the problem / feature request:

The bazel documentation is unclear in the preference of `True` or `False` vs `1` or `0` when dealing the boolean fields.

There are instances in the documentation where a boolean type field indicates a value of `1` is true and other pages of the documentation that describe the `bool` type and indicate that `True` and `False` are the value values.

The Skylark language spec indicates that booleans are `True` and `False` but allows for other values to represent truthiness and falsiness
https://github.com/google/skylark/blob/master/doc/spec.md#booleans

### Feature requests: what underlying problem are you trying to solve with this feature?

Consistency and clarity in documentation so those new to the platform know which values are supported.

###  Have you found anything relevant by searching the web?

Only the above referenced language spec.

**Comment by defunctzombie** [comment]
Related issue: https://github.com/bazelbuild/buildtools/issues/114 and mine is likely considered a duplicate.

**Comment by laszlocsomor** [comment]
> There are instances in the documentation where a boolean type field indicates a value of 1 is true and other pages of the documentation that describe the bool type and indicate that True and False are the value values.

Could you link to examples? In rule documentation I see "default is {0,1}" in abundance but not "default is {true,false}" [2].

---

[1] [inurl:docs.bazel.build "default is 1"](https://www.google.de/search?rlz=1C1GCEA_enDE775DE775&ei=6e-gWuaeGcONkgWjt7n4Bw&q=inurl%3Adocs.bazel.build+%22default+is+1%22&oq=inurl%3Adocs.bazel.build+%22default+is+1%22&gs_l=psy-ab.3...1637.1637.0.2309.1.1.0.0.0.0.94.94.1.1.0....0...1.1.64.psy-ab..0.0.0....0.bwHRsm2RbZc)
[inurl:docs.bazel.build "default is 0"](https://www.google.de/search?rlz=1C1GCEA_enDE775DE775&ei=7--gWtGnAcSXsAf-qK3wBQ&q=inurl%3Adocs.bazel.build+%22default+is+0%22&oq=inurl%3Adocs.bazel.build+%22default+is+0%22&gs_l=psy-ab.3...901.901.0.1142.1.1.0.0.0.0.52.52.1.1.0....0...1.1.64.psy-ab..0.0.0....0.aoCZRQE9FcA)

[2] [inurl:docs.bazel.build "default is true"](https://www.google.de/search?q=inurl%3Adocs.bazel.build+%22default+is+true%22&rlz=1C1GCEA_enDE775DE775&oq=inurl%3Adocs.bazel.build+%22default+is+true%22&aqs=chrome..69i57j69i58.478j0j1&sourceid=chrome&ie=UTF-8)
[inurl:docs.bazel.build "default is false"](https://www.google.de/search?rlz=1C1GCEA_enDE775DE775&ei=4e-gWte9EZC5kwWrgJOoDg&q=inurl%3Adocs.bazel.build+%22default+is+false%22&oq=inurl%3Adocs.bazel.build+%22default+is+false%22&gs_l=psy-ab.3...1323.2423.0.2554.9.7.2.0.0.0.126.514.6j1.7.0....0...1.1.64.psy-ab..1.0.0....0.uGffBXGTYoI)

**Comment by defunctzombie** [comment]
As noted in the PR description; the examples in the documentation itself use 0, 1 however the language spec uses True and False. Additionally; the examples in the documentation describe many of the fields where 0 or 1 is used as Boolean type. The documentation notes that Boolean type is True or False.

---

Related to the above; I semantically comprehend using True and False faster over 0 or 1 (which is more of a c-ism) and want to express the recommendation that documentation using Boolean type fields be updated to use True and False in the examples.

**Comment by laurentlb** [comment]
We've recently updated some of the documentation (cc @lberki). `False/True` are now preferred to `0/1`.

We originally started using `0` and `1` inside Google because we were using Python and it didn't have `True` and `False` at that time. We should now update the documentation.

**Comment by brandjon** [comment]
> The Skylark language spec indicates that booleans are True and False but allows for other values to represent truthiness and falsiness

FYI, the boolean attribute type [expects](https://github.com/bazelbuild/bazel/blob/9a02760e732632671ddde48ab841b9b0ab788e67/src/main/java/com/google/devtools/build/lib/packages/Type.java#L407-L421) its argument to be either True, False, 1, or 0. It does not admit arbitrary Starlark values the way that an if statement does; for that it'd need to call [`Starlark.truth()`](https://github.com/bazelbuild/bazel/blob/9a02760e732632671ddde48ab841b9b0ab788e67/src/main/java/net/starlark/java/eval/Starlark.java#L194-L208). (I don't think that's a change that should be made, though.)
