### ISSUE TITLE
Bazel j2obc WORKSPACE sha is invalid

### ISSUE THREAD

**Issue by afking** [bazelbuild/bazel#4801]
### Description of the problem / feature request:

Bazels j2obc WORKSPACE file sha is different to the githubs release https://github.com/bazelbuild/bazel/blob/master/WORKSPACE#L39 .

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Running `bazel fetch @bazel_j2objc//...` outputs:

```sh
ERROR: Error downloading [https://github.com/google/j2objc/releases/download/2.0.3/j2objc-2.0.3.zip] to /private/var/tmp/_bazel_edwardmcfarlane/337d342990a69aca0642298fdb696d05/external/bazel_j2objc/j2objc-2.0.3.zip: Checksum was a36bac432d0dbd8c98249e484b2b69dd5720afa4abb58711a3c3def1c0bfa21d but wanted 529ee99e6f0e3f88edef61aeae4f13dc6e5eb8183993ced191338422b0e1fbeb
Building: no action
```

### What operating system are you running Bazel on?

Mac, installed via brew.

### What's the output of `bazel info release`?

`release 0.10.0-homebrew`

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
```sh
git@github.com:afking/bazel.git
d3e102c9fb62f4416099dc9f097a5f207aa7d442
d3e102c9fb62f4416099dc9f097a5f207aa7d442
```

**Comment by laszlocsomor** [comment]
Hm, you're right, I just downloaded the zip file and computed sha256 on it, getting `a36bac432d0dbd8c98249e484b2b69dd5720afa4abb58711a3c3def1c0bfa21d`. /cc @kstanger

**Comment by philwo** [comment]
Any idea why the hash changed?

**Comment by laszlocsomor** [comment]
They may have force-pushed a new version.
This is what @kstanger wrote to me:

> It's possible that the github zip got updated to fix a bug or something. Feel free to update the checksum.
