### ISSUE TITLE
Android NDK mips64 linking is broken from r13 and higher

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#4807]
This occurs with released Bazel versions that support r13 and higher. Trying to build any Android-transitioned `cc_*` target and targeting `mips64` will cause `ld` to crash:

```
$ gbazel build //examples/android/java/bazel:hello_world --fat_apk_cpu=mips64,mips
.........
INFO: Analysed target //examples/android/java/bazel:hello_world (30 packages loaded).
INFO: Found 1 target...
ERROR: /usr/local/google/home/jingwen/code/crosstool/examples/android/java/bazel/BUILD:12:1: Linking of rule '//examples/android/java/bazel:hello_world' failed (Exit 1)
external/androidndk/ndk/toolchains/mips64el-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/mips64el-linux-android/4.9.x/../../../../mips64el-linux-android/bin/ld: cannot find crtbegin_so.o: No such file or directory
external/androidndk/ndk/toolchains/mips64el-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/mips64el-linux-android/4.9.x/../../../../mips64el-linux-android/bin/ld: cannot find -ldl
external/androidndk/ndk/toolchains/mips64el-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/mips64el-linux-android/4.9.x/../../../../mips64el-linux-android/bin/ld: cannot find -lc
external/androidndk/ndk/toolchains/mips64el-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/mips64el-linux-android/4.9.x/../../../../mips64el-linux-android/bin/ld: cannot find -ldl
external/androidndk/ndk/toolchains/mips64el-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/mips64el-linux-android/4.9.x/../../../../mips64el-linux-android/bin/ld: cannot find crtend_so.o: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //examples/android/java/bazel:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.443s, Critical Path: 0.40s
FAILED: Build did NOT complete successfully
```

The missing libraries are in `%mips64_sysroot%/usr/lib64`. From r12 to r13, the contents of `%mips64_sysroot%/usr/lib` were removed, leaving the folder empty. During link time, `ld` goes through search paths in the sysroot. For some reason, because `%mips64_sysroot%/usr/lib` is empty, `ld` assumes that the required libraries don't exist, and doesn't look further into `%mips64_sysroot%/usr/lib64`. This causes the crash.

An ugly workaround is to create a dummy file in `%mips64_sysroot%/usr/lib` to ensure `ld` searches `%mips64_sysroot%/usr/lib64`. This can be added into the `fetch` logic of `AndroidNdkRepositoryFunction`, but considering that `external/android/ndk/` is __symlinked__ to the local NDK folder, the dummy file will mutate the users' NDK directory.

The ideal workaround involves figuring out why `ld` is not looking into `%mips64_sysroot%/usr/lib64` if `%mips64_sysroot%/usr/lib` is empty, and change that behavior. We should not need to modify the NDK structure for this.

cc @ahumesky @aj-michael

**Comment by jin** [comment]
Marking this as P2 since it has been out for a while and we haven't seen anyone report this issue.

**Comment by aj-michael** [comment]
Demoting to P4 because Android NDK is deprecating MIPS:

https://developer.android.com/ndk/guides/mips.html

Also, I went into the play store console and filtered the device catalog by architecture. It shows that there are three known devices that use mips and none that use mips64. Furthermore, the three mips devices seem to be uncertified, user-registered device models. Device names: gs701b, NV310WAC and olleh

So, I don't think this is actually worth our time to fix

**Comment by jin** [comment]
SGTM.

**Comment by jin** [comment]
Will not be fixing this, since MIPS is deprecated.
