### ISSUE TITLE
standalone test strategy counts scheduling time against reported test processing time

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#4808]
```
$ cat BUILD
sh_test(
   name = 'sleepy-test',
   srcs = ['sleepy-test.sh'],
   size = 'small',
)
$ cat sleepy-test.sh
#!/bin/bash
sleep 5s
$ bazel test --runs_per_test 5 --local_test_jobs 1 :sleepy-test
INFO: Analysed target //:sleepy-test (0 packages loaded).
INFO: Found 1 test target...
Target //:sleepy-test up-to-date:
 bazel-bin/sleepy-test
INFO: Elapsed time: 25.943s, Critical Path: 25.66s
//:sleepy-test                                                           PASSED in 25.6s
 Stats over 5 runs: max = 25.6s, min = 5.1s, avg = 15.4s, dev = 7.3s

Executed 1 out of 1 test: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
INFO: Build completed successfully, 6 total actions
```

As you can see, the test timing stats are bogus, and I certainly don't deserve a warning about suspect incorrect timeouts.

The cause is that `StandaloneTestStrategy` reports the total time to schedule and execute the underlying spawn for both the `test_process_times` and `run_duration_millis` `TestResultData` fields. With the advent of `SpawnResult`, it should possible to extricate the true execution time of the test for reporting.

**Comment by laszlocsomor** [comment]
Assigning it to @aehlig, though frankly I doubt it's a UI bug. Klaus, if you're super busy, feel free to reassign (to me I guess).

@benjaminp , thanks for the detailed bug report! I don't think anybody owns this area, so if you happen to want to contribute a PR to fix it, I'd be happy to review. Otherwise I'm afraid this won't get fixed soon. :(

**Comment by aehlig** [comment]
I'm pretty sure it has nothing to do with the UI. The numbers come, as the original bug report reported correctly, from the respective test strategy. As @ulfjack is currently refactoring related code, he is probably the best person to look at. But it still might be low priority.

**Comment by ulfjack** [comment]
We first need to make sure all spawn runners capture wall time in all cases.

**Comment by ulfjack** [comment]
Unfortunately, I'm not going to be able to work on this, although it might fall out of other work I may be doing.

**Comment by aiuto** [comment]
Giving to LocalExecution team on the grounds that they are closest to all strategy selection.

**Comment by jmmv** [comment]
I gave this a try now and I seem to be getting correct timings both with the sandboxed strategy and the standalone strategy:

```
INFO: 10 processes: 10 linux-sandbox.
INFO: Build completed successfully, 6 total actions
//pkg:pkg2                                                               PASSED in 5.1s
  Stats over 5 runs: max = 5.1s, min = 5.1s, avg = 5.1s, dev = 0.0s
```

and

```
INFO: 10 processes: 10 local.
INFO: Build completed successfully, 6 total actions
//pkg:pkg2                                                               PASSED in 5.0s
  Stats over 5 runs: max = 5.0s, min = 5.0s, avg = 5.0s, dev = 0.0s
```
