### ISSUE TITLE
Platform-specific master bazel.rcs

### ISSUE THREAD

**Issue by samertm** [bazelbuild/bazel#4809]
### Description of the problem / feature request:

Add platform-specific bazel.rc. E.g. when Bazel runs on a Windows host, it will load tools/bazel-windows.rc and tools/bazel.rc, running on Linux will load tools/bazel-linux.rc and tools/bazel.rc, etc.

### Feature requests: what underlying problem are you trying to solve with this feature?

On Windows, I need to build with the option "--output_user_root=C:/tmp" to avoid long path issues, but I can't put that in "tools/bazel.rc" because then any builds I do from Linux or macOS will try to build in "C:/tmp" in the workspace root.

### What operating system are you running Bazel on?

Windows, macOS, and Linux

### What's the output of `bazel info release`?

release 0.11.0

###  Have you found anything relevant by searching the web?

I've found others hitting the same issue.

https://stackoverflow.com/questions/48159516/default-platform-specific-bazel-flags-in-bazel-rc
https://groups.google.com/forum/#!topic/bazel-discuss/Jd14TyAXlTM

**Comment by laszlocsomor** [comment]
@lfpino : WDYT?

**Comment by lfpino** [comment]
@cvcal and @aj-michael can probably say more about this than me.

**Comment by cvcal** [comment]
I'm trying to address the variety of bazelrc concerns in  https://github.com/bazelbuild/bazel/issues/4502#issuecomment-372697374. The "global" rc should allow platform-specific flags to be kept separate from the workspace-level options that are the same regardless of platform. /etc/ would be where this path lives for linux, but will be modifiable for other platforms using preprocessor macros (our windows binary would have some appropriate pat, hoping @laszlocsomor has some input on what that should be.)

I think this would address underlying issue, even if it doesn't follow the feature request's solution exactly. Could you confirm?

**Comment by samertm** [comment]
That would be a reasonable workaround, though Windows doesn't have a system-wide Bazel path defined yet: https://github.com/bazelbuild/bazel/blob/f74f9fecbdcccd49dbc4b8924a9aac7f913c7702/src/main/cpp/blaze_util_windows.cc#L232

Assuming we add a Windows path there, then we can require our Windows devs to set their config up correctly.

**Comment by cvcal** [comment]
Well, yes, I'm not saying this is possible at the moment, otherwise the other issue wouldn't be open. It sounds like we agree that the work proposed in issue #4502 will address the platform-specific concern mentioned here, so I'll close this as duplicate. Thank you!

**Comment by laszlocsomor** [comment]
For Windows, I think [`SHGetKnownFolderPath`](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762188(v=vs.85).aspx)`(`[`FOLDERID_ProgramData`](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378457(v=vs.85).aspx)`, ...)` would work well.
