### ISSUE TITLE
Sandbox segfaults on centos 7 + kernel 4.2.1-1.el7.elrepo.x86_64

### ISSUE THREAD

**Issue by pedrokiefer** [bazelbuild/bazel#481]
When I compile something that uses the sandbox, ie. bazel itself, or something using like a genrule calling bison, it segfaults.

Using centos 7 default kernel this problem goes away as it doesn't support sandboxing.

/var/log/messages:
```
[ 3179.268468] namespace-sandb[3172]: segfault at 20 ip 00000000004026d7 sp 00007fff99175d60 error 4 in namespace-sandbox[400000+6000]
[ 3179.858715] namespace-sandb[3186]: segfault at 20 ip 00000000004026d7 sp 
00007ffe278a2140 error 4 in namespace-sandbox[400000+6000]
[ 3493.910197] namespace-sandb[4784]: segfault at 20 ip 00000000004026d7 sp 00007ffc2383f520 error 4 in namespace-sandbox[400000+6000]
[ 3736.277676] namespace-sandb[6220]: segfault at 20 ip 00000000004026d7 sp 00007ffe45e156b0 error 4 in namespace-sandbox[400000+6000]
[ 3736.352874] namespace-sandb[6221]: segfault at 20 ip 00000000004026d7 sp 00007ffdc5d453c0 error 4 in namespace-sandbox[400000+6000]
[ 3736.380757] namespace-sandb[6223]: segfault at 20 ip 00000000004026d7 sp 00007fffb160fa20 error 4 in namespace-sandbox[400000+6000]
[ 3763.379429] namespace-sandb[6912]: segfault at 20 ip 0000556b535a8983 sp 00007ffddaf588e0 error 4 in namespace-sandbox[556b535a6000+6000]
```

**Comment by hanwen** [comment]
I don't think we have easy access to this platform. Could you try to see where the crash is coming from? You could try adding some printf statements to see where it dies approximately.

**Comment by pedrokiefer** [comment]
How can I invoke / debug the sandbox? I don't see any kind of tests on `src/main/tools/BUILD` or files. Any easy way of running it on gdb?

**Comment by hanwen** [comment]
there is a --sandbox_debug flag. Does that help?

**Comment by philwo** [comment]
You can manually run the sandbox runner like this (where /tmp/bazel contains a current pull from Bazel HEAD):

philwo@philwo:/tmp/bazel$ src/main/tools/
philwo@philwo:/tmp/bazel/src/main/tools$ gcc -std=gnu99 -o namespace-sandbox namespace-sandbox.c process-tools.c -lm
philwo@philwo:/tmp/bazel/src/main/tools$ mkdir /tmp/sandbox
philwo@philwo:/tmp/bazel/src/main/tools$ ./namespace-sandbox -S /tmp/sandbox -M /bin -M /lib -M /lib64 -D -- /bin/bash
src/main/tools/namespace-sandbox.c:587: sandbox root is /tmp/sandbox
src/main/tools/namespace-sandbox.c:589: working dir is / (default)
src/main/tools/namespace-sandbox.c:282: unshare succeeded after 1 tries
src/main/tools/namespace-sandbox.c:400: createdir: /usr/local/google/home/philwo
src/main/tools/namespace-sandbox.c:400: createdir: /nonexistent
src/main/tools/namespace-sandbox.c:416: mount: /bin
src/main/tools/namespace-sandbox.c:416: mount: /lib
src/main/tools/namespace-sandbox.c:416: mount: /lib64
src/main/tools/namespace-sandbox.c:524: arg: /bin/bash
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
bash-4.3$ echo hello
hello
bash-4.3$ exit

**Comment by pedrokiefer** [comment]
Running with gdb:
```
gdb --args ./namespace-sandbox -S /tmp/sandbox -M /bin -M /lib -M /lib64 -D -- /bin/bash
```

I get the following backtrace:
```
0x0000000000402d1d in SetupDirectories (opt=0x7fffffffe250) at namespace-sandbox.c:482
482	  char *homedir = getpwuid(getuid())->pw_dir;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-106.el7_2.1.x86_64
(gdb) bt full
#0  0x0000000000402d1d in SetupDirectories (opt=0x7fffffffe250) at namespace-sandbox.c:482
        homedir_from_env = 0x7fffffffef00 "/root"
        homedir = 0x4058ff "/"
#1  0x0000000000403ad1 in main (argc=12, argv=0x7fffffffe3b8) at namespace-sandbox.c:704
        opt = {timeout_secs = 0, kill_delay_secs = 0, stdout_path = 0x0, stderr_path = 0x0, args = 0x7fffffffe410, sandbox_root = 0x608170 "/tmp/sandbox", 
          working_dir = 0x0, mount_sources = 0x608010, mount_targets = 0x608080, mount_map_sizes = 12, num_mounts = 3, create_dirs = 0x6080f0, num_create_dirs = 1, 
          fake_root = 0, create_netns = 0}
        uid = 0
        gid = 0
```

So, geteuid() is returning __65534__, but centos uses uid 99 as nobody and 65534 is undefined, so getpwuid returns `NULL` and we have a segfault. I've changed the uid for nobody just for testing, and I get pass this issue. Now it fails trying to create `/` directory, which makes perfect sense, as nobody has `/` as its home directory. Changing it to `/nonexistent` (or anything else) and I have the sandbox working. 

Changes needed in the code to work with centos:
# Query nobody uid and gid.
# Check if homedir is `/`and don't create a directory in the sandbox.
# Check if getpwuid is not NULL

Time permitting I can post a PR with those changes.

**Comment by philwo** [comment]
Thanks for investigating, @pedrokiefer! I completely agree with you, your proposed changes should be made. I can have a look tomorrow, but would also gladly review & merge a PR.

**Comment by pedrokiefer** [comment]
@philwo can you review my patch? https://bazel-review.googlesource.com/#/c/2650/

**Comment by philwo** [comment]
I think this is fixed, so I'm closing this. Please feel free to reopen if this is still an issue.
