### ISSUE TITLE
Windows: Bazel should be able to build non-c++ rules when VC is not installed correctly

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#4813]
Bazel currently can ignore VC configuration if VC isn't installed at all. But a wrong VC installation could block the configuration even when we don't need to build C++ rules.
See https://github.com/bazelbuild/migration-tooling/issues/85

**Comment by davido** [comment]
I agree with this approach but I would also mention that it could be hard to try to detect/ignore all possible currupted MSVC installations. And in context of another C++ based project: LibreOffice, we generally advice developers to always avoid messing around with multiple MSVC installations on the same Windows machine/VM. And we always tweaking this detection/ckecing machinery: https://github.com/LibreOffice/core/blob/master/configure.ac#L3176-L3305.
