### ISSUE TITLE
java.lang.IllegalAccessException when calling path methods in a repository_rule ctx

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#4822]
### Description of the problem / feature request:

In a `repository_rule` implementation, calling methods on a `path` resolved by `repository_ctx.path()` throws an `IllegalAccessException`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In `repro.bzl`,

```
def _repro_impl(rctx):
  fpath = rctx.path("file")
  print(fpath)
  if not fpath.exists():
    print("File doesn't exist!")

repro = repository_rule(
    implementation = _repro_impl,
    attrs = {},
)
```

In `WORKSPACE`,

```
load(":repro.bzl", "repro")

repro(name = "repro")
```

Then, run `bazel fetch @repro//...`. This should throw:

```
Extracting Bazel installation...
..............
DEBUG: /Users/jin/Code/ndks/repro.bzl:4:3: $output_base/external/repro/file
ERROR: method invocation failed: java.lang.IllegalAccessException: Class com.google.devtools.build.lib.syntax.FuncallExpression can not access a member of class com.google.devtools.build.lib.bazel.repository.skylark.SkylarkPath with modifiers "public"
Building: no action
```

### What operating system are you running Bazel on?

macOS High Sierra.

### What's the output of `bazel info release`?

Tested with both Bazel at 7e50ced9bb59b4ab445edd7904bf31601fd2cea0 and 0.11.1. 

###  Have you found anything relevant by searching the web?

Not to this problem. I'm not sure whether this is WAI, but if it is, maybe it can be abstracted away as an error at the Skylark language level?

**Comment by jin** [comment]
cc @laurentlb

**Comment by jin** [comment]
@laurentlb @brandjon any ideas?

**Comment by brandjon** [comment]
Hm. Apparently path.exists is a boolean, not a function that returns a boolean. (Though you could be forgiven for missing that when reading its doc.)

https://source.bazel.build/bazel/+/2410e1ab3e035382abe519003c618271a69a7b8e:src/main/java/com/google/devtools/build/lib/bazel/repository/skylark/SkylarkPath.java;l=102?q=skylarkpath.java

You should use it without trying to call it. But that's no excuse for the crash. Assigning to @c-parsons since it's @SkylarkCallable related.

**Comment by jin** [comment]
@brandjon oops, thanks! Yes, a more helpful Skylark error will be useful.

**Comment by brandjon** [comment]
This has since been fixed. Current error message for trying to call `exists()` is:

```
Error: 'bool' object is not callable
```
