### ISSUE TITLE
Bazel does not forward cc_binary arguments to the .stripped target 

### ISSUE THREAD

**Issue by driveraid** [bazelbuild/bazel#4827]
### Description of the problem / feature request:

Bazel does not forward arguments specified in the `cc_binary` `args` parameter in the implicit stripped target.

### Feature requests: what underlying problem are you trying to solve with this feature?

Easily deploy production binaries containing specified arguments.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`touch WORKSPACE`

BUILD:
```
cc_binary(
    name = "bin",
    args = ["first_argument"],
    srcs = ["main.cc"]
)
```

main.cc:
```
#include <iostream>

int main(int argc, char** argv)
{
    std::cout << "Number of args: " << argc << std::endl;
    return 0;
}
```

Terminal output from running normal and stripped versions. I expected both versions to return *2* in argc.
```
StrippedProblem 🤙  $ bazel run bin
INFO: Analysed target //:bin (0 packages loaded).
INFO: Found 1 target...
Target //:bin up-to-date:
  bazel-bin/bin
INFO: Elapsed time: 0.145s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action

INFO: Running command line: bazel-bin/bin first_argument
Number of args: 2
StrippedProblem 🤙  $ bazel run bin.stripped
INFO: Analysed target //:bin.stripped (0 packages loaded).
INFO: Found 1 target...
Target //:bin.stripped up-to-date:
  bazel-bin/bin.stripped
INFO: Elapsed time: 1.062s, Critical Path: 0.92s
INFO: Build completed successfully, 2 total actions

INFO: Running command line: bazel-bin/bin.stripped
Number of args: 1
StrippedProblem 🤙  $ 
```
### What operating system are you running Bazel on?

Mac, Linux

### What's the output of `bazel info release`?

release 0.11.1-homebrew
release 0.11.0

###  Have you found anything relevant by searching the web?

No.

**Comment by mhlopko** [comment]
I didn't even know we have `args` attribute :)
