### ISSUE TITLE
bazel can't build tensorflow successfully

### ISSUE THREAD

**Issue by LanYangXiXi** [bazelbuild/bazel#4828]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

I use bazel 0.11.0 to build tensorflow 1.3.0, but it comes 

ERROR: /home/nvidia/.cache/bazel/_bazel_nvidia/d2751a49dacf4cb14a513ec663770624/external/io_bazel_rules_closure/closure/stylesheets/closure_css_library.bzl:27:13: The function 'set' has been removed in favor of 'depset', please use the latter. You can temporarily refer to the old 'set' constructor from unexecuted code by using --incompatible_disallow_uncalled_set_constructor=false
ERROR: /home/nvidia/.cache/bazel/_bazel_nvidia/d2751a49dacf4cb14a513ec663770624/external/io_bazel_rules_closure/closure/stylesheets/closure_css_binary.bzl:65:13: The function 'set' has been removed in favor of 'depset', please use the latter. You can temporarily refer to the old 'set' constructor from unexecuted code by using --incompatible_disallow_uncalled_set_constructor=false
ERROR: /home/nvidia/.cache/bazel/_bazel_nvidia/d2751a49dacf4cb14a513ec663770624/external/io_bazel_rules_closure/closure/filegroup_external.bzl:23:16: The function 'set' has been removed in favor of 'depset', please use the latter. You can temporarily refer to the old 'set' constructor from unexecuted code by using --incompatible_disallow_uncalled_set_constructor=false
ERROR: /home/nvidia/.cache/bazel/_bazel_nvidia/d2751a49dacf4cb14a513ec663770624/external/io_bazel_rules_closure/closure/testing/phantomjs_test.bzl:31:10: The function 'set' has been removed in favor of 'depset', please use the latter. You can temporarily refer to the old 'set' constructor from unexecuted code by using --incompatible_disallow_uncalled_set_constructor=false
ERROR: /home/nvidia/.cache/bazel/_bazel_nvidia/d2751a49dacf4cb14a513ec663770624/external/io_bazel_rules_closure/closure/webfiles/web_library.bzl:43:14: The function 'set' has been removed in favor of 'depset', please use the latter. You can temporarily refer to the old 'set' constructor from unexecuted code by using --incompatible_disallow_uncalled_set_constructor=false
ERROR: error loading package '': Extension 'closure/stylesheets/closure_css_library.bzl' has errors
ERROR: error loading package '': Extension 'closure/stylesheets/closure_css_library.bzl' has errors
INFO: Elapsed time: 6.423s
FAILED: Build did NOT complete successfully (0 packages loaded)

Running on my JetsonTX2, ubuntu 16.0.4, cuda8.0, cudnn6

So, what should I do? update tensorflow version or uninstall bazel 0.10.0? and how to uninstall bazel completely? Thx

**Comment by meteorcloudy** [comment]
@LanYangXiXi Yes, you should choose a newer version of TensorFlow or use an older version of Bazel.
Bazel is just a binary on your machine. If you installed bazel via `sudo apt-get install bazel`, you can do `sudo apt-get remove bazel`, otherwise just delete the Bazel binary.

**Comment by MikoyChinese** [comment]
There are two ways to solve this problem. First, congratulate you never see the problem about"bazel version 0.4.5 > version, but was 0.11.1.", and if you have this problem, you can change like this #4834[https://github.com/bazelbuild/bazel/issues/4834]. And refer to your problem now, I met the same problem. And I solved this just build it again, I think it is just the network problem, so you can build it in the morning or another time. Good luck to you. So relex, and choose another time to build it. And you can try now to build it again.

**Comment by MikoyChinese** [comment]
And if you are just interested in installing tensorflow 1.3.0 , here a wheel file you can install just like pip install. url[https://github.com/jetsonhacks/installTensorFlowJetsonTX]. It is for Jetson TX.

**Comment by LanYangXiXi** [comment]
really thx，I have fix the problems and installed TensorFlow 1.3.0 in Jetson
TX2 successfully, later I’ll try to install the latest version of
TensorFlow, and thank you.

**Comment by MikoyChinese** [comment]
Thx, can you show how you fix the problem about this issue? My way is just building it again. If you wanna install the lastest version of Tensorflow, I have a wheel which I built successfully. contact me email [ emailmikoy@163.com ], then on the next Monday I will send you this file . Or you wanna build it yourself, then I will write a document about to install it and some problem I met.

**Comment by LanYangXiXi** [comment]
Bazel 0.11 can not build TensorFlow 1.3.0 successfully so I use Bazel 0.5.2
and it works. And notice, Jdk version should be 121, otherwise Bazel could
not be built.

**Comment by MikoyChinese** [comment]
Here is my document to build Tensorflow1.5.0. 
http://note.youdao.com/noteshare?id=3779eaea012bfec0fd1dc3e6b27a2b62
Another web:
https://www.jianshu.com/p/d53d231e8cf0

**Comment by LanYangXiXi** [comment]
好的，学习了，我之前装1.5.0也遇到了同样的bazel问题，我以为是版本不支持就没有再尝试了

**Comment by shuyu0815** [comment]
@LanYangXiXi 

Can you show how to install Bazel 0.5.2 with lower Jdk version ?
I don't know how to change the compiler.sh (in bazel-0.5.2-dist)to get the lower Jdk version when installing bazel 0.5.2

Thank you very much !

**Comment by tianyufang1958** [comment]
Just add --incompatible_disallow_uncalled_set_constructor=false in the command line then the error get passed.

**Comment by PanJinquan** [comment]
Which file needs to be changed?
“ If you get the error : Closure Rules requires Bazel >=0.4.5 but was 0.11.1 , see like this bazel#4834. Change all the error file the version 0.4.5 to 0.0.0. Then you will build it successfully.”
Which file should I change?

**Comment by MikoyChinese** [comment]
> Which file needs to be changed?
> “ If you get the error : Closure Rules requires Bazel >=0.4.5 but was 0.11.1 , see like this bazel#4834. Change all the error file the version 0.4.5 to 0.0.0. Then you will build it successfully.”
> Which file should I change?

Sorry about my late replying.
I think that when you get the error, it will show the error file path and the line numbers. And you can change it bigger than 0.4.5. Or you can try the tianyufang1958's answer.
Good luck for you.
