### ISSUE TITLE
How can I gdb tfcompile by using bazel build?

### ISSUE THREAD

**Issue by xcv9685** [bazelbuild/bazel#4829]
tfcompile is a binary file to compile an inference graph into executable code for tensorflow XLA which created by bazel build.
If I want to gdb tfcompile file on ubuntu 16.04, it will return message

    Reading symbols from /PWD/tfcompile...(no debugging symbols found)...done.

It seem that should make bazel compile with something flag like -g?
I have tried to use

    bazel build XXX --compilation_mode=dbg
but there seems not change anything.

How can I resolve this question?

by the way , I'm working on Ubuntu 16.04, bazel version 0.8.1 tensorflow r1.0

Thanks for any help!

**Comment by buchgr** [comment]
Can you please ask this question on SO or on our mailinglist and we are happy to answer it there. That way many more users can benefit from the answer. Thanks!

**Comment by George35mk** [comment]
I have the same problem on windows, I have scanned the entire web, nothing. why you advertise the bazel if you can't include the symbols for the **gdb**.
