### ISSUE TITLE
"bazel build -c dbg //tensorflow/core/kernels:matmul_op_test"  occur error

### ISSUE THREAD

**Issue by xzy256** [bazelbuild/bazel#4834]
I executed `bazel build -c dbg //tensorflow/core/kernels:matmul_op_test` ,  i got error . My bazel version is `0.11.1`, it is bigger than `0.4.5`. Why do i get error `Closure Rules requires Bazel >=0.4.5 but was 0.11.1`? The log trace as follow.

> xzy@xzy-ThinkPad-S2:~/tensorflow$ bazel build -c dbg //tensorflow/core/kernels:matmul_op_test
> Extracting Bazel installation...
> ............
> ERROR: /home/xzy/tensorflow/WORKSPACE:15:1: Traceback (most recent call last):
> 	File "/home/xzy/tensorflow/WORKSPACE", line 15
> 		closure_repositories()
> 	File "/home/xzy/.cache/bazel/_bazel_xzy/c01fa588a238f7be12b727d5cfbf1a03/external/io_bazel_rules_closure/closure/repositories.bzl", line 69, in closure_repositories
> 		_check_bazel_version("Closure Rules", "0.4.5")
> 	File "/home/xzy/.cache/bazel/_bazel_xzy/c01fa588a238f7be12b727d5cfbf1a03/external/io_bazel_rules_closure/closure/repositories.bzl", line 172, in _check_bazel_version
> 		fail(("%s requires Bazel >=%s but was...)))
> Closure Rules requires Bazel >=0.4.5 but was 0.11.1
> ERROR: Error evaluating WORKSPACE file
> ERROR: Skipping '//tensorflow/core/kernels:matmul_op_test': error loading package 'external': Package 'external' contains errors
> WARNING: Target pattern parsing failed.
> ERROR: error loading package 'external': Package 'external' contains errors
> INFO: Elapsed time: 6.145s
> FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by MikoyChinese** [comment]
This the error of Tensorflow, they compare with the 0.11.1 with 0.4.5, just like the math number, so 0.4.5 > 0.11.1, caused the error. You can run change the 0.4.5 to 0.0.0 then it will success!

**Comment by xzy256** [comment]
it run correctly,thanks.

**Comment by zkself** [comment]
@xzy256  @MikoyChinese   could you please how to change？ 
does it means to change line 69？

**Comment by MikoyChinese** [comment]
> @xzy256 @MikoyChinese could you please how to change？
> does it means to change line 69？

_check_bazel_version("Closure Rules", "0.4.5")
Yes, try to change this line, this is a check method, you can change 0.4.5 to 0.
