### ISSUE TITLE
remote/performance: support HTTP/2.0 for remote caching

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#4838]
Bazel's remote caching protocol currently opens roughly as many TCP connections as there are concurrent actions running. It does use a connection pool, but it's still quite a lot of connections that can overwhelm a backend. We should transparently support HTTP/2.0 so that Bazel can use it if the backend does. GCS supports HTTP/2.0 too.

**Comment by Steve-Munday** [comment]
I would love to see this.  I am running builds in Circle CI and implemented Remote caching using GCS as the back end.  Circle CI runs in AWS.  I posted about this in (bazel-discuss)[https://groups.google.com/d/msg/bazel-discuss/1QetqWCjZFI/izCeo3W-AAAJ].

The performance benefit from adding the remote cache was cancelled out by the network overhead of fetching 5000+ files from GCS.  I turned it off.

**Comment by buchgr** [comment]
I think you commented on the wrong issue :-)

**Comment by Steve-Munday** [comment]
Not sure that I did?  Maybe I misunderstood your feature request.  I was just providing my real-world example.

I tried to use Bazel Remote Cache and found that the network latency between AWS <--> GCP was enough to cancel out any benefit of using a cache.  I have confirmed cache hits but my build time was the same as a clean build.  My action cache (in the GCS bucket) contains thousands of items that are each a few bytes, and the CAS has an equal number of items that are ~20KB in size.  If the remote cache protocol used HTTP/2.0 for the 5000+ requests during a build, then presumably the overhead of opening/closing TCP connections would be reduced, and perhaps my network bottleneck would be gone.  It seems like a good use case for HTTP/2.0.

Is this correct or are you saying HTTP/2.0 would not provide any benefit in this example?

**Comment by buchgr** [comment]
We already do connection pooling, so tcp/tls handshaking shouldn't matter much but it might help a little. I was thinking that you would like this feature request more: https://github.com/bazelbuild/bazel/issues/4844 :smile:

**Comment by Steve-Munday** [comment]
Ahhh I see.  Thanks for clarifying.  Also, I just figured out that you are the same person who responded to my bazel-discuss post, so thanks again!  😄   

AWS S3 is tougher for me because my company is all-in on GCP; we do not have any Amazon infrastructure at all.  It might be worth investigating though.

**Comment by buchgr** [comment]
@Steve-Munday I don't know whether you tried that, but in your CircleCI you run a script that tests throughput and latency to GCS buckets in different regions. I don't know in which AWS regions CircleCI runs but I think it would make sense to pick a GCP region close by.
