### ISSUE TITLE
remote/performance: don't construct a merkle tree for remote caching

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#4839]
Remote caching doesn't benefit from constructing a merkle. Some users reported significant performance overheads from constructing the merkle tree. We might just want to compute the hash of the list of input file hashes instead.

cc: @benjaminp

**Comment by buchgr** [comment]
building a merkle tree should not be much more expensive than building a list if implemented correctly.

**Comment by Globegitter** [comment]
Does this still hold true compared to the comment mentioned here: https://github.com/bazelbuild/bazel/pull/7583#issuecomment-468568192?

**Comment by buchgr** [comment]
I don't know. You'd have to benchmark the current merkle tree implementation against a list based approach I guess. I'd expect the list based approach to still be faster but I am not sure whether it's by a lot.
