### ISSUE TITLE
Enhancement request: Warn if `stamp = True` is used with no other input files

### ISSUE THREAD

**Issue by mmorearty** [bazelbuild/bazel#4842]
### Description of the problem / feature request:

It is a feature, not a bug, of build-stamping (genrule `stamp = True`) that the genrule will only be re-executed if one of the input files _other_ than `bazel-out/volatile-status.txt` has changed.

This is a good feature; but it is subtle, and seems to be something that a lot of people miss. One example, apparently from within Google: See step 3 under https://github.com/bazelbuild/rules_nodejs/blob/de5393f683b9a73d69d023ca0ffce8ed5d39fcfd/README.md#stamping

Bazel could help with this. If Bazel encounters a `genrule` which includes `stamp = True`, but has no `srcs` at all, it would make sense to omit an error message (or at least a warning; but I think an error is appropriate).

### Feature requests: what underlying problem are you trying to solve with this feature?

People mis-using `stamp = True`, assuming that a genrule with `stamp = True` and no input files can be used to generate an intermediate output file that can then be used by other targets.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`WORKSPACE`: empty file

`BUILD`:

```python
# main.out will contain main.txt plus bazel-out/volatile-status.txt.
# Since the below rule `mystamp` is incorrectly written, this will always
# end up writing the same volatile-status.txt to main.out even main.in
# changes.
genrule(
    name = "main",
    output_to_bindir = True,
    srcs = ["main.in", "mystamp"],
    outs = ["main.out"],
    cmd = "cat $(SRCS) > $@",
)

# This is an incorrectly written rule, because it has `stamp = True`, but
# no `srcs`, so it will not behave as the author intended. It will only
# run once.
genrule(
    name = "mystamp",
    output_to_bindir = True,
    outs = ["mystamp.txt"],
    stamp = True,
    cmd = "cat bazel-out/volatile-status.txt > $@",
)
```

`main.in`:

```text
this is main.txt
```

To repro the problem:

* `bazel build :main`, then look at `bazel-bin/main.out`
* Edit `main.in`
* `bazel build :main` again, and then look at the new `bazel-bin/main.out`
* Notice that the `BUILD_TIMESTAMP` line of `bazel-bin/main.out` has not changed! It would be great if Bazel had given me an error in this case, since I wrote the `mystamp` rule incorrectly.

### What operating system are you running Bazel on?

Ubuntu Linux 14.04

### What's the output of `bazel info release`?

`release 0.11.1`

###  Have you found anything relevant by searching the web?

Searched bazelbuild/bazel/issues for `is:open stamp`

**Comment by alexeagle** [comment]
@buchgr related, the issue @mmorearty points out in rules_nodejs is because I couldn't find a way to apply a stamp to arbitrary rules (I'd rather have it on my `*_package` rules).
In my experimentation, `stamp` only gathers the `volatile-status.txt` input for genrule and other native rules. Can you suggest an alternative?

**Comment by ulfjack** [comment]
@alexeagle - are you saying that there's no way to add stamp inputs for Skylark actions? That's independent of this feature request?

**Comment by alexeagle** [comment]
@ulfjack I haven't found a way to do it yet.

Also the only resource I could find on stamping has an empty-`srcs[]` on the genrule too: https://www.kchodorow.com/blog/2017/03/27/stamping-your-builds/

**Comment by alexeagle** [comment]
See discussion in https://groups.google.com/d/msgid/bazel-discuss/CAP4t0yjHEy%2BuHtTq%3Dw4j3-%2BX%2B95XSrmiHoceuxRPe5h_GQ9g6w%40mail.gmail.com?utm_medium=email&utm_source=footer
