### ISSUE TITLE
remote/feature: support AWS S3 as a remote caching backend

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#4844]
We have heard from many users who want to use AWS S3 as a remote caching backend for Bazel just as they currently do with Google Cloud Storage. This is useful when running inside Travis or CircleCI (https://github.com/notnoopci/bazel-remote-proxy) as these SaaS products already run inside AWS.

From skimming over the AWS S3 API documentation it seems that the APIs are mostly compatible, except for authentication. So implementing this feature will likely just mean to add AWS authentication to Bazel.

cc: @davidstanke @alexeagle

**Comment by GregBowyer** [comment]
#4889 is a stab at this

**Comment by buchgr** [comment]
This is a duplicate of #4889

**Comment by keithkml** [comment]
Hi @buchgr, on this project, is a PR normally considered a duplicate of the feature request which implements its fix?

**Comment by danieliziourov-form3** [comment]
@buchgr would you consider reopening this issue?

**Comment by guw** [comment]
@pauldraper How is the S3 bucket populated with cache content?

**Comment by jparismorgan** [comment]
@pauldraper & others - do you need to add Cloudfront in front of S3 to use AWS S3 as a Bazel remote cache? Or is there a way to have Bazel read and write to S3? For either approach, do you / others have an example of setting this up? Thank you!
