### ISSUE TITLE
remote/performance: support rsync compression

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#4845]
I have a prototype implementation of rsync compression for Bazel's remote cache. The idea is that for incremental builds the rsync algorithm determines deltas between Bazel's local output's from a different source state and remote outputs and only fetches these deltas from the remote side using http content-range headers.

In early experiments we are seeing up to 90% reduction in required download bandwidth.

**Comment by vishal-hegde** [comment]
Has there been any update on this one?
