### ISSUE TITLE
windows: Bazel built at head always restarts the server

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4847]
### Description of the problem / feature request:

Bazel built at current HEAD (https://github.com/bazelbuild/bazel/commit/48e205a19bed1cccaa51c7bbfbef6c2fbe47e3de) always restarts the Bazel server.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```Bash
$ git checkout 48e205a19bed1cccaa51c7bbfbef6c2fbe47e3de
$ bazel build src:bazel.exe
```

```
C:\src\bazel>bazel-bin\src\bazel.exe info server_pid
Starting local Bazel server and connecting to it...................
8032

C:\src\bazel>bazel-bin\src\bazel.exe info server_pid
Starting local Bazel server and connecting to it...................
13152

C:\src\bazel>bazel-bin\src\bazel.exe info server_pid
Starting local Bazel server and connecting to it...................
6668
```

### What operating system are you running Bazel on?

Windows 10

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
$ git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
https://bazel.googlesource.com/bazel
48e205a19bed1cccaa51c7bbfbef6c2fbe47e3de
48e205a19bed1cccaa51c7bbfbef6c2fbe47e3de
```

**Comment by laszlocsomor** [comment]
Ironically the culprit seems to be one of my commits: c2b332b45e6ea41a14ecbd3c5f30782bcdeec301.
I'll roll it back and investigate.

**Comment by laszlocsomor** [comment]
Even more ironically and sadly, the `//src/test/py/bazel:bazel_server_mode_test` passes at this commit.

**Comment by philwo** [comment]
Do we have to cherrypick the rollback into 0.12.0?

**Comment by laszlocsomor** [comment]
Yes we do. Thanks!

**Comment by laszlocsomor** [comment]
https://github.com/bazelbuild/bazel/commit/369409995bd75eeb0683fd24f7585d2a90320796 is merged, closing.
