### ISSUE TITLE
Remove global bazelrc from Bazel distribution packages

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#4850]
After a lot of discussion, we've decided that the existing global bazelrc file (https://source.bazel.build/bazel/+/369409995bd75eeb0683fd24f7585d2a90320796:scripts/packages/bazel.bazelrc) is not helpful for both general users, and is causing issues with remote execution in many cases.

See #4475 for an example. This will probably impact #4502 .

The best solution is to remove the global bazelrc entirely. Bazel will continue to set a default PATH of "/bin:/usr/bin" on non-Windows systems where PATH isn't specified via `--actions_env`.

**Comment by jgavris** [comment]
Will this remove the contents of the file for existing installations? I've been using `--nomaster_bazelrc` to deal with this.

**Comment by katre** [comment]
Debian package upgrades will overwrite the file if it hasn't been changed. If you have local edits then the file will not be changed and debian will prompt you during upgrade to resolve the matter.

**Comment by gertvdijk** [comment]
> Debian package upgrades will overwrite the file if it hasn't been changed. If you have local edits then the file will not be changed and debian will prompt you during upgrade to resolve the matter.

Unfortunately, it _is_ overwritten with local edits using Bazel 0.16.1... #6020.
