### ISSUE TITLE
skylint does not check missing rules docstring

### ISSUE THREAD

**Issue by ahippler** [bazelbuild/bazel#4854]
### Description of the problem / feature request:

skylint does not check for missing docstring of rules.

### Feature requests: what underlying problem are you trying to solve with this feature?

public variables of type rule and repository_rule should throw an error like:
`rule 'foo' has no docstring [missing-rule-docstring]`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

skylint should not pass on:
```python
"""foo"""

def _impl(ctx):
    print("foo", ctx.attr.bar)

foo = rule(
    _impl,
    attrs = {
        "bar": attr.string(),
    },
)
```

### skylint from Bazel version

0.11.1

**Comment by laurentlb** [comment]
We're going to retire Skylint in favor of Buildifier (https://github.com/bazelbuild/buildtools).
