### ISSUE TITLE
not possible to declare_file to genfiles_dir

### ISSUE THREAD

**Issue by ahippler** [bazelbuild/bazel#4858]
### Description of the problem / feature request:

since ctx.new_file() is deprecated ctx.actions.declare_file() should be a replacement.
with ctx.new_file() it was possible to generate files to genfiles_dir which I tried with ctx.actions.declare_file()

```python
out = ctx.actions.declare_file(ctx.attr.out, sibling=ctx.genfiles_dir)
```

produces

```
Cannot convert parameter 'sibling' to type File or NoneType, in method declare_file(string, root sibling) of 'actions'
```

### Feature requests: what underlying problem are you trying to solve with this feature?

it must be possible to use a root dir (ctx.bin_dir and ctx.genfiles_dir) as sibling
or as different parameter e.g. root.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

rule.bzl:
```python
def _impl(ctx):
    o = ctx.actions.declare_file('x.sh', sibling=ctx.bin_dir)
    ctx.actions.write(o, 'echo Stuff', is_executable = True)
    return [DefaultInfo(executable = o)]

my_rule = rule(_impl, executable = True)
```

BUILD:
```python
load(':rule.bzl', 'my_rule')
my_rule(name = 'xxx')
```
`bazel build xxx`

### What operating system are you running Bazel on?

macOS 10.12.6

### What's the output of `bazel info release`?

release 0.11.1-homebrew

**Comment by buchgr** [comment]
cc @laurentlb

**Comment by laurentlb** [comment]
Long-term plan is to get rid of the root and the distinction between `bin_dir` and `genfiles_dir` (cc @lberki).

We might add the feature for now, but it should be clear it will go away.

**Comment by lberki** [comment]
We can add that knob, but instead, can you get by by putting that file under `bazel-bin` instead?

**Comment by laurentlb** [comment]
Maybe try to build your code with `--noexperimental_separate_genfiles_directory`? This way, this will merge the `bin` and the `genfiles` directories. It hasn't been much tested yet, but I hope it can make things simpler.

**Comment by ahippler** [comment]
I didn't know the plan to remove the genfiles directory. Wich version will remove the separation and did you report this anywhere?

**Comment by laurentlb** [comment]
It's unclear at the moment how we'll proceed. The separation is not useful and it adds complexity. I would be very happy if we could remove it. It's still here for legacy reasons, so we need to investigate and see how much work there is to do before we can switch the default.

**Comment by limdor** [comment]
@laurentlb a ticket to be able to follow regarding this long term plan would be very beneficial. For me it was also a little bit hard to find in this ticket that this is the long term plan

**Comment by laurentlb** [comment]
The `genfiles` directory will be removed in Bazel 0.25. See https://github.com/bazelbuild/bazel/issues/6761
