### ISSUE TITLE
ascii hexcodes and String.codepoints and chr & ord globals

### ISSUE THREAD

**Issue by erickj** [bazelbuild/bazel#4862]
The Java skylark language reference lists `codepoints` as a method on Strings, but that seems to be a documentation oversight as it's not implemented:

https://github.com/bazelbuild/bazel/blob/master/site/docs/skylark/spec.md#strings

That being said, the go skylark implementation exposes globals `chr` and `ord` and `String.codepoints` with the notice that it's not provided by the Java implementation

https://github.com/google/skylark/blob/master/doc/spec.md#chr

Also, reading [Lexer.java](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/syntax/Lexer.java#L429) I can see that unicode escape sequences are explicitly not supported... 

so AFAICT it's impossible to represent unicode and non-printable ASCII character in Java-skylark, is that correct?

**Comment by erickj** [comment]
I've also just seen the [String interpolation](https://docs.bazel.build/versions/master/skylark/spec.html#string-interpolation) section of the Skylark spec which lists defines replacement `c` as:

```
c       string          x (string must encode a single Unicode code point)
        int             as if by chr(x)
```

However trying to use it in a live example, e.g. `print("%c" % 65)` results in this error:

```
unsupported format character "c" at index 7 in "char: %c"
```

**Comment by erickj** [comment]
FTR this is with:

```
$ bazel info release
release 0.10.0- (@non-git)
```

**Comment by laurentlb** [comment]
Thanks for pointing this out. We should remove this from the documentation. Do you have a use-case for non-printable characters?

To insert special characters, you can use the octal notation (apparently missing from the doc above): `"\52" == "*"`. Ideally, we would support hexadecimal notation (`"\x35"`), but I don't think I have seen requests for this before.

**Comment by erickj** [comment]
"Do you have a use-case for non-printable characters?"

A kludge one, in the absence of more complete unicode support, I would like to use them to identify invalid state transitions in a JSON parser. I believe if I can represent all ascii characters in a state transition table, then I can use the absence of a character to act as a kludge placeholder for identifying (and accepting) unicode codepoints as string characters.
