### ISSUE TITLE
runfiles,Python: move to //tools/python/runfiles

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4878]
### Description of the problem / feature request:

The language-specific tools should be under `//tools/<language>/<tool>` but the Python-specific runfiles library is currently under `@bazel_tools//tools/runfiles:py-runfiles` (in Bazel 0.12.0 release candidate).

See also https://github.com/bazelbuild/bazel/pull/4873

**Comment by laszlocsomor** [comment]
Blocking https://github.com/bazelbuild/bazel/issues/4582

**Comment by philwo** [comment]
Can we close this issue or is it still a release blocker for 0.12.0?

**Comment by laszlocsomor** [comment]
It's no longer a blocker, but it's also not resolved.
