### ISSUE TITLE
FR: more flexible checksum algorithms for repository `download` rules

### ISSUE THREAD

**Issue by erickj** [bazelbuild/bazel#4881]
FR: Extend repository rules `download` and `download_and_extract` to support more checksum algorithms.

Currently the rules are limited to sha256. This isn't flexible enough.

For example, NPM 5 has introduced package-lock.json files in order to help facilitate reproducible builds. The [package-lock.json model for checksum descriptors](https://docs.npmjs.com/files/package-lock.json#packageintegrity) used is specified by the [w3c subresource integrity recommendation](https://www.w3.org/TR/SRI/#cryptographic-hash-functions) which states:

"Conformant user agents MUST support the SHA-256, SHA-384 and SHA-512 cryptographic hash functions for use as part of a request’s integrity metadata and MAY support additional hash functions."

Adding the ability to handle sha1 (e.g. maven_jar), plus at least the above named algorithms would be helpful for supporting more external dependencies.

**Comment by jmillikin** [comment]
I've taken a crack at this in https://github.com/bazelbuild/bazel/pull/7208
