### ISSUE TITLE
@bazel_tools//tools/jdk:jar ERRORs on Windows 32-bit build

### ISSUE THREAD

**Issue by RNabel** [bazelbuild/bazel#4885]
### Description of the problem / feature request:

Bug: when building  `@bazel_tools//tools/jdk:jar` with `--cpu=x86_windows` bazel returns ERROR.

### Feature requests: what underlying problem are you trying to solve with this feature?

Not certain, but the `windows` condition is selected only when the cpu is `x64_windows` (see [`conditions/BUILD:43`](https://github.com/bazelbuild/bazel/blob/master/src/conditions/BUILD#L43).

Inside the `bazel_tools//tools/jdk:jar`  a select then appends `.exe` if the `windows` condition applies. Since x86 windows does not trigger this condition, the error may stem from the fact that it tries to find the file `bin/jar` instead of `bin/jar.exe` (see [`jdk.BUILD:37`](https://github.com/bazelbuild/bazel/blob/master/src/main/tools/jdk.BUILD#L37))

See sample output below:

```bash
$ bazel build --cpu=x86_windows  @bazel_tools//tools/jdk:jar
Loading:
Loading: 0 packages loaded
INFO: Analysed target @bazel_tools//tools/jdk:jar (0 packages loaded).
INFO: Found 1 target...
ERROR: missing input file '@local_jdk//:bin/jar'
[0 / 1] [-----] BazelWorkspaceStatusAction stable-status.txt
ERROR: C:/bazel_cache/ik31xv7y/external/local_jdk/BUILD.bazel:37:1: @local_jdk//:jar: missing input file '@local_jdk//:bin/jar'
Target @local_jdk//:jar failed to build
ERROR: C:/bazel_cache/ik31xv7y/external/local_jdk/BUILD.bazel:37:1 1 input file(s) do not exist
INFO: Elapsed time: 1.419s, Critical Path: 0.01s
FAILED: Build did NOT complete successfully

$ bazel build --cpu=x64_windows  @bazel_tools//tools/jdk:jar
Loading:
Loading: 0 packages loaded
INFO: Analysed target @bazel_tools//tools/jdk:jar (0 packages loaded).
INFO: Found 1 target...
[0 / 1] [-----] BazelWorkspaceStatusAction stable-status.txt
Target @local_jdk//:jar up-to-date (nothing to build)
INFO: Elapsed time: 1.350s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action

# Check that the .exe file can be found even on x86 cpus
$ bazel build --cpu=x86_windows  @local_jdk//:bin/jar
Loading:
Loading: 0 packages loaded
INFO: Analysed target @local_jdk//:bin/jar (0 packages loaded).
INFO: Found 1 target...
ERROR: missing input file '@local_jdk//:bin/jar'
[0 / 1] [-----] BazelWorkspaceStatusAction stable-status.txt
ERROR: C:/bazel_cache/ik31xv7y/external/local_jdk/BUILD.bazel:39:12: @local_jdk//:bin/jar: missing input file '@local_jdk//:bin/jar'
ERROR: C:/bazel_cache/ik31xv7y/external/local_jdk/BUILD.bazel:39:12 1 input file(s) do not exist
INFO: Elapsed time: 1.321s, Critical Path: 0.01s
FAILED: Build did NOT complete successfully

$ bazel build --cpu=x86_windows  @local_jdk//:bin/jar.exe
Loading:
Loading: 0 packages loaded
INFO: Analysed target @local_jdk//:bin/jar.exe (0 packages loaded).
INFO: Found 1 target...
[0 / 1] [-----] BazelWorkspaceStatusAction stable-status.txt
INFO: Elapsed time: 1.333s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action
``` 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run: `bazel build --cpu=x86_windows  @bazel_tools//tools/jdk:jar`

### What operating system are you running Bazel on?

Windows 10 (Version 1709)

### What's the output of `bazel info release`?

`release 0.11.0`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?
No.

### Any other information, logs, or outputs that you want to share?
See above.

**Comment by meteorcloudy** [comment]
Bazel is not supporting for building for x86 Windows currently, `x86_windows` is not a vaild cpu value. But we do have an external contributor working on that, see https://github.com/bazelbuild/bazel/pull/4579
Closing this.
