### ISSUE TITLE
$(CC_FLAGS) is always empty

### ISSUE THREAD

**Issue by kayasoze** [bazelbuild/bazel#489]
... regardless of `--compilation_mode`.  This makes it difficult to build CXX code using genrules (as may be necessary for third party source, like Boost).

**Comment by ulfjack** [comment]
You can set CC_FLAGS from the CROSSTOOL file, but note that it's not
recommended to use genrules for compiling C++ code.

**Comment by kayasoze** [comment]
In a configuration where primary code is built using Bazel and third party libraries are built using their native build systems (wrapped by genrules), is there no way to apply the same `CC_FLAGS` to both sets, then?  The goal is to build third-party libraries with debug symbols when `--compilation_mode=dbg`.  I was expecting `$(CC_FLAGS)` to be an amalgamation of the `compiler_flag`s and `cxx_flag`s in `CROSSTOOL`, but it doesn't contain any of them.

**Comment by ulfjack** [comment]
Sorry for the earlier very brief reply.

C++ compilation is a lot more complicated than 'run the C++ compiler with
these flags'. We support C++ modules, LIPO (a form of feedback-directed
optimization), header checking, PIC and no-PIC (even in a single run),
interface libraries (for faster incremental builds), coverage, generating
temp outputs (--save_temps), and probably more I'm forgetting - though not
all of these are available in Bazel yet. And all of these require different
sets of flags, often even within a single build.

In short, it's impossible to write a genrule that cleanly integrates with
the C++ rules, and even worse if the genrule invokes yet another build
system.

We don't automatically set CC_FLAGS, but require it to be set explicitly in
the CROSSTOOL file. It is not intended for general usage, but only for the
corner cases where using the cc_* rules is completely infeasible.
Internally, we have only a few dozen uses of CC_FLAGS across many tens of
thousands of BUILD files.

I understand that that leaves you with no good options: maintain BUILD
rules for upstream projects (like we do internally) or loose most of the
benefits of Bazel's C++ model. We could potentially improve this a little
bit by auto-generating CC_FLAGS from the CROSSTOOL, but I don't see it ever
working really well.

**Comment by kayasoze** [comment]
I agree that a general solution is unworkable.  Fortunately the *status quo* works reasonably well--PIC can be hard-coded in the genrule, for example--except in the case of opt. vs. debug.   One possibility would be to create multiple genrules and pick between them with `cmd = select()` based on `compilation_mode`.  It seems that `select()` is compatible with `cmd`, so this is a reasonable workaround.  It would be preferable if `select()` could be used in string concatenation, but that is a minor nit, as you can still use `select()` to create strings at BUILD file scope.  Closing.
