### ISSUE TITLE
Bazel's action graph is very hard to introspect and debug

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel#4891]
### Feature Request
Please add logging throughout Bazel, enableable via a command-line flag, that can be used to introspect and debug Bazel's build logic and internal state. A particular focus on the action graph and remote caching/execution seems prudent given the relative immaturity of remote features.

This is related to the debugging @gkossakowski and I did in https://github.com/bazelbuild/bazel/issues/4770 and https://github.com/bazelbuild/bazel/issues/4714 around non-deterministic Java builds. The difficulty of understanding Bazel's internal state is severe enough that both Go and Scala devs have expressed reluctance to continue using Bazel here.

### Details and Elaboration

In both the above issues, we were trying to understand why Bazel's final output was different on two similar or identical machines. The problem boiled down to understanding exactly which part of the action graph was diverging, because we could tell from `bazel dump --action_cache` that _something_ in the middle of the build was different but couldn't tell what.

As a minimal example, consider this Hello World repository:

```
$ touch WORKSPACE
$ echo 'cc_binary(name = "hello", srcs = ["hello.cc"])' > BUILD
$ echo 'int main() { return 0; }' > hello.cc
```

For each action Bazel takes, I want to print out the checksum of each known input and output file. This is, as far as I can tell, impossible in an unpatched Bazel as of 0.11.1. 

My first attempt was to turn on every debug flag I could find in the docs or `bazel help --long`:

```
$ bazel --client_debug build --build_event_json_file=bep.json --build_event_text_file=bep.txt --explain=explain.txt --logging=6 --profile=profile.dat --sandbox_debug :hello
CLIENT: Debug logging active
CLIENT: Trying to connect to server (timeout: 30 secs)...
INFO: Writing profile data to '/Users/jmillikin/cc-bazel-hello/profile.dat'
INFO: Analysed target //:hello (6 packages loaded).
INFO: Found 1 target...
INFO: Writing explanation of rebuilds to 'explain.txt'
Target //:hello up-to-date:
  bazel-bin/hello
INFO: Elapsed time: 5.281s, Critical Path: 0.21s
INFO: Build completed successfully, 5 total actions
$
```

Notice that despite the very high logging threshold (I also tried `--logging=0` in case it was inverted) there was no useful log output, such as might be printed by a C++ or Go binary with `--stderrthreshold=0 --v=10`. The resulting BEP files did not contain input/ouput file hashes, nor did `explain.txt`. The profile data was only performance info.

If I run `bazel dump --action_cache`, it prints output like this:
```
8, bazel-out/darwin-fastbuild/bin/hello:
      actionKey = 0790194f76f554a2f47d8422ce2e070e
      usedClientEnvKey = 00000000000000000000000000000000
      digestKey = bcc7d2c8ebcb8e257cff11ba4c042b0b
```
which can tell me which actions diverged, but has no information about which of the (potentially thousands) of input files was different between two runs that should have been identical.

The solution I ended up using was building a custom Bazel with the following patch applied to the action cache, so it would print per-input-file MD5 digests of each action's metadata map.
```
diff --git a/src/main/java/com/google/devtools/build/lib/actions/cache/ActionCache.java b/src/main/java/com/google/devtools/build/lib/actions/cache/ActionCache.java
index fc21b41a2d..8945cf9543 100644
--- a/src/main/java/com/google/devtools/build/lib/actions/cache/ActionCache.java
+++ b/src/main/java/com/google/devtools/build/lib/actions/cache/ActionCache.java
@@ -31,6 +31,7 @@ import java.util.HashMap;
 import java.util.List;
 import java.util.Map;
 import javax.annotation.Nullable;
+import javax.xml.bind.DatatypeConverter;
 
 /**
  * An interface defining a cache of already-executed Actions.
@@ -137,7 +138,11 @@ public interface ActionCache {
      * immutable.
      */
     public Md5Digest getFileDigest() {
+      System.out.println("getFileDigest(actionKey: \"" + actionKey + "\")");
       if (md5Digest == null) {
+        for (Map.Entry<String, Metadata> entry : mdMap.entrySet()) {
+          System.out.println("  " + DatatypeConverter.printHexBinary(entry.getValue().getDigest()).toLowerCase() + "  " + entry.getKey());
+        }
         md5Digest = DigestUtils.fromMetadata(mdMap);
         mdMap = null;
       }
```
```
$ ~/src/bazel/bazel-bin/src/bazel_with_jdk build :hello
INFO: Found 1 target...
getFileDigest(actionKey: "")
  0534a7448ff20fb32e65cc0eda852faf  external/local_config_cc/cc_wrapper.sh
getFileDigest(actionKey: "")
getFileDigest(actionKey: "6b2d560e139282e05e085e9c48fab7a6")
  ee3963bc5da04825457cd0f49af410a1  bazel-out/darwin-fastbuild/bin/hello.runfiles_manifest
getFileDigest(actionKey: "6b2d560e139282e05e085e9c48fab7a6")
getFileDigest(actionKey: "")
    bazel-out/volatile-status.txt
  c6645071a9410379121b60d66ca01136  bazel-out/stable-status.txt
getFileDigest(actionKey: "")
getFileDigest(actionKey: "a3aff581ff03822315235063beeb6dcc")
  ee3963bc5da04825457cd0f49af410a1  bazel-out/darwin-fastbuild/bin/hello.runfiles/MANIFEST
  ee3963bc5da04825457cd0f49af410a1  bazel-out/darwin-fastbuild/bin/hello.runfiles_manifest
getFileDigest(actionKey: "a3aff581ff03822315235063beeb6dcc")
getFileDigest(actionKey: "cf6469e779e67a7e63bdea515f53c3eb")
  8d26211da0fbb9ef6092ab708ee7aba8  bazel-out/darwin-fastbuild/bin/_objs/hello/hello.pic.o
  0534a7448ff20fb32e65cc0eda852faf  external/local_config_cc/cc_wrapper.sh
  6b41d999a57b95ba222552334c96d186  bazel-out/darwin-fastbuild/bin/_objs/hello/hello.pic.d
  5c11ff1def313f2a87eabf3a30f130ad  hello.cc
[...]
```

Using the above data plus `bazel dump --action_cache`, it's extremely easy to figure out which action produced different output when given the same inputs. But printf-debugging the build system is not something a Bazel user should be expected to do, and is fairly distressing to devs that don't have strong Java skills.

### What operating system are you running Bazel on?

We've been trying to debug non-determinism on MacOS and Linux.

### What's the output of `bazel info release`?

release 0.11.1

**Comment by pcj** [comment]
I'd like to see a flag that enables the action graph to be output in the BEP.

**Comment by ulfjack** [comment]
@ola-rozenfeld has a pending change [1] to output the action graph. Personally, I'm wondering whether to put it into the BEP as BEP events, or whether to put it into a separate file that's referenced in the BEP.

[1] https://bazel-review.googlesource.com/c/bazel/+/45055

**Comment by meisterT** [comment]
I've added support to dump the action graph as of analysis, see https://docs.bazel.build/versions/master/user-manual.html#dump

But for this bug execution information is necessary, so assigning back to Ola.

**Comment by pcj** [comment]
Thanks for that @meisterT, FYI I saw this on 0.10.0:

```
$ bazel dump --packages
```

```
java.lang.NullPointerException
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.dumpPackages(SequencedSkyframeExecutor.java:796)
	at com.google.devtools.build.lib.skyframe.SkyframePackageManager.dump(SkyframePackageManager.java:99)
	at com.google.devtools.build.lib.runtime.commands.DumpCommand.exec(DumpCommand.java:203)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:489)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:218)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:58)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:851)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:109)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:916)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by agoulti** [comment]
The flag --experimental_execution_log_file allows to dump the relevant information about an action, including hashes of the inputs and the actual outputs.

https://docs.bazel.build/versions/master/remote-execution-caching-debug.html has documentation on how to use it to debug cache hits, but it can also be used to debug non-deterministic outputs.

I think this covers the use case for this bug, but please reopen if it is not sufficient for your use case!
