### ISSUE TITLE
no such attribute 'proto_source_root' in 'proto_library' rule

### ISSUE THREAD

**Issue by phenomenes** [bazelbuild/bazel#4893]
### Description of the problem:

Bazel fails to build target when using `proto_source_root` attribute in `proto_library` rule. As specified in the documentation:
https://docs.bazel.build/versions/master/be/protocol-buffer.html#proto_library

```
ERROR: /test-proto/BUILD:1:1: //:person_proto: no such attribute 'proto_source_root' in 'proto_library' rule
```

### Steps to reproduce

create a `proto_library` rule:
```
# BUILD

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "person.proto",
    srcs = [
        "person.proto",
    ],
    proto_source_root = package_name(),
)
```

and the `person.proto`
```
# person.proto

syntax = "proto3";

package test

message Person {
  string name = 1;
  int32 id = 2;
  string email = 3;
}
```

build the target
```
bazel build //:person_proto --verbose_failures
```

### What operating system are you running Bazel on?

Ubuntu 16.04.3 LTS

### What's the output of `bazel info release`?

```
release 0.11.1
```

**Comment by ittaiz** [comment]
AFAIR this feature is in 0.12.0-RC1.
Can you check with it and report back?

**Comment by phenomenes** [comment]
There is no such tag, but I built from `development` and it is indeed implemented.
I can't find the right documentation for v0.11.1, the main page points to master.

**Comment by mhlopko** [comment]
Therefore I can

**Comment by ittaiz** [comment]
Yes, it’s a known issue of documentation.
@philwo
Isn’t there such a tag?

**Comment by philwo** [comment]
@ittaiz Our release scripts don't create tags for release candidates currently. We're considering adding that, though (and also publishing pre-release version on GitHub).

**Comment by ittaiz** [comment]
I see. Thanks!

**Comment by phenomenes** [comment]
@ittaiz @philwo thanks for clarifying
