### ISSUE TITLE
Failed worker protocol error doesn't explain that stdout is reserved for worker protocol

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#4897]
When a user just adds a `console.log` to a nodejs worker (or `System.out.println` to a Java one) they get a big error that looks to them like they crashed Bazel, and no indication that a Worker process is not allowed to write things to stdout.

This makes it very hard to recover from a basic attempt to debug problems.

(It helps a lot that we now print the thing that was written to stdout, like `no ivy` below, but it's hard to find unless you're accustomed to parsing this error, and still doesn't say how to fix it)

```
ERROR: /home/www/angular/packages/core/BUILD.bazel:5:1: Compiling Angular templates (ngc) //packages/core:core failed: Worker process returned an unparseable WorkResponse:

---8<---8<--- Exception details ---8<---8<---
com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:115)
	at 
 ...
com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
---8<---8<--- End of exception details ---8<---8<---

---8<---8<--- Start of log ---8<---8<---
no ivy
---8<---8<--- End of log ---8<---8<---
```

**Comment by cushon** [comment]
A better diagnostic would be helpful, but the problem could also be avoided by not using stdout to communicate with workers, e.g. #2832

**Comment by philwo** [comment]
@cushon Absolutely. Unfortunately I won't have time to work on that before Q3. :|

I prepared a fix for this that adds a more helpful message in this case.
