### ISSUE TITLE
DumpPlatformClassPath.java (part of Java toolchain) is non-deterministic

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel#4899]
See https://github.com/bazelbuild/bazel/issues/4714#issuecomment-374795250 for context.

### Description of the problem

tools/jdk/DumpPlatformClassPath.java is used to generate `platformclasspath.jar`, which as part of the Java toolchain is a direct dependency of ~every `java_binary`, `java_library`, and various language-specific rules built on JVM.

Its behavior is not deterministic because it walks the filesystem, then writes files into the `JarOutputStream` as they're discovered. This means it produces .jar files with identical unpacked content but different checksums, due to differences in the zip file index.

Non-determinism in required toolchain dependencies basically breaks all remote caching for Java targets.

### What operating system are you running Bazel on?

The non-determinism is known to occur on Linux and MacOS.

### What's the output of `bazel info release`?

`release 0.11.1`

cc @gkossakowski @johnynek

**Comment by davido** [comment]
cc @cushon

**Comment by johnynek** [comment]
I'm happy this was closed, but before we close can we comment on how we can add tests to catch and prevent this? I imagine reproducibility regressions will be really common if we don't have tests catch.

**Comment by gkossakowski** [comment]
a good tactics for reproducibility tests would be of interest for scala rules https://github.com/bazelbuild/rules_scala/issues/447

**Comment by cushon** [comment]
That is a good question. This specific genrule is temporary to support both JDK 8 and 9 host_javabases, but having a way to test for this category of error would be helpful. I started a thread of bazel-dev@:
https://groups.google.com/d/topic/bazel-dev/YOkJA769ol8/discussion
