### ISSUE TITLE
android_binary: building with a GMS Ads AAR results in missing R$styleable.class error

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#4901]
### Description of the problem / feature request:

This issue was discovered by @paladine: repro project is https://github.com/jin/bazel_gmscore_crash

This crash happens when attempting to use `com.google.android.gms.ads.AdView` from [gmaven_rules](https://github.com/aj-michael/gmaven_rules) target `@com_google_android_gms_play_services_ads_11_8_0//aar`. 

The `android_binary` target compiles successfully, but crashes on launch with this error:

```
E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: 
Didn't find class "com.google.android.gms.R$styleable" on path: 
DexPathList[[dex file "/data/local/tmp/incrementaldeployment/com.example.bin/dex/incremental_classes1.dex"],nativeLibraryDirectories=[/data/user/0/com.example.bin/lib, /system/lib, /vendor/lib]]
```

This happens with both manual `bazel build && adb install` and `mobile-install`.

### What's the output of `bazel info release`?

0.11 and master.

### Any other information, logs, or outputs that you want to share?

Grepping through the pre-dexed jar shows that the class doesn't exist, which makes me suspect this is a GMS bug, but I'm opening the issue here to track it.

```
$ zipinfo -1 bazel-bin/java/com/example/bin/bin_deploy.jar  | grep "com/google/android/gms/R"
com/google/android/gms/R$integer.class
com/google/android/gms/R$string.class
com/google/android/gms/R.class
```

A transitive dependency of the `ads` AAR, `basement`, has traces of the `styleable` class:

```
~/.m2/repository/com/google/android/gms/play-services-basement/11.8.0
$ cat R.txt | grep "styleable Ads"
int[] styleable AdsAttrs { 0x1, 0x1, 0x1 }
int styleable AdsAttrs_adSize 0
int styleable AdsAttrs_adSizes 1
int styleable AdsAttrs_adUnitId 2
```

but I'm having some trouble finding the source of `com/google/android/gms/R$styleable.class`.

**Comment by paladine** [comment]
This issue appears to be resolved when switching to @com_google_android_gms_play_services_ads_15_0_0//aar

**Comment by jin** [comment]
@paladine nice, I'll close this for now.
