### ISSUE TITLE
repository rules always re-execute if WORKSPACE mtime is before last edit to rule.bzl

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel#4903]
Given this minimal workspace:
```
$ touch BUILD
$ cat >WORKSPACE <<EOF
load(":rule.bzl", "the_rule")
the_rule(name = "the_repo")
EOF
$ cat >rule.bzl <<EOF
def _the_rule(ctx):
  print("executing _the_rule")
  ctx.file("WORKSPACE", "")
  ctx.file("BUILD.bazel", "cc_binary(name='hello', srcs=['hello.cc'])")
  ctx.file("hello.cc", "int main() { return 0; }")

the_rule = repository_rule(
  implementation = _the_rule,
)
EOF
```

If I build `@the_repo//:hello` repeatedly, the repository rule gets re-executed every time:

```
$ bazel build @the_repo//:hello
DEBUG: /Users/jmillikin/src/test-repo-rule/rule.bzl:2:3: executing _the_rule
INFO: Analysed target @the_repo//:hello (4 packages loaded).
[...]
$ bazel build @the_repo//:hello
DEBUG: /Users/jmillikin/src/test-repo-rule/rule.bzl:2:3: executing _the_rule
INFO: Analysed target @the_repo//:hello (0 packages loaded).
[...]
```

If there are many such repository rules and they need some expensive setup, this can cause very slow build times with no obvious cause (because the repo rules are run in analysis phase).

However, the behavior is dependent on `WORKSPACE` mtime!

```
$ touch WORKSPACE 
$ bazel build @the_repo//:hello
INFO: Analysed target @the_repo//:hello (4 packages loaded).
[...]
$ bazel build @the_repo//:hello
INFO: Analysed target @the_repo//:hello (0 packages loaded).
[...]
```

Changing the mtime of `rule.bzl` has no effect, but editing it (in even trivial ways) gets it stuck again:

```
$ touch rule.bzl
$ bazel build @the_repo//:hello
INFO: Analysed target @the_repo//:hello (0 packages loaded).
$ echo '' >> rule.bzl
$ bazel build @the_repo//:hello
DEBUG: /Users/jmillikin/src/test-repo-rule/rule.bzl:2:3: executing _the_rule
INFO: Analysed target @the_repo//:hello (4 packages loaded).
$ bazel build @the_repo//:hello
DEBUG: /Users/jmillikin/src/test-repo-rule/rule.bzl:2:3: executing _the_rule
INFO: Analysed target @the_repo//:hello (0 packages loaded).
```

I've verified that the external repository is correctly marked as `local=False`:

```
$ bazel dump --packages | grep -A 4 the_rule
      the_rule rule //external:the_repo
        $local = false
        $environ = []
        name = the_repo
        $toolchains = []
```

### What operating system are you running Bazel on?

MacOS

### What's the output of `bazel info release`?

`release 0.11.1`

**Comment by aehlig** [comment]
To make things even worse, that re-execution seems to hit some heavy caching. This can be seen by abusing the `execute` method to do some out-of-bound signalling, e.g., by adding `ctx.execute(["/bin/sh", "-c", "date +%s > /some/outside/path/date.txt"])`. So we have to find out two things (a) when a re-execution of the rule is reported (e.g., print messages are repeated) and (b) when side-effects (e.g., file write, network access) are redone---and for both, decide what the intended semantics should be.

**Comment by aehlig** [comment]
OK, a bit of `printf`-debugging shows that the `fetch` method of the `SkylarkRepositoryFunction` is indeed only called once; but I have no idea why the mtime influences whether the messages are replayed.
