### ISSUE TITLE
BUILD_TIME is an incorrect Unix epoch conversion in 'bazel version'

### ISSUE THREAD

**Issue by deeglaze** [bazelbuild/bazel#4905]
The current release (0.11.1) was on March 6, 2018. When you run

bazel version

You get the following:

Build label: 0.11.1
Build target: <redacted>/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 14 07:48:23 +50148 (1520362424903)
Build timestamp: 1520362424903
Build timestamp as int: 1520362424903

If you run 1520362424903 through epochconverter.com, you get the expected GMT March 6, 2018 (6:53:44.903 PM).

May 14 is what both 'date -d @1520362424903' and 'perl -le 'print scalar localtime(1520362424903)' will output, so this is an unsurprising error.

If you convert the timestamp from supposed milliseconds to seconds (date -d @1520362425), you get the expected result (for me, Tue Mar  6 10:53:44 PST 2018, which is the same time that Github reports for the release commit).

**Comment by katre** [comment]
This looks to be the same as #4469, closing it as a duplicate.

Unfortunately, trying to fix the underlying issue is difficult, as various projects currently have dependencies on the broken behavior.
