### ISSUE TITLE
Find a way to invalidate non-hermetic external repositories 

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#4907]
We don't have a good answer for people using non hermetic external repositories regarding repository invalidation.

Example:
Currently when users use our autoconfigured C++ toolchain, and then they upgrade the compiler (or OS), bazel doesn't notice and will happily use old include directories.

The only way how to automatically invalidate the repo is to make it depend on the environment variable and then change the variable when the repo should be invalidated, or run `bazel clean --expunge` to invalidate all repos.

Objective is to come up with a better story.

**Comment by mhlopko** [comment]
cc @aehlig

**Comment by hlopko** [comment]
I think there has been a major progress on this issue, and the only thing that is maybe missing is a link to documentation with best practices? Wdyt @aehlig?

**Comment by aehlig** [comment]
> I think there has been a major progress on this issue, and the only thing that is maybe missing is a link to documentation with best practices? Wdyt @aehlig?

So far, we have the `sync` [command](https://docs.bazel.build/versions/master/command-line-reference.html#commands) that, however, fetches _all_ external external repositories unconditionally (still using disk cache for files specified by their hashes). Partial syncs, for syncs for only the "configure-like" external "repositories" is not done yet.

**Comment by aehlig** [comment]
I believe [`bazel sync --configure`](https://github.com/bazelbuild/bazel/commit/4a1380fed159f09b29df461b85e0469f8cd81d34) and marking [cc configure rules as configuration-like](https://github.com/bazelbuild/bazel/commit/e1a6877240b212b192506f5269053f4ded263ee7) the issue is fixed.
