### ISSUE TITLE
Backwards-compatible constraints in Skylark

### ISSUE THREAD

**Issue by ilya-biryukov** [bazelbuild/bazel#4923]
### Description of feature request:
Add support for backwards-compatible `constraint_value`s or a similar mechanism to Skylark.

### Feature requests: what underlying problem are you trying to solve with this feature?

Each `constraint_value` defined in skylark is currently completely independent of any other values defined for the same `constraint_setting`.

This lack of information about unrelated does not let us model some useful properties.

#### Example 1. CPU architectures.
Consider the following `constraint_setting` that attempts to model a CPU architecture (e.g., used to turn on compiler optimizations or depend on a library, optimized for a particular arch):

    constraint_setting(name = "cpu_arch")
    constraint_value(name = "arm", config_setting = ":cpu_arch")
    constraint_value(name = "x86_64", config_setting = ":cpu_arch")
    constraint_value(name = "haswell", config_setting = ":cpu_arch")

Some targets may depend on this constraint:

    cc_library(
      name = "heavily_optimized", 
      srcs = select({
        # we actually need an extra 'config_setting' here, 
        # but imagine that 'select' works over 'constraint_value'.
        "@platforms//:arm": ["arm/impl.cc"],
        "@platforms//:x86_64": ["x86/impl.cc"],
        "//conditions:default": ["unoptimized/impl.cc"]}))

Since 'haswell' is backwards-compatible with 'x86_64', this target would definitely want to build `x86/impl.cc` when `cpu_arch = "haswell"`, but there is no way to specify that in Skylark now.
The only way out of that is adding `":haswell"` branch to select statements, but this is error-prone (users will inevitably forget to cover some cases) and hard to maintain when adding new a `constraint_value` for an existing setting.

#### Example 2. Versions of glibc.
Another obvious example of backwards-compatible constraints is the version of glibc.

    constraint_setting(name = "glibc")
    constraint_value(name = "glibc_2.13", config_setting = ":glibc")
    constraint_value(name = "glibc_2.14", config_setting = ":glibc")
    constraint_value(name = "glibc_2.15", config_setting = ":glibc")

glibc is backwards-compatible, so a platform with  `glibc = "2.15"` should be fine for those who require a lower version of glibc.

### Possible solution.
This section tries to very briefly sketch a possible solution. It is not intended to be a fully detailed proposal that covers all the cases.
One way to solve it is to specify for each `constraint_value` which other `constraint_value` it can fulfill.
Here's how this could look like (with a syntax proposed by John Cater):
   
    # Example 1. cpu_arch.
    constraint_value(name = "haswell", config_setting = ":cpu_arch", 
      # Specifies that x86_64 is also fulfilled by "haswell".
      includes = ":x86_64") 
   
    # Example 2. glibc.
    constraint_value(name = "glibc_2.13", config_setting = ":glibc")
    constraint_value(name = "glibc_2.14", config_setting = ":glibc",
      includes = ":glibc_2.13") 
    constraint_value(name = "glibc_2.15", config_setting = ":glibc",
      # Specifies that glibc2.14 and, transitively, glibc2.13 are also fulfilled by "glibc2.15".
      includes = ":glibc_2.14")

By default `constraint_values` in `config_setting` match the specified `constraint_value` or any other `constraint_value` that (transitively) includes it:
    
    # Matches x86 and haswell.
    config_setting(name = "is_x86", constraint_values = [":x86_64"])
    # Matches glibc 2.13, 2.14 or 2.15
    config_setting(name = "is_glibc_2.13", constraint_values = [":glibc_2.13"])

For flexibility, we should also allow to specify exact-only matches too:

    # Matches only x86, and not haswell.
    config_setting(name = "exactly_x86", constraint_values_exact = [":x86_64"])
    # Matches only glibc 2.13, but not 2.14 or 2.15
    config_setting(name = "exactly_glibc_2.13", constraint_values_exact = [":glibc_2.13"])

**Comment by katre** [comment]
This is definitely something we need to support for the config_setting case. I am a bit concerned about how this would work with [toolchain resolution](https://docs.bazel.build/versions/master/toolchains.html). Consider the following toolchain declarations, using the above glibc versions:

```
toolchain(name = 'cc-toolchain-glibc-2.13',
  exec_compatible_with = [ ':glibc_2.13'],
  // Skip the rest, it's not relevant
)

toolchain(name = 'cc-toolchain-glibc-2.15',
  exec_compatible_with = [ ':glibc_2.15'],
  // Skip the rest, it's not relevant
)

platform(name = 'system_glibc_2.13',
  constraint_values = [':glibc_2.13'])
```

If we are trying to build a target and the execution platform is ':system_glibc_2.13', which toolchain should be selected? Is the one that matches more exactly preferred? Or do we consider both to be available and fall back on the general rule from toolchain resolution that the first listed toolchain is the preferred one? (Please ignore the specifics of how glibc works, I'd like to deal with the general semantics of the constraints).

Ideally, we'd need a way to specify that we want an exact match, like you propose for `config_setting`, but since `exec_compatible_with` (and `target_compatible_with`) are lists of labels, that isn't as easily managed unless we duplicate to have `exec_compatible_with` and also `exec_compatible_with_exact`, which isn't great.

**Comment by ilya-biryukov** [comment]
Good point, `exec_compatible_with` looks like a case where you would prefer to do non-exact matches and pick the most specialized one. I wouldn't expect such detailed constraints to be used in `exec_compatible_with` much.

I have only considered `target_compatible_with` case before, for which I find exact matches to be the right default. At least in examples that I mentioned earlier, both glibc and cpu_arch can be interpreted as something that affects toolchain resolution. ('glibc' would correspond to the version of glibc that target binary links against and 'cpu_arch' would affect the optimization flags passed to the compiler in opt mode).

**Comment by katre** [comment]
Ideally, we'd have the same selection rules for `exec_compatible_with` and `target_compatible_with`, in order to simplify what people need to know to use platform constraints properly.

Still thinking about what this will look like.

**Comment by katre** [comment]
Placing this in the icebox since we have no plans to take on this work.

**Comment by katre** [comment]
This is sufficiently stale so I'm closing it: I think that the cases are better modeled differently. Specifically, CPU subtypes should be handled with specific constraint settings, and glibc versions shouldn't be constraints at all.
