### ISSUE TITLE
java.exe failures on Buildkite

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#4924]
https://buildkite.com/bazel/google-bazel-presubmit/builds/588#60311e60-e262-4ee1-83c9-270ce5296aa4

INFO: From Compiling Java headers src/main/java/com/google/devtools/build/lib/libbuild-base-hjar.jar (455 files):

  | Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(161): CreateProcessWithExplicitHandles("D:\temp\_bazel_buildkite\ogez2d-n\execroot\io_bazel\external\local_jdk\bin\java.exe" -Xverify:none -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac-9+181-r4173-1.jar -jar e(...)): command is longer than CreateProcessW's limit (32768 characters)

and also 

ERROR: Caught I/O exception: java.io.IOException: D:/temp/_bazel_buildkite/ogez2d-n/execroot/io_bazel/_tmp/8a0a6eaca3beedecec9a7a670beca254/_bazel_buildkite/install/06be74defec9017c98119afd3362b681/_embedded_binaries/embedded_tools/jdk/bin/java.exe (Permission denied)

Any thoughts on this error @laszlocsomor @meteorcloudy ?

**Comment by laszlocsomor** [comment]
Started debugging.

Known so far:
- this was a presubmit test of https://bazel.googlesource.com/bazel/+/29587f5487d3bbef9c5074f2f83b85e6cb4234a6 which was later merged as https://bazel.googlesource.com/bazel/+/f5c8c0bb0f53cd7289d65672955b37ffcff7d6c4.
- the "Action failed to execute ... command is longer than CreateProcessW's limit (32768 characters)" error is known and it's non-fatal, though I'm investigating that too and I doubt it's related because it's been around for months

**Comment by laszlocsomor** [comment]
@buchgr , the first error ("Action failed to execute ... command is longer than CreateProcessW's limit (32768 characters)") is https://github.com/bazelbuild/bazel/issues/4096

**Comment by laszlocsomor** [comment]
I don't know how to repro this  and cannot spend more time looking for it. Please reopen if you see it again.

**Comment by jasharpe** [comment]
I just saw this again: https://buildkite.com/bazel/google-bazel-presubmit/builds/1478#265338d9-48ca-4ff2-af40-d087490a556b

**Comment by jasharpe** [comment]
Seeing it consistently for the test I'm adding. Here's another one: https://buildkite.com/bazel/google-bazel-presubmit/builds/1481#5779278d-89d5-4ac7-9e9b-2393872df4f1/179-236

**Comment by laszlocsomor** [comment]
I suspect this is https://github.com/bazelbuild/bazel/issues/5038

**Comment by laszlocsomor** [comment]
@mhlopko saw the Permission Denied error on BuildKite even with Bazel 0.13.0, so it's not #5038.

https://buildkite.com/bazel/google-bazel-presubmit/builds/2469#4098e7a1-1dd1-419f-97d4-99ed19869fe5

**Comment by mhlopko** [comment]
Another: https://buildkite.com/bazel/google-bazel-presubmit/builds/2738, trying to rerun.

**Comment by laszlocsomor** [comment]
Thanks! What I know is that the error is reported here: https://github.com/bazelbuild/bazel/blob/3aa9107ebefebbf4b98b382254ff83cfb8def865/src/main/java/com/google/devtools/build/lib/exec/StandaloneTestStrategy.java#L184-L185

Without a stack trace it's difficult to know what exactly threw the exception. Let me change Bazel to report the stacktrace there.
