### ISSUE TITLE
PublishBuildEvent out of sync with googleapis repo

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/bazel#4926]
The return type for RPC PublishBuildToolEventStream was "recently" (in July) changed to PublishBuildToolEventStreamRequest, but the googleapis repo does not reflect this change.
Any chance we can get this updated?

See
https://github.com/bazelbuild/bazel/blob/master/third_party/googleapis/google/devtools/build/v1/publish_build_event.proto#L63
https://github.com/googleapis/googleapis/blob/master/google/devtools/build/v1/publish_build_event.proto#L63

**Comment by buchgr** [comment]
I have filed a bug against the internal team: b/77183232

**Comment by buchgr** [comment]
This has been fixed. Thanks for reporting @Yannic !

**Comment by Yannic** [comment]
Thanks!
