### ISSUE TITLE
Feature request: query in workspace status scripts with stamping

### ISSUE THREAD

**Issue by ah-edg** [bazelbuild/bazel#4929]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

`bazel query` should be executable in workspace_status scripts for stamping. Trying to do so deadlocks the build right now.

### Feature requests: what underlying problem are you trying to solve with this feature?

I want to make sure the build artifact does not contain any files that are not committed.
This should also work with glob and it should be based on the rule being built/run.
To do so, I want to use this in the `workspace_status.sh` script called when `stamp` is true:

```
# check that all files used in a build are committed and used in their committed version
all_required_files_committed() {
    task="${1:-main}"
    # find all files required for main in the local tree
    sources=$(bazel query 'kind("source file", deps(//:'"${task}"'))' | egrep -v '^@' | cut -b 4-)
    for src in "${sources[@]}"; do
        git ls-files --error-unmatch "$src" 2>/dev/null || return 1 # all files committed?
        git diff-index --quiet HEAD "$src" || return 1 # all files in their committed version?
    done
    return 0 # all ok
}

# validate the directory
while [[ ! -f WORKSPACE ]]; do cd  .. ; done
if [[ ! -f WORKSPACE ]]; then
    echo "No WORKSPACE found"
    exit 1
fi

GIT_COMMIT=$(git rev-parse HEAD)
GIT_STATUS=$(all_required_files_committed main && echo 'clean' || echo 'modified')
GIT_TAG=$([ "clean" == "$GIT_STATUS" ] && echo "$GIT_COMMIT" || echo 'modified')

echo "BUILD_COMMIT ${GIT_COMMIT}"
echo "BUILD_STATUS ${GIT_STATUS}"
echo "BUILD_TAG ${GIT_TAG}"
```

I lack two things:

1. I have to know know which rule bazel build / run was called with (defaulting to `main` in my script)
2. I have to call `bazel query` while bazel is already running

I consider the first problem to be minor, this issue centers on the second one.

### What operating system are you running Bazel on?

Linux and - as soon as the path length fix lands - Windows

### What's the output of `bazel info release`?

release 0.11.1

###  Have you found anything relevant by searching the web?

No. If there's another way to do it, I'm happy to hear it. The only way I can think of is calling bazel from a wrapper, writing this to a file and reading it from the stamp-script, but I'd like to avoid it.

**EDIT** I added the validate directory part. I did not copy it from my original script but it might be needed for printed paths.

**Comment by lfpino** [comment]
@ericfelly can you please triage?

**Comment by ericfelly** [comment]
Hi! The workspace_status script is intended to provide high-level information about the in-use depot, rather than fine-grained information about the particular top-level targets you are building. Therefore, trying to pass in the top-level targets or their transitive source files will trigger a lot of system-level friction. Instead, I would focus on returning the status about the git client as a whole.

i'm not an expert on git, but internally we do a "git diff" against a known depot state to provide this information.

**Comment by ah-edg** [comment]
Hi,
git diff can find tracked files that are not checked in, but I want to make sure all builds done anywhere are reproducible based on the commit. I want to avoid builds containing untracked files - or accidents with .gitignore - the local one and user specific ignore settings. This also applies when glob implicitly includes one of the ignored files.

My script above is different to git diff in making sure all source files used for the build are checked in and are committed. It checks the git status per file based on the list of used files for a rule.

This is less of a problem when there are no local ignore settings or when globbing is not used.

Concerning the severity: we did not run into problems yet, I just wanted to make sure they won't happen.

**Comment by janakdr** [comment]
Usually such a hard reproducibility requirement would be most needed when doing a "release" build, in which case you can run a git command similar to what @ericfelly suggested, since you're running on a fresh workspace. Supporting this in an arbitrary workspace that may have stray files is probably not something we'll be able to support, unfortunately.
