### ISSUE TITLE
Add documentation for cc_toolchain

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel#494]
I noticed that the `cc_toolchain` documentation is missing from the Build Encyclopedia. Is this intentional or a bug?

**Comment by damienmg** [comment]
It is there http://bazel.io/docs/build-encyclopedia.html#java_toolchain

**Comment by damienmg** [comment]
Sorry I misread "java_toolchain". It is just not yet documented. It is quite experimental and until it get stabilize we don't want to document it.

**Comment by davidzchen** [comment]
Understood. Thanks for the clarification! I'll update the issue title.

**Comment by ChrisCummins** [comment]
Is there any update on this?

**Comment by brianretford** [comment]
Would love to have some toolchain docs. Is stabilizing the interface planned anytime soon? (That would also be nice)
