### ISSUE TITLE
dashboard unreachable should only print once per build

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#495]
$ bazel build go/pkg/...
INFO: Results are being streamed to http://localhost:8082/result/2ef786ec-75f5-4dab-889d-8b5a15bfa401
Error sending results to http://localhost:8082: Connection to http://localhost:8082 refused
Error sending results to http://localhost:8082: Connection to http://localhost:8082 refused
Error sending results to http://localhost:8082: Connection to http://localhost:8082 refused
INFO: Found 5 targets...
[1 / 16] Creating source manifest for //go/pkg:lib_test

**Comment by damienmg** [comment]
This is fixed at head normally.

**Comment by damienmg** [comment]
Marking as fixed as per offline discussion, reopen if it does happens at head.
