### ISSUE TITLE
Installation Bazel using Scoop package manager on Windows

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#4950]
### Description of the problem / feature request:

Hi.

I'm maintaining Bazel Scoop package. Can you add it to this page?
https://docs.bazel.build/versions/master/install-windows.html

Scoop is Windows package manager, it is like Chocolatey, but it is completely free and more developer-specific (and [more](https://github.com/lukesampson/scoop/wiki/Chocolatey-Comparison)).

The recipe is as follows:
```
scoop bucket add user https://github.com/excitoon/scoop-user.git
scoop bucket add versions
scoop install user/bazel
```
P.S.  `versions` repository is needed because Bazel depends on Python 2.

Kind regards,
Vladimir.

### Feature requests: what underlying problem are you trying to solve with this feature?

That will improve convenience of installing Bazel on Windows.

**Comment by dslomov** [comment]
@laszlocsomor wdyt?

**Comment by laszlocsomor** [comment]
I think we can add it!

**Comment by laszlocsomor** [comment]
@excitoon : Would you mind sending a PR with the documentation changes? I'd be happy to review it.

**Comment by excitoon** [comment]
@laszlocsomor Okay, I just didn't know you have documentation in github as well. I'll make that PR soon.

**Comment by laszlocsomor** [comment]
Thanks! Yes, the files are under https://github.com/bazelbuild/bazel/tree/master/site/docs

**Comment by laszlocsomor** [comment]
@excitoon : Are you still interested in adding the links?

**Comment by excitoon** [comment]
Yeah I do. Looks like guys successfully made proper versions for Bazel dependencies (for example common zip.exe for windows did not worked way Bazel expected). And now we can add it even without custom repository:
```
scoop install bazel
```

**Comment by excitoon** [comment]
I'll check everything works fine here: https://github.com/excitoon/scoop-bazel-test and continue after that.

**Comment by excitoon** [comment]
One more thing: bazelbuild/continuous-integration#502 .
