### ISSUE TITLE
Is there a way use -g from single module by bazel build ?

### ISSUE THREAD

**Issue by AyHelloWorld** [bazelbuild/bazel#4952]
I build _pywrap_tensorflow_internal.so have 2.7G big . so that gdb load very slow ,maybe one hour.
I want is there a way use -g from single module by bazel build to reduce the symbols size ?

please help me?

**Comment by jin** [comment]
Hey @AyHelloWorld, we prefer that Bazel questions are asked on [StackOverflow](https://stackoverflow.com/questions/tagged/bazel) tagged with "bazel". We use GitHub to track bugs and feature requests for Bazel.

**Comment by AyHelloWorld** [comment]
ok ths
