### ISSUE TITLE
Bazel plugin support for Android Studio 3.1

### ISSUE THREAD

**Issue by oferb** [bazelbuild/bazel#4954]
### Description of the problem / feature request:

Bazel plugin is not supported in Android Studio 3.1 ([released March 26](https://android-developers.googleblog.com/2018/03/android-studio-3-1.html)).

![image](https://user-images.githubusercontent.com/5137671/38198793-d9b74388-3696-11e8-8a2c-1952d4dc8750.png)

**Comment by jin** [comment]
@brendandouglas

**Comment by jin** [comment]
The plugin repository is at https://github.com/bazelbuild/intellij, can you please open an issue there instead?

**Comment by oferb** [comment]
Sure, here it is: https://github.com/bazelbuild/intellij/issues/278
