### ISSUE TITLE
ci.bazel.io is failing

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#496]
Log: http://ci.bazel.io/job/Tutorial/PLATFORM_NAME=linux-x86_64/lastBuild/console

____Loading package: third_party/java/jarjar
ERROR: DEFAULT.WORKSPACE:61:1: no such package '@default_android_tools//tools/android': /home/ci/.cache/bazel/_bazel_ci/install/aa9232d464632d1aeaa807b333e3069d/_embedded_binaries/android_tools (No such file or directory) and referenced by '//external:android/stubify_manifest'.
ERROR: Loading failed; build aborted.

**Comment by damienmg** [comment]
Lukacs is already working on a fix.

**Comment by damienmg** [comment]
:) fix is being submitted waiting for sheriff exporting it :)

**Comment by laszlocsomor** [comment]
pushing now
