### ISSUE TITLE
experimental_strict_action_env should include sysctl on Mac OS X

### ISSUE THREAD

**Issue by evanj** [bazelbuild/bazel#4961]
### Description of the problem / feature request:

Python tools (and others?) expect "sysctl" to be available on PATH. For example, numpy executes `sysctl hw` to detect the number of CPUs. On Mac OS X, the full path is `/usr/sbin/sysctl`. This path is added by default to users PATH (see `man path_helper`). It should be included in `--experimental_strict_action_env=true`, at least on Mac OS X.

Example uses of "sysctl" with no path:

* Numpy C code detecting AVX: https://github.com/numpy/numpy/blob/c90d7c94fd2077d0beca48fa89a423da2b0bb663/numpy/_build_utils/src/apple_sgemv_fix.c#L66
* Numpy Python code detecting the number of CPUs: https://github.com/numpy/numpy/blob/663094532de48e131793faaa0ba06eb7c051ab47/numpy/distutils/cpuinfo.py#L367

The code in Bazel does not include this path:

https://github.com/bazelbuild/bazel/blob/b0440164eda858fa0e14f623780a00b30e20ebf7/src/main/java/com/google/devtools/build/lib/bazel/rules/BazelConfiguration.java#L172

If this seems like a reasonable change, I'd be happy to attempt to submit a patch.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a `py_test` that imports `numpy`. It will print `sh: sysctl: command not found`, and will fail to detect the number of CPUs. Since it is hard to import third-party libraries with the built-in Python rules, here is a small reproduction that I extracted from the numpy code. Run this as a `py_test` target:

```python
import commands

def main():
    # https://github.com/numpy/numpy/blob/663094532de48e131793faaa0ba06eb7c051ab47/numpy/distutils/cpuinfo.py#L32    
    status, output = commands.getstatusoutput('sysctl hw')
    print 'status:', status
    print 'output:'
    print output

    if status != 0:
        raise Exception('status should have been 0')


if __name__ == '__main__':
    main()
```

It will fail with `--experimental_strict_action_env=true`:

```
==================== Test output for //:sysctl_example:
status: 32512
output:
sh: sysctl: command not found
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_evanjones/edfcf9007cb655e72ea9c8745cba8682/bazel-sandbox/5592734835260174489/execroot/__main__/bazel-out/darwin-fastbuild/bin/sysctl_example.runfiles/__main__/sysctl_example.py", line 15, in <module>
    main()
  File "/private/var/tmp/_bazel_evanjones/edfcf9007cb655e72ea9c8745cba8682/bazel-sandbox/5592734835260174489/execroot/__main__/bazel-out/darwin-fastbuild/bin/sysctl_example.runfiles/__main__/sysctl_example.py", line 11, in main
    raise Exception('status should have been 0')
Exception: status should have been 0
================================================================================
```

### What operating system are you running Bazel on?

Mac OS X 10.13.4

### What's the output of `bazel info release`?

```
release 0.11.0
```

**Comment by benjaminp** [comment]
Probably the easiest solution is to set `--test_env=PATH=/usr/bin:/bin:/usr/sbin` (or whatever you need).

**Comment by evanj** [comment]
Thanks, this is what I've done in our `tools/bazel.rc`. My point is that since `sysctl` is on a user's path on a "clean install" of Mac OS X, various third-party tools assume this will be true. It would be nice if Bazel's defaults matched the platforms. Alternatively, maybe Bazel should explicitly document what its default environment looks like? E.g. I could imagine saying something like "tests only get the [LSB common commands](https://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/command.html)" and everything else must be referenced somehow? In this case, the `py_*` rules will need to provide sysctl on Mac OS X to make `multiprocessing` and `numpy` work correctly.

**Comment by brandjon** [comment]
On review I think this is a matter for the owners of strict_action_env, not Python.
