### ISSUE TITLE
runfiles conflicts print an ERROR message but don't fail the build

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#4965]
```
$ cat rule.bzl
def _will_break(ctx):
    ctx.actions.write(ctx.outputs.executable, '')
    other_file = ctx.actions.declare_file('other-file')
    ctx.actions.write(other_file, '')
    return struct(runfiles=ctx.runfiles(symlinks={ctx.outputs.executable.short_path: other_file}))

will_break = rule(
    executable = True,
    implementation = _will_break,
)
$ cat BUILD
load(':rule.bzl', 'will_break')
will_break(name='x')
$ bazel  --batch build //:x
INFO: Analysed target //:x (4 packages loaded).
INFO: Found 1 target...
ERROR: /home/benjamin/repos/k/BUILD:2:1: overwrote runfile x, was symlink to /home/benjamin/.cache/bazel/_bazel_benjamin/c65d72cc374bbf6340b06c981e4234e9/execroot/__main__/bazel-out/k8-fastbuild/bin/other-file, now symlink to /home/benjamin/.cache/bazel/_bazel_benjamin/c65d72cc374bbf6340b06c981e4234e9/execroot/__main__/bazel-out/k8-fastbuild/bin/x
Target //:x up-to-date:
  bazel-bin/x
INFO: Elapsed time: 1.131s, Critical Path: 0.02s
INFO: 1 process, local.
INFO: Build completed successfully, 5 total actions
$ echo $?
0
```
Generally, I expect a non-zero exit code if an `ERROR` message is printed.

**Comment by benjaminp** [comment]
Shall we reopen this, since 0e81f9aad49215fe4a13092e64384d9c0ef1ba76 reverted the fix?

**Comment by ptarjan** [comment]
+1 this was surprising to me that it wasn't failing the build

**Comment by dws-uber** [comment]
+1 this still happens in bazel-1.1.0

**Comment by jlisee** [comment]
Could we re-open this issue?  We are hitting it in 3.1.0, and in our case it's definitely signals bugs.  Our of developers are using dependencies together they should not.  We have to put together some unpleasant checks to make sure these don't creep in, but they are slow and extra code to maintain.

What about adding this back in with a compatibility flag like `--experimental_no_runfile_conflits` that we transition to in the future?  Similar to the legacy runfiles transition.

**Comment by thesayyn** [comment]
Ideally the case should not end up being a conflict. I'd expect bazel to either put `ctx.actions.symlink artifact` into runfiles.symlinks dict or handle the case above. 

I understand why bazel behaves the way it does right now but it should be improved. 

I see three things that could be done here to improve this weird edge case;

- Do not print an `ERROR` if a symlink points to same path eventually. Conflict checker would have follow the chain of symlinks in this case.

- Artifact created by the combination of `declare_file` / `declare_symlink` and `ctx.actions.symlink` should designate the declared artifact as symlink.  perhaps a new property can be added to `Artifact` class called `is_symlink` to determine whether its a symlink. similar to `is_source` `is_directory` 

- Artifact that is output of `SymlinkAction` should go into `symlinks` dict of runfiles.

**Comment by benjaminp** [comment]
In conclusion, 1e9c127d9dff47b7f904d296f2c1accf0aa1ba87 deleted the warning.
