### ISSUE TITLE
--test_filter doesn't work for py_test

### ISSUE THREAD

**Issue by jasharpe** [bazelbuild/bazel#4973]
### Description of the problem / feature request:

Bazel test's `--test_filter` flag doesn't do the right thing for py_test.

### Feature requests: what underlying problem are you trying to solve with this feature?

Want to run a single test case from a Python unittest.TestCase.

### What operating system are you running Bazel on?

This problem seems to exist on all operating systems.

### What's the output of `bazel info release`?

release 0.11.1

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

The fix is probably simple. Here's how you run a single test case for a py_test today. If you have `class MyTest(unittest.TestCase)` that has method `testFoo`, then you provide this flag to the Bazel test invocation of the py_test:

`--test_arg=MyTest.testFoo`

`--test_filter=MyTest.testFoo` for py_test should simply be implemented as passing its argument through unchanged as a test arg.

**Comment by benjaminp** [comment]
`--test_filter` is something that must be supported in the test runner and framework. Since Bazel doesn't provide any Python test runner, I don't see how Bazel can actually fix this.

**Comment by brandjon** [comment]
Likely related to #3413.
