### ISSUE TITLE
--apple_bitcode flag ineffective on iOS targets

### ISSUE THREAD

**Issue by th0br0** [bazelbuild/bazel#4982]
(originally posted as https://github.com/bazelbuild/rules_apple/issues/163)

When creating an `apple_static_library` target like [1] and building this via `bazel build --apple_bitcode=embedded --ios_multi_cpus=arm64 -c opt //:myappletarget` the bitcode is not being included in the actual build causing issues when trying to run the code on-device similar to:

```
/Project/myapplelibrary.a(lib1.o) does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
```

However, specifying `--copt=-fembed-bitcode` causes a conflict with the `-fdata-sections` and `-ffunction-sections` flags that bazel uses by default.

How can this be resolved? Is there some way I can resolve this temporarily?
This is for `bazel 0.11.1` running on MacOS with latest released XCode.

The references to `b/73546952` and `b/35091927` at https://github.com/bazelbuild/rules_apple/blob/master/test/ios_application_test.sh#L838 and https://github.com/bazelbuild/rules_apple/blob/master/test/configurations.bzl#L21 make me believe you're tracking this issue internally already?

[1]
```
cc_library(
  name="mynativedependency"],
  srcs=["lib1.c"], hdrs=["lib1.h"])

apple_static_library(
    name="myappletarget",
    deps=[":mynativedependency"],
    platform_type="ios",
    minimum_os_version="9.0",
    visibility = ["//visibility:public"])
```

**Comment by sergiocampama** [comment]
this is an issue with `cc_library` not detecting the `--apple_bitcode` flag and/or the C++ crosstool being incompatible with bitcode

**Comment by keith** [comment]
I've started to take a stab at this https://github.com/bazelbuild/bazel/pull/7356

**Comment by stristr** [comment]
This appears to be solved in 0.24.

**Comment by keith** [comment]
Yep! Thanks!

**Comment by temrich** [comment]
I am still seeing this issue with Bazel 0.24 and 0.24.1. Steps to reproduce:

1. Clone the TensorFlow GitHub [repo](https://github.com/tensorflow/tensorflow).
2. Run the configure script:
`python configure.py` (can hit enter for all questions except for the last one that asks "Do you wish to build TensorFlow with iOS support?", enter `y`)
3. Build the `ios_static_framework` using `-c opt` and the Bitcode flags:
```
bazel build tensorflow/lite/experimental/ios:TensorFlowLiteC_framework -c opt --ios_multi_cpus=x86_64,armv7,arm64 --apple_bitcode=embedded --copt=-fembed-bitcode
```

Produces the following error:
```
tensorflow/tensorflow/lite/kernels/BUILD:115:1: C++ compilation of rule '//tensorflow/lite/kernels:kernel_util'
clang: error: -ffunction-sections is not supported with -fembed-bitcode
clang: error: -fdata-sections is not supported with -fembed-bitcode
```

Let me know if I am missing something here? Thank you!

**Comment by rajivshah3** [comment]
@temrich does #7623 fix the issue for you? I may have run into the same issue when I built Bazel from source off of f8e38d1

**Comment by temrich** [comment]
@rajivshah3 yes that fixes the issue for me. Thank you!!
