### ISSUE TITLE
Remote execution failures are hard to introspect and debug

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel#4983]
### Feature request:

I'm trying to get remote execution working for C++ on my local machine, using Bazel's bundled remote worker. Something is going wrong but there's not much available in the way of debug logs.

Once the logging improvements in https://github.com/bazelbuild/bazel/issues/4891 have gotten far enough to support basic debug logging, can we get a few log.info() calls into the gRPC execution/caching path? Even just printing out the request, response, and error messages would be very useful.

Here's the current non-useful output, for comparison:

```
$ bazel --host_jvm_args=-Dbazel.DigestFunction=SHA256 build --spawn_strategy=remote --remote_executor=localhost:8080 --remote_cache=localhost:8080 :hello --verbose_failures
[...]
ERROR: /private/var/tmp/_bazel_jmillikin/58f7b685a983512db52ce88a295e38fd/external/bazel_cc_test/BUILD:2:1: C++ compilation of rule '@bazel_cc_test//:hello_lib' failed (Exit 34). Note: Remote connection/protocol failed with: execution failed: com.google.devtools.build.lib.remote.Retrier$RetryException: Call failed after exhausting retry attempts: 5
	at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:242)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:101)
	at com.google.devtools.build.lib.remote.GrpcRemoteCache.getCachedActionResult(GrpcRemoteCache.java:356)
[...]
Caused by: io.grpc.StatusRuntimeException: CANCELLED: HTTP/2 error code: CANCEL
Received Rst Stream
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:210)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:191)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:124)
	at com.google.devtools.remoteexecution.v1test.ActionCacheGrpc$ActionCacheBlockingStub.getActionResult(ActionCacheGrpc.java:279)
	at com.google.devtools.build.lib.remote.GrpcRemoteCache.lambda$getCachedActionResult$4(GrpcRemoteCache.java:359)
	at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:220)
	... 21 more
Target //:hello failed to build
```

### What operating system are you running Bazel on?
MacOS

### What's the output of `bazel info release`?
`release 0.11.1-homebrew`

**Comment by ola-rozenfeld** [comment]
Yes, we are actually adding a detailed gRPC log of all requests and responses. Most of the changes are committed by now (e.g. https://github.com/bazelbuild/bazel/commit/8fd53fba63971f58beab889dd4f3d46726dde672), with a few more to come. When it's all released, I will update this bug with instructions on how to use the feature.

That said, though -- in your particular case, I highly doubt you'll get anything more useful than:

Caused by: io.grpc.StatusRuntimeException: CANCELLED: HTTP/2 error code: CANCEL
Received Rst Stream

This is the root cause of the error. I don't think seeing the request message will give you anything interesting. I would advise at this point to check the remote worker logs -- does the call even reach the remote worker? (I doubt it). Can you paste the entire command line? I might be able to spot what's wrong. For example, you have to use   -- auth_enabled=false and --tls_enabled=false with the remote worker.

**Comment by ola-rozenfeld** [comment]
Oh, sorry, you did paste the command line -- do you see anything in the remote worker log (run with --debug)? I see the auth options are correct by default. Also, does the remote_execution_test.sh pass on the same machine? It does the exact same thing, using the remote worker as both the cache and executor for a sample build: https://github.com/bazelbuild/bazel/blob/master/src/test/shell/bazel/remote/remote_execution_test.sh#L98
I'm wondering whether https://github.com/bazelbuild/bazel/blob/master/src/test/shell/bazel/remote/remote_execution_test.sh#L99 is related.

**Comment by jmillikin-stripe** [comment]
I didn't see any logs in the remote worker, and I suspect it's something going wrong in the network layer. My assumption is that the real log messages (like "can't resolve host" or "connection refused") are being swallowed, and replaced by the error about exceeding number of retries.

I think the MacOS comment in `remote_execution_test.sh` is unrelated, since I'm not trying to use any XCode features (it's just plain C++).

**Comment by ola-rozenfeld** [comment]
Exceeding retries error message always wraps the underlying error, never
replaces it. I agree that it sounds like a network problem. Does
remote_execution_test.sh pass or fails with same error?

**Comment by jmillikin-stripe** [comment]
Also, here's various things I tried that generated differently-shaped error messages. They might be useful for diagnosis:

(1) If I shut down the worker and run `bazel build`, I get a proper "connection refused" -- so when the worker is running then Bazel is able to establish a socket:
```
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:8080
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
```

(2) If I write garbage directly to the worker port, I get an HTTP/2 failure:
```
$ echo 'testing' | nc 127.0.0.1 8080
???fHTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 74657374696e670a
```

(3) I tried listing the worker's gRPC endpoints to verify the gRPC server is working. It failed, but this may be due lack of introspection endpoints.
```
$ grpc_cli ls 127.0.0.1:8080
Received an error when querying services endpoint.
```

**Comment by ola-rozenfeld** [comment]
Okay, if the remote_execution_test passes, then something is happening
differently now from how the test does it. The test does the exact
same thing you're trying to do: it starts the worker, and uses it to
build/test a simple hello test (e.g.
https://github.com/bazelbuild/bazel/blob/master/src/test/shell/bazel/remote/remote_execution_test.sh#L154).
Can you please try adding the --auth_enabled=false and --tls_enabled=false
arguments, just in case you have a hidden bazelrc somewhere that overrides
these?
A printout of all the command line flags that Bazel actually ran with may
be helpful too (one way I know how to do it is via --build_event_text_file).

Thank you!

**Comment by jmillikin-stripe** [comment]
[bep.txt](https://github.com/bazelbuild/bazel/files/1900339/bep.txt) is the output of running the original build command with `--auth_enabled=false --tls_enabled=false`

**Comment by ola-rozenfeld** [comment]
Hmm, everything seems fine! I'm sorry I don't have a Mac to help with debugging, but what I'd do is try to converge the two builds (working and non-working) step by step in order to see what the difference is.

**Comment by jmillikin-stripe** [comment]
This has been resolved, thanks! The current version of Bazel has much improved debugging compared to v0.11. If I encounter any especially tricky failures in the future, I'll open a separate bug.
