### ISSUE TITLE
Support for asan/tsan/ubsan on Apple builds on OS X crosstool

### ISSUE THREAD

**Issue by rahul-malik** [bazelbuild/bazel#4984]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Add “features” in OS X crosstool to enable usage of TSAN, UBSAN and ASAN. There have begun api changes in rules_apple but they are not functional until the crosstool supports these features 

### Feature requests: what underlying problem are you trying to solve with this feature?

I would like to run tests using clang sanitizers.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

This is a feature request. You cannot specify a “feature” from the CLI for this currently.
### What operating system are you running Bazel on?

> Replace this line with your answer.

### What's the output of `bazel info release`?

0.12.0rc2

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by hlopko** [comment]
@sergiocampama @trybka

**Comment by keith** [comment]
https://github.com/bazelbuild/bazel/pull/12772
