### ISSUE TITLE
Add the ability to override git_repository commit for integration testing

### ISSUE THREAD

**Issue by greggdonovan** [bazelbuild/bazel#4993]
### Description of the feature request:

I'd like to add an integration test to [`rules_k8s`](https://github.com/bazelbuild/rules_k8s) that allows an updated commit SHA to be passed in at the command-line to override the default commit hash of `rules_docker` in the [`WORKSPACE`](https://github.com/bazelbuild/rules_k8s/blob/master/WORKSPACE#L16:L20). The motivation is to have a CI test that checks if `rules_docker` contains a regression that effects `rules_k8s`.

For `rules_scala`, I did something similar [via `--override_repository`](https://github.com/bazelbuild/rules_scala/blob/8117089e8969861b1774485cb49ab95b54c2b9c9/test_intellij_aspect.sh#L23), but that seems more complex than should be needed for this case.

### Feature requests: what underlying problem are you trying to solve with this feature?

Bazel builds often have the want to test their build against multiple versions of WORKSPACE dependencies: the current Git SHA they pin to and the latest version. Testing the latest version allows integration testing: you can see if a forthcoming update to a dependency breaks your tests.

### What operating system are you running Bazel on?

macOS, CentOS 7.3

### What's the output of `bazel info release`?

release 0.11.1-homebrew

###  Have you found anything relevant by searching the web?

Per [@mhlopko and @ittaiz on StackOverflow](https://stackoverflow.com/questions/49721889/bazel-how-to-override-git-repository-commit-for-integration-testing/49755678#49755678), this feature does not yet exist.

### Any other information, logs, or outputs that you want to share?

Using `--override_repository` is possible, but far more involved than I would like so override a Git SHA in the WORKSPACE. Perhaps a `buildozer` like syntax would work for overrides to the WORKSPACE dependencies?

**Comment by ittaiz** [comment]
Btw, I think this is classic for any bazel many repo story.
Currently we’re planning on using override-repository on GCB but the above
suggestion sounds better since it simplifies the CI setup

**Comment by or-shachar** [comment]
+1 
still very relevant!
