### ISSUE TITLE
no such package '@io_bazel_rules_closure//closure' when 'bazel build' for tensorflow

### ISSUE THREAD

**Issue by tianxiawuzhe** [bazelbuild/bazel#4996]
I have check issues including 'io_bazel_rules_closure' text, could add proxy for this problem.
But I installed tensorflow with no network, thus proxy could not solve this problem.
I have download io_bazel_rules_closure.tar.gz , and how can i install this package ?
many thanks.

**Comment by jin** [comment]
In this situation, unzip the rules_closure tarfile to a directly, say `/path/to/closure`.

Next, change the [`http_archive`](https://docs.bazel.build/versions/master/be/workspace.html#http_archive) rule in the `WORKSPACE` file to a [`local_repository`](https://docs.bazel.build/versions/master/be/workspace.html#local_repository) rule. From this:

https://github.com/tensorflow/tensorflow/blob/f9c5e71104cb30583127fdc918591cc7604f17ca/WORKSPACE#L3:L11

to this: 

```
local_repository(
    name = "io_bazel_rules_closure",
    path = "/path/to/closure",
)
```

If you have further questions, please ask them [StackOverflow](https://stackoverflow.com/questions/tagged/bazel) and tag your questions with `bazel`. You'll be able to get more help over there.
