### ISSUE TITLE
Allow configuring scalac location

### ISSUE THREAD

**Issue by orrsella** [bazelbuild/bazel#502]
As I understand it, scalac is [currently hard-coded](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/scala/scala.bzl#L22) to be found in `/usr/bin/scalac`. This in and of itself isn't great, but is worsened by the fact that the new version of OS X 10.11 introduces ["rootless" mode](http://apple.stackexchange.com/questions/193368/what-is-the-rootless-feature-in-el-capitan-really), which doesn't allow modifying anything in `/usr/bin`, among other directories, even when using `sudo`. This means that a symlink can't be added.

Would be best to allow configuring the location of `scalac`, or at least hard-coding it to somewhere in  `/usr/local`.

**Comment by hanwen** [comment]
this should use a downloaded toolchain. Kristina even wrote how to do it at 

http://www.kchodorow.com/blog/2015/08/12/tutorial-how-to-write-scala-rules-for-bazel/

"adding a dep for the scala compiler".

Can you see if the description over there works? If yes, we will gladly take a change that implements it.

**Comment by orrsella** [comment]
What would be a better reference implementation: @kchodorow's post or the [Groovy](https://github.com/bazelbuild/bazel/tree/master/tools/build_defs/groovy) rule?

**Comment by kchodorow** [comment]
Whichever makes the most sense to you.

**Comment by kchodorow** [comment]
There's now a pull request for adding this at https://bazel-review.googlesource.com/#/c/2410/.

**Comment by damienmg** [comment]
The PR has been merged so I believe this is resolved.

@orrsella please ping if this is not satisfactory.
