### ISSUE TITLE
config_setting incorrectly using android_cpu

### ISSUE THREAD

**Issue by anavabi** [bazelbuild/bazel#5020]
### Description of the problem / feature request:
Somewhere between bazel version 0.11.1 and 0.12.0, the config_settings seem to have gone wrong, and incorrectly use android_cpu toolchain. This is best explained with a small stand-alone example:

BUILD
```
config_setting(
    name = "android_cpu_arm",
    values = {"android_cpu": "armeabi-v7a"},
    visibility = ["//visibility:public"],
)

cc_library(
  name = "cc_headers",
  srcs = [],
  hdrs = select({
    ":android_cpu_arm": [],
    "//conditions:default": ["header.h"]
  }),
)

cc_binary(
  name = "cc_test",
  srcs = ["cc_test.cpp"],
  deps = [":cc_headers"]
)
```

header.h
`#define FOO "WORLDSSS!!"`

cc_test.cpp
```
#include<iostream>
#include "header.h"
using namespace std;

int main()
{
  cout<<"Hello "<< FOO << "\n";
  return 0;
}
```

In _select_ in the BUILD file, if the config_setting is android_cpu_arm, we don't include the header we need and we fail, and if not, we go to default and the build succeeds.

On bazel 0.11.1 this succeeds (i.e. the _select_ goes to the default).
bazel clean; bazel build cc_test

On bazel 0.12.0 and beyond this fails (i.e. the _select_ goes to android_cpu_arm):
bazel clean; bazel build cc_test
...
Analyzing: target //:cc_test (6 packages loaded)
INFO: Analysed target //:cc_test (6 packages loaded).
INFO: Found 1 target...
bazel: Entering directory `/usr/local/google/home/navabi/.cache/bazel/_bazel_navabi/d6d87394bde241eebe270ea2feb7e8b4/execroot/__main__/'
[0 / 6] [-----] BazelWorkspaceStatusAction stable-status.txt
ERROR: /usr/local/google/home/navabi/studio/bazel_jni/BUILD:16:1: C++ compilation of rule '//:cc_test' failed (Exit 1)
cc_test.cpp:3:10: fatal error: header.h: No such file or directory
 #include "header.h"
          ^~~~~~~~~~
compilation terminated.

It seems to me the new bazel version (0.12.0) is incorrectly using android_cpu toolchain to compile.
This bug is currently stopping Android Studio team upgrading their bazel version.

### What operating system are you running Bazel on?
Linux

### What's the output of `bazel info release`?
For the bazel version 0.12.0 which is broken:
release 0.12.0

**Comment by anavabi** [comment]
I originally found this issue with bazel 0.13.0rc1

**Comment by jin** [comment]
@ahumesky just a quick glance, possibly due to the default `android_cpu` switch?

**Comment by ahumesky** [comment]
Yeah, this is because the default value of `--android_cpu` changed from `armeabi` to `armeabi-v7a` in 0.12.  To get back the old behavior, you can set `--android_cpu=armeabi`.

For a longer term solution, it depends on how you're doing your android builds. If you're setting `--crosstool_top` to a specific crosstool, you can change the `config_setting` to key on `--crosstool_top` (e.g., the crosstool provided from the android_ndk_repository rule). You can also key on plain `--cpu`, depending on what other platforms you're targeting.

**Comment by gregestren** [comment]
Is there anything else we should do for this issue?

**Comment by jin** [comment]
No, the workaround here is to make the appropriate configuration changes that assume the default value of `android_cpu` is `armeabi-v7a`.

The default value is documented in https://docs.bazel.build/versions/master/command-line-reference.html#flag--android_cpu, and has been the case for 7 Bazel releases now.
