### ISSUE TITLE
Move java transitivity from --strict_java_deps to rule attribute.

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/bazel#5021]
Currently Java transitivity is controlled by the --strict_java_deps flag, making it essentially impossible to write portable BUILDs using java_*.

* If my workspace assumes transitivity, then it fails for consuming workspaces that use --strict_java_deps=off due to missing classpath entries.
* If my workspace assumes non-transitivity, then it fails for consuming workspaces that use --strict_java_deps=error due to unused direct deps.

java_library cannot be used. The only solution today today is to write my own java_library replacement that takes matters into its own hands. Which is what java_library should have had all along: transitivity configured by attribute. (For compatibility, it could default to current --strict_java_deps behavior if not set.)

---

Side note: and if we replaced the "strict deps" part of --strict_java_deps with a toolchain, we could have one less of the thousands of flags in Bazel core.

**Comment by ittaiz** [comment]
My 2c are that this is an org level decision which usually has global
impact (a leaf usually has zero motivation for enabling strict deps) so we
still need it as a flag

**Comment by pauldraper** [comment]
I'll agree that --strict_java_deps makes sense in one workspace (or one org).

The issue is when you try to do this OSS thing.

Perhaps the flag or a toolchain could have a default.

**Comment by cushon** [comment]
> If my workspace assumes non-transitivity, then it fails for consuming workspaces that use --strict_java_deps=error due to unused direct deps.

I don't understand this part, can you expand on it? Unused direct deps are not an error. And the deps required for `--strict_java_deps=error` are not unused.

I understand the problem with depending on workspaces that use `--strict_java_deps=off` from workspaces that use `--strict_java_deps=error`, but I wouldn't expect the reverse to also cause problems.

Also--this seems like a general issue with top-level build flags and workspaces, and not something specific to how strict java deps is configured. Maybe there needs to be a per-workspace `.bazelrc` mechanism.

**Comment by pauldraper** [comment]
> I don't understand this part, can you expand on it? Unused direct deps are not an error. 

Hm. I thought it was. rules_scala experience bleeding over. (Yet another difference rules_scala has on this flag.)

Since it's not, I can author portable BUILDs, by using `--strict_java_deps=off`.

> Also--this seems like a general issue with top-level build flags and workspaces, and not something specific to how strict java deps is configured. Maybe there needs to be a per-workspace .bazelrc mechanism.

That's one solution, sure.

Most Bazel flags legitimately can be global, with no ill consequence. Generally, they don't affect how you author BUILD files. Analogous to how the choice of compiler flags is mostly independent of the source (and certainly does not make a 3x difference in the amount of source code written).

`--strict_java_deps` significantly affects how BUILDs are authored. `deps` means something very different depending on this flag. IMO, it's like a compile flag that turns all your ints into floats.

**Comment by ittaiz** [comment]
Unused deps isn’t a rules scala feature yet, right?

**Comment by pauldraper** [comment]
Sorry, I believe this issue is misinformed. #4821 seeks (unwisely, I believe) to add a `--strict_java_deps`-enabled intransitive mode.
