### ISSUE TITLE
Executing scala tests

### ISSUE THREAD

**Issue by orrsella** [bazelbuild/bazel#503]
Any existing workaround to use `java_test` for executing scala tests (similar to https://github.com/bazelbuild/bazel/issues/443), or is there a different approach to substitute the lack of  `scala_test` for now? Scala test classes usually use `org.junit.runner.RunWith` and a custom `JUnitRunner` to execute (like this one for [specs2](https://github.com/etorreborre/specs2/blob/master/junit/src/main/scala/org/specs2/runner/JUnitRunner.scala)).

Simple example:

```scala
package com.example

import org.junit.runner.RunWith
import org.specs2.mutable.Specification
import org.specs2.runner.JUnitRunner

@RunWith(classOf[JUnitRunner])
class HelloWorldTest extends Specification {

  "HelloWorld" should {
    "have the correct message" in {
      HelloWorld.message must_== "Hello world!"
    }
  }
}
```

**Comment by hanwen** [comment]
you could create a scala_test that expands into java_test that imports the jar generated by scala_binary?

**Comment by palladius** [comment]
Added this issue as b/25141720.
