### ISSUE TITLE
Provide skylint as part of releases

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/bazel#5030]
For teams that develop rule sets, it would be nice if there was a place to get skylint just like we can get buildozer/buildifer binaries.  Then they can be used as part of CI on pull request to validate the patches.

https://docs.bazel.build/versions/master/skylark/skylint.html mentions how to get it, but it requires checking out all of bazel and building it which seems pretty overkill for trying to validate/screen PRs.

**Comment by alexeagle** [comment]
+1 I just waited to download 84.31M so I can run skylint.

**Comment by alexeagle** [comment]
@thomasvl you might be interested in our solution for Angular where we run our CI in a docker container that has skylint and buildifier already compiled:
https://hub.docker.com/r/angular/ngcontainer/

**Comment by ittaiz** [comment]
Isn’t this a duplicate of #4086?

**Comment by thomasvl** [comment]
> Isn’t this a duplicate of #4086?

Maybe?  I was hoping it would be like https://github.com/bazelbuild/buildtools/releases which just lets you pick up some binaries of the tool instead of having a full bazel install.

Also, the manifest for picking up the _latest_ builds (https://storage.googleapis.com/bazel-builds/metadata/latest.json) are raw binaries, not installers.

**Comment by hchauvin** [comment]
IMO this is more appropriate than #4086.  The latter would tie too much the linting rules to the version of Bazel, and one should be able to upgrade these two separately: you might want to delay code cleaning coming with a new linting rule, but still should be able to consume new features in Bazel.

**Comment by aiuto** [comment]
Yes. We definitely want skylint and buildifier as pre-built binaries. They are end-user tools and should not require a Bazel source download to use them. That said, we should consider making them a distinct download if we want to keep the core download small.

**Comment by laurentlb** [comment]
For Buildifier releases, see https://github.com/bazelbuild/buildtools/releases

Skylint is going to be retired in favor of Buildifier.

**Comment by thomasvl** [comment]
Doesn't skylint provide things that don't make sense the current buildifier?  i.e. - warnings about naming conventions, etc.  i.e. - not purely formatting things.  Will the "check" mode do more that formatting or will there be a new "lint" mode to catch these sorta things?

**Comment by laurentlb** [comment]
There is now `buildifier --lint=warn`

https://github.com/bazelbuild/buildtools/blob/master/buildifier/README.md#linter

**Comment by aiuto** [comment]
We should change the bug to "Provide buildifier as part of releases"
(unless that already exists)
