### ISSUE TITLE
Documentation for remote GCS caching does not mention --google_default_credentials option

### ISSUE THREAD

**Issue by numbsafari** [bazelbuild/bazel#5046]
### Description of the problem / feature request:

The [documentation for remote caching using GCS](https://github.com/bazelbuild/bazel/blob/master/site/docs/remote-caching.md#user-content-google-cloud-storage) fails to indicate how to tell bazel to use your local gcloud credentials. I was able to discover this was possible by reviewing the code commit for adding GCS remote caching support.

### Feature requests: what underlying problem are you trying to solve with this feature?

It would be nice if the documentation noted the existence of the `--google_default_credentials` and how it impacts remote GCS caching.

### What operating system are you running Bazel on?

Mac OS. Linux.

### What's the output of `bazel info release`?

`release 0.12.0-homebrew`

###  Have you found anything relevant by searching the web?

I found the information in the [comments on the original commit](https://github.com/bazelbuild/bazel/commit/dd11a0e2e7a143f89bca1be6e4cd56df0640dbe0#commitcomment-26398380).

### Any other information, logs, or outputs that you want to share?

Nope, other than thank you for all the hard work you've done on bazel.

**Comment by jamesonjlee** [comment]
i had the same issue, I ended up finding the flag `--google_default_credentials`

**Comment by nareddyt** [comment]
I believe this issue is resolved, `--google_default_credentials` is now in the documentation linked in the original issue.

**Comment by jin** [comment]
`--google_default_credentials` is documented in the linked page.
