### ISSUE TITLE
bazel 0.12 broke pkg_rpm with dependency on http_file

### ISSUE THREAD

**Issue by ixdy** [bazelbuild/bazel#5049]
### Description of the problem / feature request:
In kubernetes/kubernetes we [download a tarball through `http_file` as an external dependency](https://github.com/kubernetes/kubernetes/blob/17fec00b8915dbffac40b9eb481516a66092ef3e/build/root/WORKSPACE#L53-L57) and use it as a [data dependency in a `pkg_rpm` rule](https://github.com/kubernetes/kubernetes/blob/17fec00b8915dbffac40b9eb481516a66092ef3e/build/rpms/BUILD#L40-L49).

In the [rpm spec](https://github.com/kubernetes/kubernetes/blob/17fec00b8915dbffac40b9eb481516a66092ef3e/build/rpms/kubernetes-cni.spec), we then extract this file from the cwd, since that's where it existed up to bazel 0.12:

```
%prep
mkdir -p ./bin
tar -C ./bin -xz -f cni-plugins-amd64-v0.6.0.tgz
``` 

Starting in bazel 0.12, this is failing:
```
Executing(%prep): /bin/sh -e /tmp/tmpcErdSE/TMP/rpm-tmp.oojapv
+ umask 022
+ cd /tmp/tmpcErdSE/BUILD
+ mkdir -p ./bin
+ tar -C ./bin -xz -f cni-plugins-amd64-v0.6.0.tgz
tar (child): cni-plugins-amd64-v0.6.0.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
error: Bad exit status from /tmp/tmpcErdSE/TMP/rpm-tmp.oojapv (%prep)
```

Adding a `find` to debug shows that this is now located under `./external/kubernetes_cni/file`.

I went looking in the git history for `pkg_rpm`, and I found https://github.com/bazelbuild/bazel/commit/e4c8509ace6baf5182379738b7834287228116cd, which looked somewhat promising. But that doesn't seem to work in bazel 0.12: 

```
Executing(%prep): /bin/sh -e /tmp/tmpOg9q0l/TMP/rpm-tmp.bIRkcp
+ umask 022
+ cd /tmp/tmpOg9q0l/BUILD
+ find .
.
./external
./external/kubernetes_cni
./external/kubernetes_cni/file
./external/kubernetes_cni/file/cni-plugins-amd64-v0.6.0.tgz
./CHANGELOG.md
+ mkdir -p ./bin
+ tar -C ./bin -xz -f '{cni-plugins-amd64-v0.6.0.tgz}'
tar (child): {cni-plugins-amd64-v0.6.0.tgz}: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
error: Bad exit status from /tmp/tmpOg9q0l/TMP/rpm-tmp.bIRkcp (%prep)
```

It *does* seem to work if I use `pkg_rpm` from bazel tip, though, so I guess maybe that functionality didn't make it into bazel 0.12.

However, it also doesn't work with bazel 0.11. So it seems these changes were not backwards compatible in any way, and the only way I can fix this is by checking multiple paths in the RPM spec, which is frustrating.

### What operating system are you running Bazel on?
Linux

### What's the output of `bazel info release`?
release 0.12.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
```
$ git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
git@github.com:ixdy/kubernetes.git
16c3167040f1d0a739f66ea83c0ee1167887eb4e
16c3167040f1d0a739f66ea83c0ee1167887eb4e
```

cc @katre @philwo

**Comment by ixdy** [comment]
cc @mmikitka too

**Comment by mmikitka** [comment]
@ixdy It looks like the following will help you: https://github.com/bazelbuild/bazel/pull/4747 This PR preserves the source tree in the copying of files to avoid collisions.

**Comment by ixdy** [comment]
Yeah, using `{cni-plugins-amd64-v0.6.0.tgz}` with bazel 0.13.0rc1 works.

I don't like having to ratchet to a particular bazel version, but I guess we can do it if necessary.

It's going to be particularly painful for our release branches; we'll either have to require a maximum bazel version of 0.11, or we'll have to require a minimum bazel version of 0.13, neither of which is ideal.

**Comment by ixdy** [comment]
Ultimately I'm hoping that `pkg_rpm` will move out of the core bazel repo into something like `rules_pkg`, which will give us the ability to version the rules ourselves.

**Comment by katre** [comment]
I think that's definitely the overall goal, but @davidstanke probably knows more about the plan.

**Comment by davidstanke** [comment]
We created the new repo, but progress in that migration seems to be stalled. @ulfjack any thoughts?

**Comment by ulfjack** [comment]
@katre, I think you recently contributed to the packaging rules - can you also help with the migration? @davidstanke What's the target repo?

**Comment by katre** [comment]
I am planning to move the pkg_rpm rules (see https://github.com/bazelbuild/bazel/issues/5089). Once that is done and we know what's involved, we can start on the rest.

@davidstanke do we have a list of packaging rules we want to migrate?

**Comment by aiuto** [comment]
This is obsolete. The rules are moved to github.com/bazelbuild/rules_pkg.
