### ISSUE TITLE
disable visibility from package()

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#505]
it is undocumented, and should be default_visibiliity.

**Comment by laszlocsomor** [comment]
Is there any work to do here besides removing the attribute from the `package()` rule class?

**Comment by hanwen** [comment]
I suppose we might have to do a google internal cleanup; let me open an internal bug..

**Comment by hanwen** [comment]
I looked a bit at this, but does package() inherit default attributes, such as "visibility" ?

**Comment by laszlocsomor** [comment]
Dunno, but it should be easy to find out if you try it out. I'd be surprised if it did though.

**Comment by ulfjack** [comment]
No, it doesn't. It's not like a rule, but there's custom code in
PackageFactory.java to declare the function. I actually don't see a
visibility attribute...

**Comment by hanwen** [comment]
I have no idea how I managed to introduce the bug from 

https://bazel-review.googlesource.com/#/c/2130/2/tools/build_rules/go/BUILD


hanwen@han-wen:~/vc/bazel$ bazel build src:bazel
INFO: Reading 'startup' options from /usr/local/google/home/hanwen/.bazelrc: --watchfs
ERROR: /usr/local/google/home/hanwen/vc/bazel/src/BUILD:2:1: unexpected keyword 'visibility' in call to package(*, default_deprecation = ?, distribs = ?, licenses = ?, default_testonly = ?, default_visibility = ?, features = ?, default_compatible_with = ?, default_restricted_to = ?).
ERROR: no such package 'src': Package 'src' contains errors.
INFO: Elapsed time: 0.110s
