### ISSUE TITLE
Release - July 2018 - Target RC date: 2018-07-02 - name: 0.16.0

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#5058]

**Comment by dslomov** [comment]
@c-parsons lmk if you are not available on these dates

**Comment by c-parsons** [comment]
Made first RC at https://github.com/bazelbuild/bazel/tree/release-0.16.0

**Comment by petemounce** [comment]
Published to chocolatey.

**Comment by aehlig** [comment]
Did we change something to the release process? I couldn't find the distribution archive at the expected https://storage.googleapis.com/bazel/0.16.0/rc1/bazel-0.16.0rc1-dist.zip nor anywhere else.

**Comment by Globegitter** [comment]
@c-parsons any deb packages or sh installers with that release?

**Comment by buchgr** [comment]
Artifacts have been generated. There was a small delay due to CI issues, sorry about that. https://storage.googleapis.com/bazel/0.16.0/rc1/index.html

**Comment by buchgr** [comment]
@c-parsons please cherry-pick https://github.com/bazelbuild/bazel/commit/4c9a0c82d308d5df5c524e2a26644022ff525f3e

**Comment by c-parsons** [comment]
rc2 has been cherrypicked with 4c9a0c8

**Comment by buchgr** [comment]
@c-parsons please cherry-pick d3228b61f633cdc5b3f740b641a0836f1bd79abd

**Comment by mhlopko** [comment]
Pretty please cherry pick https://github.com/bazelbuild/bazel/commit/8ff87c164f48dbabe3b20becd00dde90c50d46f5 (fix for https://github.com/bazelbuild/bazel/issues/5468)

**Comment by aehlig** [comment]
Can we please also cherry-pick 10219659f58622d99034288cf9f491865f818218 and ab1f269017171223932e0da9bb539e8a17dd99ed as these commits fix the build on FreeBSD? Thanks.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by buchgr** [comment]
Release blocker: https://github.com/bazelbuild/bazel/issues/5532

**Comment by c-parsons** [comment]
rc3 has been cherrypicked with: d3228b61f633cdc5b3f740b641a0836f1bd79abd, 8ff87c164f48dbabe3b20becd00dde90c50d46f5, c4622ac9205d2f1b42dac8c598e83113d39e7f11, 10219659f58622d99034288cf9f491865f818218, ab1f269017171223932e0da9bb539e8a17dd99ed, 68e92b45a37f2142c768a56eb7ecfa484b8b22df

**Comment by ianoc** [comment]
https://github.com/bazelbuild/bazel/issues/5572 is likely i think a release blocker too

**Comment by jin** [comment]
https://github.com/bazelbuild/bazel/issues/5648 may be a release blocker due to a bug with `analyze-profile --html`

**Comment by buchgr** [comment]
Please cherry-pick 3842bd39e10612c7eef36c6048407e81bcd0a8fb

**Comment by buchgr** [comment]
#5047 is a blocker. I ll have a fix by tomorrow.

**Comment by c-parsons** [comment]
If I understand correctly, looks like #5572 was present in 0.15.0 so it's a non-blocker.

I am waiting on #5047 to be resolved before creating rc4.
For additional cherry-picks so far for rc4 we have:
f45c224    3842bd3

**Comment by buchgr** [comment]
@c-parsons working late on a fix :-)

**Comment by ianoc-stripe** [comment]
#5572 wasn't present in 0.15.{0,1, 2} since thats what we run internally with distinct host configuration enabled. Though from the state there it looks like this isn't easily fixable, and has a somewhat workaround. So we might just want to note that in the release notes?

**Comment by buchgr** [comment]
please cherry-pick ` bca1912` which fixed #5047

**Comment by c-parsons** [comment]
rc4 is out.
new cherrypicks since rc3:
f45c224 3842bd3 bca1912
Announcement incoming.

**Comment by petemounce** [comment]
rc4 is on chocolatey

**Comment by c-parsons** [comment]
I have pushed release 0.16.0 and announced it. Blog post soon to follow.

@petemounce  Could you please update chocolatey?
@ilovezfs Could you please update Homebrew?

(Thank you both very much!)

**Comment by buchgr** [comment]
ping @vbatts

**Comment by vbatts** [comment]
already on it! 
https://copr.fedorainfracloud.org/coprs/vbatts/bazel/build/782805/

**Comment by schroederc** [comment]
The release notes for 0.16.0 don't mention the update to the embedded JDK which is a breaking change.  https://github.com/google/kythe is broken due to its usage of `-Xbootclasspath/p` to bring in the javac tools jar.

**Comment by buchgr** [comment]
@schroederc sorry about that. Can you please file an issue with a more detailed error description?

**Comment by petemounce** [comment]
Chocolatey is pushed.

**Comment by ilovezfs** [comment]
The build fails on OS X 10.11 (but not on 10.12 or 10.13):
https://github.com/Homebrew/homebrew-core/pull/30653
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/28174/version=el_capitan/consoleFull
https://gist.github.com/ilovezfs/b1aa57dbd9c31bcaf0ce1daaa9378ae6

**Comment by dslomov** [comment]
@c-parsons ptal at OS X situation

**Comment by dslomov** [comment]
Is https://github.com/bazelbuild/bazel/issues/5730 a blocker, do we need a patch release?

**Comment by dslomov** [comment]
Is https://github.com/bazelbuild/bazel/issues/5741 a blocker?

**Comment by dslomov** [comment]
(@c-parsons you are off the hook for OS X)

**Comment by c-parsons** [comment]
What's the state of the OSX situation, then?

**Comment by c-parsons** [comment]
Fix for #5683 should also be cherrypicked.

**Comment by dslomov** [comment]
See https://github.com/bazelbuild/bazel/issues/5777#issuecomment-410967355

**Comment by buchgr** [comment]
@c-parsons 

we have decided that we need to rollback the JDK9 change and do a patch release that reverts the relevant changes. I have created a branch containing commits that need to be reverted and that seems to work: https://github.com/bazelbuild/bazel/pull/5786

Can you take care of the patch release please?

**Comment by c-parsons** [comment]
Lets move further discussion to #5792, where I've summarized current status for patch release.
