### ISSUE TITLE
Android testing for Bazel CI is broken at HEAD

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#5064]
Error message:

```
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/8a0cb00c5e6c620196130a70ca006095/external/androidsdk/BUILD.bazel:60:1: Couldn't build file external/androidsdk/poison_pill_for_emulator_images_android_21_x86/source.properties: Executing genrule @androidsdk//:emulator_images_android_21_x86 failed (Exit 1)
--
  | This rule requires that the Android SDK used by Bazel has the following system image installed: emulator_images_android_21_x86. Please install this system image through the Android SDK Manager and try again.
```

Full log:
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/205#00bea9e7-7e0a-4641-8075-2597b4920f1c

**Comment by jin** [comment]
The fix requires re-imaging the VMs, pending at https://github.com/bazelbuild/continuous-integration/pull/263

**Comment by jin** [comment]
This is now failing due to timeouts.

https://buildkite.com/bazel/android-testing/builds/12#9f4e267e-f77f-4022-a69b-1c7874c21d5d

**Comment by jin** [comment]
I can reproduce this on the testing VM: tests on API 23 are fine, but the new APIs (19, 21, 22) are all timing out.

**Comment by jin** [comment]
Tracking here: https://github.com/bazelbuild/bazel/issues/4979

This project has been removed from downstream, so it's not blocking releases.
