### ISSUE TITLE
Gerrit Bazel CI Failing at HEAD

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#5065]
Tests failing on all platforms for bazel at HEAD:

Was passing at commit 75b75c8, failing at commit df1f0fc
javatests/com/google/gerrit/elasticsearch:elasticsearch_changes_test 

Failure log: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/205#23280501-04e3-482d-ae31-a11d46057a7b

I've tried reproducing the failures myself, but, with the errors I'm seeing, there must be something wrong with my environment :(
This is my test output:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
E.E..E...
Time: 498.881
There were 3 failures:
1) byName(com.google.gerrit.elasticsearch.ElasticQueryProjectsTest)
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
```
....

**Comment by philwo** [comment]
This was fixed by the Gerrit team:

Bug: https://bugs.chromium.org/p/gerrit/issues/detail?id=8816
Fix: https://gerrit-review.googlesource.com/c/gerrit/+/173530
