### ISSUE TITLE
Bazel CI (Remote execution) failing at HEAD

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#5066]
Was passing at commit 75b75c8, failing at commit df1f0fc

Failure log:

https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/205#21de7331-9f61-4490-8ac5-9071e7775a1b

**Comment by meteorcloudy** [comment]
@buchgr Can you take a look?

**Comment by buchgr** [comment]
It also fails with the 0.12.0 release. The offending commit is https://github.com/bazelbuild/bazel/commit/9566f677a1093e3a3c0ddaed3f9ab34dd98e5e26. We might need to do a patch release. Assigning @ulfjack for a bug fix.

**Comment by buchgr** [comment]
```exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
INFO[action_env_test 2018-04-19 10:03:01 (+0000)] bazel binary is at /b/s/w/ir/run/bazel-out/k8-fastbuild/bin/src/test/shell/integration/action_env_test.runfiles/io_bazel/src/test/shell/bin
INFO[action_env_test 2018-04-19 10:03:01 (+0000)] setting up client in /b/s/w/ir/run/_tmp/8a97789b0e2f63da550ab7ffca13aebe/workspace
ERROR[action_env_test 2018-04-19 10:03:06 (+0000)] 'bazel info bazel-genfiles' failed, stderr: $TEST_TMPDIR defined: output root default is '/b/s/w/ir/run/_tmp/8a97789b0e2f63da550ab7ffca13aebe' and max_idle_secs default is '15'.
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
	File "/b/s/w/ir/run/_tmp/8a97789b0e2f63da550ab7ffca13aebe/root/37b3b39be5c6a3ef7ec3fe336d93b330/external/bazel_tools/tools/cpp/cc_configure.bzl", line 41
		configure_unix_toolchain(repository_ctx, cpu_value, overriden...)
	File "/b/s/w/ir/run/_tmp/8a97789b0e2f63da550ab7ffca13aebe/root/37b3b39be5c6a3ef7ec3fe336d93b330/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 419, in configure_unix_toolchain
		_find_generic(repository_ctx, "gcov", "GCOV", overri...)
	File "/b/s/w/ir/run/_tmp/8a97789b0e2f63da550ab7ffca13aebe/root/37b3b39be5c6a3ef7ec3fe336d93b330/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 403, in _find_generic
		fail(("Cannot find %s or %s%s, either...)))
Cannot find gcov or GCOV, either correct your path or set the GCOV environment variable
```

**Comment by meteorcloudy** [comment]
There is still a chance to cherry-pick the fix into 0.13.0

**Comment by buchgr** [comment]
Yes, I think in that case this should be a release blocker for 0.13.0. According to @ulfjack the issue is not specific to remote execution, but after his patch Bazel simply requires gcov to be installed on the system. Remote Execution just happens to trigger this bug.

**Comment by meteorcloudy** [comment]
@ulfjack Please ping me after fixing

**Comment by ulfjack** [comment]
Ping @meteorcloudy.

**Comment by meteorcloudy** [comment]
@ulfjack I'm getting a merge error, should I cherry-pick more commits?

**Comment by ulfjack** [comment]
We don't actually need to cherry-pick into 0.13.0, because the breakage isn't in the baseline. We'll need to make sure that both changes make it into 0.14.0 though.

**Comment by philwo** [comment]
This is happening again: https://storage.googleapis.com/bazel-buildkite-artifacts/7f1c80b5-13d0-43a6-8dae-d1a7f38eb169/src/test/shell/bazel/bazel_bootstrap_distfile_test/attempt_1.log
