### ISSUE TITLE
bazel 0.12.0 running has the  appcrash

### ISSUE THREAD

**Issue by jokeralex0** [bazelbuild/bazel#5067]
i'm the fresh about the bazel.i want a tutorial about how to use the bazel in windows .it can't work.and i don't knonw why?and the address https://docs.bazel.build/versions/master/install-windows.html#download-the-binary-recommended    isn't the right way in using bazel.

**Comment by c-parsons** [comment]
The link you have provided is for how to install bazel for windows.

There are tutorials available if you would like some guidance on how to use bazel after it is installed.
Here is an example on how to build a Java project:
https://docs.bazel.build/versions/master/tutorial/java.html

Are you seeing an error?

**Comment by iirina** [comment]
@jokeralex0 please reopen this if we can help you further.
