### ISSUE TITLE
Bazel 0.12.0 doesn't filter out -pie linker_flag when making shared objects

### ISSUE THREAD

**Issue by driveraid** [bazelbuild/bazel#5069]
Hi Bazel folks, I tried to upgrade to Bazel 0.12.0 today but my build now fails due to seemingly new behavior around the issuing of -pie in a CROSSTOOL linker_flag. 

### Description of the problem / feature request:

Our CROSSTOOL has `linker_flag: "-pie"` to improve security. It looks like prior versions of Bazel filtered out this flag when linking shared objects, but doesn't anymore.
If `-shared` is present before `-pie` in the linking operation compiler line, gcc starts looking for a `main` definition.

I'm unsure how to workaround as I don't know how to influence where on the command line -shared appears.

I tried adding `linker_flag: "-shared"` and it results in `-shared` after `-pie`, but unfortunately this seems to produce not working applications (they crash).

I also tried adding `dynamic_library_linker_flag: "-shared"` (https://github.com/bazelbuild/bazel/blob/5bfe343ffba0e36df2cea9ee7678d4662d7d102b/src/main/protobuf/crosstool_config.proto#L385) but it didn't result in any observable effect on the command line.

I'll have to temporarily disable the flag in our build.. :(

### Feature requests: what underlying problem are you trying to solve with this feature?

Improving software security by using the `-pie` linking flag.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Add `linker_flag: "-pie"` to your crosstool
2. Build a package containing a library

The shared object linking operation fails with missing definition to main.

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

release 0.12.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

Unfortunately not. :(

**Comment by meteorcloudy** [comment]
@mhlopko , can you take a look?

**Comment by mhlopko** [comment]
This is surprising, I don't remember any changes to this. I will investigate.

**Comment by mhlopko** [comment]
Is it an option to share the command lines generated by bazel 0.11.1 and 0.12? I have a suspect. You can get to them by running build with `--subcommands`.

Also if you'll add this (and remove linker_flag: pie, keep the compiler_flag for now) to your crosstool I assume things will just work:

```
feature {
    name: "pie_for_linking"
    enabled: true    
    flag_set {
      action: "c++-link-executable"
      flag_group {
        flag: "-pie"
      }
    }
  }
```

Here we use the "new", not so documented mechanism in the crosstool where you can limit the flags for particular actions. Here we add -pie to c++-link-executable, but not to e.g. c++-link-dynamic-library.

**Comment by AustinSchuh** [comment]
@mhlopko , I'm seeing this too.  I converted the -pie linker flag to using the feature per your suggestion and everything started working again.  I'm going to kick off a much more extensive build shortly which tests more platforms.

**Comment by mhlopko** [comment]
Was it just plain linker_flag: "-pie" that changed behavior? I still don't understand what changed between 0.11 and 0.12.

**Comment by AustinSchuh** [comment]
Yes.  But, I think it's between 0.12 and 0.13

**Comment by mhlopko** [comment]
Oh yeah, of by one typing error :)

**Comment by hlopko** [comment]
So, at this point, I think we can just as well close this issue, the new behavior is so old now that it's the new "right behavior" :) Thanks for reporting and investigating Austin!
