### ISSUE TITLE
Docs: footnote about using "without-jdk" installer is badly formatted

### ISSUE THREAD

**Issue by davidstanke** [bazelbuild/bazel#5074]
See: 
https://docs.bazel.build/versions/master/install-ubuntu.html
https://docs.bazel.build/versions/master/install-os-x.html
https://docs.bazel.build/versions/master/install-windows.html

...each has a footnote explaining that users who already have a JDK 8 can install a version of Bazel that doesn't bundle the JDK. The formatting seems to have gone wonky between source and publishing. Can we fix? Feel free to change how it looks. (e.g. change the superscript to [1], or remove the italics, etc.)

**Comment by cushon** [comment]
@philwo we should revisit this in light of the plan to make the bundled JDK the default/not JDK 8 in 0.14.

**Comment by meteorcloudy** [comment]
@spomorski Can you help fix the footnote?

**Comment by spomorski** [comment]
Fixed.
