### ISSUE TITLE
Propagate top-level cc_library / cc_binary "defines" down to dependencies.

### ISSUE THREAD

**Issue by maccarro** [bazelbuild/bazel#5076]
### Description of the problem / feature request:

Propagate top-level cc_library / cc_binary "defines" down to dependencies.

### Feature requests: what underlying problem are you trying to solve with this feature?

We are building a kernel that uses a limited std-c library that we build and maintain.  However, we also use gTest with the full system c/c++ libraries to test the code.  We want to be able to use a `-D_KERNEL` define to switch on or off overriding of standard function definitions within the code -- use `_KERNEL` for building the kernel, and leave it undefined for testing.

We find that the `cc_library` / `cc_binary` `defines` argument will propagate defines **upward** through anything that depends on those targets, but will not rebuild dependencies with the defines, which gives us problems when we try to build in these different configurations.

Our workaround for now has been to create our own `cc_library`, `cc_binary`, and `cc_test` macros that emit two different targets -- one with the original name and the `-D_KERNEL` define, and one with "_for_test" appended and without the define.  We munch the dependencies of "_for_test" and `cc_test` targets to also depend on "_for_test" variants.  This works, but is a rather ugly hack.

We'd prefer if Bazel had first-level support for this.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`foo.h`
```
#ifdef _KERNEL
#include "kernel/lib/serial.h"  // Defines serial
#else
#include <cstdio>  // Defines vprintf()
#endif  // _KERNEL

// If kernel mode, output to serial.  Otherwise use printf to write to stdout.
void kvprintf(char* fmt, va_list args) {
#ifdef _KERNEL
  serial->Outvf(fmt, args);
#else
  vprintf(fmt, args);
#endif  // _KERNEL
}
```

`foo_test.cc`
```
#include <cstdio>
#include "foo.h"

TEST(FooTest, PrintfWorks) {
  ...
  kvprintf("Hello World\n", args);
}
```

`BUILD`
```
cc_library(
  name = "foo_lib",
  hdrs = ["foo.h"],
  deps = ["//kernel/lib:serial"],
)

cc_binary(
  name = "foo",
  srcs = ["main.cc"],
  deps = [":foo_lib"],
  defines = ["_KERNEL"],
)

cc_test(
  name = "foo_test",
  deps = [
    ":foo",
    "//gtest:gtest_main"
  ],
)
```

Expectation is that `foo` is built using `-D_KERNEL` all the way down, and will output content to serial, while `foo_test` is built without the define and will use `vprintf()`.  What actually happens is `foo_lib` is compiled without the `-D_KERNEL` define, and binary `foo` which should output to serial instead tries to link to a non-existent `vprintf` because our kernel doesn't have it.

### What operating system are you running Bazel on?

Debian Linux rodete

### What's the output of `bazel info release`?

release 0.12.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Unreleased code, not ready to provide that info.

###  Have you found anything relevant by searching the web?

No other requests for this functionality, and Bazel documentation indicates that `depends` propagates up, but not down.

### Any other information, logs, or outputs that you want to share?

N/A

**Comment by meteorcloudy** [comment]
I don't think this is actually a good idea, because it will cause one target producing multiple outputs due to different command line options (containing / not containing `_KERNEL`). @mhlopko can confirm that, and maybe provide a better solution here?

**Comment by Monnoroch** [comment]
I don't see any problems with compiling a library multiple times if it is needed. In fact, @maccarro has to complile it multiple times anyway and Bazel currently lacks an efficient way of configuring this setup: one has to copy-paste all library targets for each set of flags.

**Comment by hlopko** [comment]
This is now doable using https://docs.bazel.build/versions/1.2.0/skylark/config.html
