### ISSUE TITLE
tools missing when compiling Bazel with Bazel

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#508]
Bazel now embeds the tools in the launcher.

This makes the following scenario break:

```
 $ ls -l ~/bin/bazel 
lrwxrwxrwx 1 hanwen eng 62 Oct  9 20:07 /usr/local/google/home/hanwen/bin/bazel -> /usr/local/google/home/hanwen/vc/use-bazel/bazel-bin/src/bazel
cd ~/vc/use-bazel 
git pull && sh compile.sh 

# now work on Bazel
cd ~/vc/bazel && rm -rf src tools && git reset --hard && git pull && bazel test src/test/shell/...
```

Since the tree now no longer contains JavaBuilder_deploy.jar, the tests under src/test/shell/ fail, since the 2nd stage bazel doesn't contain the jar.

At a minimum, the rule that constructs the launcher should abort if the jar is missing.

**Comment by damienmg** [comment]
I am unsure this is a case we should cover. I mean the bazel workspace is incomplete. There is a way to build bazel without the tools though using the bootstrap-* targets for singlejar_top and javabuilder_top but we never really supported working that way.

I think this should be closed as WAI
