### ISSUE TITLE
Building TensorFlow 1.7.0 with Bazel 0.12.0 fails on aarch64 platforms 

### ISSUE THREAD

**Issue by psyhtest** [bazelbuild/bazel#5080]
Building TensorFlow 1.7.0 from source fails on aarch64 platforms (NVIDIA TX1, Linaro HiKey960, Firefly RK3399) with a GCC error:
```
ERROR: /home/anton/.cache/bazel/_bazel_anton/19f8e08691d47ead673afa362fc193f9/external/jpeg/BUILD:269:1: C++ compilation of rule '@jpeg//:simd_armv7a' failed (Exit 1)                                                                                                   
gcc: error: unrecognized command line option '-mfloat-abi=softfp'                                                       
```

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A (a build problem)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04 (JetPack 3.1)
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.7.0
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.12.0
- **GCC/Compiler version (if compiling from source)**: 5.4.1
- **CUDA/cuDNN version**: N/A (CPU ony)
- **GPU model and memory**: N/A (CPU only)
- **Exact command to reproduce**: Install dependencies and build via [CK-TensorFlow](github.com/ctuning/ck-tensorflow):
```
$ sudo apt install liblapack-dev libatlas-dev
$ sudo pip install enum34 mock pillow wheel absl-py scipy ck
$ ck pull repo:ck-tensorflow
$ ck install ck-env:package:tool-bazel-0.12.0-linux
$ ck install package:lib-tensorflow-1.7.0-src-cpu --env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=1
```
**NB:** Restricting the number of building processes to 1 is necessary to prevent running out of memory on the NVIDIA TX1 platform (4 GB and no swap enabled) or similar.

### Describe the problem

Building TensorFlow 1.7.0 with Bazel 0.12.0 fails on aarch64 platforms (NVIDIA TX1 and Linaro HiKey960). Similar instructions for TensorFlow 1.7.0 with Bazel 0.11.1 worked well (both with and without XLA support):
```
$ ck install package:lib-tensorflow-1.7.0-src-cpu --env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=1
$ ck install package:lib-tensorflow-1.7.0-src-cpu-xla --env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=1

$ ck show env --tags=tensorflow,v1.7
Env UID:         Target OS: Bits: Name:                                       Version: Tags:

ed191cc45dda7ee4   linux-64    64 TensorFlow library (from sources, cpu, xla) 1.7      64bits,bazel,channel-stable,host-os-linux-64,lib,needs-bazel,needs-bazel-0.11.1,target-os-linux-64,tensorflow,tensorflow-cpu,v1,v1.7,v1.7.0,vcpu,vsrc,vxla
ed191cc45dda7ee3   linux-64    64 TensorFlow library (from sources, cpu)      1.7      64bits,bazel,channel-stable,host-os-linux-64,lib,needs-bazel,needs-bazel-0.11.1,target-os-linux-64,tensorflow,tensorflow-cpu,v1,v1.7,v1.7.0,vcpu,vsrc
```

### Source code / logs
```
ERROR: /home/anton/.cache/bazel/_bazel_anton/19f8e08691d47ead673afa362fc193f9/external/jpeg/BUILD:44:1: C++ compilation of rule '@jpeg//:jpeg' failed (
Exit 1)
gcc: error: unrecognized command line option '-mfloat-abi=softfp'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1106.010s, Critical Path: 72.28s
FAILED: Build did NOT complete successfully
```

**Comment by meteorcloudy** [comment]
@mhlopko Do you recongnize this option? `-mfloat-abi=softfp`

**Comment by psyhtest** [comment]
@meteorcloudy This option is used for `arm-v7` (32-bit) platforms sometimes. It shouldn't be used on `aarch64` (64-bit) platforms.

**Comment by meteorcloudy** [comment]
I see, I believe the culprit is https://github.com/tensorflow/tensorflow/commit/15bda92cdb12bceb7c96404a3abafeed1a416651.
We should fix the BUILD file of jpeg in TensorFlow

**Comment by meteorcloudy** [comment]
Or can you build with `--cpu=arm64-v8a` ?

**Comment by psyhtest** [comment]
@meteorcloudy Just to make sure we are on the same page. The problem is with building TensorFlow 1.7.0 with Bazel 0.12.0. (The link above is for a different problem with TensorFlow 1.8.0-rc0/rc1.) Did that change make it into TensorFlow 1.7.0? If so, why it didn't cause problems with Bazel 0.11.1?

**Comment by psyhtest** [comment]
No, it's not in TF 1.7.0 (`third_party/jpeg/jpeg.BUILD`):
```
config_setting(
    name = "armeabi-v7a",
    values = {"android_cpu": "armeabi-v7a"},
)

config_setting(
    name = "arm64-v8a",
    values = {"android_cpu": "arm64-v8a"},
)
```

**Comment by meteorcloudy** [comment]
@psyhtest Sorry I missed that. 
In 0.12.0, the default value of `android_cpu` was changed, which lead to this issue https://github.com/bazelbuild/bazel/issues/4652#issuecomment-367143291 
Because this is a breaking change, we need the corresponding fix from TF side. 
So you can only build TF 1.7 with Bazel 0.11.1, otherwise you have to manually fix `jpeg.BUILD`

**Comment by psyhtest** [comment]
@meteorcloudy Many thanks! I'll update the Collective Knowledge metadata for all the TensorFlow 1.7.0 package to restrict the Bazel range from 0.10.0 to 0.11.1.

**Comment by meteorcloudy** [comment]
You are welcome!

**Comment by psyhtest** [comment]
[Done](https://github.com/ctuning/ck-tensorflow/commit/56a08cc76fb583ec4a302f425e818c2386897270). Now the CK community shouldn't trip on this issue again.

Thanks again @meteorcloudy!
