### ISSUE TITLE
Support completion for fish shell

### ISSUE THREAD

**Issue by tmandry** [bazelbuild/bazel#5088]
### Description of the problem / feature request:

Bazel generates a bash completion script.

It would be nice if completions were also generated for [fish, a fairly popular shell](https://github.com/fish-shell/fish-shell).

### Feature requests: what underlying problem are you trying to solve with this feature?

Complete bazel commands and package paths in fish.

### What operating system are you running Bazel on?

Linux

###  Have you found anything relevant by searching the web?

Fish has its own completion syntax, [described in the documentation](https://fishshell.com/docs/current/index.html#completion). It has a lot of [built-in completions](https://github.com/fish-shell/fish-shell/tree/master/share/completions) that can be used as examples.

Fish also supports running a script or process to get the completions; see this [gcloud completion script for fish in python](https://gist.github.com/rjohnsondev/4069b87c9a3f7adf4379662eaba3c3d7) for an example.

Not expecting this anytime soon, but putting this on the radar with links in case anyone wants to pick it up.

**Comment by akirabaruah** [comment]
I've got basic completions working in fish. Definitely not a fish expert, so there are probably many improvements to be made to the script, but it works reasonably well so far. Hope it helps!

![Peek 2020-05-20 02-08](https://user-images.githubusercontent.com/6751517/82429304-8220e600-9a40-11ea-86f7-a33ac45957c8.gif)

**Comment by meisterT** [comment]
Thanks, that looks nice!

I'm not a fish user myself so I would appreciate if this is also looked at by one who is.

**Comment by aiuto** [comment]
That's what worries me about the PR. It adds a feature that no on on the Bazel team can maintain.
It's a pity we don't have a keyword auto-triage in github so that the mention of fish automatically assigns it to @tmandry. Something like that would reduce the cost of taking it in.

**Comment by meisterT** [comment]
aiuto@ this is one of the most upvoted issues and the code is not entangled with Bazel itself, so I am willing to merge it and give it a try.

**Comment by aiuto** [comment]
Be my guest.
My secondary concern is why are contributions not needed to build bazel or by all users in the bazel repo rather than a contrib repo. Right now, I can only get these command completion scripts with the debian distro. They should be their own package.

But... we can always fork them off another day.

**Comment by akirabaruah** [comment]
Are there already plans to create a separate contrib / completions repo? Happy to help fork out the completions if needed.

**Comment by aiuto** [comment]
There are no definite plans.  I just keep advocating for trimming the bazlebuild/bazel repo to the bare minimum size it need to be. It is much easier to have community contribution in other repos than in bazel

**Comment by meisterT** [comment]
On the other hand, splitting it up also adds more complexity since we need to figure out any compatibility issues.

**Comment by gorakhargosh** [comment]
This is the kind of stuff that makes Bazel more user friendly and lets people move to Bazel from other build systems. IMHO, stuff like this should be baked into the main repository.

**Comment by philwo** [comment]
Is this issue fixed?

**Comment by meisterT** [comment]
Yes, I consider it fixed. Any further improvement to fish deserves a new issue.
