### ISSUE TITLE
Migrate pkg_rpm to rules_pkg

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#5089]
This will prevent issues like #5049 where users have to accept changes to packaging rules when they upgrade Bazel itself.

**Comment by aiuto** [comment]
I agree with the sentiment, but rules_pkg seems to be about package *fetching* not creating, even though the name 'rules_pkg' seems to imply creating to me.

I would be happy to retask rules_pkg to create packages too, on the hunch that the same people would work on either side of the rules.  There is certainly little reason why bazel includes packaging rules in it's core.  If we need them for building our distributions, we can pull them in as a third party dep.

@lberki your name is an owner of rules_pkg. WDYT?

**Comment by aiuto** [comment]
The rules now exist in https://github.com/bazelbuild/rules_pkg.
All users should start using those rules, as we will be removing them from Bazel over the next few months.
