### ISSUE TITLE
Corrupt installation on Windows

### ISSUE THREAD

**Issue by shybovycha** [bazelbuild/bazel#5091]
### Description of the problem / feature request:

I was building my project on Windows, but after a computer went to sleep and waking it up, the Bazel installation became corrupt so that none of the commands (including `shutdown` and `clean`) worked anymore:

```
C:\Users\shybo\projects\forks\irrlicht-newton-game1>bazel clean
Error: corrupt installation: file 'C:\Users\shybo\AppData\Local\Temp/_bazel_shybo/install/9cb70f26fe3e67cb6b1d3ed5d49f4edc/_embedded_binaries/build-runfiles.exe' missing. Please remove 'C:\Users\shybo\AppData\Local\Temp/_bazel_shybo/install/9cb70f26fe3e67cb6b1d3ed5d49f4edc' and try again.

C:\Users\shybo\projects\forks\irrlicht-newton-game1>bazel shutdown
Error: corrupt installation: file 'C:\Users\shybo\AppData\Local\Temp/_bazel_shybo/install/9cb70f26fe3e67cb6b1d3ed5d49f4edc/_embedded_binaries/build-runfiles.exe' missing. Please remove 'C:\Users\shybo\AppData\Local\Temp/_bazel_shybo/install/9cb70f26fe3e67cb6b1d3ed5d49f4edc' and try again.
```

The problem was that the Bazel server was still running and kept some of the file handles inside the directory mentioned. So I was made to stop the server through Task Manager and delete the directory. Only after that bazel unpacked the installation again and started working again.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. run Bazel on Windows
2. put computer in a sleep mode
3. wake computer up
4. try running Bazel again

### What operating system are you running Bazel on?

Windows 10 x64 version 1709

### What's the output of `bazel info release`?

```
release 0.11.1
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
https://github.com/shybovycha/irrlicht-newton-game1.git
6cee533e3d1f8a3c9799a4295c098a12a9d55940
6cee533e3d1f8a3c9799a4295c098a12a9d55940
```

**Comment by meteorcloudy** [comment]
@laszlocsomor Have you seen this before?

**Comment by laszlocsomor** [comment]
Yes, but rarely and never know how to repro it. Let me git it a try!

**Comment by laszlocsomor** [comment]
I can't repro using sleep-wakeup as you described.

Was the file in question ("build-runfiles.exe") really missing, or was just Bazel reporting it was?

**Comment by laszlocsomor** [comment]
Could it have been that your AntiVirus quarantined / removed it?

**Comment by laszlocsomor** [comment]
I see. And is the "build-runfiels.exe" indeed missing? Are there any other files under "_embedded_binaries" or is the directory empty?

**Comment by laszlocsomor** [comment]
Thanks. Does this happen every time your computer wakes from sleep, or does it only happen intermittently?

**Comment by laszlocsomor** [comment]
And also, does Bazel 0.12.0 behave differently in this regard?

**Comment by laszlocsomor** [comment]
Please reopen if you see this again.
