### ISSUE TITLE
chown in fakeroot fails in Bazel sandbox

### ISSUE THREAD

**Issue by kerrick-lyft** [bazelbuild/bazel#5096]
### Description of the problem / feature request:
This command fails inside the Bazel sandbox but succeeds in a normal shell:
```
echo 'touch /tmp/foo; chown root:root /tmp/foo' | fakeroot
```

In the sandbox, it prints
```
chown: changing ownership of '/tmp/foo': Invalid argument
```
and the `chown` command returns status code 1 (however, the owner/group *is* changed, so I'm not sure why it's complaining).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Add this `genrule` to a BUILD file and run it:
```
genrule(
  name = "hello",
  outs = ["foobar"],
  cmd = "echo 'touch /tmp/foo; chown root:root /tmp/foo' | fakeroot",
)
```

### What operating system are you running Bazel on?
Ubuntu 16.04
```
Linux kerrick-dev 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### What's the output of `bazel info release`?
```
release 0.10.1
```

###  Have you found anything relevant by searching the web?
No. There is one comment from 2015 that says "fakeroot doesn't work inside Bazel's sandbox" but the author doesn't elaborate. https://groups.google.com/d/msg/bazel-discuss/YIhYlrM0EcQ/TOb16FcOAwAJ

### Any other information, logs, or outputs that you want to share?
N/A.

**Comment by meteorcloudy** [comment]
@philwo Do you have any idea on this? Thanks!

**Comment by philwo** [comment]
I would recommend to run `fakeroot` under `strace` to see which syscall fails with EINVAL.

```diff
- cmd = "echo 'touch /tmp/foo; chown root:root /tmp/foo' | fakeroot",
+ cmd = "echo 'touch /tmp/foo; chown root:root /tmp/foo' | fakeroot",

**Comment by kerrick-lyft** [comment]
Here's the output of `bazel build :hello | grep EIVNAL` after adding `strace` to the command line:
```
[pid    13] rt_sigaction(SIGSTOP, {0x402120, [], SA_RESTORER, 0x7f0802e8f4b0}, NULL, 8) = -1 EINVAL (Invalid argument)
[pid    23] fchownat(AT_FDCWD, "/tmp/foo", 0, 0, 0) = -1 EINVAL (Invalid argument)
```
PID `23` is the `chown` command:
```
[pid    23] execve("/bin/chown", ["chown", "root:root", "/tmp/foo"], [/* 12 vars */]) = 0
```
So it's the `fchownat` system call that the `chown` command performs that's failing.

### Side note:
Weirdly, outside the Bazel sandbox the `fchownat` returns `EPERM` but the `chown` command still exits with a successful status code:
```
[pid 61618] fchownat(AT_FDCWD, "/tmp/foo", 0, 0, 0) = -1 EPERM (Operation not permitted)
[pid 61618] close(1)                    = 0
[pid 61618] close(2)                    = 0
[pid 61618] exit_group(0)               = ?
[pid 61618] +++ exited with 0 +++
```

**Comment by jmmv** [comment]
To get a sense of how to prioritize this, why is this important? I mean, when do you need to use fakeroot within actions?

**Comment by kerrickstaley** [comment]
@jmmv In order to manipulate SquashFS archives containing Linux filesystems using `mksquashfs` and `unsquashfs`, you need to use `fakeroot`. SquashFS archives are often used as root filesystems for embedded Linux systems.

For example, if you want to add files to a .squashfs archive, you do these steps inside a `fakeroot`:
```
tmpdir="$$(mktemp -u)"

unsquashfs -d "$$tmpdir" "$$squashfs_path"

cp $(location my_special_file) "$$tmpdir"/path/on/Linux/filesystem

mksquashfs "$$tmpdir" "$$output_squashfs_path" -all-root > /dev/null
```

If you do not use `fakeroot`, then when you run `unsquashfs`, it will fail to create some of the device files in `/dev/` (which can only be created by root), and they will end up getting dropped from the output SquashFS file.

**Comment by meisterT** [comment]
This doesn't repro on my system anymore.

**Comment by thmiller** [comment]
I'm experiencing this problem with bazel 3.1.0, with a slightly different repro case.

If I use the original repro example inside the sandbox:

`<sandbox arguments> -- echo 'touch /tmp/foo; chown root:root /tmp/foo' | fakeroot`

I see what I assume is a successful exit code from the sandbox:

`src/main/tools/linux-sandbox.cc:206: child exited normally with exitcode 0`

But if I attempt the chown from fakeroot directly, I still get the error:

```
<sandbox arguments> -- strace -f fakeroot -- chown root:root /tmp/foo 2>&1 | grep fchown
[pid    19] fchownat(AT_FDCWD, "/tmp/foo", 0, 0, 0) = -1 EINVAL (Invalid argument)
```

I have the same use case as @kerrickstaley, where I want to run unsquashfs inside a bazel rule.

**Comment by thmiller** [comment]
For anyone stumbling upon this, adding the `--strategy=local` flag to the build will avoid the sandbox and possibly get you unstuck. Based on [this forum post](https://groups.google.com/g/bazel-discuss/c/sXuzeFYlt90/m/FqAtonU6AAAJ) plus the latest versions of the flag from [the documentation](https://docs.bazel.build/versions/master/user-manual.html#strategy-options)

**Comment by parke** [comment]
If anyone is wondering why this error is happening, I found an explanation:  
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=802612

Excerpt:  "A theory is that the linux kernel returns `EINVAL` when it encounters UIDs that don't exist in the user namespace."

So, when the UID exists, but is not allowed:
(a) `fchownat` returns `-1 EPERM`,
(b) `fakeroot` transforms `-1 EPERM` to success.

But inside the namespace:  
(a) the requested UID does not exist,  
(b) so `fchownat` returns `-1 EINVAL`,  
(c) and `fakeroot` does not transform `-1 EINVAL` to success.

**Comment by parke** [comment]
Fyi, it appears you can prevent `fakeroot` from ever calling `chown()` by setting the undocumented environment variable `FAKEROOTDONTTRYCHOWN` to any non-empty string.

For example, inside a user namespace:

    $  touch  foo
    $  fakeroot  chown  root:root  foo  &&  echo  success
    chown: changing ownership of 'foo': Invalid argument
    $  export  FAKEROOTDONTTRYCHOWN='1'
    $  fakeroot  chown  root:root  foo  &&  echo  success
    success

Depending on your requirements, this may or may not be an acceptable workaround.

Source (in fakeroot version 1.29):  
https://salsa.debian.org/clint/fakeroot/-/blob/debian/1.29-1/libfakeroot.c#L646  
https://salsa.debian.org/clint/fakeroot/-/blob/debian/1.29-1/libfakeroot.c#L865
