### ISSUE TITLE
[feature request] support unix domain sockets for the REST remote cache

### ISSUE THREAD

**Issue by gkossakowski** [bazelbuild/bazel#5098]
### Description of the problem / feature request:
Support for unix domain sockets for piping the HTTP traffic of the remote cache.

Bazel uses internally netty for http traffic and netty supports connecting over a socket: https://netty.io/4.0/api/io/netty/bootstrap/Bootstrap.html#connect-java.net.SocketAddress-

The code in bazel that invokes netty doesn't support specifying a unix socket in any way. gRPC has some support for unix sockets:

https://github.com/grpc/grpc/blob/master/doc/naming.md
https://github.com/grpc/grpc-java/blob/master/benchmarks/src/main/java/io/grpc/benchmarks/Utils.java#L79v-L112

### Feature requests: what underlying problem are you trying to solve with this feature?
In certain environments, the network connectivity is restricted to other parts of the network to happen only through a local socket. This is done for security reasons.

### What operating system are you running Bazel on?

Macos

### What's the output of `bazel info release`?
release 0.12.0

## Proposal for implementation

Could we extend bazel to understand `unix:http://myremotecache` syntax  and construct the appropriate netty api call?

**Comment by gkossakowski** [comment]
cc @andyscott

**Comment by buchgr** [comment]
Absolutely. Is the `unix:http` scheme commonly used, standardized somewhere? Do you need it on Linux and/or macOS? I have generally been thinking about introducing a single `--cache` flag that supports multiple protocols.

**Comment by andyscott** [comment]
The `unix:` scheme isn't standardized anywhere (I did some searching). However, a few libraries/tools have discussions for `http+unix://` as the scheme.

**Comment by jmillikin-stripe** [comment]
I think this might belong in the proxy layer. The local socket Grzegorz is talking about uses the `Host` header (or `authority` for gRPC) to proxy connections to the correct backend. It's not clear how to calculate this header from a UNIX domain socket path.

Bazel supports HTTP proxies via the `HTTP_PROXY` and `HTTPS_PROXY` environment variables. Something like `HTTP_PROXY=http://localhost:123 bazel build --remote_http_cache=http://bazel-remote-cache.example` works as expected. I think our use case could be satisfied by expanding the proxy handling to support proxying over UNIX domain sockets, and (for remote execution) supporting a `GRPC_PROXY` variable.

One other note: we'd want to configure Bazel to use these by default, with something like `/etc/bazel.bazelrc`. Currently there's no way (that I know of) to set proxies from a Bazel flag, and no way to set environment variables in bazelrc. Could we get flags to set the proxy URLs?

Examples:
```
$ cat /etc/bazel.bazelrc
startup --http_proxy=unix:/path/to/proxy/http.sock --grpc_proxy=unix:/path/to/proxy/grpc.sock
$ bazel build --remote_http_cache=http://bazel-remote-cache.example //...
$ bazel test --remote_executor=bazel-executor.example  //...
```

**Comment by buchgr** [comment]
Good point @jmillikin-stripe. I am unsure about the `GRPC_PROXY`, as gRPC also uses the HTTP_PROXY variable: https://github.com/grpc/grpc/blob/master/doc/environment_variables.md

I also would prefer one way to specify a proxy and thus the environment variables seem to be the better choice.

**Comment by buchgr** [comment]
This has been fixed! Yay!
