### ISSUE TITLE
py_runtime does not work with --build_python_zip

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/bazel#5104]
### Description of the problem:

The interpreter binary is copied over to the runfiles without executable permissions, only when `--build_python_zip` is true. In other cases, it works as expected. The checked-in source file does have executable permissions.

```
$ git clone https://github.com/erain/bazel-python-example
$ cd bazel-python-example
$ bazel run --python_top=//:python-3 :bin  # Works
...
$ bazel run --build_python_zip --python_top=//:python-3 :bin  # Does not work
...
OSError: [Errno 13] Permission denied: '/tmp/Bazel.runfiles_vdNLqf/runfiles/__main__/python-3/bin/python3'
```
### What operating system are you running Bazel on?

macOS and Ubuntu

### What's the output of `bazel info release`?

release 0.12.0-homebrew
release 0.12.0

###  Have you found anything relevant by searching the web?

No; just [this discussion](https://github.com/google/subpar/issues/44) over using `--build_python_zip` vs using google/subpar.

**Comment by brandjon** [comment]
This is problematic because it means that enabling `--incompatible_use_python_toolchains` will break anyone using `--build_python_zip`.

But from what I can tell, the zip file actually does have the execute bit copied over, so something else is causing the failure.

**Comment by brandjon** [comment]
Possibly related to #7947.

**Comment by brandjon** [comment]
This is due to a [bug in Python's `zipfile` library](https://bugs.python.org/issue15795), which is used to extract the zip file. The actual zip file has the correct permissions.
