### ISSUE TITLE
Using Python doctests with Bazel py_test

### ISSUE THREAD

**Issue by fferroni** [bazelbuild/bazel#5106]
### Description of the problem / feature request:

I am porting a Python library with test coverage implemented as "doctests" into a Bazel build environment. I have had success at implementing some Python tests using "unittest", because these are standalone python files. However, I am confused how to use doctests since the tests are embedded in functions scattered across the library. Would I need to make a genrule that runs doctest binary? Is this available?

**Comment by keith** [comment]
Was there a resolution to this?

**Comment by depthwise** [comment]
Here's _a_ resolution to this:
```python3
#!/usr/bin/env python3

import doctest
import unittest

def load_tests(loader, tests, ignore):
    tests.addTests(doctest.DocTestSuite("your.module.name"))
    return tests

if __name__ == "__main__":
    unittest.main()
```
You have these instead of your regular Python unittests, and register them as Python test targets in Bazel.
