### ISSUE TITLE
ImportError for py_test depending on library, with identical setup

### ISSUE THREAD

**Issue by fferroni** [bazelbuild/bazel#5115]
### Description of the problem / feature request:

I have a Bazel BUILD file, which contains two trivial Python py_tests, one importing tensorflow and the other importing numpy. Both build successfully but the Tensorflow one fails with a Tensorflow ImportError

```
load("@imports//:requirements.bzl", "requirement")

py_test(
    name = "test_numpy",
    srcs = ["test_numpy.py"],
    deps = [
        requirement("numpy"),
    ],
)

py_test(
    name = "test_tensorflow",
    srcs = ["test_tensorflow.py"],
    deps = [
        requirement("tensorflow"),
    ],
)
```

The `test_numpy` test is simply:
```
import numpy as np


def test_numpy():
    """
    >>> test_numpy()
    array([1, 2, 3])
    """
    return np.array([1, 2, 3])


if __name__ == "__main__":
    import doctest
    doctest.testmod()
```

while the `test_tensorflow` is almost identical in the pattern

```
import tensorflow as tf


def test_tensorflow():
    """
    >>> test_tensorflow()
    0
    """
    return tf.constant(0)


if __name__ == "__main__":
    import doctest
    doctest.testmod()
```

The requirements are being fetched from a `requirements.txt`, which has the following lines:
```
numpy==1.14.2
tensorflow==1.8.0
```

However, the numpy one passes just fine, whereas the tensorflow one does not. Both build successfully. I get the following error:
```
...
test_tensorflow.py", line 1, in <module>
    import tensorflow as tf
ImportError: No module named 'tensorflow'
ERROR: Non-zero return code '1' from command: Process exited with status 1
```

### Feature requests: what underlying problem are you trying to solve with this feature?

Trying to test functions which depend on Tensorflow and Numpy within a Bazel project. The numpy imports work, but the Tensorflow ones do not.

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

release 0.12.0

### Any other information, logs, or outputs that you want to share?

As I said, they both build fine.
If I cd into the test_tensorflow.runfiles/ I get the following pypi folders:
```
pypi__gast_0_2_0
pypi__setuptools_39_1_0 
pypi__termcolor_1_1_0
pypi__grpcio_1_11_0
pypi__six_1_11_0
pypi__wheel_0_31_0
pypi__absl_py_0_2_0
pypi__numpy_1_14_2
pypi__tensorboard_1_8_0
pypi__astor_0_6_2
pypi__protobuf_3_5_2_post1
pypi__tensorflow_1_8_0
```
If I cd into the test_numpy.runfiles/ I get the following pypi folders:
```
pypi__numpy_1_14_2 
```
I tried different versions of tensorflow as well, but the problem is the same.

**Comment by iirina** [comment]
I'm not sure this is a Bazel bug. Have you checked out this [Stackoverflow question](https://stackoverflow.com/questions/42244198/importerror-no-module-named-tensorflow)? Seems similar to yours.

**Comment by brandjon** [comment]
Closing as dup of those rules_python issues.
