### ISSUE TITLE
./scripts/setup-eclipse.sh logs Errors on Mac

### ISSUE THREAD

**Issue by dmaclach** [bazelbuild/bazel#512]
Once you fix up net-tools, and a small BUILD file problem (fixes for those are enroute) I still ended up with this:

ERROR: /Users/dmaclach/src/bazel/tools/build_rules/appengine/BUILD:2:1: no such package '@javax-servlet-api//jar': error loading package 'external': The repository named '@javax-servlet-api' could not be resolved and referenced by '//tools/build_rules/appengine:javax.servlet.api'.
____Loading package: @dmd-linux-x86_64//
____Loading package: @dmd-darwin-x86_64//
____Loading package: @jsonnet//
____Loading package: @sassc//
____Loading package: @libsass//
____Loading package: examples/sass/shared
ERROR: /Users/dmaclach/src/bazel/tools/build_rules/appengine/BUILD:2:1: no such package '@javax-servlet-api//jar': error loading package 'external': The repository named '@javax-servlet-api' could not be resolved and referenced by '//tools/build_rules/appengine:javax.servlet.api'.
ERROR: Evaluation of subquery "deps(//tools/...)" failed (did you want to use --keep_going?): errors were encountered while computing transitive closure.
ERROR: /Users/dmaclach/src/bazel/tools/build_rules/appengine/BUILD:2:1: no such package '@javax-servlet-api//jar': error loading package 'external': The repository named '@javax-servlet-api' could not be resolved and referenced by '//tools/build_rules/appengine:javax.servlet.api'.
ERROR: /Users/dmaclach/src/bazel/tools/build_rules/appengine/BUILD:2:1: no such package '@javax-servlet-api//jar': error loading package 'external': The repository named '@javax-servlet-api' could not be resolved and referenced by '//tools/build_rules/appengine:javax.servlet.api'.
ERROR: Evaluation of subquery "deps(//tools/...)" failed (did you want to use --keep_going?): errors were encountered while computing transitive closure.
ERROR: /Users/dmaclach/src/bazel/tools/build_rules/appengine/BUILD:2:1: no such package '@javax-servlet-api//jar': error loading package 'external': The repository named '@javax-servlet-api' could not be resolved and referenced by '//tools/build_rules/appengine:javax.servlet.api'.
ERROR: /Users/dmaclach/src/bazel/tools/build_rules/appengine/BUILD:2:1: no such package '@javax-servlet-api//jar': error loading package 'external': The repository named '@javax-servlet-api' could not be resolved and referenced by '//tools/build_rules/appengine:javax.servlet.api'.
ERROR: Evaluation of subquery "deps(//tools/...)" failed (did you want to use --keep_going?): errors were encountered while computing transitive closure.
ERROR: /Users/dmaclach/src/bazel/tools/build_rules/appengine/BUILD:2:1: no such package '@javax-servlet-api//jar': error loading package 'external': The repository named '@javax-servlet-api' could not be resolved and referenced by '//tools/build_rules/appengine:javax.servlet.api'.
ERROR: /Users/dmaclach/src/bazel/tools/build_rules/appengine/BUILD:2:1: no such package '@javax-servlet-api//jar': error loading package 'external': The repository named '@javax-servlet-api' could not be resolved and referenced by '//tools/build_rules/appengine:javax.servlet.api'.
ERROR: Evaluation of subquery "deps(//tools/...)" failed (did you want to use --keep_going?): errors were encountered while computing transitive closure.
____Empty results

The script claims that Eclipse project generated, but we should fix these?

**Comment by cgrushko** [comment]
Possibly related: the script, on a new repo clone, errors:

```
ERROR: DEFAULT.WORKSPACE:75:1: in bind rule //external:android/sdk: The external label '//external:android/sdk' is not bound to anything.
ERROR: Analysis of target '//src/tools/android/java/com/google/devtools/build/android/incrementaldeployment:incremental_split_stub_application' failed; build aborted.
INFO: Elapsed time: 2.207s
```

**Comment by kchodorow** [comment]
That's a separate issue (the setup-intellij script is trying to load android support, which it shouldn't be doing) but we can track them both in this bug.

**Comment by damienmg** [comment]
This script is not maintained and going to be deleted. Closing for now.
