### ISSUE TITLE
Build cache not invalidated when passing different zip files to the --fdo_optimize flag

### ISSUE THREAD

**Issue by guoshimin** [bazelbuild/bazel#5124]
### Description of the problem / feature request:

Build cache not invalidated when passing different zip files to the --fdo_optimize flag.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
// fdo.cc
#include <iostream>
#include <string.h>

void foo() {
  std:: cout << "hello" << std:: endl;
}

void bar() {
  std :: cout << "world" << std:: endl;
}

int main(int argc, char *argv[]) {
  if (strncmp("foo", argv[1], 3) == 0) {
    foo();
  } else {
    bar();
  }
  return 0;
}
```

```
# BUILD.bazel
cc_binary(
    name = "fdo",
    srcs = ["fdo.cc"],
)
```

```
bazel build --fdo_instrument=/tmp/foo :fdo
bazel-bin/fdo foo
bazel build --fdo_instrument=/tmp/bar :fdo
bazel-bin/fdo bar
diff -r /tmp/foo /tmp/bar
cd /tmp/foo; zip -r /tmp/foo.zip .
cd /tmp/bar; zip -r /tmp/bar.zip .
bazel build -s --fdo_optimize=/tmp/foo.zip :fdo
bazel build -s --fdo_optimize=/tmp/bar.zip :fdo  # no rebuild
```
### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 0.11.1

###  Have you found anything relevant by searching the web?

No

**Comment by scentini** [comment]
The --fdo_optimize option is silently ignored when -c opt is not used.

bazel build --fdo_optimize=/tmp/foo.zip :fdo -c opt
bazel build --fdo_optimize=/tmp/bar.zip :fdo -c opt
should trigger a rebuild.

**Comment by guoshimin** [comment]
Tried `-c opt`, got the same result. No rebuild.

**Comment by scentini** [comment]
Apologies for the delayed response.
Seems like you also need to add -c opt to the commands that have --fdo_instrument, I'll investigate why that is the case.
