### ISSUE TITLE
[FR] Allow un-setting of `--compiler` and `--glibc`

### ISSUE THREAD

**Issue by RNabel** [bazelbuild/bazel#5126]
### Description of the problem / feature request:

Once specified, the CLI flags `--compiler` and `--glibc` cannot be unset (i.e. using `--nocompiler` or similar is not possible).

This is directly related to the bug tracked here: https://github.com/bazelbuild/bazel/issues/4995

This is desirable for 2 reasons:
1. When using configs. In most cases, a "default" config is included which defines a compiler etc. to be used when building native code. Currently, it is not possible to run the below instructions because the `--compiler` and `--glibc` flags have to be overridden by all following configs. 
```
$ cat tools/bazel.rc
build --config=default

build:default --cpu=k8
build:default --compiler=compiler
build:default --glibc=libstdcpp # Multiple toolchains available so need to specify glibc.

build:funky_arch --cpu=x86_123 # Only one valid toolchain with this CPU.

$ bazel build //some/native:target
...
$ bazel build --config=funky_arch //some/native:target
ERROR: No toolchain found for --cpu='x86_123' --compiler='compiler' --glibc='libstdcpp'
```

2. A [bug](https://github.com/bazelbuild/bazel/issues/4995) within bazel results in failures on some platforms iff a) a custom CROSSTOOL is used, and b) all 3 flags (`cpu`, `compiler`, `glibc`) are set, but _not_ when only `--cpu` is set.

### Feature requests: what underlying problem are you trying to solve with this feature?

The ability to unset `--compiler` and `--glibc`. 
From an outside perspective, the options seem to be `--nocompiler` or `--compiler=None/null/""/<some magic string>`. The `nocompiler` option would keep with the existing flags, but saying "no" compiler and bazel then using a compiler is not exactly intuitive.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

On macos, with xcode installed, building any repo.
```
$ cat tools/bazel.rc
build --config=default

build:default --cpu='darwin_x86_64' --compiler='compiler' --glibc='macosx'
build:tvos --cpu='tvos_x86_64'

$ bazel build //some/target --config=tvos
ERROR: No toolchain found for --cpu='tvos_x86_64' --compiler='compiler' --glibc='macosx'. Valid toolchains are: [
  --cpu='darwin_x86_64' --compiler='compiler' --glibc='macosx',
  --cpu='ios_x86_64' --compiler='compiler' --glibc='ios',
  --cpu='watchos_i386' --compiler='compiler' --glibc='watchos',
  --cpu='tvos_x86_64' --compiler='compiler' --glibc='tvos',
  --cpu='ios_i386' --compiler='compiler' --glibc='ios',
  --cpu='ios_armv7' --compiler='compiler' --glibc='ios',
  --cpu='watchos_armv7k' --compiler='compiler' --glibc='watchos',
  --cpu='tvos_arm64' --compiler='compiler' --glibc='tvos',
  --cpu='ios_arm64' --compiler='compiler' --glibc='ios',
  --cpu='armeabi-v7a' --compiler='compiler' --glibc='armeabi-v7a',
]
```
### What operating system are you running Bazel on?

MacOs/Windows/Linux

### What's the output of `bazel info release`?

`bazel 0.13.0`

###  Have you found anything relevant by searching the web?

Using invocation policy: https://stackoverflow.com/questions/48652798/how-do-i-unset-flags-set-in-bazelrc

### Any other information, logs, or outputs that you want to share?

This feature would not be needed if the issue tracked in #4995 were resolved. The combination of sticky flags and this bug means that we have to do some really hacky flag setting and filtering in the `tools/bazel` script.

**Comment by RNabel** [comment]
Regarding `2.` above. We found a workaround: if a custom `CROSSTOOL` exists, you can define glibc and compiler in the default toolchain, so they don't need to be defined on the command line.

**Comment by mhlopko** [comment]
Thank you for a precise feature request!

I just commented on #4995. Since @katre is completely changing the way we select C++ toolchain, and with the new mechanism this FR is not applicable, and since we'll try to resolve #4995, would you mind if I closed this right away?

**Comment by RNabel** [comment]
Sounds good, thanks for the update!
