### ISSUE TITLE
bazel takes all available memory...and then some

### ISSUE THREAD

**Issue by skearnes** [bazelbuild/bazel#513]
Hi, I cloned this repo today (15 Oct 2015) and ran ./compile.sh under OpenJDK 8 (1.8.0_45-internal) and the script runs fine. However, when I cd to the output and run ./bazel, the program uses all of the available memory and runs into the swap. That's over 24G, so something is terribly wrong. Any ideas?

I'm running Ubuntu 15.04.

**Comment by ahumesky** [comment]
Hi skearnes, thanks for the report, we're aware of the problem and investigating.

**Comment by ahumesky** [comment]
Closing this for https://github.com/bazelbuild/bazel/issues/514
