### ISSUE TITLE
Windows,java_binary launcher: support jar files on multiple drives

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#5135]
### Feature requests: what underlying problem are you trying to solve with this feature?

The java_binary launcher cannot create a classpath jar if the jar files are on different drives.

### What operating system are you running Bazel on?

Windows 10.

### What's the output of `bazel info release`?

release 0.13.0

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/5125#issuecomment-385892520

**Comment by meteorcloudy** [comment]
Looks like creating junctions for those jars is the only option?

**Comment by laszlocsomor** [comment]
That's my best idea too.

**Comment by meteorcloudy** [comment]
I'll find a time to take care of this!

**Comment by laszlocsomor** [comment]
Thank you @meteorcloudy ! You could use the junction creator in https://github.com/bazelbuild/bazel/blob/56fbc9998858bc2084a351576b20818bb9290a73/src/main/native/windows/file.h#L85

**Comment by meteorcloudy** [comment]
Thanks!

**Comment by laszlocsomor** [comment]
P1 because it blocks #5125 which is also P1.
