### ISSUE TITLE
windows: support sandboxing [blocking #5640]

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#5136]
### Description of the problem / feature request:

This is an umbrella bug for the feature request of supporting sandboxing on Windows.

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 0.13.0

###  Have you found anything relevant by searching the web?

Microsoft recently opensourced Detours, which could be useful: https://github.com/Microsoft/Detours

**Comment by j3parker** [comment]
I'm sure you're aware, but Windows has something called the Host Compute Service which is used to implement containers for things like Docker.

[This blog post](https://blogs.technet.microsoft.com/virtualization/2017/01/27/introducing-the-host-compute-service-hcs/) has the high level picture and they link to wrappers+sample code for [C#](https://github.com/Microsoft/dotnet-computevirtualization/blob/master/samples/ContainerRun/Program.cs) and [Go](https://github.com/Microsoft/hcsshim) (which looks more complete and is what Docker actually uses.)

Maybe something from there would be useful?

**Comment by laszlocsomor** [comment]
I wasn't aware, thanks for the info! Could be useful indeed. Though supporting the [Docker-based sandbox strategy](https://github.com/bazelbuild/bazel/blob/25f3217c9d528ab00a329aefbfa7e8d39f02c2d1/src/main/java/com/google/devtools/build/lib/sandbox/DockerSandboxedStrategy.java) on Windows may be more convenient than implementing native sandboxing.

**Comment by j3parker** [comment]
Cool! Makes sense.

**Comment by ilya-klyuchnikov** [comment]
FYI: https://github.com/Microsoft/BuildXL has an implementation of Windows Sandboxing

**Comment by laszlocsomor** [comment]
@ilya-klyuchnikov -- Thanks for the heads-up! Very interesting, I'll take a look and try to build it.

**Comment by jin** [comment]
@laszlocsomor could you please add a priority to this issue?

**Comment by laszlocsomor** [comment]
Setting priority to p3 -- I don't expect much focus on this before Bazel 1.0 (though this is not ruled out either).

**Comment by laszlocsomor** [comment]
@rongjiecomputer is working on this feature \o/

**Comment by konste** [comment]
I wonder if you looked at FUSE implementations for Windows, such as https://dokan-dev.github.io/ or http://www.secfs.net/winfsp/ ? As Bazel already makes use of sandboxfs for Linux and Mac it may be beneficial to utilize as similar tech as possible on Windows.

**Comment by aherrmann** [comment]
@laszlocsomor @rongjiecomputer What's the status of this? Is the current progress documented somewhere?

**Comment by laszlocsomor** [comment]
@aherrmann : @rongjiecomputer implemented experimental sandbox support as part of Google Summer of Code 2019 (GSoC).

All about the project is in a public Google doc: https://docs.google.com/document/d/1dbF5cGYJouGF5zd0GDE-rbUvkKvH36DnNdtEvE4yV6w/edit

The Bazel team does not maintain this feature. We currently have no plans to work on it either.
