### ISSUE TITLE
[bisected] bazel binary crashes when invoked

### ISSUE THREAD

**Issue by fschwan** [bazelbuild/bazel#514]
Version 0.1.0 is fine, version 0.1.1 compiles without problems. Invoking the binary afterwards leads to

```
(git)-[tags/0.1.1|bisect] % ./output/bazel build scripts:bazel-complete.bash     
[1]    14607 killed     ./output/bazel build scripts:bazel-complete.bash
./output/bazel build scripts:bazel-complete.bash  1,53s user 6,32s system 98% cpu 7,983 total
```

even ./output/bazel leads to this crash.

Bisecting points to commit 97eaf9136abad30827cf1a060cc32e786745923d
log:
```
git bisect start
# bad: [97eaf9136abad30827cf1a060cc32e786745923d] Add a //src:bazel-notools target that is the same as the Bazel binary except without the embedded tools.
git bisect bad 97eaf9136abad30827cf1a060cc32e786745923d
# good: [125b349ca5441d4cf6a55ca69fb680de1f1b60c0] Release 0.1.0 (2015-09-08)
git bisect good 125b349ca5441d4cf6a55ca69fb680de1f1b60c0
# good: [a0881e84ed6dca917b54d86e13c5db1278d12598] Reset releases
git bisect good a0881e84ed6dca917b54d86e13c5db1278d12598
# good: [df0531fad8fc0288c21f5672aa59907362ae0ff5] Allow Skylark import lookup values to be computed inline in order to avoid reifying them in the Skyframe graph.
git bisect good df0531fad8fc0288c21f5672aa59907362ae0ff5
# good: [af3485700854e84ae1445ac13ab680f6fe35ec46] Allow extractIncludes method to throw an ExecException.
git bisect good af3485700854e84ae1445ac13ab680f6fe35ec46
# good: [e8061718bb3ed36e153d23e55f3484091bad1045] Removes duplicate arm crosstool toolchain definition.
git bisect good e8061718bb3ed36e153d23e55f3484091bad1045
# good: [dce5675def134b51f533d9763a36fdd92008cad7] Test concurrent get and createIfAbsent. Also remove unnecessary locking in #testAddingInflightNodes, which also gives some concurrency coverage.
git bisect good dce5675def134b51f533d9763a36fdd92008cad7
# good: [eff2b450bd44d019d3b23495e383cfce9e473fe6] Allow other ExecutorService implementations in AbstractQueueVisitor
git bisect good eff2b450bd44d019d3b23495e383cfce9e473fe6
# good: [6afd4167fabf9fb292167f70b20b674829c0739a] Update ios-app tutorial to use ios_application for bundling instead of the deprecated bundling functionality of objc_binary.
git bisect good 6afd4167fabf9fb292167f70b20b674829c0739a
# good: [c82224f4945118392488e508f179cdf1918491bd] Remove command_helper, use resolve_command instead
git bisect good c82224f4945118392488e508f179cdf1918491bd
# good: [c7106d4f6c0f550ad401ef8d8b3df2a5ec7eeea0] Make recursive package wildcards work in remote repositories.
git bisect good c7106d4f6c0f550ad401ef8d8b3df2a5ec7eeea0
# good: [3bb1990892d1bfb5a4e793431cb4730a3c0a06e6] New feature: Bazel prints a warning for unknown --config flag values.
git bisect good 3bb1990892d1bfb5a4e793431cb4730a3c0a06e6
# first bad commit: [97eaf9136abad30827cf1a060cc32e786745923d] Add a //src:bazel-notools target that is the same as the Bazel binary except without the embedded tools.
```

System:
Archlinux
Kernel 4.1.10-2-lts
gcc-Version 5.2.0 (GCC)

**Comment by ahumesky** [comment]
Hi fschwan, thanks for the report, we're aware of the problem and investigating.

**Comment by ahumesky** [comment]
Yep, this is the culprit, we'll roll this back, thanks fschwan

**Comment by fschwan** [comment]
Branch release-0.1.2 fixes this problem.
Thanks!

**Comment by filmil** [comment]
Quick question here: will you be merging release-0.1.2 into master?  I'm still seeing problem commit 97eaf9136abad30827cf1a060cc32e786745923d as latest on master.  Is this intended, given that it's a problem?

**Comment by lberki** [comment]
This change has been rolled back in dcd9a53e2699ffa3fbcd736b4df55c347ddf05bd . I will try again in a bit more principled way soon.

**Comment by fschwan** [comment]
Are there any plans to package release 0.1.2?

**Comment by kchodorow** [comment]
release-0.1.2 should be released within a week, assuming it looks okay (so far so good).  

@filmil Basically we create a branch from master and then cherry pick any fixes we need onto it (also from master), so it doesn't make a lot of sense for us to merge it back into master. See https://github.com/bazelbuild/bazel/blob/master/scripts/release/release.sh#L281-L302 for the actual script we use to create releases.

**Comment by filmil** [comment]
I understand the release process. Thanks for explaining. It is only that I
have found that master did not have the leak fix while release did at the
time when I checked. Is this expected or did I simply see it wrong?

**Comment by kchodorow** [comment]
The release branch was cut from https://github.com/bazelbuild/bazel/commit/f7cc9cdb4b4cf0a092ea8fde17d419765e3c6f38, not head, so it doesn't contain the commit that caused the leak.

**Comment by philwo** [comment]
@filmil As we cherry pick fixes from master onto the release branch, it should never happen that a release branch has a commit that master is still missing (this is how I understand what you've seen).

If you do see it happen, please let us know! :)

**Comment by filmil** [comment]
Luckily, my git repo is still in the state after the sync so I can reflect
on its current state. Here's what I have, maybe it's interesting.


What happened was this:
- I synced with master.
- built bazel from scratch
- tried to use it at which point my machine was so badly bent that I had to
restart it. :(, but no real harm done.
- restarted, learned about the bug, checked out release-0.1.2 and compiled
with success.

IIRC, 97eaf9136abad30827cf1a060cc32e786745923d was the bug culprit.  It's
also the HEAD of my master branch at this point.  I'd have expected that I
would see commits (e.g. a rollback at least) after that one on 'master' if
I can see a fixed 'release-0.1.2' branch, given that both branches as I see
them now were this way for hours before I pulled.

I'm almost certain this is about me misunderstanding something, but here's
the excerpt in case you are interested.

f@filmar:~/local/opt/bazel$ git branch
  master
* release-0.1.2
f@filmar:~/local/opt/bazel$ git log  HEAD^..HEAD
commit 7a34790a2fdad25db8c14bff2596cb9f0bbb29a3
Author: Bazel Release System <noreply@google.com>
Date:   Thu Oct 15 19:54:46 2015 -0400

    Release 0.1.2 (2015-10-15)

    Baseline: f7cc9cd

    New features:

      - java_library now supports the proguard_specs attribute for
        passing Proguard configuration up to Android (not Java) binaries.

    Important changes:

      - remove webstatusserver (--use_webstatusserver).
      - Add support for objc textual headers, which will not be compiled
        when modules are enabled.
      - actoolzip, momczip and swiftstdlibtoolzip have all been made into
        bash scripts and have been renamed to actoolwrapper, momcwrapper
        and swiftstdlibtoolwrapper respectively. The old versions will be
        deleted in a later change.
      - [rust] Add rust_bench_test and rust_doc_test rules and improve
        usability of rust_test tule.
      - Java rules now support a resource_strip_prefix attribute that
        allows the removal of path prefixes from Java resources.
      - [docker_build] incremental loading is default now. Specify
explicitly
        //package:target.tar (with the .tar extension) to obtain the full
image.



And:
f@filmar:~/local/opt/bazel$ git checkout master

Your branch is up-to-date with 'origin/master'.
f@filmar:~/local/opt/bazel$ git log  HEAD^..HEAD
commit 97eaf9136abad30827cf1a060cc32e786745923d
Author: Lukacs Berki <lberki@google.com>
Date:   Thu Oct 15 12:06:12 2015 +0000

    Add a //src:bazel-notools target that is the same as the Bazel binary
except without the embedded tools.

    Its use requires the addition of a local_workspace(name =
"bazel_tools", path=...) to the WORKSPACE file. It is useful if you don't
care

    --
    MOS_MIGRATED_REVID=105499508

**Comment by kchodorow** [comment]
Take a look at the release branch: https://github.com/bazelbuild/bazel/commits/release-0.1.2. You can see that it is the master branch, up to October 8th, and then two commits: a cherry pick of @philwo's sandboxing fix and the release notes.  (If you look on https://github.com/bazelbuild/bazel/tree/release-0.1.2, GitHub describes the branch as 2 commits ahead, 190 commits behind master.) 

You can see that https://github.com/bazelbuild/bazel/commit/97eaf9136abad30827cf1a060cc32e786745923d (the bug culprit) was committed on October 15th, well after the release branch was cut.  Thus, the bug does not exist in the release and thus it did not have to be patched.

Does that make sense?

**Comment by filmil** [comment]
On Wed, Oct 21, 2015 at 8:34 AM Kristina <notifications@github.com> wrote:

> You can see that 97eaf91
> <https://github.com/bazelbuild/bazel/commit/97eaf9136abad30827cf1a060cc32e786745923d>
> (the bug culprit) was committed on October 15th, well after the release
> branch was cut. Thus, the bug does not exist in the release and thus it did
> not have to be patched.
>
> Does that make sense?
>
Makes sense: I was under the mistaken impression that 0.1.2 was released
specifically to fix this problem.
So, I had just very unfortunate pull timing. :)

Thanks for setting me straight,
F

>

**Comment by kchodorow** [comment]
Ah, got it.  Yeah, I had just successfully released 0.1.1 and figured I'd get a jump on 0.1.2 with a known-good commit.  I didn't even realize that head was on fire.

**Comment by fschwan** [comment]
15 days ago:
```
release-0.1.2 should be released within a week, assuming it looks okay (so far so good).
```
What about now?

**Comment by kchodorow** [comment]
Although 0.1.2 passed all of our tests 15 days ago, it had a sandboxing bug we discovered and @philwo fixed.  I cherry picked the fix and... it broke everything.  We've gradually fixed all of the issues in master, but cherry picking them all in is complex enough that I think I'm actually going to abandon 0.1.2 as it stands now and recut it from a more recent commit.  As soon as our [build](http://ci.bazel.io) is green.
