### ISSUE TITLE
Bazel 0.13 prevents building with AmericanFuzzyLop compiler wrappers.

### ISSUE THREAD

**Issue by PhilArmstrong** [bazelbuild/bazel#5142]
### Description of the problem / feature request:

Bazel 0.13 breaks building binaries with AmericanFuzzyLop.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Pick any C / C++ binary build, use a bazel build line like this:

``CC=/usr/bin/afl-gcc CXX=/usr/bin/afl-g++ bazel build //target:binary``

In 0.12, bazel would happily compile with afl-g++, or afl-clang-fast etc.

In 0.13, the compile errrors out with

``gcc: error trying to exec 'cc1': execvp: No such file or directory``
or
``clang: error: unable to execute command: Executable "clang" doesn't exist!`` (if you use afl-clang-fast)

As far as I can tell, this is because bazel is clearing the environment completely before execing the compiler binary: I guess with PATH set to nothing, the compiler is unable to find itself? Weirdly, setting CC=gcc CXX=g++ still works fine, so there is some interaction with afl itself here.

If I run the same commands that bazel runs (taken from --sandbox_debug), but set PATH to /usr/bin before running the compile step, everything works fine. Setting the PATH with --action_env doesn't solve the problem however: it helps somewhat, in that the individual compilation steps succeed, however linking the final binary still fails with the same error - it appears that --action_env settings are not being passed to the link stage for reasons that I don't understand.

I'm happy to accept that afl is doing something it shouldn't be & a pointer as to how to fix afl would be appreciated in that case, but this worked fine in bazel 0.12, and the failure appears to be completely opaque. I particularly don't understand why it works fine for the compile steps if I specify a PATH on the command line with --action_env, but still fails to link with the same error. ie

``CC=/usr/bin/afl-gcc CXX=/usr/bin/afl-g++ bazel build --action_env="PATH=/bin:/usr/bin" //target:binary``

is only a partial solution :(

### What operating system are you running Bazel on?

Fedora 27

### What's the output of `bazel info release`?

release 0.13.0- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Installed from vbatts copr fedora repo.

###  Have you found anything relevant by searching the web?

Apart from bazel bugs about inconsistent behaviour with --action_env, I haven't found anything helpful.

**Comment by PhilArmstrong** [comment]
c2c7645922269ac4adc0720f129380c101842133 looks suspicious, in particular the removal of line 470 that inserts the client environment

**Comment by PhilArmstrong** [comment]
I think we might be hitting #4008, as the files which are not compiling are the source inputs to a tools entry used in our bazel BUILD files. I thought it might be a linker argument problem as at least one of tools is a single .c file, but looking closer it appears that bazel still compiles a single .c to a .o object file even in the case of a single source before linking the binary & it is this compilation step that is failing.

**Comment by PhilArmstrong** [comment]
So this might be bazel working as designed in the first instance & we need to set PATH (and possibly one or two other environment variables) via --action_env, but if you have interstitial tools, CC/CXX are used but --action_env is not passed through so the build breaks.

**Comment by PhilArmstrong** [comment]
I guess the real solution to this is a custom CROSSTOOL setup that uses the afl- prefix compilers for building the final target binaries & sets the correct PATHs there, but uses the host compilers for compiling the interstitial tools?

Meanwhile wait for #4304 / #4008 & related bugs to be fixed?  :)

**Comment by PhilArmstrong** [comment]
NB. A short term fix for this issue is to point CC and CXX at shell script wrappers that set PATH to /bin:/usr/bin before execing afl-clang-fast (or whatever).

e.g.

```
#!/bin/sh
export PATH=/bin:/usr/bin
export AFL_HARDEN=1
exec /usr/bin/afl-clang-fast $@
```

The interstitial tools will also be built with these compiler wrappers, but in my case that wasn't a problem.

**Comment by mhlopko** [comment]
I'll add that [cc_configure.bzl](https://source.bazel.build/bazel/+/master:tools/cpp/cc_configure.bzl?q=cc_configure) [resolves path passed by CC to an absolute path](https://source.bazel.build/bazel/+/master:tools/cpp/unix_cc_configure.bzl;l=411?q=unix_cc_configure), so that's the reason it works. Btw, CXX is ignored currently.

Were you able to bisect the commit that changed the behavior?

**Comment by PhilArmstrong** [comment]
Will see if I can do so...

**Comment by PhilArmstrong** [comment]
Bisecting says change 0f5679ef95611e457a6e39313cf88feac8b2278f is to blame.

**Comment by PhilArmstrong** [comment]
Ironically, that commit appears to have done the complete opposite of what it says it does...

**Comment by mhlopko** [comment]
CC @ulfjack

**Comment by ulfjack** [comment]
I think it's the same cause as #3642. Both CppCompileAction and CppLinkAction are not working correctly. :-/ Sorry about that.
