### ISSUE TITLE
java_import_external has no //jar:file equivalent

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/bazel#5143]
Sometimes it's necessary to have to the full class jar.

maven_jar (and I think http_jar) had the `//jar:file` target. Currently, java_import_external does not have this target or an equivalent.

**Comment by ittaiz** [comment]
Paul,
Do you need this because of ijar? Since that’s why we created
scala_import_external

**Comment by pauldraper** [comment]
@ittaiz yeah, I am aware of that.

The jar is a Java jar, and I do want to use ijar most of the time, except for one place.

Workarounds

(1) Use scala_import_external, and never use ijar.
(2) Write a custom rule and pull out the full jar from JavaInfo.

These workaround are acceptable. But I'm guessing there's a reason the native rules included `//jar:file`? If it was a historical artifact that we'd prefer to have removed, that's fine too.

**Comment by ittaiz** [comment]
The reason (as I remember it) was to allow scala to use maven_jar and
bypass ijar.
Btw,
We plan on having scala_import support ijar (not sure if opt-in or opt-out
yet).
If you could have scala_import_external targets which use ijar and others
which don’t would that solve the problem?

**Comment by pauldraper** [comment]
For my purposes, I figured out, I really just wanted `transitive_runtime_deps`.

Maybe there's a reason the jar itself (without deps) is needed, but I don't have one, so I'm closing.
