### ISSUE TITLE
BuildEventStream File references should include hashes for validation

### ISSUE THREAD

**Issue by EricBurnett** [bazelbuild/bazel#5145]
### Description of the problem / feature request:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto#L381 includes a URI for a file, but no way to validate the contents. Optionally including an explicit hash would allow BES consumers to validate that the files they've downloaded are bitwise correct.

Relatedly, an optional size field should probably be included at the same time as a convenience (though for correctness purposes the hash should suffice).

Note: a hash and/or size may be embedded in the URI in practice, but the API doesn't cover that and so consumers shouldn't rely on it.

### Feature requests: what underlying problem are you trying to solve with this feature?

Allow BES consumers who download referenced files to validate they've gotten the correct bytes.

### What operating system are you running Bazel on?

N/A

**Comment by ittaiz** [comment]
@helenalt @dslomov ping

**Comment by lfpino** [comment]
Hi Eric and others, sorry for the delay to respond. Can you please update the reference to the code? Which field, is it File?

Also, can you please elaborate on how critical this is? Namely, how often do users encounter this problem? Is there a workaround?

Thanks!

**Comment by buchgr** [comment]
@lfpino That sounds reasonable to me. Now that we have local file uploading implemented it's also a straightforward thing to do.

@Yannic as of recently we do have local file uploading, meaning that the BES code is able to trigger an upload of a local file referenced by some event to the remote cache. The BES event will then refer to this file by some URL pointing to the cache. It's implemented for the gRPC cache but not yet for the HTTP cache. It's simple to add though if you are interested in working on that let me know!

**Comment by Yannic** [comment]
@buchgr That's great to hear. I'm definitely interested in seeing this happen for the HTTP cache as well. I'll be busy for the next month or so, if no one else wants to pick this up until then, we can talk about some details.
