### ISSUE TITLE
Cannot use on windows 10

### ISSUE THREAD

**Issue by SevastyanDark** [bazelbuild/bazel#5148]
### Description of the problem / feature request:

Can't use bazel on windows

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Bazel fail on windows(most likely internal bazel bug)

### What operating system are you running Bazel on?

Windows 10 x64 (VS 2017)

### What's the output of `bazel info release`?

`release 0.13.0`

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

I used choco to install

###  Have you found anything relevant by searching the web?

Found, but nothing helped

### Any other information, logs, or outputs that you want to share?

```
C:\Users\dark\Desktop\cpp-tutorial\stage1>bazel info release
release 0.13.0

C:\Users\dark\Desktop\cpp-tutorial\stage1>bazel clean
INFO: Starting clean.

C:\Users\dark\Desktop\cpp-tutorial\stage1>bazel build //main:hello-world
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/users/dark/_bazel_dark/x7ca2npm/external/bazel_tools/tools/cpp/cc_configure.bzl", line 36
                configure_windows_toolchain(repository_ctx)
        File "C:/users/dark/_bazel_dark/x7ca2npm/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 304, in configure_windows_toolchain
                _find_missing_vc_tools(repository_ctx, vc_path)
        File "C:/users/dark/_bazel_dark/x7ca2npm/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 230, in _find_missing_vc_tools
                _find_vcvarsall_bat_script(repository_ctx, vc_path)
        File "C:/users/dark/_bazel_dark/x7ca2npm/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 179, in _find_vcvarsall_bat_script
                repository_ctx.path(vcvarsall).exists
Illegal char <"> at index 60: C:/users/dark/_bazel_dark/x7ca2npm/external/local_config_cc/"C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC"/Auxiliary/Build/VCVARSALL.BAT
INFO: Elapsed time: 0,746s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded)

C:\Users\dark\Desktop\cpp-tutorial\stage1>
```

**Comment by laszlocsomor** [comment]
Looks like you set one of the environment variables with quotes, like you would in Bash.
In Windows and cmd.exe, envvars must be unquoted.

What's the output of these commands?
```
set %BAZEL_SH%
set %BAZEL_VC%
set %BAZEL_VS%
set %PATH%
```

**Comment by SevastyanDark** [comment]
```
C:\Users\dark\Desktop\cpp-tutorial\stage1\main>set BAZEL_SH
BAZEL_SH=C:\tools\msys64\usr\bin\bash.exe

C:\Users\dark\Desktop\cpp-tutorial\stage1\main>set BAZEL_VC
BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.13.26128\bin\Hostx64\x64

C:\Users\dark\Desktop\cpp-tutorial\stage1\main>set BAZEL_VS
BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community

C:\Users\dark\Desktop\cpp-tutorial\stage1\main>set PATH
Path=C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\HaxeToolkit\haxe\;C:\HaxeToolkit\neko;C:\Program Files\Mono;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\ProgramData\chocolatey\bin;C:\Users\dark\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\dark\AppData\Local\Programs\Python\Python36-32\;C:\Users\dark\AppData\Local\Microsoft\WindowsApps;C:\ProgramData\chocolatey\lib\msys2;C:\tools\msys64;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
```

**Comment by laszlocsomor** [comment]
Try this:

1. delete everything under `C:/users/dark/_bazel_dark/x7ca2npm`
2. open `cmd.exe`
3. run:
    ```
    set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC
    set BAZEL_VS=
    ```
4. now run bazel from this console

Does this help?

**Comment by SevastyanDark** [comment]
Nope, same output

**Comment by laszlocsomor** [comment]
Have you set the value of `BAZEL_VS` or `BAZEL_VC` to a quoted path before running Bazel?

Bazel still gets a quotes path from your environment. If so, that's indeed a Bazel bug.

Another bug is that the error message is really unhelpful, so we have to fix that.

Let's try the previous approach a bit more aggressively:

1. run `bazel clean --expunge`
2. open a new `cmd.exe`
3. set the `BAZEL_SH` and `PATH` environment variables to the values you had, but set `BAZEL_VS` and `BAZEL_VC` to empty; make sure none of these envvars have any quotes in their values
4. run bazel like so: `bazel --nomaster_bazelrc --bazelrc=NUL --output_user_root=c:\tmp1 build //main:hello-world`

**Comment by SevastyanDark** [comment]
Ok, fixed after restarting computer, thanks.
