### ISSUE TITLE
Documentation 404 for XcTestAppProvider

### ISSUE THREAD

**Issue by rahul-malik** [bazelbuild/bazel#5151]
### Description of the problem / feature request:
This URL is a 404: https://docs.bazel.build/versions/master/skylark/lib/XcTestAppProvider.html

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
It can be accessed from here: https://docs.bazel.build/versions/master/bazel-and-apple.html#apple-apps-and-new-rules

### What operating system are you running Bazel on?
macOS

**Comment by jin** [comment]
cc @sergiocampama, is XcTestAppProvider supposed to be documented?
