### ISSUE TITLE
Interop with external package manager

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#5154]
I believe this is similar to some internal discussion about interop with Maven, maybe @dslomov or @cgruber can clarify. I'll discuss what we need specifically for Frontend development which uses NPM. As far as I understand, npm and maven are similar problems.

Bazel WORKSPACE is the file which declares the toolchain dependencies, their versions, and also indicates what side-effects need to be performed before a build that relies on one of the toolchains.

npm is the frontend package manager. It also declares dependencies (including tools), their versions, and what side-effects must be performed when they are installed.

Bazel WORKSPACE is inadequate for Angular usage because it cannot:

- Indicate a toolchain that has a transitive dependency on another
- Govern the range of allowed versions of peer toolchains
- Automatically populate the side-effects when a toolchain is added

The desired user experience for Angular is:

1. (optional) User does some bootstrap step in order to be able to run the npm toolchain under Bazel (e.g. add a short stanza to WORKSPACE manually)
1. At this point, users should never need to look at WORKSPACE unless they add non-frontend-related toolchains not managed on npm
1. User installs npm packages using one of these commands: `npm install`, `yarn`, `bazel run @nodejs//:npm install` or `bazel run @yarn//:yarn`
1. WORKSPACE is automatically updated to point to matching versions of the toolchains and perform the side-effects
1. User adds a new dependency with `npm install`, `yarn add`, or the `bazel run` equivalents
1. The WORKSPACE is updated for that user with new transitive toolchain bits
If an existing toolchain is outside the required range, the user gets a warning and advice how to fix
1. Other users on the team pick up the WORKSPACE change when they sync. It contains load() statements under node_modules/ which may not exist yet (maybe the user never installed dependencies) but Bazel still lets them run the package manager command to fetch the toolchains

Npm ecosystem has a lock file (`yarn.lock` or `package-lock.json`) which has transitive deps and their versions pinned. This seems semantically equivalent to the WORKSPACE.resolved proposal currently discussed in Bazel team. 

We have two requirements that are different (?) from the Maven case:
- frontend developers typically run the package manager to install deps first, then use their editor tooling, then perform a build. If they already installed dependencies, we don't want Bazel to download them again.
- If Bazel does download the dependencies first, users still need to see the packages laid out in `node_modules` directory(ies) in their project. We could have more symlinks managed by Bazel that point the `node_modules` to the external repository where they are installed.

**Comment by ittaiz** [comment]
Alex,
I’ve been talking to various FED people about build tools and I keep
hearing that people don’t want to continue to use npm/yarn as they don’t
have confidence in them.
Are you sure this is the right direction?

**Comment by dslomov** [comment]
> Alex,
> I’ve been talking to various FED people about build tools and I keep
> hearing that people don’t want to continue to use npm/yarn as they don’t
> have confidence in them.
> Are you sure this is the right direction?

Who are these people and what do they want to use?
The ecosystem for npm/yarn is large and mature at this point - it behooves Bazel to support them
Of course, we do what to support other package managers as well.

**Comment by jin** [comment]
@ittaiz is it related to the integrity of the package managers from the various security incidents? Or the developer experience of npm?

**Comment by alexeagle** [comment]
@ittaiz I think vendoring all the dependencies into the repository with some security review when importing changes is the sane and safe thing to do, and is already supported here. As @dslomov says, we are just paving the primary path that supports the common existing use case to meet developers where they are.

**Comment by ittaiz** [comment]
My main point is that the FED Bazel community is young and small and it seems that already there is a divide on this matter. I don’t mind Bazel supporting this but my concern is more about fragmentation since the FED I’ve talked with (from Wix and other companies) complain about both of these tools (determinism, speed, experience in general) and would like to have Bazel manage everything.

I think I’ve hijacked this issue so I apologize but I’m just not sure where this discussion should take place.
@helenalt maybe BazelCon? It’s a bit late but if we’ll do it then then maybe I can get one of our FED infra people to come

**Comment by alexeagle** [comment]
I don't think we can force everyone to vendor their dependencies, but it
would be a great blog article to explain how we do it at Google with
examples for external users to follow.

**Comment by cgruber** [comment]
I'm working up a google-ish-yet-maven-ish example of bazel based on my prototype at square (very much oriented towards a monorepo, with a hybrid approach to vendoring dependencies so to speak), and I plan to open-source the pattern/example.  I also am prototyping a second version more suitable for smaller project, that should feel more natural to both the bazel side and the maven side.  

I think it addresses some of the issues in this thread (though obviously in a maven, not npm case).  I'll ping you, @alexeagle, when I can get it into an open repo.

**Comment by dslomov** [comment]
Update on this: 
 * @irengrig is working on support for npm integration
 * https://github.com/bazelbuild/rules_jvm_external is a nice way to integrate with maven.

**Comment by katre** [comment]
@lberki, you were discussing this today. Care to comment?

Downgrading priority.
