### ISSUE TITLE
Invalid License Error While Running bazel build

### ISSUE THREAD

**Issue by cagrigider** [bazelbuild/bazel#5157]
I am trying to compile tensorflow for Macbook, but every time when I use bazel build, I am getting same error.

When I Run this command

`bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`

I get this error

`/private/var/tmp/_bazel_cagrigider/2c548436011ab6b7308cd0cc70a91ed3/external/bazel_tools/tools/cpp/BUILD:3:1: invalid license type: 'notice'`

[Full Output Of Terminal](https://i.stack.imgur.com/S9MtY.png)

Mac OS 10.13.3

Xcode version = 9.2

Tensorflow version = 1.8

Bazel version = 0.13.0

Thanks.

**Comment by RNabel** [comment]
It looks like this is an error with tensorflow. Did you try building another project with bazel (for example the `bazel` repo)?

If you can build the `bazel` repo without a problem, I'd recommend you open an issue against [TensorFlow](https://github.com/tensorflow/tensorflow/issues).

**Comment by RNabel** [comment]
My guess is that your bazel is setup incorrectly. How did you install it? Are you sure that it is version `0.13.0`?

**Comment by cagrigider** [comment]
It says version 0.13.0.

I installed Bazel on this Mac with HomeBrew
but I also installed Bazel on another Mac using binary installer. Always I
get same error.

I installed from here.
https://docs.bazel.build/versions/master/install-os-x.html

**Comment by cagrigider** [comment]
I uninstalled bazel with :

brew uninstall --force bazel


Then installed again with:

brew install bazel


but still I got same license error.

**Comment by jin** [comment]
> I tried bazel example projects and I got same error
> I tried this examples examples

This is odd - could you please elaborate more on the steps you took to point of this error with the examples repository?

**Comment by cagrigider** [comment]
I can share this file. I ran these commands. And I got invalid license
error again.

**Comment by cagrigider** [comment]
I ran these commands

`cd Documents/examples/cpp-tutorial/stage1/`
`bazel build //main:hello-world`

then I got this error.

ERROR: /private/var/tmp/_bazel_cagrigider/4c2d107b81f30b45f844673a09f76011/external/bazel_tools/tools/cpp/BUILD:17:1: invalid license type: 'notice'
ERROR: /private/var/tmp/_bazel_cagrigider/4c2d107b81f30b45f844673a09f76011/external/bazel_tools/tools/cpp/BUILD:61:1: Target '@bazel_tools//tools/cpp:grep-includes.sh' contains an error and its package is in error and referenced by '@bazel_tools//tools/cpp:grep-includes'
ERROR: /Users/cagrigider/Documents/examples/cpp-tutorial/stage1/main/BUILD:1:1: every rule of type cc_binary implicitly depends upon the target '@bazel_tools//tools/cpp:malloc', but this target could not be found because of: Target '@bazel_tools//tools/cpp:malloc' contains an error and its package is in error
ERROR: /Users/cagrigider/Documents/examples/cpp-tutorial/stage1/main/BUILD:1:1: every rule of type cc_binary implicitly depends upon the target '@bazel_tools//tools/cpp:grep-includes', but this target could not be found because of: Target '@bazel_tools//tools/cpp:grep-includes' contains an error and its package is in error
ERROR: /Users/cagrigider/Documents/examples/cpp-tutorial/stage1/main/BUILD:1:1: every rule of type cc_binary implicitly depends upon the target '@bazel_tools//tools/cpp:stl', but this target could not be found because of: Target '@bazel_tools//tools/cpp:stl' contains an error and its package is in error
ERROR: /Users/cagrigider/Documents/examples/cpp-tutorial/stage1/main/BUILD:1:1: every rule of type cc_binary implicitly depends upon the target '@bazel_tools//tools/cpp:stl', but this target could not be found because of: Target '@bazel_tools//tools/cpp:stl' contains an error and its package is in error
ERROR: Analysis of target '//main:hello-world' failed; build aborted: Loading failed

**Comment by jin** [comment]
could you please paste the contents of the file `/private/var/tmp/_bazel_cagrigider/4c2d107b81f30b45f844673a09f76011/external/bazel_tools/tools/cpp/BUILD` here?

**Comment by jin** [comment]
could you please paste line 17 of the `BUILD` file in that directory?

**Comment by cagrigider** [comment]
licenses(["notice"])  # Apache 2.0

**Comment by jin** [comment]
Ok, I'm quite stumped here. Could you please run `bazel clean --expunge` and try a clean build?

**Comment by RNabel** [comment]
Something else worth trying is to check whether you are using the bazel that homebrew provides, using `which bazel` and whether `bazel version` returns `bazel 0.13.0-homebrew`. My homebrew bazel is located at `/usr/local/bin/bazel`.

**Comment by cagrigider** [comment]
`which bazel`
returns :
`/usr/local/bin/bazel`

And `bazel version` returns

`Build label: 0.13.0-homebrew`
`Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar`

**Comment by jin** [comment]
Could this be an encoding/parsing issue? + @laurentlb for Skylark

**Comment by jin** [comment]
It could be at "notice".toUpperCase() on your system locale does not convert it to "NOTICE".

**Comment by cagrigider** [comment]
Is there anything I can do to fix this error?

**Comment by davido** [comment]
> Is there anything I can do to fix this error?

Sure, attach the debugger and check what is going on here:

```java
    licenseTypes.add(LicenseType.valueOf(str.toUpperCase()));
```

**Comment by cagrigider** [comment]
How can I attach the debugger on this code ?

**Comment by davido** [comment]
See https://bazel.build/contributing.html, particularly "Debugging Bazel" section. Basically, you need to set up IntelliJ IDEA project and call Bazel with: `bazel --host_jvm_debug build  foo` and attach remote dbugger from the IDE to the specified port.

**Comment by cagrigider** [comment]
After I did this step when preparing IntelliJ IDEA `install it from within the IDE (Settings > Plugins > Install > Browse Repositories, and search for 'Bazel').`

I can't see that, `Preferences > Other Settings > Bazel Settings` on macOS IntelliJ IDEA

**Comment by cagrigider** [comment]
When I am did this `install it from within the IDE (Settings > Plugins > Install > Browse Repositories, and search for 'Bazel'` 
I found only 'Bazel Build Formatter' plugin, Is that right one ?

**Comment by cagrigider** [comment]
And also, before creating project it wants me to build bazel .

`cd bazel`
  `bazel build //src:bazel`
This will produce a working Bazel binary in bazel-bin/src/bazel.
If everything works fine, feel free to configure your favorite IDE in the following steps.

**Comment by RNabel** [comment]
@cagrigider The IntelliJ plugin appears to only be supported in 2017.x versions (issue on their repo: https://github.com/bazelbuild/intellij/issues/290), so you are going to have to rollback to 2017.3.5 which is the last 2017 release. If you don't already, you may want to use the [JetBrains Toolbox App](https://www.jetbrains.com/toolbox/app/) which makes installing and upgrading to specific IntelliJ versions really easy.

**Comment by cagrigider** [comment]
It says :
Start creating a debug configuration for both C++ and Java in your .bazelrc with the following:

`build:debug -c dbg`
`build:debug --javacopt="-g"`
`build:debug --copt="-g"`
`build:debug --strip="never"`

Then you can rebuild Bazel with bazel build --config debug //src:bazel and use your favorite debugger to start debugging.

So I should open my bazel.bazelrc file as a text file and paste these lines into it. Then rebuild ?

**Comment by cagrigider** [comment]
Now my .bazelrc file is empty

**Comment by jin** [comment]
Could you please try passing the flag `--host_jvm_args=-Duser.language=en` to your `bazel build` command?

**Comment by RNabel** [comment]
@cagrigider adding `--config some_config` to your execution of `bazel` is the same as adding all flags specific in the config into the command line, i.e. `bazel build -c debug --javacopt="-g" --copt="-g" --strip="never" //src:bazel` for the debug build.

As @jin indicated, it would also be good to try setting user.language: `bazel --host_jvm_args=-Duser.language=en build //src:bazel`. Then run your build with the resulting binary.

**Comment by cagrigider** [comment]
I m trying this now `bazel --host_jvm_args=-Duser.language=en build //src:bazel` and it s looking like working. It didn't give any license error.
If it finish successfully, it means it will work without any problem because of this flag settings ?

**Comment by jin** [comment]
Yeah, it looks like the problem is with your system's locale setting. No worries, we should force the Locale to be `en` while performing `str.toUpperCase` in the code. I'll send in a fix.

> If it finish successfully, it means it will work without any problem because of this flag settings ?

Yes, for now, you should run any `bazel build` command with the `--host_jvm_args=-Duser.language=en`. You can also add it into your project's `.bazelrc` file like this:

```
# In $PROJECT/.bazelrc
startup --host_jvm_args=-Duser.language=en
```

**Comment by jin** [comment]
Good to hear :-)
