### ISSUE TITLE
User Manual Page Could Really Use a TOC

### ISSUE THREAD

**Issue by nathantchan** [bazelbuild/bazel#5169]
### Description of the problem / feature request:

The user manual page is really long, and it includes descriptions of bazel commands, command-line options, hermeticity, sandboxing, etc. It could really use a Table of Contents so users have a better idea of what's there and can skip to the section they are actually interested in solving.

### Feature requests: what underlying problem are you trying to solve with this feature?

Better documentation and surfacing of useful information.

**Comment by jin** [comment]
Every page now has a ToC. 

https://docs.bazel.build/versions/master/user-manual.html
