### ISSUE TITLE
Prevent self-referencing external repo

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#517]
Currently if you by accident specify an external repo in the external repo (self-reference), Bazel does accept the path, but does not seem able to handle the path correctly. This leads to nasty errors and currently I cannot think of a reason, why you would want to be able to reference the current external repo inside the repo.

**Comment by lberki** [comment]
What do you mean by "specifying an external repo in the external repo"? A few WORKSPACE/BUILD file excerpts and maybe the directory structure of your repositories would help tremendously.

**Comment by abergmeier** [comment]
The entry in `WORKSPACE`:

    new_http_archive(
      name = "boost",
      url = "http://boost.org/archive.zip",
      build_file = "my.BUILD",
    )

and a `my.BUILD` with

    cc_library(
      name = "my",
      srcs = "@boost//glorioussource.cpp",
    )

should demonstrate the issue.
There may be one reason, when this may make sense - when you use `my.BUILD/my` from different repos.

**Comment by lberki** [comment]
Can't reproduce (if for no other reason, but because `http://boost.org/archive.zip` is a 404... it also seems strange, because in a repository called `boost`, `@boost//:foo` is exactly equivalent to `@boost`. What error message do you get? Maybe you need to add the `includes=["."]` attribute to your cc_library?

I tried this:

```
echo 'new_local_repository(name="l", path=__workspace_dir__ + "/l", build_file="my.BUILD")' > WORKSPACE
cat > my.BUILD <<EOF
cc_library(name = "c", hdrs = ["c.h"])
cc_binary(name="cb", deps=["@l//:c"], srcs=["cb.cc"])
EOF
mkdir l
echo '#define MACRO 42' > l/c.h
cat > l/cb.cc <<EOF
#include "c.h"
int main(void) { return MACRO; }
EOF
bazel build @l//:cb
```

**Comment by kchodorow** [comment]
This has since been fixed.
