### ISSUE TITLE
bazel build error: java.lang.module.InvalidModuleDescriptorException: Bad constant pool entry: 4

### ISSUE THREAD

**Issue by PrinceP** [bazelbuild/bazel#5176]
bash ./compile.sh 
🍃  Building Bazel from scratch..../usr/lib/jvm/java-9-openjdk-amd64/bin/jar cmf /tmp/bazel_o1mlEWak/MANIFEST.MF /tmp/bazel_o1mlEWak/libblaze.jar -C /tmp/bazel_o1mlEWak/classes about.html -C /tmp/bazel_o1mlEWak/classes A.class -C /tmp/bazel_o1mlEWak/classes android -C /tmp/bazel_o1mlEWak/classes AnnotatedClass.class -C /tmp/bazel_o1mlEWak/classes Annotations.class -C /tmp/bazel_o1mlEWak/classes Annotations$ParametersOnlyAnnotation.class -C /tmp/bazel_o1mlEWak/classes Annotations$RuntimeInvisible.class -C /tmp/bazel_o1mlEWak/classes Annotations$RuntimeVisible.class -C /tmp/bazel_o1mlEWak/classes asm-license.txt -C /tmp/bazel_o1mlEWak/classes AUTHORS -C /tmp/bazel_o1mlEWak/classes autovalue -C /tmp/bazel_o1mlEWak/classes B.class -C /tmp/bazel_o1mlEWak/classes blogspot -C /tmp/bazel_o1mlEWak/classes build-receipt.properties -C /tmp/bazel_o1mlEWak/classes cglib-license.txt -C /tmp/bazel_o1mlEWak/classes changelog.txt -C /tmp/bazel_o1mlEWak/classes com -C /tmp/bazel_o1mlEWak/classes deps.proto -C /tmp/bazel_o1mlEWak/classes foo -C /tmp/bazel_o1mlEWak/classes gradle-cli-classpath.properties -C /tmp/bazel_o1mlEWak/classes gradle-wrapper-classpath.properties -C /tmp/bazel_o1mlEWak/classes hamcrest-license.txt -C /tmp/bazel_o1mlEWak/classes hazelcast-client-config-3.0.xsd -C /tmp/bazel_o1mlEWak/classes hazelcast-client-config-3.1.xsd -C /tmp/bazel_o1mlEWak/classes hazelcast-client-config-3.2.xsd -C /tmp/bazel_o1mlEWak/classes hazelcast-client-config-3.3.xsd -C /tmp/bazel_o1mlEWak/classes hazelcast-client-config-3.4.xsd -C /tmp/bazel_o1mlEWak/classes hazelcast-client-config-3.5.xsd -C /tmp/bazel_o1mlEWak/classes hazelcast-client-config-3.6.xsd -C /tmp/bazel_o1mlEWak/classes hazelcast-client-default.xml -C /tmp/bazel_o1mlEWak/classes hazelcast-client-full.xml -C /tmp/bazel_o1mlEWak/classes hazelcast-common-config-3.0.xsd -C /tmp/bazel_o1mlEWak/classes hazelcast-common-config-3.1.xsd -C /tmp/bazel_o1mlEWak/classes hazelcast-config-3.0.xsd -C /tmp/bazel_o1mlEWak/classes hazelcast-config-3.1.xsd -C /tmp/bazel_o1mlEWak/classes hazelcast-config-3.2.xsd -C /tmp/bazel_o1mlEWak/classes hazelcast-config-3.3.xsd -C /tmp/bazel_o1mlEWak/classes hazelcast-config-3.4.xsd -C /tmp/bazel_o1mlEWak/classes hazelcast-config-3.5.xsd -C /tmp/bazel_o1mlEWak/classes hazelcast-config-3.6.xsd -C /tmp/bazel_o1mlEWak/classes hazelcast-default.xml -C /tmp/bazel_o1mlEWak/classes hazelcast-download.properties -C /tmp/bazel_o1mlEWak/classes hazelcast-full-example.xml -C /tmp/bazel_o1mlEWak/classes hazelcast-runtime.properties -C /tmp/bazel_o1mlEWak/classes io -C /tmp/bazel_o1mlEWak/classes jacocoagent.jar -C /tmp/bazel_o1mlEWak/classes javax -C /tmp/bazel_o1mlEWak/classes jdk -C /tmp/bazel_o1mlEWak/classes junit -C /tmp/bazel_o1mlEWak/classes LICENSE -C /tmp/bazel_o1mlEWak/classes licenses -C /tmp/bazel_o1mlEWak/classes LICENSE.txt -C /tmp/bazel_o1mlEWak/classes lombok -C /tmp/bazel_o1mlEWak/classes module-info.class -C /tmp/bazel_o1mlEWak/classes module-info.java -C /tmp/bazel_o1mlEWak/classes mozilla -C /tmp/bazel_o1mlEWak/classes net -C /tmp/bazel_o1mlEWak/classes NOTICE -C /tmp/bazel_o1mlEWak/classes objenesis-license.txt -C /tmp/bazel_o1mlEWak/classes org -C /tmp/bazel_o1mlEWak/classes plugin.properties -C /tmp/bazel_o1mlEWak/classes proguard -C /tmp/bazel_o1mlEWak/classes release_notes.txt -C /tmp/bazel_o1mlEWak/classes textfile.txt
java.lang.module.InvalidModuleDescriptorException: Bad constant pool entry: 4
	at java.lang.module.ModuleInfo.invalidModuleDescriptor(java.base@9-internal/ModuleInfo.java:779)
	at java.lang.module.ModuleInfo.access$000(java.base@9-internal/ModuleInfo.java:56)
	at java.lang.module.ModuleInfo$ConstantPool.<init>(java.base@9-internal/ModuleInfo.java:606)
	at java.lang.module.ModuleInfo.doRead(java.base@9-internal/ModuleInfo.java:159)
	at java.lang.module.ModuleInfo.read(java.base@9-internal/ModuleInfo.java:87)
	at java.lang.module.ModuleDescriptor.read(java.base@9-internal/ModuleDescriptor.java:1813)
	at sun.tools.jar.Main.addExtendedModuleAttributes(jdk.jartool@9-internal/Main.java:1751)
	at sun.tools.jar.Main.run(jdk.jartool@9-internal/Main.java:242)
	at sun.tools.jar.Main.main(jdk.jartool@9-internal/Main.java:1528)

**Comment by philwo** [comment]
No clue. Maybe your JDK is broken somehow? That error message looks like some strange internal error :|

We also committed some Java 9 compatibility fixes to Bazel in the last two months. Is it working now, perhaps?

**Comment by lberki** [comment]
FWIW, I ran into this, too, on a fresh Ubuntu 16.04 Docker container with bazel-0.18.1-dist.zip . It seems that `$JAVA_HOME` *still* needs to be set to a JDK 8 :(

**Comment by jin** [comment]
Clsoing as obsolete.
