### ISSUE TITLE
Documentation: Sections in contributing.html are not linkable

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#5179]
This site is correct: https://docs.bazel.build/versions/master/bazel-overview.html.

I'm able to link section: "How do I get started?": https://docs.bazel.build/versions/master/bazel-overview.html#how-do-i-get-started.

[contributing.html](https://bazel.build/contributing.html) site doesn't offer section links. I cannot link: "Debugging Bazel" section.

**Comment by jin** [comment]
cc @spomorski

**Comment by spomorski** [comment]
This is because the Contribute section is on the "blog" site which is separate from the "docs" site. Can a Google SWE compare the code between the two?

**Comment by jin** [comment]
This seems to be fixed: https://bazel.build/contributing.html#debugging-bazel 

Maybe by the recent kramdown migration?
