### ISSUE TITLE
Extracting file permission in zip fails in 0.1.1

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#518]
In 0.1.1, when I try add `zip` files like:

    new_http_archive(
      name = "glm",
      url = "https://github.com/g-truc/glm/releases/download/0.9.4.6/glm-0.9.4.6.zip",
    )

I get errors for all tried zip files (all from github):

    Unrecognized file mode for glm: 0x10

This worked fine in 0.1.

**Comment by kchodorow** [comment]
Working on this, but even when the permissions issue is fixed, there are illegal (to Bazel) filenames in the zip (like ~$glm.docx).  So, the permissions issue is fixable, but you'll still need #374.

**Comment by abergmeier** [comment]
Ah interesting. Thanks for pointing that out. Will have to repackage at least _glm_ then.

**Comment by kchodorow** [comment]
So... I might have a hacky solution.  It looks like ~$glm.docx is a backup file and thus _has a different file permission_ than the other files in the .zip.  I'd guess this is Windows letting you mark backup files as such.  Anyway, it seems reasonable for Bazel to skip writing backup files when it's unzipping the zip (at least for now).  And all of the legit files in the archive have Bazel-allowed names.

**Comment by abergmeier** [comment]
Sounds great but would love to have to explicitly set a `ignore_extract_error`.

**Comment by kchodorow** [comment]
#374 isn't a problem with extracting a file (it's a problem Bazel hits later on when it's trying to gather up a rule's inputs) and I don't think "ignore all possible errors during extraction" is a good option to add, since the error you ran into (for example) is a bug.

**Comment by kchodorow** [comment]
As long as you don't depend on the weird-named file (e.g., `glob("**/*")`), this should work with glm.
