### ISSUE TITLE
Provide a way to use system-provided dependency instead of building one from source

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#5188]
This is a common feature request but I couldn't find it among issues. This is important for package maintainers, who need to split the "monorepo" style into more unixy style where third_party dependencies are installed on the system separately.

Details on why bundling everything in a single binary can be undesirable:
https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies
https://fedoraproject.org/wiki/Bundled_Libraries

**Comment by mhlopko** [comment]
Comment from the user:

> Ideally it would be great if bazel had a way to query pkg-config for the
> deps. There is cc_library() for bazel bundled stuff maybe there could be
> some kind of pkg-config_library(name="libpcre") and it would then do
> CFLAGS+=$(pkg-config --cflags libpcre); LDLIBS+=$(pkg-config --libs libpcre)
> and use that in place of recompiling the deps.

**Comment by mhlopko** [comment]
Related for package maintainers: https://github.com/bazelbuild/bazel/issues/5186

**Comment by aiuto** [comment]
This is a fun project. I think there are a few parts to it

- rules_cc specific, where we identify .h & .so files
- but it is not just C++. Using Frameworks in ObjectiveC is important for MacOS. Likewise, Windows SDKs are presumed to be on the target system.
- generic - find this binary on the system to create a toolchain for 'x'.  We do something like this for autoconfiguring compilers, but there are lots of tools which people might want to install in their build images that are not needed at runtime (e.g. image format converters, OS specific packaging tools, tools that are not available in source).
- If we are building packages for distribution, there is usually a need to specify dependencies to be installed on the target OS by the package manager. We might not be able to build many of those from source, but need to install the binary for things like testing the built image.

**Comment by Kernald** [comment]
Having spent a big part of my week-end trying to link a C binary to the system-provided ncurses, I would love seing that becoming a thing.

**Comment by aiuto** [comment]
I believe Yun did a lot of work on this concept for the Debian support.
