### ISSUE TITLE
$(location) and $(locations) do not properly quote file paths

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/bazel#5190]
Follow up on #3475

### Description of the problem / feature request:

A genrul using $(locations) fails with 'unbounded shell variable'.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
filegroup(
  name = "files",
  srcs = glob(["dir/*"]),    # put files with special chars here, e.g. $data.json, @foo.bar, ...
)

genrule(
  name = "example",
  srcs = [":files"],
  outs = ["foo"],
  cmd = "echo FILES: $(locations //:files) | tee $@",
)
```

### What operating system are you running Bazel on?

linux

### What's the output of `bazel info release`?

release 0.13.0

###  Have you found anything relevant by searching the web?

#3475

**Comment by aehlig** [comment]
My suggested fix is https://bazel-review.googlesource.com/c/bazel/+/56250

But note that there is no "correct" quoting of `$(location)` as those
`$(location)` arguments can occur in various places. To me, the following
all seem correct uses of a genrule (where `script` is the GNU version of
`script(1)`).

```
cmd = "$(location :tool) $(location :files)"
```

```
cmd = "script -c '$(location :tool) $(location :files)' $(location :log)"
```

```
cmd = 'script -c "$(location :tool) $(location :files)" $(location :log)'
```


-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado
