### ISSUE TITLE
Custom bazel-bin location generation per sub-package not working ?

### ISSUE THREAD

**Issue by infojg9** [bazelbuild/bazel#5195]
Dear Bazel users,

In short, how we can customize: 1. "bazel-bin" location with "bazel-bin/opt" and 2. "bazel-bin/subpackage-A/" with "bazel-bin/opt/subpackage-A/bin/" by any technical means ?

Similar to "output_to_bindir=1" concept, how any Bazel package at root level, allow any generic ctx.actions/genrule/plugin can be extended/utilized, to define per sub-package specific custom target output path "bazel-bin/opt/subpackage-A/bin/" location ?

We are not very sure whether the problem is in our api implementation usage or Bazel specification ( for example: [declare_directory](https://docs.bazel.build/versions/master/skylark/lib/actions.html#declare_directory), [genrule](https://docs.bazel.build/versions/master/be/general.html#genrule) ) limitation ?

 
Assume the build has the basic structures as inline:

    ```
root/BUILD, root/build_rules.bzl
    |
    |--subpackage-A/BUILD
    |    |--name
    |    |--bins
    |    |--etcs
    |    |--deps
    |    ...
    |
    |--subpackage-B/BUILD
    |    |--name
    |    |--bins
    |    |--etcs
    |    |--deps
    ...  ...
    
    ----
    
    Default generation with "output_to_bindir=1" under ctx.actions.run_shell():
    
        ctx.actions.run_shell(
          # COMMENTED CODES DOES NOT WORK EVEN ON BAZEL 0.13.0
          #arguments = ["-p", ctx.bin_dir, ],
          #arguments=[ output1.path, ctx.outputs.out.path, ],
          #inputs=[ctx.files.deps[a]],
          #outputs = ["opt/"+ctx.label.name+"/bin/"+file_name],
          #outouts=[":bazel-bin" + "/opt/" + file_name + "/bin/"],
          progress_message="run_shell.....",
          command="cp -vf $< $@",
          local = 1,
          output_to_bindir=1
        )
    
    default output structure:

    bazel-bin
    |--root_app1
    |
    |--sub-pkg-A
    |    |--childA_app1
    |--sub-pkg-B
    |    |--childB_app1
    
    
    ----
    
    Now, the desired generation structure would looks like:
    
    bazel-bin
    |--opt
    |   |--root_app1
    |   |
    |   |--sub-pkg-A
    |   |    |--bin
    |   |        |--childA_app1
    |   |
    |   |--sub-pkg-B
    |   |    |--bin
    |   |        |--childB_app1

```

Is the above expected generation structure is technically feasible using Bazel specification, the top level root/build_rules.bzl can perform the following tasks:

The parameter bins from [subpackage-A|subpackage-B|...], should only take cc_binary labels and those targets should be copied under "bazel-bin/opt/[subpackage-A|subpackage-B|...]/bin/"

The parameter etcs should only take a filegroup and those files in the filegroup should be copied under "bazel-bin/opt/[subpackage-A|subpackage-B|...]/etc/"

An attempt with genrule() thrown error: genrule() cannot be called during the analysis phase.

----
An further attempt with ctx.actions.declare_directory() custom deployments also facing compilation errors evene with Bazel 0.13.0 latest label.

```
root/build_rules.bzl
def _extrule(ctx):
  dir = ctx.actions.declare_directory("opt/child1/bin")
  ctx.actions.run_shell(
    #outputs = [dir, ctx.outputs.out],
    outputs = [dir],
    command = "mkdir -p " + dir.path + "; cp -vf $< $@",
    progress_message="run_shell.....",
    output_to_bindir=1
    )

extrule = rule(
  implementation = _extrule,
  outputs = {
  "out": outputs.dir(default="opt/child1/bin"),
  },
  output_to_genfiles = False,
  attrs = {
    # Do not declare "name": It is added automatically. 
    # https://github.com/bazelbuild/examples/blob/master/rules/attributes/printer.bzl
    "number": attr.int(default = 1),
    "bins": attr.label_list(),
    "deps": attr.label_list(),
    "etcs": attr.label_list(),
  },
)

$ bazel clean; bazel build -s ...
INFO: Starting clean (this may take a while).
ERROR: /home/user/root_pkg/build_rules.bzl:line:xx: name 'outputs' is not defined
ERROR: error loading package '': Extension 'build_rules.bzl' has errors
INFO: Elapsed time: 0.090s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading:  ... (2 packages)


$ bazel version
Build label: 0.13.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 18 21:33:40 +50297 (1525078013620)
Build timestamp: 1525078013620
Build timestamp as int: 1525078013620

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
user@hostname $ uname -a
Linux hostname 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

----

@mhlopko, Bazel users, any idea/hint would be highly appreciated.

**Comment by aehlig** [comment]
It is by design that the structure in all output directories follow the structure of the packages. If you need a special structure (e.g., everything under `opt` as in your example), reflecting that structure in an archive generated by [`pkg_tar`](https://docs.bazel.build/versions/master/be/pkg.html#pkg_tar) is currently the best we can offer.

We are aware that bazel is still lacking an install target (and we have nobody is currently working on it), but that could be a simple [`sh_binary`](https://docs.bazel.build/versions/master/be/shell.html#sh_binary) with that archive (wrapped in a `sh_library`) as `data` dependency.
