### ISSUE TITLE
xcode-locator-bin is run too many times

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/bazel#5196]
While investigating https://github.com/bazelbuild/bazel/issues/4603, which spilled into https://github.com/google/santa/issues/260, we have discovered that Bazel is *building and running* `xcode-locator-bin` too many times. This may be exacerbating the issue we see in the original bug.

Things I have found so far:

* This tool is compiled and executed from https://source.bazel.build/bazel/+/master:tools/osx/xcode_configure.bzl;l=116?q=xcode_configure.bzl . This seems to be the only code where the compilation and execution happens. Adding a print statement there shows that the tool is run exactly once.

* Instrumenting the `xcode_locator.m` file to record invocations shows that the tool is built and executed about 15 times. 14 for `local_config_cc` and once for `local_config_xcode`.

* The print statement introduced in `xcode_configure.bzl` only triggers for the call that happens for `local_config_xcode`; all other calls happen earlier and don't trigger the print statement. It's unclear to me how the calls for `local_config_cc` skip the message printing given that they delegate to `xcode_configure.bzl` to actually run the tool.

* Instrumenting `SkylarkExecutionResult.java` does show that we are calling `repository_ctx.execute()` multiple times.

* I fear that we are running the CC autoconfiguration multiple times by mistake without noticing... but though that should trigger the print statement and it doesn't.

* Mind you, adding a print statement at the beginning of `cc_configure` shows the message *after* all the spurious `xcode-locator` invocations have happened, and only once.

* Not to mention that this all takes **seconds** to run. Fixing this could speed up clean builds significantly.

All of this stuff is pretty complex and I don't have sufficient context right now. Maybe the issue is easy to explain so looping in the experts before I spend more time on it.

**Comment by c-parsons** [comment]
Wow, the fact that we built it 15 times is a huge bug.
This also makes very little sense to me. We find that SkylarkExecutionResult.execute() on xcode_locator.m is run 15 times, but the only caller of skylark execute() on xcode_locator.m is only called once?

Is there some sort of aggressive retry logic for execute()?
Maybe we're not seeing all the caller print statements?

**Comment by jmmv** [comment]
I have no idea... I could imagine `execute()` retrying on failure, but note that `xcode_configure.bzl` checks for error codes and we are not triggering that path. So I don't think that's the case.

Another theory is that we are running this multiple times because we have multiple threads and each decides to trigger this code path. However, `--jobs=1` does not suppress this behavior not does mutilating `SkyframeExecutor` to hardcode exactly 1 thread everywhere. So unlikely as well.

Maybe we are not seeing the print statements as you say. That may be possible, but strange as well.

**Comment by ulfjack** [comment]
Philipp said on the internal bug that we're restarting auto-configuration. I think what could happen is that we actually call print 15 times, but 14 of those are suppressed by Skyframe due to the restart.

Why are we _building_ the binary in the auto-config? That sounds wrong. Why can't we use a precompiled binary?

**Comment by ulfjack** [comment]
(I'm not sure what triggers Skyframe restarts for workspace rules.)

**Comment by c-parsons** [comment]
I think originally we simply wanted to avoid pre-compiled binaries, but I see no reason we couldn't precompile the binary now.

**Comment by ulfjack** [comment]
Another option might be to rewrite xcode-locator in Skylark. IIUC, it's only job is to call LSCopyApplicationURLsForBundleIdentifier and post-process the results (correct me if I'm wrong). We could provide a Skylark API for that (and possibly make it more generic so it can also locate other bundles).

**Comment by jmmv** [comment]
Why is building the binary wrong? Shipping a prebuilt binary or rewriting the code seems like a hack to avoid the underlying problem we trigger, not a solution.

The fact that we are triggering Skyframe restarts so many times seems more concerning to me. Note that Bazel gets stuck for a few *seconds* while this process takes place at analysis time, so I feel digging down the root cause of the restarts could help performance as well.

**Comment by ulfjack** [comment]
Sure, that won't hurt.

**Comment by jmmv** [comment]
OK, so ended up discovering `RepositoryFunction#restart()` which allows for the reexecution of a Skylark repository function (which the autoconfiguration is). Turns out we trigger a restart multiple times, and each time we do so go through the autoconfiguration code that builds and runs `xcode-locator-bin`. I had to add additional details to the exception to see what was happening, but we call restart due to the following missing files / packages, in this order:

````
/private/var/tmp/_bazel_jmmv/dbb592e2bbc9bb91bba9a9369635ca90/external/bazel_tools/tools/cpp/dummy_toolchain.bzl
/private/var/tmp/_bazel_jmmv/dbb592e2bbc9bb91bba9a9369635ca90/external/bazel_tools/tools/osx/xcode_locator.m
/private/var/tmp/_bazel_jmmv/dbb592e2bbc9bb91bba9a9369635ca90/external/bazel_tools/tools/cpp/osx_cc_wrapper.sh.tpl
@bazel_tools//tools/objc
/private/var/tmp/_bazel_jmmv/dbb592e2bbc9bb91bba9a9369635ca90/external/bazel_tools/tools/objc/xcrunwrapper.sh
/private/var/tmp/_bazel_jmmv/dbb592e2bbc9bb91bba9a9369635ca90/external/bazel_tools/tools/objc/libtool.sh
/private/var/tmp/_bazel_jmmv/dbb592e2bbc9bb91bba9a9369635ca90/external/bazel_tools/tools/objc/make_hashed_objlist.py
@bazel_tools//tools/osx/crosstool
/private/var/tmp/_bazel_jmmv/dbb592e2bbc9bb91bba9a9369635ca90/external/bazel_tools/tools/osx/crosstool/wrapped_ar.tpl
/private/var/tmp/_bazel_jmmv/dbb592e2bbc9bb91bba9a9369635ca90/external/bazel_tools/tools/osx/crosstool/BUILD.tpl
/private/var/tmp/_bazel_jmmv/dbb592e2bbc9bb91bba9a9369635ca90/external/bazel_tools/tools/osx/crosstool/osx_archs.bzl
/private/var/tmp/_bazel_jmmv/dbb592e2bbc9bb91bba9a9369635ca90/external/bazel_tools/tools/osx/crosstool/wrapped_clang.cc
/private/var/tmp/_bazel_jmmv/dbb592e2bbc9bb91bba9a9369635ca90/external/bazel_tools/tools/osx/crosstool/CROSSTOOL.tpl
```

I still believe that shipping `xcode-locator-bin` as a prebuilt binary would just hide the underlying problem. I don't see why we need to go through the same discovery process more than once.

**Comment by katre** [comment]
What do you mean by "due to the following missing files / packages"? Many
of these certainly exist.

**Comment by jmmv** [comment]
Spoke to @janakdr and we understand the problem now.

The `symlink()` calls made from the autoconfiguration code in the Skylark repository functions need to look up their arguments, and if those arguments are `Label`s (which they are), the lookups cause the repository function to be restarted.

This is a known weakness in Skyframe. The real solution is to support in-thread evaluation of other functions so that those label resolutions could be made without a restart. There are no current plans to address this, but I'll file a separate bug to track this feature request (so that we can collect all the cases in which it could help).

For now I'll try to refactor the Skylark code to delay the external command execution until after all labels have been resolved. That will not resolve the restarts, but will minimize their cost and hopefully result in us only building and executing `xcode-locator-bin` once.

**Comment by ulfjack** [comment]
I don't think in-thread evaluation is going to solve the restart problem. It may reduce the number of restarts, sure, but it's not going to eliminate them - the problem is that the stack size is limited, while label lookup can be unbounded (due to the need to resolve all symlinks on the path to the package), so there's a good chance we'll still have to restart. The only proper solution is some form of continuations, possibly emulated in Java.

That said, it'd be a good idea to build and run the xcode-locator binary as part of the build rather than as part of workspace configuration (note that workspace configuration is on the critical path for everything), whereas if it's done as part of the build (execution phase), it can be done in parallel to other actions if those don't depend on the xcode location.

**Comment by jmmv** [comment]
Tried a stupid code reorganization to minimize the number of rebuilds, which cut down the load/analysis time of Bazel's own build from 13 seconds to 7 seconds. I suspect this will mitigate/prevent https://github.com/google/santa/issues/260 but I haven't been able to confirm yet (not able to reproduce at this point, which may be a good sign).

OK, so now that we understand the underlying problem, I agree that shipping the `xcode-locator` as a precompiled embedded binary may be a good idea. After all, building it takes some precious analysis time, and are still doing this a few times. About making this part of the build, I'm not sure how it'd be done at this point: haven't put any thought on it, but I'm afraid this may require changing how the autoconfiguration process works on the Mac?
