### ISSUE TITLE
bazel version: build time off by 1000x

### ISSUE THREAD

**Issue by g-easy** [bazelbuild/bazel#5199]
### Description of the problem:

bazel reports it was built in the year 50297.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```shell
$ bazel version
[...]
Build time: Mon Oct 18 21:33:40 +50297 (1525078013620)

$ env TZ=America/Los_Angeles date --date=@1525078013620
Mon Oct 18 14:33:40 PDT 50297

$ env TZ=America/Los_Angeles date --date=@1525078013.620
Mon Apr 30 01:46:53 PDT 2018
```

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 0.13.0

**Comment by buchgr** [comment]
Thanks for reporting this issue. This has been fixed already i.e. in Bazel 0.14.0.

https://releases.bazel.build/0.14.0/rc1/index.html
