### ISSUE TITLE
Implement C++ Transitive Libraries

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#5200]
This is a tracking issue for the transitive libraries effort.

Design doc: https://docs.google.com/document/d/1d4SPgVX-OTCiEK_l24DNWiFlT14XS5ZxD7XhttFbvrI/edit#

**Comment by byronyi** [comment]
Any updates?

**Comment by oquenchil** [comment]
We are working on it:
https://github.com/bazelbuild/rules_cc/blob/master/examples/experimental_cc_shared_library.bzl

You need to use it with the flag --experimental_cc_shared_library.

Beware that we are constantly making breaking changes as we iterate on the design.
