### ISSUE TITLE
 bootstrapping 0.14.0rc1 requires network access

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/bazel#5202]
As opposed to earlier versions of bazel, bootstrapping bazel with `bash compile.sh` from the distribution artifact (as described in https://docs.bazel.build/versions/master/install-compile-source.html) requires network access. The reason is that `//tools/android:embedded_tools` pulls in `@desugar_jdk_libs` which is an `http_archive`.

Depending on our policy this may or may not block #5056, i.e. the 0.14.0 release.

Possible solutions include
- adding the lib to the distribution archive
- not embedding the lib in android tools

**Comment by jin** [comment]
+@kevin1e100

**Comment by jin** [comment]
https://github.com/google/desugar_jdk_libs is 5.7MB with `git clone depth=1`, which is about 3% of the size of the distribution archive.

**Comment by laszlocsomor** [comment]
> Possible solutions include
> - adding the lib to the distribution archive
> - not embedding the lib in android tools

For the second option: requiring the user adds a `http_archive` rule to their `WORKSPACE` file feels like the right approach, given how they also have to uncomment (or add) `android_sdk_repository` and `android_ndk_repository` rules.

**Comment by kevin1e100** [comment]
+@ahumesky

IIUC, having users add the http_archive rule will require users to have network access when building (any?) Android artifacts, is that realistic?  Could you please point us to any background why needing network access for building Bazel is problematic?

**Comment by lfpino** [comment]
Do we know which commit introduced the problem?

**Comment by aehlig** [comment]
> Do we know which commit introduced the problem?

I would guess bfd89d6393fd56c92c0b31b19d7ec78d8da9141f. But a quick forward fix like https://bazel-review.googlesource.com/c/bazel/+/56490 is probably less pain than a rollback.

**Comment by ahumesky** [comment]
I have a change in progress that puts the external dependency into bazel's repo under third_party. I'll send it out tomorrow.
