### ISSUE TITLE
direct_run changes locale

### ISSUE THREAD

**Issue by drigz** [bazelbuild/bazel#5203]
### Description of the problem / feature request:

Using `bazel run --direct_run` runs the binary with a different locale to either `bazel run --nodirect_run` or `bazel-bin/path/to/binary`.

I noticed this because it results in the following warnings when used in a VM that doesn't have en_US.ISO-8859-1 installed:

```
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.ISO-8859-1)
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.ISO-8859-1)
```

### Repro

Set up the workspace:

```
cat > test.sh << EOF
#!/bin/bash
locale
EOF
chmod +x test.sh
cat > BUILD.bazel << EOF
sh_binary(
 name = "test",
 srcs = ["test.sh"],
)
EOF
echo > WORKSPACE
```

Then run with/without direct_run:

```
> bazel run :test
[SNIP]
INFO: Running command line: bazel-bin/test
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
> bazel run --direct_run :test
[SNIP]
LANG=en_US.ISO-8859-1
LANGUAGE=en_US.ISO-8859-1
LC_CTYPE="en_US.ISO-8859-1"
LC_NUMERIC="en_US.ISO-8859-1"
LC_TIME="en_US.ISO-8859-1"
LC_COLLATE="en_US.ISO-8859-1"
LC_MONETARY="en_US.ISO-8859-1"
LC_MESSAGES="en_US.ISO-8859-1"
LC_PAPER="en_US.ISO-8859-1"
LC_NAME="en_US.ISO-8859-1"
LC_ADDRESS="en_US.ISO-8859-1"
LC_TELEPHONE="en_US.ISO-8859-1"
LC_MEASUREMENT="en_US.ISO-8859-1"
LC_IDENTIFICATION="en_US.ISO-8859-1"
LC_ALL=en_US.ISO-8859-1
```

### What operating system are you running Bazel on?

Similar to Debian Buster.

### What's the output of `bazel info release`?

release 0.13.0

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/1653 discusses how Bazel forces itself into latin-1. It appears that when direct_run is used, Bazel `exec()`s the binary without restoring the original environment.

**Comment by lberki** [comment]
This is fixed in d3d37f0c7da3eaf3277d0297cb93d81c161d8659 . It'll be in release 0.14 . Acausal bugfixing at its best -- we fix your bugs before you report them!
