### ISSUE TITLE
Vendoring bazel itself?

### ISSUE THREAD

**Issue by pspeter3** [bazelbuild/bazel#521]
Does it makes sense to vendor the bazel tool for consistent builds? If so, what is the best way to vendor it.

**Comment by hanwen** [comment]
The Bazel tool is a single binary; You can check it into your repo, and then run it from the repo.

**Comment by pspeter3** [comment]
@hanwen Sounds good though I would need to check in a version per environment theoretically?

**Comment by hanwen** [comment]
I guess so. You could have a wrapper scrpit that selects linux/osx based on uname.

**Comment by pspeter3** [comment]
I guess what I'm asking more is it possible for a workspace to specify a Bazel version or version range? Sorry for the confusion around the original question

**Comment by davidzchen** [comment]
Would it be a good idea to add a tutorial or some documentation on how to vendor Bazel? IIRC, there has been a couple of other email threads in the past on the mailing list asking about this as well.

**Comment by bsilver8192** [comment]
I think the idea proposed by #373 (create a wrapper script which downloads a fixed version from a fixed URL) is a good idea.

**Comment by AustinSchuh** [comment]
Is there a way to have the locally installed version of bazel (or maybe a wrapper shell script which is locally installed which runs the real bazel as a backup) look for this wrapper script?  That would make it so you can choose to vendor, but it isn't the only way to do it, and you can make the choice to vendor per repo and don't have to re-train users to use the checked in shell script.

**Comment by bsilver8192** [comment]
I wrote up something like what @AustinSchuh described and sent it for review as https://bazel-review.googlesource.com/2620. Comments/suggestions/etc welcome.
