### ISSUE TITLE
Docker sandbox leaves behind files owned by root

### ISSUE THREAD

**Issue by agoulti** [bazelbuild/bazel#5211]
### Description of the problem / feature request:

If a build is run with local docker sandbox and is interrupted or times out, sometimes root-owned files are left behind. This causes a subsequent run to fail since it's not able to override those files.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Set up any project with enough actions (e.g., protoc). Build it with local docker sandbox.
Wait until the analysis phase it over and some docker actions are running.
Hit Ctrl-C
More often than not there will be a message like this:

WARNING: Failed to delete sandbox base /usr/local/google/home/agoulti/.cache/bazel/_bazel_agoulti/c55e775ed7b462690a3444650658913e/sandbox: com.google.devtools.build.lib.unix.FilePermissionException: /usr/local/google/home/agoulti/.cache/bazel/_bazel_agoulti/c55e775ed7b462690a3444650658913e/sandbox/docker/10 (Operation not permitted)
WARNING: Failed to delete sandbox base /usr/local/google/home/agoulti/.cache/bazel/_bazel_agoulti/c55e775ed7b462690a3444650658913e/sandbox: com.google.devtools.build.lib.unix.FilePermissionException: /usr/local/google/home/agoulti/.cache/bazel/_bazel_agoulti/c55e775ed7b462690a3444650658913e/sandbox/docker/10 (Operation not permitted)

The subsequent run of the same build will fail:
Failed to initialize sandbox: /usr/local/google/home/agoulti/.cache/bazel/_bazel_agoulti/c55e775ed7b462690a3444650658913e/sandbox/docker/10 (Operation not permitted)

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

Any after introduction of local docker sandbox

### Any other information, logs, or outputs that you want to share?

I think this is due to a race condition when the mounted directories are removed from under "docker run". Before/while all docker runs are cleaned up, directories are removed

Here's a script that demonstrates how it works:

echo "before start:"  `ls -ld /tmp/try/nnn`
docker run -u 277174:89939 -v /tmp/try/nnn:/execroot/org_tensorflow gcr.io/cloud-marketplace/google/rbe-debian8@sha256:d84a7de5175a22505209f56b02f1da20ccec64880da09ee38eaef3670fbd2a56  sleep 3 &
echo "after start:"  `ls -ld /tmp/try/nnn`
sleep .5
rm -rf /tmp/try/nnn

echo "before sleep:"  `ls -ld /tmp/try/nnn`
sleep 3
echo "after sleep:"  `ls -ld /tmp/try/nnn`

Prints out:
before start: drwxr-x--- 2 agoulti primarygroup 4096 May 16 05:06 /tmp/try/nnn
after start: drwxr-x--- 2 agoulti primarygroup 4096 May 16 05:06 /tmp/try/nnn
ls: cannot access '/tmp/try/nnn': No such file or directory
before sleep:
after sleep: drwxr-xr-x 2 root root 4096 May 16 05:06 /tmp/try/nnn

**Comment by agoulti** [comment]
Probably related: https://github.com/moby/moby/pull/35833

**Comment by philwo** [comment]
@dslomov Please don't assign issues to me during my leave.

**Comment by philwo** [comment]
@agoulti Thanks so much for investigating this! I noticed & looked into it, but couldn't figure out where these root-owned files come from.

I'm assigning this to you for now. Please reach out to @buchgr if you need any help from the Bazel side or a code review or unassign if you don't have the time to look into this yourself. :)

**Comment by iphydf** [comment]
What's the best way to set up the docker image to avoid this?

**Comment by agoulti** [comment]
This has nothing to do with Docker Image, but with the way Bazel sets up the image.
Bazel would need to use "--mount" instead of "-v" options when setting up the image.
(here I think https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/sandbox/DockerCommandLineBuilder.java#L146)

Also, Docker version needs to be after and not including 18.06 because of  https://github.com/moby/moby/issues/37083

**Comment by mbeards** [comment]
Has anyone done any further investigation into this issue?

**Comment by ensonic** [comment]
According to
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/sandbox/DockerSandboxedSpawnRunner.java#L260
the docker image should receive the UID/GID, so the files should not be root owned.

The default sandbox image should be this one (based on distroless?), right?
https://github.com/GoogleCloudPlatform/container-definitions/tree/master/ubuntu1604_rbe
That should not contain anything preventing the uid/gid mapping.
