### ISSUE TITLE
//examples/android/java/bazel:jni doesn't build

### ISSUE THREAD

**Issue by sayrer** [bazelbuild/bazel#5212]
### Description of the problem / feature request:

Trying to build //examples/android/java/bazel:jni fails with `examples/android/java/bazel/jni.cc:1:10: fatal error: 'jni.h' file not found`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Adding the needed lines to WORKSPACE and trying to build.

### What operating system are you running Bazel on?

`macOS 10.13.4`

### What's the output of `bazel info release`?

`release 0.13.0-homebrew`

### Any other information, logs, or outputs that you want to share?

WORKSPACE Android stuff:

```
android_sdk_repository(
    name = "androidsdk",
    path = "/Users/sayrer/Library/Android/sdk",
    api_level = 26,
)

android_ndk_repository(
    name = "androidndk",
    path = "/Users/sayrer/android/android-ndk-r16b",
    api_level = 26,
)
```

```
Roberts-MacBook-Pro:bazel sayrer$ ls -l /Users/sayrer/Library/Android/sdk
total 0
drwxr-xr-x   4 sayrer  staff  128 May 13 10:38 build-tools
drwxr-xr-x   3 sayrer  staff   96 May 12 15:09 docs
drwxr-xr-x  17 sayrer  staff  544 May 12 14:12 emulator
drwxr-xr-x   6 sayrer  staff  192 May 12 15:09 extras
drwxr-xr-x   5 sayrer  staff  160 May 13 14:28 licenses
drwxr-xr-x   3 sayrer  staff   96 May 12 15:22 lldb
drwxr-xr-x   2 sayrer  staff   64 May 16 12:17 ndk-bundle
drwxr-xr-x   3 sayrer  staff   96 May 12 14:06 patcher
drwxr-xr-x  19 sayrer  staff  608 May 12 14:23 platform-tools
drwxr-xr-x   4 sayrer  staff  128 May 13 12:29 platforms
drwxr-xr-x  24 sayrer  staff  768 May 13 14:05 skins
drwxr-xr-x   4 sayrer  staff  128 May 13 12:27 sources
drwxr-xr-x   4 sayrer  staff  128 May 13 14:16 system-images
drwxr-xr-x  14 sayrer  staff  448 May 12 14:06 tools
Roberts-MacBook-Pro:bazel sayrer$ ls -l /Users/sayrer/android/android-ndk-r16b
total 72
-rw-r--r--@  1 sayrer  staff  4210 Dec  1 15:57 CHANGELOG.md
-rw-r--r--@  1 sayrer  staff   730 Dec  1 15:57 README.md
drwxr-xr-x@ 20 sayrer  staff   640 Dec  1 16:04 build
drwxr-xr-x@  3 sayrer  staff    96 Dec  1 15:57 meta
-rwxr-xr-x@  1 sayrer  staff    72 Dec  1 16:04 ndk-build
-rwxr-xr-x@  1 sayrer  staff    95 Dec  1 16:04 ndk-depends
-rwxr-xr-x@  1 sayrer  staff    91 Dec  1 16:04 ndk-gdb
-rwxr-xr-x@  1 sayrer  staff    93 Dec  1 16:04 ndk-stack
-rwxr-xr-x@  1 sayrer  staff    93 Dec  1 16:04 ndk-which
drwxr-xr-x@ 16 sayrer  staff   512 Dec  1 16:05 platforms
drwxr-xr-x@  9 sayrer  staff   288 Dec  1 16:04 prebuilt
drwxr-xr-x@  8 sayrer  staff   256 Dec  1 15:57 python-packages
drwxr-xr-x@  3 sayrer  staff    96 Dec  1 16:04 shader-tools
drwxr-xr-x@ 20 sayrer  staff   640 Dec  1 15:59 simpleperf
-rw-r--r--@  1 sayrer  staff    51 Dec  1 16:04 source.properties
drwxr-xr-x@  5 sayrer  staff   160 Dec  1 16:04 sources
drwxr-xr-x@  5 sayrer  staff   160 Dec  1 15:59 sysroot
drwxr-xr-x@ 10 sayrer  staff   320 Dec  1 16:05 toolchains
```

**Comment by ahumesky** [comment]
@benjaminp `--crosstool_top //external:android/crosstool` will work, but note that that works because of a `bind` hardcoded in the native implementation of the `android_ndk_repository` workspace rule. We'll probably get rid of that bind eventually. (long term, we'll be reimplementing `android_ndk_repository` in skylark, where we won't be able to do such a bind)

**Comment by benjaminp** [comment]
I see, but presumably there still have to be some magical target for the "current android crosstool"?

**Comment by ahumesky** [comment]
Yeah, today we have `@androidndk//:default_crosstool`. We'll need to work through the details (e.g., today you can replace the bind in your workspace file, but `@androidndk//:default_crosstool` is an alias that's generated by `android_sdk_repository` which can't be redirected like the bind. You'd have to use flags.)

**Comment by sayrer** [comment]
`If you don't build the app, you have to pass --crosstool_top //external:android/crosstool`

This fixed my problem, thanks!

**Comment by jin** [comment]
`@androidndk//:default_crosstool` is just the bind target of `//external:android/crosstool`. It was originally `@androidndk//:toolchain-gnu-libstdcpp`, but we added the `:default_crosstool` indirection to support the switch to `libc++` as the default STL in NDK 17.
