### ISSUE TITLE
android_binary allows building of apks with invalid package name

### ISSUE THREAD

**Issue by quittle** [bazelbuild/bazel#5213]
### Description of the problem / feature request:

`android_binary` will produce invalid APKs if the `AndroidManifest.xml` has an invalid package name, such as just `.` when it should fail the build.

Please save me from myself and fail the build (as is what happens with Android Gradle builds) and do not allow builds that result in invalid APKs

#### `WORKSPACE`
Given a reasonable one with a `android_sdk_repository` rule.

#### `BUILD`
```python
android_binary(
    name = "minimal",
    custom_package = "minimal.package.name",
    manifest = "AndroidManifest.xml",
)
```

#### `AndroidManifest.xml`
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package=".">
    <application />
</manifest>
```

Running `bazel build minimal` succeeds but the APK will not install because Package Manager rejects it with `There was a problem parsing the package`

If I provide a valid package name in the manifest, it builds and installs just fine.

### What operating system are you running Bazel on?

`Linux 4.9.80-c9 #1 SMP Wed Feb 7 08:47:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

### What's the output of `bazel info release`?

0.13.0

###  Have you found anything relevant by searching the web?

No

**Comment by jin** [comment]
@ahumesky this is another use case of your validation actions proposal.
