### ISSUE TITLE
Parallelise downloads in remote execution

### ISSUE THREAD

**Issue by agoulti** [bazelbuild/bazel#5215]
Currently remote execution downloads outputs serially. For actions with large numbers of outputs, this increases the latency significantly.

Downloads need to be parallelised.

**Comment by buchgr** [comment]
@agoulti can you also implement this for the `SimpleBlobStore`? Ideally moving both caches to the same interface.

**Comment by agoulti** [comment]
As discussed offline: there are some updates that need to happen to the Remote Cache interface, but it's not directly related to this change.
