### ISSUE TITLE
golang rules only work inside the bazel repo

### ISSUE THREAD

**Issue by benley** [bazelbuild/bazel#522]
tools/build_rules/go/toolchain/BUILD has several references to config_setting rules from //src, which is not a part of the default base_workspace.  This seems to mean that it's not possible to use these rules from a workspace other than the Bazel source workspace itself.

https://bazel-review.googlesource.com/2190 is my attempt at fixing it.

(major thanks to @haxorz for helping me figure this out!)

**Comment by kchodorow** [comment]
Thank you for the patch!  It's been merged in as https://github.com/bazelbuild/bazel/commit/9b96872ec9ac1a548399a4e657a6cc85805d55fb.
