### ISSUE TITLE
Support custom make variables

### ISSUE THREAD

**Issue by mboes** [bazelbuild/bazel#5223]
### Description of the feature request:

Say I define a script that has a runtime dependency on the Java compiler. I would write a rule similar to this:

```python
sh_binary(
  name = "foo",
  srcs = ["""
  ...
  $(JAVA) ...
  ...
  """],
)
```

Now, imagine I want to write a similar script that wants to call a binary in the Go, Rust or Haskell toolchains. How do i write such as `sh_binary` rule? Ideally, I'd use a make variable substitution for the compiler, just like for Java.

### Feature requests: what underlying problem are you trying to solve with this feature?

The problem is that there is no easy way to get at the path of a toolchain binary from within an `sh_binary` or `genrule` definition. In general compilers are part of toolchains, so I can't just add a `deps = ["//path/to/compiler"]` to the `sh_binary` rule above and use runfile lookup, because the label for say the compiler in the toolchain is unknown before toolchain resolution. So I wouldn't know what to put in `deps` nor by what name I should do a lookup in the runfiles.

### What's the output of `bazel info release`?

v0.13.0

###  Have you found anything relevant by searching the web?

None found in GitHub issue tracker.

**Comment by katre** [comment]
This is an interesting idea. One option we can look into is allowing toolchain providers to also provide make variables (so you could declare a toolchain type on the genrule and have that work). Something similar is actually being added for C++ currently, but we hadn't envisioned adding similar functionality in general yet.

The other option would be to write your own custom rule that requires the Go toolchain, and use that to generate actions. It's not as simple as a genrule, but it would actually be more portable across different platforms.

I'm going to add this to the toolchains category but I'm not sure it's a feature we'll be able to add soon. Would writing your own rule handle your use case?

**Comment by katre** [comment]
Thanks for the update. I'll comment back here if we end up doing anything related to this for Skylark rules.

**Comment by katre** [comment]
Work on this is happening, I have a plan to allow toolchains to expose a [TemplateVariableInfo](https://docs.bazel.build/versions/master/skylark/lib/platform_common.html#TemplateVariableInfo) provider, and have that get picked up and exposed in the rule context for variable expansion. Expect some work in a few weeks (there are other changes blocking the way, first).

**Comment by mboes** [comment]
Excellent news. Thanks!

**Comment by mboes** [comment]
The new `TemplateVariableInfo` stuff looks very promising, but how do I use it for the use case exposed in the original description of this ticket? To recap, what I want is the following:

```
sh_binary(
  name = "bar",
  srcs = ["bar.sh"],
  args = ["$(FOO)"],
  toolchains = ["//path/to:foo_toolchain_type"],
)
```

To make this work, I would need `$(FOO)` to return the absolute path to the Foo compiler. How do I do this, e.g. if the Foo compiler is actually some `cc_binary` built with Bazel?

**Comment by katre** [comment]
To answer your question: you need to define a rule that can define the FOO Make variable, possibly like this:

```
def _impl(ctx):
    path = ctx.attr.path
    return [platform_common.TemplateVariableInfo({'FOO': path})]

foo_supplier = rule(
    implementation = _impl,
    attrs = {
        'path': attr.string(),
    })
```

Then you can do this:
```
foo_supplier(
    name = 'my_foo',
    path = '/path/to/foo')

sh_binary(
    name = 'bar',
    srcs = ['bar.sh'],
    args = ["$(FOO)"],
    toolchains = [':my_foo'],
)
```

You can change the implementation of foo_supplier to take a label and export the path, to take a list of labels and compute a path string somehow, etc etc.

However, if all you really want is to know where a cc_binary is, I recommend not using TemplateVariableInfo at all:
```
cc_binary(
  name = 'foo',
  srcs = ['foo.cc'],
)

sh_test(
  name = 'bar',
  srcs = ['bar.sh'],
  data = [':foo'],
  args = ['$location :foo)'],
)
```

The test will have the relative path to foo passed in (in my test, it gets ./foo, since they are in the same directory). This saves all the deal with writing a custom rule and using TemplateVariableInfo, especially since in your use case you still need an actual dependency on foo, if you want it to be available as an input to your test.
