### ISSUE TITLE
dev-util/bazel: does not respect -j1 for make

### ISSUE THREAD

**Issue by toralf** [bazelbuild/bazel#5225]
which yields into using all cores of a multi-core system even if just 1 core should be used
origin report : https://bugs.gentoo.org/652776

Any chance to use EXTRA_BAZEL_ARGS  for that goal ?

**Comment by benjaminp** [comment]
What is this a bug report for exactly? It seems like the fix is completely upstream to Gentoo's ebuilds?

**Comment by katre** [comment]
Please clarify the following points:

1. What is the problem you are seeing with Bazel? I'm not sure why users would expect Bazel to use Make's environment variables for configuration.
2. What resolution would you like to see?

**Comment by toralf** [comment]
right, bazel doesn't use make.
