### ISSUE TITLE
android_binary rules not compiling due to missing aapt and apkbuilder files

### ISSUE THREAD

**Issue by XperielIndigo** [bazelbuild/bazel#523]
Hi everyone,

I've been building android_binaries for a few months now, however, to make it work I've always had to modify my dev environment to use hard coded paths for accessing the `aapt` and `apkbuilder` tools.

See #392 for the fix I use.

In the last comment of that issue I ask whether there is a cleaner way to do this that can be incorporated into bazel directly (instead of me patching my clone).

Has there been any progress on this issue? Or can someone tell me how to get bazel head to compile android_binaries appropriately (i.e. without the missing file errors)?

Cheers
Indigo

**Comment by damienmg** [comment]
@ahumesky @lberki: this bug was unanswered for 26 days...

**Comment by ahumesky** [comment]
So is the error still that the path looks like
```/private/var/tmp/_bazel_root/373fe016a982fda7060b14fd6dde0bd1/Master/bazel-out/local_darwin-fastbuild/bin/external/androidsdk/aapt_binary.runfiles//private/var/tmp/_bazel_root/373fe016a982fda7060b14fd6dde0bd1/Master/bazel-out/local_darwin-fastbuild/bin/external/androidsdk/build-tools/21.1.2/aapt```, i.e. there is an absolute path in there ("aapt_binary.runfiles//private....")?

Lets see what that little generated script is doing. Could you revert your changes to android_sdk_repository_template.txt, and then add the x option to bash here:

https://github.com/bazelbuild/bazel/blob/3d8469522d4b356feb2fc85e65314abb74d47d91/src/main/java/com/google/devtools/build/lib/bazel/rules/android/android_sdk_repository_template.txt#L136

so that it's "#!/bin/bash -eux", then paste the output here? You should see some output like
```
INFO: From Processing resources:
Error: + BINARY=external/androidsdk/aapt_binary
Error: ++ dirname external/androidsdk/aapt_binary
Error: + DIRNAME=external/androidsdk
```

It seems like `dirname` might be doing something unexpected, or perhaps it's different somehow on mac than on linux.

**Comment by XperielIndigo** [comment]
Any update?

**Comment by lberki** [comment]
Hm, this is kind of odd. Now that I look at this output:

https://gist.github.com/XperielIndigo/a564fb57fdaa4093e67a

aapt apparently gets executed in the target configuration as opposed to the host one. The line:

`/private/var/tmp/_bazel_root/eeba38b9814c9e09ce33cdb3fd7c34f8/Master/bazel-out/local_darwin-fastbuild/bin/external/androidsdk/aapt_binary.runfiles//private/var/tmp/_bazel_root/eeba38b9814c9e09ce33cdb3fd7c34f8/Master/bazel-out/local_darwin-fastbuild/bin/external/androidsdk/build-tools/21.1.2/aapt`

indicates that the shell suffix removal command `BINARY=${0##*-out/host/bin/}` didn't work and thus you ended up with an absolute path containing `local_darwin-fastbuild/bin` (`host/bin` would have been stripped out) here.

Sure I can fix this by changing that shell substitution command a little, but I wonder how that's possible. @gregestren , any clever ideas? The `android_sdk` rule depends on `aapt` in the host configuration as it should:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/android/AndroidRuleClasses.java#L325

@XperielIndigo , could you tell us how to reproduce this thing? I'm not very smart, so please be explicit and clear :)

**Comment by lberki** [comment]
Okay, I sent out a change that I *think* fixes it. All you need to do is to replace 

```
"BINARY=$${0#*-out/*/bin/}",
```

with

```
"BINARY=$${0#*-out/*/bin/}",
```

in `android_sdk_repository_template.txt`, but I'd like to figure out first why this is happening. aapt should never be in the target configuration...
