### ISSUE TITLE
Grpc downloadBlob global timeout exhaustion

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#5231]
### Description of the problem / feature request:

When running with large numbers of concurrent workers, the GrpcActionCache's downloadBlob method uses a local timeout through exhaustion of a global resource (the NIC).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`./rops build --remote_cache=host -j1000 //...:all` for 1000+ splay action graph with large enough average outputs in bytes (avgO) and small enough NIC baud (B) that (avgO * 1000 * 8) > B * 60.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

0.13.0

###  Have you found anything relevant by searching the web?

Grpc uses a single timeout for an entire request/response pair, which means that no amount of chunking will improve this situation - once you cross the above threshold of concurrent work (and latency factors in a great deal too, but a little harder to put into the formula).

### Any other information, logs, or outputs that you want to share?

I've submitted #5230 as a possible solution to this.

**Comment by ishikhman** [comment]
@werkt this seems to have been fixed a while ago, right?

**Comment by werkt** [comment]
Yes, by #5230 acceptance. Closing

**Comment by ishikhman** [comment]
Thanks, @werkt !
