### ISSUE TITLE
List of Bazel shell tests that fail on RBE

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#5234]
I have enabled `//src/test/shell/bazel/...` on our [Remote Execution pipeline](https://buildkite.com/bazel/remote-execution/) using the latest bazel-toolchain release: https://github.com/bazelbuild/bazel-toolchains/releases 

The following tests don't work, because of some tools not being installed in the docker container:

`//src/test/shell/bazel/android/...`
Not running Android tests due to lack of an Android SDK.

`//src/test/shell:bazel/bazel_execute_testlog`
/usr/bin/less: No such file or directory

`//src/test/shell/bazel:bazel_repository_cache_test`
remote_helpers.sh: line 27: nc: command not found

`//src/test/shell/bazel:bazel_spawnstats_test`
ERROR: 'linux-sandbox' is an invalid value for linux-sandbox spawn strategy. Valid values are: local, processwrapper-sandbox, remote, sandboxed, standalone, worker

`//src/test/shell/bazel:external_integration_test`
Failed to fetch Maven dependency: Could not transfer artifact com.example.carnivore:carnivore:jar:1.23 from/to endangered (http://127.0.0.1:36142/): Connection refused (Connection refused) and referenced by '//external:mongoose'

nc: command not found

`//src/test/shell/bazel:external_patching_test`
bash: patch: command not found

`//src/test/shell/bazel:maven_test`
nc: command not found

`//src/test/shell/integration:java_integration_test`
/b/s/w/ir/run/bazel-out/k8-fastbuild/bin/src/test/shell/integration/java_integration_test.runfiles/io_bazel/usr/lib/jvm/java-8-openjdk-amd64/bin/java: No such file or directory

`//third_party/ijar/...`
java.io.IOError: java.io.FileNotFoundException: Can't find langtools jar: /b/s/w/ir/run/bazel-out/k8-fastbuild/bin/third_party/ijar/test/IjarTests.runfiles/run/third_party/java/jdk/langtools/javac-9+181-r4173-1.jar

**Comment by dslomov** [comment]
Please do not assign issues to more than one team.
