### ISSUE TITLE
More than one JVM process running after `bazel build` finishes, hogging excessive memory.

### ISSUE THREAD

**Issue by rongjiecomputer** [bazelbuild/bazel#5245]
### Description of the problem

More than one JVM process running after `bazel build` finishes, hogging excessive memory.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
git clone --depth=1 https://github.com/bazelbuild/bazel
cd bazel
bazel build -c opt //src:bazel.exe
```

After build finishes, open Windows Task Manager. 

![capture](https://user-images.githubusercontent.com/13115060/40430505-da74f176-5ed7-11e8-8540-6bf7a5d56b6f.PNG)

JVM info:

```
java-runtime: OpenJDK Runtime Environment (build 1.8.0_163-b01) by Azul Systems, Inc.
java-vm: OpenJDK 64-Bit Server VM (build 25.163-b01, mixed mode) by Azul Systems, Inc.
max-heap-size: 928MB
```

### What operating system are you running Bazel on?

Windows 10 x64 (1803)

### What's the output of `bazel info release`?

development version

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Right from master 9b964fcec25d29cef542e314cfffd223785063be.

**Comment by rongjiecomputer** [comment]
The memory occupied by each JVM process will decrease over time (maybe GC kicks in). Before I took the screenshot, it was more than 2GB, then decreases to 340MB **very slowly**, but the number of JVM processes does not decrease. 2GB memory hog slows down my computer very significantly.

I know at least one JVM process will be running to answer query faster, but I think having > 1 JVM process is a bug.

**Comment by katre** [comment]
I believe the extra processes are the java compilation workers, but I'm sending this to @lberki for confirmation.

**Comment by rongjiecomputer** [comment]
@katre That is possible. My computer has 4 logical processors. 1 server process + 4 compilations worker processes = 5.

**Comment by benjaminp** [comment]
If it is the javac workers, `--worker_quit_after_build` should make a difference.

**Comment by rongjiecomputer** [comment]
@benjaminp Thanks for the showing me the flag. Problem solved.

I still don't understand why the default is `--worker_quit_after_build=false` though. It seems only useful if you are running Bazel in a CI server.

Feel free to close this issue if this is work as intended.

**Comment by katre** [comment]
This is intended: during interactive development, keeping the workers hot improves build performance. Typical developer workflow is to call bazel many times during development, and keeping the compilation workers alive means not having to pay the process startup penalty each time.
