### ISSUE TITLE
Merge all coverage reports from a coverage invocation

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#5246]
Create a Bazel action that merges all intermediate reports from a single coverage invocation into `bazel_out/_coverage/_coverage_report.dat`.

**Comment by lberki** [comment]
Python/shell would mean that we require Python/shell for collecting coverage data, which is onerous e.g. for pure C++ or Windows builds. The goal was to minimize dependencies, and thus the choices were Java or C++.

**Comment by iirina** [comment]
> Do that mean that code coverage will stick to the LCOV format after all?

My plan is to make Cobertura XML the final coverage report. Until Bazel can do that there are some intermediate steps to take and they imply using LCOV for the time being. 

> I’m wondering as well, since you speak of merging LCOV files, what the strategy concerning filenames would be, because there is no clear guidance concerning that, and that’s a problem when writing rules for non-core languages.

In coverage mode the test runner sets in the test environment a variable `COVERAGE_DIR`. As long as it is under that directory, `LcovMerger` will be able to find all the `.dat` files and merge them. The final merged coverage report will probably be under `bazel-testlogs/_coverage/coverage.dat` or something similar.

> Currently, if I remember correctly, Java source files are given relative to the java folders, and cc files are within _objects directories, so right now to map to the actual source files one must do some transformation which depends on the language.

Why do you need the mapping from the source files to the coverage reports?

**Comment by hchauvin** [comment]
> My plan is to make Cobertura XML the final coverage report. Until Bazel can do that there are some intermediate steps to take and they imply using LCOV for the time being.

That's great, there are many more options to generate, e.g., HTML reports from Cobertura XML than from LCOV.

> In coverage mode the test runner sets in the test environment a variable COVERAGE_DIR. 

Sorry for that, my sentence implied I was talking about the location of the .dat files, but I'm actually interested in the filenames as specified in the LCOV files (on the "FN:" lines).

I need the mapping because, I might be wrong, but I am under the impression that the source file content is not included even in Cobertura XML, so if I want an external tool to get the XML or LCOV file and match the file/line number coverage info with the actual code, I need to locate the source files.  Should source file names be absolute, relative to the execroot, proceed from some kind of transformation? Or maybe I'm not following you concerning the solution you are proposing.

**Comment by iirina** [comment]
> That's great, there are many more options to generate, e.g., HTML reports from Cobertura XML than from LCOV.

I agree that there are more tools for Cobertura XML overall, but actually I struggled finding a HTML generator from Cobertura XML. The only one I found wasn't very pretty. Could you point me to some?

> Sorry for that, my sentence implied I was talking about the location of the .dat files, but I'm actually interested in the filenames as specified in the LCOV files (on the "FN:" lines).

Oh OK, that makes more sense. In theory, the source filenames (it's actually the "SF:" lines) in the lcov tracefile should be relative to the workspace root. ATM Bazel doesn't *always* do that (*sigh* because of poor handling of some cases).

>  the source file content is not included even in Cobertura XML

That's true, the source file content is not included neither in Cobertura nor in lcov.

**Comment by hchauvin** [comment]
I don’t have a silver bullet for cobertura either, I am just noticing that
1) genhtml performance can be problematic, 2) you already have plugins for
cobertura in IntelliJ and phabricator (interestingly, there seems to be
only a plugin for LCOV in vscode), and code coverage is probably best
consumed in an IDE.

In this context, having file names relative to the workspace makes sense,
and it probably implies following symlinks then. But what about generated
files? Should they be mapped to bazel-bin and bazel-genfiles, or bazel-out?
And the source files of external dependencies? I think a clear resolution
algorithm should be devised.
Le ven. 1 juin 2018 à 10:02, Irina Iancu <notifications@github.com> a
écrit :

**Comment by iirina** [comment]
> I don’t have a silver bullet for cobertura either, I am just noticing that
> 1) genhtml performance can be problematic, 2) you already have plugins for
> cobertura in IntelliJ and phabricator (interestingly, there seems to be
> only a plugin for LCOV in vscode), and code coverage is probably best
> consumed in an IDE.

True. It's also integrated with some CIs, which is a big plus.

> it probably implies following symlinks then

Yes. This doesn't work in bazel coverage ATM.

>  But what about generated files? Should they be mapped to bazel-bin and bazel-genfiles, or bazel-out?
> And the source files of external dependencies?

This is a good question. Is there a case where someone would need coverage for generated/external files? I don't think this is a good practice and they should be excluded from the report.

**Comment by iirina** [comment]
Yes, a solution that works with remote execution would be ideal. I don't have a plan for symlinks ATM, it's probably the next on my list after this issue is fixed.

**Comment by pauldraper** [comment]
> actually I struggled finding a HTML generator from Cobertura XML. The only one I found wasn't very pretty. Could you point me to some?

Yeah, many tools generate the HTML report at the same time as the XML.

[Jenkins Cobertura Plugin](https://github.com/jenkinsci/cobertura-plugin) is popular though that's pretty tied into Jenkins.

[ReportGenerator](https://github.com/danielpalme/ReportGenerator) uses a number of formats (Cobertura, JaCoCo, lcov) into HTML reports.
