### ISSUE TITLE
Incomplete 0.13.1 Release Artifacts

### ISSUE THREAD

**Issue by promiseofcake** [bazelbuild/bazel#5247]
The Bazel 0.13.1 release is missing some published artifacts.

I noticed the following:
- bazel_0.13.1-linux-x86_64.deb
- bazel-0.13.1-without-jdk-installer-darwin-x86_64.sh
- all without-jdk installers

**Comment by meteorcloudy** [comment]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bazel-discuss/fhv8yc219Xo/P4NqP9OaAAAJ

> I manually uploaded the missing debian package. See https://github.com/bazelbuild/bazel/releases/tag/0.13.1
And we plan not to release the without-jdk installers anymore. But you can still build a Bazel without bundled jdk simply by "bazel build //src:bazel"
See https://github.com/bazelbuild/continuous-integration/issues/269
