### ISSUE TITLE
Desugaring rxjava2 jar fails with TypeNotPresentException/ClassNotFoundException

### ISSUE THREAD

**Issue by eclipsed4utoo** [bazelbuild/bazel#5248]
### Description of the problem / feature request:

I am writing a Xamarin application that requires me to do a Binding Project for an Android native library. That library references the rxjava2 library. When I desugar, I get a build error from desugar-deploy that a class is not found. If I decompile the rxjava2 library in JD-GUI, the class is there. 

I originally created an issue with Xamarin to have them investigate. After their investigation of trying to desugar outside of any Xamarin tools, they were still running into the same issue. This leads us to believe that it's an issue in the desugar jar.

Please see this comment on my issue that was created with Xamarin.
https://github.com/xamarin/xamarin-android/issues/1639#issuecomment-389761814

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The github issue that I created with Xamarin contains all of my testing information and a sample Xamarin project that exhibits the issue. The comment from one of their engineers also contains the Terminal command he used outside of Xamarin's tools.

### What operating system are you running Bazel on?

Mac Sierra, 10.12.6

###  Have you found anything relevant by searching the web?

I've spent hours and hours trying to figure out this issue before going to Xamarin for help.

### Any other information, logs, or outputs that you want to share?

The github issue that I created with Xamarin contains all of my testing information and a sample Xamarin project that exhibits the issue. The comment from one of their engineers also contains the Terminal command he used outside of Xamarin's tools.

**Comment by jin** [comment]
+ @kevin1e100 

Kevin, could you help with triaging this issue? FWIW, I tried to build an `android_binary` depending on a maven_jar `@io_reactivex_rxjava2//jar` and verified that the Desugaring action executed successfully on it. This could be due to the integration implementation between Xamarin and Desugar.

**Comment by kevin1e100** [comment]
Typically issues like this have to do with incorrect/incomplete classpaths given to the tool.  It looks like desugar is invoked with a whole bunch of Jars to desugar at the same time (by repeating pairs of --input X --output Y flags).  To my recollection the tool will process each --input in isolation from the others, which may be the source of confusion here.  For instance, if Jar X given as --input X depends on another Jar Z given as --input Z to the tool, that won't work b/c Z is ignored when processing X (and vice versa).  Instead, Z needs to be given to the tool using the --classpath_entry flag when desugaring X, and the two Jars should be processed using two separate invocations of the tool.

**Comment by sgong-pdftron** [comment]
Any update on this issue? Or workaround?

**Comment by jin** [comment]
@sgong-pdftron did you run into this issue when using desugar with Bazel? Unfortunately we don't have the bandwidth to support desugar outside of Bazel.

**Comment by sgong-pdftron** [comment]
@jin this issue is resolved for me now with https://github.com/xamarin/xamarin-android/issues/1639#issuecomment-497381359. Thanks for following up! I am not using Bazel so might not be related to the original post.
