### ISSUE TITLE
maven_jar does not honor artifact attribute

### ISSUE THREAD

**Issue by carl-mastrangelo** [bazelbuild/bazel#5250]
### Description of the problem / feature request:

When updating dependencies, bazel doesn't notice when the artifact id changes.   For example:

```
def io_netty_resolver():
  native.maven_jar(
      name = "io_netty_netty_resolver",
      artifact = "io.netty:netty-resolver:4.1.22.Final",
      sha1 = "b5484d17a97cb57b07d2a1ac092c249e47234c17",
  )
```

When updating to a newer version, the sha1 hash should match the artifact id.   However, consider the following change:

```
def io_netty_resolver():
  native.maven_jar(
      name = "io_netty_netty_resolver",
      artifact = "io.netty:netty-resolver:4.1.25.Final",
      sha1 = "b5484d17a97cb57b07d2a1ac092c249e47234c17",
  )
```

Since there is already an artifact for b5484d1, bazel assumes it already exists.   This has two bad implications:

1.  It's overly cumbersome to update deps.   
2.  It's very easy to be misleading in the deps.

### Feature requests: what underlying problem are you trying to solve with this feature?

I think it would be good to hash the artifact id with the sha1 or sha256 code, so that differences in either will be noticed.  For example, currently the artifact is stored at:

`~/.cache/bazel/_bazel_notcarl/cache/repos/v1/content_addressable/sha1/b5484d17a97cb57b07d2a1ac092c249e47234c17/ `

If bazel used `sha256(artifactId + sha1)` as the location of the jar, it could detect changes in either.  The jar could still be stored at the original sha1 location, and a symlink from the artifactid+sha could point to it.

### What operating system are you running Bazel on?

Debian Testing

### What's the output of `bazel info release`?

release 0.13.1

**Comment by davido** [comment]
Duplicate: #5144.
