### ISSUE TITLE
Bazel on Windows: improve first-time experience

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#5254]
In the spirit of https://github.com/bazelbuild/bazel/issues/5208, I'd like to collect ideas to improve the experience of first-time Bazel on Windows users. Some ideas may be Windows-specific, some may cover all platforms. I believe the experience is bumpier than it could be.

I'm opening this bug with the intent of collecting these ideas -- mine and everyone else's -- and use it as a burn-down list of improvements. Please feel free to add your ideas. I'll keep updating the list as tasks are completed.

---

- [ ] Website, "Get Bazel" button: make it point directly to the binary.
- [x] Make it so that the user doesn't have to **rename the Bazel binary** to `bazel.exe`.
  - Done by using the .msi installer, see https://github.com/bazelbuild/continuous-integration/pull/745
- [x] Consider turning the downloadable file into an **installer**: that'd remove the need to rename the binary, to set up the `PATH` manually, and to install the VC runtime DLLs separately.
  - Done: https://github.com/bazelbuild/continuous-integration/pull/745
- [x] Website, somewhere near download link: say it's a command line tool, there's no installer. Or: turn Bazel into an installer.
  - Done: https://github.com/bazelbuild/continuous-integration/pull/745
- [x] Website, installation:
  - [x] clarify which **versions of MSYS Bazel needs**. (Any versions, and hopefully not needing for long.)
    - Obsolete: Bazel works with any version.
  - [x] clarify which **versions of VC redistributable DLLs** Bazel needs.
    - Done, link is on https://docs.bazel.build/versions/0.28.0/install-windows.html
  - [x] document **how to set the PATH**
    - Done, in https://docs.bazel.build/versions/0.28.0/install-windows.html#problem-bazel-does-not-find-bash-or-bashexe
- [ ] Workspace path may not contain space. Should be supported.
- [ ] Renaming the workspace fails because the Bazel server is running in it.
- [ ] No VC installed, but Bazel gives warnings (or status messages?) about VC discovery.
- [ ] Document {java,py}_binary outputs, the fact that they generate an `.exe` file
- [ ] java_binary:
  - [ ] Document that deploy jars are self-contained and can be executed with `java -jar foo_deploy.jar`
  - [ ] Do not hardcode the JVM's path into the `.exe` files
- [ ] Runfiles manifest:
  - [ ] Review contents of runfiles manifest for data-less java_binaries: probably doesn't need to contain  things like the JDK
  - [ ] The `$0.exe.runfiles` directory's presence with just a runfiles manifest is weird, not documented anywhere. Consider **removing this runfiles directory** and just keep the `$0.runfiles_manifest` file.

**Update(2018-07-03):**
- [ ] `BAZEL_VC` or `BAZEL_VS` still needs to be defined (at least on my GCP Windows VM -- maybe I'm not admin?). An installer could do this so the user doesn't have to.
- [ ] Cryptic error messages when a genrule/sh_* uses `zip`, Bazel uses Git Bash, but MSYS is first on the PATH. (Related bug: https://github.com/bazelbuild/bazel/issues/5265)
- [x] Bazel client is slow to extract the embedded binaries. (See https://github.com/bazelbuild/bazel/issues/5444)
  - Done in https://github.com/bazelbuild/bazel/pull/5600

**Comment by laszlocsomor** [comment]
**Update(2018-07-03):**
- `BAZEL_VC` or `BAZEL_VS` still needs to be defined (at least on my GCP Windows VM -- maybe I'm not admin?). An installer could do this so the user doesn't have to.
- Cryptic error messages when a genrule/sh_* uses `zip`, Bazel uses Git Bash, but MSYS is first on the PATH. (Related bug: https://github.com/bazelbuild/bazel/issues/5265)
- Bazel client is slow to extract the embedded binaries. (See https://github.com/bazelbuild/bazel/issues/5444)

**Comment by meteorcloudy** [comment]
If users don't define BAZEL_VC and BAZEL_VS, Bazel will detect VC installation on the machine, if not found a fake crosstool will be generated. So I guess they are not mandatory, are they?

**Comment by meteorcloudy** [comment]
Just tested on the VM with 0.15.0. If I build a `sh_binary`, it worked without setting `BAZEL_VC` or `BAZEL_VS`. If I build a cc_binary, it threw an error asking me to install VC. This is working as expected.
But in both case it gives some warning about setting `BAZEL_VC`, I guess that what we should improve?
```
pcloudy@laszlocsomor-windows-testing MSYS ~/workspace/test
$ vim BUILD

pcloudy@laszlocsomor-windows-testing MSYS ~/workspace/test
$ vim bin.sh

pcloudy@laszlocsomor-windows-testing MSYS ~/workspace/test
$ ./bazel-0.15.0-windows-x86_64.exe build :bin
Loading:
Loading: 0 packages loaded
DEBUG: C:/users/pcloudy/_bazel_pcloudy/hyl7dsma/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/pcloudy/_bazel_pcloudy/hyl7dsma/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/pcloudy/_bazel_pcloudy/hyl7dsma/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for Visual C++ through registry
INFO: Analysed target //:bin (4 packages loaded).
INFO: Found 1 target...
[0 / 5] [-----] Writing script bin.exe
Target //:bin up-to-date:
  C:/users/pcloudy/_bazel_pcloudy/hyl7dsma/execroot/__main__/bazel-out/x64_windows-fastbuild/bin/bin
  C:/users/pcloudy/_bazel_pcloudy/hyl7dsma/execroot/__main__/bazel-out/x64_windows-fastbuild/bin/bin.exe
INFO: Elapsed time: 1.109s, Critical Path: 0.03s
INFO: 0 processes.
INFO: Build completed successfully, 5 total actions
INFO: Build completed successfully, 5 total actions

pcloudy@laszlocsomor-windows-testing MSYS ~/workspace/test
$ ./bazel-bin/bin
hallo

pcloudy@laszlocsomor-windows-testing MSYS ~/workspace/test
$ vim BUILD

pcloudy@laszlocsomor-windows-testing MSYS ~/workspace/test
$ vim bin.cc

pcloudy@laszlocsomor-windows-testing MSYS ~/workspace/test
$ ./bazel-0.15.0-windows-x86_64.exe build :bin
Loading:
Loading: 0 packages loaded
DEBUG: C:/users/pcloudy/_bazel_pcloudy/hyl7dsma/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/pcloudy/_bazel_pcloudy/hyl7dsma/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/pcloudy/_bazel_pcloudy/hyl7dsma/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for Visual C++ through registry
INFO: Analysed target //:bin (3 packages loaded).
INFO: Found 1 target...
[0 / 4] [-----] BazelWorkspaceStatusAction stable-status.txt
ERROR: C:/msys64/home/pcloudy/workspace/test/BUILD:1:1: C++ compilation of rule '//:bin' failed (Exit -1)

The target you are compiling requires Visual C++ build tools.
Bazel couldn't find a valid Visual C++ build tools installation on your machine.
Please check your installation following https://docs.bazel.build/versions/master/windows.html#using

Target //:bin failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.637s, Critical Path: 0.07s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

```

**Comment by laszlocsomor** [comment]
> Just tested on the VM with 0.15.0. 

Thanks for looking into this!

> If I build a `sh_binary`, it worked without setting `BAZEL_VC` or `BAZEL_VS`.

For me too. That is WAI.

> If I build a cc_binary, it threw an error asking me to install VC. This is working as expected.

For me too, and this is my primary concern. Isn't the cc_toolchain supposed to discover where VC is installed?

> But in both case it gives some warning about setting `BAZEL_VC`, I guess that what we should improve?

That's an annoyance because it spams the output and the yellow-colored DEBUG messages look like warnings, but this is only my secondary concern.

**Comment by meteorcloudy** [comment]
Hmm, I see VS 2017 is installed on the VM, but the registry info is somehow missing. Normally, bazel should be able to detect that through registry by
`reg query HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS`
It worked on my workstation for VS 2017.

**Comment by laszlocsomor** [comment]
Could you update cc_configure to fall back on checking the default installation path if the registry key is missing?

**Comment by meteorcloudy** [comment]
That's good idea!

**Comment by darthbinamira** [comment]
Want to add one issue I've encountered while following the [java tutorial](https://docs.bazel.build/versions/master/tutorial/java.html).

1. The ```bazel query``` command seems to only work in PowerShell. I tried running with the default cmd.exe terminal in IntelliJ and it just gives the following error:
```
bazel query  --nohost_deps --noimplicit_deps 'deps(//:ProjectRunner)' --output graph
ERROR: The package part of 'deps(//:ProjectRunner)' should not end in a slash
```
2. The same query can't be copy-pasted due to the \ and should be written in a single line.

**Comment by malkia** [comment]
Need to verify this (I'm on my Chromebook right now), but I think under windows "bazel.exe" actually runs "java.exe" (as expected), but unlike Linux, the name still comes as "java" during "tasklist" or "pslist" (from Sys Internals). Probably all it takes to rename "java.exe" to "bazel.exe", and then it can be killed.

Again need to verify this next week, when I have windows machine again!

**Comment by laszlocsomor** [comment]
True, it's "java.exe" in Task Manager.

@philwo : WDYT of renaming the embedded JDK's java.exe to bazel-server.exe or something?

**Comment by philwo** [comment]
Quite a hack, but yeah, why not 😅 It would get confusing if we ever used the embedded JDK to run something other than the Bazel server, but I don't think that should happen anymore (@meisterT maybe knows?).

**Comment by dslomov** [comment]
I like this. "Java? Who is Java? I am Bazel Server!"

**Comment by meisterT** [comment]
We should not run anything else than Bazel itself on the embedded JDK anymore, so feel free to rename.

**Comment by laszlocsomor** [comment]
Thanks for the feedback!
Let's rename then. (And not symlink, because that's still not supported widely enough on Windows.)

**Comment by laszlocsomor** [comment]
Updated original message with status.

**Comment by laszlocsomor** [comment]
Rest of the stuff won't get done before 1.0, removing tag.

**Comment by ofek** [comment]
Any update?

**Comment by philwo** [comment]
@ofek Are you looking for something specific?

Recently, we've been doing some light improvements for Bazel's Windows port, but are not prioritizing it very highly, because we feel like it's currently working well enough for the known users. But if you have concrete issues that we should address, please let me know here and I'll make sure we look at them!

**Comment by ofek** [comment]
Nothing in particular, just curious if the checklist is current

**Comment by jinfagang** [comment]
Error in fail: BAZEL_SH environment variable is not set

I **cannot bare it anymore in 2023 on windows**

**Comment by ofek** [comment]
@bazelbuild/triage

**Comment by meteorcloudy** [comment]
I think most of the points in the original issues have been fixed or obsolete. Please file new issue for specific Windows bugs. Thanks!
