### ISSUE TITLE
Building bazel requires implicit zip/unzip dependencies in path

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#5259]
### Description of the problem / feature request:

Attempting to build bazel under remote execution fails when my execution host does not have zip/unzip available on the $PATH

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`bazel build --remote_executor=host-without-zip --spawn_strategy=remote src:package-zip`

Both the `package-zip` and `bazel-bin` targets exhibit this dependency

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

0.13.1

### Any other information, logs, or outputs that you want to share?

```
ERROR: /home/ggensure/dev/bazel/bazel/src/BUILD:254:2: Executing genrule //src:bazel-bin failed (Exit 127): bash failed: error executing command
  (cd /home/ggensure/.cache/bazel/_bazel_ggensure/99c0e149d55a35084bab7136021e80a9/execroot/io_bazel && \
  exec env - \
    PATH=/home/ggensure/bin:/home/ggensure/Applications/.bin:/usr/bin:/home/ggensure/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; rm -f bazel-out/k8-fastbuild/bin/src/bazel; cat bazel-out/k8-fastbuild/bin/src/main/cpp/client bazel-out/k8-fastbuild/genfiles/src/package.zip > bazel-out/k8-fastbuild/bin/src/bazel && zip -qA bazel-out/k8-fastbuild/bin/src/bazel')
/bin/bash: zip: command not found
Target //src:bazel failed to build
```

**Comment by katre** [comment]
@laszlocsomor Should zip/unzip be part of the shell toolchain?

**Comment by laszlocsomor** [comment]
@katre : yes, probably. But how exactly, I don't know yet, including bintools in the shell toolchain and how to express that a rule requires some bintools warrants its own design.

**Comment by katre** [comment]
Makes sense. Do you have a tracking issue for that so we can link this from it?

@werkt, I see the issue but I'm not sure this is something we can correct in the short term. I assume you can workaround this by ensuring that all workers have zip and unzip installed?

**Comment by laszlocsomor** [comment]
Just filed one: https://github.com/bazelbuild/bazel/issues/5265

**Comment by katre** [comment]
Closing this since no action has been taken in two years.
