### ISSUE TITLE
NativePosixFilesTest dependent on exec uid

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#5262]
### Description of the problem / feature request:

A number of tests in NativePosixFilesTest depend upon being executed without root permissions. No negative feedback is being given to the jvm to validate a number of tests which modify files and expect exceptions when the user executing the test is root.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`sudo bazel test //src/test/java/com/google/devtools/build/lib:unix_test`

### What operating system are you running Bazel on?

Ubuntu 14.04

### What's the output of `bazel info release`?

0.13.1

### Any other information, logs, or outputs that you want to share?

Yes, it's weird, but these test suites should either fail during setup under the precondition that the uid not be 0, or deescalate in some manner prior to running these tests.

**Comment by jmmv** [comment]
I can fix this, but why should we? I'm tempted to say "Don't do that" and leave it as is though.

Is this the only test that breaks when you run Bazel as root?
