### ISSUE TITLE
bazel-toolchains is failing with network errors in Bazel CI for 0.14.0rc4

### ISSUE THREAD

**Issue by lfpino** [bazelbuild/bazel#5267]
The docker steps in bazel-toolchains tests are failing entirely because of network issues in the Bazel CI workers.

Example: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/252#23a7c0c0-30c1-43e9-9916-63b2dc4633e7

**Comment by lfpino** [comment]
@buchgr please add more details if you have, thanks!

**Comment by buchgr** [comment]
Fixed by creating new images.
