### ISSUE TITLE
new_http_archive doesn't follow http redirects? 

### ISSUE THREAD

**Issue by zaphar** [bazelbuild/bazel#527]
If I put the following in a WORKSPACE file it fails with a checksum error. The reason appears to be that it is pulling down the html redirect page instead of following it. The url does a 302 redirect to a cdn for the download. This is likely to be the case for many different projects that offer http download.

Is the failure to follow redirects intended or is this a bug?

new_http_archive(
    name="nunit",
    build_file="tools/build_defs/dotnet/BUILD.nunit",
    sha256="1bd925514f31e7729ccde40a38a512c2accd86895f93465f3dfe6d0b593d7170",
    type="zip",
    url="http://github.com/nunit/nunitv2/releases/download/2.6.4/NUnit-2.6.4.zip"
)

**Comment by kchodorow** [comment]
It should be following redirects.  I'll take a look. (https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/repository/HttpDownloader.java#L155)

**Comment by zaphar** [comment]
Okay I had some more time to look into this and it looks like the problem is that the redirect goes from a http to an https url and the java api doesn't automatically follow that. Changing the url to an https url works.

Not really sure if this should be considered a bug or a feature now. But at the least it probably warrants some explanatory documentation or a FAQ entry.
