### ISSUE TITLE
bazel run fails on Windows if home contains a space

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#5273]
```
$ bazel run :SlowConversion
...
INFO: Running command line: 'C:/users/ulf adams/_bazel_ulf adams/b_oqmpux/execroot/__main__/bazel-out/x64_windows-fastbuild/bin/src/main/java/info/adams/ryu/analysis/SlowConversion.exe'
'C:\users\ulf' is not recognized as an internal or external command,
operable program or batch file.
ERROR: Non-zero return code '1' from command: Process exited with status 1
```

**Comment by ulfjack** [comment]
That's right. As a workaround, I can copy either the command line into a terminal (and add double quotes), or set --output_user_root.

**Comment by laszlocsomor** [comment]
I just noticed, this is fixed at HEAD (https://github.com/bazelbuild/bazel/commit/abf74a135750ca1e8b415632975c738a8edc4d01).

**Comment by ulfjack** [comment]
I thought this might have been fixed by @lberki's rollout of --direct_run?

**Comment by laszlocsomor** [comment]
Could be, yes. I didn't bisect to see what fixed it, just verified that it was fixed.
