### ISSUE TITLE
Please add execution time to `ActionExecuted` events in BEP

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel#5275]
### Description of the problem / feature request:
Please add a `google.protobuf.Duration`[0] to `ActionExecuted`, defined in `build_event_stream.proto`, that records how long the action took to execute.

[0] Or int64 milliseconds, if Duration is not yet supported in Bazel's protos.

### Feature requests: what underlying problem are you trying to solve with this feature?
I want to run Bazel with `--build_event_publish_all_actions` to profile large builds, determine which targets have the largest total execution time, and graph them in a human-meaningful way.

Currently I'm doing this by using `event.children[].action_completed` to detect actions being scheduled, `event.id.action_completed` to detect action completion, and manually correlating by label/type/output. This is cumbersome, and the output data is low quality.

### What's the output of `bazel info release`?

release 0.13.0

**Comment by jin** [comment]
I wrote a script to analyze the raw dump of `bazel analyze-profile`: [analyze-profile.py](https://gist.github.com/jin/857d7aaa83235f6633b13b07729ee97f) to achieve the same purposes.

**Comment by jxwufan** [comment]
Hi @dslomov @lberki,
Seems that this issue exists for one year. Do you plan to add this feature to BEP? Since our team needs this feature, we can try to implement it. However, since the feature requires modifying the Protobuf definition, will you accept a PR with such modification? Or we can discuss the plan first before implementing it.

Thanks.

**Comment by meisterT** [comment]
I suggest to look at the data in Bazel's JSON profile first (https://docs.bazel.build/versions/master/skylark/performance.html#json-profile).
I would rather not have that information in two places if we can avoid it.

**Comment by meisterT** [comment]
Closing in favor of the JSON profile
