### ISSUE TITLE
Provide mechanism to augment args of a *_binary rule

### ISSUE THREAD

**Issue by mboes** [bazelbuild/bazel#5277]
### Description of the feature request

Provide a built-in rule or augment existing rules with a mechanism for defining a new target that calls the given binary with the given arguments.

### Feature requests: what underlying problem are you trying to solve with this feature?

AFAICT there is currently no easy way to write a BUILD file rule that says something very simple:

"Call the given binary with the given set of arguments"

This can be emulated by writing a shell script that takes the binary to apply as the first argument and the arguments to pass to it as the rest of the arguments. We can reuse such a shell script for all binaries we want to invoke with a fixed set of arguments. Or a genrule that produces a script that itself will take the arguments to pass to the binary. Both of these approaches seem overkill for what is a very simple thing: capture as a target the invocation of a binary with a fixed set of arguments.

Say that some external repo I have the following target:

```
cc_binary(
  name = "foo",
  srcs = ["foo.cc"],
)
```

There is no `args` here so effectively it's the empty list, but now I'd like to define a new target that just calls this binary with some arguments. Effectively, I'd like to *post hoc* augment the arguments of `foo` with more arguments.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

v0.13

###  Have you found anything relevant by searching the web?

Oddly enough, there doesn't seem to be any related ticket in the issue tracker yet.

**Comment by jin** [comment]
@laurentlb classifying this under Skylark, please reassign/reclassify if it's incorrect. Thanks.

**Comment by laurentlb** [comment]
I don't think we need to add this to Bazel itself. You could write your own rule that does this. It can also be added to [Skylib](https://github.com/bazelbuild/bazel-skylib) as it's a very generic rule.

Two rules that are somewhat related:
- https://github.com/bazelbuild/bazel-skylib/blob/master/docs/native_binary_doc.md
- https://github.com/bazelbuild/bazel-skylib/blob/master/docs/run_binary_doc.md
