### ISSUE TITLE
can't compile tensorflow with installed protobuf-2.6.1.

### ISSUE THREAD

**Issue by muyue1238** [bazelbuild/bazel#5279]
I'm trying to compile with bazel-0.13.1 with my centos, and it went well. But when I use the libtensorflow_cc.so in my own program, it told me that the libtensorflow_cc.so was compiled with protobuf-3.5.0, yet I only have protobuf-2.6.1 installed in my computer. When I looked into the compiling detail, I found that in .cache/bazel/... there's some file that demands protobuf>=3.5.0. I'm guessing bazel downloaded and use protobuf-3.5.0 during the compiling. My problem was that my other .so files were compiled with protobuf-2.6.1, and it's done by someone else. So what can I do to force bazel to compile tensorflow with  protobuf-2.6.1? Or can I do something else to make the .so files compiled by different version of protobufs can work well? Much thanks. And here's the error reported when I ran my program:

`[libprotobuf FATAL external/protobuf_archive/src/google/protobuf/stubs/common.cc:79] This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.5.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/descriptor.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.5.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/descriptor.pb.cc".)
`

**Comment by jin** [comment]
Hi, we recommend asking questions about Bazel build errors on StackOverflow instead of GitHub Issues as mentioned in the issue template.

Please post your question here: https://stackoverflow.com/questions/tagged/bazel and also tag it with `tensorflow`.

**Comment by muyue1238** [comment]
thanks for your notification, will do.
