### ISSUE TITLE
Consider moving public protocols to separate repos

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#5281]
Right now, developers who want to integrate with Bazel by implementing the Worker API or by listening to the Build Event Protocol have to either depend on the Bazel repository with all its stuff, or copy the corresponding protocol buffers to their own repository.

We should consider moving the source of truth for these protos to separate git repos, and copy the files into Bazel. That would allow non-Bazel projects to depend on that repo without pulling in all of Bazel. (Bazel will have to copy the files in, though, for various reasons.)

**Comment by ulfjack** [comment]
Remote execution has been moved.

**Comment by jmmv** [comment]
This is a product issue and it affects more than one protocol, so reclassifying.
