### ISSUE TITLE
Windows: Case sensitivity issue of environment variables while creating processes with system API

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#5285]
Bazel builds environment variables map for creating Windows process by the following function:https://github.com/bazelbuild/bazel/blob/80442861d936a7dc4e832f95cf03e51af50ca3a5/src/main/java/com/google/devtools/build/lib/windows/WindowsSubprocessFactory.java#L120

Windows environment variable names are case-insensitive, this function didn't take this into consideration. Therefore it could pass the same environment variable with different cases to the Windows API. For example, `{"FOO": "bar1", "foo" : "bar2", "Foo": "bar3"}`. **Surprisingly, Windows will allow it!**
A simple reproduce with Bazel 0.13.0:
https://github.com/meteorcloudy/my_tests/blob/master/simple_repo_rule/repo.bzl#L3

```
pcloudy@tensorlow-jenkins-win2-slave MSYS ~/workspace/my_tests/simple_repo_rule
$ bazel-0.13.0 build @env_test//...
DEBUG: C:/tools/msys64/home/pcloudy/workspace/my_tests/simple_repo_rule/repo.bzl:3:3:
C:\users\pcloudy\_bazel_pcloudy\1e3v36rp\external\env_test>set FOO
FOO=awef
Foo=123
foo=a
INFO: Analysed 0 targets (0 packages loaded).
INFO: Found 0 targets...
INFO: Elapsed time: 0.185s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

This causes problems when we will try to set or clean environment variables before executing an action. For example, https://github.com/bazelbuild/bazel/blob/768f1818bea462a359f45034003f3b9756901116/tools/cpp/windows_cc_configure.bzl#L194-L195
If in user's environment, envs like `Path` or `WindowsSdkDir` are already set, this won't be able to clean the expected envs.

**Comment by laszlocsomor** [comment]
Facepalm. Nice analysis @meteorcloudy .
