### ISSUE TITLE
bazel.io/docs/build-encyclopedia.html broken

### ISSUE THREAD

**Issue by mikesamuel** [bazelbuild/bazel#529]
Browsing to http://bazel.io/docs/build-encyclopedia.html#common.visibility yields

```
404 - Page not found
$ bazel build :what-you-were-looking-for
...............
ERROR: no such page ':what-you-were-looking-for': BUILD file not found on package path.
INFO: Elapsed time: 0.567s
```

Dev console shows:

Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by kchodorow** [comment]
We just reorganized the build encyclopedia to break it up into multiple pages.  Visibility is now under http://bazel.io/docs/be/common-definitions.html#common.visibility.  Is there somewhere that links to http://bazel.io/docs/build-encyclopedia.html#common.visibility that we should update?

**Comment by mickeyreiss** [comment]
I noticed that there's a broken link in the [README](https://github.com/bazelbuild/bazel/blame/bb23793da2ff3a0ea5a1ffb8444a626af15162c7/README.md#L31).

In the future, it would be great if HTTP redirects were installed to avoid completely breaking links to docs.

**Comment by philwo** [comment]
FYI there are also broken links in our build encyclopedia, see for example:
http://bazel.io/docs/be/common-definitions.html#common.tags

"Consult the Bazel documentation for details." links to http://bazel.io/docs/be/bazel-user-manual.html#tags_keywords which gives a 404.

**Comment by davidzchen** [comment]
I have a patch in review that fixes all the links. It should be out in the next day or so.
