### ISSUE TITLE
Restarts during Skyframe function evaluation are surprising and costly

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/bazel#5294]
In https://github.com/bazelbuild/bazel/issues/5196, we tracked down a problem in which `xcode-locator-bin` was being built and executed during C++ auto-configuration about 15 times. This, in turn, caused slowdowns during analysis and also tickled a strange kernel bug in Santa that corrupted on-disk state. All of this was very surprising because the Skylark code had no connection to the restarts, so it was hard to explain why the same code was run multiple times.

However, it turns out that this behavior was "expected". Repository functions can restart half-way thorough when they need to, for example, resolve a label. The auto-configuration code was tripping over this because the Skylark repository function had label resolution all over the place, and in particular, it had such calls *after* it had built and executed a host auto-detection tool.

I'm filing this bug to track this general problem, but we should do several things:

* Document this behavior in the relevant Skylark APIs, and somewhere holistically, to warn users about this surprising behavior.

* Add logging to the repository functions to track restarts, or provide some other mechanism for users to understand what's happening. As things are now, the way this problem manifests is by "stuckness" during analysis.

* According to @janakdr, the correct solution to fix this would be to support in-thread Skyframe evaluation so that resolving labels didn't cause restarts. @ulfjack proposes that, instead, we should have a coroutine-based execution model because even label resolution can be arbitrarily costly.

**Comment by fmeum** [comment]
Duplicates https://github.com/bazelbuild/bazel/issues/10515, which is fixed at HEAD (behind a flag).

**Comment by Wyverald** [comment]
clsoing as a dupe (#10515)
