### ISSUE TITLE
 template argument deduction/substition failed error

### ISSUE THREAD

**Issue by cyberjoseph** [bazelbuild/bazel#5297]
Just tried compiling bazel on my box, newest version of Linux Mint, everything updated and installed all dependencies.

`mtke@tomato ~/tf/bazel2 $ bash ./compile.sh 
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
INFO: Analysed target //src:bazel (198 packages loaded).
INFO: Found 1 target...
ERROR: /home/mtke/tf/bazel2/third_party/ijar/BUILD:10:1: C++ compilation of rule '//third_party/ijar:zip' failed (Exit 1): gcc failed: error executing command 
  (cd /tmp/bazel_UkipP8NO/out/execroot/io_bazel && \
  exec env - \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/piii-opt/bin/third_party/ijar/_objs/zip/third_party/ijar/mapped_file_unix.d '-frandom-seed=bazel-out/piii-opt/bin/third_party/ijar/_objs/zip/third_party/ijar/mapped_file_unix.o' -DBLAZE_OPENSOURCE -iquote . -iquote bazel-out/piii-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/piii-opt/genfiles/external/bazel_tools -isystem third_party/zlib -isystem bazel-out/piii-opt/genfiles/third_party/zlib -isystem bazel-out/piii-opt/bin/third_party/zlib -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c third_party/ijar/mapped_file_unix.cc -o bazel-out/piii-opt/bin/third_party/ijar/_objs/zip/third_party/ijar/mapped_file_unix.o)
third_party/ijar/mapped_file_unix.cc: In constructor 'devtools_ijar::MappedOutputFile::MappedOutputFile(const char*, size_t)':
third_party/ijar/mapped_file_unix.cc:114:67: error: no matching function for call to 'min(long unsigned int, unsigned int)'
                                 std::numeric_limits<size_t>::max());
                                                                   ^
In file included from /usr/include/c++/5/algorithm:61:0,
                 from third_party/ijar/mapped_file_unix.cc:21:
/usr/include/c++/5/bits/stl_algobase.h:195:5: note: candidate: template<class _Tp> const _Tp& std::min(const _Tp&, const _Tp&)
     min(const _Tp& __a, const _Tp& __b)
     ^
/usr/include/c++/5/bits/stl_algobase.h:195:5: note:   template argument deduction/substitution failed:
third_party/ijar/mapped_file_unix.cc:114:67: note:   deduced conflicting types for parameter 'const _Tp' ('long unsigned int' and 'unsigned int')
                                 std::numeric_limits<size_t>::max());
                                                                   ^
In file included from /usr/include/c++/5/algorithm:61:0,
                 from third_party/ijar/mapped_file_unix.cc:21:
/usr/include/c++/5/bits/stl_algobase.h:243:5: note: candidate: template<class _Tp, class _Compare> const _Tp& std::min(const _Tp&, const _Tp&, _Compare)
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^
/usr/include/c++/5/bits/stl_algobase.h:243:5: note:   template argument deduction/substitution failed:
third_party/ijar/mapped_file_unix.cc:114:67: note:   deduced conflicting types for parameter 'const _Tp' ('long unsigned int' and 'unsigned int')
                                 std::numeric_limits<size_t>::max());
                                                                   ^
In file included from /usr/include/c++/5/algorithm:62:0,
                 from third_party/ijar/mapped_file_unix.cc:21:
/usr/include/c++/5/bits/stl_algo.h:3445:5: note: candidate: template<class _Tp> _Tp std::min(std::initializer_list<_Tp>)
     min(initializer_list<_Tp> __l)
     ^
/usr/include/c++/5/bits/stl_algo.h:3445:5: note:   template argument deduction/substitution failed:
third_party/ijar/mapped_file_unix.cc:114:67: note:   mismatched types 'std::initializer_list<_Tp>' and 'long unsigned int'
                                 std::numeric_limits<size_t>::max());
                                                                   ^
In file included from /usr/include/c++/5/algorithm:62:0,
                 from third_party/ijar/mapped_file_unix.cc:21:
/usr/include/c++/5/bits/stl_algo.h:3451:5: note: candidate: template<class _Tp, class _Compare> _Tp std::min(std::initializer_list<_Tp>, _Compare)
     min(initializer_list<_Tp> __l, _Compare __comp)
     ^
/usr/include/c++/5/bits/stl_algo.h:3451:5: note:   template argument deduction/substitution failed:
third_party/ijar/mapped_file_unix.cc:114:67: note:   mismatched types 'std::initializer_list<_Tp>' and 'long unsigned int'
                                 std::numeric_limits<size_t>::max());
                                                                   ^
Target //src:bazel failed to build
INFO: Elapsed time: 176.892s, Critical Path: 19.07s
INFO: 266 processes, local.
FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel`

**Comment by jin** [comment]
Hi, we recommend asking questions about Bazel build errors on StackOverflow instead of GitHub Issues as mentioned in the issue template.

Please post your question here: https://stackoverflow.com/questions/tagged/bazel and tag it with "[bazel]".
