### ISSUE TITLE
Support generating IntelliJ project files

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel#53]
Similar to #12, having IntelliJ support would be awesome as well.

This would also depend on #31.

**Comment by spierce7** [comment]
:+1:

**Comment by hanwen** [comment]
here is a script that generates a library XML for external dependencies https://gist.github.com/hanwen/2df3b3f0964ee00f9062f4f1c112d4a9

**Comment by dslomov** [comment]
ij.bazel.build is it.
