### ISSUE TITLE
bazel query broken by maven java_import

### ISSUE THREAD

**Issue by ekuefler** [bazelbuild/bazel#530]
After updating Bazel I can no longer run most queries. I get errors like the following:

```
# bazel query ...
ERROR: /workspace/tmp/bazel-tmp/_bin/BUILD:264:1: //bazel-tmp/_bin:maven: non empty attribute 'jars' in 'java_import' rule '//bazel-tmp/_bin:maven' has to have at least one value.
ERROR: package contains errors: bazel-tmp/_bin.
ERROR: no such package 'bazel-tmp/_bin': Package 'bazel-tmp/_bin' contains errors.
```

This isn't a target I've defined, it looks like something generated by Bazel. Failure is happening for me at 9b96872, last time I saw this saw this same query working was fe87155.

**Comment by damienmg** [comment]
Assigning to Kristina for maven, please triage this bug.

@ekuefler: can you close the bug if it's no longer relevant?

**Comment by ekuefler** [comment]
It's still relevant. I can work around it in my case by querying `//src/...` instead of `...`, but `...` should still work, and the failure message refers to something inside of Bazel that I have no control over.

**Comment by kchodorow** [comment]
This should work now (been fixed for a while, actually).
