### ISSUE TITLE
Fail to build in chrooted environment without internet access, Mageia 7 (Cauldron)

### ISSUE THREAD

**Issue by kekePower** [bazelbuild/bazel#5313]
### Description of the problem / feature request:

Trying to build 0.14.0 in a chrooted env without internet access.
This commit https://github.com/bazelbuild/bazel/commit/3c9cd82b847f3ece8ec04b2029bd5e8ad0eb7502#diff-31959a132c4ce4e1bed4ae6851cadbd3 tries to download a zip file which won't work in my environment and I've tried to put this file in various places without luck.

Where do I put https://github.com/google/desugar_jdk_libs/archive/f5e6d80c6b4ec6b0a46603f72b015d45cf3c11cd.zip?
Do I unzip it somewhere?
I've tried putting it in `derived/distdir` to no avail.
I've also tried putting it in `external/desugar_jdk_libs` in my `output` dir. No luck.

Now at a loss.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try to build bazel 0.14.0 in iurt on Mageia.

### What operating system are you running Bazel on?

Mageia 7 (Cauldron, dev-0)

### What's the output of `bazel info release`?

Bazel 0.13.1

```
Extracting Bazel installation...
Starting local Bazel server and connecting to it..............
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: src
Analyzing: target //src:bazel (1 packages loaded)
Analyzing: target //src:bazel (2 packages loaded)
Analyzing: target //src:bazel (2 packages loaded)
Analyzing: target //src:bazel (2 packages loaded)
    currently loading: @local_config_cc//
Analyzing: target //src:bazel (3 packages loaded)
Analyzing: target //src:bazel (4 packages loaded)
    currently loading: src/main/cpp
Analyzing: target //src:bazel (9 packages loaded)
    currently loading: @bazel_tools//tools/jdk ... (2 packages)
Analyzing: target //src:bazel (37 packages loaded)
    currently loading: @bazel_tools//src/tools/launcher/util
Analyzing: target //src:bazel (51 packages loaded)
    currently loading: third_party/protobuf/3.4.0
Analyzing: target //src:bazel (105 packages loaded)
    currently loading: third_party/protobuf/3.4.0 ... (4 packages)
Analyzing: target //src:bazel (115 packages loaded)
ERROR: /rpmbuild/BUILD/bazel-0.14.0/tools/android/BUILD:182:1: no such package '@desugar_jdk_libs//': Error downloading [https://github.com/google/desugar_jdk_libs/archive/f5e6d80c6b4ec6b0a46603f72b015d45cf3c11cd.zip] to /rpmbuild/BUILD/output/external/desugar_jdk_libs/f5e6d80c6b4ec6b0a46603f72b015d45cf3c11cd.zip: Unknown host: github.com and referenced by '//tools/android:desugar_jdk_libs'
Analyzing: target //src:bazel (115 packages loaded)
ERROR: Analysis of target '//src:bazel' failed; build aborted: Loading failed
Analyzing: target //src:bazel (115 packages loaded)
INFO: Elapsed time: 5.747s
Analyzing: target //src:bazel (115 packages loaded)
INFO: 0 processes.
Analyzing: target //src:bazel (115 packages loaded)
FAILED: Build did NOT complete successfully (115 packages loaded)
```

**Comment by jin** [comment]
cc @aehlig  @kevin1e100 @ahumesky

**Comment by ahumesky** [comment]
I believe that you have to pass `--experimental_distdir` point to the directory that you put the files in.

The bootstrap script does it like this:
https://github.com/bazelbuild/bazel/commit/3c9cd82b847f3ece8ec04b2029bd5e8ad0eb7502#diff-31959a132c4ce4e1bed4ae6851cadbd3R40

**Comment by ahumesky** [comment]
Also, this is all for the android rules that are built into bazel. We're in the process of moving those to skylark, so eventually this will all go away.

**Comment by kekePower** [comment]
@ahumesky Thank you. Setting `--experimental_distdir` did work as expected.
