### ISSUE TITLE
Nested WORKSPACE file ingnored when run build for parent workspace

### ISSUE THREAD

**Issue by IKupriyanov-HORIS** [bazelbuild/bazel#5325]
I have a project with nested WORKSPACES. Nested project uses dependencies(`//lib:commons-collections4`) and scripts (`//buils-scripts:module.bzl`) from parent.

Structure:
```
├── BUILD.bazel
├── build-scripts
│   ├── BUILD.bazel
│   └── module.bzl
├── lib
│   ├── BUILD.bazel
│   ├── commons-collections4
│   │   └── BUILD.bazel
│   └── third_party.bzl
├── nested
│   ├── foo
│   │   └── BUILD.bazel
│   ├── lib
│   │   ├── BUILD.bazel
│   │   ├── commons-lang3
│   │   │   └── BUILD.bazel
│   │   └── third_party.bzl
│   └── WORKSPACE
└── WORKSPACE
```

To get access to parent's dependencies and scripts I added parent as local repository.

nested `WORKSPACE`
```
local_repository(
  name="parent",
  path= "..",
)


load("@parent//lib:third_party.bzl", "third_party_libs")
third_party_libs()

load("//lib:third_party.bzl", "nested_third_party_libs")
nested_third_party_libs()
```

nested `BUILD.bazel`

```
load("@parent//build-scripts:module.bzl", "java_library")

java_library(
    name = "foo",
    visibility = ["//visibility:public"],
    deps = [
        "//lib/commons-lang3",
        "@parent//lib/commons-collections4",
    ],
)
```

`bazel build //...` for nested workspace works fine:

```
user:~/Projects/bazel-nested-workspaces$ cd nested
user:~/Projects/bazel-nested-workspaces/nested$ bazel build //...
INFO: Analysed target //lib/commons-lang3:commons-lang3 (9 packages loaded).
INFO: Found 1 target...
Target //lib/commons-lang3:commons-lang3 up-to-date:
  bazel-bin/lib/commons-lang3/libcommons-lang3.jar
INFO: Elapsed time: 9.480s, Critical Path: 3.50s
INFO: Build completed successfully, 5 total actions
```

But when I try to build parent:

```
user:~/Projects/bazel-nested-workspaces/nested$ cd ..
user:~/Projects/bazel-nested-workspaces$ bazel build //...
ERROR: error loading package 'nested/foo': Extension file not found. Unable to load package for '@parent//build-scripts:module.bzl': The repository could not be resolved
ERROR: error loading package 'nested/foo': Extension file not found. Unable to load package for '@parent//build-scripts:module.bzl': The repository could not be resolved
INFO: Elapsed time: 0.147s
FAILED: Build did NOT complete successfully (1 packages loaded)
    currently loading: nested/foo ... (3 packages)

```
I tried different solutions (absolute path for local repository, playing with workind directory), but found that you can just write any statements with incorrect syntax to the nested WORKSPACE file and still get the same error. So looks like the WORKSPACE file is not used. 

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

release 0.11.1

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Sample:
https://github.com/IKupriyanov-HORIS/bazel-nested-workspaces

**Comment by siddharthab** [comment]
This is known. There is ongoing effort to make this happen, but until then, all deps have to be listed in the workspace file of the workspace you are building. The most common way of listing deps from internal workspaces is to make the deps available through a macro, and then calling that macro from your outer workspace file. e.g., `go_rules_dependencies`.
https://bazel.build/designs/2016/09/19/recursive-ws-parsing.html

**Comment by aehlig** [comment]
That the file `nested/WORKSPACE` is not read is expected. Your top-level directory does not even mention `nested` as an external repository. Also, as @siddharthab mentioned, recursive `WORKSPACE` files are planned in the long run, but not implemented yet (and it probably take some time till we get there).

**Comment by IKupriyanov-HORIS** [comment]
> Your top-level directory does not even mention nested as an external repository.
This is intended. What I was expecting is build `nested` successfully (detecting `nested/WORKSPACE` and external dependencies) or skip it entirely because of parent has no references to it. Both cases were fine for me - parent isolated from `nested` and can be build without errors, `nested` can be build by own command.
Anyway thank you for clarifications!
