### ISSUE TITLE
test_cc_test_coverage broken since 0.11

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#5326]
### Description of the problem / feature request:

`test_cc_test_coverage` in `//src/test/shell/bazel:bazel_coverage_test` has been broken since 0.11, and suppressed because the CI containers do not have `/usr/bin/lcov` installed

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Install `lcov` such that it appears in `/usr/bin/lcov`
1. Run `bazel test //src/test/shell/bazel:bazel_coverage_test` in bazel src root

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

`release 0.12.0` through `release 0.13.1`

### Any other information, logs, or outputs that you want to share?

The dependency target `a` is being linked with `-lgcov` in 0.11, and without it in 0.12 onwards.

**Comment by werkt** [comment]
dad2276 introduced this failure. @mhlopko

**Comment by mhlopko** [comment]
Thanks for reporting, I'll look into it.

**Comment by mhlopko** [comment]
Tried on a mac and on a linux @HEAD and it passes. Can you pls verify if it was fixed in the meantime?

**Comment by werkt** [comment]
Yup, verified fixed. Haven't pinpointed the change that did it, but good enough for me.
