### ISSUE TITLE
Remote execution project broken at head

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#5329]
https://buildkite.com/bazel/remote-execution/builds?page=4

Project is broken since this commit: https://github.com/bazelbuild/bazel/commit/452141ffc66a3cbd27c597001585ade4251a307f
Logs: https://buildkite.com/bazel/remote-execution/builds/2101#cc63b8e7-bf87-4dcf-9093-5d7d932cb54a

@tomlu 
@buchgr

**Comment by aehlig** [comment]
Duplicate of #5323
