### ISSUE TITLE
without-jdk installer clarifications

### ISSUE THREAD

**Issue by llchan** [bazelbuild/bazel#5330]
It seems that the without-jdk installers haven't been released on github since v0.13.1. I did see the notes at #5247, but wanted to confirm a few things:

- There was a comment that "we plan not to release the without-jdk installers anymore". Is that still up for discussion, or has it already been decided? What was the reason for the change? I'd have to modify a bunch of stuff to build bazel from source, so personally I like having the prebuilt ones around.
- If this is already a finalized decision, then the docs at https://docs.bazel.build/versions/master/install-ubuntu.html (similar for other OSes) need to be updated with new instructions on how to install a non-embedded binary (or link to the compile-from-source page with the build target name).

**Comment by jin** [comment]
There was a discussion here: https://github.com/bazelbuild/continuous-integration/issues/269

and the mailing list thread here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bazel-dev/ycRQMZ3woj8/Sa1SuJXPBgAJ

cc @philwo @meteorcloudy

**Comment by aehlig** [comment]
@lberki since you were the driving force about bundling the jdk, can you add some documentation on the current state and the rational behind it?
