### ISSUE TITLE
Expand on the community-maintained Bazel packages on docs.bazel.build

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#5332]
https://docs.bazel.build/versions/master/install.html

https://repology.org/metapackage/bazel/versions

Regularly updated repositories:
- Arch Linux: https://www.archlinux.org/packages/community/x86_64/bazel/
- Gentoo: https://packages.gentoo.org/packages/dev-util/bazel
- Linuxbrew: https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/bazel.rb
- Scoop: https://github.com/lukesampson/scoop/blob/master/bucket/bazel.json
- Nixpkgs: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/build-managers/bazel/default.nix
- Parabola: https://www.parabola.nu/packages/?q=bazel
- FreeBSD Ports: https://www.freshports.org/devel/bazel

Update 2018/07/02: assigned to @rishacha

**Comment by jin** [comment]
cc @spomorski

**Comment by rishacha** [comment]
Can I take this up?

**Comment by jin** [comment]
@rishacha please do!

**Comment by jin** [comment]
Implemented by @rishacha.
