### ISSUE TITLE
Rule outputs callback gets list of labels, not targets

### ISSUE THREAD

**Issue by treuherz** [bazelbuild/bazel#5335]
According to the [docs on `attr.label_list`](https://docs.bazel.build/versions/master/skylark/lib/attr.html#label_list), it produces a list of Targets. However, if you define a callback function in order to specify your outsputs list (as described in [the `rule` docs](https://docs.bazel.build/versions/master/skylark/lib/globals.html#rule.outputs), it receives a list of Labels, not a list of Targets. Unless I've missed something, without a Target there is no way to access files or other providers, which means there's no way to use this information to generate the predeclared outputs.

Rough example:
```
# my_rule.bzl
def _outputs_dict(srcs):
    print(type(srcs))

my_rule = rule(
    attrs = {
        "srcs": attr.label_list()
    },
    ...
    outputs = _outputs_dict

DEBUG: [...]/my_rule.bzl:2:5: Label.
```

I'm running Bazel version 0.14.0. Perfectly open to the possibility that this isn't actually an oversight and I'm going about this all wrong.

**Comment by aehlig** [comment]
My understanding from reading the documentation is that only the implementation function gets label attributes as Targets, whereas the function declaring outputs only gets the labels. But I agree that the documentation could be improved here.

**Comment by treuherz** [comment]
Is that actually the desired behaviour? It seems like that would provide no way of defining output names based on transitive dependencies, or even files in a filegroup.

**Comment by treuherz** [comment]
Okay, I can just bundle the intermediate outputs. Thanks for the explanation! The use of "files" in the docs where it doesn't mean `File`s is what threw me.

**Comment by brandjon** [comment]
I think the "file" vs `File` confusion is mitigated if we're just careful to always say `File` when we mean the actual object. The problem with the docs I see is that attr.html isn't clear about distinguishing between the types of the attribute (as passed to `rule()`'s `attrs` dict) and the types of the corresponding `ctx.attr` values. For simple values like ints and strings they're the same, but for labels they get replaced by targets. We do say this in [rules.html](https://docs.bazel.build/versions/master/skylark/rules.html#files) but that's no excuse to not fix it elsewhere.
