### ISSUE TITLE
Support for execution-only "bootstrap" toolchains

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel#5345]
### Description of the problem / feature request:

I'd like to be able to define toolchains that only target the execution platform. This would be useful for bootstrap toolchains that build tools that run on the execution platform and are used in other toolchains.

### Feature requests: what underlying problem are you trying to solve with this feature?

In rules_go, we're building a pluggable static analysis framework. Users will define a `go_checker` rule, which depends on `go_library` rules that implement custom checks. The `go_checker` rule does some code generation and produces a binary for the execution platform. A specific `go_checker` binary is registered in WORKSPACE. This `go_checker` binary should ideally be part of the toolchain for the target platform and should run on all the source files compiled using that toolchain.

The problem is a cyclic dependency: the Go toolchain should contain a `go_checker`, but we need a toolchain to build a `go_checker`, since it depends on regular `go_library` rules. Ideally, we would be able to select an execution-only bootstrap toolchain that doesn't include the `go_checker`, and `go_library` rules would only use `go_checker` if it were available in the toolchain.

Currently, we're working around this by using a special rule, `go_tool_library` that does not depend on `go_checker`. `go_library` has an implicit dependency on `go_checker` (`go_checker` is not currently part of the toolchain).

**Comment by jayconrod** [comment]
cc @katre

**Comment by katre** [comment]
I think the only way to handle this will be to use two toolchain types: one for the bootstrapping, one for actual usage. If you write the implementation functions modularly, and use the same property names on the toolchain providers, you should be able to re-use a lot of code.

I'm closing this issue because I don't think this is something Bazel can support at this time.
