### ISSUE TITLE
--test_strategy=standalone has no effect

### ISSUE THREAD

**Issue by nicolov** [bazelbuild/bazel#5347]
### Description of the problem / feature request:

`--test_strategy=standalone` has no effect: tests are still run in a sandbox. https://github.com/bazelbuild/bazel/issues/5193 and https://github.com/bazelbuild/bazel/issues/1737 suggest using `--strategy=TestRunner=standalone`, which indeed disables the sandbox. [The FAQ](https://github.com/bazelbuild/bazel/wiki/FAQ) is incorrect.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
cat << EOF > WORKSPACE
EOF

cat << EOF > BUILD
cc_test(
    name = "atest",
    srcs = ["main.cc"],
)
EOF

cat << EOF > main.cc
#include <limits.h>
#include <stdio.h>
#include <unistd.h>

int main() {
        char cwd[PATH_MAX];
        getcwd(cwd, PATH_MAX);
        printf("My cwd is: %s\n", cwd);
        sleep(5);
        return 0;
}
EOF
```

`bazel test --test_strategy=standalone //...` shows the test running with the sandbox executor. `bazel test --strategy=TestRunner=standalone //...` shows `local`.

### What operating system are you running Bazel on?

> Replace this line with your answer.

### What's the output of `bazel info release`?

release 0.14.0

**Comment by ulfjack** [comment]
Fixed the FAQ. Unfortunately, I don't see an easy way of changing the --test_strategy flag to work in the expected way.
