### ISSUE TITLE
Access Bazel version from within Skylark

### ISSUE THREAD

**Issue by pspeter3** [bazelbuild/bazel#535]
Is it possible for Skylark to know the version of Bazel? Either through using a `genquery` or on the `ctx`?

**Comment by ulfjack** [comment]
Not right now, and we'd rather not add that. There are ways to get version
information, though. What's your use case?

**Comment by pspeter3** [comment]
I wanted to make sure that internal developers were running the correct Bazel version and fail with a helpful error message if they weren't. The alternative would be wrapping the bazel command with a version check.

**Comment by RNabel** [comment]
The bazel version is exposed to repository rules through `native.bazel_version`, example usage: in [Skylib](https://github.com/bazelbuild/bazel-skylib/blob/master/lib/versions.bzl#L20). Related question: https://github.com/bazelbuild/bazel/issues/3138

**Comment by thesayyn** [comment]
I think this feature should go into bazel to make bazel_features work well... without using a hack like stamping the bazel_version into a .bzl file to allow loading from BUILD files... 

https://github.com/bazel-contrib/bazel_features/issues/32

**Comment by thesayyn** [comment]
@Wyverald @fmeum @ulfjack can we reconsider this?
