### ISSUE TITLE
Remove -DCOMPILER_MSVC from CROSSTOOL

### ISSUE THREAD

**Issue by rongjiecomputer** [bazelbuild/bazel#5351]
### Description of the problem / feature request:

Remove `COMPILER_MSVC` macro from `CROSSTOOL`.

### Feature requests: what underlying problem are you trying to solve with this feature?

Build system should define as little flags as possible so that it does not conflict with existing projects.

### Potential Risk

As far as I know, Google projects are the only projects that use this macro. Most Google projects open-sourced before Bazel either use `_MSC_VER` directly or define `COMPILER_MSVC` in header file (which will cause macro redefinition warning if you use Bazel). The usage of this macro in Tensorflow was removed in https://github.com/tensorflow/tensorflow/pull/18448.

### Plan

1. Remove usage of `COMPILER_MSVC` in Bazel (#5350).
1. Update `third_party/protobuf` from 3.4.0 to 3.6.0 (released this week with many MSVC fixes, including removing some `COMPILER_MSVC`). Best left this for the Bazel team.
1. Remove `-DCOMPILER_MSVC` from `CROSSTOOL`.

**Comment by meteorcloudy** [comment]
@rongjiecomputer Thanks for this suggestion, we'll remove `COMPILER_MSVC` once no one depends on it.

**Comment by meteorcloudy** [comment]
@buchgr Can you help answering the above questions?

**Comment by meteorcloudy** [comment]
@rongjiecomputer BTW, protobuf 3.6 hasn't been released yet, right? So we might want to wait for the official release.

**Comment by rongjiecomputer** [comment]
@meteorcloudy [protobuf 3.6.0](https://github.com/google/protobuf/releases/tag/v3.6.0) was released 12 days ago after 3.6.0rc1 and 3.6.0rc2. See the [updated changelog](https://github.com/google/protobuf/blob/ce044817c7ba0aea27c3fd8e496635d94d20a755/CHANGES.txt) (the changelog was only updated in 3.6.x branch, not merged back to master branch yet for some reason).

protobuf 3.6.0.1 was also released 10 days ago with some minor fixes.

**Comment by meteorcloudy** [comment]
They just had a complete release today. https://github.com/google/protobuf/releases \o/

@buchgr Can we update protobuf version to 3.6? Is it OK for external contributor to do that?

**Comment by buchgr** [comment]
absolutely, if you get stuck just ping me! looking forward to the new protobuf :-)

**Comment by aiuto** [comment]
We updated protobuf beyond this a long time ago. I'm trying a PR to remove the defines.

**Comment by aiuto** [comment]
Fixed by protobuf update and https://github.com/bazelbuild/bazel/commit/121f6c7041b1ed73c715ae3dbc21bf47ab40b697
