### ISSUE TITLE
Inconsistent documentation about dict type

### ISSUE THREAD

**Issue by ash2k** [bazelbuild/bazel#5352]
### Description of the problem / feature request:
https://docs.bazel.build/versions/master/skylark/lib/dict.html#modules.dict says:
> The iteration order for a dict is deterministic and **specified** as the order in which the keys have been added to the dict. The iteration order is not affected if a value associated with an existing key is updated. 

But https://docs.bazel.build/versions/master/skylark/lib/globals.html#dict says:
> Note that the iteration order for dictionaries is deterministic but **unspecified**, and not necessarily related to the order in which keys are given to this function.

**Comment by laurentlb** [comment]
Thanks for the report, it's fixed. Iteration order is specified. For code maintenance/readability, you probably shouldn't rely on it though.
