### ISSUE TITLE
No way to add c-only flags in toolchain

### ISSUE THREAD

**Issue by kgreenek** [bazelbuild/bazel#5359]
### Description of the problem / feature request:

In my CROSSTOOL file, I need to pass the flag "-std=c11" to gcc. The available options that look relevant are `compiler_flag` and `cxx_flag`. There is no `c_flag`.

If I use compiler_flag (like this: `compiler_flag="-std=c11"`), then that flags gets passed to g++ too, and it spews warnings when building c++ projects:

```
cc1plus: warning: command line option '-std=c11' is valid for C/ObjC but not for C++
```

### Feature requests: what underlying problem are you trying to solve with this feature?

Add some way to pass compiler options that are only passed to the c compiler, i.e. `c_flags`

### What operating system are you running Bazel on?

Ubuntu 16.04. Cross-compiling for aarch64 with linaro toolchain (4.9).

### What's the output of `bazel info release`?

release 0.14.0

**Comment by mhlopko** [comment]
Hi Kevin, this is possible using `action_config`s and `feature`s, the new way of writing crosstools. We are in the process of writing documentation for it (likely to be submitted in O(weeks)), and once that's there we'll migrate crosstools to them (https://github.com/bazelbuild/bazel/issues/5187 for tracking the effort). Marking this issue as P2, but the documentation writing and migration itself are both P1. I will close this issue once the blocking issues are resolved.

**Comment by hlopko** [comment]
I believe all work related to this issue is done. Docs can be found https://docs.bazel.build/versions/0.26.0/cc-toolchain-config-reference.html
