### ISSUE TITLE
Dump a program readable graph for build actions

### ISSUE THREAD

**Issue by hhclam** [bazelbuild/bazel#536]
It will be nice that Bazel can generate a program readable graph that lists all the build actions, the input and output of each actions and the commands and the dependencies of actions. The format could be changed in the future.

**Comment by ulfjack** [comment]
What for?

**Comment by kayasoze** [comment]
`bazel query --output=xml` comes close, but it's not filtered by `select()`, and one must parse the XML tree.  There's also `bazel query --output=graph` but it's missing all of the metadata you're looking for.

**Comment by ulfjack** [comment]
Blaze query is most likely not the right answer as it works at the wrong level of abstraction. There is the extra_action mechanism, which can be used for static analysis, if that's what you want. However, if we don't know what the data is supposed to be used for, I don't see how we can design an API to support it.
