### ISSUE TITLE
Documentation does not list all attribute types

### ISSUE THREAD

**Issue by ash2k** [bazelbuild/bazel#5362]
### Description of the problem / feature request:

https://docs.bazel.build/versions/master/build-ref.html#rules says:

> The full set of types that an attribute can have is: integer, label, list of labels, string, list of strings, output label, list of output labels

But there are quite a few more types that are available: https://docs.bazel.build/versions/master/skylark/lib/attr.html#modules.attr

**Comment by laszlocsomor** [comment]
Thanks! If you feel like fixing it, here's the source for the doc file: https://github.com/bazelbuild/bazel/blob/master/site/docs/build-ref.html

**Comment by laszlocsomor** [comment]
(Otherwise someone else will fix it later.)
