### ISSUE TITLE
Windows: new_http_archive failed when archive file contains file symlink

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#5367]
###  **Reproduce**

WORKSPACE:
```
new_http_archive(
    name = "libcoap",
    urls = ["https://github.com/dthaler/libcoap/archive/IoTivity-1.2.1d.zip"],
    sha256 = "aac5b9101fad4cf722f0166f2739ebcefe55ad0ca7aa475550b11c8eb4740511",
    strip_prefix = "libcoap-IoTivity-1.2.1d",
    build_file = "config/libcoap.BUILD",
)
```
config/libcoap.BUILD:
```
cc_library(
    name = "libcoap",
    copts = ["-std=gnu99", "-fPIC",
             '-Wall', '-ffunction-sections',
             '-fdata-sections', '-fno-exceptions',
	     # to find headers in the libcoap source tree:
             "-Iexternal/libcoap/include",
             "-Iexternal/libcoap/include/coap",
             "-DWITH_POSIX",
             "-D_GNU_SOURCE",
             "-DWITH_UPSTREAM_LIBCOAP"],
    srcs = glob(["src/**/*.c"],
                exclude=["src/**/coap_io_lwip.c"]),
    hdrs = glob(["include/**/*.h"]),
    visibility = ["//visibility:public"]
)
```
```
$ bazel build @libcoap//:libcoap
...
ERROR: Source forest creation failed: C:/path/to/execroot/__main__/external/libcoap/README (Permission denied)
```

### **Root cause**

In archive `IoTivity-1.2.1d.zip`, `libcoap-IoTivity-1.2.1d/README` is a symlink pointing to `libcoap-IoTivity-1.2.1d/README.md`. The bug happens in the following steps:

1. Bazel first tries to extract `libcoap-IoTivity-1.2.1d/README`, which is a symlink. But the target doesn't exist yet, so it created a dangling junction pointing to `libcoap-IoTivity-1.2.1d/README.md`
2. Bazel extracts `libcoap-IoTivity-1.2.1d/README.md`
3. Bazel copies files from `C:\Users\pcloudy\_bazel_pcloudy\yaymuvfk\external\libcoap` to `C:\Users\pcloudy\_bazel_pcloudy\yaymuvfk\execroot\__main__\external\libcoap`. During copying `libcoap-IoTivity-1.2.1d/README`, `Files.copy(target, link);` failed with a permission error, because `target` is a dangling junction, but it's supposed to be a file.

Code:
https://github.com/bazelbuild/bazel/blob/a729b9b4c3d7844a7d44934bf3365f92633c0a60/src/main/java/com/google/devtools/build/lib/windows/WindowsFileSystem.java#L51-L72

**Comment by meteorcloudy** [comment]
FYI @laszlocsomor @dslomov

**Comment by laszlocsomor** [comment]
Thanks for the analysis!

More info about symlink behavior on Windows, which may be relevant:
- in MSYS, you cannot create dangling symlinks
- in MSYS, creating a symlink makes a copy of the symlink target -- in case of directories, this means making a recursive copy
- in MSYS, `unzip` defers extracting the symlink from the archive if the symlink would be dangling upon extraction, and will only extract it at the end, if the symlink's target exists by then

**Comment by meteorcloudy** [comment]
Thanks for the info! 
> unzip defers extracting the symlink from the archive if the symlink would be dangling upon extraction, and will only extract it at the end, if the symlink's target exists by then

Yes, I'm crafting a change that defers the symlink creation, which should fix this problem!
