### ISSUE TITLE
Add ability to access package root in genrule even when there is only one outs file.

### ISSUE THREAD

**Issue by aaronlevin** [bazelbuild/bazel#5368]
### Description of the problem / feature request:

Request: a deterministic way to get the package root in a `genrule`. I cannot use `$(@D)` for this because its location changes depending on the number of files in the output. The following is stated about `$(@D)` (emphasis mine) in documentation [here](https://docs.bazel.build/versions/master/be/make-variables.html):

> `@D`: The output directory. **If there is only one filename in outs, this expands to the directory containing that file. If there are multiple filenames, this variable instead expands to the package's root directory in the genfiles tree, even if all the generated files belong to the same subdirectory!** If the genrule needs to generate temporary intermediate files (perhaps as a result of using some other tool like a compiler) then it should attempt to write the temporary files to `@D` (although `/tmp` will also be writable), and to remove any such generated temporary files. Especially, avoid writing to directories containing inputs - they may be on read-only filesystems, and even if they aren't, doing so would trash the source tree.

This subtle difference when there is only one file is causing my build to fail.

### Feature requests: what underlying problem are you trying to solve with this feature?

Request: a deterministic way to get the package root in a `genrule`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have the following `BUILD` file:

```
  pkg_tar(
      name = "proto_files_tar",
      srcs = glob(["**/*.proto"]),
      visibility = ["//visibility:public"],
      package_dir = "proto-out",
      strip_prefix = ".",
  )

  genrule(
      name = "proto_files",
      srcs = [ ":proto_files_tar" ],
      outs = ["proto-out/" + p for p in glob(["**/*.proto"]) ],
      visibility = ["//visibility:public"],
     cmd = " tar -C $(@D) -xf $(location :proto_files_tar) ",
  )
```

My build breaks if `:proto_files_tar` tars up only one file because it can't find the output. 

### What operating system are you running Bazel on?

macOS and Linux.

### What's the output of `bazel info release`?

```
release 0.13.0-homebrew
```

###  Have you found anything relevant by searching the web?

https://docs.bazel.build/versions/master/be/make-variables.html

### Any other information, logs, or outputs that you want to share?

here is an example bazel build invocation for a project with more than one proto file (works) and only one proto file (does not work):

```
☭  bazel build @foo_schemas//:proto_files
INFO: Analysed target @foo_schemas//:proto_files (18 packages loaded).
INFO: Found 1 target...
Target @foo_schemas//:proto_files up-to-date:
  ... 
 INFO: Elapsed time: 10.466s, Critical Path: 0.06s
INFO: 1 process, darwin-sandbox.
INFO: Build completed successfully, 2 total actions

☭  bazel build @bar_schemas//:proto_files
INFO: Analysed target @bar_schemas//:proto_files (1 packages loaded).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_aaronlevin/1e79b92a50186b03de1139ced9fb465b/external/bar_schemas/BUILD:22:1: declared output 'external/bar_schemas/proto-out/proto/protofile.proto' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
ERROR: /private/var/tmp/_bazel_aaronlevin/1e79b92a50186b03de1139ced9fb465b/external/bar_schemas/BUILD:22:1: not all outputs were created or valid
Target @bar_schemas//:proto_files failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.228s, Critical Path: 0.06s
INFO: 1 process, darwin-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by laszlocsomor** [comment]
I agree with @benjaminp -- this should do the trick:

```
genrule(
    name = "x",
    outs = ["x.txt"],
    cmd = "{ echo GENDIR=$(GENDIR) ; echo D=$(@D) ; echo pkg=" + package_name() + " ; } > $@",
)
```

**Comment by aaronlevin** [comment]
@laszlocsomor sorry, I'm a bit new to bazel and there doesn't seem to be much info on what `package_name` returns. Is it enough to just do: `$(GENDIR)/package_name()`? 

I think we should have something in the environment that consistently provides this directory, but I would be happy even with some clear documentation on how to construct this path. 

Thanks @benjaminp for your quick suggestion.

**Comment by jmillikin-stripe** [comment]
I've also been bitten by this, had had to use workarounds like a dummy `.keep` file so that the outs list would always have at least two elements.

Is the documented single-file behavior of `$(@D)` useful? I can't think of any other cases where the semantics of a make variable changes based on whether a list has size=1 or size>1.

**Comment by laszlocsomor** [comment]
@aaronlevin : `package_name()` is a function that returns a string, which you can call in the BUILD file. `$(GENDIR)` is a placeholder that you can embed in a string on the right side of `genrule.cmd`. Therefore you can write `genrule(..., cmd = "echo $(GENDIR)/%s > $@" % package_name(), ...)`.

@jmillikin-stripe : sorry, I don't know if it's useful or not. I think a consistent behavior would be better, alas we are now stuck with it.

**Comment by laszlocsomor** [comment]
Closing this since there's a solution.
