### ISSUE TITLE
Provide better sandboxfs errors (e.g. when FUSE isn't available).

### ISSUE THREAD

**Issue by PiotrSikora** [bazelbuild/bazel#5369]
### Description of the problem / feature request:

`sandboxfs` doesn't provide helpful errors (e.g. when FUSE isn't available) and returns generic `sandboxfs failed to start` error.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ sudo mv /bin/fusermount /tmp/; bazel build --experimental_use_sandboxfs //...; sudo mv /tmp/fusermount /bin
INFO: Mounting sandboxfs instance on <redacted>/sandbox/sandboxfs
ERROR: Failed to initialize sandbox: sandboxfs failed to start
INFO: Elapsed time: 0.204s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

### What operating system are you running Bazel on?

```
$ uname -a
Linux buildbox 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
$ cat /etc/debian_version
9.4
```

### What's the output of `bazel info release`?

```
$ bazel info release
release 0.14.1
```

**Comment by jmmv** [comment]
Just to pile onto the bug because this is related: depending on how sandboxfs fails, Blaze may even report that "sandboxed" is an *unknown strategy*. I think this happens when the sandboxfs binary cannot be found, but I forget now.
