### ISSUE TITLE
Pseudoterminals don't work in the Linux sandbox

### ISSUE THREAD

**Issue by lee-bin** [bazelbuild/bazel#5373]
### Description of the problem / feature request:

When I run a python script, which uses the 'sh' module,  from bazel genrule, it failed with this:
```
INFO: Analysed target //src:foo_gen (8 packages loaded).
INFO: Found 1 target...
ERROR: /home/libin11/workspace/test/test/src/BUILD:1:1: Executing genrule //src:foo_gen failed (Exit 1)
Traceback (most recent call last):
  File "src/test.py", line 2, in <module>
    sh.touch("foo.bar")
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 767, in __init__
    self.call_args, pipe, process_assign_lock)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1784, in __init__
    self._stdout_read_fd, self._stdout_write_fd = pty.openpty()
  File "/usr/lib/python2.7/pty.py", line 29, in openpty
    master_fd, slave_name = _open_terminal()
  File "/usr/lib/python2.7/pty.py", line 70, in _open_terminal
    raise os.error, 'out of pty devices'
OSError: out of pty devices
Target //src:foo_gen failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.143s, Critical Path: 0.12s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```
### Feature requests: what underlying problem are you trying to solve with this feature?

I want to integrate a thirdparty project to my own. The third party project is built with a python script, so I would like to build the project with bazel genrule. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Example file list:
```
.
├── src
│   ├── BUILD
│   └── test.py
└── WORKSPACE
```
WORKSPACE is empty, BUILD is:
```
genrule(
    name = "foo_gen",
    srcs = glob(["**/*"]),
    outs = ["foo.bar"],
    cmd = "python $(location test.py)",
)
```
test.py is:
```
import sh
sh.touch("foo.bar")
```
And run:
```
bazel build //src:foo_gen
```
### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

release 0.14.1

**Comment by laszlocsomor** [comment]
Are you sure this is a bug in Bazel? Looks like Python is giving an error message:

```
OSError: out of pty devices
```

How have you tried to resolve this issue?

**Comment by lee-bin** [comment]
However, if I run test.py directly from bash, it runs successfully. Only if I run it in bazel genrule, if fails.

**Comment by laszlocsomor** [comment]
It's hard to say whether Bazel legitimately fails to find the module or not without digging deeper.

What is the culprit of the error -- is it importing the `sh` module, or a call in the main module? Try removing code and keep rebuilding until you find the minimal code that triggers the build failure.

**Comment by lee-bin** [comment]
I actually did what you said, and minimized the Python code to only 2 lines.  From the log I pasted above, it says that it failed calling sh.touch().
>File "src/test.py", line 2, in <module>
    sh.touch("foo.bar")
All my codes are above, less than 10 lines, just enough to reproduce the problem.
You can just copy the code above to try it. Thanks.

**Comment by laszlocsomor** [comment]
Sorry, indeed you wrote that in the original post already.

I couldn't repro the same issue. Still, your use of `python` in a genrule is not the right way, and probably doesn't work with sandboxing if the python script has some dependencies, since the genrule is not aware of those dependencies.

To alleviate those problems, use a `py_binary` rule and update the `genrule` as follows:

```
genrule(
    name = "foo_gen",
    srcs = glob(["**/*"]),
    outs = ["foo.bar"],
    cmd = "$(location :test) > $@",
    tools = [":test"],
)

py_binary(
    name = "test",
    srcs = ["test.py"],
)
```

This guarantees that the Python binary is built correctly and hermetically, and will work with sandboxing.

Does this solve the issue?

**Comment by lee-bin** [comment]
I tried it again with your advice. Still, it does not work, same issue. However, if I change the Python code to 
```
sh.touch("foo.bar", _tty_in=False, _tty_out=False)
```
it works. I took advice from [here](https://stackoverflow.com/questions/50810690/cant-use-pythons-sh-module-in-bazel-genrule).
Is it because of something of Bazel genrule's strategy? Since the Python script runs successfully by itself.

**Comment by laszlocsomor** [comment]
Good to know there's a solution!

What do the `_tty_in` and `_tty_out` args do? I couldn't find any info about that. As for `genrule`, it probably closes stdin and redirects stdout to a file when running the command.

**Comment by laszlocsomor** [comment]
Closing, since there's a solution and I don't think there's any Bazel bug here.

**Comment by lee-bin** [comment]
Actually, the Python code is from a third_party project, and it builds successfully by itself. I can't integrated the project by genrule without changing the original Python code, which is not very automatic. So may be there is something Bazel's genrule could improve.

**Comment by laszlocsomor** [comment]
Thanks! I could repro the issue. You're right, this could be a genrule bug. Let me take a look.

**Comment by laszlocsomor** [comment]
Ah, this is due to sandboxing.

Bazel offers different strategies for executing the genrule's command. Building without sandboxing succeeds (using the [genrule.cmd that I suggested earlier](https://github.com/bazelbuild/bazel/issues/5373#issuecomment-396886360)).


```
  $ cat src/BUILD
genrule(
    name = "foo_gen",
    srcs = glob(["**/*"]),
    outs = ["foo.bar"],
    cmd = "python $(location test.py) > $@",
)
```

With the `sandbox` and `linux-sandbox` strategies the build fails:
```
  $ bazel build //src:foo_gen -s --genrule_strategy=linux-sandbox
INFO: Analysed target //src:foo_gen (0 packages loaded).
INFO: Found 1 target...
SUBCOMMAND: # //src:foo_gen [action 'Executing genrule //src:foo_gen']
(cd /usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/3c6cb648541dfbe89dfe0225af0cc45d/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/google/home/laszlocsomor/bazel-releases/current/bin:/usr/local/google/home/laszlocsomor/bazel-releases/current/bin:/usr/lib/google-golang/bin:/usr/local/buildtools/java/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; python src/test.py > bazel-out/k8-fastbuild/genfiles/src/foo.bar')
ERROR: /tmp/gh5373/src/BUILD:16:1: Executing genrule //src:foo_gen failed (Exit 1)
Traceback (most recent call last):
  File "src/test.py", line 2, in <module>
    sh.touch("foo.bar")
  File "/usr/local/google/home/laszlocsomor/.local/lib/python2.7/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/google/home/laszlocsomor/.local/lib/python2.7/site-packages/sh.py", line 767, in __init__
    self.call_args, pipe, process_assign_lock)
  File "/usr/local/google/home/laszlocsomor/.local/lib/python2.7/site-packages/sh.py", line 1784, in __init__
    self._stdout_read_fd, self._stdout_write_fd = pty.openpty()
  File "/usr/lib/python2.7/pty.py", line 29, in openpty
    master_fd, slave_name = _open_terminal()
  File "/usr/lib/python2.7/pty.py", line 70, in _open_terminal
    raise os.error, 'out of pty devices'
OSError: out of pty devices
Target //src:foo_gen failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.333s, Critical Path: 0.11s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

With `processwrapper-sandbox` it succeeds:

```
  $ bazel build //src:foo_gen -s --genrule_strategy=processwrapper-sandbox
INFO: Analysed target //src:foo_gen (0 packages loaded).
INFO: Found 1 target...
SUBCOMMAND: # //src:foo_gen [action 'Executing genrule //src:foo_gen']
(cd /usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/3c6cb648541dfbe89dfe0225af0cc45d/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/google/home/laszlocsomor/bazel-releases/current/bin:/usr/local/google/home/laszlocsomor/bazel-releases/current/bin:/usr/lib/google-golang/bin:/usr/local/buildtools/java/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; python src/test.py > bazel-out/k8-fastbuild/genfiles/src/foo.bar')
Target //src:foo_gen up-to-date:
  bazel-genfiles/src/foo.bar
INFO: Elapsed time: 0.329s, Critical Path: 0.12s
INFO: 1 process, processwrapper-sandbox.
INFO: Build completed successfully, 2 total actions
```

Also with `standalone`:
```
  $ bazel clean ; bazel build //src:foo_gen -s --genrule_strategy=standalone
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //src:foo_gen (8 packages loaded).
INFO: Found 1 target...
SUBCOMMAND: # //src:foo_gen [action 'Executing genrule //src:foo_gen']
(cd /usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/3c6cb648541dfbe89dfe0225af0cc45d/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/google/home/laszlocsomor/bazel-releases/current/bin:/usr/local/google/home/laszlocsomor/bazel-releases/current/bin:/usr/lib/google-golang/bin:/usr/local/buildtools/java/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; python src/test.py > bazel-out/k8-fastbuild/genfiles/src/foo.bar')
Target //src:foo_gen up-to-date:
  bazel-genfiles/src/foo.bar
INFO: Elapsed time: 0.518s, Critical Path: 0.06s
INFO: 1 process, local.
INFO: Build completed successfully, 2 total actions
```

**Comment by lee-bin** [comment]
Thanks. This really helps me. It would be better if genrule's doc could warn about this.

**Comment by laszlocsomor** [comment]
I'm glad it helped!

> It would be better if genrule's doc could warn about this.

Can you suggest a good phrasing for that? (Or even send a PR with the doc update?)

**Comment by jmmv** [comment]
An easier reproduction doesn't need the `sh` module to be installed. Some `test.py` file:

```python
import pty
pty.openpty()
```

and then:

```shell
.../path/to/install/base/linux-sandbox python test.py
```

is sufficient.

I think this should work. I don't see why the sandbox should disallow pseudoterminals (if that's what it's doing). It might have something to do with access to `/dev` though. Would need some more investigation before saying that this is just a doc fix, in particular because I suspect this will behave differently between Mac and Linux.

**Comment by sgadrian** [comment]
Any updates around this?

**Comment by frazze-jobb** [comment]
We are using an in house testing framework at Ericsson that makes use of psuedoterminals as well. And this stops us from using sandbox on our tests. We would appreciate if this was fixed!

**Comment by frazze-jobb** [comment]
@philwo you have great knowledge of sandbox. It seems that there is some problem with accessing /dev/pts, I assume that it would require a change in linux-sandbox c++ code. Do you know if there is something more to it, that would make this difficult to implement?
