### ISSUE TITLE
//src/test/java/com/google/devtools/build/lib:sandbox-tests was broken by the 0.14.0 release

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/bazel#5376]
/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/a39cf1aa22a493bc118ce43a149b1f8d/execroot/io_bazel/bazel-out/k8-fastbuild/bin/src/test/java/com/google/devtools/build/lib/sandbox-tests.runfiles/io_bazel/src/test/java/com/google/devtools/build/lib/sandbox-tests: line 353: /usr/lib/jvm/java-8-openjdk-amd64/bin/java: No such file or directory

(https://storage.googleapis.com/bazel-buildkite-artifacts/75cbf56f-9b6b-4fde-b689-9d27ecca3762/src/test/java/com/google/devtools/build/lib/sandbox-tests/attempt_1.log)

**Comment by jin** [comment]
We're going into 0.17.0, is this still a concern?
