### ISSUE TITLE
Bazel binary got much bigger

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#5378]
### Description of the problem / feature request:

With commit e28c0ab84c7967e10cc3cd5333560c54653084bd, the Bazel binary's size increased from ~110M to ~170M, and the number of files in the embedded_tools increased from 509 to 4780.

The bigger size means higher download time, but also slower Bazel startup.

The higher number of embedded tools means slower Bazel startup, especially on Windows where I/O is typically expensive.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build Bazel at e28c0ab84c7967e10cc3cd5333560c54653084bd and at bbf3e421ed8b2b431a72cd3ab4ba591dc8833634 (the commit before).

Compare the binary sizes:

```
stat bazel-bin/src/bazel
```

Compare the number of embedded tools:
```
find $(bazel-bin/src/bazel --output_user_root=/tmp/bzl/$RANDOM info install_base) -type f | wc -l
```

**Comment by laszlocsomor** [comment]
@iirina has a fix for this and I'm working on a regression test.

**Comment by alexeagle** [comment]
Wow that's impressive how much size was added just by the sources for the test coverage data parser. Thanks for the fix, I hope we can find places to reduce the binary size more, it's important for us to squeeze bazel into the existing frontend toolchain
