### ISSUE TITLE
Skylark git_repository with patches parameter produce useless errors in common use-case

### ISSUE THREAD

**Issue by RNabel** [bazelbuild/bazel#5379]
### Description of the problem / feature request:

When using the Skylark `git_repository` rule and provide a file to `patches` which complies to the patch format but is valid results in a completely misleading error message:

```
Error applying patch //:broken.patch:
WARNING: Target pattern parsing failed.
```

### Feature requests: what underlying problem are you trying to solve with this feature?

When using Skylark `git_repository`, provide additional information from `patch` binary execution, additional documentation, or suppress the `WARNING` that seems to be generated by another part of bazel.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Create folder with the following files:
```
$ cat WORKSPACE
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
  name = "protobuf",
  remote = "git@github.com:google/protobuf.git",
  tag = "v3.5.1",
  patches = ["//:garbage.patch"],
)

$ cat BUILD
exports_files(["working.patch", "broken.patch", "garbage.patch"])

$ cat working.patch
---
 CONTRIBUTORS.txt | 1 +
 1 file changed, 1 insertion(+)

--- CONTRIBUTORS.txt
+++ CONTRIBUTORS.txt
@@ -100,3 +100,4 @@ Patch contributors:
   Andrew Paprocki <andrew@ishiboo.com>
     * Fixed minor IBM xlC compiler build issues
     * Added atomicops for AIX (POWER)
+Some text
--

$ cat broken.patch
---
 CONTRIBUTORS.txt | 1 +
 1 file changed, 1 insertion(+)

--- a/CONTRIBUTORS.txt
+++ b/CONTRIBUTORS.txt
@@ -100,3 +100,4 @@ Patch contributors:
   Andrew Paprocki <andrew@ishiboo.com>
     * Fixed minor IBM xlC compiler build issues
     * Added atomicops for AIX (POWER)
+Some text
--

$ cat garbage.patch
Complete garbage.
```

2. Then run `bazel build @protobuf//:protobuf` changing the entry in the `patches` parameter within the `WORKSPACE` file to `//:working.patch`, `//:broken.patch`, and `//:garbage.patch`

3. Observe that the cases for `//:working.patch` is as expected (--> it compiles), the case for `//:garbage.patch` is as expected, you're provided with the output:
```
Error applying patch //:garbage.patch:
patch: **** Only garbage was found in the patch input.
WARNING: Target pattern parsing failed.
```
Which is actionable.

In the case of `//:broken.patch`, however, it fails printing only:
```
Error applying patch //:broken.patch:
WARNING: Target pattern parsing failed.
```
which is highly misleading.

### What operating system are you running Bazel on?

Checked on macos and Windows.

### What's the output of `bazel info release`?

`release 0.14.0-homebrew` and `release 0.14.0` respectively.

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

`broken.patch` was created from a commit made on top of the protobuf `master` branch, running the command `git format-patch HEAD^`. 

There are two ways of fixing `git` created patches: 1) remove all mentions of `a/` and `b/` within the file, 2) use a custom `patch_cmd` which calls `patch -p1`.

It would have been extremely useful if this were documented somewhere.

**Comment by aehlig** [comment]
There is already a related pull request, #4974,  which however still has some GNUism in it. Maybe I'll just merge it with a changed test, if the original author @deeglaze agrees.
