### ISSUE TITLE
All C++ builds failing on OSX

### ISSUE THREAD

**Issue by ekuefler** [bazelbuild/bazel#538]
I just updated Bazel and can no longer build anything on OS X that touches gcc, whether it's my code or stuff from Bazel. I get the following error when trying to build from my workspace:

```
$ bazel build third_party/ijar:zipper
INFO: Found 1 target...
INFO: From Compiling third_party/ijar/zip_main.cc:
process-wrapper: execvp("tools/cpp/osx_gcc_wrapper.sh", ...): No such file or directory
ERROR: /Users/erik/github/bazel/base_workspace/third_party/ijar/BUILD:29:1: C++ compilation of rule '//third_party/ijar:zipper' failed: osx_gcc_wrapper.sh failed: error executing command tools/cpp/osx_gcc_wrapper.sh '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer '-std=c++0x' -iquote . -iquote ... (remaining 17 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //third_party/ijar:zipper failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.580s, Critical Path: 0.01s
```

The same command works from the bazel workspace, so I'm not sure what's different about mine. `tools/cpp/osx_gcc_wrapper.sh` does exist in the bazel repo.

Possibly related to #534?

**Comment by ekuefler** [comment]
It works at dda3f8c8, not sure what happened since then

**Comment by kchodorow** [comment]
Looking into it.  Weird that the ci isn't hitting this.

**Comment by kchodorow** [comment]
Another report of this: https://groups.google.com/d/msgid/bazel-discuss/7a37ff41-942d-4dd4-80e5-ddebd513315d%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by philwo** [comment]
Just a guess, but maybe the "tools are integrated in the Bazel binary now" change has something to do with it? If it works in the Bazel repo, where the script is present as a file, but not when the same Bazel binary is used in a different repo, that sounds a bit like it... @lberki ?

**Comment by kchodorow** [comment]
(I haven't actually been able to reproduce this.)

**Comment by lberki** [comment]
I could reproduce this and I have a change out to fix this. The bad news is that it breaks Android on Linux with sandboxing for some reason, so I'll have to figure that out before I submit it.
