### ISSUE TITLE
Control reactions to input transience during action execution

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#5388]
### Description of the feature request:

Detect when an action's inputs are modified during its execution independent of spawn_strategy, and propagate that boolean result (possibly with the inputs modified) to the strategy for further control. Create options that allow the control of reactions (error, retry, logging, suppression, fallback, remote/local cache interactions).

### Feature requests: what underlying problem are you trying to solve with this feature?

The current solution for discovering modified inputs is currently fragmented, specialized to strategy (remote), duplicated, uncontrollable - RemoteSpawnRunner silently suppresses based on ctime modification invariably, while RemoteSpawnCache fails based on digest comparisons with an option configuration, and none of these things factor into Action definitions, meaning that an action can pass with this test in place and poison a cache for a remote action fetch that would ignore the test.

@ola-rozenfeld discussed initial ideas on this.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

release 0.14.0

**Comment by laszlocsomor** [comment]
I see multiple sub-issues, is this separation correct?
- feature: detect modified input for all strategies
- feature: let the ... (_what?_) specify what Bazel should do when an action's input is modified mid-execution
- bug: prevent cache poisoning with modified inputs

If so, could you split them into separate issues?
