### ISSUE TITLE
Allow structs in Skylark sets

### ISSUE THREAD

**Issue by schroederc** [bazelbuild/bazel#539]
It'd be useful to allow Skylark sets to contain structs of the same shape:

```
a = set([struct(field = 1)])
b = set([struct(field = 1), struct(field = 2)])
c = a + b
// c == b
```

**Comment by schroederc** [comment]
Any possible progress to this in the near future?

**Comment by damienmg** [comment]
it is kind of a hard work, is there a specific case that this is blocking?

**Comment by schroederc** [comment]
Nothing currently blocked other than some code cleanups.

**Comment by dslomov** [comment]
This is fixed now
