### ISSUE TITLE
RepositoryCache irreparably invalidated on build interrupt

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#5390]
### Description of the problem / feature request:

Maven/HttpDownloaders initiate downloads directly into repository cache paths, which, when interrupted, leave invalid repository cache contents that only fail on `get`, and are not re-downloaded.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Perform a build which populates a file in the repository cache for an http archive external repository
Modify the `file` content in the repository cache to produce an inconsistent checksum to its cache key value
Delete the root/external/<repository> to ensure an attempted repository fetch
Run a fetch/query/build/test/run which utilizes the external repository
Be greeted with an error message indicating that you should `Please delete the directory ...<cache entry digest> and try again.`

Observe that this is repeatable

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

release 0.14.0, reproduces with current HEAD

**Comment by laszlocsomor** [comment]
In other words, Bazel doesn't notice that a download was interrupted, correct?

**Comment by werkt** [comment]
Correct, it doesn't notice, and it responds to invalid content on any subsequent invocations that access it via `RepositoryCache::get` (i.e. during `HttpDownloader::download`) by erroring. The only solution is to manually intervene and excise the cache entry. This is undesirable on a build fleet, as it can occur on any build abort.

**Comment by jin** [comment]
I think @werkt's fix will do it. The current repository cache implementation doesn't have any eviction policy, so this is a good start to remove poisoned files.

**Comment by aehlig** [comment]
I believe this should be fixed with 3926e9a8d2b9ededf3a8cfac039bcaeeb7766e70. Please reopen, if the problem persists.
