### ISSUE TITLE
Building ERROR `missing input file '@local_jdk//:bin/jar` on Linux

### ISSUE THREAD

**Issue by w568w** [bazelbuild/bazel#5394]
### Description of the problem / feature request:
When I'm trying to build bazel from source on Linux,it shows `missing input file '@local_jdk//:bin/jar`.

### Feature requests: what underlying problem are you trying to solve with this feature?
n/a

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Run `apt install build-essential openjdk-8-jdk python zip unzip pkg-config g++ zlib1g-dev`  on a **fresh** `Ubuntu x86` and then run `./compile.sh`.

### What operating system are you running Bazel on?
OS:`Linux Mint 18.3`  
Kernel: `i686 Linux`
### What's the output of `bazel info release`?
I haven't built `bazel 0.14.1 release` successfully.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
n/a

###  Have you found anything relevant by searching the web?
I have had a look at [this issue](https://github.com/bazelbuild/bazel/issues/4885) and [this one](https://github.com/bazelbuild/bazel/pull/4579) but they are not related to my problem. 

### Any other information, logs, or outputs that you want to share?
Here is the build log:
```
$ ./compile.sh
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
INFO: Analysed target //src:bazel (206 packages loaded).
INFO: Found 1 target...
ERROR: missing input file '@local_jdk//:bin/jar'
ERROR: /home/w568w/bazel/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/BUILD:148:1: //src/java_tools/buildjar/java/com/google/devtools/build/buildjar:skylark-deps: missing input file '@local_jdk//:bin/jar'
Target //src:bazel failed to build
ERROR: /home/w568w/bazel/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/BUILD:148:1 1 input file(s) do not exist
INFO: Elapsed time: 270.085s, Critical Path: 19.43s
INFO: 721 processes, local.
FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel
```
And Java version:
```
$ java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) Server VM (build 25.144-b01, mixed mode)
```

**Comment by laszlocsomor** [comment]
You probably have to export `JAVA_HOME` to point to the JDK's directory. Does that help?

**Comment by laszlocsomor** [comment]
Also, what CPU architecture do you use -- 32bit or 64bit?

**Comment by w568w** [comment]
I think I have export `JAVA_HOME`,output:
```
$ echo $JAVA_HOME
/home/w568w/jdk

$ $JAVA_HOME/bin/jar
Usage: jar {ctxui}[vfmn0PMe] [jar-file] [manifest-file] [entry-point] [-C dir] files
...
```
CPU architecture is `32bit`.

**Comment by laszlocsomor** [comment]
I'm afraid Bazel doesn't support 32-bit platforms :(

@cushon : do you know if Bazel can use a 32-bit JDK?

**Comment by cushon** [comment]
@laszlocsomor maybe? I didn't think we're using that much arch-dependency JNI, etc. I'm also not sure why that would cause the error with `jar`.

@w568w which version of Bazel are you trying to build?

**Comment by w568w** [comment]
```
@w568w which version of Bazel are you trying to build?
```
@cushon It's 0.14.1,the lastest release.

**Comment by w568w** [comment]
BTW,I wonder whether it's possible to build a 32-bit version of bazel on 64-bit platforms?

**Comment by laszlocsomor** [comment]
> BTW,I wonder whether it's possible to build a 32-bit version of bazel on 64-bit platforms?

Maybe, though probably not. We don't put any effort into supporting 32-bit. In theory it's possible, because Bazel supports cross-compilation by design, and with the right compiler definition in the `CROSSTOOL`, it should be possible to build the C++ code for 32-bit. The java code is more likely to build for 32-bit, though not with `./compile.sh`, because that script compiles all Java files within one invocation, which requires more than 3G of memory if I remember correctly.

**Comment by laszlocsomor** [comment]
Actually, I see you got past the "Building Bazel from scratch......" stage, that means you compiled all the java code. That's promising!

If you want to hack on this: study how the bootstrapping scripts run the java-only version of Bazel, what flags it passes to `java` -- see this: https://github.com/bazelbuild/bazel/blob/940fbd7aafc8227a5ff110ddac1be71d17225adf/scripts/bootstrap/compile.sh#L328

The bootstrapper has a `trap` to delete all the files it created upon exit: https://github.com/bazelbuild/bazel/blob/940fbd7aafc8227a5ff110ddac1be71d17225adf/scripts/bootstrap/buildenv.sh#L128

...so you should comment out this line to prevent the file deletions.

It's still a mystery why `@local_jdk//:bin/jar` is missing. But if you build `${ARCHIVE_DIR}/libblaze.jar` and manage to run it with `run_bazel_jar`, then you could do a `run_bazel_jar query //external:local_jdk --output=build` which produces something like:

```
# /DEFAULT.WORKSPACE:6:1
new_local_repository(
  name = "local_jdk",
  path = "/usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/install/e584f4223170558586344d31921e7766/_embedded_binaries/embedded_tools/jdk",
  build_file = "/usr/local/google/home/laszlocsomor/.cache/bazel/_bazel_laszlocsomor/install/e584f4223170558586344d31921e7766/_embedded_binaries/jdk.BUILD",
)
```

As you will see, my JDK is where the `path` shows it. You can also query the targets in `@local_jdk` with `run_bazel_jar query @local_jdk//... --output=label_kind`.

I'm sorry this is so hacky and unsupported, but we don't have resources to support 32-bit host platforms.

**Comment by w568w** [comment]
> I'm sorry this is so hacky and unsupported, but we don't have resources to work on supporting 32-bit host platforms.

I have found the problem by following your steps:  
My `$JAVA_HOME/bin/jar` is a link to another path which contains non-ascii chars(so strange),  
I move it and the problem is never reported again.  
  
However,it shows another error:   
    
```
$ ./compile.sh 
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
INFO: Analysed target //src:bazel (206 packages loaded).
INFO: Found 1 target...
ERROR: /home/w568w/bazel/src/tools/singlejar/BUILD:386:1: C++ compilation of rule '//src/tools/singlejar:output_jar' failed 
(Exit 1): gcc failed: error executing command xxxxxxxxx.....(many lines of output)
./src/tools/singlejar/mapped_file_posix.inc:30:2: error: #error This code for 64 bit Unix.
 #error This code for 64 bit Unix.
Target //src:bazel failed to build
INFO: Elapsed time: 289.779s, Critical Path: 17.94s
INFO: 536 processes, local.
FAILED: Build did NOT complete successfully
```
https://github.com/bazelbuild/bazel/blob/1bacab9717a76dfbfc9612b3864bc25588220bbd/src/tools/singlejar/mapped_file_posix.inc#L30  

It seems that `bazel` **does not support 32-bit platforms**.  
Anyhow thanks for reply.
