### ISSUE TITLE
flaky tests don't actually work

### ISSUE THREAD

**Issue by bsilver8192** [bazelbuild/bazel#540]
Despite what the documentation says, flaky tests don't actually get run multiple times. https://groups.google.com/d/msgid/bazel-discuss/CAN3hOS-%2Bn9rsd_SeL4hr7gTrGA%2Bmk3831pm-bNTfCsgY6L8WAQ%40mail.gmail.com has some discussion.

**Comment by ulfjack** [comment]
It's probably because the TestStrategy implementation was a rewrite instead of open sourcing our internal implementation. We should probably refactor the two to pull out the common code, which should make this work.

**Comment by ulfjack** [comment]
I think this is a bug, and this needs to be fixed before 1.0 (preferably sooner)...

**Comment by damienmg** [comment]
Retriaged, this was wrongly categorized. This is hurting us too and it would be great to correctly fixing. Taking a look at it to assess.

**Comment by damienmg** [comment]
So I have a fix on my machine should be there to celebrate 2017 :fireworks:
