### ISSUE TITLE
Provide better fallback options for no-remote targets when running a remote build

### ISSUE THREAD

**Issue by bergsieker** [bazelbuild/bazel#5400]
### Description of the problem / feature request:

Targets marked no-remote fall back to running locally during remote builds. Ideally such targets could optionally be made to run in the sandbox instead.

### Feature requests: what underlying problem are you trying to solve with this feature?

I believe there are plans to overhaul spawn strategies and fallback in general, but Philipp suggested a short-term fix to resolve this particular case:

"In the short term, I would recommend that we fix the code like this:
- In RemoteActionContextProvider, we pass in not one, but two fallback
runners: The current platform default sandbox strategy for "no-remote"
actions and the LocalSpawnRunner for the "no-remote and no-sandbox" actions.
- We change RemoteSpawnRunner to use the correct one of the two fallback
runners."

**Comment by laszlocsomor** [comment]
Philipp is on a longer-term leave, so I'm routing this to @ulfjack .

**Comment by laszlocsomor** [comment]
also /cc @nlopezgi

**Comment by brian-peloton** [comment]
Any progress on this?

**Comment by philwo** [comment]
Sorry for the delay. Took longer than expected after my parental leave to get back up to speed. I'll fix this first thing tomorrow morning. :(

**Comment by brian-peloton** [comment]
I'm pretty sure this is fixed now, if somebody wants to close the issue.

**Comment by AustinSchuh** [comment]
From the commit:


RELNOTES: When using Bazel's remote execution feature and Bazel has to
fallback to local execution for an action, Bazel used non-sandboxed
local execution until now. From this release on, you can use the new
flag --remote_local_fallback_strategy=<strategy> to tell Bazel which
strategy to use in that case.

https://bazel-review.googlesource.com/c/bazel/+/67658/2//COMMIT_MSG

**Comment by ittaiz** [comment]
Thanks!

**Comment by philwo** [comment]
I think we can consider this fixed with the new automatic strategy selection having been released. :)
