### ISSUE TITLE
Better messaging for mix of remote strategy and caching

### ISSUE THREAD

**Issue by nlopezgi** [bazelbuild/bazel#5401]
see: https://github.com/bazelbuild/bazel-toolchains/issues/80

The remote strategy is only available if you don't use caching. If you enable remote caching, you should remove the --*_strategy=remote options. This means that your build will start to run with local sandboxing; if you don't want that, then you can set the flags to =standalone instead.

Error messaging when users include both remote strategy and caching (as the above is not well documented anywhere afaik) is not good though.

**Comment by brentleyjones** [comment]
I believe this issue is no longer valid, and can be closed.

**Comment by sgowroji** [comment]
Thanks for the update. @nlopezgi, Let us know if you are still looking support on the above issue. We are closing now., Feel free to reach us for to reopen or any further information.
