### ISSUE TITLE
gitconfig url mod causes bazel to fail with auth issues.

### ISSUE THREAD

**Issue by gergnz** [bazelbuild/bazel#5404]
### Description of the problem / feature request:

bazel fails to get plugins when git is set to rewrite URL

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

add the following to your ~/.gitconfig
```
[url "git@github.com:"]
	insteadOf = https://github.com/
```

In your WORKSPACE file add something like:
```
git_repository(
    name = "io_grpc_grpc_java",
    remote = "https://github.com/grpc/grpc-java",
    tag = "v1.12.0",
)
```
Then run bazel:
```
bazel run //:gazelle -- update-repos
```

### What operating system are you running Bazel on?

MacOS 10.13.5

### What's the output of `bazel info release`?

release 0.14.1-homebrew

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

?

###  Have you found anything relevant by searching the web?

no

### Any other information, logs, or outputs that you want to share?

(17:48:55) ERROR: error loading package '': Encountered error while reading extension file 'maven/rules.bzl': no such package '@org_pubref_rules_maven//maven': Error cloning repository: git@github.com:pubref/rules_maven: Auth fail caused by git@github.com:pubref/rules_maven: Auth fail caused by Auth fail
(17:48:55) ERROR: Skipping '//:gazelle': error loading package '': Encountered error while reading extension file 'maven/rules.bzl': no such package '@org_pubref_rules_maven//maven': Error cloning repository: git@github.com:pubref/rules_maven: Auth fail caused by git@github.com:pubref/rules_maven: Auth fail caused by Auth fail

**Comment by aehlig** [comment]
Is there a way to reproduce the error using only bazel proper, or, at least, can you provide more information on the `//:gazelle` target in your main repository that you rely on? Thanks.

**Comment by gergnz** [comment]
I'm not an experienced bazel user, but the project that I was trying to build was: https://github.com/lucperkins/colossus.

Hopefully that helps.

**Comment by dslomov** [comment]
native git_repository is no more
