### ISSUE TITLE
Bazel build tensorflow/contrib/lite/toco:toco throws no such package @local_config_git 

### ISSUE THREAD

**Issue by naelabdeljawad** [bazelbuild/bazel#5412]
HI,

Getting bellow error while building any source.

> WARNING: /home/automator/.cache/bazel/_bazel_automator/1376e9d23e5a9ca94a937b0adecd0263/external/protobuf_archive/WORKSPACE:1: Workspace name in /home/automator/.cache/bazel/_bazel_automator/1376e9d23e5a9ca94a937b0adecd0263/external/protobuf_archive/WORKSPACE (@com_google_protobuf) does not match the name given in the repository's definition (@protobuf_archive); this will cause a build error in future versions
ERROR: /home/automator/Documents/Tensorflow/tensorflow-master/tensorflow/core/BUILD:2288:1: no such package '@local_config_git//': Traceback (most recent call last):
	File "/home/automator/Documents/Tensorflow/tensorflow-master/third_party/git/git_configure.bzl", line 52
		_fail(result.stderr)
	File "/home/automator/Documents/Tensorflow/tensorflow-master/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: java.io.IOException: Cannot run program "/home/automator/.cache/bazel/_bazel_automator/1376e9d23e5a9ca94a937b0adecd0263/external/local_config_git/home/automator/Documents/Anaconda/anaconda3/bin/python" (in directory "/home/automator/.cache/bazel/_bazel_automator/1376e9d23e5a9ca94a937b0adecd0263/external/local_config_git"): error=2, No such file or directory
 and referenced by '//tensorflow/core:version_info_gen'
ERROR: /home/automator/Documents/Tensorflow/tensorflow-master/tensorflow/core/BUILD:2288:1: no such package '@local_config_git//': Traceback (most recent call last):
	File "/home/automator/Documents/Tensorflow/tensorflow-master/third_party/git/git_configure.bzl", line 52
		_fail(result.stderr)
	File "/home/automator/Documents/Tensorflow/tensorflow-master/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: java.io.IOException: Cannot run program "/home/automator/.cache/bazel/_bazel_automator/1376e9d23e5a9ca94a937b0adecd0263/external/local_config_git/home/automator/Documents/Anaconda/anaconda3/bin/python" (in directory "/home/automator/.cache/bazel/_bazel_automator/1376e9d23e5a9ca94a937b0adecd0263/external/local_config_git"): error=2, No such file or directory
 and referenced by '//tensorflow/core:version_info_gen'
ERROR: /home/automator/Documents/Tensorflow/tensorflow-master/tensorflow/core/BUILD:2288:1: no such package '@local_config_git//': Traceback (most recent call last):
	File "/home/automator/Documents/Tensorflow/tensorflow-master/third_party/git/git_configure.bzl", line 52
		_fail(result.stderr)
	File "/home/automator/Documents/Tensorflow/tensorflow-master/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: java.io.IOException: Cannot run program "/home/automator/.cache/bazel/_bazel_automator/1376e9d23e5a9ca94a937b0adecd0263/external/local_config_git/home/automator/Documents/Anaconda/anaconda3/bin/python" (in directory "/home/automator/.cache/bazel/_bazel_automator/1376e9d23e5a9ca94a937b0adecd0263/external/local_config_git"): error=2, No such file or directory
 and referenced by '//tensorflow/core:version_info_gen'
ERROR: Analysis of target '//tensorflow/contrib/lite/toco:toco' failed; build aborted: no such package '@local_config_git//': Traceback (most recent call last):
	File "/home/automator/Documents/Tensorflow/tensorflow-master/third_party/git/git_configure.bzl", line 52
		_fail(result.stderr)
	File "/home/automator/Documents/Tensorflow/tensorflow-master/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: java.io.IOException: Cannot run program "/home/automator/.cache/bazel/_bazel_automator/1376e9d23e5a9ca94a937b0adecd0263/external/local_config_git/home/automator/Documents/Anaconda/anaconda3/bin/python" (in directory "/home/automator/.cache/bazel/_bazel_automator/1376e9d23e5a9ca94a937b0adecd0263/external/local_config_git"): error=2, No such file or directory
INFO: Elapsed time: 6.945s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (41 packages loaded)

Tried on Bazel versions:
0.13.0 
0.13.1
0.14.0
0.14.1

I need to build Tensorflow source bu no luck.
Any idea what causes this error?

Thanks

**Comment by mhlopko** [comment]
It appears to me that this is an issue to be reported on the Tensorflow repo (that's where the git_configure.bzl is implemented). And it looks like a problem is with your python binary, so you can start debugging there:

`/home/automator/.cache/bazel/_bazel_automator/1376e9d23e5a9ca94a937b0adecd0263/external/local_config_git/home/automator/Documents/Anaconda/anaconda3/bin/python" (in directory "/home/automator/.cache/bazel/_bazel_automator/1376e9d23e5a9ca94a937b0adecd0263/external/local_config_git"): error=2, No such file or directory`

I'll close this issue now, please reopen if you believe this is bazel issue.

**Comment by petewarden** [comment]
As a note for anyone arriving via Google search, I was able to fix a similar error by installing the 'future' pip package:

`pip install future`

**Comment by wangyunxiaa** [comment]
> installing
i have installed future by `pip install future`
but always has the error.
my env is windows10, TFS=1.13,bazel=0.20.0, VS=1.5, I could bazel build tensorflow successfuly,but can not build TFS, the error is `ERROR: C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/org_tensorflow/tensorflow/core/BUILD:2515:1: no such package '@local_config_git//': Traceback (most recent call last):
        File "C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/org_tensorflow/third_party/git/git_configure.bzl", line 52
                _fail(result.stderr)
        File "C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/org_tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
                fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(239): CreateProcessW("C:\users\wangyunxia\_bazel_wangyunxia\5aybp25i\external\local_config_git\usr\bin\python" C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py --configure C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/org_tensorflow/ --gen_root_path C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/local_config_git/gen): ???????????

 and referenced by '@org_tensorflow//tensorflow/core:version_info_gen'
ERROR: C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/org_tensorflow/tensorflow/core/BUILD:2515:1: no such package '@local_config_git//': Traceback (most recent call last):
        File "C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/org_tensorflow/third_party/git/git_configure.bzl", line 52
                _fail(result.stderr)
        File "C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/org_tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
                fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(239): CreateProcessW("C:\users\wangyunxia\_bazel_wangyunxia\5aybp25i\external\local_config_git\usr\bin\python" C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py --configure C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/org_tensorflow/ --gen_root_path C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/local_config_git/gen): ???????????

 and referenced by '@org_tensorflow//tensorflow/core:version_info_gen'
ERROR: C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/org_tensorflow/tensorflow/core/BUILD:2515:1: no such package '@local_config_git//': Traceback (most recent call last):
        File "C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/org_tensorflow/third_party/git/git_configure.bzl", line 52
                _fail(result.stderr)
        File "C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/org_tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
                fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(239): CreateProcessW("C:\users\wangyunxia\_bazel_wangyunxia\5aybp25i\external\local_config_git\usr\bin\python" C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py --configure C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/org_tensorflow/ --gen_root_path C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/local_config_git/gen): ???????????

 and referenced by '@org_tensorflow//tensorflow/core:version_info_gen'
ERROR: Analysis of target '//tensorflow_serving/model_servers:tensorflow_model_server' failed; build aborted: no such package '@local_config_git//': Traceback (most recent call last):
        File "C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/org_tensorflow/third_party/git/git_configure.bzl", line 52
                _fail(result.stderr)
        File "C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/org_tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
                fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(239): CreateProcessW("C:\users\wangyunxia\_bazel_wangyunxia\5aybp25i\external\local_config_git\usr\bin\python" C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py --configure C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/org_tensorflow/ --gen_root_path C:/users/wangyunxia/_bazel_wangyunxia/5aybp25i/external/local_config_git/gen): ???????????`

**Comment by seshuk291** [comment]
> As a note for anyone arriving via Google search, I was able to fix a similar error by installing the 'future' pip package:
> 
> `pip install future`

This worked for me
