### ISSUE TITLE
java_stub_template is quadratic and fails for large classpaths.

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#5413]
### Description of the problem / feature request:
When trying to use very large classpaths, I could not. There are two issues:

1. it takes a very long time to start due to what appears to me a quadratic algorithm here: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt#L299
2. the bash fails when the line length gets too long, for me we have `${#CLASSPATH_LINE} == 1316701`, then we get an error like:
```
/private/var/tmp/_bazel_oscar/2e3334a32b6c7df26258a7f6c5c2cb5f/execroot/com_stripe_zoolander/bazel-out/darwin-fastbuild/bin/zoolander-archival/thrift_class_checker: line 316: ((: 1.00004e+06 == 0: syntax error: invalid arithmetic operator (error token is ".00004e+06 == 0")
/private/var/tmp/_bazel_oscar/2e3334a32b6c7df26258a7f6c5c2cb5f/execroot/com_stripe_zoolander/bazel-out/darwin-fastbuild/bin/zoolander-archival/thrift_class_checker: line 319: CLASSPATH_LINE: 1.00004e+06: syntax error: invalid arithmetic operator (error token is ".00004e+06")
```

### Feature requests: what underlying problem are you trying to solve with this feature?

ability to run with large classpaths.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

you can reproduce error two with a simple bash script:
```bash
#!/bin/sh

for i in `seq 0 71 1316701`; do
    PREFIX=" "
    if (($i == 0)); then
      PREFIX=""
    fi
    echo "good! $i"
done

```

if we change to:
```
#!/bin/sh

for i in `seq 0 71 1316701`; do
    PREFIX=" "
    if [[ "$i" = "0" ]]; then
      PREFIX=""
    fi
    echo "good! $i"
done

```
it seems to work...

### What operating system are you running Bazel on?

0.13b.1

### What's the output of `bazel info release`?

release 0.13.1-homebrew

###  Have you found anything relevant by searching the web?

I think this is a bug that I don't need much web corroboration for.

**Comment by cushon** [comment]
I agree this is a problem that should be fixed, but have you considered using a `_deploy.jar` here? Aside from the issues with the stub script, runtime classloader performance is usually not great for extremely long classpaths.

**Comment by johnynek** [comment]
1. note that an exacerbating issue is that most of these jar paths are to external repos, which have much longer paths due to also having a long workspace name. We don't have a particularly large repo, but we do code generate 1 build target (jar) per thrift file so that users can depend just on what we need. If we do something larger than that, we would have to have some complex graph coarsening to produce a DAG (while the dag at the file level is assured).

2. this problem manifests for virtually all binary targets at the top of our repo with non-trivial dependencies (if we use bazel to build the thrifts in this way), so using _deploy.jar would mean retraining all our users and also massively slowing down build (since it is slow to produce deploy jars).

**Comment by johnynek** [comment]
I wonder if the right solution is build this classpath jar with the classpath in the rule rather than having bash create it on every run.

**Comment by cushon** [comment]
@meteorcloudy, who implemented this feature for bazelbuild/bazel#2242

I ideally we'd only do this work when necessary (i.e. on windows, if the classpath exceeds the limit) and checking the classpath length during analysis is expensive. But if there's a way to push this work into a separate action that's appealing.

**Comment by johnynek** [comment]
would it be costly to create this jar for everyone at build time? seems like this would be super fast in c++ or java to take a file that has a list of files and construct a correct jar.

**Comment by meteorcloudy** [comment]
Hi, @johnynek We had a reason not to create classpath jar during build time, please see https://github.com/bazelbuild/bazel/issues/2242#issuecomment-275090032

**Comment by zachgrayio** [comment]
looks like this got handled by this PR: https://github.com/bazelbuild/bazel/pull/9314

**Comment by zachgrayio** [comment]
however we are seeing that in some cases, manifest classpaths beyond a certain length fail at runtime (truncated?), maybe a java 8 issue; so maybe shouldn't close it just yet.

performance: ✅ 
long classpaths work perfectly: 🚫
