### ISSUE TITLE
darwin installer sig key  has expired

### ISSUE THREAD

**Issue by mobileink** [bazelbuild/bazel#5421]
### Description of the problem / feature request:

$ gpg --verify bazel-0.14.1-installer-darwin-x86_64.sh.sig
gpg: assuming signed data in 'bazel-0.14.1-installer-darwin-x86_64.sh'
gpg: Signature made Fri Jun  8 07:31:31 2018 CDT
gpg:                using RSA key 3D5919B448457EE0
gpg: Good signature from "Bazel Developer (Bazel APT repository key) <bazel-dev@googlegroups.com>" [expired]
gpg: Note: This key has expired!

### What operating system are you running Bazel on?

Mac OS 10.12.6

$ gpg --version
gpg (GnuPG) 2.2.1
libgcrypt 1.8.1

**Comment by mhlopko** [comment]
I belive @buchgr has fixed this already. Please reopen if I'm wrong. Thanks!
