### ISSUE TITLE
py_proto_library' is not defined

### ISSUE THREAD

**Issue by wubo0067** [bazelbuild/bazel#5427]
**BUILD:** 
cc_proto_library(
    name = "yd_fieldoptions_cc",
    deps = [":yd_fieldoptions"],
)

py_proto_library(
    name = "yd_fieldoptions_py",
    deps = [":yd_fieldoptions"],
)

proto_library(
    name = "yd_fieldoptions",
    srcs = ["yd_fieldoptions.proto"],
    deps = [
        "@com_google_protobuf//:descriptor_proto",
    ],
)

### Error
bazel build -s //field_options:yd_fieldoptions_py
**BUILD:11:1: name 'py_proto_library' is not defined (did you mean 'cc_proto_library'?)**

bazel version: 
Build label: 0.14.0- (@non-git)
protobuf verson: 3.5.0

**Comment by rongjiecomputer** [comment]
You need to import `py_proto_library` from protobuf. Add `load("@com_google_protobuf//:protobuf.bzl", "py_proto_library")` at the beginning of the `BUILD` file.

**Comment by jin** [comment]
Thanks @rongjiecomputer for the answer! Please ask questions in StackOverflow in the future. Closing this now.
