### ISSUE TITLE
Replace HashFuncntion enum with HashFunction or Hasher Interface

### ISSUE THREAD

**Issue by gvacaliuc** [bazelbuild/bazel#5430]
Disclaimer: This may be considered a discussion starter, but I'm starting work on a PR for this, and I thought it'd be a good idea to track it.

[Relevant post on bazel-dev](https://groups.google.com/forum/#!topic/bazel-dev/SH-Dnm5e0TE) that brought up the change I'd like to make.

### Description of the problem / feature request:

Currently, the hash function used by bazel is defined in [an enum inside the FileSystem class](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/vfs/FileSystem.java#L44).  As discussed in the bazel-dev post, we're looking to add a new FileSystem implementation for internal use @ Two Sigma that happens to have a specific hash function tied to it for legacy reasons.  Since the FileSystem enum only exposes 3 hash functions (MD5, SHA1, SHA256), we end up having to patch the FileSystem file with a new enum entry rather than just passing in a reference to ours in a BlazeModule that loads in our custom filesystem.

### Feature requests: what underlying problem are you trying to solve with this feature?

Changing the usages of the current hash function enum to the HashFunction interface (which is the enum's value anyways) allows the ability to add a new HashFunction implementation at a high-level in a BlazeModule rather than patching the enum in FileSystem.

### Concrete Proposed Changes

Update all references from com.google.devtools.build.lib.vfs.FileSystem.HashFunction to com.google.common.hash.HashFunction, changing usages as needed.  Add a mapping from String to com.google.common.hash.HashFunction in BazelFileSystemModule for use with the  bazel.DigestFunction system property.

**Comment by gvacaliuc** [comment]
It looks like this was resolved in bda12a1b239235de0169b14760214e43f839bed8.

**Comment by lberki** [comment]
(/me watches this thread fly by)

I'm glad that this got fixed. For an unrelated reason, mind you, but never look the gift horse in the mouth :)
