### ISSUE TITLE
Expose repository rule(s) which give the user more control over downloading/unpacking of archives

### ISSUE THREAD

**Issue by cgoy-nvidia** [bazelbuild/bazel#5438]
### Description of the problem / feature request:

As it stands right now, `new_http_archive` will download and unpack the archive every time the `buld_file` referenced in this rule is modified.  This may make sense for some work flows, but not for all. I have attached a workaround project for anyone running into similar issues.

### Feature requests: what underlying problem are you trying to solve with this feature?

For large archive files, iterating on `BUILD` files to expose rules is very painful.  Giving the user control over when these should be downloaded (flag, sha, url change) would ease the pain of waiting for a download. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
1.Download the repro project attached
2. Build the rules without doing changing anything
3. Modify the `BUILD.symlink` file by adding a space
4. Build the `//:test_rule`
5. Modify the `BUILD.new_http_archive` file by adding a space
6. Build the `//:test_rule_http_archive`
7. Note the differences in time.

### What operating system are you running Bazel on?

Ubuntu 1604

### What's the output of `bazel info release`?

release 0.12.0

###  Have you found anything relevant by searching the web?

I see there are other issues related to this: 
#4462
#5167
maybe others.
The workaround was built based off of bazel documentation for [`repository_ctx`](https://docs.bazel.build/versions/master/skylark/lib/repository_ctx.html)

### Any other information, logs, or outputs that you want to share?

I have attached a small project to show a workaround for the issue, please read the README.md file for instructions.  I would recommend using the profiling tools that bazel has to get exact numbers on timing.

Cheers.
[bazel-repo-issue.zip](https://github.com/bazelbuild/bazel/files/2121568/bazel-repo-issue.zip)

**Comment by aehlig** [comment]
Note that with `--repository_cache` now enabled by default, files with specified hash are no longer refetched from the network. So, while more flexibility with respect to caching might be desirable, and re-unpacking might not be ideal, that issue is low priority.

**Comment by cgoy-nvidia** [comment]
Hey @aehlig,
Thanks for the response.  Which version is `--repository_cache` enabled by default?  Looking at the docs for this configuration does not give me a hint as to which version this has been flipped on.  
Cheers,
Chris

**Comment by colatkinson** [comment]
WRT re-unpacking, in certain cases it can end up being a much larger chunk of build time than fetching. I've run into this with large `xz` archives, like the ones used by LLVM for binary releases.

Profile results for a clean build with a complete repo cache:
![with cache screenshot](https://user-images.githubusercontent.com/6528368/81899346-9a988880-9588-11ea-99b4-3437c818a7c1.png)

And without:
![without cache screenshot](https://user-images.githubusercontent.com/6528368/81899348-9b311f00-9588-11ea-8781-a7032d0fa3f8.png)

What changes would be needed to avoid re-unpacks? It looks like the remote storage API [already supports tree structures](https://github.com/bazelbuild/remote-apis/blob/7802003e00901b4e740fe0ebec1243c221e02ae2/build/bazel/remote/execution/v2/remote_execution.proto#L337), but I don't know if that's even the right place to begin implementing something like this.
