### ISSUE TITLE
Too many maven_jar()s handled in parallel

### ISSUE THREAD

**Issue by deadmoose** [bazelbuild/bazel#5452]
Currently running `0.14.1` on ubuntu. Seeing similar on my mac with `0.12.0-homebrew`

I've got some projects with moderately sized webs of maven dependencies, and an initial build brings my machine to its knees by processing all the `maven_jar` declarations in parallel.

Example repository: https://github.com/deadmoose/billions_of_mavens

That's used slightly modified [bazel-deps](https://github.com/johnynek/bazel-deps) to generate `third_party/workspace.bzl` which declares a little over 200 `maven_jar` rules.

Clone that fresh, try something e.g. `bazel build //...` or `bazel fetch //...`, and watch the machine grind to a halt as 200+ mvn invocations are fired off simultaneously. I've got a real repository with a larger set of dependencies that spiked my poor desktop to > 1000 load average.

Once the jars are fetched, everything's fine, but that initial download brings everything to its knees.

**Comment by petroseskinder** [comment]
@johnynek

**Comment by johnynek** [comment]
we don't use maven_jar internally. It calls out to maven and is CRAZY slow.

Actually, we just use http_jar (a minor modification that also pulls the source). That seems to work okay.

I don't think the skylark maven_jar is actually usable. I don't know if anyone is actually using it in production with a lot of jars.

cc @ianoc

**Comment by ianoc** [comment]
We have some repo’s using maven jar, but not the one here. This is the skylark maven jar and as @johnynek mentions it spawns lots of copies of maven and isn’t usable. If you use the native.maven_jar instead which should be a drop in replacement I think you’ll have a much better time

**Comment by jin** [comment]
cc @aehlig @dslomov

**Comment by jin** [comment]
Consider using `jvm_maven_import_external` with `load("@bazel_tools//tools/build_defs/repo:jvm.bzl", "jvm_maven_import_external")`. This is available in HEAD Bazel.

Some numbers on my 6 core workstation on billions_of_mavens:

With `native.maven_jar`:

```
real    0m12.026s
user    0m0.012s
sys     0m0.044s
```

With Skylark `maven_jar` that shells out to Maven:

```
real    4m57.427s
user    0m0.024s
sys     0m0.680s
```

and this is with a manual SIGKILL after 5 minutes. Also ground my machine to a halt.

With `jvm_maven_import_external`:

```
real    0m6.530s
user    0m0.032s
sys     0m0.048s
```

**Comment by jin** [comment]
The changes to `declare_maven` workspace.bzl in bazel-deps would look like this:

```
load("@bazel_tools//tools/build_defs/repo:jvm.bzl", "jvm_maven_import_external")

def declare_maven(hash):
    jvm_maven_import_external(
        name = hash["name"],
        artifact = hash["artifact"],
        licenses = ["notice"],
        rule_name = "java_import",
        server_urls = ["https://repo.maven.apache.org/maven2"],
    )
    native.bind(
        name = hash["bind"],
        actual = hash["actual"],
    )

```

**Comment by johnynek** [comment]
note that hash also includes a url in the `"repository"` key, so you can use that in addition to any other urls you want, e.g.:

https://github.com/johnynek/bazel-deps/blob/master/3rdparty/workspace.bzl#L17

**Comment by ittaiz** [comment]
@jin I seem to remember external dependencies are sequential and not parallel. I guess I’m wrong that all of it is sequential but I assume there is still a sequential part.
Is that right? Can you say what’s sequential and what’s parallel?

**Comment by deadmoose** [comment]
I wound up having to swap to the skylark maven_jar because of private repos + authentication. Ditto for why I can't use http_jar in its place :/

It also solved another problem I was having where one bazel+maven project referenced another & had overlapping dependencies. The native maven_jar rule would blow up on duplicate declarations whereas the skylark one coped. (Ignore, for the moment, the fact that the two having dupes like that probably implies some scary things going on where one doesn't realize its expected version of some dep is getting overridden by the other...that's unfortunately a normal situation anyway with everyone's tangled web of maven deps)

About to get sucked into an afternoon full of meetings, but I'll give `jvm_maven_import_external` a look as soon as I can.

**Comment by jin** [comment]
@ittaiz That's my understanding too, although it may have changed in recent development. @dkelmer do you have any idea?

**Comment by ianoc** [comment]
For the latter case you can check if the target has already been registered and skip it. (For similar reasons I’ve had to do something like that before. ). 

jvm_import_external might work for you, but if not A repository rule would probably be a reasonably simple option for the former issues too. If you can presume the machines have curl installed. It can probably do the auth/fetch for you. The latest master of bazel deps when using coursier will emit the urls for the jar, source jar and the sha’s. So you could plug that into a simple curl ?

**Comment by deadmoose** [comment]
@ianoc do you have a pointer at a good example of checking and skipping? I've been meaning to find time to cuddle up with the docs to see how all the repo stuff works; I really miss google3 just vendoring in the universe so I don't have to think about it...

And yeah, worst case I suppose I could roll my own repository rule that curls out to get stuff, but I'm missing what that would buy? Wouldn't I be in a similar boat with a few hundred simultaneous curls eating all the resources, or is the problem here really that maven-dependency-plugin is so heavyweight? (I guess getting a chance to see how `jvm_maven_import_external` does this that jin's test run was fast might answer that)

**Comment by deadmoose** [comment]
This got back burnered for a bit since I didn't have the cycles to run from head to try `jvm_maven_import_external`, but since 0.15 shipped with it, I gave it a whirl yesterday.

First impressions are great; it was nice & speedy and no longer brought my computer to its knees.

Only concern now is skimming things, it doesn't look like there's anything in there for handling authentication to private repos (fortunately, the bulk of what I care about right now is public)

I guess in the scaffolding  around it I could build up an entry for `server_urls` that has baked in user/pass read from someplace, but that's going to be an extra hurdle to get folks onboarded + I'm a little worried about managing to leak it in a log somewhere.

Thoughts?

**Comment by deadmoose** [comment]
Related: https://github.com/bazelbuild/bazel/issues/6502

Also, while I'm here, an update on the current jury-rigged setup:
 * Patched version of bazel-deps which teaches it to use creds for certain repositories
 * If the artifact came from one of those, it's flagged as such in the generated `workspace.bzl`
 * `workspace.bzl` uses the default logic (`ctx.download`ing jars) in most cases, but if flagged as needing auth, uses the skylark `maven_jar` which shells out to `mvn`

Few enough artifacts come from the private repo that firing those off in parallel is manageable. (For now)

**Comment by dslomov** [comment]
This should now be an issue in https://github.com/bazelbuild/rules_jvm_external
