### ISSUE TITLE
Add a "deps" attribute to cc_import

### ISSUE THREAD

**Issue by pylaligand** [bazelbuild/bazel#5456]
### Description of the problem / feature request:

This is a feature request to add a `deps` attribute to `cc_import`.

### Feature requests: what underlying problem are you trying to solve with this feature?

Some prebuilt libraries have public dependencies on other libraries, by using these libraries' public headers in their own public headers. There currently does not seem to be a way to express this with `cc_import` which is the preferred way to include prebuilts.

###  Have you found anything relevant by searching the web?

There's a way to work around this by declaring a `cc_library` which both depends on the `cc_import` and on its public dependencies, and direct clients to depend on the `cc_library`.

**Comment by mhlopko** [comment]
Good point, we'll fix it. But to save cycles let's do so only after `cc_import` is in Skylark (blocked by #4570).

**Comment by MSK61** [comment]
The attribute is still not documented [here](https://bazel.build/reference/be/c-cpp#cc_import) though.
