### ISSUE TITLE
dependency on JAVA sucks

### ISSUE THREAD

**Issue by rofl0r** [bazelbuild/bazel#5458]
### Description of the problem / feature request:

> JAVA is a proprietary product, and it is almost impossible to bootstrap from source. Doing so requires building GCC with java support (deprecated starting with GCC 7.x), then going over some odd mix of GNU classpath and jamvm, and then bootstrapping JDK 6, then 7, then 8. this is a huge task, and it's asked way too much for a hobby distribution such as [sabotage linux](https://github.com/sabotage-linux/sabotage) just in order to build a build system which is required to build stuff like google tensorflow. in fact, i have successfully avoided so far to bootstrap JAVA which i personally view as a zombie from the past just like Adobe Flash (TM) that nobody should be using anymore.

### Feature requests: what underlying problem are you trying to solve with this feature?

> I want to build google tensorflow from source on a source-based linux distro without JAVA toolchain, yet this can't be done due to the choice of bazel to require JAVA.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Use a linux system without glibc and without pre-built java binaries.

### What operating system are you running Bazel on?

> Sabotage Linux based on MUSL libc

### What's the output of `bazel info release`?

> N/A

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> N/A
### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> N/A

###  Have you found anything relevant by searching the web?

> No.

### Any other information, logs, or outputs that you want to share?

> No.

**Comment by rofl0r** [comment]
another aspect is that a full JAVA install is huge, taking up more than 100MB on a harddrive. this is hardly justifiable for a build system which one uses to translate a couple .c files into object files. compare to GNU make which can be bootstrapped on any OS with nothing but a POSIX compliant shell and a C compiler and then takes up like 1-2 MB MAX.

**Comment by jbduncan** [comment]
> JAVA is a proprietary product...

I _think_ that's arguable? OpenJDK has been a thing for I don't know how long now, but years at least. :thinking: 

> ...and it is almost impossible to bootstrap from source.

Hmm. I understand that _lots_ of other programming languages also suffer from this problem. I could be wrong about this, but I recall that languages like Go, Rust and Kotlin also require earlier-version binaries to build current/future ones.

> Doing so requires building GCC with java support (deprecated starting with GCC 7.x), then going over some odd mix of GNU classpath and jamvm, and then bootstrapping JDK 6, then 7, then 8. this is a huge task...

This I won't argue. https://bootstrappable.org/projects.html describes this problem in further detail.

> in fact, i have successfully avoided so far to bootstrap JAVA which i personally view as a zombie from the past just like Adobe Flash (TM) that nobody should be using anymore.

I acknowledge your view on this. :)

> another aspect is that a full JAVA install is huge, taking up more than 100MB on a harddrive

May I question this? I don't think large install sizes has been a real problem for a long time, given that hard drives with 500GB+ are reasonably affordable... :thinking:

**Comment by jbduncan** [comment]
May I also add that just to migrate away from Java to some other platform will _probably_ take many, many man-hours, to put it mildly. :)

**Comment by rofl0r** [comment]
>>    JAVA is a proprietary product...

>I think that's arguable? OpenJDK has been a thing for I don't know how long now, but years at least. 

I seem to recall google recently lost the lawsuit against oracle?

>>    ...and it is almost impossible to bootstrap from source.

> Hmm. I understand that lots of other programming languages also suffer from this problem. I could be wrong about this, but I recall that languages like Go, Rust and Kotlin also require earlier-version binaries to build current/future ones.

yes, this is becoming a really annoying problem. out of this list, only go can be bootstrapped in a reasonable amount of time/work. one of the worst cases is haskell's GHC.

> This I won't argue. https://bootstrappable.org/projects.html describes this problem in further detail.

hey, that's a nice link! thanks :+1: 

>>    another aspect is that a full JAVA install is huge, taking up more than 100MB on a harddrive

> May I question this? I don't think large install sizes has been a real problem for a long time, given that hard drives with 500GB+ are reasonably affordable... 

these days laptops usually ship with 256 GB SSD. but install sizes that big are also a problem for VMs (i just installed openjdk-8-jre in an ubuntu vm and it took 435MB). that's quite a huge cost for a component you need only for a single purpose and imo it's not justified for a multi-purpose build system (if the build system would only target java code like maven, i wouldn't mind, as the consumer would need java anyway).

> May I also add that just to migrate away from Java to some other platform will probably take many, many man-hours, to put it mildly. :)

When i wrote this i wasn't aware yet that basically the entire project is written in Java. But i do think anyway that the issues i touch on are legit.

**Comment by jbduncan** [comment]
> I seem to recall google recently lost the lawsuit against oracle?

Maybe I'm naive, but I don't (yet?) see any negative impact on the copyright-ability of APIs or the Java world in general as a result of the lawsuit.

And maybe I'm too hopeful, but it looks to me that the EFF are working to reverse the decision, from what I skimmed over at https://www.eff.org/cases/oracle-v-google.

But all this said, I am not a lawyer, so I really have next to no idea what I'm talking about. :)

> these days laptops usually ship with 256 GB SSD. but install sizes that big are also a problem for VMs (i just installed openjdk-8-jre in an ubuntu vm and it took 435MB). that's quite a huge cost for a component you need only for a single purpose and imo it's not justified for a multi-purpose build system (if the build system would only target java code like maven, i wouldn't mind, as the consumer would need java anyway).

Hmm... I don't have any thoughts here, other than that you might be interested in [Meson](https://github.com/mesonbuild/meson), an alternative build system that looks kind of similar to Bazel, but which is implemented in Python and is apparently [used by people like GNOME](http://mesonbuild.com/Users.html).

**Comment by jbduncan** [comment]
> When i wrote this i wasn't aware yet that basically the entire project is written in Java. But i do think anyway that the issues i touch on are legit.

Sure. But unless someone on the Bazel team has something to add to all this, it's not clear to me that these issues could reasonably be tackled by the Bazel team...

_Maybe_ with Google's and Oracle's combined resources, issues like the Oracle JDK/OpenJDK's installation size and bootstrapping the JVM from source could be fixed. But I'm assuming that (1) organisations like Eclipse OpenJ9 and GraalVM haven't already done things to improve things on those fronts with their respective JVM implementations, and (2) the Oracle v. Google lawsuit isn't going to completely deter Google from investing in Java.

Really, though, I'm way out of my league here discussing all this, so I'm personally going to wait until someone from the Bazel team responds to this issue or otherwise triages it. :)

**Comment by jbduncan** [comment]
Oh, of course I forget that as of Java 9, Java has both a module system (the JPMS) and `jlink`, which when used together can create slimmed-down Java binaries. So if/when Bazel gets around to modularising its code base, the size issue should be significantly reduced @rofl0r.

**Comment by buchgr** [comment]
We are aware that binary size is a problem for some users. We are experimenting with various ways to reduce the JDK dependency in size (modules) as well as building a static binary (Graal). The later one sounding very attractive to me, because it also eliminates dead code from third party dependencies. Some of the points you two are raising are legit and rest assured that we are thinking about/working on possible improvements there.

That being said, we always love to hear constructive ideas to improve the situation. The use of offensive language @rofl0r is none of them, so I will close this issue. Feel free to open a new issue in a more constructive setting.

**Comment by rofl0r** [comment]
"sucks" is considered offensive too these days ? if so i can change the title of the issue, and you could reopen it, @buchgr 
note that it's almost impossible not to offend anybody nowadays, so the best option is to stop caring...

**Comment by buchgr** [comment]
FYI https://docs.google.com/document/d/1Igmv-2GfXkoVFWTXvBYPeniQom8nLAwzqzridDlBIS4

**Comment by jbduncan** [comment]
Cool, thanks for sharing this design document @buchgr! :+1:
