### ISSUE TITLE
cc_proto_library unusable with -Werror in CROSSTOOL

### ISSUE THREAD

**Issue by RNabel** [bazelbuild/bazel#5466]
### Description of the problem / feature request:

Suppress all C++ compilation warnings when compiling the generated C++ code from `.proto` files or allow passing of `copts` to the `cc_proto_library` (related: #4446).

### Feature requests: what underlying problem are you trying to solve with this feature?

The `cc_proto_library` compiles C++ code without allowing copts to be set, the generated C++ code [is known](https://github.com/google/protobuf/issues/719) to produce C++ compilation warnings. 

If a custom `CROSSTOOL` sets strict error flags it makes `cc_proto_library` completely unusable.

Our `CROSSTOOL` for example sets:
```
  compiler_flag: "-Wall"
  compiler_flag: "-Wextra"
  compiler_flag: "-Wpedantic"
  compiler_flag: "-Werror"
```
and we are not prepared to ignore, for example, `unused-parameters` warnings.

The recommendation made by a protobuf maintainer is to make sure that "the protos are organized in a separate lib and compile them without warnings" ([source](https://github.com/google/protobuf/issues/719#issuecomment-285788821)). This is currently impossible.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Clone: https://github.com/cgrushko/proto_library

Run `bazel build src:person_cc_proto --copt="-Werror -Weverything"` to simulate a strict `CROSSTOOL`.

### What operating system are you running Bazel on?

MacOS.

### What's the output of `bazel info release`?

`bazel 0.14.0`

###  Have you found anything relevant by searching the web?

Comment mentioning a series of protobuf issues re generated code: https://github.com/google/protobuf/issues/3128#issuecomment-351180102

Bazel `cc_proto_library` should support `cc_library` parameters: #4446 

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by rongjiecomputer** [comment]
I want to ask for `defines` in `cc_proto_library` too in addition to `copts`.

One Tensorflow's proto file defines enum values as `NEAR` and `FAR`, but it will conflict with files that include the generated header and `windows.h` because `windows.h` defines macros named `NEAR` and `FAR` too if `NOGDI` is not defined.

Adding `-DNOGDI` to all other targets depending on this `cc_proto_library` will work, but it will be easier if I can just add `defines = ["NOGDI"]` in this `cc_proto_library`.

**Comment by RNabel** [comment]
You may want to add a comment about adding `defines` to https://github.com/bazelbuild/bazel/issues/4446.

**Comment by RNabel** [comment]
@cgrushko (since you wrote parts of the `cc_proto_library`) would you mind TAL and commenting on a) current plans to improve the `cc_proto_library`, b) what your preferred approach to this issue is, and c) whether https://github.com/bazelbuild/bazel/pull/5467 has any chance of being accepted?

Sorry for directly pinging you, but it would be really awesome if this could be clarified :)

**Comment by cgrushko** [comment]
Hey, I unfortunately no longer work on Bazel.
java_proto_library has a similar situation, and perhaps @cushon remembers
what we do there.
@lberki, can you route?

**Comment by cushon** [comment]
> java_proto_library has a similar situation

We have some logic to pass additional javac flags to all proto compilations.

I'm not necessarily recommending this approach for c++, but it might be an option.

https://github.com/bazelbuild/bazel/blob/178e6cc5dd31a8b9748f9263eea6bcba5f2c7f31/tools/jdk/default_java_toolchain.bzl#L47

https://github.com/bazelbuild/bazel/blob/1d49184b071b281c83939416d7eead671729c8b5/src/main/java/com/google/devtools/build/lib/rules/java/proto/ProtoJavacOpts.java#L45

**Comment by hlopko** [comment]
Current status: protoc should not generate warning triggerring code (https://github.com/protocolbuffers/protobuf/issues/4628#issuecomment-470446302). Lowering the priority of this issue to p4.

**Comment by hlopko** [comment]
Actually, there's nothing actionable for us here AFAIU. Therefore I'll close this issue. Please ping https://github.com/protocolbuffers/protobuf/issues/4628 to make sure it will be paid attention to.
