### ISSUE TITLE
0.15.0 breaks debian package creation, _pkg_tar_impl broken?

### ISSUE THREAD

**Issue by nevion** [bazelbuild/bazel#5471]
### Description of the problem:

```bazel build scripts/packages/debian/bazel-debian``` results in the following error on 0.15.0 ( 2ff8c5fd919ad7316d06c6303e8d7b51315d4c61 )

```
ERROR: /home/jason/bazel/scripts/packages/debian/BUILD:20:1: in _real_pkg_tar rule //scripts/packages/debian:bazel-rc: 
Traceback (most recent call last):
	File "/home/jason/bazel/scripts/packages/debian/BUILD", line 20
		_real_pkg_tar(name = 'bazel-rc')
	File "/home/jason/bazel/tools/build_defs/pkg/pkg.bzl", line 82, in _pkg_tar_impl
		ctx.actions.run_shell(command = ("%s --flagfile=%s" % ...)), <5 more arguments>)
unexpected keyword 'tools', in method run_shell(string command, list inputs, list tools, list outputs, string mnemonic, bool use_default_shell_env) of 'actions'
ERROR: Analysis of target '//scripts/packages/debian:bazel-debian' failed; build aborted: Analysis of target '//scripts/packages/debian:bazel-rc' failed; build aborted
INFO: Elapsed time: 0.325s
FAILED: Build did NOT complete successfully (0 packages loaded)
```

It looks like something broke with the way run_shell accepts the tools argument.  The build command works when using on master ( e07a0b8027665e0c02f980149ee4c26eb5543e3f ) and tagged 0.14.1.

**Comment by mhlopko** [comment]
CC @laurentlb to decide if this warrants a patch release.

**Comment by mhlopko** [comment]
Pls @laurentlb add appropriate labels and raise priority if yes.

**Comment by laurentlb** [comment]
ping @tomlu

**Comment by tomlu** [comment]
The version of bazel used to build bazel is too old if it doesn't have 'tools'. I think I added tools one bazel version before I added the incompatible flag that forced the change to pkg_tar.

**Comment by nevion** [comment]
thought I had updated bazel prior to attempting the build but building 15.2 against 15.2 worked
