### ISSUE TITLE
https://www.bazel.build/roadmaps/configuration.html is missing links from its source

### ISSUE THREAD

**Issue by cjhopman** [bazelbuild/bazel#5472]
https://docs.google.com/document/d/1p7pdEwqnLOC-ATl-FdyHBJdk4Ae-5GzAYDvpJeMh4tU/edit?ts=5ac517b9# has been deprecated and replaced by https://www.bazel.build/roadmaps/configuration.html but the latter is missing a lot of the links to supporting information that is in the source (ex. https://docs.google.com/document/d/1vc8v-kXjvgZOdQdnxPTaV0rrLxtP2XwnD2tAZlYJOqw/edit#heading=h.wn5pcmdb5tnm).

https://www.bazel.build/designs/index.html also does not contain these other documents.

It would be really helpful to be able to reach this more detailed information in some way (outside of digging through the mailing list).

**Comment by gregestren** [comment]
Hi Chris,

All the original links should be in the new roadmap, although maybe they're not as easy to see. For example:

Normal look:
![link1](https://user-images.githubusercontent.com/5130366/42043588-cdfbab66-7ac4-11e8-84a5-b1db311f86fb.png)

Hover mouse pointer:
![link3](https://user-images.githubusercontent.com/5130366/42043600-d5f3ed9c-7ac4-11e8-9a37-f0451400587d.png)

Can you verify there are actual links missing?

About the design document registry, @jin  and I and a few others agree we need something better than https://www.bazel.build.designs/index.html. First and foremost we need a clear repository for designs that's more discoverable than wading through bazel-discuss emails. @jin is pushing a proposal for that right now: do we have a tracking issue for that?

**Comment by jin** [comment]
Thanks for the ping @gregce @mhlopko!

Yep, I have a proposal to create a repository to index links to published proposals. That should improve discoverability of the docs. I will make that document public in a bit and update here.

**Comment by cjhopman** [comment]
Aha, thank you. I'm just unable to understand how to use links I guess.

I've more carefully looked over the new roadmap and I think it does have all the links.

**Comment by jin** [comment]
@cjhopman We just launched an index for the documents: https://github.com/bazelbuild/proposals
