### ISSUE TITLE
Windows: Include checking failed when external repository name contains upper case

### ISSUE THREAD

**Issue by monamimani** [bazelbuild/bazel#5485]
### Description of the problem / feature request:
I am trying to add the lib glm as an external repository but Bazel gives me undeclared inclusion error but if I build it separetly ( in an other workspace) with the same build script it works.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

My folder structure

glmExtBuild
---- WORKSPACE
---- externals
-------- glm.BUILD

This is my WORKSPACE file
```
new_http_archive(
  name = "glmExt",
  url = "https://github.com/g-truc/glm/archive/0.9.9.0.tar.gz",
  sha256 = "514dea9ac0099dc389cf293cf1ab3d97aff080abad55bf79d4ab7ff6895ee69c",
  strip_prefix = "glm-0.9.9.0",
  build_file = "externals/glm.BUILD",
)
```

This is my glm.BUILD file
```
package(default_visibility = ["//visibility:public"])
cc_library(
  name= "glm",
  defines= ["GLM_ENABLE_EXPERIMENTAL", "GLM_FORCE_RADIANS", 
  "GLM_FORCE_DEPTH_ZERO_TO_ONE"],
  srcs=glob(["glm/**/*.cpp"]) + ["glm/detail/_fixes.hpp"],
  hdrs=glob(["glm/**/*.hpp"])+glob(["glm/**/*.h"]),
  includes = [".", "glm"],
  textual_hdrs = glob(["glm/**/*.inl"]),
  visibility = ["//visibility:public"],
)
```
And this is the errors that I get when I run

> bazel build @glmExt//:glm --verbose_failures --sandbox_debug
> ERROR: C:/users/...../external/glmExt/BUILD.bazel:121:1: undeclared inclusion(s) in rule '@glmExt//:glm':
> this rule is missing dependency declarations for the following files included by 'external/glmExt/glm/detail/glm.cpp': 
> 'external/glmext/glm/detail/_fixes.hpp'
> 'external/glmext/glm/detail/setup.hpp'
> 'external/glmext/glm/simd/platform.h'
> 'external/glmext/glm/fwd.hpp'
> 'external/glmext/glm/detail/setup.hpp'
> 'external/glmext/glm/detail/type_int.hpp'
> 'external/glmext/glm/detail/setup.hpp'
> 'external/glmext/glm/detail/type_float.hpp'
> ...

The working case:

My folder structure

glmBuild2
---- WORKSPACE
---- BUILD
---- glmSrc
-------- https://github.com/g-truc/glm/archive/0.9.9.0.tar.gz extracted here

My WORKSPACE file is empty

And this is my BUILD file
```
package(default_visibility = ["//visibility:public"])
cc_library(
  name= "glm",
  defines= ["GLM_ENABLE_EXPERIMENTAL", "GLM_FORCE_RADIANS", "GLM_FORCE_DEPTH_ZERO_TO_ONE"],
  srcs=glob(["glmSrc/glm/**/*.cpp"]) + ["glmSrc/glm/detail/_fixes.hpp"],
  hdrs=glob(["glmSrc/glm/**/*.hpp"])+glob(["glmSrc/glm/**/*.h"]),
  includes = ["glmSrc"],
  textual_hdrs = glob(["glmSrc/glm/**/*.inl"]),
  visibility = ["//visibility:public"],
)
```

### What operating system are you running Bazel on?

windows

### What's the output of `bazel info release`?

> release 0.15.0

I just updated bazel to 0.15.0 and it still doesn't work ( aka, it was not working in 0.14.0)

###  Have you found anything relevant by searching the web?

Nothing really, I would like to know more about the check of the include algorithm but i couldn't find anything. I can only print the result of the glob but I couldn't find a way to ask bazel what it actually has for its hdrs, srcs,...

### Any other information, logs, or outputs that you want to share?

I asked the question on stackoverflow too but I have no solution for now.
https://stackoverflow.com/questions/51053215/why-do-i-get-undeclared-inclusion-error-when-using-the-lib-as-external-library

**Comment by mhlopko** [comment]
ouch

**Comment by monamimani** [comment]
Thanks I renamed the new_http_archive name to glmext and it works.
Thanks alot!
