### ISSUE TITLE
Remote caching docs need updating post-0.15.0

### ISSUE THREAD

**Issue by drigz** [bazelbuild/bazel#5488]
The docs at https://github.com/bazelbuild/bazel/commits/master/site/docs/remote-caching.md still suggest using:

```
build --spawn_strategy=remote --genrule_strategy=remote
build --strategy=Javac=remote --strategy=Closure=remote
build --remote_http_cache=http://replace-with-your.host:port
```

but the v0.15.0 release notes say:

```
 - The --experimental_remote_spawn_cache flag is now enabled by
    default, and remote caching no longer needs --*_strategy=remote
    flags (it will fail if they are specified).
```

Additionally, the help for --experimental_remote_spawn_cache is unhelpful (from `bazel help build --long`):

```
  --[no]experimental_remote_spawn_cache (a boolean; default: "false")
    Whether to use the experimental spawn cache infrastructure for remote 
    caching. Enabling this flag makes Bazel ignore any setting for 
    remote_executor.
      Tags: no_op
```

"default: false" combined with the description appears to contradict the release notes, until you notice the `Tags: no_op` at the bottom.

### What's the output of `bazel info release`?

v0.15.0

**Comment by buchgr** [comment]
I have a change pending to update the docs.
