### ISSUE TITLE
Proper way to match ios_application provision_profile

### ISSUE THREAD

**Issue by yugiohatemu** [bazelbuild/bazel#549]
Is there a way to specify 
provisioning_profile = "iOS Team Provisioning Profile: *", 

like xcodebuild specify exportProvisionProfile "iOS Team Provisioning Profile: *" that map to correct provision profile by itself

Because bazel keeps complaining about * sign.

**Comment by damienmg** [comment]
@c-parsons @Aragos can we provide an answer to that user? Maybe document it?

**Comment by c-parsons** [comment]
Not currently - I'm unfamiliar with the wildcard method of specifying provisioning profile that you've alluded to, but we currently require provisioning_profile to be an explicitly defined and resolvable artifact.

**Comment by c-parsons** [comment]
At this point we explicitly require you specify a label to a .mobileprovision file with the provisioning_profile attribute, and it's documented as such.

I don't see much value in alternatives -- implicit auto-detected dependencies are a thing we generally want to avoid.
