### ISSUE TITLE
Bazel head can no longer be compiled with any version of bazel other than 0.15.0

### ISSUE THREAD

**Issue by nlopezgi** [bazelbuild/bazel#5493]
### Description of the problem / feature request:
Starting with https://github.com/bazelbuild/bazel/commit/1d3b6c144634b18b918c438ca042a16af8c901ff it is no longer possible to build bazel head with any version of bazel other than 0.15.0

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Install older version of bazel:
wget --no-verbose https://releases.bazel.build/0.14.1/release/bazel-0.14.1-installer-linux-x86_64.sh -O /tmp/bazel-installer.sh
chmod +x /tmp/bazel-installer.sh
/tmp/bazel-installer.sh

Clone bazel head:
git clone https://github.com/bazelbuild/bazel.git

Build bazel:
bazel build //src:bazel --spawn_strategy=standalone

### What operating system are you running Bazel on?
Reproduced issue running Bazel inside container with Xenial, Trusty or Jessie base

### What's the output of `bazel info release`?
Build label: 0.14.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 8 12:17:35 2018 (1528460255)
Build timestamp: 1528460255
Build timestamp as int: 1528460255
.
### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
4e580949c946d48bb9b6f193424badffe1d2eb20

**Comment by dslomov** [comment]
@nlopezgi does this cause any issues? I am closing this, but let us know if you have a strong reason for continuing support of building with 0.14.

**Comment by nlopezgi** [comment]
Thanks for the clarification. I don't have a strong reason to need continuing support for building with 0.14.
