### ISSUE TITLE
Bug in MSVC crosstool, missing action_config.

### ISSUE THREAD

**Issue by liberatix-samir** [bazelbuild/bazel#5495]
> - Stackoverflow topic: https://stackoverflow.com/questions/50967174/cant-build-a-project-package-using-boost-iostream-from-bazel/51057943#51057943

### Description of the problem / feature request:
I am using https://github.com/nelhage/rules_boost in a bazel project, everything is working fine except when I try to use boost/iostream. The problem occurs on windows 10, and not on linux. boost/iostream depends on zlib. The error I get when trying to build is the fallowing: 
```
ERROR: .../external/net_zlib_zlib/BUILD.bazel:6:1: in cc_library rule @net_zlib_zlib//:zlib: Expected action_config for 'preprocess-assemble' to be configured
ERROR: Analysis of target '.../storage:storage' failed; build abo
```

### Feature requests: what underlying problem are you trying to solve with this feature?

I want to be able to use boost/iostreams from the linked repository on windows.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Add the fallowing to a WORKSPACE file
```
git_repository(
  name = "com_github_nelhage_rules_boost",
  commit = "25e4da1141c56c207a5692b6d3c2aeeffc656fa4",
  remote = "https://github.com/nelhage/rules_boost",
  # path = "third_party/com_github_nelhage_rules_boost",
)

load("@com_github_nelhage_rules_boost//:boost/boost.bzl", "boost_deps")
boost_deps()
```
 and run 
```
bazel build @boost//:iostreams
```

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 0.14.1 
Had the same problem in 0.10.0 and 0.14.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/liberatix/automaton-core.git
3c17c37d029db263151a5b216fec8030600927be
1cbcf9ba01ff6e6a37324119ae1dc3d57d7f2631

###  Have you found anything relevant by searching the web?

Here is the issue where we discuses the problem in the linked library
https://github.com/nelhage/rules_boost/issues/68

### Any other information, logs, or outputs that you want to share?

At one point I was getting different error: 
```
ERROR: C:/bt/external/boost/BUILD.bazel:698:1: no such package '@net_zlib_zlib//': C:/bt/external/net_zlib_zlib (Permission denied) and referenced by '@boost//:iostreams'
ERROR: Analysis of target '@boost//:iostreams' failed; build aborted: no such package '@net_zlib_zlib//': C:/bt/external/net_zlib_zlib (Permission denied)
```

When checking the output directory, the zlib folder is empty.

**Comment by mhlopko** [comment]
We need to add `preprocess-assemble` to the msvc crosstool...

**Comment by meteorcloudy** [comment]
@liberatix-samir I have a change to add action config for `preprocess-assemble`. But I also found [the assemble file](https://github.com/nelhage/rules_boost/blob/master/BUILD.zlib#L11) belongs to zlib just doesn't compile on Windows.

I think the solution could be updating [the BUILD file for zlib](https://github.com/nelhage/rules_boost/blob/master/BUILD.zlib#L11) to exclude that assemble file.
See the zlib.BUILD from TensorFlow, it works on both Linux and Windows.
https://github.com/tensorflow/tensorflow/blob/master/third_party/zlib.BUILD
