### ISSUE TITLE
Can't find jni.h if target not declared at the root of workspace

### ISSUE THREAD

**Issue by jirkadanek** [bazelbuild/bazel#5497]
### Description of the problem:

I am having a problem I first saw described at https://stackoverflow.com/questions/49824574/cant-find-jni-h-if-target-not-declared-at-the-root-of-workspace.

If I want to build a cc_library which depends on `jni.h`, I either have to put the target in a BUILD file in the directory of the top level project WORKSPACE, or use workaround from the SO question.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

    git clone git@github.com:mhlopko/bazel-jni-example.git
    bazel build // ... # this passes just fine

    mkdir nested
    mv BUILD *.cc *.h *.java nested/
    bazel build //...

```
............
WARNING: /home/jdanek/Work/repos/bazel-jni-example/nested/BUILD:3:12: in srcs attribute of cc_library rule //nested:main-jni-lib: please do not import '@local_jdk//:include/jni.h' directly. You should either move the file to this package or depend on an appropriate rule there
WARNING: /home/jdanek/Work/repos/bazel-jni-example/nested/BUILD:3:12: in srcs attribute of cc_library rule //nested:main-jni-lib: please do not import '@local_jdk//:include/linux/jni_md.h' directly. You should either move the file to this package or depend on an appropriate rule there
INFO: Analysed 3 targets (14 packages loaded).
INFO: Found 3 targets...
ERROR: /home/jdanek/Work/repos/bazel-jni-example/nested/BUILD:1:1: C++ compilation of rule '//nested:main-jni-lib' failed (Exit 1)
nested/Main.cc:1:10: fatal error: jni.h: No such file or directory
 #include <jni.h>
          ^~~~~~~
compilation terminated.
INFO: Elapsed time: 3.842s, Critical Path: 0.26s
FAILED: Build did NOT complete successfully
```

### What operating system are you running Bazel on?

Linux, NixOS 18.03, x86_64

### What's the output of `bazel info release`?

release 0.12.0- (@non-git)

(whoops) but same thing happens with clensing all with bazel clean, bazel shutdown, upgrading, and

```
$ bazel info release
release 0.15.0- (@non-git)

$ bazel build //...
DEBUG: /home/jdanek/.cache/bazel/_bazel_jdanek/0ce7434c4d8b52d94187c164d9bd419c/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5: 
Auto-Configuration Warning: Cannot find gcov or GCOV; either correct your path or set the GCOV environment variable
WARNING: /home/jdanek/Work/repos/bazel-jni-example/nested/BUILD:3:12: in srcs attribute of cc_library rule //nested:main-jni-lib: please do not import '@local_jdk//:include/jni.h' directly. You should either move the file to this package or depend on an appropriate rule there
WARNING: /home/jdanek/Work/repos/bazel-jni-example/nested/BUILD:3:12: in srcs attribute of cc_library rule //nested:main-jni-lib: please do not import '@local_jdk//:include/linux/jni_md.h' directly. You should either move the file to this package or depend on an appropriate rule there
INFO: Analysed 3 targets (15 packages loaded).
INFO: Found 3 targets...
ERROR: /home/jdanek/Work/repos/bazel-jni-example/nested/BUILD:1:1: C++ compilation of rule '//nested:main-jni-lib' failed (Exit 1)
nested/Main.cc:1:10: fatal error: jni.h: No such file or directory
 #include <jni.h>
          ^~~~~~~
compilation terminated.
INFO: Elapsed time: 8.032s, Critical Path: 1.95s
INFO: 1 process: 1 worker.
FAILED: Build did NOT complete successfully
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

From checkout of nixpkgs with applied https://github.com/NixOS/nixpkgs/pull/42735

    nix-env -i bazel -f nixpkgs

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

It's from 0.15.0 zipped source release from github

###  Have you found anything relevant by searching the web?

https://stackoverflow.com/questions/49824574/cant-find-jni-h-if-target-not-declared-at-the-root-of-workspace

**Comment by lfpino** [comment]
Assigning to @mhlopko for triage.

**Comment by mhlopko** [comment]
The principled fix would be to change header targets in https://source.bazel.build/bazel/+/6b8c7ca48e9e48a9906c031346dc4a924b7ef559:src/main/tools/jdk.BUILD into `cc_import`s. For that we would need to add `incldues` attribute to `cc_import`. And we don't want to do it before https://github.com/bazelbuild/bazel/issues/4570 is fixed and cc_import is migrated to Skylark.

In the meantime, the workaround is to change `includes` attribute in `main-jni-lib` from `includes = [ "external/local_jdk/include", "external/local_jdk/include/linux" ],
` to `includes = [ "../external/local_jdk/include", "../external/local_jdk/include/linux" ],`

Dekujeme do Brna :)
