### ISSUE TITLE
Can't easily refer to osx_gcc_wrapper.sh in another CROSSTOOL file

### ISSUE THREAD

**Issue by kayasoze** [bazelbuild/bazel#550]
With the recent changes to internalize Bazel's default `CROSSTOOL` file, I've now defaulted to using a site-specific `CROSSTOOL` file using `--crosstool_top`.  This allows users to build using settings beyond Bazel's defaults, like C++14. 

I'd like to build OS X binaries using my own `CROSSTOOL`, but `osx_gcc_wrapper.sh` is expected to be located relative to the top of my `CROSSTOOL` tree, and I don't want to store my `CROSSTOOL` with Bazel's sources.  Is there a way to specify that it's relative to Bazel's own tree?  Is `@bazel_tools` the solution?  For now I'm using a symlink.

**Comment by ulfjack** [comment]
I don't think there is a way to do that right now, but I haven't looked deeply. There's https://bazel-review.googlesource.com/#/c/2200/, where we're discussing how to allow more complete file / directory references in CROSSTOOL files, and we could extend that to cover the tools paths as well.

Alternatively, you could copy or symlink the file into the right location.

**Comment by kayasoze** [comment]
I've been using a symlink for now.  That works well enough.

**Comment by aiuto** [comment]
Closing as obsolete because there is a workaround and no update in 6 years.
