### ISSUE TITLE
Better document support for `javac -h` native header file generation in java_library rule

### ISSUE THREAD

**Issue by jirkadanek** [bazelbuild/bazel#5503]
### Description of the problem / feature request:

To the best of my knowledge, native header generation is not mentioned in bazel documentation anywhere. IMO it is important feature for JNI and should be explained.

edit: Actually, one page: https://docs.bazel.build/versions/master/skylark/lib/java_output_jars.html#native_headers

I found it by searching in bazel souces for "generated native header", then "createCompileAction" and finally "nativeHeaderOutput". Then I started writing a feature request for option to enable it, and then I looked into one of my `.params` file and saw it there already.

### Feature requests: what underlying problem are you trying to solve with this feature?

I want to generate JNI headers, I want my solution to work on Java 10+, where `javah` is no longer available, and I want to minimize external dependencies and my own effort.

###  Have you found anything relevant by searching the web?

For the JNI usecase, I only found advice about writing a genrule around javah. Not applicable for newer Java. https://groups.google.com/forum/#!searchin/bazel-discuss/javah%7Csort:date esp. https://groups.google.com/forum/#!topic/bazel-discuss/vMmw370iaR0

### Any other information, logs, or outputs that you want to share?
Implementation commit https://github.com/bazelbuild/bazel/commit/3864a45afa368473a4a6a90d69edb48cb67d367a

I am honestly surprised the native headers are being generated by default, also in light of https://github.com/bazelbuild/bazel/commit/8d061b85a91e70df10d2f20f81217386539560c1

**Comment by jdanekrh** [comment]
This is how I am using it now. I had to write skylark rule to access the `-native-header.jar`, I did not figure out how to get to it from BUILD, using a `genrule` to extract it.

extension.bzl:

    def _impl(ctx):
    # https://github.com/bazelbuild/rules_scala/pull/286/files
    ctx.actions.run(
        inputs = [ctx.executable._zipper, ctx.attr.lib.java.outputs.native_headers],
        outputs = ctx.outputs.outs,
        executable = ctx.executable._zipper.path,
        arguments = ["vxf", ctx.attr.lib.java.outputs.native_headers.path, "-d", ctx.outputs.outs[0].dirname],
    )


    extract_native_header_jar = rule(
        implementation=_impl,
        attrs={
            "lib": attr.label(mandatory=True, single_file=True),
            "outs": attr.output_list(),
            # https://github.com/bazelbuild/bazel/issues/2414
            "_zipper": attr.label(executable=True, cfg="host", default=Label("@bazel_tools//tools/zip:zipper"), allow_files=True)
        },
        output_to_genfiles = True,
    )

BUILD:

    load(":extension.bzl", "extract_native_header_jar")

    extract_native_header_jar(
        name = "extract_headers",
        outs = ["org_apache_activemq_artemis_jlibaio_LibaioContext.h"],
        lib = ":artemis-native-java",
    )

    cc_binary(
        name = "libartemis-native-64.so",
        srcs = [
            "src/main/c/exception_helper.h",
            "src/main/c/org_apache_activemq_artemis_jlibaio_LibaioContext.c",
            ":org_apache_activemq_artemis_jlibaio_LibaioContext.h",
        ],
        includes = ["."],  # For jni headers.
        linkshared = 1,
        deps = [
            "//:jni_headers",  # workaround for https://github.com/bazelbuild/bazel/issues/5502
            "@libaio//:lib",
        ],
    )

    java_library(
        name = "artemis-native",
        data = [":libartemis-native-64.so"],
        visibility = ["//visibility:public"],
        exports = [
            ":artemis-native-java",
            ":libartemis-native-64.so",
        ],
        runtime_deps = [":libartemis-native-64.so"],  # this is probably excessive ...
    )

**Comment by lfpino** [comment]
Assigning to @lberki for triage.

**Comment by cushon** [comment]
Using skylark to access the native headers via `[JavaInfo].outputs.native_headers` and extract them is the recommended way to use the feature.

We have a `java_native_headers` rule similar to the `extract_native_header_jar` example above that could be open-sourced and documented.

**Comment by hcoona** [comment]
The snippets provided by @jirkadanek is broken now (bazel 4.0.0). Is there any suggested way to compile with the generated header files? @cushon @jin

**Comment by fmeum** [comment]
I added a [`jni_headers`](https://github.com/fmeum/rules_jni/blob/main/docs/rules.md#jni_headers) rule to [`rules_jni`](https://github.com/fmeum/rules_jni) that wraps the generated headers in a `CcInfo` for direct consumption by `cc_*` rules.
