### ISSUE TITLE
TensorFlow job in Bazel CI is red but only in Ubuntu 14.04

### ISSUE THREAD

**Issue by lfpino** [bazelbuild/bazel#5514]
The full log is in: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/330#f4d9112b-3525-45b1-a2c7-09bc95905c6d

Assigning to @meteorcloudy for diagnose and triage.

**Comment by lfpino** [comment]
Friendly ping @meteorcloudy, I also saw this today: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/332#ab7730f1-3a14-4351-ae65-1b99b4625e74

**Comment by meteorcloudy** [comment]
Thanks, I'll take a look today!

**Comment by meteorcloudy** [comment]
Found a useful error message:
```
external/com_github_googlecloudplatform_google_cloud_cpp/google/cloud/bigtable/internal/rowreaderiterator.h:57:44: error: ambiguous overload for 'operator*' (operand type is 'std::remove_reference<const google::cloud::v0::internal::optional<google::cloud::bigtable::v0::Row>&>::type {aka const google::cloud::v0::internal::optional<google::cloud::bigtable::v0::Row>}')
```

**Comment by meteorcloudy** [comment]
Filed an issue to TF: https://github.com/tensorflow/tensorflow/issues/20592

**Comment by jin** [comment]
This hasn't showed up in recent nightlies, I think we can close this now.
