### ISSUE TITLE
Unable to 'bazel run' a java_binary with a specified JAVA_HOME

### ISSUE THREAD

**Issue by bansalvinayak** [bazelbuild/bazel#5516]
### Description of the problem / feature request:

Unable to 'bazel run' a java_binary with a specified JAVA_HOME

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

 bazel run --host_javabase=:jdk8 --javabase=:jdk8 :hello_world

results in 
LAUNCHER ERROR: Rlocation failed on C:/openjdk/bin/java.exe, path doesn't exist in MANIFEST file

Relevant files (BUILD and HelloWorld.java)

package(default_visibility = ["//visibility:public"])
java_library(
    name = "hello_lib",
    srcs = glob(["*.java"]),
)

java_binary(
    name = "hello_world",
    main_class = "hello.HelloWorld",
    runtime_deps = [
        ":hello_lib",
    ],
)

java_runtime_suite(
  name = "jdk8",
  default = ":jdk8-default",
)
    
java_runtime(
  name = "jdk8-default",
  srcs = [],
  java_home = "C:/openjdk",
)

---

package hello;
public final class HelloWorld {
 public static void main(String[] args) throws Exception {
   System.out.println("Hello, world!");
 }
}

### What operating system are you running Bazel on?
Windows Server Core 1803

### What's the output of `bazel info release`?
release 0.13.0

###  Have you found anything relevant by searching the web?

After speaking with @jasharpe, 

I think there is a bug with the launcher
https://github.com/bazelbuild/bazel/blob/40f5a773e97d0e389838becd3fe0a8ab43853999/src/tools/launcher/launcher.cc#L145

If the path is absolute, we should return it regardless of whether the manifest file is empty or not

**Comment by bansalvinayak** [comment]
@laszlocsomor @meteorcloudy

**Comment by bansalvinayak** [comment]
Oh, i should add this setup needed an empty WORKSPACE file as well.

**Comment by meteorcloudy** [comment]
@bansalvinayak Thanks for reporting! You're right about the bug, I'll fix it soon!
