### ISSUE TITLE
How to create a tar package with some existed resource files

### ISSUE THREAD

**Issue by thincal** [bazelbuild/bazel#5518]
Hi,

I am trying to use the `pkg_tar` to achieve this goal, but it seems that the BUILD file is needed for the file specified in the `srcs`.

So is there any simple way to do this very simple thing ?

Thanks,
Song

**Comment by thincal** [comment]
From https://docs.bazel.build/versions/master/be/pkg.html#pkg_tar

```
srcs:

List of files, optionalFile to add to the layer.
A list of files that should be included in the docker image.
```

Why I can't add some files existed in the directory ? If yes, what's the correct way ?

Thanks very much.

**Comment by thincal** [comment]
it seems that only the files under the directory of this ` BUILD` file is allowed to added into `srcs`, outside files would be treated as the build target.

**Comment by lfpino** [comment]
Assigning to @aehlig for triage.

**Comment by aehlig** [comment]
I'm not sure, how the documentation can be improved to be easier to understand (besides the obvious https://bazel-review.googlesource.com/c/bazel/+/64731). Please reopen with suggestions.
