### ISSUE TITLE
Allow customizing "BUILD" as a package-specification file

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/bazel#552]
Most OS X installations have a case-sensitive filesystem, so "BUILD" is the same as "build". 

Some teams have directories/files named "build" in their projects, which poses a double challenge:
1. Bazel might choke on these directories/files.
2. Scripts could unintentionally damage Bazel's BUILD files.

At least as a transitionary-aid for other teams, it would be useful to customize the file-name that Bazel uses to define packages.

Suggestion: add a `WORKSPACE` rule to define a different file-name.

**Comment by adamhowardprice** [comment]
:+1: It is very common to have a `build` folder at the top level of an iOS or Android project for Xcode to put locally built artifacts and generated files. We make this assumption on our CI as well. 

I wonder why Bazel allows you to customize the location of a `BUILD` file for an external repo (via the `build_file` attr on a `git_repository`) but won't let you customize the `BUILD` file in the workspace root. 

It would be as simple as specifying in the `WORKSPACE` something like `workspace_build_file = "workspace.BUILD"`.

**Comment by damienmg** [comment]
I don't think that's a good idea. We will ends-up having different build file everywhere. We should instead do file type detection and not try to parse a directory as a build file :)

**Comment by cgrushko** [comment]
@damienmg the problem we ran into was the opposite - existing scripts (as well as Gradle, in its default configuration) were stepping on the BUILD files we wrote.

**Comment by adamhowardprice** [comment]
If the concern is that we will have different build files everywhere, maybe we could solve this problem by detecting build files by looking for files either called `BUILD` (as we do today) or `Buildfile` (similar to `Makefile`, `Gemfile`, etc). That seems unique enough that it won't be trampled by scripts, and also a familiar pattern for developers.

**Comment by adamhowardprice** [comment]
Alternatively, `Bazelfile`?

**Comment by damienmg** [comment]
SGTM BUILD.bazel ? (someone was proposing an extension to make it work outside).

**Comment by dmaclach** [comment]
Please don't reuse extensions that are already in use for different file types (i.e. please don't use .bzl).  BUILD.bld?

**Comment by davidzchen** [comment]
If we are adding an extension, I vote in favor of `BUILD.bazel`. Another benefit of this is that it is straightforward for people to say:

> build dot Bazel

Similarly, Gradle's build files are `build.gradle`.

**Comment by mightyguava** [comment]
I also need this while trying to migrate from `pants`, as it also uses BUILD files for the same purpose as `bazel` but with a different syntax...

**Comment by damienmg** [comment]
@katre @jhfield: Too many people reassigning this bug at the same time? :)

**Comment by katre** [comment]
I'm looking into it, I promise! :)

**Comment by katre** [comment]
Just as an update, work is in progress, I have a mostly working solution but there are a lot of tests to fix up as a result.

**Comment by mightyguava** [comment]
As a transitory aid, until this is done, I made a really simple script to patch Bazel https://github.com/UrbanCompass/bazel/blob/ucbuild/rename_to_ucbuild.sh. We managed to transition successfully from pants with a ~2 week overlap and then went back to the vanilla Bazel binary after.

**Comment by robertwb** [comment]
Has there been any decision as to what the extension/name of this BUILD file not named BUILD is going to be?

**Comment by katre** [comment]
The alternate name will be BUILD.bazel. I have the code for this change
mostly working and plan to pick it back up shortly.

**Comment by ixdy** [comment]
@katre any ETA? this is a pretty frustrating issue for us.

**Comment by katre** [comment]
@ixdy Sorry for the slow reply.

I have a change ready and in testing. There's some cleanup I need to do before I can start working to get it out, but it should be in review next week.

**Comment by venantius** [comment]
Chiming in from Airbnb eng -- we're looking to migrate off of Gradle as well as some of the other folks in this thread and we've run into this issue as well. Would love to see this fix released as soon as it's ready.

**Comment by katre** [comment]
I have just this evening submitted the fix for this issue. It should be pushed to GitHub in the next day or so and then be in the December release (presumably 0.4.2, but we will see what the version is).
