### ISSUE TITLE
Bazel does not work with Java 10

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#5521]
Java 9 is already EOL, and Oracle does not provide Java 9 downloads on its public page anymore.

On a OS X machine, Bazel bootstrap fails with:
```
-Xbootclasspath/p is no longer a supported option.
ion.
```

**Comment by cushon** [comment]
Bootstrapping with `./compile.sh` doesn't work with JDK 9 either. The only place a JDK newer than 8 is used currently is as the embedded and default host JDK.

And if you want a JDK 9 for testing you can still download one: http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase9-3934878.html.

**Comment by buchgr** [comment]
or from Azul :-) https://www.azul.com/downloads/zulu/zulu-mac/

**Comment by ulfjack** [comment]
Yes, I found a JDK 9 eventually. There's a longer story here. I found two bugs in OpenJDK as part of working on a personal project, and wanted to report them upstream. The instructions for filing a bug are to reproduce with the latest OpenJDK, for which I installed Jdk 10. Unfortunately, that then in turn broke my Bazel builds, which I only discovered after rewriting a significant part of my personal project due to changes in the standard libraries. Talk about Yak shaving.

**Comment by ulfjack** [comment]
(Anyway, I decided to downgrade to Jdk 8 for the time being. There's nothing compelling in Jdk 9 or 10 that I need for my personal project.)

**Comment by aiuto** [comment]
@philwo Do you think this issue is Team-EngProd or do you want me to take it in Team-Product

**Comment by dslomov** [comment]
I believe this is fully fixed now but cc @iirina to confirm

**Comment by iirina** [comment]
It does work. Closing.
