### ISSUE TITLE
The `pkg_rpm` rule does not generate an RPM with the version and release in the file name if the `version_file` or `release_file` args are used

### ISSUE THREAD

**Issue by aptbosox** [bazelbuild/bazel#5522]
### Description of the problem:
This `BUILD` file: 
```
load("@bazel_tools//tools/build_defs/pkg:rpm.bzl", "pkg_rpm")

pkg_rpm(
    name = "foo",
    spec_file = "foo.spec",
    version = "1",
    release = "1",
)
```
Generates:
```
bazel-bin/foo-1-1.all.rpm
bazel-bin/foo-all.rpm
bazel-bin/foo.rpm
```

But this `BUILD` file: 
```
load("@bazel_tools//tools/build_defs/pkg:rpm.bzl", "pkg_rpm")

pkg_rpm(
    name = "foo",
    spec_file = "foo.spec",
    version_file = "//data:version.txt",
    release = "1",
)
```
Only generates:
```
bazel-bin/foo-all.rpm
bazel-bin/foo.rpm
```

The resulting RPMs have the correct metadata, so the version file is being used correctly, but the rule is choosing not to generate a file that includes the version.

### Operating System

CentOS 7.3

### Output of `bazel info release`

```
$ bazel info release
release 0.15.0- (@non-git)
```

### How I installed Bazel

Installed via `yum` (https://docs.bazel.build/versions/master/install-redhat.html).

### Additional Info

From the looks of it, [this line](https://github.com/bazelbuild/bazel/blob/20a042faa91acf8db78684de9f38c4e628d61dd6/tools/build_defs/pkg/rpm.bzl#L125) is the culprit. the `outputs` implementation only looks at the `version` and `release` attributes, and does not consider the `version_file` and `release_file` attributes.

**Comment by lfpino** [comment]
Assigning to @katre for triage.

**Comment by katre** [comment]
I'll need to review, but I don't think this is actually possible. The pkg_rpm rule does not have access to file contents during the analysis phase, when the rule implementation is executed. Because of this, it cannot declare an output whose name is based on the contents of the file.

Do we need better documentation of this limitation in the pkg_rpm docs?

**Comment by aptbosox** [comment]
Gotcha, that makes sense. Better documentation for the rule would certainly help since it currently conveys the `version` and `version_file` attributes as essentially being equivalent. Thanks for looking into it.

**Comment by katre** [comment]
I'll take a look at the docs and see what can be done.
