### ISSUE TITLE
java_stub_template.txt as used in `kotlin_rules` does not work on windows.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/bazel#5523]
I shouldn't have tackled the windows issue at this point I thought it would a quick job. Anyhow the embedded classpath variable has not been resolved off the correct `RUNPATH`. 

[Here is how the rules expand the template](https://github.com/bazelbuild/rules_kotlin/blob/740b962803b0a128832c4970587cc8d26dc80546/kotlin/internal/utils.bzl#L178-L203)

I copied and adapted the underlying code from the scala rules removing stuff that I didn't think was needed. 

This might apply to the `scala_rules` as well although it wraps the script. I see the classpath variable is produced with a `":".join([...])` so its not windows compatible.

I updated the variables to include the following just in case. 

```
...
            "%needs_runfiles%": "1",
            "%runfiles_manifest_only%": "",
...
```

---

On a side note is the stub template available from one of the tool workspaces ? The scala and kotlin rules are retrieving it via `http_file`.

**Comment by lfpino** [comment]
Assigning to @iirina for triage.

**Comment by dslomov** [comment]
Please do not assign issues to more than one team.

**Comment by laszlocsomor** [comment]
rules_kotlin maintainers are planning to opensource Google's own Kotlin 1.3 rules.
I expect that if they find problems on Windows, they'll file bugs. 
So I'll close this bug now -- please reopen if it makes sense to.
