### ISSUE TITLE
Invocation ID should be printed when running with --remote_cache or --remote_executor

### ISSUE THREAD

**Issue by bergsieker** [bazelbuild/bazel#5524]
### Description of the problem / feature request:

When running with --bes_backend, the invocation ID is printed to the console. It should also be printed when either --remote_cache or --remote_executor is specified. 

### Feature requests: what underlying problem are you trying to solve with this feature?

The invocation ID is passed to the server via RequestMetadata when making RPCs. Depending on the server's implementation, it may be a useful identifier for searching server logs or other data while debugging failing builds.

**Comment by ifoox** [comment]
One possible workaround for users is to manually pass in a randomly generated UUID:
bazel ... --invocation_id=`uuidgen`
