### ISSUE TITLE
Bazel APT is missing "unzip" as a dependency

### ISSUE THREAD

**Issue by ocombe** [bazelbuild/bazel#5529]
### Description of the problem / feature request:

The instructions on https://docs.bazel.build/versions/master/install-ubuntu.html specify a list of dependencies to install if you install bazel using the binary installer, but no dependencies when you install with the APT repository.
I've found out that this APT package doesn't have `unzip` as a dependency. I installed bazel on windows WSL (ubuntu) and then tried to build a package. I got the following error:

```
ERROR: /home/ocombe/.cache/bazel/_bazel_ocombe/52a8f638481b31ca5db971758e63a64e/external/io_bazel_rules_webtesting/third_party/chromium/BUILD.bazel:25:1: Extracting ../org_chromium_chromium/file/chrome-linux.zip failed (Exit 127)
external/io_bazel_rules_webtesting/web/internal/extract.sh: line 20: unzip: command not found
```

It turns out that windows WSL (ubuntu) doesn't have `unzip` installed by default, and the bazel package on APT doesn't require it.
Can you either update the installation instructions or the dependencies of the package on APT?
Thanks!

### Feature requests: what underlying problem are you trying to solve with this feature?

Errors when installing bazel on a new machine via APT.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Install ubuntu on windows WSL, then install bazel following the ["Using Bazel custom APT repository" instructions](https://docs.bazel.build/versions/master/install-ubuntu.html#using-bazel-custom-apt-repository).

### What operating system are you running Bazel on?

Windows 10 WSL with Ubuntu

### What's the output of `bazel info release`?

Release 0.15.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
https://github.com/ocombe/angular.git
09222280249c6d76658c911740d8397a01029dba
b5a22546c1b48fcf79b57aed29fbd71ae4a619de
```

###  Have you found anything relevant by searching the web?

Yes, installing `unzip` manually works.

**Comment by lfpino** [comment]
Assigning to @laszlocsomor for triage.

**Comment by laszlocsomor** [comment]
@aehlig I suppose is more of domain expert than me
