### ISSUE TITLE
`bazel build //src:bazel` fails at HEAD because genrules look for make variables in `srcs` filenames

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel#5531]
### Description of the problem / feature request:

Bazel at head can't be built on my machine because `//src/main/java/com/google/devtools/build/lib:merge_licenses` is a genrule that consumes source files containing dollar signs in their filenames.

This behavior of genrule is not obvious, appears to be undocumented, and makes it very difficult to safely use `genrule` when the `srcs` attribute is derived from outputs of other rules.

```
$ bazel build //src:bazel
Starting local Bazel server and connecting to it...
................
ERROR: /Users/jmillikin/src/bazel/src/main/java/com/google/devtools/build/lib/BUILD:1374:11: in cmd attribute of genrule rule //src/main/java/com/google/devtools/build/lib:merge_licenses: '$1' syntax is not supported; use '$(1)' instead for "Make" variables, or escape the '$' as '$$' if you intended this for the shell
ERROR: Analysis of target '//src:bazel' failed; build aborted: Analysis of target '//src/main/java/com/google/devtools/build/lib:merge_licenses' failed; build aborted
```

The bad filename in this case is `third_party/java/jopt-simple/target/classes/joptsimple/BuiltinHelpFormatter$1.class`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ bazel build :hello_sha
ERROR: /Users/jmillikin/src/bazel-makevars/BUILD:5:11: in cmd attribute of genrule rule //:hello_sha: '$1world' syntax is not supported; use '$(1world)' instead for "Make" variables, or escape the '$' as '$$' if you intended this for the shell
ERROR: Analysis of target '//:hello_sha' failed; build aborted: Analysis of target '//:hello_sha' failed; build aborted

$ ls
BUILD            WORKSPACE        hello$1world.txt

$ cat BUILD 
genrule(
    name = "hello_sha",
    srcs = glob(["*.txt"]),
    outs = ["hello_sha.txt"],
    cmd = "shasum $(SRCS) > \"$@\"",
)
```

### What operating system are you running Bazel on?

MacOS 10.13.3

### What's the output of `bazel info release`?

I've verified this with `release 0.13.0` and `release 0.15.0`.

**Comment by lfpino** [comment]
Assigning to @lberki for triage.

**Comment by lberki** [comment]
The fact that source files with dollar signs in their names have this effect is unfortunate, but where does the the file you mention come from? `third_party/java/jopt-simple` does not have a subdirectory called `target` at HEAD and the last change to that directory was in 2017 December.

**Comment by jmillikin-stripe** [comment]
Hmm, that's a good question. I'd assumed those were coming from one of the Java build rules (I'm not very familiar with Java), but it looks like they're actually present on the filesystem.

If I delete them then `git status` doesn't change, and if I leave things alone for a while they come back (!!). These files must be coming from something local to my machine (maybe VS Code?).

Sorry for the noise, feel to close "working as intended" unless you think the dollar signs in filenames is enough to action.

**Comment by lberki** [comment]
Sigh. I wish I could say that it's a new thing, but it's a known issue without a resolution in sight :( So I'll close this as WAI.
