### ISSUE TITLE
non-existent //tools/defaults:BUILD appears in bazel query buildfiles

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#5533]
```
$ bazel info release
release 0.15.0
```

In the Angular repo:
```
$ bazel query "buildfiles(deps(set(//packages/core/test:test_web)))"
...
//tools/defaults:BUILD
```
but there is no such file.

Even in a empty repository, I can surprisingly 
```
bazel query "deps(//tools/defaults:BUILD)"
//tools/defaults:BUILD
```
so it seems there is something special about this path. This seems relevant: https://github.com/bazelbuild/bazel/blob/90e2b4b5e745fe2de9ca82bc8163c198e5be8ca9/src/main/java/com/google/devtools/build/lib/analysis/config/DefaultsPackage.java#L48
but I'm surprised that the synthetic file appears in query results.

As a result, `ibazel` prints a warning about watching the non-existent file:
```
Error watching file /usr/local/google/home/alexeagle/Projects/rules_nodejs/tools/defaults/BUILD
Error: no such file or directory
```

If this is WAI in Bazel, then maybe ibazel should filter out this particular path rather than report it to users?

**Comment by dbabkin** [comment]
Hello,

Do not see any bugs there. 
This is intended behavior.
