### ISSUE TITLE
Subsequent runs of "bazel build //..." are re-extracing external jars

### ISSUE THREAD

**Issue by pgr0ss** [bazelbuild/bazel#554]
I was asked to open this on IRC, and cc @kchodorow.

I'm seeing weird behavior in my project where subsequent runs of `bazel build //...`, which should do nothing (as nothing has changed) are taking over 3 seconds. Running with `--profile` and then `analyze-profile` is showing output which looks like it picks an external jar (different each time), extracts it, and then rebuilds the jars that depend on it up the tree:

Here is the bottom of `analyze-profile` (target names changed):

```
Critical path (3.082 s):
    Id        Time Percentage   Description
  4585     1.13 ms    0.04%   Building proj1/test.jar (46 files)
  4584     0.16 ms    0.01%   Extracting interface //proj1 test_helpers
  4583     1.257 s   40.77%   Building proj1/libtest_helpers.jar (4 files)
  4582     1.98 ms    0.06%   Extracting interface //proj1 proj1_lib
  4581     1.267 s   41.10%   Building proj1/libproj1_lib.jar (59 files)
  4580     0.50 ms    0.02%   Extracting interface //proj2 proj2
  4579     4.01 ms    0.13%   Building proj2/libproj2.jar (22 files)
  4578     0.36 ms    0.01%   Extracting interface //proj3 proj3
  4577     4.35 ms    0.14%   Building proj3/libproj3.jar (22 files)
  4576     1.65 ms    0.05%   Extracting interface //proj4 proj4
  4575     1.85 ms    0.06%   Building proj4/libproj4.jar (16 files)
  4574     0.73 ms    0.02%   Extracting interface //proj5 proj5
  4573     1.99 ms    0.06%   Building proj5/libproj5.jar (56 files)
  4572     8.52 ms    0.28%   Extracting interface //proj6 proj6
  4571     16.6 ms    0.54%   Building proj6/libproj6.jar (7 files)
  4570      515 ms   16.71%   Extracting interface @org.slf4j_slf4j-api//jar jar
```
The jar seems to be different on every run:
```
  4559      521 ms   16.95%   Extracting interface @io.netty_netty-common//jar jar

  4559      488 ms   15.86%   Extracting interface @com.google.auto.value_auto-value//jar jar

  4601      520 ms   16.68%   Extracting interface @com.google.guava_guava//jar jar
```

I ran `find ~/.cache/bazel -name '*.jar' | xargs ls -l` before and after these `bazel build` runs to see if the jars were actually changing. The only diff output was the timestamp of one symlink, which was for a different jar than showed up in `analyze-profile`:

```
% diff /tmp/before /tmp/after
5155c5155
< lrwxrwxrwx 1 admin admin      152 Nov  3 01:01 /home/admin/.cache/bazel/_bazel_admin/61e657d6884c63362b8b441914a1bc68/apps/_bin/joda-time-2.3.jar -> /home/admin/.cache/bazel/_bazel_admin/install/2f4600a1764c4f5c296fab148169372d/_embedded_binaries/embedded_tools/third_party/joda-time/joda-time-2.3.jar
---
> lrwxrwxrwx 1 admin admin      152 Nov  3 01:14 /home/admin/.cache/bazel/_bazel_admin/61e657d6884c63362b8b441914a1bc68/apps/_bin/joda-time-2.3.jar -> /home/admin/.cache/bazel/_bazel_admin/install/2f4600a1764c4f5c296fab148169372d/_embedded_binaries/embedded_tools/third_party/joda-time/joda-time-2.3.jar
```

We are running this commit, built from source: https://github.com/bazelbuild/bazel/commit/4c3c4b8a92e3d7ce9124541300bc773d28045632

Any idea what's going on? Or how can I debug this further?

Thanks for your help.

**Comment by ulfjack** [comment]
The next step is to figure out why these actions got invalidated in Skyframe. There's no generic mechanism for that, but I have a patch that adds (a lot of) debugging information that may help track this down. The patch is unfortunately rather dated, but maybe you want to give it a try:
https://github.com/bazelbuild/bazel/compare/master...ulfjack:ulfjack-debug-skyframe

**Comment by pgr0ss** [comment]
I got merge conflicts pulling in your branch, but I resolved them and pushed the result: https://github.com/bazelbuild/bazel/compare/release-0.1.2...pgr0ss:debug-skyframe

I'm not sure how to interpret the output, however:
```
% bazel build //... > /tmp/build_output
% grep INVALIDATING /tmp/build_output | wc -l
8630

% head /tmp/build_output
INVALIDATING null => PRECOMPUTED:build_id
INVALIDATING null => ERROR_TRANSIENCE:ERROR_TRANSIENCE
INVALIDATING PRECOMPUTED:build_id => FILE_STATE:[/]/[]
INVALIDATING PRECOMPUTED:build_id => FILE_STATE:[/]/[home/admin]
INVALIDATING PRECOMPUTED:build_id => FILE_STATE:[/]/[home/admin/bazel/tools]
INVALIDATING PRECOMPUTED:build_id => FILE_STATE:[/]/[home/admin/bazel/tools/build_rules]
INVALIDATING PRECOMPUTED:build_id => FILE_STATE:[/]/[home/admin/bazel]
INVALIDATING PRECOMPUTED:build_id => FILE_STATE:[/]/[home]
INVALIDATING PRECOMPUTED:build_id => FILE_STATE:[/]/[home/admin/bazel/tools/build_defs]
INVALIDATING PRECOMPUTED:build_id => FILE_STATE:[/]/[home/admin/bazel/tools/build_defs/docker/docker.bzl]
```
It also has lines like:
```
INVALIDATING ARTIFACT:build-info-volatile.properties com.google.devtools.build.lib.skyframe.BuildInfoCollectionValue$BuildInfoKeyAndConfig@f4a41f0 => ACTION_EXECUTION:action 'Building deploy jar app1/app1_deploy.jar' (JavaDeployJar[[Artifact:[[/home/admin/.cache/bazel/_bazel_admin/61e657d6884c63362b8b441914a1bc68/apps]bazel-out/host/internal]_middlemen/external_Slocal-jdk_Cjdk-default, Artifact:[[/home/admin/.cache/bazel/_bazel_admin/61e657d6884c63362b8b441914a1bc68/apps]bazel-out/local_linux-fastbuild/bin]app1/libapp1_lib.jar, Artifact:[[/home/admin/.cache/bazel/_bazel_admin/61e657d6884c63362b8b441914a1bc68/apps]bazel-out/local_linux-fastbuild/bin]authorization/libauthorization.jar, ...
```
What should I be looking for? I'm happy to chat on IRC if that would be easier.

**Comment by janakdr** [comment]
That looks like Bazel thinks the file home/admin/
bazel/tools/build_defs/docker/docker.bzl is external to your workspace, as
are all its ancestor directories. Bazel conservatively invalidates
"external" files on every build. What is your workspace root? Is it
possible you're referring to that bzl file via an absolute path somewhere?

**Comment by pgr0ss** [comment]
My workspace root is `/home/admin/proj/apps`

I have a `.bazelrc` in that folder with this:

```
build --package_path %workspace%:%workspace%/../../bazel/base_workspace
fetch --package_path %workspace%:%workspace%/../../bazel/base_workspace
query --package_path %workspace%:%workspace%/../../bazel/base_workspace
```

Is this related?

**Comment by janakdr** [comment]
So docker.bzl is outside any of your package path roots. Moving it into one
of them should keep it from being invalidated on every build. Since it's
being invalidated on every build, every package that loads docker.bzl will
be reloaded on every build, causing all of its actions to attempt
execution, although the action cache should prevent actual execution. I
don't have any idea why all that is causing external jars to be rebuilt --
it sounds like there's some non-determinism further down the line, which it
would be good to track down.

**Comment by haxorz** [comment]
> Is this related?

Perhaps. An "external" file is one *not* under any of the directory paths specified by --package_path. 

To rephrase janakdr's question: what's /home/admin/bazel and how are files under there (but not under /home/admin/bazel/base_workspace) being consumed during your build (e.g. do you have weird symlinks going on somewhere)?

**Comment by pgr0ss** [comment]
`/home/admin/bazel` is a git clone of https://github.com/google/bazel/, and we run `./compile.sh`. I don't think we have any weird symlinks in our repo. We load the docker file like this: `load("/tools/build_defs/docker/docker", "docker_build")`

**Comment by janakdr** [comment]
Hmm, I guess I'm still confused. Is bazel/base_workspace referring to this
file via the tools repository? I'm going to blame this on Lukács, but I
think he's traveling this week.

**Comment by pgr0ss** [comment]
Is there any other information I can give that will help us track down the issue?

**Comment by janakdr** [comment]
Can you try running your debugging bazel in the
/home/admin/bazel/base_workspace workspace and see what happens? I guess
you might have to edit a BUILD file to load docker.bzl.

**Comment by pgr0ss** [comment]
Is this what you're looking for?

```
% pwd
/home/admin/bazel/base_workspace

% git diff
diff --git a/examples/java-native/BUILD b/examples/java-native/BUILD
index b698a88..a35efca 100644
--- a/examples/java-native/BUILD
+++ b/examples/java-native/BUILD
@@ -1,3 +1,4 @@
+load("/tools/build_defs/docker/docker", "docker_build")
 package(default_visibility = ["//visibility:public"])

 filegroup(

% bazel build //examples/java-native:all > /tmp/build_output
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn of
f this warning via --ignore_unsupported_sandboxing.
____Loading...
____Loading complete.  Analyzing...
____Found 1 target...
Target //examples/java-native:srcs up-to-date (nothing to build)
____Elapsed time: 2.105s, Critical Path: 0.00s
```
build_output as a gist: https://gist.github.com/pgr0ss/75db537f872c4fe4357a

**Comment by janakdr** [comment]
That looks much better, although I'm still curious about those
embedded_binaries being invalidated. The local-jdk repository invalidation
is outside my area of expertise. So, maybe I have an idea of what's
happening. The tools/ directory in base_workspace is a symlink to the
tools/ sibling directory to base_workspace. This is not an "external"
symlink when you are building in the bazel workspace, since tools/ is still
under bazel/, but it is when you are building in another workspace and just
pulling in base_workspace via a package_path. I'm tempted to say you should
make your second package_path just %workspace%/../../bazel, but I'm not
sure if that actually works. We may need a Bazel expert to say what the
right way to pull the Bazel tools/ in is. Kristina?

**Comment by kchodorow** [comment]
Sorry, I see this, but I haven't gotten a chance to look into it yet.

**Comment by kchodorow** [comment]
Are the jars from `maven_jar` or `http_jar` (or both)?  Are you restarting bazel between builds, e.g., using --batch? (I assume not, but just checking.)

**Comment by pgr0ss** [comment]
The jars are from `maven_jar`. I am not restarting bazel between builds.

**Comment by kchodorow** [comment]
Haven't forgotten this!  @lberki has a change that's ready to go in that should fix this, but he's at a conference this week.

**Comment by lberki** [comment]
Yep, https://github.com/bazelbuild/bazel/commit/6aff7f4f2bf0c6418fb88e967653f2feeb83819e should have solved this issue. There were a few other changes in the area recently (https://github.com/bazelbuild/bazel/commit/f9fdc8dfced8b2b14561720623126a91e04b22cb, https://github.com/bazelbuild/bazel/commit/cf87843c422e90930779f078ce6bb11217570190 and one that is currently under review by Kristina). At HEAD, it should work properly, and once the aforementioned CL goes in, it will also be nice :)

**Comment by pgr0ss** [comment]
Thanks for fixing this! We haven't been tracking HEAD recently due to other issues (e.g. https://github.com/bazelbuild/bazel/issues/421), but I can try to give HEAD another shot.
