### ISSUE TITLE
Virtual include folder not cleaned after BUILD file change, leading to failure

### ISSUE THREAD

**Issue by ugoren** [bazelbuild/bazel#5541]
### Description of the problem / feature request:

A binary depends on two libraries, both export the same header. The header is included from the first, and the code compiles.
If I delete if from the first, I'd expect it to be included from the second, leading to successful compilation. But the header is not deleted from the first library's virtual include folder, and is included from there. This leads to failure when validating the includes.
Running `bazel clean --expunge` fixes it.

Only happens when sandboxing is disabled.
Discovered on Bazel 0.13, reproduced on 0.15.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Directory tree:
```
.
|-- WORKSPACE
|-- bin
|   |-- BUILD
|   `-- try.c
|-- lib
    |-- BUILD
    |-- a.h
    `-- b.h
```

File `bin/BUILD`:
```
cc_binary(
    name='try',
    srcs=['try.c'],
    deps=['//lib:a', '//lib:b'],
)
```

File `lib/BUILD`:
```
package(default_visibility=['//visibility:public'])

cc_library(
    name='a',
    hdrs=[
        'a.h',
        'b.h'
    ],
    strip_include_prefix='',
)

cc_library(
    name='b',
    hdrs=['b.h'],
    strip_include_prefix='',
)
```

File `bin/try.c`:
```
#include "a.h"
#include "b.h"

int main() {
        return 0;
}
```

Files `WORKSPACE`, `lib/a.h` and `lib/b.h` are empty.

This workspace can be built without error.
But the following sequence fails (the `sed` command deletes 'b.h'):
```
bazel build --strategy=CppCompile=standalone ...
sed -i'' -e '7d' lib/BUILD
bazel build --strategy=CppCompile=standalone ...
```
The error message is:
```
ERROR: /workspace/bin/BUILD:1:1: undeclared inclusion(s) in rule '//bin:try':
this rule is missing dependency declarations for the following files included by 'bin/try.c':
  'bazel-out/k8-fastbuild/bin/lib/_virtual_includes/a/b.h'
```

### What operating system are you running Bazel on?

CentOS 7

### What's the output of `bazel info release`?

`release 0.15.0- (@non-git)`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Installed with `yum`, from the [vbatts-bazel-epel-7.repo](https://copr.fedorainfracloud.org/coprs/vbatts/bazel/repo/epel-7/vbatts-bazel-epel-7.repo) repository

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Example in Github - https://github.com/ugoren/bazel-bug

**Comment by hlopko** [comment]
Hey @lberki , I assume you missed this one, and that you'd be fine with @scentini working on this instead :)

**Comment by katre** [comment]
Closed for lack of activity. Please ping the reviewers to reopen if this is still a problem.

**Comment by ugoren** [comment]
@katre, personally I don't mind at all.
The affected project was abandoned long ago, I changed jobs since.
I do think it's a genuine bug, and the use case isn't unreasonable, therefore it's worth fixing.
But it's your call.

**Comment by thii** [comment]
Can we reopen this? This is still a problem as of Bazel 9.2.0
