### ISSUE TITLE
ERROR: D:/tensorflow-master/tensorflow/core/platform/default/build_config/BUILD: 153:1:no such package '@png_archive//

### ISSUE THREAD

**Issue by xlrong** [bazelbuild/bazel#5544]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:
When I try to use bazel to build: bazel build tensorflow/python/tools:freeze_graph in windows 

My bazel version was: bazel-0.15.0-windows-x86_64.exe
I got below error:

ERROR: D:/tensorflow-master/tensorflow/core/platform/default/build_config/BUILD:
153:1: no such package '@png_archive//': Traceback (most recent call last):
        File "D:/tensorflow-master/third_party/repo.bzl", line 87
                _apply_patch(ctx, ctx.attr.patch_file)
        File "D:/tensorflow-master/third_party/repo.bzl", line 58, in _apply_pat
ch
                _execute_and_check_ret_code(ctx, cmd)
        File "D:/tensorflow-master/third_party/repo.bzl", line 43, in _execute_a
nd_check_ret_code
                fail("Non-zero return code({1}) when ...))
**Non-zero return code(127) when executing 'D:\msys64\usr\bin\bash.exe -l -c patch
 -p1 -d C:/users/lirong.xu/_bazel_lirong.xu/obpmm2rb/external/png_archive -i D:/
tensorflow-master/third_party/png_fix_rpi.patch':**
Stdout:
Stderr: /usr/bin/bash: patch: 鏈壘鍒板懡浠? and referenced by '//tensorflow/co
re/platform/default/build_config:platformlib'
ERROR: Analysis of target '//tensorflow/python/tools:freeze_graph' failed; build
 aborted: no such package '@png_archive//': Traceback (most recent call last):
        File "D:/tensorflow-master/third_party/repo.bzl", line 87
                _apply_patch(ctx, ctx.attr.patch_file)
        File "D:/tensorflow-master/third_party/repo.bzl", line 58, in _apply_pat
ch
                _execute_and_check_ret_code(ctx, cmd)
        File "D:/tensorflow-master/third_party/repo.bzl", line 43, in _execute_a
nd_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'D:\msys64\usr\bin\bash.exe -l -c patch
 -p1 -d C:/users/lirong.xu/_bazel_lirong.xu/obpmm2rb/external/png_archive -i D:/
tensorflow-master/third_party/png_fix_rpi.patch':
Stdout:
Stderr: /usr/bin/bash: patch: 鏈壘鍒板懡浠?INFO: Elapsed time: 19.012s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (92 packages loaded)
FAILED: Build did NOT complete successfully (92 packages loaded)

> Replace this line with your answer.

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

> windows7 64bit

### What's the output of `bazel info release`?

> release 0.15.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> I didn't find any answer after searching the web
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by jin** [comment]
Hi @xlrong, it looks like you're asking a question about Tensorflow's build. Please ask the question on StackOverflow [0] or the Tensorflow repository instead [1].

[0]: https://stackoverflow.com/questions/tagged/bazel
[1]: https://github.com/tensorflow/tensorflow/issues
