### ISSUE TITLE
wrapped_clang needs debug_prefix_map_pwd_is_dot for debug-prefix-map support on Mac/iOS

### ISSUE THREAD

**Issue by nglevin** [bazelbuild/bazel#5545]
### Description of the problem / feature request:

Bazel needs the debug_prefix_map_pwd_is_dot feature to be in its wrapped_clang, just as it is for internal purposes, for --fdebug-prefix-map to work as intended and provide portable debug information for Mac builds.

The flag is used by Tulsi here; https://github.com/bazelbuild/tulsi/blob/65ad66f77f9377db47be6894efab7f60292f0fcd/src/TulsiGenerator/Scripts/bazel_build.py#L810 It is stable for non-Bazel purposes, but Bazel should use it sooner than later.

Especially now that Bazel sandboxing appears to be breaking the current, "direct debug prefix map" solution that Bazel + Tulsi use today.

(After debug_prefix_map_pwd_is_dot support is added to Bazel, this will require an update to Tulsi's bazel_build.py script to remove the direct debug prefix map behavior. Before that can be useful, wrapped_clang needs to have this dotted path feature flag.)

### Feature requests: what underlying problem are you trying to solve with this feature?

This is required for breakpoint-level debugging to work with Tulsi and Bazel sandboxing on Darwin.

I am reporting this issue as a community service, and also as a fellow who really pushed for this solution while I was a Googler. Hello Sergio, Tom, Kelvin, David...

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1) Follow steps at https://github.com/nglevin/bazel/blob/fe4936031e38dd33687261334b2225224e96c430/site/docs/tutorial/ios-app.md to build an iOS app with Bazel 0.15.0-homebrew (the latest version I could find).

2) Generate a new Tulsi project based on this ios-app, default settings.

3) Add a breakpoint to the App Delegate's applicationDidFinishLaunching:withOptions:

4) Notice that the breakpoint isn't hit; this is because Bazel is trying to redirect debug information with -fdebug-prefix-map from bazel_build.py, but can't because the redirection needs to happen in wrapped_clang instead.

### What operating system are you running Bazel on?

macOS 10.13.5 High Sierra.

### What's the output of `bazel info release`?

camael:tutorial nglevin$ bazel info release
Starting local Bazel server and connecting to it...
............
release 0.15.0-homebrew

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

I am a Xoogler and I know how this works. I just can't copy the solution I know exists in parts-that-I-cannot-name because I no longer work for Google. So there!

### Any other information, logs, or outputs that you want to share?

Just that I think kaipi@ knows his way about wrapped_clang, and trybka@ knows how the debug_prefix_map_pwd_is_dot feature flag works. So I think the two of them would be best suited to get this working in open source land, if desired.

**Comment by jin** [comment]
cc @sergiocampama

**Comment by DavidGoldman** [comment]
This has been implemented in 3f46dd0 and hopefully will be in the next Bazel release.

**Comment by nglevin** [comment]
Hooray!

**Comment by DavidGoldman** [comment]
Closing as this is now released in Bazel 0.17.1
