### ISSUE TITLE
Add bazel.gitignore to https://github.com/github/gitignore

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/bazel#555]
...to allow users to quickly set up their workspaces.

**Comment by davidzchen** [comment]
+1

**Comment by davidstanke** [comment]
@cgrushko Sounds like a good idea. Can you submit a PR to that repo?

**Comment by cgrushko** [comment]
Does the following make sense? Should we include more files?

```
# Ignore all bazel-* symlinks. There is no full list since this can change
# based on the name of the directory bazel is cloned into.
/bazel-*
```

**Comment by jin** [comment]
Looks like it's added by @cgrushko https://github.com/github/gitignore/blob/master/community/Bazel.gitignore
