### ISSUE TITLE
[FR] Repository cache / Http Downloader should support symlinks to content and not solely copying them

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#5568]
### Description of the problem / feature request:

Repository cache / Http Downloader should support symlinks to content and not solely copying them

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm trying to minimize the disk space external dependencies take when you have many bazel projects with a lot of common dependencies.

Currently repository_cache saves the network bandwith as well as the download time.
Many of my workspaces have an `external` folder of ~1GB. Given I have tens of workspaces this adds up.

cc @aehlig

**Comment by aehlig** [comment]
The code [raises the concern](https://github.com/bazelbuild/bazel/blob/e14a7d4f156c28244a491c65083273f57734cdbe/src/main/java/com/google/devtools/build/lib/bazel/repository/cache/RepositoryCache.java#L108) that symlinks might badly interact with cache cleanup, which is indeed correct. Adding a hard link might be an option.

**Comment by ittaiz** [comment]
Thanks!

**Comment by ittaiz** [comment]
@aehlig following our offline discussion I think there is value in also supporting softlinks for the use-case of ephemeral workers in CI which don't care about cleanup and are short lived on the one hand but would rather minimize IO such as copying of the files and can't support hardlinks across different volumes (for example GCB).
I'm commenting here and not on a new issue since it has the context.
How do you suggest we advance?

**Comment by ittaiz** [comment]
@aehlig ping

**Comment by Globegitter** [comment]
@ittaiz this sounds like a very interesting use-case and I think it would be worth opening a separate issue on this for visibility and link to the issue here.

**Comment by ittaiz** [comment]
I actually talked with @aehlig offline about this and he said he'd be happy to accept contribution for this. Just haven't gotten to it yet :(
