### ISSUE TITLE
Automatic args passing on bazel run causes issues with rules_docker

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel#5570]
### Description of the problem / feature request:

rules_docker has an `args` parameter on most rules to allow setting the args of the binary run in the container on its entrypoint. This works all fine when building the container and running it manually e.g. via `docker run`. But when the container is run via `bazel run` the arguments are passed in twice, as bazel automatically passes down any aruments specified in `args`. See: https://github.com/bazelbuild/rules_docker/issues/374

Ideally there would be a way to just turn the automatic `args` passing off on a per-rule basis. Or if that is already possible, document how that is possible.

### Feature requests: what underlying problem are you trying to solve with this feature?

Not having duplicate arguments passed in on `bazel run :container_image`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run any example specified in https://github.com/bazelbuild/rules_docker/blob/master/testdata/BUILD that has arguments specified. E.g. modify https://github.com/bazelbuild/rules_docker/blob/master/testdata/py_image.py to include `print(sys.argv)` and then run  `bazel run //testdata:py_image`

### What operating system are you running Bazel on?
Ubuntu 16.04

### What's the output of `bazel info release`?

release 0.15.0

###  Have you found anything relevant by searching the web?
https://github.com/bazelbuild/rules_docker/issues/374

**Comment by jin** [comment]
cc @lberki

**Comment by lberki** [comment]
FWIW, this is not an issue with Bazel core -- `bazel run` uses the arguments the command specifies in its `FilesToRunProvider`:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/runtime/commands/RunCommand.java#L169

and I don't think it's generally useful to add a knob that changes that. It's on the Docker rules to make sure that there is no duplication.
