### ISSUE TITLE
Skylark support for multi-arch ("fat") binaries

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel#5575]
Part of the [Skylark build configuration](https://docs.google.com/document/d/1vc8v-kXjvgZOdQdnxPTaV0rrLxtP2XwnD2tAZlYJOqw/edit#heading=h.pn8nbhno42p5) project.

This is a tracking issue for the ability of Skylark writers to design [fat binaries](https://en.wikipedia.org/wiki/Fat_binary), such as fat Android APKs.

This will eventually replace ad hoc flags like [`--fat_apk_cpu`](https://docs.bazel.build/versions/master/user-manual.html#flag--fat_apk_cpu). In particular, it will make it possible for *any* rule to create multi-arch dependencies with specific compilation / bundling logic of its choosing.

This complements the [Bazel Configurability Roadmap](https://www.bazel.build/roadmaps/configuration.html). Write questions / comments / status updates here. See there for the bigger picture.

**Comment by gregestren** [comment]
**2018 EOY update:**

This feature is *essentially done*.

* The pieces of https://github.com/bazelbuild/bazel/issues/5574 needed for multi-arch are done
* This requires `--experimental_starlark_config_transitions`, which is a temporary flag going away in the next release or two
* Proper documentation is TBD.
* This has serious performance / memory consequences, as described at https://github.com/bazelbuild/bazel/issues/5574#issuecomment-458349702. We encourage cautious adoption (on the experimental side) at this time.
* Support for [custom flags](https://github.com/bazelbuild/bazel/issues/5577) is ongoing.

Since we're just easing in this support now in such a tentative way, I'll keep the issue open for now. Interested users / experimenters should ping this thread.

**Comment by ixdy** [comment]
multi-arch docker manifest lists are a strong use case for this. https://github.com/bazelbuild/rules_docker/issues/300

**Comment by Pensu** [comment]
Making multi-arch binaries for `kubernetes/test-infra` repo is also a use case for this.

**Comment by gregestren** [comment]
Sorry I missed this last comment. 

Yes, bazel can build multi-arch binaries now, with caveats. Specifically you can apply the split but the API for a consuming rule to filter its deps by how they were split (e.g. *"give me all the deps that were built for ARM"* ) is still incomplete


 Check out https://docs.bazel.build/versions/master/skylark/config.html#defining-12-transitions for an example.

**Comment by Pensu** [comment]
Thanks @gregestren. Will try these out.

**Comment by buchgr** [comment]
@gregestren I am curious what exactly is missing from the API? There seems to be [ctx.split_attr](https://docs.bazel.build/versions/master/skylark/lib/ctx.html#split_attr). Is this not sufficient?

**Comment by gregestren** [comment]
I think it'll still work if you're splitting just on `--cpu`. Generalizing that is the main challenge.
