### ISSUE TITLE
Support fast incremental reruns on --test_timeout, etc. changes

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel#5579]
Normally, changing any command line flag invalidates the build graph, meaning Bazel's analysis phase has to rebuild the graph from scratch.

There's good reason for this. But it's silly when changing flags like `--test_timeout`, `--test_filter`, etc. Those flags are known to *only* affect tests. So while the tests themselves may need to be re-analyzed, none of their transitive dependencies (which represent the vast majority of the build graph) need to be.

This is a tracking bug for the effort to optimize this case (i.e. only invalidate test targets when `--test*` flags change). 

A flag has already been written to support this: https://github.com/bazelbuild/bazel/commit/0412a9f92d00eda3b9a1df7da6c2ba059767c108. But some more graph invalidation support is needed to make it functional.

**Comment by gregestren** [comment]
@serynth this is fixed as of https://github.com/bazelbuild/bazel/commit/f29f78d19288f6d6e7aea6bc65e6bfa01b2531ad?

With the caveat that `--test_timeout` specifically won't get opted in because of the quirk of it being in `BuildConfiguration` instead of `TestConfiguration`, but options like `--test_filter`, `--test_arg`, `--runs_per_test`, etc. work out of the box?

**Comment by serynth** [comment]
Yup, that fixes it! The specific list of flags that works:
* `test_filter`
* `cache_test_results`
* `test_result_expiration`
* `test_arg`
* `test_sharding_strategy`
* `runs_per_test`
* `coverage_support`
* `coverage_report_generator`


Flags that don't work (well, any of them not listed above, but these are the ones I wanted to move):
* `test_env`
* `test_timeout`
* `instrumentation_filter`
* `instrument_test_targets`

**Comment by gregestren** [comment]
Also, have to use [`--trim_test_configuration`](https://github.com/bazelbuild/bazel/blob/f29f78d19288f6d6e7aea6bc65e6bfa01b2531ad/src/main/java/com/google/devtools/build/lib/analysis/test/TestConfiguration.java#L121) to enable the feature.

**Comment by gregestren** [comment]
Anyway, is this issue closeable now?

**Comment by serynth** [comment]
Yeah, I'm good with this! :D
