### ISSUE TITLE
Publish a blog-post about using Bazel as a custom build-system in Xcode

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/bazel#558]
Scenario:
A large iOS app has a library dependency, which can already be built using Bazel.

To incrementally introduce Bazel into one's workflow, it would be useful to build that library dependency using Bazel, and use the resulting artifact as an input in the larger build.

This is a subset of #553.

**Comment by cgrushko** [comment]
To location the output of a target, one can use

    bazel info bazel-bin

and append the output name of the target to it, such as `examples/android/examples/android/java/bazel/hello_world_deploy.jar`

**Comment by davidzchen** [comment]
+1. This would be great to have.

**Comment by cgrushko** [comment]
IIUC, @dmaclach is working on obviating this issue by changing the way we generate Xcode projects.

**Comment by meisterT** [comment]
https://tulsi.bazel.build/ should be sufficient.
