### ISSUE TITLE
Unable to select on "llvm" compiler

### ISSUE THREAD

**Issue by g-easy** [bazelbuild/bazel#5580]
### Description of the problem / feature request:

Unable to use `select()` to get different outcomes for gcc vs clang.

### Feature requests: what underlying problem are you trying to solve with this feature?

I'd like to compile with `-Werror=thread-safety` when the compiler is clang (gcc doesn't recognize this flag)

More generally, I'd like to know when the compiler is clang so I can `select()` on it.

### What operating system are you running Bazel on?

Linux

**Comment by g-easy** [comment]
cc @mhlopko

**Comment by mhlopko** [comment]
This is a simple change in [cc_configure](https://source.bazel.build/bazel/+/6b5205b000fe391faf12f84ed4f2e9ea38ae81ff:tools/cpp/cc_configure.bzl), do you want to give it a try? What needs to be done is run `cc -v`, parse the output, and decide if the compiler is clang, gcc, ... or unknown. And place that string into compiler field in the crosstool.

**Comment by mhlopko** [comment]
Cc @scentini

**Comment by hlopko** [comment]
Closing since it's not important anymore (I assume).
