### ISSUE TITLE
`@bazel_tools//tools/build_defs/repo:http.bzl` debug messages.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/bazel#5583]
Passing in a `build_file_contents` causes a debug message from `http_archive` (line 48).  This is used in the Kotlin rules. Is this line still meant to be in there ?

**Comment by dkelmer** [comment]
What is the debug message you're seeing?

**Comment by edbaunton** [comment]
It would be useful to report which version of bazel you're using but the debug messages you refer to should be fixed in https://github.com/bazelbuild/bazel/commit/eed98a66405ff70c69d435a9419c3dc4ae7c184a

**Comment by hsyed** [comment]
Aah yes. I'm on 0.14.1 at the moment. Thanks !
