### ISSUE TITLE
Inconsistent behavior with variables in query

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#5584]
### Description of the problem / feature request:

When using `bazel query` with variables, I'm getting a seemingly inconsistent behavior.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ bazel query 'let desugar_label = tools/android/desugar.sh in $desugar_label'
//tools/android:desugar.sh

$ bazel query 'attr(srcs, //tools/android:desugar.sh, //tools/android:*)'
//tools/android:srcs
//tools/android:embedded_tools

$ bazel query 'let desugar_label = tools/android/desugar.sh in attr(srcs, $desugar_label, //tools/android:*)'
INFO: Empty results
```

I expected the free variable `$desugar_label` in the `attr(..)` call to be replaced with `//tools/android:desugar.sh`, therefore getting the same results with the query that inlines the file label.
### What's the output of `bazel info release`?

release 0.15.0

@lberki @ulfjack any ideas?

**Comment by jin** [comment]
Ah, if we have the following syntax:

```let var = expr1 in expr2```

Does `query` replace all occurrences of `$var` in `expr2` with `expr1` without first eagerly evaluating `expr1`?

**Comment by lberki** [comment]
This is WAI, although the documentation could probably use some beefing up.

The reason is that the second argument of `attr` is not a label, but just a string, and `let` only knows how to assign set of targets to a variable. Thus (I haven't looked closely) you are either comparing a set of targets to a string or the variables just doesn't get substituted at all.

**Comment by jin** [comment]
Thanks for the explanation!

**Comment by jin** [comment]
Looks like I was under the impression that `$desugar_label` would be evaluated by query before calling `attr` with it, but that's not the case and it's just inlining the value `tools/android/desugar.sh`.
