### ISSUE TITLE
Support NDK r18

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#5585]
Expected release date: [September 2018](https://github.com/android-ndk/ndk/wiki#ndk-r18)

Beta 1 should be out later this month.

Roadmap: https://android.googlesource.com/platform/ndk/+/master/docs/Roadmap.md

Expected changes to Bazel:

- Remove support for non-`libc++` STLs

> libc++ has been the default for a release and has proven to be stable. It is a strict improvement over the other STLs (more features, better Clang compatibility, Apache licensed, most reliable). The fact that the NDK supports multiple STLs is a common pain point for users (it's confusing for newcomers, and it makes sharing libraries difficult because they must all use the same STL).

> Now that we have a good choice for a single STL, we‘ll remove the others. We’ll most likely move the source we have for these along with building instructions to a separate project so that people that need these for ABI compatibility reasons can continue using them, but support for these will end completely.

- Remove support for GCC

> GCC is still in the NDK today because some of gnustl's C++11 features were written such that they do not work with Clang (threading and atomics, mostly). Now that libc++ is the best choice of STL, this is no longer blocking, so GCC can be removed.

**Comment by steeve** [comment]
Looking at this, support should be pretty simple it seems? Even almost working as-is?

**Comment by steeve** [comment]
Looking at the commit, never mind 😄
