### ISSUE TITLE
add an option to disable the idle GC

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#5589]
If a Bazel server is idle for 10 seconds after finishing a command, it will invoke `System.gc()`. On HotSpot, `System.gc()` triggers an aggressive full GC. In practice, I see `System.gc()` in a Bazel server with a 2GB heap fully consume 4 cores for several seconds. This behavior is problematic for workflows that involve building a binary and then immediately running it; if the binary itself is resource intensive and long-running, Bazel will steal CPU from it. One can effectively disable the idle GC today with `--host_jvm_args=-XX:+DisableExplicitGC`, but this is hacky and makes instrumentation commands like `bazel info used-heap-size-after-gc` silently useless. So, I propose introducing an official startup flag to disable idle GC.

A new option is my conservative proposal. Going further, I'd be interested in learning the reasons for Bazel's idle GC behavior. To me, it's polite to only use lots of CPU when Bazel is synchronously processing a command. I suppose in theory an idle GC saves GC work during synchronous work, but can the value of that be measured? If a user is iterating by running `build` or `test` on the same target, most server state should be essentially persistent and won't benefit from being repeatedly walked by a full GC. If the idle GC is valuable, could Bazel use a whole-system idleness check in lieu of the current 10 second heuristic?

**Comment by dslomov** [comment]
@meisterT for triage since this is perf related. I do agree that "every 10 seconds full gc" is not awesome.

**Comment by buchgr** [comment]
I think we should delete this code. I have yet to see a benchmark showing that the application logic choosing to do a GC results in better performance than the JVM triggering the GC itself.
