### ISSUE TITLE
Build Encyclopedia's ToC (on the right) is almost always out of view

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/bazel#559]
... what do you think about having it in a separate frame?

**Comment by davidzchen** [comment]
By out of view, do you mean that it is too long to fit in a single screen?

**Comment by cgrushko** [comment]
Nope, I mean that the main part of the docs is so long, that the ToC (the thing on the right hand side) is almost always above the fold.

Also, during development, jumping between General, Workspace and Object-C (or Android) is very distracting. Worse, it requires guessing where e.g., `config_setting` is (I was usually wrong :) )

**Comment by davidzchen** [comment]
I see. Do you think it would be a good idea to expand to list the actual rules on the left navigation as well?

**Comment by cgrushko** [comment]
I think it would be useful, yes. And then perhaps it'll make sense to have one page per rule.
Perhaps we should prototype this, though, before trusting me :)

**Comment by kchodorow** [comment]
Given how many rules we have, it might be easier for users if the search box was always on-screen, instead of having to scroll through pages of rules.  But I dunno, I'm not a UX designer.

**Comment by cgrushko** [comment]
Perhaps something like CodeSearch?

https://code.google.com/p/chromium/codesearch#chromium/src/v8/src/ast.h&q=asd&sq=package:chromium&type=cs&l=2477

An always-on search box, an outline on the left that can be scrolled
independently of the main section.

**Comment by davidzchen** [comment]
That's a good idea. The [Polymer docs](https://www.polymer-project.org/1.0/docs/start/getting-the-code.html) also has this kind of layout. I can try prototyping something similar.

**Comment by davidstanke** [comment]
This is obsolete since website redesign.
