### ISSUE TITLE
Stale documentation for "--show_package_location"

### ISSUE THREAD

**Issue by petroseskinder** [bazelbuild/bazel#5592]
At least as early as Bazel 0.14.0, this flag has been deprecated. When I attempt to execute

```bash
bazel build //some-target --show_package_location
```
Bazel outputs
```bash
WARNING: Option 'show_package_location' is deprecated: This flag is no longer supported and will go away soon.
```
The docs do not indicate that 1) the flag is being deprecated, and 2) what the replacement is for identifying a package location.

Here are specific portions of doc, I have seen this
* [Options that affect how packages are located](https://docs.bazel.build/versions/master/user-manual.html#options-that-affect-how-packages-are-located) - this references the flag, and also has a stale link when clicking the --show_package_location link.  [Reference in code](https://github.com/bazelbuild/bazel/blob/master/site/docs/user-manual.html#L1076)
*  [Command Line Reference](https://docs.bazel.build/versions/master/command-line-reference.html) - does not have a deprecated tag.

**Comment by jin** [comment]
@ericfelly what's the status of this flag?
