### ISSUE TITLE
The target you are compiling requires Visual C++ build tools. Bazel couldn't find a valid Visual C++ build tools installation on your machine.

### ISSUE THREAD

**Issue by inakaaay** [bazelbuild/bazel#5593]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> I am converting my saved_model.pb to .tflite when i do 
`bazel run -c opt tensorflow/contrib/lite/toco:toco -- --savedmodel_directory=/saved_model/saved_model -- output_file=/saved_model/maonani.tflite` i get an error saying that 

`INFO: Analysed target //tensorflow/contrib/lite/toco:toco (0 packages loaded).`
`INFO: Found 1 target...`
`ERROR: C:/users/lenovo-pc/_bazel_lenovo-pc/buizwhxs/external/protobuf_archive/BUILD:70:1: C++` `compilation of rule '@protobuf_archive//:protobuf_lite' failed (Exit -1)`

`The target you are compiling requires Visual C++ build tools.`
`Bazel couldn't find a valid Visual C++ build tools installation on your machine.`
`Please check your installation following https://docs.bazel.build/versions/master/windows.html#using`

`Target //tensorflow/contrib/lite/toco:toco failed to build`
`Use --verbose_failures to see the command lines of failed build steps.`
`INFO: Elapsed time: 5.367s, Critical Path: 1.25s`
`INFO: 0 processes.`
`FAILED: Build did NOT complete successfully`
`FAILED: Build did NOT complete successfully`

but i already installed Visual Studio Build Tools 2017 yet im still getting that error

### What operating system are you running Bazel on?

> Windows 10

**Comment by rongjiecomputer** [comment]
What is the installation location of your Visual Studio Build Tools 2017?

Are you running Bazel in Visual Studio Build Tools Dev command prompt? Try running Bazel in plain Windows command prompt instead. Do not run `vcvarsall.bat` before running Bazel for the first time in a workspace.

Try setting `BAZEL_VC` env var to `<Build Tools>/VC/` and run Bazel again if Bazel still can't detect Visual Studio.

Also, as far as I know, Tensorflow Lite does not work with Bazel on Windows yet. @meteorcloudy will know more.

**Comment by meteorcloudy** [comment]
Normally, Bazel should be able to detect your installation from registry info. But as pointed out by @rongjiecomputer , you can also set `BAZEL_VC` to your VC installation directory, and make please make sure tools such as `cl.exe`, `link.exe`, `lib.exe` do exist under that directory. Sometimes VC tools are not installed by default during VS installation.

**Comment by inakaaay** [comment]
thank you for your responses! it has solve my problem however i have different issues regarding the conversion

**Comment by RNabel** [comment]
You can set environment variables permanently on Windows (just google "Set Environment Variable Windows"). 

Please note, however, that bazel starts up a bazel server which is killed either due to inactivity or when calling `bazel shutdown`. If you change your environment variables _after_ starting your bazel server you may have to kill it using `bazel shutdown` and re-run your `bazel build` command afterwards which will restart the bazel server.

**Comment by inakaaay** [comment]
thank you!
