### ISSUE TITLE
importing protos across reporitories

### ISSUE THREAD

**Issue by ola-rozenfeld** [bazelbuild/bazel#5596]
According to https://github.com/bazelbuild/rules_go/issues/877#issuecomment-337254707 there isn't currently a way to import protos across repositories. This means we will have to copy the entire https://github.com/bazelbuild/remote-apis/ into Bazel's third party instead of just depending on the released version. This is not ideal -- especially because the path bazel/third_party/bazelbuild will raise eyebrows.

**Comment by ittaiz** [comment]
What's the problem in importing protos accross repositories? We do it without a problem

**Comment by ola-rozenfeld** [comment]
Oh! Maybe it was fixed? How do you do that? Suppose I have this proto https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/execution/v2/remote_execution.proto, and I define dependency in my WORKSPACE on the repo, e.g:

    http_archive(
      name = "remoteapis",
      urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/remote-apis/archive/4ac001182e50d404fa790fb4a321daca089fe18c.tar.gz",
        "https://github.com/bazelbuild/remote-apis/archive/4ac001182e50d404fa790fb4a321daca089fe18c.tar.gz",
      ],
      strip_prefix = "remote-apis-4ac001182e50d404fa790fb4a321daca089fe18c",
      sha256 = "874560dc65861624febd747c54b9ef70a1666e3d335e147ea362d1f331711057",
    )

What import statement do I write in https://github.com/bazelbuild/bazel/blob/master/src/main/protobuf/remote_execution_log.proto#L21 to import https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/execution/v2/remote_execution.proto from the remote repository?

**Comment by ittaiz** [comment]
Our proto usage is heavily influenced by our maven origins.
All of our protos are under src/main/proto/some/folder/some.proto
Then under src/main/proto we have a BUILD.bazel with proto_library which
have “proto_source_root = native.package_name()”
Then in the depending proto file they just import some/folder/some.proto

Does that help?

**Comment by ola-rozenfeld** [comment]
Thank you very much for your help! Yes, turns out it does work, I just had a very silly mistake (wrong dependency). Sorry for wasting your time!

**Comment by ittaiz** [comment]
👍🏽
