### ISSUE TITLE
bazel_rules_test broken at HEAD

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#5607]
### Description of the problem / feature request:

Bazel with downstream projects: "Bazel Remote Execution" is broken at HEAD.
Example run:
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/341#b1274694-06b0-4b16-8ff9-d967073f0efe

Relevant snip:

** test_genrule_default_env ****************************************************
/b/s/w/ir/run/bazel-out/k8-fastbuild/bin/src/test/shell/bazel/bazel_rules_test.runfiles/io_bazel/src/test/shell/bazel/bazel_rules_test: line 295: TMPDIR: unbound variable

I believe this was caused by f814454ff5477418ca44696efb5c71339368efa4

we probably just need to not assume TMPDIR is set, which was the previous state before that change

**Comment by laszlocsomor** [comment]
Taking a look.

**Comment by laszlocsomor** [comment]
> we probably just need to not assume TMPDIR is set, which was the previous state before that change

`$TMPDIR` should always be set, see https://github.com/bazelbuild/bazel/blob/ae43043f6c42add7bd0535b66edb344bbc6e9001/src/main/java/com/google/devtools/build/lib/exec/local/PosixLocalEnvProvider.java#L55

However, it seems to be unset here. Let me take a look as to why.

**Comment by laszlocsomor** [comment]
Ah, because we're talking about remote execution, not local ones. I don't know how the remote executor sets up envvars, so let me add code that allows an empty `TMPDIR`.
