### ISSUE TITLE
Feature request: maven_aar

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/bazel#561]
... similar to maven_jar, but downloads aar files and makes them available in the build.

**Comment by cgrushko** [comment]
@menny

**Comment by cgrushko** [comment]
Actually, there's no `.aar` support in Bazel at all. 
Since this is probably a separate problem, filed #564.

**Comment by kchodorow** [comment]
In the interim, you should be able to use `new_http_archive` to download/extract .aar files. Something like:

```
new_http_archive(
    name = "yarr",
    url = "http://pirate.co/y.arr",
    sha256 = "...",
    type = "zip",
)
```

The `type = "zip"` will tell bazel that it should be extracted like a zip file, even though it has the "wrong" extension.  See http://bazel.io/docs/be/workspace.html#new_http_archive.

**Comment by menny** [comment]
@kchodorow , `build_file` is marked as _required_. What should I use there?

**Comment by kchodorow** [comment]
`new_http_archive` creates a little Bazel workspace in the directory created by unzipping the zip.  So the `build_file` is the BUILD file you want to build/expose everything in that "workspace."  I'm not too familiar with Android, but from http://tools.android.com/tech-docs/new-build-system/aar-format it looks like you might want something like:

```
java_import(
    name = "all-the-jars",
    srcs = ["classes.jar", "lint.jar"] + glob(["libs/*.jar"]),
    visibility = ["//visibility:public"],
)

exports_files([...everything else...])
```

Put that content in a file called, say, yarr.BUILD and then set `build_file = "yarr.BUILD"`. 

Then you can depend on `@yarr//:all-the-jars` from your project's BUILD files.

You can also try building it with the BUILD file I suggested above and take a look at `$(bazel info output_base)/external/yarr`, that might give you a clearer idea of what's happening.

**Comment by cgrushko** [comment]
IIRC, changing the `type` to `zip` didn't work - Bazel complained about
wrong type for the file.

**Comment by kchodorow** [comment]
I tried a simple example and it seems to work for me, let me know if you guys get any errors.

**Comment by menny** [comment]
@kchodorow , can you share the code you used? I fail to get that to work.

To be clear, we have a few AAR we want to import

**Comment by tomorrowkey** [comment]
The Workaround works fine. Thank you.

This is sample project which is using aar library.
https://github.com/tomorrowkey/HelloBazel/tree/28a2bcfdbaff264fcecff263f61a70d12968577e

**Comment by kchodorow** [comment]
@menny The workaround @tomorrowkey posted is basically what I did, if that isn't working for you could you post some steps to reproduce?

**Comment by menny** [comment]
@tomorrowkey @kchodorow , the workaround works. I forgot to reply.
Thank you.

**Comment by dwerner** [comment]
For more complicated dependency trees, this doesn't work well. Each dependency needs to be added and it gets quite tedious, finding every package which may have a different internal custom_package than the URI would suggest. Simply being able to refer to an aar file would suffice.

**Comment by aj-michael** [comment]
For anyone watching, Bazel now includes a Skylark workspace `maven_aar` rule. See 26de97ba7c2725680e8e9a424362e31935c647f4 for all the details. To use it, in your `WORKSPACE `add

```
 load("@bazel_tools//tools/build_defs/repo:maven_rules.bzl", "maven_aar")
```

and then in your `WORKSPACE` you can create a `maven_aar` target with

```
maven_aar(
    name = "facebook_android_sdk",
    artifact = "com.facebook.android:facebook-android-sdk:3.19.0",
)
```

Then in your `BUILD` file you can depend on the AAR with

```
android_binary(
    name = "my_app",
    ...
    deps = [
        "@facebook_android_sdk//aar",
        ...
    ],
)
```

HOWEVER (AND THIS IS IMPORTANT): This rule uses `aar_import` under the covers which is still highly experimental and has known issues that are being worked on. You will likely need to build with `--spawn_strategy=standalone` and if you depend on multiple AARs containing overlapping resource ids, the build may fail due to conflicts.

**Comment by aj-michael** [comment]
Ok, as of b5f480c `aar_import` is fully functional so `maven_aar` is fully functional.

See https://github.com/bazelbuild/bazel/issues/561#issuecomment-259458533 for usage details.
