### ISSUE TITLE
FAQ Pex Support Link Broken

### ISSUE THREAD

**Issue by zanes2016** [bazelbuild/bazel#5614]
On the [FAQ: What About Python site](https://bazel.build/faq.html#what-about-python), the link for pex support is broken (404 error) for https://github.com/bazelbuild/bazel/blob/master/tools/build_rules/py_rules.bzl. 

> Simplistic support for PEX-style binaries is at [here](https://github.com/bazelbuild/bazel/blob/master/tools/build_rules/py_rules.bzl).

Does anyone know what the link should be?

**Comment by dkelmer** [comment]
I don't see a What About Python section in the linked page. Could you try another link?

**Comment by zanes2016** [comment]
It looks like that section has been removed since I first posted this
