### ISSUE TITLE
Error: Unknown startup option: '--user'.

### ISSUE THREAD

**Issue by zhangkom** [bazelbuild/bazel#5615]
./bazel-0.13.0-darwin-x86_64 --user

Error: Unknown startup option: '--user'.
  For more info, run 'bazel help startup_options'.

**Comment by jin** [comment]
The `--user` flag is for the installer (`bazel-0.15.2-installer-darwin-x86_64.sh`), not the Bazel binary itself (`bazel-0.15.2-darwin-x86_64`). You can use the binary directly, or move it to a folder on your `$PATH` and rename it to `bazel`.
