### ISSUE TITLE
FR: Script to generate `maven_jar` rules from build.gradle's dependencies closure

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/bazel#562]
@menny

**Comment by jin** [comment]
I have an experimental Gradle to Bazel generator here. https://github.com/jin/rules_experimental_android#gradle-to-bazel-project-generator

It parses the output of `gradle dependencies` and generates the corresponding rules_jvm_external declaration in the WORKSPACE file. It's still in a prototype phase and constrained to Android projects, but please try it out and provide feedback if you have any.

**Comment by jin** [comment]
Also see https://github.com/Zetten/bazel-dependencies-gradle-plugin

maven_jar no longer exists, so closing this now.
