### ISSUE TITLE
Support testing across Android SDK and NDK versions in a single environment

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#5629]
The repository rules are implemented in a way that we can only test with *one* SDK and NDK version at any time. This affects the way our tests are written, and significantly reduces test coverage for older SDK/NDK versions if we rewrite them to test against the latest version.

It'll be great to have a way to either extend Bazel's internal capability to switch between Android SDK and NDK versions, and test against a range of versions.

**Comment by aj-michael** [comment]
What do you mean by SDK version? The android_sdk_repository rule already supports multiple API levels to compile against. It seems to me that the problem is not in the repository rule, but in the —android_sdk flag that forces a single API level for the whole build.
