### ISSUE TITLE
Difficulties accessing a file within an action created by an action from another rule

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel#5630]
### Description of the problem / feature request:

I am writing a js rule that bundles es modules by parsing the files import statements. It is very common to use relative imports from within a module, which works fine if the file trying to be imported is a source file, but it does not work if it is a file that has been created by another rule.

Digging deeper, the problem seems to be that the files that have been generated by rules are in the right path but under the `ctx.bin_dir.path` where-as static source files of the same package are not. 

The bundler does not have any built-in option to look for the files in different directories so it would be quite inconvenient having to go and change the behaviour of the bundler to accommodate a behaviour which seems quite unexpected in the first place.

I have managed to workaround this issue by using an empty `expand_template` to basically copy all files into the `bin_dir` and then point the bundler to the bindir but that feels quite hacky and like it would not scale.

### Feature requests: what underlying problem are you trying to solve with this feature?

Reference a generated file relative to another without having to know anything about bin_dir.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

To illustrate the issue in a much simplified way, just clone https://github.com/Globegitter/bazel-repro and run `bazel build :bundle`

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

release 0.15.2

###  Have you found anything relevant by searching the web?

No

**Comment by dkelmer** [comment]
In order to access the location of generated files you need to use $(location label) https://docs.bazel.build/versions/master/be/make-variables.html#location

**Comment by Globegitter** [comment]
But that does not work in the case of a js bundler. The bundler reads the entry point source file it gets passed in, then just sees stuff like `import bla from `component/mygeneratedcomponent`; or similar. It does not know anything about bazel and does not get passed in anything explicitly from bazel. I know in other cases this is done by overriding how the import works but this bundler does not have such an option and just imports based on standard js semantics. Why does the underlying tool have to know that this file is actually in a different location? It should be transparent for the tool.

**Comment by comius** [comment]
Closing, because this is a stale support request, because genfiles_dir was deprecated in the mean time (however not yet completely removed)
