### ISSUE TITLE
Skylark http_file does not preserve downloaded file's extension

### ISSUE THREAD

**Issue by mmorearty** [bazelbuild/bazel#5633]
### Description of the problem / feature request:

The title above may be a bit imprecise. Let me explain. If use the soon-to-be-deprecated `native.http_file` to download, say, a `.c` file, then I will be able to pass that file to rules that require C files, such as `cc_binary`.

But if I use the newer `http_file` that I load from `@bazel_tools//tools/build_defs/repo:http.bzl` (as described [here](https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#remove-native-http-archive)), then `cc_binary` complains that the file does not have a `.c` extension.

The new `http_file` is described as a drop-in replacement for the old `native.http_file`. This behavior is different, so we probably need to either:

1. (ideally) change the new one to mimic the old one's behavior, or
2. document this difference, and how to work around it.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`WORKSPACE`:

```
load(":download.bzl", "download_files")

download_files()
```

`download.bzl`:

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

def download_files():
    native.http_file(         # <---- this line is key
        name = "hello_c",
        urls = ["https://raw.githubusercontent.com/laristra/c-makefile/be51f16936f81329f3c88924d70cda20a88576c3/helloworld.c"],
        sha256 = "0a73a000d038412210a75184276966a97a5d0b8c128adf7f376b18564d4552c0"
    )
```

`BUILD`:

```
cc_binary(
	name = "hello",
	srcs = ["@hello_c//file"],
)
```

`$ bazel build :hello`

That will succeed (albeit with a warning from cc_binary). But then if you edit `download.bzl` to change `native.http_file` to just `http_file`, then you get this error message:

```
ERROR: BUILD:3:9: in srcs attribute of cc_binary rule //:hello: '@hello_c//file:file' does not produce any cc_binary srcs files (expected .cc, .cpp, .cxx, .c++, .C, .c, .h, .hh, .hpp, .ipp, .hxx, .inc, .S, .s, .asm, .a, .lib, .pic.a, .lo, .lo.lib, .pic.lo, .so, .dylib, .dll, .o, .obj or .pic.o)
```

### What operating system are you running Bazel on?

macOS 10.13.6

### What's the output of `bazel info release`?

release 0.15.2-homebrew

###  Have you found anything relevant by searching the web?

No

**Comment by mmorearty** [comment]
cc @aehlig

**Comment by aehlig** [comment]
I see the desire so simply build against an http_file, but you should
realize that the behaviour of the native rule is fully broken. E.g.,
consider the following situation.

```
$ echo Some aribtrary octets > /tmp/BUILD
$ cat WORKSPACE 
http_file(
  name = "file",
  urls = ["file:///tmp/BUILD"],
)
$ bazel build @file//...
(11:01:01) INFO: Current date is 2018-07-19
(11:01:01) ERROR: /usr/local/google/home/aehlig/.cache/bazel/_bazel_aehlig/fc209bf4e93f1e9752dcc887a678dd51/external/file/BUILD:1:6: syntax error at 'aribtrary': expected newline
(11:01:01) ERROR: /usr/local/google/home/aehlig/.cache/bazel/_bazel_aehlig/fc209bf4e93f1e9752dcc887a678dd51/external/file/BUILD:1:1: name 'Some' is not defined
(11:01:01) ERROR: package contains errors: 
(11:01:01) ERROR: error loading package '@file//': Package '' contains errors
(11:01:01) INFO: Elapsed time: 0.077s
(11:01:01) INFO: 0 processes.
(11:01:01) FAILED: Build did NOT complete successfully (0 packages loaded)
$ 
```

Moreover, preserving "the" extension of the downloaded file is not a
well-defined notion anyway. We allow several alternative URLs to obtain
the octets from. Do we take the name of the first URL, or the URL where
we managed to get the file from? Do we honor http-redirects in name
resolution?

For the time being, I suggest you do what the warning tells you to do,
i.e., use a BUILD file like the following.

```
genrule(
  name = "hello_c",
  outs = ["hello.c"],
  srcs = ["@hello_c//file"],
  cmd =  "cp $< $@",
)

cc_binary(
name = "hello",
srcs = [":hello_c"],
)
```

In the long term, it might be an option to add an option to `http_file` specifying
the file name, provided we check the name for validity and conflict-freeness.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by mmorearty** [comment]
Thanks @aehlig . I'm unclear on what problem is being demonstrated in your first example — certainly I can see that the BUILD file that's being loaded via http_file is invalid, so Bazel reports errors, but I'm not quite sure on what aspect of this means the native rule is fully broken. But that's okay :)

As for the extension, yes, I had the same thought myself, that since http_file can have multiple URLs, it doesn't make sense for it to have "an" extension. Honestly I was surprised that it behaved that way (we have some build files that rely on this behavior, and I was surprised to see that). If http_file was going to support the concept of a filename, I would have expected it to support something like `out = "hello.c"`.

In any case, thanks, I'll follow your suggestion of copying the file to another file that has the name I need.

**Comment by davido** [comment]
I pointed out exactly the same problem we are facing gerrit code review in mailing list: [1].

Quoting here:

```
2. http_file Skylark variant is not a drop in replacement for
native http_file rule, unfortunately. The provided file name is
now hard coded to always be "downloaded": [2]. So in our case,
native http_file was previously "polymer_closure.js". To satisfy
the follow-up processing (closure compiler) we have to add an
intermediate steps to rename "downloaded" to required file
with ".js" suffix: [3]. This could be probably improved.
```

We ended up to copy downloaded file to rename it to the right file name (with ".js" sufix, as required by Closure compiler) after downloading.

[1] https://groups.google.com/d/topic/bazel-discuss/dO2MHQLwJF0/discussion
[2] https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/http.bzl#L77
[3] http://paste.openstack.org/show/722557

**Comment by aehlig** [comment]
> Thanks @aehlig . I'm unclear on what problem is being demonstrated in your first example — certainly I can see that the BUILD file that's being loaded via http_file is invalid, so Bazel reports errors, but I'm not quite sure on what aspect of this means the native rule is fully broken. But that's okay :)

The example demonstrates that, if I download a file from a URL that happens to
end in a reserved name (`WORKSPACE`, `BUILD`, `BUILD.bazel`) the respective
file in the external repository gets overridden. And that is plain wrong.
No matter which URL I download a file, the BUILD file in the external
http_file repository should be the one generated by the rule and provide
me with the //file:file target.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment]
> The example demonstrates that, if I download a file from a URL that happens to
> end in a reserved name (`WORKSPACE`, `BUILD`, `BUILD.bazel`) the respective
> file in the external repository gets overridden.

Actually, it is the other way round: die downloaded file gets overwritten
by the generated file. But that's equally wrong, as the downloaded file
then no longer is in the external repository at all. And all that by only
changing the order of the mirrors...

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by xingao267** [comment]
Experiencing the similar issue here. I use the output of http_file rule in a pkg_tar rule, which enforces the input to be one of https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/pkg/pkg.bzl#L19. With the skylark http_file rule, I will need to rename it first. I agree with adding an option to `http_file` specifying the downloaded file name.

**Comment by nlopezgi** [comment]
It seems to me that allowing the user to specify the name of the downloaded file would solve all the issues and would not be hard to implement (as long as the list of forbidden names is well known). Is this something that could be considered for implementing soon (as in, before the old rules are deprecated)? Considering the number of files that we currently obtain in this way (and for which there are rules that depend on the name), refactoring all of them to use the proposed genrule approach seems like more effort than changing the rule to support specifying the name. Please let us know, Thanks!

**Comment by benjaminp** [comment]
Is this considered fixed now via 2c9c05b3960914b9120566bf680f2280c1857f82?

While I understand the old behavior was broken, it feels disingenuous to advertise the Starlark HTTP workspace rules as "drop-in replacements" for the native rules when they have significantly differing behavior like this.

**Comment by davido** [comment]
Yes, it was fixed, we were able to remove intermediate rename step: [1].

[1] https://gerrit-review.googlesource.com/c/gerrit/+/197090

**Comment by drigz** [comment]
@aehlig Is there any documentation for this incompatibility? It's not mentioned in the [Backward Compatibility docs](https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#remove-native-http-archive). I was only able to find out about `downloaded_file_path` by finding this issue, then clicking through benjaminp's comment.
