### ISSUE TITLE
Implement fast symbol lookup in the interpreter

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#5638]
We talked about speeding up the interpreter by avoiding hash maps for variable lookup. We should be able to assign statically an integer to each variable.

Unfortunately, we can't do this safely right now because of a bug in the interpreter (https://github.com/bazelbuild/bazel/issues/5637). In some cases, the name resolution is not static. Once the bug is fixed, that should be feasible.

cc @ttsugriy

**Comment by meisterT** [comment]
I assume @alandonovan's work makes this obsolete?

**Comment by laurentlb** [comment]
I'd say it's part of Alan's work. You first need the static resolution before you can generate (decent) bytecode.

**Comment by alandonovan** [comment]
What Laurent said. The following changes are necessary first:
- decouple thread from module (CL 309983907, in review)
- adding loadBindsGlobally option to resolver (will port go.starlark.net resolver)
- making the prelude behave like a load statement (no shared syntax trees -> recordScope always one)  (CL 309105613, in progress)
- use arrays for local variables (the actual optimization; it is trivial)

**Comment by brandjon** [comment]
Alan implemented this some time ago.
