### ISSUE TITLE
Support .aar files

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/bazel#564]
... similarly to `java_import`, we need a way to use `.aar` files in Android builds.

**Comment by davidzchen** [comment]
Related: https://github.com/bazelbuild/bazel/issues/561

**Comment by paladine** [comment]
This issue should be raised in priority given that the new Google Play Services ships exclusively in AAR format. It no longer ships in a buildable form. Therefore you can't really build an Android application with bazel that utilizes Play Services.

What we really need is support for external AAR files, like new_local_repository where you can define all the aar Google Play Service files, and have dependencies on them from your android_library/binary

**Comment by damienmg** [comment]
@ahumesky This is definitely a P1 now, is this beeing working on?

**Comment by ahumesky** [comment]
Was there some announcement somewhere about Google Play Services no longer updating google-play-services.jar (<sdk>/extras/google/google_play_services/libproject/google-play-services_lib/libs/google-play-services.jar)?

Importing AARs is blocked on the unpredictable action outputs work, which is being worked on, but it's not in a stable state right now. We could possibly come up with a workaround where the android_sdk_repository rule inspects the pom files and aar files in the android sdk's local maven repository where the google play services are, and generates a build file with genrules that unzips the aars and creates the other rules (java_impor, android_library, etc). It would be a pretty big hack. I'm not sure when we could find the cycles for that, it would be at least a few weeks.

**Comment by BrianEdmonds** [comment]
I needed this for personal use, so here's your hack, which I whipped up this morning. How I've run it:

$ cd <WORKSPACE>/android
$ mkdir com.android.support
$ cd com.android.support
$ <PATH/TO>/m2repo2build.sh

Then depend on something like //android/com.android.support:appcompat-v7. Lather, rinse, repeat for other m2repository packages (eg. com.google.firebase, com.google.android.gms, etc). You'll need to modify the script to point to your android-sdk-linux directory. No guarantee of function on any platform, but it works nicely for me so far.

[m2repo2build.zip](https://github.com/bazelbuild/bazel/files/405200/m2repo2build.zip)

**Comment by BrianEdmonds** [comment]
Turns out it needed some hacking to work on MacOS, and I wasn't dealing with implementation jars, and was getting the custom_packages wrong, but that is now accounted for. Again definitely still a hack, and no guarantees it'll do anything useful for anyone else.

[m2repo2build.zip](https://github.com/bazelbuild/bazel/files/405963/m2repo2build.zip)

**Comment by damienmg** [comment]
@ahumesky : ping can we resolve this in the following week? It looks like we need to drop it from 0.4 but that seems serious enough for not dropping it. It might need retriage.

**Comment by ahumesky** [comment]
The underlying mechanism (unpredictable action outputs) isn't ready yet, so it's pretty unlikely to be resolved next week. We could pursue the hacks mentioned above, but we even for that we won't have time to work on this for a few weeks at least.

**Comment by damienmg** [comment]
Dropping to milestones 0.5 :( [sadpanda]

**Comment by BrianEdmonds** [comment]
Just saying, the script I posted is working great for me. I'd be happier with a real, baked in solution, but if that is a whole extra major milestone away, you might want to include some hints on how to work around it in the mean time.

**Comment by aj-michael** [comment]
Just to confirm what has already been said about google-play-services being .aar only, with the current Google Play Services (version 32) installed:

```
$ bazel build @androidsdk//:google_play_services
...
ERROR: missing input file '@androidsdk//:extras/google/google_play_services/libproject/google-play-services_lib/AndroidManifest.xml'.
ERROR: /usr/local/google/home/ajmichael/.cache/bazel/_bazel_ajmichael/1b3a644758ec22c3d80472e8df5aba01/external/androidsdk/BUILD:5:1: @androidsdk//:google_play_services: missing input file '@androidsdk//:extras/google/google_play_services/libproject/google-play-services_lib/AndroidManifest.xml'.
Target @androidsdk//:google_play_services failed to build
...
```

**Comment by sbilkoloft** [comment]
@aj-michael can u kindly give me an example how to use aar_import? I know it's not documented on purpose and people aren't supposed to be using it yet, but I don't mind if it breaks in the future as long as it can unblock us now.

**Comment by aj-michael** [comment]
Hi @sbilkoloft, sorry for the delay. If you build bazel from HEAD, you can use the rule as

```
aar_import(
    name = "myaar",
    aar = "my-local-aar.aar",
)

aar_import(
    name = "myotheraar",
    aar = "my-other-local-aar.aar",
    exports = [
        ":myaar",
    ],
)

android_library(
    name = "mylib",
    ... 
    deps = [":myotheraar"],
)
```

This will give your android_library or android_binary access to the classes and resources from the AAR. If you have any questions or feedback, please let me know.

**Comment by sbilkoloft** [comment]
Hi @aj-michael,

For the record, seems like the code snippet posted above doesn't work as is. Does the 'aar' field have to be a path? If so, it doesn't accept absolute paths (says it cannot start with '/'). I also tried creating a symlink to my aar file and referencing it locally. Got an error that bazel-out/.../_aar/unzipped/myaar doesn't exist.

**Comment by lingz** [comment]
@aj-michael I'm getting the same error sbilkoloft is reporting. bazel-out/../_aar/ etc doesn't exist

**Comment by aj-michael** [comment]
@sbilkoloft The 'aar' field is a path relative to the BUILD file. Think of it like how "srcs" works on android_binary. It cannot accept absolute paths because Bazel rules only have access to the files in the package. I haven't tried it with symlinks, but it's intended to be used with the AAR in your source tree.

From the partial error snippet you posted, that is likely do to this bug, https://github.com/bazelbuild/bazel/issues/1928, that occurs if the AAR does not have any resources. The workaround for now is to use the `--spawn_strategy=standalone` to disable Bazel sandboxing.

**Comment by aj-michael** [comment]
As of 3f008a0, #1928 is closed, so `aar_import` will no longer require `--spawn_strategy=standalone` in all Bazel binaries built after that commit. Marking this issue as fixed as `aar_import` is now supported.

**Comment by aj-michael** [comment]
I closed this issue a bit too soon. b5f480c was just committed which is also required for `aar_import` to run in the Bazel sandbox.

There is one change remaining, which is to document this rule. Reopening until that is submitted.

**Comment by merryHunter** [comment]
Probably, I am doing something wrong, but when I am trying to include aar of gvr sdk as shown in the example documentation, I get:
....
> Cannot stat file /home/ivan/.cache/bazel/_bazel_ivan/94788c7f3adc99cf31db5cbecde32303/bazel-sandbox/5e63d754-5cf1-441e-853c-1f98fdc9fd06-17/execroot/tutorial/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/android/_aar/unzipped/resources/google-vr-sdk_b/res/values: No such file or directory
....
> ivan@ivan:~/projects/isee/examples/tutorial$ bazel build //android:android --verbose_failures
INFO: Found 1 target...
ERROR: /home/ivan/projects/isee/examples/tutorial/android/BUILD:11:1: Processing Android resources for //android:google-vr-sdk_a failed: linux-sandbox failed: error executing command 
  (cd /home/ivan/.cache/bazel/_bazel_ivan/94788c7f3adc99cf31db5cbecde32303/bazel-sandbox/108a9868-f2ae-466c-bd3b-47b6ff0aa1b2-0/execroot/tutorial && \
  exec env - \
  /home/ivan/.cache/bazel/_bazel_ivan/94788c7f3adc99cf31db5cbecde32303/execroot/tutorial/_bin/linux-sandbox @/home/ivan/.cache/bazel/_bazel_ivan/94788c7f3adc99cf31db5cbecde32303/bazel-sandbox/108a9868-f2ae-466c-bd3b-47b6ff0aa1b2-0/linux-sandbox.params -- bazel-out/host/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/AndroidResourceProcessingAction --buildToolsVersion 24.0.3 --aapt bazel-out/host/bin/external/androidsdk/aapt_binary --annotationJar external/androidsdk/tools/support/annotations.jar --androidJar external/androidsdk/platforms/android-23/android.jar --primaryData bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/android/_aar/unzipped/resources/google-vr-sdk_a::bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/android/_aar/google-vr-sdk_a/AndroidManifest.xml --packageType LIBRARY --rOutput bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/android/google-vr-sdk_a_symbols/R.txt --symbolsTxtOut bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/android/google-vr-sdk_a_symbols/local-R.txt --srcJarOutput bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/android/google-vr-sdk_a.srcjar --manifestOutput bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/android/google-vr-sdk_a_processed_manifest/AndroidManifest.xml --resourcesOutput bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/android/google-vr-sdk_a_files/resource_files.zip '--useAaptCruncher=no' --debug).
Error parsing command line: While parsing option --primaryData: invalid UnvalidatedAndroidData: bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/android/_aar/unzipped/resources/google-vr-sdk_a does not exist
Try --help.
Target //android:android failed to build

Instead, with `--spawn-strategy=standalone` the build is done successfully!
My BUILD file:
`aar_import(
        name = "google-vr-sdk_c",
        aar = "gvr-libraries/sdk-common-1.10.0.aar",    )
aar_import(
        name = "google-vr-sdk_a",
        aar = "gvr-libraries/sdk-audio-1.10.0.aar",    )
aar_import(
        name = "google-vr-sdk_b",
        aar = "gvr-libraries/sdk-base-1.10.0.aar",    )

android_binary(
    name = "android",
    custom_package = "com.google.bazel.example.android",
    manifest = "src/main/java/com/google/bazel/example/android/AndroidManifest.xml",
    resource_files = glob(["src/main/java/com/google/bazel/example/android/res/**"]),
    visibility = ["//visibility:public"],
    deps = [":activities",]
)
android_library(
    name = "activities",
    srcs = glob(["src/main/java/com/google/bazel/example/android/activities/*.java"]),
    custom_package = "com.google.bazel.example.android.activities",
    manifest = "src/main/java/com/google/bazel/example/android/activities/AndroidManifest.xml",
    resource_files = glob(["src/main/java/com/google/bazel/example/android/activities/res/**"]),
    deps = [":google-vr-sdk_a",	":google-vr-sdk_b",":google-vr-sdk_c"]
)`
Bazel version 0.4.3

**Comment by merryHunter** [comment]
@aj-michael  thank you! I thought I had checked the commit timeline, but I was mistaken.

**Comment by DandyLorenz** [comment]
Can you help me see how to solve this problem?Thanks. https://github.com/google/mediapipe/issues/1450
