### ISSUE TITLE
Do not hardcode path to LCOV tool

### ISSUE THREAD

**Issue by zaycev** [bazelbuild/bazel#5644]
Hi!

Is there a reason why the path to LCOV is hardcoded here?:
https://github.com/bazelbuild/bazel/blob/4af3da48f848c1666635deab7a50072fb3d9a8f4/tools/test/collect_coverage.sh#L143

This makes it impossible to use Bazel coverage command when lcov is installed into a diffirent location. In `0.15.2`, Bazel will generate empty dat files.

Thanks!

**Comment by iirina** [comment]
Hi Vladimir,

There is no specific reason for the hardcoded path other than easy implementation. Coverage support is not in a good shape and it's something we are working on improving this quarter - not hardcoding the lcov path is one of the things on our agenda.
