### ISSUE TITLE
feature request: ppc64le package of bazel in bazel-apt respository

### ISSUE THREAD

**Issue by grooverdan** [bazelbuild/bazel#5657]
### Description of the feature request:

Please add a ppc64le package for bazel to the following apt repository
'deb http://storage.googleapis.com/bazel-apt stable jdk1.8'

### Feature requests: what underlying problem are you trying to solve with this feature?

The ability to consume bazel on POWER8/9 hardware in a CI environment.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

<pre>
# add-apt-repository 'deb http://storage.googleapis.com/bazel-apt stable jdk1.8'
# wget https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg -O - | apt-key add -
# apt-get update
...
N: Skipping acquire of configured file 'jdk1.8/binary-ppc64el/Packages' as repository 'http://storage.googleapis.com/bazel-apt stable InRelease' doesn't support architecture 'ppc64el'
# apt-get install bazel
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package bazel
</pre>

### What operating system are you running Bazel on?

Ubuntu-18.04, ppc64le

**Comment by grooverdan** [comment]
ref: https://oplab9.parqtec.unicamp.br/pub/ppc64el/bazel/readme.html

**Comment by aiuto** [comment]
It's a reasonable request, but it is not likely to happen in the near future, as we don't have a set of PPC machines in our CI system.

**Comment by philwo** [comment]
@grooverdan Any idea where we could get PowerPC machines for our CI?

We can't add binaries to our apt-get repository that we didn't build ourselves.

**Comment by aiuto** [comment]
Can we cross-compile for PPC?

**Comment by philwo** [comment]
Maybe... it would be a nice way to exercise the platforms feature of Bazel :D I don't know anything about how to setup cross-compiling though (with or without Bazel).

Also, how would we test the binaries? Qemu in full emulation mode might be way too slow, I guess? And how does a typical "PowerPC machine" these days look like?

**Comment by aiuto** [comment]
FWIW, I believe I do have at least one PPC architecture machine in the museum collection storage here. Pulling it out and getting ubuntu up on it might be fun, but a time consuming project none-the-less

**Comment by grooverdan** [comment]
Rather than pulling out the museum pieces, and having too much fun, there's hosting available https://osuosl.org/services/powerdev/. I realize the CI service is extensively Jenkins based so maybe just the hosted service. If this doesn't work out, ping me and I'll see what other options I can find.
