### ISSUE TITLE
Support verification of external repositories

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/bazel#5660]
For external repositories that are supposed to fetch sources (like `git_repository`, `http_archive`) we expect the generated directory for the external repository to be reproducible. While we generally trust the rule authors to achieve this, there is no way of verification (similarly, we trust build rules to declare all dependencies, but still use sandboxing to detect missing declarations).

With the `--eperimental_repository_resolved_file` we already have means of [recording the output of repository rules](https://blog.bazel.build/2018/07/09/bazel-sync-and-resolved-file.html) in machine-readable form that is suitable to be committed to the repository. Adding a hash here, and options to verify the hash, would allow developers on different machines to verify that they fetched the same external repository.

**Comment by aehlig** [comment]
Current state is that a hash of the output directory is included in the resolved file since 49212c43c1aef61319d69760ca79151636988b68. Following and freezing dependencies still works as described in the blog post on [bazel sync and resolved files](https://blog.bazel.build/2018/07/09/bazel-sync-and-resolved-file.html) and the resolved file also contains an additional entry `output_directory_hash` in each repository dict. So, by specifying `--experimental_repository_hash_file=$(pwd)/resolved.bzl` and `--experimental_verify_repository_rules='@bazel_tools//tools/build_defs/repo:git.bzl%git_repository'` (or any other repository rule you care about) as in the [newly added test](https://github.com/bazelbuild/bazel/blob/24d3a01b53a603059091a690e0bddb20ef5fbc98/src/test/shell/bazel/workspace_resolved_test.sh#L517) incorrect checkouts are detected.

Not a great interface (too many options needed), but any early feedback would be appreciated.

**Comment by edbaunton** [comment]
This all looks reasonable to me. 

1. Is the plan to always produce `WORKSPACE.resolved` or only when `--experimental_repository_resolved_file` is specified?

1. Do you think it would be effective to leverage etags as an optimisation to the http rules to prevent excessive redownloading of unchanged content during `bazel sync`? Do we trust the web server enough?

1. I was wondering whether it would be useful to keep the `.git` directory outside of the tree using the `--git-dir` option to `git`, that way you wouldn't have to remove it. It might make certain debugging cases easier. I guess you don't actually need the directory for later git operations (it would make things faster), we simply clone everything anew every time.

**Comment by aehlig** [comment]
As of 877f4cec14fbf79b3cb85a17723b793d2744030f verification of repositories is opt-in, and, if I understand the plans for bazel correctly, there are no plans to make it mandatory.
