### ISSUE TITLE
mobile-install fails on a python 3 system

### ISSUE THREAD

**Issue by fhucho** [bazelbuild/bazel#567]
I followed the tutorial with bazel 0.1.1 but `bazel mobile-installl //android:android` fails when my `/usr/bin/python` points to a Python 3 binary. This is the output:

```
INFO: From Installing //android:android:
  File "bazel-out/host/bin/external/default_android_tools/tools/android/incremental_install", line 97
    except EnvironmentError, e:
                           ^
SyntaxError: invalid syntax
```

When `/usr/bin/python` points to Python 2, it works fine.

**Comment by kchodorow** [comment]
We should use Python syntax that's compatible with 2 or 3.

**Comment by damienmg** [comment]
We do not support Python 3 yet. A lot of work needed to be done for that especially have 2to3 in the bazel repository (this is open-source so no problem). @lberki for his insights.

**Comment by lberki** [comment]
Yep. In theory, we could make the Python scripts work with Python 2 and 3, but I think we all have more pressing issues to take care of (I wish I could just do this now...) If you send a change my way, I'll gladly review it, though ;)

**Comment by fhucho** [comment]
The fact that Python 3 is not supported should be explicitly mentioned on bazel.io, e.g. in System Requirements. I assumed that if Ubuntu is supported, it should work on my Arch Linux too.

**Comment by ahumesky** [comment]
I scanned through incremental_install.py
https://github.com/bazelbuild/bazel/blob/c484f19a2cf7427887d6e4c71c8534806e1ba83e/tools/android/incremental_install.py

and it looks like we updated the except clauses.
