### ISSUE TITLE
Tensorflow downstream failing on windows 

### ISSUE THREAD

**Issue by dkelmer** [bazelbuild/bazel#5677]
Link to last night's run: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/360#bedc24a2-98b8-4449-bfae-d66786fbc815

ERROR: Unrecognized option: --experimental_shortened_obj_file_path=true

**Comment by jin** [comment]
Since @meteorcloudy is OOO, I'll mailing a fix to TF to remove this from from their `configure.py`. I'd like to see TF passing in the chosen nightly before cutting the release.

**Comment by jin** [comment]
cc @mhlopko
