### ISSUE TITLE
Android rules should accept JavaInfo providers.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/bazel#5678]
I am prototyping with android support in the Kotlin rules. The Android rules  require jars to be `java_import`'ed. I don't see a work around to this as it applies transitively to all deps.

**Comment by ahumesky** [comment]
This commit should enable the android rules to depend on rules which have the javainfo provider:
https://github.com/bazelbuild/bazel/commit/c68645fda6198a46ac510c832c9b374ae3f20680

Which version of bazel are you working with?

**Comment by hsyed** [comment]
Version and error:

```
➜  android git:(hs_android) ✗ bazel version
Build label: 0.15.2-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jul 17 13:06:19 2018 (1531832779)
Build timestamp: 1531832779
Build timestamp as int: 1531832779
➜  android git:(hs_android) ✗ bazel mobile-install :android
ERROR: /Volumes/work/src/github.com/hsyed/rules_kotlin/examples/android/BUILD:35:12: in deps attribute of android_binary rule //examples/android:android: Dependencies on .jar artifacts are not allowed in Android binaries, please use a java_import to depend on examples/android/activities_kt.jar. If this is an implicit dependency then the rule that introduces it will need to be fixed to account for it correctly.
ERROR: Analysis of target '//examples/android:android' failed; build aborted: Analysis of target '//examples/android:android' failed; build aborted
INFO: Elapsed time: 0.136s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

sandwich structure I am prototyping with:

```py
java_import(
    name = "android-sdk",
    jars = ["@androidsdk//:platforms/android-27/android.jar"]
)

android_library(
  name = "activities_base",
  custom_package = "com.google.bazel.example.android.activities",
  manifest = "src/main/java/com/google/bazel/example/android/activities/AndroidManifest.xml",
  resource_files = glob(["src/main/java/com/google/bazel/example/android/activities/res/**"]),
)

kt_jvm_library(
    name = "activities_kt",
    srcs = ["src/main/java/com/google/bazel/example/android/activities/MainActivity.kt"],
    deps = ["android-sdk", ":activities_base"]
)

android_library(
    name ="activities",
    exports = [
        ":activities_base",
        ":activities_kt",
    ],
)

android_binary(
    name = "android",
    custom_package = "com.google.bazel.example.android",
    manifest = "src/main/java/com/google/bazel/example/android/AndroidManifest.xml",
    resource_files = glob(["src/main/java/com/google/bazel/example/android/res/**"]),
    deps = [":activities"],
)
```

**Comment by ahumesky** [comment]
I believe the problem here is that the android incremental dexing aspect is not traversing the kotlin rules. 

Try adding `provides = [JavaInfo]` to the skylark rule definitions.

You may also need to add an attribute called `runtime` to any kotlin toolchain rules so that the aspect will dex the jars from the runtime. Something like:

    def _kotlin_toolchain_impl(ctx):
      toolchain = dict(
          ....,
          runtime = java_common.create_provider(
              runtime_jars = ctx.files.runtime,
              use_ijar = False,
          ),
          ....,
      )
      return [
          platform_common.ToolchainInfo(**toolchain),
          ....
      ]

    kotlin_toolchain = rule(
        _kotlin_toolchain_impl,
        provides = [platform_common.ToolchainInfo],
        attrs = dict(
            ....,
            runtime = attr.label_list(
                default = [
                    Label("..."),
                    Label("..."),
                ],
                cfg = "target",
                doc = "kotlin runtime libraries."
            ),
            ....,
        ),
    )

**Comment by hsyed** [comment]
@ahumesky I've created a [scratch branch](https://github.com/bazelbuild/rules_kotlin/tree/hs_android) Could you please have a look. 

//example/android contains a `android.bazelproject`. 

The last commit in the branch adds changes to the rules. I added the changes you suggested, the `provides =[JavaInfo]` got me further along. But I am back in the same spot again it seems:

```
ERROR: /Volumes/work/src/github.com/hsyed/rules_kotlin/examples/android/BUILD:33:12: in deps attribute of android_binary rule //examples/android:android: Dependencies on .jar artifacts are not allowed in Android binaries, please use a java_import to depend on external/com_github_jetbrains_kotlin/lib/kotlin-runtime.jar. If this is an implicit dependency then the rule that introduces it will need to be fixed to account for it correctly.
```

The stdlib deps added implicitly in the rules causes the jars to be selected as deps. Adding the stdlibs explicitly in the example targets overrides this and the error doesn't occur.

**Comment by ahumesky** [comment]
Hmm, according to https://github.com/bazelbuild/bazel/commit/8fe4bec124fe5ec8324ad9c2efbc19d0e7c899f9 it looks like the attribute pointing to the toolchain has to be named "_toolchain".

It looks like this is named "_kotlin_toolchain" according to this:
https://github.com/bazelbuild/rules_kotlin/compare/hs_android#diff-c1e2efe3b75290b72110dae408b1eea3R126

What happens when you rename that to "_toolchain"?

**Comment by ahumesky** [comment]
Also I think this:
https://github.com/bazelbuild/rules_kotlin/compare/hs_android#diff-23f54ef09639bef0c873a55685756bbfR123
needs to be called "runtime_deps"

(that's what I gather from "runtime_deps" being here: https://github.com/bazelbuild/bazel/commit/8fe4bec124fe5ec8324ad9c2efbc19d0e7c899f9#diff-428ec33c9df1695dc8ede21f7795aec8R112)

**Comment by kevin1e100** [comment]
Just for context, making incremental dexing work boils down to making all Jars that are part of an app's runtime classpath reachable through attributes and rules with providers configured [here](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/android/DexArchiveAspect.java#L133), keeping in mind that $ should be written _ in skylark.

Typically this involves:

1. All build rules, e.g., kt_jvm_library, that compile Jars need to declare that they provide JavaInfo
2. Implicitly added Jars, such as the Kotlin runtime Jars, are easiest handled through a separate "toolchain" rule.  To make that work, rules should use the attribute name "_toolchain" to depend on the toolchain rule, the toolchain rule needs to be declared to provide ToolchainInfo (or JavaInfo, but that typically doesn't make sense), the toolchain rule needs to use whitelisted attribute names to depend on the Jars (e.g., "runtime" or "aidl_lib", whatever makes sense), and the Jars themselves must be wrapped into rules that provide JavaInfo, which typically means "wrapping" them into a java_import or similar rule.

Note that incremental dexing doesn't work when directly depending on a Jar file (either in explicitly listed "deps" or in implicit dependencies); instead, Jar files need to be "wrapped" in java_import or similar rules that provide JavaInfos.

Does this make sense?  Please let us know if you can make things work following these instructions.  For reference, the above guidelines "should" work for any language that compiles to bytecode, including Kotlin.

**Comment by hsyed** [comment]
@kevin

**Comment by hsyed** [comment]
Grr posting on an iphone is not fun. Didnt mean to close issue

@kevin1e100 ill go through your post in detail when i get back on the task but on point 2 kt_jvm_import and kt_jvm_library both return java_infos do they have to be wrapped. And if so will this still be the case as @jin progresses with his port of the rules to skylark ?

**Comment by kevin1e100** [comment]
kt_* rules don't need to be wrapped but they need to declare that they
provide JavaInfos, using rule()'s provides attribute.  The same goes for
any other skylark rules that provide Jars, so this needs to happen in any
rule migrations as well.

**Comment by hsyed** [comment]
[It's working](https://github.com/bazelbuild/rules_kotlin/pull/117) just needed to add the `_toolchain` containing the kotlin runtime to `kt_jvm_library`. Thanks for the help guys.
