### ISSUE TITLE
Bazel remote execution failing on CI with downstream projects

### ISSUE THREAD

**Issue by dkelmer** [bazelbuild/bazel#5680]
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/360#a3057134-c425-477f-916e-81315e462a59

With error: Couldn't build file external/com_google_protobuf/_objs/protoc_lib/java_generator.o: C++ compilation of rule '@com_google_protobuf//:protoc_lib' failed (Exit 1)
--
  | <The executable does not exist or a dependent library is missing>
  | <Check for missing .so/.dll in the .isolate or GN file>

**Comment by mhlopko** [comment]
I'm sorry I didn't have time to look into this one today. Will take a look tomorrow.

**Comment by jin** [comment]
This stopped happening in the latest nightlies now. Closing this for now, will reopen if it appears again. https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/366
