### ISSUE TITLE
bazel toolchains failing with downstream dependencies

### ISSUE THREAD

**Issue by dkelmer** [bazelbuild/bazel#5681]
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/360#be21b444-b113-4495-805a-ad3c5a770c08

Error: 'DefaultInfo' object has no attribute 'runfiles'

**Comment by c-parsons** [comment]
I believe https://github.com/bazelbuild/bazel-toolchains/pull/138 will solve this.

**Comment by dkelmer** [comment]
bazelbuild/bazel-toolchains#138 has been merged, closing for now but will note to follow up to make sure failures in nightly go away
