### ISSUE TITLE
rules_apple failing with downstream projects

### ISSUE THREAD

**Issue by dkelmer** [bazelbuild/bazel#5683]
rules_apple are failing with bazel at head: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/360#c1ba3035-bbe4-4335-a513-36ac4d25ab86

ERROR: /Users/buildkite/builds/buildkite-imacpro-3-1/bazel-downstream-projects/rules_apple/test/testdata/binaries/BUILD:12:1: Couldn't build file test/testdata/binaries/empty_staticlib-fl.a: Linking of rule '//test/testdata/binaries:empty_staticlib' failed (Exit 1)
--
  | /private/var/tmp/_bazel_buildkite/fe5a0746c5b6405e9a95248b5562d68d/sandbox/darwin-sandbox/8/execroot/build_bazel_rules_apple/external/local_config_cc/xcrunwrapper.sh: line 40: SDKROOT: unbound variable

I believe this https://github.com/bazelbuild/bazel/commit/d69b1c752587149269e9b0d1e7563bc5eb66be6a is the culprit

**Comment by jin** [comment]
@sergiocampama ping, PTAL and rollback if needed.

**Comment by sergiocampama** [comment]
This breakage was not caused by rules_apple, but by the bazel team making incompatible changes in bazel and then pushing them into rules_apple before they are released and tested.

We've updated the code in rules_apple, but integration tests are still broken as there's a missing piece in bazel, which I'm trying to submit right now. 

Once that happens, would it be possible to cherry pick it into a 0.16.X release?

**Comment by jin** [comment]
cc @c-parsons for 0.16.x cherrypicks

**Comment by sergiocampama** [comment]
@c-parsons  Would it be possible to cherrypick f330439? This fixes a discrepancy in how the rules access action_names.bzl internally vs externally.

**Comment by c-parsons** [comment]
Could you elaborate on the exact nature of this breakage? I'm at a bit of a loss in understanding why this is needed, as I'd like to entertain the possibility of a workaround before committing to a cherry-pick :)

**Comment by jin** [comment]
@sergiocampama today's nightly still has the same error: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/368#efbb1149-2436-4a22-9581-971fa77bb1fe

Is https://github.com/bazelbuild/bazel/commit/f330439fb970cfa17c70fc59c1458bb1c31c9522 expected to fix that?

**Comment by sergiocampama** [comment]
Ah, I confused the error, f330439 solves a different breakage. The fix for
this breakage is already out for review internally.

**Comment by jin** [comment]
Thanks - I'll cherrypick that into 0.17.0 rc2. We should also cherrypick that into 0.16.1.

**Comment by sergiocampama** [comment]
The fix has been submitted: 6bd0bdf5140525cb33dc2db068b210261d9df271

**Comment by sergiocampama** [comment]
Could f330439 also be cherrypicked? Hopefully into the 0.17 RC, but if it could be added to 0.16.1 that would be awesome :)

**Comment by sergiocampama** [comment]
We have travis (HEAD) tests working now, we just need 0.16.1 to be released in buildkite to be back into the green again

**Comment by sergiocampama** [comment]
rules_apple is green again
