### ISSUE TITLE
Usage of TreeArtifacts with cc_library produces non-deterministic output

### ISSUE THREAD

**Issue by castler** [bazelbuild/bazel#5686]
### Description of the problem / feature request:

When using `TreeArtifacts` with `cc_library` the output of the library is non-deterministic because order of object files in the resulting library can change even if same source tree is involved.

Presumably the order relies on (unsorted) listing as returned by the underlying filesystem.

In case of tree artifacts, it's likely OK to not care about specific order (since we're looking for "all of what was produced"; perhaps an alphabetic sort?), but the order nonetheless needs to remain stable. Among other problems, we're seeing false (remote) cache misses.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Create a library with multiple object files generated by a script used as TreeArtifacts. One could use the example given [here](https://stackoverflow.com/a/48524539).

2. Save the library that was created for later.

3. `bazel clean`

4. Build again.

5. Compare listing of libraries resulting from the previous and most recent build.

Across multiple runs (not always), different order of binary objects in the library can be observed and the resulting libraries hence being non-identical (different order, different digest, same binary objects included).

### What operating system are you running Bazel on?

Linux (Ubuntu 16.04, Slackware-14.2, Slackare-current).

### What's the output of `bazel info release`?

- release 0.15.0
- release 0.15.2

###  Have you found anything relevant by searching the web?

No

**Comment by ericfelly** [comment]
I was able to repro as follows:
```
$ for f in cxx/*; do echo "Print $f"; cat $f; echo "==========="; done
Print cxx/BUILD
load(":genccs.bzl", "genccs")

genccs(
    name = "gen_tree",
    tool = ":genccs",
)


cc_binary(
    name = "main",
    srcs = [ "gen_tree" ]
)

cc_binary(
    name = "genccs",
    srcs = [ "genccs.cc" ],
)

===========
Print cxx/genccs.bzl
def _impl(ctx):
  tree = ctx.actions.declare_directory(ctx.attr.name + ".cc")
  ctx.actions.run(
    inputs = [],
    outputs = [ tree ],
    arguments = [ tree.path ],
    progress_message = "Generating cc files into '%s'" % tree.path,
    executable = ctx.executable.tool,
  )

  return [ DefaultInfo(files = depset([ tree ])) ]

genccs = rule(
  implementation = _impl,
  attrs = {
    "tool": attr.label(
      executable = True,
      cfg = "host",
      allow_files = True,
      default = Label("//:genccs"),
    )
  }
)
===========
Print cxx/genccs.cc
#include <fstream>
#include <sys/stat.h>
#include <string>

int main (int argc, char *argv[]) {
  mkdir(argv[1], S_IRWXU);
  std::ofstream myfile;
  myfile.open(string(argv[1]) + string("/foo.cpp"));
  myfile << "int main() { return 42; }";

  for (int i = 0; i < 10; i++) {
      std::ofstream myfile;
      myfile.open(string(argv[1]) + string("/foo") + std::to_string(i) + string(".cpp"));
      myfile << "int xyz" << i <<"() { return 42; }";
  }
  return 0;
}
===========
```

```
$ bazel --batch clean && bazel --batch build //cxx:main && grep tree blaze-out/k8-opt/bin/cxx/main-2.params
blaze-out/k8-opt/bin/cxx/_objs/main/gen_tree/foo4.o
blaze-out/k8-opt/bin/cxx/_objs/main/gen_tree/foo9.o
blaze-out/k8-opt/bin/cxx/_objs/main/gen_tree/foo3.o
blaze-out/k8-opt/bin/cxx/_objs/main/gen_tree/foo8.o
blaze-out/k8-opt/bin/cxx/_objs/main/gen_tree/foo.o
blaze-out/k8-opt/bin/cxx/_objs/main/gen_tree/foo5.o
blaze-out/k8-opt/bin/cxx/_objs/main/gen_tree/foo6.o
blaze-out/k8-opt/bin/cxx/_objs/main/gen_tree/foo7.o
blaze-out/k8-opt/bin/cxx/_objs/main/gen_tree/foo2.o
blaze-out/k8-opt/bin/cxx/_objs/main/gen_tree/foo1.o
blaze-out/k8-opt/bin/cxx/_objs/main/gen_tree/foo0.o

```

The order is non-deterministic.

**Comment by buchgr** [comment]
According to @ericfelly this fix was rolled back. Should this be re-opened?

**Comment by castler** [comment]
@buchgr
So apparently https://github.com/bazelbuild/bazel/commit/287c1e7136ea07a538d57d3ad4d98aa36987736b reverted the fix. (But doesn't name any reasons for it).

I tried the repro on my local machine (0.22) and I could not reproduce it - but still I'm not sure if this is really fixed. At least it would be interesting what fixed it or if it was just "luck" that it worked now on my machine. What do you think?

**Comment by justinhorvitz** [comment]
I also get deterministic output for the repro mentioned above. I will however proceed with a roll-forward, as it seems safe to do so now.
