### ISSUE TITLE
cannot use bazel with protected nexus maven repository to fetch dependencies

### ISSUE THREAD

**Issue by waffel** [bazelbuild/bazel#5689]
### Description of the problem / feature request:

When using bazel in a coperated and restriced environment to build maven like projects, the transfer of external dependencies fails.

I started with a simple project from the bazel universum itself: https://docs.bazel.build/versions/master/generate-workspace.html

git clone https://github.com/bazelbuild/migration-tooling.git

When invoking the bazel command (as decribed in the documentation) 
`bazel run //generate_workspace`

It will fail with a transfer error.

I have modified the WORKSPACE file for this project to declare my own default maven repo (I have find out a way to declare this in .bazelrc):
`
maven_server(
    name = "default",
    url = "https://eb-conf-ci.siemens.net/nexus/repositories/public",
)
`
This is the error:

`ERROR: D:/dev/projects/git/migration-tooling/third_party/BUILD:5:1: no such package '@org_codehaus_plexus_plexus_interpolation//jar': Failed to fetch Maven dependency: Could not find artifact org.codehaus.plexus:plexus-interpolation:jar:1.24 in org_codehaus_plexus_plexus_interpolation (https://eb-conf-ci.siemens.net/nexus/repositories/public) and referenced by '//third_party:org_codehaus_plexus_plexus_interpolation'
`

### What operating system are you running Bazel on?

Windows 7

### What's the output of `bazel info release`?

release 0.15.0

###  Have you found anything relevant by searching the web?

No real answers for the mentioned problem. It is hard to find out, what is the real problem without any additional verbose output.

### Any other information, logs, or outputs that you want to share?

The nexus repository is protected with username and password. The password is encrypted in the maven settings.xml (which is forced by our security). But I have also tried to get it work with plain username and password in settings.xml.

I know that our proxy is not the problem because our nexus installation uses a self signed certificate and I need a "special" java with our internal root certificates. So if I use the wrong java I get certificate errors which indicated, the nexus service can be reached in general.

I have tried from command line and from IDEA.

I guess the problem has something to do with the username/password from maven settings.xml.

**Comment by jin** [comment]
@dslomov is generate_workspace still the recommended solution for transitive deps? If not, should we clarify it on the docs?

**Comment by waffel** [comment]
I do not know if this has in general todo with "generate_workspace". This was only one example project where the fetch of maven artifacts from nexus does not work.

For me it is a general issue how to include external maven dependencies with a protected repository management system (like nexus or artifactory).

For this is also not a feature request. It is a bug in the current version that this does not work (when this is in general not supported until now, ok ... then this may be a feature request :-))

**Comment by jin** [comment]
There's some complication here because there are currently three ways to download Maven dependencies.

1) `maven_jar` native repository rule
2) `maven_jar` rule implemented in Skylark, loaded as:

```
load("@bazel_tools//tools/build_defs/repo:maven_rules.bzl", "maven_jar")

maven_jar(
    name = "com_google_guava_guava",
    artifact = "com.google.guava:guava:18.0",
    settings = "//:settings.xml",
)
```

This uses `mvn` from your system to download the jars, and therefore respects the auth in the specified settings.xml. However, note that this is not scalable at all, since it shells out to the underlying `mvn` binary, as seen here.

and the latest, `java_import_external`/`jvm_maven_import_external`, which uses a highly robust native downloader, and drops the dependency on `mvn`. 

Please see https://github.com/bazelbuild/bazel/issues/5452 for more discussion on this.

**Comment by waffel** [comment]
Thanks for this information. 

I hope that the  `java_import_external/jvm_maven_import_external` way gets the authentication feature soon.

I will start my experiments with the `maven_jar` rule, but indeed we need this scale able approach because in our project with have >1000 dependencies for one big reactor.

Can we keep this issue open/updated until the 3. approach is ready to use authentication information and access protected repositories like nexus or artifactory?

**Comment by jin** [comment]
Update: https://github.com/bazelbuild/rules_jvm_external/ is now the recommend ruleset for resolving and fetching artifacts transitively with private repository authentication support.

**Comment by guw** [comment]
Thanks for the update. Given this prioritization I think it doesn't make sense to invest further in fixing this issue here and rather look at bazelbuild/rules_jvm_external#80
