### ISSUE TITLE
Integration testing kotlin android aspect without a local SDK installation or AS.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/bazel#5691]
I don't do any android development but I am working on support for android. I need to be able to integration test the Android aspect without having to setup a local SDK or having to install AS -- the tests should be runnable on the CI servers as well.  

I won't be able to commit to Android support unless I can easily verify it. 

I think the  android SDK  should be evolved into a toolchain and non-local SDK's should be supported -- AS is used to manage the SDK, I think the `android_sdk` should be able to download the cli tools and configure the SDK from the provided metadata.

**Comment by jin** [comment]
These are super great ideas :+1:, and thanks for your contributions! Breaking it down into individual feature requests:

1) Bazel can automatically download the Android SDK, call `sdkmanager` and download required components like `build-tools`, `platform-tools` and `android.jar`. 

[There is a project that replaces `android_sdk_repository` with a downloader version](https://github.com/quittle/bazel_android_sdk_downloader), so this might be a good workaround for the moment.

2) Implement `android_sdk` as a [Toolchain](https://docs.bazel.build/versions/master/toolchains.html), to take advantage of the new configurability mechanisms.
 
This is definitely the future of `android_sdk`. I started to look into this a while back at https://github.com/jin/android_sdk_bazel_toolchain.

As you might know, we're currently rewriting the native Android rules in Skylark, so all of these will be taken into account when designing for the new rules. I've added these feature requests to our [roadmap spreadsheet](https://docs.google.com/spreadsheets/d/1-BjWLdv3SKGnEBOdLmzPPhTPNErRVMQerjrI60N_DVs/edit#gid=1597615571).
