### ISSUE TITLE
how to use user-defined xxx_library in cc_library?

### ISSUE THREAD

**Issue by startcode** [bazelbuild/bazel#5700]
### Description of the problem / feature request:

Hi, I am trying to create a 'cuda_library', which is like 'cc_library', so that I can use it to compile some cuda code in my project. It is like the following:

```
cuda_library(
    name = "cuda_util",
    srcs = [
        "cuda_util.cu",
    ],
    hdrs = [
        "cuda_util.h",
    ],
    deps = [
    ],
)
```
My definition of 'cuda_library' is like
```
def cuda_library_impl(ctx):
    s = set()
    flags = ' '.join(ctx.attr.flags)
    output = ctx.outputs.out
    lib_flags = ["--shared", "--compiler-options '-fPIC'"]
    args = ctx.attr.flags + [f.path for f in ctx.files.srcs] + [f.path for f in ctx.files.deps]
    ctx.actions.run_shell(
            inputs=ctx.files.srcs + ctx.files.hdrs,
            outputs=[ctx.outputs.out],
            arguments=args,
            env={ 'PATH':'/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/bin', },
            command="/usr/local/cuda/bin/nvcc %s %s -o %s %s" % (' '.join(cuda_arch), ' '.join(lib_flags), output.path, " ".join(args))
    )

cuda_library = rule(
    attrs = {
        "hdrs": attr.label_list(allow_files = cuda_headers),
        "srcs": attr.label_list(
            allow_files = cuda_srcs,
            mandatory = True,
        ),
        "deps": attr.label_list(allow_files = False),
        "flags": attr.label_list(allow_files = False),
    },
    outputs = {"out": "lib%{name}.so"},
    implementation = cuda_library_impl,
)

```
Now I made it work. it can successfully generate `libcuda_util.so`, however, my other `cc_library` modules cannot depend on it. The error is like
```
cc_library can only depend on cc_library, objc_library ...
```

### Feature requests: what underlying problem are you trying to solve with this feature?

I want to find a way to let cc_library's dependency be more flexible, to include user-defined xxx_library

### What operating system are you running Bazel on?

ubuntu 16.04

### What's the output of `bazel info release`?

release 0.5.3

**Comment by rongjiecomputer** [comment]
Just put `:cuda_util` in `srcs` of a `cc_library` instead of `deps`.

**Comment by jin** [comment]
Hi, please ask questions (non-bugs or feature requests) on the [bazel-discuss mailing list](https://groups.google.com/forum/#!forum/bazel-discuss), or on [StackOverflow](https://stackoverflow.com/questions/tagged/bazel). Thanks!
