### ISSUE TITLE
Skylark should validate that only one instance of a provider is being returned by the rule

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#5709]
I received some complaints from a user that there's some very confusing behavior surrounding returned providers from a Skylark rule implementation.
Namely, if a rule implementation returns multiple providers of the same type, i.e.

```
MyProvider = provider()

def my_rule_impl(ctx):
   return struct(providers = [MyProvider(x = "foo"), MyProvider(x = " bar")])
```

that the last such provider is the only one propagated, and each other provider is silently dropped.

This reportedly led to about a day of lost work for this user, so this is likely a pattern we should error against.

**Comment by laurentlb** [comment]
Did you fix it?

**Comment by c-parsons** [comment]
Indeed. I must have lost track of this particular issue, as I filed a duplicate #5902 and tracked this fix there. Oops!
I want to leave that bug open to track the migration to the new flag. So perhaps we can close this?
