### ISSUE TITLE
incompatible_disable_objc_provider_resources

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#5710]
`ObjcProvider` resource fields are deprecated and will be removed. We don't expect any OSS clients from using these fields since most of their uses came from rules_apple, and have been migrated for some time now.

If you are using the following ObjcProvider fields directly, please reply on this bug for instructions on how to migrate to an acceptable approach:

* `ASSET_CATALOG`
* `BUNDLE_FILE`
* `ROOT_MERGE_ZIP`
* `STORYBOARD`
* `STRINGS`
* `XCASSETS_DIR`
* `XCDATAMODEL`
* `XIB`

Expected timeline:

released with Bazel August 2018, off by default
enabled by default with Bazel 0.25 (April 2019)

[Updated by kaipi]

**Comment by philwo** [comment]
@c-parsons Apparently this flag was flipped recently, but rolled back again. Do you want to turn this into an official incompatible flag bug and use the migration process for it, so that we can get it into the next release?

**Comment by c-parsons** [comment]
I believe @sergiocampama intends on owning this :)
(Sergio feel free to correct me if I'm wrong)

**Comment by sergiocampama** [comment]
@philwo should I just convert this issue into an incompatible flag issue? can I assign migration as 0.24, and flipping in 0.25, given that the flag is already rolled out?

**Comment by dslomov** [comment]
Please follow https://bazel.build/breaking-changes-guide.html
