### ISSUE TITLE
Gerrit failing on Downstream (Ubuntu 14.04)

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#5712]
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //resources/com/google/gerrit/server:commit-msg_test
-----------------------------------------------------------------------------
=== testing test_at_end
git: 'interpret-trailers' is not a git command. See 'git --help'.
FAIL: failed hook execution
```

from https://storage.googleapis.com/bazel-buildkite-artifacts/f809d4b7-3c69-4878-926d-953da0c11236/resources/com/google/gerrit/server/commit-msg_test/attempt_1.log

https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/364#f809d4b7-3c69-4878-926d-953da0c11236

@davido

**Comment by davido** [comment]
@hanwen Any insights here? You asked the same question on dev mailing list recently: [1].

[1] https://groups.google.com/d/topic/repo-discuss/WFIsKw7YPpw/discussion

**Comment by hanwen** [comment]
see comment on https://gerrit-review.googlesource.com/c/gerrit/+/189250

You need to install git 2.2 or newer onto the base image that runs the CI.

**Comment by jin** [comment]
+ @philwo It looks like the 14.04 image needs git 2.2 to keep Gerrit passing.

**Comment by philwo** [comment]
I don't think we can do anything here, as we want to test Bazel on a vanilla Ubuntu 14.04 to make sure that we still support it (until it finally is EOL'd some time next year...).

If Gerrit no longer supports Ubuntu 14.04, that's totally fine. I'd recommend to just not test it on Ubuntu 14.04 then and remove it from the config here.

I've prepared a PR for that: https://github.com/bazelbuild/continuous-integration/pull/299

**Comment by philwo** [comment]
Alternatively you could exclude specific test targets, if only a subset of tests requires git 2.2. WDYT?
