### ISSUE TITLE
Unable to upgrade bazel to 0.15

### ISSUE THREAD

**Issue by kevinashaw** [bazelbuild/bazel#5714]
### Description of the problem / feature request:
Problem:
I'm trying to install `bazel` but even though it completes successfully: "Bazel is now installed!"  The actual version of bazel is unchanged.

### Feature requests: what underlying problem are you trying to solve with this feature?

How do I correct this so that I can upgrade Bazel

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Steps:
Running Ubuntu 16.04 on AWS EC2.
I downloaded the latest `bazel`:
`wget https://github.com/bazelbuild/bazel/releases/download/0.15.2/bazel-0.15.2-installer-linux-x86_64.sh`
Changed the mode to executable.
Then executed the file:

```
(tensorflow_p36):/efs/temp$ sudo ./bazel-0.15.2-installer-linux-x86_64.sh --user
Bazel installer
---------------

Bazel is bundled with software licensed under the GPLv2 with Classpath exception.
You can find the sources next to the installer on our release page:
   https://github.com/bazelbuild/bazel/releases

# Release 0.15.2 (2018-07-17)

Baseline: b93ae42e8e693ccbcc387841a17f58259966fa38

Cherry picks:
   + 4b80f2455e7e49a95f3a4c9102a67a57dad52207:
     Add option to enable Docker sandboxing.
   + 6b1635279e8b33dc1ac505ac81825e38f8797a14:
     Allow disabling the simple blob caches via CLI flag overrides.
   + 4ec0a7524913ab2c4641368e3f8c09b347351a08:
     Use BUILD.bazel instead of BUILD for external projects
   + 2ff8c5fd919ad7316d06c6303e8d7b51315d4c61:
     Release 0.15.0 (2018-06-26)
   + 8ff87c164f48dbabe3b20becd00dde90c50d46f5:
     Fix autodetection of linker flags
   + c4622ac9205d2f1b42dac8c598e83113d39e7f11:
     Fix autodetection of -z linker flags
   + d3228b61f633cdc5b3f740b641a0836f1bd79abd:
     remote: limit number of open tcp connections by default. Fixes
     #5491

Important changes:

  - In remote caching we limit the number of open
    TCP connections to 100 by default. The number can be adjusted
    by specifying the --remote_max_connections flag.

## Build informations
   - [Commit](https://github.com/bazelbuild/bazel/commit/8225898)
Uncompressing......WARNING: ignoring LD_PRELOAD in environment.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
.

Bazel is now installed!

Make sure you have "/home/ubuntu/bin" in your path. You can also activate bash
completion by adding the following line to your :
  source /home/ubuntu/.bazel/bin/bazel-complete.bash

See http://bazel.build/docs/getting-started.html to start a new project!
(tensorflow_p36):/efs/temp$ bazel version
WARNING: ignoring LD_PRELOAD in environment.
Build label: 0.8.1- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 14 17:21:48 2017 (1513272108)
Build timestamp: 1513272108
Build timestamp as int: 1513272108

```
### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.
```
(tensorflow_p36) :/efs/temp$ bazel info release
WARNING: ignoring LD_PRELOAD in environment.
ERROR: The 'info' command is only supported from within a workspace.
```
### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```(tensorflow_p36) ubuntu@ip-172-31-19-37:/efs/tensorflow$ git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
https://github.com/tensorflow/tensorflow.git
075866e09c682c390add689e63e0f65a8e85aa9b
25c197e02393bd44f50079945409009dd4d434f8
```

###  Have you found anything relevant by searching the web?

There is no error message to search for.
Other search queries have been fruitless.

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by jin** [comment]
What does `which bazel` return you? There may be another Bazel installation that is selected before your shell reaches `/home/ubuntu/bin` in the $PATH.

**Comment by kevinashaw** [comment]
Here is the result of `which bazel`:
`/home/ubuntu/anaconda3/envs/tensorflow_p36/bin/bazel`

**Comment by jin** [comment]
Yep, that installation of Bazel is probably the old `0.8.1`. You may want to investigate your `$PATH` variable (`echo $PATH`) and make sure that `/home/ubuntu/bin` comes before `/home/ubuntu/anaconda3/envs/tensorflow_p36/bin/`. I don't know how/what anaconda3 does, so bear in mind that this will switch the used `bazel` to the one in `/home/ubuntu/bin`.

**Comment by kevinashaw** [comment]
Yes that fixed it.
`PATH="/home/ubuntu/bin":$PATH`
Thank you for your help.
