### ISSUE TITLE
Write build_request_id, invocation_id to user-supplied path

### ISSUE THREAD

**Issue by michaeledgar** [bazelbuild/bazel#5718]
### Description of the feature request:

When running bazel with a `results` config, bazel will generate a random `build_request_id` and `invocation_id`. These IDs are printed to standard output, but they are not written in a structured manner to any local file.

My request is for these IDs to be printed to a new file that may be supplied by a user on the command line.

### Feature requests: what underlying problem are you trying to solve with this feature?

I have a [Continuous Build system](https://cloud.google.com/cloud-build/docs/) that will capture the first 4KB of the file written to `$BUILDER_OUTPUT/output` and include it inline in its Results API. I would like the bazel results IDs to  be in that file after running bazel so I can easily retrieve them from the Continuous Build system's API.

**Comment by buchgr** [comment]
The invocation id aka command id is already written to the BEP in the `BuildStartedEvent.uuid` field. So you can read it from there. The build request id is not, but it sounds reasonable to add it to the BEP too.

Does that work for you?

**Comment by michaeledgar** [comment]
Yes, that works well for us. We can set --build_event_text_file=$BUILDER_OUTPUT/output.

Will BuildStarted be guaranteed to be in the first 4KB of a text-format BEP stream?

**Comment by michaeledgar** [comment]
That's fine - we'll can make do with an extra step that extracts the `uuid` field and a newly added `build_request_id` field.
