### ISSUE TITLE
Handle JavaExportsProvider in java_common API

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#5719]
ATM JavaExportsProvider is not populated with current target information from java_common API. JavaExportsProvider needs to be included in JavaInfo therefore the label of the originating target where a JavaInfo is created needs to be specified.

There are 2 ways to go about this:
1. Pass the label to all java_common API . This makes the collection of exports label correct. The downside is this change will be incompatible and adds complexity and confusion among the users that don't use the exports labels.
2. Remove JavaExportsProvider completely. This makes the API simpler and the implementation less complicated. The downside is that the projects that are already using it should have an alternative solution in place.

The API is already moving a lot between deprecated and new & better. I would like to avoid another incompatible change and remove the provider. I only know about usages in intellij and rules_scala. If the provider is removed a workaround is an aspect that collects the labels of transitive exports targets.

**Comment by iirina** [comment]
CC: @brendandouglas @djwhang @ittaiz @kevin1e100

**Comment by brendandouglas** [comment]
It seems like the current messiness of the API is a direct reflection of the messiness of exports themselves (I'd guess in hindsight most people would prefer they didn't exist).

Given that blaze does implement exported dependencies though, this seems like information that should be made easily available in the skylark API?
