### ISSUE TITLE
Docs link to Visual C++ Build Tools 2015 is broken

### ISSUE THREAD

**Issue by filipesilva** [bazelbuild/bazel#5720]
### Description of the problem / feature request:

Link to `Visual C++ Build Tools 2015` in https://docs.bazel.build/versions/master/windows.html lead to a 404

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Open https://docs.bazel.build/versions/master/windows.html, click on `Visual C++ Build Tools 2015 or later`.

### What operating system are you running Bazel on?

N/A.

### What's the output of `bazel info release`?

N/A.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A.

###  Have you found anything relevant by searching the web?

Actually found it super hard to find the mentioned Visual C++ Build Tools 2015 at all. Googling it doesn't seem to give a direct download page.

I found a link that works in [this](https://blogs.msdn.microsoft.com/pythonengineering/2016/04/11/unable-to-find-vcvarsall-bat/) python page: http://go.microsoft.com/fwlink/?LinkId=691126 

### Any other information, logs, or outputs that you want to share?

N/A.

**Comment by laszlocsomor** [comment]
Thanks for reporting it!
