### ISSUE TITLE
Typo: "Exhaused" should be "Exhausted"

### ISSUE THREAD

**Issue by mmorearty** [bazelbuild/bazel#5722]
### Description of the problem / feature request:

In `src/main/java/com/google/devtools/build/lib/remote/Retrier.java`, there's a typo. "Exhaused" was supposed to be "Exhausted".

### What's the output of `bazel info release`?

0.16.0

###  Have you found anything relevant by searching the web?

Searched for this misspelled word in the github bazel issues

**Comment by mmorearty** [comment]
cc @buchgr

**Comment by buchgr** [comment]
fixed in bazel 0.23
