### ISSUE TITLE
empty file in {new_,}http_archive results in no caching across Bazel server restarts

### ISSUE THREAD

**Issue by bsilver8192** [bazelbuild/bazel#573]
Any actions with empty files from a new_http_archive etc get rebuilt every time the Bazel server is restarted because the files get re-extracted which changes their timestamps, which is what [ActionMetadataHandler](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/skyframe/ActionMetadataHandler.java) uses to check if empty files have changed. It's not a problem for non-empty files because changes in those are identified using a hash of the file contents.

In my particular case (files in Linaro GCC tarballs which don't seem to do anything useful), removing the files as inputs is an easy workaround. However, that might be a problem in some cases and it's really hard to figure out what the problem is.

Here's a patch which adds a failing test (please do commit it along with a fix):
```patch
diff --git a/src/test/shell/bazel/external_integration_test.sh b/src/test/shell/bazel/external_integration_test.sh
index 6421d81..122369e 100755
--- a/src/test/shell/bazel/external_integration_test.sh
+++ b/src/test/shell/bazel/external_integration_test.sh
@@ -639,4 +639,39 @@ EOF
   assert_contains "def" bazel-genfiles/external/x/catter.out
 }
 
+function test_empty_file() {
+  rm -f empty
+  touch empty
+  tar czf x.tar.gz empty
+  local sha256=$(sha256sum x.tar.gz | cut -f 1 -d ' ')
+  serve_file x.tar.gz
+
+  cat > WORKSPACE <<EOF
+new_http_archive(
+    name = "x",
+    url = "http://localhost:$nc_port/x.tar.gz",
+    sha256 = "$sha256",
+    build_file = "x.BUILD",
+)
+EOF
+  cat > x.BUILD <<EOF
+exports_files(["empty"])
+EOF
+  cat > BUILD <<'EOF'
+genrule(
+  name = "rule",
+  srcs = ["@x//:empty"],
+  outs = ["timestamp"],
+  cmd = "date > $@",
+)
+EOF
+
+  bazel build //:rule || fail "Build failed"
+  bazel shutdown || fail "Shutdown failed"
+  cp bazel-genfiles/timestamp first_timestamp || fail "No output"
+  sleep 1 # Make sure we're on a different second to avoid false passes.
+  bazel build //:rule || fail "Build failed"
+  diff bazel-genfiles/timestamp first_timestamp || fail "Output was built again"
+}
+
```

**Comment by damienmg** [comment]
Assigning to Kristina for triage

**Comment by bsilver8192** [comment]
f1ffe3621002231fe4828fe4ecfd5f64df9d2052 fixed this. https://bazel-review.googlesource.com/2390 adds my test case.
