### ISSUE TITLE
SkylarkTests flaky on Windows with weird errors

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#5732]
FYI @laurentlb @laszlocsomor 

https://buildkite.com/bazel/bazel-bazel/builds/3704#91febb6f-20e8-46e7-9999-c1e4a4cb2d04

https://storage.googleapis.com/bazel-buildkite-artifacts/91febb6f-20e8-46e7-9999-c1e4a4cb2d04/src%5Ctest%5Cjava%5Ccom%5Cgoogle%5Cdevtools%5Cbuild%5Clib%5Cskylark%5CSkylarkTests%5Cattempt_1.log

https://storage.googleapis.com/bazel-buildkite-artifacts/91febb6f-20e8-46e7-9999-c1e4a4cb2d04/src%5Ctest%5Cjava%5Ccom%5Cgoogle%5Cdevtools%5Cbuild%5Clib%5Cskylark%5CSkylarkTests%5Cattempt_2.log

https://storage.googleapis.com/bazel-buildkite-artifacts/91febb6f-20e8-46e7-9999-c1e4a4cb2d04/src%5Ctest%5Cjava%5Ccom%5Cgoogle%5Cdevtools%5Cbuild%5Clib%5Cskylark%5CSkylarkTests%5Cattempt_3.log

**Comment by laszlocsomor** [comment]
Thanks for the heads-up! (Reacting only to acknowledge this bug. I'm afraid
I can't work on it at this time.)

**Comment by philwo** [comment]
The test seems so flaky, it just caused a postsubmit run to fail: https://buildkite.com/bazel/bazel-bazel/builds/3705#06f41bf5-f3bd-4807-9e5e-e99e74e7d086

**Comment by philwo** [comment]
@laurentlb Could you investigate or reassign to someone who can?

**Comment by laurentlb** [comment]
Have you seen flakiness on Linux?
It seems that the errors are Windows-specific.

**Comment by philwo** [comment]
Flakyness seems to have gone done a lot again - no clue why.

Here's another one: https://storage.googleapis.com/bazel-buildkite-artifacts/1f830b60-b7ac-4ff8-b911-8cbdde99b18e/src%5Ctest%5Cjava%5Ccom%5Cgoogle%5Cdevtools%5Cbuild%5Clib%5Cskylark%5CSkylarkTests%5Ctest.log - the errors in the logs seem to not have much to do with the actual test.

I haven't seen the flakyness on other platforms.

**Comment by laurentlb** [comment]
@c-parsons To take a look at the failure in `testSkylarkCallableScope` (https://storage.googleapis.com/bazel-buildkite-artifacts/91febb6f-20e8-46e7-9999-c1e4a4cb2d04/src%5Ctest%5Cjava%5Ccom%5Cgoogle%5Cdevtools%5Cbuild%5Clib%5Cskylark%5CSkylarkTests%5Cattempt_2.log)

**Comment by laszlocsomor** [comment]
Are these tests stable now?
