### ISSUE TITLE
Target generated by repository_rule cannot found sometimes.

### ISSUE THREAD

**Issue by nolanliou** [bazelbuild/bazel#5738]
### Description of the problem / feature request:

 target generated by repository_rule cannot found sometimes. it does not work even after I run `bazel clean`.

 please see the project https://github.com/XiaoMi/mace/blob/master/repository/opencl-kernel/opencl_kernel_configure.bzl

### What operating system are you running Bazel on?

> Ubuntu 16.04

### What's the output of `bazel info release`?
```
INFO: $TEST_TMPDIR defined: output root default is '/home/liuqi/data/.cache/bazel' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
........
release 0.13.1
```

### Any other information, logs, or outputs that you want to share?

> This case is not inevitable.

**Comment by nolanliou** [comment]
I found a way to walk around.
```
rm -rf /home/user/.cache/bazel/_bazel_user
```
It seems there is a bug in bazel cache logic.

**Comment by jin** [comment]
Have you tried `bazel clean --expunge`? `bazel clean` does not affect external dependencies.

**Comment by nolanliou** [comment]
Thanks, I'll have a try.

**Comment by nolanliou** [comment]
@jin It works. But how I avoid this problem? Is the way I use it wrong?
