### ISSUE TITLE
remote caching with GCS not reliable

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/bazel#5742]
### Description of the problem / feature request:

When using a remote cache based on google cloud storage I see various errors/warnings in the build.

### Feature requests: what underlying problem are you trying to solve with this feature?

Use the cache and don't get spammed.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Activate the cache and do lots of builds.

### What operating system are you running Bazel on?

linux

### What's the output of `bazel info release`?

release 0.15.0

### Any other information, logs, or outputs that you want to share?

```
WARNING: Error writing to the remote cache:
502 Bad Gateway
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 502 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That?s an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That?s all we know.</ins>
```

Does the caching layer do retries? 

Btw. this an the other caching related output starts with 'WARNING: Error' :) So either it is an error or a warning, right?

**Comment by keith** [comment]
@buchgr any thoughts on this, I'm still seeing this with bazel 1.0.0

**Comment by buchgr** [comment]
The best solution that comes to mind is retries. Is that what you are asking for?

**Comment by keith** [comment]
I was mostly wondering if something had changed here since it was an older issue. Is adding retries for this being tracked somewhere?

**Comment by buchgr** [comment]
https://github.com/bazelbuild/bazel/issues/7203
