### ISSUE TITLE
Nightly, all Windows builds: PermissionError: [WinError 5] Access is denied: 'c:/build' 

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#5749]
rules_nodejs: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/367#5b4e9de4-589f-4fb2-bcfb-cd13995a469e

rules_sass: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/367#5d8ee0ea-cff5-414b-a84a-b66833c98f2a

rules_typescript: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/367#5d8ad44a-b5e2-4acb-928d-be3ea236f33e

tensorflow: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/367#afa9c059-9913-47b4-aa27-982ad06876a4

Android Testing: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/368#329f3af6-a1a3-4527-a3f8-3b6124138d7a

```
 C:\Users\b\AppData\Local\Temp\buildkite-script-219452124.bat
--
  | Traceback (most recent call last):
  | File "bazelci.py", line 1255, in <module>
  | sys.exit(main())
  | File "bazelci.py", line 1242, in main
  | args.build_only, args.test_only, args.monitor_flaky_tests)
  | File "bazelci.py", line 365, in execute_commands
  | clone_git_repository(git_repository, platform)
  | File "bazelci.py", line 601, in clone_git_repository
  | root = downstream_projects_root(platform)
  | File "bazelci.py", line 313, in downstream_projects_root
  | os.makedirs(path)
  | File "C:\python3\lib\os.py", line 211, in makedirs
  | makedirs(head, exist_ok=exist_ok)
  | File "C:\python3\lib\os.py", line 211, in makedirs
  | makedirs(head, exist_ok=exist_ok)
  | File "C:\python3\lib\os.py", line 221, in makedirs
  | mkdir(name, mode)
  | PermissionError: [WinError 5] Access is denied: 'c:/build'
  | 🚨 Error: The command exited with status 1
```

cc @philwo @laszlocsomor

**Comment by laszlocsomor** [comment]
`ERROR_ACCESS_DENIED` is a versatile, generic error, and MSDN does not document it in detail.
In my experience with `CreateDirectoryW`, which I believe `os.makedirs` ultimately calls, the error may indicate:

- no permission to create directories in the root of a drive
- a check-than-act race on the file system, i.e. another process created the same directory between lines:
https://github.com/bazelbuild/continuous-integration/blob/8f09765be3f8a15c2b64ae6a8621aae3885ed0a3/buildkite/bazelci.py#L312-L313

**Comment by laszlocsomor** [comment]
I suggest one or more of:
- Catching the `PermissionError`, then checking `os.isdir(path)`. If another process concurrently created the directory, there's a chance the directory remained, though there's also a chance that it was removed again after `os.makedirs` threw but before we checked `os.isdir`. Still, checking `os.isdir` in the catch-block increases the likelihood of a figuring out what happened.
- Verifying that the process can write in the root of the drive.
- Using another output directory.

**Comment by philwo** [comment]
I’ve moved C:\build (slow persistent SSD) to D:\build (fast local SSD) recently. We probably just have to update these projects. Sorry, I wasn’t aware that anyone hardcodes  that path...

**Comment by philwo** [comment]
@buchgr FYI, maybe we have to change this simply in bazelci.py?

**Comment by dslomov** [comment]
@buchgr @philwo still failing

**Comment by jin** [comment]
Perfect, thanks @philwo.
