### ISSUE TITLE
sandboxing causes all skylark rules with tools relying on /usr/local/bin/python to fail

### ISSUE THREAD

**Issue by msolo-dropbox** [bazelbuild/bazel#576]
Replacing /usr/bin/python with a custom version is not an option most systems, thus /usr/local/bin/python is a necessity.

What is the escape hatch to make this work again?

Feels like "sandbox" is really just an ad-hoc container. Perhaps it would be better to just configure that as part of the workspace. Specifying if sandbox is generally enabled, and if so, what paths to allow would be much clearer.

Thinking further ahead, it would be even better to just allow the "sandbox enter" command to work with something like a docker container. That would make it much easier to debug and fix issues quickly.

**Comment by damienmg** [comment]
This is due of /usr/local not being mounted in the sandbox. @philwo : do you have any insight on the good fix for that?

**Comment by damienmg** [comment]
Should be fixed by using python as an external repository but that's not necessarly convenient right now

**Comment by msolo-dropbox** [comment]
That seems pretty arduous. I think some way of configuring what goes in the
sandbox is going to be necessary. The easiest thing might be to allow a
reference to a file_group or a tar package.

**Comment by bsilver8192** [comment]
The sandbox is separate for every action Bazel runs. It includes only the declared inputs and some standard system folders (/proc, /usr/bin, /usr/lib, etc). If you have a tar file or a filegroup, you can add it as an input to the action and it will then be included in the sandbox when appropriate. Also, as of f96edf7bc9346c7e7bd2260f032d8c89d074c650, can use `execution_requirements = { 'local': 'local' }` to disable the sandbox for individual actions.

**Comment by damienmg** [comment]
@msolo-dropbox once we get that configuration, we are probably going to do it. It's shouldn't be hard for the users. Configuring the sandbox might not be a great idea (ideally, nothing but dependency should be mounted in it).

**Comment by damienmg** [comment]
Closing as duplicate for #544 (note that the mechanism now exists and we should do it)

**Comment by philwo** [comment]
@damienmg What mechanism exists and what should we do? Do you mean adding paths to the sandbox (Yue has a pending CL implementing this), or adding a filegroup for /usr/local (but that doesn't work if there are filenames that are no valid labels).

**Comment by damienmg** [comment]
See "Should be fixed by using python as an external repository but that's not necessarly convenient right now"

**Comment by philwo** [comment]
OK, and what do you mean with "we should do it"? What is "it"? Access Python via an external repository in all of Bazel? I don't see how that could work, considering that Python is installed in a different place in each Linux distribution and OS X.

Or should our users define their own external_repository for /usr/local, add a filegroup that matches Python and then depend on that from all their py_* targets?

**Comment by damienmg** [comment]
We do auto-detection just like we do for C++.
