### ISSUE TITLE
Genrule unable to communicate with system's ssh agent

### ISSUE THREAD

**Issue by zaycev** [bazelbuild/bazel#5762]
### Description of the problem / feature request:

I have a rule which invokes a Go/glide build for an external repository imported in my bazel WORKSPACE. The genrule fails when glide tries to fetch some of the dependencies using git over ssh.

```
bazel build //path/to/my:target
...
{"error": "error connecting to your ssh-agent: dial unix: missing address"}
```
The build command which the genrule wraps works fine outside of the bazel. As I understand bazel remives `SSH_AUTH_SOCK` (which is added back [here](https://github.com/bazelbuild/rules_go/blob/master/hack_go_repository.bzl#L55)).

 Disabling sanbox didn't seem to help:
```
genrule(
    name = "glide-project-bin",
    ...
    cmd = ["cd extenal/glide_project && make && ..."],
    outs = [ ... ],
    local = True,
    tags = [
        "local",
        "no-cache",
        "no-sandbox",
    ],
)
```

### What operating system are you running Bazel on?

OS X, Ubuntu 14.04

### What's the output of `bazel info release`?

```release 0.15.2-homebrew```

**Comment by benjaminp** [comment]
Did you pass `--action_env=SSH_AUTH_SOCK`?

**Comment by zaycev** [comment]
@benjaminp passing `--action_env=SSH_AUTH_SOCK` helped.
Thanks!
