### ISSUE TITLE
Bazel 0.16.0 does not build on OS X 10.11 with Homebrew

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#5777]
See https://github.com/bazelbuild/bazel/issues/5058#issuecomment-410444117, potential release blocker for https://github.com/bazelbuild/bazel/issues/5058.

**Comment by dslomov** [comment]
Let's attempt this
1. Modify Homebrew recipe to not embed the JDK (as it should)
2. Require Java 1.9 on OS X

**Comment by alexeagle** [comment]
0.16.1 is also not on Homebrew, any update?

**Comment by greggdonovan** [comment]
@alexeagle It appears to be coming back starting with 0.16.1 as a Homebrew Cask shortly. See [the bazel-discuss thread](https://groups.google.com/d/msg/bazel-discuss/zQf6p2_KBfQ/9-g2W3eACwAJ0).

**Comment by mpassell** [comment]
The final message (as of right now) in the bazel-discuss thread would suggest that they're planning to go with a custom tap and then go back to directly supporting `brew install bazel` through that, rather than using cask.

**Comment by alexeagle** [comment]
I believe this is resolved, 0.16.1 is out, and the bazel blog documents the upgrade path

**Comment by bzz** [comment]
For others, landed here though the search - it's https://blog.bazel.build/2018/08/22/bazel-homebrew.html
