### ISSUE TITLE
Change the location of tools/bazel

### ISSUE THREAD

**Issue by dapirian** [bazelbuild/bazel#5788]
### Description of the problem / feature request:

`tools/bazel.rc` is already being deprecated (https://github.com/bazelbuild/bazel/issues/4502) which means the last thing requiring a top level `tools/` directory is the handling of `tools/bazel`. When you run bazel you're really running a script which does....
```
# This is a script which is installed instead of the real Bazel binary.
# It looks for a tools/bazel executable next to the containing WORKSPACE
# file and runs that. If that's not found, it runs the real Bazel binary which
# is installed next to this script as bazel-real.
```
This is super useful, and we rely on this functionality to have a hermetic versioned bazel associated with our commits, but "tools" is a really generic directory name to reserve at the top level. Any bazel-specific dir name would be fine (bazel, bazel-tools, etc). Since you'll want to preserve the old functionality, I'd suggest just also checking a new second location.

### What operating system are you running Bazel on?

ubuntu 14.04

### What's the output of `bazel info release`?

release 0.16.0

**Comment by jschaf** [comment]
If you get a mysterious error:

```
/usr/local/homebrew/Cellar/bazel/0.23.2/libexec/bin/bazel: line 80: $DIR/tools/bazel: is a directory
/usr/local/homebrew/Cellar/bazel/0.23.2/libexec/bin/bazel: line 80: exec: $DIR/tools/bazel: cannot execute: Undefined error: 0
```

It's because bazel is looking for the dev installation of bazel in `tools/bazel` which means you can't use that directory.  The fix is to change the name of the directory until this is fixed.
