### ISSUE TITLE
java_test does not copy cc_import data arguments to runfiles tree

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/bazel#5791]
### Description of the problem / feature request:

I have two Bazel packages. One imports a precompiled C++ library using a `cc_import` rule, while the other defines a `java_library` and a handful of `java_test` rules. The shared library is to be loaded at runtime, so I declare it via `java_test`'s `data` param, but `bazel test //:MyTest` fails to copy the library to the runfiles tree.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```bash
# Copy libc to current directory.
$ cp /path/to/libc.so.6 libc.so

# Generate WORKSPACE and BUILD files. Also create a dummy test.sh to illustrate that
# this seems specific to cc_import.
$ touch WORKSPACE test.sh
$ cat >BUILD.bazel <<EOF
cc_import(
    name = "libc",
    shared_library = ":libc.so",
    visibility = ["//visibility:public"],
)
sh_binary(
    name = "test"
    srcs = [":test.sh"],
    visibility = ["//visibility:public"],
)
EOF
$ mkdir -p src/java
$ cat >src/java/BUILD.bazel <<EOF
java_test(
    name = "foo_test",
    data = ["//:libc"],
)
EOF

# Execute test.
$ bazel build //src/java:foo_test

# Check manifest for files copied from this directory to the runfiles tree. Observe that
# test.sh appears but libc.so doesn't.
$ grep $PWD $(find -L bazel-out -name \*.runfiles_manifest)
```

### What operating system are you running Bazel on?

Linux (CentOS 6.6)

### What's the output of `bazel info release`?

Two versions tested:
- `development version` (compiled from 0.13.1)
- `release 0.14.1- (@non-git)`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

```bash
JAVA_HOME=/build/toolchain/lin64/jdk-1.8.0_172 CC=/path/to/customgcc CXX=/path/to/customg++ LD_LIBRARY_PATH=/path/to/customgccslibgcc ./compile.sh
```

We've applied two patches locally to resolve issues 4137 and 5634.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

1. Origin is an internal mirror of bazelbuild/bazel.
2. 4022bac855a790b3a42fcb44c06f62dbbe078c5a
3. 4002470318f98245cb9efa945661085c6c928002  (contains our patches applied against 26abd1d/tag 0.14.1)

###  Have you found anything relevant by searching the web?

Have searched, but didn't find anything.

**Comment by excitoon** [comment]
I've just encountered the same thing if `runfiles` are being read from a rule and you specify `data` attribute in `cc_import`, it is empty (0.23.2).
