### ISSUE TITLE
No deprecation warning for `alias` targets

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#5802]
### Description of the problem / feature request:

Bazel does not warn about deprecated `alias` rules.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create two targets: a1 and a2. They should each depend on another target, b1 and b2 respectively, both having a `deprecation` attribute, but one being an `alias` (to some arbitrary rule) and the other being a normal rule.

Bazel warns about the rule (a1) that depends on the deprecated normal rule (b1), but does not warn about the one (a2) that depends on the deprecated alias rule (b2).

```
  $ cat a/BUILD
filegroup(
    name = "a1",
    srcs = ["//b:b1"],
)

filegroup(
    name = "a2",
    srcs = ["//b:b2"],
)


  $ cat b/BUILD
package(default_visibility = ["//visibility:public"])

filegroup(
    name = "b1",
    srcs = ["BUILD"],
    deprecation = "b1 is deprecated",
)

alias(
    name = "b2",
    actual = "b3",
    deprecation = "b2 is deprecated",
)

filegroup(
    name = "b3",
    srcs = ["BUILD"],
    visibility = ["//visibility:private"],
)


  $ bazel build //a:all
WARNING: /tmp/foo/a/BUILD:1:1: in filegroup rule //a:a1: target '//a:a1' depends on deprecated target '//b:b1': b1 is deprecated
INFO: Analysed 2 targets (0 packages loaded).
INFO: Found 2 targets...
INFO: Elapsed time: 0.154s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

```
  $ bazel info release
release 0.16.0
```

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/644

**Comment by laszlocsomor** [comment]
Moving the `deprecation` attribute from `b2` to `b3` fixes the problem: "bazel build //a:a2" displays the warning.

**Comment by irengrig** [comment]
cc @serynth

**Comment by laszlocsomor** [comment]
Thank you for the detailed explanation!

The simpler approach is symptomatic treatment, but better than none. I support following the harder approach: `alias` is handy in the migration scenario you described. In fact I uncovered this bug in such a scenario.

I don't understand why it matters when the `alias` is in a different package than the target. Can you elaborate?

**Comment by serynth** [comment]
Unrelated to aliases, the conditions for printing deprecations are:
* Depending rule is not an aspect
* Dependency has a deprecation warning
* Dependency is not in the same logical package (special case: java/foo and javatests/foo are considered the same logical package) as depending rule
* Depending rule does not have a deprecation warning

As far as I can tell, aliases themselves still follow these conditions when they depend on their actual targets. So in theory, if you have
//foo:depending
//bar:alias
//baz:actual (with deprecation set)

Then I believe building //bar:alias will print //baz:actual's deprecation warning. (And, in the current world, building //foo:depending will also print //baz:actual's deprecation warning.)

But if it was //baz:alias instead, then they would be in the same package and building //baz:alias would not print a warning.

**Comment by laszlocsomor** [comment]
I see. I was unaware Bazel suppressed deprecation warnings for intra-package dependencies.

**Comment by gregestren** [comment]
@serynth what's the right priority for this?

**Comment by serynth** [comment]
This seems like a low priority fix (P3? the deprecation and visibility behavior might be surprising and somewhat unhelpful, but it doesn't specifically block any build functionality).

**Comment by sventiffe** [comment]
@laszlocsomor this issue hasn't got an update for a while and we will not consider it for the time being. Should we keep it open?

**Comment by laszlocsomor** [comment]
Hey @sventiffe , thanks for asking. We can close it: nobody submitted a fix so I guess it's not so bad.
