### ISSUE TITLE
Allow rules to register persistent worker processes as enabled by default.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/bazel#5805]
The Kotlin builder needs to evolve to support a task model. A task model is needed as a build optimisation and to support multiple Kotlin facets. With a task model non-persistent workers make no sense. The rules should be able to signal to Bazel that the persistent worker is either enabled by default or mandatory. 

In the short term could we make it so that when `"supports-workers"` has a value of `"2"`  the persistent worker is enabled by default ? 

Better worker process registration support is needed in general and support for registering and managing the lifecycle of singleton helper processes that aren't involved in the build -- e.g., test service managers. This requires a lot more thought.

**Comment by hsyed** [comment]
@kevin1e100 could you have a look at this. If I make the builder more granular for Ijar support then persistent workers won't be "optional" anymore for Kotlin. 

I'd like to split the Kotlin compile graph into the following actions (currently they are all done in a single action).

```
|- preprocess (if needed: expand source jars + do annotation process)
  | - ijar 
  | - jar
      | - jdeps
  |- sourcejar
```

If I can't register the worker as mandatory then I'll just generate the ijar along with the compile action (which is probably the optimal approach anyhow).

**Comment by kevin1e100** [comment]
cc @jin 

@hsyed could you clarify what the concern here is, and what's meant by "persistent worker"?  I agree it's useful to generate ijars in a separate action, and it seems you'd be able to use a worker for that (even the same worker binary).  When enabled Bazel will spin the ijar workers up as separate processes alongside the workers you already have.  Conversely, when workers are disabled, Bazel will invoke the various worker commands in short-lived processes.  Is the concern that the latter may be inefficient?

**Comment by hsyed** [comment]
> Is the concern that the latter may be inefficient?

Yes. At the moment the KotlinBuilder does everything in one step -- so it's conceivably to build without persistent workers enabled. However I wouldn't recommend it as the startup times are silly. 

If the actions are made granular it would become unuseable.

> and it seems you'd be able to use a worker for that (even the same worker binary)

Yes The JS rules share the same worker process as the JVM rules. When I split up the JVM rule actions  they will share the same binary.


I think we need a better registration process for workers in general, but for now just signalling "worker process by default" would be good enough. Such a registration could pick conservative defaults such as low shutdown timeouts, and lower default worker count.

**Comment by jin** [comment]
cc @philwo 

I agree, we need a way to expose this in Starlark. Right now, built-in rules can do this by [registering themselves in the native code](https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/bazel/rules/BazelStrategyModule.java;l=121?q=BazelStra).

**Comment by guw** [comment]
@jin @philwo I have a use case to add. I'd like to build a rule which requires a mandatory worker to be running. The worker will be exposing [a reverse proxy running on localhost](https://github.com/salesforce/bazel-maven-proxy/). The output of the buildrule would be a string (uri) with a dynamic port number that defines the uri for `jvm_maven_import_external`.

Is there anything planned for 1.x?

**Comment by larsrc-google** [comment]
Is this still a problem? You can use the --strategy flag to only allow worker execution (though I don't know if the action itself can set that flag).
