### ISSUE TITLE
-c dbg "Dwarf Error: wrong version in compilation unit header (is 0, should be 2, 3, or 4)"

### ISSUE THREAD

**Issue by deeglaze** [bazelbuild/bazel#5806]
### Description of the problem / feature request:

Every binary that bazel builds with -c dbg leads to a gdb error from the subject text .

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

BUILD:
```python
cc_binary(name = "main", srcs = ["main.cc"])
```

main.cc:
```c++
#include <iostream>
int main() { std::cout << "Hello world" << std::endl; return 0; }
```

WORKSPACE:
```python
workspace(name = "main")
```

commands:
```shell
$ bazel build -c dbg :main
$ gdb bazel-bin/main
(gdb) run
```

### What operating system are you running Bazel on?

4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

### What's the output of `bazel info release`?

release 0.16.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Not running from github source.

###  Have you found anything relevant by searching the web?

gdb 8.0 added DWARF version 5 support, but my package manager puts the current version of gdb at 7.9-gg19. My system compiler is gcc 7.3.0-5, which doesn't default to DWARF 5 (you have to add "-gdwarf-5" to get that).
The compiler command bazel issues is the following:

```shell
 /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g '-std=c++0x' -MD -MF bazel-out/k8-dbg/bin/_objs/main/main.pic.d '-frandom-seed=bazel-out/k8-dbg/bin/_objs/main/main.pic.o' -fPIC -iquote . -iquote bazel-out/k8-dbg/genfiles -iquote bazel-out/k8-dbg/bin -iquote external/bazel_tools -iquote bazel-out/k8-dbg/genfiles/external/bazel_tools -iquote bazel-out/k8-dbg/bin/external/bazel_tools -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c main.cc -o bazel-out/k8-dbg/bin/_objs/main/main.pic.o)
```

### Any other information, logs, or outputs that you want to share?

This issue is a problem for me because even though I can see symbols in the repro program, my project which exhibited the bug is segfaulting with a stack trace of ?? ?? ??. That makes debugging a difficult process.

**Comment by irengrig** [comment]
This might be relevant: https://stackoverflow.com/questions/11671009/dwarf-error-wrong-version-in-compilation-unit-header-is-4-should-be-2
