### ISSUE TITLE
Use symlinked runfiles on Windows when supported

### ISSUE THREAD

**Issue by filipesilva** [bazelbuild/bazel#5807]
### Description of the problem / feature request:

On Windows Bazel sets `RUNFILES_MANIFEST_ONLY` to `1` and does not generate symlinks to runfiles. This does not change if the current user can create symlinks.

On recent Windows 10 versions it is possible to enable symlinks for all users:

> Now in Windows 10 Creators Update, a user (with admin rights) can first enable Developer Mode, and then any user on the machine can run the mklink command without elevating a command-line console.

More details can be found in https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/

The feature I am requesting is to generate symlink to runfiles on Windows when supported by the current user.

### Feature requests: what underlying problem are you trying to solve with this feature?

Creating rules with windows support is not trivial (https://github.com/bazelbuild/bazel/issues/3726#issuecomment-329504506). 

Using symlinks on windows when available should make many existing rules work on Windows without having to resolve runfiles via the manifest, given the user has symlink support. 

On systems Windows without symlink support enabled, looking up the runfiles would still be necessary.

Related to https://github.com/bazelbuild/bazel/issues/3726, https://github.com/bazelbuild/bazel/issues/3889, https://github.com/bazelbuild/bazel/issues/1212

/cc @alexeagle

**Comment by meteorcloudy** [comment]
@filipesilva I have made some progress on this recently.
Now with Bazel built from HEAD, symlink tree will be available on Windows when you pass `--experimental_enable_runfiles`. 
Can you try if it helps with https://github.com/bazelbuild/bazel/issues/5926?

**Comment by meteorcloudy** [comment]
@filipesilva Just found a bug when dealing with long path, sending a fix now.
