### ISSUE TITLE
Allow using remote cache and local_disk_cache together

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#5811]
### Description of the problem / feature request:

I want to use remote cache and local_disk_cache at the same time. This is not currently possible.

### Feature requests: what underlying problem are you trying to solve with this feature?

I want remote cache so I can utilize my Organization's shared cache.

I want local_disk_cache since I want to utilize Bazel's local cache of my own changes when I switch between branches.

This issue has been discussed thoroughly on the [mailing list](https://groups.google.com/forum/#!topic/bazel-discuss/CNYNXacr2E4) and was mainly commented on by @jjudd @EricBurnett @buchgr and @roblg

cc @dslomov @helenalt

**Comment by jjudd** [comment]
I would love to see this. 

We worked around this not being supported by running a local nginx proxy on everyone's machines and populating the proxy with the remote cache as well as local Bazel builds. It would be nice to not need to do that.

**Comment by ittaiz** [comment]
@buchgr any update on this?

**Comment by buchgr** [comment]
Update: I agree that we should have this, but it's currently not on anyone's plans to implement it due to resource constraints.

**Comment by buchgr** [comment]
Fixed by https://github.com/bazelbuild/bazel/pull/7512
