### ISSUE TITLE
incompatible_disallow_old_style_args_add: Remove deprecated format for Args.add

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#5822]
This is a tracking issue for offering a migration solution for
`--incompatible_disallow_old_style_args_add`

**Comment by laurentlb** [comment]
Only failure on the CI is rules_typescript.

**Comment by dslomov** [comment]
@c-parsons when do you intend to flip the flag?

**Comment by laurentlb** [comment]
I've sent a PR to rules_typescript, still waiting for maintainers to merge it.
I think it will be too late for 0.23, so let's say 0.24.
