### ISSUE TITLE
incompatible_generate_javacommon_source_jar: Always generate a source jar with java_common.compile

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#5824]
This is a tracking issue for offering a migration solution for
`--incompatible_generate_javacommon_source_jar`

This flag changes java_common.compile to always generate an output source jar. Without this flag, an output source jar is not created when a source jar is the only input for the compilation.

**Comment by dslomov** [comment]
@cushon @c-parsons when do you intend to flip the flag? (what is the length of a [migration window](https://docs.bazel.build/versions/master/backward-compatibility.html#incompatible-changes-and-migration-recipes) - 1 release? more?)

**Comment by laurentlb** [comment]
Apparently, this flag has been flipped in Bazel 0.23.0.

What should have been done:
 * label migration-0.22
 * close the issue when the flag was flipped

Since the release announcement for 0.23.0 has been delayed, I can still add it.
