### ISSUE TITLE
incompatible_new_actions_api: Remove the old (deprecated) actions API

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#5825]
This is a tracking issue for offering a migration solution for
`--incompatible_new_actions_api`

This flag disables old skylark actions API. For example, `ctx.new_file` is removed, for `ctx.actions.declare_file` to be used instead.

**Comment by jin** [comment]
```
$ bazel test //... --all_incompatible_changes  --incompatible_disable_deprecated_attr_params=false
INFO: Invocation ID: a4ce5cc1-884d-4a62-97d6-2dfa03eb0c74
ERROR: /usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/8ab7e77526294574a2cf2da593f9d458/external/com_google_protobuf/BUILD:696:1: in proto_gen rule @com_google_protobuf//:protobuf_python_genproto: 
Traceback (most recent call last):
	File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/8ab7e77526294574a2cf2da593f9d458/external/com_google_protobuf/BUILD", line 696
		proto_gen(name = 'protobuf_python_genproto')
	File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/8ab7e77526294574a2cf2da593f9d458/external/com_google_protobuf/protobuf.bzl", line 108, in _proto_gen_impl
		ctx.action(inputs = inputs, outputs = ctx.out..., <4 more arguments>)
Use ctx.actions.run or ctx.actions.run_shell instead of ctx.action. 
Use --incompatible_new_actions_api=false to temporarily disable this check.
```

3.6.1.2 / 3.6.1.3 also does not have @brandjon commit to fix this: https://github.com/protocolbuffers/protobuf/commit/7b28271a61a3da0a37f6fda399b0c4c86464e5b3#diff-14e64c3c0a0449ceb162062b8291fa19 

@acozzette could you also please create 3.6.1.4 with this cherrypick?

**Comment by dslomov** [comment]
@c-parsons when do you intend to flip the flag?

**Comment by dslomov** [comment]
> @c-parsons when do you intend to flip the flag?

Ping @c-parsons @laurentlb

**Comment by laurentlb** [comment]
It's still blocked by Protobuf.

**Comment by acozzette** [comment]
We're almost ready to release protobuf 3.7.0 which should include the fix.

**Comment by katre** [comment]
This issue was tagged as "breaking-change-0.24" but does not appear ready to be flipped in the [0.24.0 release](https://github.com/bazelbuild/bazel/issues/6968). If this is incorrect please comment on that issue and discuss with me.

**Comment by laurentlb** [comment]
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/67

@c-parsons Can you check how to fix Bazel? (failure is in `third_party/grpc/build_defs.bzl`)

I'll followup with the other projects (Android Testing, Cloud Robotics Core, Remote execution, rules_nodejs).
