### ISSUE TITLE
Kill off the native git_repository rule

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#5828]
This is a tracking issue for offering a migration solution for
`--incompatible_remove_native_git_repository`

This flag would disable the native `git_repository` rule, as there is currently a skylark-defined alternative

**Comment by sergiocampama** [comment]
Is there any documentation on how to load the skylark version?

**Comment by c-parsons** [comment]
I'm not sure about existing docs off the top of my head, but you can do this with:

```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
```

**Comment by laurentlb** [comment]
Documentation: https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#remove-native-git-repository
