### ISSUE TITLE
Build failure: "third_party/ijar/classfile.cc:338: error: call of overloaded 'to_string(devtools_ijar::u1&)' is ambiguous"

### ISSUE THREAD

**Issue by ninjin** [bazelbuild/bazel#583]
I am trying to build bazel to be able to build TensorFlow on a nation-wide cluster.  The first thing I tried was to use the binary releases, but these depend on glibc 2.14 and I only have access to 2.12.  When compiling 0.1.0/0.1.1/de9a39d (HEAD) they all fail with `third_party/ijar/classfile.cc:338: error: call of overloaded 'to_string(devtools_ijar::u1&)' is ambiguous` and I have failed to find anything related to this error by searching the issues.  Apologies for bringing issues with a fairly ancient OS upon you.

System details:

    > gcc --version
    gcc (GCC) 4.9.2
    Copyright (C) 2014 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    > ldd --version
    ldd (GNU libc) 2.12
    Copyright (C) 2010 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    Written by Roland McGrath and Ulrich Drepper.

    > java -version
    java version "1.8.0_05"
    Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)

    > cat /proc/version
    Linux version 2.6.32-573.1.1.el6.x86_64 (mockbuild@x86-032.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) ) #1 SMP Tue Jul 14 02:46:51 EDT 2015

Build log:

    > ./compile.sh 
    INFO: You can skip this first step by providing a path to the bazel binary as second argument:
    INFO:    ./compile.sh build /path/to/bazel
    🍃  Building Bazel from scratch............
    🍃  Building Bazel tools.
    Building tools/jdk/ijar
    ${HOME}/git/bazel/output/bazel --nomaster_bazelrc --bazelrc=/dev/null build --singlejar_top=//src/java_tools/singlejar:bootstrap_deploy.jar --javabuilder_top=//src/java_tools/buildjar:bootstrap_deploy.jar --genclass_top=//src/java_tools/buildjar:bootstrap_genc
    lass_deploy.jar --ijar_top=//third_party/ijar --javacopt=-source 1.8 -target 1.8 --stamp --embed_label head (@97eaf91) //third_party/ijar:ijar
    Extracting Bazel installation...
    Sending SIGTERM to previous Bazel server (pid=111066)... done.
    .....................
    INFO: Waiting for response from Bazel server (pid 115316)...
    WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
    ____Loading package: third_party/ijar
    ____Loading...
    ____Loading package: src/java_tools/singlejar
    ____Loading package: @bazel_tools//tools/jdk
    ____Loading package: tools/jdk
    ____Loading package: src/java_tools/buildjar/java/com/google/devtools/build/buildjar/jarhelper
    ____Loading package: @bazel_tools//third_party
    ____Loading package: @local-jdk//
    ____Loading complete.  Analyzing...
    ____Found 1 target...
    ____Building...
    ____[5 / 10] Compiling third_party/ijar/classfile.cc
    ____From Compiling third_party/ijar/classfile.cc:
    gcc: unrecognized option '-no-canonical-prefixes'
    third_party/ijar/classfile.cc: In member function 'virtual std::string devtools_ijar::Constant_MethodHandle::Display()':
    third_party/ijar/classfile.cc:352: error: call of overloaded 'to_string(devtools_ijar::u1&)' is ambiguous
    /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
    /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
    /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
    third_party/ijar/classfile.cc: In member function 'virtual std::string devtools_ijar::Constant_InvokeDynamic::Display()':
    third_party/ijar/classfile.cc:395: error: call of overloaded 'to_string(devtools_ijar::u2&)' is ambiguous
    /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
    /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
    /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
    third_party/ijar/classfile.cc: In member function 'virtual void devtools_ijar::InnerClassesAttribute::Write(devtools_ijar::u1*&)':
    third_party/ijar/classfile.cc:491: warning: comparison between signed and unsigned integer expressions
    third_party/ijar/classfile.cc:512: warning: comparison between signed and unsigned integer expressions
    third_party/ijar/classfile.cc: In member function 'virtual void devtools_ijar::ArrayTypeElementValue::ExtractClassNames()':
    third_party/ijar/classfile.cc:635: warning: comparison between signed and unsigned integer expressions
    third_party/ijar/classfile.cc: In member function 'void devtools_ijar::TypeAnnotation::TypePath::Write(devtools_ijar::u1*&)':
    third_party/ijar/classfile.cc:861: error: expected initializer before ':' token
    third_party/ijar/classfile.cc:865: error: expected primary-expression before '}' token
    third_party/ijar/classfile.cc:865: error: expected ';' before '}' token
    third_party/ijar/classfile.cc:865: error: expected primary-expression before '}' token
    third_party/ijar/classfile.cc:865: error: expected ')' before '}' token
    third_party/ijar/classfile.cc:865: error: expected primary-expression before '}' token
    third_party/ijar/classfile.cc:865: error: expected ';' before '}' token
    third_party/ijar/classfile.cc: In member function 'virtual void devtools_ijar::AnnotationsAttribute::ExtractClassNames()':
    third_party/ijar/classfile.cc:1044: warning: comparison between signed and unsigned integer expressions
    third_party/ijar/classfile.cc: In member function 'virtual void devtools_ijar::TypeAnnotationsAttribute::ExtractClassNames()':
    third_party/ijar/classfile.cc:1127: warning: comparison between signed and unsigned integer expressions
    third_party/ijar/classfile.cc: In member function 'virtual void devtools_ijar::TypeAnnotationsAttribute::Write(devtools_ijar::u1*&)':
    third_party/ijar/classfile.cc:1136: error: expected initializer before ':' token
    third_party/ijar/classfile.cc:1139: error: could not convert 'devtools_ijar::put_u4be(((devtools_ijar::u1*&)(& payload_start)), (((devtools_ijar::u4)((long int)(p + 0xfffffffffffffffffffffffffffffffcu))) - ((devtools_ijar::u4)((long int)payload_start))))' to 'bool'
    third_party/ijar/classfile.cc:1140: error: expected primary-expression before '}' token
    third_party/ijar/classfile.cc:1140: error: expected ')' before '}' token
    third_party/ijar/classfile.cc:1140: error: expected primary-expression before '}' token
    third_party/ijar/classfile.cc:1140: error: expected ';' before '}' token
    third_party/ijar/classfile.cc: In member function 'virtual void devtools_ijar::MethodParametersAttribute::Write(devtools_ijar::u1*&)':
    third_party/ijar/classfile.cc:1165: error: expected initializer before ':' token
    third_party/ijar/classfile.cc:1169: error: could not convert 'devtools_ijar::put_u4be(((devtools_ijar::u1*&)(& payload_start)), (((devtools_ijar::u4)((long int)(p + 0xfffffffffffffffffffffffffffffffcu))) - ((devtools_ijar::u4)((long int)payload_start))))' to 'bool'
    third_party/ijar/classfile.cc:1170: error: expected primary-expression before '}' token
    third_party/ijar/classfile.cc:1170: error: expected ')' before '}' token
    third_party/ijar/classfile.cc:1170: error: expected primary-expression before '}' token
    third_party/ijar/classfile.cc:1170: error: expected ';' before '}' token
    third_party/ijar/classfile.cc: In member function 'void devtools_ijar::HasAttrs::ExtractClassNames()':
    third_party/ijar/classfile.cc:1219: warning: comparison between signed and unsigned integer expressions
    third_party/ijar/classfile.cc: In member function 'void devtools_ijar::ClassFile::WriteClass(devtools_ijar::u1*&)':
    third_party/ijar/classfile.cc:1778: warning: comparison between signed and unsigned integer expressions
    At global scope:
    cc1plus: warning: unrecognized command line option "-Wno-free-nonheap-object"
    ERROR: ${HOME}/git/bazel/third_party/ijar/BUILD:36:1: C++ compilation of rule '//third_party/ijar:ijar' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -iquote . -iquote ... (remaining 17 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
    Target //third_party/ijar:ijar failed to build
    Use --verbose_failures to see the command lines of failed build steps.
    ____Elapsed time: 21.185s, Critical Path: 0.50s

**Comment by ninjin** [comment]
Best current guess after reading and thinking, it appears that g++ is picking up the wrong libraries and end up using 4.4.7 even though this is a mismatch when it comes to the g++ version:

    > ls /usr/lib/gcc/x86_64-redhat-linux/
    3.4.6  4.1.1  4.4.4  4.4.7  4.8.2

Verified that the same error comes up with 4.8.2, filing an issue with the cluster sysops now and referring to this issue.

**Comment by trungnt13** [comment]
Our cluster got the same problem.

Many clusters system using module with Redhat or Centos < 7 which is **glibc 2.12**

Since, **bazel** requires **glibc 2.14** and the prebuilt version for linux requires **glibc 2.17**. It is hopeless to make tensorflow run on clusters.

**Comment by trungnt13** [comment]
The same issue on our server:

```
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh build /path/to/bazel
�  Building Bazel from scratch............
�  Building Bazel with Bazel.
.Extracting Bazel installation...
Sending SIGTERM to previous Bazel server (pid=57879)... done.
.........
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
INFO: From Compiling third_party/ijar/ijar.cc [for host]:
gcc: unrecognized option '-no-canonical-prefixes'
INFO: From Compiling third_party/ijar/classfile.cc [for host]:
gcc: unrecognized option '-no-canonical-prefixes'
third_party/ijar/classfile.cc: In member function 'virtual std::string devtools_ijar::Constant_MethodHandle::Display()':
third_party/ijar/classfile.cc:338: error: call of overloaded 'to_string(devtools_ijar::u1&)' is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
third_party/ijar/classfile.cc: In member function 'virtual std::string devtools_ijar::Constant_InvokeDynamic::Display()':
third_party/ijar/classfile.cc:381: error: call of overloaded 'to_string(devtools_ijar::u2&)' is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
third_party/ijar/classfile.cc: In member function 'void devtools_ijar::TypeAnnotation::TypePath::Write(devtools_ijar::u1*&)':
third_party/ijar/classfile.cc:784: error: expected initializer before ':' token
third_party/ijar/classfile.cc:788: error: expected primary-expression before '}' token
third_party/ijar/classfile.cc:788: error: expected ';' before '}' token
third_party/ijar/classfile.cc:788: error: expected primary-expression before '}' token
third_party/ijar/classfile.cc:788: error: expected ')' before '}' token
third_party/ijar/classfile.cc:788: error: expected primary-expression before '}' token
third_party/ijar/classfile.cc:788: error: expected ';' before '}' token
third_party/ijar/classfile.cc: In member function 'virtual void devtools_ijar::TypeAnnotationsAttribute::Write(devtools_ijar::u1*&)':
third_party/ijar/classfile.cc:1029: error: expected initializer before ':' token
third_party/ijar/classfile.cc:1032: error: could not convert 'devtools_ijar::put_u4be(((devtools_ijar::u1*&)(& payload_start)), (((devtools_ijar::u4)((long int)(p + 0xfffffffffffffffffffffffffffffffcu))) - ((devtools_ijar::u4)((long int)payload_start))))' to 'bool'
third_party/ijar/classfile.cc:1033: error: expected primary-expression before '}' token
third_party/ijar/classfile.cc:1033: error: expected ')' before '}' token
third_party/ijar/classfile.cc:1033: error: expected primary-expression before '}' token
third_party/ijar/classfile.cc:1033: error: expected ';' before '}' token
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-free-nonheap-object"
ERROR: /homeappl/home/trungnt/appl_taito/libs/bazel/third_party/ijar/BUILD:36:1: C++ compilation of rule '//third_party/ijar:ijar' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections ... (remaining 22 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //src:bazel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 7.403s, Critical Path: 1.72s

Building output/bazel
```

**Comment by ninjin** [comment]
According to @qm1004 `/usr/bin/gcc` is [hard coded](https://github.com/tensorflow/tensorflow/issues/82#issuecomment-155685471).  If this is the case, it would explain why the wrong headers are being picked up.

**Comment by damienmg** [comment]
Ok CROSSTOOL file is supposed to be a platform configuration and can be tweked. I believe there are works for fixing that. @klimek ?

**Comment by r4nt** [comment]
@damienmg (I didn't even remember I had an account under @klimek :) - I don't know of anybody working on a better CROSSTOOL file for open source compiles.

**Comment by damienmg** [comment]
ok, then I pinged someone I don't know :)

On a side note I am working on a configuration mechanism that should allow auto-generation of the CROSSTOOL file that could address the issue. It's some months away though.

**Comment by r4nt** [comment]
@damienmg - oh, it is me, I just didn't remember the account :)

Yep, I believe a "configure" step that creates a CROSSTOOL file based on a script (much like cmake's initial configuration step) would significantly improve portability of bazel for C++

**Comment by ninjin** [comment]
@damienmg and @r4nt, thank you for acknowledging the problem and providing some pointers.  Agreed, auto-generation would be desirable, but I am currently trying to hack my way at least some workable state until the auto-generation arrives.

With a bit of a dirty hack `sed -i -e "s|/usr/bin/gcc|$(type -p gcc)" -e "s|/usr/bin/g++|$(type -p g++)" tools/cpp/CROSSTOOL` I can at least get bazel built, but now it fails when building the tools.

    🍃  Building Bazel tools..
    Building tools/jdk/SingleJar_deploy.jar
    ${HOME}/git/bazel/output/bazel --nomaster_bazelrc --bazelrc=/dev/null build --singlejar_top=//src/java_tools/singlejar:bootstrap_deploy.jar --javabuilder_top=//src/java_tools/buildjar:bootstrap_deploy.jar --genclass_top=//src/java_tools/buildjar:bootstrap_genclass_deploy.jar --ijar_top=//third_party/ijar --javacopt=-source 1.7 -target 1.7 --stamp --embed_label head (@125b349) //src/java_tools/singlejar:SingleJar_deploy.jar
    WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
    ____Loading...
    ____Loading complete.  Analyzing...
    ____Found 1 target...
    ____Building...
    ____[15 / 41] Creating runfiles tree bazel-out/local_linux-fastbuild/bin/src/java_tools/singlejar/SingleJar.runfiles
    ____From Creating runfiles tree bazel-out/local_linux-fastbuild/bin/src/java_tools/singlejar/SingleJar.runfiles:
    ${HOME}/.cache/bazel/_bazel_${USER}/cbecda7e1cd730cf69d590c922adfd6e/bazel/_bin/build-runfiles: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by ${HOME}/.cache/bazel/_bazel_${USER}/cbecda7e1cd730cf69d590c922adfd6e/bazel/_bin/build-runfiles)
    ERROR: ${HOME}/git/bazel/src/java_tools/singlejar/BUILD:19:1: Creating runfiles tree bazel-out/local_linux-fastbuild/bin/src/java_tools/singlejar/SingleJar.runfiles failed: build-runfiles failed: error executing command ${HOME}/.cache/bazel/_bazel_${USER}/cbecda7e1cd730cf69d590c922adfd6e/bazel/_bin/build-runfiles bazel-out/local_linux-fastbuild/bin/src/java_tools/singlejar/SingleJar.runfiles_manifest ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
    ____Building complete.
    Target //src/java_tools/singlejar:SingleJar_deploy.jar failed to build
    Use --verbose_failures to see the command lines of failed build steps.
    ____Elapsed time: 6.297s, Critical Path: 4.15s

This once again looks like a case of picking up the wrong path.

    > strings /apps/gcc/4.9.2/lib64/libstdc++.so.6 | grep GLIBCXX
    GLIBCXX_3.4
    GLIBCXX_3.4.1
    GLIBCXX_3.4.2
    GLIBCXX_3.4.3
    GLIBCXX_3.4.4
    GLIBCXX_3.4.5
    GLIBCXX_3.4.6
    GLIBCXX_3.4.7
    GLIBCXX_3.4.8
    GLIBCXX_3.4.9
    GLIBCXX_3.4.10
    GLIBCXX_3.4.11
    GLIBCXX_3.4.12
    GLIBCXX_3.4.13
    GLIBCXX_3.4.14
    GLIBCXX_3.4.15
    GLIBCXX_3.4.16
    GLIBCXX_3.4.17
    GLIBCXX_3.4.18
    GLIBCXX_3.4.19
    GLIBCXX_3.4.20
    GLIBCXX_FORCE_NEW
    GLIBCXX_DEBUG_MESSAGE_LENGTH

I have tried inspecting `CROSSTOOL` to see where I would need to apply another dirty hack to get it to work but have failed to locate anything.  Any and all pointers on where to take a stab would be more than welcome.

**Comment by damienmg** [comment]
Ok did you tried to set CC and CXX environment variable too?

**Comment by ninjin** [comment]
@damienmg: Yes, I did set them to `CC=$(type -p gcc)` and `CXX=$(type -p g++)` explicitly.  Same failure.  I have tried `grep` on the bazel code base, but I can't seem to find anywhere suspicious where there would be hard-coded paths that I have not corrected.  Is the build process for the bazel tools significantly different from what is done for bazel itself?

**Comment by damienmg** [comment]
Not than I know of... sorry I have missed the reply to that bug.

**Comment by damienmg** [comment]
Maybe trying to delete the cache and retry from scratch? `rm -rf ~/.cache/bazel`

**Comment by ninjin** [comment]
Clearing the cache resulted in the same error.  I will try to take another stab at grepping through the code base.

**Comment by bsilver8192** [comment]
Shot in the dark: maybe the sandbox isn't including the correct `libstdc++.so.6` and runtime, so the binaries Bazel has built are picking up the wrong one instead? Your error message references `/usr/lib64/libstdc++.so.6` (which the sandbox does include), but you're finding the correct version in `/apps/gcc/4.9.2/lib64/libstdc++.so.6` (which is not going to be in the sandbox by default). `--sandbox_debug` is helpful for confirming the problem and `--spawn_strategy=standalone` is helpful to disable sandboxing and see if it fixes the problem.

**Comment by damienmg** [comment]
Hi there, we have an experimental feature to do C++ autodetection:
https://groups.google.com/d/msg/bazel-discuss/MSunz2ZUOq0/U5tE7uQLJQAJ

Can you try and tell me if it worked for you?
