### ISSUE TITLE
Building tensorflow (with bazel) defaults to arm

### ISSUE THREAD

**Issue by booherbg** [bazelbuild/bazel#584]
I seem to be the only one having this problem so I'm not sure if it's a bazel or tensorflow issue.

I've pulled the latest tensorflow, and installed java 8. After a default ./configure in the project (selecting 'n' to GPU support), bazel build appears to default to arm:

``` bash
54$ bazel build
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: No toolchain found for cpu 'armeabi-v7a'.
INFO: Elapsed time: 0.219s

```

``` bash
55$ bazel --help
                                                           [bazel release 0.1.0]
Usage: bazel <command> <options> ...

$ uname -a
Linux lemur 3.3.7-030307-generic #201205211535 SMP Mon May 21 19:36:02 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

$ldd --version
ldd (Ubuntu EGLIBC 2.15-0ubuntu10.3) 2.15
```

**Comment by damienmg** [comment]
I believe it is because it tries to build android target. Invoking @lberki for his expertise :)

**Comment by lberki** [comment]
My hunch is that you either got a bad CROSSTOOL file or a stale ~/.blazerc . My hunch is the latter, unless you were editing CROSSTOOL recklessly. The .blazerc system for finding tools is unfortunately pretty hairy (but we are working on fixing it!)

Check the output of `bazel info package_path` . It should point to where you compiled Bazel from in the form of `%workspace%:BAZEL_ROOT/base_workspace`. If it doesn't try either writing a new `.bazelrc` that's like this:

```
build --package_path %workspace%:<WHEREVER YOU CHECKED OUT BAZEL>/base_workspace
fetch --package_path %workspace%:<WHEREVER YOU CHECKED OUT BAZEL>/base_workspace
query --package_path %workspace%:<WHEREVER YOU CHECKED OUT BAZEL>/base_workspace
```

, or more simply, `rm ~/.bazelrc && ./compile.sh`. This shell script should regenerate it.

**Comment by vmayoral** [comment]
@booherbg you seem to have passed issue #606. Could you please advice on how to move forward?

**Comment by damienmg** [comment]
This bug is unclear, does not seems to be still an issue, closing. Feel free to ping if you still have the issue with recent Bazel
