### ISSUE TITLE
FR: Provide bazel protos in google/genproto

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/bazel#5840]
### Description of the feature request:

Provide bazel protos in google/genproto repos.

### Feature requests: what underlying problem are you trying to solve with this feature?

We run a go program to process the bazel query results, which results in some build files like the following:

```
http_archive(
    name = "io_bazel",
    urls = ["https://github.com/bazelbuild/bazel/archive/0.14.1.tar.gz"],
    # v0.14.1, the last tested version as of 2018-08-08
    strip_prefix = "bazel-0.14.1",
)
go_proto_library(
    name = "build_proto_go_proto",
    importpath = "google/devtools/build/lib/query2/proto/build_proto",
    proto = "@io_bazel//src/main/protobuf:build_proto",
    visibility = ["//visibility:public"],
)
go_library(
    name = "go_build_proto",
    embed = [":build_proto_go_proto"],
    importpath = "google/devtools/build/lib/query2/proto/build_proto",
    visibility = ["//visibility:public"],
)
```

This causes bazel to download a 70MB tarball for two files. I think there should be an easier way to use those proto files.

**Comment by dslomov** [comment]
Do you mean https://github.com/google/go-genproto? 
I think this request should be directed to maintainers of that repository.
