### ISSUE TITLE
Feature Request: Support installing artifacts to the system

### ISSUE THREAD

**Issue by perfinion** [bazelbuild/bazel#5849]
Bazel should be able to install artifacts once they are built to the system.

Bazel can build things and they end up in bazel-bin/foo, but to actually use things they should be installed to /usr/bin/foo or /usr/lib64/libfoo.so.1 or wherever. Bazel currently has no way of doing this so things need to be installed manually. 

I have had to resort to hacks that copy everything into runfiles in the right layout so I can then copy things where they need to be. For example, I use this: https://github.com/tensorflow/tensorflow/blob/v1.10.0/third_party/eigen3/BUILD#L60-L84
And then in the TensorFlow package on Gentoo I copy things to /usr/include/ manually:
https://github.com/gentoo/gentoo/blob/20b3f8c041a450814e3e8c770302cbafc6bbc30d/sci-libs/tensorflow/tensorflow-1.10.0.ebuild#L411-L414
The same goes for the libtensorflow.so a few lines below.

For the pip package, TensorFlow also uses a build_pip_package.sh to actually do the installing once bazel has built everything.

Having a command like `bazel install DESTDIR=/tmp/stage/ //tensorflow:all` would be useful.

It should understand the standard make variables to know where things should be installed too.
https://www.gnu.org/prep/standards/html_node/DESTDIR.html
https://www.gnu.org/prep/standards/html_node/Directory-Variables.html
DESTDIR is very important for package managers to be able to stage the installation separately before merging into the live system.

**Comment by aiuto** [comment]
This is an interesting and hard to implement request. It may be easy to produce good behavior for a given Linux distro, but to make it portable to other distros, BSD, OSX and Windows requires much more effort.

An alternative would be to use the packaging rules https://docs.bazel.build/versions/master/be/pkg.html to create an installed layout .tar/.rpm/.deb. That way you could most precisely specify what artifacts you expect to be installed where. After you build, you use the corresponding package installer to install to the staging area or directly to your machine.

**Comment by perfinion** [comment]
@aiuto doing all of this is quite a lot of work yeah, I think a good first step would be something similar to pkg_tar but without actually doing the tar'ing up. I assume the files are all collected somewhere first and then tar'd up, I could then untar it, but like why tar then untar needlessly when I could just cp from just before it was tar'd up? if there was some rule that just produced the files in bazel-out/ then all those pkg_tar and pkg_deb could be based off that rule. The rules have a lot of options (eg modes=) that are useful which I'm doing manually right now with a genrule.

Also I'm thinking of the case where distros are packaging things that use bazel to build. There is an inversion here, distros make packages by running eg rpmbuild on the source rpm, the source rpm contains the spec file which says how to build it. The interface to build an rpm is always rpmbuild -ba foo.spec regardless of the build system the package uses, the difference is the rules in the spec file. Distros can't run rpmbuild for most packages and bazel for some. Bazel needs to be able to run and output things in phases that these builders expect, its currently a little too end to end which is why I've used a genrule to output stuff part way through for the TensorFlow Gentoo ebuild.

**Comment by perfinion** [comment]
@mhlopko From the TensorFlow discussion earlier. Here is the bug about installing stuff to the system.

**Comment by dslomov** [comment]
Check out https://github.com/google/bazel_rules_install

**Comment by meisterT** [comment]
Closing as per the last comment.
