### ISSUE TITLE
Spurious compiler warnings on latest Bazel version

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#5853]
When building with recent Bazel (d0a3c5eb67320906e4b937df5434f0e673cb6dce) I'm seeing these warnings: [1] while building Bazel itself. I see them also when building Gerrit Code Review with latest Bazel version.

[1] http://paste.openstack.org/show/727789/

//CC @cushon

**Comment by davido** [comment]
Oh, my bad. I was using 0.17.rc1 and failed to re-run the build with actual bazel built from master. Sorry for the noise.

**Comment by cushon** [comment]
No worries, I'm glad it's fixed at head. Note that 0.17 is on hold for now [1], and will be recut to include the fix for this issue after 0.16.1 gets released.

[1] https://groups.google.com/d/msg/bazel-discuss/1116GHzkNm0/Y05J-dKaCQAJ

**Comment by davido** [comment]
> No worries, I'm glad it's fixed at head.

Thanks, I can confirm, that it's fixed at head, and yes I'm aware that 0.17 is going to be recut after 0.16.1 is released.
