### ISSUE TITLE
Android Testing fails on all platforms

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#5855]
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/380#aa774462-45d3-4b30-bcc3-4ee298e74f73

```

Exception in thread "main" java.util.concurrent.ExecutionException: com.android.dx.cf.code.SimException: stack: overflow
--
  | at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
  | at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
  | at com.google.devtools.build.android.dexer.DexBuilder.produceDexArchive(DexBuilder.java:253)
  | at com.google.devtools.build.android.dexer.DexBuilder.buildDexArchive(DexBuilder.java:136)
  | at com.google.devtools.build.android.dexer.DexBuilder.main(DexBuilder.java:123)
  | Caused by: com.android.dx.cf.code.SimException: stack: overflow
  | at com.android.dx.cf.code.ExecutionStack.throwSimException(ExecutionStack.java:341)
  | at com.android.dx.cf.code.ExecutionStack.push(ExecutionStack.java:168)
  | at com.android.dx.cf.code.BaseMachine.storeResults(BaseMachine.java:573)
  | at com.android.dx.cf.code.ValueAwareMachine.run(ValueAwareMachine.java:208)
  | at com.android.dx.cf.code.RopperMachine.run(RopperMachine.java:306)
  | at com.android.dx.cf.code.Simulator$SimVisitor.visitLocal(Simulator.java:649)
  | at com.android.dx.cf.code.BytecodeArray.parseInstruction(BytecodeArray.java:367)
  | at com.android.dx.cf.code.Simulator.simulate(Simulator.java:117)
  | at com.android.dx.cf.code.Ropper.processBlock(Ropper.java:789)
  | at com.android.dx.cf.code.Ropper.doit(Ropper.java:744)
  | at com.android.dx.cf.code.Ropper.convert(Ropper.java:349)
  | at com.android.dx.dex.cf.CfTranslator.processMethods(CfTranslator.java:309)
  | at com.android.dx.dex.cf.CfTranslator.translate0(CfTranslator.java:150)
  | at com.android.dx.dex.cf.CfTranslator.translate(CfTranslator.java:102)
  | at com.google.devtools.build.android.dexer.Dexing.addToDexFile(Dexing.java:198)
  | at com.google.devtools.build.android.dexer.DexConverter.toDexFile(DexConverter.java:31)
  | at com.google.devtools.build.android.dexer.DexConversionEnqueuer$ClassToDex.call(DexConversionEnqueuer.java:173)
  | at com.google.devtools.build.android.dexer.DexConversionEnqueuer$ClassToDex.call(DexConversionEnqueuer.java:156)
  | at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  | at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by cushon** [comment]
cc @kevin1e100 

This might be related to 3a711882dcbb3af8709844bde501ac6fca44ea7d and b/112034634.

**Comment by jin** [comment]
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds?branch=master

The tests were passing before bazelci.py changes (https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/372) on Sunday.

**Comment by jin** [comment]
@kevin1e100 are you familiar with this exception?

**Comment by cushon** [comment]
I strongly suspect this is the result of the ASM change. Are you willing to confirm that the failure was caused by 3a711882dcbb3af8709844bde501ac6fca44ea7d? Alternately, do you have any pointers to reproducing it? I'm not sure how the android testing project gets set up.

**Comment by cushon** [comment]
I was able to reproduce and confirmed that it's 3a71188 / b/112034634.

**Comment by jin** [comment]
I can look into it, but here are the setup instructions anyway.

The project is at https://github.com/googlesamples/android-testing, and the prerequisites for `android_instrumentation_test` are listed on https://docs.bazel.build/versions/master/android-instrumentation-test.html

You should be able to just run `bazel test //ui/espresso/...`. This will test everything using APIs 19-23, so maybe you could try just testing a subset of them first.

**Comment by cushon** [comment]
Here's the background from the other bug:

This is the ASM change: https://gitlab.ow2.org/asm/asm/commit/a5ad5ae694e97fe64b99603096cc8f8187c50f09.

The docs for `COMPUTE_MAXS` now include:

> Note: for classes whose version is `Opcodes#V1_7}` of more, this option requires valid stack map frames. The maximum stack size is then computed from these frames, and from the bytecode instructions in between. If stack map frames are not present or must be recomputed, used `COMPUTE_FRAMES` instead.

Desugar is writing class files with bad stack map frames (which doesn't matter for dx etc.), but that is now preventing ASM from computing the max stack size, which dx does care about, and is resulting in the `com.android.dx.cf.code.SimException`.

**Comment by cushon** [comment]
I opened a PR with the work-around, and it's passing tests: #5860.

@jin can you merge it if it looks OK?

**Comment by cushon** [comment]
It turns out that the work around has unintended side-effects, so I'm going to back that out, which means we need to fix the problem in `com.android.support.test.espresso:espresso_idling_resource:aar`. The bytecode in version 3.0.2 doesn't have this problem, so it might be sufficient to just update our version of that dependency in the `android-testing` repo.

**Comment by cushon** [comment]
I opened a PR: https://github.com/googlesamples/android-testing/pull/197
