### ISSUE TITLE
slow startup after boot: Bazel attempts to connect to dead server

### ISSUE THREAD

**Issue by evanj** [bazelbuild/bazel#5858]
### Description of the problem / feature request:

After a reboot of my Ubuntu VM, the next Bazel command will takes about a minute, since it attempts to connect to the now dead server for a long time. This is due to a race condition between the client and the server startup, causing it to try and connect to the dead server, even though it forked a new server.

### Reproducing it

1. Boot a Ubuntu VM (18.04)
2. Run any Bazel command in any workspace.
3. Reboot.
4. Run the Bazel command again; notice that it is very slow to start up

From looking at the strace output, the problem is the following:

1. Reads the existing settings from the `/server/...` files (`command_port`, `request_cookie`, `response_cookie`, `server.pid.txt`). These are ports and PIDs for a server that no longer exists.
1. opens `/proc/PID/stat` and gets a ENOENT (twice)
1. Decides the server is dead and forks a new child process for the server.
1. Unlinks and replaces `server/cmdline` and `/server/server.pid.txt`
1. Logs "Starting local Bazel Server": https://github.com/bazelbuild/bazel/blob/f05c0a48dc298ad3e90f3acb399cc53c2944a801/src/main/cpp/blaze.cc#L849
1. Reads the `/server/...` files *again*, getting the *old* port.
1. Attempts to connect to the *old* port until gRPC gives up
1. Re-reads the `/server/...` files, getting the *new* port.
1. Connects and quickly issues the command.

### Possible fixes?

* Unlink all the old server files when `::StartServer` starts a server, rather than just `cmdline`: https://github.com/bazelbuild/bazel/blob/f05c0a48dc298ad3e90f3acb399cc53c2944a801/src/main/cpp/blaze.cc#L690
* Time out the grpc connection much much faster, and re-read the server port file on each attempt

**Comment by Globegitter** [comment]
Just running onto this behaviour as well on macOS, starting and connecting to the bazel server after reboot it really slow.
