### ISSUE TITLE
Unable to build bazel master

### ISSUE THREAD

**Issue by kekePower** [bazelbuild/bazel#5861]
### Description of the problem / feature request:
A fresh copy from master and I am unable to build it.

```
$ bazel build //src:bazel
Starting local Bazel server and connecting to it...
...........
ERROR: /home/stig/.cache/bazel/_bazel_stig/6ca3e3526b8a3784d87f5ed89cfd92bb/external/openjdk_linux/file/BUILD.bazel:2:1: @openjdk_linux//file:file: invalid label 'zulu10.2%2B3-jdk10.0.1-linux_x64-allmodules.tar.gz' in element 0 of attribute 'srcs' in 'filegroup' rule: invalid target name 'zulu10.2%2B3-jdk10.0.1-linux_x64-allmodules.tar.gz': target names may not contain '%'
ERROR: /home/stig/projects/bazel/bazel/src/BUILD:195:1: Target '@openjdk_linux//file:file' contains an error and its package is in error and referenced by '//src:embedded_jdk'
ERROR: Analysis of target '//src:bazel' failed; build aborted: Loading failed
INFO: Elapsed time: 10.529s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (53 packages loaded)
```

### What operating system are you running Bazel on?

Mageia 7 (dev.0) x86_64

### What's the output of `bazel info release`?

```
$ bazel info release
development version
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

I built the last version from git over a month ago since I've been without internet connection after moving to a new place.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
$ git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
https://github.com/bazelbuild/bazel
50af3b73ad40f37ee9f6be989d630d7ae32b4767
50af3b73ad40f37ee9f6be989d630d7ae32b4767
```

**Comment by aiuto** [comment]
Do you know the commit from which you built your current bazel version?

**Comment by kekePower** [comment]
Hi.

It's the commit mentioned in the last answer.

**Comment by aiuto** [comment]
The error message seems to point to a problem. That is a strange looking path for your jdk.
ERROR: /home/stig/.cache/bazel/_bazel_stig/6ca3e3526b8a3784d87f5ed89cfd92bb/external/openjdk_linux/file/BUILD.bazel:2:1: @openjdk_linux//file:file: invalid label 'zulu10.2%2B3-jdk10.0.1-linux_x64-allmodules.tar.gz' in element 0 of attribute 'srcs' in 'filegroup' rule: invalid target name 'zulu10.2%2B3-jdk10.0.1-linux_x64-allmodules.tar.gz': target names may not contain '%'

I'm guessing that is the name coming from the zulu project. Can you try renaming it?

**Comment by philwo** [comment]
The filename used by the @openjdk_linux repository in our WORKSPACE was invalid.

This was a temporary breakage of our `master` branch, introduced in https://github.com/bazelbuild/bazel/commit/4c9149d558161e7d3e363fb697f5852bc5742a36 and fixed in https://github.com/bazelbuild/bazel/commit/7eb9ea150fb889a93908d96896db77d5658e5005.

I don't know why we didn't detect this on CI, but we've increased our test coverage a lot since then and I'm confident we would detect this now. It's also been fixed since ~8 months, so I'm closing this as fixed. :)
