### ISSUE TITLE
Bazel build not respect stdout

### ISSUE THREAD

**Issue by Theosakamg** [bazelbuild/bazel#5865]
### Description of the problem / feature request:

Bazel build not respect stderr and stdout,
when you use `bazel build` all console log are in stderr, but should be in stdout ?

If you use a tool for separate that log into separate files. All log are in stderr (but build has no error !)

### Feature requests: what underlying problem are you trying to solve with this feature?

Standard log should to redirect in stdout and Error log (in red) in stderr.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`/usr/bin/bazel build //...  > stdout.txt 2> stderr.txt`

```
$ cat stderr.txt
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Analyzing: target //:ProjectRunner (2 packages loaded)
Analyzing: target //:ProjectRunner (4 packages loaded)
INFO: Analysed target //:ProjectRunner (16 packages loaded).
INFO: Found 1 target...
[0 / 4] [-----] Writing file ProjectRunner.jar-2.params
[6 / 9] no action
[6 / 9] Compiling Java headers external/bazel_java_lib/libProjectLib-hjar.jar (1 files); 0s linux-sandbox ... (2 actions running)
[7 / 9] Building external/bazel_java_lib/libProjectLib.jar (1 source file); 2s worker ... (2 actions running)
Target //:ProjectRunner up-to-date:
  bazel-bin/ProjectRunner.jar
  bazel-bin/ProjectRunner
INFO: Elapsed time: 9.959s, Critical Path: 4.12s
INFO: 3 processes: 1 linux-sandbox, 2 worker.
INFO: Build completed successfully, 9 total actions
INFO: Build completed successfully, 9 total actions
```

```
$ cat stdout.txt
<EMPTY>
```

### What operating system are you running Bazel on?

Debian GNU/linux Testing (Buster) with bazel from repository :
`deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8`

### What's the output of `bazel info release`?

```
$ bazel info release
release 0.16.0
```

###  Have you found anything relevant by searching the web?

- email threads on https://groups.google.com/forum/#!topic/bazel-discuss/JVCotYRXeyk
- info on https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)

**Comment by Theosakamg** [comment]
_Comparison of other build system..._
 
### Gradle case 

#### Successful build :
`$ gradle jar > stdout.txt 2> stderr.txt`
```
$ cat stderr.txt
<EMPTY>
```
```
$ cat stdout.txt 
:compileJava NO-SOURCE
:processResources NO-SOURCE
:classes UP-TO-DATE
:jar UP-TO-DATE

BUILD SUCCESSFUL

Total time: 1.117 secs
```

#### Failed build
`$ gradle jar > stdout.txt 2> stderr.txt`
```
$ cat stderr.txt 
/test_gradle/src/main/java/Test.java:2: error: class, interface, or enum expected
bad code
^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```
```
$ cat stdout.txt 
:compileJava FAILED

BUILD FAILED

Total time: 1.532 secs
```

---------
### CMake case 

#### Successful build :
`$ cmake ./ >stdout.txt 2>stderr.txt`
```
$ cat stderr.txt 
<EMPTY>
```
```
$ cat stdout.txt 
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /test_cmake
```


#### Failed build
`$ cmake ./ >stdout.txt 2>stderr.txt`
```
$ cat stderr.txt 
CMake Error at CMakeLists.txt:14 (add_executable):
  Cannot find source file:

    main.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:14 (add_executable):
  No SOURCES given to target: hello
```

```
$ cat stdout.txt 
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Build files have been written to: /test_cmake
```

**Comment by Theosakamg** [comment]
Parsing building workflow is always possible if output is on stdout. Many application use stderr for detect a error. Logged a good build to stderr is very strange...

**Comment by Theosakamg** [comment]
In my case the feature is connected to [colcon](https://github.com/colcon/colcon-core) (Build system of [ROS2](https://github.com/ros2/ros2) ) extension for colcon-core to support Bazel projects ( [colcon-bazel](https://github.com/colcon/colcon-bazel) & [colcon-ros-bazel](https://github.com/colcon/colcon-ros-bazel) ).

**Comment by meisterT** [comment]
I assume partly the reason is that the output of `{,a,c}query` commands can be redirected to a file.

**Comment by alanfalloon** [comment]
Also, if you use `bazel run` to run a command that produces stdout, you don't want the stdout of actions to get mingled in as well.
