### ISSUE TITLE
Test size warning with --test_filter

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/bazel#5879]
It is common, or even expected, for tests to fall outside timeout ranges when running selective tests.

The most common way for this to happen is for users to run a small portion of a large (i.e. lengthy)
test suite.

```
WARNING: //example:test: Test execution time (5.8s excluding execution overhead) outside of range for ETERNAL tests. Consider setting timeout="short" or size="small".
```

This warning is unhelpful. Were a user to follow its advice when using `--test_filter`, they would very likely cause the unfiltered test suite to fail.

It should be disabled when `--test_filter` is present. Or, it there should be a flag to disable this warning altogether.

**Comment by janakdr** [comment]
There actually is a flag related to this this: `--test_verbose_timeout_warnings`. Would that be sufficient for you? I agree it might be nice for --test_filter to disable this warning.

**Comment by pauldraper** [comment]
Yes
