### ISSUE TITLE
duplicate name in maven_jar does not report error

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#588]
I had something like this:

```
hadoop_version = "2.5.0"
 maven_jar( name = "hadoop-client", artifact = "org.apache.hadoop:hadoop-mapreduce-client-core:%s" % hado    op_version)
 maven_jar( name = "hadoop-client", artifact = "org.apache.hadoop:hadoop-common:%s" % hadoop_version)
```

from a copy/paste error. It was a while before I noticed that the second name seemed to be shadowing the first.

I think this should be a warning at least, but I'd prefer it be an error.

**Comment by kchodorow** [comment]
We actually allow this intentionally, since their are some external repositories used internally (e.g., @bazel-tools and @local-jdk) that we want users to be able to override in their own WORKSPACE file.  However, perhaps we could make it an error for it to show up more than once in a given file.

**Comment by jin** [comment]
Closing as `maven_jar` has been removed.
