### ISSUE TITLE
Use gcov for collecting code coverage for gcc 

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#5880]
Currently C++ coverage is 2x slower than just running the corresponding tests. The goal is to have similar times for running bazel test and bazel coverage on the same targets. When `gcc` is used `gcov` is the fastest tool for computing code coverage results.

**Comment by iirina** [comment]
Note: this should also work with clang but it needs some experimentation.

**Comment by RPGillespie6** [comment]
@iirina Note that vanilla gcov is not the fastest tool for computing coverage for gcc anymore.

You can get dramatic (2-4x) performance gains if you chunk your gcda/gcno evenly across multiple gcov instances (one per core) and then assemble the coverage report completely in memory. This is possible with GCC 9.0+.

This is what fastcov does (spawns 1 gcov per core, chunking the coverage files evenly across the gcov instances, and then assembles the final report in-memory)

https://github.com/RPGillespie6/fastcov 

Just FYI if coverage calculation time is still a problem. (Disclaimer: I wrote this tool)
