### ISSUE TITLE
changing WORKSPACE maven_jar name mappings does not invalidate state

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#589]
After an error like #588 I had to do a bazel clean to fix the state.

Seems like a change to WORKSPACE should be detected, and if any of the names map to new jars the old external jars should be removed.

**Comment by johnynek** [comment]
I'm a bit worried that this bug could be more serious with this:

The fix for #337 
https://github.com/bazelbuild/bazel/commit/8ca065c2ae941309b53f95313a68e585ecc70560

I didn't see any tests that made sure that when a macro changes that we invalidate the workspace correctly.

/cc @damienmg

**Comment by damienmg** [comment]
Lukacs recently fix that I believe (this bug I mean), can you confirm?

The skylark dependency is added correctly (we share the code for the build file) but you are right we should add a test,  see #672

**Comment by kchodorow** [comment]
Closing as this should have been fixed by recent changes, please comment if it's still and issue for you.
