### ISSUE TITLE
objc_framework deps / resources

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#5895]
Currently the [`objc_framework`](https://docs.bazel.build/versions/master/be/objective-c.html#objc_framework) rule for providing pre-built `.framework` binaries, doesn't have some useful attributes like `deps` or `resources`. In our project we use many pre-built frameworks including `GoogleMaps`, which are vended with this structure:

```
GoogleMaps.framework
├── GoogleMaps
├── Headers
├── Modules
└── Resources
    └── GoogleMaps.bundle
GoogleMapsBase.framework
├── GoogleMapsBase
├── Headers
└── Modules
GoogleMapsCore.framework
├── GoogleMapsCore
└── Modules
```

In this case the `GoogleMaps` framework depends on both `GoogleMapsBase` and `GoogleMapsCore` at link time. `GoogleMaps` also vendors a pre-built `.bundle` which is compatible with [`objc_bundle`](https://docs.bazel.build/versions/master/be/objective-c.html#objc_bundle).

To use these right now I have to add all 4 of these targets as dependencies of any target that depends on them. It would be ideal if I could only add `GoogleMaps` as a dependency, so consumers don't have to know about its private dependencies and so I don't have to duplicate these 4 dependencies across all consumers.

It looks like the [`objc_import`](https://docs.bazel.build/versions/master/be/objective-c.html#objc_import) rule can handle this, with the only difference being it expects `.a` files instead of static binaries directly in frameworks.

Is there a reason `objc_framework` doesn't support these other attributes? Are we better off manually moving the binaries to be compatible with `objc_import`?

**Comment by sergiocampama** [comment]
`objc_import` and `objc_framework` are legacy rules and we're paving the way to create new ones in rules_apple. With the new rules, we'll add support for propagation of resources using the `data` attribute, and I believe this should fit this use case in most regards.

The only workaround I can offer for now is to encapsulate all targets under a single `objc_library` target and then depend on that one.

**Comment by keith** [comment]
That sounds great, is there any eta on those changes? IIRC there are issues on here talking about this migration to rules_apple from > 1 year ago.

**Comment by keith** [comment]
Ok thanks. In our case that workaround won't work since we also depend on GooglePlaces which depends on GoogleMapsBase, and we don't want targets that only depend on places to get both of those. I think for now we'll try to workaround it with objc_import.

**Comment by keith** [comment]
Using the new apple_*_framework_import rules solves this!
