### ISSUE TITLE
Bazel should put external repos after stdlib on PYTHONPATH

### ISSUE THREAD

**Issue by rickeylev** [bazelbuild/bazel#5899]
### Description of the problem / feature request:

Bazel prepends external dependencies to `PYTHONPATH` before the stdlib.
This makes external dep modules hide stdlib modules, which is generally a bad thing.

As an example, consider trying to use the `enum` module with code that is Python 2 and Python 3 compatible. The enum34 package provides the `enum` module in py2. However, its only a subset of later Python 3 enum features; i.e., its not a drop-in replacement for `enum` in Python 3.4+

So you create a `new_http_archive rule` and get the "enum" directory onto `sys.path`, which now looks something like:
`['/some-bazel-path/enum34_archive', 'python3.6/stdlib.zip", "python3.6/site-packages']`

Now if you `import enum`, it'll take the enum module from the enum34_archive entry, which breaks all sorts of things.

Instead, it should really be putting the repos after the stdlib, probably where site-packages would normally go.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The simplest way is to run a Python 3 binary that depends on the enum34 package.

```
# WORKSPACE
new_http_archive(
    name = "enum34_archive",
    urls = [
"https://pypi.python.org/packages/bf/3e/31d502c25302814a7c2f1d3959d2a3b3f78e509002ba91aea64993936876/enum34-1.1.6.tar.gz"
        ],
    sha256 = "8ad8c4783bf61ded74527bffb48ed9b54166685e4230386a9ed9b1279e2df5b1",
    strip_prefix="enum34-1.1.6",
    build_file = "enum34.BUILD"
)

# enum34.BUILD:
py_library(
    name = "enum",
    srcs = ["enum/__init__.py"],
    srcs_version = "PY2AND3",
    visibility = ["//visibility:public"],
)

py_binary(
  name = "foo"
  srcs = ["foo.py"]
  deps = ["@enum_archive//:enum"]
)
```

Then import various stdlib modules in foo.py.

Then run bazel with python3 (I was using 3.6)

bazel build --python_path=/usr/bin/python3.6 :foo
bazel-bin/foo

And it should fail out in some stdlib modules that rely on enum

### What operating system are you running Bazel on?

> Linux

### What's the output of `bazel info release`?

> release 0.16.1

###  Have you found anything relevant by searching the web?

> https://github.com/bazelbuild/bazel/issues/2867, while not about this bug, includes some PYTHONPATH output that shows that bazel is putting paths before the stdlib.

**Comment by dslomov** [comment]
@brandjon

**Comment by brandjon** [comment]
See #7959 for related `sys.path` issues.
