### ISSUE TITLE
Document CROSSTOOL

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#59]
The entire crosstool format is probably too hairy, but we should definitely have examples how to configure embedded toolchains.

**Comment by ulfjack** [comment]
Assigning to myself as I designed the original crosstool format. But any help is appreciated.

**Comment by hanwen** [comment]
there are some examples on 

  https://github.com/google/bazel-examples

**Comment by hanwen** [comment]
the best documentation currently is the included CROSSTOOL

 https://github.com/bazelbuild/bazel/blob/master/tools/cpp/CROSSTOOL

together with the proto definition,

https://github.com/bazelbuild/bazel/blob/master/src/main/protobuf/crosstool_config.proto

**Comment by davidzchen** [comment]
Perhaps let's add a brief definition of what the CROSSTOOL file is and what it is used for in the documentation on bazel.io? There are [mentions of CROSSTOOL on the site](http://bazel.io/search.html?cx=012346921571893344015%3Axv_nfgpzbu4&cof=FORID%3A10&ie=UTF-8&q=CROSSTOOL) but I don't think we ever explain what it is anywhere.

**Comment by damienmg** [comment]
internal ref: b/19928718

**Comment by kchodorow** [comment]
Note that there are now two wiki pages:

[What the CROSSTOOL](https://github.com/bazelbuild/bazel/wiki/About-the-CROSSTOOL) is and [How to use a custom toolchain](https://github.com/bazelbuild/bazel/wiki/Building-with-a-custom-toolchain).

**Comment by hhclam** [comment]
Thanks! This is very helpful.

**Comment by damienmg** [comment]
FWIW I discovered we have an extensive documentation internally, we should maybe make it publicly available.

**Comment by mhlopko** [comment]
So I checked the internal documentation and it's roughly on par with the public facing one. We will most definitely update the documentation after making CROSSTOOL more expressive and simpler in 2017, but that kind of goes without saying. So let me close this issue for now.
