### ISSUE TITLE
Failed in linux-sandbox-pid1.cc when TMPDIR is set

### ISSUE THREAD

**Issue by peter1591** [bazelbuild/bazel#5900]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Failed in linux-sandbox-pid1.cc when TMPDIR is set

third_party/bazel/src/main/tools/linux-sandbox-pid1.cc:198: "mount(/tmp/petershih, /tmp/petershih, nullptr, MS_BIND \| MS_REC, nullptr)": No such file or directory Send feedback
--

### Feature requests: what underlying problem are you trying to solve with this feature?

Balze failed to build.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Not sure. On my environment, just set $TMPDIR to /tmp/petershih, and it happens.

### What operating system are you running Bazel on?

4.16.0-3rodete1-amd64 #1 SMP Debian 4.16.16-1rodete1 (2018-06-21) x86_64 GNU/Linux

### What's the output of `bazel info release`?

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by aiuto** [comment]
I hate to ask the obvious, but does the directory /tmp/petershih exist and is writable by you?

**Comment by peter1591** [comment]
Yes, it's writable. This issue is gone after I unset the env variable $TMPDIR

**Comment by philwo** [comment]
Thanks for the issue report. I'll improve the handling around /tmp and TMPDIR in the next sprint on this code.

**Comment by philwo** [comment]
Really sorry - I didn't have time to look into this much yet. :(

It's not easy to fix due to the way we currently mount an empty tmpfs on /tmp (which hides your original TMPDIR) and would require some rewriting of the linux-sandbox that I won't have time to do in the next months.

It might be possible to simply ignore this error in the sandbox, but that might hide other real failures of this kind, so I'd rather not do it.

**Comment by noodle-rubrik** [comment]
We've hit this issue now after setting TMPDIR for a long time, after a recent Ubuntu upgrade (20->22?) and a semi-recent Bazel upgrade (5->7).

Test:
```root@<machine>:/home/ubuntu/sdmain# TMPDIR=/home/ubuntu/sdmain/logs bazel build @@rules_java//toolchains:platformclasspath --sandbox_debug -s```

Error:
```src/main/tools/linux-sandbox-pid1.cc:320: "mount(/home/ubuntu/sdmain/logs, /home/ubuntu/sdmain/logs, nullptr, MS_BIND | MS_REC, nullptr)": Permission denied```

<details>
<summary>
Full test command/output
</summary>
root@<machine>:/home/ubuntu/sdmain# TMPDIR=/home/ubuntu/sdmain/logs bazel build @@rules_java//toolchains:platformclasspath --sandbox_debug -s
INFO: Invocation ID: 5e16ca72-fcf7-48b4-a9c7-c37a5291ca28
INFO: Invocation ID: 2519b549-643c-4a56-913e-c0452c9428be
INFO: Reading 'startup' options from /home/ubuntu/sdmain/.bazelrc: --host_jvm_args=-DBAZEL_TRACK_SOURCE_DIRECTORIES=1, --host_jvm_args=-Dbazel.DigestFunction=sha256
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=214
INFO: Reading rc options for 'build' from /home/ubuntu/sdmain/.bazelrc:
  'build' options: --action_env=PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:/usr/local/go/bin:/usr/local/sbin --action_env=SPARK_REPO=external/spark --compilation_mode=opt --strip=never --incompatible_java_co
mmon_parameters=false --features per_object_debug_info --fission=yes --dynamic_mode=fully --worker_verbose --worker_sandboxing --worker_quit_after_build --output_filter=DONT_MATCH_ANYTHING --announce_rc --jobs=4 --
extra_execution_platforms=//deployment:remote_execution_platform --experimental_repository_downloader_retries=5 --action_env=ANSIBLE_LOCAL_TEMP=/tmp/.ansible/tmp --action_env=PYTHONNOUSERSITE=1
INFO: Reading rc options for 'build' from /home/ubuntu/sdmain/wrapper.bazelrc:
  'build' options: --build_event_json_file=/home/ubuntu/sdmain/bazel_beplogs.log.txt --config=read_only_remote_cache --action_env=TOOLCHAIN_ACTION_ENV_HASH=79b1c3e4cd94e68c35eed8eee1ca5e20e802573d1f0324da8c9a7f6b97
ffed65
INFO: Reading rc options for 'build' from /home/ubuntu/sdmain/.bazelrc:
  'build' options: --incompatible_sandbox_hermetic_tmp=false --incompatible_disallow_unsound_directory_outputs=false --@io_bazel_rules_docker//transitions:enable=false --remote_download_outputs=all --incompatible_default_to_explicit_init_py
INFO: Found applicable config definition build:read_only_remote_cache in file /home/ubuntu/sdmain/.bazelrc: --config=remote_cache --remote_upload_local_results=false --remote_accept_cached=true
INFO: Found applicable config definition build:remote_cache in file /home/ubuntu/sdmain/.bazelrc: --remote_cache=https://bazel-cache.rubrik.com:443/jammy/cache --experimental_strict_action_env --remote_timeout=10 --remote_local_fallback=true
INFO: Analyzed target @@rules_java//toolchains:platformclasspath (0 packages loaded, 0 targets configured).
SUBCOMMAND: # @@rules_java//toolchains:platformclasspath [action 'JavaToolchainCompileBootClasspath external/rules_java/toolchains/platformclasspath.jar', configuration: f7b74c00cf2e88589d370f465fde8331152d141103ccf10507da1bbfad1590d1, execution platform: //deployment:remote_execution_platform, mnemonic: JavaToolchainCompileBootClasspath]
(cd /home/jenkins/.cache/bazel/_bazel_root/268278c517f5e65ae6e2b568ebe64594/execroot/_main && \
  exec env - \
  external/remotejdk11_linux/bin/java -XX:+IgnoreUnrecognizedVMOptions -XX:-UsePerfData '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED' -cp bazel-out/k8-opt/bin/external/rules_java/toolchains/platformclasspath_classes DumpPlatformClassPath bazel-out/k8-opt/bin/external/rules_java/toolchains/platformclasspath.jar external/local_jdk)
# Configuration: f7b74c00cf2e88589d370f465fde8331152d141103ccf10507da1bbfad1590d1
# Execution platform: //deployment:remote_execution_platform
DEBUG: Sandbox debug output for JavaToolchainCompileBootClasspath @@rules_java//toolchains:platformclasspath:
1722292188.252636813: src/main/tools/linux-sandbox.cc:156: calling pipe(2)...
1722292188.252671193: src/main/tools/linux-sandbox.cc:165: Netns is 0
1722292188.252674693: src/main/tools/linux-sandbox.cc:176: calling clone(2)...
1722292188.253368443: src/main/tools/linux-sandbox.cc:185: linux-sandbox-pid1 has PID 20855
1722292188.253404463: src/main/tools/linux-sandbox-pid1.cc:700: Pid1Main started
1722292188.253556883: src/main/tools/linux-sandbox.cc:202: done manipulating pipes
1722292188.253650083: src/main/tools/linux-sandbox-pid1.cc:311: writable: /dev/shm
1722292188.253671513: src/main/tools/linux-sandbox-pid1.cc:311: writable: /home/jenkins/.cache/bazel/_bazel_root/268278c517f5e65ae6e2b568ebe64594/sandbox/linux-sandbox/1186/execroot/_main
1722292188.253689643: src/main/tools/linux-sandbox-pid1.cc:311: writable: /home/ubuntu/sdmain/logs
1722292188.254451843: src/main/tools/linux-sandbox.cc:243: child exited normally with code 1

Run this command to start an interactive shell in an identical sandboxed environment:
(exec env - \
    TMPDIR=/home/ubuntu/sdmain/logs \
  /home/jenkins/.cache/bazel/_bazel_root/install/80f400a450641cd3dd880bb8dec91ff8/linux-sandbox -t 15 -w /dev/shm -w /home/jenkins/.cache/bazel/_bazel_root/268278c517f5e65ae6e2b568ebe64594/sandbox/linux-sandbox/1186/execroot/_main -w /home/ubuntu/sdmain/logs -w /tmp -S /home/jenkins/.cache/bazel/_bazel_root/268278c517f5e65ae6e2b568ebe64594/sandbox/linux-sandbox/1186/stats.out -D /home/jenkins/.cache/bazel/_bazel_root/268278c517f5e65ae6e2b568ebe64594/sandbox/linux-sandbox/1186/debug.out -- /bin/sh -i)
ERROR: /home/jenkins/.cache/bazel/_bazel_root/268278c517f5e65ae6e2b568ebe64594/external/rules_java/toolchains/BUILD:254:14: JavaToolchainCompileBootClasspath external/rules_java/toolchains/platformclasspath.jar failed: (Exit 1): linux-sandbox failed: error executing JavaToolchainCompileBootClasspath command
  (cd /home/jenkins/.cache/bazel/_bazel_root/268278c517f5e65ae6e2b568ebe64594/sandbox/linux-sandbox/1186/execroot/_main && \
  exec env - \
    TMPDIR=/home/ubuntu/sdmain/logs \
  /home/jenkins/.cache/bazel/_bazel_root/install/80f400a450641cd3dd880bb8dec91ff8/linux-sandbox -t 15 -w /dev/shm -w /home/jenkins/.cache/bazel/_bazel_root/268278c517f5e65ae6e2b568ebe64594/sandbox/linux-sandbox/1186/execroot/_main -w /home/ubuntu/sdmain/logs -w /tmp -S /home/jenkins/.cache/bazel/_bazel_root/268278c517f5e65ae6e2b568ebe64594/sandbox/linux-sandbox/1186/stats.out -D /home/jenkins/.cache/bazel/_bazel_root/268278c517f5e65ae6e2b568ebe64594/sandbox/linux-sandbox/1186/debug.out -- external/remotejdk11_linux/bin/java -XX:+IgnoreUnrecognizedVMOptions -XX:-UsePerfData '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED' -cp bazel-out/k8-opt/bin/external/rules_java/toolchains/platformclasspath_classes DumpPlatformClassPath bazel-out/k8-opt/bin/external/rules_java/toolchains/platformclasspath.jar external/local_jdk)
src/main/tools/linux-sandbox-pid1.cc:320: "mount(/home/ubuntu/sdmain/logs, /home/ubuntu/sdmain/logs, nullptr, MS_BIND | MS_REC, nullptr)": Permission denied
Target @@rules_java//toolchains:platformclasspath failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Build completed, shutting down worker pool...
INFO: Elapsed time: 0.176s, Critical Path: 0.08s
INFO: 2 processes: 2 internal.
ERROR: Build did NOT complete successfully
INFO: Build Event Protocol files produced successfully.
FAILED:
</details>

Environment Details:

<details>
<summary>Machine: Ubuntu 22.04.4 LTS</summary>
```
root@<machine>:/home/ubuntu/sdmain# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
</details>

<details>
<summary>Bazel release: release 7.1.0</summary>
```
root@<machine>:/home/ubuntu/sdmain# bazel info release
INFO: Reading 'startup' options from /home/ubuntu/sdmain/.bazelrc: --host_jvm_args=-DBAZEL_TRACK_SOURCE_DIRECTORIES=1, --host_jvm_args=-Dbazel.DigestFunction=sha256
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=214
INFO: Reading rc options for 'info' from /home/ubuntu/sdmain/.bazelrc:
  Inherited 'build' options: --action_env=PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:/usr/local/go/bin:/usr/local/sbin --action_env=SPARK_REPO=external/spark --compilation_mode=opt --strip=never --incompatible_java_common_parameters=false --features per_object_debug_info --fission=yes --dynamic_mode=fully --worker_verbose --worker_sandboxing --worker_quit_after_build --output_filter=DONT_MATCH_ANYTHING --announce_rc --jobs=4 --extra_execution_platforms=//deployment:remote_execution_platform --experimental_repository_downloader_retries=5 --action_env=ANSIBLE_LOCAL_TEMP=/tmp/.ansible/tmp --action_env=PYTHONNOUSERSITE=1 --incompatible_sandbox_hermetic_tmp=false --incompatible_disallow_unsound_directory_outputs=false --@io_bazel_rules_docker//transitions:enable=false --remote_download_outputs=all --incompatible_default_to_explicit_init_py
release 7.1.0
```
</details>
