### ISSUE TITLE
Validate that only one instance of a provider is being returned by a skylark rule

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#5902]
Consider the following rule implementation function:

```
MyProvider = provider()

def _rule_impl(ctx):
    ...
    return [MyProvider(foo = 1), MyProvider(foo=2)]
```

The current behavior is that the latter of the two providers is propagated, and the former is ignored. This is a particularly error-prone behavior and we should guard against it.

**Comment by c-parsons** [comment]
5a6fc8deb863696e121ef8e6fc65361c0e35e5f8 contains a fix for this, attached to the flag `--incompatible_disallow_conflicting_providers`.

This issue will remain open to track the migration solution.

**Comment by laurentlb** [comment]
Can we switch the flag for Bazel 0.20?
If so, we have to add it to the [Bazel 0.19 release announcement](https://docs.google.com/document/d/1wDvulLlj4NAlPZamdlEVFORks3YXJonCjyuQMUQEmB0/edit?ts=5bd07778#heading=h.j0igzrozu3hh).

**Comment by c-parsons** [comment]
Hmm. I don't anticipate any blockers, but it looks like I've failed to add the Backward Compatibility information for this flag (which we usually link to in the announcement). I'll send a change for that.
