### ISSUE TITLE
incompatible_run_shell_command_string: Disallow "command" parameter of actions.run_shell to take a sequence

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#5903]
This tracks removal of a long-deprecated construct of the `command` parameter of `ctx.actions.run_shell` and `ctx.actions.run` accepting a sequence of strings.

**Comment by laurentlb** [comment]
The goal of `ctx.actions.run_shell` is to run a command using a shell. A shell command is a string, not a list.

```python
    ctx.actions.run_shell(
        outputs = [f],
        command = "touch " + f.path,
    )
```

If a user wants to run a command with an argument, e.g. "touch output" they can use `ctx.actions.run`:
```python
    ctx.actions.run(
        outputs = [f],
        executable = "touch",
        arguments = [f.path],
    )
```

So I think we should require `command` to be a string. Fixing existing code should be simple using `ctx.actions.run`.

**Comment by laurentlb** [comment]
Increasing to P1, assuming we still want to do this breaking change.

**Comment by c-parsons** [comment]
Flag: --incompatible_run_shell_command_string

Motivation
The motivation for this change is described in #6241

Migration
Use OutputGroupInfo instead.

# Before
def rule_impl(ctx):
    ...
    dep_bin = ctx.attr.dep.output_group.bin
    ...

# After
def rule_impl(ctx):
    ...
    dep_bin = ctx.attr.dep[OutputGroupInfo].bin
    ...

**Comment by laurentlb** [comment]
What's the status of this flag? Labels are missing.

**Comment by Yannic** [comment]
Friendly ping on the status of this flag.

**Comment by laurentlb** [comment]
Marking it as migration-ready, so that we can get feedback and see if it breaks something.

**Comment by keith** [comment]
@c-parsons @laurentlb do you have a suggestion for this use case?

**Comment by laurentlb** [comment]
Does it work if you call `ctx.actions.run` instead?
(I haven't checked what the output of `ctx.resolve_command` looks like.)

**Comment by keith** [comment]
How does that affect this since both `run` and `run_shell` are removing the sequence of args based on the description here?

**Comment by laurentlb** [comment]
See https://github.com/bazelbuild/bazel/issues/5903#issuecomment-413489196 for an example

**Comment by keith** [comment]
That doesn't really work for this case where we accept arbitrary commands, unless we set the executable to `/bin/bash` and prepending `-c` to the args. Note the comments in the code around this issue references `b/77637734` which may not be an issue externally, in which case forcing `/bin/bash` might be removable. I might go down that path since there doesn't seem to be a better alternative.

**Comment by laurentlb** [comment]
I've filed #12418 to track a proper resolution/recommendation.
