### ISSUE TITLE
Bazel ignores $HOME/.bazelrc if %workspace%/.bazelrc exists

### ISSUE THREAD

**Issue by josh-newman** [bazelbuild/bazel#5904]
### Description of the problem / feature request:

Bazel ignores $HOME/.bazelrc if %workspace%/.bazelrc exists. With the deprecation of tools/bazel.rc, we moved our configuration to %workspace%/.bazelrc, but that causes developers' own settings to be ignored.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I've created a repository with minimal Bazel workspaces that demonstrates the issue: [github.com/josh-newman/bazel-rc-issue](https://github.com/josh-newman/bazel-rc-issue).

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 0.16.1

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
git@github.com:josh-newman/bazel-rc-issue.git
0a4948245b4f32baec467f31fa55084dc72fc58e
0a4948245b4f32baec467f31fa55084dc72fc58e
```

###  Have you found anything relevant by searching the web?

It looks like there are several issues related to locating .bazelrc files, including #4502. However, it looks like this issue might be even older, because [`OptionProcessor::FindUserBlazerc` short-circuits its search if it finds a workspace .bazelrc](https://github.com/bazelbuild/bazel/blob/2da247fc71ae89c4682ced4703e1441c0126ec42/src/main/cpp/option_processor.cc#L156-L160). According to my reading of [the documentation](https://docs.bazel.build/versions/master/user-manual.html#where-are-the-bazelrc-files), the intended behavior is Bazel reads both, rather than reads only the first, so this seems like a bug.

CC @siddharthab

**Comment by ittaiz** [comment]
@cvcal isn’t this one of the basic scenarios you solved?

**Comment by cvcal** [comment]
Yeah, this was fixed with #4502, which you mention (https://github.com/bazelbuild/bazel/commit/ec83598cb6ee4136166bb562a24dc5dfa58921db) There are a few concerns with the migration but the fixes have been waiting on review and should make it in soon, so hopefully this makes it to Bazel 0.17

**Comment by cvcal** [comment]
Thanks, Ittai!

**Comment by josh-newman** [comment]
Glad to hear it'll be fixed soon; thanks!

**Comment by cvcal** [comment]
Unfortunately it will not make the cut for 0.17 :( but it should be in 0.18. Thanks for your patience!
