### ISSUE TITLE
Building on Alpine doesn't embed Java

### ISSUE THREAD

**Issue by errordeveloper** [bazelbuild/bazel#5909]
```
FROM golang:1.10-alpine AS build

RUN apk add --update \
      bash \
      curl \
      dev86 \
      g++ \
      gcc \
      git \
      linux-headers \
      make \
      openjdk8 \
      py-pip \
      python \
      python-dev \
      unzip \
      zip \
      && true

RUN mkdir /out
RUN mkdir -p /out/etc/apk && cp -r /etc/apk/* /out/etc/apk/
RUN apk add --no-cache --initdb --root /out \
    alpine-baselayout \
    busybox \
    ca-certificates \
    coreutils \
    git \
    libc6-compat \
    libgcc \
    libstdc++ \
    python \
    && true

## <snip> build Skaffold, which uses bazel

WORKDIR /out

RUN ln -s /lib /lib64


## <snip> install other runtime dependencies of Skaffold

ENV BAZEL_VERSION 0.16.1
ENV BAZEL_SRC /src/bazel/${BAZEL_VERSION}
ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
RUN mkdir -p "${BAZEL_SRC}"
WORKDIR "${BAZEL_SRC}"
RUN curl --silen --location "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-dist.zip" --output bazel-dist.zip \
    && unzip bazel-dist.zip && rm -f bazel-dist.zip

RUN bash compile.sh && mv output/bazel /out/usr/local/bin/bazel

FROM scratch
CMD skaffold
COPY --from=build  /out /
```

Running `bazel` in resulting container image results in this error:

```
Extracting Bazel installation...
FATAL: Could not find system javabase. Ensure JAVA_HOME is set, or javac is on your PATH.
```

Also, the binary is ~50MB smaller then released binary with embedded Java.

**Comment by aiuto** [comment]
Putting this in ExternalDeps for now, but I am not convinced it is really that team's problem. Feel free to switch to team-Product

**Comment by davido** [comment]
Are you aware of Alpine binary Bazel package I maintain: [1]?

* [1] https://github.com/davido/bazel-alpine-package

**Comment by errordeveloper** [comment]
@davido thanks! yes I am, I've looked at it first, and though it was 0.15.x, and as of 0.16.x I was expecting to be able to use embedded Java (but well, I couldn't – #5891).
I've looked at your package more closely now, and I can see you are including `openjdk8` as a runtime dependency, and I'd rather avoid that! hence this issue 😸

**Comment by mrmeku** [comment]
@errordeveloper Looking at https://github.com/bazelbuild/bazel/blob/00f8d65c36bab4199ca006ded2a0fa055f39f6a9/compile.sh#L66 you can see that the compile script is intentionally building without the jdk as it build `//src:bazel_nojdk`.

If you wanted to compile a version with the jdk you would do as this genrule does (https://github.com/bazelbuild/bazel/blob/f69c3d27b7e47bb56c0359d350c3f20a7ccf9d38/scripts/packages/BUILD#L89) and build `//src:bazel`.

So to reframe your issue, would you want a command line flag to build with or without the jdk?
