### ISSUE TITLE
Fail to build bazel with GCC other than /usr/bin/gcc 

### ISSUE THREAD

**Issue by weijianwen** [bazelbuild/bazel#591]
Hi,

I failed to build bazel from source using GCC which is not installed as ```/usr/bin/gcc```. [Environment Modules](http://modules.sourceforge.net) is adopted to manage multiple versions of software, coexisting on our platform. ```/usr/bin/gcc``` is the perhaps outdated GCC which doesn't supprot C++1x. ```compile.sh``` seems to ignore ```$PATH```, thus being unaware of other gcc available there.

This build issue can be reproduced as follows.

1. Show ```/usr/bin/gcc```.

		$ /usr/bin/gcc --version
		gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)
		Copyright (C) 2010 Free Software Foundation, Inc.
		This is free software; see the source for copying conditions.  There is NO
		warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

2. Load environment modules and check the environment variables.

		$ module purge; module load gcc/4.9 jdk/1.8
		$ echo $PATH
		/lustre/usr/gcc/4.9/bin:/lustre/usr/jdk/1.8/bin:/home/rpmbuild/.local/bin:/home/rpmbuild/bin:/usr/local/bin:/usr/local/sbin:/usr/lib64/qt-3.3/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/bin:/bin:/usr/bin:/home/rpmbuild/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/bin
		$ which gcc
		/lustre/usr/gcc/4.9/bin/gcc
		$ `which gcc` --version
		gcc (GCC) 4.9.3
		Copyright (C) 2015 Free Software Foundation, Inc.
		This is free software; see the source for copying conditions.  There is NO
		warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

3. Build bazel from source, fails.

		$ ./compile.sh
		...
		INFO: From Compiling src/main/tools/build-runfiles.cc:
		gcc: unrecognized option '-no-canonical-prefixes'
		src/main/tools/build-runfiles.cc: In member function 'void RunfilesCreator::EnsureDirReadAndWritePerms(const std::s
		tring&)':
		src/main/tools/build-runfiles.cc:342: warning: comparison between signed and unsigned integer expressions
		At global scope:
		cc1plus: warning: unrecognized command line option "-Wno-free-nonheap-object"
		INFO: From Compiling src/main/cpp/util/strings.cc:
		gcc: unrecognized option '-no-canonical-prefixes'
		src/main/cpp/util/strings.cc: In function 'void blaze_util::JoinStrings(const std::vector<std::basic_string<char, s
		td::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::
		allocator<char> > > >&, char, std::string*)':
		src/main/cpp/util/strings.cc:90: error: expected initializer before ':' token
		src/main/cpp/util/strings.cc:305: error: expected primary-expression at end of input
		src/main/cpp/util/strings.cc:305: error: expected ';' at end of input
		src/main/cpp/util/strings.cc:305: error: expected primary-expression at end of input
		src/main/cpp/util/strings.cc:305: error: expected ')' at end of input
		src/main/cpp/util/strings.cc:305: error: expected statement at end of input
		src/main/cpp/util/strings.cc:89: warning: unused variable 'first'
		src/main/cpp/util/strings.cc:305: error: expected '}' at end of input
		src/main/cpp/util/strings.cc: At global scope:
		src/main/cpp/util/strings.cc:305: error: expected '}' at end of input
		cc1plus: warning: unrecognized command line option "-Wno-free-nonheap-object"
		ERROR: /home/rpmbuild/workspace/hpc-configuration/rpmbuild/BUILD/bazel-0.1.1/src/main/cpp/util/BUILD:31:1: C++ comp
		ilation of rule '//src/main/cpp/util:strings' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_S
		OURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-
		omit-frame-pointer '-std=c++0x' -DBLAZE_OPENSOURCE -iquote . ... (remaining 18 argument(s) skipped): com.google.dev
		tools.build.lib.shell.BadExitStatusException: Process exited with status 1.

**Comment by weijianwen** [comment]
I try to build Release 0.1.1 (2015-10-05).

**Comment by damienmg** [comment]
Ok you need to change the path of GCC in tools/cpp/CROSSTOOL file so bazel know where your GCC installation is. For simplifying that, I am working on a general mechanism that would help targeting user configuration.

**Comment by weijianwen** [comment]
Great. I replace all ```/usr/bin/gcc``` instances in ```tools/cpp/CROSSTOOL``` with:

	$ export GCC=`which gcc`
	$ sed -i -e "s=/usr/bin/gcc=$GCC=g" tools/cpp/CROSSTOOL

After that, I try to build but new issues arise:

	$ ./compile
        ...
	INFO: Found 1 target...
	INFO: From Creating runfiles tree bazel-out/local_linux-fastbuild/bin/src/main/java/bazel-main.runfiles:
	/home/rpmbuild/.cache/bazel/_bazel_rpmbuild/8bfa8a9e725636d1934e3e7b74a02874/bazel-0.1.1/_bin/build-runfiles: /usr/
	lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /home/rpmbuild/.cache/bazel/_bazel_rpmbuild/8
	bfa8a9e725636d1934e3e7b74a02874/bazel-0.1.1/_bin/build-runfiles)
	ERROR: /home/rpmbuild/workspace/hpc-configuration/rpmbuild/BUILD/bazel-0.1.1/src/main/java/BUILD:664:1: Creating ru
	nfiles tree bazel-out/local_linux-fastbuild/bin/src/main/java/bazel-main.runfiles failed: build-runfiles failed: error executing command /home/rpmbuild/.cache/bazel/_bazel_rpmbuild/8bfa8a9e725636d1934e3e7b74a02874/bazel-0.1.1/_bin/build-runfiles bazel-out/local_linux-fastbuild/bin/src/main/java/bazel-main.runfiles_manifest ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
	Target //src:bazel failed to build
	Use --verbose_failures to see the command lines of failed build steps.

It seems the build process still got some troubles to figure out the correct paths. However, the ```bazel``` binary has been generated successfully:

	$ ldd output/bazel
	linux-vdso.so.1 =>  (0x00007fff605ff000)
	libstdc++.so.6 => /lustre/usr/gcc/4.9/lib64/libstdc++.so.6 (0x00002aea15651000)
	libz.so.1 => /lib64/libz.so.1 (0x000000396de00000)
	librt.so.1 => /lib64/librt.so.1 (0x000000396e200000)
	libm.so.6 => /lib64/libm.so.6 (0x000000396d600000)
	libgcc_s.so.1 => /lustre/usr/gcc/4.9/lib64/libgcc_s.so.1 (0x00002aea15985000)
	libc.so.6 => /lib64/libc.so.6 (0x000000396ce00000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x000000396da00000)
	/lib64/ld-linux-x86-64.so.2 (0x000000396ca00000)
	
I skipped the bazel tests and consider it as an acceptable workaround. Look forward to your smart approaches to search paths.

**Comment by ffmpbgrnn** [comment]
Hi, @weijianwen , @damienmg is the problem resolved? I met the same problem and I could build tensorflow with output/bazel?

**Comment by weijianwen** [comment]
@ffmpbgrnn I just cloned the latest bazel code and found my issue can be reproduced on it, which simply means the "CC path issue" is not solved yet. My workaround is to replace the path manually.

**Comment by ffmpbgrnn** [comment]
@weijianwen , i tried to solve by adding to `Wl,-rpath,$HOME/local/lib64` to `LDFLAGS`, which will make [build-runfiles](https://github.com/bazelbuild/bazel/blob/master/scripts/bootstrap/compile.sh#L328) build successfully. However, I failed to build Tensorflow with the compiled bazel binary and met [this](https://github.com/bazelbuild/bazel/issues/649#issuecomment-166059533) problem.

Can you build your software smoothly with the bazel binary you built?

**Comment by i3v** [comment]
For now (e.g. roughly a year later) I had no problem compiling bazel-0.4.1 with gcc-4.9.4, installed within my `$HOME` directory (the default system compiler is gcc-4.4.7). However, similar fixes are still [required](file:///C:/Users/i3v/Documents/Scrapbook/data/20161207182740/index.html#issuecomment-265431453) to build tensorflow 0.12rc0.
