### ISSUE TITLE
Deprecation of //tools/defaults package

### ISSUE THREAD

**Issue by dbabkin** [bazelbuild/bazel#5910]
Dear Bazel users!

We are very close to remove in-memory //tools/default* package in favor of using @bazel_tools//tools/jdk: and @bazel_tools//tools/cpp: instead.
The changes will be ready with next release.

Motivation:
//tools/default was initially created as virtual in-memory package. It generates content dynamically based on current configuration. There is no need of having //tools/defaults any more as LateBoundAlias can generate dynamic configuration-based label resolving.  Also, having //tools/default makes negative impact on performance, and introduces unnecessary code complexity. 

All references to //tools/defaults:* targets should be removed or replaced to corresponding target in @bazel_tools//tools/jdk: and @bazel_tools//tools/cpp: packages.

Scope of changes and impact:
All targets in //tools/default will not exist any more. If you have any references inside your BUILD or *.bzl files to any of its, then bazel will fail to resolve.

Migration plan:

Please replace all occurrences:

- //tools/defaults:jdk
-- by @bazel_tools//tools/jdk:current_java_runtime
-- or/and @bazel_tools//tools/jdk:current_host_java_runtime

- //tools/defaults:java_toolchain
-- by @bazel_tools//tools/jdk:current_java_toolchain

- //tools/defaults:crosstool
-- by @bazel_tools//tools/cpp:current_cc_toolchain 
-- or/and @bazel_tools//tools/cpp:current_cc_host_toolchain 
-- if you need reference to libc_top, then @bazel_tools//tools/cpp:current_libc_top

These targets will not be supported any more:
//tools/defaults:coverage_report_generator
//tools/defaults:coverage_support

**Comment by dbabkin** [comment]
Change was submitted on 10th of August: https://github.com/bazelbuild/bazel/commit/6300c7eb70622b55bbc5f73ec1ffe8116d55c9cd

**Comment by mhlopko** [comment]
I'll file individual issues, thanks!
