### ISSUE TITLE
documentation for `load` statement is missing

### ISSUE THREAD

**Issue by wayou** [bazelbuild/bazel#5913]
https://github.com/bazelbuild/bazel/blob/820a46af10808396873c36d0f331e533118cf0c6/src/main/java/com/google/devtools/build/docgen/templates/be/overview.vm#L41

This link refers to a none-existing hash of the [`Functions`](https://docs.bazel.build/versions/master/be/functions.html#functions) page. The part for `load` statement is missing.  Found some infomation about the `load` in the [`Extension overview` page](https://docs.bazel.build/versions/master/skylark/concepts.html#loading-an-extension) and maybe this is where to link to.

**Comment by laurentlb** [comment]
Correct. `load()` was incorrectly categorized as a function. It's actually a language keyword (like `import` in other languages). But the link was not updated.

Thanks for the report!
