### ISSUE TITLE
Skylint should allow UpperCamelCase identifiers for provider aliases

### ISSUE THREAD

**Issue by JaredNeil** [bazelbuild/bazel#5914]
Currently identifiers are only allowed to be `lower_snake_case` or `UPPER_SNAKE_CASE` in most cases, and also allowed to be `UpperCamelCase` if they are being [declared as a provider](https://github.com/bazelbuild/bazel/blob/901cc6c7474e2a6cc8c3812d156177f44dcb76ed/src/tools/skylark/java/com/google/devtools/skylark/skylint/NamingConventionsChecker.java#L37). This does not allow provider aliases to also be `UpperCamelCase`.

This issue came up in [this PR](https://github.com/angular/angular/pull/25256) to the angular repository. Skylint fails on [line 25](https://github.com/angular/angular/pull/25256/commits/763787afb27e8204b27b81a4e3c6c3dc6b0050b3#diff-c698d0f2da7b832a7e85568294e6653eR25) of `rules_typescript.bzl` with the following error.
```
./packages/bazel/src/rules_typescript.bzl:25:1-25:12: identifier 'TsConfigInfo' should be lower_snake_case (for variables) or UPPER_SNAKE_CASE (for constants) [name-with-wrong-case]
```

Possible solutions:

1. Always allow identifiers to be `UpperCamelCase`
2. Allow identifiers to be `UpperCamelCase` if the right side of the assignment also appears to be `UpperCamelCase`-ish.

**Comment by laurentlb** [comment]
Suggestion: enforce that Identifiers are either
 * `lower_snake_case`,
 * `UPPER_SNAKE_CASE`, or
 * `UpperCamelCaseWithSuffixInfo`
