### ISSUE TITLE
Not possible to use .axf as executable extension

### ISSUE THREAD

**Issue by staalb** [bazelbuild/bazel#5920]
### Description of the problem / feature request:

I'm cross compiling for ARM on Windows. Usually the resulting binaries have the .axf extension. However, if I configure that in the CROSSTOOL file using 'artifact_name_pattern' I get the following error when building:

> ERROR: Unrecognized file extension '.axf', allowed extensions are '' or '.exe', please check artifact_name_pattern configuration for executable in your CROSSTOOL.

### Feature requests: what underlying problem are you trying to solve with this feature?

Cross compiling, using other toolchains than GCC.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Include following fragment in your CROSSTOOL:
```
  artifact_name_pattern {
    category_name: "executable"
    prefix: ""
    extension: ".axf"
  }
```

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

> release 0.15.2

###  Have you found anything relevant by searching the web?

Yes, found nothing related

### Any other information, logs, or outputs that you want to share?

Most obvious solution would be to add this extension to this line:
https://github.com/bazelbuild/bazel/blob/ece8d5fc1adbbb924122b9f1201a877839da2d27/src/main/java/com/google/devtools/build/lib/rules/cpp/ArtifactCategory.java#L30

However, I'm wondering why the extension supplied by the CROSSTOOL file is 'checked' against a list of extensions internally by Bazel. Why don't trust the CROSSTOOL file?

**Comment by mhlopko** [comment]
I'll accept a PR that will add this extension to https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/cpp/ArtifactCategory.java;l=30?q=getAllowedExtensions&ss=bazel and a test here https://source.bazel.build/bazel/+/6488dd3c9d2b2c703a6fe24b083bf07d975ff46b:src/test/java/com/google/devtools/build/lib/rules/cpp/CcLibraryConfiguredTargetTest.java :)
