### ISSUE TITLE
Ability to set "linkstatic = True" for native cc_proto_library

### ISSUE THREAD

**Issue by dirkboye** [bazelbuild/bazel#5924]
### Description of the problem / feature request:

Ability to set "linkstatic = True" for native cc_proto_library

As a workaround I can use https://github.com/google/protobuf/blob/master/protobuf.bzl#L229 and pass kargs into cc_proto_library but then I don't use the nice native implementation of bazel.

### Feature requests: what underlying problem are you trying to solve with this feature?

I need to link some LGPL code (included in WORKSPACE with new_http_archive....) as shared library. 
All "internal" libraries of my WORKSPACE are marked "linkstatic = True".
One binary I set to "linkstatic = False" so it links the third_party library dynamically and all my internal libs are linked statically.

That works well so far, except that my protobufs are also linked dynamically.

### What operating system are you running Bazel on?

Fedora 28

### What's the output of `bazel info release`?

release 0.16.1- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Download zip and run compile.sh

**Comment by hlopko** [comment]
Can you try building bazel from HEAD and passing `--features=proto_dynamic_mode_static_link`?

**Comment by yeswalrus** [comment]
Ping, This would be extremely helpful. I'm running into the same issue with bazel 5.1.1.
