### ISSUE TITLE
Documentation of deps gives wrong description in example for limiting depth

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#5929]
### Description of the problem / feature request:

https://docs.bazel.build/versions/master/query.html#deps

> The deps operator accepts an optional second argument, which is an integer literal specifying an upper bound on the depth of the search. So `deps(foo:*, 1)` evaluates to all the direct prerequisites of any target in the foo package, and `deps(foo:*, 2)` further includes the nodes directly reachable from the nodes in `deps(foo:*, 1)`, and so on.

The example in the second sentence is wrong because `deps(foo:*, 1)` returns the direct prerequistes of any target in the foo package ***and all the targets in the foo package***.

**Comment by mehrdadn** [comment]
Yes, this is really confusing. Also, is there a way to get just the prerequisites themselves? That'd be a really useful feature.
