### ISSUE TITLE
Deadlink in docs for target patterns

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#5930]
https://docs.bazel.build/versions/master/query.html#target-patterns

In 
>bazel query target patterns work the same as bazel build build targets do; refer to Target Patterns in the Bazel User Manual for further details, or type bazel help target-syntax.

There is a link to: https://docs.bazel.build/versions/master/bazel-user-manual.html#target-patterns
This is a dead link.

**Comment by fweikert** [comment]
Link has been fixed to point at the correct page (https://docs.bazel.build/versions/master/user-manual.html#target-patterns).
