### ISSUE TITLE
Testonly is not correctly respected by testsuites

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#5935]
### Description of the problem / feature request:

I expect that non testonly rules that depend on testonly rules to not build. This doesn't happen for test suites.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
https://gist.github.com/endobson/d0b0c8adbce88bc50e48d81aad0c4718

If I try to run the tests then the tests actually run
```
endobson@yggdrasil () ~/tmp/bazel-testonly-bug % bazel test //:all_tests
INFO: Analysed target //:foo_test (0 packages loaded).
INFO: Found 1 test target...
FAIL: //:foo_test (see /private/var/tmp/_bazel_endobson/96219cd1558049fe89b271cdb9238987/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/foo_test/test.log)
INFO: From Testing //:foo_test:
==================== Test output for //:foo_test:
================================================================================
Target //:foo_test up-to-date:
  bazel-bin/foo_test
INFO: Elapsed time: 0.239s, Critical Path: 0.12s
INFO: 1 process: 1 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//:foo_test                                                              FAILED in 0.1s
  /private/var/tmp/_bazel_endobson/96219cd1558049fe89b271cdb9238987/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/foo_test/test.log

INFO: Build completed, 1 test FAILED, 2 total actions
```

If I try to run without expand the testsuites, I get an error but the tests still run:
```
endobson@yggdrasil () ~/tmp/bazel-testonly-bug % bazel test //:all_tests --noexpand_test_suites
ERROR: /Users/endobson/tmp/bazel-testonly-bug/BUILD.bazel:6:1: in test_suite rule //:all_tests: non-test target '//:all_tests' depends on testonly target '//:foo_test' and doesn't have testonly attribute set
WARNING: errors encountered while analyzing target '//:all_tests': it will not be built
INFO: Analysis succeeded for only 1 of 2 top-level targets
INFO: Analysed 2 targets (0 packages loaded).
INFO: Found 1 test target...
FAIL: //:foo_test (see /private/var/tmp/_bazel_endobson/96219cd1558049fe89b271cdb9238987/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/foo_test/test.log)
INFO: From Testing //:foo_test:
==================== Test output for //:foo_test:
================================================================================
Target //:foo_test up-to-date:
  bazel-bin/foo_test
ERROR: command succeeded, but not all targets were analyzed
INFO: Elapsed time: 0.241s, Critical Path: 0.12s
INFO: 1 process: 1 darwin-sandbox.
FAILED: Build did NOT complete successfully
//:foo_test                                                              FAILED in 0.1s
  /private/var/tmp/_bazel_endobson/96219cd1558049fe89b271cdb9238987/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/foo_test/test.log

FAILED: Build did NOT complete successfully
```

The output says that the test suite will not be built and yet it still runs.

```
endobson@yggdrasil () ~/tmp/bazel-testonly-bug % bazel version
Build label: 0.16.1- (@non-git)
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Aug 16 04:42:18 2018 (1534394538)
Build timestamp: 1534394538
Build timestamp as int: 1534394538
```

**Comment by katre** [comment]
I'm not sure what it means for a testsuite to be set as "testonly = 0". What are you trying to accomplish with this?

**Comment by katre** [comment]
And, specifically, testsuite overrides "testonly" and sets it to true: https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/test/TestSuiteRule.java;drc=2247116da2dc83c344368a68c0eea42fcc8dce30;l=37

**Comment by endobson** [comment]
I'm trying to have rules that depend on aspectified versions of tests to do static analysis and then bundle the output.

For example I have an aspect that when applied to a library rule or test rule, runs over the source code and outputs a file that contains unused dependencies. I then have a rule which applies this aspect down through all of the dependencies and then provides a single output file.

I have other ones which provide mappings of module names to file names, which are then used by another round of analysis to produce editing commands/buildifier commands to add missing/remove extra dependencies. The compiled mapping file cannot be test only because then it cannot be depended on the aspect that is doing the analysis. (See issue #5933)

Because of this I have the current workaround of making all my `_test` rules as not testonly. I have also  done the same to the `test_suite` rules. This issue is reporting the issue that `test_suite`s have inconsistent behavior depending on whether they are expanded or not.

Link to the script which runs these analysis:
https://github.com/endobson/yaspl2/blob/94aeea3fad31934cff081965b08d592f0171f33c/scripts/add-missing-dependencies.sh

**Comment by endobson** [comment]
Can I not be marked as an assignee of this? I've given the more data. I'm not on the project and so cannot remove myself, and the new buganizer mirror made a bug assigned to me which I cannot modify.

**Comment by katre** [comment]
My apologies: I forgot to reset the "untriaged" label, and so this slipped through the cracks. I have unassigned you and am taking a look at your comments now.

**Comment by katre** [comment]
@dslomov Do you understand how aspects interact with testonly? Because I am very confused by it.

**Comment by katre** [comment]
Assigning to @sdtwigg to decide whether this is an actual issue, or whether to close.

**Comment by sdtwigg** [comment]
Test rules and test_suite rules explicitly override testonly to be true. This is intentional.

test_suite rules only accept test rules in the `tests` attribute and thus a test_suite rule with `testonly` as false would have to empty, which seems vacuous.

**Comment by endobson** [comment]
sdtwigg: You seem to be assuming that test rules need to be marked as test only, this is not the case. Test rules only have that bit set by default to true, and it can be overriden.

I currently have many test rules which are not test only due to issues with aspects and test only https://github.com/bazelbuild/bazel/issues/5933

Example:
https://github.com/endobson/yaspl2/blob/1b8209c8551aa226d4b865e43a16a32232f57e64/BUILD#L30

I cannot reopen but I think this issue is not resolved.

**Comment by endobson** [comment]
So it seems that the implementation is making assumptions that all test and test_suite rules are marked as test only. And that misbehaviors because those assumptions are violated are 'wont fix'. Is there a bug tracking the enforcement that you say should ideally happen, because to me it seems that there is still an underlying issue here?

The root issue is not aspects as the reproduction steps don't include them and still show the issue. The change to the enforcement will not be trivial, as it will be a breaking change (and aspects make it a relevant one).

**Comment by sdtwigg** [comment]
I claim it as the actual root issue because otherwise users do not have a need to mark tests or testsuites as not-testonly.

Will create the enforcement issue after some more contemplation.
