### ISSUE TITLE
Forbid `native.package()` in bzl files

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#5939]
Using `native.package()` in bzl files makes the code hard to maintain. When `package()` is called in a bzl file, it silently modifies the semantics of a BUILD file. This can be surprising and it may confuse tools. In particular, it means that we can't call the `package()` function in the BUILD file (because it can be called only once). So it makes automated changes very hard, e.g. set the default `features =` in all BUILD files.

**Comment by brandjon** [comment]
I completely misunderstood this proposal on first read -- I thought you wanted to remove package() entirely!

You're saying to keep `package()` allowed in BUILD files, but remove the `native.package()` spelling within .bzl files, the rationale being that `package()` declarations should syntactically appear in the BUILD file they affect.

If all we do is remove `native.package()`, then .bzl files could theoretically still access the `package()` function if it is passed in to a macro:

    # BUILD file
    load(":my_logic.bzl", "my_special_header")
    my_special_header(package)
    ...

    # my_logic.bzl
    def my_special_header(package_func):
        package_func(...)

The simplest thing to do is allow but discourage this monstrosity. Alternatively, we could give `package()` the magical ability to inspect the stack and fail if it is not called from within a BUILD file.

**Comment by laurentlb** [comment]
Sorry for being unclear, it's only about removing it from bzl files environment.

As you point out, it's not perfect, but I think it would be enough. Your code sample is convoluted, so it will discourage users from doing it. I don't think we should add stacktrace magic for that.

**Comment by laurentlb** [comment]
Based on an offline discussion, we can first add a linter warning for `native.package()`.

**Comment by laurentlb** [comment]
Based on https://github.com/bazelbuild/bazel/issues/7496, it seems useful to be consistent and expose the same symbols in BUILD files as in the native module.

I think we can close this issue: the linter check can be sufficient.
