### ISSUE TITLE
Gerrit fails with Bazel@HEAD 

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#5944]
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/392#1605b89c-9b14-4a26-8518-2d478ad9ba53
```
ERROR: /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1604-java8-t6xh-1/bazel-downstream-projects/gerrit/gerrit-gwtui/BUILD:16:1: Couldn't build file gerrit-gwtui/libui_module_r-class.jar: Building gerrit-gwtui/libui_module_r-class.jar (354 source files) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor) failed (Exit 1)
--
  | gerrit-gwtui/src/main/java/com/google/gerrit/client/FormatUtil.java:129: error: [MathRoundIntLong] Math.round(Integer) results in truncation
  | int p = Math.abs(Math.round(delta * 100 / size));
  | ^
  | (see https://errorprone.info/bugpattern/MathRoundIntLong)
  | Did you mean 'int p = Math.abs(Ints.saturatedCast(delta * 100 / size));'?

```

@cushon Is this some new java annotation process feature? I don't see the same failure with latest release Bazel.

/cc @davido Can we fix from gerrit side?

**Comment by davido** [comment]
The code in question is GWT UI code, hat we haven't touched for years. I assume that error-prone was updated on Bazel master?

While we currently don't use Guava library in GWT client code (and I would rather not start using it, because we will eventually remove GWT UI in future), it should be easily fixable using `saturatedCast`

```
public static int saturatedCast(long value) {
100    if (value > Integer.MAX_VALUE) {
101      return Integer.MAX_VALUE;
102    }
103    if (value < Integer.MIN_VALUE) {
104      return Integer.MIN_VALUE;
105    }
106    return (int) value;
107  }
```

**Comment by davido** [comment]
Change under review: https://gerrit-review.googlesource.com/c/gerrit/+/193670.

**Comment by davido** [comment]
The mentioned change was merged on master. This should be fixed now.

**Comment by meteorcloudy** [comment]
Yes, it's fixed! Thank you so much!
