### ISSUE TITLE
TensorFlow and TensorFlow_serving are failing with Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#5945]
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/392#_

TensorFlow on Windows:
```
ERROR: Config value monolithic is not defined in any .rc file
```

TensorFlow_serving on Ubuntu:
```
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:

/var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1804-java8-00w3-1/bazel-downstream-projects/serving/tools/bazel.rc
...
cannot stat '/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/70c080ed8892b6938b5ec28c95adff17/sandbox/linux-sandbox/2378/execroot/tf_serving/external/com_github_libevent_libevent/*': No such file or directory
```
In TensorFlow_serving's `tools/bazel.rc`, it defines the following to disable sandbox:
```
build --spawn_strategy=standalone --genrule_strategy=standalone
test --spawn_strategy=standalone --genrule_strategy=standalone
run --spawn_strategy=standalone --genrule_strategy=standalone
```

I believe the root cause is the recent change on bazelrc location: https://github.com/bazelbuild/bazel/commit/ec83598cb6ee4136166bb562a24dc5dfa58921db

TensorFlow will be fixed when https://github.com/tensorflow/tensorflow/pull/21374 is merged

Filed an PR to fix TensorFlow_serving: https://github.com/tensorflow/serving/pull/1066

**Comment by meteorcloudy** [comment]
This is fixed by https://github.com/bazelbuild/bazel/commit/d96f1576107d0d4eba7c6dd745ac7aea40311cc9 from Bazel side.
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/401#a37f63b2-88aa-423e-9d76-18b504de262f

**Comment by meteorcloudy** [comment]
With the rollfoward https://github.com/bazelbuild/bazel/commit/8ceaa65973eb599d9635fa9bc566aefd1f57348c, this issue is appearing again

**Comment by perfinion** [comment]
@meteorcloudy the fix is in TF now, is this fixed now too?

**Comment by meteorcloudy** [comment]
@perfinion Yes, TensorFlow is green again on our CI, but TensorFlow_serving is still pinned to an older commit of TensorFlow. I'll disable it temporarily.

**Comment by perfinion** [comment]
@meteorcloudy Can you verify https://github.com/tensorflow/tensorflow/pull/22966 and https://github.com/tensorflow/tensorflow/pull/22964 ?
The plan is now to put back tools/bazel.rc immediately since RC9 reads that again. Then when we can we'll do 22964 and bump the minimum bazel version to 0.18.0

**Comment by jin** [comment]
Is this still an issue? Can this be closed?
