### ISSUE TITLE
mobile-install doesn't work with native activities

### ISSUE THREAD

**Issue by ahumesky** [bazelbuild/bazel#595]
The app successfully builds but when running the app it fails with:

java.lang.RuntimeException: Unable to instantiate application com.google.devtools.build.android.incrementaldeployment.StubApplication: java.lang.ClassNotFoundException: Didn't find class "com.google.devtools.build.android.incrementaldeployment.StubApplication" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

Directory structure:
```
WORKSPACE
android/
  java/
    native_app/
      AndroidManifest.xml
      BUILD
      jni/
        android_native_app_glue.c (https://github.com/googlesamples/android-ndk/blob/master/native-activity/app/src/main/jni/native_app_glue/android_native_app_glue.c)
        android_native_app_glue.h (https://github.com/googlesamples/android-ndk/blob/master/native-activity/app/src/main/jni/native_app_glue/android_native_app_glue.h)
        main.c (https://github.com/googlesamples/android-ndk/blob/master/native-activity/app/src/main/jni/main.c)
      res/
        values/
          strings.xml
```
This is what the BUILD file looks like:
```
cc_library(
    name = "mylib",
    srcs = glob(["jni/*.h", "jni/*.c"]),
    linkopts = ["-llog", "-landroid", "-lEGL", "-lGLESv1_CM"]
)

android_binary(
    name = "myapp",
    legacy_native_support = 0,
    manifest = "AndroidManifest.xml",
    deps = [":mylib"],

    resource_files = glob(["res/**"])
)
```
And the manifest file:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
      package="mynativeapp.android"
      android:versionCode="1"
      android:versionName="1.0">
  <uses-sdk android:minSdkVersion="9" />

  <application android:label="@string/app_name"
               android:hasCode="false">
    <activity android:name="android.app.NativeActivity"
              android:label="@string/app_name">
      <meta-data android:name="android.app.lib_name"
                 android:value="myapp" />
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
  </application>
</manifest>
```

**Comment by lberki** [comment]
This is strange. The stub application doesn't end up in the main APK, which doesn't have anything to do with the native activities. Investigating.

**Comment by lberki** [comment]
Meh, it is there, may bad. Then I have no idea what doesn't work...

**Comment by lberki** [comment]
Oh, stupid me. This is because you put `android:hasCode="false"` into your AndroidManifest.xml . If you do that, Android will not find the stub application Bazel injects into the APK.

If you remove it, it will work as expected (your app starts writing accelerometer messages into logcat and blacks out the screen. I guess that's what it's supposed to do.) Let me make it so that `android:hasCode` is removed from the manifest...
