### ISSUE TITLE
Installer script on mac for putting 0.16.1 on the system yields to 0.11.0-homebrew.

### ISSUE THREAD

**Issue by philderbeast** [bazelbuild/bazel#5951]
### Description of the problem / feature request:

> As can be seen in the thread of https://github.com/tweag/rules_haskell/issues/409#issuecomment-414690649, I ran the installer script for mac, the [recommended method](https://docs.bazel.build/versions/master/install-os-x.html) of installing bazel, using the script for [release 0.16.1](https://github.com/bazelbuild/bazel/releases/tag/0.16.1). The [bazel-0.16.1-installer-darwin-x86_64.sh](https://github.com/bazelbuild/bazel/releases/download/0.16.1/bazel-0.16.1-installer-darwin-x86_64.sh) file. The version I ended up with is 0.11.0-homebrew.

```
> bazel version
Build label: 0.11.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sun May 1 04:04:22 +50118 (1519414517062)
Build timestamp: 1519414517062
Build timestamp as int: 1519414517062
```

### Feature requests: what underlying problem are you trying to solve with this feature?

> I'd like for the installer script to install the latest version or the version that matches the release of the installation script.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> To reproduce, follow the recommended install instructions for mac.

### What operating system are you running Bazel on?
 
```
> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
```

### What's the output of `bazel info release`?

```
> bazel info release
ERROR: The 'info' command is only supported from within a workspace.
```

Although I don't remember having done this, it seems that homebrew knows about bazel so perhaps I did install it that way in the past. However, it would be nice if the installer script was able to detect and warn about this, about conflicting methods of installation and how if a homebrew install exists then running the installer script will not install an up to date version of bazel.

```
> brew list bazel
/usr/local/Cellar/bazel/0.11.0/bin/bazel
/usr/local/Cellar/bazel/0.11.0/bin/bazel-real
/usr/local/Cellar/bazel/0.11.0/etc/bash_completion.d/bazel-complete.bash
/usr/local/Cellar/bazel/0.11.0/libexec/bin/ (2 files)
/usr/local/Cellar/bazel/0.11.0/share/zsh/site-functions/_bazel
```

**Comment by jin** [comment]
What is the result of `echo $PATH`?  I believe the installation script installs to `$HOME/bin`, which may be after the brew `bin` dir in the `$PATH`.

**Comment by philderbeast** [comment]
Thanks @jin but I have since uninstalled 0.11.0-homebrew and installed again with the installer script. I added `$HOME/.bazel/bin` to `PATH` in `.bash_profile` too. Would you still need the `echo $PATH` result now or has the moment where we could have captured the problem setup been lost?

```
> brew uninstall bazel
> chmod +x bazel-0.16.1-installer-darwin-x86_64.sh
> ./bazel-0.16.1-installer-darwin-x86_64.sh --user
> bazel version
WARNING: --batch mode is deprecated.
Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Build label: 0.16.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 13 13:42:50 2018 (1534167770)
Build timestamp: 1534167770
Build timestamp as int: 1534167770
```

**Comment by philderbeast** [comment]
```
> echo $PATH
/Library/Frameworks/Python.framework/Versions/3.6/bin /Users/pdejoux/.local/bin /Users/pdejoux/.cabal/bin /usr/local/sbin /Users/pdejoux/.bazel/bin /Users/pdejoux/.nix-profile/bin /Users/pdejoux/.nix-profile/lib/kde4/libexec /nix/var/nix/profiles/default/bin /nix/var/nix/profiles/default /nix/var/nix/profiles/default/lib/kde4/libexec ~/.dotnet/tools /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Applications/VMware Fusion.app/Contents/Public /usr/local/share/dotnet /Library/Frameworks/Mono.framework/Versions/Current/Commands /Library/TeX/texbin /Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
```

**Comment by jin** [comment]
It looks like the problem is resolved, is that right?

**Comment by philderbeast** [comment]
For me it is but I suspect that it could stump someone else if they install version-x with homebrew and then try the installer script to install version-y.

**Comment by buchgr** [comment]
Please see https://blog.bazel.build/2018/08/22/bazel-homebrew.html for how to install Bazel in homebrew.

**Comment by philwo** [comment]
I can see two possible improvements here:
- Detect whether Homebrew is installed and if yes, whether Bazel is installed via Homebrew. If yes, print a warning.
- Generally detect whether Bazel is on the $PATH in a location where we're not going to put it. If yes, warn the user.

As we won't have time to work on this, I'll leave it as P3 Feature Request and would encourage someone who wants to contribute a patch to take this.
