### ISSUE TITLE
GCC FDO support

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#5960]
I'm a happy user of Bazel's GCC FDO support, so I was sad to see 464a8941b07dd597c53aeec0ca506c4f6cd5d7bf land. I wondering if there's a way to remove most of the code but still support GCC. For example, could the `fdo_profile` rule accept a the `.gcda` directory tree directly? E.g.,
```
fdo_profile(
    name = 'my-gcc-profile',
    srcs = glob(['**/*.gcda']),
)
```
Then the zip wouldn't have to be unpacked in the C++ rules.

**Comment by SaveTheRbtz** [comment]
A friendly ping here.  Any plans on reviving this?
