### ISSUE TITLE
Release - September 2018 - name: 0.18.0

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#5963]
@aehlig Can you take care of the release 0.18.0?

**Comment by aehlig** [comment]
> @aehlig Can you take care of the release 0.18.0?

I can take care of 0.18.0, provided it is OK that the baseline
will be cut a bit late: I'm on vacation September 1--8. But given
that 0.17.0 is delayed anyway, this should be fine.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by laurentlb** [comment]
Sounds good, we can target September 10 or 11.

**Comment by mhlopko** [comment]
It's actually awesome, because I can finish my incompatible flags cls :)))

**Comment by laszlocsomor** [comment]
Potential blocker: https://github.com/bazelbuild/bazel/issues/6061
(Need to verify if 0.18.* is affected or whether the bug is a regression.)

**Comment by aehlig** [comment]
Looking through the last nighly builds and tests of downstream
projects, the most promising baseline seems to be 2e7ccbe5cf15b7f4e8a77a2a94d0e071abfb1478

@laszlocsomor, this baseline also includes the update of protobuf to 3.6.1; do I
understand correctly, that this resolves your potential release blocker?

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by laszlocsomor** [comment]
@aehlig : Yes, that commit is beyond https://github.com/bazelbuild/bazel/commit/ddc97ed6b0367eb443e3e09a28d10e65179616ab so the potential blocker is not a blocker. Thanks for checking!

**Comment by laszlocsomor** [comment]
Another potential blocker: https://github.com/bazelbuild/bazel/issues/6099
I'll test the RC to see if it's affected.

**Comment by aehlig** [comment]
Creating 0.18.0rc1, baseline 2e7ccbe5cf15b7f4e8a77a2a94d0e071abfb1478, no cherry picks.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by laurentlb** [comment]
Some cherrypicks of 0.17 are not included in your baseline.

**Comment by mhlopko** [comment]
Please consider picking a later baseline, since we decided to follow https://docs.bazel.build/versions/master/skylark/backward-compatibility.html quite late, we rushed to submit needed cls:

* 547bf42207fc0a84178e0ada7030550567869f13
* a792821ab6287f38b05636da36a3c5f8ab805535
* 13d70a93dd795f65149a0000ee6076b412d67aa9
* 52b208efda6d02c1ea140e6bdcc0b814c6c1788d

@scentini to verify I didn't miss anything

**Comment by aehlig** [comment]
0.18.0rc1 is available at https://releases.bazel.build/0.18.0/rc1/index.html

Will create another RC with the cherry-picks that went into 0.17.1 but are not in
the baseline soon.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment]
> Some cherrypicks of 0.17 are not included in your baseline.

According to the logs on #5059, we're talking about

9323c57607d37f9c949b60e293b573584906da46 7eb9ea150fb889a93908d96896db77d5658e5005 4566a428c5317d87940aeacfd65f1018340e52b6 1e9f0aa89dad38eeab0bd40e95e689be2ab6e5e5 a572c1cbc8c26f625cab6716137e2d57d05cfdf3 29f1de099e4f6f0f50986aaa4374fc5fb7744ee8

Is this correct?

Will also check if tomorrow's nighly is suitable as a base line. If not,
I will try to add those cherry-picks on the current base line.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by cushon** [comment]
@lberki are you planning to include 7eb9ea150fb889a93908d96896db77d5658e5005 in 0.18 too?

**Comment by cushon** [comment]
@aehlig can you cherry-pick c6eef5df8ac93207500be67b097a2becadd0736f for #6105?

**Comment by lberki** [comment]
@mhlopko is informing me that there will be a new baseline

**Comment by aehlig** [comment]
> Will also check if tomorrow's nighly is suitable as a base line.

Looks good. The only thing we have to look at is what's going on with Gerrit and jdk9 as this might be bazel related.

So, let's push the baseline forward to c062b1f1730f instead of starting with too many cherry-picks right from the beginning.

**Comment by mhlopko** [comment]
Fantastic, thanks Klaus!

**Comment by davido** [comment]
> The only thing we have to look at is what's going on with Gerrit and jdk9

Can you share the logs?

**Comment by aehlig** [comment]
> > The only thing we have to look at is what's going on with Gerrit and jdk9
> 
> Can you share the logs?

The first error message is

```
ERROR: /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1804-java9-lfqk-1/bazel-downstream-projects/gerrit/java/com/google/gerrit/index/BUILD:8:1: Couldn't build file java/com/google/gerrit/index/libquery_exception-hjar.jar: Compiling Java headers java/com/google/gerrit/index/libquery_exception-hjar.jar (2 files) failed (Exit 1)
An exception has occurred in turbine.
java.lang.IllegalArgumentException: Could not find java.lang on bootclasspath
	at com.google.turbine.binder.Binder.bindPackages(Binder.java:170)
	at com.google.turbine.binder.Binder.bind(Binder.java:94)
	at com.google.turbine.main.Main.compile(Main.java:97)
	at com.google.devtools.build.java.turbine.Turbine.compile(Turbine.java:76)
	at com.google.devtools.build.java.turbine.Turbine.compile(Turbine.java:69)
	at com.google.devtools.build.java.turbine.Turbine.main(Turbine.java:46)
```

This only occurs on JDK9, and Gerrit is the only project we test with JDK9.

A potentially related commit is c1d8776487b8ee69efd50aab3fa84550f7f99ecc.
@cushon, can you have a look as well? Thanks.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment]
rc2 is available at https://releases.bazel.build/0.18.0/rc2/index.html

Please test!

**Comment by davido** [comment]
@aehlig Thanks, I see that @meteorcloudy already created extra issue for this breakage.

**Comment by aehlig** [comment]
> Thanks, I see that @meteorcloudy already created extra issue for this breakage.

This is #6127.

**Comment by lberki** [comment]
...aand, the first cherrypick request: 2834613f93f74e988c51cf27eac0e59c79ff3b8f to fix #6060 (a regression between `0.16` and `0.16.1`, still in `0.17`)

/cc @brendandouglas

**Comment by cushon** [comment]
@aehlig @lberki the fix for #6127 was submitted as 2579b791c023a78a577e8cb827890139d6fb7534

**Comment by aehlig** [comment]
scripts/release/release.sh create --force_rc=3 0.18.0 c062b1f1730f3562d5c16a037b374fc07dc8d9a2 2834613f93f74e988c51cf27eac0e59c79ff3b8f 2579b791c023a78a577e8cb827890139d6fb7534

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment]
rc3 available at https://releases.bazel.build/0.18.0/rc3/index.html

**Comment by aehlig** [comment]
rc3 looks good for all internal tests. So please do test this release candidate and report any potential release blocker within 14 days. Thanks!

**Comment by ittaiz** [comment]
@aehlig it’s a bit hard to test this given 0.17.1 hasn’t yet been released
and there are even still issues with 0.16.1.
Not sure what I’m suggesting but it feels like there is somewhat of a
downward spiral. I might be wrong and we’re past it but that’s a bit of my
concern.

**Comment by petemounce** [comment]
RCs 1-3 pushed to chocolatey.

**Comment by cushon** [comment]
@aehlig @lberki consider cherry-picking b073a18e3fac05e647ddc6b45128a6158b34de2c for #5987, which fixes an ijar bug related to JDK 11.

**Comment by lberki** [comment]
@cushon : it's not a regression, is it?

**Comment by davido** [comment]
I think it's a regression from https://github.com/bazelbuild/bazel/commit/caa2b3c36954b1f4ce4224b5235cc16ff1e8e4b2. Before that change I was able to build Gerrit with JDK11 with Vanilla Java Buidler. After that change the build on JDK11 is broken.

**Comment by cushon** [comment]
I agree with @davido that it's a regression from caa2b3c36954b1f4ce4224b5235cc16ff1e8e4b2. Also, it makes it difficult to use Bazel with JDK 11, and this is the last release we're going to ship before 11 is released.

**Comment by aehlig** [comment]
scripts/release/release.sh create --force_rc=3 0.18.0 c062b1f1730f3562d5c16a037b374fc07dc8d9a2 2834613f93f74e988c51cf27eac0e59c79ff3b8f 2579b791c023a78a577e8cb827890139d6fb7534 faaff7fa440939d4367f284ee268225a6f40b826 b073a18e3fac05e647ddc6b45128a6158b34de2c

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment]
> scripts/release/release.sh create --force_rc=3 0.18.0 c062b1f1730f3562d5c16a037b374fc07dc8d9a2 2834613f93f74e988c51cf27eac0e59c79ff3b8f 2579b791c023a78a577e8cb827890139d6fb7534 faaff7fa440939d4367f284ee268225a6f40b826 b073a18e3fac05e647ddc6b45128a6158b34de2c

Sorry, that should, of course be `--force_rc=4`; aborted that call and started

scripts/release/release.sh create --force_rc=4 0.18.0 c062b1f1730f3562d5c16a037b374fc07dc8d9a2 2834613f93f74e988c51cf27eac0e59c79ff3b8f 2579b791c023a78a577e8cb827890139d6fb7534 faaff7fa440939d4367f284ee268225a6f40b826 b073a18e3fac05e647ddc6b45128a6158b34de2c

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment]
> scripts/release/release.sh create --force_rc=4 0.18.0 c062b1f1730f3562d5c16a037b374fc07dc8d9a2 2834613f93f74e988c51cf27eac0e59c79ff3b8f 2579b791c023a78a577e8cb827890139d6fb7534 faaff7fa440939d4367f284ee268225a6f40b826 b073a18e3fac05e647ddc6b45128a6158b34de2c

rc4 is now available at https://releases.bazel.build/0.18.0/rc4/index.html

Please test this release candidate and report any regressions you may find by Sep 27, 2018.
Thanks!

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment]
We will have to create a new release candidate with bf6a63d64a010f4c363d218e3ec54dc4dc9d8f34 cherry-picked as well for #6219.

**Comment by aehlig** [comment]
scripts/release/release.sh create --force_rc=5 0.18.0 c062b1f1730f3562d5c16a037b374fc07dc8d9a2 2834613f93f74e988c51cf27eac0e59c79ff3b8f 2579b791c023a78a577e8cb827890139d6fb7534 faaff7fa440939d4367f284ee268225a6f40b826 b073a18e3fac05e647ddc6b45128a6158b34de2c

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment]
> scripts/release/release.sh create --force_rc=6 0.18.0 c062b1f 2834613 2579b79 faaff7f b073a18 bf6a63d

rc6 is now available at https://releases.bazel.build/0.18.0/rc6/index.html

Please test. Unless new issues are reported, 0.18.0 will be released on Monday or Tuesday.

**Comment by aehlig** [comment]
As `//src/test/java/com/google/devtools/build/android/idlclass:IdlClassTest` is failing, we
need another cherry-pick.

scripts/release/release.sh create --force_rc=7 0.18.0 c062b1f1730f3562d5c16a037b374fc07dc8d9a2 2834613f93f74e988c51cf27eac0e59c79ff3b8f 2579b791c023a78a577e8cb827890139d6fb7534 faaff7fa440939d4367f284ee268225a6f40b826 b073a18e3fac05e647ddc6b45128a6158b34de2c bf6a63d64a010f4c363d218e3ec54dc4dc9d8f34 c1a7b4c574f956c385de5c531383bcab2e01cadd


-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment]
rc7 is available at

https://releases.bazel.build/0.18.0/rc7/index.html

but it seems, we have to cerry-pick 71926bc25b3b91fcb44471e2739b89511807f96b as well,
to fix `//src/test/shell/bazel/apple:bazel_apple_test`.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment]
> but it seems, we have to cerry-pick 71926bc25b3b91fcb44471e2739b89511807f96b as well,
> to fix `//src/test/shell/bazel/apple:bazel_apple_test`.

scripts/release/release.sh create --force_rc=8 0.18.0 c062b1f1730f3562d5c16a037b374fc07dc8d9a2 2834613f93f74e988c51cf27eac0e59c79ff3b8f 2579b791c023a78a577e8cb827890139d6fb7534 faaff7fa440939d4367f284ee268225a6f40b826 b073a18e3fac05e647ddc6b45128a6158b34de2c bf6a63d64a010f4c363d218e3ec54dc4dc9d8f34 c1a7b4c574f956c385de5c531383bcab2e01cadd 71926bc25b3b91fcb44471e2739b89511807f96b

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by perfinion** [comment]
Can we get https://github.com/bazelbuild/bazel/commit/f03acca9d841a697432663f42dda0e8268b11d34 cherry-picked in 0.18 too? It adds try-import which we need for TensorFlow.

**Comment by dslomov** [comment]
I believe f03acca is in the release.

**Comment by perfinion** [comment]
Ah cool, yeah i double checked the baseline for rc8 and it is in. When I originally clicked the commit github didn't list any tags tho so I wasnt sure.

**Comment by petemounce** [comment]
rc-4-9 pushed to chocolatey.

**Comment by sdqali** [comment]
Thank you for taking on this release. When can we expect this to be out?

**Comment by aehlig** [comment]
> Thank you for taking on this release. When can we expect this to be out?

My plan was to release on Monday, unless more issues are reported.


-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by mhlopko** [comment]
I'm not sure what the process is, so just to be sure I'll say that I'll perform an incompatible change flip (https://github.com/bazelbuild/bazel/issues/6380) in 0.19, so 0.18 should probably mention it as an incoming incompatible change. Or not, if we're not yet doing the new process.

**Comment by laurentlb** [comment]
Tu suggest changes to the announcement, see: https://docs.google.com/document/d/1wDvulLlj4NAlPZamdlEVFORks3YXJonCjyuQMUQEmB0/edit

**Comment by mhlopko** [comment]
That sounds like something I should have done instead spamming this thread :) Thanks Laurent :)

**Comment by aehlig** [comment]
https://github.com/bazelbuild/bazel/releases/tag/0.18.0

**Comment by petemounce** [comment]
Pushed to chocolatey.

**Comment by laurentlb** [comment]
I think we need a patch release 0.18.1 to fix https://github.com/bazelbuild/bazel/issues/6292.

**Comment by meteorcloudy** [comment]
We need to cherry-pick 914b4ce for #6292

**Comment by aehlig** [comment]
On Wed, Oct 17, 2018 at 12:59:50AM -0700, Yun Peng wrote:
> We need to cherry-pick 914b4ce for #6292

Unfortunately, this is not a clean cherry-pick for 0.18.0.
Cherry-picking 914b4ce on top of 0.18.0 conflicts with the changes
by aaba6feff76 which is after the base line for 0.18.0.

@meteorcloudy, please provide guidance on how you want this patch
backported to 0.18.0.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by meteorcloudy** [comment]
@aehlig Thanks for dealing with this.

Can you just make sure 
```
      if (ccToolchain(ruleContext).supportsInterfaceSharedObjects()) {
        ccLinkingHelper.emitInterfaceSharedObjects(true);
      }
```
is added after `CcLinkingHelper ccLinkingHelper = initializeLinkingHelper(featureConfiguration, deps);`
in CcProtoAspect.java?

**Comment by aehlig** [comment]
> @aehlig Thanks for dealing with this.
> 
> Can you just make sure 
> ```
>       if (ccToolchain(ruleContext).supportsInterfaceSharedObjects()) {
>         ccLinkingHelper.emitInterfaceSharedObjects(true);
>       }
> ```
> is added after `CcLinkingHelper ccLinkingHelper = initializeLinkingHelper(featureConfiguration, deps);`
> in CcProtoAspect.java?

The line `CcLinkingHelper ccLinkingHelper = initializeLinkingHelper(featureConfiguration, deps);` does
not exist in `CcProtoAspect.java` of 0.18.0.

Created `0.18.1rc1` as discussed in person with @meteorcloudy.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment]
On Wed, Oct 24, 2018 at 01:26:23PM +0200, Klaus Aehlig wrote:
> > Created `0.18.1rc1` as discussed in person with @meteorcloudy.
> 
> After a couple of attempts to backport 914b4ce14624171a97ff8b41f9202058f10d15b2 correctly,
> finally arrived at `0.18.1rc3`, see
> 
> https://releases.bazel.build/0.18.1/rc3/index.html
> 
> Please test carefully!

This rc fails for the "no JDK" case. The internal CI link
is https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/532#3668026f-a0e0-4d06-ad82-d9d88367347c

@meteorcloudy, is there a way to fix the regression on top of
bazel 0.18.0, or do we have to wait for 0.19.0 with the fix?


-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by meteorcloudy** [comment]
I think the non-JDK issue is already fixed in 0.19.0 or at least from HEAD.
See this issue https://github.com/bazelbuild/bazel/issues/6214

**Comment by meteorcloudy** [comment]
Due to some CI change, we cannot test 0.18.0rc3 on our CI. But I ran a test on my local Windows machine that confirmed the manually cherry-pick did fix #6292.

**Comment by petemounce** [comment]
0.18.1 rc3 pushed to chocolatey. Please could a new release issue be opened for new releases? It's quite easy to miss, otherwise; this ticket is closed.

**Comment by ittaiz** [comment]
Can you please cherry pick https://github.com/bazelbuild/bazel/commit/e025726006236520f7e91e196b9e7f139e0af5f4 for #6456? Thanks! Cc @cushon

**Comment by aehlig** [comment]
On Fri, Oct 26, 2018 at 04:10:42PM +0000, Ittai Zeidman wrote:
> Can you please cherry pick https://github.com/bazelbuild/bazel/commit/e025726006236520f7e91e196b9e7f139e0af5f4 for #6456? Thanks! Cc @cushon

scripts/release/release.sh create --force_rc=4 0.18.1  c062b1f 2834613 2579b79 faaff7f b073a18 bf6a63d c1a7b4c 71926bc 86a8217  914b4ce e025726006236520f7e91e196b9e7f139e0af5f4

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by ittaiz** [comment]
Thanks!

**Comment by petemounce** [comment]
0.18.1-rc4 is published to chocolatey.

**Comment by petemounce** [comment]
0.18.1 is pushed to chocolatey

**Comment by ahippler** [comment]
`bazel-0.18.1-installer-darwin-x86_64.sh` is missing while the sha and the signature are available.
