### ISSUE TITLE
@bazel_source//tools/build_defs/pkg rule fails since 0.17.0rc1 release

### ISSUE THREAD

**Issue by dirkboye** [bazelbuild/bazel#5964]
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run a container_image rule. Since two hours or something I always get following error:
(locally I am still on 0.16.1 but I don't think such an error should occur?)

..../68a9659ed6f66b9bac3d5204ededf76d/external/io_bazel_rules_docker/container/BUILD:67:1: no such package '@bazel_source//tools/build_defs/pkg': java.io.IOException: Error downloading [https://releases.bazel.build/0.17.0/rc1/bazel-0.17.0rc1-dist.zip] to ..../68a9659ed6f66b9bac3d5204ededf76d/external/bazel_source/bazel-0.17.0rc1-dist.zip: Checksum was 46dfffac884ccd51fcb493dd86463cb8c21be949fdb17634ca37805fd544beae but wanted a9afd2b16a21085bd6c0a70a23acce30b105a8af3a7b3c92a4b83bea6b623fd8 and referenced by '@io_bazel_rules_docker//container:build_tar'

### What operating system are you running Bazel on?

fedora 28

### What's the output of `bazel info release`?

release 0.16.1- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

download zip from github
unzip 
./compile.sh

**Comment by bjchambers** [comment]
Looking at the v0.17.0 release thread it looks like rc1 was updated rather than creating an rc2. If so, that would explain these failures, since the checksum would change. I filed https://github.com/bazelbuild/rules_docker/issues/500 about the issue in rules_docker.

I am curious why a release candidate was updated rather than creating a new release candidate so that people depending on a specific version are not impacted.

**Comment by bjchambers** [comment]
Posted a workaround at https://github.com/bazelbuild/rules_docker/issues/500#issuecomment-415217328 in case it helps.

**Comment by fwouts** [comment]
I'm also running into this issue, and it's making CircleCI very sad: https://circleci.com/gh/zenclabs/bazel-javascript/75.

I'd also like to understand why rc1 was replaced instead of creating an rc2.

**Comment by philwo** [comment]
Sorry - this must have been a mistake on our side :( Release numbers and labels have to be immutable. @laurentlb will probably know what happened here. If it’s a bug in our release scripts, I can fix it on Monday.

**Comment by laurentlb** [comment]
My fault, sorry! (also, our script's fault, because it should detect this kind of issue)

@buchgr Do you know if we can fix (rollback?) rc1?

**Comment by buchgr** [comment]
@laurentlb I think the best solution is to create 0.17.1 rc1 and abandon 0.17.0 right way, coupled with an announcement.

**Comment by laurentlb** [comment]
Created 0.17.1: https://releases.bazel.build/0.17.1/rc1/index.html
(sorry for the conflicting name!)

**Comment by jin** [comment]
This should be fixed by using 0.17.1, will close this issue now.
