### ISSUE TITLE
Bazel on Windows: fail to pass --copt

### ISSUE THREAD

**Issue by AnnieYim** [bazelbuild/bazel#5966]
### Description of the problem / feature request:

I am building Tensorflow using Bazel on Windows, the compiler is VS2015(msvc), I want to pass some custom compile options using --copt, but it does't work. However, --linkopt options can be passed to bazel command and take effect.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Executing the following bazel command, and I got the warning:
bazel --output_user_root=${TMPDIR} build **-c dbg --copt=/Ob2** --copt=/arch:AVX -s --strip=never --linkopt=/DEBUG:NONE tensorflow:libtensorflow.so

cl : Command line warning D9024 : unrecognized source file type 'C:/tools/msys64/Ob2', object file assumed
cl : Command line warning D9027 : source file 'C:/tools/msys64/Ob2' ignored

Is there any way for me to pass custom msvc compile options to bazel? 

By the way, when I build on debug mode, bazel seems to hava default link options with /DEBUG:FULL /INCREMENTAL:NO, but I want the --linkopt=/DEBUG:NONE, although it can be passed to bazel command, but my option added seems to be overwritten by the default link option of dbg, how can I solve this problem?

### What operating system are you running Bazel on?

Windows 10 64bit

### What's the output of `bazel info release`?
release 0.15.2

**Comment by meteorcloudy** [comment]
Are you running bazel command in MSYS shell?
You should disable the PATH transformation in MSYS by
```
$ export MSYS_NO_PATHCONV=1
$ export MSYS2_ARG_CONV_EXCL="*"
```

See https://gist.github.com/meteorcloudy/8e5f1aab7c7fa87b16ae28e6f8fd3fd2#build-under-msys-shell

**Comment by AnnieYim** [comment]
@meteorcloudy, I do running in MSYS shell, thanks for your solution!

When I compile on **debug mode**, bazel will add the linking option of /DEBUG:FULL, it will generate too big pdb file. I try to add --linkopt=/DEBUG:NONE in bazel build command, but it will be overwritten by the default option, executing command as follows:

 `C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/link.exe /nologo /DLL /SUBSYSTEM:CONSOLE -DEFAULTLIB:advapi32.lib /MACHINE:X64 /DEBUG:NONE @bazel-out/x64_windows-dbg/bin/tensorflow/libtensorflow.so-2.params /DEBUG:FULL /INCREMENTAL:NO`

Is there any way to change or disable this option on debug mode, e.g. change from /DEBUG:FULL to /DEBUG:NONE?

**Comment by meteorcloudy** [comment]
Why do you need to build in dbg mode if you don't want the pdb file?
If you build in opt mode with `--config=opt`, it will use `/DEBUG:NONE`.

**Comment by meteorcloudy** [comment]
`-c opt` is already defined at https://github.com/tensorflow/tensorflow/blob/master/tools/bazel.rc#L61, you can just remove `-c dbg` to make it work.

**Comment by meteorcloudy** [comment]
Or you can enable fastlink mode, it should generated smaller pdb file by passing `/DEBUG:FASTLINK`.
Try `-c fastlink`

**Comment by laszlocsomor** [comment]
Hi @AnnieYim , did @meteorcloudy 's suggestion (to use `-c opt` instead of `-c dbg`) solve this issue? Can we close this bug?

**Comment by AnnieYim** [comment]
I have solved my problem, @meteorcloudy  thanks for your suggestion and sorry for late response.

**Comment by flyhorseli** [comment]
I have similar problem while using bazel(compiled from scratch) on linux arm32.
--copt is not passed into gcc as expected. Anybody know why?
