### ISSUE TITLE
Gerrit fails on Bazel@HEAD on JDK10

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#5967]
Trying to build Gerrit on JDK10 on Bazel@HEAD (398478c) is failing with: `no such package '@local_jdk//'`. Full log:

```
$ java -fullversion
openjdk full version "10.0.2+13-suse-1.1-x8664"

$ bazel build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java10 --java_toolchain=@bazel_tools//tools/jdk:toolchain_java10 :release
DEBUG: /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/bazel_skylib/lib/versions.bzl:98:7: 
Current Bazel is not a release version, cannot check for compatibility.
DEBUG: /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/bazel_skylib/lib/versions.bzl:99:7: Make sure that you are running at least Bazel 0.14.0.
ERROR: /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/bazel_tools/tools/jdk/BUILD:162:1: no such package '@local_jdk//': Expected directory at /usr/lib64/jvm/java but it does not exist. and referenced by '@bazel_tools//tools/jdk:jdk'
ERROR: Analysis of target '//:release' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.249s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
    currently loading: java/com/google/gerrit/extensions ... (4 packages)
```

To reproduce, clone gerrit from master (a9fc5a9595f72ca5e2ee1171fd15cd2536213d85) and run:

```
 $ bazel build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java10 --java_toolchain=@bazel_tools//tools/jdk:toolchain_java10 :release
```

//CC @cushon

**Comment by cushon** [comment]
I can't reproduce with bazel @ 398478cc334283a6a9c8740f8ac81b5962e5cba7, gerrit @ a9fc5a9595f72ca5e2ee1171fd15cd2536213d85.

```
$ java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
$ bazel build --verbose_failures  --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java10 --java_toolchain=@bazel_tools//tools/jdk:toolchain_java10 :release
...
DEBUG: /usr/local/google/home/cushon/.cache/bazel/_bazel_cushon/f2c5f710b171494819b8b88f2249d816/external/bazel_skylib/lib/versions.bzl:98:7: 
Current Bazel is not a release version, cannot check for compatibility.
DEBUG: /usr/local/google/home/cushon/.cache/bazel/_bazel_cushon/f2c5f710b171494819b8b88f2249d816/external/bazel_skylib/lib/versions.bzl:99:7: Make sure that you are running at least Bazel 0.14.0.
...
Target //:release up-to-date:
  bazel-bin/release.war
```

**Comment by cushon** [comment]
> `Expected directory at /usr/lib64/jvm/java but it does not exist`

Any chance you set `JAVA_HOME` to the path to the `java` binary, instead of the JDK root?

```
$ JAVA_HOME=$(which java) bazel build :a
...
Expected directory at .../bin/java but it is not a directory

$ JAVA_HOME=$(dirname $(dirname $(which java))) bazel build :a
...
Expected directory at .../bin/java but it is not a directory
```

**Comment by davido** [comment]
Right. `JAVA_HOME` was set to a path that doesn't exist. Unsetting `JAVA_HOME` solved it.

**Comment by davido** [comment]
So, the tests are failing, e,g,: [1], but I assume this is not Bazel issue, but a compatibility with asm and/or other dependencies?

[1] http://paste.openstack.org/show/728654

**Comment by cushon** [comment]
Yeah, that stack trace looks like it's using an old version of ASM that doesn't support JDK 10:

```
Caused by: java.lang.IllegalArgumentException
	at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:160)
```

**Comment by davido** [comment]
@cushon @ronshapiro 

Unless we fork Guice, there is currently no way to produce Gerrit with bazel with newer Java versions that is newer as Java 8. Bazel's Java 10 doesn't work with Java 9 any more because of annotation processor issues, that you filed (https://bugs.openjdk.java.net/browse/JDK-8209865) and the released Guice 4.2 is not compatible with Java 10 yet, and Unshading of `asm` dependency from Guice final artifact wasn't done yet.

What is you suggestion to unblock Gerrit Code Review project to be able to be built (and pass tests) with post Java 8 JDK versions?

**Comment by davido** [comment]
One work around idea is to use classes classifier, to consume non shaded Guice artifact from Central, that was mentioned here: [1]. Amd consume this non shaded artifact:

  http://repo1.maven.org/maven2/com/google/inject/guice/4.2.0/guice-4.2.0-classes.jar

Luckily, Gerrit's own `maven_jar` Skylark rule supports classifiers, so that the fix is as easy as to say:

```
GUICE_VERS = "4.2.0"

maven_jar(
    name = "guice-library",
    artifact = "com.google.inject:guice:" + GUICE_VERS + ":classes",
    attach_source = False,
    sha1 = "4c41ec3c1c6230764642f9b5666ff80d2de4273a",
)
```

And provide custom versions of upgraded `asm` and `cglib` dependency. With this hack in place all Gerrit tests pass on JDK10 on Bazel@HEAD and Bazel 0.17.0-rc1: [2]. Elastic tests are failing because docker wasn't running.

[1] https://github.com/google/guice/issues/1198#issuecomment-404932720
[2] http://paste.openstack.org/show/728704

**Comment by ronshapiro** [comment]
That was also going to be my recommendation in the interim. 

@sameb is away for the next ~week so I'm not sure when he'll be able to get around to do another Guice release (I _think_ it's ready, but I don't know for sure)

**Comment by davido** [comment]
Thanks for the update @ronshapiro!

**Comment by sameb** [comment]
I'd like to resolve a cglib compatibility issue with jdk11 and bundle the new cglib into Guice before doing the next release. I was planning to do this before my vacation, but things came up and I wasn't able to do it.   When I return Sept ~4, it should take me a couple hours to fix cglib, validate the fix doesn't break things on Google's repo (as a sanity test), and then release a new Guice with it. I expect I should have it done by Sept 10 or so at the latest.
