### ISSUE TITLE
Changes to C++ built-in directories do not trigger re-analysis

### ISSUE THREAD

**Issue by pconrad-sx** [bazelbuild/bazel#5968]
### Description of the problem / feature request:

This is an important setting, since Bazel doesn't track changes to builtin headers. Setting "/" as a builtin path has the result of deactivating all header recompilation. It appears to be incorrectly stateful, which we can see by performing these steps:
 
1. Compile with "/" as a builtin directory, deactivating header tracking.
2. Remove "/" as a builtin directory and compile again.
3. Until we bazel clean, no changes made to headers will trigger compilation. 
 
Step 2 should force Bazel to redo the header tracking analysis, but that doesn't seem to happen. I demonstrated this by inserting a #error into a header to show that the compiler isn't being invoked as we would expect.

As an aside, I've observed that paths provided as cxx_builtin_include_directory keys in the CROSSTOOL aren't checked for correctness; that is, the directories don't have to exist. Is it possible to check these directories for existence?

I can provide a minimal demonstration of this behavior, if that would be useful.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

This release will reproduce the bug: https://github.com/bazelbuild/bazel/releases/download/0.16.0/bazel-0.16.0-linux-x86_64

###  Have you found anything relevant by searching the web?

No.

**Comment by mhlopko** [comment]
Should be fixed by https://github.com/bazelbuild/bazel/commit/c3a08780f72727025c37a56c593a6eb379b07f99. Please shout if it's not true :)
