### ISSUE TITLE
Bazel build with cycle in dependency graph error

### ISSUE THREAD

**Issue by wonderfuljamesjin** [bazelbuild/bazel#5976]
Hello

I am doing a bazel build for my project,i created a java_library rule and used at different places. but I am having this cycle in dependency graph: issue, please help how to resolve it,   thanks in advanced

```
  ERROR: /Users/git/.../BUILD:11:1: java_library rule //B: cycle in dependency graph:
        //A.class
    .-> //B.class
    |   //C.class
    |   //D.class
    `-- //B.class
This cycle occurred because of a configuration option
```
This is because class B have method need call class D, and class D is also calling class B several times. can i break this cycle, i can not remove remove B from any of BUILD files

**Comment by wonderfuljamesjin** [comment]
Hi @jin 

Do you have some solution on how can I break out class from the cycle,  I am blocked on it.  thanks in advanced

**Comment by cushon** [comment]
Bazel does not allow cycles in the action graph. If there's a cycle in the sources B.java, C.java, and D.java, the usual solution is to include them all in the same `java_library`:

```
java_library(
    name = "your_library",
    srcs = [
        "B.java",
        "C.java",
        "D.java",
    ],
)
```

**Comment by wonderfuljamesjin** [comment]
Hi @cushon 

Thanks for update,  Can you please provide more info here,  and B, C, D etc is at different places, I create several java_library rules and used at different places in several BUILD files. I should include like following in each BUILD file? I did it and still get the cycle in dependency graph error

java_library(
    name = "B",
    srcs = [
        "B.java",
    ],
  deps  = [
        "//..C.java",
       "//..D.java",
    ],
)

**Comment by wonderfuljamesjin** [comment]
Hi @cushon

Does it mean all the java classes that in the dependency cycle  should be restructured in one path, and include them all in the same java_library in the one BUILD file? thanks

**Comment by cushon** [comment]
If the sources that the cycle passes through are in different directories, you can still add them to the same rule:

```
java_library(
    name = "your_library",
    srcs = [
        "b/B.java",
        "c/C.java",
        "d/D.java",
    ],
)
```

but all of those Java files need to be in the `srcs` of the same `java_library`.

Alternately, you could try to refactor to break the cycle, perhaps by extracting an interface. Having fewer `java_library` rules with more sources will generally make incremental builds slower, since more files have to be compiled at once.
