### ISSUE TITLE
Bazel should pass `-no_warning_for_no_symbols` to libtool when using XCode toolchain

### ISSUE THREAD

**Issue by nelhage-stripe** [bazelbuild/bazel#5981]
### Description of the problem / feature request:

I have a (proprietary) project that contains some C++ source code files which, on certain platforms, emit no symbols due to `#ifdef`s.  When I build on macOS, `bazel build` prints useless warnings like:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/darwin-fastbuild/bin/libempty.a(empty.o) has no symbols                                     
```

### Feature requests: what underlying problem are you trying to solve with this feature?

I'd like bazel to pass flags to suppress this useless warning.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

You can easily reproduce with a `cc_library` rule with empty .c file; I've uploaded a minimal test case here: https://gist.github.com/nelhage-stripe/df1374361be6daa938e6ec75f93daf7a

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

> `release 0.16.1`

### Any other information, logs, or outputs that you want to share?

I believe passing `no_warning_for_no_symbols` to `libtool` (which is `$AR` on the xcode toolchain, as I understand it) will suppress this warning.

**Comment by tetromino** [comment]
For future reference - internal bug is b/113576433

**Comment by jamiesnape** [comment]
Any progress on this? Since #6478 merged, this is the one remaining source of needless spam in the output on Mac.

**Comment by tetromino** [comment]
Fixed by 81b59f05cb0853d27055edf77e62b619ff0aa4ba.

**Comment by cpsauer** [comment]
Looks like some of these are still sneaking through. Posted more in the (still open) https://github.com/bazelbuild/bazel/issues/4057#issuecomment-1103309962

**Comment by keith** [comment]
can you file a new issue with a repro? should be an easy fix

**Comment by cpsauer** [comment]
On it! Thanks, Keith. Amazed at your breadth

**Comment by cpsauer** [comment]
(You're sure you don't want it in the other issue, still open and applicable?)

**Comment by keith** [comment]
either way

**Comment by phst** [comment]
I think this issue has reappeared now that C++ builds on macOS use the Unix toolchain by default (Bazel 7). I guess Bazel should pass the necessary flags for the Unix toolchain as well, at least if the macOS binaries (and not GNU ones installed via e.g. Homebrew) are used for compiling.
