### ISSUE TITLE
Non-standard protobuf should be built from source under the third_party/, or the released version should be used.

### ISSUE THREAD

**Issue by yurivict** [bazelbuild/bazel#599]
I tried to to port bazel to FreeBSD, and got it working.

However, it requires the non-standard version of protobuf: v3.0.0-alpha-3. Latest released version is 2.6.1, that's what FreeBSD has in ports. If bazel requires another version, you should include it into your build under third_party/, and make it build automatically.

linux binaries with .exe extension, that are currently added to the repository, won't do for FreeBSD. We can't use binaries, and we can't rely on linux emulation for the build system.

So please either add the compatible protobuf, or switch to the currently released version. Otherwise this is a deal breaker for FreeBSD port.

**Comment by damienmg** [comment]
While we care a lot on getting Bazel distributed on all accessible system, our bandwidth is currently greatly diminished and we cannot compile a protoc 3 for FreeBSD at the moment (need to setup the machine and co.).

Bazel depends on feature from protobuf 3 and we cannot use protobuf 2.

The instruction to generate the protobuf binary are in third_party/protobuf and we would be happy to accept patch to have more versions of it.

Two side notes:
  - The .exe extension is from the protobuf team as it is how they distribute it Maven Central
  - The current FreeBSD setting is an external contribution that is the reason it is minimalistic.

**Comment by yurivict** [comment]
I think all systems can benefit from this, not only FreeBSD. You don't need to recompile it for FreeBSD. If you depend on non-standard version, you need to include it. Including binaries generally doesn't work.

**Comment by damienmg** [comment]
It would be the same as we need protobuf compiler for the bootstrapping it means that we need to compile it during the bootstrap process that's not a extensive work but not epsilon either. I am not saying we will not do that in the future. I am just saying that we are working on more pressing issues right now.

**Comment by lberki** [comment]
That said, I agree with @yurivict -- in theory, we should include the sources (or pointers to the sources) for everything we depend on. It's just that we haven't had enough time to do so.

**Comment by yurivict** [comment]
I did this in my FreeBSD port. Bootstrapping with the specific protobuf version.

**Comment by helenalt** [comment]
Based on the thread, seems like this issue is resolved. @yurivict please re-open if not, and provide additional context.
