### ISSUE TITLE
The message "Failed to open Bazel as a zip file" should recommend not stripping an executable

### ISSUE THREAD

**Issue by yurivict** [bazelbuild/bazel#600]
I think that bazel executable is expected to not be stripped, otherwise it prints this error message:

```
file is invalid or corrupted (missing end of central directory record)

Failed to open Bazel as a zip file: (5) Input/output error
```

This message should also say something like this: "Is bazel executable stripped? It shouldn't be stripped."
Also "Input/output error" can be omitted, because I/O errors usually refer to the system call failures, which doesn't happen in this case. It only confuses the user.

**Comment by kchodorow** [comment]
The bazel binary is a tiny C++ launcher with a zip file tacked on its butt.  We don't expect people to strip it because 99% of the `bazel` "binary" is actually a Java server that is extracted from the zip file and then persisted between builds.

**Comment by yurivict** [comment]
Yes, but on BSD stripping is a normal practice, and there is a warning when the package has unstripped file.  People will likely sometimes strip it, and then will get confused. So the message should be clear and say the exact cause of the message.

**Comment by ulfjack** [comment]
That error message isn't coming from bazel itself, but from other code which we don't control. We could add a check in bazel itself, but I'm not convinced that's worth the effort. Note that you can easily build a stripped bazel binary by adding some command-line options when building it (which ones depend on how you want to strip it).

**Comment by truatpasteurdotfr** [comment]
I have packeged bazel in a nice rpm without stripping it, but if prelink is installed, it will default strip it on it's daily maintenance duty.. maybe a big fat warning should warn people about it? OTOH, couldn't bazel be offered as the expanded " a Java server that is extracted from the zip file and then persisted between builds" ?

**Comment by mhlopko** [comment]
I don't think we expect any work on our side for this issue, therefore closing.

**Comment by libTorrentUser** [comment]
Was scratching my head today after building bazel and wondering why I was seeing some zip related error messages when I tried to execute it. Turns out I had stripped it. 

Thank you, [yurivict](https://github.com/yurivict). And, yes, some sort of warning somewhere would be very helpful. At the very least the docs should mention this little tidbit so people can bootstrap a working bazel binary.
