### ISSUE TITLE
unhelpful error messages

### ISSUE THREAD

**Issue by alan-agius4** [bazelbuild/bazel#6004]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> Error messages are not always easy to understand especially for first time users.

### Feature requests: what underlying problem are you trying to solve with this feature?

> Better user experience. for instance when having the below which is a wrong import;

```skylark
load("@angular//tools/ts-api-guardian/index.bzl", "ts_api_guardian_test")
```

I was giving this error message 
```
error loading package 'etc/api': Extension file not found. Unable to load package for '@angular//tools/ts-api-guardian/index.bzl:index.bzl': BUILD file not found on package path
```

which to some extent didn't initially point me on the right path to fix the problem

//cc @alexeagle

**Comment by laurentlb** [comment]
@haxorz, any recommendation on how to do that?

**Comment by laurentlb** [comment]
In a load statement, if you use a label that doesn't exist, you get this error message:
`error loading package 'etc/api': Extension file not found. Unable to load package for '@angular//tools/ts-api-guardian/index.bzl:index.bzl': BUILD file not found on package path`

But this doesn't tell you what tries to load the bzl file. A good error message should show the location of the `load` (or one of the loads if there are multiple) that references the invalid label. The error message above only mentions the package, but the error might be in any of the bzl files that are loaded.

**Comment by haxorz** [comment]
to do this (at least for the "one .bzl file tries to load another .bzl file" case), i think it'd suffice to change https://github.com/bazelbuild/bazel/blob/11642e9d12453357987f645649c75984f96a4f45/src/main/java/com/google/devtools/build/lib/skyframe/SkylarkImportLookupFunction.java#L246 to use #getValuesOrThrow, catch the SkylarkImportFailedException exception and augment the error message to include the context of the .bzl file that had the 'load' statement.
