### ISSUE TITLE
Code coverage does not honor "exclusive" tag

### ISSUE THREAD

**Issue by dhalperi** [bazelbuild/bazel#6005]
### Description of the problem / feature request:

I have tests marked as `exclusive`, and when I run `bazel test //...`, they run serially. When I run with code coverage:

```
bazel coverage //... \                                           
--combined_report=lcov \
--coverage_report_generator=@bazel_tools//tools/test/LcovMerger/java/com/google/devtools/lcovmerger:Main \
--experimental_java_coverage && genhtml -o coverage bazel-out/_coverage/_coverage_report.dat && open coverage/index.html
```

they run in parallel.

### Feature requests: what underlying problem are you trying to solve with this feature?

`bazel coverage` should honor `exclusive` tag.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Check out https://github.com/batfish/batfish/ at 7ac4e23ea8f3887a74f2c1a56e744df7750c2217 and run the above command.

### What operating system are you running Bazel on?

Mac OS X 10.13.6 (17G65)

### What's the output of `bazel info release`?

* `development version`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

`bazel build //src:bazel @ commit d0196514e12bf09d9548160604fdae4c40063654`

Need latest features for the code coverage magic.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
git@github.com:bazelbuild/bazel.git
d0196514e12bf09d9548160604fdae4c40063654
d0196514e12bf09d9548160604fdae4c40063654
```

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

No

**Comment by dhalperi** [comment]
cc: @iirina

**Comment by dhalperi** [comment]
Revisiting after #8362 has fixed other blockers. This is still a problem.

**Comment by maxh** [comment]
My team has also encountered this issue. Our workaround is to exclude must-be-run-serially tests from our coverage report, but that artificially reduces our reported coverage. Ideally, we'd be able to generate coverage using all test targets.

>Revisiting after #8362 has fixed other blockers.

It looks like jacoco was upgraded in https://github.com/iirina/bazel/commit/f90cc57c112e3b3b2f0d8c070795222450cab631. Are there any other blockers?

If someone can provide a few pointers as to what a PR to fix would include, I might be able dig into this at some point.

Thanks!

**Comment by BillyAutrey** [comment]
Probably related - I found that even using the `--test_strategy=exclusive` flag in your execution isn't respected.  All tests will run in parallel, even with a top level option to run in exclusive mode.

**Comment by ergleb78** [comment]
Are there any updates on this? It looks like it's still an issue. It causes to use weird combination of bazel and standalone coverage reporting tools.

**Comment by woonhak** [comment]
Hi, I'm experiencing the same issue.
Is there any work-around for this issue?

**Comment by neilisaac** [comment]
As a workaround I've been running coverage tests in two steps:
```bash
bazel coverage --test_tag_filters=-exclusive --build_tests_only //...
bazel coverage --build_tests_only --local_test_jobs=1 //...
```

**Comment by coeuvre** [comment]
cc @c-mita

**Comment by c-mita** [comment]
Just a very quick test seems to indicate that the problematic flag is `--combined_report=lcov`.

```
bazel coverage --test_strategy=exclusive //tests/*
# test run one after the other
bazel coverage --test_strategy=exclusive //tests/* --combined_report=lcov
# test run all together
```

**Comment by thempatel** [comment]
We can confirm that this is indeed a poor interaction with the `--combined_report` flag as @c-mita brings up. Thanks for pushing on this and figuring out the issue!

**Comment by joeleba** [comment]
Have you tried out `--experimental_merged_skyframe_analysis_execution`. This bug should be obsolete once we flip that flag. See [#14057](https://github.com/bazelbuild/bazel/issues/14057).

**Comment by c-mita** [comment]
A quick test suggest that that flag doesn't change anything.

**Comment by joeleba** [comment]
Right, I accidentally left out the `--combined_report` flag. My bad.

**Comment by Travis-Taylor** [comment]
Is this issue actually resolved? It seems like there is no fix linked, maybe the bot just mistakenly closed?

**Comment by dhalperi** [comment]
@Travis-Taylor - the fix is in the linked commit in the last message https://github.com/bazelbuild/bazel/commit/6eb7dbb2f2634a0acaee5dc8c73f0aab710e1256

**Comment by Travis-Taylor** [comment]
> @Travis-Taylor - the fix is in the linked commit in the last message [6eb7dbb](https://github.com/bazelbuild/bazel/commit/6eb7dbb2f2634a0acaee5dc8c73f0aab710e1256) (Now, whether's that's actually a fix I'm not sure).

Got it, thank you! I'm not familiar with that tool, missed the link

**Comment by Ryang20718** [comment]
Will this be cherry-picked into 6.X.X/7.X.X releases?
