### ISSUE TITLE
incorrect documentation for `--config=`

### ISSUE THREAD

**Issue by mpictor** [bazelbuild/bazel#6006]
### Description of the problem

In the [command line reference](https://docs.bazel.build/versions/master/command-line-reference.html)'s description of `--config` it is stated that 

> [...] Note that it is currently only possible to provide these options on the command line, not in the rc files. [...]

This is incorrect, as `--config=` _does_ have an effect when specified in a bazelrc.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a bazelrc with the following (note, assumes you have a `k8` compiler and not a `badcpu` compiler - very very likely to be true).

```bash
build --config works
# instead of --cpu, below lines could use any other arg(s) which will produce differing output.
build:works --cpu=k8
build:borked --cpu=badcpu
```
Locate this bazelrc such that it'll be used by bazel.

Build something trivial with bazel, without specifying `--config` on the command line or in any other bazelrc. It will use the default compiler, k8.

Now, edit the file and change the first line to `build --config borked`. Run bazel, again without any `--config` options. This time, bazel will fail with `No default_toolchain found for cpu 'badcpu'` - proving that the documentation is incorrect and that this option _can_ be used within a bazelrc.

### What operating system are you running Bazel on?

Gentoo Linux amd64

### What's the output of `bazel info release`?

> release 0.16.1

(note, same results with gentoo-built v 0.16.0)

###  Have you found anything relevant by searching the web?

N/A

### Any other information, logs, or outputs that you want to share?

No

**Comment by gregestren** [comment]
Good catch. I'm pushing through a refresh...
