### ISSUE TITLE
Add //examples/... to RBE CI pipeline

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#6007]
See https://github.com/bazelbuild/bazel/issues/5978#issuecomment-416207322

@philwo: 

> From a config perspective, we just have to add it here:
> 
> https://github.com/bazelbuild/bazel/blob/master/.bazelci/presubmit.yml#L120
> https://github.com/bazelbuild/bazel/blob/master/.bazelci/postsubmit.yml#L93

**Comment by laurentlb** [comment]
Should we move examples to https://github.com/bazelbuild/examples?

**Comment by philwo** [comment]
@laurentlb IMHO yes. It's strange that we have two places for examples.

**Comment by jin** [comment]
I also agree. We should consolidate both into the examples repo, and provide a more detailed README for the repo.
