### ISSUE TITLE
Bazel Debian package installation overwrites global /etc/bazel.bazelrc file

### ISSUE THREAD

**Issue by gertvdijk** [bazelbuild/bazel#6020]
### Description of the problem / feature request:

Installing the Debian package of Bazel overwrites the user configuration in `/etc/bazel.bazelrc` blindly.

(This found me puzzling for an hour or so why my builds were failing.)

### Feature requests: what underlying problem are you trying to solve with this feature?

Please consider this a bug. A Debian package should never ever overwrite configuration files blindly. Users can expect their configuration files to not be overwritten by default. (See Lintian error below.)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

    $ echo "foo" > /etc/bazel.bazelrc 
    $ sudo dpkg -i ~/Downloads/bazel_0.16.1-linux-x86_64.deb 
    (Reading database ... 249675 files and directories currently installed.)
    Preparing to unpack .../bazel_0.16.1-linux-x86_64.deb ...
    Unpacking bazel (0.16.1) over (0.16.1) ...
    Setting up bazel (0.16.1) ...
    $ cat /etc/bazel.bazelrc  # empty now
    $ ls -l /etc/bazel.bazelrc
    -rw-r--r-- 1 root root 0 Jan  1  1970 /etc/bazel.bazelrc

### What operating system are you running Bazel on?

Debian/Ubuntu.

### What's the output of `bazel info release`?

    $ bazel info release
    release 0.16.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a - using release build

###  Have you found anything relevant by searching the web?

Lintian confirms this is a packaging error (see below).

### Any other information, logs, or outputs that you want to share?

By running Lintian (Debian package linter), you would have been warned for this:

    $ lintian ~/Downloads/bazel_0.16.1-linux-x86_64.deb
    [...]
    E: bazel: file-in-etc-not-marked-as-conffile etc/bash_completion.d/bazel
    E: bazel: file-in-etc-not-marked-as-conffile etc/bazel.bazelrc
    [...]

This confirms a serious packaging error.

Quoting https://lintian.debian.org/tags/file-in-etc-not-marked-as-conffile.html:
> Files in /etc must be marked conffiles if they are included in a package. Otherwise they should be created by maintainer scripts.
> Refer to Debian Policy Manual section 10.7 (Configuration files) for details.
> Severity: serious, Certainty: certain
> Check: conffiles, Type: binary

**Comment by katre** [comment]
Thank you for the bug report. I'll get a fix out ASAP.

**Comment by gertvdijk** [comment]
Confirmed fixed in [0.17.1rc3](https://releases.bazel.build/0.17.1/rc3/index.html). :tada:
