### ISSUE TITLE
ERROR: Build Event Protocol upload failed: Attempting to send over a closed stream

### ISSUE THREAD

**Issue by ola-rozenfeld** [bazelbuild/bazel#6026]
Happened with the latest nightly Bazel. A test timed out (it was supposed to), and in the end we saw this error:

ERROR: Build Event Protocol upload failed: Attempting to send over a closed stream
INFO: Partial Build Event Protocol results may be available at [redacted]

Two problems here: the failure itself is one; the other: is it the right thing to fail the build when BES upload fails? Shouldn't it be a warning instead? As is, Bazel returned the failure exit code instead of the test timeout code (3).

**Comment by philwo** [comment]
@buchgr Any idea? I guess this might have been fixed in the meantime by your rewrite of the BES uploader?

**Comment by buchgr** [comment]
> is it the right thing to fail the build when BES upload fails?

that's the expected behavior. There used to be a `--bes_best_effort` flag which would convert the error into a warning but that was removed because reasons.

> As is, Bazel returned the failure exit code instead of the test timeout code (3)

The expected behavior is that it returns PUBLISH_ERROR and not test timeout.

Ola, have you seen the error in the recent Bazel nightlies?

**Comment by ola-rozenfeld** [comment]
> Ola, have you seen the error in the recent Bazel nightlies?

Just once the two weeks ago. So you just explained this is expected behavior. Hmm, okay, I guess it has a point. I do wish they left the flag, though.

As to the failure itself, it might have coincided with the beginning of the BES outage (we're not sure, but we suspect). So I'll close this and reopen if it happens again.

Thank you for the clarification, Jakob!

**Comment by pcj** [comment]
FWIW I've observed this error on bazel 0.17.2.  Just upgraded to 19.2 and not seeing it anymore.  Checked  it on 0.18.0 and seems fixed there as well.
