### ISSUE TITLE
'no-cache' fails to exclude the targets from remote cache

### ISSUE THREAD

**Issue by yiming9** [bazelbuild/bazel#6038]
### Description of the problem:

Targets with 'no-cache' tags do not seem to be excluded from the remote cache in bazel 0.15.0.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The following page suggests that we can give a target a 'no-cache' tag to exclude it from remote cache:
https://docs.bazel.build/versions/master/remote-caching.html#exclude-specific-targets-from-using-the-remote-cache

The workspace in the following .zip file is a minimal example, in which there is just one cc_binary with one .cc file.
[bazel.zip](https://github.com/bazelbuild/bazel/files/2336820/bazel.zip)

The cc_binary looks like:
```
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    tags = ["no-cache"],
)
```

The bazelrc looks like:
```
build --remote_http_cache=http://localhost/cache
build --remote_local_fallback
build --remote_max_connections=100
```

1. Completely clear the cache directory pointed by http://localhost/cache/ in nginx.
2. Run `bazel build -c opt :main`
3. We can find that some files are written into the cache directory, which suggests that though 'main' has 'no-cache' tag, it causes something to be written into the remote cache.
4. Run `bazel build -c opt :main`. It shows:
```
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //:main (7 packages loaded).
INFO: Found 1 target...
Target //:main up-to-date:
  bazel-bin/main
INFO: Elapsed time: 0.446s, Critical Path: 0.01s
INFO: 2 processes: 2 remote cache hit.
INFO: Build completed successfully, 6 total actions
```
It shows that though `main` has 'no-cache' tag, it uses the remote cache.

### What operating system are you running Bazel on?

Ubuntu 16.04.5 LTS

### What's the output of `bazel info release`?

release 0.15.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

This minimal example is not in a git repo.

###  Have you found anything relevant by searching the web?

No.

**Comment by benjaminp** [comment]
I think this is probably the same as #4680?

**Comment by jin** [comment]
cc @buchgr

**Comment by buchgr** [comment]
I investigated this a while back and found the following:
1) The `no-cache` tag doesn't work for at least Java and C++ rules, in that the actions of these rules just don't pass it through.
2) It's implemented for tests independent of the language.
3) It works for all rules written in skylark.

Fixing this issue is not difficult but lots of work to find all the places in the code where the no-cache tag needs to be passed through

**Comment by gergelyfabian** [comment]
Do I understand correctly that this is related to the flag --experimental_allow_tags_propagation (https://github.com/bazelbuild/bazel/issues/8830), and that turning that flag on (if that works for my build) should solve this issue (as a workaround at least)?
Continuing, once allow_tags_propagation will be a stable feature it will be solution to this problem?

**Comment by sjoerdvisscher** [comment]
Note that you should set `common --experimental_allow_tags_propagation` and not `build --experimental_allow_tags_propagation`, since that will cause refetching of external dependencies if you f.e. switch between `bazel query` and `bazel build`. (because of different values of STARLARK_SEMANTICS in the marker files)

**Comment by Warchant** [comment]
Adding 
```
common --experimental_allow_tags_propagation
```

to .bazelrc solved problem of `no-*` propagation.

**Comment by coeuvre** [comment]
As mentioned above, `--experimental_allow_tags_propagation` can be used as a workaround. Closing.
