### ISSUE TITLE
aapt2 fails with certain resource filenames

### ISSUE THREAD

**Issue by sunyal** [bazelbuild/bazel#6042]
### Description of the problem / feature request:

It seems that when a resource file contains more than one period in the name it fails the build using the --android_aapt=aapt2 flag. This doesn't happen with the default aapt processor.  For example the resource file is called `Style.Cell.xml` and seems to have difficulty processing because it appears to truncate the name into the following `values_Style.arsc.flat`, dropping the `Cell`.

### Feature requests: what underlying problem are you trying to solve with this feature?

Have consistency with aapt2 for Bazel and Gradle builds.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Check out the repo and branch

`git clone -b aapt2_issue git@github.com:skoeld/examples.git`

Using the latest Bazel master execute the following command

`cd examples/tutorial`

`bazel build //android --android_aapt=aapt2` 

It should fail with the following error message

`INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //android:android (0 packages loaded).
INFO: Found 1 target...
ERROR: /Users/abeggs/Downloads/examples/tutorial/android/BUILD:17:1: Compiling Android resources for //android:activities failed (Exit 1)
Aug 30, 2018 3:27:28 PM java.util.stream.ForEachOps$ForEachOp$OfRef accept
SEVERE: /var/folders/mg/hqqxcmvj7sn0_jpl67_45hxw0000gp/T/android_resources_tmp17152668280556184528/compiled/default/android/src/main/java/com/google/bazel/example/android/activities/res/values_Style.arsc.flat does not exists after aapt2 ran.
Target //android:android failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.962s, Critical Path: 0.68s
INFO: 0 processes.
FAILED: Build did NOT complete successfully`

### What operating system are you running Bazel on?

Mac OSX v10.13.6

### What's the output of `bazel info release`?

We do a master build nightly

Build time: Wed Aug 29 21:06:22 2018 (1535576782)
Build timestamp: 1535576782
Build timestamp as int: 1535576782

**Comment by jin** [comment]
@sunyal do you know if this works with aapt2 and Gradle/AGP?

**Comment by jin** [comment]
@sunyal aapt supports compiling filenames with multiple periods in the filename, but not aapt2:

```
$ ~/sdk/build-tools/28.0.1/aapt2 compile -v -o $(pwd) android/src/main/java/com/google/bazel/example/android/activities/res/values/Style.Cell.xml
error: resource file 'android/src/main/java/com/google/bazel/example/android/activities/res/values/Style.Cell.xml' name cannot contain '.' other than forspecifying the extension.
```

Bazel currently invokes aapt2 with `--legacy` support, which is why we're seeing a "file not found" message instead of the above compilation failure. I'll work on making the error message better.

**Comment by dakshj** [comment]
Why does `aapt2` not support file names with multiple periods though?
