### ISSUE TITLE
Cross compilation: build multiples toolchains at once.

### ISSUE THREAD

**Issue by guibou** [bazelbuild/bazel#6044]
### Description of the problem / feature request:

I have multiples toolchains and I'm now using a wrapper script to build everything using all available toolchains. For example, one of my wrapper scripts contains:

```
bazel build --cpu x86_64 --compiler gcc //...
bazel build --cpu x86_64 --compiler clang //...
bazel build --cpu arm32 --compiler gcc //...
```

I'd like bazel to be able to build everything at once, for example by typing `bazel build --cpu ALL --compiler ALL`.

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm trying to simplify my workflow which contains a lot of wrapper scripts on top of bazel.

**Comment by gregestren** [comment]
Guillaume,

Take a look at the [configurability roadmap](https://bazel.build/roadmaps/configuration.html), which will ultimately lead down this path. The roadmap item "Flagless multiplatform builds" is probably closest to what you want. 

You can also check out [`--experimental_multi_cpu`](https://docs.bazel.build/versions/master/command-line-reference.html#flag--experimental_multi_cpu), which approximates some of what you're proposing, at least with the CPU flag. 

To be clear, you want to build the *same target* multiple times at once with different toolchains?

**Comment by gregestren** [comment]
Marked as P3 because we're going to have to get farther down the [configurability roadmap](https://bazel.build/roadmaps/configuration.html) before we can principally tackle / up-prioritize this.

**Comment by guibou** [comment]
> To be clear, you want to build the same target multiple times at once with different toolchains?

Or build some targets with a toolchain and somes with a another toolchain at once.

Thank you for your answer, I'm looking forward for an implementation of the relevant items from the roadmap.

**Comment by gregestren** [comment]
Ah, okay, thanks for clarifying. I suspect we'll see the latter (target A with toolchain A'  and target B with toolchain B') happen sooner. That's explicitly on the roadmap.

The former (building target A with both toolchains A' and B' in the same build) will be more complicated simply because it requires more subtle UI design.

Also note the roadmap's current ETAs need a refresh. We're reviewing and planning to update them next week (in conjunction with [BazelCon](https://conf.bazel.build/)).

**Comment by koniarik** [comment]
Hi o/

is there any update on the abillity to build target A with toolchain A' and target B with toolchain B'?

**Comment by fmeum** [comment]
@koniarik You can realize this by wrapping A and B with transitions on `--platforms` if you include a distinguishing `constraint_setting` in your toolchains. Applying transitions requires some boilerplate though. [platform_transition_filegroup](https://github.com/aspect-build/bazel-lib/blob/main/docs/transitions.md#platform_transition_filegroup) and [rules_meta](https://github.com/fmeum/rules_meta/blob/main/tests/use_meta.bzl) may help with that.

**Comment by aiuto** [comment]
As @fmeum points out, all the mechanisms needed for this are available now.
