### ISSUE TITLE
Cross compilation: forcing toolchain of a rule passed as argument to a binary

### ISSUE THREAD

**Issue by guibou** [bazelbuild/bazel#6045]
### Description of the problem / feature request:

I'm using bazel to build / deploy firmware on embedded devices. The deploying program is built using bazel and need to run on the "host" architecture. The deployed binary is built using bazel using the "target" architecture.

I'd like to use `bazel run //:deploy` and uses the `args` attribute of the `_binary` rule `deploy` to specify the firmware. This way, `bazel run` will be responsible to:

- Build my deploying tool using the host toolchain
- Build my firmware using the target toolchain
- Calling the deploying tool with the corrects arguments.

I don't know how to do that with bazel. For now I'm using a wrapper makefile. I'd like something like:

```python
xxx_binary(
   name = "deploy",
   args = ["$(location :firmware)"] # Here I want to tell than firmware will be built with a specific toolchain.
   ...
)
```

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm trying to remove all my wrapper makefile, which are working but inconvenient.

### What's the output of `bazel info release`?

I'm using a bazel 0.15 with some patchs cherry-picked from bazel 0.17rc. I'm not aware of any new feature in bazel 0.16 and 0.17rc relevant to this discussion.

**Comment by katre** [comment]
This is definitely something that we would like Bazel to be able to handle. Unfortunately we are not there yet. There are a few features on the [Configurability roadmap](https://bazel.build/roadmaps/configuration.html) that are going to be needed first. The main one is "Flagless multiplatform builds". This will allow you to write a `platform` target describing where the tool will be used, and then use that with the `platforms` attribute on your `xxx_binary` target to specify how it should be built. At that point, the build would look like this:

1. You execute `bazel run :deploy`
2. Bazel builds the deployment utility, for the default target platform, which is the same platform you are running on (ie, the host platform)
3. The deployment utility depends on the actual binary (or multiple binaries), which have the `platforms` attribute set. This causes a transition into a new configuration building the binary for that target platform.
4. The binary that was build is available to your deployment utility, and it can perform whatever actions are needed to actually deploy it.

We are looking at a lot of work still before we can enable multi-platform builds like this. There are a lot of underlying technical details still to be worked out. Thank you for your patience.

**Comment by jin** [comment]
@katre could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?
