### ISSUE TITLE
RLocation is broken in Windows and Linux

### ISSUE THREAD

**Issue by ale64bit** [bazelbuild/bazel#6048]
### Description of the problem / feature request:

While trying to use RLocation, it fails both in Windows and Linux:

(1) Windows
It simply reports that the path doesn't exist. Basically the path contains a folder that contains a manifest files with references to the actual files, but this folder doesn't seem to get expanded in the returned path for some reason.

(2) Linux
The result seems to be missing a `__main__` element in the path. For example, the path reported by `Runfiles::Rlocation()` is:

`/home/USER/.cache/bazel/_bazel_USER/114d5b98ba9a157c345b52dd92198de1/execroot/__main__/bazel-out/k8-fastbuild/bin/examples/test_app.runfiles/assets/model/sponza.glb`

while the actual path is:

`/home/USER/.cache/bazel/_bazel_USER/114d5b98ba9a157c345b52dd92198de1/execroot/__main__/bazel-out/k8-fastbuild/bin/examples/test_app.runfiles/__main__/assets/model/sponza.glb`

### Feature requests: what underlying problem are you trying to solve with this feature?

Use data files cross-platform.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Just following the example in the header comment [here](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/runfiles/runfiles_src.h).

### What operating system are you running Bazel on?

Windows 7 (not sure if matters but locale is RU)
Ubuntu 18.04.1 LTS

### What's the output of `bazel info release`?

Windows:
```
release 0.16.0
```
Linux:
```
release 0.16.1
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a

###  Have you found anything relevant by searching the web?

This seems to be what I'm seeing in Windows:
https://github.com/bazelbuild/bazel/issues/5926
https://github.com/bazelbuild/bazel/issues/5724

### Any other information, logs, or outputs that you want to share?

n/a

**Comment by jin** [comment]
cc @laszlocsomor

**Comment by laszlocsomor** [comment]
@ale64bit : Could you show us a simple example project to repro this issue? Your report suggests you're running a C++ binary from a Python binary, but a concrete example to repro the problem would help us help you. It could indeed be important that your Windows uses RU locale, thanks for mentioning that.

**Comment by ale64bit** [comment]
https://github.com/ale64bit/repro6048

### Windows

When running `bazel run app:main` I get:
```
path: C:\users\kaktus_bazel_kaktus\izgt2smd\execroot__main__\bazel-out\x64_windows-fastbuild\bin\app\main.exe.runfiles/data/test.txt
file not found
```
The file can be actually found at:
```
$ cat /c/Users/Kaktus/_bazel_Kaktus/izgt2smd/execroot/main/data/test.txt
my hovercraft is full of eels
```

Other details:

- project is stored at `D:\Work\Repos\repro6048`.
- running from MSYS2.

### Ubuntu

When running `bazel run app:main` I get:
```
path: /home/ale64bit/.cache/bazel/_bazel_ale64bit/832ebe80b8e27eeb36d88584088a4e10/execroot/__main__/bazel-out/k8-fastbuild/bin/app/main.runfiles/data/test.txt
file not found
```
The file can be actually found at:
```
$ cat /home/ale64bit/.cache/bazel/_bazel_ale64bit/832ebe80b8e27eeb36d88584088a4e10/execroot/__main__/bazel-out/k8-fastbuild/bin/app/main.runfiles/__main__/data/test.txt
my hovercraft is full of eels
```

**Comment by ale64bit** [comment]
Yep, that fixes it in Windows and Ubuntu :) thanks for the help and feel free to close.

Where can I find documentation about the right usage of `Rlocation` and about the `workspace` rule?

**Comment by laszlocsomor** [comment]
Hey @ale64bit , sorry for the terribly late reply. There's no documentation about the runfiles libraries, other than the code comments in https://github.com/bazelbuild/bazel/blob/master/tools/cpp/runfiles/runfiles_src.h.

I'll add this to my list of TODOs, I'll get to it eventually.

**Comment by laszlocsomor** [comment]
Hm... actually, it makes more sense to open a new bug. See https://github.com/bazelbuild/bazel/issues/6402
