### ISSUE TITLE
bazel server restarts when JAVA_HOME changes

### ISSUE THREAD

**Issue by brown** [bazelbuild/bazel#6050]
### Description of the problem / feature request:

The Bazel server restarts whenever the file path to the local JDK changes.  Instead, the server should only be restarted when the local JDK is different.  The code should checksum the local JDK instead of assuming it's different when its file path is different.

### Feature requests: what underlying problem are you trying to solve with this feature?

I run Bazel in an environment where the path to the local JDK can change from run to run.  The JDK at these different paths is identical, it's just the file path that changes.  Unfortunately, Bazel restarts the server whenever it believes the local JDK is different and it uses file path of javac as a conservative indication of a change.  Instead, Bazel should checksum the JDK and only restart the server if it is really different.

In my case Bazel is using JAVA_HOME to find the file path of javac,  It's the javac path change that Bazel uses to determine that the local JDK is different.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Copy your local JDK to a second location.  Start Bazel with JAVA_HOME pointing at your local JDK.  Change JAVA_HOME to point at the copy you made of your JDK.  Run Bazel again.  You should see the Bazel server restart.

### What operating system are you running Bazel on?

Linux.

### What's the output of `bazel info release`?

0.15.0

**Comment by petroseskinder** [comment]
@jin, @cushon any thoughts on restarting the server by performing a checksum on the local jdk?

**Comment by lberki** [comment]
This not relevant anymore: since we don't use the local JDK for running Bazel itself (we carry our own JDK around for that) and thus server restarts don't happen when `JAVA_HOME` changes.
