### ISSUE TITLE
Documentation should note when options are renamed

### ISSUE THREAD

**Issue by mpictor** [bazelbuild/bazel#6051]
### Description of the problem / feature request:

I find it handier to view the documentation on docs.bazel.build than to look at, for example, `bazel help startup_options`. However, the documentation doesn't show when options were added/renamed, and it doesn't seem to be possible to view docs for any version but HEAD (replacing `master` in the url with something like `0.16.1` gives me a 404).

### Feature requests: what underlying problem are you trying to solve with this feature?

Confusion when options are added/renamed in master but not in the version the user is using. In my case, this was encountered with `--nosystem_rc` (the name in the documentation on docs.bazel.build). With v 0.16.1, `bazel help startup_options` indicates the desired option is `--nomaster_bazelrc`, while v 0.16 calls it `--nomaster_blazerc`.

I would've had an easier time finding the correct option name, if any of the following were true: 
1. if the documentation showed previous names
2. if the documentation was for the latest _release_ rather than tracking HEAD
    * I'm a little surprised the website tracks head, given that users are encouraged to use an official build rather than building it themselves - let alone building a non-release like HEAD!
3. if it was possible to view documentation for a specific version on docs.bazel.build

My preference for fixing this would be a combination of points 1 and 3 - newer documentation should show the version at which something changed, and older documentation should remain available and easily locatable.

An example of how another project documents such changes can be seen in [ansible's lineinfile documentation](https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html#lineinfile-module) with the path parameter:

> Before 2.3 this option was only usable as dest, destfile and name.
> aliases: dest, destfile, name

Also note that there's a link to a documentation archive in the upper left of that page.

I'm not sure if they have some automated mechanism that documents these changes or if it must be maintained manually; automation would certainly make it more palatable.

----

As a side note, it seems like a bad idea to rename any option frequently, let alone allowing master and the previous two releases to _each_ have their own name for it. IMO this is a signal that more care should have been taken in choosing a name - the first two times ;)

### What operating system are you running Bazel on?

Gentoo

### What's the output of `bazel info release`?

`release 0.16.1`

###  Have you found anything relevant by searching the web?

No

**Comment by jin** [comment]
cc @spomorski

**Comment by dslomov** [comment]
We now have versioned documentation.
