### ISSUE TITLE
Passing the same optimization flag twice causes a rebuild

### ISSUE THREAD

**Issue by galshulkind** [bazelbuild/bazel#6058]
### Description of the problem / feature request:
Passing the same optimization flag twice will trigger a rebuild.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

bazel build //... --copt=-O3
and then
bazel build //... --copt=-O3 --copt=-O3
will cause a rebuild.

**Comment by benjaminp** [comment]
Bazel simply passes all the `--copt` flags straight through the compiler. From Bazel's perspective `--copt=-O3` produces a different command line than `--copt=-O3 --copt=--O3`, so a rebuild is required. To do any better, you would have to teach Bazel about the semantic interpretation of compiler flags. That seems like a bad idea.

**Comment by galshulkind** [comment]
Thanks @benjaminp for the explanation.
