### ISSUE TITLE
Update Protobuf to 3.6.1

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#6061]
### Description of the problem / feature request:

Please update Bazel's Protocol Buffer version to 3.6.1

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

This is breaking Bazel at HEAD when built with Visual C++ 2017 on Windows.

See https://github.com/bazelbuild/bazel/issues/6053#issuecomment-418031872.

### What operating system are you running Bazel on?

Windows 10

/cc @meteorcloudy @jin

**Comment by buchgr** [comment]
Why am I assigned to this @laszlocsomor?

**Comment by laszlocsomor** [comment]
IIRC you updated Protobuf in the past. If so, you have domain expertise. Am I confusing it with gRPC though?

**Comment by buchgr** [comment]
I have, so have other people. I currently have multiple P1s I am working on and don't have time to update protobuf anytime soon. There's a detailed description on how to update protobuf here: https://github.com/bazelbuild/bazel/tree/master/third_party/protobuf

**Comment by laszlocsomor** [comment]
Thanks for the info. Let me take a look.

**Comment by laurentlb** [comment]
If there's a cherrypick request, please add it to the release thread (https://github.com/bazelbuild/bazel/issues/5059).
