### ISSUE TITLE
Bootstrap test with --all_incompatible_changes

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#6062]
We need a test to ensure that Bazel can bootstrap itself using `--all_incompatible_changes`.

**Comment by katre** [comment]
I agree this is a useful test, but I'm not sure why Configurability team should pick it up. Can you clarify who should be handling this?

**Comment by meisterT** [comment]
`--all_incompatible_changes` might be a bit too much. But it should build with all migration ready incompatible changes. Aren't we doing that on CI already?

**Comment by aiuto** [comment]
I'm not a fan of --all_incompatible_changes at all and think we need a different release test process. So this is not a P1 to me, but since @philwo self assigned at that priority I will not change it now.

**Comment by philwo** [comment]
I think when we initially filed this, we had a different understanding of how useful `--all_incompatible_changes` would be. For example, it's not aware of migration ready flags, so it will also enable flags that are known to be still problematic.

Let's close this - we have better tooling these days with Yun's Bazelisk-powered flag testing pipeline :)
