### ISSUE TITLE
Running java_test against the host JDK.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/bazel#6067]
The Kotlin builder has tests that need to be run against the embedded host JDK. They are currently executing against jdk8 and this is making it quite hard to debug issues.

It's not clear to me how I could do with `java_test`. I have tried the following:

```
    native.java_test(name = name,
                     toolchains=["@bazel_tools//tools/jdk:current_java_toolchain"],
                     **kwargs)
```

**Comment by hsyed** [comment]
@cushon Is there a way to get the `java_test` rule to use the embedded JDK as the `java_base` ?

**Comment by cushon** [comment]
cc @lberki 

You could pass `--javabase=@embedded_jdk//:jdk`. There isn't an attribute on `java_test` that allows you to override the Java runtime from the `--javabase` for that individual target.

Another option is just to install a JDK that matches the embedded JDK version (currently `9.0.7.1+1`) and test against that.

Also note that testing host tools that will run using the embedded JDK as the default `--host_javabase` is pretty much the only time `--javabase=@embedded_jdk//:jdk` is a good idea. In general, the embedded JDK is not a good choice of target `--javabase` (see #6105).

**Comment by cushon** [comment]
@hsyed did you have a chance to try out any of the options I mentioned?

**Comment by hsyed** [comment]
Not in anger. I’ll test it properly over the next week.

**Comment by lberki** [comment]
The embedded host JDK is now disallowed for everything except running Bazel itself (and we are in the process of removing more and more modules so it'll become less and less useful anyway). So closing this as obsolete.
