### ISSUE TITLE
Stop loading packages in CppConfiguration

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/bazel#6072]
Tracking the effort to finally remove package loading from CppConfigurationLoader and CppConfiguration.

**Comment by ob** [comment]
Is this going to help `objc_library` loading so many more dependencies than `cc_library`?

**Comment by mhlopko** [comment]
Nope, it will only help with not loading C++ toolchain in the loading phase, only in the analysis phase (which is a prerequisite for migrating C++ rules to platforms). I'm not sure I know which issue are you referring to?

**Comment by mhlopko** [comment]
I failed to add the issue number to some of my late commits. Here they come:

* https://github.com/bazelbuild/bazel/commit/ff7b8783e451b9be9e214072019b5e81398aacb6
* https://github.com/bazelbuild/bazel/commit/d37e18e03b120bd9b15bd8843e46b36294aa7649
* https://github.com/bazelbuild/bazel/commit/734934d2c4e8e8343a72c73aba9eb7150d333dbe
* https://github.com/bazelbuild/bazel/commit/123f3abe9155c59fd6327d9431896fe577f2a217
* https://github.com/bazelbuild/bazel/commit/d37e18e03b120bd9b15bd8843e46b36294aa7649
* https://github.com/bazelbuild/bazel/commit/2beb781380b5218c87644f8b1205972c4388158a
* https://github.com/bazelbuild/bazel/commit/8fbe252afdf8ee15cd0a9bffb447867f39783ea3
* https://github.com/bazelbuild/bazel/commit/85ebae3e25fc2eb9a371b323160699b5c0d1f553
* https://github.com/bazelbuild/bazel/commit/ed1c01f8884baf6483d526cc348043bd3696e926
* https://github.com/bazelbuild/bazel/commit/3aa807910cf31428ae40a99567682b09b94e5acc
* https://github.com/bazelbuild/bazel/commit/37dc72689f830c28114eba41c744f591268f7a79
* https://github.com/bazelbuild/bazel/commit/52b32622ca89fd390cfc502d3ff8d9fe55bbc228

**Comment by mhlopko** [comment]
And with this I declare the issue fixed.
