### ISSUE TITLE
Build of root workspace with external name fails because Bazel walks into /bazel-*

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/bazel#6076]
### Description of the problem / feature request:

Build of root workspace with external name fails because Bazel walks into `/bazel-*`.

```
ERROR: error loading package '@bazel_walk_error//bazel-bazel_walk_error/external/bazel_tools/src/main/protobuf': Extension file not found. Unable to load package for '@bazel_walk_error//tools/build_rules:genproto.bzl': BUILD file not found on package path
INFO: Elapsed time: 0,094s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
    currently loading: @bazel_walk_error//bazel-bazel_walk_error/external/baze\
l_tools/src/main/cpp/util ... (3 packages)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- Clone `https://github.com/Yannic/bazel_walk_error.git` and `cd` into workspace.
- run `bazel build //... @bazel_walk_error//...` and wait until build finishes.
- run `bazel build //...` and see that there is no error.
- run `bazel build @bazel_walk_error//...`

### What operating system are you running Bazel on?

macOS 10.13.6 (17G65)

```
Build label: 0.16.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 13 13:42:50 2018 (1534167770)
Build timestamp: 1534167770
Build timestamp as int: 1534167770
```

Reproduced on all platforms.
https://buildkite.com/bazel/rules-go-golang/builds/626

**Comment by irengrig** [comment]
Related issue: #6350

**Comment by meisterT** [comment]
cc @lberki
