### ISSUE TITLE
windows sh_test args with quotes broken

### ISSUE THREAD

**Issue by ahippler** [bazelbuild/bazel#6084]
### Description of the problem / feature request:

test.sh:
```
echo "args: " $(printf "'%s' " "${@}" )
```

BUILD.bazel:
```
sh_test(
    name = "test",
    srcs = [
        "test.sh",
    ],
    args = [
        "foo 'foo bar' bar", # or: "foo \"foo bar\" bar"
    ],
)
```

prints different output on unix and windows.

windows: `args: 'foo' 'foo' 'bar' 'foo'`
unix. `args: 'foo' 'foo bar' 'bar'`
### Feature requests: what underlying problem are you trying to solve with this feature?

the quotes are ignored on windows

**Comment by irengrig** [comment]
Hi @ahippler, looks like single quotes are not used in Windows shell except for some commands:
https://stackoverflow.com/questions/24173825/what-does-single-quote-do-in-windows-batch-files

So this looks unrelated to Bazel.

**Comment by irengrig** [comment]
Thanks for the explanation. 
I think that you should use the Starlark list of strings for separation of the parameters (https://docs.bazel.build/versions/master/be/common-definitions.html#test.args), but on the Bazel side yes, the value should be quoted. Seems also that %* is correct value for Windows case: https://ss64.com/nt/syntax-args.html

**Comment by laszlocsomor** [comment]
https://github.com/bazelbuild/bazel/pull/6083 fixes this issue.
