### ISSUE TITLE
ijar fails to extract Bazel installation due to its size.

### ISSUE THREAD

**Issue by ivant** [bazelbuild/bazel#609]
At current head (f97a44798510160dcba7dbf600e2199ac1a4b145), I get the following error message after I build Bazel and try to use it:

    Extracting Bazel installation...
    Failed to extract Bazel as a zip file: ijar does not support decompressing files larger than 128MB.

A possible fix is the increase of the constant `MAX_BUFFER_SIZE` in `third_party/ijar/zip.cc`.

**Comment by ivant** [comment]
Can confirm that increasing the constant to 256MB fixes the problem. Probably an increase to a smaller value would also fix it.

**Comment by damienmg** [comment]
But the bazel binary shouldn't be that big... Anyway increasing the constant to 256MB is a good enough solution.

**Comment by ulfjack** [comment]
That's probably because we're bundling a lot of the tools...
