### ISSUE TITLE
Errors loading package don't specify the problematic file

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#6090]
### Description of the problem / feature request:

Source:
https://github.com/endobson/examples/tree/bazel-package-error

```
endobson@yggdrasil () ~/tmp/bazel-package-error % bazel build //user:all
ERROR: Skipping '//user:all': while parsing '//user:all': error loading package 'user': Extension file not found. Unable to load file '//pack:bar.bzl': file doesn't exist or isn't a file
WARNING: Target pattern parsing failed.
INFO: Analysed 0 targets (0 packages loaded).
INFO: Found 0 targets...
ERROR: command succeeded, but there were errors parsing the target pattern
INFO: Elapsed time: 0.129s, Critical Path: 0.00s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

A broken load statement doesn't include the location of the load statement other than the package that initiated the load. Because a package can load a `.bzl` file and that can transitively load more, it is not very clear where the broken load statement is. I think that the error message should be extended to include the file that is directly doing the load.

### Feature requests: what underlying problem are you trying to solve with this feature?

Reduce time to fix broken code. In the case that caused this issue for me I was intentionally deleting the file and trying to find all imports and clean them up, so I hadn't recently changed the load statement which would be the case if I had been adding it and mistyped it.

### What operating system are you running Bazel on?
macOS

### What's the output of `bazel info release`?

Build label: 0.16.1- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.
from the released source

**Comment by laurentlb** [comment]
Duplicate with https://github.com/bazelbuild/bazel/issues/4100
