### ISSUE TITLE
Rollback to JDK 9 breaks tests relying on `java.log`

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#6098]
In particular, `test_cache_computed_file_digests_behavior` and `test_log_file_uses_single_line_formatter`.

Disabling these for now. It seems to be a fallout of the revamp of the server logging infrastructure.

**Comment by laszlocsomor** [comment]
Apparently bazel built off HEAD does not write `$(bazel info output_base)/java.log` on Windows. I'm debugging now why.

**Comment by laszlocsomor** [comment]
repro branch: https://github.com/laszlocsomor/bazel/tree/lukacs-experimental and https://github.com/laszlocsomor/bazel/commit/102b615b4eeb7a7d51f26c6f6e0442482a4f1c0e

**Comment by philwo** [comment]
Ah - interesting. Sorry about the wrong link to #6064! This indeed looks like a different issue.

**Comment by laszlocsomor** [comment]
Related: https://github.com/bazelbuild/bazel/issues/6099
