### ISSUE TITLE
Windows, Bazel 0.17.0rc2, regression: bazel no longer writes java.log

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#6099]
### Description of the problem / feature request:

0.17.0 rc2 regression over rc1: Bazel on Windows no longer writes `<output_base>/java.log`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build anything with 0.17.0 rc1, then run `bazel info output_base`, list the reported directory, see `java.log` is there.
Do the same with rc2, see that `java.log` is not there.

### What operating system are you running Bazel on?

Windows 10 v1709

**Comment by laszlocsomor** [comment]
I found the root cause: similarly to https://github.com/bazelbuild/bazel/issues/2576, it's the java log path. Turns out we must pass the path with escaped backslashes instead of forward slashes. Working on a fix.

**Comment by lberki** [comment]
How come it worked in 0.17rc1 then?
