### ISSUE TITLE
0.17.1rc3 fails the test 18.04 (no JDK)

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#6101]
Test of Bazel 0.17.1rc3: 
https://buildkite.com/bazel/bazel-bazel/builds/4403#03954ad5-9c7e-4155-a644-839f8566853f

cc @lberki 

```
** test_bootstrap **************************************************************
readlink: missing operand
Try 'readlink --help' for more information.
Building Bazel from scratch
ERROR: JDK not found, please set $JAVA_HOME.
-- Test log: -----------------------------------------------------------
```

**Comment by cushon** [comment]
> 18.04 (no JDK)
> ...
> JDK not found, please set $JAVA_HOME.

Do we support bootstrapping Bazel without a JDK?

I guess we could use the embedded one, either by downloading it or including it in `bazel-dist.zip`.

**Comment by philwo** [comment]
AFAIK we don't support that and I would be really surprised if someone expected that to work, but I agree that we could make it work by downloading a suitable OpenJDK automatically. (I wouldn't want to distribute it in bazel-dist.zip, because including one for each platform would blow up the size of that file a lot.)

Regarding the other two failing tests in bazel_java_test, I'm not sure. Would be great if you could have a look:
https://storage.googleapis.com/bazel-buildkite-artifacts/6c52ce02-9e9c-4851-9da6-ba59cbc2d5f7/src/test/shell/bazel/bazel_java_test/attempt_1.log

**Comment by philwo** [comment]
"Failed to jar tf bazel-bin/g/libtest.jar" - maybe it's just trying to run "jar" from a wrong location in these two test cases?

**Comment by cushon** [comment]
Is there a good way to reproduce these failures locally? I guess I can hack up my `PATH` to not include `javac` and unset `JAVA_HOME`?

**Comment by philwo** [comment]
@cushon Yes, that should work. Otherwise you could also spawn a simple Ubuntu VM on GCE and try it out there. I'll give you access to our project.

**Comment by philwo** [comment]
You should have access to the DI-Cloud-Exp project on https://console.cloud.google.com/ now - feel free to create VMs for testing there if you can't easily repro it on your local machine.

**Comment by cushon** [comment]
Is there documentation on reproducing CI failures?

I didn't have any luck locally:

```
(
set -eux
unset JAVA_HOME
which javac || echo "no javac"
bazel test //src/test/shell/bazel:bazel_java_test
)
```

```
+ unset JAVA_HOME
+ which javac
+ echo 'no javac'
no javac
+ bazel test //src/test/shell/bazel:bazel_java_test
...
Executed 1 out of 1 test: 1 test passes.
```

**Comment by philwo** [comment]
There's no specific documentation, but the CI systems aren't really special - they're just a standard Ubuntu system with the packages required by Bazel installed.

Can you try running "bazel clean --expunge" before your "bazel test", just to make sure?

I was able to repro this on my Mac at home by deleting my local JDKs from `/Library/Java/JavaVirtualMachines` and then running:

```
bazel clean --expunge
bazel test --nocache_test_results --test_arg=test_java_common_compile_sourcepath //src/test/shell/bazel:bazel_java_test
```

I'll also try with a JDK installed and then unsetting JAVA_HOME to see if it still happens.

**Comment by philwo** [comment]
I think the Bazel running inside the integration test somehow gets a valid JAVA_HOME even when you unset it outside. For example, on macOS it calls `/usr/libexec/java_home` in that case and finds the path.

However, I was able to repro it like this:

bazel test --nocache_test_results --test_arg=test_java_common_compile_sourcepath --test_env=JAVA_HOME=/dev/null //src/test/shell/bazel:bazel_java_test

**Comment by cushon** [comment]
Was this fixed? I thought we just suppressed the test. I was never able to reproduce these failures locally.

I don't think it's a P0, but it'd be nice to understand what happened.

**Comment by jin** [comment]
Down-prioritizing to P2.

**Comment by meisterT** [comment]
Is that still an issue?
