### ISSUE TITLE
Modify SkylarkAnnotationContractTest to verify return types and parameter types

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#6102]
`SkylarkAnnotationContractTest` uses the full java reflection API to verify contracts of all `@SkylarkCallable` methods in bazel. One such contract is verification that return types and parameter types of such methods are legitimate and match the annotation. The test should verify this.

**Comment by jin** [comment]
could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?
