### ISSUE TITLE
never use @embedded_jdk for --javabase

### ISSUE THREAD

**Issue by cushon** [bazelbuild/bazel#6105]
`--javabase` currently defaults to `@embedded_jdk` if we can't find a local JDK (by looking at `JAVA_HOME` and `which javac`):

https://github.com/bazelbuild/bazel/blob/2000cfd764cf2b3b0ec5474a5aeed20c6638c9e6/src/main/java/com/google/devtools/build/lib/packages/WorkspaceFactory.java#L601

As discussed [here](https://groups.google.com/d/topic/bazel-sig-jvm/wA9f-B6Tl5w/discussion) this is a mistake. The embedded JDK is intended to be used as a `--server_javabase` and (for the time being) a `--host_javabse`, but when doing Java development and targeting a particular JDK version we should expect there to be a local JDK install instead of falling back to the embedded JDK.

This issue contributed to the breakages in 0.16x, because users had been relying on the embedded JDK as a `--javabase` when developing code that wasn't compatible with JDK 9, and were broken when the embedded JDK version was upgraded to JDK 9.

**Comment by cushon** [comment]
We should try to fix this in 0.18: #5963

**Comment by lberki** [comment]
Is there an urgency? Sure, we should fix this ASAP, but does it do harm if the change ends up in 0.19 instead?

**Comment by cushon** [comment]
It's a blocker for upgrading the embedded JDK version, and we need a newer JDK and javac to support building Java 11, which is being released in two weeks. I think we should try to avoid pushing Java 11 support back an additional month.

**Comment by buchgr** [comment]
FYI: Since this is a incompatible change it needs to be hidden behind a `--incompatible_` flag.

**Comment by lberki** [comment]
It is :)

**Comment by aehlig** [comment]
@lberki 
> If I understand correctly, there will be a new baseline?

Yes. the new baseline is c062b1f1730f3562d5c16a037b374fc07dc8d9a2 which includes c6eef5df8. So the changes so far are included; if you change anything more (like hiding the fix behind a flag), please ping the release bug explicitly, so that any needed cherry-picks can be included.

**Comment by cushon** [comment]
> Yes. the new baseline is c062b1f which includes c6eef5d.

Great, thanks!

> > > it needs to be hidden behind a --incompatible_ flag.
> >
> > It is :)
>
> if you change anything more (like hiding the fix behind a flag)

I'm a little confused by this exchange: to be clear, "the fix" is c6eef5df8ac93207500be67b097a2becadd0736f, and it *is* hidden behind `--incompatible_never_use_embedded_jdk_for_javabase`.

That change by itself is a no-op, the reason I'm eager to get it into a release is so we can change the default behaviour is the next release.
