### ISSUE TITLE
Run custom error-prone checks without directly depending on library that exports them

### ISSUE THREAD

**Issue by vmax** [bazelbuild/bazel#6113]
### Description of the problem / feature request:

After writing a custom check for `error-prone`, I'd like to have it ran on all Java targets without explicily depending on it.

### Feature requests: what underlying problem are you trying to solve with this feature?

Ensuring code is correct without checking that plugin was included in dependencies

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

[Here](https://github.com/google/startup-os/tree/error-prone-bazel-check/examples/errorprone) are the sources for custom check

### What operating system are you running Bazel on?

macOS 10.13.6

### What's the output of `bazel info release`?

`release 0.14.1`

###  Have you found anything relevant by searching the web?

I know I could make a `java_library` with `exported_plugins` but I'll have to ensure *all* of my targets are depending on it in order for check to be performed.

**Comment by vmax** [comment]
Quoting @oferb:

>One option would be to apply it per directory. That way, we could more easily control whitelisting when gradually introducing new custom checks to the codebase.

**Comment by cushon** [comment]
@vmax there's some support for enabling the built-in checks based on a Bazel package pattern (e.g. `//your/project/...`): https://github.com/bazelbuild/bazel/issues/3427#issuecomment-367519584

It's currently harder to use that approach for custom checks, but we could improve that. Does that style of configuration look like it would work for your use-case?

**Comment by vmax** [comment]
@cushon this seems like a good start. As I understand, we **can't** enable custom checks from `bazel`'s command line opts yet, right?

cc @oferb

**Comment by jin** [comment]
@lberki could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?

**Comment by guw** [comment]
@vmax You closed the issue as completed. Can you share some insights how you implemented it?
