### ISSUE TITLE
Better message for when `native.foo` is erroneously accessed in .bzl file as if it were top-level symbol `foo`

### ISSUE THREAD

**Issue by smukherj1** [bazelbuild/bazel#6119]
### Description of the problem / feature request:

Feature request: Better error message when a rule is defined in a BUILD file or a rule is invoked from a .bzl file instead of a cryptic "blah is not defined" error. I'm just looking to see if we can get bazel to emit a more user friendly error like:-
blah is a rule invocation which is only allowed in BUILD files. Not allowed to invoke it from blah.bzl

I'm not sure if the reverse should also be looked into ie the error message emitted when a rule is defined in a BUILD file

### Feature requests: what underlying problem are you trying to solve with this feature?

Better usability for new users

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Attaching a small test case. Here is a poorly defined bazel project with a toolchain rule that was created by a new bazel user (me :) ) when following the toolchain rule tutorial https://docs.bazel.build/versions/master/toolchains.html. At the time of creating this issue, the toolchain rule documentation does not indicate which code snippet should go in which file (exception the toolchain registration part). This project will give the following error when bazel build is invoked on the :preamble target
`ERROR: /path/to/my_lib.bzl:19:1: name 'toolchain_type' is not defined`

[bazel_toolchain_tut.tar.gz](https://github.com/bazelbuild/bazel/files/2367706/bazel_toolchain_tut.tar.gz)

### What operating system are you running Bazel on?

gLinux based on debian

### What's the output of `bazel info release`?

release 0.16.1

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Not in bazel's git repo. Using a production release

###  Have you found anything relevant by searching the web?

Not really. Documentation on toolchain_type is sparse and I wasn't actually sure if it was a builtin
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

This bazel project has many other issues and please don't get bogged down trying to get it to pass

**Comment by laurentlb** [comment]
In general, it's hard to provide a better error message for this. The interpreter doesn't know a symbol, it's hard to provide more information.

This particular issue is due to the `native` module. I agree it's not well designed: the fact that the function is not called the same way in BUILD and bzl files is indeed confusing. I would like to fix that, and I remember discussions about possible changes there.

(we could add a temporary special-cased error message that looks for `native`)

**Comment by brandjon** [comment]
We have special casing for flag-guarded values to print a pretty error message when accessing them without the proper flag, rather than "foo is not defined". We could adapt a similar mechanism to make these kinds of errors super friendly as well,
