### ISSUE TITLE
'java_runtime_suite' is not defined- 0.17.1 regression

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#6121]
### Description of the problem / feature request:

`java_runtime_suite` doesn't work (analysis failure) on 0.17.1rc4  
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

empty `WORKSPACE` file
`BUILD` file with following contents:
```
java_runtime_suite(
    name = "jdk8",
    default = ":jdk8-default",
)
java_runtime(
    name = "jdk8-default",
    srcs = [],
    java_home = "/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home",
)
```
`bazel build //...` passes with `0.16.1` and fails with `0.17.1rc4` with the following error:
```
ERROR: /Users/ittaiz/workspace/bazel-playground/java-runtime-suite/BUILD:1:1: name 'java_runtime_suite' is not defined (did you mean 'java_runtime_alias'?)
```

### What operating system are you running Bazel on?

OS X Sierra

**Comment by cushon** [comment]
There's a line about that in the [relnotes](https://releases.bazel.build/0.17.0/rc1/index.html):

> Remove support for java_runtime_suite; use alias() together with select() instead.

The `select()` is only necessary if you want to choose between different runtimes for different target architectures. For your example you can just refer to the `java_runtime` directly instead of wrapping it in a `java_runtime_suite`.

**Comment by cushon** [comment]
@lberki FYI

**Comment by ittaiz** [comment]
Shouldn’t it be in the incompatible_changes section?
My build broke without notice and honestly googling didn’t give me any info
this is going to happen.
Part of the problem is that this was a copy paste of the configuration from
bazel-toolchains (since we need a derivation of that) and we didn’t see
they also removed it.

I opened this ticket for two reasons:
1. Make sure I’m indeed not missing anything (which I did).
2. Share with y’all in case this will add more breakages.

On my side I have no problems working around this. Leaving it up to you.

Thanks for the quick reply!

**Comment by lberki** [comment]
Erm, it should totally have been in the incompatible changes section and we should totally not have done this without an incompatible change flag. We *do* have a problem of callously breaking people... there is a discussion about how we should handle this here:

https://groups.google.com/d/msg/bazel-discuss/wYocSoGTJOg/aJnD4ZqUCAAJ

In our defense, that thread was started about two months after cushon@'s change. Please take a look and see if it's going in the direction you'd like! And I promise we'll try harder *not* to break people without warning in the future.
