### ISSUE TITLE
file_test doesn't work on Windows

### ISSUE THREAD

**Issue by nex3** [bazelbuild/bazel#6122]
### Description of the problem / feature request:

The `file_test` rule doesn't seem to work on Windows. It looks like it's grepping for a POSIX path. See https://github.com/bazelbuild/rules_sass/pull/47#issuecomment-420088820 for an example of this coming up in practice.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I suspect any `file_test` rule on Windows will reproduce the bug, or you could check out https://github.com/bazelbuild/rules_sass/pull/47/commits/5618d4ac8ad515f429f8a2ef6b8bdfc3ed429175 and run `bazel test sass/test:no_sourcemap_file_test`.

### What operating system are you running Bazel on?

Windows.

### What's the output of `bazel info release`?

@jelbourn Can you see the release info from the continuous build?

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
git@github.com:bazelbuild/rules_sass
ffe6b6657a33d1d3a91140994470f58a7aae63be
5618d4ac8ad515f429f8a2ef6b8bdfc3ed429175
```

**Comment by laszlocsomor** [comment]
Indeed. Sorry for the long silence. Let me fix this bug.

**Comment by laszlocsomor** [comment]
Dropping priority to P3 -- this bug is important but probably not critical.

**Comment by laszlocsomor** [comment]
Tentatively adding "Bazel 1.0" label, though I doubt we'll get to it any time soon :/

**Comment by laszlocsomor** [comment]
Having slept on it, I don't think this is critical for 1.0 anymore.

**Comment by laszlocsomor** [comment]
This was fixed by https://github.com/bazelbuild/bazel/pull/8352
