### ISSUE TITLE
Jobs generating big output files slow with --disk_cache

### ISSUE THREAD

**Issue by AustinSchuh** [bazelbuild/bazel#6123]
I'm using the --disk_cache flag to bazel.  We've got a number of large data files that get generated as part of some rules.  I'm seeing ~300 MB/s read speeds using iostat (small % of the speed of the drive I've got for it), and 100% CPU usage in Bazel.

We are running 0.16.1

**Comment by buchgr** [comment]
The current code is rather inefficient and can be improved. Would you be interested in working on this Austin? The code is also self-contained so should be quite simple to experiment with it: https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/remote/blobstore/OnDiskBlobStore.java

**Comment by buchgr** [comment]
To provide more detail:

The current code simply copies the data from the source into a in-heap byte array and writes them to the file in the disk cache. We could improve on that by doing an in-kernel transfer on systems that support it. Java allows one to do that using `FileChannel.transferTo`. You'd need to implement a `copy` method in our FileSystem API and special case `FileInputStream/FileOutputStream`.

**Comment by AustinSchuh** [comment]
@buchgr , I'd love to take a look but I'm swamped for a couple weeks at a minimum.  If nobody gets to it before I free up, I can take a look.

This also feels like something that should be done in a parallel context instead of a single threaded context.  I'm only seeing 100% CPU, rather than 1000% CPU like I'd hope for.  That would also fix the issue.  Fast SSDs are hard to saturate with a single thread.  The drive in question can manage 1-2 GB/s of data transfer.

Maybe I'm getting too clever, but is this something where a hard link on Linux would make sense?  That would avoid duplicating the data on the disk too, which would be a significant speedup.

**Comment by purkhusid** [comment]
@buchgr I'm intersted in taking a look at this. We've got some large docker layers and also NodeJS outputs that are large and/or include a lot of files. Any pointers on where to start? I see that the whole `RemoteCacheClient` interface and `RemoteCache` base class are all expecting to work with a in memory byte array.

Would you just recommend not using the `RemoteCacheClient` interface and the methods in the `RemoteCache` base class and write the `OnDiskBlobStoreCache` from scratch using the Channels API?

**Comment by ulfjack** [comment]
I'd look at a profiler first. It might be enough to just make the buffers a bit bigger.
