### ISSUE TITLE
Poisoned disk cache

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#6126]
### Description of the problem / feature request:

I'm trying to upgrade a large repo from 0.15.2 to 0.17.1rc4 while using jdk8. This might be important since it meant I needed to do a few iterations on the build and also had no cache hits. After one of these iterations I saw the build fails on a very trivial target (creating an empty jar).
I investigated and saw that the disk_cache folder contains a few entries related to that label and that one of them is the cause of the issue.
When I removed it the repo builds fine with 0.17.1rc4 and with only it in the cache the build fails (as you can see in this isolated repro https://github.com/ittaiz/bazel_poison_disk_cache).

I think that the root cause was a "too many open files" issue which happened during one of the actions of one of the iterations.
I'm fairly confident it's not a 0.17.1rc4 issue but just happened during an iteration with it and since the cache is checksum based this is the way to reproduce it.

I think it's really important to see how we can mitigate such poisonous entries since they will cause a serious lack of trust for end users ("bazel clean" / "rm -rf cache folder" here we come).
Advice on fixing the specific action in rules_scala so this won't happen will also be welcomed but I think it's not the heart of the issue since it can happen in other rules.

Run output:
```
➜  foo git:(master) ~/Downloads/bazel-0.17.1rc4-darwin-x86_64 build //web-utils-modules/wix-http-cookies:tests_dependencies --verbose_failures --subcommands
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //web-utils-modules/wix-http-cookies:tests_dependencies (30 packages loaded).
INFO: Found 1 target...
SUBCOMMAND: # //web-utils-modules/wix-http-cookies:tests_dependencies [action 'scala //web-utils-modules/wix-http-cookies:tests_dependencies']
(cd /private/var/tmp/_bazel_ittaiz/144499a4f412f866086e876f3bbfb495/execroot/foo && \
  exec env - \
  /bin/bash -c '
rm -f bazel-out/darwin-fastbuild/bin/web-utils-modules/wix-http-cookies/tests_dependencies.jar
external/bazel_tools/tools/zip/zipper/zipper c bazel-out/darwin-fastbuild/bin/web-utils-modules/wix-http-cookies/tests_dependencies.jar @bazel-out/darwin-fastbuild/bin/web-utils-modules/wix-http-cookies/tests_dependencies_zipper_args
# ensures that empty src targets still emit a statsfile
touch bazel-out/darwin-fastbuild/bin/web-utils-modules/wix-http-cookies/tests_dependencies.statsfile
')
ERROR: /Users/ittaiz/temp/foo/web-utils-modules/wix-http-cookies/BUILD.bazel:7:1: output 'web-utils-modules/wix-http-cookies/tests_dependencies.jar' was not created
ERROR: /Users/ittaiz/temp/foo/web-utils-modules/wix-http-cookies/BUILD.bazel:7:1: not all outputs were created or valid
Target //web-utils-modules/wix-http-cookies:tests_dependencies failed to build
INFO: Elapsed time: 2.546s, Critical Path: 0.02s
INFO: 1 process: 1 remote cache hit.
FAILED: Build did NOT complete successfully
```

cc @aehlig as the master of disk cache

**Comment by ittaiz** [comment]
Replace repository cache with disk cache. Got my terms wrong. Sorry.

**Comment by ittaiz** [comment]
@buchgr why did you change the title? My original title was a mistake. The problem is with the disk cache.

**Comment by buchgr** [comment]
my bad sorry.

**Comment by ittaiz** [comment]
NP. Do you know who's the disk cache "person"?

**Comment by buchgr** [comment]
I'd probably be the person responsible :-)

>I think that the root cause was a "too many open files" issue which happened during one of the actions of one of the iterations.

What issue is that? Can you please provide more context and why you think that's the issue?

Thanks!

**Comment by ittaiz** [comment]
What I meant was that I was running a clean build and with high
parallelization and then I saw the build fail with “too many open files”
message coming from an action.
Later on I stumbled on to this and so I *think* (without concrete data)
that it might have been the issue.
I think the action completed partially and poisoned the cache.
I’m not sure I’ll be able to reproduce it easily but I still think it’s a
serious issue.
Is there anything more I can add?

**Comment by buchgr** [comment]
@ittaiz I think with the reproducer you did well and now it's my time to take a look. Thanks for the info!

**Comment by ittaiz** [comment]
Sure thing!
Keeping my fingers crossed :)

**Comment by buchgr** [comment]
@ittaiz can you confirm that the actual subcommand did succeed (exit code 0) but that Bazel then failed because this subcommand did not create all declared outputs?

**Comment by ittaiz** [comment]
You mean in the original run? I don’t know.
In the repro I don’t remember but I think you’re right because the error is
indeed about the target not having all of the outputs.

**Comment by ittaiz** [comment]
Interesting. Re remote caching you mean if this exception were to happen on
an RBE worker, for example, it would also poison the cache?

**Comment by buchgr** [comment]
@ittaiz no if the exception where to happen locally in Bazel but the remote action succeeds. it's the same code path as the local disk cache.

**Comment by ittaiz** [comment]
@buchgr any updates?

**Comment by ittaiz** [comment]
@buchgr this can happen also using your solution of `bazel-remote`, right?

**Comment by buchgr** [comment]
@ittaiz no, iirc this bug is isolated to the disk path code path.
