### ISSUE TITLE
bazel fails: no such package 'tools/jdk'

### ISSUE THREAD

**Issue by yurivict** [bazelbuild/bazel#613]
Trying to build some other project, my bazel command fails like this:

```
# bazel build --jobs 2 -c opt //tensorflow/tools/pip_package:build_pip_package --verbose_failures
ERROR: Loading of target '//tools/jdk:GenClass_deploy.jar' failed; build aborted: no such package 'tools/jdk': BUILD file not found on package path.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 0.116s
```

What can be wrong?

```
# which java && which javac
/usr/local/bin/java
/usr/local/bin/javac
# pkg info | grep jdk
bootstrap-openjdk-r351880_1    Oracle's Java 6 virtual machine release under the GPL v2
openjdk-7.80.15_1,1            Java Development Kit 7
openjdk8-8.60.24               Java Development Kit 8
```

FreeBSD 10.2

**Comment by kchodorow** [comment]
What does `bazel info package_path` say?  Did you install `bazel` from source or using the binary installer?

**Comment by yurivict** [comment]
```
# bazel info package_path
%workspace%
```

I installed bazel from the FreeBSD port. Built it from the source.

**Comment by kchodorow** [comment]
Do you have a `~/.bazelrc` file?  Please add or modify it to be:

```
build --package_path %workspace%:/path/to/your/bazel/source
fetch --package_path %workspace%:/path/to/your/bazel/source
query --package_path %workspace%:/path/to/your/bazel/source
```

...replacing `/path/to/your/bazel/source` with the actual path.

Bazel needs to use several tools to build which are in the bazel repository.  It sounds like the FreeBSD port doesn't set it up correctly, could you send me a link to where you downloaded it from?

**Comment by yurivict** [comment]
The change in ~/.bazelrc helped, thanks!

As for the FreeBSD port, I created it myself. I was under the impression that it only needs one executable 'bazel' for work.

I used Arch package as a reference https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bazel-git

They just copy the whole directories: examples third_party tools into /opt/bazel/base_workspace

Could you tell me what other files should be in the installation? Are complete copies of 
third_party tools required?

**Comment by kchodorow** [comment]
I don't remember exactly what is and isn't required, I'd guess third_party/ijar and tools/{jdk,cpp,genrule,test,defaults}, but I might be missing some stuff.  You could put those in a temporary directory, point your .bazelrc at it and see if bazel complains.

**Comment by yurivict** [comment]
Ok, thanks. I will add these.

You might want to write the document with the list of what is required. Otherwise porters will just copy the whole tree and this bloats the system.

**Comment by xubenben** [comment]
Thanks
