### ISSUE TITLE
bazel-0.16.1-dist.zip doesn't use the embedded JDK

### ISSUE THREAD

**Issue by cushon** [bazelbuild/bazel#6131]
Follow-up to #6060, cc @lberki.

> > it consistently fails to compile using a version built from https://github.com/bazelbuild/bazel/releases/download/0.16.1/bazel-0.16.1-dist.zip
> 
> I can reproduce. That build produces a binary without an embedded JDK, so if it picks up a JDK 8 from `JAVA_HOME`, and the compile-time bootclasspath handling hits this code path:

why does `bazel-0.16.1-dist.zip` produce a binary without an embedded JDK? Is that deliberate?

Generally we always recommend the embedded JDK binaries. They also allow Bazel to use the default `java_toolchain` which isn't affected by this bug, instead of the `hostjdk8` toolchain.

@BrentDouglas is it possible to use one of the binaries we distribute, or if you prefer to build it yourself to use `bazel build //src:bazel` instead of the `-dist.zip` archive?

**Comment by BrentDouglas** [comment]
Hi @cushon, sorry for the delayed reply.

Most of our devs have macbooks so we have been using brew to get bazel, our CI server is ubuntu and we've been using apt and I am on archlinux and have been using pacman. I'm not 100% sure which of these get binaries from the bazel team and which are built by maintainers but I would imagine that if they were they would be using the provided `-dist.zip`.

I only tried building using `bazel build //src:bazel` when trying to dig into why it was failing on my system.

Regarding the different toolchains, our build has always just used the default toolchain.

**Comment by lberki** [comment]
We have changed the way we use the embedded JDK, so I assume this is not a problem anymore.
