### ISSUE TITLE
Bazel 0.17.1 regression: Unrecoverable error while evaluating node

### ISSUE THREAD

**Issue by gjasny** [bazelbuild/bazel#6149]
### Description of the problem / feature request:

Bazel 0.17.1 crashes with: 
```
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node '//core/...' (requested by nodes '[//core/...] EXPAND_TEST_SUITES com.google.devtools.build.lib.pkgcache.TestFilter@e17a1')
```

Bazel 0.16.1 worked as expected.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
git clone https://github.com/jupp0r/prometheus-cpp
git reset --hard ae2568ae4607a1b53f10f0c551834e6b3e758a7d
bazel-0.17.1 build //core/...
```

See also: https://travis-ci.org/jupp0r/prometheus-cpp/builds/428587181?utm_source=github_status&utm_medium=notification

### What operating system are you running Bazel on?

MacOS (locally), Ubuntu (Travis)

### What's the output of `bazel info release`?

`release 0.17.1`

**Comment by gjasny** [comment]
If I remove the `.bazelignore` file in the project root, everything works (when no submodules have been checked out to `3rdparty`).

**Comment by iirina** [comment]
Was this fixed in more recent Bazel releases?

**Comment by gjasny** [comment]
Hi,

Bazel 0.17.2 fails, 0.18.0rc4 works.

Thanks,
Gregor

**Comment by ittaiz** [comment]
I think we’re seeing this as well (trying to double check).
Will this be in a 0.17.3? A bit concerned about waiting for 0.18 since
we’re still handling repercussions from the 17 upgrade

**Comment by iirina** [comment]
No one is working on a 0.17.3, most probably it has to wait for 0.18. You can ask on the [0.17.2 issue](https://github.com/bazelbuild/bazel/issues/6164) if the release manager thinks it makes sense to release another patch.

I'll close this as the fix was committed.
