### ISSUE TITLE
Header file changes do not retrigger builds

### ISSUE THREAD

**Issue by wateryzephyr** [bazelbuild/bazel#6155]
### Description of the problem / feature request:

Changes in header files (but not source files) don't retrigger builds.

(The exact same issue, albeit on Windows, was raised here https://github.com/bazelbuild/bazel/issues/3202)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

You can repro this using the initial bug report (see above link): https://github.com/bazelbuild/bazel/issues/3202#issuecomment-308936286

### What operating system are you running Bazel on?

Linux, Ubuntu 16.04

### What's the output of `bazel info release`?

release 0.16.1

###  Have you found anything relevant by searching the web?

See above reference.

### Any other information, logs, or outputs that you want to share?

No.

**Comment by mirandaconrado** [comment]
Seems to be fixed on 0.17.2, from a quick test.

**Comment by ulfjack** [comment]
I'm not aware of any change that could have caused this or any other report, but I'm much less involved in C++ rules these days.

@mhlopko, are you aware of this?

**Comment by wateryzephyr** [comment]
Confirmed this issue is gone with 0.17.2. Closing the bug out.
