### ISSUE TITLE
Error messages for builtin functions don't show expected keyword arguments

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#6160]
### Description of the problem / feature request:

Code: https://gist.github.com/endobson/d764dec72404fa34530b9cae8afa9cfd
```
bazel build //:test2 //:test
Users/endobson/tmp/bazel-error-message-bug/BUILD:7:1: in my_rule2 rule //:test2:
Traceback (most recent call last):
        File "/Users/endobson/tmp/bazel-error-message-bug/BUILD", line 7
                my_rule2(name = 'test2')
        File "/Users/endobson/tmp/bazel-error-message-bug/rule.bzl", line 20, in _my_rule2_impl
                helper(executable = True)
unexpected keyword 'executable' in call to helper(is_excutable = True)
ERROR: /Users/endobson/tmp/bazel-error-message-bug/BUILD:3:1: in my_rule rule //:test:
Traceback (most recent call last):
        File "/Users/endobson/tmp/bazel-error-message-bug/BUILD", line 3
                my_rule(name = 'test')
        File "/Users/endobson/tmp/bazel-error-message-bug/rule.bzl", line 13, in _my_rule_impl
                ctx.actions.write(output = new_way, content = "HELLO...", ...)
unexpected keyword 'executable', in method call write(File output, string content, bool executable) of 'actions'
WARNING: errors encountered while analyzing target '//:test2': it will not be built
WARNING: errors encountered while analyzing target '//:test': it will not be built
INFO: Analysed 2 targets (0 packages loaded).
INFO: Found 0 targets...
ERROR: command succeeded, but not all targets were analyzed
INFO: Elapsed time: 0.112s, Critical Path: 0.00s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

The error message for a bad skylark function includes the signature of the function, while a call to a builtin function includes the signature of the call. These both look very similar but the skylark one is much more useful because it tells me what keyword arguments are expected.

I would think that the builtin code should change to show the signature of the function instead of the call site.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 0.16.1- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

built from the release tar

**Comment by laurentlb** [comment]
In the second one, you get the signature of the function too:
`unexpected keyword 'executable', in method call write(File output, string content, bool executable) of 'actions'`

How can we make it clearer?
