### ISSUE TITLE
Toolchain docs use attr.string instead of attr.label

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#6161]
### Description of the problem / feature request:
From the docs here:
https://docs.bazel.build/versions/master/toolchains.html#creating-a-toolchain-rule

Rule definition uses attr.string:
```
my_toolchain = rule(
  _my_toolchain_impl,
  attrs = {
    'compiler': attr.string(),
    'system_lib': attr.string(),
    'arch_flags': attr.string_list(),
  })
```

Use site passes in strings that look like labels:
```
my_toolchain(
  name = 'linux_toolchain_impl',
  compiler = '@remote_linux_repo//compiler:compiler_binary',
  system_lib = '@remote_linux_repo//library:system_library',
  arch_flags = [
    '--arch=Linux',
    '--debug_everything',
  ]
)
```

I believe that for this to work correctly that this should be `attr.label`, if `attr.string` is actually the correct implementation then there probably should be some docs explaining why and how label resolution for this works.

**Comment by brandjon** [comment]
In a rewrite of this doc page, we keep it string and call out the fact that this is a simplification for ease of presentation.
