### ISSUE TITLE
Toolchain tutorial contradicts ToolchainInfo reference documentation

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#6162]
### Description of the problem / feature request:

Reference documentation:
https://docs.bazel.build/versions/master/skylark/lib/platform_common.html#ToolchainInfo
> The provider constructor for ToolchainInfo. The constructor takes the type of the toolchain, and a map of the toolchain's data.

Tutorial:
https://docs.bazel.build/versions/master/toolchains.html#creating-a-toolchain-rule
```
def _my_toolchain_impl(ctx):
  toolchain = platform_common.ToolchainInfo(
    compiler = ctx.attr.compiler,
    system_lib = ctx.attr.system_lib,
    arch_flags = ctx.attr.arch_flags,
  )
  return [toolchain]
```

The tutorial doesn't call `ToolchainInfo` with the type of the toolchain at all, and doesn't pass in a map, just keyword arguments. I think the tutorial documents the correct usage.

**Comment by katre** [comment]
Thanks for bringing this to my attention. We're actually in the middle of a documentation audit this week, and this is exactly the type of issue we want to flag.
