### ISSUE TITLE
Cannot bootstrap bazel 0.17.1

### ISSUE THREAD

**Issue by jgavris** [bazelbuild/bazel#6168]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Testing building bazel 0.17.1 using Xcode 9 / 10 toolchains and I am unable to build bazel from scratch / source. It appears the executable bit is lost when packaging the distribution zip.

```shell
jgavris in ~/code/software/bazel on (HEAD detached at 0.17.1)
λ find . -name ibtoolwrapper.sh | xargs ls -al
-rwxr-xr-x  1 jgavris  staff  3637 Feb  8  2018 ./src/tools/xcode/ibtoolwrapper/ibtoolwrapper.sh
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
jgavris in ~/Downloads/bazel-0.17.1-dist
λ bash ./compile.sh
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
.WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Analysed target //src:bazel_nojdk (235 packages loaded).
INFO: Found 1 target...
ERROR: /Users/jgavris/Downloads/bazel-0.17.1-dist/src/tools/xcode/ibtoolwrapper/BUILD:8:1: failed to create symbolic link 'src/tools/xcode/ibtoolwrapper/ibtoolwrapper': file 'src/tools/xcode/ibtoolwrapper/ibtoolwrapper.sh' is not executable
Target //src:bazel_nojdk failed to build
INFO: Elapsed time: 6.875s, Critical Path: 0.47s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel
./src/tools/xcode/ibtoolwrapper/ibtoolwrapper.sh
jgavris in ~/Downloads/bazel-0.17.1-dist
λ find . -name ibtoolwrapper.sh | xargs ls -al
-rw-------@ 1 jgavris  staff  3637 Dec 31  1979 ./src/tools/xcode/ibtoolwrapper/ibtoolwrapper.sh
```

### What operating system are you running Bazel on?

macOS 10.13.6

### What's the output of `bazel info release`?

N/A

**Comment by philwo** [comment]
Handing over to @aehlig, who probably knows best about the bootstrap scripts and because I'm still OOO.

Klaus, feel free to just reassign to me if you're too busy or have no idea and I'll take a look in the next days!

**Comment by aehlig** [comment]
I don't think this is related to the bootstrap scripts, more to the question how different versions of `unzip` handle file mode creation mask and the packed executable bit. As I don't have a mac machine, I cannot investigate further; but, at least, to demonstrate that different versions of `unzip` make a difference, look at the following on my personal `FreeBSD stable/10` machine.

```/tmp/work>fetch https://github.com/bazelbuild/bazel/releases/download/0.17.1/bazel-0.17.1-dist.zip
bazel-0.17.1-dist.zip                         100% of   75 MB 5247 kBps 00m15s
/tmp/work>mkdir old
/tmp/work>cd old
/tmp/work/old>/usr/bin/unzip -q ../bazel-0.17.1-dist.zip 
/tmp/work/old>ls -al src/tools/xcode/ibtoolwrapper
total 20
drwx------  2 aehlig  wheel   512 Sep 18 10:30 .
drwx------  7 aehlig  wheel   512 Sep 18 10:30 ..
-rwx------  1 aehlig  wheel   284 Jan  1  1980 BUILD
-rwx------  1 aehlig  wheel   239 Jan  1  1980 README
-rwx------  1 aehlig  wheel  3637 Jan  1  1980 ibtoolwrapper.sh
/tmp/work/old>cd ..
/tmp/work>mkdir new
/tmp/work>cd new
/tmp/work/new>/usr/local/bin/unzip -q ../bazel-0.17.1-dist.zip 
/tmp/work/new>ls -al src/tools/xcode/ibtoolwrapper
total 20
drwx------  2 aehlig  wheel   512 Sep 18 10:31 .
drwx------  7 aehlig  wheel   512 Sep 18 10:31 ..
-rwxr-xr-x  1 aehlig  wheel   284 Jan  1  1980 BUILD
-rwxr-xr-x  1 aehlig  wheel   239 Jan  1  1980 README
-rwxr-xr-x  1 aehlig  wheel  3637 Jan  1  1980 ibtoolwrapper.sh
/tmp/work/new>cd ..
/tmp/work>sha256 bazel-0.17.1-dist.zip 
SHA256 (bazel-0.17.1-dist.zip) = 23e4281c3628cbd746da3f51330109bbf69780bd64461b63b386efae37203f20
/tmp/work>
```

**Comment by philwo** [comment]
@jgavris Could you let us know which version of "unzip" you used to extract the archive? I'd like to reproduce this on my machine if possible.

**Comment by jgavris** [comment]
Hm, my bad. I just did a double-click / `open` on the zip. If I do `unzip`, the file permissions are preserved.
