### ISSUE TITLE
scala rule fails with larger targets

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#617]
doing a touch on the file list can exceed the maximum number of arguments allowed on the command line:

https://github.com/bazelbuild/bazel/blob/7c8938450636d7736614f13240b971d7cb5bec97/tools/build_defs/scala/scala.bzl#L44

I worked around this here using `find -exec`:

https://github.com/twitter/scalding/pull/1452/files#diff-95643cc899a13eaaa035f2e811e0005eR44

**Comment by damienmg** [comment]
@laurentlb can someone from the Skylark team take care of this one? This is a not too complex change (we should use the @filename syntax and store the list of arguemnts in the filename just like we do for javac).

**Comment by laurentlb** [comment]
Sorry, I'm going to leave on vacation (and busy most of December)
