### ISSUE TITLE
Failed to create runfiles tree (build_bazel_rules_typescript)

### ISSUE THREAD

**Issue by manekinekko** [bazelbuild/bazel#6176]
### Description of the problem:

Hi, I'm trying to setup bazel for my angular project: [xLayers](https://github.com/xlayers/xlayers/) ( [bazel branch](https://github.com/xlayers/xlayers/tree/bazel-support) ). I'm encountering this error after running a build command:

`bazel build ...`

Ouput:
```
Starting local Bazel server and connecting to it...
INFO: Analysed 36 targets (102 packages loaded).
INFO: Found 36 targets...
ERROR: /private/var/tmp/_bazel_wassim/a52e6be12b831a4a1e95901c31c1bbad/external/build_bazel_rules_typescript/internal/BUILD.bazel:31:1: Creating runfiles tree bazel-out/host/bin/external/build_bazel_rule
s_typescript/internal/tsc.runfiles [for host] failed: Process exited with status 1: Process exited with status 1
INFO: Elapsed time: 500.425s, Critical Path: 0.42s
INFO: 1 process: 1 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Clone this ( [branch](https://github.com/xlayers/xlayers/tree/bazel-support) and just run a build command: `bazel build ...`

### What operating system are you running Bazel on?

```
ProductName:    Mac OS X
ProductVersion: 10.13.6
BuildVersion:   17G65
```

### What's the output of `bazel info release`?

```
Build label: 0.16.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 13 13:42:50 2018 (1534167770)
Build timestamp: 1534167770
Build timestamp as int: 1534167770
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
git@github.com:xlayers/xlayers.git
0917e0b524d93ae6d33ba4fe18e7aa95dc15f9b2
39cbf2b43502ae7bf2e3b887429b855119c49cee
```

###  Have you found anything relevant by searching the web?

[This](https://github.com/bazelbuild/rules_typescript/issues/274#issuecomment-422080079). But it's not solving this issue.

### Any other information, logs, or outputs that you want to share?

My env:
- NVM: 8.11.3
- Node: 8.11.3
- NPM: 6.4.1
- TSC (local): 2.9.2
- Angular: 6.1.7

Bazel info:
```
Build label: 0.16.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 13 13:42:50 2018 (1534167770)
Build timestamp: 1534167770
Build timestamp as int: 1534167770
```

Java info:
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

Issue openned in the [bazelbuild/rules_typescript](https://github.com/bazelbuild/rules_typescript/issues/274) project as well.

cc @alexeagle

**Comment by alexeagle** [comment]
To be clear, the Bazel bug here is that the error reporting gave no output from the process that exited 1.
I saw the same in Bazel 0.17

**Comment by philwo** [comment]
That seems like a pretty bad bug. I'll investigate.

**Comment by zackarychapple** [comment]
@philwo after you resolve it would you mind sharing real quick how you debugged it. I'd love to share with others so we can help more in the future.

**Comment by philwo** [comment]
I'm really sorry, I currently don't have time to look into this in much detail. :( If you can give me a step of commands to run with which I can repro the failure, I can run a git bisect and find the commit that broke this.

I need something like "brew install some_dependency, then npm install other_dependency, git clone http://this/repo, then cd repo and bazel build //some:target, this works with Bazel 0.X.Y but it fails with the latest release".

**Comment by zackarychapple** [comment]
@manekinekko do you have a link to a branch that is having the issues for xLayers?

**Comment by philwo** [comment]
@dslomov Tobi said you know stuff about runfiles - could you have a look?

**Comment by manekinekko** [comment]
This is the [branch](https://github.com/xlayers/xlayers/tree/bazel-support)

**Comment by dslomov** [comment]
When I try to run `bazel run @yarn//:yarn`, I get
```
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=121
INFO: Reading rc options for 'build' from /Users/dslomov/work/bug6167/xlayers/.bazelrc:
  'build' options: --strategy=TypeScriptCompile=worker --strategy=AngularTemplateCompile=worker --symlink_prefix=dist/ --define=compile=legacy --verbose_failures=true --announce_rc
ERROR: error loading package '': Encountered error while reading extension file 'package.bzl': no such package '@build_bazel_rules_typescript//': /private/var/tmp/_bazel_dslomov/82593653427950b84c6b07eece86838c/external/build_bazel_rules_typescript must be an existing directory
ERROR: error loading package '': Encountered error while reading extension file 'package.bzl': no such package '@build_bazel_rules_typescript//': /private/var/tmp/_bazel_dslomov/82593653427950b84c6b07eece86838c/external/build_bazel_rules_typescript must be an existing directory
INFO: Elapsed time: 0.107s
INFO: 0 processes.
```
Your WORKSPACE file has
```
# Runs the TypeScript compiler
local_repository(
    name = "build_bazel_rules_typescript",
    path = "node_modules/@bazel/typescript",
)

load("@build_bazel_rules_typescript//:package.bzl", "rules_typescript_dependencies")
rules_typescript_dependencies()
```
but my checkout does not have `node_modules/@bazel/typescript`. How do I get that? (I guess I need to say `npm install` something or other?)

**Comment by manekinekko** [comment]
Yeh, I think you need to run `yarn install` before.

**Comment by dslomov** [comment]
got it, looking

**Comment by dslomov** [comment]
Next up:
```
$ bazel build ...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=121
INFO: Reading rc options for 'build' from /Users/dslomov/work/bug6167/xlayers/.bazelrc:
  'build' options: --strategy=TypeScriptCompile=worker --strategy=AngularTemplateCompile=worker --symlink_prefix=dist/ --define=compile=legacy --verbose_failures=true --announce_rc
ERROR: error loading package 'node_modules/@angular/bazel': Extension file not found. Unable to load package for '//tools:defaults.bzl': BUILD file not found on package path
INFO: Elapsed time: 1.045s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (9 packages loaded)
    currently loading:  ... (16 packages)
```

**Comment by dslomov** [comment]
(`node_modules/@angular/bazel/BUILD.bazel` has `load("//tools:defaults.bzl", "npm_package")` - where is this file supposed to come from?)

**Comment by manekinekko** [comment]
@alexeagle any idea?

**Comment by alexeagle** [comment]
We shouldn't be building anything for Angular under node_modules.
(starting with Bazel 0.18 we'll recommend using the new .bazelignore to prevent bazel looking under node_modules at all)

But the real question for this issue is, how did you find that error? This is an error reporting issue in Bazel, in this context I don't care about fixing the root cause.

**Comment by benjaminp** [comment]
I don't think anyone has claimed to find a root cause for the OP. dslomov's errors look like they're just en route to trying to reproduce the error in the OP.

**Comment by dslomov** [comment]
correct, I would like to get to a repro, and I am failing so far....

**Comment by manekinekko** [comment]
I've updated the `@bazel/typescript` to `0.17.0` in my project and I think the issue is now gone.
I've also sync'ed the other config files `WORKSPACE` and `BUILD` and deps with those from the [angular-bazel-example](https://github.com/alexeagle/angular-bazel-example) repo.

Now, I'm having other issues but probably not related to this one.

**Comment by Dig-Doug** [comment]
@dslomov - I also encountered this issue with the angular-bazel-example. My repro steps are [here](https://github.com/alexeagle/angular-bazel-example/issues/202). I tried them again today with bazel 0.17.2 and I am still able to repro.

Make sure you checkout the **exact commit** I mentioned, otherwise it won't fail. As @manekinekko said, the typescript issue must've been fixed.

**Comment by benjaminp** [comment]
Found it:
```
link or target filename contains space on line 7951: 'angular_bazel_example/node_modules/randomcolor/demo/Edit fiddle - JSFiddle_files/OrbitControls.js
```
which would have been seen if all runfiles building output wasn't swallowed by Bazel. :)

**Comment by philwo** [comment]
Can this considered to be fixed thanks to https://github.com/bazelbuild/bazel/commit/c63e4fedda25f5b4f547d9142138030ea8f278e1 ?

**Comment by alexeagle** [comment]
SGTM, I think that change means that the error about "filename contains space" would now be discoverable to a user.
