### ISSUE TITLE
BUILD files need an extension for good integration into Finder/Windows/Unity 

### ISSUE THREAD

**Issue by dmaclach** [bazelbuild/bazel#618]
The fact that BUILD files do not have an extension on them makes it difficult to integrate bazel nicely into desktop operating systems. Associating icons/editors/indexing them etc becomes more painful than it needs to be. I realize this is a long shot, but has there been any consideration into allowing/requiring a file extension?

**Comment by damienmg** [comment]
I don't think we can do that. This would make things incompatibles. Just like make always expect Makefile...

**Comment by damienmg** [comment]
Closing as wontfix, this is really a complex thing and it has no good reason for doing it.

**Comment by dmaclach** [comment]
Seems odd that we are happy with "it's good enough for Makefiles, so it should be good enough for us". If you want bazel adoption we should improve on the status-quo instead of just accepting it. File extensions appear to be the way that systems work and the fact that historically BUILD files didn't do this is really unfortunate. Note that skylark files do have an extension.

Reasons for doing it:
a) Allows systems to know the type of a file so that it can be indexed/searched by the operating system
b) Allows systems to associate an icon with the system
c) Allows things like Android Studio to be able to react to someone attempting to open a BUILD file by double clicking on it

I'm tasked with figuring out ways to better integrate bazel into workflows. The fact we don't have file extensions is a pain to me and is a pain to external developers who have to work with our system.

'Nuff said.

**Comment by ulfjack** [comment]
BUILD files allow essentially the same language as .bzl files, though we may want to disallow loading BUILD.bzl files (if we allow that as an extension).

**Comment by dmaclach** [comment]
I would like to keep skylark files separate from BUILD files. Even though
they are based on the same language underneath, they perform different
functions. For the tooling we are building for Mac OS X, we want something
different to happen if the user opens a BUILD file than if they open a
skylark file.
