### ISSUE TITLE
Bazel hardcodes passing -static-libgcc even if you don't use libgcc

### ISSUE THREAD

**Issue by dapirian** [bazelbuild/bazel#6185]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Bazel hardcodes passing `-static-libgcc` even if you compile with `-rtlib=compiler-rt`. This doesn't particularly hurt anything, but it causes warnings to be spammed:
`clang: warning: argument unused during compilation: '-static-libgcc' [-Wunused-command-line-argument]`

Looks like this happens here:
https://github.com/bazelbuild/bazel/blob/aaba6feff7606f72dd4a2c14e837f56761628d33/src/main/java/com/google/devtools/build/lib/rules/cpp/CcBinary.java#L329

This should be configurable somewhere toolchain/crosstool related.

### Feature requests: what underlying problem are you trying to solve with this feature?

Trying to use compiler-rt with bazel

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build with clang and pass `-rtlib=compiler-rt`

### What operating system are you running Bazel on?

Ubuntu 14.04

### What's the output of `bazel info release`?

release 0.16.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Not a public repo

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

No

**Comment by benjaminp** [comment]
You can pass `--experimental_dont_emit_static_libgcc` to inhibit that.
