### ISSUE TITLE
All tests show up as "exclusive" in the progress report

### ISSUE THREAD

**Issue by bsilver8192** [bazelbuild/bazel#619]
When tests show up in one of the progress reports printed to the console, they always show up under `Running (exclusive):`. That's confusing when they're tests which aren't running exclusively, especially because there's often more than one.

The problem is [com.google.devtools.build.lib.rules.test.TestRunnerAction#describeStrategy](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/test/TestRunnerAction.java#L309) uses `getContext(TestActionContext.class)`, which retrieves an instance of some subclass. That ends up being `ExclusiveTestStrategy` every time I've seen it; not sure if that's luck or not.

Example:
long_test.sh:
```bash
#!/bin/bash

exec sleep 60
```
BUILD:
```python
sh_test(
  name = 'long_test',
  srcs = [ 'long_test.sh' ],
  timeout = 'long',
)
```
```console
$ bazel test //:long_test --progress_report_interval=1
INFO: Found 1 test target...
[3 / 4] Still waiting for 1 job to complete:
      Running (exclusive):
        Testing //:long_test, 5 s
```

**Comment by damienmg** [comment]
I am guessing that's because the timeout is 'long'. I think this is working as intended.

Can you try to replace the timeout to medium ?

@philwo might know if that's WAI. If it is then it should be documented.

**Comment by bsilver8192** [comment]
It happens with any timeout, including not explicitly setting one.

**Comment by damienmg** [comment]
Ok the order of the test strategy is wrong according to @philwo

**Comment by bsilver8192** [comment]
This seems to be fixed with current master. Not sure when it was fixed. The messages show up as `Running (sandbox)` etc as expected.
