### ISSUE TITLE
Make template files directly accessible via bazel

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/bazel#6190]
### Description of the problem / feature request:

[rules_scala][rules_scala] requires a template file that is provided in this repository. Namely, `java_stub_template.txt`. Currently, it fetches this file directly from the GitHub repository. This circumvents potential distribution specific patches that might be required for a functioning bazel installation. See https://github.com/bazelbuild/bazel/pull/5979.

As @aehlig suggested in https://github.com/bazelbuild/bazel/pull/5979#issuecomment-420716543 such files should be made accessible directly via bazel, so that no download from the GitHub repository is necessary, and distribution specific patches do affect such files.

[rules_scala]: https://github.com/bazelbuild/rules_scala

### What operating system are you running Bazel on?

[NixOS 18.03](https://nixos.org/)

### What's the output of `bazel info release`?

`release 0.15.2- (@non-git)`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Using the Nix package of nixpkgs revision 7c826371c492d673eab5a20b185e4ac312deeae5.

**Comment by aiuto** [comment]
Adding team-ExternalDeps, but feel free to reassign or just remove yourselves. It looks like doing this would involve some changes touching a variety of places, so it is not clear who should own it.

**Comment by dslomov** [comment]
@iirina Do you think it is reasonable to export `java_stub_template.txt` from Java rules? It will then become a part of an API.

**Comment by iirina** [comment]
Yes, we can expose the stub to Starlark. This will also be needed when migrating the Java rules to Starlark.

**Comment by ittaiz** [comment]
@katre I think this relates to a discussion in the java BOF in BazelCon in case you were looking for existing issues

**Comment by katre** [comment]
Thanks!
