### ISSUE TITLE
Cross-compiling for Android (arm) is missing debug symbols (-g)

### ISSUE THREAD

**Issue by jgavris** [bazelbuild/bazel#6193]
### Description of the problem / feature request:

According to the [Compilation Mode Docs](https://docs.bazel.build/versions/master/user-manual.html#flag--compilation_mode), building with `--compilation_mode=dbg` should include `--copt=-g` to request debug symbols.

When building for Android (arm), this flag is not passed to the compiler, and debug symbols are missing. When building for Android (x86), host, or iOS, this flag is passed correctly.

It's easy enough to add this to our `bazelrc`, but this behavior is inconsistent across the platforms and contrary to the docs so I thought I'd share. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build an Android app with native library dependencies for arm architecture, observe the compiler invocations for the native library.

`./bazel-debug build //host/Applications/HeliosNativeAndroid/app:Helios  --fat_apk_cpu=arm64-v8a  -s`

### What operating system are you running Bazel on?

macOS 10.13.6

### What's the output of `bazel info release`?

`release 0.17.1`

**Comment by jin** [comment]
Just for completeness, which NDK revision are you on?

**Comment by jgavris** [comment]
@jin r17b
