### ISSUE TITLE
Support per-target sandboxing configurations

### ISSUE THREAD

**Issue by yasushi-saito** [bazelbuild/bazel#6194]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Currently, the location of a temp directory is specified in the --sandbox_tmpfs_path. I want the path to be set on a per-test rule basis.

### Feature requests: what underlying problem are you trying to solve with this feature?

We have a mix of tests that use tmpdir in different ways. Some of them require very fast random accesses over small amount of data (think of tests that sets up mysqld from scratch), and others produce very large amount of data in tmpfs but they are accessed mostly sequentially. We want to use an in-memory tmpfs only for the former class of tests.

Something like

cc_test("blah", ...
  tags = ["tmpfs_path=/dev/shm"],
  ...
}

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

N/A
### What operating system are you running Bazel on?

Linux Ubuntu 16.04

### What's the output of `bazel info release`?

release 0.16.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

Did some search over github.com/bazelbuild and google but this feature doesn't seem to be implemented.

### Any other information, logs, or outputs that you want to share?

N/A

**Comment by jmmv** [comment]
I think this makes sense, but instead of exposing this via tags and leaking platform-specific paths in them, I think it'd make more sense to have a mechanism to describe various properties of the execution environment, not just the tmp path, and then tag each test with the environment they need. And, as a matter of fact, this thing (the basic abstraction) already exists via platforms. @katre Am I right that platforms could help achieve this goal?

**Comment by katre** [comment]
I agree that tags aren't the right way to handle this. I'm not sure that platforms are, either, since the variation in tmpdir is based on the test (the platform-specific part is the specific tmpdir being used).

Would @juliexxia's work on execution groups be useful instead?

**Comment by jmmv** [comment]
Given that we shouldn't use tags, and instead use something more generic, I think it also makes sense to make this bug cover other sandbox-specific settings (like using sandboxfs or not, for example).
