### ISSUE TITLE
Windows 7 Install: WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by pauldelmusica** [bazelbuild/bazel#6197]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\tensorflow-master>cd c:\bazel

c:\bazel>bazel-0.17.1-windows-x86_64.exe
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/C:/U
sers/me/_bazel_me/install/360a69cc0fef41d83a4dd948c0474ca5/_embedded_binaries/A-
server.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of com.google.protobu
f.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflect
ive access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Ba
zel server using the command "bazel shutdown".
                                                          [bazel release 0.17.1]

Usage: bazel <command> <options> ...

Available commands:
  analyze-profile     Analyzes build profile data.
  aquery              Analyzes the given targets and queries the action graph.
  build               Builds the specified targets.
  canonicalize-flags  Canonicalizes a list of bazel options.
  clean               Removes output files and optionally stops the server.
  coverage            Generates code coverage report for specified test targets.

  cquery              Loads, analyzes, and queries the specified targets w/ conf
igurations.
  dump                Dumps the internal state of the bazel server process.
  fetch               Fetches external repositories that are prerequisites to th
e targets.
  help                Prints help for commands, or the index.
  info                Displays runtime info about the bazel server.
  license             Prints the license of this software.
  mobile-install      Installs targets to mobile devices.
  print_action        Prints the command line args for compiling a file.
  query               Executes a dependency graph query.
  run                 Runs the specified target.
  shutdown            Stops the bazel server.
  sync                Syncs all repositories specifed in the workspace file
  test                Builds and runs the specified test targets.
  version             Prints version information for bazel.

Getting more help:
  bazel help <command>
                   Prints help and options for <command>.
  bazel help startup_options
                   Options for the JVM hosting bazel.
  bazel help target-syntax
                   Explains the syntax for specifying targets.
  bazel help info-keys
                   Displays a list of keys used by the info command.

c:\bazel>

**Comment by cushon** [comment]
This is the same issue as #6164.

0.17.2 was recently released, and include fixes for some instances of this problem. Can you try updating to it?

**Comment by cushon** [comment]
Sorry, the fix I was thinking of was efdb3f6874fc1c11525bc66d51c109f9367aed36, which didn't make it into 0.17.2 It should be fixed at head, or in the next release.

Are the warnings causing anything to not work? They should be harmless (but annoying).

**Comment by pauldelmusica** [comment]
Nothing was installed

**Comment by cushon** [comment]
Sorry, I'm not sure I understand: it looks like you successfully installed `bazel`, ran it, and it printed help text with some additional warning spam. What wasn't installed?

**Comment by cushon** [comment]
`bazel-0.17.2-windows-x86_64.exe` is the bazel binary. The installation instructions suggest renaming the executable and moving it somewhere on your path: https://docs.bazel.build/versions/master/install-windows.html#getting-bazel

**Comment by pauldelmusica** [comment]
OK. I see.

I thought it were the installation package.
