### ISSUE TITLE
Should the state of --incompatible_symlinked_sandbox_expands_tree_artifacts_in_runfiles_tree affect the hashes of artifacts?

### ISSUE THREAD

**Issue by mmorearty** [bazelbuild/bazel#6204]
### Description of the problem / feature request:

Bazel 0.17.2 has `--incompatible_symlinked_sandbox_expands_tree_artifacts_in_runfiles_tree`, which is described in the CHANGELOG.md. In short, it's an experimental flag that changes the way the `runfiles` directory works, and it is well known at this point that it has the potential to cause some existing Bazel rules to break. See https://github.com/bazelbuild/bazel/issues/5971 for more detail about potential breakage.

It would be helpful if the state of this flag (true/false) was incorporated into the hash of actions and the artifacts generated by those actions. That way, any Bazel cache (local or remote) would treat the build artifacts with vs without that flag as being different.

### Feature requests: what underlying problem are you trying to solve with this feature?

CHANGELOG.md asks users to try out `--incompatible_symlinked_sandbox_expands_tree_artifacts_in_runfiles_tree`. Currently, I believe that just adding that flag to an existing build may give the appearance of a successful build, because it might just download build artifacts from an earlier build.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Sorry I don't have time to prepare a minimal example. But the basic approach would be:

* Use a remote cache
* Write a Starlark rule that (incorrectly) relies on whether runfiles are symlinks or files
* Do a build
* Do a clean
* Do another build, this time with `--incompatible_symlinked_sandbox_expands_tree_artifacts_in_runfiles_tree`

Expected behavior: The Starlark rule should have different results. Actual behavior: If the cache is being used, it may have had the same results.

### What operating system are you running Bazel on?

macOS and Linux

### What's the output of `bazel info release`?

0.17.2

**Comment by philwo** [comment]
Absolutely, yes! And we should take that we do this for other flags influencing the outputs of an action in the future.

@ulfjack Any idea how we could do so easily? Looks like we already have the "AFFECTS_OUTPUTS" OptionEffectTag, but I'm not sure if we actually use that information when computing action hash keys?

**Comment by ulfjack** [comment]
We don't currently have a mechanism for strategy-specific things to end up in the action cache. Doing so would prevent us from doing cross-strategy caching (if I build something with sandboxing and then without sandboxing, I don't get a cache hit). This would be a problem in general.

**Comment by jmmv** [comment]
I see that the flag was flipped to true in 0.25 but apparently never removed per #7887. Given this, I think we can close this issue.
