### ISSUE TITLE
add a --host_javabase=<jdk8> configuration to buildkite

### ISSUE THREAD

**Issue by cushon** [bazelbuild/bazel#6205]
Can we add test coverage for `--host_javabase=<jdk8>` to buildkite? It's still a supported configuration, but it is currently untested and keeps getting accidentally broken, e.g.:

* https://github.com/bazelbuild/bazel/issues/6203
* https://github.com/bazelbuild/bazel/issues/6159
* https://github.com/bazelbuild/bazel/issues/6164#issuecomment-423059391

Having buildkite configurations for JDK 9 / 10 / no-JDK is great, but currently those are all defaulting to using the embedded JDK 9 as the `--host_javabase`, and only exercising different target `--javabase`s.

The configuration I'm looking for is:

```
--define=ABSOLUTE_JAVABASE=$JAVA8_HOME
--host_javabase=@bazel_tools//tools/jdk:absolute_javabase
--host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
--java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
```

**Comment by philwo** [comment]
Is this LHS or RHS --host_javabase?

**Comment by cushon** [comment]
RHS. (LHS --host_javabase is now --server_javabase.)

--server_javabase coverage would be good to have too, though. Note that --server_javabase=<jdk8> is only supported when using the bazel_nojdk binaries.

**Comment by cushon** [comment]
> Should we test with Java 9 and 10 --host_javabase, too?

--host_javabase=<jdk10> would be nice to have. That should work with the default java_toolchain, e.g. just:

```
--define=ABSOLUTE_JAVABASE=$JAVA8_HOME
--host_javabase=@bazel_tools//tools/jdk:absolute_javabase
```

The default --host_javabase is the embedded JDK 9, so testing with an explicit JDK 9 shouldn't provide a lot of additional coverage. It wouldn't hurt, but I'm not sure it's worth an additional full configuration.
