### ISSUE TITLE
Docker build rule doesn't have tests for directory argument

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#621]
I'm having issues with getting the directory argument in docker_build working, in particular cannot get it to change the output of my build rule at all (when using another tar as input, raw files worked fine). So I tried to lookup the test cases for it to see an example and try and understand why it is not working for me. But there are no tests for it at all which makes it hard to figure out how it is supposed to work.

**Comment by damienmg** [comment]
Wait, I looked at the change that added the support and it added a test: https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/docker/testdata/BUILD#L71

The validation script is at https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/docker/build_test.sh.

Isn't that enough?

**Comment by endobson** [comment]
Yes, but that is not in my local repo that was HEAD two days ago. You are adding features too fast, :).
