### ISSUE TITLE
Error updating remote http_archive when --distdir is set in ~/.bazelrc

### ISSUE THREAD

**Issue by jgennis** [bazelbuild/bazel#6210]
### Description of the problem / feature request:

I'm getting an error using the --distdir command line argument in my ~/.bazelrc file when I update an http_archive that should be fetched from a remote server (i.e. it isn't found in the --distdir directory). It also looks like the bazel server needs to be restarted to detect that --distdir was removed from ~/.bazelrc.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I haven't tried this in isolation, but I think the essential parts of what I'm doing are:

1. Load the http_archive function from "@bazel_tools//tools/build_defs/repo:http.bzl"
2. Create an http_archive that is fetched from a remote https server (in my case called 'fmt').
3. Build something that depends on fmt, causing it to be fetched from the remote server.
4. Create an http_archive that lists a URL for a remote https server, but will actually be fetched from the local distdir (in my case called 'mdk').
5. Add the line "build --distdir=~/build_dist" and put the 'mdk' archive in that directory.
6. Build something that depends on both 'fmt' and 'mdk', causing 'mdk' to be fetched from the local directory.
7. Update the http_archive spec in the WORKSPACE for 'fmt' to fetch a newer version.
8. Build something that depends on both 'fmt' and 'mdk', resulting in the following error:

`ERROR: (...)/BUILD:5:1: no such package '@fmt//': java.io.FileNotFoundException: ~/build_dist/fmt-5.2.1.zip (No such file or directory) and referenced by '...'`

9. Remove the --distdir line from my ~/.bazelrc file.
10. Try to build something that depends on both 'fmt' and 'mdk', resulting in the same error as above.
11. Run 'bazel shutdown', then try to build something that depends on both 'fmt' and 'mdk', which works correctly.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

release 0.17.2

###  Have you found anything relevant by searching the web?

I didn't find other reports of this issue.

**Comment by dslomov** [comment]
> I'm getting an error using the --distdir command line argument in my ~/.bazelrc file when I update an http_archive that should be fetched from a remote server (i.e. it isn't found in the --distdir directory). It also looks like the bazel server needs to be restarted to detect that --distdir was removed from ~/.bazelrc.

This is very suspect: it looks like if the file is missing in `--distdir` we do not download, but fail.

**Comment by aehlig** [comment]
I believe that commits c3bcafb68d7b50ccd3c8f9bf56a9194b887903d0 and 9cc36db79b4ed288235e203bfe419c3adb3894b2 fix the issue. Please reopen, if the problem persists after those two commits.
