### ISSUE TITLE
Support zip64 in //third_party/ijar:zip

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#6211]
A tensorflow issue (https://github.com/tensorflow/tensorflow/issues/22390) revealed bazel's zip tool `//third_party/ijar:zip` doesn't support compressing file that's larger than 4GB.

https://github.com/bazelbuild/bazel/blob/0.17.1/third_party/ijar/zip.cc#L74

/cc @cushon

**Comment by meteorcloudy** [comment]
Yes, I added python zip support using `//third_party/ijar:zip`, because at that time the C++ implementation of singlejar didn't work on Windows. 
An external contributor has been working on https://github.com/bazelbuild/bazel/issues/2241, I'll try to replace zip with singlejar here after it's done.
Thanks for the help!

**Comment by gunan** [comment]
Any updates here?
TF is hitting this again.

**Comment by meteorcloudy** [comment]
@gunan I don't think there is any progress or planned work on this. I thought we have the workaround for TF by excluding deps for py_binary. That doesn't work anymore?

**Comment by gunan** [comment]
Unfortunately, our library's growth has made the workaround not work for us reliably any more.
How difficult do you this is this task? With guidance, do you think someone from our end could od it?

**Comment by meteorcloudy** [comment]
I guess if someone familiar with how zip works can try, I'm not sure how much guidance the Bazel team can provide.

**Comment by AustinSchuhBRT** [comment]
I just ran into this bug, seems like it is still relevant.  @bazelbuild/triage
