### ISSUE TITLE
Two recent commits broke "nojava" platform

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#6214]
Two recent commits broke the "nojava" platform on CI:

Last green build: https://buildkite.com/bazel/bazel-bazel/builds/4629#942cd665-197b-40f5-90a3-b39c461a3a47
First red build: https://buildkite.com/bazel/bazel-bazel/builds/4630#b1d3636d-1f1d-4566-aca0-3e25c67add66

The "bazel_java_test" started failing: https://storage.googleapis.com/bazel-buildkite-artifacts/cbffaf15-4e6b-440c-8c2d-942c92078954/src/test/shell/integration/bazel_java_test/attempt_1.log

A following commit by @lberki completely killed the platform then: 😆 https://github.com/bazelbuild/bazel/commit/cc96464534c770dd9fa14eb2359aae4222420c25

Now almost all tests fail: https://buildkite.com/bazel/bazel-bazel/builds/4637#36a8e86b-1205-4708-b671-3b5e58f8d94b

Example error message: https://storage.googleapis.com/bazel-buildkite-artifacts/36a8e86b-1205-4708-b671-3b5e58f8d94b/src/test/py/bazel/launcher_test/attempt_1.log

(Ignore failures on other platforms - they had a different reason that was already fixed.)

**Comment by cushon** [comment]
Sorry for breaking the build is unfortunate, but I'm not sure there's much to do here besides turn off those tests.

The regressions for the nojava platform were deliberate. From the RELNOTES for cc96464534c770dd9fa14eb2359aae4222420c25:

> If no JDK is found --javabase will be empty, and builds targeting Java will not be supported.  Previously Bazel would fall back to using the embedded JDK as a --javabase, but this is no longer default behaviour. A JDK should be explicitly installed instead to enable Java development.

**Comment by cushon** [comment]
@philwo WDYT about just turning off the nojdk build? The failures are the desired outcome of #6105.

**Comment by philwo** [comment]
Yes, I think that's fine.

However, in addition to that I think we have to carefully consider what kind of installations we want to support in Bazel - for example, should Java builds work on a system without a system JDK, but when specifying a --host_javabase / --javabase that's checked into the user's repo or that comes from an external repo? So maybe we have to add a pipeline config for that case, too.

**Comment by philwo** [comment]
For reference, here's the list of broken tests (links go to log files):

- [//src/test/py/bazel:launcher_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/py/bazel/launcher_test/attempt_1.log)
- [//src/test/py/bazel:runfiles_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/py/bazel/runfiles_test/attempt_1.log)
- [//src/test/shell/bazel:bazel_coverage_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/shell/bazel/bazel_coverage_test/attempt_1.log)
- [//src/test/shell/bazel:bazel_determinism_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/shell/bazel/bazel_determinism_test/attempt_1.log)
- [//src/test/shell/bazel:bazel_example_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/shell/bazel/bazel_example_test/attempt_1.log)
- [//src/test/shell/bazel:bazel_random_characters_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/shell/bazel/bazel_random_characters_test/attempt_1.log)
- [//src/test/shell/bazel:bazel_rules_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/shell/bazel/bazel_rules_test/attempt_1.log)
- [//src/test/shell/bazel:bazel_sandboxing_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/shell/bazel/bazel_sandboxing_test/attempt_1.log)
- [//src/test/shell/bazel:bazel_test_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/shell/bazel/bazel_test_test/attempt_1.log)
- [//src/test/shell/bazel:empty_package_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/shell/bazel/empty_package_test/attempt_1.log)
- [//src/test/shell/bazel:java_launcher_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/shell/bazel/java_launcher_test/attempt_1.log)
- [//src/test/shell/bazel:local_repository_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/shell/bazel/local_repository_test/attempt_1.log)
- [//src/test/shell/bazel:maven_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/shell/bazel/maven_test/attempt_1.log)
- [//src/test/shell/bazel:runfiles_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/shell/bazel/runfiles_test/attempt_1.log)
- [//src/test/shell/integration:bazel_java_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/shell/integration/bazel_java_test/attempt_1.log)
- [//src/test/shell/integration:bazel_sandboxed_worker_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/shell/integration/bazel_sandboxed_worker_test/attempt_1.log)
- [//src/test/shell/integration:bazel_worker_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/shell/integration/bazel_worker_test/attempt_1.log)
- [//src/test/shell/integration:discard_analysis_cache_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/shell/integration/discard_analysis_cache_test/attempt_1.log)
- [//src/test/shell/integration:java_integration_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/shell/integration/java_integration_test/attempt_1.log)
- [//src/test/shell/integration:output_filter_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/shell/integration/output_filter_test/attempt_1.log)
- [//src/test/shell/integration:stub_finds_runfiles_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/shell/integration/stub_finds_runfiles_test/attempt_1.log)
- [//src/test/shell/integration:test_test](https://storage.googleapis.com/bazel-buildkite-artifacts/8b66c620-3a46-4fc1-9fa4-b0d4fbfdd0fc/src/test/shell/integration/test_test/attempt_1.log)

**Comment by philwo** [comment]
Thinking about it: We can't easily test anything meaningful on that platform, because the "bazel" that is run on that pipeline is of course the latest released version of Bazel, not the Bazel built from a given commit. Thus, running "bazel build //example/cpp/..." only tells us that the latest release Bazel is still able to compile C++ on that platform. Nice to know, but not what we wanted to test.

What we want to test is that the Bazel *built at this commit* can still build C++. However, we can't build Bazel itself, because we don't have a JDK. 😅 Also our usual integration tests will not work, because they build Bazel as a dependency and that also needs an installed JDK.

**Comment by lberki** [comment]
Well, that's a very compelling argument indeed.

**Comment by cushon** [comment]
You could explicitly configure there to not be a `--javabase` when running the c++ tests: `--define=ABSOLUTE_JAVABASE=/not/a/JDK --host_javabase=@bazel_tools//tools/jdk:absolute_javabase --javabase=@bazel_tools//tools/jdk:absolute_javabase`.

**Comment by jin** [comment]
this is P0 issue, right?

**Comment by cushon** [comment]
> this is P0 issue, right?

probably? it'd be nice to get the post-submit unbroken.

is this blocked on anything?

**Comment by lberki** [comment]
So the decision is to remove the nojava builds?

**Comment by philwo** [comment]
First thing: You should have decided what to do *before* you broke it ;)

It’s a product decision not a technical one: Do we still support using Bazel (for any purpose) on a system that doesn’t have an installed JDK? If yes, we need to test that.

If not, we can of course remove the nojava platform.

**Comment by cushon** [comment]
> You should have decided what to do before you broke it ;)

Somewhat relatedly, why didn't this breakage get caught by the presubmit?

**Comment by lberki** [comment]
@philwo : I thought you said that we can't test this with the current infrastructure and that you said on Thursday that you'd try to cook up something to build Bazel on one system, but test it on another.

If that doesn't work, I'd prefer not having the `nojava` platform -- after all, it's broken at HEAD and there are no plans to unbreak it, so it doesn't deliver any signal.

**Comment by philwo** [comment]
To be clear: Are you making the decision to no longer support Bazel (even for C++ or genrules) on Systems without an installed JDK?

**Comment by lberki** [comment]
To clarify: not having the `nojava` tests would be awful awful. But if we had to choose between removing `nojava` tests and defaulting to the embedded JDK, I'd much rather choose the former.

However, @philwo says that I severely overestimated the pain involved in making `nojava` work, so I think all is well.

**Comment by philwo** [comment]
Some more failing tests that I'll blacklist:

- [//src/test/shell/bazel:bazel_repository_cache_test](https://storage.googleapis.com/bazel-buildkite-artifacts/e92dcf2b-b9c7-4145-ae6d-bafdb0ce53ee/src/test/shell/bazel/bazel_repository_cache_test/attempt_1.log)
- [//src/test/shell/bazel:external_integration_test](https://storage.googleapis.com/bazel-buildkite-artifacts/e92dcf2b-b9c7-4145-ae6d-bafdb0ce53ee/src/test/shell/bazel/external_integration_test/attempt_1.log)
- [//src/test/shell/integration:discard_graph_edges_test](https://storage.googleapis.com/bazel-buildkite-artifacts/e92dcf2b-b9c7-4145-ae6d-bafdb0ce53ee/src/test/shell/integration/discard_graph_edges_test/attempt_1.log)
- [//src/test/shell/integration:nonincremental_builds_test](https://storage.googleapis.com/bazel-buildkite-artifacts/e92dcf2b-b9c7-4145-ae6d-bafdb0ce53ee/src/test/shell/integration/nonincremental_builds_test/attempt_1.log)

**Comment by philwo** [comment]
Fixed in https://github.com/bazelbuild/bazel/commit/9bc3b20053a8b99bf2c4a31323a7f96fabb9f1ec

**Comment by philwo** [comment]
> Somewhat relatedly, why didn't this breakage get caught by the presubmit?

@cushon We unfortunately ran out of Google Cloud quota and couldn't run enough VMs to run all the platforms during presubmit... 

I organized us more quota and enabled all tests on all platforms again yesterday, so in the future we should catch this. :)
