### ISSUE TITLE
generate_workspace should be provided as an easy tools to run

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#622]
Maybe ship it in the bazel_tools repository so user can just bazel run @bazel_tools//generate_workspace from any workpsace

@kchodorow might have good idea on the ideal way to provide it to the user.

**Comment by davidzchen** [comment]
This sounds like a simple approach, but I feel that `bazel run @bazel_tools//generate_workspace` is a rather long command. Are there any ways we can make this shorter?

**Comment by davidstanke** [comment]
@dslomov -- can you comment on how this relates to the deps work you're doing? (And close this bug if it's no longer useful)

**Comment by jin** [comment]
generate_workspace has been deprecated. Please use [rules_jvm_external](https://github.com/bazelbuild/rules_jvm_external) instead.
