### ISSUE TITLE
C shared libraries depend on libstdc++

### ISSUE THREAD

**Issue by brown** [bazelbuild/bazel#6221]
### Description of the problem / feature request:

When I build C shard libraries, they end up having a dependency on libstdg++.so.6.
I have not figured out a way to remove this dependency.

### Feature requests: what underlying problem are you trying to solve with this feature?

I want to build a shard library from C code that does not depend on libstdc++.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a C library with Bazel's cc_binary rule.  Set linkshard = True in the BUILD file.  Run ldd
on the created shared object.  You'll see is has a dependency on libstdc++.so.6.

### What operating system are you running Bazel on?

Linux.

### What's the output of `bazel info release`?

development version
It's 0.15.0 with a couple of patches.

### Any other information, logs, or outputs that you want to share?

Go folks have worked around this problem
https://github.com/bazelbuild/rules_go/issues/1681

**Comment by petroseskinder** [comment]
@hlopko @iirina any updates on this?

**Comment by hlopko** [comment]
Hi all,

nope, no updates. Work on C-only builds has been postponed after Bazel 1.0. That means that we're unlikely to work on it in next 2 quarters, maybe more.

Very ugly workaround, if you don't build any C++, is to set `BAZEL_LINKOPTS` (https://source.bazel.build/bazel/+/7d5db9a8a925fe6cbc7e6b4e585eaca3935ff63a:tools/cpp/unix_cc_configure.bzl;l=381) environment variable to e.g. "-lm" (current bazel release will crash if you set it to empty string).

Less ugly solution would be to have `-lstdc++` in a crosstool feature, and enable that feature from your cc_binary target. I'd accept a PR for this.

The nicest solution would be if bazel detected that there are no C++ deps in the transitive closure, and then not add the `-lstdc++` automatically. That's how I'd solve this problem if I had capacity, and that's what we'll do in the future.

**Comment by meisterT** [comment]
cc @oquenchil
