### ISSUE TITLE
cc_test in an external repository fails to run when using `--nolegacy_external_runfiles`

### ISSUE THREAD

**Issue by det** [bazelbuild/bazel#6222]
### Description of the problem / feature request:

cc_test in an external repository fails to run when using `--nolegacy_external_runfiles`

### Feature requests: what underlying problem are you trying to solve with this feature?

When running bazel test the following error occurs:
`external/bazel_tools/tools/test/test-setup.sh: line 261: : command not found`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a cc_test in an external repository with an empty main and run `bazel test @repository//:test --nolegacy_external_runfiles`

### What operating system are you running Bazel on?

Ubuntu 14.04

### What's the output of `bazel info release`?

release 0.17.2

###  Have you found anything relevant by searching the web?

No

**Comment by hlopko** [comment]
Is this still valid with bazel 0.21?

**Comment by det** [comment]
This is still broken in bazel 0.25 at least

**Comment by hlopko** [comment]
Seems it is fixed for 0.26 and later: https://github.com/bazelbuild/bazel/issues/8088
