### ISSUE TITLE
Some environment variables not passed to persistent workers

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#6223]
I'm working on creating a persistent worker to support incremental compilation [for Swift](https://github.com/bazelbuild/rules_swift/issues/48). In doing so, the first issue I hit, was the lack of required environment variables being passed to the newly created persistent workers.

When running the builds normally, this is the environment passed to the build:

```
DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
TMPDIR=/var/folders/5b/bs2_gmk512147rfb9c6278f80000gp/T/
SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk
XCODE_VERSION_OVERRIDE=10.0.0
__CF_USER_TEXT_ENCODING=0x1F6:0x0:0x0
PWD=/private/var/tmp/_bazel_...
SHLVL=1
APPLE_SDK_PLATFORM=iPhoneSimulator
APPLE_SDK_VERSION_OVERRIDE=12.0
```

But the persistent workers are launched with this environment:

```
XCODE_VERSION_OVERRIDE=10.0.0
PWD=/private/var/tmp/_bazel_...
SHLVL=1
APPLE_SDK_PLATFORM=iPhoneSimulator
APPLE_SDK_VERSION_OVERRIDE=12.0
```

This results in the underlying [script](https://github.com/bazelbuild/rules_swift/blob/c8138ccf8cd798aefc9533840fcab72546e4c46c/tools/wrappers/xcrunwrapper.sh#L38) to fail since `SDKROOT` is required but not defined.

Is this variable intentionally excluded from persistent workers? Or is there a place we need to whitelist this variable to be passed along? I am testing with bazel 0.17.1

**Comment by keith** [comment]
`DEVELOPER_DIR` is also missing from the persistent worker env here

**Comment by keith** [comment]
Ok I think I discovered why this is the case. When building locally we hit this codepath: https://github.com/bazelbuild/bazel/blob/18bd7dec9609ff8924d9ebed5f14be523df4eec0/src/main/java/com/google/devtools/build/lib/sandbox/DarwinSandboxedSpawnRunner.java#L224-L225 which adds the variables we want from here https://github.com/bazelbuild/bazel/blob/1f684e1b87cd8881a0a4b33e86ba66743e32d674/src/main/java/com/google/devtools/build/lib/exec/apple/XcodeLocalEnvProvider.java#L66-L108 but persistent workers don't call this local env rewrite logic https://github.com/bazelbuild/bazel/blob/5a1ed1f24e74f8a608ee145133f399c1f34a8390/src/main/java/com/google/devtools/build/lib/worker/WorkerSpawnRunner.java#L131 meaning they don't add the variables we were hoping for.

I'm not really sure what an acceptable solution for this is since I don't think normally we'd want to pass persistent workers the local environment logic, but in this case it's required for quite a few arguments.

**Comment by keith** [comment]
@allevato assuming you have some context on these, any thoughts?

**Comment by allevato** [comment]
I've run into the same problem in my worker prototype, and my solution was to hack it by having my wrapper set DEVELOPER_DIR and SDKROOT by querying xcode-select/xcrun manually if they're not already set. Not ideal.

**Comment by buchgr** [comment]
Sounds like a problem with persistent workers. @keith wanna send us a patch? :-) cc: @philwo

**Comment by keith** [comment]
@buchgr I'm happy to submit that fix, but is that a reasonable one? Just based on the naming tying the local environment objects to the persistent workers sounds like they're intentionally attached

**Comment by keith** [comment]
I've submitted a PR that fixes it in this way, please let me know what you think! https://github.com/bazelbuild/bazel/pull/6287
