### ISSUE TITLE
No way to disable the repository cache

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#6229]
Ever since the repository cache was made the default, it's been impossible to disable. I would like some way to turn it off on the command line.

Here's why I'd like to disable it: For every archive, the repository cache and every workspace end up with a copy. Thus, the repository cache is a pessimization if only one workspace is ever going to use a given output user base.

**Comment by ittaiz** [comment]
Do you know there’s an (experimental) flag to hardlink from the repository
cache to the workspace one?
This doesn’t mean you’re not right but just trying to unblock you.
Also note there is a separate more general issue about unsetting command
line flags.

**Comment by benjaminp** [comment]
Hardlinks and the fact that the repository cache `touch`es cache files on hit cause unnecessary work on COW filesystems like overlayfs.

**Comment by buchgr** [comment]
@aehlig as the owner of the repository cache.

**Comment by aehlig** [comment]
> Here's why I'd like to disable it: For every archive, the repository cache and every workspace end up with a copy. Thus, the repository cache is a pessimization if only one workspace is ever going to use a given output user base.

I'm not sure I understand that comment. The default repository cache is shared between workspaces.

**Comment by benjaminp** [comment]
Sorry for not being clear. What I meant is that if I know there's only ever going to be one workspace, the repository cache is a waste because you end up with two copies of all archives.

**Comment by aehlig** [comment]
> Sorry  for not being clear. What I meant is that if I know there's only ever  going to be one workspace, the repository cache is a waste because you  end up with two copies of all archives.

...provided you never have to reexecute a repository rule, e.g., because you modified the programatic transformations.

Thanks for the clarification. I'll see if it is possible to add the possibility to optionally disable the cache.
