### ISSUE TITLE
toolchain type is not documented

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#6233]
Apparently, there's a rule in BUILD files called `toolchain type`, but I don't see it in the documentation.

https://docs.bazel.build/versions/master/be/overview.html

**Comment by brandjon** [comment]
Adding myself due to other related doc cleanups, but I finished this particular push for docs so I may not get to this. Note that the use of toolchain_type is described on the toolchains.html page.

**Comment by aiuto** [comment]
It must have been added sometime in the last year https://docs.bazel.build/versions/master/be/platform.html#toolchain_type

**Comment by brandjon** [comment]
I think it was part of the recent doc fixit.

**Comment by katre** [comment]
I didn't realize #3691 had a dupe, this was fixed in 6694f8a4bc9a2c6a8d2f70f2fc97837732949423.
