### ISSUE TITLE
Improve in-build Starlark Testing

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#6237]
This is a tracking issue for work proposed in Improving [In-Build Starlark Testing
](https://docs.google.com/document/d/17P2sgC6VPmcA7CcqC2p4cfU2Kaj6dwKiQfIXhtXTzl4).

**Comment by c-parsons** [comment]
This is mostly done, but there are a couple of items that need fixing, so I will leave this open to track:

1. The analysis_test_deps_limit limit should only apply to analysis test rules which use an analysis test transition. They currently apply to all analysis_test.
2. In lenient-analysis-failures mode, targets which fail (and thus propagate AnalysisFailureInfo) should result in all dependers also fast-failing with AnalysisFailureInfo. This was the proposal in the design, but it is currently not so.

**Comment by katre** [comment]
@c-parsons Is there any remaining work here?

**Comment by c-parsons** [comment]
I believe we can close this, and track any issues with this framework in different bugs :)
