### ISSUE TITLE
No "multiple definition of main" linker error on Linux when multiple deps provides it

### ISSUE THREAD

**Issue by 10or10** [bazelbuild/bazel#6238]
### Description of the problem / feature request:

Multiple definitions of main in the same cc_test should trigger an linker error.

### Feature requests: what underlying problem are you trying to solve with this feature?

Avoid arbitrary (?) selection of main function when multiple dependencies provide a main function.

The order seem to be main-functions in srcs is selected before dependencies (which in turn seem to be selected in order if no main is provided in srcs)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create two cc_libraries with implementation files containing (among other functions) main functions, include them as dependencies in a cc_test. 

See attach files:
`bazel build //...` succeeds despite dependencies containing multiple main functions
`bazel test //...` fails, selects main functions dependent on order (src > deps 1 > deps 2)?

### What operating system are you running Bazel on?
Linux

### What's the output of `bazel info release`?

release 0.17.2

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

This issue occurred when test cpp files (using googletest, but not implementing own main function) had dependencies to cc_libraries consisting of cryptopp (contains a main function a test.cpp) and gtest:main, and the cryptopp test.cpp's main function was selected in some cc_tests but not for all.

[foobar.tar.gz](https://github.com/bazelbuild/bazel/files/2416776/foobar.tar.gz)

**Comment by benjaminp** [comment]
This is just a reflection of the fact that Bazel links binaries dynamically by default and the Linux dynamic linking behavior. If you pass `--dynamic_mode=off` or set `linkstatic = True` in the `cc_test` rules, the linker will fail.

**Comment by iirina** [comment]
I'll close this as Benjamin addressed the question.
