### ISSUE TITLE
Tracking issue for Starlark Rule Output API changes

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#6241]
This will serve as a tracking issue for the proposal found at [Fixing Starlark Rule Outputs](https://docs.google.com/document/d/14A9HK8Jn2jErMayLEE3nrNJIxNfZWN_slFbhgtS6-aM)
(attached to semantics flag `--incompatible_outputs_api`)

**Comment by laurentlb** [comment]
Is it migration-ready?
When it is, the issue title should start with the flag name (if there are multiple flags, create multiple issues).

**Comment by laurentlb** [comment]
Shall we close this bug?

**Comment by c-parsons** [comment]
Sure -- the other issues I've opened should track the remaining work.
