### ISSUE TITLE
genrule with the same name as an input file leads to circular dependency error

### ISSUE THREAD

**Issue by bsilver8192** [bazelbuild/bazel#626]
A genrule which has an input file with its own name leads to a circular dependency error, but I'm pretty sure it shouldn't. People are running into this trying to build TensorFlow (like #623).

Really simple example: `WORKSPACE` and `file` are empty, BUILD is:
```python
genrule(
  name = 'file',
  srcs = [ 'file' ],
  outs = [ 'abc' ],
  cmd = 'touch $@',
)
```
```console
$ bazel build //...
ERROR: /tmp/test_circular_workspace/BUILD:1:1: in genrule rule //:file: cycle in dependency graph:
  * //:file [self-edge].
ERROR: Loading of target '//:file' failed; build aborted.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 0.396s.
```

**Comment by ulfjack** [comment]
Srcs does _not_ refer to files in the source tree, but to labels, which may be generated files or rules. For example, it could refer to the name of another genrule, in which case the output files of that genrule are treated as the srcs of this genrule.

Blaze originally had separate name spaces for files and rules, but that was much more unintuitive and error prone. This is working as designed, and the genrule (or the file) needs to be changed to have a different name.
