### ISSUE TITLE
--action_env not documented in the user manual

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#6264]
`--test_env` is documented on https://docs.bazel.build/versions/master/user-manual.html, but `--action_env` isn't.

**Comment by jin** [comment]
Seems like it's a bug that [none of the options](https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/config/BuildConfiguration.java;l=575;bpv=;bpt=1) declared in `BuildConfiguration` is generated on the user manual. Bumping to P1.

**Comment by dslomov** [comment]
@jmmv please consider reprioritising it, `--action_env` is an important flag that users are often confused about. /cc @aehlig @buchgr
