### ISSUE TITLE
`repository_rule` should have a `doc` argument

### ISSUE THREAD

**Issue by Profpatsch** [bazelbuild/bazel#6271]
`repository_rule` is similar to `rule`, except it lives on the `WORKSPACE` level. `rule` has a nice `doc` attribute which is extracted by documentation tools. It would be nice if `repository_rule` followed suit.

In [`rules_nixpkgs`](https://github.com/tweag/rules_nixpkgs) and [`rules_haskell`](https://github.com/tweag/rules_haskell) we have to resort to [manually written docs](https://github.com/tweag/rules_nixpkgs/blob/master/README.md#rules-1), which tend go out of sync easily.

**Comment by dslomov** [comment]
Sounds like a great idea!

**Comment by jmillikin** [comment]
Just hit this too. It looks like the fix is trivial (adding a no-op `doc` parameter), so I've mailed https://github.com/bazelbuild/bazel/pull/6936 . Note that rules using this param won't work with any older Bazel versions.
