### ISSUE TITLE
Document passing credentials in non-standard locations to maven_server

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/bazel#6280]
### Description of the problem / feature request:

We are using the native `maven_jar` and `maven_server` rules to fetch JAR artifacts from maven servers which require credentials. E.g.

```
maven_server(
    name = "my_repo",
    url = ...
)
maven_jar(
    name = "my_artifact",
    artifact = ...,
    sha1 = ...,
    server = "my_repo"
)
```

If `~/.m2/settings.xml` exists and contains an entry with id `my_repo` then this will read the credentials from that config file.

However, in the CI environment the credentials are provisioned under a non-standard path. Say, under an unknown path which is assigned to the environment variable `MY_MAVEN_CREDENTIALS`. The [documentation to `maven_server`](https://docs.bazel.build/versions/master/be/workspace.html#maven_server.settings_file) says that the default behavior is to look for settings files in `$M2_HOME/conf/settings.xml` and `$HOME/.m2/settings.xml`. Alternatively, the `settings_file` attribute can be set to the path to the settings file.

However, the documentation fails to explain how to read such a path from an environment variable, say `$MY_MAVEN_CREDENTIALS` and then assign it to the attribute `settings_file`. In particular, in a way that falls back to the standard behavior if the environment variable is not defined.

### Feature requests: what underlying problem are you trying to solve with this feature?

Please, extend the documentation to cover how to read a path to a configuration file from the environment and pass it to an attribute such as `settings_file` to `maven_server` in a use-case such as the above.

Having credentials provisioned in non-standard locations in CI seems like a common use-case.

---

cc @gdeest

**Comment by jin** [comment]
maven_jar has been deleted from Bazel. Closing.
