### ISSUE TITLE
Links to macos_unit_test, ios_unit_test, and ios_ui_test point to 404

### ISSUE THREAD

**Issue by khandpur** [bazelbuild/bazel#6285]
### Description of the problem / feature request:
Rule links in https://docs.bazel.build/versions/master/migrate-xcode.html#step-3b-optional-add-the-test-target-s point to 404.

### Feature requests: what underlying problem are you trying to solve with this feature?
N/A

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Go to https://docs.bazel.build/versions/master/migrate-xcode.html#step-3b-optional-add-the-test-target-s and click on the rules link.

### What operating system are you running Bazel on?
Mac High-Sierra 10.13.6

### What's the output of `bazel info release`?
N/A

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.
N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
N/A

###  Have you found anything relevant by searching the web?
N/A

>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by tetromino** [comment]
Thanks for your report!

This looks like a bug in the jekyll config that we use to transform our docs (in this case, site/docs/migrate-xcode.md) into html for the bazel.build website.

I have filed an issue internally.

**Comment by philwo** [comment]
@tetromino Can you please link to the internal issue (just b/123456 is fine)?

**Comment by tetromino** [comment]
b/117147486

**Comment by tetromino** [comment]
We really need to fix this - sorry for dropping the ball here.

**Comment by tetromino** [comment]
Hmm, links in the docs are still wrong,  :/

Maybe we don't correctly specify conditions under which the docs need to be regenerated.

**Comment by tetromino** [comment]
Docs got regenerated, links are fixed :)
