### ISSUE TITLE
Java binary with long classpath fails on read-only file system

### ISSUE THREAD

**Issue by brown** [bazelbuild/bazel#6289]
### Description of the problem / feature request:

When a Java binary's classpath is too long, the wrapper script creates manifest and jar
files containing the classpath.  The wrapper writes these files to the directory containing
the wrapper.  This fails when the binary is run from a read-only file system.

### Feature requests: what underlying problem are you trying to solve with this feature?

Allowing a Bazel compiled Java binary or test to run from a read-only file system or from
a directory that's not writable.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run a Java binary or test with a classpath that exceeds the limit (roughly 120K) on a read-only
file system.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

development version

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

bazel build src:bazel-bin
The version with the bug is 0.15.0

### Any other information, logs, or outputs that you want to share?

The following patch to the wrapper should fix the problem.

```diff
***************
*** 303,313 ****
    done
    unset IFS

-   RAND_ID=$(cat /dev/urandom | head -c 128 | md5func)
    # Create manifest file
!   MANIFEST_FILE="${self}-${RAND_ID}.jar_manifest"
! 
!   echo "Manifest-Version: 1.0" >$MANIFEST_FILE
    CLASSPATH_LINE="Class-Path:$MANIFEST_CLASSPATH"
    # No line in the MANIFEST.MF file may be longer than 72 bytes.
    # A space prefix indicates the line is still the content of the last attribute.
--- 303,311 ----
    done
    unset IFS

    # Create manifest file
!   MANIFEST_FILE=$(mktemp)
!   echo "Manifest-Version: 1.0" > "$MANIFEST_FILE"
    CLASSPATH_LINE="Class-Path:$MANIFEST_CLASSPATH"
    # No line in the MANIFEST.MF file may be longer than 72 bytes.
    # A space prefix indicates the line is still the content of the last attribute.
***************
*** 316,327 ****
      if (($i == 0)); then
        PREFIX=""
      fi
!     echo "$PREFIX${CLASSPATH_LINE:$i:71}" >>$MANIFEST_FILE
    done
!   echo "Created-By: Bazel" >>$MANIFEST_FILE

    # Create classpath JAR file
!   MANIFEST_JAR_FILE="${self}-${RAND_ID}-classpath.jar"
    if is_windows; then
      MANIFEST_JAR_FILE="$(cygpath --windows "$MANIFEST_JAR_FILE")"
      MANIFEST_FILE="$(cygpath --windows "$MANIFEST_FILE")"
--- 314,325 ----
      if (($i == 0)); then
        PREFIX=""
      fi
!     echo "$PREFIX${CLASSPATH_LINE:$i:71}" >> "$MANIFEST_FILE"
    done
!   echo "Created-By: Bazel" >> "$MANIFEST_FILE"

    # Create classpath JAR file
!   MANIFEST_JAR_FILE=$(mktemp)
    if is_windows; then
      MANIFEST_JAR_FILE="$(cygpath --windows "$MANIFEST_JAR_FILE")"
      MANIFEST_FILE="$(cygpath --windows "$MANIFEST_FILE")"
```

**Comment by cushon** [comment]
@meteorcloudy can you take a look, as the author of 752b61ee4d839b6b9680353c0d1d02de2ad13f14?

@brown's solution LGTM but you have more context.

**Comment by meteorcloudy** [comment]
Sorry, I don't quite understand the patch. Does it just avoid creating the classpath jar? Then how could the correct classpath be set?

**Comment by cushon** [comment]
I think the crux of it is using `MANIFEST_FILE=$(mktemp)` instead of `MANIFEST_FILE="${self}-${RAND_ID}.jar_manifest"`, since the latter assumes the output tree is writeable.

The patch doesn't apply cleanly at head, I had to sync back to 6ee36ef239b25f66afa83e2657bd0b529b1ff50e. Was it developed against a fairly old version of Bazel?

Here's a unified diff version in case that's easier to read:

```diff
diff --git a/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt b/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt
index dbe84b4fae..0bc3ef2261 100644
--- a/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt
+++ b/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt
@@ -300,11 +300,9 @@ function create_and_run_classpath_jar() {
   done
   unset IFS
 
-  RAND_ID=$(cat /dev/urandom | head -c 128 | md5func)
   # Create manifest file
-  MANIFEST_FILE="${self}-${RAND_ID}.jar_manifest"
-
-  echo "Manifest-Version: 1.0" >$MANIFEST_FILE
+  MANIFEST_FILE=$(mktemp)
+  echo "Manifest-Version: 1.0" > "$MANIFEST_FILE"
   CLASSPATH_LINE="Class-Path:$MANIFEST_CLASSPATH"
   # No line in the MANIFEST.MF file may be longer than 72 bytes.
   # A space prefix indicates the line is still the content of the last attribute.
@@ -313,12 +311,12 @@ function create_and_run_classpath_jar() {
     if (($i == 0)); then
       PREFIX=""
     fi
-    echo "$PREFIX${CLASSPATH_LINE:$i:71}" >>$MANIFEST_FILE
+    echo "$PREFIX${CLASSPATH_LINE:$i:71}" >> "$MANIFEST_FILE"
   done
-  echo "Created-By: Bazel" >>$MANIFEST_FILE
+  echo "Created-By: Bazel" >> "$MANIFEST_FILE"
 
   # Create classpath JAR file
-  MANIFEST_JAR_FILE="${self}-${RAND_ID}-classpath.jar"
+  MANIFEST_JAR_FILE=$(mktemp)
   if is_windows; then
     MANIFEST_JAR_FILE="$(cygpath --windows "$MANIFEST_JAR_FILE")"
     MANIFEST_FILE="$(cygpath --windows "$MANIFEST_FILE")"
```

**Comment by meteorcloudy** [comment]
@cushon Thanks for the explanation! Now it makes sense.
Can you send this as a PR or CL? Happy to review it!

**Comment by brown** [comment]
I created a pull request:  https://github.com/bazelbuild/bazel/pull/6471

**Comment by laszlocsomor** [comment]
IIUC https://github.com/bazelbuild/bazel/pull/6471 should have closed this bug, correct?

**Comment by meteorcloudy** [comment]
Yes, #6471 should fix this.
