### ISSUE TITLE
maven_server disallows valid maven repository names

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/bazel#6291]
### Description of the problem:

The `maven_server` rule can be used to specify a maven repository in a way that allows to handle authentication credentials. The `name` attribute to `maven_server` then needs to match the `id` of the repository in the maven `settings.xml` in order to associate the two. However, this `name` attribute also needs to be a valid workspace name. Presumably, due to implementation details of the `maven_server` rule. However, maven's `settings.xml` allows ids that are not valid workspace names. For example, in an environment where `settings.xml` configures `my-repo` (with a dash), the following Bazel code will fail

```
maven_server(
    name = "my-repo",
    url = ...
)
maven_jar(
    name = "a:b:1.2.3",
    artifact = ...,
    sha1 = ...,
    server = "my-repo"
)
```

with the error message 

```
maven_server rule //external:my-repo's name field must be a legal workspace name
```

`maven_server` should allow the same set of repository names that maven's `settings.xml` allows. Incompatibilities with workspace name restrictions should be handled internally by `maven_server`.

---

cc @gdeest

**Comment by regisd** [comment]
"my-repo" is not a valid name. Use "my_repo" instead.

**Comment by aherrmann** [comment]
@dslomov  Yes, that sounds like a good solution. It could default to `name` to make this backwards compatible.

**Comment by jin** [comment]
maven_server has been deleted.
