### ISSUE TITLE
Support NDK r19

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#6297]
Expected release: Q4 2018

Changes: https://android.googlesource.com/platform/ndk/+/master/docs/Roadmap.md#ndk-r19

* Make all toolchains be standalone toolchains

> Now that the NDK is down to a single compiler and STL, if we just taught the Clang driver to emit -D__ANDROID_API__=foo and to link libc.so.18 instead of libc.so, standalone toolchains would be obsolete because the compiler would already be a standalone toolchain. The NDK toolchain would Just Work regardless of build system, and the logic contained in each build system could be greatly reduced.

> Related to this (but maybe occurring in a later release), we'll want to switch from libgcc to libcompiler-rt and our own unwinder.

> See the corresponding bug make all toolchains standalone toolchains for detailed discussion of the implementation and sub-tasks.

**Comment by jin** [comment]
r19 beta 2 is available, r19 is expected to ship soon.

https://developer.android.com/ndk/downloads/

**Comment by jin** [comment]
NDK 19 has dropped: https://developer.android.com/ndk/downloads/#stable-downloads

**Comment by jin** [comment]
Link to changelog: https://github.com/android-ndk/ndk/wiki/Changelog-r19

**Comment by jin** [comment]
After speaking with @hlopko, the right way forward here is to implement the NDK CROSSTOOL in Starlark. This isn't a necessary blocker for NDK 19, since we can adapt the NDK 18 configuration for 19, but it would be nice to turn down proto CROSSTOOL generation to move to the modern approach.

@hlopko's suggestion:

> write a rule ndk_cc_toolchain_config that has attributes for things that are different between versions, and only instantiate that in BUILD files.

More information: 

- https://github.com/bazelbuild/bazel/issues/7320
- https://docs.bazel.build/versions/master/cc-toolchain-config-reference.html

**Comment by steeve** [comment]
@jin do you plan on supporting `lld` too ?

**Comment by jin** [comment]
@steeve definitely. We want the Android rules to be 100% compatible with the recommended set of tools in the NDK.

**Comment by jin** [comment]
The NDK CROSSTOOL has been ported to Starlark with massive help from @hlopko - thanks!

Going through the changelog:

> Developers should begin testing their apps with LLD. AOSP has switched to using LLD by default and the NDK will use it by default in the next release. BFD and Gold will be removed once LLD has been through a release cycle with no major unresolved issues (estimated r21). Test LLD in your app by passing -fuse-ld=lld when linking.
 
> Note: lld does not currently support compressed symbols on Windows. See Issue 888. Clang also cannot generate compressed symbols on Windows, but this can be a problem when using artifacts built from Darwin or Linux.

We will need to add support for this.

> The Play Store will require 64-bit support when uploading an APK beginning in August 2019. Start porting now to avoid surprises when the time comes. For more information, see this blog post.

We may want to add a warning message about this when building for non-64-bit.

> Issue 780: Standalone toolchains are now unnecessary. Clang, binutils, the sysroot, and other toolchain pieces are now all installed to $NDK/toolchains/llvm/prebuilt/<host-tag> and Clang will automatically find them. Instead of creating a standalone toolchain for API 26 ARM, instead invoke the compiler directly from the NDK:
> 
> $ $NDK/toolchains/llvm/prebuilt/<host-tag>/bin/armv7a-linux-androideabi26-clang++ src.cpp
> For r19 the toolchain is also installed to the old path to give build systems a chance to adapt to the new layout. The old paths will be removed in r20.

We must definitely support this, but the effects of it should be transparent to end users. It's not clear what the impact of having a standalone toolchain will be on the Starlark crosstool configuration.
 
> The make_standalone_toolchain.py script will not be removed. It is now unnecessary and will emit a warning with the above information, but the script will remain to preserve existing workflows.

Not applicable, we don't use this.

> If you're using ndk-build, CMake, or a standalone toolchain, there should be no change to your workflow. This change is meaningful for maintainers of third-party build systems, who should now be able to delete some Android-specific code. For more information, see the Build System Maintainers guide.

More reading: https://android.googlesource.com/platform/ndk/+/ndk-release-r19/docs/BuildSystemMaintainers.md

> ndk-depends has been removed. We believe that ReLinker is a better solution to native library loading issues on old Android versions.

Not applicable, we don't use this.

> Issue 862: The GCC wrapper scripts which redirected to Clang have been removed, as they are not functional enough to be drop in replacements.

This should be addressed by the standalone toolchain support.

**Comment by jin** [comment]
Addressed in https://github.com/bazelbuild/bazel/pull/8524
