### ISSUE TITLE
ijar zipper refuses to create directories: default directory are created with wrong permission

### ISSUE THREAD

**Issue by ekuefler** [bazelbuild/bazel#630]
I'm writing a genrule that creates a .ear file by unpacking several .war files into a directory and then repacking them into a single artifact. I'm trying to use `//third_party/ijar:zipper`, but it is failing when trying to extract war files that contain subdirectories that don't yet exist in the destination.

For example, my genrule does this:
```
mkdir backend
cd backend
../../$(location //third_party/ijar:zipper) x ../../$(location :backend)
cd ..
```

And when running it I get a failure that looks like this:
```
Cannot open file /root/.cache/bazel/_bazel_root/c9fadd9098376b2dddd3da4175fdad4b/master/ear/backend/WEB-INF/web.xml for writing: Permission denied
```

If I change `mkdir backend` to `mkdir -p backend/WEB-INF` the error goes away, but then I have to pre-create each subdirectory manually. This makes the ijar zipper not very useful for extracting archives that might contain subdirectories.

I can work around this easily enough by using jar instead of ijar zipper for extraction.

**Comment by damienmg** [comment]
Wow I just looked at the code and it is definitely supposed to create directory, see https://github.com/bazelbuild/bazel/blob/master/third_party/ijar/zip_main.cc#L128

Oh I have an idea, if you don't create backend/WEB-INF, does it creates WEB-INF? What's the permission of the WEB-INF/web.xml file?

**Comment by ekuefler** [comment]
Huh OK, looks like it more subtle than I thought. I tried a fresh repo with a hand-built jar and it was able to extract it alright. There's also an interaction with sandboxing - if I pass `--genrule_strategy=standalone`, I don't get the permission error. Unfortunately this means I can't tell how much it's creating before it dies since I can't tell what happened in the sandbox after the fact. web.xml permissions are 644.

I trimmed my rules down a bit, here's what I have now:

```
filegroup(
  name = "backend-webinf",
  srcs = [
    "webapp/backend/appengine-web.xml",
    "webapp/backend/logging.properties",
    "webapp/backend/web.xml",
  ],
)
genrule(
  name = "backend",
  srcs = [
    ":backend-webinf",
  ],
  outs = [
    "backend.war",
  ],
  tools = [
    "//third_party/ijar:zipper",
  ],
  cmd = """
    mkdir -p war/WEB-INF
    cd war

    for file in $(locations :backend-webinf); do
      cp ../$$file WEB-INF
    done
    ls -la WEB-INF

    ../$(location //third_party/ijar:zipper) Cc ../$@ $$(find . -type f | cut -c 3-)
""",

)
genrule(
  name = "server",
  srcs = [
    ":backend",
  ],
  outs = [
    "server.ear"
  ],
  tools = [
    "//third_party/ijar:zipper",
  ],
  cmd = """
    pwd
    echo $(location :backend)
    $(location //third_party/ijar:zipper) x $(location :backend)
    echo "success"
""",
)
```

Here's the output I get from building the server target:
```
# bazel build src/main/java/com/ekuefler/server
INFO: Found 1 target...
INFO: From Executing genrule //src/main/java/com/ekuefler/server:backend:
total 24
drwxr-xr-x 3 nobody nogroup 4096 Nov 21 22:32 .
drwxr-xr-x 3 nobody nogroup 4096 Nov 21 22:32 ..
-rw-r--r-- 1 nobody nogroup  432 Nov 21 22:32 appengine-web.xml
drwxr-xr-x 2 nobody nogroup 4096 Nov 21 22:32 lib
-rw-r--r-- 1 nobody nogroup   14 Nov 21 22:32 logging.properties
-rw-r--r-- 1 nobody nogroup 2110 Nov 21 22:32 web.xml
INFO: From Executing genrule //src/main/java/com/ekuefler/server:server:
/root/.cache/bazel/_bazel_root/c9fadd9098376b2dddd3da4175fdad4b/master
bazel-out/local_linux-fastbuild/genfiles/src/main/java/com/ekuefler/server/backend.war
Cannot open file /root/.cache/bazel/_bazel_root/c9fadd9098376b2dddd3da4175fdad4b/master/WEB-INF/web.xml for writing: Permission denied
/bin/bash: line 3:  2665 Aborted                 (core dumped) bazel-out/local_linux-fastbuild/bin/third_party/ijar/zipper x bazel-out/local_linux-fastbuild/genfiles/src/main/java/com/ekuefler/server/backend.war
ERROR: /master/src/main/java/com/ekuefler/server/BUILD:119:1: Executing genrule //src/main/java/com/ekuefler/server:server failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped).
Target //src/main/java/com/ekuefler/server:server failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.531s, Critical Path: 0.18s
```

File permissions before creating the backend war look ok according to ls, and the echoed paths look fine up until when ijar zipper is invoked. Again it works okay if I disable sandboxing, so maybe the root cause has something to do with that. If nothing jumps out at you from this I can keep trying to trim this down to a minimal repro that I can share, but it will take a bit more work.

**Comment by damienmg** [comment]
Can you try removing the -type f?

**Comment by ekuefler** [comment]
Ah good catch, that fixes it (and means that I see the directories as separate entries in the created war file).

I guess in that case it's debatable whether this is a bug or user error. I'd still lean towards bug since jar/zip are able to handle these archives, and at any rate the error message isn't very revealing. Also surprising that sandboxing has an effect here, not sure why it works with that disabled.

**Comment by damienmg** [comment]
Ok here what I think is happening (I have no proof though): zipper creates directory with a wrong umode when sandboxing. Zipper does create directory with a default mode if the entry is not specified, specifying the directory entry force to have them with the good mode in the zip file. This would be consistent with sandboxing because the default rights are a bit different in sandboxed mode.

Can you try `|| (ls -R; exit 1)` in the genrule to see the output tree in the sandbox?

**Comment by ekuefler** [comment]
I think you've got it -

`ls -lR` with `-type f`:
```
.:
total 4
drw-r--r-- 2 nobody nogroup 4096 Dec  2 00:13 WEB-INF

./WEB-INF:
total 0
```

`ls -lR` without `-type f`:
```
.:
total 4
drwxr-xr-x 3 nobody nogroup 4096 Dec  2 00:13 WEB-INF

./WEB-INF:
total 16
-rw-r--r-- 1 nobody nogroup  432 Dec  2 00:13 appengine-web.xml
drwxr-xr-x 2 nobody nogroup 4096 Dec  2 00:13 lib
-rw-r--r-- 1 nobody nogroup   14 Dec  2 00:13 logging.properties
-rw-r--r-- 1 nobody nogroup 2110 Dec  2 00:13 web.xml
```

So in the happy case the directory is created with permissions 755, but when it auto-creates it it does so with permissions 644 in the sandbox, which would explain the later error.

**Comment by damienmg** [comment]
Updated the bug title. I will fix that when I have some time.
