### ISSUE TITLE
Unable to build android executable with asan (linker error)

### ISSUE THREAD

**Issue by fabiensanglard** [bazelbuild/bazel#6301]
Repro case:

Unzip asan.zip
cd asan
bazel build :android_test

```
Error output:
external/androidndk/ndk/toolchains/x86-4.9/prebuilt/linux-x86_64/lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin/ld: error: cannot open external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/clang/3.8.275480/lib/linux/libclang_rt.asan-i686-android.so: No such file or directory
bazel-out/android-x86-fastbuild/bin/asan/_objs/test/main.o:asan/main.cc:function _GLOBAL__sub_I_main.cc: error: undefined reference to '__asan_before_dynamic_init'
bazel-out/android-x86-fastbuild/bin/asan/_objs/test/main.o:asan/main.cc:function _GLOBAL__sub_I_main.cc: error: undefined reference to '__asan_after_dynamic_init'
bazel-out/android-x86-fastbuild/bin/asan/_objs/test/main.o:asan/main.cc:function asan.module_ctor: error: undefined reference to '__asan_init'
bazel-out/android-x86-fastbuild/bin/asan/_objs/test/main.o:asan/main.cc:function asan.module_ctor: error: undefined reference to '__asan_version_mismatch_check_v8'
bazel-out/android-x86-fastbuild/bin/asan/_objs/test/main.o:asan/main.cc:function asan.module_ctor: error: undefined reference to '__asan_register_globals'
bazel-out/android-x86-fastbuild/bin/asan/_objs/test/main.o:asan/main.cc:function asan.module_dtor: error: undefined reference to '__asan_unregister_globals'
/usr/local/google/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/unwind-dw2-fde-dip.c:461: error: undefined reference to 'dl_iterate_phdr'
```

**Comment by fabiensanglard** [comment]
[asan.zip](https://github.com/bazelbuild/bazel/files/2444255/asan.zip)

**Comment by jin** [comment]
This is NDK r14, right? What Bazel version are you using?

**Comment by jin** [comment]
I can build successfully for x86 and armeabi-v7a with Bazel 0.18.0rc4 and NDK r14b:

```
$ cat BUILD
load(":android.bzl", "android_cc_binary")

cc_binary(
    name = "test",
    srcs = ["main.cc"],
    copts = [
        "-fsanitize=address",
    ],
    linkopts = [
        "-fsanitize=address",
    ],
)

android_cc_binary(
    name = "android_test",
    abis = [
        "x86",
        "armeabi-v7a",
        # "arm64-v8a",
    ],
    binary = ":test",
    filename = "test",
)
jingwen@jingwen:~/code/repro/6301_asan
$ export ANDROID_NDK_HOME=/usr/local/google/home/jingwen/ndks/android-ndk-r14b/
jingwen@jingwen:~/code/repro/6301_asan
$ bazel build :android_test --fat_apk_cpu=x86,armeabi-v7a
INFO: Analysed target //:android_test (8 packages loaded).
INFO: Found 1 target...
Target //:android_test up-to-date:
  bazel-bin/android_test/x86/test
  bazel-bin/android_test/armeabi-v7a/test
INFO: Elapsed time: 1.763s, Critical Path: 0.70s
INFO: 6 processes: 6 linux-sandbox.
INFO: Build completed successfully, 7 total actions
```

However, arm64-v8a fails:

```
$ bazel build :android_test --fat_apk_cpu=arm64-v8a
INFO: Analysed target //:android_test (1 packages loaded).
INFO: Found 1 target...
ERROR: /usr/local/google/home/jingwen/code/repro/6301_asan/BUILD:3:1: Linking of rule '//:test' failed (Exit 1)
external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: liblog.so, needed by external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/clang/3.8.275480/lib/linux/libclang_rt.asan-aarch64-android.so, not found (try using -rpath or -rpath-link)
external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libdl.so, needed by external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/clang/3.8.275480/lib/linux/libclang_rt.asan-aarch64-android.so, not found (try using -rpath or -rpath-link)
external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libm.so, needed by external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/clang/3.8.275480/lib/linux/libclang_rt.asan-aarch64-android.so, not found (try using -rpath or -rpath-link)
external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/clang/3.8.275480/lib/linux/libclang_rt.asan-aarch64-android.so: undefined reference to `dlopen@LIBC'
external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/clang/3.8.275480/lib/linux/libclang_rt.asan-aarch64-android.so: undefined reference to `dlsym@LIBC'
external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/clang/3.8.275480/lib/linux/libclang_rt.asan-aarch64-android.so: undefined reference to `dl_iterate_phdr@LIBC'
external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/clang/3.8.275480/lib/linux/libclang_rt.asan-aarch64-android.so: undefined reference to `signgam@LIBC'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //:android_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.844s, Critical Path: 0.64s
INFO: 1 process: 1 linux-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by jin** [comment]
I managed to build aarch64 by providing the linkopts `-ldl` and `-lm`:

```
$ cat BUILD
load(":android.bzl", "android_cc_binary")

cc_binary(
    name = "test",
    srcs = ["main.cc"],
    copts = [
        "-fsanitize=address",
    ],
    linkopts = [
        "-fsanitize=address",
        "-ldl",
        "-lm",
    ],
)

android_cc_binary(
    name = "android_test",
    abis = [
        "x86",
        "armeabi-v7a",
        "arm64-v8a",
    ],
    binary = ":test",
    filename = "test",
)
jingwen@jingwen:~/code/repro/6301_asan
$ bazel build :android_test --fat_apk_cpu=arm64-v8a,x86,armeabi-v7a
INFO: Analysed target //:android_test (0 packages loaded).
INFO: Found 1 target...
Target //:android_test up-to-date:
  bazel-bin/android_test/x86/test
  bazel-bin/android_test/armeabi-v7a/test
  bazel-bin/android_test/arm64-v8a/test
INFO: Elapsed time: 0.145s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

This is with Bazel 0.17.2 and NDK r14b. Could you please try that out?

**Comment by fabiensanglard** [comment]
Without the linker flags I got this error:

external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -o bazel-out/android-armeabi-v7a-fastbuild/bin/asan/test bazel-out/android-armeabi-v7a-fastbuild/bin/asan/_objs/test/main.o external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libgnustl_static.a external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libsupc++.a '-fsanitize=address' -static-libgcc -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -no-canonical-prefixes -target armv7-none-linux-androideabi -Wl,--fix-cortex-a8 -Wl,-S '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm')
ERROR: /usr/local/google/home/sanglardf/repos/studio-master-dev/asan/BUILD:3:1: Linking of rule '//asan:test' failed (Exit 1)
external/androidndk/ndk/toolchains/x86-4.9/prebuilt/linux-x86_64/lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin/ld: error: cannot open external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/clang/3.8.275480/lib/linux/libclang_rt.asan-i686-android.so: No such file or directory
bazel-out/android-x86-fastbuild/bin/asan/_objs/test/main.o:asan/main.cc:function _GLOBAL__sub_I_main.cc: error: undefined reference to '__asan_before_dynamic_init'
bazel-out/android-x86-fastbuild/bin/asan/_objs/test/main.o:asan/main.cc:function _GLOBAL__sub_I_main.cc: error: undefined reference to '__asan_after_dynamic_init'
bazel-out/android-x86-fastbuild/bin/asan/_objs/test/main.o:asan/main.cc:function asan.module_ctor: error: undefined reference to '__asan_init'
bazel-out/android-x86-fastbuild/bin/asan/_objs/test/main.o:asan/main.cc:function asan.module_ctor: error: undefined reference to '__asan_version_mismatch_check_v8'
bazel-out/android-x86-fastbuild/bin/asan/_objs/test/main.o:asan/main.cc:function asan.module_ctor: error: undefined reference to '__asan_register_globals'
bazel-out/android-x86-fastbuild/bin/asan/_objs/test/main.o:asan/main.cc:function asan.module_dtor: error: undefined reference to '__asan_unregister_globals'
/usr/local/google/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/unwind-dw2-fde-dip.c:461: error: undefined reference to 'dl_iterate_phdr'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

If I add -ldl and -lm now get a different error:

external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -o bazel-out/android-arm64-v8a-fastbuild/bin/asan/test bazel-out/android-arm64-v8a-fastbuild/bin/asan/_objs/test/main.o external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/libgnustl_static.a external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/libsupc++.a '-fsanitize=address' -ldl -lm -static-libgcc -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -target aarch64-none-linux-android -no-canonical-prefixes -Wl,-S '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm64')
ERROR: /usr/local/google/home/sanglardf/repos/studio-master-dev/asan/BUILD:3:1: Linking of rule '//asan:test' failed (Exit 1)
external/androidndk/ndk/toolchains/x86-4.9/prebuilt/linux-x86_64/lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin/ld: error: cannot open external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/clang/3.8.275480/lib/linux/libclang_rt.asan-i686-android.so: No such file or directory
bazel-out/android-x86-fastbuild/bin/asan/_objs/test/main.o:asan/main.cc:function _GLOBAL__sub_I_main.cc: error: undefined reference to '__asan_before_dynamic_init'
bazel-out/android-x86-fastbuild/bin/asan/_objs/test/main.o:asan/main.cc:function _GLOBAL__sub_I_main.cc: error: undefined reference to '__asan_after_dynamic_init'
bazel-out/android-x86-fastbuild/bin/asan/_objs/test/main.o:asan/main.cc:function asan.module_ctor: error: undefined reference to '__asan_init'
bazel-out/android-x86-fastbuild/bin/asan/_objs/test/main.o:asan/main.cc:function asan.module_ctor: error: undefined reference to '__asan_version_mismatch_check_v8'
bazel-out/android-x86-fastbuild/bin/asan/_objs/test/main.o:asan/main.cc:function asan.module_ctor: error: undefined reference to '__asan_register_globals'
bazel-out/android-x86-fastbuild/bin/asan/_objs/test/main.o:asan/main.cc:function asan.module_dtor: error: undefined reference to '__asan_unregister_globals'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jin** [comment]
Could you please share the Bazel version you're using?

**Comment by fabiensanglard** [comment]
Any update on this?

**Comment by jin** [comment]
Sorry, I haven't had the chance to look deeper into the arm64 part yet. Will spend some time on this this/next week.
