### ISSUE TITLE
Bazel on OSX is missing expand_directories

### ISSUE THREAD

**Issue by kkiningh** [bazelbuild/bazel#6303]
### Description of the problem / feature request:

Release version of Bazel on OSX is missing the expand_directories argument to [args.add_all](https://docs.bazel.build/versions/master/skylark/lib/Args.html#add_all) and the [--incompatible_expand_directories](https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#expand-directories-in-args) flag.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

$ brew tap bazelbuild/tap
$ brew tap-pin bazelbuild/tap
$ brew install bazel
$ bazel version
Build label: 0.17.2
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar                                                                                                
Build time: Fri Sep 21 11:19:02 2018 (1537528742)
Build timestamp: 1537528742
Build timestamp as int: 1537528742
$ bazel build --incompatible_expand_directories
ERROR: Unrecognized option: --incompatible_expand_directories

### What operating system are you running Bazel on?

$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.6
BuildVersion:   17G65

### What's the output of `bazel info release`?

$ bazel info release
release 0.17.2

**Comment by benjaminp** [comment]
That flag isn't expected to be in 0.17.x because that release branched at the beginning of August, and 774bfe0f2a8e9cb4fa389f1e8b50a8fc13efcfe7 landed later that month.

**Comment by kkiningh** [comment]
Oh gotcha. I got confused since the release date was after the date the feature landed. Consider this resolved.

Is there any timeline as to when this will be in a release?

**Comment by jin** [comment]
@kkiningh feel free to follow the release thread for updates: https://github.com/bazelbuild/bazel/issues/5963
