### ISSUE TITLE
bazel build flags not applied to builds of external repos

### ISSUE THREAD

**Issue by kastiglione** [bazelbuild/bazel#6307]
### Description of the problem / feature request:

`bazel build` flags are not applied to the actions that build external repositories. Specifically, I am having this problem with [protocolbuffers/protobuf](https://github.com/protocolbuffers/protobuf) via `http_archive`. The flags that are not propagated are: `--copt` and `--action_env`.

### Feature requests: what underlying problem are you trying to solve with this feature?

I came across this problem while trying to debug a rules_swift build failure Travis CI, where `@com_google_protobuf//:protoc` is failing to build because of undeclared inputs. I tried to use `--copt="-v"`, `--action_env=xcrun_log=1`, and `--action_env=xcrun_verbose=1` to diagnose the underlying issue (values of `-isysroot` and `SDKROOT`), but these flags are only being applied for the local targets, not to the external protobuf targets.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The `:protoc` build failure does not happen locally, only on CI. I have added the above build flags to bazelbuild/rules_swift#63, and the CI logs do not show the logging for `:protoc`. The flags and their logging _are working_ for rules_swift targets though.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 0.17.2

###  Have you found anything relevant by searching the web?

There are a number of related issues of build failures with Xcode 10, most of them are also failures when building protobuf.

* bazelbuild/bazel#6144
* bazelbuild/bazel#6195
* bazelbuild/bazel#6240

**Comment by dslomov** [comment]
This is weird - the flags should apply to all targets. Is there a simple repro for this?

**Comment by kastiglione** [comment]
I don't have a simple repo at the moment. I can try to make one.

**Comment by keith** [comment]
I repro'd this case when including buildifier through bazel. I believe it's because the `--host_copt` I passed was added _before_ other flags passed:

```
  external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -iquote external/com_google_protobuf -iquote bazel-out/host/genfiles/external/com_google_protobuf -iquote bazel-out/host/bin/external/com_google_protobuf -isystem external/com_google_protobuf/src -isystem bazel-out/host/genfiles/external/com_google_protobuf/src -isystem bazel-out/host/bin/external/com_google_protobuf/src -MD -MF bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/message_differencer.d '-frandom-seed=bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/message_differencer.o' -isysroot __BAZEL_XCODE_SDKROOT__ -g0 -Wno-everything -g0 -DHAVE_PTHREAD -Wall -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -Wno-writable-strings -Wno-write-strings -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_protobuf/src/google/protobuf/util/message_differencer.cc -o bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/message_differencer.o)
INFO: From Compiling external/com_google_protobuf/src/google/protobuf/compiler/cpp/cpp_message.cc [for host]:
external/com_google_protobuf/src/google/protobuf/compiler/cpp/cpp_message.cc:520:16: warning: private field 'cold_threshold_' is not used [-Wunused-private-field]
  const double cold_threshold_;
               ^
1 warning generated.
```

In this example I passed `--host_copt=-Wno-everything`. But you can see it has some warning flags after mine.

**Comment by keith** [comment]
In this case we fell back to using `--output_filter="something that isn't matched"`
