### ISSUE TITLE
Incomprehensible error message: "Exhaused retry attempts"

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#6308]
https://buildkite.com/bazel/google-bazel-presubmit/builds/9914#140dc6c6-0034-485a-bf8d-6ba99f457241

```
ERROR: /Users/buildkite/builds/buildkite-imacpro-4-1/bazel/google-bazel-presubmit/src/test/java/com/google/devtools/build/lib/BUILD:1537:1: Couldn't build file src/test/java/com/google/devtools/build/lib/rules-tests.jar: Building src/test/java/com/google/devtools/build/lib/rules-tests.jar (3 source files) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor) failed: Unexpected IO error.: Exhaused retry attempts (0)
```

What subsystem has exhausted the retries here? What did it try in the first place? 0 attempts? Really?

**Comment by ola-rozenfeld** [comment]
Did that include https://github.com/bazelbuild/bazel/commit/bf6a63d64a010f4c363d218e3ec54dc4dc9d8f34 ?

**Comment by bayareabear** [comment]
In my case, it was because my Nginx config did not set keepalive_requests. @ola-rozenfeld, If that include "bf6a63d", it will just be a warning like error read from cache. But regardless, we should add a stacktrace for the error or warning.

**Comment by ola-rozenfeld** [comment]
A stacktrace should be available for all errors you use --verbose_failures. This is a warning, though, that's why we didn't think to include a stacktrace. Not sure stacktraces on warnings are a good experience in general...

**Comment by bayareabear** [comment]
This was an error before "bf6a63d", and use "--verbose_failures" did not generate more info or stacktrace, at least in my case. Usually this warning means there is cache miss and there is an issue with server setup, that's why a stacktrace would be very helpful.

**Comment by ulfjack** [comment]
I don't know whether the binary I used included that commit, but I'm not sure it matters - the message is useless, whether it's a warning or an error. It doesn't even mention the remote cache. An exception stack trace would at least tell me which part of Bazel it's in.

**Comment by bayareabear** [comment]
To add on that:
1.  If include bf6a63d, use --verbose_failures does not generate a stacktrace, this is a bug
2. If include bf6a63d, the error becomes a warning, it is more deceiving. It makes you think your cache is working properly, but actually not.

**Comment by ola-rozenfeld** [comment]
So https://github.com/bazelbuild/bazel/commit/bf6a63d64a010f4c363d218e3ec54dc4dc9d8f34 fixed the cryptic error message bug with no stack trace. However, I'm not sure if there are any remaining things that are wrong here. What should Bazel do when your remote cache doesn't work properly with local execution?
When we designed the feature, we thought that remote cache errors should not fail local builds. So all these errors are warnings, by design. Do you think that wasn't the right call? Or do you think we should include stack traces with the warnings if --verbose_failures is on?

**Comment by bayareabear** [comment]
Thanks for the detailed info. Yes, I agree that bazel remote should not fail the build.  Ideally, at the end of the build it should provide warning summary message how many attempted connections failed(and printout something like "your server most likely has issue"). And if you use --verbose_failures flag, it can provide stacktrace.
If everything is set right(correct me if I am wrong), we will mostly get 100% cache hit, so print out some thing like "your remote server most likely has issue", when it is less than 100% hit would be very helpful for people are not so familiar with bazel remote cache. As the remote cache miss are only warnings, if people can build successfully, they may not realize their server have problem, and will just go with it. In the end, they did not utilize the full strength of remote cache. For one example, I have seen in another opened issue that  a user has a lot of such warnings in their CI box, which I believe he did not set the remote server correctly.

**Comment by bayareabear** [comment]
Also, it would be helpful if we have a flag to specify the number of retries for get/put cache. Now it seems it only tries once.

**Comment by ola-rozenfeld** [comment]
We do have a few flags controlling the retry behavior, like
--experimental_remote_retry_max_attempts. They are only relevant to gRPC
remote cache, though. We don't retry the http cache currently.

**Comment by DavinciHW** [comment]
@bayareabear  In my case, it was because my Nginx config did not set keepalive_requests.  -----  Does the nginx server print logs about this error? I also encountered this problem, occasionally failed, and failure always occurs on the same file compilation.

**Comment by bayareabear** [comment]
@dMokaMoka, Nginx does not produce any log regarding that. only the downstream uWSGI will produce an error like: upstream connection prematurely closed. You may check your real time QPS and see if the QPS is higher when compiling that file
