### ISSUE TITLE
Can't use "//tools/jdk:jar" without an explicit dep on "//tools/jdk:jdk"

### ISSUE THREAD

**Issue by ekuefler** [bazelbuild/bazel#631]
If I declare a genrule with a `tools` dependency on `//tools/jdk:jar` and attempt to invoke it like `$(location //tools/jdk:jar) xf <myfile>`, I get the following error:

```
external/local-jdk/bin/jar: error while loading shared libraries: libjli.so: cannot open shared object file: No such file or directory
```

The error goes away if I also add `//tools/jdk:jdk` to `tools`, but there's no way to figure this out from the message. Can/should jar have an implicit dependency on jdk so people don't have to figure this out?

**Comment by damienmg** [comment]
Thank you for the report, unfortunately we are a bit overloaded currently and we cannot work on that soon (it needs to have the corresponding test case especially). If you wish to fix this bug, the correct file to fix is https://github.com/bazelbuild/bazel/blob/master/src/main/tools/jdk.BUILD

**Comment by ekuefler** [comment]
Sounds good, I might try taking a look at some point but it's low-priority for me too. Hopefully this page will show up in Google for that error message until then.

**Comment by ulfjack** [comment]
There's a proposal for adding a java_runtime, which would eliminate this problem.
