### ISSUE TITLE
Rules_* jobs are failing with Bazel at HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#6311]
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/480

```
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/b56e71a8651156a61b0ca6a115747ad7/external/go_sdk/BUILD.bazel:52:1: no such target '@io_bazel_rules_go//go:toolchain': target 'toolchain' not declared in package 'go'; however, a source directory of this name exists.  (Perhaps add 'exports_files(["toolchain"])' to go/BUILD, or define a filegroup?) defined by /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/b56e71a8651156a61b0ca6a115747ad7/external/io_bazel_rules_go/go/BUILD.bazel and referenced by '@go_sdk//:go_plan9_386'
```

Bisecting gives 23488930607e4919a99e80de240d6d35f4037797 as the culprit

@katre, can you confirm this? Also, maybe we are lacking some test coverage here.

**Comment by katre** [comment]
Yes, this is caused by 2348893. Please roll it back while I investigate.

**Comment by katre** [comment]
Downstream projects from rules_go that will need to be updated once rules_go releases the fix:
* bazel-toolchains
* buildtools
* Gerrit
* rules_docker
* rules_nodejs
* rules_sass
* rules_typescript

**Comment by meteorcloudy** [comment]
Closing since the breakage has gong away
