### ISSUE TITLE
cc_binary doesn't use objc_frameworks deps

### ISSUE THREAD

**Issue by steeve** [bazelbuild/bazel#6330]
### Description of the problem / feature request:

It seems `cc_binary` does pick up `sdk_frameworks` from `objc_library` deps, but it doesn't pick up `objc_framework` deps from that library.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Given the following build file:
```python
objc_framework(
    name = "Fabric",
    framework_imports = glob(["Fabric.framework/**"]),
    is_dynamic = 0,
    visibility = ["//visibility:public"],
)

objc_library(
    name = "test",
    srcs = ["test.m"],
    enable_modules = 1,
    deps = [
        ":Fabric",
    ],
    alwayslink = 1,
)

cc_binary(
    name = "main",
    deps = [
        ":test",
    ],
)
```

The build fails with the following:
```
ERROR: /Users/steeve/myproj/BUILD.bazel:66:1: Linking of rule '//:main' failed (Exit 1): cc_wrapper.sh failed: error executing command
  (cd /private/var/tmp/_bazel_steeve/309ac22c92b055a3e3f78825fe63406b/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=12.0 \
    PATH=/bin:/usr/bin \
    XCODE_VERSION_OVERRIDE=10.0.0 \
  external/local_config_cc/cc_wrapper.sh -fobjc-link-runtime -framework UIKit -o bazel-out/ios_arm64-fastbuild/bin/main bazel-out/ios_arm64-fastbuild/bin/libtest.a  -headerpad_max_install_names -lc++ -no-canonical-prefixes -target arm64-apple-ios '-miphoneos-version-min=10.0')

Use --sandbox_debug to see verbose messages from the sandbox
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_Fabric", referenced from:
      objc-class-ref in libtest.a(test_7cae5c15fdeb54229391dd383e3cfa1b.o)
ld: symbol(s) not found for architecture arm64
```

### What operating system are you running Bazel on?

OSX

### What's the output of `bazel info release`?

```
release 0.17.2
```

**Comment by tetromino** [comment]
Apparently, this is a known issue. Meanwhile, please check if using `objc_binary` instead of `cc_binary` helps with your use case.

We are following up on this internally.

**Comment by keith** [comment]
Note this is also an issue with the Swift rules

**Comment by steeve** [comment]
@tetromino was there any advances on your side ?

**Comment by jmmv** [comment]
Is this still an issue?

@tetromino Also, when you said following up internally... what came out of that?

**Comment by c-mita** [comment]
Closing for now; if there's still a problem here then please reopen.
