### ISSUE TITLE
runfiles library in Go

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#6333]
### Description of the problem / feature request:

Implement a runfiles library for Go programs, similar to those libraries in `@bazel_tools//tools/<language>/runfiles`.

### Feature requests: what underlying problem are you trying to solve with this feature?

Standard way to handle runfiles in Go programs.

**Comment by meteorcloudy** [comment]
Should this be a part of https://github.com/bazelbuild/rules_go?

**Comment by laszlocsomor** [comment]
Yes,  it should. Thanks for asking!

**Comment by laszlocsomor** [comment]
Looks like this functionality already exists: https://github.com/bazelbuild/rules_go/blob/master/go/tools/bazel/README.md

**Comment by laszlocsomor** [comment]
Oh, but it's not aware of runfiles manifests. I guess my efforts to write the library weren't in vain then :)

**Comment by jin** [comment]
Shall we transfer this issue to rules_go?

https://help.github.com/articles/transferring-an-issue-to-another-repository/

**Comment by meteorcloudy** [comment]
@jin Yes, we should do that

**Comment by laszlocsomor** [comment]
I don't have admin powers to transfer bugs, so I just opened a new issue: https://github.com/bazelbuild/rules_go/issues/1815
