### ISSUE TITLE
Non-consistent behavior regarding emscripten

### ISSUE THREAD

**Issue by FrancoisChastel** [bazelbuild/bazel#6348]
### Description of the problem / feature request:

When trying to implement `emscripten` porting to a C/C++ project, non-consistent errors appears regarding the modification of compiler used with exactly the same parameters. 

After coming [through a guide concerning the usage of emscripten](https://github.com/bazelbuild/bazel/wiki/Yet-Another-CROSSTOOL-Writing-Tutorial) and some investigation, I am not able to figure out a way to be unlocked at all and I presume it's coming from the poor integration with other compilers. 

I get the following exact error : 
```
ERROR: /private/var/tmp/_bazel_root/7eac25f81ba1cb3897eb750dd5c677da/external/openssl/BUILD:1100:1: undeclared inclusion(s) in rule '@openssl//:openssl':
this rule is missing dependency declarations for the following files included by 'external/openssl/openssl/crypto/x509/x_crl.c':
```
when remplacing inside the `emcc.sh` from the tutorial, `emcc` to `clang` some errors still appears but are related to the code. Switching to other compilers does not make it appear as well.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Implement the tutorial into a project with external dependencies.

### What operating system are you running Bazel on?

macOS High Sierre - 10.13.6 (17G2307)

### What's the output of `bazel info release`?

`release 0.14.0`
###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

I would like to produce documentation for porting C/C++ big code base using bazel and emscripten in the next few weeks if the project is successful

**Comment by FrancoisChastel** [comment]
Forgot to mention I found a fix for this problem : `.d` files are poorly managed with a toolchain using `Emscripten`. 

You need to clean the `.d` files after the calls of `emcc` by cleaning what is recommended AND by cleaning absolute paths to the _bazel_root :

```
find . -name "*.d" -exec sed -i -e "2d" {} \;
find . -name "*.d" -exec sed -i -e "s/\/private\/var\/tmp\/_bazel_root\/xxx\///g" {} \;
```
with `xxx` the file name of the actual output of your bazel instance, to find it, you need to run `bazel info` and it should the `output_base` value.

**Comment by mhlopko** [comment]
Emscripten is not a Bazel supported toolchain, only a topic for tutorial. Please don't use it in production (unless you invest in productionalizing it :) Thanks for understanding.

**Comment by nornagon** [comment]
What @hlopko said, but if you really like sed and just want to hack something up to get it working, plopping this in `emcc.sh` worked for me:

```
find . -name "*.d" -exec sed -i -e 's/^\( *\)\/.*external/\1external/' {} \;
```
