### ISSUE TITLE
Support @argument files in the Java binary wrapper script

### ISSUE THREAD

**Issue by cushon** [bazelbuild/bazel#6355]
Related: #6354

JDK 9 adds support for flag files using the `@argument-file` syntax, see "java Command-Line Argument Files" in https://docs.oracle.com/javase/9/tools/java.htm.

We could back-fill support for that syntax for older `--javabase` versions by adding logic to the wrapper script.

**Comment by regisd** [comment]
@cushon Duplicate of #6354 ?

**Comment by cushon** [comment]
Not quite: #6354 is about adding the feature that was adding in JDK 9, this is about implementing that feature with logic in the wrapper script to support it on older JDKs.

**Comment by lberki** [comment]
I'll close this one in favor of #6354 and add the information in the description of this one there.
