### ISSUE TITLE
bazel build fails with `error loading package ''` when invoked in a `git submodule foreach` command

### ISSUE THREAD

**Issue by dpursehouse** [bazelbuild/bazel#6358]
### Description of the problem / feature request:

When invoking `bazel build` from within a `git submodule foreach` command, it fails with `error loading package ''`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
git clone --recurse-submodules --branch=stable-2.14 https://github.com/dpursehouse/gerrit-plugins
cd gerrit-plugins
git submodule foreach 'bazel build $sm_path'
```

### What operating system are you running Bazel on?

OSX 10.14

### What's the output of `bazel info release`?

`release 0.17.2`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

Could not find anything related to this.

### Any other information, logs, or outputs that you want to share?

```
gerrit-plugins $ git submodule foreach 'bazel build $sm_path'
Entering 'admin-console'
Starting local Bazel server and connecting to it...
ERROR: error loading package '': Encountered error while reading extension file 'gerrit_api.bzl': no such package '@com_googlesource_gerrit_bazlets//': Creating directories for /Users/dpursehouse/temp/gerrit-plugins/admin-console/.git failed
ERROR: error loading package '': Encountered error while reading extension file 'gerrit_api.bzl': no such package '@com_googlesource_gerrit_bazlets//': Creating directories for /Users/dpursehouse/temp/gerrit-plugins/admin-console/.git failed
INFO: Elapsed time: 0.402s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
fatal: run_command returned non-zero status for admin-console
.
```

**Comment by dkelmer** [comment]
I don't know what the root cause is, but switching to using the skylark git_repository rule in bazlets.bzl fixes the problem. Since we are deprecating the native git rules, I'm not going to keep investigating at the moment. If this is blocking you right now and you can't switch, please reopen the bug.

**Comment by dpursehouse** [comment]
Thanks, that works.  Is there also a replacement for `native.local_repository`?

**Comment by dkelmer** [comment]
There isn't (and there aren't currently plans to replace it). Are you seeing failures with local_repository as well?

**Comment by dkelmer** [comment]
And thanks for migrating the git rules so quickly! :)

**Comment by irengrig** [comment]
@dpursehouse  As I see, the local repository variant of load_bazlets does not use the passed checksum.
So you are using whatever local version you pointed to. Seems it is not the version you expected:)

**Comment by dpursehouse** [comment]
@irengrig thanks, I hadn't thought of that.  But it's strange that I never saw this problem before.  It seemed to only start after edited the `bzl` file to use the `git_repository` skylark rule, although I don't understand how that could be.  I'll try it again later.

**Comment by davido** [comment]
`local_repository` [doesn't](https://docs.bazel.build/versions/master/be/workspace.html#local_repository)  have sha1 parameter.

**Comment by dpursehouse** [comment]
I guess when I used it before I always had the same revision checked out locally in the `bazlets` repo. Sorry for the noise.
