### ISSUE TITLE
Print platform info with error message when -versbose_failures is selected

### ISSUE THREAD

**Issue by nlopezgi** [bazelbuild/bazel#6362]
### Description of the problem / feature request:

Feature Request: Print platform info with error message when -verbose_failures is selected.

If a user passes the verbose_failures and the build fails, the error message should include some info about which platform was used to run the failed action.

### Feature requests: what underlying problem are you trying to solve with this feature?

Users can make simple mistakes that lead to incorrect platform being selected. Error message showing platform would help identify these kinds of issues very easily.

**Comment by katre** [comment]
Can you provide example output showing where the message should be?

**Comment by nlopezgi** [comment]
This is a snippet from an output from a failed build for TF:

ERROR: /tmpfs/tmp/bazel/external/org_tensorflow/third_party/toolchains/preconfig/ubuntu14.04/cuda9.0-cudnn7/cuda/BUILD:206:1: Couldn't build file external/org_tensorflow/third_party/toolchains/preconfig/ubuntu14.04/cuda9.0-cudnn7/cuda/cuda/include/CL/cl.h: Executing genrule @org_tensorflow//third_party/toolchains/preconfig/ubuntu14.04/cuda9.0-cudnn7/cuda:cuda-include failed (Exit 1)
cp: cannot stat '/usr/local/cuda-9.0/include/CL/cl.h': No such file or directory
[9,866 / 10,412] 278 / 503 tests, 278 failed; no action

The error message coming from the use of --verbose_failures is:
"cp: cannot stat '/usr/local/cuda-9.0/include/CL/cl.h': No such file or directory"

This error occurred because the wrong platform was selected to run this action (due to a user mistake in flags)

It would have been ideal to get something like

cp: cannot stat '/usr/local/cuda-9.0/include/CL/cl.h': No such file or directory
Platform info: this action ran in <something about the platform that either shows all details here or points me to the platform target that was selected for this action>

Please let me know if you want more details / a more comprehensive example.
