### ISSUE TITLE
[feature request] configuring all java_binary and java_test to have certain jvm_flags set

### ISSUE THREAD

**Issue by petroseskinder** [bazelbuild/bazel#6364]
This stems from an offline discussion with @gregestren and @katre. 

Internally, at Two Sigma, we would like to globally set some jvm_flags for all of our java_library targets by default. 

In today's world, it's unclear how one would go about doing that, without doing something hacky like wrapping java_library with a java_library macro, or creating a macro that you assign to every java_library target

```
load("//:java.bzl", "default_jvm_flags")
java_library(
   ...
   jvm_flags = default_jvm_flags(),
)
```
This seems like something that bazel should allow configuring. @kevingessner discussed a similar matter in issue #3427 with setting all javacopts by default. Additionally, we have run up against this issue when trying to modify the JavaBuilder's default set of errorprone flags.

**Comment by cushon** [comment]
What are the semantics for per-library `jvm_flags`? Currently the attribute is only supported on `java_binary` and `java_test`, is the idea that the flags get rolled up and added to any tests or binaries that transitively depend on a library that sets `jvm_flags`?

Also note that there's a top-level `--jvmopt=` flag that adds options to *all* targets.

**Comment by gregestren** [comment]
Could a shared .bazelrc with `--jvmopt=` do the trick?

**Comment by petroseskinder** [comment]
Sorry, I mis-typed in my original posting. It was for a means for setting jvm_flags for all _executables_ (java_tests and java_binary targets). I had conflated this issue with what were doing with java_library and javacopts.

I was initially thinking that if we could set the jvm_flags in a java_library that it could exclusively percolate up to the java_binary targets and test targets that depended on it. Let me verify though that jvmopt does not suffice though.

**Comment by jin** [comment]
@gregestren could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?

**Comment by aiuto** [comment]
@petroseskinder Is this still an issue? My hunch is that jvmopt worked for you since this went stale a long time ago.
