### ISSUE TITLE
Missing query for discovering repositories

### ISSUE THREAD

**Issue by philsc** [bazelbuild/bazel#6377]
### Description of the problem / feature request:

Given the following WORKSPACE file:
```python
local_repository(
    name = "foo"
    path = "third_party/foo",
)
local_repository(
    name = "bar"
    path = "third_party/bar",
)
```
I am looking for a query that tells me about `@foo`. Something like:
```console
$ bazel query 'repositories()'
@
@foo 
@bar 
```

### Feature requests: what underlying problem are you trying to solve with this feature?

For CI purposes, I'd love to have a list of targets that I need to submit to `bazel test` in order to actually test _everything_. There have been a couple of times where we added a new `local_repository` rule and forgot to add it to our CI system:
```console
$ bazel test //... @foo//... @bar//...
...
```

It'd be nice to do something like this:
```console
$ bazel test $(for repository in $(bazel query 'repositories()'); do echo ${repository}//...; done)
...
```
so that we could automatically test everything.

###  Have you found anything relevant by searching the web?

I found https://stackoverflow.com/questions/46229831/how-do-you-query-for-a-list-of-all-repositories-that-are-available-in-a-workspac, and it gets close, but not quite what I was looking for.

**Comment by philsc** [comment]
Submitted too early, sorry. Fixing it up now.

**Comment by philsc** [comment]
Actually, https://docs.bazel.build/versions/master/query.html#external-repos gets pretty dang close. I think it might work for what I'm trying to do.

**Comment by philsc** [comment]
Is there a way to filter out built-in targets like `@local_jdk`?
```console
$ bazel query 'kind(local_repository, //external:*)'
//external:foo
//external:bar
//external:local_jdk
```

**Comment by bsilver8192** [comment]
#1034 is similar, but looking for a way to find all the test targets automatically in a single query.

**Comment by tferi** [comment]
It would also be useful to know the definition of the remote repository in case of transitive dependencies. For instance in my case rules_docker added a dependency on rules_go, and I couldn't figure out which version it pulled in.

**Comment by dmivankov** [comment]
Also on querying external dependency version https://github.com/bazelbuild/bazel/issues/12947

**Comment by thefallentree** [comment]
This is not a solution that uses "bazel query", but it's better

add a dump_repositories.bzl file somewhere in your workspace

```
def _sort_by_kind_then_name(x):
  return x["kind"] + x["name"]

def repositories_as_json():
  return json.encode_indent(sorted(native.existing_rules().values(), key = _sort_by_kind_then_name))

def _dump_all_repositories_impl(repository_ctx):
  repository_ctx.file("BUILD", executable = False, content = "exports_files(['result.json'])")
  repository_ctx.file("result.json", executable = False, content = repository_ctx.attr.repositories_json)

dump_all_repositories = repository_rule(
  implementation = _dump_all_repositories_impl,
  attrs = {
    "repositories_json": attr.string(mandatory = True),
  },
)
```

and in your WORKSPACE, add following to the last line (must be last)

```
# This must be the last rule in WORKSPACE file to capture all external repositories
load("dump_repositories.bzl", "dump_all_repositories", "repositories_as_json")
dump_all_repositories(
name = "all_external_repositories",
repositories_json = repositories_as_json(),
)
```
Then use this script to view all the dependencies you have,  with JQ!

```
#!/bin/bash
DIR=$(bazel info output_base)
bazel build @all_external_repositories//:result.json && cat $DIR/external/all_external_repositories/result.json | jq --sort-keys '.[] | select(.kind == "go_repository")'
```
