### ISSUE TITLE
Remote Execution: please propagate errors from REAPI service to console

### ISSUE THREAD

**Issue by pcj** [bazelbuild/bazel#6378]
If the build fails due to problems with the remote REAPI backend, please include whatever detail is available from the grpc error message.  Currently as of 0.17.2, remote execution can fail with errors like "Remote connection/protocol failed with: execution failed catastrophically" with no additional detail.

**Comment by buchgr** [comment]
@ola-rozenfeld can you take care of this please?

**Comment by ola-rozenfeld** [comment]
I did. https://github.com/bazelbuild/bazel/commit/097194ff4c751451c7cd311d8c7eab365dd1983a should have fixed this.
