### ISSUE TITLE
Tests run without (network) sandboxing when --java_debug is set

### ISSUE THREAD

**Issue by Mantas-Ragauskas** [bazelbuild/bazel#6379]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Running test in debug mode reverts network blocking, causing tests, that fail during run, pass on a debug 

### Feature requests: what underlying problem are you trying to solve with this feature?

Having network enabled on a debug mode causes tests, that try to access network & fail on normal run, to pass.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Have a test calling external service. Normal run would fail, while debug - pass

### What operating system are you running Bazel on?

MacOs

### What's the output of `bazel info release`?

release 0.17.2

**Comment by Mantas-Ragauskas** [comment]
cc @ittaiz

**Comment by Mantas-Ragauskas** [comment]
Java tests, that interact with the outside world, to be precise.
Provided there is a test, that interacts with outside world via network, running it in bazel sandbox - fail the test because of the network blocking (as expected). Running same test in debug mode - passes the test.

It isn't a critical issue, but it comes to be a nuisance when investigating the test failures

The most basic idea that comes mind - is it possible to block network for all, but debugger traffic?

**Comment by talya** [comment]
just for completeness sake,  tagging this as relevant to #2765 , as this can add to confusion when triaging tests in sandboxed/non-sandboxed mode.
using `--cache_test_results=false` is prob the best thing for these cases

**Comment by Mantas-Ragauskas** [comment]
While i do agree that it will help with not caching false positive test result, the issue lies in the fact, that running test in debug succeeds, while a normal run fails. And that, in turn, is caused by silently disabling the network blocking. 
Usability-wise, at very least, a warning, stating that networking blocking has been disabled,  would be helpful indicator of a change in environment
