### ISSUE TITLE
python stub_template hardcoded to run /usr/bin/python

### ISSUE THREAD

**Issue by JoeHazzers** [bazelbuild/bazel#638]
Despite the change to use `%python_binary%` in `src/main/java/com/google/devtools/build/lib/bazel/rules/python/stub_template.txt`, the shebang of the file is hardcoded to use `/usr/bin/python`.

This means that any machine which has `/usr/bin/python` symlinked to python3 breaks, as the file is not python3 compatible.

The other slight issue is that `python2_path` and `python3_path` are not necessarily absolute, meaning that the best solution is probably to make `stub_template.txt` python2 *and* python3 compatible.

**Comment by lberki** [comment]
Since she imported your change.

**Comment by kchodorow** [comment]
The change has some difficulties internally and I don't know how to fix, so assigning to @lberki since he did the code review.  Sorry for the hot potato.
