### ISSUE TITLE
Disallow using C++ Specific Make Variables from the configuration

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/bazel#6381]
Incompatible change.

Currently Bazel allows rule authors to access certain Make variables that are implicitly provided to every rule by the CppConfiguration. This causes every target to implicitly depend on CppConfiguration, which creates an undesirable number of extra, unused, dependencies.

We are removing the implicit provision of these Make variables, and requiring rules and targets that use these Make variables to explicitly depend on a C++ toolchain in order to access them.

[Migration docs](https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#disallow-using-c-specific-make-variables-from-the-configuration).

**Comment by mhlopko** [comment]
Flag is flipped, closing the issue.

**Comment by hlopko** [comment]
Thanks for reporting. Let me fix it :)
