### ISSUE TITLE
Bazel doesn't stop on error-prone violations

### ISSUE THREAD

**Issue by regisd** [bazelbuild/bazel#6386]
### Description of the problem

> With the maven-error-prone-plugin, "FallThrough" violations break the build.
> With Bazel, the build is successful, and not error is reported

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
mkdir error_prone_bug
cd error_prone_bug

cat > Hello.java  <<_EOF_
public class Hello {
  public static void main(String[] argv) {
    switch (argv.length) {
      case 0:
        System.out.println("Hello world!");
      case 1:
        System.out.println("Hello " + argv[1]);
    }
  }
}
_EOF_

cat > BUILD <<_EOF_
java_library(
  name = "hello",
  srcs = ["Hello.java"],
)
_EOF_

touch WORKSPACE

bazel build //:hello
cd ..
```

### What operating system are you running Bazel on?

> Linux Ubuntu rodete

### What's the output of `bazel info release`?

> release 0.18.0

###  Have you found anything relevant by searching the web?

Possible duplicate of #6077 by @davido 

> The difference is that I'm using the release version  ; and the problem reported seems to mostly affect large builds. Hello.java is not large.

**Comment by regisd** [comment]
Did I misunderstand the statement that

> We turned Error Prone on by default 
https://blog.bazel.build/2015/06/25/ErrorProne.html

Because when I run `bazel build --javacopt="-Xep:FallThrough:ERROR" //...`, the violations are correctly reported.

**Comment by davido** [comment]
I think it depends on te severity of the error. Some of them are warning and some of them are errors. You can change the priority by passing different severity (like you did). Also note, that EP warnings are not shown per default in Bazel build. Gerrit Code Review project added different toolchain to activate all EP warning in Bazel build.

**Comment by davido** [comment]
As expected, the severity of **http://errorprone.info/bugpattern/FallThrough** is warning. So that Bazel WAD here.

**Comment by cushon** [comment]
If you want `FallThroggh` to be an error, passing `--javacopt="-Xep:FallThrough:ERROR"` (or adding it to your `.bazelrc`) is the recommended way to do that.

We didn't make that check an error by default for Bazel, because it requires the use of `// fall through` comments, which isn't a convention in all codebases that might be using Bazel.

**Comment by regisd** [comment]
Makes sense
