### ISSUE TITLE
Build Event Protocol upload failed: baseline_coverage.dat (No such file or directory)

### ISSUE THREAD

**Issue by sgreenstein** [bazelbuild/bazel#6395]
### Description of the problem / feature request:

When running a bazel build collecting code coverage and using remote caching, the build fails with an error about the Build Event Protocol upload failing.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

90% reproducible. If it works for you the first time, try it again.

Empty WORKSPACE file.

BUILD file:

```
cc_test(name = "test1",srcs = ["test1.cc"],)
...
cc_test(name = "test1000",srcs = ["test1000.cc"],)
```

test1.cc - test1000.cc:

```
int main() {
  return 0;
}
```

tools/bazel.rc:

```
build --google_default_credentials
build --google_auth_scopes=https://www.googleapis.com/auth/cloud-source-tools
build --bes_backend=buildeventservice.googleapis.com
build --bes_timeout=10s
build --bes_results_url=https://source.cloud.google.com/results/invocations
build --project_id=<project id>
build --remote_cache=remotebuildexecution.googleapis.com
build --remote_instance_name=projects/<project name>/instances/default_instance
build --noremote_upload_local_results
build --spawn_strategy=standalone
build --genrule_strategy=standalone
build --tls_enabled=1
build --remote_accept_cached=true
build --remote_local_fallback
```

Run a build with coverage command:
```
$ bazel build ...  --collect_code_coverage --linkopt --coverage
INFO: Streaming Build Event Protocol to https://source.cloud.google.com/results/invocations/e2bbc3a9-0baa-45e3-8f0b-84af6623212f
INFO: Analysed 1004 targets (20 packages loaded).
INFO: Found 1004 targets...
ERROR: Build Event Protocol upload failed: /usr/local/google/home/sgreens/.cache/bazel/_bazel_sgreens/618f66811e693d3d8fe99c35d7530ea8/execroot/__main__/bazel-out/k8-fastbuild/testlogs/tests/test990/baseline_coverage.dat (No such file or directory)
ERROR: /usr/local/google/home/sgreens/test/tests/BUILD:916:1: C++ compilation of rule '//tests:test916' failed: Unexpected IO error.: Call failed with not retriable error: io.grpc.StatusRuntimeException: CANCELLED: Call was interrupted
ERROR: BuildEventServiceTransport internal error
INFO: Elapsed time: 5.246s, Critical Path: 0.62s
INFO: 58 processes: 58 local.
FAILED: Build did NOT complete successfully
```

### What operating system are you running Bazel on?

Debian

### What's the output of `bazel info release`?

release 0.17.2

Is also broken with 0.18.0.

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

It worked in bazel 0.15.0 and bazel 0.16.1

**Comment by sgreenstein** [comment]
I'm able to repro in 0.19.0

**Comment by sgreenstein** [comment]
I'm able to repro in 0.21.0

**Comment by sgreenstein** [comment]
I'm able to repro in 0.23.2

**Comment by iirina** [comment]
This is happening because we don't generate the baseline coverage report for C++ (see #5716). We can temporarily remove the file as an action output, but even then I'm not sure coverage will work remotely (see #7614 and #7247).
