### ISSUE TITLE
Building pure C binaries

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel#64]
`cc_*` rules such as `cc_library` and `cc_binary` will build pure C binaries if the file extensions of the source files are `.c` rather than one of the standard C++ file extensions. While these build rules are listed under "C/C++" in the Build Encyclopedia, it would be helpful to add a note to clarify that these rules will do the right thing when compiling only C code.

It may also be good to provide macros such as `c_library` and `c_binary` and a CROSSTOOL config for C that set the correct flags for building C binaries.

**Comment by jhi** [comment]
Also:

being able to switch easily between different sets of cc binaries and flags would be nice: I routinely want to test my code with, say, clang, gcc, g++, and if I could be bothered to get a license, also icc.  

But while the flags available between even these closely-related compilers intersect a lot, there are incompatibilities: clang has -Weverything, gcc has not, some -W flags do not make sense for C++ or they make sense only for C++, certain -fflags only work for some subset, etc.

**Comment by hanwen** [comment]
they are already called "C/C++ rules" in the header. I'm not sure what to do here.

For @jhi 's comment - you can switch compilers by switching the crosstool. See eg 

 https://github.com/bazelbuild/examples/blob/master/android-prebuilts/README.md

for an example of how to configure and use an alternate compiler.  I suppose you could use select() to make the flags depend on the compiler.
