### ISSUE TITLE
Fedora linux support

### ISSUE THREAD

**Issue by hartsantler** [bazelbuild/bazel#640]
It would be great if bazel had install instructions for Fedora, even better if there was a prebuilt binary and RPM package.

**Comment by hartsantler** [comment]
i just git cloned this repo, and ran `./compile.sh`, i have java installed but the script complains it can not find JAVA_HOME.

```
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh build /path/to/bazel
🍃  Building Bazel from scratchwhich: no javac in (/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/brett/.local/bin:/home/brett/bin)
readlink: missing operand
Try 'readlink --help' for more information.

JDK not found, please set $JAVA_HOME.
```

First of all, why a bash script?  A simple python script would do the job better.  Second, why should I have to set my JAVA_HOME environment variable?  If JAVA_HOME is not defined, then the installer script should look for it in commonly installed places like `/opt`.

If bazel wants to be a build tool taken seriously, it needs to be easily installable on at least Debian and Fedora.

**Comment by davidzchen** [comment]
@hartsantler Thanks for reporting this. We will take a look.

In the meantime, can you try using the latest Bazel binary installer: http://bazel.io/docs/install.html?

**Comment by damienmg** [comment]
The compile script complains because your javac is not on the path and no
JAVA_HOME is specified

**Comment by davidzchen** [comment]
@hartsantler How did you install Java on your Fedora machine? Which version of Java do you have?

**Comment by hartsantler** [comment]
i had java installed but was missing the sdk, i got bazel to compile by running:
`sudo yum install java-1.8.0-openjdk`
i did not have to manually set my JAVA_HOME environment variable.
