### ISSUE TITLE
Bazel's NO_PROXY doesn't work while setting HTTP_PROXY or HTTPS_PROXY

### ISSUE THREAD

**Issue by weixiao-huang** [bazelbuild/bazel#6400]
### Description of the problem / feature request:

I want to use bazel to build a go project using [rules_go](https://github.com/bazelbuild/rules_go), I have some external packages in my `WORKSPACE` file. Some of these packages are in github, golang.org, gopkg.in etc., which can be fetched from internet. The other packages are placed in internal network. However, because I'm in China, for fetching the external internet packages from github, golang.org, gopkg.in, I must set a HTTP_PROXY and HTTPS_PROXY for enjoying a high speed. But for fetching the packages in internal network, I must set NO_PROXY.

However, if I set the HTTP_PROXY, HTTPS_PROXY and NO_PROXY and execute `bazel build //...`, the external packages can be fetched but the internal packages cannot be fetched. Seems bazel doesn't respect NO_PROXY. I use `htop` and find that bazel will hang in 

```
/cache/dfb1ce1d07f3a35961571a3241719bc6/external/bazel_gazelle_go_repository_tools/bin/fetch_repo --dest /cache/dfb1ce1d07f3a35961571a3241719bc6/external/<internal_package_name> --rev 84535ec2d57a694b372ec5effa446098b2c2202f --importpath <internal_package_address>
```

The interesting thing is that if I execute the command above directly in the terminal, it can be successfully executed and fetch the packages in the relative directory.

And if I unset HTTP_PROXY and HTTPS_PROXY, I can successfully fetch the internal packages by using bazel.

### Feature requests: what underlying problem are you trying to solve with this feature?

I notice that while I set HTTP_PROXY, bazel will show a log about 

```
WARNING: detected http_proxy set in env, setting no_proxy for localhost.
```

I try to find it in the [sources](https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/blaze.cc#L1425) and discover that it seems bazel will set NO_PROXY directly to `localhost,127.0.0.1,0:0:0:0:0:0:0:1,::1` regardless of the origin value of NO_PROXY while HTTP_PROXY exists. Than I change the code to make it respects the origin value of NO_PROXY and use bazel to build it.

However, using the bazel built by myself, it also not worked for me to respect NO_PROXY. It cannot fetch the internal packages yet. I also try to reference https://github.com/bazelbuild/bazel/pull/4307 and https://github.com/bazelbuild/bazel/issues/4299, but it seems not a solution for my problem.

### What operating system are you running Bazel on?

I use bazel 0.17.2 in ubuntu 18.04 and 16.04, both have the same bug

### What's the output of `bazel info release`?

`release 0.17.2`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

I try to change code like [this](https://github.com/weixiao-huang/bazel/commit/2269036e434a7177782e06590eee8495a08080e1), and use bazel to rebuild bazel

```
bazel build //src:bazel
```

but the problem still exists.

###  Have you found anything relevant by searching the web?

I just find some issues in bazel's git, but it seems that they have few helps for my problem

- https://github.com/bazelbuild/bazel/pull/4307
- https://github.com/bazelbuild/bazel/issues/4299

**Comment by weixiao-huang** [comment]
It seems that it's the problem of bazel-gazelle, bazel-gazelle doesn't add NO_PROXY into it's fetcher, it only add HTTP_PROXY and HTTPS_PROXY. After add NO_PROXY into bazel-gazelle, it can successfully work.
However, I wonder the codes in bazel that bazel will set NO_PROXY directly to `localhost,127.0.0.1,0:0:0:0:0:0:0:1,::1` regardless of the origin value of NO_PROXY while HTTP_PROXY exists. Whether this design have some problem? So I try to open a pull request: https://github.com/bazelbuild/bazel/pull/6399, if it's convenient to you, could you please help me to find the potential bugs in this design?
Thanks

**Comment by lpapp-polatis** [comment]
Hi, is there a short term plan to fix this?

**Comment by tetromino** [comment]
The correct fix for this is to use gRPC's grpc.enable_http_proxy channel argument. We should not be munging no_proxy/NO_PROXY env variables at all.

I have a commit ready internally which fixes it, but it's pending on updating the gRPC version bundled with Bazel (issue #7259). Stay tuned!

**Comment by tetromino** [comment]
PR #7259 is in, so this is now unblocked.
