### ISSUE TITLE
incompatible_disallow_load_labels_to_cross_package_boundaries: make 'load' statement respect package boundaries

### ISSUE THREAD

**Issue by haxorz** [bazelbuild/bazel#6408]
### Description of the problem / feature request:

`load('//a:b/c.bzl', 'doesntmatter')` currently checks that '//a' is a package but doesn't check that '//a/b' is not.

### Feature requests: what underlying problem are you trying to solve with this feature?

we currently have a "label crosses subpackage boundary check" elsewhere (e.g. for target names inside of a package). so we should add this for the sake of consistency.

### Any other information, logs, or outputs that you want to share?

we should piggyback/unify the existing mechanism for the existing "label crosses subpackage boundary check" in PackageFunction.java.

**Comment by dslomov** [comment]
This is a breaking change, right? Which flag guards it? How do users migrate?

**Comment by laurentlb** [comment]
Yes, it's a breaking change.
The commit above adds an incompatible flag: https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#load-label-cannot-cross-package-boundaries

We need tooling to help the migration (cc @vladmos).

**Comment by dslomov** [comment]
What is missing for migration: migration docs, length of migration window. After these are done, please add "migration-ready" label.

**Comment by laurentlb** [comment]
**Migration notes**

This will fail when a label crosses packages, i.e. when the position of the colon is not correct in a label. The error message will tell you what is the correct label to use instead.

Read more about the label syntax here: https://docs.bazel.build/versions/master/build-ref.html#labels

**Comment by laurentlb** [comment]
Downstream projects that fail with this flag (https://buildkite.com/bazel/bazel-at-release-plus-incompatible-flags/builds/56):
 - rules_k8s
 - rules_typescript
 - TensorFlow

**Comment by philwo** [comment]
This flag was not flipped in time for the Bazel 0.23.0 release and will thus be postponed to Bazel 0.24.0.

**Comment by katre** [comment]
This issue was tagged as "breaking-change-0.24" but does not appear ready to be flipped in the [0.24.0 release](https://github.com/bazelbuild/bazel/issues/6968). If this is incorrect please comment on that issue and discuss with me.
