### ISSUE TITLE
Add --build_lang_filters option

### ISSUE THREAD

**Issue by ivyxyz** [bazelbuild/bazel#6410]
### Description of the feature request:

Similar to --test_lang_filters, build_lang_filters is useful when a configuration can only build or be useful for a few languages.

### Feature requests: what underlying problem are you trying to solve with this feature?

For example, when building with address sanitizer, Go rules does not build. Only cc_binary targets are needed. https://github.com/bazelbuild/rules_go/issues/1306

###  Have you found anything relevant by searching the web?

No.

**Comment by aiuto** [comment]
Related to #3780

**Comment by aiuto** [comment]
This is probably better served with incompatible_target_skipping. I'm not closing it yet, so that we can revisit it in Q2.

**Comment by aiuto** [comment]
Closing because it will be handled as part of #3780.  That will do it better than having another flag.
