### ISSUE TITLE
Detect about --output_user_root pointing to a slow volume, and document how to reconfigure it

### ISSUE THREAD

**Issue by IgorMinar** [bazelbuild/bazel#6411]
### Description of the problem / feature request:

I'm using bazel 0.18 on linux (glinux) and by default bazel picked ~/.cache/bazel as the output_user_root, which happens to my map to a remote network-connected volume.

I was not aware of this and was wondering why my bazel builds were running significantly slower than what I'd expect them to. Occasionally I got slow-reads warnings, but they were not actionable enough for me to realize what was going on.

Once I realized what was going on, I had a hard time figuring out how to reconfigure my system. The [docs mention](https://docs.bazel.build/versions/master/user-manual.html#flag--output_user_root) `--output_user_base` but don't explicitly state that this setting affects both `--output_base` and `--install_base` (there is just a vague sentence "*option to choose an alternate base location for all of Bazel's output (install base and output base) if there is a better location in your filesystem layout.*" which easily gets lost on the long page).

Additionally, I couldn't find instructions on how to put this flag into my `~/.bazelrc`. It's not obvious that this flag is associated with the `startup` command, and that the `~/.bazelrc` should look like this:

```
# put all the output (--output_base) and install (--install_base) files under /tmp/bazel
startup --output_user_root=/tmp/bazel/
```

I recommend the following improvements:

- fix the documentation to include clear info about how to setup bazelrc
- augment the slow read warning to point to the doc that explains when these slow reads might be happening and how to reconfigure the system not to use a remote filesystem.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 0.18.0

###  Have you found anything relevant by searching the web?

https://docs.bazel.build/versions/master/user-manual.html#flag--output_user_root

**Comment by philwo** [comment]
Assigning to the performance team, because this has nothing to do with EngProd. :)
