### ISSUE TITLE
Debian package should only suggest JDK instead of depending on it

### ISSUE THREAD

**Issue by gjasny** [bazelbuild/bazel#6412]
Right now the published Debian / Ubuntu package declares a (hard) dependency to a Java SDK. But the bazel version included in the `deb` file is already a standalone one that comes with a bundled Java runtime.

Would you accept a PR which downgrades the `Depends` to a `Suggests`? The [Debian Policy](https://www.debian.org/doc/debian-policy/ch-relationships.html) describes `Suggests` as:

> This is used to declare that one package may be more useful with one or more others. Using this field tells the packaging system and the user that the listed packages are related to this one and can perhaps enhance its usefulness, but that installing this one without them is perfectly reasonable.

Thanks,
Gregor

**Comment by dslomov** [comment]
I think such PR will be welcome - any objections @philwo ?

**Comment by philwo** [comment]
That would be great, yes. Thanks!
