### ISSUE TITLE
Add subdomains for common G Suite services

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/bazel#6413]
I'm late to the party as I just realized we had a G Suite domain for Bazel... but nice!

This request is about exposing common G Suite services as subdomains of `bazel.build` to make them easier to reach when one is not yet logged in. (The first sign in I did was from the invitation email, but then it took me a little bit of time to figure out how to log a second machine in.)

Some I can think of are `{calendar,docs,drive,hangouts,mail}.bazel.build`. I'd personally be happy with just `drive` and `mail`, but why not create others.

I bounced this idea off @philwo earlier today and he thought this would be a good idea, if only to get more familiar with customizing our DNS settings. He also suggested assigning this to @fweikert, so doing so now.

**Comment by philwo** [comment]
@jmmv The one thing I don't understand is why you had / have trouble signing in. The G Suite accounts are nothing special - whether you go to mail.bazel.build or mail.google.com, you can simply sign-in with your username@bazel.build and password. There's no need to go to any special URL to use these accounts.

Adding additional accounts works the same as for any other secondary Google account you might have: Click the little profile icon in the top-right corner of any Google product and you'll get a drop-down with all your logged in accounts and an "Add account" button.

Using Chrome profiles is another nice way to separate the accounts and make them easily accessible.

I don't even know if *.bazel.build aliases would do anything besides redirecting to the normal login form or service? There's also this strange notice in the documentation:

"Note that if you've activated a secure protocol on your domain, Google Custom URL redirection does not work as it is not compatible with TLS/SSL redirection which forces encrypted browsing."

**Comment by jmmv** [comment]
You know what... that may not have crossed my mind. I do have those aliases for my personal domain and I have used them enough that somehow expected the same to be true for bazel.build.

You are right that they just redirect to the normal login form, though I have never had issues with TLS/SSL.

So at this point I don't think this is worth doing. Let's keep things simple?

**Comment by philwo** [comment]
> So at this point I don't think this is worth doing. Let's keep things simple?

👍😊
