### ISSUE TITLE
Add the ability to request additional outputs from java_common.compile

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#6415]
This is required when additional outputs may be created during the compilation process. For example the [Android Data Binding Java plugin produces additional outputs](https://github.com/bazelbuild/bazel/blob/4ebf6c0529313be09210501aa2f010be1bf8913d/src/main/java/com/google/devtools/build/lib/rules/android/AndroidCommon.java#L502) that need to be collected and propagated up the graph.

**Comment by ahumesky** [comment]
An annotation processor might also need inputs besides java source files, e.g. from Android databinding:
https://github.com/bazelbuild/bazel/blob/926cfbdfd57e468cf7f3272a8095c62dfd12f493/src/main/java/com/google/devtools/build/lib/rules/android/AndroidCommon.java#L530-L534

**Comment by cheister** [comment]
Are there any plans to make the `annotation_processor_additional_inputs` option available to java_library?
