### ISSUE TITLE
Add Java-Starlark API for propagating exports and plugins information

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#6417]
There is a need for constructing a [JavaInfo](https://docs.bazel.build/versions/master/skylark/lib/JavaInfo.html#JavaInfo) with the purpose of propagating information without it being the result of compiling something.

The API must not have any of the jar-related fields (e.g. `output_jar`, `compile_jar`, `source_jar`, `sources`, etc) present in the `JavaInfo()` constructor and must be limited only to `exports`, `plugins`, `exported plugins`.

**Comment by ittaiz** [comment]
What about deps/runtime_deps?

**Comment by ittaiz** [comment]
No but I also don’t understand the current decision of only exports. Maybe
you can add a bit more info? You might be completely right, I was just
triggered by the asymmetry.

**Comment by ittaiz** [comment]
Is this superseded by #8867 ?

**Comment by iirina** [comment]
Yup it looks like a duplicate. Let's keep #8867 for tracking and close this as dupe, although it's the other way around.
