### ISSUE TITLE
Test fails if give function long name

### ISSUE THREAD

**Issue by dbabkin** [bazelbuild/bazel#6418]
Steps to reproduce:

1) run: bazel test //src/test/shell/bazel:bazel_enable_disable_tools_defaults_flag_test
expected result: passed

2) vim src/test/shell/bazel/bazel_enable_disable_tools_defaults_flag_test.sh
change line 91 from 
`function test_independent_target_doesnt_depend_on_flag (){`
to 
`function test_independent_target_doesnt_depend_on_flag_very_long_name_very_long_name_very_long_name_very_long_name_very_long_name (){
`
3) run: bazel test //src/test/shell/bazel:bazel_enable_disable_tools_defaults_flag_test
expected result: passed
actual result: failed without any error in log file

**Comment by philwo** [comment]
Looks like a bug in our test framework (or maybe in bash?). Unlikely to fix, because people can just use a shorter test name, but if someone wants to send a PR, I'm happy to review it.
