### ISSUE TITLE
Crash when depending on an objc_library which in turn has dependencies

### ISSUE THREAD

**Issue by tkoeppe** [bazelbuild/bazel#6419]
### Description of the problem / feature request:

Given an `objc_library` that contains `deps`, if another `cc_library` or `cc_binary` depends on that first library, Bazel crashes.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Check out https://github.com/deepmind/lab/tree/bcad27ca04a3f264f7475d03ee3d6a306d1cd619 and run `bazel build //:game --apple_platform_type=macos`. This crashes Bazel. (This is just the tip of the `macos` branch of github.com/deepmind/lab.)

### What operating system are you running Bazel on?

Mac OSX, but this seems independent of system (e.g. it also happens on Linux).

### What's the output of `bazel info release`?

`release 0.18.0`

(It appears that the problem is not present in `0.17.2-homebrew` (?).)

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

E.g. Travis sees the same problem (not using the `--apple_platform_type` flag): https://travis-ci.org/deepmind/lab/jobs/442616087

A workaround is to _not_ have any `deps` in the `objc_library`. I imagine that a minimal repro step might look as follows: Make a `cc_library` A, an `objc_library` B that depends on A, and another `cc_library` C that depends on B. Attempting to build C should cause the crash.

**Comment by tkoeppe** [comment]
Aha, yes, thanks. Feel free to close this then.

I have since removed the need for ObjC from the codebase -- console logging is ever so much better anyway, who needs UIs! So I'm no longer affected by this.

**Comment by scentini** [comment]
Closing as suggested.
