### ISSUE TITLE
Docs do not mention third_party requirements for a license

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#642]
I added a directory in my toplevel called third_party, and when building a rule within it I got an error:
```
ERROR: /Users/endobson/tmp/grpc-bazel/third_party/openssl/BUILD:78:1: third-party rule '//third_party/openssl:libssl-deb' lacks a license declaration with one of the following types: notice, reciprocal, permissive, restricted, unencumbered, by_exception_only.
```

Searching for third_party in the bazel docs does not turn up anything about this restriction: http://bazel.io/search.html?q=third_party

**Comment by kchodorow** [comment]
To work around this, you can add a `licenses(["notice"])` line to your BUILD files in the third_party directory.

**Comment by kamalmarhubi** [comment]
Is this restriction going to be relaxed? It seems a bit inconsistent to enforce this for `third_party` but not for things like `new_http_archive`.

**Comment by damienmg** [comment]
Yes AFAICT it should be relaxed and replaced by the constraint mechanism.

**Comment by trainman419** [comment]
+1. I ran into this today and was not able to find any documentation about which licenses are available or what the license() command does.

**Comment by davidzchen** [comment]
Here is the documentation on `licenses`: http://bazel.io/docs/be/functions.html#licenses. I agree that the documentation should be fleshed out a bit more since it doesn't really mention which license-type strings are available.

**Comment by kchodorow** [comment]
I added some documentation here: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/packages/PackageFactory.java#L722-L741, which I incorrectly thought would be included in the generated docs.  We should move it somewhere else so it will show up in the documentation.

**Comment by gruberjuliannama** [comment]
bit inconsistent to  the documentation. it will show up in the documentation.?

**Comment by kchodorow** [comment]
Eventually... it needs to be moved to a different file.

**Comment by trainman419** [comment]
The existing documentation describes **what**, but not **why**.

From some digging, it appears that `licenses` somehow interacts with the `--check_licenses` command-line flag. Is there any documentation describing this flag? It would be good if the documentation for `licenses` linked to that documentation.
