### ISSUE TITLE
Provide a way to gradually migrate from old flags to platforms

### ISSUE THREAD

**Issue by aragos** [bazelbuild/bazel#6426]
The new Bazel [platforms](https://docs.bazel.build/versions/master/platforms.html) are a key element for many new features. However not all projects and rule sets are going to start using them at the same time and so a mechanism is needed to allow gradual migrate from the current approach (flags like `--cpu` and `--crosstool_top`) to the new one. This issue tracks the design and implementation of that mechanism.

**Comment by aragos** [comment]
I never mentioned the design here but it's been reviewed and is now in implementation: https://docs.google.com/document/d/1Vg_tPgiZbSrvXcJ403vZVAGlsWhH9BUDrAxMOYnO0Ls

**Comment by katre** [comment]
This is now available: see https://docs.bazel.build/versions/master/platforms-intro.html#platform-mappings for details.
