### ISSUE TITLE
incompatible_restrict_attribute_names: Fail when calling rule() with non-identifier attr names

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#6437]
This should probably be an error:

```python
foo = rule(
    implementation = ...,
    attrs = {"!@#$%": attr.string()}
)
```

**Comment by dslomov** [comment]
How bad is the breakage here?

**Comment by laurentlb** [comment]
Breakage is expected to be rare. The only use-case I know is https://github.com/bazelbuild/bazel/issues/8568#issuecomment-500881228, but the $ prefix should be replaced by a `_` prefix.

**Comment by dslomov** [comment]
Closing since the flag is flipped.
