### ISSUE TITLE
No deprecation warning for java targets

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#644]
In the following BUILD files, no deprecation warning is shown when building hello-world:

```
java_binary(
    name = "hello-world",
    main_class = "com.example.myproject.Greeter",
    runtime_deps = [":hello-lib"],
)

java_library(
    name = "hello-lib",
    deprecation = "Gone",
    srcs = glob(
        ["*.java"],
        exclude = ["HelloErrorProne.java"],
    ),
)
```

Expected: deprecation warning

**Comment by ulfjack** [comment]
That's probably intentional - i.e., that rules don't give a deprecation warning for dependencies within the same package. I highly doubt that this is java-specific.

**Comment by dslomov** [comment]
Same for:
java/a/BUILD:
```
package(default_visibility = ["//visibility:public"])

java_library(name = 'A', deprecation = 'Gone')
```
java/b/BUILD
```
java_library(name = 'B',
             srcs = ['B.java'],
             deps = ['//examples/java-native/src/main/java/a:A'])
```
`deprecation` attribute is Java specific afaics.
The root cause is that the relevant code is not open-sourced.

**Comment by ulfjack** [comment]
http://bazel.io/docs/be/c-cpp.html says the C++ rules also have a
deprecation attribute.

**Comment by meisterT** [comment]
Deprecation is not displayed for every transitive target in the build but only toplevel targets to avoid logspam:
https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/TargetPatternPhaseFunction.java;l=77;drc=9a6997d595fbf3447e911346034edfbde7d8b57e;bpv=1;bpt=1
