### ISSUE TITLE
Reset the PY2/PY3 mode along data dependencies

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#6441]
The part of the build configuration that chooses the python major version can be either PY2, PY3, or unknown. Currently when it's set, it stays that way for all transitive deps. We should reset it across data deps.

The rationale is that you want to enforce (via any `srcs_version` attrs that are present) that the source files and libraries you depend on have the same version as you, but you don't want to require that of other python binaries that you invoke as a separate process.

Implementation wise, it's straightforward to do this for the case of a `py_binary`'s `data` attr. It's not so clear how to do it when you have a src file generated by another type of rule, like a `genrule` or `sh_binary`. Would you have to attach the transition to all sorts of attributes, or is there a way to attach the transition to a particular entry of the `py_binary`'s `srcs` based on the kind of rule that generates it? (Though conditioning on rule type rather than provider is a code smell too.) TBD.

**Comment by brandjon** [comment]
This proposal is rendered obsolete by the (nearly completed) work described in #6583.

**Comment by lefevere-lyft** [comment]
> This proposal is rendered obsolete by the (nearly completed) work described in #6583.
Is there something specific that users have to do to avoid the fact that python configurations are propagated through data?
I have the following simple example of a c++ data dependency used by both PY2 and PY3 targets and the c++ gets built twice. I would like to build it once. 
I tried looking at #6583 but I could not find anything relevant to this problem there.
```
cc_binary(
  name = "cpptest",
  srcs =["cpptest.cc"]
)

py_binary(
  name = "py2test",
  srcs = ["pytest.py"],
  main = "pytest.py",
  python_version = "PY2",
  data = [
      ":cpptest"
  ]
)

py_binary(
  name = "py3test",
  srcs = ["pytest.py"],
  main = "pytest.py",
  python_version = "PY3",
  data = [
      ":cpptest"
  ],
)
```
@brandjon Thanks.
