### ISSUE TITLE
Documentation/behavior mismatch with alias + config_setting

### ISSUE THREAD

**Issue by jfancher** [bazelbuild/bazel#6449]
### Description of the problem / feature request:
The [documentation](https://docs.bazel.build/versions/master/be/general.html#alias) claims that:
> Aliasing only works for "regular" targets. In particular, package_group, config_setting and test_suite rules cannot be aliased.

However, this does not seem to be accurate, at least for `config_setting`. You can create an `alias` with `actual` set to a `config_setting`, and then the `alias` may be used as a condition itself.

Is this a documentation bug or is this not supposed to work (or does it not work in some subtle way that I'll discover down the line)?

The context is that I would like to turn "raw" `config_setting`s  into something more akin to feature flags, where several different possible values for a setting map to a single condition that makes more sense for consumers. Aliasing works for this case although it seems a bit hacky; if there's a better way to achieve the same thing I'd be interested to know.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Full reproducer [here](https://github.com/jfancher/bazel-issues/tree/alias_config_setting). 

### What operating system are you running Bazel on?

macOS 10.13.2

### What's the output of `bazel info release`?

`release 0.18.0`

###  Have you found anything relevant by searching the web?

No

**Comment by gregestren** [comment]
Confirmed the behavior you're seeing.

From what I can see from the review history, it looks like there was never any design intention to exclude config_setting from aliases. Pinging @lberki for confirmation or rebuttal.

As to your deeper goal, that's an interesting use of the feature. It seems like another variant or [OR chaining](https://docs.bazel.build/versions/master/configurable-attributes.html#or-chaining). Do you see this as bringing novel functionality even beyond that?

**Comment by lberki** [comment]
Without engaging with the meat of the bug report, whether aliasing works is different for each rule you mentioned above:
 * `config_setting` should just work, I think it's a documentation bug
 * `package_group` may or may not work -- they are regrettably a little different from regular configured targets, so I wouldn't be surprised if there is a bug lurking somewhere that prevents them from working with `alias`, but I see no fundamental reason for them not to. I'd prefer them to be regular rules since they are special mostly for historical reason and then this wouldn't even be a question.
* `test_suite` is special-cased in a few places, so I'd be even less surprised if `alias` did not work for them than for `package_group`. It should, though.

**Comment by gregestren** [comment]
This approach doesn't look bad to me at all, and I think probably fits your use case as good as you're going to get.

Re: the documentation: what wording would you find clearer given the the comment above? Happy to patch or take a patch from you.

**Comment by jfancher** [comment]
Sorry, was that last question for me? I'm not sure I have enough context to answer -- I don't know what constitutes a 'regular' rule.

From a little more experimentation, neither `package_group` nor `test_suite` may be aliased. However:
- `package_group` is listed as a function, not a rule, so I'm not sure why there's the expectation that it would work in the first place.
- `test_suite` doesn't error or anything, it just doesn't run the tests. That seems to be covered by the next part of the doc that says "Tests are not run if their alias is mentioned on the command line."

So maybe the whole line is redundant and could be removed?

**Comment by gregestren** [comment]
Yeah, removing the line line sounds easiest. Will do...
