### ISSUE TITLE
Merging WORKSPACE for shared third_party management

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#645]
The use case I want to enable is N git repos which can share a set of third party dependencies (maven jars).

I want 1 repo to store all the third party dependencies, so in each of each of these repos can add this git_repository in the workspace, and then access the curated version dependencies in this one repo.

Copying this across the repos is a bit of an ugly solution to keep in sync. If we had the ability to import the maven_jars/external repositories from an external repository, then it becomes as clean as updating a git tag/sha to move forward.

**Comment by johnynek** [comment]
@haxorz and I were discussing this a bit on IRC. Just tagging him here.

**Comment by johnynek** [comment]
Side note: it seems a work-around for this problem would be to make a skylark rule to curl jars. Then I think I could get java/scala dependencies to consume those output jars of the process. By doing this, we can modularize somewhat and not put all the jars in one huge WORKSPACE.

Though, it would be preferable to import a workspace with a namespace prefix so that I could say:
```
#WORKSPACE in repo foo
maven_jar(name = "hadoop", ...)

#WORKSPACE in repo bar
git_repository(name = "foo"
  ...)
#now I can refer to @foo.hadoop// etc...  
```

**Comment by damienmg** [comment]
Wouldn't have a skylark macro with your list of maven_jar in it in your third_party repository do the trick?
Just like we do for third party dependency of skylark rules?

**Comment by johnynek** [comment]
@damienmg I think this would work, if you could load a skylark macro from a remote dependency. Can you do that now? Last I checked, load took a path, and not a label.

**Comment by damienmg** [comment]
We cannot do it yet. but @jhfield is working on it and said it should be shiped this week and we identified a problem for the load in the workspace file internally and I was planning to work on the fix starting tomorrow. So it should happens by the end of the week at HEAD hopefully (problem is we have holidays after that so if we miss it it won't happens before ~Jan 10)

**Comment by johnynek** [comment]
Thanks. I'm really looking forward to this since distributing skylark plugins as a remote git repos seems like a nice way to go.

**Comment by johnynek** [comment]
@damienmg did this get merged? Is there an easy way to track this feature (other than watching this ticket)?

**Comment by kchodorow** [comment]
Yes, 1ea7fc370f0605be2185868f9371f6e04c26a502 added `load(label)` syntax.

**Comment by damienmg** [comment]
But it does not work from the WORKSPACE file yet. My next bug to address
should fix that problem.

**Comment by damienmg** [comment]
This should be fixed now. The only left thing is handling correctly build_file. As there is a workaround (build_file_content) and a separate bug for the build_file parameters, I will close this one.
