### ISSUE TITLE
bazel-workspace-name output symlink should use the declared name in WORKSPACE file

### ISSUE THREAD

**Issue by haikalpribadi** [bazelbuild/bazel#6454]
### Description of the feature request:

At the moment, the output symlink for `bazel-<workspace-name>` uses the workspace's directory name as the `<workspace-name>`, instead of the name of the workspace declared in the `WORKSPACE` file (e.g. `workspace(name = "grakn_core")`).

### Feature requests: what underlying problem are you trying to solve with this feature?

I would like to have the Bazel output directories to be more meaningful and intuitive. At the moment, the `bazel-<workspace-name>` doesn't actually use the name of the workspace which the user expects it to be, which is the name she/he declared in the `WORKSPACE` file.

### What's the output of `bazel info release`?

release 0.18.0

**Comment by janakdr** [comment]
Duplicate of #5506
