### ISSUE TITLE
[Regression 0.17.2 -> 0.18] Turbine failure  

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#6456]
### Description of the problem / feature request:

Upgrading from 0.17.2 to 0.18 we suddenly see turbine failures

```
(17:38:03) ERROR: /workspace/...-hjar.jar: Compiling Java headers ...-hjar.jar (11 files) failed (Exit 1)
An exception has occurred in turbine.
java.lang.AssertionError: VOID_TY_SIG
	at com.google.turbine.binder.bytecode.BytecodeBinder.bindTy(BytecodeBinder.java:89)
	at com.google.turbine.binder.bytecode.BytecodeBoundClass.bindMethod(BytecodeBoundClass.java:381)
	at com.google.turbine.binder.bytecode.BytecodeBoundClass.access$600(BytecodeBoundClass.java:66)
	at com.google.turbine.binder.bytecode.BytecodeBoundClass$13.get(BytecodeBoundClass.java:365)
	at com.google.turbine.binder.bytecode.BytecodeBoundClass$13.get(BytecodeBoundClass.java:356)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:166)
	at com.google.turbine.binder.bytecode.BytecodeBoundClass.methods(BytecodeBoundClass.java:406)
	at com.google.turbine.binder.ConstEvaluator.evaluateAnnotation(ConstEvaluator.java:912)
	at com.google.turbine.binder.ConstEvaluator.evaluateAnnotations(ConstEvaluator.java:901)
	at com.google.turbine.binder.ConstBinder.bindMethod(ConstBinder.java:136)
	at com.google.turbine.binder.ConstBinder.bindMethods(ConstBinder.java:115)
	at com.google.turbine.binder.ConstBinder.bind(ConstBinder.java:92)
	at com.google.turbine.binder.Binder.constants(Binder.java:333)
	at com.google.turbine.binder.Binder.bind(Binder.java:106)
	at com.google.turbine.main.Main.compile(Main.java:97)
	at com.google.devtools.build.java.turbine.Turbine.compile(Turbine.java:76)
	at com.google.devtools.build.java.turbine.Turbine.compile(Turbine.java:69)
	at com.google.devtools.build.java.turbine.Turbine.main(Turbine.java:46)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

We don't have a repro yet

### What operating system are you running Bazel on?

linux (gcb/rbe)

### What's the output of `bazel info release`?

0.18.0

**Comment by laurentlb** [comment]
cc @aehlig

**Comment by cushon** [comment]
@lberki @iirina 

> We don't have a repro yet

It's hard to say without context, but all of the turbine changes that were included in 0.18 should have been validated and released internally by now, so this could be a Bazel-specific issue.

**Comment by ittaiz** [comment]
Tried to sculpt out a small part that I can share but unable so far.
This reproduces every time for us, can I add some logs to help you?

**Comment by ittaiz** [comment]
I can also add this is using oracle jdk 8

**Comment by ittaiz** [comment]
This class is causing the issue and if I remove the `@CrossOrigin` annotation the problem goes away.
Unfortunately this class by itself isn't enough and I'm not sure what else triggers it (there are around 40 files in that package).
Does that help?
```
package com.wix.some;

import org.springframework.web.bind.annotation.CrossOrigin;

public class SomeController  {

    @CrossOrigin
    public String do(String request) {
        return null;
    }

}
```

**Comment by cushon** [comment]
> `public String do(String request) {`

`do` is a keyword, so that example doesn't compile with javac either. Does this code definitely build with 0.17.2, or with 0.18 and `--nojava_header_compilation`?

**Comment by ittaiz** [comment]
You’re right about the “do”, I changed the text when copying. I’ll check soon

**Comment by ittaiz** [comment]
0.18.0 with `--nojava_header_compilation` passes. guessing 0.17.2 with `--experimental_java_header_compilation_disable_javac_fallback` will fail.
This is that AFAICT we don't have any annotation processing there.
Any idea why this is happening?

**Comment by cushon** [comment]
Thanks! I have a theory, do you mind checking if #6467 makes a difference?

**Comment by ittaiz** [comment]
Tomorrow morning (Israel time)?
Also do you mean to build bazel directly from that branch?

**Comment by cushon** [comment]
> Also do you mean to build bazel directly from that branch?

Yes, thanks: building at head with that PR patched in.

(I think the same problem will reproduce at head or with 0.18, and patching the fix into 0.18 should also fix the crash. If there ends up being a point release we can probably backport it.)

**Comment by ittaiz** [comment]
I checkout 0.18.0 tag, cherry-picked your commit from the PR and it indeed passes.
Any chance you can ask it will be cherry-picked to 0.18.0 (if they create a point release) and to 0.19.0?
Thanks!
We can live with the flag if a point release isn't an option but would rather not

**Comment by cushon** [comment]
> Any chance you can ask it will be cherry-picked to 0.18.0 (if they create a point release) and to 0.19.0?

paging @katre @lberki

This issue affects class reading of annotation declarations where the default value of an annotation method is a class literal for a non-class type, e.g. the `void.class` and `int.class` in:

```java
@interface V {
  Class<?> foo() default void.class;
  Class<?> bar() default int.class;
}
```

It was fixed in https://github.com/google/turbine/commit/7ef841275f620043690128b9aba1f9476609f449, and there's a PR to update Bazel's version of turbine to include the fix: #6467 

We validated this version of turbine internally and didn't encounter this, so it seems like a fairly rare problem. #6467 includes some other changes to turbine that I'm still validating, so it isn't risk-free.

**Comment by lberki** [comment]
Meh. Java compilation regressions are certainly cherrypick-worthy.

**Comment by ittaiz** [comment]
@aehlig is cutting a point version for 0.18.0
Can this be in?

**Comment by katre** [comment]
SGTM for 0.19.0 (#6116).

**Comment by cushon** [comment]
Ok, sounds like a plan. I did some internal validation of #6467 and it looks fine. Can I get a review for the PR?

**Comment by ittaiz** [comment]
So @aehlig can this get on to 0.18.1?

**Comment by katre** [comment]
In the 0.19.0rc7 build, bazel_determinism_test is failing:
```
src/main/java/com/google/devtools/build/lib/unsafe/UnsafeProvider.java:21: error: symbol not found sun.misc.Unsafe
import sun.misc.Unsafe;
```
https://storage.googleapis.com/bazel-buildkite-artifacts/ad153be8-d848-4ccc-b0df-4f0c631b1ab3/src/test/shell/bazel/bazel_determinism_test/attempt_1.log

**Comment by katre** [comment]
This actually appears to be a different error.

**Comment by cushon** [comment]
> This actually appears to be a different error.

As discussed offline that was the fix for #6433, which has been reverted.

This issue is fixed, and the fix will be included in 0.19.

**Comment by ittaiz** [comment]
So for 0.18.0 we should use the flag to turn it off?

**Comment by aehlig** [comment]
On Tue, Oct 23, 2018 at 11:32:59AM -0700, Ittai Zeidman wrote:
> So @aehlig can this get on to 0.18.1?

If this can be achieved with a clean cherry-pick on top of 0.18.0, sure.
Can you comment on #5963 with the precise patch you want to have cherry-picked?

Thanks,
Klaus


-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado
