### ISSUE TITLE
Bazel doesn't store java tests in remote cache

### ISSUE THREAD

**Issue by alexandrvb** [bazelbuild/bazel#6457]
### Description of the problem / feature request:

Bazel doesn't store java tests in remote cache.

### Feature requests: what underlying problem are you trying to solve with this feature?

I want to share test results across different machines.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

BUILD.bazel:
```
java_test(
    name = "java_test",
    size = "small",
    test_class = "AllTests",
    srcs = [
        "src/AllTests.java",
    ],
)

py_test(
    name = "python_test",
    srcs = [
        "src/python_test.py"
    ],
)
```

After running tests on the first machine, tests shound't run on the second. Only python tests are cached:
```
$ bazel test --remote_http_cache=http://10.0.0.1:8080 --remote_upload_local_results=false //...
Starting local Bazel server and connecting to it...
........
INFO: Analysed 2 targets (20 packages loaded).
INFO: Found 2 test targets...
INFO: Elapsed time: 3.890s, Critical Path: 0.58s
INFO: 3 processes: 2 remote cache hit, 1 linux-sandbox.
INFO: Build completed successfully, 11 total actions
//:python_test                                                  (cached) PASSED in 0.1s
//:java_test                                                             PASSED in 0.3s

Executed 1 out of 2 tests: 2 tests pass.
INFO: Build completed successfully, 11 total actions
```

### What operating system are you running Bazel on?

`Ubuntu 18.04.1`

### What's the output of `bazel info release`?

`release 0.15.2`

**Comment by alexandrvb** [comment]
The issue is reproduced on the 0.18.0.

**Comment by regisd** [comment]
With `remote_upload_local_results`, the cache is "read only". How do you know it contains this action?

**Comment by regisd** [comment]
What cache system are you using? Can you share the logs when you run `bazel test` on this example?

**Comment by alexandrvb** [comment]
@regisd I use two machines. First is uploading actions to remote cache, second (with `--remote_upload_local_results=false`) should reuse cached results from the first one. 

> What cache system are you using?

I tried nginx with webdav support and buchgr/bazel-remote-cache docker image.

> Can you share the logs when you run bazel test on this example?

Logs from docker container:
```
2018/10/24 11:49:32  GET 200      10.10.10.6 /ac/254b20368197353aa7aac92c1c52cc2f806ac2a2ae8402f4b67b00e1cb65fdf7
2018/10/24 11:49:32  GET 200      10.10.10.6 /cas/0073aca471c77580d2f1775efb0edafd12276a4248d2fb49d7b6c86556653e0c
2018/10/24 11:49:32  GET 200      10.10.10.6 /cas/84259478d31123aa36cf854a1a90baa4697d474cbc4bfa163fd4a29e0fd2d9d4
2018/10/24 11:49:33  GET 200      10.10.10.6 /ac/4f3fc3cc726ae738f384eecabb133c8964ceefe48d88250c2c6c94895097cd5b
2018/10/24 11:49:33  GET 200      10.10.10.6 /cas/eb55de67277a687f4e48eacaa6889cee9be14ae607a7739ae0a6a0ea5c83a530
2018/10/24 11:49:33  GET 200      10.10.10.6 /cas/e910235f479ef8e25dd60c50a2286d83915e4cf5c52dfdd9734f22f6f4a8f63d
2018/10/24 11:49:33  GET 200      10.10.10.6 /cas/59ce4142794225a1f38b79029bea63cf7ba3eea56a02a561edc034984264e6df
2018/10/24 11:49:33  GET 404      10.10.10.6 /ac/07b180db1e8512c2b7c9b6a9e76effab6b6e09fc91db73d96045fdc2f23d7dd9
```

The hash of last action (07b180db1e8512c2b7c9b6a9e76effab6b6e09fc91db73d96045fdc2f23d7dd9) on the second machine is differ from the first one. Versions of bazel and JDK don't differ. So I just want to find the difference between tho hosts..

**Comment by regisd** [comment]
Could you have different bazel build options? On both machines, try to call bazel with `--bazelrc=/dev/null`.

**Comment by alexandrvb** [comment]
Nothing changes. Hash of the last action on the second machine is still differ from the first one.

**Comment by buchgr** [comment]
@alexandrvb we do know that it works for java tests, but there might be something special about your setup. Can you provide a minimal reproducer please so that I can take a look? Thanks!

**Comment by alexandrvb** [comment]
@buchgr I created simple Vagrant configuration (you also need ansible for provision machines) with two machines with bazel and one with the cache: https://github.com/alexandrvb/bazel-cache-test

Steps for reproducing the issue:
1. `vagrant up`
2. Run tests on the first machine: `vagrant ssh node1` -> `cd /vagrant/bazeltests && bazel test --remote_http_cache=http://192.168.33.10:8080 //...`
3. Run tests on the second machine: `vagrant ssh node2` -> `cd /vagrant/bazeltests && bazel test --remote_http_cache=http://192.168.33.10:8080 //...`
4. As a result python tests are successfully downloaded from cache, but java tests are not found in the cache

```
vagrant@vagrant:~$ cd /vagrant/bazeltests && bazel test --remote_http_cache=http://192.168.33.10:8080 //...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analysed 2 targets (20 packages loaded).
INFO: Found 2 test targets...
INFO: Elapsed time: 12.480s, Critical Path: 1.03s
INFO: 4 processes: 3 remote cache hit, 1 linux-sandbox.
INFO: Build completed successfully, 11 total actions
//:python_test                                                  (cached) PASSED in 0.3s
//:java_test                                                             PASSED in 0.6s

Executed 1 out of 2 tests: 2 tests pass.
INFO: Build completed successfully, 11 total actions
```

**Comment by buchgr** [comment]
Hey @alexandrvb,

thanks! I believe the problem you are facing can be fixed by specifying --experimental_strict_action_env. We are also about to flip this flag to default: https://github.com/bazelbuild/bazel/pull/6263

**Comment by alexandrvb** [comment]
@buchgr it doesn't help
```
vagrant@vagrant:/vagrant/bazeltests$ bazel test --remote_http_cache=http://192.168.33.10:8080 --experimental_strict_action_env //...
Starting local Bazel server and connecting to it...
INFO: Analysed 2 targets (20 packages loaded).
INFO: Found 2 test targets...
INFO: Elapsed time: 11.098s, Critical Path: 0.93s
INFO: 4 processes: 3 remote cache hit, 1 linux-sandbox.
INFO: Build completed successfully, 11 total actions
//:python_test                                                  (cached) PASSED in 0.3s
//:java_test                                                             PASSED in 0.4s

Executed 1 out of 2 tests: 2 tests pass.
INFO: Build completed successfully, 11 total actions
```

**Comment by buchgr** [comment]
Bummer. For two runs, can you please generate an execlog [1] and diff it to see what's different?

[1] https://github.com/bazelbuild/bazel/tree/master/src/tools/execlog

**Comment by alexandrvb** [comment]
@buchgr I have a couple of differences in hashes of external/local_jdk/jre/lib/amd64/server/* libs, but as far as I understand it doesn't affect caching. Last diff is more interesting.

node1:
```
listed_outputs: "bazel-out/k8-fastbuild/testlogs/java_test/test.exited_prematurely"
listed_outputs: "bazel-out/k8-fastbuild/testlogs/java_test/test.infrastructure_failure"
listed_outputs: "bazel-out/k8-fastbuild/testlogs/java_test/test.outputs/outputs.zip"
listed_outputs: "bazel-out/k8-fastbuild/testlogs/java_test/test.outputs_manifest/ANNOTATIONS"
listed_outputs: "bazel-out/k8-fastbuild/testlogs/java_test/test.outputs_manifest/MANIFEST"
listed_outputs: "bazel-out/k8-fastbuild/testlogs/java_test/test.raw_splitlogs/test.splitlogs"
listed_outputs: "bazel-out/k8-fastbuild/testlogs/java_test/test.unused_runfiles_log"
listed_outputs: "bazel-out/k8-fastbuild/testlogs/java_test/test.warnings"
listed_outputs: "bazel-out/k8-fastbuild/testlogs/java_test/test.xml"
remotable: true
cacheable: true
timeout_millis: 60000
progress_message: "Testing //:java_test"
mnemonic: "TestRunner"
actual_outputs {
  path: "bazel-out/k8-fastbuild/testlogs/java_test/test.xml"
  digest {
    hash: "144a04dbe6aa5f2699e29bc1e6c46a0d9cb35029cf72be78235ed4ec20d0b441"
    size_bytes: 359
    hash_function_name: "SHA-256"
  }
}
runner: "remote cache hit"
remote_cache_hit: true
```

node2:
```
listed_outputs: "bazel-out/k8-fastbuild/testlogs/java_test/test.exited_prematurely"
listed_outputs: "bazel-out/k8-fastbuild/testlogs/java_test/test.infrastructure_failure"
listed_outputs: "bazel-out/k8-fastbuild/testlogs/java_test/test.outputs/outputs.zip"
listed_outputs: "bazel-out/k8-fastbuild/testlogs/java_test/test.outputs_manifest/ANNOTATIONS"
listed_outputs: "bazel-out/k8-fastbuild/testlogs/java_test/test.outputs_manifest/MANIFEST"
listed_outputs: "bazel-out/k8-fastbuild/testlogs/java_test/test.raw_splitlogs/test.splitlogs"
listed_outputs: "bazel-out/k8-fastbuild/testlogs/java_test/test.unused_runfiles_log"
listed_outputs: "bazel-out/k8-fastbuild/testlogs/java_test/test.warnings"
listed_outputs: "bazel-out/k8-fastbuild/testlogs/java_test/test.xml"
remotable: true
cacheable: true
timeout_millis: 60000
progress_message: "Testing //:java_test"
mnemonic: "TestRunner"
actual_outputs {
  path: "bazel-out/k8-fastbuild/testlogs/java_test/test.xml"
  digest {
    hash: "7380adf8329f3a066e54a54d5e8f50b4691b0ab8c8e90f45530ef725cae3ce28"
    size_bytes: 359
    hash_function_name: "SHA-256"
  }
}
runner: "linux-sandbox"
```

diff between test.xml files:
```
3c3
<   <testsuite name='AllTests' timestamp='1970-01-01T00:19:29.278Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.004' package='' id='0'>
---
>   <testsuite name='AllTests' timestamp='1970-01-01T00:18:23.929Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.004' package='' id='0'>
```

They differ only on timestamps. What does it mean?

**Comment by buchgr** [comment]
> I have a couple of differences in hashes of external/local_jdk/jre/lib/amd64/server/* libs, but as far as I understand it doesn't affect caching. 

If there is any difference in the inputs then that explains why you are not seeing cache hits. So that seems to explain why only java is affected too.

**Comment by alexandrvb** [comment]
Ok, thank you!

So I have differences in two files
```
external/local_jdk/jre/lib/amd64/server/classes.jsa
external/local_jdk/jre/lib/security/cacerts
```
Both of them are generated automatically during installation of openjdk deb packages. Unfortunately it makes remote bazel cache unusable for OpenJDK in Ubuntu.. Only one options is to run bazel inside docker container with installed JDK.

Do you plan to fix this issue? :)

**Comment by buchgr** [comment]
@alexandrvb please apologize the delay. The proper solution is to specify your own https://docs.bazel.build/versions/master/be/java.html#java_runtime and not use the system JDK. Essentially, you can specify a zip file containing a JDK and then have all your users use this.

**Comment by buchgr** [comment]
Please re-open this bug if it does not fix the issue.
