### ISSUE TITLE
repository rules: report progress immediately

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#6458]
### Description of the problem / feature request:

Repository rules should report progress as soon as the relevant statement is executed. Currently Bazel prints all messages once the repo rule is finished.

### Feature requests: what underlying problem are you trying to solve with this feature?

Report progress in real time for slow repo rules.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See https://github.com/laszlocsomor/projects/tree/b30533a64caf43f89ff9c5b812a896b65cb4f270/bazel/slow-repo-rule

### What operating system are you running Bazel on?

Windows 10 and Debian Linux

### What's the output of `bazel info release`?

0.18.0

**Comment by dslomov** [comment]
@aehlig is there anything more to do here?

**Comment by laszlocsomor** [comment]
Yes, there's more.

With Bazel 0.20.0 the repo rule no longer seems to execute the binary. Latest demo: https://github.com/laszlocsomor/projects/tree/d58298f88a209e90aa74139857813b26dcff580e/bazel/slow-repo-rule

**Comment by laszlocsomor** [comment]
Wait a second, something was wrong in my repro.

The repo rule indeed executes the binary. But there's still no output on stdout _while it's running_, only _after it's completed running_.

**Comment by aehlig** [comment]
OK, so progress is reported. Let's leave the remaining dicussion on #6459.
