### ISSUE TITLE
Building Bazel from source

### ISSUE THREAD

**Issue by dionescu** [bazelbuild/bazel#646]
What is the recommended way to build bazel from source?

I followed the instructions on the size and the bazel binary builds successfully but whenever I try to compile something I get include errors. For instance:

INFO: From Compiling third_party/gflags/upstream/src/gflags_completions.cc:
third_party/gflags/upstream/src/gflags_completions.cc:50:20: fatal error: config.h: No such file or directory
 #include "config.h"
                    ^
compilation terminated.
ERROR: /home/dragos/depot/third_party/gflags/BUILD:3:1: C++ compilation of rule '//third_party/gflags:gflags' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -iquote . -iquote ... (remaining 28 argument(s) skipped).
Target //examples/hello_world:hello failed to build

Nevertheless, using the release binary works. What am I missing?

**Comment by dionescu** [comment]
Note that the include errors I get are random (not just the one I mentioned above).

**Comment by AustinSchuh** [comment]
What are you trying to build?  Do you have a link to the source?

Recently the header checks have gotten stricter and caught real issues in build rules.  gflags, protobuf, and some other libraries with BUILD files in them weren't quite complete enough initially.

**Comment by dionescu** [comment]
Here is an example of code that fails:

examples/hello_world:hello in https://github.com/dionescu/trunk/

**Comment by dionescu** [comment]
IIRC, all the build rules in that repo, including third_party fail with the latest bazel built from source but succeed with the release binary.

**Comment by AustinSchuh** [comment]
I cloned your repo and took a look.  The repo you linked to is missing dependencies.

The release binary you are using has a bug in it which is causing it to not catch the missing header dependencies.  For boringssl, for example, you need to add all the internal header files to the srcs of the cc_library rule, and for the public headers, you need to add them hdrs.  Other libraries have similar problems.  If you want to save some typing, you can use glob([src/include/openssl/*.h]) to grab all the headers without listing them.

For more info on what bug exists in the release binary, see  https://github.com/bazelbuild/bazel/issues/473

**Comment by dionescu** [comment]
Thank you for the explanation. It makes sense now.
