### ISSUE TITLE
Tree artifacts do not detect out-of-band changes to the output directory

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#6460]
When a tree artifact is changed between two Bazel invocations, Bazel does not recognize the change and does not re-run the action generating the tree artifact. Reproduction in logical steps:
 1. Create an action that emits a tree artifact and another one that depends on the tree artifact
 2. Build the outputs of the second action
 3. Change the tree artifact outside of Bazel
 4. Re-run the build in (2)
 5. Observe that the tree artifact does not get rebuilt

This is in contrast with regular files whose changes do get detected. More detailed reproduction:

```
cat > rule.bzl <<'EOF'
def _dirimpl(ctx):
    out = ctx.actions.declare_directory(ctx.label.name)
    ctx.actions.run_shell(
        outputs = [out],
        inputs = [],
        command = "; ".join([
            "O=\"%s\"",
            "echo RAN",
            "mkdir -p \"$O/a\"",
            "mkdir -p \"$O/b\"",
            "echo 1 > \"$O/a/one\"",
            "echo 2 > \"$O/b/two\"",
        ]) % out.path,
    )
    return DefaultInfo(files = depset([out]))

def _fileimpl(ctx):
    out = ctx.actions.declare_file(ctx.label.name)
    ctx.actions.run_shell(
        outputs = [out],
        inputs = [],
        command = "; ".join([
            "O=\"%s\"",
            "echo 2 > \"$O\"",
        ]) % out.path,
    )
    return DefaultInfo(files = depset([out]))

dirrule = rule(implementation = _dirimpl, attrs = {})
filerule = rule(implementation = _fileimpl, attrs = {})
EOF

cat > BUILD <<'EOF'
load(":rule.bzl", "dirrule", "filerule")

dirrule(name = "dr")

filerule(name = "fr")

genrule(
    name = "gdr",
    srcs = [":dr"],
    outs = ["gdro"],
    cmd = "; ".join([
        "I=$(location :dr)",
        "cat $$I/a/one >> $@",
        "cat $$I/b/two >> $@",
        "cat $$I/a/one $$I/b/two",
    ]),
)

genrule(
    name = "gfr",
    srcs = [":fr"],
    outs = ["gfro"],
    cmd = "; ".join([
        "I=$(location :fr)",
        "cat $$I >> $@",
        "cat $$I",
    ]),
)
EOF

touch WORKSPACE
bazel build :gdr
chmod u+w bazel-bin/dr/a/one
echo bad > bazel-bin/dr/a/one
bazel build :gdr  # Observe that nothing gets rebuilt
# If the same is done to :gfr and bazel-bin/fr, :gfr *does* get rebuilt
```

**Comment by lberki** [comment]
It's also doubtful whether we re-run actions that have a symlink (as in, the output of `SymlinkAction`) to a tree artifact as an input and the tree artifact changes within the build, but I haven't had time to verify that.

**Comment by ericfelly** [comment]
I was not able to repro this failure mode. Can you confirm what the contents of "bazel-bin/dr/a/one" after you "echo bad" it? I had to chmod the file writable before that would succeed, so if that was not actually overwriting the file in question, the null rebuild is WAI.

**Comment by ericfelly** [comment]
I was not able to repro. Are you sure the "echo" actually succeeded? I needed to chmod the file writable first.

**Comment by lberki** [comment]
Uh, my bad. Probably. I updated the script (I indeed omitted the `chmod u+w` part and single quotes around `EOF`s) and I can't reproduce it anymore. It's probably an ID10T issue on my side. Sorry for wasting your time.
