### ISSUE TITLE
Windows: Bazel requires MSYS for every command

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#6462]
### Description of the problem / feature request:

On a fresh Windows 10 installation with only Bazel 0.18.0 and MSVC redistributable DLLs [1] and _without_ MSYS, running any command in a minimal workspace (just an empty WORKSPACE file) requires MSYS bash.

[1] https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

On a fresh Windows 10:

1. download Bazel 0.18.0 
2. install the [MSVC redistributable DLLs](https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe)
3. in cmd.exe:
  ```
  C:\>md c:\src\foo

  C:\>cd c:\src\foo

  C:\src\foo>echo # hello>WORKSPACE

  C:\src\foo>bazel info release
  Bazel on Windows requires MSYS2 Bash, but we could not find it.
  If you do not have it installed, you can install MSYS2 from
         http://repo.msys2.org/distrib/msys2-x86_64-latest.exe

  If you already have it installed but Bazel cannot find it,
  set BAZEL_SH environment variable to its location:
         set BAZEL_SH=c:\path\to\msys2\usr\bin\bash.exe
  [bazel ERROR src/main/cpp/blaze_util_windows.cc:1453] bash.exe not found on PATH
  [bazel INFO src/main/cpp/blaze_util_windows.cc:1473] BAZEL_SH detection took 0 msec, found
  ```

### What operating system are you running Bazel on?

Windows Server 2016 (v1607)

**Comment by robisim74** [comment]
@laszlocsomor 

I get the same error: `Bazel on Windows requires MSYS2 Bash, but we could not find it` for every command using the binaries for Bazel  provided by the `@bazel/bazel` v0.20.0 npm package.

So the only way to run Bazel on Windows is to install MSYS2 bash and disable the path conversion?

The doc says to prefer Command Prompt or PowerShell: https://docs.bazel.build/versions/master/windows.html#running-bazel-msys2-shell-vs-command-prompt-vs-powershell

**Comment by laszlocsomor** [comment]
@robisim74 : try Bazel 0.21, that should no longer complain about a missing MSYS2 Bash. Please let me know if you still find problems with it!

**Comment by robisim74** [comment]
Ok, thanks! I will try to install v0.21 (still not published on npm) and let you know.

**Comment by robisim74** [comment]
@laszlocsomor I tried to download version 0.21 directly on my machine in `c:\bazel`, and run `C:\> .\bazel help`, but nothing: same error.

For the moment, I installed MSYS2 bash to work.

**Comment by laszlocsomor** [comment]
@robisim74 : You're right. I never merged the corresponding PR (https://github.com/bazelbuild/bazel/pull/6582) because it broke some tests.

Installing MSYS2 is the best "workaround" for now. Sorry about that.

**Comment by laszlocsomor** [comment]
Bazel 0.23 still complains about missing MSYS2:
```
C:\src\tmp>c:\Users\laszlocsomor\Downloads\bazel-0.23.0-windows-x86_64.exe info release
ERROR: bash.exe not found on PATH
Bazel on Windows requires MSYS2 Bash, but we could not find it.
If you do not have it installed, you can install MSYS2 from
       http://repo.msys2.org/distrib/msys2-x86_64-latest.exe

If you already have it installed but Bazel cannot find it,
set BAZEL_SH environment variable to its location:
       set BAZEL_SH=c:\path\to\msys2\usr\bin\bash.exe
[bazel ERROR src/main/cpp/blaze_util_windows.cc:1462] bash.exe not found on PATH
[bazel INFO src/main/cpp/blaze_util_windows.cc:1477] BAZEL_SH detection took 0 msec, found
```
