### ISSUE TITLE
Windows: Java rules require MSYS

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#6464]
### Description of the problem / feature request:

The Java rules depend on at least on genrule, so they need MSYS on Windows.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

On a fresh Windows 10:

1. download Bazel 0.18.0 
2. install the [MSVC redistributable DLLs](https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe)
3. download and install JDK 8
4. create a fake msys script as `c:\src\tmp\fake-msys\usr\bin\bash.bat` that just prints its arguments and exits:
  ```
  C:\src\tmp>notepad c:\src\tmp\fake-msys\usr\bin\bash.bat

  C:\src\tmp>type c:\src\tmp\fake-msys\usr\bin\bash.bat
  @echo OFF
  echo Fake MSYS, args=(%0 %1 %2 %3 ...)
  exit /B 1
  ```

5. Create a workspace with one BUILD rule and one Java file:
  ```
  C:\src\tmp>type BUILD
  java_binary(
    name = "hello_java",
    srcs = ["Hello.java"],
    main_class = "Hello",
  )

  C:\src\tmp>type Hello.java
  public class Hello {
    public static void main(String[] args) {
      System.out.println("hello Java!");
    }
  }
  ```

6. in cmd.exe:
  ```
  C:\src\tmp>set BAZEL_SH=c:\src\tmp\fake-msys\usr\bin\bash.bat

  C:\src\tmp>bazel build //:hello_java
  ...
  ERROR: 
  C:/users/laszlocsomor/_bazel_laszlocsomor/zovul4l7/external/bazel_tools/tools/jdk/BUILD:202:5: Executing genrule @bazel_tools//tools/jdk:platformclasspath8 failed (Exit 1)
  Fake MSYS, args=("C:\src\tmp\fake-msys\usr\bin\bash.bat" -c "source external/bazel_tools/tools/genrule/genrule-setup.sh;  ...)
  Target //:hello_java failed to build
  ```

The same thing happens even when JAVA_HOME is set.

### What operating system are you running Bazel on?

Windows Server 2016 (v1607)

**Comment by cushon** [comment]
`@bazel_tools//tools/jdk:platformclasspath8` isn't genrule at head, fwiw.

**Comment by laszlocsomor** [comment]
Thanks! Indeed, using Bazel built from HEAD, I can make this work -- I replaced my fake Bash with an .exe file I wrote that just prints its arguments and exits 1, then I put it under `c:\src\fake-msys\usr\bin\bash.exe`, pointed  `BAZEL_SH` at it, and could successfully build the java_binary in the bug report.

**Comment by laszlocsomor** [comment]
See also https://github.com/bazelbuild/bazel/issues/6475
