### ISSUE TITLE
Can't depend on binary from remote git_repository

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#647]
I tried to depend on ijar from the bazel git repo:

https://github.com/twitter/scalding/commit/4f6d6623a94a3b7d70611cccc807dc19c7a8891f

using:
```
git_repository(
  name = "bazel",
  remote = "https://github.com/bazelbuild/bazel.git",
  tag = "0.1.1")

```
in my WORKSPACE and:
```
"_ijar": attr.label(executable=True, default=Label("@bazel//third_party/ijar:ijar"), single_file=True, allow_files=True)
```
as the label for the target, but my script fails because the ijar binary does not seem to be built, and I get:
```
 external/bazel/third_party/ijar/ijar: No such file or directory
```
Discussion here: https://groups.google.com/forum/#!topic/bazel-discuss/ejy79jkSrp8

**Comment by lberki** [comment]
Ths is WAI. You don't add ijar to the set of inputs to the action here:

https://github.com/twitter/scalding/blob/4f6d6623a94a3b7d70611cccc807dc19c7a8891f/bazel_tools/scala.bzl#L62

We'll figure out a way to do so on the aforementioned thread.

**Comment by johnynek** [comment]
Indeed adding `ctx.file._ijar` to the inputs of my action fixed the problem.
