### ISSUE TITLE
Windows, C++: windows_cc_configure.bzl requires BAZEL_SH

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#6474]
### Description of the problem / feature request:

`windows_cc_configure.bzl` breaks if `BAZEL_SH` is unset.

Setting `BAZEL_SH` to point to a fake Bash (`c:\src\fake-msys\usr\bin\bash.exe` -- a binary I wrote that just dumps its arguments and exits with 1) works around the problem.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Check out Bazel's sources at https://github.com/bazelbuild/bazel/commit/2fda17d46088f2bb07b049fa35759002ea1dd5db
2. Comment out the line https://github.com/bazelbuild/bazel/blob/2fda17d46088f2bb07b049fa35759002ea1dd5db/src/main/cpp/blaze.cc#L1543
3. Build Bazel
4. Unset `BAZEL_SH` (with `set BAZEL_SH=`)
5. Run `bazel info` with the Bazel you built.

```
C:\src\tmp>c:\src\bazel\bazel-bin\src\bazel.exe info
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
C:\Users\laszlocsomor/.bazelrc
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: baac9c71-b583-4c1a-9429-3ee26164b0f4
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/_bazel/zovul4l7/external/bazel_tools/tools/cpp/cc_configure.bzl", line 51
                configure_windows_toolchain(repository_ctx)
        File "C:/_bazel/zovul4l7/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 344, in configure_windows_toolchain
                repository_ctx.template("CROSSTOOL", paths["@bazel_tools//..."], ...}": ""})
        File "C:/_bazel/zovul4l7/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 361, in repository_ctx.template
                _get_escaped_windows_msys_crosstool_content(repository_ctx)
        File "C:/_bazel/zovul4l7/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 35, in _get_escaped_windows_msys_crosstool_content
                get_env_var(repository_ctx, "BAZEL_SH")
        File "C:/_bazel/zovul4l7/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 125, in get_env_var
                auto_configure_fail(("'%s' environment variable is n...))
        File "C:/_bazel/zovul4l7/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 109, in auto_configure_fail
                fail(("\n%sAuto-Configuration Error:%...)))

Auto-Configuration Error: 'BAZEL_SH' environment variable is not set
```

### What operating system are you running Bazel on?

Windows 10

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

See repro instructions above.

**Comment by laszlocsomor** [comment]
This is a bad user experience: MSYS is required just to run `bazel info`. (And also to build C++ without any genrule dependencies.)

**Comment by meteorcloudy** [comment]
Understand, I will fix this.
