### ISSUE TITLE
Document --invocation_id flag

### ISSUE THREAD

**Issue by EricBurnett** [bazelbuild/bazel#6476]
### Description of the problem / feature request:

--invocation_id is the canonical way to override the invocation ID bazel will use for an execution. But it's an undocumented and hidden flag. It should be documented.

### Feature requests: what underlying problem are you trying to solve with this feature?

Users that need to set the invocation id upstream of invoking bazel (e.g. if they want to pre-generate a link to a UI, and/or don't want to scrape bazel output to learn it) cannot find the flag.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

N/A

### What operating system are you running Bazel on?

N/A

### What's the output of `bazel info release`?

N/A

###  Have you found anything relevant by searching the web?

Asked (but not answered) on StackOverflow: https://stackoverflow.com/questions/52947834/set-bazel-invocation-id-from-command-line

### Any other information, logs, or outputs that you want to share?

There's also the environment variable BAZEL_INTERNAL_INVOCATION_ID, but it explicitly tells you to use --invocation_id instead: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/runtime/CommandEnvironment.java#L283 .

**Comment by philwo** [comment]
@EricBurnett Do you mind sending a PR to document this? :)

**Comment by cameron-martin** [comment]
I don't think that commit fixes this issue. It is still set to `OptionDocumentationCategory.UNDOCUMENTED`, and I don't see it in the documentation.
