### ISSUE TITLE
Nested workspace tests fail with --nolegacy_external_runfiles enabled

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/bazel#6481]
### Description of the problem:

When `--nolegacy_external_runfiles` is enabled, nested workspace tests such as `bazel test @nested_workspace//:test` fail with the error

```
external/bazel_tools/tools/test/test-setup.sh: line 282: : command not found
```

in the test.log. When `--nolegacy_external_runfiles` is not enabled the same tests pass.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Minimal example: https://github.com/gregmagolan/bazel_issue

### What operating system are you running Bazel on?

OSX Mohave locally. Same problem observed in the Linux CircleCI container. I haven't tested on Windows.

### What's the output of `bazel info release`?

I tested against Bazel 0.18.0 and Bazel 0.17.2. Failure is the same in both cases.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/gregmagolan/bazel_issue.git

###  Have you found anything relevant by searching the web?

Negative

**Comment by jondo2010** [comment]
This is still a problem with `v4.0.0`

**Comment by gregmagolan** [comment]
This is ancient. Closing as its no longer relevant in our uses cases
