### ISSUE TITLE
Failure to include a declare_directory in inputs of run action causes silent failures.

### ISSUE THREAD

**Issue by sdtwigg** [bazelbuild/bazel#6487]
### Description of the problem / feature request:

I have been experimenting with declare_directory and Args.add_all. If in declare_directory output is used in an Args object but the declare_directory output was not added to inputs or tools, the args expansion is suddenly just an empty list.

It would be expected that the directory still be expanded (thus causing a script error when the files are not present).

The following code sample demonstrates trying to consume a arbitrary files and directories. Not having the inputs line is an error; however, the script only fails when at least one files are passed srcs since directories get expanded to an empty list.

```python
def _concatenate_files_impl(ctx):
    outfile = ctx.actions.declare_file(ctx.attr.name + ".txt")

    args = ctx.actions.args()
    concated_files = depset(transitive = [src.files for src in ctx.attr.srcs])
    args.add_all(concated_files)

    ctx.actions.run_shell(
        command = """
set -e

touch {outfile}

for arg; do
  cat $arg >> {outfile}
done
""".format(outfile=outfile.path),
        outputs = [outfile],
        inputs = concated_files,  # comment out this line and directory files disappear completely
        arguments = [args],
    )

    return [DefaultInfo(files=depset([outfile]))]

concatenate_files = rule(
    implementation = _concatenate_files_impl,
    attrs = {
        "srcs": attr.label_list(allow_files=True),
    },
)
```

### What operating system are you running Bazel on?

Debian Linux

### Version of Bazel

I am using the google-internal version of Bazel released as of Oct. 23, 2018

**Comment by laurentlb** [comment]
I haven't looked into details, but is it related to this change? https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#expand-directories-in-args

**Comment by sdtwigg** [comment]
The behavior is the same even if you set expand_directory=True so the value of the default argument shouldn't be related.

Even so, would expect expand_directory=True to expand to multiple files and expand_directory=False to stay as the directory name. In neither case would I expect it to be nothing (unless the directory is actually empty).
