### ISSUE TITLE
rules may implicitly reference CC make variables even under --incompatible_disable_cc_configuration_make_variables

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#6489]
Reading https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#disallow-using-c-specific-make-variables-from-the-configuration, one would expect having a `genrule` that uses `$(CC)` without an implicit dependency on a cc toolchain would fail. But, this is not the case:
```
$ cat BUILD
genrule(
    name = 'run-cc',
    cmd = '$(CC) --version > $(@)',
    outs = ['cc-version.txt'],
)
$ bazel build --incompatible_disable_cc_configuration_make_variables //:run-cc
INFO: Invocation ID: 1c9a0e30-1cf8-48c5-b2bc-c4336ae2cce8
INFO: Analysed target //:run-cc (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:run-cc up-to-date:
  bazel-genfiles/cc-version.txt
INFO: Elapsed time: 0.111s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```
It seems to me the problem is [`ConfigurationMakeVariableContext`](https://github.com/bazelbuild/bazel/blob/51482d71de776b739de8591c1dc0fa264121e151/src/main/java/com/google/devtools/build/lib/analysis/ConfigurationMakeVariableContext.java#L73), which slurps up the make variables from any implicit `:cc_toolchain` attribute.

**Comment by lberki** [comment]
This is actually working as intended and the documentation is also, technically, correct because the Make variables come not from `CppConfiguration` but from an implicit dependency.

We are planning to remove the dependency of genrules on C++ toolchains, too, for this exact reason, but that's a different refactoring. Let me just clarify this in the documentation...

**Comment by benjaminp** [comment]
Ah, thanks for the explanation. I assumed it was going to be a similar story to the Java-related make variables.
