### ISSUE TITLE
Ability to generate .class files instead of jar out of java_library

### ISSUE THREAD

**Issue by rahul-nitkkr** [bazelbuild/bazel#6499]
### Description of the problem / feature request:
Is there a feature which can allow me to tweak java_library behavior to allow me to generate class files instead of the jar, or can i piggyback on the actions generating the jars to unzip the same and dump them out ? 
 

### Feature requests: what underlying problem are you trying to solve with this feature?

> My runtime is tightly coupled with the compiles time, as in, in the present build system , we dump out the .class files into a highly custom blobstore implementation, and then our wrapper on jvm directly runs them [ we have a FileSystem implementation which this custom jvm implementation can read.
So, essentially , what i'm doing right now is , once bazel build has generated the outputs , i have an utility, which explodes the jars and dumps them into this blobstore.

i am wondering if there is a more native way of doing that.
@werkt on the slack channel suggested using aspects process the jars ,trying to use them , i see that aspects are fired before the build action has been performed, so essentially there is no jar for the aspect to unzip. Am i using aspects incorrectly then ?

**Comment by jin** [comment]
Hello @rahul-nitkkr, thank you for creating this issue.

  The Bazel team uses GitHub Issues to track **bugs** and **feature requests** only. Your question will have a higher visibility on the [bazel-discuss](https://groups.google.com/forum/#!forum/bazel-discuss) mailing list and [StackOverflow](https://stackoverflow.com/questions/tagged/bazel), which are also read by the Bazel team and the community contributors. Please ask your question on those platforms instead.

  I will be closing this issue now. Thank you again for your understanding.
