### ISSUE TITLE
Error messages produced in macros are hard to debug for the user of the macro

### ISSUE THREAD

**Issue by ob** [bazelbuild/bazel#6504]
Here's a motivating example:

```
#!/bin/sh

set -Eeuo pipefail

WK=`mktemp -d`
function finish() {
    rm -rf "$WK"
}
trap cleanup EXIT

cd "$WK"
touch WORKSPACE
mkdir package
cat >package/macro.bzl <<EOF
def macro(name, **kwargs):
  native.cc_library(
    name = name,
    **kwargs
  )
EOF
cat >package/BUILD <<EOF
load("//package:macro.bzl", "macro")
macro(
  name = "foo",
  non_existent_attribute = "bar"
)
EOF

bazel build //package:foo
```

If you run that script, you get this error:

```
ERROR: BUILD:2:1: //package:foo: no such attribute 'non_existent_attribute' in 'cc_library' rule
ERROR: error loading package 'package': Package 'package' contains errors
```

There are a few things wrong with that error message:

* It references a rule created by the macro, but the user of the macro never typed that rule. If they search for the rule in the BUILD file, they won't find it. What is worse, if the macro creates many rules, some potentially of the same kind, how to tell which rule caused the error?

* It points the user at the line in the BUILD file where the macro was defined. Not where the non-existent attribute was used. In a very large BUILD file it makes it hard to find the culprit.

**Comment by laurentlb** [comment]
We should show a stacktrace in that case.

**Comment by brandjon** [comment]
Confirmed this is still an issue.
