### ISSUE TITLE
Warnings while building bazel at head

### ISSUE THREAD

**Issue by dkelmer** [bazelbuild/bazel#6505]
Using bazel 18.0 to build bazel at head leads to lots of console spam saying: 

warning: unknown enum constant FlagIdentifier.NONE
  reason: class file for com.google.devtools.build.lib.syntax.SkylarkSemantics not found

**Comment by cushon** [comment]
That looks like a duplicate of #5985.

**Comment by dkelmer** [comment]
Definitely, closing.
Duplicate of #5985
