### ISSUE TITLE
Resources downloaded for unused Go architectures

### ISSUE THREAD

**Issue by jacobvoytko** [bazelbuild/bazel#651]
Both the Darwin and Linux Go distributions are downloaded to the local machine, even though I'm only attempting to build with the Linux version.
- Command *

```
    bazel build :bazel_go_example_test
```

This is not noticeable on my home's internet connection, but is painfully obvious in slower connection settings (for instance, I'm currently using a bus' wifi).

**Comment by helenalt** [comment]
@jayconrod  Please review if this is still an issue and close/comment.

**Comment by jayconrod** [comment]
Not a problem anymore. We only download the SDK that matches the host platform.
