### ISSUE TITLE
Tests conflict on working directory when --runs_per_test is used

### ISSUE THREAD

**Issue by jlisee** [bazelbuild/bazel#6511]
### Description of the problem / feature request:

A test that generates an output file in it's working directory using a path like `./foo` works with `./bazel test` but fails with bazel test `./bazel test --runs_per_test=N` when N > 2.

The issue is that test gets a transient working directory that is cleaned up after each run, but that directory is not `TEST_TMPDIR`.  Said working directory is used by all the parallel test runs at once so any file writes and reads to that directory produces races.

This is what the transient working directory:

```
/tmp/worker/cache/d356571e86e5eb9933b505da61453487938554f6_53_dir/my/path/test.runfiles/__main__/my/path/my_test.cc
```

While this is what `TEST_TMPDIR` looks like.
```
/tmp/worker/myhost/operations/c82a20e7-65af-4c43-97da-4a50b739d905/_tmp/25e27c27b7f8b593dddd531acf40fcbc/my_test
```

### Feature requests: what underlying problem are you trying to solve with this feature?

The two options I see are:

 - Disallow writing to the working directory of tests
 - Update `runs_per_test` to provide each test a unique working directory per test

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Can provide in a follow up if asked.

### What operating system are you running Bazel on?

Linux.

### What's the output of `bazel info release`?

```
release 0.16.1
```

**Comment by jlisee** [comment]
Ok so this depends on the spawn strategy

 - `linux-sandbox` - safe
 - `remote` (buildfarm) - fails
 - `local` - fails 

Here is the repo:

Working local command (despite all the directory paths being identical):
```
$ bazel test --jobs 100  --runs_per_test=1000 //testpkg/...
...
INFO: Build completed successfully, 1001 total actions
//testpkg:test                                                           PASSED in 0.2s
  Stats over 1000 runs: max = 0.2s, min = 0.1s, avg = 0.1s, dev = 0.0s

INFO: Build completed successfully, 1001 total actions
```

Failing with local:
```
$ bazel test --spawn_strategy=local --jobs 100 --runs_per_test=1000 //testpkg/..
...
//testpkg:test                                                           FAILED in 1000 out of 1000 in 0.2s
...
INFO: Build completed, 1 test FAILED, 1001 total actions
```

Failing remote execution with buildfarm:
```
$ bazel test --spawn_strategy=remote --remote_executor=buildfarm.internal.corp  --jobs 100 --runs_per_test=1000 //testpkg/...
...
//testpkg:test                                                           FAILED in 1000 out of 1000 in 0.4s
...
INFO: Build completed, 1 test FAILED, 1001 total actions
```

Files:

`testpkg/BUILD`
```python
sh_test(
    name = "test",
    size = "small",
    srcs = ["test.sh"],
)
```

`testpkg/test.sh`
```bash
#! /bin/bash

echo "CWD: $PWD"
echo "TEST_TMPDIR: $TEST_TMPDIR"

set -euo pipefail

test_path="./foo"
pad=$RANDOM

echo "PAD: $pad"

# Write a semi-unique file
num=1000
test_string=$(for ((i=1; i<=$num; i++));do printf "%s" "$pad";done;printf "\n")
echo "$test_string" >> "$test_path"

# Read back from the file
test_value=$(cat "$test_path")
if [ "$test_value" != "$test_string" ]; then
    echo "ERROR: string does not match"
    exit 1
fi
```

**Comment by jmmv** [comment]
Confirmed that this is still a problem on a non-sandboxed test run. I'm surprised it's a problem with remote execution though.

**Comment by Vertexwahn** [comment]
On Windows you do not have `linux-sandbox` and you run with the above described example in the same problem
