### ISSUE TITLE
"Toolchain modes" for same-platform toolchain selection

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel#6517]
Tracking issue on [Bazel Configurability Roadmap](https://bazel.build/roadmaps/configuration.html) and [Bazel Platforms Roadmap](https://bazel.build/roadmaps/platforms.html)

Goal:
* Document how to define and use multiple toolchains on the same platform
* Examples: debug vs. opt mode, correctness sanitizers

**Comment by katre** [comment]
This is complete and already possible with new transition features.
