### ISSUE TITLE
Obsolete old-style "platform-like" flags

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel#6518]
Tracking issue on [Bazel Configurability Roadmap](https://bazel.build/roadmaps/configuration.html) and [Bazel Platforms Roadmap](https://bazel.build/roadmaps/platforms.html)

Goal:
* Ad hoc, ungeneralizable "platformy" flags like `--cpu`, `--javabase`, `--apple_crosstool_top` are replaced with [`--platforms`](https://docs.bazel.build/versions/master/platforms.html#specifying-a-platform-for-a-build)
* We can call this closed when `--platforms` is usable and documented as best practice.  Old flags are deprecated. A separate issue can track their outright removal (we have to migrate away legacy dependencies, which will take more time).
* `--platforms` works for *all* rules. Rules that still rely on old-style flags will have them auto-set behind the scenes by `--platforms`.

**Comment by aragos** [comment]
First step: Provide a migration path from old style flags to platforms. Tracked in #6426.

**Comment by gregestren** [comment]
**April '19 update:**

"Obsolete" may be in spirit only (vs. official documentation or semantic enforcement), but the pieces are fairly well put together.

I guess the second point on this issue's top comment remains TODO and maybe we can call this officially closed when showing a concrete example of all the pieces working for an example build (maybe for both Java and C++).

I wonder if `select` directly on `constraint_setting` should also be a blocker?

**Comment by meisterT** [comment]
What's the state of this?

**Comment by katre** [comment]
We are moving forward with migrating CC rules to use toolchain resolution, but don't have an actual timeframe for removing the legacy flags.

**Comment by gregestren** [comment]
We're still trying to track the long term as accurately as we can at https://bazel.build/roadmaps/configuration.html.

Moving more rules to platforms, which we are very much prioritizing now, will be a major milestone toward being able to focus on this.
