### ISSUE TITLE
Experimental Bazel mode automatically "trims" multi-configured graphs

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel#6524]
Tracking issue on [Bazel Configurability Roadmap](https://bazel.build/roadmaps/configuration.html)

Lots of the work on that roadmap can increase build graph size unnecessarily. For example, if two Java binaries have a common data dependency on a Go binary (either directly or transitively) and they're built in the same Bazel invocation with different JDKs <sup>1</sup>, there's no need to build the Go binary twice. But unless we make special optimizations that's exactly what will happen, because Bazel doesn't automatically distinguish that Java-related build flags don't matter for Go rules. 

@serynth is prototyping work that *does* intelligently make these distinctions. The goal of this work is to automatically make Go rules like the above only build once and make everything generally faster and leaner as a result.

Also see "manual trimming" in https://github.com/bazelbuild/bazel/issues/6523.

---
[1] *This isn't really possible today because there's no interface for applying different command line flags to different targets in the same build. This example is hypothetical. But Bazel's configurability work is rapidly opening up scenarios like this, so we've got to seriously think about them.*

**Comment by gregestren** [comment]
**April '19 update:**

This now exists but very much remains an experiment. You can use it with `--experimental_dynamic_configs=retroactive`.

@serynth is currently prioritizing doing some core memory/performance profiling and using this to automatically power Android feature flags and fast rebuilds on `--test_*` changes.

**Comment by katre** [comment]
@gregestren Can you please provide an update on this issue?

**Comment by gregestren** [comment]
@sdtwigg is currently finishing up the `--trim_test_configuration` specialization (that has its own tracking bug), after which this will be explored more generally. He can provide further details.
