### ISSUE TITLE
Provide early adoption guidance for custom Bazel flags and transitions

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel#6525]
Lots of projects on [Bazel's Configurability Roadmap](https://bazel.build/roadmaps/configuration.html) will make it *much* easier to custom-configure how builds work without having to set hard-coded flags at the command line.

This includes user-defined transitions (*"build all my deps for a different cpu"*) and user-defined flags (`--my_special_rule_flag`", possibly settable directly in the rule).

API progress is moving rapidly. But there's going to be long-term performance consequences to choosing to use these features (so much that the roadmap has an entire [section](https://bazel.build/roadmaps/configuration.html#correctness-and-speed) on them).

Users need to understand the cost/value tradeoffs involved and how to apply them to their builds. This issue tracks the effort to provide good documentation guiding this process. 

This is especially important as these features start rolling out in unoptimized, experimental mode over upcoming weeks/months.

**Comment by gregestren** [comment]
**April '19 update:**

Still on track (in some form) for summer 2019.

**Comment by dslomov** [comment]
Is this still a blocker for 1.0?

**Comment by aiuto** [comment]
Greg is OOO this week, so I will put words in his mouth. I don't see how this impacts the 1.0 release. We can provide guidance documentation at any time, regardless of when the code is frozen.

**Comment by dslomov** [comment]
Thanks @aiuto !

**Comment by gregestren** [comment]
I'm going to close this in preference for specific support requests. If there's enough of a broad call we could always reprioritize this (broad-facing documentation).
