### ISSUE TITLE
Recent Bazel releases don't run on Alpine Linux

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#6528]
I'm trying to package 0.18.0 on Alpine Linux, on Docker using this modified docker file: [1], with these commands from this project: [2]:

```
  ./compile.sh
  ./output/bazel build -s --verbose_failures scripts:bazel-complete.bash
```

It worked already last time with 0.15.2. On 0.18.0 it's failing with: [3]. This prevents me from releasing new bazel package for Alpine Linux.

[1] https://github.com/dnephin/docker-apk-build/blob/master/builder/Dockerfile
[2] https://github.com/davido/bazel-alpine-package/blob/master/APKBUILD#L23-L24
[3] http://paste.openstack.org/show/733080/

**Comment by davido** [comment]
It worked last time on Bazel 0.15.2 and is failing to build on Aline Linux in all later releases.

**Comment by davido** [comment]
OK, it seems that Alpine Linux doesn't have support for Java 9: [1].

* [1] https://bugs.alpinelinux.org/issues/8089

**Comment by jin** [comment]
Closing this issue as it's a downstream issue on Alpine.
