### ISSUE TITLE
The "What is the build label for" section on the query how-to is misleading

### ISSUE THREAD

**Issue by regnat** [bazelbuild/bazel#6529]
### Description of the problem / feature request:

In [What is the build label for //path/to/file/bar.java?](https://docs.bazel.build/versions/master/query-how-to.html#what-is-the-build-label-for-path-to-file-bar-java) (and also [here](https://docs.bazel.build/versions/master/query-how-to.html#what-package-contains-file-path-to-file-bar-java) and [here](https://docs.bazel.build/versions/master/query-how-to.html#what-rule-target-s-contain-file-path-to-file-bar-java-as-a-sourc)), it is implied that if I want to find the label for the file `foo/bar.baz` in my repo I should run:

```shell
bazel query //foo/bar.baz
```

However, running this command results in:

```console
ERROR: no such package 'foo/bar.baz': BUILD file not found on package path
```

`bazel query foo/bar.baz` however works fine as long as we stay at the root of the repo.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```shell
# Set-up a test bazel repo
git clone https://github.com/bazelbuild/examples/ && cd examples
touch WORKSPACE

# try the erroneous command
bazel query //java-tutorial/src/main/java/com/example/Greeting.java
```

#### Expected result

(according to the doc)

```console
//java-tutorial:src/main/java/com/example/Greeting.java
```

#### Actual result

```console
ERROR: no such package 'java-tutorial/src/main/java/com/example/Greeting.java': BUILD file not found on package path
```

### What operating system are you running Bazel on?

Linux (NixOS)

### What's the output of `bazel info release`?

```console
$ bazel info release
release 0.17.1- (@non-git)
```

Also tried with the docker image `l.gcr.io/google/bazel:0.17.1`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Installed through the Nix package manager

/cc @mboes

**Comment by laurentlb** [comment]
Thanks for the report, the documentation looks wrong indeed.

`bazel query` seems to use the target syntax (like `build` or `test` commands), which is explained here: https://docs.bazel.build/versions/master/guide.html#target-patterns
