### ISSUE TITLE
Bash tests (and maybe more?) fail at HEAD on Linux

### ISSUE THREAD

**Issue by jacobvoytko** [bazelbuild/bazel#653]
Unable to run bazel_go_example_test.sh at head in a virtual machine with a relatively recent Ubuntu install. Getting the following error:

ERROR:     /home/jake/.cache/bazel/_bazel_jake/4ac624ea9cd3ddd511ca21b7d083a361/bazel/_tmp/bazel_go_example_test_1/workspace/ex/BUILD:2:1: error executing shell command: 'rm -rf bazel-out/local_linux-fastbuild/bin/ex/go_default_library.a.dir && mkdir -p bazel-out/local_linux-fastbuild/bin/ex/go_default_library.a.dir && mkdir -p bazel-out/local_linux-fastbuild/bin/ex...' failed: Could not prepare mounts for sandbox execution: /sbin does not exist: Could not prepare mounts for sandbox execution: /sbin does not exist.

I binary searched, and it was caused by this commit: https://github.com/bazelbuild/bazel/commit/d91aa2e54a1f176dade3baf6d27b496ef2e8cf90

**Comment by bsilver8192** [comment]
Do you have a /sbin directory?

I have trouble seeing how you couldn't because [dpkg in Precise](http://packages.ubuntu.com/precise/amd64/dpkg/filelist) has a file installed there, and I don't see how you can have an Ubuntu system without dpkg installed.

**Comment by jacobvoytko** [comment]
I do! This is basically a stock Ubuntu VM with a clean Bazel build, I really haven't done anything interesting to configure it.

    jake@virtually:~$ stat /sbin
      File: ‘/sbin’
      Size: 12288     	Blocks: 24         IO Block: 4096   directory
    Device: fc00h/64512d	Inode: 2485505     Links: 2
    Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
    Access: 2015-11-25 21:02:17.854342439 -0500
    Modify: 2015-11-18 11:09:29.556148264 -0500
    Change: 2015-11-18 11:09:29.556148264 -0500
    Birth: -

Are there specific logs that might be helpful?

**Comment by bsilver8192** [comment]
That's weird... What's the output if you run bazel with `--verbose_failures --sandbox_debug` (including the command you're running)? Have you tried doing a `bazel shutdown`?

If you're using compile.sh, you can add those options with `export BAZEL_ARGS='--verbose_failures --sandbox_debug'`.

**Comment by hanwen** [comment]
What version is the bazel that is running the test (as opposed to the one under test?) - for the /sbin issue, I noticed that it disappeared when I synced the former to head.

**Comment by jacobvoytko** [comment]
hanwen - those steps eliminate the problem for me. Thanks!
