### ISSUE TITLE
ctx.actions.declare_directory() - all contents marked with executable permissions

### ISSUE THREAD

**Issue by jmcmullan** [bazelbuild/bazel#6530]
### Description of the problem / feature request:

When using `ctx.actions.declare_directory()`, any directory contents resulting from a `ctx.actions.run(.., output = [ directory ], ...)` end up with executable permissions set, regardless of the permissions set by the action.

### Feature requests: what underlying problem are you trying to solve with this feature?

I'd like the output directory to have the permissions as set by the action.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

BUILD
```
load("//:create_directory.bzl", "create_directory")


create_directory(
    name = "output",
    srcs = [ "subdir/a", "subdir/b", "c"]
)
```

create_directory.bzl
```
def _impl_create_directory(ctx):
    output = ctx.actions.declare_directory(ctx.label.name)

    script = ctx.actions.declare_file(ctx.label.name + ".sh")

    cmds = ["mkdir -p {dirname}; cp -L {src} {dest}".format(dirname = output.path + "/" + f.dirname, src = f.path, dest = output.path + "/" + f.short_path) for f in ctx.files.srcs]
    print("\n".join(cmds))
    ctx.actions.write(output = script, content = "\n".join(["#!/bin/sh"] + cmds) + "\n", is_executable = True)

    ctx.actions.run(
            executable = script,
            inputs = [ script ] + ctx.files.srcs,
            outputs = [ output ]
    )

    return [
        DefaultInfo(
            files = depset([ output ]),
        )
    ]

create_directory = rule(
    _impl_create_directory,
    attrs = {
        "srcs": attr.label_list(allow_files = True),
    },
)
```

### What operating system are you running Bazel on?

Linux (Ubuntu 18.04).

### What's the output of `bazel info release`?

`release 0.18.0`

###  Have you found anything relevant by searching the web?

Nothing.

### Any other information, logs, or outputs that you want to share?

[bazel-dirbug.tar.gz](https://github.com/bazelbuild/bazel/files/2520209/bazel-dirbug.tar.gz)

**Comment by benjaminp** [comment]
This is the behavior for all action outputs, directory or not.

**Comment by jmcmullan** [comment]
Is there a 'rationale' for this behavior?

I would expect this of the output of rules tagged as 'executable = True' or 'test = True', but to make _all_ output files executable seems... just wrong.

**Comment by jin** [comment]
I'm also interested to learn about the rationale behind this. @ulfjack / @lberki?

**Comment by ulfjack** [comment]
Simplicity. On posix-like systems, it's generally not a problem if files are marked executable even if they're not. It's also simpler for users (if a bit surprising). Internally, we use a file-based CAS in combination with per-action symlink trees - since symlinks can't overwrite file permissions, having multiple copies of the same file with different permissions would multiply the size of the CAS.

**Comment by jmcmullan** [comment]
Must not have many python test cases, then.
My python dependency graph pulls in ~40K python files as runfiles (when using the native 'py_library()' rules).

With a thousand or so test cases, this easily consumes all available inodes on smaller (< 1T) filesystems.

What we really want it to be able to make a common 'python environment' directory and symlink to that instead of a symlink farm to each individual file in it.

**Comment by benjaminp** [comment]
Note `declare_directory` isn't a solution to large symlink farms; when `--incompatible_symlinked_sandbox_expands_tree_artifacts_in_runfiles_tree` becomes the default, runfiles will have a symlink for every directory artifact entry. At any rate, Bazel eating all your inodes is different issue from all output artifacts being executable.

**Comment by jmcmullan** [comment]
True, Bazel eating inodes is a different issues from the 'everything's executable' issue.
But now it seems that the `declare_directory` workaround for Bazel eating all my inodes is not going to be a permanent fix, anyway.

Sigh.

**Comment by louwers** [comment]
Was this ever resolved? 

If not, can this be re-opened?
