### ISSUE TITLE
incompatible_provide_cc_toolchain_info_from_cc_toolchain_suite: Provide CcToolchainInfo from cc_toolchain_suite, not cc_toolchain.

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/bazel#6537]
**Flag:** `--incompatible_provide_cc_toolchain_info_from_cc_toolchain_suite`
**Available since:** 0.20
**Will be flipped in:** 0.21
**Enclosing tracking issue:** https://github.com/bazelbuild/bazel/issues/6072

In the past, cc_toolchain was selected during the configuration construction, and we want to move it the proper analysis phase. For that we need to change which rule provides `CcToolchainInfo`. Before it was `cc_toolchain`, now it will be `cc_toolchain_suite`. This will be mostly invisible change, things like `ctx.fragments.cpp.cc_toolchain` configuration field, [`cc_toolchain_alias`](https://source.bazel.build/bazel/+/4ca2b6d5c4d201009ff21a3abbeddd9d58d4c95b:tools/cpp/BUILD;l=50), and [`find_cpp_toolchain`](https://source.bazel.build/bazel/+/4ca2b6d5c4d201009ff21a3abbeddd9d58d4c95b:tools/cpp/toolchain_utils.bzl;l=23) will keep working transparently. 

_To refresh your understanding of how C++ specific toolchain selection works, see the [docs](https://docs.bazel.build/versions/master/crosstool-reference.html#toolchain-selection)._

**Observable changes:**

* Label of the resolved target aliased by `//tools/cpp:current_cc_toolchain` will be different
* `rule.kind` will be `cc_toolchain_suite`, not `cc_toolchain`.

**Migration notes:**

Unfortunately there is no domain-independent solution.

**Important note:**

C++ rules will migrate to [platforms](https://docs.bazel.build/versions/master/platforms.html) in 2019. When that happens, `cc_toolchain_suite` will be removed, and generic toolchain selection mechanism will be used. When we get there, we will again provide `CcToolchainInfo` from `cc_toolchain`. **Therefore we advice you to make your code work with both `cc_toolchain` and `cc_toolchain_suite`, to save you from the future migration.**

**Comment by oquenchil** [comment]
This should not cause any breakages. The only breakages one might see if in a rule a user is checking for the rule kind. Instead the user should check for the presence of CcToolchainInfo.
