### ISSUE TITLE
Remove sysroot information from CppConfiguration

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#6543]
Currently, the ` cc_toolchain` rule is looking up the label for the sysroot from the CppConfiguration. In order to break this, we need a new cc_toolchain attribute to make this connection, and to remove the legacy handling.

Internal issue: http://b/78578234

**Comment by benjaminp** [comment]
Is "systool" supposed to be "sysroot"? I'd never heard of this term before 4dd755ab2b515fa3ec9f88e4f9e5f7d76707c1c2 nor does it appear elsewhere in the codebase.

**Comment by katre** [comment]
Yes, thank you, I apparently cannot type today.

**Comment by katre** [comment]
Sending a new patch to fix the name of the flag...

**Comment by katre** [comment]
This work is done, and I believe @mhlopko has removed the legacy code path.
