### ISSUE TITLE
Java compile resource renaming

### ISSUE THREAD

**Issue by timpeut** [bazelbuild/bazel#6545]
The [native java compile builder](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/java/JavaTargetAttributes.java#L291) allows setting a path for a resource (which is where it will be placed in the jar). The [starlark implementation](https://docs.bazel.build/versions/master/skylark/lib/java_common.html#compile) does not support this, instead just using the resource path as the jar path.

We'd like to add the ability to specify a custom resource jar path to align these APIs. Rather than modifying the `resources` param (backwards incompatible) we'd like to introduce a new `resource_renames` param which optionally maps resource paths to a corresponding jar path.

**Comment by regisd** [comment]
Can you clarify?

In a Maven layout, let's say you have 
- `src/main/resources/foo/foo.properties`
- `src/main/resources/bar/bar.properties`

Currently, this places 2 resources in the jar:
- `foo/foo.properties`
- `bar/bar.properties`

What could you place in the `resource_renames` attributes and how would it change the resources in the jar?

**Comment by timpeut** [comment]
Discussed alternatives. Will not be proceeding with this.
