### ISSUE TITLE
issue bootstrapping 0.19 on centos7

### ISSUE THREAD

**Issue by cushon** [bazelbuild/bazel#6550]
@lberki 

context: see discussion in #6116 starting around https://github.com/bazelbuild/bazel/issues/6116#issuecomment-434051680

137504e8cacda23efcc4b74f7c1b03e0074da030 removed the logic that selected a `java_toolchain` based on the `--server_javabase`. Normally that logic is useless because the `--server_javabase` is always the embedded JDK 9, but the `-dist.zip` archives produce a binary without an embedded JDK (I'm not sure why? #6131), which still allow using an older `--server_javabase`.

So under 0.18 and earlier you could bootstrap with JDK 8 and also use JDK 8 as a `--host_javabase` without passing additional flags. Under 0.19 that results in the following error:

```
$ cd $(mktemp -d)
$ export JAVA_HOME=$JAVA8_HOME
$ wget https://github.com/bazelbuild/bazel/releases/download/0.19.0/bazel-0.19.0-dist.zip
$ unzip bazel-0.19.0-dist.zip
$ ./compile.sh
$ ./output/bazel build //scripts:bazel-complete.bash
...
Unrecognized VM option 'CompactStrings'
Error: Could not create the Java Virtual Machine.
```

The fix is to explicitly select a the `java_toolchain` that is compatible with a JDK 8 `--host_javabase`:

```
$ ./output/bazel build \
  --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8 \
  --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8 \
  //scripts:bazel-complete.bash
...
OK
```

Using `--incompatible_use_remotejdk_as_host_javabase` (which isn't available in 0.19) also avoids the problem.

**Comment by lberki** [comment]
I vote for doing nothing here. `--incompatible_use_remotejdk_as_host_javabase` is going to be flipped soon and then this will just work. In the meantime, that's a reasonable workaround. WDYT?

/cc @iirina @meisterT

**Comment by katre** [comment]
@lberki Release 0.19 cannot be built on redhat and centos systems, meaning those users cannot upgrade past 0.18.

Is the flip for `--incompatible_use_remotejdk_as_host_javabase` going to be something we can cherrypick into a 0.19.1 release to unbreak these users?

**Comment by meisterT** [comment]
@katre sounds good to me

**Comment by vbatts** [comment]
it's not just centos7 ... fedora 27, 28, 29, and rawhide. 
https://copr-be.cloud.fedoraproject.org/results/vbatts/bazel/fedora-29-x86_64/00816673-bazel/build.log.gz
Scroll to the bottom for the error output

**Comment by katre** [comment]
@meisterT Looks like `--incompatible_use_remotejdk_as_host_javabase` was added after the cut for 0.19.0. I tried cherrypicking that and flipping the flag's default, but the build (on fedora) fails due to the missing external repo `@remotejdk_linux//`:
```
ERROR: /tmp/bazel_BWYrQSCU/out/external/bazel_tools/tools/jdk/BUILD:320:1: no such package '@remotejdk_linux//': /root/rpmbuild/BUILD/bazel-0.19.0/derived/distdir/zulu9.0.7.1-jdk9.0.7-linux_x64-allmodules.tar.gz (No such file or directory) and referenced by '@bazel_tools//tools/jdk:remote_jdk'
ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted: Analysis failed
INFO: Elapsed time: 2.446s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (66 packages loaded, 707 targets c\
onfigured)
```

I assume there are other commits that need to be cherrypicked? I'm not sure how comfortable I am with adding these to the release.

**Comment by katre** [comment]
Repro directions:

1. Start a docker container: `docker run -it fedora bash`, then `cd /root`
2. In the container, install prerequisites: `dnf install rpm-build java-1.8.0-openjdk-devel zlib-devel pkgconfig python gcc-c++`
3. Download the spec file: `curl https://copr-be.cloud.fedoraproject.org/results/vbatts/bazel/fedora-rawhide-x86_64/00816673-bazel/bazel.spec > bazel.spec`
4. Edit the spec file, change the `Source0` line to "bazel-distfile.zip"
5. In a separate terminal, build the Bazel distfile: `bazel build //:bazel-distfile`
6. Copy the distfile to your docker container:
  - Run `docker ps` to get the container id
  - Then do `docker cp bazel-genfiles/bazel-distfile.zip $CONTAINER:/root`
7. Move the distfile to the right location:
  - `mkdir -p rpmbuild/SOURCES`
  - `mv bazel-distfile.zip rpmbuild/SOURCES/`
8. Finally, start the build: `rpmbuild -bb --target x86_64 --nodeps bazel.spec`

**Comment by meisterT** [comment]
@aehlig suggests to do a similar thing like here: https://bugs.freebsd.org/bugzilla/attachment.cgi?id=198759&action=diff

other than that, the distfile doesn't contain the remote JDKs and if we include them like here
https://github.com/bazelbuild/bazel/blob/master/WORKSPACE#L219
the build succeeds.

However, it adds architecture dependent files to the distribution archive which is intended to be distribution independent.

**Comment by katre** [comment]
I agree, including the jdk in the distfile is a bad choice. I'll look and see if we can include a patch like that. And then add lots of testing around it.

**Comment by cushon** [comment]
I though the plan for `--incompatible_use_remotejdk_as_host_javabase` was to ship it in 0.20 and then enable it by default in 0.21. Trying to accelerate that change in to 0.19x seems ambitious.

If you want a cherry-pick, 137504e8cacda23efcc4b74f7c1b03e0074da030 still rolls back cleanly and restores the previous behaviour: #6555

Are there problems with using `--host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8 --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8`, though? That's the supported way to build with a JDK 8 `--host_javabase`. The fact that this previously worked for `-dist.zip` binaries running on JDK 8 was kind of an accident.

**Comment by cushon** [comment]
> my suggested patch was meant as a downstream-patch

Something like https://bugs.freebsd.org/bugzilla/attachment.cgi?id=198759&action=diff looks fine. That's basically baking in `--host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8 --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8`. You could do that a little more directly by renaming `@bazel_tools//tools/jdk:toolchain_hostjdk8` to `@bazel_tools//tools/jdk:toolchain` without modifying `default_java_toolchain.bzl`.

**Comment by katre** [comment]
Yes, I have a downstream patch I'd like to ask @vbatts to apply. I've attached the patch and the edited bazel.spec file. The edited file just uses the patch from the local system, so we'll need somewhere to host the patch so it can be applied during the build.

@vbatts Is this something that works with the COPR system? I don't know enough about how that functions.

[rpm-jdk8.zip](https://github.com/bazelbuild/bazel/files/2530680/rpm-jdk8.zip)

**Comment by vbatts** [comment]
i'm watching https://copr.fedorainfracloud.org/coprs/vbatts/bazel/build/817021/

**Comment by vbatts** [comment]
@katre all green with your changes

**Comment by katre** [comment]
Great! Do we need another bazel release, then, or is the fedora/centos release ready now?

**Comment by katre** [comment]
Great, I think we can close this, I'll update #6116.

Thanks for your help!
