### ISSUE TITLE
Support for the equivalent of strip_include_prefix for py_library

### ISSUE THREAD

**Issue by c-y-koo** [bazelbuild/bazel#6556]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

For cc_library, there is the concept of strip_include_prefix. It'll be nice to have something equivalent 
like strip_import_prefix that we can apply for py_library target.

### Feature requests: what underlying problem are you trying to solve with this feature?

Currently, in our github repo, the cc codes are under the directory 
"cc/component/foo/...". With strip_include_prefix, external repo can include our library by 
"component/foo/..."

We plan to add the python port version of the cc codes under
"py/component/foo/...". It will be nice if external repo can import the python library by 
"component.foo..." instead of "py.component.foo..."

###  Have you found anything relevant by searching the web?

From https://groups.google.com/forum/#!topic/bazel-discuss/MPOwCq-cMdw, creating the build targets under py/ and adding import ["."] may work, but it seems to mean we need to move the build targets there which is not ideal.

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by brandjon** [comment]
Interesting proposal. When we get around to revisiting how imports are handled this will be a useful use case to keep in mind.

**Comment by brandjon** [comment]
@c-y-koo upon rereading this I'm a bit confused -- why is this not solved by `[py_library.imports](https://docs.bazel.build/versions/master/be/python.html#py_library.imports)`? If I understand correctly you're already going to expose your Python library targets under `//py/...`, so it should be enough to have all the `py_library`s under here include in their transitive closure a dep on a basic `py_library` with `imports = ["."]` (or whatever the relative path is from this basic library target to //py).

**Comment by nvachhar** [comment]
For my use case, the issue with `py_library.imports` is that code can appear as two different modules in python. In the example above, you could reference it as `py.foo` or `foo`. In python, this distinction is often important and undesirable.
