### ISSUE TITLE
Documentation claims Bazel requires JDK8

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#6557]
Currently the install documents (at https://docs.bazel.build/versions/master/install-compile-source.html#bootstrap-unix-prereq) claim that Bazel works with JDK8, but this is no longer accurate. We need to update the docs to correctly explain the required JDK versions.

**Comment by cushon** [comment]
@lberki 

It depends what "works with" means (`--server_javabase`, `--host_javabase`, or `--javabase`)? Have we decided which JDK versions are supported yet?

Those docs are talking about bootstrapping, and JDK 8 is probably still a fine choice for that. The issue in #6550 only affects the binaries without an embedded JDK.

**Comment by meisterT** [comment]
@katre I just followed the steps in a docker container and it produced a working bazel binary.

**Comment by katre** [comment]
@meisterT Was that comment supposed to be on a different issue?

**Comment by meisterT** [comment]
No, the comment was meant to be on this issue. However, in the meantime I was made aware that while the bootstrap succeeds and the resulting binary can build C++, it cannot build Java.

Assigning to @lberki to clarify supported Java version before we spend any time here.

cc @iirina

**Comment by lberki** [comment]
Regrettably, bootstrapping does *not* work with JDK 9, at least on Ubuntu 16.04 and Bazel 0.18 (I just checked). So the instructions are indeed accurate.

**Comment by lberki** [comment]
Actuall

**Comment by baryluk** [comment]
In bootstraping doc, I also found that it uses openjdk-8-jdk package as an example, but I think it is better to use `default-jdk-headless` (Debian/Ubuntu) , and if needed it will install newer JDK. User will still need to verify it is at least JDK 8 or 9.

**Comment by Flamefire** [comment]
Related issue: https://github.com/bazelbuild/bazel/issues/6035

So:
> It depends what "works with" means

The docu states clearly "JDK 8. You must install version 8 of the JDK. Versions other than 8 are not supported." but #6035 states that "--host_javabase=<JDK8> won't work anymore."

Especially building Bazel on Power9 is a PITA due to the Java dependency.
