### ISSUE TITLE
Document the exec_compatible_with attribute

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#6558]
We should document the `exec_compatible_with` attribute that can be used to influence the execution platform for a specific target.

**Comment by katre** [comment]
@spomorski, we have https://docs.bazel.build/versions/master/be/common-definitions.html, where should the `exec_compatible_with` attribute be documented? It can currently be used with any test rule, and shell rule, or genrule, but we may expand that set in the future.

**Comment by spomorski** [comment]
I think that page is fine. You didn't mention build rules, does it work
with just test/shell/genrules (I might just be misunderstanding
shell/genrules)? If it works for build rules, let's just stick it in
"Attributes common to all build rules."

**Comment by katre** [comment]
Sorry, by shell rules I mean sh_library, sh_binary, and sh_test.

I'll start adding some documentation to the common definitions.
