### ISSUE TITLE
Spurious(?) deprecation warning on --ios_simulator_version

### ISSUE THREAD

**Issue by davidsantiago** [bazelbuild/bazel#656]
If you run an iOS app through the simulator using the --ios_simulator_version tag, you will get a warning:

```
$ bazel run ios-example --ios_sdk_version=9.1 --ios_simulator_version=9.1
WARNING: Option 'ios_simulator_version' is deprecated: Use target_device instead to drive the simulator to use.
```

No matter what input I give to --target_device, it is marked as an unrecognized option:

```
$ bazel run ios-example --ios_sdk_version=9.1 --target_device=9.1
Unrecognized option: --target_device=9.1
$ bazel run ios-example --ios_sdk_version=9.1 --target_device='iPhone 5s'
Unrecognized option: --target_device=iPhone 5s
$ bazel run ios-example --ios_sdk_version=9.1 --target_device
Unrecognized option: --target_device
```

When I search the source code, I don't get that many hits for it: https://github.com/bazelbuild/bazel/search?utf8=%E2%9C%93&q=target_device It seems to be used by the test rules, but doesn't seem to be connected to the command line options. 

I'm not sure what's going on here, but this seems confusing and maybe worth straightening up, even if it's just a change in the phrasing of the warning or a documentation update.

**Comment by ulfjack** [comment]
That warning isn't coming from bazel, but from something that bazel runs. If you want to get rid of the warning, you'll have to figure out what that is and who's passing it the ios_simulator_version flag.

**Comment by davidsantiago** [comment]
Really? It looks like it's coming from this line: https://github.com/bazelbuild/bazel/blob/54f1562b60b6839adddbfc4706c0190c8aa48995/src/main/java/com/google/devtools/build/lib/rules/objc/ObjcCommandLineOptions.java#L47

Though, the thing that's passing the --ios_simulator_version flag is me, at the command line. bazel run won't work for a simulator-run ios app without it: 

```
$ bazel run ios-example --ios_sdk_version=9.1
INFO: Found 1 target...
Target //ios-example:ios-example up-to-date:
  bazel-bin/ios-example/ios-example.ipa
  bazel-bin/ios-example/ios-example.xcodeproj/project.pbxproj
INFO: Elapsed time: 1.546s, Critical Path: 1.03s

INFO: Running command line: bazel-bin/ios-example/ios-example_runner.sh
iossim: ERROR: Invalid SDK version: 8.4
Supported device/SDK combinations:
  -d 'iPhone 4s' -s '9.1'
  -d 'iPhone 5' -s '9.1'
  -d 'iPhone 5s' -s '9.1'
  -d 'iPhone 6' -s '9.1'
  -d 'iPhone 6 Plus' -s '9.1'
  -d 'iPhone 6s' -s '9.1'
  -d 'iPhone 6s Plus' -s '9.1'
  -d 'iPad 2' -s '9.1'
  -d 'iPad Retina' -s '9.1'
  -d 'iPad Air' -s '9.1'
  -d 'iPad Air 2' -s '9.1'
  -d 'iPad Pro' -s '9.1'
  -d 'Apple TV 1080p' -s '9.0'
  -d 'Apple Watch - 38mm' -s '2.0'
  -d 'Apple Watch - 38mm' -s '2.0'
  -d 'Apple Watch - 42mm' -s '2.0'
  -d 'Apple Watch - 42mm' -s '2.0'
ERROR: Non-zero return code '3' from command: Process exited with status 3.
```

With the flag passed on the command line, it spits out the WARNING: about the flag being deprecated, and to use target_device instead, but it does run. Using target_device, it does not run.

**Comment by ulfjack** [comment]
My bad. There is no target_device command line flag. I think this refers to
the ios_test.target_device attribute, maybe?

**Comment by davidsantiago** [comment]
Right, I think that's it. Ideally, you could make this flag only be deprecated when it's run on bazel test, or alternatively, have the new mechanism hooked up to bazel run. I don't see any system for making a flag be deprecated only when used with a certain command, and I don't see any replacement for this flag for a regular "bazel run" invocation. But I could be wrong about either of those. 

If that's the case, though, perhaps the "right now" thing would be to rephrase the deprecation warning to make it clear that it only applies to bazel test invocations, and that target_device is a rule attribute, not a flag (this was something I still hadn't realized until your last reply).

**Comment by c-parsons** [comment]
Deprecation warning for this flag is removed.
