### ISSUE TITLE
apt-repo Packages checksum mismatch

### ISSUE THREAD

**Issue by sevki** [bazelbuild/bazel#6563]
follow the instructions here https://docs.bazel.build/versions/master/install-ubuntu.html#install-on-ubuntu to reproduce but it looks like [Packages.gz](http://storage.googleapis.com/bazel-apt/dists/stable/jdk1.8/binary-amd64/Packages.gz) hasn't been updated with the updated package checkums
```
   Hashes of expected file:
    - Filesize:621 [weak]
    - SHA256:aace1389ded36ae55214b010ee514095f8e87357ec7b3355755b9fdd22bc5bb4
    - SHA1:c776e8d89f3427cca06931e6938273a19888673e [weak]
    - MD5Sum:a85a3148f6938eee6c7f6ba56e6615dc [weak]
   Hashes of received file:
    - SHA256:ec1b421fca4db704271e1eaf15aafa4339832bdc8e88899aea22e44c0c2fa7f5
    - SHA1:a07897a5e5d88faa2f7985fc9d968d02c0e3d430 [weak]
    - MD5Sum:2f24c80b5c9e64e299b3a914d6681f95 [weak]
    - Filesize:621 [weak]
   Last modification reported: Wed, 31 Oct 2018 14:52:16 +0000
   Release file created at: Mon, 29 Oct 2018 14:41:12 +0000
```

**Comment by jin** [comment]
cc @katre @aehlig

**Comment by sevki** [comment]
this seems to be caused by the slow roll-out process.
while CI is building and updating artifacts Packages.gz is not updated. 
a very quick fix for this would be using 2 buckets. ie, 

releasing 0.20.0
bazel-a.googlestroage.com <- serving 0.19.0
bazel-b.googlestroage.com #  is getting updated with 0.20.0

releasing 0.20.1
bazel-a.googlestroage.com #  is getting updated with 0.20.1
bazel-b.googlestroage.com <- serving 0.20.0

so on and so forth. I know this would make the release process a bit more complicated but there is a good 20mins when CI builds were failing because of this. 

I'm happy to help with this issue if you need it

**Comment by mikepurvis** [comment]
This is still broken. The `Packages.gz` file is being served as 0 bytes:

```
$ sudo apt update
[snip]
E: Failed to fetch http://storage.googleapis.com/bazel-apt/dists/stable/jdk1.8/binary-amd64/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.

$ wget http://storage.googleapis.com/bazel-apt/dists/stable/jdk1.8/
binary-amd64/Packages.gz
--2019-04-09 14:52:14--  http://storage.googleapis.com/bazel-apt/dists/stable/jdk1.8/binary-amd64/Packages.gz
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.164.240, 2607:f8b0:400b:801::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.164.240|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 0 [application/octet-stream]
Saving to: 'Packages.gz'

Packages.gz                       [ <=>                                              ]       0  --.-KB/s    in 0s      

2019-04-09 14:52:14 (0.00 B/s) - 'Packages.gz' saved [0/0]

$ ls -la
total 8
drwxrwxr-x  2 administrator administrator 4096 Apr  9 14:52 .
drwxr-xr-x 83 administrator administrator 4096 Apr  9 14:42 ..
-rw-rw-r--  1 administrator administrator    0 Apr  2 12:56 Packages.gz
```

Is everyone just building bazel from source? This seems like a huge problem to have gone unnoticed fro months.

**Comment by sevki** [comment]
Closed this since no one cared or complained about this. So I’m assuming it’s good

**Comment by mikepurvis** [comment]
It's working for me at the moment, but I have no idea how consistent it is— I don't use Bazel regularly.
