### ISSUE TITLE
incompatible_disable_sysroot_from_configuration: libc_top should be set by attribute

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#6565]
Flag: --incompatible_disable_sysroot_from_configuration
Available since: 0.20
Will be flipped in: 0.21
Enclosing tracking issue: #6543

The sysroot (also called `grte_top` and `libc_top`) was previously set by default in the CROSSTOOL file, using the `default_grte_top` property. As this is a build label, and creates a new dependency in the build, it needs to be moved into an actual build target.

The `cc_toolchain` rule now has an attribute called `libc_top` that is used to set this value.

Migration notes:
To migrate, remove any `default_grte_top` properties in your CROSSTOOL file, and set the `libc_top` attribute on the corresponding `cc_toolchain` target to be the same value. The `libc_top` needs to be a fully-qualified label, so in many cases the value from CROSSTOOL will need to have `:everything` added to refer to a specific target.

**Comment by katre** [comment]
The new incompatible change flag will be available in the 0.20 release, and the default value will be flipped to `true` in the 0.21 release.

**Comment by dslomov** [comment]
> Migration notes:
> To migrate, remove any default_grte_top properties in your CROSSTOOL file, and set the libc_top attribute on the corresponding cc_toolchain target to be the same value. The libc_top needs to be a fully-qualified label, so in many cases the value from CROSSTOOL will need to have :everything added to refer to a specific target.

If people do that, will it work without the flag?

**Comment by katre** [comment]
Yes, the migration is backwards compatible.

**Comment by katre** [comment]
Migration is done and legacy code is removed.
