### ISSUE TITLE
If I do --bazelrc=<absolute path>, Bazel claims the file is "no longer being read," but in fact it is

### ISSUE THREAD

**Issue by mmorearty** [bazelbuild/bazel#6566]
### Description of the problem / feature request:

With Bazel 0.19.0, if I pass `--bazelrc=/tmp/my.rc`, or any other absolute path, Bazel prints a message warning me that that RC file is not being read, when in fact it _is_ being read.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Make a file called `/tmp/my.rc`, and put something illegal in it, such as

```
build --bogusarg
```

Then tell Bazel to use it:

```
bazel --bazelrc=/tmp/my.rc build --announce_rc :all
```

Result: Bazel prints this warning message:

```
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/tmp/my.rc
```

But then it proceeds to read the file (and complain about the invalid arg):

```
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=152
INFO: Reading rc options for 'build' from /private/tmp/my.rc:
  'build' options: --xyz
ERROR: Unrecognized option: --xyz
```

### What operating system are you running Bazel on?

macOS High Sierra, 10.13.6

### What's the output of `bazel info release`?

release 0.19.0

###  Have you found anything relevant by searching the web?

No. Searched GitHub

### Any other information, logs, or outputs that you want to share?

I ran into this because we have a script that builds a temporary .rc file with the options we want and then runs Bazel.

**Comment by mmorearty** [comment]
cc @cvcal

**Comment by cvcal** [comment]
Thanks for the bug report!

@jmmv - this should all work by string compare, as you know, so somewhere the path must be getting mutated on mac.
