### ISSUE TITLE
incompatible_remove_native_http_archive: move to Starlark version of `http_archive`

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/bazel#6570]
Flag [incompatible_remove_native_http_archive](https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#remove-native-http-archive)

We're moving away from the native familty of `http_archive` functions to the [Starlark version of `http_archive`](https://github.com/bazelbuild/bazel/blob/c1f6455d38399853ff9f34e3eb5e8ca26e590290/tools/build_defs/repo/http.bzl#L139). The new function can be loaded with `load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")` and provides the same functionality; in fact, patching and programatic transformations of the repository are available as well.

By this change we remove duplicate functionality and switch from native rules to more flexible and more easy to maintain Starlark implementations of the same functionality.

**Comment by aehlig** [comment]
The flag was already flipped by a55714c; this issue is for documentation purpose only.

**Comment by mnlnl4** [comment]
new_http_archive is broken by this?
