### ISSUE TITLE
bazel test is failing with Java version mismatch when toolchain_vanilla is used

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#6573]
On most recent Bazel version (c1f6455d38399853ff9f34e3eb5e8ca26e590290) I'm trying to build (works) and run the tests on JGit project with Java 10. While build is working, tests are failing with java version mismatch. It seems, that for tests, Java 8 is used, even though Java 10 should be used:

```
  $ bazel test --host_javabase=:absolute_javabase --define=ABSOLUTE_JAVABASE=/usr/lib64/jvm/java-10 --host_java_toolchain=//:toolchain_vanilla --java_toolchain=//:toolchain_vanilla //...
[...]
java.lang.UnsupportedClassVersionError: org_eclipse_jgit_merge_CrissCrossMergeTestTestSuite has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

To reproduce, clone JGit (`git clone https://git.eclipse.org/r/jgit/jgit`), apply this CL: [1] and run:

```
  $ bazel test --host_javabase=:absolute_javabase --define=ABSOLUTE_JAVABASE=/usr/lib64/jvm/java-10 --host_java_toolchain=//:toolchain_vanilla --java_toolchain=//:toolchain_vanilla //...
```

Can it be, that `JAVA_HOME` has to be adjusted for `bazel test`? I think it was still pointing to Java 8 in that case. (And this would be unexpected, when `--host_javabase` is used).

[1] https://git.eclipse.org/r/#/c/128083

//CC @cushon

**Comment by cushon** [comment]
`bazel test` runs the test using the target javabase, i.e. `--javabase`. Are you configuring `--javabase` anywhere?

See also the [relnotes for 0.19](https://github.com/bazelbuild/bazel/releases/tag/0.19.0):

> Bazel now requires a JDK to be installed as it no longer falls back to the internal JDK if the --javabase flag is not set. Instead, Bazel now searches for a JDK within the JAVA_HOME and PATH environment variables. If Bazel cannot find a JDK, it will not be able to run Java builds.

**Comment by cushon** [comment]
> In fact, with older Bazel versions, it worked as expected without passing this option.

When it worked, which JDK was the test using?

**Comment by davido** [comment]
Java 10.

**Comment by davido** [comment]
@cushon As you assumed, JAVA_HOME was set to Java 8 in that case:

```
  $ $JAVA_HOME/bin/java -fullversion
openjdk full version "1.8.0_171-b11"
```

I confirmed, that both options:

1. Explicitly passing: `--javabase=:absolute_javabase`
or
2. Setting `JAVA_HOME` to Java 10: `$ JAVA_HOME=/usr/lib64/jvm/java-10 bazel test ...`

fixed this issue.

**Comment by cushon** [comment]
> > When it worked, which JDK was the test using?
> Java 10.

Did you verify it was using your local `/usr/lib64/jvm/java-10`? I was wondering if it was falling back to using the embedded JDK, before support for that was removed.

**Comment by davido** [comment]
> Did you verify it was using your local /usr/lib64/jvm/java-10?

I have not.

> I was wondering if it was falling back to using the embedded JDK, before support for that was removed.

I guess you are right. I think it WAI and as documented in the release notes. Thanks for the help.
