### ISSUE TITLE
Flags parsing errors are unhelpful for early startup issues

### ISSUE THREAD

**Issue by asuffield** [bazelbuild/bazel#6574]
### Description of the problem / feature request:

When bazel is working correctly, a command like: `bazel build --output_user_root=foo` gives the correct response of "Unrecognised option --output_user_root=foo", because the flag is in the wrong place.

When bazel cannot start up, it doesn't get as far as parsing these flags, and the output is rather more mysterious. Notably we noticed this when --output_user_root was necessary because the default location is read-only (coincidentally, this was within the test environment, using the bazel_test rule from rules_go): the output is entirely unhelpful and doesn't mention the misplaced argument.

This is non-trivial to fix because the flags parser is in java and this is before we have unpacked the jvm. I'm not sure what the best approach is here.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

rm -r $HOME/.cache/bazel
touch $HOME/.cache/bazel
bazel build --output_user_root=$HOME/tmp

**Comment by laszlocsomor** [comment]
Repro without nuking your actual Bazel cache:

```
  $ docker run -it --init gcr.io/bazel-public/ubuntu1804:java11 /bin/bash
root@6ef140580e39:/# rm -rf $HOME/.cache/bazel
root@6ef140580e39:/# touch $HOME/.cache/bazel
root@6ef140580e39:/# bazel build --output_user_root=$HOME/tmp
2019/08/16 09:11:41 Downloading https://releases.bazel.build/0.28.1/release/bazel-0.28.1-linux-x86_64...
FATAL: mkdir('/root/.cache/bazel/_bazel_root'): (error: 20): Not a directory
```
