### ISSUE TITLE
incremental correctness problem with java deploy jars and `build-info-redacted.properties`

### ISSUE THREAD

**Issue by kevingessner** [bazelbuild/bazel#6575]
### Description of the problem / feature request:

I believe I've found a latent correctness problem with the `bazel-out/k8-fastbuild/include/build-info-redacted.properties` file that is used when assembling deploy jars with singlejar.  The order of lines in that file is inconsistent; when singlejar assembles the deploy jar, it puts that file into the jar as `build-data.properties`, preserving the ordering.  That leads to inconsistencies, such as this one between two builds in my CI infra:

```
:) > diffoscope --progress 3ad6fbfbed23.jar 45a01e7dcdf7.jar
--- 3ad6fbfbed23.jar
+++ 45a01e7dcdf7.jar
├── zipinfo /dev/stdin
│ @@ -1,8 +1,8 @@
│ -Zip file size: 185070493 bytes, number of entries: 104367
│ +Zip file size: 185070494 bytes, number of entries: 104367
[redacted]
│ -104367 files, 632272626 bytes uncompressed, 163610733 bytes compressed:  74.1%
│ +104367 files, 632272626 bytes uncompressed, 163610734 bytes compressed:  74.1%
├── build-data.properties
│ @@ -1,4 +1,4 @@
│  build.target=bazel-out/k8-fastbuild/bin/apps/etsy-search1/etsy-search_deploy.jar
│ +build.time=Thu Jan 01 00\:00\:00 1970 (0)
│  build.timestamp.as.int=0
│  build.timestamp=Thu Jan 01 00\:00\:00 1970 (0)
│ -build.time=Thu Jan 01 00\:00\:00 1970 (0)
```

Note the lines of `build-data.properties` are the same in two built jars, but are in different orders.  This ultimately spoils caching, because the jars have different SHAs, particularly the hash of a docker image that contains this jar.

I have two theories about what is happening here:

1. The `WriteBuildInfoPropertiesAction` that creates `build-info-redacted.properties` uses `java.util.HashMap` and `java.util.Properties` under the hood to track the keys written to the file.  These classes don't guarantee ordering during iteration, so it's possible different runs will produce different files. Nonetheless we're seeing inconsistencies between builds with the same java version, and map iteration ordering should at least be consistent within a version, for the same content.

2. `build-info-redacted.properties` has changed over different versions of bazel, but isn't properly cleared from the cache.  Some of our CI servers have long-lived `bazel-out` directories, where the `build-info-redacted.properties` file is months old; that means it was built by a different bazel version, which we've since upgraded.  The older files are generally showing the different order from servers with newer files.  So perhaps the problem is that `bazel-out/k8-fastbuild/include/build-info-redacted.properties` isn't cleared when bazel is upgraded, and different versions produce different orderings.

Possibly it's due to a combination of these bugs or something completely different.  In any case, I think it would be best if `WriteBuildInfoPropertiesAction` explicitly set a deterministic order for the lines of files it produces, rather than relying on possibly-inconsistent ordering.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I haven't yet been able to narrow this down to a specific repro.  I think this is due to correctness or inconsistency across bazel versions or due to some specific runtime fact that I can't track down.

### What operating system are you running Bazel on?

Centos 7 with ```openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)```
### What's the output of `bazel info release`?

> Replace this line with your answer.

`release 0.17.2`, but as I said above, I think this might be an inconsistency across versions.

###  Have you found anything relevant by searching the web?

Nope

**Comment by comius** [comment]
I've seen the same thing in java_tools deployments.

**Comment by fmeum** [comment]
Looks like this was fixed inhttps://github.com/bazelbuild/bazel/commit/aafaa131ef2cd4115929f10c743d5a696a90c857.

**Comment by SinOverCos** [comment]
I'm seeing a similar issue where my caching is spoiled by the `build.time*` fields being the actual build time instead of a static value. Wondering how you were able to set the build time to epoch 0?
