### ISSUE TITLE
Missing bazel-0.18.1-installer-darwin-x86_64.sh

### ISSUE THREAD

**Issue by msohn** [bazelbuild/bazel#6577]
### Description of the problem / feature request:

It seems the file bazel-0.18.1-installer-darwin-x86_64.sh is missing for release 0.18.1
https://github.com/bazelbuild/bazel/releases/tag/0.18.1

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try to install bazel 0.18.1 on a Mac

**Comment by davido** [comment]
FWIW: The darwin installer can be found [here](https://releases.bazel.build/0.18.1/release/index.html).

**Comment by msohn** [comment]
thanks, meanwhile I upgraded to 0.19

**Comment by jin** [comment]
@meteorcloudy has manually uploaded the installer to the release page (thank you @meteorcloudy!!) 

Also see discussion on https://groups.google.com/forum/#!topic/bazel-discuss/tI6Q5QmbFCQ

Closing this now.

**Comment by msohn** [comment]
thanks
