### ISSUE TITLE
ctx.actions.run error message doesn't match args

### ISSUE THREAD

**Issue by mprobst** [bazelbuild/bazel#6581]
### Description of the problem / feature request:

Calling `ctx.actions.run(data = [...])` give this error message:

```
unexpected keyword 'data', in method call run(File executable, string progress_message, list data, depset inputs, list outputs, list arguments) of 'actions'
```

See how it suggests `run` has an argument `list data`. That's super confusing.

https://docs.bazel.build/versions/master/skylark/lib/actions.html#run

### Feature requests: what underlying problem are you trying to solve with this feature?

Docs/confusing error message.

### What's the output of `bazel info release`?

```
$ bazel info release
release 0.19.0
```

**Comment by laurentlb** [comment]
I'm confused, where do you see `list data`?

**Comment by laurentlb** [comment]
Ah, I see.
I think the line shows your call (and not the definition of the method).

**Comment by mprobst** [comment]
Well, that's quite confusing :-)

**Comment by laurentlb** [comment]
@c-parsons Now that we don't have method overloading anymore, it should be easier to get the method signature and show it there.

**Comment by brandjon** [comment]
Error is currently:

```
Error in run: run() got unexpected keyword argument 'data'
```
