### ISSUE TITLE
Ubuntu 18.10 c++ build throwing undeclared inclusion(s) in rule error

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel#6584]
### Description of the problem / feature request:

Some of our developers like to track the latest Ubuntu releases rather than LTS and after upgrading to 18.10 building [jsonnet](https://github.com/google/jsonnet) started failing with the following error:

```
(10:04:50) ERROR: /home/user/.cache/bazel/_bazel_user/065e0e2a065241c6d7a4f94e9637d7c2/external/jsonnet/third_party/md5/BUILD:4:1: undeclared inclusion(s) in rule
'@jsonnet//third_party/md5:libmd5':
this rule is missing dependency declarations for the following files included by 'external/jsonnet/third_party/md5/md5.cpp':
 '/usr/lib/gcc/x86_64-linux-gnu/7/include/stddef.h'
 '/usr/lib/gcc/x86_64-linux-gnu/7/include/stdarg.h'
 '/usr/lib/gcc/x86_64-linux-gnu/7/include/stdint.h'
```

They also tried to run `bazel clean --expunge` and that did not help. Building it with clang instead however does work (as mentioned in the jsonned readme).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Go on Ubuntu 18.10, clone https://github.com/google/jsonnet and run `bazel build //third_party/md5: libmd5`, that should then throw the error above.

### What operating system are you running Bazel on?

Ubuntu 18.10

### What's the output of `bazel info release`?

release 0.19.0

###  Have you found anything relevant by searching the web?

I have found some issues showing a very similar error message, but the provided solution did either not work (like running bazel clean --expunge), did not apply here, or was a bit too much over our cc toolchain knowledge

I was considering posting this on the jsonnet repository but since that is just using the native c++ rules it seems to me that the bazel repository is the right place.

**Comment by jin** [comment]
@scentini could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?

**Comment by gregoryEvlash** [comment]
@Globegitter 
I added `export CC=/usr/bin/g++` to my .bashrc and errors disappeared.

**Comment by Globegitter** [comment]
@gregoryEvlash Thanks, we resolved the issue by switching to the go version of jsonnet.

**Comment by hlopko** [comment]
This looks like a typical thing that happen after upgrading gcc, can you repro with `gcc` as `CC` after first running `bazel clean --expunge`?

**Comment by Globegitter** [comment]
Yep, we did also run `bazel clean --expunge` and it did not fix the issue.
