### ISSUE TITLE
should we re-release 0.19.0?

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/bazel#6588]
After the publish of bazel 0.18.1 - seems like the apt repository is confused to think that 0.18.1 is the latest version. Not sure about other packages repositories.

cc: @dslomov 

See what I had to do here:
https://github.com/GoogleCloudPlatform/cloud-builders/pull/403

**Comment by jin** [comment]
cc @katre 

Release 0.19.0 ref: https://github.com/bazelbuild/bazel/issues/6116

**Comment by katre** [comment]
For posterity: there's no way to actually re-release, just re-running the scripts would probably break in many different ways. The best alternative would be a 0.19.1 point-release with no actual new commits.

**Comment by philwo** [comment]
This was fixed and the apt repository gives 0.19.0 again.

We'll improve this in the future to make sure it won't break again.
