### ISSUE TITLE
Update embedded JDK to 11 to fix a host of docker related issues

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel#6592]
### Description of the problem / feature request:

As far as I can tell bazel is currently coming embedded with openjdk 9 and it is having issues with easily running out of memory in docker containers (most prominently CircleCI it seems), or more generically not respecting cgroups for resource limits.

issues I could find that seem releated:
https://github.com/bazelbuild/bazel/issues/3886
https://github.com/bazelbuild/bazel/issues/4616
https://github.com/bazelbuild/bazel/issues/5180
https://github.com/bazelbuild/bazel/issues/3645
https://github.com/bazelbuild/bazel/issues/5389

https://github.com/bazelbuild/rules_docker/issues/520

### Feature requests: what underlying problem are you trying to solve with this feature?

It turns out OpenJDK 10 comes with a host of fixes that would improve that situation and for us also just seemed to have solved an issue with using CircleCI. I installed bazel pointing at jdk 11 using `startup --server_javabase /usr/lib/jvm/java-11-openjdk-amd64/"` in the bazelrc, removed any flags around `local_resources` and builds that would continuously fail before are now working, in fact I had a build that would even fail with `local_resources` and `-Xmx3072m` set, but pointing bazel to use jdk 11 fixed that.

Here the links to the openjdk issues:
https://bugs.openjdk.java.net/browse/JDK-8196595
https://bugs.openjdk.java.net/browse/JDK-8146115
https://bugs.openjdk.java.net/browse/JDK-8170888
https://bugs.openjdk.java.net/browse/JDK-8140793

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Probably not that easy to reproduce, but I know rules_nodejs use circleci and had similar issues in the past that where solved with setting the same flags here: https://github.com/bazelbuild/rules_nodejs/blob/master/.circleci/bazel.rc#L17

So maybe they would be a good test case, trying to remove the flags and see if the situation improves. cc @alexeagle

### What operating system are you running Bazel on?

Ubuntu 18.04, the docker images are running on debian stretch

### What's the output of `bazel info release`?

release 0.19.0

###  Have you found anything relevant by searching the web?

Yep, see issues linked above.

**Comment by meisterT** [comment]
Cc @lberki @iirina

**Comment by Monnoroch** [comment]
Related: #6661.

**Comment by meisterT** [comment]
@Monnoroch There's no requirement anymore to have the same embedded JDK version as we use for the host javabase so #6661 is talking about updating the JDK version, it's a different JDK.

Independently, we also plan to upgrade the embedded JDK after we have submitted some other changes and hopefully it'll land before we cut 0.22.

If I understand the new java container support correctly, you probably still want to set a JVM flag in the container. The JVM uses by default 1/4 of the physical available memory for the heap. In a container, you may have less memory available than what's physically in your machine. Now, if the heap grows too large, Bazel gets killed. With the new container support, the "physical available memory" is limited to the memory available in the container. Thus, the heap will not grow too large, but it's using 1/4 of the available memory. That may not be enough and you might want to set MaxRamFraction in your CI environment.

**Comment by davido** [comment]
> Independently, we also plan to upgrade the embedded JDK after we have submitted some other changes and hopefully it'll land before we cut 0.22.

I tried 0.22rc2 yesterday and it is still using JDK 9.

**Comment by meisterT** [comment]
David, that's correct. I wasn't able to properly test and land the changes mostly because of holidays. I'll definitely do it before 0.23.

**Comment by davido** [comment]
@meisterT Thanks. Let me know, if you have a commit somewhere. I would be happy to build Bazel from scratch and test it against Gerrit Code Review and related projects.
