### ISSUE TITLE
Build of HEAD   fails on RHEL6

### ISSUE THREAD

**Issue by mj-harvey** [bazelbuild/bazel#661]
'''
./compile.sh build /path/to/bazel
🍃  Building Bazel from scratch.....
Compiling client .cc files...
g++ -I. -std=c++0x -c -DBLAZE_JAVA_CPU="k8" -DBLAZE_OPENSOURCE=1 -o /tmp/bazel.q8deWuKc/objs/blaze_util.cc.o src/main/cpp/blaze_util.cc
src/main/cpp/blaze_util.cc: In function ‘bool blaze::IsStandardTerminal()’:
src/main/cpp/blaze_util.cc:226: error: ‘nullptr’ was not declared in this scope
'''

The standard system gcc/g++ 4.4.6-4

 
commit c1b1eedc14856997d2bf68be5d94f937fb21d3a3

**Comment by damienmg** [comment]
nullptr is a C++11 construct if I am not mistaken. Maybe that's not supported by gcc 4.4.6?

I am not really the best to guess those stuff, @ulfjack can probably answer best.

**Comment by kchodorow** [comment]
Actually, looks like 4.4 is too old to be able to reference nullptr: https://gcc.gnu.org/projects/cxx0x.html (available in 4.6+). Do you have any more recent compiler on the system?

**Comment by mj-harvey** [comment]
I can get a bit further with 4.7.2, but that can't deal with "auto"
I've also 4.9.1, but this requires a newer libc. When that's in the LD path the Sun JDK malfunctions, deadlocking on a futex. the build then doesn't get any further than the exec() out to "java -verson".
Wrappering that out then leads to the lib abi compatibility  problem resurfacing when the java code tries to dlopen whatever naive code dso the Bazel build has make.

**Comment by mj-harvey** [comment]
If you're not familiar with RHEL6, I should say that 4.9.2 is available in the devtoolset-3 package but, for various reasons, I'm unable to install that on our target system.

**Comment by sethbruder** [comment]
In case it helps: gcc 4.8.2 (available in devtoolset-2, but also compilable from source) seems to be sufficient; details of my experience in #649

**Comment by damienmg** [comment]
This should be fixed.
