### ISSUE TITLE
bazel run environment variables

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#6612]
Document the `BUILD_WORKSPACE_DIRECTORY` and `BUILD_WORKING_DIRECTORY` variables

Context: https://groups.google.com/d/msg/bazel-discuss/Zk3W9x4x1MM/G1RYG2RUCgAJ

**Comment by rohansingh** [comment]
I think the pattern described in the linked bazel-discuss post is becoming more common. Our org has been using a number of silly workarounds and hacks because we didn't know about these vars.
