### ISSUE TITLE
Documentation for certain rules is missing

### ISSUE THREAD

**Issue by uri-canva** [bazelbuild/bazel#6619]
### Description of the problem / feature request:

Documentation for certain rules (for example `java_toolchain`) is missing on latest docs.build.bazel.

### Feature requests: what underlying problem are you trying to solve with this feature?

Read the docs.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://docs.bazel.build/versions/master/be/java.html

<img width="359" alt="screen shot 2018-11-07 at 1 32 02 pm" src="https://user-images.githubusercontent.com/33242106/48106906-91db3e00-e291-11e8-8eaf-d2b19662cbb5.png">

Note the missing `java_toolchain`, compare with:

https://web.archive.org/web/20181021162843/https://docs.bazel.build/versions/master/be/java.html

<img width="438" alt="screen shot 2018-11-07 at 1 32 10 pm" src="https://user-images.githubusercontent.com/33242106/48106927-a6b7d180-e291-11e8-9b61-5b0cbc64e8e4.png">

The source of the docs still exists on current master, so I don't think it's been removed intentionally: https://github.com/bazelbuild/bazel/blob/91e0bae6143e39f60e9d62e8b61854cbc8d7a4f4/src/main/java/com/google/devtools/build/lib/rules/java/JavaToolchainRule.java#L269

**Comment by jin** [comment]
cc @lberki

**Comment by jin** [comment]
Doc for java_import is also broken:

0.20.0: https://docs.bazel.build/versions/0.20.0/be/java.html#java_import 

java_import(name, deps, data, compatible_with, constraints, deprecation, distribs, exports, features, jars, licenses, neverlink, proguard_specs, restricted_to, runtime_deps, srcjar, tags, testonly, visibility)

0.21.0: https://docs.bazel.build/versions/0.21.0/be/java.html#java_import

java_import(name, deps, data, compatible_with, deprecation, distribs, exports, features, licenses, restricted_to, runtime_deps, tags, testonly, visibility)

**Comment by jin** [comment]
cc @iirina @buchgr @fweikert

**Comment by Profpatsch** [comment]
Please fix this, not finding this rule in the documentation cost me a considerable amount of time.
Writing docs for implemented code is not all that that much work compared to writing the code in the first place.

**Comment by jin** [comment]
cc @cushon
