### ISSUE TITLE
Can't build Bazel using Intel compiler (1)

### ISSUE THREAD

**Issue by mj-harvey** [bazelbuild/bazel#662]
Building Bazel on RHEL 6 using commit c1b1eedc14856997d2bf68be5d94f937fb21d3a3

In the absence of any documentation about doing this, I've set the paths for the "gcc" fields found in tools/cpp/CROSSTOOL to the fully-qualified path of icpc. Compiling gives:

'''
$ ./compile.sh 
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh build /path/to/bazel
🍃  Building Bazel from scratch.....
Compiling client .cc files...
icpc -I. -std=c++0x -c -DBLAZE_JAVA_CPU="k8" -DBLAZE_OPENSOURCE=1 -o /tmp/bazel.VWjj8WH4/objs/numbers.cc.o src/main/cpp/util/numbers.cc
src/main/cpp/util/numbers.cc(110): error: constant value is not known
    static_assert(vmax > 0, "");
                  ^

src/main/cpp/util/numbers.cc(140): error: constant value is not known
    static_assert(vmin < 0, "");
                  ^

compilation aborted for src/main/cpp/util/numbers.cc (code 2)

'''

$ icpc -v
icpc version 15.0.3 (gcc version 4.4.6 compatibility)

**Comment by davidstanke** [comment]
@mj-harvey Is this still relevant? (Can we move all discussion to #664?)
