### ISSUE TITLE
incompatible_windows_native_test_wrapper: enables Bash-less test execution on Windows

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#6622]
# Description

The option `--incompatible_windows_native_test_wrapper` enables using the Bash-less test wrapper on Windows. This flag has NO effect on other platforms.

When using `bazel test`, Bazel does not execute tests directly. Instead Bazel runs a "test wrapper" as a subprocess, which sets up the environment for the test and runs the test.

By default, Bazel uses a Bash script (`@bazel_tools//tools/test:test-setup.sh`) as the test wrapper, on all platforms. The new flag allows using an alternative test wrapper written in C++ that does not depend on Bash.

When the flag is enabled, Bazel uses the C++ test wrapper from `@bazel_tools//tools/test:tw`. This test wrapper does not depend on Bash, but it's new and has not yet been battle-tested.

When the flag is disabled, Bazel uses the Bash script test wrapper also used on every other platform, from `@bazel_tools//tools/test:test-setup.sh`. This script requires Bash. It has always been the way to run tests with Bazel, so it's battle-tested.

Related bug: https://github.com/bazelbuild/bazel/issues/5508

# Backwards-compatibility

The new test wrapper is designed to be backwards-compatible with the Bash-script based one. We do not expect any incompatibilities.

# Migration recipe

None, as of 2019-03-06.

If you do find that this flag breaks your tests, please let us know so we can find a solution.

# Rollout plan

Bazel 0.24.0 will not support this flag.
Bazel 0.25.0 is expected to support this flag, with default value being false.
Bazel 0.26.0 is expected to flip this flag to true.
Bazel 0.27.0 is expected to remove this flag.

**Comment by laszlocsomor** [comment]
Current status:
- flag is called "incompatible_windows_native_test_wrapper", will be renamed by a PR soon that will reference this issue.
- remaining logic behind the flag will be implemented in the same PR

**Comment by laszlocsomor** [comment]
Current status: updated the bug description and added migration and breaking change labels.

**Comment by laszlocsomor** [comment]
Bazel with downstream projects, with this flag enabled: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/844#77c3bd2d-6828-4949-82f5-f392d0e22cc0

Root causes:
- test trying to launch `.sh` file (bazel-skylib)
- test trying to launch NPM binary that has `.sh` launcher (rules_nodejs, rules_typescript, 
- test trying to launch binary without file extension (rules_foreign_cc, rules_typescript again, rules_sass)
- various errors that need individual triaging (buildtools)

**Comment by laszlocsomor** [comment]
P1 because I really need to resolve this for Bazel 0.27

**Comment by laszlocsomor** [comment]
Last blocker: https://github.com/bazelbuild/rules_foreign_cc/pull/263 -- just needs to get merged, then the project will be fixed. Then I can flip `--incompatible_windows_native_test_wrapper` at HEAD.

The "Bazel / Bazel@HEAD + Downstream" project on BuildKite uses Bazel from HEAD, so that will have both https://github.com/bazelbuild/bazel/issues/8203 and the flipped flag.

Bazel 0.27 will roll out the flipped flag, as well as #8203.

**Comment by laszlocsomor** [comment]
One more blocker: "Bazel integration testing" pipeline
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/979#92dc6232-8e9a-4bd7-b992-57bb9322215b

**Comment by laurentlb** [comment]
The flag was not flipped in 0.27, targeting 1.0?

**Comment by laszlocsomor** [comment]
> The flag was not flipped in 0.27, targeting 1.0?

Looks like it.

**Comment by laszlocsomor** [comment]
Status:
- this is in danger for Bazel 1.0 because some downstream projects on Bazel CI cannot yet use this flag
- I'll try to add `--incompatible_windows_native_test_wrapper` to every downstream project that is ready, and migrate the rest one by one

**Comment by laszlocsomor** [comment]
Blockers:
- [ ] https://github.com/bazelbuild/bazel-integration-testing/issues/148
- [ ] https://github.com/bazelbuild/rules_nodejs/issues/947
- [ ] https://github.com/bazelbuild/rules_typescript/issues/452

**Comment by dslomov** [comment]
What are the ETA for the flag flip?

**Comment by dslomov** [comment]
ping @meteorcloudy

**Comment by meteorcloudy** [comment]
We have one last broken project, fix is here: https://github.com/bazelbuild/rules_typescript/pull/469
I think we can flip this now to catch up the 1.0 cut.

**Comment by dslomov** [comment]
lovely, let's do it.

**Comment by laszlocsomor** [comment]
Thank you 😂
