### ISSUE TITLE
Windows: I/O error while writing action log

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#6624]
### Description of the problem / feature request:

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Unfortunately this bug is spurious.

I was hacking on Bazel and rebuilding a target.
I kept getting the same error on every try:
```
C:\src\bazel>bazel build -c opt //tools/test:tw_test
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
C:\Users\laszlocsomor/.bazelrc
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //tools/test:tw_test (1 packages loaded, 715 targets configured).
INFO: Found 1 target...
INFO: From Compiling tools/test/windows/tw.cc:
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared\minwindef.h(132): warning C4005: 'PASCAL': macro redefinition
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared\lmcons.h(45): note: see previous definition of 'PASCAL'
ERROR: I/O error while writing action log: null during journal append
Target //tools/test:tw_test up-to-date:
  C:/_bazel/o2bbs3hu/execroot/io_bazel/bazel-out/x64_windows-opt/bin/tools/test/tw_test.exe
INFO: Elapsed time: 13.965s, Critical Path: 8.14s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 63 processes: 63 local.
INFO: Build completed successfully, 68 total actions
```

"bazel shutdown" solved the problem.

Possible exception location: https://github.com/bazelbuild/bazel/blob/795bd4869e239a9c900dbd50ed585d94c583a8ac/src/main/java/com/google/devtools/build/lib/util/PersistentMap.java#L209

"null" in the error message probably comes from a null exception message.

Shot in the dark: the file is already opened and the OutputStream is not yet GC'd.

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

```
release 0.19.0
```

**Comment by meisterT** [comment]
Probably stale, closing.
