### ISSUE TITLE
Broken formatting for packaging rules

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#6626]
See [packaging rules docs](https://docs.bazel.build/versions/master/be/pkg.html#pkg_tar).

Formatting is very broken, tables render correctly but headers do not, italics start and stop at various places.
![packaging_rules_formatting](https://user-images.githubusercontent.com/326527/48152495-14fc9400-e292-11e8-8994-1637a0ceb793.png)

**Comment by katre** [comment]
@laurentlb, is this possibly related to ea4840042b0c087685ab4faffab58ba6906b06f5?

**Comment by katre** [comment]
Testing locally, the docs render correctly.

**Comment by katre** [comment]
Actually, no, they just break differently. Still investigating.

**Comment by laurentlb** [comment]
There are two issues, I think.

- The HTML is broken. I'm fixing it. With the fix, page should render correctly when testing locally.
- Syntax highlighting is broken on the site since my update. I suspect we need to update Jekyll or Rouge (cc @philwo).

**Comment by katre** [comment]
Now that 4616fdd0e2f567ae2395803e4404054a79787b22 is in, should I close this, or keep it open and re-assign for the syntax highlighting part?

**Comment by katre** [comment]
Asking @laurentlb whether to keep this open or not.

**Comment by jin** [comment]
Documentation using multi-line code blocks are severely broken (https://docs.bazel.build/versions/master/android-instrumentation-test.html), I will submit a rollback to use redcarpet first.

**Comment by jin** [comment]
The rollback (rollforward?) worked. Closing this for now.
