### ISSUE TITLE
feature request: `values` parameter for attr.string_list

### ISSUE THREAD

**Issue by dgoldstein0** [bazelbuild/bazel#6638]
### Description of the problem / feature request:

`attr.string()` currently supports a `values` parameter giving the valid values for the attribute.  I believe that `attr.string_list()` should have a similar option, to define which values are legal in the given list of strings.

e.g.

```
foo = rule(
  impl = _foo_impl,
  attrs = {
    'my_list': attr.string_list(values=["a", "b", "c"]),
  }
)

# in a BUILD file
foo(
  my_list = ["d", "a", "b"], # error - d isn't a valid value, but a and b are fine
)
```

### Feature requests: what underlying problem are you trying to solve with this feature?

easier validation of rule inputs.  I can hardcode the list of acceptable values into my rule but then it's a little more code and some work to generate a useful error message.

**Comment by laurentlb** [comment]
I agree, this feature would be useful.

**Comment by dws** [comment]
Yes, this would be useful.

**Comment by sambacha** [comment]
@bazelbuild/triage
