### ISSUE TITLE
Can't build Bazel with Intel compiler (3)

### ISSUE THREAD

**Issue by mj-harvey** [bazelbuild/bazel#664]
following on from #663 , worked around by adding a wrapper to icpc.
The build now breaks with:
'''
$ ./compile.sh 
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh build /path/to/bazel
🍃  Building Bazel from scratch............
🍃  Building Bazel with Bazel.
.Extracting Bazel installation...
Sending SIGTERM to previous Bazel server (pid=14589)... done.
........
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
INFO: From Compiling src/main/tools/network-tools.c:
icpc: command line warning #10006: ignoring unknown option '-Wno-free-nonheap-object'
icpc: command line warning #10006: ignoring unknown option '-no-canonical-prefixes'
icpc: command line warning #10006: ignoring unknown option '-Wno-builtin-macro-redefined'
icpc: command line warning #10006: ignoring unknown option '-frandom-seed=bazel-out/local_linux-fastbuild/bin/src/main/tools/_objs/network-tools/src/main/tools/network-tools.pic.o'
icpc: command line warning #10381: option '-std=c99' is not valid for C++ compilations
Warning #2011: predefined meaning of "__DATE__" discarded

Warning #2011: predefined meaning of "**TIMESTAMP**" discarded

Warning #2011: predefined meaning of "**TIME**" discarded

src/main/tools/network-tools.c(15): warning #47: incompatible redefinition of macro "_GNU_SOURCE"
  #define _GNU_SOURCE
          ^

ERROR: /raid-1/apps/bazelbuild/bazel/src/main/tools/BUILD:3:1: undeclared inclusion(s) in rule '//src/main/tools:network-tools':
this rule is missing dependency declarations for the following files included by 'src/main/tools/network-tools.c':
  '/raid-1/apps/intel/2015.3/composer_xe_2015.3.187/compiler/include/stddef.h'
  '/raid-1/apps/intel/2015.3/composer_xe_2015.3.187/compiler/include/stddef.h'
  '/raid-1/apps/intel/2015.3/composer_xe_2015.3.187/compiler/include/stddef.h'
  '/raid-1/apps/intel/2015.3/composer_xe_2015.3.187/compiler/include/stddef.h'
  '/raid-1/apps/intel/2015.3/composer_xe_2015.3.187/compiler/include/stddef.h'
  '/raid-1/apps/intel/2015.3/composer_xe_2015.3.187/compiler/include/stdarg.h'
  '/raid-1/apps/intel/2015.3/composer_xe_2015.3.187/compiler/include/stddef.h'
  '/raid-1/apps/intel/2015.3/composer_xe_2015.3.187/compiler/include/stddef.h'
  '/raid-1/apps/intel/2015.3/composer_xe_2015.3.187/compiler/include/stddef.h'
  '/raid-1/apps/intel/2015.3/composer_xe_2015.3.187/compiler/include/stddef.h'
  '/raid-1/apps/intel/2015.3/composer_xe_2015.3.187/compiler/include/stdbool.h'.
Target //src:bazel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.640s, Critical Path: 0.56s

Building output/bazel
'''

All those files exist.

**Comment by jinhoonbang** [comment]
@mj-harvey hey. I am also trying to build bazel using Intel compilers. I am wondering if you were able to make progress?

**Comment by mj-harvey** [comment]
I used a wrapper shell script that set the license server envvar before
calling the compiler proper.

**Comment by jinhoonbang** [comment]
@mj-harvey we are a research group from university and trying to compile bazel with icc. Is it possible for you to share in detail how you were able to compile? I don't have much knowledge in compilers and it would be great if we can get access to the shell script that you wrote

**Comment by mj-harvey** [comment]
Use  alittle shell script like:

$ cat icc

#!/bin/sh

export LM_LICENSE_FILE=port@license-server

/path/to/the/real-intel-compilers/bin/$(basename $0) "$@"

and ensure that it's in the PATH before the dir with the real compilers.

On 19 May 2016 at 14:24, jinhoonbang <notifications@github.com> wrote:

> @mj-harvey <https://github.com/mj-harvey> we are a research group from
> university and trying to compile bazel with icc. Is it possible for you to
> share in detail how you were able to compile? I don't have much knowledge
> in compilers and it would be great if we can get access to the shell script
> that you wrote
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/bazelbuild/bazel/issues/664#issuecomment-220322616>
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>

**Comment by helenalt** [comment]
@mj-harvey given your suggested workaround, is there still work request for Bazel here? Perhaps documentation?

**Comment by mj-harvey** [comment]
A wrapper completely fixed this for me.
