### ISSUE TITLE
Bazel weirdness with --sysroot when cross-compilling

### ISSUE THREAD

**Issue by djpetti** [bazelbuild/bazel#6653]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

I'm attempting to build a project using a custom ARM toolchain, with a configuration based on the one posted [here](https://github.com/bazelbuild/bazel/wiki/Building-with-a-custom-toolchain).

When I attempt to compile with bazel, I get an error about missing libc.so files:

```
daniel@RainbowDash:~/git/bazel_bug_poc$ bazel build --config arm ...
INFO: Analysed 15 targets (0 packages loaded).
INFO: Found 15 targets...
ERROR: /home/daniel/git/bazel_bug_poc/hello/BUILD:1:1: Linking of rule '//hello:test' failed (Exit 1)
external/arm_gcc_linux_toolchain/arm-linux-gnueabihf/bin/ld: cannot find /lib/libc.so.6
external/arm_gcc_linux_toolchain/arm-linux-gnueabihf/bin/ld: cannot find /usr/lib/libc_nonshared.a
external/arm_gcc_linux_toolchain/arm-linux-gnueabihf/bin/ld: cannot find /lib/ld-linux-armhf.so.3
collect2: error: ld returned 1 exit status
INFO: Elapsed time: 0.472s, Critical Path: 0.23s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```
In my CROSSTOOL, I have been sure to set ```--sysroot``` correctly. What makes me think this is an issue with Bazel is that when I run the build with ```-s```, and then copy and paste the linker command into a shell, it works just fine.

I've created an example [here](https://github.com/djpetti/bazel_sysroot_issue_poc). You need only download it and run ```bazel build --config arm ...``` to experience this behavior.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

release 0.13.0

###  Have you found anything relevant by searching the web?

There is issue #6189, but it seems like the root cause there was something different.

**Comment by benjaminp** [comment]
I suspect your problem is the same as https://stackoverflow.com/questions/52386530/linker-fails-in-sandbox-when-running-through-bazel-but-works-when-sandboxed-comm.

**Comment by djpetti** [comment]
Yeah, that seems like the same issue. I was actually aware about fixing it by manually changing the linker script paths, but that's a kludge and it would be nice to avoid it. Another question is why the example in the Wiki that I linked to above doesn't suffer from this same problem.
