### ISSUE TITLE
Target //src:bazel_nojdk failed to build from brew install on Ubuntu 16.04 

### ISSUE THREAD

**Issue by andrewtvuong** [bazelbuild/bazel#6654]
Hi all, I'm not exactly sure why the brew is failing to install bazel and was hoping yall would have a better idea.

I am trying to use bazel to build from source Tensorflow.

Thanks

### Description of the problem / feature request:

```
brew install bazel
==> Downloading https://github.com/bazelbuild/bazel/releases/download/0.18.1/bazel-0.18.1-dist.zip
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/20773773/b0c2cd
######################################################################## 100.0%
==> ./compile.sh

**ERROR: /tmp/bazel_iiFy8NYR/out/external/bazel_tools/tools/jdk/BUILD:186:1: no such package '@local_jdk//': error globbing [lib/**] - [lib/missioncontrol/**, lib/visualvm/**]: /tmp/bazel_iiFy8NYR/out/external/local_jdk/lib/ssl/private (Not a directory) and referenced by '@bazel_tools//tools/jdk:jdk'
ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted: Analysis failed
INFO: Elapsed time: 7.985s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (234 packages loaded)

ERROR: Could not build Bazel**
```

### Feature requests: what underlying problem are you trying to solve with this feature?

Cannot build with "brew install bazel" on Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-138-generic x86_64)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
brew install bazel
```

### What operating system are you running Bazel on?

Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-138-generic x86_64)

### What's the output of `bazel info release`?

bazel-0.18.1-dist

###  Have you found anything relevant by searching the web?

bazel query uses local_jdk
https://github.com/bazelbuild/bazel/issues/6341

**Comment by andrewtvuong** [comment]
**Latest update:**

$ brew install bazel
==> Downloading https://github.com/bazelbuild/bazel/releases/download/0.18.1/bazel-0.18.1-dist.zip
Target //src:bazel_nojdk failed to build
INFO: Elapsed time: 5.589s, Critical Path: 0.22s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel


$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by irengrig** [comment]
My guess would be the OpenJDk should be used:
from: [Compiling Bazel from source](https://docs.bazel.build/versions/master/install-compile-source.html#bootstrap-bazel):
 sudo apt-get install build-essential openjdk-8-jdk python zip unzip

**Comment by lberki** [comment]
We don't glob in the `@local_jdk` repository anymore and now we use it much less, so I'm optimistically closing this as "not a problem anymore, fixed somewhere on the way". Please report back if it's still a problem!

**Comment by EvanBrownVTM** [comment]
Hi, I have the same issue (building for Raspberry Pi4 Bullseye 32-bit):

ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted: Analysis failed
