### ISSUE TITLE
Java error on AIX

### ISSUE THREAD

**Issue by gkchaudhary** [bazelbuild/bazel#6655]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

bazel is throwing java error on AIX

(0) root @ fcdd: /
# /home/gopesh/bazel-0.18.0/output/bazel
OUTPUT: /home/gopesh/bazel-0.18.0/output/bazel

path = /home/gopesh/bazel-0.18.0/output/bazel
Error: could not find libjava.so
Error: Could not find Java SE Runtime Environment.

(2) root @ fcdd: /
# echo $?
2

libjava.so is already present on the system.

(0) root @ fcdd7: /
# find /usr -name libjava.so
/usr/java8_64/jre/lib/ppc64/libjava.so

Moreover while building the bazel binary using 'compile.sh' script , build is successful and from the log I can see the during the build time it is able to find 'libjava.so' correctly.

for e.g.

bazel-out/ppc-opt/bin/tools/test/LcovMerger/java/com/google/devtools/lcovmerger/all_lcov_merger_tools.runfiles_manifest:30004:local_jdk/jre/lib/ppc64/libjava.so /tmp/bazel_rOm4La3n/out/external/local_jdk/jre/lib/ppc64/libjava.so

So it is quite unclear what is going wrong at the time of binary execution.

Any help would be appreciated !!

Thanks,
Gopesh

> Replace this line with your answer.

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

> Replace this line with your answer.

### What's the output of `bazel info release`?

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by gkchaudhary** [comment]
# /home/gopesh/bazel-0.18.0/output/bazel info release
OUTPUT: /home/gopesh/bazel-0.18.0/output/bazel

path = /home/gopesh/bazel-0.18.0/output/bazel
Starting local Bazel server and connecting to it...
src/main/cpp/blaze_util_posix.cc:308:: No such file or directory
Server crashed during startup. Now printing /.cache/bazel/_bazel_root/d9454a1ad5f5b96f95120d234ce28bd9/server/jvm.out
Error: could not find libjava.so
Error: Could not find Java SE Runtime Environment.

(37) root @ fcdd7: /home/gopesh/bazel-0.18.0/src/main/cpp
# echo $?
37

**Comment by davido** [comment]
Bazel is shipping Linux embedded JDK in its binary, that cannot (obviously) run on AIX.

**Comment by gkchaudhary** [comment]
I have not taken the bazel binary which is compiled on Linux.

I am porting bazel on AIX, hence I compiled bazel using 'compile.sh' script , which is provided as a part of bazel src code.

**Comment by lberki** [comment]
(Why is this a P1?)

Assigning to @iirina -- she's OOO at the moment so it'll take a while before she gets to it.

**Comment by meisterT** [comment]
Can you try setting the `--server_javabase` (see https://docs.bazel.build/versions/master/command-line-reference.html#flag--server_javabase) explicitly?

**Comment by gkchaudhary** [comment]
Tried -server_javabase="/usr/java8_64" default:""
Still getting the same error.
I was checking the commandline file , there I see for java lib path it is taking different directory

-Djava.library.path=/.cache/bazel/_bazel_root/install/b21b92f83c0f65b1f4a9484f9401a08f/_embedded_binaries/

shouldn't it take the the value from LD_LIBRARY_PATH

# echo $LD_LIBRARY_PATH
/usr/java8_64/lib:/usr/java8_64/jre/lib

**Comment by gkchaudhary** [comment]
Closing it as no response.

**Comment by meisterT** [comment]
Closing as this is likely to be stale.
