### ISSUE TITLE
git_repository quiet = false

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#6659]
### Description of the problem / feature request:

When cloning large git repositories there is no input from Bazel which is a bad user experience. Wanted to suggest changing git_repository`s execute to use `quiet = false` and so redirect its output to the user to understand what's going on. Alternatively if the default shouldn't be changed then maybe expose it as another attribute for the user to configure.

 This relates to #1289 

cc @aehlig

**Comment by irengrig** [comment]
@aehlig is that already done with https://github.com/bazelbuild/bazel/issues/6427?

**Comment by aehlig** [comment]
> @aehlig is that already done with #6427?

No, this is a different kind of reporting; #6427 allows rule to report high-level what they're doing; this is a feature request to change the default for `quiet` for the individual `git` commands; this allows to closely follow the output produced by those commands.

**Comment by ittaiz** [comment]
As discussed I'll send a PR for this change (alongside allowing users to
opt out and keep quiet=True)

**Comment by ittaiz** [comment]
Tried fiddling with this now. Getting more info but I'm getting 
```
+ cd /private/var/tmp/_bazel_ittaiz/guid/external
+ rm -rf /private/var/tmp/_bazel_ittaiz/guid/external/org_repo /private/var/tmp/_bazel_ittaiz/guid/external/org_repo
+ git clone git@github.com:org/repo.git /private/var/tmp/_bazel_ittaiz/guid/external/org_repo
Cloning into '/private/var/tmp/_bazel_ittaiz/guid/external/org_repo'...
```
instead of 
```
Cloning into '/private/var/tmp/_bazel_ittaiz/guid/external/org_repo'...
remote: Enumerating objects: 8163, done.
remote: Counting objects: 100% (8163/8163), done.
remote: Compressing objects: 100% (4752/4752), done.
Receiving objects:  100% (8163/8163), xxx KiB | yyy KiB/s
```
When I run the same script in bash.
Any chance one of you has more info about how bazel redirects stdout/stderr?

**Comment by kastiglione** [comment]
I have an open PR to remove the noise #6468. @aehlig can you take a look?

**Comment by ittaiz** [comment]
I'm actually trying to add "noise" in the sense of getting the rule to
output back the regular git output

**Comment by aehlig** [comment]
> Tried fiddling with this now. Getting more info but I'm getting  [...] instead of [...]

As most programs nowadays, `git clone` behaves differently depending on
whether stderr is attached to a terminal or a different file descriptor;
the option to look for is `--progress`.

But given the compaints about bazel being too noisy, opt-in might be the
better choice for this behaviour.


-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by ittaiz** [comment]
Thanks! I’ll try it out :)

Are there such complaints about external repositories? From what I see the
complaints in that area are about Bazel being too silent.
If you’re confident about it I’ll make it opt-in.
Wdyt?

**Comment by jin** [comment]
@aehlig could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?

**Comment by ittaiz** [comment]
We've moved to primarily using http_archive so we don't have this specific need anymore (still think it's valid for existing users though).
