### ISSUE TITLE
External repository reference not overridden by http_archive

### ISSUE THREAD

**Issue by smukherj1** [bazelbuild/bazel#6664]
### Description of the problem / feature request:
Sample reproducible test case at https://github.com/smukherj1/bazel_http_archive_issue
I attempt to use the bazel_skylib repository. This is first loaded by the external repository loader macro call here (https://github.com/smukherj1/bazel_http_archive_issue/blob/master/WORKSPACE#L15) and then loaded using an explicit http_archive call here https://github.com/smukherj1/bazel_http_archive_issue/blob/master/WORKSPACE#L28. The second call uses a version that actually has the file being loaded here (https://github.com/smukherj1/bazel_http_archive_issue/blob/master/BUILD#L2). However, if you try to run "bazel build :bardocs", it will fail with the error
`ERROR: error loading package '': Extension file not found. Unable to load file '@bazel_skylib//:bzl_library.bzl': file doesn't exist or isn't a file`

If you comment out this line (https://github.com/smukherj1/bazel_http_archive_issue/blob/master/WORKSPACE#L25) the error goes away! I have no idea why

### Feature requests: what underlying problem are you trying to solve with this feature?
In my opinion, the second http_archive call should define the external archive available in the build files. When I print out the rule attributes using a macro to print the features of native.existing_rules, I see that the attributes are being overridden. But I'm not sure why the BUILD file doesn't see it and why the error disappears when I comment out the line I mentioned.

Also, does it make sense to display this information via bazel query? It would really help to see via bazel query what the resolved attributes of a external repository is. My macro was something like the following:-
`
def defined_so_far(msg):
    print("Begin ({})".format(msg))
    for target, r in native.existing_rules().items():
        print("Target: {}".format(target))
        for attr, val in r.items():
            if not val:
                continue
            print("\t{} = {}".format(attr, val))
    print("End ({})".format(msg))
`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Clone https://github.com/smukherj1/bazel_http_archive_issue and run bazel build :barlib

### What operating system are you running Bazel on?
gLinux

### What's the output of `bazel info release`?
0.19.1

**Comment by aehlig** [comment]
> If you comment out this line (https://github.com/smukherj1/bazel_http_archive_issue/blob/master/WORKSPACE#L25) the error goes away! I have no idea why

It took me a while to find out what's going on here&mdash;and that it's working as specified. I'm not sure I like this semantics, but I don't know a better one at the moment (not to talk about the transition cost, as users are relying on the current semantics). The minimal reproduction example is the following `WORKSPACE` file in an otherwise empty repository.

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "bazel",
  urls = ["http://bad.example.com/this/does/not/exist/bazel.zip"],
)

# load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository") # unreleated

http_archive(
  name = "bazel",
  urls = ["https://storage.googleapis.com/bazel/0.19.1/release/bazel-0.19.1-dist.zip"],
)
```

With this `WORKSPACE`, a `bazel build @bazel//:LICENSE` succeeds, but if I uncomment the unrelated `load` statement, it fails, complaining about the  bad URL.

The reason is the slightly convoluted semantics of `WORKSPACE` files. Generally, repository rules just write to the global name space. giving a latest-wins semantics. However, the `WORKSPACE` file is split into chunks at each `load` statement, and the existing assignments are frozen at the end of each chunk (so, in total we get the latest definition of that repository in the earliest chunk introducing it). The rational behind this is that a load statement might need files from repositories introduced before it, so the semantics of those repositories has to be frozen at that point in time.

**Comment by smukherj1** [comment]
Thanks for explaining this! Is it currently possible to query the attributes (url, version, etc) of a resolved external repository name using bazel query? If not, does it make sense to add one to debug these situations? 

Ideally, it would be most helpful if we could get some information on which load statement froze the repository resolution or the last executed http_archive location if not yet frozen but that's probably a stretch :)

**Comment by smukherj1** [comment]
@aehlig Notifying to consider my previous comment

**Comment by aehlig** [comment]
> Is it currently possible to query the attributes (url, version,
> etc) of a resolved external repository name using bazel query?

As far as I am aware, `bazel query` does not support asking for those
properties. However, if it is only about debugging, you can use the
`--experimental_repository_resolved_file` option to record which repositories
have actually been fetched. (For the primary use of this option, see
https://blog.bazel.build/2018/09/28/first-class-resolved-file.html
for a blog entry on resolved files.)

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by meteorcloudy** [comment]
@aehlig 
> However, the WORKSPACE file is split into chunks at each load statement, and the existing assignments are frozen at the end of each chunk (so, in total we get the latest definition of that repository in the earliest chunk introducing it).

Is this behavior documented somewhere? I found it very important to figure out which definition of a repository is loaded.

**Comment by keertk** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by fzakaria** [comment]
> @aehlig
> 
> > However, the WORKSPACE file is split into chunks at each load statement, and the existing assignments are frozen at the end of each chunk (so, in total we get the latest definition of that repository in the earliest chunk introducing it).
> 
> Is this behavior documented somewhere? I found it very important to figure out which definition of a repository is loaded.

Just hit the WORKSPACE chunk issue also... what a head scratcher.

**Comment by meteorcloudy** [comment]
@fzakaria WORKSPACE is going to be turned off in Bazel 8 (late 2024) and removed in Bazel 9 (late 2025). Please migrate to Bzlmod so that you no longer have to suffer from this ;)

**Comment by fzakaria** [comment]
I wrote https://fzakaria.com/2024/08/29/bazel-workspace-chunking.html for anyone who wants to learn more about this.

**Comment by meteorcloudy** [comment]
Thanks, there is also an example here: https://github.com/bazelbuild/examples/blob/ac7e3e636facb5502ff9b96634651367f71a777a/bzlmod/05-integrate_third_party_package_manager/WORKSPACE#L42-L45

And I'm really interested in what kind of blockers are you encountering when migrating to Bzlmod?
