### ISSUE TITLE
Bazel 0.19.1 released with a bug 

### ISSUE THREAD

**Issue by nlopezgi** [bazelbuild/bazel#6665]
### Description of the problem / feature request:
Bazel 0.19.1 was released with a bug fixed by https://github.com/bazelbuild/bazel/commit/6bc452874ddff69cbf7f66186238032283f1195f
(https://github.com/bazelbuild/bazel-toolchains/issues/198)

Bazel 0.19.0 does not have that bug.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Use bazel-toolchains repo
Try to run this target:
https://github.com/bazelbuild/bazel-toolchains/blob/master/tests/config/BUILD#L70
modify the value of the bazel_version target to point to 0.19.1
bazel_version = "0.19.1",

Try with version 0.19.0 to see it pass (see https://github.com/bazelbuild/bazel-toolchains/pull/237)

### What operating system are you running Bazel on?

Linux - an ubuntu16_04 docker container

### What's the output of `bazel info release`?

Bazel 0.19.1

@mhlopko fyi as he authored the commit that was not included in the 0.19.1 release

**Comment by ittaiz** [comment]
What are the ramifications? Any build with bazel 0.19.1 and
bazel-toolchains at HEAD fails? Any version of bazel-toolchains fails?

**Comment by nlopezgi** [comment]
There should be no ramifications for remote exec users. This will only impact our internal process to produce a toolchain configs that works with RBE for Bazel 0.19.1 (but the ones for 0.19.0 work well with 0.19.1).

**Comment by lberki** [comment]
(in the absence of @mhlopko )

**Comment by katre** [comment]
This may not be worth a patch, but #6662 definitely is. I am trying today to determine if they are related or not.

**Comment by scentini** [comment]
They are related, the @bazel_tools//tools/cpp:default-toolchain is in error.

**Comment by scentini** [comment]
@katre, do you know when users set --crosstool_top=@bazel_tools//tools/cpp:default-toolchain instead of using the ones generated by cc_configure?

**Comment by katre** [comment]
@scentini I do not know that. Ask the user who reported #6662.

**Comment by katre** [comment]
@nlopezgi Is there a way to run the //tests/config:debian-jessie-custom-bazel-rc-version-autoconfig with a custom local version of Bazel?

**Comment by nlopezgi** [comment]
@katre unfortunately, there is not, these tests depend on downloading an installer, you can repro the error easily though, just try to run a build form an environment in which the same env variables as those set in the docker autoconfig target are set. Specifically, you should be able to repro this by simply adding the env variable:
"CC_TOOLCHAIN_NAME": "linux_gnu_x86"
and then trying to run a build of any target that requires the cc toolchain.
With 0.19.0 the build will succeed, with 0.19.1 the build will fail unless you set
"CC_TOOLCHAIN_NAME": "local" (or remove the env variable)

**Comment by nlopezgi** [comment]
and I do agree with @lberki that if this only impacts our use case it does not warrant a new version being cut (but I'd be surprised no one else is using the CC_TOOLCHAIN_NAME env variable for some other reason)

**Comment by katre** [comment]
Okay, results of testing that (using the [cpp-tutorial](https://github.com/bazelbuild/examples/tree/master/cpp-tutorial/stage3)):

With Bazel 0.19.1:
```
$ CC_TOOLCHAIN_NAME=linux_gnu_x86 bazel build //main:hello-world 
ERROR: Toolchain identifier 'local' was not found, valid identifiers are [stub_armeabi-v7a, linux_gnu_x86, msys_x64_mingw, msvc_x64]
INFO: Elapsed time: 0.593s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
```

With Bazel 0.19.2rc1:
```
$ CC_TOOLCHAIN_NAME=linux_gnu_x86 ~/repos/bazel-release-0.19.1/bazel-bin/src/bazel build //main:hello-world 
Starting local Bazel server and connecting to it...
INFO: Analysed target //main:hello-world (8 packages loaded, 65 targets configured).
INFO: Found 1 target...
Target //main:hello-world up-to-date:
  bazel-bin/main/hello-world
INFO: Elapsed time: 1.759s, Critical Path: 0.01s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

So I will continue with sending out 0.19.2.rc1.

**Comment by wjywbs** [comment]
I'm also encountering an issue similar to this, and related to #6662 as well. I took some time to make a minimal repro in https://github.com/wjywbs/bazel-cc-toolchain-bug.

**Comment by katre** [comment]
I've pushed the cherrypick into the RC, please let me know if there are still issues.

**Comment by gunan** [comment]
This is also affecting TF

**Comment by wjywbs** [comment]
@katre The release-0.19.2 branch works in both of my use cases. Thanks for the fix.

**Comment by katre** [comment]
Closing since 0.19.2 will release today.
