### ISSUE TITLE
Document iteration order for label_keyed_string_dict, string_dict and string_list_dict

### ISSUE THREAD

**Issue by ash2k** [bazelbuild/bazel#6666]
### Description of the problem / feature request:

Currently iteration order of attribute types `label_keyed_string_dict`, `string_dict` and `string_list_dict` is not documented. Would be great to have some info on what is guaranteed and what is not.

### Feature requests: what underlying problem are you trying to solve with this feature?

I have a rule that generates content based on attribute of one of those types. If iteration order is not specified then output may suddenly change. Would be great to document what can be expected from the iteration order. I may need to manually sort items to isolate from any potential changes.

###  Have you found anything relevant by searching the web?

No, except that there is a function to sort lists of comparable items, which is good.

**Comment by laurentlb** [comment]
Iteration order of dictionaries is documented: https://docs.bazel.build/versions/master/skylark/lib/dict.html
I expect it's the same.

**Comment by laurentlb** [comment]
Do you think additional documentation is needed? Where?

**Comment by ash2k** [comment]
I think it would be useful to add a sentence to the [attr](https://docs.bazel.build/versions/master/skylark/lib/attr.html) docs saying that iteration order of the attribute types mentioned above is described on the page you linked.

**Comment by laurentlb** [comment]
The `attr.` objects just pass the dictionary to the implementation function. I don't really see why we should repeat the information about dictionary iteration order (but we can add a link to the `dict` documentation).

Also, I discourage you from relying on a specific iteration order. The point of the `dict` is to provide a mapping from keys to values. It's surprising for an end-user if changing the entries order is meaningful.

**Comment by ash2k** [comment]
> The attr. objects just pass the dictionary to the implementation function. I don't really see why we should repeat the information about dictionary iteration order (but we can add a link to the dict documentation).

I'm suggesting to add a link, nothing else.
