### ISSUE TITLE
cache misses when duplicate identical --test_env values exist

### ISSUE THREAD

**Issue by talya** [bazelbuild/bazel#6667]
### Description of the problem / feature request:

Action cache key calculation differs for multiple identical values of test_env vars

Discovered by using the `--experimental_execution_log_file` flag and then parsing it with `bazel-bin/src/tools/execlog/parser` tool.

### Feature requests: what underlying problem are you trying to solve with this feature?

Running locally and using remote cache hits from RBE.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Run a build. with a duplicated --test_env line.
2. Run an identical build but without the duplication. Use the exceclog/pasrser to see difference. Also witness cache miss.
3. Repeat but with the duplicated --test_env line and witness cache hit.

### What operating system are you running Bazel on?

docker-for-mac

### What's the output of `bazel info release`?

0.19.0

**Comment by irengrig** [comment]
Thank you for reporting the problem!
NB I have the feeling that there is a duplicate for that somewhere, but can not find it.

**Comment by coeuvre** [comment]
Does the issue still happen?

**Comment by fmeum** [comment]
I checked that duplicated `--test_env`s still benefit from action cache hits, but discard the analysis cache. This should be fixed by #18306.
