### ISSUE TITLE
Unable to upgrade bazel

### ISSUE THREAD

**Issue by markorajkovic** [bazelbuild/bazel#6668]
### Description of the problem / feature request:

> The version of Bazel my system shows is 0.13.0 although I installed 0.18.

### Feature requests: what underlying problem are you trying to solve with this feature?

> For building certain tensorflow features I need at least 0.15

### What operating system are you running Bazel on?

> Ubuntu x86_64

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

>I Installed Bazel using binary installer on official page.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

>Not a git repository (or any parent up to mount point /home/staff)

###  Have you found anything relevant by searching the web?

> This question https://github.com/bazelbuild/bazel/issues/5714 is almost the same, but I tried the recommended answers and it doesn't help.

### Any other information, logs, or outputs that you want to share?
_bazel version_

> WARNING: Output base '/home/staff/rajkovic/.cache/bazel/_bazel_rajkovic/d41d8cd98f00b204e9800998ecf8427e' is on NFS. This may lead to surprising failures and undetermined behavior.
Build label: 0.13.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 18 21:33:40 +50297 (1525078013620)
Build timestamp: 1525078013620
Build timestamp as int: 1525078013620

_which bazel_

>usr/bin/bazel

_echo $PATH_

>/home/staff/rajkovic/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/puppetlabs/bin

**Comment by jin** [comment]
Your installer may have installed it into `$HOME/bin`. Could you please check that directory?

**Comment by markorajkovic** [comment]
Yes, it is in that directory. However, there it also shows the old version. I don't understand what I am supposed to do.

**Comment by irengrig** [comment]
Thank you for sharing the results:)
