### ISSUE TITLE
[BUG]Differences betweent external repositores' build target with and local repository target?

### ISSUE THREAD

**Issue by DavinciHW** [bazelbuild/bazel#6677]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

I use tensorflow as my external dependency repository, local_repository, and build my binary depend on some tensorflow build target like @org_tensorflow//tensorflow/core:lib. 
Everything seems normal, but I find that if I compile the same goal in tensorflow's self workspace, 
The generated binaries will be much smaller than the ones I compiled using external dependencies.
For example
```
cc_binary{
  name="mylib.so"
  deps=[
    "@org_tensorfllow//tensorflow/core:lib",
    "@org_tensorfllow//tensorflow/core:core_cpu",
    "@org_tensorfllow//tensorflow/core:all_kernels",
  ]  ,
  linkeshared=True,
}
```
I compiled the above target and got a 160M dynamic library file.
But，if I copy this rule to tensorflow's BUILD file and remove `@org_tensorflow`，like
```
cc_binary{
  name="mylib.so"
  deps=[
    "//tensorflow/core:lib",
    "//tensorflow/core:core_cpu",
    "//tensorflow/core:all_kernels",
  ]  ,
  linkeshared=True,
}
```
The generated .so file will be just 50M.
I think 50M is normal, but I don't know why it makes such a huge difference.

Also，The 160M compiled target detected 1,547 dependencies, but only 1,048 were detected for 50M.

Does bazel make any difference in analyzing the compiled target of the local workspace versus the externally dependent compiled target? This problem has been bothering me for a long time and my project needs to use tensorflow as an external dependency,However, it seems that the results compiled in this way do not meet expectations.

#### os ubuntu16.04

**Comment by DavinciHW** [comment]
Sorry to repeat :lib, three dependencies are :lib :all_kernels: CPU

**Comment by irengrig** [comment]
cc @meteorcloudy @aehlig please help with investigation, afaik it is not so easy to experiment with TF :)

**Comment by DavinciHW** [comment]
I remove all caches and .bazelrc file. 

First Simply run the follwing commans in local tensorflow repository，The following results are obtained:
```bash
bazel build //tensorflow/core:lib
```bash
```
Extracting Bazel installation...
WARNING: detected http_proxy set in env, setting no_proxy for localhost.
Starting local Bazel server and connecting to it...
INFO: Analysed target //tensorflow/core:lib (31 packages loaded).
INFO: Found 1 target...
Target //tensorflow/core:lib up-to-date (nothing to build)
INFO: Elapsed time: 56.170s, Critical Path: 3.80s
INFO: 181 processes: 181 local.
INFO: Build completed successfully, 190 total actions
```
Then I remove all bazel caches again，and run the follwing commans in my repository （which use tensorflow as external repository）,
The following results are obtained:
```bash
bazel build @org_tensorflow//tensorflow/core:lib
```
```
Extracting Bazel installation...
WARNING: detected http_proxy set in env, setting no_proxy for localhost.
Starting local Bazel server and connecting to it...
INFO: Analysed target @org_tensorflow//tensorflow/core:lib (32 packages loaded).
INFO: Found 1 target...
INFO: From Compiling external/snappy/snappy-sinksource.cc:
cc1plus: warning: command line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for C++
cc1plus: warning: unrecognized command line option '-Wno-shift-negative-value'
INFO: From Compiling external/snappy/snappy-stubs-internal.cc:
cc1plus: warning: command line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for C++
cc1plus: warning: unrecognized command line option '-Wno-shift-negative-value'
INFO: From Compiling external/snappy/snappy.cc:
cc1plus: warning: command line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for C++
cc1plus: warning: unrecognized command line option '-Wno-shift-negative-value'
INFO: From ProtoCompile external/org_tensorflow/tensorflow/core/grappler/costs/op_performance_data.pb.cc:
bazel-out/k8-fastbuild/genfiles/external/protobuf_archive/src: warning: directory does not exist.
bazel-out/k8-fastbuild/genfiles/external/protobuf_archive/src: warning: directory does not exist.
INFO: From ProtoCompile external/org_tensorflow/tensorflow/core/example/example.pb.cc:
bazel-out/k8-fastbuild/genfiles/external/protobuf_archive/src: warning: directory does not exist.
Target @org_tensorflow//tensorflow/core:lib up-to-date (nothing to build)
INFO: Elapsed time: 139.948s, Critical Path: 16.03s
INFO: 592 processes: 592 linux-sandbox.
INFO: Build completed successfully, 607 total actions
```

Next, I'd like to Review the dependency graph. Can you give me some advice?

**Comment by DavinciHW** [comment]
@meteorcloudy Thank you for your reply.
Here is my WORKSPACE file
```
local_repository(
	name="org_tensorflow",
	path="../../third_party/tensorflow/tensorflow-1.8.0/tensorflow-1.8.0",
)

# TensorFlow depends on "io_bazel_rules_closure" so we need this here.
# Needs to be kept in sync with the same target in TensorFlow's WORKSPACE file.
http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "6691c58a2cd30a86776dd9bb34898b041e37136f2dc7e24cadaeaf599c95c657",
    strip_prefix = "rules_closure-08039ba8ca59f64248bb3b6ae016460fe9c9914f",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/08039ba8ca59f64248bb3b6ae016460fe9c9914f.tar.gz",
        "https://github.com/bazelbuild/rules_closure/archive/08039ba8ca59f64248bb3b6ae016460fe9c9914f.tar.gz",  # 2018-01-16
    ],
)

load('@org_tensorflow//tensorflow:workspace.bzl', 'tf_workspace')
tf_workspace(path_prefix = "", tf_repo_name = "org_davinci")
```
and BUILD file
```
package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "op_interface.so",
    srcs = [],
    deps = [
        "@org_tensorflow//tensorflow/core:lib",
        "@org_tensorflow//tensorflow/core:core_cpu",
    ],
    linkshared=True,
)
```
and execute command (I have removed all .bazelrc files and bazel cache)
```
bazel build op_interface.so
```
a 50M op_interface.so file was produced.

Then I cd to ../../third_party/tensorflow/tensorflow-1.8.0/tensorflow-1.8.0 and remove all caches，Copy my BUILD file to here and remove "@org_tensorflow", Now tensorflow's BUILD file is:
```
package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "op_interface.so",
    srcs = [],
    deps = [
        "//tensorflow/core:lib",
        "//tensorflow/core:core_cpu",
    ],
    linkshared=True,
)

```
and execute command:
```
bazel build op_interface.so
```
a 39M op_interface.so file was produced.

**Comment by DavinciHW** [comment]
The situation became clear, and I simplified my work the most, remove BUILD file and modified WORKSPACE file to the following：
```
local_repository(
        name="org_tensorflow",
        path="../tensorflow",
)
# TensorFlow depends on "io_bazel_rules_closure" so we need this here.
# Needs to be kept in sync with the same target in TensorFlow's WORKSPACE file.
http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "6691c58a2cd30a86776dd9bb34898b041e37136f2dc7e24cadaeaf599c95c657",
    strip_prefix = "rules_closure-08039ba8ca59f64248bb3b6ae016460fe9c9914f",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/08039ba8ca59f64248bb3b6ae016460fe9c9914f.tar.gz",
        "https://github.com/bazelbuild/rules_closure/archive/08039ba8ca59f64248bb3b6ae016460fe9c9914f.tar.gz",  # 2018-01-16
    ],
)
load('@org_tensorflow//tensorflow:workspace.bzl', 'tf_workspace')
tf_workspace(path_prefix = "", tf_repo_name = "org_davinci")
```

I then modified the BUILD file in the tensorflow source directory （../tensorflow），
```
exports_files(
    [
        "LICENSE",
        "ACKNOWLEDGEMENTS",
    ],
)
#bazel build //tensorflow/contrib/davinci_adpt_2:libtf_kernels.so
#By default, packages of “_impl” are not visible，Here I changed the package visibility in core/framework/BUILD
## 
cc_binary(
    name = "libtf_kernels.so",
    visibility = ["//visibility:public"],
    deps = [
        ":op_interface",
        "//tensorflow/core:framework_internal_impl",
        "//tensorflow/core:lib_internal_impl",
        "//tensorflow/core:core_cpu_impl",
    ],
    linkstatic = True,
    linkshared = True,
)
cc_library(
    name = "op_interface",
    visibility = ["//visibility:public"],
    srcs = glob([],exclude=[]),
    hdrs = glob([],exclude=[]),
    deps = [
        "//tensorflow/core:all_kernels",
        "//tensorflow/core:lib",
        "//tensorflow/core:core_cpu",
    ],
)
```
I tested three scenarios：
- In my workspace dir
```
bazel build @org_tensorflow//:libtf_kernels.so
```
This creates a 700M .so file

- in the tensorflow source directory
```
bazel build //:libtf_kernels.so
```
This creates a 125M .so file

- in the tensorflow source directory
```
bazel build @org_tensorflow//:libtf_kernels.so
```
This also creates a 125M .so file

### Here if I don't add the three "_impl" dependencies and run `bazel build //:libtf_kernels.so` in the source directory of tensorflow, I will fail in the link phase!  But even without the three "_impl" dependencies, I can still compile successfully in my own workspace!

I don't know what the problem is, the compiled source should be the same, so much difference in the link phase?

**Comment by irengrig** [comment]
This may be related to .bazelrc settings, for example, this part: 
`# Modular TF build options
build:dynamic_kernels --define=dynamic_loaded_kernels=true
build:dynamic_kernels --copt=-DAUTOLOAD_DYNAMIC_KERNELS
`
if you run the configuration script for TF (not sure if it runs automatically), then the parts of script from //tools seem to be copied.

So it will be a good idea to check what .bazelrc files you have under TF root and under you project root.

In general, the other part that is different when building from different roots is the WORKSPACE code.
Since we do not have the recursive workspaces, the code from external repositories' WORKSPACE files is not executed.

**Comment by DavinciHW** [comment]
@irengrig Thank you very much, actually, to prevent inconsistencies, I deleted all the.bazelrc files.

**Comment by DavinciHW** [comment]
```
build:dynamic_kernels --copt=-DAUTOLOAD_DYNAMIC_KERNELS
```
A configuration like this seems likely to be the cause of the problem, but is there anything else besides. Bazelrc that can affect build parameters?

**Comment by DavinciHW** [comment]
It does seem like "core:all_kernels" build target causing this problem, because when I compile within the tensorflow source directory and don't rely on "_impl" packages, links will fail.

**Comment by irengrig** [comment]
I have an idea: could you add an intermediate input to your target, for printing the setting about dynamic kernels?
For that, from a custom Starlark rule you can call this function:
`def if_dynamic_kernels(extra_deps, otherwise = []):
    return select({
        str(Label("//tensorflow:dynamic_loaded_kernels")): extra_deps,
        "//conditions:default": otherwise,
    })
`
defined in TF's build_config_root.bzl.

The custom rule can use print() for printing the debugging information and ctx.actions.write() to create some fictive output file. You can create one basing on: https://github.com/bazelbuild/examples/blob/master/rules/actions_write/file.bzl

**Comment by DavinciHW** [comment]
@irengrig Thanks a lot．
I'm currently based on tf1.8.0, where all_kernels always seems to be static and there is no if_dynamic_kernels rule. When I switched to the branch of r1.12, I found if_dynamic_kernels and wrote the following test code:
```python
# tensorflow/workspace.bzl
def _say_impl(ctx):
  print(ctx.attr.name)
say = rule(
    implementation = _say_impl,
)
```
```python
# myworkspace/BUILD
load(
    "@org_tensorflow//tensorflow/core:platform/default/build_config_root.bzl",
    "if_dynamic_kernels",
)
load(
    "@org_tensorflow//tensorflow:workspace.bzl",
    "say",
)
cc_binary(
  name="mylib.so",
  data = if_dynamic_kernels(
        [":is_dynamic"], 
        otherwise = [":not_dynamic"],
    ),
  linkshared=True,
)

say(
  name="is_dynamic",
)
say(
  name="not_dynamic",
)
```
The same target is also added to the tf's BUILD file.
unfortunate, the DEBUG outputs message is the same:  `not_dynamic`.

But I still think it's probably the cause of the problem...

**Comment by DavinciHW** [comment]
Does the rule of if_static have any effect? Do I need to verify it...?
It seems to affect the build results for core:lib
```
cc_library(
    name = "lib_internal",
    srcs = LIB_INTERNAL_PRIVATE_HEADERS,
    hdrs = LIB_INTERNAL_PUBLIC_HEADERS,
    copts = tf_copts(),
    defines = LIB_INTERNAL_DEFINES,
    linkopts = select({
        "//tensorflow:freebsd": [],
        "//tensorflow:windows": [],
        "//tensorflow:windows_msvc": [],
        "//conditions:default": [
            "-ldl",
            "-lpthread",
        ],
    }),
    deps = tf_additional_lib_deps() + [
        "//third_party/eigen3",
        "//tensorflow/core/platform/default/build_config:platformlib",
    ] + if_static([":lib_internal_impl"]),
)
```
