### ISSUE TITLE
Bazel coverage produces incorrect results when run concurrently

### ISSUE THREAD

**Issue by davidrsacks** [bazelbuild/bazel#6678]
### Description of the problem / feature request:

When running `bazel coverage`, it is observed that the coverage generated is inconsistent from run to run. Some files are entirely missing from the overall coverage report, and others show erroneously low coverage. The coverage output is non-deterministic and varies from run to run.

In addition, running `bazel coverage` with `--jobs=1` produces correct coverage data, whereas with the default concurrency, far lower coverage is observed. We also currently use `--instrument_test_targets` and `--strategy=TestRunner=standalone` with `bazel coverage`, though the removal or addition of these flags does not seem to impact the issue.

In looking at the test logs (example test.log snippets below), we see many files are not found when generating coverage data. These match up with the missing coverage we see in the report...

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //my_tests/some_path/test_dir:my_test
-----------------------------------------------------------------------------
+ [[ -z '' ]]
+ echo --
--
+ echo 'Coverage collection running in legacy mode.'
Coverage collection running in legacy mode.
+ echo 'Legacy mode only supports C++ and even then, it'\''s very brittle.'
Legacy mode only supports C++ and even then, it's very brittle.
+ COVERAGE_LEGACY_MODE=1
...
[==========] 2 tests from 1 test case ran. (44 ms total)
[  PASSED  ] 2 tests.
...
+ /usr/bin/lcov -c --no-external --ignore-errors graph -q ...
...
geninfo: WARNING: cannot read my_code#some_folder#some_folder#some_folder#some_file.cc.gcov!
geninfo: WARNING: cannot find an entry for my_code#some_folder#some_folder#some_folder#some_file.cc.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot read my_code#some_folder#some_other_folder#some_other_file.h.gcov!
geninfo: WARNING: cannot find an entry for my_code#some_folder#some_other_folder#some_other_file.h.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry for my_code#some_folder#yet_another_file.h.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry for my_code#some_folder#yet_another_file2.h.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry for my_code#some_folder#yet_another_file3.cc.gcov in .gcno file, skipping file!
```

With `--jobs=1`, no such geninfo errors are produced. The coverage outputted appears to be correct.

We have tried disabling sandboxing with no success. The only way we seem to be able to get reliable coverage data is by running with `--jobs=1`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

bazel coverage ... on a large repository consistently reproduces this.

### What operating system are you running Bazel on?

NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"

### What's the output of `bazel info release`?

release 0.16.1

However, the same behavior has been seen with 0.14.1 and 0.19.1.

###  Have you found anything relevant by searching the web?

I have not found anything relevant in conjunction with "bazel". There are some articles with information on the above error, but none have gotten me anywhere.

**Comment by lberki** [comment]
Looks somewhat similar to #7134 .
