### ISSUE TITLE
Bazel needs 1.8, and asks for 1.7+

### ISSUE THREAD

**Issue by dmaclach** [bazelbuild/bazel#668]
Did a fresh install of my Mac, and got asked to install JDK 1.7+ and then got told I needed 1.8.

------------------

* Run bazel command

Extracting Bazel installation...
Unable to find any JVMs matching version "1.7+".
No Java runtime present, try --request to install.
No output from /usr/libexec/java_home
Unable to find any JVMs matching version "1.7+".
No Java runtime present, try --request to install.
No output from /usr/libexec/java_home

* Install Java 1.7
* Run bazel command again

Java version is 1.7.0_79 while at least 1.8 is needed.
Please set JAVA_HOME.
Java version is 1.7.0_79 while at least 1.8 is needed.
Please set JAVA_HOME.

**Comment by damienmg** [comment]
huh which version are you using?

**Comment by damienmg** [comment]
ping?

**Comment by damienmg** [comment]
@dmaclach can you complete the bug to know which bazel version had that issue?

**Comment by damienmg** [comment]
Closing as I cannot repro it
