### ISSUE TITLE
rule, genrule: Provide option to not segregate src files that are genfiles?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [bazelbuild/bazel#6680]
Per the docs here:
https://docs.bazel.build/versions/master/be/general.html#general-advice

> Do use $(location) extensively, for outputs, tools and sources. Due to the segregation of output files for different configurations, genrules cannot rely on hard-coded and/or absolute paths.

This means that if one `genrule` depends on another `genrule` and is something that may not easily be connected to `$(location ...)` (in our case, it was [xacro](https://github.com/ros/xacro)), because include paths are now split between nominal source files and `genfile` source files.

Can I ask why this path was chosen? Was it performance reason, to minimize the number of symlinks that are being made? Or is there some other reason?

I ask because it's "easy"ish to workaround, by:
* Creating a wrapping macro that calls `native.genrule`, and also generates an intermediate target that has all the necessary sources in its `data` attribute
* Passing this to `genrule(tool = ...)`, and then inside the script, use its source location to find its runfiles, and use those sources, as you would with normal `runfile` scripts.

Aside from the extra lines of code, is there any where that this workaround would break?
If not, would it be possible to make this an option?
Say `genrule(use_runfiles = ...)` and `rule(use_runfiles = ...)`?

**Comment by irengrig** [comment]
cc @laszlocsomor please help

**Comment by laszlocsomor** [comment]
> This means that if one `genrule` depends on another `genrule` and is something that may not easily be connected to `$(location ...)` (in our case, it was [xacro](https://github.com/ros/xacro)), because include paths are now split between nominal source files and `genfile` source files.

Could you elaborate please? When is it not easy to use the outputs of one genrule from another? Could you show an example and point out what is happening vs. what you expect / wish for?

**Comment by EricCousineau-TRI** [comment]
Sorry for the delay!

Ultimately, yes, it was hard to locate outputs of one genrule from the other. Understandable, I could try and use `$(location ...)` for every single file that may be needed, but that doesn't seem to be all to convenient when file generation gets a little more complex (which can be the case for Xacros).

It'd ultimately be nice to hide that detail from the user, especially if it's achievable with a workaround such as this one.

I've posted a dumb file generator and example of (a) not using the workaround and (b) using the workaround to generate files, and file generation may "opaquely" depend on other generated files.

Example workspace:
https://github.com/EricCousineau-TRI/repro/tree/5b1e3212ea59361633087bc7d7c38cb23770959f/bazel/genfile_deps

What the files look like in (a), when it fails to easily locate the output of a prior genrule:
https://github.com/EricCousineau-TRI/repro/blob/5b1e3212ea59361633087bc7d7c38cb23770959f/bazel/genfile_deps/repro.output.txt#L47

What the files look like in (b), where it succeeds:
https://github.com/EricCousineau-TRI/repro/blob/5b1e3212ea59361633087bc7d7c38cb23770959f/bazel/genfile_deps/repro.output.txt#L109

**Comment by laszlocsomor** [comment]
Thanks for the repro!

I'm really sorry but I still can't say with confidence that I understand what's the problem. Is it that you don't know in advance what output files a genrule "gen1" will create, because that depends on the input file of gen1, therefore you can't declare them in gen1's `outs` attribute, therefore you can't easily list them in another genrule "gen2"'s `srcs`, and can't use `$(location <sourcefile>)` in gen2's `cmd`?

If so, that is a common problem and the usual solution is to zip up the output files in gen1, declare the zip file as gen1's output, and unpack it in gen2.

Rough example:
```
genrule(
    name = "gen1",
    outs = ["gen1.zip"],
    tools = ["//some:tool"],
    cmd = "$(location //some:tool) ... --output=./out && zip cf $@ ./out",
)

genrule(
    name = "gen2",
    srcs = ["gen1.zip"],
    tools = ["//other:tool"],
    cmd = "TMP=$$(mktemp -d) && unzip $(location gen1.zip) -d $$TMP && $(location //other:tool) $$TMP/* ...",
)
```

Does that help?

**Comment by serynth** [comment]
@laszlocsomor Assigning you for now since you're working with this - not sure if this qualifies as configurability (it maybe has something to do with output paths?)

**Comment by juliexxia** [comment]
+gregce for output paths

**Comment by EricCousineau-TRI** [comment]
> Thanks for the repro!

> I'm really sorry but I still can't say with confidence that I understand what's the problem. Is it that you don't know in advance what output files a genrule "gen1" will create,

No worries!

But, the issue is not so much that I have an open set of files to generate, but rather that I'd prefer not to care if the input files to a genrule are themselves genrules *or* plain vanilla source files.
Given that the above workaround is functional, I'm not sure why the current genfile folder structure has been chosen for source files (but definitely I understand why you'd like arguments for output files).

My question boils down to: Why is the genfile directory structure so complicated by default, as indicated by the documentation?
If possible, could it be simplified, either optionally or by default?

(This is definitely a kind-of low-priority enhancement request, but I've ran into this a few times and would like to see if it's something that's fixable.)

Thanks!

**Comment by jin** [comment]
@juliexxia could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?

**Comment by EricCousineau-TRI** [comment]
Any chance there's been a related update for this?

I've noticed this section about avoiding `$(location ...)` unless you know what it really is:
https://docs.bazel.build/versions/master/be/make-variables.html#predefined_label_variables
However, it notes that source files will always resolve to the same path, no matter what.

This (still) hurts cases in which I want to use relative paths on the input file to gather additional files, esp. when those files might be produced by `genfiles`.

The workaround I mentioned above still handles it (fiddling with the current directory), or using `@bazel_tools//tools/python/runfiles` to expand locations at runtime.

Thanks!

**Comment by katre** [comment]
I don't think at this point we're going to relax the requirement to use `$(location ...)` to find inputs in genrules. I would like to encourage you to rewrite any complex genrules as actual Starlark rules: you'll find Starlark is much more expressive for handling these sorts of inputs, and you'll have much finer control over the various actions you generate (whereas genrule always creates exactly one action, which is re-run if any of the inputs changes).
