### ISSUE TITLE
Windows: "Failed to query DisplayName of" in Bazel client

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#6685]
### Description of the problem / feature request:

Bazel displays:
```
ERROR: Failed to query DisplayName of HKCU\Software\Microsoft\Windows\CurrentVersion\Uninstall\Free mp3 Wma Converter
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://stackoverflow.com/q/53307267/7778502

Culprit seems to be an unhandled error opening a registry subkey here:
https://github.com/bazelbuild/bazel/blob/cd2a036ffff99087be125253157d16d60289e33a/src/main/cpp/blaze_util_windows.cc#L1359

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

```
Build label: 0.18.0- (@non-git)

Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/bu ild/lib/bazel/BazelServer_deploy.jar

Build time: Sun Oct 28 04:25:08 2018 (1540700708)

Build timestamp: 1540700708

Build timestamp as int: 1540700708
```

**Comment by cnishina** [comment]
I also had this issue with Chrome. I have no idea why this error exists but you could just add in a DisplayName with the registry editor. I went into regedit to: `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome` and added in a new `String Value` and called it "DisplayName". That appears to silence the error.

For the sake of having logs, here's my log output with a similar error message for the DisplayName:

```
D:\src>bazel version
ERROR: Failed to query DisplayName of HKCU\Software\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: ee818f56-b420-4910-a9fe-b54b73650abe
Build label: 0.20.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Nov 30 14:38:51 2018 (1543588731)
Build timestamp: 1543588731
Build timestamp as int: 1543588731

```

**Comment by laszlocsomor** [comment]
Thanks @cnishina ! If I'm not mistaken the error is non-fatal. Is that correct?
I'll fix the code not to show even the error. Bazel should just acknowledge that it can't read some registry key and carry on silently.

(And for the record, that warning about "--batch mode" is also benign, it just indicates that you are not running Bazel from a workspace, i.e. `d:\src` directory has no WORKSPACE file in it, nor do any of its parent directories.)

**Comment by cnishina** [comment]
That is correct, it is not a fatal error. I just commented on how I resolved the registry problem.
