### ISSUE TITLE
//... target pattern includes synthetic targets

### ISSUE THREAD

**Issue by schroederc** [bazelbuild/bazel#669]
Bazel v0.1.2rc2 resolves `//...` to include a bunch of synthetic targets which cause the build to fail due to visibility issues.

For each target in Kythe's repository (i.e. `//kythe/cxx/extractor:lib`), there seems to be a corresponding target nested under the synthetic bazel-kythe package (i.e. `//bazel-kythe/kythe/cxx/extractor:lib`).  This causes visibility issues since some `//kythe/...` targets have strict visibilities that do not include `//bazel-kythe/...` sub-packages.

What are the purpose of these synthetic targets?

**Comment by schroederc** [comment]
It also causes this error:

```
/home/schroederc/kythe/bazel-kythe/external/bazel_tools/tools/jdk/BUILD:119:1: no such package 'third_party/py/gflags': BUILD file not found on package path and referenced by '//bazel-kythe/external/bazel_tools/tools/jdk:proguard_whitelister'.
```

**Comment by zrlk** [comment]
The error you mentioned sounds like a symptom of https://github.com/bazelbuild/bazel/issues/652

**Comment by schroederc** [comment]
This appears to be a duplicate of #594.
