### ISSUE TITLE
--no-as-needed, not -no-as-needed

### ISSUE THREAD

**Issue by Profpatsch** [bazelbuild/bazel#6690]
From `tools/cpp/unix_cc_configure`:

```
…
) + _add_linker_option_if_supported(
    repository_ctx,
    cc,
    "-Wl,-no-as-needed",
    "-no-as-needed",
) + _add_linker_option_if_supported(
…
```

There is no `-no-as-needed` option to `ld`. That translates to `--nmagic --output=-as-needed` if I read the manpage correctly. Gotta love optparse.

@mhlopko, you might want to change this.

**Comment by benjaminp** [comment]
For GNU ld, the manpage states "For options whose names are multiple letters, either one dash or two can precede the option name"...

**Comment by Profpatsch** [comment]
Ok, nice.
