### ISSUE TITLE
Add test that incompatible flags are documented on backward-compatibility.html

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#6691]
According to our incompatible change process, `--incompatible_*` flags are supposed to be documented on the [Backward Compatibility page](https://docs.bazel.build/versions/master/skylark/backward-compatibility.html). Yet there are a dozen or so flags missing from this page (code search for uses of `OptionsMetadataTag.TRIGGERED_BY_ALL_INCOMPATIBLE_CHANGES)`.

We should add an integration test that all such flags are mentioned on the page. We should also do something to ensure the ToC is updated correctly, since IIRC that's a manual process.

Assigning to team-Product since it's backward compatibility, but +@laurentlb too.

**Comment by brandjon** [comment]
Since I'm messing with labels in a bug assigned to another team I suppose I should set untriaged...

**Comment by laurentlb** [comment]
@dslomov wanted to use GitHub bugs as the source of truth. It's not clear whether everything should be documented on that page.

(instead of an integration test, an alternative idea is to generate that page from the source code)

**Comment by brandjon** [comment]
Ooh, I like auto generating. I mean, I hate writing documentation inside java files and especially java strings, but it's better than things getting out of sync as the number of flags we have explodes.

There needs to be a centralized place to see all changes. Worst case scenario that's a `bazel help` invocation of some form. But ideally there's a nice place to go for hand-holding and an estimated timetable for flipping the flag.

If we use Github issues as the SoT, would that be a hotlist?
