### ISSUE TITLE
Incorrect behavior with libc++ and without O2

### ISSUE THREAD

**Issue by mihaimaruseac** [bazelbuild/bazel#6697]
### Description of the problem

I wrongly get undefined symbols when compiling a source file with `bazel build --cxxopt=-O1 --cxxopt=-stdlib=libc++`. Replacing `O1` with `O0` still gets the undefined symbols. Replacing with `O2` or removing the `libc++` gets the correct behavior.

### Bugs: what's the simplest, easiest way to reproduce this bug?

I got to this bug while trying to integrate tensorflow with OSSFuzz. A fast way to reproduce the issue with the full environment is to clone [the PR](https://github.com/google/oss-fuzz/pull/1937), remove the `-O2` lines (currently 35-38) then get into the OSSFuzz environment with `python infra/helper.py shell tensorflow` and finish by running the following 3 commands in that environment:

```
$ bazel clean --expunge
$ bazel build --cxxopt=-O1 --cxxopt=-stdlib=libc++ //tensorflow/stream_executor:stream_executor_impl
$ nm -C ./bazel-bin/tensorflow/stream_executor/_objs/stream_executor_impl/rng.o | grep SeedBytes
```

The expected result should be no lines in the `grep` command (see below).

#### Alternative reproduction instructions

The simplest way to reproduce would be to clone [tensorflow](https://github.com/tensorflow/tensorflow) and then run the following:

```
$ bazel clean --expunge
$ bazel build --cxxopt=-O1 --cxxopt=-stdlib=libc++ //tensorflow/stream_executor:stream_executor_impl
$ nm -C ./bazel-bin/tensorflow/stream_executor/_objs/stream_executor_impl/rng.o | grep SeedBytes
```

Since [the header file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/rng.h) defines the `kMinSeedBytes` and `kMaxSeedBytes` they shouldn't show up in the `nm ... | grep ...` command above in a correct compile. Replace `-O1` with `-O2` or remove the `libc++` flag to get to the correct compilation.

### What operating system are you running Bazel on?

```
root@71bb4d6dbfb7:/src/tensorflow# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
root@71bb4d6dbfb7:/src/tensorflow# uname -a
Linux 71bb4d6dbfb7 4.17.0-3rodete2-amd64 #1 SMP Debian 4.17.17-1rodete2 (2018-08-28) x86_64 x86_64 x86_64 GNU/Linux
```

### What's the output of `bazel info release`?

```
root@71bb4d6dbfb7:/src/tensorflow# bazel info release
release 0.19.1
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
root@71bb4d6dbfb7:/src/tensorflow# git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
https://github.com/tensorflow/tensorflow
495a3a3dd3ca24fa1c93da28420322ed66844791
495a3a3dd3ca24fa1c93da28420322ed66844791
```

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

The Google version of TF doesn't have this issue as the logging codepath is different. This bug started being visibile after I [made changes to disable logging in fuzzing mode](https://github.com/tensorflow/tensorflow/commit/0773b244a01e738459354b2697352feb04646c21). So, I assume that the symbols are optimized away/not pulled in except when compiling with `-O2` (which is strange to be honest).

I think this is most likely a bazel bug, not a clang, OSSFuzz or tensorflow one, that's why I'm raising this here.

**Comment by jin** [comment]
@scentini could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?

**Comment by mihaimaruseac** [comment]
We can drop as TF no longer exhibits the issue
