### ISSUE TITLE
--build_event_json_file does not produce valid JSON

### ISSUE THREAD

**Issue by Ubehebe** [bazelbuild/bazel#6704]
### Description of the problem / feature request:

[--build_event_json_file](https://docs.bazel.build/versions/master/command-line-reference.html#flag--build_event_json_file) does not produce valid JSON. The JSON spec requires one top-level value, but the file written by Bazel appears to contain one top-level [BuildEvent proto]( https://github.com/bazelbuild/bazel/blob/1f684e1b87cd8881a0a4b33e86ba66743e32d674/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto#L640) per line. As a result, parsing the file with something like [JsonFormat.Parser](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/util/JsonFormat.Parser.html) fails with an InvalidProtocolBufferException.

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm trying to parse the output of --build_event_json_file.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`bazel build //some:target --build_event_json_file=/path/to/json`, then inspect /path/to/json.

### What operating system are you running Bazel on?

MacOS and Linux.

### What's the output of `bazel info release`?

release 0.19.0

### Any other information, logs, or outputs that you want to share?

This has an easy workaround, which is to split the file into lines and parse each one as a BuildEvent JSON proto. This is more of a documentation/API issue: the flag --build_event_json_file sounds like it produces valid JSON. It's surprising when it doesn't.

I believe the fundamental issue is that protos have no concept of "delimited" JSON reading/writing, as they do with the binary serialization (e.g. [parseDelimitedFrom](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Parser#parseDelimitedFrom-java.io.InputStream-)). As a workaround, Bazel could output an array of BuildEvent protos. This would be a single top-level value, but would require a dummy "BuildEvents" proto to be defined.

In any case, the documentation for the flag should specify the format of what it produces. Currently, it says only "write a JSON serialisation of the build event protocol to that file", which is misleading.

**Comment by ashi009** [comment]
This is not invalid. It's to allow processing the events as a stream.

https://en.wikipedia.org/wiki/JSON_streaming

**Comment by michaeledgar** [comment]
@ashi009 is correct about the intent behind BEP's JSON output: all output formats are intended to be consumed in a streaming fashion. This is also true of the output produced by `--build_event_text_file`, which contains a sequence of [BuildEvent messages as defined in build_event_stream.proto](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto#L903).
