### ISSUE TITLE
0.19.2 crosstool incompatibility

### ISSUE THREAD

**Issue by schroederc** [bazelbuild/bazel#6707]
### Description of the problem / feature request:

https://github.com/kythe/kythe build breaks with Bazel 0.19.2 after working with 0.19.0 and 0.19.1.
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ git clone https://github.com/kythe/kythe.git
$ cd kythe
$ bazel-0.19.1 build //kythe/go/util/kytheuri
INFO: Build completed successfully, 238 total actions
$ bazel-0.19.2 build //kythe/go/util/kytheuri
ERROR: Toolchain identifier '%{cc_toolchain_identifier}' is illegal (does not match '[a-zA-Z_][\.\- \w]*')
INFO: Elapsed time: 0.358s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded)
```

### What's the output of `bazel info release`?

`release 0.19.2`

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
git@github.com:schroederc/kythe.git
5f5187348c218b948caf46b7a74fc528ccf0630e
5f5187348c218b948caf46b7a74fc528ccf0630e
```

###  Have you found anything relevant by searching the web?

The release notes mention two commits that are "not expected to break anybody": https://github.com/bazelbuild/bazel/releases/tag/0.19.2

**Comment by katre** [comment]
Taking a look, thanks for the report.

**Comment by katre** [comment]
This relates to the release in #6116.

**Comment by schroederc** [comment]
This looks to be the correct fix on our side: https://github.com/kythe/kythe/pull/3265

**Comment by katre** [comment]
Yes, local_config_cc contains the literal text `%cc_toolchain_identifier`.
```
cc_toolchain(
    name = "cc-compiler-k8",
    toolchain_identifier = "%{cc_toolchain_identifier}",
    all_files = ":compiler_deps",
    compiler_files = ":compiler_deps",
    cpu = "k8",
    dwp_files = ":empty",
    dynamic_runtime_libs = [":empty"],
    linker_files = ":compiler_deps",
    objcopy_files = ":empty",
    static_runtime_libs = [":empty"],
    strip_files = ":empty",
    supports_param_files = 1,
)
```

Trying to backtrack to why it isn't replaced properly by the autoconfiguration.

**Comment by katre** [comment]
That's interesting, `@local_config_cc//:cc-compiler-k8` in my local bazel repository has toolchain_identifier = "local", as expected, but from kythe it has "%{cc_toolchain_identifier}". I'm not sure why they are different.

**Comment by katre** [comment]
Oh, I see, you have you own override of the cc autoconfiguration? In the future, when we change that, how can we avoid causing problems for you?

**Comment by katre** [comment]
I am making this not a blocker for the 0.19 release, since this is specific to your version of the cc autoconfiguration, and assigning it to the CC rules team to figure out the right way forward.

**Comment by schroederc** [comment]
I believe the context to our fork is in https://github.com/bazelbuild/bazel/issues/2121

**Comment by mhlopko** [comment]
I believe there's nothing to be done here, please shout if I'm wrong. Thanks!
