### ISSUE TITLE
Bazel prints bogus warning when using --nohome_rc

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#6709]
### Description of the problem / feature request:

When using `bazel --nohome_rc build //my:target`, Bazel prints the following bogus warning:

```
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/home/philwo/.bazelrc
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See above.

### What operating system are you running Bazel on?

Arch Linux.

### What's the output of `bazel info release`?

I'm running Bazel HEAD.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

bazel build //src:bazel

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git@github.com:bazelbuild/bazel.git
46de62ced353bc5d490126464b75fd13799c543c
46de62ced353bc5d490126464b75fd13799c543c

**Comment by laszlocsomor** [comment]
I can still repro with Bazel 0.28.1 on Linux.

**Comment by laszlocsomor** [comment]
Same bug with `--nosystem_rc` and with `--noworkspace_rc` (provided `<workspace>/.bazelrc` exists).

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
