### ISSUE TITLE
Allow specifying .bazelignore through flags

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/bazel#6712]
### Description of the feature request:

Allow specifying the .bazelignore file to use, or allow setting the ignored directories through flags.

### Feature requests: what underlying problem are you trying to solve with this feature?

We used to use `bazel test -- //... -//experimental/...` during CI tests, which would break the test in case a build file in `//experimental` is malformatted. 

After adding `experimental` to `.bazelignore` this is no longer an issue for CI tests, but it renders developers who work in `experimental` impossible to build with bazel.

As the `.bazelignore` is defined in workspace scope, and there is no flag for overriding it, so there is no way to change the settings without modifying `.bazelignore`, and it's also impossible to make such change in our CI environment as the source code is in a read-only mount (which is also unpreferable).

Therefore, I'm proposing two solutions:

- add a flag to specify the `.bazelignore` file to use like `--bazelrc`.
- add a flag to specify the ignored directories, so that we can put them in the .bazelrc file

### What's the output of `bazel info release`?

```
$ bazel info release
release 0.19.1
```

**Comment by dslomov** [comment]
Well, the idea is that `experimental` is either a part of the workspace or it is not. I do not think we want to support the usecase of people checking in malformated BUILD files.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
