### ISSUE TITLE
Bazel CI: rules_apple is failing in downstream

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#6716]
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/602#994c7b9d-1e7d-4f60-b72c-6efa92867f01

Based on the [culprit finder](https://github.com/bazelbuild/bazel/commit/828b1fb23958fca29a0631c8583d5e8b777f7c53), the culprit should be 3bf685794b8568042c91d789e612af34fc3c485f

**Comment by meteorcloudy** [comment]
FYI @sergiocampama @benjaminp

**Comment by buchgr** [comment]
fixed by @benjaminp thank you!
