### ISSUE TITLE
Support of [no] addition of --remote_http_cache build option

### ISSUE THREAD

**Issue by lisaonduty** [bazelbuild/bazel#6719]
### Description of the problem / feature request:

We request a [no] addition to the --remote_http_cache build option so it will be: 
--[no]remote_http_cache

### Feature requests: what underlying problem are you trying to solve with this feature?

We have the remote caching on by default for our users (including the CI machinery). To be able to build without the remote server we have been adding an own no-remote option in a Python-wrapper of the Bazel command. We don't want own options as a long term alternative.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

0.18.0

**Comment by lisaonduty** [comment]
Hi,
If I try that (for example on Bazel's own C++ tutorial Hello World) it crashes. I've tried various ways to give an empty value: 
--remote_http_cache=""
--remote_http_cache=
--remote_http_cache=\0
--remote_http_cache=NULL
--remote_http_cache
But non of the above works.
All of them gives:
java.lang.RuntimeException: java.lang.NullPointerException
BR
Lisa

**Comment by dslomov** [comment]
Sounds like suggestion in https://github.com/bazelbuild/bazel/issues/6719#issuecomment-442005976 didn't work.

**Comment by perwestling** [comment]
Plan to have a look at this bug. Let me know if anyone else is doing that as well.

**Comment by perwestling** [comment]
I have now made a pullrequest that makes it possible to use --remote_http_cache= as described above.
https://github.com/bazelbuild/bazel/pull/7650

**Comment by ishikhman** [comment]
--remote_cache= should do the trick, as mentioned above.
Please, feel free to reopen the issue if it is still a problem.
