### ISSUE TITLE
Publicly support the compilation_prerequisites_INTERNAL_ output_group

### ISSUE THREAD

**Issue by det** [bazelbuild/bazel#6721]
### Description of the problem / feature request:

Make the `compilation_prerequisites_INTERNAL_` output group a publicly supported API.

### Feature requests: what underlying problem are you trying to solve with this feature?

For tools that depend on `compilation_commands.json` to work without compiling the whole tree. For example, your source code may depend on generated protobuf headers or symlinks for virtual include folders that will not exist before performing a build. Thankfully, it seems that bazel already has the ability to build the minimum set of things needed for the compilation environment to be correct by using the `compilation_prerequisites_INTERNAL_` output_group.  There is even a comment in the bazel source code which indicates that this flag exists to support tools like IDEs. However, the `_INTERNAL_` suffix seems to indicate that this group is not meant for users and I would be hesitant to depend on its existence.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`bazel build --output_groups=compilation_prerequisites_INTERNAL_ //...`

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 0.18.1

###  Have you found anything relevant by searching the web?

No.

**Comment by lberki** [comment]
What's `compile_commands.json`? How is it generated? What is it used by?
 
I'd be reluctant to document that output group because, well, it's an implementation detail. Not knowing more about the use case, I can't really come up with a reasonable alternative.

**Comment by SashaOv** [comment]
Hi @lberki , please take a look at https://clang.llvm.org/docs/JSONCompilationDatabase.html and https://github.com/grailbio/bazel-compilation-database. 

`compilation_database.json` is a very important feature, it helps IDEs to parse the code correctly and enables features like IntelliSense which accelerate coding dramatically.

Please consider making this into a supported feature. I am sure a lot of people would than you for that.
