### ISSUE TITLE
Generate and publish documentation for Starlark rules in @bazel_tools

### ISSUE THREAD

**Issue by moruowait** [bazelbuild/bazel#6730]
[patches attribute](https://github.com/bazelbuild/bazel/commit/7831d8c9be23d419a64dfbc48e09fa175e1f1536) for http_archive (and other rules) is not documented on https://docs.bazel.build/versions/master/be/workspace.html#http_archive.

Please update the BUILD Encyclopedia.

**Comment by c-parsons** [comment]
What do you mean by "generate documentation from repository rules" ?

1. Stardoc can generate documentation for rules which depend on other repositories (for example, Stardoc can generate documentation for `//foo/bar.bzl` even if it depends on `@baz//:other.bzl`)
2. Stardoc can generate documentation for rules across repository bounds. For example, you can generate documentation for `@bazel_tools//:foo.bzl` with no problem)
3. Stardoc **does not** yet generate documentation for invocations of `repository_rule()`, though I suspect it could be fairly easily extended to do so. It currently only handles user-defined functions, `rule()` invocations, and `provider()` invocations.

**Comment by dslomov** [comment]
On Mon, Nov 26, 2018 at 6:30 PM c-parsons <notifications@github.com> wrote:

> What do you mean by "generate documentation from repository rules" ?
>
>    1. Stardoc can generate documentation for rules which depend on other
>    repositories (for example, Stardoc can generate documentation for
>    //foo/bar.bzl even if it depends on @baz//:other.bzl)
>    2. Stardoc can generate documentation for rules across repository
>    bounds. For example, you can generate documentation for
>    @bazel_tools//:foo.bzl with no problem)
>    3. Stardoc *does not* yet generate documentation for invocations of
>    repository_rule(), though I suspect it could be fairly easily extended
>    to do so. It currently only handles user-defined functions, rule()
>    invocations, and provider() invocations.
>
>
Item 3 is what I meant (http.bzl defines repository rules that need to be
documented)

-- 
Google Germany GmbH
*Erika-Mann-Straße 33, 80636 München, Germany*
