### ISSUE TITLE
Bazel CI: downstream projects are broken by flipping --incompatible_package_name_is_a_function

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#6736]
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/606#0d48853a-552a-4d49-9b70-eeafe39cbe28
```
The value 'REPOSITORY_NAME' has been removed in favor of 'repository_name()', please use the latter 
```

What's the migration plan for `--incompatible_package_name_is_a_function`? Is there are migration window for this flag?

@laurentlb

**Comment by laurentlb** [comment]
Projects have been updated
