### ISSUE TITLE
test_filter should not cause the analysis cache to be discard

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#6737]
### Description of the problem / feature request:

Currently when one runs tests in intellij and then uses the command line or even just runs two different test cases (!) the analysis cache is discarded. 
This can add between 1-2 seconds to 10-15 seconds on various flows we've seen internally.
Should the test_filter argument cause Bazel to discard the analysis cache?

### Feature requests: what underlying problem are you trying to solve with this feature?

Get more performance

###  Have you found anything relevant by searching the web?

#6548 sounds related

cc @brendandouglas

**Comment by benjaminp** [comment]
Just pass `--trim_test_configuration`.

**Comment by ittaiz** [comment]
Thanks! I’ll take a look.
Still sounds to me the FR is valid and that it’s unclear why test_filter causes the above effect.

**Comment by ittaiz** [comment]
Tested it and it does solve this specific problem but I'm not sure if it doesn't introduce a new issue.

**Comment by ittaiz** [comment]
Btw, I think also test_output=streamed (probably any value) also causes the analysis cache to be discarded...

**Comment by gregestren** [comment]
Assigning to @serynth, the awesome author of `--trim_test_configuration` for triage.

**Comment by serynth** [comment]
`--trim_test_configuration` is the intended solution to this. Eventually it will become the default - it's not ready for that yet - but this is the problem it was created to solve! :)

Test options like `--test_filter` are used in the process of analyzing test targets to determine the command line of the test action itself. Unfortunately, this means that when they change, we need to discard the analysis cache and re-analyze. `--trim_test_configuration` limits this re-analysis to only test targets which actually use those test options to determine their command lines.

As far as `--test_output` goes - `--test_output` itself is not part of analysis, but changing between `--test_output=streamed` and another value of `--test_output` changes the value of `--test_sharding_strategy` (it's set to `disabled` by `--test_output=streamed`, but defaults to `explicit`). That option is used by test targets to determine what their test actions should look like, so it causes the analysis cache to be discarded if you haven't already set it to `disabled` - but it's also one of the options which `--trim_test_configuration` trims.

So, in sum: Use `--trim_test_configuration`. It will avoid discarding the analysis cache in all of the cases described in this issue! :)

**Comment by ittaiz** [comment]
Thanks! Is there a tracking issue for when this will become the default?
Would like to follow it

**Comment by ittaiz** [comment]
@serynth ping?

**Comment by serynth** [comment]
Sorry for the silence! :) I've created #6842 for tracking this!
