### ISSUE TITLE
Latest homebrew version does not match latest released version

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#6743]
### Description of the problem / feature request:

As I file this issue, the latest OS X release of Bazel is 0.19.2. The latest version available on [Homebrew](https://formulae.brew.sh/formula/bazel) is 0.18.1. Something is amiss, as I'd expected homebrew updates to be in step with published releases.

### What operating system are you running Bazel on?

OS X, Mojave

### What's the output of `bazel info release`?

`release 0.18.1-homebrew`

**Comment by jin** [comment]
Bazel has moved to using its own Homebrew tap:  https://github.com/bazelbuild/homebrew-tap/blob/master/README.md

**Comment by shs96c** [comment]
Is there some way to remove the version in homebrew itself? Or become the equivalent of choco's "trusted package"? It's confusing for users for this difference to exist, even if (it turns out) it's documented on the bazel site: who reads docs? :)

**Comment by dslomov** [comment]
If I remember correctly, it is up to homebrew folks to remove their formula (their formula is not officially supported by us) and they didn't do it (cc @buchgr to check whether I misrepresent).

**Comment by shs96c** [comment]
I've filed https://github.com/Homebrew/homebrew-core/issues/34404 to try and get this resolved.
