### ISSUE TITLE
ERROR: No toolchain found for cpu 's390x'.

### ISSUE THREAD

**Issue by Maronee** [bazelbuild/bazel#6749]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

While building bazel with bazel on linux for s390x an error occurs, here the full log:

🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
.WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/tmp/bazel_5jaZV3Oe/archive/libblaze.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
ERROR: No toolchain found for cpu 's390x'. Valid cpus from default_toolchain entries are: [
]. Valid toolchains are: [
  stub_armeabi-v7a: --cpu='armeabi-v7a' --compiler='compiler',
  local: --cpu='piii' --compiler='compiler',
  msys_x64_mingw: --cpu='x64_windows' --compiler='mingw-gcc',
  msvc_x64: --cpu='x64_windows' --compiler='msvc-cl',
]
INFO: Elapsed time: 5,206s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (3 packages loaded)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Here are the commands I used:

curl -L https://github.com/bazelbuild/bazel/releases/download/0.19.2/bazel-0.19.2-dist.zip -o bzl.zip 
unzip bzl.zip
bash compile.sh

### What operating system are you running Bazel on?

LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

### What's the output of `bazel info release`?

I can't run a bazel command due to the build aborting, but it is the version 0.19.2

### Any other information, logs, or outputs that you want to share?

I was able to build bazel a couple of weeks ago in version 0.19.0

**Comment by nlopezgi** [comment]
probably related to https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#disallow-using-crosstool-to-select-the-cc_toolchain-label

**Comment by dslomov** [comment]
OS/390 port is not supported by Bazel team, but patches welcome.
