### ISSUE TITLE
Bazel doesn't cache old artifacts for --config builds

### ISSUE THREAD

**Issue by kayasoze** [bazelbuild/bazel#675]
I've decided to implement ASan support by including the following in my .bazelrc:

```
build:asan --define ASAN=true
build:asan --strip=never
build:asan --copt -fsanitize=address
build:asan --copt -O1
build:asan --copt -fno-omit-frame-pointer
build:asan --linkopt -fsanitize=address
```

(the --define ASAN is for use by CMake-built dependencies that also have dependencies on Bazel-built libraries)

If I should alternate between
- `bazel build ...`
- `bazel build --config asan ...`
- `bazel build ...`

... my original build artifacts are not cached; they are instead rebuilt.  Unfortunately, I cannot build ASAN into the dbg configuration in `CROSSTOOL`, as it has false positives in certain environments and thus cannot be enabled for dbg unconditionally.  Is there a suggested best practice here?  Can one define a fourth compilation mode in `CROSSTOOL`?

**Comment by ulfjack** [comment]
No, you can't define additional modes. You can, however, use a copy of the existing toolchain but with a different value for the 'compiler', and bazel should put the output into a different output directory (you also have to set --compiler=<new value> in the config.

**Comment by bsilver8192** [comment]
[--platform_suffix](http://bazel.io/docs/bazel-user-manual.html#flag--platform_suffix) is perfect for this. My tools/bazel.rc has `build:asan --platform_suffix=-asan`, and Bazel does a good job with the caching.

**Comment by kayasoze** [comment]
Perfect!  I would never have found `--platform_suffix`.  Thanks!

**Comment by kayasoze** [comment]
This works swimmingly, with one exception: genrule dependencies.  Because genrule action arguments may change depending on --config, but they aren't saved uniquely via `--platform_suffix`, they are always rebuilt when `--config` changes.  See https://github.com/bazelbuild/bazel/issues/679.
