### ISSUE TITLE
jar stamping of external repositories is broken

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#6752]
### Description of the problem / feature request:

When one uses `java_common.stamp_jar` in a target of an external repository (for example `scala_import_external` which uses `scala_import`) bazel fails:
```
Output artifact 'external/io_bazel_rules_scala_scalactic/scalactic_2.11-3.0.5-stamped.jar' not under package directory 'external/io_bazel_rules_scala/scala/scalatest' for target '@io_bazel_rules_scala//scala/scalatest:scalatest'
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a custom jvm "import" rule which doesn't use ijar and call java_common.stamp_jar in it.
Create a repository rule which writes a BUILD file using the above rule.
Have a target in your workspace depend on the above and see the failure.
@anchlovi,
Do you think you can generate a branch of rules_scala which fails like above? 

### What's the output of `bazel info release`?

0.19.2

@lberki @iirina I don't know how easy/hard it will be to fix this but if it's easy and can get in to 0.21 that would be great. We want to try and push forward the move to JavaInfo and the usage of stamp_jar.
Usage of stamp_jar will allow to align rules_scala with rules_java with respect to strict-deps labels and possibly performance (a lot of depset (mis?)handling going on right now)

**Comment by lberki** [comment]
I don't think so -- @iirina is coming back next week which is already after the official cutoff date. Sorry :(

**Comment by ittaiz** [comment]
@iirina any thoughts?

**Comment by iirina** [comment]
Hi Ittai,

I tried to reproduce it but wasn't successful. I think I've lost you at the repository rule that creates the BUILD file. Can you sketch where that fits in with the layout of the repro? This is what I have right now:

```
external_repo_dir
  a.jar        <------- jar that will get stamped
  jvm_import.bzl  <---- jvm_import rule that only stamps the jar and returns a JavaInfo
  BUILD     <---------- defines jvm_import(my_jar)
  WORKSPACE <---- empty
current_repo_dir
  B.java <-- has a dependency on a.jar
  BUILD <-- defines java_library(java_lib, srcs = B.java, deps = ["@external_scala//:my_jar"])
```

And I build `:java_lib` in `current_repo_dir`.

In your example, is the original jar that was stamped under `external/io_bazel_rules_scala_scalactic`?

**Comment by ittaiz** [comment]
Hi @iirina
I definitely dropped the ball here because it was unclear if/when we'll move to stamping jars but now it looks closer and still it doesn't work.
You can see this [commit](https://github.com/bazelbuild/rules_scala/commit/a76792b99bc4470819340051973007adb6f9e49a) in rules_scala which just adds stamping to scala_import and the [buildkite failure](https://buildkite.com/bazel/rules-scala-scala/builds/1478):
```
(09:17:03) ERROR: /workdir/test/src/main/scala/scalarules/test/scala_import/BUILD:5:1: in scala_import rule //test/src/main/scala/scalarules/test/scala_import:guava_and_commons_lang:
--
  | Traceback (most recent call last):
  | File "/workdir/test/src/main/scala/scalarules/test/scala_import/BUILD", line 5
  | scala_import(name = 'guava_and_commons_lang')
  | File "/workdir/scala/scala_import.bzl", line 15, in _scala_import_impl
  | java_common.stamp_jar(<4 more arguments>)
  | the output artifact 'external/com_google_guava_guava_21_0_with_file/guava-21.0-stamped.jar' is not under package directory 'test/src/main/scala/scalarules/test/scala_import' for target '//test/src/main/scala/scalarules/test/scala_import:guava_and_commons_lang'
  | (09:17:03) ERROR: /workdir/test/src/main/scala/scalarules/test/scala_import/BUILD:13:1: in scala_import rule //test/src/main/scala/scalarules/test/scala_import:jffi_native_external:
  | Traceback (most recent call last):
  | File "/workdir/test/src/main/scala/scalarules/test/scala_import/BUILD", line 13
  | scala_import(name = 'jffi_native_external')
  | File "/workdir/scala/scala_import.bzl", line 15, in _scala_import_impl
  | java_common.stamp_jar(<4 more arguments>)
  | the output artifact 'external/com_github_jnr_jffi_native/jffi-1.2.17-native-stamped-stamped.jar' is not under package directory 'test/src/main/scala/scalarules/test/scala_import' for target '//test/src/main/scala/scalarules/test/scala_import:jffi_native_external'
```

**Comment by ittaiz** [comment]
@iirina do you think you'll be able to help here?

**Comment by ittaiz** [comment]
@lberki @dslomov do you think someone will be able to work on it? Label collection instead of stamping is one of the older tech debts we have at rules_scala and it would be really nice to drop it (and get perf improvements along the way)

**Comment by ittaiz** [comment]
@iirina any chance you'll be able to take a look?

**Comment by ittaiz** [comment]
Hey,
My current direction (in a few weeks when I'll have a breath) is to duplicate the code that does jar stamping into rules_scala and move off of `java_common.stamp_jar`.
I'd really rather not do it but I'd like to move off of label collection and I can't do this until I can stamp external jars.

**Comment by ittaiz** [comment]
@lberki any thoughts? Can this be contributed?

**Comment by ittaiz** [comment]
@lberki wdyt?

**Comment by Jamie5** [comment]
@ittaiz just to clarify, what is desired to be contributed? Making it possible to stamp a jar even when the source jar is not in the same directory as the stamped jar (which would IIRC be a relatively trivial change), or something bigger?

**Comment by ittaiz** [comment]
I don’t know :) I didn’t dive into the implementation like you did so I’ll refer to the API.
I want to be able to call stamp_jar on jars which come from external workspace without failing (and obviously having correct labels inside).

Also- why are you referring to the source jar? You mean origin (as opposed to sources)?

**Comment by Jamie5** [comment]
I haven't tested it (haven't really done any work in bazel core or even have it set up) but in https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/java/JavaInfoBuildHelper.java#L382 it seems like for `actions.declareFile(basename, inputJar);` instead of passing `inputJar` as sibling, we can just pass `Starlark.NONE`, which will cause the file to be made relative to the rule directory (based on https://github.com/bazelbuild/bazel/blob/2c185d1d5d18e21cde9ddf9b65685606bce02c38/src/main/java/com/google/devtools/build/lib/analysis/skylark/StarlarkActionFactory.java#L118 ).

However I have not at all tested this and it is only a theory, and even if this works it is possible that something else would then break.

Hmm yes I think I mean origin jar, as opposed to `.srcjar` source jars.

**Comment by ittaiz** [comment]
@lberki @dslomov @aiuto do you think you can find someone to review a small PR for this issue? Sounds like @Jamie5 is interested but it’s probably only worthwhile if it will be merged

**Comment by Jamie5** [comment]
Though, this may also break any existing users if they did want the stamped jar to be created in the same place as the original jar, and the original jar was within the current package subtree. So might need slight api adjustments (maybe we would instead have an optional argument to specify the output directory and/or name?)

**Comment by ulfjack** [comment]
@ittaiz, let's get this fixed. ;-)

**Comment by ittaiz** [comment]
@ulfjack do you think there's a way to move this forward?
