### ISSUE TITLE
Add @bazel_tools//tools/jdk:javadoc

### ISSUE THREAD

**Issue by ronshapiro** [bazelbuild/bazel#6757]
### Description of the problem / feature request:
`@bazel_tools//tools/jdk` replaces `@local_jdk//` for many things, but there's no equivalent for `@local_jdk//:bin/javadoc`

### Feature requests: what underlying problem are you trying to solve with this feature?

I'd like to update the `javadoc_library` in github.com/google/bazel-common to a version of Bazel that supports Bazel's move away from `@local_jdk`

### What's the output of `bazel info release`?

release 0.19.2

**Comment by davido** [comment]
What worked for our javadoc bazlets is: [1].

```
"%s/bin/javadoc" % ctx.attr._jdk[java_common.JavaRuntimeInfo].java_home
```

* [1] https://github.com/GerritCodeReview/bazlets/commit/13330934a0e577d60719551ffb746f64b0bb9637#diff-8d08250422c583ac3fd666c6492092be
