### ISSUE TITLE
incompatible_merge_genfiles_directory: unify bazel-bin and bazel-genfiles directories

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#6761]
We plan to unify the `bazel-bin` and `bazel-genfiles` directories.

This means that `bazel-genfiles` will point to the same location as `bazel-bin`, since the distinction was not meaningful. This will allow us to make simplifications in Bazel and its API.

See discussion: https://groups.google.com/d/msg/bazel-dev/5iq7n1soenA/xGM_M1NOCAAJ

**Comment by laurentlb** [comment]
Still blocked by Protobuf (https://github.com/protocolbuffers/protobuf/issues/5691).

**Comment by meteorcloudy** [comment]
@laurentlb FYI, Bazelisk + Incompatible flags couldn't catch this breakage. Because building with this flag seems have an impact on subsequent builds.
See https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/18#d6d93bbf-ca8a-432f-bd99-23d93577ede5
Unless we do a `bazel clean` between the incompatible flags and no incompatible flags build, we still get the same error message.

**Comment by jin** [comment]
This will cause all of these scripts / code that assume existence of `bazel-genfiles`, right? https://github.com/search?q=bazel-genfiles&type=Code

**Comment by laurentlb** [comment]
When testing downstream projects, we noticed very few issues. But it's true that it tests only within Bazel. Scripts that call Bazel and then look at the specific directory might break.

Not sure what we can do, apart from advertising the change more loudly.
(at least, it shows why this should be done before Bazel 1.0)

**Comment by laurentlb** [comment]
Projects that rely on `bazel-genfiles` can:
 - Specify the flag `--incompatible_merge_genfiles_directory=false`. This flag will be available for a long time (even after Bazel 1.0), to give users more time to migrate.
 - Create a symlink: `ln -s bazel-bin bazel-genfiles`

**Comment by jin** [comment]
> When testing downstream projects, we noticed very few issues. But it's true that it tests only within Bazel. Scripts that call Bazel and then look at the specific directory might break.

The symlinks are, in a way, the only user facing filesystem level API that Bazel exposes. I also have no idea what else we can do. The Downstream pipeline has no visibility into the bazel-external build infra of our users :(

> advertising the change more loudly. (at least, it shows why this should be done before Bazel 1.0)

Completely agree.
