### ISSUE TITLE
incompatible_expand_directories: Args Directory Support

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#6762]
The `--incompatible_expand_directories` flag will automatically expand directories in command lines. Design doc: https://docs.google.com/document/d/11agWFiOUiz2htBLj6swPTob5z78TrCxm8DQE4uJLOwM

**Comment by philwo** [comment]
I verified that this flag was flipped and thus will be included in the Bazel 0.23.0 release.
