### ISSUE TITLE
WARNING: failed to raise resource limit: Invalid argument on macOS

### ISSUE THREAD

**Issue by guw** [bazelbuild/bazel#6776]
### Description of the problem / feature request:
```
$ bazel version
WARNING: failed to raise resource limit 8 to 32768: Invalid argument
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Build label: 0.19.2
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Nov 19 16:24:08 2018 (1542644648)
Build timestamp: 1542644648
Build timestamp as int: 1542644648
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I installed Bazel for the first time on macOS 10.14.1. Bazel was never installed on the system before. I followed the [installation guide for Homebrew](https://docs.bazel.build/versions/master/install-os-x.html).

```
brew tap bazelbuild/tap
brew tap-pin bazelbuild/tap
brew install bazelbuild/tap/bazel
```

### What operating system are you running Bazel on?

macOS 10.14.1

### What's the output of `bazel info release`?

```
$ bazel info release
WARNING: failed to raise resource limit 8 to 32768: Invalid argument
ERROR: The 'info' command is only supported from within a workspace.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
```

Looks like it's producing the same warning message. I don't have a Bazel project yet.

**Comment by rupertks** [comment]
+ jmmv in case he has seen this before

**Comment by jmmv** [comment]
Nope, never seen that warning before (but I wrote that code :P). Resource limit 8 corresponds to `RLIMIT_NOFILE`. Can you share what the output of the following are on the same console you are running Bazel?

```
$ ulimit -S -n
$ ulimit -H -n
$ sysctl kern.maxfilesperproc
```

Thanks.

**Comment by guw** [comment]
```
$ ulimit -S -n
20960
$ ulimit -H -n
32768
$ sysctl kern.maxfilesperproc
kern.maxfilesperproc: 20960

```

**Comment by jmmv** [comment]
I see. So here is the problem:

1. Bazel tries to set the soft limit (20960) to the hard limit (32768) at startup time. On macOS, the hard limit cannot be higher than the kernel-configured limit (20960).
1. Now, Bazel has provisions to deal with the case where the hard limit is set to "unlimited", in which case it will cap the setting to the kernel limit to avoid the error you are seeing.
1. But... Bazel has no provisions to deal with the case where the hard limit is *already* larger than the kernel limit, in which case it should behave the same way as if the limit was "unlimited" (i.e. cap at kernel limit).

We should fix the latter... but I have to wonder how it is even possible to set a higher ulimit than what the kernel allows...
