### ISSUE TITLE
Remove gcc assumptions from param files for linking

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#6788]
### Problem 1

LinkCommandLine parses the command line and removes `-Wl,` prefix. Flags without the prefix are then written to the params file, and the param file is passed to the compiler as `-Wl,@param.file` (which skips the compiler handling and is passed verbatim to the linker).

Instead, we should not massage the flags, and pass the param file directly to the compiler as `@param.file`.

### Problem 2

LinkCommandLine parses linkopts and moves -l flags (telling the linker to link against the library) to a different place on the command line than the rest of the linkopts. Because of this, we cannot currently link without the param file, and we hardcode specific gcc flags that we will reshuffle.

This reshuffling shouldn’t happen, and we should be able to link without params files, or by putting whole command line to params file (depending on the command line length).

### Result

These two issues, when fixed, will allow us to unify the commandlines with how Starlark does it: [Unification of Bazel lazy action args](https://docs.google.com/document/d/11DDjHQfCY3I1kO7w0PusjCoaqmZUQQajd42HDS0F3dI/edit#heading=h.1yalups59kdz)

**Comment by oquenchil** [comment]
Fixed after #7687 was flipped
