### ISSUE TITLE
Deprivilege stdc-predef.h

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#6789]
stdc-predef.h is unconditionally included to every compilation if present in sysroot. We can remove it and migrate users to the CROSSTOOL and cc_toolchain.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
