### ISSUE TITLE
genrules re-executed unnecessarily even with --platform_suffix

### ISSUE THREAD

**Issue by kayasoze** [bazelbuild/bazel#679]
If a `--config` flag should result in a change to a genrule() action, the genrule will be rebuilt unnecessarily even if `--platform_suffix` is used within the `--config` options.  In other words, the state necessary for genrule build avoidance is not saved uniquely according to `--platform_suffix`.  This sequence of actions will always rebuild genrule dependencies, for example:

```
bazel build foo
bazel build --config asan foo (changes a genrule action for a dependency of foo)
bazel build foo <- genrule() dependencies rebuilt
```

**Comment by ulfjack** [comment]
We may print that the action is re-executed even if it's a cache hit. Can you confirm that the action is actually executed? Maybe add a sleep 30 to the genrule and confirm that the third build actually takes 30s.

**Comment by kayasoze** [comment]
Good point, but I build with -s and can see all of the genrule build steps, which are quite spammy.

My genrule looks like this:

```
# For CMake and Autotools-based genrule builds
config_setting(
  name = "asan",
  values = {"define": "ASAN=true"},
)

ASAN_FLAGS = select({
  "//asan": "-fsanitize=address",
  "//conditions:default": ""
})

genrule(
  ...
  cmd = "..." +
        "-Dasan_flags:STRING='" + ASAN_FLAGS + "' " + 
        "..."
)
```

Is it possible that select() is not correctly cacheable outside of a Bazel rule?

**Comment by ulfjack** [comment]
Even if it's printed with -s, it can still be a cache hit. The cache is at a lower level than printing the output. :-/

**Comment by kayasoze** [comment]
That's an impressive level of caching.  

In this case, the rebuild takes more than 60 seconds, and I can see the compiler processes dutifully rebuilding the dependencies' compilation units using `pgrep`.

**Comment by kayasoze** [comment]
Note that I have been noticing some build corruptions since I've begun using `--platform_suffix`.  They disappear after `bazel clean`, so there is a slim chance that artifacts from platform `foo` and `foo-suffix` are being commingled, but I don't have any solid evidence to present.

**Comment by bsilver8192** [comment]
I can't reproduce this. Have you confirmed that it still fails for you with something this simplified?

**Comment by kayasoze** [comment]
Here's the simplified repro.  It needs a genrule which uses a host-built tool.  I think the issue is that my --config affects both host and target configurations, but --platform_suffix does not affect the host artifact cache, so host tools cannot be cached and are rebuilt.  Once the tools are rebuilt, all genrules which reference those tools are rebuilt, dependencies of those are rebuilt, and so on.  I don't need --config asan to affect host tools, so I can work around that by splitting my genrules into host and target variants.

### Setup

```
cat .bazelrc
build --package_path %workspace%:%workspace%/bazel
fetch --package_path %workspace%:%workspace%/bazel
query --package_path %workspace%:%workspace%/bazel

# Containerized builds currently break Autotools-based builds:
build --spawn_strategy=standalone --genrule_strategy=standalone

# Use our own toolchain by default:
build --crosstool_top=//config:toolchain

build:asan --define ASAN=true
build:asan --strip=never
build:asan --copt -fsanitize=address
build:asan --copt -O1
build:asan --copt -fno-omit-frame-pointer
build:asan --linkopt -fsanitize=address
build:asan --platform_suffix=-asan
```

```
$ cat config/BUILD
...
# For CMake and Autotools-based genrule builds
config_setting(
  name = "asan",
  values = {"define": "ASAN=true"},
)
...
```

```
$ cat gen-dep/BUILD
ASAN_FLAGS = select({
  "//config:asan": "-fsanitize=address",
  "//conditions:default": ""
})

genrule(
  name = "build-foo",
  srcs = ["foo.c"],
  outs = ["bar.h"],
  cmd = "cd $(GENDIR)/%s && " % PACKAGE_NAME +
        "date && echo 'const char* foo = \"" + ASAN_FLAGS + "\";\n' > bar.h",
  visibility = ["//visibility:public"],
)

cc_library(
  name = "foo",
  srcs = ["bar.h"],
  hdrs = ["bar.h"],
  visibility = ["//visibility:public"],
  includes = ["."],
)
```

`$ cat gen-dep/foo.c [empty]`

```
$ cat parent-genrule/BUILD
genrule(
  name = "blah",
  srcs = ["main.c"],
  outs = ["main.out"],
  cmd = "cd $(GENDIR)/%s && " % PACKAGE_NAME +
        "date && echo $(location //gen-dep:bar.h) > main.out",
  tools = ["//gen-dep:bar.h"],
)
```

```
$ cat parent-genrule/main.c
#include "bar.h"

int main(void) {
  return (int)foo;
}
```

### Output

Here, we build without asan, then with asan, then without asan again.

```
$ cd parent-genrule
~/w/parent-genrule $ bazel build -c dbg -s ...
INFO: Found 1 target...
Target //parent-genrule:blah up-to-date:
  bazel-genfiles/parent-genrule/main.out
INFO: Elapsed time: 2.228s, Critical Path: 0.00s

~/w/parent-genrule $ bazel build -c dbg -s --config asan ...
INFO: Found 1 target...
>>>>> # //gen-dep:build-foo [action 'Executing genrule //gen-dep:build-foo [for host]']
(cd <redacted> && \
  exec env - \
    PATH=/usr/local/bin:/usr/local/sbin:/home/<redacted> \
    TMPDIR=<redacted> \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; cd bazel-out/host/genfiles/gen-dep && date && echo '\''const char* foo = "-fsanitize=address";
'\'' > bar.h')
INFO: From Executing genrule //gen-dep:build-foo [for host]:
Fri Dec  4 19:25:01 PST 2015
Target //parent-genrule:blah up-to-date:
  bazel-genfiles/parent-genrule/main.out
INFO: Elapsed time: 0.469s, Critical Path: 0.01s

~/w/parent-genrule $ bazel build -c dbg -s ...
INFO: Found 1 target...
>>>>> # //gen-dep:build-foo [action 'Executing genrule //gen-dep:build-foo [for host]']
(cd <redacted> && \
  exec env - \
    PATH=/usr/local/bin:/usr/local/sbin:<redacted> \
    TMPDIR=<redacted> \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; cd bazel-out/host/genfiles/gen-dep && date && echo '\''const char* foo = "";
'\'' > bar.h')
INFO: From Executing genrule //gen-dep:build-foo [for host]:
Fri Dec  4 19:25:03 PST 2015
Target //parent-genrule:blah up-to-date:
  bazel-genfiles/parent-genrule/main.out
INFO: Elapsed time: 0.492s, Critical Path: 0.00s
```

**Comment by bsilver8192** [comment]
I've fought that issue many times too... I solve this particular instance of the problem (detecting asan) using a `config_setting(values = {'copts': '-fsanitize=address'})`, which avoids triggering for host rules.

**Comment by kayasoze** [comment]
Perfect--thanks!  This resolves the issue for me.  Closing.

**Comment by ulfjack** [comment]
Requiring bazel clean is a serious concern. Also, using date in a genrule
makes the output non-deterministic. If the host binaries are
non-deterministic, that explains why you don't get cache hits for the
target binaries.
