### ISSUE TITLE
incompatible_make_thinlto_command_lines_standalone: Make ThinLTO actions fully configured in the CcToolchainInfo

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#6791]
**Flag:** `--incompatible_make_thinlto_command_lines_standalone`
**Available since:** 0.26
**Will be flipped in:** 1.0

### Motivation

Before this flag, `lto-indexing` action reuses flags from plain C++ linking actions. `lto-backend` uses `GCC` tool from [`tool_paths`](https://docs.bazel.build/versions/master/skylark/lib/cc_common.html#create_cc_toolchain_config_info), not action configs as it should. Because of this it's unnecessary hard to configure C++ toolchain that supports ThinLTO. Once this flag is flipped, we'll document how to configure C++ toolchain for ThinLTO, and add support for ThinLTO into Bazel's autoconfigured toolchain as part of https://github.com/bazelbuild/bazel/issues/6926.

### Migration

If your toolchain doesn't support ThinLTO you don't have to do anything. In case it does:

1) You have to define action configs for these actions:
    * `lto-backend`
    * `lto-index-for-executable`
    * `lto-index-for-dynamic-library`
    * `lto-index-for-nodeps-dynamic-library`
2) You have to mention these actions in all flag sets that you want to be expanded for lto.
3) Once this flag is flipped, you can remove mentions of `lto-indexing` in your toolchain, it will no longer be used by Bazel.

**Comment by mhlopko** [comment]
While at it, let's document thinlto features, and make Bazel crosstools support thinlto.

**Comment by dslomov** [comment]
This P1 bazel 1.0 issue is unassigned. Please assign cc @lberki
