### ISSUE TITLE
Implement toolchain libraries

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#6792]
Implement toolchain libraries as designed in https://docs.google.com/document/d/1w3nYuuzAeWSmv5UiPrxNE5sHJfsw1t2ywJp1v6HEndg/edit.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
