### ISSUE TITLE
Documentation about legacy C++ toolchain

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#6794]
1. On https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#disable-legacy-c-toolchain-api, there are references to `find_cpp_toolchain` and `find_cc_toolchain`. I expect one of them is a typo.

2. Migration doc asks me to use `find_cpp_toolchain`, but it's not documented (https://docs.bazel.build/search.html?q=find_cpp_toolchain).

3. Migration docs talk about `ctx.fragments.cpp`, but not `ctx.host_fragments.cpp`. How do I migrate my call to `ctx.host_fragments.cpp`?

**Comment by mhlopko** [comment]
I have a cl in flight for 1) and 3).

For 2, how should would you document it? It's a tiny Starlark file with one function. I wouldn't put it into bazel.build. What I would do is to have a page about how to write rules that integrate with C++ rules. SGTY?

**Comment by laurentlb** [comment]
Sounds good.

**Comment by jin** [comment]
@scentini could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?

**Comment by hlopko** [comment]
We now have https://docs.bazel.build/versions/master/integrating-with-rules-cc.html. Therefore closing this issue. Thank you all!
