### ISSUE TITLE
Add filtering options to aquery

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel#6795]
### Description of the problem / feature request:

aquery does allow you to inspect the actions, relationships between artifacts and actions and action command lines. It's currently not easy to specify any filters, however users are e.g. interested in the action that generated a specific output file.

Add various filter options, e.g. inputs/outputs/mnemonics.

**Comment by joeleba** [comment]
TODO:
- [ ] inputs function
- [ ] outputs function
- [ ] mnemonics function
- [ ] Combination with existing functions

**Comment by joeleba** [comment]
Closing this issue. #6930 will add more documentation/user guides regarding these new functions.
