### ISSUE TITLE
disabling skylint checks with a comment

### ISSUE THREAD

**Issue by bbarnes52** [bazelbuild/bazel#6796]
I cannot use skylint and write custom rules because rules are defined as global variables in .bzl files and generate a "no-effect" lint error. I would like to be able to disable this warning on a case-by-case basis, e.g. I would like to use the "no-effect" check in general, but disable it in specific instances, by annotating expressions with something like #skylint: disable-check=no-effect

**Comment by laurentlb** [comment]
We're moving away from skylint, it will be replaced with https://github.com/bazelbuild/buildtools

As such, it's unlikely we work on this and I'm going to close this issue.
