### ISSUE TITLE
--test_output=streamed does not relay remote execution error messages

### ISSUE THREAD

**Issue by sethkoehler** [bazelbuild/bazel#6798]
### Description of the problem / feature request:

Error messages issues by a remote execution server should be displayed when --test_output=streamed is used, just as they are when the flag is not used.

### Feature requests: what underlying problem are you trying to solve with this feature?

Use of test_output=streamed is confusing when the user has incorrectly specified something, but doesn't see an error message indicating this.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Requires use of Google cloud's remote execution service (i.e., you'll need to fill in a few values in the .bazelrc), and then defining something that will cause the server to generate an error (e.g., a platform that defines a bad property).  For example, with the attached project (which consists solely of a run.sh file that echoes a line of text, as well as WORKSPACE/BUILD/.bazelrc configuration), running "bazel test --test_output=streamed ..." gives two errors complaining that test.log can't be found (no such file or directory), whereas without the test_output flag, I get the proper INVALID_ARGUMENT error that the server returns.

### What operating system are you running Bazel on?

Debian Linux

### What's the output of `bazel info release`?

release 0.19.2

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

fatal: not a git repository (or any parent up to mount point /usr/local)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

###  Have you found anything relevant by searching the web?

I found https://github.com/bazelbuild/bazel/issues/4178, though I'm not sure if it's related or not.

### Any other information, logs, or outputs that you want to share?

[test-output-streamed-github.zip](https://github.com/bazelbuild/bazel/files/2626876/test-output-streamed-github.zip)

**Comment by buchgr** [comment]
--test_output=streamed limits the parallelism to 1. I believe internally test_output=streamed disables remote execution, but I think it's reasonable to support it in Bazel because the host platform might not be compatible with the remote execution platform.

**Comment by sethkoehler** [comment]
Yep, limit of parallelism to 1 makes sense.  However, just to note, I'm not seeing this option disable remote execution...I have an sh_test example that is definitely running remotely (via printout of username in that script...interestingly, hostname weirdly prints out something that doesn't match either my workstation nor the remote bot...it prints a 12-char hex string like "ccc5bcfcf3b3", and this seems to be randomized, but that behavior is seen regardless of whether this option is enabled or not).

**Comment by buchgr** [comment]
> I'm not seeing this option disable remote execution

Thanks so'll we need to implement this code path separately in Bazel :(.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
