### ISSUE TITLE
cp: cannot stat '/apollo/bazel-apollo/bazel-out/local-opt/bin/modules/perception/cuda_util/libintegrated_cuda_util.so': No such file or directory

### ISSUE THREAD

**Issue by purewater0901** [bazelbuild/bazel#6800]
When I executed followed command the above error occured while I try to install and run apollo in my computrer.

bash apollo.sh release

OS Ubuntu18.04LTS
GPU nvidia GeForce 1080Ti

**Comment by iirina** [comment]
There aren't many details on this error. Please check with the apollo team first. If they confirm it's a bazel bug, please provide more context.
