### ISSUE TITLE
Get rid of tools/build_rules/test_rules.bzl

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#6804]
If the code is useful, it can be moved to skylib.

**Comment by jin** [comment]
@laurentlb could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?

**Comment by c-parsons** [comment]
I would assess P3. Feel free to change if you disagree.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
