### ISSUE TITLE
Bazel 0.9.0 sorts keys of `attr.label_keyed_string_dict` implicity

### ISSUE THREAD

**Issue by basavaraj29** [bazelbuild/bazel#6809]
### Description of the problem / feature request:

We are currently running Bazel 0.9.0. We've defined a custom Bazel rule. In one of the fields, we are using a `attr.label_keyed_string_dict`. While processing the keys during evaluation phase, the keys are being sorted implicitly. Is there any flag/option using which we can disable this feature. I've checked version 0.14 in which the keys aren't sorted implicitly. But I wanted to know if there is anything we can do within version 0.9.0

### Feature requests: what underlying problem are you trying to solve with this feature?

Need the ordering to generate a file during execution phase

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Define a custom bazel rule with one field as `attr.label_keyed_string_dict`. Include a few key value pairs in the target, and print the key-value pairs in the skylark rule. You can see that it prints in sorted order when you run `bazel build :target`

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 0.9.0

### Have you found anything relevant by searching the web?

No

**Comment by laurentlb** [comment]
Hi!
Sorry, we don't maintain older versions of Bazel. I'd recommend you to upgrade to the newest version.

If you have trouble upgrading, please file a new bug for that.
Thanks!
