### ISSUE TITLE
Adding a leading / to build_file in WORKSPACE causes error with no hint

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#681]
If I add:
```
new_http_archive(
    name = "scala",
    strip_prefix = "scala-2.11.7",
    sha256 = "ffe4196f13ee98a66cf54baffb0940d29432b2bd820bd0781a8316eec22926d0",
    url = "http://downloads.typesafe.com/scala/2.11.7/scala-2.11.7.tgz",
    build_file = "/tools/build_defs/scala/scala.BUILD",
)
```
Note the "/tools...". I get: `ERROR: Loading failed; build aborted.` with no explanation of what went wrong.

If that is changed to `build_file = "tools/build_defs/scala/scala.BUILD"`, without a leading `/` everything works.

**Comment by damienmg** [comment]
FWIW, I think we should use label for this argument also because it will break horribly when we start loading workspace rules from external repository

**Comment by kchodorow** [comment]
+1 on the labels vs. paths, but not really related to this issue (new_http_archive isn't catching and exception it should be).  I've filed #682 to track the label thing.

**Comment by kchodorow** [comment]
I think this might have been fixed in the interim, if I build `@scala//...`, I get:

```
ERROR: In new_http_archive rule //external:scala the 'build_file' attribute does not specify an existing file (/tools/build_defs/scala/scala.BUILD does not exist).
INFO: Elapsed time: 0.076s
```
