### ISSUE TITLE
Bazel Build fails to find local_config_cc for gRPC

### ISSUE THREAD

**Issue by JonMcDevitt** [bazelbuild/bazel#6813]
### Description of the problem / feature request:

When calling `bazel build :all`, cannot find package '@local_config_cc'. Currently I am unsure whether this is a gRPC issue or whether this is an issue stemming from the Chocolatey installation of bazel.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Following the instructions in [their build document][1], clone the gRPC repository (master branch).
2. Follow the instructions for [getting Bazel for Windows][2] using Chocolatey.
3. Follow the instructions for [building C++ on Windows][3].
4. From the [gRPC build instructions][1], follow the instructions for building with bazel.

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
d:\perforce\jmcdevitt_development\apps\testapp\thirdparty\grpc/.bazelrc
d:\perforce\jmcdevitt_development\apps\testapp\thirdparty\grpc/tools/bazel.rc
release 0.19.2

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Not applicable.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git remote get-url origin - https://github.com/grpc/grpc
git rev-parse master - b88dfc227cd8c9ceeb7797b3265905a93880a077
git rev-parse HEAD - b88dfc227cd8c9ceeb7797b3265905a93880a077

###  Have you found anything relevant by searching the web?

I have tried a variety of google searches, but none of the results seem to be working as workarounds. In particular, [issue 3063][4] seemed promising, but it is closed, and could specifically be XCode related.

#### My bazel environment variables:

BAZEL_SH=C:\Windows\System32\bash.exe
BAZEL_VC=D:\dev\VisualStudio\VisualStudioPro2015\VC
BAZEL_VS=D:\dev\VisualStudio\VisualStudioPro2015

#### "Stack Trace"

```txt
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
d:\perforce\jmcdevitt_development\apps\testapp\thirdparty\grpc/.bazelrc
d:\perforce\jmcdevitt_development\apps\testapp\thirdparty\grpc/tools/bazel.rc
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/users/jmcdevitt/_bazel_jmcdevitt/zxkq2hgi/external/bazel_tools/tools/cpp/cc_configure.bzl", line 51
                configure_windows_toolchain(repository_ctx)
        File "C:/users/jmcdevitt/_bazel_jmcdevitt/zxkq2hgi/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 342, in configure_windows_toolchain
                repository_ctx.template("CROSSTOOL", paths["@bazel_tools//..."], ...}": ""})
        File "C:/users/jmcdevitt/_bazel_jmcdevitt/zxkq2hgi/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 359, in repository_ctx.template
                _get_escaped_windows_msys_crosstool_content(repository_ctx)
        File "C:/users/jmcdevitt/_bazel_jmcdevitt/zxkq2hgi/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 41, in _get_escaped_windows_msys_crosstool_content
                auto_configure_fail(("Could not determine MSYS/Cygwi...))
        File "C:/users/jmcdevitt/_bazel_jmcdevitt/zxkq2hgi/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 109, in auto_configure_fail
                fail(("\n%sAuto-Configuration Error:%...))

Auto-Configuration Error: Could not determine MSYS/Cygwin root from BAZEL_SH (c:/windows/system32/bash.exe)
INFO: Elapsed time: 0.950s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

### References

1. [gRPC Build Instructions][1]
2. [Bazel Installation Instructions (Windows)][2]
3. [Using Bazel on Windows][3]
4. [Bazel 0.5.0 build fails on Mac OS X El Capitan][4]

[1]: https://github.com/grpc/grpc/blob/v1.16.0/BUILDING.md
[2]: https://docs.bazel.build/versions/master/install-windows.html
[3]: https://docs.bazel.build/versions/master/windows.html
[4]: https://github.com/bazelbuild/bazel/issues/3063

**Comment by JonMcDevitt** [comment]
As an addendum, I've built this with three BAZEL environment configurations:

1. BAZEL_VC defined, BAZEL_VS undefined
2. BAZEL_VC undefined, BAZEL_VS defined
3. Both defined

**Comment by rongjiecomputer** [comment]
The issue is not about your Visual C++ installation, it is caused by `BAZEL_SH`.

```
Auto-Configuration Error: Could not determine MSYS/Cygwin root from BAZEL_SH (c:/windows/system32/bash.exe)
```

I am guessing that `c:/windows/system32/bash.exe` is from WSL? WSL does not work with Bazel for now. Only Msys2 is officially supported (though Git bash might work too).

**Comment by meteorcloudy** [comment]
Starting from 0.20.0, Bazel won't fail when `BAZEL_SH` isn't set. See https://github.com/bazelbuild/bazel/commit/f66086d1515866207b42e0ce55ffe6772ecf6b7d.
Please try upgrading Bazel to 0.20.0

**Comment by JonMcDevitt** [comment]
Hi @rongjiecomputer,

I changed the BAZEL_SH to point to that, and I get the same message. I ran a clean --expunge, and then tried again with `BAZEL_SH=D:\dev\MSYS2\64\msys2.exe`, and it gave the following message:

```
Auto-Configuration Error: Could not determine MSYS/Cygwin root from BAZEL_SH (d:/dev/msys2/64/msys2.exe)
INFO: Elapsed time: 14.587s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded)
```

**Comment by meteorcloudy** [comment]
Can you try `bazel clean --expunge`?

**Comment by JonMcDevitt** [comment]
Hi @meteorcloudy,

This was done after a `clean --expunge`; between every build or command I call that to make sure I'm working with a clean environment.

~Jon

**Comment by meteorcloudy** [comment]
@JonMcDevitt Can you show me more error message?

**Comment by JoneJay** [comment]
ME TOO，On linux

**Comment by beautifulnight** [comment]
> ME TOO，On linux

I tried `clean --expunge` but not work. Have you solved this problem?
