### ISSUE TITLE
pkg_deb fails with Bazel 0.20.0 and Python3 --python_top

### ISSUE THREAD

**Issue by qzmfranklin** [bazelbuild/bazel#6818]
### Description of the problem / feature request:
Bazel 0.20.0 fails to build `pkg_deb` targets when the Python toolchain is set to use python3 (via --python_top).

# Repro
```
# tools/python/BUILD
py_runtime(
    name = 'py-3',
    visibility = [
        '//visibility:public',
    ],
    interpreter_path = '/usr/bin/python3',
    files = [],
)
```

```
# bazel.rc
build --python_top=tools/python:py-3
```

Then, `bazel build` *any* `pkg_deb` targets would yield something similar to the following:
```
Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/sandbox/linux-sandbox/4/execroot/logi/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_deb.runfiles/bazel_tools/tools/build_defs/pkg/make_deb.py", line 21, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'
Target //examples/pkg_deb:foo failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

The issue seems to be that `make_deb.py` imports a python2-only module `StringIO`. To make it work with the python3 `py_runtime`, the solution is probably to change `import StringIO` to a version compatible with both Python2 and Python3.

## Regression
I have confirmed that this issue did not exist on the following versions of Bazel:
0.19.2
0.18.X

### What operating system are you running Bazel on?
Ubuntu 18.04.1
amd64

### What's the output of `bazel info release`?
0.20.0

**Comment by laurentlb** [comment]
cc @dslomov

**Comment by qzmfranklin** [comment]
Dear @iirina @dslomov and @brandjon 

I thought Google internally uses python 2.7 (am I right?) so tests were run with python 2.7 most of the time.  I'd like to see some tests with Python3 added to Bazel's test suite so that such regressions are prevented in the future.

With `git annotate`, I found that this regression was introduced by a commit attempting to add streaming capability to `pkg_deb` to avoid choking on huge files.

I am sure you already have an internal plan for fixing this. Could you share the time line here so that I can better plan the upgrade path for my team.

A lot of thanks!

**Comment by brandjon** [comment]
Thank you for the clear diagnosis and the fix, Zhongming and Łukasz!

**Comment by brandjon** [comment]
@aiuto This is a rules-packaging issue since the cause is a source file of a tool being declared compatible with `PY2AND3` but in reality only supporting python 2. But we don't have a rules-packaging team label. Maybe we need to add one?

**Comment by brandjon** [comment]
Or does that fall under team-Product?
