### ISSUE TITLE
Make new_repo rules' build_file attribute take a label

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#682]
Paths are bad.

**Comment by abergmeier** [comment]
Does this track the issue, where you specify an external build file

    new_http_archive(
        name = "boost",
        url = "http://myboost.com",
        build_file = "/tools/build_defs/boost/boost.BUILD",
    )

And `boost.BUILD` includes

    load("/tools/build_defs/boost/extensions", ...

And it searches `extensions` in the `boost` repo?
Or should this be solved by referencing an external repo (which AFAIK does not work yet!?).

**Comment by kchodorow** [comment]
`load(label)` is being tracked in #429.   Once that's in, you'll be able to do `load("//tools/build_defs/boost/extensions:whatever", ...)` to get it from the boost repo or `load("@//tools/build_defs/boost/extensions:whatever", ...)` to get it from your workspace.

**Comment by bsilver8192** [comment]
Is this actually different than #488?

**Comment by kchodorow** [comment]
No, I just failed to find #488 when commenting on #681.
