### ISSUE TITLE
incompatible_dont_emit_static_libgcc: Don't unconditionally emit --static-libgcc

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#6825]
Flag: `--incompatible_dont_emit_static_libgcc`
Available since: 0.22
Will be flipped in: 0.23
Enclosing tracking issue: #6185

### Observable changes

If true, Bazel will not add --static-libgcc to the linking command line, it will be the responsibility of the C++ toolchain to append this flag.

### Migration

Bazel already handles the migration in the case of a CROSSTOOL file that doesn't define `no_legacy_features` feature. In the rare case of a CROSSTOOL that does, please add:

```
feature {
  name: 'static_libgcc'
  enabled: true
  flag_set {
    action: 'c++-link-executable'
    action: 'c++-link-dynamic-library'
    with_feature { feature: 'static_link_cpp_runtimes' }
    flag_group {
      flag: '-static-libgcc'
    }
  }
}
```

This snippet assumes that `static_link_cpp_runtimes` is the feature that when enabled instructs C++ rules to link C++ runtime library statically.

**Comment by schroederc** [comment]
This flag is named `experimental_dont_emit_static_libgcc` in 0.21.

**Comment by hlopko** [comment]
Ouch, the rename didn't make it into the release. I  will postpone the flag flip then. Thanks for letting me know!

**Comment by scottmin0r** [comment]
Release notes for 0.22.0 says this flag was both added and flipped in 0.22 - is this accurate?

**Comment by hlopko** [comment]
Yup I messed that up, I thought the flag made it into 0.21, so I flipped it. But then I realized it's not the case, and I unflipped it, but forgot to update release notes. I'm sorry for the confusion.

**Comment by philwo** [comment]
I verified that this flag was flipped and thus will be included in the Bazel 0.23.0 release.

**Comment by sgyan19** [comment]
in Rlease 0.25.0 I can't find this flag.does it be removed?

**Comment by philwo** [comment]
@sgyan19 The flag is technically still there, but it doesn't do anything anymore.

It was enabled by default in 0.23.0 and at the same time, the possibility to disable it was removed.
