### ISSUE TITLE
incompatible_linkopts_in_user_link_flags: Expose linkopts in `user_link_flags`, not in `legacy_link_flags`

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#6826]
Flag: `--incompatible_linkopts_in_user_link_flags`
Available since: 0.22
Will be flipped in: 0.23

When enabled, flags coming from `--linkopt` Bazel option will be exposed in the `user_link_flags`, not in `legacy_link_flags`. Since these features very often come right after each other (or are added by Bazel automatically), this is very unlikely to break anybody, and in case it does, workarounds will have to be tailor made.

**Comment by hlopko** [comment]
Ouch, the rename didn't make it into the release. I will postpone the flag flip then. Thanks for letting me know!

**Comment by scottmin0r** [comment]
Release notes for 0.22.0 says this flag was both added and flipped in 0.22 - is this accurate?

**Comment by hlopko** [comment]
Yup I messed that up, I thought the flag made it into 0.21, so I flipped it. But then I realized it's not the case, and I unflipped it, but forgot to update release notes. I'm sorry for the confusion.

**Comment by philwo** [comment]
I verified that this flag was flipped and thus will be included in the Bazel 0.23.0 release.
