### ISSUE TITLE
Allow `bazel query` to find targets which provide a given Java class

### ISSUE THREAD

**Issue by keithkml** [bazelbuild/bazel#6827]
### Description of the problem / feature request:

It would be great to be able to run:

```sh
bazel query 'provider_of_java_class(:my_package, "ca.szc.configparser.Ini")'
```

or maybe:

```sh
bazel query 'find_provider_of_java_class("ca.szc.configparser.Ini", deps(:my_package))'
```

It would be really awesome if this also included class files in JAR files used by `java_import` etc.

### Feature requests: what underlying problem are you trying to solve with this feature?

Sometimes you don't know why you depend on a certain class. This information is important in a few circumstances, including migrating / refactoring, pruning dependencies, etc.

### What's the output of `bazel info release`?

We are using a slightly forked Bazel 0.19.0.

###  Have you found anything relevant by searching the web?

There are somewhat related commands for [querying Java source files](https://docs.bazel.build/versions/master/query-how-to.html#What_package_contains_file_java_), but these require that you know the full path to the Java file.

**Comment by ittaiz** [comment]
+1
An example use-case it to implement strict-deps by giving the compiler
direct deps or limited deps and then from the error finding the FQN and
using the above finding the needed target.

Two thoughts for workarounds:
1. jar -tvf on all jars in bazel-bin and external and using grep (from
talking to pants people I think that’s how they do it)
2. We’ve built a server which indexes FQN to labels for a specific reason
and then realized we can use it for this as well.

**Comment by lberki** [comment]
I'm afraid I'll have to close this as WAI -- `bazel query` doesn't really know anything about Java class names (or Java, for that matter), so it cannot tell. In theory, you could cook something up that checks the label of an input file against the fully qualified name of the class, but that would be at best a heuristic.

@meisterT , do you maybe have a clever idea for replacement functionality?

**Comment by meisterT** [comment]
No easy solution here which is guaranteed to be correct. I guess you could implement this with an aspect which collects jdeps files from strict deps checking.
