### ISSUE TITLE
 toolchain docs: toolchain_type attributes should use absolute label

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#6829]
### Description of the problem / feature request:

The toolchain docs give an example where the toolchain rule references the toolchain_type by relative label:

```
toolchain(
    name = "barc_linux_toolchain",
    exec_compatible_with = [
        "@bazel_tools//platforms:linux",
        "@bazel_tools//platforms:x86_64",
    ],
    target_compatible_with = [
        "@bazel_tools//platforms:linux",
        "@bazel_tools//platforms:x86_64",
    ],
    toolchain = ":barc_linux",
    toolchain_type = ":toolchain_type",
)
```

https://docs.bazel.build/versions/master/toolchains.html

This is wrong -- even though it's syntactically correct, toolchain resolution will not work if this rule is ever used from an external repository.

Instead, the toolchain_type should always reference absolute labels, even if the target is in the same package:

 ```
toolchain(
    ...
    toolchain_type = "@repo_name//path/to/package:toolchain_type",
)
```

###  Have you found anything relevant by searching the web?

Related bug: https://github.com/bazelbuild/bazel/issues/6828

**Comment by mfarrugi** [comment]
This is *super* difficult to debug, would love to see this immediately error out.

**Comment by katre** [comment]
This is a special case of #11128.

**Comment by sventiffe** [comment]
@laszlocsomor @juliexxia this one hasn't been updated since a while (the referenced issue mentioned on May 11 is still open though). Is this issue still relevant?

**Comment by laszlocsomor** [comment]
@sventiffe Thanks for asking!

It seems to work now. Here's a complete example, built on top of the tutorial at https://docs.bazel.build/versions/3.7.0/toolchains.html (feel free to add it to the page):

https://github.com/laszlocsomor/projects/tree/057dff60b684567fb4392be0010ec9e49518173f/bazel/2020-11-11-toolchains-platforms-toolchaintype
