### ISSUE TITLE
external repo does not work with package_path

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#683]
(maybe this is obvious, but can't judge just now.)

$ bazel build --package_path=%workspace%:../bazel test/...
Extracting Bazel installation...
..........
ERROR: Error sending results to http://localhost:8082: Connection to http://localhost:8082 refused.
ERROR: /home/hanwen/vc/bazel/tools/build_rules/go/toolchain/BUILD:15:1: no such package '@golang-linux-amd64//': In new_http_archive rule //external:golang-linux-amd64 the 'build_file' attribute does not specify an existing file (/home/hanwen/vc/test/tools/build_rules/go/toolchain/BUILD.go-toolchain does not exist) and referenced by '//tools/build_rules/go/toolchain:toolchain'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 78.693s

**Comment by kchodorow** [comment]
Dup of #488.
