### ISSUE TITLE
Issue finding gold linker if not in the same directory as clang?

### ISSUE THREAD

**Issue by allevato** [bazelbuild/bazel#6834]
### Description of the problem / feature request:

rules_swift uses the `cc_common` APIs to invoke link actions using the C++ toolchain (specifically `clang`; on Linux we specify `CC=clang` to force it).

Starting around mid-October, our Linux builds on Travis started failing with the error `clang-5.0: error: invalid linker name in argument '-fuse-ld=gold'`. Looking back, this roughly coincided with [this commit](https://source.bazel.build/bazel/+/c6ec22f94faaf1320f576d5658a106483b2bf19f), which removed a hardcoded `-B/usr/bin` that was being passed to the compiler driver.

On Travis, Bazel finds `clang` in `/usr/local/clang-5.0.0/bin`, which is different from the `/usr/bin` directory where `ld.gold` lives.

Here's what I _think_ is happening:

1. The C++ toolchain config [invokes `clang -fuse-ld=gold`](https://source.bazel.build/bazel/+/master:tools/cpp/unix_cc_configure.bzl;l=178) to determine if the gold linker is supported. This is successful (can this `repository_ctx.execute` see the system path?).
2. The toolchain config [passes clang's `bin` dir as a `-B` tools search path](https://source.bazel.build/bazel/+/master:tools/cpp/unix_cc_configure.bzl;l=227) and also adds `-fuse-ld=gold` to all link actions.
3. Build actions later on that use this toolchain try to invoke `clang -B/usr/local/clang-5.0.0/bin -fuse-ld=gold`. But `ld.gold` is not in that directory, so clang goes on to search the system path, which it also doesn't have access to. Thus, it fails.

In trying to narrow this down, I found that there were two ways to fix it:

1. Add `--action_env=PATH` to my `.bazelrc`.
2. Symlink `ld.gold` into `/usr/local/clang-5.0.0/bin`.

I went with the second approach, because I don't want to leak `PATH` into all of my build's actions.

#### Possible solutions

It seems like the C++ toolchain configuration needs to handle the situation where `ld.gold` isn't in the same directory as `clang`. Would it make sense to say that if `_is_gold_supported` is true, then we need to add the directory containing `which ld.gold` as a second `-B` option when invoking clang?

### What operating system are you running Bazel on?

Linux (Ubuntu 14.04)

**Comment by hlopko** [comment]
Good catch (and great investigation!).

I'm actually thinking about adding -B to the _is_gold_supported, so we use gold that is associated with clang installation. Whyt?

**Comment by hlopko** [comment]
Yeah, and because we add -B we should not detect gold in your case, that's what I meant. I'll think about implications of having multiple -B, I already forgot why it was a problem to have -B/usr/bin there.

**Comment by allevato** [comment]
Ah, ok. It seems like we might still potentially want to use gold if it was installed even somewhere else on the system, but as long as the behavior is *consistent*, that's the more important thing.

**Comment by mzeren-vmw** [comment]
> I already forgot why it was a problem to have -B/usr/bin there.

From: https://github.com/bazelbuild/bazel/pull/6360 https://github.com/bazelbuild/bazel/commit/c6ec22f94faaf1320f576d5658a106483b2bf19f

> [Always] Putting -B/usr/bin on the link line breaks use of custom C/C++ toolchain[s]
since support binaries such as ld, as, etc., will incorrectly "leak" to
the build machine.
...

**Comment by surak** [comment]
This issue stops JAX from working on Centos7 when using easybuild - Bazel finds ld.gold from easybuild, tests it, realizes that the --push-state option is there, and then adds a `-B/usr/bin` to files, which will then look for the system installed ld.gold there.

```
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/k8-opt/bin/external/com_google_protobuf/protoc-2.params)
Execution platform: @local_execution_config_platform//:platform
/usr/bin/ld.gold: --push-state: unknown option
/usr/bin/ld.gold: use the --help option for usage information
collect2: error: ld returned 1 exit status
```

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
