### ISSUE TITLE
Merge strip_prefix from pkg_tar and data_path from docker_build

### ISSUE THREAD

**Issue by kamalmarhubi** [bazelbuild/bazel#684]
Forked from #671.

Both of these rules use //tools/build_defs/pkg:build_tar under the hood. I find `strip_prefix` to be a clearer name than `data_path`.

Work here could also do some clearing up of duplication between the two Skylark files:
- https://github.com/bazelbuild/bazel/blob/b94713e8f83ef4dad4a6611411d93eadbcc4c95f/tools/build_defs/docker/docker.bzl#L53-L83
- https://github.com/bazelbuild/bazel/blob/b94713e8f83ef4dad4a6611411d93eadbcc4c95f/tools/build_defs/pkg/pkg.bzl#L20-L53

**Comment by damienmg** [comment]
+1

To be clear on this one: pkg_tar is the reference API (the API is close to what we have historically in Blaze), docker_build is the one we should change.

**Comment by aiuto** [comment]
Closing as obsolete. The docker rules are now in a new repo and have significantly changed.
Please create an issue in bazelbuild/rules_docker if this change would still make sense given the current rules.

CC: @nlopezgi
