### ISSUE TITLE
New http_archive rule doesn't support repo_mapping

### ISSUE THREAD

**Issue by g-easy** [bazelbuild/bazel#6845]
### Description of the problem / feature request:

prometheus-cpp imports zlib as `@net_zlib_zlib`
grpc imports zlib as `@com_github_madler_zlib`

Previously, I could "join the diamond" by doing:

```python
http_archive(
  name = "com_github_jupp0r_prometheus_cpp",
  repo_mapping = {"@net_zlib_zlib": "@com_github_madler_zlib"},
```

But with the new:

```python
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
```

The repo_mapping arg doesn't exist.

### Feature requests: what underlying problem are you trying to solve with this feature?

Join the diamond when dependencies disagree on naming, as mentioned in https://docs.bazel.build/versions/master/external.html#shadowing-dependencies

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 0.20.0

###  Have you found anything relevant by searching the web?

There are very few mentions of `repo_mapping` in general, and none on StackOverflow.

**Comment by Zetten** [comment]
The `repo_mapping` attribute is also missing from the `git_repository` rule. I wonder if it needs to be added explicitly to each `repository_rule` instantiation, or if it can be spliced in automatically.

**Comment by dkelmer** [comment]
It is supposed to be added to each rule automatically, but given these reports it might be working only for natively defined rules (rules written in Java and built into Bazel) and not for rules defined in starlark. I'll take a look today.

**Comment by cnsgsz** [comment]
Is the [doc](https://bazel.build/rules/lib/repo/http) missing `repo_mapping`?
