### ISSUE TITLE
Skylark doesn't allow named format interpolation

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/bazel#685]
"foo %(var)s bar" % {"var": "hello"}

is a quite nice pythonic construct, but in skylark I get told:

		"echo %(file)s" % {"file": ctx.file.src.path}
unsupported format character "(" at index 6 in "echo %(file)s".

**Comment by janakdr** [comment]
As a workaround, I think
"foo {file} bar".format(file="blah")
does do what you want. Maybe not pythonic enough?

**Comment by illicitonion** [comment]
Woo! Does the job for me :) Thanks!

**Comment by davidzchen** [comment]
Are we considering supporting the `"foo %(var)s bar" % {"var": "hello"}` syntax as well or is `.format()` sufficient?

**Comment by laurentlb** [comment]
.format() should be sufficient

**Comment by ittaiz** [comment]
@laurentlb this might be a different issue so feel free to ask me to open a new one but it feels very related- WDYT about supporting a more concise string interpolation format?
In Scala one can say:
```
val name = "laurent"
println(s"Hello $name")
``` 
and the above will of course return `Hello laurent`.
I've just been reading a lot of .bzl files lately and the verbosity of the .format with the repetition of the variable names impedes readability IMHO.

**Comment by laurentlb** [comment]
Your example is very simple, but you can write:
```
name = "laurent"
print("Hello %s" % name)
```
or
```
name = "laurent"
print("Hello " + name)
```

It's the same verbosity as your Scala example. I don't think it's worth adding complexity to the language, just to support yet another string syntax.
