### ISSUE TITLE
download_and_extract: strange characters when unzip 

### ISSUE THREAD

**Issue by moruowait** [bazelbuild/bazel#6855]
### Description of the problem :

> strange characters when bazel unzip a tar.gz with UTF8 format.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> use go_repository HTTP mode to download tar.gz with a file which filename is Chinese characters.  

### What operating system are you running Bazel on?

> Darwin

### What's the output of `bazel info release`?

> bazel-bin: 
execution_root: /private/var/tmp/_bazel_wushaoqing/2abb6bb8a734577b3b589dedb12ee9ea/execroot/xrc
gc-count: 21
gc-time: 1019ms
/private/var/tmp/_bazel_wushaoqing/install/71132eb9633b69fb3af8d3c541e0bb00/_embedded_binaries/embedded_tools/jdk
java-runtime: OpenJDK Runtime Environment (build 9.0.7.1+1) by Azul Systems, Inc.
java-vm: OpenJDK 64-Bit Server VM (build 9.0.7.1+1, mixed mode) by Azul Systems, Inc.
max-heap-size: 1908MB
output_base: /private/var/tmp/_bazel_wushaoqing/2abb6bb8a734577b3b589dedb12ee9ea
output_path: /private/var/tmp/_bazel_wushaoqing/2abb6bb8a734577b3b589dedb12ee9ea/execroot/xrc/bazel-out
package_path: %workspace%
release: release 0.19.1
repository_cache: /var/tmp/_bazel_wushaoqing/cache/repos/v1
server_log: /private/var/tmp/_bazel_wushaoqing/2abb6bb8a734577b3b589dedb12ee9ea/java.log
server_pid: 51748
used-heap-size: 174MB
workspace: /Users/wushaoqing/Projects/depot

**Comment by steeve** [comment]
Possibly related to https://github.com/bazelbuild/bazel/issues/374

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
