### ISSUE TITLE
Allow build event files to be appended in watch mode

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#6856]
https://docs.bazel.build/versions/master/build-event-protocol.html#consume-in-text-formats
documents a simple way for Bazel to produce machine-readable streamed output
```
--build_event_text_file
--build_event_json_file
```

However when used in combination with bazel-watcher (aka `ibazel`) the file is overwritten for each time a build is triggered. This makes it very difficult to write a client for the protocol. On Mac/Linux you could use an open filehandle to read the prior file when a new one is written, but on Windows you can't even overwrite a file that has open filehandles IIUC.

This would be much easier to use from a client if the file could be opened in append mode instead. This means the file would have multiple `BuildStarted`/`BuildFinished` events, and a client would read from a single file as the watch mode kicks off additional builds.

/cc @clydin

**Comment by katre** [comment]
Closed for lack of activity. Please ping the reviewers to reopen if this is still a problem.
