### ISSUE TITLE
Cannot construct a PathFragment in a skylark action

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/bazel#686]
I got an error message telling me that "executable" on a ctx.action must be a file or a PathFragment. I wanted to run /bin/bash, so tried constructing a PathFragment, but seemed unable to do so.

**Comment by bsilver8192** [comment]
The value there should be a [File](http://bazel.io/docs/skylark/lib/File.html), which you would usually get from an attribute through [ctx.executable](http://bazel.io/docs/skylark/lib/ctx.html#executable). However, the only way to do that for /bin/bash is using a new_local_repository, which seems overcomplicated here. I would just use [command](http://bazel.io/docs/skylark/lib/ctx.html#action.command) instead. Bazel wraps the whole thing in a `bash -c "your command"` already, so you might not to mention bash explicitly, or you can just use it from $PATH inside the command.
