### ISSUE TITLE
Incomplete repository_rule overriding

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/bazel#6864]
### Description of the problem:

A previously declared repository_rule cannot be fully overridden by a repository_rule with the same name. If these targets are declared in different bzl files.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Download https://gist.github.com/ashi009/bf09b61d7a076aa8ed59d9c06cc6b378 as an archive and unarchive it.
1. Run `bazel build //:readme` yields `# This is not patched`.
1. Run `mv WORKSPACE{.1,}`.
1. Run `bazel build //:readme` yields `# THIS IS PATCHED`.

### What operating system are you running Bazel on?

macOS 10.14.1

### What's the output of `bazel info release`?

release 0.19.1

### Any other information, logs, or outputs that you want to share?

- `bazel query` shows the patched version consistently, regardless of the loading sequence.

  ```shell
  $ bazel query //external:all --output=xml | grep com_github_ashi009_bazel_repo_rule_test -A 11
      <rule class="http_archive" location="/Users/xiaoyi/Projects/depot/test-patched.bzl:4:5" name="//external:com_github_ashi009_bazel_repo_rule_test">
          <string name="name" value="com_github_ashi009_bazel_repo_rule_test"/>
          <list name="urls">
              <string value="https://codeload.github.com/ashi009/bazel-repo-rule-test/zip/5689dd63c35cef83099a270970aad889f22a2909"/>
          </list>
          <string name="strip_prefix" value="bazel-repo-rule-test-5689dd63c35cef83099a270970aad889f22a2909"/>
          <string name="type" value="zip"/>
          <list name="patches">
              <label value="//:readme.patch"/>
          </list>
          <list name="patch_args">
              <string value="-p1"/>
          </list>
          <rule-input name="//:readme.patch"/>
      </rule>
  ```

- Moving `http_archive` targets from `test{,-patched}.bzl` to `WORKSPACE` or to the same .bzl file won't trigger the bug.

**Comment by dslomov** [comment]
Overriding repositories with the same name should never be allowed

**Comment by ashi009** [comment]
@dslomov

That's what I thought until I read https://github.com/bazelbuild/rules_go/issues/749#issuecomment-336902080 by @jayconrod. 

I think a few other rules are using this feature already: https://github.com/bazelbuild/rules_typescript/issues/341.

**Comment by dslomov** [comment]
This behavior is unintentional and incorrect. We should break it (with incompatible change). People who want to allow redefinition can do so with `_maybe` handler.

**Comment by ashi009** [comment]
Any update on this one?

**Comment by ashi009** [comment]
Friendly ping, and is this still a P1 bug?
