### ISSUE TITLE
bazel downloads the JDK during execution

### ISSUE THREAD

**Issue by sergiocampama** [bazelbuild/bazel#6865]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

When running tests with bazel, it tries to download some JDK. This makes bazel dependent on connectivity in order to run.  In our case, we do have connectivity to the internet, but if there are transitive errors when trying to download the JDK, the tests will fail. If there are no errors, it still adds extra time to the tests, which is not ideal.

Why is this needed? Can't bazel be completely hermetic and not require runtime downloads?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://travis-ci.org/bazelbuild/rules_apple/jobs/464988085

### What operating system are you running Bazel on?

macOS / Travis

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Using bazel at "head" from the nightly releases.

**Comment by sergiocampama** [comment]
This is the actual error line we're getting:

```
/private/var/tmp/_bazel_travis/2b80b7ac301f661b0fa17c1c94402319/execroot/build_bazel_rules_apple/_tmp/c740a88c54849b35c3371966379e4d43/_bazel_travis/58f5ae0bd4f5d2153c1b56727890a337/external/bazel_tools/tools/jdk/BUILD:305:1: no such package '@remotejdk_macos//': java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu-9.0.7.1-jdk9.0.7/zulu9.0.7.1-jdk9.0.7-macosx_x64-allmodules.tar.gz] to /private/var/tmp/_bazel_travis/2b80b7ac301f661b0fa17c1c94402319/execroot/build_bazel_rules_apple/_tmp/c740a88c54849b35c3371966379e4d43/_bazel_travis/58f5ae0bd4f5d2153c1b56727890a337/external/remotejdk_macos/zulu9.0.7.1-jdk9.0.7-macosx_x64-allmodules.tar.gz: Unknown host: mirror.bazel.build and referenced by '@bazel_tools//tools/jdk:remote_jdk'
```

**Comment by cushon** [comment]
cc @meisterT 

This is the result of #6656.

**Comment by meisterT** [comment]
This is intentional, we're not longer exposing the embedded JDK that we use to run bazel as host_jdk. You can explicitly set the `--host_javabase` if you want to avoid downloads, e.g., to `@local_jdk//:jdk`.

**Comment by jeb2239** [comment]
I don't think --host_javabase exists anymore is there an alternative way to prevent jdk downloads given there is a jdk on the machine.

**Comment by meisterT** [comment]
@jeb2239 `--host_javabase` still exists. You might have been confused by `incompatible_use_jdk11_as_host_javabase` which just switches the default host_javabase but doesn't remove the option to set your own.

**Comment by jeb2239** [comment]
is this supposed to be a startup option? What should it be set too if I want to stop all downloads of jdks? I have JAVA_HOME set to my local java install. I have tried pointing --host_javabase to various things but I keep getting an option doesn't exist error.

**Comment by meisterT** [comment]
No it's not a startup option, see https://docs.bazel.build/versions/master/user-manual.html#flag--host_javabase.

`bazel build --host_javabase=@local_jdk//:jdk //path/to/your:target` should work and not download any JDK.

**Comment by jhinrichsen** [comment]
I ran into the same problem and this runs just fine
