### ISSUE TITLE
Improve python shell integration test coverage

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#6868]
Namely, OSS some internal-only basic "hello world" tests demonstrating py_binary, py_library, runfiles access, and choosing the Python version.

**Comment by brandjon** [comment]
From #3567: Make sure to include coverage for end-to-end behavior of builds using in-build (hermetic) Python runtimes.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
