### ISSUE TITLE
Better documentation/controls to allow CI caching

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/bazel#6869]
Sorta related to #6865

https://travis-ci.org has support for setting up a directory to be cached/reused between runs.  It would seem like for bazel, the good thing to do would be to be able to cache all the remote repo downloads and then likely the action cache.

Looking at [Output Directory Layout](https://docs.bazel.build/versions/master/output_directories.html) and `bazel help --long startup_options` is isn't completely clear how to do this.

The _Output Directory Layout_ page seems to say things will go into `~/.caches/bazel/`, as a starting point, but that doesn't seem be true for macOS.

`--output_base` does seem to control where *everything*, goes, but this seems to include some log files, which it wouldn't make sense to get cache.

`--output_user_root` also does seem to control a large chunk of things, but again it includes some log files that likely should be in a cache.

`--disk_cache` does work, and is reasonable scoped, but we'd still need something for the downloads.

Doing some digging in other rules repos, I did find `--experimental_repository_cache`, but I can't find that in the help, and it wasn't immediately clear that the value caused anything to be written there.

The [Remote Caching](https://docs.bazel.build/versions/master/remote-caching.html) page does talk about `--disk_cache`, but the pages does't seem to cover some of the other things bazel can need to download and maintain locally.

So, can something better document (which make require more options), how to control where downloads are cached to be reused between CI runs?  These sorta controls could also be useful to allow the showing of downloads between multiple workspaces on a single machine.

**Comment by jin** [comment]
`--experimental_repository_cache` is now `--repository_cache` and enabled by default. I believe the default value is `$HOME/.cache/bazel/_bazel_jingwen/cache/repos/v1/` and all external repos with their checksums explicitly specified in the WORKSPACE are cached. @aehlig did some work here recently.

**Comment by ittaiz** [comment]
IIRC this works only for rctx.download /download_and_extract with checksums
(so no git repository, no maven_jar rule) but does catch many others
