### ISSUE TITLE
Output sharing via --output_user_root is broken

### ISSUE THREAD

**Issue by piratf** [bazelbuild/bazel#6870]
### Description of the problem / feature request:

bug: fatal error when start bazel with --output_user_root=/data/tmp/

```
$ bazel --output_user_root=/data/tmp build [other options and the target]
FATAL: mkdir('/data/tmp/'): (error: 13): Permission denied
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I want multiple users to share the same execution directory, so they can share one build process and the cache file is still saved after any user destroys itself.
the /data/ and /data/tmp/ is already created by the root user, and /data/tmp/ has setted to 777.
May be 'mkdir' should not be executed on the existing directory?

```
$ ll /data
total 828
drwxrwxrwx 19 root root   4096 Oct  9 11:46 ccache
drwxrwxrwx  2 root root   4096 Dec  7 15:33 corefile
drwxr-xr-x  4 root root   4096 Oct 29 20:18 home
drwx------  2 root root  16384 Mar  7  2018 lost+found
drwxrwxrwx  4 root root 815104 Dec  8 14:32 tmp
```

### What operating system are you running Bazel on?

CentOS 7 x86_64

### What's the output of `bazel info release`?

release 0.19.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

only 'release 0.19.1'. installed from the script "bazel-0.19.1-installer-linux-x86_64.sh" in the release page.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> fatal: Not a git repository (or any parent up to mount point /data)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /data)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /data)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

###  Have you found anything relevant by searching the web?

 I have tried google 'bazel output_user_root mkdir' but have not found solution.

### Any other information, logs, or outputs that you want to share?
 No more error messages.

**Comment by susinmotion** [comment]
Good point about Bazel trying to make a directory that already exists. We should look at this.

But if you want to share a cache between users, you probably want to use `--disk_cache` instead. We don't support using `--output_user_root` to share data between users. Does that help?

**Comment by piratf** [comment]
@susinmotion Got it, thank you!

**Comment by curgunlu** [comment]
@susinmotion I thought "--output_user_root" option is created with goal to share build objects with other users. See https://docs.bazel.build/versions/master/user-manual.html section "--output_user_root". Am I getting it wrong?

**Comment by NikolayPianikov** [comment]
I have the same issue: `FATAL: mkdir('/home/abc/system/bazel/root'): (error: 13): Permission denied`

I build a project in docker container `l.gcr.io/google/bazel:latest`
I map docker volume `-v /home/abc/system:/home/abc/system` to improve a performance for repeatable builds.
I do not change user in a docker container.
I run the command under `builduser` user account: `bazel --output_user_root=/home/abc/system/bazel/root build -- :ProjectRunner` in docker.
And it works at first time, but it fails at second and at others with error above till I delete the directory `/home/abc/system/bazel/root`.

`ls -l` from the host machine after first build is:
`drwxr-xr-x 5 builduser builduser`

When I do the same under the root user at host everething is ok.

**Comment by jmmv** [comment]
Huh, so I wonder when `--output_user_root` broke, because it's obviously broken. I see that the code even has left-over comments implying that this should work:

https://cs.opensource.google/bazel/bazel/+/master:src/main/cpp/blaze_util_posix.cc;l=495;drc=759170fc56c34356a46fb35ab1f108c8535d861f

We should add a test when fixing. `--output_user_root=/tmp` might be sufficient and work everywhere.

**Comment by jmmv** [comment]
Oh wow, took quite a bit of archaeology to reach the problem. The `CreateSecureUserRoot` and `MakeDirectories` functions have moved *so* many times...

This broke starting in 46af79d4c7401877cc34bf3a321624d8aa96923b, which "helpfully" changed a plain `mkdir` call with `MakeDirectories`. Then, in 237ba6c4e45d88baee602635883f4b03d4d7c322, `MakeDirectories` gained the feature to ensure the last path component is owned by the calling user. And boom, this untested feature broke.

**Comment by jmmv** [comment]
OK, so this was an intentional change but unfortunately it's from cl/69071385 (not available in Git, back from 2014). The change description provides no rationale for the change other than "be paranoid with directory creation", and we have an integration test to verify that the user root cannot actually be shared among users.

I understand why this may be desirable when the output root goes, by default, into a temporary directory that may be shared across users. And it does, e.g. as in #11100.

So... I think the answer here is to change the documentation to say that this is not supported instead of trying to fix this.

**Comment by ulfjack** [comment]
That rings a bell. Before open-sourcing Bazel, we went through a security review, and the reviewer may have pointed out the risk in sharing the output directory locally.
