### ISSUE TITLE
build cleaner?

### ISSUE THREAD

**Issue by cnsgsz** [bazelbuild/bazel#6871]
Is it possible to automatically update the dependencies of build rules, etc? It could be a huge productivity boost for users.

**Comment by jin** [comment]
The language rulesets typically provide their own tools, like gazelle for Go rules. Could you elaborate more on what you would like to see in this tool?

**Comment by cnsgsz** [comment]
Yes, tools like gazelle is what I'm looking for. Is there an equivalent for c++ and Python? Thanks!

**Comment by petroseskinder** [comment]
i believe there is one for python. Take a look at awesomebazel.com

c++ is a bit harder to automatically generate deps for

**Comment by cnsgsz** [comment]
I see. Thanks for the suggestion! awesomebazel.com is awesome!

Is this the one for python you have in mind? https://github.com/tuomasr/pazel

What is particularly hard about c++? Is there one for c++ used in google internally and if so is it feasible to open source that? Thanks!

**Comment by yzhao1012** [comment]
There is already an internal version working inside Google, might route this to the internal build cleaner maintainer for more input.

**Comment by regisd** [comment]
https://github.com/bazelbuild/buildtools/blob/master/unused_deps/unused_deps.go can help

**Comment by antspy** [comment]
Hi, 

Any update on this?

**Comment by fruffy-g** [comment]
We would also like to use this to check open-source contributions. Is there a build cleaner available for C++?

**Comment by meisterT** [comment]
People who interested in this issue, might be interested in this BazelCon presentation: https://www.youtube.com/watch?v=ScB0XiFrcOE&list=PLxNYxgaZ8Rsefrwb_ySGRi_bvQejpO_Tj&index=24
