### ISSUE TITLE
Update documentation to show clearer example of http_archive

### ISSUE THREAD

**Issue by iamorphen** [bazelbuild/bazel#6873]
### Description of the problem / feature request:

The `http_archive` [documentation](https://docs.bazel.build/versions/master/be/workspace.html#http_archive) refers to the new Skylark rule as being a drop-in replacement. The replacement is not drop-in, though, as the referenced build file (used when transitioning from the deprecated `new_http_archive` to the Skylark `http_archive`) is anticipated to live in an `external` folder. Calling the new Skylark rule a drop-in replacement without mentioning the requirement on a referenced build file is confusing.

### Feature requests: what underlying problem are you trying to solve with this feature?

Attempting to solve confusion when transitioning from older Bazel versions to newer versions.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See issue [5890](https://github.com/bazelbuild/bazel/issues/5890).

### What operating system are you running Bazel on?

Ubuntu 18.04.

### What's the output of `bazel info release`?

```
INFO: Invocation ID: 803d2a83-d8fb-4357-a52d-c8f313aa8cd5
release 0.20.0
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

I found issue [5890](https://github.com/bazelbuild/bazel/issues/5890) coincidentally by searching for "Not a regular file."

### Any other information, logs, or outputs that you want to share?

N/A

**Comment by aehlig** [comment]
There is documentation present for the Starlark `http_archive`, as a [docstring next to the definition](https://github.com/bazelbuild/bazel/blob/ce91f76e659cee6940d0f5e10c2bbd7e43be76d4/tools/build_defs/repo/http.bzl#L144). Unfortunately, the mechanism to put those documentation on the bazel documentation web page is not in place yet.

**Comment by laurentlb** [comment]
@aehlig Can you look at Skydoc and see if it works for you?

An alternative is to move the documentation manually to the website. It's not ideal, but since we have few files in `@bazel_tools`, it might be okay (to avoid adding complexity to the release process).

**Comment by MarkusTeufelberger** [comment]
https://docs.bazel.build/versions/master/be/overview.html (version 0.23: https://docs.bazel.build/versions/0.23.0/be/overview.html) no longer lists `http_file` as a Workspace rule at all, so unless someone by accident stumbles upon a docstring in an obscure sub-sub-subfolder in this repository, there's no way that this rule can be discovered by a new user. Please either restore the existing documentation or add the documentation of these built-in (but non-native) rules to the next release, maybe as another subsection.

**Comment by davidsmd** [comment]
This is an issue for the new_git_repositry rule as well; though that rule doesn’t have updated documentation buried in the source like http_archive does...

**Comment by aehlig** [comment]
> This is an issue for the new_git_repositry rule as well; though that rule doesn’t have updated documentation buried in the source like http_archive does...

`new_git_repository` does have a doc string as well, see https://github.com/bazelbuild/bazel/blob/d79786d45be22b27f9dce9a03a5b0cb97daed414/tools/build_defs/repo/git.bzl#L169

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment]
Fix, currently in internal review, https://bazel-review.googlesource.com/c/bazel/+/92610/
This also affects #7638 and #6730.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by limdor** [comment]
@aehlig commenting here before opening a ticket because is the closest that I've seen.
I am trying to find out the best practice on using http_archive and in the documentation that you point out I cannot find it. If you call http_archive without any kind of check, you could call it two times with the same name and different parameters and you would not get any warning/error.

One option is to check if it is already available in the existing_rules and only call http_archive if it is not present. In the else you could display a message in case that was already present but in reality you would only want a warning/error if was already called with different parameters (different library version for example).

Another option would be to wrap the http_archive in a maybe call but as far as I am aware this would also not display a warning in case that is present but behave like the if check.
