### ISSUE TITLE
find_cpp_toolchain() should not test for CPP toolchain

### ISSUE THREAD

**Issue by mboes** [bazelbuild/bazel#6874]
### Description of the problem

Since Bazel 0.20, we are required to add a hidden attribute `_cc_toolchain` to any rule that requires access to the CC toolchain. We are then asked to use `find_cpp_toolchain()` inside the rule implementation to locate the toolchain. But in an aspect this doesn't work.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Define an aspect over a rule that calls `find_cpp_utils()`. You will get an error like the following:

```
$ bazel build //...
[...]
"/home/mboes/.cache/bazel/_bazel_mboes/822aa44857e17f47d08bb198503f3032/external/io_tweag_rules_haskell/haskell/cc.bzl", line 92, in cc_interop_info
		find_cpp_toolchain(ctx)
	File "/home/mboes/.cache/bazel/_bazel_mboes/822aa44857e17f47d08bb198503f3032/external/bazel_tools/tools/cpp/toolchain_utils.bzl", line 39, in find_cpp_toolchain
		ctx.fragments
'struct' object has no attribute 'fragments'
Available attributes: actions, attr, bin_dir, executable, file, files, genfiles_dir, label, toolchains, var
```

### What operating system are you running Bazel on?

NixOS

### What's the output of `bazel info release`?

0.20.0

### Any other information, logs, or outputs that you want to share?

Looking at https://github.com/bazelbuild/bazel/blob/0.20.0/tools/cpp/toolchain_utils.bzl#L36-L42, the fix looks fairly straightforward. The first conditional tests that the `_cc_toolchain` attribute is present. So there is then no need to test whether `@bazel_tools//tools/cpp:toolchain_type` is in `ctx.toolchains`, because `_cc_toolchain` will always be present at that point in the control flow.

Found this as part of https://github.com/tweag/rules_haskell/issues/492. I should be able to workaround this using my own local version of `find_cpp_toolchain()`.

**Comment by aherrmann** [comment]
It looks like this issue was fixed by https://github.com/bazelbuild/bazel/commit/0581d1961199ee7d8b7cad92e77e7ef927d526bb which removed the access to `ctx.fragments`.
