### ISSUE TITLE
Still dependent on msys2 on Windows?

### ISSUE THREAD

**Issue by petemounce** [bazelbuild/bazel#6875]
### Description of the problem / feature request:

Someone on the internet asked, on chocolatey, why msys2 is a dependency. http://disq.us/p/1xk2xaf

I think the answer _might_ at this point be, it's not a dependency. Is that accurate? cc @laszlocsomor 

### Feature requests: what underlying problem are you trying to solve with this feature?

Remove a dependency from the chocolatey installer.

### What operating system are you running Bazel on?

Windows

**Comment by laszlocsomor** [comment]
Unfortunately MSYS2 is still a dependency, because Bazel needs Bash to run tests.
Follow along on https://github.com/bazelbuild/bazel/issues/5508

**Comment by laszlocsomor** [comment]
Closing this issue because the question is answered.
