### ISSUE TITLE
Document how to get "mostly static" link options with new C++ toolchain API

### ISSUE THREAD

**Issue by mboes** [bazelbuild/bazel#6876]
I don't know whether this is a bug. But it's at the very least a documentation request. It's blocking https://github.com/tweag/rules_haskell/issues/492.

### Description of the problem

Since Bazel 0.20, getting the CC linker flags is now done via the [new C++ toolchain API](https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#disable-legacy-c-configuration-api). Before that, I would use `cc_toolchain.mostly_static_link_options(True)`. But I can't find a way to emulate the same linker options with the new API. No matter what options I pass to the call to  `cc_common.create_link_variables()` in the code snippet provided in the migration guide, I notice that the linker flags that are returned systematically include `"-shared"` in the result, when they did not in the output of `cc_toolchain.mostly_static_link_options(True)`.

Sample output:

```
["-shared", "-fuse-ld=gold", "-Wl,-no-as-needed", "-Wl,-z,relro,-z,now", "-pass-exit-codes", "-lstdc++", "-lm"]
```

Options I tried:

* pass `is_linking_dynamic_library = False`,
* pass `is_static_linking_mode = True`,
* pass both at the same time,
* pass `CPP_LINK_STATIC_LIBRARY_ACTION_NAME` instead of `CPP_LINK_DYNAMIC_LIBRARY_ACTION_NAME` in the `cc_common.get_memory_inefficient_command_line()` call. (This doesn't work at all. Resulting link flags are just `["rcsD"]`, which GCC chokes on.)

### What operating system are you running Bazel on?

Linux NixOS

### What's the output of `bazel info release`?

0.20.0

**Comment by hlopko** [comment]
Sorry for the slow reply. Should you use `CPP_LINK_EXECUTABLE_ACTION_NAME` if you don't want -shared in the output? You might also want to add "static_linking_mode" to requested features, just to be sure. But -shared is coming because of the action name.
