### ISSUE TITLE
how to query with args

### ISSUE THREAD

**Issue by haolongzhangm** [bazelbuild/bazel#6880]
build command: bazel build //xxx/yyyyy:run -c dbg --cpu=android_armv7

what is the query command? 

if I use:    bazel query --nohost_deps --noimplicit_deps  'deps(//xxx/yyyyy:run -c dbg --cpu=android_armv7)'

will put err  syntax error at 'dbg - -' 
so How can I query the deps about target //xxx/yyyyy:run with args "-c dbg --cpu=android_armv7"

**Comment by jin** [comment]
the `query` command has no concept of configuration options like `-c` and `--cpu`. Please try `cquery` instead:

```
$ bazel cquery --noimplicit_deps --nohost_deps 'deps(//xxx/yyyyy:run)' -c dbg --cpu=armeabi-v7a
```

Please ask questions on [bazel-discuss](https://groups.google.com/forum/#!forum/bazel-discuss) or [StackOverflow](https://stackoverflow.com/questions/tagged/bazel) in the future, thank you!
