### ISSUE TITLE
Documentation menu for Starlark

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#6881]
Feedback from the [mailing-list](https://groups.google.com/d/msg/bazel-discuss/S703wE4t_Zg/bG5io7_DBAAJ):

> The other big pain point when learning bazel was the documentation site: https://docs.bazel.build/versions/master/skylark/lib/dict.html
> As you can see, when you are on that site there is no way to navigate to the list datatype. That's obviously my next question when I'm looking at dict (because I got here from some hyperlink). 
> What other datatypes exist? That would be the purpose of the side menu to be contextually relevant but it's just the same old global menu no matter where I am. 
> Actually the best example is this page: https://docs.bazel.build/versions/master/skylark/language.html
> On the left it should say Syntax, API, Modules, Files, Rules, Actions, Globals, Toolchains

**Comment by dslomov** [comment]
This P1 bazel-1.0 issue is unassigned. Please assign.
