### ISSUE TITLE
`select()` doesn't work in `bind()`.

### ISSUE THREAD

**Issue by PiotrSikora** [bazelbuild/bazel#6882]
### Description of the problem / feature request:

`select()` doesn't work in `bind()`, leading to an error:
```
argument 'actual' has type 'select', but should be 'string'
in call to builtin function bind(*, name, actual)
```

### Feature requests: what underlying problem are you trying to solve with this feature?

(same as #6883)

I'm trying to add an alternative SSL library (different build of BoringSSL, really) to Envoy, which could be selected at the build-time using `--define ssl_library=alternative`. Both: `config_setting()` and `select()` work fine for local rules, but it seems that there is no way to pass those selections to the dependencies.

Most Bazel projects that link against SSL libraries use `//external:ssl`, which works great for linking against the same SSL library in projects with a lot of dependencies,  but because there is no way to programmatically set the target of the `//external:ssl` binding nor take a different action in Skylark based on the `config_setting()`, there is no way to switch between the SSL libraries.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ cat WORKSPACE
config_setting(
    name = "use_alternative_ssl_library",
    values = {"define": "ssl_library=alternative"},
)

bind(
    name = "ssl",
    actual = select(
        {
            "//:use_alternative_ssl_library": "@alternative//:ssl",
            "//conditions:default": "@boringssl//:ssl",
        },
    ),
)
```

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 0.20.0

###  Have you found anything relevant by searching the web?

That [Skylark macros can’t evaluate select()](https://docs.bazel.build/versions/master/configurable-attributes.html#macros-select) (`native.bind()` is where I really want to use `select()`, either that, or [take different actions based on results of evaluated `config_setting()`](https://github.com/bazelbuild/bazel/issues/6883))).

That [`bind()` is considered harmful](https://github.com/bazelbuild/bazel/issues/1952), but I don't see how to solve this differently.

**Comment by katre** [comment]
The underlying problem here is that bind() is a WORKSPACE rule, and the WORKSPACE rules don't know about specific configurations.

The [`alias` ](https://docs.bazel.build/versions/master/be/general.html#alias) rule can appear in BUILD files, and accepts a `select` as the value of the `actual` attribute.

Your `config_setting` targets will also need to be in BUILD, not WORKSPACE.

**Comment by PiotrSikora** [comment]
@katre Thanks! The combination of `bind(name="//:ssl_library")` and `alias(name="ssl_library", actual=select())` did the trick for me. I didn't had a clear separation between `BUILD` and `WORKSPACE` rules in my mental model, so your comment helped a lot.

I think the bug is still valid (though perhaps documentation pointing to `bind` + `alias` might be good enough), so I'm going to leave this open and see how's triaged.

**Comment by katre** [comment]
Can you please provide a minimal version of your WORKSPACE and BUILD, showing the bind and alias targets? I'm curious why the bind is needed at all.

**Comment by katre** [comment]
Oh, I see. Thanks for clarifying.

**Comment by gregestren** [comment]
Is the current actionable just clearer documentation?

**Comment by jin** [comment]
@gregestren could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?

**Comment by PiotrSikora** [comment]
@katre either in [`bind()` docs](https://docs.bazel.build/versions/master/be/workspace.html#bind) or somewhere in [`Configurable Build Attributes`](https://docs.bazel.build/versions/master/configurable-attributes.html), perhaps in the FAQ section as `"Using bind() with select()"`?
