### ISSUE TITLE
py_runtime in third_party package conflicts with third_party.py.gflags import in Android rules

### ISSUE THREAD

**Issue by akirchhoff-modular** [bazelbuild/bazel#6886]
### Description of the problem / feature request:

When using the default Python interpreter with Bazel, system and user packages are picked up. To work around that, we are creating a Python [`venv`](https://docs.python.org/3/library/venv.html) in `third_party/python_env` and hooking it up with a `py_runtime`:

```py
package(default_visibility = ["//visibility:public"])

py_runtime(
    name = "python_env",
    files = glob(
        [
            "bin/**/*",
            "include/**/*",
            "lib/**/*",
            "share/**/*",
        ],
        exclude = [
            "lib/python3.5/site-packages/setuptools/command/launcher manifest.xml",
            "lib/python3.5/site-packages/setuptools/script (dev).tmpl",
        ],
    ),
    interpreter = "bin/python3",
    licenses = ["notice"],
)
```

(Then putting `build --python_top=//third_party/python_env` in our `.bazelrc`.)

This has worked pretty well so far, but it conflicts with the Android rules. In particular, `@bazel_tools//tools/android:aar_resources_extractor` tries to import `third_party.py.gflags`, but it can't find it:

```
testuser@c4dbade4fdee:~/example$ bazel build java/com/example:app 
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 3a20b80a-e30d-4b5c-975a-ed3ec6d6d5aa
INFO: Analysed target //java/com/example:app (38 packages loaded, 913 targets configured).
INFO: Found 1 target...
ERROR: /home/testuser/.cache/bazel/_bazel_testuser/3f9d93ae788445057f1d48d9bfbef807/external/androidsdk/com.android.support/BUILD:4869:1: AarResourcesExtractor external/androidsdk/com.android.support/_aar/unzipped/resources/support-v13-23.4.0 failed (Exit 1) aar_resources_extractor failed: error executing command bazel-out/host/bin/external/bazel_tools/tools/android/aar_resources_extractor --input_aar external/androidsdk/extras/android/m2repository/com/android/support/support-v13/23.4.0/support-v13-23.4.0.aar ... (remaining 4 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/home/testuser/.cache/bazel/_bazel_testuser/3f9d93ae788445057f1d48d9bfbef807/sandbox/processwrapper-sandbox/4/execroot/example_bazel_android/bazel-out/host/bin/external/bazel_tools/tools/android/aar_resources_extractor.runfiles/bazel_tools/tools/android/aar_resources_extractor.py", line 30, in <module>
    from third_party.py import gflags
ImportError: No module named 'third_party.py'
Target //java/com/example:app failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 5.997s, Critical Path: 0.40s
INFO: 1 process: 1 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
```

When running `aar_resources_extractor` (after the Bazel stub adjusts `PYTHONPATH` and `os.exec`s into the real executable), the Python path (as it appears in `sys.path`) looks like this:

```py
['/home/testuser/example/bazel-out/host/bin/external/bazel_tools/tools/android/aar_resources_extractor.runfiles/bazel_tools/tools/android',
 '/home/testuser/example/bazel-out/host/bin/external/bazel_tools/tools/android/aar_resources_extractor.runfiles',
 '/home/testuser/example/bazel-out/host/bin/external/bazel_tools/tools/android/aar_resources_extractor.runfiles/bazel_tools/third_party/py/six',
 '/home/testuser/example/bazel-out/host/bin/external/bazel_tools/tools/android/aar_resources_extractor.runfiles/bazel_tools/third_party/py/gflags',
 '/home/testuser/example/bazel-out/host/bin/external/bazel_tools/tools/android/aar_resources_extractor.runfiles/example_bazel_android',
 '/home/testuser/example/bazel-out/host/bin/external/bazel_tools/tools/android/aar_resources_extractor.runfiles/bazel_tools',
 '/usr/lib/python35.zip',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-x86_64-linux-gnu',
 '/usr/lib/python3.5/lib-dynload',
 '/usr/local/lib/python3.5/dist-packages',
 '/usr/lib/python3/dist-packages']
```

`third_party.py.gflags` is present in `aar_resources_extractor.runfiles/bazel_tools/third_party/py/gflags/__init__.py`, but Python stops looking after it encounters `aar_resources_extractor.runfiles/example_bazel_android/third_party/__init__.py` (which is not present in the source tree, but was created by Bazel).

> Side-note on determinism of this bug: These last two `PYTHONPATH` entries come from `GetRepositoriesImports`, defined here:
>
> https://github.com/bazelbuild/bazel/blob/2987897feed85c7e7fc60478f346e128e4eb8c99/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt#L106-L111
>
> The order of them matches the order returned by `os.listdir`. If `os.listdir` returns `bazel_tools` first, it "works"; if `example_bazel_android` comes first, we get the error seen above. From some testing, it appears that a workspace name of `example_bazel_android` will reliably result in `os.listdir` returning `example_bazel_android` before `bazel_tools`, but experimentation with random workspace names shows that only about 18% of the possible workspace names will trigger this condition. (I am not sure what determines it, but I would not be surprised if it were something mundane like the Java hash codes of `bazel_tools` vs. the workspace name.)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The following shell script (note: may require the `python3-venv` package to be installed if you are using a Debian derivative) will create an `example` directory that can reproduce the bug:

```sh
#!/bin/bash
set -e
mkdir example
cd example
cat > WORKSPACE << EOF
workspace(name = "example_bazel_android")

android_sdk_repository(
    name = "androidsdk",
    api_level = 23,
    build_tools_version = "28.0.2",
    path = "/opt/android-sdk",
)
EOF
mkdir -p java/com/example
cat > java/com/example/ExampleActivity.java << EOF
import android.app.Activity;

public class ExampleActivity extends Activity {}
EOF
cat > java/com/example/AndroidManifest.xml << EOF
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example">
  <uses-sdk android:minSdkVersion="23" android:targetSdkVersion="25"/>
  <application>
    <activity android:name=".ExampleActivity">
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
    </activity>
  </application>
</manifest>
EOF
cat > java/com/example/BUILD << EOF
android_binary(
    name = "app",
    srcs = ["ExampleActivity.java"],
    manifest = "AndroidManifest.xml",
    deps = [
        "@androidsdk//com.android.support:appcompat-v7-23.4.0",
        "@androidsdk//com.android.support.constraint:constraint-layout-1.0.2",
        "@androidsdk//com.android.support:design-23.4.0",
        "@androidsdk//com.android.support:support-v13-23.4.0",
    ],
)
EOF
mkdir third_party
python3 -m venv third_party/python_env
cat > third_party/python_env/BUILD << EOF
package(default_visibility = ["//visibility:public"])

py_runtime(
    name = "python_env",
    files = glob(
        [
            "bin/**/*",
            "include/**/*",
            "lib/**/*",
            "share/**/*",
        ],
        exclude = [
            "lib/python3.5/site-packages/setuptools/command/launcher manifest.xml",
            "lib/python3.5/site-packages/setuptools/script (dev).tmpl",
        ],
    ),
    interpreter = "bin/python3",
    licenses = ["notice"],
)
EOF
cat > .bazelrc << EOF
build --python_top=//third_party/python_env
EOF
```

If the above shell script is placed in a file named `setup.sh`, the following steps are sufficient to reproduce the bug:

```sh
$ bash setup.sh 
$ cd example
$ bazel build java/com/example:app
```

For your convenience, here is a Dockerfile that creates a Linux container that is able to reproduce the problem, although it should also be reproducible outside of a container:

```sh
FROM ubuntu:16.04

RUN \
	export DEBIAN_FRONTEND=noninteractive && \
	apt-get update && \
	apt-get dist-upgrade -y && \
	apt-get install -y curl python3 python3-venv && \
	curl https://bazel.build/bazel-release.pub.gpg | apt-key add - && \
	echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" > /etc/apt/sources.list.d/bazel.list && \
	apt-get update && \
	apt-get install -y bazel=0.20.0 && \
	curl -LO https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip && \
	unzip -d /opt/android-sdk sdk-tools-linux-4333796.zip && \
	yes | /opt/android-sdk/tools/bin/sdkmanager --licenses && \
	/opt/android-sdk/tools/bin/sdkmanager 'build-tools;28.0.2' 'extras;android;m2repository' 'extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2' 'extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2' 'platforms;android-23' 'platform-tools' && \
	adduser --disabled-password --gecos '' testuser

USER testuser
WORKDIR /home/testuser

ADD setup.sh .
RUN exec bash setup.sh

WORKDIR /home/testuser/example
CMD bazel build java/com/example:app
```

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

release 0.20.0

###  Have you found anything relevant by searching the web?

It looks like there have been similar issues in the past (#415 was the one I found), but that issue was fixed, so I assume this is a distinct bug.

### Any other information, logs, or outputs that you want to share?

This script can be used to determine whether a particular workspace name triggers the bug or not:

```py
#!/usr/bin/env python3
import subprocess

_TEMPLATE = """\
workspace(name = "{}")

android_sdk_repository(
    name = "androidsdk",
    api_level = 23,
    build_tools_version = "28.0.2",
    path = "/opt/android-sdk",
)
"""


def is_workspace_name_ok(name):
    with open('WORKSPACE', 'w') as f:
        f.write(_TEMPLATE.format(name))
    proc = subprocess.run(
        ['bazel', 'run', '@bazel_tools//tools/android:aar_resources_extractor'],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    return b"third_party.py" not in proc.stdout


def main():
    for i in range(100):
        candidate_name = "example{}".format(i)
        if is_workspace_name_ok(candidate_name):
            print(candidate_name, "does not trigger the bug")
        else:
            print(candidate_name, "does triggers the bug")


if __name__ == '__main__':
    main()
```

`example_bazel_android` is not the name of our real workspace, but our real workspace name happens to be afflicted by this. We have a few places referring to our workspace name, so it is not easy to change our workspace name to work around the issue.

Since issue was precipitated by Bazel creating unnecessary `__init__.py` files, I tried modifying the Bazel source to add [`legacy_create_init = False`](https://docs.bazel.build/versions/master/be/python.html#py_binary.legacy_create_init) to all of the `py_binary` rules in `tools/android/BUILD`, then rebuilding Bazel and using the freshly-built version of Bazel, but for reasons I do not fully understand, `__init__.py` files are still being created.

**Comment by alex-xnor** [comment]
One possible fix: In `tools/android/*.py`, `gflags` is currently being imported from `third_party.py`. If I further qualify each of them to `bazel_tools.third_party.py`, the error goes away. I would submit this as a PR, but my company has not signed a CLA and is currently unwilling to go through that process.

**Comment by brandjon** [comment]
Thank you for the detailed report Alex! I’ll respond to a few points here, but for the larger design issue of what to do about `PYTHONPATH` conflicts, I’ll refer you to the [thread I just started](https://groups.google.com/forum/?nomobile=true#!topic/bazel-sig-python/H26e3VAxsp8) on bazel-sig-python as a result of this report.

> Side-note on determinism of this bug [...]

I'm fixing the aside you mentioned about `listdir` order being ill-defined and potentially non-deterministic. The fix is to `sort()` the result of `listdir`, so this may or may not incidentally work around the problem for your specific case depending on your workspace name.

> If I further qualify each of them to `bazel_tools.third_party.py`, the error goes away. I would submit this as a PR, but my company has not signed a CLA and is currently unwilling to go through that process.

That’s a simple fix and probably good style for reasons I’ll describe below. I’ll take a look, thanks for pointing it out.

> but Python stops looking after it encounters aar_resources_extractor.runfiles/example_bazel_android/third_party/__init__.py (which is not present in the source tree, but was created by Bazel).

I suspect you didn't disable *all* of the Python targets underneath that package from implicitly creating init files. It is certainly not an ideal workaround.

**Comment by brandjon** [comment]
Leaving this open for now. We'll use #7051 to track fixing imports that reference packages under @bazel_tools. When we have a design doc for a fix, we can close this bug in favor of a tracking issue.

**Comment by brandjon** [comment]
> I'm fixing the aside you mentioned about listdir order being ill-defined and potentially non-deterministic. The fix is to sort() the result of listdir [...]

Cancel that, it turns out this breaks a large number of our integration tests due to resolving conflicts in a different way (failed CI [here](https://buildkite.com/bazel/google-bazel-presubmit/builds/13922)). We'll have to just keep the current (unspecified, arbitrary, and possibly unstable) order until we migrate away from allowing non-repo-qualified imports by default. At that point we can add the sorting, but it won't matter because those repos won't be on `PYTHONPATH` anyway.

See #7067 to track the migration for banning non-repo-qualified imports.

**Comment by cgruber** [comment]
I can't tell if I've got a related issue, but I saw the following (running perhaps notably with `--spawn_strategy=worker,local`): 

```
ERROR: /private/var/tmp/_bazel_gruber/f4486085d61cac572d65028d4ddb8d27/external/maven/androidx/documentfile/BUILD.bazel:5:1: AarResourcesExtractor external/maven/androidx/documentfile/_aar/unzipped/resources/documentfile failed (Exit 1)
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_gruber/f4486085d61cac572d65028d4ddb8d27/execroot/__main__/bazel-out/host/bin/external/bazel_tools/tools/android/aar_resources_extractor.runfiles/bazel_tools/tools/android/aar_resources_extractor.py", line 35, in <module>
    from absl import app
  File "/private/var/tmp/_bazel_gruber/f4486085d61cac572d65028d4ddb8d27/execroot/__main__/bazel-out/host/bin/external/bazel_tools/tools/android/aar_resources_extractor.runfiles/bazel_tools/third_party/py/abseil/absl/app.py", line 38, in <module>
    from absl import flags
  File "/private/var/tmp/_bazel_gruber/f4486085d61cac572d65028d4ddb8d27/execroot/__main__/bazel-out/host/bin/external/bazel_tools/tools/android/aar_resources_extractor.runfiles/bazel_tools/third_party/py/abseil/absl/flags/__init__.py", line 41, in <module>
    from absl.flags import _defines
  File "/private/var/tmp/_bazel_gruber/f4486085d61cac572d65028d4ddb8d27/execroot/__main__/bazel-out/host/bin/external/bazel_tools/tools/android/aar_resources_extractor.runfiles/bazel_tools/third_party/py/abseil/absl/flags/_defines.py", line 31, in <module>
    from absl.flags import _flag
ImportError: cannot import name '_flag' from 'absl.flags' (/private/var/tmp/_bazel_gruber/f4486085d61cac572d65028d4ddb8d27/execroot/__main__/bazel-out/host/bin/external/bazel_tools/tools/android/aar_resources_extractor.runfiles/bazel_tools/third_party/py/abseil/absl/flags/__init__.py)
----------------
Note: The failure of target @bazel_tools//tools/android:aar_resources_extractor (with exit code 1) may have been caused by the fact that it is a Python 2 program that was built in the host configuration, which uses Python 3. You can change the host configuration (for the entire build) to instead use Python 2 by setting --host_force_python=PY2.

If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
----------------
Target //samples/container-sample/src/androidTest/java/com/squareup/container/sample/tests:container-sample-test failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

This then passed on all subsequent builds, including after a `bazel clean --expunge`, both with the default spawn strategy and the worker/local pair. 

This is the closest issue connected to it, and it kind of fits with the theme of the described issue, even though some of the symptoms are different.  Not sure if it adds anything to the analysis.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
