### ISSUE TITLE
Expose a ctx.actions.Args() buildCommandLine to starlark

### ISSUE THREAD

**Issue by mfarrugi** [bazelbuild/bazel#6888]
### Description of the feature request:

[SkylarkActionFactory.Args](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/analysis/skylark/SkylarkActionFactory.java) should expose a way to access the built command line to Starlark.

### Feature requests: what underlying problem are you trying to solve with this feature?

rules_rust has a [rule](https://github.com/bazelbuild/rules_rust/blob/3228ccd3814c2ad0d7307d2f87fb8ff9616149d7/rust/private/rustdoc_test.bzl#L60-L97) that needs to build a test script, and would benefit from using `ctx.actions.args()`. In particular, some amount of code is duplicated across other actions that are using Args.

[SkylarkActionFactory.Args#debugPrint](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/analysis/skylark/SkylarkActionFactory.java#L936) does what we want, though I'm not sure of the implications of exposing it directly.

### Any other information, logs, or outputs that you want to share?

Our usecase is _very_ similar to wanting to run an action as a test, which may be a more appropriate solution.

**Comment by benjaminp** [comment]
I think what you want to do is pass `content = some_Args_object` to `ctx.actions.write()`, which will cause the command line to be written to the file.

**Comment by mfarrugi** [comment]
Thanks for pointing that out. I didn't notice that write took an `args` object, but that api is apparently to create a parameters file. 

Using that, I could `write` the parameters file, and then `write` a script that uses it.. but that amount of indirection is much more complicated, especially if end users want to inspect the script.

**Comment by adam-azarchs** [comment]
I have a similar use case, trying to write a unit test rule which just runs a single command.  My read of the docs suggested that maybe
```starlark
args.use_param_file("#!/usr/bin/env bash\n%s\n")
args.set_param_file_format("shell")
ctx.actions.write(dest, args, executable=True)
```
would result in something usable, but, alas, it seems to be ignoring the formatting directives and using the multiline format.

**Comment by brandjon** [comment]
> but that amount of indirection is much more complicated

Indirecting through actions in some form is necessary, because in general the content of an Args object is not known at analysis time (due to directory expansion, I believe).

Since there appears to be a workaround and it'd be infeasible to implement this FR as stated, I'll close this issue.
