### ISSUE TITLE
Toolchain dependencies are all in the HOST configuration

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#6889]
__EDIT__: Sorry for the first post, misposted.
 
See https://github.com/bazelbuild/bazel/pull/5650 for more context. I am opening a bug since there is no solution yet and I need to refer to it.

### Description of the problem / feature request:

If you add a target dependencies to a toolchain, the dependency ends-up being a host dependencies in the final binary. https://github.com/bazelbuild/bazel/pull/5650 contains way more information and a fix for it.

**Comment by katre** [comment]
This is a topic I plan to look into soon, sorry that the backlog has been high.

Several other rule authors have also mentioned this issue, thanks for filing it.

**Comment by katre** [comment]
See https://groups.google.com/forum/#!topic/bazel-dev/5osWxhoF0Fk for the design to address this.

**Comment by katre** [comment]
Tracking issue for implementing toolchain transitions (finally): #10523.

**Comment by katre** [comment]
This will be fixed by #7935 and #10523, closing in favor of those issues.
