### ISSUE TITLE
Error building bazel with bazel on sled11

### ISSUE THREAD

**Issue by jcremer** [bazelbuild/bazel#689]
It worked on previous Versions, but now its broken.
On sled11 with CC=gcc-4.7 and CXX=g++-4.7:

Building Bazel with Bazel.
.WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
ERROR: /home/crem_ja/git/bazel/src/main/tools/BUILD:11:1: undeclared inclusion(s) in rule '//src/main/tools:process-tools':
this rule is missing dependency declarations for the following files included by 'src/main/tools/process-tools.c':
  '/usr/lib64/gcc/x86_64-suse-linux/4.7/include/stddef.h'
  '/usr/lib64/gcc/x86_64-suse-linux/4.7/include/stdarg.h'
  '/usr/lib64/gcc/x86_64-suse-linux/4.7/include/stdbool.h'.
Target //src:bazel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.199s, Critical Path: 0.27s

**Comment by ulfjack** [comment]
You need to update the CROSSTOOL file, if you haven't already. I think you
need to add a cxx_builtin_include_path of
'/usr/lib64/gcc/x86_64-suse-linux/4.7/', if I'm not mistaken.

**Comment by jcremer** [comment]
The following solved the problem in the toolchain configuration for local-linux
cxx_builtin_include_directory: "/usr/lib64/gcc/x86_64-suse-linux/4.7/include" # 64bit includes
cxx_builtin_include_directory: "/usr/lib64/gcc/x86_64-suse-linux/4.7/include-fixed" # 64bit includes
cxx_builtin_include_directory: "/usr/lib/gcc/i586-suse-linux/4.7/include" # 32bit includes
cxx_builtin_include_directory: "/usr/lib/gcc/i586-suse-linux/4.7/include-fixed" # 32bit includes

Additionally i had to call ./compile.sh again without the previously built 'bazel from scratch binary' as parameter

My previous modification for a working version on sled11 was based on commit I514b1352514e9e194232988722fb0a97253657c and I just added some toolchain configuration. 
Yesterday I wanted to update my fork to the current 0.1.2 release and ended up with the problem above.
