### ISSUE TITLE
Windows, CI: getting "Failed to delete output files after incomplete download"

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#6890]
### Description of the problem / feature request:

On Bazel CI, I'm repeatedly getting the following error:
```
ERROR: D:/b/bk-worker-windows-java8-w528/bazel/google-bazel-presubmit/third_party/protobuf/3.6.1/BUILD:123:1: Couldn't build file third_party/protobuf/3.6.1/_objs/protobuf_lite/stringpiece.obj: C++ compilation of rule '//third_party/protobuf/3.6.1:protobuf_lite' failed: Failed to delete output files after incomplete download. Cannot continue with local execution.: D:/b/f622aej4/execroot/io_bazel/bazel-out/host/bin/third_party/protobuf/3.6.1/_objs/protobuf_lite/stringpiece.obj (Permission denied)
--
  | Target //src:bazel failed to build
```

(https://buildkite.com/bazel/google-bazel-presubmit/builds/12883#61fdc327-7d64-4979-a3b4-9d35f2c729a2)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I don't know. I saw the error on CI for my change https://bazel-review.googlesource.com/c/bazel/+/84151.

Retrying the job doesn't seem to help.

Looks like this is where the error comes from: https://github.com/bazelbuild/bazel/blob/b3f28d3da12ea2d97d838f66765bf21d5dee2f7f/src/main/java/com/google/devtools/build/lib/remote/AbstractRemoteActionCache.java#L280-L284

And I suppose the reason is that `outErr` has open streams for stdout and stderr, and those streams should be closed before attempting to delete the files here: https://github.com/bazelbuild/bazel/blob/b3f28d3da12ea2d97d838f66765bf21d5dee2f7f/src/main/java/com/google/devtools/build/lib/remote/AbstractRemoteActionCache.java#L273-L274

### What operating system are you running Bazel on?

> Replace this line with your answer.

### What's the output of `bazel info release`?

`0.20.0`

**Comment by laurentlb** [comment]
This is blocking a Bazel release: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/695#e741bbc1-151b-479b-8af0-72bf7388150d

I'm not even able to test downstream projects with the Bazel candidate, so this can hide unrelated bugs.

**Comment by laurentlb** [comment]
If it can be fixed or worked around on Monday, we still have a chance of release Bazel before the holiday.

**Comment by laszlocsomor** [comment]
> If it can be fixed or worked around on Monday, we still have a chance of release Bazel before the holiday.

Is that what we want? Will we be around to push a patch release if the main release turns out to be bad?

**Comment by laszlocsomor** [comment]
I have a repro: https://github.com/bazelbuild/bazel/issues/6945#issuecomment-448550630

**Comment by laszlocsomor** [comment]
I'll start bisecting. Apparently this is a regression in 0.20.0, because I cannot repro the bug with 0.19.0

**Comment by laszlocsomor** [comment]
The good news is, I found the culprit: https://github.com/bazelbuild/bazel/commit/d2920e32ec7f3f8551a693d33c17b19f1b802145

The bad news is, it was a rollback of https://github.com/bazelbuild/bazel/commit/1a955020ff7a27b9d49c83aef89e0991380daa5e, which caused problems.

So we cannot be with or without this feature, i.e. of opening files with deletion-sharing on Windows.

The principled fix would be for the AbstractRemoteActionCache to close files before it tries to delete them.

**Comment by laszlocsomor** [comment]
FYI @philwo

**Comment by meteorcloudy** [comment]
Wow, thanks for debugging!

**Comment by philwo** [comment]
Note to self: Mark Google bug b/121159713 as fixed, when we fixed this to let my colleagues know when this is working again.

Discussions and progress tracking should happen here.
