### ISSUE TITLE
Disable restriction for aspect's string attrs

### ISSUE THREAD

**Issue by vmax** [bazelbuild/bazel#6892]
### Description of the problem / feature request:

Currently, `attr.string` you can put in `attrs` of `aspect` *must* have defined `values`. Why is that?
Quoting [the docs](https://docs.bazel.build/versions/master/skylark/lib/globals.html#aspect):
>Explicit attributes must have type string, and must use the values restriction

### Feature requests: what underlying problem are you trying to solve with this feature?

We at @graknlabs would like to disable that restriction because we need to pass arbitratry strings from where custom rule using aspect is placed (particularly, the `package` of that target)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try defining an aspect without `values` restriction

### What operating system are you running Bazel on?

macOS High Sierra 10.14

### What's the output of `bazel info release`?

`release 0.18.1`

**Comment by laurentlb** [comment]
cc @dslomov 
Do you know if it's feasible?

**Comment by laurentlb** [comment]
I think @dslomov said it was by design.

**Comment by dslomov** [comment]
Sorry for late reply: just created a [public copy of an internal design doc](https://docs.google.com/document/d/1vcoPqeavsXru87dgdzXsE_v7zU-0B7QLwoRmgqx_AL0/edit#).

This is from the bygone era of internal-only design docs.

**Comment by vmax** [comment]
This is no longer relevant for our usecase and given this is so by design and was assigned `P4`, I'm closing it.
