### ISSUE TITLE
Build the pip package Error

### ISSUE THREAD

**Issue by LyonOconner** [bazelbuild/bazel#6894]
hi, i trying Build the pip package using GPU support but get is error, the command is : 

### bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

WARNING: Duplicate rc file: c:\tensorflowm\tools\bazel.rc is read multiple times, most recently imported from c:\tensorflowm\.bazelrc
WARNING: Processed legacy workspace file c:\tensorflowm/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
DEBUG: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for Visual C++ through registry
DEBUG: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for default Visual C++ installation directory
DEBUG: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'PROGRAMFILES(X86)' environment variable is not set, using 'C:\Program Files (x86)' as default
DEBUG: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC
DEBUG: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for Visual C++ through registry
DEBUG: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for default Visual C++ installation directory
DEBUG: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'PROGRAMFILES(X86)' environment variable is not set, using 'C:\Program Files (x86)' as default
DEBUG: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC
DEBUG: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for Visual C++ through registry
DEBUG: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for default Visual C++ installation directory
DEBUG: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'PROGRAMFILES(X86)' environment variable is not set, using 'C:\Program Files (x86)' as default
DEBUG: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC
ERROR: no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/cc_configure.bzl", line 51
                configure_windows_toolchain(repository_ctx)
        File "C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 342, in configure_windows_toolchain
                repository_ctx.template("CROSSTOOL", paths["@bazel_tools//..."], ...}": ""})
        File "C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 359, in repository_ctx.template
                _get_escaped_windows_msys_crosstool_content(repository_ctx)
        File "C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 41, in _get_escaped_windows_msys_crosstool_content
                auto_configure_fail(("Could not determine MSYS/Cygwi...))
        File "C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 109, in auto_configure_fail
                fail(("\n%sAuto-Configuration Error:%...)))

Auto-Configuration Error: Could not determine MSYS/Cygwin root from BAZEL_SH (c:/msys64/usr/bin)
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/cc_configure.bzl", line 51
                configure_windows_toolchain(repository_ctx)
        File "C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 342, in configure_windows_toolchain
                repository_ctx.template("CROSSTOOL", paths["@bazel_tools//..."], ...}": ""})
        File "C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 359, in repository_ctx.template
                _get_escaped_windows_msys_crosstool_content(repository_ctx)
        File "C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 41, in _get_escaped_windows_msys_crosstool_content
                auto_configure_fail(("Could not determine MSYS/Cygwi...))
        File "C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 109, in auto_configure_fail
                fail(("\n%sAuto-Configuration Error:%...)))

Auto-Configuration Error: Could not determine MSYS/Cygwin root from BAZEL_SH (c:/msys64/usr/bin)
INFO: Elapsed time: 10.619s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

###How i can solved its ?? regards. help me pls... 

### What operating system are you running Bazel on?

>win 10

### What's the output of `bazel info release`?

>
bazel-bin: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/execroot/org_tensorflow/bazel-out/x64_windows-opt/bin
bazel-genfiles: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/execroot/org_tensorflow/bazel-out/x64_windows-opt/genfiles
bazel-testlogs: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/execroot/org_tensorflow/bazel-out/x64_windows-opt/testlogs
character-encoding: file.encoding = ISO-8859-1, defaultCharset = ISO-8859-1
command_log: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/command.log
committed-heap-size: 734MB
execution_root: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/execroot/org_tensorflow
gc-count: 12
gc-time: 421ms
install_base: C:/users/desarrollo/_bazel_desarrollo/install/9b4a3d8963d27679daf2ef8226ad0888
java-home: C:/Users/Desarrollo/_bazel_desarrollo/install/9b4a3d8963d27679daf2ef8226ad0888/_embedded_binaries/embedded_tools/jdk
java-runtime: OpenJDK Runtime Environment (build 9.0.7.1+1) by Azul Systems, Inc.
java-vm: OpenJDK 64-Bit Server VM (build 9.0.7.1+1, mixed mode) by Azul Systems, Inc.
max-heap-size: 3790MB
output_base: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb
output_path: C:/users/desarrollo/_bazel_desarrollo/z5b7ertb/execroot/org_tensorflow/bazel-out
package_path: %workspace%
release: release 0.18.0
repository_cache: C:/users/desarrollo/_bazel_desarrollo/cache/repos/v1
server_log: c:\users\desarrollo\_bazel_desarrollo\z5b7ertb\java.log
server_pid: 16208
used-heap-size: 130MB
workspace: C:/tensorflowm

**Comment by jin** [comment]
Hi, please open an issue on the [Tensorflow repository](https://github.com/tensorflow/tensorflow/issues) because this is a Tensorflow build issue. Thanks!
