### ISSUE TITLE
fatal error: 'ares.h' file not found

### ISSUE THREAD

**Issue by enphoneh** [bazelbuild/bazel#6898]
run bazel tensorflow/lite/python:tflite_convert with tensorflow, I got the error message below:

ERROR: /private/var/tmp/_bazel_aven/2149a6e76cf4b959657c5c8ec18bb871/external/grpc/BUILD:1515:1: C++ compilation of rule '@grpc//:grpc_resolver_dns_ares' failed (Exit 1) wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' -iquote ... (remaining 57 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/grpc/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc:23:10: fatal error: 'ares.h' file not found
#include <ares.h>
1 error generated.
Target //tensorflow/lite/python:tflite_convert failed to build
Use --verbose_failures to see the command lines of failed build steps.

how to fix it ???

**Comment by jin** [comment]
Hi, please open an issue on the [Tensorflow's repository](https://github.com/tensorflow/tensorflow/issues) because this is a Tensorflow build issue. Thanks!

**Comment by adib** [comment]
This looks like [a bug in Bazel CI system](https://github.com/tensorflow/tensorflow/issues/19464)?
