### ISSUE TITLE
 sh_binary calling sh_binary with data doesn't work

### ISSUE THREAD

**Issue by kamalmarhubi** [bazelbuild/bazel#690]
I am trying to have an `sh_binary` call another `sh_binary` that is provided as `data`. The call fails as the runfiles for the callee cannot be found. I would expect it to work given the [documentation of the sh_binary srcs attribute](http://bazel.io/docs/be/shell.html#sh_binary.srcs):

> All other files required at runtime (whether scripts or data) belong in the data attribute.

Here's an example BUILD file that illustrates the problem:

```
sh_binary(
    name = "sh1",
    srcs = ["sh1.sh"],
    data = [
        "data1",
        ":sh2"],
)

sh_binary(
    name = "sh2",
    srcs = ["sh2.sh"],
    data = ["data2"],
)
```

Complete example workspace: https://gist.github.com/kamalmarhubi/72a97c3bad0206842886
(`git clone https://gist.github.com/72a97c3bad0206842886.git`)

The output I get when trying to run sh1:

```
$ bazel run :sh1
INFO: Found 1 target...
Target //:sh1 up-to-date:
  bazel-bin/sh1
INFO: Elapsed time: 1.825s, Critical Path: 0.03s.

INFO: Running command line: bazel-bin/sh1.
Hi I'm sh1 and here's my data
sh1's data
I will call my friend sh2
Hi I'm sh2 and here's my data
cat: /home/kamal/.cache/bazel/_bazel_kamal/824705cdacd5d77678d5426eea1dda19/shtest/bazel-out/local_linux-fastbuild/bin/sh1.runfiles/sh2.runfiles/data2: No such file or directory
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

**Comment by kamalmarhubi** [comment]
And just in case,

```
$ bazel version
Build label: 0.1.2
Build target: bazel-out/local_linux-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel-main_deploy.jar
Build time: Fri Dec 4 23:13:21 2015 (1449270801)
Build timestamp: 1449270801
Build timestamp as int: 1449270801
```

**Comment by bsilver8192** [comment]
Bazel only creates one runfiles tree for the top-level binary (sh1), but your code is looking under a separate tree for sh2. Binaries are supposed to look under their current directory for runfiles. Changing the RUNFILES variable in sh2 to RUNFILES=. makes your example work for me.

sh1 should have RUNFILES=. too, but it doesn't need to be for this particular example.
