### ISSUE TITLE
No way to populate host.cppCompiler when host_crosstool_top is specified

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#6900]
### Description of the problem / feature request:

When `--host_crosstool_top` is specified, there is no way to populate cppCompiler to result in a match with a specified compiler key in a `cc_toolchain_suite.toolchains` dictionary attribute. This means that host crosstools cannot switch toolchains between compilers, only cpus.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build with a `cc_toolchain_suite` with a `toolchains` attribute of `{cpu}|{compiler}` having specified that target with `--host_crosstool_top`. For current bazel, with `--incompatible_disable_cc_toolchain_label_from_crosstool_proto` now defaulting to true, an error message is printed every time indicating a missing toolchain for the CPU (but not for the compiler, since it is null from the host CppOptions).

### What operating system are you running Bazel on?

ubuntu 18.04

### What's the output of `bazel info release`?

0.20.0

**Comment by jin** [comment]
@scentini could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?

**Comment by scentini** [comment]
I added a `--host_compiler` option which can be used alongside `--host_crosstool_top` to specify the compiler for the host configuration. Bazel 0.23 supports this option, so I am marking this as resolved.
