### ISSUE TITLE
Remove the legacy `.proto.` provider

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#6901]
We now have the `ProtoInfo` provider, which is its modern version.

A flag needs to be added that disables `ctx.dep.proto.` and all uses need to be migrated to `ctx.dep[ProtoInfo]`.

**Comment by ittaiz** [comment]
Is ProtoInfo documented? Does it replace also the sources provider?

**Comment by lberki** [comment]
What's the sources provider?

**Comment by ittaiz** [comment]
https://github.com/bazelbuild/bazel/issues/3701

**Comment by lberki** [comment]
`[ProtoInfo]` is the same provider as `.proto` indeed. It's even the same implementation and all. Mind you, it's somewhat broken and we should totally fix it some day, but it's broken in the same way as `.proto` is broken so the migration should consist solely of replacing `.proto` with `[ProtoInfo]`.

**Comment by laurentlb** [comment]
Related to https://github.com/bazelbuild/bazel/issues/7347

I don't think we should special case `.proto`. We should have a flag to forbid all the old style providers.

**Comment by lberki** [comment]
If you are willing to take that big a step...

**Comment by Bocete** [comment]
Are there plans to make `ProtoInfo` instantiable by users? If so, is there an ETA? Currently, the [ProfoInfo constructor isn't callable](https://groups.google.com/forum/#!msg/bazel-dev/AZUkYcBQx2g/1aHZ3j3VCgAJ).

I understand that `ProtoInfo` has some [legacy muck that would be a bit dangerous if exposed to users](https://github.com/protocolbuffers/protobuf/pull/6163#issuecomment-499855766). But perhaps it could be made work when specifying non-legacy fields only? Maybe that's possible, maybe it isn't; I'm not familiar with the inner workings of that provider.

Thanks! I'd love to contribute to make this happen if you think it's the right thing to do, and you're only strapped for cycles.

**Comment by hlopko** [comment]
Why do you need to instantiate the provider? That would typically make sense when creating your own iproto_library, and in that case I'd prefer to improve existing proto_library.

**Comment by hlopko** [comment]
Ah now I see your comment on https://github.com/protocolbuffers/protobuf/pull/6163#issuecomment-505184402. That's a very complicated usecase that I don't understand :)

You write you "suspect" that this will help you, or maybe the Proto sandwich would. I think of sandwich API as not a way to call native.proto_library, but a way to register the same actions as proto_library would. Can you maybe simplify the usecase so I can understand it and maybe we'll come up with a way forward?

**Comment by brandjon** [comment]
>> I don't think we should special case .proto. We should have a flag to forbid all the old style providers.
>
> If you are willing to take a step that's that big...

I'd love to remove legacy struct providers this year, not sure whether it'll happen. In the meantime, if a flag helps the proto rules migrate off legacy structs, that's fine; I took the same approach in `--incompatible_disallow_legacy_py_provider`.

Triaging to the Build API team.
