### ISSUE TITLE
Loading phase errors are swallowed in `BuildViewTestCase`

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#6902]
Reproduction:

```
@Test
public void testMissingPackage() throws Exception {
  getConfiguredTarget("//a:a");
}
```

Run this test case, observe that the test case passes, even though `a/BUILD` doesn't exist anywhere.

This is usually not a problem because we usually do something with its return value, which is null and thus a `NullPointerException` would result, but it's still an ugly misfeature of our test framework.

**Comment by jin** [comment]
@lberki in the future, please also add either the `untriaged` or a priority label, so we can get a sense of the issues' priority. thanks!

**Comment by philwo** [comment]
I have no idea about our Java tests, assigning to team-Core instead.

**Comment by katre** [comment]
Closed for lack of activity. Please ping the reviewers to reopen if this is still a problem.
