### ISSUE TITLE
Host header in --remote_http_cache https contains port

### ISSUE THREAD

**Issue by kellycampbell** [bazelbuild/bazel#6906]
### Description of the problem / feature request:

`--remote_http_cache` option with an https url appends the port (:443) to the `Host:` header in the request.

This can cause weird issues for servers that match on the host header for determining how to route the request.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Setup local or other https server that can output raw headers.

`bazel build --remote_http_cache=https://foo.bar.com/ target...`

The request will have:

`Host: foo.bar.com:443`

I expected it to have 

`Host: foo.bar.com`

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 0.20.0

**Comment by kellycampbell** [comment]
I should have checked the RFCs first... looks like port is allowed. 
https://tools.ietf.org/html/rfc7230#section-5.4

I don't think the port is added by most browsers unless it's specified in the url though. Chrome seems to remove the port if you enter https://foo.bar.com:443/ 

So this could be handled better both in bazel and the server I was experiencing this on (https://github.com/datawire/ambassador). I will follow up with the ambassador team.

**Comment by buchgr** [comment]
@kellycampbell let's fix it in Bazel too. Would you like to send a patch? :-)

**Comment by kellycampbell** [comment]
> @kellycampbell let's fix it in Bazel too. Would you like to send a patch? :-)

Already did. See #6922
