### ISSUE TITLE
incompatible_use_aapt2_by_default: Enable Bazel to use aapt2 by default

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#6907]
Tracking issue for the incompatible change to switch Bazel to use aapt2 by default.

FR issue: https://github.com/bazelbuild/bazel/issues/4103

To switch between aapt versions, Bazel uses the following in order of precedence:

1) Value of `--android_aapt` flag.
2) Value of `aapt_version` attribute in the `android_binary` and `android_local_test` target.
3) `--incompatible_use_aapt2_by_default`: false -> aapt, true -> aapt2.

To resolve issues when migrating your app to build with aapt2, see https://developer.android.com/studio/command-line/aapt2#aapt2_changes

**Comment by jin** [comment]
The flag is now in master.

**Comment by jin** [comment]
The incompatible change flag is expected to enter Bazel 0.22.

**Comment by dslomov** [comment]
when are you planning to flip the flag?

**Comment by jin** [comment]
@dslomov 0.23.

**Comment by jin** [comment]
Updated plan to flip the flag in 0.24. We are delaying this by one release because of a pending bug fix in 0.23 for android_local_test targets to correctly recognize the aapt version selection.

**Comment by jin** [comment]
Discovered an issue where building an android_library with `--android_aapt=aapt2` causes Bazel to still register an resource validation action that uses aapt.

**Comment by katre** [comment]
This issue was tagged as "breaking-change-0.24" but does not appear ready to be flipped in the [0.24.0 release](https://github.com/bazelbuild/bazel/issues/6968). If this is incorrect please comment on that issue and discuss with me.

**Comment by jin** [comment]
@katre Thanks for updating, and yes, it's still blocked on an internal change.

**Comment by dkelmer** [comment]
Seems like the flag still wasn't flipped for 0.25. Changing to 0.26

**Comment by jin** [comment]
This flag is scheduled to be flipped on September first, the end of the current stability window.
