### ISSUE TITLE
Clean up `//external` namespace

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/bazel#6917]
Bazel's virtual package `//external` provides a namespace combining different kinds of targets, including the following.

- The external repositories as repository rule plus argument as `//external:<name>`; these are not the targets provided by that external repository.These targets seems like an implementation details leaking to the interface.

- Actual build targets bound to these positions via the `bind` repository rule.

This combination of different rule classes in a single name space causes confusion (see, e.g., #6725). We should aim for a semantics of that virtual package that is at least easy to understand.

**Comment by aehlig** [comment]
> Is this the issue that causes new_git_repository to incorrectly
> add "external" to the build_file path?

No.

In your example, the problem is that the expansion of label arguments
(and the build_file) is a label argument, is happening in a surprising
context, that of the external repository. What you probably had in mind
would be specified as `build_file="@//bazel/pkg:googleapis.BUILD"`,
assuming there is a `BUILD` file in the directory `bazel/pkg` of
your top-level repository.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
