### ISSUE TITLE
Rewrite cc_configure

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#6926]
Current cc_configure is greatly suboptimal:

* It doesn't follow standard gnu env variables for customization (https://github.com/bazelbuild/bazel/issues/5186).
* It doesn't support the same env variables between linux/mac/windows
* It's not even using the same logic between linux/mac/windows.
* It's not unit/integration tested  (https://docs.google.com/document/d/1oilIxMGYuN1HgWouvGDYqjrZLtcRfyoWv3eIlXIgasY/edit?ts=5c06470d#)
* It's using legacy fields/crosstool in proto, we will need it to be in Starlark
* It prefers gcc over clang
* It doesn't support thinlto/modules
* It's not always used (e.g. freebsd has a separate static toolchain, //tools/cpp:CROSSTOOL is another static one we use).
* Ideally we'd have CUDA support (https://github.com/bazelbuild/bazel/issues/6578).

**Comment by PiotrSikora** [comment]
It should also include the ability to easily switch between GNU libstdc++ and LLVM libc++.

Currently, this requires either:
- [changes to unix_cc_configure.bzl](https://github.com/bazelbuild/bazel/pull/7074/files),
- [custom cc_wrapper replacing -lstdc++ with -lc++](https://github.com/envoyproxy/envoy/pull/5563/files) for each invocation.

I think this problem falls into overall theme of this issue, but please let me know if I should open a separate issue to track this. Thanks!

**Comment by htuch** [comment]
Some earlier context on libc++ and Linux at https://github.com/bazelbuild/bazel/issues/4524

**Comment by hlopko** [comment]
@PiotrSikora and @htuch - is passing `BAZEL_LINKOPTS="--stdlib=libc++:-lc++"` not enough to use libc++? I think it works, at least on linux.

**Comment by PiotrSikora** [comment]
@hlopko you need to pass `-stdlib=libc++` to the compiler (hence [`BAZEL_CXXOPTS`](https://github.com/bazelbuild/bazel/pull/7074/files)), otherwise you'll include C++ headers from libstdc++ and not libc++.

**Comment by PiotrSikora** [comment]
> Yup. you're right. All of this is doable with Bazel today.

I wanted to verify that `BAZEL_CXXOPTS` can be set in `.bazelrc` using `--action_env`, so I updated Bazel to 0.23rc1, and even though `local_config_cc/cc_toolchain_config.bzl` is generated correctly and includes proper `cxx_builtin_include_directories`, `cxx_flags` and `link_flags`, it appears that libc++ builds are completely broken in 0.23rc1.

Perhaps `cxx_builtin_include_directories` are not included in the sandbox?
```
fatal error: 'string' file not found
#include <string>
```

Tests to catch any regressions there would be great.

> Is this enough for you, or you'd want an ability to switch it more easily than that?

Personally, I'm fine with adding a few lines to `.bazelrc` to enable `--config=libc++` myself, though it would be great if it just worked out of the box :)

@htuch @jmillikin-stripe Do you guys have any opinion on that? The two of you are a bit more pedantic, when it comes to the build system, than I am.

**Comment by hlopko** [comment]
`cxx_builtin_include_directories` are only for .d file validation, if you need to add those directories and their contents to the sandbox, you have to update filegroups in `cc_toolchain` target. Does that help?

**Comment by PiotrSikora** [comment]
@hlopko the same build works fine with Bazel 0.22, so I doubt it's something that fundamental.

Any chance you could take a look at it? The [build instructions](https://github.com/envoyproxy/envoy/blob/master/bazel/README.md#linking-against-libc-on-linux) are pretty easy.

**Comment by hlopko** [comment]
Hi Piotr,

could you pls check if its https://github.com/bazelbuild/bazel/issues/7397? I'd build bazel at https://github.com/bazelbuild/bazel/commit/71bc38fe2d165fe523b19d7879096d3fdd2086fc and then one commit before and see if it's the culprit. If so, pls comment on the issue. Thanks so much!

**Comment by PiotrSikora** [comment]
@hlopko sorry, it appears that there was a change that [broke local builds with libc++](https://github.com/envoyproxy/envoy/pull/5875/files#r256319464) in our build system committed at the time when I was testing 0.23rc1, and after reverting it 0.23rc1 seems to work fine. Sorry for the noise!

**Comment by keith** [comment]
Here's another use case that would be nice to cover so that users can override some pieces of the toolchain, without having to create their own crosstool https://github.com/bazelbuild/bazel/pull/7883

**Comment by hlopko** [comment]
From email threads:

* MSVC: SDK version selection - have an ability specify which version of the sdk to use.
* ARM64 on Windows - cover this platform as well.

**Comment by ccontavalli-j** [comment]
Also consider environments where multiple compilers may be available and necessary to build different targets. For example, having a dependency on a library that can only be built with gcc, and a different library that can only be built with clang.

A way to do this would be to extend cc_configure and/or cc_autoconf.* to take parameters, so one can specify a path for the compiler to use, for example, and the name of the toolchain to create. 

Those parameters can be filled in by default from environment variables, or detection code, but you can leave the option to call cc_configure() with the correct parameters to use of bazel to simplify the detection and creation of multiple toolchains.

See also: https://github.com/bazelbuild/bazel/issues/7020

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
