### ISSUE TITLE
Make use of cc_toolchain.ar_files and cc_toolchain.as_files

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#6928]
These attributes are currently unused. They should be used for c++-link-static-library and for assembly actions (currently all_files are used).

**Comment by benjaminp** [comment]
The existence of these fields seems contrary to the general migration of crosstools away from hardcoding knowledge of specific tools in favor of specifying everything in generic action configs.

With Starlark crosstools, wouldn't it be possible to specify the required files for a tool directory in the tool action config?

**Comment by hlopko** [comment]
Yup, https://github.com/bazelbuild/bazel/issues/7746 is also relevant for this. I still see it as a long term goal to unify concepts in this are, but I don't think removing of `cc_toolchain` attributes will happen any time soon. This issue is a small and quick fix that will enable people to speed up archiving and assembly actions (when using sandbox or remote execution where action inputs setup is not negligible).
