### ISSUE TITLE
docker_build: base layer permissions on directories should be respected when adding files

### ISSUE THREAD

**Issue by kamalmarhubi** [bazelbuild/bazel#693]
In my particular use case, I'm creating a link under `/tmp` which exists with `1777` in the base layer. The outcome is that `/tmp` has a mode of `0755`, and so is not really usable.

**Comment by kamalmarhubi** [comment]
Example repo illustrating issue: https://github.com/kamalmarhubi/bazel-issue-693


```
kamal@kx:/tmp/bazel-modes-bug$ bazel build :all
INFO: Found 3 targets...
INFO: Elapsed time: 5.624s, Critical Path: 4.24s.
kamal@kx:/tmp/bazel-modes-bug$ tar tvf bazel-bin/img.layer
drwxrwxrwt 0/0               0 1969-12-31 19:00 ./a-dir/
-rw-r--r-- 0/0               0 1969-12-31 19:00 ./a-dir/a-file
-rw-r--r-- 0/0               0 1969-12-31 19:00 ./a-file-at-root
$ tar tvf bazel-bin/img-with-link.layer                                                                                                                                          
drwxr-xr-x 0/0               0 1969-12-31 19:00 ./
drwxr-xr-x 0/0               0 1969-12-31 19:00 ./a-dir/
lrwxr-xr-x 0/0               0 1969-12-31 19:00 ./a-dir/a-file-link -> a-file-at-root
$ tar tvf bazel-bin/img-with-another-file.layer                                                                                                                                       
drwxr-xr-x 0/0               0 1969-12-31 19:00 ./
drwxr-xr-x 0/0               0 1969-12-31 19:00 ./a-dir/
-r-xr-xr-x 0/0               0 1969-12-31 19:00 ./a-dir/another-file
```

In both the derived images, the directory `a-dir` overrides the permissions in the base layer.

**Comment by kamalmarhubi** [comment]
Likely relevant comment:
```
            # Add root dir with same permissions if missing. Note that
            # add_file deduplicates directories and is safe to call here.
```

https://github.com/bazelbuild/bazel/blob/b94713e8f83ef4dad4a6611411d93eadbcc4c95f/tools/build_defs/pkg/archive.py#L351-L352

**Comment by kamalmarhubi** [comment]
This doesn't happen when using `pkg_tar` and `deps` in place of `docker_build` and `base` because the call to `build_tar` is flattening all tars. The directory entry exists with the correct permissions, and so the deduplication mentioned above actually works. For `docker_build` and `base`, the directory entry does not exist, and so it is created with the same permissions as the added file and the image layering gives the bad state at the end.

**Comment by kamalmarhubi** [comment]
Possible solution: add another action that creates a file that tracks the directory structure. This could then be propagated down through dependent rules. There would need to be a way to actually change the mode on a directory when it's the desired state. Likely #692 would help here.

**Comment by damienmg** [comment]
Closing, please reopen on bazelbuild/docker_rules if this is still an issue.
