### ISSUE TITLE
Please add Label attribute for the workspace name

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel#6941]
`Label` has an attribute `workspace_root` such that `Label("@some_repo//foo") == "external/some_repo"`. It would be nice if there was a similar property for just the unprefixed name, so that calculation of paths in .runfiles doesn't need to assume that the execution tree always puts repositories under `external/`.

current code (from [rules_bison](https://github.com/jmillikin/rules_bison/blob/73d578eb65f5de696c15902d1eb89b83e25a4261/bison.bzl#L105-L109)):
```python
    workspace_root = ctx.attr.bison.label.workspace_root
    pkgdatadir = "{}.runfiles/{}/data".format(
        ctx.executable.bison.path,
        workspace_root[len("external/"):],
    )
```

desired code:
```python
    pkgdatadir = "{}.runfiles/{}/data".format(
        ctx.executable.bison.path,
        ctx.attr.bison.label.workspace_name,
    )
```

### What's the output of `bazel info release`?

`release 0.20.0`

**Comment by ittaiz** [comment]
+1
