### ISSUE TITLE
Windows: Failed to delete output files after incomplete download (Remote caching)

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#6945]
TensorFlow build: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/699#19656e7b-76fc-4e06-962b-05abf0a95711
Bazel build: https://buildkite.com/bazel/bazel-bazel/builds/5942#d69b94ce-e62a-4ff6-8c33-370785c3c5ea
We are getting errors like:
```
ERROR: D:/b/dtlxcnct/external/com_google_absl/absl/base/BUILD.bazel:119:1: Couldn't build file external/com_google_absl/absl/base/_objs/base/cycleclock.obj: C++ compilation of rule '@com_google_absl//absl/base:base' failed: Failed to delete output files after incomplete download. Cannot continue with local execution.: D:/b/dtlxcnct/execroot/org_tensorflow/bazel-out/_tmp/action_outs/stderr-2843-0 (Permission denied)
```

This is probably caused by trying to delete the file before closing the file after the incomplete download.
/cc @buchgr

**Comment by buchgr** [comment]
@laszlocsomor has a fix: https://github.com/bazelbuild/bazel/pull/6946/files

**Comment by laszlocsomor** [comment]
Sorry, I'm not sure it actually fixes the bug.

I should've made that clear in the PR's description.

I don't know how to repro the issue and how to test my fix.

**Comment by meteorcloudy** [comment]
This issue is blocking our downstream pipeline: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/701

**Comment by meteorcloudy** [comment]
This time is the actual output file of the action failed, so @laszlocsomor 's PR may not fix it.
```
ERROR: D:/b/bhsmqyd3/external/com_google_protobuf/BUILD.bazel:123:1: Couldn't build file external/com_google_protobuf/_objs/protobuf_lite/structurally_valid.obj: C++ compilation of rule '@com_google_protobuf//:protobuf_lite' failed: Failed to delete output files after incomplete download. Cannot continue with local execution.: D:/b/bhsmqyd3/execroot/io_bazel/bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/structurally_valid.obj (Permission denied)
```

**Comment by laszlocsomor** [comment]
@meteorcloudy : that exception could have come from either of these places:
https://github.com/bazelbuild/bazel/blob/0fbbb253b643b301205ee46fc015227b2fc7b6e7/src/main/java/com/google/devtools/build/lib/remote/AbstractRemoteActionCache.java#L265
https://github.com/bazelbuild/bazel/blob/0fbbb253b643b301205ee46fc015227b2fc7b6e7/src/main/java/com/google/devtools/build/lib/remote/AbstractRemoteActionCache.java#L270

**Comment by laszlocsomor** [comment]
@buchgr , which object owns the OutputStreams? Is there a way to find and close all of them?

**Comment by laszlocsomor** [comment]
> @buchgr , which object owns the OutputStreams? Is there a way to find and close all of them?

I guess we also had to cancel outstanding downloads so that parallel download threads wouldn't try to write to the closed streams. Either that, or use custom streams that tolerate writing to them when closed. (And maybe open files with deletion sharing?)

**Comment by laszlocsomor** [comment]
I'll throw together a toy remote cache and simulate a failed download with that, to try and repro this issue.

**Comment by meteorcloudy** [comment]
In the mean time, I'll disable remote caching on Windows for now to unblock Google bazel presubmit

**Comment by laszlocsomor** [comment]
Using @buchgr 's remote cache (https://github.com/buchgr/bazel-remote), I managed to repro this issue locally: https://github.com/laszlocsomor/projects/tree/a661668237e369ebb2179546395e43b62494ddb5/bazel/gh-6945-remote-cache-failed-to-delete-partial-files

**Comment by laszlocsomor** [comment]
I'll close this bug in favor of https://github.com/bazelbuild/bazel/issues/6890. They are duplicates.
