### ISSUE TITLE
docker sandbox docker flags

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel#6953]
### Description of the problem / feature request:

I am just testing the docker sandbox to be able to connect to another service within docker on circleci, see: https://circleci.com/docs/2.0/building-docker-images/#accessing-services

The tests start to run fine in the container but I can not connect to the service because I can not seem to be able to specify the `--network` flag.

### Feature requests: what underlying problem are you trying to solve with this feature?

I want to be able to connect to a service running in another container for integration tests

### What operating system are you running Bazel on?

Elementary OS 5.0 (Ubuntu 18.04)

### What's the output of `bazel info release`?

release 0.21.0rc2

###  Have you found anything relevant by searching the web?

Not really.

**Comment by jmmv** [comment]
Could you elaborate a bit more about what would help you here? Where/how would you specify that `--network` flag?

**Comment by Globegitter** [comment]
@jmmv sorry for the long silence. It would be some generic bazel flag like all the other docker options/flags. Right now I can specify the docker sandbox strategy via flags like `--experimental_docker_image=...`, `--spawn_strategy=docker`, `--experimental_enable_docker_sandbox`, `--experimental_docker_verbose` etc. It would be great to be able to further customize this, probably with some additional flags. Either something very generic which allows me to pass any flags to docker, e.g.  `--experimental_docker_run_flags="--network somenetwork", or more specifically for this case `--experimental_docker_network=...`.

And then bazel would pass this flag on to docker, in the same way as it passes on the image specified with `--experimental_docker_image`.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
