### ISSUE TITLE
Prevent falling back to unsandboxed execution

### ISSUE THREAD

**Issue by mboes** [bazelbuild/bazel#6957]
### Description of feature request:

Sandboxing is enabled by default on Darwin and Linux. I can be explicit about turning on sandboxing by passing `--strategy=Genrule=sandbox` and the like. It should be possible to demand that Bazel use a sandbox or _fail_ the build if it cannot.

### Feature requests: what underlying problem are you trying to solve with this feature?

If Bazel thinks the host doesn't support sandboxing, then it _silently_ turns it off, even when flags to turn it on are passed explictly on the command-line. This is confusing, because it's hard to know when the sandbox really is being used. Sometimes Bazel incorrectly determines that sandboxing is not supported on a platform. It would be good to have an option to make Bazel very pedantic about sandboxes, i.e. to have it fail the build if it expectations cannot be met.

### What operating system are you running Bazel on?

NixOS (Linux).

### What's the output of `bazel info release`?

0.20.0

**Comment by jmmv** [comment]
I think there are two separate cases here:

1. You request sandboxing; Bazel determines sandboxing is not possible on the current host; the action runs without a sandbox. This is the case you describe and I agree it would be good to not fail silently.

1. You request sandboxing; some action wants to run without sandboxing; Bazel runs the action without a sandbox. What should we do here? I can see value in either of these approaches: one is "I want to ensure the whole build is sandboxed", but another one is "I want the whole build sandboxed, except for the corner cases that cannot be and are declared as such". Maybe we need to support both?

**Comment by larsrc-google** [comment]
Isn't this fixed by the new execution strategy described in https://blog.bazel.build/2019/06/19/list-strategy.html?

**Comment by larsrc-google** [comment]
There is now a flag `--incompatible_legacy_local_fallback` that controls whether to do this fallback. It defaults to true for now. The case 2. above is best handled by setting your strategies appropriately - if it's more important that you build than that it's sandboxed, set --spawn_strategy=sandboxed,local (and --strategy similarly for mnemonics you otherwise set that for).
