### ISSUE TITLE
Java sandwich API may not preserve java.library.path

### ISSUE THREAD

**Issue by brown** [bazelbuild/bazel#6958]
### Description of the problem / feature request:

When the Java sandwich API is used, transitive dependencies on native shared libraries appear to
be affected.  The native libraries appear in the runfiles tree, but they do not generate
-Djava.library.path entries in the created java_binary wrapper script.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Use the sandwich API and depend on a java_library with native shared library dependencies.
In turn have a java_binary that depends on the entity created by the sandwich rule.  The binary
will be missing java.library.path settings for the native libs.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

Bazel 20

**Comment by lberki** [comment]
My guess: the place where we collect native libraries:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/java/NativeLibraryNestedSetBuilder.java#L59

does not handle the `JavaInfo` provider so it's not entirely surprising.

What are you using Java native library support for? TBH, we haven't given it a lot of attention (at least in Bazel) so I'd not be surprised if it didn't work very well.

**Comment by brown** [comment]
We have Java libraries that dynamically load native C libraries and we use the sandwich API to modify the compile time and run time Java classpath in order to exclude unwanted dependencies.  For instance, a developer might want to exclude Guava version 22 from the classpath of an application when it depends on a collection of libraries that collectively depend on both Guava 22 and Guava 25.  More information is available in my comments here:  https://github.com/bazelbuild/bazel/issues/5821

I have submitted a pull request to improve handling of native libraries but I don't think anyone has taken a look at it:  https://github.com/bazelbuild/bazel/pull/7042

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
