### ISSUE TITLE
Invalid attribute in a dependency file

### ISSUE THREAD

**Issue by vagnercazarotto** [bazelbuild/bazel#6966]
### Description of the problem / feature request:

Hi guys, my application is using a bazel dependency and it crash because we have an invalid attribute in fragment_billing_address_detail.xml

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm trying to do a signed APK for Android

### What operating system are you running Bazel on?

macos 10-13-6

### What's the output of `bazel info release`?
Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #1

        at com.android.ide.common.workers.ExecutorServiceAdapter.close(ExecutorServiceAdapter.kt:56)

        at kotlin.io.CloseableKt.closeFinally(Closeable.kt:65)

        at com.android.build.gradle.tasks.VerifyLibraryResourcesTask.compileAndVerifyResources(VerifyLibraryResourcesTask.kt:150)

        at com.android.build.gradle.tasks.VerifyLibraryResourcesTask.doFullTaskAction(VerifyLibraryResourcesTask.kt:129)

        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:106)

        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)

        ... 40 more

Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed

Output:  /Users/crispybacon020/Desktop/YAP/payx-android/datamanager/build/intermediates/res/merged/prod/release/layout/fragment_billing_address_detail.xml:10: error: attribute layout_constraintEnd_toEndOf (aka it.nexi.yap.datamanager:layout_constraintEnd_toEndOf) not found.

/Users/crispybacon020/Desktop/YAP/payx-android/datamanager/build/intermediates/res/merged/prod/release/layout/fragment_billing_address_detail.xml:10: error: attribute layout_constraintStart_toStartOf (aka it.nexi.yap.datamanager:layout_constraintStart_toStartOf) not found.

/Users/crispybacon020/Desktop/YAP/payx-android/datamanager/build/intermediates/res/merged/prod/release/layout/fragment_billing_address_detail.xml:10: error: attribute layout_constraintTop_toTopOf (aka it.nexi.yap.datamanager:layout_constraintTop_toTopOf) not found.

/Users/crispybacon020/Desktop/YAP/payx-android/datamanager/build/intermediates/res/merged/prod/release/layout/fragment_billing_address_detail.xml:19: error: attribute layout_constraintEnd_toEndOf (aka it.nexi.yap.datamanager:layout_constraintEnd_toEndOf) not found.

/Users/crispybacon020/Desktop/YAP/payx-android/datamanager/build/intermediates/res/merged/prod/release/layout/fragment_billing_address_detail.xml:19: error: attribute layout_constraintStart_toStartOf (aka it.nexi.yap.datamanager:layout_constraintStart_toStartOf) not found.

/Users/crispybacon020/Desktop/YAP/payx-android/datamanager/build/intermediates/res/merged/prod/release/layout/fragment_billing_address_detail.xml:19: error: attribute layout_constraintTop_toBottomOf (aka it.nexi.yap.datamanager:layout_constraintTop_toBottomOf) not found.

/Users/crispybacon020/Desktop/YAP/payx-android/datamanager/build/intermediates/res/merged/prod/release/layout/fragment_billing_address_detail.xml:28: error: attribute layout_constraintEnd_toEndOf (aka it.nexi.yap.datamanager:layout_constraintEnd_toEndOf) not found.

/Users/crispybacon020/Desktop/YAP/payx-android/datamanager/build/intermediates/res/merged/prod/release/layout/fragment_billing_address_detail.xml:28: error: attribute layout_constraintStart_toStartOf (aka it.nexi.yap.datamanager:layout_constraintStart_toStartOf) not found.

/Users/crispybacon020/Desktop/YAP/payx-android/datamanager/build/intermediates/res/merged/prod/release/layout/fragment_billing_address_detail.xml:28: error: attribute layout_constraintTop_toBottomOf (aka it.nexi.yap.datamanager:layout_constraintTop_toBottomOf) not found.

/Users/crispybacon020/Desktop/YAP/payx-android/datamanager/build/intermediates/res/merged/prod/release/layout/fragment_billing_address_detail.xml:37: error: attribute layout_constraintBottom_toBottomOf (aka it.nexi.yap.datamanager:layout_constraintBottom_toBottomOf) not found.

/Users/crispybacon020/Desktop/YAP/payx-android/datamanager/build/intermediates/res/merged/prod/release/layout/fragment_billing_address_detail.xml:37: error: attribute layout_constraintEnd_toEndOf (aka it.nexi.yap.datamanager:layout_constraintEnd_toEndOf) not found.

/Users/crispybacon020/Desktop/YAP/payx-android/datamanager/build/intermediates/res/merged/prod/release/layout/fragment_billing_address_detail.xml:37: error: attribute layout_constraintStart_toEndOf (aka it.nexi.yap.datamanager:layout_constraintStart_toEndOf) not found.

/Users/crispybacon020/Desktop/YAP/payx-android/datamanager/build/intermediates/res/merged/prod/release/layout/fragment_billing_address_detail.xml:37: error: attribute layout_constraintStart_toStartOf (aka it.nexi.yap.datamanager:layout_constraintStart_toStartOf) not found.

/Users/crispybacon020/Desktop/YAP/payx-android/datamanager/build/intermediates/res/merged/prod/release/layout/fragment_billing_address_list.xml:10: error: attribute layout_constraintBottom_toTopOf (aka it.nexi.yap.datamanager:layout_constraintBottom_toTopOf) not found.

/Users/crispybacon020/Desktop/YAP/payx-android/datamanager/build/intermediates/res/merged/prod/release/layout/fragment_billing_address_list.xml:10: error: attribute layout_constraintEnd_toEndOf (aka it.nexi.yap.datamanager:layout_constraintEnd_toEndOf) not found.

/Users/crispybacon020/Desktop/YAP/payx-android/datamanager/build/intermediates/res/merged/prod/release/layout/fragment_billing_address_list.xml:10: error: attribute layout_constraintStart_toStartOf (aka it.nexi.yap.datamanager:layout_constraintStart_toStartOf) not found.

/Users/crispybacon020/Desktop/YAP/payx-android/datamanager/build/intermediates/res/merged/prod/release/layout/fragment_billing_address_list.xml:10: error: attribute layout_constraintTop_toTopOf (aka it.nexi.yap.datamanager:layout_constraintTop_toTopOf) not found.

/Users/crispybacon020/Desktop/YAP/payx-android/datamanager/build/intermediates/res/merged/prod/release/layout/fragment_billing_address_list.xml:19: error: attribute layout_constraintBottom_toBottomOf (aka it.nexi.yap.datamanager:layout_constraintBottom_toBottomOf) not found.

/Users/crispybacon020/Desktop/YAP/payx-android/datamanager/build/intermediates/res/merged/prod/release/layout/fragment_billing_address_list.xml:19: error: attribute layout_constraintEnd_toStartOf (aka it.nexi.yap.datamanager:layout_constraintEnd_toStartOf) not found.

/Users/crispybacon020/Desktop/YAP/payx-android/datamanager/build/intermediates/res/merged/prod/release/layout/fragment_billing_address_list.xml:19: error: attribute layout_constraintHorizontal_chainStyle (aka it.nexi.yap.datamanager:layout_constraintHorizontal_chainStyle) not found.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

**Comment by jin** [comment]
This does not seem like a bug in Bazel, but a bug in your resource dependencies. Could you please provide a minimal example so I can reproduce this?

**Comment by vagnercazarotto** [comment]
Hi Jin, 
You was right it was a dependency but since it was a 3rd party lib it was quite difficult to figure it out.
Anyway, thank you for the hep.
