### ISSUE TITLE
Feature request: dependency's workspace deps using that dependency's workspace.

### ISSUE THREAD

**Issue by michaelsafyan** [bazelbuild/bazel#6969]
If there is a dependency like:

```
         [repo2] ---- depends on ----> [repo1]  ------- depends on ----> [ext]
````

With "@repo2//some:target" depending on "@repo1//some/other:target" and "@repo1//some/other:target" depending on "@ext//yet/another/target", why on earth does the WORKSPACE of `repo2` need to mention `ext`? This model is very fragile and it means that this kind of chain of dependencies can *by pure coincidence* work well until some downstream dependency has added a new dependency, necessitating the creating of a workspace *.bzl file that needs to be loaded and percolated up into all downstream dependencies. That repo2 needs to express indirect dependencies is rather frustrating.

While it should not be permitted to include multiple conflicting versions of the same dependency, if a dependency hasn't been declared and it isn't an explicit dependency, it would be helpful of Bazel would just accept the depenendency provided by the dependent workspace rather than requiring the main WORKSPACE to redeclare all of these dependencies.

The current behavior makes it unreasonably difficult to split projects across multiple dependencies; I know that isn't the typical scenario at Google, but developing in small, focused repositories should be possible with Bazel. It shouldn't be necessary to be an expert on Bazel who is writing bazel build rules for a living in order to compose a build rule spanning multiple repositories, but the handling of transitive dependencies across workspaces is making it feel like that is the case.

**Comment by jin** [comment]
This is known as the recursive workspace problem. https://github.com/bazelbuild/proposals/blob/master/designs/2018-11-07-design-recursive-workspaces.md

See [design doc](https://github.com/bazelbuild/proposals/blob/master/designs/2018-11-07-design-recursive-workspaces.md) and the [mailing list discussion](https://github.com/bazelbuild/proposals/blob/master/designs/2018-11-07-design-recursive-workspaces.md).

cc @aehlig

**Comment by petroseskinder** [comment]
The discussion forum would be the most appropriate route. Thats generally
where design debates occur

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by jin** [comment]
This is addressed by bzlmod.
