### ISSUE TITLE
Cpp encyclopedia entries (and probably others) have broken anchor links

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#697]
E.g., http://bazel.io/docs/be/c-cpp.html has "Make" variable link that points to http://bazel.io/docs/be/c-cpp.html#make_variables.

**Comment by davidzchen** [comment]
I am currently working on fixing this as well as other links in the embedded documentation that are currently broken.

**Comment by hanwen** [comment]
seems to work now.

**Comment by davidzchen** [comment]
Yes, this was fixed by bf642fa0d9f3c5ece48350a471bdd4dc3d2d4f61.
