### ISSUE TITLE
Compiles with GCC 4.8.3 but find the headers under GCC 5 and reports an error

### ISSUE THREAD

**Issue by dMokaMoka** [bazelbuild/bazel#6971]
### Description of the problem / feature request:

> I used bazel's default host crosstools top to compile tensorflow. GCC version is 4.8.3. At compile time, bazel reports that the dependency declaration of the following header file could not be found.
```
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/stdint.h'
```
Under the /usr/lib/ GCC /x86_64-linux-gnu/ folder, there are the following files
```
4.8/
4.8.4 -> 4.8/
4.9/
4.9.3 -> 4.9/
5/
```
I'm sure these environmental variables were not set:
```
C_INCLUDE_PATH,
CPLUS_INCLUDE_PATH,
OBJC_INCLUDE_PATH
```
I also executed the 
```
gcc-print-search-dirs 
```
and determined that the search path did not contain /usr/lib/gcc/x86_64-linux-gnu/5/

My question is, who searches for header files in this directory?
In bazel's default crosstool file,
I see the configuration
```
cxx_builtin_include_directory: "/usr/lib/gcc/"
```
This establishes a dependency on the header file, but does not specify the version under x86_64-linux-gnu,How is the final search path determined?
I don't want to restrict the version of GCC to dead. How should I deal with it? Please give me some Suggestions

### What operating system are you running Bazel on?

> 0.19.2

**Comment by dMokaMoka** [comment]
I set  `--experimental_strict_action_env`  to share compile cache with my team.  This led to the above errors.

**Comment by dMokaMoka** [comment]
I'm still not sure what environment variables affect GCC searches needed header-files...I want to share the compile cache as much as possible, unless the local GCC version is inconsistent.
I think I should set - experimental_strict_action_env, then inherit the environment variables by set `--action_env = XXX`.  What is the name of this variable? Can you give me some advice...

**Comment by dMokaMoka** [comment]
It appears that environment variables are discarded when compiling subtargets?
I set my environment variable in bazelrc:
```
build --action_env TF_NEED_OPENCL_SYCL="0"
build --action_env TF_NEED_CUDA="0"
build --action_env TF_DOWNLOAD_CLANG="0"
```
When bazel reports a compilation error, the command line printed is
```
(cd /path/to/execroot && \
  exec env - \
    PATH=/bin:/usr/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc ...)
undeclared inclusion(s) in rule '@protobuf_archive//:js_embed':
this rule is missing dependency declarations for the following files included by 'external/protobuf_archive/src/google/protobuf/compiler/js/embed.cc':
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h'
  '/usr/lib/gcc/x86_64-linux-gnu/5/include/stdint.h'
```

**Comment by dMokaMoka** [comment]
My question is similar to this #4558 . Is there any solution now?

**Comment by hlopko** [comment]
This is weird. Can you reproduce after calling `bazel clean --expunge`? It seems bazel is using gcc 5 to build, but has toolchain configured for gcc 4. What other `cxx_builtin_include_directory` entries are there in the CROSSTOOL `cc_configure` generated?

**Comment by dMokaMoka** [comment]
This is caused by  remote cache. The cache on the remote server uses 5.4.0 GCC.    My problem is similar to this #4558
