### ISSUE TITLE
Add a `defines` parameter to the experimental `cc_common.compile` api

### ISSUE THREAD

**Issue by kkiningh** [bazelbuild/bazel#6979]
### Feature request:

Add a `defines` parameter to the experimental `cc_common.compile` api.

### What underlying problem are you trying to solve with this feature?

Current API:

```python
compilation_contexts = [dep[CcInfo].compilation_context for dep in deps]
compilation_contexts.append(cc_common.create_compilation_context(
        ctx = ctx,
        headers = depset([]),
        system_includes = depset([]),
        defines = depset(defines),
))
compilation_info = cc_common.compile(
    [...],
    compilation_contexts = compilation_contexts,
)
```

After adding a defines parameter

```python
compilation_contexts = [dep[CcInfo].compilation_context for dep in deps]
compilation_info = cc_common.compile(
    [...],
    defines = defines,
    compilation_contexts = compilation_contexts,
)
```

### Any other information, logs, or outputs that you want to share?

This should be easy to fix since `CcCompilationHelper` already has an `addDefines` method.

**Comment by kkiningh** [comment]
Also, I can create a separate issue for this, but `cc_common.create_compilation_context` fails with a stack trace if called without both the `headers` and `system_includes` parameters (`com.google.devtools.build.lib.syntax.EvalException: name 'depset' is not defined`)

**Comment by hlopko** [comment]
No need to create an issue for the second one (fix in flight).

**Comment by hlopko** [comment]
Since `cc_common.compile` has already `includes` and `copts`, it does make sense either to add `defines`, or to drop both and only use compilation contexts (which have more related fields).

@oquenchil wdyt?

**Comment by kkiningh** [comment]
This seems like it is fixed since there is a 'defines' parameter in the newest [cc_common.compile api](https://docs.bazel.build/versions/master/skylark/lib/cc_common.html#compile). Please let me know if it should stay open.
