### ISSUE TITLE
proto_library incompatible with version 0.21

### ISSUE THREAD

**Issue by bbarnes52** [bazelbuild/bazel#6984]
Building a proto_library using bazel 0.21 yields the following error:

```
ERROR: /blaze/a08c2e4811c846650b733c6fc815a920/external/com_google_protobuf/BUILD:597:1: Traceback (most recent call last):
        File "/blaze/a08c2e4811c846650b733c6fc815a920/external/com_google_protobuf/BUILD", line 597
                internal_gen_well_known_protos_java(srcs = WELL_KNOWN_PROTOS)
        File "/blaze/a08c2e4811c846650b733c6fc815a920/external/com_google_protobuf/protobuf.bzl", line 266, in internal_gen_well_known_protos_java
                Label(("%s//protobuf_java" % REPOSITOR...))
        File "/blaze/a08c2e4811c846650b733c6fc815a920/external/com_google_protobuf/protobuf.bzl", line 266, in Label
                REPOSITORY_NAME
The value 'REPOSITORY_NAME' has been removed in favor of 'repository_name()', please use the latter (https://docs.bazel.build/versions/master/skylark/lib/native.html#repository_name). You can temporarily allow the old name by using --incompatible_package_name_is_a_function=false
ERROR: /blaze/a08c2e4811c846650b733c6fc815a920/external/com_google_protobuf/BUILD:380:1: Target '@com_google_protobuf//:android' contains an error and its package is in error and referenced by '@com_google_protobuf//:protoc'
ERROR: /blaze/a08c2e4811c846650b733c6fc815a920/external/com_google_protobuf/BUILD:380:1: Target '@com_google_protobuf//:windows' contains an error and its package is in error and referenced by '@com_google_protobuf//:protoc'
ERROR: /blaze/a08c2e4811c846650b733c6fc815a920/external/com_google_protobuf/BUILD:380:1: Target '@com_google_protobuf//:windows_msvc' contains an error and its package is in error and referenced by '@com_google_protobuf//:protoc'
ERROR: /src/workspace/src/roboflow/webservice/proto/BUILD:23:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf//:protoc', but this target could not be found because of: Target '@com_google_protobuf//:protoc' contains an error and its package is in error
ERROR: Analysis of target '//src/roboflow/webservice/proto:proto_lib' failed; build aborted: Analysis failed
```

Easily worked around, just wanted to make you aware of the issue.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Building any proto_library target on 0.21 should replicate this issue

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

release 0.21.0

**Comment by bbarnes52** [comment]
There's also a dependency on the deprecated native `http_archive` that requires attention

**Comment by irengrig** [comment]
Protobuf 3.6.1 is not compatible with Bazel 0.21.0.
Please use v3.6.1.3: https://github.com/protocolbuffers/protobuf/releases/tag/v3.6.1.3

**Comment by bbarnes52** [comment]
sure, isn't `proto_library` a native bazel rule though? shouldn't the `proto_library` rule bundled with 0.21 work out of the box? I'm sure I'm misunderstanding something ..

**Comment by irengrig** [comment]
proto_library has dependencies on the version of the protobuf that you declare in the WORKSPACE file.

I just was able to build the sample project with Bazel 0.21.0 using the following dependencies in WORKSPACE file:
`http_archive(
    name = "com_google_protobuf",
    strip_prefix = "protobuf-3.6.1.3",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/v3.6.1.3.tar.gz"],
)

# java_lite_proto_library rules implicitly depend on @com_google_protobuf_javalite//:javalite_toolchain,
# which is the JavaLite proto runtime (base classes and common utilities).
http_archive(
    name = "com_google_protobuf_javalite",
    strip_prefix = "protobuf-javalite",
    urls = ["https://github.com/google/protobuf/archive/javalite.zip"],
)`

Similar changes were done, for instance, in android test project:
https://github.com/android/android-test/commit/40aee6899da31af2e11b08c6aac521681892a0a9

The (slightly outdated) blog post about protocol buffers rules in Bazel: https://blog.bazel.build/2017/02/27/protocol-buffers.html

**Comment by bbarnes52** [comment]
thank you for your explanation - the part that was confusing me is that I don't declare `com_google_protobuf` in my WORKSPACE anywhere. I do download https://github.com/pubref/rules_protobuf, which looks like it's no longer maintained.

**Comment by irengrig** [comment]
Seems https://github.com/protocolbuffers/protobuf/ is the correct place. Do not know about the other one.

**Comment by Martin20** [comment]
How I can know the protobuf version?
