### ISSUE TITLE
[aquery] Get affected actions from an input file

### ISSUE THREAD

**Issue by joeleba** [bazelbuild/bazel#6986]
### Description of the problem / feature request:

Example use case: As a Bazel user, I want to know which actions will be run after I make changes to a particular file(s).

### Feature requests: what underlying problem are you trying to solve with this feature?

With this feature, the user is able to tell how changes to their code base affect the actions executed during build.

**Comment by jin** [comment]
@joeleba could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?

**Comment by lunaris** [comment]
I have a monorepo with multiple build pipelines that I want to trigger based on changes made. On the one hand I can use `git` and the filesystem but I am conscious that Bazel is a far better source of truth. Am I correct in thinking that were this feature implemented, it'd be the correct way to go about it? Or is there another way/workaround that should be used? Essentially I want to ask Bazel "which packages will be rebuilt given the current state of the workspace" and use that output to guide pipeline triggering.

**Comment by joeleba** [comment]
AFAIK, there's unfortunately no easy way to get the changes (files added/modified/removed) in the project since the last bazel build. If you already have the list of files and want to find out the packages, you can try out [bazel query](https://docs.bazel.build/versions/master/query-how-to.html#what-package-contains-file-path-to-file-bar-java). More about Skyframe, Bazel's parallel evaluation and incrementality model [here](https://bazel.build/designs/skyframe.html#incrementality).

Our internal discussion has led to a deprioritization of this feature and I've updated the label to reflect that.

**Comment by meisterT** [comment]
We currently have no plans to work on it and also no implementation plan, so closing.
