### ISSUE TITLE
[aquery] Query against current state of Skyframe

### ISSUE THREAD

**Issue by joeleba** [bazelbuild/bazel#6987]
### Description of the problem / feature request:

Allow the user the option to omit a query expression and run aquery against the current ActionGraph on Skyframe.
e.g. `bazel aquery --skyframe-state` would automatically retrieve all actions in the current ActionGraph.

Example use case:
1. `bazel build //a`
2. `bazel build //b`
3. File `foo.out` is generated
=> Was it step (1) or (2) that generated `foo.out`?

Run `bazel aquery --skyframe-state` would give the list of actions in Skyframe, and therefore can answer the above question.

**Comment by jin** [comment]
@joeleba could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?

**Comment by joeleba** [comment]
Resolved.
