### ISSUE TITLE
0.21.0 sha of windows zip

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#6995]
Hi.

Can we have sha256 for windows zipped binary?

<img width="562" alt="2018-12-23 17_17_35-microsoft edge" src="https://user-images.githubusercontent.com/2255111/50384520-d4889680-06d6-11e9-952f-e4eec3d531eb.png">

**Comment by philwo** [comment]
Hi,

sorry! The upload of that file to GitHub didn't work in our automatic release process. I've manually uploaded it.

Cheers,
Philipp
