### ISSUE TITLE
bazel coverage cannot generate correct results when using custom CROSSTOOL

### ISSUE THREAD

**Issue by deeply** [bazelbuild/bazel#7004]
### Description of the problem / feature request:

> bazel coverage cannot generate correct results when using custom CROSSTOOL.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Wrote a custom CROSSTOOL to use linaro toolchain [gcc-linaro-6.3.1](http://releases.linaro.org/components/toolchain/binaries/6.3-2017.05/aarch64-linux-gnu/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu.tar.xz). Run coverage analysis:
```
bazel coverage \
--combined_report=lcov \
--coverage_report_generator=@bazel_tools//tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator:Main \
--experimental_cc_coverage \
--crosstool_top=@arm64-v8a-linaro-linux-gnu \
--cpu=arm64-v8a \
--compiler=gcc-6.3.1 \
--host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
--platform_suffix=-aarch64-linux \
--run_under=qemu-aarch64 \
-- //...
```
> I got error like:
```
ERROR: output '_coverage/_coverage_report.dat' was not created
ERROR: not all outputs were created or valid
```
### What operating system are you running Bazel on?

> Ubuntu 16.04

### What's the output of `bazel info release`?

> release 0.20.0

### Any other information, logs, or outputs that you want to share?

> There might be 2 issues.
> (1) broken gcov symlink:
```
ln -s "${COVERAGE_GCOV_PATH}" "${GCOV}"
```
>[this line of code](https://github.com/bazelbuild/bazel/blob/0.20.0/tools/test/collect_cc_coverage.sh#L58) will create a symlink to ${COVERAGE_GCOV_PATH}, which is a relative path like `external/arm64-v8a-linaro-linux-gnu/bin/aarch64-linux-gnu-gcov` when using custom CROSSTOOL.
> A workaround is adding `--test_env COVERAGE_GCOV_PATH=/some/absolute/path/to/gcov` when execute bazel coverage command.
>
> (2) unexpected behavior for some versions of gcov: 
> Some versions of gcov (for example, the `aarch64-linux-gnu-gcov` from gcc-linaro-6.3.1) will not print "Creating xxx.gcov" to output. The [collect_cc_coverage.sh](https://github.com/bazelbuild/bazel/blob/0.20.0/tools/test/collect_cc_coverage.sh#L161) script will fail on collecting generated .gcov files.
> A workaround is using different version of gcc. (gcov from [gcc-linaro-5.5.0](http://releases.linaro.org/components/toolchain/binaries/5.5-2017.10/aarch64-linux-gnu/gcc-linaro-5.5.0-2017.10-x86_64_aarch64-linux-gnu.tar.xz) works just fine)

**Comment by meisterT** [comment]
cc @iirina @hlopko

**Comment by cocasema** [comment]
Any updates on this? It still doesn't work w/o the mentioned workaround.

**Comment by hlopko** [comment]
No updates, This will unlikely be fixed in 2019.

**Comment by nareddyt** [comment]
Any chance that 1c77844f24ef20447cf8a63630cc48e2cbcea62e fixes "(1) broken gcov symlink" from above?

**Comment by ulfjack** [comment]
Yes, I think it fixes (1).

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
