### ISSUE TITLE
Native 'proto_library' rule fails to handle annotation imports correctly.

### ISSUE THREAD

**Issue by michaelsafyan** [bazelbuild/bazel#7005]
### Description of the problem / feature request:

Here is the way my repo is structured:

       Makefile
       cloudbuild.yaml
        src/
             WORKSPACE
             BUILD
             google/
                 BUILD
                  api/
                     BUILD
             path/
                BUILD
                 to/
                   BUILD
                    some/
                         BUILD
                          api_service/
                                 BUILD
                                  foo_service.proto

The WORKSPACE file contains:

    git_repository(
         name = "com_google_googleapis",
         remote = "https://github.com/googleapis/googleapis",
         commit = "7da57e24e735723929f09e27ce039fcff5980cce",
    )

The "google/api/BUILD" file contains:

      alias(
         name = "annotations",
         actual = "@com_google_googleapis//google/api:annotations_proto",
      )      

... thereby making "//google/api:annotations" into a valid reference to the "annotations.proto" file in the remote repository. These annotations are then used in the api_service BUILD rule:

      proto_library(
          name = "foo_service_proto",
          srcs = ["foo_service.proto"],
          deps = [
                "//google/api:annotations",
          ],
      )

... and "foo_service.proto" has an import on the remote file:

      import "google/api/annotations.proto";

The strange thing here is that this produces a `--direct_dependencies_violation` error message, even though a similar setup does not produce this error (when importing, for example, "longrunning.proto" from googleapis using a similar "google/longrunning/BUILD" file to pull in the target with an 'alias', there there is no complaint -- it seems this issue only applies in the case of the use of the "option" feature that extends a protocol buffer, but plain messages that aren't annotations don't have any issue).

### Feature requests: what underlying problem are you trying to solve with this feature?

Make it possible to reference and apply protocol buffer annotations defined in a remote repository without having to actually copy the original source files into the local repository.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See the scenario described above.

### What operating system are you running Bazel on?

Running on Google Cloud Shell.

Output of uname -a:
Linux cs-6000-devshell-vm-2b5461fb-d55d-4871-8ce2-9f4046489275 4.14.33+ #1 SMP Sat Aug 11 08:05:16 PDT 2018 x86_64 GNU/Linux

Output of lsb_release:
No LSB modules are available.

### What's the output of `bazel info release`?

release 0.20.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Confidential. Please contact me directly if you want to examine the repository.

**Comment by hlopko** [comment]
Oh this issue slipped under the radar! I'm sorry for that. Is it still unresolved?
