### ISSUE TITLE
Create replacement for `@bazel_tools//tools/jdk:jar`

### ISSUE THREAD

**Issue by RNabel** [bazelbuild/bazel#7006]
### Description of the problem / feature request:

The [JavaRuntimeInfo](https://docs.bazel.build/versions/master/skylark/lib/JavaRuntimeInfo.html) appears to be missing an entry for the `jar` tool. This makes a transition away from `@bazel_tools//tools/jdk:jar` difficult. We use the `:jar` target across our codebase and creating our own wrapper around the java_runtime feels like a regression.

### Feature requests: what underlying problem are you trying to solve with this feature?

Be able to easily access the `jar` binary contained within the current java runtime.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Setup tested is basically a copy of what is done [here](https://source.bazel.build/bazel/+/master:tools/build_rules/java_rules_skylark.bzl;l=53?q=current_java_runtime&ss=bazel) plus this line:
```
_jar = str(ctx.attr._jdk[java_common.JavaRuntimeInfo].java_home) + "/bin/jar"
```

This is, however, not Windows-proof which the previous setup was.

### What operating system are you running Bazel on?

Linux, Macos, Windows

### What's the output of `bazel info release`?

`release 0.21.0`

**Comment by ittaiz** [comment]
May I ask why do you use this jar? AFAIK it’s not reproducible

**Comment by RNabel** [comment]
This is used to generate `.jar` files from generated java files within a custom bazel rule (which, AFAIK, requires the `jar` tool). A possible workaround is to wrap the custom bazel rule in a bazel macro so that the generated java source files get wrapped in a `java_binary` rule, from which one could then get a non-executable jar file.
While this isn't a huge problem, it seems strange that the `@local_jdk` targets were deprecated without a replacement for accessing the jar tool :)

Could you clarify what you mean by `AFAIK it's not reproducible`?

**Comment by ittaiz** [comment]
The jar tool from the jdk creates an archive with timestamps. This means
that if you create two jars with the same files in different times their
hash will be different leading to non reproducibility.

**Comment by h3adache** [comment]
I'm running into this issue trying to clean up bazel warnings when updating bazel. What would be the proper solution in your opinion then @ittaiz?

**Comment by comius** [comment]
There is now a function java_common.pack_sources. It creates a jar from any collection of files and jars (not necessarily sources), without a timestamp.
