### ISSUE TITLE
incompatible_require_feature_configuration_for_pic: Require feature_configuration argument for `cc_toolchain_info.use_pic_for_dynamic_libraries`.

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#7007]
**Flag**: --incompatible_require_feature_configuration_for_pic
**Available since**: 0.22 (January 2019 release)
**Will be flipped in**: 0.23 (February 2019 release)
**Tracking issue**: #5883
**Rollout doc**: [docs.google.com/document/d/1uv4c1zag6KvdI31qdx8C6jiTognXPQrxgsUpVefm9fM/edit#](docs.google.com/document/d/1uv4c1zag6KvdI31qdx8C6jiTognXPQrxgsUpVefm9fM/edit#)

### Motivation

This is a part of larger incompatible change https://github.com/bazelbuild/bazel/issues/6861. With removing legacy crosstool fields we need `feature_configuration` to correctly tell whether pic is required for dynamic libraries.

### Migration

Pass `feature_configuration` instance as an argument to `cc_toolchain_info.needs_pic_for_dynamic_libraries` and use this method instead of `cc_toolchain_info.use_pic_for_dynamic_libraries`.

### Impact

Minimal, the method is rarely used.

**Comment by philwo** [comment]
I verified that this flag was flipped and thus will be included in the Bazel 0.23.0 release.
