### ISSUE TITLE
Add includes/imports attribute to Python rules

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel#702]
It would be great if the `py_*` rules had an `includes` or `imports` attribute, similar to the `includes` attribute for the `cc_*` rules, that would add the specified directory to `PYTHONPATH` for all targets that depend on the target.

For example, currently, the BUILD file for protobuf currently works around the lack of such an attribute by [having a custom genrule copy the sources](https://github.com/google/protobuf/blob/master/BUILD#L479) for Python support. Further, vendoring protobuf as a third_party library for Python support requires importing protobuf at `//google/protobuf` due to this limitation.

**Comment by davidzchen** [comment]
After looking further into how to use protobuf for Python with Bazel, I am now more convinced that we need this in order to remove the [hack](https://github.com/google/protobuf/blob/master/BUILD#L483) that requires importing the protobuf repo as `//google/protobuf` in your workspace.

As explained in the above link, the reason why need this hack is because the generated Python protobuf files contain imports that look like:

```python
from google.protobuf.xxx import yyy
```

Currently, Bazel's Python rules require importing from the workspace root, and there is no way to add additional directories to the `PYTHONPATH`. Including the protobuf repo as an external repository will not work either because there is no `//google` package in the protobuf repo.

**Comment by damienmg** [comment]
Once https://github.com/google/protobuf/pull/1165 is merged, we can indeed recommends to remove the comment.

**Comment by davidzchen** [comment]
Doesn't google/protobuf#1165 only fix the problem encountered when loading protobuf.bzl from an external repository? Or does it also solve the Python imports problem?

**Comment by damienmg** [comment]
It doesn't solve the py import problem as a submodule but PYTHONPATH is
correctly set to include external repositories so it fixes those case.

**Comment by davidzchen** [comment]
I still don't quite follow. The generated sources still `from google.protobuf.xxx import yyy`.

* In the git submodule case, this currently requires the the protobuf repository to be under `//google/protobuf` in the workspace.
* In the external repository case, from what I understand the root of the external repository is added to `PYTHONPATH` but there is no `google/` directory in the protobuf source tree.

**Comment by damienmg** [comment]
oh I see, yes it's a good idea to upstream those change too.

**Comment by davidzchen** [comment]
I have a [patch](https://github.com/davidzchen/bazel/commit/608337a8f16b9472662125d8a47f283cbdb126f0) that adds the `imports` attribute to the Python rules. It works with the Python example under `//examples/py_native`. Once I successfully test it with protobuf and having tensorflow include protobuf as an external repository, I'll send it out for review.

**Comment by damienmg** [comment]
I rethough a bit of 

```
  In the external repository case, from what I understand the root of the external repository
  is added to PYTHONPATH but there is no google/ directory in the protobuf source tree.
```

When including a git_repository and extracting the submodules (for TensorFlow for example), it works just fine because the PYTHONPATH include the git repository base and the submodule for protobuf will be in google/protobuf.

Anyway, we definitely wants to have your  change in for 0.2 I think, could try to merge it ASAP?

**Comment by davidzchen** [comment]
Agreed. I'll send it out for review as soon as I am done testing it.
