### ISSUE TITLE
What provider should custom rules return for cc_binary?

### ISSUE THREAD

**Issue by ax7476** [bazelbuild/bazel#7021]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:
What provider should custom rules return for cc_binary?
When target of the cc_binary depends on the target of the custom cuda_library  rule , the following error is prompted:
ERROR: /home/moonx/Downloads/tmp/cudatest/main/BUILD:13:12: in deps attribute of cc_binary rule //main:hello-world: cuda_library rule '//main:hello-greet' is misplaced here (expected cc_library, objc_library, cc_proto_library or cc_import) and '//main:hello-greet' does not have mandatory providers: 'CcSkylarkInfo'
ERROR: Analysis of target '//main:hello-world' failed; build aborted: Analysis of target '//main:hello-world' failed; build aborted
INFO: Elapsed time: 0.323s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)

### Feature requests: what underlying problem are you trying to solve with this feature?

Customize rules for cuda and the rule can be interdependent with  cc_library.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
cuda_library(
    name = "hello-greet",
    srcs = ["hello-greet.cc"],
    hdrs = ["hello-greet.h"],
)

cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
    deps = [
        ":hello-greet",
    ],
)

```
def _cuda_library_impl(ctx):
    index = ctx.build_file_path.rfind("/BUILD")
    buildpath = workspaceDir+ctx.build_file_path[:index]
    externalpath = protobufpath
    copts = ctx.attr.copts
    output=ctx.outputs.out
    lib_flags = ["-std=c++11", "-shared", "-Xcompiler", "-fPIC"] + parseDeps(ctx.files.deps)
    srcs = [f.path for f in ctx.files.srcs] 
    OutputGroupInfo(dynamic_library=ctx.files.deps)

    link_flags = ctx.attr.flags
    include_directories = []
    quote_include_directories = []
    system_include_directories = []
    for f in ctx.attr.deps:
      link_flags += f.cc.link_flags
      include_directories += ["-I" + d for d in f.cc.include_directories]
      quote_include_directories += ["-I" + d for d in f.cc.quote_include_directories]
      system_include_directories += ["-I" + d for d in f.cc.system_include_directories]

    deps_flags = link_flags + include_directories + quote_include_directories + system_include_directories

    ctx.actions.run_shell(
        inputs=ctx.files.srcs + ctx.files.hdrs + ctx.files.deps,
        outputs = [output],
        env={'PATH':'/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/bin',},
        command="nvcc %s -ccbin /usr/bin %s %s -I. -L. -I %s -I %s -I %s -I %s %s %s -o %s" % (" ".join(copts), " ".join(cuda_arch), \
' '.join(srcs), buildpath, workspaceDir, ctx.genfiles_dir.path, externalpath, ' '.join(deps_flags), ' '.join(lib_flags),  output.path),
    )

    cc = struct(defines=[], libs=[], compile_flags=[], link_flags=link_flags, include_directories=include_directories, quote_include_directories=quote_include_directories, system_include_directories=system_include_directories, transitive_headers=[])

    return struct(cc=cc)
```

### What operating system are you running Bazel on?

Linux moonx 4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### What's the output of `bazel info release`?

WARNING: Processed legacy workspace file /home/moonx/Downloads/apollo/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read #6319 for further information, including how to upgrade.
Starting local Bazel server and connecting to it...
release 0.18.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Build label: 0.18.1

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by oquenchil** [comment]
The answer is CcInfo.
