### ISSUE TITLE
0.21.0: Server terminated abruptly; SIGSEGV in ...skyframe.SkyFunctionEnvironment.maybeGetValueFromErrorOrDeps

### ISSUE THREAD

**Issue by mpictor** [bazelbuild/bazel#7028]
### Description of the problem / feature request:

Bazel crashed
$ `bazel build //...`
```
...
(14:47:59) [3,300 / 3,663] 16 actions running
...
Server terminated abruptly (error code: 14, error message: '', log file: '/home/mark/.cache/bazel/_bazel_mark/d8701ad9b2e2f65c9be5ed8883d64bb4/server/jvm.out')
```

jvm.out contains

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/home/mark/.cache/bazel/_bazel_mark/install/f6ca571514ebc1be8327564b4455aae2/_embedded_binaries/A-server.jar) to field sun.nio.ch.SelectorImpl.selectedKeys
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f72fd5575f0, pid=18338, tid=19631
#
# JRE version: OpenJDK Runtime Environment (9.0.1+1) (build 9.0.7.1+1)
# Java VM: OpenJDK 64-Bit Server VM (9.0.7.1+1, mixed mode, tiered, compressed oops, parallel gc, linux-amd64)
# Problematic frame:
# J 12104 c2 com.google.devtools.build.skyframe.SkyFunctionEnvironment.maybeGetValueFromErrorOrDeps(Lcom/google/devtools/build/skyframe/SkyKey;)Lcom/google/devtools/build/skyframe/SkyValue; (69 bytes) @ 0x00007f72fd5575f0 [0x00007f72fd557040+0x00000000000005b0]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e" (or dumping to /path/to/core.18338)
#
# An error report file with more information is saved as:
# /path/to/hs_err_pid18338.log
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/
#
```

A sanitized copy of hs_err_pid18338.log is attached.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Unknown

### What operating system are you running Bazel on?

Gentoo linux, amd64

### What's the output of `bazel info release`?

release 0.21.0

###  Have you found anything relevant by searching the web?

no

### Any other information, logs, or outputs that you want to share?

I was running `emerge` (gentoo package install tool) at the same time, but plenty of memory was available and emerge/make appeared to have stopped spawning jobs because the load average was too high (~20 IIRC). So I doubt that emerge (or anything else on the system) was the culprit.

Unfortunately, systemd's core dump facility appears to have truncated the core - so that's not available.

[hs_err_pid18338.sanitized.log](https://github.com/bazelbuild/bazel/files/2722059/hs_err_pid18338.sanitized.log)

**Comment by katre** [comment]
Closed for lack of activity. Please ping the reviewers to reopen if this is still a problem.
