### ISSUE TITLE
Bazel CI: rules_foreign_cc is broken by "Remove whitelist flag for new API"

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#7029]
Breakage:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/722#69645e62-9c06-4761-8bfe-36df45ebcf1a

Culprit Finder result points to 1d36051776557bbcbba1a8f0d98e5a408a717d11:
https://buildkite.com/bazel/culprit-finder/builds/46#9da54b3e-477b-4e8a-bd59-51be3ac21915

@oquenchil
/cc @hlopko @irengrig

**Comment by meteorcloudy** [comment]
@irengrig @oquenchil 
Should we rollback the change or update rules_foreign_cc?

**Comment by irengrig** [comment]
I will update rules_foreign_cc in 10 minutes...

**Comment by irengrig** [comment]
Still waiting for apple tests to start, but the issue with old API definitely fixed: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/724#d1235e8d-50e8-41a1-930f-93810c14ddde
