### ISSUE TITLE
new_http_archive fatal error does not appears if repository is already fetched

### ISSUE THREAD

**Issue by guibou** [bazelbuild/bazel#7032]
### Description of the problem / feature request:

I recently upgraded to bazel 0.20 and I noticed a reproducibility issue.

`new_http_archive` is now deprecated and its usage generate a fatal error. However the error won't be generated if the repository is already fetched. This leads to the following scenario:

- dev A has already fetched repository `@foo` on his machine with bazel < 0.20
- dev A update to bazel 0.20. It works.
- dev B update to bazel 0.20 and wants to fetch the repository `@foo` which was not already in the local cache and it fails.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- The following `WORKSPACE`:

```
new_http_archive(
    name = "generic_accessors",
    build_file_content = """
filegroup(
   name="foo",
   srcs=["generic-accessors.cabal"],
)
    """,
    sha256 = "538275c5f1fa93edc9f497bfc595cad0e0a43a85bc0c9b60e4445f374e98e467",
    strip_prefix = "generic-accessors-11b0892d961e2b243532160e1de758fc3006e96c",
    url = "https://github.com/ghorn/generic-accessors/archive/11b0892d961e2b243532160e1de758fc3006e96c.tar.gz",
)
```

(Don't bother with the content fetched, I needed to fetch something, I picked. a random github package).

- empty `BUILD.bazel`.

build with bazel < 0.20. I used 0.16 from `nixpkgs`, channel `nixos-18.09`.

```
$ nix run -f channel:nixos-18.09 bazel gcc gcc-unwrapped
[nix-shell] $ which bazel
/nix/store/bcgqy2l4y4hm95wwy8z946zr9pr921xi-bazel-0.16.1/bin/bazel

[nix-shell] $ bazel build @generic_accessors//...
INFO: Analysed target @generic_accessors//:foo (3 packages loaded).
INFO: Found 1 target...
Target @generic_accessors//:foo up-to-date (nothing to build)
INFO: Elapsed time: 1.316s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

It worked, as expected.

Now, in the same directory, pick a bazel 0.20 (from `nixpkgs` channel `nixpkgs-unstable`):

```
$ nix run -f channel:nixpkgs-unstable bazel gcc gcc-unwrapped

[nix-shell] $ which bazel
/nix/store/njca731lhyvzbm8rxfq4lpz1s8ispc30-bazel-0.20.0/bin/bazel

[nix-shell] $ bazel build @generic_accessors//...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 48070ee1-9cde-41df-aa7c-c3497d6b762b
INFO: Analysed target @generic_accessors//:foo (3 packages loaded, 3 targets configured).
INFO: Found 1 target...
Target @generic_accessors//:foo up-to-date (nothing to build)
INFO: Elapsed time: 3.220s, Critical Path: 0.02s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

It worked, no error message.

No call `bazel clean --expunge` and rebuild:

```
[nix-shell] $ bazel clean --expunge
INFO: Invocation ID: 9c2ad479-9055-4b22-b681-5585b5ee0567
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.

[nix-shell] $ bazel build @generic_accessors//...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 979d9f4e-634e-4126-bb20-f1d05e4fb4ee
ERROR: The native new_http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
INFO: Elapsed time: 1.795s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    Fetching @generic_accessors; fetching
```

It fails with the error message expected from bazel 0.20.

### What operating system are you running Bazel on?

Linux - nixos.

### What's the output of `bazel info release`?

Respectively:

- `release 0.16.1- (@non-git)`
- `release 0.20.0- (@non-git)`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Using nix as detailed in the example

###  Have you found anything relevant by searching the web?

no.

### Any other information, logs, or outputs that you want to share?

Nothing.

**Comment by aehlig** [comment]
> @aehlig ptal - is it only native-http-archive specific, or is there more to this?

The underlying mechanism of [invalidating external repositories](https://bazel.build/designs/2016/10/18/repository-invalidation.html) has not changed. So, basically, external repositories are not invalidated unless the definition changes. Now, in this particular case, the problem was that the deprecation error was only upon _use_ of the native rules, not upon their presence in a `WORKSPACE` file. Now, if an external repository was fetched successfully before the beginning of the deprecation period and its definition hasn't changed during the deprecation period, then the native rule was never used for that particular workspace.

I'm not sure what we can do in this case. Technically, it's all working as specified, but I agree, we could have done a better job in warning users about the deprecation of those native rules.

**Comment by aehlig** [comment]
Closing, as there is nothing we can do here any more.
