### ISSUE TITLE
How to find toolchain for cpu 'mips64'

### ISSUE THREAD

**Issue by FengRillian** [bazelbuild/bazel#7035]
After successfully compile bazel-0.19.2-dist on mips64 cpu. Install bazel.
But while compile envoy with bazel, error found:

ERROR: No toolchain found for cpu 'mips64'. Valid cpus from default_toolchain entries are: [
]. Valid toolchains are: [
  local_linux: --cpu='mips64' --compiler='compiler',
  stub_armeabi-v7a: --cpu='armeabi-v7a' --compiler='compiler',
  local: --cpu='piii' --compiler='compiler',
  msys_x64_mingw: --cpu='x64_windows' --compiler='mingw-gcc',
  msvc_x64: --cpu='x64_windows' --compiler='msvc-cl',
]
INFO: Elapsed time: 0.601s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by FengRillian** [comment]
Check bazel code, default_toolchain list is NULL.
How to add mips64 toolchain (local_linux) to default_toolchain?

**Comment by FengRillian** [comment]
Bazel 0.19.2 version.

**Comment by hlopko** [comment]
Can you try again with Bazel 0.21 and if it still fails, with Bazel built at head? I think it should work now.

**Comment by FengRillian** [comment]
It works.
