### ISSUE TITLE
`pkg_rpm` is locale-dependent

### ISSUE THREAD

**Issue by vmax** [bazelbuild/bazel#7037]
### Description of the problem / feature request:

Regex [used to get output file location](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/pkg/make_rpm.py#L101) in `pkg_rpm` expects English message.

### Feature requests: what underlying problem are you trying to solve with this feature?

Trying to build `pkg_rpm` package on non-English system

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Use the rule on a system language `rpmbuild` has translation to (e.g. I'm on `ru_RU` locale)

### What operating system are you running Bazel on?

macOS Mojave 10.14.2

### What's the output of `bazel info release`?

`release 0.21.0`

**Comment by aiuto** [comment]
It's not clear if this is a an RPM issue or a generic execution phase issue. To get predictable result, we need to set the locale for all execution steps rather than relying on the host system default.
So I'm adding two different teams and you can sort it out.
