### ISSUE TITLE
Documentation for fragments does not introduce them.

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#704]
http://bazel.io/docs/skylark/rules.html#fragments

I'm reading through the documentation of skylark custom rules and the first mention of 'fragments' seems to assume that you already know what a fragment is. Also none of the documentation seems to describe what a fragment is other than 3 possible valid values `cpp`, `java`, and `jvm`.

**Comment by steven-johnson** [comment]
Any update on this? I too wonder just what Fragments are and why/when/where I would use them.

**Comment by Syeberman** [comment]
I'm also struggling with this.

**Comment by jin** [comment]
@gregestren @spomorski can https://docs.bazel.build/versions/master/skylark/lib/skylark-configuration-fragment.html be elaborated with more information?

**Comment by gregestren** [comment]
I think the hyperlink to https://docs.bazel.build/versions/master/skylark/lib/skylark-configuration-fragment.html provides a lot of the context that was missing in the original request.

Sye (and anyone else): can you elaborate on what's still unclear?

This is really helpful feedback, so thanks for reporting this.

**Comment by spomorski** [comment]
We can definitely work on this. Who can identify what's missing and
possibly provide that information?

**Comment by gregestren** [comment]
https://docs.bazel.build/versions/master/skylark/lib/skylark-configuration-fragment.html provides more context the first report. Plus the new [Starlark build configuration](https://docs.google.com/document/d/1vc8v-kXjvgZOdQdnxPTaV0rrLxtP2XwnD2tAZlYJOqw/edit#heading=h.pn8nbhno42p5) design goes into details explaining what fragments are (and in fact makes that user-definable Starlark libraries). The documentation for that will explain this. So I'm going to close this on those updates.
