### ISSUE TITLE
Slack invite has expired

### ISSUE THREAD

**Issue by clanstyles** [bazelbuild/bazel#7046]
The slack invite code on https://bazel.build/support.html has expired.

**Comment by jin** [comment]
Please use the self inviter https://bazel-slackin.herokuapp.com for now.

**Comment by aiuto** [comment]
We need an inviter service so that we don't have direct through herokuapp.com.
This is either Team-EngProd (because we'll run a server) or Team-Product, because it is really product management.

**Comment by jin** [comment]
The inviter service is not coupled to Heroku. We can host it on GCE. https://github.com/rauchg/slackin

**Comment by dslomov** [comment]
Please do not assign issues to more than one team

**Comment by laurentlb** [comment]
The link on the website is still broken.

**Comment by philwo** [comment]
@jin Do you mind if I assign it to you, considering that you're working on our new Slack inviter?

**Comment by jin** [comment]
Sure!

**Comment by jin** [comment]
We've launched an invite portal at https://slack.bazel.build/ :tada:

**Comment by snakethatlovesstaticlibs** [comment]
Looks like the link is no longer active
