### ISSUE TITLE
Documentation for ctx.file and ctx.files is bad.

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#705]
The documentation for ctx.file and ctx.files seems to have an extra '.'/missing a word. Delving into the code it seems that `<ATTR>` is getting dropped from the documentation.

http://bazel.io/docs/skylark/lib/ctx.html#file
http://bazel.io/docs/skylark/lib/ctx.html#files

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/SkylarkRuleContext.java#L305
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/SkylarkRuleContext.java#L319

**Comment by dslomov** [comment]
Already fixed (doc looks good to me)
