### ISSUE TITLE
Make stdout/stderr accessible when remote execution fails.

### ISSUE THREAD

**Issue by bwkimmel** [bazelbuild/bazel#7053]
### Description of the problem / feature request:
The Remote Execution API indicates that the stdout/stderr digests may be included even when the status in the ExecuteResponse is not OK (https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/execution/v2/remote_execution.proto#L1019), and Remote Build Execution Alpha for Google Cloud (RBE) does include these when available, but Bazel does not print out stdout to the console in these cases. The stdout/stderr of failed remotely-executed actions should still be printed out (or made accessible to the user through some other mechanism, e.g., by printing out a URL from which it may be obtained if the user wants to see it).

### Feature requests: what underlying problem are you trying to solve with this feature?
The stdout/stderr from failed actions may help users diagnose why the action failed.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
RBE currently has a 512MB limit on stdout. One way to trigger an error is to submit a task which exceeds this limit. E.g., an `sh_test` with the following source:

```shell
#!/bin/bash
dd if=/dev/urandom | base64 | head -c 512871936  # 512MB + 1kB
```

If the number is changed to be <= 512MB, the action will succeed and print the output of the command to the client's console. As written above, it will fail, and the API does return the digest of the (truncated) stdout, but only the following error message is printed to the client's console:

Remote connection/protocol failed with: execution failed Call failed with not retriable error: com.google.devtools.build.lib.remote.ExecutionStatusException: INVALID_ARGUMENT: stdout limit exceeded (536870912 bytes): com.google.devtools.build.lib.remote.Retrier$RetryException: Call failed with not retriable error: com.google.devtools.build.lib.remote.ExecutionStatusException: INVALID_ARGUMENT: stdout limit exceeded (536870912 bytes)

In particular, the (truncated) stdout is not printed and no indication of where to find the stdout is given.
Note: also related: https://github.com/bazelbuild/bazel/issues/7034

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

0.21.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

No

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
