### ISSUE TITLE
Test output is missing for tests that timeout

### ISSUE THREAD

**Issue by mmikitka** [bazelbuild/bazel#7058]
### Description of the problem / feature request:
When a test times out, the stdout and stderr from the underlying test is not written to the console. I noticed that changes were made to write stdout and stderr to the XML test output file on a timeout as per https://github.com/bazelbuild/bazel/issues/1027. In addition to the XML test output file, I'd like test-setup.sh write to the console.

Here is an example test.

```
bazel test --test_output=all --test_timeout=1 //foo:bar
INFO: Analysed target //foo:bar (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...

TIMEOUT: //foo:bar (Summary)
      /home/mmikitka/.cache/bazel/_bazel_mmikitka/1b86488e3b748cd487297982d8416c79/execroot/myrepo/bazel-out/k8-dbg/testlogs/foo/bar/test.log
INFO: From Testing //foo:bar:
==================== Test output for //foo:bar
Terminated
================================================================================
Target //foo:bar up-to-date:
  bazel-bin/foo:bar
INFO: Elapsed time: 17.156s, Critical Path: 16.01s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 1 process: 1 local.
INFO: Build completed, 1 test FAILED, 2 total actions
//foo:bar      TIMEOUT in 16.0s
```

### Feature requests: what underlying problem are you trying to solve with this feature?
Improve diagnostics of tests that timeout.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Write a test that writes to stdout and stderr then goes into an infinite while 1 loop (sleep indefinitely). Set  --test_timeout=1 to induce Bazel to time out the test.

### What operating system are you running Bazel on?
Ubuntu 18.04

### What's the output of `bazel info release`?
release 0.19.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.
N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
N/A

###  Have you found anything relevant by searching the web?
https://github.com/bazelbuild/bazel/issues/1027 and the corresponding patch.

### Any other information, logs, or outputs that you want to share?
N/A

**Comment by ittaiz** [comment]
I don’t have the issue number right now but I think @or-shachar or @hmemcpy
opened an issue about this already

**Comment by mmikitka** [comment]
It looks like I wasn't seeing stdout/stderr because the test was not flushing it's buffers often enough. Now that I flush on every write, I see stdout/stderr when the test receives a SIGTERM from bazel

**Comment by dslomov** [comment]
Please do not assign more than one team to an issue.

**Comment by jmmv** [comment]
So based on the last reply, I assume this is not something to fix. If the test didn't flush the output, there is nothing for Bazel to print as Bazel cannot force the test to flush its buffers.

**Comment by jxramos** [comment]
@mmikitka by any chance were you running a `py_test` target over a pytest session?

**Comment by aw632** [comment]
> [@mmikitka](https://github.com/mmikitka) by any chance were you running a `py_test` target over a pytest session?

I am running into this error in this scenario, is it related?
