### ISSUE TITLE
Support `android_instrumentation_test` on macOS

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#7069]
Tracking issue for `android_instrumentation_test` support on macOS.

**Comment by jin** [comment]
This is blocked on the availability of Project Nitrogen publicly.

**Comment by jin** [comment]
While integration with Nitrogen is WIP, I've made a experimental rule that uses the Composer test runner, and it works on a Mac: https://github.com/jin/rules_experimental_android#composer-integration

**Comment by jinchizhou** [comment]
Is `android_instrumentation_test` still not supported on macOS? I'm still getting https://github.com/bazelbuild/bazel/issues/9452.

**Comment by nkoroste** [comment]
@jin why is this not higher priority? I think being able to run tests on a Mac is a pretty big deal

**Comment by jin** [comment]
It's been a while since this was being worked on (I no longer work on Android rules). AFAIK, we were waiting for the multiplatform Nitrogen test runner (as I commented above), instead of making the legacy test infrastructure work on more platforms.

**Comment by arturdryomov** [comment]
Ah, Nitrogen. Announced two years ago, not a single byte of it published. But there is always hope!
