### ISSUE TITLE
Docs for common tags incorrectly limit 'manual' tag to tests.

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#707]
http://bazel.io//docs/be/common-definitions.html#common.tags

> Tags on non-test rules are used to control sandboxed execution of genrules and Skylark actions, and for parsing by humans and/or external tools.
> 
> manual keyword will force the test target to not be included in target pattern wildcards (..., :*, :all, etc); the test target will be neither built nor run. It will also be ignored by the test_suite rules that do not mention this test explicitly. The only way to build or run such a test is to specify it via an explicit target pattern on the command line.

But the manual keyword also applies to other rules such as genrules/binary targets when building.

**Comment by helenalt** [comment]
@spomorski  please review this text and see if it needs to be re-worded based on endobson@s  point

**Comment by mboes** [comment]
Any updates?

**Comment by meisterT** [comment]
Closing in favor of the duplicate #2303
