### ISSUE TITLE
incompatible_remove_cpu_and_compiler_attributes_from_cc_toolchain

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#7075]
**Flag:** `--incompatible_remove_cpu_and_compiler_attributes_from_cc_toolchain`
**Available since:** 0.23 (February 2019 release)
**Will be flipped in:** 0.24 (March 2019 release)

### Motivation

These attributes were introduced to drive the migration towards Crosstool in Starlark, but we ended up not needing them. They are currently unused, but `cpu` attribute was mandatory. This cleanup gets rid of them.

### Migration

Delete these attributes. You can use buildozer to perform the removal:

```
buildozer 'remove cpu' '//:my_toolchain'
buildozer 'remove compiler' '//:my_toolchain'
```

**Comment by laurentlb** [comment]
It looks like this flag is not available in Bazel 0.23.

**Comment by hlopko** [comment]
Sorry for that, and thanks for fixing!

**Comment by katre** [comment]
This issue was tagged as "breaking-change-0.24" but does not appear ready to be flipped in the [0.24.0 release](https://github.com/bazelbuild/bazel/issues/6968). If this is incorrect please comment on that issue and discuss with me.

**Comment by hlopko** [comment]
Yup this is correct, I missed the flip window between 0.23 release and 0.24 cut :)

**Comment by luorixiangyang** [comment]
I do the command:

**Comment by scentini** [comment]
@luorixiangyang you're seeing this error message because you're using Bazel 25.x and Tensorflow doesn't yet support that version. It's a work in progress though, should be fixed very soon.
