### ISSUE TITLE
bazel query somepath fails because of http_archive download fail

### ISSUE THREAD

**Issue by aleb** [bazelbuild/bazel#7078]
### Description of the problem / feature request:

Bazel `query somepath` fails for no good reason.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Add an http archive sub-workspace to the `WORKSPACE`:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "dataset_svo",
    url = "http://google.com/file.zip",
    sha256 = "anything",
    build_file = "dataset.BUILD",
)
```

Add a `dataset.BUILD`:
```
filegroup(
    name = "dataset",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)
```

Add a test which depends on the thing:
```
cc_test(
    name = "test",
    size = "small",
    srcs = glob(
        ["*.cc"],
    ),
    data = [
        "@dataset_svo//:dataset",
    ],
)
```

Run:
```
$ bazel query 'somepath(//:test, @dataset_svo://:dataset)'  
ERROR: no such package '@dataset_svo//': java.io.IOException: Error downloading [http://website/file.zip] to /private/var/tmp/...: No route to host (connect failed)
```

Notice it failed even though it has all the info to print that there is a path between the two targets. It does not really need to download/build `dataset_svo`.

### What operating system are you running Bazel on?

Mac 10.12.6

### What's the output of `bazel info release`?

release 0.20.0-homebrew

###  Have you found anything relevant by searching the web?

No

**Comment by dslomov** [comment]
It is a reasonable request, but unfortunately it is pretty hard to implement.

**Comment by aleb** [comment]
A possible workaround:
```
$ touch nothing.txt
$ tar czf nothing.tar.gz nothing.txt
$ python3 -m http.server 30168 --bind 127.0.0.1

$ S=$(sha256sum nothing.tar.gz | cut -d' ' -f1)
$ sed -i .1 's@url = .*@url = "http://127.0.0.1:30168/nothing.tar.gz",@' WORKSPACE
$ sed -i .2 "s@sha256 = .*@sha256 = \"$S\",@" WORKSPACE
$ sed -i .3 's@strip_prefix = .*@@' WORKSPACE

$ bazel query 'somepath(//:test, @dataset_svo://:dataset)'
//:test
@dataset_svo//:dataset
```
