### ISSUE TITLE
Docs for distribs common tag has dead link.

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#708]
http://bazel.io//docs/be/common-definitions.html#common.tags

There is a link  `distribs()` which goes to `http://bazel.io//docs/be/functions.html#distribs` There is no function of that name on that page. A quick search (of the docs) only seems to show uses of the rule level tag and no top level function.

**Comment by davidstanke** [comment]
@gregestren Is `distribs()` still a valid attribute? If so, we are missing doc for it.

**Comment by gregestren** [comment]
This is legacy code we don't want to expose to Bazel. I'm not sure we even want licenses / --check_licenses exposed (note the other doesn't appear in the user manual).  Does anyone rely on this?

Also see #188.

**Comment by aiuto** [comment]
Closing this.
- distribs serves no useful purpose
- The purpose we used it for in Google is better fulfilled with the work being done for #7444.
- we'll be ripping it out entirely in the next 2 or 3 of Bazel releases.

The design in https://docs.google.com/document/d/1uwBuhAoBNrw8tmFs-NxlssI6VRolidGYdYqagLqHWt8/edit#   does not explicitly mention distribs, but the fundamental alignment is that you can think of a distrib as a deployment environment.
