### ISSUE TITLE
incompatible_auto_configure_host_platform: Switch to new auto-configured host platforms

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#7081]
Flag: --incompatible_auto_configure_host_platform
Available since: 0.23
Will be flipped in: Unknown

See https://github.com/bazelbuild/proposals/blob/master/designs/2018-10-22-autoconfigured-host-platform.md for more context.
The default host and target platforms are defined in `@bazel_tools//platforms`, and there is special-purpose code in the Platform rule implementation to support this. This complicates the platform rules implementation and makes them dependent on the configuration.

Once this flag is enabled, Bazel will instead default to using a host platform generated by a repository rule, located at `@local_config_platform//:host`, and which will be created only once for a given build. The target platform will also default to this. Once migration is complete, the legacy targets and code can be removed.

Migration notes:
This only affects builds where the `--host_platform` and `--platforms` flags are _not_ used. Any builds currently setting those flags will not be affected.

Any users who rely on `--host_platform` and `--platforms` being affected by the `--host_cpu` and `--cpu` flags will need to begin directly setting `--host_platform` and `--platforms`.

**Comment by katre** [comment]
Changed the targetted flag-flip release, since this will require extensive testing and may need to wait for the projected migration plan for the cpu flag.

**Comment by hlopko** [comment]
Hey @katre, I just re-discovered this flag, what's needed to flip this? Or at least to get to a place where we can ask users to try and to re-enable it on the CI to see what's broken on downstream?

**Comment by hlopko** [comment]
Related: bazelbuild/rules_go#2089, bazelbuild/rules_cc#24, #8763, https://github.com/bazelbuild/bazel/issues/8766.

**Comment by katre** [comment]
Major work left:
1. Set the right tags so that we get migration readiness reports from CI, which I apparently never get right.
2. Write directions so that users who currently use cross-compilation with `--cpu` and `--host_cpu` and platform-related rules can add a platform mapping and continue work. I suspect this is a small set of users but I can't prove that.

**Comment by hlopko** [comment]
Looks like only Bazel is to be migrated: https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/175

**Comment by katre** [comment]
Thanks for the pointer!

**Comment by katre** [comment]
Logs: https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/191#annotation---incompatible_auto_configure_host_platform

**Comment by meteorcloudy** [comment]
Since this flag is already flipped, I'm temporarily removing the `migration-0.29` label from it because https://github.com/bazelbuild/bazel/issues/9104 is preventing the incompatible flags pipeline to give correct result on Windows and our update to Bazelisk is not ready yet.

FYI @dslomov
