### ISSUE TITLE
Can't build nodejs_image rule on Windows 

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#7082]
See https://github.com/bazelbuild/rules_nodejs/issues/491

**Comment by laszlocsomor** [comment]
@meteorcloudy is looking at this now, so let me assign it to him for now

**Comment by aiuto** [comment]
SGTM. I only added you because you are tracking everything that goes on
with Windows.

**Comment by laszlocsomor** [comment]
> I only added you because you are tracking everything that goes on with Windows.

Good to know, thank you for clarifying that!

**Comment by aiuto** [comment]
What I really want is a way to CC someone on an issue. I guess I could
comment and link you, but that's not quite the same feeling.

**Comment by jin** [comment]
@laszlocsomor could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?

**Comment by laszlocsomor** [comment]
This seems to work for me now, even with Bazel 0.21.0.
Pinging the original bug whether we can close it.
