### ISSUE TITLE
Bazel's execution log should include remote cache timeouts

### ISSUE THREAD

**Issue by ob** [bazelbuild/bazel#7084]
When debugging remote cache misses, the ability to compare two executions following the instructions [in this page](https://docs.bazel.build/versions/master/remote-execution-caching-debug.html) is invaluable. Unfortunately, I've seen cases where the only difference is that an action that in a fully-cached execution is this:

```
@@ -224,8 +224,7 @@
     hash_function_name: "SHA-256"
   }
 }
-runner: "remote cache hit"
-remote_cache_hit: true
+runner: "local"
 
 
 ---------------------------------------------------------
```

This doesn't tell me _why_ Bazel chose to run the action locally instead of fetching it from the remote cache. I *know* it's in the remote cache so I suspect it was due to a timeout, network error, or something like that. 

Bazel should add the reason why it chose to run the action locally to the execution log.

**Comment by jmmv** [comment]
I understand that you expected the action to run remotely but it fell back to local execution for some reason? If so, this is probably a bug for the remote execution team.

**Comment by ob** [comment]
> I understand that you expected the action to run remotely but it fell back to local execution for some reason? If so, this is probably a bug for the remote execution team.

Note that I'm not using remote execution, only remote caching. I expected the action to be downloaded from the cache since I knew it was fully cached (I've been debugging cache misses so this was a re-run of a build that had been fully cached).

I am guessing that the remote cache took too long to reply and the bazel client decided to run the action locally, but I don't know. Having some information about _why_ bazel decided to run the action locally (like for instance mentioning that the remote cache timed out or had an error) would be really useful.

**Comment by igorgatis** [comment]
I'm facing the same issue. @ob any recommendations?

**Comment by ob** [comment]
I ended up debugging this by a combination of logging in the remote cache and sniffing the protocol... definitively not ideal.
