### ISSUE TITLE
Use keepAliveTime on grpc channels

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#7085]
### Description of the problem / feature request:

bazel as a grpc client is unconfigurable with respect to keepAliveTime as available with the channel transport. I propose adding configuration to allow a transport keepAliveTime to be specified, possibly per service.

### Feature requests: what underlying problem are you trying to solve with this feature?

Presenting a grpc endpoint through network transports (i.e. commodity load balancers) that insist on non-idle connections to maintain connectivity results - particularly with remote execution and waiting for operation responses - unrecognized connection loss. This will stall executions for a transport-implementation dependent/indeterminate amount of time until the client realizes the connection has dropped.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

release 0.21.0

**Comment by buchgr** [comment]
IIRC the current behavior should be that connection failures are retried automatically by the gRPC library. Is that not the case? Is the idea behind a keepAliveTime to fail faster?

**Comment by werkt** [comment]
Realistically, yes, fail faster is the expected outcome of this, since I've seen connection states where (java-)grpc is ignorant of the connection loss induced by the load balancer. The keepalive will cause terminated connections in this state to yield the connection loss reaction by grpc.

**Comment by v2046** [comment]
Yes

**Comment by v2046** [comment]
P2

**Comment by v2046** [comment]
Yes

**Comment by v2046** [comment]
Vincy

**Comment by ulfjack** [comment]
This was fixed in https://github.com/bazelbuild/bazel/commit/761c16265139c2e5f5db50158d39c6717094ec49.
