### ISSUE TITLE
Enable dynamic spawn strategy to work with remote cache strategies only

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#7086]
This is a feature request to equip dynamic spawn strategy to also work with the `remote-cache` strategy.

Currently, the dynamic strategy executes two spawns at the same time: one local and one remote. It uses the result of the first spawn that finishes. 

It would be great to be able to replace the remote strategy with one that just checks for a cache hit for network-bound setups. In some situations, it is faster to run the spawn locally than to download all the outputs of the spawn.

Also, after speaking with @buchgr, the work on reducing intermediary downloads will also help reducing bandwidth saturation, which may lower the demand for this feature.

**Comment by jmmv** [comment]
I think this is essentially the same as https://github.com/bazelbuild/bazel/issues/7664?

**Comment by jin** [comment]
Yep, looks like it. Feel free to close this as dupe seeing that the other has more stats.
