### ISSUE TITLE
Starlark cannot be embedded if using master HEAD

### ISSUE THREAD

**Issue by mikelalcon** [bazelbuild/bazel#7090]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:
Copybara (https://github.com/google/copybara) uses Starlark as embed language. We depend on master HEAD code and update from time to time. Latest update fails with: 

java/com/google/copybara/config/SkylarkParser.java:276: error: [strict] Using type com.google.devtools.build.lib.syntax.SkylarkSemantics from an indirect dependency (TOOL_INFO: "@io_bazel//src/main/java/com/google/devtools/build/lib:skylark_semantics"). See command below **
        .setSemantics(SkylarkSemantics.DEFAULT_SEMANTICS)
                      ^
If I try to fix it by depending on    @io_bazel//src/main/java/com/google/devtools/build/lib:skylark_semantics, I get the following error: 

ERROR: /Users/malcon/dev/copybara/third_party/BUILD:137:1: in java_library rule //third_party:skylark-lang: target '@io_bazel//src/main/java/com/google/devtools/build/lib:skylark_semantics' is not visible from target '//third_party:skylark-lang'. Check the visibility declaration of the former target if you think the dependency is legitimate

IIUC visibility for skylark_semantics has to be the same as skylark-lang.

**Comment by brandjon** [comment]
Marking P1 because it sounds like a regression that blocks users of the Java Starlark interpreter from updating

**Comment by mikelalcon** [comment]
Done. It worked!

Thanks!
