### ISSUE TITLE
Misleading error message "file must have a corresponding package"

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#7094]
Repro:
```
mkdir tmp && cd tmp
touch WORKSPACE
echo 'load("@repository//dir:file.bzl", "foo")' > BUILD
bazel build //... --incompatible_disallow_load_labels_to_cross_package_boundaries
```

Output:
```
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 548ced79-efbd-4f49-be0f-03c8e096fb86
ERROR: error loading package '': Every .bzl file must have a corresponding package, but 'dir/file.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
INFO: Elapsed time: 1.822s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Error message should report that the repository doesn't exist, instead of complaining about the missing BUILD file.

cc @haxorz

**Comment by haxorz** [comment]
implementation proposal:
- have ContainingPackageLookupFunction fail-fast if any of its PackageLookupValue deps have a #getErrorReason of REPOSITORY_NOT_FOUND.
- have ContainingPackageLookupValue contain an ErrorReason
- have SkylarkImportLookupFunction#noBuildFile include both 'fileLabel' and the ErrorReason of the ContainingPackageLookupValue

**Comment by dslomov** [comment]
Assigning to @aehlig because he is looking at the similar https://github.com/bazelbuild/bazel/issues/7457 issue.

**Comment by haxorz** [comment]
@dslomov - fyi, @irengrig already has a CL for this internally.

**Comment by dslomov** [comment]
@irengrig and @aehlig please make sure you don't step on each other's toes :)

**Comment by aehlig** [comment]
06eb1bbde616d4e9b9e92da34245c8142a5b1121 should have closed this issue.
