### ISSUE TITLE
jvm_maven_import_external should be jvm language agnostic

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#7096]
In [49b7d05](https://github.com/bazelbuild/bazel/commit/49b7d05c9d51371936616548a181f1cf12e95323) @jin added a change that made 
`jvm_maven_import_external` java specific.
IMHO it's a mistake since `jvm_maven_import_external` was designed to be the jvm agnostic version and not java bound. For example we, in rules_scala, built on top of it `scala_maven_import_external` and the intent in the original PR was to have future contributors add the small `java_maven_import_external` macro if they so wish.
https://github.com/bazelbuild/bazel/pull/7045 made `jvm_maven_import_external` a bit more generic but kept java as the default. 
I think that better modularization would be to implement the above design at the cost of having a breaking change and remove this default (while introducing java_maven_import_external).

This issue was requested by @dkelmer in https://github.com/bazelbuild/bazel/pull/7045

**Comment by jin** [comment]
I don't quite understand; the workaround here is to add explicit `rule_name` attribute to `jvm_maven_import_external`, and pass `scala_import` into it to create `scala_maven_import_external`, right?

**Comment by ittaiz** [comment]
The workaround after we merge my linked PR then yes.
Having said that should we keep with workarounds? Your change is rather new
and the cost of change should be small

**Comment by jin** [comment]
My change has been around for 3 releases now, so I don't think removing it
immediately is the best option.

**Comment by dkelmer** [comment]
If we make the change, it would need to be gated by an incompatible change
flag.

To me, the workaround seems acceptable and perhaps not worth the churn. But
OTOH, there's about to be churn around these rules anyway as I'm
deprecating the native maven rules. And so if it's the case that we'll want
to do this at some point in the future, now is probably a better time.

**Comment by ittaiz** [comment]
Indeed I don’t mean to do any breaking change but gate it.
I also think that the visibility of the existing code is somewhat limited
due to the chaotic state of the entire rules but that’s just my assessment.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
