### ISSUE TITLE
Duplicate library when external workspace depends on main workspace

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel#7099]
### Description of the problem / feature request:

A user of rules_go reported a warning they're seeing about conflicts between duplicate libraries. The warning is emitted by rules_go, but I believe it indicates a bug in Bazel. It seems like a library target is being treated as two different libraries, since it's referenced with two different names.

Here's their (simplified) repository setup:

* The main workspace contains code they've written.
* They use `go_repository` to import unmodified open source code into external workspaces.
* They use `local_repository` to import internally forked open source code into external workspaces. This code is managed in the same repository as the code in the main workspace, but it's separate as far as Bazel is concerned.

The code in their internal open source forks depends on libraries in the main workspace.

In cases where a library in the main workspace is depended on both by a binary built in the main workspace and by a library in an internally forked workspace, they get an error like this:

```
INFO: From GoLink linux_amd64_stripped/main:
GoLink: warning: package "example.com/corp/lib" is provided by more than one rule:
    @corp//lib:go_default_library
    //lib:go_default_library
Set "importmap" to different paths in each library.
This will be an error in the future.
```

This indicates that a library with the same name (as far as the linker is concerned) is provided by two distinct targets. There is only actually one target though.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Just to be concrete, here's an example that reproduces this. `bazel build :main` prints the error above.

<details>

```
-- WORKSPACE --
workspace(name = "corp")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "7be7dc01f1e0afdba6c8eb2b43d2fa01c743be1b9273ab1eaf6c233df078d705",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.16.5/rules_go-0.16.5.tar.gz"],
)

load("@io_bazel_rules_go//go:def.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains()

local_repository(
    name = "third_party",
    path = "third_party",
)

-- BUILD.bazel --
load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "main",
    srcs = ["main.go"],
    deps = [
        "//lib:go_default_library",
        "@third_party//:go_default_library",
    ],
)

-- main.go --
package main

import (
	"example.com/corp/lib"
	"example.com/third_party"
)

func main() {
	lib.Lib()
	third_party.ThirdParty()
}

-- lib/BUILD.bazel --
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["lib.go"],
    importpath = "example.com/corp/lib",
    visibility = ["//visibility:public"],
)

-- lib/lib.go --
package lib

import "fmt"

func Lib() {
	fmt.Println("Lib called")
}

-- third_party/BUILD.bazel --
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["fork.go"],
    importpath = "example.com/third_party",
    visibility = ["//visibility:public"],
    deps = ["@corp//lib:go_default_library"],
)

-- third_party/WORKSPACE --
workspace(name = "third_party")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "7be7dc01f1e0afdba6c8eb2b43d2fa01c743be1b9273ab1eaf6c233df078d705",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.16.5/rules_go-0.16.5.tar.gz"],
)

load("@io_bazel_rules_go//go:def.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains()

local_repository(
    name = "corp",
    path = "..",
)

-- third_party/fork.go --
package third_party

import "fmt"

func ThirdParty() {
	fmt.Println("ThirdParty called")
}
```

</details>

### What operating system are you running Bazel on?

Linux / amd64

### What's the output of `bazel info release`?

release 0.22.0rc2

### Any other information, logs, or outputs that you want to share?

`bazel query` indicates there is a duplicate here, too. Here's the output of `bazel query 'kind(go_library, deps(:main))'` in the example above.

```
@third_party//:go_default_library
@corp//lib:go_default_library
//lib:go_default_library
```

**Comment by dkelmer** [comment]
The functionality to fix these issues is actually still gated behind a flag, `--experimental_remap_main_repo`. Passing the flag fixes the issue in Jay's repro example. @siddharthab, can you check if passing the flag helps in your repo? Thanks!

**Comment by siddharthab** [comment]
Verified that the flag works. Thanks everyone.

**Comment by dkelmer** [comment]
Awesome, thanks for checking! I'm closing the issue.
