### ISSUE TITLE
Scala support

### ISSUE THREAD

**Issue by benmccann** [bazelbuild/bazel#71]
I'd love to see Bazel support Scala. I thought it'd be helpful to have an item here where those interested can track the issue and discuss, but feel free to close if this isn't the appropriate venue for such a suggestion.

We'd probably want to use [zinc](https://github.com/typesafehub/zinc) to handle compilation.

**Comment by laszlocsomor** [comment]
Although Scala support sounds nice to have, we currently don't have it on the roadmap. Thanks for opening this bug though! Sounds like a good exercise in Skylark [1].

**Comment by laszlocsomor** [comment]
Removing the "help wanted" label until we can finally accept pull requests -- we're working on it!

**Comment by hanwen** [comment]
Bazel doesn't have special support for incremental compilers, and for correctness, we usually prefer non-incremental ones. 

For javac, having a hot JVM is very important. This may also be the case for Scala (in which case, somehting like nailgun would be a useful technology). In any case, we'd want to have something working before we make it fast.

**Comment by fare** [comment]
If while writing this support you find that you need features not yet supported in Skylark, please file bugs about it. I'll be glad to handle them.

**Comment by mrdomino** [comment]
This is relevant to my interests.

**Comment by pspeter3** [comment]
It would be nice to use Bazel to compile Scala without using SBT

**Comment by kchodorow** [comment]
There is some experimental support here: https://github.com/bazelbuild/bazel/tree/master/tools/build_defs/scala.

**Comment by 2rs2ts** [comment]
Very interested in seeing this move forward.

**Comment by damienmg** [comment]
I think this bug should be closed in favor for more specific one (which improvement to the current rule is specifically needrd)

**Comment by damienmg** [comment]
Closing as we have a preliminary version of the ruleset. Please open more specific request if you have.
