### ISSUE TITLE
Provide an example for common features attribute

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel#710]
The documentation for the `features` common attribute describe what the attribute does but doesn't really give any details about what _features_ are and how they are used:

> Features on a rule modify the features currently enabled on the package level via the features attribute.
> For example, if the features ['a', 'b'] are enabled on the package level, and a rule features attribute contains ['-a', 'c'], the features enabled for the rule will be 'b' and 'c'.

It would be good to provide an example or two:

**Comment by davidstanke** [comment]
Here's the doc page where features are mentioned: https://docs.bazel.build/versions/master/be/common-definitions.html
