### ISSUE TITLE
macOS: New C++ Starlark API provides no way to use compiler

### ISSUE THREAD

**Issue by mboes** [bazelbuild/bazel#7105]
### Description of the problem

The new C++ Starlark API provides a `find_cpp_toolchain()` function, which returns a `cc_toolchain` struct, which embeds the path to the compiler, linker and other tools in the C++ toolchain. The problem is this: on macOS, `cc_toolchain.compiler_executable()` returns a relative path (rather than an absolute path everywhere else), but since this path is a string, there is no way to declare the compiler as an action input, hence making actions that call the compiler in sandboxed builds fail.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Consider a a `BUILD` with the following content:

```python
load(":foo.bzl", "foo_rule")
foo_rule(name = "foo", visibility = ["//visibility:public"])
```

with `foo.bzl`:

```python
load("@bazel_tools//tools/cpp:toolchain_utils.bzl", "find_cpp_toolchain")

def foo_rule_impl(ctx):
    cc_toolchain = find_cpp_toolchain(ctx)
    file = ctx.actions.declare_file("foobar")
    ctx.actions.run_shell(
      outputs = [file],
      command = "{cc} --version > {file}".format(cc = cc_toolchain.compiler_executable(), file = file.path),
    )
    return [DefaultInfo(files = depset([file]))]

foo_rule = rule(
    foo_rule_impl,
    attrs = {
        "_cc_toolchain": attr.label(
            default = Label("@bazel_tools//tools/cpp:current_cc_toolchain"),
        ),
    }
)
```

We get the following build output on macOS (Linux works fine):

```
bazel build //:foo -s
INFO: Invocation ID: bdcfe97f-6d58-4a4a-b72c-8a2489c77744
INFO: Analysed target //:foo (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
SUBCOMMAND: # //:foo [action 'SkylarkAction foobar']
(cd /private/var/tmp/_bazel_distiller/6e118b7313fc257998086ed38d79f1ff/execroot/project && \
  exec env - \
  /nix/store/742pjmksag4nz6va143hbhxrf5m2r9pb-bash/bin/bash -c 'external/local_config_cc/cc_wrapper.sh --version > bazel-out/darwin-fastbuild/bin/foobar')
ERROR: /Users/distiller/project2/BUILD:2:1: error executing shell command: '/nix/store/742pjmksag4nz6va143hbhxrf5m2r9pb-bash/bin/bash -c external/local_config_cc/cc_wrapper.sh --version > bazel-out/darwin-fastbuild/bin/foobar' failed (Exit 127) bash failed: error executing command /nix/store/742pjmksag4nz6va143hbhxrf5m2r9pb-bash/bin/bash -c 'external/local_config_cc/cc_wrapper.sh --version > bazel-out/darwin-fastbuild/bin/foobar'

Use --sandbox_debug to see verbose messages from the sandbox
/nix/store/742pjmksag4nz6va143hbhxrf5m2r9pb-bash/bin/bash: external/local_config_cc/cc_wrapper.sh: No such file or directory
Target //:foo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.168s, Critical Path: 0.04s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

The reason the build outcome is different on macOS is because on that platform, the compiler is always a wrapper, called `cc_wrapper.sh`. We get a relative path to the wrapper, rather than an absolute path to the compiler like in Linux.

### What operating system are you running Bazel on?

macOS (Darwin)

### What's the output of `bazel info release`?

0.20.0

### Any other information, logs, or outputs that you want to share?

rules_haskell cannot use `ctx.host_fragments` to get the C++ toolchain anymore in recent Bazel versions, but because of this bug, can't use the new interface either on macOS (Linux is fine). There is possibly a workaround, which we used before, which consists in creating a symlink to the relative path of the compiler, to workaround the sandbox. But this has the potential to break reproducible builds.

**Comment by mboes** [comment]
It appears that all `File`s for all C++ tools are all in `ctx.files._cc_toolchain`. Is this documented anywhere? So far we've only managed to use the new Starlark API by copy/pasting various snippets helpfully provided in tickets by @hlopko, but we are still non the wiser.

**Comment by hlopko** [comment]
Hi Mathieu,

I'm sorry you have trouble there. As you correctly noticed, there are 2 independent things that both have to happen for a compilation to succeed.

First is the correct command line, that is done by the Starlark API to the C++ toolchain (feature configuration, variables, action names, `get_memory_inefficient_command_line` are all parts of this api, `cc_toolchain.compiler_executable()` is only half-way there, we'll probably get rid of it in the future, but it's there today so feel free to use it).

Second is the correct action inputs. These are unfortunately not related to the command line at all. The way how to access them is through the [DefaultInfo.files](https://docs.bazel.build/versions/master/skylark/lib/DefaultInfo.html#files). You can access that as you wrote, or by calling:


    find_cpp_toolchain(ctx).files


Under the hood we have more fine grained collections that we will eventually expose to Starlark as well, but `files` is what works today.

We are going to add a page to bazel.build about how to integrate with C++ rules (both the C++ toolchain and the [Sandwich API](https://github.com/bazelbuild/bazel/issues/4570)), so the life will be easier soon. Is there anything else you struggled with that we should document more?

**Comment by mboes** [comment]
Thank you for the info. I remember struggling with whether to use `compiler_executable()` or `get_tool_for_action()`. Also whether to use `get_environment_variables()` or to not bother with it. In general, the examples you pasted in this and other tickets have been helpful. I found similar ones on StackOverflow. But would be easier to refer back to them if they are part of the documentation your are preparing.

**Comment by hlopko** [comment]
https://github.com/bazelbuild/rules_cc/blob/master/examples/my_c_compile/my_c_compile.bzl is currently the best "documentation" :)
