### ISSUE TITLE
Bazel reports build success when it was not successful

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#7115]
This bug was filed at https://github.com/bazelbuild/continuous-integration/issues/449, but it should be a Bazel bug

/cc @c-parsons @laurentlb

**Comment by laurentlb** [comment]
In the interpreter, we throw an exception for this. It is properly reported one level up: `package contains errors: e2e/output_runner`. But later, something swallows the error. I don't know what happens, I suspect it's related to `--keep_going`, so assigning to core team to investigate.

**Comment by laurentlb** [comment]
Repro:
```
touch WORKSPACE
mkdir sub
touch test.sh && chmod +x test.sh
echo 'sh_test(name = "test", srcs = ["test.sh"])' > BUILD
echo 'parse error' > sub/BUILD
bazel test //... -k
```

If one package cannot be loaded, but all other tests pass, Bazel returns 0.

**Comment by ericfelly** [comment]
Nathan, can you take a look?

**Comment by haxorz** [comment]
is this really P1?

**Comment by jin** [comment]
@haxorz if it's not a P1 according to the [definitions](https://www.bazel.build/maintainers-guide.html#priority), please reassign as required. thanks!

**Comment by meteorcloudy** [comment]
If we don't fix this issue, Bazel users (including us) could miss potential failures in the build, I think it's a pretty serious issue (P1).

**Comment by laurentlb** [comment]
I had a quick look yesterday. This issue also affects Google (Blaze) and has been around for at least a year. I'm surprised it didn't come up before.

**Comment by meteorcloudy** [comment]
Thank you!
