### ISSUE TITLE
Can't debug bazel

### ISSUE THREAD

**Issue by dkelmer** [bazelbuild/bazel#7118]
### Description of the problem / feature request:
Debugging a bazel built from head causes the server to crash at start up

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I synced to commit 070c5ba5b037c8334d2cc9a001b32019be64262e.
`bazel build src:bazel`
then 
`$devbazel --host_jvm_debug build //some:target`

### What operating system are you running Bazel on?

linux

### What's the output of `bazel info release`?

0.21.0

### Any other information, logs, or outputs that you want to share?
The error is: 
Server crashed during startup. Now printing /usr/local/google/home/dannark/.cache/bazel/_bazel_dannark/14bb3428d13206c99a2617067fb48a81/server/jvm.out
Error occurred during initialization of VM
Could not find agent library jdwp on the library path, with error: libjdwp.so: cannot open shared object file: No such file or directory

`bazel build src:bazel-dev`
`$devbazel --host_jvm_debug build //some:target`

does not throw the same error

**Comment by buchgr** [comment]
@meisterT did you check by how much the binary size would increase if we shipped the debug library? Building the `src:bazel-bin-dev` is a huge hit to my productivity.

**Comment by dkelmer** [comment]
Just out of curiosity, why is building the dev version a hit to your
productivity? I thought the dev version builds faster. So I'm wondering if
there's something I'm missing that could make me more productive :)

**Comment by buchgr** [comment]
@dkelmer the dev version introduces a genrule that builds the jdk and that action can't be cached, because building the jdk is not deterministic. So on every incremental build of Bazel we are rebuilding the dev version, which takes about 20 seconds on my machine.

**Comment by buchgr** [comment]
#7154 didn't actually fix this issue. While it's possible to start the debugger and set breakpoints no stack frames are available.

**Comment by buchgr** [comment]
awww nevermind. I am stupid.
