### ISSUE TITLE
Remove Python uses_shared_libraries provider field

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#7121]
On the py provider, `uses_shared_libraries` is unused in Bazel and only used for a deprecated runtime within Google. There's likely no need to keep it in the codebase.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
