### ISSUE TITLE
Error while "bazel clean": Cannot delete path... Permission denied

### ISSUE THREAD

**Issue by Maxtoq** [bazelbuild/bazel#7125]
I was building Tensorflow from source with Bazel and a file got blocked by my antivirus and the build failed.
I unblocked the file, deactivated my antivirus, tried again and got this error:

> ERROR: C:/users/maxim/_bazel_maxim/xv6zejqw/external/nasm/BUILD.bazel:8:1: failed to delete output files before executing action: Cannot delete path 'C:/users/maxim/_bazel_maxim/xv6zejqw/execroot/org_tensorflow/bazel-out/x64_windows-opt/bin/external/nasm/nasm.exe': ERROR: src/main/native/windows/file-jni.cc(104): nativeDeletePath(C:/users/maxim/_bazel_maxim/xv6zejqw/execroot/org_tensorflow/bazel-out/x64_windows-opt/bin/external/nasm/nasm.exe): ERROR: src/main/native/windows/file.cc(471): DeleteFileW(C:/users/maxim/_bazel_maxim/xv6zejqw/execroot/org_tensorflow/bazel-out/x64_windows-opt/bin/external/nasm/nasm.exe): Permission denied.

I did a bazel shutdown and then a bazel clean --expunge that failed with almost the same error log:

> ERROR: Cannot delete path 'C:/users/maxim/_bazel_maxim/xv6zejqw/execroot/org_tensorflow/bazel-out/x64_windows-opt/bin/external/nasm/nasm.exe': ERROR: src/main/native/windows/file-jni.cc(104): nativeDeletePath(C:/users/maxim/_bazel_maxim/xv6zejqw/execroot/org_tensorflow/bazel-out/x64_windows-opt/bin/external/nasm/nasm.exe): ERROR: src/main/native/windows/file.cc(471): DeleteFileW(C:/users/maxim/_bazel_maxim/xv6zejqw/execroot/org_tensorflow/bazel-out/x64_windows-opt/bin/external/nasm/nasm.exe): Permission denied.

I'm on Bazel 0.18.0.

Is there anything I can do ?
Thanks.

**Comment by meteorcloudy** [comment]
Can you check if nasm.exe is somehow still running in task manager?

**Comment by mzeren-vmw** [comment]
You might also use Process Explorer [1] to search for other processes that have an open handle to nasm.exe?
[1] https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

**Comment by Maxtoq** [comment]
Good call, I couldn't find the related processes, but I simply restarted my PC and it did the job.
So the problem is solved.
Thanks.

**Comment by official-minister** [comment]
I have same problem and ervery time I must restart my PC, I think it should be an other way to solve it.
