### ISSUE TITLE
experimental_heuristic test sharding hasn't changed in almost 4 years

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#7129]
Hi,
I'm considering using test sharding and saw `experimental_heuristic` option in the [command line reference] (https://docs.bazel.build/versions/master/command-line-reference.html#flag--test_sharding_strategy).
When I went to the [code](https://github.com/bazelbuild/bazel/commit/aded1c2dbd0e06e60ff768094ab9efcc9c680911#diff-9c332600ee30b11519fe7c1ada9bc9b7) it seems that in the first commit it was already added as experimental saying:
```
Heuristic sharding is intended as a one-off experimentation tool for determing the benefit from sharding certain tests. Please don't keep this option in your blazerc or continuous build
``` 
Is this still experimental? Should it be removed? Is it a google only feature? Do you know if RBE supports this?

**Comment by ittaiz** [comment]
Thanks! Can you clarify a bit about what you mean by 

> encode the specific sharding in your BUILD file

?

**Comment by agoulti** [comment]
You can set "shard_count" in your BUILD file for each test rule that supports it.

See https://docs.bazel.build/versions/master/be/common-definitions.html#test.shard_count

Here is an example: https://source.bazel.build/bazel/+/master:src/test/shell/integration/BUILD;l=35?q=shard_count

The experimental_heuristic simply sets sharding for tests according to their size: https://source.bazel.build/bazel/+/master:src/test/java/com/google/devtools/build/lib/packages/TestSizeTest.java;l=45?q=getDefaultShards

**Comment by ittaiz** [comment]
Thank you for this thorough answer!
