### ISSUE TITLE
Promote --experimental_enable_repo_mapping to not be experimental

### ISSUE THREAD

**Issue by dkelmer** [bazelbuild/bazel#7132]
All PRs related to this change have been submitted and so the feature is stable. Making this flag non experimental is a no-op for users not currently using the feature because users still need to opt-in by using the `repo_mapping` attribute in repository rules. Users currently using the feature will be able to stop passing the flag. 

This will happen in 2 stages:
1. Make the flag a no-op and emit a warning that it is unneeded. This means that people who have put the flag in bazelrcs won't break immediately.
2. Remove the flag.

**Comment by meisterT** [comment]
This has been removed a while ago.
