### ISSUE TITLE
Race condition when running multiple cc_test coverage in one command line

### ISSUE THREAD

**Issue by c-nuro** [bazelbuild/bazel#7134]
### Description of the problem / feature request:

Race condition when running multiple cc_test coverage in one command line

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

run `bazel coverage //...` in a codebase with may cc_test.
There's a chance that some coverage report for executed lines are not reported as covered for some test cases.

### What operating system are you running Bazel on?

ubunut 16.04

### What's the output of `bazel info release`?

release 0.19.2

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

We have spawn strategy standalone.

From test log, the race condition is:
After the test executed, `lcov` is executed with CWD at executation_root. Through strace of that lcov command, in the `lcov` process, it will unpack the .gcda files, generate many .gcov files for all sources under current directory, parse the files, and delete them. These `.gcov` temporary files are located at executation root.
If multiple `lcov` process is running at the same time, and same file names of `.gcov` files are used, it will cause race condition if the other process overwritten/delete the `.gcov` file.

**Comment by iirina** [comment]
Can you reproduce using `--incompatible_cc_coverage`?

**Comment by c-nuro** [comment]
0.19.2 doesn't have `--incompatible_cc_coverage`. Also, `experimental_cc_coverage` doesn't work for our case..

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
