### ISSUE TITLE
bazel query fails for target that has '=' sign in their name

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/bazel#7142]
### Description of the problem:

If I refer to a target with `=` sign in its name in bazel query
EG:
```
bazel query "allpaths(//a/b:c=abc, //d/g:f)" --output=graph
```
It fails. We need to either not allow this character or support it in bazel query

**Comment by ittaiz** [comment]
@aehlig 
```
bazel query --output=build //foo:agg=a_b
Starting local Bazel server and connecting to it...
ERROR: Error while parsing '//foo:agg=a_b': unexpected token '=' after query expression '//foo:agg'
Loading: 0 packages loaded
```

**Comment by ittaiz** [comment]
@aehlig any idea how difficult it would be to support `=`?

**Comment by taldod2** [comment]
@ittaiz @or-shachar any update on this?

**Comment by michajlo** [comment]
Does it work if you quote the target containing the '=' - `bazel query 'allpaths("//a/b:c=abc", //d/g:f)'`

**Comment by taldod2** [comment]
yes it is, thanks :-)

**Comment by or-shachar** [comment]
so we can probably close this one :) Thanks @michajlo !
