### ISSUE TITLE
Missing dependency declarations error for system include files

### ISSUE THREAD

**Issue by kramasamy** [bazelbuild/bazel#715]
I am compiling my project using bazel 0.1.2. For compiling a C++ files, it complains about dependency declarations on system include files. How to solve this?

````
ERROR: /data/jenkins/workspace/heron-staging_2/heron/common/src/cpp/basics/BUILD:3:1: undeclared inclusion(s) in rule '//heron/common/src/cpp/basics:basics-cxx':
20:20:32 this rule is missing dependency declarations for the following files included by 'heron/common/src/cpp/basics/randutils.cpp':
20:20:32   '/opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-redhat-linux/4.8.1/include/stddef.h'
20:20:32   '/opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-redhat-linux/4.8.1/include/stdarg.h'
20:20:32   '/opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-redhat-linux/4.8.1/include/stdint.h'.
20:20:33 ____Elapsed time: 141.787s, Critical Path: 131.46s
````

**Comment by davidzchen** [comment]
@kramasamy Can you try updating your `CROSSTOOL` file and add a `cxx_builtin_include_path` for `/opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-redhat-linux/4.8.1`?

**Comment by kchodorow** [comment]
Closing due to lack of reply, feel free to comment if you try @davidzchen's solution and still have problems.

**Comment by kramasamy** [comment]
@kchodorow - sorry to respond late. Yes, the suggestion worked. Thanks for the help
