### ISSUE TITLE
Large binary size when building optimized Android NDK binaries

### ISSUE THREAD

**Issue by feliwir** [bazelbuild/bazel#7150]
### Description of the problem / feature request:

I am building an android app with native code, for which i use `cc_library` etc. When building with default `bazel build //app/...` the size of the native `.so` file is about 30MB. To reduce the binary size i passed `-c opt` to strip debug symbols and optimize the build, but the native library ended up being 271MB (yes, just the `.so` file). I have no idea how it got that large, because it was just 6MB when i've built the same source with android studio & cmake before.
When building with `-cxxopts=-O2 --strip always` and without `-c opt` i could atleast get down to 18MB size.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Not sure.

### What operating system are you running Bazel on?

Ubuntu 18.10

### What's the output of `bazel info release`?

INFO: Invocation ID: 12806307-0534-40cc-a3c7-b0f09a2975c7
release 0.21.0

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Since this is a propietary project i can't share any more information. Since i asked in Slack before i know that others have encountered similar problems.

**Comment by jin** [comment]
@hlopko are there any known issues around `-c opt` in the context of this issue?

**Comment by matthewxperiel** [comment]
We also see a similar size issue when build with `-c opt`.

**Comment by hlopko** [comment]
Can you try the build with `--nolegacy_whole_archive`?

**Comment by matthewxperiel** [comment]
Building with `--nolegacy_whole_archive` did not reduce the size of the binary

**Comment by jin** [comment]
Marking as P2, we'll re-look at the default NDK flags while overhauling the current CROSSTOOL approach to use Starlark/Toolchains.

**Comment by feliwir** [comment]
I think this is still open?

**Comment by ahumesky** [comment]
I wonder if you're able to reproduce this behavior with the Starlark rules_android_ndk? The native android_ndk_repository has been deleted from bazel 8 and migrated to Starlark in https://github.com/bazelbuild/rules_android_ndk
