### ISSUE TITLE
incompatible_disable_legacy_proto_provider: Remove legacy `dep.proto.` access to the proto provider

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#7152]
We are migrating off of legacy providers that are addressed by name to providers addressed: https://bazel.build/designs/skylark/declared-providers.html

This bug is for migrating the provider containing information about `.proto` files. The following changes are required in Starlark sources:

* Change the way the provider is accessed from `ctx.attr.dep.proto.` to `ctx.attr.dep[ProtoInfo]`
* Change the way the presence of provider is checked from `hasattr(dep, "proto")` to `ProtoInfo in dep`
* Change the way a rule requires a provider from `providers = [["​proto"]]` to `providers = [[ProtoInfo]]`

**Comment by philwo** [comment]
This flag was not flipped in time for the Bazel 0.23.0 release and will thus be postponed to Bazel 0.24.0.

**Comment by drigz** [comment]
`ProtoInfo` was introduced in 0.22.0. Is there a way for code to be compatible with both 0.21.0 and 0.24.0 Bazel versions?

**Comment by laurentlb** [comment]
As it would break many projects on the CI and we plan to cut Bazel 0.24 tomorrow, the flag flip will be postponed.

**Comment by katre** [comment]
This issue was tagged as "breaking-change-0.24" but does not appear ready to be flipped in the [0.24.0 release](https://github.com/bazelbuild/bazel/issues/6968). If this is incorrect please comment on that issue and discuss with me.

**Comment by dkelmer** [comment]
Seems like the flag wasn't flipped in time for the 0.25 release. Changing window.

**Comment by hlopko** [comment]
And it also wasn't flipped for 0.26 or 0.27, so 1.0 it is :)

**Comment by lberki** [comment]
Fix for rules_rust is at https://github.com/bazelbuild/rules_rust/pull/242

**Comment by lberki** [comment]
For fix Bazel is at https://github.com/bazelbuild/bazel/pull/8938

**Comment by lberki** [comment]
Fix for `ts_proto_library` (and thus Bazel Codelabs) is at https://github.com/bazelbuild/rules_nodejs/pull/925 .

**Comment by lberki** [comment]
Pull request to fix Envoy: https://github.com/envoyproxy/envoy/pull/7850

**Comment by lberki** [comment]
Bug for rules_nodejs: https://github.com/bazelbuild/rules_nodejs/issues/979

**Comment by lberki** [comment]
Codelabs issue: https://github.com/bazelbuild/codelabs/issues/11
