### ISSUE TITLE
incompatible_disable_proto_source_root: remove the attribute `proto_library.proto_source_root`

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#7153]
The `proto_library.proto_source_root` attribute is going away in favor of the more flexible `proto_library.strip_import_prefix` and `proto_library.import_prefix`.

In order to migrate your BUILD files, replace `proto_source_root` with `strip_import_prefix`: since the only allowed value of that attribute is the package the rule is in, simply replace the name of the attribute and prepend `/` to its value. For example, the rule (necessarily in `foo/bar/BUILD`):

```
proto_library(name="proto", srcs=["proto.proto"], proto_source_root="foo/bar")
```

Needs to be migrated to:

```
proto_library(name="proto", srcs=["proto.proto"], strip_import_prefix="/foo/bar")
```

**Comment by philwo** [comment]
This flag was not flipped in time for the Bazel 0.23.0 release and will thus be postponed to Bazel 0.24.0.

**Comment by katre** [comment]
This issue was tagged as "breaking-change-0.24" but does not appear ready to be flipped in the [0.24.0 release](https://github.com/bazelbuild/bazel/issues/6968). If this is incorrect please comment on that issue and discuss with me.

**Comment by dkelmer** [comment]
Seems like the flag was still not flipped, changing breaking-change label to 0.26

**Comment by dslomov** [comment]
What is the status of this change wrt migration/planned flag flips?

**Comment by hlopko** [comment]
This will be flipped in 1.0. Migration is ongoing :)

**Comment by lberki** [comment]
Update: I sent out pull requests for the last two broken repositories:

https://github.com/bazelbuild/rules_scala/pull/793
https://github.com/bazelbuild/rules_rust/pull/241

**Comment by dslomov** [comment]
Is migration tooling avaliable/possible?
