### ISSUE TITLE
toolchain_hostjdk8 breaks in bazel 0.21: passing -Xbootclasspath/p to java9

### ISSUE THREAD

**Issue by asuffield** [bazelbuild/bazel#7158]
### Description of the problem / feature request:

--java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8 no longer works in bazel 0.21. The javac workers fail to start with:

---8<---8<--- Start of log ---8<---8<---
-Xbootclasspath/p is no longer a supported option.
ion.
---8<---8<--- End of log ---8<---8<---

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

git clone https://github.com/bazelbuild/examples/
cd examples
bazel build //:ProjectRunner --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8

### What's the output of `bazel info release`?

release 0.21.0

What I've figured out so far: this combination tries to run the remotejdk (zulu java 9) with JDK8_JVM_OPTS, which are not accepted by the new jvm.

**Comment by cushon** [comment]
Are you setting a `--host_javabase`? `--java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8` only works if you explicitly configure a JDK 8 host javabase.

Does your build work if you remove the `--java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8` flag and use the default toolchain?

**Comment by asuffield** [comment]
Ah, that would explain why it fails. Yes, the default toolchain is fine.

So we can call this one an incomprehensible error message for an invalid combination of options, and see if there's some way to report the actual problem.

**Comment by lberki** [comment]
Yeah, that's a pretty accurate description. Marking this P3 because this is "just" an error message issue.

**Comment by perezd** [comment]
So I'm seeing this as well if I do the following in my bazelrc:
```
common --define=ABSOLUTE_JAVABASE=/usr/lib/jvm/java-11-openjdk-amd64 \
       --javabase=@bazel_tools//tools/jdk:absolute_javabase \
       --host_javabase=@bazel_tools//tools/jdk:absolute_javabase \
       --java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla \
       --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla

```
Following along here: https://github.com/bazelbuild/bazel/issues/5723
I am trying to run my existing bazel project using host jdk11 (ubuntu)

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
