### ISSUE TITLE
*.ldscript file will not propagate to the final step when linking

### ISSUE THREAD

**Issue by chin33z** [bazelbuild/bazel#716]
```
cc_binary(
    name = "hello",
    srcs = ["main.c"],
    deps = [":lib"]  <----":lib.ldscript" to add here
)

cc_library(
    name = "lib",
    srcs = ["lib.c"],
    linkopts = ["-Wl,--version-script", ":lib.ldscript"],
    deps = [":lib.ldscript"],
)
```

Assume all files were placed & edited properly.

This will be fine :
`$> bazel build //:lib`

This will cause gcc error (lib.ldscript: No such file or directory) :
`$> bazel build //:hello`

However, if I add **":lib.ldscript"** to the deps of "hello". I will not get the error.
But from  encapsulated perspective, "hello" should not take care of this information.(The linker script is for "lib" only)

I guess this is because Bazel link all the objects/files in th last steps & the *.ldscript in deps is not propagated to the cc_binary(hello) when linking.

Is this a bug or WAD? Thanks.

**Comment by ulfjack** [comment]
It would help if you could show the libldscript rule. I think the most
likely reason is a file extension mismatch - we require linker scripts to
end with ".ld", ".lds", or ".ldscript".

**Comment by chin33z** [comment]
lib.ldscript content:
```
{
  global: *;
};
```

I know the file extension requirement in deps (*.ld, *lds, *.ldscript).
And I think the problem is not the content of the linker script.

**Comment by ulfjack** [comment]
In the email I got, it said ":libldscript" not ":lib.ldscript". Well, it does sound like a bug.

**Comment by chin33z** [comment]
> In the email I got, it said ":libldscript" not ":lib.ldscript"

sorry, what are you referring to?
do I misspelling something? I think I always type ":lib.ldscript".
Thanks.

**Comment by chin33z** [comment]
It does behave weird for me. I think the "-Wl,--version-script" argument should only present when linking the "lib". However, it shown up when "hello" is linked. Thus, the lib.ldscript is not in the sandbox at the moment.(I guess)

**Comment by burkpojken** [comment]
Hi!
Is it possible to push for this feature to be implemented earlier than 1.0??
Or even make it more generic to be able to add any type of target as a dependency (or e.g. tools = [":myLinkscript"]) that then can be used with $location in e.g. linkopts?

**Comment by mhlopko** [comment]
CC @oquenchil

**Comment by cpsauer** [comment]
FWIW, I'm seeing this work correctly when used a little differently.

The specific case: I'm passing "-Wl,--version-script,$(location example.ldscript)" into a cc_library's linkopts, and seeing things get compiled correctly by an android_binary that indirectly depends on it.

**Comment by nicmcd** [comment]
> The specific case: I'm passing "-Wl,--version-script,$(location example.ldscript)" into a cc_library's linkopts, and seeing things get compiled correctly by an android_binary that indirectly depends on it.

@cpsauer, how did you declare the example.ldscript file? Did you add it to "data"?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
