### ISSUE TITLE
Bazel CI: Bazel watcher is broken by --incompatible_remote_symlinks

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#7160]
Bazel watcher was enabled in downstream recently, but it is failing with
```
ERROR: /var/lib/buildkite-agent/builds/bk-docker-4n5t/bazel-downstream-projects/bazel-watcher/e2e/live_reload/BUILD:6:1: Couldn't build file e2e/live_reload/go_default_test/bazel0.17.1/test.log:  failed: Unexpected IO error: /home/bazel/.cache/bazel/_bazel_bazel/e7a6b0ed9ee55bc72171e2b7ad0a356e/execroot/__main__/external/build_bazel_bazel_0_17_1/bazel-real (No such file or directory)
```
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/755#74468f41-4af9-4c74-9758-61fae4eb21c0

Found 30536baa4a410d8c0a7adab5cd58cd8a2ac7e46c as the culprit by https://buildkite.com/bazel/culprit-finder/builds/73#d0aa485f-21f8-4db1-86b5-14cbfe4d166e

**Comment by buchgr** [comment]
Fixed by #7174
