### ISSUE TITLE
Trouble with nodejs_binary dependencies

### ISSUE THREAD

**Issue by rysteboe** [bazelbuild/bazel#7161]
Opening up a second bug here since that's what @aiuto did for me on the last issue I reported.

https://github.com/bazelbuild/rules_nodejs/issues/500

There's a good chance this one is pure user error - would appreciate any help in resolving.

**Comment by jin** [comment]
cc @alexeagle

**Comment by aiuto** [comment]
Jin:  Who is investigating? since there is no assignee?

**Comment by jin** [comment]
@aiuto my bad, mislabeled.

**Comment by dslomov** [comment]
Closing per https://github.com/bazelbuild/rules_nodejs/issues/500#issuecomment-457597135
