### ISSUE TITLE
Error about building outside workspace isn't helpful

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#7162]
### Description of the problem / feature request:

If the user builds in the wrong directory, the error message is not that helpful.

To repro, I just make a new directory on Windows and run `bazel build`:

```
C:\Users\alexeagle\Projects\try_bazel                                                                                                           
λ bazel build                                                                                                                                   
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
C:\Users\alexeagle/.bazelrc                                                                                                                     
ERROR: The 'build' command is only supported from within a workspace.                                                                           
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".                  
INFO: Invocation ID: a3cb664c-fa0b-409e-a45f-7a0ea5445e12                                                                                       
```

First, there's a bunch of spam here.
Next, we say "only supported from within a workspace", but this assumes the user has read some documentation. First-time users probably haven't.

Note, this is even worse if you run Bazel in an Angular project, because we also use the term "workspace" to refer to a directory with an `angular.json` file. So our users think that they *are* in a workspace when they ran `bazel`

### Suggested change

I think the error should:
- how to understand: mention `WORKSPACE` file, as this defines whether you're in a bazel workspace
- how to fix: say that you're either in the wrong directory, or didn't create a `WORKSPACE` file
- how to learn more: point to the documentation on bazel.build about workspaces

**Comment by dslomov** [comment]
```
ERROR: The 'build' command is only supported from within a workspace (below a directory having a WORKSPACE file).
See documentation at https://docs.bazel.build/versions/master/build-ref.html#workspace
```

**Comment by s1530129650** [comment]
he 'build' command is only supported from within a workspace (below a directory having a WORKSPACE file).
See documentation at https://docs.bazel.build/versions/master/build-ref.html#workspace

**Comment by ShukantPal** [comment]
I think this issue might be relevant again for bzlmod users that are don't have `WORKSPACE` files.
