### ISSUE TITLE
Rule reference to target can't supply helpful error

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#7165]
If a novice user uses rules_typescript, but didn't install the typescript dependency via npm, then they get this error:

```
ERROR: C:/users/alexeagle/projects/try_bazel/BUILD.bazel:3:1: every rule of type ts_library implicitly depends upon the target '@npm//typescript:typescript__typings', but this target could not be found because of: no such package '@npm//typescript': BUILD file not found on package path
ERROR: Analysis of target '//:root' failed; build aborted: no such package '@npm//typescript': BUILD file not found on package path
```

Bazel knows that the ts_library rule has an attribute that refers to `@npm//typescript:typescript__typings`. It could print the docstring from that attribute, or allow the ts_library rule some other way to help the user fix the error.
Another way to fix this would be for rules_nodejs to be able to intercept all `no such package: @npm//...`  messages and say "you need to npm install this package"

**Comment by dslomov** [comment]
> If a novice user uses rules_typescript, but didn't install the typescript dependency via npm, then they get this error:
> 
> ```
> ERROR: C:/users/alexeagle/projects/try_bazel/BUILD.bazel:3:1: every rule of type ts_library implicitly depends upon the target '@npm//typescript:typescript__typings', but this target could not be found because of: no such package '@npm//typescript': BUILD file not found on package path
> ERROR: Analysis of target '//:root' failed; build aborted: no such package '@npm//typescript': BUILD file not found on package path
> ```
> Bazel knows that the ts_library rule has an attribute that refers to `@npm//typescript:typescript__typings`. It could print the docstring from that attribute, or allow the ts_library rule some other way to help the user fix the error.

I guess we could add smth like `error_doc` argument to attr.label that will be a way to provide a message for implicit attributes that cannot be resolved.

> Another way to fix this would be for rules_nodejs to be able to intercept all `no such package: @npm//...` messages and say "you need to npm install this package"

This probably requires much more design...
Another way to solve this for Angular would be for the angular cli to intercept this message and provide some suggestion in npm terms - wdyt @alexeagle?

@aehlig wdyt in general?

**Comment by aehlig** [comment]
> Bazel knows that the ts_library rule has an attribute that refers to `@npm//typescript:typescript__typings`. It could print the docstring from that attribute [...]

This is actually easy to do (without changing any interfaces). My proposal is the following patch series.

  https://bazel-review.googlesource.com/c/bazel/+/91990 Extend Attribute by doc string 
  https://bazel-review.googlesource.com/c/bazel/+/91991 Set doc on SkylarkAttr
  https://bazel-review.googlesource.com/c/bazel/+/91992 For missing implicit dependencies show doc string

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment]
Since 6afb4fdec7fec0cce8b3f4a5246285b3350bfa4e the doc string for missing implicit dependencies is shown. In this way, helpful information can be provided by the tool author.
