### ISSUE TITLE
Neither Bazel or Bazel-Remote verifies the sha256 when GET files from server

### ISSUE THREAD

**Issue by bayareabear** [bazelbuild/bazel#7169]
Step to reproduce:
Use https://github.com/bazelbuild/examples and build with Bazel-Remote cache. In the cache server modify one of the files in CAS folder and verify the sha256 indeed changed using "openssl dgst -sha256", then build again. You can notice when Bazel-Remote get the modified file, you can see it just returns 200 and the build succeeds.

Question is how it can ensure the correctness of the final build output?

**Comment by buchgr** [comment]
@bayareabear which version of Bazel are you using? We do have code that is expected to verify that the digests match, but it's possible that it's broken.

**Comment by bayareabear** [comment]
I am using the following version:
xzhang3$ bazel version
INFO: Invocation ID: 7e7aca66-bb36-4374-af0b-5954e1e267ad
Build label: 0.21.0
Is the check on every AC and CAS entry or just some of them? I just randomly modified one CAS entry?
