### ISSUE TITLE
pkg_tar results in an import error

### ISSUE THREAD

**Issue by rjaquino** [bazelbuild/bazel#717]
I tried to use a pkg_tar rule, and it seems like the py_binary generated is setting PYTHON_PATH to the wrong location. We see the following error:
```sh
  File "/private/var/tmp/_bazel_asana/6ad5fad239bea6b8300de3d21f3646d8/asana2/bazel-out/host/bin/tools/build_defs/pkg/build_tar.runfiles/luna2/tools/build_defs/pkg/build_tar.py", line 22, in <module>
    from tools.build_defs.pkg import archive
```

When we modify build_tar.py to print out the PYTHON_PATH it is trying to use, we get `/private/var/tmp/_bazel_asana/6ad5fad239bea6b8300de3d21f3646d8/asana2/bazel-out/host/bin/tools/build_defs/pkg/build_tar.runfiles/`, which is missing the trailing "luna2", which is our workspace name. Is there anything we have to do to get the workspace name included in the PYTHON_PATH, or is there something wrong with the build_tar py_binary?

**Comment by kchodorow** [comment]
I'd guess that py_binary isn't setting up its runfiles in the right directory.  To work around it for now, can you use the default workspace name ("")?

**Comment by kchodorow** [comment]
This is set up correctly in 0.3.0.
