### ISSUE TITLE
Please add C++ toolchain helpers for extensions of output files

### ISSUE THREAD

**Issue by jmillikin** [bazelbuild/bazel#7170]
When compiling C++, different compiler implementations have different preferred file extensions. For example on UNIX object code is `.o` and on Windows it's `.obj`. The new sandwich-enabled C++ toolchain ([cc_common](https://docs.bazel.build/versions/master/skylark/lib/cc_common.html) + [CcInfo](https://docs.bazel.build/versions/master/skylark/lib/CcInfo.html)) supports configuring these file extensions but doesn't support querying them.

Please add some accessor functions so rules authors can figure out what extensions the C++ toolchain expects.

Example types and their extensions:
* Object code: `.o` (UNIX), `.obj` (Windows)
* Static library: `.a` (UNIX), `.lib` (Windows)
* Dynamic library: `.so` (Linux + BSD), `.dylib` (macOS), `.dll` (Windows)
* Executable: `.exe` (Windows)

There's also associated non-executable outputs like debug symbols, code coverage, and precompiled headers.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
