### ISSUE TITLE
Upgrade jarjar

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#718]
See https://groups.google.com/d/msgid/bazel-discuss/74e9018f-6bb6-4b39-b4a6-3c855cc6ec19%40googlegroups.com.

**Comment by davidstanke** [comment]
@iirina is this still an issue as of v.0.12?

**Comment by iirina** [comment]
According to 55828e256af4fe04e95f1c342a73d649d8525435 this should be fixed.
