### ISSUE TITLE
incompatible_use_toolchain_providers_in_java_common: pass JavaToolchainInfo and JavaRuntimeInfo providers to java_common APIs instead of configured targets

### ISSUE THREAD

**Issue by cushon** [bazelbuild/bazel#7186]
The option `--incompatible_use_toolchain_providers_in_java_common` makes `java_toolchain` and `host_javabase` APIs in `java_common` accept the `java_common.JavaToolchainInfo` and `java_common.JavaRuntimeInfo` providers instead of configured targets.

This change is being made in preparation for migrating the Java to use Toolchain Resolution (#4592).

# Migration Notes

Update all `java_common` APIs with the parameters `java_toolchain` or `host_javabase` to use the `find_java_runtime_toolchain` and `find_java_toolchain` utilities:

```diff
+@load("@bazel_tools//tools/jdk:toolchain_utils.bzl", "find_java_runtime_toolchain", "find_java_toolchain")

java_common.compile(
  ...,
-  java_toolchain = ctx.attr._java_toolchain,
-  host_javabase = ctx.attr._host_javabase,
+  java_toolchain = find_java_toolchain(ctx, ctx.attr._java_toolchain),
+  host_javabase = find_java_runtime_toolchain(ctx, ctx.attr._host_javabase),
)
```

The `ctx` and `java_toolchain_attr` parameters of `java_common.default_javac_opts` have been replaced with `java_toolchain`:

```diff
+@load("@bazel_tools//tools/jdk:toolchain_utils.bzl", "find_java_toolchain")

javacopts = java_common.default_javac_opts(
-    ctx,
-    java_toolchain_attr = "_java_toolchain",
+    find_java_toolchain(ctx, ctx.attr._java_toolchain),
)

```

**Comment by ittaiz** [comment]
Is this already available? Asking since I’m planning on moving rules_scala
to new java_common and JavaInfo APIs and would rather not have another
round later

**Comment by cushon** [comment]
It isn't available yet. Support for passing providers instead of targets will probably make it into 0.23, and support for passing targets will be removed some time that after.

**Comment by meteorcloudy** [comment]
Why did this flag get flipped? 0.22 is not a migration window for it and 0.23.0 is not released.

**Comment by hlopko** [comment]
Reopening because of a rollback.

**Comment by hlopko** [comment]
Pls wait with this at least for 0.23 release.

**Comment by cushon** [comment]
For posterity the rollback was ce7492782d2b6cbb576df0baf7a3c622a33986af for #7537.

@meteorcloudy the flag was flipped after the baseline was cut for 0.23, which was consistent with the policy requirements.

Please re-open incompatible change bugs and coordinate with the release manager if you have to roll back flag flips for incompatible change.

**Comment by ejona86** [comment]
As discussed in https://github.com/grpc/grpc-java/issues/5383, it seems it is not possible to migrate in Bazel 0.23 because it is missing functionality in `find_java_toolchain` and `find_java_runtime_toolchain`. So can the `migration-0.23` label be removed?
