### ISSUE TITLE
Docs don't describe what rule types are allowed in attributes

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/bazel#719]
e.g. working out where frameworks should go in ios_\* and objc_\* rules; from the source (https://github.com/bazelbuild/bazel/blob/e6180d3/src/main/java/com/google/devtools/build/lib/rules/objc/ObjcRuleClasses.java#L689) there is a finite set of rule classes which are allowed, but these aren't resolved by the doctool, so the documentation just lists that they can be labels.

**Comment by davidzchen** [comment]
This will definitely be useful. I'll also make a note to display this information for the Skylark docgen (#712) as well.

**Comment by helenalt** [comment]
@davidzchen Has this been fixed? Please close/or comment on this issue.

**Comment by meisterT** [comment]
What's the status of this?

**Comment by aiuto** [comment]
It still looks like it is not wired up right. It claims to be fixed in stardoc, but I do not see any mention of allowed types in 
https://docs.bazel.build/versions/master/be/objective-c.html
Nor in a lot of places, so this is not really just an objc issue.
