### ISSUE TITLE
Python launcher on Windows doesn't preserve working directory

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#7190]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

The Python launcher that's used on Windows (but apparently not on other platforms) doesn't seem to preserve the current working directory. This might cause the tool to break (e.g. relative paths passed on the command line will no longer be valid and looking up files in the current working directory will also not work).

I think the launcher should preserve the current working directory.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I wrote a sh_test for my little tool Bazelisk that basically looks like this:

BUILD:
```
py_binary(
    name = "bazelisk",
    srcs = ["bazelisk.py"],
)

sh_test(
    name = "bazelisk_test",
    srcs = ["bazelisk_test.sh"],
    data = [":bazelisk"],
    deps = ["@bazel_tools//tools/bash/runfiles"],
)
```

bazelisk_test.sh:
```sh
...
function test_bazel_version_from_file() {
  echo "0.19.0" > .bazelversion

  # Run Bazelisk
  "$(rlocation __main__/bazelisk.exe)" "$@" version 2>&1 | tee log
  ...
}
...
```

This test fails on Windows only, because Bazelisk can't find the `.bazelversion` in its current working directory, because its working directory is this:

```
Working directory: D:\temp\Bazel.runfiles_0lqm4tl6\runfiles\__main__
```

Where as on other platforms it looks more like this:

```
Working directory: /private/var/tmp/_bazel_philwo/35130df193e305a75a3c20980a794abf/sandbox/darwin-sandbox/1/execroot/__main__/_tmp/b09cf4133a59683555ea839f880da7b7/workspace
```

### What operating system are you running Bazel on?

Bazel's Windows CI

### What's the output of `bazel info release`?

0.21.0

**Comment by laszlocsomor** [comment]
@meteorcloudy : do you have any updates on this?

**Comment by meteorcloudy** [comment]
Not yet, looks like @philwo had a work around, so I'm not prioritizing this.

The working directory was changed to `
D:\temp\Bazel.runfiles_0lqm4tl6\runfiles\__main__` so that python binary has direct access to it's runfiles by relative path. But this was implemented a long time ago, before we have runfiles library and symlink runfiles tree on Windows. I'll look into this once I get time.

**Comment by philwo** [comment]
I think it's bad that the behavior of the Python launcher differs per platform and IMHO the current behavior of the launcher on Windows is completely broken - imagine if you had a compiler or build tool implemented in Python and we'd build it with Bazel and then try to use the resulting py_binary:

```
# Let's build some amazing stuff with my new build tool Pyzel!
$ cd ~/src/pyzel
$ pyzel build //src:pyzel
ERROR: The 'build' command is only supported from within a workspace.
# Huh? But my current directory is inside my workspace...?
```

Or:

```
# Have you heard about this awesome new C++ compiler called plang?
# Let's build hello world!
$ plang -o hello hello.cc
plang: error: no such file or directory: 'hello.cc'
plang: error: no input files

# Huh? But there IS a file called hello.cc in my current directory?
```

I think we should fix this.

**Comment by meteorcloudy** [comment]
This behavior was introduced at https://bazel-review.googlesource.com/c/bazel/+/11835/

Fortunately this only happens inside test where `RUN_UNDER_RUNFILES` is set to 1. So if you just build a py_binary then use it as a standalone binary or as a tool in genrule, the working directory should not be changed.

Removing this logic will break python tests that use data file by relative path, as far as I know TensorFlow has many test like this. I'll investigate how much effort do they need to migrate to runfiles library, then I'll try to remove this behavior maybe under an incompatible flag. How does that sound?

**Comment by philwo** [comment]
Ohh, if it's just for tests, that's already much better. :) In that case I could workaround it by running the Python binary from my shell test with the `RUN_UNDER_RUNFILES` environment variable unset for that process.

I think your plan sounds good, but I'll leave it to you - if it breaks TensorFlow and causes a lot of work, maybe we can live with it for a little longer.

**Comment by meteorcloudy** [comment]
Cool, thanks!

**Comment by laszlocsomor** [comment]
IIUC this isn't an issue then, no?
Can we close it?

**Comment by meteorcloudy** [comment]
I think so
