### ISSUE TITLE
incompatible_use_remote_java_toolchain: use remote Java tools instead of the embedded deploy jars

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#7196]
The option `--incompatible_use_remote_java_toolchain` will download the remote Java tools (archive of deploy jars) for the target configuration instead of using the corresponding embedded deploy jars. Enabling this flag only affects users of the Java rules.

# Migration Notes

There are no actions required from the users. No migration is needed.

**Comment by scottmin0r** [comment]
For this flag and the one in #7197 - what if users don't want to download this archive, or want to change the location/manner in which this archive is obtained? This would be important for CI systems with no internet connectivity, and orgs that want to audit/control build-time dependencies (both in terms of artifacts and systems). Will there be a flag moving forward that will disable this download?

**Comment by iirina** [comment]
@scottmin0r To not download the archive you have to set the flags `--java_toolchain` and `--host_java_toolchain` to point to local tools.

**Comment by scottmin0r** [comment]
Specifically what should I pass for those flag values? As per [this comment](https://github.com/bazelbuild/bazel/issues/6656#issuecomment-461084131) I've tried:

```
build --javabase=@local_jdk//:jdk
build --host_javabase=@local_jdk//:jdk
build --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
```

but this still seems to try to download tools (with two different failure modes):

```
Analyzing: 1166 targets (68 packages loaded, 2267 targets configured)
Analyzing: 1166 targets (68 packages loaded, 2267 targets configured)
Analyzing: 1166 targets (68 packages loaded, 2267 targets configured)
Analyzing: 1166 targets (68 packages loaded, 2267 targets configured)
Analyzing: 1166 targets (68 packages loaded, 2267 targets configured)
ERROR: /home/kbuilder/.cache/bazel/_bazel_kbuilder/94efa1614cde89691caae16b65396550/external/bazel_tools/tools/jdk/BUILD:218:1: no such package '@remote_java_tools//': java.io.IOException: Error downloading [https://mirror.bazel.build/bazel_java_tools/java_tools_pkg-0.5.1.tar.gz] to /home/kbuilder/.cache/bazel/_bazel_kbuilder/94efa1614cde89691caae16b65396550/external/remote_java_tools/java_tools_pkg-0.5.1.tar.gz: Network is unreachable (connect failed) and referenced by '@bazel_tools//tools/jdk:JacocoCoverageRunner'
```

```
Analyzing: 56 targets (8 packages loaded, 587 targets configured)
Analyzing: 56 targets (8 packages loaded, 587 targets configured)
Analyzing: 56 targets (8 packages loaded, 587 targets configured)
Analyzing: 56 targets (8 packages loaded, 587 targets configured)
Analyzing: 56 targets (8 packages loaded, 587 targets configured)
Analyzing: 56 targets (8 packages loaded, 587 targets configured)
ERROR: /home/kbuilder/.cache/bazel/_bazel_kbuilder/1858cc0ae663ea49d21c8c6b3132f559/external/bazel_tools/tools/jdk/BUILD:153:1: no such package '@remote_java_tools//': java.io.IOException: thread interrupted and referenced by '@bazel_tools//tools/jdk:genclass'
```
