### ISSUE TITLE
tags for --run_under binary are ignored when running tests

### ISSUE THREAD

**Issue by bsilver8192** [bazelbuild/bazel#720]
When using a label for --run_under with `bazel test`, things like 'requires-network' in the tags attribute of the rule are ignored. This would be useful to allow a wrapper script which copies the tests over the network to another machine to still have sandboxing enabled instead of having to completely disable sandboxing with `--strategy=TestRunner=local`.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
