### ISSUE TITLE
remote: review and redo supported tags and flags

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#7205]
There's currently a number of tags that can be applied to targets that influence the behavior of the remote cache / executor: `no-cache`, `no-remote`, `local`.

We need to clarify the semantics of each of them and discuss whether new tags are needed to implement currently unsupported use cases.

**Steps**:

- [x] **Flags**
   - [x] _Analysis phase:_
      - [x] review and document existing flags
      - [x] propose simplifications
      - [x] propose a migration plan (backward compatible etc)
      - [x] confirm/adjust a proposal with the community
   - [x] _Implementation phase_
      - based on the migration plan
   - [x] _Check and update the docs_

- [x] **Tags**
   - [x] _Analysis phase:_
      - [x] review and document existing tags
      - [x] propose simplifications
      - [x] propose a migration plan (backward compatible etc)
      - [x] confirm/adjust a proposal with the community
   - [x] _Implementation phase_
       - based on the migration plan
       - [x] propagate tags for native rules
   - [x] _Check and update docs_

- [ ] **Document common use cases flags/tags set examples**
- [ ] **Properly handle the most common incompatible flags/tags combination**

**Comment by buchgr** [comment]
We also need to make sure that the semantics of tags as they apply to local execution strategies and tags as they apply to remote execution make sense i.e. the "local" tag.

There's also documentation to be written, reviewed and updated i.e. https://docs.bazel.build/versions/master/be/common-definitions.html

**Comment by ishikhman** [comment]
- [ ] **Flags**
   - [ ] _Analysis phase:_
      - [ ] review and document existing flags
      - [ ] propose simplifications
      - [ ] propose a migration plan (backward compatible etc)
      - [ ] confirm/adjust a proposal with the community
   - [ ] _Implementation phase_
      - based on the migration plan
   - [ ] _Check and update the docs_

- [ ] **Tags**
   - [ ] _Analysis phase:_
      - [ ] review and document existing tags
      - [ ] propose simplifications
      - [ ] propose a migration plan (backward compatible etc)
      - [ ] confirm/adjust a proposal with the community
   - [ ] _Implementation phase_
       - based on the migration plan
       - [ ] propagate tags for native rules
   - [ ] _Check and update docs_

- [ ] **Document common use cases flags/tags set examples**
- [ ] **Properly handle the most common incompatible flags/tags combination**

**Comment by ishikhman** [comment]
related to #6649

**Comment by ishikhman** [comment]
@buchgr I'd close this issue in favour of #8830 for the reminder of tags propagation, feel free to reopen it
