### ISSUE TITLE
--watchfs ignores changes on volumes in Linux docker under a Windows host

### ISSUE THREAD

**Issue by filipesilva** [bazelbuild/bazel#7206]
### Description of the problem / feature request:

`--watchfs` ignores changes on volumes in Linux docker under a Windows host

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

On a Windows machine with bazel 0.21, docker and git, follow these commands:

- `git clone https://github.com/filipesilva/bazel-windows-docker-volume`
- `cd bazel-windows-docker-volume`
- `bazel test //:test --watchfs`
- delete contents of `BUILD.bazel`
- `bazel test //:test --watchfs`
- you should get an error:
```
INFO: Invocation ID: c1866380-8396-424d-a5ef-d2f2bbdee2db
ERROR: Skipping '//:test': no such target '//:test': target 'test' not declared in package '' defined by D:/sandbox/bazel-windows-docker-volume/BUILD.bazel
ERROR: no such target '//:test': target 'test' not declared in package '' defined by D:/sandbox/bazel-windows-docker-volume/BUILD.bazel
INFO: Elapsed time: 0.991s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
FAILED: Build did NOT complete successfully (1 packages loaded)
```

Now do the same under a Linux container with a mounted volume:
- restore the contents of `BUILD.bazel`
- `docker run -it --rm -v $(pwd -W):/src debian:jessie` 
  - note: depending on your shell you might have to replace `$(pwd -W)` with the path to the current directory manually
- `cd /src`
- `./install-bazel.sh` (this scripts follows the [Ubuntu instructions](https://docs.bazel.build/versions/master/install-ubuntu.html#install-with-installer-ubuntu))
- `bazel test //:test --watchfs`
- delete contents of `BUILD.bazel`
- `bazel test //:test --watchfs` (no error)
- `bazel test //:test` (error)

### What operating system are you running Bazel on?

Windows 10 1809

### What's the output of `bazel info release`?

release 0.21.0

###  Have you found anything relevant by searching the web?

Found a couple of issues here about --watchfs, but nothing seemed to be related to windows or indicate it stopped finding changes.

**Comment by jmmv** [comment]
Help me understand please as I have zero Docker knowledge so far. So the Bazel sources are on Windows, presumably on an NTFS drive, and they are being "exposed" into the Docker container? Do you know how this happens? Are they copied elsewhere?

**Comment by filipesilva** [comment]
Heya @jmmv. I don't know a lot about the Docker internals but will tell you whatever I can.

When using the `-v $(pwd -W):/src` flag on docker, I am saying "I want the contents of the current directory ( given by `$(pwd -W`) to be mounted under docker at `/src`".

I was calling this volume because it uses the `-v` flag, but it looks like the correct name is "bind mount": https://docs.docker.com/storage/bind-mounts/

The sources are definitely on windows (the host) in this case, in the current directory. I just checked and it is indeed a NTFS drive.

The sources are being exposed inside the running docker container. As far as I know they aren't copied anywhere. Changes that I do in the host are reflected in the container, and vice versa. I don't know the details of how Docker accomplishes this.

I think there is a bug in Bazel's `--watchfs` because:
- the files do change inside the container, 
- file changes are not recognized with `--watchfs`
- file changes are recognized with without `--watchfs`

**Comment by jmmv** [comment]
Oops, sorry for the long delay in getting back to this.

So just to confirm: in the problematic case, when you say "delete contents of BUILD.bazel", you do that from within the container or from outside?

If you use `--watchfs`, Bazel's server uses inotify to watch for changes to the source tree. If you are deleting the file from *outside* of the container, I can imagine that inotify is just not aware of that and thus cannot tell Bazel that something changed.

If you do not use `--watchfs`, Bazel will explicitly stat all source files to look for changes in them and thus will see the modified files regardless of what inotify might think.

**Comment by jmmv** [comment]
Well, turns out https://github.com/docker/for-win/issues/56 answers the question. inotify doesn't work within Docker on Windows, so that explains why `--watchfs` doesn't do the right thing. There is nothing Bazel can do, other than possibly auto-disabling `--watchfs` on Docker *if* using a shared volume... but that seems pretty fragile.

**Comment by filipesilva** [comment]
Heya, thanks for taking a look! Yeah that seems to be what's happening...
