### ISSUE TITLE
remote/http: implement timeout for uploads

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#7211]
using netty's `IdleStateHandler` in the same as we have for downloads thanks to @nicolov !

**Comment by brown** [comment]
Bazel has been much more reliable since the read timeout change made by @nicolov but it still can hang if the remote HTTP cache fails to respond when Bazel is uploading artifacts to the cache.

**Comment by brown** [comment]
I implemented write timeouts in pull request:  https://github.com/bazelbuild/bazel/pull/7590

**Comment by ishikhman** [comment]
done in #7590
