### ISSUE TITLE
incompatible_use_jdk11_as_host_javabase: makes JDK 11 the default --host_javabase for remote jdk

### ISSUE THREAD

**Issue by cushon** [bazelbuild/bazel#7219]
The option `--incompatible_use_jdk11_as_host_javabase` makes JDK 11 the default [`--host_javabase`](https://docs.bazel.build/versions/master/user-manual.html#flag--host_javabase).

See also `--incompatible_use_jdk11_as_host_javabase` (#6661).

# Migration notes

If you set the flag, Bazel will use JDK 11 as the default [`--host_javabase`](https://docs.bazel.build/versions/master/user-manual.html#flag--host_javabase).

For more information about JDK 11, see [the release notes](https://www.oracle.com/technetwork/java/javase/11-relnote-issues-5012449.html).

**Comment by xingao267** [comment]
I have few questions about this:

1. With this flag turned on, if I don't specify --host_javabase, I guess Bazel will download JDK11 to use as the host_javabase?

2. With this flag turned on, if I specify --host_javabase, and point to JDK11, it should just use the passed host_javabase right? And if the host_javabase does not point to a JDK11, does it give a version mismatch error?

**Comment by cushon** [comment]
@xingao267 `--incompatible_use_jdk11_as_host_javabase` makes a remote JDK 11 the *default* `--host_javabase`. The remote JDK 11 is used if `--host_javabase` is not explicitly set. If `--host_javabase` **is** explicit set, `--incompatible_use_jdk11_as_host_javabase` has no effect.

**Comment by katre** [comment]
This issue was tagged as "breaking-change-0.24" but does not appear ready to be flipped in the [0.24.0 release](https://github.com/bazelbuild/bazel/issues/6968). If this is incorrect please comment on that issue and discuss with me.

**Comment by cushon** [comment]
The migration window started in 0.23. Is it too late to include the flag flip in 0.24?

**Comment by katre** [comment]
The release baseline has already been chosen. We'll need to discuss and prioritize a cherrypick for this (and a few other incompatible changes).

**Comment by hlopko** [comment]
I filed https://bugs.chromium.org/p/gerrit/issues/detail?id=10570 for Gerrit breakage.

**Comment by laurentlb** [comment]
It would be nicer to ping them before the breakage.

**Comment by hlopko** [comment]
Pls investigate https://github.com/bazelbuild/bazel/issues/7672 and consider unflipping the flag, if there is a bug in the implementation or migration.
