### ISSUE TITLE
Make generated symlink names consistent with `workspace(name = ...)`

### ISSUE THREAD

**Issue by ghost** [bazelbuild/bazel#7223]
### Description of the problem

`WORKSPACE` files have a nice option of using `workspace(name = "my_consistent_name")` so that the name of the workspace in `BUILD` files is consistent regardless of what the containing directory happens to be called.

For example even if the bazel workspace is in `my_inconsistent_dir/` you can still access rules with `@my_consistent_name//etc`.

However, bazel doesn't respect this option when it comes to the symlinks and build directory layoutls . I find that it still uses `my_inconsistent_dir` as the "workspace name" in these paths. It would be great if it respected the option given in the workspace file.

### Feature requests: what underlying problem are you trying to solve with this feature?

This has come up in at least a couple of ways:
- Sometimes I like to clone a couple of copies of my repository so I can work on one while the other has bazel building something lengthy. This forces me to nest directories so that the repository directory names can be the same.
- Other developers sometimes have an aesthetic preference for cloning to a directory with a different name, there's no good reason why that behaviour shouldn't be supported.

We have several things (utility scripts, IDE config files, etc.) that need to reference directly into the `build-*` symlinks to find built resources. They would be entirely machine-agnostic if it weren't for the fact that these symlinks can change name depending on parent directory name. 

### What operating system are you running Bazel on?

Ubuntu 16.04 / 18.04

### What's the output of `bazel info release`?

```
INFO: Invocation ID: b1e08e80-af80-43cd-87b0-e0b0686f1313
release 0.21.0
```

###  Have you found anything relevant by searching the web?

I'd be surprised if this hasn't been raised elsewhere, but I couldn't find it.

**Comment by dslomov** [comment]
I am not sure what you mean by "bazel workspace is in `my_inconsistent_dir/`"?
Can you give a provide repro that illustrates the problem?

**Comment by dslomov** [comment]
> I simply mean that you have my_inconsistent_dir/WORKSPACE and in that file workspace(name = "my_consistent_name"). i.e. the workspace name is inconsistent with the directory containing it. 

Ah I see, and where do you see this name used? Is that only the `bazel-<name>` symlink in the workspace root?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
