### ISSUE TITLE
use units in --remote_timeout=

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#7224]
--remote_timeout=INT currently expects seconds. this can be quite error prone as  https://github.com/bazelbuild/bazel/issues/5440 showed. We could instead implement parsing of time units i.e. `--remote_timeout=10s` or `--remote_timeout=1m`.

cc @nicolov

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by brentleyjones** [comment]
Can we reopen this one?

**Comment by brentleyjones** [comment]
Sorry, @sgowroji, I was mistaken, it looks like this was completed it https://github.com/ehkloaj/bazel/commit/88201b061283fb48c6f8364edbe57b17ba80e203. You can close this as completed.

**Comment by brentleyjones** [comment]
Looks like it was completed here: https://github.com/bazelbuild/bazel/commit/62475e738f1206a06dbda0d2638015c2c2fb1c88
