### ISSUE TITLE
remote: improve error message if no message provided

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#7228]
In the `RemoteSpawnCache` if an exception bubbles up and it has no message attached then we print the class name of the exception to stdout. We should instead print a stack trace of the exception in order to detect and fix these cases. All exceptions bubbling up to the `RemoteSpawnCache` should have user readable and understandable messages.

**Comment by coeuvre** [comment]
I think this can be closed now since the error message is improved in `4.1.0` and we can use `--verbose_failures` to get the stack trace.
