### ISSUE TITLE
Swift with mixed objective-c mode

### ISSUE THREAD

**Issue by mennahmostafa** [bazelbuild/bazel#723]
Hi, 

I have a swift project with mixed objective-c files, I added the objective c -> swift bridging header to the bazel target, but the header file <product-name>-Swift.h which is usually generated by Xcode to allow Objective-c to reference swift is not generated and bazel fails to build the target with this error: fatal error: '<product-name>-Swift.h file not found.
I have tried couple of compiler flags but no luck. Xcode uses the emit-objc-header and -emit-objc-header-path to generate the header, but I wasn't sure which path to specify, any idea?
my target looks something like this:

``` javascript
objc_binary(
        name = "Test_bin",
        srcs=[
            "MainViewController.swift",
            "AppDelegate.swift",
            ],
        hdrs = glob(["*.h"]),
        bridging_header="Test-Bridging-Header.h",
        copts = ["-std=c++11","-stdlib=libc++","-x objective-c++","-enable-objc-interop",
       "-emit-objc-header", "-emit-objc-header-path Test-Swift.h",
       "-lobjc","-objc_abi_version","-fmodules","-isystem","-emit-module","-emit-dependencies"],
        storyboards= ["Main.storyboard"],
        bundle_id="",
        infoplist = "Info.plist", 
        enable_modules=1,
    )
```

Thanks!

**Comment by damienmg** [comment]
@c-parsons can you take a look at this?

**Comment by damienmg** [comment]
@c-parsons ping?

**Comment by c-parsons** [comment]
This bug is quite stale, and we now have a swift library rule to handle swift srcs

**Comment by dnkoutso** [comment]
@c-parsons whats the rule to use for Swift only libraries?

**Comment by keith** [comment]
`swift_library`, see the tests for examples.

**Comment by dnkoutso** [comment]
Thanks, this was not present in the docs for Bazel, perhaps its not released yet officially
