### ISSUE TITLE
Bazel CI: Bazel is broken in downstream

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#7235]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/770#_

```
ERROR: /var/lib/buildkite-agent/builds/bk-docker-kb3m/bazel-downstream-projects/bazel/src/test/shell/bazel/android/BUILD:82:1: Couldn't build file src/test/shell/bazel/android/android_ndk_integration_test/shard_3_of_6/test.log:  failed: Unexpected IO error: Input is a directory: /home/bazel/.cache/bazel/_bazel_bazel/79189da8be21f913c8180bd797ba11d1/execroot/io_bazel/external/androidndk/ndk/build
```

Bisecting at https://buildkite.com/bazel/culprit-finder/builds/80#b1f26cc2-040e-4e5d-aae6-daeb4a8e3848

**Comment by buchgr** [comment]
The reason for the breakage is that we rolled back a broken symlink support implementation for remote caching / execution. The android tests are known to not work with remote caching / execution.

**Comment by meteorcloudy** [comment]
Should we disable the test?

**Comment by meteorcloudy** [comment]
The culprit is 12ab12e80ad1c9a3510aa4bbfdf3fddafc0bca00 as confirmed by [culprit finder](https://buildkite.com/bazel/culprit-finder/builds/80#b1f26cc2-040e-4e5d-aae6-daeb4a8e3848)

Since this one is cherry-picked into 0.22.0, I think we should disable the failing android test if it's known to not work. Or is there a tag or something to disable remote caching for it?
