### ISSUE TITLE
Build ran out of memory but error doesn't indicate this

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#7237]
Tried to update rules_nodejs to stardoc. It depends on protobuf. I'm on a Pixelbook with whatever builtin linux container, I think it has less RAM (@gregmagolan reproduces in a VM as well). Error is

```
~/Projects/rules_nodejs$ yarn bazel build //docs
yarn run v1.13.0
$ /home/alexeagle/Projects/rules_nodejs/node_modules/.bin/bazel build //docs
Starting local Bazel server and connecting to it...
INFO: Invocation ID: a7b8252e-8f3b-4bf9-8e11-5d13f8b82f60
INFO: SHA256 (https://github.com/bazelbuild/skydoc/archive/0.2.0.zip) = 6b9ab4cf5c781e467888ce14864e62f47adc4b6d0cb7a9838469440d25643a4b
INFO: Rule 'com_google_protobuf' modified arguments {"shallow_since": "1542334746 -0800"}
INFO: Analysed target //docs:docs (140 packages loaded, 4432 targets configured).
INFO: Found 1 target...
ERROR: /home/alexeagle/.cache/bazel/_bazel_alexeagle/78c7479a1baf683797e1e6cd7cfefe83/external/com_google_protobuf/BUILD:267:1: C++ compilation of rule '@com_google_protobuf//:protoc_lib' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 36 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
Target //docs:docs failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 182.381s, Critical Path: 0.32s
INFO: 1 process: 1 linux-sandbox.
FAILED: Build did NOT complete successfully
```

Increasing the amount of RAM in the VM fixes it. Not sure which layer is at fault, but the error message is very unhelpful.

**Comment by dslomov** [comment]
This might be rather hard to fix....

**Comment by dslomov** [comment]
I do not see a viable way to fix this really - all we know is that some command failed with exit code 1. This tells us nothing about the reason for that - unless the tool we call report OOM, we have no information. Closing as infeasible, but lmk if you have great ideas on how to improve this.

**Comment by mirh** [comment]
> unless the tool we call report OOM, we have no information

Actually, according to #3020, even that's not doable (because _kill_ has no tags attached)
...On the other hand, I was reading how processes could be made kinda aware of the general system situation at least. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1495355#c8
https://bugs.chromium.org/p/chromium/issues/detail?id=463606#c23
