### ISSUE TITLE
cc_test does not accept .inl files in srcs argument

### ISSUE THREAD

**Issue by jblanchet** [bazelbuild/bazel#7242]
### Description of the problem / feature request:

Trying to include .inl files in a cc_test's srcs argument produces the following error: 

`ERROR: C:/users/jblanchet/_bazel_jblanchet/bssk6qfo/external/xxxxx/BUILD.bazel:21:12: in srcs attribute of cc_test rule @xxxxx//xxxxx_tests: source file '@xxxxx//:test/source/TestString.inl' is misplaced here (expected .cc, .cpp, .cxx, .c++, .C, .c, .h, .hh, .hpp, .ipp, .hxx, .inc, .S, .s, .asm, .a, .lib, .pic.a, .lo, .lo.lib, .pic.lo, .so, .dylib, .dll, .o, .obj or .pic.o)`

The documentation [here](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_test_args) shows that this should be a valid file type.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a simple C++ project with a C++ test file that includes a .inl file.

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 0.21.0

**Comment by excitoon** [comment]
Fixed in #6805, should appear in 0.23.0.

**Comment by excitoon** [comment]
@jblanchet tested it, it should now work.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by excitoon** [comment]
Your bot does not work very well, it shall be closed as fixed. Please do
not spam with useless notifications.
