### ISSUE TITLE
Implement similar local disk cache structure as bazel-remote

### ISSUE THREAD

**Issue by bayareabear** [bazelbuild/bazel#7244]
In bazel-remote commit:  https://github.com/buchgr/bazel-remote/commit/e9b9c8858f9f74bed41464231c79b168a5fdd020
Files are stored in subfolders named with the first two letters of the file. Bazel should do the same with local disk cache. This is convenient when turning on/off bazel-remote as local http proxy, bazel can consume the same local disk cache directly when bazel-remote is not used.

**Comment by buchgr** [comment]
that's a great idea! would you be interested in working on this?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by tjgq** [comment]
This was done in fff96af.
