### ISSUE TITLE
Unable to load //:abc/requirements.txt while generating par files using bazel

### ISSUE THREAD

**Issue by 01pooja** [bazelbuild/bazel#7246]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

I am trying to generate par files for a target, but it is unable to load package from requirements.txt present in abc directory.

Here are the logs:
ERROR: error loading package '': Encountered error while reading extension file 'requirements.bzl': no such package '@abc_deps//': Traceback (most recent call last):
    File "/tmp/.cache/bazel/_bazel_pog/4dbff95ef3b73130029b349a5743e7e7/external/io_bazel_rules_python/python/pip.bzl", line 26
            repository_ctx.execute(["python", repository_ctx.path(r...("")])
    File "/tmp/.cache/bazel/_bazel_pog/4dbff95ef3b73130029b349a5743e7e7/external/io_bazel_rules_python/python/pip.bzl", line 32, in repository_ctx.execute
            repository_ctx.path(repository_ctx.attr.requirements)

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

-bash-4.2$ lsb_release
LSB Version:    :core-4.1-amd64:core-4.1-noarch
-bash-4.2$ lsb_release  -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core)
Release:        7.6.1810
Codename:       Core

### What's the output of `bazel info release`?

ERROR: error loading package '': Encountered error while reading extension file 'requirements.bzl': no such package '@abc_deps//': Traceback (most recent call last):
    File "/tmp/.cache/bazel/_bazel_pog/4dbff95ef3b73130029b349a5743e7e7/external/io_bazel_rules_python/python/pip.bzl", line 26
            repository_ctx.execute(["python", repository_ctx.path(r...("")])
    File "/tmp/.cache/bazel/_bazel_pog/4dbff95ef3b73130029b349a5743e7e7/external/io_bazel_rules_python/python/pip.bzl", line 32, in repository_ctx.execute
            repository_ctx.path(repository_ctx.attr.requirements)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

NO

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by 01pooja** [comment]
Any updates on this?

**Comment by brandjon** [comment]
This is a bazelbuild/rules_python issue, not an issue with the native rules. But in any case, we'd need to see a minimal reproduction to be able to start examining this.
