### ISSUE TITLE
remote: update grpc and google auth library to latest

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#7259]

**Comment by tetromino** [comment]
I need this for properly fixing #6400 (support for grpc.enable_http_proxy channel arg was added in gRPC 1.14).

**Comment by buchgr** [comment]
@tetromino this is about the gRPC Java dependency. I believe you need https://github.com/bazelbuild/bazel/issues/2804

**Comment by brown** [comment]
The Google auth library in third_party/auth is quite old.  It did not work with my company's proxy to GCS when I tried to use a GCS bucket as a remote cache.  It needs to be updated.

**Comment by buchgr** [comment]
See https://github.com/bazelbuild/bazel/pull/8017
