### ISSUE TITLE
Bazel should autoconfigure compiler from the PATH on Windows

### ISSUE THREAD

**Issue by mboes** [bazelbuild/bazel#7265]
### Description of the feature request

When using `--compiler=*-gcc`, make Bazel pick the GCC compiler from the `PATH` during autoconfiguration.

### Feature requests: what underlying problem are you trying to solve with this feature?

Bazel CC compiler autoconfiguration assumes that GCC is a hard coded location relative to the Bash shell. When this does not match reality, autoconfiguration fails, even when there is a GCC in the `PATH`. The current logic is inconsistent with Linux, which picks GCC from the `PATH`. I submit that the same logic should be used on all platforms. e.g. on Azure Pipelines VM's, there is no MSYS2. But there is Bash for Git in one place and a MinGW64 compiler in the other. Currently Bazel cannot use this compiler without writing a `CROSSTOOL` by hand.

### What operating system are you running Bazel on?

Windows Server 2016

### What's the output of `bazel info release`?

0.21.0

**Comment by katre** [comment]
Closed for lack of activity. Please ping the reviewers to reopen if this is still a problem.
