### ISSUE TITLE
--experimental_remap_main_repo breaks providers somehow

### ISSUE THREAD

**Issue by allevato** [bazelbuild/bazel#7275]
### Description of the problem / feature request:

When using the `--experimental_remap_main_repo` flag, some providers defined in repository are not able to be found in their targets. It would appear something about the remapping is messing up provider key lookup, or provider identity.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. `git clone https://github.com/bazelbuild/rules_swift.git`
2. `bazel build //... --experimental_remap_main_repo`
3. Observe that the build fails with the following error (or one similar):

    ```
    ERROR: /Users/allevato/Source/rules_swift/examples/xplatform/hello_world/BUILD:5:1:
    in (an implicit dependency) attribute of swift_binary rule //examples/xplatform/hello_world:hello_world:
    '@build_bazel_rules_swift_local_config//:toolchain' does not have mandatory providers: 'SwiftToolchainInfo'
    ERROR: Analysis of target '//examples/xplatform/hello_world:hello_world' failed;
    build aborted: Analysis of target '//examples/xplatform/hello_world:hello_world' failed;
    build aborted
    ```

4. `bazel clean`
5. `bazel build //...`
6. Observe that the build succeeds.

I can also insert `print` statements into the toolchain rule and the binary rule to verify that:

1. The provider _does indeed_ return a `SwiftToolchainInfo` as expected
2. The toolchain target when accessed from the binary rule _does indeed_ list `SwiftToolchainInfo` in its keys

But, apparently they aren't matching in terms of provider lookup.

### What operating system are you running Bazel on?

macOS 10.13.6 (High Sierra)

### What's the output of `bazel info release`?

`release 0.21.0`

**Comment by dslomov** [comment]
@dkelmer ptal

**Comment by allevato** [comment]
It looks like it may be fixed; I can't produce the same error when using the flag with rules_swift on 0.22, so I'll close this. Thanks!

**Comment by dkelmer** [comment]
Thanks for confirming :)
