### ISSUE TITLE
Bazel duplicates the error message sent from remote execution

### ISSUE THREAD

**Issue by sethkoehler** [bazelbuild/bazel#7277]
### Description of the problem / feature request:

When an error occurs remotely, bazel prints the error twice, when it should just print the error once.  For example, running a remote build but specifying the incorrect docker container hash will give an error like this:

ERROR: .../BUILD:3:1:  failed (Exit 34). Note: Remote connection/protocol failed with: execution failed Call failed with not retriable error: com.google.devtools.build.lib.remote.ExecutionStatusException: INTERNAL: failed to prepare: failed to prepare Docker environment: while pulling Docker image "gcr.io/...": first 1k of stdout: ""; first 1k of stderr: "Error response from daemon: manifest for gcr.io/... not found\n": exit status 1: <MESSAGE DUPLICATES HERE> Call failed with not retriable error: com.google.devtools.build.lib.remote.ExecutionStatusException: INTERNAL: failed to prepare: failed to prepare Docker environment: while pulling Docker image "gcr.io/...": first 1k of stdout: ""; first 1k of stderr: "Error response from daemon: manifest for gcr.io/... not found\n": exit status 1

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Change the commit hash of the docker container image for any build using remote execution (i.e., the section in the BUILD file containing 'properties: { name: "container-image" value: "docker://gcr.io/...@sha256:..." }'

### What operating system are you running Bazel on?

Linux (Debian 4.19.12-1)

### What's the output of `bazel info release`?

release 0.22.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

fatal: not a git repository (or any parent up to mount point /usr/local)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /usr/local)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /usr/local)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

###  Have you found anything relevant by searching the web?

Searched for bazel duplicate error message on web and in github here, but didn't see anything related.

**Comment by buchgr** [comment]
This has been fixed in the latest Bazel release. Please re-open if it hasn't.
