### ISSUE TITLE
java_binary puts the JDK into runfiles

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#728]
It makes sense to put the JDK into the runfiles if the JDK is actually checked in. If it comes from an absolute path, there's really no point in doing that. We hook up the JDK through a remote repository, so it always looks as if it was checked in.

Maybe we shouldn't do that?

**Comment by dslomov** [comment]
Also a potential issue with Windows

**Comment by ulfjack** [comment]
Unassigning @dslomov; I don't think you're currently working on this... is there a windows tag we should add here?

**Comment by damienmg** [comment]
Yes if it is more a port to Windows issue we should change the category to
the windows one.
