### ISSUE TITLE
android_binary build gives deprecation warning

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#729]
This is the output from building a simple android_binary rule:

INFO: From Generating unsigned apk:

THIS TOOL IS DEPRECATED. See --help for more information.

INFO: From Generating signed apk:

THIS TOOL IS DEPRECATED. See --help for more information.

Useless and also annoying. Furthermore, we should make sure that we use supported APIs for building.

**Comment by lberki** [comment]
Assigning to Alex since he is already signed up for replacing ApkBuilder, which emits this message.

**Comment by hanwen** [comment]
I think this is fixed by 6ba5c97e9ad94b307b3383d9d18c9ef30e3f8322
