### ISSUE TITLE
--incompatible_dont_emit_static_libgcc doesn't work

### ISSUE THREAD

**Issue by dapirian** [bazelbuild/bazel#7292]
### Description of the problem / feature request:
Even with `--incompatible_dont_emit_static_libgcc`, bazel still emits `-static-libgcc`

### Feature requests: what underlying problem are you trying to solve with this feature?

I have a crosstool which uses Clang 7.0.1 & compiler-rt, not libgcc (`linker_flag: "-rtlib=compiler-rt"`). Bazel passes `'-static-libgcc` even though I'm not using libgcc, which causes this error: 
```
clang: warning: argument unused during compilation: '-static-libgcc' [-Wunused-command-line-argument]
```

`--incompatible_dont_emit_static_libgcc` was supposed to give users like me control of that, but it doesn't work:

Here's a demo of the problem:
```
$ bazel build //hello_world/cc:say_hello --incompatible_dont_emit_static_libgcc
INFO: Analysed target //hello_world/cc:say_hello (15 packages loaded, 2470 targets configured).
INFO: Found 1 target...
INFO: From Linking hello_world/cc/say_hello:
clang: warning: argument unused during compilation: '-static-libgcc' [-Wunused-command-line-argument]
Target //hello_world/cc:say_hello up-to-date:
  bazel-bin/hello_world/cc/say_hello
INFO: Elapsed time: 1.547s, Critical Path: 0.77s
INFO: 3 processes: 3 linux-sandbox.
INFO: Build completed successfully, 7 total actions
```
This is when building a `cc_binary` target.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Compile with clang & compiler-rt instead of libgcc. My build is entirely hermetic (uses a sysroot) so the system doesn't matter.

### What operating system are you running Bazel on?

Ubuntu 14.04

### What's the output of `bazel info release`?

release 0.22.0

**Comment by hlopko** [comment]
This is the place in the bazel code where the flag is added: https://source.bazel.build/bazel/+/24f573939e27bf4ca2bf9de3f28c93aec9a6f9f7:src/main/java/com/google/devtools/build/lib/rules/cpp/CppActionConfigs.java;l=752. I assume that your crosstool doesn't have `static_libgcc` feature present. You have 2 options: 

1) add empty `static_libgcc` feature, so bazel doesn't add it
2) add feature named `no_legacy_features` that will prevent Bazel from adding anything to your crosstool, and add all missing features that are patched by CppActionConfigs.

I'll close this issue now, but feel free to continue the discussion here.

Thanks!

**Comment by sgyan19** [comment]
how to add empty feature? If i don't have the custom toolchain. how can i fix it?

**Comment by sgyan19** [comment]
yeah, i found that i add command flag "--features=-static_libgcc" will fix that
