### ISSUE TITLE
bazel query exception

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel#7294]
### Description of the problem / feature request:

I was trying a query from this thread: https://github.com/bazelbuild/bazel/issues/1831#issuecomment-375760277, specifically `bazel query --universe_scope="//..." --order_output=no 'kind(rule, siblings(buildfiles(rbuildfiles(WORKSPACE))))'` and getting an exception when doing so. Not sure to be honest if this is a query that makes sense, but it should probably also not throw an exception.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

clone https://github.com/Globegitter/sandboxf-go-repro
run: `bazel query --universe_scope="//..." --order_output=no 'kind(rule, siblings(buildfiles(rbuildfiles(WORKSPACE))))'` and you should see the exception

### What operating system are you running Bazel on?

elementary OS 5.0 (Ubuntut 18.04)

### What's the output of `bazel info release`?

release 0.22.0

**Comment by gregestren** [comment]
Assigned to @juliexxia for diagnosis.

**Comment by meisterT** [comment]
This query works for me on the repro git repository with current Bazel.
