### ISSUE TITLE
incompatible_disallow_legacy_py_provider: Use PyInfo instead of "py" struct providers

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#7298]
**Flag:** `--incompatible_disallow_legacy_py_provider`
**Available since:** 0.23
**Will be flipped in:** either 0.24 or 0.25, depending on migration progress
**Tracking issue:** #7010

## Motivation

Legacy struct providers have been deprecated for a long time, yet the native Python rules (`py_library`, `py_binary`, `py_test`) still use them internally and for sandwiching with Starlark-defined rules. As of 0.23, there is now a [`PyInfo`](https://docs.bazel.build/versions/master/skylark/lib/PyInfo.html) provider that has the same fields as the struct. All rules should migrate to using `PyInfo` exclusively so we can help remove struct providers from Bazel altogether.

## Change

When a dependency of a native Python rule has both the legacy provider and `PyInfo` provider, the legacy one is ignored.

When the incompatible flag is enabled, it is not even allowed for a dependency to pass the legacy provider to the native Python rules. Doing so produces an error like:

> The legacy `"py"` provider is disallowed. Migrate to the PyInfo provider instead.

(Strictly speaking, we could have allowed this and just continued to ignore the legacy provider, but failing fast whenever we see `"py"` helps us locate rules that need to be migrated.

## Migration

See [Migrating from Legacy Providers](https://docs.bazel.build/versions/master/skylark/rules.html#migrating-from-legacy-providers) for general information about supporting both legacy and modern providers within the same ruleset.

The recommended migration steps are to:

1. Update rules to produce both providers (with identical field values).
2. Update rules to accept either provider from their dependencies (but prefer `PyInfo` over `"py"`).
3. Update rules to no longer produce `"py"`.
4. Flip the flag in your build and validate that it works.
5. Update rules to no longer care about `"py"` in their dependencies.

**Comment by katre** [comment]
This issue was tagged as "breaking-change-0.24" but does not appear ready to be flipped in the [0.24.0 release](https://github.com/bazelbuild/bazel/issues/6968). If this is incorrect please comment on that issue and discuss with me.

**Comment by brandjon** [comment]
Changing target to 0.25.

**Comment by brandjon** [comment]
According to a [recent run of the bazelisk CI](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/40), the only downstream failures due to this flag are fixed by PRs bazelbuild/rules_appengine#99 and bazelbuild/intellij#538.
