### ISSUE TITLE
--remote_http_cache build option crash

### ISSUE THREAD

**Issue by lisaonduty** [bazelbuild/bazel#7302]
### Description of the problem / feature request:

According to the answer of case: Support of [no] addition of --remote_http_cache build option #6719
It shall be possible to give the build option with an empty value.
But that will crash. The case was closed and it seems like the comment was never read.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Just give the build option with an empty value, please see comment (lisaonduty commented on Nov 27, 2018) on  #6719

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

0.20.0

**Comment by dslomov** [comment]
Sorry about that, will reopen #6719.
