### ISSUE TITLE
Error when WORKSPACE uses REPOSITORY_NAME

### ISSUE THREAD

**Issue by Reflexe** [bazelbuild/bazel#7305]
### Description of the problem / feature request:
When trying to run an external repository that uses `REPOSITORY_NAME` or `PACKAGE_NAME` on a WORKSPACE file, it fails with `"builtin variable 'REPOSITORY_NAME' is referenced before assignment."`; however it does work with `native.repository_name()` which should be equivalent. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
[bug.zip](https://github.com/bazelbuild/bazel/files/2814551/bug.zip)

`WORKSPACE`:
```python
local_repository(name = "repo", path="repo")

load("@repo//:file.bzl", "print_repository")
print_repository()
```
`repo/WORKSPACE`: empty
`repo/BUILD
`: empty

`repo/file.bzl`:
```python
def print_repository():
    print(REPOSITORY_NAME)
```

### What operating system are you running Bazel on?

Linux
### What's the output of `bazel info release`?

release 0.22.0- (@non-git)
### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

This is the official archlinux's bazel package
###  Have you found anything relevant by searching the web?

Nope

### Any other information, logs, or outputs that you want to share?
See [bug.zip](https://github.com/bazelbuild/bazel/files/2814551/bug.zip) for an example.

**Comment by vishwajit123** [comment]
@Reflexe Hey, were you able to resolve this issue?
If yes, could you please explain

**Comment by Reflexe** [comment]
@vishwajit123 see https://github.com/bazelbuild/bazel/issues/7331
