### ISSUE TITLE
docker_build example does not work due to implicit dependency on '/tools/build _defs/pkg:build_tar'

### ISSUE THREAD

**Issue by killerfoxi** [bazelbuild/bazel#731]
Currently trying to package an external docker repo similar to the example provided in the docs. It always fails with

```
ERROR: /home/killerfoxi/.cache/bazel/_bazel_killerfoxi/a3c45aa3028dd8039c18e7604e2918d1/external/docker-git
/BUILD:3:1: every rule of type docker_build_ implicitly depends upon the target '@docker-git//tools/build
_defs/pkg:build_tar',  but this target could not be found. If this is an integration test, maybe you forg
ot to add a mock for your new tool?
```

It can be reproduced with the example given on the docs. So I doubt it's a problem with my build rules.
I refer to this example: "Pulling images and deb files from the internet" on http://bazel.io/docs/be/docker.html the "docker-debian" example.

I have worked around the issue for now as of creating a filegroup in the external BUILD file and do the docker_build rule in another BUILD file (which belongs to my workspace). This works, but is ugly.

e.g.:

```python
docker_build(
  name = "docker-git",
  tars = ["@docker-git//:docker-git_tar"],
)
```

**Comment by damienmg** [comment]
This look like a problem with remote repository, can you retry with Bazel at HEAD?

**Comment by damienmg** [comment]
Closing as unreproducible
