### ISSUE TITLE
py_import is missing

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#7312]
### Description of the problem / feature request:

When working with Java, it's possible to rely on third party jars using the `java_import` rule. The same should be possible for python. Following the same naming conventions as bazel already has, this might be called `py_import`.

The Python world uses eggs and wheels as the common formats for packaging dependencies, and both of these should be supported.

### Feature requests: what underlying problem are you trying to solve with this feature?

I want to build python code using third party dependencies.

### What's the output of `bazel info release`?

`release 0.22.0`

###  Have you found anything relevant by searching the web?

There is a `[whl_import](https://github.com/bazelbuild/rules_python/blob/master/docs/python/whl.md)` but this creates a new repository, where it's very easy to have name clashes (and it looks ugly, and obscures where on the disk the dependencies are kept)

**Comment by brandjon** [comment]
Support for integration with Python package management is the job of bazelbuild/rules_python (and other pure-Starlark rulesets). So this isn't an issue for the native Python rules, although it is important for Bazel's broader Python support.

IIUC, you want a (non-repo) rule that unpacks a checked-in (not network-fetched) wheel and exposes it as a `py_library`-like target?

**Comment by shs96c** [comment]
Yeah, that’s exactly it. Essentially “java_import” for python.

**Comment by beasleyr-vmw** [comment]
Issue management question:

> Support for integration with Python package management is the job of bazelbuild/rules_python (and other pure-Starlark rulesets). So this isn't an issue for the native Python rules, although it is important for Bazel's broader Python support.

In that case, could a project admin please transfer this issue to rules_python? Or do the Bazel devs prefer to keep this open here as a placeholder for anyone searching Bazel issues for `py_import`?

**Comment by brandjon** [comment]
Most Bazel team members aren't admins of most repositories, and though I am admin in rules_python, I'm not here. +@aiuto, any recommendations for whether and how we should transfer issues?

**Comment by beasleyr-vmw** [comment]
I'd hoped that, at least for eggs, this would be as easy as 

```python
def _py_import_impl(ctx):
    return [
        DefaultInfo(
            default_runfiles = ctx.runfiles(ctx.files.src),
        ),
        PyInfo(
            transitive_sources = depset(),
            imports = depset(direct = [ctx.file.src.path]),
        ),
    ]

py_import = rule(
    implementation = _py_import_impl,
    attrs = {
        "src": attr.label(allow_single_file = True),
    },
)
```

but I'm choking at runtime because my `imports` definition doesn't line up with the `runfiles` tree. I suspect that this is because I need to perform some sort of imports fixup like in [BazelPythonSemantics.java], but I can't figure out how to do so in Starlark. (FWIW, I'm using 0.24.0.)

[BazelPythonSemantics.java]: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/python/BazelPythonSemantics.java#L103

**Comment by beasleyr-vmw** [comment]
> I'd hoped that, at least for eggs, this would be as easy as

Looks like this is all I needed:

```python
load("@bazel_skylib//lib:paths.bzl", "paths")


def _py_import_impl(ctx):
    # See https://github.com/bazelbuild/bazel/blob/0.24.0/src/main/java/com/google/devtools/build/lib/bazel/rules/python/BazelPythonSemantics.java#L104 .                                                                                 
    import_path = paths.normalize(paths.join(ctx.workspace_name, ctx.file.src.short_path))
    ...
```

**Comment by shs96c** [comment]
Closing because https://github.com/bazelbuild/rules_python/issues/222 replaces this.
