### ISSUE TITLE
cc autoconfiguration resolves symlinks in builtin include paths

### ISSUE THREAD

**Issue by asuffield** [bazelbuild/bazel#7315]
### Description of the problem / feature request:

When using c++ autoconfiguration, symlinks get fully resolved in include paths. When combined with remote builds, and machines that have differing symlinks in the compiler install path, the result is that the builtin_cxx_include_path entry in @local_config_cc//:CROSSTOOL and the paths in the .d files generated by the compiler will not match, and the build will fail with "missing dependency declarations" errors.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Install the compiler headers (gcc/include/c++/...) in a directory referenced by a symlink. We'll call this path /sw/gcc
Change the name of the symlink's target directory on different hosts, while keeping the path the same. This happens with interesting network mounts; we'll call the target paths /afs/ny-server/gcc and /afs/ln-server/gcc
Build any c++ code that includes a standard library header, with bazel running on one of these hosts, and a remote executor on another host.

The build will fail with errors about invalid dependencies on /afs/ny-server/gcc/include/c++/6.3.1/cstdio and similar files - which is a path that exists on the host where bazel is run, and not on the remote execution host.

### What operating system are you running Bazel on?

linux

### What's the output of `bazel info release`?

release 0.21.0- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Built from dist tarball (with minor patches)

### Any other information, logs, or outputs that you want to share?

The bug is coming from here:
https://github.com/bazelbuild/bazel/blob/41f06577569812366a99c047058507da23822727/tools/cpp/unix_cc_configure.bzl#L129

Running gcc like this will give absolute paths. The flag --no-canonical-prefixes is needed to prevent this behaviour.

**Comment by asuffield** [comment]
Further discovery: there is an -fno-canonical-system-headers flag being added, which purports to be sufficient, but is demonstrably not adequate to prevent the symlink from being resolved. Only --no-canonical-prefixes achieves this.

This behaviour is not consistent between all builds of gcc - I have one compiler where it happens, and another where it does not. The compiler which shows the bug is 6.3.1, and is not compiled --with-sysroot, which I suspect to be the trigger condition.

**Comment by scentini** [comment]
Fixed by 1b4c37c.
Thank you for your contribution!

**Comment by hlopko** [comment]
Reopening since the change was rolled back because of https://github.com/bazelbuild/bazel/issues/7605.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
