### ISSUE TITLE
Feature Request: Allow empty tests after applying --test_filter (Java)

### ISSUE THREAD

**Issue by theindexer** [bazelbuild/bazel#7319]
### Description of the problem / feature request:

Add the option to ignore NoTestsRemainException after applying `--test_filter` (in Java)

### Feature requests: what underlying problem are you trying to solve with this feature?

As a Java dev, I haven't investigated how this behaves / underlying code for other supported languages.

When using `--test_filter`, the test will fail if there are no matching tests. This is inconvenient for `test_suite`s and other informal collections of tests. For instance, we have a convenient way to run all test targets associated with `MyService`. When diagnosing a failing test, running that tool with a `--test_filter` passed through seems like the best way to go about it, but results in as many "spurious" errors as there are targets with no matching tests.

The alternative is to manually seek out the target with the failing test* and apply the filter, which loses out on the conveniences offered by our tooling layer.

Something like the NoOpRunner would be a nice alternative, as what happens for sharding.

*or open the test in intellij and generate the filter, but the idea here is to avoid having to take that step

### Example

run
```
bazel test testTargetAWithMatch testTargetBWithoutMatch --test_filter=matchTargetA
```
and observe testTargetA pass but B will fail with 
`java.lang.Exception: No tests found matching RegEx[matchTargetA]`

### What's the output of `bazel info release`?

release 0.22.0

###  Have you found anything relevant by searching the web?

No :(, but here's a line of code that could be modified depending on desired behavior.

https://github.com/bazelbuild/bazel/blob/master/src/java_tools/junitrunner/java/com/google/testing/junit/runner/junit4/JUnit4Runner.java#L209

### Other

Seems like a niche use case based off my googling so I'm debating whether or not to even make this request, but I guess I'll just do it.

**Comment by meisterT** [comment]
I've put this into the ice-box to indicate that we currently don't have time to work on this issue.

**Comment by henrypoon** [comment]
@theindexer any alternatives you found after? I am having a similar here and don't want to fail the test when there are no tests found.

**Comment by isopropylcyanide** [comment]
The bazel behaviour in Go, is to fail silently for tests not matching the test filter. Not sure, why Java blows up with an initialization error.

```
There was 1 failure:
1) initializationError(org.junit.runner.manipulation.Filter)
java.lang.Exception: No tests found matching RegEx
```
