### ISSUE TITLE
incompatible_disable_crosstool_file: Disable loading data from CROSSTOOL files

### ISSUE THREAD

**Issue by scentini** [bazelbuild/bazel#7320]
Flag: `--incompatible_disable_crosstool_file`
Available since: 0.23 (February 2019 release)
Will be flipped in: 0.24 (March 2019 release)

Motivation
 The motivation for this change is described here: [design doc](https://docs.google.com/document/d/1Nqf16jqDGWSrPp4VuRxh0iNnVBoAXsO0meDH69J9xoc)
#5380 tracks the effort of rewriting CROSSTOOL files in Starlark.

Migration
`cc_toolchain`s should have one extra attribute - `toolchain_config` that points to a target that provides CcToolchainConfigInfo (by calling [`cc_common.create_cc_toolchain_config_info()`](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/cpp/CcModule.java#L709)).
[`cc_toolchain_config_lib.bzl`](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/cc_toolchain_config_lib.bzl) provides Starlark equivalents for all structures and substructures defined in [`crosstool_config.proto`](https://github.com/bazelbuild/bazel/blob/master/src/main/protobuf/crosstool_config.proto).

A migrator script that converts a CROSSTOOL file to a Starlark rule can be found under [`rules_cc/blob/master/tools/migration`](https://github.com/bazelbuild/rules_cc/blob/master/tools/migration/BUILD#L89). The script assumes that the CROSSTOOL file does not contain legacy fields (see [incompatible_disable_legacy_crosstool_fields](https://github.com/bazelbuild/bazel/issues/6861)).

[`ctoolchain_compare.bzl`](https://github.com/bazelbuild/rules_cc/blob/master/tools/migration/ctoolchain_compare.bzl#L24) is a test rule that compares a CToolchain from a CROSSTOOL file and a Starlark rule.

**Comment by keith** [comment]
I'm making a crosstool change here https://github.com/bazelbuild/bazel/pull/7356 should I be editing the new file instead of the old CROSSTOOL.tpl? I attempted to run the migrator from rules_cc but ended up with a file that's very different from the one checked in, which makes me assume that's not perfectly reproducible

**Comment by scentini** [comment]
The new one. I will remove the CROSSTOOL files and the templates very soon, they are not needed anymore.
The rules_cc migrator doesn't work with templates, therefore I did some manual changes in order to convert the CROSSTOOL.tpl into cc_toolchain_config.bzl.tpl.

**Comment by scentini** [comment]
Due to a bug discovered in [incompatible_disable_legacy_crosstool_fields](https://github.com/bazelbuild/bazel/issues/6861), we are postponing the migration window to 0.24, and the breaking release will be 0.25. Apologies for the inconvenience.
