### ISSUE TITLE
http_archive decompressing: improve message when the prefix is wrong

### ISSUE THREAD

**Issue by irengrig** [bazelbuild/bazel#7321]
Typically, if I want to use a github project/library, I navigate to github page of that project and copy the url of the released contents, typically an archive.
At this moment, I am not aware of the prefix that is used inside the archive, it for sure is combined name and version, but it can use minuses (-) or underscores (_) or "v" symbol for the version.

It would be nice of the error about the wrong prefix informed me which prefix it actually was.

For instance, instead of:
ERROR: <...>/3ef9cfc3a9b14f5d67990ffd01552d35/external/rules_foreign_cc_tests/configure_gnuplot/BUILD:4:1: no such package '@zlib//': java.io.IOException: Prefix zlib-1.2.111 was given, but not found in the archive and referenced by '@rules_foreign_cc_tests//configure_gnuplot:libz'
ERROR: Analysis of target '@rules_foreign_cc_tests//configure_gnuplot:test_zlib' failed; build aborted: Analysis failed

It could say "Prefix XYZ was given, the actual prefix is ZYX"

**Comment by Reflexe** [comment]
Take a look at https://github.com/bazelbuild/bazel/pull/7333 please.

**Comment by dslomov** [comment]
(there is already a suggested fix in #7333)
