### ISSUE TITLE
cc_proto_library fails to build if proto_library dependency uses "strip_import_path" parameter

### ISSUE THREAD

**Issue by RNabel** [bazelbuild/bazel#7325]
### Description of the problem / feature request:

If a `cc_proto_library` depends on a `proto_library` which uses the `strip_import_prefix` parameter, compilation fails.

### Feature requests: what underlying problem are you trying to solve with this feature?

Compilation failure.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Unzip [cc_proto_library_repro.zip](https://github.com/bazelbuild/bazel/files/2822558/cc_proto_library_repro.zip) into a directory of your choice.
0. Run `bazel version` ensure it says Bazel 0.22.
0. Run `bazel build //proto/foo:a_proto_cc`
0. Observe failure.

Full output (running with `-s`):
```
SUBCOMMAND: # //proto/foo:a_proto [action 'Generating C++ proto_library //proto/foo:a_proto']
(cd <home dir>/.cache/bazel/_bazel_<username>/37b707ebd0de8b0a0047ae3b98f5af5e/execroot/__main__ && \
  exec env - \
    PATH=<...> \
  bazel-out/host/bin/external/com_google_protobuf/protoc '--proto_path=bazel-out/k8-fastbuild/genfiles/proto/foo/_virtual_imports/a_proto' '--cpp_out=bazel-out/k8-fastbuild/genfiles/bazel-out/k8-fastbuild/genfiles/proto/foo/_virtual_imports/a_proto' '-Ifoo/a.proto=bazel-out/k8-fastbuild/genfiles/proto/foo/_virtual_imports/a_proto/foo/a.proto' '-Iproto/foo/_virtual_imports/a_proto/foo/a.proto=bazel-out/k8-fastbuild/genfiles/proto/foo/_virtual_imports/a_proto/foo/a.proto' --direct_dependencies proto/foo/a.proto '--direct_dependencies_violation_msg=%s is imported, but //proto/foo:a_proto doesn'\''t directly depend on a proto_library that '\''srcs'\'' it.' bazel-out/k8-fastbuild/genfiles/proto/foo/_virtual_imports/a_proto/foo/a.proto)
ERROR: /repos/bazel-proto-library-repro/proto/foo/BUILD:3:1: Generating C++ proto_library //proto/foo:a_proto failed (Exit 1) protoc failed: error executing command bazel-out/host/bin/external/com_google_protobuf/protoc '--proto_path=bazel-out/k8-fastbuild/genfiles/proto/foo/_virtual_imports/a_proto' ... (remaining 7 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-fastbuild/genfiles/bazel-out/k8-fastbuild/genfiles/proto/foo/_virtual_imports/a_proto/: No such file or directory
Target //proto/foo:a_proto_cc failed to build
```

A working example is included, showing that workspace relative paths still work:
`bazel build //proto/foo:a_proto_cc_workspace_relative`.

File structure:
```
.
├── proto
│   └── foo
│       ├── a.proto
│       ├── BUILD
│       └── workspace_relative.proto
└── WORKSPACE
```
`foo/BUILD` contents:
```
proto_library(
    name = "a_proto",
    srcs = ["a.proto"],
    strip_import_prefix = "/proto",
)

cc_proto_library(
    name = "a_proto_cc",
    deps = [":a_proto"],
)

proto_library(
    name = "a_proto_workspace_relative",
    srcs = ["a.proto"],
)

cc_proto_library(
    name = "a_proto_cc_workspace_relative",
    deps = [":a_proto_workspace_relative"],
)
```

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

`release 0.22.0`

###  Have you found anything relevant by searching the web?

Potentially related issue: https://github.com/bazelbuild/bazel/issues/7060

**Comment by lberki** [comment]
Thanks for the precise reproduction! This looks important but sadly, I have no idea who could possibly fix it in the short term :(

**Comment by lberki** [comment]
...actually, I have just fixed this in our internal version, so I *think* I can fix it in whatever crumbs of free time I have. It won't be pretty, but hopefully it'll work.

/cc @dbabkin

**Comment by RNabel** [comment]
Awesome, thanks for fixing this!

**Comment by lberki** [comment]
My pleasure :)
