### ISSUE TITLE
Remove "local execution delay" from dynamic spawn scheduler

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/bazel#7327]
The dynamic spawn scheduler implements a "local execution delay", controlled via the `--experimental_local_execution_delay` flag, that we should remove.

This delay exists so that, in the case of a build that is fully cached remotely, we don't end up running any actions locally. The delay allows the scheduler to try to score a cache hit for every action and, assuming all cache hits succeed before this delay, the local counterparts never start. But as soon as an action takes longer than this delay, the scheduler assumes that the build is unclean and it will have to do work, so it starts also scheduling actions locally.

This delay is only paid once per build and, because it's set to 1 second by default, it's not a big penalty -- but regardless, it's ugly and we should remove it.

To remove this delay, we can propagate a cache miss signal from the remote execution logic to the dynamic scheduler. We can then use this signal to decide when it's time for the dynamic spawn scheduler to start running actions locally.

**Comment by dslomov** [comment]
(please do not assign issues to more than one `team-*`)

**Comment by larsrc-google** [comment]
Using a cache miss signal alone to determine whether to start running actions locally would not help with the other benefit of dynamic execution: Being able to cope with flaky or slow internet connections transparently (apart from becoming slower).

**Comment by jmmv** [comment]
You'd need to have both: a cache miss and a timeout. If the timeout was set to the existing value of the delay, then the overall behavior should be the same or better, right?

**Comment by larsrc-google** [comment]
Yes, that would work.

**Comment by larsrc-google** [comment]
I've fixed the code so the delay is only enabled once we see an actual cache hit, not as soon as a remote answer is faster. It always worked as a latch: The delay gets enabled for a build once we see a cache hit, it's not that the delay is enabled until we see a non-cache-hit. The risk in removing the delay is that we start scheduling useless dynamic actions that delay things that have to happen locally, and also adds more load to the machine. We have not found a useful alternative to the delay.
