### ISSUE TITLE
Buildifier is broken at our CI

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel#7341]
For example: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/789#e7e2597f-41b2-4bb0-bf5c-eddad2e40b0f

We should either remove them from our downstream projects (temporarily) and/or fix them.

**Comment by laurentlb** [comment]
The buildkite link is green on https://github.com/bazelbuild/buildtools/
(https://buildkite.com/bazel/buildtools)

Is it a configuration problem? cc @meteorcloudy

**Comment by sergiocampama** [comment]
Speaking of which, when will the be a new release of buildifier for the new versions of Bazel?

**Comment by meteorcloudy** [comment]
I think the failing job is related adding buildifier support on CI (See https://github.com/bazelbuild/continuous-integration/pull/448), it's not the buildifier project itself. And I don't see it anymore. So I'm closing this issue.

**Comment by fweikert** [comment]
The error in the first link was fixed by https://github.com/bazelbuild/continuous-integration/commit/3e0ffabb932a45d6cb9e271c31f916f5b531234c
