### ISSUE TITLE
Not having a system JDK can waste Bazel memory

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#7342]
Let's set up a little workspace:
```
$ bazel version
Build label: 0.22.0
$ touch WORKSPACE
$ cat > BUILD
java_binary(name = 'useless-binary')
$ mkdir manyfiles
$ python3 -c 'for i in range(1000000): open("bin/" + str(i) + ".txt", "wb").close()'
```
We can run `bazel fetch` with a system JDK installed and measure the retained heap size of the Bazel server:
```
$ which javac
/usr/bin/javac
$ bazel fetch //:useless-binary
$ bazel info used-heap-size-after-gc
23MB
```
If we repeat that exercise without a system JDK, the result is surprisingly different:
```
$ sudo apt purge default-jdk-headless --autoremove -y
$ which javac
$ bazel fetch //:useless-binary
WARNING: Running Bazel server needs to be killed, because the startup options are different.
$ bazel info used-heap-size-after-gc
167MB
```
The problem here is the `@local_jdk` external workspace. When there's a system JDK, `@local_jdk` is a local repository rule pointing to the java home. When there's no system JDK, though, `@local_jdk` ends up aliasing the main workspace. The [`BUILD` file for `@local_jdk` has a `**` glob](https://github.com/bazelbuild/bazel/blob/984ffa050b6de40b1e46402eaa1a1def44e7e09b/src/main/tools/jdk.BUILD#L146). So, all 1,000,000 files in `bin/*` are swept up and cached in Skyframe. If the workspace had the `bazel-*` convenience symlinks, the entire output tree would have been globbed, too.

**Comment by meisterT** [comment]
cc @iirina

**Comment by meisterT** [comment]
Seems to be fixed by now.

**Comment by benjaminp** [comment]
In the time since my report, the `jdk.BUILD` file has been slightly perturbed so my exact reproducer no longer works. However, this issue still exists. If you replace `manyfiles` with `bin` in my example, it will reproduce again.
