### ISSUE TITLE
Remove objc_proto_library rule

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#7348]
`objc_proto_library` is not usable in Bazel. The code is present because it may be used inside Google. We should remove the rule from Bazel and from its documentation (https://docs.bazel.build/versions/master/be/objective-c.html#objc_proto_library).

(tracking bug in Google: b/123888674)

**Comment by lberki** [comment]
What about e.g. `apple_binary` -> `proto_library` dependencies?

Removing the rule itself is a trivial amount of work, but it appears that `apple_binary` and `apple_static_library` also use the aspect. Does this mean that those rules can't depend directly on `proto_library` rules?

**Comment by lberki** [comment]
What does that aspect do then? I mean, `objc_proto_library` propagates that aspect just as well, so what extra functionality does `apple_binary` / `apple_static_library` gain from it?

**Comment by sergiocampama** [comment]
`apple_binary` propagates the aspect to collect all `proto_library` sources and other files to generate a comprehensive list of protos and which symbols are required, and at that point generate/compile/link them into the binary.

We'd like to remove the processing done in `apple_binary` at some point, but disallowing the `objc_proto_library` rule from Bazel should be orthogonal to that cleanup.

Please ping me for a more in depth description of how objc protos work, if you want to gaze into the abyss.

**Comment by lberki** [comment]
Well, I thought it was simpler than that :) My motivation was to also remove the aspect implementation and not just `objc_proto_library` itself. 

Let's continue the discussion on the "Bazel 1.0 and objc_proto_library" thread.

**Comment by dnkoutso** [comment]
Related https://github.com/bazelbuild/bazel/issues/1802

**Comment by dslomov** [comment]
This P1 bazel 1.0 issue is unassigned. Please assign cc @aragos

**Comment by thomasvl** [comment]
@sergiocampama is working on this

**Comment by dslomov** [comment]
Does not seem to be on track for 1.0

**Comment by sergiocampama** [comment]
`objc_proto_library` has been deleted from the native codebase, but not all native support has been removed. We would have liked to remove this sooner, but there are still unresolved blockers.

**Comment by meisterT** [comment]
I think this is gone by now, isn't it? cc @c-parsons

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
