### ISSUE TITLE
Make actions.args() object chainable

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#7352]
We have a user request for making actions.args() object chainable:

```python
arguments = [ctx.attr.args().add("--foo").add_all(srcs)],
```

I think it can be useful and make the code shorter in some cases.

**Comment by brandjon** [comment]
Do we have good automatic formatting for this case, assuming the user doesn't want to squeeze it all on one line?

**Comment by laurentlb** [comment]
Yes, formatting looks fine to me, e.g.

```python
arguments = (
    ctx.attr.args()
        .add("--foo")
        .add_all(srcs),
)
```
