### ISSUE TITLE
Invalid SHA256 checksum error

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#7353]
When SHA256 checksum is invalid, the error message is:
```
ERROR: /usr/local/google/home/dslomov/work/rules_closure/java/com/google/javascript/jscomp/BUILD:17:1: no such package '@com_google_javascript_closure_compiler//': java.io.IOException: Invalid SHA256 checksum and referenced by '//java/com/google/javascript/jscomp:jscomp'
```

It does not tell me where the invalid SHA is coming from.

See the following example (where jar_sha256 is a bogus string):

```
    java_import_external(
        name = "com_google_javascript_closure_compiler",
        licenses = ["reciprocal"],  # MPL v1.1 (Rhino AST), Apache 2.0 (JSCompiler)
        jar_urls = [
            "https://mirror.bazel.build/repo1.maven.org/maven2/com/google/javascript/closure-compiler-unshaded/v20181125/closure-compiler-unshaded-v20181125.jar",
            "http://repo1.maven.org/maven2/com/google/javascript/closure-compiler-unshaded/v20181125/closure-compiler-unshaded-v20181125.jar",
        ],
        jar_sha256 = "facf537aad7f643c92771f71bd8d9c9b6830ec2aa56e458d2411678d8dc32453672",
    )
```

I guess we need fixes in both `rctx.download`  (to properly report this) and in `java_import_external` (to propagate the report)

**Comment by aehlig** [comment]
`ctx.download` already accepts an empty `sha256` argument and will report the `SHA256` sum of the file actually downloaded, at least as an `INFO` event.

**Comment by aehlig** [comment]
Actually, `ctx.download` already returns the needed hash sum. So it is only about changing `java_import_external` to make good use of `ctx.download`.

**Comment by dslomov** [comment]
To be clear, the error message should contain:
1. Precise location of an error (`jar_sha256` attribute of repository rule "com_google_javascript_closure_compiler" with its location)
1. Actual checksum of the file downloaded

Currently the error location reported is:
```
ERROR: /usr/local/google/home/dslomov/work/rules_closure/java/com/google/javascript/jscomp/BUILD:17:1: no such package '@com_google_javascript_closure_compiler//': java.io.IOException: Invalid SHA256 checksum and referenced by '//java/com/google/javascript/jscomp:jscomp'`
```
which is unrelated to the repository rule in question
