### ISSUE TITLE
incompatible_disallow_split_empty_separator: string.split shouldn't accept empty separator

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#7355]
From https://github.com/bazelbuild/starlark/blob/master/spec.md#string%C2%B7split
> "If sep is the empty string, split fails."

Yet:

```
% src/main/java/com/google/devtools/skylark/Skylark
>> "abc".split("")
.. 
["a", "b", "c", ""]
```

Compare:

```
% python2
>>> "abc".split("")
ValueError: empty separator

% python3
>>> "abc".split("")
ValueError: empty separator

% starlark  # go.starlark.net
>>> "abc".split("")
Error: split: empty separator
```

When the flag `incompatible_disallow_split_empty_separator` is set to true, string.split requires a separator. The default will be true with Bazel 1.0.

Fix:

Use [`string.elems`](https://docs.bazel.build/versions/master/skylark/lib/string.html#elems) instead.

**Comment by laurentlb** [comment]
cc @Quarz0 - want to send a PR?

**Comment by dslomov** [comment]
Is there migration tooling? What is the extent of breakage?

**Comment by laurentlb** [comment]
Breakages are expected to be extremely rare. There's only one occurrence of it in all of Google code base.

It's not worth writing a tool for this.

**Comment by dslomov** [comment]
Let's see what the https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/ has to say.

**Comment by laurentlb** [comment]
Flipped in https://github.com/bazelbuild/bazel/commit/67cc4263dbfc5827fe5928195f2898a85cbc33ca
