### ISSUE TITLE
py_binary DefaultInfo.default_runfiles does not include auto-generated __init__.py files

### ISSUE THREAD

**Issue by chrismcbride** [bazelbuild/bazel#7357]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Auto-generated empty __init__.py files from a py_binary are not being added to DefaultInfo.default_runfiles despite being added when using ctx.runfiles(collect_default=True)

### Feature requests: what underlying problem are you trying to solve with this feature?

Im trying to write a rule that can wrap a py_binary executable

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

def.bzl:

```python
def _py_wrapper_transitive_impl(ctx):
    ctx.actions.write(
        output = ctx.outputs.executable,
        content = "#!/bin/sh -eu\n./" + ctx.attr.src.files_to_run.executable.short_path,
        is_executable = True,
    )

    return [DefaultInfo(runfiles = ctx.runfiles(
        transitive_files = ctx.attr.src[DefaultInfo].default_runfiles.files,
    ))]

py_wrapper_transitive = rule(
    implementation = _py_wrapper_transitive_impl,
    executable = True,
    attrs = {
        "src": attr.label(executable = True, mandatory = True, cfg = "host"),
    },
)

def _py_wrapper_collect_default_impl(ctx):
    ctx.actions.write(
        output = ctx.outputs.executable,
        content = "#!/bin/sh -eu\n./" + ctx.attr.srcs[0].files_to_run.executable.short_path,
        is_executable = True,
    )

    return [DefaultInfo(runfiles = ctx.runfiles(collect_default = True))]

py_wrapper_collect_default = rule(
    implementation = _py_wrapper_collect_default_impl,
    executable = True,
    attrs = {
        "srcs": attr.label_list(mandatory = True),
    },
)
```

BUILD
```python
load(":def.bzl", "py_wrapper_collect_default", "py_wrapper_transitive")

py_binary(
    name = "main",
    srcs = ["main.py"],
    deps = ["//lib"],
)

py_wrapper_collect_default(
    name = "collect_default",
    srcs = ["main"],
)

py_wrapper_transitive(
    name = "transitive",
    src = "main",
)
```

main.py
```python
from lib import lib

lib.hi()
```

lib/BUILD
```python
py_library(
    name = "lib",
    srcs = ["lib.py"],
    visibility = ["//visibility:public"],
)
```

lib/lib.py
```
def hi():
  print("hi")
```

Running all three targets:
```sh
[pytest]$ bazel run :main
INFO: Analysed target //:main (1 packages loaded).
INFO: Found 1 target...
Target //:main up-to-date:
  bazel-bin/main
INFO: Elapsed time: 0.108s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 3 total actions
INFO: Build completed successfully, 3 total actions
hi

[pytest]$ bazel run :collect_default
INFO: Analysed target //:collect_default (0 packages loaded).
INFO: Found 1 target...
Target //:collect_default up-to-date:
  bazel-bin/collect_default
INFO: Elapsed time: 0.092s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 2 total actions
INFO: Build completed successfully, 2 total actions
hi

[pytest]$ bazel run :transitive
INFO: Analysed target //:transitive (0 packages loaded).
INFO: Found 1 target...
Target //:transitive up-to-date:
  bazel-bin/transitive
INFO: Elapsed time: 0.092s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 2 total actions
INFO: Build completed successfully, 2 total actions
Traceback (most recent call last):
  File "/home/mcbride/.cache/bazel/_bazel_mcbride/5cae0d95dec541a2694ba8a3b26cb0e9/execroot/__main__/bazel-out/k8-fastbuild/bin/transitive.runfiles/__main__/main.py", line 1, in <module>
    from lib import lib
ImportError: No module named lib
```
In the case of using the transitive runfiles the auto-gen'd __init__.py is missing from lib/. Using collect_default includes it. Ive also tried using the data_runfiles. Note this is only reproducible using python2 since python3 doesnt require empty __init__.py files.

### What operating system are you running Bazel on?

linux 4.19.4

### What's the output of `bazel info release`?

release 0.18.0

###  Have you found anything relevant by searching the web?

Nothing relating to this exact issue.

**Comment by brandjon** [comment]
The runfiles API in Starlark is a bit quirky, and so is the concept of these auto-generated empty `__init__.py` files. We're trying to [move away from](https://docs.bazel.build/versions/master/be/python.html#py_binary.legacy_create_init) auto-generating init files anyway, so if possible you could migrate your build to have explicit source init files instead.

**Comment by rohansingh** [comment]
@brandjon I think that would be reasonable except that stuff like `@bazel_tools//python/runfiles` doesn't even do that yet, so there's no way to wrap it without hacks. Or am I missing something?

**Comment by brandjon** [comment]
Sounds fair. There may be another way but I'm not aware of it. I think it's just a matter of better runfiles documentation and API. For instance, you can retrieve a depset of the names of the init files with [`runfiles.empty_filenames`](https://docs.bazel.build/versions/master/skylark/lib/runfiles.html#empty_filenames), but it's not clear how to pass them to the [runfiles constructor](https://docs.bazel.build/versions/master/skylark/lib/ctx.html#runfiles).

**Comment by rohansingh** [comment]
Oh awesome, that's the piece I was missing. I was then able to successfully able to wrap my `py_binary` with:

```python
empty_files = []
root_symlinks = {}
for fn in ctx.attr._some_py_binary[DefaultInfo].default_runfiles.empty_filenames:
    f = ctx.actions.declare_file(fn)
    ctx.actions.write(f, "")

    empty_files.append(f)
    if fn.startswith("external/"):
        trimmed_fn = fn[len("external/"):]
        root_symlinks[trimmed_fn] = f

transitive_runfiles = depset(
    transitive = [
        ctx.attr._some_py_binary[DefaultInfo].default_runfiles.files,
        depset(empty_files),
    ],
)

runfiles = ctx.runfiles(
    collect_default = True,
    transitive_files = transitive_runfiles,
    root_symlinks = root_symlinks,
)
```

Not sure if it would work for all cases, but it allowed the dependency on `@bazel_tools//tools/python/runfiles` to work.

**Comment by brandjon** [comment]
Cool, glad that helped a bit.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
