### ISSUE TITLE
incompatible_py3_is_default: Bazel configures targets for Python 3 by default

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#7359]
**Flag:** `--incompatible_py3_is_default`
**Available since:** 0.24
**Will be flipped in:** 0.25
**Tracking issue:** #6647

*It is recommended to enable this flag at the same time as [`--incompatible_py2_outputs_are_suffixed`](https://github.com/bazelbuild/bazel/issues/7593).*

## Motivation

Bazel currently defaults to Python 2 due to historic reasons, but the community has largely moved on to Python 3. We should fix this before 1.0.

**Note:** This incompatible change affects the mechanism that Bazel uses to decide whether a target should be built for Python 2 or 3. However, due to #4815, even when a target is built for Python 3 it may still execute under a Python 2 interpreter. See the workaround using `py_runtime` / `--python_top` in https://github.com/bazelbuild/bazel/issues/4815#issuecomment-460777113.

## Change

As of 0.24, `py_binary` and `py_test` targets that do not specify a `python_version` attribute (formerly called `default_python_version`) will use `PY3` instead of `PY2` when `--incompatible_py3_is_default` is enabled. In addition, `--incompatible_py3_is_default` makes the host configuration use `PY3` instead of `PY2`, unless `--host_force_python=PY2` is given to override this behavior.

`--incompatible_py3_is_default` requires that `--incompatible_allow_python_version_transitions` is set true, or else an error is raised. This means that if you opt out of `--incompatible_allow_python_version_transitions` during the migration window, you should also opt out of `--incompatible_py3_is_default`.

## Migration

Any `py_binary` or `py_test` targets that cannot tolerate Python 3 should have an attribute `python_version = "PY2"` added. You can do this with buildozer using a command like the following:

```
buildozer -k -types 'py_binary,py_test' 'set_if_absent python_version PY2' //...:*
```

For targets that get built in the host configuration, this command can modify their definitions but it will not actually affect the version that they use. If your build has tools in the host configuration that cannot tolerate Python 3, then you can keep the old behavior of using Python 2 for all host configuration targets (across your entire build) by adding `--host_force_python=PY2` to your build invocations. We do not currently have a story for incremental migration of targets in the host configuration to PY3. This is a consequence of the technical limitations of the host configuration, and should be addressed by future work on toolchains.

**Comment by limdor** [comment]
Nice to see this issue. A really good motivation for this issue that is not mentioned could be that Python 2 will reach End of Life in less than 11 months. https://pythonclock.org/

**Comment by brandjon** [comment]
Ran a downstream presubmit with this flag and `--incompatible_py2_outputs_are_suffixed` both flipped. Here's the [results](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/853#601d2a9d-cc78-4ff8-962c-b677a8ea1ee9). We have failures in:

- [TensoryFlow](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/851#bab9da10-9838-4583-9147-7301e0e9ea92)

- [Remote execution](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/853#0c1a2d2d-e935-4d74-bf85-22980e8a9bab)

- [Android Studio Plugin](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/853#07ba19f9-c154-47f9-ae1d-26d4ae301030)

- [Android Testing](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/853#de2ee549-8269-49c4-be34-e924b6a57baa)

For TensorFlow it didn't actually run the test because it failed a hardcoded version check, and it's not clear that it uses the bazel under test. Filed bazelbuild/continuous-integration#569 for assistance.

For the other failures I have no idea whether they're legit or not, and will probably rerun the presubmit to deflake.

**Comment by brandjon** [comment]
All four of these failures are broken at head.

**Comment by brandjon** [comment]
It helps if the branch I'm using actually has the flag flips I'm testing. Sigh. Let's do this over again.

**Comment by brandjon** [comment]
New results [here](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/858#c5a81110-14b8-4ba8-887a-edbdccc0e163).

- TensorFlow and gmaven_rules are already failing, so no information there.

- rules_k8s fails due to `--incompatible_remove_old_python_version_api`, so that needs to be fixed first

- Not sure about the Gerrit failure, could be a flake. It's only on one platform (mac).

As of this post rules_typescript and Bazel itself still have a mac test running.

In any case, this looks good enough that I'm willing to flip both `--incompatible_py3_is_default` and `--incompatible_py2_outputs_are_suffixed` for Bazel 0.25.

**Comment by greggdonovan** [comment]
[~brandjon] This is really promising -- thanks! Does this test exercise rules_docker and, transitively, [containerregistry](https://github.com/google/containerregistry)?

**Comment by brandjon** [comment]
Well I'm not so sure. There is indeed a rules_docker project in the set of downstream tests that get run. But when I tested another flag `--incompatible_remove_old_python_version_api`, I [noticed failures](https://github.com/bazelbuild/bazel/issues/7308#issuecomment-472081689) in rules_k8s but not rules_docker, even though they both have dependencies on subpar that needed updating.

You can test yourself by grabbing Bazel at head, or a 0.24 RC, and passing (at the same time) --incompatible_py3_is_default and --incompatible_py2_outputs_are_suffixed. You can also check the bazel invocation [used in my presubmit](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/858#dbf9466a-bece-4748-a8de-0678de52d8e9) and see if any test targets that would've identified problems were missing.

**Comment by greggdonovan** [comment]
@brandjon Ahh, right, it looks like google/containerregistry needs a new release with an updated subpar to enable rules_docker and rules_k8s to be updated.

**Comment by brandjon** [comment]
In [another run](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/871) today, the only failure is in IntelliJ. They're using an output-path-based method for determining whether a Python target is PY2 or PY3. I'm in communication with them to fix.

**Comment by meteorcloudy** [comment]
This flag is not actually tested on Bazel CI:
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/58

Because it relies on `--incompatible_allow_python_version_transitions`
```
ERROR: cannot enable `--incompatible_py3_is_default` without also enabling `--incompatible_allow_python_version_transitions`
```

Can we automatically enable `--incompatible_allow_python_version_transitions` when `--incompatible_py3_is_default` is specified in code?

**Comment by meteorcloudy** [comment]
I manually tested this flag with Bazel 0.24.0 and got the following error
```
pcloudy@pcloudy:~/workspace/tensorflow
$ bazel build --config=opt tensorflow/tools/pip_package:build_pip_package --incompatible_py3_is_default --incompatible_allow_python_version_transitions
WARNING: /usr/local/google/home/pcloudy/workspace/tensorflow/tensorflow/python/BUILD:3243:1: in py_library rule //tensorflow/python:standard_ops: target '//tensorflow/python:standard_ops' depends on deprecated target '//tensorflow/python/ops/distributions:distributions': TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.distributions will not receive new features, and will be removed by early 2019. You should update all usage of `tf.distributions` to `tfp.distributions`.
WARNING: /usr/local/google/home/pcloudy/workspace/tensorflow/tensorflow/python/BUILD:102:1: in py_library rule //tensorflow/python:no_contrib: target '//tensorflow/python:no_contrib' depends on deprecated target '//tensorflow/python/ops/distributions:distributions': TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.distributions will not receive new features, and will be removed by early 2019. You should update all usage of `tf.distributions` to `tfp.distributions`.
WARNING: /usr/local/google/home/pcloudy/workspace/tensorflow/tensorflow/contrib/metrics/BUILD:16:1: in py_library rule //tensorflow/contrib/metrics:metrics_py: target '//tensorflow/contrib/metrics:metrics_py' depends on deprecated target '//tensorflow/python/ops/distributions:distributions': TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.distributions will not receive new features, and will be removed by early 2019. You should update all usage of `tf.distributions` to `tfp.distributions`.
WARNING: /usr/local/google/home/pcloudy/workspace/tensorflow/tensorflow/contrib/learn/BUILD:17:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': No longer supported. Switch to SavedModel immediately.
WARNING: /usr/local/google/home/pcloudy/workspace/tensorflow/tensorflow/contrib/learn/BUILD:17:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': No longer supported. Switch to SavedModel immediately.
WARNING: /usr/local/google/home/pcloudy/workspace/tensorflow/tensorflow/contrib/bayesflow/BUILD:17:1: in py_library rule //tensorflow/contrib/bayesflow:bayesflow_py: target '//tensorflow/contrib/bayesflow:bayesflow_py' depends on deprecated target '//tensorflow/contrib/distributions:distributions_py': TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.contrib.distributions are unmaintained, unsupported, and will be removed by late 2018. You should update all usage of `tf.contrib.distributions` to `tfp.distributions`.
WARNING: /usr/local/google/home/pcloudy/workspace/tensorflow/tensorflow/contrib/BUILD:13:1: in py_library rule //tensorflow/contrib:contrib_py: target '//tensorflow/contrib:contrib_py' depends on deprecated target '//tensorflow/contrib/distributions:distributions_py': TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.contrib.distributions are unmaintained, unsupported, and will be removed by late 2018. You should update all usage of `tf.contrib.distributions` to `tfp.distributions`.
ERROR: file 'external/icu/_objs/icuuc/uprops.pic.o' is generated by these conflicting actions:
Label: @icu//:icuuc
RuleClass: cc_library rule
Configuration: 98c6e8c3d595f000f2cc3fbc5194178d, cd31cd26593c7ea5d91cb6602ad66fc4
Mnemonic: CppCompile
Action key: ec9d8825160200c6b2b395858d5a2e86
Progress message: Compiling external/icu/icu4c/source/common/uprops.cpp
PrimaryInput: File:[/usr/local/google/home/pcloudy/.cache/bazel/_bazel_pcloudy/d2f15366e3b15100d3593f2d595721a3[source]]external/icu/icu4c/source/common/uprops.cpp
PrimaryOutput: File:[[<execution_root>]bazel-out/k8-py3-opt/bin]external/icu/_objs/icuuc/uprops.pic.o
Primary outputs are different: 972537493, 1038679363
Owner information: @icu//:icuuc BuildConfigurationValue.Key[98c6e8c3d595f000f2cc3fbc5194178d] false, @icu//:icuuc BuildConfigurationValue.Key[cd31cd26593c7ea5d91cb6602ad66fc4] false
MandatoryInputs: are equal
Outputs: Attempted action contains artifacts not in previous action (first 5): 
        external/icu/_objs/icuuc/uprops.pic.o
        external/icu/_objs/icuuc/uprops.pic.d
Previous action contains artifacts not in attempted action (first 5): 
        external/icu/_objs/icuuc/uprops.pic.o
        external/icu/_objs/icuuc/uprops.pic.d
ERROR: com.google.devtools.build.lib.actions.MutableActionGraph$ActionConflictException: for external/icu/_objs/icuuc/uprops.pic.o, previous action: action 'Compiling external/icu/icu4c/source/common/uprops.cpp', attempted action: action 'Compiling external/icu/icu4c/source/common/uprops.cpp'
INFO: Elapsed time: 11.820s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (396 packages loaded, 27672 targets configured)
```

This looks like a bug that has already been fixed at HEAD, but it also means we cannot flip this flag for 0.25.0, because users cannot use 0.24.0 for migration.

**Comment by brandjon** [comment]
See the link in my last post -- I ran the Bazel CI using the downstream w/ bazel@head pipeline, on a custom build that flipped all four python-version-related flags (2 introduced in 0.23 and 2 in 0.24, all to be flipped in 0.25) and it was green. So I don't think migration is actually an issue for this change.

The action conflict issue is partially mitigated by turning on `--incompatible_remove_old_python_version_api`, which is one of those four flags to be flipped in 0.25. The only remaining action conflicts occur in the rarer case that a target is built both at the top-level configuration and at a config reached by transitioning away from the default Python version and then back again.

**Comment by brandjon** [comment]
Ran another rerun of downstream at head + flag flips [here](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/887). It's clean except for Tulsi which is broken at Bazel head, and Bazel's own presubmits are still running as I'm writing this. So I'm pretty comfortable with proceeding with these flips.

Note that I still have to update Bazels own unit tests for the flag flips. (This isn't reflected by the above presubmit since it modified the host blaze, not the blaze under test.)
