### ISSUE TITLE
Android: Build fails with local support libraries

### ISSUE THREAD

**Issue by menny** [bazelbuild/bazel#736]
Rather than using the built-in support libraries Bazel has (for example `@androidsdk//:appcompat_v4`) we're bringing in all the support libraries either from a hosted Artifactory server (an onsite Maven Central) or from the file-system. This ensures that we know which version of support libraries we are using, and it also fills in the missing "Design" library.

I noticed that although I depend on all the support libraries aars and jars, Bazel still fails to build.
I've built an example app the fails to build with Bazel: *https://github.com/menny/BazelPlayground/tree/missing-v4-deps*
my `app` target depends on all the required support libraries (see https://github.com/menny/BazelPlayground/blob/missing-v4-deps/app/BUILD), but still fails to compile:
```
app/src/main/java/net/evendanan/bazelplayground/ScrollingActivity.java:12: error: cannot access DrawerLayoutImpl
public class ScrollingActivity extends AppCompatActivity {
       ^
  class file for android.support.v4.widget.DrawerLayoutImpl not found
1 error
```
If I add `"@androidsdk//:appcompat_v4"` to the deps field, it builds fine. See branch: https://github.com/menny/BazelPlayground/tree/missing-v4-deps-with-hack and updated BUILD file: https://github.com/menny/BazelPlayground/blob/missing-v4-deps-with-hack/app/BUILD

I'm using Bazel 0.1.2.

**Comment by menny** [comment]
@cgrushko

**Comment by menny** [comment]
I have a newsgroup discussion here: https://groups.google.com/forum/#!topic/bazel-discuss/a0gMSAFi-LI

**Comment by lberki** [comment]
Yargh. I cloned your repo, realized that I can't reproduce the issue, then looked at the newsgroup thread above and realized that your repo has been updated to reflect what you found there. I should have looked a bit closer to avoid wasting some time :)

**Comment by menny** [comment]
Forgot about this. Sorry, I should have closed this.

**Comment by lberki** [comment]
Np. May this be the biggest misunderstanding in my life :)
