### ISSUE TITLE
Remove support for the Java singlejar implementation

### ISSUE THREAD

**Issue by cushon** [bazelbuild/bazel#7365]
Previously: #2241

The [Java implementation](https://github.com/bazelbuild/bazel/tree/master/src/java_tools/singlejar/java/com/google/devtools/build/singlejar) of singlejar has been replaced by a [faster c++ implementation](https://github.com/bazelbuild/bazel/blob/df036962c94eeac0ccb6d1359d6f9681195b45ef/src/tools/singlejar/singlejar_main.cc) everywhere except:

* RBE, because of issues with a dependency on c++ protos
* some places in the bootstrap build, where it might be tricky to use the native implementation but where other zip tools might be fine (it's not very performance-critical)
* I'm not sure the c++ implementation works on arm yet

We should use the c++ implementation everywhere, and stop supporting the legacy Java singlejar.

**Comment by lberki** [comment]
Would be indeed nice!
