### ISSUE TITLE
http_archive expects files in a downloaded tar.gz to be writeable

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#7369]
Bazel 0.23.0-rc1

Using pkg_tar with a TreeArtifact input was recently fixed:
https://github.com/bazelbuild/bazel/pull/6980#issuecomment-461195853

As I mention in that comment, the resulting tar has all entries in a `./` directory.
This means that a tar file produced by Bazel can't be later consumed as an http_archive by bazel.

(My use case is packaging up rules_nodejs so that downstream users don't download all our code and don't have to re-build tooling from source)

**Comment by beasleyr-vmw** [comment]
Related issue #7293 .

**Comment by alexeagle** [comment]
Thanks @beasleyr-vmw - I realized my issue is actually different.

Bazel is happy to install a package with `./` prefix in the tar.gz. It's a permissions error where it expects the files to be writable.

```
ERROR: error loading package '': Encountered error while reading extension file 'defs.bzl': no such package '@build_bazel_rules_nodejs//': Traceback (most recent call last):
	File "/usr/local/google/home/alexeagle/.cache/bazel/_bazel_alexeagle/859eca348cd807944dbd9d433d10a2e6/external/bazel_tools/tools/build_defs/repo/http.bzl", line 56
		workspace_and_buildfile(ctx)
	File "/usr/local/google/home/alexeagle/.cache/bazel/_bazel_alexeagle/859eca348cd807944dbd9d433d10a2e6/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 57, in workspace_and_buildfile
		ctx.file("WORKSPACE", "workspace(name = \"{...))
com.google.devtools.build.lib.vfs.FileAccessException: /usr/local/google/home/alexeagle/.cache/bazel/_bazel_alexeagle/859eca348cd807944dbd9d433d10a2e6/external/build_bazel_rules_nodejs/WORKSPACE (Permission denied)
```

It turns out I need the option `--mode='a+rw'` passed to `tar` to make a package that works with `http_archive`

**Comment by alexeagle** [comment]
Sigh, I'm even more wrong. It's just that `http_archive` expects packages are published without a `WORKSPACE` file which makes total sense, since no transitive info from such a file would be referenced anyway.
