### ISSUE TITLE
Windows, Bazel CI, Bazel@HEAD + downstream projects: broken for Bazel job

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#7372]
### Description of the problem / feature request:

Bazel@HEAD + Downstream Projects job on BuildKite is broken:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/799#d0a5c84f-4269-4596-9260-ec444d3eee19

The `//src/test/shell/bazel:bazel_rules_test` is timing out.

**Comment by laszlocsomor** [comment]
Last good CI run: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/790#0444d0fe-af58-472e-af56-432a4f9c018e
First bad CI run: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/791#8cc30c63-19b3-4aa6-841b-6fd01f2d0f82

This is the line timing out: https://github.com/bazelbuild/bazel/blob/8070555c99b2fe40e6ed3d7c5ca5301ad6f5fc3b/src/test/shell/bazel/bazel_rules_test.sh#L110

The correct syntax is:
```diff
-cat  | sed "s/{{WORKSPACE_NAME}}/$WORKSPACE_NAME/" > mypkg/echoer.sh << 'EOF'
+cat << 'EOF' | sed "s/{{WORKSPACE_NAME}}/$WORKSPACE_NAME/" > mypkg/echoer.sh
```

I'm investigating:
- how this works at all on Linux, when the bad syntax hangs on a Linux machine too
- which commit introduced the problem

**Comment by philwo** [comment]
Culprit is this change: 6da8982d997c119c548881aa6d7db736b9dd07d0 (according to Culprit Finder: https://buildkite.com/bazel/culprit-finder/builds/96#232ffafc-c676-43eb-979d-b0c26cd16b50)

**Comment by philwo** [comment]
I can confirm removing the `cat` fixes the test! :)
