### ISSUE TITLE
local_repository does not support repo_mapping

### ISSUE THREAD

**Issue by jblanchet** [bazelbuild/bazel#7378]
### Description of the problem / feature request:

Your documentation suggests using [repo_mapping ](https://docs.bazel.build/versions/master/external.html#shadowing-dependencies)to get around versioning issues.

[Local_repository](https://docs.bazel.build/versions/master/external.html#shadowing-dependencies) does not actually support repo_mapping though.

### What's the output of `bazel info release`?
release 0.21.0

**Comment by dslomov** [comment]
I believe it does, so probably documentation error. Have you tried?

**Comment by jblanchet** [comment]
After some digging, I discovered you need to use this flag: --experimental_enable_repo_mapping.

It would be great if that sort of thing was in the documentation.

**Comment by dslomov** [comment]
Ah sorry about that - this flag went away in Bazel 0.22 - it is no longer needed.

**Comment by ymwang1984** [comment]
Looks like the documents have not updated yet?
