### ISSUE TITLE
Use repo_mapping to fix circular project references

### ISSUE THREAD

**Issue by jblanchet** [bazelbuild/bazel#7379]
### Description of the problem / feature request:

Allow the repo_mapping argument to map to a local target in order to fix circular project references

### Feature requests: what underlying problem are you trying to solve with this feature?

Consider two projects:

      project1/
        WORKSPACE
        BUILD
          ...
      project2/
        WORKSPACE
        BUILD

Project1 has two libraries: Project1-A and Project1-B. 
Project2 has one library: Project2-C.

Project1-B depends upon Project1-A and upon Project2-C.
Project2-C depends upon Project1-A.

Project2-C needs to be buildable both on its own and as a dependency of Project1-B.
In Project2-C's deps argument, when building it on its own, I normally reference Project1-A via: @Project1-A.
When building Project1-B, Project2-C will complain that it can't find @Project1-A (as its not an external package in this context). So instead I need to reference Project1-A via: @//:Project1-A.

Obviously I cannot have both references in the Project2-C deps argument.

It would be great if, in the Project1 WORKSPACE, when I load Project2, I could use a repo_mapping to remap Project2's @Project1-A to @//:Project1-A.

**Comment by dslomov** [comment]
I do not think I quite follow - what you say should be possible with repo mappings. Can you write the example WORKSPACE files of Project1 and Project2?

**Comment by jblanchet** [comment]
Project1 WORKSPACE:
```
local_repository(
    name = "project2",
    path = "D:\\git\\project2",
    repo_mapping = {"@project1" : ":project1"}
)
```

Project1 BUILD file:
```
cc_library(
    name = "project1",
    srcs = glob(
        ["source/*.cpp"]
    ),
    hdrs = glob(
        ["include/**/*.h"]
    ),
    includes = [
        "include",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "test",    # project1-B
    srcs = glob(
        [
            "test/**/*.cpp", 
        ]
    ),
    deps = [
        ":project1",
        "@project2"
    ],
    visibility = ["//visibility:public"],
)
```

Project2 WORKSPACE:
```
local_repository(
    name = "project1",
    path = "D:\\git\\project1",
)
```

Project2 BUILD file:
```
cc_library(
    name = "project2",
    srcs = glob(
        ["source/*.cpp"]
    ),
    hdrs = glob(
        ["include/**/*.h"]
    ),
    includes = [
        "include",
    ],
    deps = [
        "@project1",
    ],
    visibility = ["//visibility:public"],
)
```

Building Project2 on its own, works fine. Building the test package within Project1, with the above setup will fail with this error about repo_mapping:

`ERROR: D:/git/project1/WORKSPACE:19:1: invalid repository name ':project1': workspace names must start with '@'`

**Comment by dslomov** [comment]
Ah I see.
You can just provide the name for your workspace using the `workspace` "function": https://docs.bazel.build/versions/master/skylark/lib/globals.html#workspace
E.g Project1's WORKSPACE:
```
workspace(name = "project1")
local_repository(
    name = "project2",
    path = "D:\\git\\project2",
    repo_mapping = {"@project1" : ":project1"}
)
```
I see that https://docs.bazel.build/versions/master/external.html doesn't actually use it, which is a mistake.

(Btw as the error message tells you, this line
```
    repo_mapping = {"@project1" : ":project1"}
```
should be
```
    repo_mapping = {"@project1" : "@project1"}
```
but you do not really need it in your case)

**Comment by dslomov** [comment]
> I see that https://docs.bazel.build/versions/master/external.html doesn't actually use it, which is a mistake.

Fix: https://github.com/bazelbuild/bazel/pull/7396

**Comment by jblanchet** [comment]
That did it, thanks!
