### ISSUE TITLE
DNS Resolution broken in sandboxes with `requires-network`

### ISSUE THREAD

**Issue by ahirreddy** [bazelbuild/bazel#738]
I am currently trying to download some javascript dependencies with a sandboxed gen-rule. I added the `requires-network` tag, but it appears that DNS resolution is broken. I confirmed that I could reach the localhost and that I could reach external hosts if I used the IP, but any attempts using host names fails.

This is reproducible with the following rule
```python
genrule(
    name = "network_test",
    srcs = glob(["some/input/files/*"]),
    cmd = """
        # I started a server on the host on port 8000
        curl localhost:8000

        # google.com ip
        curl 173.194.33.104

        # This will fail
        curl google.com
    """,
    outs = ["out"],
    tags = ["requires-network"]
)
```

The first 2 curl commands succeed, and the third fails with `curl: (6) Could not resolve host: google.com`

I'm on Ubuntu 15.10 with kernel 4.2.0-18.  This issue appeared both on bazel release 1.2 and master at the time of writing 9799246dc64429bc8f5b612c2596715180fe7592

**Comment by bsilver8192** [comment]
Is `/etc/resolv.conf` a symlink on your system? I've seen this issue before when the resolvconf package is installed, which makes it a symlink to `/etc/resolvconf/run/resolv.conf`. I think I fixed that issue at some point, but I don't remember how and I can't find the code...

**Comment by AustinSchuh** [comment]
I just ran into this today.

$ ls -lah /etc/resolv.conf /etc/resolvconf/run
lrwxrwxrwx 1 root root   31 Sep 17 15:09 /etc/resolv.conf -> /etc/resolvconf/run/resolv.conf
lrwxrwxrwx 1 root root   15 Sep 17 15:09 /etc/resolvconf/run -> /run/resolvconf

Maybe the intermediate symlink is failing to be resolved right?

Is someone working on this?  I'm going to start taking a look since I need this to make progress on my original goal.

**Comment by philwo** [comment]
@hermione521 has a fix for this, that's currently in code review.

The proposed thing to do is to simply add the following to LinuxSandboxedStrategy#mountUsualUnixDirs:
```java
Path resolv = fs.getPath("/etc/resolv.conf");
if (resolv.exists() && resolv.isSymbolicLink()) {
  Path resolvTarget = resolv.resolveSymbolicLinks();
  mounts.put(resolvTarget, resolvTarget);
}
```

Alternatively, we could treewalk through /etc completely and resolve + mount the targets of all symlinks found there, but this would be rather expensive, as we (currently) can't cache the results and have to do this each time we execute a spawn.

What do you think?

**Comment by AustinSchuh** [comment]
FYI @brian-peloton 

Without caching, there will be a performance hit for walking /etc/.  Sandbox bringup is already pretty expensive (It is a good chunk of my wall clock time in a build right now)  I'm fine with resolving /etc/resolv.conf specially for now.

I'm curious to see how many more things are symlinks in /etc/ which could cause a problem.  I'll go poke around and report back.  It may not be a big deal for anything else, or it could be a big deal.

**Comment by philwo** [comment]
@AustinSchuh I would love to improve the performance of the sandbox, so if you or @bsilver8192 have any ideas, I'm all ears. For standard Unix directories like /etc, /usr, ..., I wonder if we could treewalk and cache the results once per build. This should be pretty safe, because the contents shouldn't change during a build.

FYI, once done with my current project concerning persistent Java workers, I'll also focus again on the sandbox and do some profiling & optimizing to speed it up.

**Comment by AustinSchuh** [comment]
@philwo  Summary: resolv.conf, maybe /etc/network/run are broken.  You'll get most of the way there with just fixing /etc/resolv.conf.  The rest may be Debian Jessie specific.

I ran the following bash in a sandboxed test.

```
for f in $(find /etc/ -type l)
do
  if [[ ! -e ${f} ]]
  then
    ls -lah ${f}
  fi  
done
```

Result:
```
/etc/resolv.conf -> /etc/resolvconf/run/resolv.conf
/etc/opt/brother/scanner/brscan4/Brsane4.ini -> /opt/brother/scanner/brscan4/Brsane4.ini 
/etc/opt/brother/scanner/brscan4/brsanenetdevice4.cfg -> /opt/brother/scanner/brscan4/brsanenetdevice4.cfg
/etc/opt/brother/scanner/brscan4/models4 -> /opt/brother/scanner/brscan4/models4
/etc/opt/brother/Printers/MFC8910DW/inf/brMFC8910DWrc -> /opt/brother/Printers/MFC8910DW/inf/brMFC8910DWrc
/etc/cron.daily/google-chrome -> /opt/google/chrome/cron/google-chrome
/etc/alternatives/x-www-browser -> /usr/bin/google-chrome-stable
/etc/alternatives/google-chrome -> /usr/bin/google-chrome-stable
/etc/alternatives/gnome-www-browser -> /usr/bin/google-chrome-stable
/etc/resolvconf/run -> /run/resolvconf
/etc/qmail/qmail-smtpd/log/supervise -> /var/lib/supervise/qmail-smtpd.log
/etc/qmail/qmail-smtpd/supervise -> /var/lib/supervise/qmail-smtpd
/etc/qmail/qmail-verify/log/supervise -> /var/lib/supervise/qmail-verify.log
/etc/qmail/qmail-verify/supervise -> /var/lib/supervise/qmail-verify
/etc/qmail/qmail-send/log/supervise -> /var/lib/supervise/qmail-send.log
/etc/qmail/qmail-send/supervise -> /var/lib/supervise/qmail-send
/etc/network/run -> /run/network
/etc/sv/getty-5/supervise -> /var/run/sv.getty-5
/etc/sgml/catalog -> /var/lib/sgml-base/supercatalog
/etc/dictionaries-common/default.hash -> /usr/lib/ispell/american.hash
/etc/dictionaries-common/ispell-default -> /var/cache/dictionaries-common/ispell-default
```

Caching treewalk results would help some.  Maybe you could also create a namespace to clone from that already has the base OS stuff as well at that point in time.

The biggest slow down on my machine seems to be the kernel lock for creating sandboxes and/or mapping files into sandboxes.  I think it would be worth looking at what's going on there and maybe talking with a kernel guy or looking for ways to hit the lock less.
