### ISSUE TITLE
Option to leave stderr and stdout messages in the order they were generated

### ISSUE THREAD

**Issue by ghost** [bazelbuild/bazel#7388]
### Description of the feature request:

Right now, if a build fails bazel appears to dump first the stderr buffer, then all stdout buffer. This is frustrating in cases where a build step produces verbose and complex output on both buffers and users are used to seeing messages in the order they're produced.

Right now, my workaround is to run through a `genrule` just so I can add `2>&1` to the relevant command being run, thereby getting all messages in the right order. It would be much more stable and cleaner to have a bazel option to simply report them in the order they were written (as a normal tty would).

### Feature requests: what underlying problem are you trying to solve with this feature?

One example is where stdout is super verbose (and rightly so), the stderr messages get hidden above huge quantities of stdout with how bazel works right now.

### What operating system are you running Bazel on?

Ubuntu 18.04 / 16.04

### What's the output of `bazel info release`?

`release 0.22.0`

**Comment by jmmv** [comment]
Could you provide an example on when exactly this happens?

I've experienced this frustration often with other build systems, but I don't remember hitting it in Bazel.

**Comment by johnmarkwayve** [comment]
Here's a MWE:

- `WORKSPACE` empty
- `BUILD` containing
```
genrule(
  name = "test_genrule",
  tools = ["test_script.sh"],
  outs = ["test_out.txt"],
  cmd = """
$(location :test_script.sh) $(location :test_out.txt)
"""
)
```
- `test_script.sh` containing
```
echo "stdout 1"
>&2 echo "stderr 1"
echo "stdout 2"
>&2 echo "stderr 2"
touch $1
```

I'd expect output to be
```
stdout 1
stderr 1
stdout 2
stderr 2
```

but the output to terminal is
```
stderr 1
stderr 2
stdout 1
stdout 2
```

**Comment by jmmv** [comment]
But the output to the terminal running which Bazel command?

**Comment by johnmarkwayve** [comment]
@jmmv `bazel clean && bazel build :test_genrule`

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
