### ISSUE TITLE
Bazel 0.22 prints repository rule modified arguments on every run

### ISSUE THREAD

**Issue by jgavris** [bazelbuild/bazel#7389]
### Description of the problem / feature request:

After https://github.com/bazelbuild/bazel/pull/6468, which changed the log level from info to debug, the repository rule results are printed on every build command, even when they have not changed. For workspaces with many repository rules, this adds a lot of log spam to the day-to-day build logs.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build a target in a workspace with a few repository rules on bazel 0.22. Observe the following output:

```shell
λ bazel run //host/Applications/ImagingSandbox --config=asan
INFO: Invocation ID: 89861536-76f3-4f2d-b6b8-911ad430de41
DEBUG: Rule 'io_bazel_rules_go' modified arguments {"shallow_since": "1543610332 -0500"}
DEBUG: Rule 'com_github_bazelbuild_buildtools' modified arguments {"sha256": "30c8e027d0ed7843651fbe2dbb6338171c963ba1184a7bce802ae4a30e223fd4"}
DEBUG: Rule 'io_bazel_rules_kotlin' modified arguments {"shallow_since": "1542356984 +1100"}
DEBUG: Rule 'robolectric' modified arguments {"shallow_since": "1521227318 -0700"}
DEBUG: Rule 'gmaven_rules' modified arguments {"sha256": "51cdfdd8a73f6a4cf52da18b15c7e51f8dee5a5c101239db85655baa0e1195ab"}
INFO: Analysed target //host/Applications/ImagingSandbox:ImagingSandbox (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //host/Applications/ImagingSandbox:ImagingSandbox up-to-date:
  bazel-bin/host/Applications/ImagingSandbox/ImagingSandbox
INFO: Elapsed time: 1.018s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

### What operating system are you running Bazel on?

macOS 10.14.3

### What's the output of `bazel info release`?

release 0.22.0

**Comment by aehlig** [comment]
> After #6468, which changed the log level from info to debug [...]

Note that `debug` is a lower log level than `info`, i.e., whenever `debug` messages are printed, `info` messages are printed as well.

>  the repository rule results are printed on every build command, even when they have not changed. 

That I cannot reproduce (see example below). Debug information from the repository rules is only printed if it is advisable to change the definition of the repository rule (either directly in the `WORKSPACE` file, or by using a resolved file); will change the message to make this more obvious. In your example, bazel points out the following.

- A file is downloaded without a checksum being specified. Downloading files without verifying integrity can be a security issue; providing a hash also improves caching.

- A `git_repository` is used for a specific commit, but no reference date is given. Specifying a reference date allows users of the same `WORKSPACE` file to clone in a shallow way.

And here the example that I believe shows that the debug messages do not occur on a clean `WORKSPACE` file.

```
$ cat WORKSPACE
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name =  "ext",
  strip_prefix = "ext",
  urls = ["file:///memfs/tmp/ext.tar"],
  sha256 = "0761dc172c9704c2b1c0bee3cb8346c2d37cb147e62b63274f0d4fbb2b0e226f",
)
$ bazel build @ext//...
Starting local Bazel server and connecting to it...
(09:04:38) INFO: Current date is 2019-02-11
(09:04:38) INFO: Analysed target @ext//:foo (3 packages loaded, 18 targets configured).
(09:04:38) INFO: Found 1 target...
Target @ext//:foo up-to-date:
  /crypto/general/aehlig/.cache/bazel/_bazel_aehlig/c5b124fa446373c8c02df387509b8c3c/execroot/__main__/bazel-out/freebsd-fastbuild/genfiles/external/ext/foo.txt
(09:04:38) INFO: Elapsed time: 1.772s, Critical Path: 0.11s
(09:04:38) INFO: 1 process: 1 processwrapper-sandbox.
(09:04:38) INFO: Build completed successfully, 2 total actions
$ # remove checksum
$ ed WORKSPACE
246
/sha256
  sha256 = "0761dc172c9704c2b1c0bee3cb8346c2d37cb147e62b63274f0d4fbb2b0e226f",
d
w
167
q
$ !? build
bazel build @ext//...
(09:05:04) INFO: Current date is 2019-02-11
(09:05:04) INFO: SHA256 (file:/memfs/tmp/ext.tar) = 0761dc172c9704c2b1c0bee3cb8346c2d37cb147e62b63274f0d4fbb2b0e226f
(09:05:04) DEBUG: Rule 'ext' modified arguments {"sha256": "0761dc172c9704c2b1c0bee3cb8346c2d37cb147e62b63274f0d4fbb2b0e226f"}
(09:05:04) INFO: Analysed target @ext//:foo (1 packages loaded, 1 target configured).
(09:05:04) INFO: Found 1 target...
Target @ext//:foo up-to-date:
  /crypto/general/aehlig/.cache/bazel/_bazel_aehlig/c5b124fa446373c8c02df387509b8c3c/execroot/__main__/bazel-out/freebsd-fastbuild/genfiles/external/ext/foo.txt
(09:05:04) INFO: Elapsed time: 0.217s, Critical Path: 0.00s
(09:05:04) INFO: 0 processes.
(09:05:04) INFO: Build completed successfully, 1 total action
$
```

**Comment by aehlig** [comment]
> Note that `debug` is a lower log level than `info`, i.e., whenever `debug` messages are printed, `info` messages are printed as well.

Despite this being true in the order of `EventKind` and in general, it seems not that easy to disable debug messages. That seems a different issue.

**Comment by dslomov** [comment]
Let's rework the messages here to explain better what is meant: the suggestion to users abot how to make their repo rules more reproducible.

**Comment by jgavris** [comment]
Ah, thanks for pointing out that I have not fully specified my repository rules, I will add checksums / shallow dates. I'm just surprised this was not being printed out on every build in 0.21. Was there another change recently?

**Comment by aehlig** [comment]
>  I'm just surprised this was not being printed out on every build in 0.21. Was there another change recently?

94e1dcc99373f24d042624d72800223c03e98825 added the ability of `http_archive` rules to report the checksum of the file actually downloaded, so 0.22 is the first bazel release to actually indicate missing checksums for `http_archives`; the recommendation of adding checksum for security and caching reasons is much older, however.

**Comment by dslomov** [comment]
Great to see the fix in a117ddf! It would be even better if we print the attributes to add/modify not in JSON-like format (`{ "attr1" : "value1", "attr2" : 2 }`) but in the format directly copy-pastable to WORKSPACE file:
```
attr1 = "value1", 
attr2 = 2
```

**Comment by keith** [comment]
So I see that the fix re-words this log statement, but what's the recommendation to eliminate them entirely? Should we be submitting patches upstream to lock the versions and validate their shas? For example if you include buildifier inside bazel, these repositories print this log https://github.com/bazelbuild/rules_go/blob/346de0cb6de6af7e71b746070aea9e0b469d509d/go/private/repositories.bzl#L38-L65

I've tried using a resolved file from master, but I'm seeing other issues with that, is that an alternative as well?

**Comment by keith** [comment]
Any thoughts on this ^ @aehlig ?
