### ISSUE TITLE
Presence of cxx_extractor causes cgo to build for various platforms.

### ISSUE THREAD

**Issue by robinp** [bazelbuild/bazel#7391]
### Description of the problem

See https://github.com/kythe/kythe/issues/3469 - if I run a `cgo` compilation without the presence of the `cxx extractor`, all is fine. When the `--experimental_action_listener=@io_kythe//kythe/extractors:extract_kzip_cxx` is passed to bazel, cgo starts trying to build for various platforms (`arm`, `darwin` etc). Which will fail, since the `CC` used is not a cross-compiler (nor do I desire it to be).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

Linux Arch + Nixpkgs

### What's the output of `bazel info release`?

release 0.21.0- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Nix-modded Bazel, so far, which I understand is not a canonical setup, but I don't suspect this playing a major role in the bug.

Can you point me how to find out why a certain platform build gets triggered? Any other insights?

Thank you,
Robin

**Comment by scentini** [comment]
cc/@jayconrod

Can you please provide a repro?

**Comment by robinp** [comment]
@scentini @jayconrod as for repro:

Check out Google Kythe as described in https://kythe.io/getting-started/, then

```
bazel build -s @go_levigo//... --experimental_action_listener=@io_kythe//kythe/extractors:extract_kzip_cxx
```
This will fail due to trying to build levigo (which uses cgo) for various platforms. If you remove the action listener, it will just build for the target platform.

**Comment by katre** [comment]
Closed for lack of activity. Please ping the reviewers to reopen if this is still a problem.
