### ISSUE TITLE
Windows, testing: --test_output=streamed is broken

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#7392]
### Description of the problem / feature request:

Bazel doesn't stream the test's output, just prints it as if it were `--test_output=all`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`bazel test --test_output=streamed //some:test`

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

0.22.0

**Comment by laszlocsomor** [comment]
Found the culprit.

[When `--test_strategy=streamed`](https://github.com/bazelbuild/bazel/blob/c9ae9617f63f738585946e91228fe520ce7b90e3/src/main/java/com/google/devtools/build/lib/exec/StandaloneTestStrategy.java#L299), the [StandaloneTestStrategy creates](https://github.com/bazelbuild/bazel/blob/c9ae9617f63f738585946e91228fe520ce7b90e3/src/main/java/com/google/devtools/build/lib/exec/StandaloneTestStrategy.java#L301) a StreamedTestOutput object, that [has a FileWatcher](https://github.com/bazelbuild/bazel/blob/c9ae9617f63f738585946e91228fe520ce7b90e3/src/main/java/com/google/devtools/build/lib/exec/TestStrategy.java#L492). The FileWatcher is a Thread that [pumps the test's output in a loop if the output exists](https://github.com/bazelbuild/bazel/blob/c9ae9617f63f738585946e91228fe520ce7b90e3/src/main/java/com/google/devtools/build/lib/util/io/FileWatcher.java#L80). To check whether the file exists, on Windows we use [JavaIoFileSystem.exists](https://github.com/bazelbuild/bazel/blob/c9ae9617f63f738585946e91228fe520ce7b90e3/src/main/java/com/google/devtools/build/lib/vfs/JavaIoFileSystem.java#L122), which uses java.nio.file.Files.exists.

Unfortunately the result of Files.exists is unreliable: if the result is false, one should also check Files.notExist, because the result may have been false due to a file sharing error:

> Note that this method is not the complement of the `exists` method. Where it is not possible to determine if a file exists or not then both methods return `false`.

(from https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#notExists)

JavaIoFileSystem does not check Files.notExist, and indeed JavaIoFileSystem.exists keeps returning false even though the test's output exists.

And the reason is that we open the tests's [stdout](https://github.com/bazelbuild/bazel/blob/c9ae9617f63f738585946e91228fe520ce7b90e3/src/main/native/windows/processes-jni.cc#L231) and [stderr](https://github.com/bazelbuild/bazel/blob/c9ae9617f63f738585946e91228fe520ce7b90e3/src/main/native/windows/processes-jni.cc#L283) without any sharing.

I'll fix all CreateFile[AW] calls to open files with at least read-sharing. That fixes this bug.

**Comment by jmmv** [comment]
I added a new test in 397f172139169410abf672c6ff95dfb9e2f56fe6 which uses `--test_output=streamed` and when it runs on Windows I don't see any of its output.

So I have reasons to believe that this is broken again, and it wouldn't surprise me because the fix seems very subtle and there are no tests for this feature. Need to confirm that this works and, at a very minimum, add an integration test for this behavior.

(Note that we *do* have tests that use `--test_output=streamed`, but they do not consume the test's output as it is produced. They only look at the output post-build, so it's possible that `streamed` is only dumping the output at the end of the test on Windows and not during its execution.)

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
