### ISSUE TITLE
repository_ctx: string; or Label; or path

### ISSUE THREAD

**Issue by Profpatsch** [bazelbuild/bazel#7394]
https://github.com/bazelbuild/bazel/commit/44847d8442d5c93c2ffbf76e11fd76e9a1567ff3 introduced the `getPath` method, effectively changing the input type of most paths in `repository_ctx` subroutines to `string; or Label; or path`.

Documentation was non-existing at the time, so the documentation that was added later does not give many hints as to what the different input types mean.

The interface should be simplified, by changing all these attributes back to only accept `path`, and requiring the user to explicitely pass `Label`s and `string`s through `repository_ctx.path()`.

In the meantime, the documentation should be updated to clearly describe the interface. This should be done in one place, and all the documentation of all attributes that use `getPath` should point to that.  Here’s a first draft of the general note:

```
Note: Every attribute that expects `string; or Label; or path` treats the different types in the following way:
- `path`: references a file known to bazel
- `Label`: treated as a path; you can use the `Label()` constructor to reference a file by target name
- `string`: an arbitrary path to a file in the filesystem. If it denotes an absolute path, it will be used as-is, if it denotes a relative path, it is used relative to the `outputDirectory` (TODO: what is the outputDirectory?!)
```

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
