### ISSUE TITLE
Rules for building distribution archives

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel#74]
Add rules for building distribution archives, similar to `make dist`, `mvn package`, and the [Gradle Distribution Plugin](https://gradle.org/docs/current/userguide/distribution_plugin.html).

It might be good to use a `bazel dist //package:dist_target` command similar to the way we invoke test targets via `bazel test //package:test_target`.

**Comment by laszlocsomor** [comment]
Would build rules creating `rpm` or `deb` files solve that?

**Comment by davidzchen** [comment]
Having rules that build packages such as RPMs or deb packages would be awesome.

We would also want rules for building archives such as .zip and .tar.gz archives, which is that `make dist`, `mvn package`, and Gradle Distribution do.

**Comment by talios** [comment]
@davidzchen Would you want to use native rpm-tools or something else - at $work we use http://redline-rpm.org which is a pure Java RPM generation library which makes building RPMs a breeze on multiple platforms.

**Comment by laszlocsomor** [comment]
@davidzchen Bazel has no built-in support for that (yet?), but it sounds like something some `genrule`s or a [Skylark rule](http://bazel.io/docs/skylark/rules.html) could accomplish.

**Comment by davidzchen** [comment]
@talios Thanks for the suggestion! Redline looks promising for implementing rules for building RPMs.

To clarify, what I meant by building distribution archives was building tarballs and .zip archives, similar to the `dist` targets of the other build tools I mentioned.

@laszlocsomor I agree that this can be implemented using Skylark and genrule. However, I think semantically it might make more sense to invoke distribution rules with a different subcommand such as `bazel dist` similar to how `bazel test` is used to invoke test targets.

**Comment by hanwen** [comment]
Since a RPM and DEBs are normal artifiacts (which can be cached normally), I don't think we need a separate command: bazel build has alll the functionality we need assuming somebody writes a rule.

traditionally "make dist" is to make a source tarball of the project, and is probably easier handled by extracting a tarball from the version control system. Handling it in Bazel is annoying, because you'd have to declare lists of inputs to distribute in each BUILD file separately.

**Comment by damienmg** [comment]
Closing now pkg_deb has landed.
