### ISSUE TITLE
remote_http_cache doesn't work

### ISSUE THREAD

**Issue by zhangningdlut** [bazelbuild/bazel#7400]
I want to use the remote_http_cache flag to build, but it doesn't work. 
```
bazel build --remote_http_cache=http://remote_cache xxx
```
The remote server  doesn't receive the request, and the build server doesn't send the request neither.

How can use it？

**Comment by buchgr** [comment]
I think we'll need more information than this. Do you get any error messages?

**Comment by katre** [comment]
Closed for lack of activity. Please ping the reviewers to reopen if this is still a problem.
