### ISSUE TITLE
Toolchain types should be aliasable

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#7404]
Suppose you define a `toolchain_type` with label `"//pkg:tt"`, and an `alias` that points to it named `"//tt2"`. Then you should be able to use either `//pkg:tt` and `//pkg:tt2`interchangeably. This is important for smooth migration of `toolchain_type` definitions from one name/package/repository to another.

Currently this works for a `toolchain` target's `toolchain_type` attribute: When you specify `//pkg:tt2`, it retrieves the original `ToolchainTypeInfo` provider from the `alias` target and sees the original `//pkg:tt` label.

It does not work for a rule that declares a required toolchain type of `//pkg:tt2`. The problem can be traced back to the fact that [ToolchainResolutionFunction](https://github.com/bazelbuild/bazel/blob/fcf46b2f781cecd4c2003633fe2de745c0fa1044/src/main/java/com/google/devtools/build/lib/skyframe/ToolchainResolutionFunction.java#L132) directly compares the label of the requested toolchain type, when it should instead resolve this label to a configured target and retrieve the label in the `ToolchainTypeInfo` provider.

**Comment by brandjon** [comment]
Note that once this is fixed, it would still not be expected that you can require a toolchain type under one name but retrieve it from `ctx.toolchains` under another.

**Comment by katre** [comment]
This seems related to the concerns @aragos has about constraint values proliferating.

**Comment by brandjon** [comment]
How so? I did a cursory check, and aliasing appears to be fully transparent to constraint values and constraint settings.

Or are you referring to the problem of explicitly merging two distinct constraint values that are not declared as aliases?

**Comment by katre** [comment]
I meant the latter, which won't directly involve alias rules, but which is conceptually related.
