### ISSUE TITLE
incompatible_dont_enable_host_nonhost_crosstool_features: Do not automatically enable "host" and "nonhost" crosstool features

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#7407]
**Flag:** `--incompatible_dont_enable_host_nonhost_crosstool_features`
**Available since:** 0.24 (March 2019 release)
**Will be flipped in:** 0.25 (April 2019 release)
**Tracking issue:** #6516

# Motivation

With the move of C++ rules to use platforms/toolchains (tracked in #6516), we are removing host specific logic. Platforms don't guarantee existence of separate host toolchain, in which case it's not clear which feature to enable, and it can happen that there will be multiple execution platforms, which currently don't have a way to enable a specific feature. My research shows that these Bazel features are actually mostly unused, so instead of coming up with non-trivial solution, we will remove them.

# Migration

With the flag flipped, `host` and `nonhost` features will never be enabled automatically. There are no generally useful migration notes.

**Comment by hlopko** [comment]
CC @katre

**Comment by dkelmer** [comment]
Seems like the flag wasn't flipped. Changing breaking-change label to 0.26
