### ISSUE TITLE
Feature: multi file query

### ISSUE THREAD

**Issue by zegl** [bazelbuild/bazel#7408]
### Description of the problem / feature request:

`bazel query path/to/file.xyz` can be used to find the "package" that contains the file specified. Currently there is no way to perform this action for many files at a time, and one instead has to execute `bazel query` in a loop with adds quite a lot of overhead.

I'd like to have the ability to run `bazel query file/a.txt file/b.txt` (or similar), and get the same result as `bazel query file/a.txt` + `bazel query file/b.txt` would.

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm trying to utilize the power of Bazel to find out which services that has changed between two revisions from our VCS. Currently I can do that by executing `bazel query` once for each file that has changed, and then run a `bazel query "kind(container_image, rdeps(//..., set(//packageA:a.txt //packageB:b.txt)))"`, where the input to `set()` is determined by the result of the first `bazel query` executions.

**Comment by benjaminp** [comment]
You could do `bazel query 'file/a + file/b'`.

Admittedly, I think the normal way to determine a file's package is to simply walk up the path until you find a `BUILD` file.

**Comment by zegl** [comment]
Thanks for the answer @benjaminp, the `+` notation does exactly what I needed, it was just a bit hard to find. 😃
