### ISSUE TITLE
Support restricting extensions for attr.output()

### ISSUE THREAD

**Issue by jmillikin** [bazelbuild/bazel#7409]
### Description of the problem / feature request:

`attr.label()` can set `allow_single_file=[".foo", ".bar"]` to restrict the extensions of allowed files. It would be nice if `attr.output()` had similar functionality.

### Feature requests: what underlying problem are you trying to solve with this feature?

Some tools change their behavior when the output file has a different extension, for example using different compression algorithms for `.gz` or `.xz`. I want to encode the set of supported extensions into the rule and have Bazel enforce this, instead of merely documenting and then having to manually `fail()` for unexpected extensions.

**Comment by laurentlb** [comment]
Indeed, this looks like a very reasonable feature request.
