### ISSUE TITLE
bazel 0.1.2 version update

### ISSUE THREAD

**Issue by f1yinthesky** [bazelbuild/bazel#741]
I have download the 0.1.2 sh script and ran the scrip with sudo. But when I type bazel version, it is still 0.1.1, I have restarted the machine but didn't fixed it. Could someone give a clue here?

**Comment by kchodorow** [comment]
Could you paste the installer command you ran and the output it gave, plus what `which bazel` returns?

**Comment by philwo** [comment]
Closing because we didn't hear back for a week, but feel free to re-open if it still doesn't work :)

**Comment by damienmg** [comment]
(note for future reference: this is probably due to the ~/bin directory being first in the PATH, /usr/local/bin being after, removing ~/bin/bazel should do the trick)
