### ISSUE TITLE
Test Setup Script incompatible with Bash 5

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#7410]
This was reported to me by a fellow Googler.

### Description of the problem / feature request:

When running on Debian Buster with Bash 5, the test-setup script always generates a test.xml with an error about SIGCHLD:
```
  <testsuite name="simple_script_test" tests="1" failures="0" errors="1">
    <testcase name="simple_script_test" status="run" duration="0" time="0"><error message="Terminated by signal SIGCHLD"></error></testcase>
    <system-out><![CDATA[]]></system-out>
  </testsuite>
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
WORKSPACE:
-----
workspace(name="sh_test_recreate")
-----
BUILD:
-----
sh_test(
  name = "simple_script_test",
  srcs = ["simple_script.sh"],
)
-----
simple_script.sh:
-----
#!/bin/bash

exit 0
-----
```

### What operating system are you running Bazel on?

Debian Buster

### What's the output of `bazel info release`?

0.22.0

###  Have you found anything relevant by searching the web?

No.

**Comment by ulfjack** [comment]
My hypothesis is that this is fixed as of 6da8982d997c119c548881aa6d7db736b9dd07d0, which is included in 0.23.0 rc1.

I wonder if this is critical enough to warrant patch releases for earlier releases. That would be possible, but we'd have to come up with a patch - it is _not_ directly possible to back-port 6da8982d997c119c548881aa6d7db736b9dd07d0 as there were a number of relevant changes before the flag flip.

**Comment by KeithMoyer** [comment]
I can confirm that is fixed in a fresh-built 0.23.0rc1.

**Comment by KeithMoyer** [comment]
I was also able to fix this in 0.22.0 by simply adding a

[ "${signal}" = "SIGCHLD" ] && continue

to the trapping loop in test-setup.sh. Would that be acceptable for patching earlier releases?

**Comment by ulfjack** [comment]
Yes, that sounds good. Do you want to set a PR?

**Comment by KeithMoyer** [comment]
Created PR #7441 based on the release-deb028e branch (which, as near as I could tell, is where a 0.22.1 release would be derived). Tests appear to have all passed.

**Comment by ulfjack** [comment]
I don't have a good understanding of how we decide to do patch releases, or who would be responsible for that. @meisterT, any idea?

**Comment by meisterT** [comment]
https://bazel.build/support.html#policy has a short section about critical issues and patch releases.

@aehlig was the release manager for 0.22, so I'll assign this to him.

**Comment by aehlig** [comment]
> @aehlig was the release manager for 0.22, so I'll assign this to him.

It probably is a good idea to do a patch release, even though Debian Buster isn't even in full freeze yet, so technically not a supported platform. But if we do so, we should also start adding Debian Buster to our CI system.

Another problem is that release pipleline is based on the idea of "baseline plus cherry-picks from master", so I have to find out what the easiest way is to generate such a patch release.

**Comment by aehlig** [comment]
On the other hand, 0.23 will probably be released tomorrow and a patch release takes at least (by policy) two days to release, so I wonder if it is worth the effort.

**Comment by ulfjack** [comment]
We can check in a patch at head, and then cherrypick that, although I'm not 100% sure it'll apply cleanly. Let me take a look.

**Comment by ulfjack** [comment]
Nope, it doesn't apply cleanly.

**Comment by aehlig** [comment]
>  But if we do so, we should also start adding Debian Buster to our CI system.

I talked to our CI team. Regular testing for Debian Buster will come eventually, but not before the 0.23.0 release. So I don't think it warrents a 0.22 patch release.

Over to to @philwo who handles the 0.23 release (#6495) to decide if any action is needed there.

**Comment by philwo** [comment]
I'm on vacation, please don't assign time-critical issues to me.

Reassigning to Laurent who is helping with the 0.23.0 release.

**Comment by ulfjack** [comment]
This is all fixed as of d2fd660917fe204ec64c96fea1f1003d6ece7c7e, and we're not planning to cherry-pick into older releases. @philwo, this was assigned to you because you were handling the release, and the fix was cherry-picked by @laurentlb who took over from you, so everything went just fine?

**Comment by ulfjack** [comment]
I guess don't do releases if you're on vacation? :-p

**Comment by philwo** [comment]
@ulfjack Mhm, I don't see a problem with handling most of the work doing a release (which would have gone out before my vacation as planned, if it weren't again for "oh by the way, I just tested it and it's broken for me" feedback on the day before the release would have happened) and then handing it off to someone to do the last cherry-picks. :)

However, I don't see the reason why @aehlig assigned me this issue while I was already on vacation (and marked as OOO in our internal calendar and the equivalent "Busy" here on GitHub, too), though. It would have been better to ask "Who is handling the release now that philwo is on vacation?" and assigning it to that person, rather than counting on me noticing this and reassigning it.

**Comment by ulfjack** [comment]
Huh, cool! I didn't even know that was possible.
