### ISSUE TITLE
Coverage failure with GCC 7 and above

### ISSUE THREAD

**Issue by felixguo** [bazelbuild/bazel#7417]
It looks like this GCOV bug is not fixed.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84879

```
$ echo "int main() { return 0; }" > t.c
$ gcc t.c -o t --coverage
$ ./t
$ gcov -iab t.c
File 't.c'
Lines executed:100.00% of 1
No branches
No calls
Creating 't.c.gcov'
Segmentation fault (core dumped)
```

Tested with two versions of gcc including 7.3.1, 8.2.1, and got the same result.
The key problem here is that using both -i and -b will trigger that segment fault.
bazel 0.21 introduced gcov based coverage reporting

```
"${GCOV}" -i -b -o "$(dirname ${gcda})" "${gcda}" &> "$gcov_log"
```
https://github.com/bazelbuild/bazel/blob/master/tools/test/collect_cc_coverage.sh#L149

Can we temporarily remove -b so that we can generate coverage report for higher gcc version?

**Comment by iirina** [comment]
Thanks for reporting this. Since gcc doesn't plan to fix this we can remove branch coverage information for the time being. I'll send a PR.

**Comment by felixguo** [comment]
Thanks! Really appreciate it.
