### ISSUE TITLE
proto_lang_toolchain - command line multiple args

### ISSUE THREAD

**Issue by zacharya19** [bazelbuild/bazel#7422]
### Description of the problem / feature request:
When creating new proto_lang_toolchain with custom plugin in the command line, it's not possible to pass more than one args.
If for example this is my toolchain:
```
proto_lang_toolchain(
    name = "java_toolchain",
    command_line = "--plugin=protoc-gen-custom=/home/zacharya/pb_plugin --java_out=$(OUT)",
    runtime = "@com_google_protobuf//:protobuf_java",
    visibility = ["//visibility:public"],
)
```
When running build for proto java lib I'm getting `Missing output directives.`.
After checking the command line using --sandbox_debug flag, look like `proto_lang_toolchain` is passing the entire string as one arg, so only `--plugin` is passed with the value `protoc-gen-custom=/home/zacharya/pb_plugin --java_out=$(OUT)`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
```
proto_library(
    name = "proto",
    srcs = glob(["*.proto"]),
    deps = [
        "@com_google_protobuf//:descriptor_proto"
    ],
    visibility = ["//visibility:public"]
)

proto_lang_toolchain(
    name = "java_toolchain",
    command_line = "--plugin=protoc-gen-custom=/home/zacharya/pb_plugin;--java_out=$(OUT)",
    runtime = "@com_google_protobuf//:protobuf_java",
    visibility = ["//visibility:public"],
)

java_proto_library(
    name = "java_proto",
    deps = [":proto"],
)
```

And running `bazel build //:java_proto --proto_toolchain_for_java="//:java_toolchain"`

### What operating system are you running Bazel on?
Ubuntu 18.04.

### What's the output of `bazel info release`?
release 0.19.1

**Comment by vsrikrishna32** [comment]
Is this resolved? Or is there a work-around for this?
