### ISSUE TITLE
Website rss feed is malformed.

### ISSUE THREAD

**Issue by carstn** [bazelbuild/bazel#743]
The bazel.io blog feed is malformed: http://bazel.io/blog/feed.xml

I think the issue is that the `<description>` element of each `<item>` must contain entity-encoded HTML. Currently, the content of each item's `<description>` element is decoded HTML. 

For example, 
```xml
<item>
  <descripion><p>Lorem ipsum…</p>
  <img src="/bazel.png"></description>
  …
</item>
```
should be
```xml
<item>
  <descripion>&#x3C;p&#x3E;…&#x3C;/p&#x3E;
  &#x3C;img src=&#x22;/bazel.png&#x22;&#x3E;</description>
  …
</item>
```
To fix it, the page generator could just put plain text in the RSS feed items' descriptions. Refer to [the RSS 2.0 spec](http://cyber.law.harvard.edu/rss/rss.html#hrelementsOfLtitemgt) or an [example](http://cyber.law.harvard.edu/rss/encodingDescriptions.html).

**Comment by carstn** [comment]
I think you can just edit the gh-pages [blog/feed.xml](https://github.com/bazelbuild/bazel/blob/gh-pages/blog/feed.xml) file:
`<description>{{ post.content | xml_escape }}</description>`

**Comment by kchodorow** [comment]
Thanks, will do.
