### ISSUE TITLE
Reuse outputs which are not expected to change

### ISSUE THREAD

**Issue by mgechev** [bazelbuild/bazel#7431]
### Description of the problem / feature request:

Reuse output files from the previous run of Bazel, which are not expected to change.

### Feature requests: what underlying problem are you trying to solve with this feature?

While comparing the performance of the TypeScript compiler in watch mode and `ibazel` with [`rules_typescript`](https://github.com/bazelbuild/rules_typescript) with a single package, we found out that `tsc -w` is orders of magnitude faster. In practice in both experiments we run a single instance of the TypeScript compiler, watch the file system, and recompile the program on change.

After a more careful look, we noticed that in `tsc-wrapped` there's a file and a program cache, which do not require the entire package to be parsed on change. About 2/3 of the execution time, however, was spent in emitting JavaScript for TypeScript files which haven't changed. In some cases, the update of a file may impact other TypeScript files transitively (for example, updating an `enum` definition to `const enum`), but still, a large portion of the compilation was unnecessary.

Ideally, we'd want to reemit only the files which are directly or transitively impacted by the change and reuse the other outputs.

The purpose of this issue is to start a discussion whether this is feasible given the Bazel's design, instead of a proposal of a feature request.

// cc @alexeagle @dslomov @mprobst @rkirov

**Comment by dslomov** [comment]
cc @meteorcloudy since this comes out of Angular

**Comment by janakdr** [comment]
Bazel normally does not recompile files that haven't changed. Could you give examples of an unchanged file that caused downstream work to be done. It sounds like you might want some kind of heuristic, which Bazel is not likely to add, though.
