### ISSUE TITLE
`.bazelignore` does not actually ignore directories in the file

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#7433]
It makes Bazel not recognize packages under the specified directories, but does allow label references under them and allows globs to descend under them, too. 

It's even weirder because even though packages are not recognized under such prefixes, `BUILD` files there do stop glob evaluations.

Reproduction:

```
touch WORKSPACE
echo 'filegroup(name="f", srcs=glob(["**"]))' > BUILD
echo 'ignored' > .bazelignore
mkdir -p ignored/pkg
touch ignored/pkg/{BUILD,a}
touch ignored/file
bazel query //...:all-targets
```

The result will be the following set of labels:

```
//:f
//:ignored/file
//:WORKSPACE
//:BUILD
//:.bazelignore
```

**Comment by clintharrison** [comment]
> even though packages are not recognized under such prefixes, `BUILD` files there do stop glob evaluations

@lberki this is not consistently true. I'm able to reproduce the output you have, _but_ if you "change" the BUILD file after that, you'll see a different result:

```
$ bazel query //...:all-targets
//:f
//:ignored/file
//:WORKSPACE
//:BUILD
//:.bazelignore

$ touch BUILD

$ bazel query //...:all-targets
//:f
//:ignored/pkg/a
//:ignored/pkg/BUILD
//:ignored/file
//:WORKSPACE
//:BUILD
//:.bazelignore
```

**Comment by lberki** [comment]
Oof.

**Comment by lberki** [comment]
Better late than never.

@clintharrison , your finding that this can be broken in two *different* ways was very interesting and it turned out that it has a very good reason (we are running Skyframe-based and legacy globbing in parallel, and they both were buggy in different ways)
