### ISSUE TITLE
 bazel build tensorflow failure for help

### ISSUE THREAD

**Issue by fangliangs** [bazelbuild/bazel#7436]
fang@fang-desktop:~/tensorflow/tensorflow$ bazel build tensorflow/python/tools:freeze_graph
Starting local Bazel server and connecting to it...
.
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:101:9: //external:bazel_gpg: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:110:9: //external:docker_gpg: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:119:9: //external:gcloud_gpg: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:128:9: //external:launchpad_openjdk_gpg: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:138:9: //external:golang_release: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:147:9: //external:debian8_clang_release: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:155:9: //external:ubuntu16_04_clang_release: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:164:9: //external:debian8_libcxx_release: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:172:9: //external:ubuntu16_04_libcxx_release: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0141_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0150_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0152_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0161_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0171_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0172_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0180_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0181_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0190_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0192_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0200_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:184:13: //external:bazel_0210_installer: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:196:9: //external:azul_open_jdk: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: /home/fang/.cache/bazel/_bazel_fang/e5d457e05168b61f089c543aed37d39a/external/bazel_toolchains/repositories/repositories.bzl:204:9: //external:azul_open_jdk_src: no such attribute 'downloaded_file_path' in 'http_file' rule
ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.915s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by jin** [comment]
Hi, please open Tensorflow build issues on the Tensorflow GitHub repositories. Thanks!
