### ISSUE TITLE
Tutorial Build Fails in Xcode

### ISSUE THREAD

**Issue by spierce7** [bazelbuild/bazel#744]
I'm following the instructions in [the iOS build tutorial](http://bazel.io/docs/tutorial/ios-app.html). I've cloned the final tutorial from the github repo. I'm getting the following error while trying build from xcode. It looks like several files aren't being generated.

```
error: could not read data from '/.../examples/tutorial/bazel-out/local_darwin-fastbuild/bin/ios-app/ios-app-MergedInfo.plist': The file “ios-app-MergedInfo.plist” couldn’t be opened because there is no such file.
```

Not sure where to go from here. Any help / direction would be great.

**Comment by c-parsons** [comment]
Can you elaborate on your steps to reproduce this? For instance, I've:
1. Installed a fresh bazel from the repo at head.
2. Freshly cloned the tutorial repository
3. "bazel build ios-app"
4. Open the generated xcodeproj using xcode 7.1
5. Rebuilt in xcode

I haven't run into any problems. The ios-app-MergedInfo.plist is present and available.

However, re-building in xcode on top of bazel is still a little delicate. For instance, invoking bazel operations (such as bazel clean) will delete the generated files, such as the MergedInfo.plist, and xcode will be unable to build the project appropriately without regenerating these files.

We know of this, and are still working on some solutions.

**Comment by spierce7** [comment]
Nice avatar.

I'm using x-code 7.2. Could that be a problem? I was also using the command `bazel build //ios-app:ios-app`.

I'd try it again, but I'm running into a different issue now. After I installed the 8.4 simulator, and the bazel build was completing, but then I was forced to do a hard-restart of the computer and now it won't build. I get the following error:

```
.../examples/tutorial/ios-app/BUILD:17:1: null failed: Process exited with status 1 : xcodebuild: error: SDK "iphonesimulator8.4" cannot be located.
xcodebuild: error: SDK "iphonesimulator8.4" cannot be located.
xcrun: error: unable to lookup item 'Path' in SDK 'iphonesimulator8.4'
```

But I clearly have the 8.4 simulator installed:
![screen shot 2015-12-28 at 1 34 35 pm](https://cloud.githubusercontent.com/assets/871169/12023631/3efd0cdc-ad69-11e5-94c5-8634ef264f32.png)

I've tried uninstalling simulator, and re-installing it, but I end up with the same result each time.

Where could I specify what version of the simulator version to use? Maybe specifying a different version would work?

**Comment by c-parsons** [comment]
Actually, bazel is looking for the appropriate *SDK* version to complete the build.
With xcode 7.2, I believe you should have 9.2 installed by default.
Thus, try including the build flag --ios_sdk_version=9.2
(The current default value of this flag is 8.4. We're looking into assessing system-level defaults to avoid the need to update this)

**Comment by spierce7** [comment]
@c-parsons Thanks for your response. I just tried your suggestion. I've tried adding this to the `objc_library` rule:

```python
    copts = [
        '--ios_sdk_version=9.2',
    ],
```

I tried a few different things, but it's still asking for "iphonesimulator8.4". How should I include the build flag exactly?

**Comment by spierce7** [comment]
I was able to get it working using the command `bazel build //ios-app:ios-app --ios_sdk_version=9.2`. When I open the xcode file, everything builds fine. I just did a clean install of El Capitan today. That may have had something to do with why it's working now. 

Two questions:
1. Bazel still can't find my 8.4 sdk. What am I doing wrong?
2. Is there a way to declare the ios_sdk_version in a more convenient way inside one of the build files so I don't have to remember to tack on the --ios_sdk_version flag?

**Comment by c-parsons** [comment]
Sorry I wasn't clear :) Yes, `bazel build //ios-app:ios-app --ios_sdk_version=9.2` is what I had in mind.

This flag is a build-wide flag and not a target-level attribute; it wouldn't make sense to place this flag in a BUILD file.
For convenience, consider adding the flag to your .bazelrc file. See the [user manual](http://bazel.io/docs/bazel-user-manual.html) for details.

**Comment by spierce7** [comment]
.bazelrc was perfect. Thanks @c-parsons !
