### ISSUE TITLE
Remote Java tools do not work on Windows (unless it's a clean build)

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#7440]
### Description of the problem :

bazel 0.22 introduced 2 flags that swtich to using an `http_archive` of tools needed for building Java targets instead of using the same tools embedded into the bazel binary.

I succeed to build a Java target on Windows with these flags enabled only after a clean build. When I run the same command again the build fails with:

```
ERROR: Source forest creation failed: D:/b/sdlshnzi/execroot/io_bazel/_tmp/2713b7a92d8298dcf32c3b44de75c8b1/root/sb26b24g/execroot/main/external/remote_java_tools/JavaBuilder_deploy.jar (Permission denied)
```

Probably useful:
* Both the first and second bazel run call `JavaBuilder_deploy.jar`. 
* `JavaBuilder_deploy.jar` file has write permissions 
* The `http_archive` is declared in [jdk.WORKSPACE](https://github.com/bazelbuild/bazel/blob/1d205e14e4c069e9199ab71b127c6a6e26a9443b/src/main/java/com/google/devtools/build/lib/bazel/rules/java/jdk.WORKSPACE#L208)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ mkdir -p java_example/java/com/google/src/

$ cat >java_example/BUILD << EOL
java_binary( 
    name = "JavaExample", 
    srcs = ["java/com/google/src/JavaExample.java"], 
   main_class = "com.google.src.JavaExample", 
) 
EOL

$ cat >java/com/google/src/JavaExample.java << EOL
package com.google.src;
public class JavaExample {
   public static void main(String[] args) {
       System.out.println("SUCCESS!");
   }
}
EOL

$ bazel build :ExampleJava --incompatible_use_remote_java_toolchain --incompatible_use_remote_host_java_toolchain

$ bazel build :ExampleJava --incompatible_use_remote_java_toolchain --incompatible_use_remote_host_java_toolchain
```

The first bazel run should complete successfully, while the second should fail with the above error.

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 0.23.0rc1

### Any other information, logs, or outputs that you want to share?

There are some failures on BuildKite as well, for example:
[example 1](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/af825a52-2e0c-4d94-bbee-e1924dad7c25/src%5Ctest%5Cshell%5Cbazel%5Cbazel_windows_example_test%5Cattempt_1.log)

**Comment by iirina** [comment]
cc: @laszlocsomor @lberki

**Comment by iirina** [comment]
This is a blocker for #7196 and #7197 which are planned for Bazel 0.24.

**Comment by iirina** [comment]
I have found a fix for this...

The current content of my `http_archive` consists only of regular files (e.g. `JavaBuilder_deploy.jar`). If I place all the files under a top-level directory this issue is fixed.

IIUC this is because you can only create symlinks for directories on Windows. Bazel tries to remove all non-symlink directories/files from the execroot tree. On Windows this means that it tries to remove all the files downloaded from my `http_archive`. If I place everything under a directory it won't try to remove it anymore, so the `Permission denied` error is not happening anymore.

**Comment by laszlocsomor** [comment]
@iirina : Is this a blocker for 0.23.0? (https://github.com/bazelbuild/bazel/issues/7440)

More info: `bazel shutdown`, then build again: this works.

**Comment by iirina** [comment]
Laszlo, it's not blocking 0.23.0.

**Comment by laszlocsomor** [comment]
Great, thanks!

Meanwhile I found out that JavaBuilder_deploy.jar is held open by the java persistent worker, child process of Bazel, which explains why it cannot be deleted. It does not explain though why Bazel tries to delete this file at all -- the second build is a null build after all. Do you have any idea what's going on?

**Comment by iirina** [comment]
The error is thrown in the [ExecutionTool](https://github.com/bazelbuild/bazel/blob/38da4abf71d9afac22d92248dcfd85b4e15e4ea0/src/main/java/com/google/devtools/build/lib/buildtool/ExecutionTool.java#L455) where it creates a SymlinkForest. The SymlinkForest tries to delete everything in the execroot tree that is not a symlink. I think this part of the code is always executed even on null builds because it's in the execution phase.

**Comment by iirina** [comment]
@laszlocsomor Thanks for looking into it! I will mark this issue as fixed since my workaround was submitted and the remote Java tools now work correctly on all platforms. I opened #7458 to keep track of the actual issue that was causing the failure.
