### ISSUE TITLE
Support Authentication in jvm_maven_import_external/java_import_external

### ISSUE THREAD

**Issue by guw** [bazelbuild/bazel#7443]
### Description of the problem:

With #6799 `native.maven_rule` is going away. It supported reading authentication credentials for a Maven repository from `~/.m2/settings.xml`. `jvm_maven_import_external` (which is recommended as a replacement in #6799) does not support authentication.

### Feature requests: what underlying problem are you trying to solve with this feature?

In certain networks access to public Maven Central is not possible. Instead people have to go through an internal Maven repository. This requires authentication. It must be possible to download jars from Maven repositories that require authentication.

Note, some Maven repositories do not support URL style submitting of username and password. Thus, it must be provided by a HTTP header.

### Notes:

Support for Basic Authentication should be sufficient in the first place. 

Reading username/password from `~/.m2/settings.xml` would be ideal (convenient but not mandatory as long as it's decoupled from Bazel BUILD/WORKSPACE files).

**Comment by cgruber** [comment]
I'm not sure if this is simply a problem with the rule... I don't see any particular mechanism to instruct repository_ctx.download() to use some authentication.  I'm having a similar issue with bintray returning html login pages, instead of .pom files in Square's maven integration. :/

**Comment by guw** [comment]
@cgruber See #7469.

**Comment by meisterT** [comment]
Is there anything left to do here?
