### ISSUE TITLE
Account for /bin/ps in Sandbox configuration

### ISSUE THREAD

**Issue by vmax** [bazelbuild/bazel#7448]
### Description of the problem / feature request:

If a binary in system path has SUID bit set, test will fail in runtime with `Operation not permitted`. Sandbox on Linux, however, does not have the same behaviour.

### Feature requests: what underlying problem are you trying to solve with this feature?

I need to read process list via executing `ps` in `sh_test`. It works on Linux whereas on macOS I'm getting
```
/private/var/tmp/_bazel_vmax/8e8cab568c69716a0c9992fe4f39e019/sandbox/darwin-sandbox/1/execroot/__main__/bazel-out/darwin-fastbuild/bin/my.runfiles/__main__/my: line 12: /bin/ps: Operation not permitted
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`test.sh`:
```
#!/usr/bin/env bash
ps
```

`BUILD`:
```
sh_test(
    name = 'my',
    srcs = ["test.sh"]
)
```

### What operating system are you running Bazel on?

macOS Mojave 10.14.3 where bug is reproducible
Debian 9.5 in Docker where there's no such bug

### What's the output of `bazel info release`?

`release 0.22.0`

###  Have you found anything relevant by searching the web?

—

### Any other information, logs, or outputs that you want to share?

I suspect the reason is somehow that `/bin/ps` has SUID bit set on:
```
ghost:is-ps-forbidden-in-tests vmax$ ls -la $(which ps)
-rwsr-xr-x  1 root  wheel  51280 30 ноя 10:39 /bin/ps
```

I've created my own dummy script with SUID bit in a PATH visible in `bazel`'s runtime and the behaviour is consistent with what is described in the issue
`bazel run //:my`, however, works perfectly

**Comment by jmmv** [comment]
I don't see a way to detect SUID binaries in the `sandbox-exec` configuration. However, it is possible to poke holes for specific binaries. I have found that this works:

```
(version 1)
(allow default)
(allow process-exec (with no-sandbox) (literal "/bin/ps"))
```

so we should probably extend the sandbox configuration to account for `/bin/ps` given that `ps` failing is surprising behavior and it doesn't match Linux.

I do not see other worthwhile binaries to include though:

```
$ ls -l /bin /sbin /usr/bin /usr/sbin | grep rws
-rwsr-xr-x  1 root  wheel    64416 Apr  6 16:39 ps
-rwsr-xr-x   1 root   wheel     52320 Apr  6 16:38 crontab
-rwxr-xr-x   1 root   wheel      6357 Nov  9  2019 rwsnoop
-rwsr-xr-x   1 root   wheel     43136 Apr  6 16:38 su
```

so I'd say that's sufficient.

**Comment by ajbouh** [comment]
At the suggestion of @dws-uber, I ended up working around this by using `pgrep` instead of `ps`.

**Comment by jeffzoch** [comment]
Do we have any plans to allow /bin/ps? It seems a strange omission

**Comment by keith** [comment]
I submitted https://github.com/bazelbuild/bazel/pull/13727 for this
