### ISSUE TITLE
Bazel gives a cryptic error message if there's a directory named external/

### ISSUE THREAD

**Issue by glinscott** [bazelbuild/bazel#745]
Repro:

```
├── external
│   └── foo
│       ├── BUILD
│       └── main.cc
└── WORKSPACE
```

BUILD

```
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "foo",
    srcs = glob(["*.cc"]),
)
```

main.cc

```
int main() {
  return 0;
}
```

```
$ cd external/foo
$ bazel build ...
......
INFO: Found 1 target...
ERROR: ~/bazel-external-bug/external/foo/BUILD:3:1: undeclared inclusion(s) in rule '//external/foo:foo':
this rule is missing dependency declarations for the following files included by 'external/foo/main.cc':
  'external/foo/main.cc'.
Target //external/foo:foo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.983s, Critical Path: 0.07s
```

**Comment by kchodorow** [comment]
We should give a better error message, but you can't have a directory named external/.  It's reserved for use by bazel.

**Comment by glinscott** [comment]
Ah, okay, thanks!  This is definitely something bazel should check for on startup if it's not allowed.  We were converting an existing project which had a lot of projects under the "external" directory, and things mostly worked for python packages.  We had trouble with things like "bazel build ..." at the root though, hitting things like: https://github.com/bazelbuild/bazel/issues/696.

After removing everything from the external directory, things are much happier!

**Comment by kchodorow** [comment]
Sorry for the inconvenience, we'll add an error message as soon as it detects the directory.

**Comment by jin** [comment]
This is no longer the case.
