### ISSUE TITLE
bazel error py_binary 

### ISSUE THREAD

**Issue by adibrastegarnia** [bazelbuild/bazel#7460]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

When I try to create a binary of my python program using the following command:
```
COMPILE_DEPS = [
    "@dnos_core_grpc_python//protobuf/proto:onos-core-protobuf-services-proto",
]

py_binary(
    name = "py_samplepacketprocessor",
    srcs = ["samplepacketprocessor.py"],
    main = "samplepacketprocessor.py",
    deps = COMPILE_DEPS,
)

```
it gives me the following error:

```
Use --sandbox_debug to see verbose messages from the sandbox.
external/com_github_grpc_grpc/src/compiler/ruby_generator.cc: In function 'grpc::string grpc_ruby_generator::GetServices(const FileDescriptor*)':
external/com_github_grpc_grpc/src/compiler/ruby_generator.cc:165:25: error: 'const class google::protobuf::FileOptions' has no member named 'has_ruby_package'
     if (file->options().has_ruby_package()) {
                         ^
external/com_github_grpc_grpc/src/compiler/ruby_generator.cc:166:38: error: 'const class google::protobuf::FileOptions' has no member named 'ruby_package'
       package_name = file->options().ruby_package();
```

It works fine without using deps but I need to include gRPC stubs generated using python_grpc_library as dependencies. 

Here is the link to protobuf models BUILD file: 
[BUILD file for protobuf models](https://github.com/dnosproject/dnos-core-grpc-python/blob/master/protobuf/proto/BUILD)
### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

Ubuntu

### What's the output of `bazel info release`?
0.19.2

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by brandjon** [comment]
The native Python rules don't really do any C++ compilation directly, so I would guess that this error comes from somewhere underneath [`python_grpc_compile`](https://github.com/stackb/rules_proto/blob/master/python/python_grpc_library.bzl#L12). I suggest opening a bug with gRPC to triage further.
