### ISSUE TITLE
Support authentication for repository_ctx.download

### ISSUE THREAD

**Issue by guw** [bazelbuild/bazel#7469]
### Description of the problem / feature request:

The API of `repository_ctx.download` doesn't allow to supply authentication information.

### Feature requests: what underlying problem are you trying to solve with this feature?

I need to be able to download from an url that requires authentication. At a very minimum BASIC authentication should be supported.

Ideally, it would be nice to supply authentication information in a central file for all Bazel builds and independent/decoupled from Bazel BUILD and WORKSPACE files checked into Git.

**Comment by excitoon** [comment]
I would even ask for not only Basic but NTLM/SSPI authentication.

**Comment by dkelmer** [comment]
Related bugs
[bug in starlark maven jar](https://github.com/bazelbuild/bazel/issues/7781)
[http archive authentication](https://github.com/bazelbuild/bazel/issues/7770)
[remove native maven jar](https://github.com/bazelbuild/bazel/issues/6799)

**Comment by jin** [comment]
Thanks to @aehlig's work, repository_ctx.download now supports authentication through netrc.

**Comment by aehlig** [comment]
This is indeed implemented as per the [approved design on adding authentication to downloads](https://github.com/bazelbuild/proposals/blob/master/designs/2019-05-27-auth.md) in commits 24cf645480eabbd464f7b7d9b7dbf0669e5c87b6, 38cfc187d3b8c3068cd46b730a5ca84ba27d0655, e1e074c9160affea3fe49062f01e0f331622f405, and c26e3396cb341e173b4be5c780cafac3ec386df5.

**Comment by igorgatis** [comment]
Current Bazel documentation about `repository_ctx.download`'s authentication is rather poor. I already spent literaly a handful of hours trying to make it work.

**Comment by cristifalcas** [comment]
> Current Bazel documentation about `repository_ctx.download`'s authentication is rather poor. I already spent literaly a handful of hours trying to make it work.

Please share how to do it :)

**Comment by koenverwimp** [comment]
@igorgatis Could you please share your findings?
@cristifalcas  Did you find a solution in the mean time?

**Comment by tomml** [comment]
I would like to use a Bearer token here instead of basic auth. Is this possible? I need to access a private company maven repositor.
Documentation is pretty poor at this point only mentioning that there is a "type" which can be basic.

@aehlig It seems you've proposed and implemented the auth feature. Could you give some more insights? Thanks!
