### ISSUE TITLE
Unable to dynamic link libstdc++.so on Android

### ISSUE THREAD

**Issue by llhe** [bazelbuild/bazel#7475]
### Description of the problem / feature request:

Build with Android NDK will result in statically linking of libstdc++ (with Android NDK 17+), and there is no way or no documentation for dynamic linking of this library.

### Feature requests: what underlying problem are you trying to solve with this feature?

Provide an approach or documents about dynamic linking of libstdc++

### What operating system are you running Bazel on?

Ubuntu 16.04.5 LTS

### What's the output of `bazel info release`?

release 0.18.0

###  Have you found anything relevant by searching the web?

Adding "-lstdc++" to linkopts does not work.

### Any other information, logs, or outputs that you want to share?

```
SUBCOMMAND: # //crt/util:util_test [action 'Linking crt/util/util_test']
(cd /home/heliangliang/.cache/bazel/_bazel_heliangliang/e4e233213fdd9bfa2cfe47893fd44864/execroot/crt && \
  exec env - \
    PATH=/home/heliangliang/app/cmake-2.8.0-Linux-i386/bin/:/home/heliangliang/app/jdk/jdk1.8.0_25/bin:/home/heliangliang/bin:/home/heliangliang/app/bin:/home/heliangliang/app/idea-IC-171.4424.56/bin/:/home/heliangliang/app/apache-maven-3.3.9/bin:/home/heliangliang/app/phabricator/arcanist/bin:/home/heliangliang/app/protobuf3.1.0/bin:/home/heliangliang/bin:/home/heliangliang/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/heliangliang/work/minos/client:/home/heliangliang/go/bin:/home/heliangliang/app/gradle-4.4/bin \
    PWD=/proc/self/cwd \
  external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -o bazel-out/arm64-v8a-fastbuild/bin/crt/util/util_test bazel-out/arm64-v8a-fastbuild/bin/crt/util/_objs/util_test/string_util_test.o bazel-out/arm64-v8a-fastbuild/bin/crt/util/libutil.a bazel-out/arm64-v8a-fastbuild/bin/external/gtest/libgtest_main.a bazel-out/arm64-v8a-fastbuild/bin/external/gtest/libgtest.a external/androidndk/ndk/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++.a external/androidndk/ndk/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_static.a external/androidndk/ndk/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++abi.a -ldl -pie -llog -lstdc++ -pthread -pthread -static-libgcc -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -target aarch64-none-linux-android -no-canonical-prefixes -Lexternal/androidndk/ndk/sources/cxx-stl/llvm-libc++/libs/arm64-v8a -rdynamic -static-libgcc -Wl,-S '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm64')

```

**Comment by llhe** [comment]
Simply adding `linkstatic = 0` works.

**Comment by cpsauer** [comment]
@llhe, if you still remember, any chance I could ask you for some more details on how you got around this?

I was running into a similar thing, exploring trying to use c++_shared to share libc++_shared.so between .so's. But adding linkstatic=0 to the cc_library being depended on by the android_library doesn't seem to change the link command at all. libc++_static.a and friends still get linked in. (And I couldn't find any other docs.)

**Comment by cpsauer** [comment]
@llhe?

**Comment by llhe** [comment]
@cpsauer Sorry for the late reply. I could not remember the exact problem (and recently not working on Android platform), but the solution might be this: https://github.com/XiaoMi/mace/blob/fa72958a647be9457cf0a19d2f1195205a4b1a58/mace/libmace/BUILD.bazel#L104. You could try.

**Comment by cpsauer** [comment]
No, thanks so much for posting back!

Super useful as a general example. Mine are via an android_library, so I'll have to figure out how to do it in that case.
