### ISSUE TITLE
incompatible_list_based_execution_strategy_selection: List-based explicit spawn strategy selection.

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#7480]
:no_good_man: Current situation:
- The user can set the execution strategy in general and for individual action mnemonics using the flags `--spawn_strategy=`, `--strategy=Mnemonic=` and `--strategy_regexp=Regex=`. The flags take a single strategy name as value. Example: `--spawn_strategy=linux-sandbox`.
- Bazel has a hardcoded and undocumented list of mnemonics that are known to work well with certain strategies and uses these unless the user overrides them *individually* using `--strategy=Mnemonic=` flags. Example: Bazel will use some kind of sandboxing by default if its available on your system, otherwise non-sandboxed execution (e.g. on Windows). However, it will run Javac actions via the persistent worker strategy.
- Each strategy has custom code to deal with the situation that it can't execute a given action - for example, the remote strategy silently falls back to sandboxed execution if an action can't run remotely. The sandbox strategy silently falls back to non-sandboxed local execution if an action doesn't support sandboxing. There's no good way to configure this behavior.

:new: The option `--incompatible_list_based_execution_strategy_selection`:
- Allows the user to pass comma-separated lists of strategies to the above mentioned flags: `--spawn_strategy=remote,worker,linux-sandbox`.
- Each strategy now knows whether it can execute a given action. For any action that it wants to execute, Bazel just picks the first strategy from the given list that claims to be able to execute the action. If no strategy remains, the execution will fail.
 - This means you can now have your build fail if any non-sandboxable or non-remotable action sneaks in! More reproducibility and safety for your builds! :tada:
- The strategies no longer do their own custom fallback, simplifying the code and unifying the behavior.

:bulb: Some ideas how to use this:
- Don't set any flags and Bazel will try to do the best automatically: Use remote execution if it's available, otherwise persistent workers, otherwise sandboxed execution, otherwise non-sandboxed execution.
- I want the best sandboxed build on my Linux machine and no automatic fallback to symlink-only sandboxing, non-sandboxed execution and no persistent workers: `--spawn_strategy=linux-sandbox`.
- I want persistent workers for actions that support it, but otherwise only sandboxed execution: `--spawn_strategy=worker,sandboxed`.

:construction: Migration needed:
- If you currently use the strategy selection flags, you'll want to revisit the values you set them to.
- If you currently patch your Bazel version to remove fallback to non-sandboxed execution, this should no longer be necessary then (:wave: @AustinSchuh).

**Comment by AustinSchuh** [comment]
Thanks @philwo !  This looks helpful.

We moved over to just using ```--spawn_strategy=linux-sandbox``` based on your advice in late 2017.  That means we no longer have a patch for that.

Does this replace ```--remote_local_fallback_strategy=linux-sandbox``` ?

**Comment by agoulti** [comment]
Yes.
Under `incompatible_list_based_execution_strategy_selection`, `remote_local_fallback_strategy` will no longer be respected. A target that is marked no-remote will not be eligible for remote execution, so the next available strategy from the list will be applied.

We plan to deprecate `remote_local_fallback_strategy` by the time `incompatible_list_based_execution_strategy_selection` becomes the default.

We think that the new strategy list should serve all the fallback needs (and make things more explicit and cleaner). Do let us know if for some reason your case is not being served!

**Comment by buchgr** [comment]
@ishikhman as parts of your flag work can you please take over ownership of flipping this flag? You probably won't get to it by 0.26 (this thursday) so let's target to flip this in 0.27? I don't expect there to be much trouble except for fixing a few tests.

**Comment by laurentlb** [comment]
Could you improve the release notes about it?
See https://github.com/bazelbuild/bazel/issues/7816#issuecomment-502304725

**Comment by ishikhman** [comment]
> Could you improve the release notes about it?
> See [#7816 (comment)](https://github.com/bazelbuild/bazel/issues/7816#issuecomment-502304725)

hm, it is in release notes (I've checked https://github.com/bazelbuild/bazel-blog/pull/178) and blog post is coming right after 0.27 release (https://github.com/bazelbuild/bazel-blog/pull/173). 

The release notes are already rather long, so what I can suggest is to include a link to the blog post. WDYT?

**Comment by laurentlb** [comment]
Sounds good to me.

**Comment by ishikhman** [comment]
> Yes.
> Under `incompatible_list_based_execution_strategy_selection`, `remote_local_fallback_strategy` will no longer be respected. A target that is marked no-remote will not be eligible for remote execution, so the next available strategy from the list will be applied.
> 
> We plan to deprecate `remote_local_fallback_strategy` by the time `incompatible_list_based_execution_strategy_selection` becomes the default.
> 
> We think that the new strategy list should serve all the fallback needs (and make things more explicit and cleaner). Do let us know if for some reason your case is not being served!

I just checked that this is no _exactly_ the case. There are 2 use cases where `remote_local_fallback_strategy` was used:
1) when target is marked as `no-remote` or `no-remote-exec`: [link](https://github.com/bazelbuild/bazel/blob/11a98a51095bfda494ddf7ba69d8ad80309ef63c/src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnRunner.java#L181)
2) when remote execution failed and was caused NOT by a Timeout exception: [link](https://github.com/bazelbuild/bazel/blob/11a98a51095bfda494ddf7ba69d8ad80309ef63c/src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnRunner.java#L281) and [link2](https://github.com/bazelbuild/bazel/blob/11a98a51095bfda494ddf7ba69d8ad80309ef63c/src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnRunner.java#L216)

The first case is fully covered by a list-based strategy, but not the second one. Therefore if the second use case is important (which I think it is, because someone mentioned that they rely on fallback in case of connection problems to a remote system) we cannot discard `remote_local_fallback_strategy`.

I'll remove the usages for the first case as a part of #8970.

If we want to completely deprecate `remote_local_fallback_strategy`, i think, we should consider generic fallback mechanism that would be using a provided list.
