### ISSUE TITLE
aquery_differ documentation

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#7481]
https://docs.bazel.build/versions/master/aquery.html#diff-tool

Documentation doesn't say where is the tool.
The command-line from the example doesn't work (`bazel run //tools/aquery_differ`).

**Comment by jin** [comment]
cc @joeleba

**Comment by joeleba** [comment]
@laurentlb By "the command-line from the example doesn't work", do you mean it doesn't work outside of the bazelbuild/bazel repo?

**Comment by laurentlb** [comment]
Yes.
Do you expect users to guess they have to download Bazel source code and run Bazel from there?
