### ISSUE TITLE
failed to run ./compile.sh

### ISSUE THREAD

**Issue by panjiepan** [bazelbuild/bazel#749]
./compile.sh 
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh build /path/to/bazel
🍃  Building Bazel from scratch............
🍃  Building Bazel with Bazel.
.Extracting Bazel installation...
Sending SIGTERM to previous Bazel server (pid=5805)... done.
..............
INFO: Found 1 target...
INFO: From Building src/tools/android/java/com/google/devtools/build/android/libandroid_builder_lib.jar (18 files):
src/tools/android/java/com/google/devtools/build/android/AndroidResourceProcessor.java:323: error: incompatible types: StringBuilder cannot be converted to StringBuffer
          idMatcher.appendReplacement(resourceIds, String.format("public static int %s=0x%08X;",
                                      ^
src/tools/android/java/com/google/devtools/build/android/AndroidResourceProcessor.java:326: error: incompatible types: StringBuilder cannot be converted to StringBuffer
        idMatcher.appendTail(resourceIds);
                             ^
src/tools/android/java/com/google/devtools/build/android/AndroidResourceProcessor.java:327: error: incompatible types: StringBuilder cannot be converted to StringBuffer
        innerClassMatcher.appendReplacement(out,
                                            ^
src/tools/android/java/com/google/devtools/build/android/AndroidResourceProcessor.java:330: error: incompatible types: StringBuilder cannot be converted to StringBuffer
      innerClassMatcher.appendTail(out);
                                   ^
Note: src/tools/android/java/com/google/devtools/build/android/ResourceShrinker.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
4 errors
BazelJavaBuilder threw exception: java compilation returned status ERROR
ERROR: /home/panjie/src/bazel/src/tools/android/java/com/google/devtools/build/android/BUILD:35:1: Java compilation in rule '//src/tools/android/java/com/google/devtools/build/android:android_builder_lib' failed: java failed: error executing command external/local-jdk/bin/java -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac.jar -client -jar bazel-out/host/bin/src/java_tools/buildjar/bootstrap_deploy.jar ... (remaining 1 argument(s) skipped): Worker process sent response with exit code: 1.
Target //src:bazel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 25.066s, Critical Path: 11.77s

Building output/bazel

**Comment by chin33z** [comment]
+1

**Comment by kchodorow** [comment]
This should be fixed as of 0e72b69d0df6924537e8c4dd996c10c53586902c.
