### ISSUE TITLE
Updating bundled gRPC to 1.18 increased Bazel binary size by ~1.7 MB

### ISSUE THREAD

**Issue by tetromino** [bazelbuild/bazel#7497]
As noticed by @meisterT - 458ab037e395f872fece67403a2a46a3ad480112 and 539bfc9870d26ab44c4912e65c08c0cc285f7d8b (updating bundled gRPC c++ library to 1.18) seem to have increased the bazel binary size by ~1.7 MB: from 151.6 MB to 153.4 MB.

The new version of gRPC is much larger; SLOC in `//third_party/grpc` has more than doubled. But perhaps we are compiling more of that code than we really need for the bazel client's purposes.

Investigation is needed.

**Comment by meisterT** [comment]
Any update here?

**Comment by tetromino** [comment]
I've compared the list of source files for old vs. new bundled gRPC. The main difference that jumps out to me is [the new load balancing code](https://github.com/grpc/grpc/blob/master/doc/load-balancing.md). A quick test shows that removing grpc_lb_policy_grpclb and grpc_lb_policy_xds reduces Bazel binary size by 174 KB.

But it means carrying a small patch to disable those policies in the code and manually applying that patch (and resolving inevitable conflicts) every time we bump the bundled library version.

Worth doing?

**Comment by meisterT** [comment]
No, 174KB is not worth it. I still wonder what increased it by 1.7MB then, but closing for now. Thanks for investigating!
