### ISSUE TITLE
Remote Execution contains duplicate output_files

### ISSUE THREAD

**Issue by DaveGay** [bazelbuild/bazel#7500]
As of the Bazel release stamped "21-02-2019 16:18" (earlier today), calls to Execute for our Java test targets are now including a duplicated "output_files" entry:

`output_files: "bazel-out/k8-fastbuild/bin/hello_world_test.jar"`
`output_files: "bazel-out/k8-fastbuild/bin/hello_world_test.jar_manifest_proto"`
`output_files: "bazel-out/k8-fastbuild/bin/hello_world_test.jdeps"`
`output_files: "bazel-out/k8-fastbuild/bin/hello_world_test.jdeps"`

Previous runs of the same test generated this list:

`output_files: "bazel-out/k8-fastbuild/bin/hello_world_test.jar"`
`output_files: "bazel-out/k8-fastbuild/bin/hello_world_test.jar_manifest_proto"`
`output_files: "bazel-out/k8-fastbuild/bin/hello_world_test.jdeps"`

**Comment by ulfjack** [comment]
Duplicate of #7508.
