### ISSUE TITLE
Remove dependency on the java.desktop module

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel#7502]
It contributes 13MB to the the size of the embedded JDK which is ~40MB in total right now.

This list describes the paths in the `server.jar` which contain classes that depend on the java.desktop module:
- [x] `javax/xml/bind`
- [x] `com/android/ddmlib`
- [ ] `com/android/ide/common/util`
- [ ] `com/android/ide/common/rendering`
- [ ] `com/android/ide/common/rendering/api`
- [ ] `com/android/ide/common/vectordrawable`
- [ ] `com/android/tools/lint/checks`
- [ ] `com/android/sdklib/devices`
- [ ] `com/android/builder/png`
- [x] `lombok/ast/ecj`
- [x] `lombok/ast/grammar`

In turn `javax.xml.bind` is used by maven_jar (see #6799) and by the android_common dependency of `android_sdk_repository`.
`lombok/.*` comes from `third_party/android_common/com.android.tools.external.lombok_lombok-ast_0.2.3.jar`.

**Comment by jin** [comment]
Making a change in android_common jars will typically incur a lot of changes internally - please let us (@ahumesky / myself) know if you stumble upon any roadblocks.

**Comment by meisterT** [comment]
@jin to be clear: I still count on you / the Android team to work on unbundling the tools (#1055).
This issue is to keep track of the removal of the module itself and the outstanding blockers.

**Comment by jin** [comment]
Ah, my bad, I misunderstood the assignment on this issue as you taking it up :) Thanks for clarifying! Unbundling the mobile tools will definitely be part of the ongoing Android Starlark migration (and land in bazelbuild/tools_android).
