### ISSUE TITLE
Building TensorFlow on Windows 10 64-Bit fails

### ISSUE THREAD

**Issue by cenh** [bazelbuild/bazel#7504]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> I tried to build/compile tensorflow using the command ``$ bazel build -c opt contrib/model_pruning:strip_pruning_vars
``
> I get the following message:
> C:\Users\chhn\Desktop\Tensorflow\tensorflow>bazel build -c opt contrib/model_pruning:strip_pruning_vars

> Extracting Bazel installation...
> Starting local Bazel server and connecting to it...
> INFO: Invocation ID: ad8a559f-f40a-424c-8968-8c3616e76a03
> Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//tensorflow/python:gen_boosted_trees_ops_py_wrappers_cc BuildConfigurationValue.Key[fa716c1f3ad995922675f9480f09004e] true' (requested by nodes '//tensorflow/python:boosted_trees_ops_pygenrule BuildConfigurationValue.Key[fa716c1f3ad995922675f9480f09004e] true', '//tensorflow/python:boosted_trees_ops_pygenrule BuildConfigurationValue.Key[a46389e7efd2cfd6bf7ec804c025d95e] false')
>         at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:514)
>         at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
>         at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.localPopAndExec(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
> Caused by: java.lang.IllegalStateException
>         at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
>         at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addDynamicInputLinkOptions(LibrariesToLinkCollector.java:293)
>         at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addLinkerInputs(LibrariesToLinkCollector.java:258)
>         at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.collectLibrariesToLink(LibrariesToLinkCollector.java:203)
>         at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(CppLinkActionBuilder.java:826)
>         at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createDynamicLibrary(CcLinkingHelper.java:716)
>         at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createCcLinkActions(CcLinkingHelper.java:441)
>         at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.link(CcLinkingHelper.java:357)
>         at com.google.devtools.build.lib.rules.cpp.CcBinary.createTransitiveLinkingActions(CcBinary.java:720)
>         at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:416)
>         at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:242)
>         at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:75)
>         at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:323)
>         at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:207)
>         at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:758)
>         at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:780)
>         at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:326)
>         at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:437)
>         ... 6 more
> 
> INFO: Elapsed time: 189.324s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (159 packages loaded, 7515 targets configured)
>     Fetching @swig; fetching 109s
>     Fetching @grpc; fetching 37s
>     Fetching @png_archive; fetching 12s
> Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//tensorflow/python:gen_boosted_trees_ops_py_wrappers_cc BuildConfigurationValue.Key[fa716c1f3ad995922675f9480f09004e] true' (requested by nodes '//tensorflow/python:boosted_trees_ops_pygenrule BuildConfigurationValue.Key[fa716c1f3ad995922675f9480f09004e] true', '//tensorflow/python:boosted_trees_ops_pygenrule BuildConfigurationValue.Key[a46389e7efd2cfd6bf7ec804c025d95e] false')
>         at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:514)
>         at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
>         at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.localPopAndExec(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
> Caused by: java.lang.IllegalStateException
>         at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
>         at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addDynamicInputLinkOptions(LibrariesToLinkCollector.java:293)
>         at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addLinkerInputs(LibrariesToLinkCollector.java:258)
>         at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.collectLibrariesToLink(LibrariesToLinkCollector.java:203)
>         at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(CppLinkActionBuilder.java:826)
>         at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createDynamicLibrary(CcLinkingHelper.java:716)
>         at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createCcLinkActions(CcLinkingHelper.java:441)
>         at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.link(CcLinkingHelper.java:357)
>         at com.google.devtools.build.lib.rules.cpp.CcBinary.createTransitiveLinkingActions(CcBinary.java:720)
>         at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:416)
>         at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:242)
>         at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:75)
>         at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:323)
>         at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:207)
>         at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:758)
>         at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:780)
>         at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:326)
>         at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:437)
>         ... 6 more
> java.lang.RuntimeException: Unrecoverable error while evaluating node '//tensorflow/python:gen_boosted_trees_ops_py_wrappers_cc BuildConfigurationValue.Key[fa716c1f3ad995922675f9480f09004e] true' (requested by nodes '//tensorflow/python:boosted_trees_ops_pygenrule BuildConfigurationValue.Key[fa716c1f3ad995922675f9480f09004e] true', '//tensorflow/python:boosted_trees_ops_pygenrule BuildConfigurationValue.Key[a46389e7efd2cfd6bf7ec804c025d95e] false')
>         at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:514)
>         at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
>         at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.localPopAndExec(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
> Caused by: java.lang.IllegalStateException
>         at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
>         at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addDynamicInputLinkOptions(LibrariesToLinkCollector.java:293)
>         at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addLinkerInputs(LibrariesToLinkCollector.java:258)
>         at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.collectLibrariesToLink(LibrariesToLinkCollector.java:203)
>         at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(CppLinkActionBuilder.java:826)
>         at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createDynamicLibrary(CcLinkingHelper.java:716)
>         at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createCcLinkActions(CcLinkingHelper.java:441)
>         at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.link(CcLinkingHelper.java:357)
>         at com.google.devtools.build.lib.rules.cpp.CcBinary.createTransitiveLinkingActions(CcBinary.java:720)
>         at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:416)
>         at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:242)
>         at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:75)
>         at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:323)
>         at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:207)
>         at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:758)
>         at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:780)
>         at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:326)
>         at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:437) ... 6 more
> java.lang.RuntimeException: Unrecoverable error while evaluating node '//tensorflow/python:gen_boosted_trees_ops_py_wrappers_cc BuildConfigurationValue.Key[fa716c1f3ad995922675f9480f09004e] true' (requested by nodes '//tensorflow/python:boosted_trees_ops_pygenrule BuildConfigurationValue.Key[fa716c1f3ad995922675f9480f09004e] true', '//tensorflow/python:boosted_trees_ops_pygenrule BuildConfigurationValue.Key[a46389e7efd2cfd6bf7ec804c025d95e] false')
>         at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:514)
>         at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
>         at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.localPopAndExec(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
>         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
> Caused by: java.lang.IllegalStateException
>         at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
>         at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addDynamicInputLinkOptions(LibrariesToLinkCollector.java:293)
>         at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addLinkerInputs(LibrariesToLinkCollector.java:258)
>         at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.collectLibrariesToLink(LibrariesToLinkCollector.java:203)
>         at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(CppLinkActionBuilder.java:826)
>         at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createDynamicLibrary(CcLinkingHelper.java:716)
>         at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createCcLinkActions(CcLinkingHelper.java:441)
>         at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.link(CcLinkingHelper.java:357)
>         at com.google.devtools.build.lib.rules.cpp.CcBinary.createTransitiveLinkingActions(CcBinary.java:720)
>         at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:416)
>         at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:242)
>         at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:75)
>         at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:323)
>         at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:207)
>         at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:758)
> FAILED: Build did NOT complete successfully (159 packages loaded, 7515 targets configured)
>     Fetching @swig; fetching 109s
>     Fetching @grpc; fetching 37s
>     Fetching @png_archive; fetching 12s

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Get the latest version of Tensorflow and Bazel on Windows 64-Bit. Try to build bazel.

### What operating system are you running Bazel on?

> Windows 10 64-Bit

### What's the output of `bazel info release`?

> ``INFO: Invocation ID: 05684888-9867-4168-86d7-4549771b3ba2
release 0.22.0``

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Not built using git

###  Have you found anything relevant by searching the web?

> Nope

### Any other information, logs, or outputs that you want to share?

> I ran ``bazel clean`` before building
> Environmental variables has been set.
> Using jre1.8.0_161
> Python 3.5
> Also tried earlier versions of bazel (0.12, 0.18, 0.22)

**Comment by jin** [comment]
Slotting this to team-Windows, please reassign if necessary.

**Comment by laszlocsomor** [comment]
@cenh : Let's try to diagnose this. I followed the steps of https://www.tensorflow.org/install/source_windows, and although my build of `contrib/model_pruning:strip_pruning_vars` is still running, it's looking good so far (and it already completed ~2000 actions). I'm using Bazel 0.22.0 on Windows 10.

1. Did you run `python ./configure.py`? Did you specify any non-default value?
1. Which commit or branch of TensorFlow do you have checked out? Mine is https://github.com/tensorflow/tensorflow/commit/00afc7bb81d6d36a0f619c08c011abe08965a25b.
1. How did you set your PATH? I did this:
   ```
   set PATH=c:\Python37;c:\Python37\Scripts;c:\msys64\usr\bin;c:\src\bazel-releases\current;c:\Windows\System32
   ```
1. Do you have the `BAZEL_SH`, and either the `BAZEL_VC` or the `BAZEL_VS` environment variables set up? What's their value? (Run `set BAZEL_` in cmd.exe to print all envvars whose name starts with "BAZEL_").

**Comment by laszlocsomor** [comment]
The build eventually finished:
```
Target //tensorflow/contrib/model_pruning:strip_pruning_vars up-to-date:
  C:/_bazel/fe7cy5zh/execroot/org_tensorflow/bazel-out/x64_windows-opt/bin/tensorflow/contrib/model_pruning/strip_pruning_vars.exe
  C:/_bazel/fe7cy5zh/execroot/org_tensorflow/bazel-out/x64_windows-opt/bin/tensorflow/contrib/model_pruning/strip_pruning_vars.zip
INFO: Elapsed time: 2129.866s, Critical Path: 245.23s
INFO: 4225 processes: 4225 local.
INFO: Build completed successfully, 5451 total actions
```

**Comment by cenh** [comment]
@laszlocsomor thanks for the help. I tried the commit of Tensorflow you put there and I got further I believe.

To answer your questions: 

* Did you run `python ./configure.py`? Did you specify any non-default value?

- I used default values when available, disabled support for the others without default values.

* Which commit or branch of TensorFlow do you have checked out? Mine is [tensorflow/tensorflow@00afc7b](https://github.com/tensorflow/tensorflow/commit/00afc7bb81d6d36a0f619c08c011abe08965a25b).

- I am now using this commit.

* How did you set your PATH? I did this:
  ```
  set PATH=c:\Python37;c:\Python37\Scripts;c:\msys64\usr\bin;c:\src\bazel-releases\current;c:\Windows\System32
  ```

- I set the paths using the environmental variables interface for Windows. So I have the relevants paths in 'Path': C:\Users\chhn\AppData\Local\Continuum\anaconda3, C:\bazel, C:\msys32\usr\bin

* Do you have the `BAZEL_SH`, and either the `BAZEL_VC` or the `BAZEL_VS` environment variables set up? What's their value? (Run `set BAZEL_` in cmd.exe to print all envvars whose name starts with "BAZEL_").

set BAZEL_
- BAZEL_SH=C:\msys32\usr\bin\bash.exe
- BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC
- BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2017


I should say that I followed the instructions from msys after installation, updated and upgraded with a restart of the terminal inbetween.

My error code now with using the new commit is:

``C:\Users\chhn\Desktop\tensorflow\tensorflow>bazel build -c opt contrib/model_pruning:strip_pruning_vars
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 111afa41-eb2f-4e96-9fd5-26c9b4898612
DEBUG: C:/users/chhn/_bazel_chhn/x3deuiqq/external/build_bazel_rules_apple/apple/repositories.bzl:35:5:
WARNING: `build_bazel_rules_apple` depends on `bazel_skylib` loaded from https://github.com/bazelbuild/bazel-skylib.git (tag 0.6.0), but we have detected it already loaded into your workspace from None (tag None). You may run into compatibility issues. To silence this warning, pass `ignore_version_differences = True` to `apple_rules_dependencies()`.

ERROR: C:/users/chhn/desktop/tensorflow/tensorflow/core/platform/default/build_config/BUILD:222:1: no such package '@png_archive//': Traceback (most recent call last):
        File "C:/users/chhn/desktop/tensorflow/third_party/repo.bzl", line 106
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/users/chhn/desktop/tensorflow/third_party/repo.bzl", line 73, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/users/chhn/desktop/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'C:\msys32\usr\bin\bash.exe -l -c "patch" "-p1" "-d" "C:/users/chhn/_bazel_chhn/x3deuiqq/external/png_archive" "-i" "C:/users/chhn/desktop/tensorflow/third_party/png_fix_rpi.patch"':
Stdout:
Stderr: /usr/bin/bash: patch: command not found
 and referenced by '//tensorflow/core/platform/default/build_config:png'
ERROR: Analysis of target '//tensorflow/contrib/model_pruning:strip_pruning_vars' failed; build aborted: Analysis failed
INFO: Elapsed time: 47.051s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (182 packages loaded, 6586 targets configured)
    Fetching @swig; fetching 26s
    Fetching @eigen_archive; fetching 23s
    Fetching @grpc; fetching 13s
    Fetching @png_archive; fetching 10s``

**Comment by cenh** [comment]
I installed my current MSYS2, and got the 64-bit version, and updated the environmental variables to the c:\msys64. I then did:
- ``pacman -Syu``
- Closed the terminal
- ``pacman -Su``
- ``pacman -S diffutils``
- Got no errors in the terminal. Closed msys64
- Opened a cmd-prompt
- ``bazel clean``
- ``bazel build -c opt contrib/model_pruning:strip_pruning_vars``
- And I get the same error:

C:\Users\chhn\Desktop\tensorflow\tensorflow>bazel build -c opt contrib/model_pruning:strip_pruning_vars
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 23f21931-9598-429f-8b34-554e4a7e713e
DEBUG: C:/users/chhn/_bazel_chhn/x3deuiqq/external/build_bazel_rules_apple/apple/repositories.bzl:35:5:
WARNING: `build_bazel_rules_apple` depends on `bazel_skylib` loaded from https://github.com/bazelbuild/bazel-skylib.git (tag 0.6.0), but we have detected it already loaded into your workspace from None (tag None). You may run into compatibility issues. To silence this warning, pass `ignore_version_differences = True` to `apple_rules_dependencies()`.

ERROR: Analysis of target '//tensorflow/contrib/model_pruning:strip_pruning_vars' failed; build aborted: no such package '@eigen_archive//': Traceback (most recent call last):
        File "C:/users/chhn/desktop/tensorflow/third_party/repo.bzl", line 106
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/users/chhn/desktop/tensorflow/third_party/repo.bzl", line 73, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/users/chhn/desktop/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'C:\msys64\usr\bin\bash.exe -l -c "patch" "-p1" "-d" "C:/users/chhn/_bazel_chhn/x3deuiqq/external/eigen_archive" "-i" "C:/users/chhn/desktop/tensorflow/third_party/eigen3/gpu_packet_math.patch"':
Stdout:
Stderr: /usr/bin/bash: patch: command not found
INFO: Elapsed time: 75.727s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (183 packages loaded, 6057 targets configured)
    currently loading: tensorflow/core/platform/default/build_config
    Fetching @swig; fetching 67s
    Fetching @grpc; fetching 59s
    Fetching @icu; fetching 52s
    Fetching @eigen_archive; fetching 48s

**Comment by laszlocsomor** [comment]
Still looks like the same error: `Stderr: /usr/bin/bash: patch: command not found`.

Can you run `patch` from a MSYS2 shell?

**Comment by cenh** [comment]
I could not, so I ran ``pacman -S patch`` in MSYS2 shell and it seemed to work. But after a looong time of no errors I ran into a new problem:

C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\xtr1common(88): note: see reference to class template instantiation 'std::is_same<_Ty1,_Ty2>' being compiled
INFO: From Linking tensorflow/lite/toco/python/_tensorflow_wrap_toco.so:
LINK : warning LNK4044: unrecognized option '/ldl'; ignored
LINK : warning LNK4044: unrecognized option '/lpthread'; ignored
LINK : warning LNK4044: unrecognized option '/ldl'; ignored
LINK : warning LNK4044: unrecognized option '/ldl'; ignored
   Creating library bazel-out/x64_windows-opt/bin/tensorflow/lite/toco/python/_tensorflow_wrap_toco.so.if.lib and object bazel-out/x64_windows-opt/bin/tensorflow/lite/toco/python/_tensorflow_wrap_toco.so.if.exp
utils.lib(utils.obj) : warning LNK4217: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported in function "bool __cdecl tensorflow::grappler::NodeIsOnCpu(class tensorflow::NodeDef const *)" (?NodeIsOnCpu@grappler@tensorflow@@YA_NPEBVNodeDef@2@@Z)
utils.lib(utils.obj) : warning LNK4217: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported in function "bool __cdecl tensorflow::grappler::NodeIsOnGpu(class tensorflow::NodeDef const *)" (?NodeIsOnGpu@grappler@tensorflow@@YA_NPEBVNodeDef@2@@Z)
ERROR: C:/users/chhn/desktop/tensorflow/tensorflow/BUILD:601:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1): bash.exe failed: error executing command
  cd C:/users/chhn/_bazel_chhn/x3deuiqq/execroot/org_tensorflow
  SET PATH=C:\msys64\usr\bin;C:\msys64\bin;c:\program files (x86)\smartbear\testcomplete 12\x64\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\7-Zip;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\chhn\AppData\Local\Continuum\anaconda3;C:\bazel;C:\Program Files\dotnet\;C:\msys64\usr\bin;C:\Users\chhn\AppData\Local\Continuum\anaconda3;C:\Users\chhn\AppData\Local\Continuum\anaconda3\Library\mingw-w64\bin;C:\Users\chhn\AppData\Local\Continuum\anaconda3\Library\usr\bin;C:\Users\chhn\AppData\Local\Continuum\anaconda3\Library\bin;C:\Users\chhn\AppData\Local\Continuum\anaconda3\Scripts;C:\Users\chhn\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\chhn\AppData\Local\Programs\Python\Python36\;C:\Users\chhn\AppData\Local\Microsoft\WindowsApps;C:\Users\chhn\AppData\Local\atom\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\
    SET PYTHON_BIN_PATH=C:/Users/chhn/AppData/Local/Continuum/anaconda3/python.exe
    SET PYTHON_LIB_PATH=C:/Users/chhn/AppData/Local/Continuum/anaconda3/lib/site-packages
    SET TF_DOWNLOAD_CLANG=0
    SET TF_NEED_CUDA=0
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
  C:/msys64/usr/bin/bash.exe bazel-out/x64_windows-opt/genfiles/tensorflow/tf_python_api_gen_v1.genrule_script.sh
Execution platform: @bazel_tools//platforms:host_platform
Traceback (most recent call last):
  File "\\?\C:\Users\chhn\AppData\Local\Temp\Bazel.runfiles_tdaftpim\runfiles\org_tensorflow\tensorflow\python\tools\api\generator\create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "\\?\C:\Users\chhn\AppData\Local\Temp\Bazel.runfiles_tdaftpim\runfiles\org_tensorflow\tensorflow\python\__init__.py", line 82, in <module>
    from tensorflow.python import keras
  File "\\?\C:\Users\chhn\AppData\Local\Temp\Bazel.runfiles_tdaftpim\runfiles\org_tensorflow\tensorflow\python\keras\__init__.py", line 30, in <module>
    from tensorflow.python.keras import datasets
  File "\\?\C:\Users\chhn\AppData\Local\Temp\Bazel.runfiles_tdaftpim\runfiles\org_tensorflow\tensorflow\python\keras\datasets\__init__.py", line 25, in <module>
    from tensorflow.python.keras.datasets import imdb
  File "\\?\C:\Users\chhn\AppData\Local\Temp\Bazel.runfiles_tdaftpim\runfiles\org_tensorflow\tensorflow\python\keras\datasets\imdb.py", line 25, in <module>
    from tensorflow.python.keras.preprocessing.sequence import _remove_long_seq
  File "\\?\C:\Users\chhn\AppData\Local\Temp\Bazel.runfiles_tdaftpim\runfiles\org_tensorflow\tensorflow\python\keras\preprocessing\__init__.py", line 21, in <module>
    import keras_preprocessing
ModuleNotFoundError: No module named 'keras_preprocessing'
Target //tensorflow/contrib/model_pruning:strip_pruning_vars failed to build
INFO: Elapsed time: 11384.874s, Critical Path: 670.48s
INFO: 4219 processes: 4219 local.
FAILED: Build did NOT complete successfully

**Comment by laszlocsomor** [comment]
That looks good, Bazel is working fine. The build fails because of a missing Python module. Make sure you have all the required pip modules installed.
