### ISSUE TITLE
incompatible_disallow_native_in_build_file: Forbid native module in BUILD files

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#7513]
The [native](https://docs.bazel.build/versions/master/skylark/lib/native.html) module was created to access BUILD file functions in bzl files.

The native module has been exposed by accident to BUILD files. We are going to remove it from BUILD files, and keep it only in bzl files.
Fixing the issue should be trivial, e.g.

```diff
- native.cc_library(
+ cc_library(
```

```diff
-    srcs = native.glob(["*.java"])
+    srcs = glob(["*.java"])
```

The fix is mechanical, it can be [fixed automatically](https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#native-build) using:
  `buildifier --lint=fix file.bzl`

**Comment by katre** [comment]
I am assuming the migration window is one release: if this is not the case please let me know.
