### ISSUE TITLE
Add Starlark support for Symlink actions.

### ISSUE THREAD

**Issue by sergiocampama** [bazelbuild/bazel#7514]
### Description of the problem / feature request:

There are multiple benefits for using symlinks in certain actions, especially when creating directory structures or renaming artifacts' basenames. For example, rules_apple requires heavy usage of [symlinks](https://github.com/bazelbuild/rules_apple/blob/0a9df881d57288f54a1c571fc822f9b275e574ba/apple/bundling/file_actions.bzl).

Given that symlinks are a core foundation of how Bazel works, Starlark should provide an API to register symlink actions, that work both on macOS, Linux and Windows. In native code this already exists, through the [`SymlinkAction`](https://github.com/bazelbuild/bazel/blob/da74aa058422c3b9e32e4b86b17c3a264521a926/src/main/java/com/google/devtools/build/lib/analysis/actions/SymlinkAction.java) class.  

This could be added to the `actions` interface, something like `ctx.actions.symlink(src, dest)` where both `src` and `dest` are `File` instances created through `ctx.actions.declare_file`, for example. Notice that `File`instances can also represent tree artifacts.

**Comment by laurentlb** [comment]
@Yannic, thanks for the pull request!

Can you briefly clarify your plans? Do you plan to do followup changes after #10695?

**Comment by Yannic** [comment]
@laurentlb I'm planning to investigate allowing symlinks to executables (it's unclear how dangling symlinks interact with them and I don't want to commit to an API yet), and to allow specifying a progress message for these actions (actually, it's not large change so I guess I'll just do it as part of #10695). That said, #10695 can be used by rule authors to create symlinks without any follow-ups.

**Comment by Yannic** [comment]
I think this is implemented and can be closed?

**Comment by pauldraper** [comment]
Yep.

https://docs.bazel.build/versions/master/skylark/lib/actions.html#declare_symlink

https://docs.bazel.build/versions/master/skylark/lib/actions.html#symlink

**Comment by thiagohmcruz** [comment]
Got here while reading some things about `ctx.actions.symlink`, jump bump-ing that apparently this can be closed 👍

**Comment by brandjon** [comment]
Thanks, closing.
