### ISSUE TITLE
bazel coverage crashes, likely due to old jacoco

### ISSUE THREAD

**Issue by dhalperi** [bazelbuild/bazel#7517]
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`bazel coverage //projects/batfish-common-protocol/...` crashes in https://github.com/batfish/batfish/

The stack trace includes the following

```
91) testGetPartialMatchesSpecifierComplete(org.batfish.specifier.parboiled.ParserUtilsTest)
java.lang.IllegalAccessError: tried to access method org.batfish.specifier.parboiled.CommonParser.$jacocoInit()[Z from class org.batfish.specifier.parboiled.TestParser$$parboiled
	at org.batfish.specifier.parboiled.TestParser$$parboiled.input(Unknown Source)
	at org.batfish.specifier.parboiled.ParserUtilsTest.getRunner(ParserUtilsTest.java:25)
	at org.batfish.specifier.parboiled.ParserUtilsTest.testGetPartialMatchesSpecifierComplete(ParserUtilsTest.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

which it looks like has been fixed by jacoco 0.7.8.

### What operating system are you running Bazel on?

macOS 10.14.3

### What's the output of `bazel info release`?

development version

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

built from bazel head using `bazel build //src:bazel && cp -f bazel-bin/src/bazel`

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
git@github.com:bazelbuild/bazel.git
2a1d99076eb46510484bd0bcbee0c607c03d4943
2a1d99076eb46510484bd0bcbee0c607c03d4943
```

###  Have you found anything relevant by searching the web?

Yes.

* JaCoCo reports having fixed this issue in the 0.7.8 release notes. https://github.com/jacoco/jacoco/releases/tag/v0.7.8

* I also came across this related Bazel issue filed by Android team:  https://github.com/bazelbuild/bazel/issues/3471

    But that issue was apparently triaged in such a way that it was decided coverage/bazel were unimplicated and instead Android team should apply a workaround. I saw no discussion of whether Bazel can upgrade or why/why not, so I'm hoping there will be new discussion here.

    As it's a third-party library causing the issue in our case, we're not able to apply the same workaround.

cc: @iirina

**Comment by dhalperi** [comment]
I notice that Bazel already uses ASM 7.0, which is the main dep of jacoco. Maybe upgrading wouldn't be a huge yak shafe?

**Comment by dhalperi** [comment]
I've tried modifying Bazel to upgrade the jar myself, locally, but there's one jar I can't figure out how it was created: https://github.com/bazelbuild/bazel/tree/master/third_party/java/jacoco , `jacocoagent.jar`. It was checked in with the rest, but does not seem to correspond to any of the rest.

**Comment by dhalperi** [comment]
Any update? I'd like to get coverage working, its one of the key blockers to switching.

**Comment by Ubehebe** [comment]
Thanks for the report, @dhalperi. I'm running into the same problem. I believe this completely breaks `bazel coverage` when used with jdk9+ due to https://github.com/jacoco/jacoco/pull/434.

**Comment by iirina** [comment]
I'll try to update tomorrow to jacoco 0.8.3.

**Comment by dhalperi** [comment]
Thank you @iirina !

Is this still a recommended command to look at the code coverage output?

```
bazel coverage //... \
--combined_report=lcov --test_keep_going \
--coverage_report_generator=@bazel_tools//tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator:Main \
&& genhtml -o coverage bazel-out/_coverage/_coverage_report.dat && open coverage/index.html
```

(Still getting a ton of crashes, but elsewhere.)

**Comment by iirina** [comment]
@dhalperi Yes, that's right. Can you please open new issues for the other crashes? Thanks!

**Comment by dhalperi** [comment]
@iirina - will open other issues, if they are in Bazel. May well be in other libraries not working with java11 now. Just making sure I'm on good footing. Thanks again!
