### ISSUE TITLE
0.1.2 and JDK7

### ISSUE THREAD

**Issue by JonBoyle87** [bazelbuild/bazel#752]
On the release of 0.1.2, you have release downloads for linux  from https://github.com/bazelbuild/bazel/releases (specifically bazel_0.1.2-jdk7-linux-x86_64.deb) that specifies jdk7 in the name; however, the deb looks for openjdk-8-jdk openjdk-8-source. 

Am I misunderstanding something, or is something wrong with the deb?

**Comment by philwo** [comment]
Sounds like a P1 to me (it probably means the package is not usable on systems that don't have JDK8, however those systems are the intended users of the package)

@damienmg - please lower the priority if I judged it wrong.

**Comment by damienmg** [comment]
The priority is probably not P1 but only because JDK7 support is not rated high. Anyway the fix should not be too hard but it won't be fixed before 0.1.3 I think (I will re-emit a rc later today with a P1 fix and this one).

**Comment by damienmg** [comment]
Not that you should be able to test the change with the current rc:
https://storage.googleapis.com/bazel/0.1.3/rc3/index.html
