### ISSUE TITLE
bazel 0.23.0rc3: git_repository not working with https URL

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/bazel#7522]
Just tried Bazel 0.23.0rc3 ( #6495 )  on Linux with git `2.20.1`.

Seems like there was a change to `git_repository` behavior...
Previously this would work for us:
```python
git_repository(
    name = "io_bazel_rules_appengine",
    remote = "https://github.com/bazelbuild/rules_appengine",
    remote = "git@github.com:bazelbuild/rules_appengine.git",
    commit = "f6a099e3c07672438768183578192d56d46fef80",
)
```

Now it will result in error:
```
17:55:00  + git clone https://github.com/bazelbuild/rules_appengine /home/builduser/.cache/bazel/_bazel_builduser/d95f300509f1e228190b211abeba17c4/external/io_bazel_rules_appengine
17:55:00  Cloning into '/home/builduser/.cache/bazel/_bazel_builduser/d95f300509f1e228190b211abeba17c4/external/io_bazel_rules_appengine'...
17:55:00  warning: templates not found in /tmp/git/share/git-core/templates
17:55:00  fatal: unable to find remote helper for 'https'
```
Had to change the git URL to `git@github.com:bazelbuild/rules_appengine.git` and then it worked.

Is it a known declared change?

**Comment by aehlig** [comment]
> Is it a known declared change?

None that I'm aware of.  Also, the definition of the `git_repository` rule hasn't changed since the last release and commands executed by a repository rule are not sandboxed.

Also note that  the error message was generated by `git`. Does `git clone https://github.com/bazelbuild/rules_appengine` work when called directly (i.e., outside `bazel`)?

**Comment by gertvdijk** [comment]
@or-shachar 
That git error message looks completely unrelated to Bazel indeed and points to a problem with your local git installation (google it).

**Comment by irengrig** [comment]
@or-shachar, have you been able to resolve the problem? Is that appears to be the problem on the Git side?
Thank you.

**Comment by or-shachar** [comment]
@irengrig I resolved by setting the right git url... Not sure why it worked beforehand with the wrong format. But I guess it's for the best that it failed.
