### ISSUE TITLE
how to get external dependencies WORKSPACE file

### ISSUE THREAD

**Issue by hellozmz** [bazelbuild/bazel#7523]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:
I want to get the  external dependencies WORKSPACE file, how could I do? Please help me.

### Feature requests: what underlying problem are you trying to solve with this feature?
transtive dependencies WORKSPACE include some lib in version A, local WORKSPACE include those lib in version B, so I want to find how many libs are in different version.

### What operating system are you running Bazel on?
centos

### What's the output of `bazel info release`?
0.18

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/2757

**Comment by dslomov** [comment]
Transitive workspaces are not supported (yet) - see #2757.
One way to see which versions of external dependencies a project uses is [`bazel sync` command](https://blog.bazel.build/2018/07/09/bazel-sync-and-resolved-file.html). /cc @aehlig
