### ISSUE TITLE
CppLinkActionTest#testCompilesTestSourcesIntoDynamicLibrary should be enabled on windows

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#7524]
This test was disabled on windows in times when running an unit test on a platform used that platform's C++ toolchain. So running this test on Windows used Windows toolchain. This test didn't work with Windows toolchain. I'm changing this now so all unit tests share the same setup, and the test still fails, so I'm keeping it disabled. Please fix.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
