### ISSUE TITLE
Feature request: custom options for lcov tool

### ISSUE THREAD

**Issue by pylipp** [bazelbuild/bazel#7525]
### Description of the problem / feature request:

Pass options to `lcov` tool

### Feature requests: what underlying problem are you trying to solve with this feature?

I want to specify a custom configuration for `lcov` using its `--config-file` command line option. (I could put the configuration to /etc/lcovrc or ~/.lcovrc but I don't want to modify the file structure for testing/coverage collection). This should be extensible to any `lcov` option. 

### What operating system are you running Bazel on?

Linux (Ubuntu 16.04)

### What's the output of `bazel info release`?

release 0.18.0

###  Have you found anything relevant by searching the web?

The `lcov` man pages:
http://ltp.sourceforge.net/coverage/lcov/lcovrc.5.php
http://ltp.sourceforge.net/coverage/lcov/lcov.1.php

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
