### ISSUE TITLE
bazel coverage: "Coverage runner: cannot locate file"

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/bazel#7529]
### Description of the problem / feature request:

Generating a test coverage report fails with the error above. It looks like this is the code
https://github.com/bazelbuild/bazel/blob/master/tools/test/collect_coverage.sh#L68
and LCOV_MERGER is empty. Running `bazel coverage --combined_report=lcov //...` does not help, since it leads to #6450.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
git clone https://github.com/googlecloudrobotics/core.git
cd core
bazel coverage //...
```

### What operating system are you running Bazel on?

linux (debian)

### What's the output of `bazel info release`?

release 0.22.0

###  Have you found anything relevant by searching the web?

Nothing on Stackoverflow/Github issues.

**Comment by ensonic** [comment]
Is something failing to pass the LcovMerger to the env? It looks like this was added here:
https://github.com/werkt/bazel/commit/b00c8e7f23371137930952ad10b098ecc37aedc5

**Comment by iirina** [comment]
@ensonic what rule sets do you use? Only the rules embedded by Bazel and that allow coverage collection (Java, C++, shell) have an attribute defined named `$lcov_merger`. For custom rules the owners have to also define this attribute.

**Comment by ensonic** [comment]
I just run it against the top of the project, so there is at least python and go. I understand that coverage report is not 100%, but it would be nice to find a better failure mode.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
