### ISSUE TITLE
Using Bazel with Android Studio

### ISSUE THREAD

**Issue by droidekas** [bazelbuild/bazel#754]
Is there a way to use Bazel with android studio?

**Comment by philwo** [comment]
I don't think so, but Dmitry is working on IDE integration and might have a status update.

**Comment by winterDroid** [comment]
:+1:

**Comment by bashbeik** [comment]
Yes would be great to use with an IDE

**Comment by davidzchen** [comment]
+cc @dslomov

**Comment by jvmvik** [comment]
+1

**Comment by martianmartin** [comment]
+1

**Comment by linggom** [comment]
+1

**Comment by jdc2172** [comment]
+1

**Comment by winterDroid** [comment]
I guess https://github.com/bazelbuild/intellij fixes this, doesn't it?

**Comment by damienmg** [comment]
Yes indeed.

**Comment by damienmg** [comment]
Closing this one, please file issues to https://github.com/bazelbuild/intellij/issues if you have any problem with the plugin

**Comment by dslomov** [comment]
Actually closing
