### ISSUE TITLE
Builds on buildkite are hanging on remote-cache after 0.23

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#7555]
All the builds (e.g. presubmits) on Buildkite are hanging sith 'remote-cache' status with Bazel 0.23 ([example](https://buildkite.com/bazel/bazel-bazel/builds/6945#bef7fa8e-a6e6-435d-89c8-7b874903273d)). I see hangs on [mac](https://buildkite.com/bazel/bazel-bazel/builds/6945#316e0668-982f-43c3-9fd0-0372870bb430) and [windows](https://buildkite.com/bazel/bazel-bazel/builds/6950#09da69c2-766f-4d28-b523-1b84cbe36dc8) as well.

Builds with 0.22 are still passing ([example](https://buildkite.com/bazel/bazel-bazel/builds/6945#16b66e29-ccd5-4e83-b5f1-1bc132d96598)).

Testing 0.23rc3 with downstream (which include bazel and its tests) was [green](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/821).

**Comment by hlopko** [comment]
CC @laurentlb @fweikert @meisterT @buchgr

**Comment by hlopko** [comment]
It seems like all the hangs are on the C++ actions.

**Comment by hlopko** [comment]
I'm trying whether disabling remote cache (https://github.com/bazelbuild/continuous-integration/commit/c6131a7a3a857f2adff1413857b121d3c38c53fa) will help. I will now cancel some hanging builds to make workers available.

**Comment by meisterT** [comment]
It seems that downloading from remote never gives a timeout for the affected actions. Is https://github.com/bazelbuild/bazel/commit/285c03e5e60b31cd4a73a707f47fabab6688ae96#diff-b1b932f73f8ce938510d06b752945cb1 related?

What's special about the C++ actions? Do they produce larger artifacts?

**Comment by hlopko** [comment]
I disabled remote cache on the ci, queued builds are now running, presubmits should be working. I'm not sure mac presubmits will finish in under 1 hour without remote cache though.

**Comment by hlopko** [comment]
They don't produce large artifacts. They are not spawn actions, so maybe they behave in a non standard way. Or it's a red herring.

**Comment by meteorcloudy** [comment]
Hmm,, I couldn't reproduce the failure on Ubuntu 1404 in a docker running on a CI Linux slave.

**Comment by meteorcloudy** [comment]
It is not always failing with 0.23.0, for example in one presubmit:
https://buildkite.com/bazel/bazel-bazel-github-presubmit/builds/1833#_

**Comment by hlopko** [comment]
Hmm, that could mean it was a temporary GCS outage and all is fine now...

**Comment by meisterT** [comment]
Well, it should still not hang forever but run into a timeout.

**Comment by hlopko** [comment]
Absolutely.

**Comment by meteorcloudy** [comment]
But this bug might also exists in previous versions? So maybe not a regression.

**Comment by buchgr** [comment]
It seems to work fine again on testing pipelines. I ll re-enable remote caching for presubmits again.

> Hmm, that could mean it was a temporary GCS outage and all is fine now...
The reason it can't really be a GCS outage is that mac presubmits don't use GCS.

**Comment by buchgr** [comment]
As of now, I see no reason for a patch release because I don't know what exactly the bug is. I was not able to reproduce it.

**Comment by meteorcloudy** [comment]
I found a way to reproduce the hanging symptom (probably it's the same bug)

1. First build a project with remote cache flag,
2. Bazel clean
3. Build without remote cache flag

Then the actions will still try to use remote caching but end up hanging.

**Comment by buchgr** [comment]
@laurentlb this will need a patch release. I am sending out a fix and will update this bug once submitted
