### ISSUE TITLE
Header file mapping

### ISSUE THREAD

**Issue by njlr** [bazelbuild/bazel#7568]
### Description of the ~~problem~~ / feature request:

Sometimes the include paths I want to use in my code do not match up to the folder structure on disk. 

I would like to be able to specify a _map_, rather than a _list_, of headers to `cc_library`. 

### Feature requests: what underlying problem are you trying to solve with this feature?

Suppose I have this folder structure like this:

```bash
$ tree . 
.
├── foo.cpp
├── foo
│   └── baz.hpp
└── qux
    └── waldo.hpp

2 directories, 3 files
```

But `foo.cpp` looks like this: 

```c++
#include "bar/baz.hpp" // alias for foo/baz.hpp
#include "xyz.hpp"     // alias for qux/waldo.hpp

int foo() {
  return 0;
}
```

Then the most natural way for me to specify headers would be a map: 

```c++
cc_library(
  name = "app",
  srcs = [
      "foo.cpp",
  ],
  hdrs = {
    "bar/baz.hpp": "foo/baz.hpp",
    "xyz.hpp": "qux/waldo.hpp"
  },
)
```

The L.H.S of the map would be the path you use to include the header. The R.H.S of the map would be a label. 

However, Bazel only seems to support lists. 

Note that `include_prefix` and `strip_include_prefix` are a less general (and perhaps less intuitive) version of a map. 

It would also be useful to add a `private_hdrs` attribute so that this can be done for private headers in `cc_library` and `cc_binary`. 

-----------------------

UPDATE: The existing private headers implementation via `srcs` could not support header maps because it serves the additional function as the list of cpp files.

**Comment by hlopko** [comment]
Related, @scentini is working on https://github.com/bazelbuild/bazel/issues/6790 which will make `includes` like attributes cover more use cases. 

It seems to me that maps assume you want to 'quote' include the header, what do I do if I want to '<>' include the header, or I want/have to allow users of my library to use both?

How often does it happen in practice that multiple headers are included in different directories? I assumed the common case is all headers are together in a single (or 2) directories (such as "headers", or "include", or "private"), so 'includes' like attributes are less overhead than having to deal with each header separately. I extrapolate this from our internal situation - we have thousands third_party libraries (not all C++) and `includes` seems to work better than maps would, especially since often times headers are globbed. What do you think?

**Comment by njlr** [comment]
> It seems to me that maps assume you want to 'quote' include the header, what do I do if I want to '<>' include the header, or I want/have to allow users of my library to use both?

The header maps could be made to work with either 'quote'  or '<>', depending on the use-case. This seems orthogonal to me. 

> How often does it happen in practice that multiple headers are included in different directories?

It is not the most common case, but it does happen. To drive Bazel adoption, it is important that people do not need to change their source-code, even if the layout is a bit crazy! 

> includes seems to work better than maps would, especially since often times headers are globbed.

You would be able to build the map with globs. Buck uses [this function](https://github.com/facebook/buck/issues/1963#issuecomment-404344676) to generate a map from globs and directories. 

For example, suppose we had this layout: 

```bash
$ tree .
.
└── include
    ├── foo
    │   ├── bar
    │   │   └── bar.hpp
    │   └── foo.hpp
    └── qux
        └── qux.hpp

4 directories, 3 files
```

And we wanted a header map (dict) like so: 

```python
{
  'foo/foo.hpp': 'include/foo/foo.hpp',
  'foo/bar/bar.hpp': 'include/foo/bar/bar.hpp',
  'qux/qux.hpp': 'include/qux/qux.hpp',
}
```

Then we could use `subdir_glob` like this: 

```python
headers = subdir_glob([
  ('include', '**/*.hpp'),
])
```

This gives us all of the benefits of globbing and the fine-control of a map, where required.

**Comment by njlr** [comment]
It also appears that `cc_binary` does not support the `strip_include_prefix` / `include_prefix` pair, so include paths are particularly awkward here.

**Comment by njlr** [comment]
https://github.com/bazelbuild/bazel/issues/4463

**Comment by njlr** [comment]
Related question from a Bazel user on SO: https://stackoverflow.com/questions/50662996/bazel-how-to-glob-headers-into-one-include-path

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
