### ISSUE TITLE
External dependency cannot see main project files through CROSSTOOL includes

### ISSUE THREAD

**Issue by deeglaze** [bazelbuild/bazel#7570]
### Description of the problem / feature request:

The Asylo project defines some POSIX and system headers since it's compiling for an OS-less environment. Our CROSSTOOL has been inserting include paths that point to our include directories, but with the default value of --incompatible_remap_main_repo switched to true, these paths no longer exist. What is the expected solution that isn't just --incompatible_remap_main_repo=false?

Context:
https://github.com/google/asylo/blob/master/asylo/distrib/sgx_x86_64/CROSSTOOL.tpl#L49

**Comment by dkelmer** [comment]
I'm sorry, I don't know too much about CROSSTOOL. But the flag definitely shouldn't be changing the _existence_ of paths. What do you mean by "the paths no longer exist"? What are the errors you're seeing? How are you setting up this external repository? The most helpful thing would be if you have a minimal repro so that I can investigate.

**Comment by deeglaze** [comment]
I don't really have a simple repro because I try to not fuss with CROSSTOOL changes.

```shell
git clone github.com/google/asylo.git
cd asylo/distrib/sgx_x86_64
mkdir -p /opt/asylo/toolchains
./install_toolchain --user
# FAILS
bazel build --config=sgx-sim @boringssl//:crypto
# SUCCEEDS
bazel build --config=sgx-sim --incompatible_remap_main_repo=false @boringssl//:crypto
```

The toolchain BUILD file gets its files from @com_google_asylo//..., and the CROSSTOOL file inserts flags to allow implicit includes from external/com_google_asylo/... in order for headers to resolve during builds. This flag appears to make the main repo no longer appear in external, which causes problems when I build targets in dependencies that have their own workspace name.

**Comment by dkelmer** [comment]
I'm getting this error from the install step:

```
$ ./install-toolchain --user
getopt: illegal option -- o
grep: /proc/cpuinfo: No such file or directory
mkdir: /opt/asylo/toolchains/sgx_x86_64: Permission denied
$ sudo ./install-toolchain --user
getopt: illegal option -- o
grep: /proc/cpuinfo: No such file or directory
Missing supporting tool to fetch dependencies: wget
```

**Comment by dkelmer** [comment]
Those paths still exist at `asylo/platform/posix/include`. Could you change the CROSSTOOL to have:
`compiler_flag: "-isystemasylo/platform/posix/include"`?

**Comment by deeglaze** [comment]
Ah, I did that, but not to all the toolchain entries in the CROSSTOOL file. I missed some. That did solve the issue. Thanks!
