### ISSUE TITLE
Relative target paths and files should be resolved against package_path

### ISSUE THREAD

**Issue by ovy** [bazelbuild/bazel#7571]
### Description of the problem / feature request:

I am trying to merge two existing source trees into a single workspace using package_path.  Similar to https://www.kchodorow.com/blog/2015/12/08/combining-projects-without-converting-to-a-monorepo/  , but the two trees will not have their own WORKSPACE files, as the shared external deps would make it nightmarish.

I am putting a WORKSPACE file above the two and using `package_path=%workspace%/src1:%worskpace%/src2`  to "union" them (it's important that package paths inside BUILD files stay as they are and do not include `src1` and `src2`).

```  shell
(root)/
  WORKSPACE
  .bazelrc            # with package_paths to src1/ and src2/
  src1/
      spaghetti/
          BUILD       # want accessible as //spaghetti
  src2/
      meatballs/
          BUILD       # want accessible as //meatballs
```

This mostly works, except that I am unable to use relative target names OR query files by path (unless, uncommonly, I refer to the files with a //path).  All paths used must be absolute.

In a sample repository ([Google Drive Link](https://drive.google.com/file/d/1dJ-dBPAeHyBM0VSi7NH468HIAOZboR--/view?usp=sharing) )  with naming based on the blog post:

``` shell
(bazel_package_path/src1/spaghetti) $  bazel build //spaghetti:spaghetti
Target //spaghetti:spaghetti up-to-date:
  bazel-bin/spaghetti/spaghetti

(bazel_package_path/src1/spaghetti) $ bazel build :spaghetti 
ERROR: Skipping ':spaghetti': no such package 'src1/spaghetti': BUILD file not found on package path

(bazel_package_path/src1/spaghetti) $ bazel query //spaghetti:spaghetti.sh  --output=package
spaghetti

(bazel_package_path/src1/spaghetti) $ bazel query spaghetti.sh
ERROR: couldn't determine target from filename 'src1/spaghetti/spaghetti.sh'
```

I *could* put `:%workspace%` as a third package_path, where building `:spaghetti` would *seem* to work, but it builds the wrong target path `//src1/spaghetti:spaghetti` rather than `//spaghetti`.  As you probably know, having two ways to refer to the same target is a terrible idea, e.g. a `cc_library` will have different `#include` paths in one vs the other.

For the same reason though, fixing this might be semantically simple, as we don't need to carefully ponder which of two possible package_paths to consider as root:   structures with multiple paths to the same target are probably unworkable in Blaze anyway.  We should pick the first, the same way that BUILD-finding does it.

I am on the fence on whether to consider this a feature request or a bug. It stands to reason that if a package path gets resolved to a specific filesystem path (file or directory), the reverse should also work.  Let's say, this one is a case that probably hasn't been considered: a filesystem path that *is* above a workspace so it can be reasoned about, but in a package path that *is not* `%workspace%`.

Also note that I am in no way asking for nested workspaces, just a way to merge them. I would also be willing to put WORKSPACE under one of the trees (e.g. `src1`), although it's a little less elegant than the parent, if that didn't prevent me from using blaze from `src2` entirely. e.g. if there was a WORKSPACE.redirect asking `src2` to build in `src1`. Of course, that would still have the problem of paths from `src2` not resolving vs `package_path`.

### Feature requests: what underlying problem are you trying to solve with this feature?

Merging two workspaces, where I have no need for the individual workspaces, but git structure prevents me from using the same root for the foreseeable future. It is also infeasible to do a filesystem union of the two.

### What operating system are you running Bazel on?

Tried on Linux and Mac.

### What's the output of `bazel info release`?

`release 0.23.0`.   Also tried with `release 0.22.0`.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Installed from the releases page.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Did not use git bazel

###  Have you found anything relevant by searching the web?

Nope 

### Any other information, logs, or outputs that you want to share?

Hopefully this is clear enough. Reposting sample tree link:   https://drive.google.com/file/d/1dJ-dBPAeHyBM0VSi7NH468HIAOZboR--/view?usp=sharing

**Comment by dslomov** [comment]
We do not really support package_paths pointing inside the workspace...
Thu bug here is that we do not report an error for this.

**Comment by ovy** [comment]
@dslomov: well, can we support it then?

As far as I understand it, two things will never work without a dominating WORKSPACE file:
* Running bazel from inside a package_path'd directory
* Any filesystem path references (relative OR filesystem-absolute) in e.g. query

Without these, we are reducing the usefulness of `package_path` to only the "other workspaces" use case, unnecessarily so IMHO because the semantics can be made clean. Nothing in the documentation suggests that this limitation is intended.

To elaborate on semantics: if you're concerned about multiple paths to the same package, this isn't a new problem, as package_path can create duplicate paths when outside the workspace just as well. So it has to be handled to some degree.  The semantic rule that "the Bazel path for a given fs path is based on the first package_path that is a parent" is intuitive and matches the existing lookup rule in the other direction: "the fs path for a given Bazel package is based on the first package_path root where the Bazel package exists as a subpath".

How else can I union two trees while making the above operations work?  There isn't any other way to control the workspace dir that I'm aware of.

**Comment by ovy** [comment]
@dslomov : alternatively, should I close this and ask for a means to point a source directory to another workspace that is not a parent?  To provide a means of `pwd` resolution (i.e. the meaning of relative paths) in repo union scenarios.

Sketch:
1.  Workspace resolution:
   * When looking for a dominating WORKSPACE[.bazel], also allow for a `WORKSPACE.real` symlink to a WORKSPACE file in a different directory. From then on, `workspace` points to the directory of the link target. The `.real` suffix distinguishes between this and the current behaviour of a symlinked WORKSPACE, which keeps the directory unchanged.
    *OR*
   * WORKSPACE may contain a single declaration `worskpace([name=optional], location="../src1")`. The rest of the file is ignored and `workspace` points to that location henceforth. This has the benefit of not introducing another file name.

In both variants above, there are no implications about `package_path`. The workspace directory should probably contain a .bazelrc that adds the non-workspace-parented directory as a `package_path`.

 **_AND_**

2. `pwd` resolution when started inside the non-workspace-parented directory:
   * The Bazel path of the current directory is computed relative to the `WORKSPACE[.real]` redirector above, not the actual workspace directory.
   *OR*
   * The Bazel path of the current directory is based on a `package_path` entry that contains it (present feature request, but without allowing it to be contained inside the workspace)

I'd be almost as happy with this solution (designating `src1` in my scenario as the workspace directory) as with the common parent.

**Comment by katre** [comment]
Closed for lack of activity. Please ping the reviewers to reopen if this is still a problem.
