### ISSUE TITLE
Release 0.23.1

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#7573]
Bazel 0.23.1 will be built on top of 0.23.0 (https://github.com/bazelbuild/bazel/issues/6495).

There's one cherrypick request so far:
> this needs to be cherry picked into a patch release [f0a1597](https://github.com/bazelbuild/bazel/commit/f0a1597cca2252754daf1d53ff76cf1a9b3dd9b9) to fix #7555.

I plan to create the candidate tomorrow.

**Comment by laurentlb** [comment]
Candidate created with:
`scripts/release/release.sh create 0.23.1` 441fd75d0047f8a998d784c557736ab9075db893 6ca7763669728253606578a56a205bca3ea883e9 2310b1c2c8b2f32db238f667747e7d5672480f4a f9eb1b56706f91063e9d080b850fa56964e77324 f0a1597cca2252754daf1d53ff76cf1a9b3dd9b9

Available here: https://releases.bazel.build/0.23.1/rc1/index.html

**Comment by meteorcloudy** [comment]
Running a downstream test for 0.23.1 at https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/833

**Comment by laurentlb** [comment]
Bazel 0.23.1 released. https://github.com/bazelbuild/bazel/releases/tag/0.23.1

It contains a single change on top of Bazel 0.23.0 to fix an issue with remote caching.

cc @vbatts @petemounce @excitoon

**Comment by vbatts** [comment]
Fedora and Centos build is kicked-off
https://copr.fedorainfracloud.org/coprs/build/864426

**Comment by excitoon** [comment]
Scoop package is in place:
https://github.com/lukesampson/scoop/commit/18af048d5fea0f5e178fe407be785ee056f6fa23
Turned out they have some automatic tooling which consumes GitHub releases and rolls out the package, so I shall just check everything is fine.

**Comment by petemounce** [comment]
Published to chocolatey.

**Comment by nlopezgi** [comment]
container with Bazel 0.23.1 published to gcr.io/cloud-marketplace/google/bazel
