### ISSUE TITLE
`implies: ...` does not stack well with `static_link_msvcrt`

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#7578]
### Description of the problem / feature request:

Hi. I can not enable `static_link_msvcrt` from another feature:

```
    imply_static_link_msvcrt_feature = feature(
        name = "imply_static_link_msvcrt",
        implies = ["static_link_msvcrt"]
    )
```

When I do:
```
cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cpp"],
    features = ["imply_static_link_msvcrt"],
    linkopts = ["-DEFAULTLIB:libcmt.lib", "-WX"] # Ensuring static_link_msvcrt is enabled.
)
```
linker says that:
```
LINK : warning LNK4098: defaultlib 'msvcrt.lib' conflicts with use of other libs; use /NODEFAULTLIB:library
LINK : error LNK1218: warning treated as error; no output file generated
```

Second thing is that if I use non-existent feature, it is silently ignored by Bazel. I feel that that is not right.

See https://github.com/excitoon/bazel-issues/tree/master/imply-static-link-msvcrt

### What operating system are you running Bazel on?

Windows 10 x64

### What's the output of `bazel info release`?

Build label: 0.23.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Feb 26 17:40:30 2019 (1551202830)
Build timestamp: 1551202830
Build timestamp as int: 1551202830

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
