### ISSUE TITLE
Create "glaze" BUILD file generator for Go

### ISSUE THREAD

**Issue by aschran** [bazelbuild/bazel#758]
As described in this doc on the implementation plan for Go support for Bazel:
https://docs.google.com/document/d/1_fNIFC-2gLETPBXWipNDaZEi1NCKDJRBqGN7lF0Eo7k/view#heading=h.ukvbyrl4dbrx

> For making Bazel work with Go, we will have a tool called “glaze”, which analyzes the Go source files in a directory, and emits a BUILD file to match. Glaze must be run by hand (or, as an editor hook) when modifying Go code.

**Comment by raliste** [comment]
Please please please

**Comment by damienmg** [comment]
Issue have been transfered to the rules_go repository at bazelbuild/rules_go#15
