### ISSUE TITLE
incompatible_disable_objc_library_resources

### ISSUE THREAD

**Issue by sergiocampama** [bazelbuild/bazel#7594]
`objc_library` resource attributes are deprecated and will be removed. Refer to the Resources [guide](https://github.com/bazelbuild/rules_apple/blob/master/doc/resources.md) for more information on using resources for Apple platform targets.

In short, the following attributes are marked as deprecated:

* `asset_catalogs`
* `bundles`
* `datamodels`
* `resources`
* `storyboards`
* `strings`   
* `structured_resources`
* `xibs`

Most of these attributes can be directly moved to the `data` attribute, except the `structured_resources` ones. Please refer to the Resources guide for more information.

Expected timeline:

* released with Bazel 0.24 (March 2019), off by default
* enabled by default with Bazel 0.25 (April 2019)

**Comment by dslomov** [comment]
Please follow the guidance https://www.bazel.build/breaking-changes-guide.html for incompatible changes

**Comment by dslomov** [comment]
cc @katre - we shouldn't miss this for 0.24 labels #6968.

**Comment by katre** [comment]
@dslomov Updated, thanks for the notification.

**Comment by sergiocampama** [comment]
I'm not following the migration-0.24 and breaking-change-0.26, what about 0.25? I would like to flip it as soon as I can, could it be done in 0.25?

**Comment by katre** [comment]
The issue description says the flag will be flipped for 0.26, so that was what I chose. You can change it to 0.25 if you think all downstream projects will be migrated in time.

**Comment by sergiocampama** [comment]
I've updated it for 0.25. I'm ok with pushing for this harder deadline for our clients, if that's ok with the Bazel policy

**Comment by katre** [comment]
Labels updated.

**Comment by dkelmer** [comment]
Can this be closed @sergiocampama ?

**Comment by sergiocampama** [comment]
it's been flipped to true, but there's cleanup involved... what's the general guidance? should this be closed when the flag is removed? or when it's flipped to true?

**Comment by dkelmer** [comment]
Most people tend to close the bug when the flag is flipped (this is the only open bug with "breaking change 0.25 label which is what lead me to ask), but I don't think we actually have guidelines about this so if you want to use the bug to track the cleanup I think that makes a lot of sense :)

**Comment by dslomov** [comment]
>  I don't think we actually have guidelines about this so if you want to use the bug to track the cleanup I think that makes a lot of sense :)

We actually do: https://www.bazel.build/breaking-changes-guide.html#flipping-the-flag
When the flag is flipped to true, the corresponding incompatible-change issue should be closed.
