### ISSUE TITLE
incompatible_disallow_legacy_java_provider: Remove the old style, string-indexed Starlark ‘java’ provider

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#7598]
**Flag:** `--incompatible_disallow_legacy_java_provider`
**Available since:** 0.23 (February 2019 release)
**Will be flipped in:** 0.25 (April 2019 release)

The old style '.java' provider is removed in favor of [JavaInfo](https://docs.bazel.build/versions/master/skylark/lib/JavaInfo.html).

# Migration Notes

All Starlark usages of `.java` must be replaced by `[JavaInfo]`.

**Comment by dslomov** [comment]
Please follow the guidance at https://www.bazel.build/breaking-changes-guide.html

**Comment by lberki** [comment]
Can we put back the `breaking-change-0.25` label now that the flag is released?

**Comment by iirina** [comment]
0.25 is not a realistic estimation anymore. 0.26 is safest.

**Comment by lberki** [comment]
Even thoug there are about six weeks until the April release is released?

**Comment by iirina** [comment]
There are only 2 weeks until the first RC is cut. Do we have a policy for cherry picking flipping incompatible flags?

**Comment by lberki** [comment]
Well, let's see who breaks... unfortunately, the `migration-*` label was missing, so CI run for this flag :(

**Comment by dkelmer** [comment]
What is the status with this flag? 0.25 is being cut now. Do you want to leave breaking-change-0.26?

**Comment by dkelmer** [comment]
The instructions [here](https://github.com/bazelbuild/continuous-integration/blob/master/docs/release-playbook.md#start-new-migration-windows) say to remove the migration-ready label so I'm doing that

**Comment by dslomov** [comment]
what is the status of this in 0.26?

**Comment by hlopko** [comment]
Still not flipped. I updated labels now.

**Comment by dslomov** [comment]
Is there migration tooling available? What is the extent of the breakage?

**Comment by iirina** [comment]
Gerrit code review sent in https://gerrit-review.googlesource.com/c/gerrit/+/233678.
