### ISSUE TITLE
improve remote integration test performance

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#7602]
our integration tests take too much time during presubmits. I have collected wall clock times for each individual test case on our mac ci workers. I suppose we'll need to take at each individual test case and try to optimize it.

**test cases taking more than 10s**
test_cc_binary took 18.683032989501953s
test_cc_binary_grpc_cache took 15.883466958999634s
test_cc_binary_grpc_cache_statsline took 16.147663116455078s
test_failing_cc_test took 12.91596508026123s
test_genrule_large_output_chunking took 16.978738069533s
test_py_test took 12.938128232955933s
test_py_test_with_xml_output took 12.823876142501831s
test_failing_py_test_with_xml_output took 12.911952018737793s
test_timeout took 15.814425230026245s
test_passed_env_user took 13.359048843383789s
test_exitcode took 11.158556938171387s
test_symlinks_in_directory_cache_only took 11.301131010055542s
test_treeartifact_in_runfiles took 12.915179967880249s
test_cc_binary_http_cache took 15.427610158920288s
test_cc_binary_http_cache_bad_server took 15.333914995193481s
test_directory_artifact_skylark took 11.431648015975952s
test_directory_artifact_skylark_grpc_cache took 11.228773832321167s
test_directory_artifact_skylark_rest_cache took 11.125195980072021s
test_directory_artifact_in_runfiles_skylark_rest_cache took 14.98225712776184s

**test cases taking less than 10s**
test_cc_test took 8.390116930007935s
test_cc_test_split_xml took 6.763534784317017s
test_local_fallback_works_with_local_strategy took 8.944122791290283s
test_local_fallback_works_with_sandboxed_strategy took 8.83690094947815s
test_failed_test_outputs_not_uploaded took 6.511876106262207s
test_noinput_action took 8.765592098236084s
test_display_non_testerrors took 7.941400766372681s
test_symlinks_in_directory took 8.991476058959961s
test_refuse_to_upload_symlink took 8.612972974777222s
test_refuse_to_upload_symlink_in_directory took 8.64738392829895s
test_directory_artifact_skylark_local took 8.647170066833496s
test_genrule took 1.578629732131958s
test_genrule_can_write_to_path took 1.5175738334655762s
test_genrule_cannot_write_to_other_path took 1.5554478168487549s

@agoulti

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
