### ISSUE TITLE
error while loading shared libraries: libcloog-isl.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ksaha79** [bazelbuild/bazel#7603]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> Getting following error when trying to load "lubridate" R-package in Linux CentOS6. 
> install.packages("lubridate"); library(lubridate)
Installing package into ‘/data/home004/korak.saha/R/x86_64-redhat-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cran.cnr.berkeley.edu/src/contrib/lubridate_1.7.4.tar.gz'
Content type 'application/x-gzip' length 449850 bytes (439 KB)
==================================================
downloaded 439 KB

* installing *source* package ‘lubridate’ ...
** package ‘lubridate’ successfully unpacked and MD5 sums checked
** libs
g++ -m64 -std=gnu++0x -I"/usr/include/R" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/data/home004/korak.saha/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c RcppExports.cpp -o RcppExports.o
/data/starfs1/compilers/gcc-4.9.4/bin/gcc -std=gnu99 -I"/usr/include/R" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/data/home004/korak.saha/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c datetime.c -o datetime.o
/data/starfs1/compilers/gcc-4.9.4/bin/../libexec/gcc/x86_64-unknown-linux-gnu/4.9.4/cc1: error while loading shared libraries: libcloog-isl.so.4: cannot open shared object file: No such file or directory
make: *** [datetime.o] Error 1
ERROR: compilation failed for package ‘lubridate’
* removing ‘/data/home004/korak.saha/R/x86_64-redhat-linux-gnu-library/3.5/lubridate’

The downloaded source packages are in
	‘/tmp/RtmpcWZSil/downloaded_packages’
Warning message:
In install.packages("lubridate") :
  installation of package ‘lubridate’ had non-zero exit status

Attaching package: ‘lubridate’

The following object is masked from ‘package:base’:

    date

Also is in required to have the missing libcloog-isl.so.4 file in the /path/to/gcc-package/lib/

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

> Replace this line with your answer.

### What's the output of `bazel info release`?

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by irengrig** [comment]
Hello @ksaha79, sorry could you add more information on what are you doing with Bazel?
Can not figure out how it is related.
