### ISSUE TITLE
Upgrade //third_party/protobuf version to 3.7.0

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#7611]
Protobuf 3.7.0 was recently released: [1].

[1] https://github.com/protocolbuffers/protobuf/releases/tag/v3.7.0

**Comment by davido** [comment]
Currently, the new release cannot be built with Bazel due to the missing dependency on Error Prone Annotations library, that was fixed here: [1].

[1] https://github.com/protocolbuffers/protobuf/pull/5811

**Comment by buchgr** [comment]
Hi @davido,

I'd like to understand why you think we need to upgrade the protobuf version in Bazel?

Thanks,
Jakob

**Comment by davido** [comment]
@buchgr I already answered trhis question in my answer to @laszlocsomor why this PR: https://github.com/bazelbuild/bazel/pull/7681#issuecomment-473186729.

**Comment by meisterT** [comment]
Update to a more recent version in https://github.com/bazelbuild/bazel/commit/5e571d28eb2ea7907f29187012038cfae25bc476
