### ISSUE TITLE
improve remote test coverage

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#7614]
The remote caching and execution package has some unit and integration tests, but those seem to insufficiently cover the breath of functionality. We should revisit our tests and see which tests can be removed and which should be added. Ideally, we end up with an exhaustive test suite that's still small in order to keep it maintainable and fast.

Related #7602, #7530

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
