### ISSUE TITLE
Run using a specific Bazel version

### ISSUE THREAD

**Issue by captainIowa** [bazelbuild/bazel#7620]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

To reduce the risk of a breaking change caused by regular Bazel updates, users should have a mechanism to invoke a specific version of Bazel. Similar functionality is available in the bazelisk project via the USE_BAZEL_VERSION flag. 

### Feature requests: what underlying problem are you trying to solve with this feature?

Provide more administrative functionality for users. Always using the latest version of Bazel may have unintended consequences. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

N/A

### What operating system are you running Bazel on?

Request for all supported systems.

### What's the output of `bazel info release`?

N/A - not a bug.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A - not a bug.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A - not a bug.

###  Have you found anything relevant by searching the web?

Related project: https://github.com/philwo/bazelisk

### Any other information, logs, or outputs that you want to share?

N/A

**Comment by aiuto** [comment]
This is exactly why we have bazelisk. Selecting the version of Bazel to use is better left outside the Bazel binary itself. We may move bazalisk to a bazelbuild repo, but there are no plans to make it part of the bazel distribution.

**Comment by laszlocsomor** [comment]
https://github.com/bazelbuild/bazelisk solves this.
