### ISSUE TITLE
Why is CcLinkingContext.libraries_to_link a list rather than a depset?

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#7626]
`CcLinkingContext.libraries_to_link` is currently a flat Starlark list. The underlying storage on `CcLinkingContext`, though, is a `depset`, so `getSkylarkLibrariesToLink` is obliged to expand the nested set every time `.libraries_to_link` is used. Is there a reason for this? It seems like an unnecessary pessimization.

**Comment by oquenchil** [comment]
Hey Benjamin, what do you want to do with libraries_to_link? If you are going to propagate them downstream and merge them with other libraries to link then you can use merge() from CcInfo without flattening. If you are going to do something with libraries_to_link itself, then you will be iterating over it and flattening anyway.

Please tell us how you will use it, we are definitely looking forward to making improvements.

**Comment by benjaminp** [comment]
I realize you have to iterate it to do anything useful. Mainly, it's counter-intuitive to me that `CcLinkingContext` is not a dumb container, which is what I expect most providers to be. For example, if you write:
```
if linking_context.libraries_to_link:
    for l2l in linking_context.libraries_to_link:
        do_something(l2l)
```
a (probably large) list of libraries will be allocated twice.

**Comment by oquenchil** [comment]
https://github.com/bazelbuild/bazel/issues/8118
