### ISSUE TITLE
compile.sh prints lots of notes about deprecation or unchecked operations

### ISSUE THREAD

**Issue by ahumesky** [bazelbuild/bazel#763]
for example:

INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh build /path/to/bazel
🍃  Building Bazel from scratch............
🍃  Building Bazel with Bazel.
.Extracting Bazel installation...
......
INFO: Found 1 target...
INFO: From Building src/main/java/com/google/devtools/common/options/liboptions.jar (18 files):
Note: src/main/java/com/google/devtools/common/options/GenericTypeHelper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
INFO: From Building src/tools/android/java/com/google/devtools/build/android/ziputils/libziputils_lib.jar (12 files):
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
INFO: From Building src/tools/android/java/com/google/devtools/build/android/libandroid_builder_lib.jar (18 files):
Note: src/tools/android/java/com/google/devtools/build/android/ResourceShrinker.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
INFO: From Building src/main/java/com/google/devtools/build/skyframe/libskyframe.jar (58 files):
Note: src/main/java/com/google/devtools/build/skyframe/ReverseDepsUtilImpl.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
INFO: From Building src/main/java/com/google/devtools/build/lib/libpackages-internal.jar (91 files):
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
INFO: From Building src/main/java/com/google/devtools/build/lib/libbuild-base.jar (339 files):
Note: src/main/java/com/google/devtools/build/lib/analysis/RuleContext.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
INFO: From Building src/main/java/com/google/devtools/build/lib/query2/libquery2.jar (10 files):
Note: src/main/java/com/google/devtools/build/lib/query2/BlazeTargetAccessor.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
INFO: From Building src/main/java/com/google/devtools/build/lib/libproto-rules.jar (7 files):
Note: src/main/java/com/google/devtools/build/lib/rules/proto/ProtoCommon.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
INFO: From Building src/main/java/com/google/devtools/build/lib/query2/libquery-output.jar (10 files):
Note: src/main/java/com/google/devtools/build/lib/query2/output/QueryOutputUtils.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
INFO: From Building src/main/java/com/google/devtools/build/lib/rules/genquery/libgenquery.jar (2 files):
Note: src/main/java/com/google/devtools/build/lib/rules/genquery/GenQuery.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
INFO: From Building src/main/java/com/google/devtools/build/lib/rules/cpp/libcpp.jar (68 files):
Note: src/main/java/com/google/devtools/build/lib/rules/cpp/CppHelper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
INFO: From Building src/main/java/com/google/devtools/build/lib/libbazel-repository.jar (21 files):
Note: src/main/java/com/google/devtools/build/lib/bazel/repository/MavenJarFunction.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
INFO: From Building src/main/java/com/google/devtools/build/lib/libjava-rules.jar (56 files):
Note: src/main/java/com/google/devtools/build/lib/rules/java/JavaCompilationHelper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
INFO: From Building src/main/java/com/google/devtools/build/lib/libandroid-rules.jar (39 files):
Note: src/main/java/com/google/devtools/build/lib/rules/android/AndroidBinary.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
INFO: From Building src/main/java/com/google/devtools/build/lib/rules/objc/libobjc.jar (81 files):
Note: src/main/java/com/google/devtools/build/lib/rules/objc/IterableWrapper.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by jin** [comment]
Verified that this is not an issue anymore on 0.18.1, closing for now.
