### ISSUE TITLE
"bes upload" uploads unnecessary files

### ISSUE THREAD

**Issue by EricBurnett** [bazelbuild/bazel#7630]
### Description of the problem / feature request:

Bazel appears to attempt to upload every file referenced by BES to the CAS, even ones it just downloaded *from* the CAS. This is not harmful, but somewhat wasteful - one extra RPC per file, and at least one round-trip worth of file contents (more if the CAS implementation doesn't short-circuit `OK` blobs it already has without waiting).

![image](https://user-images.githubusercontent.com/201307/53811762-10867600-3f28-11e9-892c-d281a2c05c90.png)

Consider this an optimization request, but not super high priority.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run a remote build with BES enabled, and look at the RPCs issued.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

0.23.0

**Comment by buchgr** [comment]
Thanks for the report. I have been wanting to fix this for a while, but it's never been a high enough priority. I ll probably get to this by the end of this week, because it's a strict requirement for "Remote Builds without the Bytes".

**Comment by coeuvre** [comment]
is this still an issue?

**Comment by EricBurnett** [comment]
I have no idea. Let's call it obsolete - if it shows up again as material we can do something about it, but if either it's no longer happening, or it is but doesn't seem to be important for performance in practice, it's probably not worth spending time on.
