### ISSUE TITLE
Feature Request: Let skylark know if external is already present in repository cache

### ISSUE THREAD

**Issue by mafanasyev-tri** [bazelbuild/bazel#7635]
### Description of the problem / feature request:

At our org, we have an internal file server which requires proprietary authentication (a valid token). I would like to use a file hosted on this server as a bazel external.

The server needs to authenticate to download the file, so there is a Skylark repository rule that checks if user has a valid token (via `repository_ctx.execute`), dynamically generates download URL with token embedded, and passes it to `repository_ctx.download_and_extract`. If there is no valid token, build fails and user is prompted to re-login.

The problem is that we have no way of knowing if the file is present in repository cache or not. As a result, our build process always requires up-to-date token, even in the very common case when all files are already present in repository cache, and there is no need to hit the network at all.

We would like our repository rule to skip the URL generation if the file can be satisfied from the cache. Any of the things below would solve our problem:
- Add `repository_ctx.is_sha256_in_content_cache` function, which can check for arbitrary sha256
- Allow callbacks in `url` argument of `repository_ctx.download`. Those callbacks would be called only of file is not in the cache (or previous fetch failed), and would return an actual URL to fetch.
- Add `allow_fail` option to `repository_ctx.download` -- if set, and download cannot be completed, then it will return None/False instead of raising an error. 

### Feature requests: what underlying problem are you trying to solve with this feature?

How to write a Skylark repository rule which downloads the file, if getting file's URL is expensive.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Sample repo:
```
mkdir fetch-test
cd fetch-test
cat >WORKSPACE <<EOF
workspace(name = "fetch_test")
load("//:fetch.bzl", "fetch_slow")

fetch_slow(
    name = "test",
    sha256 = "dd47199f92452bf67b2c5d60ad4b7143554eaf2c6196ab6e8713449d81a0491d",
    url = "https://github.com/bazelbuild/bazel/releases/download/0.23.1/bazel-0.23.1-dist.zip",
)
EOF
touch BUILD
cat >fetch.bzl <<EOF
def _fetch_slow_impl(ctx):
    ctx.report_progress("Simulating long login process")
    token = ctx.execute(["sh", "-c", "sleep 30 && echo TOKEN"]).stdout.strip()

    ctx.report_progress("Actually downloading file")
    ctx.download(ctx.attr.url + "?token=" + token, "downloaded", ctx.attr.sha256, False)
    ctx.file("WORKSPACE", "workspace(name = \"{name}\")".format(name = ctx.name))
    ctx.file("BUILD", """filegroup(name = "file", srcs = ["downloaded"])""")

fetch_slow = repository_rule(
    attrs = {
        "sha256": attr.string(mandatory = True),
        "url": attr.string(mandatory = True),
    },
    implementation = _fetch_slow_impl,
)
EOF
```

Run it once, as expected it takes over 30 seconds:
```
time bazel fetch --curses=no @test//...
```
Clean it and re-fetch
```
bazel clean --expunge
time bazel fetch --curses=no @test//...
```
This time, there is nothing to download; the file was retrieved from the repository cache. However, we still spent 30 seconds trying to get a token we did not need.

### What operating system are you running Bazel on?

Ubuntu 16.04 and Ubuntu 18.04

### What's the output of `bazel info release`?

release 0.23.1- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Downloaded -dist.zip file from the releases page

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

The closed matches are is #6016 (expose cache locations to skylark), and possibly #5438 (Expose repository rule(s) ...)

### Any other information, logs, or outputs that you want to share?

We can fake it by manually reaching into external repository cache directory and checking if specified files exist. But this is pretty fragile, as there does not seem to be a reliable way to get cache location.

**Comment by dslomov** [comment]
@dkelmer @aehlig wdyt?

**Comment by aehlig** [comment]
> @dkelmer @aehlig wdyt?

I think, allowing to test whether a file is already in cache is a good idea. This issue describes a convincing use case. Moreover, there is no good reason for the asymetry between `ctx.execute` and `ctx.download`: for commands we can check for errors and react accordingly, whereas for downloads every failure is fatal and cannot be handled. So I would suggest to implement the third proposal, i.e., adding `allow_fail` to `ctx.download` and `ctx.download_and_extract`. That would also be easy to implement, but, of course, is change to the build API, albeit a backwards compatible one.

**Comment by aehlig** [comment]
Proposed implementation: https://bazel-review.googlesource.com/c/bazel/+/93594

Tomorrow, I'll also write a short document justifying the API change so that it can hopefully be approved soon.

**Comment by aehlig** [comment]
Proposal: https://github.com/bazelbuild/proposals/blob/master/designs/2019-03-21-download-failures.md

Decision to be expected on Mar 28, 2019.

**Comment by aehlig** [comment]
> Decision to be expected on Mar 28, 2019.

The respective meeting has been moved to Apr 4, 2019.

**Comment by aehlig** [comment]
The proposal was approved. Will send out the implementation for review.
