### ISSUE TITLE
When I cross compile the example  , Bazel does not produce shared libraries

### ISSUE THREAD

**Issue by darbee** [bazelbuild/bazel#7637]
When I cross compile the example using qnx ,  Bazel does not produce shared libraries. Instead, in the bazel-bin directory, there are only static libraries,(.a), not any dynamic libraries(.so). If I do not use cross compile , I can produce dynamic libraries.

**Comment by hlopko** [comment]
Oh we'll need more information than this (most of these questions are in the default issue template) to help.

1) What is the platform you're running Bazel on?
2) What version of Bazel do you run?
3) What example do you build? Can you share the full Bazel command? A repro repo?
4) What does it mean to cross-compile in your case? Which C++ toolchain do you use? What is the value of `--crosstool_top` and `--cpu` and `--compiler` Bazel options?
5) If you use Bazel's autoconfigured C++ toolchain, what compilers do you have installed, what environment variables do you set? Do you set `CC`?

**Comment by darbee** [comment]
HI sorry to reply late, I run bazel on 
1.x86_64 platform, and the 
2.  version is 0.22.0. 
3. the example is at 
      ` https://github.com/bazelbuild/examples/tree/master/cpp-tutorial/stage3`
   and I follow the instruction at 
  `https://github.com/bazelbuild/bazel/wiki/Building-with-a-custom-toolchain/581fe11cea8396ce125c879db9160d8368a5957e`
      
4. the target cpu is aarch64,  and the system is qnx
5. I find the the solution: We need add linking_mode_flags { mode: DYNAMIC } to the CROSSTOOL file

**Comment by hlopko** [comment]
5) The better solution is to add:

    feature { name: "supports_dynamic_linker" enabled: "true" }

6) A lot has changed since 0.5.3, don't use the same toolchain for both Bazel version. Have 2 separate toolchains.
7) Very soon we're flipping https://github.com/bazelbuild/rules_cc/pull/8 and https://github.com/bazelbuild/bazel/issues/7320, be sure to check out the migration instructions. Also docs on bazel.build have been updated.

Cool, glad this got resolved. Happy hacking!

**Comment by hlopko** [comment]
(edited the link to the issue)
