### ISSUE TITLE
Bootstrapping bazel fails on windows with MAX_PATH issue

### ISSUE THREAD

**Issue by asuffield** [bazelbuild/bazel#7641]
I'm bootstrapping bazel on windows, in a temporary directory which happens to be 77 bytes long.

It fails on this rule: https://source.bazel.build/bazel/+/master:src/java_tools/singlejar/java/com/google/devtools/build/singlejar/BUILD;l=82

Notably, it's the unzip command which fails, repoting "cannot create ..." for several .class files.

To the best of my knowledge, there's no version of unzip for windows that avoids the MAX_PATH probelm.

It's always tricky to prove MAX_PATH is the culprit here, but I notice that all the files that get stuck have full paths around 270 bytes long.

We'll probably want to stop relying on unzipping jars into the build area, as I can see this being a recurring issue with MAX_PATH.

**Comment by asuffield** [comment]
A bunch of debugging later, I've found what is either a workaround or an undeclared dependency.

For this to work, the version of winzip used needs to be a (vaguely recent) msys2 unzip, which rewrites file paths into the "long path" form. I had a cygwin version in the path, which does not work.

**Comment by laszlocsomor** [comment]
Thank you for debugging. I agree this is annoying.

To remedy this, the bootstrap script could:
- Improve error reporting: upon unzip failure, check each path in the zip (`unzip -l`) against the output directory.
- Create a virtual drive with `subst`. (Caveat: needs an available drive letter.)
- Check if it's running under MSYS. ([We know it won't work under Cygwin](https://github.com/bazelbuild/bazel/issues/2885).)

WDYT?

**Comment by asuffield** [comment]
Some basic checking that the right tools are available wouldn't hurt, but in this particular case, I had msys versions of bash/coreutils/etc, it was just zip and unzip that happened to be coming from cygwin elsewhere in PATH (which took a while to decipher). We could polish that some more, but...

We keep having problems with windows tools because we're relying on a poorly-defined list of non-hermetic tools being available in the path. Rather than trying to get better at doing that, probably the right answer is to stop relying on non-hermetic tools in the first place.

This bug is probably too small, I'll start an email thread about the general "shell toolchain" problem. When we have a clear story on that, slotting zip/unzip in somewhere should be straightforward.

**Comment by laszlocsomor** [comment]
I agree we need a long-term solution for shell toolchains.

Alas, it wouldn't help bootstrapping. These are raw shell scripts, not running Bazel (for the initial build).

**Comment by laszlocsomor** [comment]
I agree we need a long-term solution for shell toolchains.

Alas, it wouldn't help bootstrapping. These are raw shell scripts, not running Bazel (for the initial build).

**Comment by asuffield** [comment]
Hmm, perhaps we can do something more constrained for the bootstrapping case. Is it possible to produce a complete list of tools that get used in it, and validate that we have the correct versions of all those?

**Comment by laszlocsomor** [comment]
Yes. Bash doesn't support dry run (https://stackoverflow.com/a/19116083/7778502) so I exported PATH to /dev/null and ran `./compile.sh` to find all missing tools.

On Linux, the bootstrap scripts of 0.23.2 use:
```
basename cat gcc chmod comm cp cygpath dirname find grep ln ls mkdir mktemp unzip rm sed sort tail touch tr uname
```
