### ISSUE TITLE
Labels as `tool_path` in `CROSSTOOL`

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#7642]
Can we have a possibility to specify Labels as `tool_path` in `CROSSTOOL`'s (possibly even being compiled in the same build)? That would be a great step towards hermeticness.

E.g.:
```
  tool_path: "@some_gcc//:bin/gcc"
```

**Comment by silvergasp** [comment]
As of bazel 0.23.0 CROSSTOOL is deprecated in favour of skylark cc_toolchain and cc_common.create_cc_toolchain_config_info. See [here](https://docs.bazel.build/versions/master/tutorial/cc-toolchain-config.html). However the same problem persists in the new implementation i.e. 
```python 
tool_path(
    name = "gcc",
    path = "@some_gcc//bin:gcc",
),
```
Is not possible.

I would perhaps recommend editing the CROSSTOOL title to this issue to match the new toolchain skylark api, as it is more likely to receive support.

**Comment by silvergasp** [comment]
I am also interested in a fix or a workaround for this. I would be happy to create a more up to date descriptive issue if that were ok with you?

**Comment by excitoon** [comment]
Sure. I can not edit title from phone unfortunately.

**Comment by silvergasp** [comment]
I have added a new issue here #7746. If this doesn't cover your use case I'd keep this issue open.

**Comment by kada-zaouak** [comment]
[``](**### 

- 
#7046 

**)

**Comment by kada-zaouak** [comment]
#700#

**Comment by scentini** [comment]
cc/ @hlopko

**Comment by hlopko** [comment]
Hi all, let's continue the discussion in https://github.com/bazelbuild/bazel/issues/7746. Thanks!
