### ISSUE TITLE
Force loading C++ rules from rules_cc repo

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#7643]
This big breaking change will force users of C++ rules to use Starlark rules from [rules_cc](https://github.com/bazelbuild/rules_cc) repository. Rules there are currently only wrappers around native rules, but they will soon be rewritten.

**Comment by Yannic** [comment]
Blocking #10006

**Comment by oquenchil** [comment]
We won't do this anymore.

**Comment by aaliddell** [comment]
What changed? And does this impact other internal rules that were pending being forced external?
