### ISSUE TITLE
Support TestRunnerAction in aquery

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel#7647]
Right now we neither display command lines nor environment variables in `bazel aquery` because `TestRunnerAction` does not subclass `SpawnAction`.

We can get command lines from here:
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/exec/TestStrategy.java#L140
and the environment variables from here:
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/analysis/test/TestRunnerAction.java#L498

**Comment by finnball** [comment]
For more context, I would like to be able to find the binary how it will be executed when tested without actually running it.

As an example, if I run:

`bazel test -s //absl/algorithm:algorithm_test`

It will output:

```
(cd /home/me/.cache/bazel/_bazel_finn/465e7e526733cb116d77f110a062bc6e/execroot/com_google_absl && \
  exec env - \
  <snip> input variables </snip> \
  external/bazel_tools/tools/test/test-setup.sh absl/algorithm/algorithm_test)
```
It would be useful if there were an easy way to get this information without having to execute the test.
