### ISSUE TITLE
Bazel hangs when using cache

### ISSUE THREAD

**Issue by njlr** [bazelbuild/bazel#7652]
### Description of the problem / ~~feature request~~:

When I build _with_ an HTTP cache, Bazel will hang forever:

```bash
$ bazel build --remote_http_cache=https://my.cache.server.com //...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 5cd527ae-da38-494a-8a2d-d7bf774872a2
INFO: Analysed 757 targets (72 packages loaded, 3146 targets configured).
INFO: Found 757 targets...
[1,445 / 1,876] @bazel_tools//tools/jdk:platformclasspath; 205s linux-sandbox
```

_Note that the cache server has worked for other projects. I am only seeing this issue now with JGit._ 

When I build _without_, it succeeds in a timely manner: 

```bash
$ bazel build //...
```

I suppose there should be an extra timeout somewhere in the cache logic. 

### What operating system are you running Bazel on?

Ubuntu 18.10

### What's the output of `bazel info release`?

```bash
$ bazel info release                                                   
release 0.23.1
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```bash
$ git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
https://github.com/eclipse/jgit.git
16f75aa9da53220026603af6f564da271a9cba3f
16f75aa9da53220026603af6f564da271a9cba3f
```

**Comment by buchgr** [comment]
Have you tried setting --remote_timeout?

**Comment by katre** [comment]
Closed for lack of activity. Please ping the reviewers to reopen if this is still a problem.
