### ISSUE TITLE
Empty `__init__.py` files are being generated for repo root and runfiles root

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#7653]
This happens only for targets that are referenced by their full repo name, i.e. `@//foo:bar` or `//foo:bar`. This probably includes all external repo targets (though I have not tested that), and main repo targets when the main repo's full name is not used and when `--incompatible_remap_main_repo` is false.

See [here](https://github.com/bazelbuild/bazel/issues/7569#issuecomment-470288486) for a more detailed explanation.

The effect of this bug is that some targets have been able to get away with omitting a dependency on the top-level `__init__.py` file of their repo, provided that the `legacy_create_init` attribute is true (default). Fixing this bug may break these targets.

It's also questionable whether we should bother fixing this behavior at all, or just go ahead and deprecate automatic init creation.

**Comment by brandjon** [comment]
Note, however, that targets that have been getting away with not declaring a dependency on the top-level init file will likely break when `--incompatible_remap_main_repo` is flipped on. In fact, flipping that flag may have the side-effect of effectively fixing this bug, or at least making it inaccessible. (@dkelmer)

**Comment by eacousineau** [comment]
I think relates #3998 (for remote repos)? (along the lines of `legacy_create_init`)

**Comment by brandjon** [comment]
They're both import-related, but that bug's about name clashes between multiple things on the `PYTHONPATH`, and this is about `__init__.py` getting created in places where it isn't expected.

**Comment by EricCousineau-TRI** [comment]
FTR, here's a doc link for current version of Bazel (3.1.0):
https://docs.bazel.build/versions/3.1.0/be/python.html#py_binary.legacy_create_init

In those docs, there's the flag `--incompatible_default_to_explicit_init_py`, which can be used to override.

As a small related note, without control over how the runfiles tree is generated, it may be impossible to do things like workaround https://github.com/bazelbuild/bazel/issues/4594 for Python. See example solution here:
https://github.com/RobotLocomotion/drake/pull/8240

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
