### ISSUE TITLE
No matching toolchains found with --incompatible_remap_main_repo

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel#7654]
### Description of the problem / feature request:

When testing rules_go with `--all_incompatible_changes`, I ran across the error below. It seems to be caused by `--incompatible_remap_main_repo`.

```
rules_go $ bazel test --incompatible_remap_main_repo tests/core/go_binary:hello
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Analyzing: target //tests/core/go_binary:hello (1 packages loaded, 0 targets configured)
Analyzing: target //tests/core/go_binary:hello (6 packages loaded, 16 targets configured)
ERROR: While resolving toolchains for target //tests/core/go_binary:hello: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
ERROR: Analysis of target '//tests/core/go_binary:hello' failed; build aborted: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
INFO: Elapsed time: 3.046s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (10 packages loaded, 91 targets configured)
ERROR: Couldn't start the build. Unable to run tests
FAILED: Build did NOT complete successfully (10 packages loaded, 91 targets configured)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

A minimal reproducible test case is at https://github.com/jayconrod/bazel_remap_main_repo. This is a Starlark-only repository that defines toolchains in an external repo, following the same structure as rules_go.

### What operating system are you running Bazel on?

gLinux 

### What's the output of `bazel info release`?

release 0.24.0rc2

**Comment by jayconrod** [comment]
cc @dkelmer

**Comment by dkelmer** [comment]
Thanks @jayconrod!

bazel built with this bazel works for the attached repro: https://github.com/dkelmer/bazel/tree/toolchainsWithRemapping

Will investigate more thoroughly and write tests tomorrow
