### ISSUE TITLE
Line numbers for `load` statements that can't find the .bzl file to be loaded are confusing

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#766]
The line number of the target that depended on the target that cannot be loaded is displayed, which means that finding the offending `load` statement is not easy. Example:

```
mkdir -p t r/a/b
cat > r/BUILD <<EOF
load("//a/b:d.bzl", "fn")
package(default_visibility = ["//v"])
fn()
EOF

cat >r/a/b/c.bzl <<EOF
def fn():
  native.filegroup(name="fn")
EOF

touch r/a/b/BUILD

cat >t/WORKSPACE <<EOF
local_repository(name="r", path=<THE APPROPRIATE PATH>")
EOF

cat >t/BUILD <<EOF
filegroup(name="r", srcs=["@r//:fn"])
EOF
```

In this case, the line number reported for the missing `.bzl` file is that in t/BUILD insteadof r/BUILD:1

**Comment by hanwen** [comment]
lukacs: "Report the error where SkylarkImportLookupValue.key is called
History is off. Messages may disappear before people see them.
instead of in SkylarkImportLookupFunction
where .key() is called, you should have an AST nearby"

**Comment by dslomov** [comment]
"Improve error messages" drive

**Comment by laurentlb** [comment]
I improved this error message recently (a month ago?)
