### ISSUE TITLE
Bazel tries to compile the same file multiple times at once?

### ISSUE THREAD

**Issue by njlr** [bazelbuild/bazel#7662]
### Description of the problem / ~~feature request~~:

Bazel tries to compile the same `cpp` file multiple times at once. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Fetch `cppitertools`, try to build everything.  

```bash
$ bazel build //... 
```

### What operating system are you running Bazel on?

Ubuntu 18.10

### What's the output of `bazel info release`?

```bash=
$ bazel info release
release 0.23.1
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```bash
$ git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
https://github.com/ryanhaining/cppitertools.git
24fb7df23e207e725c621b694af6a73f950b6515
24fb7df23e207e725c621b694af6a73f950b6515
```

![screenshot from 2019-03-07 09-24-07](https://user-images.githubusercontent.com/1577531/53957239-c04d1680-40d5-11e9-9037-3efe69996802.png)

**Comment by njlr** [comment]
Should note that this issue occurred with and without a remote cache.

**Comment by benjaminp** [comment]
`test_main.cc` is listed as a source in each one of the test targets, so it's compiled each time. Put the test support code in its own `cc_library` to avoid that.

**Comment by njlr** [comment]
Indeed it is: https://github.com/ryanhaining/cppitertools/blob/master/test/make_tests.bzl#L5

Closing this.
