### ISSUE TITLE
Tristate attributes shouldn't allow booleans

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#7663]
Some attributes in native rules, such as `stamp`, are maked as integer in the documentation: https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary.stamp

They allow only 3 values, `-1`, `0`, and `1`. Internally, they have the type `tristate`, which is not exposed to Starlark code. In a Starlark rule, the equivalent is to use: `attr.int(values = [-1, 0, 1])`

Due to a bug, booleans are implicitly converted to tristate/integer. This happens only with native rules, not the Starlark rules. We should fix that.

**Comment by hlopko** [comment]
Isn't this an [incompatible change](https://docs.bazel.build/versions/master/backward-compatibility.html)?

    cc_binary(name = 'foo', srcs = [ 'foo.cc' ], stamp = False)

worked before, and now it doesn't.
