### ISSUE TITLE
Release 0.23.2

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#7667]
Bazel 0.23.2 will be built on top of 0.23.1 (#7573).

There's one cherrypick request so far, to fix https://github.com/bazelbuild/bazel/issues/7661 (Bazel on Windows no longer works when users don't have VC installed).

**Comment by meteorcloudy** [comment]
The fix is ready to be cherry-picked https://github.com/bazelbuild/bazel/commit/56366ee3a73e2c92b2fa36a9840478202b9618ca

**Comment by laurentlb** [comment]
Candidate created with:
scripts/release/release.sh create 0.23.2 441fd75d0047f8a998d784c557736ab9075db893 6ca7763669728253606578a56a205bca3ea883e9 2310b1c2c8b2f32db238f667747e7d5672480f4a f9eb1b56706f91063e9d080b850fa56964e77324 f0a1597cca2252754daf1d53ff76cf1a9b3dd9b9 56366ee3a73e2c92b2fa36a9840478202b9618ca

**Comment by afking** [comment]
Hello, is it possible to get https://github.com/bazelbuild/bazel/commit/d79786d45be22b27f9dce9a03a5b0cb97daed414 ?

**Comment by laurentlb** [comment]
We normally cherry-pick only when it's a critical regression. cc @aehlig

**Comment by meteorcloudy** [comment]
@laurentlb, when is the patch release going to be available? It is currently blocking some users on Windows.

**Comment by meteorcloudy** [comment]
https://github.com/bazelbuild/bazel/commit/d79786d45be22b27f9dce9a03a5b0cb97daed414 doesn't look like a regression

**Comment by afking** [comment]
Its not a regression just noticing it now from switching over to 0.23 where more libraries are using `shallow_since` arg to avoid the debug print lines. No problem, thanks.

**Comment by laurentlb** [comment]
Released.
https://github.com/bazelbuild/bazel/releases/tag/0.23.2

cc @petemounce & @excitoon
(It's not important to update Linux/Mac packages as the cherry-pick is just for Windows.)

**Comment by petemounce** [comment]
Published to chocolatey.

**Comment by excitoon** [comment]
Now I'm 100% sure Scoop have [their own automatics](https://github.com/lukesampson/scoop/commit/5c810040c173f45d7def430c904fa9b80f37ce82), so I will only come up if anything go wrong on Scoop side.

**Comment by jin** [comment]
Reported from Slack: https://github.com/bazelbuild/bazel/releases/tag/0.23.2 doesn't contain the .deb package.

**Comment by meteorcloudy** [comment]
Manually uploaded the deb package.
