### ISSUE TITLE
Documentation for @bazel_tools//src/conditions

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#7668]
@laszlocsomor used this technique in a bzl file to test if we're on Windows:

```python
        is_windows = select({
            "@bazel_tools//src/conditions:host_windows": True,
            "//conditions:default": False,
        }),
```

I didn't find anything about `@bazel_tools//src/conditions` in the documentation.

**Comment by laszlocsomor** [comment]
I used this pattern in https://github.com/bazelbuild/bazel-skylib/pull/122 and https://github.com/bazelbuild/bazel-skylib/pull/123.

**Comment by yogurtearl** [comment]
Related: 

https://bazel.build/docs/configurable-attributes

https://github.com/bazelbuild/bazel/blame/364b77ed34afcd07d48313472e8fe3b260a8312f/src/conditions/BUILD

**Comment by aiuto** [comment]
Obsolete. We should be removing this in favor of the `@platforms` repo.
