### ISSUE TITLE
--incompatible_use_jdk11_as_host_javabase broke java9 toolchain 

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#7672]
As pointed out in https://github.com/bazelbuild/bazel/issues/7219#issuecomment-470420496, now, that `--incompatible_use_jdk11_as_host_javabase` is flipped on master, `//tools/jdk:toolchain_java9` seems to be broken.

It only shows up on Gerrit, on Bazel-CI, because it appears to be the only downstream project, that is using `toolchain_java9`. To reproduce, build Bazel@HEAD, and run bazel with these options, here on example of my Bazel example project: [bazel_printy](https://github.com/davido/bazel_printy):

```
  $ bazel build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java9 --java_toolchain=@bazel_tools//tools/jdk:toolchain_java9 :printy_lib
  INFO: Analysed target //:printy_lib (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/davido/projects/bazel_printy/BUILD:9:1: Building libprinty_lib.jar (1 source file) failed (Exit 1)
error: cannot access module-info
  bad class file: /modules/java.logging/module-info.class
    class file has wrong version 55.0, should be 53.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
Target //:printy_lib failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.197s, Critical Path: 0.06s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by hlopko** [comment]
cc @iirina @meisterT

**Comment by cushon** [comment]
* This will be 'fixed' by #7625
* It looks like JavaBuilder's `--bootclasspath` flag isn't being honoured for `-source 9 -target 9`, and it's reading the host JDK's bootclasspath, which is now JDK 11 (i.e. v55 classfiles, and the current javac9 only supports up to v54)
* I think we should wait for #7625, since the Java > 8 support is experimental and doesn't have an SLA.

**Comment by davido** [comment]
Thanks, I can confirm, that #7625 fixed the breakage. Even when Java9 toolchain support is experimental, there is a dedicated Gerrit job on Bazel CI with this toolchain. This job is now broken, after the flip of `--incompatible_use_jdk11_as_host_javabase`.

I wouldn't disagree, to discontinue and remove java9 toolchain from Bazel, though. But since it is there, it should work.

**Comment by philwo** [comment]
> This job is now broken, after the flip of --incompatible_use_jdk11_as_host_javabase.

Why did we flip the flag if it breaks Gerrit?

**Comment by iirina** [comment]
#7625 was merged. Let us know if the issue persists.
