### ISSUE TITLE
glob(["**"], exclude_directories = 0) causes java.lang.IllegalArgumentException: Encountered two inputs with the same path

### ISSUE THREAD

**Issue by mariusgrigoriu** [bazelbuild/bazel#7675]
### Description of the problem / feature request:

`glob(["**"], exclude_directories = 0)` causes `java.lang.IllegalArgumentException: Encountered two inputs with the same path` in my example below.

My intention is to create a tar / container image layer of all files in this external repository while preserving directory structure.

I thought that including `**` and exclude_directories = 0 is the way to go, but that crashes with a stack trace. The docs make it seem like this combination of args is a valid scenario. If it isn't it would be better if a friendlier error were printed instead.

I was able to make it work with `*` and exclude_directories = 0. I wasn't expecting it to recurse through directories, but it did.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

WORKSPACE:
```
new_git_repository(
    name = "com_github_tagomoris_fluent_plugin_flowcounter",
    remote = "https://github.com/tagomoris/fluent-plugin-flowcounter.git",
    tag = "v1.3.0",
    build_file = "@//applications/fluentd:BUILD.flowcounter"
)
```

BUILD.flowcounter:
```
filegroup(
    name = "gem",
    srcs = glob(
        include = ["**"],
        exclude_directories = 0,    
    ),
    visibility = ["//visibility:public"],
)
```

### What operating system are you running Bazel on?

Mac OS High Sierra

### What's the output of `bazel info release`?

release 0.23.1

###  Have you found anything relevant by searching the web?

According to the docs:
> The "**" wildcard has one corner case: the pattern "**" doesn't match the package's directory path. That is to say, glob(["**"], exclude_directories = 0) matches all files and directories transitively strictly under the current package's directory (but of course not going into directories of subpackages - see the previous note about that).

**Comment by laszlocsomor** [comment]
I can still repro this with 0.27.0

**Comment by laszlocsomor** [comment]
Actually, I cannot repro this bug on macOS, neither with 0.23.1 nor with 0.27.0.

Do you still see this issue with Bazel 0.27.0?

**Comment by mariusgrigoriu** [comment]
I seem to be no longer be able to repro, but I am now on Mojave and no longer have access to a High Sierra machine.

**Comment by laszlocsomor** [comment]
Thanks for following up!
