### ISSUE TITLE
repository_ctx.download uses sha256 for cache, regardless of url

### ISSUE THREAD

**Issue by shahms** [bazelbuild/bazel#7676]
### Description of the problem / feature request:

When using `repository_ctx.download(url = url, sha256 = "...")` if the sha256 exists in the cache, the url is ignored.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1) Write a repository rule which uses repository_ctx.download and a sha256sum, e.g
```
def _impl(repository_ctx):
    url = "https://raw.githubusercontent.com/technomancy/leiningen/%s/bin/lein" % (repository_ctx.attr.version,)                                                     
    repository_ctx.download(
        url = url,
        output = "home/lein.sh.in",
        sha256 = repository_ctx.attr.sha256,
        executable = False,
    )
    ...
```
2) Build something using that repository
3) Change the URL (via version in the above) without changing sha256
4) Notice how there is no failure and the previous version is used

### What operating system are you running Bazel on?
Debian-based Linux distribution.

### What's the output of `bazel info release`?

release 0.23.1

###  Have you found anything relevant by searching the web?

I was unable to find anything relevant in discussion forums or other issues.

### Any other information, logs, or outputs that you want to share?

Happy to share anything useful :-)

**Comment by aehlig** [comment]
> When using `repository_ctx.download(url = url, sha256 = "...")` if the sha256 exists in the cache, the url is ignored.

This is happening on purpose: if the file is already in cache, we want to avoid unnecessary calls to the network. What benefit would such a fetch bring? If we don't error out, the will get a file we have already.
Also note, that for `url` usually a list of alternative mirrors is provided, and extending that list is a legitimate case where `url` changes but we still don't want to redownload the file.

I'm aware that this can lead to usage errors, as is discussed in #5144, #6089. Closing as duplicate.
