### ISSUE TITLE
Custom repository rule with local = True not getting fetched everytime

### ISSUE THREAD

**Issue by kkanhere** [bazelbuild/bazel#7677]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

A repository rule with local attribute set to True doesn't fetch/run every time. Even an explicit fetch on it doesn't cause it to run again.

Surprisingly a bazel shutdown followed by bazel build command causes it to correctly run again. So it seems like the server is caching a previous run in memory and not invalidating it correctly even if the rule is marked local.

### Feature requests: what underlying problem are you trying to solve with this feature?

We have some external maven artifacts that are trunk-SNAPSHOT versions and need to be downloaded every time a target depending on them is built. For that we have a custom repository rule implementation with local attribute set to True, with the expectation that marking it local will cause it to be fetched every time.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Can be easily reproduced by creating the following bazel project

<pre>
#WORKSAPCE
workspace(name = "local_repo")
load("//:my_local_repo.bzl", "my_local_repo")
my_local_repo(
    name = "main_local_repo",
)
</pre>

<pre>
#my_local_repo.bzl
def _my_local_repo_impl(repository_ctx):
    repository_ctx.file("BUILD.bazel", "exports_files(['date.txt'])")
    repository_ctx.file("date.txt", repository_ctx.execute(["date"]).stdout)

my_local_repo = repository_rule(
    implementation = _my_local_repo_impl,
    local = True,
)
</pre>

<pre>
#BUILD.bazel
genrule(
    name = "main",
    srcs = ["@main_local_repo//:date.txt"],
    outs = ["date.out"],
    cmd = "cat $< > $@",
)
</pre>

Multiple executions of 

> bazel build :main; cat bazel-genfiles/date.out

return the same date (i.e. date from the first run), but multiple executions of the command

> bazel --batch build :main; cat bazel-genfiles/date.out

correctly returns current dates 

### What operating system are you running Bazel on?

CentOS Linux release 7.3.1611 (Core) 

### What's the output of `bazel info release`?

release 0.22.0-imc (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

We pulled the 0.22.0 dist tarball from [here](https://github.com/bazelbuild/bazel/releases/download/0.22.0/bazel-0.22.0-dist.zip) and built it into an rpm (built the target `//src:bazel_nojdk`)

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> NA

###  Have you found anything relevant by searching the web?

GitHub issues: https://github.com/bazelbuild/bazel/issues/3062
The need in our case is always run kind of trigger. I can't think of a way that file dependency will solve our problem, because the files that the respository rule deals with are external.

GitHub issues: https://github.com/bazelbuild/bazel/issues/5740
But the solution mentioned is not applicable in our case. There is no dependency on any environment variable for our rule.

### Any other information, logs, or outputs that you want to share?

> NA

**Comment by dslomov** [comment]
The semantics of `local` is unfortunately [not specified very well)[https://docs.bazel.build/versions/master/skylark/repository_rules.html#when-is-the-implementation-function-executed]...

What are you trying to acheive? We do have some support for "volatile" information about the build (https://stackoverflow.com/questions/49879399/bazel-how-to-access-workspace-status-variables-in-skylark, https://docs.bazel.build/versions/master/user-manual.html#workspace_status), although it is not documented.

**Comment by kkanhere** [comment]
How would I introduce sensitivity to these files on the repo rule?

I tried adding a custom rule that just cats the ctx.info_file and ctx.version_file to an output file and invoke with command <pre>bazel build --workspace_status_command='echo "STABLE_TIMESTAMP $(date +%s)" -- //...'</pre> and I see that the custom rule runs every time and creates the output file correctly. But I am not able to get the repo rule to run based on this generated file.


Also out of curiosity, why does the original problem get fixed with the command <pre>bazel --batch build :main</pre>

**Comment by kkanhere** [comment]
What I am trying to accomplish is provide support for trunk-SNAPSHOT version for maven artifacts where any bazel build target depending on such an artifact should result in re-fetching of the artifact and re-building of the target. I have a custom repository rule that can fetch the trunk-SNAPSHOT version but it is not getting invoked everytime the target depending on it is build. It surprisingly works with --batch startup option though.

**Comment by kkanhere** [comment]
After a few experiments, I am able to get this working using the below (changes highlighted in bold)

<pre>
#WORKSAPCE
workspace(name = "local_repo")
load("//:my_local_repo.bzl", "my_local_repo")
my_local_repo(
    name = "main_local_repo",
    <b>info = "//:timestamp.bzl",</b>
)
</pre>

<pre>
#my_local_repo.bzl
def _my_local_repo_impl(repository_ctx):
    repository_ctx.file("BUILD.bazel", "exports_files(['date.txt'])")
    repository_ctx.file("date.txt", repository_ctx.execute(["date"]).stdout)

my_local_repo = repository_rule(
    implementation = _my_local_repo_impl,
    local = True,
    <b>attrs = { "info" : attr.label(allow_single_file = True, mandatory = True), },</b>
)
</pre>

<pre>
#BUILD.bazel
genrule(
    name = "main",
    srcs = ["@main_local_repo//:date.txt"],
    outs = ["date.out"],
    cmd = "cat $< > $@",
)
</pre>

<pre><b>
#.bazelrc
build --workspace_status_command='echo "TIMESTAMP = $(date +%s)" > timestamp.bzl'
</b></pre>

With this 
> bazel build :main; cat bazel-genfiles/date.out

is outputting correct date on every run.

But this feels like a very hacky way and abuse of workspace_status_command argument. Would be really much better if there was a way to make the repository rule sensitive to the volatile_status.txt file.

**Comment by katre** [comment]
Closed for lack of activity. Please ping the reviewers to reopen if this is still a problem.

**Comment by GabrielGhe** [comment]
I'm also hitting this (custom repository rule with `local = True` not re-running).

We got around this by conditionally setting `--repo_env=rerun=$(date +%s)` when we want to rerun the repo rule and

```
our_rule = repository_rule(
    implementation = _our_rule_impl,
    local = True,
    environ = ["rerun"],
    attrs = { ... },
)
```

**Comment by pauldraper** [comment]
> Closed for lack of activity. Please ping the reviewers to reopen if this is still a problem.

This is still a problem.

I don't know what local does, but it doesn't seem to work.

**Comment by pauldraper** [comment]
Ah, I see. `local` only re-runs on server restart.

An odd flag, I think.

https://bazel.build/external/repo#when-is-the-implementation-function-executed
