### ISSUE TITLE
bazel fails to extract

### ISSUE THREAD

**Issue by mattcarrier** [bazelbuild/bazel#7678]
### Description of the problem / feature request:

When installing bazel it fails the final step which seems to be calling itself to extract for faster run time.  It also fails anytime I try to run bazel after the install as well.

```
Extracting Bazel installation...
FATAL: failed to open '/var/tmp/_bazel_mcarrier/install/a134bf748a9bb448b9801b24812c57ec.tmp.71924/_embedded_binaries/A-server.jar' for syncing: (error: 13): Permission denied
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

This was reproducible for me anytime I tried to install bazel or try and run bazel directly after the failed install.

### What operating system are you running Bazel on?

macOS High Sierra 10.13.6

### What's the output of `bazel info release`?

```
Extracting Bazel installation...
FATAL: failed to open '/var/tmp/_bazel_mcarrier/install/a134bf748a9bb448b9801b24812c57ec.tmp.71924/_embedded_binaries/A-server.jar' for syncing: (error: 13): Permission denied
```

###  Have you found anything relevant by searching the web?

https://stackoverflow.com/questions/52283372/permission-denied-when-installing-bazel-0-16-1-on-macos-10-13-6

It is the same exact issue I have and the one answer said to post a bazel bug ;-)

### Any other information, logs, or outputs that you want to share?

seems to have correct permissions to "Extract" but I don't know where it is trying to extract TO to check the permissions

```
-rwxr-xr-x  1 mcarrier  wheel  39145045 Mar  5  2029 /var/tmp/_bazel_mcarrier/install/a134bf748a9bb448b9801b24812c57ec.tmp.71924/_embedded_binaries/A-server.jar
```

**Comment by mattcarrier** [comment]
OK, I just tried this on my non-work mac and it definitely works.  So I just need to know what areas I need to check my permissions.

**Comment by meisterT** [comment]
I assume this is stale. Please reply if not.
