### ISSUE TITLE
support for multiple `processor_class` in `java_plugin`

### ISSUE THREAD

**Issue by menny** [bazelbuild/bazel#7689]
### Description of the problem / feature request:

Ability to specify multiple `processor_class` at https://docs.bazel.build/versions/master/be/java.html#java_plugin.processor_class

### Feature requests: what underlying problem are you trying to solve with this feature?

In many annotation-processor libraries (for example, auto-value) there are multiple published `Processor` classes. Currently, if I want to use those I'll need to (1) create a `java_plugin` target for each `process_class` and add all of those to the `plugins` list of my BUILD target. Or, (2) I could group all the `java_plugin` targets into one `java_library` under `exported_plugin` and add this grouping `java_library` to the `deps` list of the BUILD target. This is error-prone or confusing:

1) if I go the route of 1 - create a `java_plugin` for each `process_class` - I might miss some in some cases, and if the process-classes change I need to change the `plugins` list in multiple places. Depending on one target would solve this.
2) if I go the route of 2 - create a `java_library` that group all `java_plugin` - I end up adding this `java_library` to the `deps` list which is a confusing, implicit, outcome.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create multiple `java_plugin`s, for example for `auto-value`:
In the WORKSPACE:
```
http_file(name = 'com_google_auto_value__auto_value__1_6_3rc2',
        urls = ['http://central.maven.org/maven2/com/google/auto/value/auto-value/1.6.3rc2/auto-value-1.6.3rc2.jar'],
        downloaded_file_path = 'auto-value-1.6.3rc2.jar',
    )
```

In a BUILD file:
```
java_import(name = 'com_google_auto_value__auto_value__1_6_3rc2',
        jars = ['@com_google_auto_value__auto_value__1_6_3rc2//file'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )
java_plugin(name = 'com_google_auto_value__auto_value__1_6_3rc2___generates_api___processor_class_0',
        processor_class = 'com.google.auto.value.extension.memoized.processor.MemoizedValidator',
        generates_api = 1,
        deps = [':com_google_auto_value__auto_value__1_6_3rc2'],
    )
java_plugin(name = 'com_google_auto_value__auto_value__1_6_3rc2___generates_api___processor_class_1',
        processor_class = 'com.google.auto.value.processor.AutoAnnotationProcessor',
        generates_api = 1,
        deps = [':com_google_auto_value__auto_value__1_6_3rc2'],
    )
java_plugin(name = 'com_google_auto_value__auto_value__1_6_3rc2___generates_api___processor_class_2',
        processor_class = 'com.google.auto.value.processor.AutoOneOfProcessor',
        generates_api = 1,
        deps = [':com_google_auto_value__auto_value__1_6_3rc2'],
    )
java_plugin(name = 'com_google_auto_value__auto_value__1_6_3rc2___generates_api___processor_class_3',
        processor_class = 'com.google.auto.value.processor.AutoValueBuilderProcessor',
        generates_api = 1,
        deps = [':com_google_auto_value__auto_value__1_6_3rc2'],
    )
java_plugin(name = 'com_google_auto_value__auto_value__1_6_3rc2___generates_api___processor_class_4',
        processor_class = 'com.google.auto.value.processor.AutoValueProcessor',
        generates_api = 1,
        deps = [':com_google_auto_value__auto_value__1_6_3rc2'],
    )
java_library(name = 'com_google_auto_value__auto_value__1_6_3rc2___generates_api___processor_class_all',
        exported_plugins = [
            ':com_google_auto_value__auto_value__1_6_3rc2___processor_class_0',
            ':com_google_auto_value__auto_value__1_6_3rc2___processor_class_1',
            ':com_google_auto_value__auto_value__1_6_3rc2___processor_class_2',
            ':com_google_auto_value__auto_value__1_6_3rc2___processor_class_3',
            ':com_google_auto_value__auto_value__1_6_3rc2___processor_class_4',
        ],
    )

```

### What operating system are you running Bazel on?

macOS, Linux, Windows

### What's the output of `bazel info release`?

release 0.23.1-homebrew

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a

###  Have you found anything relevant by searching the web?

I had a discussion with @jin at https://bazelbuild.slack.com/archives/CA31HN1T3/p1552312744086100

**Comment by cushon** [comment]
> group all the java_plugin targets into one java_library under exported_plugin

[`java_plugin.exported_plugin`](https://docs.bazel.build/versions/master/be/java.html#java_plugin.exported_plugin) is the recommended way to do this.

In the auto-value example you need a `dep` on the target that provides the `@AutoValue` annotations anyways, so typically that target would also provide the plugins via `exported_plugins`. Here's a complete example of targets for auto: https://github.com/google/bazel-common/blob/f1115e0f777f08c3cdb115526c4e663005bec69b/third_party/java/auto/BUILD#L63

Having to also add the processors to `plugins` is more explicit, but also duplicative and error-prone.
