### ISSUE TITLE
incompatible_fixme_crosstool_static_link_msvcrt_feature

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#7691]
**Need label**: incompatible-change FIXME

### Description ###

Windows features `dynamic_link_msvcrt_debug`, `dynamic_link_msvcrt_no_debug`, `static_link_msvcrt_debug`, `static_link_msvcrt_no_debug` are being removed. Also logic of `static_link_msvcrt` feature on Windows (expanding to one of above) is moving away to default CROSSTOOL generation code. #7579

You are affected by this change if:
- you are using custom `CROSSTOOL` targeting Windows (a); or
- you manually enable and/or disable `dynamic_link_msvcrt_debug`, `dynamic_link_msvcrt_no_debug`, `static_link_msvcrt_debug`, `static_link_msvcrt_no_debug` features for some targets (b).

### Migration ###

a) Update `CROSSTOOL` according to [this](https://github.com/bazelbuild/bazel/pull/7579/commits/9398a3d87c96bdc61658ef18952886c1dea3c3e9#diff-c5fe7ff39135c1e57570c74c952f0146):
1. Add 2 features which shall turn static and dynamic flags on depending on `static_link_msvcrt`, enabled by default (`enabled: true`), one for debug and another for no debug mode:
```
        flag_sets = [
            flag_set(
                actions = [ACTION_NAMES.c_compile, ACTION_NAMES.cpp_compile],
                with_features = [with_feature_set(not_features=["static_link_msvcrt"])],
                flag_groups = [flag_group(flags = ["/MDd"])],
            ),
            flag_set(
                actions = [ACTION_NAMES.c_compile, ACTION_NAMES.cpp_compile],
                with_features = [with_feature_set(features=["static_link_msvcrt"])],
                flag_groups = [flag_group(flags = ["/MTd"])],
            ),
...
```

b) In your CROSSTOOL create 1-4 features with desirable names with desirable flags.

### Expected timeline ###
FIXME

**Comment by aiuto** [comment]
Giving it to C++ and Windows for further triage.

**Comment by laszlocsomor** [comment]
@hlopko , @meteorcloudy : please triage

**Comment by hlopko** [comment]
Hi @excitoon, I just discovered this flag. Is it still relevant? If so, could you pls  update the issue to follow https://bazel.build/breaking-changes-guide.html? Thank you!
