### ISSUE TITLE
Expose --jvmopt to Starlark

### ISSUE THREAD

**Issue by timpeut** [bazelbuild/bazel#7701]
Bazel defines the `--jvmopt` flag but there is currently no way to access this value in Starlark. We need access to this value for feature parity with the native Android rules.

Mostly likely makes sense to expose via Starlark `java_common`. AFAICT it is currently accessed via `JavaConfiguration.getDefaultJvmFlags()`.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
