### ISSUE TITLE
Install problem: Error: parent directory is world writable but not sticky

### ISSUE THREAD

**Issue by heikoludwig** [bazelbuild/bazel#7703]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

I have a problem installing on a Mac. 

==> ./bazel-0.23.1-installer-darwin-x86_64.sh --prefix=/private/tmp/bazel-20190312-50926-1od5eec
Error: parent directory is world writable but not sticky
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:28:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:732:in `build'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:308:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:318:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:250:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:248:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:248:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'

./bazel-0.23.1-installer-darwin-x86_64.sh --prefix=/private/tmp/bazel-20190312-50926-1od5eec
Error: parent directory is world writable but not sticky

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Homebrew Install

### What operating system are you running Bazel on?

MacOS 10.14.3

### What's the output of `bazel info release`?

don't get to install bazel

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by vsmida** [comment]
> /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:93:in `mktmpdir' /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:28:in `safe_fork'

requires to have 'sticky' permission on `/private/tmp`
https://github.com/Homebrew/legacy-homebrew/issues/39170

```shell
$ sudo chmod +t /private/tmp/

**Comment by meisterT** [comment]
Is this still a problem today?
