### ISSUE TITLE
Not able to build for graph_transforms uisng bazel

### ISSUE THREAD

**Issue by BhuvanKanade** [bazelbuild/bazel#7704]
while compiling below command i am getting issue

C:\tensorflow>bazel build tensorflow/tools/graph_transforms:transform_graph
INFO: Invocation ID: 4ea64e6b-cff5-46e0-9558-c6b07dcda809
ERROR: Skipping 'tensorflow/tools/graph_transforms:transform_graph': error loading package 'tensorflow/tools/graph_transforms': in C:/tensorflow/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'rocm/build_defs.bzl': no such package '@local_config_rocm//rocm': Traceback (most recent call last):
File "C:/tensorflow/third_party/gpus/rocm_configure.bzl", line 755
_create_local_rocm_repository(repository_ctx)
File "C:/tensorflow/third_party/gpus/rocm_configure.bzl", line 599, in _create_local_rocm_repository
_get_rocm_config(repository_ctx)
File "C:/tensorflow/third_party/gpus/rocm_configure.bzl", line 421, in _get_rocm_config
_rocm_toolkit_path(repository_ctx)
File "C:/tensorflow/third_party/gpus/rocm_configure.bzl", line 221, in _rocm_toolkit_path
auto_configure_fail("Cannot find rocm toolkit path.")
File "C:/tensorflow/third_party/gpus/rocm_configure.bzl", line 121, in auto_configure_fail
fail(("\n%sROCm Configuration Error:%...)))

ROCm Configuration Error: Cannot find rocm toolkit path.
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/graph_transforms': in C:/tensorflow/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'rocm/build_defs.bzl': no such package '@local_config_rocm//rocm': Traceback (most recent call last):
File "C:/tensorflow/third_party/gpus/rocm_configure.bzl", line 755
_create_local_rocm_repository(repository_ctx)
File "C:/tensorflow/third_party/gpus/rocm_configure.bzl", line 599, in _create_local_rocm_repository
_get_rocm_config(repository_ctx)
File "C:/tensorflow/third_party/gpus/rocm_configure.bzl", line 421, in _get_rocm_config
_rocm_toolkit_path(repository_ctx)
File "C:/tensorflow/third_party/gpus/rocm_configure.bzl", line 221, in _rocm_toolkit_path
auto_configure_fail("Cannot find rocm toolkit path.")
File "C:/tensorflow/third_party/gpus/rocm_configure.bzl", line 121, in auto_configure_fail
fail(("\n%sROCm Configuration Error:%...)))

ROCm Configuration Error: Cannot find rocm toolkit path.
INFO: Elapsed time: 0.543s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
currently loading: tensorflow/tools/graph_transforms
Fetching @local_config_rocm; fetching

**Comment by BhuvanKanade** [comment]
while compiling below command i am getting issue


C:\tensorflow>bazel build tensorflow/tools/graph_transforms:transform_graph
INFO: Invocation ID: 4ea64e6b-cff5-46e0-9558-c6b07dcda809
ERROR: Skipping 'tensorflow/tools/graph_transforms:transform_graph': error loading package 'tensorflow/tools/graph_transforms': in C:/tensorflow/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'rocm/build_defs.bzl': no such package '@local_config_rocm//rocm': Traceback (most recent call last):
        File "C:/tensorflow/third_party/gpus/rocm_configure.bzl", line 755
                _create_local_rocm_repository(repository_ctx)
        File "C:/tensorflow/third_party/gpus/rocm_configure.bzl", line 599, in _create_local_rocm_repository
                _get_rocm_config(repository_ctx)
        File "C:/tensorflow/third_party/gpus/rocm_configure.bzl", line 421, in _get_rocm_config
                _rocm_toolkit_path(repository_ctx)
        File "C:/tensorflow/third_party/gpus/rocm_configure.bzl", line 221, in _rocm_toolkit_path
                auto_configure_fail("Cannot find rocm toolkit path.")
        File "C:/tensorflow/third_party/gpus/rocm_configure.bzl", line 121, in auto_configure_fail
                fail(("\n%sROCm Configuration Error:%...)))

ROCm Configuration Error: Cannot find rocm toolkit path.
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/graph_transforms': in C:/tensorflow/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'rocm/build_defs.bzl': no such package '@local_config_rocm//rocm': Traceback (most recent call last):
        File "C:/tensorflow/third_party/gpus/rocm_configure.bzl", line 755
                _create_local_rocm_repository(repository_ctx)
        File "C:/tensorflow/third_party/gpus/rocm_configure.bzl", line 599, in _create_local_rocm_repository
                _get_rocm_config(repository_ctx)
        File "C:/tensorflow/third_party/gpus/rocm_configure.bzl", line 421, in _get_rocm_config
                _rocm_toolkit_path(repository_ctx)
        File "C:/tensorflow/third_party/gpus/rocm_configure.bzl", line 221, in _rocm_toolkit_path
                auto_configure_fail("Cannot find rocm toolkit path.")
        File "C:/tensorflow/third_party/gpus/rocm_configure.bzl", line 121, in auto_configure_fail
                fail(("\n%sROCm Configuration Error:%...)))

ROCm Configuration Error: Cannot find rocm toolkit path.
INFO: Elapsed time: 0.543s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/graph_transforms
    Fetching @local_config_rocm; fetching

**Comment by aiuto** [comment]
Can you please provide enough information so someone could reproduce this?

**Comment by BhuvanKanade** [comment]
I am using anaconda 

(tensorflow2_0) C:\tensorflow>conda list
# packages in environment at C:\Users\KANADBK\AppData\Local\conda\conda\envs\tensorflow2_0:
#
# Name                    Version                   Build  Channel
absl-py                   0.7.0                     <pip>
astor                     0.7.1                     <pip>
attrs                     19.1.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bazel                     0.22.0               h33f27b4_0
bleach                    3.1.0                      py_0    conda-forge
certifi                   2018.11.29               py36_0    anaconda
colorama                  0.4.1                     <pip>
colorama                  0.4.1                      py_0    conda-forge
contextlib2               0.5.5                     <pip>
cycler                    0.10.0                    <pip>
Cython                    0.29.6                    <pip>
decorator                 4.3.2                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
defusedxml                0.5.0                     <pip>
entrypoints               0.3                   py36_1000    conda-forge
enum34                    1.1.6                     <pip>
gast                      0.2.2                     <pip>
google-pasta              0.1.4                     <pip>
grpcio                    1.19.0                    <pip>
h5py                      2.9.0                     <pip>
ipykernel                 5.1.0           py36h39e3cac_1002    conda-forge
ipython                   7.3.0                     <pip>
ipython                   7.3.0            py36h39e3cac_0    conda-forge
ipython-genutils          0.2.0                     <pip>
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                     <pip>
jedi                      0.13.3                   py36_0    conda-forge
jedi                      0.13.3                    <pip>
Jinja2                    2.10                      <pip>
jinja2                    2.10                       py_1    conda-forge
jsonschema                3.0.1                    py36_0    conda-forge
jsonschema                3.0.1                     <pip>
jupyter                   1.0.0                     <pip>
jupyter-console           6.0.0                     <pip>
jupyter_client            5.2.4                      py_3    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
Keras-Applications        1.0.6                     <pip>
Keras-Preprocessing       1.0.5                     <pip>
kiwisolver                1.0.1                     <pip>
libprotobuf               3.7.0                h1a1b453_1    conda-forge
libsodium                 1.0.16            h2fa13f4_1001    conda-forge
lxml                      4.3.2                     <pip>
m2-base                   1.0.0                         2
m2-bash                   4.3.042                       5
m2-bash-completion        2.3                           2
m2-catgets                1.1                           3
m2-coreutils              8.25                        102
m2-dash                   0.5.8                         2
m2-diffutils              3.3                           4
m2-file                   5.25                          2
m2-filesystem             2016.04                       4
m2-findutils              4.6.0                         2
m2-gawk                   4.1.3                         2
m2-gcc-libs               5.3.0                         4
m2-gettext                0.19.7                        4
m2-gmp                    6.1.0                         3
m2-grep                   2.22                          4
m2-gzip                   1.7                           2
m2-inetutils              1.9.2                         2
m2-info                   6.0                           2
m2-less                   481                           2
m2-libasprintf            0.19.7                        4
m2-libbz2                 1.0.6                         3
m2-libcatgets             1.1                           3
m2-libcrypt               1.3                           2
m2-libgettextpo           0.19.7                        4
m2-libiconv               1.14                          3
m2-libintl                0.19.7                        4
m2-liblzma                5.2.2                         2
m2-libpcre                8.38                          2
m2-libreadline            6.3.008                       8
m2-libutil-linux          2.26.2                        2
m2-libxml2                2.9.2                         3
m2-make                   4.1                           5
m2-mintty                 1!2.2.3                       2
m2-mpfr                   3.1.4                         2
m2-msys2-launcher-git     0.3.28.860c495                2
m2-msys2-runtime          2.5.0.17080.65c939c               3
m2-ncurses                6.0.20160220                  2
m2-sed                    4.2.2                         3
m2-tar                    1.28                          4
m2-tftp-hpa               5.2                           2
m2-time                   1.7                           2
m2-ttyrec                 1.0.8                         2
m2-tzcode                 2015.e                        2
m2-unzip                  6.0                           3
m2-util-linux             2.26.2                        2
m2-which                  2.21                          3
m2-zip                    3.0                           2
m2-zlib                   1.2.8                         4
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
Markdown                  3.0.1                     <pip>
markupsafe                1.1.1            py36hfa6e2cd_0    conda-forge
matplotlib                3.0.3                     <pip>
mistune                   0.8.4           py36hfa6e2cd_1000    conda-forge
msys2-conda-epoch         20160418                      1
nbconvert                 5.4.1                      py_2    conda-forge
nbconvert                 5.4.1                     <pip>
nbformat                  4.4.0                      py_1    conda-forge
nbformat                  4.4.0                     <pip>
notebook                  5.5.0                    py36_0    conda-forge
numpy                     1.16.2                    <pip>
object-detection          0.1                       <pip>
opencv-python             4.0.0.21                  <pip>
openjdk                   11.0.1          c_compilervs2015_1014    conda-forge
pandoc                    2.6                           1    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pandocfilters             1.4.2                     <pip>
parso                     0.3.4                      py_0    conda-forge
pickleshare               0.7.5                     <pip>
pickleshare               0.7.5                 py36_1000    conda-forge
Pillow                    5.4.1                     <pip>
pip                       19.0.3                   py36_0    conda-forge
posix                     1.0.0                         2
prometheus-client         0.6.0                     <pip>
prometheus_client         0.6.0                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
protobuf                  3.7.0                     <pip>
protobuf                  3.7.0            py36he025d50_0    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pyparsing                 2.3.1                     <pip>
pyrsistent                0.14.11          py36hfa6e2cd_0    conda-forge
python                    3.6.7             he025d50_1004    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pywinpty                  0.5.5                     <pip>
pywinpty                  0.5.5                 py36_1000    conda-forge
pyzmq                     18.0.1           py36he418aac_0    conda-forge
pyzmq                     18.0.1                    <pip>
qtconsole                 4.4.3                     <pip>
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.8.0                   py36_0    conda-forge
six                       1.12.0                    <pip>
six                       1.12.0                py36_1000    conda-forge
tb-nightly                1.14.0a20190301           <pip>
tensorflow                2.0.0a0                   <pip>
termcolor                 1.1.0                     <pip>
terminado                 0.8.1                     <pip>
terminado                 0.8.1                 py36_1001    conda-forge
testpath                  0.4.2                 py36_1000    conda-forge
tf-estimator-nightly      1.14.0.dev2019030115           <pip>
tornado                   5.1.1            py36hfa6e2cd_0    anaconda
traitlets                 4.3.2                 py36_1000    conda-forge
traitlets                 4.3.2                     <pip>
vc                        14.1                 h21ff451_3    anaconda
vs2015_runtime            15.5.2                        3    anaconda
wcwidth                   0.1.7                      py_1    conda-forge
wcwidth                   0.1.7                     <pip>
webencodings              0.5.1                      py_1    conda-forge
webencodings              0.5.1                     <pip>
Werkzeug                  0.14.1                    <pip>
wheel                     0.33.1                   py36_0    conda-forge
widgetsnbextension        3.4.2                     <pip>
wincertstore              0.2                   py36_1002    conda-forge
winpty                    0.4.3                         4    conda-forge
zeromq                    4.2.5             he025d50_1006    conda-forge
zlib                      1.2.11            h2fa13f4_1004    conda-forge

and tensorflow folder is having latest tensorflow code from git hub.

Please let me know if any more information is required.

Can i run summary graph without bazel as well ?

**Comment by jin** [comment]
This is a TF build issue; please reopen this issue on the TensorFlow repository.
