### ISSUE TITLE
Minimize output of --toolchain_resolution_debug

### ISSUE THREAD

**Issue by EricBurnett** [bazelbuild/bazel#7713]
### Description of the problem / feature request:

--toolchain_resolution_debug contains useful information for understanding why a toolchain was selected, but it's also very verbose - in an example case involving the Go rules, 1600 lines of output mostly of the form "considering X; constraint doesn't match; rejected X", plus a large number of repeated lines when unspecified actions choose a toolchain (_"Selected execution platform //:builder_platform, type @io_bazel_rules_go//go:toolchain -> toolchain @go_sdk//:go_linux_amd64-impl"_ 800 times)

### Feature requests: what underlying problem are you trying to solve with this feature?

It'd be nice if this could be more compacted, and easier to scan. E.g. by collecting up the resolution details first, then producing a compact structured output second - 

    Toolchain resolution debug info:
        @io_bazel_rules_go//go:toolchain for @bazel_tools//platforms:target_platform
            Matched execution platforms and toolchains: {//:builder_platform -> @go_sdk//:go_linux_amd64-impl, @bazel_tools//platforms:host_platform -> @go_sdk//:go_linux_amd64-impl}
            Rejected toolchains @go_sdk//:go_android_386-impl, @go_sdk//:go_android_amd64-impl, and 20 others for not matching constraint @bazel_tools//platforms:os , value @bazel_tools//platforms:linux
        @io_bazel_rules_go//go:toolchain for @bazel_tools//platforms:host_platform
            Matched execution platforms and toolchains: {//:builder_platform -> @go_sdk//:go_linux_amd64-impl, @bazel_tools//platforms:host_platform -> @go_sdk//:go_linux_amd64-impl}
            Rejected toolchains @go_sdk//:go_android_386-impl, @go_sdk//:go_android_amd64-impl, and 20 others for not matching constraint @bazel_tools//platforms:os , value @bazel_tools//platforms:linux
        @bazel_tools//tools/cpp:toolchain_type for @bazel_tools//platforms:target_platform
        ...

For matching of toolchains against actions themselves, it seems it'd be better to either omit those lines, or to emit the target as well - 800 lines saying the go toolchain was selected but without context don't quite solve that well.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Add --toolchain_resolution_debug to any build including Go.

**Comment by cushon** [comment]
see also b/126375095

**Comment by katre** [comment]
This is being left open because it's still an issue, but I don't have any good ideas for better ways to report this output.

If anyone does have ideas, I'd welcome comments or PRs.
