### ISSUE TITLE
[BEP] can BuildMetrics message include remote cache hits

### ISSUE THREAD

**Issue by petroseskinder** [bazelbuild/bazel#7714]
### Description of the problem / feature request:
I would like for BEP to report cache hits via the [BuildMetrics](https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto;l=623?q=%22buildMetrics%22) message.

Currently, the [BuildMetrics](https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto;l=623?q=%22buildMetrics%22) message contains an [action_summary](https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto;l=633?q=%22buildMetrics%22) message with an actions_executed field. The field indicates the number of actions actually executed, including actions that were remotely cached. 

```proto
message BuildMetrics {
  message ActionSummary {
    // The total number of actions created and registered during the build.
    // This includes unused actions that were constructed but
    // not executed during this build.
    int64 actions_created = 1;

    // The total number of actions executed during the build.
    // This includes any remote cache hits, but excludes
    // local action cache hits.
    int64 actions_executed = 2;
  }
  ActionSummary action_summary = 1;
...
```
It would be really helpful if it also contained an `actions_cached` field, so that one can easily parse the remote cache hit rate.

```
{
  "id": {
    "buildMetrics": {}
  },
  "lastMessage": true,
  "buildMetrics": {
    "actionSummary": {
      "actionsCreated": "689",
      "actionsExecuted": "314",
      "remoteCacheHits": "0"
    },
    ...
  }
}

```

### Feature requests: what underlying problem are you trying to solve with this feature?
I am trying to build a monitoring service that uses BEP output to monitor remote cache performance across our builds

Today, if one wanted to determine the remote cache hit rate, one would need to parse stderr of [Progress message](https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto;l=43?q=%22buildMetrics%22). For example:
```
{
  "id": {"progress": {
      "opaqueCount": 80
    }
  },
  "progress": {
    "stderr": "INFO: Elapsed time: 15.459s, Critical Path: 6.54s\nINFO: 235 processes: 220 remote cache hit, 14 linux-sandbox, 1 worker.\nINFO: Build completed successfully, 314 total actions\n"
  }
}
```
This is mildly annoying to do, if one doesn't have cache hits, as it does not report 0 report cache hits. 
```
{
  "id": {"progress": {
      "opaqueCount": 139
    }
  },
  "progress": {
    "stderr": "INFO: Elapsed time: 28.428s, Critical Path: 19.73s\nINFO: 235 processes: 213 linux-sandbox, 22 worker.\nINFO: Build completed successfully, 314 total actions\n"
  }
}
```

### What operating system are you running Bazel on?
linux

### What's the output of bazel info release?
`release 0.20.0`
### Have you found anything relevant by searching the web?
I am aware of the execution log parser ( --experimental_execution_log_file), but would prefer to obtain this via BEP as we are already using BEP for other purposes, see #4776

I am also aware that in #6567 @ulfjack was [apprehensive about including target specific cache information to BEP](https://github.com/bazelbuild/bazel/issues/6567#issuecomment-439844840) for non-test targets. I believe my request is different. My desire is to get aggregate cache performance in a more structured manner.

**Comment by petroseskinder** [comment]
@aiuto is there any reason this wasn't labeled as [category:BEP](https://github.com/bazelbuild/bazel/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22category%3A+BEP%22+)

**Comment by buchgr** [comment]
@petroseskinder your request sounds reasonable to me. it's effectively the same information that we include in stdout already but in a machine readable format. any objections @ulfjack @ericfelly @lfpino ?

**Comment by ulfjack** [comment]
I don't have a strong opinion either way. Including is sounds reasonable to
me.

**Comment by ericfelly** [comment]
No objections from me.

**Comment by lfpino** [comment]
No objections from my part.

**Comment by keith** [comment]
Until this is supported by the BEP is there another way to get these metrics anyone can suggest?

**Comment by buchgr** [comment]
@keith you can parse it from the command line output?

**Comment by keith** [comment]
Parsing that seemed a bit unstable. Since I posted here we ended up writing a tool to parse the execution log for this info.

**Comment by GabrielGhe** [comment]
We also ended up parsing the progress messages to get this information, but it really should be in the `BuildMetrics` message.

Is there a plan for this ticket?

**Comment by coeuvre** [comment]
I will look into this feature.

**Comment by or-shachar** [comment]
Hey,
Reviving this thread if I may... At Wix we collect this info straight form invocation log, which is not that stable like @keith mentioned. @coeuvre - any updates about that?

Thanks a lot!

**Comment by brentleyjones** [comment]
This is still a desired feature 🙏.
