### ISSUE TITLE
broken docs for https://docs.bazel.build/versions/master/command-line-reference.html#license 

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/bazel#7715]
Open https://docs.bazel.build/versions/master/command-line-reference.html#license

This chapter is labeled "License Options" and contains one flag that looks completely unrelated.

**Comment by aiuto** [comment]
The problem is that  --bep_publish_used_heap_size_post_build   is in the wrong section. Giving it to the performance team since it looks like they added the flag.
