### ISSUE TITLE
Launcher.cc on Windows: backslash problems with msys leads to file not found

### ISSUE THREAD

**Issue by aimoehi** [bazelbuild/bazel#7720]
### Description of the problem / feature request:

launcher.cc gets called with wrong command line, using default windows path containing backslashes instead of slashes. as it is run in msys, the path gets shorten because the backslash is interpreted. Only happens on windows with msys2 command

also it runs the program as a command line, not calling the .exe and passing the rest as a argument

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> LAUNCHER ERROR: Cannot launch process: "python.exe" 
> C:\users\XXX\_bazel_XXX\ge7islmr\execroot\bazel-
> out\host\bin\platform\bazel\tools\generator.zip bazel-out/x64_windows-fastbuild/generator.h 
> Reason: (error: 2): File not found.

when running the command seperately it the problem is visible:
> $ "python.exe" C:\users\XXX\_bazel_XXX\ge7islmr\execroot\bazel-out\host\bin\platform\bazel\tools\generator.zip bazel-out/x64_windows-fastbuild/generator.h

> C:\bazel\Python3\python.exe: can't open file 'C:usersXXX_bazel_XXXge7islmrexecrootbazel-outhostbinplatformbazeltoolsgenerator.zip': [Errno 2] No such file or directory

### Fix-Idea:
in launcher.cc file try to replace '\\' (github even did it so too, i needed double-backslashes to unescape) ) in Cmdline.cmdline with '/' before executing the command or somewhere on around it.

### What operating system are you running Bazel on?

Windows 7 x64 
Bazel 0.23.2 release

**Comment by laszlocsomor** [comment]
Thanks for reporting. How can we repro?

**Comment by aimoehi** [comment]
i just found out you can bypass the problem by adding commandline to bazel:
>--python_path="c:/bazel/Python3/python.exe"

so apparently the default (>where python) doesnt work

**Comment by laszlocsomor** [comment]
Repro: `bazel run` any py_binary from MSYS.

**Comment by laszlocsomor** [comment]
I believe everything is working fine here.

The `bazel run` seems to have failed because `python.exe` was not on the path, not because of the backslashed paths. I see the same if I remove python from my PATH and ignore all bazelrc files.

Then @aimoehi ran python with an absolute path (`C:\bazel\Python3\python.exe`), but used the backslashed path -- that didn't work in MSYS because Bash thought the backslahes were escaping the subsequent characters.
