### ISSUE TITLE
Config setting with msvc compiler constraint appears to be never selected

### ISSUE THREAD

**Issue by oakad** [bazelbuild/bazel#7730]
Tested with bazel 0.23.1

I'm trying to use the following construct to `select` compiler specific code:
```
config_setting(
	name = "windows_msvc",
	constraint_values = [
		"@bazel_tools//platforms:windows",
		"@bazel_tools//tools/cpp:msvc",
	],
	visibility = ["//visibility:public"],
)
```
Unfortunately, it appears that select clauses predicated with ":windows_msvc" are never selected. No errors are being reported and I have tried several compiler/cpu command line flag combinations as well as some custom `...cpp:cc_compiler` constraint values to no avail.

If I comment out the "msvc" line everything works as expected, apart from the fact that the build becomes unsuitable for msys.

It appears to me that a minor bug of some sort may exist within the msvc toolchain definitions.

**Comment by laszlocsomor** [comment]
@katre : Could you please help triaging?

**Comment by katre** [comment]
The `config_setting.constraint_values` are matched against the target platform, not the selected toolchain. I suspect that this is happening because no platform is setting the `:msvc` constraint.

How are you selecting the msvc compiler in the first place? If you are using the `--compiler` flag, then your `constraint_setting` should also be using that.

**Comment by oakad** [comment]
@katre Of course I tested various variants.

> bazel build --compiler msvc ...
> in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'x64_windows' and compiler 'msvc'.

Ok, another try:

> build:msvc --compiler msvc-cl ...

Works, but there's no constraint to select `msvc-cl`.

Let's try to create a custom constraint value:

```
constraint_value(
	name = "msvc-cl",
	constraint_setting = "@bazel_tools//tools/cpp:cc_compiler",
)

config_setting(
	name = "windows_msvc",
	constraint_values = [
		"@bazel_tools//platforms:windows",
		#"@bazel_tools//tools/cpp:msvc",
		":msvc-cl",
	],
	visibility = ["//visibility:public"],
)
```

No errors reported, but config is not selected  - default select clause gets triggered.

Which brings me to a more general question: is there a setting or aspect to make bazel print the state of constraints and selected configs?

**Comment by katre** [comment]
I am sorry that I was not clear: do not use the msvc constraint value as part of your config_setting.

Since you are setting the flag `--compiler`, use that in the config_setting:
```
config_setting(
    name = "windows_msvc",
    values = {
        "compiler": "msvc",
    },
)
```

This config_setting will match whenever the build has the flag `--compiler msvc`.

**Comment by laszlocsomor** [comment]
@katre : Thanks for answering! Is there a Bazel bug here?

**Comment by katre** [comment]
No, there is no bug.

I should probably work with @hlopko to remove the confusing compiler constraint_setting, however.

**Comment by laszlocsomor** [comment]
Thanks!

**Comment by oakad** [comment]
There is a bug.

Allow me to repeat:

> bazel build --compiler msvc ...
> in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'x64_windows' and compiler 'msvc'.

**Comment by katre** [comment]
Re-opening and assigning to @laszlocsomor to figure out why the `--compiler` flag isn't working as expected.

**Comment by hlopko** [comment]
@oakad I think you have to use `bazel build --compiler msvc-cl`, that's the compiler used by our autoconfigured toolchain.

If you want to decouple your select from whether we use `--crosstool_top`, `--cpu`, and `--compiler` to select the C++ toolchain, or platforms/toolchains, you can use https://source.bazel.build/bazel/+/fc69ecd1824d1f318a7a18d5a955040eed23c6ea:tools/cpp/compiler_flag.bzl.

Does that help?

**Comment by laszlocsomor** [comment]
@hlopko : Please help triaging this bug. Shall we improve documentation? If so, how?

**Comment by laszlocsomor** [comment]
@hlopko, What shall we do here? Is "type: documentation" accurate?

**Comment by meisterT** [comment]
@oakad anything needs to be done here?

**Comment by oakad** [comment]
Don't know. I'm avoiding msvc now (clang on msys will be much welcome, though, as mentioned in my other ticket).
