### ISSUE TITLE
Verifying bazel releases installation

### ISSUE THREAD

**Issue by placidchat** [bazelbuild/bazel#7732]
The bazel release has a sig file that is can be used to verify the sh file, but usually this sig file is used to verify the sha256 file. Either choose to verify the shasum or not remove it from use.

**Comment by meisterT** [comment]
cc @meteorcloudy

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
