### ISSUE TITLE
No such package remotejdk_win

### ISSUE THREAD

**Issue by ozio85** [bazelbuild/bazel#7734]
### Description of the problem / feature request:

When trying to run GoogleTest on windows, I get:
"bazel_tools/tools/jdk/BUILD:305:1: no such package '@remotejdk_win//': java.io.IOException: thread interrupted and referenced by '@bazel_tools//tools/jdk:remote_jdk'"

According to what I have read in the manual, it seems that this package should be downloaded automatically? I am working behind a proxy, so this can be a factor as well. However, all other workspace rules works, so my question is then: Why is remotejdk_win special?

I can get it to work by selecting my local java installation:
**--host_javabase=@local_jdk//:jdk**

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have provided a minimal repro, that use GoogleTest and runs a simple unittest:
[Repro.zip](https://github.com/bazelbuild/bazel/files/2970467/Repro.zip)

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

0.22.0, (tested also with 0.23.1, same behavior)

###  Have you found anything relevant by searching the web?

- GitHub issues:
https://github.com/angular/angular/issues/27508
https://github.com/bazelbuild/bazel/issues/6313

### Any other information, logs, or outputs that you want to share?

[Repro.zip](https://github.com/bazelbuild/bazel/files/2970467/Repro.zip)

**Comment by Globegitter** [comment]
We where also seeing something similar just now in ci:

```
(11:19:46) ERROR: error loading package '': Encountered error while reading extension file 'python/pip.bzl': no such package '@io_bazel_rules_python//python': java.io.IOException: thread interrupted
(11:19:46) ERROR: error loading package '': Encountered error while reading extension file 'python/pip.bzl': no such package '@io_bazel_rules_python//python': java.io.IOException: thread interrupted
```

Maybe something failed during download of the external package and poisoned the cache?

**Comment by ozio85** [comment]
For me.. no .. I can start from a fresh build, and still get the error..

**Comment by ozio85** [comment]
It seems it is some kind of combination of proxy settings, and settings not forwarded correctly. I have managed to get it to work, so I will close this issue.

One problem is that even if i wanted to have it local (i do not want to download java), even if I set host_javabase and javabase, Bazel will try to download remote_java_tools_windows..
