### ISSUE TITLE
Prune old build artifacts

### ISSUE THREAD

**Issue by pspeter3** [bazelbuild/bazel#775]
Is there a way to prune the artifacts in `bazel-bin` that are no longer in the build graph? Specifically, I'd like to not have to run a full clean to vacuum old artifacts.

**Comment by damienmg** [comment]
bazel clean --expunge?

**Comment by pspeter3** [comment]
My understanding was --expunge removed even more things than `bazel clean`? I want to leave legitimate build products but prune artifacts that are no longer part of the build graph. I may be misunderstanding --expunge however.

**Comment by damienmg** [comment]
Oh ok. Yes expunge clear the cache. I don't know if such a thing exists.

**Comment by hanwen** [comment]
It would be very hard to figure out what to delete, since you'd have to enumerate all possible outputs in the entire tree, and those outputs can change depending on compilation mode, target platform, compiler, etc.

**Comment by hanwen** [comment]
closing because I think this is infeasible..............
