### ISSUE TITLE
Bazed dosen't load CROSSFILE next to BUILD file when run inside a 2019 core container

### ISSUE THREAD

**Issue by carpenterjc** [bazelbuild/bazel#7751]
### Description of the problem / feature request:

I have a 2019 core server running docker under which I intend to run Bazel. I map in my source directory to c:\src inside the container. When I run Bazel inside a docker container it will not detect CROSSFILES which are located next to the BUILD files. 

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

On 2019 core server, I build a docker image based off : https://github.com/Microsoft/vs-dockerfiles/tree/master/native-desktop where I have additionally used chocolaty to installed bazel.

I run up process monitor on the outer 2019 server, and can see processes accessing BUILD files, but not the CROSSFILE. The only time it opens CROSSFILES it looks in the Bazel installation layer. 

### What operating system are you running Bazel on?
2019 core under Docker. 

> Replace this line with your answer.

### What's the output of `bazel info release`?

C:\src>bazel info release
INFO: Invocation ID: 669c0151-52fc-46e9-81cc-1ad1fe6c4d34
release 0.22.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

No, the issues seem to be conflaited with using the default CROSSTOOL, no information on not detecting a custom CROSSTOOL. 

### Any other information, logs, or outputs that you want to share?

I cannot see it enumerating the directory to find the CROSSTOOL file. 
My suspicion it is not getting as far as CcSkyframeSupportFunctions.java:95 specifically I wonder if the CROSSTOOL file can't be found in some form of cache.

I have tried various versions of Bazel including 0.23.2

When this is run on  the container, there is a crash when it is trying to auto-detect the visual studio location. However autodetction is not needed is its completely specified in the CROSSTOOL file. 

> Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=128
INFO: Options provided by the client:
  'build' options: --python_path=C:/Python27/python.exe
INFO: Reading rc options for 'build' from c:\src\.bazelrc:
  'build' options: --crosstool_top=//tools/config:my_toolchains --features=static_link_msvcrt --features=fully_static_link
DEBUG: C:/src/imports/thirdparty/zlib/BUILD:15:1: Evaluating Zlib build file
DEBUG: C:/src/tools/config/BUILD:107:1: Evaluating BUILD file next to CROSSTOOL
ERROR: no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/users/containeradministrator/_bazel_containeradministrator/pok7sxjd/external/bazel_tools/tools/cpp/cc_configure
.bzl", line 52
                configure_windows_toolchain(repository_ctx)
        File "C:/users/containeradministrator/_bazel_containeradministrator/pok7sxjd/external/bazel_tools/tools/cpp/windows_cc_c
onfigure.bzl", line 341, in configure_windows_toolchain
                _find_missing_vc_tools(repository_ctx, vc_path)
        File "C:/users/containeradministrator/_bazel_containeradministrator/pok7sxjd/external/bazel_tools/tools/cpp/windows_cc_c
onfigure.bzl", line 244, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, vc_path, tool)
        File "C:/users/containeradministrator/_bazel_containeradministrator/pok7sxjd/external/bazel_tools/tools/cpp/windows_cc_c
onfigure.bzl", line 217, in find_msvc_tool
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2017/TestAgent/VC/Tools/MSVC (No such file or directory)
ERROR: Analysis of target '//imports/thirdparty/zlib:zlib' failed; build aborted: no such package '@local_config_cc//': Tracebac
k (most recent call last):
        File "C:/users/containeradministrator/_bazel_containeradministrator/pok7sxjd/external/bazel_tools/tools/cpp/cc_configure
.bzl", line 52
                configure_windows_toolchain(repository_ctx)
        File "C:/users/containeradministrator/_bazel_containeradministrator/pok7sxjd/external/bazel_tools/tools/cpp/windows_cc_c
onfigure.bzl", line 341, in configure_windows_toolchain
                _find_missing_vc_tools(repository_ctx, vc_path)
        File "C:/users/containeradministrator/_bazel_containeradministrator/pok7sxjd/external/bazel_tools/tools/cpp/windows_cc_c
onfigure.bzl", line 244, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, vc_path, tool)
        File "C:/users/containeradministrator/_bazel_containeradministrator/pok7sxjd/external/bazel_tools/tools/cpp/windows_cc_c
onfigure.bzl", line 217, in find_msvc_tool
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2017/TestAgent/VC/Tools/MSVC (No such file or directory)
INFO: Elapsed time: 13.231s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (15 packages loaded, 16 targets configured)
    Fetching @local_config_cc; fetching

**Comment by carpenterjc** [comment]
I have further explored with process monitor and have found when it works on windows 10 it will enumerate the directory which contains my cross tool before the target. When it doesn't work will only look for the BUILD file, and does so after enumerating the target BUILD files.

**Comment by carpenterjc** [comment]
I have found and enabled a debug environmental variable. CC_CONFIGURE_DEBUG. Here are the results of that. 
[CC_CONFIGURE_DEBUG.txt](https://github.com/bazelbuild/bazel/files/2987888/CC_CONFIGURE_DEBUG.txt)

**Comment by hlopko** [comment]
Are you passing `--crosstool_top=//path_to/your/custom:cc_toolchain`? Bazel will not try to use the builtin autoconfigured toolchain when not needed. You can follow https://docs.bazel.build/versions/master/tutorial/cc-toolchain-config.html and see where things start failing.

**Comment by carpenterjc** [comment]
Yes, our .bazelrc file looks like this: 

```
build --crosstool_top=//tools/config:my_toolchains
build --features=static_link_msvcrt
build --features=fully_static_link

# Define platforms. This must match the setup in toolchain/BUILD that defines the
# configurations that are used for select().
build:win_x64_rel -c opt --cpu=x64_windows
build:win_x64_dbg -c dbg --cpu=x64_windows
build:win_x86_rel -c opt --cpu=x86_windows
build:win_x86_dbg -c dbg --cpu=x86_windows

# Prevent it from downloading the JDK https://github.com/bazelbuild/bazel/issues/6865#issuecomment-447261288
build --host_javabase @local_jdk//:jdk
```

We will then build as long as we set BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN = 1 in the environment.

**Comment by hlopko** [comment]
Oh I finally know what's going on. Because of `register_toolchains` call the `@local_config_cc` is always executed (https://source.bazel.build/bazel/+/8bd7e4822ed96615ccac77cc40ca96eddc74c510:tools/cpp/cc_configure.bzl;l=93). BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN = 1 is your only workaround today.

The proper fix on our side is to decouple repository with `toolchain` rules from the repository with `cc_toolchain` rules, afaiu. Does it make sense to you @katre?

**Comment by katre** [comment]
Yes, I think that makes sense, but we need to make sure that when users want to autodetected cc toolchain, it does get registered.

**Comment by hlopko** [comment]
To double check.

Say `@local_config_cc_toolchains` is the repo with `toolchain` rules that reference `@local_config_cc` with actual `cc_toolchains` in it.

So `@local_config_cc_toolchains` will contain:

    native.register_toolchains("//...")

and `@local_config_cc_toolchains//:BUILD` we will have:

    toolchain(
      name = "local",
      ...
      toolchain = "@local_config_cc//:local_cc_toolchain",
    )

and `@local_config_cc` does the autoconfiguration and `@local_config_cc//:BUILD` has:

    cc_toolchain(name = "local_cc_toolchain", ...)

Now, is my hope correct that `@local_config_cc` will not be fetched until `@local_config_cc_toolchains//:local` is selected? Or Bazel will load the repository and the package, and all toolchains in it, but it will only analyze the selected toolchain?

**Comment by katre** [comment]
Your hope is correct: Bazel analyzes `toolchain()` rules, but the `toolchain.toolchain` attribute is `LABEL_NODEP`, so that isn't followed until a specific toolchain is selected during resolution.

**Comment by hlopko** [comment]
Great! Then this can be fixed as part of https://github.com/bazelbuild/bazel/issues/6926.
