### ISSUE TITLE
Windows: --test_env=Foo is ignored if "Foo" is not the exact casing

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#7761]
### Description of the problem / feature request:

Envvar names are case-insensitive on Windows: `%FOO%` and `%Foo%` are equivalent.
`bazel test --test_env=FOO` should work even if `%Foo%` is defined, but it doesn't; only with `--test_env=Foo`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`BUILD`:
```
sh_test(
    name = "envvars",
    srcs = ["envvars.sh"],
)
```

`envvars.sh`:
```
#!/bin/bash
env | grep "blah"
false
```

```
C:\src\tmp>set Foo=blah

C:\src\tmp>set BAR=blah

C:\src\tmp>bazel test --test_output=errors //:envvars --test_env=Foo --test_env=Bar
...
==================== Test output for //:envvars:
Foo=blah
================================================================================

C:\src\tmp>bazel test --test_output=errors //:envvars --test_env=Foo --test_env=BAR
...
==================== Test output for //:envvars:
Foo=blah
BAR=blah
================================================================================

C:\src\tmp>bazel test --test_output=errors //:envvars --test_env=FOO --test_env=BAR
...
==================== Test output for //:envvars:
BAR=blah
================================================================================
```

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

`release 0.23.1`

**Comment by laszlocsomor** [comment]
I think this is WAI, esp. in light of https://github.com/bazelbuild/bazel/issues/8799.

But Bazel should probably warn if there's an envvar with the same name but different casing, so I'll keep this bug open.

**Comment by laszlocsomor** [comment]
I decided to make this a warning, not an error, because some things (namely "bazel info") work fine when output paths have a space.

**Comment by laszlocsomor** [comment]
Envvar names must match casing for `--action_env` too.

Bazel could warn the user on Windows if envvars in `--action_env` or `--test_env` are wrongly cased.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
