### ISSUE TITLE
Building on macOS without dependency_file feature fails

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#7769]
### Description of the problem / feature request:

If you try and disable the `dependency_file` feature that's defined here: https://github.com/bazelbuild/bazel/blob/fc69ecd1824d1f318a7a18d5a955040eed23c6ea/tools/osx/crosstool/cc_toolchain_config.bzl.tpl#L5249-L5272

Your build will fail with:

```
ERROR: /Users/ksmiley/dev/bazel/examples/cpp/BUILD:3:1: error while parsing .d file: /private/var/tmp/_bazel_ksmiley/5ef608190b288a339c09ffb210204e7f/execroot/io_bazel/bazel-out/darwin-fastbuild/bin/examples/cpp/_objs/hello-lib/hello-lib.d (No such file or directory)
Target //examples/cpp:hello-lib failed to build
```

The goal of disabling this feature is that the `.d` file generated contains absolute paths to header files on the host system which breaks remote caching (related to #1000)

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
bazel build examples/cpp:hello-lib --features=-dependency_file
```

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 0.23.1

This also happens with bazel master at cf1777b4795e47094ff3426fdbc19968a8dd6a6c

**Comment by keith** [comment]
The execution log from my real test case makes it very clear why this fails:

```
listed_outputs: "bazel-out/darwin-fastbuild/bin/_objs/CYaml/writer.d"
listed_outputs: "bazel-out/darwin-fastbuild/bin/_objs/CYaml/writer.o"
remotable: true
cacheable: true
progress_message: "Compiling Sources/CYaml/src/writer.c"
mnemonic: "CppCompile"
actual_outputs {
  path: "bazel-out/darwin-fastbuild/bin/_objs/CYaml/writer.o"
  digest {
    hash: "58d157761ee6f7d002527f6de3cd89ad81b0ffad34b71bf162987c71f3af854f"
    size_bytes: 2460
    hash_function_name: "SHA-256"
  }
}
runner: "darwin-sandbox"
```

You can see the rule defines the `.d` even with that feature disable, so it is not produced

**Comment by keith** [comment]
I've submitted a possible fix for this https://github.com/bazelbuild/bazel/pull/7771

**Comment by hlopko** [comment]
Can this be closed now?

**Comment by keith** [comment]
AFAIK this is still an issue, but if this is a won't fix we can close it?
