### ISSUE TITLE
using maven_jar extension in windows and having ubuntu shell installed seems to be broken

### ISSUE THREAD

**Issue by MarkaRagnos0815** [bazelbuild/bazel#7781]
### Description of the problem / feature request:

using maven_jar extension in windows and having ubuntu shell installed seems to be broken

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- install ubuntu 18.04 bash in windows (you can get it from MS store)
- load maven_jar plugin -> load("@bazel_tools//tools/build_defs/repo:maven_rules.bzl", "maven_jar"")
- add any external maven dependency (like apache commons lang 3) via maven_jar rule to workspace
- setup a java library having the maven jar as dep 
- build the project 
- see errors (see additional information)

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 0.23.2

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

there seems to be a lot of different errors
1. on my system, it complains about missing maven dependency plugin. I need to use mvn and download it manually and inside ubuntu shell (or point the to the same local repository). 
2. after downloading the dependency plugin it downloads all maven artifacts but fails to open any jar because the created link seems to be broken
3. inside the external jar directory the creates a folder structure starting with drive letter and an unprintable character like (because ":" is forbidden in windows).
4. removing the ubuntu shell leads to some other issue because it seems to ignore BAZEL_SH variable (which points in my case to msys2 bash)
either usage BAZEL_SH variable is broken or BAZEL_SH isn't used anymore.

**Comment by jin** [comment]
We have just released a new approach to resolve Maven deps that doesn't depend on any system dependencies. It also works on Windows, please try it out: https://github.com/bazelbuild/rules_jvm_external/

cc @dkelmer

**Comment by dslomov** [comment]
We recommend to switch to  https://github.com/bazelbuild/rules_jvm_external/

**Comment by MarkaRagnos0815** [comment]
thanks for your reply, but the extension needs to have plain user/password which is unacceptable to me.

**Comment by jin** [comment]
https://github.com/bazelbuild/rules_jvm_external/issues/80 contains some discussion on this, and alternative approaches that don't rely on checked in plaintext passwords.

**Comment by MarkaRagnos0815** [comment]
thanks, seems to be a temporary solution. i don't like the idea of resolving maven transitive dependencies. My question is: will someone from bazel dev group fix the issue with maven extension?

btw. the original maven_jar rule works so far until I need to access our internal repository because it seems not to support authentication.

**Comment by dkelmer** [comment]
I just reread your report and noticed you're not using the native `maven_jar` rule, but rather the other starlark `maven_jar` rule. However, everything I said above applies to that rule as well. It will no longer be supported once `jvm_maven_import_external` reaches feature parity

**Comment by MarkaRagnos0815** [comment]
@dkelmer thanks for your answer:
- yes i am using starlark maven_jar, native maven_jar rule works as expected unless you need authentication
- ok, using jvm_import_external may help, but I need authentication without having a user/password pair somewhere plain (not sure how they will implement this)
- I am not sure, but my issue seems to have an second issue which I am not sure about. it seems bazel is not using the BAZEL_SH env variable und using just "bash" as command. As long as I have an ubuntu shell in my windows it will use this shell and not the one provided in the BAZEL_SH var.

**Comment by dkelmer** [comment]
If the native maven_jar rule is working for you, then you could use it in conjunction with the [maven_server](https://docs.bazel.build/versions/master/be/workspace.html#maven_server) rule to get the authentication. 

Of course you would eventually need to migrate to the jvm_import_external rules, and I apologize for the churn, but we are actively trying to get these rules into a robust and user friendly state asap :)

**Comment by MarkaRagnos0815** [comment]
maven_server rule does not work with native maven_jar rule or at least in the way I am using maven. I have an settings.xml and settings_security.xml according to http://maven.apache.org/guides/mini/guide-encryption.html. It fails and maven server log shows a authentication error in log

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
