### ISSUE TITLE
pass platform and execution requirements to xml generating spawn

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#7794]
The fix for https://github.com/bazelbuild/bazel/issues/4608 splits a test action into two spawns. The first spawn runs the actual test and the second spawn declares the `test.log` as an input and produces a test.xml file. 

We found an issue where a `sh_test` target was marked as `no-remote` but the test.xml-generating spawn would not get this tag passed along and would thus run remotely.

The proposed fix is to pass along the execution requirements and platform of the test spawn to the test.xml-generating spawn.

**Comment by meteorcloudy** [comment]
Does this issue only happen when `test.log` is very large?

**Comment by buchgr** [comment]
no it's independent of the test.log size.

**Comment by meteorcloudy** [comment]
The workaround for this issue is to use `--experimental_split_xml_generation=false`
