### ISSUE TITLE
Bazel 0.24.0 fails on `dynamic_runtime_libs` coming from toolchain

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/bazel#7795]
Relates to #6968 

### Description of the problem / feature request:

My builds ran fine on bazel 0.23.X.

I tried to use bazel 0.24.0rc7 on one of our repo that is used `--crosstool_top=@bazel_toolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:toolchain` and `--extra_toolchains=@bazel_toolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/cpp:cc-toolchain-clang-x86_64-default` from bazel toolchain commit https://github.com/bazelbuild/bazel-toolchains/commit/31b5dc8c4e9c7fd3f5f4d04c6714f2ce87b126c1 

I got this error:
```
12:07:26  ERROR: /home/builduser/.cache/bazel/_bazel_builduser/d95f300509f1e228190b211abeba17c4/external/bazel_toolchains/configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default/BUILD:57:1: @bazel_toolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:cc-compiler-k8: no such attribute 'dynamic_runtime_libs' in 'cc_toolchain' rule
```

I didn't see anything in documents of this release about deprecating `dynamic_runtime_libs`. It may be just a missing documentation.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

Bazel 0.24.0rc7

###  Have you found anything relevant by searching the web?

Didn't see anything interesting .. Other than a note for bazel [0.22.0]( https://github.com/bazelbuild/bazel/releases/tag/0.22.0) that `dynamic_runtime_libs` is optional.

====
Note: Changing the toolchain and crosstool to point to `/bazel_toolchains/configs/ubuntu16_04_clang/1.1/bazel_0.22.0/*` solved the issue because there the attribute `dynamic_runtime_libs` does not exist.
Still I think something needs to be documented about it.

**Comment by or-shachar** [comment]
@katre  - not sure how to provide steps to reproduce as we're running our builds with Remote Execution service I can share our `.bazelrc` if that's helpful or you can take some repo like `rules_scala` and try to play with it's bazelrc

**Comment by hlopko** [comment]
This was guarded by https://github.com/bazelbuild/bazel/issues/6942. It was announced in https://blog.bazel.build/2019/01/28/bazel-0.22.0.html. 0.24 release notes will have the announcement that this flag has been flipped.

**Comment by or-shachar** [comment]
Great! thanks!
