### ISSUE TITLE
Cleanup flags and code paths for legacy Python version api and semantics

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#7797]
Tracking bug for deleting `--incompatible_remove_old_python_version_api`, `--incompatible_allow_python_version_transitions`, and the code supporting these flags.

The flags are being flipped in Bazel 0.25. Google still uses these flags internally, but we expect to be migrated for them soon as well, so this might happen in the near term (O(weeks)).

Corresponds to implemented feature #6583.

**Comment by brandjon** [comment]
`--force_python`, `--incompatible_remove_old_python_version_api`, and `--incompatible_allow_python_version_transitions` are now all no-ops. Still need to remove the actual flags themselves.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
