### ISSUE TITLE
Hard to find documentation on http_archive, git_repository and friends

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#7798]
The following rules are documented on HEAD and 0.23.0: https://docs.bazel.build/versions/0.23.0/be/workspace.html

```
bind
local_repository
maven_jar
maven_server
new_local_repository
xcode_config
xcode_version
```

It's missing the native rules that have been moved out to Starlark from 0.23.0 onwards. The [documentation for 0.22.0](https://docs.bazel.build/versions/0.22.0/be/workspace.html) shows the original list:

```
bind
git_repository
http_archive
http_file
http_jar
local_repository
maven_jar
maven_server
new_git_repository
new_http_archive
new_local_repository
xcode_config
xcode_version
```

Can we reinstate the documentation for the Starlark implementations into this page, or add a link to the generated Stardocs?

**Comment by aehlig** [comment]
Note that the [documentation on `http_archive` etc](https://docs.bazel.build/versions/master/repo/index.html) is online, just a bit harder to find. Will work on adding more links.

**Comment by jin** [comment]
Thank you!

**Comment by aehlig** [comment]
Under review: https://bazel-review.googlesource.com/c/bazel/+/93753
