### ISSUE TITLE
Can't supply default_provisioning_profile with 0.1.3

### ISSUE THREAD

**Issue by mrdomino** [bazelbuild/bazel#780]
Until now, I've been setting the default_provisioning_profile issue by modifying tools/objc/BUILD in the base workspace (or in the tree's workspace if I've had bazel vendored). But now it seems that the profile is being extracted from the bazel binary itself, so I can't modify it.

This seems like a really basic need for iOS development -- like no iOS targets will build for me at the moment -- so it's possible that I'm doing something wrong or am too far off the beaten path without realizing it. In that case, advice would be appreciated.

**Comment by mrdomino** [comment]
The exact error I'm getting, fwiw, is:

```
ERROR: Loading of target '@bazel_tools//tools/objc:default_provisioning_profile' failed; build aborted: no such target '@bazel_tools//tools/objc:default_provisioning_profile': target 'default_provisioning_profile' not declared in package 'tools/objc' defined by /private/var/tmp/_bazel_steven/18e5bedf6c320a14ee822ce84f434040/external/bazel_tools/tools/objc/BUILD.
ERROR: Loading failed; build aborted.
```

I've seen this pretty often in the past. It's been a thing for so long that I don't remember when or how I happened upon the workaround described above.

**Comment by damienmg** [comment]
Note that you can get the legacy behavior by putting `build --default_ios_provisioning_profile //tools/objc:default_provisioning_profile` in your .bazelrc file.

**Comment by mrdomino** [comment]
@damienmg That option doesn't seem to be recognized with bazel 0.1.3, although I do see it in the source...

For now, I was able to work around it by compiling a custom version of 0.1.3 with the profile specified in tools/objc/BUILD.

**Comment by damienmg** [comment]
it is fixed at head

**Comment by mrdomino** [comment]
Awesome, thank you.
