### ISSUE TITLE
$foo attributes are supposed to be inaccessible to Starlark

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#7801]
@alandonovan pointed out that a user can use the private attributes of a rule using `**kwargs`.

`BUILD`:
```
load(":a.bzl", "macro")

macro()
```

`a.bzl`:
```
def _r_impl(ctx):
    print(ctx.attr._hidden)

r = rule(
    implementation = _r_impl,
    attrs = {
        "_hidden": attr.string(),
    },
)

def macro():
    r(**{"name": "foo", "$hidden": "abc"})
```

The name `$hidden` was supposed to be an internal detail, but it can leak to the user as shown here. This bug affects both native rules and Starlark rules.

Proposed fix: the rule function should reject setting any internal attribute.

**Comment by brandjon** [comment]
Changing type to bug because I think `incompatible-change` is for the tracking bug of a migration/flag. Also this could arguably be implemented without a flag because it's a bugfix of a behavior users shouldn't be depending on.
