### ISSUE TITLE
Provide a way to modify or construct a custom JavaInfo

### ISSUE THREAD

**Issue by timpeut** [bazelbuild/bazel#7803]
The current JavaInfo constructor does too much work under the hood to fit all use cases - there is no way to create a JavaInfo with specific values for each field. In our case, we want to remove the `transitive_XXX` fields while maintaining all others.

Two options come to mind:
- Provide a way to decompose a JavaInfo into its components and then reassamble it with modificatons
- Provide a simple builder-style constructor that allows setting individual attributes

**Comment by iirina** [comment]
@timpeut Can you describe a bit more your use case? I'm interested in why removing the transitive fields is required. As a first thought this sounds like something that aspects could solve.

**Comment by timpeut** [comment]
This is no longer required.
