### ISSUE TITLE
Expose the Python version of a target to downstream dependencies

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#7806]
If you depend on a `py_library`, `py_binary`, or `py_test`, you may wish to know that target's `python_version` value (`"PY2"` or `"PY3"`). This value is set by the configuration, though in the case of `py_binary` and `py_test` the configuration itself is set by an attribute on the target.

This would be useful e.g. for aspects that traverse Python targets, like IntelliJ's Bazel plugin.

We could probably add `python_version` as a field of [`PyInfo`](https://docs.bazel.build/versions/master/skylark/lib/PyInfo.html). We may also want to consider adding it to the (currently unused) Python Starlark fragment (`ctx.fragments...`).

**Comment by brandjon** [comment]
For the case of `py_binary` and `py_test`, the same information could also be obtained using #7805 and accessing `PyRuntimeInfo.python_version`.

**Comment by brandjon** [comment]
I don't want to add anything to `ctx.fragments` for Python because I don't want to add more native rule logic. It should be possible to retrieve the current target's Python version if the rule is made to have an implicit dependency on `@bazel_tools//tools/python:python_version`. Then you can consume [the FeatureFlagInfo provider](https://github.com/bazelbuild/bazel/blob/b5d534d8d683e6869f64b74ee067c02d5e4deab1/tools/python/python_version.bzl#L39).

I think we can do this for 0.27.

**Comment by brandjon** [comment]
Reconsidering this FR, I'm not sure this is something we really want to add.

If the `PyInfo.python_version` field just means "The Python version of this target, as specified by its configuration", then we're really just duplicating information from the configuration. Presumably in most cases the parent target that would consume this provider already knows its child's configuration. (Maybe that's not true for aspects though.) Having this information be repeated risks letting it get inconsistent, e.g. due to a poorly defined rule.

Maybe we should just rely on getting the `PyRuntimeInfo` of executable targets (#7805), and see if we need to go further after that.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
