### ISSUE TITLE
Bazel requires remote_jdk10 to run a py_test rule

### ISSUE THREAD

**Issue by StephenWassell** [bazelbuild/bazel#7817]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

I'm trying to run a py_test rule on a machine with no internet connection but it fails because bazel tries to download remote_jdk10. If I only have cc_ rules there's no problem.

Setting any or all of these options doesn't seem to help:
--noincompatible_use_remote_java_toolchain --noincompatible_use_remote_host_java_toolchain
--java_toolchain=@local_jdk//:jdk
--host_java_toolchain=@local_jdk//:jdk

If I have openjdk 1.8.0 installed on the machine, specifying @local_jdk//:jdk results in a series of runtime exceptions (see attached log). [openjdk-errors.log](https://github.com/bazelbuild/bazel/files/2997357/openjdk-errors.log)

### Feature requests: what underlying problem are you trying to solve with this feature?

Run py_test unit tests on isolated build VMs without an internet connection.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Contents of BUILD:
```
py_test(
    name = "pytest",
    srcs = ["pytest.py"],
    data = [
    ],
)
```
Contents of pytest.py: `print("hello")`

Command to run: `bazel test //:pytest`

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 0.23.2

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/7196

### Any other information, logs, or outputs that you want to share?

Please see attached screenshot.
![bazel-wants-jdk](https://user-images.githubusercontent.com/20539874/54836387-01d7e700-4cbc-11e9-8aae-8f1085e52366.png)

**Comment by jin** [comment]
cc @iirina

**Comment by nesqi** [comment]
You can download the packages, put them in a local directory and run bazel with the  --distdir option.
see, https://github.com/bazelbuild/bazel/issues/7487#issuecomment-466064886

**Comment by iirina** [comment]
bazel tries to download remote_jdk10 for its host javabase. Trying to set `--java_toolchain` and `--host_java_toolchain` flag will not help. You need to set `--host_javabase=@local_jdk//:jdk`.

However, bazel will then try to download a java_tools zip file. To work around that, @nesqi's advice in https://github.com/bazelbuild/bazel/issues/7817#issuecomment-492650850 is helpful.

Let me know if I can help further.

**Comment by StephenWassell** [comment]
Thank you @nesqi and @iirina for the advice! I'll give those ideas a try.

**Comment by StephenWassell** [comment]
Solved! --distdir was the answer. It only needed one package on Linux:
https://mirror.bazel.build/openjdk/azul-zulu10.2+3-jdk10.0.1/zulu10.2+3-jdk10.0.1-linux_x64-allmodules.tar.gz
