### ISSUE TITLE
Make the dynamic strategy work without sandboxing

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/bazel#7818]
The dynamic strategy should be made to work without sandboxing.

From what I can tell from the code, it seems that this should already work... but we have observed breakages that imply otherwise—and the whole thing could be made better.

----

The reason is simple: sandboxing can still incur a huge performance penalty under some circumstances. For example, on some iOS builds, we regularly observe single compilation actions that end up with a sandbox tree with ~20k entries (counting both files and directories). Cleaning up the sandbox tree for these actions takes a _lot_ of time on macOS (think minutes under heavy load; #7527). But the problem is that this specific penalty comes from the *cleanup* of the local action, not from its execution. This means that if the remote action completes sooner than the local sandboxed action... we will issue a cancellation of the local action, which in turn will trigger its cleanup, which in turn will delay completion unnecessarily: we already got the result from remote execution; we are now just paying the price of a local cleanup.

----

As far as I know, the primary reason sandboxing is required today is because, when we have two concurrent spawns running, they will both write to the same output files. Therefore, for local actions, we must ensure that whatever command we run writes stuff to a separate tree so that, once the command completes successfully, we can move its outputs to the "final locations".

But we already protect against this by "locking" the outputs before we write to them (see `SpawnExecutionContext#lockOutputFiles()`), and we only allow a single strategy to lock the outputs at any given time.

And in fact, it seems that this should all work already with the local strategy: the local strategy locks its outputs *before* running the command (because once the command has started we have no control on *when* it will write the outputs), and the remote spawn runner will lock its outputs *before* fetching them.

If this is true, then local actions should already work fine. We need to figure out why using the local strategy causes build failures, assuming I'm not missing something obvious.

(Note: I'm leaving aside the fact that we use sandboxing to ensure all subprocesses are terminated. For iOS builds, we already run them without sandboxing in the general case and they work fine.)

----

But under this scenario, there is a downside: once we have started a local action, the remote counterpart will never be able to finish (even if it completes immediately!) because it won't be able to acquire the outputs lock. One idea to resolve this is to change the remote spawn runner to fetch output files into a temporary location (e.g. by suffixing all outputs with `.tmp`, to ensure they remain in the same file system), *without* locking the outputs. This would ensure that any fetch time is accounted to the action execution.

Once all outputs are fetched, the remote action could lock the outputs, explicitly cancel the local action to avoid races, and *then* rename the fetched `.tmp` files into the real locations. With this, we could make the local strategy run *without* locking the outputs.

CC @philwo @meisterT

**Comment by ulfjack** [comment]
Did you try running with the sandbox on tmpfs?

Another option might be to use a pure symlink sandbox and avoid the overhead of the security policy.

**Comment by jmmv** [comment]
There is no tmpfs on macOS.

I do not think the security policy is at fault here. The pain comes from creating/deleting the gigantic symlink trees. fac322b1ef7a9acbe71f3718143c0dae43fb5833 made that significantly better, but it's still a problem.

**Comment by ulfjack** [comment]
That is a common misconception. MacOS supports RAM disks, and I have used
them with Bazel at some point, but I can't say off the top of my head how
to create one.

**Comment by jmmv** [comment]
Well, RAM disks and tmpfs are very different things -- so the two statements are not conflicting.

I still don't see a reason why the dynamic scheduler *shouldn't* work without the sandbox though, and this is precisely what this bug is about.

**Comment by ulfjack** [comment]
Not really. :-p

I agree that it should work if the local strategy locks the outputs before running, but it may also reduce performance in some cases unless we find a way to interrupt the locally running action.

**Comment by jmmv** [comment]
FTR the magic command to create a ramdisk is something along the lines of:

```
disk="$(hdiutil attach -nomount ram://2048)"
diskutil erasevolume HFS+ “RAMDisk” "${disk}"
diskutil mount "${disk}"
```

**Comment by jmmv** [comment]
Unrelated to this bug, but to close on the latter suggestion: using a ramdisk makes builds slower. The same build that used to take ~4300s takes ~4800s when pointing `--experimental_sandbox_path` to a ramdisk created as above.

I don't think the performance problems are disk contention: they are either file system-level contention (which the ramdisk doesn't change because it still has a file system on top, unlike tmpfs), or higher level contention in the VFS layer.

**Comment by aiuto** [comment]
Is this really still P2?

**Comment by larsrc-google** [comment]
If I understand this correctly, it's what `--experimental_local_lockfree_output` is for. Can anyone say something more specific about the breakages without sandboxing mentioned at the start? Do they also occur with `--experimental_local_lockfree_output`?

**Comment by jmmv** [comment]
That's correct. That flag I added should allow this to work.

**Comment by larsrc-google** [comment]
Between `--experimental_local_lockfree_output`, `--reuse_sandbox_directories`, and various optimizations in the sandbox code, I believe this bug is no longer relevant.
