### ISSUE TITLE
bazel has no response, no outputs, no error messages.

### ISSUE THREAD

**Issue by 365670123** [bazelbuild/bazel#7819]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem:

bazel has no response, no outputs, no error messages.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I follow the steps on official document, and set up all environment variables. 
type 'bazel version' in powershell, but nothing happens.
I tried typing ‘bazel’ + any word, still nothing happens 

### What operating system are you running Bazel on?

windows 10 pro 64bit
bazel-0.21.0-windows-x86_64
msys2-x86_64-20180531

path:
![image](https://user-images.githubusercontent.com/32214756/54870795-45c70b00-4de6-11e9-9f89-a3bf5522ae17.png)

### What's the output of `bazel info release`?

there is no output
![image](https://user-images.githubusercontent.com/32214756/54870643-642c0700-4de4-11e9-8202-8c44d068b98b.png)

###  Have you found anything relevant by searching the web?

I found nothing.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by meteorcloudy** [comment]
Are you sure you downloaded the correct binary?
https://github.com/bazelbuild/bazel/releases/download/0.23.2/bazel-0.23.2-windows-x86_64.exe

**Comment by laszlocsomor** [comment]
Try the following commands:
- `bazel --client_debug`
- `bazel --client_debug --output_user_root=c:/tmp1`
- `set TMP=c:\tmp1 & bazel --client_debug --output_user_root=c:/tmp1`

Does any of these work? What's their output?

**Comment by 365670123** [comment]
> Try the following commands:
> 
> bazel --client_debug
> bazel --client_debug --output_user_root=c:/tmp1
> set TMP=c:\tmp1 & bazel --client_debug --output_user_root=c:/tmp1
> 
> Does any of these work? What's their output?

there is no output. nothing happens

**Comment by 365670123** [comment]
> Are you sure you downloaded the correct binary?
> https://github.com/bazelbuild/bazel/releases/download/0.23.2/bazel-0.23.2-windows-x86_64.exe

yes, I am sure, I download from github

**Comment by laszlocsomor** [comment]
After you run Bazel, what does `echo %errorlevel%` print?

**Comment by laszlocsomor** [comment]
I mean, `echo $lastexitcode` (since you are in powershell, not cmd).

**Comment by laszlocsomor** [comment]
If you copy some any .exe file (e.g. the MSYS installer) next to the Bazel binary, can you run that?

**Comment by laszlocsomor** [comment]
@365670123 :  is this issue resolved?

**Comment by 365670123** [comment]
> @365670123 :  is this issue resolved?

I don't know. I just gave up compiling tensorflow with it.

**Comment by laszlocsomor** [comment]
Thanks! Could you maybe try it with a newer version, e.g.  https://github.com/bazelbuild/bazel/releases/download/0.27.1/bazel-0.27.1-windows-x86_64.exe ?

This was a weird error and I'd like to understand it better.

**Comment by simsanutiy** [comment]
Got the same issue with both 0.29.1 and 0.26.1, tensorflow's configuration script says that command 'returned non-zero exit status 3221226356', if it will be helpful

**Comment by laszlocsomor** [comment]
@simsanutiy :
- Did you install [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) ?
- What's the output if you do this in `cmd.exe`?
  ```
  md c:\foo & cd c:\foo

  type nul > WORKSPACE

  c:\path\to\bazel.exe --client_debug info
  ```
- Do you use non-English Windows?

**Comment by simsanutiy** [comment]
@laszlocsomor :
1) Yes

2)

> Microsoft Windows [Version 10.0.18362.356]
> (c) Корпорация Майкрософт (Microsoft Corporation), 2019. Все права защищены.
> 
> C:\Users\Михалыч>md c:\foo & cd c:\foo
> 
> c:\foo>type nul > WORKSPACE
> 
> c:\foo>c:\windows\bazel.exe --client_debug info

Absolutely nothing

3) Yes

**Comment by laszlocsomor** [comment]
I suspect it's the non-English Windows. @365670123 also uses non-English.
I'll try to find a Windows box with Russian locale and do some debugging.

**Comment by laszlocsomor** [comment]
Tried installing Russian language pack on an English Windows but that doesn't trigger this bug for me, cmd.exe stays English.

@simsanutiy : could you try another thing please:
```
c:\windows\bazel.exe --ignore_all_rc_files --output_user_root=c:\foo2 --client_debug info
```

**Comment by laszlocsomor** [comment]
Never mind, managed to repro on an English Windows. I believe it will work for you now because of `--ignore_all_rc_files`.

The problem seems to be with non-latin paths: Bazel tries to read your "home rc" file, i.e. check if `C:\Users\Михалыч\.bazelrc` exists and then read it, and that fails. I can repro the problem if I create a path with Cyrillic characters:

```
c:\cyr>type nul > WORKSPACE

c:\cyr>bazel --version
bazel 0.29.0

c:\cyr>cd c:\cyr\привет\foo

c:\cyr\привет\foo>type nul > WORKSPACE

c:\cyr\привет\foo>bazel info

c:\cyr\привет\foo>echo %errorlevel%
-1073740940
```

**Comment by simsanutiy** [comment]
It doesn't seem like this has changed anything for me. Maybe it checks some other directories that can contain cyrillic letters too?

**Comment by laszlocsomor** [comment]
Bummer. Yes, it seems to still check the home rc file. What's more annoying is it tries `SHGetKnownFolderPath()` to look up the home directory before reading any envvars (this is a bug -- should check an envvar first; I'll fix that), and that function succeeds, and the subsequent string conversion crashes. Because, as I forgot to mention, I found in the meantime that we have a buggy string conversion function.

Let me see if I can find a workaround for you. Otherwise the earliest release I can fix this in is Bazel 1.1.0, ETA sometime in October.

**Comment by laszlocsomor** [comment]
@simsanutiy : Could you try creating a user with ASCII characters in the name, and running cmd.exe / PowerShellas that user, and then running Bazel from there? I think that could work around this issue.

**Comment by laszlocsomor** [comment]
Sweet, thanks for your update!
If it breaks again, I noticed it's also a good idea to set TMP, TEMP, USERPROFILE, and the paths in PATH, to ascii-only paths.

**Comment by meisterT** [comment]
I assume this is fixed.
