### ISSUE TITLE
Allow users to import pom type dependencies from maven

### ISSUE THREAD

**Issue by xinxiao** [bazelbuild/bazel#7822]
### Description of the feature request:

> Allow users to import pom type dependencies from maven, such as [Guice Parent](https://mvnrepository.com/artifact/com.google.inject/guice-parent/4.2.2)

### Feature requests: what underlying problem are you trying to solve with this feature?

> With such feature, users could much more easily import a maven dependency that requires other external dependencies. For example, importing Guice through [Guice Parent](https://mvnrepository.com/artifact/com.google.inject/guice-parent/4.2.2) could be a way to control Guice dependency in one place.

**Comment by keith** [comment]
This functionality is provided by https://github.com/bazelbuild/rules_jvm_external

**Comment by xinxiao** [comment]
@keith Thanks! This resolves all my requirements.

**Comment by keith** [comment]
Awesome! (might want to close this then)
