### ISSUE TITLE
Allow .bazel extension for the WORKSPACE file

### ISSUE THREAD

**Issue by mgechev** [bazelbuild/bazel#7829]
### Description of the problem / feature request:

Allow `.bazel` extension on the `WORKSPACE` file.

### Feature requests: what underlying problem are you trying to solve with this feature?

Similarly to `BUILD` and `BUILD.bazel` files, for consistency allow `WORKSPACE` to have a `.bazel` extension.

// cc @alexeagle

**Comment by jin** [comment]
This is a dupe of https://github.com/bazelbuild/bazel/issues/3885.
