### ISSUE TITLE
Help users move the colon in their label

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#7834]
In Angular, I have a lot of users being confused about how to formulate a label that addresses their file.

For example, we install stuff from npm, and the user wants to reference
`node_modules/@package/name/path/to/file.json`
They used a rule to install the dependencies which creates a workspace called npm.

How does the developer know which of these labels to use?
- `@npm//node_modules/@package/name/path/to:file.json` (this is the intuitive one since slashes after the colon are unusual)
- `@npm//:node_modules/@package/name/path/to/file.json` (might look right to them since their package.json was in the root of their WORKSPACE and they already typed this once)

Of course the answer is to look around for the nearest ancestor `BUILD.bazel` file in the tree, but that requires they know how to look in `$(bazel info output_base)/external/npm/...` to locate files.

The error from bazel is `target not declared in package` or `no such package` depending where the wrong colon is, and also `maybe add exports_files` which is not helpful in an external BUILD file.

The right error message would be `you probably meant to put the colon here: @npm//node_modules/@package/name:path/to/file.json`

**Comment by Jonathan34** [comment]
> Of course the answer is to look around for the nearest ancestor BUILD.bazel file in the tree, but that requires they know how to look in $(bazel info output_base)/external/npm/... to locate files.

that is actually a must to understand what s going on and fix the deps and import path. Thank you for that!

**Comment by jin** [comment]
Related: https://github.com/bazelbuild/bazel/issues/9364

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
