### ISSUE TITLE
Protobufs do not compile in Tensorflow if it's a remote repository

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#784]
The error message is as follows:

```
INFO: From Unknown external/r/tensorflow/core/example/example.pb.h:
tensorflow/core/example/feature.proto: File not found.
external/r/tensorflow/core/example/example.proto: Import "tensorflow/core/example/feature.proto" was not found or had errors.
external/r/tensorflow/core/example/example.proto:88:3: "Features" is not defined.
external/r/tensorflow/core/example/example.proto:266:3: "Features" is not defined.
external/r/tensorflow/core/example/example.proto:267:3: "FeatureLists" is not defined.
external/r/tensorflow/core/example/example.proto:271:3: "Features" is not defined.
external/r/tensorflow/core/example/example.proto:272:12: "Features" is not defined.
ERROR: BLAH/external/r/tensorflow/core/BUILD:403:1: null failed: protoc failed: error executing command bazel-out/host/bin/external/r/google/protobuf/protoc '--cpp_out=bazel-out/local_linux-fastbuild/genfiles/' -I. external/r/tensorflow/core/example/example.proto ... (remaining 20 argument(s) skipped).
```

@damienmg : do you know which protobuf implementation they use? It seems that it's not aware of multiple repositories.

**Comment by lberki** [comment]
Note that you can't get this far at HEAD pending the resolution of #783 . I have an awfully hackish change that fixes that, but I'd rather figure out something more palatable.

**Comment by damienmg** [comment]
They use git submodule and a custom genproto.bzl.

**Comment by damienmg** [comment]
Ok with my change 	9dc1f5a on protobuf and 0.1.4rc2 that is about to be released, this works.

We still have #792 though

**Comment by damienmg** [comment]
Closing on our side, the PR is sent out.

**Comment by davidzchen** [comment]
I think we need to make it possible to add directories to the `PYTHONPATH` for the Python rules in order to be able to use an external repository rather than git submodule for vendoring protobuf. I added a comment explaining this in #702.
