### ISSUE TITLE
file_test rule to address --incompatible_disallow_struct_provider_syntax flag

### ISSUE THREAD

**Issue by alex1545** [bazelbuild/bazel#7842]
### Description of the problem / feature request:

In [rules_docker](https://github.com/bazelbuild/rules_docker) we are addressing issue #7347 to only return a list of providers from all rule implementation functions ([PR](https://github.com/bazelbuild/rules_docker/pull/755)). We import the `file_test` rule from this project that still [returns](https://github.com/bazelbuild/bazel/blob/53edc2f2db90929a6610fbd09853409d398854ec/tools/build_rules/test_rules.bzl#L304) a struct, which makes our CI fail when running with the `--incompatible_disallow_struct_provider_syntax` flag.

Do you have any timelines as of when you plan to address issue #7347 in this project or maybe for the `file_test` rule?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run any `file_test`target with the `--incompatible_disallow_struct_provider_syntax` flag.

### What's the output of `bazel info release`?

0.23.2

**Comment by laurentlb** [comment]
@c-parsons fixed the file `test_rules.bzl`.

Chris, shall we get rid of `test_rules.bzl`? Any reason not to use Skylib?

**Comment by katre** [comment]
Closed for lack of activity. Please ping the reviewers to reopen if this is still a problem.
