### ISSUE TITLE
Support autodetecting toolchain on windows

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#7844]
We're currently supporting this on linux. Windows support requires rewriting the pywrapper shell script in .bat, and is also blocked on bazelbuild/continuous-integration#578.

**Comment by brandjon** [comment]
Just realized that by adding an autodetecting toolchain that doesn't work for windows, I'm breaking the default behavior on windows for when `--incompatible_use_python_toolchains` is turned on. Easiest way to resolve is to add a hack to override the autodetecting toolchain with the legacy behavior on windows, until a proper default toolchain for it is implemented.

**Comment by brandjon** [comment]
Also make sure to update site/docs/windows.md.

**Comment by brandjon** [comment]
An alternative to implementing this toolchain for windows would be to just have a repo rule create a toolchain for the host system. This might help eliminate that `--python_path` hackery in the bazel client under windows.

**Comment by brandjon** [comment]
See [here](https://github.com/bazelbuild/bazel/issues/7026#issuecomment-494572350) for more discussion relating to detecting the interpreter at workspace evaluation time versus execution time. Looks like workspace time is preferred.

**Comment by Warchant** [comment]
`python_path` is counted in `configuration` hash calculation, which means that 2 windows machines won't share same "remote cache" if python is installed in different paths, even if everything else is same. Even if python is not used by the project.
https://github.com/bazelbuild/bazel/issues/3717#issuecomment-992725276
