### ISSUE TITLE
bazel query disagrees with workspace evaluation about which repository rule wins

### ISSUE THREAD

**Issue by asuffield** [bazelbuild/bazel#7855]
Filing this now before I forget it's a bug, I'll put a demonstration together later - this might not be a precise description of how to reproduce the problem.

If we have this in WORKSPACE:

local_repository(name = "foo", {definition 1})
local_repository(name = "foo", {definition 2})
load(...)
local_repository(name = "foo", {definition 3})

Then definition 2 will be used to create the repository, but "bazel query --output=build //external:foo" selects definition 3.

I guess bazel query is somehow not respecting the crazy workspace-splitting behaviour, which confounds attempts to use it for debugging workspace. I have not precisely identified how this is broken, but I have seen bazel query clearly lying about which rule is being used.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
