### ISSUE TITLE
repo unable to load internal packages when loaded through local_repository

### ISSUE THREAD

**Issue by mikest** [bazelbuild/bazel#7857]
### Description of the problem / feature request:

When using load_repository() to load an external repo, I am unable to reference dependencies in the external repo because those internal packages reference other internal packages which are unavailable. They are available when building in the external local repo directly. They become unavailable when loaded into a new workspace.

I'm not super familiar with the internals of Bazel, but it also appears as if the WORKSPACE in my child project is not getting loaded for the child project. Putting a trace into the child WORKSPACE shows that it never gets executed.

I have the following parent workspace:
```
# /foo/WORKSPACE
local_repository(
    name = "bar",
    path = "./bar",
)
```

the build file references a target in bar:
```
# /foo/BUILD
filegroup(
    name = "foo",
    srcs = [
        "@bar//:bar",
    ]
)
```

elsewhere I have the bar workspace:
```
# /foo/bar/WORKSPACE

...load external repos here...
```

```
# /foo/bar/BUILD
filegroup(
    name = "bar",
    srcs = [
        "//second",
    ],
)
```

```
# /foo/bar/conditions/BUILD
package(
    default_visibility = ["//visibility:public"]
)

config_setting(
    name = "osx",
    constraint_values = ["@bazel_tools//platforms:osx"]
)

config_setting(
    name = "windows",
    constraint_values = ["@bazel_tools//platforms:windows"]
)

config_setting(
    name = "linux",
    constraint_values = ["@bazel_tools//platforms:linux"]
)
```

...and here's where things fail:
```
# /foo/bar/second/BUILD
cc_library(
    name = "second",
    ...
    deps = select({
        "//conditions:osx": ["something"],
        "//conditions:windows": ["something_else"],
        "//conditions:linux": ["another_thing"],
    }),
    visibility = ["//visibility:public"],
)
```

I get the following error:
```
/private/var/tmp/_bazel_estee/.../external/bar/second/BUILD:14:1: no such package 'conditions': BUILD file not found on package path and referenced by '@bar//second:second'
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try and load a local_repository into your workspace and reference a target that also references conditions. Building the target in the original workspace works correctly, but as soon as the target is referenced in the parent workspace it no longer works.

### What operating system are you running Bazel on?

osx

### What's the output of `bazel info release`?

release 0.24.0

###  Have you found anything relevant by searching the web?

I've found references to this error string, but nothing that is specific to the particular edge case.

**Comment by mikest** [comment]
I think this may be to a recent behavior I noticed when upgrading from bazel 0.21.0 > 0.24.0:

When I try and load protobuf:
```
http_archive(
    name = "com_google_protobuf",
    # calculated with `openssl dgst -sha256 ~/Downloads/protobuf-3.7.1.zip`
    sha256 = "f976a4cd3f1699b6d20c1e944ca1de6754777918320c719742e1674fcf247b7e",
    strip_prefix = "protobuf-3.7.1",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/v3.7.1.zip"],
)
```

It fails to find dependencies specified in the WORKSPACE and I have to prepend the following to get it to load:
```
# workaround for: https://github.com/protocolbuffers/protobuf/issues/5178
http_archive(
    name = "bazel_skylib",
    sha256 = "bbccf674aa441c266df9894182d80de104cabd19be98be002f6d478aaa31574d",
    strip_prefix = "bazel-skylib-2169ae1c374aab4a09aa90e65efe1a3aad4e279b",
    urls = ["https://github.com/bazelbuild/bazel-skylib/archive/2169ae1c374aab4a09aa90e65efe1a3aad4e279b.tar.gz"],
)

bind(
    name = "zlib",
    actual = "@net_zlib//:zlib",
)

http_archive(
    name = "net_zlib",
    build_file = "@com_google_protobuf//:third_party/zlib.BUILD",
    sha256 = "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1",
    strip_prefix = "zlib-1.2.11",
    urls = ["https://zlib.net/zlib-1.2.11.tar.gz"],
)
```

**Comment by dslomov** [comment]
I think there are multiple issues here:
1. The WORKSPACEs of dependencies are not processed by workspace loader. This is working as intended (so far)
2. A local repository pointing inside the parent workspace is problematic (your `bar` is under `foo`, where `foo` is parent workspace). Does the problem go away if you move `bar` outside of `foo`?

**Comment by mikest** [comment]
I think the first part was due to a misunderstanding I have around how WORKSPACE works.

The second part feels like a bug. If I have folder in the `.bazelignore` list I feel like it shouldn't matter if it's in the same folder?

**Comment by katre** [comment]
Closed for lack of activity. Please ping the reviewers to reopen if this is still a problem.
