### ISSUE TITLE
starlark alias method name not printed on parameter error

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#7858]
### Description of the problem / feature request:

When a `load`ed starlark method that is aliased into a symbol with a keyword parameter is invoked with an unexpected parameter list, the error string printed is of the name of the original method definition.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

foo.bzl
```
def method():
    pass
````

BUILD
```
load(":foo.bzl", _method_alias = "method")

_method_alias(unexpected = "inquisition")
```

Error reported:
`ERROR: <repo>/BUILD:3:1: unexpected keyword 'unexpected' in call to method()`

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

0.24.0

**Comment by brandjon** [comment]
This is working as intended. A function embeds its name at definition time, just like in Python. The failure occurs after we've already passed control to `method`, by which point the syntax/identifier by which we got there isn't known.

In Python 3:

```python
>>> def f():
...     1/0
... 
>>> g = f
>>> g()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in f
ZeroDivisionError: division by zero
```
