### ISSUE TITLE
Simplify and unify mock C++ toolchain configs

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#7863]
I was wondering if there was any way we could remove the mock crosstools used for tests. https://github.com/bazelbuild/bazel/blob/ce4b73e1ff222cc6a3750f85923bcd622640a635/src/test/java/com/google/devtools/build/lib/packages/util/mock/osx_cc_toolchain_config.bzl

In the past I have seen multiple tests that passed because the mock crosstool supports a feature that the real crosstool does not, and vice versa. It seems like ideally we would use the same crosstool file that users ended up hitting, and test against the same behavior.

I am not familiar with the details of why we need the mock crosstool, so this might be a very difficult ask, I just wanted to start the conversation

**Comment by scentini** [comment]
We want to have a mock crosstool so we can test the relationships between features, action_configs and everything else. We want to be able to test that a user who maintains their own cc_toolchain_config.bzl can introduce new features, that specified flags will end up on the command line etc. 

The current version of the mock config is way too complex, it should contain the bare minimum.
For example, take a look at the [android mock implementation](https://github.com/bazelbuild/bazel/blob/master/src/test/java/com/google/devtools/build/lib/packages/util/mock/android_cc_toolchain_config.bzl#L68). It supports nothing by itself and only adds features when requested by a unit test.

I plan to work on reducing the mock osx cc_toolchain_config to contain only what is absolutely necessary. I believe the best solution is to have one empty mock cc_toolchain_config.bzl that will only contain elements that the unit test specifically asked for.

**Comment by keith** [comment]
That sounds great!

**Comment by hlopko** [comment]
@scentini do you want to keep this issue open to track that effort? We can change the title of the issue to more accurately say what it's for then.

**Comment by scentini** [comment]
Yes, let's have it open. Renamed.

**Comment by keith** [comment]
Thanks!

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
