### ISSUE TITLE
Python code using gflags needs to move to absl.flags (absl-py)

### ISSUE THREAD

**Issue by gpshead** [bazelbuild/bazel#7864]
Various pieces of Python code in Bazel have:

```python
from third_party.py import gflags
```

Bazel appears to be maintaining a copy of this ancient dead library.  The correct thing to do is to adopt absl.flags from https://pypi.org/project/absl-py/ and *get rid of your vendored copy of third_party.py.gflags*.

**Comment by yilei** [comment]
This was almost done in https://github.com/bazelbuild/bazel/pull/3855, but no further progress

**Comment by aiuto** [comment]
Replaced by #11544.
