### ISSUE TITLE
Bazel fails to compile a hello world project with visual studio 2019 RC.4

### ISSUE THREAD

**Issue by monamimani** [bazelbuild/bazel#7865]
### Description of the problem / feature request:
I tried to use bazel with the new Visual Studio 2019 RC4 and it fails and seems to be confused with the other Visual Studio that I have installed 2017. I say it get confused because I can see paths with 2017 in the output log, but I have no idea where bazel pulls those. I am just aware of the env vars.

I updated my env var to
BAZEL_VC C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC
BAZEL_VS C:\Program Files (x86)\Microsoft Visual Studio\2019\Community

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have just a hello world project.
my build file
cc_binary(
  name = "HelloWorld",
  srcs = ["main.cpp"]
)

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

release 0.23.2

###  Have you found anything relevant by searching the web?

no

### Any other information, logs, or outputs that you want to share?
the output log

>------ Build started: Project: WORKSPACE, Configuration:  ------
  Loading: 
  Loading: 0 packages loaded
  Analyzing: target //Project1:HelloWorld (0 packages loaded, 0 targets configured)
  Analyzing: target //Project1:HelloWorld (1 packages loaded, 0 targets configured)
  INFO: Analysed target //Project1:HelloWorld (2 packages loaded, 21 targets configured).
  INFO: Found 1 target...
  [0 / 6] checking cached actions
  SUBCOMMAND: # //Project1:HelloWorld [action 'Compiling Project1/main.cpp']
  cd C:/users/mani/_bazel_mani/hj7ianrx/execroot/__main__
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt
      SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\15.0\bin;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\;;C:\WINDOWS\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
      SET PWD=/proc/self/cwd
      SET TEMP=C:\Users\Mani\AppData\Local\Temp
      SET TMP=C:\Users\Mani\AppData\Local\Temp
    C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-dbg/genfiles /Ibazel-out/x64_windows-dbg/bin /Iexternal/bazel_tools /Ibazel-out/x64_windows-dbg/genfiles/external/bazel_tools /Ibazel-out/x64_windows-dbg/bin/external/bazel_tools /showIncludes /MDd /Od /Z7 /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Fobazel-out/x64_windows-dbg/bin/Project1/_objs/HelloWorld/main.obj /c Project1/main.cpp
D:\_Dev\Playground\BazelVs\EXEC : error : D:/_dev/playground/bazelvs/Project1/BUILD:2:1: C++ compilation of rule '//Project1:HelloWorld' failed (Exit 2): cl.exe failed: error executing command
    cd C:/users/mani/_bazel_mani/hj7ianrx/execroot/__main__
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include\yvals_core.h(338): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.20 or newer.
      SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\15.0\bin;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\;;C:\WINDOWS\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
      SET PWD=/proc/self/cwd
      SET TEMP=C:\Users\Mani\AppData\Local\Temp
      SET TMP=C:\Users\Mani\AppData\Local\Temp
    C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-dbg/genfiles /Ibazel-out/x64_windows-dbg/bin /Iexternal/bazel_tools /Ibazel-out/x64_windows-dbg/genfiles/external/bazel_tools /Ibazel-out/x64_windows-dbg/bin/external/bazel_tools /showIncludes /MDd /Od /Z7 /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Fobazel-out/x64_windows-dbg/bin/Project1/_objs/HelloWorld/main.obj /c Project1/main.cpp
  Execution platform: @bazel_tools//platforms:host_platform
  Target //Project1:HelloWorld failed to build
  INFO: Elapsed time: 7.102s, Critical Path: 0.37s
  INFO: 0 processes.
  FAILED: Build did NOT complete successfully
  FAILED: Build did NOT complete successfully

Build failed.

**Comment by laszlocsomor** [comment]
The include paths look fishy, and there's this:

    C:\...\2019\...\MSVC\14.20.27508\include\yvals_core.h(338): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.20 or newer.

I suspect https://github.com/bazelbuild/bazel/blob/master/tools/cpp/windows_cc_configure.bzl is not yet ready for MSVS 2019.

**Comment by laszlocsomor** [comment]
What if you set BAZEL_VC to the 2017 path? (Enough to set one of BAZEL_VC and BAZEL_VS.)

**Comment by monamimani** [comment]
> What if you set BAZEL_VC to the 2017 path? (Enough to set one of BAZEL_VC and BAZEL_VS.)

I tried it and it doesn't work, but I see You already made a commit to fix it.

Thanks alot!
