### ISSUE TITLE
Use different Java toolchains to compile different `java_library` rules

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#7868]
It's helpful to use different Java toolchains to compile different `java_library` (and other rules, such as protobufs). Two concrete examples include when targeting multi-release jars (#5947), and when a mono-repo contains `java_binary`s that target different JREs.

###  Have you found anything relevant by searching the web?

Not yet, but it looks like #6521 builds the basis on which this feature could be delivered.

**Comment by iirina** [comment]
It looks like this is the same as #8735. I added more info on that issue & I'll close this as dupe of #6519 as well.
