### ISSUE TITLE
Error message about non-existing packages is confusing

### ISSUE THREAD

**Issue by asuffield** [bazelbuild/bazel#7870]
When a package does not exist, bazel's error resembles:

"no such package //:foo: not found"

One of the most common questions I get from people new to bazel is about this error, because if you haven't internalised the distinction between package/target/label then this appears to be saying that the file "foo" does not exist.

Let's change this one to say:

"No such package //: ...{full path}.../BUILD.bazel not found"

For bonus points, we could also check for parent packages which exist, in this scenario:

"No such package //foo/bar found for label //foo/bar:baz. However, //foo:bar/baz exists"

**Comment by aehlig** [comment]
> Let's change this one to say:
> 
> "No such package //: ...{full path}.../BUILD.bazel not found"

FYI, we had that once, in 81ab902812b0141ef034ec39338bfeefdd5254ef (see in particular the test added there), but that change increased the memory usage of bazel and hence was rolled back.
