### ISSUE TITLE
Circular workspace dependencies are undebuggable

### ISSUE THREAD

**Issue by asuffield** [bazelbuild/bazel#7871]
Writing this one down before I forget it, I'll try to assemble a working demonstration of the problem later.

When a circular load dependency exists in WORKSPACE, the error message will reference one of the repositories that cannot be loaded, but not the place it was loaded from or the sequence of events which led to this. Typically I end up having to debug this by commenting out code until I find the call which caused it, often buried deep in some rules_* repo.

We need to get a starlark stack trace in here.

**Comment by vmax** [comment]
@asuffield correct me if I'm wrong, but circular dependencies between workspaces _are_ allowed (i.e. `bazel` is able to resolve the correct order). The tip that helped me is to always specify workspace name with [`workspace()`](https://docs.bazel.build/versions/master/skylark/lib/globals.html#workspace) and make sure you reference them exactly as they appear in `WORKSPACE`

**Comment by asuffield** [comment]
Circular dependencies between repos at the build graph level are fine, as long as the graph itself forms a DAG. Circular dependencies in starlark loading of the WORKSPACE file itself will break. This is when you have a chain of load() statements referencing starlark code in other repos, which eventually forms a cycle.
