### ISSUE TITLE
Bazel 0.24 doesn't build on Fedora

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#7874]
0.24 release couldn't be built on Fedora.

Build link: copr.fedorainfracloud.org/coprs/build/873974

Logs:
(from copr-be.cloud.fedoraproject.org/results/vbatts/bazel/fedora-rawhide-x86_64/00873974-bazel/build.log.gz)

And from copr-be.cloud.fedoraproject.org/results/vbatts/bazel/fedora-rawhide-x86_64/00873974-bazel/root.log.gz

Suspect change is https://github.com/bazelbuild/bazel/commit/458ab037e395f872fece67403a2a46a3ad480112#diff-6f9f3b0ebf3a405262ce1170d74d73bb.

**Comment by hlopko** [comment]
Lowering priority since gcc-9 is not yet released so there is no urgency in fixing this.

**Comment by oquenchil** [comment]
Really old Bazel version. Closing it.
