### ISSUE TITLE
Allow users to add and remove compilation modes

### ISSUE THREAD

**Issue by moof2k** [bazelbuild/bazel#788]
Feature request: Allow users to add and remove compilation modes.

Background: Three fixed compilation modes named 'debug' 'fastbuild' and 'opt' doesn't work for everyone. Some teams may desire the ability to maintain fewer targets, like only 'debug' and 'opt', and make 'opt' the default.

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/analysis/config/CompilationMode.java appears to hardcode these defaults. It would be great if users could add or remove them via .bazelrc options.

**Comment by damienmg** [comment]
Would [`--config`](http://bazel.io/docs/bazel-user-manual.html#flag--config) works for this use case along with --cpu? I thing the -c is a legacy thing

**Comment by moof2k** [comment]
My read of the docs gave me the impression `--config` was intended as a "build style" parameter, for use for things like "memcheck," "gprof", "coverage," etc. You may want to combine debug with memcheck, or opt with gprof, etc.

My core beef here is bazel encourages a best practice of having three primary compilation modes, debug, fastbuild and opt--which makes a lot of sense for most projects btw--but then it doesn't provide a way to change these. I like best practices but there should be a way to override them if they don't work for you.

Elimination of the compilation modes would certainly address my beef but then users would be on their own to discover the best practice.

**Comment by bsilver8192** [comment]
Another part of --compilation_mode I find important is that it adds a component to the output path name which is separate from --platform_suffix. If you try to use multiple --config options which all want separate output directories, the --platform_suffix from the last one overrides all the other ones.

Also, --compilation_mode interacts with the CROSSTOOL file in some ways I don't think are possible with just --config (for example, in the HOST configuration it is always set to opt).

**Comment by davidstanke** [comment]
@katre WDYT we should do here?

**Comment by ashi009** [comment]
> My read of the docs gave me the impression `--config` was intended as a "build style" parameter, for use for things like "memcheck," "gprof", "coverage," etc. You may want to combine debug with memcheck, or opt with gprof, etc.
> 
> My core beef here is bazel encourages a best practice of having three primary compilation modes, debug, fastbuild and opt--which makes a lot of sense for most projects btw--but then it doesn't provide a way to change these. I like best practices but there should be a way to override them if they don't work for you.
> 
> Elimination of the compilation modes would certainly address my beef but then users would be on their own to discover the best practice.

The reason why compilation mode works is that rules are designed to produce different outputs based on the COMPILATION_MODE enum. There is no way to design rules to understand any random input. Having those modes predefined gives the community a steady working surface to design rules.

Also, if you are using remote building cache for building some relatively large codebase, having random configs will basically render them useless -- nothing is gonna hit.

So not allowing random build modes is WAI.

**Comment by aiuto** [comment]
Closing.  It can't be folded into -c opt  easily, and the equivalent can be done with existing toolchain mechanisms.
