### ISSUE TITLE
Flip --incompatible_symlinked_sandbox_expands_tree_artifacts_in_runfiles_tree

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#7887]
The flag `--incompatible_symlinked_sandbox_expands_tree_artifacts_in_runfiles_tree` will be flipped in Bazel 0.25 and is scheduled to be removed in 0.26

Related #6204

**Comment by ishikhman** [comment]
@buchgr are you taking care of this? I can take it over to a couple of other flags' flips

**Comment by buchgr** [comment]
Yes. It's already flipped.

**Comment by coeuvre** [comment]
This option is flipped and removed. Closing.
