### ISSUE TITLE
[Skylark] struct.to_proto support for dicts

### ISSUE THREAD

**Issue by fangism** [bazelbuild/bazel#7896]
### Description of the problem / feature request:

Dicts are not supported in converting structs `to_proto()`.
https://docs.bazel.build/versions/master/skylark/lib/struct.html#to_proto

### Feature requests: what underlying problem are you trying to solve with this feature?

Improve convertibility from Skylark structs to proto.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`struct(foo={'a': 'b'}).to_proto()`

### What operating system are you running Bazel on?

Linux.

### What's the output of `bazel info release`?

release blaze-2019.03.22-2 (mainline @239715033)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

Related:
https://github.com/bazelbuild/bazel/issues/5542 (similar request for JSON)

### Any other information, logs, or outputs that you want to share?

Have a CL has a starting point for discussion, refers to two b/ s.

**Comment by laurentlb** [comment]
This looks reasonable to me. Even if there are problems with `to_proto`, allowing dicts here seems intuitive.
