### ISSUE TITLE
Add html titles to documentation pages

### ISSUE THREAD

**Issue by xiongchiamiov** [bazelbuild/bazel#790]
While this may seem like a minor thing, it gets pretty annoying clicking around madly trying to find the right page when your browser window has half a dozen tabs just labelled "Bazel".  Ideally the `<title>` would be something like "Page Title - Bazel".

**Comment by damienmg** [comment]
@davidzchen can you take a look?

**Comment by xiongchiamiov** [comment]
Thanks!
