### ISSUE TITLE
Migrate unit and integration tests to Python 3

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#7903]
With #6647 we flip the default Python version to PY3, but we opt out of this change for our own unit and integration tests. We should eventually port these tests to Python 3 and remove the opt-out.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
