### ISSUE TITLE
pkg_rpm fails when using --incompatible_py3_is_default

### ISSUE THREAD

**Issue by apt-itude** [bazelbuild/bazel#7914]
### Description of the problem / feature request:

`pkg_rpm` rules fail when the `--incompatible_py3_is_default` flag is used. This is the error output:
```
$ bazel build --incompatible_py3_is_default rpm:fake-package
INFO: Analysed target //rpm:fake-package (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/athompson/code/bazel-test-workspace/rpm/BUILD:3:1: MakeRpm rpm/fake-package-x86_64.rpm failed (Exit 1) make_rpm failed: error executing command bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_rpm '--name=fake-package' '--arch=x86_64' '--spec_file=bazel-out/k8-py3-fastbuild/bin/rpm/fake-package.spec' ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/Users/athompson/.cache/bazel/_bazel_athompson/ac1428c9c547e01eac9d076b7db4af52/sandbox/processwrapper-sandbox/1/execroot/__main__/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_rpm.runfiles/bazel_tools/tools/build_defs/pkg/make_rpm.py", line 305, in <module>
    main(FLAGS(sys.argv))
  File "/Users/athompson/.cache/bazel/_bazel_athompson/ac1428c9c547e01eac9d076b7db4af52/sandbox/processwrapper-sandbox/1/execroot/__main__/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_rpm.runfiles/bazel_tools/tools/build_defs/pkg/make_rpm.py", line 297, in main
    return builder.Build(FLAGS.spec_file, FLAGS.out_file)
  File "/Users/athompson/.cache/bazel/_bazel_athompson/ac1428c9c547e01eac9d076b7db4af52/sandbox/processwrapper-sandbox/1/execroot/__main__/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_rpm.runfiles/bazel_tools/tools/build_defs/pkg/make_rpm.py", line 286, in Build
    status = self.CallRpmBuild(dirname)
  File "/Users/athompson/.cache/bazel/_bazel_athompson/ac1428c9c547e01eac9d076b7db4af52/sandbox/processwrapper-sandbox/1/execroot/__main__/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_rpm.runfiles/bazel_tools/tools/build_defs/pkg/make_rpm.py", line 257, in CallRpmBuild
    self.rpm_path = FindOutputFile(output)
  File "/Users/athompson/.cache/bazel/_bazel_athompson/ac1428c9c547e01eac9d076b7db4af52/sandbox/processwrapper-sandbox/1/execroot/__main__/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_rpm.runfiles/bazel_tools/tools/build_defs/pkg/make_rpm.py", line 108, in FindOutputFile
    m = WROTE_FILE_RE.search(log)
TypeError: can't use a string pattern on a bytes-like object
Target //rpm:fake-package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.945s, Critical Path: 0.76s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```
This appears to be failing because the `make_rpm.py` binary is only Python2-compatible, but it is being executed with a Python3 interpreter. I suspect this is because its corresponding `py_binary` rule [here](https://github.com/bazelbuild/bazel/blob/0.24.0/tools/build_defs/pkg/BUILD) does not set the `python_version` attribute to `"PY2"`.

### Steps to reproduce

1. `git clone https://github.com/apt-itude/bazel-pkg-rpm-py3-default.git`
2. `cd bazel-pkg-rpm-py3-default/`
3. `bazel build --incompatible_py3_is_default rpm:fake-package`

### What operating system are you running Bazel on?

`CentOS Linux release 7.5.1804`

### What's the output of `bazel info release`?

`release 0.24.0- (@non-git)`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Installed from `vbatts-bazel` COPR repository.

**Comment by aiuto** [comment]
We should expand this.  All of tools/build_defs/pkg is python 2-ish. Someone needs to update them all.

**Comment by brandjon** [comment]
Sigh, another case of #4815. The binary declares that it's PY2 but it's ignored at runtime. This would've been fixed in 0.26 by `--incompatible_use_python_toolchains` but we had to delay that flag flip because of downstream failures. You can try enabling that flag in your build or set a `--python_top` to a workaround `py_runtime` target as in [here](https://github.com/bazelbuild/bazel/issues/4815#issuecomment-460777113).

**Comment by brandjon** [comment]
Actually scratch that, this happens when you pass in the flag to change the default Python version as it is known to Bazel at analysis time, so #4815 isn't relevant. This sounds more like it's getting the Python version from the host platform. That's #6443.

The workaround is to opt out of updating the Python version for host-configured targets by passing `--host_force_python=PY2`.

**Comment by apt-itude** [comment]
@brandjon thanks for triaging. Does `--host_force_python=PY2` enforce that all `cfg="host"` targets and `genrule`s _must_ use Python 2? Or just that they will by default if the tool itself doesn't declare a `python_version`? In my case we have a bunch of Python-3-only tools, so it won't help to force them all to use Python 2.

**Comment by brandjon** [comment]
It's that they must be PY2. Unfortunately there can only be one "host" configuration so all host-configured targets have to be the same Python version. There's work on the [execution transition](https://github.com/bazelbuild/proposals/blob/master/designs/2019-02-12-execution-transitions.md) to replace the host configuration.

If your build was working prior to turning on `--incompatible_py3_is_default`, then all your host-configured tools were running as PY2. This is the behavior you preserve by using `--host_force_python=PY2`; the incompatible flag changes the default for both the target and host to PY3, and this force flag sets the host back.

Now, it's possible that targets that were configured for one version of Python end up actually running with an interpreter for the other, depending on the values of `--python_top` / `--python_path` (see #4815). It's still the case that only one runtime is used however.

**Comment by apt-itude** [comment]
Actually, this issue is preventing my org from even turning on the `--incompatible_allow_python_version_transitions` flag, so we haven't gotten to the point where we can try `--incompatible_py3_is_default` yet (I created this issue when I was doing discovery work for the transition). 

We can currently get away with having both PY2-only and PY3-only host-configured tools in the same workspace because we're using the `py_runtime` shell script hack where we pick a Python interpreter based on the shebang of the script. The `pkg_rpm` rule works because it falls back to Python 2, and all of our tools work because we specify Python 3 in the shebang.

Ultimately our problem is solved if:
1. All rules like `pkg_rpm` that use Python tools add Python 3 support
2. There is true support for having both PY2 and PY3 tools run on the host

Will using `cfg="exec"` (once it's implemented) actually for the second option?

**Comment by brandjon** [comment]
Why is `--incompatible_allow_python_version_transitions` causing failures? That shouldn't change the behavior of the host config.

The `py_runtime` shell script hack, since it is an execution-time hack, should continue to work regardless of all these flags. But analysis-time logic, like `srcs_version` attribute validation, is affected.

`cfg="exec"` should in principle allow for (2), but it will require moving dependencies from a host-configured attribute to an "exec"-configured attribute. E.g., `genrule` will get an `exec_tools` attribute that functions like `tools` except for this difference. (It's also possible that the Configurability team will find a way to change all host-configured attributes to exec-configured without the need for new attributes.)

**Comment by apt-itude** [comment]
Turning on the flag isn't, by itself, causing issues for us. However, the main reason we want to turn the flag on is to get rid of the runtime hack and start using the `python_version` attribute instead of shebangs. It sounds like until exec-config is implemented we can't really drop the hack.

**Comment by Globegitter** [comment]
The issue for exec transition btw is https://github.com/bazelbuild/bazel/issues/7935, which does seem to be making good progress.

**Comment by aiuto** [comment]
@apt-itude  This is now fixed in rules_pkg. Are you able to migrate to that?
https://github.com/bazelbuild/rules_pkg/releases

**Comment by apt-itude** [comment]
@aiuto yup! My fix to make `make_rpm` Python-3 compatible actually made it into Bazel before you forked, so we migrated to `rules_pkg` as soon as you made the first release instead of waiting for the Bazel release, and all is well 👍

**Comment by aiuto** [comment]
Yup. It seems fixed in rules pkg, so closing.
