### ISSUE TITLE
macos shell installer emits "-n" cruftiness

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#7916]
Bazel version 0.24, macos. shell installer

Download https://github.com/bazelbuild/bazel/releases/download/0.24.0/bazel-0.24.0-installer-darwin-x86_64.sh

sh ./Downloads/bazel-0.24.0-installer-darwin-x86_64.sh --user

I get this as part of the output: The -n is probably an incorrect use of echo -n
Probably because I did   "sh <script>" rather than chmod <script>, ./<script>
But the former is an idiomatic usage, so I would still expect something reasonable
to happen.

There is probably no need for the "echo -n ." lines.  It is not like we need to be minimal with the logging. We might as well just log full sentences about what we are doing or nothing at all.

## Build information
   - [Commit](https://github.com/bazelbuild/bazel/commit/f092ec388a4)
-n Uncompressing.
-n .
-n .
-n .
-n .
-n .
Extracting Bazel installation...
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
.

**Comment by philwo** [comment]
The reason is that `sh` is not `bash`, but our installer is a `bash` script, not a `sh` script. So you have to call it like `bash bazel-0.24.0-installer-darwin-x86_64.sh --user`.

We could also fix it by making it a `sh` script instead, which would be a good idea for compatibility anyway.
