### ISSUE TITLE
No starlark equivalent of native java compile addExcludedArtifacts

### ISSUE THREAD

**Issue by timpeut** [bazelbuild/bazel#7920]
There is no starlark equivalent of the native JavaTargetAttributes.Builder#addExcludedArtifacts()

**Comment by timpeut** [comment]
Yes, this is still relevant.

**Comment by iirina** [comment]
@timpeut Thanks! Can you describe your use case for exposing something similar to `JavaTargetAttributes.Builder#addExcludedArtifacts()` to Starlark?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
