### ISSUE TITLE
Query gives invalid target format error for relative paths on BUILD files

### ISSUE THREAD

**Issue by dfreese** [bazelbuild/bazel#7923]
### Description of the problem / feature request:

From the [Bazel Query How-to](https://docs.bazel.build/versions/master/query-how-to.html#what-is-the-build-label-for-path-to-file-bar-java), passing the path of a file returns the bazel target name.  This works from the WORKSPACE directory, but the behavior of BUILD files and other files differs if run from a directory above build files.  As a minimal example:

    mkdir -p workspace/build/tmp
    touch workspace/WORKSPACE
    echo 'filegroup(name="f", srcs=["file.cpp"])' > workspace/build/BUILD
    touch workspace/build/file.cpp
    cd workspace
    bazel query 'set(build/BUILD build/file.cpp)'

This prints out:

    //build:file.cpp
    //build:BUILD

but when going further into the directory structure, and running similar queries

    cd build/tmp
    bazel query ../file.cpp
    bazel query ../BUILD

The first query prints the files bazel target path:

    //build:file.cpp

The second returns the following error:

    ERROR: Skipping '../BUILD': invalid target format '../BUILD': invalid package name 'build/tmp/..': package name component contains only '.' characters

### Feature requests: what underlying problem are you trying to solve with this feature?

Being able to run the following from workspace/build/tmp

    bazel query 'set(../BUILD ../file.cpp)'

and get the following output

    //build:file.cpp
    //build:BUILD

### What operating system are you running Bazel on?

Ubuntu 16.04 LTS (4.15.0-46-generic)

### What's the output of `bazel info release`?

release 0.16.1

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A for this example.

**Comment by katre** [comment]
Closed for lack of activity. Please ping the reviewers to reopen if this is still a problem.

**Comment by dfreese** [comment]
Low priority, but the inconsistency described still exists on v3.1.0, and would be nice to rectify at some point, if possible.

**Comment by katre** [comment]
Thanks for confirming it's still present. I'll ask the Core team to take a look and prioritize.
