### ISSUE TITLE
cc_library should have distinct local and transitive 'defines'

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#7939]
The cc_library **defines** attribute is a problem.
https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library

1. If you just see the name, you think it applies only to the target. When you read the docs you realize it applies all the way up the graph. Thus, using **defines=["foo"]** instead of **copts=["-Dfoo"]** has a far greater cost.
2. **defines** has a really nice property. It does the right thing per platform. So you get **-Dx** with some compilers and **/Dx** with others. Yippee! I want to use that. 
3. Please do not. See point 1.

The quick solution is to add something like *local_defines*, which does the magic -D|/D transformation. That would tie in with #6979.

But that would suffer from the problem of **defines** being a much better name for the per library defines. So, what I would like to see is a multi-phase transition where we

- allow local_defines
- migrate all uses of defines to dependant_defines
- flip defines to mean local
- deprecate local_defines

Super painful? Yes. But it will increase understandabilty in the long run.

**Comment by jyknight** [comment]
I'd just mention that -DFOO=BAR _does_ work on all compilers -- including MSVC. Anywhere it documents "/option", it also accepts "-option". E.g. `cl.exe -DFOO=bar -O2` is just fine by MSVC.
