### ISSUE TITLE
Documentation site should default to latest release, not master

### ISSUE THREAD

**Issue by stephenjudkins** [bazelbuild/bazel#7945]
### Description of the problem / feature request:
The documentation site at https://docs.bazel.build defaults to the docs generated from `master`. Instead, it should default to the latest non-RC release.

### Feature requests: what underlying problem are you trying to solve with this feature?
Changes in `master` typically aren't useful for the average Bazel user.

**Comment by laszlocsomor** [comment]
It does now.
