### ISSUE TITLE
incompatible_no_target_output_group: Remove Target.output_group field

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#7949]
**Flag:** --incompatible_no_target_output_group
Available since: 0.23 (February 2019 release)

**Motivation**
The motivation for this change is described in #6241

**Migration**
Use OutputGroupInfo instead.

```python
# Before
def rule_impl(ctx):
    ...
    dep_bin = ctx.attr.dep.output_group.bin
    ...

# After
def rule_impl(ctx):
    ...
    dep_bin = ctx.attr.dep[OutputGroupInfo].bin
    ...

```

**Comment by hlopko** [comment]
This flag looks like it needs some update of labels :) Is it still relevant?

**Comment by c-parsons** [comment]
Still relevant, still needs to be flipped. (Internally, a number of teams still depend on this. I'm going to have to evaluate the downstream projects to see if they need to be migrated. I've already migrated a number of our tests which still use this syntax, but there's probably more, too.

**Comment by dslomov** [comment]
Is migration tooling avaliable?

**Comment by c-parsons** [comment]
Yes, buildifier is able to facilitate this migration.

**Comment by dslomov** [comment]
Closing since the flag is flipped
