### ISSUE TITLE
ProtoInfo.transitive_proto_path does not add genfiles path prefixes

### ISSUE THREAD

**Issue by EdSchouten** [bazelbuild/bazel#7964]
### Description of the problem / feature request:

I am currently working on rules_elm: a set of Bazel rules for [Elm](https://elm-lang.org/), a Haskell-like programming language that transpiles to Javascript. As there exists [a Protobuf compiler for Elm](https://github.com/tiziano88/elm-protobuf), I also want to add an `elm_proto_library()`.

While implementing this function and testing it on [the REv2 protocol](https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/execution/v2/remote_execution.proto), I observed the following build failure:

```
external/com_google_protobuf: warning: directory does not exist.
google/protobuf/descriptor.proto: File not found.
google/api/annotations.proto: Import "google/protobuf/descriptor.proto" was not found or had errors.
google/api/annotations.proto:28:8: "google.protobuf.MethodOptions" is not defined.
google/protobuf/any.proto: File not found.
google/protobuf/empty.proto: File not found.
google/rpc/status.proto: Import "google/protobuf/any.proto" was not found or had errors.
[ lots of errors follow ]
```

The Protobuf compiler was being invoked by my build rules as follows:

```
bazel‑out/host/bin/external/com_google_protobuf/protoc ‑‑plugin bazel‑out/host/bin/external/com_github_tiziano88_elm_protobuf/protoc‑gen‑elm/linux_amd64_stripped/protoc‑gen‑elm ‑‑elm_out '' ‑I external/com_github_bazelbuild_remote_apis ‑I external/com_google_protobuf ‑I external/googleapis external/com_github_bazelbuild_remote_apis/build/bazel/remote/execution/v2/remote_execution.proto
```

As I'm using remote builds, I managed to extract [a tarball of the input root](https://github.com/bazelbuild/bazel/files/3050253/0f650c6669c74b014f8e429bfc5970711b69e7dfceff004ff87f2cdbb2405822.tar.gz). As you can see, the .proto files that are reported as missing are stored underneath `bazel-out/k8-fastbuild/genfiles/external/com_google_protobuf/google/protobuf`, while the compiler is invoked to include `external/com_google_protobuf`.

To obtain the include paths I'm passing to protoc, [I'm using ProtoInfo.transitive_proto_path](https://github.com/EdSchouten/rules_elm/blob/eb8fa5ca662f9a4eadad5da8bc4f67ee21ce91dd/proto/def.bzl#L27), which I thought would be sufficient. The question is: is Bazel incorrect in that it omits the genfiles prefixes where applicable, or am I supposed to do some post-processing on ProtoInfo.transitive_proto_path?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Check out [bb-browser](https://github.com/buildbarn/bb-browser), commit `e40af2807d5bd4bd5bc80e010f0b880172351415` in branch `elm`. Then try to build `//cmd/bb_browser/frontend/...`.

### What operating system are you running Bazel on?

Ubuntu 18.04 LTS

### What's the output of `bazel info release`?

release 0.24.1

###  Have you found anything relevant by searching the web?

No. :-(

**Comment by EdSchouten** [comment]
Might it be the case that this issue is weakly related to https://github.com/bazelbuild/bazel/issues/7157?

**Comment by EdSchouten** [comment]
I guess that the issue is that [the `Library` class in `ProtoCommon`](https://github.com/bazelbuild/bazel/blob/e6cd8eec65946ccce1276b9a54d9fb1311b64ac6/src/main/java/com/google/devtools/build/lib/rules/proto/ProtoCommon.java#L162) only allows setting a single `sourceRoot`. In theory, you could have multiple of those in case you'd declare a `proto_library()` that has some source files and some generated ones. The [`getProtoSourceRoot` function](https://github.com/bazelbuild/bazel/blob/e6cd8eec65946ccce1276b9a54d9fb1311b64ac6/src/main/java/com/google/devtools/build/lib/rules/proto/ProtoCommon.java#L196-L220) only computes the path of source files; not generated ones.

+cc @lberki, as there already is a TODO with his name right above this code. Do you think this analysis is correct?

**Comment by lberki** [comment]
There are many TODOs with my name...

The way this works with built-in rules is that we pass `-I<import path>=<execpath>` parameters to `protoc` so that it knows exactly where to find which files. Unfortunately, that map is not yet available in Starlark. I'm afraid the only workaround I can think of is to look at the path of the input artifact, try to determine if it's an output artifact and then brew your own `-I` arguments.

Not very satisfying,  I know :(

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
