### ISSUE TITLE
Bazel Installing Itself on Windows with space in path name breaks some things

### ISSUE THREAD

**Issue by rdeushane** [bazelbuild/bazel#7979]
### Description of the problem / feature request:

When Bazel extracts itself on a fresh install, it created the folder: 
`C:/Users/jdoe/_bazel_John Doe`  according to `%USERNAME%`
Since There is a space in the directory name, when Bazel uses git.bzl (in my case), and possibly other commands involving the windows installation path, it will fail with "Too Many Arguments".    

It's easy enough to fix by changing %USERNAME%, bit if I had this problem chances are someone else will.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Install Bazel on a windows installation with a space in `%USERNAME%`.

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 0.24.1

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

```
Starting local Bazel server and connecting to it...
ERROR: Skipping '//:buildifier': error loading package '': in C:/users/jdoe/_bazel_john doe/kw772bcd/external/com_github_bazelbuild_buildtools/buildifier/def.bzl: Encountered error while reading extension file 'lib/shell.bzl': no such package '@bazel_skylib//lib': Traceback (most recent call last):
        File "C:/users/jdoe/_bazel_john doe/kw772bcd/external/bazel_tools/tools/build_defs/repo/git.bzl", line 164                _clone_or_update(ctx)
        File "C:/users/jdoe/_bazel_john doe/kw772bcd/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning bazel_skylib:
/usr/bin/bash: line 1: cd: too many arguments
+ cd C:/users/jdoe/_bazel_john doe/kw772bcd/external
/usr/bin/bash: line 3: cd: too many arguments
+ git -C 'C:/users/jdoe/_bazel_john doe/kw772bcd/external/bazel_skylib' reset --hard 6741f733227dc68137512161a5ce6fcf283e3f58
fatal: not a git repository (or any of the parent directories): .git
+ git -C 'C:/users/jdoe/_bazel_john doe/kw772bcd/external/bazel_skylib' fetch --shallow-since=1549647446 +0100 origin 6741f733227dc68137512161a5ce6fcf283e3f58:6741f733227dc68137512161a5ce6fcf283e3f58
fatal: not a git repository (or any of the parent directories): .git
+ git -C 'C:/users/jdoe/_bazel_john doe/kw772bcd/external/bazel_skylib' fetch origin 6741f733227dc68137512161a5ce6fcf283e3f58:6741f733227dc68137512161a5ce6fcf283e3f58
fatal: not a git repository (or any of the parent directories): .git
WARNING: Target pattern parsing failed.
ERROR: error loading package '': in C:/users/jdoe/_bazel_john doe/kw772bcd/external/com_github_bazelbuild_buildtools/buildifier/def.bzl: Encountered error while reading extension file 'lib/shell.bzl': no such package '@bazel_skylib//lib': Traceback (most recent call last):
        File "C:/users/jdoe/_bazel_john doe/kw772bcd/external/bazel_tools/tools/build_defs/repo/git.bzl", line 164                _clone_or_update(ctx)
        File "C:/users/jdoe/_bazel_john doe/kw772bcd/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning bazel_skylib:
/usr/bin/bash: line 1: cd: too many arguments
+ cd C:/users/jdoe/_bazel_john doe/kw772bcd/external
/usr/bin/bash: line 3: cd: too many arguments
+ git -C 'C:/users/jdoe/_bazel_john doe/kw772bcd/external/bazel_skylib' reset --hard 6741f733227dc68137512161a5ce6fcf283e3f58
fatal: not a git repository (or any of the parent directories): .git
+ git -C 'C:/users/jdoe/_bazel_john doe/kw772bcd/external/bazel_skylib' fetch --shallow-since=1549647446 +0100 origin 6741f733227dc68137512161a5ce6fcf283e3f58:6741f733227dc68137512161a5ce6fcf283e3f58
fatal: not a git repository (or any of the parent directories): .git
+ git -C 'C:/users/jdoe/_bazel_john doe/kw772bcd/external/bazel_skylib' fetch origin 6741f733227dc68137512161a5ce6fcf283e3f58:6741f733227dc68137512161a5ce6fcf283e3f58
fatal: not a git repository (or any of the parent directories): .git
INFO: Elapsed time: 5.233s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading:
```

**Comment by rdeushane** [comment]
If anyone else has this problem;  
* Open command line and run `netplwiz`  
* Change your username, log out and back in, and run `echo %USERNAME%`  
* Re-run Bazel

**Comment by laszlocsomor** [comment]
Thanks for the report.

You can avoid the bug with `bazel --output_user_root=c:/_bazel build //foo`.

**Comment by rdeushane** [comment]
Thanks @laszlocsomor, I will give that a go.

**Comment by xiak** [comment]
I thinks this issue is not only username but also --shallow-since=1549647446 +0100

It should --shallow-since="1549647446 +0100" not --shallow-since=1549647446 +0100.

**Comment by laszlocsomor** [comment]
I just noticed, a space in the install path breaks more than just the git rules.
Even on Linux we can't build Bazel from source when `--output_user_root` has a space.

I'll fix Bazel to check for space in the install path, and maybe use another path.

@xiak : could you show an example with shallow-since?

**Comment by laszlocsomor** [comment]
I decided to make this a warning, not an error, because some things (namely "bazel info") work fine when output paths have a space.

**Comment by kundanSingh11** [comment]
Use this if you don't  want to change your user name just rename bazel.exe to anything and make bazel.bat file in the same dir and add that to path done 

@set args=%1
@shift
@:start
@if [%1] == [] goto done
@set args=%args% %1
@shift
@goto start

:done
@call bazelasd.exe --output_user_root=c:/_bazel_build %args%

**Comment by Guillaume-Garrigos** [comment]
> If anyone else has this problem;
> 
>     * Open command line and run `netplwiz`
> 
>     * Change your username, log out and back in, and run `echo %USERNAME%`
> 
>     * Re-run Bazel

I would like to warn that doing this literally broke my computer : after changing my username in netplwiz, I am now unable to login, as windows thinks my password is incorrect. This way of changing the username might not be bugfree.
