### ISSUE TITLE
-Wunused-result warnings when running tests

### ISSUE THREAD

**Issue by tfarina** [bazelbuild/bazel#798]
$ ./compile.sh test ./output/bazel
...
INFO: From Compiling src/main/cpp/blaze.cc [for host]:
src/main/cpp/blaze.cc: In function 'void blaze::AcquireLock()':
src/main/cpp/blaze.cc:1482:32: warning: ignoring return value of 'int ftruncate(int, __off_t)', declared with attribute warn_unused_result [-Wunused-result]
   ftruncate(globals->lockfd, 0);
                                ^
src/main/cpp/blaze.cc:1488:49: warning: ignoring return value of 'ssize_t write(int, const void_, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(globals->lockfd, msg.data(), msg.size());
                                                 ^
src/main/cpp/blaze.cc: In function 'void blaze::Daemonize(int)':
src/main/cpp/blaze.cc:383:21: warning: ignoring return value of 'int dup(int)', declared with attribute warn_unused_result [-Wunused-result]
   dup(STDOUT_FILENO);  // stderr (2>&1)
                     ^
src/main/cpp/blaze.cc: In function 'void blaze::sigprintf(const char_, ...)':
src/main/cpp/blaze.cc:1051:31: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(STDERR_FILENO, buf, r);
                               ^
...

**Comment by hanwen** [comment]
please fix only the ones where you can meaningfully provide feedback; some of them happen in the daemonization code.

**Comment by helenalt** [comment]
@lberki is this a bug that needs fixing?

**Comment by lberki** [comment]
I don't think so. It's a little code beauty issue which may or may not have been fixed since then and it's a tiny issue anyway.
