### ISSUE TITLE
Android c++ build under Windows, command line to long

### ISSUE THREAD

**Issue by MarkaRagnos0815** [bazelbuild/bazel#7982]
### Description of the problem / feature requests

I am trying to build a c++ library using bazel under windows. I am using the following command:
``
bazel build <target> --compilation_mode=opt --crosstool_top=@androidndk//:default_crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=armeabi-v7a 
``
I am getting the following error message:
``
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(429): CreateProcessWithExplicitHandles("<user>\_bazel_exb_a\kkszmrzt\execroot\dbsdk\external\androidndk\ndk\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ar" rcsD bazel-out/armeabi-v7a-(...)): command is longer than CreateProcessW's limit (32767 characters)
``
Unlike Linux/windows build that are using a linker input file for commands the ndk version passes all parameters via command line

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- create a cc_binary for android
- add as much as possible files to exceed 32K of characters in command line
- see failing build

### What operating system are you running Bazel on?

- windows 10

### What's the output of `bazel info release`?

- release 0.24.1

###  Have you found anything relevant by searching the web?

- no

**Comment by jin** [comment]
@laszlocsomor how do you typical deal with issues like this on Windows? Param files?

**Comment by MarkaRagnos0815** [comment]
yes, param files should help (like normal bazel k8 build does)

**Comment by laszlocsomor** [comment]
@jin: Yes, with param files. Beware there's no standard encoding (that I know), so use ASCII to stay safe.

**Comment by meteorcloudy** [comment]
> <user>\_bazel_exb_a\kkszmrzt\execroot\dbsdk\external\androidndk\ndk\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ar"

It's weird to run an arm linux binary on Windows, I guess the rule doesn't work on Windows at all?

Anyway, this issue looks obsolete, please reopen if the issue still exists.

**Comment by homuler** [comment]
This issue still exist, but I'm sorry for not being able to show you the smallest example.

At least, I can reproduce this error with [google/mediapipe](https://github.com/google/mediapipe) repository.
For now, mediapipe does not support Android build on Windows, so we need to apply a following patch.

```diff
diff --git a/WORKSPACE b/WORKSPACE
index 9dbbff3..1cfaecc 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -96,6 +96,7 @@ http_archive(
     ],
     patches = [
         "@//third_party:com_github_glog_glog_9779e5ea6ef59562b030248947f787d1256132ae.diff",
+        "@//third_party:com_github_glog_glog_no_gflags.diff",
     ],
     patch_args = [
         "-p1",
diff --git a/third_party/com_github_glog_glog_no_gflags.diff b/third_party/com_github_glog_glog_no_gflags.diff
new file mode 100644
index 0000000..f266d7e
--- /dev/null
+++ b/third_party/com_github_glog_glog_no_gflags.diff
@@ -0,0 +1,28 @@
+diff --git a/bazel/glog.bzl b/bazel/glog.bzl
+index a46e2d1..5f63514 100644
+--- a/bazel/glog.bzl
++++ b/bazel/glog.bzl
+@@ -107,12 +107,12 @@ def glog_library(namespace = "google", with_gflags = 1, **kwargs):
+             "src/utilities.h",
+             "src/vlog_is_on.cc",
+         ] + select({
+-            "@bazel_tools//src/conditions:windows": windows_only_srcs,
++            "@//mediapipe:windows": windows_only_srcs,
+             "//conditions:default": [":config_h"],
+         }),
+         copts =
+             select({
+-                "@bazel_tools//src/conditions:windows": common_copts + windows_only_copts,
++                "@//mediapipe:windows": common_copts + windows_only_copts,
+                 "@bazel_tools//src/conditions:darwin": common_copts + linux_or_darwin_copts + darwin_only_copts,
+                 "@bazel_tools//src/conditions:freebsd": common_copts + linux_or_darwin_copts + freebsd_only_copts,
+                 ":wasm": common_copts + wasm_copts,
+@@ -128,7 +128,7 @@ def glog_library(namespace = "google", with_gflags = 1, **kwargs):
+     native.cc_library(
+         name = "glog_headers",
+         deps = select({
+-            "@bazel_tools//src/conditions:windows": [":windows_glog_headers"],
++            "@//mediapipe:windows": [":windows_glog_headers"],
+             "//conditions:default": [":default_glog_headers"],
+         }),
+     )
```

After that, when I run the below command, then this error occurs (total parameter's length is about 35,000).
```sh
bazel build -c opt --action_env PYTHON_BIN_PATH="C://path//to//python.exe" --verbose_failures --config=android_arm64 --noenable_platform_specific_config --cxxopt=-std=c++17 //mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu:facedetectiongpu
```

```txt
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(165): CreateProcessWithExplicitHandles("C:\users\homul\_bazel_homul\auxtleee\execroot\mediapipe\external\androidndk\ndk\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64\bin\aarch64-linux-android-ar" rcsD bazel-out/android-arm64-v8a-opt/bin/external/XNNPACK/libneonfma_ukernels.pic.a bazel-out/android-arm64-v8a-opt/bin/external/XNNPACK/_objs/neonfma_ukernels/up4x4-minmax-neonfma-acc2.pic.o bazel-out/android-arm64-v8a-opt/bin/external/XNNPACK/_objs/neonfma_ukernels/up4x4-minmax-neonfma.pic.o bazel-out/android-arm64-v8a-(...)): command is longer than CreateProcessW's limit (32767 characters)
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu:facedetectiongpu failed to build
INFO: Elapsed time: 11.464s, Critical Path: 9.91s
INFO: 219 processes: 129 internal, 90 local.
FAILED: Build did NOT complete successfully
```

**Comment by homuler** [comment]
I'm not sure but it may be caused by the below line.
https://github.com/bazelbuild/bazel/blob/90a8c27f9416babae78fbd3432567ccec1a04cfb/src/main/java/com/google/devtools/build/lib/bazel/rules/android/android_ndk_cc_toolchain_template.txt#L17

If I change 0 to 1, the error has gone.
