### ISSUE TITLE
`no-remote` tag still builds target remotely

### ISSUE THREAD

**Issue by finnball** [bazelbuild/bazel#7988]
### Description of the problem / feature request:
Using either tag with a `cc_binary` rule:
`tags = ["no-remote", "local"]` 
Still builds remotely.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Add the above tag to a `cc_binary` rule.

### What operating system are you running Bazel on?

Arch Linux

### What's the output of `bazel info release`?

`release: release 0.24.1`
and
`release: release 0.17.0`

###  Have you found anything relevant by searching the web?

Perhaps: https://github.com/bazelbuild/bazel/issues/7766

**Comment by keith** [comment]
Possibly related https://github.com/bazelbuild/bazel/issues/6038#issuecomment-418294602 https://github.com/bazelbuild/bazel/issues/4680#issuecomment-410692749

**Comment by buchgr** [comment]
fyi @ishikhman

**Comment by ishikhman** [comment]
related to #7766 
FYI: design proposal is in review at the moment.

**Comment by buchgr** [comment]
@ishikhman `cc_binary` is a native rule. this is orthogonal to starlark rules.

**Comment by ishikhman** [comment]
> @ishikhman `cc_binary` is a native rule. this is orthogonal to starlark rules.

thanks! added another issue for the native rules (design proposal irrelevant of the rule type)

**Comment by ishikhman** [comment]
will be available in Bazel 1.0 (already available in HEAD) under the flag `--experimental_allow_tags_propagation`. Feel free to try it out!

Please let us know, if you face any issues with it, here is a tracking issue #8830
