### ISSUE TITLE
android_library does not rewrite AndroidManifest.xml file for ${applicationId} replacement

### ISSUE THREAD

**Issue by menny** [bazelbuild/bazel#799]
Gradle can re-write `AndroidManifest.xml` files with `@{applicationId}` and replace this placeholder with the package name of the application's.

I created a demo repo that shows the problem:
https://github.com/menny/BazelPlayground/tree/manifest-re-write

This app builds and runs with no issues when using Gradle. It does not build with Gradle.

To clarify the severity, Google's own `com.google.android.gms.measurement` uses `${applicationId}` in its `AndroidManifest.xml` file to describe authorities for its content-provider.

**Comment by ahumesky** [comment]
Can you talk about the use case for this? Is this for when, say, you have a library that has a manifest, and that manifest wants to use the application id of the final binary?

**Comment by ahumesky** [comment]
Ok, I see from your example repo that this is what you were talking about:
https://github.com/menny/BazelPlayground/blob/manifest-re-write/rewrite-lib/src/main/AndroidManifest.xml#L11

**Comment by ahumesky** [comment]
We're working on refactoring resource merging, and substituting ${androidId} should be enabled by that work, so this should be possible soon.

**Comment by menny** [comment]
thanks @ahumesky.

**Comment by ahumesky** [comment]
This is available with android_binary.manifest_merger:
http://www.bazel.io/docs/be/android.html#android_binary.manifest_merger
