### ISSUE TITLE
incompatible_require_java_toolchain_header_compiler_direct

### ISSUE THREAD

**Issue by cushon** [bazelbuild/bazel#7990]
See: https://github.com/bazelbuild/bazel/commit/2ebb0a20b6caee1766820f17bf001350d5463e16. `java_toolchain.header_compiler_direct` should always be set when toolchain resolution is enabled.

No migration is needed for the built-in toolchains, or for custom toolchains using `default_java_toolchain`.

**Comment by hlopko** [comment]
Hi Liam, could you pls update this issue to follow https://bazel.build/breaking-changes-guide.html? (e.g. the title of the issue is not right, I could fix that myself but that link is quite nicely written and contains useful advice :).

**Comment by cushon** [comment]
The docs say the title should start with the name of the flag, which is `incompatible_require_java_toolchain_header_compiler_direct`. The [example](https://github.com/bazelbuild/bazel/issues/6611) has a similar title. Did you already update the title, or am I missing something?

**Comment by hlopko** [comment]
Oh sorry for the confusion it was me who should read the docs. I thought the format has to be `<flag-name>: Description` (note the colon). Sorry again :/
