### ISSUE TITLE
Bazel does not distinguish between aborted and failed repository fetches

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#7993]
To reproduce with Bazel 0.25.0 rc1:
```
$ git clone https://github.com/tensorflow/tensorflow.git
$ cd tensorflow
$ yes "" | ./configure
$ bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package --incompatible_disable_genrule_cc_toolchain_dependency 
Starting local Bazel server and connecting to it...
ERROR: /usr/local/google/home/pcloudy/.cache/bazel/_bazel_pcloudy/d2f15366e3b15100d3593f2d595721a3/external/com_github_googlecloudplatform_google_cloud_cpp/google/cloud/BUILD:31:11: in cmd attribute of genrule rule @com_github_googlecloudplatform_google_cloud_cpp//google/cloud:generate_build_info: $(CC) not defined
INFO: An error occurred during the fetch of repository 'com_google_absl'
INFO: Call stack for the definition of repository 'com_google_absl':
 - /usr/local/google/home/pcloudy/workspace/tensorflow/tensorflow/workspace.bzl:135:5
 - /usr/local/google/home/pcloudy/workspace/tensorflow/WORKSPACE:104:1
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis of target '@com_github_googlecloudplatform_google_cloud_cpp//google/cloud:generate_build_info' failed; build aborted
INFO: Elapsed time: 7.706s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (301 packages loaded, 6067 targets configured)
```

Bazel reports an error in `com_google_absl`, but the actual error comes from `com_github_googlecloudplatform_google_cloud_cpp`

**Comment by aehlig** [comment]
First note that the call stack is not _incorrect_; it does show the correct place where the repository was defined. It might seem unrelated, but it is still factually correct.

The more fundamental problem in the implementation of external repositories is that all interrupted fetches look the same to the repository rule: a timeout (which would be a legitimate fetch failure) is reported to the repository rule the same way as an "abort the build, as something else has failed anyway". And technically the statement is correct: an error did occur while the fetch of that repository was going on; but it is certainly a legitimate feature request to distinguish between the reasons why a fetch was aborted. As a work around, you can `sync` or `fetch` first, or simply build with `-k`.

**Comment by aehlig** [comment]
Related (but different) issue #3851.

**Comment by aehlig** [comment]
Under review https://bazel-review.googlesource.com/c/bazel/+/97350
