### ISSUE TITLE
Document the persistent worker API

### ISSUE THREAD

**Issue by Ubehebe** [bazelbuild/bazel#7997]
I recently implemented a [persistent worker in Python](https://github.com/Ubehebe/bazel-worker-examples). A primary difficulty was the lack of documentation for persistent workers. They seem to have no documentation on docs.bazel.build, though they are mentioned in a [few](https://docs.bazel.build/versions/master/command-line-reference.html#flag--experimental_spawn_scheduler) [places](https://docs.bazel.build/versions/master/be/java.html#java_toolchain).

The best non-documentation resources about persistent workers include [this Bazel blog post](https://blog.bazel.build/2015/12/10/java-workers.html) from 2015, [this bazel-discuss thread](https://groups.google.com/forum/#!msg/bazel-discuss/oAEnuhYOPm8/ol7hf4KWJgAJ) from 2016,  and [this Medium post](https://medium.com/@mmorearty/how-to-create-a-persistent-worker-for-bazel-7738bba2cabb) from 2017. I think they could be turned into official docs without too much effort.

The persistent worker feature is valuable for many kinds of tools. It deserves documentation that reflects its value.

**Comment by endobson** [comment]
I just ran into this as well. https://docs.bazel.build/versions/master/multiplex-worker.html exists now, but isn't linked anywhere so isn't discoverable.

**Comment by susinmotion** [comment]
A note not to forget to include the location of log files generated by workers, re: #1082

**Comment by meisterT** [comment]
@larsrc-google created https://docs.bazel.build/versions/master/persistent-workers.html in https://github.com/bazelbuild/bazel/commit/4513812aa52a570544033fec23837bd16ecb8757 recently.

Lars, can you please double check the references above and see if we missed something?

**Comment by larsrc-google** [comment]
I believe we have include all the references mentioned.
