### ISSUE TITLE
Add options to ignore `deprecation` warnings

### ISSUE THREAD

**Issue by schroederc** [bazelbuild/bazel#8001]
### Description of the feature request:

Add option to ignore warnings emitted due to `deprecation` attributes set on targets.

### Feature requests: what underlying problem are you trying to solve with this feature?

Reduce log spam during dev and CI builds for known deprecation issues while migration from deprecated targets is not yet possible.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
