### ISSUE TITLE
improve turbine cold-start performance

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#8006]
It seems to me that using a persist worker for turbine Java header compilations would be beneficial for the same reasons as running javac as a persistent worker is. Has this been considered?

**Comment by iirina** [comment]
cc: @cushon

**Comment by cushon** [comment]
I considered it, but decided to use a graalvm native-image for turbine instead. That approach has shown good startup performance without the overhead of additional workers.

**Comment by benjaminp** [comment]
I see. So maybe this issue is actually feature request to graal turbine in Bazel's java tools. :)

**Comment by meisterT** [comment]
cc @larsrc-google

**Comment by larsrc-google** [comment]
That, or use multiplex workers.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by fmeum** [comment]
@sgowroji Could you reopen?

**Comment by benjaminp** [comment]
#19361
