### ISSUE TITLE
Issue with Bazel wrapper portability

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#801]
@bsilver8192 see https://github.com/bazelbuild/bazel/commit/ba04b2d2d2466540c39c93539285d7c97216272a#commitcomment-15559735.

**Comment by damienmg** [comment]
I agree with Brian, we should not make that script too complex and let the wrapper portability happens in the vendored script.

However, we might want to provide a vendor script for the future that copies all your dependencies in your workspace file (i.e. vendor the external package, vendor the various bazel binaries and provide the correct WORKSPACE file). In that case then we would need to provide a nice wrapper that is portable.

**Comment by mrdomino** [comment]
FYI I also agree with Brian. The current approach seems good -- I just hadn't grokked that tools/bazel would be something other than bazel-real.
