### ISSUE TITLE
Disable heap dumper (high priority for us!)

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#8013]
How to disable heap dump in Bazel?

In our case heap dump after OOM caused a bunch of stuck processes (for at least 2 hours):
![aaa](https://user-images.githubusercontent.com/2255111/56010579-df4e5200-5cec-11e9-83f3-c814e989a8a1.png)

Why could that happen? Version 0.23.2. OS Linux.

**Comment by meisterT** [comment]
Does it help you to add `--host_jvm_args=-XX:-HeapDumpOnOutOfMemoryError` to your bazel startup flags?

**Comment by meisterT** [comment]
I am closing this based on the reaction on my last comment. Feel free to reopen.

**Comment by excitoon** [comment]
Thank you @meisterT for your advice. And this is totally incorrect issue.
Just for future organic users, `HeapDumpOnOutOfMemoryError`,
`HeapDumpPath`, `UseParallelOldGC` are not indicator of an issue, as I
thought from the start (must have missed this `On` word). These are simply
default options of internal command line. 😅
