### ISSUE TITLE
bazelrc: Remove inheritance of targets from `bazel build` in `bazel cquery`, `bazel clean`

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#8014]
`.bazelrc`:
```
build //some:target # This is pretty useful
```

With such settings one no longer use `cquery` and `clean` because targets are going to its command line which is not intended for that.

Can we just skip inheriting targets from build (but leave settings as they are useful) in these commands?

**Comment by aiuto** [comment]
Yuch. I would propose that the request is really more like
   "Only apply rc lines to the specific command named"
That would imply we fix this all around, rather than just special casing clean and cquery.

The docs (https://docs.bazel.build/versions/master/guide.html#bazelrc), OTOH, talk about rule inheritance, such that test inherits from build. That is convenient, but magical behavior, since it is not obvious it should be so.  I would advocate that we should eliminate that inheritance and clarify that
- while *building* targets for test runs, the build options apply. That can happen without any notion of command inheritance.

**Comment by excitoon** [comment]
@aiuto I see it more like "only apply inheritance rules to options (starting from '-')".

Generally, you cquery the same option set as you build for. That is why inheritance is a good thing here.

**Comment by gregestren** [comment]
I didn't even realize you could set targets in the bazelrc. I wonder how common that is.

@excitoon - what exactly do you do with this? Are you usually only building a single target?

**Comment by excitoon** [comment]
@gregestren Well, building bunch of targets by one `--config` setting (and other bunch by another). This is pretty useful thing. Is that something accidental?

**Comment by gregestren** [comment]
No, I don't think it's accidental. But I wasn't personally familiar with it, and I know people have different kinds of usage patterns.

That honestly sounds reasonable to me.

**Comment by beasleyr-vmw** [comment]
Just ran into this with `clean` when trying out [user-defined flags][1].

```console
$ cat .bazelrc
build --no//my/project:boolean_flag
$ bazel clean
...
ERROR: Unrecognized arguments: --no//my/project:boolean_flag
```

A comment in `CleanCommand.java` suggests that its inheritance from `build` should go away: https://github.com/bazelbuild/bazel/blob/93e269e6c7e797c0c0245fbcfdddfc3fe3b8ae61/src/main/java/com/google/devtools/build/lib/runtime/commands/CleanCommand.java#L53-L54

It makes sense to me why `cquery` inherits  from `build`, but I don't yet know why `clean` should. (Maybe to inherit the output_root family of args?) I'll probably patch this out locally.

[1]: https://docs.bazel.build/versions/master/skylark/config.html#settings-build-settings-on-the-command-line

**Comment by gregestren** [comment]
Please share what you find, Ryan. I'm also marking this to discuss later this week among some core Bazel devs to see if anyone knows the history on this.

**Comment by beasleyr-vmw** [comment]
Okay, so I read the rest of CleanCommand.java, and the only referenced flag from `build` is [`--symlink-prefix`](https://docs.bazel.build/versions/master/command-line-reference.html#flag--symlink_prefix). It'd be easy to point CleanCommand to `BuildRequestOptions.class` and drop inheritance from `build`, but then users who set `--symlink_prefix` via `.bazelrc` (everyone using `--symlink_prefix`?) would end up with dangling symlinks w/o also adding a `clean` stanza.

However, @aiuto's take in https://github.com/bazelbuild/bazel/issues/8014#issuecomment-484176700 is prolly the right call for Bazel as a whole. I'm guessing it wouldn't take a whole lot of surgery to implement, but as a breaking change it'd have to wait until the next major release to ship.

https://github.com/bazelbuild/bazel/blob/e904605808e83cf2555f8c6ee7183ab7038e1f2c/src/main/java/com/google/devtools/build/lib/runtime/BlazeOptionHandler.java#L165-L187

https://github.com/bazelbuild/bazel/blob/e904605808e83cf2555f8c6ee7183ab7038e1f2c/src/main/java/com/google/devtools/build/lib/runtime/BlazeOptionHandler.java#L522-L535

(Delete `getCommandNamesToParseHelper` and replace its call in `getCommandNamesToParse` with `result.add(commandAnnotation.name())`.)

**Comment by gabroo** [comment]
What is the recommended way of specifying targets for `bazel build` in the `.bazelrc` without breaking `bazel clean`?

![image](https://user-images.githubusercontent.com/6046841/75704568-72c6a380-5c6e-11ea-9d06-ad8fe8543989.png)

**Comment by gregestren** [comment]
Thanks for this feedback.

> However, @aiuto's take in [#8014 (comment)](https://github.com/bazelbuild/bazel/issues/8014#issuecomment-484176700) is prolly the right call for Bazel as a whole. I'm guessing it wouldn't take a whole lot of surgery to implement, but as a breaking change it'd have to wait until the next major release to ship.

It's not obvious to me breaking the inheritance between `test` and `build` offers the right experience. All `test` is, ultimately, is a glorified `build` + `run`. The `build` part is already implicit, so the relationship between their flags doesn't feel arbitrary to me.

**Comment by gregestren** [comment]
> What is the recommended way of specifying targets for `bazel build` in the `.bazelrc` without breaking `bazel clean`?

You could always add a `--config` to your build. But it's not ideal since it takes away some of the convenience of having the target auto-trigger in the first place.

I think we need Bazel changes to make this use case work cleanly.

**Comment by gabroo** [comment]
Thanks for the suggestion. I'm using `--config` for now, and it works

**Comment by sbenedetto** [comment]
Hi, What is the status of this ticket? I also stumbled upon this issue. We have configs where we exclude targets during the build, but the list of excluded targets is inherited also by the `run` (along with `test` and `clean`) command and it fails miserably when executing the application as the excluded list of targets is passed to the application.

**Comment by gregestren** [comment]
`bazel clean` failing with user-defined flags (https://github.com/bazelbuild/bazel/issues/8014#issuecomment-587665769)  is fixed with https://github.com/bazelbuild/bazel/issues/11506. `--no//my/project:boolean_flag` still fails but `--//my/project:boolean_flag=0` works.

I think we could fix `bazel clean` failures on `//some:target` by a small extension to https://github.com/bazelbuild/bazel/pull/11508/files that changes lines 137-140 to a warning vs. failure.

Excluding targets differently for `build` vs. `test` vs. `run` isn't obvious because there's legitimate overlap for these commands. Eliminating that inheritance can just as easily break users who depend on it. For this case it's really best to break the ambiguity by creating a `--config=exclude_targets` mode and triggering that for the appropriate invocation.

**Comment by djmarcin** [comment]
> `bazel clean` failing with user-defined flags ([#8014 (comment)](https://github.com/bazelbuild/bazel/issues/8014#issuecomment-587665769)) is fixed with #11506. `--no//my/project:boolean_flag` still fails but `--//my/project:boolean_flag=0` works.

It seems that if a string or string list flag contains the string "//" then it still fails:
```
build --@rules_rust//:experimental_incremental_prefixes=//foo/bar
```
```
$ bazel clean
INFO: Invocation ID: 036ac0f9-0e69-459a-91fe-9787d4cf3c9f
ERROR: Unrecognized arguments: --@rules_rust//:experimental_incremental_prefixes=//foo/bar
```

Changing this to just a single slash causes the warning instead:
```
$ bazel clean
INFO: Invocation ID: 86dbe56b-9c0f-47e5-a8c5-22009db74fbe
WARNING: Blaze clean does not support starlark options. Ignoring options: [--@rules_rust//:experimental_incremental_prefixes=/foo/bar]
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
```

**Comment by gregestren** [comment]
@djmarcin which Bazel version were you using? Note https://github.com/bazelbuild/bazel/issues/12808#issuecomment-849128627.

**Comment by anthpi** [comment]
Any update on this issue? We would like NOT to get any warning for user defined build settings when running bazel clean command.

**Comment by gregestren** [comment]
See the final comments at https://github.com/bazelbuild/bazel/issues/13473. I'd ask for any further clarification on that thread.
