### ISSUE TITLE
remote: error while parsing .d file

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#8015]
<s>```
ERROR: /home/chebotarev/project/some/BUILD:8:1: error while parsing .d file: /home/chebotarev/.cache/bazel/_bazel_chebotarev/87b9ad596471673f453285a61f1d55a1/execroot/__main__/bazel-out/k8-opt/bin/some/_objs/target/source_name.pic.d (No such file or directory)
Target //some:target failed to build
```

`some/BUILD`:
```
cc_library(
  name = "target",
  srcs = ["source_name.cpp"]
)
```

`.bazelrc`:
```
build --experimental_strict_action_env
build --nolegacy_whole_archive
build --compilation_mode=opt
build --remote_http_cache=http://some.storage.ru
build --spawn_strategy=standalone
```

Can you advice something about it?

Bazel 0.23.2, OS Linux
</s>

**Comment by excitoon** [comment]
Bazel is working just fine.

**Comment by cherishTMYY** [comment]
> Bazel is working just fine.

hello, I also encountered the same problem.How did you solve it at that time?
