### ISSUE TITLE
Bazel CI: Tulsi is broken

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#8016]
With Bazel@Release:
https://buildkite.com/bazel/tulsi-bazel-darwin

With Bazel@HEAD:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/914#f273d29f-e93c-4831-840e-a1da24409992

@philwo Is this caused by the upgrade of the mac machines?

/cc @DavidGoldman

**Comment by philwo** [comment]
I think so. I'm working on adding an xcode_version tag to the YAML so that we can continue to run these projects on an older Xcode version.

**Comment by meteorcloudy** [comment]
Thanks!

**Comment by DavidGoldman** [comment]
The `xcode_version` tag has been added, right? I'll update Tulsi to use it

**Comment by philwo** [comment]
Yes, please give it a try and let me know if it works :)

**Comment by DavidGoldman** [comment]
Just pushed https://github.com/bazelbuild/tulsi/commit/f7e894221c9d598f188f570e9259012262a254c4, hopefully it fixes the failure

**Comment by DavidGoldman** [comment]
Looks like the current failure is caused by spaces in the Xcode installation path, can you replace it with `_`?

**Comment by philwo** [comment]
@DavidGoldman I see... yeah, we can do that.

I've removed the space from the path to Xcode, it's now:

- /Applications/Xcode10.1.app
- /Applications/Xcode10.2.app

Hope that helps!

**Comment by philwo** [comment]
Tulsi seems to be green again: https://buildkite.com/bazel/tulsi-bazel-darwin/builds/108 :)
