### ISSUE TITLE
Support exec_compatible_with on cc_binary/cc_library.

### ISSUE THREAD

**Issue by bwkimmel** [bazelbuild/bazel#8026]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Currently, exec_compatible_with is only available on genrules, shell rules and *_test: https://docs.bazel.build/versions/master/be/common-definitions.html#exec_compatible_with

### Feature requests: what underlying problem are you trying to solve with this feature?

A Remote Build Execution customer has a C++ compile action which runs out of memory on `n1-standard-2` machines, and it would be more cost-effective for them if they could target a small pool of larger machines, rather than replacing all of their machines with larger machines.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

0.23.2

### What's the output of `bazel info release`?

Don't know (reporting for a customer).

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

No

**Comment by gregestren** [comment]
@katre for triage

**Comment by katre** [comment]
This is a fairly simple request to implement, the open question is "which rules should allow adding exec_compatible_with?"

Right now, the answer is:
1. sh_*
2. *_test
3. genrule

**Comment by katre** [comment]
Discussed this today with the configurability team, and we decided to just throw it open and not restrict the target types. I'll send a PR shortly.

**Comment by katre** [comment]
Okay, not as easy as a single PR.

Plan:
1. Send a short PR that defaults to enable `exec_compatible_with` for all native rules. May also deprecate the `RuleClass.Builder` method that controls this.
2. Create an incompatible change issue to track removing the `execution_platform_constraints_allowed` from the `rule()` method in Starlark.
3. Then remove the functionality.
