### ISSUE TITLE
Bazel doesn't seem to handle the Visual Studio 2019 toolchain layout

### ISSUE THREAD

**Issue by tlemo** [bazelbuild/bazel#8028]
# using Bazel release 0.24.1

>set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC

>bazel build ...
INFO: Analysed 2 targets (1 packages loaded, 46 targets configured).
INFO: Found 2 targets...
ERROR: BUILD:2:1: C++ compilation of rule '//:hello' failed (Exit 1)

The target you are compiling requires Visual C++ build tools.
Bazel couldn't find a valid Visual C++ build tools installation on your machine.

Visual C++ build tools seems to be installed at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC
But Bazel can't find the following tools:
    VCVARSALL.BAT, cl.exe, link.exe, lib.exe, ml64.exe

Please check your installation following https://docs.bazel.build/versions/master/windows.html#using

INFO: Elapsed time: 0.275s, Critical Path: 0.04s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by cg31** [comment]
I can confirm it.

And I found this:
https://github.com/bazelbuild/bazel/pull/7686

I wonder if the change was in 0.24.1 and even Visual Studio 2017 works properly.

**Comment by yrwy** [comment]
rename 2019 to 2017
I use bazel to compile tensorflow,it works

**Comment by laszlocsomor** [comment]
https://github.com/bazelbuild/bazel/pull/7872 fixed this.
Bazel 0.25.0 will have the fix.

**Comment by raulftang** [comment]
Hi laszlocsomor,

But where can I get 0.25.0 now? When will you release it?

Thanks.

**Comment by laszlocsomor** [comment]
@raulftang : It's not released yet. Follow https://github.com/bazelbuild/bazel/issues/7498

**Comment by liao1995** [comment]
> rename 2019 to 2017
> I use bazel to compile tensorflow,it works

worked for me.

**Comment by ys10** [comment]
> rename 2019 to 2017
> I use bazel to compile tensorflow,it works

I used bazel-0.21 & VS build tool 2019, meet the same problem.
And this resolution worked for me too.

**Comment by fighttiger25** [comment]
> > rename 2019 to 2017
> > I use bazel to compile tensorflow,it works
> 
> I used bazel-0.21 & VS build tool 2019, meet the same problem.
> And this resolution worked for me too.

Also works for me in order to build tensorflow 1.13.1 from source.

**Comment by amuuu** [comment]
I have the same problem. I only have the 2019 version so the renaming won't work for me.

All of the files that Bazel says it can't find, actually exist in these directories:
`...\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64` 
and  `...\Community\VC\Auxiliary\Build`

And in my `BAZEL_VC` variable I have added the directory to this path: `...\Community\VC`

I don't know why it doesn't work.
Also, I have Visual studio installed in a custom directory if it makes any difference.

**Comment by amuuu** [comment]
I had the same problem.
My visual studio is installed in a custom directory in another drive and initially, the `C:\Program Files (x86)\Microsoft Visual Studio\2019\` directory didn't exist at all.

All the files that the error mentioned could be found in where my visual studio installed but Bazel still had errors.

Then I installed Build Tools for Visual Studio 2019 from [here](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019) and changed the `BAZEL_VC` variable to the directory that was created in `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC` and it fixed the problem. I hope it helps.
