### ISSUE TITLE
proto_library's import_prefix does not work across repository boundaries

### ISSUE THREAD

**Issue by RNabel** [bazelbuild/bazel#8030]
### Description of the problem / feature request:

`import_prefix` does not set the prefix correctly when the `proto_library` target lives in an external dependency.

### Feature requests: what underlying problem are you trying to solve with this feature?

The `import_prefix` should work across repo boundaries.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

(Skip to `Repro case` below for a zip containing a testable example of the reported behaviour)

Create a `proto_library` with `import_prefix` and reference it from a different workspace. If the depended-on repository has name `dependency_a` and the depended-on `proto_library` target uses `import_prefix = "prefix_a"`, the expected import path is in a .proto file is:

```
import "prefix_a/test.proto";
```
but the actual path is:
```
import "prefix_a/external/dependency_a/test.proto";
```

#### Repro case
Please download this [repro.zip](https://github.com/bazelbuild/bazel/files/3077400/repro.zip), which illustrates this behaviour using a `local_repository`.

```
$ tree
.
├── BUILD
├── WORKSPACE
├── local_repo
│   ├── BUILD
│   ├── WORKSPACE
│   └── imported.proto
└── test.proto
```

Build the repro target: `bazel build :test_proto`
The file `test.proto` contains both the expected, non-functional import path, and the actual import path.

### What operating system are you running Bazel on?

macOS 10.14

### What's the output of `bazel info release`?

Tested on both 0.22 and 0.24.1

###  Have you found anything relevant by searching the web?

Related error: `proto_source_root` not working across multiple workspaces https://github.com/bazelbuild/bazel/issues/4665

**Comment by aiuto** [comment]
My bad on the mis-categorization

**Comment by hlopko** [comment]
Hi Robin, could you pls check that https://github.com/bazelbuild/bazel/pull/8683 fixes your problem?
