### ISSUE TITLE
No stack trace or core dump displayed after `bazel test` or `bazel run`

### ISSUE THREAD

**Issue by finnball** [bazelbuild/bazel#8050]
### Description of the problem / feature request:

No stack trace or core dump displayed after a failed test or a failed run.

### Feature requests: what underlying problem are you trying to solve with this feature?

Making the debugging of tests easier.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Added a simple `abort();` to a `cc_test`. Then run the following:

`bazel test --test_output=errors --verbose_failures ...`

Should output something like this:
```
INFO: From Testing //:hello_test:
==================== Test output for //:hello_test:
Running main() from gmock_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Greeter
[ RUN      ] Greeter.Works
external/bazel_tools/tools/test/test-setup.sh: line 310:  7380 Aborted     (core dumped) "${TEST_PATH}" "$@" 2>&1
================================================================================
```

The command `bazel run` which combined with `--verbose_failures` only yields:

`Aborted (core dumped)`

It would be way more useful if we could have the stack trace outputted here. Especially for remote execution when we don't want to have to shell into a worker. Would it be possible to display a stack trace?

### What operating system are you running Bazel on?
Arch

### What version of Bazel are you using?
v0.24.1

**Comment by finnball** [comment]
Possibly related: https://github.com/bazelbuild/bazel/issues/3380

**Comment by aiuto** [comment]
Handing to remote exec team, but that is just a guess at this point.

**Comment by buchgr** [comment]
I don't see how this is related to remote execution.

**Comment by jin** [comment]
I believe test execution (test-setup.sh) falls under local execution.

**Comment by cnsgsz** [comment]
I ran into the same issue. Is there any update on the bug or suggestions for work around? Thanks!

**Comment by susinmotion** [comment]
This isn't feasible to fix for Bazel run since it execs the command, so by the time the command crashes, Bazel is out of the picture. Having Bazel use exec was an intentional change made last year in order to correctly handle stdin of binaries.

For Bazel test, printing the stack trace is the responsibility of the test framework, so in this case, you may want to file a feature request with googletest.

**Comment by Jingzhao123** [comment]
> I ran into the same issue. Is there any update on the bug or suggestions for work around? Thanks!

Hi, @cnsgsz I encounter the same issue. How did you resolve it?

**Comment by Ryang20718** [comment]
install systemd-coredump
