### ISSUE TITLE
incompatible_tls_enabled_removed: flip it and enable tls by default while deprecating tls_enabled flag

### ISSUE THREAD

**Issue by ishikhman** [bazelbuild/bazel#8061]
`--tls_enabled` flag is deprecated and should be removed in one of the next releases.
If `--incompatible_tls_enabled_removed` flag set to true, an error is rised in case tls_enabled is still in use.

**Migration**
* gRPC + enabled TLS:
Replace `--tls_enabled=true` and `--remote_cache=localhost:1234` with : `--remote_cache=grpcs://localhost:1234` or `--remote_cache=localhost:1234`
* gRPC + disabled TLS:
Replace `--tls_enabled=false` and `--remote_cache=localhost:1234` with : `--remote_cache=grpc://localhost:1234`

**Note**: the same migration plan applies to all of the following flags: `-remote_cache`, `--remote_executor `or `--bes_backend`. Use `--incompatible_tls_enabled_removed=true` to test.

**Note2**: http cache/executor is not affected

**Expected timeline**
Released with Bazel 0.26 (May 2019), off by default
Enabled by default with Bazel 0.30 (September 2019)

**Comment by hlopko** [comment]
Hi @ishikhman, just in the improbable case you didn't see it, we have a page with infomation how to roll out breaking changes over at https://bazel.build/breaking-changes-guide.html. There are some minor things missing in this issue (title format, missing migration-ready label)

Thanks!

**Comment by ishikhman** [comment]
thanks @hlopko! updated the issue accordingly.

**Comment by limdor** [comment]
Any plans to remove incompatible_tls_enabled_removed flag completely? The problem is that with bazel at HEAD when you specify all_incompatible_changes to do a migration the flag incompatible_tls_enabled_removed gets also set displaying the following warning.

`WARNING: Option 'incompatible_tls_enabled_removed' is deprecated: No-op. See #8061 for details.`
