### ISSUE TITLE
Windows and patch files

### ISSUE THREAD

**Issue by MarkaRagnos0815** [bazelbuild/bazel#8076]
### Description of the problem / feature request:

I am trying to build buildfarm-worker on a windows machine.
I did a bazel setup according to bazel website (bazel + java + maven + msys64 shell)

1. this fails since msys64 shell does not have a program called "patch" (I can not find one via pacman) to apply patches to google protobuf (3.7.0)
2. installed Linux subsystem for windows to provide a different bash (ubuntu 18.04) it fails since it cannot find the patch file

In both cases the error message looks nearly the same:

```
ERROR: error loading package '': Encountered error while reading extension file 'protobuf_deps.bzl': no such package '@com_google_protobuf//': Traceback (most recent call last):
        File "C:/users/awagner/_bazel_awagner/464pz4qt/external/bazel_tools/tools/build_defs/repo/http.bzl", line 55
                patch(ctx)
        File "<path_to_cache>/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 84, in patch
                fail(("Error applying patch %s:\n%s%s...)))
Error applying patch //third_party/com_google_protobuf:b6375e03aa.patch:

in case 1: bash: command not found
in case 2: /bin/bash: <path_to_buildfarm>/third_party/com_google_protobuf/b6375e03aa.patch: No such file or directory
```
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- get bazel buildfarm master
- do bazel setup according to bazel web site (windows)

### What operating system are you running Bazel on?

windows 10

### What's the output of `bazel info release`?

release 0.24.1

###  Have you found anything relevant by searching the web?

no

**Comment by aiuto** [comment]
Added both ExternalDeps and Windows. It is ExternalDeps problem, but windows team might have the better chance of addressing it well.

**Comment by laszlocsomor** [comment]
1. Install `diffutils` with pacman, that has `patch`.
2. Sorry, we don't support WSL.

**Comment by laszlocsomor** [comment]
Regarding case 1's `bash: command not found`:
- Where did you install msys64?
- Is that on the PATH?
- What's the output with `--verbose_failures`?

**Comment by MarkaRagnos0815** [comment]
1. diffutils does not contain patch, after some research i found this command "pacman -S base-devel --needed" which installs all needed apps
2. Installed msys64 to a custom directory o c drive
3. I added everything path variable according to bazel windows install guide

It works after installing "base-devel" package

**Comment by laszlocsomor** [comment]
@MarkaRagnos0815 : Thanks! Turns out `patch` has its own package, you can `pacman -S patch`. I'll update the docs.
