### ISSUE TITLE
Using --experimental_action_listener causes a failure when --distinct_host_configuration=false

### ISSUE THREAD

**Issue by kentsommer** [bazelbuild/bazel#8080]
### Description of the problem / feature request:

`--experimental_action_listener` fails (causes a dependency cycle) when  `--distinct_host_configuration=false`

Due to long running genrules I don't want to split target and host configurations (causes a steep build time increase). So, while that allows the `--experimental_action_listener` to work, it is not a satisfying solution.

```
kentsommer@x:~/scratch/bazel-al-repro$ ./build.sh 
Loading: 0 packages loaded
ERROR: /bazel-pool/test-bazel/bazel/_bazel_kentsommer/fb4104c6c149d00459043491050af5bb/external/bazel_tools/platforms/BUILD:99:1: in platform rule @bazel_tools//platforms:target_platform: cycle in dependency graph:
    //main:hello-world
.-> @bazel_tools//platforms:target_platform
|   @bazel_tools//platforms:x86_32
|   //tools:my_action_listener
`-- @bazel_tools//platforms:target_platform
This cycle occurred because of a configuration option
ERROR: Analysis of target '//main:hello-world' failed; build aborted
INFO: Elapsed time: 0.123s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. `git clone https://github.com/kentsommer/bazel-al-repro.git`
2. `cd bazel-al-repro`
3. `./build.sh`

### What operating system are you running Bazel on?

Ubuntu Xenial.

### What's the output of `bazel info release`?

```
kentsommer@x:~/scratch/bazel-al-repro$ bazel info release
release 0.24.1
````
 
###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

N/A.

**Comment by aiuto** [comment]
Klaus/Florian: your names are popping up on CLs regarding experimental_action_listener.
If this is not yours, please unassign yourselves.

**Comment by jin** [comment]
@dslomov which team owns action listeners?

**Comment by dslomov** [comment]
pinging @c-parsons

**Comment by c-parsons** [comment]
What's your use case for `--experimental_action_listener` ? 
We haven't quite **deprecated** that flag (we'd like to, but need to migrate some of our users), but we do have a pretty decent alternative which should satisfy a number of use cases:

You can access the actions registered by a target in Starlark using `target.actions`. It will return a list of [Action](https://docs.bazel.build/versions/master/skylark/lib/Action.html) objects which you can inspect to get action details, and register your own actions based on those you find. [Here](https://github.com/bazelbuild/bazel-skylib/blob/master/lib/unittest.bzl#L133) is an example.

**Comment by kentsommer** [comment]
Use case was/is tighter integration of llvm/clang tooling: generation of a compilation database, hooked runs of clang-tidy or clang in static analysis mode etc.

I'll need to poke a bit more at the links you posted to be able to understand if it solves what I want to do.

**Comment by kentsommer** [comment]
@c-parsons your suggestion does work for me. Closing this out :+1:
