### ISSUE TITLE
Bazel v0.24.1 build fails with JDK 8 version 

### ISSUE THREAD

**Issue by guirish** [bazelbuild/bazel#8089]
### Description of the problem / feature request:

> Building Bazel v0.24.1 fails on s390x with OpenJDK version 8. However could build Bazel v0.24.1 using AdoptJDK 11.  **Is it fine to build Bazel with JDK version > 8** ? As [documentation ](https://docs.bazel.build/versions/0.24.0/install-compile-source.html)states only to use JDK 8.

### Feature requests: what underlying problem are you trying to solve with this feature?

> Trying to build envoy for Istio using Bazel v0.24.1.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Below are the build steps:
> $ wget https://github.com/bazelbuild/bazel/releases/download/0.24.1/bazel-0.24.1-dist.zip
$ unzip bazel-0.24.1-dist.zip
$ env EXTRA_BAZEL_ARGS="--verbose_failures --sandbox_debug --spawn_strategy=standalone --genrule_strategy=standalone --host_javabase=@local_jdk//:jdk"JAVA_HOME=/usr/lib/jvm/java-8-openjdk-s390x bash ./compile.sh

### What operating system are you running Bazel on?

> Ubuntu 18.04
(4 core CPU and 64GB RAM)

### Any other information, logs, or outputs that you want to share?
Build log:
> 
> If the files are large, upload as attachment or provide link.
`Slow read: a 1384856-byte read from /tmp/bazel_s41PzgDb/out/execroot/io_bazel/bazel-out/s390x-opt/bin/src/main/tools/process-wrapper took 6637 ms.
ERROR: /home/test/bazel/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/BUILD:153:1: error executing shell command: '/bin/bash -c set -e;rm -rf bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_output bazel-out/host/bin/src/java_tools/buildjar/java/com/go...' failed (Exit 1): bash failed: error executing command
  (cd /tmp/bazel_s41PzgDb/out/execroot/io_bazel && \
  exec env - \
    PATH=/usr/lib/jvm/java-8-openjdk-s390x/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
  /bin/bash -c 'set -e;rm -rf bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_output bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_java bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_java_list
mkdir bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_output bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_java
external/local_jdk/bin/javac  -classpath '\''third_party/auto/auto-value-1.6.3rc1.jar:third_party/auto/auto-value-annotations-1.6.3rc1.jar:third_party/error_prone/error_prone_annotations-2.2.0.jar:third_party/guava/guava-25.1-jre.jar:third_party/jcip_annotations/jcip-annotations-1.0-1.jar:third_party/jsr305/jsr-305.jar:third_party/protobuf/3.6.1/libprotobuf_java.jar:third_party/java/jacoco/org.jacoco.core-0.7.5.201505241946.jar:third_party/grpc/grpc-auth-1.10.0.jar:third_party/grpc/grpc-context-1.10.0.jar:third_party/grpc/grpc-core-1.10.0.jar:third_party/grpc/grpc-netty-1.10.0.jar:third_party/grpc/grpc-protobuf-1.10.0.jar:third_party/grpc/grpc-protobuf-lite-1.10.0.jar:third_party/grpc/grpc-stub-1.10.0.jar:third_party/tomcat_annotations_api/tomcat-annotations-api-8.0.5.jar:third_party/java/jdk/langtools/javac-9+181-r4173-1.jar'\'' -d bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_output @bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar-2.params
external/local_jdk/bin/jar cf bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar -C bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_output .
touch bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_output
')
Execution platform: @bazel_tools//platforms:host_platform
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.jar.Manifest$FastInputStream.<init>(Manifest.java:367)
        at java.util.jar.Manifest$FastInputStream.<init>(Manifest.java:362)
        at java.util.jar.Manifest.read(Manifest.java:230)
        at java.util.jar.Manifest.<init>(Manifest.java:81)
        at java.util.jar.Manifest.<init>(Manifest.java:73)
        at java.util.jar.JarFile.getManifestFromReference(JarFile.java:199)
        at java.util.jar.JarFile.getManifest(JarFile.java:180)
        at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:992)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:451)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.sun.tools.javac.main.Main.resourceMessage(Main.java:610)
        at com.sun.tools.javac.main.Main.compile(Main.java:543)
        at com.sun.tools.javac.main.Main.compile(Main.java:381)
        at com.sun.tools.javac.main.Main.compile(Main.java:370)
        at com.sun.tools.javac.main.Main.compile(Main.java:361)
        at com.sun.tools.javac.Main.compile(Main.java:56)
        at com.sun.tools.javac.Main.main(Main.java:42)
Target //src:bazel_nojdk failed to build
INFO: Elapsed time: 4225.408s, Critical Path: 1939.30s
INFO: 1391 processes: 1391 local.
FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel`

**Comment by Maronee** [comment]
Could this be a memory issue? As I spot this in the log 

> Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

You could try tunning it they explain it here under bazel/scripts/bootstrap/compile.sh

 ```
  # Use BAZEL_JAVAC_OPTS to pass additional arguments to javac, e.g.,
  # export BAZEL_JAVAC_OPTS="-J-Xmx2g -J-Xms200m"
  # Useful if your system chooses too small of a max heap for javac.
  # We intentionally rely on shell word splitting to allow multiple
```

Thats how I manage to at least compile 0.18.1 with oracle jdk 8 on s390x but nothing newer.

**Comment by guirish** [comment]
Until v0.19.0 bazel build is successful on s390x with listed changes for BAZEL_JAVAC_OPTS but from v0.20.0 we are observing the build failure with OpenJDK 8 usage.

**Comment by philwo** [comment]
It's fine to build Bazel with OpenJDK 11. We test this on CI and we use OpenJDK 11 as the default embedded JDK for Bazel in recent versions. We should update our documentation regarding this.

I don't know why building with OpenJDK 8 fails on your machine, but the error message points to an out of memory issue - it might just require even more RAM.

**Comment by Namburger** [comment]
@philwo 
I increased swapsapce to 4GB now with no luck. I dont imagine memory is the issue, but rather the java heap space. but even increasing that didn't help :(

**Comment by mleonhard** [comment]
@guirish Would you please tell me where you found the log file?  Please reply in #10112.
