### ISSUE TITLE
Example usage in tools/python/toolchain.bzl has incorrect syntax

### ISSUE THREAD

**Issue by VictorAw** [bazelbuild/bazel#8096]
### Description of the problem / feature request:

Example usage of @bazel_tools//tools/python:toolchain.bzl is incorrect. If used directly, the load line results in the error message "Unable to load package for '@bazel_tools//tools/python/toolchain.bzl:toolchain.bzl': BUILD file not found on package path". The load command should instead be 'load("@bazel_tools//tools/python:toolchain.bzl", "py_runtime_pair")'.

### Feature requests: what underlying problem are you trying to solve with this feature?

Using the py_runtime_pair rule by following the example usage.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Write a BUILD file with 'load("@bazel_tools//tools/python/toolchain.bzl", "py_runtime_pair")' (which is the line written in the example usage) then try to build a rule in that BUILD file.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

0.24.0

**Comment by tuananhckpt90** [comment]
T

**Comment by tuananhckpt90** [comment]
Chiu

**Comment by brandjon** [comment]
Thanks for noticing this, fixing now.
