### ISSUE TITLE
Add support for cloning over SSH for git_repository rules

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel#810]
Currently, the `git_repository` workspace rules only support cloning over HTTP and do not support cloning over SSH. Adding support for SSH authentication [is not too difficult](http://www.codeaffine.com/2014/12/09/jgit-authentication/) but will require some careful consideration about how the credentials are passed.

**Comment by kayasoze** [comment]
This would really help our internal use-cases, where, for a sundry mix of reasons, HTTP can't be made secure and is unreliable, while SSH would be (obviously) more secure, and 10x faster to boot.

**Comment by johnynek** [comment]
by the way, hopefully it can interact with ssh-agent to get they key passwords as well.

**Comment by ulfjack** [comment]
I think we should consider running the clone in a separate process, which
could be implemented in another language, and would make this much more
hackable.

**Comment by davidzchen** [comment]
Since Skylark remote repositories is coming along, how about if we move these rules out of Java and implement them in Skylark instead to invoke the Git binaries?

This approach will also make it easier for someone to add similar rules, such as `hg_repository`.

**Comment by nelhage** [comment]
I wanted this for an internal project, so I took a stab at implementing this using the Skylark repository rule support now in HEAD. It's early and lacks a bunch of features, but I'm successfully using it to clone private repos into a bazel workspace: https://github.com/nelhage/bazel_git_repositories

Comments or contributions welcome, and I'd be happy to turn this into a PR against Bazel if it'd be productive to do so.

**Comment by wolfgangmeyers** [comment]
+1

**Comment by kchodorow** [comment]
I think bazel_git_repositories is the way to go.

**Comment by johnynek** [comment]
@kchodorow @damienmg I work with @nelhage who started bazel_git_repositories. I think he would be open to moving it to bazelbuild. I can reach out.

**Comment by davidzchen** [comment]
Thanks, @johnynek! That would be awesome.

Here's the tracking bug for replacing the native Git rules with bazel_git_repositories: #1408.
