### ISSUE TITLE
select() doens't work in remote repositories with labels pointing to the main one

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#811]
For example: `select({"@//:foo"}: <stuff>)`

This is a consequence of our awkward handling of main repository / default repository labels. 

@bsilver8192 is working on making this more sane in the code, but in the meantime, I'll fix it with a quick patch so as not to step on his toes and so that @chin33z is not blocked.

**Comment by chin33z** [comment]
Thanks. It really helps!
