### ISSUE TITLE
Warn when smart quotes are parsed on the command line

### ISSUE THREAD

**Issue by dmaclach** [bazelbuild/bazel#8110]
### Description of the problem / feature request:
Warn when "smart quotes" are found on the bazel command line. If the system sees any other quote character than 0x27 (apostrophe) or 0x22 (double-quote).

### Feature requests: what underlying problem are you trying to solve with this feature?
It is extremely easy to copy command lines out of docs or web pages that have converted " into ” and not realize it. Bazel makes this more likely since it has things like --features="foo=bar".
Distinguishing --features="foo=bar" from --features=“foo=bar” is almost impossible.

This caused a pile of pain for various developers because they were unaware that their features weren't being applied.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release exoblaze-2019.04.10-7 (mainline @242798681)

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
