### ISSUE TITLE
Accept .h++ as an extension for C++ headers

### ISSUE THREAD

**Issue by macbutch** [bazelbuild/bazel#8111]
### Description of the problem / feature request:

This is very similar to #302. I am trying to build an existing project ([libconfig](https://github.com/hyperrealm/libconfig)) which uses `.h++` as the extension for C++ header files but this extension is not supported by Bazel. This would affect anyone else working with a legacy code base using that naming.

For me, the error looks like this:

> ERROR: /private/var/tmp/_bazel_mark/85b990e918dfdf17ac335343d25f30e0/external/libconfig/BUILD.bazel:4:9: in srcs attribute of cc_library rule @libconfig//:lib: source file '@libconfig//:lib/libconfig.h++' is misplaced here (expected .cc, .cpp, .cxx, .c++, .C, .c, .h, .hh, .hpp, .ipp, .hxx, .inc, .inl, .H, .S, .s, .asm, .a, .lib, .pic.a, .lo, .lo.lib, .pic.lo, .so, .dylib, .dll, .o, .obj or .pic.o)

Ideally, I would be able to build libconfig with Bazel (without modifying the libconfig source).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Here is `WORKSPACE`, I expect there are other issues affecting the build:

```
http_archive(
  name = "libconfig",
  urls = [ "https://github.com/hyperrealm/libconfig/archive/v1.7.2.zip" ],
  build_file_content = """
cc_library(
  name = "lib",
  srcs= glob([
    "lib/*.c",
    "lib/*.c++",
    "lib/*.h",
    "lib/*.h++"
  ]),
  hdrs = [\"lib/libconfig.h++\"],
  visibility = [\"//visibility:public\"]
)
""",
  sha256 = "a3ae202153fafb40558c26831429ce39845b2395ad8d30269a50e309a7585a8c",
  strip_prefix = "libconfig-1.7.2",
)
```

The issue can be triggered by specifying libconfig as a dependency:

```
cc_library(
        ...,
        deps = [
            ...,
            "@libconfig//:lib"
        ],
)
```

### What operating system are you running Bazel on?

MacOS and Ubuntu Xenial.

### What's the output of `bazel info release`?

release 0.24.1

###  Have you found anything relevant by searching the web?

I found #302 which is the same issue but for files with `.c++` extension. I have not found anything related to header files. I imagine that this naming system is fairly rare.

**Comment by oquenchil** [comment]
We could accept this. Could you please send a PR?

**Comment by macbutch** [comment]
@oquenchil, there is a linked PR, I've just updated it to resolve a conflict.
