### ISSUE TITLE
not all outputs were created or valid (Remote caching, all platforms)

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#8125]
0.23.2

```
	ERROR: /some/path/BUILD:25:1: output 'some/outpu.t' was not created
	ERROR: /some/path/BUILD:25:1: not all outputs were created or valid
```

@meteorcloudy 
This issue happens every time when cache server (https://github.com/neitanod/toxy) terminates connection without an answer:
```
[toxy]$ ./main -p 9999 -t leave:asap
2019/04/24 07:18:31 Starting reverse proxy for leave:asap
2019/04/24 07:19:02 unsupported protocol scheme "leave"
```

**Comment by excitoon** [comment]
Basically the problem is zero answer for action result is perfectly fine (??) and that leads to 0 outputs of an action, which is downloading without an error.

ef7fe3deeab7bc85e7b8c83e12a6cdc6c877bf84 fixes that, but the problem is more general.

I can guess Bazel shall have some kind of tolerance to network errors. Maybe some checksums for cache entries?

**Comment by buchgr** [comment]
@excitoon 

> Basically the problem is zero answer for action result is perfectly fine (??) and that leads to 0 outputs of an action, which is downloading without an error.

Yes it's fine for an action to not produce an output file, but then it must also not declare an output file or else you'll see this error.

> I can guess Bazel shall have some kind of tolerance to network errors. Maybe some checksums for cache entries?

We do have that, but it looks like that this is not the problem here. Would have a reproducer for me to take a look at?

**Comment by excitoon** [comment]
@buchgr 
```
git clone https://github.com/neitanod/toxy
go run toxy/main.go -p 9999 -t bad &
bazel build //some:thing --spawn_strategy=standalone --remote_http_cache=http://localhost:9999
```

**Comment by buchgr** [comment]
@excitoon how does the //some:thing target look like?

**Comment by excitoon** [comment]
Any cacheable target with outputs. E.g. for bazel itself:
```
[chebotarev@some_machine bazel]$ bazel build //src:bazel --spawn_strategy=standalone --remote_http_cache=http://localhost:9999
INFO: Invocation ID: 42a78889-b7bf-4617-b9d7-e65ec085bc84
INFO: Analysed target //src:bazel (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 7] [-----] BazelWorkspaceStatusAction stable-status.txt
URI (GET): localhost:9990/ac/6953a6c58d4dc26c7160d766f3293f0d78621719e78c2cba85e7c006ec9257a1
ERROR: /home/chebotarev/bazel/src/tools/android/java/com/google/devtools/build/android/BUILD:21:1: output 'src/tools/android/java/com/google/devtools/build/android/all_android_tools_deploy.jar' was not created
ERROR: /home/chebotarev/bazel/src/tools/android/java/com/google/devtools/build/android/BUILD:21:1: not all outputs were created or valid
[1 / 10] 4 actions running
    Building deploy jar .../devtools/build/lib/bazel/BazelServer_deploy.jar; 0s remote-cache
    Building deploy jar .../devtools/build/android/all_android_tools_deploy.jar; 0s remote-cache
    .../java/com/google/devtools/coverageoutputgenerator:all_lcov_merger_tools; 0s remote-cache
    Building deploy jar .../build/importdeps/ImportDepsChecker_deploy.jar; 0s remote-cache
URI (GET): localhost:9990/ac/9d51dc88f1684479abed944587c2ce01605e75ab215a49e4c068645f9e7bb527
Target //src:bazel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.320s, Critical Path: 0.07s
INFO: 1 process: 1 remote cache hit.
FAILED: Build did NOT complete successfully
```

**Comment by excitoon** [comment]
@buchgr about a target without outputs and without output file, what is the caching strategy for it? Shall Bazel ask cache for that absence of files?

**Comment by buchgr** [comment]
@excitoon aww I see what you mean - that's indeed a bug.

> This issue happens every time when cache server (https://github.com/neitanod/toxy) terminates connection without an answer:

This statement is not fully correctly. what toxy seems to do is send a 200 OK response with an empty body. So that's a badly behaving server. That's different from the server just terminating the connection.

I think the proper fix would be to add a check that the generated outputs are a super set of the declared outputs.

**Comment by excitoon** [comment]
@buchgr why not exact set?

**Comment by buchgr** [comment]
@excitoon it's totally legal for a  command to create more output files than declared in Bazel (i.e. debug output).

**Comment by excitoon** [comment]
@buchgr But Content-Length is not a mandatory header, so theoretically,
Bazel can confuse accidental disconnect from graceful shutdown, as I can
guess.

**Comment by excitoon** [comment]
That thing that 0 bytes protobuf is a valid entity is indeed interesting.

**Comment by buchgr** [comment]
@excitoon it's a bit unfortunate. 0 bytes is a valid protobuf in that all fields in the protobuf will have its default values. We check the `int exit_code` field and the default value of an int is `0` which also happens to be the exit code signaling success...

**Comment by excitoon** [comment]
@buchgr Is e530f684be3d32cbb9e67a6905aebf6bbdb61a89 fine enough?

**Comment by buchgr** [comment]
Mostly yes. Open a PR (with a test) and we can discuss it further? I added a comment on the commit. Thanks!

**Comment by EricBurnett** [comment]
Changing the API to require a positively set field (so an empty proto isn't valid) is also https://github.com/bazelbuild/remote-apis/issues/6 . I don't think it can happen until V3, since it'd be a breaking change, but would be a long-term defense against this.

**Comment by buchgr** [comment]
I believe Bazel should be able to handle it client side independent of the API. To the best of my knowledge if the output is of type `Artifact` it's a declared and thus required output by Bazel.

**Comment by ob** [comment]
Any status on this, we are hitting this problem when using `bazel-remote` with Bazel 0.25.1. I still don't know how an empty file got into the `ac`, but: 

```
% find ac -size 0
ac/05/0520dc913c0d5fcf9791bb16affdeef7ea13ee5f8d6b42924b89c84a65d40fc6
```
When bazel asks for that file, `bazel-remote` happily hands it with size 0 which causes the build to fail because the output wasn't created.

**Comment by mostynb** [comment]
@ob: you might want to try upgrading bazel-remote, I added some ActionResult validation when implementing the gRPC interface, and then refactored the code so that the HTTP interface also has this validation.

**Comment by mostynb** [comment]
Duh, this part of the validation I added to bazel-remote is obviously out of spec (followup in https://github.com/buchgr/bazel-remote/issues/121).

**Comment by MikhailTymchukFT** [comment]
Starting with 4.0.0 release, bazel hangs when using `multiplex-worker` strategy. It fails immediately with the message described in #0 post when using other strategies like `sandboxed` or `local`.
