### ISSUE TITLE
Separate log of single failed action

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#8126]
I need a way to separate output from failed action from bazel stdout/stderr file.

How would I achieve this?
Now, when error has occurred stdout/stderr have mixed lines from different threads/actions. How would I get log for exact action (failed one)?

**Comment by buchgr** [comment]
Please ask questions of this kind on our mailing list bazel-discuss@googlegroups.com. Thanks!

**Comment by excitoon** [comment]
https://groups.google.com/d/msg/bazel-discuss/JmP5vBaj3Bs/KK9Jo0JdCwAJ

**Comment by excitoon** [comment]
@buchgr I have not received any answer there. May I ask you to re-open this issue for me? I can't do it myself now.

**Comment by excitoon** [comment]
The solution is to use (Build Event Protocol)[https://docs.bazel.build/versions/master/build-event-protocol.html]
