### ISSUE TITLE
Broken links in documentation about licenses

### ISSUE THREAD

**Issue by vhiairrassary** [bazelbuild/bazel#8138]
Since https://github.com/bazelbuild/bazel/commit/eb2fd5c7e9f09249b7050d14510dd8198a656ce9 there are invalid links about licenses in the online documentation like:

- https://github.com/bazelbuild/bazel/blob/eb2fd5c7e9f09249b7050d14510dd8198a656ce9/src/main/java/com/google/devtools/build/docgen/templates/be/functions.vm#L19
- https://github.com/bazelbuild/bazel/blob/master/site/docs/best-practices.md#third-party-dependencies

**Comment by alex-xnor** [comment]
Another one in https://docs.bazel.build/versions/master/be/overview.html, under the "Functions" section
