### ISSUE TITLE
Get rid of cmd_helper

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#8139]
It has been marked as deprecated for a long time and it's not really useful: https://docs.bazel.build/versions/master/skylark/lib/cmd_helper.html

cc @c-parsons

**Comment by laurentlb** [comment]
cc @alandonovan - if you want to delete some code, we need a flag to remove `cmd_helper`.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
