### ISSUE TITLE
ERROR: does not contain a toolchain for cpu 'aarch64'

### ISSUE THREAD

**Issue by hoonkai** [bazelbuild/bazel#8143]
### Description of the problem / feature request:

I am trying to install bazel 0.24.1 installed on aarch64 cpu with linux, but I keep running into an error.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
```
sudo ./compile.sh

[  Building Bazel with Bazel.h......
.WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
ERROR: /tmp/bazel_RUv58bmJ/out/external/local_config_cc/BUILD:45:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'aarch64'
ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
INFO: Elapsed time: 34.826s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (56 packages loaded, 339 targets c\
onfigured)

ERROR: Could not build Bazel
```

### What operating system are you running Bazel on?

Ubuntu 18.04

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

Here's some output:
```
java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
```

```
hostnamectl
   Static hostname: orangepipc2
         Icon name: computer
        Machine ID: cec95d764ec843898992c224851ff60f
           Boot ID: 42cc35273bcf4ea29c26ba7341b897f9
  Operating System: Ubuntu 18.04.2 LTS
            Kernel: Linux 4.19.34-sunxi64
      Architecture: arm64
```

```
uname -m
aarch64
```

**Comment by ArielleA** [comment]
I just built 0.25.2 on aarch64 in a debian 9.5 docker container by following the instructions on the bootstrapping page, I could spin up a Ubuntu docker container and try it:
```
root@f4387aef4783:/usr/src/bazel-dist# /usr/src/bazel-dist/output/bazel info            
bazel-bin: /root/.cache/bazel/_bazel_root/dd33e3ea7415426eac181c3fcdce1234/execroot/io_bazel/bazel-out/aarch64-fastbuild/bin
bazel-genfiles: /root/.cache/bazel/_bazel_root/dd33e3ea7415426eac181c3fcdce1234/execroot/io_bazel/bazel-out/aarch64-fastbuild/bin
bazel-testlogs: /root/.cache/bazel/_bazel_root/dd33e3ea7415426eac181c3fcdce1234/execroot/io_bazel/bazel-out/aarch64-fastbuild/testlogs
character-encoding: file.encoding = ISO-8859-1, defaultCharset = ISO-8859-1
command_log: /root/.cache/bazel/_bazel_root/dd33e3ea7415426eac181c3fcdce1234/command.log
committed-heap-size: 2465MB
execution_root: /root/.cache/bazel/_bazel_root/dd33e3ea7415426eac181c3fcdce1234/execroot/io_bazel
gc-count: 15
gc-time: 5532ms
install_base: /root/.cache/bazel/_bazel_root/install/c19067872b3c750354eb42c04e93f492
java-home: /usr/lib/jvm/java-8-openjdk-arm64/jre
java-runtime: OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01) by Oracle Corporation
java-vm: OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode) by Oracle Corporation
max-heap-size: 28631MB
output_base: /root/.cache/bazel/_bazel_root/dd33e3ea7415426eac181c3fcdce1234
output_path: /root/.cache/bazel/_bazel_root/dd33e3ea7415426eac181c3fcdce1234/execroot/io_bazel/bazel-out
package_path: %workspace%
release: release 0.25.2- (@non-git)
repository_cache: /root/.cache/bazel/_bazel_root/cache/repos/v1
server_log: /root/.cache/bazel/_bazel_root/dd33e3ea7415426eac181c3fcdce1234/java.log.f4387aef4783.root.log.java.20190516-193355.24579
server_pid: 24579
used-heap-size: 339MB
workspace: /usr/src/bazel-dist

```

**Comment by ArielleA** [comment]
Building the same in a `docker run -it ubuntu:bionic` and following the instructions gave the following output:
`Target //src:bazel_nojdk up-to-date:
  bazel-bin/src/bazel_nojdk
INFO: Elapsed time: 366.045s, Critical Path: 265.14s
INFO: 1777 processes: 1538 local, 239 worker.
INFO: Build completed successfully, 1824 total actions
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
DEBUG: /tmp/bazel_LDBwtjXC/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:49:5:
Current Bazel is not a release version, cannot check for compatibility.
DEBUG: /tmp/bazel_LDBwtjXC/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:51:5: Make sure that you are running at least Bazel 0.17.1.

Build successful! Binary is here: /usr/src/bazel-dist/output/bazel
root@47bf780d2859:/usr/src/bazel-dist# /usr/src/bazel-dist/output/bazel info
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
bazel-bin: /root/.cache/bazel/_bazel_root/dd33e3ea7415426eac181c3fcdce1234/execroot/io_bazel/bazel-out/aarch64-fastbuild/bin
bazel-genfiles: /root/.cache/bazel/_bazel_root/dd33e3ea7415426eac181c3fcdce1234/execroot/io_bazel/bazel-out/aarch64-fastbuild/bin
bazel-testlogs: /root/.cache/bazel/_bazel_root/dd33e3ea7415426eac181c3fcdce1234/execroot/io_bazel/bazel-out/aarch64-fastbuild/testlogs
character-encoding: file.encoding = ISO-8859-1, defaultCharset = ISO-8859-1
command_log: /root/.cache/bazel/_bazel_root/dd33e3ea7415426eac181c3fcdce1234/command.log
committed-heap-size: 1606MB
execution_root: /root/.cache/bazel/_bazel_root/dd33e3ea7415426eac181c3fcdce1234/execroot/io_bazel
gc-count: 3
gc-time: 200ms
install_base: /root/.cache/bazel/_bazel_root/install/e1b4cc5546196e1b12d9270ef6c69ead
java-home: /usr/lib/jvm/java-8-openjdk-arm64/jre
java-runtime: OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03) by Oracle Corporation
java-vm: OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode) by Oracle Corporation
max-heap-size: 28631MB
output_base: /root/.cache/bazel/_bazel_root/dd33e3ea7415426eac181c3fcdce1234
output_path: /root/.cache/bazel/_bazel_root/dd33e3ea7415426eac181c3fcdce1234/execroot/io_bazel/bazel-out
package_path: %workspace%
release: release 0.25.2- (@non-git)
repository_cache: /root/.cache/bazel/_bazel_root/cache/repos/v1
server_log: /root/.cache/bazel/_bazel_root/dd33e3ea7415426eac181c3fcdce1234/java.log.47bf780d2859.root.log.java.20190516-200814.18195
server_pid: 18195
used-heap-size: 384MB
workspace: /usr/src/bazel-dist
root@47bf780d2859:/usr/src/bazel-dist# uname -a
Linux 47bf780d2859 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:33:57 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux
`

**Comment by hoonkai** [comment]
I've just fixed it by giving it a larger heap space.

**Comment by vbatts** [comment]
@hoonkai ok, how did you do that? Could you provide more info before closing the issue

**Comment by hoonkai** [comment]
@vbatts  In my case, I only needed `--Xmx1000M` for `javac`.

**Comment by vbatts** [comment]
@hoonkai sorry for my ignorance. Where did you provide that flag?
```shell
+ EXTRA_BAZEL_ARGS=' --host_javabase=@local_jdk//:jdk --host_jvm_args=-Xmx2g --nokeep_state_after_build --notrack_incremental_state --nokeep_state_after_build'
+ ./compile.sh
Building Bazel from scratch......
Building Bazel with Bazel.
.WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/tmp/bazel_Wj4jXGXD/archive/libblaze.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
ERROR: Unrecognized option: --host_jvm_args=-Xmx2g
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
```
