### ISSUE TITLE
Make to_json() and to_proto() work on CcInfo

### ISSUE THREAD

**Issue by mboes** [bazelbuild/bazel#8146]
### Description of the problem

Given a `CcInfo`, calling its `to_json()` or `to_proto()` methods results in an error.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

If `cc` is any `CcInfo`, then `print(cc.to_json())` yields the following output:

```
Invalid text format, expected a struct, a string, a bool, or an int but got a CompilationContext for struct field 'compilation_context'
```

### What's the output of `bazel info release`?

Bazel 0.24.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
