### ISSUE TITLE
incompatible_restrict_named_params: make a number of params positional-only

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#8147]
This flag makes a number of parameters of Starlark builtin functions positional-only.

**Flag:** --incompatible_restrict_named_params

**Motivation**
The affected Starlark parameters were originally intended to be positional-only, but, due to an infrastructure bug, they were able to be specified by keyword for several releases.

An example case is that, today, one can specify:

```
len(x = [])
```

But `len`'s one parameter should be positional-only.

See #5010 for original bug.

**Migration**
We will incorporate automatic migration using buildifier for affected parameters. Migration can also be achieved manually by specifying affected parameters positionally (look to the Bazel Starlark builtins docs for positional ordering, when in doubt!)

**Comment by thomasvl** [comment]
Shouldn't the docs get updated to not use a name and have their description cover the name when describing behaviors?  i.e. - https://docs.bazel.build/versions/master/skylark/lib/globals.html#getattr, `default` appears to now only be positional, but given how it is documented, it really seems to call it out as something that is named instead.

**Comment by c-parsons** [comment]
Yes, you are correct. Lets track this as part of this issue. (I will own that change)

**Comment by dslomov** [comment]
Is migration tooling available?

**Comment by c-parsons** [comment]
@vladmos IIRC we discussed writing buildifier warnings for this, but I'm difficulty finding these conversations (and therefore I can't recall if we did any work towards this), do you recall?

**Comment by vladmos** [comment]
@c-parsons the actual pull request is https://github.com/bazelbuild/buildtools/pull/692 . There was a prototype in a different PR earlier that was closed by Github because I accidentally deleted the branch.

**Comment by laurentlb** [comment]
@vladmos Can you provide instructions for migration?

**Comment by vladmos** [comment]
The command is `buildifier --lint=fix --warnings=keyword-positional-params`, you'll need to either build Buildifier manually from head or wait for 0.29 which should be released this week.

Note that it will only fix (and warn about) the following top-level functions: https://github.com/vladmos/buildtools/blob/fe14be0e63262168393387d0f7c87250c44be5d2/warn/warn_bazel_api.go#L842-L856
Various methods such as `string.split` are not (yet) supported, and even if they were, buildifier can't guarantee to find all of their usages due to lack of static typing.

**Comment by meteorcloudy** [comment]
rules_rust is failing in downstream due to the flip of this flag:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1169#cc99beed-1b8a-468f-83fa-ffa0475c5b73

**Comment by c-parsons** [comment]
Are you sure it's failing due to this flag? The failure looks unrelated., and building rules_rust with release bazel at that flag seems to exhibit no failure on my machine...

**Comment by c-parsons** [comment]
Also looks like manually flipping the flag to false at HEAD Bazel doesn't fix the issue
Running culprit finder. https://buildkite.com/bazel/culprit-finder/builds/210#c0afdadf-fdc2-494d-a35b-4de47e9f4538

**Comment by c-parsons** [comment]
Culprit is 0c8f22e07a6fb7c31b2a9564a9ce4ae1196bb594, so unrelated to this change.

**Comment by meteorcloudy** [comment]
Ah, thanks for looking into this!

**Comment by dslomov** [comment]
Closing since the flag is flipped

**Comment by alandonovan** [comment]
Can we keep this open until the vestigial logic has been removed?

**Comment by laurentlb** [comment]
No, we always close issues when the incompatible flag is enabled by default.

You can file a bug for the code removal if you want.
