### ISSUE TITLE
--test_output=errors should be the default

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/bazel#815]
True, Bazel prints the log file name, but I think an interactive user would almost always want to see the failure reason.

**Comment by damienmg** [comment]
This was somehow made the default at some point of time and resulted in a lot case where it was spamming the user so it was reverted.

**Comment by cgrushko** [comment]
Do you have a link to that discussion?

**Comment by hanwen** [comment]
It was a google internal discussion. In short many people do 

  bazel test foo/bar/...

if you make some error in a base class, all of them will fail, and make the terminal log unusable.

**Comment by damienmg** [comment]
Anyway let's not do that.
