### ISSUE TITLE
bazel.io in-page tutorial links are broken

### ISSUE THREAD

**Issue by shahms** [bazelbuild/bazel#816]
A substantial fraction of the documentation links in the tutorial point to "<page>.md" rather than "<page>.html"; e.g. the "setting up" link from http://bazel.io/docs/tutorial/index.html

The "next" links in the tutorial are pretty much universally broken, but I recall encountering this issue on other pages as well.

**Comment by davidzchen** [comment]
This has been fixed with the newest doc push.
