### ISSUE TITLE
BES fails with Non-consecutive sequence number error

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#8160]
With Bazel from HEAD we see the below error quite a bit

```
ERROR: The Build Event Protocol upload failed: INVALID_ARGUMENT: INVALID_ARGUMENT: Non-consecutive sequence number
```

The error appeared on most of the failed steps in the below downstream run

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/932

**Comment by lfpino** [comment]
Thanks Jakob, I also saw it in one of our test, I think I know what the problem is. Will update in the next couple of hours with a rollback or a fix.
