### ISSUE TITLE
import_deps_checker tests aren't compatible with the current Bazel JDK

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#8162]
Because tests under //src/java_tools haven't been run, the code has decayed badly. I don't understand how to fix these.

# To reproduce:
```
$ bazel build --nokeep_going  //src/java_tools/import_deps_checker/javatests/...
INFO: Analysed 31 targets (0 packages loaded, 0 targets configured).
INFO: Found 31 targets...
ERROR: missing input file '@local_jdk//:jre/lib/rt.jar'
ERROR: /usr/local/google/home/jcater/repos/bazel/src/java_tools/import_deps_checker/javatests/com/google/devtools/build/importdeps/BUILD:84:1: //src/java_tools/import_deps_checker/javatests/com/google/devtools/build/importdeps:DepsCheckerClassVisitorTest: missing input file '@local_jdk//:jre/lib/rt.jar'
ERROR: /usr/local/google/home/jcater/repos/bazel/src/java_tools/import_deps_checker/javatests/com/google/devtools/build/importdeps/BUILD:84:1 1 input file(s) do not exist
INFO: Elapsed time: 0.325s, Critical Path: 0.02s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

I suspect that even cleaning this up to build, the tests still won't actually pass.

**Comment by katre** [comment]
In #8164, I add all tests under //src/java_tools _except_ the tests for `import_deps_checker`. Be sure to re-enable the tests when this is fixed.

**Comment by katre** [comment]
Buildtools also fails under jdk8. I don't know if there's a way to fix this for both.

**Comment by iirina** [comment]
@katre can you also link a log or an error snippet for buildtools?

**Comment by iirina** [comment]
I found the buildkite run: https://buildkite.com/bazel/bazel-bazel-github-presubmit/builds/2717#533453ca-1692-4357-a693-15e7257602b1

**Comment by cushon** [comment]
@kevin1e100 FYI for import_deps_checker.

`@local_jdk` shouldn't be used anymore, but even if the test resolves a JDK correctly `rt.jar` doesn't exist for JDK > 8.

I would try dropping in `@bazel_tools//tools/jdk:platformclasspath` instead of `@local_jdk//:jre/lib/rt.jar` and see if that works.

> `java.lang.NoSuchFieldError: ANNOTATION_PROCESSOR_MODULE_PATH`

That probably indicates the necessary `--patch-module=` flags aren't getting set, or are being set incorrectly.

**Comment by meisterT** [comment]
This seems to be fixed.

**Comment by meisterT** [comment]
likely, let's try?

**Comment by meisterT** [comment]
Nope, I though @meteorcloudy did, but I don't see a sign. Do you want to try it?

**Comment by meteorcloudy** [comment]
Sorry, I didn't, it was a drop-by comment when I was fixing something else.

**Comment by comius** [comment]
https://github.com/bazelbuild/bazel/pull/16491
