### ISSUE TITLE
Cleanup flags and code paths for legacy runtime resolution

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#8169]
Tracking bug for deleting `--incompatible_use_python_toolchains`, `--python_top`, `--python_path`, `--python2_path`, `--python3_path`, and the legacy code supporting these flags. `--python_path` is also tracked by #7901.

We actually still depend on a variant of the legacy mechanism within Google, so this cleanup won't be completed anytime soon.

**Comment by Warchant** [comment]
Any news?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
