### ISSUE TITLE
Can Bazel be configured to work with Clang on Android NDK?

### ISSUE THREAD

**Issue by mnbittorrent** [bazelbuild/bazel#817]
There's a note in this [example](https://github.com/bazelbuild/bazel/tree/master/examples/android) for android that says:

> Yes, we know that this is a little clunky. We are working on the following things (and more):
>
> Supporting other architectures than `armeabi-v7a` and compilers other than GCC 4.9

Is there any way to hack around this to swap GCC for Clang until it is officially supported?

**Comment by ahumesky** [comment]
We have the beginnings of support for clang, but it doesn't appear to be working at the moment, e.g.:

bazel build l:hello_world --fat_apk_cpu=x86 --android_compiler=clang3.6
INFO: Found 1 target...
ERROR: /usr/local/google/home/ahumesky/bazel-android-test/java/bazel/BUILD:26:1: C++ compilation of rule '//java/bazel:jni' failed: clang failed: error executing command external/androidndk/ndk/toolchains/llvm-3.6/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/x86-linux-android-4.8/prebuilt/linux-x86_64 -target i686-none-linux-android ... (remaining 37 argument(s) skipped).
src/main/tools/namespace-sandbox.c:645: execvp(argv[0], argv): No such file or directory

So it looks like something is not correctly declared in the generated crosstool file, which is done here:
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/android/AndroidNdkRepositoryFunction.java

If you'd like to try creating your own separate crosstool for clang, there is an example android ndk crosstool here: https://github.com/bazelbuild/examples/tree/master/android-ndk

**Comment by bsilver8192** [comment]
Another hint for anybody who looks at this: the BUILD file next to the CROSSTOOL file might need work too in order to include all of the appropriate files in the sandbox.

**Comment by ahumesky** [comment]
I've finished the initial updates to bazel to work with NDK r11, including clang support. This should be released to head by tomorrow some time. You should then be able to do:

    bazel build <target> --fat_apk_cpu=x86 --android_compiler=clang3.8

**Comment by ahumesky** [comment]
This is now available

**Comment by aj-michael** [comment]
For anyone reading this in the future, you will likely need Bazel 0.4.5 to use clang for Android builds. Otherwise you will encounter https://github.com/bazelbuild/bazel/issues/2601 in which the gcc includes paths are being used by clang instead of the clang ones.

Note also that starting in NDK 13 (Bazel 0.4.5), clang is the default.
