### ISSUE TITLE
Allow to override preserveName and prefixConsumer in create_library_to_link

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/bazel#8180]
### Description of the feature request:

Bazel's new CC Starlark API allows users to create `LibraryToLink` objects using `create_library_to_link`. The current implementation imposes `preserveName = true` and `prefixConsumer = true` for dynamic libraries. Please expose these flags to the user and allow overriding the default values.

### Feature requests: what underlying problem are you trying to solve with this feature?

With `create_library_to_link` dynamic libraries will be placed under the global `_solibs` directory. With `preserveName = true` Bazel generates an additional directory and places the library under `_solibs/<extra-dir>/<unmangled-lib>`. Additionally, `prefixConsumer = true` causes `<extra-dir>` to be made up of the package path to the library target as well as the package path to the consumer of the library. These paths can become rather large.

On MacOS the MACH-O header size is limited to 32k. If a target depends on many dynamic libraries, which require long load-commands or rpath-entries, then this limit can quickly be exceeded.

With [rules_haskell](https://github.com/tweag/rules_haskell) we have frequently encountered issues with the MACH-O header size limit in practice. rules_haskell already employs several work-arounds to avoid this issue. Currently, it is not possible for rules_haskell to make full use of the CC Starlark API and define Haskell build results with `create_library_to_link`, because the resulting load commands would exceed the MACH-O header size limit in practice.

With `preserveName = false` rules_haskell could make use of Bazel's builtin name mangling to avoid library name conflicts, while achieving sufficiently short load commands. Also, rules_haskell requires stable library names across consumers, which `prefixConsumer = false` would provide.

### What operating system are you running Bazel on?

MacOS Mojave 10.14.4

### What's the output of `bazel info release`?

```
release 0.24.0- (@non-git)
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

[nixpkgs](https://github.com/NixOS/nixpkgs/blob/36587a587ab191eddd868179d63c82cdd5dee21b/pkgs/development/tools/build-managers/bazel/default.nix)

**Comment by mboes** [comment]
It could also be worth considering an option that says "do preserve the library soname (à la `preserveName = True`, but assume it's unique, so don't bother with an extra layer of directories in the `_solibs` folder (à la `preserveName = False`)". Though it would then become the responsibility of the caller to make sure all libraries always have unique sonames.

**Comment by mboes** [comment]
Additional motivation for this feature request: https://stackoverflow.com/questions/46256118/bazel-java-app-with-jni-dependency.

The question is about how to create a native app that calls the JVM via the JNI. This looks pretty much impossible in modern day Bazel, because when calling `JNI_CreateJavaVM()`, the JVM dynamically loads additional shared objects that it expects to find in locations relative to `libjvm.so` (specifically, in the parent directory of its directory). If the real location of `libjvm.so` is obfuscated by symlinking, as is inevitably the case despite the fact that it's a system library not built by Bazel, then the dynamic loading will fail. No matter of `RUNPATH` or `-Djava.library.path` hacking fixes that.

**Comment by mboes** [comment]
There are two workarounds in the end:

- Write a `genrule` that writes the result of calling `realpath` on the location of `libjvm.so` to get the real absolute system location of the library's directory. Then hope the linker supports response files and pass the file to the linker as a response file with `-rpath` prepended.
- Use `patchelf` or similar, or `install_name_tool` on macOS, to fix up the `RUNPATH` of the produced binary in a postprocessing step.

Both are unfortunate. The first isn't very portable and hard to guess, and as for the second, I don't know how to post process a test in a genrule and have the genrule be a test too.

**Comment by aherrmann** [comment]
@oquenchil I took a shot at fixing this in https://github.com/bazelbuild/bazel/pull/8888.
