### ISSUE TITLE
skylark in documentation url

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#8185]
In our documentation, the urls look like: https://docs.bazel.build/versions/master/skylark/concepts.html

We should rename `skylark` to `starlark` and set a redirection.

**Comment by jin** [comment]
Taking a stab at this now. Having the unversioned navigation sidebar makes this more tricky; I think that needs to be complete first. If not, the sidebar's Starlark link will 404.

**Comment by allevato** [comment]
Now that [Buildifier 3.2.0](https://github.com/bazelbuild/buildtools/releases/tag/3.2.0) (released today) issues warnings for the word "skylark" found in comments and docstrings, anyone who has links to Bazel API documentation in their Starlark code will get these warnings and have to explicitly disable them or remove the links.

**Comment by brandjon** [comment]
This is moot in the current devsite documentation page.
