### ISSUE TITLE
--test_summary=testcase is sometimes wrong

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#8188]
For a sharded test with ~70 test cases, I get this output:
```
Test cases: finished with 3 passing and 1 failing out of 4 test cases
```

I suspect it's not handling sharding correctly. It so happens that the shard with the failing test has 4 test cases total.

**Comment by ulfjack** [comment]
@eransha75 @ittaiz

This was introduced in #5429.

**Comment by ulfjack** [comment]
How about this:
```
Test cases: finished with -32 passing and 57 failing out of 25 test cases
```

**Comment by ittaiz** [comment]
We indeed don't use test sharding so didn't encounter this...
