### ISSUE TITLE
Get the local path of external repositories

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#8190]
Let's say I write a tool that tries to understand BUILD files.

If the BUILD file contains `load("//foo:file1.bzl", "x")`, it easy to find `file.bzl` on the disk. But if the BUILD file contains, `load("@repo//foo:file2.bzl", "x")`, how can I find `file2.bzl` on the disk?

I can ask the user to first run `bazel fetch ... --experimental_repository_resolved_file=resolved.bzl`. This is very useful, because I can know the list of all external repositories. But how to get the corresponding local path?

Could the resolved file contain a `path` attribute for each repository?

**Comment by dslomov** [comment]
cc @aehlig

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
