### ISSUE TITLE
json output for experimental_repository_resolved_file

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#8191]
With `experimental_repository_resolved_file`, we output some very valuable information about external repositories. The data would be simpler to use if it was a more standard format like JSON (lots of tools can easily parse JSON files).

cc @dslomov

**Comment by dslomov** [comment]
cc @aehlig

**Comment by fenollp** [comment]
Since the generated file records external repositories' inputs and JSON doesn't have a `set([])` type maybe JSON isn't the right format?

A workaround for now can be to load this file with Python.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
