### ISSUE TITLE
Change execution log proto to differentiate between remote and disk cache hits

### ISSUE THREAD

**Issue by kastiglione** [bazelbuild/bazel#8192]
### Description of the bug _and_ feature request:

The execution log protobuf contains [`remote_cache_hit`](https://github.com/bazelbuild/bazel/blob/8753ecae6af114b227c62e341bdd57f8302e9b6b/src/main/protobuf/spawn.proto#L114-L116), but does not have an equivalent `disk_cache_hit`.

There appears to also be a bug here. @Keith found that `remote_cache_hit` is being set to true for disk cache hits. For the purpose of metrics, these should be split out, as the times will be different.

### Feature requests: what underlying problem are you trying to solve with this feature?

We want to track performance of caching, including cache hit ratios and time to fetch from cache. The metrics would be more precise if the different types of cache hits were kept distinct.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build twice, once to populate the disk cache, once to use the cache and generate an execution log.

1. Populate disk cache: `--disk_cache=some/path --remote_upload_local_results`
2. Produce execution log: `--disk_cache=some/path --experimental_execution_log_file=path/to/execution.log`

Then, inspect the execution log to see that `remote_cache_hit` is true.

### What operating system are you running Bazel on?

macos

### What's the output of `bazel info release`?

0.25.0rc2

### Any other information, logs, or outputs that you want to share?

This relates to the recent work to support using both disk and remote http cache together. See #7512, #8052, and #8141.

**Comment by kastiglione** [comment]
Update: I had myself confused, this is the execution log not the build event log. I've updated the issue accordingly.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
