### ISSUE TITLE
Add support for configure-like repository rules

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#8193]
Hello repository rules experts,

So just in case you are not aware, there is this long standing issue with Bazel's autoconfigured toolchains, where we don't detect changes to the host system. For example, we run a build with Bazel, then we upgrade system installed gcc, which changes include paths, and then we rerun the build with Bazel. Bazel will not notice changes to the gcc and the build will fail with undeclared headers used during compilation.

We have the same problem on macs with xcode detection, and the same problem we'll have with my Q2 OKR re using system installed libraries (which will make this problem much more common).

One thing that prevents me from naively fixing this is that Bazel caches calls to ctx.execute:

```
# repo.bzl
def _impl(ctx):
   print(ctx.execute(["date"]).stdout)
   ctx.file("BUILD", "")

yolo = repository_rule(
    implementation = _impl,
    local = True,
)

# WORKSPACE
load("//:repo.bzl", "yolo")
yolo(
    name = "foo",
)
```

You can call `bazel build @foo//...` many times and you'll get the same date printed out. AFAIU repository rules are only invalidated when:

* when their definition changes
* when an artifact they depend on changes (note this behavior can only be used with files inside the source tree, not for /usr/bin/gcc)
* a declared environment variable changes
* on bazel sync.

If I as a repository rule author could force Bazel to reexecute the `date` command (ideally with the data from previous run of the repository, similar to what --experimental_repository_resolved_file stores), I'd be able to detect system updates. Maybe not 100% reliably, but maybe it would be good enough.

I see a lot of good progress in the repository rules land, and I also chatted with Klaus about this last week. He pointed me to this doc:

https://docs.google.com/document/d/1kVNXcw3nLlfFQRR_87SGOka9DJ8nnawlYHUIK4m3s0I/edit#

Other than that I found this [doc](https://docs.google.com/document/d/1Ju74cmBCfYl8SEZT_tXhRmbi49ZLMzXgoQzzqve-dxI/edit#) about the inception of `cc_configure`.

My humble questions are:

1) Is there a solution to my problem that I'm not aware of?
2) Are there plans to finish the work on configure like repository rules?
3) Possibly unrelated, but was there any progress (investigations, design work) regarding executing repository rules on the remote execution workers (to "configure" execution platform when it's not 'local' one)?

Thank you all!

**Comment by hlopko** [comment]
I chatted with @aehlig and @irengrig and we concluded that there is currently no way to do what I'm asking for. @aehlig also pointed out that always running `gcc -v` might not be the best solution, since that logic will certainly grow more complicated in time, and will have the same destiny as ./configure - being forced to be a manually triggered step. With which I'm fine - if we have a properly documented `bazel reconfigure` command, I think users will learn how to use it properly.

**Comment by hlopko** [comment]
Another idea I got. The logic that detects the toolchain can indeed take too long. But the logic that shows the toolchain needs to be invalidated can execute in much shorter time.

Example - finding the CC compiler, and deciding which features it supports can take long, but maybe checking that already detected CC compiler is the same as the last one can be faster. Of course this means that the repository rule author has to optimize and evaluate tradeoffs what to execute unconditionally.

I'm not sure it's a good idea, just in idea :)

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
