### ISSUE TITLE
don't print <unbound> in error messages

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#8199]
When we print error messages, we sometimes print the full signature of a function, including the type of the arguments and the default value.

In some cases, we print `<unbound>` for the default value (meaning it's an optional argument, but it has no default value). We shouldn't.

**Comment by brandjon** [comment]
I don't think we print those signatures anymore. At least, I don't see it when I call a function with an incorrect number of arguments or bad argument types.
