### ISSUE TITLE
Link to corporate contributor license agreement is broken

### ISSUE THREAD

**Issue by ivucica** [bazelbuild/bazel#820]
In [CONTRIBUTING.md], link to "corporate contributor license agreement" is broken.

[CONTRIBUTING.md]: https://github.com/bazelbuild/bazel/blob/7b93bbec4b356accac9f4421432993bb869b49a9/CONTRIBUTING.md

**Comment by kchodorow** [comment]
Looks like it should link to https://cla.developers.google.com/about/google-corporate, we'll update the docs.  Thanks!
