### ISSUE TITLE
Windows, launcher: cannot run py/sh/java binaries with ".." in argv0

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#8202]
### Description of the problem / feature request:

In workspace "foo", if you build a sh/py/java binary on Windows, you can run it from `bazel-bin\name.exe` from the parent directory using `foo\bazel-bin\name.exe`, but not from a sibling directory using `..\foo\bazel-bin\name.exe`.

### What operating system are you running Bazel on?

windows 10

### What's the output of `bazel info release`?

0.24.1

**Comment by laszlocsomor** [comment]
@meteorcloudy : does this look familiar?

**Comment by meteorcloudy** [comment]
Hmm,, I didn't know about this

**Comment by laszlocsomor** [comment]
Found the bug, will fix and retreat to my shame cube:
https://github.com/bazelbuild/bazel/blob/77b987524ad0988dd0d21cd5e9dcadb897bedd26/src/main/cpp/util/path_windows.cc#L466

(clue: `*result` may start with `..\`)
