### ISSUE TITLE
Update git_repository documentation to reflect new parameters

### ISSUE THREAD

**Issue by kastiglione** [bazelbuild/bazel#8206]
### Description of the problem request:

The documentation for [`git_repository`](https://docs.bazel.build/versions/0.19.1/be/workspace.html#git_repository) mentions the new version as a drop in replacement, but the new version also accepts parameters that the original doesn't, and these parameters are not documented:

* [`shallow_since`](https://github.com/bazelbuild/bazel/blob/5b76c1b5a494fe95725fe461c4fc4f0a995cbfee/tools/build_defs/repo/git.bzl#L142-L151)
* [`branch`](https://github.com/bazelbuild/bazel/blob/5b76c1b5a494fe95725fe461c4fc4f0a995cbfee/tools/build_defs/repo/git.bzl#L158-L163)
* `verbose`
* [`strip_prefix`](https://github.com/bazelbuild/bazel/blob/5b76c1b5a494fe95725fe461c4fc4f0a995cbfee/tools/build_defs/repo/git.bzl#L169-L172)
* [`patches `](https://github.com/bazelbuild/bazel/blob/5b76c1b5a494fe95725fe461c4fc4f0a995cbfee/tools/build_defs/repo/git.bzl#L173-L178)
* [`patch_args`](https://github.com/bazelbuild/bazel/blob/5b76c1b5a494fe95725fe461c4fc4f0a995cbfee/tools/build_defs/repo/git.bzl#L183-L186)
* [`patch_cmds`](https://github.com/bazelbuild/bazel/blob/5b76c1b5a494fe95725fe461c4fc4f0a995cbfee/tools/build_defs/repo/git.bzl#L187-L190)

Is there a plan for how long the docs will show the original version, before switching over to documenting the new version of `git_repository`?

**Comment by aehlig** [comment]
> Is there a plan for how long the docs will show the original version, before switching over to documenting the new version of `git_repository`?

As you can see, the documentation is versioned. The native `git_repository` rule is documented for those versions of bazel that contain it (up to and including 0.22). The Starlark version of [`git_repository`](https://docs.bazel.build/versions/master/repo/git.html) is already documented at master, and the documentation will be part of the versioned documentation for 0.25 and beyond.

**Comment by kastiglione** [comment]
I didn't realize google was taking me to way old docs, thanks!
