### ISSUE TITLE
--disk_cache overrides --noremote_upload_local_results

### ISSUE THREAD

**Issue by JaredNeil** [bazelbuild/bazel#8216]
### Description of the feature request:

I would like to be able to use the `--disk_cache` as a read/write cache, but the remote cache as a read-only cache. I thought `--noremote_upload_local_results` would do this, but it seems that flag is just overridden by the `--disk_cache` option. It seems this is the expected behavior, since in #7512, I see it says:
>On put, Bazel will store items in both the disk and the HTTP cache.

Could this be changed to support this mixed use case?

### What underlying problem are you trying to solve with this feature?

We are still in the process of moving our build to bazel, and not all builds on dev machines are safe to be pushed to the shared remote cache, so we only populate the remote cache from CI builds. Being able to have a local cache is very helpful when switching between dev branches for super fast builds. Our current workaround is to run a remote cache on every machine that acts as a proxy to the real shared cache, but we would like to move away from all of that overhead.

**Comment by buchgr** [comment]
I agree. disk cache should always be read/write and the `remote_upload_local_results` flag should only apply to remote caching.

**Comment by SrodriguezO** [comment]
Hey @ishikhman! Have you had a chance to look any further into this?

**Comment by buchgr** [comment]
@SrodriguezO we love contributions :)

**Comment by SrodriguezO** [comment]
We're happy to help! Just wanted to avoid duplicate efforts, since the issue's assigned. We can start looking into it next week.

**Comment by SrodriguezO** [comment]
We'll still hold off to hear back from @ishikhman though (to avoid duplicate efforts)

**Comment by ishikhman** [comment]
> We'll still hold off to hear back from @ishikhman though (to avoid duplicate efforts)

unfortunately, not yet. That would be really great if you could look into it! Removed myself from the assignment ;)

**Comment by SrodriguezO** [comment]
Silly me.. I just realized this won't actually solve our problem :( 

We're exploring a move to RBE and are hoping to utilize its remote cache, but it isn't compatible with local disk caching in the first place :/

**Comment by buchgr** [comment]
@SrodriguezO it's just not been implemented yet. It should be a straightforward PR. Would also love your contribution :)

**Comment by SrodriguezO** [comment]
@buchgr I dug around a bit and it seems a bit involved. I opened a draft PR to test things out as well as a feature request to formalize the process and to get some input. I'd love your feedback. https://github.com/bazelbuild/bazel/issues/8690

**Comment by keith** [comment]
@buchgr any chance we could mark this as a blocker for 1.0?

**Comment by buchgr** [comment]
I am hopeful that we'll get this fixed before 1.0 (September 2nd). However, I don't think that it qualifies as a blocker. Why do you think so?

**Comment by keith** [comment]
It just seems like this feature is dead in the water until this is fixed

**Comment by alexeagle** [comment]
@meteorcloudy it seems like we're missing the `incompatible-change` tracking issue for flipping the default value of --incompatible_remote_results_ignore_disk to true? Can you create it?

**Comment by meteorcloudy** [comment]
@coeuvre Can you help create the tracking issue for this remote execution flag? https://bazel.build/contribute/breaking-changes

**Comment by coeuvre** [comment]
Created #15148.
