### ISSUE TITLE
Malformed /ac/ url when both http and disk caching enabled 

### ISSUE THREAD

**Issue by cocasema** [bazelbuild/bazel#8218]
### Description of the problem:

When both http and disk cache enabled, action result url is malformed.
It becomes `/cas/ac_HEX` instead of `/ac/HEX`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
.bazelrc:
 build --remote_http_cache=http://127.0.0.1:9090
 build --remote_upload_local_results=true
 build --remote_timeout=5
 build --disk_cache=/cache/bazel/disk

bazel clean
bazel test :all
```

### What operating system are you running Bazel on?

Linux Mint 19.1

### What's the output of `bazel info release`?

release 0.25.0

###  Have you found anything relevant by searching the web?

Nope.

### Any other information, logs, or outputs that you want to share?

I'm using https://github.com/buchgr/bazel-remote as remote caching service.

Build with http remote only:
```
2019/05/02 05:51:29  GET 404      172.20.0.1 /ac/34adacfa4223720ddca3008caf5b97d55af6b8e879fa225e6fe13b3faf981a68
2019/05/02 05:51:32  PUT 200      172.20.0.1 /cas/34adacfa4223720ddca3008caf5b97d55af6b8e879fa225e6fe13b3faf981a68
2019/05/02 05:51:32  PUT 200      172.20.0.1 /ac/34adacfa4223720ddca3008caf5b97d55af6b8e879fa225e6fe13b3faf981a68
```

Build with http remote + disk cache:
```
2019/05/02 05:59:14  GET 400      172.20.0.1 /cas/ac_34adacfa4223720ddca3008caf5b97d55af6b8e879fa225e6fe13b3faf981a68
2019/05/02 05:59:16  PUT 200      172.20.0.1 /cas/34adacfa4223720ddca3008caf5b97d55af6b8e879fa225e6fe13b3faf981a68
2019/05/02 05:59:16  PUT 400      172.20.0.1 /cas/ac_34adacfa4223720ddca3008caf5b97d55af6b8e879fa225e6fe13b3faf981a68
```
```
WARNING: Writing to Remote Cache:
400 Bad Request
resource name must be a SHA256 hash in hex. got '/cas/ac_34adacfa4223720ddca3008caf5b97d55af6b8e879fa225e6fe13b3faf981a68'

```

**Comment by buchgr** [comment]
This is currently being fixed by https://github.com/bazelbuild/bazel/pull/8141

**Comment by cocasema** [comment]
Thanks! I somehow missed that issue...
