### ISSUE TITLE
minimum_required_bazel_version WORKSPACE rule?

### ISSUE THREAD

**Issue by jendap** [bazelbuild/bazel#822]
Can we, please, add something like 'bazel(minimum_required_version="0.1.4")' to WORKSPACE (or BUILD) file? Most build systems have that feature. For example maven has <prerequisites><maven>3.0.0</maven></prerequisites>.

If the requirement is not met it should print a _readable_ message like "You need bazel 0.1.4 or newer to build this, please download and install it from http://..."

Rationale: The breaking change in tensorflow BUILD files output very cryptic message. There is no change one could figure out he should upgrade bazel from current error message.

**Comment by damienmg** [comment]
Yes that's something we plan to do. Might make sense to do it sooner now. @kchodorow and @jhfield, we discussed that earlier about skylark extension.

**Comment by jendap** [comment]
Ping. Can we do this please? We are going to bump the version of bazel in tensorflow again tomorrow. It will create a lot of issues, questions, confusion etc. if we do not have this.

**Comment by jendap** [comment]
@vrv @martinwicke FYI

**Comment by martinwicke** [comment]
Dupe of #1014 (actually, of course, it's the other way around, but #1014 is P1, so it should stay :) )

**Comment by jendap** [comment]
You have already create another one? Ok, I'm closing this one.
