### ISSUE TITLE
not actionable notice: rule x indicated that a canonical reproducible form can be obtained ...

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/bazel#8222]
### Description of the problem / feature request:

Recently I get a lot of output like below in my builds
```
DEBUG: Rule 'org_golang_x_tools' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "11629171a39a1cb4d426760005be6f7cb9b4182e4cb2756b7f1c5c2b6ae869fe"
DEBUG: Rule 'org_golang_x_sys' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1547471016 +0000"
DEBUG: Rule 'org_golang_x_net' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1547150550 +0000"
```

now sadly those are all inherited targets (from WORKSPACE), at least a git grep "org_golang_x_sys" does not show anything. It would be great to only show messages about targets that the user *can* fix.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See e.g. https://buildkite.com/bazel/bazel-at-release-plus-incompatible-flags/builds/121#5df6012a-4031-4ee1-bc8c-52ab6233473f

### What operating system are you running Bazel on?

linux

### What's the output of `bazel info release`?

bazel version
Build label: 0.25.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed May 1 21:45:01 2019 (1556747101)
Build timestamp: 1556747101
Build timestamp as int: 1556747101

**Comment by dslomov** [comment]
@aehlig wdyt? Maybe not show this for repos originating from macros outside of main workspace?

**Comment by keith** [comment]
FWIW there are 2 actions you can take for these:

- fix it upstream for everyone
- lock the dep in your own WORKSPACE

**Comment by Globegitter** [comment]
Yep agreed with @keith, this has helped me to improve the fetching from upstream rules so I would prefer to keep the error messages as is.

**Comment by ensonic** [comment]
I totally agree that fixing it upstream would be nice, but for that the error should contain more information to make it an easy thing for me. Right now it is not straight forward to locate where it is coming from. If bazel know, please print full context.

**Comment by aehlig** [comment]
>  Right now it is not straight forward to locate where it is coming from. If bazel know, please print full context.

Bazel does know where the rules are defined, but there is the request to not print too much information; so currently, that information is only recorded in the `--experimental_repository_resolved_file`. If there is consensus that we should print that information on the console as well, we could easily do it, the same way as we currently do it for repositories involved in failures.

**Comment by davido** [comment]
I'm seeing this message at Bazel@HEAD:

```
DEBUG: Rule 'remote_java_tools_darwin' indicated that a canonical reproducible form can be obtained by dropping arguments ["generator_name", "generator_function"]
DEBUG: Repository remote_java_tools_darwin instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/bazel_tools/tools/build_defs/repo/http.bzl:336:16: in <toplevel>
DEBUG: Rule 'remote_java_tools_windows' indicated that a canonical reproducible form can be obtained by dropping arguments ["generator_name", "generator_function"]
DEBUG: Repository remote_java_tools_windows instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/bazel_tools/tools/build_defs/repo/http.bzl:336:16: in <toplevel>
```

What can I do to fix it (except patching Bazel to silence the warning in
src/main/java/com/google/devtools/build/lib/bazel/repository/RepositoryResolvedEvent.java)?

**Comment by limdor** [comment]
Same here, here the instantiation callstack
```
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by dropping arguments ["generator_name", "generator_function"]
DEBUG: Repository rules_cc instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:131:1: in <toplevel>
  C:/users/appveyor/_bazel_appveyor/4y3zg7it/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:9: in maybe
Repository rule http_archive defined at:
  C:/users/appveyor/_bazel_appveyor/4y3zg7it/external/bazel_tools/tools/build_defs/repo/http.bzl:339:16: in <toplevel>
Analyzing: 21 targets (16 packages loaded, 0 targets configured)
```

**Comment by davido** [comment]
I filed this #11040 and bisected the problem.

**Comment by ryohji** [comment]
I appreciate if anyone can confirm that what I'm doing is right or not:

According to the [Google Test tutorial](https://google.github.io/googletest/quickstart-bazel.html), it said to prepare `WORKSPACE`:
```txt
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "com_google_googletest",
  urls = ["https://github.com/google/googletest/archive/609281088cfefc76f9d0ce82e1ff6c30cc3591e5.zip"],
  strip_prefix = "googletest-609281088cfefc76f9d0ce82e1ff6c30cc3591e5",
)
```

This produces:
```txt
INFO: SHA256 (https://github.com/google/googletest/archive/609281088cfefc76f9d0ce82e1ff6c30cc3591e5.zip) = 5cf189eb6847b4f8fc603a3ffff3b0771c08eec7dd4bd961bfd45477dd13eb73       
DEBUG: Rule 'com_google_googletest' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "5cf189eb6847b4f8fc603a3ffff3b0771c08eec7dd4bd961bfd45477dd13eb73"
DEBUG: Repository com_google_googletest instantiated at:
  C:/users/XXXX/WORKSPACE:3:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/XXXX/mrkfkorq/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
```

According to `DEBUG` message, I add `sha256` property in the `WORKSPACE` like:
```txt
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "com_google_googletest",
  urls = ["https://github.com/google/googletest/archive/609281088cfefc76f9d0ce82e1ff6c30cc3591e5.zip"],
  strip_prefix = "googletest-609281088cfefc76f9d0ce82e1ff6c30cc3591e5",
  sha256 = "5cf189eb6847b4f8fc603a3ffff3b0771c08eec7dd4bd961bfd45477dd13eb73",
)
```

To do this, "a canonical reproducible form can be obtained by modifying arguments sha256 = ..." messages dissapeared.

I'm also appreciated if I could have the pointer to clear this problem's cause and how-to fix in the Bazel manual.

**Comment by ensonic** [comment]
@ryohji that's correct. Adding the sha256 will ensure that you get the same version each tiem the build runs.

**Comment by TypeDefinition** [comment]
Hi, I know that it has been 3 years since this thread originated. But this is the only result on Google, and I still don't know what the message means.

I see some suggestions about fixing something upstream and something about sha256. But I don't understand what these are solving.

What _does the message mean_?

**Comment by madnik** [comment]
https://github.com/bazelbuild/bazel/blob/b1be758019487d4b5dd93d46e69e216f5a7b8457/tools/build_defs/repo/git_worker.bzl#L58

The current implementation fall back to `shallow = "--depth=1"` if shallow_since is not defined. 
This warning becomes unnecessary noise if I only define commit intentionally.
