### ISSUE TITLE
--remote_default_host_platform_properties should invalidate actions

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#8224]
If the contents of this flag change then skyframe actions should also be invalidated.

cc @katre

**Comment by katre** [comment]
This makes sense, and definitely needs to happen. Thanks for catching it.

**Comment by ishikhman** [comment]
@buchgr did you mean `--remote_default_platform_properties` flag?

**Comment by buchgr** [comment]
Yes!
