### ISSUE TITLE
Archiving artifacts fails

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#823]
See http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.7,PLATFORM_NAME=ubuntu_15.10-x86_64/326/console:

```
Archiving artifacts
WARN: No artifacts found that match the file pattern "output/ci/**". Configuration error?
WARN: ‘output/ci/**’ doesn’t match anything, but ‘**’ does. Perhaps that’s what you mean?
```

I don't think it's actually causing any issues, so marking P3.

**Comment by damienmg** [comment]
That's working as intended. There's no way that I know to remove those warnings.
