### ISSUE TITLE
//src/test/shell/bazel/android/... is incompatible with RBE

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#8235]
Sample error:

```
Exception in thread "main" com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	bazel-out/host/bin/external/androidsdk/aapt_binary package -f --no-crunch --no-version-vectors -I external/androidsdk/platforms/android-28/android.jar -M /tmp/resource_validator_tmp12788981107769083666/manifest-aapt-dummy/AndroidManifest.xml -m -J /tmp/resource_validator_tmp12788981107769083666/generated_resources --output-text-symbols /tmp/resource_validator_tmp12788981107769083666/generated_resources -F bazel-out/android-armeabi-v7a-fastbuild/bin/java/bazel/aar_files/library.ap_ --debug-mode --non-constant-id -0 apk
Error Code:
	127
Output:
	error parsing linebazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/androidsdk/build-tools/28.0.3/aapt: error while loading shared libraries: libc++.so: cannot open shared object file: No such file or directory
	at com.google.devtools.build.android.AndroidResourceProcessor.runAapt(AndroidResourceProcessor.java:422)
	at com.google.devtools.build.android.AndroidResourceValidatorAction.main(AndroidResourceValidatorAction.java:148)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$2.call(ResourceProcessorBusyBox.java:72)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:240)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:203)
```

Key problem: `	error parsing linebazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/androidsdk/build-tools/28.0.3/aapt: error while loading shared libraries: libc++.so: cannot open shared object file: No such file or directory`

It looks the dynamically linked libc++.so dependency of aapt/aapt2 at `sdk/build-tools/<version>/lib64/libc++.so` cannot be found when executing Android actions remotely through a Bazel-in-Bazel `sh_test`. This suggests some kind of issue with the hermeticity of `@androidsdk//:aapt_binary` and `@androidsdk//:aapt2_binary`.

Regular Android builds do work with RBE, however.

cc @buchgr 

trunk issue: https://github.com/bazelbuild/bazel/issues/8033

**Comment by buchgr** [comment]
Related https://github.com/bazelbuild/bazel/issues/4663

**Comment by buchgr** [comment]
We have tagged the android shell tests as "no-remote" for now.

**Comment by tjgq** [comment]
This issue was fixed by https://github.com/bazelbuild/bazel/pull/17826 but we need to wait until it makes it into a Bazel release before we can reenable the tests (except android_ndk_integration_test, which requires additional work to address https://github.com/bazelbuild/bazel/issues/17784).

**Comment by meteorcloudy** [comment]
@tjgq Can we remove `no-remote` for those tests now? https://github.com/bazelbuild/bazel/commit/a9fb6d39f52969bb19ecddba404d0041af310c70

**Comment by tjgq** [comment]
I don't know, but we could give it a try and see if we're still hitting the same error.
