### ISSUE TITLE
`cc_toolchain`  rules in `@bazel_tools//tools/cpp` contain deprecated attributes

### ISSUE THREAD

**Issue by scottmin0r** [bazelbuild/bazel#8236]
### Description of the problem / feature request:

Error when building with 0.25.0:

```
ERROR: /usr/local/google/home/<REDACTED>/.cache/bazel/_bazel_<REDACTED>/86021668b1f881516e569ba9a9189b20/external/bazel_tools/tools/cpp/BUILD:229:1: in cc_toolchain rule @bazel_tools//tools/cpp:cc-compiler-darwin: attributes 'cpu' and 'compiler' have been deprecated, please remove them. See https://github.com/bazelbuild/bazel/issues/7075 for details.
```

It looks like the rules in https://github.com/bazelbuild/bazel/blob/0.25.0/tools/cpp/BUILD haven't been updated to handle the flip of `incompatible_remove_cpu_and_compiler_attributes_from_cc_toolchain`?

### What operating system are you running Bazel on?

Linux (Debian variant)

### What's the output of `bazel info release`?

`release 0.25.0`

**Comment by luorixiangyang** [comment]
I also encounter this issue when use bazel0.25.0 to compiler tensorflow1.14 on windows10. i don't know how to remove attributes "cpu" and "compiler" mention by log.

At the same time, i also try download bazel code recompiler local version and still can't solve this issue.
