### ISSUE TITLE
java_library outputs WARNING for legitimate case

### ISSUE THREAD

**Issue by natansil** [bazelbuild/bazel#8238]
### Description of the problem / feature request:

In case where there are several java packages that have a cyclic dependency between them (each with source files), if there are bazel packages for each one with only a `filegroup` target,
and the parent package has a `java_library` that has all these filegroups as `srcs`, then the there is a warning that requests `not to import these source files directly`:

For example (the full repro can be found [here](https://github.com/natansil/java_lib_file_group_repro)), let's assume there are the following java packages
`iterator`(parent package), `bst`, `list`
let's mark a dependency with `->`:
`Iterator` -> `bst`
`Iterator` -> `list`
`list` -> `Iterator`
`bst` -> `Iterator`

so the automatic migrator, [exodus](https://github.com/wix-incubator/exodus/) creates a `java_library` target for `iterator` called `agg=._bst_list` with 
 ```
java_library(
    name = "agg=._bst_list",
    srcs = [
        "//iterator/src/main/java/com/iluwatar/iterator/bst:sources" , 
        "//iterator/src/main/java/com/iluwatar/iterator/list:sources" , 
        "//iterator/src/main/java/com/iluwatar/iterator:sources"
    ],
...
```

building `agg=._bst_list` gives this warning (among other similar ones):
```
WARNING: /Users/natans/java_lib_repro/iterator/src/main/java/com/iluwatar/iterator/BUILD.bazel:6:12: 
in srcs attribute of java_library rule //iterator/src/main/java/com/iluwatar/iterator:agg=._bst_list: 
please do not import '//iterator/src/main/java/com/iluwatar/iterator/bst:BstIterator.java' directly. 
You should either move the file to this package or depend on an appropriate rule there
```
You can run `bazel build //...` on [this repro ](https://github.com/natansil/java_lib_file_group_repro) to get a better sense.

This `filegroup` pattern allows [exodus](https://github.com/wix-incubator/exodus/) (that attempts to create java package level targets) to identify cycles and to create composite targets for them, while keeping other targets in the same "module" at the package level.

**So I think this warning should be removed,  or at least have an option to configure muting it.**
In order to allow Exodus to perform this very helpful optimisation.

### What operating system are you running Bazel on?

MacOS

### What's the output of `bazel info release`?

release 0.24.1

CC: @lberki @iirina 
Also @ittaiz

**Comment by natansil** [comment]
Can someone please take a look at this?

**Comment by iirina** [comment]
Taking a look now.

**Comment by iirina** [comment]
I'm trying to understand why `exodus` tries to create the sub-packages (in this case `bst` and `list`). Are there advantages over defining the `filegroup` tagets in the `iterator` package?

**Comment by natansil** [comment]
Thank you @iirina for your response!

Your question is exactly what I asked @ittaiz, and this was his reply:
"it (defining the file groups in the parent package - N.S.) works on some use-cases. We started like this but moved to our current solution because globs can’t pass package boundary in bazel.
This means that if you have:
A
  B
    C
And A+C are a cycle and B is it’s own thing then your solution doesn’t work (the agg=a+c rule is broken)"

**Comment by iirina** [comment]
In your A B C example, what is the directory structure? Are all 3 directories top level? Or B and C are under A?

**Comment by natansil** [comment]
B and C are under A

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
