### ISSUE TITLE
genrule output doesn't exist in bazel-bin with experimental_remote_download_outputs=minimal

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#8244]
### Description of the problem / feature request:

When using `--experimental_remote_download_outputs=minimal` and explicitly building a genrule target, the output files of that genrule are not downloaded to bazel-bin when you get a remote cache hit.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In [this sample project](https://github.com/bazelbuild/bazel/files/3149065/sampleworkspace.zip): replace the placeholder cache in `.bazelrc` with a cache you have access to. Run `./repro.sh`

From scratch:

Create a simple genrule:

```python
genrule(
    name = "example",
    srcs = ["WORKSPACE"],
    outs = ["output.txt"],
    cmd = "echo hi > $@",
)
```

Build once to push it to a remote cache:

```
bazel build example --remote_http_cache=https://CACHE_URL --experimental_inmemory_dotd_files --experimental_inmemory_jdeps_files --experimental_remote_download_outputs=minimal
```

Note the output exists in `bazel-bin/output.txt`

Build it again, where this time it should fetch it:

```
bazel clean
bazel build example --remote_http_cache=https://CACHE_URL --experimental_inmemory_dotd_files --experimental_inmemory_jdeps_files --experimental_remote_download_outputs=minimal
```

Verify it builds from the cache, and note no file exists at `bazel-bin/output.txt`

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 0.25.0

###  Have you found anything relevant by searching the web?

Maybe this is solved by https://github.com/bazelbuild/bazel/pull/7984 ?

**Comment by buchgr** [comment]
@keith yep it's indeed solved by #7984. I ll post a blog post detailing the new feature later today.
