### ISSUE TITLE
Allow passing extra HTTP headers to remote cache

### ISSUE THREAD

**Issue by ob** [bazelbuild/bazel#8245]
It's currently not possible to pass extra HTTP headers to the remote cache. I would like to be able to do something like this:

```
bazel build --remote_http_cache=$SOME_URL --remote_http_header="Build-Id: some-id" --remote_http_header="Product-Name: Some-Name"
```

The idea is to allow for custom logic in the remote http cache to keep metrics about cache usage on a per-product or per-build basis.

**Comment by buchgr** [comment]
SGTM. It seems like a good idea to also support this for gRPC as it's HTTP/2 after all.

I think I'd prefer a format like `--remote_header=Header=Value`.

**Comment by simon0191** [comment]
@ob are you planning to add support for GRPC headers?

**Comment by ob** [comment]
I'm not sure how to do that. I'm not familiar with that section of the code. I'll take a look but if you have any pointers on what would need to be done I'd appreciate it.

**Comment by excitoon** [comment]
@ob I would rather add "headers-adder" to the pipeline. That will be pretty clean solution.

**Comment by ob** [comment]
I believe this issue is fixed.
