### ISSUE TITLE
Dependencies to shared objects in deps are ignored without warning

### ISSUE THREAD

**Issue by burkpojken** [bazelbuild/bazel#8247]
### Description of the problem / feature request:
It looks like the behaviour has changed for dependencies to shared objects.
Previously you got an error if you had a dependency to a shared object in "deps" (the shared object being created with a cc_binary() rule)
The error looked like this
"in deps attribute of cc_library rule //:t2: cc_binary rule '//:libtso.so' is misplaced here (expected cc_inc_library, cc_library, objc_library, experimental_objc_library or cc_proto_library)."

We now use bazel 0.24.1 and there is no such warning.
It looks like if you have the dependency in deps it is not linked in, it is just ignored, and you get "undefined reference" if you actually needed something from the shared object. If you have it in srcs it is linked in like before.

Is this new behaviour explained anywhere?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal Example 
cc_binary(
    name = "test",
    deps = [":t3"],
)

cc_library(
    name = "t3",
    srcs = ["t3.c"],
    deps = [
        ":t2",
    ],
)

cc_library(
    name = "t2",
    srcs = [
        "t2.c",
        # ":libtso.so",  Works 
    ],
    deps = [
        # ":libtso.so",  Used to give a warning, now it is just ignored
    ],
)

cc_binary(
    name = "libtso.so",
    linkshared = 1,
    deps = [":t"],
)

cc_library(
    name = "t",
    srcs = ["t.c"],
    alwayslink = 1,
)
### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

0.24.1

###  Have you found anything relevant by searching the web?
I asked about this in https://groups.google.com/forum/#!topic/bazel-discuss/WCzO2gv68nw
But got no answer

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
