### ISSUE TITLE
Remote Builds without the Bytes should work with BES

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#8249]
Split out of #6862

When using the build event service (BES) together with remote caching / execution URIs to files are automatically translated to remote URIs pointing to the remote cache. This rewriting is disabled when the --experimental_remote_download_outputs flag is set.

**Comment by jjardon** [comment]
Hi @buchgr , reading your comment at https://github.com/bazelbuild/bazel/issues/6862#issuecomment-504731010 ;  does that mean this can be closed now?

**Comment by buchgr** [comment]
Yep! Thanks!

**Comment by Yannic** [comment]
https://blog.bazel.build/2019/05/07/builds-without-bytes.html#local-file-uploads-and-uri-rewriting-in-the-build-event-service still mentions this as a limitation. Should the blog post be updated?
