### ISSUE TITLE
Allow "malloc" attribute of cc_xxx rules to accept any target

### ISSUE THREAD

**Issue by irengrig** [bazelbuild/bazel#8252]
Currently it asserts passed targets to be cc_library.
Example to test the current behavior: https://github.com/bazelbuild/rules_foreign_cc/tree/master/examples/use_malloc

**Comment by hcoona** [comment]
any progress on this issue?

**Comment by hcoona** [comment]
ping again :'(

**Comment by oquenchil** [comment]
The fix is to replace this line:
https://cs.opensource.google/bazel/bazel/+/master:src/main/starlark/builtins_bzl/common/cc/cc_binary_attrs.bzl;drc=db36147bc66109cc2f34bcdb5bb8829182ef0346;l=65

with `providers = [CcInfo]`

A PR is welcome.

**Comment by hcoona** [comment]
@oquenchil could you help to review it at your convenience?
