### ISSUE TITLE
Improve readability of error messages in py[2|3]wrapper.sh

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#8253]
In particular, in the logs of [this](https://travis-ci.org/bazelbuild/rules_docker/builds/529485481?utm_source=github_status&utm_medium=notification) build, the output included:

> Tagging fe2161629fe8514d05580240d088af2e265123bf13b47a68bcd0c4f1b4a7a04a as bazel/testdata/test:py_image_using_layers
Error: The default python toolchain (@bazel_tools//tools/python:autodetecting_toolchain) was unable to locate a suitable Python interpreter on the target platform at execution time. Please register an appropriate Python toolchain. See the documentation for py_runtime_pair here:
https://github.com/bazelbuild/bazel/blob/master/tools/python/toolchain.bzl.
Failure reason: Cannot locate 'python3' or 'python' on the target platform's PATH, which is:
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin contains Successfully imported six 1.11.0

The failure is because `which` was not found on `PATH`, but it's easy to miss this and think `python` and `python3` weren't found. Would be nice to delimit all error output from the wrapper with a common header/footer. (Also note the missing newline after printing out the content of `PATH`.)

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
