### ISSUE TITLE
Bazel 0.25 breaks upb build: Output artifact '_objs/upb_lib/descriptor.upb.pic.o' not under package directory 'external/com_google_protobuf' for target '@com_google_protobuf//:descriptor_proto'

### ISSUE THREAD

**Issue by haberman** [bazelbuild/bazel#8254]
### Description of the problem / feature request:

Bazel 0.25 breaks the build of https://github.com/protocolbuffers/upb.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

$ wget https://github.com/bazelbuild/bazel/releases/download/0.25.1/bazel-0.25.1-linux-x86_64
$ chmod a+x bazel-0.25.1-linux-x86_64
$ git clone --single-branch --branch bazel25 https://github.com/haberman/upb.git
$ cd upb
$ ../bazel-0.25.1-linux-x86_64 build :descriptor_upbproto

I get the following output/error:

```
ERROR: /usr/local/google/home/haberman/.cache/bazel/_bazel_haberman/3d6dddcf72cff0e2141218f5c0401c8f/external/com_google_protobuf/BUILD:284:2: in //:build_defs.bzl%_upb_proto_library_aspect aspect on proto_library rule @com_google_protobuf//:descriptor_proto:
Traceback (most recent call last):
        File "/usr/local/google/home/haberman/.cache/bazel/_bazel_haberman/3d6dddcf72cff0e2141218f5c0401c8f/external/com_google_protobuf/BUILD", line 284                          
                //:build_defs.bzl%_upb_proto_library_aspect(...)
        File "/tmp/foo/upb/build_defs.bzl", line 357, in _upb_proto_aspect_impl
                cc_library_func(ctx = ctx, hdrs = files.hdrs, srcs =..., ...]))
        File "/tmp/foo/upb/build_defs.bzl", line 288, in cc_library_func
                cc_common.compile(actions = ctx.actions, feature_con..., <5 more arguments>)                                                                                       
Output artifact '_objs/upb_lib/descriptor.upb.pic.o' not under package directory 'external/com_google_protobuf' for target '@com_google_protobuf//:descriptor_proto'               
ERROR: Analysis of target '//:descriptor_upbproto' failed; build aborted: Analysis of target '@com_google_protobuf//:descriptor_proto' failed; build aborted    
```

### What operating system are you running Bazel on?

Linux.

### What's the output of `bazel info release`?

release 0.25.1

### Any other information, logs, or outputs that you want to share?

This seems related to my StackOverflow question where I am wondering how to properly write rules/aspects that operate on external repositories: https://stackoverflow.com/questions/55796252/how-to-write-bazel-rules-that-work-with-external-repositories

I am very receptive to hearing about how to write my rule/aspect to make it simpler and avoid this error.

**Comment by haberman** [comment]
Any idea @hlopko @oquenchil ?

**Comment by oquenchil** [comment]
The problem is that [here](https://github.com/bazelbuild/bazel/blob/ce62e55a23521bea2ba96c46809757994dec4ecc/src/main/java/com/google/devtools/build/lib/rules/cpp/CcModule.java#L1445) we are calling getPackageName() instead of getPackageIdentifier(), so the repo section of the package got dropped. This problems exists at head. I will send a fix. I can't think of a workaround at the moment. 

0.26 is a week away, would it be possible for you to wait until then?

**Comment by aehlig** [comment]
> [...] This problems exists at head. I will send a fix. I can't think of a workaround at the moment.
> 
> 0.26 is a week away, would it be possible for you to wait until then?

Note that the baseline for 0.26 (#7499) is already determined. Are your requesting a cherry-pick? That would require a rgression with respect to 0.25. Is a patch-release needed for 0.25 (#7498)?

**Comment by oquenchil** [comment]
I have sent the fix for review. It would need to be cherry-picked into 0.26. I don't know if 0.25 needs to be patched. I would imagine that this depends on how many people this affects. Joshua if I remember correctly from our chat conversations you were still playing around experimenting with this API. Did this make it into any of your releases and does it affect a lot of users?

**Comment by haberman** [comment]
> Did this make it into any of your releases and does it affect a lot of users?

gRPC is an important customer of mine who is more or less blocked until I can get this working. That's why I have been spending so much effort on it. I found a way to get it working finally in 0.24.1 but then 0.25 regressed me.

If 0.26 is a week away, I am ok waiting for that. But I don't want to wait much longer than that.

**Comment by oquenchil** [comment]
Thanks Joshua. The fix https://github.com/bazelbuild/bazel/commit/942f7cf6a0da0a4ecc804615424f039e50963933 has been cherrypicked already.

**Comment by dkelmer** [comment]
@haberman  I'm also creating a patch release with the fix for this so you'll be able to use 0.25.2 later today

**Comment by haberman** [comment]
Thanks all for the quick resolution!

**Comment by oquenchil** [comment]
Is everything working correctly Joshua?

**Comment by haberman** [comment]
@oquenchil yes I have everything working now, thanks! :)
