### ISSUE TITLE
rule.toolchains should warn if anything except toolchain_type targets is used

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#8259]
A user attempted to add a rule like this:
```
new_rule = rule(
  implementation = _impl,
  attrs = {...},
  toolchains = ["@bazel_tools//tools/cpp:cc_tools"],
)
```

This is incorrect but not clear because of the difference between how `genrule` and `rule` use the `toolchains` attribute.

Currently, the error this gives is something like:
`While resolving toolchains for target <snip>: no matching toolchains found for types //:cc_flags`. It should instead be made clear that the target rule type is invalid (since it should be a target created from `toolchain_type`.)

**Comment by katre** [comment]
Leaving this open in case anyone wants to pick it up.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
