### ISSUE TITLE
should debian package dependency on openjdk-8-source

### ISSUE THREAD

**Issue by jendap** [bazelbuild/bazel#826]
It makes (some) docker images bigger. But not a big deal.

Would it be enough to have it as "Suggests:" instead of "Depends:" in the control file?

**Comment by damienmg** [comment]
We removed that dependency at HEAD.

**Comment by damienmg** [comment]
see d5b2d25c33500d1aa418566dd74758b8171ddef2

**Comment by jendap** [comment]
Thank you!

BTW: I see. You did it 15 days ago. That explain why I could not send you PR. I could not find it in the source tree any more :-)
