### ISSUE TITLE
Easy xx_binary deployment with runfiles

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#8263]
### Description of the problem / feature request:

Find a way to easily deploy Bazel-built binaries with runfiles.

### Feature requests: what underlying problem are you trying to solve with this feature?

Making Bazel-built binaries easily portable across computers.

There are various options to do this.

On Linux, macOS, and platforms that support symlinks and building runfiles trees, we could package the runfiles tree (with dereferenced symlinks of course) with the binary.

On Windows, we could do the same based on the runfiles_manifest.

In every case we should be smart and exclude files from local repositories of tools, e.g. `local_jdk`, but include things like `librunfiles.jar` if a java rule depends on `@bazel_tools//tools/java/runfiles`.

We could also think about making it easy to adapt paths in the runfiles_manifest to the local environment.

### What operating system are you running Bazel on?

Windows 10, but this affects every platform

### What's the output of `bazel info release`?

0.25.1

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
