### ISSUE TITLE
Custom protobuf plugins with starlark rules

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#8272]
Currently [rules_swift](https://github.com/bazelbuild/rules_swift/) provides a [`swift_proto_library`](https://github.com/bazelbuild/rules_swift/blob/master/swift/internal/swift_proto_library.bzl) target that's analogous to `cc_proto_library`. Currently the implementation of this rule bakes in the plugin being used to generate the protos. For our use case we'd like to override the plugin with our own custom implementation. On the cc / java side it looks like this is done by defining a custom [`proto_lang_toolchain`](https://docs.bazel.build/versions/master/be/protocol-buffer.html#proto_lang_toolchain) and passing the appropriate `--proto_toolchain_for_*` flag.

How should this work for non java / cc rules, like the case of rules_swift? Should the rules be responsible for allowing you to override the desired fields, or should this come from bazel core somehow?

**Comment by keith** [comment]
I'm happy to post there instead if folks think that's the right place

**Comment by hlopko** [comment]
I presume it's the on the individual rules side, e.g. [rules_go](https://github.com/bazelbuild/rules_go/blob/master/proto/BUILD.bazel#L21) implement this on their side as well. Let me know if I'm missing smth. Thanks!
