### ISSUE TITLE
Starlark, ctx.actions.run: support capturing stdout and stderr

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#8275]
### Description of the problem / feature request:

I want to specify where to redirect an action's stdout and stderr in Starlark, without having to run the action with `ctx.actions.run_shell` and `1>file.txt`. Instead I want to write:
```
stdout_file = ctx.actions.declare_file("tool.out")
ctx.actions.run(
    ...
    executable = [ctx.executables.tool],
    stdout = stdout_file,
    stderr = redirect,
)
```

This would let me run the action without Bash.

### Feature requests: what underlying problem are you trying to solve with this feature?

https://github.com/bazelbuild/bazel-skylib/issues/149

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

0.25.0

**Comment by laurentlb** [comment]
Duplicate with #5511
