### ISSUE TITLE
Python data dependencies should not require/provide .zip files on Windows

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#8292]
I believe if you have `py_binary` A with a data dependency on `py_binary` B, B's zip file will be included inside A's. That is, we get a zipfile size that is quadratic in the length of the chain of data dependencies.

This is probably avoidable by not propagating the zip file to transitive reverse dependencies, and by having the stub script detect whether it is running from an already extracted runfiles tree.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
