### ISSUE TITLE
Improve error message in case the user forgot to specify managed directory for the repository

### ISSUE THREAD

**Issue by irengrig** [bazelbuild/bazel#8293]
Currently, if one forgets to mention the managed directory in the workspace function, the following error is shown to user:

no such package '@repo//package': BUILD file not found on package path and referenced by <target>

This message can be improved as we can "guess" that the package missing under the external repository is probably in generated code, and therefore it should be marked as managed directory

Context: managed directories: https://github.com/bazelbuild/bazel/issues/8201

**Comment by dslomov** [comment]
Maybe the  repository rule that requires managed directories should check for their existence and error out then?

**Comment by irengrig** [comment]
The problem is that in the situation, when the user forgot to specify managed directories, the repository rule is not called, so it can not do anything. (And managed directories settings are not exposed to Starlark).

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
