### ISSUE TITLE
Java builds fail on CentOS 6, ijar GLIBC_2.14 not found

### ISSUE THREAD

**Issue by Preston4tw** [bazelbuild/bazel#8294]
### Description of the problem:

I upgraded Bazel from 0.24.1 to 0.25.1 and Java builds began failing.

It looks like the issue is that ijar is being built on a system with a toolchain more recent than CentOS 6 and ijar is being pulled down as a binary rather than being built. ijar is throwing a runtime error.

```
scl enable devtoolset-8 -- bazel build //...
...
external/remote_java_tools_linux/java_tools/ijar/ijar: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by external/remote_java_tools_linux/java_tools/ijar/ijar)
external/remote_java_tools_linux/java_tools/ijar/ijar: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by external/remote_java_tools_linux/java_tools/ijar/ijar)
external/remote_java_tools_linux/java_tools/ijar/ijar: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by external/remote_java_tools_linux/java_tools/ijar/ijar)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
docker run -it --rm centos:6

cd /root && mkdir bazel && cd bazel && curl -LO https://github.com/bazelbuild/bazel/releases/download/0.25.1/bazel-0.25.1-dist.zip
yum -y install centos-release-scl
yum -y install devtoolset-8 java-1.8.0-openjdk-devel.x86_64
unzip bazel-0.25.1-dist.zip
scl enable devtoolset-8 -- ./compile.sh
cp -v output/bazel /usr/bin/

mkdir -p /root/jtest && cd /root/jtest

cat > BUILD << EOF
java_binary(
  name = "Test",
  srcs = ["Test.java"],
  main_class = "Test",
  deps = [
    "@com_google_guava_guava//jar",
  ],
)
EOF

cat > WORKSPACE << EOF
maven_jar(
  name = "com_google_guava_guava",
  artifact = "com.google.guava:guava:20.0",
)
EOF

cat > Test.java << EOF
public class Test {
        public static void main(String[] args) {
                System.out.println("Hello World");
        }
}
EOF

scl enable devtoolset-8 -- bazel build //...
```

Output:
```
[root@421fd07b2bf2 jtest]# scl enable devtoolset-8 -- bazel build //...
INFO: Analyzed target //:Test (18 packages loaded, 462 targets configured).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/f3a7123f4b1ce348c38f7ee792cc5945/external/com_google_guava_guava/jar/BUILD.bazel:2:1: Extracting interface @com_google_guava_guava//jar:jar failed (Exit 1) ijar failed: error executing command external/remote_java_tools_linux/java_tools/ijar/ijar external/com_google_guava_guava/jar/guava-20.0.jar ... (remaining 3 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/remote_java_tools_linux/java_tools/ijar/ijar: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by external/remote_java_tools_linux/java_tools/ijar/ijar)
external/remote_java_tools_linux/java_tools/ijar/ijar: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by external/remote_java_tools_linux/java_tools/ijar/ijar)
external/remote_java_tools_linux/java_tools/ijar/ijar: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by external/remote_java_tools_linux/java_tools/ijar/ijar)
Target //:Test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.536s, Critical Path: 0.08s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

### What operating system are you running Bazel on?

CentOS 6

### What's the output of `bazel info release`?

release 0.25.1- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

`scl enable devtoolset-8 -- ./compile.sh` from https://github.com/bazelbuild/bazel/releases/download/0.25.1/bazel-0.25.1-dist.zip on CentOS 6

###  Have you found anything relevant by searching the web?

There are some other GitHub issues with GLIBC references, but none seemed relevant.

**Comment by beasleyr-vmw** [comment]
Just ran into this while evaluating Bazel 0.26.0 rc10.

For those interested in building the tools yourself against your own libc baseline, according to https://github.com/bazelbuild/java_tools/issues/6, the current java_tools release was cut from https://github.com/bazelbuild/bazel/commit/b0317496ce596a36eea8f95d3af650a74d6a29d5 . In https://github.com/bazelbuild/bazel/issues/6316#issuecomment-482474265, @iirina briefly touched on instructions for compiling these binaries locally and then using `bazel --distdir` when running on a networkless CI node.

**Comment by iirina** [comment]
I opened #8406 to add a platform-independent java_tools release, which will fix this issue.

As a temp hack you can also try using `--define EXECUTOR=remote` when running bazel. This will trigger by default compiling ijar and singlejar instead of using the pre-built binaries. However, I'm not sure if there are any side effects.
