### ISSUE TITLE
Stop patching Crosstool features from CppActionConfig

### ISSUE THREAD

**Issue by oquenchil** [bazelbuild/bazel#8303]
No features should be patched from CppActionConfig. 

cc_toolchain_config.bzl.tpl should work on its own with all features declared.

**Comment by oquenchil** [comment]
Still need to remove patching action configs and features that are added last to the crosstool

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
