### ISSUE TITLE
Print a description of what environmental differences forced a rebuild.

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/bazel#8306]
### Description of the problem / feature request:

Diagnosing differences in context between two invocations of bazel in the same workspace (classically, the CLI and inside an IDE) is very difficult. It would be vastly easier to normalize environments if Bazel would articulate the elements of the environment which the new invocation sees as different from the prior one.

**Comment by hlopko** [comment]
Have you tried to use [`--explain`](https://docs.bazel.build/versions/master/command-line-reference.html#flag--explain)? What information do you miss there?

**Comment by janakdr** [comment]
Not enough in this bug to act on. Bazel reports when it discards its analysis cache, not clear what other environmental differences are important without more information.
