### ISSUE TITLE
bazel test fails with current_java_* not declared in package tools/jdk

### ISSUE THREAD

**Issue by samikama** [bazelbuild/bazel#8309]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

running bazel test fails with 
`.../external/bazel_tools/tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator/BUILD:3:1: every rule of type java_import implicitly depends upon the target '@bazel_tools//tools/jdk:current_host_java_runtime', but this target could not be found because of: no such target '@bazel_tools//tools/jdk:current_host_java_runtime': target 'current_host_java_runtime' not declared in package 'tools/jdk' defined by /ssdscratch/.cache/bazel/_bazel_skama/bcb472c9eb95a299b283d265489f564f/external/bazel_tools/tools/jdk/BUILD`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Checkout tensorflow, configure and run `bazel test  //tensorflow/core/...`

### What operating system are you running Bazel on?

ubuntu 18.04

### What's the output of `bazel info release`?

INFO: Invocation ID: 600b8950-ce85-4ce1-855a-f7dd1d47b242
release 0.24.1- (@non-git)
similarly fails with 0.25.2 but with java exceptions 
### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

download bazel-0.24.1-dist.zip from github and run compile.sh

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

There are similar threads from 2015 issues but these are supposed to be solved by now.

>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

`
ERROR: /bcb472c9eb95a299b283d265489f564f/external/bazel_tools/tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator/BUILD:3:1: every rule of type java_import implicitly depends upon the target '@bazel_tools//tools/jdk:current_java_toolchain', but this target could not be found because of: no such target '@bazel_tools//tools/jdk:current_java_toolchain': target 'current_java_toolchain' not declared in package 'tools/jdk' defined by /bcb472c9eb95a299b283d265489f564f/external/bazel_tools/tools/jdk/BUILD
ERROR: /bcb472c9eb95a299b283d265489f564f/external/bazel_tools/tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator/BUILD:8:1: every rule of type java_binary implicitly depends upon the target '@bazel_tools//tools/jdk:current_java_toolchain', but this target could not be found because of: no such target '@bazel_tools//tools/jdk:current_java_toolchain': target 'current_java_toolchain' not declared in package 'tools/jdk' defined by /bcb472c9eb95a299b283d265489f564f/external/bazel_tools/tools/jdk/BUILD
ERROR: /bcb472c9eb95a299b283d265489f564f/external/bazel_tools/tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator/BUILD:8:1: every rule of type java_binary implicitly depends upon the target '@bazel_tools//tools/jdk:current_host_java_runtime', but this target could not be found because of: no such target '@bazel_tools//tools/jdk:current_host_java_runtime': target 'current_host_java_runtime' not declared in package 'tools/jdk' defined by /bcb472c9eb95a299b283d265489f564f/external/bazel_tools/tools/jdk/BUILD
ERROR: /bcb472c9eb95a299b283d265489f564f/external/bazel_tools/tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator/BUILD:8:1: every rule of type java_binary implicitly depends upon the target '@bazel_tools//tools/jdk:current_java_runtime', but this target could not be found because of: no such target '@bazel_tools//tools/jdk:current_java_runtime': target 'current_java_runtime' not declared in package 'tools/jdk' defined by /bcb472c9eb95a299b283d265489f564f/external/bazel_tools/tools/jdk/BUILD
ERROR: /bcb472c9eb95a299b283d265489f564f/external/bazel_tools/tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator/BUILD:8:1: every rule of type java_binary implicitly depends upon the target '@bazel_tools//tools/jdk:JacocoCoverageRunner', but this target could not be found because of: no such target '@bazel_tools//tools/jdk:JacocoCoverageRunner': target 'JacocoCoverageRunner' not declared in package 'tools/jdk' defined by /bcb472c9eb95a299b283d265489f564f/external/bazel_tools/tools/jdk/BUILD
ERROR: Analysis of target '//tensorflow/core/kernels:non_max_suppression_op_test' failed; build aborted: Analysis failed
`

**Comment by Ivy147** [comment]
I got same problem ，have you solved it?

**Comment by comius** [comment]
Closing this, we are testing daily if tensorflow builds with Bazel.
