### ISSUE TITLE
Go rules: support cgo

### ISSUE THREAD

**Issue by jirkadanek** [bazelbuild/bazel#831]
My Go package has Go files and C files. Nowadays I compile the C files with a Makefile to get a static library (.a on Linux) and then link it in Go with `// #cgo LDFLAGS: ${SRCDIR}/path/to/lib.a`

I'd like to be able to move all of my build to Bazel, but since cgo is not supported at all, I cannot.

**Comment by damienmg** [comment]
This was completed by bazelbuild/rules_go#10
