### ISSUE TITLE
Windows: BAZEL_* envvars should support quotes

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#8310]
### Description of the problem / feature request:

Allow `BAZEL_VC` and other `BAZEL_*` envvars to have quotes in them.

Quotes are never allows in Windows paths, so the quote cannot be part of the path, so de-quoting is safe.

Quotes appear when using TAB-completion in cmd.exe, as one sets the envvar. A tab-completion sequence typically looks like:

1. `C:\>set BAZEL_VC=C:\Progra<TAB><TAB>`
1. `C:\>set BAZEL_VC="C:\Program Files (x86)"`
1. `C:\>set BAZEL_VC="C:\Program Files (x86)"\Micros<TAB>...<TAB>`
1. `C:\>set BAZEL_VC="C:\Program Files (x86)\Microsoft Visual Studio 14.0"`
1. `C:\>set BAZEL_VC="C:\Program Files (x86)\Microsoft Visual Studio 14.0"\V<TAB>`
1. `C:\>set BAZEL_VC="C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"<ENTER>`

The shell preserves these quotes so they become part of the envvar value, unless I manually delete them, which is annoying. Bazel could do this itself.

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

0.25.0

**Comment by laszlocsomor** [comment]
@meteorcloudy : do you have time to fix this or shall I?

**Comment by meteorcloudy** [comment]
Can you fix this? Thanks!

**Comment by laszlocsomor** [comment]
Will do, thanks!
