### ISSUE TITLE
Message "a canonical reproducible form can be obtained"

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#8315]
When building rules_k8s with Bazel 0.25.2, I get these messages:

```
DEBUG: Rule 'io_bazel_rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1555445174 -0400"
DEBUG: Rule 'io_bazel_rules_jsonnet' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556260764 +0200"
DEBUG: Rule 'subpar' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1551997562 -0500"
```

It's unclear to me what it means, and whether I should care about the messages.

**Comment by aehlig** [comment]
That seems like a duplicate of #8222 where the request was to [keep the message as is](https://github.com/bazelbuild/bazel/issues/8222#issuecomment-489205142).

**Comment by laurentlb** [comment]
It looks like your commit adds the location. That's already better.
